### PR TITLE
cherrypick-1.1: sqlccl: de-flake TestLoadCSVUniqueDuplicate, TestLoadCSVPrimaryDuplicate

### LINKED ISSUE #18343: teamcity: failed tests on release-1.1: testrace/TestLoadCSVPrimaryDuplicate
The following tests appear to have failed:

[#346891](https://teamcity.cockroachdb.com/viewLog.html?buildId=346891):

```
--- FAIL: testrace/TestLoadCSVPrimaryDuplicate (0.110s)
csv_test.go:196: unexpected error: no files in backup
------- Stdout: -------
I170907 20:08:19.509064 125205 storage/engine/rocksdb.go:411  opening rocksdb instance at "/go/src/github.com/cockroachdb/cockroach/artifacts/TestLoadCSVPrimaryDuplicate696536409/cockroach-csv-rocksdb628343524"
I170907 20:08:19.610640 125205 storage/engine/rocksdb.go:526  closing rocksdb instance at "/go/src/github.com/cockroachdb/cockroach/artifacts/TestLoadCSVPrimaryDuplicate696536409/cockroach-csv-rocksdb628343524\n
```
Please assign, take a look and update the issue accordingly.

### LINKED ISSUE #18359: ccl/sqlccl: TestLoadCSVPrimaryDuplicate failed under stress
SHA: https://github.com/cockroachdb/cockroach/commits/6adf8f17160d64334b08120ce8b232173f0efaf1

Parameters:
```
TAGS=
GOFLAGS=
```

Stress build found a failed test: https://teamcity.cockroachdb.com/viewLog.html?buildId=347213&tab=buildLog

```
I170908 06:25:32.645579 116269 storage/engine/rocksdb.go:411  opening rocksdb instance at "/go/src/github.com/cockroachdb/cockroach/artifacts/TestLoadCSVPrimaryDuplicate191228498/cockroach-csv-rocksdb142764425"
I170908 06:25:32.729710 116269 storage/engine/rocksdb.go:526  closing rocksdb instance at "/go/src/github.com/cockroachdb/cockroach/artifacts/TestLoadCSVPrimaryDuplicate191228498/cockroach-csv-rocksdb142764425"
	csv_test.go:196: unexpected error: no files in backup
```

### LINKED ISSUE #18388: teamcity: failed tests on master: testrace/TestLoadCSVPrimaryDuplicate, testrace/TestLogic, testrace/TestLogic/distsql, testrace/TestLogic/distsql/alter_table
The following tests appear to have failed:

[#348038](https://teamcity.cockroachdb.com/viewLog.html?buildId=348038):

```
--- FAIL: testrace/TestLoadCSVPrimaryDuplicate (0.090s)
csv_test.go:196: unexpected error: no files in backup
------- Stdout: -------
I170909 02:36:06.122648 128004 storage/engine/rocksdb.go:411  opening rocksdb instance at "/go/src/github.com/cockroachdb/cockroach/artifacts/TestLoadCSVPrimaryDuplicate772886832/cockroach-csv-rocksdb107932879"
I170909 02:36:06.204041 128004 storage/engine/rocksdb.go:526  closing rocksdb instance at "/go/src/github.com/cockroachdb/cockroach/artifacts/TestLoadCSVPrimaryDuplicate772886832/cockroach-csv-rocksdb107932879\n--- FAIL: testrace/TestLogic (591.250s)
<autogenerated>:10: test logs captured to: /go/src/github.com/cockroachdb/cockroach/artifacts/logTestLogic356759421
<autogenerated>:9: use -show-logs to present logs inline
--- FAIL: testrace/TestLogic/distsql (2.280s)
null
--- FAIL: testrace/TestLogic/distsql/alter_table (176.170s)
logic_test.go:1770: 
	testdata/logic_test/alter_table:506: 
	expected:
	    2 42
	    3 10
	    5 NULL
	    
	but found (query options: "rowsort" -> ignore the following ordering of rows) :
	
logic_test.go:1803: testdata/logic_test/alter_table:513: too many errors encountered, skipping the rest of the input

```
Please assign, take a look and update the issue accordingly.

### LINKED ISSUE #18389: teamcity: failed tests on master: testrace/TestLoadCSVUniqueDuplicate
The following tests appear to have failed:

[#348047](https://teamcity.cockroachdb.com/viewLog.html?buildId=348047):

```
--- FAIL: testrace/TestLoadCSVUniqueDuplicate (0.120s)
csv_test.go:157: unexpected error: no files in backup
------- Stdout: -------
I170909 04:15:27.712609 128645 storage/engine/rocksdb.go:411  opening rocksdb instance at "/go/src/github.com/cockroachdb/cockroach/artifacts/TestLoadCSVUniqueDuplicate380480018/cockroach-csv-rocksdb652767305"
I170909 04:15:27.810228 128645 storage/engine/rocksdb.go:526  closing rocksdb instance at "/go/src/github.com/cockroachdb/cockroach/artifacts/TestLoadCSVUniqueDuplicate380480018/cockroach-csv-rocksdb652767305\n
```
Please assign, take a look and update the issue accordingly.

### PR DESCRIPTION
**Pull request by tbg**
See #17336 which also tracks refactoring that allows testing the originally
desired error.

Fixes #18343.
Fixes #18359.
Fixes #18388.
Fixes #18389.

cc @cockroachdb/release

### CODE REVIEW

File: pkg/ccl/sqlccl/csv.go [hunk 1]
```diff
@@ -182,6 +182,11 @@ func doLocalCSVTransform(
 	})
 	group.Go(func() error {
 		defer close(contentCh)
+		// TODO(mjibson): this error may be swalloed if the goroutine below returns first
```
Comment (benesch) [inline pkg/ccl/sqlccl/csv.go]: nit: "swalloed"

**Review by benesch — APPROVED** [review]

File: pkg/ccl/sqlccl/csv.go (hunk 1 above)
Comment (benesch) [reply pkg/ccl/sqlccl/csv.go]: (I realize this is on master too; feel free to ignore.)

**Review by madelynnblue — APPROVED** [review]
