### PR TITLE
sql: fix `SHOW COMPLETIONS` length check panic

### LINKED ISSUE #84153: sql: v22.1.2: index out of range with SHOW COMPLETIONS
This issue was autofiled by Sentry. It represents a crash or reported error on a live cluster with telemetry enabled.

Sentry link: https://sentry.io/organizations/cockroach-labs/issues/3414516914/?referrer=webhooks_plugin

Panic message:

>conn_executor.go:746: runtime error: index out of range [3] with length 3
(1) attached stack trace
  -- stack trace:
  | github.com/cockroachdb/cockroach/pkg/sql.(*Server).ServeConn.func1
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:746
  | [...repeated from below...]
Wraps: (2) while executing: SHOW COMPLETIONS AT OFFSET 4 FOR '_'
Wraps: (3) attached stack trace
  -- stack trace:
  | github.com/cockroachdb/cockroach/pkg/sql.(*Server).ServeConn.func1
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:746
  | runtime.gopanic
  | 	GOROOT/src/runtime/panic.go:1038
  | runtime.goPanicIndex
  | 	GOROOT/src/runtime/panic.go:90
  | github.com/cockroachdb/cockroach/pkg/sql/delegate.RunShowCompletions
  | 	github.com/cockroachdb/cockroach/pkg/sql/delegate/show_completions.go:69
  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).runShowCompletions
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:1875
  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).runObserverStatement
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:1737
  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execStmt
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:103
  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execCmd.func1
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:1874
  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execCmd
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:1878
  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).run
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:1800
  | github.com/cockroachdb/cockroach/pkg/sql.(*Server).ServeConn
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:748
  | github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*conn).processCommandsAsync.func1
  | 	github.com/cockroachdb/cockroach/pkg/sql/pgwire/conn.go:724
  | runtime.goexit
  | 	GOROOT/src/runtime/asm_amd64.s:1581
Wraps: (4) runtime error: index out of range [3] with length 3
Error types: (1) *withstack.withStack (2) *safedetails.withSafeDetails (3) *withstack.withStack (4) runtime.boundsError
-- report composition:
runtime.boundsError
conn_executor.go:746: *withstack.withStack (top exception)
*safedetails.withSafeDetails: while executing: SHOW COMPLETIONS AT OFFSET 4 FOR '_'
conn_executor.go:746: *withstack.withStack (1)
(check the extra data payloads)

<details>
<summary>Stacktrace (expand for inline code snippets):</summary>

https://github.com/cockroachdb/cockroach/blob/fc456a26830067b6dfbb8cd87e093a28d9b833d1/pkg/sql/conn_executor.go#L745-L747 in pkg/sql.(*Server).ServeConn.func1
GOROOT/src/runtime/panic.go#L1037-L1039 in runtime.gopanic
GOROOT/src/runtime/panic.go#L89-L91 in runtime.goPanicIndex
https://github.com/cockroachdb/cockroach/blob/fc456a26830067b6dfbb8cd87e093a28d9b833d1/pkg/sql/delegate/show_completions.go#L68-L70 in pkg/sql/delegate.RunShowCompletions
https://github.com/cockroachdb/cockroach/blob/fc456a26830067b6dfbb8cd87e093a28d9b833d1/pkg/sql/conn_executor_exec.go#L1874-L1876 in pkg/sql.(*connExecutor).runShowCompletions
https://github.com/cockroachdb/cockroach/blob/fc456a26830067b6dfbb8cd87e093a28d9b833d1/pkg/sql/conn_executor_exec.go#L1736-L1738 in pkg/sql.(*connExecutor).runObserverStatement
https://github.com/cockroachdb/cockroach/blob/fc456a26830067b6dfbb8cd87e093a28d9b833d1/pkg/sql/conn_executor_exec.go#L102-L104 in pkg/sql.(*connExecutor).execStmt
https://github.com/cockroachdb/cockroach/blob/fc456a26830067b6dfbb8cd87e093a28d9b833d1/pkg/sql/conn_executor.go#L1873-L1875 in pkg/sql.(*connExecutor).execCmd.func1
https://github.com/cockroachdb/cockroach/blob/fc456a26830067b6dfbb8cd87e093a28d9b833d1/pkg/sql/conn_executor.go#L1877-L1879 in pkg/sql.(*connExecutor).execCmd
https://github.com/cockroachdb/cockroach/blob/fc456a26830067b6dfbb8cd87e093a28d9b833d1/pkg/sql/conn_executor.go#L1799-L1801 in pkg/sql.(*connExecutor).run
https://github.com/cockroachdb/cockroach/blob/fc456a26830067b6dfbb8cd87e093a28d9b833d1/pkg/sql/conn_executor.go#L747-L749 in pkg/sql.(*Server).ServeConn
https://github.com/cockroachdb/cockroach/blob/fc456a26830067b6dfbb8cd87e093a28d9b833d1/pkg/sql/pgwire/conn.go#L723-L725 in pkg/sql/pgwire.(*conn).processCommandsAsync.func1
GOROOT/src/runtime/asm_amd64.s#L1580-L1582 in runtime.goexit
</details>

```
pkg/sql/conn_executor.go in pkg/sql.(*Server).ServeConn.func1 at line 746
GOROOT/src/runtime/panic.go in runtime.gopanic at line 1038
GOROOT/src/runtime/panic.go in runtime.goPanicIndex at line 90
pkg/sql/delegate/show_completions.go in pkg/sql/delegate.RunShowCompletions at line 69
pkg/sql/conn_executor_exec.go in pkg/sql.(*connExecutor).runShowCompletions at line 1875
pkg/sql/conn_executor_exec.go in pkg/sql.(*connExecutor).runObserverStatement at line 1737
pkg/sql/conn_executor_exec.go in pkg/sql.(*connExecutor).execStmt at line 103
pkg/sql/conn_executor.go in pkg/sql.(*connExecutor).execCmd.func1 at line 1874
pkg/sql/conn_executor.go in pkg/sql.(*connExecutor).execCmd at line 1878
pkg/sql/conn_executor.go in pkg/sql.(*connExecutor).run at line 1800
pkg/sql/conn_executor.go in pkg/sql.(*Server).ServeConn at line 748
pkg/sql/pgwire/conn.go in pkg/sql/pgwire.(*conn).processCommandsAsync.func1 at line 724
GOROOT/src/runtime/asm_amd64.s in runtime.goexit at line 1581
```

| Tag | Value |
|---|---|
| Cockroach Release | `v22.1.2` |
| Cockroach SHA: | fc456a26830067b6dfbb8cd87e093a28d9b833d1 |
| Platform | linux amd64 |
| Distribution | CCL |
| Environment | v22.1.2 |
| Command | server |
| Go Version | ``|
| # of CPUs ||
| # of Goroutines ||

Jira issue: CRDB-17496
Epic CRDB-14049

### PR DESCRIPTION
**Pull request by e-mbrown**
fixes #84153

In cases where the offset was larger than the rune length of statements with special 
characters, `SHOW COMPLETIONS` would return a panic. We now apply the offset on a byte slice before casting to a rune to fix that issue.

Release justification: Bug fix for SHOW COMPLETIONS

Release note: None

### CODE REVIEW

File: pkg/sql/delegate/show_completions.go [hunk 1]
```diff
@@ -66,7 +66,8 @@ func RunShowCompletions(stmt string, offset int) ([]string, error) {
 	// Ie "SELECT ", will only return one token being "SELECT".
 	// If we're at the whitespace, we do not want to return completion
 	// recommendations for "SELECT".
-	if unicode.IsSpace([]rune(stmt)[offset-1]) {
+	b := []byte(stmt)
```
Comment (RichardJCai) [inline pkg/sql/delegate/show_completions.go:69]: I think we need to do this before the checks on line 59

**Review by e-mbrown — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/87530)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @RichardJCai)

___
*[`pkg/sql/delegate/show_completions.go` line 69 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/87530#-NBOQ5441jYsKnmUIjcz-r1-69:-NBTdR4e7fQHOxeo-tM3:bb6un1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/37b273b30f0c363e4e295d398848589f8836d9e2/pkg/sql/delegate/show_completions.go#L69)):*
<details><summary><i>Previously, RichardJCai (Richard Cai) wrote…</i></summary><blockquote>

I think we need to do this before the checks on line 59
</blockquote></details>

Done

**Review by rafiss — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/87530)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @e-mbrown and @RichardJCai)

___
*[`pkg/sql/delegate/show_completions.go` line 60 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/87530#-NBTmdY--nPHWZvkhJtq:-NBTmdY--nPHWZvkhJtr:bxzh44c) ([raw file](https://github.com/cockroachdb/cockroach/blob/61a68a3ab6414f5c5806d7d590f4c1f9c8884154/pkg/sql/delegate/show_completions.go#L60)):*
> ```Go
> func RunShowCompletions(stmt string, offset int) ([]string, error) {
> 	b := []byte(stmt)
> 	if offset <= 0 || offset > len(stmt) {
> ```

this should check `len(b)` now, not `len(stmt)` - otherwise there's no reason to create the byte slice before this check.

also, consider using a more descriptive name than `b`

File: pkg/sql/delegate/show_completions_test.go [hunk 2]
```diff
@@ -87,6 +87,16 @@ func TestCompletions(t *testing.T) {
 			expectedCompletions: []string{"SELECT"},
 			offset:              12,
 		},
+		{
+			stmt:                "😋😋😋 😋😋😋",
+			expectedCompletions: []string{},
+			offset:              25,
```
Comment (RichardJCai) [inline pkg/sql/delegate/show_completions_test.go:93]: Can this be updated to use offset 30 such that the test covers the example in the issue description.

**Review by RichardJCai — APPROVED** [review]
LGTM after test is updated

**Review by e-mbrown — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/87530)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @e-mbrown, @rafiss, and @RichardJCai)

___
*[`pkg/sql/delegate/show_completions_test.go` line 93 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/87530#-NBOQ5441jYsKnmUIjd--r3-93:-NBXzzGI4VQ-FBU_cOmf:b-39hx70) ([raw file](https://github.com/cockroachdb/cockroach/blob/97136d7f974ccd9f0319d6fbf31a9c72f2e723c2/pkg/sql/delegate/show_completions_test.go#L93)):*
<details><summary><i>Previously, RichardJCai (Richard Cai) wrote…</i></summary><blockquote>

Can this be updated to use offset 30 such that the test covers the example in the issue description.
</blockquote></details>

Before the fix, this test would pass with an offset of 30. It failed after the offset was changed 25

**Comment by RichardJCai** [comment]
>Before the fix, this test would pass with an offset of 30. It failed after the offset was changed 25

erm, I'm not following, if 25 is out of range wouldn't 30 also be out of range?

**Review by e-mbrown — COMMENTED** [review]
I messed around and for `😋😋😋 😋😋😋` an offset between 7 and 26 causes a panic, anything greater than 26 and the test passes. I did the same for `Jalapeño` and only got a panic with an offset of 9 but not 10. 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/87530#-:-NBYKH4UCwa6Ld9rEo7p:bsczh5p)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @e-mbrown, @rafiss, and @RichardJCai)

**Comment by rafiss** [comment]
> if 25 is out of range wouldn't 30 also be out of range?

it would, but i'm guessing 30 did not panic because it would short-circuit at the `len(stmt)` check.

**Comment by e-mbrown** [comment]
Thanks for all the reviews!

bors r+

**Review by rafiss — APPROVED** [review]

**Comment by rafiss** [comment]
trying again

bors r+
