### PR TITLE
server: Implement 'gossip' endpoint in multitenant setup

### LINKED ISSUE #110022: server: the "gossip" status API endpoint should work with secondary tenants with sufficient capability
Found while investigating #110001.

**Describe the problem**

When `TestStatusGossipJson` in `server/storage_api` is modified to point to a secondary tenant (e.g. via #110008), the test starts failing when accessing the `/_status/gossip` endpoint:

```
    gossip_test.go:36: status: 501 Not Implemented, content-type: application/json, body: {
          "error": "method Gossip not implemented",
          "code": 12,
          "message": "method Gossip not implemented",
          "details": [
          ]
```

**How to reproduce**

from #110008 reset `DefaultTestTenant` in `TestStatusGossipJson`, run the test with a test tenant and observe the failure.

**Expected behavior**

Once the tenant is granted a suitable capability, the endpoint should work properly. It should retrieve the gossip info over the KV tenant connector over the network.

Epic CRDB-38968

Jira issue: CRDB-31227

### PR DESCRIPTION
**Pull request by shaikzakiriitm**
What was there before: previously, gossip endpoint wasn't accessible from secondary tenant why it needed to change: gossip endpoint provides crucial information for debugging and this should be accessible from secondary tenant for troubleshooting issues within gossip protocol of the cluster
What you did about it: To address this, we created gossip endpoint in tenant status server. The implementation uses connector to redirect the call to the system tenant on the requested kv node. Access to this endpoint is guarded by `can_debug_process` capability as this is node's debugging information albeit gossip related one. Updated the gossip status unit test for both system tenant and application tenant.

Epic: CRDB-38968
Fixes: #110022

Release note: None

### CODE REVIEW

File: pkg/server/storage_api/gossip_test.go [hunk 1]
```diff
@@ -7,42 +7,77 @@ package storage_api_test
...
 	"github.com/cockroachdb/cockroach/pkg/testutils/serverutils"
 	"github.com/cockroachdb/cockroach/pkg/util/leaktest"
 	"github.com/cockroachdb/cockroach/pkg/util/log"
+	"github.com/stretchr/testify/require"
 )
 
-// TestStatusGossipJson ensures that the output response for the full gossip
-// info contains the required fields.
-func TestStatusGossipJson(t *testing.T) {
+func TestStatusGossipJsonWithSystemTenant(t *testing.T) {
```
Comment (cthumuluru-crdb) [inline pkg/server/storage_api/gossip_test.go:23]: For test, can you use similar approach as in `pkg/server/storage_api/network_test.go`?

**Review by cthumuluru-crdb — CHANGES_REQUESTED** [review]

**Review by cthumuluru-crdb — CHANGES_REQUESTED** [review]
I left some comments, please take a look. Also, use the commit guidelines from here: https://cockroachlabs.atlassian.net/wiki/spaces/CRDB/pages/73072807/Git+Commit+Messages. I think you also need to title on the commit, not just the PR.

File: pkg/server/status.go [hunk 2]
```diff
@@ -721,6 +721,21 @@ func (s *statusServer) dialNode(
...
 
+// Gossip returns current state of gossip information on the given node
+// which is crucial for monitoring and debugging the gossip protocol in
+// CockroachDB cluster.
+func (t *statusServer) Gossip(
+	ctx context.Context, req *serverpb.GossipRequest,
+) (*gossip.InfoStatus, error) {
+	ctx = t.AnnotateCtx(ctx)
+
+	if err := t.privilegeChecker.RequireViewClusterMetadataPermission(ctx); err != nil {
```
[the remark this answers is not in the document]
Comment (shubhamdhama) [reply pkg/server/status.go:732]: Not sure, maybe @dhartunian can help with this.

[the remark this answers is not in the document]
Comment (shaikzakiriitm) [reply pkg/server/status.go:732]: IMO looks like both the permissions are apt here. We can either say this (`gossip info`) is debug info or as well say that this is cluster metadata information (and hence the view cluster metadata permission). Any specific reason for inclination towards one over the other?

**Comment by shaikzakiriitm** [comment]
> I left some comments, please take a look. Also, use the commit guidelines from here: https://cockroachlabs.atlassian.net/wiki/spaces/CRDB/pages/73072807/Git+Commit+Messages. I think you also need to title on the commit, not just the PR.

Fixed the commit title.

File: pkg/server/storage_api/gossip_test.go [hunk 3]
```diff
@@ -7,42 +7,75 @@ package storage_api_test
...
+
+	if srv.TenantController().StartedDefaultTestTenant() {
+		// explicitly enabling debug capability for the secondary/application tenant
+		_, err := srv.SystemLayer().SQLConn(t).Exec(
+			`ALTER TENANT [$1] GRANT CAPABILITY can_debug_process=true`,
+			serverutils.TestTenantID().ToUint64(),
+		)
+		require.NoError(t, err)
+		serverutils.WaitForTenantCapabilities(t, srv, serverutils.TestTenantID(),
+			map[tenantcapabilities.ID]string{tenantcapabilities.CanDebugProcess: "true"}, "")
```
Comment (cthumuluru-crdb) [inline pkg/server/storage_api/gossip_test.go:40]: Another source of my confusion is the capability we are setting here is `CanDebugProcess`.

**Review by cthumuluru-crdb — APPROVED** [review]
Besides one comment on the capability we have to use, other changes look good to me. Please wait for the response from David or Steven before committing the changes.

**Review by cthumuluru-crdb — APPROVED** [review]
Besides one comment on the capability we have to use, other changes look good to me. Please wait for the response from David or Steven before committing the changes.

File: pkg/server/status.go (hunk 2 above)
[the remark this answers is not in the document]
Comment (dhartunian) [reply pkg/server/status.go:732]: I think `VIEWCLUSTERMETADATA` is appropriate here. I think `VIEWDEBUG` is meant more for process-level debugging and profiling.

File: pkg/multitenant/tenantcapabilities/capabilities.go [hunk 4]
```diff
@@ -81,7 +81,9 @@ const (
 
 	// CanDebugProcess describes the ability of a tenant to set vmodule on the
 	// process and run pprof profiles and tools. This can reveal information
-	// across tenant boundaries.
+	// across tenant boundaries. This also encompasses tenant's ability to retrieve
```
[the remark this answers is not in the document]
Comment (dhartunian) [reply pkg/multitenant/tenantcapabilities/capabilities.go]: I don't agree. That sentence is meant as an explanation of why profiling is blocked by default not as a statement of what this capability is meant to govern. In some sense many capabilities are about blocking stuff "across tenant boundaries".

Consider using `CanViewNodeInfo` instead. That one is used to gate cluster-wide metadata which I think gossip is part of.

**Review by dhartunian — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/141212)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @cthumuluru-crdb, @kyle-a-wong, @rharding6373, @shaikzakiriitm, @shubhamdhama, and @stevendanna)

**Review by cthumuluru-crdb — APPROVED** [review]
lgtm. Thanks!

File: pkg/server/storage_api/gossip_test.go [hunk 5]
```diff
@@ -7,42 +7,75 @@ package storage_api_test
...
-	// TODO(#110022): grant a special capability to the secondary tenant
-	// before the endpoint can be accessed.
+	srv := serverutils.StartServerOnly(t, base.TestServerArgs{
+		// Note: We're only testing external-process mode because shared service
+		// mode tenants have all capabilities.
+		DefaultTestTenant: base.ExternalTestTenantAlwaysEnabled,
+	})
+	defer srv.Stopper().Stop(context.Background())
+
+	if srv.TenantController().StartedDefaultTestTenant() {
```
Comment (shubhamdhama) [inline pkg/server/storage_api/gossip_test.go:57]: You don't need this line since this test has external process enabled.

File: pkg/server/storage_api/gossip_test.go [hunk 6]
```diff
@@ -7,42 +7,75 @@ package storage_api_test
...
 
-// TestStatusGossipJson ensures that the output response for the full gossip
-// info contains the required fields.
 func TestStatusGossipJson(t *testing.T) {
 	defer leaktest.AfterTest(t)()
 	defer log.Scope(t).Close(t)
 
 	srv := serverutils.StartServerOnly(t, base.TestServerArgs{
-		DefaultTestTenant: base.TestIsForStuffThatShouldWorkWithSecondaryTenantsButDoesntYet(110022),
+		DefaultTestTenant: base.TestTenantProbabilistic,
```
Comment (shubhamdhama) [inline pkg/server/storage_api/gossip_test.go:28]: This would disable testing for single-tenant.

File: pkg/server/storage_api/gossip_test.go [hunk 7]
```diff
@@ -7,42 +7,75 @@ package storage_api_test
...
 	})
 	defer srv.Stopper().Stop(context.Background())
+
+	if srv.TenantController().StartedDefaultTestTenant() {
+		// explicitly enabling debug capability for the secondary/application tenant
```
Comment (shubhamdhama) [inline pkg/server/storage_api/gossip_test.go:33]: nit: "Explicitly enabling `can_view_node_info` capability for the secondary tenant"

File: pkg/server/storage_api/gossip_test.go (hunk 6 above)
Comment (shubhamdhama) [reply pkg/server/storage_api/gossip_test.go]: Whoops, I guess I was wrong here. It was right the first time 😬

**Review by shubhamdhama — APPROVED** [review]
Great work!
LGTM!

small suggestions and don't let it block this PR: you can use this helper now: https://github.com/cockroachdb/cockroach/pull/141490

**Comment by shaikzakiriitm** [comment]
> Great work! LGTM!
> 
> small suggestions and don't let it block this PR: you can use this helper now: #141490

👍 got it. Will raise a followup pr to clean the usage. Thanks!

**Comment by shaikzakiriitm** [comment]
bors r=shubhamdhama,cthumuluru-crdb

**Comment by dhartunian** [comment]
@shaikzakiriitm please squash fixups before merging in the future

**Comment by shaikzakiriitm** [comment]
> @shaikzakiriitm please squash fixups before merging in the future

@dhartunian My bad, squashing the fixup commits really slipped my mind. Thank you for pointing it out, will keep this in my mind from now on. Thanks!
