### PR TITLE
storageparam: do not allow subqueries in storage param clause

### LINKED ISSUE #110629: sql/tests: TestRandomSyntaxSchemaChangeColumn failed
sql/tests.TestRandomSyntaxSchemaChangeColumn [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RandomSyntaxTestsBazel/11770371?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RandomSyntaxTestsBazel/11770371?buildTab=artifacts#/) on master @ [0cde11b885a5e156b970c003505acd081fb4f326](https://github.com/cockroachdb/cockroach/commits/0cde11b885a5e156b970c003505acd081fb4f326):

Random syntax error:

```
    rsg_test.go:887: Crash detected: server panic: pq: internal error: ReturnType called on TypedExpr with empty typeAnnotation. Was the underlying Expr type-checked before asserting a type of TypedExpr?
```
Query:

```
        ALTER TABLE ident.ident SET ( 'string' = EXISTS ( TABLE error ) );
```
<details><summary>Help</summary>
<p>

See also: [How To Investigate a Go Test Failure \(internal\)](https://cockroachlabs.atlassian.net/l/c/HgfXfJgM)
</p>
</details>
<details><summary>Same failure on other branches</summary>
<p>

- #110626 sql/tests: TestRandomSyntaxSchemaChangeColumn failed [C-test-failure O-robot T-sql-foundations branch-release-23.1.11-rc release-blocker]
- #109988 sql/tests: TestRandomSyntaxSchemaChangeColumn failed [C-test-failure O-robot T-sql-foundations branch-release-22.2]
</p>
</details>
/cc @cockroachdb/sql-foundations
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*TestRandomSyntaxSchemaChangeColumn.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)
</sub>

Jira issue: CRDB-31532

### PR DESCRIPTION
**Pull request by rafiss**
This would previously cause an internal error. Now it displays a feature not supported error.

fixes https://github.com/cockroachdb/cockroach/issues/110629
Release note: None

### CODE REVIEW

File: pkg/sql/storageparam/storage_param.go [hunk 1]
```diff
@@ -65,6 +65,9 @@ func Set(
 		// Cast these as strings.
 		expr := paramparse.UnresolvedNameToStrVal(sp.Value)
 
+		defer semaCtx.Properties.Restore(semaCtx.Properties)
```
Comment (ecwall) [inline pkg/sql/storageparam/storage_param.go:68]: Could you add a comment explaining why they are not allowed?

**Review by ecwall — APPROVED** [review]

File: pkg/sql/storageparam/storage_param.go (hunk 1 above)
Comment (rafiss) [reply pkg/sql/storageparam/storage_param.go:70]: added

**Comment by rafiss** [comment]
tftr!

bors r+
