### PR TITLE
changefeedccl: fix PTS test

### LINKED ISSUE #135639: changefeedccl: TestPTSRecordProtectsTargetsAndSystemTables failed
This test failed under `maybe_stressrace` on Bazel Extended CI on #135613. Seems a little weird given we backported the PR protecting the zones table in #130622.

```
=== RUN   TestPTSRecordProtectsTargetsAndSystemTables
    test_log_scope.go:165: test logs captured to: /artifacts/tmp/_tmp/905465f697dc04c39f7d8a82cb057bfe/logTestPTSRecordProtectsTargetsAndSystemTables2369024512
    test_log_scope.go:76: use -show-logs to present logs inline
    protected_timestamps_test.go:500: updating PTS reader cache to 1731962155.517292301,0
    protected_timestamps_test.go:512: enqueuing range 7 for mvccGC
    protected_timestamps_test.go:500: updating PTS reader cache to 1731962158.896807831,0
    protected_timestamps_test.go:512: enqueuing range 9 for mvccGC
    protected_timestamps_test.go:500: updating PTS reader cache to 1731962162.143584093,0
    protected_timestamps_test.go:512: enqueuing range 27 for mvccGC
    protected_timestamps_test.go:500: updating PTS reader cache to 1731962165.419260368,0
    protected_timestamps_test.go:512: enqueuing range 26 for mvccGC
    protected_timestamps_test.go:500: updating PTS reader cache to 1731962168.663082802,0
    protected_timestamps_test.go:512: enqueuing range 8 for mvccGC
    protected_timestamps_test.go:544:
          Error Trace:  pkg/ccl/changefeedccl/protected_timestamps_test.go:544
          Error:        Received unexpected error:
                        batch timestamp 1731962150.678137806,0 must be after replica GC threshold 1731962159.471710070,0 (r9: /Table/{5-6})
          Test:         TestPTSRecordProtectsTargetsAndSystemTables
    panic.go:626: -- test log scope end --
test logs left over in: /artifacts/tmp/_tmp/905465f697dc04c39f7d8a82cb057bfe/logTestPTSRecordProtectsTargetsAndSystemTables2369024512
```

See https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_BazelExtendedCi/17824471?hideProblemsFromDependencies=false&hideTestsFromDependencies=false&expandBuildProblemsSection=true&expandBuildChangesSection=true&expandBuildTestsSection=true

Jira issue: CRDB-44660

### LINKED ISSUE #135805: ccl/changefeedccl: TestPTSRecordProtectsTargetsAndSystemTables failed
ccl/changefeedccl.TestPTSRecordProtectsTargetsAndSystemTables [failed](https://tanzanite.cluster.engflow.com/invocations/default/063875b0-9460-4e91-b3ec-b1d7e00f885c?testReportRun=2&testReportShard=10&testReportAttempt=1#targets-Ly9wa2cvY2NsL2NoYW5nZWZlZWRjY2w6Y2hhbmdlZmVlZGNjbF90ZXN0) on release-24.1.7-rc @ [3613a619e327fb412ac62036ce2c7060c25e48db](https://github.com/cockroachdb/cockroach/commits/3613a619e327fb412ac62036ce2c7060c25e48db):

```
=== RUN   TestPTSRecordProtectsTargetsAndSystemTables
    test_log_scope.go:165: test logs captured to: outputs.zip/logTestPTSRecordProtectsTargetsAndSystemTables2066818542
    test_log_scope.go:76: use -show-logs to present logs inline
    protected_timestamps_test.go:500: updating PTS reader cache to 1732093806.614024818,0
    protected_timestamps_test.go:512: enqueuing range 7 for mvccGC
    protected_timestamps_test.go:500: updating PTS reader cache to 1732093808.766324818,0
    protected_timestamps_test.go:512: enqueuing range 9 for mvccGC
    protected_timestamps_test.go:500: updating PTS reader cache to 1732093811.919775669,0
    protected_timestamps_test.go:512: enqueuing range 27 for mvccGC
    protected_timestamps_test.go:500: updating PTS reader cache to 1732093815.075711779,0
    protected_timestamps_test.go:512: enqueuing range 26 for mvccGC
    protected_timestamps_test.go:540: 
        	Error Trace:	github.com/cockroachdb/cockroach/pkg/ccl/changefeedccl/protected_timestamps_test.go:540
        	Error:      	Received unexpected error:
        	            	batch timestamp 1732093803.017933432,0 must be after replica GC threshold 1732093809.507815991,0
        	Test:       	TestPTSRecordProtectsTargetsAndSystemTables
    panic.go:626: -- test log scope end --
test logs left over in: outputs.zip/logTestPTSRecordProtectsTargetsAndSystemTables2066818542
--- FAIL: TestPTSRecordProtectsTargetsAndSystemTables (18.80s)
```

Parameters:
 - <code>attempt=1</code>
 - <code>deadlock=true</code>
 - <code>run=2</code>
 - <code>shard=10</code>
<details><summary>Help</summary>
<p>

See also: [How To Investigate a Go Test Failure \(internal\)](https://cockroachlabs.atlassian.net/l/c/HgfXfJgM)
</p>
</details>
/cc @cockroachdb/cdc
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*TestPTSRecordProtectsTargetsAndSystemTables.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/bazci/githubpost/issues)

</sub>

Jira issue: CRDB-44724

### LINKED ISSUE #136396: ccl/changefeedccl: TestPTSRecordProtectsTargetsAndSystemTables failed
ccl/changefeedccl.TestPTSRecordProtectsTargetsAndSystemTables [failed](https://tanzanite.cluster.engflow.com/invocations/default/006f0cf0-8fad-47cf-b727-503c49077adc?testReportRun=2&testReportShard=13&testReportAttempt=1#targets-Ly9wa2cvY2NsL2NoYW5nZWZlZWRjY2w6Y2hhbmdlZmVlZGNjbF90ZXN0) on release-24.2.6-rc @ [9dab6cb9f71f21ef1e9c98640193035783ba9a4e](https://github.com/cockroachdb/cockroach/commits/9dab6cb9f71f21ef1e9c98640193035783ba9a4e):

```
=== RUN   TestPTSRecordProtectsTargetsAndSystemTables
    test_log_scope.go:165: test logs captured to: outputs.zip/logTestPTSRecordProtectsTargetsAndSystemTables2336339089
    test_log_scope.go:76: use -show-logs to present logs inline
    protected_timestamps_test.go:500: updating PTS reader cache to 1732869843.834437177,0
    protected_timestamps_test.go:512: enqueuing range 7 for mvccGC
    protected_timestamps_test.go:500: updating PTS reader cache to 1732869848.026306868,0
    protected_timestamps_test.go:512: enqueuing range 9 for mvccGC
    protected_timestamps_test.go:500: updating PTS reader cache to 1732869851.231835032,0
    protected_timestamps_test.go:512: enqueuing range 27 for mvccGC
    protected_timestamps_test.go:500: updating PTS reader cache to 1732869853.420100374,0
    protected_timestamps_test.go:512: enqueuing range 26 for mvccGC
    protected_timestamps_test.go:500: updating PTS reader cache to 1732869856.606599294,0
    protected_timestamps_test.go:512: enqueuing range 8 for mvccGC
    protected_timestamps_test.go:544: 
        	Error Trace:	github.com/cockroachdb/cockroach/pkg/ccl/changefeedccl/protected_timestamps_test.go:544
        	Error:      	Received unexpected error:
        	            	batch timestamp 1732869838.353478426,0 must be after replica GC threshold 1732869848.105407236,0 (r9: /Table/{5-6})
        	Test:       	TestPTSRecordProtectsTargetsAndSystemTables
    panic.go:626: -- test log scope end --
test logs left over in: outputs.zip/logTestPTSRecordProtectsTargetsAndSystemTables2336339089
--- FAIL: TestPTSRecordProtectsTargetsAndSystemTables (27.79s)
```

Parameters:
 - <code>attempt=1</code>
 - <code>deadlock=true</code>
 - <code>run=2</code>
 - <code>shard=13</code>
<details><summary>Help</summary>
<p>

See also: [How To Investigate a Go Test Failure \(internal\)](https://cockroachlabs.atlassian.net/l/c/HgfXfJgM)
</p>
</details>
<details><summary>Same failure on other branches</summary>
<p>

- #135805 ccl/changefeedccl: TestPTSRecordProtectsTargetsAndSystemTables failed [A-cdc C-test-failure O-robot P-2 T-cdc release-blocker]
</p>
</details>
/cc @cockroachdb/cdc
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*TestPTSRecordProtectsTargetsAndSystemTables.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/bazci/githubpost/issues)

</sub>

Jira issue: CRDB-45016

### LINKED ISSUE #137505: ccl/changefeedccl: TestPTSRecordProtectsTargetsAndSystemTables failed
ccl/changefeedccl.TestPTSRecordProtectsTargetsAndSystemTables [failed](https://tanzanite.cluster.engflow.com/invocations/default/873efd91-f6eb-4802-9407-a9401a840cd0?testReportRun=3&testReportShard=12&testReportAttempt=1#targets-Ly9wa2cvY2NsL2NoYW5nZWZlZWRjY2w6Y2hhbmdlZmVlZGNjbF90ZXN0) on release-24.1.8-rc @ [05e5df3c04a577643a59b78f574b0084832e67e6](https://github.com/cockroachdb/cockroach/commits/05e5df3c04a577643a59b78f574b0084832e67e6):

```
=== RUN   TestPTSRecordProtectsTargetsAndSystemTables
    test_log_scope.go:165: test logs captured to: outputs.zip/logTestPTSRecordProtectsTargetsAndSystemTables2146102615
    test_log_scope.go:76: use -show-logs to present logs inline
    protected_timestamps_test.go:500: updating PTS reader cache to 1734253368.798283605,0
    protected_timestamps_test.go:512: enqueuing range 7 for mvccGC
    protected_timestamps_test.go:500: updating PTS reader cache to 1734253370.953435469,0
    protected_timestamps_test.go:512: enqueuing range 9 for mvccGC
    protected_timestamps_test.go:500: updating PTS reader cache to 1734253374.122388057,0
    protected_timestamps_test.go:512: enqueuing range 27 for mvccGC
    protected_timestamps_test.go:500: updating PTS reader cache to 1734253376.312431448,0
    protected_timestamps_test.go:512: enqueuing range 26 for mvccGC
    protected_timestamps_test.go:500: updating PTS reader cache to 1734253379.470142802,0
    protected_timestamps_test.go:512: enqueuing range 8 for mvccGC
    protected_timestamps_test.go:544: 
        	Error Trace:	github.com/cockroachdb/cockroach/pkg/ccl/changefeedccl/protected_timestamps_test.go:544
        	Error:      	Received unexpected error:
        	            	batch timestamp 1734253364.795712343,0 must be after replica GC threshold 1734253370.998554691,0 (r9: /Table/{5-6})
        	Test:       	TestPTSRecordProtectsTargetsAndSystemTables
    panic.go:626: -- test log scope end --
test logs left over in: outputs.zip/logTestPTSRecordProtectsTargetsAndSystemTables2146102615
--- FAIL: TestPTSRecordProtectsTargetsAndSystemTables (21.62s)
```

Parameters:
 - <code>attempt=1</code>
 - <code>deadlock=true</code>
 - <code>run=3</code>
 - <code>shard=12</code>
<details><summary>Help</summary>
<p>

See also: [How To Investigate a Go Test Failure \(internal\)](https://cockroachlabs.atlassian.net/l/c/HgfXfJgM)
</p>
</details>
<details><summary>Same failure on other branches</summary>
<p>

- #136396 ccl/changefeedccl: TestPTSRecordProtectsTargetsAndSystemTables failed [A-cdc C-test-failure O-robot P-3 T-cdc branch-release-24.2.6-rc release-blocker]
- #135805 ccl/changefeedccl: TestPTSRecordProtectsTargetsAndSystemTables failed [A-cdc C-test-failure O-robot P-2 T-cdc release-blocker]
</p>
</details>
/cc @cockroachdb/cdc
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*TestPTSRecordProtectsTargetsAndSystemTables.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/bazci/githubpost/issues)

</sub>

Jira issue: CRDB-45623

### LINKED ISSUE #137885: ccl/changefeedccl: TestPTSRecordProtectsTargetsAndSystemTables failed
ccl/changefeedccl.TestPTSRecordProtectsTargetsAndSystemTables [failed](https://tanzanite.cluster.engflow.com/invocations/default/fe1ae78f-7357-4746-8a4f-d763a7c4f12b?testReportRun=1&testReportShard=12&testReportAttempt=1#targets-Ly9wa2cvY2NsL2NoYW5nZWZlZWRjY2w6Y2hhbmdlZmVlZGNjbF90ZXN0) on release-24.1 @ [a80ff6a3b1289d382029e628759b1e50271b6069](https://github.com/cockroachdb/cockroach/commits/a80ff6a3b1289d382029e628759b1e50271b6069):

```
=== RUN   TestPTSRecordProtectsTargetsAndSystemTables
    test_log_scope.go:165: test logs captured to: outputs.zip/logTestPTSRecordProtectsTargetsAndSystemTables2939620825
    test_log_scope.go:76: use -show-logs to present logs inline
    protected_timestamps_test.go:500: updating PTS reader cache to 1734771697.946733163,0
    protected_timestamps_test.go:512: enqueuing range 7 for mvccGC
    protected_timestamps_test.go:500: updating PTS reader cache to 1734771702.105240735,0
    protected_timestamps_test.go:512: enqueuing range 9 for mvccGC
    protected_timestamps_test.go:500: updating PTS reader cache to 1734771705.258120594,0
    protected_timestamps_test.go:512: enqueuing range 27 for mvccGC
    protected_timestamps_test.go:500: updating PTS reader cache to 1734771708.415709837,0
    protected_timestamps_test.go:512: enqueuing range 26 for mvccGC
    protected_timestamps_test.go:500: updating PTS reader cache to 1734771711.572794203,0
    protected_timestamps_test.go:512: enqueuing range 8 for mvccGC
    protected_timestamps_test.go:544: 
        	Error Trace:	github.com/cockroachdb/cockroach/pkg/ccl/changefeedccl/protected_timestamps_test.go:544
        	Error:      	Received unexpected error:
        	            	batch timestamp 1734771693.726253348,0 must be after replica GC threshold 1734771702.721377239,0 (r9: /Table/{5-6})
        	Test:       	TestPTSRecordProtectsTargetsAndSystemTables
    panic.go:626: -- test log scope end --
test logs left over in: outputs.zip/logTestPTSRecordProtectsTargetsAndSystemTables2939620825
--- FAIL: TestPTSRecordProtectsTargetsAndSystemTables (25.08s)
```

Parameters:
 - <code>attempt=1</code>
 - <code>deadlock=true</code>
 - <code>run=1</code>
 - <code>shard=12</code>
<details><summary>Help</summary>
<p>

See also: [How To Investigate a Go Test Failure \(internal\)](https://cockroachlabs.atlassian.net/l/c/HgfXfJgM)
</p>
</details>
<details><summary>Same failure on other branches</summary>
<p>

- #137505 ccl/changefeedccl: TestPTSRecordProtectsTargetsAndSystemTables failed [A-cdc C-test-failure O-robot P-2 T-cdc X-duplicate branch-release-24.1.8-rc]
- #136396 ccl/changefeedccl: TestPTSRecordProtectsTargetsAndSystemTables failed [A-cdc C-test-failure O-robot P-3 T-cdc branch-release-24.2.6-rc]
- #135805 ccl/changefeedccl: TestPTSRecordProtectsTargetsAndSystemTables failed [A-cdc C-test-failure O-robot P-2 T-cdc]
</p>
</details>
/cc @cockroachdb/cdc
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*TestPTSRecordProtectsTargetsAndSystemTables.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/bazci/githubpost/issues)

</sub>

Jira issue: CRDB-45789

### LINKED ISSUE #138066: ccl/changefeedccl: TestPTSRecordProtectsTargetsAndSystemTables failed
ccl/changefeedccl.TestPTSRecordProtectsTargetsAndSystemTables [failed](https://tanzanite.cluster.engflow.com/invocations/default/b071f0ef-ab56-4ea1-8a66-d34f2c9e4ceb?testReportRun=3&testReportShard=16&testReportAttempt=1#targets-Ly9wa2cvY2NsL2NoYW5nZWZlZWRjY2w6Y2hhbmdlZmVlZGNjbF90ZXN0) on release-24.3.3-rc @ [7dab2bb943152658ca94aeae83c450742ec361a5](https://github.com/cockroachdb/cockroach/commits/7dab2bb943152658ca94aeae83c450742ec361a5):

```
=== RUN   TestPTSRecordProtectsTargetsAndSystemTables
    test_log_scope.go:165: test logs captured to: outputs.zip/logTestPTSRecordProtectsTargetsAndSystemTables1695693227
    test_log_scope.go:76: use -show-logs to present logs inline
    protected_timestamps_test.go:500: updating PTS reader cache to 1735465165.707160503,0
    protected_timestamps_test.go:512: enqueuing range 7 for mvccGC
    protected_timestamps_test.go:500: updating PTS reader cache to 1735465168.909630025,0
    protected_timestamps_test.go:512: enqueuing range 9 for mvccGC
    protected_timestamps_test.go:500: updating PTS reader cache to 1735465172.099638197,0
    protected_timestamps_test.go:512: enqueuing range 27 for mvccGC
    protected_timestamps_test.go:500: updating PTS reader cache to 1735465175.304703659,0
    protected_timestamps_test.go:512: enqueuing range 26 for mvccGC
    protected_timestamps_test.go:500: updating PTS reader cache to 1735465177.532670544,0
    protected_timestamps_test.go:512: enqueuing range 8 for mvccGC
    protected_timestamps_test.go:544: 
        	Error Trace:	pkg/ccl/changefeedccl/protected_timestamps_test.go:544
        	Error:      	Received unexpected error:
        	            	batch timestamp 1735465159.945363138,0 must be after replica GC threshold 1735465169.194012228,0 (r9: /Table/{5-6})
        	Test:       	TestPTSRecordProtectsTargetsAndSystemTables
    panic.go:626: -- test log scope end --
test logs left over in: outputs.zip/logTestPTSRecordProtectsTargetsAndSystemTables1695693227
--- FAIL: TestPTSRecordProtectsTargetsAndSystemTables (27.55s)
```

Parameters:
 - <code>attempt=1</code>
 - <code>deadlock=true</code>
 - <code>run=3</code>
 - <code>shard=16</code>
<details><summary>Help</summary>
<p>

See also: [How To Investigate a Go Test Failure \(internal\)](https://cockroachlabs.atlassian.net/l/c/HgfXfJgM)
</p>
</details>
<details><summary>Same failure on other branches</summary>
<p>

- #137885 ccl/changefeedccl: TestPTSRecordProtectsTargetsAndSystemTables failed [A-cdc C-test-failure O-robot T-cdc X-duplicate branch-release-24.1]
- #137505 ccl/changefeedccl: TestPTSRecordProtectsTargetsAndSystemTables failed [A-cdc C-test-failure O-robot P-2 T-cdc X-duplicate branch-release-24.1.8-rc]
- #136396 ccl/changefeedccl: TestPTSRecordProtectsTargetsAndSystemTables failed [A-cdc C-test-failure O-robot P-3 T-cdc branch-release-24.2.6-rc]
- #135805 ccl/changefeedccl: TestPTSRecordProtectsTargetsAndSystemTables failed [A-cdc C-test-failure O-robot P-2 T-cdc]
</p>
</details>
/cc @cockroachdb/cdc
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*TestPTSRecordProtectsTargetsAndSystemTables.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/bazci/githubpost/issues)

</sub>

Jira issue: CRDB-45879

### PR DESCRIPTION
**Pull request by asg0451**
Fix failing TestPTSRecordProtectsTargetsAndSystemTables test

Fixes: #135639
Fixes: #138066
Fixes: #137885
Fixes: #137505
Fixes: #136396
Fixes: #135805
Fixes: #135639

Release note: None

### CODE REVIEW

File: pkg/ccl/changefeedccl/protected_timestamps_test.go [hunk 1]
```diff
@@ -451,29 +453,74 @@ func TestPTSRecordProtectsTargetsAndSystemTables(t *testing.T) {
 	defer leaktest.AfterTest(t)()
 	defer log.Scope(t).Close(t)
 
-	s, db, stopServer := startTestFullServer(t, feedTestOptions{})
+	// skip.UnderStress(t, "under stress it can take forever for the span config reconciler to update")
+
+	ctx := context.Background()
+
+	// Useful for debugging.
+	require.NoError(t, log.SetVModule("spanconfigstore=2,store=2,reconciler=2,mvcc_gc_queue=2,kvaccessor=2"))
```
Comment (stevendanna) [inline pkg/ccl/changefeedccl/protected_timestamps_test.go:461]: Do we still need this?

File: pkg/ccl/changefeedccl/protected_timestamps_test.go [hunk 2]
```diff
@@ -523,7 +570,18 @@ func TestPTSRecordProtectsTargetsAndSystemTables(t *testing.T) {
 	// Change the user's password to update the users table.
 	sqlDB.Exec(t, `ALTER USER test WITH PASSWORD 'testpass'`)
 
-	time.Sleep(2 * time.Second)
```
Comment (stevendanna) [inline pkg/ccl/changefeedccl/protected_timestamps_test.go:526]: I think for this test to be valid , we likely want to sleep some amount of time to ensure that `ts` is beyond the gc threshold before we try to gc the range.

File: pkg/spanconfig/spanconfigreconciler/reconciler.go [hunk 3]
```diff
@@ -461,6 +461,10 @@ func updateSpanConfigRecords(
 			}
 			return err // not a retryable error, bubble up
 		}
+
+		if log.V(2) {
+			log.Infof(ctx, "successfully updated span config records: deleted = %+#v; upserted = %+#v", toDelete, toUpsert)
+		}
```
Comment (stevendanna) [inline pkg/spanconfig/spanconfigreconciler/reconciler.go:467]: Even at V(2) I wonder if we want this particular log message.   It's rather chatty and hard to read. I leave it to your judgement.

**Review by stevendanna — COMMENTED** [review]
Thanks for continuing to dig into this. Apologies for adding this flaky test :D.

I left one more small comment. Don't feel the need to block on my approval though.

Condolences on now being a span configuration expert.

File: pkg/ccl/changefeedccl/protected_timestamps_test.go (hunk 1 above)
Comment (asg0451) [reply pkg/ccl/changefeedccl/protected_timestamps_test.go:461]: We don't need it, but if it flakes again i'd like to have them.

**Review by stevendanna — APPROVED** [review]

**Comment by asg0451** [comment]
bors r=stevendanna
