### PR TITLE
kvserver: deflake TestRequestsOnFollowerWithNonLiveLeaseholder

### LINKED ISSUE #107200: kv/kvserver: TestRequestsOnFollowerWithNonLiveLeaseholder failed
kv/kvserver.TestRequestsOnFollowerWithNonLiveLeaseholder [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Ci_TestsAwsLinuxArm64_UnitTests/10978381?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Ci_TestsAwsLinuxArm64_UnitTests/10978381?buildTab=artifacts#/) on master @ [30acaf93015008a672667c0d3fdc00ac95f446a6](https://github.com/cockroachdb/cockroach/commits/30acaf93015008a672667c0d3fdc00ac95f446a6):

```
=== RUN   TestRequestsOnFollowerWithNonLiveLeaseholder
    test_log_scope.go:167: test logs captured to: /artifacts/tmp/_tmp/7e19515d2bcbb456ac5289a12c95b9a2/logTestRequestsOnFollowerWithNonLiveLeaseholder1391283936
    test_log_scope.go:81: use -show-logs to present logs inline
    client_raft_test.go:1439: condition failed to evaluate within 45s: from client_raft_test.go:1442: lease still valid
    panic.go:522: -- test log scope end --
test logs left over in: /artifacts/tmp/_tmp/7e19515d2bcbb456ac5289a12c95b9a2/logTestRequestsOnFollowerWithNonLiveLeaseholder1391283936
--- FAIL: TestRequestsOnFollowerWithNonLiveLeaseholder (46.79s)
```
<details><summary>Help</summary>
<p>

See also: [How To Investigate a Go Test Failure \(internal\)](https://cockroachlabs.atlassian.net/l/c/HgfXfJgM)
</p>
</details>
/cc @cockroachdb/replication
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*TestRequestsOnFollowerWithNonLiveLeaseholder.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)
</sub>

Jira issue: CRDB-29943

### PR DESCRIPTION
**Pull request by tbg**
The test previously relied on aggressive liveness heartbeat expirations to
avoid running for too long. As a result, it was flaky since liveness wasn't
reliably pinned in the way the test wanted.

The hybrid manual clock allows time to jump forward at an opportune moment.
Use it here to avoid running with a tight lease interval.

On my gceworker, previously flaked within a few minutes. As of this commit, I
ran it for double-digit minutes without issue.

Fixes #107200.

Epic: None
Release note: None

### CODE REVIEW

File: pkg/kv/kvserver/replica_range_lease.go [hunk 1]
```diff
@@ -445,6 +445,8 @@ func (p *pendingLeaseRequest) requestLeaseAsync(
 	return nil
 }
 
+var logFailedHeartbeatOwnLiveness = log.Every(10 * time.Second)
```
Comment (erikgrinaker) [inline pkg/kv/kvserver/replica_range_lease.go:448]: nit: consider 6 seconds, i.e. the lease interval.

**Review by erikgrinaker — APPROVED** [review]
While we're here, mind changing the test to use `t.Logf` instead of `log.Infof()`?

File: pkg/kv/kvserver/replica_range_lease.go (hunk 1 above)
Comment (tbg) [reply pkg/kv/kvserver/replica_range_lease.go:448]: Not sure why that's better - I'd rather avoid the illusion that this number is somehow special.

**Comment by tbg** [comment]
> While we're here, mind changing the test to use t.Logf instead of log.Infof()?

It was actually useful to have this in the logs, since then it interleaves with the actual logs. Otherwise, you don't get timestamps and you're left wondering about the relative ordering.

TFTR!

bors r=erikgrinaker
