### PR TITLE
sql: add cache for jobs to avoid querying system.jobs to find existing jobs

### LINKED ISSUE #50165: v20.1.1 Regression: Grant on all tables is Very Slow
**Describe the problem**

Please describe the issue you observed, and any steps we can take to reproduce it:

When running a statement like: `grant all on * to "test";` it takes nearly 1 minute to execute on a cluster with 6 nodes.

**To Reproduce**

I wrote a script to test this use case. It spins up 9 nodes, creates 100 tables, and then runs a grant command. If you run it with 19.1.1 or 19.2.2 the grant takes about 400ms. On 20.1.1 it takes 4 seconds.

To use, save the script somewhere then call it with `bash /tmp/script.sh 20.1.1` (or `19.2.2` to see the difference.)

```bash
#!/usr/bin/env bash

set -e -o pipefail -u

version="${1:-20.1.1}"

dir=$( mktemp -d )
cd "$dir"

function cockroach(){
    if ! [[ -x /tmp/cockroach-v$version.darwin-10.9-amd64/cockroach ]]; then
        (
            cd /tmp/;
            curl https://binaries.cockroachdb.com/cockroach-v$version.darwin-10.9-amd64.tgz | tar -xz
        )
    fi
    command /tmp/cockroach-v$version.darwin-10.9-amd64/cockroach "${@}"
}

cockroach version

num_nodes=9
num_tables=100
startsqlport=26257
starthttpport=8080

join=""
for (( i=0; i<9; i++ )); do
    join="$join,localhost:$(( startsqlport + i ))"
done

join="${join#,}"
pids=()

for (( i=0; i<num_nodes; i++ )); do
    cockroach start \
    --insecure \
    --store="node$i" \
    --listen-addr=localhost:$(( $startsqlport + $i )) \
    --http-addr=localhost:$(( $starthttpport + $i )) \
    --join="$join" \
    --background
done

until cockroach init --insecure --host localhost:$startsqlport || echo "select 1;" | cockroach sql --insecure --host localhost:$startsqlport; do 
    sleep 1
done

command=()
command+=( "create user if not exists test;" )
for (( i=0; i<num_tables; i++ )); do
    command+=( "create table if not exists test$i ();" )
done
command+=( "grant all on * to test;" )

printf "%s\n" "${command[@]}" | cockroach sql --insecure --host localhost:$startsqlport

for (( i=0; i<num_nodes; i++ )); do
    args=()
    if [[ $version == 20.1.1 ]]; then
        args+=( "--drain-wait" "5s" )
    fi
    cockroach quit "${args[@]}" --insecure --host localhost:$(( $startsqlport + $i )) &
done

wait

rm -r "$dir"
```

**Expected behavior**
Grants should happen quickly.

**Environment:**
 - CockroachDB version: 20.1.1
 - Server OS: Linux running in GKE across 2 or 3 regions.
- The test script (above) I run on MacOS 10.14.5

### PR DESCRIPTION
**Pull request by RichardJCai**
Currently, we perform a loop through all existing jobs which involves
querying a system table to check if there is an existing job for the current
table undergoing a schema change. To avoid this query, we can use a cache
to map TableIDs to jobs.

Fixes #50165, #50783

Release note: None

### CODE REVIEW

File: pkg/sql/testdata/ddl_analysis/ddl_analysis [hunk 1]
```diff
@@ -36,7 +36,7 @@ CREATE TABLE t10();
 count
 GRANT ALL ON * TO TEST
 ----
-160
+50
```
Comment (rohany) [inline pkg/sql/testdata/ddl_analysis/ddl_analysis:39]: 🚀 🏎️

File: pkg/sql/planner.go [hunk 2]
```diff
@@ -72,6 +72,8 @@ type extendedEvalContext struct {
 
 	Jobs *jobsCollection
 
+	JobsCache *map[sqlbase.ID]*jobs.Job
```
Comment (rohany) [inline pkg/sql/planner.go:75]: Does this need to be a pointer? I thought just copying the map by value took a reference

Comment (rohany) [reply pkg/sql/planner.go:75]: Is it also possible to comment what this is aliasing (as well as the Jobs) alias above? I've found it difficult in the past to figure out how the `extraTxnState` was getting modified.

File: pkg/sql/conn_executor.go [hunk 3]
```diff
@@ -937,6 +939,11 @@ type connExecutor struct {
 		// that staged them commits.
 		jobs jobsCollection
 
+		// jobsCache is a map of TableIDs to Jobs.
```
Comment (rohany) [inline pkg/sql/conn_executor.go:942]: Can you change this comment to be just descriptor IDs? We're going to have jobs tracking changes to descriptors other than tables in the future.

**Comment by rohany** [comment]
Would we backport something like this? I'm not sure.

File: pkg/sql/planner.go (hunk 2 above)
Comment (RichardJCai) [reply pkg/sql/planner.go:75]: I think it actually does have to be a pointer, I don't think maps are pass by reference in go.
Just tried making it not a pointer and it doesn't work.

Also by aliasing do you mean how Jobs/JobsCache refers to values in extraTxnState?

Comment (rohany) [reply pkg/sql/planner.go:75]: Something is wonky, because maps are surely pass by reference -- you can pass a map into a function which fills up the map for you.

> Also by aliasing do you mean how Jobs/JobsCache refers to values in extraTxnState?

Yeah exactly.

Comment (RichardJCai) [reply pkg/sql/planner.go:75]: > Something is wonky, because maps are surely pass by reference -- you can pass a map into a function which fills up the map for you.
> 
> > Also by aliasing do you mean how Jobs/JobsCache refers to values in extraTxnState?
> 
> Yeah exactly.

Wait yeah they're definitely pass by reference... I'm not sure why the pointer is necessary here, hmm

**Review by ajwerner — COMMENTED** [review]
The idea looks good to me. I think we would backport this to 20.1, it's a major regression and does not touch any durable state. The pointer map should get fixed. Otherwise just the naming nit from me.

> Reviewed 1 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/50848#-:-MBADO8l1Lqkgx8TReq2:b-gakk00)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @RichardJCai and @rohany)

___
*[pkg/sql/conn_executor.go, line 942 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/50848#-MBACyRB6Q97dkQR0JnA:-MBACyRC7wI63MSPp2za:b-oa9qbo) ([raw file](https://github.com/cockroachdb/cockroach/blob/83a6476cf1168f896f321f6a0c77cc9645fe1c73/pkg/sql/conn_executor.go#L942)):*
> ```Go
> 		jobs jobsCollection
> 
> 		// jobsCache is a map of TableIDs to Jobs.
> ```

nit: maybe call this `schemaChangeJobCache`

File: pkg/sql/planner.go (hunk 2 above)
Comment (RichardJCai) [reply pkg/sql/planner.go:75]: Nvm I was being dumb, the pointer is necessary because we actually want the map to be reset by the call to resetExtraTxnState since it resets the cache. Without the pointer the cache doesn't get cleared when a txn is committed

**Review by ajwerner — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/50848)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @RichardJCai and @rohany)

___
*[pkg/sql/planner.go, line 75 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/50848#-MB6Dbd13f9f58Ahrx2M-r2-75:-MBAIyln6NuRJkZoa2yq:brcqpui) ([raw file](https://github.com/cockroachdb/cockroach/blob/83a6476cf1168f896f321f6a0c77cc9645fe1c73/pkg/sql/planner.go#L75)):*
<details><summary><i>Previously, RichardJCai (Richard Cai) wrote…</i></summary><blockquote>

Nvm I was being dumb, the pointer is necessary because we actually want the map to be reset by the call to resetExtraTxnState since it resets the cache. Without the pointer the cache doesn't get cleared when a txn is committed
</blockquote></details>

Perhaps a better option is to clear the map rather than constructing a new one in `resetExtraTxnState`. 

https://github.com/golang/go/issues/20138

**Comment by RichardJCai** [comment]
> > _[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/50848)_ status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @RichardJCai and @rohany)
> 
> _[pkg/sql/planner.go, line 75 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/50848#-MB6Dbd13f9f58Ahrx2M-r2-75:-MBAIyln6NuRJkZoa2yq:brcqpui) ([raw file](https://github.com/cockroachdb/cockroach/blob/83a6476cf1168f896f321f6a0c77cc9645fe1c73/pkg/sql/planner.go#L75)):_
> 
> Previously, RichardJCai (Richard Cai) wrote…
> > Nvm I was being dumb, the pointer is necessary because we actually want the map to be reset by the call to resetExtraTxnState since it resets the cache. Without the pointer the cache doesn't get cleared when a txn is committed
> 
> Perhaps a better option is to clear the map rather than constructing a new one in `resetExtraTxnState`.
> 
> [golang/go#20138](https://github.com/golang/go/issues/20138)

Yeah that's probably the way 

> > _[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/50848)_ status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @RichardJCai and @rohany)
> 
> _[pkg/sql/planner.go, line 75 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/50848#-MB6Dbd13f9f58Ahrx2M-r2-75:-MBAIyln6NuRJkZoa2yq:brcqpui) ([raw file](https://github.com/cockroachdb/cockroach/blob/83a6476cf1168f896f321f6a0c77cc9645fe1c73/pkg/sql/planner.go#L75)):_
> 
> Previously, RichardJCai (Richard Cai) wrote…
> > Nvm I was being dumb, the pointer is necessary because we actually want the map to be reset by the call to resetExtraTxnState since it resets the cache. Without the pointer the cache doesn't get cleared when a txn is committed
> 
> Perhaps a better option is to clear the map rather than constructing a new one in `resetExtraTxnState`.
> 
> [golang/go#20138](https://github.com/golang/go/issues/20138)

Good call, I'll do this instead.

**Review by ajwerner — APPROVED** [review]
:lgtm_strong:

> Reviewed 1 of 5 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/50848#-:-MBAcgAlBo91TK3tydqa:b-jbsf8z)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @RichardJCai and @rohany)

**Comment by RichardJCai** [comment]
TFTR!

**Comment by RichardJCai** [comment]
bors r=ajwerner
