### PR TITLE
conflict: diff the clusters when there is a row mismatch

### LINKED ISSUE #156714: roachtest: ldr/conflict failed
roachtest.ldr/conflict [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/20683769?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/20683769?buildTab=artifacts#/ldr/conflict) on master @ [40030306caf369f2a052870dd4aff0db2de97169](https://github.com/cockroachdb/cockroach/commits/40030306caf369f2a052870dd4aff0db2de97169):

```
(assertions.go:369).Fail: 
	Error Trace:	pkg/cmd/roachtest/tests/logical_data_replication.go:1119
	            				pkg/cmd/roachtest/tests/logical_data_replication.go:471
	Error:      	Not equal: 
	            	expected: [][]string{[]string{"conflict_pkey", "3489598971242901138"}, []string{"conflict_col0_4_idx", "-1377892507833848180"}, []string{"conflict_col0_9_col0_6_idx", "232440952925414237"}}
	            	actual  : [][]string{[]string{"conflict_pkey", "-5491769801872468327"}, []string{"conflict_col0_4_idx", "8918791243268455092"}, []string{"conflict_col0_9_col0_6_idx", "-2154589561955823963"}}
	            	
	            	Diff:
	            	--- Expected
	            	+++ Actual
	            	@@ -3,3 +3,3 @@
	            	   (string) (len=13) "conflict_pkey",
	            	-  (string) (len=19) "3489598971242901138"
	            	+  (string) (len=20) "-5491769801872468327"
	            	  },
	            	@@ -7,3 +7,3 @@
	            	   (string) (len=19) "conflict_col0_4_idx",
	            	-  (string) (len=20) "-1377892507833848180"
	            	+  (string) (len=19) "8918791243268455092"
	            	  },
	            	@@ -11,3 +11,3 @@
	            	   (string) (len=26) "conflict_col0_9_col0_6_idx",
	            	-  (string) (len=18) "232440952925414237"
	            	+  (string) (len=20) "-2154589561955823963"
	            	  }
	Test:       	ldr/conflict
	Messages:   	fingerprint mismatch for table conflict
(require.go:162).Equal: FailNow called
test artifacts and logs in: /artifacts/ldr/conflict/run_1
```

Parameters:
 - <code>arch=amd64</code>
 - <code>cloud=gce</code>
 - <code>coverageBuild=false</code>
 - <code>cpu=4</code>
 - <code>encrypted=false</code>
 - <code>fs=ext4</code>
 - <code>localSSD=false</code>
 - <code>metamorphicLeases=expiration</code>
 - <code>metamorphicWriteBuffering=true</code>
 - <code>runtimeAssertionsBuild=false</code>
 - <code>ssd=0</code>
<details><summary>Help</summary>
<p>

See: [roachtest README](https://github.com/cockroachdb/cockroach/blob/master/pkg/cmd/roachtest/README.md)

See: [How To Investigate \(internal\)](https://cockroachlabs.atlassian.net/l/c/SSSBr8c7)

See: [Grafana](https://go.crdb.dev/roachtest-grafana/teamcity-20683769/ldr-conflict/1762005972398/1762007159867)

</p>
</details>
<details><summary>Same failure on other branches</summary>
<p>

- #156268 roachtest: ldr/conflict failed [A-disaster-recovery C-test-failure O-roachtest O-robot P-2 T-disaster-recovery branch-release-25.4.0-rc]
</p>
</details>
/cc @cockroachdb/disaster-recovery
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*ldr/conflict.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/bazci/githubpost/issues)

</sub>

Jira issue: CRDB-56135

### PR DESCRIPTION
**Pull request by jeffswenson**
## conflict: diff the clusters when there is a row mismatch
There is a known unlikely bug in LDR, if conflicting rows with the same
primary key are written at the same mvcc timestamp in both clusters,
then they tie LWW and the clusters do not converge. Since timestamps are
nanosecond precision and LWW is intended for low conflict workloads,
this is believed to be very rare in production, but the conflict
workload reproduces it every few runs.

For now, we will check for this known form of non-convergence.

Fixes: #156714
Release note: none

## rand: move TableWriter from conflict to rand package
Move the table writer infrastructure from `pkg/workload/conflict` to
`pkg/workload/rand` as an exported `TableWriter` type. The writer
operates on `rand.Table` and naturally belongs in the same package.

This makes the writer available to other packages (e.g. for use in
diff tests) without creating cross-package dependencies.

Release note: none

### CODE REVIEW

File: pkg/cmd/roachtest/tests/logical_data_replication.go [hunk 1]
```diff
@@ -469,11 +470,58 @@ func TestLDRConflict(
...
+	fpRight := setup.right.sysSQL.QueryStr(t, fpQuery)
+
+	if fmt.Sprint(fpLeft) == fmt.Sprint(fpRight) {
+		t.L().Printf("fingerprints match")
+		return
+	}
+
+	t.Status("running row-level diff")
+
+	diffs, err := workloadrand.Diff(setup.left.db, "conflict.conflict", setup.right.db, "conflict.conflict", 100)
```
Comment (aerfrei) [inline pkg/cmd/roachtest/tests/logical_data_replication.go]: I'm curious about the 100 limit here. Theoretically, I think this means that if we saw 101 diffs, we wouldn't validate the 101st one and may have missed a real issue. (I guess we could return an error if there are more than 100 diffs). But more realistically, it seems like we don't expect to hit that limit given how rare this issue is. If so, why do we need to be able to specify a limit at all?

File: pkg/cmd/roachtest/tests/logical_data_replication.go [hunk 2]
```diff
@@ -469,11 +470,58 @@ func TestLDRConflict(
...
+	require.NoError(t, err)
+	require.NotEmpty(t, diffs, "fingerprints differ but no row diffs found")
+
+	// Check if all diffs are caused by the known bug: two conflict rows with
+	// the same origin timestamp cause nondeterministic resolution.
+	for _, diff := range diffs {
+		if diff.RowA == nil || diff.RowB == nil {
+			// TODO(jeffswenson): this case is a little sad because we don't
```
Comment (aerfrei) [inline pkg/cmd/roachtest/tests/logical_data_replication.go:543]: nit: Could we file an issue and include the number instead?

File: pkg/workload/rand/diff.go [hunk 3]
```diff
@@ -0,0 +1,326 @@
...
+) (map[int64]fetchedRow, error) {
+	rows, err := conn.Query(query)
+	if err != nil {
+		return nil, errors.Wrap(err, "fetching diff rows")
+	}
+	defer rows.Close()
+
+	result := make(map[int64]fetchedRow)
+	for rows.Next() {
+		// +3: crdb_internal_mvcc_timestamp, crdb_internal_origin_timestamp, pk_hash
```
Comment (aerfrei) [inline pkg/workload/rand/diff.go]: nit: Could this be a full sentence? Took me a second to realize what `:3+` meant

File: pkg/workload/rand/schema.go [hunk 4]
```diff
@@ -59,6 +59,25 @@ func (t *Table) RandomRow(rng *rand.Rand, nullPct int) ([]any, error) {
 	return row, nil
 }
 
+// IndexableColumns returns the indices of columns with a type that can be
+// stored in an index. This is useful for things like fingeprinting, where we
```
Comment (aerfrei) [inline pkg/workload/rand/schema.go]: nit: typo. fingerprinting has two rs.

**Review by aerfrei — APPROVED** [review]
Looks good. I left a few nits. I'm hoping to take another pass, there's a lot of code to read here.

File: pkg/cmd/roachtest/tests/logical_data_replication.go (hunk 1 above)
Comment (KeithCh) [reply pkg/cmd/roachtest/tests/logical_data_replication.go]: +1, is a limit ncessary?

**Review by KeithCh — APPROVED** [review]
Overall looks good. If only we can make fingerprinting work Molt Verify as well.

File: pkg/cmd/roachtest/tests/logical_data_replication.go (hunk 1 above)
Comment (jeffswenson) [reply pkg/cmd/roachtest/tests/logical_data_replication.go:533]: The motivation for the limit is that in the worst case this reports the entire database which is millions of rows. In practice we expect 1-2 rows with matching origin times, so if there is a 100 or more the test is going to fail.

File: pkg/cmd/roachtest/tests/logical_data_replication.go (hunk 2 above)
Comment (jeffswenson) [reply pkg/cmd/roachtest/tests/logical_data_replication.go:541]: Good suggestion! I opened this issue: https://github.com/cockroachdb/cockroach/issues/168541.

File: pkg/cmd/roachtest/tests/BUILD.bazel [hunk 5]
```diff
@@ -325,6 +325,7 @@ go_library(
         "//pkg/workload/debug",
         "//pkg/workload/histogram",
         "//pkg/workload/histogram/exporter",
+        "//pkg/workload/rand",
         "//pkg/workload/schemachange",
         "//pkg/workload/tpcc",
```
Comment (jeffswenson) [inline pkg/cmd/roachtest/tests/BUILD.bazel:331]: Fixed

File: pkg/workload/rand/diff.go (hunk 3 above)
Comment (jeffswenson) [reply pkg/workload/rand/diff.go]: Fixed

File: pkg/workload/rand/schema.go (hunk 4 above)
Comment (jeffswenson) [reply pkg/workload/rand/schema.go]: Fixed

**Comment by jeffswenson** [comment]
Thanks for the reviews!

File: pkg/workload/rand/diff.go [hunk 6]
```diff
@@ -0,0 +1,329 @@
...
+	// Build diff results from the fetched rows.
+	colNames := make([]string, len(schema.Cols))
+	for i, col := range schema.Cols {
+		colNames[i] = col.Name
+	}
+
+	var results []RowDiff
+	for pk := range diffPKs {
+		if len(results) >= resultLimit {
+			break
```
Comment (aerfrei) [inline pkg/workload/rand/diff.go:297]: nit: Would it make more sense to just return an error if we hit this case? Is there another mechanism by which the test fails when the limit is exceeded. I think I was missing something from your previous answer about the limit.

Comment (jeffswenson) [reply pkg/workload/rand/diff.go:297]: Good point! I added an assertion to the conflict workload so that if the number of diffs returned is equal to the limit, it fails the test. 

I don't think the `diff` package should return an error because there are situations where outputting a sample of diffed rows is reasonable.
