### PR TITLE
crosscluster: fix TestTxnModeCreateLogicallyReplicated flake

### LINKED ISSUE #168170: TestTxnModeCreateLogicallyReplicated flaking
`TestTxnModeCreateLogicallyReplicated` is flaking due to the incorrect time being passed into
`WaitUntilReplicatedTime`. This caused us to assert that certain rows were replicated before
it actually is replicated.

Jira issue: CRDB-62822

### PR DESCRIPTION
**Pull request by KeithCh**
The WaitForReplicatedTime calls were made with a time that 
is before the transaction was committed, causing us to check
that the rows were replicated too early.

Fixes: #168170
Release Note: None

### CODE REVIEW

**Comment by KeithCh** [comment]
The failed test in CI will be fixed by #168168

File: pkg/crosscluster/logical/txnmode/txnmode_test.go [hunk 1]
```diff
@@ -207,14 +207,13 @@ func TestTxnModeCreateLogicallyReplicated(t *testing.T) {
...
 	// Insert more data in a transaction after replication starts
-	now := s.Clock().Now()
 	sourceDB.Exec(t, `
 		BEGIN;
 		INSERT INTO orders VALUES (2, 100, 75.00);
 		INSERT INTO orders VALUES (3, 101, 100.00);
 		COMMIT;
 	`)
-
+	now := s.Clock().Now()
```
Comment (aerfrei) [inline pkg/crosscluster/logical/txnmode/txnmode_test.go]: nit: looks like you can avoid the now variable entirely and just move this expression in line. I think that would decrease mental load when reading it if you're not expecting now to come up again later.

**Review by aerfrei — APPROVED** [review]
Looks good! I left a nit
