### PR TITLE
bulkio: Fix backup tpcc roachtest failure.

### LINKED ISSUE #53591: roachtest: backupTPCC failed
[(roachtest).backupTPCC failed](https://teamcity.cockroachdb.com/viewLog.html?buildId=2229371&tab=buildLog) on [release-19.2@272857ba9f6d5f34b9cdd5141043288a6ecb31bc](https://github.com/cockroachdb/cockroach/commits/272857ba9f6d5f34b9cdd5141043288a6ecb31bc):

```
The test failed on branch=release-19.2, cloud=gce:
test artifacts and logs in: /home/agent/work/.go/src/github.com/cockroachdb/cockroach/artifacts/backupTPCC/run_1
	cluster.go:2183,backup.go:229,test_runner.go:754: output in run_055427.948_n1_workload_init_tpcc: /home/agent/work/.go/src/github.com/cockroachdb/cockroach/bin/roachprod run teamcity-2229371-1598593613-18-n3cpu4:1 -- ./workload init tpcc --warehouses=10 {pgurl:1-3} returned: exit status 20
		(1) attached stack trace
		  -- stack trace:
		  | main.(*cluster).RunE
		  | 	/home/agent/work/.go/src/github.com/cockroachdb/cockroach/pkg/cmd/roachtest/cluster.go:2261
		  | main.(*cluster).Run
		  | 	/home/agent/work/.go/src/github.com/cockroachdb/cockroach/pkg/cmd/roachtest/cluster.go:2181
		  | main.registerBackup.func4
		  | 	/home/agent/work/.go/src/github.com/cockroachdb/cockroach/pkg/cmd/roachtest/backup.go:229
		  | main.(*testRunner).runTest.func2
		  | 	/home/agent/work/.go/src/github.com/cockroachdb/cockroach/pkg/cmd/roachtest/test_runner.go:754
		  | runtime.goexit
		  | 	/usr/local/go/src/runtime/asm_amd64.s:1357
		Wraps: (2) output in run_055427.948_n1_workload_init_tpcc
		Wraps: (3) /home/agent/work/.go/src/github.com/cockroachdb/cockroach/bin/roachprod run teamcity-2229371-1598593613-18-n3cpu4:1 -- ./workload init tpcc --warehouses=10 {pgurl:1-3} returned
		  | stderr:
		  | 00828 05:54:57.897220 1 workload/workloadsql/dataload.go:140  imported history (5s, 300000 rows)
		  | I200828 05:55:03.686077 1 workload/workloadsql/dataload.go:140  imported order (6s, 300000 rows)
		  | I200828 05:55:04.294774 1 workload/workloadsql/dataload.go:140  imported new_order (1s, 90000 rows)
		  | I200828 05:55:05.548329 1 workload/workloadsql/dataload.go:140  imported item (1s, 100000 rows)
		  | I200828 05:56:04.413677 1 workload/workloadsql/dataload.go:140  imported stock (59s, 1000000 rows)
		  | I200828 05:56:44.328131 1 workload/workloadsql/dataload.go:140  imported order_line (40s, 3001222 rows)
		  | Error: Could not postload: pq: foreign key requires an existing index on columns ("h_c_w_id", "h_c_d_id", "h_c_id")
		  | Hint: try using the --deprecated-fk-indexes flag
		  | Error: COMMAND_PROBLEM: exit status 1
		  | (1) COMMAND_PROBLEM
		  | Wraps: (2) Node 1. Command with error:
		  |   | ```
		  |   | ./workload init tpcc --warehouses=10 {pgurl:1-3}
		  |   | ```
		  | Wraps: (3) exit status 1
		  | Error types: (1) errors.Cmd (2) *hintdetail.withDetail (3) *exec.ExitError
		  |
		  | stdout:
		  | pq: foreign key requires an existing index on columns ("h_c_w_id", "h_c_d_id", "h_c_id")
		Wraps: (4) exit status 20
		Error types: (1) *withstack.withStack (2) *errutil.withPrefix (3) *main.withCommandDetails (4) *exec.ExitError

```

<details><summary>More</summary><p>

Artifacts: [/backupTPCC](https://teamcity.cockroachdb.com/viewLog.html?buildId=2229371&tab=artifacts#/backupTPCC)
Related:
- #53082 roachtest: backupTPCC failed  [C-test-failure](https://api.github.com/repos/cockroachdb/cockroach/labels/C-test-failure) [O-roachtest](https://api.github.com/repos/cockroachdb/cockroach/labels/O-roachtest) [O-robot](https://api.github.com/repos/cockroachdb/cockroach/labels/O-robot) [branch-provisional_202008191705_v19.2.10](https://api.github.com/repos/cockroachdb/cockroach/labels/branch-provisional_202008191705_v19.2.10) [release-blocker](https://api.github.com/repos/cockroachdb/cockroach/labels/release-blocker)

[See this test on roachdash](https://roachdash.crdb.dev/?filter=status%3Aopen+t%3A.%2AbackupTPCC.%2A&sort=title&restgroup=false&display=lastcommented+project)
<sub>powered by [pkg/cmd/internal/issues](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)</sub></p></details>

### LINKED ISSUE #53728: roachtest: backupTPCC failed
[(roachtest).backupTPCC failed](https://teamcity.cockroachdb.com/viewLog.html?buildId=2237018&tab=buildLog) on [release-20.1@ff3749579c10bb948e89598a5b58bfdcfeb432be](https://github.com/cockroachdb/cockroach/commits/ff3749579c10bb948e89598a5b58bfdcfeb432be):

```
The test failed on branch=release-20.1, cloud=gce:
test artifacts and logs in: /home/agent/work/.go/src/github.com/cockroachdb/cockroach/artifacts/backupTPCC/run_1
	cluster.go:2197,backup.go:229,test_runner.go:754: output in run_062201.915_n1_workload_init_tpcc: /home/agent/work/.go/src/github.com/cockroachdb/cockroach/bin/roachprod run teamcity-2237018-1598940224-22-n3cpu4:1 -- ./workload init tpcc --warehouses=10 {pgurl:1-3} returned: exit status 20
		(1) attached stack trace
		  -- stack trace:
		  | main.(*cluster).RunE
		  | 	/home/agent/work/.go/src/github.com/cockroachdb/cockroach/pkg/cmd/roachtest/cluster.go:2275
		  | main.(*cluster).Run
		  | 	/home/agent/work/.go/src/github.com/cockroachdb/cockroach/pkg/cmd/roachtest/cluster.go:2195
		  | main.registerBackup.func4
		  | 	/home/agent/work/.go/src/github.com/cockroachdb/cockroach/pkg/cmd/roachtest/backup.go:229
		  | main.(*testRunner).runTest.func2
		  | 	/home/agent/work/.go/src/github.com/cockroachdb/cockroach/pkg/cmd/roachtest/test_runner.go:754
		  | runtime.goexit
		  | 	/usr/local/go/src/runtime/asm_amd64.s:1357
		Wraps: (2) output in run_062201.915_n1_workload_init_tpcc
		Wraps: (3) /home/agent/work/.go/src/github.com/cockroachdb/cockroach/bin/roachprod run teamcity-2237018-1598940224-22-n3cpu4:1 -- ./workload init tpcc --warehouses=10 {pgurl:1-3} returned
		  | stderr:
		  | 00901 06:22:22.414074 1 workload/workloadsql/dataload.go:140  imported history (5s, 300000 rows)
		  | I200901 06:22:28.940679 1 workload/workloadsql/dataload.go:140  imported order (7s, 300000 rows)
		  | I200901 06:22:29.750213 1 workload/workloadsql/dataload.go:140  imported new_order (1s, 90000 rows)
		  | I200901 06:22:31.115943 1 workload/workloadsql/dataload.go:140  imported item (1s, 100000 rows)
		  | I200901 06:23:04.777378 1 workload/workloadsql/dataload.go:140  imported stock (34s, 1000000 rows)
		  | I200901 06:23:46.605816 1 workload/workloadsql/dataload.go:140  imported order_line (42s, 3001222 rows)
		  | Error: Could not postload: pq: foreign key requires an existing index on columns ("h_c_w_id", "h_c_d_id", "h_c_id")
		  | Hint: try using the --deprecated-fk-indexes flag
		  | Error: COMMAND_PROBLEM: exit status 1
		  | (1) COMMAND_PROBLEM
		  | Wraps: (2) Node 1. Command with error:
		  |   | ```
		  |   | ./workload init tpcc --warehouses=10 {pgurl:1-3}
		  |   | ```
		  | Wraps: (3) exit status 1
		  | Error types: (1) errors.Cmd (2) *hintdetail.withDetail (3) *exec.ExitError
		  |
		  | stdout:
		  | pq: foreign key requires an existing index on columns ("h_c_w_id", "h_c_d_id", "h_c_id")
		Wraps: (4) exit status 20
		Error types: (1) *withstack.withStack (2) *errutil.withPrefix (3) *main.withCommandDetails (4) *exec.ExitError

```

<details><summary>More</summary><p>

Artifacts: [/backupTPCC](https://teamcity.cockroachdb.com/viewLog.html?buildId=2237018&tab=artifacts#/backupTPCC)
Related:
- #53591 roachtest: backupTPCC failed  [C-test-failure](https://api.github.com/repos/cockroachdb/cockroach/labels/C-test-failure) [O-roachtest](https://api.github.com/repos/cockroachdb/cockroach/labels/O-roachtest) [O-robot](https://api.github.com/repos/cockroachdb/cockroach/labels/O-robot) [branch-release-19.2](https://api.github.com/repos/cockroachdb/cockroach/labels/branch-release-19.2) [release-blocker](https://api.github.com/repos/cockroachdb/cockroach/labels/release-blocker)

[See this test on roachdash](https://roachdash.crdb.dev/?filter=status%3Aopen+t%3A.%2AbackupTPCC.%2A&sort=title&restgroup=false&display=lastcommented+project)
<sub>powered by [pkg/cmd/internal/issues](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)</sub></p></details>

### PR DESCRIPTION
**Pull request by miretskiy**
Fixes #53728
Fixes #53591

Add a `--deprecated-fk-indexes` flag to workload command when running
at version below 20.2.

Release Notes: None
Release Justification: release blocking roachtest fix.

### CODE REVIEW

**Review by adityamaru — APPROVED** [review]

**Review by pbardea — APPROVED** [review]

File: pkg/cmd/roachtest/backup.go [hunk 1]
```diff
@@ -52,9 +52,15 @@ func registerBackup(r *testRegistry) {
 		c.Run(ctx, c.All(), `./workload csv-server --port=8081 &> logs/workload-csv-server.log < /dev/null &`)
 		time.Sleep(time.Second) // wait for csv server to open listener
 
-		c.Run(ctx, c.Node(1), "./workload", "fixtures", "import", "bank",
+		importArgs := []string{
+			"./workload", "fixtures", "import", "bank",
```
Comment (dt) [inline pkg/cmd/roachtest/backup.go:56]: this is `bank` not `tpcc` and bank doesn't accept the `deprecated-fk-indexes` flag.
