### PR TITLE
sql: handle ColumnConversionValidate conversions for alter column type

### LINKED ISSUE #50277: sql: unknown conversion for int8 -> int4 for ALTER COLUMN TYPE
We get an unknown conversion type for INT8 -> INT4 conversion. In general we're missing a switch case for ColumnConversionValidate which results in the panic.

Example:

```
root@127.0.0.1:63709/movr> create table t(x int8);
CREATE TABLE

Time: 2.697ms

root@127.0.0.1:63709/movr> alter table t alter column x type int2;
ERROR: internal error: unknown conversion for INT8 -> INT2
SQLSTATE: XX000
DETAIL: stack trace:
github.com/cockroachdb/cockroach/pkg/sql/alter_column_type.go:127: AlterColumnType()
github.com/cockroachdb/cockroach/pkg/sql/alter_table.go:810: applyColumnMutation()
github.com/cockroachdb/cockroach/pkg/sql/alter_table.go:606: startExec()
github.com/cockroachdb/cockroach/pkg/sql/plan.go:457: func2()
github.com/cockroachdb/cockroach/pkg/sql/walk.go:144: func1()
github.com/cockroachdb/cockroach/pkg/sql/walk.go:763: visitInternal()
github.com/cockroachdb/cockroach/pkg/sql/walk.go:111: visit()
github.com/cockroachdb/cockroach/pkg/sql/walk.go:75: walkPlan()
github.com/cockroachdb/cockroach/pkg/sql/plan.go:460: startExec()
github.com/cockroachdb/cockroach/pkg/sql/plan_node_to_row_source.go:117: Start()
github.com/cockroachdb/cockroach/pkg/sql/execinfra/processorsbase.go:747: Run()
github.com/cockroachdb/cockroach/pkg/sql/flowinfra/flow.go:369: Run()
github.com/cockroachdb/cockroach/pkg/sql/distsql_running.go:406: Run()
github.com/cockroachdb/cockroach/pkg/sql/distsql_running.go:1018: PlanAndRun()
github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:904: execWithDistSQLEngine()
github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:801: dispatchToExecutionEngine()
github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:488: execStmtInOpenState()
github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:99: execStmt()
github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:1356: execCmd()
github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:1285: run()
github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:490: ServeConn()
github.com/cockroachdb/cockroach/pkg/sql/pgwire/conn.go:595: func1()
runtime/asm_amd64.s:1357: goexit()
```

### PR DESCRIPTION
**Pull request by RichardJCai**
Perform online schema change for ALTER COLUMN TYPE ColumnConversionValidate

Fixes #50277

Was missing a switch statement case for ColumnConversionValidate causing the code
to reach the default case of unknown conversion.

Release note (sql change): Fix error for ALTER COLUMN TYPE for certain conversions
where a the data matches byte for byte but we have to perform a validation. Ie
INT8 -> INT4. Previously this conversion would error out.

### CODE REVIEW

File: pkg/sql/logictest/testdata/logic_test/alter_column_type [hunk 1]
```diff
@@ -523,3 +523,9 @@ SELECT x FROM t28 ORDER BY x
 5
 10
 15
+
+# Regression 50277, ensure ColumnConversionValidate type conversion doesn't
+# error before running the online schema change.
+statement ok
+CREATE TABLE t29 (x INT8);
```
Comment (rohany) [inline pkg/sql/logictest/testdata/logic_test/alter_column_type:530]: Can you add some data in the table, and a case that errors out (if it should)

**Review by rohany — CHANGES_REQUESTED** [review]

File: pkg/sql/logictest/testdata/logic_test/alter_column_type (hunk 1 above)
Comment (RichardJCai) [reply pkg/sql/logictest/testdata/logic_test/alter_column_type:530]: Done both.

File: pkg/sql/schemachange/alter_column_type.go [hunk 2]
```diff
@@ -101,11 +101,11 @@ var classifiers = map[types.Family]map[types.Family]classifier{
 		types.BytesFamily: func(s *types.T, b *types.T) ColumnConversionKind {
 			switch {
 			case b.Width() == 0:
-				return ColumnConversionTrivial
+				return ColumnConversionValidate
```
Comment (rohany) [inline pkg/sql/schemachange/alter_column_type.go:104]: Can't this whole function just return `ColumnConversionValidate` now?

File: pkg/sql/logictest/testdata/logic_test/alter_column_type [hunk 3]
```diff
@@ -523,3 +523,25 @@ SELECT x FROM t28 ORDER BY x
...
+ALTER TABLE t29 ALTER COLUMN x TYPE INT4;
+
+query I
+SELECT x FROM t29 ORDER BY x
+----
+1
+2
+3
+
+# ColumnConversionValidate should error out if the conversion is not valid.
```
Comment (rohany) [inline pkg/sql/logictest/testdata/logic_test/alter_column_type:541]: This comment doesn't make much sense out of context -- can you give the context needed?

**Review by rohany — CHANGES_REQUESTED** [review]

File: pkg/sql/schemachange/alter_column_type.go (hunk 2 above)
Comment (RichardJCai) [reply pkg/sql/schemachange/alter_column_type.go]: Done

File: pkg/sql/logictest/testdata/logic_test/alter_column_type (hunk 3 above)
Comment (RichardJCai) [reply pkg/sql/logictest/testdata/logic_test/alter_column_type:541]: Added context

**Review by rohany — APPROVED** [review]

**Comment by RichardJCai** [comment]
Thanks for the review!

**Comment by RichardJCai** [comment]
bors r=rohany
