### PR TITLE
ttljob: make TTL work for multi-tenant

### LINKED ISSUE #82386: ttljob: make the TTL job compatible with multi-tenancy
At the moment, row-level TTL fails in multi-tenancy with:

`Unauthenticated desc = requested key /Meta2/Tenant/10/Table/105/1/NULL not fully contained in tenant keyspace /Tenant/1{0-1}`

After this setup:
```
CREATE TABLE t (v INT PRIMARY KEY) WITH (ttl_expire_after = '1 microsecond', ttl_job_cron = '@every 1s');
INSERT INTO t SELECT x FROM generate_series(1,100) g(x);
```

This is because the range scan operation is prohibited in multi-tenancy:

https://github.com/cockroachdb/cockroach/blob/aa56262a5e0457e9e56304ade5ca2b7673c8f75f/pkg/sql/ttl/ttljob/ttljob.go#L432-L435

This probably involves some work exposing available ranges for the given table through kvtenant interface: https://github.com/cockroachdb/cockroach/pull/67098/commits.

**For v22.1:** Alternatively, we could consider making this work for serverless for v22.1 temporarily by avoiding the range scan and assume that TTL is not partitioned by range.

Related: https://cockroachlabs.atlassian.net/browse/CC-7065, [slack convo](https://cockroachlabs.slack.com/archives/C04U1BTF8/p1654153575326459)

Jira issue: CRDB-16344
Epic CRDB-14592

### PR DESCRIPTION
**Pull request by otan**
Use the appropriate KV abstraction to make ttl work for serverless
clusters.

We can't use `SPLIT AT` with multi-tenant tests, so we are skipping
those for now.

Release note (sql change): The cluster setting
`sql.ttl.range_batch_size` is deprecated.

Resolves #82386

Release note (sql change): Row-level TTL now works for multi-tenant
clusters.

### CODE REVIEW

**Comment by ajstorm** [comment]
> We can't use SPLIT AT with multi-tenant tests, so we are skipping
those for now.

@rharding6373 FYI.

**Review by rafiss — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/82390)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ecwall and @otan)

___
*[`pkg/sql/ttl/ttljob/main_test.go` line 18 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/82390#-N3f96VR84CcjNPFn8Y-:-N3f96VR84CcjNPFn8Y0:b-jc76x2) ([raw file](https://github.com/cockroachdb/cockroach/blob/7dc6a3cfa38e6873331b109c65ff49c27b2a8200/pkg/sql/ttl/ttljob/main_test.go#L18)):*
> ```Go
> 
> 	// Since we are testing multi-tenancy, we need to blank import kvtenantccl.
> 	_ "github.com/cockroachdb/cockroach/pkg/ccl/kvccl/kvtenantccl"
> ```

is this the official way of doing this? or would we want the test file to be in `pkg/ccl`?

maybe this won't matter after @knz 's licensing work?

**Comment by otan** [comment]
*[`pkg/sql/ttl/ttljob/main_test.go` line 18 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/82390#-N3f96VR84CcjNPFn8Y-:-N3fPoCN1F8AkSWtkA0_:btxnb64) ([raw file](https://github.com/cockroachdb/cockroach/blob/7dc6a3cfa38e6873331b109c65ff49c27b2a8200/pkg/sql/ttl/ttljob/main_test.go#L18)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

is this the official way of doing this? or would we want the test file to be in `pkg/ccl`?

maybe this won't matter after @knz 's licensing work?
</blockquote></details>

I'm not sure unfortunately :(

**Review by ajwerner — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/82390)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ecwall and @knz)

___
*[`pkg/sql/ttl/ttljob/main_test.go` line 18 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/82390#-N3f96VR84CcjNPFn8Y-:-N3tVgC1CfxOmKkjld4Y:bi4yjpd) ([raw file](https://github.com/cockroachdb/cockroach/blob/7dc6a3cfa38e6873331b109c65ff49c27b2a8200/pkg/sql/ttl/ttljob/main_test.go#L18)):*
<details><summary><i>Previously, otan (Oliver Tan) wrote…</i></summary><blockquote>

I'm not sure unfortunately :( 
</blockquote></details>

The party line is that any tenant testing needs to be moved to a `ccl` package.

**Review by knz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/82390)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ecwall and @rafiss)

___
*[`pkg/sql/ttl/ttljob/main_test.go` line 18 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/82390#-N3f96VR84CcjNPFn8Y-:-N3tWmA6ADJWOYW8GBdb:b-o1hjzb) ([raw file](https://github.com/cockroachdb/cockroach/blob/7dc6a3cfa38e6873331b109c65ff49c27b2a8200/pkg/sql/ttl/ttljob/main_test.go#L18)):*
> maybe this won't matter after @knz 's licensing work?
correct but we're not there yet. so for now this is ok

**Comment by otan** [comment]
do we still want this merged & in v22.1?

**Comment by rafiss** [comment]
> do we still want this merged & in v22.1?

yes

**Comment by otan** [comment]
stamp me :D

File: pkg/settings/registry.go [hunk 1]
```diff
@@ -119,6 +119,7 @@ var retiredSettings = map[string]struct{}{
 	"trace.datadog.project":                                            {},
 	"sql.defaults.interleaved_tables.enabled":                          {},
 	"sql.defaults.copy_partitioning_when_deinterleaving_table.enabled": {},
+	"sql.ttl.range_batch_size":                                         {},
```
Comment (rafiss) [inline pkg/settings/registry.go:122]: nit: rebase and put it under the "removed as oof 22.2" comment

**Review by rafiss — APPROVED** [review]
added a nit

File: pkg/settings/registry.go (hunk 1 above)
Comment (otan) [reply pkg/settings/registry.go:122]: Hmm that won't backport nicely, technically this is straight away in 22.1.ill put something in between

**Comment by otan** [comment]
bors r=rafiss

**Comment by otan** [comment]
bors r=rafiss
