### PR TITLE
attempt at fixing #893

### LINKED ISSUE #893: TestStoreRangeMergeNonConsecutive loses Raft command on last range, times out
The following test appears to have failed:

[#2050](https://circleci.com/gh/cockroachdb/cockroach/2050):

```
I0502 15:30:39.768189     443 multiraft.go:694] node 100000001: group 2 raft ready
I0502 15:30:39.768254     443 multiraft.go:699] HardState updated: {Term:6 Vote:4294967297 Commit:16 XXX_unrecognized:[]}
I0502 15:30:39.769040     443 multiraft.go:702] New Entry[0]: 6/16 EntryNormal 0000000000000000799e447ae60f42c8: raft_id:2 origin_node_id:4294967297 cmd:<internal_resolve_intent:<header:<timestamp:<wall_time:0 logical:52 > cmd_id:<wall_time:0 random:0 > key:"\00
I0502 15:30:39.769815     443 multiraft.go:705] Committed Entry[0]: 6/16 EntryNormal 0000000000000000799e447ae60f42c8: raft_id:2 origin_node_id:4294967297 cmd:<internal_resolve_intent:<header:<timestamp:<wall_time:0 logical:52 > cmd_id:<wall_time:0 random:0 > key:"\00
I0502 15:30:39.771286     443 multiraft.go:873] dropping stale write to group 3
panic: test timed out after 5m0s

goroutine 3477 [running]:
testing.func·008()
	/usr/src/go/src/testing/testing.go:681 +0x168
created by time.goFunc
	/usr/src/go/src/time/sleep.go:129 +0x59

goroutine 1 [chan receive, 4 minutes]:
testing.RunTests(0x13466c8, 0x182a420, 0xa3, 0xa3, 0x1)
	/usr/src/go/src/testing/testing.go:556 +0xdc3
--
	/go/src/github.com/cockroachdb/cockroach/kv/txn_coord_sender.go:502 +0xd2a
github.com/cockroachdb/cockroach/util.func·005()
	/go/src/github.com/cockroachdb/cockroach/util/stopper.go:73 +0x80
created by github.com/cockroachdb/cockroach/util.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/util/stopper.go:74 +0x133
FAIL	github.com/cockroachdb/cockroach/storage	300.049s
=== RUN TestBatchBasics
I0502 15:31:31.356473     531 rocksdb.go:88] opening in-memory rocksdb instance
I0502 15:31:31.357485     531 rocksdb.go:113] closing in-memory rocksdb instance
--- PASS: TestBatchBasics (0.00s)
=== RUN TestBatchGet
I0502 15:31:31.360548     531 rocksdb.go:88] opening in-memory rocksdb instance
I0502 15:31:31.360922     531 rocksdb.go:113] closing in-memory rocksdb instance
--- PASS: TestBatchGet (0.00s)
=== RUN TestBatchMerge
I0502 15:31:31.364016     531 rocksdb.go:88] opening in-memory rocksdb instance
I0502 15:30:39.768189     443 multiraft.go:694] node 100000001: group 2 raft ready
I0502 15:30:39.768254     443 multiraft.go:699] HardState updated: {Term:6 Vote:4294967297 Commit:16 XXX_unrecognized:[]}
I0502 15:30:39.769040     443 multiraft.go:702] New Entry[0]: 6/16 EntryNormal 0000000000000000799e447ae60f42c8: raft_id:2 origin_node_id:4294967297 cmd:<internal_resolve_intent:<header:<timestamp:<wall_time:0 logical:52 > cmd_id:<wall_time:0 random:0 > key:"\00
I0502 15:30:39.769815     443 multiraft.go:705] Committed Entry[0]: 6/16 EntryNormal 0000000000000000799e447ae60f42c8: raft_id:2 origin_node_id:4294967297 cmd:<internal_resolve_intent:<header:<timestamp:<wall_time:0 logical:52 > cmd_id:<wall_time:0 random:0 > key:"\00
I0502 15:30:39.771286     443 multiraft.go:873] dropping stale write to group 3
panic: test timed out after 5m0s

goroutine 3477 [running]:
testing.func·008()
	/usr/src/go/src/testing/testing.go:681 +0x168
created by time.goFunc
	/usr/src/go/src/time/sleep.go:129 +0x59

goroutine 1 [chan receive, 4 minutes]:
testing.RunTests(0x13466c8, 0x182a420, 0xa3, 0xa3, 0x1)
	/usr/src/go/src/testing/testing.go:556 +0xdc3
--
	/go/src/github.com/cockroachdb/cockroach/kv/txn_coord_sender.go:502 +0xd2a
github.com/cockroachdb/cockroach/util.func·005()
	/go/src/github.com/cockroachdb/cockroach/util/stopper.go:73 +0x80
created by github.com/cockroachdb/cockroach/util.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/util/stopper.go:74 +0x133
FAIL	github.com/cockroachdb/cockroach/storage	300.049s
=== RUN TestBatchBasics
I0502 15:31:31.356473     531 rocksdb.go:88] opening in-memory rocksdb instance
I0502 15:31:31.357485     531 rocksdb.go:113] closing in-memory rocksdb instance
--- PASS: TestBatchBasics (0.00s)
=== RUN TestBatchGet
I0502 15:31:31.360548     531 rocksdb.go:88] opening in-memory rocksdb instance
I0502 15:31:31.360922     531 rocksdb.go:113] closing in-memory rocksdb instance
--- PASS: TestBatchGet (0.00s)
=== RUN TestBatchMerge
I0502 15:31:31.364016     531 rocksdb.go:88] opening in-memory rocksdb instance

```
Please assign, take a look and update the issue accordingly.

### PR DESCRIPTION
**Pull request by tbg**
when a group gets deleted, everyone still waiting for a command to commit will
have their proposals aborted.
closes #893

there are still issues with this test (or multiraft/raft, depending on how you
see it), but this should fix the overwhelming majority of test failures in
TestStoreRangeMergeNonConsecutive.

see #906 for a very rare, open bug caused by this test.

### CODE REVIEW

**Comment by BramGruneir** [comment]
LGTM

**Comment by mrtracy** [comment]
LGTM

**Comment by spencerkimball** [comment]
LGTM, but @bdarnell should definitely weigh in on the raft changes.

File: multiraft/multiraft.go [hunk 1]
```diff
@@ -654,10 +654,21 @@ func (s *state) createGroup(groupID uint64) error {
...
+	g, ok := s.groups[op.groupID]
+	if !ok {
 		op.ch <- nil
 		return
 	}
+
+	// Cancel commands which are still in transit.
+	for cmdID, prop := range g.pending {
+		if prop.ch != nil {
+			prop.ch <- util.Errorf("group deleted")
```
Comment (bdarnell) [inline multiraft/multiraft.go]: This needs to return a retryable error to the client. To maintain separation of multiraft, create a new error type here to return, and then have the client convert multiraft.GroupDeletedError to a new proto.RangeMovedError (which should be Retryable). This way the client will retry and find the new home of this range.

**Comment by bdarnell** [comment]
LGTM

File: multiraft/multiraft.go (hunk 1 above)
Comment (tschottdorf) [inline multiraft/multiraft.go]: ok, I'll do it tomorrow. BTW looks that now that this bug is fixed, we'll hit #906 more often (at least it happened twice today).
