### PR TITLE
storage: deflake TestRestoreReplicas

### LINKED ISSUE #9997: teamcity: failed tests on master: testrace/TestRestoreReplicas
The following tests appear to have failed:

[#32069](https://teamcity.cockroachdb.com/viewLog.html?buildId=32069):

```
--- FAIL: testrace/TestRestoreReplicas (0.002s)
	client_raft_test.go:347: range 1: replica {1 1 1} not lease holder; node_id:2 store_id:2 replica_id:2  is

```
Please assign, take a look and update the issue accordingly.

### PR DESCRIPTION
**Pull request by petermattis**
Fixes #9997

---

This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/10017)

### CODE REVIEW

File: pkg/storage/client_raft_test.go [hunk 1]
```diff
@@ -301,7 +301,15 @@ func TestReplicateRange(t *testing.T) {
 // persisted to disk and restored when a node is stopped and restarted.
 func TestRestoreReplicas(t *testing.T) {
 	defer leaktest.AfterTest(t)()
-	mtc := startMultiTestContext(t, 2)
+
+	sc := storage.TestStoreConfig()
+	// Disable periodic gossip activities. The periodic gossiping of the first
+	// range can cause spurious lease transfers which cause this test to fail.
+	sc.TestingKnobs.DisablePeriodicGossips = true
+	mtc := &multiTestContext{
```
Comment (tamird) [inline pkg/storage/client_raft_test.go]: nit: need not be a pointer.

**Review by tamird — APPROVED** [review]

File: pkg/storage/client_raft_test.go (hunk 1 above)
Comment (petermattis) [inline pkg/storage/client_raft_test.go]: `mtc.Start` takes a pointer receiver. I prefer the explicitness. Also, there are some global methods with take `*multiTestContext`. We're a bit inconsistent here, so I've gone ahead and changed all of the `mtc` variables to pointers.

**Comment by tschottdorf** [comment]
LGTM
