### PR TITLE
ui: add line graph for replication lag metric

### LINKED ISSUE #120652: DB Console: Add Replication Lag chart
We should add observability for the replication lag in PCR (current time - replicated time, where the src and dst cluster are exactly the same). Since replication lag is essentially the RPO for customers, we should surface this metric, ideally as a chart on the cluster replication dashboard.

This will require rendering computed difference between the wall time and the reported replicated time, since we can only reliably export the replicated time, not the difference. We do not export the computed difference because doing so is susceptible to failing in the worst possible way if the code updating this metric fails/gets stuck/crashes, in that it if it stopped replicating, the replicated time is not advancing and the observed lag should _increase_ but if the metric keeps export the last reported value of lag, before it got stuck, it would misleadingly look fine.

Jira issue: CRDB-36680

Jira issue: CRDB-36805

### PR DESCRIPTION
**Pull request by kev-cao**
There currently does not exist observability for replication lag in PCR in the DB Console. As replication lag is essentially RPO for customers, this metric should be made available to them in the dashboard. This commit adds the metric as the difference between the wall time and the reported replicated time.

Fixes #120652

Release note (ui change): Added observability for PCR replication lag to the metrics dashboard

### CODE REVIEW

File: pkg/ui/workspaces/db-console/src/views/cluster/containers/nodeGraphs/dashboards/crossClusterReplication.tsx [hunk 1]
```diff
@@ -48,5 +49,32 @@ export default function (props: GraphDashboardProps) {
...
+      tooltip={`Replication lag between primary and standby cluster`}
+    >
+      <Axis units={AxisUnits.Duration} label="duration">
+        <Metric
+          downsampler={TimeSeriesQueryAggregator.MIN}
+          aggregator={TimeSeriesQueryAggregator.AVG}
+          name="cr.node.physical_replication.replicated_time_seconds"
+          title="Replication Lag"
+          transform={datapoints =>
+            datapoints.map(d =>
```
Comment (xinhaoz) [inline pkg/ui/workspaces/db-console/src/views/cluster/containers/nodeGraphs/dashboards/crossClusterReplication.tsx:65]: Do we need to wrap this in a `map`? `transform` seems to be equivalent to `map` so we can just pass the inner function here.

Comment (xinhaoz) [inline pkg/ui/workspaces/db-console/src/views/cluster/containers/nodeGraphs/dashboards/crossClusterReplication.tsx:65]: `Do we need to wrap this in a `map`? `transform` seems to be equivalent to `map` so we can just pass the inner function here.

Comment (kev-cao) [reply pkg/ui/workspaces/db-console/src/views/cluster/containers/nodeGraphs/dashboards/crossClusterReplication.tsx:65]: There's a use-case where we may want to do more than just a `map`. For instance, we just finished up some discussion on the replication lag metric where we want to filter out `replicated_time_seconds` with a value of `0` (as during the initial scan phase).

We could add separate props for `filter` and `map`, but I figured that having a general purpose `transform` may be better. Thoughts?

Comment (xinhaoz) [reply pkg/ui/workspaces/db-console/src/views/cluster/containers/nodeGraphs/dashboards/crossClusterReplication.tsx:65]: Gotcha. I don't have a strong preference here so sgtm!

**Review by xinhaoz — APPROVED** [review]

**Comment by kev-cao** [comment]
TFTR!

bors r=xinhaoz

**Comment by kev-cao** [comment]
bors r=xinhaoz
