### PR TITLE
sql/schemachanger: fix incorrect clean up of sequence ownership

### LINKED ISSUE #151925: sql/schemachanger: sequence is not dropped with table
**Describe the problem**

Sequence should be dropped when table is dropped. On dropping the table, the sequence remains and when the sequence is dropped we receive:  `ERROR: cannot drop sequence id_seq because other objects depend on it.` I believe is OWNED BY  us supposed to prevent this from happening. 

**To Reproduce**
```
CREATE TABLE t1 (
            id BIGSERIAL NOT NULL
        );
set autocommit_before_ddl=on;
CREATE SEQUENCE id_seq OWNED BY t1.id;
ALTER TABLE t1 ALTER COLUMN id SET DEFAULT nextval('id_seq');
drop table t1;
show tables;
```
7. Sequence is still there.

**Expected behavior**
Sequence is gone.

Jira issue: CRDB-53539

Epic CRDB-49398

### PR DESCRIPTION
**Pull request by fqazi**
Previously, when a default expression was cleaned up the sequence ownerships would be incorrectly cleaned up. This meant when we added support for setting default expressions in the declarative schema changer, any updates could wipe out sequence ownership information. To address this, this patch removes the incorrect clean up logic.

Fixes: #151925

Release note (bug fix): Updating column default expressions would incorrectly remove sequence ownerships for the affected column.

### CODE REVIEW

File: pkg/sql/logictest/testdata/logic_test/sequences [hunk 1]
```diff
@@ -2536,3 +2536,25 @@ SELECT substring(sequence_schema FOR 7), sequence_name FROM [SHOW SEQUENCES] WHE
...
+CREATE SEQUENCE id_seq_owned OWNED BY t_seq_owner.id;
+
+statement ok
+ALTER TABLE t_seq_owner ALTER COLUMN id SET DEFAULT nextval('id_seq_owned');
+
+statement ok
+drop table t_seq_owner;
+
+query I
+SELECT count(*) FROM [SHOW TABLES] WHERE table_name='id_seq_owned'
```
Comment (rafiss) [inline pkg/sql/logictest/testdata/logic_test/sequences]: can we look at the `pg_sequences` table instead? and let's also make sure `t_seq_owner_id_seq` got cleaned up.

File: pkg/sql/schemachanger/scexec/scmutationexec/helpers.go [hunk 2]
```diff
@@ -280,7 +280,6 @@ func updateColumnExprSequenceUsage(d *descpb.ColumnDescriptor) error {
 		ids.ForEach(all.Add)
 	}
 	d.UsesSequenceIds = all.Ordered()
-	d.OwnsSequenceIds = all.Ordered()
```
Comment (rafiss) [inline pkg/sql/schemachanger/scexec/scmutationexec/helpers.go:283]: one thing i'm wondering is if we need to special case IDENTITY columns. aren't those implemented with a default expression, and the column should own the backing sequence? or is that handled separately? (since tests passed i assume it's fine, but i'm just curious.)

**Review by rafiss — CHANGES_REQUESTED** [review]

File: pkg/sql/schemachanger/scexec/scmutationexec/helpers.go (hunk 2 above)
Comment (fqazi) [reply pkg/sql/schemachanger/scexec/scmutationexec/helpers.go:283]: So, for identity columns the default expression is unmodifiable without doing DROP IDENTITY. When you do a DROP IDENTITY operation that is responsible for cleaning up the sequence too.

File: pkg/sql/logictest/testdata/logic_test/sequences (hunk 1 above)
Comment (fqazi) [reply pkg/sql/logictest/testdata/logic_test/sequences]: Done.

**Review by fqazi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/151947)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @rafiss)

**Review by rafiss — APPROVED** [review]

**Comment by fqazi** [comment]
@rafiss TFTR!

bors r+
