### PR TITLE
raft: bump proposal timeout for TestNodeProposeWaitDropped

### LINKED ISSUE #129967: raft: TestNodeProposeWaitDropped failed
raft.TestNodeProposeWaitDropped [failed](https://tanzanite.cluster.engflow.com/invocations/default/3816f2eb-7981-4e9c-9412-4389178172ca?testReportRun=21&testReportShard=1&testReportAttempt=1#targets-Ly9wa2cvcmFmdDpyYWZ0X3Rlc3Q=) on release-24.2 @ [14962dfb7274e11754658d4fa2be32a1dd31b94b](https://github.com/cockroachdb/cockroach/commits/14962dfb7274e11754658d4fa2be32a1dd31b94b):

```
=== RUN   TestNodeProposeWaitDropped
raft2024/09/01 04:12:55 INFO: 1 switched to configuration voters=(1)
raft2024/09/01 04:12:55 INFO: 1 became follower at term 0
raft2024/09/01 04:12:55 INFO: newRaft 1 [peers: [1], term: 0, commit: 0, applied: 0, lastindex: 0, lastterm: 0]
raft2024/09/01 04:12:55 INFO: 1 is starting a new election at term 0
raft2024/09/01 04:12:55 INFO: 1 became candidate at term 1
raft2024/09/01 04:12:55 INFO: 1 received MsgVoteResp from 1 at term 1
raft2024/09/01 04:12:55 INFO: 1 has received 1 MsgVoteResp votes and 0 vote rejections
raft2024/09/01 04:12:55 INFO: 1 became leader at term 1
raft2024/09/01 04:12:55 INFO: raft.node: 1 elected leader 1 at term 1
    node_test.go:379: 
        	Error Trace:	github.com/cockroachdb/cockroach/pkg/raft/node_test.go:379
        	Error:      	Not equal: 
        	            	expected: *errors.errorString(&errors.errorString{s:"raft proposal dropped"})
        	            	actual  : context.deadlineExceededError(context.deadlineExceededError{})
        	Test:       	TestNodeProposeWaitDropped
    node_test.go:348: dropping message: type:MsgProp to:0 from:1 term:0 logTerm:0 index:0 entries:<Term:0 Index:0 Type:EntryNormal Data:"test_dropping" > commit:0 vote:0 reject:false rejectHint:0 match:0 
--- FAIL: TestNodeProposeWaitDropped (0.13s)
```

Parameters:
 - <code>attempt=1</code>
 - <code>run=21</code>
 - <code>shard=1</code>
<details><summary>Help</summary>
<p>

See also: [How To Investigate a Go Test Failure \(internal\)](https://cockroachlabs.atlassian.net/l/c/HgfXfJgM)
</p>
</details>
/cc @cockroachdb/kv
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*TestNodeProposeWaitDropped.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/bazci/githubpost/issues)
</sub>

Jira issue: CRDB-41809

### PR DESCRIPTION
**Pull request by arulajmani**
In some rare cases, we see context cancellation race with the proposal being dropped (#129967, #128878). Up the context cancellation deadline 10x to hopefully prevent this, while still not causing the test to hang indefinitely.

closes https://github.com/cockroachdb/cockroach/issues/129967

Release note: None

### CODE REVIEW

File: pkg/raft/node_test.go [hunk 1]
```diff
@@ -375,7 +375,7 @@ func TestNodeProposeWaitDropped(t *testing.T) {
 		}
 		n.Advance()
 	}
-	proposalTimeout := time.Millisecond * 100
+	proposalTimeout := time.Second
```
Comment (pav-kv) [inline pkg/raft/node_test.go:378]: Do we need this timeout in the first place? The code seems to expect that dropping must happen, so we might be ok to timeout the test if it doesn't happen.

I wonder if there is a race here which results in this proposal never being dropped (whichever the timeout is). This race could be the thing to fix then.

Comment (arulajmani) [reply pkg/raft/node_test.go:378]: > I wonder if there is a race here which results in this proposal never being dropped (whichever the timeout is). This race could be the thing to fix then.

I don't think that's the case; we see log lines indicating that the proposal was dropped when the timeout fires.

Comment (arulajmani) [reply pkg/raft/node_test.go:378]: > Do we need this timeout in the first place? The code seems to expect that dropping must happen, so we might be ok to timeout the test if it doesn't happen.

Sorry I didn't reply to this part. You're right, in that we don't strictly need the timeout. I think it just fails the test faster. I'm open to removing the thing if you prefer that approach over this one.

Comment (pav-kv) [reply pkg/raft/node_test.go:378]: Yeah, let's try removing the timeout.

The race I have in mind is:
1. `r.step = dropStep` sets the handler.
2. But before we get to `n.Propose` a couple of lines below, the `RawNode` transitions to some other state (e.g. it steps down from leadership) and resets `r.step` to a function that does not drop proposals.

I'm not sure if (2) can happen, but if it can then that would be the root cause here. We'll find this out if the tests fails again after removing the timeout.

Comment (pav-kv) [reply pkg/raft/node_test.go:378]: OTOH, if (2) was the case, then `n.Propose` would return early rather than with a timeout. It's probably just a timing issue.

Comment (arulajmani) [reply pkg/raft/node_test.go]: I removed the timeout. RFAL.

**Review by pav-kv — APPROVED** [review]

**Comment by arulajmani** [comment]
Thanks Pavel. 

bors r=pav-kv
