### PR TITLE
sql/parser: impure functions are not constant

### LINKED ISSUE #2403: sql: order by gets confused by nullary functions
```sql
Tamirs-MacBook-Pro.local:8080> select * from descriptor order by RANDOM();
query error: invalid ORDER BY: 0.39028524628024286
```

### PR DESCRIPTION
**Pull request by tamird**
Fixes #2403.

### CODE REVIEW

File: sql/parser/normalize.go [hunk 1]
```diff
@@ -353,10 +353,17 @@ var _ Visitor = &isConstVisitor{}
...
 func (v *isConstVisitor) Visit(expr Expr, pre bool) (Visitor, Expr) {
 	if pre && v.isConst {
-		switch expr.(type) {
+		switch t := expr.(type) {
 		case DReference, *ExistsExpr, *QualifiedName, *Subquery, ValArg:
 			v.isConst = false
 			return nil, expr
+		case *FuncExpr:
+			// We need to type check this guy to make sure `fn` is populated.
+			_, _ = typeCheckFuncExpr(t)
```
Comment (petermattis) [inline sql/parser/normalize.go]: Should you be ignoring the error here? Seems like `t.fn` won't be filled in correctly in which case I think you should set `v.isConst = false`.

File: sql/parser/normalize_test.go [hunk 2]
```diff
@@ -72,6 +72,7 @@ func TestNormalizeExpr(t *testing.T) {
 		{`1=a/2`, `a = 2`},
 		{`a=lower('FOO')`, `a = 'foo'`},
 		{`lower(a)='foo'`, `lower(a) = 'foo'`},
+		{`random()`, `random()`},
```
Comment (petermattis) [inline sql/parser/normalize_test.go]: I'd really like to see a test in `testdata/order_by` and perhaps one in `testdata/builtin` as well. This is tricky because `random()` is not deterministic. But I think we should fix that by allowing an optional seed argument to `random()`. File an issue if you don't want to do this in this PR.

File: sql/parser/normalize.go (hunk 1 above)
Comment (tamird) [inline sql/parser/normalize.go]: fixed

File: sql/parser/normalize.go [hunk 3]
```diff
@@ -371,9 +377,14 @@ func isConst(expr Expr) bool {
 }
 
 func isVar(expr Expr) bool {
-	switch expr.(type) {
+	switch t := expr.(type) {
 	case DReference, *ExistsExpr, *QualifiedName, *Subquery, ValArg:
 		return true
+	case *FuncExpr:
```
Comment (petermattis) [inline sql/parser/normalize.go]: Can you expand on why this is necessary? I understand the `isConstVisitor` check, but this one seems suspicious.

**Comment by petermattis** [comment]
LGTM

File: sql/parser/normalize.go (hunk 3 above)
Comment (tamird) [inline sql/parser/normalize.go]: just a mistake. removed.

File: sql/parser/normalize_test.go (hunk 2 above)
Comment (tamird) [inline sql/parser/normalize_test.go]: done! PTAL

**Comment by petermattis** [comment]
LGTM

File: sql/parser/builtins.go [hunk 4]
```diff
@@ -311,10 +312,19 @@ var builtins = map[string][]builtin{
...
 			fn: func(args DTuple) (Datum, error) {
 				return DFloat(rand.Float64()), nil
 			},
 		},
+		builtin{
+			types:      typeList{intType},
+			returnType: DummyFloat,
+			impure:     true,
+			fn: func(args DTuple) (Datum, error) {
+				return DFloat(rand.New(rand.NewSource(int64(args[0].(DInt)))).Float64()), nil
```
Comment (bdarnell) [inline sql/parser/builtins.go]: Won't this produce the same random number for every row? (we need a test that `order by random(5)` produces different results from `order by random(6)`) `random(seed)` needs to construct the RNG once per query and then evaluate it once per row. I'm not sure it's worth trying to fit this special case into our execution model just for testing.

Comment (tamird) [inline sql/parser/builtins.go]: Yeah, that's quite a special case. I guess I'll back this out.

Comment (tamird) [inline sql/parser/builtins.go]: done

Comment (petermattis) [inline sql/parser/builtins.go]: Yeah, the implementation was busted and it doesn't seem easy to fix with our current eval infrastructure.
