### PR TITLE
storage: make average diversity score for diversityRemovalScore

### LINKED ISSUE #17479: storage: Diversity scores not working as intended in allocator
Diversity scores aren't working well for properly spreading replicas around different localities in indigo. All the nodes are well-balanced across all dimensions, but close to half of all ranges have two replicas in the same locality (and one locality without a replica). This looks like it was broken even before #16878, but it's probably a bit worse now because ad9e5523f2ab54075bbc7861390eabc22765cd22 separated out the converge score from the constraint score, so there's no chance for the possibility of convergence to help us do the right thing anymore.

There are two problems here, one really easy to fix and one I still need to think about a little more.

1. When considering a rebalance, we use one diversity score method for existing replicas and a different one for other replicas. We consider an existing replica to have good diversity if we can remove it and the range will still be diverse, but we only consider a new replica diverse if it doesn't overlap with any existing replica's locality. That means that we never choose to rebalance from one node in a locality to another node in the same locality. This is easy to fix.
1. `diversityRemovalScore` doesn't seem to do what we want. It returns the max diversity of any remaining pair of replicas in a range. That means that if a range has 6 replicas (say it's down-replicating from 6 to 5) in localities [a, b, c, c, c, c] respectively, it'll consider all replicas to be equally valid for removal because no matter which one is removed, there will still be a pair of replicas with no locality tiers in common. To a human, this seems like an obviously bad choice. We may want to do something like average locality remaining after removing a replica to ensure that in cases like this we'd pick one of the replicas in locality c to remove.

Or maybe it's just fundamentally a bad idea to prioritize diversity over all other aspects of balance. If one locality has significantly more capacity than another, perhaps it would be better to keep all the replicas in `c` and remove one of the ones in `a` or `b`. I don't think that's going to be the case in most deployments, though.

### PR DESCRIPTION
**Pull request by a6802739**
Fixes #17479.

@a-robinson, I didn't use `diversityRemovalAverageScore` to replace `diversityRemovalScore` in `rebalanceCandidates`.

If I replace it, it will fail in the test `TestReplicateQueueRebalance`.

### CODE REVIEW

File: pkg/storage/allocator_scorer_test.go [hunk 1]
```diff
@@ -703,51 +704,51 @@ func TestDiversityRemovalScore(t *testing.T) {
 		{
 			name: "four existing replicas",
 			expected: map[roachpb.StoreID]float64{
-				testStoreUSa15:  1.0 / 4.0,
-				testStoreUSa1:   1.0 / 4.0,
-				testStoreUSb:    1.0 / 2.0,
-				testStoreEurope: 1,
+				testStoreUSa15:  1.0 / (1.0 + (2.0*(0.5+1.0+1.0))/6.0),
```
Comment (a-robinson) [inline pkg/storage/allocator_scorer_test.go]: With how complicated these numbers are getting, it may be better to just specify the expected ordering of diversity scores for the replicas (e.g. `USa15 > USa1 > USb > Europe`)

File: pkg/storage/allocator_scorer_test.go [hunk 2]
```diff
@@ -693,7 +694,7 @@ func TestRebalanceToDiversityScore(t *testing.T) {
 	}
 }
 
-func TestDiversityRemovalScore(t *testing.T) {
+func TestDiversityRemovalAverageScore(t *testing.T) {
```
Comment (a-robinson) [inline pkg/storage/allocator_scorer_test.go]: We're going to need a new test (or a restructuring of this test) in order to actually test the kinds of configurations that motivated #17479 in the first place, since this test isn't set up to handle multiple replicas being in the same locality.

File: pkg/storage/allocator_scorer.go [hunk 3]
```diff
@@ -733,6 +733,34 @@ func diversityRemovalScore(
...
+		}
+		for anotherNodeID, anotherLocality := range existingNodeLocalities {
+			if anotherNodeID == nodeID || anotherNodeID == otherNodeID {
+				continue
+			}
+			newScore := anotherLocality.DiversityScore(otherLocality)
+			sumScore += newScore
+		}
+	}
+	if len(existingNodeLocalities) < 3 {
```
Comment (a-robinson) [inline pkg/storage/allocator_scorer.go]: Could you explain this way of getting the average? It's pretty obtuse, and seeing the magic numbers here scares me.

**Review by a-robinson — COMMENTED** [review]
Before moving ahead with this, we need to understand why it's failing `TestReplicateQueueRebalance`, since that's probably a sign that it's not working right.

Also, adding yet another diversity method without being able to get rid of an old one is a bit troubling. We already have three different ways of calculating diversity, and the more we add the more likely we are to run into situations where their differences cause problems in a real cluster.

File: pkg/storage/allocator_scorer.go (hunk 3 above)
Comment (a6802739) [reply pkg/storage/allocator_scorer.go]: Sorry.  I'm afraid `num - 1` to be zero, so I need to make sure `len(existingNodeLocalities)` is bigger than three, then we could use the formula below.
```
1.0 / (1.0 + sumScore/float64(num*(num-1)))
```

File: pkg/storage/allocator_scorer_test.go (hunk 2 above)
Comment (a6802739) [reply pkg/storage/allocator_scorer_test.go]: Yeah, I will add a test for #17479.

File: pkg/storage/allocator_scorer_test.go (hunk 1 above)
Comment (a6802739) [reply pkg/storage/allocator_scorer_test.go]: Yeah, that's better idea.

File: pkg/storage/allocator_scorer.go (hunk 3 above)
Comment (a-robinson) [reply pkg/storage/allocator_scorer.go]: Never returning a score of zero seems bad, since currently we use the entire range `[0,1]` and return the score of 0 quite frequently if all replicas are in the same locality. This is also more complicated than it needs to be. How about we just simplify this method to look more like:

```go
var sumScore float64
var numSamples int
for ... {
  if ... { continue }
  for ... {
    if ... { continue }
    sumScore += ...
    numSamples++
  }
}
if numSamples == 0 {
  return 1.0
}
return sumScore / float64(numSamples)
```

**Comment by BramGruneir** [comment]
The more we play with diversity scores, the more I think they deserve a full RFC.  Ad hoc changes are just going to complicate the reasoning around them, and I'm certain that the current test suite does not adequately cover all strange cases of them.

**Comment by a-robinson** [comment]
Agreed (https://github.com/cockroachdb/cockroach/issues/17603)

File: pkg/storage/allocator_scorer.go (hunk 3 above)
Comment (a6802739) [reply pkg/storage/allocator_scorer.go]: Hmm, I think `sumScore / float64(numSamples)` will be the inverse order with `diversityScore`, 
right?

Comment (a-robinson) [reply pkg/storage/allocator_scorer.go]: I'm not sure what you mean. Can you explain? I could be mistaken, but it certainly looks like `sumScore / float64(numSamples)` will return the average diversity score of all pairs of replicas. That'll be different from the `diversityScore` function on line 703 of this file, but being different from that was intended.

Either way, as @BramGruneir mentioned, adding more diversity score logic without a high-level plan for what the end state should be is just creating more work for ourselves. We should focus on getting that plan before worrying too much about the details of this PR.

Comment (a6802739) [reply pkg/storage/allocator_scorer.go]: Sorry, My bad expression.

when `diversityScore` is much bigger, which means the specified Node will be a better fit for the `Range`. But for `averageDiversityScore`, when it's much bigger, it means the specified Node will be a worse fit for the `Range`.

Yeah, I understand we should process the definition of `diversityScore` to avoid confusion, so what we should do is write down all the case we have been involved with `diversityScore`, right?

Comment (a-robinson) [reply pkg/storage/allocator_scorer.go]: > so what we should do is write down all the case we have been involved with diversityScore, right?

Yeah, the plan should cover all uses of diversity within the allocator.

**Comment by a6802739** [comment]
@a-robinson , I just list all the `diversityScore` we would used in 3 cases.

* diversityAddScore : used for `allocateCandidates`, when we try to add a replica for specified range. 
we could just calculate the the average diversity score if we add a replica to the specified target store.
just like:

```
func diversityAddScore(
	targetStore roachpb.StoreDescriptor, existingNodeLocalities map[roachpb.NodeID]roachpb.Locality,
) float64 {
```

*diversityRemovalScore : used for `removeCandidates`, when we try to remove a replica for specified range.
we could just calculate the the average diversity score if we remove a replica to the specified target store.
just like:
```
func diversityAddScore(
	targetStore roachpb.StoreDescriptor, existingNodeLocalities map[roachpb.NodeID]roachpb.Locality,
) float64 {
```


*diversityRebalanceScore : it's a little complicated, when we try to add a replica for the specified range, 
I wonder if we should consider the replica which we'll remove later. We should combine these two steps together, 
or we just consider this as two single steps. if we combine these two steps together, we could first get the ordered
`existingCandidates` in `rebalanceCandidates`, and then calculate the average diversity score if we rebalance to a candidate
and then remove the worst candidate from `existingCandidates`. just like :

```
func rebalanceToDiversityScore(
	removalTagetStore, rebalanceTargetStore roachpb.StoreDescriptor, existingNodeLocalities map[roachpb.NodeID]roachpb.Locality,
) float64 {

```

**Comment by a-robinson** [comment]
> diversityRebalanceScore : it's a little complicated, when we try to add a replica for the specified range, I wonder if we should consider the replica which we'll remove later.

Yeah, that's what I was thinking as well. Getting the rebalance scoring right is the most important part, since it's what could cause thrashing if we get it wrong. Some refactoring will be probably be required.

The other important point to consider is whether the pairwise average is really the best way of computing the diversity of a list of replica localities. Experimenting with it a little bit seems worthwhile - you may want to try running it against all sorts of different locality lists and making sure the results line up with your intuition of which lists have better diversity. If you could share that experiment/output, it'd be useful to record in a unit test and/or github.

**Comment by a6802739** [comment]
@a-robinson, I have changed `diversityScore` to three methods:

*`diversityAllocateScore`:  used for `allocateCandidates`. And add a test `TestAllocatorAllocateTargetLocality` for it.

*`diversityRemovalScore`: used for `removeCandidates`. And add a test `TestAllocatorRemoveTargetLocality` for it.

*`diversityRebalanceScore`: used for `rebalanceCandidates`. And add a test 
`TestAllocatorRebalanceTargetLocality` for it.

File: pkg/storage/allocator_scorer.go [hunk 4]
```diff
@@ -697,63 +705,74 @@ func constraintCheck(store roachpb.StoreDescriptor, constraints config.Constrain
...
-// rebalanceToDiversityScore is like diversityScore, but it returns what
-// the diversity score would be if the given store was added and one of the
-// existing stores was removed. This is equivalent to the second lowest score.
-//
-// This is useful for considering rebalancing a range that already has enough
-// replicas - it's perfectly fine to add a replica in the same locality as an
-// existing replica in such cases.
-func rebalanceToDiversityScore(
-	store roachpb.StoreDescriptor, existingNodeLocalities map[roachpb.NodeID]roachpb.Locality,
+// diversityRebalanceScore is a little complicated, we should coalesce the upcoming removing
```
Comment (a-robinson) [inline pkg/storage/allocator_scorer.go]: I'd replace this first sentence with "diversityRebalanceScore calculates what the range's average diversity score would be if removeStore was removed from the range and rebalanceStore was added to it."

File: pkg/storage/allocator_scorer.go [hunk 5]
```diff
@@ -697,63 +705,74 @@ func constraintCheck(store roachpb.StoreDescriptor, constraints config.Constrain
...
-	for _, locality := range existingNodeLocalities {
-		newScore := store.Node.Locality.DiversityScore(locality)
-		if newScore < minScore {
-			nextMinScore = minScore
-			minScore = newScore
-		} else if newScore < nextMinScore {
-			nextMinScore = newScore
+	var sumScore float64
+	var numSamples int
+	for nodeID, locality := range existingNodeLocalities {
```
Comment (a-robinson) [inline pkg/storage/allocator_scorer.go]: I'm not convinced that it's sufficient to only count the average diversity of the new replica against all the existing ones, because the choice of `removeStore` affects the average diversity as well. Can you explain/justify why this is correct?

I kind of expected us to just do a pairwise computation over all the replicas that would be in the resulting range. That'd be much easier to understand without being slower enough to matter. I think we should switch to that unless there's some reasoning I'm not seeing. Honestly, I think we'd be best off just doing that for all three of these functions for the sake of clarity.

**Comment by a-robinson** [comment]
Reviewed 1 of 3 files at r2.
Review status: 1 of 3 files reviewed at latest revision, 12 unresolved discussions, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/19486)*

File: pkg/storage/allocator_scorer.go [hunk 6]
```diff
@@ -697,63 +705,74 @@ func constraintCheck(store roachpb.StoreDescriptor, constraints config.Constrain
...
+	// We didn't calculate the overall diversityScore for the range, because the original overall diversityScor
+	// of this range is always the same.
 	for otherNodeID, otherLocality := range existingNodeLocalities {
 		if otherNodeID == nodeID {
 			continue
 		}
-		if newScore := otherLocality.DiversityScore(locality); newScore < minScore {
-			minScore = newScore
-		}
+		newScore := locality.DiversityScore(otherLocality)
```
[the remark this answers is not in the document]
Comment (a6802739) [reply pkg/storage/allocator_scorer.go]: Hmm... How about I add the comment like

```
We have no need the calculate the overall diversityScore after we remove the replica on `nodeID`, because the overall diversityScore of this range is always the same, we just calculate the diversityScore between the `nodeID` and other replicas for this range.
```

File: pkg/storage/allocator_scorer.go [hunk 7]
```diff
@@ -697,63 +705,74 @@ func constraintCheck(store roachpb.StoreDescriptor, constraints config.Constrain
...
+		sumScore += newScore
+		numSamples++
 	}
-	return minScore
+	if numSamples == 0 {
+		return 0
```
[the remark this answers is not in the document]
Comment (a6802739) [reply pkg/storage/allocator_scorer.go]: When this range has no replicas, from my understanding, it couldn't remove any replica, so I set it to `0`.

File: pkg/storage/allocator_scorer.go (hunk 5 above)
Comment (a6802739) [reply pkg/storage/allocator_scorer.go]: For `diversityRebalanceScore`, If we have known the `removeStore`, what we need to do is to find the best rebalance target, it's just like `diversityAllocateScore`, but when we calculate the diversityScore, we just kick out the `removeStore`.

File: pkg/storage/allocator_scorer.go [hunk 8]
```diff
@@ -519,7 +529,7 @@ func rebalanceCandidates(
 					s, rangeInfo, balanceScore, sl)
 				continue
 			}
-			diversityScore := rebalanceToDiversityScore(s, existingNodeLocalities)
+			diversityScore := diversityRebalanceScore(existingCandidates[len(existingCandidates)-1].store, s, existingNodeLocalities)
```
[the remark this answers is not in the document]
Comment (a6802739) [reply pkg/storage/allocator_scorer.go]:
```
It seems likely that there are subtle issues here where the addition of the new candidate to the range could change which existing candidate would be chosen for removal.
```
Sorry, I couldn't quite understand what do you mean here. Yes, I'm just wondering the case if we will not remove the worst store from the existing replicas. We could make sure we'll not remove the replica we just rebalance to.

[the remark this answers is not in the document]
Comment (a-robinson) [reply pkg/storage/allocator_scorer.go]: Here's one of many potential examples. I'm sure there are more complicated ones, this is just the first that came to mind:

existing replica localities:
1. a=1,b=1,c=1
2. a=1,b=2,c=1
3. a=2,b=1,c=1

localities of possible rebalance candidates:
4. a=1,b=1,c=1
5. a=1,b=1,c=2

Since replicas 1 and 2 have equal diversity scores, we'll randomly choose one of them to consider the worst (ignoring which one of their stores is more loaded, which isn't relevant to this example). If we choose to remove replica 2, then we'll end up picking replica 5 to replace it. However, notice that this is actually hurting the diversity of the range. It'd be much better to remove replica 1 and replace it with either of 4 or 5.

File: pkg/storage/allocator_scorer.go (hunk 6 above)
[the remark this answers is not in the document]
Comment (a-robinson) [reply pkg/storage/allocator_scorer.go]: I don't know how you choose to think about it, but my intuition around why taking this shortcut is ok is that it's because the replica with the worst average diversityScore is the one that's dragging down the range's overall diversityScore the most.

File: pkg/storage/allocator_scorer.go (hunk 7 above)
[the remark this answers is not in the document]
Comment (a-robinson) [reply pkg/storage/allocator_scorer.go]: But 1 means that the replica is a good fit, while 0 means it's a bad fit.

**Review by a-robinson — COMMENTED** [review]
Did you do any comparisons to alternative approaches of measuring diversity? @BramGruneir and I are a bit concerned that we settled on this approach without thinking things through very fully, e.g. not writing an RFC or comparing why this is better than alternative approaches.

**Comment by a6802739** [comment]
@a-robinson, I have add more test case for this PR, See https://github.com/a6802739/cockroach/pull/3/files.
Then I list the comparison test results between old methods and new methods as below.

***diversityRemovalScore
old Method result:
```
=== RUN   TestRemoveDiversityScore
=== RUN   TestRemoveDiversityScore/case_1
case 1, store 1 removal diversity score 0.500000
case 1, store 2 removal diversity score 0.500000
case 1, store 3 removal diversity score 0.500000
=== RUN   TestRemoveDiversityScore/case_2
case 2, store 1 removal diversity score 0.500000
case 2, store 2 removal diversity score 0.500000
case 2, store 5 removal diversity score 1.000000
=== RUN   TestRemoveDiversityScore/case_3
case 3, store 1 removal diversity score 1.000000
case 3, store 5 removal diversity score 1.000000
case 3, store 9 removal diversity score 1.000000
=== RUN   TestRemoveDiversityScore/case_4
case 4, store 1 removal diversity score 0.500000
case 4, store 2 removal diversity score 0.500000
case 4, store 3 removal diversity score 0.500000
case 4, store 4 removal diversity score 0.500000
=== RUN   TestRemoveDiversityScore/case_5
case 5, store 1 removal diversity score 0.500000
case 5, store 2 removal diversity score 0.500000
case 5, store 3 removal diversity score 0.500000
case 5, store 5 removal diversity score 1.000000
=== RUN   TestRemoveDiversityScore/case_6
case 6, store 1 removal diversity score 0.500000
case 6, store 2 removal diversity score 0.500000
case 6, store 5 removal diversity score 0.500000
case 6, store 6 removal diversity score 0.500000
=== RUN   TestRemoveDiversityScore/case_7
case 7, store 1 removal diversity score 0.500000
case 7, store 2 removal diversity score 0.500000
case 7, store 5 removal diversity score 1.000000
case 7, store 9 removal diversity score 1.000000
=== RUN   TestRemoveDiversityScore/case_8
case 8, store 1 removal diversity score 0.500000
case 8, store 2 removal diversity score 0.500000
case 8, store 3 removal diversity score 0.500000
case 8, store 4 removal diversity score 0.500000
case 8, store 5 removal diversity score 1.000000
=== RUN   TestRemoveDiversityScore/case_9
case 9, store 1 removal diversity score 0.500000
case 9, store 2 removal diversity score 0.500000
case 9, store 3 removal diversity score 0.500000
case 9, store 5 removal diversity score 0.500000
case 9, store 6 removal diversity score 0.500000
=== RUN   TestRemoveDiversityScore/case_10
case 10, store 1 removal diversity score 0.500000
case 10, store 2 removal diversity score 0.500000
case 10, store 5 removal diversity score 0.500000
case 10, store 6 removal diversity score 0.500000
case 10, store 9 removal diversity score 1.000000
=== RUN   TestRemoveDiversityScore/case_11
case 11, store 1 removal diversity score 0.500000
case 11, store 2 removal diversity score 0.500000
case 11, store 3 removal diversity score 0.500000
case 11, store 4 removal diversity score 0.500000
case 11, store 5 removal diversity score 0.500000
case 11, store 6 removal diversity score 0.500000
=== RUN   TestRemoveDiversityScore/case_12
case 12, store 1 removal diversity score 0.500000
case 12, store 2 removal diversity score 0.500000
case 12, store 3 removal diversity score 0.500000
case 12, store 5 removal diversity score 0.500000
case 12, store 6 removal diversity score 0.500000
case 12, store 9 removal diversity score 1.000000
=== RUN   TestRemoveDiversityScore/case_13
case 13, store 1 removal diversity score 0.500000
case 13, store 2 removal diversity score 0.500000
case 13, store 3 removal diversity score 0.500000
case 13, store 5 removal diversity score 0.500000
case 13, store 6 removal diversity score 0.500000
case 13, store 9 removal diversity score 1.000000
=== RUN   TestRemoveDiversityScore/case_14
case 14, store 1 removal diversity score 0.500000
case 14, store 2 removal diversity score 0.500000
case 14, store 3 removal diversity score 0.500000
case 14, store 4 removal diversity score 0.500000
case 14, store 5 removal diversity score 0.500000
case 14, store 6 removal diversity score 0.500000
case 14, store 7 removal diversity score 0.500000
=== RUN   TestRemoveDiversityScore/case_15
case 15, store 1 removal diversity score 0.500000
case 15, store 2 removal diversity score 0.500000
case 15, store 5 removal diversity score 0.500000
case 15, store 6 removal diversity score 0.500000
case 15, store 7 removal diversity score 0.500000
case 15, store 9 removal diversity score 0.500000
case 15, store 10 removal diversity score 0.500000
```

New Menthod result:
```
=== RUN   TestRemoveDiversityScore
=== RUN   TestRemoveDiversityScore/case_1
case 1, store 1 removal diversity score 0.500000
case 1, store 2 removal diversity score 0.500000
case 1, store 3 removal diversity score 0.500000
=== RUN   TestRemoveDiversityScore/case_2
case 2, store 1 removal diversity score 0.750000
case 2, store 2 removal diversity score 0.750000
case 2, store 5 removal diversity score 1.000000
=== RUN   TestRemoveDiversityScore/case_3
case 3, store 1 removal diversity score 1.000000
case 3, store 5 removal diversity score 1.000000
case 3, store 9 removal diversity score 1.000000
=== RUN   TestRemoveDiversityScore/case_4
case 4, store 1 removal diversity score 0.500000
case 4, store 2 removal diversity score 0.500000
case 4, store 3 removal diversity score 0.500000
case 4, store 4 removal diversity score 0.500000
=== RUN   TestRemoveDiversityScore/case_5
case 5, store 1 removal diversity score 0.666667
case 5, store 2 removal diversity score 0.666667
case 5, store 3 removal diversity score 0.666667
case 5, store 5 removal diversity score 1.000000
=== RUN   TestRemoveDiversityScore/case_6
case 6, store 1 removal diversity score 0.833333
case 6, store 2 removal diversity score 0.833333
case 6, store 5 removal diversity score 0.833333
case 6, store 6 removal diversity score 0.833333
=== RUN   TestRemoveDiversityScore/case_7
case 7, store 1 removal diversity score 0.833333
case 7, store 2 removal diversity score 0.833333
case 7, store 5 removal diversity score 1.000000
case 7, store 9 removal diversity score 1.000000
=== RUN   TestRemoveDiversityScore/case_8
case 8, store 1 removal diversity score 0.625000
case 8, store 2 removal diversity score 0.625000
case 8, store 3 removal diversity score 0.625000
case 8, store 4 removal diversity score 0.625000
case 8, store 5 removal diversity score 1.000000
=== RUN   TestRemoveDiversityScore/case_9
case 9, store 1 removal diversity score 0.750000
case 9, store 2 removal diversity score 0.750000
case 9, store 3 removal diversity score 0.750000
case 9, store 5 removal diversity score 0.875000
case 9, store 6 removal diversity score 0.875000
=== RUN   TestRemoveDiversityScore/case_10
case 10, store 1 removal diversity score 0.875000
case 10, store 2 removal diversity score 0.875000
case 10, store 5 removal diversity score 0.875000
case 10, store 6 removal diversity score 0.875000
case 10, store 9 removal diversity score 1.000000
=== RUN   TestRemoveDiversityScore/case_11
case 11, store 1 removal diversity score 0.700000
case 11, store 2 removal diversity score 0.700000
case 11, store 3 removal diversity score 0.700000
case 11, store 4 removal diversity score 0.700000
case 11, store 5 removal diversity score 0.900000
case 11, store 6 removal diversity score 0.900000
=== RUN   TestRemoveDiversityScore/case_12
case 12, store 1 removal diversity score 0.800000
case 12, store 2 removal diversity score 0.800000
case 12, store 3 removal diversity score 0.800000
case 12, store 5 removal diversity score 0.900000
case 12, store 6 removal diversity score 0.900000
case 12, store 9 removal diversity score 1.000000
=== RUN   TestRemoveDiversityScore/case_13
case 13, store 1 removal diversity score 0.800000
case 13, store 2 removal diversity score 0.800000
case 13, store 3 removal diversity score 0.800000
case 13, store 5 removal diversity score 0.900000
case 13, store 6 removal diversity score 0.900000
case 13, store 9 removal diversity score 1.000000
=== RUN   TestRemoveDiversityScore/case_14
case 14, store 1 removal diversity score 0.750000
case 14, store 2 removal diversity score 0.750000
case 14, store 3 removal diversity score 0.750000
case 14, store 4 removal diversity score 0.750000
case 14, store 5 removal diversity score 0.833333
case 14, store 6 removal diversity score 0.833333
case 14, store 7 removal diversity score 0.833333
=== RUN   TestRemoveDiversityScore/case_15
case 15, store 1 removal diversity score 0.916667
case 15, store 2 removal diversity score 0.916667
case 15, store 5 removal diversity score 0.833333
case 15, store 6 removal diversity score 0.833333
case 15, store 7 removal diversity score 0.833333
case 15, store 9 removal diversity score 0.916667
case 15, store 10 removal diversity score 0.916667
```

***diversityAllocateScore
Old Method result:
```
=== RUN   TestAllocateDiversityScore
=== RUN   TestAllocateDiversityScore/case_1
case 1, store 4 allocate diversity score 0.500000
case 1, store 5 allocate diversity score 1.000000
case 1, store 6 allocate diversity score 1.000000
case 1, store 7 allocate diversity score 1.000000
case 1, store 8 allocate diversity score 1.000000
case 1, store 9 allocate diversity score 1.000000
case 1, store 10 allocate diversity score 1.000000
case 1, store 11 allocate diversity score 1.000000
case 1, store 12 allocate diversity score 1.000000
=== RUN   TestAllocateDiversityScore/case_2
case 2, store 3 allocate diversity score 0.500000
case 2, store 4 allocate diversity score 0.500000
case 2, store 6 allocate diversity score 0.500000
case 2, store 7 allocate diversity score 0.500000
case 2, store 8 allocate diversity score 0.500000
case 2, store 9 allocate diversity score 1.000000
case 2, store 10 allocate diversity score 1.000000
case 2, store 11 allocate diversity score 1.000000
case 2, store 12 allocate diversity score 1.000000
=== RUN   TestAllocateDiversityScore/case_3
case 3, store 2 allocate diversity score 0.500000
case 3, store 3 allocate diversity score 0.500000
case 3, store 4 allocate diversity score 0.500000
case 3, store 6 allocate diversity score 0.500000
case 3, store 7 allocate diversity score 0.500000
case 3, store 8 allocate diversity score 0.500000
case 3, store 10 allocate diversity score 0.500000
case 3, store 11 allocate diversity score 0.500000
case 3, store 12 allocate diversity score 0.500000
=== RUN   TestAllocateDiversityScore/case_4
case 4, store 5 allocate diversity score 1.000000
case 4, store 6 allocate diversity score 1.000000
case 4, store 7 allocate diversity score 1.000000
case 4, store 8 allocate diversity score 1.000000
case 4, store 9 allocate diversity score 1.000000
case 4, store 10 allocate diversity score 1.000000
case 4, store 11 allocate diversity score 1.000000
case 4, store 12 allocate diversity score 1.000000
=== RUN   TestAllocateDiversityScore/case_5
case 5, store 4 allocate diversity score 0.500000
case 5, store 6 allocate diversity score 0.500000
case 5, store 7 allocate diversity score 0.500000
case 5, store 8 allocate diversity score 0.500000
case 5, store 9 allocate diversity score 1.000000
case 5, store 10 allocate diversity score 1.000000
case 5, store 11 allocate diversity score 1.000000
case 5, store 12 allocate diversity score 1.000000
=== RUN   TestAllocateDiversityScore/case_6
case 6, store 3 allocate diversity score 0.500000
case 6, store 4 allocate diversity score 0.500000
case 6, store 7 allocate diversity score 0.500000
case 6, store 8 allocate diversity score 0.500000
case 6, store 9 allocate diversity score 1.000000
case 6, store 10 allocate diversity score 1.000000
case 6, store 11 allocate diversity score 1.000000
case 6, store 12 allocate diversity score 1.000000
=== RUN   TestAllocateDiversityScore/case_7
case 7, store 3 allocate diversity score 0.500000
case 7, store 4 allocate diversity score 0.500000
case 7, store 6 allocate diversity score 0.500000
case 7, store 7 allocate diversity score 0.500000
case 7, store 8 allocate diversity score 0.500000
case 7, store 10 allocate diversity score 0.500000
case 7, store 11 allocate diversity score 0.500000
case 7, store 12 allocate diversity score 0.500000
=== RUN   TestAllocateDiversityScore/case_8
case 8, store 6 allocate diversity score 0.500000
case 8, store 7 allocate diversity score 0.500000
case 8, store 8 allocate diversity score 0.500000
case 8, store 9 allocate diversity score 1.000000
case 8, store 10 allocate diversity score 1.000000
case 8, store 11 allocate diversity score 1.000000
case 8, store 12 allocate diversity score 1.000000
=== RUN   TestAllocateDiversityScore/case_9
case 9, store 4 allocate diversity score 0.500000
case 9, store 7 allocate diversity score 0.500000
case 9, store 8 allocate diversity score 0.500000
case 9, store 9 allocate diversity score 1.000000
case 9, store 10 allocate diversity score 1.000000
case 9, store 11 allocate diversity score 1.000000
case 9, store 12 allocate diversity score 1.000000
=== RUN   TestAllocateDiversityScore/case_10
case 10, store 3 allocate diversity score 0.500000
case 10, store 4 allocate diversity score 0.500000
case 10, store 7 allocate diversity score 0.500000
case 10, store 8 allocate diversity score 0.500000
case 10, store 10 allocate diversity score 0.500000
case 10, store 11 allocate diversity score 0.500000
case 10, store 12 allocate diversity score 0.500000
=== RUN   TestAllocateDiversityScore/case_11
case 11, store 7 allocate diversity score 0.500000
case 11, store 8 allocate diversity score 0.500000
case 11, store 9 allocate diversity score 1.000000
case 11, store 10 allocate diversity score 1.000000
case 11, store 11 allocate diversity score 1.000000
case 11, store 12 allocate diversity score 1.000000
=== RUN   TestAllocateDiversityScore/case_12
case 12, store 4 allocate diversity score 0.500000
case 12, store 7 allocate diversity score 0.500000
case 12, store 8 allocate diversity score 0.500000
case 12, store 10 allocate diversity score 0.500000
case 12, store 11 allocate diversity score 0.500000
case 12, store 12 allocate diversity score 0.500000
=== RUN   TestAllocateDiversityScore/case_13
case 13, store 4 allocate diversity score 0.500000
case 13, store 7 allocate diversity score 0.500000
case 13, store 8 allocate diversity score 0.500000
case 13, store 10 allocate diversity score 0.500000
case 13, store 11 allocate diversity score 0.500000
case 13, store 12 allocate diversity score 0.500000
=== RUN   TestAllocateDiversityScore/case_14
case 14, store 8 allocate diversity score 0.500000
case 14, store 9 allocate diversity score 1.000000
case 14, store 10 allocate diversity score 1.000000
case 14, store 11 allocate diversity score 1.000000
case 14, store 12 allocate diversity score 1.000000
=== RUN   TestAllocateDiversityScore/case_15
case 15, store 3 allocate diversity score 0.500000
case 15, store 4 allocate diversity score 0.500000
case 15, store 8 allocate diversity score 0.500000
case 15, store 11 allocate diversity score 0.500000
case 15, store 12 allocate diversity score 0.500000
```
New Method result:
```
=== RUN   TestAllocateDiversityScore
=== RUN   TestAllocateDiversityScore/case_1
case 1, store 4 allocate diversity score 0.500000
case 1, store 5 allocate diversity score 1.000000
case 1, store 6 allocate diversity score 1.000000
case 1, store 7 allocate diversity score 1.000000
case 1, store 8 allocate diversity score 1.000000
case 1, store 9 allocate diversity score 1.000000
case 1, store 10 allocate diversity score 1.000000
case 1, store 11 allocate diversity score 1.000000
case 1, store 12 allocate diversity score 1.000000
=== RUN   TestAllocateDiversityScore/case_2
case 2, store 3 allocate diversity score 0.666667
case 2, store 4 allocate diversity score 0.666667
case 2, store 6 allocate diversity score 0.833333
case 2, store 7 allocate diversity score 0.833333
case 2, store 8 allocate diversity score 0.833333
case 2, store 9 allocate diversity score 1.000000
case 2, store 10 allocate diversity score 1.000000
case 2, store 11 allocate diversity score 1.000000
case 2, store 12 allocate diversity score 1.000000
=== RUN   TestAllocateDiversityScore/case_3
case 3, store 2 allocate diversity score 0.833333
case 3, store 3 allocate diversity score 0.833333
case 3, store 4 allocate diversity score 0.833333
case 3, store 6 allocate diversity score 0.833333
case 3, store 7 allocate diversity score 0.833333
case 3, store 8 allocate diversity score 0.833333
case 3, store 10 allocate diversity score 0.833333
case 3, store 11 allocate diversity score 0.833333
case 3, store 12 allocate diversity score 0.833333
=== RUN   TestAllocateDiversityScore/case_4
case 4, store 5 allocate diversity score 1.000000
case 4, store 6 allocate diversity score 1.000000
case 4, store 7 allocate diversity score 1.000000
case 4, store 8 allocate diversity score 1.000000
case 4, store 9 allocate diversity score 1.000000
case 4, store 10 allocate diversity score 1.000000
case 4, store 11 allocate diversity score 1.000000
case 4, store 12 allocate diversity score 1.000000
=== RUN   TestAllocateDiversityScore/case_5
case 5, store 4 allocate diversity score 0.625000
case 5, store 6 allocate diversity score 0.875000
case 5, store 7 allocate diversity score 0.875000
case 5, store 8 allocate diversity score 0.875000
case 5, store 9 allocate diversity score 1.000000
case 5, store 10 allocate diversity score 1.000000
case 5, store 11 allocate diversity score 1.000000
case 5, store 12 allocate diversity score 1.000000
=== RUN   TestAllocateDiversityScore/case_6
case 6, store 3 allocate diversity score 0.750000
case 6, store 4 allocate diversity score 0.750000
case 6, store 7 allocate diversity score 0.750000
case 6, store 8 allocate diversity score 0.750000
case 6, store 9 allocate diversity score 1.000000
case 6, store 10 allocate diversity score 1.000000
case 6, store 11 allocate diversity score 1.000000
case 6, store 12 allocate diversity score 1.000000
=== RUN   TestAllocateDiversityScore/case_7
case 7, store 3 allocate diversity score 0.750000
case 7, store 4 allocate diversity score 0.750000
case 7, store 6 allocate diversity score 0.875000
case 7, store 7 allocate diversity score 0.875000
case 7, store 8 allocate diversity score 0.875000
case 7, store 10 allocate diversity score 0.875000
case 7, store 11 allocate diversity score 0.875000
case 7, store 12 allocate diversity score 0.875000
=== RUN   TestAllocateDiversityScore/case_8
case 8, store 6 allocate diversity score 0.900000
case 8, store 7 allocate diversity score 0.900000
case 8, store 8 allocate diversity score 0.900000
case 8, store 9 allocate diversity score 1.000000
case 8, store 10 allocate diversity score 1.000000
case 8, store 11 allocate diversity score 1.000000
case 8, store 12 allocate diversity score 1.000000
=== RUN   TestAllocateDiversityScore/case_9
case 9, store 4 allocate diversity score 0.700000
case 9, store 7 allocate diversity score 0.800000
case 9, store 8 allocate diversity score 0.800000
case 9, store 9 allocate diversity score 1.000000
case 9, store 10 allocate diversity score 1.000000
case 9, store 11 allocate diversity score 1.000000
case 9, store 12 allocate diversity score 1.000000
=== RUN   TestAllocateDiversityScore/case_10
case 10, store 3 allocate diversity score 0.800000
case 10, store 4 allocate diversity score 0.800000
case 10, store 7 allocate diversity score 0.800000
case 10, store 8 allocate diversity score 0.800000
case 10, store 10 allocate diversity score 0.900000
case 10, store 11 allocate diversity score 0.900000
case 10, store 12 allocate diversity score 0.900000
=== RUN   TestAllocateDiversityScore/case_11
case 11, store 7 allocate diversity score 0.833333
case 11, store 8 allocate diversity score 0.833333
case 11, store 9 allocate diversity score 1.000000
case 11, store 10 allocate diversity score 1.000000
case 11, store 11 allocate diversity score 1.000000
case 11, store 12 allocate diversity score 1.000000
=== RUN   TestAllocateDiversityScore/case_12
case 12, store 4 allocate diversity score 0.750000
case 12, store 7 allocate diversity score 0.833333
case 12, store 8 allocate diversity score 0.833333
case 12, store 10 allocate diversity score 0.916667
case 12, store 11 allocate diversity score 0.916667
case 12, store 12 allocate diversity score 0.916667
=== RUN   TestAllocateDiversityScore/case_13
case 13, store 4 allocate diversity score 0.750000
case 13, store 7 allocate diversity score 0.833333
case 13, store 8 allocate diversity score 0.833333
case 13, store 10 allocate diversity score 0.916667
case 13, store 11 allocate diversity score 0.916667
case 13, store 12 allocate diversity score 0.916667
=== RUN   TestAllocateDiversityScore/case_14
case 14, store 8 allocate diversity score 0.785714
case 14, store 9 allocate diversity score 1.000000
case 14, store 10 allocate diversity score 1.000000
case 14, store 11 allocate diversity score 1.000000
case 14, store 12 allocate diversity score 1.000000
=== RUN   TestAllocateDiversityScore/case_15
case 15, store 3 allocate diversity score 0.857143
case 15, store 4 allocate diversity score 0.857143
case 15, store 8 allocate diversity score 0.785714
case 15, store 11 allocate diversity score 0.857143
case 15, store 12 allocate diversity score 0.857143
```

***diversityRebalanceScore
Original Method result:
```
case 1, store 4 rebalance diversity score 0.500000
case 1, store 5 rebalance diversity score 1.000000
case 1, store 6 rebalance diversity score 1.000000
case 1, store 7 rebalance diversity score 1.000000
case 1, store 8 rebalance diversity score 1.000000
case 1, store 9 rebalance diversity score 1.000000
case 1, store 10 rebalance diversity score 1.000000
case 1, store 11 rebalance diversity score 1.000000
case 1, store 12 rebalance diversity score 1.000000
=== RUN   TestRebalanceDiversityScore/case_2
case 2, store 3 rebalance diversity score 0.500000
case 2, store 4 rebalance diversity score 0.500000
case 2, store 6 rebalance diversity score 1.000000
case 2, store 7 rebalance diversity score 1.000000
case 2, store 8 rebalance diversity score 1.000000
case 2, store 9 rebalance diversity score 1.000000
case 2, store 10 rebalance diversity score 1.000000
case 2, store 11 rebalance diversity score 1.000000
case 2, store 12 rebalance diversity score 1.000000
=== RUN   TestRebalanceDiversityScore/case_3
case 3, store 2 rebalance diversity score 1.000000
case 3, store 3 rebalance diversity score 1.000000
case 3, store 4 rebalance diversity score 1.000000
case 3, store 6 rebalance diversity score 1.000000
case 3, store 7 rebalance diversity score 1.000000
case 3, store 8 rebalance diversity score 1.000000
case 3, store 10 rebalance diversity score 1.000000
case 3, store 11 rebalance diversity score 1.000000
case 3, store 12 rebalance diversity score 1.000000
=== RUN   TestRebalanceDiversityScore/case_4
case 4, store 5 rebalance diversity score 1.000000
case 4, store 6 rebalance diversity score 1.000000
case 4, store 7 rebalance diversity score 1.000000
case 4, store 8 rebalance diversity score 1.000000
case 4, store 9 rebalance diversity score 1.000000
case 4, store 10 rebalance diversity score 1.000000
case 4, store 11 rebalance diversity score 1.000000
case 4, store 12 rebalance diversity score 1.000000
=== RUN   TestRebalanceDiversityScore/case_5
case 5, store 4 rebalance diversity score 0.500000
case 5, store 6 rebalance diversity score 1.000000
case 5, store 7 rebalance diversity score 1.000000
case 5, store 8 rebalance diversity score 1.000000
case 5, store 9 rebalance diversity score 1.000000
case 5, store 10 rebalance diversity score 1.000000
case 5, store 11 rebalance diversity score 1.000000
case 5, store 12 rebalance diversity score 1.000000
=== RUN   TestRebalanceDiversityScore/case_6
case 6, store 3 rebalance diversity score 0.500000
case 6, store 4 rebalance diversity score 0.500000
case 6, store 7 rebalance diversity score 0.500000
case 6, store 8 rebalance diversity score 0.500000
case 6, store 9 rebalance diversity score 1.000000
case 6, store 10 rebalance diversity score 1.000000
case 6, store 11 rebalance diversity score 1.000000
case 6, store 12 rebalance diversity score 1.000000
=== RUN   TestRebalanceDiversityScore/case_7
case 7, store 3 rebalance diversity score 0.500000
case 7, store 4 rebalance diversity score 0.500000
case 7, store 6 rebalance diversity score 1.000000
case 7, store 7 rebalance diversity score 1.000000
case 7, store 8 rebalance diversity score 1.000000
case 7, store 10 rebalance diversity score 1.000000
case 7, store 11 rebalance diversity score 1.000000
case 7, store 12 rebalance diversity score 1.000000
=== RUN   TestRebalanceDiversityScore/case_8
case 8, store 6 rebalance diversity score 1.000000
case 8, store 7 rebalance diversity score 1.000000
case 8, store 8 rebalance diversity score 1.000000
case 8, store 9 rebalance diversity score 1.000000
case 8, store 10 rebalance diversity score 1.000000
case 8, store 11 rebalance diversity score 1.000000
case 8, store 12 rebalance diversity score 1.000000
=== RUN   TestRebalanceDiversityScore/case_9
case 9, store 4 rebalance diversity score 0.500000
case 9, store 7 rebalance diversity score 0.500000
case 9, store 8 rebalance diversity score 0.500000
case 9, store 9 rebalance diversity score 1.000000
case 9, store 10 rebalance diversity score 1.000000
case 9, store 11 rebalance diversity score 1.000000
case 9, store 12 rebalance diversity score 1.000000
=== RUN   TestRebalanceDiversityScore/case_10
case 10, store 3 rebalance diversity score 0.500000
case 10, store 4 rebalance diversity score 0.500000
case 10, store 7 rebalance diversity score 0.500000
case 10, store 8 rebalance diversity score 0.500000
case 10, store 10 rebalance diversity score 1.000000
case 10, store 11 rebalance diversity score 1.000000
case 10, store 12 rebalance diversity score 1.000000
=== RUN   TestRebalanceDiversityScore/case_11
case 11, store 7 rebalance diversity score 0.500000
case 11, store 8 rebalance diversity score 0.500000
case 11, store 9 rebalance diversity score 1.000000
case 11, store 10 rebalance diversity score 1.000000
case 11, store 11 rebalance diversity score 1.000000
case 11, store 12 rebalance diversity score 1.000000
=== RUN   TestRebalanceDiversityScore/case_12
case 12, store 4 rebalance diversity score 0.500000
case 12, store 7 rebalance diversity score 0.500000
case 12, store 8 rebalance diversity score 0.500000
case 12, store 10 rebalance diversity score 1.000000
case 12, store 11 rebalance diversity score 1.000000
case 12, store 12 rebalance diversity score 1.000000
=== RUN   TestRebalanceDiversityScore/case_13
case 13, store 4 rebalance diversity score 0.500000
case 13, store 7 rebalance diversity score 0.500000
case 13, store 8 rebalance diversity score 0.500000
case 13, store 10 rebalance diversity score 1.000000
case 13, store 11 rebalance diversity score 1.000000
case 13, store 12 rebalance diversity score 1.000000
=== RUN   TestRebalanceDiversityScore/case_14
case 14, store 8 rebalance diversity score 0.500000
case 14, store 9 rebalance diversity score 1.000000
case 14, store 10 rebalance diversity score 1.000000
case 14, store 11 rebalance diversity score 1.000000
case 14, store 12 rebalance diversity score 1.000000
=== RUN   TestRebalanceDiversityScore/case_15
case 15, store 3 rebalance diversity score 0.500000
case 15, store 4 rebalance diversity score 0.500000
case 15, store 8 rebalance diversity score 0.500000
case 15, store 11 rebalance diversity score 0.500000
case 15, store 12 rebalance diversity score 0.500000
```
New Method result:
```
=== RUN   TestRebalanceDiversityScore
=== RUN   TestRebalanceDiversityScore/case_1
case 1, store 4 rebalance diversity score 0.500000
case 1, store 5 rebalance diversity score 0.750000
case 1, store 6 rebalance diversity score 0.750000
case 1, store 7 rebalance diversity score 0.750000
case 1, store 8 rebalance diversity score 0.750000
case 1, store 9 rebalance diversity score 0.750000
case 1, store 10 rebalance diversity score 0.750000
case 1, store 11 rebalance diversity score 0.750000
case 1, store 12 rebalance diversity score 0.750000
=== RUN   TestRebalanceDiversityScore/case_2
case 2, store 3 rebalance diversity score 0.750000
case 2, store 4 rebalance diversity score 0.750000
case 2, store 6 rebalance diversity score 1.000000
case 2, store 7 rebalance diversity score 1.000000
case 2, store 8 rebalance diversity score 1.000000
case 2, store 9 rebalance diversity score 1.000000
case 2, store 10 rebalance diversity score 1.000000
case 2, store 11 rebalance diversity score 1.000000
case 2, store 12 rebalance diversity score 1.000000
=== RUN   TestRebalanceDiversityScore/case_3
case 3, store 2 rebalance diversity score 1.000000
case 3, store 3 rebalance diversity score 1.000000
case 3, store 4 rebalance diversity score 1.000000
case 3, store 6 rebalance diversity score 1.000000
case 3, store 7 rebalance diversity score 1.000000
case 3, store 8 rebalance diversity score 1.000000
case 3, store 10 rebalance diversity score 1.000000
case 3, store 11 rebalance diversity score 1.000000
case 3, store 12 rebalance diversity score 1.000000
=== RUN   TestRebalanceDiversityScore/case_4
case 4, store 5 rebalance diversity score 0.666667
case 4, store 6 rebalance diversity score 0.666667
case 4, store 7 rebalance diversity score 0.666667
case 4, store 8 rebalance diversity score 0.666667
case 4, store 9 rebalance diversity score 0.666667
case 4, store 10 rebalance diversity score 0.666667
case 4, store 11 rebalance diversity score 0.666667
case 4, store 12 rebalance diversity score 0.666667
=== RUN   TestRebalanceDiversityScore/case_5
case 5, store 4 rebalance diversity score 0.722222
case 5, store 6 rebalance diversity score 0.888889
case 5, store 7 rebalance diversity score 0.888889
case 5, store 8 rebalance diversity score 0.888889
case 5, store 9 rebalance diversity score 0.888889
case 5, store 10 rebalance diversity score 0.888889
case 5, store 11 rebalance diversity score 0.888889
case 5, store 12 rebalance diversity score 0.888889
=== RUN   TestRebalanceDiversityScore/case_6
case 6, store 3 rebalance diversity score 0.888889
case 6, store 4 rebalance diversity score 0.888889
case 6, store 7 rebalance diversity score 0.888889
case 6, store 8 rebalance diversity score 0.888889
case 6, store 9 rebalance diversity score 0.888889
case 6, store 10 rebalance diversity score 0.888889
case 6, store 11 rebalance diversity score 0.888889
case 6, store 12 rebalance diversity score 0.888889
=== RUN   TestRebalanceDiversityScore/case_7
case 7, store 3 rebalance diversity score 0.888889
case 7, store 4 rebalance diversity score 0.888889
case 7, store 6 rebalance diversity score 1.000000
case 7, store 7 rebalance diversity score 1.000000
case 7, store 8 rebalance diversity score 1.000000
case 7, store 10 rebalance diversity score 1.000000
case 7, store 11 rebalance diversity score 1.000000
case 7, store 12 rebalance diversity score 1.000000
=== RUN   TestRebalanceDiversityScore/case_8
case 8, store 6 rebalance diversity score 0.812500
case 8, store 7 rebalance diversity score 0.812500
case 8, store 8 rebalance diversity score 0.812500
case 8, store 9 rebalance diversity score 0.812500
case 8, store 10 rebalance diversity score 0.812500
case 8, store 11 rebalance diversity score 0.812500
case 8, store 12 rebalance diversity score 0.812500
=== RUN   TestRebalanceDiversityScore/case_9
case 9, store 4 rebalance diversity score 0.812500
case 9, store 7 rebalance diversity score 0.875000
case 9, store 8 rebalance diversity score 0.875000
case 9, store 9 rebalance diversity score 0.875000
case 9, store 10 rebalance diversity score 0.875000
case 9, store 11 rebalance diversity score 0.875000
case 9, store 12 rebalance diversity score 0.875000
=== RUN   TestRebalanceDiversityScore/case_10
case 10, store 3 rebalance diversity score 0.937500
case 10, store 4 rebalance diversity score 0.937500
case 10, store 7 rebalance diversity score 0.937500
case 10, store 8 rebalance diversity score 0.937500
case 10, store 10 rebalance diversity score 0.937500
case 10, store 11 rebalance diversity score 0.937500
case 10, store 12 rebalance diversity score 0.937500
=== RUN   TestRebalanceDiversityScore/case_11
case 11, store 7 rebalance diversity score 0.840000
case 11, store 8 rebalance diversity score 0.840000
case 11, store 9 rebalance diversity score 0.840000
case 11, store 10 rebalance diversity score 0.840000
case 11, store 11 rebalance diversity score 0.840000
case 11, store 12 rebalance diversity score 0.840000
=== RUN   TestRebalanceDiversityScore/case_12
case 12, store 4 rebalance diversity score 0.880000
case 12, store 7 rebalance diversity score 0.920000
case 12, store 8 rebalance diversity score 0.920000
case 12, store 10 rebalance diversity score 0.920000
case 12, store 11 rebalance diversity score 0.920000
case 12, store 12 rebalance diversity score 0.920000
=== RUN   TestRebalanceDiversityScore/case_13
case 13, store 4 rebalance diversity score 0.880000
case 13, store 7 rebalance diversity score 0.920000
case 13, store 8 rebalance diversity score 0.920000
case 13, store 10 rebalance diversity score 0.920000
case 13, store 11 rebalance diversity score 0.920000
case 13, store 12 rebalance diversity score 0.920000
=== RUN   TestRebalanceDiversityScore/case_14
case 14, store 8 rebalance diversity score 0.833333
case 14, store 9 rebalance diversity score 0.833333
case 14, store 10 rebalance diversity score 0.833333
case 14, store 11 rebalance diversity score 0.833333
case 14, store 12 rebalance diversity score 0.833333
=== RUN   TestRebalanceDiversityScore/case_15
case 15, store 3 rebalance diversity score 0.916667
case 15, store 4 rebalance diversity score 0.916667
case 15, store 8 rebalance diversity score 0.888889
case 15, store 11 rebalance diversity score 0.916667
case 15, store 12 rebalance diversity score 0.916667
```

File: pkg/storage/allocator_scorer.go (hunk 6 above)
[the remark this answers is not in the document]
Comment (a6802739) [reply pkg/storage/allocator_scorer.go]: Yeah, something like that.

**Review by a-robinson — COMMENTED** [review]
Thanks for all test output and explanations, @a6802739! I still need to take a closer look at the tests, and there are some more nits that could be picked related to code duplication, but I'm fairly happy with the approach. I'll chat with @BramGruneir about it again tomorrow to see if he's also on board, and if so I'll give the tests a closer code review.

**Comment by a-robinson** [comment]
Reviewed 1 of 3 files at r3.
Review status: 1 of 3 files reviewed at latest revision, 14 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/19486)*

**Comment by BramGruneir** [comment]
Discussed this with @a-robinson offline and we walked through the new scores.  Looks really good.  I support this change.

**Comment by a6802739** [comment]
@BramGruneir  @a-robinson, Thank you for your kind review!

I will wait for @a-robinson to have a look at the tests.

**Review by a-robinson — APPROVED** [review]
@a6802739 I've gone through and rather than leaving nit-picky review comments about typos, unclear sentences, and small cosmetic changes, I've added a new commit to the PR on top of yours with the changes. I didn't change the semantics of anything, just minor stuff. Let me know if there's anything in it you think I got wrong, though! This LGTM after the changes.

**Comment by a6802739** [comment]
@a-robinson, Thank you very much. 
LGTM after you change and learned a lot from your change!
