### PR TITLE
changefeedccl: make options values case insensitive

### LINKED ISSUE #69154: changefeedccl: make options values case insensitive
Changefeed option values are currently case sensitive, as shown by the following `CREATE CHANGEFEED` statement:

```
CREATE CHANGEFEED FOR TABLE foo INTO 'kafka://localhost:9092' WITH format='JSON';
ERROR: unknown format: JSON
```
If some users misremember option values as being uppercase, it might save them a little bit of headache to not have to re-enter.
Easy implementation (just iterate through option values before evaluating and convert all to lowercase)

Also need to consider: which options will this not work for? i.e. `confluent_schema_registry` can't just be converted to lowercase since it has potential base64-encoded params which is case sensitive. 
(Note: may be safer to explicitly declare a list of options which we CAN convert to lowercase)

### PR DESCRIPTION
**Pull request by sumit-tembe**
changefeedccl: Make options values case insensitive

Treat changefeed option values as case insensitive.

Fixes #69154

Release Justification: Low danger, UX performance improvement.
Release note (enterprise change): changefeed option values are case insensitive.

### CODE REVIEW

**Review by miretskiy — CHANGES_REQUESTED** [review]
Thank you for your contribution!

While the addition of case insensitive options might make sense, the fact is that options and their interpretation are statement dependent.

I think it would make sense to simply lower case option values directly when starting changefeed, somewhere after
https://github.com/cockroachdb/cockroach/blob/3c46f0702fb56dff176ae826a127f3fcba36a680/pkg/ccl/changefeedccl/changefeed_stmt.go#L155

File: pkg/sql/planner.go [hunk 1]
```diff
@@ -651,6 +651,11 @@ const (
 	KVStringOptRequireValue   KVStringOptValidate = `value`
 )
 
+// KVStringCaseInsensitiveOpts options which supports case Insensitive value
+var KVStringCaseInsensitiveOpts = map[string]struct{}{
```
Comment (spiffyyeng) [inline pkg/sql/planner.go:655]: Thanks for the PR!

We should probably move this var into a changefeed package since we're only dealing with the supported options at the changefeed level. Perhaps [`changefeedbase/options.go`](https://github.com/cockroachdb/cockroach/blob/master/pkg/ccl/changefeedccl/changefeedbase/options.go) and call it something like `CaseInsensitiveOpts`?

File: pkg/ccl/changefeedccl/changefeed_stmt.go [hunk 2]
```diff
@@ -154,6 +155,13 @@ func changefeedPlanHook(
 			return err
 		}
 
+		for key, value := range opts {
+			// if option is case insensitive then convert it's value to lower case
```
Comment (spiffyyeng) [inline pkg/ccl/changefeedccl/changefeed_stmt.go:159]: nit: :%s/it's/its/g

File: pkg/ccl/changefeedccl/changefeed_stmt.go [hunk 3]
```diff
@@ -154,6 +155,13 @@ func changefeedPlanHook(
 			return err
 		}
 
+		for key, value := range opts {
```
Comment (spiffyyeng) [inline pkg/ccl/changefeedccl/changefeed_stmt.go:158]: Could you also add some tests for this? Maybe add to `changefeed_test.go` ([TestChangefeedErrors](https://github.com/cockroachdb/cockroach/blob/master/pkg/ccl/changefeedccl/changefeed_test.go#L2451))

File: pkg/sql/planner.go [hunk 4]
```diff
@@ -651,6 +651,11 @@ const (
...
+	"format": {},
+}
```
Comment (spiffyyeng) [inline pkg/sql/planner.go:657]: We'll need to add more opts here, but this is the right idea ("whitelist" options we want to be case insensitive). I'll provide the full list here shortly.

File: pkg/sql/planner.go [hunk 5]
```diff
@@ -651,6 +651,11 @@ const (
 	KVStringOptRequireValue   KVStringOptValidate = `value`
 )
 
+// KVStringCaseInsensitiveOpts options which supports case Insensitive value
+var KVStringCaseInsensitiveOpts = map[string]struct{}{
+	"format": {},
```
Comment (spiffyyeng) [inline pkg/sql/planner.go:656]: nit: Make sure when populating this map, refer to the keys by their option constant values (`changefeedbase.OptFormat`) in this case rather than the raw string

**Review by spiffyy99 — CHANGES_REQUESTED** [review]

**Comment by spiffyyeng** [comment]
@sumit-tembe let's allow only the enum-based options:

- `envelope`
- `format`
- `compression`
- `schema_change_events`
- `schema_change_policy`
- `on_error`

**Comment by sumit-tembe** [comment]
@miretskiy @spiffyyeng 
Thanks, for the review comments. I'm working on these changes.

File: pkg/ccl/changefeedccl/changefeedbase/options.go [hunk 6]
```diff
@@ -160,3 +160,13 @@ var ChangefeedOptionExpectValues = map[string]sql.KVStringOptValidate{
 	OptWebhookClientTimeout:     sql.KVStringOptRequireValue,
 	OptOnError:                  sql.KVStringOptRequireValue,
 }
+
+// CaseInsensitiveOpts options which supports case Insensitive value
```
Comment (miretskiy) [inline pkg/ccl/changefeedccl/changefeedbase/options.go:164]: perhaps rephrase a bit:
`// CaceInsensitiveOpts specifies which options are case insensitive.`

File: pkg/ccl/changefeedccl/changefeed_test.go [hunk 7]
```diff
@@ -2867,6 +2867,27 @@ func TestChangefeedErrors(t *testing.T) {
 		t, `unknown on_error: not_valid, valid values are 'pause' and 'fail'`,
 		`CREATE CHANGEFEED FOR foo into $1 WITH on_error='not_valid'`,
 		`kafka://nope`)
+
```
Comment (miretskiy) [inline pkg/ccl/changefeedccl/changefeed_test.go:2870]: Let's move this test into a separate test fixture.  (This particular test deals with error)

File: pkg/ccl/changefeedccl/changefeed_test.go [hunk 8]
```diff
@@ -2867,6 +2867,27 @@ func TestChangefeedErrors(t *testing.T) {
...
+		assertPayloads(t, cf, []string{
+			`insensitive: [0]->{"after": {"x": 0, "y": "hello"}}`,
+		})
+	}
+
+	t.Run(`sinkless`, sinklessTest(testFn))
+	t.Run(`enterprise`, enterpriseTest(testFn))
+	t.Run(`kafka`, kafkaTest(testFn))
+	t.Run(`webhook`, webhookTest(testFn))
```
Comment (miretskiy) [inline pkg/ccl/changefeedccl/changefeed_test.go:2890]: You probably don't need to run this for all types of feed -- afterall, you're testing option parsing, not the actual sinks.

File: pkg/ccl/changefeedccl/changefeedbase/options.go [hunk 9]
```diff
@@ -160,3 +160,13 @@ var ChangefeedOptionExpectValues = map[string]sql.KVStringOptValidate{
...
+var CaseInsensitiveOpts = map[string]struct{}{
```
Comment (miretskiy) [inline pkg/ccl/changefeedccl/changefeedbase/options.go:165]: I wonder if the option names (keys) should be case insensitive. @amruss?

**Review by miretskiy — CHANGES_REQUESTED** [review]

File: pkg/ccl/changefeedccl/changefeedbase/options.go (hunk 9 above)
Comment (spiffyyeng) [reply pkg/ccl/changefeedccl/changefeedbase/options.go:165]: think she is out this week

File: pkg/ccl/changefeedccl/changefeed_test.go [hunk 10]
```diff
@@ -4394,4 +4395,44 @@ CREATE CHANGEFEED FOR tbl INTO 'null://';
 		"SELECT count(*) FROM crdb_internal.active_range_feeds WHERE range_start LIKE '/Table/%d/%%'",
 		tableID)
 	sqlDB.CheckQueryResultsRetry(t, numRangesQuery, [][]string{{"1"}})
+
+}
+
+func TestChangefeedCaceInsensitiveOpts(t *testing.T) {
```
Comment (spiffyyeng) [inline pkg/ccl/changefeedccl/changefeed_test.go:4401]: nit: :%s/Cace/Case/g

**Comment by sumit-tembe** [comment]
The build is failing due to the DATA race while running UT TestChangefeedCaseInsensitiveOpts and TestChangefeedInitialScan.
```
WARNING: DATA RACE
Write at 0x00c005c84d90 by goroutine 183:
  github.com/cockroachdb/cockroach/pkg/sql/sqlliveness/slinstance.(*Instance).extendSession()
      /go/src/github.com/cockroachdb/cockroach/pkg/sql/sqlliveness/slinstance/slinstance.go:201 +0x3e5
      
 Previous read at 0x00c005c84d90 by goroutine 253:
  github.com/cockroachdb/cockroach/pkg/sql/sqlliveness/slinstance.(*session).Expiration()
      /go/src/github.com/cockroachdb/cockroach/pkg/sql/sqlliveness/slinstance/slinstance.go:73 +0x4b
```
Working on the same.

**Comment by stevendanna** [comment]
@sumit-tembe I believe that failure is likely related to a recently merged change elsewhere and likely not a result of your changes.  We'll work to get it sorted out.

**Comment by sumit-tembe** [comment]
> @sumit-tembe I believe that failure is likely related to a recently merged change elsewhere and likely not a result of your changes. We'll work to get it sorted out.

Thank you for letting me know.

**Comment by miretskiy** [comment]
@sumit-tembe can you pull & rebase on master to make sure everything is up to date.

I think I'm okay merging this PR -- seems like a good UX improvement.  We can decide later if we also want to support lowercasing option names.

**Comment by sumit-tembe** [comment]
> @sumit-tembe can you pull & rebase on master to make sure everything is up to date.
> 
> I think I'm okay merging this PR -- seems like a good UX improvement. We can decide later if we also want to support lowercasing option names.

Sure.

**Comment by spiffyyeng** [comment]
LGTM, but please address the blathers comments (squash into one commit, add proper [commit message](https://cockroachlabs.atlassian.net/wiki/spaces/CRDB/pages/73072807/Git+Commit+Messages))

**Comment by sumit-tembe** [comment]
@spiffyyeng 
Can we restart builds? Build got failed due to missing `Release justification`.

**Comment by miretskiy** [comment]
You can update commit description in your branch and push updated branch -- this should trigger new build.
I think you should update your change description in your branch (`git commit --amend`) and after pushing this branch
update description manually on PR descritpion.
I also think you should expand the description:

Something like:

```
changefeedccl: Make options values case insensitive

Treat changefeed option values as case insensitive.

Fixes #69154

Release Justification: Low danger, UX performance improvement.
Release Notes: changefeed option values are case insensitive.

**Comment by spiffyyeng** [comment]
@sumit-tembe i think for blathers to stop complaining you have to format your release note like this:

```
Release note (enterprise change): changefeed option values are case insensitive.
```

**Comment by sumit-tembe** [comment]
> @sumit-tembe i think for blathers to stop complaining you have to format your release note like this:
> 
> ```
> Release note (enterprise change): changefeed option values are case insensitive.
> ```

Ok

**Review by spiffyy99 — APPROVED** [review]

**Comment by shermanCRL** [comment]
I’m OK’ing this as a stability addition, contingent on confidence from @spiffyyeng that it’s well-tested and low-impact.

**Comment by sumit-tembe** [comment]
@miretskiy Can you please review?

**Review by HonoreDB — APPROVED** [review]
> Reviewed 1 of 2 files at r11, 2 of 2 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/69217)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @amruss, @miretskiy, and @sumit-tembe)

**Comment by HonoreDB** [comment]
bors r+

Thanks so much @sumit-tembe for the PR and revisions!
