### PR TITLE
roachtest: avoid using single quotes in ORM test

### LINKED ISSUE #113255: roachtest: gorm failed
roachtest.gorm [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/12391423?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/12391423?buildTab=artifacts#/gorm) on master @ [aa85c69776da942b4d539891725b780ba995401e](https://github.com/cockroachdb/cockroach/commits/aa85c69776da942b4d539891725b780ba995401e):

```
(java_helpers.go:205).parseAndSummarizeJavaORMTestsResults: all attempts failed for fetching results file ~/logs/report/gorm/report.xml: COMMAND_PROBLEM: exit status 1
test artifacts and logs in: /artifacts/gorm/run_1
```
<p>Parameters: <code>ROACHTEST_arch=amd64</code>
, <code>ROACHTEST_cloud=gce</code>
, <code>ROACHTEST_cpu=4</code>
, <code>ROACHTEST_encrypted=false</code>
, <code>ROACHTEST_ssd=0</code>
</p>
<details><summary>Help</summary>
<p>

See: [roachtest README](https://github.com/cockroachdb/cockroach/blob/master/pkg/cmd/roachtest/README.md)

See: [How To Investigate \(internal\)](https://cockroachlabs.atlassian.net/l/c/SSSBr8c7)

See: [Grafana](https://go.crdb.dev/roachtest-grafana/teamcity-12391423/gorm/1698490555264/1698492474864)

</p>
</details>
/cc @cockroachdb/sql-foundations
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*gorm.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)
</sub>

Jira issue: CRDB-32827

### LINKED ISSUE #113263: roachtest: lib/pq failed
roachtest.lib/pq [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/12391423?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/12391423?buildTab=artifacts#/lib/pq) on master @ [aa85c69776da942b4d539891725b780ba995401e](https://github.com/cockroachdb/cockroach/commits/aa85c69776da942b4d539891725b780ba995401e):

```
(java_helpers.go:205).parseAndSummarizeJavaORMTestsResults: all attempts failed for fetching results file ~/logs/report/libpq-results/report.xml: COMMAND_PROBLEM: exit status 1
test artifacts and logs in: /artifacts/lib/pq/run_1
```
<p>Parameters: <code>ROACHTEST_arch=amd64</code>
, <code>ROACHTEST_cloud=gce</code>
, <code>ROACHTEST_cpu=4</code>
, <code>ROACHTEST_encrypted=false</code>
, <code>ROACHTEST_ssd=0</code>
</p>
<details><summary>Help</summary>
<p>

See: [roachtest README](https://github.com/cockroachdb/cockroach/blob/master/pkg/cmd/roachtest/README.md)

See: [How To Investigate \(internal\)](https://cockroachlabs.atlassian.net/l/c/SSSBr8c7)

See: [Grafana](https://go.crdb.dev/roachtest-grafana/teamcity-12391423/lib-pq/1698510322813/1698512198143)

</p>
</details>
/cc @cockroachdb/sql-foundations
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*lib/pq.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)
</sub>

Jira issue: CRDB-32833

### LINKED ISSUE #113383: roachtest: gorm failed
roachtest.gorm [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/12428928?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/12428928?buildTab=artifacts#/gorm) on release-22.2 @ [11d9281c826075cad5392e94cdba4d254feea141](https://github.com/cockroachdb/cockroach/commits/11d9281c826075cad5392e94cdba4d254feea141):

```
test artifacts and logs in: /artifacts/gorm/run_1
(java_helpers.go:216).parseAndSummarizeJavaORMTestsResults: all attempts failed for fetching results file ~/logs/report/gorm/report.xml: COMMAND_PROBLEM: ssh verbose log retained in ssh_091725.423206800_n1_cat-logsreportgormre.log: exit status 1
```
<p>Parameters: <code>ROACHTEST_arch=amd64</code>
, <code>ROACHTEST_cloud=gce</code>
, <code>ROACHTEST_cpu=4</code>
, <code>ROACHTEST_encrypted=false</code>
, <code>ROACHTEST_ssd=0</code>
</p>
<details><summary>Help</summary>
<p>

See: [roachtest README](https://github.com/cockroachdb/cockroach/blob/master/pkg/cmd/roachtest/README.md)

See: [How To Investigate \(internal\)](https://cockroachlabs.atlassian.net/l/c/SSSBr8c7)

</p>
</details>
<details><summary>Same failure on other branches</summary>
<p>

- #113255 roachtest: gorm failed [C-test-failure O-roachtest O-robot T-sql-foundations branch-master]
</p>
</details>
/cc @cockroachdb/sql-foundations
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*gorm.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)
</sub>

Jira issue: CRDB-32917

### LINKED ISSUE #113389: roachtest: gorm failed
roachtest.gorm [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/12428942?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/12428942?buildTab=artifacts#/gorm) on release-23.1 @ [cd3ca8999f8103451ef2a7e2110ab75e6604d7ee](https://github.com/cockroachdb/cockroach/commits/cd3ca8999f8103451ef2a7e2110ab75e6604d7ee):

```
(java_helpers.go:205).parseAndSummarizeJavaORMTestsResults: all attempts failed for fetching results file ~/logs/report/gorm/report.xml: COMMAND_PROBLEM: exit status 1
test artifacts and logs in: /artifacts/gorm/run_1
```
<p>Parameters: <code>ROACHTEST_arch=amd64</code>
, <code>ROACHTEST_cloud=gce</code>
, <code>ROACHTEST_cpu=4</code>
, <code>ROACHTEST_encrypted=false</code>
, <code>ROACHTEST_ssd=0</code>
</p>
<details><summary>Help</summary>
<p>

See: [roachtest README](https://github.com/cockroachdb/cockroach/blob/master/pkg/cmd/roachtest/README.md)

See: [How To Investigate \(internal\)](https://cockroachlabs.atlassian.net/l/c/SSSBr8c7)

See: [Grafana](https://go.crdb.dev/roachtest-grafana/teamcity-12428942/gorm/1698748480203/1698750603977)

</p>
</details>
<details><summary>Same failure on other branches</summary>
<p>

- #113383 roachtest: gorm failed [C-test-failure O-roachtest O-robot T-sql-foundations branch-release-22.2 release-blocker]
- #113255 roachtest: gorm failed [C-test-failure O-roachtest O-robot T-sql-foundations branch-master]
</p>
</details>
/cc @cockroachdb/sql-foundations
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*gorm.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)
</sub>

Jira issue: CRDB-32921

### LINKED ISSUE #113390: roachtest: lib/pq failed
roachtest.lib/pq [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/12428928?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/12428928?buildTab=artifacts#/lib/pq) on release-22.2 @ [11d9281c826075cad5392e94cdba4d254feea141](https://github.com/cockroachdb/cockroach/commits/11d9281c826075cad5392e94cdba4d254feea141):

```
test artifacts and logs in: /artifacts/lib/pq/run_1
(java_helpers.go:216).parseAndSummarizeJavaORMTestsResults: all attempts failed for fetching results file ~/logs/report/libpq-results/report.xml: COMMAND_PROBLEM: ssh verbose log retained in ssh_111624.424368202_n1_cat-logsreportlibpqr.log: exit status 1
```
<p>Parameters: <code>ROACHTEST_arch=amd64</code>
, <code>ROACHTEST_cloud=gce</code>
, <code>ROACHTEST_cpu=4</code>
, <code>ROACHTEST_encrypted=false</code>
, <code>ROACHTEST_ssd=0</code>
</p>
<details><summary>Help</summary>
<p>

See: [roachtest README](https://github.com/cockroachdb/cockroach/blob/master/pkg/cmd/roachtest/README.md)

See: [How To Investigate \(internal\)](https://cockroachlabs.atlassian.net/l/c/SSSBr8c7)

</p>
</details>
<details><summary>Same failure on other branches</summary>
<p>

- #113263 roachtest: lib/pq failed [C-test-failure O-roachtest O-robot T-sql-foundations branch-master]
</p>
</details>
/cc @cockroachdb/sql-foundations
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*lib/pq.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)
</sub>

Jira issue: CRDB-32922

### LINKED ISSUE #113391: roachtest: gorm failed
roachtest.gorm [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/12428970?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/12428970?buildTab=artifacts#/gorm) on release-23.2 @ [348d11425a1184ce4de8a6f8dc85995cd3c653bc](https://github.com/cockroachdb/cockroach/commits/348d11425a1184ce4de8a6f8dc85995cd3c653bc):

```
(java_helpers.go:205).parseAndSummarizeJavaORMTestsResults: all attempts failed for fetching results file ~/logs/report/gorm/report.xml: COMMAND_PROBLEM: exit status 1
test artifacts and logs in: /artifacts/gorm/run_1
```
<p>Parameters: <code>ROACHTEST_arch=amd64</code>
, <code>ROACHTEST_cloud=gce</code>
, <code>ROACHTEST_cpu=4</code>
, <code>ROACHTEST_encrypted=false</code>
, <code>ROACHTEST_ssd=0</code>
</p>
<details><summary>Help</summary>
<p>

See: [roachtest README](https://github.com/cockroachdb/cockroach/blob/master/pkg/cmd/roachtest/README.md)

See: [How To Investigate \(internal\)](https://cockroachlabs.atlassian.net/l/c/SSSBr8c7)

See: [Grafana](https://go.crdb.dev/roachtest-grafana/teamcity-12428970/gorm/1698750641292/1698752659607)

</p>
</details>
<details><summary>Same failure on other branches</summary>
<p>

- #113389 roachtest: gorm failed [C-test-failure O-roachtest O-robot T-sql-foundations branch-release-23.1 release-blocker]
- #113383 roachtest: gorm failed [C-test-failure O-roachtest O-robot T-sql-foundations branch-release-22.2 release-blocker]
- #113255 roachtest: gorm failed [C-test-failure O-roachtest O-robot T-sql-foundations branch-master]
</p>
</details>
/cc @cockroachdb/sql-foundations
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*gorm.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)
</sub>

Jira issue: CRDB-32923

### LINKED ISSUE #113497: roachtest: lib/pq failed
roachtest.lib/pq [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/12428942?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/12428942?buildTab=artifacts#/lib/pq) on release-23.1 @ [cd3ca8999f8103451ef2a7e2110ab75e6604d7ee](https://github.com/cockroachdb/cockroach/commits/cd3ca8999f8103451ef2a7e2110ab75e6604d7ee):

```
(java_helpers.go:205).parseAndSummarizeJavaORMTestsResults: all attempts failed for fetching results file ~/logs/report/libpq-results/report.xml: COMMAND_PROBLEM: exit status 1
test artifacts and logs in: /artifacts/lib/pq/run_1
```
<p>Parameters: <code>ROACHTEST_arch=amd64</code>
, <code>ROACHTEST_cloud=gce</code>
, <code>ROACHTEST_cpu=4</code>
, <code>ROACHTEST_encrypted=false</code>
, <code>ROACHTEST_ssd=0</code>
</p>
<details><summary>Help</summary>
<p>

See: [roachtest README](https://github.com/cockroachdb/cockroach/blob/master/pkg/cmd/roachtest/README.md)

See: [How To Investigate \(internal\)](https://cockroachlabs.atlassian.net/l/c/SSSBr8c7)

See: [Grafana](https://go.crdb.dev/roachtest-grafana/teamcity-12428942/lib-pq/1698762116751/1698764033644)

</p>
</details>
<details><summary>Same failure on other branches</summary>
<p>

- #113390 roachtest: lib/pq failed [C-test-failure O-roachtest O-robot T-sql-foundations branch-release-22.2 release-blocker]
- #113263 roachtest: lib/pq failed [C-test-failure O-roachtest O-robot T-sql-foundations branch-master]
</p>
</details>
/cc @cockroachdb/sql-foundations
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*lib/pq.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)
</sub>

Jira issue: CRDB-33024

### LINKED ISSUE #113499: roachtest: lib/pq failed
roachtest.lib/pq [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/12428970?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/12428970?buildTab=artifacts#/lib/pq) on release-23.2 @ [348d11425a1184ce4de8a6f8dc85995cd3c653bc](https://github.com/cockroachdb/cockroach/commits/348d11425a1184ce4de8a6f8dc85995cd3c653bc):

```
(java_helpers.go:205).parseAndSummarizeJavaORMTestsResults: all attempts failed for fetching results file ~/logs/report/libpq-results/report.xml: COMMAND_PROBLEM: exit status 1
test artifacts and logs in: /artifacts/lib/pq/run_1
```
<p>Parameters: <code>ROACHTEST_arch=amd64</code>
, <code>ROACHTEST_cloud=gce</code>
, <code>ROACHTEST_cpu=4</code>
, <code>ROACHTEST_encrypted=false</code>
, <code>ROACHTEST_ssd=0</code>
</p>
<details><summary>Help</summary>
<p>

See: [roachtest README](https://github.com/cockroachdb/cockroach/blob/master/pkg/cmd/roachtest/README.md)

See: [How To Investigate \(internal\)](https://cockroachlabs.atlassian.net/l/c/SSSBr8c7)

See: [Grafana](https://go.crdb.dev/roachtest-grafana/teamcity-12428970/lib-pq/1698763785539/1698765879677)

</p>
</details>
<details><summary>Same failure on other branches</summary>
<p>

- #113497 roachtest: lib/pq failed [C-test-failure O-roachtest O-robot T-sql-foundations branch-release-23.1 release-blocker]
- #113390 roachtest: lib/pq failed [C-test-failure O-roachtest O-robot T-sql-foundations branch-release-22.2 release-blocker]
- #113263 roachtest: lib/pq failed [C-test-failure O-roachtest O-robot T-sql-foundations branch-master]
</p>
</details>
/cc @cockroachdb/sql-foundations
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*lib/pq.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)
</sub>

Jira issue: CRDB-33026

### PR DESCRIPTION
**Pull request by rafiss**
A recent change used single quotes in a command, which prevents ~ from
being expanded in path names. Now the $ characters are escaped, which
prevents them from being handled as environment variables, but
still allows ~ to be expanded.

fixes https://github.com/cockroachdb/cockroach/issues/113255
fixes https://github.com/cockroachdb/cockroach/issues/113263
fixes https://github.com/cockroachdb/cockroach/issues/113499
fixes https://github.com/cockroachdb/cockroach/issues/113497
fixes https://github.com/cockroachdb/cockroach/issues/113391
fixes https://github.com/cockroachdb/cockroach/issues/113390
fixes https://github.com/cockroachdb/cockroach/issues/113389
fixes https://github.com/cockroachdb/cockroach/issues/113383
Release note: None

### CODE REVIEW

**Review by andyyang890 — APPROVED** [review]

File: pkg/cmd/roachtest/tests/java_helpers.go [hunk 1]
```diff
@@ -192,7 +193,9 @@ func parseAndSummarizeJavaORMTestsResults(
 	for i, file := range files {
 		t.L().Printf("Parsing %d of %d: %s\n", i+1, len(files), file)
 		// NB: It is necessary to single quote the file name to prevent
-		// unintentional variable interpolation if the name contains $'s.
+		// unintentional variable interpolation if the name contains $'s. The
```
Comment (andyyang890) [inline pkg/cmd/roachtest/tests/java_helpers.go:196]: Actually I wonder if we should maybe replace instances of `$` with `\$` instead of single-quoting the file name

Comment (rafiss) [reply pkg/cmd/roachtest/tests/java_helpers.go]: done

**Comment by rafiss** [comment]
tftr!

bors r+
