### PR TITLE
*: force zone.o to link on macOS

### LINKED ISSUE #15272: server/status: CGO memory stats are broken on Mac OS X
Unlike the previous breakage where the stats were always zero, now they have non-zero constant values:

```
I170422 20:51:08.914979 42 server/status/runtime.go:225  [n1] runtime stats: 67 MiB RSS, 186 goroutines, 14 MiB/11 MiB/36 MiB GO alloc/idle/total, 258 KiB/408 KiB CGO alloc/total, 99.80cgo/sec, 0.01/0.00 %(u/s)time, 0.00 %gc (1x)
I170422 20:51:18.917336 42 server/status/runtime.go:225  [n1] runtime stats: 69 MiB RSS, 186 goroutines, 20 MiB/5.9 MiB/37 MiB GO alloc/idle/total, 258 KiB/408 KiB CGO alloc/total, 129.27cgo/sec, 0.01/0.00 %(u/s)time, 0.00 %gc (1x)
I170422 20:51:28.915687 42 server/status/runtime.go:225  [n1] runtime stats: 71 MiB RSS, 186 goroutines, 13 MiB/14 MiB/39 MiB GO alloc/idle/total, 258 KiB/408 KiB CGO alloc/total, 120.72cgo/sec, 0.01/0.00 %(u/s)time, 0.00 %gc (1x)
```

### PR DESCRIPTION
**Pull request by tamird**
This is the mechanism by which jemalloc hooks into `malloc` on macOS;
without it, jemalloc is not used.

Closes #15272.

### CODE REVIEW

**Comment by benesch** [comment]
I wonder why this didn't bite us with c-jemalloc, because Go also builds a static library out of each package, right? 

Also, I feel obligated to ask: you verified this actually works, yeah?

File: pkg/cli/start_jemalloc.go [hunk 1]
```diff
@@ -19,7 +19,8 @@
 package cli
 
 // #cgo CPPFLAGS: -DJEMALLOC_NO_DEMANGLE
-// #cgo LDFLAGS: -ljemalloc
+// #cgo !darwin LDFLAGS: -ljemalloc
+// #cgo darwin LDFLAGS: -ljemalloc -u_je_zone_register
```
Comment (petermattis) [inline pkg/cli/start_jemalloc.go]: Do you have to do this in all of the cgo directives? I would think this one would be sufficient.

**Review by petermattis — APPROVED** [review]

File: pkg/cli/start_jemalloc.go (hunk 1 above)
Comment (tamird) [inline pkg/cli/start_jemalloc.go]: Yes, one is sufficient, but do you think the inconsistency is worth it?

**Review by tamird — COMMENTED** [review]
> I wonder why this didn't bite us with c-jemalloc, because Go also builds a static library out of each package, right?

It's because cgo mashes all the object files into a single object file called `_all.o` before creating the static archive; the linker is only able to omit whole files, not single functions, so it is forced to keep everything.

> Also, I feel obligated to ask: you verified this actually works, yeah?

Yes.

File: pkg/cli/start_jemalloc.go (hunk 1 above)
Comment (petermattis) [inline pkg/cli/start_jemalloc.go]: Inconsistency doesn't bother me. I would have only made this change to `server/status/runtime_jemalloc.go` because that is the only one we care about. Also, add a comment explaining what is going on.

Comment (tamird) [inline pkg/cli/start_jemalloc.go]: What do you mean? The problem here is not a reporting problem; before this change, jemalloc is not being used in our macOS builds, period.

Added a comment.

Comment (petermattis) [inline pkg/cli/start_jemalloc.go]: >  before this change, jemalloc is not being used in our macOS builds, period.

Do we care other than the stats reporting? Btw, given that this is the second time this has broken, perhaps a small test is in order.

Comment (tamird) [inline pkg/cli/start_jemalloc.go]: Hm, this behaviour is specific to macOS, which we don't run CI on. How would we test it?

I think we care, even in the absence of stats reporting, but probably just for consistency with other platforms.

Comment (petermattis) [inline pkg/cli/start_jemalloc.go]: > Hm, this behaviour is specific to macOS, which we don't run CI on. How would we test it?

Developers run tests on macOS frequently. A test would have caught this very quickly. Also, seems possible for this to break on another platform as well.

Comment (petermattis) [inline pkg/cli/start_jemalloc.go]: PS I don't particularly care how many places you add `-u_je_zone_register`. The test is the more important bit.

Comment (tamird) [inline pkg/cli/start_jemalloc.go]: Added a test.

File: pkg/server/status/runtime_jemalloc.go [hunk 2]
```diff
@@ -120,3 +126,9 @@ func getJemallocStats(ctx context.Context) (uint, uint, error) {
 
 	return uint(js.Allocated), uint(js.Resident), nil
 }
+
+// Used to force allocation in tests.
+func allocateMemory() {
```
Comment (benesch) [inline pkg/server/status/runtime_jemalloc.go]: Why not put this in the test file?

**Review by petermattis — APPROVED** [review]
LGTM

**Comment by tamird** [comment]
Because `import "C"` is not supported in tests. Can't make this stuff up.
