### PR TITLE
tracing: remove panic in Finish

### LINKED ISSUE #83502: roachtest: follower-reads/mixed-version/single-region failed
roachtest.follower-reads/mixed-version/single-region [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/5582417?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/5582417?buildTab=artifacts#/follower-reads/mixed-version/single-region) on master @ [7f8fef4c3f24ec2b6f9a3db1eb38756da68b3d5a](https://github.com/cockroachdb/cockroach/commits/7f8fef4c3f24ec2b6f9a3db1eb38756da68b3d5a):

```
test artifacts and logs in: /artifacts/follower-reads/mixed-version/single-region/run_1
	follower_reads.go:295,follower_reads.go:901,follower_reads.go:102,test_runner.go:896: error verifying node values: dial tcp 34.148.137.234:26257: connect: connection refused
```
<p>Parameters: <code>ROACHTEST_cloud=gce</code>
, <code>ROACHTEST_cpu=2</code>
, <code>ROACHTEST_ssd=0</code>
</p>
<details><summary>Help</summary>
<p>

See: [roachtest README](https://github.com/cockroachdb/cockroach/blob/master/pkg/cmd/roachtest/README.md)

See: [How To Investigate \(internal\)](https://cockroachlabs.atlassian.net/l/c/SSSBr8c7)

</p>
</details>
/cc @cockroachdb/kv-triage
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*follower-reads/mixed-version/single-region.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)
</sub>

Jira issue: CRDB-17109

### PR DESCRIPTION
**Pull request by stevendanna**
In https://github.com/cockroachdb/cockroach/pull/81079, we added an assertion that failed if a child recording of a
RecordingStructured span had more than one span recording. However,
this is problematic for couple of reasons:

1) The assertion was on a code path shared with RecordingVerbose
   spans; and,

2) A RecordingStructured span can have a RecordingVerbose child. The
   RecordingVerbose child is likely to have more than one span recording.

As a result, we have seen roachtests failing with

    panic: RecordingStructured has 12 recordings; expected 1

Here, we remove the assertion.

Fixes #83502

Release note: None

### CODE REVIEW

File: pkg/util/tracing/crdbspan.go [hunk 1]
```diff
@@ -543,8 +543,13 @@ func (s *crdbSpan) recordFinishedChildrenLocked(childRecording tracingpb.Recordi
 		}
 
 		// We don't have space for this recording. Let's collect just the structured
-		// records by falling through.
-		fallthrough
+		// records.
+		for ci := range childRecording {
```
Comment (adityamaru) [inline pkg/util/tracing/crdbspan.go:547]: hmm was there another bug hiding in that we only collected the structured events from the root of a verbose recording if we ran out of space. When the comment indicates that we want to collect events from the whole recording. If thats the case do you think you can add this to the regression test where each child span can:

`child.RecordStructured(&types.Int32Value{Value: 4})`

and then right at the end we can `sp.FinishAndGetConfiguredRecording()` and check we have the right number of structured events?

**Review by adityamaru — APPROVED** [review]
Thanks for the fix 💯

**Review by andreimatei — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/83625)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @adityamaru, @andreimatei, and @stevendanna)

___
*[`pkg/util/tracing/crdbspan.go` line 547 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/83625#-N5lqeKBBENiyr0ko8ns:-N5lqeKCA3o1ORu4zuZQ:bajswtc) ([raw file](https://github.com/cockroachdb/cockroach/blob/d768e25adf1bc437e660bf8d2978c32ed98f7fc8/pkg/util/tracing/crdbspan.go#L547)):*
> ```Go
> 		// We don't have space for this recording. Let's collect just the structured
> 		// records.
> 		for ci := range childRecording {
> ```

I think a better fix is to get rid of the assertion in the structured case below, and make that code deal with multiple spans too. That's how it was before #81079, and I'm not sure if there was a specific reason why it changed.

I think it's important for all this code to be fairly permissive in what recording it accepts. For example, as written, I think this code would crash if an RPC is made within a `RecordingStructured` span, and then the remote child is dynamically changed via `\tracez` to `RecordingVerbose`: a verbose, multi-span recording will come back and the client span will choke on it.

Please add the following test with this occassion:

```
// Test that a RecordingStructured parent does not panic when asked to ingest a
// remote verbose recording. Ingesting a recording of different type is unusual,
// since children are created with the parent's recording mode, but it can
// happen if the child's recording mode was changed dynamically.
func TestRemoteSpanWithDifferentRecordingMode(t *testing.T) {
	tr := NewTracer()
	s1 := tr.StartSpan("p", WithRecording(tracingpb.RecordingStructured))
	s2 := tr.StartSpan("c", WithRemoteParentFromSpanMeta(s1.Meta()), WithRecording(tracingpb.RecordingVerbose))
	s3 := tr.StartSpan("cc", WithParent(s2), WithRecording(tracingpb.RecordingVerbose))
	s3.Finish()
	r := s2.FinishAndGetConfiguredRecording()
	require.NotPanic(s1.ImportRemoteRecording(r))
	s1.Finish()
}
```
___
*[`pkg/util/tracing/span_test.go` line 408 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/83625#-N5luhyx7tWZXIgIO_vJ:-N5luhyx7tWZXIgIO_vK:b-ja0p8h) ([raw file](https://github.com/cockroachdb/cockroach/blob/d768e25adf1bc437e660bf8d2978c32ed98f7fc8/pkg/util/tracing/span_test.go#L408)):*
> ```Go
> }
> 
> // TestRecordingFinishWithMaxSpans is a regression test to ensure that a verbose
> ```

let's rephrase this test as Aditya was suggesting, and then I don't have to nitpick about this comment.
Call it `TestRecordingDowngradesToStructuredIfTooBig` and check that you end up with a recording with just one or two spans or whatever, and all the structured events.

File: pkg/util/tracing/crdbspan.go (hunk 1 above)
Comment (stevendanna) [reply pkg/util/tracing/crdbspan.go:549]: Good idea, done.

**Review by stevendanna — COMMENTED** [review]
TFTR!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/83625#-:-N5nw31A68h3HQFPxgkM:b-814g8k)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @adityamaru and @andreimatei)

___
*[`pkg/util/tracing/crdbspan.go` line 547 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/83625#-N5lqeKBBENiyr0ko8ns:-N5nvjrKBSKX3-79wMlD:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/d768e25adf1bc437e660bf8d2978c32ed98f7fc8/pkg/util/tracing/crdbspan.go#L547)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

I think a better fix is to get rid of the assertion in the structured case below, and make that code deal with multiple spans too. That's how it was before #81079, and I'm not sure if there was a specific reason why it changed.

I think it's important for all this code to be fairly permissive in what recording it accepts. For example, as written, I think this code would crash if an RPC is made within a `RecordingStructured` span, and then the remote child is dynamically changed via `\tracez` to `RecordingVerbose`: a verbose, multi-span recording will come back and the client span will choke on it.

Please add the following test with this occassion:

```
// Test that a RecordingStructured parent does not panic when asked to ingest a
// remote verbose recording. Ingesting a recording of different type is unusual,
// since children are created with the parent's recording mode, but it can
// happen if the child's recording mode was changed dynamically.
func TestRemoteSpanWithDifferentRecordingMode(t *testing.T) {
	tr := NewTracer()
	s1 := tr.StartSpan("p", WithRecording(tracingpb.RecordingStructured))
	s2 := tr.StartSpan("c", WithRemoteParentFromSpanMeta(s1.Meta()), WithRecording(tracingpb.RecordingVerbose))
	s3 := tr.StartSpan("cc", WithParent(s2), WithRecording(tracingpb.RecordingVerbose))
	s3.Finish()
	r := s2.FinishAndGetConfiguredRecording()
	require.NotPanic(s1.ImportRemoteRecording(r))
	s1.Finish()
}
```
</blockquote></details>

Done.
___
*[`pkg/util/tracing/span_test.go` line 408 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/83625#-N5luhyx7tWZXIgIO_vJ:-N5nvqMI6H0pCr3HnDrD:buvrwfe) ([raw file](https://github.com/cockroachdb/cockroach/blob/d768e25adf1bc437e660bf8d2978c32ed98f7fc8/pkg/util/tracing/span_test.go#L408)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

let's rephrase this test as Aditya was suggesting, and then I don't have to nitpick about this comment.
Call it `TestRecordingDowngradesToStructuredIfTooBig` and check that you end up with a recording with just one or two spans or whatever, and all the structured events.
</blockquote></details>

Done. We don't get all of the structured events because of the size of the ring buffer, but I've checked that we get as many as possible given the size of the buffer.

**Review by andreimatei — COMMENTED** [review]
:lgtm: but let's wait for Aditya to seewhat he says about that assertion. I think at some point he was relying on it, but maybe that changed. 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/83625#-:-N5qdbNt7_jTyIxY_GJp:b-ef6dry)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @adityamaru, @andreimatei, and @stevendanna)

___
*[`pkg/util/tracing/span_test.go` line 460 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/83625#-N5qdRiqBcEPowAFuNhU:-N5qdRir3-fByi25y_dR:b-iisr2) ([raw file](https://github.com/cockroachdb/cockroach/blob/b94c14f40fe143ce364cfe614cc2df1171151d88/pkg/util/tracing/span_test.go#L460)):*
> ```Go
> 	s3.Finish()
> 	r := s2.FinishAndGetConfiguredRecording()
> 	require.NotPanics(t, func() { s1.ImportRemoteRecording(r) })
> ```

please also test that s1's recording only has one span in it

**Review by adityamaru — APPROVED** [review]

**Comment by stevendanna** [comment]
bors r=adityamaru,
