### PR TITLE
sql: add the array_to_string builtin

### LINKED ISSUE #23774: sql: implement array_to_string
I am building an application with PHP Yii2 Framework which has its ORM module. Yii2 already have a good PostgreSQL support so that wanted to use CockroachDB with Yii2 and unfortunately I am getting below error:

**ERROR:  unknown function: array_to_string()**

Any help would be appreciated.

Query is being run by Yii2 is

```sql
SELECT  d.nspname AS table_schema,
 c.relname AS table_name, 
a.attname AS column_name, 
COALESCE(td.typname, tb.typname, t.typname) AS data_type,
COALESCE(td.typtype, tb.typtype, t.typtype) AS type_type, 
a.attlen AS character_maximum_length,
 pg_catalog.col_description(c.oid, a.attnum) AS column_comment, 
a.atttypmod AS modifier, 
a.attnotnull = false AS is_nullable, 
CAST(pg_get_expr(ad.adbin, ad.adrelid) AS varchar) AS column_default,
 coalesce(pg_get_expr(ad.adbin, ad.adrelid) ~ 'nextval',false) AS is_autoinc,
 CASE 
WHEN COALESCE(td.typtype, tb.typtype, t.typtype) = 'e'::char 
THEN array_to_string((SELECT array_agg(enumlabel) 
   FROM pg_enum 
   WHERE enumtypid = COALESCE(td.oid, tb.oid, a.atttypid))::varchar[], ',') 
ELSE NULL 
 END AS enum_values,
 CASE atttypid  
WHEN 21 /*int2*/ THEN 16
 WHEN 23 /*int4*/ THEN 32 
WHEN 20 /*int8*/ THEN 64
 WHEN 1700 /*numeric*/ THEN  CASE 
  WHEN atttypmod = -1 THEN null
   ELSE ((atttypmod - 4) >> 16) & 65535  END
 WHEN 700 /*float4*/ THEN 24 /*FLT_MANT_DIG*/ 
WHEN 701 /*float8*/ THEN 53 /*DBL_MANT_DIG*/ 
ELSE null 
END AS numeric_precision, 
CASE 
WHEN atttypid IN (21, 23, 20) THEN 0
 WHEN atttypid IN (1700) THEN  CASE 
   WHEN atttypmod = -1 THEN null
    ELSE (atttypmod - 4) & 65535
 END
 ELSE null  END AS numeric_scale, 
CAST( information_schema._pg_char_max_length(information_schema._pg_truetypid(a, t), information_schema._pg_truetypmod(a, t))  AS numeric ) AS size, 
a.attnum = any (ct.conkey) as is_pkey, 
COALESCE(NULLIF(a.attndims, 0), NULLIF(t.typndims, 0), (t.typcategory='A')::int) AS dimension  
FROM  pg_class c 
LEFT JOIN pg_attribute a ON a.attrelid = c.oid 
LEFT JOIN pg_attrdef ad ON a.attrelid = ad.adrelid AND a.attnum = ad.adnum LEFT JOIN pg_type t ON a.atttypid = t.oid
 LEFT JOIN pg_type tb ON (a.attndims > 0 OR t.typcategory='A') AND t.typelem > 0 AND t.typelem = tb.oid OR t.typbasetype > 0 AND t.typbasetype = tb.oid 
LEFT JOIN pg_type td ON t.typndims > 0 AND t.typbasetype > 0 AND tb.typelem = td.oid 
LEFT JOIN pg_namespace d ON d.oid = c.relnamespace 
LEFT JOIN pg_constraint ct ON ct.conrelid = c.oid AND ct.contype = 'p' 
WHERE  a.attnum > 0 AND t.typname != '' AND c.relname = 'tbl_user'  AND d.nspname = 'public' 
ORDER BY  a.attnum;
```

### PR DESCRIPTION
**Pull request by jordanlewis**
This is used to join values in an array with a delimiter into a string,
with an optional null replacement string.

Fixes #23774.

Release note (sql change): add the array_to_string builtin function.

### CODE REVIEW

File: pkg/sql/sem/builtins/builtins.go [hunk 1]
```diff
@@ -3671,6 +3699,32 @@ func stringToArray(str string, delimPtr *string, nullStr *string) (tree.Datum, e
 	return result, nil
 }
 
+// arrayToString implements the array_to_string builtin - arr is joined using
+// delim. If nullStr is non-nil, NULL values in the array will be replaced by
+// it.
+func arrayToString(arr *tree.DArray, delimPtr *string, nullStr *string) (tree.Datum, error) {
```
Comment (knz) [inline pkg/sql/sem/builtins/builtins.go]: I seem to recall we have very similar code to produce the string representation of arrays for pgwire. Since your new implementation here is more general, is there a way to use it in pgwire now?

**Review by knz — APPROVED** [review]

File: pkg/sql/sem/builtins/builtins.go (hunk 1 above)
Comment (jordanlewis) [reply pkg/sql/sem/builtins/builtins.go]: There's a few small behavior differences (when to quote the inner vars). I don't see a strong reason to DRY these, I think it's simpler and more Go-y to leave them as-is. I think combining them will be annoying if we ever start supporting nested arrays properly.

**Comment by jordanlewis** [comment]
TFTR!

bors r+

**Comment by jordanlewis** [comment]
Docker network flake of some sort.

bors r+
