### PR TITLE
server, statusccl: de-flake span stats fan-out tests

### LINKED ISSUE #99559: pkg/ccl/serverccl/statusccl/statusccl_test: TestTenantStatusAPI failed
pkg/ccl/serverccl/statusccl/statusccl_test.TestTenantStatusAPI [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_StressBazel/9244922?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_StressBazel/9244922?buildTab=artifacts#/) on master @ [0fcc33bc2870961b9387999d8a9fed97fccbb2ae](https://github.com/cockroachdb/cockroach/commits/0fcc33bc2870961b9387999d8a9fed97fccbb2ae):

```
=== RUN   TestTenantStatusAPI
    test_log_scope.go:161: test logs captured to: /artifacts/tmp/_tmp/8bc2de686563d04c3522b0df244fc129/logTestTenantStatusAPI2330030715
=== CONT  TestTenantStatusAPI
    tenant_status_test.go:141: -- test log scope end --
CREATE UNIQUE INDEX test_pkey ON test_db1.public.test USING btree (k ASC)test logs left over in: /artifacts/tmp/_tmp/8bc2de686563d04c3522b0df244fc129/logTestTenantStatusAPI2330030715
--- FAIL: TestTenantStatusAPI (37.95s)
=== RUN   TestTenantStatusAPI/tenant_span_stats
    --- FAIL: TestTenantStatusAPI/tenant_span_stats (0.64s)
=== RUN   TestTenantStatusAPI/tenant_span_stats/test_KV_node_fan-out
    tenant_status_test.go:222: 
        	Error Trace:	pkg/ccl/serverccl/statusccl/statusccl_test/pkg/ccl/serverccl/statusccl/tenant_status_test.go:222
        	Error:      	Not equal: 
        	            	expected: 882
        	            	actual  : 900
        	Test:       	TestTenantStatusAPI/tenant_span_stats/test_KV_node_fan-out
        --- FAIL: TestTenantStatusAPI/tenant_span_stats/test_KV_node_fan-out (0.46s)
```
<p>Parameters: <code>TAGS=bazel,gss,deadlock</code>
</p>
<details><summary>Help</summary>
<p>

See also: [How To Investigate a Go Test Failure \(internal\)](https://cockroachlabs.atlassian.net/l/c/HgfXfJgM)
</p>
</details>
<details><summary>Same failure on other branches</summary>
<p>

- #92382 pkg/ccl/serverccl/statusccl/statusccl_test: TestTenantStatusAPI failed [A-observability-inf C-test-failure O-robot T-observability-inf branch-release-22.2]
</p>
</details>
/cc @cockroachdb/sql-observability @cockroachdb/multi-tenant
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*TestTenantStatusAPI.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)
</sub>

Jira issue: CRDB-25932

### LINKED ISSUE #99770: pkg/ccl/serverccl/statusccl/statusccl_test: TestTenantStatusAPI failed
pkg/ccl/serverccl/statusccl/statusccl_test.TestTenantStatusAPI [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_StressBazel/9283933?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_StressBazel/9283933?buildTab=artifacts#/) on release-23.1 @ [3551dc089ac3efcb3772df2109164dcb01e79d8f](https://github.com/cockroachdb/cockroach/commits/3551dc089ac3efcb3772df2109164dcb01e79d8f):

```
=== RUN   TestTenantStatusAPI
    test_log_scope.go:161: test logs captured to: /artifacts/tmp/_tmp/8bc2de686563d04c3522b0df244fc129/logTestTenantStatusAPI249676458
=== CONT  TestTenantStatusAPI
    tenant_status_test.go:141: -- test log scope end --
CREATE UNIQUE INDEX test_pkey ON test_db1.public.test USING btree (k ASC)test logs left over in: /artifacts/tmp/_tmp/8bc2de686563d04c3522b0df244fc129/logTestTenantStatusAPI249676458
--- FAIL: TestTenantStatusAPI (39.87s)
=== RUN   TestTenantStatusAPI/tenant_span_stats
    --- FAIL: TestTenantStatusAPI/tenant_span_stats (1.35s)
=== RUN   TestTenantStatusAPI/tenant_span_stats/test_KV_node_fan-out
    tenant_status_test.go:222: 
        	Error Trace:	pkg/ccl/serverccl/statusccl/statusccl_test/pkg/ccl/serverccl/statusccl/tenant_status_test.go:222
        	Error:      	Not equal: 
        	            	expected: 889
        	            	actual  : 892
        	Test:       	TestTenantStatusAPI/tenant_span_stats/test_KV_node_fan-out
        --- FAIL: TestTenantStatusAPI/tenant_span_stats/test_KV_node_fan-out (0.67s)
```
<p>Parameters: <code>TAGS=bazel,gss,deadlock</code>
</p>
<details><summary>Help</summary>
<p>

See also: [How To Investigate a Go Test Failure \(internal\)](https://cockroachlabs.atlassian.net/l/c/HgfXfJgM)
</p>
</details>
<details><summary>Same failure on other branches</summary>
<p>

- #99559 pkg/ccl/serverccl/statusccl/statusccl_test: TestTenantStatusAPI failed [C-test-failure O-robot T-cluster-observability branch-master]
- #92382 pkg/ccl/serverccl/statusccl/statusccl_test: TestTenantStatusAPI failed [A-observability-inf C-test-failure O-robot T-observability-inf branch-release-22.2]
</p>
</details>
/cc @cockroachdb/sql-observability @cockroachdb/multi-tenant
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*TestTenantStatusAPI.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)
</sub>

Jira issue: CRDB-26064

### PR DESCRIPTION
**Pull request by zachlite**
This commit fixes flaky behavior while running
`TestSpanStatsFanOut` and `TestTenantSpanStats` under stress.

Both tests have been updated to ensure the following behavior:
- The tests make sure range splits occur before proceeding.
- The tests will retry their assertions to give the new key-value pairs time to replicate.

Additionally, `NewTestTenantHelper` was updated to accept a parameter for the number of nodes in the test host cluster. `TestTenantSpanStats` now uses a 3-node cluster to test a real fan-out.

Resolves #99770
Resolves #99559
Epic:none
Release note: None

### CODE REVIEW

File: pkg/ccl/serverccl/tenant_test_utils.go [hunk 1]
```diff
@@ -141,7 +141,7 @@ var _ TenantTestHelper = &tenantTestHelper{}
 
 // NewTestTenantHelper constructs a TenantTestHelper instance.
 func NewTestTenantHelper(
-	t *testing.T, tenantClusterSize int, knobs base.TestingKnobs,
+	t *testing.T, tenantClusterSize int, numNodes int, knobs base.TestingKnobs,
```
Comment (knz) [inline pkg/ccl/serverccl/tenant_test_utils.go:144]: This API is sus...
(it was already somewhat sus before your change)

This parameter "tenantClusterSize" indicates the number of tenant servers to start _connecting to a single KV node_.  

On the one hand I get that the original goal was simply to obtain a test framework where there were multiple SQL pods running side-by-side. 
On the other hand, this is not a realistic deployment scenario -- in practice a cluster should have multiple nodes. Multiple tenant servers on top of a one-node CockroachDB cluster is not very representative.

What should we do about this?

I'm not exactly sure, but the API extension you're proposing here is adding a problem on top of another problem: now with your change, if someone specifies "tenantClusterSize=3" and "numNodes=3" they get 9 SQL servers, and I don't think that's what we want.

If I were you I would reason about this backwards: as a CRL developer, what am I trying to achieve with my test code?

It seems to me (if my reading is right) that we want 
1) some tests in this package want multiple SQL servers
2) some tests need multiple KV nodes
3) there's no test that really _requires_ to have just 1 KV node or 1 SQL server

So why not... removing these 2 parameters altogether, and always start a 3-node storage cluster with 1 tenant server per node?

Comment (knz) [reply pkg/ccl/serverccl/tenant_test_utils.go:144]: @herkolategan can I get your input on this too? Thanks

**Review by herkolategan — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/106551)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dhartunian and @knz)

___
*[`pkg/ccl/serverccl/tenant_test_utils.go` line 144 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/106551#gh-1259310356:-N_3E3Z_4khvTyWU1hkt:bxwbmuw) ([raw file](https://github.com/cockroachdb/cockroach/blob/68753c7ac3b0319611e2e1bf68d38e2a7b8b8b14/pkg/ccl/serverccl/tenant_test_utils.go#L144)):*
<details><summary><i>Previously, knz (Raphael 'kena' Poss) wrote…</i></summary><blockquote>

@herkolategan can I get your input on this too? Thanks
</blockquote></details>

Something about selecting the first server and then starting tenants against it feels off to me, especially when `numNodes > 1`. 
Looking at https://github.com/cockroachdb/cockroach/blob/master/pkg/server/testserver.go#L1058 this selects one KV node.
It would be better if tenants had the full list of KV nodes when starting on top of a host test cluster. But I think @knz is right, this is a compounding problem.

Outside the scope of this PR, but in general I think `TestCluster` needs an overhaul to have proper virtual cluster support (multiple tenants). It already has methods like `WaitForTenantCapabilities`. Instead of having separate utility classes for managing tenants on top of test clusters we should provide a more general solution accessible to other parts of the codebase as well.

**Review by knz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/106551)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dhartunian and @herkolategan)

___
*[`pkg/ccl/serverccl/tenant_test_utils.go` line 144 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/106551#gh-1259310356:-N_4B48J68007xNGpxPD:bs7wmae) ([raw file](https://github.com/cockroachdb/cockroach/blob/68753c7ac3b0319611e2e1bf68d38e2a7b8b8b14/pkg/ccl/serverccl/tenant_test_utils.go#L144)):*
<details><summary><i>Previously, herkolategan (Herko Lategan) wrote…</i></summary><blockquote>

Something about selecting the first server and then starting tenants against it feels off to me, especially when `numNodes > 1`. 
Looking at https://github.com/cockroachdb/cockroach/blob/master/pkg/server/testserver.go#L1058 this selects one KV node.
It would be better if tenants had the full list of KV nodes when starting on top of a host test cluster. But I think @knz is right, this is a compounding problem.

Outside the scope of this PR, but in general I think `TestCluster` needs an overhaul to have proper virtual cluster support (multiple tenants). It already has methods like `WaitForTenantCapabilities`. Instead of having separate utility classes for managing tenants on top of test clusters we should provide a more general solution accessible to other parts of the codebase as well.
</blockquote></details>

Thanks Herko.

In the interest of helping Zach make progress here, could you advise what is the smallest amount of incremental improvement that Zach can do in this PR, ahead of making the testserver API better?

Then, separately, I would welcome you explaining what you recommend for the API into a new (separate) issue under epic CRDB-18499. Cheers

**Review by zachlite — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/106551)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @herkolategan and @knz)

___
*[`pkg/ccl/serverccl/tenant_test_utils.go` line 144 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/106551#gh-1259310356:-N_4Uc0l9yk_mp5gOr6P:b78zr0x) ([raw file](https://github.com/cockroachdb/cockroach/blob/68753c7ac3b0319611e2e1bf68d38e2a7b8b8b14/pkg/ccl/serverccl/tenant_test_utils.go#L144)):*
<details><summary><i>Previously, knz (Raphael 'kena' Poss) wrote…</i></summary><blockquote>

Thanks Herko.

In the interest of helping Zach make progress here, could you advise what is the smallest amount of incremental improvement that Zach can do in this PR, ahead of making the testserver API better?

Then, separately, I would welcome you explaining what you recommend for the API into a new (separate) issue under epic CRDB-18499. Cheers
</blockquote></details>

Thanks for catching this.

Since the the primary goal of this PR is to de-flake the mentioned tests, I'll revert the change I made to `newTestTenantHelper`.

The fan-out path is already covered by the tests in `pkg/server`, so I think the status quo (sans the flakes :smile: ) is acceptable here.

**Review by herkolategan — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/106551)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @herkolategan and @knz)

___
*[`pkg/ccl/serverccl/tenant_test_utils.go` line 144 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/106551#gh-1259310356:-N_4l4YAEvZ78Cg3aS9n:b-3e9n65) ([raw file](https://github.com/cockroachdb/cockroach/blob/68753c7ac3b0319611e2e1bf68d38e2a7b8b8b14/pkg/ccl/serverccl/tenant_test_utils.go#L144)):*
<details><summary><i>Previously, zachlite wrote…</i></summary><blockquote>

Thanks for catching this.

Since the the primary goal of this PR is to de-flake the mentioned tests, I'll revert the change I made to `newTestTenantHelper`.

The fan-out path is already covered by the tests in `pkg/server`, so I think the status quo (sans the flakes :smile: ) is acceptable here.


</blockquote></details>

Given the current state of things I think it's best just to fix the flake as @zachlite mentioned (Thanks!).
@knz I'll create an issue under the CRDB-18499 epic.

**Review by knz — APPROVED** [review]
> Reviewed 1 of 5 files at r1, 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/106551)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @zachlite)
