### PR TITLE
security: only perform strict validation on first certificate.

### LINKED ISSUE #38146: Certificate validation error when using intermediate CA certificates
**Describe the problem**

There is a regression in CockroachDB 2.1.x: TLS artifacts (certificate and key files) that worked with 2.0.7 and stopped working with 2.1.7.

We're deploying CockroachDB with a custom `client.root.crt` certificate signed by an intermediate CA certificate.
To create a valid certificate chain for authentication the `client.root.crt` file contains the end entity certificate with `CN=root` followed by the intermediate CA certificates with their own CN's.
This TLS artifact configuration for CockroachDB worked for us with 2.0 but stopped working with 2.1.

We see the following error with CockroachDB 2.1.7:

```
W190612 13:25:01.490332 1 security/certificate_loader.go:331  could not parse certificate for /run/dcos/pki/cockroach/client.root.crt: failed to validate certificate 1 in file client.root.crt: client certificate has Subject "CN=Integration Test Intermediate CA 02", expected "CN=root" (must match filename)
Error: connections with user root must use a client certificate
```

We've figured out that the reason our configuration stopped working was introduced with PR #24687.
CockroachDB's own SQL client now checks for the CN field for each certificate in the certificate chain in `client.root.crt` file to match the user name `root`.

Notably, this error does not seem to happen as part of a TLS handshake, but merely as part of a well-intended configuration validation check.
Once we removed the validation CockroachDB 2.1 works just as well as 2.0 did for our configuration.

```
diff --git a/pkg/security/certificate_loader.go b/pkg/security/certificate_loader.go
index 25a72bcf7e..def0fa9ff7 100644
--- a/pkg/security/certificate_loader.go
+++ b/pkg/security/certificate_loader.go
@@ -416,9 +416,6 @@ func parseCertificate(ci *CertInfo) error {
 			return makeErrorf(err, "failed to parse certificate %d in file %s", i, ci.Filename)
 		}
 
-		if err := validateCockroachCertificate(ci, x509Cert); err != nil {
-			return makeErrorf(err, "failed to validate certificate %d in file %s", i, ci.Filename)
-		}
 		if i == 0 {
 			// The first certificate is the effective one; use its expiration time.
 			expires = x509Cert.NotAfter
```

Details of any intermediate certificate should not be validated for these fields as there is no way to know in advance what the CN (and other details) should be.
The expected behavior would be to only check the CN field of the first certificate of the chain (`end entity certificate`), if anything.

In case of using a root certificate and no intermediate certificates to sign the client certificate CockroachDB 2.1.7 behaves correctly.
In that case `client.root.crt` only contains a single certificate with `CN` set to `root`.

**To Reproduce**

We are not providing a full reproduction because this is a lot of effort and we believe that the description may be clear enough for the problem to be understood.
However, if the description is not clear enough for a change to be made, we will create and share such a reproduction.

**Expected behavior**

We expected no error to be shown for the described configuration.

**Environment:**

 - CockroachDB version [e.g. 2.1.7] (we expect that this is also an issue in more recent versions, given code we have read)
 - Server OS: [e.g. CentOS 7] (we expect this to not be relevant)
 - Client app [`cockroach sql`]

**Additional context**

We cannot update DC/OS Enterprise to a recent CockroachDB version without a patch.
This is because one cannot access the database of a secure CockroachDB cluster with an intermediate certificate.

### PR DESCRIPTION
**Pull request by mberhault**
Fixes #38146.

If a client or node certificate includes intermediates, we used to
apply the same strict validation to the intermediates as well. This
will fail on invalid CommonName.

Now also return error when part of the certificate file could not be
parsed.

Release note: (security): only check CN on first certificate in file

### CODE REVIEW

File: pkg/security/pem.go [hunk 1]
```diff
@@ -100,6 +100,9 @@ func PEMToCertificates(contents []byte) ([]*pem.Block, error) {
 		var block *pem.Block
 		block, contents = pem.Decode(contents)
 		if block == nil {
+			if len(contents) > 0 {
+				return nil, errors.Errorf("block #%d could not be parsed", len(certs))
```
Comment (mberhault) [inline pkg/security/pem.go]: This check is stricter than it used to be. If we still want to make use of the certificates seen so far, we could just log a warning.

**Review by bdarnell — APPROVED** [review]
> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/38163)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @mberhault)

___
*[pkg/security/pem.go, line 104 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/38163#-LhLTbC3-MC97FPIB7KX-r1-104:-LhLZMJ727awvNgj7cKs:b-dg5trz) ([raw file](https://github.com/cockroachdb/cockroach/blob/72ae2517e20a070b36b22ccee42d8604ebe74ce3/pkg/security/pem.go#L104)):*
<details><summary><i>Previously, mberhault (marc) wrote…</i></summary><blockquote>

This check is stricter than it used to be. If we still want to make use of the certificates seen so far, we could just log a warning.
</blockquote></details>

What motivated this change? What kind of problem can lead to this path being taken? 

This sounds like a good change, but it might be safest to make it a separate commit. (So we can backport the other changes but keep this part for 19.2 only).

**Review by mberhault — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/38163)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @bdarnell)

___
*[pkg/security/pem.go, line 104 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/38163#-LhLTbC3-MC97FPIB7KX-r1-104:-LhLeHSP8bu8znTEwsuE:bdj2vce) ([raw file](https://github.com/cockroachdb/cockroach/blob/72ae2517e20a070b36b22ccee42d8604ebe74ce3/pkg/security/pem.go#L104)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

What motivated this change? What kind of problem can lead to this path being taken? 

This sounds like a good change, but it might be safest to make it a separate commit. (So we can backport the other changes but keep this part for 19.2 only). 
</blockquote></details>

I was poking at the test case that adds junk after the certificate and found the handling had changed. It also seems dependent on the version I'm running (pem validation has had some tweaks over the last two years).
I removed it from this PR (including the entire test case) and will put it on a separate one. I would say we want a warning at the very least.

**Comment by mberhault** [comment]
TFTR. Are you ok with backporting to both 19.1 and 2.1?

**Comment by bdarnell** [comment]
Yes, this should be backported to both branches.
