### PR TITLE
sql/jobs: fix races in TestRegistryResumeExpiredLease

### LINKED ISSUE #20623: sql/jobs: TestRegistryResumeExpiredLease flake
Buncha errors like:

E171210 02:49:57.748507 2349 sql/jobs/registry.go:206  error while adopting jobs: current lease node_id:2 epoch:1  did not match expected lease node_id:1 epoch:1 

https://teamcity.cockroachdb.com/viewLog.html?buildId=436950&tab=buildResultsDiv&buildTypeId=Cockroach_UnitTests_Test

### PR DESCRIPTION
**Pull request by madelynnblue**
Release note: None

Sometimes jobs will resume more times than usual. Move lock and
unlocking to places to prevent deadlocks. Move the done close to
a place that will allow all jobs to proceed without receiving from
resumeCalled.

Fixes #20623

### CODE REVIEW

File: pkg/sql/jobs/registry_external_test.go [hunk 1]
```diff
@@ -175,31 +174,35 @@ func TestRegistryResumeExpiredLease(t *testing.T) {
...
 
 	nodeLiveness.FakeIncrementEpoch(3)
 	<-resumeCalled
+	close(done)
 	testutils.SucceedsSoon(t, func() error {
 		lock.Lock()
-		if e, a := 2, resumeCounts[jobMap[3]]; e != a {
+		defer lock.Unlock()
+		if e, a := 2, resumeCounts[jobMap[3]]; e > a {
 			return errors.Errorf("expected resumeCount to be %d, but got %d", e, a)
```
Comment (benesch) [inline pkg/sql/jobs/registry_external_test.go]: Ideally the error message would be updated a la `expected hookCallCount to be > %d, but got %d`.

**Review by benesch — APPROVED** [review]
