### PR TITLE
server: hold tenant stopper until serveConn completes

### LINKED ISSUE #168117: pkg/crosscluster/logical/txnmode/txnmode_test: TestTxnModeSmoketest failed
pkg/crosscluster/logical/txnmode/txnmode_test.TestTxnModeSmoketest [failed](https://mesolite.cluster.engflow.com/invocations/default/e9a60136-87db-4022-92bb-a53e885bc230?testReportRun=1&testReportShard=1&testReportAttempt=1#targets-Ly9wa2cvY3Jvc3NjbHVzdGVyL2xvZ2ljYWwvdHhubW9kZTp0eG5tb2RlX3Rlc3Q=) on master @ [596ed4c7e3a48146619358799898ac4a2face0e1](https://github.com/cockroachdb/cockroach/commits/596ed4c7e3a48146619358799898ac4a2face0e1):

Fatal error:

```
panic: pebble: closed [recovered, repanicked]
	panic: found 1 short-living non-stopped monitors in exec
	exec 20 KiB
	    flow-3064688e 20 KiB
	 [recovered]
	panic: found 1 short-living non-stopped monitors in exec
	exec 20 KiB
	    flow-3064688e 20 KiB
	

```
Stack: 

```
goroutine 8116 [running]:
github.com/cockroachdb/cockroach/pkg/util/mon.(*BytesMonitor).doStop(0xc0045b6bb0, {0xd161690, 0xc00e97b2c0}, 0x0)
	pkg/util/mon/bytes_usage.go:781 +0xa9c
github.com/cockroachdb/cockroach/pkg/util/mon.(*BytesMonitor).EmergencyStop(...)
	pkg/util/mon/bytes_usage.go:717
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).close(0xc00511e508, {0xd161690, 0xc00e97b2c0}, 0x1)
	pkg/sql/conn_executor.go:1520 +0xdf8
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).closeWrapper(0xc00511e508, {0xd161690, 0xc00e97b2c0}, {0xb1e6400, 0xc014d7ad10})
	pkg/sql/conn_executor.go:1408 +0x227
github.com/cockroachdb/cockroach/pkg/sql.(*Server).ServeConn.func1({0xd161690, 0xc00e97b2c0}, {0x4b60a5?})
	pkg/sql/conn_executor.go:1126 +0x4b
panic({0xb1e6400?, 0xc014d7ad10?})
	GOROOT/src/runtime/panic.go:783 +0x132
github.com/cockroachdb/cockroach/pkg/util/mon.(*BytesMonitor).doStop(0xc0045b6bb0, {0xd161690, 0xc00fbcdb80}, 0x1)
	pkg/util/mon/bytes_usage.go:781 +0xa9c
github.com/cockroachdb/cockroach/pkg/util/mon.(*BytesMonitor).Stop(...)
	pkg/util/mon/bytes_usage.go:722
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).dispatchToExecutionEngine.func1()
	pkg/sql/conn_executor_exec.go:2932 +0x3c5
panic({0xb2dbfe0?, 0xc0038bca20?})
	GOROOT/src/runtime/panic.go:783 +0x132
github.com/cockroachdb/cockroach/pkg/sql/colexecerror.CatchVectorizedRuntimeError.func1()
	pkg/sql/colexecerror/error.go:137 +0x81a
panic({0xb2dbfe0?, 0xc0038bca20?})
	GOROOT/src/runtime/panic.go:783 +0x132
github.com/cockroachdb/pebble.(*DB).applyInternal(0xc0043f4c08, 0xc02c047800, 0x133f6bbe, 0x0)
	external/com_github_cockroachdb_pebble/db.go:789 +0x9fd
github.com/cockroachdb/pebble.(*DB).Apply(...)
	external/com_github_cockroachdb_pebble/db.go:764
github.com/cockroachdb/pebble.(*DB).DeleteRange(0xc0043f4c08, {0xc01900d4d0, 0x1, 0x18}, {0xc0186174b8, 0x1, 0x1}, 0x133f6bbe)
	external/com_github_cockroachdb_pebble/db.go:667 +0xc5
github.com/cockroachdb/cockroach/pkg/storage.(*pebbleMap).Clear(0xc001b634a0)
	pkg/storage/disk_map.go:170 +0x1b3
github.com/cockroachdb/cockroach/pkg/storage.(*pebbleMap).Close(0xc001b634a0, {0xd161690, 0xc00fc04000})
	pkg/storage/disk_map.go:186 +0x45
github.com/cockroachdb/cockroach/pkg/crosscluster/producer.(*OrderedBuffer).Close(...)
	pkg/crosscluster/producer/ordered_buffer.go:278
github.com/cockroachdb/cockroach/pkg/crosscluster/producer.(*OrderedStreamHandler).Close(0xc0019154d0, {0xd161690, 0xc00fc04000})
	pkg/crosscluster/producer/ordered_event_stream.go:195 +0x10c
github.com/cockroachdb/cockroach/pkg/sql/rowexec.(*projectSetProcessor).close(0xc013faf888)
	pkg/sql/rowexec/project_set.go:356 +0x13c
github.com/cockroachdb/cockroach/pkg/sql/rowexec.(*projectSetProcessor).ConsumerClosed(0xc013faf888)
	pkg/sql/rowexec/project_set.go:365 +0x27
github.com/cockroachdb/cockroach/pkg/sql/execinfra.(*ProcessorBaseNoHelper).InternalClose(0xc0049edc08)
	pkg/sql/execinfra/processorsbase.go:983 +0x107
github.com/cockroachdb/cockroach/pkg/sql/colexec.(*Columnarizer).Close(0xc0049edc08, {0xc00118f96f?, 0xc018617760?})
	pkg/sql/colexec/columnarizer.go:301 +0xb8
github.com/cockroachdb/cockroach/pkg/sql/colexec.(*invariantsChecker).Close(0xc010a49630, {0xd160920, 0xc010a49540})
	pkg/sql/colexec/invariants_checker.go:137 +0x75
github.com/cockroachdb/cockroach/pkg/sql/colexec/colexecargs.(*CloserRegistry).Close.func1()
	pkg/sql/colexec/colexecargs/closer_registry.go:47 +0xd6
github.com/cockroachdb/cockroach/pkg/sql/colexecerror.CatchVectorizedRuntimeError(0xc018617950)
	pkg/sql/colexecerror/error.go:162 +0x79
github.com/cockroachdb/cockroach/pkg/sql/colexec/colexecargs.(*CloserRegistry).Close(0xc002a10e40, {0xd160920, 0xc010a49540})
	pkg/sql/colexec/colexecargs/closer_registry.go:45 +0x132
github.com/cockroachdb/cockroach/pkg/sql/colflow.(*vectorizedFlowCreator).cleanup(0xc00f60e580, {0xd160920, 0xc010a49540})
	pkg/sql/colflow/vectorized_flow.go:674 +0x58
github.com/cockroachdb/cockroach/pkg/sql/colflow.(*vectorizedFlow).Cleanup(0xc010e33e50, {0xd160920, 0xc010a49540})
	pkg/sql/colflow/vectorized_flow.go:386 +0x1f7
github.com/cockroachdb/cockroach/pkg/sql.(*DistSQLPlanner).Run.func3()
	pkg/sql/distsql_running.go:1022 +0x59
github.com/cockroachdb/cockroach/pkg/sql.(*DistSQLPlanner).Run(0xc00f34a6e0, {0xd160920, 0xc010a49540}, 0xc010d2a750, 0xc010d2a0d0, 0xc0022c6580, 0xc00eb7db08, 0xc00511f320, 0xc00ca5c698)
	pkg/sql/distsql_running.go:1088 +0x1c53
github.com/cockroachdb/cockroach/pkg/sql.(*DistSQLPlanner).PlanAndRun(0xc00f34a6e0, {0xd161690, 0xc00fbcdb80}, 0xc00511f320, 0xc010d2a750, 0xc010d2a0d0, {{0xd1a8d90, 0xc012ec6480}, 0x0}, 0xc00eb7db08, ...)
	pkg/sql/distsql_running.go:2397 +0x3a5
github.com/cockroachdb/cockroach/pkg/sql.(*DistSQLPlanner).PlanAndRunAll.func3(0xc00511ed48, 0xc00f34a6e0, {0xd161690, 0xc00fbcdb80}, 0xc00511f320, 0xc010d2a750, 0xc00eb7db08)
	pkg/sql/distsql_running.go:2096 +0x19d
github.com/cockroachdb/cockroach/pkg/sql.(*DistSQLPlanner).PlanAndRunAll(0xc00f34a6e0, {0xd161690, 0xc00fbcdb80}, 0xc00511f320, 0xc010d2a750, 0xc00511ed48, 0xc00eb7db08, 0x0)
	pkg/sql/distsql_running.go:2099 +0x359
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execWithDistSQLEngine(0xc00511e508, {0xd161690, 0xc00fbcdb80}, 0xc00511ed48, 0x3, {0x7f87054eb9a0, 0xc0037fcb60}, 0x0, 0xc004c175d8, 0x0)
	pkg/sql/conn_executor_exec.go:3694 +0xba5
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).dispatchToExecutionEngine(0xc00511e508, {0xd161690, 0xc00fbcdb80}, 0xc00511ed48, {0x7f87054eb9a0, 0xc0037fcb60})
	pkg/sql/conn_executor_exec.go:3185 +0x270e
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execStmtInOpenState(0xc00511e508, {0xd160920, 0xc010a490e0}, {{0xd18ff40, 0xc0105c0e10}, {0x0, 0x0, 0x0}, {0xc002c5e073, 0x34}, ...}, ...)
	pkg/sql/conn_executor_exec.go:1178 +0x69b6
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execStmt.func2({0xd160920, 0xc010a490e0})
	pkg/sql/conn_executor_exec.go:183 +0x185
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execWithProfiling(0xc00511e508, {0xd160920, 0xc010a490e0}, {0xd18ff40, 0xc0105c0e10}, 0xc01152a200, 0xc00ca5eb20)
	pkg/sql/conn_executor_exec.go:4766 +0x997
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execStmt(0xc00511e508, {0xd160920, 0xc010a490e0}, {{0xd18ff40, 0xc0105c0e10}, {0x0, 0x0, 0x0}, {0xc002c5e073, 0x34}, ...}, ...)
	pkg/sql/conn_executor_exec.go:182 +0xdbe
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execPortal(0xc00511e508, {0xd160920, 0xc010a490e0}, {{0xc002c5e0e6, 0x0}, 0xc01152a200, {0xc0137baea0, 0x2, 0x2}, {0xc00dbf97ee, ...}, ...}, ...)
	pkg/sql/conn_executor_exec.go:333 +0x73f
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execCmd.func2(0xc00ca5f5a8, 0xc00511e508, 0xc01861b6d8, 0xc01861b6c8, 0xc00ca5f6b0, 0xc00ca5f378, 0xc00ca5f728, 0xc01861b6f8)
	pkg/sql/conn_executor.go:2586 +0x1429
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execCmd(0xc00511e508)
	pkg/sql/conn_executor.go:2588 +0x11dd
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).run(0xc00511e508, {0xd161690, 0xc00e97b2c0}, 0xc00c7e20b0, 0xc00e86cbb8, 0xc01484dcc0)
	pkg/sql/conn_executor.go:2387 +0x409
github.com/cockroachdb/cockroach/pkg/sql.(*Server).ServeConn(0xc005443808, {0xd161690, 0xc00e97b2c0}, {0xc0171ec4d0?}, 0xc00e86cbb8, 0xc01484dcc0)
	pkg/sql/conn_executor.go:1128 +0x205
github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*conn).processCommands(0xc0037fc408, {0xd161690, 0xc00e97b2c0}, {0x0, 0x4, {0x1, {0xb8f5f7a, 0x3}, {0xc00d9c2cc0, 0x18}, ...}, ...}, ...)
	pkg/sql/pgwire/conn.go:254 +0x728
github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*Server).serveImpl.func4()
	pkg/sql/pgwire/server.go:1295 +0x211
created by github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*Server).serveImpl in goroutine 8088
	pkg/sql/pgwire/server.go:1292 +0xa39
```
<details><summary>Log preceding fatal error</summary>
<p>

```
*   | 	pkg/storage/disk_map.go:170
*   | github.com/cockroachdb/cockroach/pkg/storage.(*pebbleMap).Close
*   | 	pkg/storage/disk_map.go:186
*   | github.com/cockroachdb/cockroach/pkg/crosscluster/producer.(*OrderedBuffer).Close
*   | 	pkg/crosscluster/producer/ordered_buffer.go:278
*   | github.com/cockroachdb/cockroach/pkg/crosscluster/producer.(*OrderedStreamHandler).Close
*   | 	pkg/crosscluster/producer/ordered_event_stream.go:195
*   | github.com/cockroachdb/cockroach/pkg/sql/rowexec.(*projectSetProcessor).close
*   | 	pkg/sql/rowexec/project_set.go:356
*   | github.com/cockroachdb/cockroach/pkg/sql/rowexec.(*projectSetProcessor).ConsumerClosed
*   | 	pkg/sql/rowexec/project_set.go:365
*   | github.com/cockroachdb/cockroach/pkg/sql/execinfra.(*ProcessorBaseNoHelper).InternalClose
*   | 	pkg/sql/execinfra/processorsbase.go:983
*   | github.com/cockroachdb/cockroach/pkg/sql/colexec.(*Columnarizer).Close
*   | 	pkg/sql/colexec/columnarizer.go:301
*   | github.com/cockroachdb/cockroach/pkg/sql/colexec.(*invariantsChecker).Close
*   | 	pkg/sql/colexec/invariants_checker.go:137
*   | github.com/cockroachdb/cockroach/pkg/sql/colexec/colexecargs.(*CloserRegistry).Close.func1
*   | 	pkg/sql/colexec/colexecargs/closer_registry.go:47
*   | github.com/cockroachdb/cockroach/pkg/sql/colexecerror.CatchVectorizedRuntimeError
*   | 	pkg/sql/colexecerror/error.go:162
*   | github.com/cockroachdb/cockroach/pkg/sql/colexec/colexecargs.(*CloserRegistry).Close
*   | 	pkg/sql/colexec/colexecargs/closer_registry.go:45
*   | github.com/cockroachdb/cockroach/pkg/sql/colflow.(*vectorizedFlowCreator).cleanup
*   | 	pkg/sql/colflow/vectorized_flow.go:674
*   | github.com/cockroachdb/cockroach/pkg/sql/colflow.(*vectorizedFlow).Cleanup
*   | 	pkg/sql/colflow/vectorized_flow.go:386
*   | github.com/cockroachdb/cockroach/pkg/sql.(*DistSQLPlanner).Run.func3
*   | 	pkg/sql/distsql_running.go:1022
*   | github.com/cockroachdb/cockroach/pkg/sql.(*DistSQLPlanner).Run
*   | 	pkg/sql/distsql_running.go:1088
*   | github.com/cockroachdb/cockroach/pkg/sql.(*DistSQLPlanner).PlanAndRun
*   | 	pkg/sql/distsql_running.go:2397
*   | github.com/cockroachdb/cockroach/pkg/sql.(*DistSQLPlanner).PlanAndRunAll.func3
*   | 	pkg/sql/distsql_running.go:2096
*   | github.com/cockroachdb/cockroach/pkg/sql.(*DistSQLPlanner).PlanAndRunAll
*   | 	pkg/sql/distsql_running.go:2099
*   | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execWithDistSQLEngine
*   | 	pkg/sql/conn_executor_exec.go:3694
*   | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).dispatchToExecutionEngine
*   | 	pkg/sql/conn_executor_exec.go:3185
*   | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execStmtInOpenState
*   | 	pkg/sql/conn_executor_exec.go:1178
*   | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execStmt.func2
*   | 	pkg/sql/conn_executor_exec.go:183
* Wraps: (7) found 1 short-living non-stopped monitors in exec
*   | exec 20 KiB
*   |     flow-3064688e 20 KiB
* Error types: (1) *withstack.withStack (2) *safedetails.withSafeDetails (3) *safedetails.withSafeDetails (4) *withstack.withStack (5) *assert.withAssertionFailure (6) *withstack.withStack (7) *errutil.leafError
*
```
</p>
</details>

Parameters:
 - <code>attempt=1</code>
 - <code>race=true</code>
 - <code>run=1</code>
 - <code>shard=1</code>
<details><summary>Help</summary>
<p>

See also: [How To Investigate a Go Test Failure \(internal\)](https://cockroachlabs.atlassian.net/l/c/HgfXfJgM)
</p>
</details>
/cc @cockroachdb/cdc
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*TestTxnModeSmoketest.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/bazci/githubpost/issues)

</sub>

Jira issue: CRDB-62808

### LINKED ISSUE #168118: pkg/crosscluster/logical/txnmode/txnmode_test: TestTxnModeCreateLogicallyReplicated failed
pkg/crosscluster/logical/txnmode/txnmode_test.TestTxnModeCreateLogicallyReplicated [failed](https://mesolite.cluster.engflow.com/invocations/default/e9a60136-87db-4022-92bb-a53e885bc230?testReportRun=3&testReportShard=1&testReportAttempt=1#targets-Ly9wa2cvY3Jvc3NjbHVzdGVyL2xvZ2ljYWwvdHhubW9kZTp0eG5tb2RlX3Rlc3Q=) on master @ [596ed4c7e3a48146619358799898ac4a2face0e1](https://github.com/cockroachdb/cockroach/commits/596ed4c7e3a48146619358799898ac4a2face0e1):

Fatal error:

```
panic: pebble: closed
	panic: txn: no bytes to release, current 10240, free 1054720
	panic: found 1 short-living non-stopped monitors in exec
	exec 10 KiB
	    flow-ddc37417 0 B
	 [recovered]
	panic: found 1 short-living non-stopped monitors in exec
	exec 10 KiB
	    flow-ddc37417 0 B
	

```
Stack: 

```
goroutine 24131 [running]:
github.com/cockroachdb/cockroach/pkg/util/mon.(*BytesMonitor).doStop(0xc02cda1760, {0xd161690, 0xc022eff4a0}, 0x0)
	pkg/util/mon/bytes_usage.go:781 +0xa9c
github.com/cockroachdb/cockroach/pkg/util/mon.(*BytesMonitor).EmergencyStop(...)
	pkg/util/mon/bytes_usage.go:717
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).close(0xc00ccb1908, {0xd161690, 0xc022eff4a0}, 0x1)
	pkg/sql/conn_executor.go:1520 +0xdf8
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).closeWrapper(0xc00ccb1908, {0xd161690, 0xc022eff4a0}, {0xb1e6400, 0xc012b423f0})
	pkg/sql/conn_executor.go:1408 +0x227
github.com/cockroachdb/cockroach/pkg/sql.(*Server).ServeConn.func1({0xd161690, 0xc022eff4a0}, {0x4b60a5?})
	pkg/sql/conn_executor.go:1126 +0x4b
panic({0xb1e6400?, 0xc012b423f0?})
	GOROOT/src/runtime/panic.go:783 +0x132
github.com/cockroachdb/cockroach/pkg/util/mon.(*BytesMonitor).doStop(0xc02cda1760, {0xd161690, 0xc0108fc000}, 0x1)
	pkg/util/mon/bytes_usage.go:781 +0xa9c
github.com/cockroachdb/cockroach/pkg/util/mon.(*BytesMonitor).Stop(...)
	pkg/util/mon/bytes_usage.go:722
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).dispatchToExecutionEngine.func1()
	pkg/sql/conn_executor_exec.go:2932 +0x3c5
panic({0xb2dbfe0?, 0xc011a59d40?})
	GOROOT/src/runtime/panic.go:783 +0x132
github.com/cockroachdb/cockroach/pkg/util/log/logcrash.ReportOrPanic({0xd160920, 0xc0340085f0}, 0xc004cb8000, {0xba2cdba, 0x2c}, {0xc016fb6d90, 0x3, 0x3})
	pkg/util/log/logcrash/crash_reporting.go:434 +0x3a5
github.com/cockroachdb/cockroach/pkg/util/mon.(*BytesMonitor).releaseBytesLocked(0xc02cda16b0, {0xd160920, 0xc0340085f0}, 0x101800)
	pkg/util/mon/bytes_usage.go:1283 +0x1e8
github.com/cockroachdb/cockroach/pkg/util/mon.(*BytesMonitor).releaseBytes(0xc02cda16b0, {0xd160920, 0xc0340085f0}, 0x101800)
	pkg/util/mon/bytes_usage.go:1275 +0xa8
github.com/cockroachdb/cockroach/pkg/util/mon.(*BoundAccount).Close(0xc015efbcd8, {0xd160920, 0xc0340085f0})
	pkg/util/mon/bytes_usage.go:1107 +0x105
github.com/cockroachdb/cockroach/pkg/crosscluster/producer.(*eventStream).Close(0xc015efbc08, {0xd160920, 0xc0340085f0})
	pkg/crosscluster/producer/event_stream.go:273 +0x11f
github.com/cockroachdb/cockroach/pkg/crosscluster/producer.(*OrderedStreamHandler).Close(0xc0264a3710, {0xd160920, 0xc0340085f0})
	pkg/crosscluster/producer/ordered_event_stream.go:194 +0xaa
github.com/cockroachdb/cockroach/pkg/sql/rowexec.(*projectSetProcessor).close(0xc015efb508)
	pkg/sql/rowexec/project_set.go:356 +0x13c
github.com/cockroachdb/cockroach/pkg/sql/rowexec.(*projectSetProcessor).ConsumerClosed(0xc015efb508)
	pkg/sql/rowexec/project_set.go:365 +0x27
github.com/cockroachdb/cockroach/pkg/sql/execinfra.(*ProcessorBaseNoHelper).InternalClose(0xc00e581950)
	pkg/sql/execinfra/processorsbase.go:983 +0x107
github.com/cockroachdb/cockroach/pkg/sql/colflow.(*FlowCoordinator).close(0xc00e581950)
	pkg/sql/colflow/flow_coordinator.go:161 +0x29
github.com/cockroachdb/cockroach/pkg/sql/colflow.(*FlowCoordinator).ConsumerClosed(0xc00e581950)
	pkg/sql/colflow/flow_coordinator.go:168 +0x27
github.com/cockroachdb/cockroach/pkg/sql/execinfra.(*ProcessorBaseNoHelper).Close(...)
	pkg/sql/execinfra/processorsbase.go:784
github.com/cockroachdb/cockroach/pkg/sql/flowinfra.(*FlowBase).Cleanup(0xc02201a288, {0xd160920, 0xc0340085f0})
	pkg/sql/flowinfra/flow.go:688 +0xea
github.com/cockroachdb/cockroach/pkg/sql/colflow.(*vectorizedFlow).Cleanup(0xc016f43590, {0xd160920, 0xc0340085f0})
	pkg/sql/colflow/vectorized_flow.go:408 +0x59a
github.com/cockroachdb/cockroach/pkg/sql.(*DistSQLPlanner).Run.func3()
	pkg/sql/distsql_running.go:1022 +0x59
panic({0xb2dbfe0?, 0xc011a59c50?})
	GOROOT/src/runtime/panic.go:783 +0x132
github.com/cockroachdb/pebble.(*DB).applyInternal(0xc003f60008, 0xc035c68900, 0x133f6bbe, 0x0)
	external/com_github_cockroachdb_pebble/db.go:789 +0x9fd
github.com/cockroachdb/pebble.(*DB).Apply(...)
	external/com_github_cockroachdb_pebble/db.go:764
github.com/cockroachdb/pebble.(*DB).DeleteRange(0xc003f60008, {0xc00c82efa8, 0x1, 0x18}, {0xc016fb76d8, 0x1, 0x1}, 0x133f6bbe)
	external/com_github_cockroachdb_pebble/db.go:667 +0xc5
github.com/cockroachdb/cockroach/pkg/storage.(*pebbleMap).Clear(0xc0268f97d0)
	pkg/storage/disk_map.go:170 +0x1b3
github.com/cockroachdb/cockroach/pkg/storage.(*pebbleMap).Close(0xc0268f97d0, {0xd160920, 0xc0340085f0})
	pkg/storage/disk_map.go:186 +0x45
github.com/cockroachdb/cockroach/pkg/crosscluster/producer.(*OrderedBuffer).Close(...)
	pkg/crosscluster/producer/ordered_buffer.go:278
github.com/cockroachdb/cockroach/pkg/crosscluster/producer.(*OrderedStreamHandler).Close(0xc0264a3710, {0xd160920, 0xc0340085f0})
	pkg/crosscluster/producer/ordered_event_stream.go:195 +0x10c
github.com/cockroachdb/cockroach/pkg/sql/rowexec.(*projectSetProcessor).close(0xc015efb508)
	pkg/sql/rowexec/project_set.go:356 +0x13c
github.com/cockroachdb/cockroach/pkg/sql/rowexec.(*projectSetProcessor).ConsumerClosed(0xc015efb508)
	pkg/sql/rowexec/project_set.go:365 +0x27
github.com/cockroachdb/cockroach/pkg/sql/execinfra.(*ProcessorBaseNoHelper).InternalClose(0xc00e581950)
	pkg/sql/execinfra/processorsbase.go:983 +0x107
github.com/cockroachdb/cockroach/pkg/sql/colflow.(*FlowCoordinator).close(0xc00e581950)
	pkg/sql/colflow/flow_coordinator.go:161 +0x29
github.com/cockroachdb/cockroach/pkg/sql/colflow.(*FlowCoordinator).ConsumerClosed(0xc00e581950)
	pkg/sql/colflow/flow_coordinator.go:168 +0x27
github.com/cockroachdb/cockroach/pkg/sql/execinfra.Run({0xd160920, 0xc0340085f0}, {0xd1958c0, 0xc00e581950}, {0xd11e298, 0xc00f23d688})
	pkg/sql/execinfra/base.go:208 +0xa5
github.com/cockroachdb/cockroach/pkg/sql/execinfra.(*ProcessorBaseNoHelper).Run(0xc00e581950, {0xd160920, 0xc0340085f0}, {0xd11e298, 0xc00f23d688})
	pkg/sql/execinfra/processorsbase.go:771 +0xcd
github.com/cockroachdb/cockroach/pkg/sql/flowinfra.(*FlowBase).Run(0xc02201a288, {0xd160920, 0xc0340085f0}, 0x0)
	pkg/sql/flowinfra/flow.go:584 +0x767
github.com/cockroachdb/cockroach/pkg/sql/colflow.(*vectorizedFlow).Run(0xc016f43590, {0xd160920, 0xc0340085f0}, 0x0)
	pkg/sql/colflow/vectorized_flow.go:302 +0x373
github.com/cockroachdb/cockroach/pkg/sql.(*DistSQLPlanner).Run(0xc02479a2c0, {0xd160920, 0xc0340085f0}, 0xc0354fe000, 0xc0353b1930, 0xc00225c380, 0xc00f23d688, 0xc00ccb2720, 0xc00e420698)
	pkg/sql/distsql_running.go:1087 +0x1c4e
github.com/cockroachdb/cockroach/pkg/sql.(*DistSQLPlanner).PlanAndRun(0xc02479a2c0, {0xd161690, 0xc0108fc000}, 0xc00ccb2720, 0xc0354fe000, 0xc0353b1930, {{0xd1a8d90, 0xc026513e00}, 0x0}, 0xc00f23d688, ...)
	pkg/sql/distsql_running.go:2397 +0x3a5
github.com/cockroachdb/cockroach/pkg/sql.(*DistSQLPlanner).PlanAndRunAll.func3(0xc00ccb2148, 0xc02479a2c0, {0xd161690, 0xc0108fc000}, 0xc00ccb2720, 0xc0354fe000, 0xc00f23d688)
	pkg/sql/distsql_running.go:2096 +0x19d
github.com/cockroachdb/cockroach/pkg/sql.(*DistSQLPlanner).PlanAndRunAll(0xc02479a2c0, {0xd161690, 0xc0108fc000}, 0xc00ccb2720, 0xc0354fe000, 0xc00ccb2148, 0xc00f23d688, 0x0)
	pkg/sql/distsql_running.go:2099 +0x359
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execWithDistSQLEngine(0xc00ccb1908, {0xd161690, 0xc0108fc000}, 0xc00ccb2148, 0x3, {0x7f3fb7798708, 0xc02d66f760}, 0x0, 0xc004e3ece8, 0x0)
	pkg/sql/conn_executor_exec.go:3694 +0xba5
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).dispatchToExecutionEngine(0xc00ccb1908, {0xd161690, 0xc0108fc000}, 0xc00ccb2148, {0x7f3fb7798708, 0xc02d66f760})
	pkg/sql/conn_executor_exec.go:3185 +0x270e
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execStmtInOpenState(0xc00ccb1908, {0xd160920, 0xc0340082d0}, {{0xd18ff40, 0xc0164f8820}, {0x0, 0x0, 0x0}, {0xc00cbaf073, 0x34}, ...}, ...)
	pkg/sql/conn_executor_exec.go:1178 +0x69b6
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execStmt.func2({0xd160920, 0xc0340082d0})
	pkg/sql/conn_executor_exec.go:183 +0x185
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execWithProfiling(0xc00ccb1908, {0xd160920, 0xc0340082d0}, {0xd18ff40, 0xc0164f8820}, 0xc02558e200, 0xc00e422b20)
	pkg/sql/conn_executor_exec.go:4766 +0x997
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execStmt(0xc00ccb1908, {0xd160920, 0xc0340082d0}, {{0xd18ff40, 0xc0164f8820}, {0x0, 0x0, 0x0}, {0xc00cbaf073, 0x34}, ...}, ...)
	pkg/sql/conn_executor_exec.go:182 +0xdbe
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execPortal(0xc00ccb1908, {0xd160920, 0xc0340082d0}, {{0xc00cbaf0e6, 0x0}, 0xc02558e200, {0xc034ed53a0, 0x2, 0x2}, {0xc002d66abe, ...}, ...}, ...)
	pkg/sql/conn_executor_exec.go:333 +0x73f
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execCmd.func2(0xc00e4235a8, 0xc00ccb1908, 0xc016fbb6d8, 0xc016fbb6c8, 0xc00e4236b0, 0xc00e423378, 0xc00e423728, 0xc016fbb6f8)
	pkg/sql/conn_executor.go:2586 +0x1429
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execCmd(0xc00ccb1908)
	pkg/sql/conn_executor.go:2588 +0x11dd
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).run(0xc00ccb1908, {0xd161690, 0xc022eff4a0}, 0xc02c67dce0, 0xc027dee570, 0xc001f9a540)
	pkg/sql/conn_executor.go:2387 +0x409
github.com/cockroachdb/cockroach/pkg/sql.(*Server).ServeConn(0xc003c3a408, {0xd161690, 0xc022eff4a0}, {0xc017380790?}, 0xc027dee570, 0xc001f9a540)
	pkg/sql/conn_executor.go:1128 +0x205
github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*conn).processCommands(0xc02d66f008, {0xd161690, 0xc022eff4a0}, {0x0, 0x4, {0x1, {0xb8f5f7a, 0x3}, {0xc00e479140, 0x18}, ...}, ...}, ...)
	pkg/sql/pgwire/conn.go:254 +0x728
github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*Server).serveImpl.func4()
	pkg/sql/pgwire/server.go:1295 +0x211
created by github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*Server).serveImpl in goroutine 24081
	pkg/sql/pgwire/server.go:1292 +0xa39
```
<details><summary>Log preceding fatal error</summary>
<p>

```
*   | 	pkg/crosscluster/producer/ordered_event_stream.go:194
*   | github.com/cockroachdb/cockroach/pkg/sql/rowexec.(*projectSetProcessor).close
*   | 	pkg/sql/rowexec/project_set.go:356
*   | github.com/cockroachdb/cockroach/pkg/sql/rowexec.(*projectSetProcessor).ConsumerClosed
*   | 	pkg/sql/rowexec/project_set.go:365
*   | github.com/cockroachdb/cockroach/pkg/sql/execinfra.(*ProcessorBaseNoHelper).InternalClose
*   | 	pkg/sql/execinfra/processorsbase.go:983
*   | github.com/cockroachdb/cockroach/pkg/sql/colflow.(*FlowCoordinator).close
*   | 	pkg/sql/colflow/flow_coordinator.go:161
*   | github.com/cockroachdb/cockroach/pkg/sql/colflow.(*FlowCoordinator).ConsumerClosed
*   | 	pkg/sql/colflow/flow_coordinator.go:168
*   | github.com/cockroachdb/cockroach/pkg/sql/execinfra.(*ProcessorBaseNoHelper).Close
*   | 	pkg/sql/execinfra/processorsbase.go:784
*   | github.com/cockroachdb/cockroach/pkg/sql/flowinfra.(*FlowBase).Cleanup
*   | 	pkg/sql/flowinfra/flow.go:688
*   | github.com/cockroachdb/cockroach/pkg/sql/colflow.(*vectorizedFlow).Cleanup
*   | 	pkg/sql/colflow/vectorized_flow.go:408
*   | github.com/cockroachdb/cockroach/pkg/sql.(*DistSQLPlanner).Run.func3
*   | 	pkg/sql/distsql_running.go:1022
*   | runtime.gopanic
*   | 	GOROOT/src/runtime/panic.go:783
*   | github.com/cockroachdb/pebble.(*DB).applyInternal
*   | 	external/com_github_cockroachdb_pebble/db.go:789
*   | github.com/cockroachdb/pebble.(*DB).Apply
*   | 	external/com_github_cockroachdb_pebble/db.go:764
*   | github.com/cockroachdb/pebble.(*DB).DeleteRange
*   | 	external/com_github_cockroachdb_pebble/db.go:667
*   | github.com/cockroachdb/cockroach/pkg/storage.(*pebbleMap).Clear
*   | 	pkg/storage/disk_map.go:170
*   | github.com/cockroachdb/cockroach/pkg/storage.(*pebbleMap).Close
*   | 	pkg/storage/disk_map.go:186
*   | github.com/cockroachdb/cockroach/pkg/crosscluster/producer.(*OrderedBuffer).Close
*   | 	pkg/crosscluster/producer/ordered_buffer.go:278
*   | github.com/cockroachdb/cockroach/pkg/crosscluster/producer.(*OrderedStreamHandler).Close
*   | 	pkg/crosscluster/producer/ordered_event_stream.go:195
*   | github.com/cockroachdb/cockroach/pkg/sql/rowexec.(*projectSetProcessor).close
*   | 	pkg/sql/rowexec/project_set.go:356
*   | github.com/cockroachdb/cockroach/pkg/sql/rowexec.(*projectSetProcessor).ConsumerClosed
*   | 	pkg/sql/rowexec/project_set.go:365
*   | github.com/cockroachdb/cockroach/pkg/sql/execinfra.(*ProcessorBaseNoHelper).InternalClose
*   | 	pkg/sql/execinfra/processorsbase.go:983
*   | github.com/cockroachdb/cockroach/pkg/sql/colflow.(*FlowCoordinator).close
*   | 	pkg/sql/colflow/flow_coordinator.go:161
*   | github.com/cockroachdb/cockroach/pkg/sql/colflow.(*FlowCoordinator).ConsumerClosed
*   | 	pkg/sql/colflow/flow_coordinator.go:168
* Wraps: (7) found 1 short-living non-stopped monitors in exec
*   | exec 10 KiB
*   |     flow-ddc37417 0 B
* Error types: (1) *withstack.withStack (2) *safedetails.withSafeDetails (3) *safedetails.withSafeDetails (4) *withstack.withStack (5) *assert.withAssertionFailure (6) *withstack.withStack (7) *errutil.leafError
*
```
</p>
</details>

Parameters:
 - <code>attempt=1</code>
 - <code>race=true</code>
 - <code>run=3</code>
 - <code>shard=1</code>
<details><summary>Help</summary>
<p>

See also: [How To Investigate a Go Test Failure \(internal\)](https://cockroachlabs.atlassian.net/l/c/HgfXfJgM)
</p>
</details>
/cc @cockroachdb/cdc
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*TestTxnModeCreateLogicallyReplicated.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/bazci/githubpost/issues)

</sub>

Jira issue: CRDB-62809

### LINKED ISSUE #168132: pkg/crosscluster/logical/txnmode/txnmode_test: TestTxnModeUniqueConstraintUpdate failed
pkg/crosscluster/logical/txnmode/txnmode_test.TestTxnModeUniqueConstraintUpdate [failed](https://mesolite.cluster.engflow.com/invocations/default/3d1e0ce4-5b18-4c7f-869e-306a29ad5172?testReportRun=1&testReportShard=1&testReportAttempt=1#targets-Ly9wa2cvY3Jvc3NjbHVzdGVyL2xvZ2ljYWwvdHhubW9kZTp0eG5tb2RlX3Rlc3Q=) on master @ [d7f43f10758cc0c772a67a863cad69935f44d96c](https://github.com/cockroachdb/cockroach/commits/d7f43f10758cc0c772a67a863cad69935f44d96c):

Fatal error:

```
panic: pebble: closed [recovered, repanicked]
	panic: found 1 short-living non-stopped monitors in exec
	exec 20 KiB
	    flow-2dc6170b 20 KiB
	 [recovered]
	panic: found 1 short-living non-stopped monitors in exec
	exec 20 KiB
	    flow-2dc6170b 20 KiB
	

```
Stack: 

```
goroutine 13242 [running]:
github.com/cockroachdb/cockroach/pkg/util/mon.(*BytesMonitor).doStop(0xc02cefb550, {0x87dd550, 0xc01823c000}, 0x0)
	pkg/util/mon/bytes_usage.go:781 +0x653
github.com/cockroachdb/cockroach/pkg/util/mon.(*BytesMonitor).EmergencyStop(...)
	pkg/util/mon/bytes_usage.go:717
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).close(0xc004978f08, {0x87dd550, 0xc01823c000}, 0x1)
	pkg/sql/conn_executor.go:1520 +0x853
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).closeWrapper(0xc004978f08, {0x87dd550, 0xc01823c000}, {0x706f500?, 0xc0017d74b0?})
	pkg/sql/conn_executor.go:1408 +0x15a
github.com/cockroachdb/cockroach/pkg/sql.(*Server).ServeConn.func1({0x87dd550, 0xc01823c000}, {0xc00bfd7bc0?})
	pkg/sql/conn_executor.go:1126 +0x45
panic({0x706f500?, 0xc0017d74b0?})
	GOROOT/src/runtime/panic.go:783 +0x132
github.com/cockroachdb/cockroach/pkg/util/mon.(*BytesMonitor).doStop(0xc02cefb550, {0x87dd550, 0xc0170c4280}, 0x1)
	pkg/util/mon/bytes_usage.go:781 +0x653
github.com/cockroachdb/cockroach/pkg/util/mon.(*BytesMonitor).Stop(...)
	pkg/util/mon/bytes_usage.go:722
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).dispatchToExecutionEngine.func1()
	pkg/sql/conn_executor_exec.go:2932 +0x1e6
panic({0x7163ce0?, 0xc00f1f2eb8?})
	GOROOT/src/runtime/panic.go:783 +0x132
github.com/cockroachdb/cockroach/pkg/sql/colexecerror.CatchVectorizedRuntimeError.func1()
	pkg/sql/colexecerror/error.go:137 +0x546
panic({0x7163ce0?, 0xc00f1f2eb8?})
	GOROOT/src/runtime/panic.go:783 +0x132
github.com/cockroachdb/pebble.(*DB).applyInternal(0xc030496c08?, 0xc02bfd3bf0?, 0x1?, 0x0?)
	external/com_github_cockroachdb_pebble/db.go:789 +0x4c5
github.com/cockroachdb/pebble.(*DB).Apply(...)
	external/com_github_cockroachdb_pebble/db.go:764
github.com/cockroachdb/pebble.(*DB).DeleteRange(0xc030496c08, {0xc02bfd3bf0, 0x1, 0x30}, {0xc00bfd4be0, 0x1, 0x1}, 0xd71a6bd)
	external/com_github_cockroachdb_pebble/db.go:667 +0x9e
github.com/cockroachdb/cockroach/pkg/storage.(*pebbleMap).Clear(0xc01813f950)
	pkg/storage/disk_map.go:170 +0x109
github.com/cockroachdb/cockroach/pkg/storage.(*pebbleMap).Close(0xc003934008?, {0x87dd550, 0xc0170c4640})
	pkg/storage/disk_map.go:186 +0x25
github.com/cockroachdb/cockroach/pkg/crosscluster/producer.(*OrderedBuffer).Close(...)
	pkg/crosscluster/producer/ordered_buffer.go:278
github.com/cockroachdb/cockroach/pkg/crosscluster/producer.(*OrderedStreamHandler).Close(0xc017cb82d0, {0x87dd550, 0xc0170c4640})
	pkg/crosscluster/producer/ordered_event_stream.go:195 +0xd2
github.com/cockroachdb/cockroach/pkg/sql/rowexec.(*projectSetProcessor).close(0xc003921c08)
	pkg/sql/rowexec/project_set.go:356 +0x8e
github.com/cockroachdb/cockroach/pkg/sql/rowexec.(*projectSetProcessor).ConsumerClosed(0x4498b1d?)
	pkg/sql/rowexec/project_set.go:365 +0x13
github.com/cockroachdb/cockroach/pkg/sql/execinfra.(*ProcessorBaseNoHelper).InternalClose(0xc02e342708)
	pkg/sql/execinfra/processorsbase.go:983 +0x7e
github.com/cockroachdb/cockroach/pkg/sql/colexec.(*Columnarizer).Close(0xc0323a6c08?, {0xc0017d7310?, 0x4e77f2?})
	pkg/sql/colexec/columnarizer.go:301 +0x78
github.com/cockroachdb/cockroach/pkg/sql/colexec.(*invariantsChecker).Close(0xc00bfd4f10?, {0x87dc880?, 0xc0014de690?})
	pkg/sql/colexec/invariants_checker.go:137 +0x4b
github.com/cockroachdb/cockroach/pkg/sql/colexec/colexecargs.(*CloserRegistry).Close.func1()
	pkg/sql/colexec/colexecargs/closer_registry.go:47 +0x75
github.com/cockroachdb/cockroach/pkg/sql/colexecerror.CatchVectorizedRuntimeError(0xc032953c08?)
	pkg/sql/colexecerror/error.go:162 +0x4d
github.com/cockroachdb/cockroach/pkg/sql/colexec/colexecargs.(*CloserRegistry).Close(0x3d60226?, {0x87dc880, 0xc0014de690})
	pkg/sql/colexec/colexecargs/closer_registry.go:45 +0xd4
github.com/cockroachdb/cockroach/pkg/sql/colflow.(*vectorizedFlowCreator).cleanup(0xc003ca0b00, {0x87dc880, 0xc0014de690})
	pkg/sql/colflow/vectorized_flow.go:674 +0x29
github.com/cockroachdb/cockroach/pkg/sql/colflow.(*vectorizedFlow).Cleanup(0xc00e317800, {0x87dc880, 0xc0014de690})
	pkg/sql/colflow/vectorized_flow.go:386 +0xf2
github.com/cockroachdb/cockroach/pkg/sql.(*DistSQLPlanner).Run.func3()
	pkg/sql/distsql_running.go:1022 +0x27
github.com/cockroachdb/cockroach/pkg/sql.(*DistSQLPlanner).Run(0xc03197db80, {0x87dc880, 0xc0014de690}, 0xc02f7fb110, 0xc01805b980, 0xc017945880, 0xc00e40e908, 0xc004979d18, 0xc003d85940)
	pkg/sql/distsql_running.go:1088 +0xf58
github.com/cockroachdb/cockroach/pkg/sql.(*DistSQLPlanner).PlanAndRun(0xc03197db80, {0x87dd550, 0xc0170c4280}, 0xc004979d18, 0xc02f7fb110, 0xc01805b980, {{0x8824ad0, 0xc013daa720}, 0x0}, 0xc00e40e908, ...)
	pkg/sql/distsql_running.go:2397 +0x267
github.com/cockroachdb/cockroach/pkg/sql.(*DistSQLPlanner).PlanAndRunAll.func3(0xc003d859a6?, 0x0?, {0x87dd550?, 0xc0170c4280?}, 0x4483249?, 0x8824ad0?, 0xc013daa720?)
	pkg/sql/distsql_running.go:2096 +0xaf
github.com/cockroachdb/cockroach/pkg/sql.(*DistSQLPlanner).PlanAndRunAll(0xc03197db80, {0x87dd550, 0xc0170c4280}, 0xc004979d18, 0xc02f7fb110, 0xc004979740, 0xc00e40e908, 0x0)
	pkg/sql/distsql_running.go:2099 +0x205
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execWithDistSQLEngine(0xc004978f08, {0x87dd550, 0xc0170c4280}, 0xc004979740, 0x3?, {0x7f7802221ea8, 0xc002382b60}, 0x0, 0xc02e298c38, 0x0)
	pkg/sql/conn_executor_exec.go:3694 +0x465
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).dispatchToExecutionEngine(0xc004978f08, {0x87dd550, 0xc0170c4280}, 0xc004979740, {0x7f7802221ea8, 0xc002382b60})
	pkg/sql/conn_executor_exec.go:3185 +0x1313
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execStmtInOpenState(0xc004978f08, {0x87dc880?, 0xc001171db0?}, {{0x880b6e0, 0xc0011712c0}, {0x0, 0x0, 0x0}, {0xc002eff073, 0x34}, ...}, ...)
	pkg/sql/conn_executor_exec.go:1178 +0x3b32
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execStmt.func2({0x87dc880?, 0xc001171db0?})
	pkg/sql/conn_executor_exec.go:183 +0xaa
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execWithProfiling(0xc004978f08, {0x87dc880, 0xc001171db0}, {0x880b6e0, 0xc0011712c0}, 0xc017c9d600, 0xc003d87218)
	pkg/sql/conn_executor_exec.go:4766 +0x47e
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execStmt(0xc004978f08, {0x87dc880, 0xc001171db0}, {{0x880b6e0, 0xc0011712c0}, {0x0, 0x0, 0x0}, {0xc002eff073, 0x34}, ...}, ...)
	pkg/sql/conn_executor_exec.go:182 +0x805
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execPortal(0xc004978f08, {0x87dc880, 0xc001171db0}, {{0xc002eff0e6, 0x0}, 0xc017c9d600, {0xc02b8b1040, 0x2, 0x2}, {0xc02a985a0c, ...}, ...}, ...)
	pkg/sql/conn_executor_exec.go:333 +0x479
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execCmd.func2(0xc003d878e8, 0xc004978f08, 0xc00bfd79e0, 0xc00bfd79d0, 0xc003d87958, 0xc003d877f8, 0xc003d87a10, 0xc00bfd79f8)
	pkg/sql/conn_executor.go:2586 +0xadb
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execCmd(0xc004978f08)
	pkg/sql/conn_executor.go:2588 +0x81a
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).run(0xc004978f08, {0x87dd550, 0xc01823c000}, 0xf667c6?, 0x0?, 0xc02cf9d6b0?)
	pkg/sql/conn_executor.go:2387 +0x1f7
github.com/cockroachdb/cockroach/pkg/sql.(*Server).ServeConn(0xc03189f960?, {0x87dd550?, 0xc01823c000?}, {0xc0180b0370?}, 0x2?, 0x0?)
	pkg/sql/conn_executor.go:1128 +0xb9
github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*conn).processCommands(0xc002382408, {0x87dd550, 0xc01823c000}, {0x0, 0x4, {0x1, {0x77712ab, 0x3}, {0xc0341a33c0, 0x18}, ...}, ...}, ...)
	pkg/sql/pgwire/conn.go:254 +0x4b5
github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*Server).serveImpl.func4()
	pkg/sql/pgwire/server.go:1295 +0xec
created by github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*Server).serveImpl in goroutine 13219
	pkg/sql/pgwire/server.go:1292 +0x5b2
```
<details><summary>Log preceding fatal error</summary>
<p>

```
*   | 	pkg/storage/disk_map.go:170
*   | github.com/cockroachdb/cockroach/pkg/storage.(*pebbleMap).Close
*   | 	pkg/storage/disk_map.go:186
*   | github.com/cockroachdb/cockroach/pkg/crosscluster/producer.(*OrderedBuffer).Close
*   | 	pkg/crosscluster/producer/ordered_buffer.go:278
*   | github.com/cockroachdb/cockroach/pkg/crosscluster/producer.(*OrderedStreamHandler).Close
*   | 	pkg/crosscluster/producer/ordered_event_stream.go:195
*   | github.com/cockroachdb/cockroach/pkg/sql/rowexec.(*projectSetProcessor).close
*   | 	pkg/sql/rowexec/project_set.go:356
*   | github.com/cockroachdb/cockroach/pkg/sql/rowexec.(*projectSetProcessor).ConsumerClosed
*   | 	pkg/sql/rowexec/project_set.go:365
*   | github.com/cockroachdb/cockroach/pkg/sql/execinfra.(*ProcessorBaseNoHelper).InternalClose
*   | 	pkg/sql/execinfra/processorsbase.go:983
*   | github.com/cockroachdb/cockroach/pkg/sql/colexec.(*Columnarizer).Close
*   | 	pkg/sql/colexec/columnarizer.go:301
*   | github.com/cockroachdb/cockroach/pkg/sql/colexec.(*invariantsChecker).Close
*   | 	pkg/sql/colexec/invariants_checker.go:137
*   | github.com/cockroachdb/cockroach/pkg/sql/colexec/colexecargs.(*CloserRegistry).Close.func1
*   | 	pkg/sql/colexec/colexecargs/closer_registry.go:47
*   | github.com/cockroachdb/cockroach/pkg/sql/colexecerror.CatchVectorizedRuntimeError
*   | 	pkg/sql/colexecerror/error.go:162
*   | github.com/cockroachdb/cockroach/pkg/sql/colexec/colexecargs.(*CloserRegistry).Close
*   | 	pkg/sql/colexec/colexecargs/closer_registry.go:45
*   | github.com/cockroachdb/cockroach/pkg/sql/colflow.(*vectorizedFlowCreator).cleanup
*   | 	pkg/sql/colflow/vectorized_flow.go:674
*   | github.com/cockroachdb/cockroach/pkg/sql/colflow.(*vectorizedFlow).Cleanup
*   | 	pkg/sql/colflow/vectorized_flow.go:386
*   | github.com/cockroachdb/cockroach/pkg/sql.(*DistSQLPlanner).Run.func3
*   | 	pkg/sql/distsql_running.go:1022
*   | github.com/cockroachdb/cockroach/pkg/sql.(*DistSQLPlanner).Run
*   | 	pkg/sql/distsql_running.go:1088
*   | github.com/cockroachdb/cockroach/pkg/sql.(*DistSQLPlanner).PlanAndRun
*   | 	pkg/sql/distsql_running.go:2397
*   | github.com/cockroachdb/cockroach/pkg/sql.(*DistSQLPlanner).PlanAndRunAll.func3
*   | 	pkg/sql/distsql_running.go:2096
*   | github.com/cockroachdb/cockroach/pkg/sql.(*DistSQLPlanner).PlanAndRunAll
*   | 	pkg/sql/distsql_running.go:2099
*   | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execWithDistSQLEngine
*   | 	pkg/sql/conn_executor_exec.go:3694
*   | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).dispatchToExecutionEngine
*   | 	pkg/sql/conn_executor_exec.go:3185
*   | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execStmtInOpenState
*   | 	pkg/sql/conn_executor_exec.go:1178
*   | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execStmt.func2
*   | 	pkg/sql/conn_executor_exec.go:183
* Wraps: (7) found 1 short-living non-stopped monitors in exec
*   | exec 20 KiB
*   |     flow-2dc6170b 20 KiB
* Error types: (1) *withstack.withStack (2) *safedetails.withSafeDetails (3) *safedetails.withSafeDetails (4) *withstack.withStack (5) *assert.withAssertionFailure (6) *withstack.withStack (7) *errutil.leafError
*
```
</p>
</details>

Parameters:
 - <code>attempt=1</code>
 - <code>run=1</code>
 - <code>shard=1</code>
<details><summary>Help</summary>
<p>

See also: [How To Investigate a Go Test Failure \(internal\)](https://cockroachlabs.atlassian.net/l/c/HgfXfJgM)
</p>
</details>
/cc @cockroachdb/cdc
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*TestTxnModeUniqueConstraintUpdate.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/bazci/githubpost/issues)

</sub>

Jira issue: CRDB-62813

### PR DESCRIPTION
**Pull request by KeithCh**
We ran into a test failure where the tenant stopper runs before the 
serve conn finishes, which shut down the pebble instance in the temp 
engine before we were able to close a map backed the same pebble 
instance, resulting in a panic.

Fixes: #168117 
Fixes: #168132
Fixes: #168118
Release Note: None

### CODE REVIEW

**Review by aerfrei — APPROVED** [review]
Change looks good and makes sense to me. Getting approval from server too though might be nice. 

nit: In order to close multiple issues at the same time, each issue should have its own `Fixes` line iirc.

**Review by fqazi — APPROVED** [review]
:lgtm:

> @fqazi reviewed 1 file and all commit messages, and made 1 comment.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/168336#-:-OqC5pB64P8lK-bkidB_:bnfp4nl)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on jeffswenson).

File: pkg/server/server_controller_sql.go [hunk 1]
```diff
@@ -182,5 +183,11 @@ func (t *tenantServerWrapper) serveConn(
 ) error {
 	pgCtx := t.server.sqlServer.AnnotateCtx(context.Background())
 	pgCtx = logtags.AddTags(pgCtx, logtags.FromContext(ctx))
+	stopCtx, stopHandle, err := t.stopper.GetHandle(pgCtx, stop.TaskOpts{TaskName: "serve-conn"})
```
Comment (cthumuluru-crdb) [inline pkg/server/server_controller_sql.go:186]: While this looks good to me, the patten I see in every other place is to get a handle, launch a task, call activate and release in the new task.

File: pkg/server/server_controller_sql.go [hunk 2]
```diff
@@ -182,5 +183,11 @@ func (t *tenantServerWrapper) serveConn(
...
+	if err != nil {
+		return errors.Wrap(err, "error getting stop handle")
+	}
+	handle := stopHandle.Activate(stopCtx)
```
Comment (cthumuluru-crdb) [inline pkg/server/server_controller_sql.go:190]: What is the impact on tenant shutdown when there are idle connections?

File: pkg/server/server_controller_sql.go (hunk 1 above)
Comment (jeffswenson) [reply pkg/server/server_controller_sql.go:186]: This code path is a bit unique. Because the listner is shared by all tenants, we are starting on a goroutine that is part of the system tenant and we transition into code that is owned by the application tenant.

File: pkg/server/server_controller_sql.go (hunk 2 above)
Comment (KeithCh) [reply pkg/server/server_controller_sql.go:190]: The temp engine pebble instance will get shut down by the tenant before resources backed by the pebble instance shuts down, which causes a panic when the system runs its clean up flow to close said resources.

Comment (cthumuluru-crdb) [reply pkg/server/server_controller_sql.go:190]: Now I think about it, how idle connections impact tenant shutdown is unrelated to your changes.

**Review by cthumuluru-crdb — APPROVED** [review]
LGTM!

**Comment by KeithCh** [comment]
TFTRs!
