### PR TITLE
kvserver: deflake TestProcessSplitAfterRightHandSideHasBeenRemoved

### LINKED ISSUE #154313: kv/kvserver: TestProcessSplitAfterRightHandSideHasBeenRemoved failed
kv/kvserver.TestProcessSplitAfterRightHandSideHasBeenRemoved [failed](https://mesolite.cluster.engflow.com/invocations/default/a8746d11-a8b4-4d08-ae3c-df6471ece88c?testReportRun=2&testReportShard=1&testReportAttempt=1#targets-Ly9wa2cva3Yva3ZzZXJ2ZXI6a3ZzZXJ2ZXJfdGVzdA==) on master @ [299240d06a0bf6036c92ca18da148255342fa516](https://github.com/cockroachdb/cockroach/commits/299240d06a0bf6036c92ca18da148255342fa516):

```
=== RUN   TestProcessSplitAfterRightHandSideHasBeenRemoved
    test_log_scope.go:171: test logs captured to: outputs.zip/logTestProcessSplitAfterRightHandSideHasBeenRemoved3936177541
    test_log_scope.go:82: use -show-logs to present logs inline
    client_raft_test.go:5759: -- test log scope end --
test logs left over in: outputs.zip/logTestProcessSplitAfterRightHandSideHasBeenRemoved3936177541
--- FAIL: TestProcessSplitAfterRightHandSideHasBeenRemoved (412.44s)
=== RUN   TestProcessSplitAfterRightHandSideHasBeenRemoved/lease-type=LeaseExpiration
--- FAIL: TestProcessSplitAfterRightHandSideHasBeenRemoved/lease-type=LeaseExpiration (291.09s)
=== RUN   TestProcessSplitAfterRightHandSideHasBeenRemoved/lease-type=LeaseExpiration/(4)_initial_replica_RHS_partition,_with_restart
    client_raft_test.go:5741: condition failed to evaluate within 3m45s: from client_raft_test.go:5744: hard state not yet initialized: got 0, expected 10
--- FAIL: TestProcessSplitAfterRightHandSideHasBeenRemoved/lease-type=LeaseExpiration/(4)_initial_replica_RHS_partition,_with_restart (246.45s)
```

Parameters:
 - <code>attempt=1</code>
 - <code>race=true</code>
 - <code>run=2</code>
 - <code>shard=1</code>
<details><summary>Help</summary>
<p>

See also: [How To Investigate a Go Test Failure \(internal\)](https://cockroachlabs.atlassian.net/l/c/HgfXfJgM)
</p>
</details>
/cc @cockroachdb/kv-triage
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*TestProcessSplitAfterRightHandSideHasBeenRemoved.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/bazci/githubpost/issues)

</sub>

Jira issue: CRDB-54862

### PR DESCRIPTION
**Pull request by pav-kv**
The test relies on the fact that the LHS replica will be caught up via log, and run the split trigger. In the flake, the replica has been caught up by a snapshot. Likely cause is that the leader's log has been truncated while the replica has been partitioned away. The PR disables log truncation for this test, so that the catch up via log is guaranteed.

Fixes #154313

### CODE REVIEW

**Review by tbg — APPROVED** [review]
> @tbg reviewed 1 of 1 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/154444)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @pav-kv)

File: pkg/kv/kvserver/client_raft_test.go [hunk 1]
```diff
@@ -5396,6 +5396,11 @@ func TestProcessSplitAfterRightHandSideHasBeenRemoved(t *testing.T) {
 							// Newly-started stores (including the "rogue" one) should not GC
 							// their replicas. We'll turn this back on when needed.
 							DisableReplicaGCQueue: true,
+							// Some subtests, e.g. (4), expect that n1 catches up on the raft
+							// log after a partition, and runs the split trigger. Disable raft
+							// log truncation to make sure that it doesn't miss the split
+							// trigger by being caught up by a later snapshot. See #154313.
+							DisableRaftLogQueue:   true,
```
Comment (pav-kv) [inline pkg/kv/kvserver/client_raft_test.go:5403]: Only thing I'm not sure is whether the truncation actually happened in this flake. Our truncation policy is quite [generous](https://github.com/cockroachdb/cockroach/blob/0d5068e114763c15f4d67bbdfe20a85b654ad2c8/pkg/kv/kvserver/raft_log_queue.go#L554-L558) in this partition case, it needs 64KiB of backlog before truncating. In this test, there is very little written to this range.

But it's the only plausible explanation I see. Maybe there is some rare condition that made the truncation happen.
