### PR TITLE
failureinjection: add disk stall cycle option

### LINKED ISSUE #148345: roachtest: disk-stalled/wal-failover/among-stores/with-progress failed
roachtest.disk-stalled/wal-failover/among-stores/with-progress [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/19936838?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/19936838?buildTab=artifacts#/disk-stalled/wal-failover/among-stores/with-progress) on master @ [c8569680eeb708caf4b90d0b322116770cc72ef4](https://github.com/cockroachdb/cockroach/commits/c8569680eeb708caf4b90d0b322116770cc72ef4):

```
(disk_stall.go:98).Slow: full command output in run_093009.516724982_n1_sudo-binbash-c-echo-.log: COMMAND_PROBLEM: exit status 1
(disk_stall.go:579).func3: context done while sampling: context canceled
(cluster.go:2462).Run: context canceled
(assertions.go:369).Fail: 
	Error Trace:	pkg/cmd/roachtest/tests/disk_stall.go:665
	            				pkg/cmd/roachtest/tests/disk_stall.go:439
	            				pkg/cmd/roachtest/test_runner.go:1387
	            				src/runtime/asm_amd64.s:1700
	Error:      	expected value must have a value other than zero to calculate the relative error
	Test:       	disk-stalled/wal-failover/among-stores/with-progress
	Messages:   	sample 0.000000 is not within tolerance of mean 0.000000
(require.go:977).InEpsilonf: FailNow called
test artifacts and logs in: /artifacts/disk-stalled/wal-failover/among-stores/with-progress/run_1
```

Parameters:
 - <code>arch=amd64</code>
 - <code>cloud=gce</code>
 - <code>coverageBuild=false</code>
 - <code>cpu=16</code>
 - <code>encrypted=false</code>
 - <code>fs=ext4</code>
 - <code>localSSD=false</code>
 - <code>metamorphicBufferedSender=true</code>
 - <code>metamorphicLeases=default</code>
 - <code>runtimeAssertionsBuild=false</code>
 - <code>ssd=0</code>
<details><summary>Help</summary>
<p>

See: [roachtest README](https://github.com/cockroachdb/cockroach/blob/master/pkg/cmd/roachtest/README.md)

See: [How To Investigate \(internal\)](https://cockroachlabs.atlassian.net/l/c/SSSBr8c7)

See: [Grafana](https://go.crdb.dev/roachtest-grafana/teamcity-19936838/disk-stalled-wal-failover-among-stores-with-progress/1749976130375/1749979965043)

</p>
</details>
/cc @cockroachdb/storage
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*disk-stalled/wal-failover/among-stores/with-progress.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/bazci/githubpost/issues)

</sub>

### PR DESCRIPTION
**Pull request by DarrylWong**
Some usages of disk stalls wish to repeatedly stall and unstall a disk in a short period of time. The current implementation requires an ssh connection per stall/unstall call, which can easily lead to flakes. e.g. the unstall call runs into an ssh flake and the node fatals before it can be recovered.

This change adds a disk stall cycle option which will do this in one single ssh connection until Recover is called.

Fixes: https://github.com/cockroachdb/cockroach/issues/148345
Release note: none

### CODE REVIEW

File: pkg/roachprod/failureinjection/failures/disk_stall.go [hunk 1]
```diff
@@ -116,27 +123,20 @@ fi
 }
 func (s *CGroupDiskStaller) Cleanup(ctx context.Context, l *logger.Logger, args FailureArgs) error {
 	diskStallArgs := args.(DiskStallArgs)
-	stallType := []bandwidthType{readBandwidth, writeBandwidth}
 	nodes := diskStallArgs.Nodes
 
-	// Setting cgroup limits is idempotent so attempt to unlimit reads/writes in case
```
Comment (DarrylWong) [inline pkg/roachprod/failureinjection/failures/disk_stall.go:122]: Removed this since the `Failer` wrapper now manages the state of failure modes, i.e. it will attempt to `Recover` before `Cleanup`

File: pkg/roachprod/failureinjection/failures/disk_stall.go [hunk 2]
```diff
@@ -226,25 +281,60 @@ func (s *CGroupDiskStaller) Recover(ctx context.Context, l *logger.Logger, args
...
-	err = s.setThroughput(ctx, l, stallTypes, throughput{limited: false}, nodes, cockroachIOController)
-	return forEachNode(diskStallArgs.Nodes, func(n install.Nodes) error {
+	// unlimit anything.
+	cmd, err := s.setThroughputCmd(ctx, l, stallTypes, throughput{limited: false}, cockroachIOController)
+	if err != nil {
+		return errors.CombineErrors(cycleErr, err)
+	}
+	err = s.Run(ctx, l, diskStallArgs.Nodes, cmd)
+
+	// If we aren't restarting nodes, then return the error we encountered attempting to
```
Comment (DarrylWong) [inline pkg/roachprod/failureinjection/failures/disk_stall.go:272]: Noting the previous bug where the error was always swallowed.

File: pkg/roachprod/failureinjection/failures/disk_stall.go [hunk 3]
```diff
@@ -442,27 +499,48 @@ func (s *DmsetupDiskStaller) Setup(ctx context.Context, l *logger.Logger, args F
...
 
 func (s *DmsetupDiskStaller) Recover(
 	ctx context.Context, l *logger.Logger, args FailureArgs,
 ) error {
 	diskStallArgs := args.(DiskStallArgs)
 	nodes := diskStallArgs.Nodes
+
+	// If we are running an async disk stall cycle script, cancel the script and
+	// block until it returns.
+	if diskStallArgs.Cycle {
```
Comment (DarrylWong) [inline pkg/roachprod/failureinjection/failures/disk_stall.go:518]: ~~Note that it's still possible that the unstall command encounters an ssh flake and our disk stall is induced for too long. IMO this is okay since:~~

1. The goal of the PR is to reduce the number of ssh connections/flakes not necessarily make it flake proof. SSH flakes should be rare so simply reducing the number of connections from 1000+ a test to a dozen should help a lot.
2. The test is probably still sensitive to a Stall hitting an SSH flake and throwing off timings, Unstall failing just happens to be more noisy.
3. With the second commit, any Unstall errors should fail the test. If it does hit an ssh flake, the roachtest framework should mark the test as an infra flake.

~~But lmk if anyone has differing opinions.~~

edit: Nevermind, spoke too soon I hit the case where unstall hit an ssh flake in the TC runs 😓 I'll make it so the script always unstalls before exiting.

File: pkg/roachprod/failureinjection/failures/disk_stall.go [hunk 4]
```diff
@@ -540,3 +620,41 @@ func (s *DmsetupDiskStaller) WaitForFailureToRecover(
...
+	time sleep %[2]f
+	%[3]s
+	echo "$(date '+%%Y-%%m-%%d %%H:%%M:%%S.%%3N'): disk unstalled for %[4]f seconds"
+	time sleep %[4]f
+done
+`, stallCmd, stallSleep, unstallCmd, unstallSleep)
+
+	l.Printf("starting disk stall cycle on nodes %d", args.Nodes)
+
+	return runAsync(ctx, l, func(ctx context.Context) error {
```
Comment (DarrylWong) [inline pkg/roachprod/failureinjection/failures/disk_stall.go:675]: I experimented and opted against using systemd to run this since I didn't want the logs to be hidden in the `journal` which I assume most people don't look at. Piping the output to a logger seemed possible but also would've required goroutine management similar to here.

**Comment by DarrylWong** [comment]
Passed locally a few times but kicked off a TC run here with `count=5` for `disk-stalled/wal-failover/among-stores/with-progress`

https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/20036495?hideProblemsFromDependencies=false&hideTestsFromDependencies=false&expandBuildChangesSection=true

**Review by xinhaoz — APPROVED** [review]
Nice, thanks for working on this!

**Comment by DarrylWong** [comment]
TFTR!

bors r=xinhaoz

**Comment by DarrylWong** [comment]
blathers backport 25.3
