### PR TITLE
roachtest: fix overlapping failure injection bug

### LINKED ISSUE #151522: roachtest: admission-control/elastic-workload/mixed-version failed
roachtest.admission-control/elastic-workload/mixed-version [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/20308582?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/20308582?buildTab=artifacts#/admission-control/elastic-workload/mixed-version) on master @ [143f585657f5a05f376b5c23b34d778f430df4fc](https://github.com/cockroachdb/cockroach/commits/143f585657f5a05f376b5c23b34d778f430df4fc):

```
(mixedversion.go:880).Run: preparing to run step 56: failed to get binary version for node 2 (system): pq: replica unavailable: (n2,s2):2 unable to serve request to r33:/NamespaceTable/{30-Max} [(n1,s1):1, (n2,s2):2, (n3,s3):3, next=4, gen=4]: lost quorum (down: (n1,s1):1,(n3,s3):3); closed timestamp: 1754549144.624030208,0 (2025-08-07 06:45:44); raft status: {"id":"2","term":18,"vote":"1","commit":95,"lead":"0","leadEpoch":"0","raftState":"StateFollower","applied":95,"progress":{},"leadtransferee":"0"}: replica has been leaderless for 1m0s
test artifacts and logs in: /artifacts/admission-control/elastic-workload/mixed-version/run_1
```

Parameters:
 - <code>arch=amd64</code>
 - <code>cloud=gce</code>
 - <code>coverageBuild=false</code>
 - <code>cpu=8</code>
 - <code>encrypted=false</code>
 - <code>fs=ext4</code>
 - <code>localSSD=true</code>
 - <code>mvtDeploymentMode=system-only</code>
 - <code>mvtVersions=v24.3.15 → v25.1.8 → v25.2.2 → master</code>
 - <code>runtimeAssertionsBuild=false</code>
 - <code>ssd=0</code>
<details><summary>Help</summary>
<p>

See: [roachtest README](https://github.com/cockroachdb/cockroach/blob/master/pkg/cmd/roachtest/README.md)

See: [How To Investigate \(internal\)](https://cockroachlabs.atlassian.net/l/c/SSSBr8c7)

See: [Grafana](https://go.crdb.dev/roachtest-grafana/teamcity-20308582/admission-control-elastic-workload-mixed-version/1754545862486/1754550256672)

</p>
</details>
/cc @cockroachdb/kv-triage
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*admission-control/elastic-workload/mixed-version.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/bazci/githubpost/issues)

</sub>

### PR DESCRIPTION
**Pull request by dev-kyle**
This change fixes a bug regarding failure injections overlapping over each other when not intended. Marks the mutator step itself to also set unavailableNodes so sequential failure injections don't insert into them. Also considers `waitForStableClusterVersionStep` as incompatible when injecting a network partition recovery.

Epic: none

Release note: none

Fixes: #151522 , #151384

### CODE REVIEW

File: pkg/cmd/roachtest/roachtestutil/mixedversion/planner.go [hunk 1]
```diff
@@ -148,9 +148,11 @@ type (
 	// performed. If a new step is being added to the plan, `impl`
 	// includes its implementation.
 	mutation struct {
-		reference *singleStep
-		impl      singleStepProtocol
-		op        mutationOp
+		reference                 *singleStep
+		impl                      singleStepProtocol
+		op                        mutationOp
+		hasUnavailableSystemNodes bool
```
Comment (DarrylWong) [inline pkg/cmd/roachtest/roachtestutil/mixedversion/planner.go:162]: Lets explain why we need this, i.e. mutations are wrapped in a step context which contains unavailability, so we can't add it directly here but rather have to plumb it to `applyMutations`.

File: pkg/cmd/roachtest/roachtestutil/mixedversion/mutators.go [hunk 2]
```diff
@@ -555,6 +556,10 @@ func (m networkPartitionMutator) Generate(
 			// Many hook steps require communication between specific nodes, so we
 			// should recover the network partition before running them.
 			_, runHook := s.impl.(runHookStep)
+			// Waiting for stable cluster version requires communication between
+			// all nodes in the cluster, so we should recover the network partition
+			// before running it.
+			_, waitForStable := s.impl.(waitForStableClusterVersionStep)
```
Comment (DarrylWong) [inline pkg/cmd/roachtest/roachtestutil/mixedversion/mutators.go:570]: nit: you could make this it's own commit for clarity, i.e. explain in the commit message the (separate) bug it's fixing.

File: pkg/cmd/roachtest/roachtestutil/mixedversion/mutators.go [hunk 3]
```diff
@@ -488,6 +488,7 @@ func (m panicNodeMutator) Generate(
 			return s == restartStep[0]
 		})
 		failureContextSteps.MarkNodesUnavailable(true, false)
+		addPanicStep[0].hasUnavailableSystemNodes = true
 
 		mutations = append(mutations, addPanicStep...)
 		mutations = append(mutations, addRestartStep...)
```
Comment (DarrylWong) [inline pkg/cmd/roachtest/roachtestutil/mixedversion/mutators.go:495]: Should the restart steps set `UnavailableSystemNodes` to true as well? What if another failure mutator selects it (since `UnavailableSystemNodes=false` and attempts to inject a step before the recover?

**Comment by DarrylWong** [comment]
I'm still seeing the [unit test I wrote](https://github.com/cockroachdb/cockroach/compare/master...DarrylWong:fork:mvt-fi-unit-test?expand=1) fail with on this commit, it generates:

```
   │   ├── panicking system interface on node 1 (36)
   │   ├── setting up outgoing network partition: dropping connections from nodes [2] to [3 4 1] (37)
   │   ├── recovering from outgoing network partition: allowing connections from nodes [2] to [3 4 1] (38)
   │   ├── restarting node 1 after panic (39)
   │   └── restart node 2 with binary version v24.1.1 (40)
   ├── upgrade nodes :1-4 from "v24.1.1" to "<current>"
   │   ├── restart node 3 with binary version <current> (41)
   │   ├── restart node 1 with binary version <current> (42)
   │   ├── run "test hook" (43)
   │   ├── restart node 2 with binary version <current> (44)
   │   └── restart node 4 with binary version <current> (45)
   ├── allow upgrade to happen on system tenant by resetting `preserve_downgrade_option` (46)
   ├── run "test hook" (47)
   └── wait for all nodes (:1-2,4,3) to acknowledge cluster version <current> on system tenant (48)
```

**Comment by dev-kyle** [comment]
That may have been due to your comment about also marking the recovery step as invalid, I just pushed out a commit to patch that (hopefully)

File: pkg/cmd/roachtest/roachtestutil/mixedversion/mutators.go [hunk 4]
```diff
@@ -496,6 +498,15 @@ func (m panicNodeMutator) Generate(
 	return mutations, nil
 }
 
+func GetFailer(planner *testPlanner, name string) (*failures.Failer, error) {
+	if planner._getFailer != nil {
+		return planner._getFailer(name)
+	}
+
+	return planner.cluster.GetFailer(planner.logger, planner.cluster.CRDBNodes(), name)
+
```
Comment (DarrylWong) [inline pkg/cmd/roachtest/roachtestutil/mixedversion/mutators.go]: super nit: stray new line :)

**Review by DarrylWong — COMMENTED** [review]
Revert 0cda1d68b4f3147b11b6d13a89ae93bd352ae8ff ?

**Review by DarrylWong — APPROVED** [review]

**Comment by dev-kyle** [comment]
TFTR!

bors r=DarrylWong

File: pkg/cmd/roachtest/roachtestutil/mixedversion/mixedversion.go [hunk 5]
```diff
@@ -964,6 +966,7 @@ func (t *Test) plan() (plan *TestPlan, retErr error) {
 			bgChans:        t.bgChans,
 			logger:         t.logger,
 			cluster:        t.cluster,
+			_getFailer:     t._getFailer,
```
Comment (herkolategan) [inline pkg/cmd/roachtest/roachtestutil/mixedversion/mixedversion.go:969]: Regarding this. I'm working on a PR that makes mixedversion plans serializable. And one of the issues I'm encountering is that "step implementations" or at least their underlying structs contain runtime state. Luckily there weren't too many of these cases, but `*Failer` was one of them.

My solution was to offload the responsibility to `MVT/Helper`, so a `*Failer` would be lazily instantiated based on arguments for a step, and the state managed by the `runnner`/`helper`. I needed to do the same for function hooks and a few other steps.
See Here as an example: https://github.com/cockroachdb/cockroach/pull/151461/files#diff-603c5afc6a7ede4bfe6ae37e40c7cefc3f08b8e3ad7ec0fc1013dc2cf6a3ab28R358

@DarrylWong do you reckon we could do something similar in this PR, so that `*Failer` state is rather kept on the runner (accessible via the `Helper`), and only the execution / failure mode details (that are serializable) are kept on the step the mutator introduces?

**Comment by herkolategan** [comment]
> TFTR!
> 
> b_rs r=DarrylWong

Made a comment before the merge, but should not be a problem. I can sort out the merge conflict on my PR.

File: pkg/cmd/roachtest/roachtestutil/mixedversion/mixedversion.go (hunk 5 above)
Comment (DarrylWong) [reply pkg/cmd/roachtest/roachtestutil/mixedversion/mixedversion.go:969]: >*Failer state is rather kept on the runner 

Yeah, that would be ideal since we also want want to avoid calling setup and cleanup multiple times if possible. We also want the runner to recover from any faillure injection if the test fails even if the cleanup step was never hit.

We went with the approach of passing the failer directly for simplicity (at least for the first iteration), but I don't think there was a reason other than that.

Comment (herkolategan) [reply pkg/cmd/roachtest/roachtestutil/mixedversion/mixedversion.go:969]: Okay thanks, I'll attempt to add it on my PR as a separate commit.

**Comment by dev-kyle** [comment]
bors retry

**Comment by herkolategan** [comment]
> b_rs retry

Mmm, not sure if my reply messed up b_rs. I replaced the o with _ just in case (if so apologies!).
Unfortunately there is now also a conflict to deal with.

**Comment by dev-kyle** [comment]
bors retry

**Comment by DarrylWong** [comment]
You have a conflict, once you fix that, try again with a b o r s r+

**Comment by DarrylWong** [comment]
Hmm, I don't think you want a merge here, does a `git pull origin master --rebase` work?

**Comment by dev-kyle** [comment]
Yeah, I was trying to use the one provided by the github cli, let me try it the normal way whoops
