### PR TITLE
geogen: disallow EMPTY in multi and geometry collections

### LINKED ISSUE #62141: sql/distsql: TestAggregatorAgainstProcessor failed
[(sql/distsql).TestAggregatorAgainstProcessor failed](https://teamcity.cockroachdb.com/viewLog.html?buildId=2785812&tab=buildLog) on [master@597e4a8c487e3c23d64885563d608a692b59055c](https://github.com/cockroachdb/cockroach/commits/597e4a8c487e3c23d64885563d608a692b59055c):

```
runtime/pprof.Do(0x503d4c0, 0xc000e90030, 0xc000599480, 0x1, 0x1, 0xc000117fb8)
	/usr/local/go/src/runtime/pprof/runtime.go:40 +0xcc
github.com/cockroachdb/pebble.(*tableCacheShard).releaseLoop(0xc00068f200)
	/go/src/github.com/cockroachdb/cockroach/vendor/github.com/cockroachdb/pebble/table_cache.go:175 +0x89
created by github.com/cockroachdb/pebble.(*tableCacheShard).init
	/go/src/github.com/cockroachdb/cockroach/vendor/github.com/cockroachdb/pebble/table_cache.go:167 +0x1a5

goroutine 12 [chan receive]:
github.com/cockroachdb/pebble.(*tableCacheShard).releaseLoop.func1(0x503d4c0, 0xc000a921b0)
	/go/src/github.com/cockroachdb/cockroach/vendor/github.com/cockroachdb/pebble/table_cache.go:176 +0x76
runtime/pprof.Do(0x503d4c0, 0xc000a921b0, 0xc000599480, 0x1, 0x1, 0xc00009b7b8)
	/usr/local/go/src/runtime/pprof/runtime.go:40 +0xcc
github.com/cockroachdb/pebble.(*tableCacheShard).releaseLoop(0xc00068f300)
	/go/src/github.com/cockroachdb/cockroach/vendor/github.com/cockroachdb/pebble/table_cache.go:175 +0x89
created by github.com/cockroachdb/pebble.(*tableCacheShard).init
	/go/src/github.com/cockroachdb/cockroach/vendor/github.com/cockroachdb/pebble/table_cache.go:167 +0x1a5

goroutine 13 [chan receive]:
github.com/cockroachdb/pebble.(*tableCacheShard).releaseLoop.func1(0x503d4c0, 0xc000a92270)
	/go/src/github.com/cockroachdb/cockroach/vendor/github.com/cockroachdb/pebble/table_cache.go:176 +0x76
runtime/pprof.Do(0x503d4c0, 0xc000a92270, 0xc000599480, 0x1, 0x1, 0xc00009bfb8)
	/usr/local/go/src/runtime/pprof/runtime.go:40 +0xcc
github.com/cockroachdb/pebble.(*tableCacheShard).releaseLoop(0xc00068f400)
	/go/src/github.com/cockroachdb/cockroach/vendor/github.com/cockroachdb/pebble/table_cache.go:175 +0x89
created by github.com/cockroachdb/pebble.(*tableCacheShard).init
	/go/src/github.com/cockroachdb/cockroach/vendor/github.com/cockroachdb/pebble/table_cache.go:167 +0x1a5

goroutine 14 [sync.Cond.Wait]:
runtime.goparkunlock(...)
	/usr/local/go/src/runtime/proc.go:312
sync.runtime_notifyListWait(0xc000374ae0, 0x0)
	/usr/local/go/src/runtime/sema.go:513 +0xf8
sync.(*Cond).Wait(0xc000374ad0)
	/usr/local/go/src/sync/cond.go:56 +0x9d
github.com/cockroachdb/pebble/internal/record.(*flusherCond).Wait(...)
	/go/src/github.com/cockroachdb/cockroach/vendor/github.com/cockroachdb/pebble/internal/record/log_writer.go:193
github.com/cockroachdb/pebble/internal/record.(*LogWriter).flushLoop(0xc000374a00, 0x503d4c0, 0xc000c9a030)
	/go/src/github.com/cockroachdb/cockroach/vendor/github.com/cockroachdb/pebble/internal/record/log_writer.go:396 +0x10b
runtime/pprof.Do(0x503d4c0, 0xc000c9a030, 0xc000598d40, 0x1, 0x1, 0xc000112fb8)
	/usr/local/go/src/runtime/pprof/runtime.go:40 +0xcc
github.com/cockroachdb/pebble/internal/record.NewLogWriter.func2(0xc000374a00)
	/go/src/github.com/cockroachdb/cockroach/vendor/github.com/cockroachdb/pebble/internal/record/log_writer.go:314 +0x89
created by github.com/cockroachdb/pebble/internal/record.NewLogWriter
	/go/src/github.com/cockroachdb/cockroach/vendor/github.com/cockroachdb/pebble/internal/record/log_writer.go:313 +0x2ea


ERROR: exit status 2

1 runs completed, 1 failures, over 0s
context canceled

```

<details><summary>More</summary><p>
Parameters:

- TAGS=
- GOFLAGS=-parallel=4

```
make stressrace TESTS=TestAggregatorAgainstProcessor PKG=./pkg/sql/distsql TESTTIMEOUT=5m STRESSFLAGS='-timeout 5m' 2>&1
```

[See this test on roachdash](https://roachdash.crdb.dev/?filter=status%3Aopen+t%3A.%2ATestAggregatorAgainstProcessor.%2A&sort=title&restgroup=false&display=lastcommented+project)
<sub>powered by [pkg/cmd/internal/issues](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)</sub></p></details>

### PR DESCRIPTION
**Pull request by andyyang890**
Allowing EMPTYs inside multi or geometry collections was
causing panics due to a GEOS bug. This patch explicitly
disallows such geometries from being generated.

Fixes #62141.

Release note: None

### CODE REVIEW

File: pkg/geo/geogen/geogen.go [hunk 1]
```diff
@@ -208,7 +208,12 @@ func RandomMultiPoint(
 	// 10% chance to generate an empty multipoint (when num is 0).
 	num := rng.Intn(10)
 	for i := 0; i < num; i++ {
-		if err := ret.Push(RandomPoint(rng, randomBounds, srid, layout)); err != nil {
+		// TODO(ayang): permit EMPTY collection item once GEOS is patched
```
Comment (otan) [inline pkg/geo/geogen/geogen.go:211]: can you replace ayang with an issue number?
unfortunately you're not here forever :3

**Review by otan — APPROVED** [review]

**Comment by andyyang890** [comment]
bors r=otan
