### PR TITLE
opt: fix bugs in plan gist decoding

### LINKED ISSUE #108979: Index out of range error when decoding plan gist
root@localhost:26257/defaultdb> select crdb_internal.decode_plan_gist('AgGwAgQAgQIAAgAEBQITsAICAxgGDA==');
ERROR: internal error: runtime error: index out of range [0] with length 0
SQLSTATE: XX000
DETAIL: stack trace:
github.com/cockroachdb/cockroach/pkg/util/errorutil/catch.go:29: ShouldCatch()
github.com/cockroachdb/cockroach/pkg/sql/opt/exec/explain/plan_gist_factory.go:169: func1()
GOROOT/src/runtime/panic.go:884: gopanic()
GOROOT/src/runtime/panic.go:113: goPanicIndex()
github.com/cockroachdb/cockroach/pkg/sql/opt/exec/explain/emit.go:773: emitNodeAttributes()
github.com/cockroachdb/cockroach/pkg/sql/opt/exec/explain/emit.go:53: func1()
github.com/cockroachdb/cockroach/pkg/sql/opt/exec/explain/emit.go:44: func1()
github.com/cockroachdb/cockroach/pkg/sql/opt/exec/explain/emit.go:57: func1()
github.com/cockroachdb/cockroach/pkg/sql/opt/exec/explain/emit.go:57: func1()
github.com/cockroachdb/cockroach/pkg/sql/opt/exec/explain/emit.go:57: func1()
github.com/cockroachdb/cockroach/pkg/sql/opt/exec/explain/emit.go:44: func1()
github.com/cockroachdb/cockroach/pkg/sql/opt/exec/explain/emit.go:66: Emit()
github.com/cockroachdb/cockroach/pkg/sql/opt/exec/explain/plan_gist_factory.go:185: DecodePlanGistToRows()
github.com/cockroachdb/cockroach/pkg/sql/plan_opt.go:728: DecodeGist()
github.com/cockroachdb/cockroach/pkg/sql/sem/builtins/generator_builtins.go:628: Start()
github.com/cockroachdb/cockroach/pkg/sql/rowexec/project_set.go:209: nextInputRow()
github.com/cockroachdb/cockroach/pkg/sql/rowexec/project_set.go:291: Next()
github.com/cockroachdb/cockroach/pkg/sql/colexec/columnarizer.go:239: Next()
github.com/cockroachdb/cockroach/pkg/sql/colflow/stats.go:118: next()
github.com/cockroachdb/cockroach/pkg/sql/colexecerror/error.go:92: CatchVectorizedRuntimeError()
github.com/cockroachdb/cockroach/pkg/sql/colflow/stats.go:126: Next()
github.com/cockroachdb/cockroach/pkg/sql/colflow/flow_coordinator.go:250: nextAdapter()
github.com/cockroachdb/cockroach/pkg/sql/colexecerror/error.go:92: CatchVectorizedRuntimeError()
github.com/cockroachdb/cockroach/pkg/sql/colflow/flow_coordinator.go:254: next()
github.com/cockroachdb/cockroach/pkg/sql/colflow/flow_coordinator.go:286: Run()
github.com/cockroachdb/cockroach/pkg/sql/colflow/vectorized_flow.go:324: Run()
github.com/cockroachdb/cockroach/pkg/sql/distsql_running.go:902: Run()
github.com/cockroachdb/cockroach/pkg/sql/distsql_running.go:1913: PlanAndRun()
github.com/cockroachdb/cockroach/pkg/sql/distsql_running.go:1645: func3()
github.com/cockroachdb/cockroach/pkg/sql/distsql_running.go:1648: PlanAndRunAll()
github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:2153: execWithDistSQLEngine()
github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:1707: dispatchToExecutionEngine()

HINT: You have encountered an unexpected error.

Please check the public issue tracker to check whether this problem is
already tracked. If you cannot find it there, please report the error
with details by creating a new issue.

If you would rather not post publicly, please contact us directly
using the support form.

We appreciate your feedback.

Jira issue: CRDB-30730

### LINKED ISSUE #109560: sql/tests: TestRandomSyntaxFunctions failed [index out of range in `decode_external_plan_gist`]
sql/tests.TestRandomSyntaxFunctions [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RandomSyntaxTestsBazel/11508337?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RandomSyntaxTestsBazel/11508337?buildTab=artifacts#/) on master @ [0a895777f13e48209c8cd23f1b304d33f7e1cea1](https://github.com/cockroachdb/cockroach/commits/0a895777f13e48209c8cd23f1b304d33f7e1cea1):

Random syntax error:

```
    rsg_test.go:887: Crash detected: server panic: pq: internal error: runtime error: index out of range [-1]
```
Query:

```
        SELECT crdb_internal.decode_external_plan_gist('Ag8f':::STRING) ;
```
<details><summary>Help</summary>
<p>

See also: [How To Investigate a Go Test Failure \(internal\)](https://cockroachlabs.atlassian.net/l/c/HgfXfJgM)
</p>
</details>
<details><summary>Same failure on other branches</summary>
<p>

- #95619 sql/tests: TestRandomSyntaxFunctions failed [C-test-failure O-robot T-sql-foundations branch-release-22.2]
</p>
</details>
/cc @cockroachdb/sql-foundations
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*TestRandomSyntaxFunctions.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)
</sub>

Jira issue: CRDB-30987

### PR DESCRIPTION
**Pull request by mgartner**
#### opt: fix plan gist decoding of inverted filters

Details about inverted filter nodes are not encoded in plan gists. The
plan gist decoder incorrectly assumed there were some details encoded,
and would raise an internal error whenever decoding a plan gist with an
inverted filter. This commit fixes the incorrect assumption to prevent
the internal error.

Fixes #108979

There is no release not because plan gists are an undocumented feature.

Release note: None

#### opt: fix plan gist decoding internal error

This commit fixes some cases where `crdb_internal.decode_plan_gist`
could raise internal index-out-of-bound errors when given incorrectly
formed input.

Fixes #109560

Release note: None

### CODE REVIEW

**Review by cucaroach — APPROVED** [review]

File: pkg/sql/opt/exec/explain/emit.go [hunk 1]
```diff
@@ -779,9 +779,7 @@ func (e *emitter) emitNodeAttributes(n *Node) error {
 		e.emitLockingPolicyWithPrefix("right ", a.RightLocking)
 
 	case invertedFilterOp:
-		a := n.args.(*invertedFilterArgs)
-		ob.Attr("inverted column", a.Input.Columns()[a.InvColumn].Name)
-		ob.Attr("num spans", len(a.InvFilter.SpansToRead))
+		// No details are encoded for inverted filters.
```
Comment (cucaroach) [inline pkg/sql/opt/exec/explain/emit.go:782]: Why not?  Seems like this would change normal explain which I would think we'd want to output inverted filter details.

Comment (mgartner) [reply pkg/sql/opt/exec/explain/emit.go:782]: I don't know the reasoning behind it, but we don't encode any details besides the type of operator for filters and inverted filters. The plan gist factory code looks like:

```go
func (f *PlanGistFactory) ConstructFilter(
	input exec.Node,
	filter tree.TypedExpr,
	reqOrdering exec.OutputOrdering,
) (exec.Node, error) {
	f.encodeOperator(filterOp)
	node, err := f.wrappedFactory.ConstructFilter(
		input,
		filter,
		reqOrdering,
	)
	return node, err
}

func (f *PlanGistFactory) ConstructInvertedFilter(
	input exec.Node,
	invFilter *inverted.SpanExpression,
	preFiltererExpr tree.TypedExpr,
	preFiltererType *types.T,
	invColumn exec.NodeColumnOrdinal,
) (exec.Node, error) {
	f.encodeOperator(invertedFilterOp)
	node, err := f.wrappedFactory.ConstructInvertedFilter(
		input,
		invFilter,
		preFiltererExpr,
		preFiltererType,
		invColumn,
	)
	return node, err
}
```

I assumed it was to prevent sensitive details, or too-specific of information from being encoded in the plan gist, since it's meant to just contain the general shape of the plan.

Comment (mgartner) [reply pkg/sql/opt/exec/explain/emit.go:782]: Nevermind, I see what you mean about this affecting normal explain. I'll fix it.

Comment (mgartner) [reply pkg/sql/opt/exec/explain/emit.go]: Fixed.

**Review by cucaroach — APPROVED** [review]

**Review by cucaroach — APPROVED** [review]

**Comment by mgartner** [comment]
TFTR!

bors r+

**Comment by mgartner** [comment]
blathers backport 23.1
