### PR TITLE
base: make TestValidateAddrs work without a network connection

### LINKED ISSUE #109052: pkg/base: base_test fails if no network access
Looks like `TestValidateAddrs/23/{nonexistent.example.com:26257_____}` fails.

```
    addr_validation_test.go:169: expected error "no such host", got invalid --listen-addr: lookup nonexistent.example.com on 169.254.169.254:53: dial udp 169.254.169.254:53: connect: network is unreachable
```

Epic: CRDB-8308

Jira issue: CRDB-30751

### PR DESCRIPTION
**Pull request by arulajmani**
Looking up an invalid host name may result in a different error depending on whether the test has access to a network connection or not. This patch modifies the test to catch that.

Fixes: #109052

Release note: None

### CODE REVIEW

**Review by nvb — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/110069#-:-NdewrGN1IfKAHJBYCww:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @arulajmani)

**Comment by arulajmani** [comment]
Thanks!

bors r=nvanbenschoten

File: pkg/base/addr_validation_test.go [hunk 1]
```diff
@@ -64,12 +64,17 @@ func TestValidateAddrs(t *testing.T) {
...
+	// "no such host" error. However, it may return a different error if there is
+	// no network access. See
+	// https://github.com/cockroachdb/cockroach/issues/109052.
+	noSuchHostErr := func(host string) string {
+		_, err := net.DefaultResolver.LookupIPAddr(context.Background(), host)
+		if err == nil { // the supplied host is expected to be reliably non-resolvable
+			t.Fatal("expected host resolution failure, got no error")
+		}
+		return err.Error()
 	}
```
Comment (knz) [inline pkg/base/addr_validation_test.go:78]: have you even checked with @rickystewart whether this was a good fix?
I fear with this code that `noSuchHostErr("foo") == noSuchHostErr("bar")` and so the test below is testing something unrelated.

Comment (arulajmani) [reply pkg/base/addr_validation_test.go:78]: > have you even checked with @rickystewart whether this was a good fix?

I haven't; @rickystewart thoughts?

> I fear with this code that `noSuchHostErr("foo") == noSuchHostErr("bar")` and so the test below is testing something unrelated.

`noSuchHostErr("foo") != noSuchHostErr("bar")` -- the host's name is printed in the error, which is actually why I had to pass the host name as a parameter. The error's something like "<hostname> no such host" IIRC.

Comment (rickystewart) [reply pkg/base/addr_validation_test.go:78]: The fix seems to work inasmuch as it fixes the test. It works since we expect to get "some" error, whatever it is, and we just check whether it matches up to the expected error.

Note that this test will run in an environment without network access. To me this means the way the test is written is pretty misleading -- the IP lookup is going to fail in CI, whether the domain we're looking up is example.com or google.com or whatever. This also means that the "test" in CI is going to differ from the "test" as people run it on their local machines -- they'll be performing different `assert`s.

IMO it is more correct to [follow the advice I gave](https://github.com/cockroachdb/cockroach/issues/109052#issuecomment-1686600283) and mock the network lookup in a unit test: it is a *unit test*, so we shouldn't have a dependency on the network, and the test should be written such that we don't do useless network lookups that are guaranteed to fail.

For this, all I care about is whether the test is or is not failing, so I think it's fine as written.
