### PR TITLE
mixedversion: add same series upgrades

### LINKED ISSUE #152694: roachtest/mixeversion: add `sameReleaseSeries` predecessor
Currently, the mixedversion framework doesn't test for upgrades _within_ the same release series, i.e., same `major.minor`, different `major.minor.patch` versions. While a patch release is unlikely to contain new (ungated) functionality, it can still have unwanted side-effects, e.g., performance regression; correctness bugs could also have snuck in undetected during the code review. (See [1] for our backport policy.) Thus, similarly to skip upgrades, we should be testing upgrades between different patch versions.

Recall, the `randomPredecessor` [1] is the default; some tests will use `latestPredecessor`. The former picks the _previous_ release series
and a random (non-withdrawn) patch within it; the latter picks the _latest_ patch in the previous release series. Neither predecessor is aware
of skip upgrades, since that requires a pair of releases. Instead, `chooseUpgradePath` may exclude one (or more) predecessors from the result, thereby forcing a skip upgrade.

To enable upgrades within the same release series, we could add `sameReleaseSeries` predecessor which is really a constrained version of
`randomPredecessor`; i.e., it chooses a random patch within the same release series as opposed to the previous one. Arguably, the naming
of these now three `predecessorFunc`s is a bit awkward. Perhaps, there is a more intuitive and less ambiguous naming.

### Distribution

Below is a distribution of upgrade paths over _one million_ tests plans for `tpcc/mixed-headroom/n5cpu16`. I've removed the patch versions
so that we can focus our attention to the release series. As expected, ~50% has no skips, ~36% has one skip, and ~14 has 2 skips. None of the upgrade paths include an upgrade _within_ the same release series. This is also expected, since we default to the `RandomPredecessor` [1].

#### No skips
| Plans  | Upgrade path → current |
|-------:|-------------------------|
| 189,506 | 25.3 → 25.4-alpha.00000000-dev (<current>) |
| 150,580 | 25.2 → 25.3 → 25.4-alpha.00000000-dev (<current>) |
| 107,671 | 25.1 → 25.2 → 25.3 → 25.4-alpha.00000000-dev (<current>) |
| 52,373  | 24.3 → 25.1 → 25.2 → 25.3 → 25.4-alpha.00000000-dev (<current>) |
| **Total** | **500,130** |

#### 1 skip
| Plans  | Upgrade path → current |
|-------:|-------------------------|
| 190,816 | 25.2 → 25.4-alpha.00000000-dev (<current>) |
| 75,104  | 25.1 → 25.2 → 25.4-alpha.00000000-dev (<current>) |
| 53,639  | 24.3 → 25.1 → 25.2 → 25.4-alpha.00000000-dev (<current>) |
| 26,846  | 24.2 → 24.3 → 25.2 → 25.4-alpha.00000000-dev (<current>) |
| 12,887  | 24.2 → 24.3 → 25.1 → 25.2 → 25.4-alpha.00000000-dev (<current>) |
| **Total** | **359,292** |

#### 2 skips
| Plans  | Upgrade path → current |
|-------:|-------------------------|
| 75,531  | 24.3 → 25.2 → 25.4-alpha.00000000-dev (<current>) |
| 26,170  | 24.1 → 24.3 → 25.2 → 25.4-alpha.00000000-dev (<current>) |
| 13,160  | 24.1 → 24.2 → 24.3 → 25.2 → 25.4-alpha.00000000-dev (<current>) |
| 12,905  | 24.1 → 24.3 → 25.1 → 25.2 → 25.4-alpha.00000000-dev (<current>) |
| 12,813  | 23.2 → 24.1 → 24.3 → 25.2 → 25.4-alpha.00000000-dev (<current>) |
| **Total** | **140,579** |

[1] https://cockroachlabs.atlassian.net/wiki/spaces/ENG/pages/1043235321/Database+Backport+Patch+Policy#New-functionality-can-only-be-added-to-a-patch-release-under-the-following-conditions%3A
[2] https://github.com/cockroachdb/cockroach/blob/1303c66cead8329c634deff8b025449958ae5388/pkg/cmd/roachtest/roachtestutil/mixedversion/mixedversion.go#L1266

### PR DESCRIPTION
**Pull request by cpj2195**
Previously, the mixedversion testing framework only exercised cross-series
upgrades (e.g., v24.2 → v24.3). However, customers also perform same-series
patch upgrades (e.g., v24.3.5 → v24.3.12), and these upgrade paths were not
being tested.

This commit adds support for optionally inserting same-series upgrade steps
into mixedversion test plans. When enabled, the framework may insert an older
patch version from the same series before a version in the upgrade path,
creating upgrade steps like v24.3.5 → v24.3.12.

Example: An upgrade path of [24.1.5, 24.2.3, 24.3.10, current] with
probability=1 might become [24.1.2, 24.1.5, 24.2.1, 24.2.3, 24.3.7, 24.3.10, current]
where 24.1.2 → 24.1.5, 24.2.1 → 24.2.3, and 24.3.7 → 24.3.10 are same-series upgrades.

Fixes: [#152694](https://github.com/cockroachdb/cockroach/issues/152694)
Epic: None
Release Note: None

### CODE REVIEW

File: pkg/cmd/roachtest/roachtestutil/mixedversion/mixedversion.go [hunk 1]
```diff
@@ -653,6 +654,7 @@ func defaultTestOptions() testOptions {
 		waitForReplication:             true,
 		enabledDeploymentModes:         allDeploymentModes,
 		skipVersionProbability:         0.5,
+		sameSeriesUpgradeProbability:   0,
```
Comment (DarrylWong) [inline pkg/cmd/roachtest/roachtestutil/mixedversion/mixedversion.go:662]: Same series upgrade feel to me like it should be a `predecessorFunc` instead of a an additional option.

i.e. `sameSeries`, `latest`, and `random` predecessor are all incompatable, you can only pick one of the three.

File: pkg/cmd/roachtest/roachtestutil/mixedversion/mixedversion.go [hunk 2]
```diff
@@ -675,6 +677,23 @@ func WithSkipVersionProbability(p float64) CustomOption {
 	}
 }
 
+// WithSameSeriesUpgradeProbability allows callers to set the specific
+// probability under which same-series upgrades (e.g., 24.3.5 -> 24.3.12)
+// will be inserted in a test run. Same-series upgrades test patch-level
+// upgrades within the same major.minor release series.
+func WithSameSeriesUpgradeProbability(p float64) CustomOption {
```
Comment (DarrylWong) [inline pkg/cmd/roachtest/roachtestutil/mixedversion/mixedversion.go:690]: IMO we should pick a test or two we own (e.g. tpcc/mixed-headroom) and set this to 50% so we can smoke test it. I think the end goal would be flipping it as the default?

File: pkg/cmd/roachtest/roachtestutil/mixedversion/mixedversion.go [hunk 3]
```diff
@@ -1344,10 +1363,65 @@ func (t *Test) chooseUpgradePath(
...
+	// random numbers that would change the random sequence for other operations.
+	if len(upgradePath) == 0 || t.options.sameSeriesUpgradeProbability == 0 {
+		return upgradePath
+	}
+
+	mbv := t.options.minimumBootstrapVersion
+	result := make([]*clusterupgrade.Version, 0, len(upgradePath))
+
+	for i, v := range upgradePath {
+		// Don't insert same-series upgrades before the current version (last in path).
```
Comment (DarrylWong) [inline pkg/cmd/roachtest/roachtestutil/mixedversion/mixedversion.go]: Why do we skip the current version? This makes sense on master, but on release branches this would be the most important version to test. Remember on release branches, `current != master`.

File: pkg/cmd/roachtest/roachtestutil/mixedversion/mixedversion.go [hunk 4]
```diff
@@ -1344,10 +1363,65 @@ func (t *Test) chooseUpgradePath(
 	slices.Reverse(upgradePath)
 	// Complete the upgrade path by appending the current version.
 	upgradePath = append(upgradePath, clusterupgrade.CurrentVersion())
+	// Optionally insert same-series upgrades (e.g., 24.3.5 -> 24.3.12).
+	upgradePath = t.chooseSameSeriesUpgrades(upgradePath)
```
Comment (DarrylWong) [inline pkg/cmd/roachtest/roachtestutil/mixedversion/mixedversion.go]: We still want to respect `maxUpgrades` of the plan. A same series upgrade should take about the same time as a major series upgrade (migrations is negligible compared to user hooks). In the worst case this could double the runtime which would likely cause most tests to time out.

File: pkg/cmd/roachtest/roachtestutil/mixedversion/mixedversion_test.go [hunk 5]
```diff
@@ -320,6 +320,138 @@ func Test_choosePreviousReleases(t *testing.T) {
 	}
 }
 
+func Test_chooseSameSeriesUpgrades(t *testing.T) {
```
Comment (DarrylWong) [inline pkg/cmd/roachtest/roachtestutil/mixedversion/mixedversion_test.go:338]: Lets also add a datadriven test for same series upgrades.

File: pkg/cmd/roachtest/roachtestutil/mixedversion/mixedversion.go [hunk 6]
```diff
@@ -1344,10 +1363,65 @@ func (t *Test) chooseUpgradePath(
...
+	for i, v := range upgradePath {
+		// Don't insert same-series upgrades before the current version (last in path).
+		// Also skip pre-releases since they don't have enumerable older patches.
+		if i == len(upgradePath)-1 || v.IsPrerelease() {
+			result = append(result, v)
+			continue
+		}
+
+		// Check probability for inserting a same-series upgrade.
+		if t.prng.Float64() < t.options.sameSeriesUpgradeProbability {
```
Comment (DarrylWong) [inline pkg/cmd/roachtest/roachtestutil/mixedversion/mixedversion.go]: Instead of inserting a same series upgrade for every upgrade with p probability, I think it makes more sense to:

1. Enable same series upgrades with p probability
2. If enabled, pick up to n (dependent on `maxUpgrades`, but e.g. 3) upgrades to insert same series upgrades into.

Wdyt?

File: pkg/cmd/roachtest/roachtestutil/mixedversion/mixedversion.go (hunk 1 above)
Comment (cpj2195) [reply pkg/cmd/roachtest/roachtestutil/mixedversion/mixedversion.go:662]: Good point. I considered this, but the current design allows same-series upgrades to be combined with cross-series upgrades in a single path (e.g., 24.1.2 → 24.1.5 → 24.2.3 → 24.3.7 → 24.3.10 → current).

If we make it a predecessorFunc, we'd need to decide:
  1. Pure same-series: Only do same-series upgrades (exhaust all patches in a series before moving to the next)?
  2. Hybrid: Sometimes return same-series, sometimes cross-series?

I'm happy to refactor this as a predecessorFunc if you think the approaches should be mutually exclusive. Could you clarify which behavior you'd prefer for a sameSeriesPredecessor function?

File: pkg/cmd/roachtest/roachtestutil/mixedversion/mixedversion.go (hunk 3 above)
Comment (cpj2195) [reply pkg/cmd/roachtest/roachtestutil/mixedversion/mixedversion.go]: Good catch! On release branches like release-24.3, the current version would be something like v24.3.15-dev, and we'd want to test upgrading from an older 24.3 patch to it.

The issue is OlderPatchReleases() needs released versions to compare against. For pre-release/dev versions, we don't have the patch number in the release data. However, I can modify the logic to:

  1. Check if current is a pre-release (IsPrerelease())
  2. If not a pre-release (i.e., we're on a release branch with a concrete version), allow inserting a same-series upgrade before it

  I'll update the code to handle this case.

File: pkg/cmd/roachtest/roachtestutil/mixedversion/mixedversion.go (hunk 6 above)
Comment (cpj2195) [reply pkg/cmd/roachtest/roachtestutil/mixedversion/mixedversion.go]: I feel the current implementation is more straightforward. For each version, check probability and maybe insert. The two stage approach requires collecting eligible versions, shuffling, selecting, building a map, then reconstructing the path.
Also it produces varied outcomes, sometimes 0, sometimes 1, sometimes 2+ insertions. This exercises more code paths across different test runs. The two stage approach is more binary, either you get the max insertions or none.

what do you say?

File: pkg/cmd/roachtest/tests/tpcc.go [hunk 7]
```diff
@@ -729,6 +729,8 @@ func runTPCCMixedHeadroom(ctx context.Context, t test.Test, c cluster.Cluster, c
 		// See #138014 for more details.
 		mixedversion.MaxNumPlanSteps(70),
 		mixedversion.WithWorkloadNodes(c.WorkloadNode()),
+		// Smoke test same-series upgrades (e.g., 24.3.5 -> 24.3.12) with 50% probability.
+		mixedversion.WithSameSeriesUpgradeProbability(0.5),
```
Comment (srosenberg) [inline pkg/cmd/roachtest/tests/tpcc.go]: This is only for smoke testing, right? The plan is to fold this into a default before the PR is merged?

File: pkg/cmd/roachtest/roachtestutil/mixedversion/mixedversion.go [hunk 8]
```diff
@@ -1347,10 +1376,88 @@ func (t *Test) chooseUpgradePath(
 	slices.Reverse(upgradePath)
 	// Complete the upgrade path by appending the current version.
 	upgradePath = append(upgradePath, clusterupgrade.CurrentVersion())
```
Comment (srosenberg) [inline pkg/cmd/roachtest/roachtestutil/mixedversion/mixedversion.go:1465]: Shouldn't this be the last step? It establishes the invariant that every upgrade path must terminate in the current version.

File: pkg/cmd/roachtest/roachtestutil/mixedversion/mixedversion.go [hunk 9]
```diff
@@ -1347,10 +1376,88 @@ func (t *Test) chooseUpgradePath(
...
+//
+// For pre-release versions (e.g., on release branches like release-24.3 where
+// current is v24.3.15-dev), the function uses AllPatchReleases to find
+// available patches in the same series.
+func (t *Test) chooseSameSeriesUpgrades(
+	upgradePath []*clusterupgrade.Version, maxUpgrades int,
+) []*clusterupgrade.Version {
+	// Early return if same-series upgrades are disabled to avoid consuming
+	// random numbers that would change the random sequence for other operations.
+	if len(upgradePath) == 0 || t.options.sameSeriesUpgradeProbability == 0 {
```
Comment (srosenberg) [inline pkg/cmd/roachtest/roachtestutil/mixedversion/mixedversion.go]: Do we allow `len(upgradePath) == 0`?

File: pkg/cmd/roachtest/roachtestutil/mixedversion/mixedversion.go [hunk 10]
```diff
@@ -1347,10 +1376,88 @@ func (t *Test) chooseUpgradePath(
...
+	// Track how many same-series upgrades we've inserted.
+	// The original path has len(upgradePath)-1 upgrades.
+	// We can insert at most maxUpgrades - (len(upgradePath)-1) same-series upgrades.
+	originalUpgrades := len(upgradePath) - 1
+	maxSameSeriesInsertions := maxUpgrades - originalUpgrades
+	sameSeriesInserted := 0
+
+	for _, v := range upgradePath {
+		// Only attempt insertion if we have budget remaining.
+		if sameSeriesInserted < maxSameSeriesInsertions {
```
Comment (srosenberg) [inline pkg/cmd/roachtest/roachtestutil/mixedversion/mixedversion.go]: Nit: it's easier to read straight-line code for mere mortals; i.e.,

```
if sameSeriesInserted >= maxSameSeriesInsertions {
    break
}
```

File: pkg/cmd/roachtest/roachtestutil/mixedversion/mixedversion.go [hunk 11]
```diff
@@ -1347,10 +1376,88 @@ func (t *Test) chooseUpgradePath(
...
+			// Check probability for inserting a same-series upgrade.
+			if t.prng.Float64() < t.options.sameSeriesUpgradeProbability {
+				var candidatePatches []string
+				var err error
+
+				if v.IsPrerelease() {
+					// For pre-releases (e.g., v24.3.15-dev on release branches),
```
Comment (srosenberg) [inline pkg/cmd/roachtest/roachtestutil/mixedversion/mixedversion.go]: Nit: `dev` isn't an actual suffix; see `phaseName` (in version.go)

File: pkg/cmd/roachtest/roachtestutil/mixedversion/mixedversion.go [hunk 12]
```diff
@@ -1347,10 +1376,88 @@ func (t *Test) chooseUpgradePath(
...
+					// get all patches in the same series since we can't compare patch numbers.
```
Comment (srosenberg) [inline pkg/cmd/roachtest/roachtestutil/mixedversion/mixedversion.go]: A pre-release is denoted by `phase`; we _can_ extracts its `patch` and fall through to the case below, using `OlderPatchReleases`.

File: pkg/cmd/roachtest/roachtestutil/mixedversion/mixedversion_test.go (hunk 5 above)
Comment (srosenberg) [reply pkg/cmd/roachtest/roachtestutil/mixedversion/mixedversion_test.go:338]: We should also update `Test_UpgradePaths` to check that same series upgrades are feasible with the default probability.

File: pkg/cmd/roachtest/roachtestutil/mixedversion/testdata/planner/same_series_upgrades [hunk 13]
```diff
@@ -0,0 +1,74 @@
+# Test that we are able to generate test plans with same-series upgrades
+# (patch-level upgrades within the same major.minor release series).
+#
+# Same-series upgrades test upgrading between patch releases, e.g.,
+# v24.1.2 -> v24.1.5, which is a common customer scenario that we want
+# to ensure works correctly.
+
+# With same_series_upgrade_probability=1.0, the framework will insert
```
Comment (srosenberg) [inline pkg/cmd/roachtest/roachtestutil/mixedversion/testdata/planner/same_series_upgrades]: We should updated README.md to describe this new feature and the corresponding (probability) setting.

File: pkg/cmd/roachtest/roachtestutil/mixedversion/mixedversion.go (hunk 9 above)
Comment (cpj2195) [reply pkg/cmd/roachtest/roachtestutil/mixedversion/mixedversion.go]: Not really, just defensive!

File: pkg/cmd/roachtest/roachtestutil/mixedversion/mixedversion.go (hunk 12 above)
Comment (cpj2195) [reply pkg/cmd/roachtest/roachtestutil/mixedversion/mixedversion.go]: got it, `-dev` seems to be an adhoc version which doesnt require any handling.

File: pkg/cmd/roachtest/tests/tpcc.go (hunk 7 above)
Comment (cpj2195) [reply pkg/cmd/roachtest/tests/tpcc.go]: yes, but I was planning to commit it separately so as to reduce diff count to regenerate test files.

File: pkg/cmd/roachtest/roachtestutil/mixedversion/mixedversion.go (hunk 1 above)
Comment (DarrylWong) [reply pkg/cmd/roachtest/roachtestutil/mixedversion/mixedversion.go:662]: I think definitely option 2 since that seems to reflect how customers run upgrades the best?

I also think it's reasonable for it to just be folded into `randomPredecessor`, given we eventually want to flip it on by default with some probability? Essentially what you have already but with it being an invariant, i.e. add checks to `assertValidTest` to make sure we don't accidentally use `latestPredecessor` with a non 0 `sameSeriesUpgradeProbability`?

File: pkg/cmd/roachtest/roachtestutil/mixedversion/mixedversion.go [hunk 14]
```diff
@@ -1345,12 +1378,99 @@ func (t *Test) chooseUpgradePath(
 	upgradePath := predecessors[0:availableUpgrades]
 	// The upgrade path to be returned is from oldest to newest release.
 	slices.Reverse(upgradePath)
+	// Optionally insert same-series upgrades (e.g., 24.3.5 -> 24.3.12).
+	// We pass maxUpgrades to limit the total number of upgrades.
+	// This is done before appending the current version to ensure the
+	// current version remains the final step in the upgrade path.
+	upgradePath = t.chooseSameSeriesUpgrades(upgradePath, t.options.maxUpgrades)
```
Comment (DarrylWong) [inline pkg/cmd/roachtest/roachtestutil/mixedversion/mixedversion.go]: Something that can be fine tuned in the future, but I'd be curious how much coverage we'd gain by just running the same series migrations without user hooks (in addition to running a few upgrades with). That way we can run a bunch of same series series upgrades without worrying too much about test time increase.

File: pkg/cmd/roachtest/roachtestutil/mixedversion/mixedversion.go [hunk 15]
```diff
@@ -1050,14 +1069,24 @@ func (t *Test) assertPlanValid(plan *TestPlan, numUpgrades int, skipVersions boo
...
+//
+// In all other cases, the plan must have the exact number of specified upgrades (i.e., NumUpgrades(k)).
 func (t *Test) assertNumUpgrades(plan *TestPlan, expectedUpgrades int) error {
 	actualUpgrades := len(plan.allUpgrades())
 	if actualUpgrades != expectedUpgrades {
+		// Skip version upgrades may reduce the count by 1.
 		if t.options.skipVersionProbability > 0 && actualUpgrades == expectedUpgrades-1 {
 			return nil
 		}
+		// Same-series upgrades may increase the count, up to maxUpgrades.
```
Comment (DarrylWong) [inline pkg/cmd/roachtest/roachtestutil/mixedversion/mixedversion.go]: Hmm, I like this approach better since we won't get unbounded test plans anymore, but it does feel like it defeats the purpose of `numUpgrades`. If the plan to is to enable this on by default, then `numUpgrades` will usually be wrong right?

Related to our other [dicussion](https://github.com/cockroachdb/cockroach/pull/161839#discussion_r2742418679):

> The two stage approach requires collecting eligible versions, shuffling, selecting, building a map, then reconstructing the path.

My main thinking there was that we want to predetermine the number of same series upgrades, i.e. `numMajorUpgrades` and `numSameSeriesUpgrades` which makes this validation more precise, and also may simplify the logic you have with making sure not to exceed `maxUpgrades`.

File: pkg/cmd/roachtest/roachtestutil/mixedversion/mixedversion.go (hunk 1 above)
Comment (DarrylWong) [reply pkg/cmd/roachtest/roachtestutil/mixedversion/mixedversion.go:662]: One thing to note is that for `separateProcessDeployment`, we always use `latestPredecessor`. The reason being that serverless usually runs on the latest patch, so if we hit a bug on an older patch, it either:

1. Exists on the latest patch, we could've caught it anyway
2. Does not exist on the latest patch, no action required since nothing is running this version anymore

At the same time, I think this makes it a prime candidate for stressing same series upgrades since it means we run a ton of them. But only for the newest release branch, since a bug hit on an older release branch has the same reasoning as above?

Not something I think needs to be handled in the PR, just thinking out loud.

File: pkg/testutils/release/releases.go [hunk 16]
```diff
@@ -119,6 +119,52 @@ func LatestPatch(seriesStr string) (string, error) {
...
+	}
+
+	return olderPatches, nil
+}
+
+// AllPatchReleases returns all non-withdrawn patch releases in the
+// given series. This is useful for pre-release versions (e.g., on release
+// branches) where we can't compare patch numbers but want to find
+// available patches in the same series.
+func AllPatchReleases(seriesStr string) ([]string, error) {
```
Comment (DarrylWong) [inline pkg/testutils/release/releases.go]: This seems redundant given that it just parses the `seriesStr` and calls `activePatchReleases`? I would either:

1. remove it completely and just do the parsing before calling `activePatchReleases`
2. rename this function to reflect that it's just a convenience helper for `activePatchReleases`

Comment (DarrylWong) [inline pkg/testutils/release/releases.go]: Hmm actually, I'm not seeing this used anywhere. OlderPatchReleases above just calls `activePatchReleases` so I think this can be removed?

File: pkg/cmd/roachtest/roachtestutil/mixedversion/mixedversion.go [hunk 17]
```diff
@@ -1146,7 +1191,11 @@ func (t *Test) assertSkipUpgrade(plan *TestPlan, skipVersions bool) error {
 	if skipVersions && hasEligibleSkips && numSkips == 0 {
 		return errors.Newf("expected at least one skip upgrade, got none")
 	}
-	if numSkips > 0 && t.supportsSkipUpgradeTo(upgrades[len(upgrades)-1].from, upgrades[len(upgrades)-1].to) && numSkipsToFinal == 0 {
+	// Check that skip upgrades to final are present when expected. However,
+	// if the final upgrade is a same-series upgrade (e.g., v25.2.4 → v25.2.10),
+	// we don't expect it to be a skip upgrade even if skip upgrades are enabled.
```
Comment (DarrylWong) [inline pkg/cmd/roachtest/roachtestutil/mixedversion/mixedversion.go]: It's kind of annoying, but we can still validate that the last non same series upgrade should be a skip right?

File: pkg/cmd/roachtest/roachtestutil/mixedversion/mixedversion.go [hunk 18]
```diff
@@ -1329,28 +1378,112 @@ func (t *Test) chooseUpgradePath(
...
+	msv := t.options.minimumSupportedVersion
+
+	const maxRetriesPerInsertion = 100
+	insertions := make(map[int]*clusterupgrade.Version) // idx -> chosen older patch
+
+	for inserted := 0; inserted < numInsertions; {
+		found := false
+		for retries := 0; retries < maxRetriesPerInsertion; retries++ {
+			idx := t.prng.Intn(len(upgradePath))
+			if _, already := insertions[idx]; already {
```
Comment (DarrylWong) [inline pkg/cmd/roachtest/roachtestutil/mixedversion/mixedversion.go]: What's wrong running multiple same series upgrades for the same major upgrade. You'd have to make sure the ordering is correct between the patches, but I assume multiple minor upgrades is more realistic?

Comment (DarrylWong) [reply pkg/cmd/roachtest/roachtestutil/mixedversion/mixedversion.go]: If `numUpgrades` returns only one major upgrade but 3 same series upgrades this would block indefinitely right? Since we only have one open slot to insert.

File: pkg/cmd/roachtest/roachtestutil/mixedversion/mixedversion.go [hunk 19]
```diff
@@ -1329,28 +1378,112 @@ func (t *Test) chooseUpgradePath(
...
+			}
+
+			insertions[idx] = validPatches[t.prng.Intn(len(validPatches))]
+			inserted++
+			found = true
+			break
+		}
+
+		if !found {
+			// Exhausted retries for this insertion; stop trying.
```
Comment (DarrylWong) [inline pkg/cmd/roachtest/roachtestutil/mixedversion/mixedversion.go]: It's probably better to put the retry limit on the outer loop for the above reason. Imagine we get incredibly unlucky and every major upgrade is the `.0` version.

**Review by DarrylWong — COMMENTED** [review]
A few comments around making sure we don't block indefinitely but overall I think this is looking good!

File: pkg/cmd/roachtest/tests/tpcc.go (hunk 7 above)
Comment (DarrylWong) [inline pkg/cmd/roachtest/tests/tpcc.go]: Do you have a team city run where you stress this a couple times? If not can you kick one off (let me know if you need help)?

File: pkg/cmd/roachtest/roachtestutil/mixedversion/mixedversion.go [hunk 20]
```diff
@@ -1146,8 +1191,26 @@ func (t *Test) assertSkipUpgrade(plan *TestPlan, skipVersions bool) error {
 	if skipVersions && hasEligibleSkips && numSkips == 0 {
 		return errors.Newf("expected at least one skip upgrade, got none")
 	}
-	if numSkips > 0 && t.supportsSkipUpgradeTo(upgrades[len(upgrades)-1].from, upgrades[len(upgrades)-1].to) && numSkipsToFinal == 0 {
-		return errors.Newf("expected at least one skip upgrade to the final version, got none")
+	// Check that the last cross-series upgrade is a skip when expected.
```
Comment (DarrylWong) [inline pkg/cmd/roachtest/roachtestutil/mixedversion/mixedversion.go:1243]: Just a passing thought, but I wonder if storing upgrades as a 2d slice (that gets flattened into `upgradePaths` afterwards) would make all these assertions easier:

```
┌─────────┬─────────┬─────────┐                                                                                                                                                                                        
│ v24.1.2 │ v24.1.5 │ v24.1.8 │                                                                                                                                                                                      
├─────────┼─────────┼─────────┤                                                                                                                                                                                        
│ v24.2.1 │ v24.2.3 │         │                                                                                                                                                                                        
├─────────┼─────────┼─────────┤                                                                                                                                                                                        
│ v24.3.10│<current>│         │                                                                                                                                                                                        
└─────────┴─────────┴─────────┘
```

This would let us easily check if the last upgrade is a skip, and let us be more precise in `assertNumUpgrades`. e.g. `len(upgrades) == expectedMajorUpgrades` and `len(upgrades[0]) + len(upgrades[1]) + len(upgrades[2])... == expectedSameSeriesUpgrades`

We could do this without the slice, but it seems like a lot of boilerplate like seen below. I didn't actually test this out though, so maybe there's a catch.

File: pkg/cmd/roachtest/roachtestutil/mixedversion/mixedversion.go [hunk 21]
```diff
@@ -1047,20 +1071,41 @@ func (t *Test) assertPlanValid(plan *TestPlan, numUpgrades int, skipVersions boo
...
+// matches the specification in the test. It uses the predetermined
+// counts of major (cross-series) and same-series upgrades for precise
+// validation:
+//   - The actual count must be at most expectedMajor + expectedSameSeries.
+//   - Skip version upgrades may reduce the major count by 1.
+//   - Same-series insertions may fail if no eligible older patches exist
+//     (rejection sampling exhaustion), reducing the same-series count.
+//   - The actual count must be at least max(1, expectedMajor - 1) to
+//     account for skip version effects.
+func (t *Test) assertNumUpgrades(
```
Comment (DarrylWong) [inline pkg/cmd/roachtest/roachtestutil/mixedversion/mixedversion.go:1093]: Related to my comment about the 2d slice, but it feels like we could be a lot more precise with this check here:

1. Assert on `expectedMajorUpgrades` and `expectedSameSeriesUpgrades` individually
2. Assert that if `actualSameSeriesUpgrades < expectedSameSeriesUpgrades`, it must be that all of our final versions in each majorVersion slice are the `.0` version or the `dev` version.

**Review by DarrylWong — COMMENTED** [review]
A comment around our assertions but I think the core functionality lgtm.

File: pkg/cmd/roachtest/tests/tpcc.go (hunk 7 above)
Comment (cpj2195) [reply pkg/cmd/roachtest/tests/tpcc.go]: yes, it [passed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/21119716?hideTestsFromDependencies=false&hideProblemsFromDependencies=false&expandBuildChangesSection=true&expandBuildTestsSection=true)..

Comment (DarrylWong) [reply pkg/cmd/roachtest/tests/tpcc.go]: In the future I would've just run the mixed version tests say 3x times instead of all the tests.

Comment (DarrylWong) [reply pkg/cmd/roachtest/tests/tpcc.go]: Actually it looked like the tpcc mixed version test was skipped, I kicked off another run https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/21121659?hideProblemsFromDependencies=false&hideTestsFromDependencies=false

File: pkg/cmd/roachtest/roachtestutil/mixedversion/mixedversion_test.go [hunk 22]
```diff
@@ -320,6 +333,144 @@ func Test_choosePreviousReleases(t *testing.T) {
...
+	defer withTestBuildVersion("v24.3.0")()
+
+	// Test data with multiple patches per series for testing same-series upgrades.
+	testReleaseDataWithPatches := map[string]release.Series{
```
Comment (DarrylWong) [inline pkg/cmd/roachtest/roachtestutil/mixedversion/mixedversion_test.go]: Why do we need this hardcoded test data over using the actual release data?

File: pkg/cmd/roachtest/roachtestutil/mixedversion/mixedversion_test.go [hunk 23]
```diff
@@ -240,6 +240,18 @@ func Test_assertValidTest(t *testing.T) {
 		`mixedversion.NewTest: invalid test options: minimum bootstrap version (v24.2.0) should be from an older release series than current version (v23.1.2)`,
 		fatalErr.Error(),
 	)
+
+	// Validating that AlwaysUseLatestPredecessors and same-series upgrades
+	// cannot be used together.
+	mvt = newTest(AlwaysUseLatestPredecessors, WithSameSeriesUpgradeProbability(0.5))
```
Comment (DarrylWong) [inline pkg/cmd/roachtest/roachtestutil/mixedversion/mixedversion_test.go:247]: `newTest` uses a hardcoded seed, I think this test should work randomized right?

Comment (cpj2195) [reply pkg/cmd/roachtest/roachtestutil/mixedversion/mixedversion_test.go:247]: The seed is irrelevant to this particular test case because no random numbers are consumed. It's hardcoded in newTest solely because the Test struct requires a PRNG. Making it randomized here would add no value, the assertion is purely about option validation, not plan generation.

Comment (DarrylWong) [reply pkg/cmd/roachtest/roachtestutil/mixedversion/mixedversion_test.go:247]: Oh oops sorry I meant to comment this under the `Test_chooseSameSeriesUpgrades` which does call `chooseUpgradePath`

File: pkg/cmd/roachtest/roachtestutil/mixedversion/mixedversion_test.go (hunk 22 above)
Comment (cpj2195) [reply pkg/cmd/roachtest/roachtestutil/mixedversion/mixedversion_test.go]: just using pre-exisitng pattern seen amongst other tests, no other reason TBH!

Comment (DarrylWong) [reply pkg/cmd/roachtest/roachtestutil/mixedversion/mixedversion_test.go]: Lets remove it then, I don't see it being used extensively in other tests and it seemed to pass for me when I got rid of it.

**Review by DarrylWong — COMMENTED** [review]
https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/21131025?hideProblemsFromDependencies=false&hideTestsFromDependencies=false

Kicked off another smoke test since the last one got all preempted. I think once this looks good and you fix the test failure this should be good to go

File: pkg/cmd/roachtest/roachtestutil/mixedversion/mixedversion.go [hunk 24]
```diff
@@ -1394,13 +1592,21 @@ func (t *Test) chooseSkips(
...
+// same-series (patch-level) upgrades that will be performed in this
+// test run. majorUpgrades is picked from [minUpgrades, maxUpgrades].
+// sameSeriesUpgrades is picked from [0, maxUpgrades - majorUpgrades]
+// when same-series upgrades are enabled (sameSeriesUpgradeProbability > 0),
+// and 0 otherwise. The total number of upgrades is bounded by maxUpgrades.
+func (t *Test) numUpgrades() (majorUpgrades, sameSeriesUpgrades int) {
+	majorUpgrades = t.prng.Intn(
 		t.options.maxUpgrades-t.options.minUpgrades+1,
 	) + t.options.minUpgrades
+	if t.options.sameSeriesUpgradeProbability > 0 {
```
Comment (DarrylWong) [inline pkg/cmd/roachtest/roachtestutil/mixedversion/mixedversion.go]: This isn't quite correct, we should pull the rng check of enabling same series upgrade outside of this function and pass a bool in as an argument.

File: pkg/cmd/roachtest/roachtestutil/mixedversion/README.md [hunk 25]
```diff
@@ -397,6 +397,16 @@ using workload during your test is to execute a workload command on a binary tha
 this option tells the framework to handle staging all the binaries you need for your test on the workload node(s)
 during test setup.
 
+``` go
+mixedversion.WithSameSeriesUpgradeProbability(0.5)
+```
+
+This option controls the probability of inserting same-series upgrades (patch-level upgrades within the same major.minor release series) into the upgrade path. For example, if the upgrade path is `[24.1.5, 24.2.3, 24.3.10, current]`, the framework might insert an older patch before some versions, resulting in `[24.1.2, 24.1.5, 24.2.3, 24.3.7, 24.3.10, current]` where `24.1.2 -> 24.1.5` and `24.3.7 -> 24.3.10` are same-series upgrades.
+
+Same-series upgrades test that patch-level upgrades work correctly, which is important since most customer upgrades are patch upgrades within the same release series. The probability value (0.0 to 1.0) determines how likely it is that a same-series upgrade will be inserted before each eligible version in the upgrade path. A value of 0 disables same-series upgrades entirely.
```
Comment (DarrylWong) [inline pkg/cmd/roachtest/roachtestutil/mixedversion/README.md]: nit: this is not updated with how the probability now works

**Review by DarrylWong — APPROVED** [review]
Ah i see, unfortunately the env vars are case sensitive so it needs to be `env.TESTS`. I was able to get it to run locally so I think it should be fine. LGTM
