### PR TITLE
workload/schemachanger: primary index detection is incorrect

### LINKED ISSUE #77885: roachtest: schemachange/mixed-versions failed
roachtest.schemachange/mixed-versions [failed](https://teamcity.cockroachdb.com/viewLog.html?buildId=4583063&tab=buildLog) with [artifacts](https://teamcity.cockroachdb.com/viewLog.html?buildId=4583063&tab=artifacts#/schemachange/mixed-versions) on release-22.1 @ [a1c1879e01ceee79a81693c67a1dba184b5fc1b1](https://github.com/cockroachdb/cockroach/commits/a1c1879e01ceee79a81693c67a1dba184b5fc1b1):

```
		  |  "ops": [
		  |   "BEGIN",
		  |   "CREATE SCHEMA IF NOT EXISTS schema35 AUTHORIZATION root",
		  |   "ALTER DATABASE schemachange SURVIVE REGION FAILURE"
		  |  ],
		  |  "expectedExecErrors": "22023,42602",
		  |  "expectedCommitErrors": "",
		  |  "message": "ROLLBACK; Successfully got expected execution error. Dumping state before death:\nExpected errors: 22023,42602===========================Executed queries for generating errors: QUERY [SELECT region FROM [SHOW REGIONS FROM DATABASE]] : \nQUERY [SHOW DATABASE] :schemachange\n===========================Previous statements [CREATE SCHEMA IF NOT EXISTS schema35 AUTHORIZATION root ALTER DATABASE schemachange SURVIVE REGION FAILURE]: ERROR: database must have associated regions before a survival goal can be set (SQLSTATE 42602)"
		  | }
		  | {
		  |  "workerId": 0,
		  |  "clientTimestamp": "05:25:21.166557",
		  |  "ops": [
		  |   "BEGIN",
		  |   "CREATE TYPE schema48.enum49 AS ENUM ('fsaaf', 'das', 'afa')"
		  |  ],
		  |  "expectedExecErrors": "3F000",
		  |  "expectedCommitErrors": "",
		  |  "message": "ROLLBACK; Successfully got expected execution error. Dumping state before death:\nExpected errors: 3F000===========================Executed queries for generating errors: QUERY [\"SELECT EXISTS (\\n\\tSELECT schema_name\\n\\t\\tFROM information_schema.schemata\\n   WHERE schema_name = $1\\n\\t)\" [\"schema48\"]] :false\n===========================Previous statements [CREATE TYPE schema48.enum49 AS ENUM ('fsaaf', 'das', 'afa')]: ERROR: cannot create \"schema48.enum49\" because the target database or schema does not exist (SQLSTATE 3F000)"
		  | }
		  | {
		  |  "workerId": 0,
		  |  "clientTimestamp": "05:25:21.30131",
		  |  "ops": [
		  |   "BEGIN",
		  |   "SELECT 'validating all objects', crdb_internal.validate_multi_region_zone_configs()",
		  |   "COMMIT"
		  |  ],
		  |  "expectedExecErrors": "",
		  |  "expectedCommitErrors": "",
		  |  "message": ""
		  | }
		  | {
		  |  "workerId": 0,
		  |  "clientTimestamp": "05:25:21.144218",
		  |  "ops": [
		  |   "BEGIN",
		  |   "ALTER DATABASE schemachange ADD REGION \"us-east1\""
		  |  ],
		  |  "expectedExecErrors": "42P12",
		  |  "expectedCommitErrors": "",
		  |  "message": "ROLLBACK; Successfully got expected execution error. Dumping state before death:\nExpected errors: 42P12===========================Executed queries for generating errors: QUERY [SELECT region FROM [SHOW REGIONS FROM CLUSTER]] : us-east1,\nQUERY [SELECT region FROM [SHOW REGIONS FROM DATABASE]] : \nQUERY [SHOW DATABASE] :schemachange\n===========================Previous statements [ALTER DATABASE schemachange ADD REGION \"us-east1\"]: ERROR: cannot add region \"us-east1\" to database schemachange (SQLSTATE 42P12)"
		  | }
		Wraps: (4) SSH_PROBLEM
		Wraps: (5) Node 1. Command with error:
		  | ``````
		  | ./workload run schemachange --verbose=1 --tolerate-errors=true --max-ops 100 --concurrency 5 {pgurl:1-4}
		  | ``````
		Wraps: (6) exit status 255
		Error types: (1) *withstack.withStack (2) *errutil.withPrefix (3) *cluster.WithCommandDetails (4) errors.SSH (5) *hintdetail.withDetail (6) *exec.ExitError
```
<details><summary>Help</summary>
<p>

See: [roachtest README](https://github.com/cockroachdb/cockroach/blob/master/pkg/cmd/roachtest/README.md)

See: [How To Investigate \(internal\)](https://cockroachlabs.atlassian.net/l/c/SSSBr8c7)

</p>
</details>
<details><summary>Same failure on other branches</summary>
<p>

- #64687 roachtest: schemachange/mixed-versions failed [C-test-failure O-roachtest O-robot T-sql-schema branch-master]
- #62158 roachtest: schemachange/mixed-versions failed [C-test-failure O-roachtest O-robot T-sql-schema branch-release-21.1]
</p>
</details>
/cc @cockroachdb/sql-schema
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*schemachange/mixed-versions.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)
</sub>

Jira issue: CRDB-13810

### PR DESCRIPTION
**Pull request by fqazi**
Fixes: #77885

Previously, the schemachanger workload incorrectly detected primary
indexes using their names checking for either the words
'pkey' or 'primary'. This approach was not correct and heuristic
in nature. To address this, this patch uses crdb_internal.table_indexes
to detect primary indexes.

Release note: None

### CODE REVIEW

File: pkg/workload/schemachange/error_screening.go [hunk 1]
```diff
@@ -177,16 +177,25 @@ func (og *operationGenerator) colIsPrimaryKey(
...
+						SELECT index_name
+						  FROM crdb_internal.table_indexes
+						 WHERE index_type = 'primary'
+						       AND descriptor_id = $3::REGCLASS
+					)
+		       )
+		       AND table_schema = $1
+		       AND table_name = $2
+		       AND storing = 'NO'
+       );
```
Comment (postamar) [inline pkg/workload/schemachange/error_screening.go:197]: nit: the indentation seems off here

**Review by postamar — APPROVED** [review]
Nice! Yes this is much better.

**Review by fqazi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/78184)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @postamar)

___
*[pkg/workload/schemachange/error_screening.go, line 197 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/78184#-MyhHSyr_u7R719l4mX2-r1-197:-MyhxbudCAaoWo_gm4rd:bb6un1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/79e131c92cadf5c95c9b603cbf37f0f5c5c705ba/pkg/workload/schemachange/error_screening.go#L197)):*
<details><summary><i>Previously, postamar (Marius Posta) wrote…</i></summary><blockquote>

nit: the indentation seems off here
</blockquote></details>

Done

**Comment by fqazi** [comment]
@postamar TFTR!

**Comment by fqazi** [comment]
blathers backport 22.1
