### PR TITLE
backup: rewrite region enum ID in schema change state on table restore

### LINKED ISSUE #168804: pkg/ccl/schemachangerccl/sctestbackupmrccl/sctestbackupmrccl_test: TestBackupSuccess_multiregion_alter_table_locality_rbt_secondary_region_to_primary_region failed
pkg/ccl/schemachangerccl/sctestbackupmrccl/sctestbackupmrccl_test.TestBackupSuccess_multiregion_alter_table_locality_rbt_secondary_region_to_primary_region [failed](https://mesolite.cluster.engflow.com/invocations/default/9537c188-2410-4017-be29-fe3925a27e4b?testReportRun=1&testReportShard=45&testReportAttempt=1#targets-Ly9wa2cvY2NsL3NjaGVtYWNoYW5nZXJjY2wvc2N0ZXN0YmFja3VwbXJjY2w6c2N0ZXN0YmFja3VwbXJjY2xfdGVzdA==) on master @ [c6453d0c4339189822ad5f45274a24aebd5daee6](https://github.com/cockroachdb/cockroach/commits/c6453d0c4339189822ad5f45274a24aebd5daee6):

```
=== RUN   TestBackupSuccess_multiregion_alter_table_locality_rbt_secondary_region_to_primary_region
    test_log_scope.go:172: test logs captured to: outputs.zip/logTestBackupSuccess_multiregion_alter_table_locality_rbt_secondary_region_to_primary_region3171843704
    test_log_scope.go:82: use -show-logs to present logs inline
    framework.go:574: 
        /mnt/engflow/worker/work/0/exec/bazel-out/k8-fastbuild/bin/pkg/ccl/schemachangerccl/sctestbackupmrccl/sctestbackupmrccl_test_/sctestbackupmrccl_test.runfiles/com_github_cockroachdb_cockroach/pkg/ccl/schemachangerccl/testdata/end_to_end/alter_table_locality_rbt_secondary_region_to_primary_region/alter_table_locality_rbt_secondary_region_to_primary_region.definition:1:
          setup
          CREATE DATABASE multiregion_db PRIMARY REGION "us-east1" REGIONS "us-east2", "us-east3";
          CREATE TABLE multiregion_db.public.t (  
            pk INT PRIMARY KEY,
            i INT NOT NULL,
            j STRING,
            INDEX(i)
          ) LOCALITY REGIONAL BY TABLE IN "us-east2";
          ----
    test_server_shim.go:95: cluster virtualization disabled due to issue: #156308 (expected label: C-test-failure)
    test_server_shim.go:95: cluster virtualization disabled due to issue: #156308 (expected label: C-test-failure)
    datadriven.go:357: /mnt/engflow/worker/work/0/exec/bazel-out/k8-fastbuild/bin/pkg/ccl/schemachangerccl/sctestbackupmrccl/sctestbackupmrccl_test_/sctestbackupmrccl_test.runfiles/com_github_cockroachdb_cockroach/pkg/ccl/schemachangerccl/testdata/end_to_end/alter_table_locality_rbt_secondary_region_to_primary_region/alter_table_locality_rbt_secondary_region_to_primary_region.definition:11: still running after 10.000102075s
    panic.go:694: -- test log scope end --
test logs left over in: outputs.zip/logTestBackupSuccess_multiregion_alter_table_locality_rbt_secondary_region_to_primary_region3171843704
--- FAIL: TestBackupSuccess_multiregion_alter_table_locality_rbt_secondary_region_to_primary_region (16.49s)
=== RUN   TestBackupSuccess_multiregion_alter_table_locality_rbt_secondary_region_to_primary_region/post_commit_stage_1_of_1
--- FAIL: TestBackupSuccess_multiregion_alter_table_locality_rbt_secondary_region_to_primary_region/post_commit_stage_1_of_1 (4.21s)
=== RUN   TestBackupSuccess_multiregion_alter_table_locality_rbt_secondary_region_to_primary_region/post_commit_stage_1_of_1/restore_all_tables_in_database
    backup.go:948: error executing query="RESTORE TABLE multiregion_db.public.t FROM LATEST IN 'userfile://backups.public.userfiles_$user/data_PostCommitPhase_1' WITH skip_missing_sequences, skip_missing_udfs" args=[]: pq: table descriptor rewrite failed: rewriting declarative schema changer state: rewriting descriptor ids: missing rewrite for id 108 in TableLocalitySecondaryRegion:{DescID: 127, ReferencedDescID: 108, Value: us-east2}
--- FAIL: TestBackupSuccess_multiregion_alter_table_locality_rbt_secondary_region_to_primary_region/post_commit_stage_1_of_1/restore_all_tables_in_database (0.32s)
```

Parameters:
 - <code>attempt=1</code>
 - <code>run=1</code>
 - <code>shard=45</code>
<details><summary>Help</summary>
<p>

See also: [How To Investigate a Go Test Failure \(internal\)](https://cockroachlabs.atlassian.net/l/c/HgfXfJgM)
</p>
</details>
/cc @cockroachdb/sql-foundations
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*TestBackupSuccess_multiregion_alter_table_locality_rbt_secondary_region_to_primary_region.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/bazci/githubpost/issues)

</sub>

Jira issue: CRDB-63128

### LINKED ISSUE #168884: pkg/ccl/schemachangerccl/sctestbackupmrccl/sctestbackupmrccl_test: TestBackupSuccess_multiregion_alter_table_locality_rbt_secondary_region_to_global failed
pkg/ccl/schemachangerccl/sctestbackupmrccl/sctestbackupmrccl_test.TestBackupSuccess_multiregion_alter_table_locality_rbt_secondary_region_to_global [failed](https://mesolite.cluster.engflow.com/invocations/default/351a2724-5034-4905-b7e5-058cc31401c4?testReportRun=1&testReportShard=44&testReportAttempt=1#targets-Ly9wa2cvY2NsL3NjaGVtYWNoYW5nZXJjY2wvc2N0ZXN0YmFja3VwbXJjY2w6c2N0ZXN0YmFja3VwbXJjY2xfdGVzdA==) on master @ [2dcfd5d93848d59442394f82f268301fc7ab3b00](https://github.com/cockroachdb/cockroach/commits/2dcfd5d93848d59442394f82f268301fc7ab3b00):

```
=== RUN   TestBackupSuccess_multiregion_alter_table_locality_rbt_secondary_region_to_global
    test_log_scope.go:172: test logs captured to: outputs.zip/logTestBackupSuccess_multiregion_alter_table_locality_rbt_secondary_region_to_global623261278
    test_log_scope.go:82: use -show-logs to present logs inline
    framework.go:574: 
        /mnt/engflow/worker/work/0/exec/bazel-out/k8-fastbuild/bin/pkg/ccl/schemachangerccl/sctestbackupmrccl/sctestbackupmrccl_test_/sctestbackupmrccl_test.runfiles/com_github_cockroachdb_cockroach/pkg/ccl/schemachangerccl/testdata/end_to_end/alter_table_locality_rbt_secondary_region_to_global/alter_table_locality_rbt_secondary_region_to_global.definition:1:
          setup
          CREATE DATABASE multiregion_db PRIMARY REGION "us-east1" REGIONS "us-east2", "us-east3";
          CREATE TABLE multiregion_db.public.t (  
            pk INT PRIMARY KEY,
            i INT NOT NULL,
            j STRING,
            INDEX(i)
          ) LOCALITY REGIONAL BY TABLE IN "us-east2";
          ----
    test_server_shim.go:95: cluster virtualization disabled due to issue: #156308 (expected label: C-test-failure)
    test_server_shim.go:95: cluster virtualization disabled due to issue: #156308 (expected label: C-test-failure)
    datadriven.go:357: /mnt/engflow/worker/work/0/exec/bazel-out/k8-fastbuild/bin/pkg/ccl/schemachangerccl/sctestbackupmrccl/sctestbackupmrccl_test_/sctestbackupmrccl_test.runfiles/com_github_cockroachdb_cockroach/pkg/ccl/schemachangerccl/testdata/end_to_end/alter_table_locality_rbt_secondary_region_to_global/alter_table_locality_rbt_secondary_region_to_global.definition:11: still running after 10.000050101s
    panic.go:694: -- test log scope end --
test logs left over in: outputs.zip/logTestBackupSuccess_multiregion_alter_table_locality_rbt_secondary_region_to_global623261278
--- FAIL: TestBackupSuccess_multiregion_alter_table_locality_rbt_secondary_region_to_global (15.00s)
=== RUN   TestBackupSuccess_multiregion_alter_table_locality_rbt_secondary_region_to_global/post_commit_stage_1_of_1
--- FAIL: TestBackupSuccess_multiregion_alter_table_locality_rbt_secondary_region_to_global/post_commit_stage_1_of_1 (3.67s)
=== RUN   TestBackupSuccess_multiregion_alter_table_locality_rbt_secondary_region_to_global/post_commit_stage_1_of_1/restore_all_tables_in_database
    backup.go:948: error executing query="RESTORE TABLE multiregion_db.public.t FROM LATEST IN 'userfile://backups.public.userfiles_$user/data_PostCommitPhase_1' WITH skip_missing_sequences, skip_missing_udfs" args=[]: pq: table descriptor rewrite failed: rewriting declarative schema changer state: rewriting descriptor ids: missing rewrite for id 108 in TableLocalitySecondaryRegion:{DescID: 127, ReferencedDescID: 108, Value: us-east2}
--- FAIL: TestBackupSuccess_multiregion_alter_table_locality_rbt_secondary_region_to_global/post_commit_stage_1_of_1/restore_all_tables_in_database (0.28s)
```

Parameters:
 - <code>attempt=1</code>
 - <code>run=1</code>
 - <code>shard=44</code>
<details><summary>Help</summary>
<p>

See also: [How To Investigate a Go Test Failure \(internal\)](https://cockroachlabs.atlassian.net/l/c/HgfXfJgM)
</p>
</details>
/cc @cockroachdb/sql-foundations
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*TestBackupSuccess_multiregion_alter_table_locality_rbt_secondary_region_to_global.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/bazci/githubpost/issues)

</sub>

Jira issue: CRDB-63165

### LINKED ISSUE #169008: pkg/ccl/schemachangerccl/sctestbackupmrccl/sctestbackupmrccl_test: TestBackupSuccess_multiregion_alter_table_locality_rbt_secondary_region_to_primary_region failed
pkg/ccl/schemachangerccl/sctestbackupmrccl/sctestbackupmrccl_test.TestBackupSuccess_multiregion_alter_table_locality_rbt_secondary_region_to_primary_region [failed](https://mesolite.cluster.engflow.com/invocations/default/333bf4fd-da72-4185-a376-4e25cec59b46?testReportRun=1&testReportShard=45&testReportAttempt=1#targets-Ly9wa2cvY2NsL3NjaGVtYWNoYW5nZXJjY2wvc2N0ZXN0YmFja3VwbXJjY2w6c2N0ZXN0YmFja3VwbXJjY2xfdGVzdA==) on master @ [28a853eb4b32b35fea59230757a64bcc8ed1f40b](https://github.com/cockroachdb/cockroach/commits/28a853eb4b32b35fea59230757a64bcc8ed1f40b):

```
=== RUN   TestBackupSuccess_multiregion_alter_table_locality_rbt_secondary_region_to_primary_region
    test_log_scope.go:172: test logs captured to: outputs.zip/logTestBackupSuccess_multiregion_alter_table_locality_rbt_secondary_region_to_primary_region2730549172
    test_log_scope.go:82: use -show-logs to present logs inline
    framework.go:572: 
        /mnt/engflow/worker/work/0/exec/bazel-out/k8-fastbuild/bin/pkg/ccl/schemachangerccl/sctestbackupmrccl/sctestbackupmrccl_test_/sctestbackupmrccl_test.runfiles/com_github_cockroachdb_cockroach/pkg/ccl/schemachangerccl/testdata/end_to_end/alter_table_locality_rbt_secondary_region_to_primary_region/alter_table_locality_rbt_secondary_region_to_primary_region.definition:1:
          setup
          CREATE DATABASE multiregion_db PRIMARY REGION "us-east1" REGIONS "us-east2", "us-east3";
          CREATE TABLE multiregion_db.public.t (  
            pk INT PRIMARY KEY,
            i INT NOT NULL,
            j STRING,
            INDEX(i)
          ) LOCALITY REGIONAL BY TABLE IN "us-east2";
          ----
    test_server_shim.go:95: cluster virtualization disabled due to issue: #156308 (expected label: C-test-failure)
    test_server_shim.go:95: cluster virtualization disabled due to issue: #156308 (expected label: C-test-failure)
    datadriven.go:357: /mnt/engflow/worker/work/0/exec/bazel-out/k8-fastbuild/bin/pkg/ccl/schemachangerccl/sctestbackupmrccl/sctestbackupmrccl_test_/sctestbackupmrccl_test.runfiles/com_github_cockroachdb_cockroach/pkg/ccl/schemachangerccl/testdata/end_to_end/alter_table_locality_rbt_secondary_region_to_primary_region/alter_table_locality_rbt_secondary_region_to_primary_region.definition:11: still running after 10.000065845s
    panic.go:694: -- test log scope end --
test logs left over in: outputs.zip/logTestBackupSuccess_multiregion_alter_table_locality_rbt_secondary_region_to_primary_region2730549172
--- FAIL: TestBackupSuccess_multiregion_alter_table_locality_rbt_secondary_region_to_primary_region (15.90s)
=== RUN   TestBackupSuccess_multiregion_alter_table_locality_rbt_secondary_region_to_primary_region/post_commit_stage_1_of_1
--- FAIL: TestBackupSuccess_multiregion_alter_table_locality_rbt_secondary_region_to_primary_region/post_commit_stage_1_of_1 (3.78s)
=== RUN   TestBackupSuccess_multiregion_alter_table_locality_rbt_secondary_region_to_primary_region/post_commit_stage_1_of_1/restore_all_tables_in_database
    backup.go:948: error executing query="RESTORE TABLE multiregion_db.public.t FROM LATEST IN 'userfile://backups.public.userfiles_$user/data_PostCommitPhase_1' WITH skip_missing_sequences, skip_missing_udfs" args=[]: pq: table descriptor rewrite failed: rewriting declarative schema changer state: rewriting descriptor ids: missing rewrite for id 108 in TableLocalitySecondaryRegion:{DescID: 127, ReferencedDescID: 108, Value: us-east2}
--- FAIL: TestBackupSuccess_multiregion_alter_table_locality_rbt_secondary_region_to_primary_region/post_commit_stage_1_of_1/restore_all_tables_in_database (0.24s)
```

Parameters:
 - <code>attempt=1</code>
 - <code>run=1</code>
 - <code>shard=45</code>
<details><summary>Help</summary>
<p>

See also: [How To Investigate a Go Test Failure \(internal\)](https://cockroachlabs.atlassian.net/l/c/HgfXfJgM)
</p>
</details>
/cc @cockroachdb/sql-foundations
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*TestBackupSuccess_multiregion_alter_table_locality_rbt_secondary_region_to_primary_region.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/bazci/githubpost/issues)

</sub>

Jira issue: CRDB-63210

### LINKED ISSUE #169088: pkg/ccl/schemachangerccl/sctestbackupmrccl/sctestbackupmrccl_test: TestBackupSuccess_multiregion_alter_table_locality_rbt_secondary_region_to_primary_region failed
pkg/ccl/schemachangerccl/sctestbackupmrccl/sctestbackupmrccl_test.TestBackupSuccess_multiregion_alter_table_locality_rbt_secondary_region_to_primary_region [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Ci_TestsAwsLinuxArm64_UnitTests/21326638?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Ci_TestsAwsLinuxArm64_UnitTests/21326638?buildTab=artifacts#/) on master @ [bc211692c608064757b4fe998d9dce51deb823f5](https://github.com/cockroachdb/cockroach/commits/bc211692c608064757b4fe998d9dce51deb823f5):

```
=== RUN   TestBackupSuccess_multiregion_alter_table_locality_rbt_secondary_region_to_primary_region
    test_log_scope.go:172: test logs captured to: /artifacts/tmp/_tmp/d3150f4d25f43307ce504209c6f28e87/logTestBackupSuccess_multiregion_alter_table_locality_rbt_secondary_region_to_primary_region1026986890
    test_log_scope.go:82: use -show-logs to present logs inline
    framework.go:572: 
        /home/roach/.cache/bazel/_bazel_roach/c5a4e7d36696d9cd970af2045211a7df/sandbox/processwrapper-sandbox/20005/execroot/com_github_cockroachdb_cockroach/bazel-out/aarch64-fastbuild/bin/pkg/ccl/schemachangerccl/sctestbackupmrccl/sctestbackupmrccl_test_/sctestbackupmrccl_test.runfiles/com_github_cockroachdb_cockroach/pkg/ccl/schemachangerccl/testdata/end_to_end/alter_table_locality_rbt_secondary_region_to_primary_region/alter_table_locality_rbt_secondary_region_to_primary_region.definition:1:
          setup
          CREATE DATABASE multiregion_db PRIMARY REGION "us-east1" REGIONS "us-east2", "us-east3";
          CREATE TABLE multiregion_db.public.t (  
            pk INT PRIMARY KEY,
            i INT NOT NULL,
            j STRING,
            INDEX(i)
          ) LOCALITY REGIONAL BY TABLE IN "us-east2";
          ----
    test_server_shim.go:95: cluster virtualization disabled due to issue: #156308 (expected label: C-test-failure)
    test_server_shim.go:95: cluster virtualization disabled due to issue: #156308 (expected label: C-test-failure)
    datadriven.go:357: /home/roach/.cache/bazel/_bazel_roach/c5a4e7d36696d9cd970af2045211a7df/sandbox/processwrapper-sandbox/20005/execroot/com_github_cockroachdb_cockroach/bazel-out/aarch64-fastbuild/bin/pkg/ccl/schemachangerccl/sctestbackupmrccl/sctestbackupmrccl_test_/sctestbackupmrccl_test.runfiles/com_github_cockroachdb_cockroach/pkg/ccl/schemachangerccl/testdata/end_to_end/alter_table_locality_rbt_secondary_region_to_primary_region/alter_table_locality_rbt_secondary_region_to_primary_region.definition:11: still running after 10.000050123s
    panic.go:694: -- test log scope end --
test logs left over in: /artifacts/tmp/_tmp/d3150f4d25f43307ce504209c6f28e87/logTestBackupSuccess_multiregion_alter_table_locality_rbt_secondary_region_to_primary_region1026986890
--- FAIL: TestBackupSuccess_multiregion_alter_table_locality_rbt_secondary_region_to_primary_region (13.46s)
=== RUN   TestBackupSuccess_multiregion_alter_table_locality_rbt_secondary_region_to_primary_region/post_commit_stage_1_of_1
--- FAIL: TestBackupSuccess_multiregion_alter_table_locality_rbt_secondary_region_to_primary_region/post_commit_stage_1_of_1 (3.54s)
=== RUN   TestBackupSuccess_multiregion_alter_table_locality_rbt_secondary_region_to_primary_region/post_commit_stage_1_of_1/restore_all_tables_in_database
    backup.go:948: error executing query="RESTORE TABLE multiregion_db.public.t FROM LATEST IN 'userfile://backups.public.userfiles_$user/data_PostCommitPhase_1' WITH skip_missing_sequences, skip_missing_udfs" args=[]: pq: table descriptor rewrite failed: rewriting declarative schema changer state: rewriting descriptor ids: missing rewrite for id 108 in TableLocalitySecondaryRegion:{DescID: 127, ReferencedDescID: 108, Value: us-east2}
--- FAIL: TestBackupSuccess_multiregion_alter_table_locality_rbt_secondary_region_to_primary_region/post_commit_stage_1_of_1/restore_all_tables_in_database (0.23s)
```
<details><summary>Help</summary>
<p>

See also: [How To Investigate a Go Test Failure \(internal\)](https://cockroachlabs.atlassian.net/l/c/HgfXfJgM)
</p>
</details>
/cc @cockroachdb/sql-foundations
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*TestBackupSuccess_multiregion_alter_table_locality_rbt_secondary_region_to_primary_region.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/bazci/githubpost/issues)

</sub>

Jira issue: CRDB-63245

### LINKED ISSUE #169089: pkg/ccl/schemachangerccl/sctestbackupmrccl/sctestbackupmrccl_test: TestBackupSuccess_multiregion_alter_table_locality_rbt_secondary_region_to_primary_region failed
pkg/ccl/schemachangerccl/sctestbackupmrccl/sctestbackupmrccl_test.TestBackupSuccess_multiregion_alter_table_locality_rbt_secondary_region_to_primary_region [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Ci_TestsAwsLinuxArm64_UnitTests/21326682?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Ci_TestsAwsLinuxArm64_UnitTests/21326682?buildTab=artifacts#/) on master @ [1b0945c824a7b033449e4c15416596c135fb52a9](https://github.com/cockroachdb/cockroach/commits/1b0945c824a7b033449e4c15416596c135fb52a9):

```
=== RUN   TestBackupSuccess_multiregion_alter_table_locality_rbt_secondary_region_to_primary_region
    test_log_scope.go:172: test logs captured to: /artifacts/tmp/_tmp/d3150f4d25f43307ce504209c6f28e87/logTestBackupSuccess_multiregion_alter_table_locality_rbt_secondary_region_to_primary_region220829677
    test_log_scope.go:82: use -show-logs to present logs inline
    framework.go:572: 
        /home/roach/.cache/bazel/_bazel_roach/c5a4e7d36696d9cd970af2045211a7df/sandbox/processwrapper-sandbox/20714/execroot/com_github_cockroachdb_cockroach/bazel-out/aarch64-fastbuild/bin/pkg/ccl/schemachangerccl/sctestbackupmrccl/sctestbackupmrccl_test_/sctestbackupmrccl_test.runfiles/com_github_cockroachdb_cockroach/pkg/ccl/schemachangerccl/testdata/end_to_end/alter_table_locality_rbt_secondary_region_to_primary_region/alter_table_locality_rbt_secondary_region_to_primary_region.definition:1:
          setup
          CREATE DATABASE multiregion_db PRIMARY REGION "us-east1" REGIONS "us-east2", "us-east3";
          CREATE TABLE multiregion_db.public.t (  
            pk INT PRIMARY KEY,
            i INT NOT NULL,
            j STRING,
            INDEX(i)
          ) LOCALITY REGIONAL BY TABLE IN "us-east2";
          ----
    test_server_shim.go:95: cluster virtualization disabled due to issue: #156308 (expected label: C-test-failure)
    test_server_shim.go:95: cluster virtualization disabled due to issue: #156308 (expected label: C-test-failure)
    datadriven.go:357: /home/roach/.cache/bazel/_bazel_roach/c5a4e7d36696d9cd970af2045211a7df/sandbox/processwrapper-sandbox/20714/execroot/com_github_cockroachdb_cockroach/bazel-out/aarch64-fastbuild/bin/pkg/ccl/schemachangerccl/sctestbackupmrccl/sctestbackupmrccl_test_/sctestbackupmrccl_test.runfiles/com_github_cockroachdb_cockroach/pkg/ccl/schemachangerccl/testdata/end_to_end/alter_table_locality_rbt_secondary_region_to_primary_region/alter_table_locality_rbt_secondary_region_to_primary_region.definition:11: still running after 10.001476266s
    datadriven.go:357: /home/roach/.cache/bazel/_bazel_roach/c5a4e7d36696d9cd970af2045211a7df/sandbox/processwrapper-sandbox/20714/execroot/com_github_cockroachdb_cockroach/bazel-out/aarch64-fastbuild/bin/pkg/ccl/schemachangerccl/sctestbackupmrccl/sctestbackupmrccl_test_/sctestbackupmrccl_test.runfiles/com_github_cockroachdb_cockroach/pkg/ccl/schemachangerccl/testdata/end_to_end/alter_table_locality_rbt_secondary_region_to_primary_region/alter_table_locality_rbt_secondary_region_to_primary_region.definition:11: still running after 20.002281299s
    panic.go:694: -- test log scope end --
test logs left over in: /artifacts/tmp/_tmp/d3150f4d25f43307ce504209c6f28e87/logTestBackupSuccess_multiregion_alter_table_locality_rbt_secondary_region_to_primary_region220829677
--- FAIL: TestBackupSuccess_multiregion_alter_table_locality_rbt_secondary_region_to_primary_region (29.48s)
=== RUN   TestBackupSuccess_multiregion_alter_table_locality_rbt_secondary_region_to_primary_region/post_commit_stage_1_of_1
--- FAIL: TestBackupSuccess_multiregion_alter_table_locality_rbt_secondary_region_to_primary_region/post_commit_stage_1_of_1 (6.54s)
=== RUN   TestBackupSuccess_multiregion_alter_table_locality_rbt_secondary_region_to_primary_region/post_commit_stage_1_of_1/restore_all_tables_in_database
    backup.go:948: error executing query="RESTORE TABLE multiregion_db.public.t FROM LATEST IN 'userfile://backups.public.userfiles_$user/data_PostCommitPhase_1' WITH skip_missing_sequences, skip_missing_udfs" args=[]: pq: table descriptor rewrite failed: rewriting declarative schema changer state: rewriting descriptor ids: missing rewrite for id 108 in TableLocalitySecondaryRegion:{DescID: 127, ReferencedDescID: 108, Value: us-east2}
--- FAIL: TestBackupSuccess_multiregion_alter_table_locality_rbt_secondary_region_to_primary_region/post_commit_stage_1_of_1/restore_all_tables_in_database (0.33s)
```
<details><summary>Help</summary>
<p>

See also: [How To Investigate a Go Test Failure \(internal\)](https://cockroachlabs.atlassian.net/l/c/HgfXfJgM)
</p>
</details>
/cc @cockroachdb/sql-foundations
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*TestBackupSuccess_multiregion_alter_table_locality_rbt_secondary_region_to_primary_region.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/bazci/githubpost/issues)

</sub>

Jira issue: CRDB-63246

### LINKED ISSUE #169090: pkg/ccl/schemachangerccl/sctestbackupmrccl/sctestbackupmrccl_test: TestBackupSuccess_multiregion_alter_table_locality_rbt_secondary_region_to_primary_region failed
pkg/ccl/schemachangerccl/sctestbackupmrccl/sctestbackupmrccl_test.TestBackupSuccess_multiregion_alter_table_locality_rbt_secondary_region_to_primary_region [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Ci_TestsAwsLinuxArm64_UnitTests/21326705?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Ci_TestsAwsLinuxArm64_UnitTests/21326705?buildTab=artifacts#/) on master @ [be9c14beadcb1a7ff4c7e9f842f47f9bd7e86a3b](https://github.com/cockroachdb/cockroach/commits/be9c14beadcb1a7ff4c7e9f842f47f9bd7e86a3b):

```
=== RUN   TestBackupSuccess_multiregion_alter_table_locality_rbt_secondary_region_to_primary_region
    test_log_scope.go:172: test logs captured to: /artifacts/tmp/_tmp/d3150f4d25f43307ce504209c6f28e87/logTestBackupSuccess_multiregion_alter_table_locality_rbt_secondary_region_to_primary_region3969086969
    test_log_scope.go:82: use -show-logs to present logs inline
    framework.go:572: 
        /home/roach/.cache/bazel/_bazel_roach/c5a4e7d36696d9cd970af2045211a7df/sandbox/processwrapper-sandbox/20755/execroot/com_github_cockroachdb_cockroach/bazel-out/aarch64-fastbuild/bin/pkg/ccl/schemachangerccl/sctestbackupmrccl/sctestbackupmrccl_test_/sctestbackupmrccl_test.runfiles/com_github_cockroachdb_cockroach/pkg/ccl/schemachangerccl/testdata/end_to_end/alter_table_locality_rbt_secondary_region_to_primary_region/alter_table_locality_rbt_secondary_region_to_primary_region.definition:1:
          setup
          CREATE DATABASE multiregion_db PRIMARY REGION "us-east1" REGIONS "us-east2", "us-east3";
          CREATE TABLE multiregion_db.public.t (  
            pk INT PRIMARY KEY,
            i INT NOT NULL,
            j STRING,
            INDEX(i)
          ) LOCALITY REGIONAL BY TABLE IN "us-east2";
          ----
    test_server_shim.go:95: cluster virtualization disabled due to issue: #156308 (expected label: C-test-failure)
    test_server_shim.go:95: cluster virtualization disabled due to issue: #156308 (expected label: C-test-failure)
    datadriven.go:357: /home/roach/.cache/bazel/_bazel_roach/c5a4e7d36696d9cd970af2045211a7df/sandbox/processwrapper-sandbox/20755/execroot/com_github_cockroachdb_cockroach/bazel-out/aarch64-fastbuild/bin/pkg/ccl/schemachangerccl/sctestbackupmrccl/sctestbackupmrccl_test_/sctestbackupmrccl_test.runfiles/com_github_cockroachdb_cockroach/pkg/ccl/schemachangerccl/testdata/end_to_end/alter_table_locality_rbt_secondary_region_to_primary_region/alter_table_locality_rbt_secondary_region_to_primary_region.definition:11: still running after 10.000100049s
    panic.go:694: -- test log scope end --
test logs left over in: /artifacts/tmp/_tmp/d3150f4d25f43307ce504209c6f28e87/logTestBackupSuccess_multiregion_alter_table_locality_rbt_secondary_region_to_primary_region3969086969
--- FAIL: TestBackupSuccess_multiregion_alter_table_locality_rbt_secondary_region_to_primary_region (17.98s)
=== RUN   TestBackupSuccess_multiregion_alter_table_locality_rbt_secondary_region_to_primary_region/post_commit_stage_1_of_1
--- FAIL: TestBackupSuccess_multiregion_alter_table_locality_rbt_secondary_region_to_primary_region/post_commit_stage_1_of_1 (4.25s)
=== RUN   TestBackupSuccess_multiregion_alter_table_locality_rbt_secondary_region_to_primary_region/post_commit_stage_1_of_1/restore_all_tables_in_database
    backup.go:948: error executing query="RESTORE TABLE multiregion_db.public.t FROM LATEST IN 'userfile://backups.public.userfiles_$user/data_PostCommitPhase_1' WITH skip_missing_sequences, skip_missing_udfs" args=[]: pq: table descriptor rewrite failed: rewriting declarative schema changer state: rewriting descriptor ids: missing rewrite for id 108 in TableLocalitySecondaryRegion:{DescID: 127, ReferencedDescID: 108, Value: us-east2}
--- FAIL: TestBackupSuccess_multiregion_alter_table_locality_rbt_secondary_region_to_primary_region/post_commit_stage_1_of_1/restore_all_tables_in_database (0.31s)
```
<details><summary>Help</summary>
<p>

See also: [How To Investigate a Go Test Failure \(internal\)](https://cockroachlabs.atlassian.net/l/c/HgfXfJgM)
</p>
</details>
/cc @cockroachdb/sql-foundations
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*TestBackupSuccess_multiregion_alter_table_locality_rbt_secondary_region_to_primary_region.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/bazci/githubpost/issues)

</sub>

Jira issue: CRDB-63247

### LINKED ISSUE #169128: pkg/ccl/schemachangerccl/sctestbackupmrccl/sctestbackupmrccl_test: TestBackupSuccess_multiregion_alter_table_locality_rbt_secondary_region_to_primary_region failed
pkg/ccl/schemachangerccl/sctestbackupmrccl/sctestbackupmrccl_test.TestBackupSuccess_multiregion_alter_table_locality_rbt_secondary_region_to_primary_region [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Ci_TestsIbmCloudLinuxS390x_UnitTestsS390x/21327941?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Ci_TestsIbmCloudLinuxS390x_UnitTestsS390x/21327941?buildTab=artifacts#/) on master @ [daec8eb58cf82768a4e2c6336324e4779d857a6e](https://github.com/cockroachdb/cockroach/commits/daec8eb58cf82768a4e2c6336324e4779d857a6e):

```
=== RUN   TestBackupSuccess_multiregion_alter_table_locality_rbt_secondary_region_to_primary_region
    test_log_scope.go:172: test logs captured to: /artifacts/tmp/_tmp/7c378d1c41067478bc42a8d97bbbd09b/logTestBackupSuccess_multiregion_alter_table_locality_rbt_secondary_region_to_primary_region3902025439
    test_log_scope.go:82: use -show-logs to present logs inline
    framework.go:572: 
        /home/roach/.cache/bazel/_bazel_roach/c5a4e7d36696d9cd970af2045211a7df/sandbox/processwrapper-sandbox/3353/execroot/com_github_cockroachdb_cockroach/bazel-out/s390x-fastbuild/bin/pkg/ccl/schemachangerccl/sctestbackupmrccl/sctestbackupmrccl_test_/sctestbackupmrccl_test.runfiles/com_github_cockroachdb_cockroach/pkg/ccl/schemachangerccl/testdata/end_to_end/alter_table_locality_rbt_secondary_region_to_primary_region/alter_table_locality_rbt_secondary_region_to_primary_region.definition:1:
          setup
          CREATE DATABASE multiregion_db PRIMARY REGION "us-east1" REGIONS "us-east2", "us-east3";
          CREATE TABLE multiregion_db.public.t (  
            pk INT PRIMARY KEY,
            i INT NOT NULL,
            j STRING,
            INDEX(i)
          ) LOCALITY REGIONAL BY TABLE IN "us-east2";
          ----
    test_server_shim.go:95: cluster virtualization disabled due to issue: #156308 (expected label: C-test-failure)
    test_server_shim.go:95: cluster virtualization disabled due to issue: #156308 (expected label: C-test-failure)
    datadriven.go:357: /home/roach/.cache/bazel/_bazel_roach/c5a4e7d36696d9cd970af2045211a7df/sandbox/processwrapper-sandbox/3353/execroot/com_github_cockroachdb_cockroach/bazel-out/s390x-fastbuild/bin/pkg/ccl/schemachangerccl/sctestbackupmrccl/sctestbackupmrccl_test_/sctestbackupmrccl_test.runfiles/com_github_cockroachdb_cockroach/pkg/ccl/schemachangerccl/testdata/end_to_end/alter_table_locality_rbt_secondary_region_to_primary_region/alter_table_locality_rbt_secondary_region_to_primary_region.definition:11: still running after 10.000046596s
    datadriven.go:357: /home/roach/.cache/bazel/_bazel_roach/c5a4e7d36696d9cd970af2045211a7df/sandbox/processwrapper-sandbox/3353/execroot/com_github_cockroachdb_cockroach/bazel-out/s390x-fastbuild/bin/pkg/ccl/schemachangerccl/sctestbackupmrccl/sctestbackupmrccl_test_/sctestbackupmrccl_test.runfiles/com_github_cockroachdb_cockroach/pkg/ccl/schemachangerccl/testdata/end_to_end/alter_table_locality_rbt_secondary_region_to_primary_region/alter_table_locality_rbt_secondary_region_to_primary_region.definition:11: still running after 20.000860334s
    panic.go:694: -- test log scope end --
test logs left over in: /artifacts/tmp/_tmp/7c378d1c41067478bc42a8d97bbbd09b/logTestBackupSuccess_multiregion_alter_table_locality_rbt_secondary_region_to_primary_region3902025439
--- FAIL: TestBackupSuccess_multiregion_alter_table_locality_rbt_secondary_region_to_primary_region (23.99s)
=== RUN   TestBackupSuccess_multiregion_alter_table_locality_rbt_secondary_region_to_primary_region/post_commit_stage_1_of_1
--- FAIL: TestBackupSuccess_multiregion_alter_table_locality_rbt_secondary_region_to_primary_region/post_commit_stage_1_of_1 (6.23s)
=== RUN   TestBackupSuccess_multiregion_alter_table_locality_rbt_secondary_region_to_primary_region/post_commit_stage_1_of_1/restore_all_tables_in_database
    backup.go:948: error executing query="RESTORE TABLE multiregion_db.public.t FROM LATEST IN 'userfile://backups.public.userfiles_$user/data_PostCommitPhase_1' WITH skip_missing_sequences, skip_missing_udfs" args=[]: pq: table descriptor rewrite failed: rewriting declarative schema changer state: rewriting descriptor ids: missing rewrite for id 108 in TableLocalitySecondaryRegion:{DescID: 127, ReferencedDescID: 108, Value: us-east2}
--- FAIL: TestBackupSuccess_multiregion_alter_table_locality_rbt_secondary_region_to_primary_region/post_commit_stage_1_of_1/restore_all_tables_in_database (0.33s)
```
<details><summary>Help</summary>
<p>

See also: [How To Investigate a Go Test Failure \(internal\)](https://cockroachlabs.atlassian.net/l/c/HgfXfJgM)
</p>
</details>
/cc @cockroachdb/sql-foundations
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*TestBackupSuccess_multiregion_alter_table_locality_rbt_secondary_region_to_primary_region.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/bazci/githubpost/issues)

</sub>

Jira issue: CRDB-63283

### PR DESCRIPTION
**Pull request by spilchen**
When a multi-region table is backed up mid-`ALTER TABLE ... SET LOCALITY` and restored at the table level, the table's declarative schema changer state may reference the source database's region enum and array type IDs. Only table descriptors get entries in `descriptorRewrites` during table-level restore, so the rewrite passes failed with one of:

- `missing rewrite for type N` (in `TypeDescs`)
- `missing rewrite for id N in TableLocalitySecondaryRegion` (in `rewriteSchemaChangerState`, RBT-IN-region case)
- `missing rewrite for id N in ColumnType` (in `rewriteSchemaChangerState`, RBR variants where the `crdb_region` column type closure references both the enum and its array type)

`remapTables` now records `ToExisting` rewrites for both the source enum and array type IDs to the destination database's existing enum and array type (`parentDB.MultiRegionEnumID` and the enum descriptor's `ArrayTypeID`) before the rewrite passes run. The source IDs are discovered from `typesByID` when the enum descriptor is in scope (RBR and other UDT-referencing cases), or from `TableLocalitySecondaryRegion` in the schema changer state otherwise (RBT-IN-region case).

Resolves: #169128
Resolves: #168804 
Resolves: #168884
Resolves: #169008 
Resolves: #169088
Resolves: #169089
Resolves: #169090

Epic: none

Release note (bug fix): Fixed a bug where RESTORE TABLE of a multi-region table backed up mid-ALTER TABLE ... SET LOCALITY would fail with a descriptor rewrite error.

### CODE REVIEW

**Review by fqazi — APPROVED** [review]
:lgtm: 

@spilchen Nice work!

> @fqazi reviewed 3 files and all commit messages, and made 1 comment.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/169277#-:-OrObsrNCxUDTdw9jTK6:b1sj39q)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on andrew-r-thomas).

**Comment by shghasemi** [comment]
Thanks for fixing this Matt. Do you know why the test started failing recently? I'm surprised that we didn't see any failures for months and it failed several times during this week. 

Also, we might want to backport this to 26.2.

File: pkg/backup/restore_planning.go [hunk 1]
```diff
@@ -468,6 +480,123 @@ func remapTables(
...
+	// crdb_region values exist only in the source would be silently mismapped
+	// after the rewrite. The fallback branch in findSourceRegionEnumIDs (where
+	// srcEnum is nil) has no source descriptor to compare against and skips
+	// this check.
+	if srcEnum != nil {
+		if err := srcEnum.IsCompatibleWith(destEnumDesc); err != nil {
+			return errors.Wrapf(err,
+				"%q is not compatible with type %q existing in cluster",
+				srcEnum.GetName(), destEnumDesc.GetName())
+		}
```
Comment (rafiss) [inline pkg/backup/restore_planning.go:541]: nit: this wraps an error that already says the same thing — you end up with:

```
"us-east-1" is not compatible with type "crdb_internal_region" existing in cluster: "us-east-1" of type ENUM is not compatible with type ENUM ...
```

Maybe just add the table/db context instead?

```suggestion
		if err := srcEnum.IsCompatibleWith(destEnumDesc); err != nil {
			return errors.Wrapf(err,
				"table-level restore of %q into database %q",
				table.GetName(), parentDB.GetName())
		}
```

File: pkg/backup/restore_planning.go [hunk 2]
```diff
@@ -468,6 +480,123 @@ func remapTables(
...
+	if !needRewrite(srcEnumID) && !needRewrite(srcArrayID) {
+		return nil
+	}
+
+	destEnumID, err := parentDB.MultiRegionEnumID()
+	if err != nil {
+		return errors.Wrapf(err,
+			"looking up region enum for table-level restore of %q into database %q",
+			table.GetName(), parentDB.GetName())
+	}
```
Comment (rafiss) [inline pkg/backup/restore_planning.go:523]: nit: `MultiRegionEnumID` only errors when `!IsMultiRegion()`, which we already checked on line 503. Either drop to an assertion error or leave a comment so the next reader doesn't go looking for a real failure mode here.

File: pkg/backup/testdata/backup-restore/restore-table-mid-locality-change [hunk 3]
```diff
@@ -0,0 +1,62 @@
...
+exec-sql
+CREATE DATABASE d2 PRIMARY REGION "us-east-1" REGIONS "us-west-1", "eu-central-1";
+----
+
+# Before the fix this failed with:
+#   pq: table descriptor rewrite failed: rewriting declarative schema
+#   changer state: rewriting descriptor ids: missing rewrite for id N in
+#   TableLocalitySecondaryRegion:{...}
+exec-sql
+RESTORE TABLE d.t FROM LATEST IN 'nodelocal://1/test-backup' WITH into_db = 'd2', skip_missing_sequences, skip_missing_udfs;
```
Comment (rafiss) [inline pkg/backup/testdata/backup-restore/restore-table-mid-locality-change:54]: The `IsCompatibleWith` check in `maybeAddRegionEnumRewriteForSchemaChangeState` is the only thing preventing silent mismapping of `crdb_region` values, but nothing tests it. Worth adding a case where the source enum has a region the destination doesn't, and asserting RESTORE fails with the compatibility error.

**Review by rafiss — APPROVED** [review]
Approved. A few non-blocking suggestions inline.

---
*(made with [/review-crdb](https://github.com/cockroachdb/cockroach/blob/master/.claude/skills/review-crdb/SKILL.md))*

**Comment by spilchen** [comment]
> Thanks for fixing this Matt. Do you know why the test started failing recently? I'm surprised that we didn't see any failures for months and it failed several times during this week.
> 
> Also, we might want to backport this to 26.2.

I'm not sure why it started to fail recently.... Yes, good idea to backport.

File: pkg/backup/testdata/backup-restore/restore-table-mid-locality-change (hunk 3 above)
Comment (spilchen) [reply pkg/backup/testdata/backup-restore/restore-table-mid-locality-change:54]: Added new test.

**Review by spilchen — COMMENTED** [review]
> @spilchen made 1 comment and resolved 2 discussions.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/169277)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on andrew-r-thomas, fqazi, and rafiss).

**Comment by spilchen** [comment]
TFTRs!

/trunk merge

**Comment by spilchen** [comment]
blathers backport 26.1

**Comment by spilchen** [comment]
blathers backport 26.2

**Comment by spilchen** [comment]
This only needs to be backported to 26.2. I mistakenly did 26.1 earlier. Commit cf3ad306d75 landed only in release-26.2, which is a prereq for this.
