### PR TITLE
util/log: fix data race in `TestRedactedDecodeFile`

### LINKED ISSUE #71902: util/log: TestRedactedDecodeFile failed
util/log.TestRedactedDecodeFile [failed](https://teamcity.cockroachdb.com/viewLog.html?buildId=3626947&tab=buildLog) with [artifacts](https://teamcity.cockroachdb.com/viewLog.html?buildId=3626947&tab=artifacts#/) on master @ [31ccb1ce864ebea41131fc94e28ff3c398c9a5fe](https://github.com/cockroachdb/cockroach/commits/31ccb1ce864ebea41131fc94e28ff3c398c9a5fe):

```
--- FAIL: TestRedactedDecodeFile (0.03s)
=== RUN   TestRedactedDecodeFile/5
    redact_test.go:147: test logs captured to: /go/src/github.com/cockroachdb/cockroach/artifacts/logTestRedactedDecodeFile_5155915646
    redact_test.go:151: -- test log scope file rotation --
==================
WARNING: DATA RACE
Read at 0x00c000204028 by goroutine 7:
  bufio.(*Writer).Flush()
      /usr/local/go/src/bufio/bufio.go:604 +0x7e
  github.com/cockroachdb/cockroach/pkg/util/log.(*syncBuffer).Flush()
      <autogenerated>:1 +0x5d
  github.com/cockroachdb/cockroach/pkg/util/log.(*fileSink).flushAndMaybeSyncLocked()
      /go/src/github.com/cockroachdb/cockroach/pkg/util/log/file.go:269 +0x16b
  github.com/cockroachdb/cockroach/pkg/util/log.(*fileSink).lockAndFlushAndMaybeSync()
      /go/src/github.com/cockroachdb/cockroach/pkg/util/log/file.go:231 +0x9d
  github.com/cockroachdb/cockroach/pkg/util/log.flushDaemon.func1()
      /go/src/github.com/cockroachdb/cockroach/pkg/util/log/log_flush.go:87 +0x4a
  github.com/cockroachdb/cockroach/pkg/util/log.(*sinkInfoRegistry).iterFileSinks.func1()
      /go/src/github.com/cockroachdb/cockroach/pkg/util/log/registry.go:84 +0x90
  github.com/cockroachdb/cockroach/pkg/util/log.(*sinkInfoRegistry).iter()
      /go/src/github.com/cockroachdb/cockroach/pkg/util/log/registry.go:72 +0x11a
  github.com/cockroachdb/cockroach/pkg/util/log.(*sinkInfoRegistry).iterFileSinks()
      /go/src/github.com/cockroachdb/cockroach/pkg/util/log/registry.go:82 +0x64
  github.com/cockroachdb/cockroach/pkg/util/log.flushDaemon()
      /go/src/github.com/cockroachdb/cockroach/pkg/util/log/log_flush.go:86 +0x179

Previous write at 0x00c000204028 by goroutine 50:
  bufio.(*Writer).Flush()
      /usr/local/go/src/bufio/bufio.go:619 +0x3d9
  github.com/cockroachdb/cockroach/pkg/util/log.TestRedactedDecodeFile.func1()
      /go/src/github.com/cockroachdb/cockroach/pkg/util/log/redact_test.go:162 +0x258
  testing.tRunner()
      /usr/local/go/src/testing/testing.go:1193 +0x202

Goroutine 7 (running) created at:
  github.com/cockroachdb/cockroach/pkg/util/log.init.5()
      /go/src/github.com/cockroachdb/cockroach/pkg/util/log/log_flush.go:41 +0x44

Goroutine 50 (running) created at:
  testing.(*T).Run()
      /usr/local/go/src/testing/testing.go:1238 +0x5d7
  github.com/cockroachdb/cockroach/pkg/util/log.TestRedactedDecodeFile()
      /go/src/github.com/cockroachdb/cockroach/pkg/util/log/redact_test.go:144 +0x375
  testing.tRunner()
      /usr/local/go/src/testing/testing.go:1193 +0x202
==================
    redact_test.go:198: -- test log scope end --
test logs left over in: /go/src/github.com/cockroachdb/cockroach/artifacts/logTestRedactedDecodeFile_5155915646
    testing.go:1092: race detected during execution of test
    --- FAIL: TestRedactedDecodeFile/5 (0.01s)
```
<details><summary>Help</summary>
<p>
See also: [How To Investigate a Go Test Failure \(internal\)](https://cockroachlabs.atlassian.net/l/c/HgfXfJgM)Parameters in this failure:

- GOFLAGS=-race -parallel=4
</p>
</details>
/cc @cockroachdb/server knz
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*TestRedactedDecodeFile.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)
</sub>

### PR DESCRIPTION
**Pull request by knz**
Fixes #71902

It's racy to call `Flush()` on the `*syncBuffer` directly, because of
the async flusher.

Release note: None

### CODE REVIEW

File: pkg/util/log/redact_test.go [hunk 1]
```diff
@@ -154,14 +154,14 @@ func TestRedactedDecodeFile(t *testing.T) {
 			Infof(context.Background(), "marker: this is safe, stray marks ‹›, %s", "this is not safe")
 
 			// Retrieve the log writer and log location for this test.
-			info, ok := debugLog.getFileSink().mu.file.(*syncBuffer)
+			debugSink := debugLog.getFileSink()
+			info, ok := debugSink.mu.file.(*syncBuffer)
```
Comment (tbg) [inline pkg/util/log/redact_test.go:158]: Without knowing the internals, I'm not sure why this is safe, is there a reason you can't grab the lock here?

Comment (knz) [reply pkg/util/log/redact_test.go:158]: Grab which lock?

Comment (tbg) [reply pkg/util/log/redact_test.go:158]: I see `debugSink.mu`, so I would've expected a `debugSink.mu.Lock()`before accessing `debugSink.mu.file`.

**Review by knz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/74137)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @tbg)

___
*[pkg/util/log/redact_test.go, line 158 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/74137#-MrSHs5YJGRAOgrXu-Eq-r1-158:-MrSyJDu0W2jL6m0VCRF:b-1hoqby) ([raw file](https://github.com/cockroachdb/cockroach/blob/3b6af69b7f0f085210a437b7779344fb40cb3fcf/pkg/util/log/redact_test.go#L158)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

I see `debugSink.mu`, so I would've expected a `debugSink.mu.Lock()`before accessing `debugSink.mu.file`.
</blockquote></details>

That is a fair question. We look at `debugSink.mu.file` quite often throughout unit tests in this package without grabbing the lock, so I was following convention here.
The reason why this is not racy is that throughout all these unit tests, there is no log file rotation (the tests are too short to run into the file size limit) so `.file` doesn't get written.

However, the fields _inside_ the `*syncBuffer` (e.g. buffer cursor) get updated by Flush calls, and that's racy, hence the need to lock for flushing. 

I don't know what's best here: should we document that these accesses to `.mu.file` are safe and why, or should we revisit the entire directory to add defensive locking  to all the accesses?

**Comment by tbg** [comment]
I personally would lock them all just as a matter of simplicity, but it's fine by me if you consider the status quo ok.

**Comment by knz** [comment]
> I personally would lock them all just as a matter of simplicity, but it's fine by me if you consider the status quo ok.

Ok, done.

**Review by tbg — APPROVED** [review]
Thank you!

**Comment by knz** [comment]
TFYR!

bors r=tbg

**Comment by knz** [comment]
blathers backport 21.2
