### PR TITLE
sql: release save point did not retry for two version invariant errors

### LINKED ISSUE #107171: sql: could not publish new descriptors when creating users within a transaction
**Describe the problem**

When trying to create a SQL user through the CRDB transaction wrapper within cockroach-go, we get the following error: `pq: cannot publish new versions for descriptors: [{users 4 1} {role_options 33 1}], old versions still in use`.

**To Reproduce**

Script to reproduce:

```go
package main

import (
	"context"
	"database/sql"
	"fmt"
	"sync"

	"github.com/cockroachdb/cockroach-go/v2/crdb"
	_ "github.com/lib/pq"
)

func main() {
	db, err := sql.Open("postgres", "postgresql://root@localhost:26257/defaultdb?sslmode=disable")
	if err != nil {
		panic(err)
	}
	defer db.Close()

	err = db.Ping()
	if err != nil {
		panic(err)
	}

	ctx := context.Background()
	var wg sync.WaitGroup
	for i := 170; i < 180; i++ {
		wg.Add(1)
		go func(i int) {
			defer wg.Done()
			if err := crdb.ExecuteTx(ctx, db, nil, func(tx *sql.Tx) error {
				query := fmt.Sprintf(`CREATE USER IF NOT EXISTS "user%d"`, i)
				_, err := tx.ExecContext(ctx, query)
				return err
			}); err != nil {
				panic(err)
			}
		}(i)
	}
	wg.Wait()
}

```

**Expected behavior**

We expected that the script completes successfully.

**Additional data**

This issue seems to manifest on **v22.2.0 onwards**. The error doesn't show up on v22.1.21 (and prior versions).

**Environment:**
 - CockroachDB version: v22.2.0 onwards
 - cockroach-go SHA: `558bee73bf0634385a862b19708de4ed19316fbb`
 - Server OS: MacOS

Jira issue: CRDB-29933

### PR DESCRIPTION
**Pull request by fqazi**
Previously, when release save point was issued for cockroach_restart this would drive a commit, which could run into retryable errors. Like the two version invariant error, which is not tagged as a user facing re triable error, so the client doesn't know to retry. To address this, this patch converts two version invariant errors in this case into user facing retryable errors;

Fixes: #107171

Release note (bug fix): Release save point could incorrectly emit "cannot publish new versions for descriptors" instead of a retryable error to applications.

### CODE REVIEW

File: pkg/sql/catalog/lease/lease_test.go [hunk 1]
```diff
@@ -1586,6 +1586,121 @@ CREATE TABLE t.kv (k CHAR PRIMARY KEY, v CHAR);
...
+	}
+
+	if _, err := txRetry.Exec(`ALTER TABLE t.kv1 RENAME TO t.kv2`); err != nil {
+		t.Fatal(err)
+	}
+
+	var wg sync.WaitGroup
+	wg.Add(1)
+	go func() {
+		// This can hang waiting for one version before tx.Commit() is
```
Comment (rafiss) [inline pkg/sql/catalog/lease/lease_test.go:1675]: nit: use `defer wg.Done()` here in case this code is refactored later to exit early.

File: pkg/sql/catalog/lease/lease_test.go [hunk 2]
```diff
@@ -1586,6 +1586,121 @@ CREATE TABLE t.kv (k CHAR PRIMARY KEY, v CHAR);
...
+		if !testutils.IsError(err,
+			fmt.Sprintf(`TransactionRetryWithProtoRefreshError: cannot publish new versions for descriptors: \[\{kv1 %d 1\}\], old versions still in use`, tableDesc.GetID()),
+		) {
+			t.Errorf("err = %v", err)
+		}
+		err = txRetry.Rollback()
+		if err != nil {
+			t.Errorf("err = %v", err)
+		}
+		wg.Done()
```
Comment (rafiss) [inline pkg/sql/catalog/lease/lease_test.go:1687]: and remove this call to `Done`

File: pkg/sql/conn_executor.go [hunk 3]
```diff
@@ -3285,6 +3285,23 @@ func errIsRetriable(err error) bool {
...
+	if descs.IsTwoVersionInvariantViolationError(err) {
+		if resetErr := ex.resetTransactionOnSchemaChangeRetry(ctx); resetErr != nil {
+			return false, resetErr
+		}
+		// Generating a forced retry error here, right after resetting the
+		// transaction is not exactly necessary, but it's a sound way to
+		// generate the only type of ClientVisibleRetryError we have.
+		return true, ex.state.mu.txn.GenerateForcedRetryableError(ctx, redact.Sprint(err))
+	}
+	return true, err
```
Comment (rafiss) [inline pkg/sql/conn_executor.go:3302]: why does this return `true` here? it doesn't seem to be converted

File: pkg/sql/conn_executor_exec.go [hunk 4]
```diff
@@ -1233,15 +1233,9 @@ func (ex *connExecutor) commitSQLTransaction(
...
-				return ex.makeErrEvent(err, ast)
-			}
-			// Generating a forced retry error here, right after resetting the
-			// transaction is not exactly necessary, but it's a sound way to
-			// generate the only type of ClientVisibleRetryError we have.
-			err = ex.state.mu.txn.GenerateForcedRetryableError(ctx, redact.Sprint(err))
-		}
+		// For certain retryable errors, we should turn them into client visible
+		// errors, since the client needs to retry now.
+		_, err = ex.convertRetriableErrorIntoUserVisibleError(ctx, err)
```
Comment (rafiss) [inline pkg/sql/conn_executor_exec.go:1238]: why do we ignore `converted` here? seems like it should be similar to how you handle it in `execRelease`?

**Review by rafiss — CHANGES_REQUESTED** [review]

File: pkg/sql/conn_executor_savepoints.go [hunk 5]
```diff
@@ -152,6 +152,12 @@ func (ex *connExecutor) execRelease(
 		// Committing the transaction failed. We'll go to state RestartWait if
 		// it's a retriable error, or to state RollbackWait otherwise.
 		if errIsRetriable(err) {
+			// For certain retryable errors, we should turn them into client visible
+			// errors, since the client needs to retry now.
+			var converted bool
```
Comment (chrisseto) [inline pkg/sql/conn_executor_savepoints.go:157]: ooc, why not just use `:=` in the below if statement? Is there not a compiler optimization that renders these equivalent in performance or are we intentionally trying to leak out `err`?

File: pkg/sql/conn_executor.go [hunk 6]
```diff
@@ -3285,6 +3285,23 @@ func errIsRetriable(err error) bool {
 		descs.IsTwoVersionInvariantViolationError(err)
 }
 
+// convertRetriableErrorIntoUserVisibleError converts internal retriable
```
Comment (chrisseto) [inline pkg/sql/conn_executor.go:3288]: when and why would we want to convert an internal error into a user visible error? An example usage here would go a long way!

File: pkg/sql/conn_executor.go (hunk 3 above)
Comment (fqazi) [reply pkg/sql/conn_executor.go:3302]: Yikes, yes that's wrong and buggy. I have changed the flag to be clearer and named it: failedDuringConversion

Comment (fqazi) [reply pkg/sql/conn_executor.go:3302]: To clarify we only want callers to act if we encounter an error during the conversion

File: pkg/sql/conn_executor_exec.go (hunk 4 above)
Comment (fqazi) [reply pkg/sql/conn_executor_exec.go:1238]: Either way, this code path will return the error. In the other case we have special treatment for retriable errors

File: pkg/sql/conn_executor.go (hunk 6 above)
Comment (fqazi) [reply pkg/sql/conn_executor.go:3288]: Good point updated the comment:

// convertRetriableErrorIntoUserVisibleError converts internal retriable
// errors into external, so that the client goes and retries this
// transaction. One example of this is two version invariant errors, which
//happens when a schema change is waiting for a schema change transition to
// propagate. When this happens, we either need to retry externally or internally,
// depending on if we are in an explicit transaction.

**Review by fqazi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/108133)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @chrisseto and @rafiss)

___
*[`pkg/sql/catalog/lease/lease_test.go` line 1687 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/108133#gh-1286341769:-NbNDdT4AfiHSRu_Akjy:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/3c57cdfa57ed422201236e0c75aa0ea537166f17/pkg/sql/catalog/lease/lease_test.go#L1687)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

and remove this call to `Done`
</blockquote></details>

Done.

**Review by rafiss — APPROVED** [review]
nice find on this! and just to confirm, is the example that Jay gave working now?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/108133#-:-NbNVKuCCsCrRixZGKD0:buxpglq)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @chrisseto)

**Comment by fqazi** [comment]
bors r+

(Needed a rebase because of a test infra change)
