### PR TITLE
sql: fix "no user specified" errors in statement bundles

### LINKED ISSUE #80396: sql: statement bundles are missing schema, environment, or table statistics
On `release-22.1.0` (current at https://github.com/cockroachdb/cockroach/commit/dc225064c5f50ae59bd2216283b5a1ee13adbd1), the `env.sql`, `schema.sql`, and `stats*.sql` files have errors like:

```
error getting version: no user specified for internal query
```

These files contain none of the usual information. I first noticed this problem when collecting a statement bundle for the telemetry cluster which was running v22.1.0-beta.2.

Marking this as a GA blocker because the information in these files is absolutely critical for diagnosing performance problems.

### PR DESCRIPTION
**Pull request by mgartner**
A regression was introduced in #71246 that caused errors when running
internal queries to populate files in statement bundles. As a result,
critical information was missing from the `env.sql`, `schema.sql`, and
`stats*.sql` files. This commit fixes the issue by using the internal
executor factory to create an internal executor with the current
session's session data.

Fixes #80396

Release note: None

### CODE REVIEW

File: pkg/sql/explain_bundle.go [hunk 1]
```diff
@@ -431,14 +432,19 @@ func makeStmtEnvCollector(ctx context.Context, ie *InternalExecutor) stmtEnvColl
 	return stmtEnvCollector{ctx: ctx, ie: ie}
 }
 
+// explainBundleUserSessionsDataOverride is an InternalExecutorOverride which
+// overrides the users to the RootUser.
+var explainBundleUserSessionDataOverride = sessiondata.InternalExecutorOverride{
+	User: security.MakeSQLUsernameFromPreNormalizedString(security.RootUser)}
```
Comment (mgartner) [inline pkg/sql/explain_bundle.go:438]: Is it safe to use a root user override here? If not, what is a better alternative?

**Review by knz — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/80405)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @mgartner, @rafiss, and @RichardJCai)

___
*[pkg/sql/explain_bundle.go, line 438 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/80405#-N0HtKBmI8WPeE8BhD0V-r1-438:-N0HtgXP0L0ziR5B8nxp:b-w28ejb) ([raw file](https://github.com/cockroachdb/cockroach/blob/f0413ebe7ec7a7337325c81c751a7e23ea555ad7/pkg/sql/explain_bundle.go#L438)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

Is it safe to use a root user override here? If not, what is a better alternative?
</blockquote></details>

This looks suspicious. Why can't this use the identity of the user requesting the bundle?

**Review by knz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/80405)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @mgartner, @rafiss, and @RichardJCai)

___
*[pkg/sql/explain_bundle.go, line 438 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/80405#-N0HtKBmI8WPeE8BhD0V-r1-438:-N0Htn-7E8z2l6eG3AyL:b-ezi192) ([raw file](https://github.com/cockroachdb/cockroach/blob/f0413ebe7ec7a7337325c81c751a7e23ea555ad7/pkg/sql/explain_bundle.go#L438)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

This looks suspicious. Why can't this use the identity of the user requesting the bundle?
</blockquote></details>

As in, make `stmtEnvCollector` take the requester's username as argument or something like that.

**Comment by rafiss** [comment]
> a node user is insufficient - it does not have
privileges on user-defined relations which is needed for the
SHOW CREATE queries that populate schema.sql.

was this fixed by https://github.com/cockroachdb/cockroach/pull/79098/ ?

**Comment by mgartner** [comment]
How about this second attempt that doesn't use an override at all?

**Review by knz — APPROVED** [review]

**Comment by knz** [comment]
is it already common practice to instantiate InternalExecutors on-the-fly? Is this an expensive operation?

(Asking for a friend - if we don't need to keep a predefined instance around, I would cut down on the server code)

**Comment by mgartner** [comment]
>

I copied this pattern from: https://github.com/cockroachdb/cockroach/blob/2115a44e6993dd4355365b2748fbe8b9aed288ca/pkg/sql/opt_exec_factory.go#L1160-L1163
It seems fairly prolific given that `planner.QueryRowEx`, which is used in numerous places, creates a new internal executor: https://github.com/cockroachdb/cockroach/blob/d4daa99f6bcae263ba351e2b101901dae8bb110f/pkg/sql/planner.go#L879

**Comment by knz** [comment]
Amazing. TIL. Thanks for explaining.

**Comment by mgartner** [comment]
TFTR!

bors r+
