### PR TITLE
roachtest: use versioned bank workloads for mixed version

### LINKED ISSUE #150128: roachtest: tpcc/mixed-headroom/n5cpu16 failed
roachtest.tpcc/mixed-headroom/n5cpu16 [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyAzureBazel/20164911?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyAzureBazel/20164911?buildTab=artifacts#/tpcc/mixed-headroom/n5cpu16) on master @ [f6e9d3fd43f7fe1ace06387984cb79bfeb6f8600](https://github.com/cockroachdb/cockroach/commits/f6e9d3fd43f7fe1ace06387984cb79bfeb6f8600):

```
(mixedversion.go:852).Run: mixed-version test failure while running step 34 (run "TPCC workload"): full command output in run_095317.651813333_n5_cockroach-workload-r.log: COMMAND_PROBLEM: exit status 1
test artifacts and logs in: /artifacts/tpcc/mixed-headroom/n5cpu16/run_1
```

Parameters:
 - <code>arch=amd64</code>
 - <code>cloud=azure</code>
 - <code>coverageBuild=false</code>
 - <code>cpu=16</code>
 - <code>encrypted=true</code>
 - <code>fs=ext4</code>
 - <code>localSSD=true</code>
 - <code>mvtDeploymentMode=shared-process</code>
 - <code>mvtVersions=v25.2.1 → master</code>
 - <code>runtimeAssertionsBuild=false</code>
 - <code>ssd=0</code>
<details><summary>Help</summary>
<p>

See: [roachtest README](https://github.com/cockroachdb/cockroach/blob/master/pkg/cmd/roachtest/README.md)

See: [How To Investigate \(internal\)](https://cockroachlabs.atlassian.net/l/c/SSSBr8c7)

_Grafana is not yet available for azure clusters_</p>
</details>
/cc @cockroachdb/test-eng
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*tpcc/mixed-headroom/n5cpu16.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/bazci/githubpost/issues)

</sub>

Jira issue: CRDB-52579

### PR DESCRIPTION
**Pull request by DarrylWong**
As of #149374, the bank workload is no longer backwards compatible. This changes mixed version tests that use the bank workload to upload a versioned binary and use that to import the workload.

Fixes: https://github.com/cockroachdb/cockroach/issues/150128
Informs: [#147562](https://github.com/cockroachdb/cockroach/issues/147562)
Release note: none

### CODE REVIEW

File: pkg/cmd/roachtest/roachtestutil/mixedversion/mixedversion.go [hunk 1]
```diff
@@ -826,8 +826,13 @@ func (t *Test) BackgroundCommand(
...
 // synchronously as a regular startup function. `runCmd` is the
 // command to actually run the command; it is run in the background.
+//
+// If overrideBinary is true, the binary used to run the command(s) will
+// be replaced with the cockroach binary of the current version the
+// cluster is running in.
+// TODO(testeng): Replace with https://github.com/cockroachdb/cockroach/issues/147374
 func (t *Test) Workload(
-	name string, node option.NodeListOption, initCmd, runCmd *roachtestutil.Command,
+	name string, node option.NodeListOption, initCmd, runCmd *roachtestutil.Command, overrideBinary bool,
```
Comment (DarrylWong) [inline pkg/cmd/roachtest/roachtestutil/mixedversion/mixedversion.go]: I kept this behavior as opt in for now to reduce surface area of this change, but I feel like after #147374 we can make it the default.

**Comment by DarrylWong** [comment]
https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/20280058?hideProblemsFromDependencies=false&hideTestsFromDependencies=false


(backup failure is a preexisting issue. was able to get a passing run)

**Review by herkolategan — APPROVED** [review]

**Comment by DarrylWong** [comment]
TFTR!

bors r=herkolategan
