### PR TITLE
server: clear tenant cookies when tenant is missing

### LINKED ISSUE #95365: server: new clusters try to create `demo-tenant` for no reason
```
rm -rf cockroach-data
./cockroach start-single-node --insecure --logtostderr
```

The log is spammed with:

```

W230117 16:37:15.222589 1078 server/server_controller.go:254 ⋮ [T1] 179  unable to start server for tenant ‹"demo-tenant"›: no tenant found with name ‹"demo-tenant"›
```

Note that this is not a demo cluster.

### LINKED ISSUE #95366: dbconsole: console doesn't load for new clusters - interference with demo cookies?
I sometimes get in a state where the console doesn't load at all for a new cluster
```
rm -rf cockroach-data
./cockroach start-single-node --insecure --logtostderr
```

Go to `http://127.0.0.1:8080/` - nothing loads. The Chrome Console shows:
```
Failed to load resource: the server responded with a status of 500 ()              chrome-error://chromewebdata/:1
```

Using an incognito window works; I believe that the breakage has something to do with having previously run a secure demo cluster (or a secure cluster in general perhaps) and having some cookies around from logging into that. Adding an `--http-port=8081` and accessing on that port also works (without incognito), which tracks with this having something to do with cookies.
Interestingly, after accessing the page in incognito, accessing it from the non-incognito window seems to work again, until starting another demo cluster and logging into that.

Jira issue: CRDB-23485

### PR DESCRIPTION
**Pull request by dhartunian**
Previously, when we had cookies in an HTTP Request referencing a tenant, and that tenant didn't exist, we'd be stuck in an error loop constantly attempting to start a tenant that didn't exist.

This commit updates the error log in `server_controller.go` to clear cookies for multi-tenant sessions when we return an error in order to break the browser out of the bad update cycle and have it either continue happily with an insecure cluster that doesn't need a session anyway, or request a new one by routing the user to the login page.

Resolves: #95365
Resolves: #95366
Epic: CRDB-14545

Release note: None

### CODE REVIEW

File: pkg/server/server_controller.go [hunk 1]
```diff
@@ -252,6 +252,21 @@ func (c *serverController) httpMux(w http.ResponseWriter, r *http.Request) {
 	s, err := c.getOrCreateServer(ctx, tenantName)
 	if err != nil {
 		log.Warningf(ctx, "unable to start server for tenant %q: %v", tenantName, err)
+		// Clear session and tenant cookies after all logouts have completed.
```
Comment (knz) [inline pkg/server/server_controller.go:255]: ok to trash TenantSelectCookieName

however I think we should keep the _remaining_ tenants in MultitenantSessionCookieName.

Comment (dhartunian) [reply pkg/server/server_controller.go:255]: I'm not so sure this is helpful because then I put the UI in a state where there's no `tenant` cookie but a list of sessions. Do we expect the UI to pick one randomly? Should we pick a random tenant to assign the `tenant` cookie to instead?

My take is that a missing tenant tells me that "enough has changed" about the backing DB that we should logout completely.

Comment (knz) [reply pkg/server/server_controller.go:255]: If the multitenancy session has some part that is still valid, the console should still be able to see it. So I'd suggest making the tenant cookie point to that remaining tenant.

Consider the following scenario:

1. Multilogin to tenant A and B
2. Tenant B is dropped
3. ??? I think tenant A should still be available for use in console.

Also, this reminds me that we should also support this use case:

1. Login to tenant A
2. Another tenant B is created
3. Login to tenant B
4. Switch between A and B becomes possible.

I don't believe this is currently possible but i think we can make it happen. But this may be a separate issue. Should i file it?

**Review by knz — APPROVED** [review]
We can also merge this as is and file followup issues for the UX improvement.

**Comment by dhartunian** [comment]
TFTR

bors r=knz
