### PR TITLE
 spanconfig: introduce factory to construct txn scoped SQLTranslators

### LINKED ISSUE #77828: spanconfigstore: duplicate updates in the systemspanconfigstore is crashing the node
Relevant stack:

```
F220315 05:52:59.439757 488912 spanconfig/spanconfigstore/store.go:113  [n1,job=744663189094334465] 1  found duplicate updates {entire-keyspace} and {entire-keyspace}
F220315 05:52:59.439757 488912 spanconfig/spanconfigstore/store.go:113  [n1,job=744663189094334465] 1 !goroutine 488912 [running]:
F220315 05:52:59.439757 488912 spanconfig/spanconfigstore/store.go:113  [n1,job=744663189094334465] 1 !github.com/cockroachdb/cockroach/pkg/util/log.getStacks(0x0)
F220315 05:52:59.439757 488912 spanconfig/spanconfigstore/store.go:113  [n1,job=744663189094334465] 1 !	github.com/cockroachdb/cockroach/pkg/util/log/get_stacks.go:25 +0x9c
F220315 05:52:59.439757 488912 spanconfig/spanconfigstore/store.go:113  [n1,job=744663189094334465] 1 !github.com/cockroachdb/cockroach/pkg/util/log.(*loggerT).outputLogEntry(0xc00d822ab0, {{{0xc008cc4630, 0x24}, {0x6c0adb0, 0x1}, {0x0, 0x0}, {0x0, 0x0}}, 0x16dc78114ea1ba47, ...})
F220315 05:52:59.439757 488912 spanconfig/spanconfigstore/store.go:113  [n1,job=744663189094334465] 1 !	github.com/cockroachdb/cockroach/pkg/util/log/clog.go:237 +0xb7
F220315 05:52:59.439757 488912 spanconfig/spanconfigstore/store.go:113  [n1,job=744663189094334465] 1 !github.com/cockroachdb/cockroach/pkg/util/log.logfDepth({0xa6711c8, 0xc00da7c0f0}, 0x1, 0x4, 0x0, {0x6b7bdb2, 0x2}, {0xc00c095e38, 0x1, 0x1})
F220315 05:52:59.439757 488912 spanconfig/spanconfigstore/store.go:113  [n1,job=744663189094334465] 1 !	github.com/cockroachdb/cockroach/pkg/util/log/channels.go:60 +0x386
F220315 05:52:59.439757 488912 spanconfig/spanconfigstore/store.go:113  [n1,job=744663189094334465] 1 !github.com/cockroachdb/cockroach/pkg/util/log.Fatalf(...)
F220315 05:52:59.439757 488912 spanconfig/spanconfigstore/store.go:113  [n1,job=744663189094334465] 1 !	github.com/cockroachdb/cockroach/bazel-out/k8-dbg/bin/pkg/util/log/log_channels_generated.go:834
F220315 05:52:59.439757 488912 spanconfig/spanconfigstore/store.go:113  [n1,job=744663189094334465] 1 !github.com/cockroachdb/cockroach/pkg/spanconfig/spanconfigstore.(*Store).Apply(0x0, {0xa6711c8, 0xc00da7c0f0}, 0x0, {0xc008317080, 0x3, 0x3})
F220315 05:52:59.439757 488912 spanconfig/spanconfigstore/store.go:113  [n1,job=744663189094334465] 1 !	github.com/cockroachdb/cockroach/pkg/spanconfig/spanconfigstore/store.go:113 +0x148
F220315 05:52:59.439757 488912 spanconfig/spanconfigstore/store.go:113  [n1,job=744663189094334465] 1 !github.com/cockroachdb/cockroach/pkg/spanconfig/spanconfigreconciler.(*incrementalReconciler).reconcile.func1({0xa6711c8, 0xc00da7c0f0}, {0xc00b272320, 0x4, 0x4}, {0xc008421001, 0x75b1c08, 0xc0})
F220315 05:52:59.439757 488912 spanconfig/spanconfigstore/store.go:113  [n1,job=744663189094334465] 1 !	github.com/cockroachdb/cockroach/pkg/spanconfig/spanconfigreconciler/reconciler.go:453 +0xca5
F220315 05:52:59.439757 488912 spanconfig/spanconfigstore/store.go:113  [n1,job=744663189094334465] 1 !github.com/cockroachdb/cockroach/pkg/spanconfig/spanconfigsqlwatcher.(*SQLWatcher).watch(0xc010c963c0, {0xa6711c8, 0xc00da7c0f0}, {0xc0075b1bd8, 0x0, 0x0}, 0xc0075b1bd8)
F220315 05:52:59.439757 488912 spanconfig/spanconfigstore/store.go:113  [n1,job=744663189094334465] 1 !	github.com/cockroachdb/cockroach/pkg/spanconfig/spanconfigsqlwatcher/sqlwatcher.go:174 +0x998
F220315 05:52:59.439757 488912 spanconfig/spanconfigstore/store.go:113  [n1,job=744663189094334465] 1 !github.com/cockroachdb/cockroach/pkg/spanconfig/spanconfigsqlwatcher.(*SQLWatcher).WatchForSQLUpdates(0x18, {0xa6711c8, 0xc00da7c0f0}, {0xc0054f0400, 0x75b1bc0, 0xc0}, 0x0)
F220315 05:52:59.439757 488912 spanconfig/spanconfigstore/store.go:113  [n1,job=744663189094334465] 1 !	github.com/cockroachdb/cockroach/pkg/spanconfig/spanconfigsqlwatcher/sqlwatcher.go:89 +0x72
F220315 05:52:59.439757 488912 spanconfig/spanconfigstore/store.go:113  [n1,job=744663189094334465] 1 !github.com/cockroachdb/cockroach/pkg/spanconfig/spanconfigreconciler.(*incrementalReconciler).reconcile(0xc00b816d80, {0xa6711c8, 0xc00da7c0f0}, {0x8, 0x8, 0x0}, 0xc0075b1bc0)
F220315 05:52:59.439757 488912 spanconfig/spanconfigstore/store.go:113  [n1,job=744663189094334465] 1 !	github.com/cockroachdb/cockroach/pkg/spanconfig/spanconfigreconciler/reconciler.go:386 +0x136
F220315 05:52:59.439757 488912 spanconfig/spanconfigstore/store.go:113  [n1,job=744663189094334465] 1 !github.com/cockroachdb/cockroach/pkg/spanconfig/spanconfigreconciler.(*Reconciler).Reconcile(0xc0062b2090, {0xa6711c8, 0xc00da7c0f0}, {0xc004e12928, 0xf913a78, 0xc0}, 0xc00f416b40)
F220315 05:52:59.439757 488912 spanconfig/spanconfigstore/store.go:113  [n1,job=744663189094334465] 1 !	github.com/cockroachdb/cockroach/pkg/spanconfig/spanconfigreconciler/reconciler.go:173 +0x525
F220315 05:52:59.439757 488912 spanconfig/spanconfigstore/store.go:113  [n1,job=744663189094334465] 1 !github.com/cockroachdb/cockroach/pkg/spanconfig/spanconfigjob.(*resumer).Resume(0xc0004bf1c0, {0xa6711c8, 0xc00da7c0f0}, 
```

First seen - https://github.com/cockroachdb/cockroach/issues/77814

@arulajmani probably going to need your help to figure out whats going on here.

Jira issue: CRDB-13791

### PR DESCRIPTION
**Pull request by arulajmani**
The SQLTranslator is responsible for translating a tenant's SQL zone
config state to the implied KV span config state. It is used by the
Reconciler to issue updates to KV whenever a zone config or PTS record
changes. However, deletions corresponding to PTS-es being released or
tables being deleted aren't handeld by the Translator; instead, the
Reconciler identifies such cases and issues deletion requests to KV.

Previously, the Translator would create its own txn to read from
system.{zones,descriptors,protected_ts_records} when constructing span
config state, and the Reconciler would create and use a separate txns to
identify and generate the deleiton requests described above.

This isn't sound, because we aren't reconciling a snapshot of the SQL
state by using 3 different transactions here. In practice, when
working with "regular" span configurations, it just happened to be the
case that this wasn't a problem because of the way the code was
structured. We would check if we needed to construct a deletion by
trying to read a table descriptor corresponding to an ID before we
translated it, so there was no way for us to construct both a deletion
and an update for the same table in the same batch. Had the order of
operations been reversed, we would be susceptible to a race with a
concurrent table descriptor delete.

This is a real problem for system span configurations however. Think
protection timestamps written on the entire keyspace of a tenant.
Protected timestamp records that apply to the entire keyspace may be
deleted and re-written multiple times, unlike table descriptors which
can never be re-written after they've been deleted as in our previous
illustration. Thus, we may end up generating an update and a delete
for the same system span config target in the same batch. Instead of
trying to figure out which one actually applies, we instead eschew this
entirely by constructing span config state transactionally in the
Reconciler. Instead of using 3 different transactions like we were
before, we now work with a single transaction and use it for:

- Translating SQL state to span config state
- Constructing "regular" span config deletions if a table has been
dropped.
- Constructing system span config deletions

To do so, this patch changes  the SQLTranslator to be single-use and
transaction scoped.  We introduce a new SQLTranslatorFactory to bind
transactions and construct such a SQLTranslator in the Reconciler.
Every time the reconciler is processing a batch of updates from the
Watcher, it now constructs a fresh SQLTranslator.

Fixes #77828

Release justification: bug fixes and low-risk updates to new functionality.
Release note: None

### CODE REVIEW

File: pkg/spanconfig/spanconfigreconciler/reconciler.go [hunk 1]
```diff
@@ -212,8 +214,22 @@ func (f *fullReconciler) reconcile(
...
+
+	if err := sql.DescsTxn(ctx, f.execCfg, func(
+		ctx context.Context, txn *kv.Txn, descsCol *descs.Collection,
+	) error {
+		// We're in a retryable closure, so clear any records from previous
+		// attempts.
+		records = records[:0]
+
+		translator := f.sqlTranslatorFactory.SQLTranslator(txn, descsCol)
+		records, reconciledUpUntil, err = spanconfig.FullTranslate(ctx, translator)
```
Comment (adityamaru) [inline pkg/spanconfig/spanconfigreconciler/reconciler.go:226]: nit: simplify to return err?

File: pkg/spanconfig/spanconfigreconciler/reconciler.go [hunk 2]
```diff
@@ -403,30 +419,44 @@ func (r *incrementalReconciler) reconcile(
...
+					return err
+				}); err != nil {
 				return err
 			}
 
-			updates := make([]spanconfig.Update, 0,
-				len(missingTableIDs)+len(missingProtectedTimestampTargets)+len(entries))
-			for _, entry := range entries {
+			updates := make(
+				[]spanconfig.Update,
```
Comment (adityamaru) [inline pkg/spanconfig/spanconfigreconciler/reconciler.go:455]: nit: formatting looks wonky, should we revert the diff

File: pkg/spanconfig/spanconfig.go [hunk 3]
```diff
@@ -86,6 +87,15 @@ type KVSubscriber interface {
 	Subscribe(func(ctx context.Context, updated roachpb.Span))
 }
 
+// SQLTranslatorFactory constructs new SQLTranslators.
+type SQLTranslatorFactory interface {
+	// SQLTranslator constructs and returns a single-use, transaction-scoped
+	// SQLTranslator. The returned SQLTranslators are not safe for concurrent use.
```
Comment (adityamaru) [inline pkg/spanconfig/spanconfig.go:93]: nit: The returned SQLTranslator is not safe...

**Review by adityamaru — COMMENTED** [review]
Thanks for jumping on this, did a first pass and nothing looks surprising.

File: pkg/spanconfig/spanconfigreconciler/reconciler.go [hunk 4]
```diff
@@ -212,8 +214,18 @@ func (f *fullReconciler) reconcile(
...
 	var records []spanconfig.Record
-	records, reconciledUpUntil, err = spanconfig.FullTranslate(ctx, f.sqlTranslator)
-	if err != nil {
+
+	if err := sql.DescsTxn(ctx, f.execCfg, func(
+		ctx context.Context, txn *kv.Txn, descsCol *descs.Collection,
+	) error {
+		// We're in a retryable closure, so clear any records from previous
+		// attempts.
+		records = records[:0]
```
Comment (irfansharif) [inline pkg/spanconfig/spanconfigreconciler/reconciler.go:223]: This isn't necessary, we're not appending things, we're setting the value.

File: pkg/spanconfig/spanconfigreconciler/reconciler.go [hunk 5]
```diff
@@ -403,30 +415,41 @@ func (r *incrementalReconciler) reconcile(
...
+			var missingProtectedTimestampTargets []spanconfig.SystemTarget
+			var records []spanconfig.Record
+
+			if err := sql.DescsTxn(ctx, r.execCfg,
+				func(ctx context.Context, txn *kv.Txn, descsCol *descs.Collection) error {
+					// We're in a retryable closure, so clear any records state from
+					// previous attempts.
+					missingTableIDs = missingTableIDs[:0]
+					missingProtectedTimestampTargets = missingProtectedTimestampTargets[:0]
+					records = records[:0]
```
Comment (irfansharif) [inline pkg/spanconfig/spanconfigreconciler/reconciler.go:428]: Same here, resetting these vars is not necessary. We're not appending things to them -- there's not loop within the txn.

File: pkg/spanconfig/spanconfigreconciler/reconciler.go [hunk 6]
```diff
@@ -403,30 +415,41 @@ func (r *incrementalReconciler) reconcile(
...
+
+					var err error
+					missingTableIDs, err = r.filterForMissingTableIDs(ctx, txn, descsCol, sqlUpdates)
```
Comment (irfansharif) [inline pkg/spanconfig/spanconfigreconciler/reconciler.go:431]: Either leave a TODO here to return missing table IDs from the translator, or make that change. There's no reason for this to exist on the reconciler anymore -- the translator is also missing-table-aware.

File: pkg/spanconfig/spanconfigreconciler/reconciler.go [hunk 7]
```diff
@@ -403,30 +415,41 @@ func (r *incrementalReconciler) reconcile(
...
+					if err != nil {
+						return err
+					}
 
-			missingProtectedTimestampTargets, err := r.filterForMissingProtectedTimestampSystemTargets(
-				ctx, sqlUpdates)
-			if err != nil {
-				return err
-			}
+					missingProtectedTimestampTargets, err = r.filterForMissingProtectedTimestampSystemTargets(
```
Comment (irfansharif) [inline pkg/spanconfig/spanconfigreconciler/reconciler.go:436]: Ditto re: TODO, the translator could adopt this responsibility easily instead of having the reconciler house this logic. This is easy now that the translator's txn scoped.

File: pkg/spanconfig/spanconfigsqltranslator/sqltranslator.go [hunk 8]
```diff
@@ -32,112 +33,129 @@ import (
...
-		// timestamp subsystem, and the internal limits to limit the size of this
-		// table, there is scope for improvement in the future. One option could be
-		// a rangefeed-backed materialized view of the system table.
-		ptsState, err := s.execCfg.ProtectedTimestampProvider.GetState(ctx, txn)
+) (records []spanconfig.Record, _ hlc.Timestamp, _ error) {
+	if s.used {
+		return nil, hlc.Timestamp{}, errors.AssertionFailedf("SQLTranslator already used")
+	}
+
+	// Mark the Translator as used to disallow subsequent calls to Translate.
```
Comment (irfansharif) [inline pkg/spanconfig/spanconfigsqltranslator/sqltranslator.go:92]: Why make this single use? This variable's also making this unsafe for concurrent use. I can imagine wanting to paginate through a list of IDs at the caller now that it's all txn scoped -- making this single use gets in the way of that. And also makes it unsafe for concurrent only to serve an assertion.

**Review by arulajmani — COMMENTED** [review]
> Dismissed @irfansharif from 3 discussions.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/77873)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner and @irfansharif)

___
*[pkg/spanconfig/spanconfigreconciler/reconciler.go, line 455 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/77873#-MyFKJNHdi6xdFDUZn64-r1-455:-MyIDGIw31_cnfQ2-KJ4:bqcaqp6) ([raw file](https://github.com/cockroachdb/cockroach/blob/b6d6f968b6d621f5fbdbcebb42f2557db40d9904/pkg/spanconfig/spanconfigreconciler/reconciler.go#L455)):*
<details><summary><i>Previously, adityamaru (Aditya Maru) wrote…</i></summary><blockquote>

nit: formatting looks wonky, should we revert the diff
</blockquote></details>

Done, though what was here before looked slightly wonky as well. 
___
*[pkg/spanconfig/spanconfigreconciler/reconciler.go, line 223 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/77873#-MyFKJNHdi6xdFDUZn64-r2-223:-MyIog1S-2TYOP1jq8qP:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/c3e4cd25ee6bbf9e7f72f5ca29a508fc2083fcb1/pkg/spanconfig/spanconfigreconciler/reconciler.go#L223)):*
<details><summary><i>Previously, irfansharif (irfan sharif) wrote…</i></summary><blockquote>

This isn't necessary, we're not appending things, we're setting the value.
</blockquote></details>

Done.
___
*[pkg/spanconfig/spanconfigreconciler/reconciler.go, line 428 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/77873#-MyFKJNHdi6xdFDUZn64-r2-428:-MyIowqw0mlUDoKdl9Wu:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/c3e4cd25ee6bbf9e7f72f5ca29a508fc2083fcb1/pkg/spanconfig/spanconfigreconciler/reconciler.go#L428)):*
<details><summary><i>Previously, irfansharif (irfan sharif) wrote…</i></summary><blockquote>

Same here, resetting these vars is not necessary. We're not appending things to them -- there's not loop within the txn.
</blockquote></details>

Done.
___
*[pkg/spanconfig/spanconfigreconciler/reconciler.go, line 431 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/77873#-MyFKJNHdi6xdFDUZn64-r2-431:-MyIrFGE6H4vcQjDVgiZ:b73hc6s) ([raw file](https://github.com/cockroachdb/cockroach/blob/c3e4cd25ee6bbf9e7f72f5ca29a508fc2083fcb1/pkg/spanconfig/spanconfigreconciler/reconciler.go#L431)):*
<details><summary><i>Previously, irfansharif (irfan sharif) wrote…</i></summary><blockquote>

Either leave a TODO here to return missing table IDs from the translator, or make that change. There's no reason for this to exist on the reconciler anymore -- the translator is also missing-table-aware.
</blockquote></details>

Thinking about this a bit more, I'm personally fine with the way this patch leaves things. The Translator is in the business of generating `spanconfig.Records` and the reconciler is responsible for dealing with `Updates`. Given this, I think it's okay for the `Reconciler` to construct these `Deletion` updates as it does today. 
___
*[pkg/spanconfig/spanconfigreconciler/reconciler.go, line 436 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/77873#-MyFKJNHdi6xdFDUZn64-r2-436:-MyItwjZ5uD42XEGGMF7:b-hp453d) ([raw file](https://github.com/cockroachdb/cockroach/blob/c3e4cd25ee6bbf9e7f72f5ca29a508fc2083fcb1/pkg/spanconfig/spanconfigreconciler/reconciler.go#L436)):*
<details><summary><i>Previously, irfansharif (irfan sharif) wrote…</i></summary><blockquote>

Ditto re: TODO, the translator could adopt this responsibility easily instead of having the reconciler house this logic. This is easy now that the translator's txn scoped.
</blockquote></details>

See above, I'm not too keen on this change. 
___
*[pkg/spanconfig/spanconfigsqltranslator/sqltranslator.go, line 92 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/77873#-MyFKJNHdi6xdFDUZn66-r2-92:-MyIpYGR9Y33c8fiVBVW:b4fj66w) ([raw file](https://github.com/cockroachdb/cockroach/blob/c3e4cd25ee6bbf9e7f72f5ca29a508fc2083fcb1/pkg/spanconfig/spanconfigsqltranslator/sqltranslator.go#L92)):*
<details><summary><i>Previously, irfansharif (irfan sharif) wrote…</i></summary><blockquote>

Why make this single use? This variable's also making this unsafe for concurrent use. I can imagine wanting to paginate through a list of IDs at the caller now that it's all txn scoped -- making this single use gets in the way of that. And also makes it unsafe for concurrent only to serve an assertion.
</blockquote></details>

No reason, was just being defensive about the use. Removed. Btw, I don't follow the motivation around wanting to paginate through a list of IDs at the caller, is there a benefit here that I'm missing?

**Review by irfansharif — APPROVED** [review]
> Reviewed 2 of 11 files at r1, 4 of 10 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/77873)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner and @arulajmani)

___
*[pkg/spanconfig/spanconfigreconciler/reconciler.go, line 431 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/77873#-MyFKJNHdi6xdFDUZn64-r2-431:-MyJ1bWxBKI0-EFOH-QB:b-voj6iq) ([raw file](https://github.com/cockroachdb/cockroach/blob/c3e4cd25ee6bbf9e7f72f5ca29a508fc2083fcb1/pkg/spanconfig/spanconfigreconciler/reconciler.go#L431)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

Thinking about this a bit more, I'm personally fine with the way this patch leaves things. The Translator is in the business of generating `spanconfig.Records` and the reconciler is responsible for dealing with `Updates`. Given this, I think it's okay for the `Reconciler` to construct these `Deletion` updates as it does today. 
</blockquote></details>

I'll still encourage you to leave a TODO, feel free to assign to me. The reconciler would still generate `Deletion` updates, it'll just do it using data the translator provides (missing table IDs), instead of also constructing that data itself. Ditto below.
___
*[pkg/spanconfig/spanconfigsqltranslator/sqltranslator.go, line 92 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/77873#-MyFKJNHdi6xdFDUZn66-r2-92:-MyJ1vWjEiCOh07vuSDz:b-n74kfy) ([raw file](https://github.com/cockroachdb/cockroach/blob/c3e4cd25ee6bbf9e7f72f5ca29a508fc2083fcb1/pkg/spanconfig/spanconfigsqltranslator/sqltranslator.go#L92)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

No reason, was just being defensive about the use. Removed. Btw, I don't follow the motivation around wanting to paginate through a list of IDs at the caller, is there a benefit here that I'm missing? 
</blockquote></details>

Smaller txns, might be useful for perf/memory reasons (think full reconciliation over large # of tables).
___
*[pkg/spanconfig/spanconfigsqltranslator/sqltranslator.go, line 71 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/77873#-MyJ2TWSARZyRkX2N4_G:-MyJ2TWSARZyRkX2N4_H:b-oi9zkn) ([raw file](https://github.com/cockroachdb/cockroach/blob/2bb60862ea55e8a1dbea5b8875bcb452e9f93199/pkg/spanconfig/spanconfigsqltranslator/sqltranslator.go#L71)):*
> ```Go
> // spanconfig.SQLTranslator. The caller must ensure that the collection passed
> // in is associated with the supplied transaction.
> func (f *Factory) SQLTranslator(txn *kv.Txn, descsCol *descs.Collection) spanconfig.SQLTranslator {
> ```

It's uncommon to return an interface. Returning the concrete type is easier cause the caller can decide if they do actually want the concrete type (and incur a package dependency) or avoid the dependency by assigning it to the interface type. See https://github.com/golang/go/wiki/CodeReviewComments#interfaces.

Also, call this method "NewSQLTranslator" or "MakeSQLTranslator" instead? Since it's a factory etc.

**Review by arulajmani — COMMENTED** [review]
TFTRs! 

bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/77873#-:-MyJCoMj8VdkQF3hq8Ab:b-oe2moi)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @arulajmani, and @irfansharif)

___
*[pkg/spanconfig/spanconfigreconciler/reconciler.go, line 431 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/77873#-MyFKJNHdi6xdFDUZn64-r2-431:-MyJB-XT1Mh6CUNKE-Av:b-savlmw) ([raw file](https://github.com/cockroachdb/cockroach/blob/c3e4cd25ee6bbf9e7f72f5ca29a508fc2083fcb1/pkg/spanconfig/spanconfigreconciler/reconciler.go#L431)):*
<details><summary><i>Previously, irfansharif (irfan sharif) wrote…</i></summary><blockquote>

I'll still encourage you to leave a TODO, feel free to assign to me. The reconciler would still generate `Deletion` updates, it'll just do it using data the translator provides (missing table IDs), instead of also constructing that data itself. Ditto below.
</blockquote></details>

Sure, I'll add some words and assign them to you. 
___
*[pkg/spanconfig/spanconfigsqltranslator/sqltranslator.go, line 71 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/77873#-MyJ2TWSARZyRkX2N4_G:-MyJBcD6DOQ3YhAoQMRY:b-7dyiwf) ([raw file](https://github.com/cockroachdb/cockroach/blob/2bb60862ea55e8a1dbea5b8875bcb452e9f93199/pkg/spanconfig/spanconfigsqltranslator/sqltranslator.go#L71)):*
<details><summary><i>Previously, irfansharif (irfan sharif) wrote…</i></summary><blockquote>

It's uncommon to return an interface. Returning the concrete type is easier cause the caller can decide if they do actually want the concrete type (and incur a package dependency) or avoid the dependency by assigning it to the interface type. See https://github.com/golang/go/wiki/CodeReviewComments#interfaces.

Also, call this method "NewSQLTranslator" or "MakeSQLTranslator" instead? Since it's a factory etc.
</blockquote></details>

Switched; I was trying to keep the concrete type private to this package (which is a pattern we follow in a few places btw).
