### PR TITLE
changefeedccl: fix split_column_families changefeeds

### LINKED ISSUE #128973: CREATE CHANGEFEED attempts to create a "{_family_}" topic in downstream sink
**Describe the problem**

Creating a changefeed on a multi-family table with the `split_column_families` attempts to create a topic called "{_family_}" on the broker, despite this not being the name of any column family defined in the table.

**To Reproduce**

* Create a new cluster, single node is enough.  Have a downstream broker such as Kafka/Redpanda with automatic topic creation enabled.

* Run the following SQL:

```
CREATE TABLE t (
    id UUID PRIMARY KEY,
    s STRING,
    FAMILY "a" (id),
    FAMILY "b" (s)); -- two column families, called a and b
```

```
CREATE CHANGEFEED FOR TABLE t INTO '<kafka sink address>' WITH OPTIONS (split_column_families);
```

Without populating the table with any entries, if I go and look at the created topics, I see one that shouldn't be there:

```
NAME                    PARTITIONS  REPLICAS
t._u007b_family_u007d_  1           1
```

This topic does not show up on 23.2.x, but it does show up in 24.1.x and 24.2.x.  However, all versions (including 23.2.x) show this nonsense notice message:

```
NOTICE: changefeed will emit to topic t._u007b_family_u007d_
```

With a broker that doesn't automatically create topics, the changefeed cannot start up and produces the following log message:

```
Changefeed job <job id> encountered transient error: ‹kafka server: Request was for a topic or partition that does not exist on this broker› (attempt 1)
```

**Expected behavior**

It should not attempt to create a `{_family_}` topic, especially as this topic doesn't receive any messages.   This breaks changefeeds that send to a broker that has disabled automatic topic creation as they cannot start up.  Also the above NOTICE message should not be produced.

**Environment:**
 - CockroachDB version: 23.2.x (for the NOTICE message), 24.1.x and 24.2.x for the NOTICE and message creation.

Jira issue: CRDB-41314

Epic CRDB-48876

### PR DESCRIPTION
**Pull request by KeithCh**
This fixes the following when creating changefeeds 
for tables that have multiple columns and with the 
option split_column_families, into sinks that have topics:

When using a Kafka V1 sink, we would always 
attempt to create a nonsense topic even if the
Kafka broker setting has
auto.create.topics.enable=false. This would cause
the changefeed to fail.

Release note(bug fix):
Remove unncessary Kafka topic creation that would
could cause changefeed start up to fail when using 
changefeed.new_kafka_sink_enabled=false.

Fixes: https://github.com/cockroachdb/cockroach/issues/128973
Epic: CRDB-41784

### CODE REVIEW

File: pkg/ccl/changefeedccl/changefeed_test.go [hunk 1]
```diff
@@ -5126,6 +5126,70 @@ func TestChangefeedOutputTopics(t *testing.T) {
...
+					topicPrefixStr = "prefix_"
+					if withTopicName {
+						queryString += fmt.Sprintf("&topic_prefix=%s", topicPrefixStr)
+					} else {
+						queryString = fmt.Sprintf("?topic_prefix=%s", topicPrefixStr)
+					}
+				}
+
+				actual = "(no notice)"
+				f := func() cdctest.TestFeedFactory {
```
Comment (KeithCh) [inline pkg/ccl/changefeedccl/changefeed_test.go:5177]: Context for why I didn't use `cdcTest` 
https://github.com/cockroachdb/cockroach/pull/144859#discussion_r2082319959

File: pkg/ccl/changefeedccl/sink_kafka.go [hunk 2]
```diff
@@ -264,9 +264,8 @@ func (s *kafkaSink) Dial() error {
 		return err
 	}
 
-	if err = client.RefreshMetadata(s.Topics()...); err != nil {
-		// Now that we do not fetch metadata for all topics by default, we try
-		// RefreshMetadata manually to check for any connection error.
+	if err = client.RefreshMetadata(); err != nil {
+		// Try RefreshMetadata manually to check for any connection error.
```
Comment (asg0451) [inline pkg/ccl/changefeedccl/sink_kafka.go:268]: i think we dont fetch all topics on purpose in case we don't have access to some, if the user has set that up

**Review by asg0451 — CHANGES_REQUESTED** [review]

File: pkg/ccl/changefeedccl/sink_kafka.go (hunk 2 above)
Comment (KeithCh) [reply pkg/ccl/changefeedccl/sink_kafka.go]: Changed to a different method that makes an RPC call.

File: pkg/ccl/changefeedccl/changefeed_test.go [hunk 3]
```diff
@@ -6651,15 +6651,15 @@ func TestChangefeedErrors(t *testing.T) {
...
+	badHostErrRE := "(no such host|connection refused|network is unreachable)"
 	if KafkaV2Enabled.Get(&s.ClusterSettings().SV) {
 		badHostErrRE = "(unable to dial|unable to open connection to broker|lookup .* on .*: server misbehaving|connection refused)"
 	}
 
 	// Check unavailable kafka - bad dns.
 	longTimeoutSQLDB.ExpectErrWithTimeout(
 		t, badHostErrRE,
-		`CREATE CHANGEFEED FOR foo INTO 'kafka://nope'`,
+		`CREATE CHANGEFEED FOR foo INTO 'kafka://nope:9999'`,
```
Comment (asg0451) [inline pkg/ccl/changefeedccl/changefeed_test.go:6662]: why is the port necessary?

File: pkg/ccl/changefeedccl/sink_kafka.go [hunk 4]
```diff
@@ -264,10 +267,16 @@ func (s *kafkaSink) Dial() error {
 		return err
 	}
 
-	if err = client.RefreshMetadata(s.Topics()...); err != nil {
-		// Now that we do not fetch metadata for all topics by default, we try
-		// RefreshMetadata manually to check for any connection error.
-		return errors.CombineErrors(err, client.Close())
+	// Make sure the broker can be reached.
+	broker := client.LeastLoadedBroker()
```
Comment (asg0451) [inline pkg/ccl/changefeedccl/sink_kafka.go:271]: i think this will mostly just end up being the seed broker(s), but that's ok

File: pkg/ccl/changefeedccl/sink_kafka.go [hunk 5]
```diff
@@ -264,10 +267,16 @@ func (s *kafkaSink) Dial() error {
...
+	if broker != nil {
```
Comment (asg0451) [inline pkg/ccl/changefeedccl/sink_kafka.go:272]: when can this be nil? if it is nil should we error?

File: pkg/ccl/changefeedccl/sink_kafka.go [hunk 6]
```diff
@@ -264,10 +267,16 @@ func (s *kafkaSink) Dial() error {
...
+		req := &sarama.ApiVersionsRequest{}
```
Comment (asg0451) [inline pkg/ccl/changefeedccl/sink_kafka.go:273]: the arguments for the ApiVersionsRequest are kinda sarama specific and i'd hate to have to replicate them.

instead i think you should do this (pseudocode):

```go
if err := broker.Open(s.kafkaCfg); err != nil && !errors.Is(err, sarama.AlreadyConnected) { .. }
if ok, err := broker.Connected(); !ok || err != nil { ... }
```

see https://pkg.go.dev/github.com/shopify/sarama#Broker.Open

**Review by asg0451 — CHANGES_REQUESTED** [review]

File: pkg/ccl/changefeedccl/changefeed_test.go (hunk 3 above)
Comment (KeithCh) [reply pkg/ccl/changefeedccl/changefeed_test.go:6719]: You would get this error
`pq: dial tcp: address nope: missing port in address`

File: pkg/ccl/changefeedccl/sink_kafka.go (hunk 5 above)
Comment (KeithCh) [reply pkg/ccl/changefeedccl/sink_kafka.go]: It can be nil in the case that we're using a `fakeKafkaClient`, but we don't always want to error since this connection check is not needed in some test cases (see `s.knobs.bypassKafkaV1ConnectionCheck`).

File: pkg/ccl/changefeedccl/topic.go [hunk 7]
```diff
@@ -185,7 +185,7 @@ func (tn *TopicNamer) makeName(s changefeedbase.Target, td TopicDescriptor) (str
 		return tn.nameFromComponents(s.StatementTimeName, s.FamilyName), nil
 	case jobspb.ChangefeedTargetSpecification_EACH_FAMILY:
 		if td == nil {
-			return tn.nameFromComponents(s.StatementTimeName, familyPlaceholder), nil
+			return tn.nameFromComponents(s.StatementTimeName) + string(tn.join) + familyPlaceholder, nil
```
Comment (asg0451) [inline pkg/ccl/changefeedccl/topic.go]: what's the purpose of this change? seems unnecessary and possibly wrong, unless i'm misunderstanding smth

Comment (asg0451) [reply pkg/ccl/changefeedccl/topic.go]: looks good otherwise, just address this guy and i'll green it

Comment (KeithCh) [reply pkg/ccl/changefeedccl/topic.go]: This fixes the  `t.u007b_family_u007d` issue so that it'll show as `t.{family}` instead in the notice.

Comment (asg0451) [reply pkg/ccl/changefeedccl/topic.go]: i see. can you accomplish that in a different way? i don't want this topic name to accidentally make it to kafka again, but this time the name is invalid, causing an error

Comment (KeithCh) [reply pkg/ccl/changefeedccl/topic.go]: I'm going to remove it from this PR since I don't think it'll be that trivial. 

p.s. I strongly dislike `TopicNamer`.

Comment (asg0451) [reply pkg/ccl/changefeedccl/topic.go]: >  I strongly dislike TopicNamer.

me too

**Review by asg0451 — APPROVED** [review]

**Comment by KeithCh** [comment]
bors r=asg0451

**Comment by rharding6373** [comment]
[Team meeting]: Since this is an issue with kafka v1, we don't currently plan on backporting the fix.
