### PR TITLE
roachprod-microbench: cache baseline results

### LINKED ISSUE #128883: build: store microbenchmark results in GCS
The microbenchmarks CI job [1] (script) currently runs microbenchmarks for two revisions of the repository against a `roachprod` cluster each week. The results from these are stored in the artifacts of the job (on TeamCity) and generates Google Sheets from the results that depicts the comparison of each benchmark to be able to bubble regressions up more easily. The job also posts to a Slack channel which is a summary of the sheets and shows the topmost regressions.

There are a couple of enhancements that can be made here that will address a few issue. Currently if the artifacts on the job expire we no longer have the source of truth for a comparison, the sheets are the only information that remain. And when we run a new comparison, if the same baseline revision is used it has to be run again.

By caching (or storing) the results of the microbenchmarks on Google Cloud Storage it will give us the ability to reprocess comparisons if required and re-use results from previous revisions to save on compute costs.

In addition we should select a path on GCS that encodes the conditions under which the microbenchmarks were run. This can include the type of machine and the SHA of the revision. But we should also store metadata along with the run that will be useful for reprocessing or loading the data into a new system.

[1] https://github.com/cockroachdb/cockroach/blob/master/build/teamcity/cockroach/nightlies/microbenchmark_weekly.sh

Jira issue: CRDB-41254

### PR DESCRIPTION
**Pull request by herkolategan**
Previously, we would run microbenchmarks for both sets of binaries (the baseline
and experiment revision). Although this was beneficial to eliminate variance to
some degree, we could rather reuse cached results from the baseline revision and
possibly spend the extra compute on an extra run mid-week.

This change writes the results of the baseline revision to GCS. If the revision
exists in storage it will pull and compare against those results, and only run
the `experiment` revision.

Resolves: #128883

Epic: None
Release note: None

### CODE REVIEW

File: build/teamcity/cockroach/nightlies/microbenchmark_weekly.sh [hunk 1]
```diff
@@ -61,17 +73,21 @@ for rev in "${revisions[@]}"; do
   sha_arr+=("$sha")
 done
 
+# Check if the baseline cache exists and copy it to the output directory.
+baseline_cache_path="gs://$BENCH_BUCKET/cache/$GCE_MACHINE_TYPE/$SANITIZED_BENCH_PACKAGE/${sha_arr[1]}"
+if gsutil ls "$baseline_cache_path" &>/dev/null; then
```
Comment (renatolabs) [inline build/teamcity/cockroach/nightlies/microbenchmark_weekly.sh:80]: I was going to suggest using `check_gcs_path_exists`, but it seems that the support file is not `source`d here. I actually can't seem to find where that file is used. 🤔

File: build/teamcity/cockroach/nightlies/microbenchmark_weekly.sh [hunk 2]
```diff
@@ -61,17 +73,21 @@ for rev in "${revisions[@]}"; do
...
+fi
+
 # Builds binaries for the given SHAs.
-BAZEL_SUPPORT_EXTRA_DOCKER_ARGS="-e GOOGLE_EPHEMERAL_CREDENTIALS -e BENCH_PACKAGE -e BUILDS_BUCKET" \
+BAZEL_SUPPORT_EXTRA_DOCKER_ARGS="-e GOOGLE_EPHEMERAL_CREDENTIALS -e SANITIZED_BENCH_PACKAGE -e BENCH_PACKAGE -e BENCH_BUCKET" \
   run_bazel build/teamcity/cockroach/nightlies/microbenchmark_build_support.sh "${sha_arr[@]}"
 
-# Set up credentials (needs to be done after the build phase)
-google_credentials="$GOOGLE_EPHEMERAL_CREDENTIALS"
+# Log into gcloud again (previous credentials are no longer available at this point)
```
Comment (renatolabs) [inline build/teamcity/cockroach/nightlies/microbenchmark_weekly.sh:91]: What do you mean by no longer available?

File: build/teamcity/cockroach/nightlies/microbenchmark_weekly.sh [hunk 3]
```diff
@@ -104,10 +120,15 @@ done
...
+# Push baseline to cache if we ran both benchmarks
+if [[ ${#sha_arr[@]} -gt 1 ]]; then
+  gsutil -mq cp -r "$output_dir/baseline" "$baseline_cache_path"
+fi
 
-# Compare the results, if both sets of benchmarks were run
-if [ -d "$output_dir/0" ] && [ "$(ls -A "$output_dir/0")" ] \
-&& [ -d "$output_dir/1" ] && [ "$(ls -A "$output_dir/1")" ]; then
+# Compare the results, if both sets of benchmarks were run.
+# These should exists if the benchmarks were run successfully.
```
Comment (renatolabs) [inline build/teamcity/cockroach/nightlies/microbenchmark_weekly.sh:155]: Nit: `exist`.

File: build/teamcity/cockroach/nightlies/microbenchmark_weekly.sh [hunk 4]
```diff
@@ -75,6 +76,7 @@ done
 
 # Check if the baseline cache exists and copy it to the output directory.
 baseline_cache_path="gs://$BENCH_BUCKET/cache/$GCE_MACHINE_TYPE/$SANITIZED_BENCH_PACKAGE/${sha_arr[1]}"
+baseline_commit=${sha_arr[1]}
```
Comment (renatolabs) [inline build/teamcity/cockroach/nightlies/microbenchmark_weekly.sh:79]: It took me a while to understand the `unset` call below -- it's a way to signal that we used cached baseline results. But then we erase the baseline SHA, which we now have to copy over here because we actually need it.

Maybe we can signal that we used cached results using some kind of boolean variable instead of array deletion? Bonus for then keeping the symmetry between `sha_arr` and `name_arr`.

File: build/teamcity/cockroach/nightlies/microbenchmark_weekly.sh [hunk 5]
```diff
@@ -120,6 +122,26 @@ done
...
+echo "" > "$output_dir/baseline/metadata.log"
+for key in "${!metadata[@]}"; do
+  echo "$key": "${metadata[$key]}" >> "$output_dir/baseline/metadata.log"
+done
+
+metadata["experiment-commit"]=${sha_arr[0]}
+metadata["experiment-commit-time"]=$(git show -s --format=%cI "${sha_arr[0]}")
+for key in "${!metadata[@]}"; do
+  echo "$key": "${metadata[$key]}" >> "$output_dir/experiment/metadata.log"
+done
```
Comment (renatolabs) [inline build/teamcity/cockroach/nightlies/microbenchmark_weekly.sh:143]: Is the idea that this metadata would be parsed by `roachprod-microbench` in the future? Might be worth having that tool generate the metadata in a well defined format (e.g., JSON) via a data structure in code, rather than writing it in the bash script.

**Review by renatolabs — APPROVED** [review]
A few suggestions, but LGTM!

File: build/teamcity/cockroach/nightlies/microbenchmark_weekly.sh (hunk 1 above)
Comment (herkolategan) [reply build/teamcity/cockroach/nightlies/microbenchmark_weekly.sh:80]: I can probably move this to support, so that it can be reused, although it's such a small function, but probably makes it more clear what it's doing.

File: build/teamcity/cockroach/nightlies/microbenchmark_weekly.sh (hunk 2 above)
Comment (herkolategan) [reply build/teamcity/cockroach/nightlies/microbenchmark_weekly.sh]: This is a silly workaround, `teamcity-support.sh` has a trap that wipes the credentials file on exit, when the build support script above is executed (it also pulls in teamcity-support.sh to login the gcloud in the container, but wipes the outer file).

File: build/teamcity/cockroach/nightlies/microbenchmark_weekly.sh (hunk 5 above)
Comment (herkolategan) [reply build/teamcity/cockroach/nightlies/microbenchmark_weekly.sh:143]: Yes, it's already part of this PR https://github.com/cockroachdb/cockroach/pull/129074. The format is that of the traditional go benchmark logs, and it's what [benchfmt](https://pkg.go.dev/golang.org/x/perf/storage/benchfmt) will consume to add `residues` (as they call it) to the benchmark results. Hence I didn't feel the need to have a tool generate it, but I can add a comment to mention here that these metadata files just become part of the benchmark logs that the reader will consume.

File: build/teamcity/cockroach/nightlies/microbenchmark_weekly.sh (hunk 3 above)
Comment (herkolategan) [reply build/teamcity/cockroach/nightlies/microbenchmark_weekly.sh:155]: Done.

File: build/teamcity/cockroach/nightlies/microbenchmark_weekly.sh (hunk 4 above)
Comment (herkolategan) [reply build/teamcity/cockroach/nightlies/microbenchmark_weekly.sh]: True, the logic here is a bit befuddled. To remedy this I opted for a separate array that needs to be built and run, vs. an array to reference the SHAs we're comparing. I tried a boolean, but it felt cleaner using another array.

File: build/teamcity/cockroach/nightlies/microbenchmark_weekly.sh (hunk 1 above)
Comment (renatolabs) [reply build/teamcity/cockroach/nightlies/microbenchmark_weekly.sh]: Nah, I get it now, I was grepping for the wrong string.
