### PR TITLE
backup: SHOW BACKUPS in a subquery no longer hangs if parent query fails

### LINKED ISSUE #166581: backup: SHOW BACKUPS hangs as a subquery if consumer closes
When running `SHOW BACKUPS` in a subquery whose parent query runs into an error, the query hangs. This is because we send the results of `SHOW BACKUPS` into a result channel without checking the context:

https://github.com/cockroachdb/cockroach/blob/be174661a8282b35ed3469b2d774ed04fb413136/pkg/backup/show.go#L1498-L1504

If there exists more than one row in the `SHOW BACKUPS` output, this goroutine is stuck on `chan send` and causes the query to hang.

Jira issue: CRDB-62014

### PR DESCRIPTION
**Pull request by kev-cao**
This commit teaches SHOW BACKUPS to listen to the parent context when sending row results. Previously, we wrote directly to the results channel without listening to the context, which meant that if the parent query ran into an error, the SHOW BACKUPS subquery would hang on `chan send`.

Fixes: #166581

Release note: None

### CODE REVIEW

File: pkg/backup/show_test.go [hunk 1]
```diff
@@ -1301,3 +1301,37 @@ func TestShowBackupWithIDs(t *testing.T) {
...
+// hanging. See issue #166581.
+func TestShowBackupsSubqueryClose(t *testing.T) {
+	defer leaktest.AfterTest(t)()
+	defer log.Scope(t).Close(t)
+
+	const numAccounts = 11
+	_, sqlDB, _, cleanupFn := backupRestoreTestSetup(t, singleNode, numAccounts, InitManualReplication)
+	defer cleanupFn()
+
+	sqlDB.Exec(t, `SET use_backups_with_ids = true`)
```
Comment (andrew-r-thomas) [inline pkg/backup/show_test.go:1316]: Should we also have this test validate the legacy path? Since it seems like that could potentially hang too

**Review by andrew-r-thomas — APPROVED** [review]
LGTM! Just one potential tweak to the test that might be good

File: pkg/backup/show_test.go (hunk 1 above)
Comment (kev-cao) [reply pkg/backup/show_test.go:1316]: Ah yeah it does also hang — I'll update the test. Nice catch

Comment (kev-cao) [reply pkg/backup/show_test.go:1316]: Oh looking back at this, it looks like I did add it — the weekend has rotted away my memory.
