### PR TITLE
backup: randomize `TestRestoreEntryCover`

### LINKED ISSUE #167114: backup: TestRestoreEntryCover12 failed
backup.TestRestoreEntryCover12 [failed](https://mesolite.cluster.engflow.com/invocations/default/776f5dca-1057-4b0a-836c-68f853218eb0?testReportRun=1&testReportShard=30&testReportAttempt=1#targets-Ly9wa2cvYmFja3VwOmJhY2t1cF90ZXN0) on master @ [c131cef8e39340439c67c2e685f19679655cf25e](https://github.com/cockroachdb/cockroach/commits/c131cef8e39340439c67c2e685f19679655cf25e):

```
github.com/cockroachdb/cockroach/pkg/rpc.kvAuth.streamDRPCInterceptor.func1({0x70048a0, 0xc0266a5080}, {0x7ff0268?, 0xcae3b80?})
	pkg/rpc/auth.go:227 +0x8d
github.com/cockroachdb/cockroach/pkg/rpc.(*wrappedDRPCServerStream).MsgRecv(0xc0266a5080?, {0x70048a0?, 0xc0266a5080?}, {0x7ff0268?, 0xcae3b80?})
	pkg/rpc/auth_tenant.go:592 +0x38
github.com/cockroachdb/cockroach/pkg/kv/kvpb.(*drpcKVBatch_BatchStreamStream).RecvMsg(0xc020e6a808?, {0x70048a0?, 0xc0266a5080?})
	bazel-out/k8-fastbuild/bin/pkg/kv/kvpb/kvpb_go_proto_/github.com/cockroachdb/cockroach/pkg/kv/kvpb/api_drpc.pb.go:220 +0x33
github.com/cockroachdb/cockroach/pkg/server.(*Node).batchStreamImpl(0xc020e6a808, {0x7f94003a2d38, 0xc014634530})
	pkg/server/node.go:1978 +0x90
github.com/cockroachdb/cockroach/pkg/server.(*kvBatchServer).BatchStream(0xc020e6a808?, {0x80913c0?, 0xc014634530?})
	pkg/server/node.go:2010 +0x3e
github.com/cockroachdb/cockroach/pkg/kv/kvpb.(*DRPCKVBatchDescription).Method.DRPCKVBatchDescription.Method.func2({0x65c4ee0?, 0xc020e6a808}, {0x8080808080808001?, 0xc0176013f8?}, {0x6a5b0e0?, 0xc0058482a0}, {0x20?, 0x6c84660?})
	bazel-out/k8-fastbuild/bin/pkg/kv/kvpb/kvpb_go_proto_/github.com/cockroachdb/cockroach/pkg/kv/kvpb/api_drpc.pb.go:147 +0x134
storj.io/drpc/drpcmux.(*Mux).HandleRPC.func2({0x806d828, 0xc0058482a0})
	external/io_storj_drpc/drpcmux/handle_rpc.go:42 +0x79
github.com/cockroachdb/cockroach/pkg/rpc.NewDRPCServer.StreamServerInterceptor.func7({0x806d6c0, 0xc01540dec0}, {0xc01c8c0a80, 0x26}, 0xc033cad980)
	pkg/util/tracing/drpcinterceptor/drpc_interceptor.go:100 +0x5c3
storj.io/drpc/drpcmux.getChainedStreamHandler.func1.getChainedStreamHandler.1({0x806d6c0, 0xc01540dec0})
	external/io_storj_drpc/drpcmux/interceptor.go:77 +0x8e
github.com/cockroachdb/cockroach/pkg/rpc.NewDRPCServer.func2({0x806d6c0, 0xc01540dec0}, {0xc01c8c0a80?, 0x4b8aa5?}, 0xc031e7d380)
	pkg/rpc/drpc.go:380 +0x5d
storj.io/drpc/drpcmux.getChainedStreamHandler.func1({0x806d6c0?, 0xc01540dec0?})
	external/io_storj_drpc/drpcmux/interceptor.go:77 +0x135
github.com/cockroachdb/cockroach/pkg/rpc.kvAuth.streamDRPCInterceptor({0xc002d5a000, {{0x1}, {0x8092380, 0xc027ea2780}}, 0x1}, {0x806f990, 0xc01740b188}, {0xc01c8c0a80, 0x26}, 0xc031e7d340)
	pkg/rpc/auth.go:241 +0x39b
storj.io/drpc/drpcmux.getChainedStreamHandler.func1.getChainedStreamHandler.1({0x806f990, 0xc01740b188})
	external/io_storj_drpc/drpcmux/interceptor.go:77 +0x8e
github.com/cockroachdb/cockroach/pkg/server.newDRPCServer.NewDRPCStreamServerRequestMetricsInterceptor.func10({0x806f990, 0xc01740b188}, {0xc01c8c0a80, 0x26}, 0xc031e7d300)
	pkg/rpc/metrics.go:606 +0x198
storj.io/drpc/drpcmux.getChainedStreamHandler.func1({0x806f990?, 0xc01740b188?})
	external/io_storj_drpc/drpcmux/interceptor.go:77 +0x135
github.com/cockroachdb/cockroach/pkg/rpc.NewDRPCServer.makeStopperInterceptors.func5.1({0xc01aab9401?, 0x803eb78?})
	pkg/rpc/drpc.go:304 +0x2b
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunTaskWithErr(0xc01ed96900, {0x803eb78, 0xc01740b188}, {0xc01c8c0a80, 0x26}, 0xc017601ab0)
	pkg/util/stop/stopper.go:358 +0x137
github.com/cockroachdb/cockroach/pkg/rpc.NewDRPCServer.makeStopperInterceptors.func5({0x806f990, 0xc01740b188}, {0xc01c8c0a80, 0x26}, 0xc031e7d2c0)
	pkg/rpc/drpc.go:302 +0xc5
storj.io/drpc/drpcmux.NewWithInterceptors.chainStreamInterceptors.func2({0x806f990, 0xc01740b188}, {0xc01c8c0a80, 0x26}, 0x1?)
	external/io_storj_drpc/drpcmux/interceptor.go:63 +0x83
storj.io/drpc/drpcmux.(*Mux).HandleRPC(0xc0241e4918, {0x806f990, 0xc01740b188}, {0xc01c8c0a80, 0x26})
	external/io_storj_drpc/drpcmux/handle_rpc.go:40 +0x452
storj.io/drpc/drpcserver.(*Server).handleRPC(0xc0144bf4a0?, 0xc01740b188, {0xc01c8c0a80?, 0xcae3b80?})
	external/io_storj_drpc/drpcserver/server.go:218 +0x42
storj.io/drpc/drpcserver.(*Server).ServeOne(0xc00335b2c0, {0x803eb40?, 0xc024a9db90?}, {0x802b280?, 0xc017141188?})
	external/io_storj_drpc/drpcserver/server.go:156 +0x4c5
storj.io/drpc/drpcserver.(*Server).Serve.func2({0x803eb40?, 0xc024a9db90?})
	external/io_storj_drpc/drpcserver/server.go:208 +0x57
storj.io/drpc/drpcctx.(*Tracker).track(0xc024a9db90, 0xc036ec7220?)
	external/io_storj_drpc/drpcctx/tracker.go:35 +0x25
created by storj.io/drpc/drpcctx.(*Tracker).Run in goroutine 138597
	external/io_storj_drpc/drpcctx/tracker.go:30 +0x76
```

Parameters:
 - <code>attempt=1</code>
 - <code>run=1</code>
 - <code>shard=30</code>
<details><summary>Help</summary>
<p>

See also: [How To Investigate a Go Test Failure \(internal\)](https://cockroachlabs.atlassian.net/l/c/HgfXfJgM)
</p>
</details>
/cc @cockroachdb/disaster-recovery
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*TestRestoreEntryCover12.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/bazci/githubpost/issues)

</sub>

Jira issue: CRDB-62253

### LINKED ISSUE #167146: backup: TestRestoreEntryCover20 failed
backup.TestRestoreEntryCover20 [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Ci_TestsAwsLinuxArm64_UnitTests/21291489?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Ci_TestsAwsLinuxArm64_UnitTests/21291489?buildTab=artifacts#/) on master @ [d056a08f22afbc2f971f42d72e9d6b87a2f15d55](https://github.com/cockroachdb/cockroach/commits/d056a08f22afbc2f971f42d72e9d6b87a2f15d55):

```
	external/io_storj_drpc/drpcmanager/manager.go:340 +0xb4
storj.io/drpc/drpcmanager.(*Manager).manageStreams(0x4020d674a0)
	external/io_storj_drpc/drpcmanager/manager.go:329 +0x60
created by storj.io/drpc/drpcmanager.NewWithOptions in goroutine 1832604
	external/io_storj_drpc/drpcmanager/manager.go:129 +0x3a4

goroutine 1833788 [select]:
storj.io/drpc/drpcmanager.(*Manager).manageStream(0x401e0ba960, {0x7254a30, 0x40152ab9e0}, 0x4015a66f08)
	external/io_storj_drpc/drpcmanager/manager.go:340 +0xb4
storj.io/drpc/drpcmanager.(*Manager).manageStreams(0x401e0ba960)
	external/io_storj_drpc/drpcmanager/manager.go:329 +0x60
created by storj.io/drpc/drpcmanager.NewWithOptions in goroutine 1830373
	external/io_storj_drpc/drpcmanager/manager.go:129 +0x3a4

goroutine 1833385 [select]:
storj.io/drpc/drpcmanager.(*Manager).manageStream(0x401a1d9a40, {0x7254a30, 0x402b02d6b0}, 0x4013903b88)
	external/io_storj_drpc/drpcmanager/manager.go:340 +0xb4
storj.io/drpc/drpcmanager.(*Manager).manageStreams(0x401a1d9a40)
	external/io_storj_drpc/drpcmanager/manager.go:329 +0x60
created by storj.io/drpc/drpcmanager.NewWithOptions in goroutine 1833446
	external/io_storj_drpc/drpcmanager/manager.go:129 +0x3a4

goroutine 1831724 [select]:
storj.io/drpc/drpcmanager.(*Manager).manageStream(0x4017d7e1e0, {0x7254a30, 0x401fa9cc60}, 0x400e69ca08)
	external/io_storj_drpc/drpcmanager/manager.go:340 +0xb4
storj.io/drpc/drpcmanager.(*Manager).manageStreams(0x4017d7e1e0)
	external/io_storj_drpc/drpcmanager/manager.go:329 +0x60
created by storj.io/drpc/drpcmanager.NewWithOptions in goroutine 1831777
	external/io_storj_drpc/drpcmanager/manager.go:129 +0x3a4

goroutine 1832799 [chan receive]:
storj.io/drpc/drpcpool.(*poolConn[...]).monitorStream(0x72c6860, {0x7293630, 0x402f8e3b88?}, {0x7286d00?, 0x4022d22c40}, 0x401f6ebd60)
	external/io_storj_drpc/drpcpool/conn.go:108 +0x54
created by storj.io/drpc/drpcpool.(*poolConn[...]).NewStream in goroutine 1830373
	external/io_storj_drpc/drpcpool/conn.go:102 +0x1f0

goroutine 1833203 [select]:
storj.io/drpc/drpcmanager.(*Manager).manageStream(0x4026a50f00, {0x7254a30, 0x40024fbe60}, 0x4012642288)
	external/io_storj_drpc/drpcmanager/manager.go:340 +0xb4
storj.io/drpc/drpcmanager.(*Manager).manageStreams(0x4026a50f00)
	external/io_storj_drpc/drpcmanager/manager.go:329 +0x60
created by storj.io/drpc/drpcmanager.NewWithOptions in goroutine 1830373
	external/io_storj_drpc/drpcmanager/manager.go:129 +0x3a4
=== RUN   TestRestoreEntryCover20/numSpans=3,_numFiles=10,_merge=4,_slim=true
    restore_span_covering_test.go:863: 
        	Error Trace:	pkg/backup/restore_span_covering_test.go:863
        	Error:      	Received unexpected error:
        	            	rpc error: code = Canceled desc = context canceled
        	Test:       	TestRestoreEntryCover20/numSpans=3,_numFiles=10,_merge=4,_slim=true
--- FAIL: TestRestoreEntryCover20/numSpans=3,_numFiles=10,_merge=4,_slim=true (2.49s)
```
<details><summary>Help</summary>
<p>

See also: [How To Investigate a Go Test Failure \(internal\)](https://cockroachlabs.atlassian.net/l/c/HgfXfJgM)
</p>
</details>
/cc @cockroachdb/disaster-recovery
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*TestRestoreEntryCover20.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/bazci/githubpost/issues)

</sub>

Jira issue: CRDB-62261

### LINKED ISSUE #167182: backup: TestRestoreEntryCover9 failed
backup.TestRestoreEntryCover9 [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Ci_TestsAwsLinuxArm64_UnitTests/21292433?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Ci_TestsAwsLinuxArm64_UnitTests/21292433?buildTab=artifacts#/) on master @ [06e48102c52233df51077b34e026b9254eb4321b](https://github.com/cockroachdb/cockroach/commits/06e48102c52233df51077b34e026b9254eb4321b):

```
storj.io/drpc/drpcmux.getChainedStreamHandler.func1({0x729c638?, 0x401a342ba0?})
	external/io_storj_drpc/drpcmux/interceptor.go:77 +0xfc
github.com/cockroachdb/cockroach/pkg/rpc.kvAuth.streamDRPCInterceptor({0x4002982000, {{0x1}, {0x72c1360, 0x40183701e0}}, 0x1}, {0x729e9d0, 0x401e90b408}, {0x401af4ab00, 0x33}, 0x401e16f280)
	pkg/rpc/auth.go:241 +0x2c4
storj.io/drpc/drpcmux.getChainedStreamHandler.func1.getChainedStreamHandler.1({0x729e9d0, 0x401e90b408})
	external/io_storj_drpc/drpcmux/interceptor.go:77 +0x80
github.com/cockroachdb/cockroach/pkg/server.newDRPCServer.NewDRPCStreamServerRequestMetricsInterceptor.func10({0x729e9d0, 0x401e90b408}, {0x401af4ab00, 0x33}, 0x401e16f240)
	pkg/rpc/metrics.go:606 +0x108
storj.io/drpc/drpcmux.getChainedStreamHandler.func1({0x729e9d0?, 0x401e90b408?})
	external/io_storj_drpc/drpcmux/interceptor.go:77 +0xfc
github.com/cockroachdb/cockroach/pkg/rpc.NewDRPCServer.makeStopperInterceptors.func5.1({0x0?, 0x726d618?})
	pkg/rpc/drpc.go:304 +0x2c
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunTaskWithErr(0x4023520900, {0x726d618, 0x401e90b408}, {0x401af4ab00, 0x33}, 0x401ebada90)
	pkg/util/stop/stopper.go:358 +0xe4
github.com/cockroachdb/cockroach/pkg/rpc.NewDRPCServer.makeStopperInterceptors.func5({0x729e9d0, 0x401e90b408}, {0x401af4ab00, 0x33}, 0x401e16f200)
	pkg/rpc/drpc.go:302 +0x94
storj.io/drpc/drpcmux.NewWithInterceptors.chainStreamInterceptors.func2({0x729e9d0, 0x401e90b408}, {0x401af4ab00, 0x33}, 0x1?)
	external/io_storj_drpc/drpcmux/interceptor.go:63 +0x80
storj.io/drpc/drpcmux.(*Mux).HandleRPC(0x402580a0c0, {0x729e9d0, 0x401e90b408}, {0x401af4ab00, 0x33})
	external/io_storj_drpc/drpcmux/handle_rpc.go:46 +0x29c
storj.io/drpc/drpcserver.(*Server).handleRPC(0x401d976000?, 0x401e90b408, {0x401af4ab00?, 0xb84b260?})
	external/io_storj_drpc/drpcserver/server.go:218 +0x40
storj.io/drpc/drpcserver.(*Server).ServeOne(0x4005e99a40, {0x726d5e0?, 0x402968a330?}, {0x7259960?, 0x401e8b5888?})
	external/io_storj_drpc/drpcserver/server.go:156 +0x344
storj.io/drpc/drpcserver.(*Server).Serve.func2({0x726d5e0?, 0x402968a330?})
	external/io_storj_drpc/drpcserver/server.go:208 +0x60
storj.io/drpc/drpcctx.(*Tracker).track(0x402968a330, 0xb84b260?)
	external/io_storj_drpc/drpcctx/tracker.go:35 +0x34
created by storj.io/drpc/drpcctx.(*Tracker).Run in goroutine 100532
	external/io_storj_drpc/drpcctx/tracker.go:30 +0x78

goroutine 103648 [select, 14 minutes]:
github.com/cockroachdb/cockroach/pkg/sql.(*runnerCoordinator).init.func1({0x401af55740?, 0x725f450?})
	pkg/sql/distsql_running.go:173 +0x90
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunAsyncTaskEx.func1({0x725f450, 0xb84b260})
	pkg/util/stop/stopper.go:447 +0x7c
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunAsyncTaskEx in goroutine 101578
	pkg/util/stop/stopper.go:445 +0xe0

goroutine 100662 [sync.Cond.Wait]:
sync.runtime_notifyListWait(0x402986fd50, 0x3f91)
	GOROOT/src/runtime/sema.go:606 +0x140
sync.(*Cond).Wait(0x402986fd40)
	GOROOT/src/sync/cond.go:71 +0xa4
github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*raftSchedulerShard).worker(0x401fda7a40, {0x7262250, 0x401698c820}, {0x7291780, 0x400355dc08}, 0x4003a31008)
	pkg/kv/kvserver/scheduler.go:379 +0x34c
github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*raftScheduler).Start.func2({0x7262250, 0x401698c820}, 0x7262250?)
	pkg/kv/kvserver/scheduler.go:314 +0xcc
created by github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*raftScheduler).Start in goroutine 100542
	pkg/kv/kvserver/scheduler.go:329 +0x224
```
<details><summary>Help</summary>
<p>

See also: [How To Investigate a Go Test Failure \(internal\)](https://cockroachlabs.atlassian.net/l/c/HgfXfJgM)
</p>
</details>
/cc @cockroachdb/disaster-recovery
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*TestRestoreEntryCover9.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/bazci/githubpost/issues)

</sub>

Jira issue: CRDB-62279

### PR DESCRIPTION
**Pull request by andrew-r-thomas**
This patch converts a handful of `TestRestoreEntryCover` tests to randomize parameters rather than exhaustively testing many permutations. This resolves recent flakiness due to timeouts.

Fixes: #167182
Fixes: #167114
Fixes: #167146

Release note: None

### CODE REVIEW

File: pkg/backup/restore_span_covering_test.go [hunk 1]
```diff
@@ -718,84 +723,112 @@ func sanityCheckFileIterator(
...
+	// Simulated size in bytes of each SST file (1 B to 1 MiB). This value is
+	// set on each file's EntryCounts.DataSize and drives the size-based span
+	// merging decisions in the covering logic.
+	fileSize := r.Intn(1<<20) + 1
+
+	// Target size in MiB for each restore span entry. Adjacent spans are merged
+	// until their combined file sizes exceed targetSize<<20. A value of 0
+	// disables size-based merging (spans are only merged when file sets are
+	// subsets). The production default is 384 MiB.
+	targetSize := r.Intn(1000)
```
Comment (msbutler) [inline pkg/backup/restore_span_covering_test.go:757]: maybe 20% of time, we chose 0?

**Review by msbutler — APPROVED** [review]
nice job!

**Comment by andrew-r-thomas** [comment]
TFTR!

/trunk merge
