### PR TITLE
roachtest: skip failing liquibase test

### LINKED ISSUE #66524: roachtest: liquibase failed
roachtest.liquibase [failed](https://teamcity.cockroachdb.com/viewLog.html?buildId=3087613&tab=buildLog) with [artifacts](https://teamcity.cockroachdb.com/viewLog.html?buildId=3087613&tab=artifacts#/liquibase) on master @ [ec36bc66f5147a8703719a9c890be12dd0c08945](https://github.com/cockroachdb/cockroach/commits/ec36bc66f5147a8703719a9c890be12dd0c08945):

```
		  | INFO: Custom SQL executed
		  | Jun 16, 2021 7:23:12 AM liquibase.changelog
		  | INFO: ChangeSet liquibase/harness/change/changelogs/sql.xml::sqlTest::kristyl ran successfully in 67ms
		  | Jun 16, 2021 7:23:12 AM liquibase.lockservice
		  | INFO: Successfully released change log lock
		  | Jun 16, 2021 7:23:12 AM java_util_logging_Logger$info$1 call
		  | INFO: Found 2 changeLogs for cockroachdb/20.2 in liquibase/harness/snapshot
		  | Error: COMMAND_PROBLEM: exit status 1
		  | (1) COMMAND_PROBLEM
		  | Wraps: (2) Node 1. Command with error:
		  |   | ``````
		  |   | cd /mnt/data1/liquibase-test-harness/ && mvn test -Dtest=LiquibaseHarnessSuiteTest -DdbName=cockroachdb -DdbVersion=20.2
		  |   | ``````
		  | Wraps: (3) exit status 1
		  | Error types: (1) errors.Cmd (2) *hintdetail.withDetail (3) *exec.ExitError
		  |
		  | stdout:
		  | <... some data truncated by circular buffer; go to artifacts for details ...>
		  | d SQL and DB snapshot(liquibase.harness.change.ChangeObjectTests): No signature of method: liquibase.command.core.SnapshotCommand.execute() is applicable for argument types: () values: [](..)
		  |   apply addNotNullConstraint against cockroachdb 20.2; verify generated SQL and DB snapshot(liquibase.harness.change.ChangeObjectTests): No signature of method: liquibase.command.core.SnapshotCommand.execute() is applicable for argument types: () values: [](..)
		  |   apply addUniqueConstraint against cockroachdb 20.2; verify generated SQL and DB snapshot(liquibase.harness.change.ChangeObjectTests): No signature of method: liquibase.command.core.SnapshotCommand.execute() is applicable for argument types: () values: [](..)
		  |   apply createIndex against cockroachdb 20.2; verify generated SQL and DB snapshot(liquibase.harness.change.ChangeObjectTests): No signature of method: liquibase.command.core.SnapshotCommand.execute() is applicable for argument types: () values: [](..)
		  |   apply createTableDataTypeText against cockroachdb 20.2; verify generated SQL and DB snapshot(liquibase.harness.change.ChangeObjectTests): No signature of method: liquibase.command.core.SnapshotCommand.execute() is applicable for argument types: () values: [](..)
		  |   apply createTableTimestamp against cockroachdb 20.2; verify generated SQL and DB snapshot(liquibase.harness.change.ChangeObjectTests): No signature of method: liquibase.command.core.SnapshotCommand.execute() is applicable for argument types: () values: [](..)
		  |   apply createView against cockroachdb 20.2; verify generated SQL and DB snapshot(liquibase.harness.change.ChangeObjectTests): No signature of method: liquibase.command.core.SnapshotCommand.execute() is applicable for argument types: () values: [](..)
		  |   apply dropColumn against cockroachdb 20.2; verify generated SQL and DB snapshot(liquibase.harness.change.ChangeObjectTests): No signature of method: liquibase.command.core.SnapshotCommand.execute() is applicable for argument types: () values: [](..)
		  |   apply dropDefaultValue against cockroachdb 20.2; verify generated SQL and DB snapshot(liquibase.harness.change.ChangeObjectTests): No signature of method: liquibase.command.core.SnapshotCommand.execute() is applicable for argument types: () values: [](..)
		  |   apply dropNotNullConstraint against cockroachdb 20.2; verify generated SQL and DB snapshot(liquibase.harness.change.ChangeObjectTests): No signature of method: liquibase.command.core.SnapshotCommand.execute() is applicable for argument types: () values: [](..)
		  |   apply sql against cockroachdb 20.2; verify generated SQL and DB snapshot(liquibase.harness.change.ChangeObjectTests): No signature of method: liquibase.command.core.SnapshotCommand.execute() is applicable for argument types: () values: [](..)
		  |
		  | Tests run: 32, Failures: 9, Errors: 14, Skipped: 5
		  |
		  | [[1;34mINFO[m] [1m------------------------------------------------------------------------[m
		  | [[1;34mINFO[m] [1;31mBUILD FAILURE[m
		  | [[1;34mINFO[m] [1m------------------------------------------------------------------------[m
		  | [[1;34mINFO[m] Total time:  43.660 s
		  | [[1;34mINFO[m] Finished at: 2021-06-16T07:23:20Z
		  | [[1;34mINFO[m] [1m------------------------------------------------------------------------[m
		  | [[1;31mERROR[m] Failed to execute goal [32morg.apache.maven.plugins:maven-surefire-plugin:2.12.4:test[m [1m(default-test)[m on project [36mliquibase-test-harness[m: [1;31mThere are test failures.[m
		  | [[1;31mERROR[m] [1;31m[m
		  | [[1;31mERROR[m] [1;31mPlease refer to /mnt/data1/liquibase-test-harness/target/surefire-reports for the individual test results.[m
		  | [[1;31mERROR[m] -> [1m[Help 1][m
		  | [[1;31mERROR[m] 
		  | [[1;31mERROR[m] To see the full stack trace of the errors, re-run Maven with the [1m-e[m switch.
		  | [[1;31mERROR[m] Re-run Maven using the [1m-X[m switch to enable full debug logging.
		  | [[1;31mERROR[m] 
		  | [[1;31mERROR[m] For more information about the errors and possible solutions, please read the following articles:
		  | [[1;31mERROR[m] [1m[Help 1][m http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
		Wraps: (4) exit status 20
		Error types: (1) *withstack.withStack (2) *errutil.withPrefix (3) *main.withCommandDetails (4) *exec.ExitError
```
<details><summary>Reproduce</summary>
<p>
<p>To reproduce, try:

```bash
# From https://go.crdb.dev/p/roachstress, perhaps edited lightly.
caffeinate ./roachstress.sh liquibase
```
</p>
</p>
</details>
/cc @cockroachdb/sql-experience
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*liquibase.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)
</sub>

### PR DESCRIPTION
**Pull request by RichardJCai**
Not sure why this is failing, the SQL being executed in the test passes against Cockroach v20.2+.

Will re-evaluate once liquibase test harness v1.0.3 is released.

Release note: None

Resolves https://github.com/cockroachdb/cockroach/issues/66524

### CODE REVIEW

File: pkg/cmd/roachtest/tests/liquibase.go [hunk 1]
```diff
@@ -99,13 +100,23 @@ func registerLiquibase(r registry.Registry) {
...
-		// The dbVersion is set to 20.2 since that causes all known passing tests
-		// to be run.
-		if err = c.RunE(ctx, node,
+
+		rawResults, err := c.RunWithBuffer(ctx, t.L(), node,
 			`cd /mnt/data1/liquibase-test-harness/ && mvn test -Dtest=LiquibaseHarnessSuiteTest -DdbName=cockroachdb -DdbVersion=20.2`,
-		); err != nil {
-			t.Fatal(err)
+		)
+		rawResultsStr := string(rawResults)
```
Comment (rafiss) [inline pkg/cmd/roachtest/tests/liquibase.go:107]: since this is a java test, i think we can do a better supported parsing approach using blocklists and stuff. like we just call `parseAndSummarizeJavaORMTestsResults` (see hibernate for example).

oh also, this failure is only affecting v21.2-alpha right? so maybe we need a check so if we backport this logic doesn't get applied.

**Review by rafiss — CHANGES_REQUESTED** [review]

File: pkg/cmd/roachtest/tests/liquibase.go (hunk 1 above)
Comment (RichardJCai) [reply pkg/cmd/roachtest/tests/liquibase.go]: I used surefire but not sure if it was necessary to get the right output.

Updated to use `parseAndSummarizeJavaORMTestsResults`

**Review by rafiss — APPROVED** [review]
lgtm after addressing a minor nit -- feel free to merge after

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/67683#-:-Mf0d6QKD_bR7dmQ2d6q:b-1p2aj3)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rafiss and @RichardJCai)

___
*[pkg/cmd/roachtest/tests/liquibase.go, line 116 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/67683#-Mf0d00MAiy7Gogp-IcT:-Mf0d00MAiy7Gogp-IcU:b-ylqxzq) ([raw file](https://github.com/cockroachdb/cockroach/blob/9c3bf1907e6e330227e226f38848bacbee636064/pkg/cmd/roachtest/tests/liquibase.go#L116)):*
> ```Go
> 			"-DdbName=cockroachdb -DdbVersion=20.2 -DoutputDirectory=%s", repoDir)
> 
> 		err = c.RunE(ctx, node, cmd)
> ```

nit: let's log the error, even though the error is expected. see the gorm test for example

**Comment by RichardJCai** [comment]
bors r=rafiss
