### PR TITLE
goschedstats: use runtime.NumRunnableGoroutines

### LINKED ISSUE #141977: pkg/util/goschedstats/goschedstats_test_/goschedstats_test: pkg failed
pkg/util/goschedstats/goschedstats_test_/goschedstats_test.pkg [failed](https://tanzanite.cluster.engflow.com/invocations/default/346fdbe0-4c3f-4bda-b37e-d185b880897c?testReportRun=1&testReportShard=1&testReportAttempt=1#targets-Ly9wa2cvdXRpbC9nb3NjaGVkc3RhdHM6Z29zY2hlZHN0YXRzX3Rlc3Q=) on master @ [8cd9b03b04c3007dc40c3bdf6b10bbb1d15df430](https://github.com/cockroachdb/cockroach/commits/8cd9b03b04c3007dc40c3bdf6b10bbb1d15df430):

```
```

Parameters:
 - <code>attempt=1</code>
 - <code>deadlock=true</code>
 - <code>run=1</code>
 - <code>shard=1</code>
<details><summary>Help</summary>
<p>

See also: [How To Investigate a Go Test Failure \(internal\)](https://cockroachlabs.atlassian.net/l/c/HgfXfJgM)
</p>
</details>
/cc @cockroachdb/test-eng
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*pkg.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/bazci/githubpost/issues)

</sub>

Jira issue: CRDB-48104

### PR DESCRIPTION
**Pull request by RaduBerinde**
Use the implementation we have added to our Go fork and remove all
other implementations.

Fixes: #141977
Release note: None

### CODE REVIEW

File: pkg/util/goschedstats/runnable.go [hunk 1]
```diff
@@ -114,6 +107,10 @@ var callbackInfo struct {
 	st  *cluster.Settings
 }
 
+// RunnableCountCallback is provided the current value of runnable goroutines,
+// GOMAXPROCS, and the current sampling period.
+type RunnableCountCallback func(numRunnable int, numProcs int, samplePeriod time.Duration)
```
Comment (rickystewart) [inline pkg/util/goschedstats/runnable.go:112]: Please add back `runnable_common.go` and put this there. It's not to our benefit to have the same thing defined in two different places, they could diverge unexpectedly.

File: pkg/util/goschedstats/runnable_test.go [hunk 2]
```diff
@@ -35,7 +35,7 @@ func TestNumRunnableGoroutines(t *testing.T) {
 	// running, with the rest waiting.
 	expected := n - runtime.GOMAXPROCS(0) + 1
 	testutils.SucceedsSoon(t, func() error {
-		if n, _ := numRunnableGoroutines(); n < expected {
+		if n, _ := runtime.NumRunnableGoroutines(); n < expected {
```
Comment (rickystewart) [inline pkg/util/goschedstats/runnable_test.go:38]: If you're going to do this then the build tags for the file need to be updated to be the same as `runnable.go` (i.e. `go:build bazel`)

**Review by rickystewart — CHANGES_REQUESTED** [review]

File: pkg/util/goschedstats/runnable_test.go (hunk 2 above)
Comment (rickystewart) [reply pkg/util/goschedstats/runnable_test.go:38]: Otherwise, `go test ./pkg/util/goschedstats` will fail.

File: pkg/util/goschedstats/runnable.go (hunk 1 above)
Comment (rickystewart) [reply pkg/util/goschedstats/runnable.go:112]: Looks like you can just simply un-do your deletion of the file, this was the only thing in there.

Comment (RaduBerinde) [reply pkg/util/goschedstats/runnable.go]: Sure, done.

File: pkg/util/goschedstats/runnable_test.go (hunk 2 above)
Comment (RaduBerinde) [reply pkg/util/goschedstats/runnable_test.go:38]: Good point, done. I'm running `go test` too to make sure.

**Review by RaduBerinde — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/142104)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @rickystewart and @srosenberg)

**Review by rickystewart — APPROVED** [review]
This is great, thank you.

**Comment by RaduBerinde** [comment]
TFTR!

bors r+
