### PR TITLE
kvserver: deflake TestTxnReadWithinUncertaintyIntervalAfterLeaseTransfer

### LINKED ISSUE #151859: kv/kvserver: TestTxnReadWithinUncertaintyIntervalAfterLeaseTransfer failed
kv/kvserver.TestTxnReadWithinUncertaintyIntervalAfterLeaseTransfer [failed](https://mesolite.cluster.engflow.com/invocations/default/de0556e4-289b-4fd8-9593-022231846320?testReportRun=2&testReportShard=43&testReportAttempt=1#targets-Ly9wa2cva3Yva3ZzZXJ2ZXI6a3ZzZXJ2ZXJfdGVzdA==) on release-25.3 @ [69e01687614d9b3f1cebd348e7d683689567c2f3](https://github.com/cockroachdb/cockroach/commits/69e01687614d9b3f1cebd348e7d683689567c2f3):

```
=== RUN   TestTxnReadWithinUncertaintyIntervalAfterLeaseTransfer
    test_log_scope.go:165: test logs captured to: outputs.zip/logTestTxnReadWithinUncertaintyIntervalAfterLeaseTransfer3327300306
    test_log_scope.go:76: use -show-logs to present logs inline
    client_replica_test.go:870: 
        	Error Trace:	pkg/kv/kvserver/client_replica_test.go:870
        	Error:      	Should be true
        	Test:       	TestTxnReadWithinUncertaintyIntervalAfterLeaseTransfer
    client_replica_test.go:873: writeTs=1755146495.661274231,3, txn="test" meta={id=0b89c1ec key="b" iso=Serializable pri=0.00008503 epo=0 ts=1755146495.661274231,1 min=1755146495.661274231,1 seq=0} lock=true stat=PENDING rts=1755146495.661274231,1 gul=1755146496.161274231,1 obs={n2@1755146495.661274231,4}, obsTs=[{NodeID:2 Timestamp:1755146495.661274231,4}]
    panic.go:635: -- test log scope end --
test logs left over in: outputs.zip/logTestTxnReadWithinUncertaintyIntervalAfterLeaseTransfer3327300306
--- FAIL: TestTxnReadWithinUncertaintyIntervalAfterLeaseTransfer (0.65s)
```

Parameters:
 - <code>attempt=1</code>
 - <code>run=2</code>
 - <code>shard=43</code>
<details><summary>Help</summary>
<p>

See also: [How To Investigate a Go Test Failure \(internal\)](https://cockroachlabs.atlassian.net/l/c/HgfXfJgM)
</p>
</details>
/cc @cockroachdb/kv-triage
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*TestTxnReadWithinUncertaintyIntervalAfterLeaseTransfer.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/bazci/githubpost/issues)

</sub>

Jira issue: CRDB-53499

### PR DESCRIPTION
**Pull request by iskettaneh**
The test failed in the past, and it seems that there is a test race condition. This
commit adds more logging and increases the verbosity of the test so hopefully we
understand better what happens next time.

One failure that was captures was that clocks didn't become in sync at the
beginning of the test, probably due to a message between the nodes affecting
the sync. This commit also keeps trying to sync the clocks at the beginning of the
test.

Fixes: #151859

Release note: None

### CODE REVIEW

**Review by pav-kv — APPROVED** [review]
The test name in the PR title seems off.

File: pkg/kv/kvserver/client_replica_test.go [hunk 1]
```diff
@@ -804,42 +806,69 @@ func TestTxnReadWithinUncertaintyIntervalAfterLeaseTransfer(t *testing.T) {
...
-		m.Increment(maxNanos - m.UnixNano())
-	}
+
+	// Synchronize the clocks. We wrap this in a SucceedsSoon to avoid messages
+	// between the nodes to cause them to remain out of sync.
+	testutils.SucceedsSoon(t, func() error {
+		// Find the maximum clock value.
+		var maxNanos int64
+		for _, m := range manuals {
+			if cur := m.UnixNano(); cur > maxNanos {
```
Comment (pav-kv) [inline pkg/kv/kvserver/client_replica_test.go]: nit: while here, use `max` builtin?

File: pkg/kv/kvserver/client_replica_test.go [hunk 2]
```diff
@@ -804,42 +806,69 @@ func TestTxnReadWithinUncertaintyIntervalAfterLeaseTransfer(t *testing.T) {
...
+				maxNanos = cur
+			}
+		}
+		// After doing so, perfectly synchronize them.
+		for _, m := range manuals {
+			m.Increment(maxNanos - m.UnixNano())
+		}
+
+		if tc.Servers[0].Clock().Now().WallTime != tc.Servers[1].Clock().Now().WallTime {
```
Comment (pav-kv) [inline pkg/kv/kvserver/client_replica_test.go]: we have the `clocks` slice which can be reused for brevity

File: pkg/kv/kvserver/client_replica_test.go [hunk 3]
```diff
@@ -804,42 +806,69 @@ func TestTxnReadWithinUncertaintyIntervalAfterLeaseTransfer(t *testing.T) {
...
+			return errors.Errorf("clocks are not synchronized: n1's clock: %+v, n2's clock: %+v",
+				tc.Servers[0].Clock().Now(), tc.Servers[1].Clock().Now())
```
Comment (pav-kv) [inline pkg/kv/kvserver/client_replica_test.go]: need to store the result of `Now()` in vars, both for brevity and because we can print a different value than the one evaluated a moment ago

File: pkg/kv/kvserver/client_replica_test.go [hunk 4]
```diff
@@ -804,42 +806,69 @@ func TestTxnReadWithinUncertaintyIntervalAfterLeaseTransfer(t *testing.T) {
...
+		}
+		return nil
+	})
+
+	t.Logf("all clocks synchronized: n1's clock: %+v, n2's clock: %+v", tc.Servers[0].Clock().Now(), tc.Servers[1].Clock().Now())
```
Comment (pav-kv) [inline pkg/kv/kvserver/client_replica_test.go]: nit: reuse `clocks` var here and below

File: pkg/kv/kvserver/client_replica_test.go [hunk 5]
```diff
@@ -804,42 +806,69 @@ func TestTxnReadWithinUncertaintyIntervalAfterLeaseTransfer(t *testing.T) {
...
 		clocks = append(clocks, tc.Servers[i].Clock())
 	}
-	// After doing so, perfectly synchronize them.
-	for _, m := range manuals {
-		m.Increment(maxNanos - m.UnixNano())
-	}
+
+	// Synchronize the clocks. We wrap this in a SucceedsSoon to avoid messages
+	// between the nodes to cause them to remain out of sync.
+	testutils.SucceedsSoon(t, func() error {
```
Comment (pav-kv) [inline pkg/kv/kvserver/client_replica_test.go:829]: Presumably, the problem before was: while we're incrementing the timestamp, there is another increment racing with it. Since the increment is racy, so is the equality check in line 841. How does an instant equality guarantee that the clocks won't be changed the next moment, and we won't result in differing timestamps again?

Comment (iskettaneh) [reply pkg/kv/kvserver/client_replica_test.go:829]: The [Clock update](https://github.com/cockroachdb/cockroach/blob/ea447b2c2bcb5698efcb72da97ef7b04949a1aa1/pkg/util/hlc/hlc.go#L473-L495) doesn't use increment. It atomically changes the clocks value into the higher received in the message.We first pause the clock, and then measure the reading of the clocks to see which one needs to be ticked to match the other.  
After we finish ticking the lower clock, we then compare the two readings .. if they match, then there should be no way of a message that causes one clock to advance over the other. If the clocks don't match, we repeat the process again.

File: pkg/kv/kvserver/client_replica_test.go (hunk 2 above)
Comment (iskettaneh) [reply pkg/kv/kvserver/client_replica_test.go]: Done.

File: pkg/kv/kvserver/client_replica_test.go (hunk 3 above)
Comment (iskettaneh) [reply pkg/kv/kvserver/client_replica_test.go]: Done.

**Review by iskettaneh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/151923)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @pav-kv)

**Comment by iskettaneh** [comment]
TFTR!

bors r+
