### PR TITLE
backupccl: error message for restoring databases with AOST before GC TTL

### LINKED ISSUE #47105: backupccl: improve error message when restoring AOST before GC TTL
We could improve the error message when restoring before the GC TTL of the backup.

## Reproduction Steps

```
CREATE DATABASE my_db;
CREATE TABLE my_db.my_table (a int);
BACKUP DATABASE my_db TO 'nodelocal://1/my_backup' WITH revision_history;
DROP DATABASE my_db CASCADE;
RESTORE DATABASE my_db FROM 'nodelocal://1/my_backup' AS OF SYSTEM TIME '-100h';
```
Note: GC TTL of the backup was 25h, so any RESTORE attempting to RESTORE before then should be invalid.

The error returned is: `ERROR: unknown database "my_db"`, but it would be better if we returned something along the lines of `ERROR: invalid RESTORE timestamp: supplied backups do not cover requested time`.

### PR DESCRIPTION
**Pull request by annezhu98**
Previously, if a target database was not found for a RESTORE, whether it's due to AOST being before GC TTL or attempting to restore a database that has never existed, the same error message gets printed.

Since the errors do not occur for the same reason, having different error messages would be more informative for users to understand the cause of error.

Resolves: #47105

Release note (bug fix): more accurate error message for restoring AOST before GC TTL

### CODE REVIEW

**Comment by adityamaru** [comment]
Generally LGTM but can we add a test that looks something like the repro steps in the issue. 
Can we also consider adding something similar for table-level backups, I believe if you swap out the database backup/restore in the above reproduction steps we would see a different error when go to restore AOST a table that doesn't exist in our backup.

**Comment by knz** [comment]
nit: before this merges, ensure the commits are squashed and the fixup prefix has been removed.

File: pkg/ccl/backupccl/backupresolver/targets.go [hunk 1]
```diff
@@ -258,11 +259,16 @@ func DescriptorsMatchingTargets(
...
 	alreadyExpandedDBs := make(map[descpb.ID]struct{})
+	invalidRestoreTsErr := errors.Errorf("supplied backups do not cover requested time")
 	// Process all the DATABASE requests.
 	for _, d := range targets.Databases {
 		dbID, ok := resolver.DbsByName[string(d)]
 		if !ok {
-			return ret, errors.Errorf("unknown database %q", d)
+			// given a non-empty aost, it's possible that we're unable to find the database due to aost being set before gc ttl
+			if asOf.IsEmpty() {
+				return ret, errors.Errorf("unknown database %q", d)
```
Comment (adityamaru) [inline pkg/ccl/backupccl/backupresolver/targets.go:269]: nit: can we change this and below to say - "database ... does not exist"

**Comment by adityamaru** [comment]
Yup as Raphael mentioned above, we should amend the commit title to remove the fixup prefix, and squash the two commits into one. I can help you out with this, but should be good to go after that 🎉

File: pkg/ccl/backupccl/backupresolver/targets.go (hunk 1 above)
Comment (annezhu98) [reply pkg/ccl/backupccl/backupresolver/targets.go]: done

File: pkg/ccl/backupccl/backupresolver/targets.go [hunk 2]
```diff
@@ -258,11 +259,16 @@ func DescriptorsMatchingTargets(
 
 	alreadyRequestedDBs := make(map[descpb.ID]struct{})
 	alreadyExpandedDBs := make(map[descpb.ID]struct{})
+	invalidRestoreTsErr := errors.Errorf("supplied backups do not cover requested time")
 	// Process all the DATABASE requests.
 	for _, d := range targets.Databases {
 		dbID, ok := resolver.DbsByName[string(d)]
 		if !ok {
-			return ret, errors.Errorf("unknown database %q", d)
+			// given a non-empty aost, it's possible that we're unable to find the database due to aost being set before gc ttl
```
Comment (adityamaru) [inline pkg/ccl/backupccl/backupresolver/targets.go:267]: nit: I think we can remove this comment, the error message is explanatory

Comment (annezhu98) [reply pkg/ccl/backupccl/backupresolver/targets.go]: done

**Review by adityamaru — APPROVED** [review]

**Comment by annezhu98** [comment]
bors r=adityamaru

**Comment by annezhu98** [comment]
bors r=adityamaru
