### PR TITLE
crosscluster: fix retained time test flake

### LINKED ISSUE #127291: ccl/crosscluster/physical: TestAlterTenantCompleteToLatest failed
ccl/crosscluster/physical.TestAlterTenantCompleteToLatest [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Ci_TestsAwsLinuxArm64_UnitTests/16102107?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Ci_TestsAwsLinuxArm64_UnitTests/16102107?buildTab=artifacts#/) on master @ [89aa5c870293c3fe0db6a5be8ee616e271b508c5](https://github.com/cockroachdb/cockroach/commits/89aa5c870293c3fe0db6a5be8ee616e271b508c5):

```
=== RUN   TestAlterTenantCompleteToLatest
    test_log_scope.go:170: test logs captured to: /artifacts/tmp/_tmp/a52355e0a9a05347a789d171cedfed59/logTestAlterTenantCompleteToLatest915054443
    test_log_scope.go:81: use -show-logs to present logs inline
    testutils.go:290: error scanning '&{<nil> 0x40057e61b0}': sql: Scan error on column index 0, name "retained_time": unsupported Scan, storing driver.Value type <nil> into type *time.Time
    panic.go:626: -- test log scope end --
test logs left over in: /artifacts/tmp/_tmp/a52355e0a9a05347a789d171cedfed59/logTestAlterTenantCompleteToLatest915054443
--- FAIL: TestAlterTenantCompleteToLatest (7.39s)
```
<details><summary>Help</summary>
<p>

See also: [How To Investigate a Go Test Failure \(internal\)](https://cockroachlabs.atlassian.net/l/c/HgfXfJgM)
</p>
</details>
/cc @cockroachdb/disaster-recovery
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*TestAlterTenantCompleteToLatest.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/bazci/githubpost/issues)
</sub>

### PR DESCRIPTION
**Pull request by azhu-crl**
This PR deflakes unit tests that use `Cutover()` in
`replicationtestutils` by catching potential nil
pointer to `retained_time` when a job completes.

Epic: none
Fixes: https://github.com/cockroachdb/cockroach/issues/127291, https://github.com/cockroachdb/cockroach/issues/127233, https://github.com/cockroachdb/cockroach/issues/127732, https://github.com/cockroachdb/cockroach/issues/127731, https://github.com/cockroachdb/cockroach/issues/127406
Release note: none

### CODE REVIEW

File: pkg/ccl/crosscluster/replicationutils/utils.go [hunk 1]
```diff
@@ -323,3 +323,31 @@ func TestingGetPTSFromReplicationJob(
 
 	return ptsRecord.Timestamp
 }
+
+func TestingGetRetainedTimeFromReplicationJob(
+	t *testing.T,
+	ctx context.Context,
+	sqlRunner *sqlutils.SQLRunner,
+	srv serverutils.ApplicationLayerInterface,
+	producerJobID int,
```
Comment (msbutler) [inline pkg/ccl/crosscluster/replicationutils/utils.go:332]: you're trying to grab the pts from the consumer job, right? TestingGetPTSFromReplicationJob grabs the pts on the producer job already.

File: pkg/ccl/crosscluster/replicationtestutils/testutils.go [hunk 2]
```diff
@@ -284,12 +284,10 @@ func (c *TenantStreamingClusters) Cutover(
 	require.LessOrEqual(c.T, protectedTimestamp.GoTime(), cutoverOutput.GoTime())
 
 	// PTS should be less than or equal to retained time as a result of heartbeats.
-	var retainedTime time.Time
-	c.DestSysSQL.QueryRow(c.T,
-		`SELECT retained_time FROM [SHOW TENANT $1 WITH REPLICATION STATUS]`,
-		c.Args.DestTenantName).Scan(&retainedTime)
-
-	require.LessOrEqual(c.T, protectedTimestamp.GoTime(), retainedTime)
+	retainedTime := replicationutils.TestingGetRetainedTimeFromReplicationJob(c.T, ctx, c.SrcSysSQL, c.SrcSysServer, producerJobID)
```
Comment (msbutler) [inline pkg/ccl/crosscluster/replicationtestutils/testutils.go:287]: this scan was flaking because we couldn't cast a nil value to a timestamp right? Instead of building a brand new helper function, could we just handle the error after the query? i.e.:

```
if err := db.QueryRow(blah).Scan(&retainedTime); err != nil {
  if err is nil, skip the pts to retained time check
}
```

Comment (azhu-crl) [reply pkg/ccl/crosscluster/replicationtestutils/testutils.go:287]: I wonder if it's better to query pts on the destination cluster directly since `Scan()` kills the test on error and doesn't return anything?

Comment (stevendanna) [reply pkg/ccl/crosscluster/replicationtestutils/testutils.go]: I don't know if it'll work at this call site, but there is also `pq.NullTime` which you could scan into.

Comment (azhu-crl) [reply pkg/ccl/crosscluster/replicationtestutils/testutils.go]: Awesome I think that's what we need, thanks for the suggestion!

**Review by msbutler — APPROVED** [review]

**Comment by msbutler** [comment]
I removed the backport label becuase i think you'll need to backport this in conjunction with the pr that caused these tests to flake. it would be good to use the `backport` tool to collect the commits into one backport por
