### PR TITLE
sql: introduce new FIFO cache for txnID cache

### LINKED ISSUE #76013: roachperf: kv95 regression around February 1st
`kv95` dropped in excess of 20% around February 1st, e.g. [`kv95/enc=false/nodes=3 `](https://roachperf.crdb.dev/?filter=kv95&view=kv95%2Fenc%3Dfalse%2Fnodes%3D3&tab=gce):

<a href="https://roachperf.crdb.dev/?filter=kv95&view=kv95%2Fenc%3Dfalse%2Fnodes%3D3&tab=gce">Screenshot 2022-02-04 at 09 48 45</a>

### PR DESCRIPTION
**Pull request by Azhng**
Reviewer note: first commit belongs to #76244

---

Previously, txnID cache relied on cache.UnorderedCache for storage and
FIFO eviction behavior. However, due to unintended allocation behavior
within cache.UnorderedCache, this yielded about 20% throughput drop in
kv95 benchmark.

This commit introduces a new FIFO cache, built to remove all allocation
during write operation. This commit removes all performance hit caused
by the previous use of cache.UnorderedCache.

Resolves #76013

Release note: None

### CODE REVIEW

**Review by ajwerner — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/76350)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner and @Azhng)

___
*[pkg/sql/contention/txnidcache/fifo_cache.go, line 68 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/76350#-MvZ4mC74D_JnulxU1uB:-MvZ4mC74D_JnulxU1uC:b-agbfbv) ([raw file](https://github.com/cockroachdb/cockroach/blob/30c10c913bdf3cf9fe6bcf496f93c1c12bbcb7a0/pkg/sql/contention/txnidcache/fifo_cache.go#L68)):*
> ```Go
> 	}
> 
> 	c.mu.eviction.insertBlock(block)
> ```

I worry about cases where you flush due to a timer as opposed to because the blocks are full and then you end up with mostly empty blocks in the cache. Perhaps it'd be better to have `evictionNode` have its own embedded messageBlock (as opposed to *messageBlock) and copy out of the block in `add` and into the current tail, filling up blocks in the FIFO as you go. Then you know you'll only ever have at most one non-full block. Then, `sync.Pool` the `evictionNode`.

**Review by Azhng — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/76350)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner)

___
*[pkg/sql/contention/txnidcache/fifo_cache.go, line 68 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/76350#-MvZ4mC74D_JnulxU1uB:-Mv_nE_71UYQspFmaOe_:b-klnt3e) ([raw file](https://github.com/cockroachdb/cockroach/blob/30c10c913bdf3cf9fe6bcf496f93c1c12bbcb7a0/pkg/sql/contention/txnidcache/fifo_cache.go#L68)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

I worry about cases where you flush due to a timer as opposed to because the blocks are full and then you end up with mostly empty blocks in the cache. Perhaps it'd be better to have `evictionNode` have its own embedded messageBlock (as opposed to *messageBlock) and copy out of the block in `add` and into the current tail, filling up blocks in the FIFO as you go. Then you know you'll only ever have at most one non-full block. Then, `sync.Pool` the `evictionNode`. 
</blockquote></details>

I went down the route of just directly hijacking the blocks and use them in the eviction list. (mostly was because I misunderstood your comment when I first read it). 

Thoughts on this approach?

**Comment by Azhng** [comment]
Compared to the previous approach (that risked having many empty blocks) I think the new overhead here is about 7% in the microbenchmark. I will follow up with the kv95 result once it's ready.

```
azhng@crlMBP-C02F814DMD6TMTA1: ~/go/src/github.com/cockroachdb/cockroach txn-id-faster-cache ⚡
$ benchstat ~/tmp/BenchmarkWriter-typed-cache/bench ~/tmp/BenchmarkWriter-compact-evict-list/bench | grep -v 'blackHole'                                     [17:49:23]
name                                               old time/op    new time/op    delta
Writer/sinkType=real/concurrentWriter=1-24            363ns ± 1%     389ns ± 3%  +7.20%  (p=0.000 n=10+9)
Writer/sinkType=real/concurrentWriter=24-24           366ns ± 2%     393ns ± 3%  +7.39%  (p=0.000 n=10+9)
Writer/sinkType=real/concurrentWriter=48-24           364ns ± 1%     388ns ± 3%  +6.64%  (p=0.000 n=9+9)
Writer/sinkType=real/concurrentWriter=64-24           360ns ± 2%     387ns ± 2%  +7.51%  (p=0.000 n=9+10)
Writer/sinkType=real/concurrentWriter=92-24           358ns ± 5%     388ns ± 3%  +8.27%  (p=0.000 n=10+10)
Writer/sinkType=real/concurrentWriter=128-24          356ns ± 3%     386ns ± 1%  +8.43%  (p=0.000 n=10+10)

name                                               old speed      new speed      delta
Writer/sinkType=real/concurrentWriter=1-24         67.7GB/s ± 1%  63.2GB/s ± 3%  -6.67%  (p=0.000 n=10+9)
Writer/sinkType=real/concurrentWriter=24-24        67.1GB/s ± 2%  62.5GB/s ± 3%  -6.88%  (p=0.000 n=10+9)
Writer/sinkType=real/concurrentWriter=48-24        67.6GB/s ± 1%  63.4GB/s ± 3%  -6.19%  (p=0.000 n=9+9)
Writer/sinkType=real/concurrentWriter=64-24        68.2GB/s ± 2%  63.4GB/s ± 2%  -6.98%  (p=0.000 n=9+10)
Writer/sinkType=real/concurrentWriter=92-24        68.6GB/s ± 5%  63.4GB/s ± 3%  -7.67%  (p=0.000 n=10+10)
Writer/sinkType=real/concurrentWriter=128-24       69.0GB/s ± 3%  63.7GB/s ± 1%  -7.79%  (p=0.000 n=10+10)

name                                               old alloc/op   new alloc/op   delta
Writer/sinkType=real/concurrentWriter=1-24            70.6B ± 2%     68.9B ± 3%  -2.36%  (p=0.009 n=9+9)
Writer/sinkType=real/concurrentWriter=24-24           73.7B ± 6%     69.4B ± 5%  -5.83%  (p=0.001 n=10+10)
Writer/sinkType=real/concurrentWriter=48-24           73.0B ± 4%     67.7B ± 6%  -7.26%  (p=0.000 n=10+10)
Writer/sinkType=real/concurrentWriter=64-24           69.8B ± 5%     69.4B ± 2%    ~     (p=0.975 n=10+8)
Writer/sinkType=real/concurrentWriter=92-24           69.8B ± 3%     70.2B ± 5%    ~     (p=0.576 n=9+10)
Writer/sinkType=real/concurrentWriter=128-24          69.1B ± 6%     70.8B ± 4%  +2.46%  (p=0.034 n=10+10)

name                                               old allocs/op  new allocs/op  delta
Writer/sinkType=real/concurrentWriter=1-24             0.00           0.00         ~     (all equal)
Writer/sinkType=real/concurrentWriter=24-24            0.00           0.00         ~     (all equal)
Writer/sinkType=real/concurrentWriter=48-24            0.00           0.00         ~     (all equal)
Writer/sinkType=real/concurrentWriter=64-24            0.00           0.00         ~     (all equal)
Writer/sinkType=real/concurrentWriter=92-24            0.00           0.00         ~     (all equal)
Writer/sinkType=real/concurrentWriter=128-24           0.00           0.00         ~     (all equal)
```

**Comment by Azhng** [comment]
Updated kv95 benchmark. Hmm seems like it's a bit slower than the previous simple eviction list implementation.

| Branch                   | elapsed       | errors | ops(total)  | ops/sec(cum) | avg(ms) | p50(ms) | p95(ms)  | p99(ms)  | pMax(ms)  |
|--------------------------|---------------|--------|-------------|--------------|---------|---------|----------|----------|-----------|
| baseline                 | 2700.0s       |   0    | 55785736    |  20661.4     | 3.1     |  2.4    |  8.4     |  13.1    |  75.5     |
| cache                    | 2700.0s       |   0    | 49867068    |  18469.3     | 3.5     |  2.5    |  10.0    |  17.8    |  671.1    |
| cache-noop-sink          | 2700.0s       |   0    | 56440227    |  20903.8     | 3.1     |  2.4    |  8.1     |  13.1    |  71.3     |
| cache-regular-evict-list | 2700.0s       |   0    | 60666291    |  22469.0     | 2.8     |  2.2    |  7.6     |  11.0    |  75.5     |
| cache-compact-evict-list | 2700.0s       |   0    | 54782029    |  20289.6     | 3.2     |  2.5    |  8.4     |  12.6    |  109.1    |

**Comment by Azhng** [comment]
Raw files output from both kv95 runs

[kv95.compact-list.txt](https://github.com/cockroachdb/cockroach/files/8045026/kv95.compact-list.txt)
[kv95.normal-list.txt](https://github.com/cockroachdb/cockroach/files/8045027/kv95.typed-cache.txt)

File: pkg/sql/contention/txnidcache/fifo_cache.go [hunk 1]
```diff
@@ -0,0 +1,234 @@
...
+	for i := range block {
+		if !block[i].valid() {
+			break
+		}
+
+		c.mu.data[block[i].TxnID] = block[i].TxnFingerprintID
+		blockSize++
+	}
+
+	if blockHijacked := c.mu.eviction.insertBlock(block, blockSize); !blockHijacked {
```
Comment (ajwerner) [inline pkg/sql/contention/txnidcache/fifo_cache.go:84]: some of this hijacking feels too clever to me. I feel like just embedding the `messageBlock` as a value in eviction list and pooling that will be simpler from a data abstraction perspective layer. You can do it as a single for loop over the block. I don't feel that strongly though.

File: pkg/sql/contention/txnidcache/fifo_cache.go [hunk 2]
```diff
@@ -0,0 +1,234 @@
...
+	mu struct {
+		syncutil.RWMutex
+
+		data map[uuid.UUID]roachpb.TransactionFingerprintID
+
+		eviction evictionList
+	}
+}
+
+type evictionNode struct {
```
Comment (ajwerner) [inline pkg/sql/contention/txnidcache/fifo_cache.go:36]: I think these things need to be pooled. I'd like to see the benchmark allocating on average zero or near zero bytes as opposed to the current ~70. I wouldn't focus so much on the runtime in terms of nanoseconds for this, if you get the allocations to zero, my money is that we won't see big impact on the kv workload.

File: pkg/sql/contention/txnidcache/fifo_cache.go (hunk 1 above)
Comment (Azhng) [reply pkg/sql/contention/txnidcache/fifo_cache.go]: Done. Switched to using `pool` for node allocation.

File: pkg/sql/contention/txnidcache/fifo_cache.go [hunk 3]
```diff
@@ -0,0 +1,198 @@
...
+		if !node.messageBlock[i].valid() {
+			break
+		}
+
+		delete(c.mu.data, node.messageBlock[i].TxnID)
+	}
+}
+
+// insertBlock insert the messageBlock into the eviction list.
+func (e *evictionList) insertBlock(block *messageBlock, blockSize int) {
```
Comment (ajwerner) [inline pkg/sql/contention/txnidcache/fifo_cache.go:139]: I think it might be more elegant if you just passed the block in here as a slice. It's an extra word on the stack, but who cares.

File: pkg/sql/contention/txnidcache/fifo_cache.go [hunk 4]
```diff
@@ -0,0 +1,198 @@
...
+
+		e.head = newNode
+		e.tail = e.head
+		e.tailBlockIdx = blockSize
+
+		return
+	}
+
+	// Handle when the tail block is full.
+	if e.tail.isFull() {
```
Comment (ajwerner) [inline pkg/sql/contention/txnidcache/fifo_cache.go:153]: what if, instead of this method, you put a method on the `evictionNode` which was:

```go
func (e *evictionList) append(msgs []ResolveTxnID) {
    msgs = e.appendToTail(msgs)
    for len(msgs) > 0 {
        e.addNode()
        msgs = e.appendToTail(msgs)
    }
}

func (e *evictionList) addNode() {
    newNode := nodePool.Get().(*evictionNode)
    if e.head == nil {
        e.head = newNode
    } else {
        e.tail.next = newNode
    }
    e.tail = newNode
}

func (e *evictionList) appendToTail(msgs []ResolvedTxnID) (remaining []ResolvedTxnID) {
    if e.head == nil {
        return msgs
    }
    toCopy := messageBlockSize - e.tailBlockIdx
    if toCopy > len(msgs) {
       toCopy = len(msgs)
    }
    copy(e.tail.messageBlock[:], msgs[:toCopy])
    return msgs[toCopy:]
}
```

File: pkg/sql/contention/txnidcache/fifo_cache.go [hunk 5]
```diff
@@ -0,0 +1,198 @@
...
+	return c
+}
+
+// Add insert a messageBlock into the fifoCache.
+//
+// N.B. After Add() returns, the input messageBlock should not be reused. The
+// fifoCache sometimes directly hijack the input messageBlock to form the
+// eviction list and often even directly overwrite its content to minimize
+// memory allocation.
+func (c *fifoCache) Add(block *messageBlock) {
```
Comment (ajwerner) [inline pkg/sql/contention/txnidcache/fifo_cache.go:75]: how come this is exported?

File: pkg/sql/contention/txnidcache/concurrent_write_buffer.go [hunk 6]
```diff
@@ -20,6 +20,10 @@ const messageBlockSize = 1024
 
 type messageBlock [messageBlockSize]ResolvedTxnID
```
Comment (ajwerner) [inline pkg/sql/contention/txnidcache/concurrent_write_buffer.go:21]: If I were to be nit-picky, I like I'd just call this `block`. The fact that things are "messages" sort of muddles things for me. I think I'd go through and eliminate the word `message`/`msg` everywhere. `messageSink` would become `blockSink`, `messageBlockSize`->`blockSize` `msgBlockPool`->`blockPool`. Then for the list, maybe `blockListNode` and `blockList`?

File: pkg/sql/contention/txnidcache/concurrent_write_buffer.go [hunk 7]
```diff
@@ -20,6 +20,10 @@ const messageBlockSize = 1024
```
Comment (ajwerner) [inline pkg/sql/contention/txnidcache/concurrent_write_buffer.go:20]: 1024 feels pretty big to me. How do you feel about maybe 170? If each `ResolvedTxnID` is 24 bytes, that gives you as close as you can get with a 4k page and your nodes would be still under 4k too. I think at 170 you've already amortized a ton.

File: pkg/sql/contention/txnidcache/fifo_cache.go [hunk 8]
```diff
@@ -0,0 +1,198 @@
...
+
+// evictionList is a singly-linked list of messageBlocks. The list is used to
+// implement FIFO eviction.
+type evictionList struct {
+	head *evictionNode
+	tail *evictionNode
+
+	// tailBlockIdx is an index pointing into the next empty slot in messageBlock
+	// stored in the tail pointer.
+	tailBlockIdx int
```
Comment (ajwerner) [inline pkg/sql/contention/txnidcache/fifo_cache.go:55]: `tailBlockIdx` feels like one too many words. `tailIdx`?

File: pkg/sql/contention/txnidcache/fifo_cache_test.go [hunk 9]
```diff
@@ -0,0 +1,231 @@
...
+				"the cache, but it was found", expectedKey)
+		}
+	}
+}
+
+func forkBlock(b *messageBlock) *messageBlock {
+	newBlock := &messageBlock{}
+	copy(newBlock[:], b[:])
+	return newBlock
+}
```
Comment (ajwerner) [inline pkg/sql/contention/txnidcache/fifo_cache_test.go:211]: nit: `cloneBlock`?

**Review by ajwerner — APPROVED** [review]
Just cleanup nits from me. I didn't scrutinize the tests all that closely, but they seemed fine. 

Mod the nits, and the naming one really are up to you, 👍 LGTM

**Review by Azhng — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/76350)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner)

___
*[pkg/sql/contention/txnidcache/concurrent_write_buffer.go, line 20 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/76350#-Mv_mv8EjzDmTEkoMKGK-r6-20:-Mvyd6nq4DlSpwIHtb7R:b-wva74f) ([raw file](https://github.com/cockroachdb/cockroach/blob/04610e9e49b57a38c7e21f044980784409bd0767/pkg/sql/contention/txnidcache/concurrent_write_buffer.go#L20)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

1024 feels pretty big to me. How do you feel about maybe 170? If each `ResolvedTxnID` is 24 bytes, that gives you as close as you can get with a 4k page and your nodes would be still under 4k too. I think at 170 you've already amortized a ton. 
</blockquote></details>

Set it to 168 so that it makes some math a bit easier without doing rounding.
___
*[pkg/sql/contention/txnidcache/concurrent_write_buffer.go, line 21 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/76350#-Mv_mv8EjzDmTEkoMKGK-r6-21:-MvyegJg-6Z8UlS-_xkV:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/04610e9e49b57a38c7e21f044980784409bd0767/pkg/sql/contention/txnidcache/concurrent_write_buffer.go#L21)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

If I were to be nit-picky, I like I'd just call this `block`. The fact that things are "messages" sort of muddles things for me. I think I'd go through and eliminate the word `message`/`msg` everywhere. `messageSink` would become `blockSink`, `messageBlockSize`->`blockSize` `msgBlockPool`->`blockPool`. Then for the list, maybe `blockListNode` and `blockList`? 
</blockquote></details>

Done.
___
*[pkg/sql/contention/txnidcache/fifo_cache.go, line 55 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/76350#-MvW-fOVK1Jx_DoDDIeD-r6-55:-MvyVkIO-Gq-Yk7gpvDk:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/04610e9e49b57a38c7e21f044980784409bd0767/pkg/sql/contention/txnidcache/fifo_cache.go#L55)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

`tailBlockIdx` feels like one too many words. `tailIdx`?
</blockquote></details>

Done.
___
*[pkg/sql/contention/txnidcache/fifo_cache.go, line 75 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/76350#-MvW-fOVK1Jx_DoDDIeD-r6-75:-MvyVyzR65knOj_WdOAn:b5tfkyx) ([raw file](https://github.com/cockroachdb/cockroach/blob/04610e9e49b57a38c7e21f044980784409bd0767/pkg/sql/contention/txnidcache/fifo_cache.go#L75)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

how come this is exported?
</blockquote></details>

Done. Unexported.
___
*[pkg/sql/contention/txnidcache/fifo_cache.go, line 139 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/76350#-MvW-fOVK1Jx_DoDDIeD-r6-139:-MvyYtAdBdBt4uyG527I:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/04610e9e49b57a38c7e21f044980784409bd0767/pkg/sql/contention/txnidcache/fifo_cache.go#L139)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

I think it might be more elegant if you just passed the block in here as a slice. It's an extra word on the stack, but who cares.
</blockquote></details>

Done.
___
*[pkg/sql/contention/txnidcache/fifo_cache.go, line 153 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/76350#-MvW-fOVK1Jx_DoDDIeD-r6-153:-Mvyd4SsBlC7lVtLauvS:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/04610e9e49b57a38c7e21f044980784409bd0767/pkg/sql/contention/txnidcache/fifo_cache.go#L153)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

what if, instead of this method, you put a method on the `evictionNode` which was:

```go
func (e *evictionList) append(msgs []ResolveTxnID) {
    msgs = e.appendToTail(msgs)
    for len(msgs) > 0 {
        e.addNode()
        msgs = e.appendToTail(msgs)
    }
}

func (e *evictionList) addNode() {
    newNode := nodePool.Get().(*evictionNode)
    if e.head == nil {
        e.head = newNode
    } else {
        e.tail.next = newNode
    }
    e.tail = newNode
}

func (e *evictionList) appendToTail(msgs []ResolvedTxnID) (remaining []ResolvedTxnID) {
    if e.head == nil {
        return msgs
    }
    toCopy := messageBlockSize - e.tailBlockIdx
    if toCopy > len(msgs) {
       toCopy = len(msgs)
    }
    copy(e.tail.messageBlock[:], msgs[:toCopy])
    return msgs[toCopy:]
}
```
</blockquote></details>

Done.
___
*[pkg/sql/contention/txnidcache/fifo_cache_test.go, line 211 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/76350#-MvW-fOVK1Jx_DoDDIeE-r6-211:-Mvy_WhL1FV9pNbPjDkz:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/04610e9e49b57a38c7e21f044980784409bd0767/pkg/sql/contention/txnidcache/fifo_cache_test.go#L211)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

nit: `cloneBlock`?
</blockquote></details>

Done.

**Review by ajwerner — APPROVED** [review]
LGTM

**Comment by Azhng** [comment]
TFTR!

bors r+
