### PR TITLE
multiregionccl,testutilsccl: deflake TestAlterTableLocalityRegionalByRowCorrectZoneConfigBeforeBackfill

### LINKED ISSUE #113820: ccl/multiregionccl: TestAlterTableLocalityRegionalByRowCorrectZoneConfigBeforeBackfill failed
ccl/multiregionccl.TestAlterTableLocalityRegionalByRowCorrectZoneConfigBeforeBackfill [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Ci_TestsGcpLinuxX8664BigVm_CclUnitTests/12499373?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Ci_TestsGcpLinuxX8664BigVm_CclUnitTests/12499373?buildTab=artifacts#/) on release-23.2 @ [4b9b072a1dc54be28deffd366bc145a7d749515d](https://github.com/cockroachdb/cockroach/commits/4b9b072a1dc54be28deffd366bc145a7d749515d):

```
=== RUN   TestAlterTableLocalityRegionalByRowCorrectZoneConfigBeforeBackfill
    test_log_scope.go:170: test logs captured to: /artifacts/tmp/_tmp/96442b76c285f60de3ae793a1f7d862e/logTestAlterTableLocalityRegionalByRowCorrectZoneConfigBeforeBackfill937616132
    test_log_scope.go:81: use -show-logs to present logs inline
    regional_by_row_test.go:167: -- test log scope end --
test logs left over in: /artifacts/tmp/_tmp/96442b76c285f60de3ae793a1f7d862e/logTestAlterTableLocalityRegionalByRowCorrectZoneConfigBeforeBackfill937616132
--- FAIL: TestAlterTableLocalityRegionalByRowCorrectZoneConfigBeforeBackfill (37.60s)
=== RUN   TestAlterTableLocalityRegionalByRowCorrectZoneConfigBeforeBackfill/REGIONAL_BY_ROW_to_GLOBAL
    test_server_shim.go:152: automatically injected virtual cluster under test; see comment at top of test_server_shim.go for details.
    alter_primary_key.go:105: pq: setting sql.virtual_cluster.feature_access.multiregion.enabled disallows use of multi-region abstractions
    --- FAIL: TestAlterTableLocalityRegionalByRowCorrectZoneConfigBeforeBackfill/REGIONAL_BY_ROW_to_GLOBAL (7.54s)
```
<details><summary>Help</summary>
<p>

See also: [How To Investigate a Go Test Failure \(internal\)](https://cockroachlabs.atlassian.net/l/c/HgfXfJgM)
</p>
</details>
<details><summary>Same failure on other branches</summary>
<p>

- #113654 ccl/multiregionccl: TestAlterTableLocalityRegionalByRowCorrectZoneConfigBeforeBackfill failed [C-test-failure O-remote-execution O-robot T-sql-foundations branch-master release-blocker]
</p>
</details>
/cc @cockroachdb/sql-foundations
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*TestAlterTableLocalityRegionalByRowCorrectZoneConfigBeforeBackfill.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)
</sub>

Jira issue: CRDB-33179

### LINKED ISSUE #113853: ccl/multiregionccl: TestAlterTableLocalityRegionalByRowCorrectZoneConfigBeforeBackfill fails with shared process
**Describe the problem**

When running `TestAlterTableLocalityRegionalByRowCorrectZoneConfigBeforeBackfill` with a shared process virtual cluster the test fails:
```
=== RUN   TestAlterTableLocalityRegionalByRowCorrectZoneConfigBeforeBackfill
    test_log_scope.go:170: test logs captured to: outputs.zip/logTestAlterTableLocalityRegionalByRowCorrectZoneConfigBeforeBackfill3202632306
    test_log_scope.go:81: use -show-logs to present logs inline
    regional_by_row_test.go:167: -- test log scope end --
test logs left over in: outputs.zip/logTestAlterTableLocalityRegionalByRowCorrectZoneConfigBeforeBackfill3202632306
--- FAIL: TestAlterTableLocalityRegionalByRowCorrectZoneConfigBeforeBackfill (9.45s)
=== RUN   TestAlterTableLocalityRegionalByRowCorrectZoneConfigBeforeBackfill/REGIONAL_BY_TABLE_to_REGIONAL_BY_ROW
    test_server_shim.go:152: automatically injected virtual cluster under test; see comment at top of test_server_shim.go for details.
    alter_primary_key.go:105: pq: setting sql.virtual_cluster.feature_access.multiregion.enabled disallows use of multi-region abstractions
    --- FAIL: TestAlterTableLocalityRegionalByRowCorrectZoneConfigBeforeBackfill/REGIONAL_BY_TABLE_to_REGIONAL_BY_ROW (1.79s)
```

This seems to be caused by mismatching cluster settings or capabilities and likely be addressed by: #113187
By selectively enabling only required cluster settings or capabilities required for this test.

**How to reproduce**

Force the test to use a shared process virtual cluster by one of the various methods available to do this:
Either by setting the `TestServerArgs`
```
DefaultTestTenant: base.SharedTestTenantAlwaysEnabled,
```
or by setting the environment variable `COCKROACH_TEST_TENANT` to `shared`

**Expected behavior**
The test should pass when running with a shared process virtual cluster, unless after investigation the test is expected not to work with one.

Test failure: #113654

Ref: https://github.com/cockroachdb/cockroach/issues/112857
Epic: CRDB-26687

Jira issue: CRDB-33229

### PR DESCRIPTION
**Pull request by rafiss**
This test could fail if run from a secondary tenant. It can be fixed by enabling a cluster setting.

fixes https://github.com/cockroachdb/cockroach/issues/113820
fixes https://github.com/cockroachdb/cockroach/issues/113853

Release note: None

### CODE REVIEW

File: pkg/ccl/testutilsccl/alter_primary_key.go [hunk 1]
```diff
@@ -67,6 +67,11 @@ func AlterPrimaryKeyCorrectZoneConfigTest(
 			}
 
 			runCheck := false
+			sql.SecondaryTenantsMultiRegionAbstractionsEnabled.Override(
```
Comment (chrisseto) [inline pkg/ccl/testutilsccl/alter_primary_key.go:70]: nit: Consider adding a comment about why we're overriding this setting so we don't have to delve into git history to understand why?

**Review by chrisseto — APPROVED** [review]
LGTM!

**Review by herkolategan — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/113826)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rafiss)

___
*[`pkg/ccl/testutilsccl/alter_primary_key.go` line 64 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/113826#-NidgNEK1i4JCuFJJiAQ:-NidgNEK1i4JCuFJJiAR:bccltm) ([raw file](https://github.com/cockroachdb/cockroach/blob/4ddf3c043b930eaeb02455959fc2af1edbde5eaf/pkg/ccl/testutilsccl/alter_primary_key.go#L64)):*
> ```Go
> 		t.Run(tc.Desc, func(t *testing.T) {
> 			var db *gosql.DB
> 			var params base.TestServerArgs
> ```

Rebasing this PR will add this line: https://github.com/cockroachdb/cockroach/blob/master/pkg/ccl/testutilsccl/alter_primary_key.go#L65
As it was skipped as part of this issue: #113853
After rebasing the test looks like it will work with a shared process virtual cluster, as this was the cause of this failure.
So might be good just to remove the lines above that will disable it.

File: pkg/ccl/testutilsccl/alter_primary_key.go (hunk 1 above)
Comment (rafiss) [reply pkg/ccl/testutilsccl/alter_primary_key.go:70]: done

**Comment by rafiss** [comment]
> Rebasing this PR will add this line: [master/pkg/ccl/testutilsccl/alter_primary_key.go#L65](https://github.com/cockroachdb/cockroach/blob/master/pkg/ccl/testutilsccl/alter_primary_key.go?rgh-link-date=2023-11-07T12%3A13%3A32Z#L65)
As it was skipped as part of this issue: https://github.com/cockroachdb/cockroach/issues/113853
After rebasing the test looks like it will work with a shared process virtual cluster, as this was the cause of this failure.
So might be good just to remove the lines above that will disable it.

Thanks for the heads up - I've removed those lines that disabled the test for tenants.

bors r+

**Review by herkolategan — APPROVED** [review]

**Comment by herkolategan** [comment]
Thanks!

bors retry
