### PR TITLE
optbuilder: Fix optbuilder to build correctly typed subqueries

### LINKED ISSUE #27330: opt: optbuilder builds incorrectly typed subquery
Repro:
```
exec-ddl
CREATE TABLE a (k INT PRIMARY KEY, i INT, f FLOAT, s STRING, j JSON)
----
TABLE a
 ├── k int not null
 ├── i int
 ├── f float
 ├── s string
 ├── j jsonb
 └── INDEX primary
      └── k int not null

build
SELECT *
FROM a
WHERE 'bar'=(SELECT max(s) FROM a GROUP BY i ORDER BY i LIMIT 1)
----
```
EXPECTED: Subquery should have `string` type
ACTUAL: Subquery has `int` type

### PR DESCRIPTION
**Pull request by rytaft**
The typing of some subqueries was incorrect because the `ORDER BY`
columns were being projected along with the output columns of the
subquery. This commit adds logic to detect when the `ORDER BY` columns
should not be projected, and wraps the underlying expression in a
`Project` operation to remove the excess columns. This fixes the
issue with incorrect typing.

Fixes #27330

Release note: None

### CODE REVIEW

File: pkg/sql/opt/optbuilder/scope.go [hunk 1]
```diff
@@ -726,6 +736,14 @@ func (s *scope) replaceSubquery(sub *tree.Subquery, multiRow bool, desiredColumn
 		}
 	}
 
+	if outScope.colSet().Len() != outScope.canBeProjectedColSet().Len() {
```
Comment (andy-kimball) [inline pkg/sql/opt/optbuilder/scope.go]: I think `canBeProjectedColSet` is a misleading name, since in the normal case, we do project both `cols` and `orderByCols`. Also, the comment for `orderByCols` says that there can be overlap between it and `cols`, but then the code for `constructProjectForScope` just appends the two lists as if there is no overlap. If there can be no overlap, then this check could be simplified to just be `if len(outScope.orderByCols) != 0`. But if there can be overlap, then other locations need to be fixed. Either way, I'd add tests where there's possible overlap.

Even if you do end up allowing overlap (I'd probably try to prohibit it), then I think it'd be better to create a function like `hasExtraOrderByCols`:
```
func (s *scope) hasExtraOrderByCols() bool {
  if len(s.orderByCols) > 0 {
    cols := s.colSet()
    for _, c := range s.orderByCols {
      if !cols.contains(c) {
        return true
      }
    }
  }
  return false
}
```
This will be much faster in the common case where there are no `orderByCols`, and I think has a better name.

**Review by rytaft — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/27524)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/opt/optbuilder/scope.go, line 739 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/27524#-LHKmWcbmbu7ktPqfMIx-r1-739:-LHYNfr02gWTHkc8Jf2H:bjxgyqi) ([raw file](https://github.com/cockroachdb/cockroach/blob/6d1f1384f3dc7d9bf04342340cf5c9435b638633/pkg/sql/opt/optbuilder/scope.go#L739)):*
<details><summary><i>Previously, andy-kimball (Andy Kimball) wrote…</i></summary><blockquote>

I think `canBeProjectedColSet` is a misleading name, since in the normal case, we do project both `cols` and `orderByCols`. Also, the comment for `orderByCols` says that there can be overlap between it and `cols`, but then the code for `constructProjectForScope` just appends the two lists as if there is no overlap. If there can be no overlap, then this check could be simplified to just be `if len(outScope.orderByCols) != 0`. But if there can be overlap, then other locations need to be fixed. Either way, I'd add tests where there's possible overlap.

Even if you do end up allowing overlap (I'd probably try to prohibit it), then I think it'd be better to create a function like `hasExtraOrderByCols`:
```
func (s *scope) hasExtraOrderByCols() bool {
  if len(s.orderByCols) > 0 {
    cols := s.colSet()
    for _, c := range s.orderByCols {
      if !cols.contains(c) {
        return true
      }
    }
  }
  return false
}
```
This will be much faster in the common case where there are no `orderByCols`, and I think has a better name.
</blockquote></details>

Good idea - I've added the function `hasExtraOrderByCols`.

I considered disallowing overlap between `cols` and `orderByCols`, but it made the logic much more complicated in the previous PR. For example, when copying the ordering from one scope to another (see `scope.copyOrdering()`), we would need to check if there are any columns in `cols` in the old scope that need to be added back to `orderByCols` in the new scope (e.g., if they were projected out). This isn't a simple check since we need to iterate through every column in Ordering and find out if it is already included in `cols` or `orderByCols`, etc.

The code you referred to in `constructProjectForScope` is correct because the duplicates get removed inside `constructProject`. (This removal of duplicates is necessary anyway since there can be duplicates in the SELECT list).

There are already a bunch of tests with some or no overlap between the `SELECT` list and `ORDER BY` cols in the `orderby` test file.

**Review by andy-kimball — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/27524#-:-LHYr6MZ1MBZqQl4sOeo:bnfp4nl)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

**Review by RaduBerinde — APPROVED** [review]
LGTM

> Reviewed 1 of 2 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/27524#-:-LHZ0iMY3-WNeZI12CGN:bb6ywmx)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/sql/opt/optbuilder/scope.go, line 270 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/27524#-LHZ0-Wv0qhUxDzl6cKo:-LHZ0-Wv0qhUxDzl6cKp:b-m0e17i) ([raw file](https://github.com/cockroachdb/cockroach/blob/9e624d35cff0f9307d3372373920e1546db648d7/pkg/sql/opt/optbuilder/scope.go#L270)):*
> ```Go
> // as the other scope.
> func (s *scope) hasSameColumns(other *scope) bool {
> 	return s.colSetWithOrderBy().Equals(other.colSetWithOrderBy())
> ```

This is probably not a concern in practice, but what if one scope has cols=A, B and no orderByCols and the other has cols=A and orderByCols=B

**Comment by rytaft** [comment]
___
*[pkg/sql/opt/optbuilder/scope.go, line 270 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/27524#-LHZ0-Wv0qhUxDzl6cKo:-LHZFIjvDEbSPmIloz-j:b-y8euvi) ([raw file](https://github.com/cockroachdb/cockroach/blob/9e624d35cff0f9307d3372373920e1546db648d7/pkg/sql/opt/optbuilder/scope.go#L270)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

This is probably not a concern in practice, but what if one scope has cols=A, B and no orderByCols and the other has cols=A and orderByCols=B
</blockquote></details>

This function is only called by `constructProjectForScope`, which uses it to determine whether or not to construct a projection. Since the projection includes all the order by columns, this check is sufficient to determine whether or not the projection is necessary.

Do you think I should rename the function to `hasSameColumnsWithOrderBy` or something like that?

**Review by RaduBerinde — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/27524)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/sql/opt/optbuilder/scope.go, line 270 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/27524#-LHZ0-Wv0qhUxDzl6cKo:-LHZMKcz6CgW7Q9-joZX:bjj5fa7) ([raw file](https://github.com/cockroachdb/cockroach/blob/9e624d35cff0f9307d3372373920e1546db648d7/pkg/sql/opt/optbuilder/scope.go#L270)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

This function is only called by `constructProjectForScope`, which uses it to determine whether or not to construct a projection. Since the projection includes all the order by columns, this check is sufficient to determine whether or not the projection is necessary.

Do you think I should rename the function to `hasSameColumnsWithOrderBy` or something like that?
</blockquote></details>

Nah, I'd leave the name as-is. Maybe just mention in the comment.

**Review by rytaft — COMMENTED** [review]
Thanks!

bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/27524#-:-LHZSFHpB8WmdR0eNcxz:b-voiyyw)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/sql/opt/optbuilder/scope.go, line 270 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/27524#-LHZ0-Wv0qhUxDzl6cKo:-LHZS64d8PgXKsiE-LFh:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/9e624d35cff0f9307d3372373920e1546db648d7/pkg/sql/opt/optbuilder/scope.go#L270)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

Nah, I'd leave the name as-is. Maybe just mention in the comment.
</blockquote></details>

Done.
