### PR TITLE
schema: allow transaction retry in schema changer backfill

### LINKED ISSUE #106696: sql: CREATE TABLE AS and REFRESH MATERIALIZED VIEW with some expressions fail in the face of transaction retries
**Describe the problem**

`CREATE TABLE AS` and `REFRESH MATERIALIZED VIEW` built from expressions that are not guaranteed to return the same value on subsequent calls can fail with the following error in the face of transaction retries:

```
        (XXUUU) addsstable [/Table/116/1/-9222809086901354496/0,/Table/116/1/-9222809086901354496/0/NULL): checking for key collisions: ingested key collides with an existing one: /Table/116/1/-9222809086901354496/0
```

The error comes from AddSSTable because despite the fact that we set DisallowShadowingBelow to a value that allows for retries, the values must still match. As explained in a code comment in the bulk row writer, the DisallowedShadowing check is required:

```
			// We disallow shadowing here to ensure that we report errors when builds
			// of unique indexes fail when there are duplicate values. Note that while
			// the timestamp passed does allow shadowing other writes by the same job,
			// the check for allowed shadowing also requires the values match, so a
			// conflicting unique index entry would still be rejected as its value
			// would point to a different owning row.
			DisallowShadowingBelow: writeTS,
````

This was found as part of #106417 and not in the wild. It isn't clear to me that such retries are very likely given that both used a fixed timestamp scan that is likely to be some time in the past.

Jira issue: CRDB-29682

### PR DESCRIPTION
**Pull request by ecwall**
Fixes #106696

This change adds a test to simulate transaction retries during the schema
changer backfill.

Some retries caused `ingested key collides with an existing one` errors
during addSSTable because the schema change's source data changed.
For example: `CREATE TABLE t AS SELECT nextval('seq');` - `nextval` is
non-transactional so each time it is selected, the value changes.

This change also allows the schema changer to specify that addSSTable is
allowed to shadow (replace) keys' values if they are different to handle
this case.

Release note: None

### CODE REVIEW

**Review by fqazi — COMMENTED** [review]
> Reviewed 9 of 9 files at r1, 13 of 13 files at r2, 8 of 8 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/107954)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ecwall, @rytaft, and @stevendanna)

___
*[`pkg/kv/kvclient/kvcoord/testing_knobs.go` line 64 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/107954#-NbUpU_P9o5NDnd_bDXG:-NbUpU_P9o5NDnd_bDXH:b-d1t8gn) ([raw file](https://github.com/cockroachdb/cockroach/blob/3069d1d2360e656656c4fb3ae8f82b32050ba63a/pkg/kv/kvclient/kvcoord/testing_knobs.go#L64)):*
> ```Go
> 	// loops to randomly inject retriable errors.
> 	EnableRandomTransactionRetryErrors bool
> }
> ```

Should this setting be a probability value instead?
___
*[`pkg/kv/kvclient/kvcoord/txn_coord_sender.go` line 43 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/107954#-NbUppnM-nn0qoY-2S9Y:-NbUppnM-nn0qoY-2S9Z:behj9em) ([raw file](https://github.com/cockroachdb/cockroach/blob/3069d1d2360e656656c4fb3ae8f82b32050ba63a/pkg/kv/kvclient/kvcoord/txn_coord_sender.go#L43)):*
> ```Go
> //
> // See: https://github.com/cockroachdb/cockroach/pull/73512.
> var DisableCommitSanityCheck = envutil.EnvOrDefaultBool("COCKROACH_DISABLE_COMMIT_SANITY_CHECK", false)
> ```

Should this be in this commit?
___
*[`pkg/sql/rowexec/bulk_row_writer.go` line 146 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/107954#-NbUqcyyEo8y8LkHTXDi:-NbUqcyyEo8y8LkHTXDj:b2v2mrj) ([raw file](https://github.com/cockroachdb/cockroach/blob/41820281ec982b6aeb4a542ed7dda11255097309/pkg/sql/rowexec/bulk_row_writer.go#L146)):*
> ```Go
> 			Name:          sp.tableDesc.GetName(),
> 			MinBufferSize: bufferSize,
> 			// We disallow shadowing here to ensure that we report errors when builds
> ```

Update the comment here, also I think this will prevent errors from surfacing I think in other cases?

**Review by ecwall — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/107954)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @fqazi and @stevendanna)

___
*[`pkg/kv/kvclient/kvcoord/txn_coord_sender.go` line 43 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/107954#-NbUppnM-nn0qoY-2S9Y:-NbZe3af5Fa9liVoX3rt:b-mz3oav) ([raw file](https://github.com/cockroachdb/cockroach/blob/3069d1d2360e656656c4fb3ae8f82b32050ba63a/pkg/kv/kvclient/kvcoord/txn_coord_sender.go#L43)):*
<details><summary><i>Previously, fqazi (Faizan Qazi) wrote…</i></summary><blockquote>

Should this be in this commit?
</blockquote></details>

This is a change from @stevendanna that has not been merged yet. My change extends some of the functionality.
___
*[`pkg/sql/rowexec/bulk_row_writer.go` line 146 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/107954#-NbUqcyyEo8y8LkHTXDi:-NbZeHR456zw4BCCX6az:bwmaaye) ([raw file](https://github.com/cockroachdb/cockroach/blob/41820281ec982b6aeb4a542ed7dda11255097309/pkg/sql/rowexec/bulk_row_writer.go#L146)):*
<details><summary><i>Previously, fqazi (Faizan Qazi) wrote…</i></summary><blockquote>

Update the comment here, also I think this will prevent errors from surfacing I think in other cases?
</blockquote></details>

After talking with the DR team (https://cockroachlabs.slack.com/archives/C03JCUUSCD6/p1691669801528989), I will have to rethink this part of the PR.

**Review by ecwall — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/107954)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @fqazi and @stevendanna)

___
*[`pkg/kv/kvclient/kvcoord/testing_knobs.go` line 64 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/107954#-NbUpU_P9o5NDnd_bDXG:-NbZebqr25TKr6-Y_8Ee:b-abo6mc) ([raw file](https://github.com/cockroachdb/cockroach/blob/3069d1d2360e656656c4fb3ae8f82b32050ba63a/pkg/kv/kvclient/kvcoord/testing_knobs.go#L64)):*
<details><summary><i>Previously, fqazi (Faizan Qazi) wrote…</i></summary><blockquote>

Should this setting be a probability value instead?
</blockquote></details>

Only some of the filtering is probability based so I left it to the filter impl to do that calculation.

File: pkg/sql/rowexec/bulk_row_writer.go [hunk 1]
```diff
@@ -133,6 +133,21 @@ func (sp *bulkRowWriter) wrapDupError(ctx context.Context, orig error) error {
 
 func (sp *bulkRowWriter) ingestLoop(ctx context.Context, kvCh chan row.KVBatch) error {
 	writeTS := sp.spec.Table.CreateAsOfTime
+
+	// Delete existing span before ingestion to prevent key collisions.
+	if sp.spec.DeleteSpan {
```
Comment (fqazi) [inline pkg/sql/rowexec/bulk_row_writer.go:138]: If this operation is distributed, don't we risk stepping on ourselves? Should this be done at a higher level?

Comment (dt) [reply pkg/sql/rowexec/bulk_row_writer.go:138]: Yeah, I don't think we should be doing this in the processor; I think we should be doing this in the coordinator before we setup the flow, since a) now every proc is deleting the same span, which will all the levels of the LSM with duplicate range keys pushing all writes into L0, and more importantly b) one proc might already be writing by the time another starts up, gets scheduled and runs its deletes, leading to data corruption.

**Review by fqazi — APPROVED** [review]
> Reviewed 18 of 18 files at r9, 13 of 13 files at r10, 1 of 1 files at r11, 1 of 1 files at r12, 8 of 8 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/107954)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dt and @stevendanna)

**Comment by ecwall** [comment]
bors r=fqazi
