### PR TITLE
roachtest: fix typeorm setup

### LINKED ISSUE #110136: roachtest: typeorm failed
roachtest.typeorm [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/11645234?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/11645234?buildTab=artifacts#/typeorm) on master @ [ad4e53f6b4dda9a76c60d4fe52f6f9d7c6afde2a](https://github.com/cockroachdb/cockroach/commits/ad4e53f6b4dda9a76c60d4fe52f6f9d7c6afde2a):

```
(typeorm.go:160).func1: all attempts failed for building TypeORM: full command output in run_195141.721870164_n1_cd-mntdata1typeorm-n.log: COMMAND_PROBLEM: exit status 1
test artifacts and logs in: /artifacts/typeorm/run_1
```
<p>Parameters: <code>ROACHTEST_arch=amd64</code>
, <code>ROACHTEST_cloud=gce</code>
, <code>ROACHTEST_cpu=4</code>
, <code>ROACHTEST_encrypted=false</code>
, <code>ROACHTEST_ssd=0</code>
</p>
<details><summary>Help</summary>
<p>

See: [roachtest README](https://github.com/cockroachdb/cockroach/blob/master/pkg/cmd/roachtest/README.md)

See: [How To Investigate \(internal\)](https://cockroachlabs.atlassian.net/l/c/SSSBr8c7)

See: [Grafana](https://go.crdb.dev/p/roachfana/teamcity-11645234-1693979296-130-n1cpu4/1694027841361/1694029938747)

</p>
</details>
/cc @cockroachdb/sql-foundations
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*typeorm.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)
</sub>

Jira issue: CRDB-31511

### LINKED ISSUE #110203: roachtest: typeorm failed
roachtest.typeorm [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/11663807?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/11663807?buildTab=artifacts#/typeorm) on release-22.2 @ [af6752b2faf39115fd322e9db76421e71b76507d](https://github.com/cockroachdb/cockroach/commits/af6752b2faf39115fd322e9db76421e71b76507d):

```
test artifacts and logs in: /artifacts/typeorm/run_1
(test_runner.go:985).runTest: test timed out (10h0m0s)
```
<p>Parameters: <code>ROACHTEST_arch=amd64</code>
, <code>ROACHTEST_cloud=gce</code>
, <code>ROACHTEST_cpu=4</code>
, <code>ROACHTEST_encrypted=false</code>
, <code>ROACHTEST_ssd=0</code>
</p>
<details><summary>Help</summary>
<p>

See: [roachtest README](https://github.com/cockroachdb/cockroach/blob/master/pkg/cmd/roachtest/README.md)

See: [How To Investigate \(internal\)](https://cockroachlabs.atlassian.net/l/c/SSSBr8c7)

</p>
</details>
<details><summary>Same failure on other branches</summary>
<p>

- #110169 roachtest: typeorm failed [C-test-failure O-roachtest O-robot T-sql-foundations branch-release-23.1.9-rc.FROZEN]
- #110136 roachtest: typeorm failed [C-test-failure O-roachtest O-robot T-sql-foundations branch-master release-blocker]
</p>
</details>
/cc @cockroachdb/sql-foundations
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*typeorm.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)
</sub>

Jira issue: CRDB-31318

### LINKED ISSUE #110233: roachtest: typeorm failed
roachtest.typeorm [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/11663820?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/11663820?buildTab=artifacts#/typeorm) on release-23.1 @ [914e15822b995399c22b12ed7d0bfe1c24503051](https://github.com/cockroachdb/cockroach/commits/914e15822b995399c22b12ed7d0bfe1c24503051):

```
(test_runner.go:1136).runTest: test timed out (10h0m0s)
(typeorm.go:195).func1: COMMAND_PROBLEM: exit status 131
test artifacts and logs in: /artifacts/typeorm/run_1
```
<p>Parameters: <code>ROACHTEST_arch=amd64</code>
, <code>ROACHTEST_cloud=gce</code>
, <code>ROACHTEST_cpu=4</code>
, <code>ROACHTEST_encrypted=false</code>
, <code>ROACHTEST_ssd=0</code>
</p>
<details><summary>Help</summary>
<p>

See: [roachtest README](https://github.com/cockroachdb/cockroach/blob/master/pkg/cmd/roachtest/README.md)

See: [How To Investigate \(internal\)](https://cockroachlabs.atlassian.net/l/c/SSSBr8c7)

See: [Grafana](https://go.crdb.dev/p/roachfana/teamcity-11663820-1694065556-17-n1cpu4/1694103703520/1694139770324)

</p>
</details>
<details><summary>Same failure on other branches</summary>
<p>

- #110230 roachtest: typeorm failed [C-test-failure O-roachtest O-robot T-sql-foundations branch-release-23.1.10-rc release-blocker]
- #110203 roachtest: typeorm failed [C-test-failure O-roachtest O-robot T-sql-foundations branch-release-22.2 release-blocker]
- #110169 roachtest: typeorm failed [C-test-failure O-roachtest O-robot T-sql-foundations branch-release-23.1.9-rc.FROZEN]
- #110136 roachtest: typeorm failed [C-test-failure O-roachtest O-robot T-sql-foundations branch-master release-blocker]
</p>
</details>
/cc @cockroachdb/sql-foundations
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*typeorm.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)
</sub>

Jira issue: CRDB-31335

### PR DESCRIPTION
**Pull request by rafiss**
Use an upstream PR that fixes the test setup. Once the project releases it, this test can be updated to use the official release.

fixes https://github.com/cockroachdb/cockroach/issues/110136
fixes https://github.com/cockroachdb/cockroach/issues/110233
fixes https://github.com/cockroachdb/cockroach/issues/110203

Release note: None

### CODE REVIEW

File: pkg/cmd/roachtest/tests/typeorm.go [hunk 1]
```diff
@@ -25,7 +25,10 @@ import (
 )
 
 var typeORMReleaseTagRegex = regexp.MustCompile(`^(?P<major>\d+)\.(?P<minor>\d+)\.(?P<point>\d+)$`)
-var supportedTypeORMRelease = "0.3.17"
+
+// Use 0.3.18 from the upstream repo once it is released.
```
Comment (andyyang890) [inline pkg/cmd/roachtest/tests/typeorm.go:29]: Should we file an issue for this and leave a TODO comment here?

**Review by andyyang890 — APPROVED** [review]

File: pkg/cmd/roachtest/tests/typeorm.go (hunk 1 above)
Comment (rafiss) [reply pkg/cmd/roachtest/tests/typeorm.go:29]: IMO there's not actually any urgency in updating to the stable release. Whenever we get around to updating the ORMs we test, we can handle this one too. (I feel like it's similar to why we don't make tracking issues for updating each ORM under test until we see a need to)

**Comment by rafiss** [comment]
tftr!

bors r+
