### PR TITLE
roachtest: add missing backslash in nightly script

### LINKED ISSUE #123346: roachtest: generate-fixtures failed
roachtest.generate-fixtures [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/15057518?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/15057518?buildTab=artifacts#/generate-fixtures) on master @ [af3173a899e16af30d2ca9489d8c2c926c410121](https://github.com/cockroachdb/cockroach/commits/af3173a899e16af30d2ca9489d8c2c926c410121):

```
(fixtures.go:60).func1: FIXTURE_VERSION must be set
test artifacts and logs in: artifacts/generate-fixtures/run_1
```

Parameters:
 - <code>ROACHTEST_arch=amd64</code>
 - <code>ROACHTEST_cloud=gce</code>
 - <code>ROACHTEST_coverageBuild=false</code>
 - <code>ROACHTEST_cpu=4</code>
 - <code>ROACHTEST_encrypted=false</code>
 - <code>ROACHTEST_metamorphicBuild=false</code>
 - <code>ROACHTEST_ssd=0</code>
<details><summary>Help</summary>
<p>

See: [roachtest README](https://github.com/cockroachdb/cockroach/blob/master/pkg/cmd/roachtest/README.md)

See: [How To Investigate \(internal\)](https://cockroachlabs.atlassian.net/l/c/SSSBr8c7)

See: [Grafana](https://go.crdb.dev/roachtest-grafana/teamcity-1714542508/generate-fixtures/1714543347865/1714543477566)

</p>
</details>
/cc @cockroachdb/dev-inf
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*generate-fixtures.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/bazci/githubpost/issues)
</sub>

Jira issue: CRDB-38308

### LINKED ISSUE #123348: roachtest: roachtest/hang failed
roachtest.roachtest/hang [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyAwsBazel/15057519?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyAwsBazel/15057519?buildTab=artifacts#/roachtest/hang) on master @ [af3173a899e16af30d2ca9489d8c2c926c410121](https://github.com/cockroachdb/cockroach/commits/af3173a899e16af30d2ca9489d8c2c926c410121):

```
(test_runner.go:1224).runTest: test timed out (3m0s)
test artifacts and logs in: artifacts/roachtest/hang/cpu_arch=arm64/run_1
```

Parameters:
 - <code>ROACHTEST_arch=arm64</code>
 - <code>ROACHTEST_cloud=aws</code>
 - <code>ROACHTEST_coverageBuild=false</code>
 - <code>ROACHTEST_cpu=4</code>
 - <code>ROACHTEST_encrypted=false</code>
 - <code>ROACHTEST_metamorphicBuild=false</code>
 - <code>ROACHTEST_ssd=0</code>
<details><summary>Help</summary>
<p>

See: [roachtest README](https://github.com/cockroachdb/cockroach/blob/master/pkg/cmd/roachtest/README.md)

See: [How To Investigate \(internal\)](https://cockroachlabs.atlassian.net/l/c/SSSBr8c7)

_Grafana is not yet available for aws clusters_</p>
</details>
/cc @cockroachdb/test-eng
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*roachtest/hang.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/bazci/githubpost/issues)
</sub>

Jira issue: CRDB-38310

### PR DESCRIPTION
**Pull request by DarrylWong**
This causes all subsequent flags to be dropped.

Fixes: #123348
Release note: none
Epic: none

### CODE REVIEW

**Review by srosenberg — APPROVED** [review]

File: build/teamcity/cockroach/nightlies/roachtest_nightly_impl.sh [hunk 1]
```diff
@@ -62,7 +62,7 @@ build/teamcity-roachtest-invoke.sh \
   --select-probability="${select_probability}" \
   --cloud="${CLOUD}" \
   --count="${COUNT-1}" \
-  --clear-cluster-cache="${CLEAR_CLUSTER_CACHE:-true}"
+  --clear-cluster-cache="${CLEAR_CLUSTER_CACHE:-true}" \
```
Comment (srosenberg) [inline build/teamcity/cockroach/nightlies/roachtest_nightly_impl.sh:65]: Great example of why shell programming is not for the faint-hearted. :)

**Review by srosenberg — APPROVED** [review]

**Review by renatolabs — APPROVED** [review]

**Comment by DarrylWong** [comment]
TFTRs!

bors r=srosenberg, renatolabs
