### PR TITLE
changefeedccl: enable a couple of tests with test tenant

### LINKED ISSUE #98816: changefeedccl: fix broken tests for tenants
If tests in a pkg do not enable enterprise explicitly, test servers will not attempt to create a test tenant server. We want to tests to sometimes run on a tenant server so that we have test coverage for tenants. Some packages in `pkg/ccl/changefeedccl` do not enable enterprise explicitly.

Not enabling enterprise (ie. enabling tenant testing) causes at least one test to fail: 
1.  https://github.com/cockroachdb/cockroach/blob/93133e7bd7d52da6a9e3d0bec929703eaf2efc14/pkg/ccl/changefeedccl/cdcevent/event_test.go#L24 I suspect that `GetHydratedTableDescriptor` doesn't work for tenants

There are at least two packages which do not enable it
- `cdcevent`
- `cdceval`

Notes:
- To enable enterprise testing for a package, you need to add `defer ccl.TestingEnableEnterprise()()` to `main_test.go` in the package. You might have to change the pkg name for `main_test.go` to include `_test`, so that its different than the actual package (I'm not sure why)
- Tenants are disabled here: https://github.com/cockroachdb/cockroach/blob/99d2af93f561d5d8f747394f0bb7cf97b7f2f30f/pkg/server/testserver.go#L533

- Context about how tenant testing is enabled: https://github.com/cockroachdb/cockroach/commit/dc9448130adee55cf34b72e38d76f2e4d6bc1c77

TODO
- [ ] enable testing in all changefeed ccl packages which do not enable enterprise
- [ ] fix tests that fail when running on tenants

Jira issue: CRDB-25534

Epic CRDB-26115

### PR DESCRIPTION
**Pull request by yuzefovich**
Fixes: #98816
Informs: #142799
Release note: None

### CODE REVIEW

File: pkg/ccl/changefeedccl/changefeed_test.go [hunk 1]
```diff
@@ -8549,9 +8547,7 @@ func TestChangefeedHandlesRollingRestart(t *testing.T) {
 			return perNode
 		}(),
 		ServerArgs: base.TestServerArgs{
-			// Test uses SPLIT AT, which isn't currently supported for
-			// secondary tenants. Tracked with #76378.
-			DefaultTestTenant: base.TODOTestTenantDisabled,
+			DefaultTestTenant: base.TestDoesNotWorkWithSecondaryTenantsButWeDontKnowWhyYet(142799),
```
Comment (aerfrei) [inline pkg/ccl/changefeedccl/changefeed_test.go:8550]: Were these comments (that SPLIT AT isn't supported for secondary tenants) no longer true?
Are we now tracking these exclusively in #142799 and not #76378?

File: pkg/ccl/changefeedccl/changefeed_test.go [hunk 2]
```diff
@@ -11309,7 +11301,7 @@ func TestChangefeedExecLocality(t *testing.T) {
 	const nodes = 4
 	args := base.TestClusterArgs{
 		ServerArgs: base.TestServerArgs{
-			DefaultTestTenant: base.TODOTestTenantDisabled, // need nodelocal and splits.
```
Comment (aerfrei) [inline pkg/ccl/changefeedccl/changefeed_test.go:11312]: This comment too, is it not accurate for why this test wasn't working for tenants?

File: pkg/ccl/changefeedccl/parquet_test.go [hunk 3]
```diff
@@ -48,17 +48,16 @@ func TestParquetRows(t *testing.T) {
 	skip.UnderStress(t)
 
 	ctx := context.Background()
-	s, db, _ := serverutils.StartServer(t, base.TestServerArgs{
-		// TODO(#98816): cdctest.GetHydratedTableDescriptor does not work with tenant dbs.
```
Comment (aerfrei) [inline pkg/ccl/changefeedccl/parquet_test.go:52]: Awesome, nice that we have this test back.

File: pkg/ccl/changefeedccl/changefeed_test.go (hunk 2 above)
Comment (yuzefovich) [reply pkg/ccl/changefeedccl/changefeed_test.go:11312]: This comment is somewhat stale for sure. `CanUseNodelocalStorage` capability _should_ now be granted in the tests by default (see `testServer.grantDefaultTenantCapabilities`).

File: pkg/ccl/changefeedccl/changefeed_test.go (hunk 1 above)
Comment (yuzefovich) [reply pkg/ccl/changefeedccl/changefeed_test.go:8550]: The comments here are definitely stale, which is why I decided to remove them to avoid possible confusion. (In particular, when this comment was added, we needed to explicitly add `tenantcapabilitiespb.CanAdminSplit` to the tenant, but now this capability is granted by default, so no need to do anything about it. Perhaps the test will just work, perhaps it'll require some other adjustments, but SPLIT AT _should_ just work.)

I'm working on doing first level triage of all things that reference #76378 with the goal of closing that issue soon. All tests / packages that have test tenant randomization disabled will have a separate, specific issue, and #142799 is the common issue for all CDC tests.

**Review by yuzefovich — COMMENTED** [review]
TFTR!

Both essential CI and extended CI failures seem like flakes.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/156306#-:-OcfhxXQ5Y5cjSCp7kr1:b-rupaft)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @aerfrei)

**Review by asg0451 — APPROVED** [review]
