### PR TITLE
roachtest/mixedversion: use same node for backup dest and execution

### LINKED ISSUE #160498: roachtest/mixedversion: version-upgrade must not hardcode n1 in "maybe run backup" user hook
In `runVersionUpgrade`, "maybe run backup" user hook does the following,

```
dest := fmt.Sprintf("nodelocal://1/%d", timeutil.Now().UnixNano())
return h.Exec(rng, `BACKUP INTO $1`, dest)
```

Occasionally this yields in `X-infra-flake`, e.g., [1], [2], [3]. The crux of the issue is that `h.Exec` picks a random _available_ node whereas `dest` forces distsql to execute always on `n1`. Technically, `n1` may still be available, i.e., it's not a target of any failure injection. However, in the linked test failures, we observe that `n1` was just restarted which makes it temporarily unavailable. E.g., in [3], `h.Exec` is executed on `n4`  immediately after `n1` is restarted; we can see from `n4`'s log, it temporarily loses gRPC connection to `n1`,

```
...
E251231 07:02:18.484082 613 2@rpc/peer.go:694 â‹® [T1,Vsystem,n4,rnode=1,raddr=â€¹10.1.0.107:26257â€º,class=system,rpc] 473  failed connection attempt (last connected 1.002s ago): grpc: â€¹connection error: desc = "transport: error while dialing: dial tcp 10.1.0.107:26257: connect: connection refused"â€º [code 14/Unavailable]
...
I251231 07:02:27.399172 12567 1@backup/backup_planning.go:773 â‹® [T3,Vmixed-version-tenant-xchyv,n4,client=34.162.222.114:43834,hostssl,user=â€¹roachprodâ€º] 477  backup planning to connect to destination nodelocal://1/1767164547378856466
I251231 07:02:27.405368 12582 jobs/registry.go:1606 â‹® [T3,Vmixed-version-tenant-xchyv,n4] 478  BACKUP job 1137358102197567492: stepping through state running
I251231 07:02:27.424969 12582 1@jobs/update.go:193 â‹® [T3,Vmixed-version-tenant-xchyv,n4] 479 ={"Timestamp":1767164547424965547,"EventType":"status_change","JobID":1137358102197567492,"JobType":"BACKUP","Description":"state changed to: running","PreviousStatus":"running","NewStatus":"running","RunNum":0}
E251231 07:02:27.425949 12582 jobs/registry.go:1600 â‹® [T3,Vmixed-version-tenant-xchyv,n4] 480  BACKUP job 1137358102197567492: stepping through state reverting with unexpected error: failed to create blob client: connecting to node 1: gRPC: failed to connect to n1 at â€¹10.1.0.107:26257â€º: grpc: â€¹node unavailable; try another peerâ€º [code 2/Unknown]
```

even though `n1` is technically ready to serve as of `7:02:22`,

```
I251231 07:02:22.829599 68 1@cli/start.go:1294 â‹® [T1,Vsystem,n1] 132  node startup completed:
I251231 07:02:22.829599 68 1@cli/start.go:1294 â‹® [T1,Vsystem,n1] 132 +CockroachDB node starting at 2025-12-31 07:02:22.828931297 +0000 UTC m=+2.799539635 (took 2.6s)
I251231 07:02:22.829599 68 1@cli/start.go:1294 â‹® [T1,Vsystem,n1] 132 +build:               CCL v25.3.6 @ 2025/12/16 12:08:06 (go1.23.12 X:nocoverageredesign)
I251231 07:02:22.829599 68 1@cli/start.go:1294 â‹® [T1,Vsystem,n1] 132 +malloc_conf:         prof:false,prof_active:true,background_thread:true,thp:never,metadata_thp:disabled,narenas:16,dirty_decay_ms:2000,muzzy_decay_ms:0
I251231 07:02:22.829599 68 1@cli/start.go:1294 â‹® [T1,Vsystem,n1] 132 +webui:               â€¹https://10.1.0.107:26258â€º
I251231 07:02:22.829599 68 1@cli/start.go:1294 â‹® [T1,Vsystem,n1] 132 +sql:                 â€¹postgresql://root@10.1.0.107:26257/defaultdb?sslcert=certs%2Fclient.root.crt&sslkey=certs%2Fclient.root.key&sslmode=verify-full&sslrootcert=certs%2Fca.crtâ€º
I251231 07:02:22.829599 68 1@cli/start.go:1294 â‹® [T1,Vsystem,n1] 132 +sql (JDBC):          â€¹jdbc:postgresql://10.1.0.107:26257/defaultdb?sslcert=certs%2Fclient.root.crt&sslkey=certs%2Fclient.root.key&sslmode=verify-full&sslrootcert=certs%2Fca.crt&user=rootâ€º
I251231 07:02:22.829599 68 1@cli/start.go:1294 â‹® [T1,Vsystem,n1] 132 +RPC client flags:    â€¹./v25.3.6/cockroach <client cmd> --host=10.1.0.107:26257 --certs-dir=certsâ€º
I251231 07:02:22.829599 68 1@cli/start.go:1294 â‹® [T1,Vsystem,n1] 132 +logs:                â€¹/home/ubuntu/logsâ€º
I251231 07:02:22.829599 68 1@cli/start.go:1294 â‹® [T1,Vsystem,n1] 132 +locality:            â€¹cloud=azure,region=eastus,zone=eastuszâ€º
I251231 07:02:22.829599 68 1@cli/start.go:1294 â‹® [T1,Vsystem,n1] 132 +temp dir:            â€¹/mnt/data1/cockroach/cockroach-temp1444867039â€º
I251231 07:02:22.829599 68 1@cli/start.go:1294 â‹® [T1,Vsystem,n1] 132 +external I/O path:   â€¹/mnt/data1/cockroach/externâ€º
I251231 07:02:22.829599 68 1@cli/start.go:1294 â‹® [T1,Vsystem,n1] 132 +store[0]:            â€¹path=/mnt/data1/cockroach,attrs=node1:node1store1:store1â€º
I251231 07:02:22.829599 68 1@cli/start.go:1294 â‹® [T1,Vsystem,n1] 132 +clusterID:           af163ac3-1b89-4039-b468-45d7f6153dff
I251231 07:02:22.829599 68 1@cli/start.go:1294 â‹® [T1,Vsystem,n1] 132 +status:              restarted pre-existing node
I251231 07:02:22.829599 68 1@cli/start.go:1294 â‹® [T1,Vsystem,n1] 132 +nodeID:              1
```

The suggested workaround is to update `dest` dynamically to match the same node where `h.Exec` is executed.

[1] https://github.com/cockroachdb/cockroach/issues/153493#issuecomment-3326157634
[2] https://github.com/cockroachdb/cockroach/issues/155698#issuecomment-3453264998
[3] https://github.com/cockroachdb/cockroach/issues/160317

### PR DESCRIPTION
**Pull request by shailendra-patel**
the `maybe run backup` hook in `runVersionUpgrade` test hardcoded `nodelocal://1/` in the backup destination while `h.Exec` picked a random available node for SQL execution. This caused flaky failures when n1 was just restarted and temporarily unavailable for gRPC connections, even though the SQL executed on a different node.

This change ensures the backup destination and SQL execution use the same randomly selected available node.

Fixes #160498

Release note: None

Epic: None

### CODE REVIEW

**Comment by shailendra-patel** [comment]
[Teamcity](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/21069956?hideProblemsFromDependencies=false&hideTestsFromDependencies=false&expandBuildChangesSection=true) smoketest.

File: pkg/cmd/roachtest/tests/versionupgrade.go [hunk 1]
```diff
@@ -123,8 +123,13 @@ func runVersionUpgrade(ctx context.Context, t test.Test, c cluster.Cluster) {
 				// Verify that backups can be created in various configurations. This is
 				// important to test because changes in system tables might cause backups to
 				// fail in mixed-version clusters.
-				dest := fmt.Sprintf("nodelocal://1/%d", timeutil.Now().UnixNano())
-				return h.Exec(rng, `BACKUP INTO $1`, dest)
+				availableNodes := h.AvailableNodes()
+				if len(availableNodes) == 0 {
```
Comment (DarrylWong) [inline pkg/cmd/roachtest/tests/versionupgrade.go]: Is this check necessary? I think its fine to assume `h.AvailableNodes` will always return at least one node (it will panic if it doesn't anyway). If there are no available nodes then we've constructed a bad test plan.

File: pkg/cmd/roachtest/tests/versionupgrade.go [hunk 2]
```diff
@@ -123,8 +123,13 @@ func runVersionUpgrade(ctx context.Context, t test.Test, c cluster.Cluster) {
 				// Verify that backups can be created in various configurations. This is
 				// important to test because changes in system tables might cause backups to
 				// fail in mixed-version clusters.
-				dest := fmt.Sprintf("nodelocal://1/%d", timeutil.Now().UnixNano())
-				return h.Exec(rng, `BACKUP INTO $1`, dest)
+				availableNodes := h.AvailableNodes()
```
Comment (DarrylWong) [inline pkg/cmd/roachtest/tests/versionupgrade.go]: Should we just add a `h.RandomAvailableNode` helper?

Comment (shailendra-patel) [reply pkg/cmd/roachtest/tests/versionupgrade.go]: This make sense, thanks!

**Review by srosenberg — APPROVED** [review]
