### PR TITLE
roachtest: fix the deco test + re-implement the warning test

### LINKED ISSUE #44276: roachtest: acceptance/decommission failed
[(roachtest).acceptance/decommission failed](https://teamcity.cockroachdb.com/viewLog.html?buildId=1705466&tab=buildLog) on [release-19.2@51a7a6e8f795f960d857717ad11f097bb5cafe47](https://github.com/cockroachdb/cockroach/commits/51a7a6e8f795f960d857717ad11f097bb5cafe47):

```
The test failed on branch=release-19.2, cloud=gce:
test artifacts and logs in: /home/agent/work/.go/src/github.com/cockroachdb/cockroach/artifacts/20200123-1705466/acceptance/decommission/run_1
	decommission.go:447,acceptance.go:84,test_runner.go:719: expected warning at start of duplicate decommission, got:
		id	is_live	replicas	is_decommissioning	is_draining
		1	true	0	true	false
		
		No more data reported on target nodes. Please verify cluster health before removing the nodes.
		

```

<details><summary>More</summary><p>

Artifacts: [/acceptance/decommission](https://teamcity.cockroachdb.com/viewLog.html?buildId=1705466&tab=artifacts#/acceptance/decommission)
Related:
- #44271 roachtest: acceptance/decommission failed  [C-test-failure](https://api.github.com/repos/cockroachdb/cockroach/labels/C-test-failure) [O-roachtest](https://api.github.com/repos/cockroachdb/cockroach/labels/O-roachtest) [O-robot](https://api.github.com/repos/cockroachdb/cockroach/labels/O-robot) [branch-release-19.1](https://api.github.com/repos/cockroachdb/cockroach/labels/branch-release-19.1) [release-blocker](https://api.github.com/repos/cockroachdb/cockroach/labels/release-blocker)

- #44269 roachtest: acceptance/decommission failed  [C-test-failure](https://api.github.com/repos/cockroachdb/cockroach/labels/C-test-failure) [O-roachtest](https://api.github.com/repos/cockroachdb/cockroach/labels/O-roachtest) [O-robot](https://api.github.com/repos/cockroachdb/cockroach/labels/O-robot) [branch-release-2.1](https://api.github.com/repos/cockroachdb/cockroach/labels/branch-release-2.1) [release-blocker](https://api.github.com/repos/cockroachdb/cockroach/labels/release-blocker)

- #44233 roachtest: acceptance/decommission failed  [C-test-failure](https://api.github.com/repos/cockroachdb/cockroach/labels/C-test-failure) [O-roachtest](https://api.github.com/repos/cockroachdb/cockroach/labels/O-roachtest) [O-robot](https://api.github.com/repos/cockroachdb/cockroach/labels/O-robot) [branch-provisional_202001221958_v2.1.11](https://api.github.com/repos/cockroachdb/cockroach/labels/branch-provisional_202001221958_v2.1.11) [release-blocker](https://api.github.com/repos/cockroachdb/cockroach/labels/release-blocker)

- #41178 roachtest: acceptance/decommission failed  [C-test-failure](https://api.github.com/repos/cockroachdb/cockroach/labels/C-test-failure) [O-roachtest](https://api.github.com/repos/cockroachdb/cockroach/labels/O-roachtest) [O-robot](https://api.github.com/repos/cockroachdb/cockroach/labels/O-robot) [branch-master](https://api.github.com/repos/cockroachdb/cockroach/labels/branch-master)

[See this test on roachdash](https://roachdash.crdb.dev/?filter=status%3Aopen+t%3A.%2Aacceptance%2Fdecommission.%2A&sort=title&restgroup=false&display=lastcommented+project)
<sub>powered by [pkg/cmd/internal/issues](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)</sub></p></details>

### PR DESCRIPTION
**Pull request by knz**
Fixes #44276.

The test to check for a warning on double [rd]ecommission was
implemented in roachtest; this was invalid because roachtest
is also used on previous versions and the warning is a new thing.

This patch moves the test to a TCL interactive test instead.

Release note: None

### CODE REVIEW

File: pkg/cmd/roachtest/decommission.go [hunk 1]
```diff
@@ -440,12 +441,18 @@ func runDecommissionAcceptance(ctx context.Context, t *test, c *cluster) {
 	}
 
 	t.l.Printf("trying to decommission a second time\n")
-	if buf, err := decommission(ctx, 2, c.Node(1), "decommission"); err != nil {
-		t.Fatalf("decommission failed: %v", err)
-	} else {
+	if err := testutils.SucceedsSoonError(func() error {
```
Comment (tbg) [inline pkg/cmd/roachtest/decommission.go]: But this will still fail hard on any branches that don't have your commit, no?

Comment (knz) [reply pkg/cmd/roachtest/decommission.go]: How come is a _new_ roachtest applied on a branch with the _old_ code?

If there's such mix of version, what do you want me to do? You suggested a roachtest to check the warning, is that recommendation rescinded? I can do a TCL interactive test instead if needed.

**Comment by tbg** [comment]
roachtests aren't versioned, we always run the code from master against the release branches. Apologies for not making that clear and for (apparently) telling you to test this in a roachtest, which was bad advice for the reasons we're seeing here. Sorry to have wasted your time. Yes a TCL test or whatever cheap way (cli test?) is better. Unfortunately the roachtest might not like the new output you added (so it will have to change anyway). Or maybe not? All depends on what exactly this crazy parsing here does:

https://github.com/cockroachdb/cockroach/blob/e85cdeb1bd8a3f134ab867d8039339212e71c0aa/pkg/cmd/roachtest/decommission.go#L303-L316

**Comment by knz** [comment]
Rewrote the PR. PTAL.

**Review by tbg — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/44297#-:-Lzb-3DfAmeGyHpKvzqU:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained

**Review by tbg — APPROVED** [review]
> Reviewed 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/44297)* status: :shipit: complete! 1 of 0 LGTMs obtained

**Comment by knz** [comment]
thx 

bors r=tbg
