### PR TITLE
encoding: fix UnsafeConvertStringToBytes to work with large input strings

### LINKED ISSUE #111626: encoding: UnsafeConvertStringToBytes panic on large input
Panic importing 2.7GB file https://cockroachlabs.slack.com/archives/CV581CE78/p1696286878568879
```
panic: runtime error: slice bounds out of range [::5626539592] with length 2147483647 [recovered]
	panic: runtime error: slice bounds out of range [::5626539592] with length 2147483647

goroutine 933315 [running]:
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).closeWrapper(0x14013faa600, {0x109afcec0, 0x14005d2f980}, {0x109722b60?, 0x14011e72000?})
	github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:1199 +0x164
github.com/cockroachdb/cockroach/pkg/sql.(*Server).ServeConn.func1({0x109afcec0, 0x14005d2f980}, {0x0?})
	github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:952 +0x4c
panic({0x109722b60, 0x14011e72000})
	GOROOT/src/runtime/panic.go:884 +0x204
github.com/cockroachdb/cockroach/pkg/util/encoding.UnsafeConvertStringToBytes(...)
	github.com/cockroachdb/cockroach/pkg/util/encoding/encoding.go:927
github.com/cockroachdb/cockroach/pkg/sql/sem/tree.(*DBytes).UnsafeBytes(...)
	github.com/cockroachdb/cockroach/pkg/sql/sem/tree/datum.go:1674
github.com/cockroachdb/cockroach/pkg/sql.(*fileUploadMachine).writeFile(0x14008e3e810, {0x109afce18, 0x1400a0c8dc0}, 0x1?)
	github.com/cockroachdb/cockroach/pkg/sql/copy_file_upload.go:204 +0x210
github.com/cockroachdb/cockroach/pkg/sql.(*copyMachine).processCopyData(0x14009874e00, {0x109afce18, 0x1400a0c8dc0}, {0x0, 0x0}, 0x1)
	github.com/cockroachdb/cockroach/pkg/sql/copy_from.go:671 +0x3f4
```

Jira issue: CRDB-31994

### PR DESCRIPTION
**Pull request by ecwall**
Fixes #111626

The previous impl assumed input string length <= math.MaxInt32. Go 1.20 added unsafe.StringData (https://pkg.go.dev/unsafe#StringData) which properly handles longer strings. This changes the impl to use unsafe.StringData and adds a unit test.

Release note (bug fix): Fixed a panic that could occur if a query uses a string
larger than 2^31-1 bytes.

### CODE REVIEW

File: pkg/util/encoding/encoding.go [hunk 1]
```diff
@@ -913,18 +913,7 @@ func prettyPrintInvertedIndexKey(b []byte) (string, []byte, error) {
 // modified if the input string is expected to be used again - doing so could
 // violate Go semantics.
 func UnsafeConvertStringToBytes(s string) []byte {
-	if len(s) == 0 {
```
Comment (cucaroach) [inline pkg/util/encoding/encoding.go:916]: If the go docs are to be believed I think we need to leave in the zero length check.  https://pkg.go.dev/unsafe#StringData

**Comment by cucaroach** [comment]
Thanks for the quick fix!

File: pkg/util/encoding/encoding.go (hunk 1 above)
Comment (ecwall) [reply pkg/util/encoding/encoding.go:916]: Ok, added this back.

**Review by cucaroach — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/111627)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ecwall and @j82w)

___
*[`pkg/util/encoding/encoding.go` line 999 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/111627#-Nfpg7cbBVormASuoGrj:-Nfpg7cbBVormASuoGrk:b-9yqb19) ([raw file](https://github.com/cockroachdb/cockroach/blob/f157ff5ceec40a580bf421ce170b34445c9481a0/pkg/util/encoding/encoding.go#L999)):*
> ```Go
> 	// Next we treat the string data as a maximally sized array which we
> 	// slice. This usage is safe because the pointer value remains in the string.
> 	arg := (*[0x7fffffff]byte)(unsafe.Pointer(hdr.Data))[:len(s):len(s)]
> ```

We should fix this one too

**Comment by ecwall** [comment]
> > _[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/111627)_ status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ecwall and @j82w)
> 
> _[`pkg/util/encoding/encoding.go` line 999 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/111627#-Nfpg7cbBVormASuoGrj:-Nfpg7cbBVormASuoGrk:b-9yqb19) ([raw file](https://github.com/cockroachdb/cockroach/blob/f157ff5ceec40a580bf421ce170b34445c9481a0/pkg/util/encoding/encoding.go#L999)):_
> 
> > ```go
> > 	// Next we treat the string data as a maximally sized array which we
> > 	// slice. This usage is safe because the pointer value remains in the string.
> > 	arg := (*[0x7fffffff]byte)(unsafe.Pointer(hdr.Data))[:len(s):len(s)]
> > ```
> 
> We should fix this one too

Good catch.

**Review by cucaroach — APPROVED** [review]

**Comment by j82w** [comment]
*[`pkg/util/encoding/encoding_test.go` line 2648 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/111627#-Nfpy3Gd3pSWTx-rnSvG:-Nfpy3Gd3pSWTx-rnSvH:bxi9eqt) ([raw file](https://github.com/cockroachdb/cockroach/blob/a1865b407eb8d78a68ca46d7c8c82613f8111df7/pkg/util/encoding/encoding_test.go#L2648)):*
> ```Go
> 		t.Run(tc.desc, func(t *testing.T) {
> 			actual := UnsafeConvertStringToBytes(tc.input)
> 			require.Equal(t, tc.expected, actual)
> ```

I think the test might be failing because the `t` is overloaded, and it's using the outer `t` from the original test call. I would suggest renaming it to avoid the ambiguity to make sure it use the t from the function.

**Comment by ecwall** [comment]
> _[`pkg/util/encoding/encoding_test.go` line 2648 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/111627#-Nfpy3Gd3pSWTx-rnSvG:-Nfpy3Gd3pSWTx-rnSvH:bxi9eqt) ([raw file](https://github.com/cockroachdb/cockroach/blob/a1865b407eb8d78a68ca46d7c8c82613f8111df7/pkg/util/encoding/encoding_test.go#L2648)):_
> 
> > ```go
> > 		t.Run(tc.desc, func(t *testing.T) {
> > 			actual := UnsafeConvertStringToBytes(tc.input)
> > 			require.Equal(t, tc.expected, actual)
> > ```
> 
> I think the test might be failing because the `t` is overloaded, and it's using the outer `t` from the original test call. I would suggest renaming it to avoid the ambiguity to make sure it use the t from the function.

The inner `t` shadows the outer one which is what we want because calling `require.Equal(t, ...)` with the outer one when inside a subtest will fail the test with a useless error message like
```
testing.go:1471: test executed panic(nil) or runtime.Goexit: subtest may have called FailNow on a parent test
```

I think the test needs to be skipped under stress because of the large input.

**Review by rafiss — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/111627)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @cucaroach, @ecwall, and @j82w)

___
*[`-- commits` line 11 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/111627#-NfqOEwAC6qOc3J17tct):*
nit: the public facing release notes should not reference an internal function name in our code base. can this be rephrased so something more high level? like "Fixed a panic that could occur if a query uses a string larger than 2^32 bytes."

**Review by ecwall — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/111627)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @cucaroach, @j82w, and @rafiss)

___
*[`-- commits` line 11 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/111627#-NfqOEwAC6qOc3J17tct):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

nit: the public facing release notes should not reference an internal function name in our code base. can this be rephrased so something more high level? like "Fixed a panic that could occur if a query uses a string larger than 2^32 bytes."
</blockquote></details>

The function name appears in the error output because of the panic so I thought it would make sense to reference it here so customers can identify if they had this problem. I don't have a strong opinion though so I will change it (also, it is 2^31-1 bytes).

**Review by rafiss — APPROVED** [review]
