### PR TITLE
Do not call Store.{Split,Merge}Range until after the RocksDB commit.

### LINKED ISSUE #1191: crash in raft.sendAppend: requested index at entry is unavailable
This happened in tandem with #1185 and after a flurry of messages

```
W0529 13:18:33.251543       1 dist_sender.go:588] failed to invoke InternalPushTxn: key range "00065201
"-"" outside of bounds of range ""-""
```

(which are not surprising in this scenario given that the node never executes any of the splits)

```
I0529 13:18:33.251657       1 retry.go:95] routing InternalPushTxn rpc failed; retrying immediately
W0529 13:18:33.251948       1 dist_sender.go:588] failed to invoke InternalPushTxn: key range "00065201"-"" outside of bounds of range ""-""
I0529 13:18:33.251966       1 retry.go:95] routing InternalPushTxn rpc failed; retrying immediately
W0529 13:18:33.253062       1 dist_sender.go:588] failed to invoke InternalPushTxn: key range "00065201"-"" outside of bounds of range ""-""
I0529 13:18:33.253138       1 retry.go:95] routing InternalPushTxn rpc failed; retrying immediately
panic: requested entry at index is unavailable

goroutine 64 [running]:
github.com/coreos/etcd/raft.(*raft).sendAppend(0xc2097f4000, 0x300000003)
        /home/tobias/Code/Go/src/github.com/coreos/etcd/raft/raft.go:250 +0x159
github.com/coreos/etcd/raft.stepLeader(0xc2097f4000, 0x4, 0x200000002, 0x300000003, 0x6, 0x0, 0xa, 0x0, 0x0, 0x0, ...)
        /home/tobias/Code/Go/src/github.com/coreos/etcd/raft/raft.go:523 +0x6f3
github.com/coreos/etcd/raft.(*raft).Step(0xc2097f4000, 0x4, 0x200000002, 0x300000003, 0x6, 0x0, 0xa, 0x0, 0x0, 0x0, ...)
        /home/tobias/Code/Go/src/github.com/coreos/etcd/raft/raft.go:487 +0x259
github.com/coreos/etcd/raft.(*multiNode).run(0xc2080ff0e0)
        /home/tobias/Code/Go/src/github.com/coreos/etcd/raft/multinode.go:236 +0xd0b
created by github.com/coreos/etcd/raft.StartMultiNode
        /home/tobias/Code/Go/src/github.com/coreos/etcd/raft/multinode.go:56 +0xb6
```

### PR DESCRIPTION
**Pull request by bdarnell**
Introduce Engine.Defer() to associate callbacks with the commit.

Fixes #1191.

### CODE REVIEW

File: storage/engine/rocksdb.go [hunk 1]
```diff
@@ -417,6 +417,10 @@ func (r *RocksDB) Commit() error {
 	return nil
 }
 
+// Defer is a noop for RocksDB engine.
+func (r *RocksDB) Defer(func()) {
```
Comment (tamird) [inline storage/engine/rocksdb.go]: total nit: it is apparently possible to write:
```
func (*RocksDB) Defer(func()) {
```

**Comment by bdarnell** [comment]
Unfortunately I was never able to reproduce this locally but can't come up with any more reliable way to test it than the SnapshotRace test that fails intermittently on circleci. I tried adding more sanity checks to Store.SplitRange but couldn't do anything that would catch the bug without breaking all the tests using `splitTestRange` (which should be removed, but that's another TODO).

File: storage/engine/rocksdb.go [hunk 2]
```diff
@@ -663,9 +672,19 @@ func (r *rocksDBBatch) Commit() error {
 	}
 	C.DBBatchDestroy(r.batch)
 	r.batch = nil
+
+	// On success, run the deferred functions in reverse order.
+	for i := range r.defers {
+		r.defers[len(r.defers)-i-1]()
```
Comment (tamird) [inline storage/engine/rocksdb.go]: nit: i'd put `i` at the end as the non-static thing in the list

**Comment by tamird** [comment]
LGTM but do we want to add an integration test for #1191?

File: storage/engine/rocksdb.go [hunk 3]
```diff
@@ -511,9 +515,14 @@ func (r *rocksDBSnapshot) Commit() error {
 	return util.Errorf("cannot Commit to a snapshot")
 }
 
+// Defer is a noop for rocksDBSnapshot.
+func (r *rocksDBSnapshot) Defer(func()) {
```
Comment (tamird) [inline storage/engine/rocksdb.go]: ditto that nit

File: storage/engine/rocksdb.go (hunk 2 above)
Comment (tamird) [inline storage/engine/rocksdb.go]: also, do we need to clear these defers out as we call them?

**Comment by tschottdorf** [comment]
@bdarnell adding the `time.Sleep(100*time.Millisecond)` as I suggested in https://github.com/cockroachdb/cockroach/issues/1191#issuecomment-112776586 didn't fail it on your machine?

File: storage/engine/batch_test.go [hunk 4]
```diff
@@ -435,3 +435,31 @@ func TestBatchConcurrency(t *testing.T) {
...
+	})
+
+	if err := b.Commit(); err != nil {
+		t.Fatal(err)
+	}
+
+	// Order was reversed when the defers were run.
+	if !reflect.DeepEqual(list, []string{"two", "one"}) {
+		t.Errorf("expected [two, one]; got %v", list)
+	}
```
Comment (tschottdorf) [inline storage/engine/batch_test.go]: Can you add a test case for a non-batch engine? Because it used to say that `Commit()` is a no-op then, but probably you still want to run any callbacks.

Comment (tschottdorf) [inline storage/engine/batch_test.go]: Ok, you say in `engine.go` that you're not running them, so a bogus test for that please.

File: storage/engine/rocksdb.go (hunk 2 above)
Comment (tschottdorf) [inline storage/engine/rocksdb.go]: I don't think we need to, but we should for consistency (plus otherwise if we leak the batch, we also leak the defers)

File: storage/range_command.go [hunk 5]
```diff
@@ -1084,7 +1091,13 @@ func (r *Range) mergeTrigger(batch engine.Engine, merge *proto.MergeTrigger) err
 	// and not worth the extra logic and potential for error.
 	r.tsCache.Clear(r.rm.Clock())
 
-	return r.rm.MergeRange(r, merge.UpdatedDesc.EndKey, merge.SubsumedRaftID)
+	batch.Defer(func() {
```
Comment (tschottdorf) [inline storage/range_command.go]: unrelated to this PR, but the comment of mergeTrigger isn't up to date.

Comment (tschottdorf) [inline storage/range_command.go]: Also, doesn't everything that mutates `r` above need to be done in the defer (and Fatal when something goes wrong or somehow recover the previous state)?

**Comment by tschottdorf** [comment]
LGTM, but under the assumption that when doing the Commit/update memory state dance, any error is pretty much fatal, it looks like we *could* just have the triggers executed right before the `Commit()` (if we make it a point to Fatal should the commit fail)?

**Comment by tschottdorf** [comment]
Do you still need to lock the range around the call to `batch.Commit()` (if there are deferred triggers - hard to know from the API, so my last comment might be relevant) or do we already do that anyways?

File: storage/engine/rocksdb.go (hunk 2 above)
Comment (bdarnell) [inline storage/engine/rocksdb.go]: Done (moving `i` to the end and clearing the defer list after calling them)

File: storage/engine/batch_test.go (hunk 4 above)
Comment (bdarnell) [inline storage/engine/batch_test.go]: I'll just make Defer panic for non-batch engines.

File: storage/engine/rocksdb.go (hunk 1 above)
Comment (petermattis) [inline storage/engine/rocksdb.go]: Should this method and `rocksDBSnapshot.Defer` panic instead of silently doing nothing?

File: storage/range_command.go (hunk 5 above)
Comment (bdarnell) [inline storage/range_command.go]: Probably, but that's another can of worms.

File: storage/engine/rocksdb.go [hunk 6]
```diff
@@ -663,9 +672,19 @@ func (r *rocksDBBatch) Commit() error {
 	}
 	C.DBBatchDestroy(r.batch)
 	r.batch = nil
+
+	// On success, run the deferred functions in reverse order.
+	for i := range r.defers {
```
Comment (petermattis) [inline storage/engine/rocksdb.go]: Might be clearer to do: `for i := len(r.defers)-1; i >= 0; i-- {`

**Comment by petermattis** [comment]
LGTM on the `Engine.Defer` mechanism.

**Comment by bdarnell** [comment]
Adding the sleep to the non-test code path does reproduce the problem, but I can't figure out how to reproduce in a way that would be acceptable for a test.

The triggers cannot execute before `Commit()` because as soon as `Store.SplitRange` releases the `Store` lock, another thread may find the new range in the map and expect to read its descriptor from disk.

Range operations are generally serialized by the fact that raft processing is single threaded, not by a range-level lock. The question is whether we should also lock the *store* around the commit. I don't want to do that unless we have to, and so far the only actual problem we've identified is that the store shouldn't point to ranges until after they exist on disk.

**Comment by petermattis** [comment]
@bdarnell Could you add something like the testpoint stuff we did at Square? That is, allow the test to indicate it wants the regular code to pause at a certain point in order to test a particular code path.

**Comment by bdarnell** [comment]
@petermattis I wasn't familiar with the testpoint stuff but yeah, it would be possible to add some sort of hook here.

**Comment by petermattis** [comment]
@MBerhault wrote the testpoint stuff. I'm sure we could extract something similar from his brain again.

**Comment by bdarnell** [comment]
Actually I'm not sure a testpoint would make sense here. We could have reproduced the old bug with one, but now that the fix has reorganized things there's not really a place to put the delay that demonstrates something useful. I think the better fix is to add more invariant checking in SplitRange but we can't do that until we clean up some of the existing tests. I'm going to merge this now to fix the current test flakiness and have filed #1417 to track the remaining issues.
