### PR TITLE
backupccl,kvserver: log failed ExportRequest trace on client and server

### LINKED ISSUE #86047: backupccl: print trace before timing out ExportRequest
Every ExportRequest sent by backup is given 5 minutes to complete, after which its context is canceled and the backup fails. This is a rather blunt hammer, and there is potentially scope for improvement, but in the meantime we should add more observability that helps triage why the ExportRequest was stuck for so long. One easy way to surface more information would be to pull a trace a few seconds before we are going to timeout and log it for consumption. Backups collect traces as they execute and so the trace would give us insight into where the ExportRequest spent the majority of the 5 mins. This would potentially help us triage support issues such as intent buildup a lot quicker.

Jira issue: CRDB-18544

Epic CRDB-8964

### PR DESCRIPTION
**Pull request by adityamaru**
This change strives to improve observability around
backups that fail because of timed out ExportRequests.
Currently, there is very little indication of what the request
was doing when the client cancelled the context after
the pre-determined timeout window. With this change we
now log the trace of the ExportRequest that failed. If
the ExportRequest was served locally, then the trace will be
part of the sender's tracing span. However, if the request
was served on a remote node then the sender does not wait
for the server side evaluation to notice the context cancellation.
To work around this, we also print the trace on the server side
if the request encountered a context cancellation and the
associating tracing span is not a noop.

This change also adds a private cluster setting
`bulkio.backup.export_request_verbose_tracing` that if set to true
will send all backup export requests with verbose tracing
mode.

To debug a backup failing with a timed out export request we
can now:
- SET CLUSTER SETTING bulkio.backup.export_request_verbose_tracing = true;
- SET CLUSTER SETTING trace.snapshot.rate = '1m'

Once the backup times out we can look at the logs
for the server side and client side ExportRequest traces
to then understand where we were stuck executing for so long.

Fixes: https://github.com/cockroachdb/cockroach/issues/86047
Release note: None

### CODE REVIEW

**Comment by adityamaru** [comment]
@arulajmani not sure how much you like this approach but as discussed offline for remotely served ExportRequests DistSender does not way for the batch response before returning an error to the client. For this reason, the trace emitted on the client will only contain calls upto `DistSender.Send`. To work around this I've added a server side log line in case the `BatchRequest` encounters a context cancellation. This way if an ExportRequest were to timeout we'd atleast have the trace for that request in the logs to understand why it timed out.

Let me know if you think its useful to push forward with this diff. Some experimentation in roachprod shows that if we always send ExportRequests as verbose then for requests that take longer than the timeout we see the following log line, which is definitely more than what we have today. A structured trace would give us less that what is pasted below, but would be a good starting point. I want to leave the switch to verbose tracing spans to a follow up that is done with some performance testing of different backups.

```
adityamaru-test-0003> W230504 22:13:50.766535 4269 server/node.go:1227 ⋮ [T1,n3] 237 request: ‹1 Export›
error: ‹context canceled›
trace: ‹     0.000ms      0.000ms    === operation:/cockroach.roachpb.Internal/Batch _unfinished:1 _verbose:1 node:3 span.kind:server request:Export [/Table/104/1,/Table/104/2), [wait-policy: Error]›
‹     0.000ms      0.000ms    [evalExport: {count: 1, duration 40s}]›
‹     0.000ms      0.000ms    [storage.MVCCExportToSST: {count: 1, duration 40s}]›
‹     0.039ms      0.039ms    event:server/node.go:1171 [n3] node received request: 1 Export›
‹     0.122ms      0.083ms    event:kv/kvserver/store_send.go:154 [n3,s3] executing Export [/Table/104/1,/Table/104/2), [wait-policy: Error]›
‹     0.159ms      0.037ms    event:kv/kvserver/replica_send.go:180 [n3,s3,r64/3:/{Table/104-Max}] read-only path›
‹     0.184ms      0.025ms    event:kv/kvserver/concurrency/concurrency_manager.go:195 [n3,s3,r64/3:/{Table/104-Max}] sequencing request›
‹     0.198ms      0.014ms    event:kv/kvserver/concurrency/concurrency_manager.go:276 [n3,s3,r64/3:/{Table/104-Max}] acquiring latches›
‹     0.217ms      0.020ms    event:kv/kvserver/concurrency/concurrency_manager.go:320 [n3,s3,r64/3:/{Table/104-Max}] scanning lock table for conflicting locks›
‹     0.257ms      0.039ms    event:kv/kvserver/replica_follower_read.go:126 [n3,s3,r64/3:/{Table/104-Max}] serving via follower read; query timestamp below closed timestamp by 1.71932036s›
‹     0.333ms      0.076ms    event:kv/kvserver/replica_read.go:297 [n3,s3,r64/3:/{Table/104-Max}] can drop latches early for batch (Export [/Table/104/1,/Table/104/2), [wait-policy: Error]); scanning lock table first to detect conflicts›
‹     0.399ms      0.066ms    event:kv/kvserver/replica_read.go:114 [n3,s3,r64/3:/{Table/104-Max}] lock table scan complete without conflicts; dropping latches early›
‹     0.415ms      0.016ms    event:kv/kvserver/replica_read.go:409 [n3,s3,r64/3:/{Table/104-Max}] executing read-only batch›
‹     0.422ms      0.007ms        === operation:evalExport _verbose:1 node:3 store:3 range:64/3:/{Table/104-Max}›
‹     0.422ms      0.000ms        [storage.MVCCExportToSST: {count: 1, duration 40s}]›
‹     0.427ms      0.005ms            === operation:storage.MVCCExportToSST _verbose:1 node:3 store:3 range:64/3:/{Table/104-Max}›
‹ 40001.896ms  40001.474ms        event:kv/kvserver/batcheval/cmd_export.go:243 [n3,s3,r64/3:/{Table/104-Max}] the error we are getting is context canceled›
‹ 40002.107ms  40001.692ms    event:kv/kvserver/replica_evaluate.go:550 [n3,s3,r64/3:/{Table/104-Max}] evaluated Export command header:<kvnemesis_seq:<> key:"\360\211" end_key:"\360\212" > resume_key_ts:<> start_time:<> split_mid_key:true target_file_size:16777216 fingerprint_options:<> , txn=<nil> : resp=header:<> start_time:<> , err=context canceled›
‹ 40002.192ms      0.085ms    event:kv/kvserver/replica_read.go:217 [n3,s3,r64/3:/{Table/104-Max}] context canceled›
‹ 40002.241ms      0.049ms    event:kv/kvserver/replica_send.go:199 [n3,s3,r64/3:/{Table/104-Max}] replica.Send got error: context canceled›
‹ 40002.274ms      0.033ms    event:server/node.go:1204 [n3] error from stores.Send: context canceled›
‹ 40002.481ms      0.207ms    event:stack as of 21.3s ago: goroutine 4269 [sleep]:›
‹time.Sleep(0x9502f9000)›
‹       GOROOT/src/runtime/time.go:195 +0x135›
‹github.com/cockroachdb/cockroach/pkg/storage.mvccExportToWriter({0x74c48b0, 0xc004a615c0}, {0x7505f10, 0xc005618600}, {{{0xc00a086a08, 0x2, 0x8}, {0x0, 0x0, 0x0}}, ...}, ...)›
‹       github.com/cockroachdb/cockroach/pkg/storage/mvcc.go:6519 +0x399›
‹github.com/cockroachdb/cockroach/pkg/storage.MVCCExportToSST({0x74c48b0?, 0xc004a61560?}, 0x754ea90?, {0x7505f10, 0xc005618600}, {{{0xc00a086a08, 0x2, 0x8}, {0x0, 0x0, ...}}, ...}, ...)›
‹       github.com/cockroachdb/cockroach/pkg/storage/mvcc.go:6349 +0x2a5›
‹github.com/cockroachdb/cockroach/pkg/kv/kvserver/batcheval.evalExport({_, _}, {_, _}, {{0x75632b0, 0xc003bf1500}, {{0x175c1064a34626bb, 0x0, 0x0}, 0x0, ...}, ...}, ...)›
‹       github.com/cockroachdb/cockroach/pkg/kv/kvserver/batcheval/cmd_export.go:232 +0xb36›
‹github.com/cockroachdb/cockroach/pkg/kv/kvserver.evaluateCommand({_, _}, {_, _}, {_, _}, _, _, {{0x175c1064a34626bb, 0x0, ...}, ...}, ...)›
‹       github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/replica_evaluate.go:528 +0x4c7›
‹github.com/cockroachdb/cockroach/pkg/kv/kvserver.evaluateBatch({_, _}, {_, _}, {_, _}, {_, _}, _, 0xc004acf7a0, ...)›
‹       github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/replica_evaluate.go:294 +0xea5›
```

**Review by arulajmani — COMMENTED** [review]
Thanks for doing this, this is sick! I have no opinions on the approach to be honest. 

> I want to leave the switch to verbose tracing spans to a follow up that is done with some performance testing of different backups.

Consider putting it behind a cluster setting, defaulted to false. That way, we can reach for verbose tracing when running experiments/or whatever else. 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/102793#-:-NUgK8WTDhcigZRGgzLY:b-e98icj)* status: :shipit: complete! 0 of 0 LGTMs obtained

**Comment by adityamaru** [comment]
I changed the error wrapping to a log line just because this error is stored in the jobs table and is surfaced on the console, so having a big trace dumped in the error doesn't look great.

The only part I'm antsy about is the change to `node.go` so let's loop in a couple more folks that might have opinions.

**Comment by adityamaru** [comment]
https://github.com/cockroachdb/cockroach/pull/103034 will make the use of `log.Error` correct

**Review by irfansharif — APPROVED** [review]
LGTM, but you could just inline what you're doing in SendWrappedWithAdmissionTraced like the comment below suggests.

File: pkg/kv/sender.go [hunk 1]
```diff
@@ -424,10 +427,35 @@ func SendWrappedWith(
...
 
-// SendWrappedWithAdmission is a convenience function which wraps the request
-// in a batch and sends it via the provided Sender and headers. It returns the
-// unwrapped response or an error. It's valid to pass a `nil` context; an
-// empty one is used in that case.
+// SendWrappedWithAdmissionTraced is a convenience function that calls
+// SendWrappedWithAdmission but with the execution wrapped in a tracing span.
+// This method returns the unwrapped response or an error along with the trace
+// recording of the span.
+func SendWrappedWithAdmissionTraced(
```
[the remark this answers is not in the document]
Comment (adityamaru) [reply pkg/kv/sender.go]: done! There are 2 callers fwiw but still inlining makes sense to me.

**Comment by adityamaru** [comment]
Flake is https://github.com/cockroachdb/cockroach/issues/99261

bors r=irfansharif

File: pkg/ccl/backupccl/backup_processor.go [hunk 2]
```diff
@@ -453,6 +471,9 @@ func runBackupProcessor(
 						// TimeoutError improves the opaque `context deadline exceeded` error
 						// message so use that instead.
 						if errors.HasType(exportRequestErr, (*contextutil.TimeoutError)(nil)) {
+							if recording != nil {
+								log.Errorf(ctx, "failed export request for span %s\n trace:\n%s", span.span, recording)
```
Comment (knz) [inline pkg/ccl/backupccl/backup_processor.go:475]: here and below: unnecessary space before `trace`.

File: pkg/ccl/backupccl/backup_processor.go [hunk 3]
```diff
@@ -82,6 +84,13 @@ var (
 		"split backup data on timestamps when writing revision history",
 		true,
 	)
+
+	sendExportRequestWithVerboseTracing = settings.RegisterBoolSetting(
+		settings.TenantWritable,
+		"bulkio.backup.export_request_verbose_tracing",
```
Comment (knz) [inline pkg/ccl/backupccl/backup_processor.go:90]: How come this name was validated by the test `TestLintClusterSettingNames` in `pkg/sql/show_test.go`? It's not valid per that linter. Ditto the `_delay` one above.

**Comment by adityamaru** [comment]
blathers backport 23.1 22.2
