### PR TITLE
 server,grpcutil: fix nil panic in TestDrain with DRPC

### LINKED ISSUE #165377: server: TestDrain failed
server.TestDrain [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Ci_TestsAwsLinuxArm64_UnitTests/21226939?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Ci_TestsAwsLinuxArm64_UnitTests/21226939?buildTab=artifacts#/) on master @ [bb02fd678b06df257d9296b22ceb48cba45f0693](https://github.com/cockroachdb/cockroach/commits/bb02fd678b06df257d9296b22ceb48cba45f0693):

```
=== RUN   TestDrain
    test_log_scope.go:172: test logs captured to: /artifacts/tmp/_tmp/4b992d1f969871bcc9fd338a5653884d/logTestDrain3341812692
    test_log_scope.go:82: use -show-logs to present logs inline
--- FAIL: TestDrain (4.48s)
panic: runtime error: invalid memory address or nil pointer dereference [recovered, repanicked]
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x1b7e3e0]

goroutine 17366 [running]:
testing.tRunner.func1.2({0x5443000, 0xabc2b40})
	GOROOT/src/testing/testing.go:1872 +0x190
testing.tRunner.func1()
	GOROOT/src/testing/testing.go:1875 +0x31c
panic({0x5443000?, 0xabc2b40?})
	GOROOT/src/runtime/panic.go:783 +0x120
github.com/cockroachdb/cockroach/pkg/util/grpcutil.IsClosedConnection({0x0, 0x0})
	pkg/util/grpcutil/grpc_util.go:94 +0xf0
github.com/cockroachdb/cockroach/pkg/server_test.doTestDrain.func3()
	pkg/server/drain_test.go:130 +0x6c
github.com/cockroachdb/cockroach/pkg/testutils.SucceedsWithinError.func1()
	pkg/testutils/soon.go:95 +0x38
github.com/cockroachdb/cockroach/pkg/util/retry.ForDuration(0xa7a358200, 0x400375fd30)
	pkg/util/retry/retry.go:362 +0xbc
github.com/cockroachdb/cockroach/pkg/testutils.SucceedsWithinError(0x400359fec0, 0xa7a358200)
	pkg/testutils/soon.go:101 +0x4c
github.com/cockroachdb/cockroach/pkg/testutils.SucceedsWithin({0x6dbf030, 0x4001cff2f0}, 0x400359fec0, 0xa7a358200)
	pkg/testutils/soon.go:63 +0x44
github.com/cockroachdb/cockroach/pkg/testutils.SucceedsSoon({0x6dbf030, 0x4001cff2f0}, 0x400359fec0)
	pkg/testutils/soon.go:42 +0x4c
github.com/cockroachdb/cockroach/pkg/server_test.doTestDrain(0x4011d5ac40, 0x0)
	pkg/server/drain_test.go:128 +0x304
github.com/cockroachdb/cockroach/pkg/server_test.TestDrain.func1(0x4016bbef58?, 0xac?)
	pkg/server/drain_test.go:40 +0x1c
github.com/cockroachdb/cockroach/pkg/testutils.RunValues[...].func1()
	pkg/testutils/subtest.go:23 +0x28
testing.tRunner(0x4011d5ac40, 0x401dc290e0)
	GOROOT/src/testing/testing.go:1934 +0xc8
created by testing.(*T).Run in goroutine 17361
	GOROOT/src/testing/testing.go:1997 +0x364
=== RUN   TestDrain/secondaryTenants=false
    test_server_shim.go:638: DRPC is enabled (via testserver factory defaults)
    drain_test.go:105: drain response: is_draining:true 
--- FAIL: TestDrain/secondaryTenants=false (4.48s)
```
<details><summary>Help</summary>
<p>

See also: [How To Investigate a Go Test Failure \(internal\)](https://cockroachlabs.atlassian.net/l/c/HgfXfJgM)
</p>
</details>
/cc @cockroachdb/kv-triage @cockroachdb/sql-foundations
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*TestDrain.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/bazci/githubpost/issues)

</sub>

Jira issue: CRDB-61358

### LINKED ISSUE #166117: release-26.2: server: TestDrain failed
server.TestDrain [failed](https://mesolite.cluster.engflow.com/invocations/default/b822ed37-6521-4d03-9e35-998695351fbc?testReportRun=1&testReportShard=11&testReportAttempt=1#targets-Ly9wa2cvc2VydmVyOnNlcnZlcl90ZXN0) on release-26.2 @ [e45d572891ae68c6a062b8f85cbeaa6f51a22e92](https://github.com/cockroachdb/cockroach/commits/e45d572891ae68c6a062b8f85cbeaa6f51a22e92):

Fatal error:

```
panic: runtime error: invalid memory address or nil pointer dereference [recovered, repanicked]
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x1e9182a]

```
Stack: 

```
goroutine 14871 [running]:
testing.tRunner.func1.2({0x6236720, 0xbe14080})
	GOROOT/src/testing/testing.go:1872 +0x237
testing.tRunner.func1()
	GOROOT/src/testing/testing.go:1875 +0x35b
panic({0x6236720?, 0xbe14080?})
	GOROOT/src/runtime/panic.go:783 +0x132
github.com/cockroachdb/cockroach/pkg/util/grpcutil.IsClosedConnection({0x0, 0x0})
	pkg/util/grpcutil/grpc_util.go:94 +0xea
github.com/cockroachdb/cockroach/pkg/server_test.doTestDrain.func3()
	pkg/server/drain_test.go:130 +0x65
github.com/cockroachdb/cockroach/pkg/testutils.SucceedsWithinError.func1()
	pkg/testutils/soon.go:76 +0x42
github.com/cockroachdb/cockroach/pkg/util/retry.ForDuration(0xa7a358200, 0xc002a8fd40)
	pkg/util/retry/retry.go:362 +0xbe
github.com/cockroachdb/cockroach/pkg/testutils.SucceedsWithinError(0xc019153ec8, 0xa7a358200)
	pkg/testutils/soon.go:82 +0x56
github.com/cockroachdb/cockroach/pkg/testutils.SucceedsWithin({0x7c29930, 0xc01f3c5410}, 0xc019153ec8, 0xa7a358200)
	pkg/testutils/soon.go:59 +0x58
github.com/cockroachdb/cockroach/pkg/testutils.SucceedsSoon({0x7c29930, 0xc01f3c5410}, 0xc019153ec8)
	pkg/testutils/soon.go:38 +0x45
github.com/cockroachdb/cockroach/pkg/server_test.doTestDrain(0xc013794a80, 0x0)
	pkg/server/drain_test.go:128 +0x3b6
github.com/cockroachdb/cockroach/pkg/server_test.TestDrain.func1(0x5d1ed3?, 0x53?)
	pkg/server/drain_test.go:40 +0x13
github.com/cockroachdb/cockroach/pkg/testutils.RunValues[...].func1()
	pkg/testutils/subtest.go:23 +0x1b
testing.tRunner(0xc013794a80, 0xc013beb220)
	GOROOT/src/testing/testing.go:1934 +0xea
created by testing.(*T).Run in goroutine 14866
	GOROOT/src/testing/testing.go:1997 +0x465
```
<details><summary>Log preceding fatal error</summary>
<p>

```
=== RUN   TestDrain
    test_log_scope.go:172: test logs captured to: outputs.zip/logTestDrain172011007
    test_log_scope.go:82: use -show-logs to present logs inline
--- FAIL: TestDrain (24.22s)
```
</p>
</details>

Parameters:
 - <code>attempt=1</code>
 - <code>run=1</code>
 - <code>shard=11</code>
<details><summary>Help</summary>
<p>

See also: [How To Investigate a Go Test Failure \(internal\)](https://cockroachlabs.atlassian.net/l/c/HgfXfJgM)
</p>
</details>
/cc @cockroachdb/kv-triage @cockroachdb/sql-foundations
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*TestDrain.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/bazci/githubpost/issues)

</sub>

Jira issue: CRDB-61751

### PR DESCRIPTION
**Pull request by Nukitt**
Previously, `grpcutil.IsClosedConnection` would panic with a nil pointer dereference when called with a nil error, because it called `err.Error()` without a nil guard. This was exposed by a race condition specific to DRPC: after server shutdown, the DRPC connection can remain alive (unlike gRPC which tears down immediately via `grpc.Stop()`), allowing `Drain()` to return a nil error during the shutdown window.

cockroachdb/drpc#36 widened this race by introducing a heap allocation (`ClosedError.New`) in the manager's stream cancellation path, slightly delaying `stream.Cancel()` and making it more likely for `CloseSend()` to complete before termination signals are set.

This change adds a nil guard to `IsClosedConnection` and a nil check in `drain_test.go` before calling it.

For more details: https://github.com/cockroachdb/cockroach/issues/165377#issuecomment-4116252691

Epic: None
Fixes: #165377
Fixes: #166117 
Release note: None

### CODE REVIEW

File: pkg/util/grpcutil/grpc_util.go [hunk 1]
```diff
@@ -80,6 +80,9 @@ func IsContextCanceled(err error) bool {
 // IsClosedConnection returns true if err's Cause is an error produced by gRPC
 // on closed connections.
 func IsClosedConnection(err error) bool {
+	if err == nil {
```
Comment (cthumuluru-crdb) [inline pkg/util/grpcutil/grpc_util.go:83]: In production code all callers of this method are already checking if the error is nil or not. While this check adds more defence towards panics, we will be running the same check twice.

**Review by cthumuluru-crdb — APPROVED** [review]
LGTM!

File: pkg/util/grpcutil/grpc_util.go (hunk 1 above)
Comment (cthumuluru-crdb) [reply pkg/util/grpcutil/grpc_util.go:83]: `IsClosedConnection()` is an exported function and so I would have liked the nil check there but since the check is being done by all the callers, maybe we can update the comment on the function to suggest error cannot be nil.

**Review by suj-krishnan — APPROVED** [review]
LGTM

File: pkg/util/grpcutil/grpc_util.go (hunk 1 above)
Comment (Nukitt) [reply pkg/util/grpcutil/grpc_util.go:83]: Resolving following our [slack thread](https://cockroachlabs.slack.com/archives/C06V95X6CVA/p1774365497519459?thread_ts=1774262929.175029&cid=C06V95X6CVA).
