### PR TITLE
Fix rocksdb prefix Seek performance.

### LINKED ISSUE #4196: Progressively degrading performance while running block writer example
I started up the [block writer](https://github.com/cockroachdb/examples-go/tree/master/block_writer) example this weekend in order to see how performance has improved since the last time I was intensely running it (several months ago).  What I discovered was a startling progressive performance degradation:

```
2016/02/07 03:19:37 88 dumps were executed at 88.0/second (0 total errors)
2016/02/07 03:19:38 905 dumps were executed at 905.0/second (0 total errors)
2016/02/07 03:19:39 663 dumps were executed at 662.2/second (0 total errors)
2016/02/07 03:19:40 548 dumps were executed at 548.6/second (0 total errors)
2016/02/07 03:19:41 453 dumps were executed at 451.3/second (0 total errors)
2016/02/07 03:19:42 411 dumps were executed at 412.1/second (0 total errors)
2016/02/07 03:19:43 397 dumps were executed at 396.2/second (0 total errors)
2016/02/07 03:19:44 377 dumps were executed at 377.7/second (0 total errors)
2016/02/07 03:19:45 327 dumps were executed at 326.9/second (0 total errors)
2016/02/07 03:19:46 321 dumps were executed at 320.7/second (0 total errors)
2016/02/07 03:19:47 314 dumps were executed at 314.2/second (0 total errors)
2016/02/07 03:19:48 280 dumps were executed at 279.2/second (0 total errors)
2016/02/07 03:19:49 271 dumps were executed at 272.3/second (0 total errors)
2016/02/07 03:19:50 261 dumps were executed at 261.0/second (0 total errors)
2016/02/07 03:19:51 246 dumps were executed at 244.8/second (0 total errors)
2016/02/07 03:19:52 235 dumps were executed at 236.1/second (0 total errors)
2016/02/07 03:19:53 222 dumps were executed at 221.5/second (0 total errors)
2016/02/07 03:19:54 211 dumps were executed at 211.3/second (0 total errors)
2016/02/07 03:19:55 199 dumps were executed at 199.1/second (0 total errors)
2016/02/07 03:19:56 207 dumps were executed at 207.0/second (0 total errors)
2016/02/07 03:19:57 203 dumps were executed at 203.0/second (0 total errors)
2016/02/07 03:19:58 192 dumps were executed at 192.0/second (0 total errors)
```

After the example starts running, performance begins quickly and permanently degrading - eventually it seems to level off at around 30 dumps (inserts) per second, representing a 97% reduction in throughput.  

Notably, *restarting the block writer causes this phenomena to reset*: it returns to its peak around 900 inserts/s, then degrades in the same fashion.

### Experiments
I ran this tool in a number of experimental configurations trying to narrow down the problem:
* I ran the test with six nodes, three nodes, and finally on a single node cluster.  The problem is present even on a single node, which eliminated replication traffic as the culprit.
* In order to see if the block writer itself was at fault, I reconfigured the example to run against postgres; postgres had no degradation and write load was very steady (at  ~3700 inserts/s). Thus, the block writer itself was not the problem.
* Because restarting the block writer "reset" the problem, my first theory is that there was some bug with the SQL session itself that caused it to slow down over time; thus, I modified the block writer to occasionally force-close all SQL connections.  However, the performance profile persisted even with a new connection.
* My next theory was that the performance was related to the size of the table: block writer deletes the existing block table whenever it starts up.  I disabled this, and found my first real clue; if the table is not deleted, the performance _remains degraded_ even after restarting the block writer.
* Next, I wanted to see if this problem persisted even if CockroachDB was reset.  I stopped the single cockroach node and restarted it, preserving the existing tables.  *This resets the performance degredation*.
* Finally, I tried changing the table being written to by the block writer; the performance problem resets every time a new table is selected, but returns when switching back to a table which was already degraded. The degradation appears to affect each table independently.

### Summary of the Issue
I believe I have narrowed down the scope of the issue: subsequent inserts to the same table on the same running CockroachDB node will progressively degrade in performance. The performance degradation affects each table independently, and the degradation is reset if CockroachDB is restarted.

Unfortunately, I am having quite a lot of trouble profiling CockroachDB using pprof, which is probably a separate issue; therefore, I am throwing this issue to the team for now, hoping that someone has an idea of what could be causing it.

@tschottdorf

### PR DESCRIPTION
**Pull request by petermattis**
Set ReadOptions.iterate_upper_bound when creating "prefix"
iterators. This avoids pathological performance when seeking into a
rocksdb MemTable which contains large expanses of deletion tombstones.

Added a benchmark which demonstrates the pathological performance of the
old code.

```
name             old time/op  new time/op  delta
MVCCPutDelete-8   185µs ± 8%    11µs ± 3%  -94.11%  (p=0.000 n=10+10)
```

Fixes #4196.

[Review on Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/4319)

### CODE REVIEW

**Comment by dt** [comment]
This will probably need a quick rebase since #4308 merged

---

Review status: 0 of 11 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4319#-:-KAFoOtTZIXrou-W2Yzj:1443817364)*

File: storage/engine/rocksdb/db.cc [hunk 1]
```diff
@@ -1418,15 +1425,35 @@ DBIterator* DBBatch::NewIter(bool prefix) {
...
 }
 
-DBIterator* DBNewIter(DBEngine* db, bool prefix) {
+DBIterator::DBIterator(DBSlice prefix)
+    : upper_bound_ptr(NULL) {
+  if (prefix.len > 0) {
+    // When we're performing a prefix scan, we want to limit the scan
+    // to the keys that have the matching prefix. Prefix in this case
+    // refers to an exact match on the non-timestamp portion of a
+    // key. We do this be constructing an encoded mvcc key which has a
```
Comment (tschottdorf) [inline storage/engine/rocksdb/db.cc]: s/be/by/

File: storage/engine/rocksdb/db.cc [hunk 2]
```diff
@@ -1418,15 +1425,35 @@ DBIterator* DBBatch::NewIter(bool prefix) {
...
+    // zero timestamp (hence the trailing 0) and is the "next" key
+    // (thus the additional 0). See EncodeKey and SplitKey for more
```
Comment (tschottdorf) [inline storage/engine/rocksdb/db.cc]: where can I find these functions? Can this ad-hoc encoding move to a location closer to other encoding stuff?

File: storage/engine/rocksdb/db.cc [hunk 3]
```diff
@@ -1418,15 +1425,35 @@ DBIterator* DBBatch::NewIter(bool prefix) {
...
+    // details on the encoded key format.
+    upper_bound_str.reserve(prefix.len + 2);
+    upper_bound_str.append(prefix.data, prefix.len);
+    upper_bound_str.push_back(0);
+    upper_bound_str.push_back(0);
+    upper_bound = upper_bound_str;
```
Comment (tschottdorf) [inline storage/engine/rocksdb/db.cc]: why do you need both fields on `DBIterator`?

File: storage/engine/rocksdb/db.h [hunk 4]
```diff
@@ -118,12 +118,13 @@ DBEngine* DBNewSnapshot(DBEngine* db);
...
-// user-key prefix of the supplied MVCC key to restrict which sstables are
-// searched, but iteration (using Next) over keys without the same user-key
-// prefix will not work correctly (keys may be skipped). It is the callers
-// responsibility to call DBIterDestroy().
-DBIterator* DBNewIter(DBEngine* db, bool prefix);
+// Creates a new database iterator. When prefix is not empty, Seek
+// will use the user-key prefix of the supplied MVCC key to restrict
+// which sstables are searched, but iteration (using Next) over keys
+// without the same user-key prefix will not work correctly (keys may
+// be skipped). It is the callers responsibility to call
```
Comment (tschottdorf) [inline storage/engine/rocksdb/db.h]: s/callers/caller's/

File: storage/engine/rocksdb/db.cc (hunk 3 above)
Comment (petermattis) [inline storage/engine/rocksdb/db.cc]: I don't, but it makes setting `iterate_upper_bound` in the options more convenient.

File: storage/engine/rocksdb/db.cc (hunk 2 above)
Comment (petermattis) [inline storage/engine/rocksdb/db.cc]: They are elsewhere in this file. Yeah, I can move this encoding next to those routines.

File: storage/engine/rocksdb/db.cc (hunk 1 above)
Comment (petermattis) [inline storage/engine/rocksdb/db.cc]: Done.

File: storage/engine/rocksdb_test.go [hunk 5]
```diff
@@ -592,3 +592,30 @@ func BenchmarkMVCCComputeStats1Version32Bytes(b *testing.B) {
...
+	zeroTS := roachpb.ZeroTimestamp
+	var blockNum int64
+
+	for i := 0; i < b.N; i++ {
+		blockID := r.Int63()
+		blockNum++
+		key := encoding.EncodeVarintAscending(nil, blockID)
+		key = encoding.EncodeVarintAscending(key, blockNum)
+
+		if err := MVCCPut(rocksdb, nil, key, zeroTS, value, txn1); err != nil {
```
Comment (tschottdorf) [inline storage/engine/rocksdb_test.go]: what's with the `txn1` here? Shouldn't you get a `WriteIntentError` on the `MVCCDelete` which you carry out w/o Txn?

File: storage/engine/rocksdb/db.cc (hunk 3 above)
Comment (petermattis) [inline storage/engine/rocksdb/db.cc]: Turned out to not be too difficult to remove. Done.

File: storage/engine/rocksdb/db.h (hunk 4 above)
Comment (petermattis) [inline storage/engine/rocksdb/db.h]: Done. And elsewhere in this file.

File: storage/engine/rocksdb_test.go (hunk 5 above)
Comment (petermattis) [inline storage/engine/rocksdb_test.go]: Hmm, not sure what is going on there. The `txn1` certainly isn't necessary. This test evolved over the course of debugging and I was originally resolving the write intents.

**Comment by petermattis** [comment]
This PR also has a big impact on the `{Update,Delete}1` benchmarks. Presumably they were also encountering the same performance degradation. 

```
name                   old time/op    new time/op    delta
Insert1_Cockroach-8       312µs ± 1%     317µs ± 2%   +1.58%         (p=0.001 n=9+10)
Insert10_Cockroach-8      597µs ± 2%     590µs ± 2%   -1.07%        (p=0.043 n=10+10)
Insert100_Cockroach-8    3.14ms ± 1%    3.06ms ± 1%   -2.57%         (p=0.000 n=9+10)
Update1_Cockroach-8       752µs ± 1%     602µs ± 1%  -19.92%        (p=0.000 n=10+10)
Update10_Cockroach-8     3.51ms ± 1%    3.55ms ± 1%   +1.00%        (p=0.000 n=10+10)
Update100_Cockroach-8    31.0ms ± 1%    31.6ms ± 1%   +1.93%         (p=0.000 n=10+8)
Delete1_Cockroach-8      1.04ms ±13%    0.61ms ± 1%  -40.70%         (p=0.000 n=10+9)
Delete10_Cockroach-8     1.50ms ± 9%    1.26ms ± 1%  -16.40%        (p=0.000 n=10+10)
Delete100_Cockroach-8    6.46ms ± 1%    6.61ms ± 2%   +2.29%         (p=0.000 n=9+10)
Scan1_Cockroach-8         135µs ± 1%     135µs ± 1%     ~           (p=0.315 n=10+10)
Scan10_Cockroach-8        166µs ± 2%     167µs ± 1%   +0.82%         (p=0.013 n=10+9)
Scan100_Cockroach-8       421µs ± 2%     431µs ± 2%   +2.40%        (p=0.005 n=10+10)
```

File: storage/engine/rocksdb_test.go (hunk 5 above)
Comment (tschottdorf) [inline storage/engine/rocksdb_test.go]: Is `txn1` non-nil? If so, I'd like to understand why there isn't a `WriteIntentError` after.

**Comment by petermattis** [comment]
Not sure what is up with the circleci failure. I did notice that an unrelated changed had snuck into my `GLOCKFILE`. Perhaps that was it.

Anyone want to stamp this with an LGTM?

**Comment by tschottdorf** [comment]
LGTM. I hope you've seen Igor's comment which was on a commit that you've since replaced.

**Comment by tschottdorf** [comment]
Reviewed 4 of 11 files at r1, 6 of 7 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[storage/engine/rocksdb_test.go, line 614 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4319#-KAFjXC4YePWHJSqPgEf-r1-614:-KAGdRqrtx0yLA1AAf7Q:-1755922353) ([raw file](https://github.com/cockroachdb/cockroach/blob/fd0685552d5b00660ae4a49fc7bee7a052bfdd68/storage/engine/rocksdb_test.go#L614)):*
Still feels funny that this worked. Put a TODO for me please (I'm assuming you don't want to take 5 and figure it out).

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4319)*

**Comment by petermattis** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[storage/engine/rocksdb_test.go, line 614 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4319#-KAFjXC4YePWHJSqPgEf-r1-614:-KAGfHbe0bmeR7BQb7fK:2016351573) ([raw file](https://github.com/cockroachdb/cockroach/blob/fd0685552d5b00660ae4a49fc7bee7a052bfdd68/storage/engine/rocksdb_test.go#L614)):*
The `txn` parameter is ignored if the timestamp is "zero". Changing to a non-zero timestamp and we see the error you expect.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4319)*

**Comment by tschottdorf** [comment]
Gotcha. I may rest in piece. Thanks for looking.

**Comment by bdarnell** [comment]
The unrelated `GLOCKFILE` change is because the docker API has a dependency hidden behind a build tag that `glock save` can't see (#4282). For now it is only safe to run `glock save` from linux (`build/builder.sh glock save` will work); if you run it from a mac you'll have to manually tweak the output.

**Comment by tamird** [comment]
See https://github.com/robfig/glock/issues/29
