### PR TITLE
sql/sem/builtins: deflake TestGenerateUniqueUnorderedIDOrder

### LINKED ISSUE #108668: sql/sem/builtins: TestGenerateUniqueUnorderedIDOrder failed
sql/sem/builtins.TestGenerateUniqueUnorderedIDOrder [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_StressBazel/11297752?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_StressBazel/11297752?buildTab=artifacts#/) on master @ [6b0f43a13c4d2b36b4da5961e523161dabe212c0](https://github.com/cockroachdb/cockroach/commits/6b0f43a13c4d2b36b4da5961e523161dabe212c0):

```
=== RUN   TestGenerateUniqueUnorderedIDOrder
    test_log_scope.go:167: test logs captured to: /artifacts/tmp/_tmp/ad72371e92981b2b572c54a0422f4d25/logTestGenerateUniqueUnorderedIDOrder567054207
    test_log_scope.go:81: use -show-logs to present logs inline
    builtins_test.go:150: swap counts: []int{314, 291, 283, 269, 305, 299, 279, 281, 277, 263, 277, 251, 256, 258, 255, 269, 289, 265, 277, 281, 265, 271, 253, 266, 248, 282, 284, 348, 292, 264, 278, 288, 278, 280, 278, 278, 242, 267, 297, 270, 284, 272, 266, 298, 264, 252, 262, 262, 294, 269, 297, 246, 276, 239, 267, 278, 280, 260, 230, 274, 290, 273, 294, 262, 250, 284, 250, 264, 279, 263, 276, 282, 318, 248, 282, 284, 348, 292, 264, 278, 288, 278, 280, 278, 278, 242, 267, 297, 270, 284, 272, 266, 298, 264, 252, 262, 262, 294, 269, 297}
    builtins_test.go:165: z-score: 1.985714
    builtins_test.go:170: there is evidence that the generated IDs are not unordered (p < 0.05)
    panic.go:522: -- test log scope end --
--- FAIL: TestGenerateUniqueUnorderedIDOrder (0.10s)
```
<p>Parameters: <code>TAGS=bazel,gss,deadlock</code>
, <code>stress=true</code>
</p>
<details><summary>Help</summary>
<p>

See also: [How To Investigate a Go Test Failure \(internal\)](https://cockroachlabs.atlassian.net/l/c/HgfXfJgM)
</p>
</details>
/cc @cockroachdb/sql-foundations
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*TestGenerateUniqueUnorderedIDOrder.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)
</sub>

### PR DESCRIPTION
**Pull request by andyyang890**
This patch deflakes TestGenerateUniqueUnorderedIDOrder by increasing the confidence level used for the statistical z-test.

Fixes #108668

Release note: None

### CODE REVIEW

File: pkg/sql/sem/builtins/builtins_test.go [hunk 1]
```diff
@@ -125,13 +126,20 @@ func TestGenerateUniqueUnorderedIDOrder(t *testing.T) {
...
-	// number of swaps. We then compare it against the critical value of +-1.96,
-	// which corresponds to a confidence level of 95%.
+	// number of swaps.
 	const (
 		numTrials       = 100
 		numGensPerTrial = 101
 	)
 
+	// We then compare it against the critical value of +-2.58,
+	// which corresponds to a confidence level of 99%.
```
Comment (rafiss) [inline pkg/sql/sem/builtins/builtins_test.go:136]: would a confidence level of 99% make this more likely to flake?

**Review by rafiss — APPROVED** [review]

File: pkg/sql/sem/builtins/builtins_test.go (hunk 1 above)
Comment (andyyang890) [reply pkg/sql/sem/builtins/builtins_test.go:136]: It would be less likely to flake since a higher confidence level means we are even more certain that the mean is different (i.e. there's a bigger margin of error allowed)

**Comment by andyyang890** [comment]
TFTR!

bors r=rafiss
