### PR TITLE
sql: revive BenchmarkTracing

### LINKED ISSUE #62081: bench: BenchmarkTracing broken on master
```
--- FAIL: BenchmarkTracing/Cockroach
    bench_test.go:429: error executing 'SET CLUSTER SETTING trace.mode = background': pq: unknown cluster setting 'trace.mode'
--- FAIL: BenchmarkTracing/MultinodeCockroach
    bench_test.go:429: error executing 'SET CLUSTER SETTING trace.mode = background': pq: unknown cluster setting 'trace.mode'
```

I'm not sure why our [nightly bench CI target](https://teamcity.cockroachdb.com/viewType.html?buildTypeId=Cockroach_UnitTests_Bench&branch_Cockroach_UnitTests=%3Cdefault%3E&tab=buildTypeStatusDiv) didn't catch this.

### PR DESCRIPTION
**Pull request by irfansharif**
Fixes #62081. It had rotted after we removed the trace.mode setting. It
now makes use of a testing knob if enabled, installs real spans all sql
statements. We'll defer the actual investigation into the cause of the
slow-down in future PRs (prototyped in #62227).

    $ make bench PKG=./pkg/bench  TESTFLAGS='-benchtime=10000x -count 20' \
        BENCHES='BenchmarkTracing' BENCHTIMEOUT=50m > benchmark-tracing.txt
    $ cat benchmark-tracing.txt | grep -v tracing=t | sed 's/tracing=f//' > old.txt
    $ cat benchmark-tracing.txt | grep -v tracing=f | sed 's/tracing=t//' > new.txt
    $ benchstat old.txt new.txt

    name                                   old time/op    new time/op    delta
    Tracing/Cockroach//Scan1-24               382µs ± 2%     412µs ± 8%   +7.68%  (p=0.000 n=10+10)
    Tracing/Cockroach//Insert-24              579µs ± 2%     609µs ± 6%   +5.10%  (p=0.000 n=10+10)
    Tracing/MultinodeCockroach//Scan1-24      799µs ± 2%     885µs ± 1%  +10.76%  (p=0.000 n=10+9)
    Tracing/MultinodeCockroach//Insert-24    1.09ms ± 1%    1.14ms ± 2%   +5.04%  (p=0.000 n=9+10)

    name                                   old alloc/op   new alloc/op   delta
    Tracing/Cockroach//Scan1-24              25.3kB ± 5%    32.0kB ± 4%  +26.55%  (p=0.000 n=10+10)
    Tracing/Cockroach//Insert-24             38.0kB ± 6%    42.2kB ± 5%  +11.02%  (p=0.000 n=10+10)
    Tracing/MultinodeCockroach//Scan1-24     77.7kB ± 8%    97.1kB ±12%  +25.05%  (p=0.000 n=10+10)
    Tracing/MultinodeCockroach//Insert-24     107kB ± 8%     115kB ± 7%   +7.66%  (p=0.023 n=10+10)

    name                                   old allocs/op  new allocs/op  delta
    Tracing/Cockroach//Scan1-24                 256 ± 1%       280 ± 1%   +9.10%  (p=0.000 n=9+9)
    Tracing/Cockroach//Insert-24                301 ± 2%       321 ± 1%   +6.64%  (p=0.000 n=10+10)
    Tracing/MultinodeCockroach//Scan1-24        787 ± 2%       921 ± 2%  +17.04%  (p=0.000 n=9+9)
    Tracing/MultinodeCockroach//Insert-24       748 ± 1%       805 ± 2%   +7.61%  (p=0.000 n=9+9)

Release note: None

### CODE REVIEW

**Comment by irfansharif** [comment]
(bump)

File: pkg/sql/exec_util.go [hunk 1]
```diff
@@ -190,6 +190,15 @@ var traceSessionEventLogEnabled = settings.RegisterBoolSetting(
 	false,
 ).WithPublic()
 
+// debugForceRealSpans can be used to force the use of real tracing spans for
+// every statement. It's used primarily to measure the tracing overhead in
+// BenchmarkTracing.
+var debugForceRealSpans = settings.RegisterBoolSetting(
```
Comment (knz) [inline pkg/sql/exec_util.go:196]: May I suggest a debug knob instead of a cluster setting. The cluster setting increases the chance that users will shoot themselves in the foot.

**Review by irfansharif — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/62118)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @knz and @tbg)

___
*[pkg/sql/exec_util.go, line 196 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/62118#-MVxa5CT0bpcI0ORexur-r1-196:-MWUO8oa5UJPBrBUMGbr:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/209b26aaa9aa9e8a771b8ec0dd109f7d408cbf6a/pkg/sql/exec_util.go#L196)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

May I suggest a debug knob instead of a cluster setting. The cluster setting increases the chance that users will shoot themselves in the foot.
</blockquote></details>

Done.

**Review by knz — APPROVED** [review]

**Comment by irfansharif** [comment]
Unrelated flakes.

bors r+
