### PR TITLE
changefeedccl: fix violation of CDC's ordering guarantees

### LINKED ISSUE #38368: teamcity: failed test: TestChangefeedNemeses [skipped]
The following tests appear to have failed on master (testrace): TestChangefeedNemeses/cloudstorage, TestChangefeedNemeses

You may want to check [for open issues](https://github.com/cockroachdb/cockroach/issues?q=is%3Aissue+is%3Aopen+TestChangefeedNemeses).

[#1354798](https://teamcity.cockroachdb.com/viewLog.html?buildId=1354798):

```
TestChangefeedNemeses
--- FAIL: testrace/TestChangefeedNemeses (40.980s)




TestChangefeedNemeses/cloudstorage
...hile adopting jobs: adopt-job: node unavailable; try another peer
E190623 17:37:44.040624 143691 jobs/registry.go:325  error while adopting jobs: adopt-job: node unavailable; try another peer
E190623 17:37:44.053103 143691 jobs/registry.go:325  error while adopting jobs: adopt-job: node unavailable; try another peer
E190623 17:37:44.065990 143691 jobs/registry.go:325  error while adopting jobs: adopt-job: node unavailable; try another peer
E190623 17:37:44.078540 143691 jobs/registry.go:325  error while adopting jobs: adopt-job: node unavailable; try another peer
E190623 17:37:44.091180 143691 jobs/registry.go:325  error while adopting jobs: adopt-job: node unavailable; try another peer
E190623 17:37:44.111396 143691 jobs/registry.go:325  error while adopting jobs: adopt-job: node unavailable; try another peer
E190623 17:37:44.123850 143691 jobs/registry.go:325  error while adopting jobs: adopt-job: node unavailable; try another peer
E190623 17:37:44.136363 143691 jobs/registry.go:325  error while adopting jobs: adopt-job: node unavailable; try another peer
E190623 17:37:44.148870 143691 jobs/registry.go:325  error while adopting jobs: adopt-job: node unavailable; try another peer
E190623 17:37:44.161273 143691 jobs/registry.go:325  error while adopting jobs: adopt-job: node unavailable; try another peer
E190623 17:37:44.173759 143691 jobs/registry.go:325  error while adopting jobs: adopt-job: node unavailable; try another peer
E190623 17:37:44.186289 143691 jobs/registry.go:325  error while adopting jobs: adopt-job: node unavailable; try another peer
E190623 17:37:44.199652 143691 jobs/registry.go:325  error while adopting jobs: adopt-job: node unavailable; try another peer
I190623 17:37:44.200110 143684 storage/queue.go:527  [n1,s1] rate limited in MaybeAdd (gc): node unavailable; try another peer
I190623 17:37:44.200277 143684 storage/queue.go:527  [n1,s1] rate limited in MaybeAdd (merge): node unavailable; try another peer
I190623 17:37:44.200393 143684 storage/queue.go:527  [n1,s1] rate limited in MaybeAdd (split): node unavailable; try another peer
I190623 17:37:44.200518 143684 storage/queue.go:527  [n1,s1] rate limited in MaybeAdd (replicate): node unavailable; try another peer
I190623 17:37:44.200676 143684 storage/queue.go:527  [n1,s1] rate limited in MaybeAdd (replicaGC): node unavailable; try another peer
I190623 17:37:44.200805 143684 storage/queue.go:527  [n1,s1] rate limited in MaybeAdd (raftlog): node unavailable; try another peer
I190623 17:37:44.200904 143684 storage/queue.go:527  [n1,s1] rate limited in MaybeAdd (raftsnapshot): node unavailable; try another peer
I190623 17:37:44.201012 143684 storage/queue.go:527  [n1,s1] rate limited in MaybeAdd (consistencyChecker): node unavailable; try another peer
I190623 17:37:44.201175 143684 storage/queue.go:527  [n1,s1] rate limited in MaybeAdd (timeSeriesMaintenance): node unavailable; try another peer
E190623 17:37:44.212163 143691 jobs/registry.go:325  error while adopting jobs: adopt-job: node unavailable; try another peer
E190623 17:37:44.224852 143691 jobs/registry.go:325  error while adopting jobs: adopt-job: node unavailable; try another peer
E190623 17:37:44.237481 143691 jobs/registry.go:325  error while adopting jobs: adopt-job: node unavailable; try another peer
E190623 17:37:44.250287 143691 jobs/registry.go:325  error while adopting jobs: adopt-job: node unavailable; try another peer
E190623 17:37:44.263378 143691 jobs/registry.go:325  error while adopting jobs: adopt-job: node unavailable; try another peer
W190623 17:37:44.263833 143676 ts/db.go:196  [n1,ts-poll] error writing time series data: node unavailable; try another peer
        nemeses_test.go:32: topic foo partition : saw new row timestamp 1561311460694418535.0000000000 after 1561311460950945674.0000000000 was seen
        nemeses_test.go:32: topic foo partition : saw new row timestamp 1561311460708480872.0000000000 after 1561311461663534533.0000000000 was seen




```

Please assign, take a look and update the issue accordingly.

### PR DESCRIPTION
**Pull request by aayushshah15**
In cloudStorageSink, we currently name output files based on the earliest
timestamps inside those files. This can sometimes muddle the ordering
of output files, leading to a violation of CDC's ordering properties

This change fixes this violation by instead using the times of the 
last `EmitRow` and `EmitResolvedTimestamp` calls to order files. This ensures
that timestamps within the output files are consumed in the same order
that they're emitted in.

Fixes: #38368

Release justification: Fixes limitation of changefeeds when using cloud storage sinks.

Release note: None

### CODE REVIEW

**Review by ajwerner — COMMENTED** [review]
This approach works but I think there's a simpler approach that will work. Instead of making the sink aware of the initial high water mark, let's instead filter any rows which might precede that high water mark. If all rows emitted from the processor come after the initial high water mark then we'll never create a file which precedes that high water mark using the existing naming rules. We know we don't need to emit those rows because we've already resolved a timestamp above them. 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/40696#-:-LoYkIcM29vhmaWyVoOr:b40htjm)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner and @nvanbenschoten)

**Review by ajwerner — APPROVED** [review]
:lgtm: 

I wonder if we should be doing the filtering at a lower level like in the poller. Let's go forward with this for now and continue to investigate why the poller is emitting rows beneath the closed timestamp in the first place. 

> Reviewed 4 of 4 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/40696#-:-LoaqKrq0o9Xsi9vTSX6:bx8g5ix)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @aayushshah15 and @nvanbenschoten)

___
*[pkg/ccl/changefeedccl/changefeed.go, line 167 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/40696#-LoaqgBgEkuZQUK-zs4h:-LoaqgBgEkuZQUK-zs4i:b-dr5akk) ([raw file](https://github.com/cockroachdb/cockroach/blob/72c869b050e9ef91bb92dda66b22c243d6c57b03/pkg/ccl/changefeedccl/changefeed.go#L167)):*
> ```Go
> 	var scratch bufalloc.ByteAllocator
> 	emitRowFn := func(ctx context.Context, row encodeRow) error {
> 		// If timestamp of the row is older than the latest resolved timestamp
> ```

It's fun that this works in the equals case because the ascii `.` is less than the ascii `_`. The wording in the docs makes me think this needs to be the condition but I would love it if we could make it `!initialHighWater.Less(row.updated)`. I haven't convinced myself that that's safe so this is fine. Maybe add a TODO to consider filtering rows equal to the `initialHighWater`
___
*[pkg/ccl/changefeedccl/changefeed_processors.go, line 124 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/40696#-LoaduLqDsaDnZS8bnPT:-LoaduLqDsaDnZS8bnPU:b3lnwb0) ([raw file](https://github.com/cockroachdb/cockroach/blob/72c869b050e9ef91bb92dda66b22c243d6c57b03/pkg/ccl/changefeedccl/changefeed_processors.go#L124)):*
> ```Go
> 	ctx = ca.StartInternal(ctx, changeAggregatorProcName)
> 
> 	initialHighWater := hlc.Timestamp{WallTime: -1}
> ```

does this code movement still need to happen?

**Review by aayushshah15 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/40696)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @ajwerner and @nvanbenschoten)

___
*[pkg/ccl/changefeedccl/changefeed.go, line 167 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/40696#-LoaqgBgEkuZQUK-zs4h:-Lob2wamAMvOFlnRPTNy:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/72c869b050e9ef91bb92dda66b22c243d6c57b03/pkg/ccl/changefeedccl/changefeed.go#L167)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

It's fun that this works in the equals case because the ascii `.` is less than the ascii `_`. The wording in the docs makes me think this needs to be the condition but I would love it if we could make it `!initialHighWater.Less(row.updated)`. I haven't convinced myself that that's safe so this is fine. Maybe add a TODO to consider filtering rows equal to the `initialHighWater`
</blockquote></details>

Done.
___
*[pkg/ccl/changefeedccl/changefeed_processors.go, line 124 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/40696#-LoaduLqDsaDnZS8bnPT:-Lob1qkR0XQA_namw9oA:bt2vr1b) ([raw file](https://github.com/cockroachdb/cockroach/blob/72c869b050e9ef91bb92dda66b22c243d6c57b03/pkg/ccl/changefeedccl/changefeed_processors.go#L124)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

does this code movement still need to happen?
</blockquote></details>

Fixed.

**Comment by aayushshah15** [comment]
I did run the nemeses against all versions of this change, so my first reaction was maybe this issue isn't as reproducible as we thought. I switched to `master` and ran `make roachprod-stressrace PKG=./pkg/ccl/changefeedccl TESTS=TestChangefeedNemeses/cloudstorage CLUSTER=$USER-stress` for about an hour (500K runs) on a 20 node cluster and couldn't reproduce it.

**Comment by ajwerner** [comment]
I fine this reproduces almost instantly with `roachprod-stress` assuming you unskip the test:

```
--- a/pkg/ccl/changefeedccl/nemeses_test.go
+++ b/pkg/ccl/changefeedccl/nemeses_test.go
@@ -34,8 +34,5 @@ func TestChangefeedNemeses(t *testing.T) {
        }
        t.Run(`sinkless`, sinklessTest(testFn))
        t.Run(`enterprise`, enterpriseTest(testFn))
-       t.Run(`cloudstorage`, func(t *testing.T) {
-               t.Skip("https://github.com/cockroachdb/cockroach/issues/38368")
-               cloudStorageTest(testFn)
-       })
+       t.Run(`cloudstorage`, cloudStorageTest(testFn))
 }
```

**Comment by aayushshah15** [comment]
> I find this reproduces almost instantly with `roachprod-stress` assuming you unskip the test:
> 
> ```
> --- a/pkg/ccl/changefeedccl/nemeses_test.go
> +++ b/pkg/ccl/changefeedccl/nemeses_test.go
> @@ -34,8 +34,5 @@ func TestChangefeedNemeses(t *testing.T) {
>         }
>         t.Run(`sinkless`, sinklessTest(testFn))
>         t.Run(`enterprise`, enterpriseTest(testFn))
> -       t.Run(`cloudstorage`, func(t *testing.T) {
> -               t.Skip("https://github.com/cockroachdb/cockroach/issues/38368")
> -               cloudStorageTest(testFn)
> -       })
> +       t.Run(`cloudstorage`, cloudStorageTest(testFn))
>  }
> ```

As discussed offline, this was due to me misunderstanding how the testing library works. I can now reproduce the issue on master.

**Comment by aayushshah15** [comment]
I updated the PR to implement the approach we briefly discussed. The updated PR description gives an overview of the idea.

The new approach keeps track of when `EmitRow` was called for each file and uses the timestamp of the last call to order files. This intuitively solves the date boundary issue we faced with previous approaches.

Additionally, it should be robust to job restarts (even in the absence of a synchronized clock). This is because the system guarantees that `updated` timestamps seen between two `resolved` timestamps will be resent in case of a failure. Thus, an inversion of our intended ordering here should not violate our user-facing guarantees.

File: pkg/ccl/changefeedccl/sink_cloudstorage.go [hunk 1]
```diff
@@ -187,10 +190,12 @@ func (s *cloudStorageSink) EmitRow(
...
 	}
-	if file.earliestTs.IsEmpty() || updated.Less(file.earliestTs) {
-		file.earliestTs = updated
-	}
 
+	// Keep track of the time of the last call to this method before a Flush.
+	// Using this timestamp in the output file names allows us to ensure that,
+	// during consumption, timestamps are consumed in the same order that they're
+	// emitted in.
+	file.lastUpdatedTs = s.clock.Now()
```
Comment (ajwerner) [inline pkg/ccl/changefeedccl/sink_cloudstorage.go]: Is there a way we can make this approach work without needing to read the clock for every single row? It seems like there should be.

**Comment by aayushshah15** [comment]
@ajwerner pointed out that this approach can't work due to unsynchronized clocks between the `changeFrontier` and `changeAggregator`s. Because of this, `%d.RESOLVED` files emitted by the `changeFrontier` can lexicographically precede files emitted by the `changeAggregator`s, which would violate our ordering guarantees. There is also an issue with high contention when using the `Clock` from `flowCtx` due to calling `Now()` for every row.

One potential way to solve this would be as follows: Have each `changeAggregator` maintain a separate local `Clock`. When the `changeAggregator`s send their resolved timestamps up to the `changeFrontier`, they also send their local clock timestamp as of the `emitEntries` call. The `changeFrontier` uses this local clock timestamp that it receives from the `changeAggregator` to name its  `%d.RESOLVED` files. This buys us monotonicity across all (`updated`, `resolved`) files emitted by the same `changeAggregator`.  This is admittedly a confusing solution.

**Comment by aayushshah15** [comment]
A second, completely separate potential approach would be this:  

 We name our `update` output files based on the least recent resolved timestamp for the `span` the row belongs to. We can use a local `spanFrontier` object to keep track of the info needed. The resolved timestamps emitted by the `changeFrontier` should be less than or equal to the span-level resolved timestamps. In any case, our naming convention should lexicographically order `%d.RESOLVED` files before other files with the same prefix.   

Date boundaries should not be a problem for this approach. However, session restarts pose a problem since `update` filenames could clash. We can however, solve this using a lease sequence number suffix in the filename.

File: pkg/ccl/changefeedccl/sink_cloudstorage.go (hunk 1 above)
Comment (aayushshah15) [reply pkg/ccl/changefeedccl/sink_cloudstorage.go]: This is doable. See following comment.

**Comment by aayushshah15** [comment]
> A second, completely separate potential approach would be this: 
> 
>  We name our `update` output files based on the least recent resolved timestamp for the `span` the row belongs to. We can use a local `spanFrontier` object to keep track of the info needed. The resolved timestamps emitted by the `changeFrontier` should be less than or equal to the span-level resolved timestamps. In any case, our naming convention should lexicographically order `%d.RESOLVED` files before other files with the same prefix.   
> 
> Date boundaries should not be a problem for this approach. However, session restarts pose a problem since `update` filenames could clash. We can however, solve this using a lease sequence number suffix in the filename.

Writing up an implementation of this.

**Comment by aayushshah15** [comment]
Update on why the `TestChangefeedNemeses/cloudstorage` test was failing:

The test works like this: it calls `noteFeedMessage` every time it sees an `eventFeedMessage` (which is simply an event triggered when an `updated` message is emitted). `noteFeedMessage` calls `cloudFeed.walkDir` to walk through and read files from a given directory in lexical order. `noteFeedMessage` populates a local queue with the output of `walkDir` and the top of the queue is popped and returned every time its called. When this local buffer is empty, it calls `walkDir` again to get it populated.

Now, `walkDir` has this block of code:
```
if strings.Compare(c.resolved, path) >= 0 {
		// Already output this in a previous walkDir.
		return nil
}
```
`c.resolved` here indicates the most recently seen resolved timestamp.
This essentially allows subsequent runs of `walkDir` to skip reading files its already read before. This works for the original approach (the one that's in `master` as of this comment's writing) since there will never be a situation where something like `1.RESOLVED` is emitted before `1.ndjson` (since we always flush before emitting a resolved timestamp).

However, in our current approach (see immediately preceding comment), this can and does happen. Since each `changeAggregator` uses the current least recent resolved timestamp to name files, it is totally possible emit a `1.RESOLVED` file and *then* start buffering into a file named `1.ndjson`. If `walkDir` is called before this `1.ndjson` file is emitted, it will record `1` in `c.resolved` and, in its next run, assume that it must have read this file and hence ignore it.

Removing that `if` block gets it to pass. Note that this is fine because its okay to see previously seen updates before.

Let me know if anything above isn't clear.

**Comment by ajwerner** [comment]
Offline discussed that the problem is data files which share a timestamp with a resolved file. It is semantically legal for the data files to come earlier but it is better if they come after. Lexically the `.` follows the `-` so a change of the first `-` in the file name to an `_` will fix the problem and lead to a better user experience.

**Review by ajwerner — CHANGES_REQUESTED** [review]
Nice! This is good and simple. I'm glad we got here. 

> Reviewed 1 of 8 files at r3, 2 of 10 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/40696#-:-LpEwrqI7a0mKpgKXQ-H:b9lxyik)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @aayushshah15, @ajwerner, and @nvanbenschoten)

___
*[pkg/ccl/changefeedccl/changefeed_processors.go, line 124 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/40696#-LpEsUxg6KflQEfT7Jnn:-LpEsUxh5S_M_XpCu9_V:b3wtpap) ([raw file](https://github.com/cockroachdb/cockroach/blob/11213521516370482c33c84b942eb0eea9e6589c/pkg/ccl/changefeedccl/changefeed_processors.go#L124)):*
> ```Go
> 	ctx = ca.StartInternal(ctx, changeAggregatorProcName)
> 
> 	initialHighWater := hlc.Timestamp{WallTime: -1}
> ```

This isn't your code but your touching it so I have comments. 

Why is this setting initialHighWater to -1. It's like it wants to use that to detect if ca.spec.Watches was empty, but why?

It seems like we should use:

```
var initialHighWater hlc.Timestamp
```
___
*[pkg/ccl/changefeedccl/changefeed_processors.go, line 125 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/40696#-LpEsZkf2yRJDPumNHtF:-LpEsZkf2yRJDPumNHtG:b-q4gh2v) ([raw file](https://github.com/cockroachdb/cockroach/blob/11213521516370482c33c84b942eb0eea9e6589c/pkg/ccl/changefeedccl/changefeed_processors.go#L125)):*
> ```Go
> 
> 	initialHighWater := hlc.Timestamp{WallTime: -1}
> 	var spans []roachpb.Span
> ```

nit: pre-allocate the span:

```
spans := make([]roachpb.Span, 0, len(ca.spec.Watches)
```
___
*[pkg/ccl/changefeedccl/changefeed_processors.go, line 128 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/40696#-LpEsheN-4CIKG049tSy:-LpEsheN-4CIKG049tSz:b69y2w0) ([raw file](https://github.com/cockroachdb/cockroach/blob/11213521516370482c33c84b942eb0eea9e6589c/pkg/ccl/changefeedccl/changefeed_processors.go#L128)):*
> ```Go
> 	for _, watch := range ca.spec.Watches {
> 		spans = append(spans, watch.Span)
> 		if initialHighWater.WallTime == -1 || watch.InitialResolved.Less(initialHighWater) {
> ```

This isn't your code but I have nits Can't you instead do:

```
initialHighWater.IsEmpty() || watch.InitialResolved.Less(initialHighWater)
```

But even more to the point, if you just initialize `initialHighWater` above then:

```
if watch.InitialResolved.Less(initialHighWater) {
    initialHighWater = watch.InitialResolved
}
```

seems fine.
___
*[pkg/ccl/changefeedccl/changefeed_processors.go, line 134 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/40696#-LpEtcVr83_kazYLJnwW:-LpEtcVr83_kazYLJnwX:b15fqyc) ([raw file](https://github.com/cockroachdb/cockroach/blob/11213521516370482c33c84b942eb0eea9e6589c/pkg/ccl/changefeedccl/changefeed_processors.go#L134)):*
> ```Go
> 
> 	// This SpanFrontier only tracks the spans being watched on this node.
> 	// (There is a different SpanFrontier elsewhere for the entire changefeed.)
> ```

No need for `(`...`)`.
___
*[pkg/ccl/changefeedccl/sink_cloudstorage.go, line 196 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/40696#-LpEunv5BLcsQ_etiKZW:-LpEunv5BLcsQ_etiKZX:b-katmz4) ([raw file](https://github.com/cockroachdb/cockroach/blob/11213521516370482c33c84b942eb0eea9e6589c/pkg/ccl/changefeedccl/sink_cloudstorage.go#L196)):*
> ```Go
> 		// careful to bound the size of the memory held by the pool.
> 		leastResolvedTs := s.sf.Frontier()
> 		if leastResolvedTs.Equal(hlc.Timestamp{}) {
> ```

Could this be simplified to:

```
if leastResolvedTs.Less(s.initialHighWater) {
```
___
*[pkg/ccl/changefeedccl/sink_cloudstorage.go, line 228 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/40696#-LpEv8VxAoDrt8K69jt8:-LpEv8VxAoDrt8K69jt9:b-vaofrb) ([raw file](https://github.com/cockroachdb/cockroach/blob/8e300bf5a6b39e80403ee9eb99d9e6256a7df4d5/pkg/ccl/changefeedccl/sink_cloudstorage.go#L228)):*
> ```Go
> 	part := resolved.GoTime().Format(s.partitionFormat)
> 	filename := fmt.Sprintf(`%s.RESOLVED`, cloudStorageFormatTime(resolved))
> 	if log.V(1) {
> ```

Please put this back. 
___
*[pkg/ccl/changefeedccl/sink_cloudstorage_test.go, line 310 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/40696#-LpEvlTx69TVkNU31OXe:-LpEvlTx69TVkNU31OXf:biqzk45) ([raw file](https://github.com/cockroachdb/cockroach/blob/11213521516370482c33c84b942eb0eea9e6589c/pkg/ccl/changefeedccl/sink_cloudstorage_test.go#L310)):*
> ```Go
> 		// The resolved timestamp file sorts after all data with that timestamp.
> 		require.NoError(t, s.EmitResolvedTimestamp(ctx, e, ts(5)))
> 		require.Equal(t, []string{
> ```

I want to make sure I understand this case. Aren't we gaurenteed to have updated our span frontier to at least `5`before we emit the the resolved timestamp 5? Should the resolved files still follow the entry with `v6`?
___
*[pkg/ccl/changefeedccl/sink_cloudstorage_test.go, line 326 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/40696#-LpEwfZ92uSmJJJaUSOd:-LpEwfZ92uSmJJJaUSOe:bu4i7v1) ([raw file](https://github.com/cockroachdb/cockroach/blob/11213521516370482c33c84b942eb0eea9e6589c/pkg/ccl/changefeedccl/sink_cloudstorage_test.go#L326)):*
> ```Go
> 			"v6\nv7\nv8\n",
> 			"v9\n",
> 			`{"resolved":"5.0000000000"}`,
> ```

Same question. 
___
*[pkg/ccl/changefeedccl/cdctest/testfeed.go, line 576 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/40696#-LpEwl6z8FA8eLF_7SJH:-LpEwl6z8FA8eLF_7SJI:blu8kmo) ([raw file](https://github.com/cockroachdb/cockroach/blob/8e300bf5a6b39e80403ee9eb99d9e6256a7df4d5/pkg/ccl/changefeedccl/cdctest/testfeed.go#L576)):*
> ```Go
> 				Resolved: e.payload,
> 			}
> ```

nit: revert.

**Review by aayushshah15 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/40696)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @aayushshah15, @ajwerner, and @nvanbenschoten)

___
*[pkg/ccl/changefeedccl/changefeed_processors.go, line 124 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/40696#-LpEsUxg6KflQEfT7Jnn:-LpFsibO1TTtG_NzI28t:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/11213521516370482c33c84b942eb0eea9e6589c/pkg/ccl/changefeedccl/changefeed_processors.go#L124)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

This isn't your code but your touching it so I have comments. 

Why is this setting initialHighWater to -1. It's like it wants to use that to detect if ca.spec.Watches was empty, but why?

It seems like we should use:

```
var initialHighWater hlc.Timestamp
```
</blockquote></details>

Done.
___
*[pkg/ccl/changefeedccl/changefeed_processors.go, line 128 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/40696#-LpEsheN-4CIKG049tSy:-LpFq9ns2FqnW2taZCa8:b13dkse) ([raw file](https://github.com/cockroachdb/cockroach/blob/11213521516370482c33c84b942eb0eea9e6589c/pkg/ccl/changefeedccl/changefeed_processors.go#L128)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

This isn't your code but I have nits Can't you instead do:

```
initialHighWater.IsEmpty() || watch.InitialResolved.Less(initialHighWater)
```

But even more to the point, if you just initialize `initialHighWater` above then:

```
if watch.InitialResolved.Less(initialHighWater) {
    initialHighWater = watch.InitialResolved
}
```

seems fine.
</blockquote></details>

Done. The `initialHighWater.IsEmpty()` condition still needs to exist, because otherwise the variable is never updated in this loop.
___
*[pkg/ccl/changefeedccl/changefeed_processors.go, line 134 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/40696#-LpEtcVr83_kazYLJnwW:-LpFs_j2Amr-Sehhe962:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/11213521516370482c33c84b942eb0eea9e6589c/pkg/ccl/changefeedccl/changefeed_processors.go#L134)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

No need for `(`...`)`.
</blockquote></details>

Done.
___
*[pkg/ccl/changefeedccl/sink_cloudstorage.go, line 196 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/40696#-LpEunv5BLcsQ_etiKZW:-LpFixCd8gwnBG8bXHEv:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/11213521516370482c33c84b942eb0eea9e6589c/pkg/ccl/changefeedccl/sink_cloudstorage.go#L196)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

Could this be simplified to:

```
if leastResolvedTs.Less(s.initialHighWater) {
```
</blockquote></details>

Done.
___
*[pkg/ccl/changefeedccl/sink_cloudstorage.go, line 228 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/40696#-LpEv8VxAoDrt8K69jt8:-LpFixes3tjDx8GyHT2U:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/8e300bf5a6b39e80403ee9eb99d9e6256a7df4d5/pkg/ccl/changefeedccl/sink_cloudstorage.go#L228)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

Please put this back. 
</blockquote></details>

Done.

**Review by aayushshah15 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/40696)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @ajwerner and @nvanbenschoten)

___
*[pkg/ccl/changefeedccl/sink_cloudstorage_test.go, line 310 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/40696#-LpEvlTx69TVkNU31OXe:-LpFx2CfCLBi285k5WfN:b-v5wv6p) ([raw file](https://github.com/cockroachdb/cockroach/blob/11213521516370482c33c84b942eb0eea9e6589c/pkg/ccl/changefeedccl/sink_cloudstorage_test.go#L310)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

I want to make sure I understand this case. Aren't we gaurenteed to have updated our span frontier to at least `5`before we emit the the resolved timestamp 5? Should the resolved files still follow the entry with `v6`?
</blockquote></details>

In the present form of the test, the resolved file should succeed the data files since we haven't manually `Forward`ed the spanFrontier. But you're right that this isn't representative of what would actually happen. I updated the test to forward to a ts >= 5 in order to ensure that the files created after that point follow the resolved file created at ts 5.
___
*[pkg/ccl/changefeedccl/sink_cloudstorage_test.go, line 326 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/40696#-LpEwfZ92uSmJJJaUSOd:-LpG2Efc2aqTmNUbrkse:b-7pi2ou) ([raw file](https://github.com/cockroachdb/cockroach/blob/11213521516370482c33c84b942eb0eea9e6589c/pkg/ccl/changefeedccl/sink_cloudstorage_test.go#L326)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

Same question. 
</blockquote></details>

Fixed, see comment above.

**Review by aayushshah15 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/40696)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @ajwerner and @nvanbenschoten)

___
*[pkg/ccl/changefeedccl/cdctest/nemeses.go, line 64 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/40696#-LpG3NNm5ki7IjNnMOCI:-LpG3NNm5ki7IjNnMOCJ:b-dv3p86) ([raw file](https://github.com/cockroachdb/cockroach/blob/b8fea83a0df4577ca7c8e4d08eb3eef2780f16f6/pkg/ccl/changefeedccl/cdctest/nemeses.go#L64)):*
> ```Go
> 			// any deadlocks after stress-racing for over 10K runs. So uncommenting
> 			// for now.
> 			eventPause{}: 10,
> ```

I ran this with a `TESTTIMEOUT=50s` flag and still didn't seem to have run into a deadlock. Let me know if that's what you meant in our discussion.

**Comment by aayushshah15** [comment]
bors try

**Comment by aayushshah15** [comment]
bors try

**Comment by aayushshah15** [comment]
bors try

**Comment by aayushshah15** [comment]
Not sure why bors is failing on me. Both the commit message and PR desc contain the release justification.

**Review by ajwerner — CHANGES_REQUESTED** [review]
> Reviewed 1 of 5 files at r5.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/40696)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @aayushshah15, @ajwerner, and @nvanbenschoten)

___
*[pkg/ccl/changefeedccl/bench_test.go, line 221 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/40696#-LpZXO2bBCn48jLB9Ns6:-LpZXO2c5J5cWdLwSOmI:b-6n6dlf) ([raw file](https://github.com/cockroachdb/cockroach/blob/238b7d19a46dce876bd263725752a54bda55a4f6/pkg/ccl/changefeedccl/bench_test.go#L221)):*
> ```Go
> 	}
> 	rowsFn := kvsToRows(s.LeaseManager().(*sql.LeaseManager), details, buf.Get)
> 	watchedSF := makeSpanFrontier()
> ```

given we know `spans` should we pass them to `makeSpanFrontier`?
___
*[pkg/ccl/changefeedccl/changefeed_processors.go, line 134 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/40696#-LpEtcVr83_kazYLJnwW:-LpJnVqS6XjZuargnRHf:bulygo3) ([raw file](https://github.com/cockroachdb/cockroach/blob/11213521516370482c33c84b942eb0eea9e6589c/pkg/ccl/changefeedccl/changefeed_processors.go#L134)):*
<details><summary><i>Previously, aayushshah15 (Aayush Shah) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Is it?
___
*[pkg/ccl/changefeedccl/changefeed_stmt.go, line 214 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/40696#-LpZWt0f45Pl69dPnfBH:-LpZWt0f45Pl69dPnfBI:bqtw1xq) ([raw file](https://github.com/cockroachdb/cockroach/blob/238b7d19a46dce876bd263725752a54bda55a4f6/pkg/ccl/changefeedccl/changefeed_stmt.go#L214)):*
> ```Go
> 		}
> 
> 		sessionID := uuid.FastMakeV4()
> ```

I'm not all that keen on using a full v4 uuid here. For one, its string reprentation contains `-` characters and for two it's gigantic regardless. I think we can convince ourselves that 8 bytes is plenty. 
___
*[pkg/ccl/changefeedccl/sink_cloudstorage.go, line 228 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/40696#-LpEv8VxAoDrt8K69jt8:-LpZWZFo9qC6uvK9Gqhw:bulygo3) ([raw file](https://github.com/cockroachdb/cockroach/blob/8e300bf5a6b39e80403ee9eb99d9e6256a7df4d5/pkg/ccl/changefeedccl/sink_cloudstorage.go#L228)):*
<details><summary><i>Previously, aayushshah15 (Aayush Shah) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Is it?
___
*[pkg/jobs/jobspb/jobs.proto, line 206 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/40696#-LpZWmka81RPRQPLgaCT:-LpZWmka81RPRQPLgaCU:bitv6n3) ([raw file](https://github.com/cockroachdb/cockroach/blob/238b7d19a46dce876bd263725752a54bda55a4f6/pkg/jobs/jobspb/jobs.proto#L206)):*
> ```protobuf
>   map<string, string> opts = 4;
>   util.hlc.Timestamp statement_time = 7 [(gogoproto.nullable) = false];
>   string session_id = 8 [(gogoproto.customname) = "SessionID"];
> ```

Please add commentary on what this is and why it's used.

**Review by aayushshah15 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/40696)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @ajwerner and @nvanbenschoten)

___
*[pkg/ccl/changefeedccl/bench_test.go, line 221 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/40696#-LpZXO2bBCn48jLB9Ns6:-LpZfcg2-QUtutK4mXsO:b-2egyz3) ([raw file](https://github.com/cockroachdb/cockroach/blob/238b7d19a46dce876bd263725752a54bda55a4f6/pkg/ccl/changefeedccl/bench_test.go#L221)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

given we know `spans` should we pass them to `makeSpanFrontier`?
</blockquote></details>

Done. The reason this didn't cause issues with the test is because `benchSink` doesn't use it at all.
___
*[pkg/ccl/changefeedccl/changefeed_processors.go, line 134 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/40696#-LpEtcVr83_kazYLJnwW:-LpZgi6O4wz-rTdRLEJA:b181a1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/11213521516370482c33c84b942eb0eea9e6589c/pkg/ccl/changefeedccl/changefeed_processors.go#L134)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

Is it?
</blockquote></details>

Fixed now. 
___
*[pkg/ccl/changefeedccl/changefeed_stmt.go, line 214 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/40696#-LpZWt0f45Pl69dPnfBH:-LpZtPlQDe_GtI-Hxpq5:bs7wumx) ([raw file](https://github.com/cockroachdb/cockroach/blob/238b7d19a46dce876bd263725752a54bda55a4f6/pkg/ccl/changefeedccl/changefeed_stmt.go#L214)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

I'm not all that keen on using a full v4 uuid here. For one, its string reprentation contains `-` characters and for two it's gigantic regardless. I think we can convince ourselves that 8 bytes is plenty. 
</blockquote></details>

Done. 
___
*[pkg/ccl/changefeedccl/sink_cloudstorage.go, line 228 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/40696#-LpEv8VxAoDrt8K69jt8:-LpZdWBD7sQ6GHqcv_LM:b-mctwez) ([raw file](https://github.com/cockroachdb/cockroach/blob/8e300bf5a6b39e80403ee9eb99d9e6256a7df4d5/pkg/ccl/changefeedccl/sink_cloudstorage.go#L228)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

Is it?
</blockquote></details>

Oops, must've mistakenly reverted it with other changes. Fixed now. 
___
*[pkg/jobs/jobspb/jobs.proto, line 206 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/40696#-LpZWmka81RPRQPLgaCT:-LpZdxOy7rcqenH8f6mG:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/238b7d19a46dce876bd263725752a54bda55a4f6/pkg/jobs/jobspb/jobs.proto#L206)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

Please add commentary on what this is and why it's used.
</blockquote></details>

Done.

**Review by danhhz — COMMENTED** [review]
here's some mostly superficial comments. i'd like to take another pass after you address the one i left about updating the comment on `cloudStorageSink`

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/40696#-:-Lp_3BKRAhLxybrIduox:b-2asvw0)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @aayushshah15, @ajwerner, and @nvanbenschoten)

___
*[pkg/ccl/changefeedccl/bench_test.go, line 221 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/40696#-Lp_02WoBA5aWbEgdoMG:-Lp_02WoBA5aWbEgdoMH:b-s158io) ([raw file](https://github.com/cockroachdb/cockroach/blob/0458d1b6d95a97164204dd25256fb22f19c285b0/pkg/ccl/changefeedccl/bench_test.go#L221)):*
> ```Go
> 	}
> 	rowsFn := kvsToRows(s.LeaseManager().(*sql.LeaseManager), details, buf.Get)
> 	watchedSF := makeSpanFrontier(spans...)
> ```

nit: call this `sf` instead of `watchedSF` to match the other ones. here and elsewhere
___
*[pkg/ccl/changefeedccl/changefeed_stmt.go, line 13 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/40696#-Lp_0LFUBZWH8wlYvLdo:-Lp_0LFVElRQaqdSKLX9:bkhi6cf) ([raw file](https://github.com/cockroachdb/cockroach/blob/0458d1b6d95a97164204dd25256fb22f19c285b0/pkg/ccl/changefeedccl/changefeed_stmt.go#L13)):*
> ```Go
> import (
> 	"context"
> 	"crypto/rand"
> ```

crypto/rand instead of math/rand? is this intentional? if so, please add a comment justifying it
___
*[pkg/ccl/changefeedccl/sink_cloudstorage.go, line 59 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/40696#-Lp_1U679dpoREv0ku8M:-Lp_1U679dpoREv0ku8N:b-3p8t33) ([raw file](https://github.com/cockroachdb/cockroach/blob/0458d1b6d95a97164204dd25256fb22f19c285b0/pkg/ccl/changefeedccl/sink_cloudstorage.go#L59)):*
> ```Go
> }
> 
> // cloudStorageSink emits to files on cloud storage.
> ```

this comment is out of date now, please update the parts that have rotted ("_" vs "-") and also add a big section on how the correctness of all of this works while you have it all loaded up in your head
___
*[pkg/ccl/changefeedccl/sink_cloudstorage.go, line 196 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/40696#-Lp_10T-D6IL5sgFglDU:-Lp_10T-D6IL5sgFglDV:blp871c) ([raw file](https://github.com/cockroachdb/cockroach/blob/0458d1b6d95a97164204dd25256fb22f19c285b0/pkg/ccl/changefeedccl/sink_cloudstorage.go#L196)):*
> ```Go
> 		// We could pool the bytes.Buffers if necessary, but we'd need to be
> 		// careful to bound the size of the memory held by the pool.
> 		leastResolvedTs := s.sf.Frontier()
> ```

nit: this is called "frontier" everywhere else, lets be consistent here
___
*[pkg/ccl/changefeedccl/sink_cloudstorage.go, line 198 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/40696#-Lp_1H3LCzgS7F4VkF5S:-Lp_1H3LCzgS7F4VkF5T:bf5gaac) ([raw file](https://github.com/cockroachdb/cockroach/blob/0458d1b6d95a97164204dd25256fb22f19c285b0/pkg/ccl/changefeedccl/sink_cloudstorage.go#L198)):*
> ```Go
> 		leastResolvedTs := s.sf.Frontier()
> 		if leastResolvedTs.Less(s.initialHighWater) {
> 			// This condition being true indicates that this is a new job that
> ```

"new job" is a little misleading here since the phase before the first resolved timestamps (the "initial scan") can actually be quite long
___
*[pkg/ccl/changefeedccl/sink_cloudstorage_test.go, line 113 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/40696#-Lp_1xSd7eCk9rcr1FFJ:-Lp_1xSeDJFNJktYkU-3:baxqrrz) ([raw file](https://github.com/cockroachdb/cockroach/blob/0458d1b6d95a97164204dd25256fb22f19c285b0/pkg/ccl/changefeedccl/sink_cloudstorage_test.go#L113)):*
> ```Go
> 
> 		// Emitting rows and flushing should write them out in one file per table.
> 		var rows = []struct {
> ```

nit: this doesn't get you anything over the way it was before and it's harder to read
___
*[pkg/ccl/changefeedccl/sink_cloudstorage_test.go, line 147 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/40696#-Lp_264k7RA4vsXhOS_7:-Lp_264k7RA4vsXhOS_8:b-lar1fd) ([raw file](https://github.com/cockroachdb/cockroach/blob/0458d1b6d95a97164204dd25256fb22f19c285b0/pkg/ccl/changefeedccl/sink_cloudstorage_test.go#L147)):*
> ```Go
> 		// Flush and now it does.
> 		// Note that rows with table descriptor t2 should be read after rows
> 		// with table descriptor t1.
> ```

why is this true now? potentially something to include in the comment update i asked for above

**Review by ajwerner — COMMENTED** [review]
> Reviewed 4 of 7 files at r8.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/40696)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @aayushshah15, @ajwerner, and @nvanbenschoten)

___
*[pkg/ccl/changefeedccl/changefeed.go, line 167 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/40696#-LpaPQ3b3UupHXEbtaIF:-LpaPQ3c5flrSwCxHWoh:bwoi275) ([raw file](https://github.com/cockroachdb/cockroach/blob/dd459ae566a459537a5ed1406dc196b8db577f3f/pkg/ccl/changefeedccl/changefeed.go#L167)):*
> ```Go
> 	var scratch bufalloc.ByteAllocator
> 	emitRowFn := func(ctx context.Context, row encodeRow) error {
> 		// If timestamp of the row is older than the latest resolved timestamp
> ```

How come you removed this? Is it because you moved equivalent logic into the cloudstorage sink? It's not clear that that should always live there and now other sinks don't get the benefit. Is there some equivalent, sound logic using the spanFrontier?
___
*[pkg/ccl/changefeedccl/changefeed_stmt.go, line 84 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/40696#-LpaPX66ETKpj6vxapyZ:-LpaPX66ETKpj6vxapy_:b-4116o) ([raw file](https://github.com/cockroachdb/cockroach/blob/327488b81235f7350988721e86f9abe65ee80011/pkg/ccl/changefeedccl/changefeed_stmt.go#L84)):*
> ```Go
> 	sinkParamSASLPassword     = `sasl_password`
> 
> 	uuidSizeBytes = 8
> ```

It's not a UUID anymore. Just call it a session ID and provide a comment for it. Also move it down to the constructing function. 

Let's motivate this number. Please type a comment that makes a future reader feel like 8 is a sane number of bytes.

Each new session for the same job changefeed will potentially occur at the same timestamp for its catchup scan. This ID is used to make sure that two sessions with the same timestamp don't clobber existing files. Let's assume each of these runs for 0 seconds. Sessions hold a lease for how long (figure this out), let's be conservative and say it's 1 second (it's definitely longer than this). With 8 bytes using the rough approximation of the birthday problem https://en.wikipedia.org/wiki/Birthday_problem#Square_approximation we'll have a 50% chance of a single collision after sqrt(2^64) == 2^32 ~= 4billion. So if we restart a new job every second we'll have a coin flip chance of a single collision after 136 years. With this same conservative approximation you get something like 220 days to have a .001% chance of a collision. Realistically it may be longer to adopt a job and the jobs are likely to run for longer so it's all probably fine at 8 bytes. A similar line of reasoning and you can probably convince yourself that 4 bytes is cutting it close and 16 bytes is way overkill. 
___
*[pkg/ccl/changefeedccl/changefeed_stmt.go, line 461 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/40696#-LpaPh7g2DAfUIEokwJY:-LpaPh7g2DAfUIEokwJZ:bsbmny4) ([raw file](https://github.com/cockroachdb/cockroach/blob/327488b81235f7350988721e86f9abe65ee80011/pkg/ccl/changefeedccl/changefeed_stmt.go#L461)):*
> ```Go
> }
> 
> func generateChangefeedSessionID(size int) string {
> ```

Move the const with the size down here into this method itself and add a comment to describe what this is and what it's used for. 
___
*[pkg/ccl/changefeedccl/changefeed_stmt.go, line 463 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/40696#-LpaQegrAvKoJjLGwidj:-LpaQegrAvKoJjLGwidk:b6ir1cc) ([raw file](https://github.com/cockroachdb/cockroach/blob/327488b81235f7350988721e86f9abe65ee80011/pkg/ccl/changefeedccl/changefeed_stmt.go#L463)):*
> ```Go
> func generateChangefeedSessionID(size int) string {
> 	p := make([]byte, size)
> 	buf := make([]byte, hex.EncodedLen(size))
> ```

This is totally fine. You could use strings.Builder to avoid an allocation but it doesn't matter here. 
___
*[pkg/ccl/changefeedccl/sink_cloudstorage.go, line 55 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/40696#-LpaQyg109nbbL7tgfOx:-LpaQyg109nbbL7tgfOy:b-gc2fpk) ([raw file](https://github.com/cockroachdb/cockroach/blob/327488b81235f7350988721e86f9abe65ee80011/pkg/ccl/changefeedccl/sink_cloudstorage.go#L55)):*
> ```Go
> 
> type cloudStorageSinkFile struct {
> 	frontier hlc.Timestamp
> ```

Write a brief comment explaining what this is and how it's used. 
___
*[pkg/jobs/jobspb/jobs.proto, line 206 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/40696#-LpZWmka81RPRQPLgaCT:-LpaSAWa01TTbUzqyCCH:bapsas2) ([raw file](https://github.com/cockroachdb/cockroach/blob/238b7d19a46dce876bd263725752a54bda55a4f6/pkg/jobs/jobspb/jobs.proto#L206)):*
<details><summary><i>Previously, aayushshah15 (Aayush Shah) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

It's not a UUID, it's just a unique string. UUID's are quite specific. Point the reader at the code that generates these which explains why they are what they are.

**Review by aayushshah15 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/40696)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @aayushshah15, @ajwerner, @danhhz, and @nvanbenschoten)

___
*[pkg/ccl/changefeedccl/bench_test.go, line 221 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/40696#-Lp_02WoBA5aWbEgdoMG:-Lp_LuZ35OobcghDDtw-:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/0458d1b6d95a97164204dd25256fb22f19c285b0/pkg/ccl/changefeedccl/bench_test.go#L221)):*
<details><summary><i>Previously, danhhz (Daniel Harrison) wrote…</i></summary><blockquote>

nit: call this `sf` instead of `watchedSF` to match the other ones. here and elsewhere
</blockquote></details>

Done.
___
*[pkg/ccl/changefeedccl/changefeed.go, line 167 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/40696#-LpaPQ3b3UupHXEbtaIF:-Lpdb-I23QSIvXOYoAW0:b7tb1i5) ([raw file](https://github.com/cockroachdb/cockroach/blob/dd459ae566a459537a5ed1406dc196b8db577f3f/pkg/ccl/changefeedccl/changefeed.go#L167)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

How come you removed this? Is it because you moved equivalent logic into the cloudstorage sink? It's not clear that that should always live there and now other sinks don't get the benefit. Is there some equivalent, sound logic using the spanFrontier?
</blockquote></details>

I removed it because the cloudStorageSink contained a slightly more general version of this de-duplication logic, but I didn't consider other sinks. Now, this logic only lives in `emitEntries`.  It also now uses a forwarded `spanFrontier` to make the decision.
___
*[pkg/ccl/changefeedccl/changefeed_stmt.go, line 84 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/40696#-LpaPX66ETKpj6vxapyZ:-Lpds6qd06b7GDy8xMGa:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/327488b81235f7350988721e86f9abe65ee80011/pkg/ccl/changefeedccl/changefeed_stmt.go#L84)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

It's not a UUID anymore. Just call it a session ID and provide a comment for it. Also move it down to the constructing function. 

Let's motivate this number. Please type a comment that makes a future reader feel like 8 is a sane number of bytes.

Each new session for the same job changefeed will potentially occur at the same timestamp for its catchup scan. This ID is used to make sure that two sessions with the same timestamp don't clobber existing files. Let's assume each of these runs for 0 seconds. Sessions hold a lease for how long (figure this out), let's be conservative and say it's 1 second (it's definitely longer than this). With 8 bytes using the rough approximation of the birthday problem https://en.wikipedia.org/wiki/Birthday_problem#Square_approximation we'll have a 50% chance of a single collision after sqrt(2^64) == 2^32 ~= 4billion. So if we restart a new job every second we'll have a coin flip chance of a single collision after 136 years. With this same conservative approximation you get something like 220 days to have a .001% chance of a collision. Realistically it may be longer to adopt a job and the jobs are likely to run for longer so it's all probably fine at 8 bytes. A similar line of reasoning and you can probably convince yourself that 4 bytes is cutting it close and 16 bytes is way overkill. 
</blockquote></details>

Done.
___
*[pkg/ccl/changefeedccl/changefeed_stmt.go, line 461 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/40696#-LpaPh7g2DAfUIEokwJY:-Lpds5M79n2C_SBnHMNZ:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/327488b81235f7350988721e86f9abe65ee80011/pkg/ccl/changefeedccl/changefeed_stmt.go#L461)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

Move the const with the size down here into this method itself and add a comment to describe what this is and what it's used for. 
</blockquote></details>

Done.
___
*[pkg/ccl/changefeedccl/sink_cloudstorage.go, line 59 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/40696#-Lp_1U679dpoREv0ku8M:-LpdV4iN9lS4XN8nMfkC:bwxl4l6) ([raw file](https://github.com/cockroachdb/cockroach/blob/0458d1b6d95a97164204dd25256fb22f19c285b0/pkg/ccl/changefeedccl/sink_cloudstorage.go#L59)):*
<details><summary><i>Previously, danhhz (Daniel Harrison) wrote…</i></summary><blockquote>

this comment is out of date now, please update the parts that have rotted ("_" vs "-") and also add a big section on how the correctness of all of this works while you have it all loaded up in your head
</blockquote></details>

Done, let me know if you'd like me to change any part of the updated description.
___
*[pkg/ccl/changefeedccl/sink_cloudstorage.go, line 55 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/40696#-LpaQyg109nbbL7tgfOx:-LpddCgB1uiGg31Pwnh6:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/327488b81235f7350988721e86f9abe65ee80011/pkg/ccl/changefeedccl/sink_cloudstorage.go#L55)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

Write a brief comment explaining what this is and how it's used. 
</blockquote></details>

Done.
___
*[pkg/ccl/changefeedccl/sink_cloudstorage_test.go, line 147 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/40696#-Lp_264k7RA4vsXhOS_7:-Lp_cxjiC7uO06aAtTlu:be73ewq) ([raw file](https://github.com/cockroachdb/cockroach/blob/0458d1b6d95a97164204dd25256fb22f19c285b0/pkg/ccl/changefeedccl/sink_cloudstorage_test.go#L147)):*
<details><summary><i>Previously, danhhz (Daniel Harrison) wrote…</i></summary><blockquote>

why is this true now? potentially something to include in the comment update i asked for above
</blockquote></details>

Added a better explanation, let me know if this still seems lacking.

**Review by aayushshah15 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/40696)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @ajwerner, @danhhz, and @nvanbenschoten)

___
*[pkg/ccl/changefeedccl/changefeed_stmt.go, line 463 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/40696#-LpaQegrAvKoJjLGwidj:-Lpdy0q72jcvPoHlxnN4:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/327488b81235f7350988721e86f9abe65ee80011/pkg/ccl/changefeedccl/changefeed_stmt.go#L463)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

This is totally fine. You could use strings.Builder to avoid an allocation but it doesn't matter here. 
</blockquote></details>

Done.

**Review by ajwerner — COMMENTED** [review]
Nice, my comments now are just nits. Let's wait for Dan to sign off. 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/40696#-:-LpeGOxV06kNpY0EN2Ft:b1y93k7)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @aayushshah15, @ajwerner, @danhhz, and @nvanbenschoten)

___
*[pkg/ccl/changefeedccl/changefeed.go, line 167 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/40696#-LpaPQ3b3UupHXEbtaIF:-LpeERAW82M6mz_FwSjL:b-mdznwu) ([raw file](https://github.com/cockroachdb/cockroach/blob/dd459ae566a459537a5ed1406dc196b8db577f3f/pkg/ccl/changefeedccl/changefeed.go#L167)):*
<details><summary><i>Previously, aayushshah15 (Aayush Shah) wrote…</i></summary><blockquote>

I removed it because the cloudStorageSink contained a slightly more general version of this de-duplication logic, but I didn't consider other sinks. Now, this logic only lives in `emitEntries`.  It also now uses a forwarded `spanFrontier` to make the decision.
</blockquote></details>

:raised_hands: 
___
*[pkg/ccl/changefeedccl/changefeed.go, line 153 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/40696#-LpeF0DOBNv2wVWdJupf:-LpeF0DOBNv2wVWdJupg:b-dlkhuy) ([raw file](https://github.com/cockroachdb/cockroach/blob/255e76d923818064f4979bdbd7d1e3938c765a17/pkg/ccl/changefeedccl/changefeed.go#L153)):*
> ```Go
> // emits them to the sink. It returns a closure that may be repeatedly called to
> // advance the changefeed and which returns span-level resolved timestamp
> // updates. The returned closure is not threadsafe.
> ```

Please augment this comment to describe the optimization. Something like, rows read from the inputFn which precede the Frontier of the spanFrontier will not be emitted. 
___
*[pkg/ccl/changefeedccl/changefeed_stmt.go, line 475 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/40696#-LpeGc3_BhlvUtvcAzrw:-LpeGc3a7g9G3mnaNSkp:bvcfcsw) ([raw file](https://github.com/cockroachdb/cockroach/blob/255e76d923818064f4979bdbd7d1e3938c765a17/pkg/ccl/changefeedccl/changefeed_stmt.go#L475)):*
> ```Go
> 	// single collision after 136 years. With this same approximation, we get
> 	// something like 220 days to have a 0.001% chance of a collision. In practice,
> 	// jobs are likely to run for longer and its likely to take longer for
> ```

s/its/it's/
___
*[pkg/ccl/changefeedccl/sink_cloudstorage.go, line 55 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/40696#-LpeF_XB-Vdn5SaJbNKc:-LpeF_XB-Vdn5SaJbNKd:bsmsi6z) ([raw file](https://github.com/cockroachdb/cockroach/blob/255e76d923818064f4979bdbd7d1e3938c765a17/pkg/ccl/changefeedccl/sink_cloudstorage.go#L55)):*
> ```Go
> 
> type cloudStorageSinkFile struct {
> 	// This is the least resolved timestamp being tracked by `sf`
> ```

`sf` is awkward to talk about here because it's not contextually present. 

How about something like:

```
frontier stores the least resolved timestamp being tracked by the changeAggregator writing to this file
when the file was created. It is used to name the output file such that CDC's external ordering guarantees are preserved.
See the comment on cloudStorageSink for more details.
```
___
*[pkg/ccl/changefeedccl/sink_cloudstorage.go, line 294 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/40696#-LpeGEZW230GVzsqgCFD:-LpeGEZX3jX39qlQt5kt:b1snfty) ([raw file](https://github.com/cockroachdb/cockroach/blob/255e76d923818064f4979bdbd7d1e3938c765a17/pkg/ccl/changefeedccl/sink_cloudstorage.go#L294)):*
> ```Go
> 	fileID := s.fileID
> 	s.fileID++
> 	// Pad file ID to maintain lexical ordering among files from the same sink.
> ```

12 is a lot. How big of a table does that imply?

**Comment by aayushshah15** [comment]
___
*[pkg/ccl/changefeedccl/sink_cloudstorage.go, line 294 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/40696#-LpeGEZW230GVzsqgCFD:-LpeK-zG2x56vE3bOOee:b-qzzt1z) ([raw file](https://github.com/cockroachdb/cockroach/blob/255e76d923818064f4979bdbd7d1e3938c765a17/pkg/ccl/changefeedccl/sink_cloudstorage.go#L294)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

12 is a lot. How big of a table does that imply? 
</blockquote></details>

Since we increment the same `fileID` sink-wide, this padding probably needs to be quite high. I suppose the question we need to answer is: what is the upper bound on the number of files a `cloudStorageSink` object can emit over the course of its lifetime? A trillion seems overkill but I'm not sure how to make any estimation here. One thing to note is that since files are flushed every time a resolved timestamp is emitted by `changeAggregator`,  variables like `changefeedPollInterval`(see `emitEntries` in `changefeed.go`) would affect how frequently `fileID` is incremented.

**Review by aayushshah15 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/40696)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @ajwerner, @danhhz, and @nvanbenschoten)

___
*[pkg/ccl/changefeedccl/changefeed_stmt.go, line 475 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/40696#-LpeGc3_BhlvUtvcAzrw:-LpeJGNEARGI7PQOgEwA:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/255e76d923818064f4979bdbd7d1e3938c765a17/pkg/ccl/changefeedccl/changefeed_stmt.go#L475)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

s/its/it's/
</blockquote></details>

Done.
___
*[pkg/ccl/changefeedccl/sink_cloudstorage.go, line 55 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/40696#-LpeF_XB-Vdn5SaJbNKc:-LpeIyZi4PI-IPijvBu2:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/255e76d923818064f4979bdbd7d1e3938c765a17/pkg/ccl/changefeedccl/sink_cloudstorage.go#L55)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

`sf` is awkward to talk about here because it's not contextually present. 

How about something like:

```
frontier stores the least resolved timestamp being tracked by the changeAggregator writing to this file
when the file was created. It is used to name the output file such that CDC's external ordering guarantees are preserved.
See the comment on cloudStorageSink for more details.
```
</blockquote></details>

Done.
___
*[pkg/jobs/jobspb/jobs.proto, line 206 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/40696#-LpZWmka81RPRQPLgaCT:-Lpe3cKSDyuyM9Lv2cBs:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/238b7d19a46dce876bd263725752a54bda55a4f6/pkg/jobs/jobspb/jobs.proto#L206)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

It's not a UUID, it's just a unique string. UUID's are quite specific. Point the reader at the code that generates these which explains why they are what they are. 
</blockquote></details>

Done.

**Review by danhhz — COMMENTED** [review]
sorry! i misremembered that i had finished this round of comments yesterday

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/40696#-:-Lpi72564n-b6APmuovo:b-ourfgh)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @aayushshah15, @ajwerner, @danhhz, and @nvanbenschoten)

___
*[pkg/ccl/changefeedccl/changefeed.go, line 154 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/40696#-LphzyGP4xk8hDmUUgaT:-LphzyGP4xk8hDmUUgaU:basb95q) ([raw file](https://github.com/cockroachdb/cockroach/blob/4206253e91dec8a5df6f8485bf61479715b5e2d3/pkg/ccl/changefeedccl/changefeed.go#L154)):*
> ```Go
> // advance the changefeed and which returns span-level resolved timestamp
> // updates. The returned closure is not threadsafe. Note that rows read from
> // `inputFn` which precede the Frontier of `sf` will not be emitted.
> ```

"will not be emitted because they're provably duplicates."
___
*[pkg/ccl/changefeedccl/changefeed_processors.go, line 128 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/40696#-Lpi2hQS8Lk6x9_vcJn4:-Lpi2UnE-BO_ihuOMxom:b-2sim0l) ([raw file](https://github.com/cockroachdb/cockroach/blob/4206253e91dec8a5df6f8485bf61479715b5e2d3/pkg/ccl/changefeedccl/changefeed_processors.go#L128)):*
> ```Go
> 	for _, watch := range ca.spec.Watches {
> 		spans = append(spans, watch.Span)
> 		if initialHighWater.IsEmpty() || watch.InitialResolved.Less(initialHighWater) {
> ```

I haven't finished my coffee so definitely check my thinking here, but isn't this initialHighwater computation the same as `sf.Frontier()` after we construct it below? in which case, we could avoid plumbing it down through getSink
___
*[pkg/ccl/changefeedccl/sink_cloudstorage.go, line 294 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/40696#-LpeGEZW230GVzsqgCFD:-Lpi1OoO8XB0G1C-Damq:baquocy) ([raw file](https://github.com/cockroachdb/cockroach/blob/255e76d923818064f4979bdbd7d1e3938c765a17/pkg/ccl/changefeedccl/sink_cloudstorage.go#L294)):*
<details><summary><i>Previously, aayushshah15 (Aayush Shah) wrote…</i></summary><blockquote>

Since we increment the same `fileID` sink-wide, this padding probably needs to be quite high. I suppose the question we need to answer is: what is the upper bound on the number of files a `cloudStorageSink` object can emit over the course of its lifetime? A trillion seems overkill but I'm not sure how to make any estimation here. One thing to note is that since files are flushed every time a resolved timestamp is emitted by `changeAggregator`,  variables like `changefeedPollInterval`(see `emitEntries` in `changefeed.go`) would affect how frequently `fileID` is incremented. 
</blockquote></details>

wait why do we need this?
___
*[pkg/ccl/changefeedccl/sink_cloudstorage.go, line 85 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/40696#-Lpi6rWX0ffPE_E8LHar:-Lpi6rWX0ffPE_E8LHas:bizdkv8) ([raw file](https://github.com/cockroachdb/cockroach/blob/4206253e91dec8a5df6f8485bf61479715b5e2d3/pkg/ccl/changefeedccl/sink_cloudstorage.go#L85)):*
> ```Go
> // from overwriting its own data if there are multiple changefeeds, or if a
> // changefeed gets canceled/restarted/zombied. Internally, it's generated by
> // `<node_id>_<sink_id>_<file_id>_<session_id>` where `<sink_id>` is a unique id for each
> ```

shouldn't session_id be before file_id?
___
*[pkg/ccl/changefeedccl/sink_cloudstorage.go, line 95 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/40696#-Lpi5Nl98LDPwXzT7joK:-Lpi5Nl98LDPwXzT7joL:b-2e8gld) ([raw file](https://github.com/cockroachdb/cockroach/blob/4206253e91dec8a5df6f8485bf61479715b5e2d3/pkg/ccl/changefeedccl/sink_cloudstorage.go#L95)):*
> ```Go
> //
> // This naming convention of data files is carefully chosen in order to preserve
> // the external ordering guarantees of CDC. Naming output files in this fashion
> ```

I think it's worth spelling out how this works more explicitly, I'm definitely having to think pretty hard to convince myself that these pieces line up to indeed give these guarantees. We should be nice to our future selves and write down the logic so it doesn't have to be reasoned out each time

**Review by aayushshah15 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/40696)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @ajwerner, @danhhz, and @nvanbenschoten)

___
*[pkg/ccl/changefeedccl/changefeed_processors.go, line 128 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/40696#-Lpi2hQS8Lk6x9_vcJn4:-LpnMCg5Cod99iaSgKRm:b-3x3t84) ([raw file](https://github.com/cockroachdb/cockroach/blob/4206253e91dec8a5df6f8485bf61479715b5e2d3/pkg/ccl/changefeedccl/changefeed_processors.go#L128)):*
<details><summary><i>Previously, danhhz (Daniel Harrison) wrote…</i></summary><blockquote>

I haven't finished my coffee so definitely check my thinking here, but isn't this initialHighwater computation the same as `sf.Frontier()` after we construct it below? in which case, we could avoid plumbing it down through getSink
</blockquote></details>

Ah good catch, done.
___
*[pkg/ccl/changefeedccl/sink_cloudstorage.go, line 294 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/40696#-LpeGEZW230GVzsqgCFD:-LpnMIEbBonl3RZSboPM:bp5emym) ([raw file](https://github.com/cockroachdb/cockroach/blob/255e76d923818064f4979bdbd7d1e3938c765a17/pkg/ccl/changefeedccl/sink_cloudstorage.go#L294)):*
<details><summary><i>Previously, danhhz (Daniel Harrison) wrote…</i></summary><blockquote>

wait why do we need this?
</blockquote></details>

While we probably don't need a sink-wide file ID, we need something to ensure correct ordering among files when multiple files are emitted at the same timestamp (this will happen if the file size exceeds our threshold before the local `spanFrontier` object is forwarded).
___
*[pkg/ccl/changefeedccl/sink_cloudstorage.go, line 85 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/40696#-Lpi6rWX0ffPE_E8LHar:-LpnNK8d36B0HAz7mfrk:b-o7y3t1) ([raw file](https://github.com/cockroachdb/cockroach/blob/4206253e91dec8a5df6f8485bf61479715b5e2d3/pkg/ccl/changefeedccl/sink_cloudstorage.go#L85)):*
<details><summary><i>Previously, danhhz (Daniel Harrison) wrote…</i></summary><blockquote>

shouldn't session_id be before file_id?
</blockquote></details>

I believe it doesn't matter since `sessionID` is a randomly generated string anyway. I think my explanation of the approach above will answer your question.
___
*[pkg/ccl/changefeedccl/sink_cloudstorage.go, line 95 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/40696#-Lpi5Nl98LDPwXzT7joK:-LpnMo3C7p754Lk8oRPv:b822y60) ([raw file](https://github.com/cockroachdb/cockroach/blob/4206253e91dec8a5df6f8485bf61479715b5e2d3/pkg/ccl/changefeedccl/sink_cloudstorage.go#L95)):*
<details><summary><i>Previously, danhhz (Daniel Harrison) wrote…</i></summary><blockquote>

I think it's worth spelling out how this works more explicitly, I'm definitely having to think pretty hard to convince myself that these pieces line up to indeed give these guarantees. We should be nice to our future selves and write down the logic so it doesn't have to be reasoned out each time
</blockquote></details>

I added a more descriptive section that explains it the way I convinced myself of its correctness. I'm finding it pretty challenging to enunciate this properly so feel free to ask me to revise this again if it still isn't satisfactory.

**Review by danhhz — COMMENTED** [review]
I'm divided on this. I really want this correctness issue to be fixed in 19.2, but in all honesty, I am unconvinced of the correctness of the new approach. It's not that I have any suspicions on where it's wrong, but rather, I've been trying to form a mental model and intuition of why it's correct since I got back on Tuesday and I'm still not able to do that. For some reason I just find it incredibly difficult to reason about this after the switch from naming them after "earliest ts in file" to "local frontier at the time the file was created". At the very least, I think this deserves a much more rigorous proof than is even in the latest revision. OTOH if it's so hard to reason about, I wonder if we have the wrong model. @nvanbenschoten mentioned offline that he's also not a fan of using the span frontier for file naming. Summary: I'm not sure how to proceed here.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/40696#-:-Lpn_SlMEXMKpF_0g6vz:b6fe46)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @ajwerner, @danhhz, and @nvanbenschoten)

**Review by ajwerner — CHANGES_REQUESTED** [review]
I second some of Dan’s hesitation. This is tricky stuff and this PR doesn’t yet inspire the confidence in its correctness that it needs to. With a bit of hustle I believe you could get it there. 

> he's also not a fan of using the span frontier for file naming. 

I’d like to unpack this one. Is there a philosophical objection? I find it to be pretty elegant but I’m open to being convinced it’s problematic. 


An argument I can buy is that it pins correctness of an already not simple thing (how do clients consume these cloud storage files) on another complicated thing (the frontier). That being said, what we did before wasn’t simple.

 The ideas with a sequence number had some potentially pretty gross ux implications. 

Do we have any other classes of ideas?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/40696#-:-Lpndzda17NtvNq1f7nx:bcpemis)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @aayushshah15, @ajwerner, @danhhz, and @nvanbenschoten)

___
*[pkg/ccl/changefeedccl/sink_cloudstorage.go, line 294 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/40696#-LpeGEZW230GVzsqgCFD:-LpnTzEADFobJABSS_p1:bwueag) ([raw file](https://github.com/cockroachdb/cockroach/blob/255e76d923818064f4979bdbd7d1e3938c765a17/pkg/ccl/changefeedccl/sink_cloudstorage.go#L294)):*
<details><summary><i>Previously, aayushshah15 (Aayush Shah) wrote…</i></summary><blockquote>

While we probably don't need a sink-wide file ID, we need something to ensure correct ordering among files when multiple files are emitted at the same timestamp (this will happen if the file size exceeds our threshold before the local `spanFrontier` object is forwarded).
</blockquote></details>

May as well add those comments here. 
___
*[pkg/ccl/changefeedccl/sink_cloudstorage.go, line 85 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/40696#-Lpi6rWX0ffPE_E8LHar:-LpnSgSoBRhSL9fmThdo:b-d0b6k4) ([raw file](https://github.com/cockroachdb/cockroach/blob/4206253e91dec8a5df6f8485bf61479715b5e2d3/pkg/ccl/changefeedccl/sink_cloudstorage.go#L85)):*
<details><summary><i>Previously, aayushshah15 (Aayush Shah) wrote…</i></summary><blockquote>

I believe it doesn't matter since `sessionID` is a randomly generated string anyway. I think my explanation of the approach above will answer your question.
</blockquote></details>

These different orderings are definitely not exactly equivalent. I worry that they may have bearing on correctness. Maybe it’s safe to do it either way but I’m not convinced. Even if it is okay, let’s think through how clients should consume files in these cases. Do clients need to process all of the files from all of the sessions which occur at some timestamp. 

Please type out examples of how this works and make the code convincing that it’s correct. 
___
*[pkg/ccl/changefeedccl/sink_cloudstorage.go, line 95 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/40696#-Lpi5Nl98LDPwXzT7joK:-Lpnbtk91rdtxUie7rXu:b-4ktkpe) ([raw file](https://github.com/cockroachdb/cockroach/blob/4206253e91dec8a5df6f8485bf61479715b5e2d3/pkg/ccl/changefeedccl/sink_cloudstorage.go#L95)):*
<details><summary><i>Previously, aayushshah15 (Aayush Shah) wrote…</i></summary><blockquote>

I added a more descriptive section that explains it the way I convinced myself of its correctness. I'm finding it pretty challenging to enunciate this properly so feel free to ask me to revise this again if it still isn't satisfactory.
</blockquote></details>

I second Dan’s concerns here’s about correctness in the worst case. I think we need both a convincing argument for correctness and good testing around the new edge case: files occurring at the same timestamp from different sessions, either at the initial scan or resumption.

**Review by ajwerner — COMMENTED** [review]
Woah lost some of my writers from the last comment. 

The sequence number ideas has some potentially gross ux issues. 

Were there other classes of solutions?


In case my feedback wasn’t clear, to get this over the finish line you’re going to need to work through the cases where we have multiple sessions emitting files at the same timestamp. We should unit test all of those cases. They occur in 3 different ways: 

1)  resumptions from the same timestamp, 
2) resumptions which picks up at a timestamp written by a job which started at a different timestamp 
3) first run at the initial timestamp and resumptions from the initial timestamp (I.e. resumptions which need to do an initial scan).

If we write out how all of these are safe, how clients should consume these files and test them all then I suspect we’ll all feel better

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/40696#-:-LpngQrV5z3v2r1X_49k:bi2sq4k)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @aayushshah15, @ajwerner, @danhhz, and @nvanbenschoten)

**Review by ajwerner — COMMENTED** [review]
Oh actually they were there. Mobile web...

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/40696#-:-LpnhKG76cwnFqRlPveR:bqt84mk)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @aayushshah15, @ajwerner, @danhhz, and @nvanbenschoten)

**Review by ajwerner — COMMENTED** [review]
For those tests it’s important that we explore each session writing potentially more than one file at that same timestamp. 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/40696#-:-Lpnhlad2SY6geEvR45I:b-u5x6n5)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @aayushshah15, @ajwerner, @danhhz, and @nvanbenschoten)

**Comment by danhhz** [comment]
> With a bit of hustle I believe you could get it there.

I second this. I re-read my last comment and I want to be explicit that none of this hesitation is a reflection on your work here @aayushshah15. You're doing a top notch job on this. You just happened to get handed a complex and subtle problem. There's now 4 smart people thinking on it and (if I'm reading the room right) no one is really confidant yet that we've nailed it.

> > he's also not a fan of using the span frontier for file naming.

> I’d like to unpack this one. Is there a philosophical objection? I find it to be pretty elegant but I’m open to being convinced it’s problematic.

Dunno what Nathan's thoughts here were, he broadly expressed a preference for it being "based on the values in the files themselves + some memory of the values in the previous files".

Personally, I don't have a philosophical objection. My objection is that I'm finding it very hard to develop intuition around it. It's totally possible that y'all already have that intuition and just getting it really fleshed out in a comment will address my concern.

Just because I wasn't involved in the discussions the past couple weeks, can someone remind me what the UX issues are with sequence numbers?

> If we write out how all of these are safe, how clients should consume these files and test them all then I suspect we’ll all feel better.

I like the idea of including descriptions of how clients will consume them. We provide a set of guarantees, but they mostly feel arbitrary and they're really just stepping stones to the two main ways we expect users to use changefeeds. It's probably better to anchor this in terms of those two ways.

1) Act on each row update in order, ignoring txns.

To do this, the user would poll s3, grab any ndjson files it previously hadn't processed, and read them in order of lexicographic filename. Every time a RESOLVED file is processed, any ndjson files with lesser names can be removed from the list of processed files (and future polls can skip any file with a filename lesser than the RESOLVED file).

Alternatively, they could do something like below, but without the grouping by timestamp.

2) Act on each txn in order.

To do this, the user would poll s3, grabbing the latest RESOLVED file. If this is new since the last poll, every file between the last processed RESOLVED and the new one is read. Everything in those files is grouped by timestamp and each group is processed in timestamp order as a txn (which can merge 2 txns that touched a totally separate set of ranges, but can never split a txn).

**Comment by aayushshah15** [comment]
> If we write out how all of these are safe, how clients should consume these files and test them all then I suspect we’ll all feel better

I'm a little confused as to how to really test this without involving the jobs infrastructure. Based on my understanding of why this solution works, what we really want to do here is prove that *ordering among same-timestamp files at the boundaries of job sessions doesn't matter*. If we can prove/test this statement, overall correctness should follow since we have monotonicity within each session.

**Comment by ajwerner** [comment]
> I'm a little confused as to how to really test this without involving the jobs infrastructure.

The jobs infrastructure just creates and runs flows. You can use the lower level abstractions in testing. Think manually creating nodes etc. I don’t want to overly send you astray. Maybe you could find a way to bend the jobs infrastructure to your testing needs but I wouldn’t get trapped into the thinking that you have to create tests using such a far away interface. Consider manually constructing change aggregators

**Comment by ajwerner** [comment]
> Just because I wasn't involved in the discussions the past couple weeks, can someone remind me what the UX issues are with sequence numbers?

The sequence number solutions we discussed require putting the sequence number out front. This is sort of a bummer and makes the partitioning piece sort of useless. Maybe it’s not a big deal. 

> Dunno what Nathan's thoughts here were, he broadly expressed a preference for it being "based on the values in the files themselves + some memory of the values in the previous files".

The frontier when the first row is buffered is guaranteed to precede all rows in the file (logic was added in the pr to ensure this). The way that resolved timestamps are checkpointed and then jobs resumed in a sense provides the only memory we have between sessions and thus files written by previous sessions. If you squint you could say that this approach is based on the values in the files and some memory about previous files. I was hoping to avoid needing to add extra memory across sessions with this approach. Perhaps it’s too clever.

**Comment by aayushshah15** [comment]
I'd like to take another stab at convincing everyone why the solution is correct:

First, we should all agree on this: ensuring that files are lexically ordered the way they’re emitted gives us correctness, at least within a single job session. 

For the above, we need a source that gives us monotonically increasing timestamps. We can agree that the `frontier` timestamps fulfill this requirement (again, at least within a session), and when the `frontier` timestamps are equal, the monotonically increasing `fileID` fulfills this requirement.

Now, in order to achieve overall correctness we need to explain ordering *across* job sessions. What follows is an explanation of why this is okay. My goal with this is to convince you that the ordering of boundary files of multiple job sessions does not matter: 

For simplicity, let’s say the files are named as: `{timestamp}_{nodeID}_{fileID}_{sessionID}`, and let’s restrict ourselves to watching just one row. Say the current globally resolved timestamp is 0 (`initialHighWater` = 0). Say there are 2 nodes in the system (with ids 0 and 1). Let’s say session A (scheduled on node 1) with current local `frontier` timestamp 0 has been buffering a file `0_1_0_A.ndjson`. Say this file contains the timestamps `[2,3,4]`. This job session emits that file and somehow fails. Now allow me to present two cases below which consider ordering of this file in relation to a file emitted by a new session:

 a) Session B (scheduled on node 0) starts with the initialHighWater of 0. It does a catch up scan starting from 0 and starts buffering a file named `0_0_0_B.ndjson` that contains the timestamps `[2,3,4,5]`.  Note that here we *know* it must contain `[2,3,4]` because of the catch up scan.  Now lexically, the file emitted by session B is ordered before the file emitted by session A but notice that reading files in this way doesn’t violate any of our guarantees.

b) Session B (scheduled on node 1) starts with the initialHighWater of 0, does the catch up scan starting from 0 and starts buffering the file with contents `[2,3,4,5]` named `0_1_0_B.ndjson`. Lexically the file is ordered after the file emitted by session A, so we read `[2,3,4]` and then `[2,3,4,5]` (which is also totally okay).

The above means that the ordering among such boundary files does not affect correctness (because of the catch up scan). Thus we should have overall correctness.

I'm still working on a way to test all this in an isolated way. This approach currently works with our nemeses test (tested for ~5K runs). Please let me know if you're still not convinced @danhhz (or if any of my underlying assumptions here are wrong).

**Review by ajwerner — COMMENTED** [review]
I think you’re on the right track to making a case for that when two sessions begin at the same timestamp and each write one file that it is safe to read either one first. You don’t here make any claims about how those two files interact with a) all the other files at potentially higher timestamps or other files at the same timestamp interact with correctness or b) 3 or more different sessions and the various possible interleavings of those sessions files at the same timestamp.  


More concretely, you’ve convinced us that given the following two files, it’s fine to read them in any order. 

A: `[2, 3, 4, 5]`
B: `[2, 3, 4]`

You didn’t explore all future files that could possible exist and how the order you read these files can’t possible impact the correctness of the later files. 

I implore you to stop trying to convince us in the thread with specific examples. Convince us in comments in the code with claims, correctness invariants and then a proof of safety given those claims. Prose focusing on specific cases is unlikely to get us to a point of confidence. 

Try typing out, in the code, the algorithm by which clients consume the files (as dan suggested), the invariants about rows and resolved timestamps we expose to this algorithm and then a proof for how, given the way the files are produced, those invariants cannot be violated. 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/40696#-:-Lppd3R_-q4VuRHmGkA8:b-twlbcv)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @aayushshah15, @ajwerner, @danhhz, and @nvanbenschoten)

**Comment by danhhz** [comment]
Okay, so this is super rough, but I started writing the proof that I wanted. In the process, I've convinced myself that we actually can't use the local frontier to name the data files. This is super rough and WIP, but I'm headed to the airport soon, so I figured I'd put it out there.

> Changefeeds offer the following two ordering guarantees to external clients
> 1) Rows are emitted with a timestamp. Individual rows are emitted in timestamp order. There may be duplicates, but once a row is seen at a given timestamp no previously unseen version of that row will be emitted at a less (or equal) timestamp. For example, you may see 1 2 1 2, or even 1 2 1, but never simply 2 1.
> 2) Periodically, a resolved timestamp is emitted. This is a changefeed-wide guarantee that no previously unseen row will later be seen with a timestamp less (or equal) to the resolved one.
>
> The cloud storage sink is structured as a number of distsql processors that each emit some part of the total changefeed. These processors only write files containing row data (initially only in ndjson format). This mapping is stable for a given distsql flow of a changefeed (meaning any given row is always emitted by the same processor), but it's not stable across restarts (pause/unpause). Each of these processors report partial progress information to a central coordinator, which is responsible for writing the resolved timestamp files.
>
> In addition to the guarantees required of any changefeed, the cloud storage sink adds some quality of life guarantees of its own.
> 4) All rows in a file are from the same table. Futher, all rows in a file are from the same schema version of that table, and so all have the same schema.
> 5) All files are partitioned into folders by the date part of the filename.
> 6) TODO(dan): This is not currently true, but I think we should guarantee that all rows in all files under a date partition is from that date. This is mostly true, but breaks down around date boundaries. Should be an easy fix.
>
>Two methods of the cloudStorageSink on each data emitting processor are called. EmitRow is called with each row change and Flush is called before sending partial progress information to the coordinator. This happens with no concurrency, all EmitRow and Flush calls for a sink are serialized.
>
> Only the EmitResolvedTimestamp method is called on the coordinator.
>
> The rows handed to EmitRow by the changefeed are guaranteed to satisfy condition (1). Further, as long as the sink has written every EmitRow it's gotten before returning from Flush, condition (2) is upheld.
>
> The cloudStorageSink uses lexicographic filename ordering to provide a total ordering for the output of this sink. Guarantees (1) and (2) depend on this ordering. Specifically, at any given time, the order of the data written by the sink is by lexicographic filename and then by order within the file.
>
> To make this all concrete: an unreasonably simple but valid implementation of this sink would write each row one to a file with the name `<ts>_<uuid>.ndjson` and resolved timestamps to `<ts>.RESOLVED` (where `<ts>` is a lexicographically comparable serialization of timestamps). Note that a resolved timestamp closes out every timestamp less *or equal* so the resolved timestamp filename must compare as *greater* than the filename of any data files with a less or equal timestamp, hence `<ts>_` and `<ts>.`
>
> WIP explain how clients are expected work with this.
>
> This model is unreasonably simple because we'd like to include the table name and a way to indicate which specific schema of that table (easy), but more importantly because we need to batch multiple row changes into a file. Batching is hard because we (a) have to pick a representative timestamp for the file and (b) for each topic, all files emitted by a given sink must be written in filename order. (a) is required for comparison with the resolved timestamp filenames as part of guarantee (2). (b) is technically stricter than it needs to be, but is the only reasonably way to preserve row orderings.
>
> Whenever the local progress is sent to the coordinator (called the "local frontier" as opposed to the resolved timestamp which is exactly a "global frontier" or "changefeed-level frontier"), Flush is immediately called beforehand. To accomplish (a), we need two invariants. First (a1) is that once Flush is called, we can never write a file with a name that is less or equal to the local frontier. This is because the local progress update could indeed cause a resolved timestamp file to be written with that timestamp. If this happens, the client is free to ignore any files with a lesser filename. We picked the resolve timestamp filename to sort after a data file with the same timestamp, so it can't even be at the same timestamp, it has to be at a greater one. (Note that the local frontier is a guarantee that the sink will never get an EmitRow with that timestamp or lower). Second, (a2) is that whenever Flush is called, all files written by the sink must have names less than the one for the local frontier at the time Flush is called. This is again because our local progress update could cause the global progress to be updated and we need everything written so far to be less than the new resolved timestamp.
>
>WIP work through job restarts.

The key here being "once Flush is called, we can never write a file with a name that is less or equal to the local frontier".

@aayushshah15 and @ajwerner wanna check my logic here? FYI I'm going to be on a plane without wifi for most of the day after this, so don't expect any responses from me until tomorrow

**Comment by aayushshah15** [comment]
> Note that a resolved timestamp closes out every timestamp less or equal so the resolved timestamp filename must compare as greater than the filename of any data files with a less or equal timestamp

In the current implementation, the timestamp of a data file is effectively a *lower bound* on the timestamps contained within the file. So we actually want the resolved timestamp filename to compare as *less* than the filename of any data file with an equal timestamp.

> hence `<ts>_` and `<ts>.`

Lexically `<ts>.` is actually before the `<ts>_`.

> If this happens, the client is free to ignore any files with a lesser filename.

> The key here being "once Flush is called, we can never write a file with a name that is less or equal to the local frontier".

This actually fine (in the current implementation) because of what I wrote above, since those data files will be ordered after the `<ts>.RESOLVED` file, even if they have the same timestamp.

**Comment by aayushshah15** [comment]
I extended dan's write-up with a formal proof: https://drive.google.com/file/d/1_kRgzruPwSJqf0wiC6DTlEZxnWRObqJr/view?usp=sharing. Proof starts from page 3. Please let me know if any terminology seems ambiguous.

**Comment by danhhz** [comment]
Great! I took a look and it seems fine to me, but I've never been a very good reader of proofs. I asked @tbg if he'd be willing to take a look and he said yes. The plan is to get together sometime tomorrow and go over any questions that he has.

**Review by aayushshah15 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/40696)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @aayushshah15, @ajwerner, @danhhz, and @nvanbenschoten)

___
*[pkg/ccl/changefeedccl/sink_cloudstorage.go, line 294 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/40696#-LpeGEZW230GVzsqgCFD:-LqCxeOLEqMmq35I9e-V:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/255e76d923818064f4979bdbd7d1e3938c765a17/pkg/ccl/changefeedccl/sink_cloudstorage.go#L294)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

May as well add those comments here. 
</blockquote></details>

Done.

**Comment by aayushshah15** [comment]
I believe I stumbled into a UX bug while testing my latest change. 

The poller uses the same mechanism for emitting backfill row updates as it does for the initial scan (ie. when the changefeed began). In particular, the poller emits the backfill rows as of the last modification time of their table descriptor. (Correct me if I'm wrong here ->) I believe this can often (always?) be the resolved timestamp of the corresponding `span`. Because of this, the poller actually forwards a resolved timestamp and *then* emits all these backfill row updates with the same timestamp. 

I have updated the PR to fix this. Please let me know if you have any questions, but otherwise I believe this is ready for another look.

**Review by ajwerner — COMMENTED** [review]
Just nits from me on this pass. Your build failed with a flake which should be fixed, rebase to pick that up. 

> Reviewed 2 of 7 files at r9, 3 of 10 files at r11.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/40696#-:-LqYxFPnBhdnf8RrMZry:b-tfuaum)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @aayushshah15, @ajwerner, @danhhz, and @nvanbenschoten)

___
*[pkg/ccl/changefeedccl/changefeed_processors.go, line 145 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/40696#-LqYtkao3HEWYpKi9XA-:-LqYtkao3HEWYpKi9XA0:b-73nemo) ([raw file](https://github.com/cockroachdb/cockroach/blob/6392952b2924c0aac2f0b09fae6c7ec58f0655a9/pkg/ccl/changefeedccl/changefeed_processors.go#L145)):*
> ```Go
> 			// to avoid naming the first cloudStorageSink file to the zero epoch timestamp.
> 			// We call Prev() on it because `sf` is Next()ed in the cloudStorageSink
> 			// when it's used to name a file.
> ```

Also note that all rows in the initial scan will be emitted at Feed.StatementTime and refer to the method which sets that up (`makePoller`?)
___
*[pkg/ccl/changefeedccl/changefeed_processors.go, line 443 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/40696#-LqYuxF7-NQ4e2Beld8q:-LqYuxF7-NQ4e2Beld8r:b-ghtavz) ([raw file](https://github.com/cockroachdb/cockroach/blob/6392952b2924c0aac2f0b09fae6c7ec58f0655a9/pkg/ccl/changefeedccl/changefeed_processors.go#L443)):*
> ```Go
> 	var err error
> 	if cf.sink, err = getSink(
> 		cf.spec.Feed.SinkURI, nodeID, cf.spec.Feed.SessionID, cf.spec.Feed.Opts, cf.spec.Feed.Targets, cf.flowCtx.Cfg.Settings, makeSpanFrontier(),
> ```

Maybe it'd be nice to pass nil here. We're never going to use this span frontier. It only is consulted when calling EmitRow or FlushFile which we should never do. I don't feel strongly here. 
___
*[pkg/ccl/changefeedccl/nemeses_test.go, line 31 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/40696#-LqYu8QC4Ji4Kguk3mF5:-LqYu8QC4Ji4Kguk3mF6:b-57b8jc) ([raw file](https://github.com/cockroachdb/cockroach/blob/6392952b2924c0aac2f0b09fae6c7ec58f0655a9/pkg/ccl/changefeedccl/nemeses_test.go#L31)):*
> ```Go
> 		// TODO(aayush,dan): Ugly hack to disable `eventPause` in sinkless
> 		// feeds. See comment in `RunNemesis` for details.
> 		if strings.Contains(t.Name(), "sinkless") {
> ```


nit:
```
// TODO(aayush,dan): Ugly hack to disable `eventPause` in sinkless
// feeds. See comment in `RunNemesis` for details.
isSinkless := strings.Contains(t.Name(), "sinkless")
```
___
*[pkg/ccl/changefeedccl/sink_cloudstorage.go, line 55 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/40696#-LqYr-OP-mQA3qUrm_9O:-LqYr-OP-mQA3qUrm_9P:b-5sxd4p) ([raw file](https://github.com/cockroachdb/cockroach/blob/6392952b2924c0aac2f0b09fae6c7ec58f0655a9/pkg/ccl/changefeedccl/sink_cloudstorage.go#L55)):*
> ```Go
> 
> type cloudStorageSinkFile struct {
> 	// `lowWaterTs` is the local spanFrontier's Frontier().Next() timestamp as of
> ```

nit: we use both low and high water to mean sort of roughly the same thing but we never define either of them. I know I used this term "low water" when talking to you. How about just `minTS` as it represents an inclusive lower bound of any row in the file? 
___
*[pkg/ccl/changefeedccl/sink_cloudstorage.go, line 66 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/40696#-LqYrHBnCwX7Nb3A6Yrb:-LqYrHBnCwX7Nb3A6Yrc:b-p1u6hz) ([raw file](https://github.com/cockroachdb/cockroach/blob/6392952b2924c0aac2f0b09fae6c7ec58f0655a9/pkg/ccl/changefeedccl/sink_cloudstorage.go#L66)):*
> ```Go
> 
> // Changefeeds offer the following two ordering guarantees to external clients:
> ```

nit: keep this as all one comment by putting `//` for the breaks.
___
*[pkg/ccl/changefeedccl/sink_cloudstorage.go, line 106 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/40696#-LqYvoU9D4aaJr2seMJX:-LqYvoU9D4aaJr2seMJY:b-hq27mb) ([raw file](https://github.com/cockroachdb/cockroach/blob/6392952b2924c0aac2f0b09fae6c7ec58f0655a9/pkg/ccl/changefeedccl/sink_cloudstorage.go#L106)):*
> ```Go
> // This batching is hard because:
> // a) We need to pick a representative timestamp for the file
> // b) For each topic, all files emitted by a given sink must be written in filename order.
> ```

The language on this one is ambiguous. It's not clear whether you're talking about parallelism or just about naming. 
___
*[pkg/ccl/changefeedccl/sink_cloudstorage.go, line 109 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/40696#-LqYv_B2EXTlM1TjpmIw:-LqYv_B2EXTlM1TjpmIx:b-5xpkkl) ([raw file](https://github.com/cockroachdb/cockroach/blob/6392952b2924c0aac2f0b09fae6c7ec58f0655a9/pkg/ccl/changefeedccl/sink_cloudstorage.go#L109)):*
> ```Go
> 
> // (a) is required for comparison with resolved timestamp filenames as part of guarantee.
> // (b) is technically stricter than it needs to be but is the only reasonable way of
> ```

I don't know that I buy "the only reasonable way". Also I don't really think the sentences here explain why the batching is "hard". Can you take another pass on this little subsection?
___
*[pkg/ccl/changefeedccl/sink_cloudstorage.go, line 114 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/40696#-LqYwOAh0pDgr_jHaVD9:-LqYwOAi1PDtcSrXGkLo:b-exbw2q) ([raw file](https://github.com/cockroachdb/cockroach/blob/6392952b2924c0aac2f0b09fae6c7ec58f0655a9/pkg/ccl/changefeedccl/sink_cloudstorage.go#L114)):*
> ```Go
> // Whenever the local progress is sent to the coordinator (called the "local frontier"
> // as opposed to the resolved timestamp which is exactly a "global frontier" or
> // "changefeed-level frontier"), Flush is immediately called beforehand. To accomplish
> ```

nit: I'm not sure `immediately` adds to the meaning. I think this sentence would be clearer if you said something more like: before local progress is sent to the coordinator all buffered data which preceded that update is flushed.
___
*[pkg/ccl/changefeedccl/sink_cloudstorage.go, line 130 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/40696#-LqYrMpX708bT1Ki3ZLJ:-LqYrMpX708bT1Ki3ZLK:b-xef9k5) ([raw file](https://github.com/cockroachdb/cockroach/blob/6392952b2924c0aac2f0b09fae6c7ec58f0655a9/pkg/ccl/changefeedccl/sink_cloudstorage.go#L130)):*
> ```Go
> 
> // The data files written by this sink are named according to the pattern
> // `<timestamp>-<topic>-<schema_id>-<uniquer>.<ext>`, each component of which is
> ```

Was this just wrong in the code? I.e. 
___
*[pkg/ccl/changefeedccl/sink_cloudstorage.go, line 160 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/40696#-LqYwuExENB2w0KdZ0dG:-LqYwuExENB2w0KdZ0dH:b-jmovja) ([raw file](https://github.com/cockroachdb/cockroach/blob/6392952b2924c0aac2f0b09fae6c7ec58f0655a9/pkg/ccl/changefeedccl/sink_cloudstorage.go#L160)):*
> ```Go
> // the external ordering guarantees of CDC. Naming output files in this fashion
> // provides monotonicity among files emitted by a given sink for a given table
> // name, table schema version pair. This ensures that all rows for a given span
> ```

Well technically it only provides monotonicity for a given session but provides safety across sessions, see proof below. 
___
*[pkg/ccl/changefeedccl/sink_cloudstorage.go, line 439 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/40696#-LqYrc777D3Y5mGLYSXW:-LqYrc777D3Y5mGLYSXX:b-aa68qg) ([raw file](https://github.com/cockroachdb/cockroach/blob/6392952b2924c0aac2f0b09fae6c7ec58f0655a9/pkg/ccl/changefeedccl/sink_cloudstorage.go#L439)):*
> ```Go
> 	// `%d.RESOLVED` files to lexicographically succeed data files that have the
> 	// same timestamp. This works because ascii `-` < ascii '.'.
> 	filename := fmt.Sprintf(`%s-%s-%08d-%d-%d-%012d-%s%s`,
> ```

justify the 8 and 12? 12 feels especially excessive. If the only reason we flush a file is due to a resolved timestamp being emitted (which means future files must be at a later ts) or buffers being filled (64 MiB), then to overflow 12 decimal digits would be 1e11 * 64 MiB = 6 exabytes which I don't think we're going to need to worry about. 8 decimal digits is probably fine. That being said, we can use hex both here and in the schema ID for "free". How about 8 hex digits for the file ID? That gives us hundreds of petabytes for a single table's catch up scan which seems like more than enough.

**Review by aayushshah15 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/40696)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @aayushshah15, @ajwerner, @danhhz, and @nvanbenschoten)

___
*[pkg/ccl/changefeedccl/changefeed_processors.go, line 443 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/40696#-LqYuxF7-NQ4e2Beld8q:-LqZ42CUCnkfLQHfw4TJ:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/6392952b2924c0aac2f0b09fae6c7ec58f0655a9/pkg/ccl/changefeedccl/changefeed_processors.go#L443)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

Maybe it'd be nice to pass nil here. We're never going to use this span frontier. It only is consulted when calling EmitRow or FlushFile which we should never do. I don't feel strongly here. 
</blockquote></details>

Done.
___
*[pkg/ccl/changefeedccl/sink_cloudstorage.go, line 106 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/40696#-LqYvoU9D4aaJr2seMJX:-LqZQWqgD_dPtKiEyHuy:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/6392952b2924c0aac2f0b09fae6c7ec58f0655a9/pkg/ccl/changefeedccl/sink_cloudstorage.go#L106)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

The language on this one is ambiguous. It's not clear whether you're talking about parallelism or just about naming. 
</blockquote></details>

Done.
___
*[pkg/ccl/changefeedccl/sink_cloudstorage.go, line 109 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/40696#-LqYv_B2EXTlM1TjpmIw:-LqZQjDH3cDByY5remUZ:b-oeuy7h) ([raw file](https://github.com/cockroachdb/cockroach/blob/6392952b2924c0aac2f0b09fae6c7ec58f0655a9/pkg/ccl/changefeedccl/sink_cloudstorage.go#L109)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

I don't know that I buy "the only reasonable way". Also I don't really think the sentences here explain why the batching is "hard". Can you take another pass on this little subsection?
</blockquote></details>

Done.  Let me know if it still seems lacking.
___
*[pkg/ccl/changefeedccl/sink_cloudstorage.go, line 160 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/40696#-LqYwuExENB2w0KdZ0dG:-LqZ8wBREMWc4xOdD4yQ:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/6392952b2924c0aac2f0b09fae6c7ec58f0655a9/pkg/ccl/changefeedccl/sink_cloudstorage.go#L160)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

Well technically it only provides monotonicity for a given session but provides safety across sessions, see proof below. 
</blockquote></details>

Done.
___
*[pkg/ccl/changefeedccl/sink_cloudstorage.go, line 439 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/40696#-LqYrc777D3Y5mGLYSXW:-LqZCh9Y8Q1DsbyizHab:b-kn2rud) ([raw file](https://github.com/cockroachdb/cockroach/blob/6392952b2924c0aac2f0b09fae6c7ec58f0655a9/pkg/ccl/changefeedccl/sink_cloudstorage.go#L439)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

justify the 8 and 12? 12 feels especially excessive. If the only reason we flush a file is due to a resolved timestamp being emitted (which means future files must be at a later ts) or buffers being filled (64 MiB), then to overflow 12 decimal digits would be 1e11 * 64 MiB = 6 exabytes which I don't think we're going to need to worry about. 8 decimal digits is probably fine. That being said, we can use hex both here and in the schema ID for "free". How about 8 hex digits for the file ID? That gives us hundreds of petabytes for a single table's catch up scan which seems like more than enough. 
</blockquote></details>

Done. I also added logic to reset the sink's `fileID` once the local frontier timestamp changes.

**Review by aayushshah15 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/40696)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @ajwerner, @danhhz, and @nvanbenschoten)

___
*[pkg/ccl/changefeedccl/sink_cloudstorage.go, line 130 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/40696#-LqYrMpX708bT1Ki3ZLJ:-LqajzlQBLwET9N8yvLb:bfynavo) ([raw file](https://github.com/cockroachdb/cockroach/blob/6392952b2924c0aac2f0b09fae6c7ec58f0655a9/pkg/ccl/changefeedccl/sink_cloudstorage.go#L130)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

Was this just wrong in the code? I.e. 
</blockquote></details>

yes it seems so.

**Review by ajwerner — APPROVED** [review]
:lgtm_strong: just a few nits mostly in the language of the proof.

Let's let Dan sign off before we bors it.

Thanks again for taking the time to get this over the finish line!!

> Reviewed 4 of 10 files at r11, 1 of 3 files at r12, 2 of 2 files at r13.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/40696#-:-LqapX7YB_zPGX-Sj6JG:b-hexoko)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @aayushshah15, @danhhz, and @nvanbenschoten)

___
*[pkg/ccl/changefeedccl/changefeed_processors.go, line 443 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/40696#-LqYuxF7-NQ4e2Beld8q:-Lqakk8QAFCy9gZXrtFd:b-2der4p) ([raw file](https://github.com/cockroachdb/cockroach/blob/6392952b2924c0aac2f0b09fae6c7ec58f0655a9/pkg/ccl/changefeedccl/changefeed_processors.go#L443)):*
<details><summary><i>Previously, aayushshah15 (Aayush Shah) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

super duper nit: add a comment about why you're passing nil

```
// Pass a nil spanFrontier because this sink is only used to emit resolved timestamps and the spanFrontier
// is only used when dealing with rows. 
sf := nil 
```

I know this is a lot of back and forth but we're really close now. 
___
*[pkg/ccl/changefeedccl/poller.go, line 110 at r13](https://reviewable.io/reviews/cockroachdb/cockroach/40696#-LqapLkK9A5Bnkt7ZdTB:-LqapLkK9A5Bnkt7ZdTC:b76a3xw) ([raw file](https://github.com/cockroachdb/cockroach/blob/e18ed8683b83a57b1337f046a3278816117fd66b/pkg/ccl/changefeedccl/poller.go#L110)):*
> ```Go
> 		p.mu.scanBoundaries = append(p.mu.scanBoundaries, details.StatementTime)
> 	} else {
> 		// Otherwise, Next() the highWater value since a resolved timestamp closes
> ```

Thanks for doing this. I want @danhhz to sign off on this. 
___
*[pkg/ccl/changefeedccl/sink_cloudstorage.go, line 115 at r13](https://reviewable.io/reviews/cockroachdb/cockroach/40696#-LqalprKA4v3cXRnf3kO:-LqalprL5w1ATnM5UY2F:b-1fnjpi) ([raw file](https://github.com/cockroachdb/cockroach/blob/e18ed8683b83a57b1337f046a3278816117fd66b/pkg/ccl/changefeedccl/sink_cloudstorage.go#L115)):*
> ```Go
> // frontier" as opposed to the resolved timestamp which is exactly a "global
> // frontier" or "changefeed-level frontier"), all buffered data which preceded
> // that update is flushed. To accomplish (a), we need two invariants. First (a1)
> ```

nit: start a new paragraph for each of these sub invariants
___
*[pkg/ccl/changefeedccl/sink_cloudstorage.go, line 119 at r13](https://reviewable.io/reviews/cockroachdb/cockroach/40696#-LqamUaS2GwjnX6ULFaa:-LqamUaS2GwjnX6ULFab:bpkv62b) ([raw file](https://github.com/cockroachdb/cockroach/blob/e18ed8683b83a57b1337f046a3278816117fd66b/pkg/ccl/changefeedccl/sink_cloudstorage.go#L119)):*
> ```Go
> // is less than or equal to the local frontier. This is because the local
> // progress update could indeed cause a resolved timestamp file to be written
> // with that timestamp. If this happens, the client is free to ignore any files
> ```

What is `this` referring to? We just said we'd never write files below the resolve timestamp file. 
___
*[pkg/ccl/changefeedccl/sink_cloudstorage.go, line 120 at r13](https://reviewable.io/reviews/cockroachdb/cockroach/40696#-LqalW2lB8A7RAaRs72V:-LqalW2lB8A7RAaRs72W:b-exmw31) ([raw file](https://github.com/cockroachdb/cockroach/blob/e18ed8683b83a57b1337f046a3278816117fd66b/pkg/ccl/changefeedccl/sink_cloudstorage.go#L120)):*
> ```Go
> // progress update could indeed cause a resolved timestamp file to be written
> // with that timestamp. If this happens, the client is free to ignore any files
> // with a lesser filename. We picked the resolve timestamp filename to sort
> ```

s/resolve/resolved/
___
*[pkg/ccl/changefeedccl/sink_cloudstorage.go, line 121 at r13](https://reviewable.io/reviews/cockroachdb/cockroach/40696#-Lqal_td1RZjzja2d5pD:-Lqal_td1RZjzja2d5pE:bwd475w) ([raw file](https://github.com/cockroachdb/cockroach/blob/e18ed8683b83a57b1337f046a3278816117fd66b/pkg/ccl/changefeedccl/sink_cloudstorage.go#L121)):*
> ```Go
> // with that timestamp. If this happens, the client is free to ignore any files
> // with a lesser filename. We picked the resolve timestamp filename to sort
> // after a data file with the same timestamp, so it can't even be at the same
> ```

I find `it` in this sentence to be ambiguous. Can you rework this sentence? I think you're saying future data files can't must have a higher timestamp but that doesn't really follow from the first part of the sentence which is about data files at the same timestamp. 
___
*[pkg/ccl/changefeedccl/sink_cloudstorage.go, line 204 at r13](https://reviewable.io/reviews/cockroachdb/cockroach/40696#-LqanWcq6TvMS_-zei_m:-LqanWcq6TvMS_-zei_n:b-9zxfuw) ([raw file](https://github.com/cockroachdb/cockroach/blob/e18ed8683b83a57b1337f046a3278816117fd66b/pkg/ccl/changefeedccl/sink_cloudstorage.go#L204)):*
> ```Go
> // 2. Data files emitted by a single session of a changefeed job are lexically
> // ordered exactly as they were emitted. Xi lexically precedes X(i-1), for i in
> // integers, for all job sessions X. The naming convention described above guarantees
> ```

super nit: for `i in Nat` (Nat is a shorthand for the set of naturals numbers used by TLA+). 
___
*[pkg/ccl/changefeedccl/sink_cloudstorage.go, line 206 at r13](https://reviewable.io/reviews/cockroachdb/cockroach/40696#-LqaniyL67xtjt4R8BWf:-LqaniyL67xtjt4R8BWg:b2y4vti) ([raw file](https://github.com/cockroachdb/cockroach/blob/e18ed8683b83a57b1337f046a3278816117fd66b/pkg/ccl/changefeedccl/sink_cloudstorage.go#L206)):*
> ```Go
> // integers, for all job sessions X. The naming convention described above guarantees
> // this.
> // 3. Data files are named 1 logical timestamp higher than the "local frontier"
> ```

nit: successor instead of 1 logical timestamp higher
___
*[pkg/ccl/changefeedccl/sink_cloudstorage.go, line 230 at r13](https://reviewable.io/reviews/cockroachdb/cockroach/40696#-Lqao8NF2xrWYBdrZf0t:-Lqao8NF2xrWYBdrZf0u:bb70qn7) ([raw file](https://github.com/cockroachdb/cockroach/blob/e18ed8683b83a57b1337f046a3278816117fd66b/pkg/ccl/changefeedccl/sink_cloudstorage.go#L230)):*
> ```Go
> // assume there is a violation here. Since there is a total lexical ordering
> // among files in each set individually, we must have read Y(e-1) before Ye, for
> // all e in integers. Similarly for X. Without loss of generality, lets say
> ```

Nat?
___
*[pkg/ccl/changefeedccl/sink_cloudstorage.go, line 231 at r13](https://reviewable.io/reviews/cockroachdb/cockroach/40696#-LqaoEoJEK0c6RtAku0b:-LqaoEoJEK0c6RtAku0c:bmgr5nh) ([raw file](https://github.com/cockroachdb/cockroach/blob/e18ed8683b83a57b1337f046a3278816117fd66b/pkg/ccl/changefeedccl/sink_cloudstorage.go#L231)):*
> ```Go
> // among files in each set individually, we must have read Y(e-1) before Ye, for
> // all e in integers. Similarly for X. Without loss of generality, lets say
> // there are 2 files Ye and Xf such that (1.1) Ye < Xf such that Xf contains an
> ```

nit: `and` instead of the second `such that`

**Comment by danhhz** [comment]
I'm currently looking at this. I have some reasonably substantive comments so definitely don't bors yet

**Review by aayushshah15 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/40696)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ajwerner, @danhhz, and @nvanbenschoten)

___
*[pkg/ccl/changefeedccl/sink_cloudstorage.go, line 119 at r13](https://reviewable.io/reviews/cockroachdb/cockroach/40696#-LqamUaS2GwjnX6ULFaa:-Lqausu3-MdpS9ZkfgV8:b-8q3k57) ([raw file](https://github.com/cockroachdb/cockroach/blob/e18ed8683b83a57b1337f046a3278816117fd66b/pkg/ccl/changefeedccl/sink_cloudstorage.go#L119)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

What is `this` referring to? We just said we'd never write files below the resolve timestamp file. 
</blockquote></details>

Rewrote that little subsection.

**Review by danhhz — COMMENTED** [review]
Okay feels like this is getting close. A few key things here are different than what I remember us agreeing on in the meeting, though. Did something change or am I wrong about what I thought we agreed on?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/40696#-:-LqbGg2V0RWhPj2usV6C:b-p780je)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @aayushshah15, @ajwerner, @danhhz, and @nvanbenschoten)

___
*[pkg/ccl/changefeedccl/changefeed.go, line 155 at r13](https://reviewable.io/reviews/cockroachdb/cockroach/40696#-LqaoAmI27OhdSVrRsjr:-LqaoAmI27OhdSVrRsjs:b-cuj9w5) ([raw file](https://github.com/cockroachdb/cockroach/blob/e18ed8683b83a57b1337f046a3278816117fd66b/pkg/ccl/changefeedccl/changefeed.go#L155)):*
> ```Go
> // advance the changefeed and which returns span-level resolved timestamp
> // updates. The returned closure is not threadsafe. Note that rows read from
> // `inputFn` which precede the Frontier of `sf` will not be emitted because they're
> ```

nit: precede or equal
___
*[pkg/ccl/changefeedccl/changefeed.go, line 173 at r13](https://reviewable.io/reviews/cockroachdb/cockroach/40696#-Lqaoh09--EI37ThsY59:-Lqaoh09--EI37ThsY5A:btjvh3n) ([raw file](https://github.com/cockroachdb/cockroach/blob/e18ed8683b83a57b1337f046a3278816117fd66b/pkg/ccl/changefeedccl/changefeed.go#L173)):*
> ```Go
> 		// ensure that this never happens.
> 		if !sf.Frontier().Less(row.updated) {
> 			return errors.AssertionFailedf("error: detected a row.updated timestamp %s"+
> ```

shouldn't we just skip these (maybe with a TODO to make it an assertion error)? i feel like there's (possibly unlikely) replay cases where this would happen and i want to keep the risk of this PR low. 
___
*[pkg/ccl/changefeedccl/changefeed_processors.go, line 147 at r13](https://reviewable.io/reviews/cockroachdb/cockroach/40696#-LqapWpwEEeZag84l0cA:-LqapWpxB2pwW-lAehjx:blynt93) ([raw file](https://github.com/cockroachdb/cockroach/blob/e18ed8683b83a57b1337f046a3278816117fd66b/pkg/ccl/changefeedccl/changefeed_processors.go#L147)):*
> ```Go
> 			// timestamp. We call Prev() on it because `sf` is Next()ed in the
> 			// cloudStorageSink when it's used to name a file.
> 			sf.Forward(watch.Span, ca.spec.Feed.StatementTime.Prev())
> ```

as I mentioned in our meeting, I don't like this. It's so much more obvious to leave the span frontier at zero and then handle a zero frontier in the cloud storage sink
___
*[pkg/ccl/changefeedccl/poller.go, line 110 at r13](https://reviewable.io/reviews/cockroachdb/cockroach/40696#-LqapLkK9A5Bnkt7ZdTB:-Lqathsc2vfmCG2iuORI:br74yf0) ([raw file](https://github.com/cockroachdb/cockroach/blob/e18ed8683b83a57b1337f046a3278816117fd66b/pkg/ccl/changefeedccl/poller.go#L110)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

Thanks for doing this. I want @danhhz to sign off on this. 
</blockquote></details>

I don't get it. Maybe the comment needs to be expanded? Or maybe this Next would be more clear if it happens in a different place?
___
*[pkg/ccl/changefeedccl/poller.go, line 162 at r13](https://reviewable.io/reviews/cockroachdb/cockroach/40696#-Lqau7a16z6uZk50XTIk:-Lqau7a16z6uZk50XTIl:b-9sk9bc) ([raw file](https://github.com/cockroachdb/cockroach/blob/e18ed8683b83a57b1337f046a3278816117fd66b/pkg/ccl/changefeedccl/poller.go#L162)):*
> ```Go
> 				// We do this because resolved timestamps are supposed close out all
> 				// timestamps less than or equal.
> 				scanTime = p.mu.scanBoundaries[0].Next()
> ```

Ditto I don't get this either, maybe the comment needs to be expanded? Also, it seems like doing this when the scanBoundary is added might be a better place for this
___
*[pkg/ccl/changefeedccl/sink_cloudstorage.go, line 95 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/40696#-Lpi5Nl98LDPwXzT7joK:-LqbEpx22vptK5Nd0X79:bdb2qlv) ([raw file](https://github.com/cockroachdb/cockroach/blob/4206253e91dec8a5df6f8485bf61479715b5e2d3/pkg/ccl/changefeedccl/sink_cloudstorage.go#L95)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

I second Dan’s concerns here’s about correctness in the worst case. I think we need both a convincing argument for correctness and good testing around the new edge case: files occurring at the same timestamp from different sessions, either at the initial scan or resumption. 
</blockquote></details>

Yay! I am convinced \o/
___
*[pkg/ccl/changefeedccl/sink_cloudstorage.go, line 61 at r13](https://reviewable.io/reviews/cockroachdb/cockroach/40696#-LqbBxWa9uMzY4xlvLBA:-LqbBxWb-gxovgkQ5ysv:b-aert2c) ([raw file](https://github.com/cockroachdb/cockroach/blob/e18ed8683b83a57b1337f046a3278816117fd66b/pkg/ccl/changefeedccl/sink_cloudstorage.go#L61)):*
> ```Go
> 	// Note that this timestamp is an inclusive lower bound on the timestamps
> 	// of the row updates that can be seen in this file.
> 	minTs hlc.Timestamp
> ```

inclusiveLowerBoundTs?
___
*[pkg/ccl/changefeedccl/sink_cloudstorage.go, line 65 at r13](https://reviewable.io/reviews/cockroachdb/cockroach/40696#-LqbD5ADDSsu2cQOb7cJ:-LqbD5ADDSsu2cQOb7cK:bpg6l4s) ([raw file](https://github.com/cockroachdb/cockroach/blob/e18ed8683b83a57b1337f046a3278816117fd66b/pkg/ccl/changefeedccl/sink_cloudstorage.go#L65)):*
> ```Go
> }
> 
> // Changefeeds offer the following two ordering guarantees to external clients:
> ```

nit: start this like godoc even if the linter is not making you do it (because cloudStorageSink is unexported)

something like "cloudStorageSink writes changefeed output to files in the cloud (s3/gcs/http) maintaining our usual ordering guarantees though lexicographic filename ordering."
___
*[pkg/ccl/changefeedccl/sink_cloudstorage.go, line 77 at r13](https://reviewable.io/reviews/cockroachdb/cockroach/40696#-LqbCxytD0iwYFZwtGso:-LqbCxytD0iwYFZwtGsp:b-qhfzq6) ([raw file](https://github.com/cockroachdb/cockroach/blob/e18ed8683b83a57b1337f046a3278816117fd66b/pkg/ccl/changefeedccl/sink_cloudstorage.go#L77)):*
> ```Go
> // a number of distsql processors that each emit some part of the total changefeed.
> // These processors only write files containing row data (initially only in ndjson
> // format). This mapping is stable for a given distsql flow of a changefeed
> ```

initially only in ndjson format in this cloudStorageSink
___
*[pkg/ccl/changefeedccl/sink_cloudstorage.go, line 106 at r13](https://reviewable.io/reviews/cockroachdb/cockroach/40696#-LqbDiHW4AYSRVj9E2Lu:-LqbDiHW4AYSRVj9E2Lv:b3braxp) ([raw file](https://github.com/cockroachdb/cockroach/blob/e18ed8683b83a57b1337f046a3278816117fd66b/pkg/ccl/changefeedccl/sink_cloudstorage.go#L106)):*
> ```Go
> // Batching these row updates into files is complicated because:
> // a) We need to pick a representative timestamp for the file. This is required
> // for comparison with resolved timestamp filenames as part of guarantee.
> ```

as part of guarantee (2)?
___
*[pkg/ccl/changefeedccl/sink_cloudstorage.go, line 109 at r13](https://reviewable.io/reviews/cockroachdb/cockroach/40696#-LqbDrS81UJU-fI5Ebpq:-LqbDrS81UJU-fI5Ebpr:bour665) ([raw file](https://github.com/cockroachdb/cockroach/blob/e18ed8683b83a57b1337f046a3278816117fd66b/pkg/ccl/changefeedccl/sink_cloudstorage.go#L109)):*
> ```Go
> // b) For each topic, the row ordering guarantees must be preserved.
> // One intuitive way of solving (b) is to ensure that filenames are lexically
> // ordered the way they're emitted. This guarantees correctness as long as
> ```

filenames are emitted in strictly lexically increasing order (and then actually do this, see my other comment)
___
*[pkg/ccl/changefeedccl/sink_cloudstorage.go, line 232 at r13](https://reviewable.io/reviews/cockroachdb/cockroach/40696#-LqbFaNM8NPvphNpwuwk:-LqbFaNM8NPvphNpwuwl:b-dy97t9) ([raw file](https://github.com/cockroachdb/cockroach/blob/e18ed8683b83a57b1337f046a3278816117fd66b/pkg/ccl/changefeedccl/sink_cloudstorage.go#L232)):*
> ```Go
> // all e in integers. Similarly for X. Without loss of generality, lets say
> // there are 2 files Ye and Xf such that (1.1) Ye < Xf such that Xf contains an
> // unseen timestamp that is lower than at least one timestamp seen in Ye. Let's
> ```

super nit: /Let's call this timestamp t./Call this timestamp t./
___
*[pkg/ccl/changefeedccl/sink_cloudstorage.go, line 439 at r13](https://reviewable.io/reviews/cockroachdb/cockroach/40696#-LqaxluS8hzE3RkNfnfw:-LqaxluT332FJrmAi9-X:b-9pr6ga) ([raw file](https://github.com/cockroachdb/cockroach/blob/e18ed8683b83a57b1337f046a3278816117fd66b/pkg/ccl/changefeedccl/sink_cloudstorage.go#L439)):*
> ```Go
> 		s.fileID = 0
> 	} else if s.prevFileTs.Equal(file.minTs) {
> 		s.fileID++
> ```

I think werner talked me into not resetting the fileID last week. we have to pad it either way, so i kind of like knowing how many files a given sink instance has written
___
*[pkg/ccl/changefeedccl/sink_cloudstorage.go, line 456 at r13](https://reviewable.io/reviews/cockroachdb/cockroach/40696#-LqavRBt58A7m-BD6TQN:-LqavRBt58A7m-BD6TQO:bswskoh) ([raw file](https://github.com/cockroachdb/cockroach/blob/e18ed8683b83a57b1337f046a3278816117fd66b/pkg/ccl/changefeedccl/sink_cloudstorage.go#L456)):*
> ```Go
> 		ts, key.Topic, key.SchemaID, s.nodeID, s.sinkID, fileID, s.jobSessionID, s.ext)
> 
> 	s.prevFileTs = file.minTs
> ```

As discussed in the meeting on thursday, please add a check here with assertion error that this filename is strictly lexicographically greater than the last one. This requires tracking the last written filename and also rearranging the fields in the generated filename (topic and schemaID have to go after fileID). My preferred ordering is `<ts>-<sessionID>-<nodeID>-<sinkID>-<fileID>-<topic>-<schemaID>.ext`. This also means we don't have to pad schemaID which is nice
___
*[pkg/ccl/changefeedccl/cdctest/nemeses.go, line 45 at r13](https://reviewable.io/reviews/cockroachdb/cockroach/40696#-LqanrliEXTRBBYXEvCP:-LqanrliEXTRBBYXEvCQ:bj0dr58) ([raw file](https://github.com/cockroachdb/cockroach/blob/e18ed8683b83a57b1337f046a3278816117fd66b/pkg/ccl/changefeedccl/cdctest/nemeses.go#L45)):*
> ```Go
> 	rng, _ := randutil.NewPseudoRand()
> 
> 	eventPauseCount := 10
> ```

let's roachprod-stress this at some point if we haven't already
___
*[pkg/ccl/changefeedccl/cdctest/nemeses.go, line 50 at r13](https://reviewable.io/reviews/cockroachdb/cockroach/40696#-LqanDFQ54V_I9kZdpov:-LqanDFQ54V_I9kZdpow:bfsiwga) ([raw file](https://github.com/cockroachdb/cockroach/blob/e18ed8683b83a57b1337f046a3278816117fd66b/pkg/ccl/changefeedccl/cdctest/nemeses.go#L50)):*
> ```Go
> 		// have "correct" pause and unpause mechanisms for changefeeds that aren't
> 		// based on the jobs infrastructure. Enabling it for sinkless might require
> 		// support for "AS OF SYSTEM TIME" for changefeeds. See #41006 for more details.
> ```

nit: we have AS OF SYSTEM TIME support, we'd just have to use it in `sinklessFeed` (which hasn't been done because sinklessFeed would itself have to track the frontier, which is annoying)
___
*[pkg/jobs/jobspb/jobs.proto, line 209 at r13](https://reviewable.io/reviews/cockroachdb/cockroach/40696#-Lqaq4qC9pbZphQEF2on:-Lqaq4qC9pbZphQEF2oo:b-idjeas) ([raw file](https://github.com/cockroachdb/cockroach/blob/e18ed8683b83a57b1337f046a3278816117fd66b/pkg/jobs/jobspb/jobs.proto#L209)):*
> ```protobuf
>   // cloudStorageSink output files by different sessions of the same changefeed job.
>   // See `generateChangefeedSessionID` in changefeed_stmt.go.
>   string session_id = 8 [(gogoproto.customname) = "SessionID"];
> ```

comment that this is never persisted to the jobs table. in fact, i'm almost leaning toward saying we should do the session_id stuff inside the `makeCloudStorageSink` constructor and keep it super tightly scoped. the sinks in a single changefeed wouldn't have the same session_id, but they didn't before and I don't really think we care

then when we have a real session id from the jobs framework in 20.1, we can use that

**Review by ajwerner — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/40696)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @aayushshah15, @ajwerner, @danhhz, and @nvanbenschoten)

___
*[pkg/ccl/changefeedccl/changefeed_processors.go, line 147 at r13](https://reviewable.io/reviews/cockroachdb/cockroach/40696#-LqapWpwEEeZag84l0cA:-LqbMV104NHF3IONGB8C:b-s7h6yl) ([raw file](https://github.com/cockroachdb/cockroach/blob/e18ed8683b83a57b1337f046a3278816117fd66b/pkg/ccl/changefeedccl/changefeed_processors.go#L147)):*
<details><summary><i>Previously, danhhz (Daniel Harrison) wrote…</i></summary><blockquote>

as I mentioned in our meeting, I don't like this. It's so much more obvious to leave the span frontier at zero and then handle a zero frontier in the cloud storage sink
</blockquote></details>

One idea that came up is that if we're going to deal with that logic then I'm supportive of hiding the fact that this minTS is coming from a spanFrontier at all behind an abstraction that can be a conduit for comments. Something like:

```
type timestampLowerBoundOracle interface {
    inclusiveLowerBoundTS() hlc.Timestamp
}

type changeAggregatorLowerBoundOracle struct {
   sf *spanFrontier
   initialInclusiveLowerBound hlc.Timestamp
}

func (o *changeAggregatorLowerBoundOracle) inclusiveLowerBoundTS() hlc.Timestamp {
    if frontier := o.sf.Frontier(); !frontier.IsEmpty() {
        return frontier.Next()
    } 
    return o.initialInclusiveLowerBound
}
```

And then have `getSink` take a `timestampLowerBoundOracle`
___
*[pkg/ccl/changefeedccl/poller.go, line 110 at r13](https://reviewable.io/reviews/cockroachdb/cockroach/40696#-LqapLkK9A5Bnkt7ZdTB:-LqbOcs3-QV2sCL3GNgB:bkdg936) ([raw file](https://github.com/cockroachdb/cockroach/blob/e18ed8683b83a57b1337f046a3278816117fd66b/pkg/ccl/changefeedccl/poller.go#L110)):*
<details><summary><i>Previously, danhhz (Daniel Harrison) wrote…</i></summary><blockquote>

I don't get it. Maybe the comment needs to be expanded? Or maybe this Next would be more clear if it happens in a different place?
</blockquote></details>

If I understood Aayush's explanation, the issue he uncovered is that when we perform a catch-up scan (not an initial scan) we could emit rows which were exactly equal to the previous resolved timestamp. I guess now that I've typed this I don't understand why that's problematic as it should have been okay to just drop those rows. Why did we need to make this change again?
___
*[pkg/ccl/changefeedccl/sink_cloudstorage.go, line 262 at r14](https://reviewable.io/reviews/cockroachdb/cockroach/40696#-LqbMKfT5_o8PY5UWEuT:-LqbMKfUD0qYGLhi5VkS:b-jlwxxm) ([raw file](https://github.com/cockroachdb/cockroach/blob/a0747203fa8251bd8dcca4eed53c392770fb30e9/pkg/ccl/changefeedccl/sink_cloudstorage.go#L262)):*
> ```Go
> // we're back to the case where k = 2 with jobs P and Q. Thus, by induction we
> // have the required proof.
> ```

If we're going to make this in the style of a godoc comment then add ` //` here to connect it to the `cloudStorageSink`
___
*[pkg/jobs/jobspb/jobs.proto, line 209 at r13](https://reviewable.io/reviews/cockroachdb/cockroach/40696#-Lqaq4qC9pbZphQEF2on:-LqbOJqG8cgTcURtxxPA:b-z6ojt3) ([raw file](https://github.com/cockroachdb/cockroach/blob/e18ed8683b83a57b1337f046a3278816117fd66b/pkg/jobs/jobspb/jobs.proto#L209)):*
<details><summary><i>Previously, danhhz (Daniel Harrison) wrote…</i></summary><blockquote>

comment that this is never persisted to the jobs table. in fact, i'm almost leaning toward saying we should do the session_id stuff inside the `makeCloudStorageSink` constructor and keep it super tightly scoped. the sinks in a single changefeed wouldn't have the same session_id, but they didn't before and I don't really think we care

then when we have a real session id from the jobs framework in 20.1, we can use that
</blockquote></details>

Seems reasonable to me.

**Comment by aayushshah15** [comment]
___
*[pkg/ccl/changefeedccl/poller.go, line 162 at r13](https://reviewable.io/reviews/cockroachdb/cockroach/40696#-Lqau7a16z6uZk50XTIk:-LqbOfuXAB6Dp73iSeby:b-8d1130) ([raw file](https://github.com/cockroachdb/cockroach/blob/e18ed8683b83a57b1337f046a3278816117fd66b/pkg/ccl/changefeedccl/poller.go#L162)):*
<details><summary><i>Previously, danhhz (Daniel Harrison) wrote…</i></summary><blockquote>

Ditto I don't get this either, maybe the comment needs to be expanded? Also, it seems like doing this when the scanBoundary is added might be a better place for this
</blockquote></details>

I added a better comment. I'll paste it here for discussion:
```
// This condition means this a backfill scan. We want to set scanTime
// to the successor of the scan boundary because this boundary is set
// to the last modification timestamp of the altered table's table
// descriptor. This timestamp can be a resolved timestamp which could
// have already been forwarded to the `changeAggregator` (and consquently
// to the `changeFrontier`), and emitted as a globally resolved timestamp.
// Thus, emitting row updates with the scan boundary as is could cause
// a consumption bug (since the client is free to ignore all the timestamps
// less than or equal to a globally resolved timestamp).
```

**Comment by aayushshah15** [comment]
___
*[pkg/ccl/changefeedccl/poller.go, line 162 at r13](https://reviewable.io/reviews/cockroachdb/cockroach/40696#-Lqau7a16z6uZk50XTIk:-LqbQ5Bz4z1WUchl9bgt:b-qhwhx5) ([raw file](https://github.com/cockroachdb/cockroach/blob/e18ed8683b83a57b1337f046a3278816117fd66b/pkg/ccl/changefeedccl/poller.go#L162)):*
<details><summary><i>Previously, aayushshah15 (Aayush Shah) wrote…</i></summary><blockquote>

I added a better comment. I'll paste it here for discussion:
```
// This condition means this a backfill scan. We want to set scanTime
// to the successor of the scan boundary because this boundary is set
// to the last modification timestamp of the altered table's table
// descriptor. This timestamp can be a resolved timestamp which could
// have already been forwarded to the `changeAggregator` (and consquently
// to the `changeFrontier`), and emitted as a globally resolved timestamp.
// Thus, emitting row updates with the scan boundary as is could cause
// a consumption bug (since the client is free to ignore all the timestamps
// less than or equal to a globally resolved timestamp).
```
</blockquote></details>

Additionally, `Next()`ing when adding the scan boundary might make certain other things a little harder to reason about since we compare these boundaries with other timestamps in the main poller goroutine (see lines 258 to 303 in `poller.go`). So the reason I'm doing only this when calling `exportScansParallel` is because it seemed like a much less intrusive way of doing it. `exportScansParallel` only uses this timestamp to attach it to the row updates it streams out, and nothing else.

**Comment by aayushshah15** [comment]
>If I understood Aayush's explanation, the issue he uncovered is that when we perform a catch-up scan (not an initial scan) we could emit rows which were exactly equal to the previous resolved timestamp. I guess now that I've typed this I don't understand why that's problematic as it should have been okay to just drop those rows. Why did we need to make this change again?

As discussed offline: the problem is with emitting row updates after an `ALTER TABLE ... WITH DEFAULT` statement where an additional column is added with a default value. Please let me know if the updated comment I posted about still seems unclear.

**Review by danhhz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/40696)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @aayushshah15, @ajwerner, @danhhz, and @nvanbenschoten)

___
*[pkg/ccl/changefeedccl/changefeed_processors.go, line 147 at r13](https://reviewable.io/reviews/cockroachdb/cockroach/40696#-LqapWpwEEeZag84l0cA:-LqbZX_R1KtCmiiEHveQ:b-ibgm0m) ([raw file](https://github.com/cockroachdb/cockroach/blob/e18ed8683b83a57b1337f046a3278816117fd66b/pkg/ccl/changefeedccl/changefeed_processors.go#L147)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

One idea that came up is that if we're going to deal with that logic then I'm supportive of hiding the fact that this minTS is coming from a spanFrontier at all behind an abstraction that can be a conduit for comments. Something like:

```
type timestampLowerBoundOracle interface {
    inclusiveLowerBoundTS() hlc.Timestamp
}

type changeAggregatorLowerBoundOracle struct {
   sf *spanFrontier
   initialInclusiveLowerBound hlc.Timestamp
}

func (o *changeAggregatorLowerBoundOracle) inclusiveLowerBoundTS() hlc.Timestamp {
    if frontier := o.sf.Frontier(); !frontier.IsEmpty() {
        return frontier.Next()
    } 
    return o.initialInclusiveLowerBound
}
```

And then have `getSink` take a `timestampLowerBoundOracle`
</blockquote></details>

that wfm
___
*[pkg/ccl/changefeedccl/poller.go, line 162 at r13](https://reviewable.io/reviews/cockroachdb/cockroach/40696#-Lqau7a16z6uZk50XTIk:-Lqb_5KsAv5f58wQtjPr:bslvr9t) ([raw file](https://github.com/cockroachdb/cockroach/blob/e18ed8683b83a57b1337f046a3278816117fd66b/pkg/ccl/changefeedccl/poller.go#L162)):*
<details><summary><i>Previously, aayushshah15 (Aayush Shah) wrote…</i></summary><blockquote>

Additionally, `Next()`ing when adding the scan boundary might make certain other things a little harder to reason about since we compare these boundaries with other timestamps in the main poller goroutine (see lines 258 to 303 in `poller.go`). So the reason I'm doing only this when calling `exportScansParallel` is because it seemed like a much less intrusive way of doing it. `exportScansParallel` only uses this timestamp to attach it to the row updates it streams out, and nothing else.
</blockquote></details>

I still don't understand. This explanation seems too in the weeds. Can you back up and give it to me from 10,000 ft? I ask because this seems like a hack and I'd like to understand what a more principled fix would look like before dismissing it as too invasive

**Review by danhhz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/40696)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @aayushshah15, @ajwerner, @danhhz, and @nvanbenschoten)

___
*[pkg/ccl/changefeedccl/poller.go, line 162 at r13](https://reviewable.io/reviews/cockroachdb/cockroach/40696#-Lqau7a16z6uZk50XTIk:-LqbcEd_0KsP78PKH6By:bebxcyx) ([raw file](https://github.com/cockroachdb/cockroach/blob/e18ed8683b83a57b1337f046a3278816117fd66b/pkg/ccl/changefeedccl/poller.go#L162)):*
<details><summary><i>Previously, danhhz (Daniel Harrison) wrote…</i></summary><blockquote>

I still don't understand. This explanation seems too in the weeds. Can you back up and give it to me from 10,000 ft? I ask because this seems like a hack and I'd like to understand what a more principled fix would look like before dismissing it as too invasive
</blockquote></details>

Specifically, one thing I want to know is whether the other sinks are incorrect because of this. If they're fine, why can't we fix it inside the cloud storage sink?

**Comment by aayushshah15** [comment]
___
*[pkg/ccl/changefeedccl/poller.go, line 162 at r13](https://reviewable.io/reviews/cockroachdb/cockroach/40696#-Lqau7a16z6uZk50XTIk:-LqbejJvBrpNIipgrceh:b-javpsb) ([raw file](https://github.com/cockroachdb/cockroach/blob/e18ed8683b83a57b1337f046a3278816117fd66b/pkg/ccl/changefeedccl/poller.go#L162)):*
<details><summary><i>Previously, danhhz (Daniel Harrison) wrote…</i></summary><blockquote>

Specifically, one thing I want to know is whether the other sinks are incorrect because of this. If they're fine, why can't we fix it inside the cloud storage sink?
</blockquote></details>

Yes, the other sinks would be incorrect because of this.

To elaborate:

The poller uses `exportSpansParallel` to perform its initial scan of the table (when the changefeed starts) and to perform a backfill (for example: when a table thats being watched by the changefeed gets altered to contain a new column with a default value). The poller detects a schema change by keeping track of the corresponding table descriptor's last `ModificationTime`. When this changes, it adds the new `ModificationTime` to `scanBoundaries` to trigger a full scan of the underlying table. 

The issue with this approach is that this `ModificationTime` timestamp is often (or always in my testing) the last resolved timestamp that was emitted by the poller. So what ends up happening is that the `changeAggregator` forwards its local frontier using this resolved timestamp and *then* the changeFrontier sees all these backfill-related row updates at the same timestamp (which is the incorrect part).

**Review by danhhz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/40696)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @aayushshah15, @ajwerner, @danhhz, and @nvanbenschoten)

___
*[pkg/ccl/changefeedccl/poller.go, line 162 at r13](https://reviewable.io/reviews/cockroachdb/cockroach/40696#-Lqau7a16z6uZk50XTIk:-LqbnvxN-MaPXmR3SUbv:b-exosra) ([raw file](https://github.com/cockroachdb/cockroach/blob/e18ed8683b83a57b1337f046a3278816117fd66b/pkg/ccl/changefeedccl/poller.go#L162)):*
<details><summary><i>Previously, aayushshah15 (Aayush Shah) wrote…</i></summary><blockquote>

Yes, the other sinks would be incorrect because of this.

To elaborate:

The poller uses `exportSpansParallel` to perform its initial scan of the table (when the changefeed starts) and to perform a backfill (for example: when a table thats being watched by the changefeed gets altered to contain a new column with a default value). The poller detects a schema change by keeping track of the corresponding table descriptor's last `ModificationTime`. When this changes, it adds the new `ModificationTime` to `scanBoundaries` to trigger a full scan of the underlying table. 

The issue with this approach is that this `ModificationTime` timestamp is often (or always in my testing) the last resolved timestamp that was emitted by the poller. So what ends up happening is that the `changeAggregator` forwards its local frontier using this resolved timestamp and *then* the changeFrontier sees all these backfill-related row updates at the same timestamp (which is the incorrect part).
</blockquote></details>

We discussed this offline. This is a new bug in all changefeeds and will have to be backported (great find!), so I encouraged Aayush to pull it into a separate PR to make that easy and to get this cloud sink fix, which is already a huge change, merged earlier.

Also as a result of our discussion, I suspect that the fix is not advancing the scan timestamp, but rather investigating and eliminating the unexpected resolved timestamp. Aayush will investigate exactly what's happening after the cloud sink stuff is done.

**Review by aayushshah15 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/40696)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @aayushshah15, @ajwerner, @danhhz, and @nvanbenschoten)

___
*[pkg/ccl/changefeedccl/poller.go, line 162 at r13](https://reviewable.io/reviews/cockroachdb/cockroach/40696#-Lqau7a16z6uZk50XTIk:-LqcCYhsEzFllNUUWEIV:b-tav93u) ([raw file](https://github.com/cockroachdb/cockroach/blob/e18ed8683b83a57b1337f046a3278816117fd66b/pkg/ccl/changefeedccl/poller.go#L162)):*
<details><summary><i>Previously, danhhz (Daniel Harrison) wrote…</i></summary><blockquote>

We discussed this offline. This is a new bug in all changefeeds and will have to be backported (great find!), so I encouraged Aayush to pull it into a separate PR to make that easy and to get this cloud sink fix, which is already a huge change, merged earlier.

Also as a result of our discussion, I suspect that the fix is not advancing the scan timestamp, but rather investigating and eliminating the unexpected resolved timestamp. Aayush will investigate exactly what's happening after the cloud sink stuff is done.
</blockquote></details>

Created issue #41415 to track this. 
___
*[pkg/ccl/changefeedccl/cdctest/nemeses.go, line 50 at r13](https://reviewable.io/reviews/cockroachdb/cockroach/40696#-LqanDFQ54V_I9kZdpov:-LqbuEST86gqp1jpefvd:b-2i3kor) ([raw file](https://github.com/cockroachdb/cockroach/blob/e18ed8683b83a57b1337f046a3278816117fd66b/pkg/ccl/changefeedccl/cdctest/nemeses.go#L50)):*
<details><summary><i>Previously, danhhz (Daniel Harrison) wrote…</i></summary><blockquote>

nit: we have AS OF SYSTEM TIME support, we'd just have to use it in `sinklessFeed` (which hasn't been done because sinklessFeed would itself have to track the frontier, which is annoying)
</blockquote></details>

Ah good to know. I'll update the referenced issue.

**Review by danhhz — COMMENTED** [review]
I'll take a last pass after you get the tests deflaked, but this seems just about ready to go!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/40696#-:-LqheRr7-P7V713KIJHq:b-qyj0r5)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @aayushshah15, @ajwerner, @danhhz, and @nvanbenschoten)

___
*[pkg/ccl/changefeedccl/changefeed_processors.go, line 169 at r16](https://reviewable.io/reviews/cockroachdb/cockroach/40696#-Lqhd5Y2CXf3YjEHbPiE:-Lqhd5Y3BJQl3o0fwaJq:b-25wyfe) ([raw file](https://github.com/cockroachdb/cockroach/blob/2293f4bf0acc5e09b386bc73b3eda9dd62a55d19/pkg/ccl/changefeedccl/changefeed_processors.go#L169)):*
> ```Go
> 	// monotonic fashion.
> 	sf := makeSpanFrontier(spans...)
> 	timestampOracle := &changeAggregatorLowerBoundOracle{sf: sf, initialInclusiveLowerBound: ca.spec.Feed.StatementTime}
> ```

super nit: move this line below the for/range that does the watch forwarding
___
*[pkg/ccl/changefeedccl/sink_cloudstorage.go, line 55 at r16](https://reviewable.io/reviews/cockroachdb/cockroach/40696#-Lqh_hgS87d4F-RVfJ1E:-Lqh_hgS87d4F-RVfJ1F:bb7aypj) ([raw file](https://github.com/cockroachdb/cockroach/blob/2293f4bf0acc5e09b386bc73b3eda9dd62a55d19/pkg/ccl/changefeedccl/sink_cloudstorage.go#L55)):*
> ```Go
> 
> type cloudStorageSinkFile struct {
> 	// `inclusiveLowerBoundTs` is the local spanFrontier's Frontier().Next() timestamp as of
> ```

this comment is now slightly out of date
___
*[pkg/ccl/changefeedccl/sink_cloudstorage.go, line 280 at r16](https://reviewable.io/reviews/cockroachdb/cockroach/40696#-LqhaF3YEs_xV2S5qIXt:-LqhaF3YEs_xV2S5qIXu:bpnclo) ([raw file](https://github.com/cockroachdb/cockroach/blob/2293f4bf0acc5e09b386bc73b3eda9dd62a55d19/pkg/ccl/changefeedccl/sink_cloudstorage.go#L280)):*
> ```Go
> 	timestampOracle       timestampLowerBoundOracle
> 	jobSessionID          string
> 	inclusiveLowerBoundTs hlc.Timestamp
> ```

nit: maybe something like dataFileTs?

separate out the fields that are only used in EmitRow/Flush into a block with a comment at the top
___
*[pkg/ccl/changefeedccl/sink_cloudstorage.go, line 307 at r16](https://reviewable.io/reviews/cockroachdb/cockroach/40696#-LqhaOUD7i3_bvs_LBQw:-LqhaOUD7i3_bvs_LBQx:b46j1ud) ([raw file](https://github.com/cockroachdb/cockroach/blob/2293f4bf0acc5e09b386bc73b3eda9dd62a55d19/pkg/ccl/changefeedccl/sink_cloudstorage.go#L307)):*
> ```Go
> 		partitionFormat:   defaultPartitionFormat,
> 		timestampOracle:   timestampOracle,
> 		jobSessionID:      generateChangefeedSessionID(),
> ```

put a TODO here to use the job frameworks session id once it has one
___
*[pkg/ccl/changefeedccl/sink_cloudstorage.go, line 364 at r16](https://reviewable.io/reviews/cockroachdb/cockroach/40696#-LqhavJL6UXwiAQJU-st:-LqhavJL6UXwiAQJU-su:bn6ezvc) ([raw file](https://github.com/cockroachdb/cockroach/blob/2293f4bf0acc5e09b386bc73b3eda9dd62a55d19/pkg/ccl/changefeedccl/sink_cloudstorage.go#L364)):*
> ```Go
> 		// careful to bound the size of the memory held by the pool.
> 		inclusiveLowerBoundTs := s.inclusiveLowerBoundTs
> 		file = &cloudStorageSinkFile{inclusiveLowerBoundTs: inclusiveLowerBoundTs}
> ```

this no longer needs to be kept on the file structs
___
*[pkg/ccl/changefeedccl/sink_cloudstorage.go, line 422 at r16](https://reviewable.io/reviews/cockroachdb/cockroach/40696#-LqhadSi2NbUDYV-bs4I:-LqhadSjE6Adunw6VAQF:bn2njgx) ([raw file](https://github.com/cockroachdb/cockroach/blob/2293f4bf0acc5e09b386bc73b3eda9dd62a55d19/pkg/ccl/changefeedccl/sink_cloudstorage.go#L422)):*
> ```Go
> 		delete(s.files, key)
> 	}
> 	s.inclusiveLowerBoundTs = s.timestampOracle.inclusiveLowerBoundTS()
> ```

short comment here about what's going on and a pointer back to the big comment. in fact, it might be clearer to store the formatted string version (and partition) on cloudStorageSink
___
*[pkg/ccl/changefeedccl/sink_cloudstorage.go, line 442 at r16](https://reviewable.io/reviews/cockroachdb/cockroach/40696#-LqheG8A4OMpkEUfBu1A:-LqheG8A4OMpkEUfBu1B:b-5yt62s) ([raw file](https://github.com/cockroachdb/cockroach/blob/2293f4bf0acc5e09b386bc73b3eda9dd62a55d19/pkg/ccl/changefeedccl/sink_cloudstorage.go#L442)):*
> ```Go
> 	s.fileID++
> 	// Pad file ID to maintain lexical ordering among files from the same sink.
> 	// Pad SchemaID to maintain ordering across schema changes.
> ```

we're no longer padding schemaID

**Review by danhhz — COMMENTED** [review]
:lgtm_strong: great work! let's merge this and backport it to 19.2 \o/

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/40696#-:-LqlWm3O89gZzVoikVrF:bigb8ak)* status: :shipit: complete! 2 of 0 LGTMs obtained (waiting on @aayushshah15, @ajwerner, @danhhz, and @nvanbenschoten)

___
*[pkg/ccl/changefeedccl/sink_cloudstorage.go, line 59 at r17](https://reviewable.io/reviews/cockroachdb/cockroach/40696#-LqlTuqe7x5WVxIYuQ_h:-LqlTuqe7x5WVxIYuQ_i:bozqqds) ([raw file](https://github.com/cockroachdb/cockroach/blob/3a68ec724d029501032b2f3b95e4b92b9f5c7a2c/pkg/ccl/changefeedccl/sink_cloudstorage.go#L59)):*
> ```Go
> 	// chosen to preserve CDC's external ordering guarantees. See comment on
> 	// cloudStorageSink below for more details.
> 	// Note that this timestamp is an inclusive lower bound on the timestamps
> ```

this field is no longer present
___
*[pkg/ccl/changefeedccl/sink_cloudstorage.go, line 284 at r17](https://reviewable.io/reviews/cockroachdb/cockroach/40696#-LqlWMht0nZslOAsDeyq:-LqlWMhu2f9lGe6nTM6z:baa3d0f) ([raw file](https://github.com/cockroachdb/cockroach/blob/3a68ec724d029501032b2f3b95e4b92b9f5c7a2c/pkg/ccl/changefeedccl/sink_cloudstorage.go#L284)):*
> ```Go
> 	files           map[cloudStorageSinkKey]*cloudStorageSinkFile
> 	timestampOracle timestampLowerBoundOracle
> 	// TODO(aayush): Use the jobs framework's session ID once that's available.
> ```

nit: this TODO is probably better placed at the site of the generateChangefeedSessionID call
___
*[pkg/ccl/changefeedccl/sink_cloudstorage.go, line 454 at r17](https://reviewable.io/reviews/cockroachdb/cockroach/40696#-LqlVwyyEUkfPF-b-c0I:-LqlVwyyEUkfPF-b-c0J:b-jp8xt0) ([raw file](https://github.com/cockroachdb/cockroach/blob/3a68ec724d029501032b2f3b95e4b92b9f5c7a2c/pkg/ccl/changefeedccl/sink_cloudstorage.go#L454)):*
> ```Go
> 	s.fileID++
> 	// Pad file ID to maintain lexical ordering among files from the same sink.
> 	// Pad SchemaID to maintain ordering across schema changes.
> ```

i think reviewable ate this comment, but schemaid is no longer padded

**Review by aayushshah15 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/40696)* status: :shipit: complete! 2 of 0 LGTMs obtained (waiting on @aayushshah15, @ajwerner, @danhhz, and @nvanbenschoten)

___
*[pkg/ccl/changefeedccl/sink_cloudstorage.go, line 59 at r17](https://reviewable.io/reviews/cockroachdb/cockroach/40696#-LqlTuqe7x5WVxIYuQ_h:-LqlWzUo2nMzR8nyrPgF:b-x3e3uz) ([raw file](https://github.com/cockroachdb/cockroach/blob/3a68ec724d029501032b2f3b95e4b92b9f5c7a2c/pkg/ccl/changefeedccl/sink_cloudstorage.go#L59)):*
<details><summary><i>Previously, danhhz (Daniel Harrison) wrote…</i></summary><blockquote>

this field is no longer present
</blockquote></details>

oops, my apologies, I thought I removed the whole blob.
___
*[pkg/ccl/changefeedccl/sink_cloudstorage.go, line 454 at r17](https://reviewable.io/reviews/cockroachdb/cockroach/40696#-LqlVwyyEUkfPF-b-c0I:-LqlXGiODcEa3eR9octn:b-94xsrz) ([raw file](https://github.com/cockroachdb/cockroach/blob/3a68ec724d029501032b2f3b95e4b92b9f5c7a2c/pkg/ccl/changefeedccl/sink_cloudstorage.go#L454)):*
<details><summary><i>Previously, danhhz (Daniel Harrison) wrote…</i></summary><blockquote>

i think reviewable ate this comment, but schemaid is no longer padded
</blockquote></details>

huh thought I did this too, not sure what happened, it's possible some of my changes were unstaged when I switched to master to test out the `roachprod-stressrace` thing.

**Comment by aayushshah15** [comment]
thanks for spending so much time on this with me! @ajwerner and @danhhz 

bors r+

**Comment by danhhz** [comment]
Yes, absolutely
