### PR TITLE
backup: add retry loop to `doDownloadFiles`

### LINKED ISSUE #148081: restore: implement retry policy for `doDownloadFiles`
Currently, any error that bubbles up from `doDownloadFiles` (e.g. a node blip) causes the online/fast restore to fail. We should have a very generous retry policy, aside from missing sst errors here. This would could be lumped into https://github.com/cockroachdb/cockroach/issues/148028

Jira issue: CRDB-51390

Epic CRDB-51394

### PR DESCRIPTION
**Pull request by kev-cao**
Previously, `doDownloadFiles` would immediately fail the download job upon encountering an error. This commit teaches the download workers to retry the download requests before giving up and failing.

Epic: CRDB-51394

Fixes: #148081

Release note: Download phase of fast restore now will retry downloads before giving up.

### CODE REVIEW

File: pkg/backup/restore_online_test.go [hunk 1]
```diff
@@ -581,6 +583,65 @@ func TestOnlineRestoreErrors(t *testing.T) {
...
+	t.Logf("always fail download requests: %t", alwaysFail)
+	totalFailures := int32(rng.Intn(maxDownloadAttempts-1) + 1)
+	var currentFailures atomic.Int32
+
+	clusterArgs := base.TestClusterArgs{
+		ServerArgs: base.TestServerArgs{
+			DefaultTestTenant: base.TestIsSpecificToStorageLayerAndNeedsASystemTenant,
+			Knobs: base.TestingKnobs{
+				BackupRestore: &sql.BackupRestoreTestingKnobs{
+					RunBeforeSendingDownloadSpan: func() error {
```
Comment (kev-cao) [inline pkg/backup/restore_online_test.go:605]: I'm wondering if there's a better way to go about this instead of a testing knob? I was originally thinking of a dependency injection of the `TenantStatusServer`, but mocking the handling of `DownloadSpanRequest` would also require appropriate mocking of `SpanStatsRequest`.

Also is there an easier way to inject a `ExecutorConfig`? I see that changefeeds does so via a testing knob that replaces the `execCfg` in the DistSQL processor.

File: pkg/backup/restore_online.go [hunk 2]
```diff
@@ -556,14 +557,28 @@ func (r *restoreResumer) sendDownloadWorker(
...
+		// still spans to download (e.g. because of a rabalancing).
 		for rt := retry.StartWithCtx(
 			ctx, retry.Options{InitialBackoff: time.Millisecond * 100, MaxBackoff: time.Second * 10},
 		); ; rt.Next() {
 			if err := ctx.Err(); err != nil {
 				return err
 			}
 
-			if err := sendDownloadSpan(ctx, execCtx, spans); err != nil {
+			if err := retry.WithMaxAttempts(ctx, retry.Options{
```
Comment (dt) [inline pkg/backup/restore_online.go]: should we push this retry down into `sendDownloadSpans` so that we retry _individual_ requests 5 times?

Comment (kev-cao) [reply pkg/backup/restore_online.go]: `sendDownloadSpan` pretty much just sends a request right? Although it does mean we don't open a tracing span for each retry or decode errors for each request. I'll update it

Comment (dt) [reply pkg/backup/restore_online.go]: hm, yeah, you're right. I was thinking of the fan-out and retying the request that is sent to _each node_, but I guess that doesn't actually happen until you get into status server, over here: https://github.com/cockroachdb/cockroach/blob/master/pkg/server/span_download.go#L79

File: pkg/backup/restore_online_test.go (hunk 1 above)
Comment (dt) [reply pkg/backup/restore_online_test.go:605]: Yeah, I don't think it is worth mocking it out just to test the loop. In an ideal world we'd have perfect coverage but in reality these sorts of retry paths typically just get validated with the odd manual test and roachtests

File: pkg/backup/restore_online.go (hunk 2 above)
Comment (dt) [reply pkg/backup/restore_online.go]: Yeah, I guess I see some benefit to retrying the one call to DownloadSpans() in case finding nodes hits a gossip error or something, which both this iteration and what you had here previously did. I might suggest we _also_ put a retry inside `nodeFn` to add per-node retries to the fan-out so a brief failure from one node doesn't fail the whole call, but as far as retrying the whole call to the status server, I think your previous iteration was maybe actually tidier than it is just moved into `sendDownloadSpans` (my bad, sorry!)

Comment (kev-cao) [reply pkg/backup/restore_online.go]: Gotcha, yeah the code was certainly a bit cleaner. No worries, still have the commit hash so easy revert!

Comment (dt) [reply pkg/backup/restore_online.go]: Do you think it is worth adding a retry loop per node, inside `nodeFn` in span_download.go ? otherwise a fixed 5 tries here at this level seems like it requires a lower chance of failure per request for a larger cluster to send a request to every node and still stay under 5

Comment (kev-cao) [reply pkg/backup/restore_online.go]: It might be, although couldn't an argument be made that that's essentially always true for most requests across the cluster? I guess the difference is found in requests that only need quorum (which isn't sensitive to the number of nodes in the cluster) vs requests that need every node to succeed (like this one).

Comment (dt) [reply pkg/backup/restore_online.go]: well for most requests across the cluster, we _do_ put a retry loop around individual requests: backup_processor.go retries individual export requests, restore/import/etc all retry individual `AddSSTable` requests in sst_adder.go, etc. In those jobs, i AddSST or Export requests need, say, up to 5 attempts to be reliable, each request is given those attempts, regardless of if the job has to to 100 requests or 1M.

Here, if we just put a 5 attempt retry around `TenantStatusServer.DownloadSpan`, since the implementation of this function needs to make an RPC to every node, if any one of those RPCs needs X attempts to be reliable but we only try each one and the set a fixed number of times, then making the set larger reduces the effective allowed attempts per node.

Comment (kev-cao) [reply pkg/backup/restore_online.go]: Yeah that checks out to me, thanks for the explanation! Updated

**Review by dt — APPROVED** [review]

File: pkg/server/span_download.go [hunk 3]
```diff
@@ -63,7 +66,19 @@ func (s *systemStatusServer) DownloadSpan(
...
+		for r := retry.StartWithCtx(ctx, retry.Options{
+			InitialBackoff: time.Millisecond * 100,
+			MaxBackoff:     time.Second,
+			MaxRetries:     perNodeMaxDownloadAttempts - 1,
+		}); r.Next(); {
+			nodeResp, err = status.DownloadSpan(ctx, &remoteRequest)
+			if err == nil && len(resp.Errors) == 0 {
+				break
+			}
+		}
```
Comment (dt) [inline pkg/server/span_download.go:91]: I sometimes am glad when I remember to log the err in the case where we are tying again since otherwise it can be a little opaque when we just see the rpcs are higher than we expect. /2¢

Comment (kev-cao) [reply pkg/server/span_download.go:91]: Yeah that's a good point, I'll add that too

**Comment by kev-cao** [comment]
TFTR!

bors r=dt
