### PR TITLE
changefeedccl: give notice when metrics_label set without child_metrics

### LINKED ISSUE #75682: changefeedccl: fail changefeed when server.child_metrics.enabled cluster setting is false and metrics label config used
See: https://cockroachlabs.atlassian.net/wiki/spaces/CDC/pages/2398552506/22.1+Metrics+Labels+Acceptance+Testing for reproducibility

When creating a changefeed using the CREATE CHANGEFED ... WITH metrics_label=X configuration the user must set the cluster setting server.child_metrics.enabled=true in order for the feature to work. If they do not set this cluster setting, we still allow them to create the changefeed, but the metrics label feature is silently not applied. We should instead fail the changefeed creation when this happens, with a similar error message to when COCKROACH_EXPERIMENTAL_ENABLE_PER_CHANGEFEED_METRICS=true is not set:

image

Jira issue: CRDB-12779

Epic CRDB-13931

### PR DESCRIPTION
**Pull request by samiskin**
Resolves #75682

Surfaces a notice of
```
server.child_metrics.enabled is set to false, metrics will only be published to the '<scope>' label when it is set to true"
```
When child_metrics setting isn't enabled during changefeed creation

Release note (enterprise change): Changefeeds created/altered with a metrics_label set while server.child_metrics.enabled is false will now provide the user a notice upon creation.

### CODE REVIEW

File: pkg/server/status/recorder.go [hunk 1]
```diff
@@ -86,7 +86,7 @@ type storeMetrics interface {
 	Registry() *metric.Registry
 }
 
-var childMetricsEnabled = settings.RegisterBoolSetting(
+var ChildMetricsEnabled = settings.RegisterBoolSetting(
```
Comment (miretskiy) [inline pkg/server/status/recorder.go:89]: exported variables need a comment.

**Review by miretskiy — APPROVED** [review]

**Comment by rail** [comment]
bors single on

**Comment by rail** [comment]
bors r-
We have temporarily disabled bors for merges. Please merge the PR manually when all required checks pass.

**Comment by rail** [comment]
bors r-
We have temporarily disabled bors for merges. Please merge the PR manually when all required checks pass.
