### PR TITLE
logical: fix bug in tombstone updater

### LINKED ISSUE #159306: roachtest: ldr/conflict failed
**Note:** This build has runtime assertions enabled. If the same failure was hit in a run without assertions enabled, there should be a similar failure without this message. If there isn&#39;t one, then this failure is likely due to an assertion violation or (assertion) timeout.

roachtest.ldr/conflict [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/20847152?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/20847152?buildTab=artifacts#/ldr/conflict) on release-26.1 @ [e15b1ecc444676ba53266770e0b758de9ae72d22](https://github.com/cockroachdb/cockroach/commits/e15b1ecc444676ba53266770e0b758de9ae72d22):

Failed with:

```
(soon.go:60).SucceedsWithin: condition failed to evaluate within 2m0s: pq: replica unavailable: (n3,s3):2 unable to serve request to r34:/NamespaceTable/{30-Max} [(n1,s1):1, (n3,s3):2, (n2,s2):3, next=4, gen=4]: lost quorum (down: (n1,s1):1,(n2,s2):3); closed timestamp: 1765482010.674232937,0 (2025-12-11 19:40:10); raft status: {"id":"2","term":7,"vote":"2","commit":39,"lead":"0","leadEpoch":"0","raftState":"StateFollower","applied":39,"progress":{},"leadtransferee":"0"}: replica has been leaderless for 1m0s
test artifacts and logs in: /artifacts/ldr/conflict/run_1
```
Cluster Node to Ip Mapping:
| Node | Public IP | Private IP |
| --- | --- | --- |
| teamcity-20847152-1765436998-228-n7cpu4-0001 | 34.148.40.145 | 10.142.0.135 |
| teamcity-20847152-1765436998-228-n7cpu4-0002 | 35.237.223.91 | 10.142.0.122 |
| teamcity-20847152-1765436998-228-n7cpu4-0003 | 34.74.6.195 | 10.142.0.123 |
| teamcity-20847152-1765436998-228-n7cpu4-0004 | 35.185.115.13 | 10.142.0.131 |
| teamcity-20847152-1765436998-228-n7cpu4-0005 | 34.148.7.200 | 10.142.0.117 |
| teamcity-20847152-1765436998-228-n7cpu4-0006 | 34.23.199.26 | 10.142.0.133 |
| teamcity-20847152-1765436998-228-n7cpu4-0007 | 34.23.224.170 | 10.142.0.140 |

Parameters:
 - <code>arch=amd64</code>
 - <code>cloud=gce</code>
 - <code>coverageBuild=false</code>
 - <code>cpu=4</code>
 - <code>encrypted=false</code>
 - <code>fs=ext4</code>
 - <code>localSSD=false</code>
 - <code>metamorphicLeases=default</code>
 - <code>metamorphicWriteBuffering=true</code>
 - <code>runtimeAssertionsBuild=true</code>
 - <code>ssd=0</code>
<details><summary>Help</summary>
<p>

See: [roachtest README](https://github.com/cockroachdb/cockroach/blob/master/pkg/cmd/roachtest/README.md)

See: [How To Investigate \(internal\)](https://cockroachlabs.atlassian.net/l/c/SSSBr8c7)

See: [Grafana](https://go.crdb.dev/roachtest-grafana/teamcity-20847152/ldr-conflict/1765481859835/1765484335407)

</p>
</details>
<details><summary>Same failure on other branches</summary>
<p>

- #156714 roachtest: ldr/conflict failed [A-disaster-recovery C-test-failure O-roachtest O-robot T-disaster-recovery branch-master]
</p>
</details>
/cc @cockroachdb/disaster-recovery
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*ldr/conflict.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/bazci/githubpost/issues)

</sub>

Jira issue: CRDB-57774

### PR DESCRIPTION
**Pull request by jeffswenson**
This fixes a bug in the tombstone updater. The tombstone decoder was using the columns decoded by the kv writer when it needs to expect the columns decoded by the sql/crud writers. There is one difference between these two sets of columns that impacts computed columns:

1. The sql/crud writer only decode computed columns that are in the primary key.
2. The kv writer decodes virtual computed columns in the primary key and all stored computed columns in the row.

This mismatch can cause panics if the stored column is in an index (which is what the conflict workload noticed) and it can cause the tombstone updater to generate incorrect keys if there is a stored computed column with a lower column id than the primary key column. If that happened, and we hit the tombstone update race condition, we would issue a cput for the wrong row. That would end up creating a tombstone with an origin time stamp at that wrong key value. This would not cause data corruption, since we are using cput, so the write only succeeds if there was nothing there. Additionally we would be creating a tombstone, so it does not have side effects from the SQL layer. But it could LDR to fail to converge, since the tombstone updater is not working.

A secondary discovery here is that the tombstone updater is formatting deletes for indexes other than the primary index. Now, we use the index update helper to ensure we only generate updates for the primary key index.

Fixes: #159306
Release note: None

### CODE REVIEW

File: pkg/crosscluster/logical/tombstone_updater.go [hunk 1]
```diff
@@ -164,9 +168,16 @@ func (tu *tombstoneUpdater) getDeleter(ctx context.Context, txn *kv.Txn) (row.De
...
-			return row.Deleter{}, err
+		table := tu.leased.descriptor.Underlying().(catalog.TableDescriptor)
+		schema := getColumnSchema(table)
+		cols := make([]catalog.Column, len(schema))
+		for i, cs := range schema {
+			cols[i] = cs.column
+		}
+
+		tu.leased.ph = row.PartialIndexUpdateHelper{}
+		for _, index := range table.NonPrimaryIndexes() {
```
Comment (jeffswenson) [inline pkg/crosscluster/logical/tombstone_updater.go]: @michae2 I pulled you in for some sql queries expertise. Is this use of the PartialIndexUpdateHelper sound?

File: pkg/crosscluster/logical/tombstone_updater.go [hunk 2]
```diff
@@ -40,6 +40,11 @@ type tombstoneUpdater struct {
 		// deleter is a row.Deleter that uses the leased descriptor. Callers should
 		// use getDeleter to ensure the lease is valid for the current transaction.
 		deleter row.Deleter
+
+		// partialIndexUpdateHelper is used to avoid constructing delete requests
+		// for indexes. Since the cput ensures we are only overwriting tombstones,
+		// we know there are no index entries to delete.
```
Comment (msbutler) [inline pkg/crosscluster/logical/tombstone_updater.go]: could you flesh this comment out a little more? this feels like a bit of a hack, as we are not necessarily dealing with partial indexes. I think what's going on is: the PartialIndexUpdateHelper is normally used to avoid constructing cputs for partial indexe updates when the partial index predicate doesn't match, but we're simply using it to avoid sending cputs to _all_ secondary index keys, right?

File: pkg/crosscluster/logical/tombstone_updater.go [hunk 3]
```diff
@@ -164,9 +168,16 @@ func (tu *tombstoneUpdater) getDeleter(ctx context.Context, txn *kv.Txn) (row.De
...
-		if err != nil {
-			return row.Deleter{}, err
+		table := tu.leased.descriptor.Underlying().(catalog.TableDescriptor)
+		schema := getColumnSchema(table)
+		cols := make([]catalog.Column, len(schema))
+		for i, cs := range schema {
+			cols[i] = cs.column
+		}
+
+		tu.leased.ph = row.PartialIndexUpdateHelper{}
```
Comment (msbutler) [inline pkg/crosscluster/logical/tombstone_updater.go]: should the `ph` also get get zero'd out in `ReleaseLeases()`?

File: pkg/crosscluster/logical/tombstone_updater.go (hunk 2 above)
Comment (msbutler) [reply pkg/crosscluster/logical/tombstone_updater.go]: perhaps we let queries michael comment.

File: pkg/crosscluster/logical/tombstone_updater_test.go [hunk 4]
```diff
@@ -82,3 +88,77 @@ func TestTombstoneUpdaterSetsOriginID(t *testing.T) {
 		{"1", "42"},
 	})
 }
+
+func TestTombstoneUpdaterRandomTables(t *testing.T) {
```
Comment (msbutler) [inline pkg/crosscluster/logical/tombstone_updater_test.go:125]: nice test!

File: pkg/crosscluster/logical/tombstone_updater.go (hunk 2 above)
Comment (jeffswenson) [reply pkg/crosscluster/logical/tombstone_updater.go]: I think the alternative approach would be to skip the index update code in row/deleter.go if `oth.PreviousWasDeleted` is set to true. I suspect that is what I thought was happening when I wrote this code, since it doesn't make sense to waste cpu generating index updates that we know do not exist.

File: pkg/crosscluster/logical/tombstone_updater_test.go (hunk 4 above)
Comment (jeffswenson) [reply pkg/crosscluster/logical/tombstone_updater_test.go:125]: I added in a second assertion. I make sure that a second tombstone update loses lww. That way we can be certain we are using cputs.

**Comment by jeffswenson** [comment]
I noticed this related bug when working on fixes to the tombstone updater: https://github.com/cockroachdb/cockroach/issues/159860.

File: pkg/crosscluster/logical/tombstone_updater.go (hunk 2 above)
Comment (michae2) [reply pkg/crosscluster/logical/tombstone_updater.go]: I notice that the kv writer is [also using](https://github.com/cockroachdb/cockroach/blob/5ddade291266a204ed1521393e7d648ba3b3eb23/pkg/crosscluster/logical/lww_kv_processor.go#L553) `oth.PreviousWasDeleted`. Should the kv writer also be skipping writes to secondary indexes when this is set?

Why is it that the kv writer doesn't run into this problem? Is it because the sql/crud writers only get PK columns from events when prevRow is deleted, but the kv writer gets all columns when prevRow is deleted? I'm not quite following why that is. Are the sql/crud writers choosing to decode fewer columns?

It does seem like a bit of a hack to use PartialIndexUpdateHelper, especially if we want to use it one day to support partial indexes in LDR.

**Review by michae2 — COMMENTED** [review]
Sorry for the delay, it's taking me a while to remember all of the context. I think this all makes sense, just had some questions.

> @michae2 made 2 comments.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/159746#-:-OgsGsy96-FMo-5V4as1:b-enr9ep)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @jeffswenson, @kev-cao, and @msbutler).

File: pkg/crosscluster/logical/tombstone_updater.go (hunk 2 above)
Comment (jeffswenson) [reply pkg/crosscluster/logical/tombstone_updater.go]: > I notice that the kv writer is [also using](https://github.com/cockroachdb/cockroach/blob/5ddade291266a204ed1521393e7d648ba3b3eb23/pkg/crosscluster/logical/lww_kv_processor.go#L553) `oth.PreviousWasDeleted`. Should the kv writer also be skipping writes to secondary indexes when this is set?

The KV writer is generating del commands that it doesn't need to. But it only supports computed stored columns and always decodes the stored column. Which means its able to reliably generate the indexes.

> It does seem like a bit of a hack to use PartialIndexUpdateHelper, especially if we want to use it one day to support partial indexes in LDR.

We already do support partial indexes in the crud writer. But the tombstone updater is only called when we have performed a read on the cluster and observed there is no local row, and we need to try and update the origin timestamp assigned to the tombstone.

But I'm happy to make a change to deleter if you prefer that approach. It would make the kv writer slightly more efficient, though this codepath is only taken by replays and racing deletes, so its not particularly performance sensitive.

**Review by jeffswenson — COMMENTED** [review]
> @jeffswenson made 1 comment.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/159746)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @kev-cao, @michae2, and @msbutler).

File: pkg/crosscluster/logical/tombstone_updater.go (hunk 2 above)
Comment (jeffswenson) [reply pkg/crosscluster/logical/tombstone_updater.go]: I updated this change to have the delewter check the oth.PreviousWasDeleted and skip secondary index updates if it is set.

Comment (michae2) [reply pkg/crosscluster/logical/tombstone_updater.go]: Thanks! This all makes sense.

> Is it because the sql/crud writers only get PK columns from events when prevRow is deleted, but the kv writer gets all columns when prevRow is deleted? I'm not quite following why that is. Are the sql/crud writers choosing to decode fewer columns?

Ah, I read through getColumnSchema and now pieces are clicking into place.

**Review by michae2 — APPROVED** [review]
:lgtm: Very nice!

> @michae2 reviewed 4 files and all commit messages, and made 3 comments.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/159746#-:-Ogsm5ugEqChlWTfkoGt:b-kerl87)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @jeffswenson, @kev-cao, @msbutler, and @mw5h).

___
*[`pkg/sql/row/deleter.go` line 225 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/159746#-OgspEoLAwtHgu9FoES2:-OgspEoLAwtHgu9FoES3:b-o4oytk) ([raw file](https://github.com/cockroachdb/cockroach/blob/e2006d503ccf17aa8c80ff44038ddbc1be5749ab/pkg/sql/row/deleter.go#L225)):*
> ```Go
> 			// If we are updating a tombstone, then there are no secondary index entries
> 			// that need to be deleted.
> 			continue
> ```

If you wanted to, you could lift this out of the loop as an early return.

**Review by jeffswenson — COMMENTED** [review]
> @jeffswenson made 1 comment.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/159746)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @kev-cao, @michae2, @msbutler, and @mw5h).

___
*[`pkg/sql/row/deleter.go` line 225 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/159746#-OgspEoLAwtHgu9FoES2:-Oh6CnIECAYudYSQtO16:bigl54i) ([raw file](https://github.com/cockroachdb/cockroach/blob/e2006d503ccf17aa8c80ff44038ddbc1be5749ab/pkg/sql/row/deleter.go#L225)):*
<details><summary><i>Previously, michae2 (Michael Erickson) wrote…</i></summary><blockquote>

If you wanted to, you could lift this out of the loop as an early return.
</blockquote></details>

I switched this to an early return right before the loop.
