### PR TITLE
roachtest: set 23.1.8 as MinSupportedVersion for sql-stats/mixed-version 

### LINKED ISSUE #123278: roachtest: sql-stats/mixed-version failed
roachtest.sql-stats/mixed-version [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyAwsBazel/15041954?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyAwsBazel/15041954?buildTab=artifacts#/sql-stats/mixed-version) on master @ [086f930e2b94913737db9ef9877d10976355874c](https://github.com/cockroachdb/cockroach/commits/086f930e2b94913737db9ef9877d10976355874c):

```
(mixedversion.go:592).Run: mixed-version test failure while running step 10 (run "request stmts stats"): failed to request stats for empty interval: Get "https://3.147.89.154:26258/_status/combinedstmts?fetch_mode.stats_type=0&start=0&end=100&limit=10": EOF
test artifacts and logs in: /artifacts/sql-stats/mixed-version/cpu_arch=arm64/run_1
```

Parameters:
 - <code>ROACHTEST_arch=arm64</code>
 - <code>ROACHTEST_cloud=aws</code>
 - <code>ROACHTEST_coverageBuild=false</code>
 - <code>ROACHTEST_cpu=4</code>
 - <code>ROACHTEST_encrypted=false</code>
 - <code>ROACHTEST_fs=ext4</code>
 - <code>ROACHTEST_localSSD=true</code>
 - <code>ROACHTEST_metamorphicBuild=false</code>
 - <code>ROACHTEST_ssd=0</code>
<details><summary>Help</summary>
<p>

See: [roachtest README](https://github.com/cockroachdb/cockroach/blob/master/pkg/cmd/roachtest/README.md)

See: [How To Investigate \(internal\)](https://cockroachlabs.atlassian.net/l/c/SSSBr8c7)

_Grafana is not yet available for aws clusters_</p>
</details>
/cc @cockroachdb/obs-prs
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*sql-stats/mixed-version.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/bazci/githubpost/issues)
</sub>

Jira issue: CRDB-38269

### PR DESCRIPTION
**Pull request by xinhaoz**
There is a bug in the sql stats api prior to 23.1.8, where
passing a requested start time of 0 or nil results in a
nil pointer dereference.

Setting this min supported version  also resolves some mixed
version authentication limitations.

Epic: none
Fixes: https://github.com/cockroachdb/cockroach/issues/123278

Release note: None

### CODE REVIEW

File: pkg/cmd/roachtest/tests/mixed_version_sql_stats.go [hunk 1]
```diff
@@ -203,7 +203,9 @@ func (s *sqlStatsRequestHelper) requestSQLStats(
 	for _, addr := range adminUIAddrs {
 		url := getCombinedStatementStatsURL(addr, statsType, requestedRange)
 		statsResponse := &serverpb.StatementsResponse{}
-		if err := s.client.GetJSON(ctx, url, statsResponse, httputil.IgnoreUnknownFields()); err != nil {
+		if err := retry.ForDuration(10*time.Second, func() error {
```
Comment (renatolabs) [inline pkg/cmd/roachtest/tests/mixed_version_sql_stats.go:206]: Why do we need the retry logic? What kinds of spurious failures do we expect here?

Comment (xinhaoz) [reply pkg/cmd/roachtest/tests/mixed_version_sql_stats.go:206]: Mostly motivated from seeing it applied here: https://github.com/cockroachdb/cockroach/blob/7c3d18ae4a3024ddf48a87e96098672334e1bebc/pkg/cmd/roachtest/tests/status_server.go#L50, where it seems like the status server was not yet ready to serve requests.

Comment (renatolabs) [reply pkg/cmd/roachtest/tests/mixed_version_sql_stats.go:206]: Hrm, but that change was done in 2018 (#29492), does it still apply today? Have we seen this test flake because the status server was not ready to handle requests?

Comment (xinhaoz) [reply pkg/cmd/roachtest/tests/mixed_version_sql_stats.go:206]: Okay that seems pretty outdated. So far this test has failed twice in the nightly run at this step, but with different error messages:

1. `Get "https://3.147.89.154:26258/_status/combinedstmts?fetch_mode.stats_type=0&start=0&end=100&limit=10": EOF` [[ref](https://github.com/cockroachdb/cockroach/issues/123278#issue-2270771970)]

2. `roachtestutil.addCookie: unable to extract sessionID: roachtestutil.GetSessionID: failed to authenticate: COMMAND_PROBLEM: exit status 1` [[ref](https://github.com/cockroachdb/cockroach/issues/123278#issuecomment-2088532991)]

Do these point to an issue with the mixed version test or an issue within roachtest? Is there guidance on restricting the test to certain cloud providers? Running the test locally passed so these failures seemed sporadic to me.

Comment (DarrylWong) [reply pkg/cmd/roachtest/tests/mixed_version_sql_stats.go:206]: That second issue seems the same as https://github.com/cockroachdb/cockroach/issues/119064. You weren't running into it before because you had `mixedversion.MaxUpgrades(2)` but that was removed.

I think we need to either add that back in or run it in insecure mode, neither of which are great options. The former wouldn't solve the issue if we backport this test, and the latter would mean we have 0 mixed version roachtests that run on secure mode. 

FWIW I only noticed https://github.com/cockroachdb/cockroach/pull/122468 because this test was running on secure mode so I'm not convinced disabling it is the easy answer. But maybe with 23.1 support dropping soon it doesn't matter 🤷

Comment (DarrylWong) [reply pkg/cmd/roachtest/tests/mixed_version_sql_stats.go:206]: For failure 2, I see: `ERROR: column "user_id" does not exist` when trying to auth on `23.1`. Since I removed the version gate for that, I think the fix is for the mvt framework to also drop support for 23.1 on master?

Comment (renatolabs) [reply pkg/cmd/roachtest/tests/mixed_version_sql_stats.go:206]: > I think the fix is for the mvt framework to also drop support for 23.1 on master?

Ah my bad, I didn't realize this is why the PR had `MaxUpgrades(2)` originally. I forgot the details on when the auth stuff works. I suggest passing the `MinimumSupportedVersion("v23.1.0")` option to the test, which will make sure user functions will only run once the cluster is at least that version.

> Do these point to an issue with the mixed version test or an issue within roachtest?

I think neither in this case? Failure 2 is a limitation in cockroach with authenticating in mixed-version state, as I understand it. It can be worked around by specifying the minimum version as I mentioned above.

Issue 1 actually seems to be a bug in the stats code -- n4 crashed with this error (only a few frames here for clarity):

```
E240430 07:54:10.992587 21115 1@util/log/logcrash/crash_reporting.go:188 ⋮ [-] 506  a panic has occurred!
E240430 07:54:10.992587 21115 1@util/log/logcrash/crash_reporting.go:188 ⋮ [-] 506 +runtime error: invalid memory address or nil pointer dereference
E240430 07:54:10.992587 21115 1@util/log/logcrash/crash_reporting.go:188 ⋮ [-] 506 +(1) attached stack trace
E240430 07:54:10.992587 21115 1@util/log/logcrash/crash_reporting.go:188 ⋮ [-] 506 +  -- stack trace:
E240430 07:54:10.992587 21115 1@util/log/logcrash/crash_reporting.go:188 ⋮ [-] 506 +  | runtime.gopanic
E240430 07:54:10.992587 21115 1@util/log/logcrash/crash_reporting.go:188 ⋮ [-] 506 +  | 	GOROOT/src/runtime/panic.go:884
E240430 07:54:10.992587 21115 1@util/log/logcrash/crash_reporting.go:188 ⋮ [-] 506 +  | runtime.panicmem
E240430 07:54:10.992587 21115 1@util/log/logcrash/crash_reporting.go:188 ⋮ [-] 506 +  | 	GOROOT/src/runtime/panic.go:260
E240430 07:54:10.992587 21115 1@util/log/logcrash/crash_reporting.go:188 ⋮ [-] 506 +  | runtime.sigpanic
E240430 07:54:10.992587 21115 1@util/log/logcrash/crash_reporting.go:188 ⋮ [-] 506 +  | 	GOROOT/src/runtime/signal_unix.go:835
E240430 07:54:10.992587 21115 1@util/log/logcrash/crash_reporting.go:188 ⋮ [-] 506 +  | github.com/cockroachdb/cockroach/pkg/server.activityTablesHaveFullData
E240430 07:54:10.992587 21115 1@util/log/logcrash/crash_reporting.go:188 ⋮ [-] 506 +  | 	github.com/cockroachdb/cockroach/pkg/server/combined_statement_stats.go:232
E240430 07:54:10.992587 21115 1@util/log/logcrash/crash_reporting.go:188 ⋮ [-] 506 +  | github.com/cockroachdb/cockroach/pkg/server.getCombinedStatementStats
E240430 07:54:10.992587 21115 1@util/log/logcrash/crash_reporting.go:188 ⋮ [-] 506 +  | 	github.com/cockroachdb/cockroach/pkg/server/combined_statement_stats.go:100
E240430 07:54:10.992587 21115 1@util/log/logcrash/crash_reporting.go:188 ⋮ [-] 506 +  | github.com/cockroachdb/cockroach/pkg/server.(*statusServer).CombinedStatementStats
E240430 07:54:10.992587 21115 1@util/log/logcrash/crash_reporting.go:188 ⋮ [-] 506 +  | 	github.com/cockroachdb/cockroach/pkg/server/combined_statement_stats.go:65
```

Comment (renatolabs) [reply pkg/cmd/roachtest/tests/mixed_version_sql_stats.go:206]: Granted, the error message could be more explicit (and it could be if the monitor had noticed the process death soon enough, but the client saw the EOF first, and that was the error reported). A client seeing an EOF from a connection often means that the server crashed, FWIW.

> Running the test locally passed so these failures seemed sporadic to me.

As a bit of context, there's a lot of randomization happening in these tests so passing locally doesn't mean that test failures are flakes or spurious necessarily.

**Review by renatolabs — APPROVED** [review]

**Comment by xinhaoz** [comment]
TFTR!
bors r+
