### PR TITLE
tpcc: use explicit decimal when initializing items

### LINKED ISSUE #143913: roachtest: ldr/tpcc failed
roachtest.ldr/tpcc [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/19314742?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/19314742?buildTab=artifacts#/ldr/tpcc) on master @ [04aaac4c89e3f80a32c809b74704f74d057d8d10](https://github.com/cockroachdb/cockroach/commits/04aaac4c89e3f80a32c809b74704f74d057d8d10):

```
(assertions.go:369).Fail: 
	Error Trace:	pkg/cmd/roachtest/tests/logical_data_replication.go:1010
	            				pkg/cmd/roachtest/tests/logical_data_replication.go:388
	Error:      	Not equal: 
	            	expected: [][]string{[]string{"item_pkey", "8405375278825208764"}}
	            	actual  : [][]string{[]string{"item_pkey", "-4842524901426009324"}}
	            	
	            	Diff:
	            	--- Expected
	            	+++ Actual
	            	@@ -3,3 +3,3 @@
	            	   (string) (len=9) "item_pkey",
	            	-  (string) (len=19) "8405375278825208764"
	            	+  (string) (len=20) "-4842524901426009324"
	            	  }
	Test:       	ldr/tpcc
	Messages:   	fingerprint mismatch for table item
(require.go:162).Equal: FailNow called
test artifacts and logs in: /artifacts/ldr/tpcc/run_1
```

Parameters:
 - <code>arch=amd64</code>
 - <code>cloud=gce</code>
 - <code>coverageBuild=false</code>
 - <code>cpu=8</code>
 - <code>encrypted=false</code>
 - <code>fs=ext4</code>
 - <code>localSSD=false</code>
 - <code>metamorphicBufferedSender=false</code>
 - <code>metamorphicLeases=default</code>
 - <code>runtimeAssertionsBuild=false</code>
 - <code>ssd=0</code>
<details><summary>Help</summary>
<p>

See: [roachtest README](https://github.com/cockroachdb/cockroach/blob/master/pkg/cmd/roachtest/README.md)

See: [How To Investigate \(internal\)](https://cockroachlabs.atlassian.net/l/c/SSSBr8c7)

See: [Grafana](https://go.crdb.dev/roachtest-grafana/teamcity-19314742/ldr-tpcc/1743769897014/1743771284312)

</p>
</details>
/cc @cockroachdb/disaster-recovery
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*ldr/tpcc.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/bazci/githubpost/issues)

</sub>

Jira issue: CRDB-49157

### LINKED ISSUE #144289: roachtest: ldr/tpcc failed
**Note:** This build has runtime assertions enabled. If the same failure was hit in a run without assertions enabled, there should be a similar failure without this message. If there isn&#39;t one, then this failure is likely due to an assertion violation or (assertion) timeout.

roachtest.ldr/tpcc [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/19395764?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/19395764?buildTab=artifacts#/ldr/tpcc) on release-25.2 @ [0e37e8c11132a7175d402a2a03ecbcf2091d3781](https://github.com/cockroachdb/cockroach/commits/0e37e8c11132a7175d402a2a03ecbcf2091d3781):

```
(assertions.go:369).Fail: 
	Error Trace:	pkg/cmd/roachtest/tests/logical_data_replication.go:1010
	            				pkg/cmd/roachtest/tests/logical_data_replication.go:388
	Error:      	Not equal: 
	            	expected: [][]string{[]string{"item_pkey", "1158338437640662310"}}
	            	actual  : [][]string{[]string{"item_pkey", "4689711947015190026"}}
	            	
	            	Diff:
	            	--- Expected
	            	+++ Actual
	            	@@ -3,3 +3,3 @@
	            	   (string) (len=9) "item_pkey",
	            	-  (string) (len=19) "1158338437640662310"
	            	+  (string) (len=19) "4689711947015190026"
	            	  }
	Test:       	ldr/tpcc
	Messages:   	fingerprint mismatch for table item
(require.go:162).Equal: FailNow called
test artifacts and logs in: /artifacts/ldr/tpcc/run_1
```

Parameters:
 - <code>arch=amd64</code>
 - <code>cloud=gce</code>
 - <code>coverageBuild=false</code>
 - <code>cpu=8</code>
 - <code>encrypted=false</code>
 - <code>metamorphicBufferedSender=false</code>
 - <code>metamorphicLeases=default</code>
 - <code>runtimeAssertionsBuild=true</code>
 - <code>ssd=0</code>
<details><summary>Help</summary>
<p>

See: [roachtest README](https://github.com/cockroachdb/cockroach/blob/master/pkg/cmd/roachtest/README.md)

See: [How To Investigate \(internal\)](https://cockroachlabs.atlassian.net/l/c/SSSBr8c7)

See: [Grafana](https://go.crdb.dev/roachtest-grafana/teamcity-19395764/ldr-tpcc/1744368793114/1744370237202)

</p>
</details>
<details><summary>Same failure on other branches</summary>
<p>

- #143913 roachtest: ldr/tpcc failed [A-disaster-recovery C-test-failure O-roachtest O-robot P-0 T-disaster-recovery branch-master]
</p>
</details>
/cc @cockroachdb/disaster-recovery
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*ldr/tpcc.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/bazci/githubpost/issues)

</sub>

Jira issue: CRDB-49316

### PR DESCRIPTION
**Pull request by jeffswenson**
Previously, TPCC relied on a float -> decimal -> decimal(precision, scale) cast to import data. In rare cases this could lead to incorrectly normalized values like 1E2 instead of 100. Now, the TPCC workload generator creates decimals with the correct scale.

Informs: #144474
Informs: #143870
Fixes: #143913
Fixes: #144289
Release note: none

### CODE REVIEW

**Review by michae2 — APPROVED** [review]
:lgtm: Nice fixup!

> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/144818#-:-OOP1lUw1FCYdrLAa75x:bsf86w5)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @golgeek, @herkolategan, and @msbutler)

File: pkg/workload/tpcc/generate.go [hunk 1]
```diff
@@ -34,20 +35,26 @@ const (
...
-	ytd            = 30000.00
 	nextOrderID    = 3001
-	creditLimit    = 50000.00
-	balance        = -10.00
-	ytdPayment     = 10.00
 	paymentCount   = 1
 	deliveryCount  = 0
 )
 
+func makeDecimal(value, scale int32) apd.Decimal {
```
Comment (msbutler) [inline pkg/workload/tpcc/generate.go:43]: nit: it's a bit confusing that this helper passes scale as a negative value while `types.Decimal` passes it as a positive value. Can't win them all i guess. Perhaps add a comment to clarify this?

File: pkg/workload/tpcc/generate.go [hunk 2]
```diff
@@ -78,11 +85,14 @@ func (w *tpcc) tpccItemInitialRowBatch(rowIdx int, cb coldata.Batch, a *bufalloc
 
 	iID := rowIdx + 1
 
+	var price apd.Decimal
+	price.SetFinite(randInt(l.rng.Rand, 100, 10000), -2)
```
Comment (msbutler) [inline pkg/workload/tpcc/generate.go:89]: use the helper?

File: pkg/workload/tpcc/generate.go [hunk 3]
```diff
@@ -359,10 +369,10 @@ func (w *tpcc) tpccCustomerInitialRowBatch(
 	cb.ColVec(11).Bytes().Set(0, randNStringInitialDataOnly(&l.rng, &no, a, 16, 16)) // phone number
 	cb.ColVec(12).Timestamp()[0] = w.nowTime
 	cb.ColVec(13).Bytes().Set(0, credit)
-	cb.ColVec(14).Float64()[0] = creditLimit
-	cb.ColVec(15).Float64()[0] = float64(randInt(l.rng.Rand, 0, 5000)) / float64(10000.0) // discount
-	cb.ColVec(16).Float64()[0] = balance
-	cb.ColVec(17).Float64()[0] = ytdPayment
+	cb.ColVec(14).Decimal()[0] = creditLimit
+	cb.ColVec(15).Decimal()[0] = makeDecimal(int32(randInt(l.rng.Rand, 0, 5000)), -4)
```
Comment (msbutler) [inline pkg/workload/tpcc/generate.go:373]: nit: add back // discount

i'm ruthless

**Review by msbutler — APPROVED** [review]
Thanks for doing this!! does the test now pass with this new workload? :D

**Review by msbutler — APPROVED** [review]
Thanks for doing this!! does the test now pass with this new workload? :D

**Comment by msbutler** [comment]
oh looks like you got one unit test still complaining

File: pkg/workload/tpcc/generate.go (hunk 1 above)
Comment (jeffswenson) [reply pkg/workload/tpcc/generate.go:43]:
```
func makeDecimal(value, exponent int32) apd.Decimal {
  var result apd.Decimal
	result.SetFinite(int64(value*int32(math.Pow10(exponent))), -exponent)
	return result
}
```
This only allows defining integer decimals.

I guess I could do something like
```go
func makeDecimal(value float64, scale int32) apd.Decimal {
}
```

File: pkg/workload/tpcc/generate.go (hunk 2 above)
Comment (jeffswenson) [reply pkg/workload/tpcc/generate.go]: Done

File: pkg/workload/tpcc/generate.go (hunk 3 above)
Comment (jeffswenson) [reply pkg/workload/tpcc/generate.go]: Fixed

File: pkg/workload/tpcc/random.go [hunk 4]
```diff
@@ -173,8 +142,20 @@ func randInt(rng *rand.Rand, min, max int) int64 {
...
-	return int64(rng.Intn(max-min+1) + min)
+func makeDecimal(value float64, scale int32) apd.Decimal {
+	value = math.Round(value * math.Pow(10, float64(scale)))
+	var result apd.Decimal
+	result.SetFinite(int64(value), -scale)
+	return result
+}
+
+func randDecimal(rng *rand.Rand, min, max float64, scale int32) apd.Decimal {
+	minInt := int64(min * math.Pow(10, float64(scale)))
```
Comment (srosenberg) [inline pkg/workload/tpcc/random.go:153]: Why not the optimized `Pow10`?

Comment (jeffswenson) [reply pkg/workload/tpcc/random.go]: Good idea! Done.

**Comment by jeffswenson** [comment]
Thanks for the reviews!

bors r+
