### PR TITLE
workload: mark repair-order-ids tpcc flag as runtime only

### LINKED ISSUE #135677: roachtest: backup-restore/mixed-version failed
roachtest.backup-restore/mixed-version [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/17831321?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/17831321?buildTab=artifacts#/backup-restore/mixed-version) on master @ [9927a9a1f0827daa734d5eb718017cf260dfe676](https://github.com/cockroachdb/cockroach/commits/9927a9a1f0827daa734d5eb718017cf260dfe676):

```
(mixedversion.go:759).Run: mixed-version test failure while running step 13 (run "initialize tpcc workload"): full command output in run_070212.502726436_n5_cockroach-workload-i.log: COMMAND_PROBLEM: exit status 1
test artifacts and logs in: /artifacts/backup-restore/mixed-version/run_1
```

Parameters:
 - <code>arch=amd64</code>
 - <code>cloud=gce</code>
 - <code>coverageBuild=false</code>
 - <code>cpu=4</code>
 - <code>encrypted=true</code>
 - <code>fs=ext4</code>
 - <code>localSSD=true</code>
 - <code>mvtDeploymentMode=shared-process</code>
 - <code>mvtVersions=v23.1.28 → v23.2.15 → v24.1.6 → v24.2.4 → master</code>
 - <code>runtimeAssertionsBuild=false</code>
 - <code>ssd=0</code>
<details><summary>Help</summary>
<p>

See: [roachtest README](https://github.com/cockroachdb/cockroach/blob/master/pkg/cmd/roachtest/README.md)

See: [How To Investigate \(internal\)](https://cockroachlabs.atlassian.net/l/c/SSSBr8c7)

See: [Grafana](https://go.crdb.dev/roachtest-grafana/teamcity-17831321/backup-restore-mixed-version/1731999508358/1731999886341)

</p>
</details>
<details><summary>Same failure on other branches</summary>
<p>

- #125677 roachtest: backup-restore/mixed-version failed [C-test-failure O-roachtest O-robot P-3 T-disaster-recovery branch-release-23.1]
</p>
</details>
/cc @cockroachdb/disaster-recovery
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*backup-restore/mixed-version.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/bazci/githubpost/issues)

</sub>

Jira issue: CRDB-44672

### LINKED ISSUE #135785: roachtest: c2c/mixed-version failed
roachtest.c2c/mixed-version [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyAzureBazel/17851108?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyAzureBazel/17851108?buildTab=artifacts#/c2c/mixed-version) on master @ [8eeb7f2ae3b2cede564b46ca47e2353fd147c061](https://github.com/cockroachdb/cockroach/commits/8eeb7f2ae3b2cede564b46ca47e2353fd147c061):

```
(mixedversion.go:759).Run: source: mixed-version test failure while running step 8 (run "initialize tpcc workload"): full command output in run_064627.076735144_n9_cockroach-workload-i.log: COMMAND_PROBLEM: exit status 1
(mixedversion.go:759).Run: dest: cluster.StopE: one or more parallel execution failure(s): context canceled
test artifacts and logs in: /artifacts/c2c/mixed-version/cpu_arch=arm64/run_1
```

Parameters:
 - <code>arch=arm64</code>
 - <code>cloud=azure</code>
 - <code>coverageBuild=false</code>
 - <code>cpu=4</code>
 - <code>encrypted=false</code>
 - <code>fs=ext4</code>
 - <code>localSSD=true</code>
 - <code>mvtDeploymentMode=system-only</code>
 - <code>mvtVersions=v24.2.4 → master</code>
 - <code>runtimeAssertionsBuild=false</code>
 - <code>ssd=0</code>
<details><summary>Help</summary>
<p>

See: [roachtest README](https://github.com/cockroachdb/cockroach/blob/master/pkg/cmd/roachtest/README.md)

See: [How To Investigate \(internal\)](https://cockroachlabs.atlassian.net/l/c/SSSBr8c7)

_Grafana is not yet available for azure clusters_</p>
</details>
/cc @cockroachdb/disaster-recovery
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*c2c/mixed-version.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/bazci/githubpost/issues)

</sub>

Jira issue: CRDB-44705

### PR DESCRIPTION
**Pull request by msbutler**
This means the default value will be hidden when a cmd is generated, which
prevents backward incompatibility.

Fixes https://github.com/cockroachdb/cockroach/issues/135677
Fixes https://github.com/cockroachdb/cockroach/issues/135785

Release note: none

### CODE REVIEW

File: pkg/workload/tpcc/tpcc.go [hunk 1]
```diff
@@ -273,6 +273,7 @@ var tpccMeta = workload.Meta{
 			`query-trace-file`:         {RuntimeOnly: true},
 			`fake-time`:                {RuntimeOnly: true},
 			`txn-preamble-file`:        {RuntimeOnly: true},
+			`repair-order-ids`:         {RuntimeOnly: true},
```
Comment (kev-cao) [inline pkg/workload/tpcc/tpcc.go:276]: There's an `order-id-repairs` above this, are these related/is one a typo?

**Review by kev-cao — APPROVED** [review]
LGTM! Just one question

File: pkg/workload/tpcc/tpcc.go (hunk 1 above)
Comment (msbutler) [reply pkg/workload/tpcc/tpcc.go]: oh, you're totally right. nice catch. fixed.

**Comment by msbutler** [comment]
TFTR!

bors r+
