### PR TITLE
ui: add "Errors" chart to SQL dashboard

### LINKED ISSUE #14148: ui: show failed query count somewhere in admin ui
I just debugged why one of the production clusters wasn't getting any queries. It turns out it got wiped without restarting block_writer, which only creates the necessary databases and tables at startup, so it was continuously failing (with `pq: database "datablocks" does not exist` in the logs).  As far as I could see on the admin ui, nothing strange was happening to the cluster. Could be useful for these sorts of situations to have the count of failed SQL queries in one of the graphs.

### LINKED ISSUE #29346: ui: timeseries: Add failed query count to Queries chart
We have added a new time series for failed query counts, however it is currently not exposed and only accessible through custom charts in debug pages. We should expose this time series on the Overview dashboard in the Queries chart.

cc @vilterp @couchand @danhhz

### PR DESCRIPTION
**Pull request by vilterp**
This metric shows the number of statements per second resulting in a
planning or execution error:

image

Fixes #14148
Fixes #29346

### CODE REVIEW

**Review by mrtracy — APPROVED** [review]

**Comment by vilterp** [comment]
Pasting @andreimatei's response to my question "what kinds of execution errors are there" from Slack:

> A million things - from logic errors like duplicate key, to a million "internal errors" - retriable transaction errors, ambiguous commit, all sorts of unavailability, query cancelation... [also Raphael said division by 0]

I think if they're retriable they won't show up here.

**Comment by danhhz** [comment]
itshappening.gif

**Comment by vilterp** [comment]
Changed this to be a separate chart on the SQL dashboard. Hopefully that's an acceptable compromise between not burying it too much and not showing an incommensurable metric on the existing Queries chart.

File: pkg/ui/src/views/cluster/containers/nodeGraphs/dashboards/sql.tsx [hunk 1]
```diff
@@ -49,6 +49,16 @@ export default function (props: GraphDashboardProps) {
       </Axis>
     </LineGraph>,
 
+    <LineGraph
+      title="SQL Query Errors"
+      sources={nodeSources}
+      tooltip={"The number of statements which returned a planning or runtime error."}
+    >
+      <Axis label="queries">
```
Comment (couchand) [inline pkg/ui/src/views/cluster/containers/nodeGraphs/dashboards/sql.tsx]: s/queries/errors/

File: pkg/ui/src/views/cluster/containers/nodeGraphs/dashboards/sql.tsx [hunk 2]
```diff
@@ -49,6 +49,16 @@ export default function (props: GraphDashboardProps) {
...
+        <Metric name="cr.node.sql.failure.count" title="Failures" nonNegativeRate />
```
Comment (couchand) [inline pkg/ui/src/views/cluster/containers/nodeGraphs/dashboards/sql.tsx]: I think it may be confusing to use different terms for the chart title and the series title.  Maybe just s/Failures/Errors/?

**Review by couchand — APPROVED** [review]
LGTM pending terminology

File: pkg/ui/src/views/cluster/containers/nodeGraphs/dashboards/sql.tsx (hunk 1 above)
Comment (vilterp) [reply pkg/ui/src/views/cluster/containers/nodeGraphs/dashboards/sql.tsx]: Done.

File: pkg/ui/src/views/cluster/containers/nodeGraphs/dashboards/sql.tsx (hunk 2 above)
Comment (vilterp) [reply pkg/ui/src/views/cluster/containers/nodeGraphs/dashboards/sql.tsx]: Done.

**Comment by vilterp** [comment]
Failure was unrelated (`gossip/restart-node-one` roachtest); trying again.

bors r+
