### PR TITLE
descs: fix txn commit waiting on wrong lease version

### LINKED ISSUE #87672: sql: hang possible due to bad version bookkeeping
**Describe the problem**

Consider the following test:
```sql
CREATE DATABASE db;
USE db;
CREATE SCHEMA sc;
BEGIN;
    CREATE SCHEMA sc2;
    SELECT * FROM crdb_internal.tables;
    DROP SCHEMA sc CASCADE;
COMMIT;
```

This now fails, and it was broken in https://github.com/cockroachdb/cockroach/pull/87067

**Additional context**
This was discovered while investigating https://github.com/cockroachdb/cockroach/issues/78478. 

Jira issue: CRDB-19466

### PR DESCRIPTION
**Pull request by postamar**
Recent work on the descs.Collection (PR #87067) introduced a regression
in which it would return bad lease.IDVersion versions for the uncommitted
descriptors.

Fixes #87672.

Release justification: important bug fix
Release note: None

### CODE REVIEW

File: pkg/sql/catalog/descs/collection.go [hunk 1]
```diff
@@ -308,16 +308,42 @@ func (tc *Collection) WriteDesc(
...
+) {
+	err = tc.uncommitted.iterateOriginalByID(func(original catalog.Descriptor) error {
+		uncommitted := tc.uncommitted.getUncommittedByID(original.GetID())
+		// Sanity check.
+		if original.GetVersion() == 0 {
+			return errors.AssertionFailedf(
+				"expected original version of uncommitted %s %q (%d) to be non-zero",
+				uncommitted.DescriptorType(), uncommitted.GetName(), uncommitted.GetID())
+		}
+		// Ignore uncommitted descriptors which for whatever reason have not
```
Comment (ajwerner) [inline pkg/sql/catalog/descs/collection.go:330]: Do you understand the reason?

**Review by ajwerner — APPROVED** [review]
LGTM though I don't have a totally clear understanding as to how it happens.

File: pkg/sql/catalog/descs/uncommitted_descriptors.go [hunk 2]
```diff
@@ -111,17 +110,19 @@ func (ud *uncommittedDescriptors) getUncommittedByName(
...
-	fn func(originalVersion lease.IDVersion) error,
+// iterateOriginalByID applies fn to each original descriptor for which an
+// uncommitted non-new descriptor exists (new descriptors don't have an original
+// descriptor).
+func (ud *uncommittedDescriptors) iterateOriginalByID(
+	fn func(original catalog.Descriptor) error,
 ) error {
 	return ud.uncommitted.IterateByID(func(entry catalog.NameEntry) error {
-		if o := ud.original.Get(entry.GetID()); o != nil {
-			return fn(lease.NewIDVersionPrev(o.GetName(), o.GetID(), o.(catalog.Descriptor).GetVersion()))
```
Comment (postamar) [inline pkg/sql/catalog/descs/uncommitted_descriptors.go:122]: The bug proper was that `fn` was being called a bit too liberally here. The regression was introduced in this PR, I highlighted the line with the relevant part of the old logic: https://github.com/cockroachdb/cockroach/pull/87067/files#diff-74473a29d93e28d8f048009aed817c687c38ab748f111c95fba1ec148f7c0768L664

I fixed this and pushed a more verbose version of this code down to the call site in the hopes of clarifying what it's supposed to do.

File: pkg/sql/catalog/descs/collection.go (hunk 1 above)
Comment (postamar) [reply pkg/sql/catalog/descs/collection.go:330]: For a reason unknown to me we allow uncommitted descriptors to be added with the same version as the cluster version, in addition to clusterVersion+1. These were previously excluded by an early return on `mut.IsUncommittedDescriptor()`.

Comment (postamar) [reply pkg/sql/catalog/descs/collection.go:330]: Perhaps we should file an issue to tighten this. I can't see any instances where `AddUncommittedDescriptor` isn't preceded by a `MaybeIncrementVersion` call, unless it's obviously a new descriptor.

Comment (ajwerner) [reply pkg/sql/catalog/descs/collection.go:330]: In the old world, before your rewrite, we'd add to `uncommittedDescriptors` or whatever it was then called (`storedDescriptors`) on the read path, and the caller which resolved that descriptor might decide to throw that away. 

I'd still like to understand how we were modifying this set which, as you say, shouldn't have anything added to it unless it is being written. One note is that the thing which triggers the bug is the underlying call to `GetAllDescriptors`.

Comment (postamar) [reply pkg/sql/catalog/descs/collection.go:330]: I looked into this and the bug is deeper, even though the changes brought by this PR are good. 

The problem is that we upsert into the storage cache when really we should be inserting. Consider this test case which you supplied. What happens in that transaction is that `CREATE SCHEMA sc2` adds an uncommitted db descriptor to the collection with the new schema entry and bumps its version counter. It then `Run`s that batch. The subsequent `crdb_internal.tables` query calls a `GetAllDescriptors` which overwrites the storage cache with the uncommitted descriptor!

This is why the `original` descriptors in the uncommitted layer can't be relied on.

Comment (ajwerner) [reply pkg/sql/catalog/descs/collection.go:330]: >This is why the original descriptors in the uncommitted layer can't be relied on. 

Yeah... this seems like the right answer. I think we should avoid touching `original` in `AddUncommittedDescriptor` when we already have an entry for the descriptor as opposed to pulling from the `stored` cache.

Comment (postamar) [reply pkg/sql/catalog/descs/collection.go:330]: Indeed. I'll revert to draft mode and push a fix in that direction and we'll see what happens.

**Comment by postamar** [comment]
Well wouldn't you know it, we're updating view back-references in tables based on leased descriptors.

**Review by ajwerner — APPROVED** [review]
Now this feels like the right fix!

LGTM

**Comment by postamar** [comment]
Yes I feel much better too! Glad to get rid of this weirdness with the versions.

**Comment by postamar** [comment]
Thanks for the review.

bors r+
