### PR TITLE
sql: fix `destroy_tenant`

### LINKED ISSUE #97873: sql: crdb_internal.destroy_tenant no longer destroys active tenant
**Describe the problem**

In https://github.com/cockroachdb/cockroach/pull/95691, it is noted that we need to invoke `ALTER TENANT STOP SERVICE` before dropping a tenant with the exception of `crdb_internal.destroy_tenant` for backwards compatibility with CC. That's not the case based on experiments on the following revision:

```
Build Tag:        v23.1.0-alpha.3-377-g13c58f6215
Build Time:       2023/02/27 07:04:17
Distribution:     CCL
Platform:         linux amd64 (x86_64-pc-linux-gnu)
Go Version:       go1.19.4
C Compiler:       gcc 6.5.0
Build Commit ID:  13c58f621519794e775b7cfc4d8b557bc99eeca0
Build Type:       release
```

**To Reproduce**

```
demo@127.0.0.1:26259/defaultdb> select * from crdb_internal.create_tenant(1000);
  crdb_internal.create_tenant
-------------------------------
                         1000
(1 row)

Time: 77ms total (execution 76ms / network 1ms)

demo@127.0.0.1:26259/defaultdb> select * from crdb_internal.destroy_tenant(1000);
ERROR: crdb_internal.destroy_tenant(): destroying tenant: cannot use tenant service mode external with data state drop
demo@127.0.0.1:26259/defaultdb> alter tenant 'tenant-1000' stop service;
ALTER TENANT SERVICE

Time: 14ms total (execution 13ms / network 1ms)

demo@127.0.0.1:26259/defaultdb> select * from crdb_internal.destroy_tenant(1000);
  crdb_internal.destroy_tenant
--------------------------------
                          1000
(1 row)

Time: 21ms total (execution 20ms / network 1ms)
```

Note that I'm using docker with `cockroach demo` here (+ switching into the system tenant), but it shouldn't affect the environment:

```
docker run -it <internal CC docker registry>/cockroach:v23.1.0-alpha.3-377-g13c58f6215 demo --demo-locality=region=us-east1,az=1:region=us-central1,az=2:region=us-west2,az=3 --nodes=3
```

**Expected behavior**

I'd have expected that destroy_tenant would just drop the tenant entry like before.

This is what happens in *v22.1.5*:

```
# Server version: CockroachDB CCL v22.1.5 (x86_64-pc-linux-gnu, built 2022/07/28 14:58:04, go1.17.11) (same version as client)
# Cluster ID: 2aa2179d-322f-4f26-a104-75c3b90114d6
# Organization: Cockroach Demo
#
# Enter \? for a brief introduction.
#
demo@127.0.0.1:26257/movr> select * from crdb_internal.create_tenant(1000);
  crdb_internal.create_tenant
-------------------------------
                         1000
(1 row)


Time: 36ms total (execution 36ms / network 1ms)

demo@127.0.0.1:26257/movr> select * from crdb_internal.destroy_tenant(1000);
  crdb_internal.destroy_tenant
--------------------------------
                          1000
(1 row)


Time: 10ms total (execution 10ms / network 0ms)
```

### PR DESCRIPTION
**Pull request by knz**
Fixes #97873.

We aimed in #95691 to preserve compatibility with the previous semantics of `destroy_tenant()`, but we failed to do so and there was no test to tell us about the mistake.

This commit fixes both.

Release note: None

### CODE REVIEW

File: pkg/sql/tenant_deletion.go [hunk 1]
```diff
@@ -83,9 +83,13 @@ func dropTenantInternal(
...
 
 	if settings.Version.IsActive(ctx, clusterversion.V23_1TenantNamesStateAndServiceMode) {
+		if ignoreServiceMode {
+			// Compatibility with CC serverless use of crdb_internal.destroy_tenant().
+			info.ServiceMode = mtinfopb.ServiceModeNone
+		}
 		// We can only check the service mode after upgrading to a version
 		// that supports the service mode column.
-		if !ignoreServiceMode && info.ServiceMode != mtinfopb.ServiceModeNone {
+		if info.ServiceMode != mtinfopb.ServiceModeNone {
```
Comment (stevendanna) [inline pkg/sql/tenant_deletion.go:92]: In case this confuses others as well: This fixes the bug not because of anything wrong with this if condition, but rather because UpdateTenantRecord (called below) performs additional validation, which is why we need to explicitly override the ServiceMode above.

**Review by stevendanna — APPROVED** [review]
Thanks!

File: pkg/sql/tenant_deletion.go (hunk 1 above)
Comment (knz) [reply pkg/sql/tenant_deletion.go:92]: Is your feedback a request to add a comment?

Comment (knz) [reply pkg/sql/tenant_deletion.go:92]: i added the comment nonetheless.

**Comment by knz** [comment]
bors r=stevendanna

File: pkg/sql/tenant_deletion.go (hunk 1 above)
Comment (stevendanna) [reply pkg/sql/tenant_deletion.go:95]: I was mostly hoping to save Jay a few seconds of confusion in case he was reviewing it as well.  A comment may be nice, but I think it is fine to merge as-is.
