### PR TITLE
grpcutil: Catch "closed connection" error when using tls

### LINKED ISSUE #15158: teamcity: failed tests on master: acceptance/TestDockerMigration_7429
The following tests appear to have failed:

[#228372](https://teamcity.cockroachdb.com/viewLog.html?buildId=228372):

```
--- FAIL: acceptance/TestDockerMigration_7429 (6.420s)
test_log_scope.go:80: test logs captured to: /home/agent/work/.go/src/github.com/cockroachdb/cockroach/artifacts/acceptance/logTestDockerMigration_7429058687400
test_log_scope.go:61: use -show-logs to present logs inline
reference_test.go:41: non-zero exit code: 1
------- Stdout: -------
test logs left over in: /home/agent/work/.go/src/github.com/cockroachdb/cockroach/artifacts/acceptance/logTestDockerMigration_7429058687400

```
Please assign, take a look and update the issue accordingly.

### PR DESCRIPTION
**Pull request by a-robinson**
Since for some reason it's worded slightly differently than the non-tls
error. After securing the acceptance tests,cockroach quit flaked with
Error: Error sending drain request: rpc error: code = Internal desc = transport: tls: use of closed connection

Fixes #15158

### CODE REVIEW

File: pkg/util/grpcutil/grpc_util.go [hunk 1]
```diff
@@ -50,6 +50,7 @@ func IsClosedConnection(err error) bool {
 		grpc.Code(err) == codes.Unavailable ||
 		grpc.ErrorDesc(err) == grpc.ErrClientConnClosing.Error() ||
 		strings.Contains(err.Error(), "is closing") ||
+		strings.Contains(err.Error(), "use of closed connection") ||
```
Comment (tamird) [inline pkg/util/grpcutil/grpc_util.go]: Looks like there's some duplication between this and another check in `rpc/context_test.go`. Could you merge the two? See `gRPCErrorsRegex` in that file.

**Comment by andreimatei** [comment]
:lgtm: mod Tamir's comment.

I hate the TLS code; wrestled with it myself.

---

Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15160#-:-Ki5lsgLF4s8lhmNzKsJ:bud7fa1)*

File: pkg/util/grpcutil/grpc_util.go (hunk 1 above)
Comment (a-robinson) [inline pkg/util/grpcutil/grpc_util.go]: Nice catch, done.

**Comment by tamird** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks pending.

---

*[pkg/util/grpcutil/grpc_util.go, line 53 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/15160#-Ki5llKSlpRfR3F1Q3SB-r1-53:-Ki5sdmyiuS58vowl-z8:b7f409g) ([raw file](https://github.com/cockroachdb/cockroach/blob/76e3f583b1ed5a42418fc010211a273b68d2ce48/pkg/util/grpcutil/grpc_util.go#L53)):*
<details><summary><i>Previously, a-robinson (Alex Robinson) wrote…</i></summary><blockquote>

Nice catch, done.
</blockquote></details>

Let's keep the prefix on this one: `tls: use of closed connection`

---

*[pkg/util/grpcutil/grpc_util.go, line 55 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/15160#-Ki5suYmnxL_pe4g-A74:-Ki5suYmnxL_pe4g-A75:b-rox9wz) ([raw file](https://github.com/cockroachdb/cockroach/blob/ebece391dbf172c75152842260ac85f4974606bf/pkg/util/grpcutil/grpc_util.go#L55)):*
> ```Go
> 		strings.Contains(err.Error(), "use of closed connection") ||
> 		strings.Contains(err.Error(), "use of closed network connection") ||
> 		strings.Contains(err.Error(), "read/write on a closed pipe") ||
> ```

This one is `io.ErrClosedPipe.Error()`

---

*[pkg/util/grpcutil/grpc_util.go, line 56 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/15160#-Ki5syQqCd_hXaOPQJWm:-Ki5syQqCd_hXaOPQJWn:blxj29m) ([raw file](https://github.com/cockroachdb/cockroach/blob/ebece391dbf172c75152842260ac85f4974606bf/pkg/util/grpcutil/grpc_util.go#L56)):*
> ```Go
> 		strings.Contains(err.Error(), "use of closed network connection") ||
> 		strings.Contains(err.Error(), "read/write on a closed pipe") ||
> 		strings.Contains(err.Error(), "EOF") ||
> ```

`io.EOF.Error()` please.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15160)*

**Comment by a-robinson** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks pending.

---

*[pkg/util/grpcutil/grpc_util.go, line 53 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/15160#-Ki5llKSlpRfR3F1Q3SB-r1-53:-Ki5tZN9vKTUu6FFqWAF:b-ibrpir) ([raw file](https://github.com/cockroachdb/cockroach/blob/76e3f583b1ed5a42418fc010211a273b68d2ce48/pkg/util/grpcutil/grpc_util.go#L53)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

Let's keep the prefix on this one: `tls: use of closed connection`
</blockquote></details>

Why? That makes it less future proof for no clear benefit. Any use of a closed connection, tls or non-tls, would fall under the heading of `IsClosedConnection`

---

*[pkg/util/grpcutil/grpc_util.go, line 55 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/15160#-Ki5suYmnxL_pe4g-A74:-Ki5trVlEcMBH16IBoD6:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/ebece391dbf172c75152842260ac85f4974606bf/pkg/util/grpcutil/grpc_util.go#L55)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

This one is `io.ErrClosedPipe.Error()`
</blockquote></details>

Done.

---

*[pkg/util/grpcutil/grpc_util.go, line 56 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/15160#-Ki5syQqCd_hXaOPQJWm:-Ki5tsIA4bL7dfIxc7fX:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/ebece391dbf172c75152842260ac85f4974606bf/pkg/util/grpcutil/grpc_util.go#L56)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

`io.EOF.Error()` please.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15160)*

**Comment by tamird** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[pkg/util/grpcutil/grpc_util.go, line 53 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/15160#-Ki5llKSlpRfR3F1Q3SB-r1-53:-Ki5u5PSzC_fKess3C3d:b-hibymp) ([raw file](https://github.com/cockroachdb/cockroach/blob/76e3f583b1ed5a42418fc010211a273b68d2ce48/pkg/util/grpcutil/grpc_util.go#L53)):*
<details><summary><i>Previously, a-robinson (Alex Robinson) wrote…</i></summary><blockquote>

Why? That makes it less future proof for no clear benefit. Any use of a closed connection, tls or non-tls, would fall under the heading of `IsClosedConnection`
</blockquote></details>

Because it's more self-documenting. You already have "use of closed network connection" here, which is the error coming from "net". What is the upshot of trimming the prefix? `tls` produces this error string directly, it is not wrapping some other error, so the "reuse" you're implying here has no basis.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15160)*

**Comment by a-robinson** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[pkg/util/grpcutil/grpc_util.go, line 53 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/15160#-Ki5llKSlpRfR3F1Q3SB-r1-53:-Ki5uf9wouMwY3dK7eEn:b-ed5yqc) ([raw file](https://github.com/cockroachdb/cockroach/blob/76e3f583b1ed5a42418fc010211a273b68d2ce48/pkg/util/grpcutil/grpc_util.go#L53)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

Because it's more self-documenting. You already have "use of closed network connection" here, which is the error coming from "net". What is the upshot of trimming the prefix? `tls` produces this error string directly, it is not wrapping some other error, so the "reuse" you're implying here has no basis.
</blockquote></details>

The upshot of trimming the prefix is handling any other new code that returns this error without a "tls: " prefix. If that ever happens we'll have to come back and update this logic again.

Documenting more clearly where the error is coming from doesn't seem more valuable than the future-proofing given that a simple google search finds the source of it

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15160)*

**Comment by tamird** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[pkg/util/grpcutil/grpc_util.go, line 53 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/15160#-Ki5llKSlpRfR3F1Q3SB-r1-53:-Ki5w3xilDVeee0afEVp:bgmkeab) ([raw file](https://github.com/cockroachdb/cockroach/blob/76e3f583b1ed5a42418fc010211a273b68d2ce48/pkg/util/grpcutil/grpc_util.go#L53)):*
<details><summary><i>Previously, a-robinson (Alex Robinson) wrote…</i></summary><blockquote>

The upshot of trimming the prefix is handling any other new code that returns this error without a "tls: " prefix. If that ever happens we'll have to come back and update this logic again.

Documenting more clearly where the error is coming from doesn't seem more valuable than the future-proofing given that a simple google search finds the source of it
</blockquote></details>

In fact I consider the future proofing of this to be a downside, not an upside. This isn't a structured error, and matching intent using string comparisons is crazy enough as it is, we should be as strict as possible when we're forced to do it.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15160)*

**Comment by a-robinson** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[pkg/util/grpcutil/grpc_util.go, line 53 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/15160#-Ki5llKSlpRfR3F1Q3SB-r1-53:-Ki64YN_VSfyc3ARp3hs:b-r17dhw) ([raw file](https://github.com/cockroachdb/cockroach/blob/76e3f583b1ed5a42418fc010211a273b68d2ce48/pkg/util/grpcutil/grpc_util.go#L53)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

In fact I consider the future proofing of this to be a downside, not an upside. This isn't a structured error, and matching intent using string comparisons is crazy enough as it is, we should be as strict as possible when we're forced to do it.
</blockquote></details>

The intent of "use of closed connection" seems about as clear as an error's intent can possibly be, especially in the context of a method called `IsClosedConnection`. I'll give in, though.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15160)*

**Comment by tamird** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[pkg/util/grpcutil/grpc_util.go, line 53 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/15160#-Ki5llKSlpRfR3F1Q3SB-r1-53:-Ki65Qr4s-BjJaf25w2Z:bn84awb) ([raw file](https://github.com/cockroachdb/cockroach/blob/76e3f583b1ed5a42418fc010211a273b68d2ce48/pkg/util/grpcutil/grpc_util.go#L53)):*
<details><summary><i>Previously, a-robinson (Alex Robinson) wrote…</i></summary><blockquote>

The intent of "use of closed connection" seems about as clear as an error's intent can possibly be, especially in the context of a method called `IsClosedConnection`. I'll give in, though.
</blockquote></details>

Yes, that would be fine if you were matching on the entire string, but this is a substring match, it doesn't seem hard to construct an error that would confuse this.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15160#-:-Ki65huyFL7ScwVbyn4t:bnfp4nl)*
