### PR TITLE
sql/inspect: fix LTREE[] handling in query bounds

### LINKED ISSUE #156121: sql/inspect: support indexes with LTREE[] primary key columns
INSPECT’s index consistency checks build query bounds using primary key column types and comparison operators like < and >. This fails when a key column is of type LTREE[], since arrays don’t support these operators, causing the query to fail at compile time.

~~To handle this, we could limit the bounds to the leading comparable columns. This may broaden the scan range, and in the worst case—if the first key is non-comparable—each processor would scan the full table.~~

~~Currently, such indexes are skipped since they’re rare. This issue tracks adding support if they become more common.~~

EDIT: it was a bug in how the datum is rendered. It was leaving out the data type.

Jira issue: CRDB-55792

Epic CRDB-55075

### PR DESCRIPTION
**Pull request by spilchen**
INSPECT builds query bounds from primary key column types. When a table had an LTREE[] column, the bound datums could be interpreted as string[] by the query engine, causing errors like:
```
unsupported comparison operator: <ltree[]> >= <string[]>
```

This happened because the datum formatting omitted type information for array elements. For example, ['j.k.l']::LTREE[] was formatted as ARRAY['j.k.l'], which loses the cast. The fix marks the LTREE type as ambiguous so the formatter includes explicit type casts, avoiding mismatches in distributed queries.

While testing, I also added placeholder values to the logged query in inspect issues (previously only the query text was shown).

Informs: #155483
Closes: #156121
Epic: CRDB-55075

Release note: none

### CODE REVIEW

File: pkg/sql/inspect_job.go [hunk 1]
```diff
@@ -227,5 +220,21 @@ func isUnsupportedIndexForIndexConsistencyCheck(
 		return true
 	}
 
+	// Check if the primary key contains LTREE[] arrays. LTREE[] arrays don't
+	// support inequality comparison operators (<, >, <=, >=) which are required
+	// for generating span-based query predicates.
+	// TODO(156121): add support for indexes with LTREE[] primary keys.
```
Comment (rafiss) [inline pkg/sql/inspect_job.go]: Hm something seems off here -- if those comparisons don't exist, then I would think `LTREE[]` would not be allowed in the primary key. I checked the `ltree` logic tests, and the following does work:

```
root@localhost:26257/defaultdb> CREATE TABLE la (lta LTREE[]);
CREATE TABLE

root@localhost:26257/defaultdb> INSERT INTO la VALUES (ARRAY['A', 'A.B']), (ARRAY['A.B.C', 'A.B.D', 'Z']), (ARRAY['X', 'Y']), (ARRAY[]), (ARRAY['']),
                             -> (NULL);
                             ->
INSERT 0 6

root@localhost:26257/defaultdb> SELECT * FROM la WHERE lta > array['A.B']::ltree[] ORDER BY lta;
        lta
-------------------
  {A.B.C,A.B.D,Z}
  {X,Y}
(2 rows)
```

so perhaps something is wrong with the query being generated. what was the error?

**Review by rafiss — CHANGES_REQUESTED** [review]

File: pkg/sql/inspect_job.go (hunk 1 above)
Comment (spilchen) [reply pkg/sql/inspect_job.go]: The error that we got was something like this:
```
inspect-index-consistency-check: (@1 >= ARRAY['a.b.c']) AND (@1 <= ARRAY['g.h.i']): unsupported comparison operator: <ltree[]> >= <string[]>
```

The thing is that isn't really part of the query I run. I always use the type. A full query is too big to copy/paste, but I think it's this part:
```
pri_nonnull AS (
      SELECT pk_ltree_array, val FROM [107 AS table_pri]@{FORCE_INDEX=[1]} WHERE (
    (pk_ltree_array >= $1::LTREE[])
  )
  AND (
    (pk_ltree_array <= $2::LTREE[])
  ) AND (val IS NOT NULL)
  ),
```

I'm starting to think this may be a bug in the query code. When I pull out the exact query and run it manually (filling it literals for the placeholders). It's fine. It seems to be when the query is compiled with placeholders that we lose the LTREE[] type. 

This PR may end up being a block for LTREE[] until that bug is tracked down. But let me dig into it somemore.

**Review by spilchen — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/156122)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @rafiss and @spilchen)

File: pkg/sql/inspect_job.go (hunk 1 above)
Comment (rafiss) [reply pkg/sql/inspect_job.go]: thanks for the extra details. often we resolve errors like `unsupported comparison operator: <ltree[]> >= <string[]>` by adding an explicit cast to that value in the query.

Comment (spilchen) [reply pkg/sql/inspect_job.go]: Okay, I found the root cause. See the fix in datum.go. I update the PR/commit text since we aren't skipping LTREE now. Let me know if you think someone of SQL Queries should review this also.

**Review by spilchen — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/156122)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @rafiss and @spilchen)

**Review by rafiss — APPROVED** [review]
lgtm! thank you for tracking this down and fixing

**Review by mw5h — APPROVED** [review]
:lgtm:

**Review by yuzefovich — COMMENTED** [review]
Nice catch on `DLTree.AmbiguousFormat`! Do we plan to backport this change to 25.4? If not, we should probably backport the fix to `datum.go` file.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/156122#-:-OclYIEo9Sav_jRLayqI:b-gq7yfu)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @rafiss and @spilchen)

**Review by spilchen — COMMENTED** [review]
No, the INSPECT changes won't be backported. I'll separate the changes into two commits so that we can backport just the change to `datum.go`.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/156122#-:-OclZSdeDVLjKHO2ogP4:bl9ybma)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @rafiss and @spilchen)
