### PR TITLE
roachtest: disable backfill success check

### LINKED ISSUE #137093: roachtest: perturbation/full/backfill failed
roachtest.perturbation/full/backfill [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/18112167?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/18112167?buildTab=artifacts#/perturbation/full/backfill) on master @ [de3b1220f5c71ac966561505c1b379060fa1407f](https://github.com/cockroachdb/cockroach/commits/de3b1220f5c71ac966561505c1b379060fa1407f):

```
(assertions.go:363).Fail: 
	Error Trace:	pkg/cmd/roachtest/tests/perturbation/framework.go:671
	            				pkg/cmd/roachtest/test_runner.go:1322
	            				src/runtime/asm_amd64.s:1695
	Error:      	Should be true
	Test:       	perturbation/full/backfill
	Messages:   	FAILURE: follower-read  : Increase 529429.2047 > 40.0000 BASE: 6.799776ms SCORE: 1h0m0s
	            	
	            	FAILURE: read           : Increase 599969.5016 > 40.0000 BASE: 6.000305ms SCORE: 1h0m0s
	            	
	            	FAILURE: write          : Increase 193048.0812 > 40.0000 BASE: 18.648204ms SCORE: 1h0m0s
(require.go:1950).True: FailNow called
test artifacts and logs in: /artifacts/perturbation/full/backfill/run_1
```

Parameters:
 - <code>acMode=defaultOption</code>
 - <code>arch=amd64</code>
 - <code>blockSize=4096</code>
 - <code>cloud=gce</code>
 - <code>coverageBuild=false</code>
 - <code>cpu=16</code>
 - <code>diskBandwidthLimit=0</code>
 - <code>disks=2</code>
 - <code>encrypted=false</code>
 - <code>fillDuration=10m0s</code>
 - <code>fs=ext4</code>
 - <code>leaseType=epoch</code>
 - <code>localSSD=true</code>
 - <code>mem=standard</code>
 - <code>numNodes=12</code>
 - <code>numWorkloadNodes=1</code>
 - <code>perturbationDuration=10m0s</code>
 - <code>ratioOfMax=0.5</code>
 - <code>runtimeAssertionsBuild=false</code>
 - <code>seed=0</code>
 - <code>splits=10000</code>
 - <code>ssd=2</code>
 - <code>validationDuration=5m0s</code>
 - <code>vcpu=16</code>
<details><summary>Help</summary>
<p>

See: [roachtest README](https://github.com/cockroachdb/cockroach/blob/master/pkg/cmd/roachtest/README.md)

See: [How To Investigate \(internal\)](https://cockroachlabs.atlassian.net/l/c/SSSBr8c7)

See: [Grafana](https://go.crdb.dev/roachtest-grafana/teamcity-18112167/perturbation-full-backfill/1733839023050/1733842163258)

</p>
</details>
/cc @cockroachdb/kv-triage
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*perturbation/full/backfill.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/bazci/githubpost/issues)

</sub>

Jira issue: CRDB-45381

### LINKED ISSUE #137392: roachtest: perturbation/metamorphic/backfill failed
roachtest.perturbation/metamorphic/backfill [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_PerturbationNightlyGceBazel/18162949?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_PerturbationNightlyGceBazel/18162949?buildTab=artifacts#/perturbation/metamorphic/backfill) on master @ [603ff88e54d3e3f6e49b0f673abd5ec564bf418b](https://github.com/cockroachdb/cockroach/commits/603ff88e54d3e3f6e49b0f673abd5ec564bf418b). A Side-Eye cluster snapshot was captured on timeout: [https://app.side-eye.io/#/snapshots/468](https://app.side-eye.io/#/snapshots/468).

```
(test_runner.go:1371).runTest: test timed out (3h0m0s)
test artifacts and logs in: /artifacts/perturbation/metamorphic/backfill/run_1
```

Parameters:
 - <code>acMode=fullNormalElasticRepl</code>
 - <code>arch=amd64</code>
 - <code>blockSize=1024</code>
 - <code>cloud=gce</code>
 - <code>coverageBuild=false</code>
 - <code>cpu=16</code>
 - <code>diskBandwidthLimit=350MiB</code>
 - <code>disks=2</code>
 - <code>encrypted=false</code>
 - <code>fillDuration=10m0s</code>
 - <code>fs=ext4</code>
 - <code>leaseType=expiration</code>
 - <code>localSSD=true</code>
 - <code>mem=standard</code>
 - <code>numNodes=30</code>
 - <code>numWorkloadNodes=2</code>
 - <code>perturbationDuration=30m0s</code>
 - <code>ratioOfMax=0.5</code>
 - <code>runtimeAssertionsBuild=false</code>
 - <code>seed=-7744531226375341113</code>
 - <code>splits=10000</code>
 - <code>ssd=2</code>
 - <code>validationDuration=5m0s</code>
 - <code>vcpu=16</code>
<details><summary>Help</summary>
<p>

See: [roachtest README](https://github.com/cockroachdb/cockroach/blob/master/pkg/cmd/roachtest/README.md)

See: [How To Investigate \(internal\)](https://cockroachlabs.atlassian.net/l/c/SSSBr8c7)

See: [Grafana](https://go.crdb.dev/roachtest-grafana/teamcity-18162949/perturbation-metamorphic-backfill/1734073868387/1734084975057)

</p>
</details>
/cc @cockroachdb/kv-triage
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*perturbation/metamorphic/backfill.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/bazci/githubpost/issues)

</sub>

Jira issue: CRDB-45558

### PR DESCRIPTION
**Pull request by andrewbaptist**
The perturbation/*/backfill tests are flaky and are failing at least once a week with the default configuration. This change temporarily disables the check to allow easier investigation of the other failure modes such as backfill failing to complete and node OOMs. Once those are closed, and the test is running more stably, this threshold can be dropped.

Fixes: #137093
Fixes: #137392

Informs: #133114

Release note: None

### CODE REVIEW

File: pkg/cmd/roachtest/tests/perturbation/index_backfill.go [hunk 1]
```diff
@@ -27,7 +28,9 @@ type backfill struct{}
 var _ perturbation = backfill{}
 
 func (b backfill) setup() variations {
-	v := setup(b, 40.0)
+	// TODO(baptist): Track down why this test causes stalls and drop the value
+	// to something more reasonable (like 5) once this is done.
```
Comment (stevendanna) [inline pkg/cmd/roachtest/tests/perturbation/index_backfill.go:32]: Do we have an issue we can reference here?

**Review by stevendanna — APPROVED** [review]

File: pkg/cmd/roachtest/tests/perturbation/index_backfill.go (hunk 1 above)
Comment (andrewbaptist) [reply pkg/cmd/roachtest/tests/perturbation/index_backfill.go]: Good idea. I created #139262.

**Comment by andrewbaptist** [comment]
TFTR!

bors r=stevendanna

**Comment by kvoli** [comment]
Is the assign intentional @andrewbaptist? Usually I've seen this field used for the PR author.
