### PR TITLE
sql: soften AOST check to be a pgerror

### LINKED ISSUE #82179: sql: v22.1.0: cannot specify AS OF SYSTEM TIME with different timestamps
This issue was autofiled by Sentry. It represents a crash or reported error on a live cluster with telemetry enabled.

Sentry link: https://sentry.io/organizations/cockroach-labs/issues/3315875000/?referrer=webhooks_plugin

Panic message:

>conn_executor_exec.go:776: cannot specify AS OF SYSTEM TIME with different timestamps. expected: 1654036652.936867000,0, got: 1654036593.136867000,0
(1) assertion failure
Wraps: (2) attached stack trace
  -- stack trace:
  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).handleAOST
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:776
  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execStmtInOpenState
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:607
  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execStmt
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:143
  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execPortal
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:231
  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execCmd.func2
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:1951
  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execCmd
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:1953
  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).run
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:1799
  | github.com/cockroachdb/cockroach/pkg/sql.(*Server).ServeConn
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:747
  | github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*conn).processCommandsAsync.func1
  | 	github.com/cockroachdb/cockroach/pkg/sql/pgwire/conn.go:724
  | runtime.goexit
  | 	GOROOT/src/runtime/asm_amd64.s:1581
Wraps: (3) cannot specify AS OF SYSTEM TIME with different timestamps. expected: 1654036652.936867000,0, got: 1654036593.136867000,0
Error types: (1) *assert.withAssertionFailure (2) *withstack.withStack (3) *errutil.leafError
-- report composition:
*errutil.leafError: cannot specify AS OF SYSTEM TIME with different timestamps. expected: 1654036652.936867000,0, got: 1654036593.136867000,0
conn_executor_exec.go:776: *withstack.withStack (top exception)
*assert.withAssertionFailure

<details>
<summary>Stacktrace (expand for inline code snippets):</summary>

https://github.com/cockroachdb/cockroach/blob/5b78463ed2e7106a8477b63fa837564ad02bb510/pkg/sql/conn_executor_exec.go#L775-L777 in pkg/sql.(*connExecutor).handleAOST
https://github.com/cockroachdb/cockroach/blob/5b78463ed2e7106a8477b63fa837564ad02bb510/pkg/sql/conn_executor_exec.go#L606-L608 in pkg/sql.(*connExecutor).execStmtInOpenState
https://github.com/cockroachdb/cockroach/blob/5b78463ed2e7106a8477b63fa837564ad02bb510/pkg/sql/conn_executor_exec.go#L142-L144 in pkg/sql.(*connExecutor).execStmt
https://github.com/cockroachdb/cockroach/blob/5b78463ed2e7106a8477b63fa837564ad02bb510/pkg/sql/conn_executor_exec.go#L230-L232 in pkg/sql.(*connExecutor).execPortal
https://github.com/cockroachdb/cockroach/blob/5b78463ed2e7106a8477b63fa837564ad02bb510/pkg/sql/conn_executor.go#L1950-L1952 in pkg/sql.(*connExecutor).execCmd.func2
https://github.com/cockroachdb/cockroach/blob/5b78463ed2e7106a8477b63fa837564ad02bb510/pkg/sql/conn_executor.go#L1952-L1954 in pkg/sql.(*connExecutor).execCmd
https://github.com/cockroachdb/cockroach/blob/5b78463ed2e7106a8477b63fa837564ad02bb510/pkg/sql/conn_executor.go#L1798-L1800 in pkg/sql.(*connExecutor).run
https://github.com/cockroachdb/cockroach/blob/5b78463ed2e7106a8477b63fa837564ad02bb510/pkg/sql/conn_executor.go#L746-L748 in pkg/sql.(*Server).ServeConn
https://github.com/cockroachdb/cockroach/blob/5b78463ed2e7106a8477b63fa837564ad02bb510/pkg/sql/pgwire/conn.go#L723-L725 in pkg/sql/pgwire.(*conn).processCommandsAsync.func1
GOROOT/src/runtime/asm_amd64.s#L1580-L1582 in runtime.goexit
</details>

```
pkg/sql/conn_executor_exec.go in pkg/sql.(*connExecutor).handleAOST at line 776
pkg/sql/conn_executor_exec.go in pkg/sql.(*connExecutor).execStmtInOpenState at line 607
pkg/sql/conn_executor_exec.go in pkg/sql.(*connExecutor).execStmt at line 143
pkg/sql/conn_executor_exec.go in pkg/sql.(*connExecutor).execPortal at line 231
pkg/sql/conn_executor.go in pkg/sql.(*connExecutor).execCmd.func2 at line 1951
pkg/sql/conn_executor.go in pkg/sql.(*connExecutor).execCmd at line 1953
pkg/sql/conn_executor.go in pkg/sql.(*connExecutor).run at line 1799
pkg/sql/conn_executor.go in pkg/sql.(*Server).ServeConn at line 747
pkg/sql/pgwire/conn.go in pkg/sql/pgwire.(*conn).processCommandsAsync.func1 at line 724
GOROOT/src/runtime/asm_amd64.s in runtime.goexit at line 1581
```

| Tag | Value |
|---|---|
| Cockroach Release | `v22.1.0` |
| Cockroach SHA: | 5b78463ed2e7106a8477b63fa837564ad02bb510 |
| Platform | linux amd64 |
| Distribution | CCL |
| Environment | v22.1.0 |
| Command | server |
| Go Version | ``|
| # of CPUs ||
| # of Goroutines ||

Jira issue: CRDB-16241
Epic CRDB-14049

### PR DESCRIPTION
**Pull request by otan**
Resolves #82179

Release note (bug fix): Previously, using AS OF SYSTEM TIME of two
different statements in the same line would result in an assertion
error. This is now a PG error with code 0A000.

### CODE REVIEW

File: pkg/sql/conn_executor_exec.go [hunk 1]
```diff
@@ -775,9 +775,11 @@ func (ex *connExecutor) handleAOST(ctx context.Context, stmt tree.Statement) err
 			}
 			return errors.AssertionFailedf("expected bounded_staleness set with a max_timestamp_bound")
 		}
-		return errors.AssertionFailedf(
+		return pgerror.Newf(
+			pgcode.FeatureNotSupported,
```
Comment (rafiss) [inline pkg/sql/conn_executor_exec.go:779]: could also be InvalidParameter, but up to you

**Review by rafiss — APPROVED** [review]
lgtm! do you think there are any cases that should still be treated as an assertion error? if so, then maybe we want to detect this differently.

File: pkg/ccl/logictestccl/testdata/logic_test/as_of [hunk 2]
```diff
@@ -29,6 +29,9 @@ BEGIN AS OF SYSTEM TIME follower_read_timestamp(); SELECT * FROM t
 statement ok
 ROLLBACK
 
+statement error pgcode 0A000 cannot specify AS OF SYSTEM TIME with different timestamps
```
Comment (rafiss) [inline pkg/ccl/logictestccl/testdata/logic_test/as_of:32]: ah actually i just realized, this is affecting 22.1, which has `enable_implicit_transaction_for_batch_statements` set to false.

based on the stack trace in https://github.com/cockroachdb/cockroach/issues/82179 it looks like this happened when executing a prepared statement (there is `execPortal` in the stack trace)

also it shows that it's from this line: https://github.com/cockroachdb/cockroach/blob/5b78463ed2e7106a8477b63fa837564ad02bb510/pkg/sql/conn_executor_exec.go#L776

**Review by rafiss — CHANGES_REQUESTED** [review]

File: pkg/ccl/logictestccl/testdata/logic_test/as_of (hunk 2 above)
Comment (rafiss) [reply pkg/ccl/logictestccl/testdata/logic_test/as_of:32]: oh that's the line you updated. ok. i'm fine with this change

**Review by rafiss — APPROVED** [review]

File: pkg/ccl/logictestccl/testdata/logic_test/as_of (hunk 2 above)
Comment (rafiss) [reply pkg/ccl/logictestccl/testdata/logic_test/as_of:32]: i think it's because we also use an implicit transaction for the extended protocol now (https://github.com/cockroachdb/cockroach/pull/76792), so a test for that  too would be nice.

File: pkg/sql/conn_executor_exec.go (hunk 1 above)
Comment (otan) [reply pkg/sql/conn_executor_exec.go:779]: i'm keeping it as this to be consistent with the other places

File: pkg/ccl/logictestccl/testdata/logic_test/as_of (hunk 2 above)
Comment (otan) [reply pkg/ccl/logictestccl/testdata/logic_test/as_of:32]: do you know how it'd be triggered using the extended protocol?

Comment (rafiss) [reply pkg/ccl/logictestccl/testdata/logic_test/as_of:32]: yeah, i think  if you do something like:

```
Parse SELECT .. AOST '-1us`
Bind
Exec
Parse SELECT ... AOST '-4us'
Bind
Exec
Sync
```

hmm but that wouldn't cause it during ExecPortal

what if you do
```
Parse SELECT .. AOST follower_read_timestamp()
Bind
Exec
Sync
```

Comment (otan) [reply pkg/ccl/logictestccl/testdata/logic_test/as_of:32]: dones

**Comment by otan** [comment]
bors r=rafiss
