### PR TITLE
sql: chunk deletions

### LINKED ISSUE #17921: DELETE FROM ... [returning nothing] crashes a node
A cluster has 3 nodes running on Cockroachdb 1.0.5 (Linux, 64bit)
A db has about 195 millions of records.
Scheme is 
```
CREATE TABLE stats (
	numa STRING(32) NULL,
	bytes INT NULL,
	amount DECIMAL NULL,
	ts TIMESTAMP NULL,
	da INT NULL,
	INDEX idx_stats_ts (ts ASC) STORING (numa, bytes, amount, da),
	FAMILY "primary" (numa, bytes, amount, ts, da, rowid)
)
```
The db has data of an one month.
I want to delete data starting from second day of month, so
I run either  `delete from stats where ts > '2017-01-01 23:59:59'::timestamp;` or `delete from stats where ts > '2017-01-01 23:59:59'::timestamp returning nothing;`.
I use the `cockroach sql --insecure --host = ...` command to run my query.
After some minutes an used node dies.
A db driver returns - bad connection.
And there are a lot of messages like that `context canceled while in command queue: ResolveIntent...` in the log.

All nodes have free space.

Do I have to delete data by chunks?

Thanks.

### PR DESCRIPTION
**Pull request by tbg**
In the absence of a fast path deletion, `DELETE` would generate one
potentially giant batch and OOM the gateway node. This became obvious
quickly via heap profiling.

Added chunking of the deletions to `tableDeleter`. SQL folks may have
stronger opinions on how to achieve this, or a better idea of a
preexisting chunking mechanism that works more reliably. If nothing
else, this change serves as a prototype to fix #17921.

With this change, `roachtest run drop` works (as in, it doesn't
out-of-memory right away; the run takes a long time so I can't yet
confirm that it actually passes).

Release note (sql change): deleting many rows at once now consumes less
memory.

### CODE REVIEW

File: pkg/sql/tablewriter.go [hunk 1]
```diff
@@ -736,6 +737,15 @@ func (td *tableDeleter) init(txn *client.Txn, evalCtx *tree.EvalContext) error {
 func (td *tableDeleter) row(
 	ctx context.Context, values tree.Datums, traceKV bool,
 ) (tree.Datums, error) {
+	if td.batchSize > 10000 {
```
Comment (knz) [inline pkg/sql/tablewriter.go]: extract the constant in the global scope and give it an explanatory comment.

**Review by knz — APPROVED** [review]
LGTM with nit

**Comment by knz** [comment]
if this merges into master, please also cherry-pick into 2.0

**Comment by petermattis** [comment]
:lgtm:

---

Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[pkg/sql/tablewriter.go, line 740 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/22991#-L60IBCvGOEhwsQl7MwQ-r1-740:-L6276rcKerj4SbMSkxM:b-roebv5) ([raw file](https://github.com/cockroachdb/cockroach/blob/ca55a93e81193bf17733b469f13aaca26019a719/pkg/sql/tablewriter.go#L740)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

extract the constant in the global scope and give it an explanatory comment.
</blockquote></details>

Not sure the constant needs to be in the global scope given it is only accessed here, but :thumbsup: on making a constant.

Also, shouldn't this be `>=`? Otherwise you'll be running batches of 10001 rows, which while not wrong, offends my sense of propriety.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/22991#-:-L627yRhJLmEcwKZCVpw:bnfp4nl)*

**Comment by spencerkimball** [comment]
@tschottdorf (+@knz, @andreimatei) when I ran this locally, I noticed that we seem to be scanning and buffering the entire set of rows to be deleted. It seems with this change that the total memory footprint should not soar into the GiBs. Why doesn't SQL consume rows from the scanner in a streaming fashion to feed to the table writer?

**Comment by andreimatei** [comment]
Spencer is this what you're looking for?
https://github.com/cockroachdb/cockroach/issues/16180
