### PR TITLE
server, ui: fix data distribution endpoint

### LINKED ISSUE #24853: server: ReplicaMatrix endpoint errors after a database has dropped
*repro*

- create a database
- drop it
- hit the replica matrix endpoint

*expected*

- dropped db either doesn't show up, or is marked as dropped

*actual*

- endpoint errors, with message `relation [<db id>].<table> doesn't exist` in the log.

This is because when you do a `DROP DATABASE CASCADE`, the database's tables still show up in `crdb_internal.tables`, but with `[<db id>]` as the database name: https://github.com/cockroachdb/cockroach/blob/65c0bfbd64ca6d92ac3d2c655415a0d1433586d6/pkg/sql/crdb_internal.go#L220-L224

A simple fix is to not return dropped tables at all, or return them marked as deleted. However, a complete response would probably reflect the fact that a dropped table still takes up space in the cluster until the data in its replicas has been GC'd (may take 25 hours).

### PR DESCRIPTION
**Pull request by vilterp**
Still needs some design tweaks (@couchand suggested greying out dropped tables instead of red-asterisk-ing them), but the backend part is ready for review.

Fixes #24853

image

### CODE REVIEW

**Comment by vilterp** [comment]
Roachtest timed out in CI — I think it's spurious; hit rebuild.

File: pkg/ui/src/views/cluster/containers/dataDistribution/replicaMatrix.tsx [hunk 1]
```diff
@@ -94,6 +100,32 @@ class ReplicaMatrix extends Component<ReplicaMatrixProps, ReplicaMatrixState> {
     return `${arrow} ${label}`;
   }
 
+  rowLabel(row: FlattenedNode<SchemaObject>) {
+    const text = this.rowLabelText(row);
+
+    const droppedIndicator = row.data.droppedAt
```
Comment (couchand) [inline pkg/ui/src/views/cluster/containers/dataDistribution/replicaMatrix.tsx]: Since you've got the conditional below anyway, you can get rid of this one entirely.

File: pkg/ui/src/views/shared/components/loading/index.tsx [hunk 2]
```diff
@@ -12,11 +12,12 @@ interface LoadingProps {
 // * loading prop is true.
 // *
 export default function Loading(props: LoadingProps) {
+  const className = props.className || "loading-image loading-image__spinner-left";
```
Comment (couchand) [inline pkg/ui/src/views/shared/components/loading/index.tsx]: Nice.  Heck, why not `const imagePath = props.image || spinner;`, too?

**Review by couchand — APPROVED** [review]
Looks great!

File: pkg/ui/src/views/shared/components/loading/index.tsx (hunk 2 above)
Comment (vilterp) [reply pkg/ui/src/views/shared/components/loading/index.tsx]: Done. Hilarious how many call sites pass the same thing, and that we didn't do this earlier 😂

File: pkg/ui/src/views/cluster/containers/dataDistribution/replicaMatrix.tsx (hunk 1 above)
Comment (vilterp) [reply pkg/ui/src/views/cluster/containers/dataDistribution/replicaMatrix.tsx]: Got rid of this anyway since changed from asterisk to greying out dropped tables
