### PR TITLE
roachtest: create kafka topics manually before consuming

### LINKED ISSUE #155512: roachtest: cdc/kafka-topics failed
roachtest.cdc/kafka-topics [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/20608571?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/20608571?buildTab=artifacts#/cdc/kafka-topics) on master @ [4b80cd59c6299f26b2b4f02a96064d5127ccad94](https://github.com/cockroachdb/cockroach/commits/4b80cd59c6299f26b2b4f02a96064d5127ccad94):

```
(monitor.go:267).Wait: monitor failure: kafka server: Request was for a topic or partition that does not exist on this broker
test artifacts and logs in: /artifacts/cdc/kafka-topics/run_1
```

Parameters:
 - <code>arch=amd64</code>
 - <code>cloud=gce</code>
 - <code>coverageBuild=false</code>
 - <code>cpu=4</code>
 - <code>encrypted=false</code>
 - <code>fs=ext4</code>
 - <code>localSSD=true</code>
 - <code>metamorphicLeases=default</code>
 - <code>metamorphicWriteBuffering=true</code>
 - <code>runtimeAssertionsBuild=false</code>
 - <code>ssd=0</code>
<details><summary>Help</summary>
<p>

See: [roachtest README](https://github.com/cockroachdb/cockroach/blob/master/pkg/cmd/roachtest/README.md)

See: [How To Investigate \(internal\)](https://cockroachlabs.atlassian.net/l/c/SSSBr8c7)

See: [Grafana](https://go.crdb.dev/roachtest-grafana/teamcity-20608571/cdc-kafka-topics/1760600984033/1760601428612)

</p>
</details>
/cc @cockroachdb/cdc
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*cdc/kafka-topics.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/bazci/githubpost/issues)

</sub>

Jira issue: CRDB-55467

### LINKED ISSUE #155675: roachtest: cdc/kafka-topics failed
roachtest.cdc/kafka-topics [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/20621045?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/20621045?buildTab=artifacts#/cdc/kafka-topics) on master @ [d3e894c7937e255e7472a0b5311b56d82ddd4f43](https://github.com/cockroachdb/cockroach/commits/d3e894c7937e255e7472a0b5311b56d82ddd4f43):

```
(monitor.go:267).Wait: monitor failure: kafka server: Request was for a topic or partition that does not exist on this broker
test artifacts and logs in: /artifacts/cdc/kafka-topics/run_1
```

Parameters:
 - <code>arch=amd64</code>
 - <code>cloud=gce</code>
 - <code>coverageBuild=false</code>
 - <code>cpu=4</code>
 - <code>encrypted=false</code>
 - <code>fs=ext4</code>
 - <code>localSSD=true</code>
 - <code>metamorphicLeases=leader</code>
 - <code>runtimeAssertionsBuild=false</code>
 - <code>ssd=0</code>
<details><summary>Help</summary>
<p>

See: [roachtest README](https://github.com/cockroachdb/cockroach/blob/master/pkg/cmd/roachtest/README.md)

See: [How To Investigate \(internal\)](https://cockroachlabs.atlassian.net/l/c/SSSBr8c7)

See: [Grafana](https://go.crdb.dev/roachtest-grafana/teamcity-20621045/cdc-kafka-topics/1760773853641/1760774303523)

</p>
</details>
/cc @cockroachdb/cdc
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*cdc/kafka-topics.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/bazci/githubpost/issues)

</sub>

Jira issue: CRDB-55537

### LINKED ISSUE #160064: roachtest: cdc/kafka-topics failed
**Note:** This build has runtime assertions enabled. If the same failure was hit in a run without assertions enabled, there should be a similar failure without this message. If there isn&#39;t one, then this failure is likely due to an assertion violation or (assertion) timeout.

roachtest.cdc/kafka-topics [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/20900401?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/20900401?buildTab=artifacts#/cdc/kafka-topics) on release-26.1 @ [cb0cd727a4fe4b3c9e14709a4f6c573e691f86f2](https://github.com/cockroachdb/cockroach/commits/cb0cd727a4fe4b3c9e14709a4f6c573e691f86f2):

Failed with:

```
(monitor.go:267).Wait: monitor failure: kafka server: Request was for a topic or partition that does not exist on this broker
test artifacts and logs in: /artifacts/cdc/kafka-topics/run_1
```
Cluster Node to Ip Mapping:
| Node | Public IP | Private IP |
| --- | --- | --- |
| teamcity-20900401-1766474063-79-n4cpu4-0001 | 34.75.70.167 | 10.142.0.63 |
| teamcity-20900401-1766474063-79-n4cpu4-0002 | 35.229.74.58 | 10.142.0.8 |
| teamcity-20900401-1766474063-79-n4cpu4-0003 | 35.229.20.231 | 10.142.0.66 |
| teamcity-20900401-1766474063-79-n4cpu4-0004 | 34.74.213.237 | 10.142.1.24 |

Parameters:
 - <code>arch=amd64</code>
 - <code>cloud=gce</code>
 - <code>coverageBuild=false</code>
 - <code>cpu=4</code>
 - <code>encrypted=false</code>
 - <code>fs=ext4</code>
 - <code>localSSD=true</code>
 - <code>metamorphicLeases=default</code>
 - <code>metamorphicWriteBuffering=true</code>
 - <code>runtimeAssertionsBuild=true</code>
 - <code>ssd=0</code>
<details><summary>Help</summary>
<p>

See: [roachtest README](https://github.com/cockroachdb/cockroach/blob/master/pkg/cmd/roachtest/README.md)

See: [How To Investigate \(internal\)](https://cockroachlabs.atlassian.net/l/c/SSSBr8c7)

See: [Grafana](https://go.crdb.dev/roachtest-grafana/teamcity-20900401/cdc-kafka-topics/1766492082789/1766492533627)

</p>
</details>
<details><summary>Same failure on other branches</summary>
<p>

- #155675 roachtest: cdc/kafka-topics failed [A-cdc C-test-failure O-roachtest O-robot P-3 T-cdc X-duplicate branch-master]
</p>
</details>
/cc @cockroachdb/cdc
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*cdc/kafka-topics.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/bazci/githubpost/issues)

</sub>

Jira issue: CRDB-58135

### LINKED ISSUE #162293: roachtest: cdc/crdb-chaos failed
roachtest.cdc/crdb-chaos [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyAzureBazel/21058806?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyAzureBazel/21058806?buildTab=artifacts#/cdc/crdb-chaos) on master @ [9f3a52ff608d1b01713148aa74a802917c00c990](https://github.com/cockroachdb/cockroach/commits/9f3a52ff608d1b01713148aa74a802917c00c990):

Failed with:

```
(monitor.go:267).Wait: monitor failure: kafka server: Request was for a topic or partition that does not exist on this broker
test artifacts and logs in: /artifacts/cdc/crdb-chaos/run_1
```
Cluster Node to Ip Mapping:
| Node | Public IP | Private IP |
| --- | --- | --- |
| teamcity-21058806-1770101631-10-n4cpu16-0001 | 74.235.105.156 | 10.1.0.111 |
| teamcity-21058806-1770101631-10-n4cpu16-0002 | 20.51.241.239 | 10.1.0.110 |
| teamcity-21058806-1770101631-10-n4cpu16-0003 | 40.76.226.194 | 10.1.0.109 |
| teamcity-21058806-1770101631-10-n4cpu16-0004 | 20.102.42.196 | 10.1.0.144 |

Parameters:
 - <code>arch=amd64</code>
 - <code>cloud=azure</code>
 - <code>coverageBuild=false</code>
 - <code>cpu=16</code>
 - <code>diskCount=0</code>
 - <code>encrypted=false</code>
 - <code>fs=ext4</code>
 - <code>localSSD=true</code>
 - <code>metamorphicLeases=expiration</code>
 - <code>runtimeAssertionsBuild=false</code>
<details><summary>Help</summary>
<p>

See: [roachtest README](https://github.com/cockroachdb/cockroach/blob/master/pkg/cmd/roachtest/README.md)

See: [How To Investigate \(internal\)](https://cockroachlabs.atlassian.net/l/c/SSSBr8c7)

_Grafana is not yet available for azure clusters_</p>
</details>
/cc @cockroachdb/cdc
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*cdc/crdb-chaos.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/bazci/githubpost/issues)

</sub>

Jira issue: CRDB-59362

### LINKED ISSUE #163153: roachtest: cdc/kafka-chaos failed
roachtest.cdc/kafka-chaos [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyAzureBazel/21079874?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyAzureBazel/21079874?buildTab=artifacts#/cdc/kafka-chaos) on master @ [fdb92776bd279bee489ced860ce37f6c003827aa](https://github.com/cockroachdb/cockroach/commits/fdb92776bd279bee489ced860ce37f6c003827aa):

Failed with:

```
(monitor.go:267).Wait: monitor failure: kafka server: Request was for a topic or partition that does not exist on this broker
test artifacts and logs in: /artifacts/cdc/kafka-chaos/run_1
```
Cluster Node to Ip Mapping:
| Node | Public IP | Private IP |
| --- | --- | --- |
| teamcity-21079874-1770533712-28-n4cpu16-0001 | 20.55.83.199 | 10.1.0.115 |
| teamcity-21079874-1770533712-28-n4cpu16-0002 | 48.217.232.122 | 10.1.0.116 |
| teamcity-21079874-1770533712-28-n4cpu16-0003 | 20.55.0.210 | 10.1.0.113 |
| teamcity-21079874-1770533712-28-n4cpu16-0004 | 52.146.91.167 | 10.1.0.117 |

Parameters:
 - <code>arch=amd64</code>
 - <code>cloud=azure</code>
 - <code>coverageBuild=false</code>
 - <code>cpu=16</code>
 - <code>diskCount=0</code>
 - <code>encrypted=false</code>
 - <code>metamorphicLeases=leader</code>
 - <code>runtimeAssertionsBuild=false</code>
<details><summary>Help</summary>
<p>

See: [roachtest README](https://github.com/cockroachdb/cockroach/blob/master/pkg/cmd/roachtest/README.md)

See: [How To Investigate \(internal\)](https://cockroachlabs.atlassian.net/l/c/SSSBr8c7)

_Grafana is not yet available for azure clusters_</p>
</details>
/cc @cockroachdb/cdc
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*cdc/kafka-chaos.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/bazci/githubpost/issues)

</sub>

Jira issue: CRDB-60080

### LINKED ISSUE #164590: roachtest: cdc/tpcc-100/10min/sink=kafka/envelope=enriched failed
roachtest.cdc/tpcc-100/10min/sink=kafka/envelope=enriched [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/21176419?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/21176419?buildTab=artifacts#/cdc/tpcc-100/10min/sink=kafka/envelope=enriched) on release-26.1.1-rc @ [0fbf7b3d1b76716bc22e362b21f263d66fc81bf5](https://github.com/cockroachdb/cockroach/commits/0fbf7b3d1b76716bc22e362b21f263d66fc81bf5):

Failed with:

```
(monitor.go:267).Wait: monitor failure: kafka server: Request was for a topic or partition that does not exist on this broker
test artifacts and logs in: /artifacts/cdc/tpcc-100/10min/sink=kafka/envelope=enriched/cpu_arch=fips/run_1
```
Cluster Node to Ip Mapping:
| Node | Public IP | Private IP |
| --- | --- | --- |
| teamcity-21176419-1772262673-35-n4cpu16-0001 | 34.139.168.29 | 10.142.2.158 |
| teamcity-21176419-1772262673-35-n4cpu16-0002 | 34.26.173.141 | 10.142.2.206 |
| teamcity-21176419-1772262673-35-n4cpu16-0003 | 34.75.204.26 | 10.142.2.207 |
| teamcity-21176419-1772262673-35-n4cpu16-0004 | 34.26.167.21 | 10.142.2.225 |

Parameters:
 - <code>arch=fips</code>
 - <code>cloud=gce</code>
 - <code>coverageBuild=false</code>
 - <code>cpu=16</code>
 - <code>diskCount=0</code>
 - <code>encrypted=false</code>
 - <code>metamorphicLeases=default</code>
 - <code>runtimeAssertionsBuild=false</code>
<details><summary>Help</summary>
<p>

See: [roachtest README](https://github.com/cockroachdb/cockroach/blob/master/pkg/cmd/roachtest/README.md)

See: [How To Investigate \(internal\)](https://cockroachlabs.atlassian.net/l/c/SSSBr8c7)

See: [Grafana](https://go.crdb.dev/roachtest-grafana/teamcity-21176419/cdc-tpcc-100-10min-sink-kafka-envelope-enriched/1772270738304/1772271568666)

</p>
</details>
/cc @cockroachdb/cdc
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*cdc/tpcc-100/10min/sink=kafka/envelope=enriched.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/bazci/githubpost/issues)

</sub>

Jira issue: CRDB-60884

### PR DESCRIPTION
**Pull request by aerfrei**
Previously, Kafka topic consumers were started in setupSink before
the changefeed was created without being explicitly created. This
meant consumers could call Partitions() before the topics existed
in Kafka if the changefeed didn't create them in time. While Kafka can
auto-create topics on metadata requests, this didn't always succeed,
likely due to a race with leader, resulting in
  "Request was for a topic or partition that does not exist on this
  broker".
The error was buffered in the monitor's errgroup and only
surfaced at shutdown.

Manually creating the topics ensures this doesn't happen and the test
doesn't flake.

Fixes: https://github.com/cockroachdb/cockroach/issues/164590
Fixes: https://github.com/cockroachdb/cockroach/issues/162293
Fixes: https://github.com/cockroachdb/cockroach/issues/163153
Fixes: https://github.com/cockroachdb/cockroach/issues/155512
Fixes: https://github.com/cockroachdb/cockroach/issues/160064
Fixes: https://github.com/cockroachdb/cockroach/issues/155675

Release note: None

### CODE REVIEW

File: pkg/cmd/roachtest/tests/cdc.go [hunk 1]
```diff
@@ -632,6 +631,14 @@ func (ct *cdcTester) newChangefeed(args feedArgs) changefeedJob {
 
 	ct.t.Status(fmt.Sprintf("created changefeed %s with jobID %d", cj.Label(), jobID))
 
+	// Start topic consumers after the changefeed has been created so that the
```
Comment (andyyang890) [inline pkg/cmd/roachtest/tests/cdc.go]: Wouldn't we still have a race where the changefeed might not have created the topics yet? Could we instead manually create the topics in `setupSink`?  You can look at `cdc/bank` as an example.

Or alternatively maybe `startTopicConsumers` should have a retry loop.

**Review by andyyang890 — CHANGES_REQUESTED** [review]

**Review by DarrylWong — APPROVED** [review]
LGTM

File: pkg/cmd/roachtest/tests/cdc.go [hunk 2]
```diff
@@ -283,6 +283,18 @@ func (ct *cdcTester) setupSink(args feedArgs) string {
 		kafka.mon = ct.mon
 		kafka.validateOrder = args.kafkaArgs.validateOrder
 
+		// Manually create Kafka topics so that topic consumers can start
+		// without racing on auto-creation by the changefeed.
+		for _, target := range args.targets {
+			topic := target
+			if i := strings.LastIndex(target, "."); i != -1 {
```
Comment (andyyang890) [inline pkg/cmd/roachtest/tests/cdc.go]: nit:
```suggestion
			if i := strings.LastIndex(topic, "."); i != -1 {
```

**Review by andyyang890 — APPROVED** [review]

**Comment by aerfrei** [comment]
blathers backport-all
