### PR TITLE
sql: migration for descriptors fixes

### LINKED ISSUE #65012: sql: create long running migration to fix privilege descriptors for tables/db created on 20.1 or before
Would like a more permanent solution to fixing USAGE on tables/db descs created in 20.1.

https://github.com/cockroachdb/cockroach/pull/65010 

Example:
https://github.com/cockroachdb/cockroach/blob/master/pkg/migration/migrations/foreign_key_representation_upgrade.go

Must also make sure restore is aware of this case:
https://github.com/cockroachdb/cockroach/issues/58611

Epic CRDB-2476

### PR DESCRIPTION
**Pull request by RichardJCai**
This migration fixes corrupted privilege descriptors in the wild resulting
from the fallout of the ZONECONFIG/USAGE bug and the ALTER DATABASE CONVERT TO
SCHEMA bug. Additionally, all privilege descriptors will be updated to explicitly
have Owners. Privilege descriptors created before 20.2 do not have their owner field
set and instead owners are implicitly inferred.

Finally all privilege descriptors will be bumped up to Version21_2 after the migration
so we can strictly validate privileges.

Release note (bugfix): This migration will be run when users upgrade to
21.2 (Specifically 21.2.14).
This migration fixes any privilege descriptors that are corrupted from the
fallout of the ZONECONFIG/USAGE bug on tables and databases after upgrading
from 20.1 -> 20.2 (#65010) and those that are corrupted after converting a
database to a schema (#65697).

Fixes #65012

### CODE REVIEW

File: pkg/migration/migrations/fix_privileges_migration.go [hunk 1]
```diff
@@ -0,0 +1,172 @@
...
+			if err != nil {
+				return err
+			}
+			privilegeDesc = desc.GetPrivileges()
+		case privilege.Type:
+			desc, err = descriptors.GetMutableTypeByID(ctx, txn, upgrade, tree.ObjectLookupFlags{
+				CommonLookupFlags: tree.CommonLookupFlags{Required: true}},
+			)
+			privilegeDesc = desc.GetPrivileges()
+		}
```
Comment (postamar) [inline pkg/migration/migrations/fix_privileges_migration.go:81]: `desc, err := descriptors.GetMutableDescriptorByID(...)`?

File: pkg/migration/migrations/fix_privileges_migration.go [hunk 2]
```diff
@@ -0,0 +1,172 @@
...
+				privilegeDesc.SetOwner(security.NodeUserName())
+			}
+			privilegeDesc.SetOwner(security.RootUserName())
+		}
+
+		if privilegeDesc.Version < descpb.Version21_2 {
+			privilegeDesc.SetVersion(descpb.Version21_2)
+		}
+
+		return descriptors.WriteDesc(ctx, false /* kvTrace */, desc, txn)
```
Comment (postamar) [inline pkg/migration/migrations/fix_privileges_migration.go:102]: I allude to this in another comment but wouldn't having one transaction per descriptor be wasteful?

File: pkg/migration/migrations/fix_privileges_migration.go [hunk 3]
```diff
@@ -0,0 +1,172 @@
...
+		if err := fixPrivileges(ctx, idToUpgrade, d, objectType); err != nil {
+			return err
+		}
+		lastUpgradedID = idToUpgrade
+	}
+}
+
+func fixPrivileges(
+	ctx context.Context, upgrade descpb.ID, d migration.TenantDeps, objectType privilege.ObjectType,
+) error {
```
Comment (postamar) [inline pkg/migration/migrations/fix_privileges_migration.go:50]: This might be out of scope but would it be possible to also apply `descpb.MaybeFixPrivileges` and perhaps `descpb.MaybeFixUsagePrivForTablesAndDBs` in this migration instead of having to rely solely on the `RunPostDeserializationChanges` method of `catalog.DescriptorBuilder` for this purpose?

File: pkg/migration/migrations/fix_privileges_migration_external_test.go [hunk 4]
```diff
@@ -0,0 +1,218 @@
...
+		   							SELECT id
+		   								FROM system.namespace
+		   							 WHERE "parentID"
+		   										 = (
+		   													SELECT id
+		   														FROM system.namespace
+		   													 WHERE "parentID" = 0 AND name = 'db'
+		   											)
+		   									OR "parentID" = 0 AND name = 'db'
+		   					);
```
Comment (postamar) [inline pkg/migration/migrations/fix_privileges_migration_external_test.go:64]: The formatting here is all weird (in github at least), is this expected?

File: pkg/migration/migrations/fix_privileges_migration_external_test.go [hunk 5]
```diff
@@ -0,0 +1,218 @@
...
+		db := tc.ServerConn(0)
+		kvDB := tc.Server(0).DB()
+		require.NoError(t, sqlutils.InjectDescriptors(ctx, db, descriptorsToInject, true))
+
+		_, err := tc.Conns[0].ExecContext(ctx, `SET CLUSTER SETTING version = $1`,
+			clusterversion.ByKey(clusterversion.FixedPrivilegeDescriptors).String())
+		require.NoError(t, err)
+
+		err = kvDB.Txn(ctx, func(ctx context.Context, txn *kv.Txn) error {
+			descs, err := catalogkv.GetAllDescriptors(ctx, txn, keys.SystemSQLCodec)
```
Comment (postamar) [inline pkg/migration/migrations/fix_privileges_migration_external_test.go:173]: Seeing as `GetAllDescriptors` will validate those descriptors which will in turn validate the privilege descriptors, aren't some of the checks below redundant? I'm pretty sure the calls to `privilegeDesc.Validate` are. Speaking of which, shouldn't some checks be added to that method, perhaps version-gated behind `privilegeDesc.Version`?

File: pkg/testutils/sqlutils/inject.go [hunk 6]
```diff
@@ -24,7 +24,10 @@ import (
 
 // InjectDescriptors attempts to inject the provided descriptors into the
 // database.
-func InjectDescriptors(ctx context.Context, db *gosql.DB, input []*descpb.Descriptor) error {
+// If force is true, we can inject descriptors that are invalid.
+func InjectDescriptors(
+	ctx context.Context, db *gosql.DB, input []*descpb.Descriptor, force bool,
```
Comment (postamar) [inline pkg/testutils/sqlutils/inject.go:29]: nit: can you sprinkle `/* force */` comments everywhere you call `InjectDescriptors` with a boolean literal as argument, please?

**Review by postamar — CHANGES_REQUESTED** [review]
I have a few comments but I'd like Andrew to take a look at this as well at some point, just to make sure. I'm paranoid about migrations.

Somewhat related and I might be wrong, but the backup case could perhaps be handled by adding a new upgrade step to the`RunPostDeserializationChanges` method of `catalog.DescriptorBuilder`, in which case it'd be appropriate to include in this PR.

**Review by rafiss — CHANGES_REQUESTED** [review]
nit: for the release note, i think we can make it something a bit more user-focused. It can just focus on what the end-user would notice, and the other details can stay just in the commit message.

Release note (bug fix): An internal upgrade was added that runs when a cluster is upgraded to v21.2, and which fixes the representation of database object privileges. This fixes a potential source of corruption that could leave the database in an unusable state.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/66495#-:-McNq1iVC0cXTii1v9lv:b-egv1m1)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner and @RichardJCai)

___
*[pkg/migration/migrations/fix_privileges_migration.go, line 84 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/66495#-McNrgWu32l_Ma9I_LYc:-McNrgWu32l_Ma9I_LYd:b-pmnb35) ([raw file](https://github.com/cockroachdb/cockroach/blob/97721126ab3e55b50d15f231d0fcacab274974fb/pkg/migration/migrations/fix_privileges_migration.go#L84)):*
> ```Go
> 
> 		if privilegeDesc.Version >= descpb.Version21_2 {
> 			log.Infof(ctx, "privilege descriptor has already been fixed, skipping %d", upgrade)
> ```

nit: will this get logged every time a node starts? maybe we'd want to be less verbose.
___
*[pkg/migration/migrations/fix_privileges_migration_external_test.go, line 36 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/66495#-McNtEgT-t30thqVFWdk:-McNtEgU2SWALZXEU7G_:b24ukk3) ([raw file](https://github.com/cockroachdb/cockroach/blob/97721126ab3e55b50d15f231d0fcacab274974fb/pkg/migration/migrations/fix_privileges_migration_external_test.go#L36)):*
> ```Go
> )
> 
> func TestFixPrivilegesMigration(t *testing.T) {
> ```

cool tests! nit on adjusting the whtiespace for the sql queries in the comments.

**Review by ajwerner — COMMENTED** [review]
> Reviewed 4 of 14 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/66495)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @RichardJCai)

___
*[pkg/migration/migrations/fix_privileges_migration.go, line 37 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/66495#-McPEbKH5EZEuEdEy-NE:-McPEbKH5EZEuEdEy-NF:bdkr64) ([raw file](https://github.com/cockroachdb/cockroach/blob/97721126ab3e55b50d15f231d0fcacab274974fb/pkg/migration/migrations/fix_privileges_migration.go#L37)):*
> ```Go
> 	var lastUpgradedID descpb.ID
> 	for {
> 		done, idToUpgrade, objectType, err := findNextDescriptorToFix(ctx, d.InternalExecutor, lastUpgradedID)
> ```

I find the control flow here to be surprising. It's mostly weird because we're scanning the descriptors table, decoding the thing, then throwing that away, getting it by ID etc. 

Instead, what if we just literally scanned the descriptor table and then did the modification in place. I think it would simplify the code a bunch. You can still use descs.Txn to do the writing. `catalogkv.NewBuilderWithMVCCTimestamp(&desc, ts)` is your friend. Lastly, I think you'll benefit greatly from marking a bit if you did a repair -- I think you can avoid all of the specialized logic that occurs on a per-type basis, keeping all of the complexity in the builder.

**Review by RichardJCai — COMMENTED** [review]
Updated, did too much cargo culting previously. Reworked so all descriptors are upgraded in one transaction and refactored a bunch of logic including some of the old MaybeFixPrivilege logic, we can hopefully remove it after 21.2

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/66495#-:-McPRSlpEmUuOMBYRdlc:b-2xguup)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @postamar, and @rafiss)

___
*[pkg/migration/migrations/fix_privileges_migration.go, line 37 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/66495#-McPEbKH5EZEuEdEy-NE:-McjpmiM6nvryHflYuUv:b-6l73p0) ([raw file](https://github.com/cockroachdb/cockroach/blob/97721126ab3e55b50d15f231d0fcacab274974fb/pkg/migration/migrations/fix_privileges_migration.go#L37)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

I find the control flow here to be surprising. It's mostly weird because we're scanning the descriptors table, decoding the thing, then throwing that away, getting it by ID etc. 

Instead, what if we just literally scanned the descriptor table and then did the modification in place. I think it would simplify the code a bunch. You can still use descs.Txn to do the writing. `catalogkv.NewBuilderWithMVCCTimestamp(&desc, ts)` is your friend. Lastly, I think you'll benefit greatly from marking a bit if you did a repair -- I think you can avoid all of the specialized logic that occurs on a per-type basis, keeping all of the complexity in the builder. 
</blockquote></details>

Agreed, too much cargo culting. I've changed a lot here.

Also, I think the Version field is akin to the bit for a repair (it determines whether we need to repair or not as descriptors created with version 21.2 are guaranteed to not have these issues)
___
*[pkg/migration/migrations/fix_privileges_migration.go, line 50 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/66495#-McG4wGMOfuRKhHovdKC-r1-50:-McjpXpL3RpE3sGsCuGH:b-xue6v9) ([raw file](https://github.com/cockroachdb/cockroach/blob/97721126ab3e55b50d15f231d0fcacab274974fb/pkg/migration/migrations/fix_privileges_migration.go#L50)):*
<details><summary><i>Previously, postamar (Marius Posta) wrote…</i></summary><blockquote>

This might be out of scope but would it be possible to also apply `descpb.MaybeFixPrivileges` and perhaps `descpb.MaybeFixUsagePrivForTablesAndDBs` in this migration instead of having to rely solely on the `RunPostDeserializationChanges` method of `catalog.DescriptorBuilder` for this purpose? 
</blockquote></details>

Done (I believe). Changed it so `MaybeFixPrivileges` is used in this migration.
___
*[pkg/migration/migrations/fix_privileges_migration.go, line 81 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/66495#-McG4wGMOfuRKhHovdKC-r1-81:-McjpWAw3tCGbcB6OG8c:b2nhjff) ([raw file](https://github.com/cockroachdb/cockroach/blob/97721126ab3e55b50d15f231d0fcacab274974fb/pkg/migration/migrations/fix_privileges_migration.go#L81)):*
<details><summary><i>Previously, postamar (Marius Posta) wrote…</i></summary><blockquote>

`desc, err := descriptors.GetMutableDescriptorByID(...)`?
</blockquote></details>

N/A
___
*[pkg/migration/migrations/fix_privileges_migration.go, line 84 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/66495#-McNrgWu32l_Ma9I_LYc:-McjpiMN7OPUo3o-HBEJ:b-nn4y5m) ([raw file](https://github.com/cockroachdb/cockroach/blob/97721126ab3e55b50d15f231d0fcacab274974fb/pkg/migration/migrations/fix_privileges_migration.go#L84)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

nit: will this get logged every time a node starts? maybe we'd want to be less verbose.
</blockquote></details>

Should only be called once for each ID during the migration, not during node start.
___
*[pkg/migration/migrations/fix_privileges_migration.go, line 102 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/66495#-McG4wGMOfuRKhHovdKC-r1-102:-McjpX7W8FI8NEiVZhHf:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/97721126ab3e55b50d15f231d0fcacab274974fb/pkg/migration/migrations/fix_privileges_migration.go#L102)):*
<details><summary><i>Previously, postamar (Marius Posta) wrote…</i></summary><blockquote>

I allude to this in another comment but wouldn't having one transaction per descriptor be wasteful?
</blockquote></details>

Done.
___
*[pkg/migration/migrations/fix_privileges_migration.go, line 131 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/66495#-McG4wGMOfuRKhHovdKC-r1-131:-McjpRaODTGPo8DcghEV:b-pdndra) ([raw file](https://github.com/cockroachdb/cockroach/blob/97721126ab3e55b50d15f231d0fcacab274974fb/pkg/migration/migrations/fix_privileges_migration.go#L131)):*
<details><summary><i>Previously, postamar (Marius Posta) wrote…</i></summary><blockquote>

Have you considered calling `catalogkv.NewBuilderWithMVCCTimestamp(&desc, ts)` instead and building a `catalog.Descriptor` instance?

Not only would this simplify your code by removing a lot of switch cases and added `descpb` methods but you'd be able to apply the changes in `fixPrivileges` in the same transaction, which would be preferable.

Alternatively, couldn't this whole `findNextDescriptorToFix` be expressed as one big SQL query? That would also be preferable. I'm not sure you actually need to return `objectType`.
</blockquote></details>

Done, changed it to "one big SQL query" or rather have all the descriptors updated in one txn
___
*[pkg/migration/migrations/fix_privileges_migration_external_test.go, line 36 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/66495#-McNtEgT-t30thqVFWdk:-Mcjq3Lf0bSVdq-91G9g:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/97721126ab3e55b50d15f231d0fcacab274974fb/pkg/migration/migrations/fix_privileges_migration_external_test.go#L36)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

cool tests! nit on adjusting the whtiespace for the sql queries in the comments.
</blockquote></details>

Done.
___
*[pkg/migration/migrations/fix_privileges_migration_external_test.go, line 64 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/66495#-McG4wGMOfuRKhHovdKD-r1-64:-McjpyViE-_A_m25NSDY:b6h3ulr) ([raw file](https://github.com/cockroachdb/cockroach/blob/97721126ab3e55b50d15f231d0fcacab274974fb/pkg/migration/migrations/fix_privileges_migration_external_test.go#L64)):*
<details><summary><i>Previously, postamar (Marius Posta) wrote…</i></summary><blockquote>

The formatting here is all weird (in github at least), is this expected?
</blockquote></details>

Should be fixed.
___
*[pkg/migration/migrations/fix_privileges_migration_external_test.go, line 173 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/66495#-McG4wGMOfuRKhHovdKD-r1-173:-Mcjpzf646wiaB3Zw6RK:bnwzr8z) ([raw file](https://github.com/cockroachdb/cockroach/blob/97721126ab3e55b50d15f231d0fcacab274974fb/pkg/migration/migrations/fix_privileges_migration_external_test.go#L173)):*
<details><summary><i>Previously, postamar (Marius Posta) wrote…</i></summary><blockquote>

Seeing as `GetAllDescriptors` will validate those descriptors which will in turn validate the privilege descriptors, aren't some of the checks below redundant? I'm pretty sure the calls to `privilegeDesc.Validate` are. Speaking of which, shouldn't some checks be added to that method, perhaps version-gated behind `privilegeDesc.Version`?
</blockquote></details>

Done, and slightly updated `Validate`.

**Review by ajwerner — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/66495)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @postamar, @rafiss, and @RichardJCai)

___
*[pkg/migration/migrations/fix_privileges_migration.go, line 43 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/66495#-MclAsRe6tNjhSVqbMmo:-MclAsRe6tNjhSVqbMmp:b-yy3rcz) ([raw file](https://github.com/cockroachdb/cockroach/blob/333a7fae79f0d88c58a49da0b1b0f2904b0d8383/pkg/migration/migrations/fix_privileges_migration.go#L43)):*
> ```Go
> 	for ; ok; ok, err = rows.Next(ctx) {
> 		row := rows.Cur()
> 		id := descpb.ID(*row[0].(*tree.DInt))
> ```

nit: refactor the row parsing into a helper.

I think with the various helpers, this should read:

```
ok, err := rows.Next(ctx)
for ; ok, ok, err = rows.Next(ctx) {
    desc, err := decodeRow(ctx, row)
    if err != nil {
        return err // wrap the error in decodeRow with which row
    }
    if desc.GetPrivileges.Version > descpb.Version21_2 {
        continue
    }
    if err := upgradePrivileges(ctx, desc.GetID()); err != nil {
        return err
    }
}
```
___
*[pkg/migration/migrations/fix_privileges_migration.go, line 72 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/66495#-MclATTCAFrAQMdgy995:-MclATTCAFrAQMdgy996:b5fp9iq) ([raw file](https://github.com/cockroachdb/cockroach/blob/333a7fae79f0d88c58a49da0b1b0f2904b0d8383/pkg/migration/migrations/fix_privileges_migration.go#L72)):*
<details><summary><i alt="summary">Quoted 11 lines of code…</i></summary>

> ```
> 
> 		switch b.DescriptorType() {
> 		case catalog.Database:
> 			objectType = privilege.Database
> 		case catalog.Schema:
> 			objectType = privilege.Schema
> 		case catalog.Table:
> 			objectType = privilege.Table
> 		case catalog.Type:
> 			objectType = privilege.Type
> 		}
> ```
</details>

nit: factor this out into a helper.
___
*[pkg/migration/migrations/fix_privileges_migration.go, line 76 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/66495#-MclAmoj1fKXfT7suHyg:-MclAmoj1fKXfT7suHyh:b-tjaslj) ([raw file](https://github.com/cockroachdb/cockroach/blob/333a7fae79f0d88c58a49da0b1b0f2904b0d8383/pkg/migration/migrations/fix_privileges_migration.go#L76)):*
> ```Go
> 		err = descs.Txn(ctx, d.Settings, d.LeaseManager, d.InternalExecutor, d.DB, func(
> 			ctx context.Context, txn *kv.Txn, descriptors *descs.Collection) error {
> 			if privilegeDesc.Version >= descpb.Version21_2 {
> ```

why do this down here? I think it'd be better if you did this check above with a continue. 
___
*[pkg/migration/migrations/fix_privileges_migration.go, line 85 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/66495#-MclAWQ_4gXkCcTIL96Z:-MclAWQ_4gXkCcTIL96_:b-3uya7i) ([raw file](https://github.com/cockroachdb/cockroach/blob/333a7fae79f0d88c58a49da0b1b0f2904b0d8383/pkg/migration/migrations/fix_privileges_migration.go#L85)):*
<details><summary><i alt="summary">Quoted 13 lines of code…</i></summary>

> ```
> 		err = descs.Txn(ctx, d.Settings, d.LeaseManager, d.InternalExecutor, d.DB, func(
> 			ctx context.Context, txn *kv.Txn, descriptors *descs.Collection) error {
> 			if privilegeDesc.Version >= descpb.Version21_2 {
> 				log.Infof(ctx, "privilege descriptor has already been fixed, skipping %d", id)
> 				return nil
> 			}
> 			privs := mutableDesc.GetPrivileges()
> 			descpb.MaybeFixPrivileges(
> 				mutableDesc.GetID(), mutableDesc.GetParentID(),
> 				&privs, objectType,
> 			)
> 			return descriptors.WriteDesc(ctx, false /* kvTrace */, mutableDesc, txn)
> 		})
> ```
</details>

nit: factor this out into a helper

**Review by RichardJCai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/66495)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @postamar, and @rafiss)

___
*[pkg/migration/migrations/fix_privileges_migration.go, line 76 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/66495#-MclAmoj1fKXfT7suHyg:-McoEdhL-N6xWfLT5W9E:bb6un1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/333a7fae79f0d88c58a49da0b1b0f2904b0d8383/pkg/migration/migrations/fix_privileges_migration.go#L76)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

why do this down here? I think it'd be better if you did this check above with a continue. 
</blockquote></details>

Done

**Comment by RichardJCai** [comment]
> Somewhat related and I might be wrong, but the backup case could perhaps be handled by adding a new upgrade step to the`RunPostDeserializationChanges` method of `catalog.DescriptorBuilder`, in which case it'd be appropriate to include in this PR.

I added a call to `MaybeFixPrivileges` in `RunPostDeserializationChanges` for all objects which guarantees that restores will catch it too. My question here is when can we remove this? We'll have to keep it here until we have an API that allows us to sync migrations and restores.

File: pkg/migration/migrations/fix_privileges_migration.go [hunk 7]
```diff
@@ -0,0 +1,122 @@
...
+		}
+		if desc.GetPrivileges().Version >= descpb.Version21_2 {
+			log.Infof(ctx, "privilege descriptor has already been fixed, skipping %d", desc.GetID())
+			continue
+		}
+		if err := upgradePrivileges(ctx, desc, d); err != nil {
+			return err
+		}
+	}
+	if err != nil {
```
Comment (ajwerner) [inline pkg/migration/migrations/fix_privileges_migration.go:118]: nit: this whole thing can be return err

File: pkg/migration/migrations/fix_privileges_migration.go [hunk 8]
```diff
@@ -0,0 +1,122 @@
...
+		descpb.MaybeFixPrivileges(
+			desc.GetID(), desc.GetParentID(),
+			&privs, objectType,
+		)
+
+		return descriptors.WriteDesc(ctx, false /* kvTrace */, desc, txn)
+	})
+}
+
+// fixPrivilegesMigration calls descpb.MaybeFixPrivileges on every PrivilegeDescriptor
```
Comment (ajwerner) [inline pkg/migration/migrations/fix_privileges_migration.go:90]: extreme nit: I'd put this function first. It's nice to see the main driver at the top and scroll down to unpack the helpers.

File: pkg/sql/catalog/descpb/structured.go [hunk 9]
```diff
@@ -388,3 +388,18 @@ func (ni NameInfo) GetParentSchemaID() ID {
 func (ni NameInfo) GetName() string {
 	return ni.Name
 }
+
+// Dropped returns true if the database is being dropped.
+func (s *SchemaDescriptor) Dropped() bool {
```
Comment (ajwerner) [inline pkg/sql/catalog/descpb/structured.go:393]: What are these about?

**Review by RichardJCai — COMMENTED** [review]
General comment for @ajwerner @postamar 
Now that this was added in https://github.com/cockroachdb/cockroach/pull/66599

This migration fails due to a validation error since we're injecting old descriptors with an older Primary Key version
`pq: internal error: running migration for 21.1-14: relation "tb" (60): primary index "primary" has invalid version 0, expected 4`

The Validation fails on `fix_privileges_migration.go line 117` `return descriptors.WriteDesc(ctx, false /* kvTrace */, desc, txn)`
Since RunPostDeserialzation doesn't happen during the migration.

Does it make sense to add this fix into the migration as well?
```	
changes.UpgradedIndexFormatVersion = maybeUpgradePrimaryIndexFormatVersion(desc)
	for i := range desc.Indexes {
		changes.UpgradedIndexFormatVersion = changes.UpgradedIndexFormatVersion || maybeUpgradeSecondaryIndexFormatVersion(&desc.Indexes[i])
	}
	for i := range desc.Mutations {
		if idx := desc.Mutations[i].GetIndex(); idx != nil {
			changes.UpgradedIndexFormatVersion = changes.UpgradedIndexFormatVersion || maybeUpgradeSecondaryIndexFormatVersion(idx)
		}
	}
```

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/66495#-:-MctbRSN2m1Cdz8ZArQS:bzc4144)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @postamar, @rafiss, and @RichardJCai)

___
*[pkg/migration/migrations/fix_privileges_migration.go, line 90 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/66495#-McG4wGMOfuRKhHovdKC-r3-90:-MctYYTe4ZcQfvI_zPgN:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/3fc4b38658e726b1849bb669b2310ee7811b2529/pkg/migration/migrations/fix_privileges_migration.go#L90)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

extreme nit: I'd put this function first. It's nice to see the main driver at the top and scroll down to unpack the helpers. 
</blockquote></details>

Done.
___
*[pkg/sql/doctor/doctor_test.go, line 294 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/66495#-Mctb9Yv13h2ZpO0o2J4:-Mctb9Yv13h2ZpO0o2J5:bjjnxi2) ([raw file](https://github.com/cockroachdb/cockroach/blob/3fc4b38658e726b1849bb669b2310ee7811b2529/pkg/sql/doctor/doctor_test.go#L294)):*
<details><summary><i alt="summary">Quoted 12 lines of code…</i></summary>

> ```
> 						// Skip `toBytes` to produce a descriptor with unset privileges field.
> 						// The purpose of this is to produce a nil dereference during validation
> 						// in order to test that doctor recovers from this.
> 						//
> 						// Note that it might be the case that validation aught to check that
> 						// this field is not nil in the first place, in which case this test case
> 						// will need to craft a corrupt descriptor serialization in a more
> 						// creative way. Ideally validation code should never cause runtime errors
> 						// but there's no way to guarantee that short of formally verifying it. We
> 						// therefore have to consider the possibility of runtime errors (sadly) and
> 						// doctor should absolutely make every possible effort to continue executing
> 						// in the face of these, considering its main use case!
> ```
</details>


Had to update this test case, since `MaybeFixPrivileges` is called in `RunPostDeserializationChanges` for types now, this no longer produces a nil dereference. I can't think of a way to do this off the top of my head, any suggestions?
___
*[pkg/sql/catalog/descpb/structured.go, line 393 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/66495#-McG4wGL5WgwvPRmt3H--r3-393:-MctY_VIBwnwD8VxQ2nJ:b-sk66fc) ([raw file](https://github.com/cockroachdb/cockroach/blob/3fc4b38658e726b1849bb669b2310ee7811b2529/pkg/sql/catalog/descpb/structured.go#L393)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

What are these about?
</blockquote></details>

Removed, thought I needed this before but stopped using it.

**Review by ajwerner — COMMENTED** [review]
> Reviewed 5 of 30 files at r5.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/66495)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @nihalpednekar, @postamar, @rafiss, and @RichardJCai)

___
*[pkg/migration/migrations/fix_descriptor_migration.go, line 83 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/66495#-MdI3gOi7RZ600ASrB2l:-MdI3gOi7RZ600ASrB2m:btto2p5) ([raw file](https://github.com/cockroachdb/cockroach/blob/667e0048db0fb5f101c000cca181d2f1f2715495/pkg/migration/migrations/fix_descriptor_migration.go#L83)):*
> ```Go
> }
> 
> func runPostDeserializationChanges(
> ```

1) This could have a better name.
2) This is not transactionally safe -- you need to re-read the descriptor in the transaction. Otherwise you risk overwriting a change that happened between the scan and now.

**Review by RichardJCai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/66495)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @nihalpednekar, @postamar, and @rafiss)

___
*[pkg/migration/migrations/fix_descriptor_migration.go, line 83 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/66495#-MdI3gOi7RZ600ASrB2l:-MdJ9Hn15sFx3UAq84YI:b-prn102) ([raw file](https://github.com/cockroachdb/cockroach/blob/667e0048db0fb5f101c000cca181d2f1f2715495/pkg/migration/migrations/fix_descriptor_migration.go#L83)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

1) This could have a better name.
2) This is not transactionally safe -- you need to re-read the descriptor in the transaction. Otherwise you risk overwriting a change that happened between the scan and now.  
</blockquote></details>

1. Changed to just `fixDescriptor`
2. Oops, fixed.

**Review by ajwerner — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/66495)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @nihalpednekar, @postamar, @rafiss, and @RichardJCai)

___
*[pkg/sql/catalog/descpb/structured.proto, line 1195 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/66495#-MdJAp9hAn07kaZmL_ET:-MdJAp9hAn07kaZmL_EU:b-6ywonk) ([raw file](https://github.com/cockroachdb/cockroach/blob/cfb16b6bc180b1cb195ba0d627466dce01305006/pkg/sql/catalog/descpb/structured.proto#L1195)):*
> ```
>   // IsRepaired is set if the descriptor has been upgrade through fix_descriptor_migration.
>   optional bool is_repaired = 47 [(gogoproto.nullable)=false];
> ```

I'm skeptical of this field. Can you help me understand why we want or need it? Even if you wanted to track whether the post-deserialization changes did anything, you should do that in the in-memory object only. My preference is that you track whether you did anything on the builder object. 
___
*[pkg/migration/migrations/fix_descriptor_migration.go, line 83 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/66495#-MdI3gOi7RZ600ASrB2l:-MdJ9nbe7YtTDn4efBMN:b4nlrj7) ([raw file](https://github.com/cockroachdb/cockroach/blob/667e0048db0fb5f101c000cca181d2f1f2715495/pkg/migration/migrations/fix_descriptor_migration.go#L83)):*
<details><summary><i>Previously, RichardJCai (Richard Cai) wrote…</i></summary><blockquote>

1. Changed to just `fixDescriptor`
2. Oops, fixed.
</blockquote></details>

At this point it's clearer if you just pass the ID and version at which you knew it needed to be repaired rather than the mutable descriptor itself. 
___
*[pkg/migration/migrations/fix_descriptor_migration.go, line 90 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/66495#-MdJ9w9dCT1ZPIqveu9J:-MdJ9w9dCT1ZPIqveu9K:bix8z9i) ([raw file](https://github.com/cockroachdb/cockroach/blob/cfb16b6bc180b1cb195ba0d627466dce01305006/pkg/migration/migrations/fix_descriptor_migration.go#L90)):*
<details><summary><i alt="summary">Quoted 9 lines of code…</i></summary>

> ```
> 		datums, err := d.InternalExecutor.QueryRow(ctx, "fix-descriptor-migration", txn,
> 			`SELECT id, descriptor, crdb_internal_mvcc_timestamp FROM system.descriptor WHERE id = $1`, desc.GetID())
> 		if err != nil {
> 			return err
> 		}
> 		desc, err := getMutableDescFromDescriptorRow(datums)
> 		if err != nil {
> 			return err
> 		}
> ```
</details>

I'd prefer if you did: 

```
// Will do the upgrades.
desc, err := descriptors.GetMutableDescriptorByID(...)
if err != nil { /* ... */ }
if desc.GetVersion() > badVersion {
    // Already rewritten.
   return nil
}
// WriteDesc increments the version.
return descriptors.WriteDesc(...)
```

**Review by RichardJCai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/66495)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @nihalpednekar, @postamar, @rafiss, and @RichardJCai)

___
*[pkg/migration/migrations/fix_descriptor_migration.go, line 90 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/66495#-MdJ9w9dCT1ZPIqveu9J:-MdJWa3fEFG2q6eT7i_k:b-y5lmsd) ([raw file](https://github.com/cockroachdb/cockroach/blob/cfb16b6bc180b1cb195ba0d627466dce01305006/pkg/migration/migrations/fix_descriptor_migration.go#L90)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

> ```
> 		datums, err := d.InternalExecutor.QueryRow(ctx, "fix-descriptor-migration", txn,
> 			`SELECT id, descriptor, crdb_internal_mvcc_timestamp FROM system.descriptor WHERE id = $1`, desc.GetID())
> 		if err != nil {
> 			return err
> 		}
> 		desc, err := getMutableDescFromDescriptorRow(datums)
> 		if err != nil {
> 			return err
> 		}
> ```
I'd prefer if you did: 

```
// Will do the upgrades.
desc, err := descriptors.GetMutableDescriptorByID(...)
if err != nil { /* ... */ }
if desc.GetVersion() > badVersion {
    // Already rewritten.
   return nil
}
// WriteDesc increments the version.
return descriptors.WriteDesc(...)
```
</blockquote></details>

I don't think we actually have a "badVersion" here right now. `desc.GetVersion()` `DescriptorVersion` is just sequential numbers. 

We can add another "DescriptorTypeVersion" or something along those lines. I can't think of a great name here. Or we could rename the current `DescriptorVersion` to `DescriptorLeaseVersion`, I think that should work as well.

**Review by ajwerner — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/66495)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @nihalpednekar, @postamar, @rafiss, and @RichardJCai)

___
*[pkg/migration/migrations/fix_descriptor_migration.go, line 90 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/66495#-MdJ9w9dCT1ZPIqveu9J:-MdJ_ZvF7Nft2PTe67Zs:b-eyb7rt) ([raw file](https://github.com/cockroachdb/cockroach/blob/cfb16b6bc180b1cb195ba0d627466dce01305006/pkg/migration/migrations/fix_descriptor_migration.go#L90)):*
>DescriptorVersion is just sequential numbers.

Exactly! We know that if the version we read from the store is the same as the version we read from the scan then we know that nobody has rewritten it since and thus we need to do a repair. If the version is higher than the one we have from the store, it means that the version has changed. Given all nodes of this version do the repair, we know that any new version must be repaired.

**Review by RichardJCai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/66495)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @nihalpednekar, @postamar, and @rafiss)

___
*[pkg/migration/migrations/fix_descriptor_migration.go, line 90 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/66495#-MdJ9w9dCT1ZPIqveu9J:-MdJfTYJ8jyFdjR1PIxN:bkmp77o) ([raw file](https://github.com/cockroachdb/cockroach/blob/cfb16b6bc180b1cb195ba0d627466dce01305006/pkg/migration/migrations/fix_descriptor_migration.go#L90)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

>DescriptorVersion is just sequential numbers.

Exactly! We know that if the version we read from the store is the same as the version we read from the scan then we know that nobody has rewritten it since and thus we need to do a repair. If the version is higher than the one we have from the store, it means that the version has changed. Given all nodes of this version do the repair, we know that any new version must be repaired. 
</blockquote></details>

Oh shoot okay I get it now, that's smart. Nice.

**Review by RichardJCai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/66495)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @nihalpednekar, @postamar, and @rafiss)

___
*[pkg/migration/migrations/fix_descriptor_migration.go, line 97 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/66495#-MdJhSr9Dxp3nr08SCU0:-MdJhSr9Dxp3nr08SCU1:b-seqsgb) ([raw file](https://github.com/cockroachdb/cockroach/blob/acafc44ac63b97620504c55f75a0d7876e599b3f/pkg/migration/migrations/fix_descriptor_migration.go#L97)):*
> ```Go
> 		}
> 		log.Infof(ctx, "upgrading descriptor with id %d", desc.GetID())
> 		return descriptors.WriteDesc(ctx, false /* kvTrace */, desc, txn)
> ```

Needa make one more change to check if anything changed or not before writing desc.

**Review by ajwerner — COMMENTED** [review]
Very close. Thanks for fighting toughing it through all of these revisions. 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/66495#-:-MdKYIAp32K0idWhmzR-:bop6zun)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @nihalpednekar, @postamar, @rafiss, and @RichardJCai)

___
*[pkg/migration/migrations/fix_descriptor_migration.go, line 97 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/66495#-MdJhSr9Dxp3nr08SCU0:-MdKYBatBVjmMS08jKkZ:b-1286xh) ([raw file](https://github.com/cockroachdb/cockroach/blob/acafc44ac63b97620504c55f75a0d7876e599b3f/pkg/migration/migrations/fix_descriptor_migration.go#L97)):*
<details><summary><i>Previously, RichardJCai (Richard Cai) wrote…</i></summary><blockquote>

Needa make one more change to check if anything changed or not before writing desc.
</blockquote></details>

Can't we make that check above?
___
*[pkg/migration/migrations/fix_descriptor_migration.go, line 46 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/66495#-MdKY-GI7VnGtvJS3XAv:-MdKY-GI7VnGtvJS3XAw:b-qthbod) ([raw file](https://github.com/cockroachdb/cockroach/blob/868b9f246bd7da8caf1f495ddbe72077edc82204/pkg/migration/migrations/fix_descriptor_migration.go#L46)):*
> ```Go
> 		if err != nil {
> 			return err
> 		}
> ```

Now check here whether we actually need to do the fix. Unless I'm mistaken, not that many descriptors are actually going to need to be touched. 
___
*[pkg/migration/migrations/fix_descriptor_migration.go, line 82 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/66495#-MdKX92rEVlTabSbpKeU:-MdKX92s6CKs1yoCdkeH:b-hbimv) ([raw file](https://github.com/cockroachdb/cockroach/blob/868b9f246bd7da8caf1f495ddbe72077edc82204/pkg/migration/migrations/fix_descriptor_migration.go#L82)):*
> ```Go
> // by running RunPostDeserializationChanges.
> func fixDescriptor(
> 	ctx context.Context, id descpb.ID, d migration.TenantDeps, version descpb.DescriptorVersion,
> ```

super nit: switch the order of d and id in this method.

**Review by RichardJCai — COMMENTED** [review]
No worries, really appreciate the reviews and tight review cycles.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/66495#-:-MdNBbHOBLOzl756jdIO:b-u0ei70)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @nihalpednekar, @postamar, @rafiss, and @RichardJCai)

___
*[pkg/migration/migrations/fix_descriptor_migration.go, line 97 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/66495#-MdJhSr9Dxp3nr08SCU0:-MdNE5sO4KFVuY3viImx:b-pqq4jh) ([raw file](https://github.com/cockroachdb/cockroach/blob/acafc44ac63b97620504c55f75a0d7876e599b3f/pkg/migration/migrations/fix_descriptor_migration.go#L97)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

Can't we make that check above?
</blockquote></details>

`getMutableDescFromDescriptorRow` doesn't call `RunPostDeserializationChanges` so to do the check above, we'd have to call it there and `fixDescriptor` will call it again doubling the calls.
___
*[pkg/migration/migrations/fix_descriptor_migration.go, line 46 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/66495#-MdKY-GI7VnGtvJS3XAv:-MdNDM8l-lFIG-WHWyQQ:b5sza18) ([raw file](https://github.com/cockroachdb/cockroach/blob/868b9f246bd7da8caf1f495ddbe72077edc82204/pkg/migration/migrations/fix_descriptor_migration.go#L46)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

Now check here whether we actually need to do the fix. Unless I'm mistaken, not that many descriptors are actually going to need to be touched. 
</blockquote></details>

Right now it's set so every PrivilegeDescriptor created before 21.2 will be updated, so theoretically every descriptor will be changed.  The version field is only used for validation purposes. Should we remove this so we don't upgrade every descriptor.

```
	if p.Version < Version21_2 {
		p.SetVersion(Version21_2)
		changed = true
	}
```

**Review by ajwerner — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/66495)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @nihalpednekar, @postamar, @rafiss, and @RichardJCai)

___
*[pkg/migration/migrations/fix_descriptor_migration.go, line 97 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/66495#-MdJhSr9Dxp3nr08SCU0:-MdNVspQ0L_xlcXGLy_5:b-415m5n) ([raw file](https://github.com/cockroachdb/cockroach/blob/acafc44ac63b97620504c55f75a0d7876e599b3f/pkg/migration/migrations/fix_descriptor_migration.go#L97)):*
<details><summary><i>Previously, RichardJCai (Richard Cai) wrote…</i></summary><blockquote>

`getMutableDescFromDescriptorRow` doesn't call `RunPostDeserializationChanges` so to do the check above, we'd have to call it there and `fixDescriptor` will call it again doubling the calls.
</blockquote></details>

So what? Pass in a nil descgetter and it’s just an in-memory op.

**Review by RichardJCai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/66495)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @nihalpednekar, @postamar, and @rafiss)

___
*[pkg/migration/migrations/fix_descriptor_migration.go, line 97 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/66495#-MdJhSr9Dxp3nr08SCU0:-MdNdS1wBmrhMmh30Yg8:b-yoay9k) ([raw file](https://github.com/cockroachdb/cockroach/blob/acafc44ac63b97620504c55f75a0d7876e599b3f/pkg/migration/migrations/fix_descriptor_migration.go#L97)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

So what? Pass in a nil descgetter and it’s just an in-memory op. 
</blockquote></details>

Fair enough, don
___
*[pkg/migration/migrations/fix_descriptor_migration.go, line 82 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/66495#-MdKX92rEVlTabSbpKeU:-MdNdRYL4cK_k2c7h5tK:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/868b9f246bd7da8caf1f495ddbe72077edc82204/pkg/migration/migrations/fix_descriptor_migration.go#L82)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

super nit: switch the order of d and id in this method. 
</blockquote></details>

Done.

**Review by ajwerner — COMMENTED** [review]
> Reviewed 1 of 14 files at r1, 1 of 13 files at r4, 3 of 10 files at r6, 2 of 17 files at r8.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/66495)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @nihalpednekar, @postamar, @rafiss, and @RichardJCai)

___
*[pkg/sql/catalog/catalog.go, line 49 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/66495#-MdODsng26pNy-NgqBa6:-MdODsnh0OM_0ykusFoH:b-tn300g) ([raw file](https://github.com/cockroachdb/cockroach/blob/92ad363395959cfa178af68e22097bdef956fb1c/pkg/sql/catalog/catalog.go#L49)):*
> ```Go
> 	// GetChanged returns if the MutableDescriptor was changed after running
> 	// RunPostDeserializationChanges.
> 	GetChanged() bool
> ```

Can we call this something more descriptive. `HasPostDeserializationChanges`? Also, I was envisioning this method living on the builder rather than the descriptor, but this is fine. 
___
*[pkg/migration/migrations/fix_descriptor_migration.go, line 46 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/66495#-MdKY-GI7VnGtvJS3XAv:-MdOEZOCD9Iwws-EOc7p:bvzt8lj) ([raw file](https://github.com/cockroachdb/cockroach/blob/868b9f246bd7da8caf1f495ddbe72077edc82204/pkg/migration/migrations/fix_descriptor_migration.go#L46)):*
<details><summary><i>Previously, RichardJCai (Richard Cai) wrote…</i></summary><blockquote>

Right now it's set so every PrivilegeDescriptor created before 21.2 will be updated, so theoretically every descriptor will be changed.  The version field is only used for validation purposes. Should we remove this so we don't upgrade every descriptor.

```
	if p.Version < Version21_2 {
		p.SetVersion(Version21_2)
		changed = true
	}
```
</blockquote></details>

What does that version mean? Are we getting value out of setting it?

**Review by RichardJCai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/66495)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @nihalpednekar, @postamar, @rafiss, and @RichardJCai)

___
*[pkg/migration/migrations/fix_descriptor_migration.go, line 46 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/66495#-MdKY-GI7VnGtvJS3XAv:-MdOFVWDAFNYoFnEqpWQ:b-gpti3g) ([raw file](https://github.com/cockroachdb/cockroach/blob/868b9f246bd7da8caf1f495ddbe72077edc82204/pkg/migration/migrations/fix_descriptor_migration.go#L46)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

What does that version mean? Are we getting value out of setting it?
</blockquote></details>

The version means we can check the validate the privileges strictly.

Validate is prior to and during the migration, in which we have less strict checks.

```
	// Validate can be called during the fix_privileges_migration introduced in
	// 21.2. It is possible for have invalid privileges prior to 21.2 in certain
	// cases due to bugs. We can strictly check privileges in 21.2 and onwards.
	if p.Version < Version21_2 {
		if objectType == privilege.Schema {
			// Prior to 21_2, it was possible for a schema to have some database
			// privileges on it. This was temporarily fixed by an upgrade on read
			// but in 21.2 onwards, it should be permanently fixed with a migration.
			allowedPrivilegesBits |= privilege.GetValidPrivilegesForObject(privilege.Database).ToBitField()
		}
		if objectType == privilege.Table || objectType == privilege.Database {
			// Prior to 21_2, it was possible for a table or database to have USAGE
			// privilege on it due to a bug when upgrading from 20.1 to 20.2.
			// In 21.2 onwards, it should be permanently fixed with a migration.
			allowedPrivilegesBits |= privilege.USAGE.Mask()
		}
	}
```

**Review by ajwerner — COMMENTED** [review]
I do think that the code you're writing here is something we should find a way to package up for reuse. See how you feel about my batching suggestion. 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/66495#-:-MdQ-VOL8klJjFnIYqUX:b5baz89)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @nihalpednekar, @postamar, @rafiss, and @RichardJCai)

___
*[pkg/migration/migrations/fix_descriptor_migration.go, line 46 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/66495#-MdKY-GI7VnGtvJS3XAv:-MdQ-5Xb4LnPx6XMmKDK:b-j1nyjy) ([raw file](https://github.com/cockroachdb/cockroach/blob/868b9f246bd7da8caf1f495ddbe72077edc82204/pkg/migration/migrations/fix_descriptor_migration.go#L46)):*
<details><summary><i>Previously, RichardJCai (Richard Cai) wrote…</i></summary><blockquote>

The version means we can check the validate the privileges strictly.

Validate is prior to and during the migration, in which we have less strict checks.

```
	// Validate can be called during the fix_privileges_migration introduced in
	// 21.2. It is possible for have invalid privileges prior to 21.2 in certain
	// cases due to bugs. We can strictly check privileges in 21.2 and onwards.
	if p.Version < Version21_2 {
		if objectType == privilege.Schema {
			// Prior to 21_2, it was possible for a schema to have some database
			// privileges on it. This was temporarily fixed by an upgrade on read
			// but in 21.2 onwards, it should be permanently fixed with a migration.
			allowedPrivilegesBits |= privilege.GetValidPrivilegesForObject(privilege.Database).ToBitField()
		}
		if objectType == privilege.Table || objectType == privilege.Database {
			// Prior to 21_2, it was possible for a table or database to have USAGE
			// privilege on it due to a bug when upgrading from 20.1 to 20.2.
			// In 21.2 onwards, it should be permanently fixed with a migration.
			allowedPrivilegesBits |= privilege.USAGE.Mask()
		}
	}
```
</blockquote></details>

The fact that we're going to touch most descriptors makes me wonder if we should be accumulating a batch at a time (we probably should). What if we make a slice of `lease.IDVersion` and then pick some arbitrary batch size and go do the upgrade when the batch is full.

**Review by RichardJCai — COMMENTED** [review]
I'll try to pull out the descriptor getting / upgrade into a package.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/66495#-:-MdSEjX9AtO1H6rrFmKC:bcr03i6)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @nihalpednekar, @postamar, @rafiss, and @RichardJCai)

___
*[pkg/migration/migrations/fix_descriptor_migration.go, line 46 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/66495#-MdKY-GI7VnGtvJS3XAv:-MdSErjf0V_Fb5iSHz2N:bs0hcyg) ([raw file](https://github.com/cockroachdb/cockroach/blob/868b9f246bd7da8caf1f495ddbe72077edc82204/pkg/migration/migrations/fix_descriptor_migration.go#L46)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

The fact that we're going to touch most descriptors makes me wonder if we should be accumulating a batch at a time (we probably should). What if we make a slice of `lease.IDVersion` and then pick some arbitrary batch size and go do the upgrade when the batch is full. 
</blockquote></details>

Seems reasonable to me, do you have an idea of what is a good arbitrary batch size? 100?

**Review by ajwerner — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/66495)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @nihalpednekar, @postamar, @rafiss, and @RichardJCai)

___
*[pkg/migration/migrations/fix_descriptor_migration.go, line 46 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/66495#-MdKY-GI7VnGtvJS3XAv:-MdSFOOU8H0eyRTOVtUG:blebi5v) ([raw file](https://github.com/cockroachdb/cockroach/blob/868b9f246bd7da8caf1f495ddbe72077edc82204/pkg/migration/migrations/fix_descriptor_migration.go#L46)):*
<details><summary><i>Previously, RichardJCai (Richard Cai) wrote…</i></summary><blockquote>

Seems reasonable to me, do you have an idea of what is a good arbitrary batch size? 100?
</blockquote></details>

That seems like the right order of magnitude. What if we did it based on byte size rather than number of descriptors? `desc.DescriptorProto().Size()` should be a good proxy. I think 512 KiB would be a good batch size.

**Review by ajwerner — COMMENTED** [review]
> I'll try to pull out the descriptor getting / upgrade into a package.

I think it's fine for it to be in the migrations package. Just think about some minor abstracting. We can further abstract it later. 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/66495#-:-MdSFmwnAjf3xfg5VFT7:b4405fu)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @nihalpednekar, @postamar, @rafiss, and @RichardJCai)

**Review by RichardJCai — COMMENTED** [review]
Added an abstraction for migrations that will go over all descriptors and fix them.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/66495#-:-MdT2eka4jdyhcWf_Lot:bvur21q)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @nihalpednekar, @postamar, and @rafiss)

___
*[pkg/sql/catalog/catalog.go, line 49 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/66495#-MdODsng26pNy-NgqBa6:-MdT34OPBF2kQjJ2_NrA:bb6un1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/92ad363395959cfa178af68e22097bdef956fb1c/pkg/sql/catalog/catalog.go#L49)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

Can we call this something more descriptive. `HasPostDeserializationChanges`? Also, I was envisioning this method living on the builder rather than the descriptor, but this is fine. 
</blockquote></details>

Done
___
*[pkg/migration/migrations/fix_descriptor_migration.go, line 46 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/66495#-MdKY-GI7VnGtvJS3XAv:-MdT2bSQ9E1yZ6Pfbm29:b-g16bu5) ([raw file](https://github.com/cockroachdb/cockroach/blob/868b9f246bd7da8caf1f495ddbe72077edc82204/pkg/migration/migrations/fix_descriptor_migration.go#L46)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

That seems like the right order of magnitude. What if we did it based on byte size rather than number of descriptors? `desc.DescriptorProto().Size()` should be a good proxy. I think 512 KiB would be a good batch size. 
</blockquote></details>

Done I used 512 KiB as a batch size.

**Review by ajwerner — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/66495)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @nihalpednekar, @postamar, @rafiss, and @RichardJCai)

___
*[pkg/migration/migrations/fix_descriptor_migration.go, line 65 at r13](https://reviewable.io/reviews/cockroachdb/cockroach/66495#-MdT4hkUBaCbLjLwuV35:-MdT4hkUBaCbLjLwuV36:bwzi5gs) ([raw file](https://github.com/cockroachdb/cockroach/blob/275028f0a068f0d098061faf888a84a6a2d0d888/pkg/migration/migrations/fix_descriptor_migration.go#L65)):*
> ```Go
> 	}
> 
> 	return descriptorUpgradeMigration(ctx, rows, fixDescriptorFunc, 524288 /* batchSizeInBytes */)
> ```

`1<<19 /* 512 KiB batch size */`? 
___
*[pkg/migration/migrations/fix_descriptor_migration.go, line 73 at r13](https://reviewable.io/reviews/cockroachdb/cockroach/66495#-MdT57KX75AwRrQcZ6m1:-MdT57KX75AwRrQcZ6m2:b-go7n1u) ([raw file](https://github.com/cockroachdb/cockroach/blob/275028f0a068f0d098061faf888a84a6a2d0d888/pkg/migration/migrations/fix_descriptor_migration.go#L73)):*
> ```Go
> 	ctx context.Context, d migration.TenantDeps, id descpb.ID, version descpb.DescriptorVersion,
> ) error {
> 	return descs.Txn(ctx, d.Settings, d.LeaseManager, d.InternalExecutor, d.DB, func(
> ```

The point of the batching is to batch the writes into a single write batch. Use `descriptors.WriteDescToBatch`
___
*[pkg/migration/migrations/fix_descriptor_migration.go, line 85 at r13](https://reviewable.io/reviews/cockroachdb/cockroach/66495#-MdT4y1m9EB2ciDOuelN:-MdT4y1m9EB2ciDOuelO:br6d7c8) ([raw file](https://github.com/cockroachdb/cockroach/blob/275028f0a068f0d098061faf888a84a6a2d0d888/pkg/migration/migrations/fix_descriptor_migration.go#L85)):*
> ```Go
> 			return nil
> 		}
> 		log.Infof(ctx, "upgrading descriptor with id %d", desc.GetID())
> ```

nit: this is loud. I don't really want us logging 1M times if we fix 1M descriptors. Maybe lot out the batch?
___
*[pkg/migration/migrations/fix_descriptor_migration.go, line 124 at r13](https://reviewable.io/reviews/cockroachdb/cockroach/66495#-MdT5Jw0BQ1V9V58fASG:-MdT5Jw16teywqpM9mkb:b-a1mkhm) ([raw file](https://github.com/cockroachdb/cockroach/blob/275028f0a068f0d098061faf888a84a6a2d0d888/pkg/migration/migrations/fix_descriptor_migration.go#L124)):*
> ```
> 
> 		descs = append(descs, desc)
> 		timestamps = append(timestamps, ts)
> ```
I feel like I wasn't clear enough on the reason for the batching. We'd like to evaluate the predicate inside the loop here and then accumulate a batch to write to the store in a single shot.

**Review by RichardJCai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/66495)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @nihalpednekar, @postamar, @rafiss, and @RichardJCai)

___
*[pkg/migration/migrations/fix_descriptor_migration.go, line 73 at r13](https://reviewable.io/reviews/cockroachdb/cockroach/66495#-MdT57KX75AwRrQcZ6m1:-MdTH1811aheHcI_fx8k:bhdb8pu) ([raw file](https://github.com/cockroachdb/cockroach/blob/275028f0a068f0d098061faf888a84a6a2d0d888/pkg/migration/migrations/fix_descriptor_migration.go#L73)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

The point of the batching is to batch the writes into a single write batch. Use `descriptors.WriteDescToBatch`
</blockquote></details>

Oops for some reason I thought I was doing that :facepalm: done now
___
*[pkg/migration/migrations/fix_descriptor_migration.go, line 85 at r13](https://reviewable.io/reviews/cockroachdb/cockroach/66495#-MdT4y1m9EB2ciDOuelN:-MdT7JGt-I4il1BjbS3Q:b-ds12mn) ([raw file](https://github.com/cockroachdb/cockroach/blob/275028f0a068f0d098061faf888a84a6a2d0d888/pkg/migration/migrations/fix_descriptor_migration.go#L85)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

nit: this is loud. I don't really want us logging 1M times if we fix 1M descriptors. Maybe lot out the batch?
</blockquote></details>

Logging per batch
___
*[pkg/migration/migrations/fix_descriptor_migration.go, line 124 at r13](https://reviewable.io/reviews/cockroachdb/cockroach/66495#-MdT5Jw0BQ1V9V58fASG:-MdTIJG4-fvEmL6-TNVu:b-t06l1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/275028f0a068f0d098061faf888a84a6a2d0d888/pkg/migration/migrations/fix_descriptor_migration.go#L124)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

> ```
> 
> 		descs = append(descs, desc)
> 		timestamps = append(timestamps, ts)
> ```
I feel like I wasn't clear enough on the reason for the batching. We'd like to evaluate the predicate inside the loop here and then accumulate a batch to write to the store in a single shot. 
</blockquote></details>

Sorry, it was clear for some reason I just forgot how `WriteDescToBatch` worked.

**Review by ajwerner — APPROVED** [review]
Needs a `make bazel-generate` but :lgtm: 

> Reviewed 1 of 3 files at r9.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/66495#-:-MdUiXMu0KWAencdCvu7:bkhme7w)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ajwerner, @nihalpednekar, @postamar, @rafiss, and @RichardJCai)

**Comment by RichardJCai** [comment]
bors r=ajwerner
