### PR TITLE
changefeedccl: disallow changfeeds on regional by row tables

### LINKED ISSUE #63239: CDC: disable changefeeds for Regional by Row table
Changefeeds should fail when a user alters table to be regional by row, with a job error of "Changefeeds not supported when setting region by row."

When a user attempts to create a changefeed on a table with RBR enabled, we should fail with an error, like above.

### PR DESCRIPTION
**Pull request by stevendanna**
To fully support changefeeds, we need to make a number of technical-
and product-level decisions and changes. Until those changes are made,
we want to disable changefeeds on regional by row tables.

This change ads a new check in the table validator that will prevent
new changefeeds from being started on a table where
IsLocalityRegionalByRow() is true.

Further, existing feeds will fails with a non-retriable error.

Fixes #63239

Release note (enterprise change): Changefeeds will now fail on any
regional by row table with an error such as:

    CHANGEFEED cannot target REGIONAL BY ROW tables: TABLE_NAME

This is to prevent unexpected changefeed behavior until we can offer
full support for regional by row tables.

### CODE REVIEW

File: pkg/ccl/changefeedccl/kvfeed/kv_feed.go [hunk 1]
```diff
@@ -214,7 +214,14 @@ func (f *kvFeed) run(ctx context.Context) (err error) {
 		boundaryType := jobspb.ResolvedSpan_BACKFILL
 		if f.schemaChangePolicy == changefeedbase.OptSchemaChangePolicyStop {
 			boundaryType = jobspb.ResolvedSpan_EXIT
-		} else if events, err := f.tableFeed.Peek(ctx, highWater.Next()); err == nil && isPrimaryKeyChange(events) {
+		} else if events, err := f.tableFeed.Peek(ctx, highWater.Next()); err == nil && isRegionalByRowChange(events) {
+			// NOTE(ssd): The user is unlikely to see this
+			// error. The schemafeed will fail with an
+			// non-retriable error, meaning we likely
+			// return right after runUntilTableEvent
+			// above.
```
Comment (stevendanna) [inline pkg/ccl/changefeedccl/kvfeed/kv_feed.go:222]: Note: because of this, if we want the absolutely most minimal change, we can avoid any changes to the event_table_filter and this code and just rely on the error coming out of validate.  I realized that the validate changes were  enough after writing this code and then thought it might be good to keep it in case the validate code changes, but given that we have a test for in-flight changefeeds failing, perhaps we can drop it.

**Comment by stevendanna** [comment]
@amruss I used a slightly different error message than what you recommended to be consistent with the error messages we output for other unsupported tables such as those with column families.  Let me know if you'd prefer I change it to your recommended language.

**Comment by amruss** [comment]
>  I used a slightly different error message than what you recommended to be consistent with the error messages we output for other unsupported tables such as those with column families. Let me know if you'd prefer I change it to your recommended language.

LGTM - probably better to be consistent here

File: pkg/ccl/changefeedccl/kvfeed/kv_feed.go (hunk 1 above)
Comment (stevendanna) [reply pkg/ccl/changefeedccl/kvfeed/kv_feed.go:231]: I've split this into a second commit to make it easier to drop if we want to.

**Comment by stevendanna** [comment]
The first commit is all that is strictly needed, so it might be good to go commit-by-commit.

File: pkg/ccl/changefeedccl/changefeed_test.go [hunk 2]
```diff
@@ -1172,6 +1177,59 @@ func TestChangefeedAuthorization(t *testing.T) {
 	t.Run(`enterprise`, enterpriseTest(testFn))
 }
 
+func TestChangefeedFailOnRBRChange(t *testing.T) {
+	defer leaktest.AfterTest(t)()
+	defer log.Scope(t).Close(t)
+
+	skip.UnderRace(t)
+	skip.UnderShort(t)
```
Comment (miretskiy) [inline pkg/ccl/changefeedccl/changefeed_test.go:1185]: does the test take long time to run?

File: pkg/ccl/changefeedccl/changefeed_test.go [hunk 3]
```diff
@@ -1172,6 +1177,59 @@ func TestChangefeedAuthorization(t *testing.T) {
...
+		case <-ctx.Done():
+			t.Fatal("timed out waiting for changefeed to fail")
+		case <-done:
+		}
+	}
+	testFn := func(t *testing.T, db *gosql.DB, f cdctest.TestFeedFactory) {
+		sqlDB := sqlutils.MakeSQLRunner(db)
+		sqlDB.Exec(t, "SET CLUSTER SETTING changefeed.experimental_poll_interval = '200ms'")
+		sqlDB.Exec(t, "SET CLUSTER SETTING kv.closed_timestamp.target_duration = '50ms'")
+		sqlDB.Exec(t, "SET CLUSTER SETTING kv.closed_timestamp.close_fraction = .99")
```
Comment (miretskiy) [inline pkg/ccl/changefeedccl/changefeed_test.go:1207]: I don't think these 3 are needed, are they?  I thought sinkless+enterprise test below do that already.

**Review by miretskiy — APPROVED** [review]

File: pkg/ccl/changefeedccl/changefeed_test.go (hunk 2 above)
Comment (stevendanna) [reply pkg/ccl/changefeedccl/changefeed_test.go:1185]: Not the fastest but not the slowest either:

```
--- PASS: TestChangefeedFailOnRBRChange (1.32s)
    --- PASS: TestChangefeedFailOnRBRChange/sinkless (0.48s)
        --- PASS: TestChangefeedFailOnRBRChange/sinkless/regional_by_row (0.28s)
    --- PASS: TestChangefeedFailOnRBRChange/enterprise (0.82s)
        --- PASS: TestChangefeedFailOnRBRChange/enterprise/regional_by_row (0.53s)
```

File: pkg/ccl/changefeedccl/changefeed_test.go (hunk 3 above)
Comment (stevendanna) [reply pkg/ccl/changefeedccl/changefeed_test.go:1207]: I removed 2 of the 3.  The lower target_duration does seem to speed up this test substantially and right now we have a default of 1s.

**Comment by stevendanna** [comment]
bors r=miretskiy
