### PR TITLE
crosscluster/logical: use UDF as an "applier"

### LINKED ISSUE #129036: ldr: reinstate applier mode for UDF support
**Describe the problem**

We've decided that the UDF should _always_ apply to an incoming row. Currently the UDF is only used on a fallback if the optimistic insert path does not work.

Jira issue: CRDB-41343

### PR DESCRIPTION
**Pull request by stevendanna**
Previously, we were using the UDF as a fallback when an insert hit a conflict. We've subsequently decided that we think running the UDF on every proposed row is more useful.

Fixes #129036
Release note: none

### CODE REVIEW

**Comment by msbutler** [comment]
@stevendanna the failure in extended CI looks concerning. I'll wait to review until after you give it a look.

**Comment by stevendanna** [comment]
@msbutler I'm like 95% sure I understand the test failure and it is a problem in the test.

File: pkg/ccl/crosscluster/logical/logical_replication_job_test.go [hunk 1]
```diff
@@ -1134,6 +1127,11 @@ func TestLogicalStreamIngestionJobWithFallbackUDF(t *testing.T) {
 	RETURNS string
 	AS $$
 	BEGIN
+	SELECT crdb_internal.log((proposed).payload);
+        IF existing IS NULL THEN
+            RETURN 'accept_proposed';
+        END IF;
```
Comment (msbutler) [inline pkg/ccl/crosscluster/logical/logical_replication_job_test.go:1133]: i guess this is the only test that needed to be changed, now that udf is run as an applier instead of via conflict resolution?

**Review by msbutler — APPROVED** [review]
LGTM! Down the line, we should test streaming multiple tables with different applier policies.

File: pkg/ccl/crosscluster/logical/logical_replication_job_test.go (hunk 1 above)
Comment (stevendanna) [reply pkg/ccl/crosscluster/logical/logical_replication_job_test.go:1133]: Yeah, the tests were all originally written for the applier mode except for this one.
