### PR TITLE
server: don't print trace if empty

### LINKED ISSUE #105378: server: spammy trace logging on context cancellation
In #102793, we began logging trace events on context cancellation. However, this results in traces being logged constantly, mostly for internal requests. We see this frequently in roachtests, e.g. #104709 and #105260, often due to `HeartbeatTxn`, `QueryTxn`, and `EndTxn` requests. The traces are often, but not always, empty. We need to do something about these.

Here's an example, there were thousands of these in a few minutes.

```
I230619 12:36:59.982466 46378 server/node.go:1317 ⋮ [T1,n7] 1352  batch request ‹HeartbeatTxn [/Local/Range/Table/106/1/-8578380985326469808/RangeDescriptor,/Min), [txn: c9232c77]› failed with error: ‹result is ambiguous: after 0.02s of attempting command: context canceled›
I230619 12:36:59.982466 46378 server/node.go:1317 ⋮ [T1,n7] 1352 +trace:
I230619 12:36:59.982466 46378 server/node.go:1317 ⋮ [T1,n7] 1352 +‹<empty recording>›
```

Jira issue: CRDB-29006

### PR DESCRIPTION
**Pull request by adityamaru**
This change adds a conditional to only print the
trace of context cancelled request if the trace is not empty. This avoids log spam noticed in #105378.

Fixes: #105378
Release note: None

### CODE REVIEW

File: pkg/server/node.go [hunk 1]
```diff
@@ -1315,8 +1315,11 @@ func (n *Node) batchInternal(
 	// the request was doing at the time it noticed the cancellation.
 	if pErr != nil && ctx.Err() != nil {
 		if sp := tracing.SpanFromContext(ctx); sp != nil && !sp.IsNoop() {
-			log.Infof(ctx, "batch request %s failed with error: %s\ntrace:\n%s", args.String(),
-				pErr.GoError().Error(), sp.GetConfiguredRecording().String())
+			recording := sp.GetConfiguredRecording()
+			if recording.Len() != 0 {
+				log.Infof(ctx, "batch request %s failed with error: %s\ntrace:\n%s", args.String(),
```
Comment (knz) [inline pkg/server/node.go:1320]: don't we want to see the batch error object even if the recording is empty?

Also, plse print `pErr.GoError()` and not call `.Error()`. This will ensure that the non-redactable bits of the error show up in logs properly.

(nit Also use `%v` for the error. )

**Review by knz — CHANGES_REQUESTED** [review]
consider printing the error, but not the trace if empty

File: pkg/server/node.go (hunk 1 above)
Comment (adityamaru) [reply pkg/server/node.go:1320]: The errors will always be `context canceled` or `context deadline exceeded` because we only log the line if `ctx.Err() != nil`. I don't have a sense for whether this is useful for the HeartbeatTxn, QueryTxn, and EndTxn requests that @erikgrinaker pointed out as spamming the logs in some roachtests?

Thanks for the pointer on the error message format, fixing that up now.

Comment (adityamaru) [reply pkg/server/node.go]: For ExportRequests by backups (which is what motivated me to add this logline) we always expect a non-empty tracing span as they are sent with a `Structured` recording. If for some reason there is no trace, we'd see the context cancelled/timed out error on the client side anyways so there isn't much value in printing it here too.

**Review by knz — APPROVED** [review]

File: pkg/server/node.go [hunk 2]
```diff
@@ -1315,8 +1315,11 @@ func (n *Node) batchInternal(
 	// the request was doing at the time it noticed the cancellation.
 	if pErr != nil && ctx.Err() != nil {
 		if sp := tracing.SpanFromContext(ctx); sp != nil && !sp.IsNoop() {
-			log.Infof(ctx, "batch request %s failed with error: %s\ntrace:\n%s", args.String(),
-				pErr.GoError().Error(), sp.GetConfiguredRecording().String())
+			recording := sp.GetConfiguredRecording()
+			if recording.Len() != 0 {
+				log.Infof(ctx, "batch request %s failed with error: %v\ntrace:\n%s", args.String(),
+					pErr.GoError(), recording.String())
```
Comment (knz) [inline pkg/server/node.go:1321]: Also, don't call `.String()` on the recording. This will also ensure non-redactable details from the trace are properly included!

Comment (adityamaru) [reply pkg/server/node.go:1321]: doh yes, I need to get out of the habit of calling `.String`. thanks!

File: pkg/server/node.go (hunk 1 above)
Comment (erikgrinaker) [reply pkg/server/node.go]: Yeah, let's err on the side of not logging here. Generally, we only want to see this when we're reasonably sure that there's a human who requested the trace (is there a better way to determine that?). If they trigger for any random request, we'll get thousands of log lines for internal requests that noone cares about.

**Comment by adityamaru** [comment]
bors r=knz
