### PR TITLE
sql: fix sql input to security.SQLUsername issue

### LINKED ISSUE #67818: sql: properly convert user name as sql input to security.SQLUsername
Currently the following two statements do not have their sql inputs converted correctly to `security.SQLUsername`

- `drop owned by`
- `reassigned owned by`

They rely on `role_spec_list` which does not correctly generate the `security.SQLUsername`

Most cases where we have a `security.SQLUsername` are already normalized. This is important because usernames are case-insensitive in CockroachDB.'

See https://github.com/cockroachdb/cockroach/pull/67625 for an example of how this was fixed for GRANT.

### PR DESCRIPTION
**Pull request by e-mbrown**
Resolves: #67818 

The statements `drop owned by` and `reassigned owned by` were case-sensitive because they relied on `role_spec_list` which wasn't correctly generating `security.SQLusername`. With this change the two statement use `NameLists` that are then converted into `security.SQLusernames`. 

`role_spec_list` has been removed from the parser because it is no longer being used.

Release note: None

### CODE REVIEW

File: pkg/sql/sem/tree/reassign_owned_by.go [hunk 1]
```diff
@@ -16,7 +16,7 @@ import "github.com/cockroachdb/cockroach/pkg/security"
 type ReassignOwnedBy struct {
 	// TODO(solon): Adjust this, see
 	// https://github.com/cockroachdb/cockroach/issues/54696
```
Comment (RichardJCai) [inline pkg/sql/sem/tree/reassign_owned_by.go:18]: This comment is out of date now

**Review by RichardJCai — APPROVED** [review]

File: pkg/sql/parser/sql.y [hunk 2]
```diff
@@ -8869,10 +8858,10 @@ multiple_set_clause:
 // TO {<name> | CURRENT_USER | SESSION_USER}
 // %SeeAlso: DROP OWNED BY
 reassign_owned_by_stmt:
-  REASSIGN OWNED BY role_spec_list TO role_spec
+  REASSIGN OWNED BY name_list TO role_spec
```
Comment (RichardJCai) [inline pkg/sql/parser/sql.y:8861]: Can you look into normalizing role_spec correctly as well?

See:
https://github.com/cockroachdb/cockroach/issues/55396

and:
https://github.com/cockroachdb/cockroach/blob/master/pkg/sql/parser/sql.y#L1319
https://github.com/cockroachdb/cockroach/blob/master/pkg/sql/parser/sql.y#L2478

Can be a separate PR

**Comment by e-mbrown** [comment]
bors r=RichardJCai
