### PR TITLE
roachprod: avoid extra dead event in roachprod monitor

### LINKED ISSUE #66522: roachtest: version/mixed/nodes=3 failed
roachtest.version/mixed/nodes=3 [failed](https://teamcity.cockroachdb.com/viewLog.html?buildId=3087613&tab=buildLog) with [artifacts](https://teamcity.cockroachdb.com/viewLog.html?buildId=3087613&tab=artifacts#/version/mixed/nodes=3) on master @ [ec36bc66f5147a8703719a9c890be12dd0c08945](https://github.com/cockroachdb/cockroach/commits/ec36bc66f5147a8703719a9c890be12dd0c08945):

```
The test failed on branch=master, cloud=gce:
test artifacts and logs in: /home/agent/work/.go/src/github.com/cockroachdb/cockroach/artifacts/version/mixed/nodes=3/run_1
	cluster.go:1870,version.go:139,cluster.go:2462,errgroup.go:57: /home/agent/work/.go/src/github.com/cockroachdb/cockroach/bin/roachprod start --encrypt=false teamcity-3087613-1623823848-07-n4cpu4:1 returned: context canceled
		(1) /home/agent/work/.go/src/github.com/cockroachdb/cockroach/bin/roachprod start --encrypt=false teamcity-3087613-1623823848-07-n4cpu4:1 returned
		  | stderr:
		  |
		  | stdout:
		  | teamcity-3087613-1623823848-07-n4cpu4: starting nodes
		Wraps: (2) secondary error attachment
		  | signal: killed
		  | (1) signal: killed
		  | Error types: (1) *exec.ExitError
		Wraps: (3) context canceled
		Error types: (1) *main.withCommandDetails (2) *secondary.withSecondaryError (3) *errors.errorString

	cluster.go:2484,version.go:208,version.go:222,test_runner.go:757: monitor failure: unexpected node event: 1: dead (exit status 0)
		(1) attached stack trace
		  -- stack trace:
		  | main.(*monitor).WaitE
		  | 	/home/agent/work/.go/src/github.com/cockroachdb/cockroach/pkg/cmd/roachtest/cluster.go:2472
		  | main.(*monitor).Wait
		  | 	/home/agent/work/.go/src/github.com/cockroachdb/cockroach/pkg/cmd/roachtest/cluster.go:2480
		  | main.registerVersion.func1
		  | 	/home/agent/work/.go/src/github.com/cockroachdb/cockroach/pkg/cmd/roachtest/version.go:208
		  | main.registerVersion.func2
		  | 	/home/agent/work/.go/src/github.com/cockroachdb/cockroach/pkg/cmd/roachtest/version.go:222
		  | main.(*testRunner).runTest.func2
		  | 	/home/agent/work/.go/src/github.com/cockroachdb/cockroach/pkg/cmd/roachtest/test_runner.go:757
		  | runtime.goexit
		  | 	/usr/local/go/src/runtime/asm_amd64.s:1374
		Wraps: (2) monitor failure
		Wraps: (3) unexpected node event: 1: dead (exit status 0)
		Error types: (1) *withstack.withStack (2) *errutil.withPrefix (3) *errors.errorString
```
<details><summary>Reproduce</summary>
<p>
<p>To reproduce, try:

```bash
# From https://go.crdb.dev/p/roachstress, perhaps edited lightly.
caffeinate ./roachstress.sh version/mixed/nodes=3
```
</p>
</p>
</details>
/cc @cockroachdb/kv
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*version/mixed/nodes=3.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)
</sub>

### LINKED ISSUE #66528: roachtest: version/mixed/nodes=5 failed
roachtest.version/mixed/nodes=5 [failed](https://teamcity.cockroachdb.com/viewLog.html?buildId=3087613&tab=buildLog) with [artifacts](https://teamcity.cockroachdb.com/viewLog.html?buildId=3087613&tab=artifacts#/version/mixed/nodes=5) on master @ [ec36bc66f5147a8703719a9c890be12dd0c08945](https://github.com/cockroachdb/cockroach/commits/ec36bc66f5147a8703719a9c890be12dd0c08945):

```
The test failed on branch=master, cloud=gce:
test artifacts and logs in: /home/agent/work/.go/src/github.com/cockroachdb/cockroach/artifacts/version/mixed/nodes=5/run_1
	cluster.go:1870,version.go:139,cluster.go:2462,errgroup.go:57: /home/agent/work/.go/src/github.com/cockroachdb/cockroach/bin/roachprod start --encrypt=false teamcity-3087613-1623823848-37-n6cpu4:1 returned: context canceled
		(1) /home/agent/work/.go/src/github.com/cockroachdb/cockroach/bin/roachprod start --encrypt=false teamcity-3087613-1623823848-37-n6cpu4:1 returned
		  | stderr:
		  |
		  | stdout:
		  | teamcity-3087613-1623823848-37-n6cpu4: starting nodes
		  | teamcity-3087613-1623823848-37-n6cpu4: initializing cluster
		Wraps: (2) secondary error attachment
		  | signal: killed
		  | (1) signal: killed
		  | Error types: (1) *exec.ExitError
		Wraps: (3) context canceled
		Error types: (1) *main.withCommandDetails (2) *secondary.withSecondaryError (3) *errors.errorString

	cluster.go:2484,version.go:208,version.go:222,test_runner.go:757: monitor failure: unexpected node event: 1: dead (exit status 0)
		(1) attached stack trace
		  -- stack trace:
		  | main.(*monitor).WaitE
		  | 	/home/agent/work/.go/src/github.com/cockroachdb/cockroach/pkg/cmd/roachtest/cluster.go:2472
		  | main.(*monitor).Wait
		  | 	/home/agent/work/.go/src/github.com/cockroachdb/cockroach/pkg/cmd/roachtest/cluster.go:2480
		  | main.registerVersion.func1
		  | 	/home/agent/work/.go/src/github.com/cockroachdb/cockroach/pkg/cmd/roachtest/version.go:208
		  | main.registerVersion.func2
		  | 	/home/agent/work/.go/src/github.com/cockroachdb/cockroach/pkg/cmd/roachtest/version.go:222
		  | main.(*testRunner).runTest.func2
		  | 	/home/agent/work/.go/src/github.com/cockroachdb/cockroach/pkg/cmd/roachtest/test_runner.go:757
		  | runtime.goexit
		  | 	/usr/local/go/src/runtime/asm_amd64.s:1374
		Wraps: (2) monitor failure
		Wraps: (3) unexpected node event: 1: dead (exit status 0)
		Error types: (1) *withstack.withStack (2) *errutil.withPrefix (3) *errors.errorString
```
<details><summary>Reproduce</summary>
<p>
<p>To reproduce, try:

```bash
# From https://go.crdb.dev/p/roachstress, perhaps edited lightly.
caffeinate ./roachstress.sh version/mixed/nodes=5
```
</p>
</p>
</details>
/cc @cockroachdb/kv
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*version/mixed/nodes=5.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)
</sub>

### PR DESCRIPTION
**Pull request by tbg**
Prior to this commit, we'd get an extra dead event when restarting a
node:

```
// initially running
1: 5762
// issue roachprod stop
1: dead (exit status 137)
// issue roachprod start
1: dead (exit status 0)
1: 6254
```

This would in turn upset roachtest's `monitor`, as it keeps track of
the number of expected death events, and cause bogus test failures.

This was introduced in #66414 and is fixed in this commit.

As a small extra fix, if we don't observe the exit status of the
stopped systemd unit (i.e. if the process cycles rapidly), we now
correctly print that we don't know the exit status, where previously
we would print the "exit" status of the new running incarnation, i.e.
likely zero.

I tested this manually by exacerbating the sleeps in the shell snippet:

```
1: 10885
1: dead (exit status unknown)
1: 11220
```

I also verfied that repeated restarts produce the expected events in
general, i.e. one dead event following one pid event.

Closes https://github.com/cockroachdb/cockroach/issues/66522
Closes https://github.com/cockroachdb/cockroach/issues/66528

Release note: None

### CODE REVIEW

**Comment by tbg** [comment]
Heh, still one buglet left. When pointed at a running node, we get a bogus event:

```
$ roachprod monitor tobias-dead
1: dead (exit status unknown)
1: 12078
```

I'll ping when it's *actually* ready.

Wonder how one would unit test this sort of thing. Maybe the next best thing is a roachtest just for testing these things in isolation.

**Comment by erikgrinaker** [comment]
Aw man, I realized this after I went to bed the other night, but then forgot what the problem was the next morning. The logic here is surprisingly annoying to get right.

File: pkg/cmd/roachprod/install/cluster_synced.go [hunk 1]
```diff
@@ -366,22 +366,39 @@ if [ ! -f "{{.Store}}/CURRENT" ]; then
...
+	status="unknown"
 {{- else }}
+  # When CRDB is not running, this is zero.
 	pid=$(systemctl show cockroach --property MainPID --value)
 	status=$(systemctl show cockroach --property ExecMainStatus --value)
 {{- end }}
 
+  if [[ "${lastpid}" == -1 && "${pid}" != 0 ]]; then
+    # On the first iteration through the loop, if the process is running,
+    # don't register a PID change (which would trigger an erroneous dead
```
Comment (erikgrinaker) [inline pkg/cmd/roachprod/install/cluster_synced.go:385]: This reads a bit odd, because this _does_ register as a PID change (pid != 0 thus pid != lastpid), but it doesn't register as a dead event.

**Review by erikgrinaker — APPROVED** [review]
LGTM, thanks for fixing this.

File: pkg/cmd/roachprod/install/cluster_synced.go (hunk 1 above)
Comment (tbg) [reply pkg/cmd/roachprod/install/cluster_synced.go:385]: Yeah - I agree. I'm heading out for tonight though and would like the tests to *not* fail again in the upcoming nightly, so going to merge this for now.

**Comment by tbg** [comment]
bors r=erikgrinaker
