### PR TITLE
changefeedccl: deflake TestAlterChangefeedAddTargetsDuringSchemaChangeError

### LINKED ISSUE #163294: ccl/changefeedccl: TestAlterChangefeedAddTargetsDuringSchemaChangeError failed
ccl/changefeedccl.TestAlterChangefeedAddTargetsDuringSchemaChangeError [failed](https://mesolite.cluster.engflow.com/invocations/default/da8749e7-8349-4709-a4c7-49f203b8ed79?testReportRun=1&testReportShard=4&testReportAttempt=1#targets-Ly9wa2cvY2NsL2NoYW5nZWZlZWRjY2w6Y2hhbmdlZmVlZGNjbF90ZXN0) on master @ [6ff0c3e5ce16f75a302d6c774ed501fa3552c160](https://github.com/cockroachdb/cockroach/commits/6ff0c3e5ce16f75a302d6c774ed501fa3552c160):

```
    alter_changefeed_test.go:2241: span /Table/106/2/9{20/0-30/0} NONE 1770750742.114615960,0
    alter_changefeed_test.go:2275: handling span /Table/106/2/9{20/0-30/0}: true
    alter_changefeed_test.go:2241: span /Table/106/2/9{30/0-40/0} NONE 1770750742.114615960,0
    alter_changefeed_test.go:2275: handling span /Table/106/2/9{30/0-40/0}: false
    alter_changefeed_test.go:2241: span /Table/106/2/9{40/0-50/0} NONE 1770750742.114615960,0
    alter_changefeed_test.go:2275: handling span /Table/106/2/9{40/0-50/0}: false
    alter_changefeed_test.go:2241: span /Table/106/2/9{50/0-60/0} NONE 1770750742.114615960,0
    alter_changefeed_test.go:2275: handling span /Table/106/2/9{50/0-60/0}: false
    alter_changefeed_test.go:2241: span /Table/106/2/9{60/0-70/0} NONE 1770750742.114615960,0
    alter_changefeed_test.go:2275: handling span /Table/106/2/9{60/0-70/0}: true
    alter_changefeed_test.go:2241: span /Table/106/2/9{70/0-80/0} NONE 1770750742.114615960,0
    alter_changefeed_test.go:2275: handling span /Table/106/2/9{70/0-80/0}: false
    alter_changefeed_test.go:2241: span /Table/106/2/9{80/0-90/0} NONE 1770750742.114615960,0
    alter_changefeed_test.go:2275: handling span /Table/106/2/9{80/0-90/0}: false
    alter_changefeed_test.go:2241: span /Table/106/{2-3} NONE 1770750742.114615960,0
    alter_changefeed_test.go:2275: handling span /Table/106/{2-3}: false
    alter_changefeed_test.go:2241: span /Table/106/{2-3} NONE 0,0
    alter_changefeed_test.go:2267: handling span /Table/106/{2-3}: false
    alter_changefeed_test.go:2241: span /Table/106/{2-3} NONE 1770750746.000000000,0
    alter_changefeed_test.go:2267: handling span /Table/106/{2-3}: true
    alter_changefeed_test.go:2241: span /Table/106/{2-3} NONE 1770750747.000000000,0
    alter_changefeed_test.go:2267: handling span /Table/106/{2-3}: true
    alter_changefeed_test.go:2241: span /Table/106/{2-3} NONE 1770750750.000000000,0
    alter_changefeed_test.go:2267: handling span /Table/106/{2-3}: true
    alter_changefeed_test.go:2241: span /Table/106/{2-3} NONE 1770750753.000000000,0
    alter_changefeed_test.go:2267: handling span /Table/106/{2-3}: true
    alter_changefeed_test.go:2241: span /Table/106/{2-3} NONE 1770750756.000000000,0
    alter_changefeed_test.go:2267: handling span /Table/106/{2-3}: true
    alter_changefeed_test.go:2241: span /Table/106/{2-3} NONE 1770750759.000000000,0
    alter_changefeed_test.go:2267: handling span /Table/106/{2-3}: true
    alter_changefeed_test.go:2241: span /Table/106/{2-3} NONE 1770750762.000000000,0
    alter_changefeed_test.go:2267: handling span /Table/106/{2-3}: true
    alter_changefeed_test.go:2241: span /Table/106/{2-3} NONE 1770750765.000000000,0
    alter_changefeed_test.go:2267: handling span /Table/106/{2-3}: true
    alter_changefeed_test.go:2241: span /Table/106/{2-3} NONE 1770750768.000000000,0
    alter_changefeed_test.go:2267: handling span /Table/106/{2-3}: true
    alter_changefeed_test.go:2241: span /Table/106/{2-3} NONE 1770750771.000000000,0
    alter_changefeed_test.go:2267: handling span /Table/106/{2-3}: true
    alter_changefeed_test.go:2241: span /Table/106/{2-3} NONE 1770750774.000000000,0
    alter_changefeed_test.go:2267: handling span /Table/106/{2-3}: true
    alter_changefeed_test.go:2241: span /Table/106/{2-3} NONE 1770750777.000000000,0
    alter_changefeed_test.go:2267: handling span /Table/106/{2-3}: true
    alter_changefeed_test.go:2241: span /Table/106/{2-3} NONE 1770750780.000000000,0
    alter_changefeed_test.go:2267: handling span /Table/106/{2-3}: true
    alter_changefeed_test.go:2241: span /Table/106/{2-3} NONE 1770750783.000000000,0
    alter_changefeed_test.go:2267: handling span /Table/106/{2-3}: true
    alter_changefeed_test.go:2241: span /Table/106/{2-3} NONE 1770750786.000000000,0
    alter_changefeed_test.go:2267: handling span /Table/106/{2-3}: true
    alter_changefeed_test.go:2287: condition failed to evaluate within 45s: from alter_changefeed_test.go:2294: waiting for checkpoint
--- FAIL: TestAlterChangefeedAddTargetsDuringSchemaChangeError/webhook (57.90s)
```

Parameters:
 - <code>attempt=1</code>
 - <code>run=1</code>
 - <code>shard=4</code>
<details><summary>Help</summary>
<p>

See also: [How To Investigate a Go Test Failure \(internal\)](https://cockroachlabs.atlassian.net/l/c/HgfXfJgM)
</p>
</details>
/cc @cockroachdb/cdc
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*TestAlterChangefeedAddTargetsDuringSchemaChangeError.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/bazci/githubpost/issues)

</sub>

Jira issue: CRDB-60162

### PR DESCRIPTION
**Pull request by jeffswenson**
There was a bug in TestAlterChangefeedAddTargetsDuringSchemaChangeError. It was trying to filter spans that cover the entire index, but it was using the index id from the original index, not the index id from the rewritten index. The only reason the test used to pass most of the time is one of the partial spans would trigger a checkpoint flush before the full index span was observed.

Fixes: #163294
Release note: None

### CODE REVIEW

File: pkg/ccl/changefeedccl/alter_changefeed_test.go [hunk 1]
```diff
@@ -2269,13 +2276,13 @@ WITH resolved = '1s', no_initial_scan, min_checkpoint_frequency='1ns'`,
...
-			// Only allow resolving if we definitely won't have a completely resolved table
-			if !r.Span.Equal(tableSpan) && haveGaps {
+			// Only allow resolving if we definitely won't have a completely resolved index
+			if !isFullIndexSpan(r.Span) && haveGaps {
 				skip := rnd.Intn(10) > 7
 				t.Logf("handling span %s: %t", r.Span.String(), skip)
 				return skip, nil
 			}
-			t.Logf("skipping span %s", r.Span.String())
+			t.Logf("skipping full index span %s", r.Span.String())
```
Comment (andyyang890) [inline pkg/ccl/changefeedccl/alter_changefeed_test.go]: nit: this code would be hit for non-full index spans too

File: pkg/ccl/changefeedccl/alter_changefeed_test.go [hunk 2]
```diff
@@ -2269,13 +2276,13 @@ WITH resolved = '1s', no_initial_scan, min_checkpoint_frequency='1ns'`,
...
 			haveGaps = true
```
Comment (andyyang890) [inline pkg/ccl/changefeedccl/alter_changefeed_test.go]: nit: it's technically wrong for us to set `hasGaps` when the span is the full-index span, but I believe we'd always get the sub-spans first

maybe we for code clarity, we should have an `if isFullIndexSpan(r.Span)` branch a little higher that returns true without setting `hasGaps` and then we'd be able to simplify the if condition for this statement?

**Review by andyyang890 — APPROVED** [review]
Nice find!

You might want to replace the issue referenced in the commit message/PR desc with the one for master so that we don't close the 26.1 branch issue until it's backported: #163294

File: pkg/ccl/changefeedccl/alter_changefeed_test.go (hunk 2 above)
Comment (jeffswenson) [reply pkg/ccl/changefeedccl/alter_changefeed_test.go]: `hasGaps` was actually a misnomer in the original implementation. It was only set when we observed the full table index. I decided to rewrite the filter to explicitly track the state we care about: we never want to emit a span that overlaps with a span we are trying to skip.

I also moved the checkpoint polling out of the span filter and into the succeeds soon loop.

File: pkg/ccl/changefeedccl/alter_changefeed_test.go [hunk 3]
```diff
@@ -2155,14 +2154,9 @@ func TestAlterChangefeedAddTargetsDuringSchemaChangeError(t *testing.T) {
...
 		sqlDB := sqlutils.MakeSQLRunner(s.DB)
-		usingLegacySchemaChanger := maybeDisableDeclarativeSchemaChangesForTest(t, sqlDB)
-		// NB: For the `ALTER TABLE foo ADD COLUMN ... DEFAULT` schema change,
-		// the expected boundary is different depending on if we are using the
-		// legacy schema changer or not.
-		expectedBoundaryType := jobspb.ResolvedSpan_RESTART
-		if usingLegacySchemaChanger {
-			expectedBoundaryType = jobspb.ResolvedSpan_BACKFILL
-		}
+		// Metemorphically disable declarative schema changer to ensure we cover
```
Comment (andyyang890) [inline pkg/ccl/changefeedccl/alter_changefeed_test.go:2157]: nit: typo in "Metamorphically"

File: pkg/ccl/changefeedccl/alter_changefeed_test.go [hunk 4]
```diff
@@ -2219,89 +2213,70 @@ WITH resolved = '1s', no_initial_scan, min_checkpoint_frequency='1ns'`,
...
-			// abort the transaction which is trying to write the job record.
-			if nextProgressCheck.IsZero() || nextProgressCheck.Before(timeutil.Now()) {
-				// Check if we've set a checkpoint yet
-				progress := loadProgress(t, jobFeed, jobRegistry)
-				if checkpoint := loadCheckpoint(t, progress); checkpoint != nil {
-					initialCheckpoint = makeSpanGroupFromCheckpoint(t, checkpoint)
-					atomic.StoreInt32(&foundCheckpoint, 1)
-				}
-				nextProgressCheck = timeutil.Now().Add(progressBackoff)
+			if backfillTimestamp == (hlc.Timestamp{}) {
```
Comment (andyyang890) [inline pkg/ccl/changefeedccl/alter_changefeed_test.go]: nit: use `IsEmpty()`

File: pkg/ccl/changefeedccl/alter_changefeed_test.go [hunk 5]
```diff
@@ -2219,89 +2213,70 @@ WITH resolved = '1s', no_initial_scan, min_checkpoint_frequency='1ns'`,
...
+		// for the backfill scan.
 		var backfillTimestamp hlc.Timestamp
-		var initialCheckpoint roachpb.SpanGroup
-		var foundCheckpoint int32
-		progressBackoff := jobRecordPollFrequency
-		var nextProgressCheck time.Time
+
+		// We track skipped spans to ensure we never emit a checkpoint that
+		// overlaps with a span we already skipped.
+		skippedSpans := interval.NewRangeTree()
```
Comment (andyyang890) [inline pkg/ccl/changefeedccl/alter_changefeed_test.go:2224]: Out of curiosity, why an `interval.RangeTree` instead of a `roachpb.SpanGroup`?

File: pkg/ccl/changefeedccl/alter_changefeed_test.go (hunk 2 above)
Comment (andyyang890) [reply pkg/ccl/changefeedccl/alter_changefeed_test.go]: > `hasGaps` was actually a misnomer in the original implementation. It was only set when we observed the full table index.

Hmm my reading of the original code was that it fell through to `hasGaps` with the first non-table span at the backfill timestamp. I like the rewrite though!

File: pkg/ccl/changefeedccl/alter_changefeed_test.go [hunk 6]
```diff
@@ -2219,89 +2213,70 @@ WITH resolved = '1s', no_initial_scan, min_checkpoint_frequency='1ns'`,
...
-				}
-				nextProgressCheck = timeutil.Now().Add(progressBackoff)
+			if backfillTimestamp == (hlc.Timestamp{}) {
+				t.Logf("dropping span %s because we haven't found the boundary event yet", r.Span.String())
+				return true, nil
 			}
 
-			// Filter non-backfill-related spans
-			if !r.Timestamp.Equal(backfillTimestamp.Next()) {
-				skip := !(backfillTimestamp.IsEmpty() || r.Timestamp.LessEq(backfillTimestamp.Next()))
```
Comment (andyyang890) [inline pkg/ccl/changefeedccl/alter_changefeed_test.go:2266]: One thing the rewrite has changed is it no longer passes through all the spans with empty timestamps and timestamps earlier than the backfill timestamp. Should we be keeping that behavior?

Aside: IMO this is an example of a boolean condition where the DeMorganfied version would be easier to read 😛

**Review by andyyang890 — COMMENTED** [review]
> You might want to replace the issue referenced in the commit message/PR desc with the one for master so that we don't close the 26.1 branch issue until it's backported: https://github.com/cockroachdb/cockroach/issues/163294

Wanted to bump this comment

File: pkg/ccl/changefeedccl/alter_changefeed_test.go (hunk 5 above)
Comment (jeffswenson) [reply pkg/ccl/changefeedccl/alter_changefeed_test.go:2224]: It doesn't implement Overlaps and I didn't want to add it just so a test could use it, especially since its a thin wrapper around interval.Range.

File: pkg/ccl/changefeedccl/alter_changefeed_test.go (hunk 6 above)
Comment (jeffswenson) [reply pkg/ccl/changefeedccl/alter_changefeed_test.go:2266]: >One thing the rewrite has changed is it no longer passes through all the spans with empty timestamps and timestamps earlier than the backfill timestamp. Should we be keeping that behavior?

I don't think we need it, since the boundary span will cover the whole range, so I would rather do the simpler thing.

File: pkg/ccl/changefeedccl/alter_changefeed_test.go (hunk 3 above)
Comment (jeffswenson) [reply pkg/ccl/changefeedccl/alter_changefeed_test.go:2157]: Fixed

File: pkg/ccl/changefeedccl/alter_changefeed_test.go (hunk 2 above)
Comment (jeffswenson) [reply pkg/ccl/changefeedccl/alter_changefeed_test.go]: Ahh, you are right. I think maybe emittedSpan is probably the right way to describe the checkpoint.

**Review by andyyang890 — APPROVED** [review]
LGTM
