### PR TITLE
roachtest: fix pertubation disk stall

### LINKED ISSUE #149004: roachtest: perturbation/full/slowDisk failed
roachtest.perturbation/full/slowDisk [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/20042624?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/20042624?buildTab=artifacts#/perturbation/full/slowDisk) on master @ [d94e3501a43b45740331a70ddfddd9f08f567971](https://github.com/cockroachdb/cockroach/commits/d94e3501a43b45740331a70ddfddd9f08f567971):

```
(disk_stall.go:117).Slow: failed to slow disk: failure mode is not setup
test artifacts and logs in: /artifacts/perturbation/full/slowDisk/run_1
```

Parameters:
 - <code>acMode=defaultOption</code>
 - <code>arch=amd64</code>
 - <code>blockSize=4096</code>
 - <code>cloud=gce</code>
 - <code>coverageBuild=false</code>
 - <code>cpu=16</code>
 - <code>diskBandwidthLimit=0</code>
 - <code>disks=2</code>
 - <code>encrypted=false</code>
 - <code>fillDuration=10m0s</code>
 - <code>fs=ext4</code>
 - <code>leaseType=epoch</code>
 - <code>localSSD=true</code>
 - <code>mem=standard</code>
 - <code>numNodes=12</code>
 - <code>numWorkloadNodes=1</code>
 - <code>perturbationDuration=10m0s</code>
 - <code>ratioOfMax=0.5</code>
 - <code>runtimeAssertionsBuild=false</code>
 - <code>seed=0</code>
 - <code>splits=10000</code>
 - <code>ssd=2</code>
 - <code>validationDuration=5m0s</code>
 - <code>vcpu=16</code>
<details><summary>Help</summary>
<p>

See: [roachtest README](https://github.com/cockroachdb/cockroach/blob/master/pkg/cmd/roachtest/README.md)

See: [How To Investigate \(internal\)](https://cockroachlabs.atlassian.net/l/c/SSSBr8c7)

See: [Grafana](https://go.crdb.dev/roachtest-grafana/teamcity-20042624/perturbation-full-slowdisk/1751030317877/1751031598102)

</p>
</details>
/cc @cockroachdb/kv-triage
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*perturbation/full/slowDisk.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/bazci/githubpost/issues)

</sub>

### LINKED ISSUE #149097: roachtest: perturbation/full/slowDisk failed
roachtest.perturbation/full/slowDisk [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/20042778?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/20042778?buildTab=artifacts#/perturbation/full/slowDisk) on release-25.3 @ [50a2d61d2543dc79ec72fd9dc8494592ce3de97f](https://github.com/cockroachdb/cockroach/commits/50a2d61d2543dc79ec72fd9dc8494592ce3de97f):

```
(disk_stall.go:117).Slow: failed to slow disk: failure mode is not setup
test artifacts and logs in: /artifacts/perturbation/full/slowDisk/run_1
```

Parameters:
 - <code>acMode=defaultOption</code>
 - <code>arch=amd64</code>
 - <code>blockSize=4096</code>
 - <code>cloud=gce</code>
 - <code>coverageBuild=false</code>
 - <code>cpu=16</code>
 - <code>diskBandwidthLimit=0</code>
 - <code>disks=2</code>
 - <code>encrypted=false</code>
 - <code>fillDuration=10m0s</code>
 - <code>fs=ext4</code>
 - <code>leaseType=epoch</code>
 - <code>localSSD=true</code>
 - <code>mem=standard</code>
 - <code>numNodes=12</code>
 - <code>numWorkloadNodes=1</code>
 - <code>perturbationDuration=10m0s</code>
 - <code>ratioOfMax=0.5</code>
 - <code>runtimeAssertionsBuild=false</code>
 - <code>seed=0</code>
 - <code>splits=10000</code>
 - <code>ssd=2</code>
 - <code>validationDuration=5m0s</code>
 - <code>vcpu=16</code>
<details><summary>Help</summary>
<p>

See: [roachtest README](https://github.com/cockroachdb/cockroach/blob/master/pkg/cmd/roachtest/README.md)

See: [How To Investigate \(internal\)](https://cockroachlabs.atlassian.net/l/c/SSSBr8c7)

See: [Grafana](https://go.crdb.dev/roachtest-grafana/teamcity-20042778/perturbation-full-slowdisk/1751054447315/1751055729859)

</p>
</details>
<details><summary>Same failure on other branches</summary>
<p>

- #149004 roachtest: perturbation/full/slowDisk failed [A-testing C-bug C-test-failure O-roachtest O-robot T-testeng branch-master release-blocker]
</p>
</details>
/cc @cockroachdb/kv-triage
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*perturbation/full/slowDisk.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/bazci/githubpost/issues)

</sub>

Jira issue: CRDB-51981

### PR DESCRIPTION
**Pull request by DarrylWong**
These tests were not calling disk stall setup. While setup is currently a noop under the configuration it uses, the FI framework asserts that failers are setup first.

Fixes: https://github.com/cockroachdb/cockroach/issues/149004
Fixes: https://github.com/cockroachdb/cockroach/issues/149097
Release note: none

### CODE REVIEW

**Review by golgeek — APPROVED** [review]

File: pkg/cmd/roachtest/tests/perturbation/framework.go [hunk 1]
```diff
@@ -297,6 +297,9 @@ func RegisterTests(r registry.Registry) {
 
 func (v variations) makeClusterSpec() spec.ClusterSpec {
 	opts := append(v.specOptions, spec.CPU(v.vcpu), spec.SSD(v.disks), spec.Mem(v.mem), spec.TerminateOnMigration())
+	if v.perturbationName() == "slowDisk" {
+		opts = append(opts, spec.ReuseNone())
```
Comment (srosenberg) [inline pkg/cmd/roachtest/tests/perturbation/framework.go:302]: I'm assuming this is to avoid potential side-effects of cgroups? It's not entirely obvious why `ReuseNone` only applies in this case.

Comment (DarrylWong) [reply pkg/cmd/roachtest/tests/perturbation/framework.go:302]: Yeah, added a comment. The metamorphic version already sets `ReuseNone` for `slowDisk` although the the `full` and `dev` versions do not.

**Review by herkolategan — APPROVED** [review]

**Comment by DarrylWong** [comment]
TFTRs!

bors r+

**Comment by DarrylWong** [comment]
blathers backport 25.3
