### PR TITLE
upgrades: fix desc ID sequence definition to match expectation

### LINKED ISSUE #93602: roachtest: systemschema/validate-after-version-upgrade failed
roachtest.systemschema/validate-after-version-upgrade [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/7952891?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/7952891?buildTab=artifacts#/systemschema/validate-after-version-upgrade) on master @ [052acc88ad9d7296ce6b8b441627fb469cc74d95](https://github.com/cockroachdb/cockroach/commits/052acc88ad9d7296ce6b8b441627fb469cc74d95):

```
test artifacts and logs in: /artifacts/systemschema/validate-after-version-upgrade/run_1
(test_impl.go:291).Fatal: After upgrading, ``USE system; SHOW CREATE ALL TABLES;`` does not match expected output after version upgrade.
```
<p>Parameters: <code>ROACHTEST_cloud=gce</code>
, <code>ROACHTEST_cpu=4</code>
, <code>ROACHTEST_encrypted=false</code>
, <code>ROACHTEST_fs=ext4</code>
, <code>ROACHTEST_localSSD=true</code>
, <code>ROACHTEST_ssd=0</code>
</p>
<details><summary>Help</summary>
<p>

See: [roachtest README](https://github.com/cockroachdb/cockroach/blob/master/pkg/cmd/roachtest/README.md)

See: [How To Investigate \(internal\)](https://cockroachlabs.atlassian.net/l/c/SSSBr8c7)

</p>
</details>
/cc @cockroachdb/sql-schema
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*systemschema/validate-after-version-upgrade.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)
</sub>

Jira issue: CRDB-22434

### PR DESCRIPTION
**Pull request by ajwerner**
Before this change, the test fails with:

```
Diff:
@@ -29,11 +29,11 @@
 	"lastUpdated" TIMESTAMP NOT NULL DEFAULT now():::TIMESTAMP,
 	"valueType" STRING NULL,
 	CONSTRAINT "primary" PRIMARY KEY (name ASC),
 	FAMILY "fam_0_name_value_lastUpdated_valueType" (name, value, "lastUpdated", "valueType")
 );
-CREATE SEQUENCE public.descriptor_id_seq MINVALUE 1 MAXVALUE 9223372036854775807 INCREMENT 1 START 1;
+CREATE SEQUENCE public.descriptor_id_seq MINVALUE 1 MAXVALUE 9223372036854775807 INCREMENT 1 START 104;
 CREATE TABLE public.tenants (
 	id INT8 NOT NULL,
 	active BOOL NOT NULL DEFAULT true,
 	info BYTES NULL,
 	name STRING NULL AS (crdb_internal.pb_to_json('cockroach.sql.sqlbase.TenantInfo':::STRING, info)->>'name':::STRING) VIRTUAL,
----

```

This was revealed by #93487 which fixed the broken roachtest. Expect a few more of these.
Fixes: #93602

Release note: None

### CODE REVIEW

File: pkg/upgrade/upgrades/desc_id_sequence_for_system_tenant.go [hunk 1]
```diff
@@ -27,14 +27,21 @@ func descIDSequenceForSystemTenant(
 	if !d.Codec.ForSystemTenant() {
 		return nil
 	}
-	mut := tabledesc.NewBuilder(systemschema.DescIDSequence.TableDesc()).BuildCreatedMutableTable()
+	mut := tabledesc.NewBuilder(systemschema.DescIDSequence.TableDesc()).
+		BuildCreatedMutableTable()
```
Comment (postamar) [inline pkg/upgrade/upgrades/desc_id_sequence_for_system_tenant.go:31]: You can get rid of this entirely and replace the sole remaining usage of `mut` with `systemschema.DescIDSequence`, since we're not messing with the start value any more.

**Review by postamar — APPROVED** [review]
LGTM

File: pkg/upgrade/upgrades/desc_id_sequence_for_system_tenant.go (hunk 1 above)
Comment (ajwerner) [reply pkg/upgrade/upgrades/desc_id_sequence_for_system_tenant.go:31]: 🤷

Comment (ajwerner) [reply pkg/upgrade/upgrades/desc_id_sequence_for_system_tenant.go]: Done.

**Comment by ajwerner** [comment]
TFTR!

bors r+

File: pkg/upgrade/upgrades/desc_id_sequence_for_system_tenant.go (hunk 1 above)
Comment (postamar) [reply pkg/upgrade/upgrades/desc_id_sequence_for_system_tenant.go]: Don't get me wrong, it's so obviously inconsequential that I didn't think the comment needed to be prefixed with "nit :".
