### PR TITLE
rpc: Handle closed error

### LINKED ISSUE #77754: rpc: TestHeartbeatHealthTransport failed
rpc.TestHeartbeatHealthTransport [failed](https://teamcity.cockroachdb.com/viewLog.html?buildId=4566826&tab=buildLog) with [artifacts](https://teamcity.cockroachdb.com/viewLog.html?buildId=4566826&tab=artifacts#/) on master @ [231fd420c61e39b6ad08c982c496d82cf1910bc5](https://github.com/cockroachdb/cockroach/commits/231fd420c61e39b6ad08c982c496d82cf1910bc5):

```
=== RUN   TestHeartbeatHealthTransport
    context_test.go:757: rpc error: code = Unknown desc = client cluster ID "5745c6bc-64a8-40f4-9d60-a9dc253c27e8" doesn't match server cluster ID "f8521426-68e9-429d-abd3-99406a9db4de"
--- FAIL: TestHeartbeatHealthTransport (0.05s)
```
<details><summary>Help</summary>
<p>

See also: [How To Investigate a Go Test Failure \(internal\)](https://cockroachlabs.atlassian.net/l/c/HgfXfJgM)
Parameters in this failure:

- TAGS=bazel,gss,deadlock
</p>
</details>
/cc @cockroachdb/server
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*TestHeartbeatHealthTransport.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)
</sub>

Jira issue: CRDB-13752

### LINKED ISSUE #100391: rpc: TestHeartbeatHealthTransport failed
rpc.TestHeartbeatHealthTransport [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_StressBazel/9376853?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_StressBazel/9376853?buildTab=artifacts#/) on release-23.1 @ [5d5abe704b0551556c35d51aa673d3162f493aa8](https://github.com/cockroachdb/cockroach/commits/5d5abe704b0551556c35d51aa673d3162f493aa8):

```
W230401 10:48:57.484263 4298 rpc/context_test.go:1208  [-] 198  close tcp 127.0.0.1:40845 -> 127.0.0.1:53674: use of closed network connection
W230401 10:48:57.484323 4298 rpc/context_test.go:1208  [-] 199  close tcp 127.0.0.1:40845 -> 127.0.0.1:53674: use of closed network connection
W230401 10:48:57.484357 4298 rpc/context_test.go:1208  [-] 200  close tcp 127.0.0.1:40845 -> 127.0.0.1:53674: use of closed network connection
W230401 10:48:57.484413 4298 rpc/context_test.go:1208  [-] 201  close tcp 127.0.0.1:40845 -> 127.0.0.1:53674: use of closed network connection
W230401 10:48:57.484452 4298 rpc/context_test.go:1208  [-] 202  close tcp 127.0.0.1:40845 -> 127.0.0.1:53674: use of closed network connection
W230401 10:48:57.484509 4298 rpc/context_test.go:1208  [-] 203  close tcp 127.0.0.1:40845 -> 127.0.0.1:53674: use of closed network connection
W230401 10:48:57.484547 4298 rpc/context_test.go:1208  [-] 204  close tcp 127.0.0.1:40845 -> 127.0.0.1:53674: use of closed network connection
W230401 10:48:57.484598 4298 rpc/context_test.go:1208  [-] 205  close tcp 127.0.0.1:40845 -> 127.0.0.1:53674: use of closed network connection
W230401 10:48:57.484659 4298 rpc/context_test.go:1208  [-] 206  close tcp 127.0.0.1:40845 -> 127.0.0.1:53674: use of closed network connection
W230401 10:48:57.484713 4298 rpc/context_test.go:1208  [-] 207  close tcp 127.0.0.1:40845 -> 127.0.0.1:53674: use of closed network connection
W230401 10:48:57.484762 4298 rpc/context_test.go:1208  [-] 208  close tcp 127.0.0.1:40845 -> 127.0.0.1:53674: use of closed network connection
W230401 10:48:57.484818 4298 rpc/context_test.go:1208  [-] 209  close tcp 127.0.0.1:40845 -> 127.0.0.1:53674: use of closed network connection
W230401 10:48:57.484882 4298 rpc/context_test.go:1208  [-] 210  close tcp 127.0.0.1:40845 -> 127.0.0.1:53674: use of closed network connection
W230401 10:48:57.484939 4298 rpc/context_test.go:1208  [-] 211  close tcp 127.0.0.1:40845 -> 127.0.0.1:53674: use of closed network connection
W230401 10:48:57.485001 4298 rpc/context_test.go:1208  [-] 212  close tcp 127.0.0.1:40845 -> 127.0.0.1:53674: use of closed network connection
W230401 10:48:57.485079 4298 rpc/context_test.go:1208  [-] 213  close tcp 127.0.0.1:40845 -> 127.0.0.1:53674: use of closed network connection
W230401 10:48:57.485137 4298 rpc/context_test.go:1208  [-] 214  close tcp 127.0.0.1:40845 -> 127.0.0.1:53674: use of closed network connection
W230401 10:48:57.485197 4298 rpc/context_test.go:1208  [-] 215  close tcp 127.0.0.1:40845 -> 127.0.0.1:53674: use of closed network connection
W230401 10:48:57.485260 4298 rpc/context_test.go:1208  [-] 216  close tcp 127.0.0.1:40845 -> 127.0.0.1:53674: use of closed network connection
W230401 10:48:57.485311 4298 rpc/context_test.go:1208  [-] 217  close tcp 127.0.0.1:40845 -> 127.0.0.1:53674: use of closed network connection
W230401 10:48:57.485364 4298 rpc/context_test.go:1208  [-] 218  close tcp 127.0.0.1:40845 -> 127.0.0.1:53674: use of closed network connection
W230401 10:48:57.485425 4298 rpc/context_test.go:1208  [-] 219  close tcp 127.0.0.1:40845 -> 127.0.0.1:53674: use of closed network connection
W230401 10:48:57.485485 4298 rpc/context_test.go:1208  [-] 220  close tcp 127.0.0.1:40845 -> 127.0.0.1:53674: use of closed network connection
W230401 10:48:57.485550 4298 rpc/context_test.go:1208  [-] 221  close tcp 127.0.0.1:40845 -> 127.0.0.1:53674: use of closed network connection
W230401 10:48:57.485609 4298 rpc/context_test.go:1208  [-] 222  close tcp 127.0.0.1:40845 -> 127.0.0.1:53674: use of closed network connection
W230401 10:48:57.485671 4298 rpc/context_test.go:1208  [-] 223  close tcp 127.0.0.1:40845 -> 127.0.0.1:53674: use of closed network connection
W230401 10:48:57.485736 4298 rpc/context_test.go:1208  [-] 224  close tcp 127.0.0.1:40845 -> 127.0.0.1:53674: use of closed network connection
W230401 10:48:57.485806 4298 rpc/context_test.go:1208  [-] 225  close tcp 127.0.0.1:40845 -> 127.0.0.1:53674: use of closed network connection
W230401 10:48:57.485875 4298 rpc/context_test.go:1208  [-] 226  close tcp 127.0.0.1:40845 -> 127.0.0.1:53674: use of closed network connection
W230401 10:48:57.485936 4298 rpc/context_test.go:1208  [-] 227  close tcp 127.0.0.1:40845 -> 127.0.0.1:53674: use of closed network connection
W230401 10:48:57.485999 4298 rpc/context_test.go:1208  [-] 228  close tcp 127.0.0.1:40845 -> 127.0.0.1:53674: use of closed network connection
W230401 10:48:57.486055 4298 rpc/context_test.go:1208  [-] 229  close tcp 127.0.0.1:40845 -> 127.0.0.1:53674: use of closed network connection
W230401 10:48:57.486121 4298 rpc/context_test.go:1208  [-] 230  close tcp 127.0.0.1:40845 -> 127.0.0.1:53674: use of closed network connection
W230401 10:48:57.486257 4298 rpc/context_test.go:1208  [-] 231  close tcp 127.0.0.1:40845 -> 127.0.0.1:53674: use of closed network connection
W230401 10:48:57.486328 4298 rpc/context_test.go:1208  [-] 232  close tcp 127.0.0.1:40845 -> 127.0.0.1:53674: use of closed network connection
W230401 10:48:57.486384 4298 rpc/context_test.go:1208  [-] 233  close tcp 127.0.0.1:40845 -> 127.0.0.1:53674: use of closed network connection
W230401 10:48:57.486446 4298 rpc/context_test.go:1208  [-] 234  close tcp 127.0.0.1:40845 -> 127.0.0.1:53674: use of closed network connection
W230401 10:48:57.486501 4298 rpc/context_test.go:1208  [-] 235  close tcp 127.0.0.1:40845 -> 127.0.0.1:53674: use of closed network connection
W230401 10:48:57.486557 4298 rpc/context_test.go:1208  [-] 236  close tcp 127.0.0.1:40845 -> 127.0.0.1:53674: use of closed network connection
W230401 10:48:57.486616 4298 rpc/context_test.go:1208  [-] 237  close tcp 127.0.0.1:40845 -> 127.0.0.1:53674: use of closed network connection
W230401 10:48:57.486676 4298 rpc/context_test.go:1208  [-] 238  close tcp 127.0.0.1:40845 -> 127.0.0.1:53674: use of closed network connection
W230401 10:48:57.486738 4298 rpc/context_test.go:1208  [-] 239  close tcp 127.0.0.1:40845 -> 127.0.0.1:53674: use of closed network connection
W230401 10:48:57.486797 4298 rpc/context_test.go:1208  [-] 240  close tcp 127.0.0.1:40845 -> 127.0.0.1:53674: use of closed network connection
W230401 10:48:57.486851 4298 rpc/context_test.go:1208  [-] 241  close tcp 127.0.0.1:40845 -> 127.0.0.1:53674: use of closed network connection
W230401 10:48:57.486884 4298 rpc/context_test.go:1208  [-] 242  close tcp 127.0.0.1:40845 -> 127.0.0.1:53674: use of closed network connection
W230401 10:48:57.486918 4298 rpc/context_test.go:1208  [-] 243  close tcp 127.0.0.1:40845 -> 127.0.0.1:53674: use of closed network connection
I230401 10:48:57.495773 4732 2@rpc/context.go:2564  [rnode=1,raddr=127.0.0.1:40845,class=default,rpc] 244  connection is now ready
    context_test.go:1262: close tcp 127.0.0.1:40845->127.0.0.1:53674: use of closed network connection
I230401 10:48:57.496088 4732 rpc/context.go:2302  [rnode=1,raddr=127.0.0.1:40845,class=default,rpc] 245  connection heartbeat loop ended with err: grpc: context canceled [code 1/Canceled]
--- FAIL: TestHeartbeatHealthTransport (0.05s)
```
<p>Parameters: <code>TAGS=bazel,gss,deadlock</code>
</p>
<details><summary>Help</summary>
<p>

See also: [How To Investigate a Go Test Failure \(internal\)](https://cockroachlabs.atlassian.net/l/c/HgfXfJgM)
</p>
</details>
<details><summary>Same failure on other branches</summary>
<p>

- #77754 rpc: TestHeartbeatHealthTransport failed [C-test-failure O-robot T-server-and-security branch-master]
</p>
</details>
/cc @cockroachdb/kv
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*TestHeartbeatHealthTransport.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)
</sub>

Jira issue: CRDB-26406

### PR DESCRIPTION
**Pull request by andrewbaptist**
We close the listener before closing the connection. This can result in a spurious failure due to the Listener also closing our connection.

Epic: none
Fixes: #100391
Fixes: #77754
Informs: #80034

Release note: None

### CODE REVIEW

**Comment by andrewbaptist** [comment]
I fixed the first issue (`conn.Close()` returning `net.ErrClosed`) easily in stress and then hit the second issue cluster ID after a longer stress run (5-10min / 50K iterations). I think the second issue is due to "reusing ports" between test runs but I'm not sure. It has been happening for ~1 year, but very infrequently.

I can run the test for >30min without failure with both of these fixes.

File: pkg/rpc/context_test.go [hunk 1]
```diff
@@ -1272,10 +1274,16 @@ func TestHeartbeatHealthTransport(t *testing.T) {
 		return nil
 	})
 
+	// TODO(baptist): Better understand when this happens. It appears we can get
+	// spurious connections to other tests on a stress run. This has been
+	// happening for a while, but only comes out rarely when this package is
+	// stressed. This test is very aggressive since it is calling GRPCDialNode in
+	// a busy loop for 50ms.
```
Comment (erikgrinaker) [inline pkg/rpc/context_test.go:1281]: I think this is a known problem. Test servers bind to port 0 to let the OS pick a random unused port, but as soon as we close it then a different test can be randomly assigned that very same port number, so if we later try to connect to that port we get unexpected results. This typically causes problems when we attempt to restart a stopped server reusing the same port number it was previously assigned, but someone else bound to it in the meanwhile.

**Review by erikgrinaker — APPROVED** [review]

**Comment by andrewbaptist** [comment]
bors r=erikgrinaker
