### PR TITLE
kvcoord: deflake rangefeed tests

### LINKED ISSUE #156852: kv/kvclient/kvcoord.TestMuxRangeCatchupScanQuotaReleased: TestMuxRangeCatchupScanQuotaReleased failed
kv/kvclient/kvcoord.TestMuxRangeCatchupScanQuotaReleased.TestMuxRangeCatchupScanQuotaReleased [failed](https://mesolite.cluster.engflow.com/invocations/default/faad93fb-e7b3-4597-bd2d-c3baca91d155?testReportRun=1&testReportShard=11&testReportAttempt=1#targets-Ly9wa2cva3Yva3ZjbGllbnQva3Zjb29yZDprdmNvb3JkX3Rlc3Q=) on master @ [8e56ad9c46e544c2ef368e02322d949a03723891](https://github.com/cockroachdb/cockroach/commits/8e56ad9c46e544c2ef368e02322d949a03723891):

```
=== RUN   TestMuxRangeCatchupScanQuotaReleased
    test_log_scope.go:171: test logs captured to: outputs.zip/logTestMuxRangeCatchupScanQuotaReleased646464566
    test_log_scope.go:82: use -show-logs to present logs inline
    test_server_shim.go:141: cluster virtualization disabled in global scope due to issue: #76378 (expected label: C-bug)
    dist_sender_rangefeed_test.go:305: test timed out
    panic.go:615: -- test log scope end --
test logs left over in: outputs.zip/logTestMuxRangeCatchupScanQuotaReleased646464566
--- FAIL: TestMuxRangeCatchupScanQuotaReleased (304.64s)
```

Parameters:
 - <code>attempt=1</code>
 - <code>race=true</code>
 - <code>run=1</code>
 - <code>shard=11</code>
<details><summary>Help</summary>
<p>

See also: [How To Investigate a Go Test Failure \(internal\)](https://cockroachlabs.atlassian.net/l/c/HgfXfJgM)
</p>
</details>
/cc @cockroachdb/kv-triage
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*TestMuxRangeCatchupScanQuotaReleased.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/bazci/githubpost/issues)

</sub>

Jira issue: CRDB-56226

### LINKED ISSUE #157003: kv/kvclient/kvcoord: TestMuxRangeCatchupScanQuotaReleased failed
kv/kvclient/kvcoord.TestMuxRangeCatchupScanQuotaReleased [failed](https://mesolite.cluster.engflow.com/invocations/default/0166fd08-6914-4e4f-b2f9-9da75ca7a0be?testReportRun=1&testReportShard=11&testReportAttempt=1#targets-Ly9wa2cva3Yva3ZjbGllbnQva3Zjb29yZDprdmNvb3JkX3Rlc3Q=) on master @ [20b835654a432e90e997dd12bb28961e52fc0a89](https://github.com/cockroachdb/cockroach/commits/20b835654a432e90e997dd12bb28961e52fc0a89):

```
=== RUN   TestMuxRangeCatchupScanQuotaReleased
    test_log_scope.go:171: test logs captured to: outputs.zip/logTestMuxRangeCatchupScanQuotaReleased2449550052
    test_log_scope.go:82: use -show-logs to present logs inline
    test_server_shim.go:141: cluster virtualization disabled in global scope due to issue: #156327 (expected label: C-bug)
    dist_sender_rangefeed_test.go:305: test timed out
    panic.go:615: -- test log scope end --
test logs left over in: outputs.zip/logTestMuxRangeCatchupScanQuotaReleased2449550052
--- FAIL: TestMuxRangeCatchupScanQuotaReleased (303.79s)
```

Parameters:
 - <code>attempt=1</code>
 - <code>race=true</code>
 - <code>run=1</code>
 - <code>shard=11</code>
<details><summary>Help</summary>
<p>

See also: [How To Investigate a Go Test Failure \(internal\)](https://cockroachlabs.atlassian.net/l/c/HgfXfJgM)
</p>
</details>
/cc @cockroachdb/kv-triage
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*TestMuxRangeCatchupScanQuotaReleased.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/bazci/githubpost/issues)

</sub>

Jira issue: CRDB-56343

### LINKED ISSUE #157064: kv/kvclient/kvcoord: TestRangeFeedMetricsManagement failed
kv/kvclient/kvcoord.TestRangeFeedMetricsManagement [failed](https://mesolite.cluster.engflow.com/invocations/default/813eb1c7-0280-4db8-ada8-5ed1c1ee01f0?testReportRun=2&testReportShard=13&testReportAttempt=1#targets-Ly9wa2cva3Yva3ZjbGllbnQva3Zjb29yZDprdmNvb3JkX3Rlc3Q=) on master @ [ccdd2647944cbbda82017879398e376cb9478363](https://github.com/cockroachdb/cockroach/commits/ccdd2647944cbbda82017879398e376cb9478363):

```
=== RUN   TestRangeFeedMetricsManagement
    test_log_scope.go:171: test logs captured to: outputs.zip/logTestRangeFeedMetricsManagement275544180
    test_log_scope.go:82: use -show-logs to present logs inline
    test_server_shim.go:141: cluster virtualization disabled in global scope due to issue: #156327 (expected label: C-bug)
    test_server_shim.go:594: DRPC is enabled (override by TestingGlobalDRPCOption)
    dist_sender_rangefeed_test.go:561: condition failed to evaluate within 3m45s: from dist_sender_rangefeed_test.go:563: waiting for frontier advance: [/Table/104/1{-/300}@0,0] [/Table/104/1/{300-500}@1762517824.519028645,0] [/Table/104/1/{500-900}@1762517833.239785603,0] [/Table/104/{1/900-2}@0,0]
    panic.go:615: -- test log scope end --
test logs left over in: outputs.zip/logTestRangeFeedMetricsManagement275544180
--- FAIL: TestRangeFeedMetricsManagement (229.77s)
```

Parameters:
 - <code>attempt=1</code>
 - <code>race=true</code>
 - <code>run=2</code>
 - <code>shard=13</code>
<details><summary>Help</summary>
<p>

See also: [How To Investigate a Go Test Failure \(internal\)](https://cockroachlabs.atlassian.net/l/c/HgfXfJgM)
</p>
</details>
/cc @cockroachdb/kv-triage
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*TestRangeFeedMetricsManagement.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/bazci/githubpost/issues)

</sub>

Jira issue: CRDB-56298

### PR DESCRIPTION
**Pull request by stevendanna**
This aims at fixing recent failures in

    TestRangeFeedMetricsManagement
    TestMuxRangeFeedCatchupScanQuotaReleased

A clear root cause was found for the former while the latter appears
to be related to slowdowns as a result of recreating catchup scan iterators
when running under the race-detector.

Fixes #156852
Fixes #157003
Fixes #157064

### CODE REVIEW

**Review by tbg — APPROVED** [review]
> @tbg reviewed 1 of 1 files at r1, 1 of 1 files at r2, 1 of 1 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/157259)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @pav-kv and @sumeerbhola)

___
*[`pkg/kv/kvserver/rangefeed/catchup_scan.go` line 266 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/157259#-OdxYVnuA3wSSpmoFixV:-OdxYVnuA3wSSpmoFixW:ba3gmgc) ([raw file](https://github.com/cockroachdb/cockroach/blob/7b8721859475b6c3d7b6c7efa66bdcab2d8ba5b7/pkg/kv/kvserver/rangefeed/catchup_scan.go#L266)):*
> ```Go
> 				// Fibonacci hash https://probablydance.com/2018/06/16/fibonacci-hashing-the-optimization-that-the-world-forgot-or-a-better-alternative-to-integer-modulo/
> 				simpleHash := (11400714819323198485 * uint64(uintptr(unsafe.Pointer(&iter)))) >> 63
> 				forceRecreateUnderTest = simpleHash == 0
> ```

So this does it 50% of the time? That still seems like a lot.
___
*[`pkg/kv/kvclient/kvcoord/dist_sender_rangefeed_test.go` line 185 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/157259#-OdxWJmDE3ncqsq3-d5r:-OdxWJmDE3ncqsq3-d5s:b-sm5j40) ([raw file](https://github.com/cockroachdb/cockroach/blob/227f59c83000d9e832ac26303945b307a0126364/pkg/kv/kvclient/kvcoord/dist_sender_rangefeed_test.go#L185)):*
> ```Go
> func channelWaitWithTimeout(t *testing.T, ch chan struct{}, errCh chan error) {
> 	t.Helper()
> 	timeOut := testutils.SucceedsSoonDuration()
> ```

:drake-good: :thumbsup: 
___
*[`pkg/kv/kvclient/kvcoord/dist_sender_rangefeed_test.go` line 221 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/157259#-OdxWY2SEtcBA-4USj-T:-OdxWY2SEtcBA-4USj-U:b-bcnhc3) ([raw file](https://github.com/cockroachdb/cockroach/blob/227f59c83000d9e832ac26303945b307a0126364/pkg/kv/kvclient/kvcoord/dist_sender_rangefeed_test.go#L221)):*
> ```Go
> 	startTime := ts.Clock().Now()
> 
> 	kvserver.RangefeedEnabled.Override(
> ```

It is funny. So when rangefeeds are off, we can still do catch up scans? Huh?

**Review by sumeerbhola — APPROVED** [review]
> @sumeerbhola reviewed 1 of 1 files at r1, 1 of 1 files at r2, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/157259)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @pav-kv, @stevendanna, and @tbg)

___
*[`pkg/kv/kvserver/rangefeed/catchup_scan.go` line 266 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/157259#-OdxYVnuA3wSSpmoFixV:-Odxa5ezEjqvpQ8ExF3k:be7kw42) ([raw file](https://github.com/cockroachdb/cockroach/blob/7b8721859475b6c3d7b6c7efa66bdcab2d8ba5b7/pkg/kv/kvserver/rangefeed/catchup_scan.go#L266)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

So this does it 50% of the time? That still seems like a lot.
</blockquote></details>

Change this to 25% via `>> 62`?

Thanks for fixing this.

**Review by stevendanna — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/157259)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @pav-kv and @tbg)

___
*[`pkg/kv/kvclient/kvcoord/dist_sender_rangefeed_test.go` line 221 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/157259#-OdxWY2SEtcBA-4USj-T:-OdxaDZn49TbYhLij-Ip:b-h6fssx) ([raw file](https://github.com/cockroachdb/cockroach/blob/227f59c83000d9e832ac26303945b307a0126364/pkg/kv/kvclient/kvcoord/dist_sender_rangefeed_test.go#L221)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

It is funny. So when rangefeeds are off, we can still do catch up scans? Huh?
</blockquote></details>

Hrm. Actually, while I did observe this error and while adding this did resolve the issue, I think I mis-described the order of operations that must be happening because now that I re-read the code, we do seem to check this before we the catch up scan should be able to start.  I'll take a second look.

**Review by stevendanna — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/157259)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @pav-kv and @tbg)

___
*[`pkg/kv/kvclient/kvcoord/dist_sender_rangefeed_test.go` line 221 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/157259#-OdxWY2SEtcBA-4USj-T:-OdxeXk74Wq8fq1jZO9d:b-8znnxj) ([raw file](https://github.com/cockroachdb/cockroach/blob/227f59c83000d9e832ac26303945b307a0126364/pkg/kv/kvclient/kvcoord/dist_sender_rangefeed_test.go#L221)):*
<details><summary><i>Previously, stevendanna (Steven Danna) wrote…</i></summary><blockquote>

Hrm. Actually, while I did observe this error and while adding this did resolve the issue, I think I mis-described the order of operations that must be happening because now that I re-read the code, we do seem to check this before we the catch up scan should be able to start.  I'll take a second look.
</blockquote></details>

I am not 100% sure, but one possibility is that some ranges are starting their catch up scan while others are hitting the error. One way that could happen is if the span configuration attach to our replica either hasn't been explicitly set et or because we are sharing a range with a span that has rangefeeds enabled via zone configuration:

```
func (r *Replica) isRangefeedEnabledRLocked() (ret bool) {
	if !r.mu.spanConfigExplicitlySet {
		return true
	}
	return r.mu.conf.RangefeedEnabled
}
```

**Review by wenyihu6 — COMMENTED** [review]
Thanks for looking into this! Is `TestRangeFeedMetricsManagement` flaky now just because catch up scans are now slower with the re-opening iterators? 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/157259#-:-OdxiuOz9GZkpGX8zgyP:b-90smz8)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @pav-kv and @tbg)

___
*[`pkg/kv/kvclient/kvcoord/dist_sender_rangefeed_test.go` line 227 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/157259#-OdxigGV-boADNorPS1d:-OdxigGW4e1N6qsAE5Cl:bgmywq0) ([raw file](https://github.com/cockroachdb/cockroach/blob/227f59c83000d9e832ac26303945b307a0126364/pkg/kv/kvclient/kvcoord/dist_sender_rangefeed_test.go#L227)):*
> ```Go
> 	// test cluster nodes.
> 	sqlDB.ExecMultiple(t,
> 		`ALTER DATABASE defaultdb CONFIGURE ZONE USING num_replicas = 1`,
> ```

Why doesn't cluster setting work? Is it because it needs rangefeed to set cluster settings or something else?

File: pkg/kv/kvserver/rangefeed/catchup_scan.go [hunk 1]
```diff
@@ -253,6 +256,16 @@ func (i *CatchUpSnapshot) CatchUpScan(
...
 			// recreateIter => now is initialized.
 			var now crtime.Mono
+
+			// Under race tests we want to recreate the iterator more often. Doing
+			// this on every iteration proved a bit slow.
+			forceRecreateUnderTest := false
+			if util.RaceEnabled {
+				// Fibonacci hash https://probablydance.com/2018/06/16/fibonacci-hashing-the-optimization-that-the-world-forgot-or-a-better-alternative-to-integer-modulo/
+				simpleHash := (11400714819323198485 * uint64(uintptr(unsafe.Pointer(&iter)))) >> 63
+				forceRecreateUnderTest = simpleHash == 0
```
Comment (pav-kv) [inline pkg/kv/kvserver/rangefeed/catchup_scan.go]: This looks sophisticated. Would something like `rand % 2 == 0` do the job, or we want the property that one `iter` is either always recreated, or always not?

Comment (pav-kv) [reply pkg/kv/kvserver/rangefeed/catchup_scan.go]: If we need this decision somewhat "reproducible", using `iter` does not achieve that because it's also random (and perhaps even can change due to runtime moving objects in memory; not sure about that part).

If we absolutely need this trick though, a comment would be good (and/or a helper that wraps this trick).

Comment (pav-kv) [reply pkg/kv/kvserver/rangefeed/catchup_scan.go]: From https://pkg.go.dev/unsafe#Pointer:

> A uintptr is an integer, not a reference. Converting a Pointer to a uintptr creates an integer value with no pointer semantics. Even if a uintptr holds the address of some object, the garbage collector will not update that uintptr's value if the object moves, nor will that uintptr keep the object from being reclaimed.

Reading between the lines, it seems like the `uintptr` value can change even if `&iter` is the same.

Comment (pav-kv) [reply pkg/kv/kvserver/rangefeed/catchup_scan.go]: So the semantics here are: when we decide whether `&iter` recreated, this decision is sticky. But not guaranteed because the runtime can fiddle with the `uintptr`? Which is fine if it happens occasionally?

Contrasting to `rand % 2 == 0` <- that would recreate many times in all cases.

Comment (stevendanna) [reply pkg/kv/kvserver/rangefeed/catchup_scan.go]: I agree the previous semantics were maybe confusing. I tested this locally with just a integer modulo to do this every 10 keys rather than every key and it seems to be OK on these tests at least. If we keep seeing flakes we can perhaps move this to something simpler:

- A bool that forces us to recreate the iterator at least once under race the first time through this code and then just falls back to the normal behavior.

**Review by stevendanna — COMMENTED** [review]
>  Is `TestRangeFeedMetricsManagement` flaky now just because catch up scans are now slower with the re-opening iterators?

I put my best theory in the commit message for my update to that test:

```
    This test failed to enable rangefeeds. One may ask why this ever worked at all.
    My belief is that when the test was faster, the catch-up scans may have been
    completing before all of the relevant ranges had explicitly set span
    configuration. When no explicit span configuration is in place, we default to
    assuming that the range has rangefeeds enabled via span configuration. When the
    test is too slow, some ranges then observe that they _do not_ have rangefeeds
    enabled via span configuration and fall back to the cluster setting.
```

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/157259#-:-OdyPxAbCeDQoB-K3lWN:b-1237k5)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @pav-kv, @sumeerbhola, @tbg, and @wenyihu6)

___
*[`pkg/kv/kvserver/rangefeed/catchup_scan.go` line 266 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/157259#-OdxYVnuA3wSSpmoFixV:-OdyQBdGAF9ugOSYAz6W:bd7umkp) ([raw file](https://github.com/cockroachdb/cockroach/blob/7b8721859475b6c3d7b6c7efa66bdcab2d8ba5b7/pkg/kv/kvserver/rangefeed/catchup_scan.go#L266)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

Change this to 25% via `>> 62`?

Thanks for fixing this.
</blockquote></details>

I changed this to every 10 keys.
___
*[`pkg/kv/kvclient/kvcoord/dist_sender_rangefeed_test.go` line 227 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/157259#-OdxigGV-boADNorPS1d:-OdySpSMBHvt8Dx__uPI:b-qj4dt5) ([raw file](https://github.com/cockroachdb/cockroach/blob/227f59c83000d9e832ac26303945b307a0126364/pkg/kv/kvclient/kvcoord/dist_sender_rangefeed_test.go#L227)):*
<details><summary><i>Previously, wenyihu6 (Wenyi Hu) wrote…</i></summary><blockquote>

Why doesn't cluster setting work? Is it because it needs rangefeed to set cluster settings or something else?
</blockquote></details>

Unintended change. I started trying to get these tests to work with secondary tenants and then decided to punt that to another day.

**Review by sumeerbhola — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/157259)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @pav-kv, @stevendanna, @tbg, and @wenyihu6)

___
*[`pkg/kv/kvserver/rangefeed/catchup_scan.go` line 266 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/157259#-OdxYVnuA3wSSpmoFixV:-Odyd_Te-KHLlISoa29j:b-3b1ypr) ([raw file](https://github.com/cockroachdb/cockroach/blob/7b8721859475b6c3d7b6c7efa66bdcab2d8ba5b7/pkg/kv/kvserver/rangefeed/catchup_scan.go#L266)):*
<details><summary><i>Previously, stevendanna (Steven Danna) wrote…</i></summary><blockquote>

I changed this to every 10 keys.
</blockquote></details>

Some test have very few keys. And having those tests be randomly covered with immediate restarts was very helpful in finding various corner cases. The iterator hashing has that nice property.

**Review by tbg — APPROVED** [review]
> @tbg reviewed 2 of 2 files at r5, 1 of 1 files at r6, 1 of 1 files at r7, 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/157259)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @pav-kv and @wenyihu6)

File: pkg/kv/kvserver/rangefeed/catchup_scan.go (hunk 1 above)
Comment (pav-kv) [reply pkg/kv/kvserver/rangefeed/catchup_scan.go]: I'm good with either approach, just spelling out the semantics would be good. The pointer trick seems cool: if you end up with it, consider factoring out into a func with a comment.

Disclaimer: haven't looked at the code changes after the last time.

**Review by stevendanna — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/157259)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @pav-kv, @sumeerbhola, @tbg, and @wenyihu6)

___
*[`pkg/kv/kvserver/rangefeed/catchup_scan.go` line 266 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/157259#-OdxYVnuA3wSSpmoFixV:-OdzYdigEhoZJT8d-RRW:bb9d1io) ([raw file](https://github.com/cockroachdb/cockroach/blob/7b8721859475b6c3d7b6c7efa66bdcab2d8ba5b7/pkg/kv/kvserver/rangefeed/catchup_scan.go#L266)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

Some test have very few keys. And having those tests be randomly covered with immediate restarts was very helpful in finding various corner cases. The iterator hashing has that nice property.
</blockquote></details>

OK. I've brought this back, but moved it into a helper method and added come comments per @pav-kv's suggestion.

File: pkg/kv/kvserver/rangefeed/catchup_scan.go [hunk 2]
```diff
@@ -253,6 +255,22 @@ func (i *CatchUpSnapshot) CatchUpScan(
 			recreateIter := false
 			// recreateIter => now is initialized.
 			var now crtime.Mono
+
+			// Under race tests we want to recreate the iterator more often to
+			// increase test coverage of this code. Doing this on every iteration
+			// proved a bit slow.
+			forceRecreateUnderTest := false
+			if util.RaceEnabled {
+				// Hash the pointer of our iterator into the range [0, 4] and only
```
Comment (pav-kv) [inline pkg/kv/kvserver/rangefeed/catchup_scan.go]: nit: `[0,4)` or `[0,3]`

Optionally, remove one step that needs comprehending, and say that the probability is 1/4 (for a fixed `iter`).

**Review by pav-kv — APPROVED** [review]
Thank you!

**Comment by pav-kv** [comment]
Please tag the fixed issues in the desc, for posterity etc.

File: pkg/kv/kvserver/rangefeed/catchup_scan.go (hunk 1 above)
Comment (sumeerbhola) [reply pkg/kv/kvserver/rangefeed/catchup_scan.go]: > and perhaps even can change due to runtime moving objects in memory; not sure about that part

btw, golang does not have a moving garbage collector, and there was some discussion internally (can't find it now) which concluded that that aspect can likely never change.

**Review by sumeerbhola — APPROVED** [review]
:lgtm: 

> @sumeerbhola reviewed 1 of 3 files at r12.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/157259#-:-Oe1XFgbE7ayqyWh06VZ:bg7igkv)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @pav-kv, @stevendanna, @tbg, and @wenyihu6)

**Comment by stevendanna** [comment]
TFTR!

bors r=pav-kv,tbg,sumeerbhola
