### PR TITLE
changefeedccl: remove extra characters from topic names

### LINKED ISSUE #148181: Using double quotes in changefeed query results in unicode passed to the topic name in the sink
**Describe the problem**

Please describe the issue you observed, and any steps we can take to reproduce it:
https://cockroachdb.zendesk.com/agent/tickets/27428

When creating a changefeed to kafka using a field or table that has capital letters, you must surround the table/field in double quotes ("), but cockroachDB is converting this to unicode when it creates the topic in kafka. So for instance this query from the customer (redacted):

```
CREATE CHANGEFEED
	INTO 'external://kafka_cdc''
	WITH diff,
		full_table_name,
		on_error=pause,
		updated,
		envelope=wrapped,
		initial_scan=no
	AS SELECT *,
		"SomeField"->>'PropA' AS "PropA",
		"SomeField"->>'prop_b' AS "PropB"
	FROM public.mytable;
```

Results in the topic name:
`myprefix.mydb.myschema._u0022_mytable_u0022_`

**To Reproduce**

I was not able to replicate using a field name, but I could replicate using a table name. I set up local instances of cockroach and kafka, created a table with capital letters, and then set up a changefeed using the following query:

```
CREATE CHANGEFEED
FOR defaultdb."MyTable"
INTO 'kafka://localhost:9092'
WITH diff,
full_table_name,
on_error=pause,
updated,
envelope=wrapped;
```

The resulting message was:
`NOTICE: changefeed will emit to topic defaultdb.public.u0022_MyTable_u0022`

If possible, provide steps to reproduce the behavior:

1. Set up CockroachDB cluster (can be single node)
2. Set up a kafka sink
3. Create a table with capital letters in the name
4. Set up a changefeed wrapping the table name in double quotes. Example:
```
CREATE CHANGEFEED
FOR defaultdb."MyTable"
INTO 'kafka://localhost:9092'
WITH diff,
full_table_name,
on_error=pause,
updated,
envelope=wrapped;
```

**Expected behavior**
The topic in kafka should just be 'MyTable' but is instead 'u0022_MyTable_u0022'

**Environment:**
 - The customer is on v24.3.12, I tested on 24.3.11.
 - Server OS: Mac OSX
 - I used cockroach sql, do not know what the client is using.

**Additional context**
What was the impact? Incorrect topic name in kafka, operator inconvenience.

Having to surround table/field names with capital letters is a quirk of postgresql. If you do not do it, it converts the value to lowercase by default and will not properly match on the field/table.

### PR DESCRIPTION
**Pull request by aerfrei**
Previously, when creating topic names, we would include quotes
around identifiers that included capital letters resulting in
some unexpected topic names. We removed this behavior from when
we render table names as strings.

Epic: none
Fixes: https://github.com/cockroachdb/cockroach/issues/148181

Release note (sql change): Fix a bug where extra quotes or escaped
quote characters would be added to topic names in changefeeds.

### CODE REVIEW

File: pkg/ccl/changefeedccl/changefeed_test.go [hunk 1]
```diff
@@ -788,6 +788,78 @@ func TestChangefeedBasicConfluentKafka(t *testing.T) {
...
+		})
+	}
+
+	cdcTest(t, testFn)
+}
+
+// TestChangefeedQuotedIdentifiersKafkaTopic is similar to
+// TestChangefeedQuotedTableNameKafkaTopic, but for quoted identifiers
+// in the SELECT clause instead of the table name.
+func TestChangefeedQuotedIdentifiersKafkaTopic(t *testing.T) {
```
Comment (asg0451) [inline pkg/ccl/changefeedccl/changefeed_test.go]: did this used to be an issue? i just tested manually on 25.2 and didnt see any weird quotes

```

CREATE TABLE "T3" ("A" string);
INSERT INTO "T3" VALUES ('hi');
CREATE CHANGEFEED FOR "T3";
> {"key":"[1086210902574137345]","table":"T3","value":"{\"after\": {\"A\": \"hi\", \"rowid\": 1086210902574137345}}"}
CREATE CHANGEFEED AS SELECT 1 AS "W" FROM "T3";
> {"key":"[1086210902574137345]","table":"T3","value":"{\"W\": 1}"}

```

File: pkg/ccl/changefeedccl/changefeed_stmt.go [hunk 2]
```diff
@@ -1745,7 +1745,7 @@ func getQualifiedTableName(
 	if err != nil {
 		return "", err
 	}
-	return tbName.String(), nil
+	return tree.AsStringWithFlags(&tbName, tree.FmtBareIdentifiers), nil
```
Comment (asg0451) [inline pkg/ccl/changefeedccl/changefeed_stmt.go]: might be worth making a cluster setting to disable this change in behaviour for a version or two because it's a breaking change.

**Review by asg0451 — CHANGES_REQUESTED** [review]

File: pkg/ccl/changefeedccl/changefeed_test.go (hunk 1 above)
Comment (aerfrei) [reply pkg/ccl/changefeedccl/changefeed_test.go]: Not that I saw. This is what was described in the ticket though. In the ticket it said they couldn't reproduce and I wasn't able to either. Seems like it couldn't hurt to have the test anyway though.

File: pkg/ccl/changefeedccl/changefeed_stmt.go (hunk 2 above)
Comment (aerfrei) [reply pkg/ccl/changefeedccl/changefeed_stmt.go]: I wanted to ask you about this. That sounds like a good approach. Would this be off by default?

Comment (asg0451) [reply pkg/ccl/changefeedccl/changefeed_stmt.go]: yeah -- default to the new behaviour and let ppl disable it if they need to.

File: pkg/ccl/changefeedccl/changefeed_test.go [hunk 3]
```diff
@@ -788,6 +788,78 @@ func TestChangefeedBasicConfluentKafka(t *testing.T) {
...
+		defer closeFeed(t, foo)
+
+		// The topic name should be d.public.MyTable and not d.public._u0022_MyTable_u0022_
+		// or d.public."MyTable".
+		assertPayloads(t, foo, []string{
+			`d.public.MyTable: [0]->{"after": {"a": 0, "b": "updated"}, "before": null}`,
+		})
+	}
+
+	cdcTest(t, testFn)
```
Comment (KeithCh) [inline pkg/ccl/changefeedccl/changefeed_test.go:812]: Add `feedTestForceSink("kafka")`?

File: pkg/ccl/changefeedccl/changefeed_stmt.go [hunk 4]
```diff
@@ -73,6 +73,14 @@ var featureChangefeedEnabled = settings.RegisterBoolSetting(
 	featureflag.FeatureFlagEnabledDefault,
 	settings.WithPublic)
 
+var featureChangefeedBareTableNames = settings.RegisterBoolSetting(
+	settings.ApplicationLevel,
+	"feature.changefeed.bare_table_names",
```
Comment (rharding6373) [inline pkg/ccl/changefeedccl/changefeed_stmt.go]: The convention is to end the setting name in ".enabled" for bool settings (the linter will probably complain about this).

Is there a reason to begin the cluster setting with "feature.", other than that the previous setting in this file does? The previous setting seems like a special case. Usually we start all changefeed-specific settings with "changefeed."

File: pkg/ccl/changefeedccl/changefeed_stmt.go [hunk 5]
```diff
@@ -73,6 +73,14 @@ var featureChangefeedEnabled = settings.RegisterBoolSetting(
...
+	"set to true to use bare table names in changefeed topics, false to use quoted table names; default is true",
+	true,
+	settings.WithPublic,
```
Comment (rharding6373) [inline pkg/ccl/changefeedccl/changefeed_stmt.go]: Why do we want to make this setting public?

File: pkg/ccl/changefeedccl/changefeed_test.go (hunk 3 above)
Comment (KeithCh) [inline pkg/ccl/changefeedccl/changefeed_test.go:812]:
```suggestion
	cdcTest(t, testFn, feedTestForceSink("kafka"))
```

Comment (asg0451) [reply pkg/ccl/changefeedccl/changefeed_test.go:812]: in fact since this happens in other sinks too, lets leave it to use them all and change the test name to reflect that

also you'll need to opt out of metamorphic enriched tests if webhook because that stuff doesnt work right with families currently. see https://github.com/cockroachdb/cockroach/blob/09a530f3c063bb53552995a587c57c2786399471/pkg/ccl/changefeedccl/changefeed_test.go#L2073 for example

Comment (aerfrei) [reply pkg/ccl/changefeedccl/changefeed_test.go:812]: I'll rename the test but I think this test is useful for all sinks and the behavior changes for all sinks. For webhook, for example, this topic will now show as d.public.MyTable instead of d.public."MyTable".

Comment (aerfrei) [reply pkg/ccl/changefeedccl/changefeed_test.go:812]: @asg0451 These don't have column families if I'm not mistaken and both are not forcing the enriched envelope because of wrapped envelope and cdc queries.

Comment (asg0451) [reply pkg/ccl/changefeedccl/changefeed_test.go:812]: ah yep you're right. could you actually not specify `envelope=wrapped` so it does run sometimes? thx

Comment (KeithCh) [reply pkg/ccl/changefeedccl/changefeed_test.go:812]: ~Nit: Would it more accurate to remove any "topic" references from this PR then? Since webhooks for example don't have topics.~

Comment (KeithCh) [reply pkg/ccl/changefeedccl/changefeed_test.go:812]: ~e.g. `TestChangefeedQuotedTableNameTopicName`-> `TestChangefeedQuotedTableName`~

Comment (asg0451) [reply pkg/ccl/changefeedccl/changefeed_test.go:812]: webhook does have topics. they get put into the msg body via `topic_in_value`

Comment (aerfrei) [reply pkg/ccl/changefeedccl/changefeed_test.go:812]: This seems to break when we metamorphically apply enriched. Seems to not output the full table name. It did that even when the table name was normal (no capitals or quotes). This isn't a known limitation of the metamorphic testing, is it?

Comment (aerfrei) [reply pkg/ccl/changefeedccl/changefeed_test.go:812]: I think the fact that we take the table name instead of the topic name for enriched envelopes means this will not be compatible. Should we generally opt out of metamorphically testing when full_table_name is specified? For now I'm going to add a manual opt out of metamorphic testing when it's a webhook sink.

Comment (asg0451) [reply pkg/ccl/changefeedccl/changefeed_test.go:812]: that sounds right to me, thanks

File: pkg/ccl/changefeedccl/changefeed_stmt.go [hunk 6]
```diff
@@ -73,6 +73,12 @@ var featureChangefeedEnabled = settings.RegisterBoolSetting(
 	featureflag.FeatureFlagEnabledDefault,
 	settings.WithPublic)
 
+var featureChangefeedBareTableNames = settings.RegisterBoolSetting(
```
Comment (asg0451) [inline pkg/ccl/changefeedccl/changefeed_stmt.go]: pls put this in changefeedbase/settings.go

**Review by asg0451 — APPROVED** [review]

File: pkg/ccl/changefeedccl/changefeed_stmt.go (hunk 6 above)
Comment (andyyang890) [reply pkg/ccl/changefeedccl/changefeed_stmt.go]: pls also strip the `featureChangefeed` from the var name, maybe `useBareTableNames` instead

**Comment by aerfrei** [comment]
bors r=asg0451

**Comment by aerfrei** [comment]
bors r=asg0451

**Comment by rharding6373** [comment]
[Team meeting]: The fix is potentially a breaking change, so we're not planning on backporting it at this time.
