### PR TITLE
sql: fix left semi and left anti virtual lookup joins

### LINKED ISSUE #88096: sql: query planning/execution correctness bug on a vtable anti join
Solution needed for  #88061.

**Describe the problem**

It's a compound problem:
- PostgreSQL and CockroachDB return different results on a simple query containing a correlated join on a vtable;
- CockroachDB also *returns inconsistent results* depending on which predicate is added to the query, where PostgreSQL would return the same results in any case.

Close inspection of the query plan suggest that the `virtual table lookup join (anti)` may be inverting its boolean predicate condition.

**How to reproduce**

After initial:
```sql
create type mytype as enum('hello');
```

Crdb returns conflicting results on the following queries:

```sql
SELECT *
  FROM pg_type AS t
 WHERE NOT EXISTS(SELECT 1 FROM pg_type AS el WHERE el.oid = t.typelem AND el.typarray = t.oid)
   AND t.typname LIKE 'myt%'
```

(here, the output is correct)

and
```sql
SELECT *
  FROM pg_type AS t
 WHERE t.typrelid = 0
   AND NOT EXISTS(SELECT 1 FROM pg_type AS el WHERE el.oid = t.typelem AND el.typarray = t.oid)
   AND t.typname LIKE 'myt%'
```

(here, the output is incorrect)

In PostgreSQL, both queries return the same output, that of the first query above.

This suggests that the query plan for the 2nd query is incorrect.

cc @mgartner for triage.

Jira issue: CRDB-19682

### LINKED ISSUE #91012: sql/opt: incorrect query results with virtual table lookup semi join
**Describe the problem**

There's a problem that seems to happen when a virtual table lookup semi join is planned. See below.

**To Reproduce**

Start a fresh cluster, then:
```
-- setup
CREATE TABLE b (id INT, a_id INT);

root@localhost:26257/defaultdb> 
SELECT
  count(*)
FROM
  pg_class AS t INNER JOIN pg_attribute AS a ON t.oid = a.attrelid
WHERE
  a.attnotnull = 'f'
  AND a.attname = 'a_id'
  AND t.relname = 'b'
  AND a.atttypid
    IN (
        SELECT
          oid
        FROM
          pg_type
        WHERE
          typname = ANY (ARRAY['int8'])
      );
  count
---------
      0
(1 row)
```

If you force a hash join, then a count of 1 is returned.
```
root@localhost:26257/defaultdb> 
SELECT
  count(*)
FROM
  pg_class AS t
  INNER HASH JOIN pg_attribute AS a ON t.oid = a.attrelid
WHERE
  a.attnotnull = 'f'
  AND a.attname = 'a_id'
  AND t.relname = 'b'
  AND a.atttypid
    IN (
        SELECT
          oid
        FROM
          pg_type
        WHERE
          typname = ANY (ARRAY['int8'])
      );
  count
---------
      1
(1 row)
```

**Expected behavior**
The query should return a count of 1.

**Environment:**
Reproduced on v22.2.0-beta.2 and v22.1.8.

### PR DESCRIPTION
**Pull request by yuzefovich**
Epic: CRDB-23454

This commit fixes the execution of the left semi and left anti virtual
lookup joins. The bug was that we forgot to project away the looked up
columns (coming from the "right" side) which could then lead to wrong
columns being used higher up the tree. The bug was introduced during
22.1 release cycle where we added the optimizer support for generating
plans that could contain left semi and left anti virtual lookup joins.
This commit fixes that issue as well as the output columns of such joins
(I'm not sure whether there is a user facing impact of having incorrect
"output columns").

Additionally, this commit fixes the execution of these virtual lookup
joins to correctly return the input row only once. Previously, for left
anti joins we'd be producing an output row if there was a match (which
is wrong), and for both left semi and left anti we would emit an output
row every time there was a match (but this should be done only once).
(Although I'm not sure whether it is possible for virtual indexes to
result in multiple looked up rows.)

Also, as a minor simplification this commit makes it so that the output
rows are not added into the row container for left semi and left anti
and the container is not instantiated at all.

Fixes: #91012.
Fixes: #88096.

Release note (bug fix): CockroachDB previously could incorrectly
evaluate queries that performed left semi and left anti "virtual lookup"
joins on tables in `pg_catalog` or `information_schema`. These join types
can be planned when a subquery is used inside of a filter condition. The
bug was introduced in 20.2.0 and is now fixed.

### CODE REVIEW

**Comment by yuzefovich** [comment]
For context, #76697 is where we added the support for semi, anti, and left outer joins in the optimizer.

Feedback on the release note would be especially helpful to make it more useful for the end users to understand if they are affected.

Also I took the liberty and left a TODO for Marcus, I hope you don't mind 😃

**Comment by rafiss** [comment]
idea for a release note:

> CockroachDB previously could incorrectly evaluate queries that performed left semi and left anti "virtual lookup" joins on tables in pg_catalog or information_schema. These join types can be planned when a subquery is used inside of a filter condition. The bug was introduced in 22.1.0 and is now fixed.

I don't think we need too many details, since the release note in the docs will link to the PR for anyone who is interested in more.

**Comment by yuzefovich** [comment]
Included the fix to #88096 as well as the release note as Rafi suggested (thanks!).

RFAL.

**Review by ajwerner — COMMENTED** [review]
~~While you're here, I just wrote a head-scratching query while trying to demo something to @dikshant. This query should fail with the below error, but instead it succeeds. Wanna add it to this logictest with the expected error?~~

```
ERROR: column "oid" does not exist
SQLSTATE: 42703
```

```sql
SELECT *
  FROM pg_class
 WHERE oid
       IN (
            SELECT oid
              FROM pg_index
             WHERE indrelid
                   IN (SELECT oid FROM pg_class WHERE relname = 'foo')
        );
 ```
 
 edit: the above query is weird and I'm wrong.

**Comment by rafiss** [comment]
I'm missing something - why is an error expected? Seems like that query works fine on postgres.

**Comment by ajwerner** [comment]
Oh gosh correlated subqueries are confusing. `oid` here is from the outer query. Ignore me. I'm sorry.

**Review by msirek — APPROVED** [review]
Looks good. Nice fix!

> Reviewed 3 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/92713#-:-NIEpjDx0lM0NPQvtlcn:bieurhr)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @mgartner)

**Comment by yuzefovich** [comment]
TFTR!

bors r+

File: pkg/sql/opt/xform/join_funcs.go [hunk 1]
```diff
@@ -292,6 +292,7 @@ func (c *CustomFuncs) GenerateLookupJoins(
 //
 // It should be possible to support semi- and anti- joins. Left joins may be
 // possible with additional complexity.
+// TODO(mgartner): update this comment.
```
Comment (mgartner) [inline pkg/sql/opt/xform/join_funcs.go:295]: Ack. Though this has nothing to do with lookup joins on virtual tables - this rule is for lookup joins involving virtual computed columns.

**Comment by mgartner** [comment]
> For context, https://github.com/cockroachdb/cockroach/pull/76697 is where we added the support for semi, anti, and left outer joins in the optimizer.

I don't think that PR is related - it has to do with virtual computed columns, not virtual indexes. So this bug might be present in versions older than 22.1.

File: pkg/sql/opt/xform/join_funcs.go (hunk 1 above)
Comment (mgartner) [reply pkg/sql/opt/xform/join_funcs.go:295]: Addressed here: https://github.com/cockroachdb/cockroach/pull/93042

**Comment by yuzefovich** [comment]
Thanks Marcus for the comments. Indeed, I think you're right - I tried reproductions from both issues on 21.2.17, and both resulted in incorrect output. Now I believe that the bugs date back to 20.2 (#48226 which introduced the support for virtual lookup joins) since the corresponding optimizer changes were merged in 2019 (#38625). Is it worth opening a docs issue to update the release note?

**Comment by yuzefovich** [comment]
Filed https://github.com/cockroachdb/docs/issues/15753 and https://github.com/cockroachdb/docs/issues/15755.
