### PR TITLE
distsql: fix recently introduced leak of CancelFunc

### LINKED ISSUE #149658: sql: context.CancelFunc 'leak' causes memory leak
**Describe the problem**

In drt-chaos, we see context.WithCancel accounting for large portion of the `inuse_space` profile:

Image

My strong suspicion is that this is the result of this change:

https://github.com/cockroachdb/cockroach/pull/143990

which creates a CancelFunc but doesn't call it, resulting in the child context being retained (output from `grf`):

```
----------------------------------------------------------+-------------
      flat  flat%   sum%        cum   cum%   calls calls% + context
----------------------------------------------------------+-------------
                                       624836.51kB   100% |   c. (*context.cancelCtx)
624947.97kB 19.96% 19.96% 625028.20kB 19.97%                | children. (map[context.canceler]struct {})
----------------------------------------------------------+-------------
```

I think the `go vet` linter doesn't catch this because we _also_ squirrel away a reference to the CancelFunc in the stopper itself so we haven't _technically_ leaked it.

Jira issue: CRDB-52271

### PR DESCRIPTION
**Pull request by yuzefovich**
In 27a65c961b55b2c3639828692b144e67ffc16b06 we introduced the logic to make sure that remote flows respect the quiesce signal. However, we consciusly ignored the returned CancelFunc since the lifetime of the context is non-trivial. This introduced a leak of that CancelFunc since we keep the reference to it in the stopper even when the flow exits, so every time a remote flow runs on a node, the leak would slowly grow.

This leak is now fixed by ensuring the cancellation function is always called. This is achieved by passing the function as another thing to do on the "flow cleanup" (we already always need to close the reserved memory account, so we have the necessary infrastructure set up).

Fixes: #149658.

Release note (bug fix): In 25.1.8, 25.2.1, 25.2.2, and 25.3 betas, a slow memory leak was introduced that would accumulate whenever a node executes a part of the distributed plan (the gateway node of the plan is not affected). The leak can only be mitigated by restarting the node and is now fixed.

### CODE REVIEW

File: pkg/sql/distsql/server.go [hunk 1]
```diff
@@ -301,18 +305,27 @@ func (ds *ServerImpl) setupFlow(
 			onFlowCleanupEnd = func(ctx context.Context) {
 				localEvalCtx.Txn = origTxn
 				reserved.Close(ctx)
+				if onFlowCleanup != nil {
+					onFlowCleanup()
+				}
```
Comment (mgartner) [inline pkg/sql/distsql/server.go]: nit: you could make these blocks 1-liners with something like:

```go
type flowCleanupFn func()

func (f flowCleanupFn) Do() {
    if f != nil {
        f()
    }
}
```

**Review by mgartner — APPROVED** [review]
Nice find!

File: pkg/sql/distsql/server.go (hunk 1 above)
Comment (yuzefovich) [reply pkg/sql/distsql/server.go]: Nice, done.

**Review by yuzefovich — COMMENTED** [review]
All credit goes to @stevendanna :smiley: 

TFTR!

bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/149800#-:-OUpUj9QB9wp_3dBJOG4:b-be1y5q)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @mgartner and @michae2)
