### PR TITLE
ui: fix metric load

### LINKED ISSUE #45364: ui: graphs no longer auto-update
**Describe the problem**

The `metrics/overview/cluster` page "Overview Dashboard" does not update graphs automatically.

I also created a graph on the Custom Chart Page. It did not automatically update with data over time.

**Expected behavior**
I expect these graphs to update with data automatically as time passes. (under a minute).

### PR DESCRIPTION
**Pull request by vladlos**
adjusted calculation of scale and `key` to fix performance and refresh issues on charts that generated by link

Resolves: #45364, #44836 

Release note(ui): none

### CODE REVIEW

File: pkg/ui/src/views/cluster/containers/timescale/index.tsx [hunk 1]
```diff
@@ -108,8 +108,13 @@ class TimeScaleDropdown extends React.Component<TimeScaleDropdownProps, {}> {
     // If the timescale extends into the future then fallback to a default
     // timescale. Otherwise set the key to "Custom" so it appears correctly.
     if (!windowEnd || windowEnd > moment().subtract(currentScale.windowValid)) {
-      if (_.find(timewindow.availableTimeScales, { windowSize: { _data: windowSize._data } } as any)) {
-        selected = (_.find(timewindow.availableTimeScales, { windowSize: { _data: windowSize._data } } as any));
+      const size = { windowSize: { _data: windowSize._data } } ;
+      if (_.find(timewindow.availableTimeScales, size as any)) {
+        const data = {
+          ..._.find(timewindow.availableTimeScales, size as any),
```
Comment (nathanstilwell) [inline pkg/ui/src/views/cluster/containers/timescale/index.tsx]: As a nit pick, it seems like you could capture `_.find(timewindow.availableTimeScales, size as any)` in a variable since you are referencing it twice. It might also help the readability in using the spread operator,

```js
const availableTimeScaleSize = _.find(timewindow.availableTimeScales, size as any);
const timeScaleKey = key: _.findKey(timewindow.availableTimeScales, size as any);

if (availableTimeScaleSize) {
  const data = {
    ...availableTimeScaleSize,
    key: timeScaleKey,
  };
  selected = data;
}

**Review by nathanstilwell — APPROVED** [review]
I only left a single nitpicky comment about readability, but it dawns on my that this code is pretty complex and takes time to wrap my head around. In future I would like to see a description of the motivation of the fix in the PR description. I appreciate that the issue is linked, but it would really help in reviewing if there was more assistance in framing the problem and then speaking to the solution for code as terse as this.

I also fully appreciate that there is a test! Thank you for that.
