### PR TITLE
builtins: fix possible out of bounds in regexp_replace

### LINKED ISSUE #51289: Regular expression in REGEXP_REPLACE() can crash the server
**Describe the problem**

I can write a regular expression using `REGEXP_REPLACE()` that produces an internal error in some cases, and can crash the server in others.

**To Reproduce**

I'm trying to reverse engineer the supported regex syntax, and was trying to use a non-capturing group like in Java: `(?:abc)`. The following query:

```sql
select regexp_replace('TIMESTAMP(6)', '.*(?:\((\d+)\))?.*', '\1') 
```

Produces this exception:

``` 
SQL-Fehler [XX000]: ERROR: internal error: runtime error: slice bounds out of range [:-1]
  Detail: stack trace:
/go/src/github.com/cockroachdb/cockroach/pkg/util/errorutil/catch.go:29: ShouldCatch()
/go/src/github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder/builder.go:169: func1()
/usr/local/go/src/runtime/panic.go:679: gopanic()
/usr/local/go/src/runtime/panic.go:85: goPanicSliceAlen()
/go/src/github.com/cockroachdb/cockroach/pkg/sql/sem/builtins/builtins.go:4993: regexpReplace()
/go/src/github.com/cockroachdb/cockroach/pkg/sql/sem/builtins/builtins.go:1218: func80()
/go/src/github.com/cockroachdb/cockroach/pkg/sql/sem/tree/eval.go:4065: Eval()
/go/src/github.com/cockroachdb/cockroach/pkg/sql/opt/norm/fold_constants_funcs.go:359: FoldFunction()
/go/src/github.com/cockroachdb/cockroach/pkg/sql/opt/norm/factory.og.go:14082: ConstructFunction()
/go/src/github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder/scalar.go:482: buildFunction()
/go/src/github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder/scalar.go:291: buildScalar()
/go/src/github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder/project.go:171: buildProjectionList()
/go/src/github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder/select.go:949: buildSelectClause()
/go/src/github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder/select.go:869: buildSelectStmtWithoutParens()
/go/src/github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder/select.go:842: func1()
/go/src/github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder/with.go:29: processWiths()
/go/src/github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder/select.go:841: buildSelect()
/go/src/github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder/builder.go:253: buildStmt()
/go/src/github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder/builder.go:217: buildStmtAtRoot()
/go/src/github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder/builder.go:188: Build()
/go/src/github.com/cockroachdb/cockroach/pkg/sql/plan_opt.go:312: buildReusableMemo()
/go/src/github.com/cockroachdb/cockroach/pkg/sql/plan_opt.go:117: prepareUsingOptimizer()
/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_prepare.go:238: populatePrepared()
/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_prepare.go:180: func1()
/go/src/github.com/cockroachdb/cockroach/pkg/kv/db.go:702: func1()
/go/src/github.com/cockroachdb/cockroach/pkg/kv/txn.go:800: exec()
/go/src/github.com/cockroachdb/cockroach/pkg/kv/db.go:701: Txn()
/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_prepare.go:192: prepare()
/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_prepare.go:106: addPreparedStmt()
/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_prepare.go:52: execPrepare()
/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:1438: execCmd()
/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:1297: run()
```

If I use the regular expression in a query like this, then the server crashes:

```sql
-- Create a table first, otherwise, the query just returns an empty set
CREATE TABLE ts (
  ts_p0 timestamp(0),
  ts_p1 timestamp(1),
  ts_p3 timestamp(3),
  ts_p6 timestamp(6)
);

SELECT column_name, data_type, datetime_precision, regexp_replace(crdb_sql_type, '.*(?:\((\d+)\))?.*', '\1') 
FROM information_schema.columns
WHERE table_name = 'ts';
```

I can provide crash reports if you need, but I'd probably need some hints as to how to obtain them from a docker cockroachdb container

**Expected behavior**

There's probably just a syntax error, as the Java regex syntax is not supported. I'd expect that syntax error to be reported, and no crashes.

**Environment:**
 - CockroachDB version: CockroachDB CCL v20.1.3 (x86_64-unknown-linux-gnu, built 2020/06/23 08:44:08, go1.13.9)
 - Server OS: Docker on Windows
 - Client app: JDBC

### PR DESCRIPTION
**Pull request by yuzefovich**
It is possible that a regex matches the input string yet capture
groups end up being empty. Previously, in such cases we would hit an
internal error (due to out of bounds panic because values in
`matchIndex` would be negative), and now this is fixed by making sure
that capture groups are not empty.

Fixes: #51289.

Release note (bug fix): Previously, CockroachDB could hit an
internal error when executing `regexp_replace` builtin, and
this has been fixed.

### CODE REVIEW

File: pkg/sql/sem/builtins/builtins.go [hunk 1]
```diff
@@ -5145,9 +5145,10 @@ func regexpReplace(ctx *tree.EvalContext, s, pattern, to, sqlFlags string) (tree
 						newString.WriteString(s[matchStart:matchEnd])
 					} else {
 						idx := int(to[i] - '0')
-						// regexpReplace expects references to "out-of-bounds" capture groups
-						// to be ignored.
-						if 2*idx < len(matchIndex) {
+						// regexpReplace expects references to "out-of-bounds"
+						// and empty (when the corresponding match indices
+						// are negative) capture groups to be ignored.
+						if 2*idx < len(matchIndex) && matchIndex[2*idx] >= 0 {
```
Comment (jordanlewis) [inline pkg/sql/sem/builtins/builtins.go:5151]: can you capture some of these variables and arithmetic expressions? Currently this expression is a bit of an eye chart.

You could capture 2*idx, and matchIndex[2*idx+1]  maybe.

**Review by jordanlewis — APPROVED** [review]
LGTM

**Review by yuzefovich — COMMENTED** [review]
TFTR!

bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/51303#-:-MBu4rbaBEZve2oguQ9D:b-oduykh)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jordanlewis)

___
*[pkg/sql/sem/builtins/builtins.go, line 5151 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/51303#-MBtpds1Ge8E83mYLfGj-r1-5151:-MBu4pjj4Mfh5tyIjp8W:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/ea68cc4435d5c8a94433f81063a5072ae9ee4cc5/pkg/sql/sem/builtins/builtins.go#L5151)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

can you capture some of these variables and arithmetic expressions? Currently this expression is a bit of an eye chart.

You could capture 2*idx, and matchIndex[2*idx+1]  maybe.
</blockquote></details>

Done.
