### PR TITLE
kvcoord,kvserver: deflake flow control tests affected by leaseholder randomization

### LINKED ISSUE #167371: kv/kvserver: TestFlowControlSendQueueRangeRelocate failed
kv/kvserver.TestFlowControlSendQueueRangeRelocate [failed](https://mesolite.cluster.engflow.com/invocations/default/d63bc8a9-7944-402b-b1da-b47de3459fc7?testReportRun=1&testReportShard=34&testReportAttempt=1#targets-Ly9wa2cva3Yva3ZzZXJ2ZXI6a3ZzZXJ2ZXJfdGVzdA==) on master @ [f664d721208396abddf8e14e862ca09f4c07eec5](https://github.com/cockroachdb/cockroach/commits/f664d721208396abddf8e14e862ca09f4c07eec5):

```
github.com/cockroachdb/pebble/internal/genericcache.(*shard[...]).releaseLoop(0xc001166000)
	external/com_github_cockroachdb_pebble/internal/genericcache/shard.go:61 +0x6f
created by github.com/cockroachdb/pebble/internal/genericcache.(*shard[...]).Init in goroutine 49916
	external/com_github_cockroachdb_pebble/internal/genericcache/shard.go:54 +0x1a7

goroutine 49983 [chan receive, 14 minutes]:
github.com/cockroachdb/pebble/internal/genericcache.(*shard[...]).releaseLoop(0x0)
	external/com_github_cockroachdb_pebble/internal/genericcache/shard.go:61 +0x6f
created by github.com/cockroachdb/pebble/internal/genericcache.(*shard[...]).Init in goroutine 49916
	external/com_github_cockroachdb_pebble/internal/genericcache/shard.go:54 +0x1a7

goroutine 49982 [chan receive, 14 minutes, "pebble":"gc"]:
github.com/cockroachdb/pebble/internal/deletepacer.(*DeletePacer).mainLoop(0xc01ee26a08)
	external/com_github_cockroachdb_pebble/internal/deletepacer/delete_pacer.go:183 +0x33b
github.com/cockroachdb/pebble/internal/deletepacer.Open.func1.1({0x8dc72d8?, 0xc01b24c720?})
	external/com_github_cockroachdb_pebble/internal/deletepacer/delete_pacer.go:108 +0x17
runtime/pprof.Do({0x8dc6800?, 0xdf9ca80?}, {{0xc011ee8000?, 0x0?, 0x1?}}, 0xc0184fd7a0)
	GOROOT/src/runtime/pprof/runtime.go:51 +0x8c
github.com/cockroachdb/pebble/internal/deletepacer.Open.func1()
	external/com_github_cockroachdb_pebble/internal/deletepacer/delete_pacer.go:107 +0x9c
created by github.com/cockroachdb/pebble/internal/deletepacer.Open in goroutine 49916
	external/com_github_cockroachdb_pebble/internal/deletepacer/delete_pacer.go:106 +0x229

goroutine 52606 [chan receive, 14 minutes]:
github.com/cockroachdb/cockroach/pkg/gossip.(*server).start.func3({0xc015e81d00?, 0x8dc7978?})
	pkg/gossip/server.go:404 +0x48
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunAsyncTaskEx.func1({0x8dc7978, 0xc012ce81e0})
	pkg/util/stop/stopper.go:447 +0x8a
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunAsyncTaskEx in goroutine 49916
	pkg/util/stop/stopper.go:445 +0x125

goroutine 52207 [select]:
github.com/cockroachdb/cockroach/pkg/util/admission.initWorkQueue.func2()
	pkg/util/admission/work_queue.go:468 +0x85
created by github.com/cockroachdb/cockroach/pkg/util/admission.initWorkQueue in goroutine 49916
	pkg/util/admission/work_queue.go:465 +0x338

goroutine 50401 [select, 14 minutes]:
github.com/cockroachdb/cockroach/pkg/gossip.(*infoStore).launchCallbackWorker.func1({0xc01038ad40?, 0x8dc7978?})
	pkg/gossip/infostore.go:293 +0x105
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunAsyncTaskEx.func1({0x8dc7978, 0xc011c26f00})
	pkg/util/stop/stopper.go:447 +0x8a
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunAsyncTaskEx in goroutine 49916
	pkg/util/stop/stopper.go:445 +0x125

goroutine 50840 [select]:
github.com/cockroachdb/cockroach/pkg/util/admission.(*WorkQueue).startClosingEpochs.func1()
	pkg/util/admission/work_queue.go:578 +0x145
created by github.com/cockroachdb/cockroach/pkg/util/admission.(*WorkQueue).startClosingEpochs in goroutine 49916
	pkg/util/admission/work_queue.go:549 +0x4f
```

Parameters:
 - <code>attempt=1</code>
 - <code>run=1</code>
 - <code>shard=34</code>
<details><summary>Help</summary>
<p>

See also: [How To Investigate a Go Test Failure \(internal\)](https://cockroachlabs.atlassian.net/l/c/HgfXfJgM)
</p>
</details>
/cc @cockroachdb/kv-triage
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*TestFlowControlSendQueueRangeRelocate.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/bazci/githubpost/issues)

</sub>

Jira issue: CRDB-62417

### LINKED ISSUE #167372: kv/kvserver: TestFlowControlRangeSplitMergeMixedVersion failed
kv/kvserver.TestFlowControlRangeSplitMergeMixedVersion [failed](https://mesolite.cluster.engflow.com/invocations/default/d63bc8a9-7944-402b-b1da-b47de3459fc7?testReportRun=6&testReportShard=35&testReportAttempt=1#targets-Ly9wa2cva3Yva3ZzZXJ2ZXI6a3ZzZXJ2ZXJfdGVzdA==) on master @ [f664d721208396abddf8e14e862ca09f4c07eec5](https://github.com/cockroachdb/cockroach/commits/f664d721208396abddf8e14e862ca09f4c07eec5):

```
internal/poll.(*pollDesc).waitRead(...)
	GOROOT/src/internal/poll/fd_poll_runtime.go:89
internal/poll.(*FD).Read(0xc001f06900, {0xc01e681800, 0x800, 0x800})
	GOROOT/src/internal/poll/fd_unix.go:165 +0x279
net.(*netFD).Read(0xc001f06900, {0xc01e681800?, 0x7fb?, 0xc0045fd020?})
	GOROOT/src/net/fd_posix.go:68 +0x25
net.(*conn).Read(0xc020c11298, {0xc01e681800?, 0xc01e681800?, 0x5?})
	GOROOT/src/net/net.go:196 +0x45
github.com/cockroachdb/cmux.(*MuxConn).Read(0xc01c52dce0, {0xc01e681800, 0x800, 0x800})
	external/com_github_cockroachdb_cmux/cmux.go:241 +0x14f
crypto/tls.(*atLeastReader).Read(0xc01e7f64f8, {0xc01e681800?, 0x7fb?, 0x317f860?})
	GOROOT/src/crypto/tls/conn.go:816 +0x3b
bytes.(*Buffer).ReadFrom(0xc019eb49a8, {0x8d70440, 0xc01e7f64f8})
	GOROOT/src/bytes/buffer.go:217 +0x98
crypto/tls.(*Conn).readFromUntil(0xc019eb4708, {0x7f34fa435600, 0xc01c52dce0}, 0x4a4994?)
	GOROOT/src/crypto/tls/conn.go:838 +0xde
crypto/tls.(*Conn).readRecordOrCCS(0xc019eb4708, 0x0)
	GOROOT/src/crypto/tls/conn.go:627 +0x3db
crypto/tls.(*Conn).readRecord(...)
	GOROOT/src/crypto/tls/conn.go:589
crypto/tls.(*Conn).Read(0xc019eb4708, {0xc00e25c000, 0x1000, 0x1e9d7cf?})
	GOROOT/src/crypto/tls/conn.go:1392 +0x145
storj.io/drpc/drpcwire.(*Reader).read(0xc0148d32d0, {0xc00e25c000, 0x1000, 0x1000})
	external/io_storj_drpc/drpcwire/reader.go:71 +0x71
storj.io/drpc/drpcwire.(*Reader).ReadPacketUsing(0xc0148d32d0, {0xc0136c59e0?, 0x0?, 0x60?})
	external/io_storj_drpc/drpcwire/reader.go:116 +0x4ec
storj.io/drpc/drpcmanager.(*Manager).manageReader(0xc013fe6f00)
	external/io_storj_drpc/drpcmanager/manager.go:236 +0xd9
created by storj.io/drpc/drpcmanager.NewWithOptions in goroutine 33142
	external/io_storj_drpc/drpcmanager/manager.go:128 +0x40c

goroutine 75732 [chan receive, 2 minutes]:
storj.io/drpc/drpcpool.(*poolConn[...]).monitorStream(0x8e41340, {0x8e054c0, 0xc028cf6288?}, {0x8df3220?, 0xc028b4ba40}, 0xc028b4bae0)
	external/io_storj_drpc/drpcpool/conn.go:108 +0x4a
created by storj.io/drpc/drpcpool.(*poolConn[...]).NewStream in goroutine 75672
	external/io_storj_drpc/drpcpool/conn.go:102 +0x2e5

goroutine 76350 [select, 1 minutes]:
storj.io/drpc/drpcmanager.(*Manager).manageStream(0xc01ecb6960, {0x8dc72d8, 0xc0255535f0}, 0xc019844a08)
	external/io_storj_drpc/drpcmanager/manager.go:340 +0xed
storj.io/drpc/drpcmanager.(*Manager).manageStreams(0xc01ecb6960)
	external/io_storj_drpc/drpcmanager/manager.go:329 +0x85
created by storj.io/drpc/drpcmanager.NewWithOptions in goroutine 76345
	external/io_storj_drpc/drpcmanager/manager.go:129 +0x448

goroutine 78201 [select, "tags":"n3,rnode=1,raddr=127.0.0.1:38511,class=default,rpc", "workload.id":"RPC_HEARTBEAT"]:
storj.io/drpc/drpcmanager.(*Manager).manageStreams(0xc031142d20)
	external/io_storj_drpc/drpcmanager/manager.go:327 +0x110
created by storj.io/drpc/drpcmanager.NewWithOptions in goroutine 30196
	external/io_storj_drpc/drpcmanager/manager.go:129 +0x448
```

Parameters:
 - <code>attempt=1</code>
 - <code>run=6</code>
 - <code>shard=35</code>
<details><summary>Help</summary>
<p>

See also: [How To Investigate a Go Test Failure \(internal\)](https://cockroachlabs.atlassian.net/l/c/HgfXfJgM)
</p>
</details>
/cc @cockroachdb/kv-triage
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*TestFlowControlRangeSplitMergeMixedVersion.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/bazci/githubpost/issues)

</sub>

Jira issue: CRDB-62418

### LINKED ISSUE #167383: kv/kvserver: TestFlowControlCrashedNodeV2 failed
kv/kvserver.TestFlowControlCrashedNodeV2 [failed](https://mesolite.cluster.engflow.com/invocations/default/c987d3c3-e0ff-451b-835e-6771b3d1425d?testReportRun=1&testReportShard=22&testReportAttempt=1#targets-Ly9wa2cva3Yva3ZzZXJ2ZXI6a3ZzZXJ2ZXJfdGVzdA==) on master @ [e99199606f52e553ab0a5198893ad44215d4f98c](https://github.com/cockroachdb/cockroach/commits/e99199606f52e553ab0a5198893ad44215d4f98c):

```
sync.runtime_notifyListWait(0xc013acc210, 0x36)
	GOROOT/src/runtime/sema.go:606 +0x159
sync.(*Cond).Wait(0xc01add1c08?)
	GOROOT/src/sync/cond.go:71 +0x73
github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*raftSchedulerShard).worker(0xc005966d20, {0x8dc78d8, 0xc0166fcbe0}, {0x8df1e00, 0xc01add1c08}, 0xc00362b008)
	pkg/kv/kvserver/scheduler.go:379 +0x385
github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*raftScheduler).Start.func2({0x8dc78d8, 0xc0166fcbe0}, 0xc00e6aa140?)
	pkg/kv/kvserver/scheduler.go:314 +0xe9
created by github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*raftScheduler).Start in goroutine 73431
	pkg/kv/kvserver/scheduler.go:329 +0x28c

goroutine 73497 [select]:
github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*Store).coalescedHeartbeatsLoop(0xc01add1c08, {0x8dc78d8, 0xc00f1f4140})
	pkg/kv/kvserver/store_raft.go:1099 +0xe5
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunAsyncTaskEx.func1({0x8dc78d8, 0xc00f1f4140})
	pkg/util/stop/stopper.go:447 +0x8a
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunAsyncTaskEx in goroutine 73431
	pkg/util/stop/stopper.go:445 +0x125

goroutine 72708 [select, "gen":"2", "mux_n":"1", "n":"1", "rangefeed":"system-config-cache"]:
github.com/cockroachdb/cockroach/pkg/kv/kvserver/rangefeed.(*BufferedSender).run(0xc0151fbc20, {0x8dc7200, 0xc0151fbcc0}, 0xc004c68900, 0xc01720cc00)
	pkg/kv/kvserver/rangefeed/buffered_sender.go:276 +0x165
github.com/cockroachdb/cockroach/pkg/kv/kvserver/rangefeed.(*StreamManager).Start.func1({0x8dc7200, 0xc0151fbcc0})
	pkg/kv/kvserver/rangefeed/stream_manager.go:196 +0xc3
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunAsyncTaskEx.func1({0x8dc7200, 0xc0151fbcc0})
	pkg/util/stop/stopper.go:447 +0x8a
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunAsyncTaskEx in goroutine 72707
	pkg/util/stop/stopper.go:445 +0x125

goroutine 71798 [sync.Cond.Wait]:
sync.runtime_notifyListWait(0xc012119150, 0x876)
	GOROOT/src/runtime/sema.go:606 +0x159
sync.(*Cond).Wait(0x7149f00?)
	GOROOT/src/sync/cond.go:71 +0x73
github.com/cockroachdb/cockroach/pkg/kv/kvserver/rangefeed.(*schedulerShard).processEvents(0xc01625e900, {0x8dc78d8, 0xc00e71c1e0})
	pkg/kv/kvserver/rangefeed/scheduler.go:476 +0x556
github.com/cockroachdb/cockroach/pkg/kv/kvserver/rangefeed.(*Scheduler).Start.func1({0x8dc78d8, 0xc00e71c1e0})
	pkg/kv/kvserver/rangefeed/scheduler.go:249 +0x151
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunAsyncTaskEx.func1({0x8dc78d8, 0xc00e71c1e0})
	pkg/util/stop/stopper.go:447 +0x8a
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunAsyncTaskEx in goroutine 71787
	pkg/util/stop/stopper.go:445 +0x125

goroutine 70866 [select, 13 minutes]:
github.com/cockroachdb/cockroach/pkg/sql.(*runnerCoordinator).init.func1({0xc0025750c0?, 0x8dc78d8?})
	pkg/sql/distsql_running.go:173 +0x110
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunAsyncTaskEx.func1({0x8dc78d8, 0xc03d2e05a0})
	pkg/util/stop/stopper.go:447 +0x8a
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunAsyncTaskEx in goroutine 70849
	pkg/util/stop/stopper.go:445 +0x125
```

Parameters:
 - <code>attempt=1</code>
 - <code>run=1</code>
 - <code>shard=22</code>
<details><summary>Help</summary>
<p>

See also: [How To Investigate a Go Test Failure \(internal\)](https://cockroachlabs.atlassian.net/l/c/HgfXfJgM)
</p>
</details>
/cc @cockroachdb/kv-triage
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*TestFlowControlCrashedNodeV2.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/bazci/githubpost/issues)

</sub>

Jira issue: CRDB-62424

### LINKED ISSUE #167396: kv/kvserver: TestFlowControlSendQueue failed
kv/kvserver.TestFlowControlSendQueue [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Ci_TestsIbmCloudLinuxS390x_UnitTestsS390x/21293468?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Ci_TestsIbmCloudLinuxS390x_UnitTestsS390x/21293468?buildTab=artifacts#/) on master @ [461753032b18f0f9ee89924637c850cd2fc4a02d](https://github.com/cockroachdb/cockroach/commits/461753032b18f0f9ee89924637c850cd2fc4a02d):

```
github.com/cockroachdb/pebble/record.(*flusherCond).Wait(...)
	external/com_github_cockroachdb_pebble/record/log_writer.go:371
github.com/cockroachdb/pebble/record.(*LogWriter).flushLoop(0xc02c670000, {0x89682030, 0xc0027ef0b0})
	external/com_github_cockroachdb_pebble/record/log_writer.go:682 +0x8ec
runtime/pprof.Do({0x89681430, 0x8e118d20}, {{0xc00144a240, 0x1, 0x1}}, 0xc0203a97c8)
	GOROOT/src/runtime/pprof/runtime.go:51 +0xc2
github.com/cockroachdb/pebble/record.NewLogWriter.func2()
	external/com_github_cockroachdb_pebble/record/log_writer.go:596 +0x68
created by github.com/cockroachdb/pebble/record.NewLogWriter in goroutine 44143
	external/com_github_cockroachdb_pebble/record/log_writer.go:595 +0x67e

goroutine 225941 [sync.Cond.Wait, "pebble":"wal-sync"]:
sync.runtime_notifyListWait(0xc011b380a8, 0x1738)
	GOROOT/src/runtime/sema.go:606 +0x1cc
sync.(*Cond).Wait(0xc011b38098)
	GOROOT/src/sync/cond.go:71 +0xc4
github.com/cockroachdb/pebble/record.(*flusherCond).Wait(...)
	external/com_github_cockroachdb_pebble/record/log_writer.go:371
github.com/cockroachdb/pebble/record.(*LogWriter).flushLoop(0xc011b38000, {0x89682030, 0xc001daf170})
	external/com_github_cockroachdb_pebble/record/log_writer.go:682 +0x8ec
runtime/pprof.Do({0x89681430, 0x8e118d20}, {{0xc00144a240, 0x1, 0x1}}, 0xc0048827c8)
	GOROOT/src/runtime/pprof/runtime.go:51 +0xc2
github.com/cockroachdb/pebble/record.NewLogWriter.func2()
	external/com_github_cockroachdb_pebble/record/log_writer.go:596 +0x68
created by github.com/cockroachdb/pebble/record.NewLogWriter in goroutine 45805
	external/com_github_cockroachdb_pebble/record/log_writer.go:595 +0x67e

goroutine 477594 [select]:
github.com/cockroachdb/cockroach/pkg/sql/stats.(*Refresher).Start.func1.1({0x896826f8, 0xc01492edc0})
	pkg/sql/stats/automatic_stats.go:624 +0x18a
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunAsyncTaskEx.func1({0x896826f8, 0xc01492edc0})
	pkg/util/stop/stopper.go:447 +0xac
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunAsyncTaskEx in goroutine 47297
	pkg/util/stop/stopper.go:445 +0x16c

goroutine 354410 [sync.Cond.Wait, "pebble":"wal-sync"]:
sync.runtime_notifyListWait(0xc0277180a8, 0x72f)
	GOROOT/src/runtime/sema.go:606 +0x1cc
sync.(*Cond).Wait(0xc027718098)
	GOROOT/src/sync/cond.go:71 +0xc4
github.com/cockroachdb/pebble/record.(*flusherCond).Wait(...)
	external/com_github_cockroachdb_pebble/record/log_writer.go:371
github.com/cockroachdb/pebble/record.(*LogWriter).flushLoop(0xc027718000, {0x89682030, 0xc02b740c90})
	external/com_github_cockroachdb_pebble/record/log_writer.go:682 +0x8ec
runtime/pprof.Do({0x89681430, 0x8e118d20}, {{0xc00144a240, 0x1, 0x1}}, 0xc016a757c8)
	GOROOT/src/runtime/pprof/runtime.go:51 +0xc2
github.com/cockroachdb/pebble/record.NewLogWriter.func2()
	external/com_github_cockroachdb_pebble/record/log_writer.go:596 +0x68
created by github.com/cockroachdb/pebble/record.NewLogWriter in goroutine 47793
	external/com_github_cockroachdb_pebble/record/log_writer.go:595 +0x67e
```
<details><summary>Help</summary>
<p>

See also: [How To Investigate a Go Test Failure \(internal\)](https://cockroachlabs.atlassian.net/l/c/HgfXfJgM)
</p>
</details>
/cc @cockroachdb/kv-triage
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*TestFlowControlSendQueue.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/bazci/githubpost/issues)

</sub>

Jira issue: CRDB-62432

### LINKED ISSUE #167406: kv/kvserver: TestFlowControlLeaderNotLeaseholderV2 failed
kv/kvserver.TestFlowControlLeaderNotLeaseholderV2 [failed](https://mesolite.cluster.engflow.com/invocations/default/f7cc918e-fd32-484a-937a-53cde79d1dee?testReportRun=1&testReportShard=29&testReportAttempt=1#targets-Ly9wa2cva3Yva3ZzZXJ2ZXI6a3ZzZXJ2ZXJfdGVzdA==) on master @ [84b19817fd09dd1a124206eb53a7627141caa5b0](https://github.com/cockroachdb/cockroach/commits/84b19817fd09dd1a124206eb53a7627141caa5b0):

```

goroutine 72475 [sync.Cond.Wait, 14 minutes]:
sync.runtime_notifyListWait(0xc010f93a10, 0x0)
	GOROOT/src/runtime/sema.go:606 +0x159
sync.(*Cond).Wait(0x52baa96a39bb7f28?)
	GOROOT/src/sync/cond.go:71 +0x73
github.com/cockroachdb/cockroach/pkg/kv/kvserver/rangefeed.(*schedulerShard).processEvents(0xc018968ba0, {0x8dc7eb8, 0xc0116d9ae0})
	pkg/kv/kvserver/rangefeed/scheduler.go:476 +0x556
github.com/cockroachdb/cockroach/pkg/kv/kvserver/rangefeed.(*Scheduler).Start.func1({0x8dc7eb8, 0xc0116d9ae0})
	pkg/kv/kvserver/rangefeed/scheduler.go:249 +0x151
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunAsyncTaskEx.func1({0x8dc7eb8, 0xc0116d9ae0})
	pkg/util/stop/stopper.go:447 +0x8a
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunAsyncTaskEx in goroutine 72442
	pkg/util/stop/stopper.go:445 +0x125

goroutine 69657 [select]:
github.com/cockroachdb/cockroach/pkg/sql/catalog/lease.(*Manager).StartRefreshLeasesTask.func1({0x8dc7818, 0xc001a7d5c0})
	pkg/sql/catalog/lease/lease.go:2868 +0x187
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunAsyncTaskEx.func1({0x8dc7818, 0xc001a7d5c0})
	pkg/util/stop/stopper.go:447 +0x8a
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunAsyncTaskEx in goroutine 66886
	pkg/util/stop/stopper.go:445 +0x125

goroutine 72476 [sync.Cond.Wait, 14 minutes]:
sync.runtime_notifyListWait(0xc010f93a10, 0x5)
	GOROOT/src/runtime/sema.go:606 +0x159
sync.(*Cond).Wait(0x24?)
	GOROOT/src/sync/cond.go:71 +0x73
github.com/cockroachdb/cockroach/pkg/kv/kvserver/rangefeed.(*schedulerShard).processEvents(0xc018968ba0, {0x8dc7eb8, 0xc0116d9ae0})
	pkg/kv/kvserver/rangefeed/scheduler.go:476 +0x556
github.com/cockroachdb/cockroach/pkg/kv/kvserver/rangefeed.(*Scheduler).Start.func1({0x8dc7eb8, 0xc0116d9ae0})
	pkg/kv/kvserver/rangefeed/scheduler.go:249 +0x151
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunAsyncTaskEx.func1({0x8dc7eb8, 0xc0116d9ae0})
	pkg/util/stop/stopper.go:447 +0x8a
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunAsyncTaskEx in goroutine 72442
	pkg/util/stop/stopper.go:445 +0x125

goroutine 71847 [select]:
github.com/cockroachdb/cockroach/pkg/sql/sqlstats/persistedsqlstats.(*jobMonitor).start.func1({0x8dc7818, 0xc0267ccde0})
	pkg/sql/sqlstats/persistedsqlstats/scheduled_job_monitor.go:97 +0x2b5
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunAsyncTaskEx.func1({0x8dc7818, 0xc0267ccde0})
	pkg/util/stop/stopper.go:447 +0x8a
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunAsyncTaskEx in goroutine 66886
	pkg/util/stop/stopper.go:445 +0x125

goroutine 130992 [select]:
storj.io/drpc/drpcmanager.(*Manager).manageStreams(0xc02f2a03c0)
	external/io_storj_drpc/drpcmanager/manager.go:327 +0x110
created by storj.io/drpc/drpcmanager.NewWithOptions in goroutine 131157
	external/io_storj_drpc/drpcmanager/manager.go:129 +0x448
```

Parameters:
 - <code>attempt=1</code>
 - <code>run=1</code>
 - <code>shard=29</code>
<details><summary>Help</summary>
<p>

See also: [How To Investigate a Go Test Failure \(internal\)](https://cockroachlabs.atlassian.net/l/c/HgfXfJgM)
</p>
</details>
/cc @cockroachdb/kv-triage
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*TestFlowControlLeaderNotLeaseholderV2.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/bazci/githubpost/issues)

</sub>

Jira issue: CRDB-62438

### LINKED ISSUE #167415: kv/kvserver: TestFlowControlClassPrioritizationV2 failed
kv/kvserver.TestFlowControlClassPrioritizationV2 [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Ci_TestsAwsLinuxArm64_UnitTests/21295904?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Ci_TestsAwsLinuxArm64_UnitTests/21295904?buildTab=artifacts#/) on master @ [84b19817fd09dd1a124206eb53a7627141caa5b0](https://github.com/cockroachdb/cockroach/commits/84b19817fd09dd1a124206eb53a7627141caa5b0):

```
storj.io/drpc/drpcwire.(*Reader).read(0x403dcd3a40, {0x4053ab4000, 0x1f000, 0x1f000})
	external/io_storj_drpc/drpcwire/reader.go:71 +0x6c
storj.io/drpc/drpcwire.(*Reader).ReadPacketUsing(0x403dcd3a40, {0x4057d1e000?, 0x177?, 0x86000?})
	external/io_storj_drpc/drpcwire/reader.go:116 +0x364
storj.io/drpc/drpcmanager.(*Manager).manageReader(0x403f654000)
	external/io_storj_drpc/drpcmanager/manager.go:236 +0xc0
created by storj.io/drpc/drpcmanager.NewWithOptions in goroutine 105881
	external/io_storj_drpc/drpcmanager/manager.go:128 +0x364

goroutine 106530 [IO wait]:
internal/poll.runtime_pollWait(0xea5b0cf3d000, 0x72)
	GOROOT/src/runtime/netpoll.go:351 +0xa0
internal/poll.(*pollDesc).wait(0x40276d9e80?, 0x401a943000?, 0x0)
	GOROOT/src/internal/poll/fd_poll_runtime.go:84 +0x28
internal/poll.(*pollDesc).waitRead(...)
	GOROOT/src/internal/poll/fd_poll_runtime.go:89
internal/poll.(*FD).Read(0x40276d9e80, {0x401a943000, 0x800, 0x800})
	GOROOT/src/internal/poll/fd_unix.go:165 +0x1e0
net.(*netFD).Read(0x40276d9e80, {0x401a943000?, 0xc?, 0x401a943005?})
	GOROOT/src/net/fd_posix.go:68 +0x28
net.(*conn).Read(0x403dcea108, {0x401a943000?, 0x402e37d888?, 0x42da28?})
	GOROOT/src/net/net.go:196 +0x34
github.com/cockroachdb/cmux.(*MuxConn).Read(0x4016572480, {0x401a943000, 0x800, 0x800})
	external/com_github_cockroachdb_cmux/cmux.go:241 +0x15c
crypto/tls.(*atLeastReader).Read(0x4020b6a660, {0x401a943000?, 0x402e37d948?, 0x7f3474?})
	GOROOT/src/crypto/tls/conn.go:816 +0x38
bytes.(*Buffer).ReadFrom(0x401e3869a8, {0x7e145c0, 0x4020b6a660})
	GOROOT/src/bytes/buffer.go:217 +0x90
crypto/tls.(*Conn).readFromUntil(0x401e386708, {0xea5b0cef4258, 0x4016572480}, 0x402e37d9f0?)
	GOROOT/src/crypto/tls/conn.go:838 +0xcc
crypto/tls.(*Conn).readRecordOrCCS(0x401e386708, 0x0)
	GOROOT/src/crypto/tls/conn.go:627 +0x340
crypto/tls.(*Conn).readRecord(...)
	GOROOT/src/crypto/tls/conn.go:589
crypto/tls.(*Conn).Read(0x401e386708, {0x403f9fc000, 0x1000, 0x0?})
	GOROOT/src/crypto/tls/conn.go:1392 +0x14c
storj.io/drpc/drpcwire.(*Reader).read(0x403fd48d20, {0x403f9fc000, 0x1000, 0x1000})
	external/io_storj_drpc/drpcwire/reader.go:71 +0x6c
storj.io/drpc/drpcwire.(*Reader).ReadPacketUsing(0x403fd48d20, {0x40536da6e0?, 0x0?, 0xa0?})
	external/io_storj_drpc/drpcwire/reader.go:116 +0x364
storj.io/drpc/drpcmanager.(*Manager).manageReader(0x4043f3e000)
	external/io_storj_drpc/drpcmanager/manager.go:236 +0xc0
created by storj.io/drpc/drpcmanager.NewWithOptions in goroutine 106483
	external/io_storj_drpc/drpcmanager/manager.go:128 +0x364

goroutine 107553 [select]:
storj.io/drpc/drpcmanager.(*Manager).manageStreams(0x4012081c20)
	external/io_storj_drpc/drpcmanager/manager.go:327 +0xc8
created by storj.io/drpc/drpcmanager.NewWithOptions in goroutine 107840
	external/io_storj_drpc/drpcmanager/manager.go:129 +0x3a4
```
<details><summary>Help</summary>
<p>

See also: [How To Investigate a Go Test Failure \(internal\)](https://cockroachlabs.atlassian.net/l/c/HgfXfJgM)
</p>
</details>
/cc @cockroachdb/kv-triage
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*TestFlowControlClassPrioritizationV2.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/bazci/githubpost/issues)

</sub>

Jira issue: CRDB-62445

### LINKED ISSUE #167416: kv/kvserver: TestFlowControlClassPrioritizationV2 failed
kv/kvserver.TestFlowControlClassPrioritizationV2 [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Ci_TestsAwsLinuxArm64_UnitTests/21295904?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Ci_TestsAwsLinuxArm64_UnitTests/21295904?buildTab=artifacts#/) on master @ [84b19817fd09dd1a124206eb53a7627141caa5b0](https://github.com/cockroachdb/cockroach/commits/84b19817fd09dd1a124206eb53a7627141caa5b0):

```
internal/poll.(*pollDesc).wait(0x401d51d180?, 0x401d4f1000?, 0x0)
	GOROOT/src/internal/poll/fd_poll_runtime.go:84 +0x28
internal/poll.(*pollDesc).waitRead(...)
	GOROOT/src/internal/poll/fd_poll_runtime.go:89
internal/poll.(*FD).Read(0x401d51d180, {0x401d4f1000, 0x800, 0x800})
	GOROOT/src/internal/poll/fd_unix.go:165 +0x1e0
net.(*netFD).Read(0x401d51d180, {0x401d4f1000?, 0xc?, 0x401d4f1005?})
	GOROOT/src/net/fd_posix.go:68 +0x28
net.(*conn).Read(0x40023f5ba0, {0x401d4f1000?, 0x4014cde888?, 0x42da28?})
	GOROOT/src/net/net.go:196 +0x34
github.com/cockroachdb/cmux.(*MuxConn).Read(0x402e183c80, {0x401d4f1000, 0x800, 0x800})
	external/com_github_cockroachdb_cmux/cmux.go:241 +0x15c
crypto/tls.(*atLeastReader).Read(0x404a991cc8, {0x401d4f1000?, 0x4014cde948?, 0x7f3474?})
	GOROOT/src/crypto/tls/conn.go:816 +0x38
bytes.(*Buffer).ReadFrom(0x40161cc2a8, {0x7e145c0, 0x404a991cc8})
	GOROOT/src/bytes/buffer.go:217 +0x90
crypto/tls.(*Conn).readFromUntil(0x40161cc008, {0xe40cf8dc26f8, 0x402e183c80}, 0x4014cde9f0?)
	GOROOT/src/crypto/tls/conn.go:838 +0xcc
crypto/tls.(*Conn).readRecordOrCCS(0x40161cc008, 0x0)
	GOROOT/src/crypto/tls/conn.go:627 +0x340
crypto/tls.(*Conn).readRecord(...)
	GOROOT/src/crypto/tls/conn.go:589
crypto/tls.(*Conn).Read(0x40161cc008, {0x402889e000, 0x1000, 0x0?})
	GOROOT/src/crypto/tls/conn.go:1392 +0x14c
storj.io/drpc/drpcwire.(*Reader).read(0x40275122a0, {0x402889e000, 0x1000, 0x1000})
	external/io_storj_drpc/drpcwire/reader.go:71 +0x6c
storj.io/drpc/drpcwire.(*Reader).ReadPacketUsing(0x40275122a0, {0x401a4e66e0?, 0x0?, 0xa0?})
	external/io_storj_drpc/drpcwire/reader.go:116 +0x364
storj.io/drpc/drpcmanager.(*Manager).manageReader(0x4027ac4d20)
	external/io_storj_drpc/drpcmanager/manager.go:236 +0xc0
created by storj.io/drpc/drpcmanager.NewWithOptions in goroutine 54686
	external/io_storj_drpc/drpcmanager/manager.go:128 +0x364

goroutine 107182 [select]:
storj.io/drpc/drpcmanager.(*Manager).NewServerStream(0x404c028d20, {0x7e6bb90, 0x401f39eed0})
	external/io_storj_drpc/drpcmanager/manager.go:461 +0x1a4
storj.io/drpc/drpcserver.(*Server).ServeOne(0x400a11e780, {0x7e701b8?, 0x4015a63950?}, {0x7e5d890?, 0x402267f888?})
	external/io_storj_drpc/drpcserver/server.go:152 +0x32c
storj.io/drpc/drpcserver.(*Server).Serve.func2({0x7e701b8?, 0x4015a63950?})
	external/io_storj_drpc/drpcserver/server.go:208 +0x60
storj.io/drpc/drpcctx.(*Tracker).track(0x4015a63950, 0x401686c640?)
	external/io_storj_drpc/drpcctx/tracker.go:35 +0x34
created by storj.io/drpc/drpcctx.(*Tracker).Run in goroutine 44943
	external/io_storj_drpc/drpcctx/tracker.go:30 +0x78

goroutine 84678 [select, "tags":"n3,rnode=1,raddr=127.0.0.1:33091,class=system,rpc", "workload.id":"RPC_HEARTBEAT"]:
storj.io/drpc/drpcmanager.(*Manager).manageStreams(0x4022c663c0)
	external/io_storj_drpc/drpcmanager/manager.go:327 +0xc8
created by storj.io/drpc/drpcmanager.NewWithOptions in goroutine 48665
	external/io_storj_drpc/drpcmanager/manager.go:129 +0x3a4
```
<details><summary>Help</summary>
<p>

See also: [How To Investigate a Go Test Failure \(internal\)](https://cockroachlabs.atlassian.net/l/c/HgfXfJgM)
</p>
</details>
/cc @cockroachdb/kv-triage
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*TestFlowControlClassPrioritizationV2.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/bazci/githubpost/issues)

</sub>

Jira issue: CRDB-62446

### LINKED ISSUE #167421: kv/kvserver: TestFlowControlBlockedAdmissionV2 failed
kv/kvserver.TestFlowControlBlockedAdmissionV2 [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Ci_TestsAwsLinuxArm64_UnitTests/21295960?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Ci_TestsAwsLinuxArm64_UnitTests/21295960?buildTab=artifacts#/) on master @ [1cae9feb482c56614e0a3c488a3978daf9e75167](https://github.com/cockroachdb/cockroach/commits/1cae9feb482c56614e0a3c488a3978daf9e75167):

```
storj.io/drpc/drpcpool.(*poolConn[...]).monitorStream(0x7ee9860, {0x7ead9c8, 0x4004343908?}, {0x7e9b3e0?, 0x40133b2540}, 0x40133b25e0)
	external/io_storj_drpc/drpcpool/conn.go:108 +0x54
created by storj.io/drpc/drpcpool.(*poolConn[...]).NewStream in goroutine 59570
	external/io_storj_drpc/drpcpool/conn.go:102 +0x1f0

goroutine 55012 [select, 14 minutes]:
github.com/cockroachdb/cockroach/pkg/sql.(*runnerCoordinator).init.func1({0x4019ba0dc0?, 0x7e6f538?})
	pkg/sql/distsql_running.go:173 +0x90
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunAsyncTaskEx.func1({0x7e6f538, 0x401b7212c0})
	pkg/util/stop/stopper.go:447 +0x7c
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunAsyncTaskEx in goroutine 52987
	pkg/util/stop/stopper.go:445 +0xe0

goroutine 58267 [sync.Cond.Wait, 14 minutes]:
sync.runtime_notifyListWait(0x4022775810, 0x5)
	GOROOT/src/runtime/sema.go:606 +0x140
sync.(*Cond).Wait(0x4022775800)
	GOROOT/src/sync/cond.go:71 +0xa4
github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*raftSchedulerShard).worker(0x4013bee7e0, {0x7e6f538, 0x401600bea0}, {0x7e99da0, 0x401d654808}, 0x4001ccd008)
	pkg/kv/kvserver/scheduler.go:379 +0x34c
github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*raftScheduler).Start.func2({0x7e6f538, 0x401600bea0}, 0x7e6f538?)
	pkg/kv/kvserver/scheduler.go:314 +0xcc
created by github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*raftScheduler).Start in goroutine 58054
	pkg/kv/kvserver/scheduler.go:329 +0x224

goroutine 58214 [sync.Cond.Wait]:
sync.runtime_notifyListWait(0x4022775710, 0xc01)
	GOROOT/src/runtime/sema.go:606 +0x140
sync.(*Cond).Wait(0x4022775700)
	GOROOT/src/sync/cond.go:71 +0xa4
github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*raftSchedulerShard).worker(0x4013bee690, {0x7e6f538, 0x401600bea0}, {0x7e99da0, 0x401d654808}, 0x4001ccd008)
	pkg/kv/kvserver/scheduler.go:379 +0x34c
github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*raftScheduler).Start.func2({0x7e6f538, 0x401600bea0}, 0x7e6f538?)
	pkg/kv/kvserver/scheduler.go:314 +0xcc
created by github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*raftScheduler).Start in goroutine 58054
	pkg/kv/kvserver/scheduler.go:329 +0x224

goroutine 56156 [chan receive, 14 minutes]:
github.com/cockroachdb/cockroach/pkg/util/netutil.MakeHTTPServer.func2({0x4002289f00?, 0x7e6f538?})
	pkg/util/netutil/net.go:101 +0x50
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunAsyncTaskEx.func1({0x7e6f538, 0x401b7212c0})
	pkg/util/stop/stopper.go:447 +0x7c
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunAsyncTaskEx in goroutine 54424
	pkg/util/stop/stopper.go:445 +0xe0

goroutine 55054 [chan receive, 14 minutes]:
github.com/cockroachdb/pebble/internal/genericcache.(*shard[...]).releaseLoop(0x401b7212c0)
	external/com_github_cockroachdb_pebble/internal/genericcache/shard.go:61 +0x68
created by github.com/cockroachdb/pebble/internal/genericcache.(*shard[...]).Init in goroutine 54424
	external/com_github_cockroachdb_pebble/internal/genericcache/shard.go:54 +0x15c
```
<details><summary>Help</summary>
<p>

See also: [How To Investigate a Go Test Failure \(internal\)](https://cockroachlabs.atlassian.net/l/c/HgfXfJgM)
</p>
</details>
/cc @cockroachdb/kv-triage
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*TestFlowControlBlockedAdmissionV2.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/bazci/githubpost/issues)

</sub>

Jira issue: CRDB-62447

### LINKED ISSUE #167422: kv/kvserver: TestFlowControlTransferLeaseV2 failed
kv/kvserver.TestFlowControlTransferLeaseV2 [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Ci_TestsAwsLinuxArm64_UnitTests/21295960?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Ci_TestsAwsLinuxArm64_UnitTests/21295960?buildTab=artifacts#/) on master @ [1cae9feb482c56614e0a3c488a3978daf9e75167](https://github.com/cockroachdb/cockroach/commits/1cae9feb482c56614e0a3c488a3978daf9e75167):

```
bytes.(*Buffer).ReadFrom(0x4017796628, {0x7e178a0, 0x4023d7a318})
	GOROOT/src/bytes/buffer.go:217 +0x90
crypto/tls.(*Conn).readFromUntil(0x4017796388, {0xf45126d6b9e8, 0x40194f9440}, 0x4004dc89f0?)
	GOROOT/src/crypto/tls/conn.go:838 +0xcc
crypto/tls.(*Conn).readRecordOrCCS(0x4017796388, 0x0)
	GOROOT/src/crypto/tls/conn.go:627 +0x340
crypto/tls.(*Conn).readRecord(...)
	GOROOT/src/crypto/tls/conn.go:589
crypto/tls.(*Conn).Read(0x4017796388, {0x4016de2000, 0x1000, 0x0?})
	GOROOT/src/crypto/tls/conn.go:1392 +0x14c
storj.io/drpc/drpcwire.(*Reader).read(0x40193497a0, {0x4016de2000, 0x1000, 0x1000})
	external/io_storj_drpc/drpcwire/reader.go:71 +0x6c
storj.io/drpc/drpcwire.(*Reader).ReadPacketUsing(0x40193497a0, {0x40130505a0?, 0x3c?, 0x60?})
	external/io_storj_drpc/drpcwire/reader.go:116 +0x364
storj.io/drpc/drpcmanager.(*Manager).manageReader(0x40093a45a0)
	external/io_storj_drpc/drpcmanager/manager.go:236 +0xc0
created by storj.io/drpc/drpcmanager.NewWithOptions in goroutine 81248
	external/io_storj_drpc/drpcmanager/manager.go:128 +0x364

goroutine 74034 [select, 14 minutes]:
github.com/cockroachdb/cockroach/pkg/sql.(*runnerCoordinator).init.func1({0x40177c56c0?, 0x7e6f538?})
	pkg/sql/distsql_running.go:173 +0x90
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunAsyncTaskEx.func1({0x7e6f538, 0x401c94ebe0})
	pkg/util/stop/stopper.go:447 +0x7c
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunAsyncTaskEx in goroutine 74002
	pkg/util/stop/stopper.go:445 +0xe0

goroutine 81753 [select, "tags":"n5,rnode=1,raddr=127.0.0.1:41639,class=rangefeed,rpc", "workload.id":"RPC_HEARTBEAT"]:
github.com/cockroachdb/cockroach/pkg/rpc.(*peer[...]).runHeartbeatUntilFailure(0x7f445c0, {0x7e6ee70, 0x4015c2ac00}, 0x4015ccc620)
	pkg/rpc/peer.go:552 +0x190
github.com/cockroachdb/cockroach/pkg/rpc.(*peer[...]).runOnce(0x7f445c0, {0x7e6ee70, 0x4015c2ac00}, 0x4003f40a90)
	pkg/rpc/peer.go:427 +0x258
github.com/cockroachdb/cockroach/pkg/rpc.(*peer[...]).run(0x7f445c0, {0x7e6ee70, 0x4015c2ac00}, 0x4003f40a90, 0x40176d9440)
	pkg/rpc/peer.go:356 +0x15c
github.com/cockroachdb/cockroach/pkg/rpc.(*peer[...]).launch.func1()
	pkg/rpc/peer.go:317 +0x40
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunAsyncTaskEx.func1({0x7e6ee70, 0x4015c2ac00})
	pkg/util/stop/stopper.go:447 +0x7c
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunAsyncTaskEx in goroutine 81752
	pkg/util/stop/stopper.go:445 +0xe0

goroutine 82119 [select]:
github.com/cockroachdb/cockroach/pkg/kv/kvclient/rangefeed/rangefeedcache.(*Watcher[...]).Run(0x7ebf300, {0x7e6ee38, 0x4008089090})
	pkg/kv/kvclient/rangefeed/rangefeedcache/watcher.go:344 +0x6e4
github.com/cockroachdb/cockroach/pkg/kv/kvclient/rangefeed/rangefeedcache.Start[...].func1()
	pkg/kv/kvclient/rangefeed/rangefeedcache/watcher.go:202 +0x1d8
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunAsyncTaskEx.func1({0x7e6f538, 0x4008fcf0e0})
	pkg/util/stop/stopper.go:447 +0x7c
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunAsyncTaskEx in goroutine 73273
	pkg/util/stop/stopper.go:445 +0xe0
```
<details><summary>Help</summary>
<p>

See also: [How To Investigate a Go Test Failure \(internal\)](https://cockroachlabs.atlassian.net/l/c/HgfXfJgM)
</p>
</details>
/cc @cockroachdb/kv-triage
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*TestFlowControlTransferLeaseV2.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/bazci/githubpost/issues)

</sub>

Jira issue: CRDB-62448

### LINKED ISSUE #167443: kv/kvserver: TestFlowControlGranterAdmitOneByOneV2 failed
kv/kvserver.TestFlowControlGranterAdmitOneByOneV2 [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Ci_TestsAwsLinuxArm64_UnitTests/21296417?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Ci_TestsAwsLinuxArm64_UnitTests/21296417?buildTab=artifacts#/) on master @ [fc60810b6fd26913d8c4c6d4ce3dda8cd01c36a1](https://github.com/cockroachdb/cockroach/commits/fc60810b6fd26913d8c4c6d4ce3dda8cd01c36a1):

```
created by storj.io/drpc/drpcmanager.NewWithOptions in goroutine 110140
	external/io_storj_drpc/drpcmanager/manager.go:129 +0x3a4

goroutine 109169 [select]:
storj.io/drpc/drpcmanager.(*Manager).manageStreams(0x401550dc20)
	external/io_storj_drpc/drpcmanager/manager.go:327 +0xc8
created by storj.io/drpc/drpcmanager.NewWithOptions in goroutine 109166
	external/io_storj_drpc/drpcmanager/manager.go:129 +0x3a4

goroutine 108255 [select]:
storj.io/drpc/drpcmanager.(*Manager).manageStream(0x4026c04960, {0x7e6f1f0, 0x4002984ae0}, 0x4019055908)
	external/io_storj_drpc/drpcmanager/manager.go:340 +0xb4
storj.io/drpc/drpcmanager.(*Manager).manageStreams(0x4026c04960)
	external/io_storj_drpc/drpcmanager/manager.go:329 +0x60
created by storj.io/drpc/drpcmanager.NewWithOptions in goroutine 109185
	external/io_storj_drpc/drpcmanager/manager.go:129 +0x3a4

goroutine 110327 [IO wait]:
internal/poll.runtime_pollWait(0xf16af8526200, 0x72)
	GOROOT/src/runtime/netpoll.go:351 +0xa0
internal/poll.(*pollDesc).wait(0x401b92e800?, 0x40223a7000?, 0x0)
	GOROOT/src/internal/poll/fd_poll_runtime.go:84 +0x28
internal/poll.(*pollDesc).waitRead(...)
	GOROOT/src/internal/poll/fd_poll_runtime.go:89
internal/poll.(*FD).Read(0x401b92e800, {0x40223a7000, 0x4800, 0x4800})
	GOROOT/src/internal/poll/fd_unix.go:165 +0x1e0
net.(*netFD).Read(0x401b92e800, {0x40223a7000?, 0x40223a7000?, 0x5?})
	GOROOT/src/net/fd_posix.go:68 +0x28
net.(*conn).Read(0x402e340690, {0x40223a7000?, 0x40308128e8?, 0x4900fc?})
	GOROOT/src/net/net.go:196 +0x34
crypto/tls.(*atLeastReader).Read(0x4001a49440, {0x40223a7000?, 0x4030812948?, 0x7f3474?})
	GOROOT/src/crypto/tls/conn.go:816 +0x38
bytes.(*Buffer).ReadFrom(0x401f8af7a8, {0x7e17c20, 0x4001a49440})
	GOROOT/src/bytes/buffer.go:217 +0x90
crypto/tls.(*Conn).readFromUntil(0x401f8af508, {0xf16afdafe670, 0x401444af00}, 0x40308129f0?)
	GOROOT/src/crypto/tls/conn.go:838 +0xcc
crypto/tls.(*Conn).readRecordOrCCS(0x401f8af508, 0x0)
	GOROOT/src/crypto/tls/conn.go:627 +0x340
crypto/tls.(*Conn).readRecord(...)
	GOROOT/src/crypto/tls/conn.go:589
crypto/tls.(*Conn).Read(0x401f8af508, {0x400da08000, 0xf000, 0x0?})
	GOROOT/src/crypto/tls/conn.go:1392 +0x14c
storj.io/drpc/drpcwire.(*Reader).read(0x4027072850, {0x400da08000, 0xf000, 0xf000})
	external/io_storj_drpc/drpcwire/reader.go:71 +0x6c
storj.io/drpc/drpcwire.(*Reader).ReadPacketUsing(0x4027072850, {0x4006108000?, 0xa8?, 0x8000?})
	external/io_storj_drpc/drpcwire/reader.go:116 +0x364
storj.io/drpc/drpcmanager.(*Manager).manageReader(0x40197710e0)
	external/io_storj_drpc/drpcmanager/manager.go:236 +0xc0
created by storj.io/drpc/drpcmanager.NewWithOptions in goroutine 110379
	external/io_storj_drpc/drpcmanager/manager.go:128 +0x364
```
<details><summary>Help</summary>
<p>

See also: [How To Investigate a Go Test Failure \(internal\)](https://cockroachlabs.atlassian.net/l/c/HgfXfJgM)
</p>
</details>
/cc @cockroachdb/kv-triage
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*TestFlowControlGranterAdmitOneByOneV2.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/bazci/githubpost/issues)

</sub>

Jira issue: CRDB-62459

### PR DESCRIPTION
**Pull request by arulajmani**
The leaseholder randomization introduced in #166760 can cause flow
control tests to stall indefinitely. These tests deliberately disable
admission control on specific nodes; if leaseholder randomization
kicks in during a slow config change (e.g., `AddVotersOrFatal` with
joint consensus), the cached leaseholder can be set to an AC-disabled
node, causing `h.put()` to block forever.

See https://github.com/cockroachdb/cockroach/issues/167371#issuecomment-4195466951
for the full root cause analysis.

The first commit introduces a `DontRandomizeLeaseholderOnCtxError`
testing knob. The middle commits are mechanical — each sets the knob on
one affected test. The last commit re-enables the 2s default (reverting
the temporary disable from #167646) and adds a 500ms floor with a
warning if someone sets the env var too low.

Fixes: #167371
Fixes: #167383
Fixes: #167396
Fixes: #167406
Fixes: #167415
Fixes: #167416
Fixes: #167421
Fixes: #167422
Fixes: #167443
Fixes: #167451
Fixes: #167486
Fixes: #167496
Fixes: #167372
Epic: none
Release note: None

### CODE REVIEW

File: pkg/kv/kvclient/kvcoord/dist_sender.go [hunk 1]
```diff
@@ -2434,8 +2444,9 @@ func (ds *DistSender) sendPartialBatch(
 	// See the documentation for the function
 	// (*EvictionToken).RandomizeLeaseholder() for an explanation.
 	if ctx.Err() != nil && routingTok.Valid() &&
-		randomizeLeaseholderOnContextErrorDuration > 0 &&
-		routingTok.SinceLeaseholderContacted() >= randomizeLeaseholderOnContextErrorDuration {
+		dur > 0 &&
+		routingTok.SinceLeaseholderContacted() >= dur &&
+		!ds.dontRandomizeLeaseholderOnCtxError {
```
Comment (pav-kv) [inline pkg/kv/kvclient/kvcoord/dist_sender.go]: Do we need two disabling mechanisms, or we could just ratchet up (or set zero) the threshold in the tests? E.g. `t.Setenv()` would do the job.

File: pkg/kv/kvclient/kvcoord/dist_sender.go [hunk 2]
```diff
@@ -2428,6 +2426,13 @@ func (ds *DistSender) sendPartialBatch(
 		log.KvExec.Fatal(ctx, "exited retry loop without an error or early exit")
 	}
 
+	dur := randomizeLeaseholderOnContextErrorDuration
+	if dur > 0 && dur < minRandomizeLeaseholderOnContextErrorDuration {
+		log.Dev.Warningf(ctx,
```
Comment (5hubh4m) [inline pkg/kv/kvclient/kvcoord/dist_sender.go]: Can we perform this check at module initialization and print one log line? Or do we wanna log this every time this error occurs?

File: pkg/kv/kvclient/kvcoord/dist_sender.go (hunk 1 above)
Comment (arulajmani) [reply pkg/kv/kvclient/kvcoord/dist_sender.go]: TIL about this t.Setenv thing. Strictly speaking, no, but mild preference for keeping the testing knob still.

File: pkg/kv/kvclient/kvcoord/dist_sender.go (hunk 2 above)
Comment (arulajmani) [reply pkg/kv/kvclient/kvcoord/dist_sender.go]: Good call. Done.

**Review by 5hubh4m — APPROVED** [review]
LGTM!
