### PR TITLE
workload: add last-duration flag to tpcc check

### LINKED ISSUE #147397: roachtest: weekly/tpcc/headroom failed
roachtest.weekly/tpcc/headroom [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestWeeklyBazel/19770378?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestWeeklyBazel/19770378?buildTab=artifacts#/weekly/tpcc/headroom) on master @ [faeec16ebdfa4e4b24815650941485eddc2d8a68](https://github.com/cockroachdb/cockroach/commits/faeec16ebdfa4e4b24815650941485eddc2d8a68):

```
(cluster.go:2462).Run: full command output in run_092001.030951280_n4_cockroach-workload-c.log: COMMAND_PROBLEM: exit status 1
test artifacts and logs in: /artifacts/weekly/tpcc/headroom/run_1
```

Parameters:
 - <code>arch=amd64</code>
 - <code>cloud=gce</code>
 - <code>coverageBuild=false</code>
 - <code>cpu=16</code>
 - <code>encrypted=true</code>
 - <code>fs=ext4</code>
 - <code>localSSD=true</code>
 - <code>metamorphicLeases=leader</code>
 - <code>runtimeAssertionsBuild=false</code>
 - <code>ssd=0</code>
<details><summary>Help</summary>
<p>

See: [roachtest README](https://github.com/cockroachdb/cockroach/blob/master/pkg/cmd/roachtest/README.md)

See: [How To Investigate \(internal\)](https://cockroachlabs.atlassian.net/l/c/SSSBr8c7)

See: [Grafana](https://go.crdb.dev/roachtest-grafana/teamcity-19770378/weekly-tpcc-headroom/1748077509317/1748424763537)

</p>
</details>
/cc @cockroachdb/test-eng
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*weekly/tpcc/headroom.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/bazci/githubpost/issues)

</sub>

Jira issue: CRDB-51033

### PR DESCRIPTION
**Pull request by herkolategan**
Previously, if a workload is run with a long duration, some of the consistency
checks would be skipped. This check is only done when running a workload, but
some tests also run a separate post check.

This post check is not aware of the previous workload's duration and will run
the checks even if the workload is run with a long duration.

This change adds a new flag, `last-duration`, which can be used to set the
duration of the previous workload run. This flag can be used during a post
consistency check to determine which checks to skip for long duration workloads.

Fixes: #147397

Epic: None
Release note: None

### CODE REVIEW

**Comment by herkolategan** [comment]
Have not run a smoke test. Will once I'm not on a train and have better WiFi.

File: pkg/workload/tpcc/tpcc.go [hunk 1]
```diff
@@ -267,6 +298,7 @@ var tpccMeta = workload.Meta{
 			`txn-retries`:              {RuntimeOnly: true},
 			`repair-order-ids`:         {RuntimeOnly: true},
 			`expensive-checks`:         {RuntimeOnly: true, CheckConsistencyOnly: true},
+			`last-duration`:            {RuntimeOnly: true, CheckConsistencyOnly: true},
```
Comment (srosenberg) [inline pkg/workload/tpcc/tpcc.go:301]: The flags just keep on creeping up... short of spelling out which checks to exclude, I don't see how to avoid yet another flag.

**Review by srosenberg — APPROVED** [review]
Thanks!

File: pkg/workload/tpcc/tpcc.go (hunk 1 above)
Comment (herkolategan) [reply pkg/workload/tpcc/tpcc.go:301]: Yep, I thought about re-using  "duration", but it would probably just add to the confusion, and require hacking to make a run flag appear for the "check" command, but be specific to tpcc.

**Comment by herkolategan** [comment]
Ran a check on TC, both run & check invoked: https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/19943994

**Comment by herkolategan** [comment]
TFTR!

bors r=srosenberg
