### PR TITLE
roachtest: de-flake 'inconsistent'

### LINKED ISSUE #54005: roachtest: inconsistency failed
[(roachtest).inconsistency failed](https://teamcity.cockroachdb.com/viewLog.html?buildId=2251139&tab=buildLog) on [master@8b9e8dc32e73cfdfc1999da35d61e5cc9a2b35ec](https://github.com/cockroachdb/cockroach/commits/8b9e8dc32e73cfdfc1999da35d61e5cc9a2b35ec):

```
test artifacts and logs in: /home/agent/work/.go/src/github.com/cockroachdb/cockroach/artifacts/inconsistency/run_1
	inconsistency.go:97,test_runner.go:754: dial tcp 35.225.170.169:26257: connect: connection refused

	cluster.go:1651,context.go:135,cluster.go:1640,test_runner.go:823: dead node detection: /home/agent/work/.go/src/github.com/cockroachdb/cockroach/bin/roachprod monitor teamcity-2251139-1599459125-22-n3cpu4 --oneshot --ignore-empty-nodes: exit status 1 1: dead
		2: dead
		3: 5692
		Error: UNCLASSIFIED_PROBLEM: 1: dead
		(1) UNCLASSIFIED_PROBLEM
		Wraps: (2) secondary error attachment
		  | 2: dead
		  | (1) attached stack trace
		  |   -- stack trace:
		  |   | main.glob..func14
		  |   | 	/home/agent/work/.go/src/github.com/cockroachdb/cockroach/pkg/cmd/roachprod/main.go:1143
		  |   | main.wrap.func1
		  |   | 	/home/agent/work/.go/src/github.com/cockroachdb/cockroach/pkg/cmd/roachprod/main.go:267
		  |   | github.com/spf13/cobra.(*Command).execute
		  |   | 	/home/agent/work/.go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:830
		  |   | github.com/spf13/cobra.(*Command).ExecuteC
		  |   | 	/home/agent/work/.go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:914
		  |   | github.com/spf13/cobra.(*Command).Execute
		  |   | 	/home/agent/work/.go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:864
		  |   | main.main
		  |   | 	/home/agent/work/.go/src/github.com/cockroachdb/cockroach/pkg/cmd/roachprod/main.go:1839
		  |   | runtime.main
		  |   | 	/usr/local/go/src/runtime/proc.go:203
		  |   | runtime.goexit
		  |   | 	/usr/local/go/src/runtime/asm_amd64.s:1357
		  | Wraps: (2) 2: dead
		  | Error types: (1) *withstack.withStack (2) *errutil.leafError
		Wraps: (3) attached stack trace
		  -- stack trace:
		  | main.glob..func14
		  | 	/home/agent/work/.go/src/github.com/cockroachdb/cockroach/pkg/cmd/roachprod/main.go:1143
		  | main.wrap.func1
		  | 	/home/agent/work/.go/src/github.com/cockroachdb/cockroach/pkg/cmd/roachprod/main.go:267
		  | github.com/spf13/cobra.(*Command).execute
		  | 	/home/agent/work/.go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:830
		  | github.com/spf13/cobra.(*Command).ExecuteC
		  | 	/home/agent/work/.go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:914
		  | github.com/spf13/cobra.(*Command).Execute
		  | 	/home/agent/work/.go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:864
		  | main.main
		  | 	/home/agent/work/.go/src/github.com/cockroachdb/cockroach/pkg/cmd/roachprod/main.go:1839
		  | runtime.main
		  | 	/usr/local/go/src/runtime/proc.go:203
		  | runtime.goexit
		  | 	/usr/local/go/src/runtime/asm_amd64.s:1357
		Wraps: (4) 1: dead
		Error types: (1) errors.Unclassified (2) *secondary.withSecondaryError (3) *withstack.withStack (4) *errutil.leafError

```

<details><summary>More</summary><p>

Artifacts: [/inconsistency](https://teamcity.cockroachdb.com/viewLog.html?buildId=2251139&tab=artifacts#/inconsistency)

[See this test on roachdash](https://roachdash.crdb.dev/?filter=status%3Aopen+t%3A.%2Ainconsistency.%2A&sort=title&restgroup=false&display=lastcommented+project)
<sub>powered by [pkg/cmd/internal/issues](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)</sub></p></details>

### PR DESCRIPTION
**Pull request by tbg**
This test sets up an intentionally corrupted replica and wants its node
to shut down as a result of its detection. When only two of the three
nodes were included in the consistency check, either one of them could
end up terminating (as no obvious majority of healthy replicas can be
determined). Change the test so that we wait for the cluster to come
fully together before setting a low consistency check interval.

Closes #54005.

Release justification: testing
Release note: None

### CODE REVIEW

File: pkg/cmd/roachtest/inconsistency.go [hunk 1]
```diff
@@ -85,6 +81,21 @@ func runInconsistency(ctx context.Context, t *test, c *cluster) {
 		}
 		return nil
 	})
+
+	// Give the cluster time to fully come together, then set an aggressive
+	// consistency check interval. This makes sure that the consistency check runs
+	// against all three nodes. If it targeted only two nodes, a random one would
+	// fatal - not what we want.
+	time.Sleep(20 * time.Second)
```
Comment (knz) [inline pkg/cmd/roachtest/inconsistency.go:89]: I stand behind moving the cluster setting change to after the call for `waitForFullReplication()~

However I do not understand the 20s wait - isn't `waitForFullReplication()` sufficient to "wait for the cluster to come together"? 


Also, separately, a question: the comment says "this makes sure that the consistency check runs against all three nodes". However the cluster setting change is onyl effected against node 2. Given that cluster settings take a little while to propagate, it looks to me like node 2 is the one that's going to predominently fall over, as it will start its checks before the other two nodes get the setting update. Is that intentional?

Comment (tbg) [reply pkg/cmd/roachtest/inconsistency.go:89]: > However I do not understand the 20s wait - isn't waitForFullReplication() sufficient to "wait for the cluster to come together"?

You're right that this should not be necessary. If replicas are moved to the node, it is likely (though not guaranteed, but alas) that it is considered live by all. Removed.

> Also, separately, a question: the comment says "this makes sure that the consistency check runs against all three nodes". However the cluster setting change is onyl effected against node 2. Given that cluster settings take a little while to propagate, it looks to me like node 2 is the one that's going to predominently fall over, as it will start its checks before the other two nodes get the setting update. Is that intentional?

The consistency check runs against all members of the range. It does not matter which node it gets run on, other than that that node's view of liveness determines who is probed as part of the check. I am choosing n2 here since n1 is the one we expect to die; it may already be dead (though it usually isn't).

**Review by knz — APPROVED** [review]
thanks for explaining.

**Comment by tbg** [comment]
bors r=knz
