### PR TITLE
log: ensure timely exit on fatal errors

### LINKED ISSUE #81025: log: blocked log file rotation can prevent fatal log lines from crashing process in a timely fashion
**Describe the problem**

An longer than typical log file rotation - a slow flush of the existing file, followed by latency creating the new file (e.g. in a period of elevated filesystem latency, or "stalls") - can prevent "fatal" log lines from crashing the process in a timely fashion.

**To Reproduce**

Assume the filesystem on which log files are written is under duress - certain operations may take many seconds to complete (specifically writes, syncs, and creation of new files).

Consider the following sequence of events during this period:
- a logging event triggers the rotation of a log file - this happens via the following calls:
  - [`(l *fileSink).output()` acquires the mutex for the log sink](https://github.com/cockroachdb/cockroach/blob/11787edfcfc157a0df951abc34684e4e18b3ef20/pkg/util/log/file.go#L183) before calling [`(l *fileSink).writeToFileLocked()`](https://github.com/cockroachdb/cockroach/blob/11787edfcfc157a0df951abc34684e4e18b3ef20/pkg/util/log/file.go#L190)
  - `(l *fileSink).writeToFileLocked()` [calls `Write()`](https://github.com/cockroachdb/cockroach/blob/11787edfcfc157a0df951abc34684e4e18b3ef20/pkg/util/log/file_sync_buffer.go#L59) on the sink's `flushSyncWriter` interface
  - the concrete type is a `syncBuffer`, with an implementation of `Write()` that [rotates the file](https://github.com/cockroachdb/cockroach/blob/11787edfcfc157a0df951abc34684e4e18b3ef20/pkg/util/log/file_sync_buffer.go#L46-L50) if it exceeds some limit
- this file rotation:
  - first [flushes the existing log file](https://github.com/cockroachdb/cockroach/blob/11787edfcfc157a0df951abc34684e4e18b3ef20/pkg/util/log/file_sync_buffer.go#L154)
  - [creates a new log file](https://github.com/cockroachdb/cockroach/blob/11787edfcfc157a0df951abc34684e4e18b3ef20/pkg/util/log/file_sync_buffer.go#L162)
  - either of these two operations could stall indefinitely

Assume the filesystem prevents rotating this log file.

Consider now another goroutine that wishes to crash the process by calling [`log.Fatalf`](https://github.com/cockroachdb/cockroach/blob/11787edfcfc157a0df951abc34684e4e18b3ef20/pkg/util/log/log_channels_generated.go#L734-L736). This function may need to log into the sink that is blocked waiting for its log file to rotate.

When logging a fatal event, [`logfDepth` first calls itself recursively with the same event, downgrading the severity to `INFO`](https://github.com/cockroachdb/cockroach/blob/11787edfcfc157a0df951abc34684e4e18b3ef20/pkg/util/log/channels.go#L67-L84). As this event is logged to the sink that is blocked on the file rotation, this recursive call blocks. This effectively prevents the "fatal" part (after the recursion pops back up) from occurring.

This sounds academic. However, in a real world example (see [this](https://github.com/cockroachlabs/support/issues/1571) support case), the following occurred:
- One or more storage volumes were degraded (at least one volume for a Pebble store, and another that backed the log files)
- A Pebble write / sync operation stalled.
- Pebble calls `Fatalf` after 60 seconds - at this point the process should crash.
- However, the process remained alive for 7 minutes.
- After the log file eventually rotated and the new file was created - the fatal event made its way through the logging framework and killed the process, printing the desired fatal line - albeit 7 minutes too late. 

**Expected behavior**

Calling `Fatalf` should crash the process as soon as reasonably possible, even if this means that logs may not be durably persisted in a timely fashion. It should honor the "fatal" part of the API.

**Additional data / screenshots**

We do already have a timer that should kill the process if logging is blocked. However, this is for syncing the file. There is an [existing TODO](https://github.com/cockroachdb/cockroach/blob/11787edfcfc157a0df951abc34684e4e18b3ef20/pkg/util/log/file.go#L243-L256) that points at #56893. The timer is only set after a the write has completed. The write may block (as explained above), so the timer is too late.

**Environment:**
 - CockroachDB version: observed on v21.2.9
 - Server OS: Linux

### PR DESCRIPTION
**Pull request by dhartunian**
Previously, a stall on the disk during file rotation could cause a Fatal
log entry to *not* exit the process in a timely manner as it would wait
on disk. This would happen because our exit timeout was only set in a
call to `shoutfDepth`. Unfortunately, `logfDepth` is called *before*
`shoutfDepth` when a `FATAL` log is emitted so the timeout was blocked
on writes.

This change moves the exit timeout call to a shared helper between
`logfDepth` and `shoutfDepth` ensuring that no matter what order they
are called in, `FATAL` log calls which always set an exit timeout in
case they block for too long.

Resolves https://github.com/cockroachdb/cockroach/issues/81025

Release note (ops change): Disk stalls no longer prevent the cockroach
process from crashing when Fatal errors are emitted.

### CODE REVIEW

File: pkg/util/log/channels.go [hunk 1]
```diff
@@ -42,9 +42,30 @@ func logfDepth(
...
+			exitFunc := func(x exit.Code, _ error) { exit.WithCode(x) }
+			logging.mu.Lock()
+			if logging.mu.exitOverride.f != nil {
+				exitFunc = logging.mu.exitOverride.f
+			}
+			logging.mu.Unlock()
+
+			opsLogFinished := make(chan struct{})
+			go func() {
+				logfDepth(ctx, depth+1, severity.INFO, channel.OPS,
```
Comment (tbg) [inline pkg/util/log/channels.go:57]: This changes the stack, need to check that this is OK. It probably is but need to think about it

**Review by knz — COMMENTED** [review]
I don't think that the added complexity inside the `if ch != channels.OPS` is the right way to go about this.

So, if we were just looking to address the issue at hand the change needed here is _much_ simpler:

1. take the code as originally written (revert the change as currently written)
2. move the `if sev == severity.FATAL` conditional (which adds the exit timeout) from under `shoutfDepth()` to `logfDepth()`

Suppose we did just this, would be sufficient to solve #81025.  

However, it would introduce a regression for an unrelated issue, fixed a long time ago (in v2.1 IIRC? unfortunately there's no commit message): if the process' stderr stream is blocked, it would prevent timeline exit upon log.Shout. It's important that `shoutfDepth` also implement a timeout for the direct write to OrigStderr.

We can achieve this using a more future-proof approach:

```
func logfDepth(
        ctx context.Context, depth int, sev Severity, ch Channel, format string, args ...interface{},
) {
   logfDepthInternal(ctx, depth+1, sev, ch, false /* shout */, format, args...)
}

func shoutfDepth(
        ctx context.Context, depth int, sev Severity, ch Channel, format string, args ...interface{},
) {
   logfDepthInternal(ctx, depth+1, sev, ch, true /* shout */, format, args...)
}

func logfDepthInternal(
        ctx context.Context, depth int, sev Severity, ch Channel, shout bool, format string, args ...interface{},
) {
        if sev == severity.FATAL {
                // ... (from previous impl of shoutfDepth)
                t := time.AfterFunc(...)
                defer t.Stop()
        }
        if shout && !LoggingToStderr(sev) {
                // ...
                fmt.Fprintf(OrigStderr, ...)
        }

        // (now include here all the previous code from logfDepth)
}
```

Now, with this simple refactoring, you've not added any new code/complexity and instead generalized the mechanism that was already available in shoutfDepth.

> Reviewed 1 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/81708#-:-N2q8ToiC-vVQ9m1m2Q-:b-tclgbq)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dhartunian and @nicktrav)

**Review by dhartunian — COMMENTED** [review]
@knz PTAL, thanks for the advice.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/81708#-:-N2reWSZ1XBkn4tHtEmO:b-odtr8g)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @nicktrav and @tbg)

___
*[`pkg/util/log/channels.go` line 57 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/81708#-N2nbmZGfKjg1bDnArAA-r2-57:-N2reZFoCY6usfW7CS7C:baxdjwn) ([raw file](https://github.com/cockroachdb/cockroach/blob/ee0ad33314663ff272500944c824dd131e3a2447/pkg/util/log/channels.go#L57)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

This changes the stack, need to check that this is OK. It probably is but need to think about it
</blockquote></details>

Done. Given Raphael's advice, the recursive `logfDepth` call is no longer in a new goroutine.

**Review by knz — COMMENTED** [review]
LGTM with nits

> Reviewed 1 of 2 files at r1, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/81708#-:-N2vwDLd0CeXpw4y-Uih:b3nilp)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dhartunian, @nicktrav, and @tbg)

___
*[`-- commits` line 11 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/81708#-N2vvgEn-5Gsf1n79lWq):*
might need a commit message update.
___
*[`pkg/util/log/channels.go` line 78 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/81708#-N2vvs5J-4_PIAYwxPr1:-N2vvs5J-4_PIAYwxPr2:b-xt3ah8) ([raw file](https://github.com/cockroachdb/cockroach/blob/125cbcb398ee546d705573826a7b9a8f5eec7008/pkg/util/log/channels.go#L78)):*
> ```Go
> 		// Fatal error handling later already tries to exit even if I/O should
> 		// block, but crash reporting might also be in the way.
> 		t := time.AfterFunc(ExitTimeoutOnFatalLog, func() {
> ```

I believe you want to pull the definition of the timer above the `if shout ...` so that the timeout logic also applies to the write to stderr.
___
*[`pkg/util/log/file_rotation_test.go` line 173 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/81708#-N2vw4aD54r2eb5mK_io:-N2vw4aD54r2eb5mK_ip:bpjme5w) ([raw file](https://github.com/cockroachdb/cockroach/blob/125cbcb398ee546d705573826a7b9a8f5eec7008/pkg/util/log/file_rotation_test.go#L173)):*
> ```Go
> 	// complete.
> 	require.Eventuallyf(t, func() bool {
> 		return observedExitCode != nil && observedExitCode.String() == "8"
> ```

why check the literal value "8"? is comparing against `exit.TimeoutAfterFatalError()` inadequate?

**Review by dhartunian — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/81708)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @knz, @nicktrav, and @tbg)

___
*[`-- commits` line 11 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/81708#-N2vvgEn-5Gsf1n79lWq):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

might need a commit message update.
</blockquote></details>

Done.
___
*[`pkg/util/log/channels.go` line 78 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/81708#-N2vvs5J-4_PIAYwxPr1:-N3tPVRK-BwwiVt_bYIu:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/125cbcb398ee546d705573826a7b9a8f5eec7008/pkg/util/log/channels.go#L78)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

I believe you want to pull the definition of the timer above the `if shout ...` so that the timeout logic also applies to the write to stderr.
</blockquote></details>

Done.
___
*[`pkg/util/log/file_rotation_test.go` line 173 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/81708#-N2vw4aD54r2eb5mK_io:-N3tPhRiCxOVbYstXMsc:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/125cbcb398ee546d705573826a7b9a8f5eec7008/pkg/util/log/file_rotation_test.go#L173)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

why check the literal value "8"? is comparing against `exit.TimeoutAfterFatalError()` inadequate?
</blockquote></details>

Done.

**Review by knz — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/81708#-:-N3tUe2Y4-F-PXMuaWu5:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @nicktrav and @tbg)

**Comment by nicktrav** [comment]
How backportable do we think this is?

**Comment by dhartunian** [comment]
@nicktrav I don't see any reason why we couldn't do 22.1
