### PR TITLE
server: delay job scheduler startup

### LINKED ISSUE #114842: server: scheduled jobs can startup before external storage is init'ed
Scheduled backups fail with `cannot create external storage before init` if they are scheduled to run just around the time of node startup. This was probably introduced in https://github.com/cockroachdb/cockroach/pull/98184/files#diff-104a11712684e520f0affa95e6a053faeb713306a10f69ee99b9729cc9dd1996.

Jira issue: CRDB-33708

### PR DESCRIPTION
**Pull request by stevendanna**
We previously moved external storage init after the sqlServer preStart
to ensure we have a SQL instance ID. Unfortunately, sqlServer.preStart
also started the job scheduler, which may immediately execute a job
that assumes that external storage has been initialized.

This is a minimal fix intended for backport that starts the job
scheduler after we initialize external storage.

Fixes https://github.com/cockroachdb/cockroach/issues/114842

Epic: none

Release note (bug fix): Fix a bug where scheduled jobs using external
storage providers may fail shortly after node startup.

### CODE REVIEW

**Comment by stevendanna** [comment]
Need to write some tests.

**Comment by stevendanna** [comment]
It would be nice to have a functional test that covers the bug here.  I'll see what we can do.

File: pkg/server/server.go [hunk 1]
```diff
@@ -2213,6 +2219,29 @@ func (s *topLevelServer) PreStart(ctx context.Context) error {
...
+		return nil
+	}
+	// The job scheduler may immediately start jobs that require
+	// external storage providers to be available. We expect the
+	// server start up ordering to ensure this. Hitting this error
+	// is a programming error somewhere in server startup.
+	if err := s.externalStorageBuilder.assertInitComplete(); err != nil {
+		return err
+	}
+	s.sqlServer.startJobScheduler(ctx, s.cfg.TestingKnobs)
```
Comment (adityamaru) [inline pkg/server/server.go:2241]: nit: is this to many layers of indirection? This init method is not really init'ing anything so maybe we can just move this logic to startJobScheduler? I don't feel strongly so feel free to ignore.

**Review by adityamaru — APPROVED** [review]

File: pkg/server/server.go (hunk 1 above)
Comment (stevendanna) [reply pkg/server/server.go:2241]: I kinda agree, but to me its kinda ugly either way. Having a function that just calls another function is definitely a bit meh. But then if we move that call inline here we suddenly have a number of more places where we reach into sqlServer's fields directly.

**Comment by stevendanna** [comment]
bors r=adityamaru

**Comment by stevendanna** [comment]
bors retry

**Comment by stevendanna** [comment]
blathers backport 23.2.0

**Comment by stevendanna** [comment]
blathers backport 23.2.0-rc
