### PR TITLE
sctest: Fix bug that backup/restore suite would secretely early return

### LINKED ISSUE #104205: sctest: Backup/Restore tests might secretly skip certain testdata
Running `TestBackup_base_create_function_in_txn` gives the following output:
<details>
  <summary>Unmaterialized Test Output</summary>
  
```
...
=== RUN   TestBackup_base_create_function_in_txn/backup_and_restore_at_stage_0_of_9
    cumulative.go:1255: finished
=== RUN   TestBackup_base_create_function_in_txn/backup_and_restore_at_stage_1_of_9
    cumulative.go:1255: finished
=== RUN   TestBackup_base_create_function_in_txn/backup_and_restore_at_stage_2_of_9
    cumulative.go:1255: finished
=== RUN   TestBackup_base_create_function_in_txn/backup_and_restore_at_stage_3_of_9
    cumulative.go:1255: finished
=== RUN   TestBackup_base_create_function_in_txn/backup_and_restore_at_stage_4_of_9
    cumulative.go:1255: finished
=== RUN   TestBackup_base_create_function_in_txn/backup_and_restore_at_stage_5_of_9
    cumulative.go:1255: finished
=== RUN   TestBackup_base_create_function_in_txn/backup_and_restore_at_stage_6_of_9
    cumulative.go:1255: finished
=== RUN   TestBackup_base_create_function_in_txn/backup_and_restore_at_stage_7_of_9
    cumulative.go:1255: finished
=== RUN   TestBackup_base_create_function_in_txn/backup_and_restore_at_stage_8_of_9
    cumulative.go:1255: finished
=== RUN   TestBackup_base_create_function_in_txn/backup_and_restore_at_stage_9_of_9
    cumulative.go:1255: finished
...
```
</details>
which looks good but a closer look into the test reveals that no actual test content was run (i.e. no backups are taken and no restores are run) because the test early returns. One can verify this easily with a debugger to find the early return point.

<br/>
<br/>
A valid backup/restore test output should be much longer and look something like
<details>
  <summary>Valid/Materialized Test Output</summary>
  
```
...
=== RUN   TestBackup_base_create_index_create_schema_separate_statements/backup_and_restore_at_stage_0_of_9
    cumulative.go:1208: stage 1/9 in PostCommitPhase (rollback=false) 0 "defaultdb" false
    cumulative.go:1208: stage 1/2 in PostCommitNonRevertiblePhase (rollback=true) 0 "defaultdb" false
    cumulative.go:1208: stage 2/2 in PostCommitNonRevertiblePhase (rollback=true) 0 "defaultdb" true
    cumulative.go:1240: reached final stage, waiting for completion
    cumulative.go:1255: finished
=== RUN   TestBackup_base_create_index_create_schema_separate_statements/backup_and_restore_at_stage_0_of_9/restore_database
    cumulative.go:1382: testing backup 0 (rollback=false)
=== RUN   TestBackup_base_create_index_create_schema_separate_statements/backup_and_restore_at_stage_0_of_9/restore_database_with_schema-only
    cumulative.go:1382: testing backup 0 (rollback=false)
=== RUN   TestBackup_base_create_index_create_schema_separate_statements/backup_and_restore_at_stage_0_of_9/restore_database#01
    cumulative.go:1382: testing backup 1 (rollback=false)
=== RUN   TestBackup_base_create_index_create_schema_separate_statements/backup_and_restore_at_stage_0_of_9/restore_database_with_schema-only#01
    cumulative.go:1382: testing backup 1 (rollback=false)
=== RUN   TestBackup_base_create_index_create_schema_separate_statements/backup_and_restore_at_stage_0_of_9/restore_database#02
    cumulative.go:1382: testing backup 2 (rollback=true)
=== RUN   TestBackup_base_create_index_create_schema_separate_statements/backup_and_restore_at_stage_0_of_9/restore_database_with_schema-only#02
    cumulative.go:1382: testing backup 2 (rollback=true)
=== RUN   TestBackup_base_create_index_create_schema_separate_statements/backup_and_restore_at_stage_0_of_9/restore_all_tables_in_database
    cumulative.go:1382: testing backup 2 (rollback=true)
=== RUN   TestBackup_base_create_index_create_schema_separate_statements/backup_and_restore_at_stage_1_of_9
    cumulative.go:1208: stage 1/9 in PostCommitPhase (rollback=false) 1 "defaultdb" false
    cumulative.go:1208: stage 2/9 in PostCommitPhase (rollback=false) 1 "defaultdb" false
    cumulative.go:1208: stage 1/2 in PostCommitNonRevertiblePhase (rollback=true) 1 "defaultdb" false
    cumulative.go:1208: stage 2/2 in PostCommitNonRevertiblePhase (rollback=true) 1 "defaultdb" true
    cumulative.go:1240: reached final stage, waiting for completion
    cumulative.go:1255: finished
=== RUN   TestBackup_base_create_index_create_schema_separate_statements/backup_and_restore_at_stage_1_of_9/restore_database
    cumulative.go:1382: testing backup 0 (rollback=false)
=== RUN   TestBackup_base_create_index_create_schema_separate_statements/backup_and_restore_at_stage_1_of_9/restore_database_with_schema-only
    cumulative.go:1382: testing backup 0 (rollback=false)
=== RUN   TestBackup_base_create_index_create_schema_separate_statements/backup_and_restore_at_stage_1_of_9/restore_database#01
    cumulative.go:1382: testing backup 1 (rollback=false)
=== RUN   TestBackup_base_create_index_create_schema_separate_statements/backup_and_restore_at_stage_1_of_9/restore_database_with_schema-only#01
    cumulative.go:1382: testing backup 1 (rollback=false)
=== RUN   TestBackup_base_create_index_create_schema_separate_statements/backup_and_restore_at_stage_1_of_9/restore_database#02
    cumulative.go:1382: testing backup 2 (rollback=true)
=== RUN   TestBackup_base_create_index_create_schema_separate_statements/backup_and_restore_at_stage_1_of_9/restore_database_with_schema-only#02
    cumulative.go:1382: testing backup 2 (rollback=true)
=== RUN   TestBackup_base_create_index_create_schema_separate_statements/backup_and_restore_at_stage_1_of_9/restore_all_tables_in_database
    cumulative.go:1382: testing backup 2 (rollback=true)
...
```
</details>

Jira issue: CRDB-28409

### PR DESCRIPTION
**Pull request by Xiang-Gu**
Previously, the backup/restore testing suite would quietly early return
    on certain test cases without running any actual content (i.e. no
    backups were taken nor restores were done). This commit fixes that.

  Fix #104205

   Release note: None

### CODE REVIEW

File: pkg/sql/schemachanger/sctest/cumulative.go [hunk 1]
```diff
@@ -1100,23 +1100,20 @@ func Backup(t *testing.T, path string, newCluster NewClusterFunc) {
...
-					if !closedStageChan {
+				if p.Stages[stageIdx].Phase == scop.StatementPhase {
+					return nil
+				}
+				if p.Stages[stageIdx].Phase == scop.PreCommitPhase {
+					if p.Stages[len(p.Stages)-1].Phase < scop.PostCommitPhase && !closedStageChan {
+						// We've seen all stmts in the test case (bc we're in PreCommitPhase)
+						// and there is no PostCommitPhase in the plan. Close stageChan eagerly
+						// and use a bool to ensure we only close it once.
 						closedStageChan = true
```
Comment (postamar) [inline pkg/sql/schemachanger/sctest/cumulative.go:1111]: nit: use sync.Once and update comment

**Review by postamar — APPROVED** [review]
