### PR TITLE
log: Fix decoding large entries and speed up multiline parsing

### LINKED ISSUE #15958: ui: Logs page fails if node's log file is too big
I'm not sure where things are getting stuck, but if there are too many log entries the logs page fails to load any of the logs, instead just showing a "No data" error:

screen shot 2017-05-16 at 12 58 21 pm

This happened locally on a one-node cluster with >10MB of logs, both before and after #15949. It's easy to repro by just starting a node with `--verbosity=3` and waiting a few minutes.

### PR DESCRIPTION
**Pull request by a-robinson**
**log: Fix speed regression from matching multiline log messages**
I tested this on a 4MB log file with 11k entries, and it takes:

580ms without any multiline matching
24.6s before this change
620ms after this change

**log: Don't choke when decoding log entries too big for bufio.Scanner**
This was broken before #15949, but we're more likely to hit it
afterwards. It's unlikely to ever matter unless running with high
verbosity, but gets hit pretty quickly when you do so.

Fixes #15958

### CODE REVIEW

File: pkg/util/log/clog.go [hunk 1]
```diff
@@ -383,14 +391,38 @@ func (d *EntryDecoder) split(data []byte, atEOF bool) (advance int, token []byte
...
 		}
-		// Request more data.
+		if len(data) >= bufio.MaxScanTokenSize {
+			// If there's no room left in the buffer, returning the current
+			// truncated entry.
+			d.truncatedLastEntry = true
+			return len(data), data, nil
+		}
+		// If there is still room to read more, ask for more before deciding whether
+		// to truncate the entry.
```
Comment (petermattis) [inline pkg/util/log/clog.go]: Thanks for the plentiful comments.

File: pkg/util/log/clog.go [hunk 2]
```diff
@@ -351,7 +359,7 @@ func (d *EntryDecoder) Decode(entry *Entry) error {
 			return io.EOF
 		}
 		b := d.scanner.Bytes()
-		m := entryRE.FindSubmatch(b)
+		m := entryCaptureRE.FindSubmatch(b)
```
Comment (petermattis) [inline pkg/util/log/clog.go]: Rather than have a separate `entryCaptureRE`, I think we could find the index of the file:line match and strip of the prefix. Or perhaps change `entryMatchRE` to be `(?m)^([IWEF])(\d{6} \d{2}:\d{2}:\d{2}.\d{6}) (?:(\d+) )?([^:]+):(\d+)  `.

File: pkg/util/log/clog_test.go [hunk 3]
```diff
@@ -173,6 +187,7 @@ func TestEntryDecoder(t *testing.T) {
 				}
 				t.Fatal(err)
 			}
+			fmt.Println(len(entry.Message))
```
Comment (petermattis) [inline pkg/util/log/clog_test.go]: Did you mean to leave this in?

File: pkg/util/log/clog_test.go [hunk 4]
```diff
@@ -155,12 +156,25 @@ func TestEntryDecoder(t *testing.T) {
...
 	contents += formatEntry(Severity_INFO, t2, 1, "clog_test.go", 137, "multi-\nline")
-	contents += formatEntry(Severity_WARNING, t3, 2, "clog_test.go", 138, "warning")
-	contents += formatEntry(Severity_ERROR, t4, 3, "clog_test.go", 139, "error")
-	contents += formatEntry(Severity_FATAL, t5, 4, "clog_test.go", 140, "fatal\nstack\ntrace")
+	contents += formatEntry(Severity_INFO, t3, 2, "clog_test.go", 138, reallyLongEntry)
+	contents += formatEntry(Severity_INFO, t4, 3, "clog_test.go", 139, tooLongEntry)
+	contents += formatEntry(Severity_WARNING, t5, 4, "clog_test.go", 140, "warning")
+	contents += formatEntry(Severity_ERROR, t6, 5, "clog_test.go", 141, "error")
+	contents += formatEntry(Severity_FATAL, t7, 6, "clog_test.go", 142, "fatal\nstack\ntrace")
+	contents += formatEntry(Severity_INFO, t8, 7, "clog_test.go", 143, tooLongEntry)
```
Comment (petermattis) [inline pkg/util/log/clog_test.go]: Perhaps test what happens to the next message after the `tooLongEntry`.

**Review by petermattis — APPROVED** [review]

File: pkg/util/log/clog.go (hunk 2 above)
Comment (a-robinson) [inline pkg/util/log/clog.go]: We could strip the prefix, yeah, but then as far as I can tell we'd have to run the regex twice here (or the regex once and some other logic once) -- once to to capture the groups and once to figure out where the message starts since otherwise the length of the matched portion isn't known.

I've gone with your second suggestion and removed the message part from `entryMatchRE`.

**Comment by petermattis** [comment]
:lgtm:

---

Review status: 0 of 2 files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

*[pkg/util/log/clog.go, line 362 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/15972#-KkI60aWTpiyAUwKFER6-r1-362:-KkMR6EWKcdcvm05QVt4:bofyps3) ([raw file](https://github.com/cockroachdb/cockroach/blob/69bd2db711f82faef03d01f7537c6a90819bd4d3/pkg/util/log/clog.go#L362)):*
<details><summary><i>Previously, a-robinson (Alex Robinson) wrote…</i></summary><blockquote>

We could strip the prefix, yeah, but then as far as I can tell we'd have to run the regex twice here (or the regex once and some other logic once) -- once to to capture the groups and once to figure out where the message starts since otherwise the length of the matched portion isn't known.

I've gone with your second suggestion and removed the message part from `entryMatchRE`.
</blockquote></details>

My thought was to run the regex once and then take everything from the end of `entryMatchRE` to the end of the scanner token as `entry.Message`. What you have here is likely fine. 

---

*[pkg/util/log/clog_test.go, line 177 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/15972#-KkI60aWTpiyAUwKFER7-r1-177:-KkMRQHgQ14FJFHMo8C2:btqntq6) ([raw file](https://github.com/cockroachdb/cockroach/blob/69bd2db711f82faef03d01f7537c6a90819bd4d3/pkg/util/log/clog_test.go#L177)):*
<details><summary><i>Previously, a-robinson (Alex Robinson) wrote…</i></summary><blockquote>

That gets tested above - I put in two test cases with `tooLongEntry` specifically to test both what happens with entries after it and what happens at the end of the file.
</blockquote></details>

Ah, missed that. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15972#-:-KkMRV0qAj0NFxYQOO9t:bnfp4nl)*

**Comment by a-robinson** [comment]
Review status: 0 of 2 files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

*[pkg/util/log/clog.go, line 362 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/15972#-KkI60aWTpiyAUwKFER6-r1-362:-KkMRyi90d7nWbBdrjsQ:bdffype) ([raw file](https://github.com/cockroachdb/cockroach/blob/69bd2db711f82faef03d01f7537c6a90819bd4d3/pkg/util/log/clog.go#L362)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

My thought was to run the regex once and then take everything from the end of `entryMatchRE` to the end of the scanner token as `entry.Message`. What you have here is likely fine. 
</blockquote></details>

Right, but how do we tell where the end of `entryMatchRE` is in the string without doing a second run of matching logic or adding some fragile counting of the sizes of each captured group? Go's regexp package doesn't appear to have a single function that does both things, and the log text that `entryMatchRE` matches isn't a fixed size.

I'm going to keep it like this.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15972)*

**Comment by petermattis** [comment]
Review status: 0 of 2 files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

*[pkg/util/log/clog.go, line 362 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/15972#-KkI60aWTpiyAUwKFER6-r1-362:-KkMdJgHfSgNuqbT26Qy:biqzf4q) ([raw file](https://github.com/cockroachdb/cockroach/blob/69bd2db711f82faef03d01f7537c6a90819bd4d3/pkg/util/log/clog.go#L362)):*
<details><summary><i>Previously, a-robinson (Alex Robinson) wrote…</i></summary><blockquote>

Right, but how do we tell where the end of `entryMatchRE` is in the string without doing a second run of matching logic or adding some fragile counting of the sizes of each captured group? Go's regexp package doesn't appear to have a single function that does both things, and the log text that `entryMatchRE` matches isn't a fixed size.

I'm going to keep it like this.
</blockquote></details>

The first match (`m[0]`) is for the entire regexp. I was thinking of something like: https://play.golang.org/p/rFA5BXzi8q

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15972)*

**Comment by a-robinson** [comment]
Review status: 0 of 2 files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

*[pkg/util/log/clog.go, line 362 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/15972#-KkI60aWTpiyAUwKFER6-r1-362:-KkMe5CoARO73loQgNVV:b4yxh03) ([raw file](https://github.com/cockroachdb/cockroach/blob/69bd2db711f82faef03d01f7537c6a90819bd4d3/pkg/util/log/clog.go#L362)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

The first match (`m[0]`) is for the entire regexp. I was thinking of something like: https://play.golang.org/p/rFA5BXzi8q
</blockquote></details>

Ugh, you're right, I need to read better. I do like that more than having separate regexes.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15972)*

**Comment by petermattis** [comment]
Review status: 0 of 2 files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

*[pkg/util/log/clog.go, line 362 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/15972#-KkI60aWTpiyAUwKFER6-r1-362:-KkMf0fe69DvY4m6jRTi:b-t3zsyx) ([raw file](https://github.com/cockroachdb/cockroach/blob/69bd2db711f82faef03d01f7537c6a90819bd4d3/pkg/util/log/clog.go#L362)):*
<details><summary><i>Previously, a-robinson (Alex Robinson) wrote…</i></summary><blockquote>

Ugh, you're right, I need to read better. I do like that more than having separate regexes.
</blockquote></details>

Note that the regex in the playground link contains the spaces between the header and the message, but I'm not sure if that is necessary given the `strings.TrimSpace` below.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15972)*
