### PR TITLE
batchevel: make cmd_truncate_log use the log engine

### LINKED ISSUE #157895: batcheval: plumb log engine to TruncateLog cmd
In #156537, we are confirming that there are only a few exceptions of commands in the eval stack that access log/raft engine keys. We want these to be removed (e.g. the `RaftTruncatedState` write in splits has moved below raft), or justified and worked around.

The log truncation command needs to compute stats delta over the truncated portion of the log, so that followers don't repeat this computation:

https://github.com/cockroachdb/cockroach/blob/6816c43040b24bb221d00717c91f6a68a1a8e191/pkg/kv/kvserver/batcheval/cmd_truncate_log.go#L113-L124

Long-term, this can be removed in favour of something like #136358. Short-term, we need to plumb the log engine from `Replica` to `TruncateLog`.

It is probably not worth changing the entire eval function signature just for this, rather it would be prudent to add something to the [EvalContext](https://github.com/cockroachdb/cockroach/blob/6816c43040b24bb221d00717c91f6a68a1a8e191/pkg/kv/kvserver/batcheval/declare.go#L205). For example, this command already accesses the raft log via the [GetTerm](https://github.com/cockroachdb/cockroach/blob/6816c43040b24bb221d00717c91f6a68a1a8e191/pkg/kv/kvserver/batcheval/cmd_truncate_log.go#L78-L82) func plumbed through the `EvalContext`.

Epic: CRDB-55220
Jira issue: CRDB-57002

### PR DESCRIPTION
**Pull request by iskettaneh**
This is the last known place where touch the unreplicated rangeID local keyspace. This commit provides the LogEngine through EvalCtx so that cmd_truncate_log can use it to compute the stats.

Fixes: #157895

Release note: None

### CODE REVIEW

File: pkg/kv/kvserver/batcheval/cmd_truncate_log.go [hunk 1]
```diff
@@ -118,7 +118,10 @@ func TruncateLog(
 	// are not tracked in the raft log delta. The delta will be adjusted below
 	// raft.
 	// We can pass zero as nowNanos because we're only interested in SysBytes.
-	ms, err := storage.ComputeStats(ctx, readWriter, start, end, 0 /* nowNanos */)
+	// Use the log engine to compute stats for the raft log.
+	// TODO(#136358): After we precisely maintain the Raft Log size, we could stop
+	// needing the Log Engine to compute the stats.
+	ms, err := storage.ComputeStats(ctx, cArgs.EvalCtx.LogEngine(), start, end, 0 /* nowNanos */)
```
Comment (pav-kv) [inline pkg/kv/kvserver/batcheval/cmd_truncate_log.go]: I think there is some clean up due here, we can TODO it.

```
TODO(pav-kv): hide GetCompactedIndex, GetTerm, LogEngine in a raft log accessor.
```

Rn `EvalContext` gives us 3 methods (see how they are used above): `GetCompactedIndex`, `GetTerm`, and now `LogEngine()`. Logically, these all belong to the "raft log storage" (we have `replicaLogStorage` type and the `logstore` package).

So I think we could, instead of cluttering `EvalContext` with these lower-level methods, have it give us the raft log "accessor", through which we would get these things.

E.g. for log stats we already have this (which, though, takes sideloaded entries into account, whereas here we purposefully skip them):

https://github.com/cockroachdb/cockroach/blob/9d2b6d9bd355381d99dd9feda9b91b08703a483f/pkg/kv/kvserver/logstore/logstore.go#L524-L543

File: pkg/kv/kvserver/batcheval/cmd_truncate_log_test.go [hunk 2]
```diff
@@ -64,22 +64,36 @@ func TestTruncateLog(t *testing.T) {
...
 		Index: compactedIndex + 2,
 		Term:  term,
 	}
 
-	putTruncatedState(t, eng, rangeID, truncState)
+	putTruncatedState(t, stateEng, rangeID, truncState)
+
+	// Write some raft log entries to the log engine to create non-zero stats.
+	// These entries will be "truncated" by our request.
+	for i := compactedIndex + 2; i < compactedIndex+8; i++ {
```
Comment (pav-kv) [inline pkg/kv/kvserver/batcheval/cmd_truncate_log_test.go]: The invariant is: we can't have a gap between `compactedIndex` and existing entries. Start from `i := compactedIndex+1`?

File: pkg/kv/kvserver/batcheval/cmd_truncate_log_test.go [hunk 3]
```diff
@@ -64,22 +64,36 @@ func TestTruncateLog(t *testing.T) {
...
+		key := keys.RaftLogKey(rangeID, kvpb.RaftIndex(i))
+		err := logEng.PutUnversioned(key, []byte("some-data"))
+		require.NoError(t, err)
```
Comment (pav-kv) [inline pkg/kv/kvserver/batcheval/cmd_truncate_log_test.go]: nit:

```golang
require.NoError(t, logEng.PutUnversioned(...))
```

File: pkg/kv/kvserver/batcheval/cmd_truncate_log_test.go [hunk 4]
```diff
@@ -91,7 +105,7 @@ func TestTruncateLog(t *testing.T) {
 		Args:    &req,
 	}
 	resp := &kvpb.TruncateLogResponse{}
-	res, err := TruncateLog(ctx, eng, cArgs, resp)
+	res, err := TruncateLog(ctx, stateEng, cArgs, resp)
 	if err != nil {
 		t.Fatal(err)
 	}
```
Comment (pav-kv) [inline pkg/kv/kvserver/batcheval/cmd_truncate_log_test.go]: While here, `require.NoError(t, err)`?

File: pkg/kv/kvserver/batcheval/cmd_truncate_log.go (hunk 1 above)
Comment (iskettaneh) [reply pkg/kv/kvserver/batcheval/cmd_truncate_log.go]: I took a stab at it. Does it match your expectations (second commit)?

File: pkg/kv/kvserver/raftlog/accessor.go [hunk 5]
```diff
@@ -0,0 +1,41 @@
...
+
+package raftlog
+
+import (
+	"github.com/cockroachdb/cockroach/pkg/kv/kvpb"
+	"github.com/cockroachdb/cockroach/pkg/storage"
+)
+
+// Accessor provides access to the raft log storage.
+type Accessor interface {
```
Comment (iskettaneh) [inline pkg/kv/kvserver/raftlog/accessor.go]: @pav-kv Do you have some better location in mind to define this interface and that it avoids a circular dependency?

File: pkg/kv/kvserver/batcheval/cmd_truncate_log_test.go (hunk 2 above)
Comment (iskettaneh) [reply pkg/kv/kvserver/batcheval/cmd_truncate_log_test.go]: Done.

File: pkg/kv/kvserver/batcheval/cmd_truncate_log_test.go (hunk 4 above)
Comment (iskettaneh) [reply pkg/kv/kvserver/batcheval/cmd_truncate_log_test.go]: Done.

**Review by iskettaneh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/157932)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @pav-kv)

File: pkg/kv/kvserver/batcheval/cmd_truncate_log.go (hunk 1 above)
Comment (iskettaneh) [reply pkg/kv/kvserver/batcheval/cmd_truncate_log.go]: Discussed offline, we decided to not do the LogAccessor for now, and think more about it later.

Comment (pav-kv) [reply pkg/kv/kvserver/batcheval/cmd_truncate_log.go]: A couple of caveats here. I'm pretty sure we don't hold `raftMu` here, but perhaps even not `Replica.mu` (judging by the fact that both `GetTerm()` and `GetCompactedIndex()` above lock `mu` internally). Could double-check, but I'm pretty sure.

So the whole thing is a bit wacky (pre-existing). One more reason to hide all 3 things behind one call that does everything and does the locking right. Can update the TODO correspondingly: we should hide the whole "prepare truncation" instead of a more flexible accessor.

Another caveat is with using `LogEngine()` directly: it's a `storage.Engine`, which does implement `storage.Reader`, but we ideally want to be sure the reader provides a consistent view (same as `readWriter` does before this PR). Could you do this for now:

```golang
logReader := cArgs.EvalCtx.LogEngine().NewReader()
defer logReader.Close()
ComputeStats(logReader)
```

Comment (iskettaneh) [reply pkg/kv/kvserver/batcheval/cmd_truncate_log.go]: 1) I don't think that raftMu  or Replica.Mu are held during the evaluation. I didn't want to take the mutex when returning the LogEngine, as it is part of the "store", not necessarily the replica. Do you think it's necessary?

2) Oh that's a good point. I added:
```
	logReader := cArgs.EvalCtx.LogEngine().NewReader(storage.StandardDurability)
	defer logReader.Close()
```

File: pkg/kv/kvserver/batcheval/cmd_truncate_log.go [hunk 6]
```diff
@@ -118,7 +118,12 @@ func TruncateLog(
 	// are not tracked in the raft log delta. The delta will be adjusted below
 	// raft.
 	// We can pass zero as nowNanos because we're only interested in SysBytes.
-	ms, err := storage.ComputeStats(ctx, readWriter, start, end, 0 /* nowNanos */)
+	// Use the log engine to compute stats for the raft log.
+	// TODO(#136358): After we precisely maintain the Raft Log size, we could stop
+	// needing the Log Engine to compute the stats.
+	logReader := cArgs.EvalCtx.LogEngine().NewReader(storage.StandardDurability)
+	defer logReader.Close()
+	ms, err := storage.ComputeStats(ctx, logReader, start, end, 0 /* nowNanos */)
```
Comment (pav-kv) [inline pkg/kv/kvserver/batcheval/cmd_truncate_log.go]: Could you move this block above the "Compute the stats delta..." comment? The latter describes the `ComputeStats` invocation. Also, please add the following TODO to revisit the consistency/locking here.

```golang
// TODO(pav-kv): GetCompactedIndex, GetTerm, and NewReader calls can disagree
// on the state of the log since we don't hold any Replica locks here. Move
// the computation inside Replica where locking can be controlled precisely.

// Use the log engine...
// TODO(#136358): After we precisely ...
logReader := ...
defer ...
// Compute the stats ...
ms, err := 
```

**Review by pav-kv — APPROVED** [review]

File: pkg/kv/kvserver/batcheval/cmd_truncate_log.go (hunk 1 above)
Comment (pav-kv) [reply pkg/kv/kvserver/batcheval/cmd_truncate_log.go]: > I didn't want to take the mutex when returning the LogEngine, as it is part of the "store", not necessarily the replica. Do you think it's necessary?

It's a pre-existing issue. See TODO in another comment. The solution here, roughly, would be to have one call (run inside `Replica` through the `EvalContext` method) that does:

1. Under `Replica.mu`, look at the compacted index, get the term, grab the reader.
2. After releasing `Replica.mu`, compute the stats (the reader will remain consistent with what we've done under the mutex).
3. Return all that back to this eval command.

Comment (pav-kv) [reply pkg/kv/kvserver/batcheval/cmd_truncate_log.go]: If you want, can tackle it in this PR or the next one.

Comment (iskettaneh) [reply pkg/kv/kvserver/batcheval/cmd_truncate_log.go]: Will do it in a next PR
