### PR TITLE
roachtest: fix allow_unsafe_internals edge cases

### LINKED ISSUE #156702: roachtest: network/authentication/nodes=4 failed
roachtest.network/authentication/nodes=4 [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/20683769?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/20683769?buildTab=artifacts#/network/authentication/nodes=4) on master @ [40030306caf369f2a052870dd4aff0db2de97169](https://github.com/cockroachdb/cockroach/commits/40030306caf369f2a052870dd4aff0db2de97169):

```
(monitor.go:267).Wait: monitor failure: COMMAND_PROBLEM: exit status 127
test artifacts and logs in: /artifacts/network/authentication/nodes=4/run_1
```

Parameters:
 - <code>arch=amd64</code>
 - <code>cloud=gce</code>
 - <code>coverageBuild=false</code>
 - <code>cpu=4</code>
 - <code>encrypted=false</code>
 - <code>metamorphicLeases=leader</code>
 - <code>metamorphicWriteBuffering=true</code>
 - <code>runtimeAssertionsBuild=false</code>
 - <code>ssd=0</code>
<details><summary>Help</summary>
<p>

See: [roachtest README](https://github.com/cockroachdb/cockroach/blob/master/pkg/cmd/roachtest/README.md)

See: [How To Investigate \(internal\)](https://cockroachlabs.atlassian.net/l/c/SSSBr8c7)

See: [Grafana](https://go.crdb.dev/roachtest-grafana/teamcity-20683769/network-authentication-nodes-4/1761978020250/1761978257674)

</p>
</details>
/cc @cockroachdb/kv-triage
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*network/authentication/nodes=4.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/bazci/githubpost/issues)

</sub>

Jira issue: CRDB-56124

### LINKED ISSUE #156703: roachtest: copyfrom/crdb-atomic/sf=1/nodes=1 failed
roachtest.copyfrom/crdb-atomic/sf=1/nodes=1 [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/20683769?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/20683769?buildTab=artifacts#/copyfrom/crdb-atomic/sf=1/nodes=1) on master @ [40030306caf369f2a052870dd4aff0db2de97169](https://github.com/cockroachdb/cockroach/commits/40030306caf369f2a052870dd4aff0db2de97169):

```
(cluster.go:2512).Run: full command output in run_063603.007526714_n1_psql-postgresimporte.log: COMMAND_PROBLEM: exit status 2
(monitor.go:267).Wait: monitor failure: monitor user task failed: t.Fatal() was called
test artifacts and logs in: /artifacts/copyfrom/crdb-atomic/sf=1/nodes=1/run_1
```

Parameters:
 - <code>arch=amd64</code>
 - <code>cloud=gce</code>
 - <code>coverageBuild=false</code>
 - <code>cpu=4</code>
 - <code>encrypted=false</code>
 - <code>metamorphicLeases=default</code>
 - <code>runtimeAssertionsBuild=false</code>
 - <code>ssd=0</code>
<details><summary>Help</summary>
<p>

See: [roachtest README](https://github.com/cockroachdb/cockroach/blob/master/pkg/cmd/roachtest/README.md)

See: [How To Investigate \(internal\)](https://cockroachlabs.atlassian.net/l/c/SSSBr8c7)

See: [Grafana](https://go.crdb.dev/roachtest-grafana/teamcity-20683769/copyfrom-crdb-atomic-sf-1-nodes-1/1761978894996/1761979104302)

</p>
</details>
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*copyfrom/crdb-atomic/sf=1/nodes=1.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/bazci/githubpost/issues)

</sub>

Jira issue: CRDB-56125

### LINKED ISSUE #156706: roachtest: copyfrom/crdb-nonatomic/sf=1/nodes=1 failed
roachtest.copyfrom/crdb-nonatomic/sf=1/nodes=1 [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/20683769?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/20683769?buildTab=artifacts#/copyfrom/crdb-nonatomic/sf=1/nodes=1) on master @ [40030306caf369f2a052870dd4aff0db2de97169](https://github.com/cockroachdb/cockroach/commits/40030306caf369f2a052870dd4aff0db2de97169):

```
(cluster.go:2512).Run: full command output in run_100712.267589648_n1_psql-postgresimporte.log: COMMAND_PROBLEM: exit status 2
(monitor.go:267).Wait: monitor failure: monitor user task failed: t.Fatal() was called
test artifacts and logs in: /artifacts/copyfrom/crdb-nonatomic/sf=1/nodes=1/run_1
```

Parameters:
 - <code>arch=amd64</code>
 - <code>cloud=gce</code>
 - <code>coverageBuild=false</code>
 - <code>cpu=4</code>
 - <code>encrypted=false</code>
 - <code>fs=ext4</code>
 - <code>localSSD=true</code>
 - <code>metamorphicLeases=epoch</code>
 - <code>runtimeAssertionsBuild=false</code>
 - <code>ssd=0</code>
<details><summary>Help</summary>
<p>

See: [roachtest README](https://github.com/cockroachdb/cockroach/blob/master/pkg/cmd/roachtest/README.md)

See: [How To Investigate \(internal\)](https://cockroachlabs.atlassian.net/l/c/SSSBr8c7)

See: [Grafana](https://go.crdb.dev/roachtest-grafana/teamcity-20683769/copyfrom-crdb-nonatomic-sf-1-nodes-1/1761991557273/1761991773507)

</p>
</details>
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*copyfrom/crdb-nonatomic/sf=1/nodes=1.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/bazci/githubpost/issues)

</sub>

Jira issue: CRDB-56128

### PR DESCRIPTION
**Pull request by DarrylWong**
In https://github.com/cockroachdb/cockroach/pull/156581, we started setting `allow_unsafe_internals` unconditionally for roachtests. However, there are a few edge cases where we can't set this. Namely when using `psql` to connect to a postgres database where the CRDB only parameter does not exist.

Fixes: https://github.com/cockroachdb/cockroach/issues/156702
Fixes: https://github.com/cockroachdb/cockroach/issues/156703
Fixes: https://github.com/cockroachdb/cockroach/issues/156706

Release note: none

### CODE REVIEW

File: pkg/cmd/roachtest/tests/network.go [hunk 1]
```diff
@@ -206,7 +202,7 @@ SELECT $1::INT = ALL (
 				}
 
 				// Construct a connection URL to server i.
-				url := serverUrls[server-1]
+				url := fmt.Sprintf("{pgurl:%d}", server-1)
```
Comment (herkolategan) [inline pkg/cmd/roachtest/tests/network.go]: Should this not be just `fmt.Sprintf("{pgurl:%d}", server)`, and not `server-1`, since I think expanders start from 1?

Comment (DarrylWong) [reply pkg/cmd/roachtest/tests/network.go]: Ah good catch, I was confused why the test didn't fail in this case, but it looks like it was "saved" by:

```
		if i == expectedLeaseholder {
			continue
		}
```

where `expectedLeaseholder = 1`

File: pkg/cmd/roachtest/cluster.go [hunk 2]
```diff
@@ -2721,9 +2721,6 @@ func (c *clusterImpl) InternalPGUrl(
 	return c.pgURLErr(ctx, l, nodes, opts)
 }
 
-// Silence unused warning.
-var _ = (&clusterImpl{}).InternalPGUrl
```
Comment (srosenberg) [inline pkg/cmd/roachtest/cluster.go:2725]: Good riddance.

File: pkg/cmd/roachtest/tests/network.go [hunk 3]
```diff
@@ -206,7 +202,7 @@ SELECT $1::INT = ALL (
 				}
 
 				// Construct a connection URL to server i.
-				url := serverUrls[server-1]
+				url := fmt.Sprintf("{pgurl:%d}", server)
```
Comment (srosenberg) [inline pkg/cmd/roachtest/tests/network.go:205]: Nice.

**Review by srosenberg — APPROVED** [review]

**Review by herkolategan — APPROVED** [review]

**Comment by DarrylWong** [comment]
TFTRs

bors r=herkolategan, srosenberg
