### PR TITLE
dev: various fixes and improvements

### LINKED ISSUE #67385: dev: symlinking logic broken
`dev build cockroach-short` creates a broken symlink:

    lrwxr-xr-x   1 ricky  staff    92B Jul  8 14:53 cockroach-short -> /private/var/tmp/_bazel_ricky/be70b24e7357091e16c49d70921b7985/execroot/cockroach/bazel-out/

Epic CRDB-8036

### PR DESCRIPTION
**Pull request by rickystewart**
1. Add a new script `./dev` which builds `dev` and runs it.
2. Over time the symlinking logic bitrotted. Replace the old logic for
   determining the output path of an executable (which involved running
   `bazel aquery` and parsing the output) with something dumber that
   works better (we just munge the target name slightly to find the
   executable).
3. Use `--color=no` over `--color=yes` in a few places where color
   doesn't make sense, like where we're parsing command output.
4. Have `dev generate bazel` just call right into the same script that
   `make bazel-generate` uses instead of duplicating that code.

Closes #67385.

Release note: None

### CODE REVIEW

**Review by rail — CHANGES_REQUESTED** [review]
In overall it looks good. Just need to fix some linter errors.

> Reviewed 10 of 10 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/67436#-:-MeQag6w0jk2jMdd-0Bn:btlxoks)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rickystewart)

**Comment by rickystewart** [comment]
> In overall it looks good. Just need to fix some linter errors.
> 
> > Reviewed 10 of 10 files at r1.
> > _[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/67436#-:-MeQag6w0jk2jMdd-0Bn:btlxoks)_ status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rickystewart)

done

**Comment by rickystewart** [comment]
Having `dev` live in `bin` didn't work (`builder.sh` mounts it as a volume and that ruins some stuff in CI). I just put it at the root level for now.

**Review by rail — APPROVED** [review]
:lgtm:

> Reviewed 4 of 6 files at r3, 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/67436#-:-MeSi7_i1RKF0ur-eKRG:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @rail)

**Comment by rickystewart** [comment]
bors r=rail

File: pkg/cmd/dev/build.go [hunk 1]
```diff
@@ -136,53 +131,12 @@ func (d *dev) symlinkBinaries(ctx context.Context, targets []string) error {
...
-				}
-			}
-		}
-	}
-
-	return "", errors.Newf("could not find path to binary %q", target)
+	bazelBin := strings.TrimSpace(string(out))
+	target = strings.TrimPrefix(target, "//")
+	_, filename := filepath.Split(target)
+	return filepath.Join(bazelBin, target, filename+"_", filename), nil
```
Comment (irfansharif) [inline pkg/cmd/dev/build.go:141]: Drive by comment because I too was wondering if there was something better than this aquery mess, cquery!

```
bazel cquery //pkg/cmd/cockroach-short --output=starlark --starlark:expr="providers(target).get('FilesToRunProvider').executable.path"
```
