### PR TITLE
changefeedccl: add structured logging for changefeed create and failed

### LINKED ISSUE #77283: cdc: add telemetry logging for create changefeed
Since the new logging framework is only for serverless. We should do some more detailed logging of create changefeed for majority of users going into 22.1 launch. This will help us better understand what are customers are doing and where they are struggling. 

**Create changefeed event:**
The biggest thing we should log is the sink_type (gs, s3, http, webhook, kafka, gc pubsub). Additionally, logging the number of non-default configurations would be a great thing to log, but its a nice to have not a must have.

**Changefeed fail event**
There are three things we should log
- changefeed failed before changefeed create succeeded
- changefeed failed due to closed connection (core)
- All other failures

Jira issue: CRDB-13517

### PR DESCRIPTION
**Pull request by samiskin**
Resolves #77283

Previously we didn't have any logging related to the new Telemetry
channel (see
https://cockroachlabs.atlassian.net/wiki/spaces/MC/pages/2283798543/Telemetry+Logging).
This patch adds events around changefeed creation and failure, informing
us of some creation options and a general reason for a failure.

Release justification: low risk logging related changes

Release note (ops change): Changefeed creations and failures event logs
are now emitted to the telemetry channel

### CODE REVIEW

File: pkg/ccl/changefeedccl/changefeed_stmt.go [hunk 1]
```diff
@@ -1123,3 +1156,51 @@ func AllTargets(cd jobspb.ChangefeedDetails) (targets []jobspb.ChangefeedTargetS
...
+		JobType:     jobspb.TypeChangefeed.String(),
+		Description: jr.Description,
+		Status:      string(jobs.StatusPending),
+	}
+
+	changefeedDetails := jr.Details.(jobspb.ChangefeedDetails)
+	createChangefeedEvent := &eventpb.CreateChangefeedQuery{
+		CommonJobEventDetails: jobEventDetails,
+		NumTables:             int32(len(AllTargets(changefeedDetails))),
+		SinkType:              "core",
```
Comment (miretskiy) [inline pkg/ccl/changefeedccl/changefeed_stmt.go:1172]: Perhaps empty string for core? I'm okay either way... it's just we're using "" elsewhere.

File: pkg/util/log/eventpb/telemetry.proto [hunk 2]
```diff
@@ -71,3 +71,31 @@ message CapturedIndexUsageStats {
   bool is_unique = 10 [(gogoproto.jsontag) = ",omitempty"];
   bool is_inverted = 11 [(gogoproto.jsontag) = ",omitempty"];
 }
+
+// CreateChangefeedQuery
```
Comment (miretskiy) [inline pkg/util/log/eventpb/telemetry.proto:75]: Better comment needed if you going to have a comment.
Also, I'm not too keen on having "query" in its name.  Maybe simply `CreateChangefeed`?

File: pkg/util/log/eventpb/telemetry.proto [hunk 3]
```diff
@@ -71,3 +71,31 @@ message CapturedIndexUsageStats {
...
+message CreateChangefeedQuery {
+  CommonEventDetails common = 1 [(gogoproto.nullable) = false, (gogoproto.jsontag) = "", (gogoproto.embed) = true];
+  CommonJobEventDetails job = 2 [(gogoproto.nullable) = false, (gogoproto.jsontag) = "", (gogoproto.embed) = true];
```
Comment (miretskiy) [inline pkg/util/log/eventpb/telemetry.proto:78]: Not sure we should embed job details.  We do have core style changefeeds -- and those don't have job record(s).  So, it's a bit strange to see it here.  Secondly, does the job detail proto give us interesting information?  I.e. is knowing job id interesting?  Personally, I don't think so.  Furthermore, we are using "Description" of the job event details to put in, basically a redacted changefeed statement.  Why don't we use `CommonSQLEventDetails` which already has  statement field (which gets redacted)?

File: pkg/util/log/eventpb/telemetry.proto [hunk 4]
```diff
@@ -71,3 +71,31 @@ message CapturedIndexUsageStats {
...
+
+  // The number of tables listed in the query that the changefeed is to run on.
+  int32 num_tables = 3 [(gogoproto.jsontag) = ",omitempty"];
+
+  // The type of sink being emitted to (ex: kafka, nodelocal, webhook-https).
+  string sink_type = 4 [(gogoproto.jsontag) = ",omitempty", (gogoproto.moretags) = "redact:\"nonsensitive\""];
+
+  // The behavior of emitted resolved spans.
```
Comment (miretskiy) [inline pkg/util/log/eventpb/telemetry.proto:86]: is this the value of resolved option (like "resolved=10s")?  Is it useful? Or do we care more about the fact that resolved option was specified?
Perhaps we can include a boolean? And that's sufficient?

Also, should we perhaps include booleans for things like initial_scan? I know we have plenty of various options now for this (including the recently added initial_scan_only)... But maybe we can have initial_scan as a string which can take one of the values:
   off, only, cursor (i.e. no_initial_scan was specified, so cursor was either specified or we used statement time).

File: pkg/util/log/eventpb/telemetry.proto [hunk 5]
```diff
@@ -71,3 +71,31 @@ message CapturedIndexUsageStats {
...
+  string resolved = 5 [(gogoproto.jsontag) = ",omitempty", (gogoproto.moretags) =  "redact:\"nonsensitive\""];
+
+  // The data format being emitted (ex: JSON, Avro).
+  string format = 6 [(gogoproto.jsontag) = ",omitempty", (gogoproto.moretags) =  "redact:\"nonsensitive\""];
+}
+
+// ChangefeedFailed
+message ChangefeedFailed {
```
Comment (miretskiy) [inline pkg/util/log/eventpb/telemetry.proto:94]: i'm questioning why we would want to have the separate message for falures.
Why not have failure_reason above in the main changefeed telemetry message?  Even when changefeed creation fails, it is possible that the other fields (e..g format, sink type, etc)  could be initialized.  So, for example, we could see particular sink types seem to fail more often.

File: pkg/ccl/changefeedccl/changefeed_stmt.go [hunk 6]
```diff
@@ -71,6 +72,34 @@ func init() {
 	)
 }
 
+// Wraps changefeedPlanHook to log startup errors to the Telemetry channel
+func changefeedPlanHookWrapped(
```
Comment (miretskiy) [inline pkg/ccl/changefeedccl/changefeed_stmt.go:76]: going to delay reviewing this part until proto message comments addressed.

**Review by miretskiy — APPROVED** [review]

File: pkg/ccl/changefeedccl/helpers_test.go [hunk 7]
```diff
@@ -682,3 +685,71 @@ func forceTableGC(
...
 	}
 }
+
+// All structured logs should contain this property which stores the snake_cased
+// version of the name of the message struct
+type BaseEventStruct struct {
+	EventType string
+}
+
+var cmLogRe = regexp.MustCompile(`event_log\.go`)
```
[the remark this answers is not in the document]
Comment (samiskin) [reply pkg/ccl/changefeedccl/helpers_test.go:695]: Compiled, this was copied from a bulk test looking at these files, I'll just expand the variable name since its unclear.

**Comment by samiskin** [comment]
I pushed a new incomplete commit just to have the protobuf changes and general error wrapping setup shown for review.  Still adding the filling in of the description and sink type to failure messages.

**Comment by samiskin** [comment]
Actually I think I'll leave it like this in this PR for now just to ensure this gets in, where we don't have any `sink_type` or `description` information for `Failure` events that occur during startup, but we do at least have it for events after the job's been created.

File: pkg/util/log/eventpb/telemetry.proto [hunk 8]
```diff
@@ -71,3 +71,32 @@ message CapturedIndexUsageStats {
...
+// successfully starts running.  Failed CREATE statements will show up as
+// ChangefeedFailed events.
+message CreateChangefeed {
+  CommonChangefeedEventDetails common = 1 [(gogoproto.nullable) = false, (gogoproto.jsontag) = "", (gogoproto.embed) = true];
+
+  // The number of tables listed in the query that the changefeed is to run on.
+  int32 num_tables = 2 [(gogoproto.jsontag) = ",omitempty"];
+
+  // The behavior of emitted resolved spans (ex: yes, no, 10s)
+  string resolved = 3 [(gogoproto.jsontag) = ",omitempty", (gogoproto.moretags) =  "redact:\"nonsensitive\""];
```
Comment (miretskiy) [inline pkg/util/log/eventpb/telemetry.proto:85]: I kinda think that just indication if resolved option was used or not is probably enough.
But okay..

File: pkg/util/log/eventpb/telemetry.proto (hunk 5 above)
Comment (miretskiy) [reply pkg/util/log/eventpb/telemetry.proto:96]: I still think my question stands: why is changefeed creation should be any different from changfeed error event?  Wouldn't we want to know for example, how many webhook sinks with more than 5 tables fail?
When changefeed fails after the job is created, we have all of the information that we include in createChangefeed event...

Also, I kinda think that we should not be adding many changefeed event types. For example, wouldn't we want to also emit events if somebody alters changefeed?
We could probably use CreateChangefeed (though this should be renamed) to ChangefeedEvent maybe)?

Comment (samiskin) [reply pkg/util/log/eventpb/telemetry.proto:96]: What would be the benefit of sharing a `ChangefeedEvent` and I would assume adding another string property to distinguish the actual changefeed-specific event type, compared to having multiple events but putting more information in `CommonChangefeedEventDetails`?  

There's an idea for a Backfill Event with information like backfill_type, backfill_length, and backfill_size.  If we had multiple events like that with very specific information, I feel like a single `ChangefeedEvent` struct would get noisy.

Having just one struct would make parsing easier in the test, but I think it's worth that sacrifice for the clarity.

Comment (miretskiy) [reply pkg/util/log/eventpb/telemetry.proto:84]: > What would be the benefit of sharing a `ChangefeedEvent` and I would assume adding another string property to distinguish the actual changefeed-specific event type, compared to having multiple events but putting more information in `CommonChangefeedEventDetails`?
> 
> There's an idea for a Backfill Event with information like backfill_type, backfill_length, and backfill_size. If we had multiple events like that with very specific information, I feel like a single `ChangefeedEvent` struct would get noisy.
> 
> Having just one struct would make parsing easier in the test, but I think it's worth that sacrifice for the clarity.

Argh... I didn't realize this pr had LG.  That's unfortunate.  I have not for example, gave much thought to tagged errors, etc.  I think I made a mistake LG-ing instead of some other pr.

Thank you for moving to changefeed common details.  This addresses my biggest criticism.
I'm still not clear about the split into multiple message types -- there is "no prior" art for this (afaik other systems don't differentiate), nor do I know of any guidance for the telemetry usage.
