### PR TITLE
importccl: fix target columns order

### LINKED ISSUE #45422: IMPORT INTO does not seem to respect named column order
**Describe the problem**

```sql
CREATE TABLE Foo (
    id STRING NOT NULL,
    num INT NOT NULL
);
```

and with a csv file `reversed_columns.csv` that contains the following:

```csv
17,hello
18,goodbye
```

Start a web server in the same directory as the csv file, then try to import the data but with the order of the columns reversed as compared to the DDL:

```sql
IMPORT INTO Foo (num, id) CSV DATA ('http://localhost:9001/reversed_columns.csv');
```

This results in an error that makes it clear it's trying to import the data into columns in the same order as they exist in the database rather than as named in the `IMPORT` command:

```
pq: "http://localhost:9001/test.csv": row 1: parse "num" as INT8: could not parse "hello" as type int: strconv.ParseInt: parsing "hello": invalid syntax
```

**Environment:**
 - CockroachDB version: 19.2.4
 - Server OS: Windows 10 1909
 - Client app: `cockroach sql`

### PR DESCRIPTION
**Pull request by C0rWin**
Fixes #45422.

Currently during the import the order of the columns during data
transformation based on the table description rather than order of
the columns as appeared in the import expression.

This commit takes care that during the import from the external data
sourced it will also consider the order of the mentioned columns
such that it will properly apply conversion for accurate data type. Fixes

Signed-off-by: Artem Barger <bartem@il.ibm.com>

Release note (bug fix): Fix cases where target column specifications in IMPORT INTO were ignored

### CODE REVIEW

**Comment by C0rWin** [comment]
Instead of accidentally closed PR #45713

File: pkg/ccl/importccl/import_stmt_test.go [hunk 1]
```diff
@@ -2127,6 +2127,26 @@ func TestImportIntoCSV(t *testing.T) {
 		)
 	})
 
+	// Tests the case where we create table columns in specific order while trying
+	// to import data from csv where columns order is different and import expression
+	// defines in what order columns should be imported to align with table definition
+	t.Run("target-cols-reordered", func(t *testing.T) {
+		sqlDB.Exec(t, "CREATE TABLE t (a INT PRIMARY KEY, b int, c STRING NOT NULL, d DECIMAL NOT NULL)")
```
Comment (dt) [inline pkg/ccl/importccl/import_stmt_test.go]:
```suggestion
		sqlDB.Exec(t, "CREATE TABLE t (a INT PRIMARY KEY, b INT, c STRING NOT NULL, d DECIMAL NOT NULL)")
```

File: pkg/ccl/importccl/import_stmt_test.go [hunk 2]
```diff
@@ -2127,6 +2127,26 @@ func TestImportIntoCSV(t *testing.T) {
...
+
+		srv := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
+			if r.Method == "GET" {
+				_, _ = w.Write([]byte(data))
+			}
+		}))
+		defer srv.Close()
+
+		sqlDB.Exec(t, fmt.Sprintf(`IMPORT INTO t (d, c, a) CSV DATA ("%s")`, srv.URL))
+		sqlDB.CheckQueryResults(t, `SELECT COUNT(*) FROM t`, [][]string{{"2"}})
```
Comment (dt) [inline pkg/ccl/importccl/import_stmt_test.go]:
```suggestion
		sqlDB.CheckQueryResults(t, `SELECT * FROM t ORDER BY a`, 
				[][]string{{"1", "NULL", "c is a string", "3.14"}, {"2", "NULL", "another string", "2.73"}},
		)
```

**Review by dt — COMMENTED** [review]
Thanks for re-opening this!

On the earlier one, I saw a test failure on the CI run in one of the other IMPORT target column tests, in `target-cols-with-default-pk`. I looked at that test and I think something funky is up, since it is importing a 6 field CSV with 1 target column and somehow succeeding, but then somehow this patch changed which field it imported. I haven't dug deeper on that yet.

A couple commit message nits: 
Commit message (and PR title) style convention is just `pkg: ` (no brackets), so ideally something like: `importccl: fix target columns order`
Additionally, this probably deserves a release-note line for inclusion in published release notes, e.g.
`Release note (bug fix): respect the order that target columns are specified in IMPORT INTO.`

**Comment by dt** [comment]
@C0rWin I think there's another bug lurking around here we might need to fix at the same time, based on the failures coming from the `target-cols-with-default-pk` test. Looking at that test, it looks like the test is wrong (i.e. it is confirming incorrect behavior), since we're importing a 6-field CSV with one or two or three target columns in the individual cases, but that _should_ fail: If you have 2 target columns, your CSV should have two columns and anything else is a bug.

Right now though it looks like currently aren't respecting the target-columns when checking if the input file row has the right number of fields, but rather just using all the visible columns similar to the case you've already caught, but this time on this line: https://github.com/cockroachdb/cockroach/blob/master/pkg/ccl/importccl/read_import_csv.go#L137

We might need to put an `expectedColumns` field in the csvRowProducer and set it, in init, to `len(targetColumns)` if non-nil, falling back to `len(tableDesc.VisibleColumns())` otherwise?

After that, we'll need to fix that test, update `data` above each subtest to have the correct width and verify it works.

**Comment by C0rWin** [comment]
>  We might need to put an expectedColumns field in the csvRowProducer and set it, in init, to len(targetColumns) if non-nil, falling back to len(tableDesc.VisibleColumns()) otherwise?

pushed an update to address this.

**Comment by C0rWin** [comment]
``` --- FAIL: TestZip (79.50s)
    zip_test.go:235: 
        	Error Trace:	zip_test.go:235
        	Error:      	Not equal: ```

seems quite unrelated to the PR failure.

**Comment by dt** [comment]
Thanks for digging in and fixing these @C0rWin !

bors r=dt
