### PR TITLE
storage: don't panic on Iterator.Close

### LINKED ISSUE #84396: storage: pebbleIterator panics too eagerly on Close()
After hooking the new pebbleIterator into the restore processor (https://github.com/cockroachdb/cockroach/pull/83984), a few restore roachtests on master have been failing (https://github.com/cockroachdb/cockroach/issues/84240, https://github.com/cockroachdb/cockroach/issues/84237), because the pebbleIterator panics when it attempts to close, for example: 
```
panic: EOF                                                                      
    9                                                                                 
   10 goroutine 45749 [running]:                                                      
   11 panic({0x483a900, 0xc0000a4120})                                                
   12         GOROOT/src/runtime/panic.go:1147 +0x3a8 fp=0xc0061cb528 sp=0xc0061cb468 pc=0x48a828
   13 github.com/cockroachdb/cockroach/pkg/storage.(*pebbleIterator).destroy(0xc0039f0000)
   14         github.com/cockroachdb/cockroach/pkg/storage/pebble_iterator.go:897 +0x1e5 fp=0xc0061cb668 sp=0xc0061cb528 pc=0x17a61a5
   15 github.com/cockroachdb/cockroach/pkg/storage.(*pebbleIterator).Close(0xc0039f0000)
```
(see full example panic stack trace in[ comment](https://github.com/cockroachdb/cockroach/issues/84240#issuecomment-1182279432)).

In the failed tests and in repros, the panic reasons have been `EOF`, `Context cancelled`, and `nil`, which at a high level, makes me wonder if all this panicking is necessary. To get a better understanding of when the iterator panics, I ran the `restore/nodeShutdown/coordinator` roachtest on my gce-worker using master + a [commit](https://github.com/cockroachdb/cockroach/commit/bf79431f9169f8765c7aa659e20e02fdd628f541) that adds more logging related to the SSTs in the iterator and issues prints instead of panics in `pebbleIterator.destroy()`. 

I can explain and reproduce the `context cancelled` panic. When the restore fails for some independent reason, context cancellations circulates throughout the goroutines, leading to pebbleIterator.Valid() returning `!ok`  and a `context cancelled` error. This then leads to `defer.Close()`, surfacing the `context cancelled` error during `destroy()`, leading to a panic. To repro this, stress the `restore/nodeShutdown/coordinator` roachtest above, potentially with my augmented commit.

I'm not sure what causes the EOF or nil based panics. 
@erikgrinaker 

Jira issue: CRDB-17633

Epic CRDB-2624

### PR DESCRIPTION
**Pull request by jbowens**
Don't panic if Iterator.Close returns a non-nil error. Iteration errors should
already be surfaced through (*pebble.Iterator).Error and
(storage.EngineIterator).Valid. Panicking may crash the node for retriable,
ephemeral I/O errors, especially when reading from sstables over the network.

In a follow up, we should make sure we're still appropriately panicking for
non-retriable errors.

Fix #84396.

Release note (bug fix): fix bug where an ephemeral I/O error could crash a
node.

### CODE REVIEW

File: pkg/storage/pebble_iterator.go [hunk 1]
```diff
@@ -892,10 +892,11 @@ func (p *pebbleIterator) destroy() {
 		panic("iterator still in use")
 	}
 	if p.iter != nil {
-		err := p.iter.Close()
-		if err != nil {
-			panic(err)
-		}
+		_ = p.iter.Close()
+		// TODO(jackson): The error returned by iter.Close() may be an ephemeral
```
Comment (erikgrinaker) [inline pkg/storage/pebble_iterator.go:896]: This should call out that if `iter.Valid()` returns an error, then that same error will also be returned by `Close()`. In most cases, we do not care about that error during `Close`, since the caller may already have handled it appropriately (e.g. a context cancellation) but still wants to close the iterator via e.g. `defer`.

**Review by erikgrinaker — APPROVED** [review]
Thanks!

**Review by nicktrav — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/84449#-:-N6z6IiG9X-YNB0-5gp9:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @jbowens)

**Comment by jbowens** [comment]
TFTRs!

bors r=nicktrav,erikgrinaker
