### PR TITLE
cli,rpc,server: verify cluster names

### LINKED ISSUE #16784: core: user-provided cluster name.
A user-provided cluster name would be very helpful for in a lot of cases:
* could be provided by every node on startup and be required to match when joining a cluster (would prevent unitialized nodes from joining the wrong cluster)
* could be used in certificates to easily identify the object of the certificate. The certificate field could be checked against the actual cluster name to disallow certs for other clusters that were signed with the same CA (common for people with established pki infrastructure: they'll have a single org CA)
* included as a label in metrics. This makes multi-cluster monitoring much simpler, skipping the need for cluster names in the monitoring config. see #15888

All three cases above would require a strict verification of the cluster name. This would mean that **should** be provided at cluster initialization and never changed. An empty name could be supported (making supporting existing cluster much simpler). Changing the name would be possible for all the listed cases, just very very tedious (coordinate node flags, regenerate all certificates, manually relabel metrics to preserve history).

### PR DESCRIPTION
**Pull request by knz**
Fixes #16784.
Implements #39196.

This patch introduces a "cluster name" checked in addition to the
cluster ID (and especially when the cluster ID is not known yet) to
ensure that nodes don't join the wrong cluster by mistake.

This cluster name is not persisted and only configurable via the
command line. Also it cannot be modified as long as one node in the
cluster is still running (as this node will be checking connections
from any new peer). It can only be modified by stopping all nodes,
changing the command-line parameter value, and restarting the nodes.

It is also accessible from SQL via `crdb_internal.cluster_name()`
(each node will report its local view on the value, which may differ
across nodes) and `crdb_internal.gossip_nodes` (where different
values on different nodes can be distinguished).

Release note (cli change): CockroachDB will now check that the value
passed via `--cluster-name`, if provided, matches when a node connects
to a cluster. This feature is meant for use in combination with the
cluster ID, which is still checked in any case, to protect newly
created nodes (that don't have a cluster ID yet) from joining the
wrong cluster.

### CODE REVIEW

**Comment by knz** [comment]
@bdarnell I notice that the heartbeat services' `Ping()` method verifies the cluster ID, version and maxOffset, and separately the requestor (`rpc.Context.runHeartbeat()` *also* checks the version.

Was there a specific reason to have the service check the cluster ID and maxOffset and not the requestor?

Why is the version checked on both sides?

**Comment by knz** [comment]
@mberhault I have not yet implemented the TLS field validation as I have still to figure out the flow of data that serves to verify node-node certs. Once I understand that, I plan to extend the PR with an additional commit to do the TLS validation too.

**Comment by mberhault** [comment]
I think it's fair to keep the use of the cluster name in cert validation for another PR. There's still a question of where it belongs (which field) and even whether said field is customizable.

**Comment by knz** [comment]
ok thanks

File: pkg/cli/cliflags/flags.go [hunk 1]
```diff
@@ -293,6 +293,14 @@ csv, table, records, sql, raw, html. If left unspecified, defaults to
 tsv for non-interactive sessions and table for interactive sessions.`,
 	}
 
+	ClusterName = FlagInfo{
+		Name: "cluster-name",
+		Description: `
+Sets a name to verify the identity of a remote node or cluster, when
+either the node or cluster, or both, have not yet been initialized
+yet.`,
```
Comment (mberhault) [inline pkg/cli/cliflags/flags.go]: Could you mention that all nodes must have the same cluster name if set.

**Comment by knz** [comment]
added the missing tests

File: pkg/rpc/context_test.go [hunk 2]
```diff
@@ -1243,6 +1243,68 @@ func TestClusterIDMismatch(t *testing.T) {
...
+				if err != nil {
+					t.Error(err)
+				}
+				wg.Done()
+			}()
+		}
+		wg.Wait()
+	})
+
+	t.Run("different names", func(t *testing.T) {
```
Comment (mberhault) [inline pkg/rpc/context_test.go]: It should work as expected from looking at the code, but could you add a test for one side with a cluster name, the other without?

File: pkg/rpc/heartbeat.go [hunk 3]
```diff
@@ -56,6 +58,16 @@ type HeartbeatService struct {
 	testingAllowNamedRPCToAnonymousServer bool
 }
 
+func checkClusterName(clusterName string, peerName string) error {
+	if clusterName != peerName {
+		err := errors.Errorf(
+			"local cluster name %q does not match peer cluster name %q", clusterName, peerName)
```
Comment (mberhault) [inline pkg/rpc/heartbeat.go]: I'm wondering if we want clearer error messages in the case of `peer cluster name is %q, but local cluster name is not set` (and vice versa). The quoted name should be sufficient, so up to you.

**Review by mberhault — APPROVED** [review]
Nice! This will definitely need some new docs. Though the stricter requirements (and difficulty of changing the name) will come with more uses. As is, it only impacts new nodes which is quite nice.

File: pkg/cli/cliflags/flags.go (hunk 1 above)
Comment (knz) [reply pkg/cli/cliflags/flags.go]: Done.

File: pkg/cli/flags.go [hunk 4]
```diff
@@ -182,6 +184,37 @@ func (a addrSetter) Set(v string) error {
...
+		return errors.Newf(`cluster name can contain at most %d characters`, maxClusterNameLength)
+	}
+	*a.clusterName = v
+	return nil
+}
+
+// clusterNameRe matches valid cluster names.
+// For example, "a", "a1.23" and "a-b" are OK,
+// but "0123", "a-" and "123a" are not OK.
+var clusterNameRe = regexp.MustCompile(`^[_a-zA-Z](?:[-._a-zA-Z0-9]*[_a-zA-Z0-9]|)$`)
```
[the remark this answers is not in the document]
Comment (knz) [reply pkg/cli/flags.go]: Done.

File: pkg/rpc/context_test.go (hunk 2 above)
Comment (knz) [reply pkg/rpc/context_test.go]: Done.

File: pkg/rpc/heartbeat.go (hunk 3 above)
Comment (knz) [reply pkg/rpc/heartbeat.go]: Done.

File: pkg/cli/cliflags/flags.go [hunk 5]
```diff
@@ -293,6 +293,17 @@ csv, table, records, sql, raw, html. If left unspecified, defaults to
 tsv for non-interactive sessions and table for interactive sessions.`,
 	}
 
+	ClusterName = FlagInfo{
+		Name: "cluster-name",
+		Description: `
+Sets a name to verify the identity of a remote node or cluster. The
+value must match between this node and the remote node(s) specified
+via --join.
+This can be used as an additional verification when either either the
```
Comment (mberhault) [inline pkg/cli/cliflags/flags.go]: "either either"

**Comment by knz** [comment]
>  As is, it only impacts new nodes which is quite nice.

No that's not accurate. I don't think the code as-is can introduce a cluster name into a cluster that has been started without one. Should I update the code to make it possible?

**Review by mberhault — COMMENTED** [review]
> > As is, it only impacts new nodes which is quite nice.
> 
> No that's not accurate. I don't think the code as-is can introduce a cluster name into a cluster that has been started without one. Should I update the code to make it possible?

Sorry, that's what I meant.
With the current use, mismatches in `--cluster-name` only matter when attempting to add a node. All mismatches (empty vs not, different strings) fail the node join. As long as no nodes are being added, mismatches do not cause an issue so rolling restarts with different settings are ok. This situation will either change or need special logic once certificate checking is in place.

**Comment by knz** [comment]
I have changed the logic to support rolling upgrades via a temporary flag `--disable-peer-name-verification`. I also have updated the RFC to explain why it exists and how it works.

File: pkg/cli/cliflags/flags.go (hunk 5 above)
Comment (knz) [reply pkg/cli/cliflags/flags.go]: Fixed

File: pkg/rpc/heartbeat.go [hunk 6]
```diff
@@ -56,6 +60,31 @@ type HeartbeatService struct {
 	testingAllowNamedRPCToAnonymousServer bool
 }
 
+func checkClusterName(disablePeerNameVerification bool, clusterName string, peerName string) error {
+	if disablePeerNameVerification && (clusterName == "" || peerName == "") {
```
Comment (mberhault) [inline pkg/rpc/heartbeat.go]: Don't you want to OR the local and remote `disablePeerNameVerification`?
I'm thinking of the following situation:
- node A has flags with `--cluster-name=foo` and `--disable-peer-name-verification`
- node B has not had the new flags applied yet

node A is restarted as part of the name rollout.
node B restarts on its own, but still has not had the new flags applied.

At this point, node B will ping node A, but will fail due to `disablePeerNameVerification = false`. This will go into the `clusterName != peerName` check and fail.

Comment (knz) [reply pkg/rpc/heartbeat.go]: The OR is there, performed by the caller.
It's in the RFC and *also* checked in the unit test in the same package.

Comment (mberhault) [reply pkg/rpc/heartbeat.go]: oops. My bad. I had it in my head that `checkClusterName`'s signature was `(localDisable, remoteDisable, localName, remoteName)`. Sorry about that.

Comment (knz) [reply pkg/rpc/heartbeat.go]: np. so good to go?

Comment (mberhault) [reply pkg/rpc/heartbeat.go]: I'm good, but I'd like @bdarnell to take a look.

**Review by bdarnell — COMMENTED** [review]
> Reviewed 13 of 21 files at r1, 8 of 8 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/39270)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @bdarnell, @knz, and @mberhault)

___
*[pkg/base/config.go, line 171 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/39270#-LlX_-Uv9yZUn7pQuDHJ:-LlX_-Uv9yZUn7pQuDHK:b-cedp94) ([raw file](https://github.com/cockroachdb/cockroach/blob/9c15373079e6081d2a4483b34a836df9d420615c/pkg/base/config.go#L171)):*
> ```Go
> 	// both sides match. This is meant for use while rolling an
> 	// existing cluster into using a new cluster name.
> 	DisablePeerNameVerification bool
> ```

s/Peer/Cluster/

So this flag permits combining empty and non-empty, but non-empty values must match? This does make it possible to change from one name to another, but it's a very awkward process:

1. Restart all nodes with disable cluster name verification flag (and the old name)
2. Restart all nodes with disable flag and no name
3. Restart all nodes with disable flag and new name
4. Restart all nodes with new name without disable flag

I think this flag should disable the checking completely so it can be used to go directly from the old name to the new one. (which still leaves this a 3-step process, but I think it's more understandable without the "no name" step in the middle)

Maybe we should just permit a mix of empty and non-empty cluster names at all times, so that cluster names only prevent mixups when both clusters use them. I'm not sure it's worth having extra configuration to disable checks here. 
___
*[pkg/cli/flags.go, line 219 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/39270#-LlXaSnd5X5ZAJ-Ll4Q6:-LlXaSnd5X5ZAJ-Ll4Q7:bz7tbmo) ([raw file](https://github.com/cockroachdb/cockroach/blob/9c15373079e6081d2a4483b34a836df9d420615c/pkg/cli/flags.go#L219)):*
> ```Go
> // For example, "a", "a1.23" and "a-b" are OK,
> // but "0123", "a-" and "123a" are not OK.
> var clusterNameRe = regexp.MustCompile(`^[a-zA-Z](?:[-.a-zA-Z0-9]*[a-zA-Z0-9]|)$`)
> ```

Ooh, if these names are DNS-legal then maybe we can do some nice things with mDNS.  I'd remove `.` from the middle block too; we only need one separator character (and then we can translate `-` to `.` or `_` when required by other formats, without ambiguity)

**Review by knz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/39270)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @bdarnell, @knz, and @mberhault)

___
*[pkg/base/config.go, line 171 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/39270#-LlX_-Uv9yZUn7pQuDHJ:-LlXczvL1F-oInLqRGTP:bcpbra6) ([raw file](https://github.com/cockroachdb/cockroach/blob/9c15373079e6081d2a4483b34a836df9d420615c/pkg/base/config.go#L171)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

s/Peer/Cluster/

So this flag permits combining empty and non-empty, but non-empty values must match? This does make it possible to change from one name to another, but it's a very awkward process:

1. Restart all nodes with disable cluster name verification flag (and the old name)
2. Restart all nodes with disable flag and no name
3. Restart all nodes with disable flag and new name
4. Restart all nodes with new name without disable flag

I think this flag should disable the checking completely so it can be used to go directly from the old name to the new one. (which still leaves this a 3-step process, but I think it's more understandable without the "no name" step in the middle)

Maybe we should just permit a mix of empty and non-empty cluster names at all times, so that cluster names only prevent mixups when both clusters use them. I'm not sure it's worth having extra configuration to disable checks here. 
</blockquote></details>

The name change is document in the RFC and 1) there's one less step needed than you say here 2) this can be later automated, should we want this to become a common operation, by introducing a new cluster RPC (which is also explained in the RFC).

Additonnally, the reason why I chose to not allow empty and non-empty names by default is to: 
  - prevent someone from mistakenly adding a node without a name to a cluster that has a name (feature ask by marc)
  - prevent someone from mistakenly adding a node with a name to a cluster without a name (e.g. a pre-19.2 cluster). This was also a feature ask by marc.
  - to ensure that names are consistent across the cluster.

Really we need to prevent a realistic mistake: two or more 'active" nodes started with conflicting cluster names. If you have 2+ nodes with different cluster names, it becomes impossible to reliably activate the cluster name verification throughout the cluster.

**Review by bdarnell — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/39270)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @bdarnell, @knz, and @mberhault)

___
*[pkg/base/config.go, line 171 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/39270#-LlX_-Uv9yZUn7pQuDHJ:-LlXgwTlD2n-DDZg6wqs:bb8izmm) ([raw file](https://github.com/cockroachdb/cockroach/blob/9c15373079e6081d2a4483b34a836df9d420615c/pkg/base/config.go#L171)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

The name change is document in the RFC and 1) there's one less step needed than you say here 2) this can be later automated, should we want this to become a common operation, by introducing a new cluster RPC (which is also explained in the RFC).

Additonnally, the reason why I chose to not allow empty and non-empty names by default is to: 
  - prevent someone from mistakenly adding a node without a name to a cluster that has a name (feature ask by marc)
  - prevent someone from mistakenly adding a node with a name to a cluster without a name (e.g. a pre-19.2 cluster). This was also a feature ask by marc.
  - to ensure that names are consistent across the cluster.

Really we need to prevent a realistic mistake: two or more 'active" nodes started with conflicting cluster names. If you have 2+ nodes with different cluster names, it becomes impossible to reliably activate the cluster name verification throughout the cluster.


</blockquote></details>

In the RFC the disable flag completely disables the check (as I'm suggesting here), but in this implementation it only disables the check if either the old or the new name is empty.

**Review by knz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/39270)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @bdarnell and @mberhault)

___
*[pkg/base/config.go, line 171 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/39270#-LlX_-Uv9yZUn7pQuDHJ:-LlXjUTH5R6YA5P1MMSE:bf5tw8e) ([raw file](https://github.com/cockroachdb/cockroach/blob/9c15373079e6081d2a4483b34a836df9d420615c/pkg/base/config.go#L171)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

In the RFC the disable flag completely disables the check (as I'm suggesting here), but in this implementation it only disables the check if either the old or the new name is empty.
</blockquote></details>

let's discuss on the RFC then.
___
*[pkg/cli/flags.go, line 219 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/39270#-LlXaSnd5X5ZAJ-Ll4Q6:-LlXjR9w7Js5Fr2mgs0h:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/9c15373079e6081d2a4483b34a836df9d420615c/pkg/cli/flags.go#L219)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

Ooh, if these names are DNS-legal then maybe we can do some nice things with mDNS.  I'd remove `.` from the middle block too; we only need one separator character (and then we can translate `-` to `.` or `_` when required by other formats, without ambiguity)
</blockquote></details>

Done.

**Comment by bdarnell** [comment]
> @bdarnell I notice that the heartbeat services' Ping() method verifies the cluster ID, version and maxOffset, and separately the requestor (rpc.Context.runHeartbeat() also checks the version.
> 
> Was there a specific reason to have the service check the cluster ID and maxOffset and not the requestor?
> 
> Why is the version checked on both sides?

I don't remember why it's organized this way, and it's probably just how the code evolved instead of having a good reason.

**Comment by knz** [comment]
modified as discussed, rfal

**Review by bdarnell — APPROVED** [review]
> Reviewed 21 of 22 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/39270)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @bdarnell, @knz, and @mberhault)

___
*[pkg/rpc/heartbeat.go, line 66 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/39270#-LlYazV-8karUIBAf4W-:-LlYazV-8karUIBAf4W0:bqjhsc) ([raw file](https://github.com/cockroachdb/cockroach/blob/ba5e55760db940504f9f0862465e9c4922c1068c/pkg/rpc/heartbeat.go#L66)):*
> ```Go
> 	disableClusterNameVerification bool, clusterName string, peerName string,
> ) error {
> 	if disableClusterNameVerification {
> ```

Nit: Since this argument now just makes the method a no-op, I'd remove the argument and change the call site to `if !disableClusterNameVerification { checkClusterName(...) }`
___
*[pkg/rpc/heartbeat.proto, line 69 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/39270#-LlYagU34V5tugcVAu0Z:-LlYagU34V5tugcVAu0_:b-e2vqd8) ([raw file](https://github.com/cockroachdb/cockroach/blob/ba5e55760db940504f9f0862465e9c4922c1068c/pkg/rpc/heartbeat.proto#L69)):*
> ```protobuf
>   optional string cluster_name = 4 [(gogoproto.nullable) = false];
>   // Skip cluster name check if either side's name is empty / not configured.
>   optional bool disable_cluster_name_verification = 5 [(gogoproto.nullable) = false];
> ```

I think I'd get rid of this - it's a little bit easier to think about things when each node makes its decisions based on its own flag instead of passing this over the network. It's a little less convenient for the "name change" scenario since you have to rollout the disable flag and then change the name in a separate pass, but I think that's OK.

**Review by knz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/39270)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @bdarnell and @mberhault)

___
*[pkg/rpc/heartbeat.go, line 66 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/39270#-LlYazV-8karUIBAf4W-:-LlYbr4d1mFEnCHzuKu8:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/ba5e55760db940504f9f0862465e9c4922c1068c/pkg/rpc/heartbeat.go#L66)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

Nit: Since this argument now just makes the method a no-op, I'd remove the argument and change the call site to `if !disableClusterNameVerification { checkClusterName(...) }`
</blockquote></details>

Done.
___
*[pkg/rpc/heartbeat.proto, line 69 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/39270#-LlYagU34V5tugcVAu0Z:-LlYbroK65bwAQAPGkxZ:b-npxx3a) ([raw file](https://github.com/cockroachdb/cockroach/blob/ba5e55760db940504f9f0862465e9c4922c1068c/pkg/rpc/heartbeat.proto#L69)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

I think I'd get rid of this - it's a little bit easier to think about things when each node makes its decisions based on its own flag instead of passing this over the network. It's a little less convenient for the "name change" scenario since you have to rollout the disable flag and then change the name in a separate pass, but I think that's OK. 
</blockquote></details>

I tried that and it does not work (reliably). That's because the originator of the first heartbeat is not always the node you're just joining or restarting, oftentimes another node connects into the new node before that. We want the new node with the --disable flag to be able to make that other-initiated heartbeat succeed.

**Comment by knz** [comment]
TFYRs

bors r+
