### PR TITLE
sql: add drain mode to LeaseManager

### LINKED ISSUE #9493: sql: schema change after server restart blocks once then looks like DB corruption after retry
Steps:
1. create fresh cluster `rm -rf cockroach-data; ./cockroach start --background`
2. load the example db: `./cockroach gen example-data startrek | ./cockroach sql`
3. confirm that the example db can be reloaded multiple times (can DROP then CREATE multiple times): repeat step 2 a few times.
4. stop the server with `killall cockroach` - wait for the server to finish shutting down
5. restart the server `./cockroach start --background`
6. attempt step 2 again; **observe: the server hangs after SET, upon encountering the first DROP**
7. interrupt the client with Ctrl+C
8. attempt step 2 again; **observe: the first DROP fails with an error, then the client hangs** (error: `pq: missing fk back reference to quotes.quotes_episode_idx from episodes.primary`)
9. interrupt the client again with Ctrl+C
10. attempt step 2 again; **observe: major confusion**

```
CREATE DATABASE
SET
pq: missing fk back reference to quotes.quotes_episode_idx from episodes.primary
pq: table "episodes" has been deleted
pq: relation "episodes" already exists
pq: table is being deleted
pq: relation "quotes" already exists
pq: table is being deleted
Error: pq: table is being deleted
Failed running "sql"
```

From that point forward the db cannot be used but also cannot be deleted.

### PR DESCRIPTION
**Pull request by asubiotto**
Fixes #9493 by deleting all unreferenced table descriptor leases on
clean shutdown. Leases whose refcount drops to 0 while in this drain
mode are also deleted.

---
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/12501)

### CODE REVIEW

**Comment by tamird** [comment]
Reviewed 3 of 4 files at r1.
Review status: 3 of 4 files reviewed at latest revision, 2 unresolved discussions.

---

*[pkg/server/server.go, line 755 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/12501#-KZS8_z-wdY0VDffXFjY:-KZS8_z-wdY0VDffXFjZ:b54ywxe) ([raw file](https://github.com/cockroachdb/cockroach/blob/7a58c3eec696e84a2bfb97b065fb0e3c914bafaa/pkg/server/server.go#L755)):*
> ```Go
> 	for _, mode := range modes {
> 		var err error
> 		switch {
> ```

drive by, but why isn't this
```
switch mode {
case serverpb.DrainMode_CLIENT:
  if err := s.pgServer.SetDraining(setTo); err != nil {
    return err
  }
  s.leaseMgr.SetDraining(setTo)
case serverpb.DrainMode_LEASES:
  s.nodeLivenessPauseHeartbeat(setTo)
  if err := s.node.SetDraining(setTo); err != nil {
    return err
  }
default:
  return errors.Errorf("unknown drain mode %s", mode) // <-- %s here is intentional, since protobuf enums implement String()
}
```

---

*[pkg/sql/lease.go, line 1171 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/12501#-KZSB3LcTCfJPH-uZ91P:-KZSB3LdCioaJlKN09Z1:b800qm) ([raw file](https://github.com/cockroachdb/cockroach/blob/7a58c3eec696e84a2bfb97b065fb0e3c914bafaa/pkg/sql/lease.go#L1171)):*
> ```Go
> 	for _, t := range m.tables {
> 		t.mu.Lock()
> 		toRelease := append([]*LeaseState(nil), t.active.data...)
> ```

why the copy?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/12501)*

**Comment by asubiotto** [comment]
Review status: 3 of 4 files reviewed at latest revision, 2 unresolved discussions.

---

*[pkg/server/server.go, line 755 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/12501#-KZS8_z-wdY0VDffXFjY:-KZSLG3rz93-rK6DIot5:bhoakb0) ([raw file](https://github.com/cockroachdb/cockroach/blob/7a58c3eec696e84a2bfb97b065fb0e3c914bafaa/pkg/server/server.go#L755)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

drive by, but why isn't this
```
switch mode {
case serverpb.DrainMode_CLIENT:
  if err := s.pgServer.SetDraining(setTo); err != nil {
    return err
  }
  s.leaseMgr.SetDraining(setTo)
case serverpb.DrainMode_LEASES:
  s.nodeLivenessPauseHeartbeat(setTo)
  if err := s.node.SetDraining(setTo); err != nil {
    return err
  }
default:
  return errors.Errorf("unknown drain mode %s", mode) // <-- %s here is intentional, since protobuf enums implement String()
}
```
</blockquote></details>

Good point. I'm not sure. It would lead to the same behavior and have better scoping with your suggestion.

---

*[pkg/sql/lease.go, line 1171 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/12501#-KZSB3LcTCfJPH-uZ91P:-KZSLwLbXUqRouQhnGnm:bpoa4av) ([raw file](https://github.com/cockroachdb/cockroach/blob/7a58c3eec696e84a2bfb97b065fb0e3c914bafaa/pkg/sql/lease.go#L1171)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

why the copy?
</blockquote></details>

`t.active.data` is changed by `releaseLeasesIfNotActive` (per the comment on `releaseLeasesIfNotActive`)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/12501)*

**Comment by asubiotto** [comment]
Review status: 3 of 4 files reviewed at latest revision, 2 unresolved discussions.

---

*[pkg/server/server.go, line 755 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/12501#-KZS8_z-wdY0VDffXFjY:-KZSMeyBsiNtgdSydA_R:b-hkyvhn) ([raw file](https://github.com/cockroachdb/cockroach/blob/7a58c3eec696e84a2bfb97b065fb0e3c914bafaa/pkg/server/server.go#L755)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

Good point. I'm not sure. It would lead to the same behavior and have better scoping with your suggestion.
</blockquote></details>

Sorry, I'm talking about the previous version of the code having the same behavior. Will change this to execute the `LeaseManager` draining logic even if `pgServer.SetDraining` errors out.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/12501)*

**Comment by tamird** [comment]
Reviewed 1 of 4 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[pkg/sql/lease.go, line 1171 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/12501#-KZSB3LcTCfJPH-uZ91P:-KZSOCQ5KRbgo7Br2--1:b5gwzue) ([raw file](https://github.com/cockroachdb/cockroach/blob/7a58c3eec696e84a2bfb97b065fb0e3c914bafaa/pkg/sql/lease.go#L1171)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

`t.active.data` is changed by `releaseLeasesIfNotActive` (per the comment on `releaseLeasesIfNotActive`)
</blockquote></details>

wow, that behaviour is quite bizarre, and with this patch, both callers of that function make a copy of `t.active.data` before calling it. Perhaps `releaseLeasesIfNotActive` should instead lose its first parameter and make whatever copies it needs internally.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/12501)*

File: pkg/sql/lease.go [hunk 1]
```diff
@@ -1149,7 +1148,30 @@ func (m *LeaseManager) Release(lease *LeaseState) error {
 	// could be bad if a lot of tables keep being created. I looked into cleaning
 	// up a bit, but it seems tricky to do with the current locking which is split
 	// between LeaseManager and tableState.
-	return t.release(lease, m.LeaseStore)
+	return t.release(lease, m)
+}
+
+func (m *LeaseManager) isDrainingLeases() bool {
```
Comment (vivekmenezes) [inline pkg/sql/lease.go]: s/isDrainingLeases/isDraining

File: pkg/sql/lease.go [hunk 2]
```diff
@@ -714,12 +714,10 @@ func (t *tableState) release(lease *LeaseState, store LeaseStore) error {
 	decRefcount := func(s *LeaseState) bool {
 		// Figure out if we'd like to remove the lease from the store asap (i.e. when
 		// the refcount drops to 0). If so, we'll need to mark the lease as released.
-		removeOnceDereferenced := false
-
-		if store.testingKnobs.RemoveOnceDereferenced {
+		removeOnceDereferenced := m.isDrainingLeases()
+		if m.LeaseStore.testingKnobs.RemoveOnceDereferenced {
 			removeOnceDereferenced = true
 		}
```
Comment (vivekmenezes) [inline pkg/sql/lease.go]: removeOnceDereferenced := m.isDraining() ||  m.LeaseStore.testingKnobs.RemoveOnceDereferenced

File: pkg/sql/lease.go [hunk 3]
```diff
@@ -1149,7 +1148,30 @@ func (m *LeaseManager) Release(lease *LeaseState) error {
...
+func (m *LeaseManager) SetDraining(drain bool) {
+	m.mu.Lock()
+	defer m.mu.Unlock()
+	m.draining = drain
+	if !drain {
+		return
+	}
+	for _, t := range m.tables {
+		t.mu.Lock()
+		toRelease := append([]*LeaseState(nil), t.active.data...)
```
Comment (vivekmenezes) [inline pkg/sql/lease.go]: Why do you need to make this extra copy of the leases

File: pkg/sql/lease.go [hunk 4]
```diff
@@ -1149,7 +1148,30 @@ func (m *LeaseManager) Release(lease *LeaseState) error {
...
+		t.releaseLeasesIfNotActive(toRelease, m.LeaseStore)
+		t.mu.Unlock()
+	}
```
Comment (vivekmenezes) [inline pkg/sql/lease.go]: Are you confident that we can hold on to m.mu while running the loop above?

File: pkg/sql/lease.go (hunk 2 above)
Comment (tamird) [inline pkg/sql/lease.go]: fwiw I think the current form is clearer. if anything, i'd check the testing knob first since it avoids a function call.

Comment (asubiotto) [inline pkg/sql/lease.go]: I agree that the current form is clearer. Will push back the draining check.

File: pkg/sql/lease.go (hunk 3 above)
Comment (asubiotto) [inline pkg/sql/lease.go]: `releaseLeasesIfNotActive` results in a modification of `t.active.data` per the comment on `releaseLeasesIfNotActive`. A discussion of this exists in the reviewable comments.

File: pkg/sql/lease.go (hunk 4 above)
Comment (asubiotto) [inline pkg/sql/lease.go]: Yes, the locking order is correct according to the comment on `LeaseManager` and it protects both `draining` and `m.tables`.

**Comment by asubiotto** [comment]
Review status: 2 of 4 files reviewed at latest revision, 6 unresolved discussions.

---

*[pkg/sql/lease.go, line 1154 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/12501#-KZS7ETauiVwiRDqDzzV-r1-1154:-KZSlesi32XZkh9ncygk:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/7a58c3eec696e84a2bfb97b065fb0e3c914bafaa/pkg/sql/lease.go#L1154)):*
<details><summary><i>Previously, vivekmenezes wrote…</i></summary><blockquote>

s/isDrainingLeases/isDraining
</blockquote></details>

Done.

---

*[pkg/sql/lease.go, line 1171 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/12501#-KZSB3LcTCfJPH-uZ91P:-KZSlg82miebzjuqo_GR:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/7a58c3eec696e84a2bfb97b065fb0e3c914bafaa/pkg/sql/lease.go#L1171)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

wow, that behaviour is quite bizarre, and with this patch, both callers of that function make a copy of `t.active.data` before calling it. Perhaps `releaseLeasesIfNotActive` should instead lose its first parameter and make whatever copies it needs internally.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/12501)*

**Comment by tamird** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 6 unresolved discussions, some commit checks pending.

---

*[pkg/server/server.go, line 755 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/12501#-KZS8_z-wdY0VDffXFjY:-KZSmO2wQMIw4b-Db18B:b-yktzq0) ([raw file](https://github.com/cockroachdb/cockroach/blob/7a58c3eec696e84a2bfb97b065fb0e3c914bafaa/pkg/server/server.go#L755)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

Sorry, I'm talking about the previous version of the code having the same behavior. Will change this to execute the `LeaseManager` draining logic even if `pgServer.SetDraining` errors out.
</blockquote></details>

any reason your new changes don't use `switch mode` as I suggested, nor the expression `errors.Errorf("unknown drain mode %s", mode)`?

---

*[pkg/server/server.go, line 754 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/12501#-KZSme__LtHbc6i7fHG_:-KZSme__LtHbc6i7fHGa:b2a6qqj) ([raw file](https://github.com/cockroachdb/cockroach/blob/b0f682e2d3bcd6c463f1e788a44ca6f3f528d153/pkg/server/server.go#L754)):*
> ```Go
> 		switch {
> 		case mode == serverpb.DrainMode_CLIENT:
> 			err := s.pgServer.SetDraining(setTo)
> ```

since this is surprising to read, it should probably have a comment explaining why the ordering matters

---

*[pkg/sql/lease.go, line 720 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/12501#-KZS7ETauiVwiRDqDzzV-r1-720:-KZSms7Xxipj6Cs16UB2:b-fo385j) ([raw file](https://github.com/cockroachdb/cockroach/blob/7a58c3eec696e84a2bfb97b065fb0e3c914bafaa/pkg/sql/lease.go#L720)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

I agree that the current form is clearer. Will push back the draining check.
</blockquote></details>

Note that you're still evaluating every one of these guys.
how about:
```
// Figure out if we'd like to remove the lease from the store asap (i.e. when
// the refcount drops to 0). If so, we'll need to mark the lease as released.
removeOnceDereferenced := m.LeaseStore.testingKnobs.RemoveOnceDereferenced ||
	// Release from the store if the table has been deleted; no leases can be
	// acquired any more.
	t.deleted ||
	// Release from the store if the lease is not for the latest version; only
	// leases for the latest version can be acquired.
	s != t.active.findNewest(0) ||
	...
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/12501)*

**Comment by asubiotto** [comment]
Review status: all files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---

*[pkg/server/server.go, line 755 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/12501#-KZS8_z-wdY0VDffXFjY:-KZSos_Hh_hiB5YPF6jG:binhcf2) ([raw file](https://github.com/cockroachdb/cockroach/blob/7a58c3eec696e84a2bfb97b065fb0e3c914bafaa/pkg/server/server.go#L755)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

any reason your new changes don't use `switch mode` as I suggested, nor the expression `errors.Errorf("unknown drain mode %s", mode)`?
</blockquote></details>

None. They escaped my attention.

---

*[pkg/server/server.go, line 754 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/12501#-KZSme__LtHbc6i7fHG_:-KaCtIjy_9VkVsrC_IdK:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/b0f682e2d3bcd6c463f1e788a44ca6f3f528d153/pkg/server/server.go#L754)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

since this is surprising to read, it should probably have a comment explaining why the ordering matters
</blockquote></details>

Done.

---

*[pkg/sql/lease.go, line 720 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/12501#-KZS7ETauiVwiRDqDzzV-r1-720:-Ka88gt8nfbUEOOdoqPp:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/7a58c3eec696e84a2bfb97b065fb0e3c914bafaa/pkg/sql/lease.go#L720)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

Note that you're still evaluating every one of these guys.
how about:
```
// Figure out if we'd like to remove the lease from the store asap (i.e. when
// the refcount drops to 0). If so, we'll need to mark the lease as released.
removeOnceDereferenced := m.LeaseStore.testingKnobs.RemoveOnceDereferenced ||
	// Release from the store if the table has been deleted; no leases can be
	// acquired any more.
	t.deleted ||
	// Release from the store if the lease is not for the latest version; only
	// leases for the latest version can be acquired.
	s != t.active.findNewest(0) ||
	...
```
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/12501)*

**Comment by vivekmenezes** [comment]
Review status: 1 of 4 files reviewed at latest revision, 8 unresolved discussions, some commit checks failed.

---

*[pkg/server/server.go, line 760 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/12501#-KaD0P5T5suK1x-4kViK:-KaD0P5UNaHJaU0yFlXU:b-h35oou) ([raw file](https://github.com/cockroachdb/cockroach/blob/e122380df6a4e3bfc49765e6a9a84c28f970ff17/pkg/server/server.go#L760)):*
> ```Go
> 				// work.
> 				defer s.leaseMgr.SetDraining(setTo)
> 				return s.pgServer.SetDraining(setTo)
> ```

you want to call leaseMgr.SetDraining() even when pgServer.SetDraining() returns an error?

---

*[pkg/sql/lease_test.go, line 448 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/12501#-KaD-eYxyZh93SDL7XE_:-KaD-eYyTdeKmq2EJJnY:b-sp6lib) ([raw file](https://github.com/cockroachdb/cockroach/blob/e122380df6a4e3bfc49765e6a9a84c28f970ff17/pkg/sql/lease_test.go#L448)):*
> ```Go
> 		if _, err := t.acquire(1, descID, 0); !testutils.IsError(err, "cannot acquire lease when draining") {
> 			t.Fatalf("unexpected error: %v", err)
> 		}
> ```

I suppose you could move this test to soon after you call SetDraining(true) above

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/12501)*

**Comment by asubiotto** [comment]
Review status: 1 of 4 files reviewed at latest revision, 8 unresolved discussions.

---

*[pkg/server/server.go, line 760 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/12501#-KaD0P5T5suK1x-4kViK:-KaD2VezvxUT4RHV0F_c:bf2ks6q) ([raw file](https://github.com/cockroachdb/cockroach/blob/e122380df6a4e3bfc49765e6a9a84c28f970ff17/pkg/server/server.go#L760)):*
<details><summary><i>Previously, vivekmenezes wrote…</i></summary><blockquote>

you want to call leaseMgr.SetDraining() even when pgServer.SetDraining() returns an error?
</blockquote></details>

Yes. An error from `pgServer.SetDraining` means that the server is in the draining state but open connections may continue to exist. We still want to delete all unreferenced leases, prevent these connections from acquiring new ones, and if leases held by these open connections are released, remove them from `system.lease`.

---

*[pkg/sql/lease_test.go, line 448 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/12501#-KaD-eYxyZh93SDL7XE_:-KaD4XKaEdzkGwjr-V5h:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/e122380df6a4e3bfc49765e6a9a84c28f970ff17/pkg/sql/lease_test.go#L448)):*
<details><summary><i>Previously, vivekmenezes wrote…</i></summary><blockquote>

I suppose you could move this test to soon after you call SetDraining(true) above
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/12501)*

**Comment by tamird** [comment]
:lgtm: (i think, lost most of the mental context on this one)

---

Reviewed 2 of 3 files at r3, 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 6 unresolved discussions, some commit checks pending.

---

*[pkg/sql/lease_test.go, line 448 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/12501#-KaD-eYxyZh93SDL7XE_:-KaD5KCmtPGQw_wSpUXd:bmqd1gh) ([raw file](https://github.com/cockroachdb/cockroach/blob/e122380df6a4e3bfc49765e6a9a84c28f970ff17/pkg/sql/lease_test.go#L448)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

errant newline here, now.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/12501#-:-KaD5NC2NdeNker2g7hu:b8vtavf)*

**Comment by asubiotto** [comment]
I'll wait a bit in case you want to take a second look. @andreimatei, would you mind giving the PR a quick look?

---

Review status: 3 of 4 files reviewed at latest revision, 6 unresolved discussions, some commit checks pending.

---

*[pkg/sql/lease_test.go, line 448 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/12501#-KaD-eYxyZh93SDL7XE_:-KaDKp6eVbHKUnePLITz:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/e122380df6a4e3bfc49765e6a9a84c28f970ff17/pkg/sql/lease_test.go#L448)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

errant newline here, now.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/12501#-:-KaDKsYnV2zRyAnCi6wB:by8ydvc)*

**Comment by tamird** [comment]
Reviewed 1 of 1 files at r5.
Review status: all files reviewed at latest revision, 6 unresolved discussions, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/12501)*

**Comment by vivekmenezes** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/12501#-:-KaDXQWtrhgmUkBlm9PH:bnfp4nl)*

**Comment by andreimatei** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[pkg/sql/lease.go, line 727 at r5](https://reviewable.io:443/reviews/cockroachdb/cockroach/12501#-KaE1ns505bRzeiyWQX4:-KaE1ns505bRzeiyWQX5:b-k8iopz) ([raw file](https://github.com/cockroachdb/cockroach/blob/46cda79d086f88b35cd738cf213174fc8f06b89f/pkg/sql/lease.go#L727)):*
> ```Go
> 		// when the refcount drops to 0). If so, we'll need to mark the lease as
> 		// released.
> 		removeOnceDereferenced := m.LeaseStore.testingKnobs.RemoveOnceDereferenced ||
> ```

nit: my personal preference is to put random stuff like this testing knob at the end of the condition and more important conditions first.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/12501#-:-KaE32TDJO2SL62hgy_R:bnfp4nl)*

**Comment by asubiotto** [comment]
TestLeaseManagerDrain was failing under stress due to incorrectly tracking lease removal. Fixed and should be good to merge.

---

Review status: 3 of 4 files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[pkg/sql/lease.go, line 727 at r5](https://reviewable.io:443/reviews/cockroachdb/cockroach/12501#-KaE1ns505bRzeiyWQX4:-KaISAYPm7MBpvD5M1Cm:bd7tmny) ([raw file](https://github.com/cockroachdb/cockroach/blob/46cda79d086f88b35cd738cf213174fc8f06b89f/pkg/sql/lease.go#L727)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

nit: my personal preference is to put random stuff like this testing knob at the end of the condition and more important conditions first.
</blockquote></details>

Keeping as is.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/12501#-:-KaIRi7cEN3ALx5wLjJP:b-8x0j0s)*
