### PR TITLE
sql/copy: DESTINATION in non-external storage copies should be error

### LINKED ISSUE #87006: sql: destination argument of COPY is ignored
**Describe the problem**

It seems like the `DESTINATION` argument of `COPY` is ignored when `COPY` is run from the command line.

**To Reproduce**

On master, run `./cockroach demo`. Then run:
```
CREATE TABLE tab (col1 STRING, col2 STRING, col3 STRING, col4 STRING, col5 STRING, col6 STRING);
COPY tab FROM STDIN with destination = 'tab1.csv';
-- Now paste the following:
'remove'	'planned'	'slave'	'instrument'	'shoe'	'rays'
'doing'	'bring'	'color'	'busy'	'flat'	'difficulty'
'western'	'mouse'	'seems'	'fully'	'memory'	'neighborhood'
'cup'	'fairly'	'orbit'	'visit'	'lay'	'cave'
'dry'	'vast'	'instrument'	'scared'	'toy'	'completely'
'paragraph'	'roll'	'atomic'	'doctor'	'best'	'finish'
'job'	'suddenly'	'box'	'affect'	'on'	'date'
\.
```

Although the data is copied into `tab`, the destination `tab1.csv` seems to be ignored. The command succeeds but no file is created.

**Expected behavior**

I'm not sure exactly what the expected behavior should be since COPY and this DESTINATION parameter are not documented. But I would expect *something* to happen -- either an error message or else creation of the file.

Jira issue: CRDB-19090

### PR DESCRIPTION
**Pull request by cucaroach**
CRDB supports a DESTINATION argument on copy that's only valid on
file upload copies to external storage.

Fixes: #87006
Release justification: low risk updates to new functionality
Release note: None

### CODE REVIEW

File: pkg/sql/copy.go [hunk 1]
```diff
@@ -232,6 +232,12 @@ func newCopyMachine(
 
 		c.csvEscape, _ = utf8.DecodeRuneInString(s)
 	}
+	if n.Options.Destination != nil {
+		return nil, pgerror.Newf(
+			pgcode.FeatureNotSupported,
+			"DESTINATION can only be specified when table is external storage table",
```
Comment (otan) [inline pkg/sql/copy.go:238]: what is "external storage table" / is that clear to the user / should we be attaching an issue to it?

Comment (cucaroach) [reply pkg/sql/copy.go:238]: Its a fake table name that's indicates a nodelocal or a user file.  I couldn't find any docs on this so I'm not sure how to say it better.  I'm not sure but I think this copy destination form is what `cockroach userfile upload` is implemented with.

**Review by otan — APPROVED** [review]
/shrug

**Comment by cucaroach** [comment]
bors r+
TFTRs!

**Comment by cucaroach** [comment]
bors r+ 
flake...

**Comment by rafiss** [comment]
Heads up - if you were counting on this to be in v22.2, it will need to be backported now

**Comment by cucaroach** [comment]
blathers backport 22.2

**Comment by mgartner** [comment]
Does this need to be backported to 22.2.0 too?

**Comment by cucaroach** [comment]
I don't think so, its a pretty minor bug.
