### PR TITLE
roachtest: poll job status in jobSurvivesNodeShutdown

### LINKED ISSUE #72721: roachtest: restore/nodeShutdown/worker failed
roachtest.restore/nodeShutdown/worker [failed](https://teamcity.cockroachdb.com/viewLog.html?buildId=3724964&tab=buildLog) with [artifacts](https://teamcity.cockroachdb.com/viewLog.html?buildId=3724964&tab=artifacts#/restore/nodeShutdown/worker) on release-21.1 @ [c6db4eb5fb9770dfa3c7898e514dd5d77c2cdcba](https://github.com/cockroachdb/cockroach/commits/c6db4eb5fb9770dfa3c7898e514dd5d77c2cdcba):

```
The test failed on branch=release-21.1, cloud=gce:
test artifacts and logs in: /home/agent/work/.go/src/github.com/cockroachdb/cockroach/artifacts/restore/nodeShutdown/worker/run_1
	jobs.go:142,restore.go:288,test_runner.go:733: job too fast! job got to state succeeded before the target node could be shutdown
		(1) attached stack trace
		  -- stack trace:
		  | main.jobSurvivesNodeShutdown.func2
		  | 	/home/agent/work/.go/src/github.com/cockroachdb/cockroach/pkg/cmd/roachtest/jobs.go:127
		  | main.(*monitor).Go.func1
		  | 	/home/agent/work/.go/src/github.com/cockroachdb/cockroach/pkg/cmd/roachtest/cluster.go:2666
		  | golang.org/x/sync/errgroup.(*Group).Go.func1
		  | 	/home/agent/work/.go/src/github.com/cockroachdb/cockroach/vendor/golang.org/x/sync/errgroup/errgroup.go:57
		  | runtime.goexit
		  | 	/usr/local/go/src/runtime/asm_amd64.s:1371
		Wraps: (2) job too fast! job got to state succeeded before the target node could be shutdown
		Error types: (1) *withstack.withStack (2) *errutil.leafError
```
<details><summary>Reproduce</summary>
<p>
<p>To reproduce, try:

```bash
# From https://go.crdb.dev/p/roachstress, perhaps edited lightly.
caffeinate ./roachstress.sh restore/nodeShutdown/worker
```
</p>
</p>
</details>
/cc @cockroachdb/bulk-io
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*restore/nodeShutdown/worker.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)
</sub>

### PR DESCRIPTION
**Pull request by msbutler**
Previously, any bulk roachtest invoking jobSurvivesNodeShutdown would wait 5
seconds before shutting down a node. These roachtests can flake if the job takes
less than 5 seconds to run.

I modify jobSurvivesNodeShutdown to query the job status once per second, and
to wait an additional second if the job is running before shutting a node down.
We wait at least a second to ensure the bulk job has begun doing meaningful
work.

Fixes: #72721

Release Note: None

### CODE REVIEW

**Review by stevendanna — APPROVED** [review]
LGTM! Let's see if this helps on master for a bit before backporting it.

File: pkg/cmd/roachtest/tests/jobs.go [hunk 1]
```diff
@@ -103,31 +102,39 @@ func jobSurvivesNodeShutdown(
...
+			case <-ctx.Done():
+				return errors.Wrapf(ctx.Err(), "stopping test, did not shutdown node")
+			case <-timer.C:
+				timer.Read = true
+			}
+			// Break a second after confirming the job is running to ensure the node shutdown
+			// "in the middle" of running the job, right after the job began running.
+			if jobRunning == true {
+				break
+			}
```
Comment (stevendanna) [inline pkg/cmd/roachtest/tests/jobs.go:137]: I think in our original discussion we talked about how cancelling in the middle of the job might be a side-effect of the old code, which is why it is preserved here.  Perhaps lets revisit this if we are still having issues after this fix is in since we can probably come up with either better coordination or just immediately try to cancel once we know it is running.

**Comment by msbutler** [comment]
bors, r=stevendanna

**Comment by msbutler** [comment]
blathers backport 21.2

**Comment by msbutler** [comment]
blathers backport 21.1
