### PR TITLE
kvprober: reuse TracingEnabled config variable

### LINKED ISSUE #131672: Sentry: signal_unix.go:881: runtime error: invalid memory address or nil pointer dereference (1) attached stack trace   -- stack trace:   | runtime.sigpanic   | 	GOROOT/src/runtime/signal_unix.go:881 ...
This issue was auto filed by Sentry. It represents a crash or reported error on a live cluster with telemetry enabled.

Sentry Link: [https://cockroach-labs.sentry.io/issues/5935915086/?referrer=webhooks_plugin](https://cockroach-labs.sentry.io/issues/5935915086/?referrer=webhooks_plugin)

Panic Message:

```
signal_unix.go:881: runtime error: invalid memory address or nil pointer dereference
(1) attached stack trace
  -- stack trace:
  | runtime.sigpanic
  | 	GOROOT/src/runtime/signal_unix.go:881
  | github.com/cockroachdb/cockroach/pkg/kv/kvprober.(*Prober).writeProbeImpl
  | 	github.com/cockroachdb/cockroach/pkg/kv/kvprober/kvprober.go:515
  | github.com/cockroachdb/cockroach/pkg/kv/kvprober.(*Prober).writeProbe
  | 	github.com/cockroachdb/cockroach/pkg/kv/kvprober/kvprober.go:447
  | github.com/cockroachdb/cockroach/pkg/kv/kvprober.(*Prober).Start.func1.1
  | 	github.com/cockroachdb/cockroach/pkg/kv/kvprober/kvprober.go:341
  | github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunAsyncTaskEx.func2
  | 	github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:503
  | runtime.goexit
  | 	src/runtime/asm_amd64.s:1695
Wraps: (2) runtime error: invalid memory address or nil pointer dereference
Error types: (1) *withstack.withStack (2) runtime.errorString
-- report composition:
runtime.errorString
signal_unix.go:881: *withstack.withStack (top exception)
```

<details>
<summary>Stacktrace (expand for inline code snippets):</summary>

[src/runtime/asm_amd64.s#L1694-L1696](src/runtime/asm_amd64.s#L1694-L1696)
[https://github.com/cockroachdb/cockroach/blob/a55b0171112fc9471764f6fe08d10f6fe323ff50/pkg/util/stop/stopper.go#L502-L504](https://github.com/cockroachdb/cockroach/blob/a55b0171112fc9471764f6fe08d10f6fe323ff50/pkg/util/stop/stopper.go#L502-L504)
[https://github.com/cockroachdb/cockroach/blob/a55b0171112fc9471764f6fe08d10f6fe323ff50/pkg/kv/kvprober/kvprober.go#L340-L342](https://github.com/cockroachdb/cockroach/blob/a55b0171112fc9471764f6fe08d10f6fe323ff50/pkg/kv/kvprober/kvprober.go#L340-L342)
[https://github.com/cockroachdb/cockroach/blob/a55b0171112fc9471764f6fe08d10f6fe323ff50/pkg/kv/kvprober/kvprober.go#L446-L448](https://github.com/cockroachdb/cockroach/blob/a55b0171112fc9471764f6fe08d10f6fe323ff50/pkg/kv/kvprober/kvprober.go#L446-L448)
[https://github.com/cockroachdb/cockroach/blob/a55b0171112fc9471764f6fe08d10f6fe323ff50/pkg/kv/kvprober/kvprober.go#L514-L516](https://github.com/cockroachdb/cockroach/blob/a55b0171112fc9471764f6fe08d10f6fe323ff50/pkg/kv/kvprober/kvprober.go#L514-L516)
[GOROOT/src/runtime/signal_unix.go#L880-L882](GOROOT/src/runtime/signal_unix.go#L880-L882)
</details>

```
src/runtime/asm_amd64.s in runtime.goexit at line 1695
pkg/util/stop/stopper.go in pkg/util/stop.(*Stopper).RunAsyncTaskEx.func2 at line 503
pkg/kv/kvprober/kvprober.go in pkg/kv/kvprober.(*Prober).Start.func1.1 at line 341
pkg/kv/kvprober/kvprober.go in pkg/kv/kvprober.(*Prober).writeProbe at line 447
pkg/kv/kvprober/kvprober.go in pkg/kv/kvprober.(*Prober).writeProbeImpl at line 515
GOROOT/src/runtime/signal_unix.go in runtime.sigpanic at line 881
```

### Tags

| Tag | Value |
| --- | --- |
| Command | server |
| Environment | v24.3.0-alpha.1 |
| Go Version | go1.22.5 X:nocoverageredesign |
| Platform | linux amd64 |
| Distribution | CCL |
| Cockroach Release | v24.3.0-alpha.1 |
| Cockroach SHA | a55b0171112fc9471764f6fe08d10f6fe323ff50 |
| # of CPUs | 4 |
| # of Goroutines | 757 |

Jira issue: CRDB-42649

### PR DESCRIPTION
**Pull request by VishalJaishankar**
There was a panic caused due to null reference from variable `finishAndGetRecording` 
see #131672

This was happening because we check the TracingEnabled config twice and in a corner case the flag was false on the first call and enabled when the second call was made causing the null reference.

This PR checks the flag once and reuses it.

Fixes: #131672

Epic: none
Release note: None

### CODE REVIEW

File: pkg/kv/kvprober/kvprober.go [hunk 1]
```diff
@@ -425,7 +425,7 @@ func (p *Prober) readProbeImpl(ctx context.Context, ops proberOpsI, txns proberT
 
 	d := timeutil.Since(start)
 	// Extract leaseholder information from the trace recording if enabled.
-	if tracingEnabled.Get(&p.settings.SV) {
+	if tracingEnabled.Get(&p.settings.SV) && finishAndGetRecording != nil {
 		leaseholder := p.returnLeaseholderInfo(finishAndGetRecording())
 		ctx = logtags.AddTag(ctx, "leaseholder", leaseholder)
```
Comment (joshimhoff) [inline pkg/kv/kvprober/kvprober.go:430]: `writeProbeImpl` also has the bug.

File: pkg/kv/kvprober/kvprober.go [hunk 2]
```diff
@@ -425,7 +425,7 @@ func (p *Prober) readProbeImpl(ctx context.Context, ops proberOpsI, txns proberT
 
 	d := timeutil.Since(start)
 	// Extract leaseholder information from the trace recording if enabled.
-	if tracingEnabled.Get(&p.settings.SV) {
+	if tracingEnabled.Get(&p.settings.SV) && finishAndGetRecording != nil {
```
Comment (joshimhoff) [inline pkg/kv/kvprober/kvprober.go:428]: Why is `finishAndGetRecording` null? Is it bc/ tracing was enabled part way thru the trace? If yes, I think a clearer way to write the bug fix is to check the cluster setting a single time at the top of this function (store it in a local variable for use later), instead of checking it twice.

File: pkg/kv/kvprober/kvprober.go [hunk 3]
```diff
@@ -425,7 +425,7 @@ func (p *Prober) readProbeImpl(ctx context.Context, ops proberOpsI, txns proberT
 
 	d := timeutil.Since(start)
```
Comment (joshimhoff) [inline pkg/kv/kvprober/kvprober.go:426]: Does this bug panic the server? We should ensure the call to `logcrash.RecoverAndReportNonfatalPanic` means this bug does NOT panic the server. I think it does, but we should check this via a manual test or similar.

**Review by joshimhoff — COMMENTED** [review]
Nice job finding the bug. Few comments.

File: pkg/kv/kvprober/kvprober.go (hunk 2 above)
Comment (VishalJaishankar) [reply pkg/kv/kvprober/kvprober.go:428]: I looked at the occurrences of the error in sentry and this happened in 2 separate clusters only once, which matches with the flag changing inbetween the 2 calls.
signal_unix_go_881__sigpanic___runtime_errorString__runtime_error__invalid_memory_address_or_nil_pointer_dereference_via__withstack_withStack_—_cockroach-labs_—_cockroachdb

Taking the cluster id `b1c618ed-a9ff-4264-b623-dff46c7c90ae` which is `crl-staging-8k4c`, the crash happened at `Oct 1, 2024 4:15:23 PM UTC` which corresponds to when the flag was switched [ddog log](https://us5.datadoghq.com/logs?query=crl-staging-8k4c%20set%20kv.prober.tracing.enabled%20from%20false%20to%20true%20&agg_m=count&agg_m_source=base&agg_t=count&cols=host%2Cservice&fromUser=true&messageDisplay=inline&refresh_mode=paused&storage=flex_tier&stream_sort=time%2Casc&viz=stream&from_ts=1727799237029&to_ts=1727799608353&live=false)

File: pkg/kv/kvprober/kvprober.go (hunk 1 above)
Comment (VishalJaishankar) [reply pkg/kv/kvprober/kvprober.go:431]: added the logic for this too. Thanks!

File: pkg/kv/kvprober/kvprober.go (hunk 3 above)
Comment (VishalJaishankar) [reply pkg/kv/kvprober/kvprober.go:427]: the error message does suggest that it panics
`signal_unix.go:881: runtime error: invalid memory address or nil pointer dereference
(1) attached stack trace
  -- stack trace:
  | runtime.sigpanic
  | 	GOROOT/src/runtime/signal_unix.go:881`
will see whats up here

Comment (VishalJaishankar) [reply pkg/kv/kvprober/kvprober.go:427]: Verified locally by panicking the server, but it recovered as expected.

**Review by kvoli — COMMENTED** [review]
:lgtm:  -- I have an outstanding question regarding how this panic manifested, after which I'll stamp.

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/132741#-:-O9oxV6xEnyk5j3zYfd3:brnjywp)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @joshimhoff and @VishalJaishankar)

___
*[`-- commits` line 6 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/132741#-O9owYeKBOYQORzNrlaF):*
nit: nil rather than null here and above for idiomatic Golang.

Also even smaller nit: I'd refer to the commit, rather than PR, e.g., "This commit checks..."
___
*[`pkg/kv/kvprober/kvprober.go` line 370 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/132741#-O9ox73r5p5YJKSXgoeL:-O9ox73s4jqEK9MRis4S:b2fpnln) ([raw file](https://github.com/cockroachdb/cockroach/blob/24cf4deb6275c1cf558f097c184b03bb1acef097/pkg/kv/kvprober/kvprober.go#L370)):*
> ```Go
> 	var probeCtx = ctx
> 
> 	isTracingEnabled := tracingEnabled.Get(&p.settings.SV)
> ```

I'm a bit confused how the added step here of assigning a conditional var, then checking it is any different than before. Was the panic explicitly on `tracingEnabled`?  Cluster settings vars should never be nil, unless they were re-assigned at runtime, or declared at compile time as nil. What happened here?

**Review by kvoli — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/132741#-:-O9oy-Og81qdhol0iWBZ:bnfp4nl)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @joshimhoff and @VishalJaishankar)

___
*[`pkg/kv/kvprober/kvprober.go` line 370 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/132741#-O9ox73r5p5YJKSXgoeL:-O9oxgIgA7e7dAbofiIM:b-rh4sbp) ([raw file](https://github.com/cockroachdb/cockroach/blob/24cf4deb6275c1cf558f097c184b03bb1acef097/pkg/kv/kvprober/kvprober.go#L370)):*
<details><summary><i>Previously, kvoli (Austen) wrote…</i></summary><blockquote>

I'm a bit confused how the added step here of assigning a conditional var, then checking it is any different than before. Was the panic explicitly on `tracingEnabled`?  Cluster settings vars should never be nil, unless they were re-assigned at runtime, or declared at compile time as nil. What happened here?
</blockquote></details>

Ah, I see it in the PR description. Consider adding this to the commit description as well.

When contributors `git blame`, they tend not to look at the PR description unless they wish to also look at the review comments. 

Adding this all to the commit description makes this process smoother.

**Review by joshimhoff — APPROVED** [review]
LGTM too! Thanks for fixing, Vishal. Thanks for reviewing, Austen. Agree re: moving the nice description of the bug in the PR description to the commit message before merge.

**Comment by VishalJaishankar** [comment]
bors r=kvoli,joshimhoff
