### PR TITLE
sql: fix qualified index name resolution

### LINKED ISSUE #24475: sql: not-searched index name found already qualified
The following statement fails to execute. This is likely fallout from https://github.com/cockroachdb/cockroach/pull/22753.

```
8 exec "" {} "DROP INDEX public.\"primary\"" {} 0.109 0
"programmer error: not-searched index name found already qualified: public.\"primary\"@"
```

Found when revisiting https://github.com/cockroachdb/cockroach/issues/22298.

### PR DESCRIPTION
**Pull request by knz**
Fixes #24475.
cc @nvanbenschoten 

In CockroachDB index names are relative to a table name
(e.g. `tbl@idx`) but in Postgres index names live in the schema
namespace. To offer compatibility with Postgres, CockroachDB
implements a special name resolution algorithm for index names
specified without the '@' syntax. For example, `DROP INDEX foo` will
search all tables in the current schema to find one with index name
`foo`.

Prior to this patch, CockroachDB was not able to search for a
_qualified_ index name specified without the '@' syntax. For example,
TypeORM issues `DROP INDEX public."primary"`, expecting to be able to
drop the primary index of some table in the `public` schema. This was
not recognized by CockroachDB.

This patch extends the name resolution for index names to support both
partial and complete qualification, using the same name resolution
rules as other objects.

Release note (sql change): CockroachDB now supports more ways to
specify an index name for statements that require one (e.g., `DROP
INDEX`, `ALTER INDEX ... RENAME`, etc.), in a way more compatible with
PostgreSQL.

### CODE REVIEW

File: pkg/sql/resolver.go [hunk 1]
```diff
@@ -370,32 +373,39 @@ func expandIndexName(
...
+		foundTn, desc, err = findTableContainingIndex(
+			sc.LogicalSchemaAccessor(), tn.Catalog(), tn.Schema(), index.Index, lookupFlags)
 		if err != nil {
 			return nil, nil, err
-		} else if tn == nil {
-			// NB: tn is nil here if and only if requireTable is
-			// false, otherwise err would be non-nil.
-			return nil, nil, nil
+		} else if foundTn != nil {
+			// Memoize the table name that was found.
```
Comment (justinj) [inline pkg/sql/resolver.go]: Is this comment still true? Doesn't look like we're sticking anything onto the struct anymore, unless `tn` points into the struct as a result of having been returned from `Normalize`, which I think would merit a comment.

**Review by justinj — APPROVED** [review]

File: pkg/sql/resolver.go (hunk 1 above)
Comment (knz) [reply pkg/sql/resolver.go]: Yes it is still true. I added a comment.

**Comment by nvanbenschoten** [comment]
@knz yeah, this seems to have fixed the issue with TypeORM. Thanks!
