### PR TITLE
cli: switch to jackc/pgx

### LINKED ISSUE #48607: cli: switch to using jackc/pgx instead of lib/pq
Pgx is a more full-featured Postgres driver that allows more customizability and provides access to useful Postgres-protocol-specific things than lib/pq, which is hindered by its implementation of the database/sql interfaces.

It would be really nice to have Pgx's extra features in the SQL shell. For example, implementing a client-side flag to display type OIDs per column would be easy with pgx but impossible with lib/pq.

Pgx has gotten some upgrades recently that are necessary for that example. But, pgx is also a user of Go modules. Dep can't handle this and blows up when you try to add pgx of a newish version to the dependency list.

See PR https://github.com/stripe/stripe-go/pull/1055 - they ran into similar problems with dep and ended up just losing support for dep when they upgraded to Go modules.

### LINKED ISSUE #55234: cli: compound statements that don't return rows aren't reported correctly
The following compound statement works correctly, since each statement returns rows:

```
root@:26257/defaultdb> select 1; select 2;
  ?column?
------------
         1
(1 row)

Note: timings for multiple statements on a single line are not supported. See https://go.crdb.dev/issue-v/48180/v20.2.

  ?column?
------------
         2
(1 row)

Note: timings for multiple statements on a single line are not supported. See https://go.crdb.dev/issue-v/48180/v20.2.
```

The next compound statement doesn't. I'd expect it to say `CREATE TABLE` before returning the results of the second statement, since it did in fact execute both statements:

```
root@:26257/defaultdb> create table testtable(a int); select 1;
  ?column?
------------
         1
(1 row)

Note: timings for multiple statements on a single line are not supported. See https://go.crdb.dev/issue-v/48180/v20.2.

root@:26257/defaultdb> select * from testtable;
  a
-----
(0 rows)

Time: 27ms total (execution 27ms / network 0ms)
```

Jira issue: CRDB-6301

### LINKED ISSUE #61114: cli: sql does not render second select in single-stmt txn
**Describe the problem**

psql (run against same CRDB demo instance as below):

```
demo=> begin;select 1; select * from (select 1 as foo) where foo = 2;commit
BEGIN
 ?column? 
----------
        1
(1 row)

 foo 
-----
(0 rows)
```

crdb:

```
$ ./cockroach demo -e "begin;select 1; select * from (select 1 as foo) where foo = 2;commit"  ?column?
------------
         1
(1 row)

COMMIT
```

**To Reproduce**

`./cockroach demo` on master

**Expected behavior**

I was expecting the `./cockroach demo -e` invocation to also render a zero-row result for the second select.

**Additional data / screenshots**

Removing the begin and commit fixes it:

```
$ ./cockroach demo -e "select 1; select * from (select 1 as foo) where foo = 2"
  ?column?
------------
         1
(1 row)

Time: 0ms

  foo
-------
(0 rows)

Time: 1ms
```

Leaving the txn in but making the second query return a result fixes it:

```
$ ./cockroach demo -e "begin;select 1; select * from (select 1 as foo) where foo = 1;commit;"  ?column?
------------
         1
(1 row)

  foo
-------
    1
(1 row)
```

Removing the first query fixes it:

```
$ ./cockroach demo -e "begin; select * from (select 1 as foo) where foo = 2;commit;"
  foo
-------
(0 rows)
```

Opening the txn separately does *not* fix it. Opening the txn & running the first select and then running the rest separately *does* fix it.

My reading from all of this is that when in an explicitly opened txn, a multi-select stmt will erroneously omit rendering an empty result set for all but the first query.

**Environment:**
master at time of issue creation

**Additional context**
I was confused :-)

Jira issue: CRDB-6281

### LINKED ISSUE #68671: cli: quoting of jsonb results in cockroach sql do not match jsonb cast to string, nor postgres
When `JSONB` results are printed by `cockroach sql` the quoting does not match the same `JSONB` cast to `VARCHAR`. Nor do the printed results match PostgreSQL. I'm not sure whether this printing happens on the server side or client side.

CockroachDB 21.2 (development) with `cockroach sql`:

```
demo@127.0.0.1:26257/defaultdb> SELECT '"ab"'::JSONB, '"ab"'::JSONB::VARCHAR, '"a\\b"'::JSONB, '"a\\b"'::JSONB::VARCHAR, '"a\"b"'::JSONB, '"a\"b"'::JSONB::VARCHAR;
  jsonb | varchar |  jsonb   | varchar |  jsonb  | varchar
--------+---------+----------+---------+---------+----------
  "ab"  | "ab"    | "a\\\\b" | "a\\b"  | "a\\"b" | "a\"b"
(1 row)
```

PostgreSQL 13.3 with `psql`:

```
michae2=# SELECT '"ab"'::JSONB, '"ab"'::JSONB::VARCHAR, '"a\\b"'::JSONB, '"a\\b"'::JSONB::VARCHAR, '"a\"b"'::JSONB, '"a\"b"'::JSONB::VARCHAR;
 jsonb | varchar | jsonb  | varchar | jsonb  | varchar
-------+---------+--------+---------+--------+---------
 "ab"  | "ab"    | "a\\b" | "a\\b"  | "a\"b" | "a\"b"
(1 row)
```

This breaks `ALTER TABLE INJECT STATISTICS` when the histograms produced by `SHOW STATISTICS USING JSON` contain `"` characters.

Jira issue: CRDB-9158

### LINKED ISSUE #76651: cli: does not format CHAR(n) type correctly
```sql
root@localhost:26257/defaultdb> create table ta(c1 varchar(10));
CREATE TABLE


Time: 129ms total (execution 129ms / network 0ms)

root@localhost:26257/defaultdb> create table tb(c1 char(10));
CREATE TABLE


Time: 148ms total (execution 148ms / network 1ms)

root@localhost:26257/defaultdb> insert into ta values('你好');
INSERT 1


Time: 123ms total (execution 123ms / network 0ms)

root@localhost:26257/defaultdb> insert into tb values('你好');
INSERT 1


Time: 89ms total (execution 89ms / network 1ms)

root@localhost:26257/defaultdb> select * from ta;
   c1
--------
  你好
(1 row)


Time: 1ms total (execution 1ms / network 0ms)

root@localhost:26257/defaultdb> select * from tb;
                 c1
------------------------------------
  \xe4\xbd\xa0\xe5\xa5\xbd
(1 row)


Time: 1ms total (execution 1ms / network 0ms)
```

Jira issue: CRDB-13207

### LINKED ISSUE #80398: cli: does not properly respect the bytea_output setting for displaying BYTEA values
**Describe the problem**

The cockroach cli shows BYTEA values in a go-escaped format, which is difficult to worth with if you want to use the value by copy/pasting it into a different SQL command.

**To Reproduce**

Connect to a CRDB cluster using `cockroach sql` and run:
```
root@:26257/defaultdb> select descriptor from system.descriptor limit 1;
                                                                      descriptor
-------------------------------------------------------------------------------------------------------------------------------------------------------
  \x129\n\x06system\x10\x01\x1a%\n\r\n\x05admin\x10\x80\x10\x18\x80\x10\n\f\n\x04root\x10\x80\x10\x18\x80\x10\x12\x04node\x18\x02"\x00(\x01@\x00J\x00
```

**Expected behavior**
If you connect using `psql` to the same cluster, you get:
```
defaultdb=> select descriptor from system.descriptor limit 1;
                                                        descriptor
--------------------------------------------------------------------------------------------------------------------------
 \x12390a0673797374656d10011a250a0d0a0561646d696e1080101880100a0c0a04726f6f7410801018801012046e6f646518022200280140004a00
```

**Environment:**
 - CockroachDB commit dbbe9ed99a

**Additional context**
Using a cast like `select descriptor::text from system.descriptor limit 1;` does work correctly.

@knz points out that the behavior is a limitation of lib/pq, see: https://github.com/cockroachdb/cockroach/blob/11a0a9f420fb4ce31e9fdac16ecbf14283e4282a/pkg/cli/clisqlexec/format_value.go#L90-L106

Moving the CLI to use pgx could help address this issue.

Jira issue: CRDB-15625

### PR DESCRIPTION
**Pull request by rafiss**
This is split off from #81007 to make it easier to review.

Fixes https://github.com/cockroachdb/cockroach/issues/48607
Fixes https://github.com/cockroachdb/cockroach/issues/80398
Fixes https://github.com/cockroachdb/cockroach/issues/76651
Fixes https://github.com/cockroachdb/cockroach/issues/68671
Fixes https://github.com/cockroachdb/cockroach/issues/55234
Fixes https://github.com/cockroachdb/cockroach/issues/61114

- Address TODO about RowsAffected. Unlike lib/pq pgx doesn't use
  incorrect command tags for queries that return 0 rows, so we don't
  need this special logic.
- BYTEA values are now formatted correctly. pgx lets us scan results
  directly into a string that already has the proper formatting from pgwire.
- We needed an additional "multi result set" rows object. lib/pq would
  handle this with one interface, but this isn't possible using
  pgx/pgconn.

Release note (cli change): BYTEA values are now formatted according to
the bytea_output session setting.

Release note (cli change): The statement tag displayed for INSERT
statements now has the full information returned by the server. It is
the string "INSERT" followed by the OID of the row that was inserted
(which is currently always 0 in CockroachDB), followed by the number of
rows inserted.

Release note (cli change): BOOLEAN values are now formatted as `t`  or
`f` instead of `True` or `False`.

### CODE REVIEW

**Review by rafiss — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/81943)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @knz)

___
*[`pkg/cli/clisqlclient/rows_multi.go` line 103 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/81943#-N35sMLZBL7yNV0SDzgP:-N35sMLZBL7yNV0SDzgQ:b-lzv2h) ([raw file](https://github.com/cockroachdb/cockroach/blob/d98b5c59b57b04e2c405f0554a648cf3fb7276d2/pkg/cli/clisqlclient/rows_multi.go#L103)):*
> ```Go
> 		fieldOID := rd.FieldDescriptions()[i].DataTypeOID
> 		fieldFormat := rd.FieldDescriptions()[i].Format
> 		if dt, ok := r.connInfo.DataTypeForOID(fieldOID); !ok || strings.HasPrefix(dt.Name, "_") {
> ```

@knz i'm realizing that another option is to change this complicated conditional stmt into:

```
		var s string
		err := r.connInfo.Scan(fieldOID, fieldFormat, rowVal, &s)
		if err != nil {
			return pgx.ScanArgError{ColumnIndex: i, Err: err}
		}
		values[i] = s
```

that is, just decode everything into a string. (i believe this is also what `psql` does). this means that we'd just display whatever was sent over pgwire (which we already format properly)

it also means that we could get rid of all formatting logic in the CLI. i am _pretty_ sure that the reason we didn't do it this way before is because lib/pq didn't allow us to. do you know?

- from the user perspective, it would mean the formatting of booleans changes from `true/false` to `t/f`.
- it also seems like we'd want to fix a bug where FLOAT infinity is not formatted correctly in pgwire if it appears in an array. 

what do you think?

File: pkg/cli/clisqlclient/api.go [hunk 1]
```diff
@@ -85,9 +87,9 @@ type Conn interface {
 	// The sql argument is the SQL query to use to retrieve the value.
 	GetServerValue(ctx context.Context, what, sql string) (driver.Value, string, bool)
 
-	// GetDriverConn exposes the underlying SQL driver connection object
+	// GetPGXConn exposes the underlying PGX driver connection object
```
Comment (otan) [inline pkg/cli/clisqlclient/api.go:90]: nit: "underlying pgx driver"?

File: pkg/cli/clisqlclient/conn.go [hunk 2]
```diff
@@ -246,8 +242,8 @@ func (c *sqlConn) GetServerMetadata(
 ) (nodeID int32, version, clusterID string, err error) {
 	// Retrieve the node ID and server build info.
 	rows, err := c.Query(ctx, "SELECT * FROM crdb_internal.node_build_info")
-	if errors.Is(err, driver.ErrBadConn) {
```
Comment (otan) [inline pkg/cli/clisqlclient/conn.go:249]: can you explain how this changed? does the driver close the connection instead now?

File: pkg/cli/clisqlclient/rows.go [hunk 3]
```diff
@@ -78,18 +81,52 @@ func (r *sqlRows) Next(values []driver.Value) error {
...
+		return reflect.TypeOf(int32(0))
+	case pgtype.Int2OID:
+		return reflect.TypeOf(int16(0))
+	case pgtype.VarcharOID, pgtype.TextOID:
+		return reflect.TypeOf("")
+	case pgtype.BoolOID:
+		return reflect.TypeOf(false)
+	case pgtype.DateOID, pgtype.TimeOID, 1266, pgtype.TimestampOID, pgtype.TimestamptzOID:
+		// 1266 is the OID for TimeTZ.
+		// TODO(rafi): Add TimetzOID to pgtype.
```
Comment (otan) [inline pkg/cli/clisqlclient/rows.go:102]: i wonder whether time.Time is the appropriate thing to use for Time/TimeTZ. 24:00:00 time springs to mind as a point of confusion. that said, if we do that today then so be it.

can we use `pgtype.OID(oid.T_Timetz)` for now?

**Review by otan — COMMENTED** [review]
so many removed TODOs! took a glance, will deep look again next week (if knz doesnt approve ya first)

**Review by knz — COMMENTED** [review]
This is quite a lot of progress, thank you.

The main concern I still have with this approach is the removal of the intermediate interfaces. I think they are useful and I think we don't want a hard pgx dependency everywhere someone needs to send a query through a connection. If we can't use `driver.Querier` any more we need to define a new interface.

> Reviewed 44 of 44 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/81943#-:-N3A510LBxYhHz-ySG79:b-ok8576)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rafiss)

___
*[`pkg/cli/clierrorplus/decorate_error.go` line 110 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/81943#-N3A273sAZ_N3_rDjifu:-N3A273t20CnSwQVxwOS:bmrgjq3) ([raw file](https://github.com/cockroachdb/cockroach/blob/d98b5c59b57b04e2c405f0554a648cf3fb7276d2/pkg/cli/clierrorplus/decorate_error.go#L110)):*
> ```Go
> 
> 		// Is this an "unable to connect" type of error?
> 		// TODO(rafi): patch jackc/pgconn to add an ErrSSLNotSupported constant.
> ```

is there an upstream issue filed that we can track?
___
*[`pkg/cli/clisqlclient/api.go` line 92 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/81943#-N3A2D0zCD-u0TI7WGXl:-N3A2D0zCD-u0TI7WGXm:b-owdwjp) ([raw file](https://github.com/cockroachdb/cockroach/blob/d98b5c59b57b04e2c405f0554a648cf3fb7276d2/pkg/cli/clisqlclient/api.go#L92)):*
> ```Go
> 	// GetPGXConn exposes the underlying PGX driver connection object
> 	// for use by the cli package.
> 	GetPGXConn() *pgx.Conn
> ```

I'll reproduce my comment here from the other PR: this would benefit from an interface instead of exposing the raw type directly.  
Also if that interface is defined in a separate standalone package, it will ensure that all the places where the itnerface is used won't have a direct dependency on pgx, which will decouple the build further.
___
*[`pkg/cli/clisqlclient/conn.go` line 246 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/81943#-N3A2dlwCAQW_jh2or-d:-N3A2dlwCAQW_jh2or-e:bcmju42) ([raw file](https://github.com/cockroachdb/cockroach/blob/d98b5c59b57b04e2c405f0554a648cf3fb7276d2/pkg/cli/clisqlclient/conn.go#L246)):*
> ```Go
> 	rows, err := c.Query(ctx, "SELECT * FROM crdb_internal.node_build_info")
> 	if c.conn.IsClosed() {
> 		return 0, "", "", errors.CombineErrors(ErrConnectionClosed, err)
> ```

We want to expose `err` as the primary error (and its error text). See my comment on the other PR about combining `errors.CombineErrors` and `errors.Mark`.
___
*[`pkg/cli/clisqlclient/conn.go` line 352 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/81943#-N3A2kGU40EHIbzT9b91:-N3A2kGU40EHIbzT9b92:b-7ropln) ([raw file](https://github.com/cockroachdb/cockroach/blob/d98b5c59b57b04e2c405f0554a648cf3fb7276d2/pkg/cli/clisqlclient/conn.go#L352)):*
> ```Go
> 	_, newServerVersion, newClusterID, err := c.GetServerMetadata(ctx)
> 	if c.conn.IsClosed() {
> 		return errors.CombineErrors(ErrConnectionClosed, err)
> ```

ditto
___
*[`pkg/cli/clisqlclient/conn.go` line 519 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/81943#-N3A2lOzD6wd6-saRrdM:-N3A2lOzD6wd6-saRrdN:b-7ropln) ([raw file](https://github.com/cockroachdb/cockroach/blob/d98b5c59b57b04e2c405f0554a648cf3fb7276d2/pkg/cli/clisqlclient/conn.go#L519)):*
> ```Go
> 		c.reconnecting = true
> 		c.silentClose()
> 		return errors.CombineErrors(ErrConnectionClosed, err)
> ```

ditto
___
*[`pkg/cli/clisqlclient/conn.go` line 539 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/81943#-N3A2meEAJza-_dQVOd2:-N3A2meEAJza-_dQVOd3:b-7ropln) ([raw file](https://github.com/cockroachdb/cockroach/blob/d98b5c59b57b04e2c405f0554a648cf3fb7276d2/pkg/cli/clisqlclient/conn.go#L539)):*
> ```Go
> 			c.reconnecting = true
> 			c.silentClose()
> 			return nil, errors.CombineErrors(ErrConnectionClosed, err)
> ```

ditto
___
*[`pkg/cli/clisqlclient/conn.go` line 553 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/81943#-N3A2ov17Re6_fS7yd5L:-N3A2ov17Re6_fS7yd5M:b-7ropln) ([raw file](https://github.com/cockroachdb/cockroach/blob/d98b5c59b57b04e2c405f0554a648cf3fb7276d2/pkg/cli/clisqlclient/conn.go#L553)):*
> ```Go
> 		c.reconnecting = true
> 		c.silentClose()
> 		return nil, errors.CombineErrors(ErrConnectionClosed, multiResultReader.Close())
> ```

ditto
___
*[`pkg/cli/clisqlclient/rows.go` line 26 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/81943#-N3A2wVV-HcHiniUjXf1:-N3A2wVW37UscEXje4k4:b-f2wj9m) ([raw file](https://github.com/cockroachdb/cockroach/blob/d98b5c59b57b04e2c405f0554a648cf3fb7276d2/pkg/cli/clisqlclient/rows.go#L26)):*
> ```Go
> type sqlRows struct {
> 	rows     pgx.Rows
> 	connInfo *pgtype.ConnInfo
> ```

These two would benefit from interfaces instead of exposing the pgx types directly, to decouple the build.
___
*[`pkg/cli/clisqlclient/rows.go` line 32 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/81943#-N3A32TcDVLal5qZh897:-N3A32TcDVLal5qZh898:bpjp44t) ([raw file](https://github.com/cockroachdb/cockroach/blob/d98b5c59b57b04e2c405f0554a648cf3fb7276d2/pkg/cli/clisqlclient/rows.go#L32)):*
> ```Go
> var _ Rows = (*sqlRows)(nil)
> 
> func (r *sqlRows) Columns() []string {
> ```

See my comment on the other PR - this needs a comment to explain the method is expensive,
and an audit of all callers to ensure its result is cached.
___
*[`pkg/cli/clisqlclient/rows.go` line 88 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/81943#-N3A3Fgr-Bjz5_c-mBho:-N3A3Fgr-Bjz5_c-mBhp:bgcc6cg) ([raw file](https://github.com/cockroachdb/cockroach/blob/d98b5c59b57b04e2c405f0554a648cf3fb7276d2/pkg/cli/clisqlclient/rows.go#L88)):*
> ```Go
> 
> func (r *sqlRows) ColumnTypeScanType(index int) reflect.Type {
> 	o := r.rows.FieldDescriptions()[index].DataTypeOID
> ```

See my comment in the other PR - this implementation should be extracted in helper functions.
___
*[`pkg/cli/clisqlclient/rows.go` line 112 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/81943#-N3A3JCX9jAJz-Orii06:-N3A3JCX9jAJz-Orii07:b-7ropln) ([raw file](https://github.com/cockroachdb/cockroach/blob/d98b5c59b57b04e2c405f0554a648cf3fb7276d2/pkg/cli/clisqlclient/rows.go#L112)):*
> ```Go
> 
> func (r *sqlRows) ColumnTypeDatabaseTypeName(index int) string {
> 	fieldOID := r.rows.FieldDescriptions()[index].DataTypeOID
> ```

ditto
___
*[`pkg/cli/clisqlclient/rows_multi.go` line 36 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/81943#-N3A3LgQ-2GJIjT-AHfZ:-N3A3LgQ-2GJIjT-AHf_:b-b5purw) ([raw file](https://github.com/cockroachdb/cockroach/blob/d98b5c59b57b04e2c405f0554a648cf3fb7276d2/pkg/cli/clisqlclient/rows_multi.go#L36)):*
> ```Go
> 
> func (r *sqlRowsMultiResultSet) Columns() []string {
> 	rr := r.rows.ResultReader()
> ```

see previous comment about caching
___
*[`pkg/cli/clisqlclient/rows_multi.go` line 96 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/81943#-N3A3VOH7NCies-NtSxa:-N3A3VOH7NCies-NtSxb:b-emfdzb) ([raw file](https://github.com/cockroachdb/cockroach/blob/d98b5c59b57b04e2c405f0554a648cf3fb7276d2/pkg/cli/clisqlclient/rows_multi.go#L96)):*
> ```Go
> 	}
> 	for i := range values {
> 		rowVal := rd.Values()[i]
> ```

this loop body is too complex, deserves to be moved into helper function(s).
___
*[`pkg/cli/clisqlclient/rows_multi.go` line 103 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/81943#-N35sMLZBL7yNV0SDzgP:-N3A3be4E3vzysSDGXHA:bgp3hqe) ([raw file](https://github.com/cockroachdb/cockroach/blob/d98b5c59b57b04e2c405f0554a648cf3fb7276d2/pkg/cli/clisqlclient/rows_multi.go#L103)):*
> it also means that we could get rid of all formatting logic in the CLI. i am pretty sure that the reason we didn't do it this way before is because lib/pq didn't allow us to. do you know?

Yes you are right.

> what do you think?

I think it's a great idea, but at the same time we need to be sure that automation that consumes the output via the table formatters (tsv, csv, etc...) does not get confused.
So I think the proper course of action here is to:
- determine a precise list of things that would change formatting if we do what you say
- decide which are innocuous (or better, improvements) and focus on those that break
- add a "compatibility" flag and for the breaking changes add an opt-in to re-format them in the old way.
___
*[`pkg/cli/clisqlclient/rows_multi.go` line 167 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/81943#-N3A4A-s50DzLXWySK1w:-N3A4A-s50DzLXWySK1x:b-3z2hm9) ([raw file](https://github.com/cockroachdb/cockroach/blob/d98b5c59b57b04e2c405f0554a648cf3fb7276d2/pkg/cli/clisqlclient/rows_multi.go#L167)):*
> ```Go
> 
> func (r *sqlRowsMultiResultSet) ColumnTypeScanType(index int) reflect.Type {
> 	rd := r.rows.ResultReader()
> ```

ditto helper function
___
*[`pkg/cli/clisqlclient/rows_multi.go` line 192 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/81943#-N3A4BP-9Y7wy3KsOtxS:-N3A4BP-9Y7wy3KsOtxT:b-7ropln) ([raw file](https://github.com/cockroachdb/cockroach/blob/d98b5c59b57b04e2c405f0554a648cf3fb7276d2/pkg/cli/clisqlclient/rows_multi.go#L192)):*
> ```Go
> 
> func (r *sqlRowsMultiResultSet) ColumnTypeDatabaseTypeName(index int) string {
> 	rd := r.rows.ResultReader()
> ```

ditto
___
*[`pkg/cli/flags_test.go` line 975 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/81943#-N3A4qFWCbXmyLpo_DAA:-N3A4qFWCbXmyLpo_DAB:b-85bp) ([raw file](https://github.com/cockroachdb/cockroach/blob/d98b5c59b57b04e2c405f0554a648cf3fb7276d2/pkg/cli/flags_test.go#L975)):*
> ```Go
> 		expectedAddr string
> 	}{
> 		{[]string{"quit"}, "localhost:" + base.DefaultPort},
> ```

Why did this change?
___
*[`pkg/cli/clisqlexec/format_table_test.go` line 67 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/81943#-N3A4vvh5faAaSm_I5Yy:-N3A4vvh5faAaSm_I5Yz:bcdzgjf) ([raw file](https://github.com/cockroachdb/cockroach/blob/d98b5c59b57b04e2c405f0554a648cf3fb7276d2/pkg/cli/clisqlexec/format_table_test.go#L67)):*
> ```Go
> 	// CREATE TABLE
> 	// sql -e insert into t.u values (0, 0, 0, 0, 0, 0, 0, 0)
> 	// INSERT 0 1
> ```

Can you explain what's up here?

**Review by rafiss — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/81943)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @knz, @otan, and @rafiss)

___
*[`pkg/cli/clisqlclient/api.go` line 92 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/81943#-N3A2D0zCD-u0TI7WGXl:-N3BESDt4Nf5F1S3zTT5:bllsl2a) ([raw file](https://github.com/cockroachdb/cockroach/blob/d98b5c59b57b04e2c405f0554a648cf3fb7276d2/pkg/cli/clisqlclient/api.go#L92)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

I'll reproduce my comment here from the other PR: this would benefit from an interface instead of exposing the raw type directly.  
Also if that interface is defined in a separate standalone package, it will ensure that all the places where the itnerface is used won't have a direct dependency on pgx, which will decouple the build further.
</blockquote></details>

i will work on this
___
*[`pkg/cli/clisqlclient/conn.go` line 246 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/81943#-N3A2dlwCAQW_jh2or-d:-N3BEUYi7VGfMx4JE0_I:bllsl2a) ([raw file](https://github.com/cockroachdb/cockroach/blob/d98b5c59b57b04e2c405f0554a648cf3fb7276d2/pkg/cli/clisqlclient/conn.go#L246)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

We want to expose `err` as the primary error (and its error text). See my comment on the other PR about combining `errors.CombineErrors` and `errors.Mark`.
</blockquote></details>

i will work on this
___
*[`pkg/cli/clisqlclient/rows.go` line 32 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/81943#-N3A32TcDVLal5qZh897:-N3BAZC65I0bUFDU3Fig:brkyfr) ([raw file](https://github.com/cockroachdb/cockroach/blob/d98b5c59b57b04e2c405f0554a648cf3fb7276d2/pkg/cli/clisqlclient/rows.go#L32)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

See my comment on the other PR - this needs a comment to explain the method is expensive,
and an audit of all callers to ensure its result is cached.
</blockquote></details>

Instead, I've updated the implementation to cache the result.
___
*[`pkg/cli/clisqlclient/rows.go` line 88 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/81943#-N3A3Fgr-Bjz5_c-mBho:-N3B7brn4Jlz54fhm9gQ:b-53l2bv) ([raw file](https://github.com/cockroachdb/cockroach/blob/d98b5c59b57b04e2c405f0554a648cf3fb7276d2/pkg/cli/clisqlclient/rows.go#L88)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

See my comment in the other PR - this implementation should be extracted in helper functions.
</blockquote></details>

oops, i meant to squash that here. it is in the `cli: make ColumnTypeScanType consistent` commit of the larger PR.

fixed
___
*[`pkg/cli/clisqlclient/rows.go` line 102 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/81943#-N312iAl0pqQmcvOREQK-r1-102:-N3BDNxe0-UOLX4VrZb_:b-7wv190) ([raw file](https://github.com/cockroachdb/cockroach/blob/d98b5c59b57b04e2c405f0554a648cf3fb7276d2/pkg/cli/clisqlclient/rows.go#L102)):*
<details><summary><i>Previously, otan (Oliver Tan) wrote…</i></summary><blockquote>

i wonder whether time.Time is the appropriate thing to use for Time/TimeTZ. 24:00:00 time springs to mind as a point of confusion. that said, if we do that today then so be it.

can we use `pgtype.OID(oid.T_Timetz)` for now?
</blockquote></details>

hm, well then we have to keep pulling in the lib/pq dependency here
___
*[`pkg/cli/clisqlclient/rows.go` line 112 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/81943#-N3A3JCX9jAJz-Orii06:-N3BBpVO3s6G2vFW1jFI:b-7ql1td) ([raw file](https://github.com/cockroachdb/cockroach/blob/d98b5c59b57b04e2c405f0554a648cf3fb7276d2/pkg/cli/clisqlclient/rows.go#L112)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

fixed
___
*[`pkg/cli/clisqlclient/rows_multi.go` line 36 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/81943#-N3A3LgQ-2GJIjT-AHfZ:-N3BDXXz6c9gAhyd67ye:b-7ql1td) ([raw file](https://github.com/cockroachdb/cockroach/blob/d98b5c59b57b04e2c405f0554a648cf3fb7276d2/pkg/cli/clisqlclient/rows_multi.go#L36)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

see previous comment about caching
</blockquote></details>

fixed
___
*[`pkg/cli/clisqlclient/rows_multi.go` line 96 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/81943#-N3A3VOH7NCies-NtSxa:-N3B7TG93q4y8rTg5gFN:by6yzvk) ([raw file](https://github.com/cockroachdb/cockroach/blob/d98b5c59b57b04e2c405f0554a648cf3fb7276d2/pkg/cli/clisqlclient/rows_multi.go#L96)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

this loop body is too complex, deserves to be moved into helper function(s).
</blockquote></details>

this would not be complex if we scan everything into strings (i.e. if we do the idea of the comment thread below)
___
*[`pkg/cli/clisqlclient/rows_multi.go` line 103 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/81943#-N35sMLZBL7yNV0SDzgP:-N3612Y65NgS2AL2AbRC:b-xnvy6v) ([raw file](https://github.com/cockroachdb/cockroach/blob/d98b5c59b57b04e2c405f0554a648cf3fb7276d2/pkg/cli/clisqlclient/rows_multi.go#L103)):*
> determine a precise list of things that would change formatting if we do what you say

after https://github.com/cockroachdb/cockroach/pull/82022 is merged, the only change will be that the formatting of booleans changes from `true/false` to `t/f`.

it seems innocuous to me, so IMO it would be fine to skip adding a compatibility flag.
___
*[`pkg/cli/clisqlclient/rows_multi.go` line 167 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/81943#-N3A4A-s50DzLXWySK1w:-N3BDbZaB6jRYMtcWxPp:b-7ql1td) ([raw file](https://github.com/cockroachdb/cockroach/blob/d98b5c59b57b04e2c405f0554a648cf3fb7276d2/pkg/cli/clisqlclient/rows_multi.go#L167)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

ditto helper function
</blockquote></details>

fixed
___
*[`pkg/cli/clisqlclient/rows_multi.go` line 192 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/81943#-N3A4BP-9Y7wy3KsOtxS:-N3BDcLP0VWJo27k2Gyp:b-7ql1td) ([raw file](https://github.com/cockroachdb/cockroach/blob/d98b5c59b57b04e2c405f0554a648cf3fb7276d2/pkg/cli/clisqlclient/rows_multi.go#L192)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

fixed
___
*[`pkg/cli/flags_test.go` line 975 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/81943#-N3A4qFWCbXmyLpo_DAA:-N3BDuDOAxxmkDAKqwLL:b-juv5cb) ([raw file](https://github.com/cockroachdb/cockroach/blob/d98b5c59b57b04e2c405f0554a648cf3fb7276d2/pkg/cli/flags_test.go#L975)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

Why did this change?
</blockquote></details>

due to the change in https://reviewable.io/reviews/cockroachdb/cockroach/81007#-N2wThGg2rvFy3W1ItP7

the "localhost" default is now part of our CLI (whereas before we used to rely on lib/pq to default to "localhost")
___
*[`pkg/cli/clisqlexec/format_table_test.go` line 67 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/81943#-N3A4vvh5faAaSm_I5Yy:-N3BE4x87sSQK7FB-EO1:bk90wmp) ([raw file](https://github.com/cockroachdb/cockroach/blob/d98b5c59b57b04e2c405f0554a648cf3fb7276d2/pkg/cli/clisqlexec/format_table_test.go#L67)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

Can you explain what's up here?
</blockquote></details>

this is the statement tag that both CockroachDB and PostgreSQL returns for INSERT statements.

for example, if you use psql to connect to either PG or CRDB that's what you'd see.

it is explained here: https://www.postgresql.org/message-id/4AD5F063.8050708@iol.ie

**Review by knz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/81943)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @knz, @otan, and @rafiss)

___
*[`pkg/cli/clisqlclient/rows_multi.go` line 103 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/81943#-N35sMLZBL7yNV0SDzgP:-N3BFSUvAa4eFvxHkz68:bscvm1x) ([raw file](https://github.com/cockroachdb/cockroach/blob/d98b5c59b57b04e2c405f0554a648cf3fb7276d2/pkg/cli/clisqlclient/rows_multi.go#L103)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

> determine a precise list of things that would change formatting if we do what you say

after https://github.com/cockroachdb/cockroach/pull/82022 is merged, the only change will be that the formatting of booleans changes from `true/false` to `t/f`.

it seems innocuous to me, so IMO it would be fine to skip adding a compatibility flag.
</blockquote></details>

for the ascii art table formatter, which is meant to be consumed by humans, I agree it is innocuous.

However I am not so sure about the csv/tsv/html formatters.

**Review by rafiss — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/81943)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @knz, @otan, and @rafiss)

___
*[`pkg/cli/clisqlclient/rows_multi.go` line 103 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/81943#-N35sMLZBL7yNV0SDzgP:-N3BFs_3-Or0X6wKYoWi:bbmdzlk) ([raw file](https://github.com/cockroachdb/cockroach/blob/d98b5c59b57b04e2c405f0554a648cf3fb7276d2/pkg/cli/clisqlclient/rows_multi.go#L103)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

for the ascii art table formatter, which is meant to be consumed by humans, I agree it is innocuous.

However I am not so sure about the csv/tsv/html formatters. 
</blockquote></details>

in that case, perhaps we can add special logic for bools. it would be much simpler than the existing formatting logic. i will investigate further.

**Review by rafiss — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/81943)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @knz, @otan, and @rafiss)

___
*[`pkg/cli/clierrorplus/decorate_error.go` line 110 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/81943#-N3A273sAZ_N3_rDjifu:-N3BH6YA5hHb63N7gers:b-si3fgp) ([raw file](https://github.com/cockroachdb/cockroach/blob/d98b5c59b57b04e2c405f0554a648cf3fb7276d2/pkg/cli/clierrorplus/decorate_error.go#L110)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

is there an upstream issue filed that we can track?
</blockquote></details>

filed https://github.com/jackc/pgconn/issues/118

**Review by knz — COMMENTED** [review]
I think you haven't pushed your latest change yet.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/81943#-:-N3BKuCC1o4zrMEdcinR:bg0tti3)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @knz, @otan, and @rafiss)

___
*[`pkg/cli/flags_test.go` line 975 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/81943#-N3A4qFWCbXmyLpo_DAA:-N3BKVAU-81_WsBuVnD1:b3bbsyw) ([raw file](https://github.com/cockroachdb/cockroach/blob/d98b5c59b57b04e2c405f0554a648cf3fb7276d2/pkg/cli/flags_test.go#L975)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

due to the change in https://reviewable.io/reviews/cockroachdb/cockroach/81007#-N2wThGg2rvFy3W1ItP7

the "localhost" default is now part of our CLI (whereas before we used to rely on lib/pq to default to "localhost")
</blockquote></details>

Ok but then let's be mindful of the PR ordering. In this PR (81943) you do not need to update cliCtx.clientConnHost yet in context.go, I think? Then if you revert context.go, flags_test.go does not need to change here yet. You can make that combined change in the followup commit in PR 81007.
___
*[`pkg/cli/clisqlexec/format_table_test.go` line 67 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/81943#-N3A4vvh5faAaSm_I5Yy:-N3BKpPI7GWsGlETgYf7:b-bxk31w) ([raw file](https://github.com/cockroachdb/cockroach/blob/d98b5c59b57b04e2c405f0554a648cf3fb7276d2/pkg/cli/clisqlexec/format_table_test.go#L67)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

this is the statement tag that both CockroachDB and PostgreSQL returns for INSERT statements.

for example, if you use psql to connect to either PG or CRDB that's what you'd see.

it is explained here: https://www.postgresql.org/message-id/4AD5F063.8050708@iol.ie
</blockquote></details>

OK thanks. This change needs to be documented in a release note.

**Comment by rafiss** [comment]
> I think you haven't pushed your latest change yet.

i hadn't since i haven't had time to do the errors.Mark or the sqlConn interface changes that you suggested. but if you find it useful to iterate anyway, i've pushed them now.

**Review by rafiss — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/81943)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @knz, @otan, and @rafiss)

___
*[`pkg/cli/flags_test.go` line 975 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/81943#-N3A4qFWCbXmyLpo_DAA:-N3Bit5l79MEswEaLf9y:b-50mr4n) ([raw file](https://github.com/cockroachdb/cockroach/blob/d98b5c59b57b04e2c405f0554a648cf3fb7276d2/pkg/cli/flags_test.go#L975)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

Ok but then let's be mindful of the PR ordering. In this PR (81943) you do not need to update cliCtx.clientConnHost yet in context.go, I think? Then if you revert context.go, flags_test.go does not need to change here yet. You can make that combined change in the followup commit in PR 81007.
</blockquote></details>

i do still need to update it in this PR, since it includes this diff

```
diff --git a/pkg/cli/context.go b/pkg/cli/context.go
index 1ed138c687..7c1152932b 100644
--- a/pkg/cli/context.go
+++ b/pkg/cli/context.go
@@ -220,7 +220,7 @@ func setCliContextDefaults() {
     cliCtx.IsInteractive = false
     cliCtx.EmbeddedMode = false
     cliCtx.cmdTimeout = 0 // no timeout
-    cliCtx.clientConnHost = ""
+    cliCtx.clientConnHost = "localhost"
     cliCtx.clientConnPort = base.DefaultPort
     cliCtx.certPrincipalMap = nil
     cliCtx.sqlConnURL = nil
```

**Review by rafiss — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/81943)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @knz, @otan, and @rafiss)

___
*[`pkg/cli/clisqlclient/conn.go` line 246 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/81943#-N3A2dlwCAQW_jh2or-d:-N3DQcSpEbWiXwpMd0NJ:bb7f2mf) ([raw file](https://github.com/cockroachdb/cockroach/blob/d98b5c59b57b04e2c405f0554a648cf3fb7276d2/pkg/cli/clisqlclient/conn.go#L246)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

i will work on this
</blockquote></details>

done
___
*[`pkg/cli/clisqlclient/conn.go` line 352 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/81943#-N3A2kGU40EHIbzT9b91:-N3DQe3hCyXS_7vJXO_1:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/d98b5c59b57b04e2c405f0554a648cf3fb7276d2/pkg/cli/clisqlclient/conn.go#L352)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.
___
*[`pkg/cli/clisqlclient/conn.go` line 519 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/81943#-N3A2lOzD6wd6-saRrdM:-N3DQeiz-QSfrcUq1WRA:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/d98b5c59b57b04e2c405f0554a648cf3fb7276d2/pkg/cli/clisqlclient/conn.go#L519)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.
___
*[`pkg/cli/clisqlclient/conn.go` line 539 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/81943#-N3A2meEAJza-_dQVOd2:-N3DQfYeEO9whIwXwAeu:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/d98b5c59b57b04e2c405f0554a648cf3fb7276d2/pkg/cli/clisqlclient/conn.go#L539)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.
___
*[`pkg/cli/clisqlclient/conn.go` line 553 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/81943#-N3A2ov17Re6_fS7yd5L:-N3DQfw95_lBhQyBEiob:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/d98b5c59b57b04e2c405f0554a648cf3fb7276d2/pkg/cli/clisqlclient/conn.go#L553)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.
___
*[`pkg/cli/clisqlexec/format_table_test.go` line 67 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/81943#-N3A4vvh5faAaSm_I5Yy:-N3DROBz5c7Ykv8JwPee:bb7f2mf) ([raw file](https://github.com/cockroachdb/cockroach/blob/d98b5c59b57b04e2c405f0554a648cf3fb7276d2/pkg/cli/clisqlexec/format_table_test.go#L67)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

OK thanks. This change needs to be documented in a release note.
</blockquote></details>

done

File: pkg/cli/clisqlclient/conn.go (hunk 2 above)
Comment (rafiss) [reply pkg/cli/clisqlclient/conn.go:249]: this condition is just meant to detect when the connection to the server was lost. e.g. because the server was shut down, or the computer lost its network connection.

**Review by rafiss — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/81943)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @knz, @otan, and @rafiss)

___
*[`pkg/cli/clisqlclient/rows.go` line 26 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/81943#-N3A2wVV-HcHiniUjXf1:-N3FvnBG38zbICmgk1CA:b-alex9c) ([raw file](https://github.com/cockroachdb/cockroach/blob/d98b5c59b57b04e2c405f0554a648cf3fb7276d2/pkg/cli/clisqlclient/rows.go#L26)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

These two would benefit from interfaces instead of exposing the pgx types directly, to decouple the build.
</blockquote></details>

i'm less convinced of this suggestion.

prior to my PR, this package was already depending on lib/pq.

even if we refactored these fields, this package would still need to depend on pgx because it contains the `sqlConn` struct, which requires `*pgx.Conn`

and i think changing that has diminishing returns. it would be quite complicated, and IMO not provide much benefit, since we don't change the pgx dependency frequently (so not much of a benefit to build times)

**Review by rafiss — COMMENTED** [review]
this is now ready for another look. the failing tests  should be resolved with the changes in https://github.com/cockroachdb/cockroach/pull/81007

do you think it's time to create a new PR that has all the changes together? (or whatever else you'd like to be able to review this easily?)

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/81943#-:-N3FwpDsADCUD15EZKB3:bjb8h3a)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @knz, @otan, and @rafiss)

File: pkg/cli/clisqlclient/api.go [hunk 4]
```diff
@@ -85,18 +91,22 @@ type Conn interface {
 	// The sql argument is the SQL query to use to retrieve the value.
 	GetServerValue(ctx context.Context, what, sql string) (driver.Value, string, bool)
 
-	// GetDriverConn exposes the underlying SQL driver connection object
+	// GetDriverConn exposes the underlying pgx driver connection object
```
Comment (otan) [inline pkg/cli/clisqlclient/api.go:94]: should the comment mention pgx driver still?

File: pkg/cli/auth.go [hunk 5]
```diff
@@ -93,6 +93,7 @@ func createAuthSessionToken(
 	username string,
 ) (sessionID int64, httpCookie *http.Cookie, resErr error) {
 	sqlConn, err := makeSQLClient("cockroach auth-session login", useSystemDb)
+
```
Comment (otan) [inline pkg/cli/auth.go:96]: nit: extra \n

File: pkg/cli/clierrorplus/decorate_error.go [hunk 6]
```diff
@@ -107,7 +107,9 @@ func MaybeDecorateError(
 		}
 
 		// Is this an "unable to connect" type of error?
-		if errors.Is(err, pq.ErrSSLNotSupported) {
+		// TODO(rafi): patch jackc/pgconn to add an ErrSSLNotSupported constant.
+		// See https://github.com/jackc/pgconn/issues/118.
+		if strings.Contains(err.Error(), "server refused TLS connection") {
```
Comment (otan) [inline pkg/cli/clierrorplus/decorate_error.go:112]: wonder if you can use `go:linkname` to reference it 😂

**Review by otan — COMMENTED** [review]
LGTM but letting knz sign off + some remaining tests to look at

**Review by knz — COMMENTED** [review]
This looks great! 

Regarding the failing tests, are you sure there's nothing to do in this PR?

For one, there's a lint failure `TestForbiddenImportsSQLShell`. I think this is because of the new import of `errorutil`. Probably the new function should be placed into a separate standalone package. (Maybe `clierror`?)

There's also a couple of test files that don't compile any more. I think this should be addressed here as well.


Also regarding the zip tests:
```
ERROR: prepared statement had 2 statements, expected 1
```
Is that because the other PR also splits the timeout change into a separate statement? 

I don't mind delaying looking at the demo failures until the other PR.

> Reviewed 3 of 6 files at r2, 21 of 21 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/81943#-:-N3KAubQ669cpUhVka_f:bo5y5u6)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @otan and @rafiss)

___
*[`pkg/cli/sql_shell_cmd.go` line 61 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/81943#-N3KAAQeEVJeWVJEALBA:-N3KAAQeEVJeWVJEALBB:b-sxzdob) ([raw file](https://github.com/cockroachdb/cockroach/blob/75a378610fc755cea1d29c4aa62ae8d73bf014d9/pkg/cli/sql_shell_cmd.go#L61)):*
> ```Go
> 		return err
> 	}
> 	conn.SetAlwaysInferResultTypes(false)
> ```

Are you sure about whether this is the right place for this? It feels like this belongs to clisqlcfg.

If you're sure this is the right place, then please also add this to pkg/cmd/cockroach-sql/main.go too thanks.
___
*[`pkg/cli/clisqlcfg/context.go` line 183 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/81943#-N3KAU814AiDGqu8qnV1:-N3KAU814AiDGqu8qnV2:b-13hdko) ([raw file](https://github.com/cockroachdb/cockroach/blob/75a378610fc755cea1d29c4aa62ae8d73bf014d9/pkg/cli/clisqlcfg/context.go#L183)):*
> ```Go
> 	conn := c.ConnCtx.MakeSQLConn(c.CmdOut, c.CmdErr, url)
> 	conn.SetMissingPassword(!usePw || !pwdSet)
> 	conn.SetAlwaysInferResultTypes(true)
> ```

Are you sure about this one? `clisqlcfg` is specfically dedicated to prepare a SQL shell. Then in `sql_shell_cmd` you set this to false. Maybe it should be false here right away?

(with an explanatory comment)

**Review by rafiss — COMMENTED** [review]
i am pretty sure everything will be resolved by adding in the commits from the other PR. I will confirm this, and if so, I'll open a new separate PR with everything combined. (and also do the `clierror` change)

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/81943#-:-N3M9bbt6Pz7Z9AidBcu:b-u89m56)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @otan and @rafiss)

**Review by rafiss — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/81943)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @knz, @otan, and @rafiss)

___
*[`pkg/cli/auth.go` line 96 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/81943#-N3DQbKItNzrbYT6IcO4-r3-96:-N3MyFTg3BW3JmmAj-bZ:b-7ql1td) ([raw file](https://github.com/cockroachdb/cockroach/blob/75a378610fc755cea1d29c4aa62ae8d73bf014d9/pkg/cli/auth.go#L96)):*
<details><summary><i>Previously, otan (Oliver Tan) wrote…</i></summary><blockquote>

nit: extra \n
</blockquote></details>

fixed
___
*[`pkg/cli/sql_shell_cmd.go` line 61 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/81943#-N3KAAQeEVJeWVJEALBA:-N3Mwajn9Q7ZZXvkFCOW:b-gnmmt9) ([raw file](https://github.com/cockroachdb/cockroach/blob/75a378610fc755cea1d29c4aa62ae8d73bf014d9/pkg/cli/sql_shell_cmd.go#L61)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

Are you sure about whether this is the right place for this? It feels like this belongs to clisqlcfg.

If you're sure this is the right place, then please also add this to pkg/cmd/cockroach-sql/main.go too thanks.
</blockquote></details>

i think it's correct (see below comment). good point on cockroach-sql. i'll also need it for demo.
___
*[`pkg/cli/clierrorplus/decorate_error.go` line 112 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/81943#-N312iAl0pqQmcvOREQC-r3-112:-N3MwMto19MHLbdHTyQz:byynmis) ([raw file](https://github.com/cockroachdb/cockroach/blob/75a378610fc755cea1d29c4aa62ae8d73bf014d9/pkg/cli/clierrorplus/decorate_error.go#L112)):*
<details><summary><i>Previously, otan (Oliver Tan) wrote…</i></summary><blockquote>

wonder if you can use `go:linkname` to reference it 😂 
</blockquote></details>

unfortunately no, since it's returned as `errors.New(...)` :( 
___
*[`pkg/cli/clisqlcfg/context.go` line 183 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/81943#-N3KAU814AiDGqu8qnV1:-N3MwFYj79JX58OQXKNK:b-n1rd9t) ([raw file](https://github.com/cockroachdb/cockroach/blob/75a378610fc755cea1d29c4aa62ae8d73bf014d9/pkg/cli/clisqlcfg/context.go#L183)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

Are you sure about this one? `clisqlcfg` is specfically dedicated to prepare a SQL shell. Then in `sql_shell_cmd` you set this to false. Maybe it should be false here right away?

(with an explanatory comment)
</blockquote></details>

hm, maybe this function got misused over time then. this is called by makeSQLClient, which is used by essentially everything else (e.g. `runDebugZip`)
___
*[`pkg/cli/clisqlclient/api.go` line 94 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/81943#-N312iAl0pqQmcvOREQF-r3-94:-N3My3Nv3yOYcbaFcvsM:b-6wez3q) ([raw file](https://github.com/cockroachdb/cockroach/blob/75a378610fc755cea1d29c4aa62ae8d73bf014d9/pkg/cli/clisqlclient/api.go#L94)):*
<details><summary><i>Previously, otan (Oliver Tan) wrote…</i></summary><blockquote>

should the comment mention pgx driver still?
</blockquote></details>

eh, i think so, but fine either way

**Comment by knz** [comment]
> i am pretty sure everything will be resolved by adding in the commits from the other PR. I will confirm this, and if so, I'll open a new separate PR with everything combined.

that's possible yes, but I think there's also something better that will also create more confidence during the review.

My reasoning is as follows: in this PR, it's pleasantly surprising _how few_ CI failures remain.
So it's possible there's only very few changes from the other PRs needed here to make CI happy.
What about we try this first? Bring in the strict minimum commits from the other PRs that make this one pass tests.

Should you be able to achieve this, the next PR then becomes "improvements upon the status quo enabled by pgx", which can be split into stages with separate reviews.

What do you think?

**Review by knz — APPROVED** [review]
LGTM with nits.

I see you've chosen to let the bool t/f representation go through in this PR.
I'll let you keep that choice, but then please change the release note type from "cli change" to "backward-incompatible change".

> Reviewed 34 of 35 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/81943#-:-N3UIUw4996ENYAPaeds:b-bex2zw)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @otan and @rafiss)

___
*[`pkg/cli/context.go` line 216 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/81943#-N3UH6KAB_vqPLY_0mC9:-N3UH6KAB_vqPLY_0mCA:b-6hmatc) ([raw file](https://github.com/cockroachdb/cockroach/blob/8852d678fc6e5664469a7a508cb78f20a12034db/pkg/cli/context.go#L216)):*
> ```Go
> 	cliCtx.cmdTimeout = 0 // no timeout
> 	cliCtx.clientOpts.ServerHost = "localhost"
> 	if h := os.Getenv("PGHOST"); h != "" {
> ```

what about this alternative:
(pseudo-code)
"if env var PGHOST is not defined, then set it to localhost"

then let the go code as-is.

This will ensure that the output of `cockroach sql --help` does not change depending on the value of $PGHOST
___
*[`pkg/testutils/lint/lint_test.go` line 448 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/81943#-N3UIGz82-b6AzFU9q0N:-N3UIGz82-b6AzFU9q0O:b2ru2a9) ([raw file](https://github.com/cockroachdb/cockroach/blob/8852d678fc6e5664469a7a508cb78f20a12034db/pkg/testutils/lint/lint_test.go#L448)):*
> ```Go
> 					":!util/grpcutil",  // GRPC_GO_* variables
> 					":!roachprod",      // roachprod requires AWS environment variables
> 					":!cli/context.go", // The CLI needs the PGHOST variable.
> ```

if you decide to keep the env var logic, please move it to a different file. There's a lot going on in context.go and we'd like to avoid env var stuff creeping in elsewhere.

**Review by rafiss — COMMENTED** [review]
updated the release note for booleans, and fixed the env var checking

i'll merge this after confirming CI is still good

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/81943#-:-N3VPFbHCDSyf1NKCLBo:bxl2own)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @knz, @otan, and @rafiss)

___
*[`pkg/cli/context.go` line 216 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/81943#-N3UH6KAB_vqPLY_0mC9:-N3VMIFM4ApMcAOQD2-O:b7arimt) ([raw file](https://github.com/cockroachdb/cockroach/blob/8852d678fc6e5664469a7a508cb78f20a12034db/pkg/cli/context.go#L216)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

what about this alternative:
(pseudo-code)
"if env var PGHOST is not defined, then set it to localhost"

then let the go code as-is.

This will ensure that the output of `cockroach sql --help` does not change depending on the value of $PGHOST
</blockquote></details>

good idea
___
*[`pkg/testutils/lint/lint_test.go` line 448 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/81943#-N3UIGz82-b6AzFU9q0N:-N3VO4CY3r9FpKqBww2R:b-q7efzr) ([raw file](https://github.com/cockroachdb/cockroach/blob/8852d678fc6e5664469a7a508cb78f20a12034db/pkg/testutils/lint/lint_test.go#L448)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

if you decide to keep the env var logic, please move it to a different file. There's a lot going on in context.go and we'd like to avoid env var stuff creeping in elsewhere.
</blockquote></details>

done

moved to cli/env.go
