### PR TITLE
sql: Self-referencing tables can now reference a non-primary index without manually adding an index.

### LINKED ISSUE #20042: sql: double self-referential tables creation issue
So for some reason this doesn't work, but it should (works on Postgres):
```SQL
CREATE TABLE self_x2 (
  x INT PRIMARY KEY
 ,y INT UNIQUE REFERENCES self_x2(x)
 ,z INT REFERENCES self_x2(y)
);
```

But it will work if you add an index to `z`
```SQL
CREATE TABLE self_x2 (
  x INT PRIMARY KEY
 ,y INT UNIQUE REFERENCES self_x2(x)
 ,z INT REFERENCES self_x2(y)
 ,INDEX(z)
);
```

This index should be implied in the creation of the reference.

### PR DESCRIPTION
**Pull request by BramGruneir**
Previously, this would fail:
```sql
CREATE TABLE test20042 (
  x STRING PRIMARY KEY
 ,y STRING UNIQUE
 ,z STRING REFERENCES test20042(y)
);
```

But this would pass:

```sql
CREATE TABLE test20042 (
  x STRING PRIMARY KEY
 ,y STRING UNIQUE
 ,z STRING REFERENCES test20042(y)
 ,INDEX(z)
);
```

Release Note: Fixed a bug that prevented creating self-referencing tables that referenced a non-primary index without manually including the index on the referencing column.

Fixes #20042.

### CODE REVIEW

File: pkg/sql/logictest/testdata/logic_test/fk [hunk 1]
```diff
@@ -874,15 +874,22 @@ pkref_b  CREATE TABLE pkref_b (
 
 # See https://github.com/cockroachdb/cockroach/issues/20045
 statement ok
-CREATE TABLE self_x2 (
+CREATE TABLE test20045 (
   x STRING PRIMARY KEY
- ,y STRING UNIQUE REFERENCES self_x2(x)
- ,z STRING REFERENCES self_x2(y)
- ,INDEX(z)
```
Comment (vivekmenezes) [inline pkg/sql/logictest/testdata/logic_test/fk]: Why did you take out INDEX(z).

I'd actually not make the entire 20045 related change in this COMMIT

File: pkg/sql/logictest/testdata/logic_test/fk [hunk 2]
```diff
@@ -874,15 +874,22 @@ pkref_b  CREATE TABLE pkref_b (
...
 
 statement ok
-INSERT INTO self_x2 (x, y, z) VALUES ('pk1', NULL, NULL);
+INSERT INTO test20045 (x, y, z) VALUES ('pk1', NULL, NULL);
 
 statement ok
-DELETE FROM self_x2 WHERE x = 'pk1';
+DELETE FROM test20045 WHERE x = 'pk1';
+
+# See https://github.com/cockroachdb/cockroach/issues/20042
```
Comment (vivekmenezes) [inline pkg/sql/logictest/testdata/logic_test/fk]: no need for this since you already refer to 20042 in the table name

File: pkg/sql/logictest/testdata/logic_test/fk [hunk 3]
```diff
@@ -874,15 +874,22 @@ pkref_b  CREATE TABLE pkref_b (
...
+statement ok
+CREATE TABLE test20042 (
+  x STRING PRIMARY KEY
+ ,y STRING UNIQUE
+ ,z STRING REFERENCES test20042(y)
+);
```
Comment (vivekmenezes) [inline pkg/sql/logictest/testdata/logic_test/fk]: Wanna add an INSERT and DELETE after this to make sure that it works for this schema

File: pkg/sql/create_table.go [hunk 4]
```diff
@@ -403,15 +403,22 @@ func resolveFK(
 		constraintName = fmt.Sprintf("fk_%s_ref_%s", string(d.FromCols[0]), target.Name)
 	}
 
-	var targetIdx *sqlbase.IndexDescriptor
+	// We can't keep a reference to the index in the slice and at the same time
+	// add a new index to that slice without losing the reference. Instead, keep
+	// the index's index into target's list of indexes. If it is a primary index,
+	// targetIdxIndex is set to -1. Also store the targetIndex's ID so we
+	// don't have to do the lookup twice.
+	targetIdxIndex := -1
```
Comment (vivekmenezes) [inline pkg/sql/create_table.go]: I think you can get rid of this and use only targetIdxID in this change

**Review by vivekmenezes — COMMENTED** [review]
Thanks for fixing this!

**Comment by BramGruneir** [comment]
I took out the `INDEX(z)` as it was only required for table creation due to this bug.  I've split this into two commits, the second one dealing with 20045 exclusively.

---

Review status: 0 of 2 files reviewed at latest revision, 3 unresolved discussions.

---

*[pkg/sql/create_table.go, line 411 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/20325#-L-7PUCrEZbD1uVTo8EH-r1-411:-L-Dld6jJeYyOOejNuIP:b-zi9i6d) ([raw file](https://github.com/cockroachdb/cockroach/blob/2b5345017845b03d24359bb5f44836b554fe271b/pkg/sql/create_table.go#L411)):*
<details><summary><i>Previously, vivekmenezes wrote…</i></summary><blockquote>

I think you can get rid of this and use only targetIdxID in this change
</blockquote></details>

How?  We have an slice of indices, but I don't think that the location in the slice matches the ID every time.

---

*[pkg/sql/logictest/testdata/logic_test/fk, line 889 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/20325#-L-7PUCrEZbD1uVTo8EI-r1-889:-L-DlyEBoxT4On3H_OBJ:bd0bfwx) ([raw file](https://github.com/cockroachdb/cockroach/blob/2b5345017845b03d24359bb5f44836b554fe271b/pkg/sql/logictest/testdata/logic_test/fk#L889)):*
<details><summary><i>Previously, vivekmenezes wrote…</i></summary><blockquote>

no need for this since you already refer to 20042 in the table name
</blockquote></details>

Sure, I'll remove the comment, just seemed harmless to keep in there and matches how other issues are referenced in the logic tests.

---

*[pkg/sql/logictest/testdata/logic_test/fk, line 895 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/20325#-L-7PUCrEZbD1uVTo8EI-r1-895:-L-DmwpMEl-yudrDofl9:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/2b5345017845b03d24359bb5f44836b554fe271b/pkg/sql/logictest/testdata/logic_test/fk#L895)):*
<details><summary><i>Previously, vivekmenezes wrote…</i></summary><blockquote>

Wanna add an INSERT and DELETE after this to make sure that it works for this schema
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/20325#-:-L-DnB4BxKQbYbKuw_o3:b1xjotj)*

**Review by vivekmenezes — APPROVED** [review]
