### PR TITLE
roachprod: handle insecure cluster in delete cluster config

### LINKED ISSUE #125616: roachprod: The insecure flag is not considered when deleting a cluster
If a insecure cluster is created, the corresponding config is created in prometheus. This config is created in a separate location that is different from the secure clusters. When this cluster is destroyed, the `?insecure=true` flag has to be passed so that the specific config file is deleted. This is not done today.

To reproduce, create and start a insecure cluster and then destroy the same. The targets remain in 
https://grafana.testeng.crdb.io/prometheus/targets?search=&scrapePool=cluster-configs-insecure

Jira issue: CRDB-39528

### PR DESCRIPTION
**Pull request by nameisbhaskar**
If a insecure cluster is created, the corresponding config is created in prometheus. This config is created in a separate location that is different from the secure clusters. When this cluster is destroyed, the ?insecure=true flag has to be passed so that the specific config file gets deleted. This is not done today.

This change passes the ?insecure=true for insecure clusters

Fixes: #125616
Epic: None

### CODE REVIEW

**Comment by nameisbhaskar** [comment]
Service side change - https://github.com/cockroachlabs/prom-helper-service/pull/2

**Review by DarrylWong — COMMENTED** [review]
Is there a reason why when we create a cluster config, we note `insecure` as part of the HTTP request body, but when we delete it, we have to append it as part of the url? Is it an anti pattern to send a body for DELETE?

Besides that it lgtm!

**Comment by nameisbhaskar** [comment]
> Is there a reason why when we create a cluster config, we note `insecure` as part of the HTTP request body, but when we delete it, we have to append it as part of the url? Is it an anti pattern to send a body for DELETE?
> 
> Besides that it lgtm!

DELETE does not take any body. Also, this is a general convention.

**Comment by nameisbhaskar** [comment]
Thanks @DarrylWong for reviewing the changes!

**Comment by nameisbhaskar** [comment]
bors r=@DarrylWong

**Review by DarrylWong — APPROVED** [review]

**Comment by nameisbhaskar** [comment]
bors r=@DarrylWong

File: pkg/roachprod/cloud/cluster_cloud.go [hunk 1]
```diff
@@ -387,8 +388,18 @@ func DestroyCluster(l *logger.Logger, c *Cluster) error {
 		if _, ok := promhelperclient.SupportedPromProjects[node.Project]; ok &&
 			node.Provider == gce.ProviderName {
 			if err := promhelperclient.NewPromClient().DeleteClusterConfig(context.Background(),
-				c.Name, false, l); err != nil {
-				l.Errorf("Failed to delete the cluster config: %v", err)
+				c.Name, false, false /* insecure */, l); err != nil {
+				// TODO(bhaskar): Obtain secure cluster information.
+				// Cluster does not have the information on secure or not. So, we retry as insecure
+				// if delete fails with cluster as secure
+				if strings.Contains(err.Error(), "request failed with status 404") {
```
Comment (srosenberg) [inline pkg/roachprod/cloud/cluster_cloud.go:395]: In hindsight, we should have exposed `response.StatusCode`. String matching on the response payload makes refactoring more error-prone.
