### PR TITLE
storage: fix range quiescence

### LINKED ISSUE #9372: storage: quiescence leads to more elections
I'm able to reproduce the additional elections when quiescing is turned on in a local test environment. Within a single scheduler worker iteration we do the following:

```
			// Process the range ID.
			if state&stateRaftTick != 0 {
				// processRaftTick returns true if the range should perform ready
				// processing. Do not reorder this below the call to processRaftReady.
				if s.processor.processTick(id) {
					state |= stateRaftReady
				}
			}
			if state&stateRaftRequest != 0 {
				s.processor.processRequestQueue(id)
			}
			if state&stateRaftReady != 0 {
				s.processor.processReady(id)
			}
```

My untested hypothesis of what is happening:
1. Follower ticks a replica.
2. Follower processes a "quiesce" message from the leader.
3. Followers performs raft ready processing (due to the earlier tick) which unquiesces the replica.

At this point, the leader is "quiesced" but the follower is not. The follower will tick and then perform an election. What I'm not quite clear on is that exact timing for why this causes a disruption of request processing.

### PR DESCRIPTION
**Pull request by petermattis**
Fix range quiescence so that a follower is not left unquiesced while the
leader is quiesced. We address this problem in 3 ways, any of which by
itself would fix the problem:
1. The ordering of raft processing for a replica in raftScheduler has
   been changed so that a newly quiesced replica will not be woken by a
   spurious raft ready processing due to a tick.
2. We only unquiesce a range during raft ready processing if we actually
   have a ready struct to process.
3. If a follower unquiesces due to something other than a raft command
   being proposed or a message being received, it sends an empty proposal
   to the leader which will wake it from quiescence.

Fixes #9372.

---

This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/9383)

### CODE REVIEW

**Comment by tschottdorf** [comment]
LGTM in spirit, but all of the above need basic tests, in particular 3 because I don't think we send empty proposals at any other time. I would also want to understand exactly what causes the actual timeout (as far as I can tell, we haven't pinpointed the exact progression all the way to the end), for which there is likely zero motivation once this merges.

---

Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[storage/scheduler.go, line 188 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/9383#-KRfd_HG1GPqn1C1olWi:-KRfd_HHdJpjJrjFSjMf:b-bmvnck) ([raw file](https://github.com/cockroachdb/cockroach/blob/69db771252e6bde9da09a92ac87296455b62da85/storage/scheduler.go#L188)):*
> ```Go
> 			// "quiesce" message are processed in the same iteration and intervening
> 			// raft ready processing unquiesced the replica. Note that request
> 			// processing could also occur last, it just shouldn't occur in between
> ```

Could you expand this a little bit and explain what now happens when a quiesce request is received? Naively since you're processing it first it seems like the other two steps would wake it up again (putting processRequestQueue last seems more intuitive: first do work, then quiesce).

---

*[storage/scheduler.go, line 195 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/9383#-KRfdN-Vdy-CS_81T4wh:-KRfdN-Vdy-CS_81T4wi:bdtdy4g) ([raw file](https://github.com/cockroachdb/cockroach/blob/69db771252e6bde9da09a92ac87296455b62da85/storage/scheduler.go#L195)):*
> ```Go
> 			if state&stateRaftTick != 0 {
> 				// processRaftTick returns true if the range should perform ready
> 				// processing. Do not reorder this below the call to processRaftReady.
> ```

while you're here: s/Raft//

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/9383#-:-KRfcQmIvLr3eDEwx_tP:btmss4j)*

**Comment by petermattis** [comment]
Yeah, I need to figure out how to test this. Empty proposals actually are generated by Raft internally when there are conflicting conf changes. 

---

Review status: 4 of 5 files reviewed at latest revision, 2 unresolved discussions, some commit checks pending.

---

*[storage/scheduler.go, line 188 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/9383#-KRfd_HG1GPqn1C1olWi:-KRi2q3GXjod-hgqROco:b-fx63b7) ([raw file](https://github.com/cockroachdb/cockroach/blob/69db771252e6bde9da09a92ac87296455b62da85/storage/scheduler.go#L188)):*
<details><summary><i>Previously, tschottdorf (Tobias Schottdorf) wrote…</i></summary>
> Could you expand this a little bit and explain what now happens when a quiesce request is received? Naively since you're processing it first it seems like the other two steps would wake it up again (putting processRequestQueue last seems more intuitive: first do work, then quiesce).
</details>
The tick becomes a no-op because the replica is quiesced. Moved this last as I didn't have a preference on the ordering.

---

*[storage/scheduler.go, line 195 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/9383#-KRfdN-Vdy-CS_81T4wh:-KRi3auAymXZCqH_nuMz:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/69db771252e6bde9da09a92ac87296455b62da85/storage/scheduler.go#L195)):*
<details><summary><i>Previously, tschottdorf (Tobias Schottdorf) wrote…</i></summary>
> while you're here: s/Raft//
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/9383#-:-KRi2Me7Bkod7U9rvofJ:bnxis9e)*

File: storage/replica.go [hunk 1]
```diff
@@ -1681,42 +1686,65 @@ func defaultProposeRaftCommandLocked(r *Replica, p *pendingCmd) error {
...
-				return raftGroup.ProposeConfChange(raftpb.ConfChange{
-					Type:    changeTypeInternalToRaft[crt.ChangeType],
-					NodeID:  uint64(crt.Replica.ReplicaID),
-					Context: encodedCtx,
-				})
+			return r.withRaftGroupLocked(true, func(raftGroup *raft.RawNode) (bool, error) {
+				// We're proposing a command here so there is no need to wake the
+				// leader if we were quiesced.
+				r.unquiesceLocked()
+				return false, /* !unquiesce */
```
Comment (bdarnell) [inline storage/replica.go]: I don't like that calling `r.unquiesceLocked()` and returning false is not equivalent to returning true. The return value needs to be named and documented as something other than just `unquiesce`.

File: storage/replica.go [hunk 2]
```diff
@@ -1681,42 +1686,65 @@ func defaultProposeRaftCommandLocked(r *Replica, p *pendingCmd) error {
...
+	}
+}
+
+func (r *Replica) unquiesceAndWakeLeaderLocked() {
+	if r.mu.quiescent {
+		if log.V(3) {
+			log.Infof(r.ctx, "unquiescing: waking leader")
+		}
+		r.mu.quiescent = false
+		_ = r.mu.internalRaftGroup.Propose(nil)
```
Comment (bdarnell) [inline storage/replica.go]: This should be harmless because raft does generate these empty messages on its own, but it's inefficient because we watch for these messages (which are normally infrequent) and use them to trigger reproposals and other relatively expensive operations. We don't want to make these more common than they already are. We should send a different message to the leader to wake it up (or possibly a MsgProp containing no Entries, instead of an MsgProp containing one empty Entry).

**Comment by petermattis** [comment]
Modulo tests (which I need to ponder how to write), I think this is ready to go. Quiescence has a problematic interaction with the Raft CheckQuorum functionality, but the possibility of a follower not quiescing when the leader does is almost completely eliminated by this change.

File: storage/replica.go [hunk 3]
```diff
@@ -2032,7 +2060,19 @@ var enableQuiescence = envutil.EnvOrDefaultBool("COCKROACH_ENABLE_QUIESCENCE", f
 // follower which will send a MsgProp to the leader that will unquiesce the
 // leader. If the leader of a quiesced range dies, followers will not notice,
 // though any request directed to the range will eventually end up on a
-// follower which will unquiesce the follower and lead to an election.
+// follower which will unquiesce the follower and lead to an election. When a
+// follower unquiesces for a reason other than receiving a raft message or
+// proposing a raft command, it wakes the leader by sending an empty message
```
Comment (bdarnell) [inline storage/replica.go]: What other reasons are there for unquiescing?

File: storage/replica.go [hunk 4]
```diff
@@ -2032,7 +2060,19 @@ var enableQuiescence = envutil.EnvOrDefaultBool("COCKROACH_ENABLE_QUIESCENCE", f
...
+// proposal. This acts a failsafe against bugs in which a follower is left
+// unquiesced while the leader is quiesced.
```
Comment (bdarnell) [inline storage/replica.go]: Why is this a scenario that must be avoided? If the follower is unquiesced, won't it eventually unquiesce the leader of its own accord?

File: storage/replica.go [hunk 5]
```diff
@@ -2032,7 +2060,19 @@ var enableQuiescence = envutil.EnvOrDefaultBool("COCKROACH_ENABLE_QUIESCENCE", f
...
+//
+// TODO(peter): There remains a scenario in which a follower is left unquiesced
+// while the leader is quiesced: the follower's receive queue is full and the
```
Comment (bdarnell) [inline storage/replica.go]: The transport is allowed to drop/reorder messages for other reasons too. We can't guarantee that either the quiesce message or the empty MsgProp will make it through in a single attempt; the system must be able to recover from these messages getting dropped.

File: storage/replica.go (hunk 3 above)
Comment (petermattis) [inline storage/replica.go]: Concurrent enqueuing of a tick. If the scheduler is overwhelmed I could see that happening.

File: storage/replica.go (hunk 4 above)
Comment (petermattis) [inline storage/replica.go]: Must be avoided is strong language. Desirable to avoid as it leads to spurious elections which cause hiccups due to the analysis in #9372.

File: storage/replica.go (hunk 5 above)
Comment (petermattis) [inline storage/replica.go]: The system will recover from either the quiesce or empty `MsgProp` being dropped. We'll get an unnecessary election and worst case we'll see the behavior of #9372 and a few second hiccup to the range. If we fix the election machinery so the spurious election doesn't fail (simulated by disabling `CheckQuorum`) the hiccup becomes microscopic.

File: storage/replica.go (hunk 2 above)
Comment (petermattis) [inline storage/replica.go]: Given that sending this wakeup is expected to be extremely rare, do you think it is worth plumbing in something other than an empty `MsgProp`.

File: storage/replica.go (hunk 1 above)
Comment (petermattis) [inline storage/replica.go]: Yeah, let me figure out a better name.

Comment (petermattis) [inline storage/replica.go]: I wonder if it would be better to always require the user of `withRaftGroupLocked` to unquiesce as appropriate. I was trying to avoid that.

File: storage/replica.go (hunk 2 above)
Comment (petermattis) [inline storage/replica.go]: To give some sense for how often this happens: before the other fixes in this PR we were waking the leader ~20/min under the test load I'm using. With the other fixes in this PR we haven't woken the leader once after running for 10 minutes. I've added a comment.

File: storage/replica.go (hunk 1 above)
Comment (petermattis) [inline storage/replica.go]: I've renamed the return value to `unquiesceAndWakeLeader`.

File: storage/replica.go (hunk 4 above)
Comment (petermattis) [inline storage/replica.go]: I've extended the commentary here.

File: storage/replica.go (hunk 5 above)
Comment (petermattis) [inline storage/replica.go]: I've extended the commentary about dropped and reordered messages. Reordering doesn't seem problematic, but dropping will lead to elections.

**Comment by petermattis** [comment]
Added a test that verifies the leader doesn't move if a follower is inadvertently unquiesced.

File: storage/client_raft_test.go [hunk 6]
```diff
@@ -2504,3 +2504,72 @@ func TestRaftBlockedReplica(t *testing.T) {
...
+	// campaign.
+	ticks := mtc.stores[followerIdx].Metrics().RaftTicks.Count
+	for targetTicks := ticks() + int64(2*sc.RaftElectionTimeoutTicks); ticks() < targetTicks; {
+		time.Sleep(time.Millisecond)
+	}
+
+	// Wait for the range to quiesce again.
+	waitForQuiescence(1)
+
+	// The leadership should not have changed.
```
Comment (bdarnell) [inline storage/client_raft_test.go]: Also check that `RaftStatus().HardState.Term` has not changed (the Term changes in any election, even if leadership ended up back where it started)

File: storage/replica.go [hunk 7]
```diff
@@ -2048,7 +2079,32 @@ var enableQuiescence = envutil.EnvOrDefaultBool("COCKROACH_ENABLE_QUIESCENCE", f
...
+// follower unquiesces for a reason other than receiving a raft message or
+// proposing a raft command (for example the concurrent enqueuing of a tick),
+// it wakes the leader by sending an empty message proposal. This avoids
+// unnecessary elections due to bugs in which a follower is left unquiesced
+// while the leader is quiesced.
+//
+// Note that both the quiesce and wake-the-leader messages can be dropped or
+// reordered by the transport. The wake-the-leader message is termless so it
+// won't affect elections and, while it triggers reproprosals that won't cause
+// problems on reorderin. If the wake-the-leader message is dropped the leader
```
Comment (bdarnell) [inline storage/replica.go]: s/reorderin/reordering/

File: storage/replica.go [hunk 8]
```diff
@@ -2048,7 +2079,32 @@ var enableQuiescence = envutil.EnvOrDefaultBool("COCKROACH_ENABLE_QUIESCENCE", f
...
+// won't be woken and the follower will eventually call an election.
+//
+// If the quiesce message is dropped the follower which missed it will not
+// quiesce and will eventually cause an election. The quiesce message is tagged
+// with the current term and commit index. If the quiesce message is reordered
+// it will either still apply to the recipient or the recipient will have moved
+// forward and the quiesce message will fall back to being a heartbeat.
+//
+// TODO(peter): There remains a scenario in which a follower is left unquiesced
```
Comment (bdarnell) [inline storage/replica.go]: I think this TODO can be removed. This scenario is already acknowledged in the previous paragraph.

File: storage/replica.go (hunk 2 above)
Comment (bdarnell) [inline storage/replica.go]: Yeah, if it's rare it's not worth bothering with. For some reason I was thinking it was going to be much more common than elections, but I'm not sure why.

**Review by bdarnell — APPROVED** [review]
