### PR TITLE
sql: fix AS OF SYSTEM TIME test flakiness

### LINKED ISSUE #9779: test failure: TestAsOfTime
```
--- FAIL: TestAsOfTime (0.05s)
	as_of_test.go:70: unexpected error: pq: database "d" does not exist
```

Saw this on a private build with my own changes but looks totally unrelated to my changes.

### PR DESCRIPTION
**Pull request by madelynnblue**
Fixes #9779

---

This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/9857)

### CODE REVIEW

File: sql/as_of_test.go [hunk 1]
```diff
@@ -59,13 +59,22 @@ func TestAsOfTime(t *testing.T) {
...
+	tsDBExists := logicalTime.Format(time.RFC3339Nano)
 	if err := db.QueryRow("SELECT now()").Scan(&tm); err != nil {
 		t.Fatal(err)
+	} else {
+		t.Logf("Now: %v", tm.UnixNano())
 	}
-	tsDBExists := tm.Format(time.RFC3339Nano)
+	// AS OF SYSTEM TIME requires now() to be after time timestamp. Since we
+	// got the timestamp from the HLC, need to wait until it is after now().
+	time.Sleep(logicalTime.Sub(tm))
```
Comment (vivekmenezes) [inline sql/as_of_test.go]: I think what you need to do here is keep querying the DB with SELECT now() until it's after the logicalTime or perhaps SELECT now() > logical_time and move forward when it's positive

Comment (vivekmenezes) [inline sql/as_of_test.go]: I suppose you can use SucceedsSoon()

Comment (mjibson) [inline sql/as_of_test.go]: Done.

**Comment by mjibson** [comment]
Also found a similar problem in the other test with the same solution. Added #9859 as a more general fix for these bugs.

File: sql/as_of_test.go [hunk 2]
```diff
@@ -178,19 +192,40 @@ func TestAsOfRetry(t *testing.T) {
...
+		return nil
+	})
 
 	var walltime int64
-	if err := sqlDB.QueryRow("UPDATE d.t SET a = $1 RETURNING cluster_logical_timestamp()::int", val2).Scan(&walltime); err != nil {
+	if err := sqlDB.QueryRow("UPDATE d.t SET a = $1 RETURNING cluster_logical_timestamp()::int, cluster_logical_timestamp()::string", val2).Scan(&walltime, &clss); err != nil {
 		t.Fatal(err)
 	}
+	t.Logf("CLS 2: %v", walltime)
+	t.Logf("CLSS 2: %v", clss)
```
Comment (vivekmenezes) [inline sql/as_of_test.go]: No strong need for Logf and the one above

File: sql/as_of_test.go [hunk 3]
```diff
@@ -178,19 +192,40 @@ func TestAsOfRetry(t *testing.T) {
...
+	util.SucceedsSoon(t, func() error {
+		var afterNow bool
+		if err := sqlDB.QueryRow("SELECT now() >= $1", tsStart).Scan(&afterNow); err != nil {
+			return err
+		}
+		if !afterNow {
+			return errors.New("timestamp not after now()")
+		}
+		return nil
+	})
```
Comment (vivekmenezes) [inline sql/as_of_test.go]: I suppose you are calling this twice, so you might as well write a function that implements this.

File: sql/as_of_test.go [hunk 4]
```diff
@@ -59,13 +61,25 @@ func TestAsOfTime(t *testing.T) {
...
+	var logicalTS int64
+	if err := db.QueryRow("CREATE DATABASE d; SELECT cluster_logical_timestamp()::int").Scan(&logicalTS); err != nil {
 		t.Fatal("unexpected error:", err)
 	}
-	if err := db.QueryRow("SELECT now()").Scan(&tm); err != nil {
-		t.Fatal(err)
-	}
-	tsDBExists := tm.Format(time.RFC3339Nano)
+	// Make sure we see the DB create by using a TS after its txn time.
+	logicalTime := time.Unix(0, logicalTS+1)
```
Comment (vivekmenezes) [inline sql/as_of_test.go]: No strong need for logicalTime

File: sql/as_of_test.go [hunk 5]
```diff
@@ -59,13 +61,25 @@ func TestAsOfTime(t *testing.T) {
...
-	if _, err := db.Exec("CREATE DATABASE d"); err != nil {
+	var logicalTS int64
+	if err := db.QueryRow("CREATE DATABASE d; SELECT cluster_logical_timestamp()::int").Scan(&logicalTS); err != nil {
 		t.Fatal("unexpected error:", err)
 	}
-	if err := db.QueryRow("SELECT now()").Scan(&tm); err != nil {
-		t.Fatal(err)
-	}
-	tsDBExists := tm.Format(time.RFC3339Nano)
+	// Make sure we see the DB create by using a TS after its txn time.
```
Comment (tschottdorf) [inline sql/as_of_test.go]: Wait a minute, all nodes in this cluster share a clock, right? It shouldn't be possible to get a transaction back at a timestamp that's ahead of any physical clock in the system (hard to imagine even when clocks jump backward).

Do you have an explanation? Otherwise, I think you're in for a bug hunt!

Comment (mjibson) [inline sql/as_of_test.go]: Nope, no explanation. The bug is trivially reproducible with

```
make test 'PKG=./sql' 'TESTS=TestAsOfTime' 'TESTFLAGS=-count 100'
```

Comment (mjibson) [inline sql/as_of_test.go]: I'll look into it deeper tonight.

File: sql/as_of_test.go (hunk 3 above)
Comment (mjibson) [inline sql/as_of_test.go]: Done.

**Comment by tamird** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 10 unresolved discussions, some commit checks failed.

---

*[sql/as_of_test.go, line 67 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/9857#-KTl0ceA7nSb5PItYvrB:-KTl0ceBe7e1xS79wgHc:barghzy) ([raw file](https://github.com/cockroachdb/cockroach/blob/cc354424e77261454468ca576db492bb0a747ac0/sql/as_of_test.go#L67)):*
> ```Go
> 	var logicalTS int64
> 	if err := db.QueryRow("CREATE DATABASE d; SELECT cluster_logical_timestamp()::int").Scan(&logicalTS); err != nil {
> 		t.Fatal("unexpected error:", err)
> ```

yikes, this needs to be `Fatalf`, but actually `t.Fatal(err)` is also fine.

---

*[sql/as_of_test.go, line 188 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/9857#-KTl1-1_u3Mx97vK-aag:-KTl1-1_u3Mx97vK-aah:bc7rn3p) ([raw file](https://github.com/cockroachdb/cockroach/blob/cc354424e77261454468ca576db492bb0a747ac0/sql/as_of_test.go#L188)):*
> ```Go
> 	var walltime int64
> 
> 	if err := sqlDB.QueryRow(fmt.Sprintf(`
> ```

wait, can't this use a placeholder?

---

*[sql/as_of_test.go, line 196 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/9857#-KTl14mAF87NEu00qqjs:-KTl14mAF87NEu00qqjt:bc3nlio) ([raw file](https://github.com/cockroachdb/cockroach/blob/cc354424e77261454468ca576db492bb0a747ac0/sql/as_of_test.go#L196)):*
> ```Go
> 		t.Fatal(err)
> 	}
> 	tsStart := time.Unix(0, walltime+1).Format(time.RFC3339Nano)
> ```

probably better to do the formatting in the function.

---

*[sql/as_of_test.go, line 259 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/9857#-KTl0MOz3Fo9myiyf2Xt:-KTl0MOz3Fo9myiyf2Xu:bq1rlt5) ([raw file](https://github.com/cockroachdb/cockroach/blob/cc354424e77261454468ca576db492bb0a747ac0/sql/as_of_test.go#L259)):*
> ```Go
> }
> 
> func waitForNow(t *testing.T, db *sql.DB, ts string) {
> ```

the error message produced by this are going to suck because they will point inside this function regardless of the caller. It would be better to put everything except the `util.SucceedsSoon` in this function and put the `util.SucceedsSoon` directly in the caller.

---

*[sql/as_of_test.go, line 266 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/9857#-KTl0pnt8gWCl8VyuH1r:-KTl0pnt8gWCl8VyuH1s:b-kvjc3f) ([raw file](https://github.com/cockroachdb/cockroach/blob/cc354424e77261454468ca576db492bb0a747ac0/sql/as_of_test.go#L266)):*
> ```Go
> 		}
> 		if !afterNow {
> 			return errors.New("timestamp not after now()")
> ```

would be good to include `ts` in this message because why not.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/9857)*

**Comment by mjibson** [comment]
Review status: 0 of 1 files reviewed at latest revision, 10 unresolved discussions.

---

*[sql/as_of_test.go, line 69 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/9857#-KTk6XxTrYihuxXKXjNg-r2-69:-KTmp5CuavFcNi3d3R75:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/db4bfd501833bb84835308cf7dd507e0868ed5ba/sql/as_of_test.go#L69)):*
<details><summary><i>Previously, vivekmenezes wrote…</i></summary>
> No strong need for logicalTime
</details>
Done.

---

*[sql/as_of_test.go, line 228 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/9857#-KTk6XxTrYihuxXKXjNg-r2-228:-KTmq94i8CGeOqIGTbLm:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/db4bfd501833bb84835308cf7dd507e0868ed5ba/sql/as_of_test.go#L228)):*
<details><summary><i>Previously, vivekmenezes wrote…</i></summary>
> No strong need for Logf and the one above
</details>
Done.

---

*[sql/as_of_test.go, line 67 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/9857#-KTl0ceA7nSb5PItYvrB:-KTmp44wv74eYZ5YEhj8:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/cc354424e77261454468ca576db492bb0a747ac0/sql/as_of_test.go#L67)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> yikes, this needs to be `Fatalf`, but actually `t.Fatal(err)` is also fine.
</details>
Done.

---

*[sql/as_of_test.go, line 188 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/9857#-KTl1-1_u3Mx97vK-aag:-KTmqtH_TyaY1PPl-9Sq:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/cc354424e77261454468ca576db492bb0a747ac0/sql/as_of_test.go#L188)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> wait, can't this use a placeholder?
</details>
Done.

---

*[sql/as_of_test.go, line 196 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/9857#-KTl14mAF87NEu00qqjs:-KTmpoR2EeOgjA67RwTW:b2l3tli) ([raw file](https://github.com/cockroachdb/cockroach/blob/cc354424e77261454468ca576db492bb0a747ac0/sql/as_of_test.go#L196)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> probably better to do the formatting in the function.
</details>
One of the usages needs the string version later, so we'd have to format it twice. I think it's ok as is.

---

*[sql/as_of_test.go, line 259 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/9857#-KTl0MOz3Fo9myiyf2Xt:-KTmqs_xCKW-ZK8hA8mM:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/cc354424e77261454468ca576db492bb0a747ac0/sql/as_of_test.go#L259)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> the error message produced by this are going to suck because they will point inside this function regardless of the caller. It would be better to put everything except the `util.SucceedsSoon` in this function and put the `util.SucceedsSoon` directly in the caller.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/9857)*

**Comment by tamird** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 6 unresolved discussions, all commit checks successful.

---

*[sql/as_of_test.go, line 266 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/9857#-KTl0pnt8gWCl8VyuH1r:-KTnH0tKBARhbiDNQGX3:b-ezo2en) ([raw file](https://github.com/cockroachdb/cockroach/blob/cc354424e77261454468ca576db492bb0a747ac0/sql/as_of_test.go#L266)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> would be good to include `ts` in this message because why not.
</details>
So thinking about it a bit more, I realized that the error message this produces will still point to this line (since the line number comes from the `errors.Errorf` call. I think you're gonna need to repeat this code to get reasonable errors.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/9857)*

**Comment by mjibson** [comment]
Review status: 0 of 1 files reviewed at latest revision, 6 unresolved discussions.

---

*[sql/as_of_test.go, line 266 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/9857#-KTl0pnt8gWCl8VyuH1r:-KTpI24sJG-eS9IxyBsd:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/cc354424e77261454468ca576db492bb0a747ac0/sql/as_of_test.go#L266)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> So thinking about it a bit more, I realized that the error message this produces will still point to this line (since the line number comes from the `errors.Errorf` call. I think you're gonna need to repeat this code to get reasonable errors.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/9857)*

File: sql/as_of_test.go [hunk 6]
```diff
@@ -56,39 +58,50 @@ func TestAsOfTime(t *testing.T) {
...
-	if err := db.QueryRow("SELECT now()").Scan(&tm); err != nil {
+	var logicalTS int64
+	if err := db.QueryRow("CREATE DATABASE d; SELECT cluster_logical_timestamp()::int").Scan(&logicalTS); err != nil {
 		t.Fatal(err)
 	}
-	tsDBExists := tm.Format(time.RFC3339Nano)
+	// Make sure we see the DB create by using a TS after its txn time.
+	tsDBExists := time.Unix(0, logicalTS+1).Format(time.RFC3339Nano)
+	// Wait until now() is after the above cluster_logical_timestamp() so the max check doesn't get hit.
+	util.SucceedsSoon(t, func() error {
```
Comment (RaduBerinde) [inline sql/as_of_test.go]: [nit] this could be a function since it'used twice

**Review by RaduBerinde — APPROVED** [review]
LGTM

File: sql/as_of_test.go (hunk 6 above)
Comment (mjibson) [inline sql/as_of_test.go]: We just finished a 3 revision process adding and removing this as a function. See Tamir's comments above about error line numbers.

Comment (RaduBerinde) [inline sql/as_of_test.go]: Ha, sorry about that, should have looked at the previous comments (didn't open Reviewable).

**Comment by tamird** [comment]
Reviewed 1 of 1 files at r5.
Review status: all files reviewed at latest revision, 6 unresolved discussions, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/9857)*

File: sql/as_of_test.go (hunk 5 above)
Comment (vivekmenezes) [inline sql/as_of_test.go]: Hey what was the bug?

Comment (mjibson) [inline sql/as_of_test.go]: Dunno yet. This is a stop gap to prevent the test flakiness. I've opened #9899 to track that bug.
