### PR TITLE
kvserver: deflake TestLeaseTransferReplicatesLocks

### LINKED ISSUE #164262: kv/kvserver: TestLeaseTransferReplicatesLocks failed
kv/kvserver.TestLeaseTransferReplicatesLocks [failed](https://mesolite.cluster.engflow.com/invocations/default/804f1eb1-d48d-4ffb-a567-2ee6561fe51f?testReportRun=1&testReportShard=39&testReportAttempt=1#targets-Ly9wa2cva3Yva3ZzZXJ2ZXI6a3ZzZXJ2ZXJfdGVzdA==) on master @ [943f82fd320a79d23fc71ddb65f0223e10713081](https://github.com/cockroachdb/cockroach/commits/943f82fd320a79d23fc71ddb65f0223e10713081):

```
=== RUN   TestLeaseTransferReplicatesLocks
    test_log_scope.go:172: test logs captured to: outputs.zip/logTestLeaseTransferReplicatesLocks134941666
    test_log_scope.go:82: use -show-logs to present logs inline
    test_server_shim.go:686: DRPC is enabled (via override by TestingGlobalDRPCOption)
    client_replica_test.go:5906: transferring to s1
    client_replica_test.go:5908: done transferring to s1
    client_replica_test.go:5926: txn1: lock acquired, waiting for txn2 cancellation
    client_replica_test.go:5939: txn2: tnx1 lock acquisition observed, starting txn
    client_replica_test.go:5965: transferring lease from s1 -> s2
    client_replica_test.go:5968: cancelling txn2
    client_replica_test.go:5928: txn1: done
    client_replica_test.go:5975: 
        	Error Trace:	pkg/kv/kvserver/client_replica_test.go:5975
        	Error:      	"0" is not greater than or equal to "1"
        	Test:       	TestLeaseTransferReplicatesLocks
    panic.go:615: -- test log scope end --
test logs left over in: outputs.zip/logTestLeaseTransferReplicatesLocks134941666
--- FAIL: TestLeaseTransferReplicatesLocks (35.04s)
```

Parameters:
 - <code>attempt=1</code>
 - <code>race=true</code>
 - <code>run=1</code>
 - <code>shard=39</code>
<details><summary>Help</summary>
<p>

See also: [How To Investigate a Go Test Failure \(internal\)](https://cockroachlabs.atlassian.net/l/c/HgfXfJgM)
</p>
</details>
/cc @cockroachdb/kv-triage
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*TestLeaseTransferReplicatesLocks.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/bazci/githubpost/issues)

</sub>

Jira issue: CRDB-60722

### PR DESCRIPTION
**Pull request by wenyihu6**
This test was flaky because it used a regular scratch range, which
could get a leader lease under metamorphic testing. With leader
leases, the lease follows Raft leadership — so a Raft election
(common under race builds) causes an uncooperative lease change
that clears the lock table without exporting unreplicated locks.
The subsequent cooperative transfer then finds no locks to export,
causing the metric assertion to fail.

This commit sets RaftElectionTimeoutTicks high in the test to prevent
timeout-based elections, and also sets DisablePreCampaignStoreLivenessCheck
to ensure the initial campaign succeeds despite the high election timeout
(without it, a cold cluster under leader leases can fail the first
campaign due to missing store liveness support, and then never retry).

Note that this may not fully address the flake: if store liveness blips
long enough after a leader is established, the leader is lost permanently
since the high election timeout prevents a timely re-election. 

Fixes: https://github.com/cockroachdb/cockroach/issues/164262

Release note: None

Made-with: Cursor

### CODE REVIEW

File: pkg/kv/kvserver/client_replica_test.go [hunk 1]
```diff
@@ -5893,7 +5893,7 @@ func TestLeaseTransferReplicatesLocks(t *testing.T) {
 	})
 	defer tc.Stopper().Stop(ctx)
 
-	scratch := tc.ScratchRange(t)
+	scratch := tc.ScratchRangeWithExpirationLease(t)
```
Comment (pav-kv) [inline pkg/kv/kvserver/client_replica_test.go]: I didn't follow the explanation for why this is a fix. Typically, when we try to prevent leadership loss in tests, we increase the election timeout:

https://github.com/cockroachdb/cockroach/blob/402cb7973d16c84a53c64e1f28aa513d13d0b156/pkg/kv/kvserver/client_raft_test.go#L1895-L1898

Comment (wenyihu6) [reply pkg/kv/kvserver/client_replica_test.go]: Thanks for the pointer! My understanding was that the prior fix of using expiration leases would sidestep the uncooperative lease transfer with leader lease but wasn't sure if it was the best approach. Agreed that the fix you proposed provides better coverage. Updated.

Comment (tbg) [reply pkg/kv/kvserver/client_replica_test.go]: When we set the election timeout very high, isn't there a chance that an initial election stalemates, and then we're stuck unavailable because the timer for the next attempt never fires?

Comment (pav-kv) [reply pkg/kv/kvserver/client_replica_test.go]: The comment linked above references one such case: `DisablePreCampaignStoreLivenessCheck` fixes the case when election can't succeed due to missing store liveness signal [[1](https://github.com/cockroachdb/cockroach/blob/402cb7973d16c84a53c64e1f28aa513d13d0b156/pkg/kv/kvserver/client_raft_test.go#L1932-L1937)]. Did you mean that bit, or some other scenario(s)?

We should likely use that second knob too. The UX of this is a bit unfortunate.

Comment (pav-kv) [reply pkg/kv/kvserver/client_replica_test.go]: There is also a problem: if store liveness blips long enough, we lose the leader permanently in this test.

Comment (wenyihu6) [reply pkg/kv/kvserver/client_replica_test.go]: Added the second knob. Understood that this may not fully deflake. Do we prefer if you just skip this test under race?

Comment (wenyihu6) [reply pkg/kv/kvserver/client_replica_test.go]: Put up https://github.com/cockroachdb/cockroach/pull/164508 if that's a better option.

Comment (pav-kv) [reply pkg/kv/kvserver/client_replica_test.go]: I'm ok with the fix as is, and we can address if the fix doesn't help.

The lease is subject to this kind of loss no matter which type: if any of the heartbeat mechanism is late by some seconds.

**Review by pav-kv — APPROVED** [review]

File: pkg/kv/kvserver/client_replica_test.go (hunk 1 above)
Comment (wenyihu6) [reply pkg/kv/kvserver/client_replica_test.go]: Ack, removed that part from the commit msg. Will look into more on this as well.

Comment (wenyihu6) [reply pkg/kv/kvserver/client_replica_test.go]: Will merge both this PR and https://github.com/cockroachdb/cockroach/pull/164508. We can revert this commit if it becomes undesirable.
