### PR TITLE
backupccl: fix codec selection during restore

### LINKED ISSUE #115773: backupccl: empty full followed by incremental backup can result in use of the wrong codec
An empty full backup captures no Spans in the backup manifest. If this full backup is then followed by an incremental that does capture some data, the codec we use in the key rewriter is incorrect. This is because we resolve the codec based on the Spans in the full backup manifest, of which there are none, causing us to default to a SystemCodec. Using a system codec when running inside an application tenant generates an error when decoding the key and causes the restore to fail. We should be inferring the codec from the first non-empty backup manifest.

Jira issue: CRDB-34204

### PR DESCRIPTION
**Pull request by adityamaru**
Previously, the codec selection logic only looked at a single manifest to determine whether the backup data requires a system or tenant codec to be read. In older release branches if the full backup was empty (but a subsequent incremental was not) then we could incorrectly use a system codec for a backup that actually required a tenant codec.

To fix this we now process all the manifests in the backup chain and use the first non-empty manifest.

Fixes: #115773
Release note(bug fix): an empty full backup, followed by non-empty incrementals taken inside an application tenant may be unrestoreable because of the use of an incorrect SQL codec

### CODE REVIEW

File: pkg/ccl/backupccl/backupinfo/manifest_handling_test.go [hunk 1]
```diff
@@ -292,3 +294,86 @@ func mustCreateFileIterFactory(
...
+		{
+			name: "all-empty",
+			manifests: []backuppb.BackupManifest{
+				{Spans: []roachpb.Span{{}}},
+				{Spans: []roachpb.Span{{}}},
+				{Spans: []roachpb.Span{{}}},
+			},
+			expectedCodec: keys.SystemSQLCodec,
+		},
+	} {
```
Comment (msbutler) [inline pkg/ccl/backupccl/backupinfo/manifest_handling_test.go:372]: nice test!

File: pkg/ccl/backupccl/backup_test.go [hunk 2]
```diff
@@ -3735,6 +3731,55 @@ func TestRestoreAsOfSystemTime(t *testing.T) {
...
+	backupPath := "nodelocal://1/create_and_drop"
+
+	t.Run("empty-full-non-empty-inc", func(t *testing.T) {
+		sqlDB.Exec(t, "CREATE DATABASE create_and_drop")
+		sqlDB.Exec(t, "CREATE DATABASE create_and_drop_restore")
+		sqlDB.Exec(t, `BACKUP DATABASE create_and_drop INTO $1 WITH revision_history`, backupPath)
+		sqlDB.Exec(t, "CREATE TABLE create_and_drop.a (k int, v string)")
+		sqlDB.Exec(t, "INSERT INTO create_and_drop.a VALUES (1, 'foo')")
+		sqlDB.QueryRow(t, "SELECT cluster_logical_timestamp()").Scan(&tsBefore)
+		sqlDB.Exec(t, "DROP TABLE create_and_drop.a")
```
Comment (msbutler) [inline pkg/ccl/backupccl/backup_test.go:3756]: curious: why did you need to drop the table?

**Review by msbutler — APPROVED** [review]
Looks great! nice tests!

File: pkg/ccl/backupccl/backup_test.go (hunk 2 above)
Comment (adityamaru) [reply pkg/ccl/backupccl/backup_test.go:3756]: don't necessarily have to, just copy pasted this test from another test where I initially noticed this behaviour

**Comment by adityamaru** [comment]
Thanks!

bors r=msbutler

**Comment by adityamaru** [comment]
bors retry

**Comment by stevendanna** [comment]
@adityamaru Heads up that your auto-backport failed here.
