### PR TITLE
server: avoid deadlock when initing additional stores

### LINKED ISSUE #106706: server: TestAddNewStoresToExistingNodes failed
server.TestAddNewStoresToExistingNodes [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Ci_TestsAwsLinuxArm64_UnitTests/10886615?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Ci_TestsAwsLinuxArm64_UnitTests/10886615?buildTab=artifacts#/) on master @ [665084ed379a25fcde92ee8b4c9dc48e192876e5](https://github.com/cockroachdb/cockroach/commits/665084ed379a25fcde92ee8b4c9dc48e192876e5):

Fatal error:

```
panic: test timed out after 14m55s

```
Stack: 

```
goroutine 131489 [running]:
testing.(*M).startAlarm.func1()
	GOROOT/src/testing/testing.go:2036 +0x88
created by time.goFunc
	GOROOT/src/time/sleep.go:176 +0x38
```
<details><summary>Log preceding fatal error</summary>
<p>

```
=== RUN   TestAddNewStoresToExistingNodes
    test_log_scope.go:167: test logs captured to: /artifacts/tmp/_tmp/dbd7076bfe20e3183065a44fa4f7e406/logTestAddNewStoresToExistingNodes363450179
    test_log_scope.go:81: use -show-logs to present logs inline
```
</p>
</details>
<details><summary>Help</summary>
<p>

See also: [How To Investigate a Go Test Failure \(internal\)](https://cockroachlabs.atlassian.net/l/c/HgfXfJgM)
</p>
</details>
/cc @cockroachdb/kv @cockroachdb/storage
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*TestAddNewStoresToExistingNodes.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)
</sub>

### PR DESCRIPTION
**Pull request by tbg**
We need to start node liveness before waiting for additional store init.

Otherwise, we can end up in a situation where each node is sitting on the
channel and nobody has started their liveness yet. The sender to the channel
will first have to get an Increment through KV, but if nobody acquires the
lease (since nobody's heartbeat loop is running), this will never happen.

In practice, *most of the time*, there is no deadlock because the lease
acquisition path performs a synchronous heartbeat to the own entry in most
cases (ignoring the fact that liveness hasn't been started yet). But there is
also another path where someone else's epoch needs to be incremented, and this
path also checks if the node itself is live - which it won't necessarily be
(liveness loop is not running yet).

Fixes #106706

Epic: None
Release note (bug fix): a rare (!) situation in which nodes would get stuck
during start-up was addressed. This is unlikely to have been encountered by
production users This is unlikely to have been encountered by users. If so, it
would manifest itself through a stack frame sitting on a select in
`waitForAdditionalStoreInit` for extended periods of time (i.e. minutes).

### CODE REVIEW

File: pkg/server/server.go [hunk 1]
```diff
@@ -1900,13 +1900,20 @@ func (s *Server) PreStart(ctx context.Context) error {
...
+	s.nodeLiveness.Start(workersCtx)
+
 	// We'll block here until all stores are fully initialized. We do this here
 	// for two reasons:
 	// - some of the components below depend on all stores being fully
 	//   initialized (like the debug server registration for e.g.)
 	// - we'll need to do it after having opened up the RPC floodgates (due to
 	//   the hazard described in Node.start, around initializing additional
 	//   stores)
+	// - we'll need to do it after starting node liveness, see:
```
Comment (erikgrinaker) [inline pkg/server/server.go:1915]: nit: update "two reasons" to "three reason" above (or just "several reasons".

File: pkg/server/server.go [hunk 2]
```diff
@@ -1900,13 +1900,20 @@ func (s *Server) PreStart(ctx context.Context) error {
 	// initialized.
 	s.grpc.setMode(modeOperational)
 
+	// Begin the node liveness heartbeat. Add a callback which records the local
+	// store "last up" timestamp for every store whenever the liveness record is
+	// updated.
```
Comment (erikgrinaker) [inline pkg/server/server.go:1905]: I think the comment about the callback is stale here.

**Review by erikgrinaker — APPROVED** [review]
We don't need a release note, this was broken recently in #103601.

LGTM once comments on #107265 are addressed. Thanks!

**Comment by erikgrinaker** [comment]
> We don't need a release note, this was broken recently in #103601.

Nah, I might be wrong about that. I thought we moved the startup there, but looks like we didn't.

**Comment by tbg** [comment]
TFTR!

bors r=erikgrinaker
