### PR TITLE
kvserver: improve store.capacity allocations 

### LINKED ISSUE #167775: roachtest: kv/splits/nodes=3/quiesce=false/lease=expiration failed
**Note:** This build has runtime assertions enabled. If the same failure was hit in a run without assertions enabled, there should be a similar failure without this message. If there isn&#39;t one, then this failure is likely due to an assertion violation or (assertion) timeout.

roachtest.kv/splits/nodes=3/quiesce=false/lease=expiration [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/21300716?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/21300716?buildTab=artifacts#/kv/splits/nodes=3/quiesce=false/lease=expiration) on master @ [7e489320238b6feb3fcf94afa5727b7dff7cf51f](https://github.com/cockroachdb/cockroach/commits/7e489320238b6feb3fcf94afa5727b7dff7cf51f):

Failed with:

```
(cluster.go:2539).Run: full command output in run_144155.239018125_n4_cockroach-workload-r.log: COMMAND_PROBLEM: exit status 1
(monitor.go:267).Wait: monitor failure: monitor user task failed: t.Fatal() was called
test artifacts and logs in: /artifacts/kv/splits/nodes=3/quiesce=false/lease=expiration/run_1
```
Cluster Node to Ip Mapping:
| Node | Public IP | Private IP |
| --- | --- | --- |
| teamcity-21300716-1775543003-134-n4cpu4-0001 | 34.74.243.147 | 10.142.1.113 |
| teamcity-21300716-1775543003-134-n4cpu4-0002 | 34.75.72.242 | 10.142.1.112 |
| teamcity-21300716-1775543003-134-n4cpu4-0003 | 35.229.35.220 | 10.142.1.114 |
| teamcity-21300716-1775543003-134-n4cpu4-0004 | 34.23.237.208 | 10.142.0.2 |

Parameters:
 - <code>MetamorphicFilesystem=ext4</code>
 - <code>MetamorphicVolumeType=pd-ssd</code>
 - <code>arch=amd64</code>
 - <code>cloud=gce</code>
 - <code>coverageBuild=false</code>
 - <code>cpu=4</code>
 - <code>diskCount=0</code>
 - <code>encrypted=false</code>
 - <code>fs=ext4</code>
 - <code>localSSD=false</code>
 - <code>runtimeAssertionsBuild=true</code>
<details><summary>Help</summary>
<p>

See: [roachtest README](https://github.com/cockroachdb/cockroach/blob/master/pkg/cmd/roachtest/README.md)

See: [How To Investigate \(internal\)](https://cockroachlabs.atlassian.net/l/c/SSSBr8c7)

See: [Grafana](https://go.crdb.dev/roachtest-grafana/teamcity-21300716/kv-splits-nodes-3-quiesce-false-lease-expiration/1775572889360/1775575595506)

See: [Datadog Logs](https://us5.datadoghq.com/logs?query=service%3Aroachtest+%40cluster%3Ateamcity-21300716-1775543003-134-n4cpu4&from_ts=1775572889360&to_ts=1775575595506&live=false&storage=flex_tier)

</p>
</details>
/cc @cockroachdb/kv-triage
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*kv/splits/nodes=3/quiesce=false/lease=expiration.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/bazci/githubpost/issues)

</sub>

Jira issue: CRDB-62636

### PR DESCRIPTION
**Pull request by wenyihu6**
Epic: none 
Release note: none
Informs: #158288
Fixes: https://github.com/cockroachdb/cockroach/issues/167775

---
**kvserver: add BenchmarkReplicaAccumulator**

This commit adds a benchmark for ReplicaAccumulator.AddReplica to
measure the cost of replica ranking during Store.Capacity scans.
This exercises the heap insertion path that is called for every
replica on the store.

---
**kvserver: avoid interface boxing in replica ranking comparisons**

The replica accumulator's `val()` closure calls `RangeUsageInfo().Load().Dim(dim)`
on every heap comparison. `Load()` returns a `load.Vector` as the `load.Load`
interface, which boxes the `[2]float64` array on the heap each time. With 30k
replicas and 2 dimensions, the heap operations invoke `val()` ~180k+ times per
`Store.Capacity` scan.

This change adds `RangeUsageInfo.LoadDim()` which returns a single dimension
value directly as `float64`, bypassing the interface. The accumulator's `val()`
closure is updated to use it.

```
benchdiff --new=581804e8b667be04e648fb75b6730ab1d1f6a1e9 --old=68eb5349dfa28054c133309fe9ee2821aa2ec014  --post-checkout='bash post-checkout.sh' --run=BenchmarkReplicaAccumulator  --count=10 ./pkg/kv/kvserver

name                                  old time/op    new time/op    delta
ReplicaAccumulator/replicas=1000-12      544µs ±10%     337µs ± 6%  -38.07%  (p=0.000 n=10+9)
ReplicaAccumulator/replicas=30000-12    5.38ms ± 6%    3.46ms ± 1%  -35.68%  (p=0.000 n=9+9)
ReplicaAccumulator/replicas=10000-12    2.28ms ± 5%    1.48ms ± 3%  -35.17%  (p=0.000 n=10+9)
ReplicaAccumulator/replicas=128-12      40.9µs ± 8%    27.7µs ± 7%  -32.31%  (p=0.000 n=10+9)

name                                  old alloc/op   new alloc/op   delta
ReplicaAccumulator/replicas=1000-12      405kB ± 3%     105kB ± 0%  -74.08%  (p=0.000 n=10+10)
ReplicaAccumulator/replicas=10000-12    2.10MB ± 1%    0.97MB ± 0%  -53.87%  (p=0.000 n=10+10)
ReplicaAccumulator/replicas=30000-12    5.43MB ± 1%    2.89MB ± 0%  -46.79%  (p=0.000 n=10+9)
ReplicaAccumulator/replicas=128-12      38.5kB ± 3%    21.3kB ± 0%  -44.63%  (p=0.000 n=10+10)

name                                  old allocs/op  new allocs/op  delta
ReplicaAccumulator/replicas=1000-12      19.8k ± 3%      1.0k ± 0%  -94.84%  (p=0.000 n=10+10)
ReplicaAccumulator/replicas=128-12       1.22k ± 6%     0.15k ± 0%  -87.89%  (p=0.000 n=10+10)
ReplicaAccumulator/replicas=10000-12     80.7k ± 2%     10.0k ± 0%  -87.59%  (p=0.000 n=10+10)
ReplicaAccumulator/replicas=30000-12      189k ± 1%       30k ± 0%  -84.10%  (p=0.000 n=10+10)
```

---
**kvserver: add `BenchmarkReplicaRangeUsageInfo`**

This commit adds a benchmark for `Replica.RangeUsageInfo()`, which is
called per-replica during `Store.Capacity` scans. The benchmark
establishes a baseline for measuring the preceding optimizations
to the load stats retrieval path.

---
**kvserver: extract `getLockedWithNow` and `statsLockedWithNow`**

The `getLocked` method recomputes `timeutil.Unix(0, rl.clock.PhysicalNow())`
on every call. `Stats()` calls it 8 times under a single mutex hold,
producing 8 independent timestamps where one would suffice.

This change replaces `getLocked` with `getLockedWithNow`, which accepts
a pre-computed `time.Time`, and adds `statsLockedWithNow` to populate a
`ReplicaLoadStats` from a single timestamp. `Stats()` is updated to use
the new helper.

---
**kvserver: return `RatedSummary` by value**

`SnapshotRatedSummary` returns `*RatedSummary`, forcing a heap allocation
on every call. The method is not inlineable (its callers hold a mutex),
so the escape is unavoidable. `RatedSummary` is small enough to return
by value without concern.

This change switches `SnapshotRatedSummary` to return `RatedSummary` and
updates `RequestLocalityInfo` accordingly, eliminating one allocation per
replica during `Store.Capacity` scans.

---
**kvserver: combine mutex acquisitions in `RangeUsageInfo`**

`Replica.RangeUsageInfo()` acquires the `ReplicaLoad` mutex twice: once
via `LoadStats()` and once via `RequestLocalityInfo()`. During
`Store.Capacity` scans with 30k+ replicas, this doubles the lock
overhead per replica.

This change adds `StatsWithLocalityInfo()`, which acquires the mutex
once, computes the current time once, and returns both the load stats
and the locality summary. `Replica.RangeUsageInfo()` is updated to
use it.

Execution traces from kv/splits roachtest failures (#167775) show
the `ReplicaLoad` path as the most frequently recurring contributor
to scheduling latency spikes (6 of 10 worst). The longest-running
entries blocking other goroutines:

  `RequestLocalityInfo` -> `PerLocalityDecayingRate`   18-20ms
  `getLocked` -> `AverageRatePerSecond`                15ms
  `Capacity.func1` -> `LoadStats` -> `Stats`           16ms

```
benchdiff --new=2a7001d22023034ffefb124b8751c59270bc7934 --old= 14f968ea1532de3b73e4e668230803492b015cb8 --post-checkout='bash post-checkout.sh' --run=BenchmarkReplicaRangeUsageInfo --count=10 ./pkg/kv/kvserver

building benchmark binaries for 83e4584: kvserver: combine mutex acquisitions in `RangeUsag [bazel=false] 1/1 |
name                      old time/op    new time/op    delta
ReplicaRangeUsageInfo-12     549ns ±10%     471ns ± 4%  -14.26%  (p=0.000 n=9+9)

name                      old alloc/op   new alloc/op   delta
ReplicaRangeUsageInfo-12      296B ± 0%      272B ± 0%   -8.11%  (p=0.000 n=10+10)

name                      old allocs/op  new allocs/op  delta
ReplicaRangeUsageInfo-12      4.00 ± 0%      3.00 ± 0%  -25.00%  (p=0.000 n=10+10)
```

### CODE REVIEW

File: pkg/kv/kvserver/load/replica_load.go [hunk 1]
```diff
@@ -211,6 +211,19 @@ func (rl *ReplicaLoad) Stats() ReplicaLoadStats {
...
 
+// StatsWithLocalityInfo returns load stats and the Queries dimension's
+// locality info in a single locked operation. This avoids the overhead of
+// acquiring the mutex twice and computing the current time repeatedly,
+// which matters when called per-replica during Store.Capacity scans
+// (30k+ replicas).
+func (rl *ReplicaLoad) StatsWithLocalityInfo() (ReplicaLoadStats, replicastats.RatedSummary) {
+	rl.mu.Lock()
+	defer rl.mu.Unlock()
+	now := timeutil.Unix(0, rl.clock.PhysicalNow())
```
Comment (tbg) [inline pkg/kv/kvserver/load/replica_load.go]: does this need to be under the lock?

**Review by tbg — APPROVED** [review]
Nice!

File: pkg/kv/kvserver/load/replica_load.go (hunk 1 above)
Comment (wenyihu6) [reply pkg/kv/kvserver/load/replica_load.go]: Good call, done. Moved `now := timeutil.Unix(0, rl.clock.PhysicalNow())` before the mutex lock for other places as well.
