### PR TITLE
roachtest/cdc: ensure hydra endpoint is up

### LINKED ISSUE #122456: roachtest: cdc/kafka-oauth failed
I'm creating this issue manually because `hydra` fails with status 255, which is the same exit code we use to identify SSH flakes. In this case, however, the failure is not an SSH flake, but a legitimate test failure (thankfully, it seems like this is just a test bug).

For artifacts, see https://github.com/cockroachdb/cockroach/issues/90695#issuecomment-2051503141 and subsequent failures in the following runs.

The error happens when the following command is executed:

```
run_111029.305694316_n4_homeubuntuhydra-crea: 11:10:29 cluster.go:2432: > /home/ubuntu/hydra create oauth2-client -e http://localhost:4445 --grant-type client_credentials --token-endpoint-auth-method client_secret_basic --name "Test Client"
teamcity-14856548-1713246668-46-n4cpu4:[4]: /home/ubuntu/hydra create o...
Error: Post "http://localhost:4445/admin/clients": dial tcp 127.0.0.1:4445: connect: connection refused
Usage:
  hydra create oauth2-client [flags]
```

It seems that we should wait for the admin interface to be up before attempting to call this command.

Jira issue: CRDB-37895

### PR DESCRIPTION
**Pull request by rharding6373**
When we start hydra to enable oauth during roachtest testing, the admin endpoint may not have started before the create oauth client command is called, resulting in a test failure. This PR puts the create command in a retry loop with a timeout so that the command has a chance to succeed.

Fixes: #122456
Epic: None

Release note: None

### CODE REVIEW

File: pkg/cmd/roachtest/tests/cdc.go [hunk 1]
```diff
@@ -2398,11 +2398,27 @@ func (k kafkaManager) configureHydraOauth(ctx context.Context) (string, string)
...
-	result, err := k.c.RunWithDetailsSingleNode(ctx, k.t.L(), option.WithNodes(k.kafkaSinkNode), "/home/ubuntu/hydra create oauth2-client",
-		"-e", "http://localhost:4445",
-		"--grant-type", "client_credentials",
-		"--token-endpoint-auth-method", "client_secret_basic",
-		"--name", `"Test Client"`,
+
+	var result install.RunResultDetails
+	// The admin server may not be up immediately, so retry the create command
+	// until it succeeds or times out.
+	err = timeutil.RunWithTimeout(
```
Comment (renatolabs) [inline pkg/cmd/roachtest/tests/cdc.go:2405]: I think the `retry` package is a better fit for this: it will automatically apply some backoff instead of trying to run the command non-stop like is being done here (which `sshd` might not like).

**Review by renatolabs — APPROVED** [review]

**Review by wenyihu6 — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/123345#-:-NxDLQTa8HStfsj8jCcv:bnfp4nl)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @DarrylWong and @rharding6373)

**Comment by wenyihu6** [comment]
*[`pkg/cmd/roachtest/tests/cdc.go` line 2417 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/123345#-NxDLS083bCOwHxKq64y:-NxDLS083bCOwHxKq64z:bbbsd7n) ([raw file](https://github.com/cockroachdb/cockroach/blob/8d1be4076d3c2adda3e0094f5d125f1fd4950414/pkg/cmd/roachtest/tests/cdc.go#L2417)):*
> ```Go
> 					return nil
> 				}
> 				if err != nil && errors.Is(ctx.Err(), context.DeadlineExceeded) {
> ```

For education purposes, do you mind explaining to me when `context.DeadlineExceeded` would happen here?

**Comment by renatolabs** [comment]
Friendly ping.

**Review by rharding6373 — COMMENTED** [review]
Thanks for the ping. RFAL.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/123345#-:-Nxp236l4FGCmK8Yskyo:b-lyfkdp)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @DarrylWong, @renatolabs, and @wenyihu6)

___
*[`pkg/cmd/roachtest/tests/cdc.go` line 2405 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/123345#gh-1591037998:-Nxp0nHTAjTv2wYPudxb:bt4ox15) ([raw file](https://github.com/cockroachdb/cockroach/blob/8d1be4076d3c2adda3e0094f5d125f1fd4950414/pkg/cmd/roachtest/tests/cdc.go#L2405)):*
<details><summary><i>Previously, renatolabs (Renato Costa) wrote…</i></summary><blockquote>

I think the `retry` package is a better fit for this: it will automatically apply some backoff instead of trying to run the command non-stop like is being done here (which `sshd` might not like).
</blockquote></details>

Done. Thanks for the suggestion!
___
*[`pkg/cmd/roachtest/tests/cdc.go` line 2417 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/123345#-NxDLS083bCOwHxKq64y:-Nxp0pFP6lhfa-lcLwfx:bxq4h91) ([raw file](https://github.com/cockroachdb/cockroach/blob/8d1be4076d3c2adda3e0094f5d125f1fd4950414/pkg/cmd/roachtest/tests/cdc.go#L2417)):*
<details><summary><i>Previously, wenyihu6 (Wenyi Hu) wrote…</i></summary><blockquote>

For education purposes, do you mind explaining to me when `context.DeadlineExceeded` would happen here?
</blockquote></details>

Not really relevant with the revised implementation, but `context.DeadlineExceeded` would be the error returned once the timeout on the context occurred.

File: pkg/sql/plpgsql/parser/BUILD.bazel [hunk 2]
```diff
@@ -35,6 +35,7 @@ go_library(
     importpath = "github.com/cockroachdb/cockroach/pkg/sql/plpgsql/parser",
     visibility = ["//visibility:public"],
     deps = [
+        "//pkg/build",
```
Comment (renatolabs) [inline pkg/sql/plpgsql/parser/BUILD.bazel:38]: This seems unrelated.

**Review by renatolabs — APPROVED** [review]
I think the BUILD file was accidentally added to this commit, but otherwise LGTM!

**Comment by renatolabs** [comment]
blathers backport 24.1 23.2

**Comment by renatolabs** [comment]
Would be nice to backport this to 23.2 as well as it's been failing on that branch too.
