### PR TITLE
rangefeed: fix BenchmarkRangefeedBudget

### LINKED ISSUE #156748: pkg/kv/kvserver/rangefeed: BenchmarkRangefeedBudget failed
pkg/kv/kvserver/rangefeed.BenchmarkRangefeedBudget [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachprodMicrobenchmarkWeeklyWip/20685401?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachprodMicrobenchmarkWeeklyWip/20685401?buildTab=artifacts#./artifacts/microbench/experiment) on master @ [cc61b3c16062dfeef5ee82e6a80d868d499e047e](https://github.com/cockroachdb/cockroach/commits/cc61b3c16062dfeef5ee82e6a80d868d499e047e):

Fatal error:

```
panic: unknown rangefeed test type

```
Stack: 

```
goroutine 55 gp=0xc000602f00 m=3 mp=0xc0000d3008 [running]:
panic({0x22fc640?, 0x2d31af0?})
	GOROOT/src/runtime/panic.go:802 +0x168 fp=0xc0005e7880 sp=0xc0005e77d0 pc=0x49f2a8
github.com/cockroachdb/cockroach/pkg/kv/kvserver/rangefeed.newTestProcessor({0x2d8ce60, 0xc000710588}, {0xc0005e7d80, 0x5, 0x0?})
	pkg/kv/kvserver/rangefeed/processor_helpers_test.go:457 +0x870 fp=0xc0005e7ae8 sp=0xc0005e7880 pc=0x1f54b50
github.com/cockroachdb/cockroach/pkg/kv/kvserver/rangefeed.runBenchmarkRangefeed(0xc000710588, {{0x0, 0x0}, {0x27e7421, 0x5}, 0x1, 0x0})
	pkg/kv/kvserver/rangefeed/bench_test.go:92 +0x2c5 fp=0xc0005e7e98 sp=0xc0005e7ae8 pc=0x1f3fc05
github.com/cockroachdb/cockroach/pkg/kv/kvserver/rangefeed.BenchmarkRangefeedBudget.func1(0xc000710588?)
	pkg/kv/kvserver/rangefeed/bench_test.go:71 +0x75 fp=0xc0005e7f10 sp=0xc0005e7e98 pc=0x1f3f915
testing.(*B).runN(0xc000710588, 0x1)
	GOROOT/src/testing/benchmark.go:219 +0x190 fp=0xc0005e7fa0 sp=0xc0005e7f10 pc=0x59ab10
testing.(*B).run1.func1()
	GOROOT/src/testing/benchmark.go:245 +0x48 fp=0xc0005e7fe0 sp=0xc0005e7fa0 pc=0x59b188
runtime.goexit({})
	src/runtime/asm_amd64.s:1693 +0x1 fp=0xc0005e7fe8 sp=0xc0005e7fe0 pc=0x4a7d81
created by testing.(*B).run1 in goroutine 29
	GOROOT/src/testing/benchmark.go:238 +0x90
```
<details><summary>Log preceding fatal error</summary>
<p>

```
goos: linux
goarch: amd64
cpu: Intel(R) Xeon(R) CPU @ 2.60GHz
BenchmarkRangefeedBudget
BenchmarkRangefeedBudget/budget=false

```
</p>
</details>
<details><summary>Help</summary>
<p>

See also: [How To Investigate a Go Test Failure \(internal\)](https://cockroachlabs.atlassian.net/l/c/HgfXfJgM)
</p>
</details>
/cc @cockroachdb/kv-triage
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*BenchmarkRangefeedBudget.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/bazci/githubpost/issues)

</sub>

Jira issue: CRDB-56167

### PR DESCRIPTION
**Pull request by stevendanna**
This benchmark was broken in f4d1c07f1bed85346051197e414e71941c7c2015 but was not noticed becuase benchmarks aren't run in CI.

Fixes #156748
Release note: none

### CODE REVIEW

**Comment by stevendanna** [comment]
Proof it works:

```
> ./dev bench ./pkg/kv/kvserver/rangefeed/ --filter BenchmarkRangefeedBudget
$ bazel test pkg/kv/kvserver/rangefeed:all --nocache_test_results --test_arg -test.run=- --test_arg -test.bench=BenchmarkRangefeedBudget --test_sharding_strategy=disabled --test_arg -test.cpu --test_arg 1 --test_arg -test.benchmem --crdb_test_off --crdb_bench --test_env COCKROACH_TEST_FIXTURES_DIR=/Users/ssd/Library/Caches/crdb-test-fixtures --sandbox_writable_path=/Users/ssd/Library/Caches/crdb-test-fixtures --test_output streamed
INFO: Invocation ID: e3163e43-c653-48b6-b5f5-923b6630ca3c
WARNING: Streamed test output requested. All tests will be run locally, without sharding, one at a time
INFO: Analyzed 2 targets (0 packages loaded, 2 targets configured).
goos: darwin
goarch: arm64
cpu: Apple M1 Pro
BenchmarkRangefeedBudget/budget=false/proc=unbuffered_sender             1853752               637.0 ns/op           427 B/op          7 allocs/op
BenchmarkRangefeedBudget/budget=false/proc=buffered_sender               1832642               697.8 ns/op           422 B/op          7 allocs/op
BenchmarkRangefeedBudget/budget=true/proc=unbuffered_sender              1599313               755.6 ns/op           438 B/op          7 allocs/op
BenchmarkRangefeedBudget/budget=true/proc=buffered_sender                1657382               725.6 ns/op           440 B/op          7 allocs/op
PASS
INFO: Found 1 target and 1 test target...
INFO: Elapsed time: 10.589s, Critical Path: 10.03s
INFO: 2 processes: 1 internal, 1 darwin-sandbox.
INFO: Build completed successfully, 2 total actions
//pkg/kv/kvserver/rangefeed:rangefeed_test                               PASSED in 9.9s
```

File: pkg/kv/kvserver/rangefeed/bench_test.go [hunk 1]
```diff
@@ -63,17 +63,20 @@ func BenchmarkRangefeed(b *testing.B) {
...
-		b.Run(fmt.Sprintf("budget=%t", budget), func(b *testing.B) {
-			var budgetSize int64
-			if budget {
-				budgetSize = math.MaxInt64
-			}
-			runBenchmarkRangefeed(b, benchmarkRangefeedOpts{
-				opType:           writeOpType,
-				numRegistrations: 1,
-				budget:           budgetSize,
+		for _, procType := range testTypes {
```
Comment (pav-kv) [inline pkg/kv/kvserver/rangefeed/bench_test.go:66]: nit: make `testTypes` the outer loop, like in the test above?

**Review by pav-kv — APPROVED** [review]

File: pkg/kv/kvserver/rangefeed/bench_test.go (hunk 1 above)
Comment (pav-kv) [reply pkg/kv/kvserver/rangefeed/bench_test.go:66]: Feel free to ignore. Looks like the "centrepiece" in this test is the "budget" thing.

**Comment by stevendanna** [comment]
TFTR!

I think I'll keep the ordering since, as you mention, it seems the budget is the "main" issue bit of this benchmark.

bors r=pav-kv
