### PR TITLE
rangefeed: track testing caughtUp state with an atomic

### LINKED ISSUE #136544: kv/kvserver/rangefeed: TestProcessorBackpressure failed
kv/kvserver/rangefeed.TestProcessorBackpressure [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Ci_TestsAwsLinuxArm64_UnitTests/18007415?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Ci_TestsAwsLinuxArm64_UnitTests/18007415?buildTab=artifacts#/) on master @ [c14af3c5756e94ca09a0dff809ac20fb97549980](https://github.com/cockroachdb/cockroach/commits/c14af3c5756e94ca09a0dff809ac20fb97549980):

Fatal error:

```
panic: test timed out after 5m0s
running tests:
	TestProcessorBackpressure (4m59s)
	TestProcessorBackpressure/feed_type=scheduled (4m59s)

```
Stack: 

```
goroutine 527 [running]:
testing.(*M).startAlarm.func1()
	GOROOT/src/testing/testing.go:2366 +0x30c
created by time.goFunc
	GOROOT/src/time/sleep.go:177 +0x38
```
<details><summary>Log preceding fatal error</summary>
<p>

```
=== RUN   TestProcessorBackpressure
=== RUN   TestProcessorBackpressure/feed_type=scheduled
```
</p>
</details>
<details><summary>Help</summary>
<p>

See also: [How To Investigate a Go Test Failure \(internal\)](https://cockroachlabs.atlassian.net/l/c/HgfXfJgM)
</p>
</details>
/cc @cockroachdb/kv
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*TestProcessorBackpressure.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/bazci/githubpost/issues)

</sub>

Jira issue: CRDB-45112

### PR DESCRIPTION
**Pull request by stevendanna**
The caughtUp variable is used in tests to assure that the rangefeed has sent all of its messages to the sender. However, it was subject to a race condition in which the testing-only blocking write path would set catchUp to false _after_ the event had been handled because this testing variable and other variables shared the same mutex.

We increment the counter on every push into the buffer and decrement it after the stream send has succeeded. In the blocking case that was buggy before, it is possible that the counter is temporarily -1, but this doesn't pose a problem.

Epic: none

Fixes #136544

Release note: None

### CODE REVIEW

File: pkg/kv/kvserver/rangefeed/buffered_registration.go [hunk 1]
```diff
@@ -318,7 +318,7 @@ func (br *bufferedRegistration) waitForCaughtUp(ctx context.Context) error {
 	}
 	for re := retry.StartWithCtx(ctx, opts); re.Next(); {
 		br.mu.Lock()
```
Comment (andrewbaptist) [inline pkg/kv/kvserver/rangefeed/buffered_registration.go:320]: nit: This locking doesn't seem necessary anymore.

File: pkg/kv/kvserver/rangefeed/buffered_registration.go [hunk 2]
```diff
@@ -65,6 +63,10 @@ type bufferedRegistration struct {
 		// that disconnect is called, it is closed by disconnect.
 		catchUpIter *CatchUpIterator
 	}
+
+	// Number of events that have been written to the buffer but
+	// not sent. Used only for testing.
+	testPendingEventToSend atomic.Int64
```
Comment (andrewbaptist) [inline pkg/kv/kvserver/rangefeed/buffered_registration.go:69]: nit: I'd recommend not calling this `test` since it is read by the non-test method`waitForCaughtUp`. Instead maybe just mark as internal?

Reading the code more, it appears `waitForCaughtUp` is only used in tests as well, so this is probably OK, although consider adding a comment to that method to mention that it is only used in tests. Then it would be OK to leave the variable as a `test` name.

**Review by andrewbaptist — APPROVED** [review]
LGTM

A couple minor nits, but this looks good structurally.

**Comment by stevendanna** [comment]
bors r=andrewbaptist
