### PR TITLE
ttl: fix incorrect roachpb.RKey decoding error output

### LINKED ISSUE #90707: ttl: incorrect roachpb.RKey decoding error output
Currently we are incorrectly outputting `RKey` values when decoding them in the TTL job:
`fmt.Sprintf("%x", rKey))` incorrectly outputs a hex encoded string of the pretty print output of a `RKey` (via `RKey.String()`).
`fmt.Sprintf("%x", []byte(rKey)))` correctly outputs a hex encoded string of the `RKey` `[]byte` itself.

Jira issue: CRDB-20900

### PR DESCRIPTION
**Pull request by ecwall**
fixes https://github.com/cockroachdb/cockroach/issues/90707

`fmt.Sprintf("%x", rKey))` incorrectly outputs a hex encoded string of the pretty print output of a RKey (via RKey.String()). `fmt.Sprintf("%x", []byte(rKey)))` correctly outputs a hex encoded string of the RKey []byte itself.

Release note (bug fix): TTL decoding error messages now correctly contain hex encoded key bytes instead of hex encoded key pretty print output.

### CODE REVIEW

File: pkg/sql/ttl/ttljob/ttljob_processor.go [hunk 1]
```diff
@@ -387,40 +387,44 @@ func (t *ttlProcessor) runTTLOnSpan(
 
 // keyToDatums translates a RKey on a span for a table to the appropriate datums.
 func keyToDatums(
-	key roachpb.RKey, codec keys.SQLCodec, pkTypes []*types.T, alloc *tree.DatumAlloc,
+	rKey roachpb.RKey, codec keys.SQLCodec, pkTypes []*types.T, alloc *tree.DatumAlloc,
```
Comment (ecwall) [inline pkg/sql/ttl/ttljob/ttljob_processor.go:390]: Also rename the confusingly named `key` (which is a RKey) to `rKey` and `rKey` (which is a Key) to `key` to match their types.

**Review by rafiss — APPROVED** [review]
lgtm! btw, you could fix the issue link, since the PR is linked to itself right now

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/90710#-:-NFKENLQ69zjZnJEmKZ1:bnw27vo)* status: :shipit: complete! 0 of 0 LGTMs obtained

**Comment by ecwall** [comment]
bors r=rafiss
