### PR TITLE
bulkio: Fix transaction semantics in job scheduler.

### LINKED ISSUE #52959: jobs: TestJobSchedulerDaemonProcessesJobs failed
[(jobs).TestJobSchedulerDaemonProcessesJobs failed](https://teamcity.cockroachdb.com/viewLog.html?buildId=2190017&tab=buildLog) on [master@3ea329fa4e3d52dcfb9fc92ecd5c9229b8942b97](https://github.com/cockroachdb/cockroach/commits/3ea329fa4e3d52dcfb9fc92ecd5c9229b8942b97):

```
=== RUN   TestJobSchedulerDaemonProcessesJobs
test logs left over in: /go/src/github.com/cockroachdb/cockroach/artifacts/logTestJobSchedulerDaemonProcessesJobs668446127
--- FAIL: TestJobSchedulerDaemonProcessesJobs (1.17s)
    test_log_scope.go:154: test logs captured to: /go/src/github.com/cockroachdb/cockroach/artifacts/logTestJobSchedulerDaemonProcessesJobs668446127
    test_log_scope.go:63: use -show-logs to present logs inline
    job_scheduler_test.go:379: 
        	Error Trace:	job_scheduler_test.go:379
        	Error:      	Not equal: 
        	            	expected: int(5)
        	            	actual  : int64(0)
        	Test:       	TestJobSchedulerDaemonProcessesJobs

```

<details><summary>More</summary><p>
Parameters:

- GOFLAGS=-json

```
make stressrace TESTS=TestJobSchedulerDaemonProcessesJobs PKG=./pkg/jobs TESTTIMEOUT=5m STRESSFLAGS='-timeout 5m' 2>&1
```

[See this test on roachdash](https://roachdash.crdb.dev/?filter=status%3Aopen+t%3A.%2ATestJobSchedulerDaemonProcessesJobs.%2A&sort=title&restgroup=false&display=lastcommented+project)
<sub>powered by [pkg/cmd/internal/issues](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)</sub></p></details>

### LINKED ISSUE #53033: bulkio: Incorrect transaction semantics in job_scheduler
Job scheduler does not use transactions correctly, and this can lead to deadlocks.
In particular, the query to find schedules to run does not use transaction; yet the updates
to schedules are done under txn.  This can lead to a stuck process if the transaction retries
after any changes have been made to any of the schedules.

In addition, currently, a single schedule with any sort of error (planning, etc) would lead to the
entire scheduler loop to be undone.

### PR DESCRIPTION
**Pull request by miretskiy**
Fixes #53033
Fixes #52959 

Use transaction when querying for the schedules to run.
In addition, ensure that a single bad schedule does not cause
all of the previous work to be wasted by using transaction savepoints.

Release Notes: None

### CODE REVIEW

File: pkg/jobs/job_scheduler.go [hunk 1]
```diff
@@ -252,8 +254,20 @@ func (s *jobScheduler) executeSchedules(
 			continue
 		}
 
+		sp, err := txn.CreateSavepoint(ctx)
```
Comment (dt) [inline pkg/jobs/job_scheduler.go:257]: @knz or @nvanbenschoten can you just double-check we're using the Savepoint API correctly?

**Review by dt — APPROVED** [review]

**Review by knz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/53049)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @nvanbenschoten)

___
*[pkg/jobs/job_scheduler.go, line 257 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/53049#-MF6VxWFXOeugCTVB9ve-r1-257:-MF6XusC9UnyfPA1gHRM:bbo24ik) ([raw file](https://github.com/cockroachdb/cockroach/blob/4f7759928b34c2b018cddd8d416bbdbfd8fa86e0/pkg/jobs/job_scheduler.go#L257)):*
<details><summary><i>Previously, dt (David Taylor) wrote…</i></summary><blockquote>

@knz or @nvanbenschoten can you just double-check we're using the Savepoint API correctly?
</blockquote></details>

looks good
