### PR TITLE
sql: fix IS NAN syntax type-checking

### LINKED ISSUE #63940: sql/tests: TestRandomSyntaxFuncCommon failed
sql/tests.TestRandomSyntaxFuncCommon [failed](https://teamcity.cockroachdb.com/viewLog.html?buildId=2903571&tab=buildLog) with [artifacts](https://teamcity.cockroachdb.com/viewLog.html?buildId=2903571&tab=artifacts#/) on master @ [09be4f72a054cf66ef603b1e4525844c9ef547fc](https://github.com/cockroachdb/cockroach/commits/09be4f72a054cf66ef603b1e4525844c9ef547fc):

Fatal error:

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x1913e99]

```
Stack: 

```
goroutine 5888145 [running]:
github.com/cockroachdb/cockroach/pkg/sql/parser.(*lexer).populateErrorDetails(0xc000d90030)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/parser/lexer.go:230 +0x699
github.com/cockroachdb/cockroach/pkg/sql/parser.(*lexer).setErr(0xc000d90030, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/parser/lexer.go:210 +0x5c
github.com/cockroachdb/cockroach/pkg/sql/parser.setErr(0x5bde980, 0xc000d90030, 0x0, 0x0, 0x8)
	sql-gen.y:40 +0x50
github.com/cockroachdb/cockroach/pkg/sql/parser.(*sqlParserImpl).Parse(0xc000d90098, 0x5bde980, 0xc000d90030, 0x0)
	sql-gen.y:10833 +0x6b4a5
github.com/cockroachdb/cockroach/pkg/sql/parser.(*Parser).parse(0xc000d90000, 0x2, 0xc0060636c0, 0x39, 0xc000db4000, 0x12, 0x20, 0x7d62420, 0x0, 0x0, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/parser/parse.go:188 +0x175
github.com/cockroachdb/cockroach/pkg/sql/parser.(*Parser).parseWithDepth(0xc000d90000, 0x1, 0xc0060636c0, 0x39, 0x7d62420, 0x0, 0x0, 0x0, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/parser/parse.go:168 +0x1d1
github.com/cockroachdb/cockroach/pkg/sql/parser.Parse(...)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/parser/parse.go:237
github.com/cockroachdb/cockroach/pkg/sql/tests_test.verifyFormat(0xc0060636c0, 0x39, 0x32, 0x73)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/tests/rsg_test.go:57 +0x7c
github.com/cockroachdb/cockroach/pkg/sql/tests_test.(*verifyFormatDB).exec(0xc01fa78840, 0xc01fbb0780, 0x5c36580, 0xc00175df40, 0xc0060636c0, 0x39, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/tests/rsg_test.go:125 +0x73
github.com/cockroachdb/cockroach/pkg/sql/tests_test.TestRandomSyntaxFuncCommon.func1(0x5c36580, 0xc00175df40, 0xc01fa78840, 0xc01ab5c2e0, 0x5b94f00, 0xc0192cd760)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/tests/rsg_test.go:355 +0x105
github.com/cockroachdb/cockroach/pkg/sql/tests_test.testRandomSyntax.func3(0x5c36580, 0xc00175df40, 0x1, 0x15dbce2, 0x5c365c0)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/tests/rsg_test.go:748 +0xc7
github.com/cockroachdb/cockroach/pkg/util/ctxgroup.GroupWorkers.func1(0x5c36580, 0xc00175df40, 0xc012612200, 0x7000000054b5b60)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/ctxgroup/ctxgroup.go:175 +0x42
github.com/cockroachdb/cockroach/pkg/util/ctxgroup.Group.GoCtx.func1(0xc012612200, 0x54b5b60)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/ctxgroup/ctxgroup.go:166 +0x3a
golang.org/x/sync/errgroup.(*Group).Go.func1(0xc01837faa0, 0xc01837fb00)
	/go/src/github.com/cockroachdb/cockroach/vendor/golang.org/x/sync/errgroup/errgroup.go:57 +0x59
created by golang.org/x/sync/errgroup.(*Group).Go
	/go/src/github.com/cockroachdb/cockroach/vendor/golang.org/x/sync/errgroup/errgroup.go:54 +0x66
```
<details><summary>Log preceding fatal error</summary>
<p>

```
=== RUN   TestRandomSyntaxFuncCommon
    test_log_scope.go:73: test logs captured to: /go/src/github.com/cockroachdb/cockroach/artifacts/logTestRandomSyntaxFuncCommon077978143
    test_log_scope.go:74: use -show-logs to present logs inline
    rsg_test.go:731: 5s of 5m0s: 4416 executions, 60 successful
    rsg_test.go:731: 10s of 5m0s: 8526 executions, 87 successful
    rsg_test.go:731: 15s of 5m0s: 12560 executions, 117 successful
    rsg_test.go:731: 20s of 5m0s: 16578 executions, 151 successful
    rsg_test.go:731: 25s of 5m0s: 20507 executions, 182 successful
    rsg_test.go:731: 30s of 5m0s: 24313 executions, 200 successful
    rsg_test.go:731: 35s of 5m0s: 28236 executions, 228 successful
    rsg_test.go:731: 40s of 5m0s: 32059 executions, 247 successful
    rsg_test.go:731: 45s of 5m0s: 35829 executions, 269 successful
    rsg_test.go:731: 50s of 5m0s: 39605 executions, 294 successful
    rsg_test.go:731: 55s of 5m0s: 43232 executions, 328 successful
    rsg_test.go:731: 1m0s of 5m0s: 46957 executions, 350 successful
    rsg_test.go:731: 1m5s of 5m0s: 50557 executions, 371 successful
    rsg_test.go:731: 1m10s of 5m0s: 54143 executions, 397 successful
    rsg_test.go:731: 1m15s of 5m0s: 57768 executions, 419 successful
    rsg_test.go:731: 1m20s of 5m0s: 61452 executions, 447 successful
    rsg_test.go:731: 1m25s of 5m0s: 65042 executions, 471 successful
    rsg_test.go:731: 1m30s of 5m0s: 68569 executions, 489 successful
    rsg_test.go:731: 1m35s of 5m0s: 72004 executions, 506 successful
    rsg_test.go:731: 1m40s of 5m0s: 75482 executions, 533 successful
    rsg_test.go:731: 1m45s of 5m0s: 79019 executions, 552 successful
    rsg_test.go:731: 1m50s of 5m0s: 82539 executions, 574 successful
    rsg_test.go:731: 1m55s of 5m0s: 86078 executions, 598 successful
    rsg_test.go:731: 2m0s of 5m0s: 89642 executions, 615 successful
    rsg_test.go:731: 2m5s of 5m0s: 93112 executions, 632 successful
```
</p>
</details>
<details><summary>Reproduce</summary>
<p>
<p>To reproduce, try:

```bash
make stressrace TESTS=TestRandomSyntaxFuncCommon PKG=./pkg/sql/tests TESTTIMEOUT=5m STRESSFLAGS='-timeout 5m' 2>&1
```
</p>
</p>
</details>
<details><summary>Internal log</summary>
<p>

```
mjibson marked as alumn{us/a}; resolving to rafiss instead
```
</p>
</details>

/cc @rafiss
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*TestRandomSyntaxFuncCommon.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)
</sub>

### LINKED ISSUE #72257: sql/tests: TestRandomSyntaxSelect failed
sql/tests.TestRandomSyntaxSelect [failed](https://teamcity.cockroachdb.com/viewLog.html?buildId=3658630&tab=buildLog) with [artifacts](https://teamcity.cockroachdb.com/viewLog.html?buildId=3658630&tab=artifacts#/) on master @ [db229cad354c2776ea35c9dc4f78e6ce66b9437c](https://github.com/cockroachdb/cockroach/commits/db229cad354c2776ea35c9dc4f78e6ce66b9437c):

Random syntax error:

```
    rsg_test.go:781: Crash detected: server panic: pq: internal error: comparison overload not found (eq, tuple, string)
```
Query:

```
        SELECT ROW ( ) IS NAN AS EXTRACT_DURATION FROM ident ;
```
<details><summary>Help</summary>
<p>
See also: [How To Investigate a Go Test Failure \(internal\)](https://cockroachlabs.atlassian.net/l/c/HgfXfJgM)</p>
</details>
<details><summary>Same failure on other branches</summary>
<p>

- #64396 sql/tests: TestRandomSyntaxSelect failed [C-test-failure O-robot T-sql-experience branch-release-21.1]
</p>
</details>
<details><summary>Internal log</summary>
<p>

```
mjibson marked as alumn{us/a}; resolving to rafiss instead
```
</p>
</details>

/cc @cockroachdb/sql-experience rafiss
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*TestRandomSyntaxSelect.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)
</sub>

### PR DESCRIPTION
**Pull request by rafiss**
fixes https://github.com/cockroachdb/cockroach/issues/63940
fixes https://github.com/cockroachdb/cockroach/issues/72257

Previously using the IS NAN syntax with tuples would cause a
type-checking error. The NAN was treated as a constant string val, which
would be coerced into a tuple. To avoid this, the NAN is now treated as
a constant NumVal.

No release note since this bug was never released. The bug was only
revealed after we started allowing string->tuple casts.

Release note: None

### CODE REVIEW

File: pkg/sql/sem/tree/constant.go [hunk 1]
```diff
@@ -168,6 +168,8 @@ func (expr *NumVal) Format(ctx *FmtCtx) {
 	s := expr.origString
 	if s == "" {
 		s = expr.value.String()
+	} else if strings.EqualFold(s, "NaN") {
+		s = "'NaN'"
```
Comment (otan) [inline pkg/sql/sem/tree/constant.go:172]: you need to check `FmtBareIdentifiers` to print the `'` though, right?

**Review by otan — APPROVED** [review]

File: pkg/sql/sem/tree/constant.go (hunk 1 above)
Comment (rafiss) [reply pkg/sql/sem/tree/constant.go:172]: in this case it'd be `FmtParsableNumerics`

but i don't think we want it here -- I think a `NaN` NumVal can only appear in the context of formatting a query string. if we normalized `SELECT a IS NAN` into `SELECT a = NaN` it would actually be a syntax error.

**Comment by rafiss** [comment]
tftr!

bors r=otan
