### PR TITLE
sql: fix swallowing of errors in planVisitor

### LINKED ISSUE #12850: benchmarks: panic: attempting to move SQL txn to state NoTxn inconsistent with KV txn state: PENDING
Looks like BenchmarkBank2_Cockroach-16 produces a panic in the nightly benchmark tests. From `sql.test.stderr` in https://teamcity.cockroachdb.com/viewLog.html?buildId=114365&buildTypeId=Cockroach_BenchmarkTests&tab=artifacts:

```
panic: attempting to move SQL txn to state NoTxn inconsistent with KV txn state: PENDING (finalized: false) [recovered]
	panic: 
UPDATE bench.bank
  SET balance = CASE id WHEN $1 THEN balance-$3 WHEN $2 THEN balance+$3 END
  WHERE id IN ($1, $2) AND (SELECT balance >= $3 FROM bench.bank WHERE id = $1): attempting to move SQL txn to state NoTxn inconsistent with KV txn state: PENDING (finalized: false) [recovered]
	panic: 
UPDATE bench.bank
  SET balance = CASE id WHEN $1 THEN balance-$3 WHEN $2 THEN balance+$3 END
  WHERE id IN ($1, $2) AND (SELECT balance >= $3 FROM bench.bank WHERE id = $1): attempting to move SQL txn to state NoTxn inconsistent with KV txn state: PENDING (finalized: false)

goroutine 411743 [running]:
panic(0x189eee0, 0xc424781a50)
	/usr/local/go/src/runtime/panic.go:500 +0x1a1
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).Recover(0xc422b82000)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:185 +0x6e
panic(0x189eee0, 0xc424781a50)
	/usr/local/go/src/runtime/panic.go:458 +0x243
github.com/cockroachdb/cockroach/pkg/sql.(*Executor).ExecuteStatements.func1(0xc421009001, 0xae)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/executor.go:455 +0x149
panic(0x1857280, 0xc424781a30)
	/usr/local/go/src/runtime/panic.go:458 +0x243
github.com/cockroachdb/cockroach/pkg/sql.(*txnState).resetStateAndTxn(0xc421375668, 0x0)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/session.go:360 +0x3dc
github.com/cockroachdb/cockroach/pkg/sql.(*Executor).execRequest(0xc421d669a0, 0xc421375600, 0xc421009001, 0xae, 0x0, 0x0, 0x0, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/executor.go:689 +0xcf8
github.com/cockroachdb/cockroach/pkg/sql.(*Executor).ExecuteStatements(0xc421d669a0, 0xc421375600, 0xc421009001, 0xae, 0xc423d19410, 0x0, 0x0, 0x0, 0x632900)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/executor.go:461 +0x11f
github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*v3Conn).executeStatements(0xc421230c00, 0x7f1700249400, 0xc4251cdda0, 0xc421009001, 0xae, 0xc423d19410, 0x2b9fbc8, 0x0, 0x0, 0xc420f61000, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/pgwire/v3.go:792 +0x94
github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*v3Conn).handleExecute(0xc421230c00, 0x7f1700249400, 0xc4251cdda0, 0xc421230c28, 0x9, 0x0)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/pgwire/v3.go:778 +0x20a
github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*v3Conn).serve(0xc421230c00, 0x7f1700249400, 0xc4251cdda0, 0x5400, 0xc420ae82f8, 0x7f1700249400, 0xc42363e300, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/pgwire/v3.go:420 +0xc70
github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*Server).ServeConn(0xc420ae81c0, 0x7f1700249400, 0xc42363e300, 0x2686460, 0xc422f18000, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/pgwire/server.go:309 +0x999
github.com/cockroachdb/cockroach/pkg/server.(*Server).Start.func8.1(0x26873c0, 0xc4231604d0)
	/go/src/github.com/cockroachdb/cockroach/pkg/server/server.go:522 +0x106
github.com/cockroachdb/cockroach/pkg/util/netutil.(*Server).ServeWith.func1(0xc422b82000, 0xc4214c0060, 0x26873c0, 0xc4231604d0, 0xc42299a620)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/netutil/net.go:136 +0x95
created by github.com/cockroachdb/cockroach/pkg/util/netutil.(*Server).ServeWith
	/go/src/github.com/cockroachdb/cockroach/pkg/util/netutil/net.go:138 +0x277
```

### PR DESCRIPTION
**Pull request by andreimatei**
Before this patch, planVisitor.visit() used to make a copy of itself for
visiting the current node and recursing. That caused errors encountered
in this process to nod be saved in the original visitor.err, and thus
not returned from walkPlan().
The only reason for this copy was so that "attrs" were prepended with
the node name; that can be achieved by directly passing the current node
name around.

Fixes #12850

cc @knz

---
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/13004)

### CODE REVIEW

File: pkg/sql/subquery.go [hunk 1]
```diff
@@ -174,12 +170,12 @@ func (s *subquery) doEval() (result parser.Datum, err error) {
...
 			}
 			another, err := s.plan.Next()
-			if s.err = err; err != nil {
+			if err != nil {
 				return result, err
 			}
 			if another {
-				s.err = fmt.Errorf("more than one row returned by a subquery used as an expression")
-				return result, s.err
+				err = fmt.Errorf("more than one row returned by a subquery used as an expression")
```
Comment (RaduBerinde) [inline pkg/sql/subquery.go]: [nit] `return result, fmt.Errorf()`, or at least use `err := `

File: pkg/sql/subquery_test.go [hunk 2]
```diff
@@ -0,0 +1,48 @@
...
+
+import (
+	"testing"
+
+	"github.com/cockroachdb/cockroach/pkg/sql/parser"
+	"github.com/cockroachdb/cockroach/pkg/testutils"
+	"github.com/cockroachdb/cockroach/pkg/util/leaktest"
+)
+
+// Test that starting the subqueries return an error if the evaluation of a
```
Comment (RaduBerinde) [inline pkg/sql/subquery_test.go]: returns

**Review by RaduBerinde — APPROVED** [review]
Great! Thanks for fixing, LGTM!

**Comment by tamird** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

*[pkg/sql/subquery_test.go, line 45 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/13004#-KatpSIXiHKjB2g3JyAA:-KatpSIXiHKjB2g3JyAB:b-sghe46) ([raw file](https://github.com/cockroachdb/cockroach/blob/f5c2a188a31c7a8b391190cd025af4991b6ad061/pkg/sql/subquery_test.go#L45)):*
> ```Go
> 		t.Fatal(err)
> 	}
> 	if err := p.startSubqueryPlans(plan); !testutils.IsError(err, "forced by crdb_internal.force_retry()") {
> ```

note that this string is a regular expression, so you might want to write `"forced by crdb_internal\.force_retry\(\)"`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/13004)*

**Comment by knz** [comment]
Please fork the subquery-related change into a separate commit/PR; this one is good to go.

Also please separate the fix to the primary bug at hand here from your "refactoring" that removes the visitor copy.
The bug needs to be fixed and a simple propagation of the err field is sufficient to fix it (and that fix would be good to go right away).

Regarding the last part, where you removed the visitor copy. I think it is interesting to remove the visitor copy but I think you erred too far in the opposite direction. The code after your change is far less readable and maintainable than it was before. Please consider the alternative to use a `curNodeName` field in the visitor and have it updated properly by the `visit` method.

---

Reviewed 2 of 3 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/13004#-:-Kb5RaFn-oK7JcrO0I2O:bjmgmo2)*

**Comment by knz** [comment]
(In case that wasn't clear, this PR is not yet gtg as-is imho)

**Comment by RaduBerinde** [comment]
I disagree that the code is less readable and maintainable - it's much clearer like this compared to using internal state with non-trivial semantics. Having a `curNodeName` field in the visitor means that it's only valid to call the methods that use it until the first recursive call to `visit` (which is a fairly subtle limitation). I don't oppose doing it that way as long as the limitations are documented properly though.

---

Review status: all files reviewed at latest revision, 5 unresolved discussions, all commit checks successful.

---

*[pkg/sql/walk.go, line 81 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/13004#-Kb6wvD-wEHK-KvijsQi:-Kb6wvD-wEHK-KvijsQj:b-dhuh81) ([raw file](https://github.com/cockroachdb/cockroach/blob/f5c2a188a31c7a8b391190cd025af4991b6ad061/pkg/sql/walk.go#L81)):*
> ```Go
> 	}
> 
> 	curNodeName := nodeName(plan)
> ```

name could be shorter, like `name`

---

*[pkg/sql/walk.go, line 377 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/13004#-Kb6vRk6DQW3UZAzIfrI:-Kb6vRk72gRIgJJm4PfV:b-lbu2b2) ([raw file](https://github.com/cockroachdb/cockroach/blob/f5c2a188a31c7a8b391190cd025af4991b6ad061/pkg/sql/walk.go#L377)):*
> ```Go
> }
> 
> // attr wraps observer.attr() and provides it with the current node's name.
> ```

The comment about the current node's name doesn't make sense anymore.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/13004#-:-Kb6vtbpDAVzc-4XYOG8:bqqdirz)*

**Comment by andreimatei** [comment]
Raphael, I moved the subquery.err change to #13105 . I'm scared of what you might say there :S

Now, what's wrong with not copying the visitor? The way I see it, the bug was that we were copying the visitor; the natural fix is to not copy it any more :) If I had to propagate the error back, I'd have had to figure out the proper place to do that.
I think the code is peachy; what's wrong with it?

---

Review status: 0 of 2 files reviewed at latest revision, 5 unresolved discussions, some commit checks pending.

---

*[pkg/sql/subquery_test.go, line 27 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/13004#-KaruNvx2z6tRXTiVt3L-r1-27:-KbCjKeigrCvOvT7Bh4m:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/f5c2a188a31c7a8b391190cd025af4991b6ad061/pkg/sql/subquery_test.go#L27)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

returns
</blockquote></details>

Done.

---

*[pkg/sql/subquery_test.go, line 45 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/13004#-KatpSIXiHKjB2g3JyAA:-KbCj5w5whkSbYyo0rw3:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/f5c2a188a31c7a8b391190cd025af4991b6ad061/pkg/sql/subquery_test.go#L45)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

note that this string is a regular expression, so you might want to write `"forced by crdb_internal\.force_retry\(\)"`
</blockquote></details>

Done.

---

*[pkg/sql/walk.go, line 81 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/13004#-Kb6wvD-wEHK-KvijsQi:-KbCiYSZY-O7DLY7MC5_:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/f5c2a188a31c7a8b391190cd025af4991b6ad061/pkg/sql/walk.go#L81)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

name could be shorter, like `name`
</blockquote></details>

Done.

---

*[pkg/sql/walk.go, line 377 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/13004#-Kb6vRk6DQW3UZAzIfrI:-KbCi_G0zZQHSBp-3HLs:bf0xi92) ([raw file](https://github.com/cockroachdb/cockroach/blob/f5c2a188a31c7a8b391190cd025af4991b6ad061/pkg/sql/walk.go#L377)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

The comment about the current node's name doesn't make sense anymore.
</blockquote></details>

got rid of this method

---

*[pkg/sql/subquery.go, line 177 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/13004#-KaruNvx2z6tRXTiVt3K-r1-177:-KbCjJcL3JUTEWUzAVId:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/f5c2a188a31c7a8b391190cd025af4991b6ad061/pkg/sql/subquery.go#L177)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

[nit] `return result, fmt.Errorf()`, or at least use `err := `
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/13004#-:-KbCjONh2ualY-1Gf_Eo:bcdsewx)*

**Comment by tamird** [comment]
Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/13004)*

**Comment by knz** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/13004#-:-KbFP5CACbhGn49yTnyt:bnfp4nl)*

**Comment by knz** [comment]
(I changed my mind)
