### PR TITLE
sql/catalog/descs: fix descriptor lookup during public schema migration

### LINKED ISSUE #75805: roachtest: tpcc/mixed-headroom/n5cpu16 failed
roachtest.tpcc/mixed-headroom/n5cpu16 [failed](https://server-url-not-found-in-env.com/viewLog.html?buildId=4263825&tab=buildLog) with [artifacts](https://server-url-not-found-in-env.com/viewLog.html?buildId=4263825&tab=artifacts#/tpcc/mixed-headroom/n5cpu16) on master @ [8548987813ff9e1b8a9878023d3abfc6911c16db](https://github.com/cockroachdb/cockroach/commits/8548987813ff9e1b8a9878023d3abfc6911c16db):

```
		  |   274.0s        0          185.8           86.7     28.3     52.4     56.6     62.9 newOrder
		  |   274.0s        0           19.0            9.2      6.8      8.4      9.4      9.4 orderStatus
		  |   274.0s        0          195.8           92.5     15.7     30.4     37.7     39.8 payment
		  |   274.0s        0           16.0            9.2     25.2     35.7     37.7     37.7 stockLevel
		  |   275.0s        0           18.0            9.2     54.5     67.1     71.3     71.3 delivery
		  |   275.0s        0          184.0           87.0     27.3     37.7     41.9     48.2 newOrder
		  |   275.0s        0           19.0            9.3      6.6      9.4     11.5     11.5 orderStatus
		  |   275.0s        0          171.0           92.8     15.2     24.1     29.4     32.5 payment
		  |   275.0s        0           15.0            9.2     25.2     28.3     28.3     28.3 stockLevel
		  |   276.0s        0           13.0            9.2     50.3     58.7     75.5     75.5 delivery
		  |   276.0s        0          152.1           87.2     28.3     39.8     44.0     50.3 newOrder
		  |   276.0s        0           15.0            9.3      5.8      7.1     10.0     10.0 orderStatus
		  |   276.0s        0          162.1           93.0     15.7     22.0     27.3     32.5 payment
		  |   276.0s        0           17.0            9.3     21.0     44.0     44.0     44.0 stockLevel
		  | _elapsed___errors__ops/sec(inst)___ops/sec(cum)__p50(ms)__p95(ms)__p99(ms)_pMax(ms)
		  |   277.0s        0           22.0            9.2     56.6     71.3     88.1     88.1 delivery
		  |   277.0s        0          159.1           87.5     27.3     39.8     46.1     50.3 newOrder
		  |   277.0s        0           20.0            9.3      6.6      9.4     11.5     11.5 orderStatus
		  |   277.0s        0          169.1           93.3     16.3     23.1     27.3     28.3 payment
		  |   277.0s        0           15.0            9.3     27.3     48.2     67.1     67.1 stockLevel
		  |   278.0s        0           16.0            9.2     52.4     65.0     67.1     67.1 delivery
		  |   278.0s        0          152.0           87.7     28.3     46.1     54.5     62.9 newOrder
		  |   278.0s        0           19.0            9.4      7.1     13.1     25.2     25.2 orderStatus
		  |   278.0s        0          195.0           93.7     15.7     22.0     33.6     56.6 payment
		  |   278.0s        0           15.0            9.3     22.0     41.9     44.0     44.0 stockLevel
		Wraps: (8) COMMAND_PROBLEM
		Wraps: (9) Node 5. Command with error:
		  | ``````
		  | ./cockroach workload run tpcc --warehouses=909 --histograms=perf/stats.json  --ramp=5m0s --duration=2h0m0s --prometheus-port=2112 --pprofport=33333  {pgurl:1-4}
		  | ``````
		Wraps: (10) exit status 1
		Error types: (1) *withstack.withStack (2) *errutil.withPrefix (3) *withstack.withStack (4) *errutil.withPrefix (5) *withstack.withStack (6) *errutil.withPrefix (7) *cluster.WithCommandDetails (8) errors.Cmd (9) *hintdetail.withDetail (10) *exec.ExitError

	mixed_version_jobs.go:73,versionupgrade.go:208,tpcc.go:414,test_runner.go:780: already failed
		(1) attached stack trace
		  -- stack trace:
		  | main.(*monitorImpl).WaitE
		  | 	main/pkg/cmd/roachtest/monitor.go:112
		  | github.com/cockroachdb/cockroach/pkg/cmd/roachtest/tests.(*backgroundStepper).wait
		  | 	github.com/cockroachdb/cockroach/pkg/cmd/roachtest/tests/mixed_version_jobs.go:69
		  | github.com/cockroachdb/cockroach/pkg/cmd/roachtest/tests.(*versionUpgradeTest).run
		  | 	github.com/cockroachdb/cockroach/pkg/cmd/roachtest/tests/versionupgrade.go:208
		  | github.com/cockroachdb/cockroach/pkg/cmd/roachtest/tests.registerTPCC.func2
		  | 	github.com/cockroachdb/cockroach/pkg/cmd/roachtest/tests/tpcc.go:414
		  | main.(*testRunner).runTest.func2
		  | 	main/pkg/cmd/roachtest/test_runner.go:780
		  | runtime.goexit
		  | 	GOROOT/src/runtime/asm_amd64.s:1581
		Wraps: (2) already failed
		Error types: (1) *withstack.withStack (2) *errutil.leafError
```
<details><summary>Help</summary>
<p>

See: [roachtest README](https://github.com/cockroachdb/cockroach/blob/master/pkg/cmd/roachtest/README.md)

See: [How To Investigate \(internal\)](https://cockroachlabs.atlassian.net/l/c/SSSBr8c7)

</p>
</details>
<details><summary>Same failure on other branches</summary>
<p>

- #74892 roachtest: tpcc/mixed-headroom/n5cpu16 failed [OOM during import while running 21.2] [C-test-failure O-roachtest O-robot T-bulkio branch-release-21.2 release-blocker]
</p>
</details>
/cc @cockroachdb/kv-triage
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*tpcc/mixed-headroom/n5cpu16.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)
</sub>

Jira issue: CRDB-12844

### PR DESCRIPTION
**Pull request by ajwerner**
This PR adds some special-case logic to the descs.Collection to deal with the
situation when the public schema is moving from being vitual to being a real
schema descriptor. During this transition, it's possible for the table in the
lease manager to have been updated before the database descriptor which would
contain the reference to the new public schema. The trick is that we want to
fall back to resolving the public schema for the database in the case where
we know we're in the midst of this migration and we fail to find a descriptor
at the virtual public schema ID.

The change ends up being rather minimal. The test, as written, would fail
readily under stress before the change. The cost of this change should be
pretty minimal: in some rare cases, one extra lookup may need to occur to
find the correct public schema and one extra lookup will occur due to the
cache miss with the old schema ID. 

Fixes #75805.

Release note: None

### CODE REVIEW

**Comment by ajwerner** [comment]
This went through more iterations and attempts than I'd like to admit. This is by far the simplest one that worked that I could find.

**Comment by ajwerner** [comment]
`1823 runs so far, 0 failures, over 12m5s`

File: pkg/sql/catalog/descs/object.go [hunk 1]
```diff
@@ -184,19 +189,41 @@ func (tc *Collection) getObjectByNameIgnoringRequiredAndType(
...
+		// We add a special case to deal with the public schema migration. During
+		// that migration, we create a real descriptor for the public schema and we
+		// re-parent the members of the descriptor-less public schema into this new
+		// schema. The hazard is that we have a lease on the database descriptor
+		// which does not know about the new public schema, but the table we're
+		// going to lease does. There are more targeted things which could be done,
+		// but this situation should be exceedingly rare. To detect it, we notice
+		// that we're currently in the migration in question and not past it, then
+		// we return a restart error which will lead to the current transaction
+		// being retried.
```
Comment (postamar) [inline pkg/sql/catalog/descs/object.go:214]: For my information, where is this error actually thrown?

**Review by postamar — APPROVED** [review]

**Review by RichardJCai — APPROVED** [review]
Nice fix!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/78393#-:-MywQAiPC_4iPSYOjQkO:b-k6moza)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @postamar, and @RichardJCai)

___
*[pkg/sql/catalog/descs/descriptor.go, line 413 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/78393#-MywQ2pwAW-Tf4Qc0wpO:-MywQ2pwAW-Tf4Qc0wpP:bvothy3) ([raw file](https://github.com/cockroachdb/cockroach/blob/96fe86fd88a542c5e1370b6461d4ffd32490cef1/pkg/sql/catalog/descs/descriptor.go#L413)):*
> ```Go
> 	if !db.HasPublicSchemaWithDescriptor() && name == tree.PublicSchema {
> 		// TODO(ajwerner): Remove ignoreMissingPublicSchema in 22.2.
> 		if ignoreMissingPublicSchema {
> ```

nit: maybe a better name for this is `alwaysLookupLeasedPublicSchema`?
___
*[pkg/sql/catalog/descs/object.go, line 220 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/78393#-MywNWMr0Ev5oaF5h830:-MywNWMr0Ev5oaF5h831:bgh6tqv) ([raw file](https://github.com/cockroachdb/cockroach/blob/96fe86fd88a542c5e1370b6461d4ffd32490cef1/pkg/sql/catalog/descs/object.go#L220)):*
> ```Go
> 		// TODO(ajwerner): Remove this for 22.2.
> 		if !ignoreMissingPublicSchema && sc.GetID() == keys.PublicSchemaID &&
> 			!tc.settings.Version.IsActive(ctx, clusterversion.PublicSchemasWithDescriptors) &&
> ```

nit: Do we need `!tc.settings.Version.IsActive(ctx, clusterversion.PublicSchemaWithDescriptors)` here? It's redundant given the next check right?

**Review by ajwerner — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/78393)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @postamar and @RichardJCai)

___
*[pkg/sql/catalog/descs/descriptor.go, line 413 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/78393#-MywQ2pwAW-Tf4Qc0wpO:-Mywcj7qCK6N1c5xrbcp:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/96fe86fd88a542c5e1370b6461d4ffd32490cef1/pkg/sql/catalog/descs/descriptor.go#L413)):*
<details><summary><i>Previously, RichardJCai (Richard Cai) wrote…</i></summary><blockquote>

nit: maybe a better name for this is `alwaysLookupLeasedPublicSchema`?
</blockquote></details>

Done.
___
*[pkg/sql/catalog/descs/object.go, line 220 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/78393#-MywNWMr0Ev5oaF5h830:-MywbGls1dJ88gavcyip:b-5wwe6h) ([raw file](https://github.com/cockroachdb/cockroach/blob/96fe86fd88a542c5e1370b6461d4ffd32490cef1/pkg/sql/catalog/descs/object.go#L220)):*
<details><summary><i>Previously, RichardJCai (Richard Cai) wrote…</i></summary><blockquote>

nit: Do we need `!tc.settings.Version.IsActive(ctx, clusterversion.PublicSchemaWithDescriptors)` here? It's redundant given the next check right?
</blockquote></details>

I don't think it's redundant. Once `PublicSchemasWithDescriptors` is active, we've waited for leases to drain on the database descriptors, so we never need to go down this route. The below check is about seeing if it's possible that we now have the new descriptors.


```
21.2[---before--][--mid--][--after--]22.1
```

This code only runs between these two versions. I think that's nice.

**Comment by ajwerner** [comment]
TFTR!

bors r+
