### PR TITLE
roachtest: fail the latency verifier immediately if latency is too high

### LINKED ISSUE #117182: roachtest: c2c/weekly/kv50 failed
roachtest.c2c/weekly/kv50 [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestWeeklyAwsBazel/13334997?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestWeeklyAwsBazel/13334997?buildTab=artifacts#/c2c/weekly/kv50) on master @ [c316d6a615fa02a05357a20bf03b8a197ab27810](https://github.com/cockroachdb/cockroach/commits/c316d6a615fa02a05357a20bf03b8a197ab27810):

```
(latency_verifier.go:199).assertValid: max latency was more than allowed: 59m0.156290984s vs 5m0s
(monitor.go:153).Wait: monitor failure: monitor user task failed: t.Fatal() was called
test artifacts and logs in: /artifacts/c2c/weekly/kv50/run_1
```

Parameters:
 - <code>ROACHTEST_arch=amd64</code>
 - <code>ROACHTEST_cloud=aws</code>
 - <code>ROACHTEST_coverageBuild=false</code>
 - <code>ROACHTEST_cpu=8</code>
 - <code>ROACHTEST_encrypted=false</code>
 - <code>ROACHTEST_fs=ext4</code>
 - <code>ROACHTEST_localSSD=false</code>
 - <code>ROACHTEST_metamorphicBuild=false</code>
 - <code>ROACHTEST_ssd=0</code>
<details><summary>Help</summary>
<p>

See: [roachtest README](https://github.com/cockroachdb/cockroach/blob/master/pkg/cmd/roachtest/README.md)

See: [How To Investigate \(internal\)](https://cockroachlabs.atlassian.net/l/c/SSSBr8c7)

_Grafana is not yet available for aws clusters_</p>
</details>
/cc @cockroachdb/disaster-recovery
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*c2c/weekly/kv50.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)
</sub>

Jira issue: CRDB-35037

### PR DESCRIPTION
**Pull request by msbutler**
Previously, the latency verifier used by c2c and cdc roachtests would not fail immediately if latency was too high. This patch fails the latency verifier immediately, as the roachtest is going to eventually fail anyway.

In addition, immediately after a latency verifier failure, this patch captures c2c debug zips to better understand the cause of the increased latency.

Fixes #117182

Release note: none

### CODE REVIEW

File: pkg/cmd/roachtest/tests/latency_verifier.go [hunk 1]
```diff
@@ -181,6 +181,10 @@ func (lv *latencyVerifier) pollLatencyUntilJobSucceeds(
 			lv.logger.Printf("unexpected status: %s, error: %s", status, info.GetError())
 			return errors.Errorf("unexpected status: %s", status)
 		}
+		if lv.targetSteadyLatency != 0 && lv.maxSeenSteadyLatency > lv.targetSteadyLatency {
```
Comment (stevendanna) [inline pkg/cmd/roachtest/tests/latency_verifier.go:184]: Note to self/other reviewers: maxSeenSteadyLatency is only set once we've already already established a latency below the targetSteadyLatency.

**Review by stevendanna — APPROVED** [review]

**Review by jayshrivastava — APPROVED** [review]

**Comment by msbutler** [comment]
TFTR! 

bors r=stevendanna
