### PR TITLE
kvserver: deflake TestRaftForceCampaignPreVoteCheckQuorum

### LINKED ISSUE #152555: kv/kvserver: TestRaftForceCampaignPreVoteCheckQuorum failed
kv/kvserver.TestRaftForceCampaignPreVoteCheckQuorum [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Ci_TestsIbmCloudLinuxS390x_UnitTestsS390x/20391364?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Ci_TestsIbmCloudLinuxS390x_UnitTestsS390x/20391364?buildTab=artifacts#/) on master @ [f276f1ade7253ccbb6f3073ce215ca464b7d8220](https://github.com/cockroachdb/cockroach/commits/f276f1ade7253ccbb6f3073ce215ca464b7d8220):

```
=== RUN   TestRaftForceCampaignPreVoteCheckQuorum
    test_log_scope.go:171: test logs captured to: /artifacts/tmp/_tmp/15f2e1706383de9d6af3292f657b4304/logTestRaftForceCampaignPreVoteCheckQuorum3093547704
    test_log_scope.go:82: use -show-logs to present logs inline
    client_raft_test.go:6183: n1 StateLeader at term=6 commit=20
    client_raft_test.go:6184: n1 is leader in term 6
    client_raft_test.go:6189: n3 campaigning
    client_raft_test.go:6195: n1 StateLeader at term=6 commit=20
    client_raft_test.go:6195: n1 StateLeader at term=6 commit=21
    client_raft_test.go:6195: n1 StateLeader at term=6 commit=21
    client_raft_test.go:6195: n1 StateLeader at term=6 commit=21
    client_raft_test.go:6195: n1 StateLeader at term=6 commit=21
    client_raft_test.go:6195: n1 StateLeader at term=6 commit=22
    client_raft_test.go:6195: n1 StateLeader at term=6 commit=22
    client_raft_test.go:6195: n1 StateLeader at term=6 commit=22
    client_raft_test.go:6195: n1 StateLeader at term=6 commit=22
    client_raft_test.go:6195: n1 StateLeader at term=6 commit=22
    client_raft_test.go:6195: n1 StateLeader at term=6 commit=22
    client_raft_test.go:6195: n1 StateLeader at term=6 commit=22
    client_raft_test.go:6195: n1 StateLeader at term=6 commit=23
    client_raft_test.go:6195: n1 StateLeader at term=6 commit=23
    client_raft_test.go:6195: n1 StateLeader at term=6 commit=23
    client_raft_test.go:6195: n1 StateLeader at term=6 commit=23
    client_raft_test.go:6195: n1 StateLeader at term=6 commit=23
    client_raft_test.go:6195: n1 StateLeader at term=6 commit=23
    client_raft_test.go:6195: n1 StateLeader at term=6 commit=24
    client_raft_test.go:6192: 
        	Error Trace:	pkg/kv/kvserver/client_raft_test.go:6192
        	Error:      	Condition never satisfied
        	Test:       	TestRaftForceCampaignPreVoteCheckQuorum
    panic.go:635: -- test log scope end --
test logs left over in: /artifacts/tmp/_tmp/15f2e1706383de9d6af3292f657b4304/logTestRaftForceCampaignPreVoteCheckQuorum3093547704
--- FAIL: TestRaftForceCampaignPreVoteCheckQuorum (12.00s)
```
<details><summary>Help</summary>
<p>

See also: [How To Investigate a Go Test Failure \(internal\)](https://cockroachlabs.atlassian.net/l/c/HgfXfJgM)
</p>
</details>
/cc @cockroachdb/kv-triage
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*TestRaftForceCampaignPreVoteCheckQuorum.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/bazci/githubpost/issues)

</sub>

Jira issue: CRDB-53912

### PR DESCRIPTION
**Pull request by miraradeva**
The test seems to fail if `ForceCampaign` is called while there are still pending config changes. This commit adds a check for this case.

Fixes: #152555

Release note: None

### CODE REVIEW

File: pkg/kv/kvserver/client_raft_test.go [hunk 1]
```diff
@@ -6183,6 +6183,12 @@ func TestRaftForceCampaignPreVoteCheckQuorum(t *testing.T) {
 	logStatus(initialStatus)
 	t.Logf("n1 is leader in term %d", initialStatus.Term)
 
+	// Wait for any pending config changes to be finalized. Otherwise, the forced
+	// campaign will fail and not retry.
```
Comment (pav-kv) [inline pkg/kv/kvserver/client_raft_test.go:6187]: Do we need it to win? The comment below says it's enough that it bumps the term.

File: pkg/kv/kvserver/client_raft_test.go [hunk 2]
```diff
@@ -6183,6 +6183,12 @@ func TestRaftForceCampaignPreVoteCheckQuorum(t *testing.T) {
...
+	require.Eventually(t, func() bool {
+		return !desc.Replicas().InAtomicReplicationChange()
+	}, 10*time.Second, 500*time.Millisecond)
```
Comment (pav-kv) [inline pkg/kv/kvserver/client_raft_test.go]: Does `desc` change while this waits? Looks like a constant.

Comment (miraradeva) [reply pkg/kv/kvserver/client_raft_test.go]: You're right. I can re-calculate the desc ... or hold off on this fix until I can repro.

File: pkg/kv/kvserver/client_raft_test.go [hunk 3]
```diff
@@ -6183,6 +6183,12 @@ func TestRaftForceCampaignPreVoteCheckQuorum(t *testing.T) {
 	logStatus(initialStatus)
 	t.Logf("n1 is leader in term %d", initialStatus.Term)
 
+	// Wait for any pending config changes to be finalized. Otherwise, the forced
+	// campaign will fail and not retry.
+	require.Eventually(t, func() bool {
+		return !repl3.Desc().Replicas().InAtomicReplicationChange()
```
Comment (pav-kv) [inline pkg/kv/kvserver/client_raft_test.go]: Do you have a sense on why this replica can be in this state? Is this because of what this test does (e.g. `AddVoters` above), or due to random things that `TestCluster` can do without our control?

`Desc().Replicas().InAtomicReplicationChange()` is based on the **applied** state, but the check in raft that rejects a campaign is based on the unapplied entries in the log. So not sure this wait will guarantee that the campaign will not be rejected.

Comment (pav-kv) [reply pkg/kv/kvserver/client_raft_test.go]: Would it help to wait until `repl3` applies everything that we've proposed above?

Comment (miraradeva) [reply pkg/kv/kvserver/client_raft_test.go]: I think it's just not done with the config change resulting from `AddVoters`, but that's just a guess. I haven't been able to repro, so it's hard to say for sure. Any ideas how to ensure at least that part has completed before issuing the `ForceCampaign`?

Comment (pav-kv) [reply pkg/kv/kvserver/client_raft_test.go]: Given this bit above:

```golang
	desc := tc.AddVotersOrFatal(t, key, tc.Targets(1, 2)...)
	_, pErr := kv.SendWrapped(ctx, sender, incrementArgs(key, 1))
	require.NoError(t, pErr.GoError())
	tc.WaitForValues(t, key, []int64{1, 1, 1})
```

It looks like we're waiting for the `increment` to be applied on all replicas. Which happens after the config change is applied. So I would think that the `AddVoters` has done its job by this time.

But looking at the `AddVoters` implementation, I'm not sure it waits long enough. Maybe it only waits until replicas are added but doesn't wait until we exit the joint config state.

Comment (pav-kv) [reply pkg/kv/kvserver/client_raft_test.go]: This is what it waits for:

https://github.com/cockroachdb/cockroach/blob/8ab959aa89dd7f379bc747540f383798faa053b5/pkg/testutils/testcluster/testcluster.go#L890-L892

Maybe we should trick it into calling this thing with `waitForVoter == true`.

Comment (pav-kv) [reply pkg/kv/kvserver/client_raft_test.go]: Would this help?

https://github.com/cockroachdb/cockroach/blob/8ab959aa89dd7f379bc747540f383798faa053b5/pkg/testutils/testcluster/testcluster.go#L954-L958

Comment (pav-kv) [reply pkg/kv/kvserver/client_raft_test.go]: A similar clause here:

https://github.com/cockroachdb/cockroach/blob/8ab959aa89dd7f379bc747540f383798faa053b5/pkg/kv/kvserver/client_raft_test.go#L4236-L4240

Comment (miraradeva) [reply pkg/kv/kvserver/client_raft_test.go]: It's worth a shot.

File: pkg/kv/kvserver/client_raft_test.go [hunk 4]
```diff
@@ -6183,6 +6183,10 @@ func TestRaftForceCampaignPreVoteCheckQuorum(t *testing.T) {
 	logStatus(initialStatus)
 	t.Logf("n1 is leader in term %d", initialStatus.Term)
 
+	// Wait for the config changes corresponding to adding voters to be finalized.
+	// Otherwise, the forced campaign will fail and not retry.
```
Comment (pav-kv) [inline pkg/kv/kvserver/client_raft_test.go]: Could you add `See #152555.` for posterity in case we come back here?

**Review by pav-kv — APPROVED** [review]

**Comment by miraradeva** [comment]
@pav-kv Wow, it actually reproed in CI, even with the latest fix. I'll stress some more I guess.

**Comment by pav-kv** [comment]
Maybe your original fix works better then. Though I'm surprized that `WaitForVoters` didn't help.

For debugging, might be helpful to print that pending config that prevents the campaign. We are scanning the log here:

https://github.com/cockroachdb/cockroach/blob/8ab959aa89dd7f379bc747540f383798faa053b5/pkg/raft/raft.go#L1462-L1482

So we have that entry. Something like:

```golang
if CrdbTestBuild {
	// log ents[i]
}
```

File: pkg/kv/kvserver/client_raft_test.go [hunk 5]
```diff
@@ -6165,6 +6165,9 @@ func TestRaftForceCampaignPreVoteCheckQuorum(t *testing.T) {
 	// Create a range, upreplicate it, and replicate a write.
 	key := tc.ScratchRange(t)
 	desc := tc.AddVotersOrFatal(t, key, tc.Targets(1, 2)...)
+	// Wait for the config changes corresponding to adding voters to be finalized.
+	// Otherwise, the forced campaign will fail and not retry. See #152555.
```
Comment (pav-kv) [inline pkg/kv/kvserver/client_raft_test.go]: nit: will -> can/could

**Review by pav-kv — APPROVED** [review]

**Comment by miraradeva** [comment]
TFTR!

bors r=pav-kv
