### PR TITLE
ui: Refresh Liveness on Single Node page

### LINKED ISSUE #17554: ui: node overview displays incorrect node status after refresh
1. Start a cluster and kill a node.
2. Open the Admin UI, click on "View nodes list."
3. Click on the killed node.
4. Observe the "suspected" or "dead" status in the node summary box on the top right.
5. Refresh the page.
6. Observe that the node summary box erroneously displays the status as "healthy."

### PR DESCRIPTION
**Pull request by mrtracy**
Liveness records were not being refreshed at all while viewing the
single-node page.

Fixes #17554

Release note (admin ui): Fixed a bug where liveness status would not
always display correctly on the single-node page.

### CODE REVIEW

**Review by vilterp — APPROVED** [review]
LGTM. Verified the fix with a dead node on my system.

File: pkg/ui/src/redux/nodes.ts [hunk 1]
```diff
@@ -240,3 +240,11 @@ export const nodesSummarySelector = createSelector(
 
 const nodesSummaryType = nullOfReturnType(nodesSummarySelector);
 export type NodesSummary = typeof nodesSummaryType;
+
+// selectNodesSummaryValid is a selector that returns true if the current
+// nodesSummary is "valid" (i.e. based on acceptably recent data). This is
+// included in the redux-connected state of some pages in order to support
+// automatically refreshing data.
+export function selectNodesSummaryValid (state: AdminUIState) {
```
Comment (vilterp) [inline pkg/ui/src/redux/nodes.ts]: nit: remove space. Do we not lint stuff like this? :P

File: pkg/ui/src/views/cluster/containers/nodeOverview/index.tsx [hunk 2]
```diff
@@ -32,12 +34,14 @@ class NodeOverview extends React.Component<NodeOverviewProps, {}> {
   componentWillMount() {
     // Refresh nodes status query when mounting.
     this.props.refreshNodes();
+    this.props.refreshNodes();
```
Comment (couchand) [inline pkg/ui/src/views/cluster/containers/nodeOverview/index.tsx]: whoops!

File: pkg/ui/src/views/cluster/containers/nodeOverview/index.tsx [hunk 3]
```diff
@@ -180,9 +184,11 @@ export default connect(
     return {
       node: currentNode(state, ownProps),
       nodesSummary: nodesSummarySelector(state),
+      nodesSummaryValid: selectNodesSummaryValid(state),
```
Comment (couchand) [inline pkg/ui/src/views/cluster/containers/nodeOverview/index.tsx]: it looks like this isn't actually used anywhere?

**Review by couchand — COMMENTED** [review]
Going through stuff that was merged while I was out, looks like there are two minor questions here.

File: pkg/ui/src/views/cluster/containers/nodeOverview/index.tsx (hunk 3 above)
Comment (mrtracy) [reply pkg/ui/src/views/cluster/containers/nodeOverview/index.tsx]: It needs to be on there or it won't actually refresh when the status becomes invalid.

Comment (couchand) [reply pkg/ui/src/views/cluster/containers/nodeOverview/index.tsx]: how does that work if there are no references to it?

Comment (mrtracy) [reply pkg/ui/src/views/cluster/containers/nodeOverview/index.tsx]: You're looking at the reference right there; the object returned from mapStateToProps is what react-redux uses to determine if a component re-renders or not.

Comment (couchand) [reply pkg/ui/src/views/cluster/containers/nodeOverview/index.tsx]: That is not at all clear from reading the code.

Comment (mrtracy) [reply pkg/ui/src/views/cluster/containers/nodeOverview/index.tsx]: That is how all of the automatic refreshes work on every page.

I realize it is confusing, #18741 was supposed to address this (it's called out specifically in that issue) but has been sidelined for the foreseeable future.
