### PR TITLE
restore: fix retry revert stuck in reverting

### LINKED ISSUE #156019: restore: do not fail on missing descriptors during restore cleanup
Currently, if a function descriptor is missing during restore cleanup, restore fails and the job is put in a retry loop as it attempts to revert. If restore is performing a cleanup of all descriptors, having a missing descriptor should not fail cleanup.

Jira issue: CRDB-55741

### PR DESCRIPTION
**Pull request by kev-cao**
Previously, if a reverting restore job was paused after dropping its descriptors and then resumed, the restore job would get stuck in a retry loop due to missing descriptors.

This commit adds a field in the restore details that can be set once descriptors have been dropped during restore cleanup. This allows us to avoid attempting to drop descriptors if they have already been dropped.

Fixes: #156019

Release note: Restore no longer gets stuck in a retry loop when reverts are attempted twice.

### CODE REVIEW

File: pkg/backup/restore_job.go [hunk 1]
```diff
@@ -2820,6 +2820,13 @@ func (r *restoreResumer) OnFailOrCancel(
 		return err
 	}
 
+	testingKnobs := execCfg.BackupRestoreTestingKnobs
+	if testingKnobs != nil && testingKnobs.AfterRevertRestoreDropDescriptors != nil {
+		if err := testingKnobs.AfterRevertRestoreDropDescriptors(); err != nil {
+			return err
+		}
+	}
```
[the remark this answers is not in the document]
Comment (kev-cao) [reply pkg/backup/restore_job.go:2832]: That's actually just straight up false.

File: pkg/backup/restore_job.go [hunk 2]
```diff
@@ -2865,6 +2876,19 @@ func (r *restoreResumer) dropDescriptors(
 		return nil
 	}
 
+	jobInfo := jobs.InfoStorageForJob(txn, r.job.ID())
```
Comment (jeffswenson) [inline pkg/backup/restore_job.go:2879]: Instead of adding a checkpoint, how difficult would it be to make the cleanup logic idempotent so it is safe to run twice? Making the code naturally idempotent is my preferred solution for job retries.

Comment (kev-cao) [reply pkg/backup/restore_job.go:2879]: My original implementation was to make the code naturally idempotent. It required adding `if pgerr.GetPGCode(err) == pgcode.UndefinedX` checks in 4 or 5 places.

Since it required more reasoning to determine where to place these checks, it felt more susceptible to bugs if we were to ever come back and add more cleanup logic, which is why I went with the checkpoint approach.

I'm open to being convinced otherwise though.

**Review by jeffswenson — APPROVED** [review]
LGTM

File: pkg/backup/restore_job.go (hunk 2 above)
Comment (jeffswenson) [reply pkg/backup/restore_job.go:2879]: Looking through the code I think you are right. This would probably need to be rewritten to be cleanly idempotent.

**Comment by msbutler** [comment]
btw, i dont think we need to backport this change. It's not a trival backport and it's not a severe bug.
