### PR TITLE
release-21.1: sql: fix COPY bugs for binary/csv formats

### LINKED ISSUE #63235: sql: COPY IN BINARY doesn't return correct format code to client
lib/pq's `txn.Prepare("COPY temp (num) FROM STDIN WITH binary")` should fail with `pq: only text format supported for COPY`, however this does not happen for CRDB, no error is returned. 

The error should be generated by lib/pq here: https://github.com/lib/pq/blob/master/copy.go#L89

Roughly 9/10 times no error will be returned, however 1/10 `pq: unrecognized client message type ClientMsgSimpleQuery` is returned.

To reproduce (This correctly errors when pointing it to a pg db):
Start a CRDB Cluster
1. `cockroach demo --empty `
2. Run the following script after replacing the postgres url with the one given by CRDB's console.
```
package main

import (
	"database/sql"
	"log"

	_ "github.com/lib/pq"
)

func main() {
	db, err := sql.Open("postgres", "postgres://root:admin@127.0.0.1:55977?sslmode=require")

	if err != nil {
		log.Fatal("error connecting to the database: ", err)
	}

	defer db.Close()

	txn, err := db.Begin()
	if err != nil {
		panic(err)
	}
	defer txn.Rollback()
	_, err = txn.Exec("CREATE TEMP TABLE temp (num INTEGER)")
	if err != nil {
		panic(err)
	}

	println("prepare?")
	_, err = txn.Prepare("COPY temp (num) FROM STDIN WITH binary")
	if err != nil {
		panic(err.Error())
	}

	// check that the protocol is in a valid state
	err = txn.Commit()
	if err != nil {
		panic(err)
	}
}
```

### LINKED ISSUE #68804: COPY CSV doesn't support bytea column
**Describe the problem**
COPY CSV does not support binary data. Since CSV is a text-based format, you have to encode `bytea` columns to hex or octal when generating the CSV. CockroachDB doesn't decode these encoded fields embedded in the CSV and instead inserts them as string into the bytea column.

**To Reproduce**

1. `cockroach demo`
2. `psql "postgres://demo:<password>@127.0.0.1:26257/movr?sslmode=require"`
2. `alter table users add column data bytea;`
3. `COPY users(id,city,data) FROM STDIN CSV;`
4. `8a3d70a3-d70a-4000-8000-00000000001d,seattle,"\x00"`
5. `\.`
6. `select * from users where id = '8a3d70a3-d70a-4000-8000-00000000001d';`
```sql
                  id                  |  city   | name | address | credit_card |    data
--------------------------------------+---------+------+---------+-------------+------------
 8a3d70a3-d70a-4000-8000-00000000001d | seattle |      |         |             | \x5c783030
```
7. `insert into users (id, city, data) values (gen_random_uuid(), 'new york', decode('00', 'hex'));`
8. `select * from users where data = '\x00';`
```sql
                  id                  |     city      |        name         |            address             | credit_card |     data
--------------------------------------+---------------+---------------------+--------------------------------+-------------+--------------
d4272cf3-589d-481b-97bb-ef8712b5d227  | new york      |                     |                                |             | \x00
```

The `data` column should be `\x00` and not `\x5c783030`. `5c783030` is the characters `\x00` encoded to hex, so it's doubly encoded. Regular insert works fine and can insert `\x00`. If you repeat the above steps using COPY in PostgreSQL, you also get `\x00`.

**Expected behavior**
Binary data to be inserted as is without being doubly encoded. In the above example the `data` should be `\x00` and not `\x5c783030`.

It should also probably support octal encoded `\00` format as well to have [parity](https://www.postgresql.org/docs/13/sql-copy.html) with PostgreSQL.

**Additional data / screenshots**

**Environment:**
* CockroachDB version v21.1.6
* Server OS: MacOS
* Client app: JDBC

**Additional context**
What was the impact?

Unable to move forward with the PoC.

cc @rafiss 

Epic CRDB-7217

### LINKED ISSUE #68805: pgwire: COPY binary protocol fails when the client chunks the data stream in the middle of a record
Per the pgwire spec:
> CopyData: Messages sent from the backend will always correspond to single data rows, but messages sent by frontends might divide the data stream arbitrarily.

The pgx/pgconn library divides binary COPY streams at arbitrary 64k boundaries
https://github.com/jackc/pgconn/blob/53f5fed36c570f0b5c98d6ec2415658c7b9bd11c/pgconn.go#L1217-L1222

Copying large amount of data thus leads to "partial copy data row" errors at https://github.com/cockroachdb/cockroach/blob/8de063f1c60767797f143a60c2413685794f21f6/pkg/sql/copy.go#L485 because the overall structure of the `copyMachine` code assumes that tuples aren't split across wire-message boundaries.

X-Ref: https://github.com/cockroachdb/cdc-sink/issues/45

Epic CRDB-7217

### PR DESCRIPTION
**Pull request by rafiss**
Backport 5/5 commits from #69066.

/cc @cockroachdb/release

---

See individual commits:

sql: return correct format code for COPY
fixes #63235 

sql: COPY BINARY messages can be split at arbitrary boundaries 
fixes #68805 

sql: COPY CSV handles arbitrary message boundaries
refs #68805 

sql: fix byte escaping in COPY CSV input 
fixes #68804 

Release justification: Fixes for high-priority bugs in existing functionality. ("Another rule of thumb to consider: if a customer hit this bug after releasing, would we patch the release to fix it? If we would patch the release later to fix the bug, then usually it's best to fix the bug now.")

### CODE REVIEW

File: pkg/sql/copy.go [hunk 1]
```diff
@@ -244,7 +245,9 @@ func (c *copyMachine) run(ctx context.Context) error {
 	case tree.CopyFormatText:
 		c.textDelim = []byte{c.delimiter}
 	case tree.CopyFormatCSV:
-		c.csvReader = csv.NewReader(&c.buf)
+		c.csvInput.Reset()
+		c.csvReader = csv.NewReader(&c.csvInput)
+		//c.csvReader = csv.NewReader(&c.buf)
```
Comment (otan) [inline pkg/sql/copy.go]: hehe, you put the delete on the wrong commit
oh well, no biggie!

Comment (rafiss) [reply pkg/sql/copy.go]: whooooops
