### PR TITLE
sql: never produce a NULL shard column value

### LINKED ISSUE #47055: sql: WITH HASH hash column is not null but formula can return NULL
```
create table t (x int);
CREATE INDEX ON t(x) USING HASH WITH BUCKET_COUNT = 10;
```

This is what the optimizer sees through the catalog:
```
root@127.0.0.1:43341/defaultdb> explain (opt, catalog) select * from t;
                                                                      text
-------------------------------------------------------------------------------------------------------------------------------------------------
  TABLE t
   ├── x int
   ├── rowid int not null default (unique_rowid()) [hidden]
   ├── crdb_internal_x_shard_10 int4 not null as (mod(fnv32(CAST(x AS STRING)), 10)) stored [hidden]
   ├── CHECK (crdb_internal_x_shard_10 IN (0:::INT8, 1:::INT8, 2:::INT8, 3:::INT8, 4:::INT8, 5:::INT8, 6:::INT8, 7:::INT8, 8:::INT8, 9:::INT8))
   ├── INDEX primary
   │    └── rowid int not null default (unique_rowid()) [hidden]
   └── INDEX t_crdb_internal_x_shard_10_x_idx
        ├── crdb_internal_x_shard_10 int4 not null as (mod(fnv32(CAST(x AS STRING)), 10)) stored [hidden]
        ├── x int
        └── rowid int not null default (unique_rowid()) [hidden]
  scan t
   ├── check constraint expressions
   │    └── crdb_internal_x_shard_10 IN (0, 1, 2, 3, 4, 5, 6, 7, 8, 9)
   └── computed column expressions
        └── crdb_internal_x_shard_10
             └── mod(fnv32(x::STRING), 10)
```

The `crdb_internal_x_shard_10` column is defined as `not null` with the formula `mod(fnv32(CAST(x AS STRING)), 10)`. But this formula returns NULL when x is NULL.

This means that we can't insert NULL values, and index creation will fail if there are null values:
```
ERROR: null value in column "crdb_internal_x_shard_10" violates not-null constraint
```

We should either:
 - allow NULL values and make sure they map to bucket 0, or
 - require the hash column to be marked as non-null, or
 - automatically mark the hash column as non-null when creating index.

### PR DESCRIPTION
**Pull request by ajwerner**
This commit fixes a bug whereby NULL valued members of hash-sharded indexes
would produce a NULL shard column value. This was especially problematic
because the shard column is marked NOT NULL. This bug meant that such
NULL values could not be added to the table.

The commit chooses to coalesce NULL values with the empty string for the
purposes of hashing. This choice is relatively arbitrary but is simple
and cheap.

Fixes #47055

Release note (bug fix): Fix bug preventing NULL index members from being
added to hash sharded indexes.

### CODE REVIEW

File: pkg/sql/create_table.go [hunk 1]
```diff
@@ -1852,7 +1852,23 @@ func makeHashShardComputeExpr(colNames []string, buckets int) *string {
...
+				// we'll have a collision for every combination of NULLable string
+				// columns. That seems just fine.
+				&tree.CoalesceExpr{
+					Name: "COALESCE",
+					Exprs: tree.Exprs{
+						&tree.CastExpr{
+							Type: types.String,
+							Expr: unresolvedName(colName),
+						},
+						tree.NewStrVal(""),
```
Comment (rohany) [inline pkg/sql/create_table.go:1869]: Should this be a DString datum rather than a strval?

File: pkg/sql/logictest/testdata/logic_test/hash_sharded_index [hunk 2]
```diff
@@ -276,26 +276,26 @@ CREATE TABLE sharded_secondary (a INT8, INDEX (a) USING HASH WITH BUCKET_COUNT=1
...
-                │           render 0       mod(fnv32(column1::STRING), 12)                    ·                                    ·
-                │           render 1       unique_rowid()                                     ·                                    ·
-                │           render 2       column1                                            ·                                    ·
-                └── values  ·              ·                                                  (column1)                            ·
-·                           size           1 column, 2 rows                                   ·                                    ·
-·                           row 0, expr 0  1                                                  ·                                    ·
-·                           row 1, expr 0  2                                                  ·                                    ·
+·                           distributed    false                                                  ·                                    ·
```
Comment (rohany) [inline pkg/sql/logictest/testdata/logic_test/hash_sharded_index:279]: While you're here, can you move this from logictest into the execbuilder tests? Tests that look at plans shouldn't be in the logictest/ dir.

**Review by rohany — CHANGES_REQUESTED** [review]

**Review by ajwerner — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/47311)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner and @rohany)

___
*[pkg/sql/create_table.go, line 1869 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/47311#-M4WgCqovrsPnUEEaXqP-r1-1869:-M4X2sCTAmqPXFwh4n4S:b3g2tcg) ([raw file](https://github.com/cockroachdb/cockroach/blob/e80cbff4d7addff5e838b08539eb9636b7a33126/pkg/sql/create_table.go#L1869)):*
<details><summary><i>Previously, rohany (Rohan Yadav) wrote…</i></summary><blockquote>

Should this be a DString datum rather than a strval?
</blockquote></details>

Can you help me understand the difference?

**Comment by rohany** [comment]
> Can you help me understand the difference?

A DString is a `Datum`, so when making one it has a resolved type and it is a string.

A StrVal is a string constant that we don't know what type it is -- it could turn into a variety of different types depending on the context. It's mostly used when parsing iirc

**Review by ajwerner — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/47311)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rohany)

___
*[pkg/sql/create_table.go, line 1869 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/47311#-M4WgCqovrsPnUEEaXqP-r1-1869:-M4XPXOy9nPYsSpGQgKS:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/e80cbff4d7addff5e838b08539eb9636b7a33126/pkg/sql/create_table.go#L1869)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

Can you help me understand the difference?
</blockquote></details>

Done.
___
*[pkg/sql/logictest/testdata/logic_test/hash_sharded_index, line 279 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/47311#-M4WgCqovrsPnUEEaXqQ-r1-279:-M4XPXqs10z38CS4QUf9:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/e80cbff4d7addff5e838b08539eb9636b7a33126/pkg/sql/logictest/testdata/logic_test/hash_sharded_index#L279)):*
<details><summary><i>Previously, rohany (Rohan Yadav) wrote…</i></summary><blockquote>

While you're here, can you move this from logictest into the execbuilder tests? Tests that look at plans shouldn't be in the logictest/ dir.
</blockquote></details>

Done.

File: pkg/sql/opt/exec/execbuilder/testdata/hash_sharded_index [hunk 3]
```diff
@@ -0,0 +1,53 @@
+# LogicTest: local
+
```
Comment (rohany) [inline pkg/sql/opt/exec/execbuilder/testdata/hash_sharded_index:2]: missing the set session variable

**Review by rohany — APPROVED** [review]

**Comment by ajwerner** [comment]
TFTR!

bors r=rohany
