### PR TITLE
backupccl: don't restore sql_instances, sqlliveness or lease rows

### LINKED ISSUE #101518: ccl/backupccl: TestBackupTenantImportingTable failed
ccl/backupccl.TestBackupTenantImportingTable [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_StressBazel/9599352?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_StressBazel/9599352?buildTab=artifacts#/) on master @ [8e6cdbd8b3d12ba5d65db101a3abfeb2cb1bf470](https://github.com/cockroachdb/cockroach/commits/8e6cdbd8b3d12ba5d65db101a3abfeb2cb1bf470):

```
=== RUN   TestBackupTenantImportingTable
    test_log_scope.go:161: test logs captured to: /artifacts/tmp/_tmp/95e138e66d69292427dfb9528cf06d04/logTestBackupTenantImportingTable515955645
    test_log_scope.go:79: use -show-logs to present logs inline
    backup_tenant_test.go:101: condition failed to evaluate within 45s: pq: job 856487830635249665: job with status reverting cannot be requested to be canceled
    panic.go:522: -- test log scope end --
test logs left over in: /artifacts/tmp/_tmp/95e138e66d69292427dfb9528cf06d04/logTestBackupTenantImportingTable515955645
--- FAIL: TestBackupTenantImportingTable (54.82s)
```
<p>Parameters: <code>TAGS=bazel,gss</code>
</p>
<details><summary>Help</summary>
<p>

See also: [How To Investigate a Go Test Failure \(internal\)](https://cockroachlabs.atlassian.net/l/c/HgfXfJgM)
</p>
</details>
/cc @cockroachdb/disaster-recovery
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*TestBackupTenantImportingTable.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)
</sub>

Jira issue: CRDB-26985

### PR DESCRIPTION
**Pull request by dt**
Restoring these rows from the old cluster can cause the restored cluster to experience error when trying to plan and run queries that run on 'all' nodes due to the old rows in these tables that track the set of nodes still appearing to be valid until they expire.

Release note: none.
Epic: none.

### CODE REVIEW

File: pkg/ccl/backupccl/key_rewriter.go [hunk 1]
```diff
@@ -229,6 +229,17 @@ func (kr *KeyRewriter) RewriteKey(key []byte, wallTime int64) ([]byte, bool, err
 	// in which case we are restoring as a system tenant.
 	if kr.fromSystemTenant && bytes.HasPrefix(key, keys.TenantPrefix) {
 		k, ok := kr.tenants.rewriteKey(key)
+		if ok {
+			suffix, _, err := keys.DecodeTenantPrefix(key)
+			if err != nil {
+				return nil, false, err
+			}
+			_, tableID, _ := keys.SystemSQLCodec.DecodeTablePrefix(suffix)
```
Comment (msbutler) [inline pkg/ccl/backupccl/key_rewriter.go:237]: Even though you're using the system codec to decode a tenant key, this still works because you've stripped the tenant prefix. It also looks like you swallow the error here which implies this is best effort?

Mind adding a comment here that motivates all of this?

Comment (msbutler) [reply pkg/ccl/backupccl/key_rewriter.go:237]: "We attempt to elide tenant keys from a couple system tables to prevent poor behavior in the restored tenant. This is best effort because the restored tenant can recover even if these keys are restored. Note that we can grab the tenant table ID using the system codec because the tenant prefix has already been stripped from the key."

Comment (dt) [reply pkg/ccl/backupccl/key_rewriter.go:237]: I'm not sure I'd call it 'best effort' -- any key that errors also isn't in one of those tables

Comment (dt) [reply pkg/ccl/backupccl/key_rewriter.go]: Added a comment though explaining why we're skipping these

**Review by msbutler — APPROVED** [review]

File: pkg/ccl/backupccl/key_rewriter.go (hunk 1 above)
Comment (msbutler) [reply pkg/ccl/backupccl/key_rewriter.go]: Thanks!

**Comment by dt** [comment]
@msbutler @stevendanna added exclusion to fingerprinting too

**Review by msbutler — APPROVED** [review]
LGTM though I wonder if the race in Extended CI is caused by this change.

**Comment by dt** [comment]
> if the race in Extended CI is caused by this change.

My guess is that is from https://github.com/cockroachdb/cockroach/pull/97589 ? @rhu713 might know more.
```
==================
WARNING: DATA RACE
Read at 0x00c00d0d5370 by goroutine 338590:
  github.com/cockroachdb/cockroach/pkg/ccl/backupccl.(*routingDatumCache).cachedNodeIDs()
      github.com/cockroachdb/cockroach/pkg/ccl/backupccl/generative_split_and_scatter_processor.go:502 +0x555
  github.com/cockroachdb/cockroach/pkg/ccl/backupccl.runGenerativeSplitAndScatter.func3()
      github.com/cockroachdb/cockroach/pkg/ccl/backupccl/generative_split_and_scatter_processor.go:387 +0x549
  github.com/cockroachdb/cockroach/pkg/util/ctxgroup.Group.GoCtx.func1()
      github.com/cockroachdb/cockroach/pkg/util/ctxgroup/ctxgroup.go:168 +0x4c
  golang.org/x/sync/errgroup.(*Group).Go.func1()
      golang.org/x/sync/errgroup/external/org_golang_x_sync/errgroup/errgroup.go:75 +0x86

Previous write at 0x00c00d0d5370 by goroutine 338570:
  github.com/cockroachdb/cockroach/pkg/ccl/backupccl.(*routingDatumCache).putRoutingDatum()
      github.com/cockroachdb/cockroach/pkg/ccl/backupccl/generative_split_and_scatter_processor.go:496 +0x474
  github.com/cockroachdb/cockroach/pkg/ccl/backupccl.(*generativeSplitAndScatterProcessor).Next()
      github.com/cockroachdb/cockroach/pkg/ccl/backupccl/generative_split_and_scatter_processor.go:199 +0x360
  github.com/cockroachdb/cockroach/pkg/sql/execinfra.Run()
      github.com/cockroachdb/cockroach/pkg/sql/execinfra/base.go:192 +0x59
  github.com/cockroachdb/cockroach/pkg/sql/execinfra.(*ProcessorBaseNoHelper).Run()
      github.com/cockroachdb/cockroach/pkg/sql/execinfra/processorsbase.go:726 +0xcf
  github.com/cockroachdb/cockroach/pkg/ccl/backupccl.(*generativeSplitAndScatterProcessor).Run()
      <autogenerated>:1 +0x6b
  github.com/cockroachdb/cockroach/pkg/sql/flowinfra.(*FlowBase).StartInternal.func1()
      github.com/cockroachdb/cockroach/pkg/sql/flowinfra/flow.go:510 +0x114
  github.com/cockroachdb/cockroach/pkg/sql/flowinfra.(*FlowBase).StartInternal.func2()
      github.com/cockroachdb/cockroach/pkg/sql/flowinfra/flow.go:512 +0x47

Goroutine 338590 (running) created at:
  golang.org/x/sync/errgroup.(*Group).Go()
      golang.org/x/sync/errgroup/external/org_golang_x_sync/errgroup/errgroup.go:72 +0x12e
  github.com/cockroachdb/cockroach/pkg/util/ctxgroup.Group.GoCtx()
      github.com/cockroachdb/cockroach/pkg/util/ctxgroup/ctxgroup.go:167 +0x109
  github.com/cockroachdb/cockroach/pkg/ccl/backupccl.runGenerativeSplitAndScatter()
      github.com/cockroachdb/cockroach/pkg/ccl/backupccl/generative_split_and_scatter_processor.go:364 +0x4fe
  github.com/cockroachdb/cockroach/pkg/ccl/backupccl.(*generativeSplitAndScatterProcessor).Start.func2()
      github.com/cockroachdb/cockroach/pkg/ccl/backupccl/generative_split_and_scatter_processor.go:165 +0x1a4
  github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunAsyncTaskEx.func2()
      github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:470 +0x1f6

Goroutine 338570 (running) created at:
  github.com/cockroachdb/cockroach/pkg/sql/flowinfra.(*FlowBase).StartInternal()
      github.com/cockroachdb/cockroach/pkg/sql/flowinfra/flow.go:509 +0x690
  github.com/cockroachdb/cockroach/pkg/sql/flowinfra.(*FlowBase).Run()
      github.com/cockroachdb/cockroach/pkg/sql/flowinfra/flow.go:568 +0x495
  github.com/cockroachdb/cockroach/pkg/sql/rowflow.(*rowBasedFlow).Run()
      <autogenerated>:1 +0x6e
  github.com/cockroachdb/cockroach/pkg/sql.(*DistSQLPlanner).Run()
      github.com/cockroachdb/cockroach/pkg/sql/distsql_running.go:902 +0x1555
  github.com/cockroachdb/cockroach/pkg/ccl/backupccl.distRestore.func5()
      github.com/cockroachdb/cockroach/pkg/ccl/backupccl/restore_processor_planning.go:301 +0x4d6
  github.com/cockroachdb/cockroach/pkg/util/ctxgroup.Group.GoCtx.func1()
      github.com/cockroachdb/cockroach/pkg/util/ctxgroup/ctxgroup.go:168 +0x4c
  golang.org/x/sync/errgroup.(*Group).Go.func1()
      golang.org/x/sync/errgroup/external/org_golang_x_sync/errgroup/errgroup.go:75 +0x86
```

**Review by jbowens — APPROVED** [review]
> Reviewed 1 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/102413)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dt and @stevendanna)

**Comment by dt** [comment]
the data race reproduces on master so I don't think it needs to block the PR.

TFTR!

bors r+

**Comment by dt** [comment]
`TestStreamPartition/stream-table-cursor-error` timed out. Stressed I for a few minutes locally on this branch and got a few hundred successes and no failures so seems like another random flake.

bors r+
