### PR TITLE
storage: deflake TestStoreRangeSplitAtIllegalKeys

### LINKED ISSUE #13212: github.com/cockroachdb/cockroach/pkg/storage: TestStoreRangeSplitAtIllegalKeys failed under stress
SHA: https://github.com/cockroachdb/cockroach/commits/b3f16992ff9ae8a876031bbe306a9439bd4d955f

Parameters:
```
COCKROACH_PROPOSER_EVALUATED_KV=true
TAGS=
GOFLAGS=
```

Stress build found a failed test: https://teamcity.cockroachdb.com/viewLog.html?buildId=131230&tab=buildLog

```
I170128 07:56:36.986146 32766 gossip/gossip.go:293  [n1] NodeDescriptor set to node_id:1 address:<network_field:"" address_field:"" > attrs:<> locality:<> 
I170128 07:56:36.988152 32766 storage/store.go:1255  [n1,s1]: failed initial metrics computation: [n1,s1]: system config not yet available
I170128 07:56:36.989389 32976 storage/split_queue.go:99  [split,s1,r1/1:/M{in-ax},@c420bd0000] splitting at keys [/Table/11/0 /Table/12/0 /Table/13/0 /Table/14/0]
I170128 07:56:36.991464 32976 storage/replica_command.go:2354  [split,s1,r1/1:/M{in-ax},@c420bd0000] initiating a split of this range at key /Table/11 [r2]
E170128 07:56:36.993613 32976 storage/queue.go:599  [split,s1,r1/1:/{Min-Table/11},@c420bd0000] unable to split [n1,s1,r1/1:/{Min-Table/11}] at key "/Table/12/0": key range /Table/12/0-/Table/12/0 outside of bounds of range /Min-/Max
I170128 07:56:36.993784 32976 storage/split_queue.go:99  [split,s1,r1/1:/{Min-Table/11},@c420bd0000] splitting at keys [/Table/0/0]
I170128 07:56:36.993827 32976 storage/replica_command.go:2354  [split,s1,r1/1:/{Min-Table/11},@c420bd0000] initiating a split of this range at key /Table/0 [r3]
I170128 07:56:36.995641 32766 util/stop/stopper.go:472  quiescing; tasks left:
1      storage/queue.go:507
1      kv/txn_coord_sender.go:920
I170128 07:56:36.995691 32766 util/stop/stopper.go:472  quiescing; tasks left:
1      storage/queue.go:507
	client_split_test.go:88: /Table/10: unexpected split error key range /Table/10-/Table/10 outside of bounds of range /Min-/Table/0
```

### PR DESCRIPTION
**Pull request by petermattis**
Fixes #13212

---
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/13332)

### CODE REVIEW

**Comment by bdarnell** [comment]
:lgtm:

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/13332#-:-KbrpWcPAE0r4HeZNrGN:bnfp4nl)*

File: pkg/storage/client_split_test.go [hunk 1]
```diff
@@ -71,10 +71,13 @@ func adminSplitArgs(key, splitKey roachpb.Key) *roachpb.AdminSplitRequest {
 // at illegal keys.
 func TestStoreRangeSplitAtIllegalKeys(t *testing.T) {
 	defer leaktest.AfterTest(t)()
-	t.Skip("#13212")
 	stopper := stop.NewStopper()
 	defer stopper.Stop()
-	store, _ := createTestStore(t, stopper)
+
+	manual := hlc.NewManualClock(123)
+	cfg := storage.TestStoreConfig(hlc.NewClock(manual.UnixNano, time.Nanosecond))
```
Comment (bdarnell) [inline pkg/storage/client_split_test.go]: Does this need to be a manual clock or can it use `TestStoreConfig(nil)`?

Comment (petermattis) [inline pkg/storage/client_split_test.go]: No, it doesn't. Removed.
