### PR TITLE
acceptance: list all containers

### LINKED ISSUE #6906: circleci: failed tests: TestGossipPeerings
The following test appears to have failed:

[#18320](https://circleci.com/gh/cockroachdb/cockroach/18320):

```
I160525 19:37:49.135656 acceptance/cluster/docker.go:328  unable to create container volumes: Error response from daemon: Conflict. The name "/volumes" is already in use by container 5aeed1e69a157a774b6c6143e5c5d723b1295673184a9f6d324a415b88f50b2a. You have to remove (or rename) that container to be able to reuse that name.
W160525 19:37:49.136447 acceptance/cluster/docker.go:355  error indicated existing container volumes, but none found:
error: Error response from daemon: Conflict. The name "/volumes" is already in use by container 5aeed1e69a157a774b6c6143e5c5d723b1295673184a9f6d324a415b88f50b2a. You have to remove (or rename) that container to be able to reuse that name.
containers: [{ID:25f3ac0f112738044e8a4fc242ae0a29bec1ac029533c81a6088726cd45cd57a Names:[/jovial_turing] Image:cockroachdb/builder:20160305-182433 ImageID:sha256:26823585ed7ee28fa547f4a91d16d6f26765bfcc3b49e8befcd6f67189ad4617 Command:make test 'TESTFLAGS=-v --verbosity=1 --vmodule=monitor=2,tracer=2' Created:1464204673 Ports:[] SizeRw:0 SizeRootFs:0 Labels:map[] State: Status:Exited (0) 2 minutes ago HostConfig:{NetworkMode:default} NetworkSettings:0xc8201145a8 Mounts:[]} {ID:ce78d763c82f1162a5090014ba717226a96fe6852481584741467007ab4cff28 Names:[/nauseous_bardeen] Image:cockroachdb/builder:20160305-182433 ImageID:sha256:26823585ed7ee28fa547f4a91d16d6f26765bfcc3b49e8befcd6f67189ad4617 Command:build/circle-deps.sh docker Created:1464204536 Ports:[] SizeRw:0 SizeRootFs:0 Labels:map[] State: Status:Exited (0) 7 minutes ago HostConfig:{NetworkMode:default} NetworkSettings:0xc8201147d8 Mounts:[]}]
I160525 19:37:49.136483 acceptance/cluster/localcluster.go:658  stopping
--- FAIL: TestGossipPeerings (10.73s)
panic: ContainerCreate: exceeded 10 tries with a 10s timeout [recovered]
	panic: ContainerCreate: exceeded 10 tries with a 10s timeout [recovered]
	panic: ContainerCreate: exceeded 10 tries with a 10s timeout

goroutine 1124 [running]:
panic(0x169ab40, 0xc8204eb7e0)
	/usr/local/go/src/runtime/panic.go:464 +0x3e6
testing.tRunner.func1(0xc8203e21b0)
	/usr/local/go/src/testing/testing.go:467 +0x192
panic(0x169ab40, 0xc8204eb7e0)
	/usr/local/go/src/runtime/panic.go:426 +0x4e9
github.com/cockroachdb/cockroach/acceptance/cluster.(*LocalCluster).stopOnPanic(0xc820130620)
	/go/src/github.com/cockroachdb/cockroach/acceptance/cluster/localcluster.go:238 +0x9b
panic(0x169ab40, 0xc8204eb7e0)
	/usr/local/go/src/runtime/panic.go:426 +0x4e9
github.com/cockroachdb/cockroach/acceptance/cluster.maybePanic(0x7f1c07047028, 0xc8204eb7e0)
	/go/src/github.com/cockroachdb/cockroach/acceptance/cluster/docker.go:166 +0x4b
github.com/cockroachdb/cockroach/acceptance/cluster.(*LocalCluster).initCluster(0xc820130620)
	/go/src/github.com/cockroachdb/cockroach/acceptance/cluster/localcluster.go:366 +0x11f9
github.com/cockroachdb/cockroach/acceptance/cluster.(*LocalCluster).Start(0xc820130620)
	/go/src/github.com/cockroachdb/cockroach/acceptance/cluster/localcluster.go:589 +0xd3
github.com/cockroachdb/cockroach/acceptance.StartCluster(0xc8203e21b0, 0xc820314080, 0x9, 0xc820398260, 0x1, 0x1, 0x12a05f200, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/acceptance/util_test.go:187 +0x3d1
github.com/cockroachdb/cockroach/acceptance.runTestOnConfigs.func1(0xc8203e21b0, 0xc820279eb8, 0x1c658d0)
--
testing.tRunner(0xc8203e21b0, 0x240ea68)
	/usr/local/go/src/testing/testing.go:473 +0x98
created by testing.RunTests
	/usr/local/go/src/testing/testing.go:582 +0x892

goroutine 1 [chan receive]:
testing.RunTests(0x1c67b98, 0x240e9c0, 0x18, 0x18, 0xc820261d01)
	/usr/local/go/src/testing/testing.go:583 +0x8d2
testing.(*M).Run(0xc82004bef8, 0x1c65820)
	/usr/local/go/src/testing/testing.go:515 +0x81
github.com/cockroachdb/cockroach/acceptance.TestMain(0xc82004bef8)
	/go/src/github.com/cockroachdb/cockroach/acceptance/main_test.go:48 +0x3e
main.main()
	github.com/cockroachdb/cockroach/acceptance/_test/_testmain.go:98 +0x114

goroutine 17 [syscall, 2 minutes, locked to thread]:
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1998 +0x1

goroutine 21 [select, 2 minutes, locked to thread]:
runtime.gopark(0x1c683e8, 0xc820027f28, 0x18ced20, 0x6, 0xc82012c018, 0x2)
	/usr/local/go/src/runtime/proc.go:262 +0x163
runtime.selectgoImpl(0xc820027f28, 0x0, 0x18)
	/usr/local/go/src/runtime/select.go:392 +0xa67
runtime.selectgo(0xc820027f28)
	/usr/local/go/src/runtime/select.go:215 +0x12
runtime.ensureSigM.func1()
	/usr/local/go/src/runtime/signal1_unix.go:279 +0x358
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1998 +0x1

goroutine 6 [chan receive]:
github.com/cockroachdb/cockroach/util/log.(*loggingT).flushDaemon(0x26e9aa0)
	/go/src/github.com/cockroachdb/cockroach/util/log/clog.go:1011 +0x64
created by github.com/cockroachdb/cockroach/util/log.init.1
	/go/src/github.com/cockroachdb/cockroach/util/log/clog.go:598 +0x8a

goroutine 8 [syscall, 2 minutes]:
os/signal.signal_recv(0x0)
	/usr/local/go/src/runtime/sigqueue.go:116 +0x132
os/signal.loop()
	/usr/local/go/src/os/signal/signal_unix.go:22 +0x18
created by os/signal.init.1
	/usr/local/go/src/os/signal/signal_unix.go:28 +0x37

goroutine 9 [chan receive, 2 minutes]:
github.com/cockroachdb/cockroach/acceptance.TestMain.func1()
	/go/src/github.com/cockroachdb/cockroach/acceptance/main_test.go:39 +0xd8
created by github.com/cockroachdb/cockroach/acceptance.TestMain
	/go/src/github.com/cockroachdb/cockroach/acceptance/main_test.go:47 +0x30

goroutine 740 [chan receive, 1 minutes]:
database/sql.(*DB).connectionOpener(0xc8202c40b0)
	/usr/local/go/src/database/sql/sql.go:727 +0x45
created by database/sql.Open
	/usr/local/go/src/database/sql/sql.go:493 +0x33f

goroutine 13 [IO wait, 1 minutes]:
net.runtime_pollWait(0x7f1c07059cf8, 0x72, 0xc8203f0000)
	/usr/local/go/src/runtime/netpoll.go:160 +0x60
net.(*pollDesc).Wait(0xc820359870, 0x72, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc820359870, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).Read(0xc820359810, 0xc8203f0000, 0x1000, 0x1000, 0x0, 0x7f1c07047050, 0xc820014200)
	/usr/local/go/src/net/fd_unix.go:250 +0x23a
net.(*conn).Read(0xc82002a600, 0xc8203f0000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/net.go:172 +0xe4
--
net/http.(*persistConn).readLoop(0xc82036bd40)
	/usr/local/go/src/net/http/transport.go:1069 +0x177
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:853 +0x10a6

goroutine 14 [select, 1 minutes]:
net/http.(*persistConn).writeLoop(0xc82036bd40)
	/usr/local/go/src/net/http/transport.go:1273 +0x472
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:854 +0x10cb

goroutine 375 [IO wait, 1 minutes]:
net.runtime_pollWait(0x7f1c07059ab8, 0x72, 0xc820188000)
	/usr/local/go/src/runtime/netpoll.go:160 +0x60
net.(*pollDesc).Wait(0xc820359b10, 0x72, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc820359b10, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).Read(0xc820359ab0, 0xc820188000, 0x1000, 0x1000, 0x0, 0x7f1c07047050, 0xc820014200)
	/usr/local/go/src/net/fd_unix.go:250 +0x23a
net.(*conn).Read(0xc820114450, 0xc820188000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/net.go:172 +0xe4
--
net/http.(*persistConn).readLoop(0xc8200605b0)
	/usr/local/go/src/net/http/transport.go:1069 +0x177
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:853 +0x10a6

goroutine 161 [select, 1 minutes]:
net/http.(*persistConn).writeLoop(0xc82013e680)
	/usr/local/go/src/net/http/transport.go:1273 +0x472
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:854 +0x10cb

goroutine 1113 [select]:
net/http.(*persistConn).writeLoop(0xc82013eb60)
	/usr/local/go/src/net/http/transport.go:1273 +0x472
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:854 +0x10cb

goroutine 567 [chan receive, 1 minutes]:
database/sql.(*DB).connectionOpener(0xc8200116b0)
	/usr/local/go/src/database/sql/sql.go:727 +0x45
created by database/sql.Open
	/usr/local/go/src/database/sql/sql.go:493 +0x33f

goroutine 871 [IO wait]:
net.runtime_pollWait(0x7f1c07059938, 0x72, 0xc8202c3000)
	/usr/local/go/src/runtime/netpoll.go:160 +0x60
net.(*pollDesc).Wait(0xc820358a00, 0x72, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc820358a00, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).Read(0xc8203589a0, 0xc8202c3000, 0x1000, 0x1000, 0x0, 0x7f1c07047050, 0xc820014200)
	/usr/local/go/src/net/fd_unix.go:250 +0x23a
net.(*conn).Read(0xc82002a278, 0xc8202c3000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/net.go:172 +0xe4
--
net/http.(*persistConn).readLoop(0xc82013f930)
	/usr/local/go/src/net/http/transport.go:1069 +0x177
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:853 +0x10a6

goroutine 1156 [select]:
net/http.(*persistConn).writeLoop(0xc82013ea90)
	/usr/local/go/src/net/http/transport.go:1273 +0x472
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:854 +0x10cb

goroutine 287 [IO wait, 1 minutes]:
net.runtime_pollWait(0x7f1c070599f8, 0x72, 0xc820439000)
	/usr/local/go/src/runtime/netpoll.go:160 +0x60
net.(*pollDesc).Wait(0xc82041c680, 0x72, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc82041c680, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).Read(0xc82041c620, 0xc820439000, 0x1000, 0x1000, 0x0, 0x7f1c07047050, 0xc820014200)
	/usr/local/go/src/net/fd_unix.go:250 +0x23a
net.(*conn).Read(0xc82002a180, 0xc820439000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/net.go:172 +0xe4
--
net/http.(*persistConn).readLoop(0xc82036a750)
	/usr/local/go/src/net/http/transport.go:1069 +0x177
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:853 +0x10a6

goroutine 695 [select]:
net/http.(*persistConn).writeLoop(0xc82013e340)
	/usr/local/go/src/net/http/transport.go:1273 +0x472
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:854 +0x10cb

goroutine 467 [select, 1 minutes]:
net/http.(*persistConn).writeLoop(0xc82036a9c0)
	/usr/local/go/src/net/http/transport.go:1273 +0x472
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:854 +0x10cb

goroutine 694 [IO wait]:
net.runtime_pollWait(0x7f1c07063f80, 0x72, 0xc820348000)
	/usr/local/go/src/runtime/netpoll.go:160 +0x60
net.(*pollDesc).Wait(0xc820358220, 0x72, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc820358220, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).Read(0xc8203581c0, 0xc820348000, 0x1000, 0x1000, 0x0, 0x7f1c07047050, 0xc820014200)
	/usr/local/go/src/net/fd_unix.go:250 +0x23a
net.(*conn).Read(0xc8201142c8, 0xc820348000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/net.go:172 +0xe4
--
net/http.(*persistConn).readLoop(0xc82013e340)
	/usr/local/go/src/net/http/transport.go:1069 +0x177
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:853 +0x10a6

goroutine 535 [chan receive, 1 minutes]:
database/sql.(*DB).connectionOpener(0xc8203a1340)
	/usr/local/go/src/database/sql/sql.go:727 +0x45
created by database/sql.Open
	/usr/local/go/src/database/sql/sql.go:493 +0x33f

goroutine 160 [IO wait, 1 minutes]:
net.runtime_pollWait(0x7f1c070597b8, 0x72, 0xc82040a000)
	/usr/local/go/src/runtime/netpoll.go:160 +0x60
net.(*pollDesc).Wait(0xc82041cf40, 0x72, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc82041cf40, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).Read(0xc82041cee0, 0xc82040a000, 0x1000, 0x1000, 0x0, 0x7f1c07047050, 0xc820014200)
	/usr/local/go/src/net/fd_unix.go:250 +0x23a
net.(*conn).Read(0xc82002a1a8, 0xc82040a000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/net.go:172 +0xe4
--
net/http.(*persistConn).readLoop(0xc82013e680)
	/usr/local/go/src/net/http/transport.go:1069 +0x177
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:853 +0x10a6

goroutine 513 [chan receive, 1 minutes]:
database/sql.(*DB).connectionOpener(0xc8203a0f20)
	/usr/local/go/src/database/sql/sql.go:727 +0x45
created by database/sql.Open
	/usr/local/go/src/database/sql/sql.go:493 +0x33f

goroutine 466 [IO wait, 1 minutes]:
net.runtime_pollWait(0x7f1c07059b78, 0x72, 0xc820438000)
	/usr/local/go/src/runtime/netpoll.go:160 +0x60
net.(*pollDesc).Wait(0xc8203581b0, 0x72, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc8203581b0, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).Read(0xc820358150, 0xc820438000, 0x1000, 0x1000, 0x0, 0x7f1c07047050, 0xc820014200)
	/usr/local/go/src/net/fd_unix.go:250 +0x23a
net.(*conn).Read(0xc8201140b0, 0xc820438000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/net.go:172 +0xe4
--
net/http.(*persistConn).readLoop(0xc82036a9c0)
	/usr/local/go/src/net/http/transport.go:1069 +0x177
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:853 +0x10a6

goroutine 731 [chan receive, 1 minutes]:
database/sql.(*DB).connectionOpener(0xc82042e160)
	/usr/local/go/src/database/sql/sql.go:727 +0x45
created by database/sql.Open
	/usr/local/go/src/database/sql/sql.go:493 +0x33f

goroutine 518 [chan receive, 1 minutes]:
database/sql.(*DB).connectionOpener(0xc8200109a0)
	/usr/local/go/src/database/sql/sql.go:727 +0x45
created by database/sql.Open
	/usr/local/go/src/database/sql/sql.go:493 +0x33f

goroutine 376 [select, 1 minutes]:
net/http.(*persistConn).writeLoop(0xc8200605b0)
	/usr/local/go/src/net/http/transport.go:1273 +0x472
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:854 +0x10cb

goroutine 596 [chan receive, 1 minutes]:
database/sql.(*DB).connectionOpener(0xc82042e630)
	/usr/local/go/src/database/sql/sql.go:727 +0x45
created by database/sql.Open
	/usr/local/go/src/database/sql/sql.go:493 +0x33f

goroutine 288 [select, 1 minutes]:
net/http.(*persistConn).writeLoop(0xc82036a750)
	/usr/local/go/src/net/http/transport.go:1273 +0x472
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:854 +0x10cb

goroutine 872 [select]:
net/http.(*persistConn).writeLoop(0xc82013f930)
	/usr/local/go/src/net/http/transport.go:1273 +0x472
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:854 +0x10cb

goroutine 531 [chan receive, 1 minutes]:
database/sql.(*DB).connectionOpener(0xc8203a1130)
	/usr/local/go/src/database/sql/sql.go:727 +0x45
created by database/sql.Open
	/usr/local/go/src/database/sql/sql.go:493 +0x33f

goroutine 545 [chan receive, 1 minutes]:
database/sql.(*DB).connectionOpener(0xc82042e580)
	/usr/local/go/src/database/sql/sql.go:727 +0x45
created by database/sql.Open
	/usr/local/go/src/database/sql/sql.go:493 +0x33f

goroutine 604 [chan receive, 1 minutes]:
database/sql.(*DB).connectionOpener(0xc82042e790)
	/usr/local/go/src/database/sql/sql.go:727 +0x45
created by database/sql.Open
	/usr/local/go/src/database/sql/sql.go:493 +0x33f

goroutine 614 [chan receive, 1 minutes]:
database/sql.(*DB).connectionOpener(0xc8203a1970)
	/usr/local/go/src/database/sql/sql.go:727 +0x45
created by database/sql.Open
	/usr/local/go/src/database/sql/sql.go:493 +0x33f

goroutine 1176 [runnable]:
github.com/docker/engine-api/client/transport/cancellable.Do.func3(0x7f1c07058c38, 0xc8200149e0, 0xc8204eb830, 0xc820207e60)
	/go/src/github.com/docker/engine-api/client/transport/cancellable/cancellable.go:77
created by github.com/docker/engine-api/client/transport/cancellable.Do
	/go/src/github.com/docker/engine-api/client/transport/cancellable/cancellable.go:84 +0x336

goroutine 1155 [IO wait]:
net.runtime_pollWait(0x7f1c07063bc0, 0x72, 0xc8203f6000)
	/usr/local/go/src/runtime/netpoll.go:160 +0x60
net.(*pollDesc).Wait(0xc820358d80, 0x72, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc820358d80, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).Read(0xc820358d20, 0xc8203f6000, 0x1000, 0x1000, 0x0, 0x7f1c07047050, 0xc820014200)
	/usr/local/go/src/net/fd_unix.go:250 +0x23a
net.(*conn).Read(0xc8201143d8, 0xc8203f6000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/net.go:172 +0xe4
--
net/http.(*persistConn).readLoop(0xc82013ea90)
	/usr/local/go/src/net/http/transport.go:1069 +0x177
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:853 +0x10a6

goroutine 1112 [IO wait]:
net.runtime_pollWait(0x7f1c07059038, 0x72, 0xc8204a9000)
	/usr/local/go/src/runtime/netpoll.go:160 +0x60
net.(*pollDesc).Wait(0xc820305560, 0x72, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc820305560, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).Read(0xc820305500, 0xc8204a9000, 0x1000, 0x1000, 0x0, 0x7f1c07047050, 0xc820014200)
	/usr/local/go/src/net/fd_unix.go:250 +0x23a
net.(*conn).Read(0xc82002a250, 0xc8204a9000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/net.go:172 +0xe4

```
Please assign, take a look and update the issue accordingly.

### PR DESCRIPTION
**Pull request by tbg**
It looks like the implementation of ContainerList in docker/engine-api/client
expects -1 to be passed for listing all containers. This could fix #6906.

---

This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/6946)

### CODE REVIEW

File: acceptance/cluster/docker.go [hunk 1]
```diff
@@ -326,7 +326,10 @@ func (cli resilientDockerClient) ContainerCreate(
 	response, err := cli.APIClient.ContainerCreate(ctx, config, hostConfig, networkingConfig, containerName)
 	if err != nil && strings.Contains(err.Error(), "already in use") {
 		log.Infof("unable to create container %s: %v", containerName, err)
-		containers, cerr := cli.ContainerList(ctx, types.ContainerListOptions{All: true})
+		containers, cerr := cli.ContainerList(ctx, types.ContainerListOptions{
+			All:   true,
+			Limit: -1, // no limit
```
Comment (tamird) [inline acceptance/cluster/docker.go]: can you point to some code here? I think that'd be useful

**Comment by tamird** [comment]
LGTM

**Comment by tschottdorf** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[acceptance/cluster/docker.go, line 331 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6946#-KImtZugyQItm6rMge61-r1-331:-KJ2180-Vuss2VJFBLqL:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/7f9c2138e7d4397d613e859459e1914f4c202971/acceptance/cluster/docker.go#L331)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> can you point to some code here? I think that'd be useful
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6946)*
