### PR TITLE
changefeedccl: deflake TestParquetRows

### LINKED ISSUE #158214: ccl/changefeedccl: TestParquetRows failed
ccl/changefeedccl.TestParquetRows [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Ci_TestsAwsLinuxArm64_UnitTests/20766458?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Ci_TestsAwsLinuxArm64_UnitTests/20766458?buildTab=artifacts#/) on master @ [f37e9c26d7d9affe6496172cdc647d49bd9e7cf7](https://github.com/cockroachdb/cockroach/commits/f37e9c26d7d9affe6496172cdc647d49bd9e7cf7):

```
=== RUN   TestParquetRows
    test_log_scope.go:171: test logs captured to: /artifacts/tmp/_tmp/caa72099da386999b346f93d4299a93a/logTestParquetRows2695337708
    test_log_scope.go:82: use -show-logs to present logs inline
    test_server_shim.go:155: automatically injected a shared process virtual cluster under test; see comment at top of test_server_shim.go for details.
    parquet_test.go:263: -- test log scope end --
test logs left over in: /artifacts/tmp/_tmp/caa72099da386999b346f93d4299a93a/logTestParquetRows2695337708
--- FAIL: TestParquetRows (1.81s)
=== RUN   TestParquetRows/decimal
    row.go:35: 
        	Error Trace:	pkg/ccl/changefeedccl/cdctest/row.go:59
        	            				pkg/ccl/changefeedccl/cdctest/row.go:35
        	            				pkg/ccl/changefeedccl/parquet_test.go:269
        	            				pkg/ccl/changefeedccl/parquet_test.go:181
        	Error:      	Should be true
        	Test:       	TestParquetRows/decimal
--- FAIL: TestParquetRows/decimal (0.24s)
```
<details><summary>Help</summary>
<p>

See also: [How To Investigate a Go Test Failure \(internal\)](https://cockroachlabs.atlassian.net/l/c/HgfXfJgM)
</p>
</details>
/cc @cockroachdb/cdc
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*TestParquetRows.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/bazci/githubpost/issues)

</sub>

Jira issue: CRDB-57166

### PR DESCRIPTION
**Pull request by KeithCh**
Use override instead of setting the cluster setting using a SQL 
statement to prevent a race condition.

Fixes: #158214
Release note: None

### CODE REVIEW

File: pkg/ccl/changefeedccl/parquet_test.go [hunk 1]
```diff
@@ -52,8 +53,9 @@ func TestParquetRows(t *testing.T) {
 	defer srv.Stopper().Stop(ctx)
 	s := srv.ApplicationLayer()
 
-	sysDB := sqlutils.MakeSQLRunner(srv.SystemLayer().SQLConn(t))
-	sysDB.Exec(t, "SET CLUSTER SETTING kv.rangefeed.enabled = true")
+	for _, l := range []serverutils.ApplicationLayerInterface{s, srv.SystemLayer()} {
```
Comment (aerfrei) [inline pkg/ccl/changefeedccl/parquet_test.go:56]: It looks like we're doing this on both the aplication layer and the system layer (hence the range). Why?

Comment (KeithCh) [reply pkg/ccl/changefeedccl/parquet_test.go:56]: Some code paths read from the tenant settings values, others from the system settings values. Doing this just ensures that the value is consistent across them. Also looks like every test that overrides this value does it.

**Review by aerfrei — APPROVED** [review]
lgtm
