### PR TITLE
roachtest: report pubsub sink latency to roachperf

### LINKED ISSUE #159501: roachtest: cdc/pubsub-sink failed
roachtest.cdc/pubsub-sink [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/20862371?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/20862371?buildTab=artifacts#/cdc/pubsub-sink) on release-25.4.2-rc @ [fed2b8351ac420fec6a1eecce0c78e3848d11896](https://github.com/cockroachdb/cockroach/commits/fed2b8351ac420fec6a1eecce0c78e3848d11896):

```
(monitor.go:267).Wait: monitor failure: changefeed[default]: max latency was more than allowed: 1m55.366762562s vs 1m0s
test artifacts and logs in: /artifacts/cdc/pubsub-sink/run_1
```

Parameters:
 - <code>arch=amd64</code>
 - <code>cloud=gce</code>
 - <code>coverageBuild=false</code>
 - <code>cpu=16</code>
 - <code>encrypted=false</code>
 - <code>metamorphicLeases=leader</code>
 - <code>runtimeAssertionsBuild=false</code>
 - <code>ssd=0</code>
<details><summary>Help</summary>
<p>

See: [roachtest README](https://github.com/cockroachdb/cockroach/blob/master/pkg/cmd/roachtest/README.md)

See: [How To Investigate \(internal\)](https://cockroachlabs.atlassian.net/l/c/SSSBr8c7)

See: [Grafana](https://go.crdb.dev/roachtest-grafana/teamcity-20862371/cdc-pubsub-sink/1765789124092/1765791146645)

</p>
</details>
<details><summary>Same failure on other branches</summary>
<p>

- #158753 roachtest: cdc/pubsub-sink failed [A-cdc C-test-failure O-roachtest O-robot P-2 T-cdc X-duplicate branch-release-25.2]
- #158701 roachtest: cdc/pubsub-sink failed [A-cdc C-test-failure O-roachtest O-robot P-2 T-cdc branch-release-24.3]
- #158322 roachtest: cdc/pubsub-sink failed [A-cdc C-test-failure O-roachtest O-robot P-2 T-cdc branch-release-25.3]
</p>
</details>
/cc @cockroachdb/cdc
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*cdc/pubsub-sink.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/bazci/githubpost/issues)

</sub>

Jira issue: CRDB-57897

### PR DESCRIPTION
**Pull request by aerfrei**
Previously, we had a hard latency cutoff of 1 minute that was
enforced in this test. When we received a failure it was hard
to determine how much of a deviation from the average it represented
or how to action.

Now we report to roachperf so that identifying a trend towards
regression should be easier and remove the existing cutoff.

Fixes: https://github.com/cockroachdb/cockroach/issues/159501
Epic: none
Release note: None

### CODE REVIEW

File: pkg/cmd/roachtest/tests/cdc.go [hunk 1]
```diff
@@ -666,6 +695,18 @@ func (ct *cdcTester) runFeedLatencyVerifier(
 	finished := make(chan struct{})
 	ct.mon.Go(func(ctx context.Context) error {
 		defer close(finished)
+
+		// If the feed is not an initial scan, it will not finish but will
+		// indefinitely poll the latency in pollLatencyUntilJobSucceeds. So that
+		// we can still report a single time to roachperf, we report the max
+		// latency to roachperf inside this defer.
+		defer func() {
+			if targets.reportSteadyLatency == nil {
```
Comment (andyyang890) [inline pkg/cmd/roachtest/tests/cdc.go]: nit: reverse the condition and eliminate the extra return

File: pkg/cmd/roachtest/tests/cdc.go [hunk 2]
```diff
@@ -168,6 +168,35 @@ func (ct *cdcTester) startStatsCollection() func() {
 	}
 }
 
+func (ct *cdcTester) exportLatencyToRoachperf(value time.Duration, startTime time.Time) {
```
Comment (andyyang890) [inline pkg/cmd/roachtest/tests/cdc.go:171]: Are you able to provide a screenshot or something showing that it works, or is that not possible until it merges?

File: pkg/cmd/roachtest/tests/cdc.go [hunk 3]
```diff
@@ -830,8 +871,9 @@ func (ct *cdcTester) startGrafana() {
 }
 
 type latencyTargets struct {
-	initialScanLatency time.Duration
-	steadyLatency      time.Duration
+	initialScanLatency  time.Duration
+	steadyLatency       time.Duration
+	reportSteadyLatency func(duration time.Duration)
```
Comment (andyyang890) [inline pkg/cmd/roachtest/tests/cdc.go]: It seems a little strange to me to include the reporting callback in the latency targets passed to the latency verifier. Maybe instead the latency verifier could return the max steady latency and then you can call the report function from the test?

File: pkg/cmd/roachtest/tests/cdc.go (hunk 2 above)
Comment (aerfrei) [reply pkg/cmd/roachtest/tests/cdc.go:171]: There's a three step process:
- Generating the stats.json, this looks like `{"total":{"Max latency (s)":29.278690065},"stats":{}}` now. 
- There's a middle step of roachperf collecting and processing the stats.jsons which I don't think we have visibility into.
- I ran roachperf locally and manually put in the file format I was expecting and saw the chart get generated as expected. This is somewhat artificial, but we can't do this with actual data until we actually export those stats.jsons.

Screenshot 2026-01-23 at 2 12 59 PM

File: pkg/cmd/roachtest/tests/cdc.go (hunk 3 above)
Comment (aerfrei) [reply pkg/cmd/roachtest/tests/cdc.go]: Because the latency verifier runs asynchronously and the polling doesn’t complete until the job finishes, I had trouble making this work. Is there a way you’d suggest doing this within runFeedLatencyVerifier? As it stands, that function doesn’t really return or complete. This wasn’t my preferred approach, but I wasn’t able to find a better alternative.

File: pkg/cmd/roachtest/tests/cdc.go [hunk 4]
```diff
@@ -168,6 +168,35 @@ func (ct *cdcTester) startStatsCollection() func() {
 	}
 }
 
+func (ct *cdcTester) exportLatencyToRoachperf(value time.Duration, startTime time.Time) {
+	if ct.promCfg == nil {
+		ct.t.Error("prometheus configuration is nil")
```
Comment (andyyang890) [inline pkg/cmd/roachtest/tests/cdc.go]: What's the reason for changing all the `Fatal` calls to `Error`?

File: pkg/cmd/roachtest/tests/cdc.go (hunk 3 above)
Comment (andyyang890) [reply pkg/cmd/roachtest/tests/cdc.go]: Hmm ok, I'd still like to extract it from the `latencyTargets` struct since it's not really a target. Maybe you could pass it as a separate arg to `runFeedLatencyVerifier`?

File: pkg/cmd/roachtest/tests/cdc.go [hunk 5]
```diff
@@ -666,6 +695,17 @@ func (ct *cdcTester) runFeedLatencyVerifier(
 	finished := make(chan struct{})
 	ct.mon.Go(func(ctx context.Context) error {
 		defer close(finished)
+
+		// If the feed is not an initial scan, it will not finish but will
+		// indefinitely poll the latency in pollLatencyUntilJobSucceeds. So that
+		// we can still report a single time to roachperf, we report the max
+		// latency to roachperf inside this defer.
```
Comment (andyyang890) [inline pkg/cmd/roachtest/tests/cdc.go]: I'm somewhat confused by this comment; it seems like it's documenting a design choice but it's not clear to me what the alternative would have been. Would you mind making it more clear?

File: pkg/cmd/roachtest/tests/cdc.go [hunk 6]
```diff
@@ -666,6 +695,17 @@ func (ct *cdcTester) runFeedLatencyVerifier(
 	finished := make(chan struct{})
 	ct.mon.Go(func(ctx context.Context) error {
 		defer close(finished)
+
+		// If the feed is not an initial scan, it will not finish but will
```
Comment (DarrylWong) [inline pkg/cmd/roachtest/tests/cdc.go]: A more general question about the test, but does this imply that for non `initial_scan: 'no'` changefeeds we may not actually verify the initial scan latency? i.e. `verifier.assertValid(ct.t)` races with the roachtest cleanup? I could be missing it but i don't see anywhere else the initial scan latency is used besides `assertValid`.

A similar observation is that it seems unfortunate we rely on this very broad `cdcTester.Close()` to signal the polling to stop, rather than having it be part of a `waitGroup` similar to `waitForWorkload`.

**Review by DarrylWong — APPROVED** [review]
Roachperf changes LGTM, but i'll defer the final stamp to Andy who has better knowledge of the actual test.

File: pkg/cmd/roachtest/tests/cdc.go (hunk 6 above)
Comment (DarrylWong) [reply pkg/cmd/roachtest/tests/cdc.go]: Ahh nevermind, i was mistaken and it is part of the wait group that `cdcTester.Close()` blocks on. In that case I'm not sure I understand why we need this defer?

File: pkg/cmd/roachtest/tests/cdc.go (hunk 5 above)
Comment (aerfrei) [reply pkg/cmd/roachtest/tests/cdc.go]: Sorry, I was misunderstanding something here. Comment no longer needed.

File: pkg/cmd/roachtest/tests/cdc.go (hunk 6 above)
Comment (aerfrei) [reply pkg/cmd/roachtest/tests/cdc.go]: Sorry I misunderstood this. It was not needed.

File: pkg/cmd/roachtest/tests/cdc.go (hunk 4 above)
Comment (aerfrei) [reply pkg/cmd/roachtest/tests/cdc.go]: I'm not sure what happened here, these should be fatal and I changed them for another test as well. This was the issue flagged by claude review and I think claude was correct.

**Review by andyyang890 — APPROVED** [review]

**Review by DarrylWong — APPROVED** [review]

**Comment by aerfrei** [comment]
blathers backport-all
