### PR TITLE
sqlstats: fix fullScan determination and add test coverage

### LINKED ISSUE #107945: sql stats: statements with full scan are incorrectly reported as not having a full scan
**Describe the problem**

This was brought to our attention by a recent escalation by a customer running v22.2. They reported that although they are statements with full cans. The statement details page for a fingerprint indicates full table scans to be true. However, when applying the filter condition "full scan" on the statements fingerprints section on the SQL activity page, the table returns an empty result, when there should be some statements that show up.

**To Reproduce**

This happens in 23.1 and 23.2 as well so reproducing is fairly straightforward. 

1. Run an insights workload
  ```
  $ cockroach workload init insights
  $ cockroach workload run insights
  ```
2. Go to the statements fingerprints section on the SQL activity page, select a statement (preferably one that has a high CPU time) to find one that has a `Full Scan? Yes` in its statements details page. This confirms that there is at least one statement with a Full Scan.
3. Go back to the statements fingerprints section and open filter and check the box that says "Only show statements with full table scans". 
4. Observe an empty table

**Expected behavior**
After selecting "Only show statements with full table scans" from the filter, we should be seeing at least one statement in the table (the one statement fingerprint which is marked as having a full scan in its details page).

**Environment:**
- Happens on 22.2 and 23.1 on single node and multi-node clusters.

**Additional context**
This came from an escalation from a customer. 

Jira issue: CRDB-30266

### PR DESCRIPTION
**Pull request by gtr**
Fixes: #107945.

A recent escalation revealed an issue with the "full scan" filter in the
UI, where the filter was not returning any results. Investigation found
that the "full scan" determination was always evaluating to false due to
an incorrect mapping between statements and their expected full scan
property.

This bug fix addresses the problem by ensuring that when reading data
from the SQL stats table to form a response, the "full scan" is marked
as true if there was at least one full scan count in the aggregate data.

Release note (bug fix): fixes the `fullScan` attribute when reading from
sqlstats to be true when there is at least one fullScanCount in the
metadata.

### CODE REVIEW

**Review by maryliag — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/108354)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @gtr)

___
*[`pkg/sql/sqlstats/persistedsqlstats/sqlstatsutil/json_impl.go` line 110 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/108354#-NbKQN7z0Z7SlvQ_1pO9:-NbKQN7z0Z7SlvQ_1pOA:bqverz1) ([raw file](https://github.com/cockroachdb/cockroach/blob/83aba3f5531b4dd4247fa5239427137a00bcae15/pkg/sql/sqlstats/persistedsqlstats/sqlstatsutil/json_impl.go#L110)):*
> ```Go
> 
> func (s *aggregatedMetadata) jsonFields() jsonFields {
> 	fullScan := s.FullScanCount > 0
> ```

can you do the same with `distSQL` and `failed`?

File: pkg/sql/sqlstats/persistedsqlstats/sqlstatsutil/json_impl.go [hunk 1]
```diff
@@ -107,11 +107,13 @@ func (s *stmtStatsMetadata) jsonFields() jsonFields {
 type aggregatedMetadata appstatspb.AggregatedStatementMetadata
 
 func (s *aggregatedMetadata) jsonFields() jsonFields {
+	fullScan := s.FullScanCount > 0
 	return jsonFields{
 		{"db", (*stringArray)(&s.Databases)},
 		{"appNames", (*stringArray)(&s.AppNames)},
 		{"distSQLCount", (*jsonInt)(&s.DistSQLCount)},
 		{"failedCount", (*jsonInt)(&s.FailedCount)},
+		{"fullScan", (*jsonBool)(&fullScan)},
```
Comment (xinhaoz) [inline pkg/sql/sqlstats/persistedsqlstats/sqlstatsutil/json_impl.go:116]: I think if I understand the issue correctly, this is occurring because we're now aggregating the metadata in the server side api. Previously we did that in the frontend so this means that the returned `metadata` column changed from `stmtStatsMetadata` to `aggregatedMetadata`. It looks like we missed that in the original implementation and so we are now trying to decode the aggregated metadata as the single metadata object. I think the fix is not to add these fields to the aggregatedMetadata, but in the combined statements api we should decode the column as the aggregated version and then use that to populate the fields previously expected. WDYT?

**Review by gtr — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/108354)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @maryliag, @Santamaura, and @xinhaoz)

___
*[`pkg/sql/sqlstats/persistedsqlstats/sqlstatsutil/json_impl.go` line 110 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/108354#-NbKQN7z0Z7SlvQ_1pO9:-NbLmJ805elt5-h-v-XS:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/83aba3f5531b4dd4247fa5239427137a00bcae15/pkg/sql/sqlstats/persistedsqlstats/sqlstatsutil/json_impl.go#L110)):*
<details><summary><i>Previously, maryliag (Marylia Gutierrez) wrote…</i></summary><blockquote>

can you do the same with `distSQL` and `failed`?
</blockquote></details>

Done.
___
*[`pkg/sql/sqlstats/persistedsqlstats/sqlstatsutil/json_impl.go` line 116 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/108354#gh-1287231291:-NbLmXWs9IwUq3XO7bzZ:blph6y3) ([raw file](https://github.com/cockroachdb/cockroach/blob/83aba3f5531b4dd4247fa5239427137a00bcae15/pkg/sql/sqlstats/persistedsqlstats/sqlstatsutil/json_impl.go#L116)):*
Yes, you are correct! 
> I think the fix is not to add these fields to the aggregatedMetadata, but in the combined statements api we should properly decode the column as the aggregated type (since that's what it is) and then use that to populate the fields previously expected. WDYT?

Makes sense, I also decided against adding these fields to aggregatedMetadata and instead decoded the counts and populated the fields based on those counts. See `fillInCountsToBools`.

**Review by maryliag — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/108354#-:-NboPnGQ3dHLhQv9XwxY:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @Santamaura and @xinhaoz)

**Review by maryliag — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/108354)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @gtr, @Santamaura, and @xinhaoz)

___
*[`pkg/server/application_api/sql_stats_test.go` line 536 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/108354#-Nbpu6eM8lTRZ4-SmfSi:-Nbpu6eM8lTRZ4-SmfSj:b-bo3mo4) ([raw file](https://github.com/cockroachdb/cockroach/blob/6e89b137d019965b53825afcdd52baa08d38c7aa/pkg/server/application_api/sql_stats_test.go#L536)):*
> ```Go
> 		{stmt: `DROP INDEX IF EXISTS idx_age`, respQuery: `DROP INDEX IF EXISTS idx_age`, fullScan: false, distSQL: false, failed: false},
> 		{stmt: `CREATE INDEX idx_age ON players (age) STORING (name)`, respQuery: `CREATE INDEX idx_age ON players (age) STORING (name)`, fullScan: false, distSQL: false, failed: false},
> 		{stmt: `SELECT name FROM players WHERE age < 32`, respQuery: `SELECT name FROM players WHERE age < _`, fullScan: false, distSQL: false, failed: false},
> ```

you should also have an example where the same fingerprint have a value for fullScan as true and then when executed again as false, for example
`SELECT name FROM players WHERE age >= 32`, and then confirm if the result is doing the right thing as setting the fullScan to true and on this case you should also check for the execution count to confirm it has 2 executions
___
*[`pkg/server/application_api/sql_stats_test.go` line 542 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/108354#-Nbpt0UnCy_CTcHOGO0V:-Nbpt0UnCy_CTcHOGO0W:bl9de1y) ([raw file](https://github.com/cockroachdb/cockroach/blob/6e89b137d019965b53825afcdd52baa08d38c7aa/pkg/server/application_api/sql_stats_test.go#L542)):*
> ```Go
> 	distSQLMap := make(map[string]bool)
> 	failedMap := make(map[string]bool)
> 	for _, stmt := range statements {
> ```

you create an array, then you create a map for each one, why not create a single map, that has the stmt as key, and a struct with all the other values you will need as its value?

**Review by gtr — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/108354)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @maryliag, @Santamaura, and @xinhaoz)

___
*[`pkg/server/application_api/sql_stats_test.go` line 536 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/108354#-Nbpu6eM8lTRZ4-SmfSi:-NbqoWiREczUErLS5WFZ:b-rvcoz4) ([raw file](https://github.com/cockroachdb/cockroach/blob/6e89b137d019965b53825afcdd52baa08d38c7aa/pkg/server/application_api/sql_stats_test.go#L536)):*
<details><summary><i>Previously, maryliag (Marylia Gutierrez) wrote…</i></summary><blockquote>

you should also have an example where the same fingerprint have a value for fullScan as true and then when executed again as false, for example
`SELECT name FROM players WHERE age >= 32`, and then confirm if the result is doing the right thing as setting the fullScan to true and on this case you should also check for the execution count to confirm it has 2 executions
</blockquote></details>

Got it, I added a new example for `SELECT name FROM players WHERE age >= 32` before and after an index is created. In both cases `fullScan` is true but the count is 1 for the first and 2 for the second. There's also another example, `SELECT name FROM players WHERE age < 32` which is executed after the index is created that should have a `fullScan` as false.
___
*[`pkg/server/application_api/sql_stats_test.go` line 542 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/108354#-Nbpt0UnCy_CTcHOGO0V:-NbqLCotBaGtYJk7yYLA:bnb16ot) ([raw file](https://github.com/cockroachdb/cockroach/blob/6e89b137d019965b53825afcdd52baa08d38c7aa/pkg/server/application_api/sql_stats_test.go#L542)):*
<details><summary><i>Previously, maryliag (Marylia Gutierrez) wrote…</i></summary><blockquote>

you create an array, then you create a map for each one, why not create a single map, that has the stmt as key, and a struct with all the other values you will need as its value?
</blockquote></details>

Good catch, fixed and looks much cleaner. 

Btw I added a few print statements for debugging on CI, I wanted to see if the JSON reading was causing the time limit exceeding.

**Comment by gtr** [comment]
New revision that checks if the process is running under any instance of stress, and increases the timeout if so. Just checking it if works. If it does, I'll clean up the `srvtestutils` to generalize this call.

**Comment by gtr** [comment]
New iteration solves the timeout failure by increasing the HTTP client's timeout to 40s. @maryliag mind taking one last look 👀 ? Thanks!

**Review by j82w — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/108354)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @gtr, @maryliag, @Santamaura, and @xinhaoz)

___
*[`pkg/server/srvtestutils/testutils.go` line 92 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/108354#-NbulttICBdHNspVYLvK:-NbulttICBdHNspVYLvL:biwvyop) ([raw file](https://github.com/cockroachdb/cockroach/blob/b57d51a1252e089f775224a53a3f0d358ade9506/pkg/server/srvtestutils/testutils.go#L92)):*
> ```Go
> // GetStatusJSONProtoWithAdminOption but allows the caller to customize the
> // timeout.
> func GetStatusJSONProtoWithAdminOptionAndTimeout(
> ```

Why is this necessary?
___
*[`pkg/server/application_api/sql_stats_test.go` line 543 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/108354#-NbunPZ74mpGM_-cXPT8:-NbunPZ74mpGM_-cXPT9:b-15q7pz) ([raw file](https://github.com/cockroachdb/cockroach/blob/b57d51a1252e089f775224a53a3f0d358ade9506/pkg/server/application_api/sql_stats_test.go#L543)):*
> ```Go
> 	statements2 := []TestCases{
> 		{stmt: `DROP INDEX IF EXISTS idx_age`, respQuery: `DROP INDEX IF EXISTS idx_age`, fullScan: false, distSQL: false, failed: false, count: 1},
> 		{stmt: `CREATE INDEX idx_age ON players (age) STORING (name)`, respQuery: `CREATE INDEX idx_age ON players (age) STORING (name)`, fullScan: false, distSQL: false, failed: false, count: 1},
> ```

If I understand it correctly schema changes are done as part of a background job. It's not guaranteed to be done before the next statement is executed.
https://www.cockroachlabs.com/docs/v23.1/online-schema-changes
___
*[`pkg/server/application_api/sql_stats_test.go` line 546 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/108354#-NbuoO27Dm-WGpaToXAk:-NbuoO27Dm-WGpaToXAl:bsyufmj) ([raw file](https://github.com/cockroachdb/cockroach/blob/b57d51a1252e089f775224a53a3f0d358ade9506/pkg/server/application_api/sql_stats_test.go#L546)):*
> ```Go
> 		// Since the index is created, the fullScan value should be false.
> 		{stmt: `SELECT name FROM players WHERE age < 32`, respQuery: `SELECT name FROM players WHERE age < _`, fullScan: false, distSQL: false, failed: false, count: 1},
> 		// Although the index is created, the fullScan value should be true because the previous query was not using the index. Its count should also be 2.
> ```

Why merge these together into a single row if the full scan is different?

**Comment by j82w** [comment]
*[`pkg/server/application_api/sql_stats_test.go` line 546 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/108354#-NbuoO27Dm-WGpaToXAk:-NbutWGa032afS00gSMe:b-e4gx3o) ([raw file](https://github.com/cockroachdb/cockroach/blob/b57d51a1252e089f775224a53a3f0d358ade9506/pkg/server/application_api/sql_stats_test.go#L546)):*
<details><summary><i>Previously, j82w (Jake) wrote…</i></summary><blockquote>

Why merge these together into a single row if the full scan is different?
</blockquote></details>

Wondering if a new count should be added to remove the ambiguity.

**Comment by j82w** [comment]
*[`pkg/server/combined_statement_stats.go` line 715 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/108354#-NbuuQfL6puqKxsi6GaS:-NbuuQfL6puqKxsi6GaT:bikg3q3) ([raw file](https://github.com/cockroachdb/cockroach/blob/b57d51a1252e089f775224a53a3f0d358ade9506/pkg/server/combined_statement_stats.go#L715)):*
> ```Go
> 		}
> 
> 		err := fillInCountsToBools(metadataJSON, &stmt.Key.KeyData)
> ```

Why use  `metadataJSON` instead of the parsed `metadata` object and avoid the expensive json parsing?

**Comment by j82w** [comment]
*[`pkg/server/application_api/sql_stats_test.go` line 608 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/108354#-Nbuydd537oDhxlb7PT-:-Nbuydd537oDhxlb7PT0:bg1xl69) ([raw file](https://github.com/cockroachdb/cockroach/blob/b57d51a1252e089f775224a53a3f0d358ade9506/pkg/server/application_api/sql_stats_test.go#L608)):*
> ```Go
> 			}
> 
> 			if actualCount != int64(expectedData.count) {
> ```

nit: require.Equal

**Review by gtr — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/108354)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @j82w, @maryliag, @Santamaura, and @xinhaoz)

___
*[`pkg/server/srvtestutils/testutils.go` line 92 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/108354#-NbulttICBdHNspVYLvK:-Nbuqbrh4OcDrlzQd2Mz:bwqsy0i) ([raw file](https://github.com/cockroachdb/cockroach/blob/b57d51a1252e089f775224a53a3f0d358ade9506/pkg/server/srvtestutils/testutils.go#L92)):*
<details><summary><i>Previously, j82w (Jake) wrote…</i></summary><blockquote>

Why is this necessary?
</blockquote></details>

Earlier, the stress tests would cause requests to produce a `context deadline exceeded` [error in CI](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_BazelExtendedCi/11244657?hideProblemsFromDependencies=false&hideTestsFromDependencies=false&expandBuildChangesSection=true&expandBuildProblemsSection=true&expandBuildTestsSection=true). This was because the http client had a timeout of 10s. I added this new function to allow adding more time to the http client's timeout (if under stress) to fix it.
___
*[`pkg/server/application_api/sql_stats_test.go` line 543 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/108354#-NbunPZ74mpGM_-cXPT8:-Nbutxwi5hTO4bADB0Z6:brvc1kt) ([raw file](https://github.com/cockroachdb/cockroach/blob/b57d51a1252e089f775224a53a3f0d358ade9506/pkg/server/application_api/sql_stats_test.go#L543)):*
<details><summary><i>Previously, j82w (Jake) wrote…</i></summary><blockquote>

If I understand it correctly schema changes are done as part of a background job. It's not guaranteed to be done before the next statement is executed.
https://www.cockroachlabs.com/docs/v23.1/online-schema-changes
</blockquote></details>

Ah that's right, I missed that. There was one [CI failure](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_BazelExtendedCi/11331304?hideProblemsFromDependencies=false&hideTestsFromDependencies=false&expandBuildChangesSection=true&expandBuildProblemsSection=true&expandBuildTestsSection=true) under stress that might be related to this. I haven't seen this fail locally but I can see it being flaky under stress.

I think since the schema changes are executed as background jobs, one option would be to block until we can confirm that the schema change and the associated index backfill are marked as complete before executing the following query. WDYT?
___
*[`pkg/server/application_api/sql_stats_test.go` line 546 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/108354#-NbuoO27Dm-WGpaToXAk:-NbuwSZAE_lexs38iAfm:b32rf54) ([raw file](https://github.com/cockroachdb/cockroach/blob/b57d51a1252e089f775224a53a3f0d358ade9506/pkg/server/application_api/sql_stats_test.go#L546)):*
> Why merge these together into a single row if the full scan is different?

I'm a little confused here. Are you referring to the `SELECT name FROM players WHERE age < 32` and `SELECT name FROM players WHERE age >= 32` test cases? I'm expecting the second one (`WHERE age >= 32`) to have fullScan as false since there was a previous execution of that same query that was run "before" the index was created and since we're aggregating the fullScan, it should still show as having a fullScan for that fingerprint. Additionally, I added that `count: 2` to confirm that there was indeed a previous execution of that statement.

> Wondering if a new count should be added to remove the ambiguity.

My intention for count in the test cases was to confirm that the queries were being run the expected number of times, perhaps it should be renamed to executionCount to be more precise. WDYT?

**Comment by j82w** [comment]
*[`pkg/server/application_api/sql_stats_test.go` line 579 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/108354#-NbuymsbAeVoF7A2cNvH:-NbuymsbAeVoF7A2cNvI:bdqqdbc) ([raw file](https://github.com/cockroachdb/cockroach/blob/b57d51a1252e089f775224a53a3f0d358ade9506/pkg/server/application_api/sql_stats_test.go#L579)):*
> ```Go
> 
> 		err := srvtestutils.GetStatusJSONProtoWithAdminOptionAndTimeout(firstServerProto, endpoint, &resp, false, timeout)
> 		if err != nil {
> ```

nit: require.NoError(t, err)

**Comment by j82w** [comment]
*[`pkg/server/application_api/sql_stats_test.go` line 543 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/108354#-NbunPZ74mpGM_-cXPT8:-Nbuz_Av8Ujw6YATed0f:b6u2kk8) ([raw file](https://github.com/cockroachdb/cockroach/blob/b57d51a1252e089f775224a53a3f0d358ade9506/pkg/server/application_api/sql_stats_test.go#L543)):*
<details><summary><i>Previously, gtr (Gerardo Torres Castro) wrote…</i></summary><blockquote>

Ah that's right, I missed that. There was one [CI failure](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_BazelExtendedCi/11331304?hideProblemsFromDependencies=false&hideTestsFromDependencies=false&expandBuildChangesSection=true&expandBuildProblemsSection=true&expandBuildTestsSection=true) under stress that might be related to this. I haven't seen this fail locally but I can see it being flaky under stress.

I think since the schema changes are executed as background jobs, one option would be to block until we can confirm that the schema change and the associated index backfill are marked as complete before executing the following query. WDYT?
</blockquote></details>

I agree that waiting until the schema changes are applied would be the best way.

**Comment by j82w** [comment]
*[`pkg/server/srvtestutils/testutils.go` line 92 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/108354#-NbulttICBdHNspVYLvK:-Nbv-2lVEeYsN-8kNG7K:b2djtc8) ([raw file](https://github.com/cockroachdb/cockroach/blob/b57d51a1252e089f775224a53a3f0d358ade9506/pkg/server/srvtestutils/testutils.go#L92)):*
<details><summary><i>Previously, gtr (Gerardo Torres Castro) wrote…</i></summary><blockquote>

Earlier, the stress tests would cause requests to produce a `context deadline exceeded` [error in CI](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_BazelExtendedCi/11244657?hideProblemsFromDependencies=false&hideTestsFromDependencies=false&expandBuildChangesSection=true&expandBuildProblemsSection=true&expandBuildTestsSection=true). This was because the http client had a timeout of 10s. I added this new function to allow adding more time to the http client's timeout (if under stress) to fix it.
</blockquote></details>

Are all the other tests skipping stress? Trying to understand why only this test needs it.

**Comment by j82w** [comment]
*[`pkg/server/application_api/sql_stats_test.go` line 546 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/108354#-NbuoO27Dm-WGpaToXAk:-Nbv-XbvECMrxZf54mda:bku4svd) ([raw file](https://github.com/cockroachdb/cockroach/blob/b57d51a1252e089f775224a53a3f0d358ade9506/pkg/server/application_api/sql_stats_test.go#L546)):*
<details><summary><i>Previously, gtr (Gerardo Torres Castro) wrote…</i></summary><blockquote>

> Why merge these together into a single row if the full scan is different?

I'm a little confused here. Are you referring to the `SELECT name FROM players WHERE age < 32` and `SELECT name FROM players WHERE age >= 32` test cases? I'm expecting the second one (`WHERE age >= 32`) to have fullScan as false since there was a previous execution of that same query that was run "before" the index was created and since we're aggregating the fullScan, it should still show as having a fullScan for that fingerprint. Additionally, I added that `count: 2` to confirm that there was indeed a previous execution of that statement.

> Wondering if a new count should be added to remove the ambiguity.

My intention for count in the test cases was to confirm that the queries were being run the expected number of times, perhaps it should be renamed to executionCount to be more precise. WDYT?
</blockquote></details>

I was wondering if it was better to have `"fullScan"=true,"fullScanCount=42` so if you looked at the results you could tell if only a single query did a full scan or if all of them did.

**Comment by j82w** [comment]
*[`pkg/server/combined_statement_stats.go` line 698 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/108354#-NcN6tssC2Xs1whuJlb8:-NcN6tssC2Xs1whuJlb9:bqptpl1) ([raw file](https://github.com/cockroachdb/cockroach/blob/052abd998918873ef711fe3d4626f0546873b5fd/pkg/server/combined_statement_stats.go#L698)):*
> ```Go
> 		}
> 
> 		metadata := appstatspb.CollectedStatementStatistics{
> ```

Ideally it should just return the aggregateMetadataJSON instead of converting the aggregate back to a single entry, but that would be a breaking change. I'm not sure if it's worth changing just to avoid the logic below. I just think it's bad because it makes the stats ambiguous. A single full scan or failure means they all failed. @maryliag what do you think?

**Comment by j82w** [comment]
*[`pkg/server/application_api/sql_stats_test.go` line 600 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/108354#-NcNEWi03GHNFGCtqLQQ:-NcNEWi03GHNFGCtqLQR:b-y5kndi) ([raw file](https://github.com/cockroachdb/cockroach/blob/052abd998918873ef711fe3d4626f0546873b5fd/pkg/server/application_api/sql_stats_test.go#L600)):*
> ```Go
> 	checkCombinedStmtStats(statementsBeforeIdx)
> 
> 	// Wait for the job which creates the index to complete.
> ```

This still has a race condition. You need to split up the queries.
1. Execute without index
2. Validate
3. Add index.
4. Wait for index to be done
5. Execute queries 
6. Validate

**Review by maryliag — COMMENTED** [review]
> Reviewed 1 of 5 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/108354)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @gtr, @j82w, @Santamaura, and @xinhaoz)

___
*[`pkg/server/combined_statement_stats.go` line 698 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/108354#-NcN6tssC2Xs1whuJlb8:-NcNEyr42vGiPDAt1RQi:b-e9gqki) ([raw file](https://github.com/cockroachdb/cockroach/blob/052abd998918873ef711fe3d4626f0546873b5fd/pkg/server/combined_statement_stats.go#L698)):*
<details><summary><i>Previously, j82w (Jake) wrote…</i></summary><blockquote>

Ideally it should just return the aggregateMetadataJSON instead of converting the aggregate back to a single entry, but that would be a breaking change. I'm not sure if it's worth changing just to avoid the logic below. I just think it's bad because it makes the stats ambiguous. A single full scan or failure means they all failed. @maryliag what do you think?
</blockquote></details>

The ideal solution would be return the counts to the endpoint, and then the UI would handle the filter of when show something with full scan, etc. That is what we do on the statement details endpoint+UI.
On the overview page, we don't show the count, so this flag end up working as a "has at least one full scan" and not a "all where full scan". If we ever decide to have a filter on non-full scan, this current implementation wouldn't work.
Since right now this is causing a bug and we don't want to break compatibility I would say:
- Return the flag, using the count to calculate (like you have it here)
- Create a new issue for returning the count for these values, not a boolean, and then have the UI use the new field to populate

**Review by gtr — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/108354)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @j82w, @maryliag, @Santamaura, and @xinhaoz)

___
*[`pkg/server/combined_statement_stats.go` line 715 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/108354#-NbuuQfL6puqKxsi6GaS:-NcNOtjQ7xukIeleqFmC:bt2vr1b) ([raw file](https://github.com/cockroachdb/cockroach/blob/b57d51a1252e089f775224a53a3f0d358ade9506/pkg/server/combined_statement_stats.go#L715)):*
<details><summary><i>Previously, j82w (Jake) wrote…</i></summary><blockquote>

Why use  `metadataJSON` instead of the parsed `metadata` object and avoid the expensive json parsing?
</blockquote></details>

Fixed.
___
*[`pkg/server/combined_statement_stats.go` line 698 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/108354#-NcN6tssC2Xs1whuJlb8:-NcNOViH-tRmSU4Lvq9m:b-az8ipr) ([raw file](https://github.com/cockroachdb/cockroach/blob/052abd998918873ef711fe3d4626f0546873b5fd/pkg/server/combined_statement_stats.go#L698)):*
<details><summary><i>Previously, maryliag (Marylia Gutierrez) wrote…</i></summary><blockquote>

The ideal solution would be return the counts to the endpoint, and then the UI would handle the filter of when show something with full scan, etc. That is what we do on the statement details endpoint+UI.
On the overview page, we don't show the count, so this flag end up working as a "has at least one full scan" and not a "all where full scan". If we ever decide to have a filter on non-full scan, this current implementation wouldn't work.
Since right now this is causing a bug and we don't want to break compatibility I would say:
- Return the flag, using the count to calculate (like you have it here)
- Create a new issue for returning the count for these values, not a boolean, and then have the UI use the new field to populate
</blockquote></details>

Yes that the ideal solution would be to return the counts rather than a boolean and then make the UI handle the counts. I'll create a follow-up issue for that. 
___
*[`pkg/server/application_api/sql_stats_test.go` line 579 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/108354#-NbuymsbAeVoF7A2cNvH:-Nbv133WBphwe4FDSCHW:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/b57d51a1252e089f775224a53a3f0d358ade9506/pkg/server/application_api/sql_stats_test.go#L579)):*
<details><summary><i>Previously, j82w (Jake) wrote…</i></summary><blockquote>

nit: require.NoError(t, err)
</blockquote></details>

Done.
___
*[`pkg/server/application_api/sql_stats_test.go` line 608 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/108354#-Nbuydd537oDhxlb7PT-:-Nbv1k9rD-0V35JZv_Wp:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/b57d51a1252e089f775224a53a3f0d358ade9506/pkg/server/application_api/sql_stats_test.go#L608)):*
<details><summary><i>Previously, j82w (Jake) wrote…</i></summary><blockquote>

nit: require.Equal
</blockquote></details>

Done.
___
*[`pkg/server/application_api/sql_stats_test.go` line 600 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/108354#-NcNEWi03GHNFGCtqLQQ:-NcNOLky-gXeEan8i0N8:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/052abd998918873ef711fe3d4626f0546873b5fd/pkg/server/application_api/sql_stats_test.go#L600)):*
<details><summary><i>Previously, j82w (Jake) wrote…</i></summary><blockquote>

This still has a race condition. You need to split up the queries.
1. Execute without index
2. Validate
3. Add index.
4. Wait for index to be done
5. Execute queries 
6. Validate
</blockquote></details>

Done.

**Comment by j82w** [comment]
*[`pkg/server/application_api/sql_stats_test.go` line 495 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/108354#-NcPP0fZCmuLGFni8UJG:-NcPP0fZCmuLGFni8UJH:b-cg0uqi) ([raw file](https://github.com/cockroachdb/cockroach/blob/c5b20e4ecebe1d2fff5a90f290984c40a3860c0a/pkg/server/application_api/sql_stats_test.go#L495)):*
> ```Go
> 
> 	// Skip under stress until we extend the timeout for the http client.
> 	skip.UnderStressWithIssue(t, 109184)
> ```

Just to confirm do other test using this endpoint have the same skip? Other than that it LGTM.

**Review by maryliag — APPROVED** [review]
:lgtm:

> Reviewed 1 of 6 files at r7, 1 of 1 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/108354#-:-NcPen8vAywbI6IRhsLY:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @gtr, @j82w, @Santamaura, and @xinhaoz)

**Review by maryliag — COMMENTED** [review]
I meant to say +1 to Jake's comment, LGTM if we have the same skip on the other tests of the same endpoint

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/108354#-:-NcPexjfCO7Tf8s68eRA:b-e21s7i)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @gtr, @j82w, @Santamaura, and @xinhaoz)

**Review by j82w — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/108354#-:-NcSXH4U4BmxQal3LckZ:bnfp4nl)* status: :shipit: complete! 2 of 0 LGTMs obtained (waiting on @gtr, @maryliag, @Santamaura, and @xinhaoz)

**Review by maryliag — APPROVED** [review]
@gtr you can go ahead with the merge with the skipped test, so we can get the fix in. Then on a following PR you can look into the test itself.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/108354#-:-NcSXGNSBJfoQKRJ1zN2:bs23t5v)* status: :shipit: complete! 2 of 0 LGTMs obtained (waiting on @gtr, @j82w, @Santamaura, and @xinhaoz)

**Comment by gtr** [comment]
TFTR! Will look into the tests.
bors r+
