### PR TITLE
jobs: Add tests to validate the canceled job metrics

### LINKED ISSUE #64572: jobs: Add tests to validate the canceled job metrics
Currently, there are only tests for failed and successful schema change jobs, we should add tests for failed jobs too.

### PR DESCRIPTION
**Pull request by fqazi**
Fixes: #64572

Previously, there was no testing to validate job cancelation
metrics, which was inadequate because of the potential danger
of regressing these counters. This, patch adds basic sanity
tests to validate the job cancellation metrics.

Release note: None

### CODE REVIEW

File: pkg/sql/schema_changer_test.go [hunk 1]
```diff
@@ -6238,6 +6238,14 @@ ALTER TABLE t.public.test DROP COLUMN v;
 	require.Equal(t, [][]string{
 		{"1", "2"},
 	}, rows)
+
+	// Validate the job cancellation metrics.
+	rows = runner.QueryStr(t, "SELECT * FROM crdb_internal.feature_usage WHERE feature_name LIKE 'job.%.canceled'")
```
Comment (postamar) [inline pkg/sql/schema_changer_test.go:6243]: Perhaps I misunderstood the issue but is there a specific reason why you're querying the telemetry table instead of `SELECT COUNT(*) FROM system.jobs WHERE status = 'canceled'`?

Comment (fqazi) [reply pkg/sql/schema_changer_test.go:6243]: The intent of these changes is to only provide coverage for the telemetry. I didn't add any coverage for validating the cancelled counters for jobs.

**Review by postamar — COMMENTED** [review]
Is there is a specific reason for why these tests are only for schema change jobs? I'm not saying that there should or shouldn't be but, if there is a reason, it would be worth explaining in the commit message.

**Comment by fqazi** [comment]
> Is there is a specific reason for why these tests are only for schema change jobs? I'm not saying that there should or shouldn't be but, if there is a reason, it would be worth explaining in the commit message.

No specific reason, this code is common so covering one type of cancellation covers all. I'll add that in the commit message. I did look at other tests of CANCEL JOB statements and didn't find any proper coverage on other operations.

**Comment by postamar** [comment]
I'm curious about the status of this PR, is it blocked on something? I can't remember.

**Comment by fqazi** [comment]
> I'm curious about the status of this PR, is it blocked on something? I can't remember.

Think it needed a re-review from now, and I forgot about it. So, I didn't remind you :( @postamar

**Review by postamar — APPROVED** [review]
It must have slipped under my radar as well, sorry. LGTM. Please don't feel bad about nagging reviewers for another look, nothing good can come from letting a PR grow stale.

**Comment by fqazi** [comment]
bors r=postmar

**Comment by fqazi** [comment]
bors cancel

**Comment by fqazi** [comment]
bors r=postamar

**Comment by fqazi** [comment]
bors cancel

**Comment by fqazi** [comment]
bors r=postamar
