### PR TITLE
cli: Print more info to stdout when starting a node

### LINKED ISSUE #8650: Clarify stdout summary when node starts
Per @mberhault, we could improve the current stdout behavior of starting nodes/joining clusters by:

- Including cluster ID
- Removing `join[0]` or augment its behavior when `--join` fails
- Including line "Initialized new cluster" vs. "Joined existing cluster" that could include the cluster ID.

This is a potentially better experience in general but specifically improves visibility into issues when having nodes join clusters.

### Repro Steps
You are able to get an ambiguous stdout message in this scenario:
1. Create network that prohibits communication on port 26257.
2. Start a node (`cockroach start --insecure`), which creates the `cockroach-data` dir.
3. Stop the node.
4. Have the node attempt to join an existing cluster (`cockroach start --join=<other IP address>:26257`)

stdout will then generate something like the following:

```
build:     beta-20160728 @ 2016/07/28 17:02:34 (go1.6.3)
admin:     http://insecure-node3:8080
sql:       postgresql://root@insecure-node3:26257?sslmode=disable
logs:      cockroach-data/logs
store[0]:  path=cockroach-data
join[0]:   <other IP address>:26257
```

### Expectation

An error message that my node is unable to join the cluster, or some indication that it's creating its own new cluster instead of joining the existing cluster.

### Reality

The command including `--join` looks like it's executed, which leads me to believe the node successfully joined the cluster. The line `join[0]:   <other IP address>:26257` reinforces that supposition.

### PR DESCRIPTION
**Pull request by a-robinson**
As mentioned in https://github.com/cockroachdb/cockroach/issues/8650#issuecomment-244426880, I could use a little more explanation around the intended behavior when trying to join a cluster when a local store already exists, but otherwise this provides a little useful more info to stdout when starting a node.

Closes #8650

@mberhault @sploiselle

---

This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/9066)

### CODE REVIEW

**Comment by knz** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[cli/start.go, line 403 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/9066#-KQjgI6qloobm-oyHRKf:-KQjgI6r1fEru-BIqMlA:bdxvu3r) ([raw file](https://github.com/cockroachdb/cockroach/blob/b86c7bc09dfbf4161e3d7edd8b31ec303bf64cae/cli/start.go#L403)):*
> ```Go
> 		if nodeID == server.FirstNodeID {
> 			fmt.Fprintf(tw, "Initialized new cluster\n")
> 			joinStr = "failed to join"
> ```

I'm not sure the message "failed to join" is an appropriate description for this situation.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/9066)*

File: cli/start.go [hunk 1]
```diff
@@ -394,8 +394,26 @@ func runStart(_ *cobra.Command, args []string) error {
...
 	}
-	for i, address := range serverCtx.JoinList {
-		fmt.Fprintf(tw, "join[%d]:\t%s\n", i, address)
+	var joinStr string
+	initialBoot := s.InitialBoot()
+	nodeID := s.NodeID()
+	if initialBoot {
+		if nodeID == server.FirstNodeID {
+			fmt.Fprintf(tw, "Initialized new cluster\n")
+			joinStr = "failed to join"
```
Comment (mberhault) [inline cli/start.go]: we can't have a non-empty `JoinList` and initialize a new cluster. This means that `failed to join` will never be printed.

File: cli/start.go [hunk 2]
```diff
@@ -394,8 +394,26 @@ func runStart(_ *cobra.Command, args []string) error {
...
+			joinStr = "joined"
+		}
+	} else {
+		fmt.Fprintf(tw, "Restarted existing node\n")
+	}
+	fmt.Fprintf(tw, "clusterID:\t%s\n", s.ClusterID())
+	fmt.Fprintf(tw, "nodeID:\t%d\n", nodeID)
+	if joinStr != "" {
+		for i, address := range serverCtx.JoinList {
+			fmt.Fprintf(tw, "%s[%d]:\t%s\n", joinStr, i, address)
```
Comment (mberhault) [inline cli/start.go]: the problem with the `JoinList` is that it sounds like something more than just a flag. Unless we have more details on which address was good, I'd say we need to de-emphasize.

**Comment by a-robinson** [comment]
Review status: 2 of 3 files reviewed at latest revision, 3 unresolved discussions, some commit checks pending.

---

*[cli/start.go, line 403 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/9066#-KQfmx9kURAHz3BQ17NF-r1-403:-KQxS5NTrafXai0rVesk:b8ubtba) ([raw file](https://github.com/cockroachdb/cockroach/blob/b86c7bc09dfbf4161e3d7edd8b31ec303bf64cae/cli/start.go#L403)):*
<details><summary><i>Previously, mberhault (marc) wrote…</i></summary>
> we can't have a non-empty `JoinList` and initialize a new cluster. This means that `failed to join` will never be printed.
</details>
Thanks for the explanation, that's good to hear.

---

*[cli/start.go, line 403 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/9066#-KQjgI6qloobm-oyHRKf:-KQzXbWzmDJOymTxCFX2:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/b86c7bc09dfbf4161e3d7edd8b31ec303bf64cae/cli/start.go#L403)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary>
> I'm not sure the message "failed to join" is an appropriate description for this situation.
</details>
Done.

---

*[cli/start.go, line 415 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/9066#-KQfmx9kURAHz3BQ17NF-r1-415:-KQzXqiQpnJq6kCWlBQ2:bsfj3xm) ([raw file](https://github.com/cockroachdb/cockroach/blob/b86c7bc09dfbf4161e3d7edd8b31ec303bf64cae/cli/start.go#L415)):*
<details><summary><i>Previously, mberhault (marc) wrote…</i></summary>
> the problem with the `JoinList` is that it sounds like something more than just a flag. Unless we have more details on which address was good, I'd say we need to de-emphasize.
</details>
Ack, I've removed for now.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/9066)*

**Comment by a-robinson** [comment]
Throwing on the docs-todo label because this changes the output when running `cockroach start` to something more like this:

```
build:     beta-20160829-411-gb86c7bc-dirty @ 2016/09/06 12:51:18 (go1.7)
admin:     http://localhost:8080
sql:       postgresql://root@localhost:26257?sslmode=disable
logs:      cockroach-data/logs
store[0]:  path=cockroach-data
Initialized new cluster
clusterID:  {e27f29d8-e2d8-4412-99e7-112dd8711984}
nodeID:     1
```

Or this:

```
build:     beta-20160829-411-gb86c7bc-dirty @ 2016/09/06 12:51:18 (go1.7)
admin:     http://localhost:8080
sql:       postgresql://root@localhost:26257?sslmode=disable
logs:      cockroach-data/logs
store[0]:  path=cockroach-data
Restarted existing node in existing cluster
clusterID:  {8414f587-d249-4ae3-bc33-53c0a6ac1a61}
nodeID:     1
```

Or this:
```
build:     beta-20160829-411-gb86c7bc-dirty @ 2016/09/06 12:51:18 (go1.7)
admin:     http://localhost:8081
sql:       postgresql://root@localhost:26258?sslmode=disable
logs:      cockroach-data2/logs
store[0]:  path=cockroach-data2
Joined existing cluster
clusterID:  {e27f29d8-e2d8-4412-99e7-112dd8711984}
nodeID:     2
```

**Comment by knz** [comment]
Ok LGTM but let me bikeshed this just once more. I think the word "existing" in the messages doesn't carry what's happening well enough, especially in the case "existing node to existing cluster". Also it doesn't follow the pattern of the other lines that start with a `prefix:`. What about:
```
status: first node in cluster, initialized new cluster
status: initialized new node in existing cluster
status: node restarted, joined previous cluster
```

or something to the same effect.

---

Review status: 2 of 3 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[cli/start.go, line 406 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/9066#-KQzbgHENujlC_XwIiPR:-KQzbgHENujlC_XwIiPS:bbk30o3) ([raw file](https://github.com/cockroachdb/cockroach/blob/0d4a8460aba595879c19a03a8d1197087906bd52/cli/start.go#L406)):*
> ```Go
> 		}
> 	} else {
> 		fmt.Fprintf(tw, "Restarted existing node in existing cluster\n")
> ```

The word "existing" here is confusing. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/9066#-:-KQzbqfu6Uc2Fjq9w-a-:b1df551)*

**Comment by a-robinson** [comment]
Sure, prefixing them all with "status:" makes for nice consistency with the pattern. I also tried clarifying the messages a bit

---

Review status: 2 of 3 files reviewed at latest revision, 3 unresolved discussions, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/9066#-:-KQzfARcWH3q-T0N-0M0:b-slnxx2)*

**Comment by knz** [comment]
:lgtm:

---

Review status: 2 of 3 files reviewed at latest revision, 2 unresolved discussions, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/9066#-:-KQzh6uwWBy35eNVZVTp:bnfp4nl)*
