### PR TITLE
sql: add metric for schema change job user/database errors

### LINKED ISSUE #68111: sql: Add telemetry counters for schema change error type
Motivating telemetry question:

- Did a schema change fail because of user error (constraint violation) or internal database error?

### PR DESCRIPTION
**Pull request by fqazi**
Fixes: #68111

Previously, we had no way of tracking the reason
a schema change job failed in our metrics. This was
inadequate because we had no way of knowing why
schema jobs failed. To address this, this patch
will add metrics for tracking failures due to constraint
violations and database errors.

Release note (sql change): Add a new metrics to track schema job failure
(sql.schema_changer.errors.all,
sql.schema_changer.errors.constraint_violation,
sql.schema_changer.errors.uncategorized), errors inside the
crdb_internal.feature_usage table.

### CODE REVIEW

File: pkg/sql/schema_changer.go [hunk 1]
```diff
@@ -137,6 +138,18 @@ func NewSchemaChangerForTesting(
...
+// an error introduced by the user. For example a constraint
+// violation.
+func IsConstraintError(err error) bool {
+	pgCode := pgerror.GetPGCode(err)
+	return pgCode == pgcode.CheckViolation ||
+		pgCode == pgcode.UniqueViolation ||
+		pgCode == pgcode.ForeignKeyViolation ||
+		pgCode == pgcode.NotNullViolation ||
+		pgCode == pgcode.IntegrityConstraintViolation
+}
```
Comment (postamar) [inline pkg/sql/schema_changer.go:151]: Assuming this is correct (I honestly don't know) this might not age so well if we need to cover new failure codes. Have you considered making the pgcode itself part of the telemetry counter key? That way you wouldn't have to worry about this. I believe it'd be OK to shift the burden of interpreting these to the client. cc @vy-ton

**Review by postamar — COMMENTED** [review]
Just a few comments from me.

File: pkg/sql/schema_changer.go (hunk 1 above)
Comment (vy-ton) [reply pkg/sql/schema_changer.go:151]: > pgcode itself part of the telemetry counter key
Do you mean a counter for every time a pgcode is returned? Could that be noisy and include instances when these specific codes are encountered in non-schema changes?

When we have the new telemetry logging infra, I think tracking pgcode errors would be a great thing to add.

**Review by fqazi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/68252)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @postamar)

___
*[pkg/sql/schema_changer.go, line 151 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/68252#-Mfo3LnRyHKezcXQNdtw-r1-151:-MgDwvi96yY9yTpwkBR9:bo5dps) ([raw file](https://github.com/cockroachdb/cockroach/blob/26f7760072ca0897a3dabed0b231225616a3d8ae/pkg/sql/schema_changer.go#L151)):*
<details><summary><i>Previously, vy-ton (Vy Ton) wrote…</i></summary><blockquote>

> pgcode itself part of the telemetry counter key
Do you mean a counter for every time a pgcode is returned? Could that be noisy and include instances when these specific codes are encountered in non-schema changes?

When we have the new telemetry logging infra, I think tracking pgcode errors would be a great thing to add.
</blockquote></details>

Does that mean right now we are okay with this approach, due to limitations of existing infrasturcture? I do like the idea of shifting the burden on the clients and just adding this in the key @postamar @vy-ton 
___
*[pkg/sql/schema_changer.go, line 2135 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/68252#-Mfo3LnRyHKezcXQNdtw-r1-2135:-MgDwfSO5aO8fe2llRsG:b3zi6oq) ([raw file](https://github.com/cockroachdb/cockroach/blob/26f7760072ca0897a3dabed0b231225616a3d8ae/pkg/sql/schema_changer.go#L2135)):*
<details><summary><i>Previously, postamar (Marius Posta) wrote…</i></summary><blockquote>

There's nothing wrong with this AllErrors counter per se, but since it can be trivially inferred by summing the other two above I'd be inclined to remove it. 

When running analytics queries on the counters it's nice to be able to aggregate on the parent key. In CRDB this means `SELECT ..., sum(usage_count) FROM crdb_internal.feature_usage WHERE feature_name LIKE 'sql.schema_changer.errors.%' AND ... GROUP BY ...` and in Snowflake it's I don't know what but I'd wager a guess that it's nicer for the clients of these counters to not have to special-case AllErrors.
</blockquote></details>

Good point, I'll drop the allErrors counter, since it's trivial to compute.
___
*[pkg/sql/logictest/testdata/logic_test/alter_table, line 1848 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/68252#-Mfo3LnRyHKezcXQNdtv-r1-1848:-MgDwGuY8vDNbJROkVow:b-ez1z8k) ([raw file](https://github.com/cockroachdb/cockroach/blob/26f7760072ca0897a3dabed0b231225616a3d8ae/pkg/sql/logictest/testdata/logic_test/alter_table#L1848)):*
<details><summary><i>Previously, postamar (Marius Posta) wrote…</i></summary><blockquote>

I find this query quite confusing to be honest. What is the purpose and meaning of the `usage_count > 1` clause? Shouldn't this be a `sum` instead of a `count`?
</blockquote></details>

This is more of a sanity check at the end of the test depending on the mode we are running for the logic test, there may be either N or more failures.  I'll make this saner by having it greater than N. The count is just mean to give a binary indicator that a greater or equal number was seen.

**Review by fqazi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/68252)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @postamar)

___
*[pkg/sql/logictest/testdata/logic_test/alter_table, line 1848 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/68252#-Mfo3LnRyHKezcXQNdtv-r1-1848:-MgE0zjI6Ahgn1w2U839:beg1n96) ([raw file](https://github.com/cockroachdb/cockroach/blob/26f7760072ca0897a3dabed0b231225616a3d8ae/pkg/sql/logictest/testdata/logic_test/alter_table#L1848)):*
<details><summary><i>Previously, fqazi (Faizan Qazi) wrote…</i></summary><blockquote>

This is more of a sanity check at the end of the test depending on the mode we are running for the logic test, there may be either N or more failures.  I'll make this saner by having it greater than N. The count is just mean to give a binary indicator that a greater or equal number was seen.
</blockquote></details>

*Sorry its because the errors sum across the different modes

**Comment by postamar** [comment]
LGTM

**Comment by fqazi** [comment]
@postamar TFTR!

**Comment by fqazi** [comment]
bors r=postamar

**Comment by fqazi** [comment]
bors r=postamar
