### PR TITLE
bazel,colexec: generate crossjoiner.eg.go within bazel 

### LINKED ISSUE #59052: build/bazel: build is broken at `HEAD`
Broken by `92b52f8fc1dcef5bd1f03836d16ed5d3015990d9`, which introduced a new generated file without making the corresponding change in Bazel.

### PR DESCRIPTION
**Pull request by alan-mas**
We broke the bazel build in 52c5f51 when we introduced a new .eg.go
file, without updating the bazel target. We do that here.

Fixes #59052

### CODE REVIEW

**Comment by alan-mas** [comment]
@irfansharif would you mind to confirm the variables part on the commits? (That what I am not totally sure if I am missing something) I think I am missing `type` but I am not sure how to include it
```
// Workaround for bazel auto-generated code. goimports does not automatically
// pick up the right packages when run within the bazel sandbox.
var (
	_ = typeconv.DatumVecCanonicalTypeFamily

)
```

**Comment by rickystewart** [comment]
> @irfansharif would you mind to confirm the variables part on the commits? (That what I am not totally sure if I am missing something) I think I am missing `type` but I am not sure how to include it
> 
> ```
> // Workaround for bazel auto-generated code. goimports does not automatically
> // pick up the right packages when run within the bazel sandbox.
> var (
> 	_ = typeconv.DatumVecCanonicalTypeFamily
> 
> )
> ```

`_ = types.Unknown`?

**Comment by alan-mas** [comment]
> _ = types.Unknown

Just tried and `bazel build //pkg/cmd/cockroach-short --sandbox_debug` is working as well as `make build` let see what TC says about it

**Review by rickystewart — APPROVED** [review]

**Comment by irfansharif** [comment]
Thanks for the patch!

bors r+

**Comment by alan-mas** [comment]
> Thanks for the patch!
> 
> bors r+

And about the vars, is all good? @irfansharif 
```
// Workaround for bazel auto-generated code. goimports does not automatically
// pick up the right packages when run within the bazel sandbox.
var (
	_ = typeconv.DatumVecCanonicalTypeFamily

)
```

I added what Ricky suggested, but seems that you took them away, right? (so might be wrong that change from my side hahah)

**Comment by irfansharif** [comment]
Yup!

File: pkg/sql/colexec/crossjoiner_tmpl.go [hunk 1]
```diff
@@ -23,11 +23,20 @@ import (
...
 	"github.com/cockroachdb/cockroach/pkg/sql/colexecbase/colexecerror"
+	"github.com/cockroachdb/cockroach/pkg/sql/types"
 	"github.com/cockroachdb/errors"
 )
 
+// Workaround for bazel auto-generated code. goimports does not automatically
+// pick up the right packages when run within the bazel sandbox.
+var (
+	_ = typeconv.DatumVecCanonicalTypeFamily
+
```
Comment (rickystewart) [inline pkg/sql/colexec/crossjoiner_tmpl.go:37]: Looks like the linter has an issue with this blank line?
