### PR TITLE
storage: De-flake TestRemovePlaceholderRace

### LINKED ISSUE #16227: storage: TestRemovePlaceholderRace failed under stress
SHA: https://github.com/cockroachdb/cockroach/commits/0bf5973c239ed35e63df9753f61957c39e5e0925

Parameters:
```
TAGS=deadlock
GOFLAGS=
```

Stress build found a failed test: https://teamcity.cockroachdb.com/viewLog.html?buildId=260914&tab=buildLog

```

I170531 08:14:09.848890 1263757 storage/replica_command.go:3565  [s1,r1/1:/M{in-ax}] change replicas (ADD_REPLICA (n2,s2):94): read existing descriptor r1:/M{in-ax} [(n1,s1):1, (n3,s3):3, next=94]
I170531 08:14:09.852108 1267270 storage/store.go:3159  [s2,r1/?:/M{in-ax}] added to replica GC queue (peer suggestion)
I170531 08:14:09.853332 1265163 storage/store.go:2146  [replicaGC,s2,r1/?:/M{in-ax}] removing replica
I170531 08:14:09.855920 1265163 storage/replica.go:714  [replicaGC,s2,r1/?:/M{in-ax}] removed 33 (25+8) keys in 2ms [clear=1ms commit=0ms]
I170531 08:14:09.856646 1457120 storage/replica.go:2857  [s1,r1/1:/M{in-ax}] proposing ADD_REPLICA (n2,s2):94: [(n1,s1):1 (n3,s3):3 (n2,s2):94]
I170531 08:14:09.870633 1263757 storage/replica_command.go:3565  [s1,r1/1:/M{in-ax}] change replicas (REMOVE_REPLICA (n2,s2):94): read existing descriptor r1:/M{in-ax} [(n1,s1):1, (n3,s3):3, (n2,s2):94, next=95]
I170531 08:14:09.877098 1457916 storage/replica.go:2857  [s1,r1/1:/M{in-ax}] proposing REMOVE_REPLICA (n2,s2):94: [(n1,s1):1 (n3,s3):3]
I170531 08:14:09.879614 1263757 storage/replica_raftstorage.go:416  [s1,r1/1:/M{in-ax}] generated preemptive snapshot 69e0b3b7 at index 410
I170531 08:14:09.899507 1263757 storage/store.go:3352  [s1,r1/1:/M{in-ax}] streamed snapshot to (n2,s2):?: kv pairs: 606, log entries: 44, rate-limit: 2.0 MiB/sec, 20ms
W170531 08:14:09.901470 1267226 storage/store.go:3167  [s1] got error from r1, replica (n2,s2):93: raft group deleted
E170531 08:14:09.901713 1267270 storage/store.go:3157  [s2,r1/94:{-}] unable to add to replica GC queue: replica not initialized
I170531 08:14:09.904031 1457978 storage/replica_raftstorage.go:597  [s2,r1/94:{-}] applying preemptive snapshot at index 410 (id=69e0b3b7, encoded size=68220, 1 rocksdb batches, 44 log entries)
I170531 08:14:09.909266 1457978 storage/replica_raftstorage.go:605  [s2,r1/94:/M{in-ax}] applied preemptive snapshot in 5ms [clear=1ms batch=0ms entries=2ms commit=2ms]
I170531 08:14:09.911140 1263757 storage/replica_command.go:3565  [s1,r1/1:/M{in-ax}] change replicas (ADD_REPLICA (n2,s2):95): read existing descriptor r1:/M{in-ax} [(n1,s1):1, (n3,s3):3, next=95]
I170531 08:14:09.920182 1458825 storage/replica.go:2857  [s1,r1/1:/M{in-ax}] proposing ADD_REPLICA (n2,s2):95: [(n1,s1):1 (n3,s3):3 (n2,s2):95]
I170531 08:14:09.942271 1263757 storage/replica_command.go:3565  [s1,r1/1:/M{in-ax}] change replicas (REMOVE_REPLICA (n2,s2):95): read existing descriptor r1:/M{in-ax} [(n1,s1):1, (n3,s3):3, (n2,s2):95, next=96]
I170531 08:14:09.957862 1459687 storage/replica.go:2857  [s1,r1/1:/M{in-ax}] proposing REMOVE_REPLICA (n2,s2):95: [(n1,s1):1 (n3,s3):3]
I170531 08:14:09.961539 1267270 storage/store.go:3159  [s2,r1/95:/M{in-ax}] added to replica GC queue (peer suggestion)
I170531 08:14:09.961691 1263757 storage/replica_raftstorage.go:416  [s1,r1/1:/M{in-ax}] generated preemptive snapshot 3bb3d65f at index 414
I170531 08:14:09.964489 1263757 storage/store.go:3352  [s1,r1/1:/M{in-ax}] streamed snapshot to (n2,s2):?: kv pairs: 612, log entries: 48, rate-limit: 2.0 MiB/sec, 3ms
I170531 08:14:09.964980 1265163 storage/store.go:2146  [replicaGC,s2,r1/95:/M{in-ax}] removing replica
I170531 08:14:09.966965 1265163 storage/replica.go:714  [replicaGC,s2,r1/95:/M{in-ax}] removed 33 (25+8) keys in 2ms [clear=1ms commit=0ms]
I170531 08:14:09.971466 1263757 storage/replica_command.go:3565  [s1,r1/1:/M{in-ax}] change replicas (ADD_REPLICA (n2,s2):96): read existing descriptor r1:/M{in-ax} [(n1,s1):1, (n3,s3):3, next=96]
I170531 08:14:09.976662 1460803 storage/replica.go:2857  [s1,r1/1:/M{in-ax}] proposing ADD_REPLICA (n2,s2):96: [(n1,s1):1 (n3,s3):3 (n2,s2):96]
I170531 08:14:09.985358 1263757 storage/replica_command.go:3565  [s1,r1/1:/M{in-ax}] change replicas (REMOVE_REPLICA (n2,s2):96): read existing descriptor r1:/M{in-ax} [(n1,s1):1, (n3,s3):3, (n2,s2):96, next=97]
I170531 08:14:09.991059 1461443 storage/replica.go:2857  [s1,r1/1:/M{in-ax}] proposing REMOVE_REPLICA (n2,s2):96: [(n1,s1):1 (n3,s3):3]
E170531 08:14:10.001489 1267270 storage/store.go:3157  [s2,r1/96:{-}] unable to add to replica GC queue: replica not initialized
I170531 08:14:10.001717 1263757 storage/replica_raftstorage.go:416  [s1,r1/1:/M{in-ax}] generated preemptive snapshot d775cbb9 at index 418
I170531 08:14:10.004708 1263757 storage/store.go:3352  [s1,r1/1:/M{in-ax}] streamed snapshot to (n2,s2):?: kv pairs: 618, log entries: 52, rate-limit: 2.0 MiB/sec, 3ms
I170531 08:14:10.008220 1461916 storage/replica_raftstorage.go:597  [s2,r1/96:{-}] applying preemptive snapshot at index 418 (id=d775cbb9, encoded size=74604, 1 rocksdb batches, 52 log entries)
I170531 08:14:10.013495 1461916 storage/replica_raftstorage.go:605  [s2,r1/96:/M{in-ax}] applied preemptive snapshot in 5ms [clear=1ms batch=0ms entries=2ms commit=2ms]
I170531 08:14:10.014928 1263757 storage/replica_command.go:3565  [s1,r1/1:/M{in-ax}] change replicas (ADD_REPLICA (n2,s2):97): read existing descriptor r1:/M{in-ax} [(n1,s1):1, (n3,s3):3, next=97]
I170531 08:14:10.018320 1462364 storage/replica.go:2857  [s1,r1/1:/M{in-ax}] proposing ADD_REPLICA (n2,s2):97: [(n1,s1):1 (n3,s3):3 (n2,s2):97]
I170531 08:14:10.037283 1263757 storage/replica_command.go:3565  [s1,r1/1:/M{in-ax}] change replicas (REMOVE_REPLICA (n2,s2):97): read existing descriptor r1:/M{in-ax} [(n1,s1):1, (n3,s3):3, (n2,s2):97, next=98]
I170531 08:14:10.046760 1463337 storage/replica.go:2857  [s1,r1/1:/M{in-ax}] proposing REMOVE_REPLICA (n2,s2):97: [(n1,s1):1 (n3,s3):3]
I170531 08:14:10.049984 1263757 storage/replica_raftstorage.go:416  [s1,r1/1:/M{in-ax}] generated preemptive snapshot b4fcb4d3 at index 422
I170531 08:14:10.060992 1267270 storage/store.go:3159  [s2,r1/97:/M{in-ax}] added to replica GC queue (peer suggestion)
I170531 08:14:10.062527 1265163 storage/store.go:2146  [replicaGC,s2,r1/97:/M{in-ax}] removing replica
I170531 08:14:10.063068 1265163 storage/replica.go:714  [replicaGC,s2,r1/97:/M{in-ax}] removed 33 (25+8) keys in 0ms [clear=0ms commit=0ms]
I170531 08:14:10.070290 1263757 storage/store.go:3352  [s1,r1/1:/M{in-ax}] streamed snapshot to (n2,s2):?: kv pairs: 624, log entries: 56, rate-limit: 2.0 MiB/sec, 20ms
I170531 08:14:10.071173 1464053 storage/replica_raftstorage.go:597  [s2,r1/?:{-}] applying preemptive snapshot at index 422 (id=b4fcb4d3, encoded size=77796, 1 rocksdb batches, 56 log entries)
I170531 08:14:10.081037 1464053 storage/replica_raftstorage.go:605  [s2,r1/?:/M{in-ax}] applied preemptive snapshot in 10ms [clear=0ms batch=0ms entries=9ms commit=1ms]
W170531 08:14:10.081284 1267226 storage/store.go:3167  [s1] got error from r1, replica (n2,s2):97: raft group deleted
I170531 08:14:10.082105 1263757 storage/replica_command.go:3565  [s1,r1/1:/M{in-ax}] change replicas (ADD_REPLICA (n2,s2):98): read existing descriptor r1:/M{in-ax} [(n1,s1):1, (n3,s3):3, next=98]
I170531 08:14:10.088740 1464521 storage/replica.go:2857  [s1,r1/1:/M{in-ax}] proposing ADD_REPLICA (n2,s2):98: [(n1,s1):1 (n3,s3):3 (n2,s2):98]
I170531 08:14:10.093975 1263757 storage/replica_command.go:3565  [s1,r1/1:/M{in-ax}] change replicas (REMOVE_REPLICA (n2,s2):98): read existing descriptor r1:/M{in-ax} [(n1,s1):1, (n3,s3):3, (n2,s2):98, next=99]
I170531 08:14:10.106180 1465421 storage/replica.go:2857  [s1,r1/1:/M{in-ax}] proposing REMOVE_REPLICA (n2,s2):98: [(n1,s1):1 (n3,s3):3]
I170531 08:14:10.115010 1263757 storage/replica_raftstorage.go:416  [s1,r1/1:/M{in-ax}] generated preemptive snapshot b83de2b8 at index 426
I170531 08:14:10.115390 1265163 storage/store.go:2146  [replicaGC,s2,r1/98:/M{in-ax}] removing replica
I170531 08:14:10.116188 1265163 storage/replica.go:714  [replicaGC,s2,r1/98:/M{in-ax}] removed 33 (25+8) keys in 1ms [clear=0ms commit=0ms]
I170531 08:14:10.130370 1263757 storage/store.go:3352  [s1,r1/1:/M{in-ax}] streamed snapshot to (n2,s2):?: kv pairs: 630, log entries: 60, rate-limit: 2.0 MiB/sec, 13ms
I170531 08:14:10.132577 1466180 storage/replica_raftstorage.go:597  [s2,r1/?:{-}] applying preemptive snapshot at index 426 (id=b83de2b8, encoded size=80988, 1 rocksdb batches, 60 log entries)
I170531 08:14:10.140866 1466180 storage/replica_raftstorage.go:605  [s2,r1/?:/M{in-ax}] applied preemptive snapshot in 8ms [clear=0ms batch=0ms entries=7ms commit=1ms]
I170531 08:14:10.142744 1263757 storage/replica_command.go:3565  [s1,r1/1:/M{in-ax}] change replicas (ADD_REPLICA (n2,s2):99): read existing descriptor r1:/M{in-ax} [(n1,s1):1, (n3,s3):3, next=99]
I170531 08:14:10.150005 1466631 storage/replica.go:2857  [s1,r1/1:/M{in-ax}] proposing ADD_REPLICA (n2,s2):99: [(n1,s1):1 (n3,s3):3 (n2,s2):99]
I170531 08:14:10.171144 1263757 storage/replica_command.go:3565  [s1,r1/1:/M{in-ax}] change replicas (REMOVE_REPLICA (n2,s2):99): read existing descriptor r1:/M{in-ax} [(n1,s1):1, (n3,s3):3, (n2,s2):99, next=100]
I170531 08:14:10.201495 1467484 storage/replica.go:2857  [s1,r1/1:/M{in-ax}] proposing REMOVE_REPLICA (n2,s2):99: [(n1,s1):1 (n3,s3):3]
I170531 08:14:10.213577 1267270 storage/store.go:3159  [s2,r1/99:/M{in-ax}] added to replica GC queue (peer suggestion)
I170531 08:14:10.215437 1263757 storage/replica_raftstorage.go:416  [s1,r1/1:/M{in-ax}] generated preemptive snapshot 0e790af9 at index 430
I170531 08:14:10.217019 1265163 storage/store.go:2146  [replicaGC,s2,r1/99:/M{in-ax}] removing replica
I170531 08:14:10.217800 1265163 storage/replica.go:714  [replicaGC,s2,r1/99:/M{in-ax}] removed 33 (25+8) keys in 1ms [clear=0ms commit=0ms]
I170531 08:14:10.244224 1263757 storage/store.go:3352  [s1,r1/1:/M{in-ax}] streamed snapshot to (n2,s2):?: kv pairs: 636, log entries: 64, rate-limit: 2.0 MiB/sec, 29ms
I170531 08:14:10.245434 1467418 storage/replica_raftstorage.go:597  [s2,r1/?:{-}] applying preemptive snapshot at index 430 (id=0e790af9, encoded size=84180, 1 rocksdb batches, 64 log entries)
I170531 08:14:10.260968 1467418 storage/replica_raftstorage.go:605  [s2,r1/?:/M{in-ax}] applied preemptive snapshot in 15ms [clear=0ms batch=0ms entries=14ms commit=1ms]
I170531 08:14:10.262340 1263757 storage/replica_command.go:3565  [s1,r1/1:/M{in-ax}] change replicas (ADD_REPLICA (n2,s2):100): read existing descriptor r1:/M{in-ax} [(n1,s1):1, (n3,s3):3, next=100]
I170531 08:14:10.265688 1468742 storage/replica.go:2857  [s1,r1/1:/M{in-ax}] proposing ADD_REPLICA (n2,s2):100: [(n1,s1):1 (n3,s3):3 (n2,s2):100]
I170531 08:14:10.272157 1263757 storage/replica_command.go:3565  [s1,r1/1:/M{in-ax}] change replicas (REMOVE_REPLICA (n2,s2):100): read existing descriptor r1:/M{in-ax} [(n1,s1):1, (n3,s3):3, (n2,s2):100, next=101]
I170531 08:14:10.285952 1469490 storage/replica.go:2857  [s1,r1/1:/M{in-ax}] proposing REMOVE_REPLICA (n2,s2):100: [(n1,s1):1 (n3,s3):3]
I170531 08:14:10.291270 1267270 storage/store.go:3159  [s2,r1/100:/M{in-ax}] added to replica GC queue (peer suggestion)
I170531 08:14:10.291928 1265163 storage/store.go:2146  [replicaGC,s2,r1/100:/M{in-ax}] removing replica
I170531 08:14:10.293747 1265163 storage/replica.go:714  [replicaGC,s2,r1/100:/M{in-ax}] removed 33 (25+8) keys in 2ms [clear=1ms commit=0ms]
I170531 08:14:10.294675 1263757 storage/replica_raftstorage.go:416  [s1,r1/1:/M{in-ax}] generated preemptive snapshot a2f682fc at index 434
I170531 08:14:10.296018 1263757 storage/store.go:3352  [s1,r1/1:/M{in-ax}] streamed snapshot to (n2,s2):?: kv pairs: 642, log entries: 68, rate-limit: 2.0 MiB/sec, 1ms
I170531 08:14:10.297450 1470333 storage/replica_raftstorage.go:597  [s2,r1/?:{-}] applying preemptive snapshot at index 434 (id=a2f682fc, encoded size=87372, 1 rocksdb batches, 68 log entries)
I170531 08:14:10.303211 1470333 storage/replica_raftstorage.go:605  [s2,r1/?:/M{in-ax}] applied preemptive snapshot in 6ms [clear=0ms batch=0ms entries=4ms commit=1ms]
I170531 08:14:10.304325 1267270 storage/store.go:3159  [s2,r1/?:/M{in-ax}] added to replica GC queue (peer suggestion)
I170531 08:14:10.305436 1263757 storage/replica_command.go:3565  [s1,r1/1:/M{in-ax}] change replicas (ADD_REPLICA (n2,s2):101): read existing descriptor r1:/M{in-ax} [(n1,s1):1, (n3,s3):3, next=101]
I170531 08:14:10.306630 1265163 storage/store.go:2146  [replicaGC,s2,r1/?:/M{in-ax}] removing replica
I170531 08:14:10.307578 1265163 storage/replica.go:714  [replicaGC,s2,r1/?:/M{in-ax}] removed 33 (25+8) keys in 1ms [clear=0ms commit=0ms]
I170531 08:14:10.310647 1471116 storage/replica.go:2857  [s1,r1/1:/M{in-ax}] proposing ADD_REPLICA (n2,s2):101: [(n1,s1):1 (n3,s3):3 (n2,s2):101]
I170531 08:14:10.316535 1263757 storage/replica_command.go:3565  [s1,r1/1:/M{in-ax}] change replicas (REMOVE_REPLICA (n2,s2):101): read existing descriptor r1:/M{in-ax} [(n1,s1):1, (n3,s3):3, (n2,s2):101, next=102]
I170531 08:14:10.321477 1471783 storage/replica.go:2857  [s1,r1/1:/M{in-ax}] proposing REMOVE_REPLICA (n2,s2):101: [(n1,s1):1 (n3,s3):3]
I170531 08:14:10.323557 1264240 storage/replica_raftstorage.go:416  [raftsnapshot,s1,r1/1:/M{in-ax}] generated Raft snapshot 3538e3b8 at index 437
I170531 08:14:10.325440 1263757 storage/replica_raftstorage.go:416  [s1,r1/1:/M{in-ax}] generated preemptive snapshot e157b6db at index 438
I170531 08:14:10.326662 1263757 storage/replica_raftstorage.go:416  [s1,r1/1:/M{in-ax}] generated preemptive snapshot b3f63eae at index 438
I170531 08:14:10.327352 1263757 storage/replica_raftstorage.go:416  [s1,r1/1:/M{in-ax}] generated preemptive snapshot 7f7244a0 at index 438
I170531 08:14:10.327780 1264240 storage/store.go:3352  [raftsnapshot,s1,r1/1:/M{in-ax}] streamed snapshot to (n2,s2):101: kv pairs: 648, log entries: 71, rate-limit: 8.0 MiB/sec, 4ms
I170531 08:14:10.328500 1263757 storage/replica_raftstorage.go:416  [s1,r1/1:/M{in-ax}] generated preemptive snapshot ef1cea88 at index 438
I170531 08:14:10.329142 1263757 storage/replica_raftstorage.go:416  [s1,r1/1:/M{in-ax}] generated preemptive snapshot d9fd865c at index 438
I170531 08:14:10.329505 1471946 storage/replica_raftstorage.go:597  [s2,r1/101:{-}] applying Raft snapshot at index 437 (id=3538e3b8, encoded size=89944, 1 rocksdb batches, 71 log entries)
I170531 08:14:10.335654 1471946 storage/replica_raftstorage.go:605  [s2,r1/101:/M{in-ax}] applied Raft snapshot in 6ms [clear=1ms batch=0ms entries=3ms commit=1ms]
I170531 08:14:10.336336 1263757 storage/replica_raftstorage.go:416  [s1,r1/1:/M{in-ax}] generated preemptive snapshot fe79197e at index 438
I170531 08:14:10.336580 1267270 storage/store.go:3159  [s2,r1/101:/M{in-ax}] added to replica GC queue (peer suggestion)
I170531 08:14:10.337591 1265163 storage/store.go:2146  [replicaGC,s2,r1/101:/M{in-ax}] removing replica
I170531 08:14:10.338840 1265163 storage/replica.go:714  [replicaGC,s2,r1/101:/M{in-ax}] removed 34 (25+9) keys in 1ms [clear=1ms commit=0ms]
I170531 08:14:10.340062 1263757 storage/store.go:3352  [s1,r1/1:/M{in-ax}] streamed snapshot to (n2,s2):?: kv pairs: 648, log entries: 72, rate-limit: 2.0 MiB/sec, 3ms
I170531 08:14:10.342086 1472788 storage/replica_raftstorage.go:597  [s2,r1/?:{-}] applying preemptive snapshot at index 438 (id=fe79197e, encoded size=90564, 1 rocksdb batches, 72 log entries)
I170531 08:14:10.349260 1472788 storage/replica_raftstorage.go:605  [s2,r1/?:/M{in-ax}] applied preemptive snapshot in 7ms [clear=2ms batch=0ms entries=4ms commit=1ms]
F170531 08:14:10.349480 1264923 storage/replica.go:895  [s2,r1/?:/M{in-ax}] leader has uninitialized proposalQuota pool
goroutine 1264923 [running]:
github.com/cockroachdb/cockroach/pkg/util/log.getStacks(0x134d01, 0x14d4a4a2, 0x2c54140, 0x10)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/log/clog.go:891 +0xa7
github.com/cockroachdb/cockroach/pkg/util/log.(*loggingT).outputLogEntry(0x2c55880, 0xc400000004, 0x24f9075, 0x12, 0x37f, 0xc4301a0740, 0x3f)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/log/clog.go:763 +0x548
github.com/cockroachdb/cockroach/pkg/util/log.addStructured(0x7f4acf758128, 0xc434582f60, 0x7f4a00000004, 0x2, 0x0, 0x0, 0xc42b419080, 0x1, 0x1)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/log/structured.go:158 +0x4b3
github.com/cockroachdb/cockroach/pkg/util/log.logDepth(0x7f4acf758128, 0xc434582f60, 0x1, 0xc400000004, 0x0, 0x0, 0xc42b419080, 0x1, 0x1)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/log/log.go:68 +0x8c
github.com/cockroachdb/cockroach/pkg/util/log.Fatal(0x7f4acf758128, 0xc434582f60, 0xc42b419080, 0x1, 0x1)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/log/log.go:171 +0x76
github.com/cockroachdb/cockroach/pkg/storage.(*Replica).updateProposalQuotaRaftMuLocked(0xc42a99ea80, 0x7f4acf758128, 0xc434582f60, 0xc400000000)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/replica.go:895 +0x661
github.com/cockroachdb/cockroach/pkg/storage.(*Replica).handleRaftReadyRaftMuLocked(0xc42a99ea80, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/replica.go:3018 +0x1c70
github.com/cockroachdb/cockroach/pkg/storage.(*Replica).handleRaftReady(0xc42a99ea80, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/replica.go:2965 +0xe0
github.com/cockroachdb/cockroach/pkg/storage.(*Store).processReady(0xc4341cdc00, 0x1)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/store.go:3417 +0x131
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).worker(0xc423d7f500, 0xc42fa002d0)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:217 +0x270
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).Start.func2(0x7f4acf758128, 0xc429250b70)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:168 +0x33
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc42d7249c0, 0xc42fa002d0, 0xc42a97bc40)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:215 +0xf7
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:216 +0xad

goroutine 1 [chan receive]:
testing.(*T).Run(0xc4203e2410, 0x1b3fd81, 0x19, 0x1bf7868, 0xc420643a01)
	/usr/local/go/src/testing/testing.go:698 +0x2f4
testing.runTests.func1(0xc4203e2410)
	/usr/local/go/src/testing/testing.go:882 +0x67
testing.tRunner(0xc4203e2410, 0xc420643b78)
	/usr/local/go/src/testing/testing.go:657 +0x96
testing.runTests(0xc4201da780, 0x27adc20, 0x1b4, 0x1b4, 0xc420643c00)
	/usr/local/go/src/testing/testing.go:888 +0x2c1
testing.(*M).Run(0xc42063df20, 0xc420643d70)
	/usr/local/go/src/testing/testing.go:822 +0xfc
github.com/cockroachdb/cockroach/pkg/storage_test.TestMain(0xc420643f20)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/main_test.go:59 +0x20a
main.main()
	github.com/cockroachdb/cockroach/pkg/storage/_test/_testmain.go:924 +0xf7

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:2197 +0x1

goroutine 22 [chan receive]:
github.com/cockroachdb/cockroach/pkg/util/log.(*loggingT).flushDaemon(0x2c55880)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/log/clog.go:1057 +0x77
created by github.com/cockroachdb/cockroach/pkg/util/log.init.1
	/go/src/github.com/cockroachdb/cockroach/pkg/util/log/clog.go:603 +0xd9

goroutine 36 [syscall]:
os/signal.signal_recv(0xc42045cfc0)
	/usr/local/go/src/runtime/sigqueue.go:116 +0x104
os/signal.loop()
	/usr/local/go/src/os/signal/signal_unix.go:22 +0x22
created by os/signal.init.1
	/usr/local/go/src/os/signal/signal_unix.go:28 +0x41

goroutine 1264240 [select]:
github.com/cockroachdb/cockroach/pkg/storage.(*baseQueue).processLoop.func1(0x7f4acf758128, 0xc42c5d1050)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/queue.go:490 +0x364
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc42afebf10, 0xc43126fc20, 0xc425bf7b80)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:215 +0xf7
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:216 +0xad

goroutine 1265715 [semacquire]:
sync.runtime_notifyListWait(0xc4356f1250, 0xc400000362)
	/usr/local/go/src/runtime/sema.go:298 +0x10b
sync.(*Cond).Wait(0xc4356f1240)
	/usr/local/go/src/sync/cond.go:57 +0x89
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).worker(0xc424620a00, 0xc434c487e0)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:199 +0xac
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).Start.func2(0x7f4acf758128, 0xc427cbbaa0)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:168 +0x33
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc42d80e430, 0xc434c487e0, 0xc42aa45880)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:215 +0xf7
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:216 +0xad

goroutine 1264859 [select]:
github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/transport.(*http2Client).keepalive(0xc431058300)
	/go/src/github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/transport/http2_client.go:1214 +0x4ed
created by github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/transport.newHTTP2Client
	/go/src/github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/transport/http2_client.go:299 +0xeee

goroutine 1264682 [select]:
github.com/cockroachdb/cockroach/pkg/kv.(*TxnCoordSender).printStatsLoop(0xc42bd985b0, 0x7f4acf758128, 0xc42ceccde0)
	/go/src/github.com/cockroachdb/cockroach/pkg/kv/txn_coord_sender.go:255 +0xb47
github.com/cockroachdb/cockroach/pkg/kv.NewTxnCoordSender.func1(0x7f4acf758128, 0xc42ceccde0)
	/go/src/github.com/cockroachdb/cockroach/pkg/kv/txn_coord_sender.go:239 +0x3e
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc42d644a40, 0xc42fa002d0, 0xc42d644a30)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:215 +0xf7
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:216 +0xad

goroutine 1264082 [semacquire]:
sync.runtime_notifyListWait(0xc42720dfd0, 0xc4000005ff)
	/usr/local/go/src/runtime/sema.go:298 +0x10b
sync.(*Cond).Wait(0xc42720dfc0)
	/usr/local/go/src/sync/cond.go:57 +0x89
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).worker(0xc4315a5c80, 0xc43126fc20)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:199 +0xac
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).Start.func2(0x7f4acf758128, 0xc42cbf2120)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:168 +0x33
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc42d527f30, 0xc43126fc20, 0xc42b97a960)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:215 +0xf7
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:216 +0xad

goroutine 1265745 [semacquire]:
sync.runtime_notifyListWait(0xc4356f1250, 0xc40000035e)
	/usr/local/go/src/runtime/sema.go:298 +0x10b
sync.(*Cond).Wait(0xc4356f1240)
	/usr/local/go/src/sync/cond.go:57 +0x89
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).worker(0xc424620a00, 0xc434c487e0)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:199 +0xac
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).Start.func2(0x7f4acf758128, 0xc427ec4e10)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:168 +0x33
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc42d80e620, 0xc434c487e0, 0xc42aa45c40)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:215 +0xf7
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:216 +0xad

goroutine 1264055 [semacquire]:
sync.runtime_notifyListWait(0xc42720dfd0, 0xc4000005df)
	/usr/local/go/src/runtime/sema.go:298 +0x10b
sync.(*Cond).Wait(0xc42720dfc0)
	/usr/local/go/src/sync/cond.go:57 +0x89
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).worker(0xc4315a5c80, 0xc43126fc20)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:199 +0xac
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).Start.func2(0x7f4acf758128, 0xc42c5d0840)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:168 +0x33
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc42d527d80, 0xc43126fc20, 0xc42b97a480)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:215 +0xf7
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:216 +0xad

goroutine 1265728 [semacquire]:
sync.runtime_notifyListWait(0xc4356f1250, 0xc400000380)
	/usr/local/go/src/runtime/sema.go:298 +0x10b
sync.(*Cond).Wait(0xc4356f1240)
	/usr/local/go/src/sync/cond.go:57 +0x89
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).worker(0xc424620a00, 0xc434c487e0)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:199 +0xac
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).Start.func2(0x7f4acf758128, 0xc4296e1080)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:168 +0x33
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc42d80e500, 0xc434c487e0, 0xc42aa45a20)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:215 +0xf7
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:216 +0xad

goroutine 1264058 [semacquire]:
sync.runtime_notifyListWait(0xc42720dfd0, 0xc4000005e8)
	/usr/local/go/src/runtime/sema.go:298 +0x10b
sync.(*Cond).Wait(0xc42720dfc0)
	/usr/local/go/src/sync/cond.go:57 +0x89
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).worker(0xc4315a5c80, 0xc43126fc20)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:199 +0xac
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).Start.func2(0x7f4acf758128, 0xc42c5d08d0)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:168 +0x33
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc42d527db0, 0xc43126fc20, 0xc42b97a4e0)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:215 +0xf7
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:216 +0xad

goroutine 1265723 [semacquire]:
sync.runtime_notifyListWait(0xc4356f1250, 0xc40000037f)
	/usr/local/go/src/runtime/sema.go:298 +0x10b
sync.(*Cond).Wait(0xc4356f1240)
	/usr/local/go/src/sync/cond.go:57 +0x89
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).worker(0xc424620a00, 0xc434c487e0)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:199 +0xac
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).Start.func2(0x7f4acf758128, 0xc427cbbc20)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:168 +0x33
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc42d80e4b0, 0xc434c487e0, 0xc42aa45980)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:215 +0xf7
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:216 +0xad

goroutine 1263973 [chan receive]:
github.com/cockroachdb/cockroach/pkg/util/netutil.ListenAndServeGRPC.func1(0x7f4acf758128, 0xc428fef380)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/netutil/net.go:51 +0x6f
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc42d527300, 0xc43126fb00, 0xc42c58af30)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:215 +0xf7
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:216 +0xad

goroutine 1265711 [semacquire]:
sync.runtime_notifyListWait(0xc4356f1250, 0xc400000387)
	/usr/local/go/src/runtime/sema.go:298 +0x10b
sync.(*Cond).Wait(0xc4356f1240)
	/usr/local/go/src/sync/cond.go:57 +0x89
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).worker(0xc424620a00, 0xc434c487e0)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:199 +0xac
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).Start.func2(0x7f4acf758128, 0xc424bc11a0)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:168 +0x33
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc42d80e380, 0xc434c487e0, 0xc42aa45800)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:215 +0xf7
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:216 +0xad

goroutine 1264070 [semacquire]:
sync.runtime_notifyListWait(0xc42720dfd0, 0xc4000005f9)
	/usr/local/go/src/runtime/sema.go:298 +0x10b
sync.(*Cond).Wait(0xc42720dfc0)
	/usr/local/go/src/sync/cond.go:57 +0x89
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).worker(0xc4315a5c80, 0xc43126fc20)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:199 +0xac
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).Start.func2(0x7f4acf758128, 0xc42c5d0d50)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:168 +0x33
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc42d527e70, 0xc43126fc20, 0xc42b97a680)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:215 +0xf7
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:216 +0xad

goroutine 1265917 [select]:
github.com/cockroachdb/cockroach/pkg/storage.(*baseQueue).processLoop.func1(0x7f4acf758128, 0xc42bac4930)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/queue.go:490 +0x364
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc42d621250, 0xc434c487e0, 0xc42a937a40)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:215 +0xf7
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:216 +0xad

goroutine 1265709 [semacquire]:
sync.runtime_notifyListWait(0xc4356f1250, 0xc40000037c)
	/usr/local/go/src/runtime/sema.go:298 +0x10b
sync.(*Cond).Wait(0xc4356f1240)
	/usr/local/go/src/sync/cond.go:57 +0x89
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).worker(0xc424620a00, 0xc434c487e0)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:199 +0xac
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).Start.func2(0x7f4acf758128, 0xc42437bdd0)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:168 +0x33
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc42d80e340, 0xc434c487e0, 0xc42aa457a0)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:215 +0xf7
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:216 +0xad

goroutine 1264017 [semacquire]:
sync.runtime_notifyListWait(0xc42720dfd0, 0xc400000605)
	/usr/local/go/src/runtime/sema.go:298 +0x10b
sync.(*Cond).Wait(0xc42720dfc0)
	/usr/local/go/src/sync/cond.go:57 +0x89
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).worker(0xc4315a5c80, 0xc43126fc20)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:199 +0xac
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).Start.func2(0x7f4acf758128, 0xc42c5bd500)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:168 +0x33
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc42d527c00, 0xc43126fc20, 0xc42b97a1c0)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:215 +0xf7
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:216 +0xad

goroutine 1265702 [semacquire]:
sync.runtime_notifyListWait(0xc4356f1250, 0xc400000359)
	/usr/local/go/src/runtime/sema.go:298 +0x10b
sync.(*Cond).Wait(0xc4356f1240)
	/usr/local/go/src/sync/cond.go:57 +0x89
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).worker(0xc424620a00, 0xc434c487e0)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:199 +0xac
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).Start.func2(0x7f4acf758128, 0xc424bc1500)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:168 +0x33
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc42d80e2a0, 0xc434c487e0, 0xc42aa456c0)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:215 +0xf7
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:216 +0xad

goroutine 1264071 [semacquire]:
sync.runtime_notifyListWait(0xc42720dfd0, 0xc4000005f3)
	/usr/local/go/src/runtime/sema.go:298 +0x10b
sync.(*Cond).Wait(0xc42720dfc0)
	/usr/local/go/src/sync/cond.go:57 +0x89
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).worker(0xc4315a5c80, 0xc43126fc20)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:199 +0xac
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).Start.func2(0x7f4acf758128, 0xc42c5d0d80)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:168 +0x33
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc42d527e80, 0xc43126fc20, 0xc42b97a6a0)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:215 +0xf7
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:216 +0xad

goroutine 1264011 [semacquire]:
sync.runtime_notifyListWait(0xc42720dfd0, 0xc400000604)
	/usr/local/go/src/runtime/sema.go:298 +0x10b
sync.(*Cond).Wait(0xc42720dfc0)
	/usr/local/go/src/sync/cond.go:57 +0x89
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).worker(0xc4315a5c80, 0xc43126fc20)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:199 +0xac
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).Start.func2(0x7f4acf758128, 0xc42c5bcb70)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:168 +0x33
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc42d527ba0, 0xc43126fc20, 0xc42b97a0a0)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:215 +0xf7
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:216 +0xad

goroutine 1264012 [semacquire]:
sync.runtime_notifyListWait(0xc42720dfd0, 0xc400000607)
	/usr/local/go/src/runtime/sema.go:298 +0x10b
sync.(*Cond).Wait(0xc42720dfc0)
	/usr/local/go/src/sync/cond.go:57 +0x89
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).worker(0xc4315a5c80, 0xc43126fc20)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:199 +0xac
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).Start.func2(0x7f4acf758128, 0xc42c5bcc00)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:168 +0x33
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc42d527bb0, 0xc43126fc20, 0xc42b97a0e0)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:215 +0xf7
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:216 +0xad

goroutine 1265670 [IO wait]:
net.runtime_pollWait(0x7f4ace52ed40, 0x72, 0x0)
	/usr/local/go/src/runtime/netpoll.go:164 +0x59
net.(*pollDesc).wait(0xc427d25098, 0x72, 0x0, 0xc42acfd980)
	/usr/local/go/src/net/fd_poll_runtime.go:75 +0x38
net.(*pollDesc).waitRead(0xc427d25098, 0xffffffffffffffff, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:80 +0x34
net.(*netFD).accept(0xc427d25030, 0x0, 0x27b8960, 0xc42acfd980)
	/usr/local/go/src/net/fd_unix.go:430 +0x1e5
net.(*TCPListener).accept(0xc420d03d90, 0xc42b960df8, 0xb28d87, 0x6b8f70)
	/usr/local/go/src/net/tcpsock_posix.go:136 +0x2e
net.(*TCPListener).Accept(0xc420d03d90, 0x1bf8ab0, 0xc428ba1200, 0x27d47c0, 0xc420d03da0)
	/usr/local/go/src/net/tcpsock.go:228 +0x49
github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc.(*Server).Serve(0xc428ba1200, 0x27c97e0, 0xc420d03d90, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/server.go:432 +0x189
github.com/cockroachdb/cockroach/pkg/util/netutil.ListenAndServeGRPC.func2(0x7f4acf758128, 0xc4296e0cc0)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/netutil/net.go:58 +0x3c
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc42d7e04e0, 0xc43126fb00, 0xc42acfd7c0)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:215 +0xf7
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:216 +0xad

goroutine 1264863 [select]:
github.com/cockroachdb/cockroach/pkg/rpc.(*Context).runHeartbeat(0xc4315a5b00, 0xc42e3ef480, 0xc42d7243a0, 0xf, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/pkg/rpc/context.go:371 +0x801
github.com/cockroachdb/cockroach/pkg/rpc.(*Context).GRPCDial.func1.2.1(0x7f4acf758128, 0xc42cecd170)
	/go/src/github.com/cockroachdb/cockroach/pkg/rpc/context.go:307 +0x6b
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc42d7244a0, 0xc43126fb00, 0xc42a672000)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:215 +0xf7
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:216 +0xad

goroutine 1265913 [select]:
github.com/cockroachdb/cockroach/pkg/storage.(*baseQueue).processLoop.func1(0x7f4acf758128, 0xc427ec5620)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/queue.go:490 +0x364
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc42d621210, 0xc434c487e0, 0xc42a9379c0)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:215 +0xf7
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:216 +0xad

goroutine 1263993 [select]:
github.com/cockroachdb/cockroach/pkg/gossip.(*Gossip).manage.func1(0x7f4acf758128, 0xc428fefaa0)
	/go/src/github.com/cockroachdb/cockroach/pkg/gossip/gossip.go:1093 +0x325
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc42d5275c0, 0xc43126fb00, 0xc42d5275b0)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:215 +0xf7
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:216 +0xad

goroutine 1264849 [chan receive]:
github.com/cockroachdb/cockroach/pkg/util/netutil.ListenAndServeGRPC.func1(0x7f4acf758128, 0xc42cecce10)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/netutil/net.go:51 +0x6f
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc42d7242e0, 0xc43126fb00, 0xc424ae9590)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:215 +0xf7
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:216 +0xad

goroutine 1263454 [select]:
github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/transport.(*http2Server).controller(0xc42d3dbce0)
	/go/src/github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/transport/http2_server.go:956 +0x78d
created by github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/transport.newHTTP2Server
	/go/src/github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/transport/http2_server.go:225 +0x96d

goroutine 1264095 [select]:
github.com/cockroachdb/cockroach/pkg/storage.(*Store).startGossip.func4(0x7f4acf758128, 0xc42cbf2c00)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/store.go:1355 +0x4ee
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc42d5c2090, 0xc43126fc20, 0xc433a88d70)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:215 +0xf7
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:216 +0xad

goroutine 1265690 [chan receive]:
github.com/cockroachdb/cockroach/pkg/gossip.(*server).start.func3(0x7f4acf758128, 0xc4296e10e0)
	/go/src/github.com/cockroachdb/cockroach/pkg/gossip/server.go:386 +0x66
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc42d80e130, 0xc43126fb00, 0xc42aa45520)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:215 +0xf7
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:216 +0xad

goroutine 1264009 [semacquire]:
sync.runtime_notifyListWait(0xc42720dfd0, 0xc400000603)
	/usr/local/go/src/runtime/sema.go:298 +0x10b
sync.(*Cond).Wait(0xc42720dfc0)
	/usr/local/go/src/sync/cond.go:57 +0x89
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).worker(0xc4315a5c80, 0xc43126fc20)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:199 +0xac
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).Start.func2(0x7f4acf758128, 0xc42c5bc9f0)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:168 +0x33
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc42d527b70, 0xc43126fc20, 0xc42b947fe0)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:215 +0xf7
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:216 +0xad

goroutine 1263781 [select]:
github.com/cockroachdb/cockroach/pkg/kv.(*TxnCoordSender).printStatsLoop(0xc42afa3380, 0x7f4acf758128, 0xc428e90e10)
	/go/src/github.com/cockroachdb/cockroach/pkg/kv/txn_coord_sender.go:255 +0xb47
github.com/cockroachdb/cockroach/pkg/kv.NewTxnCoordSender.func1(0x7f4acf758128, 0xc428e90e10)
	/go/src/github.com/cockroachdb/cockroach/pkg/kv/txn_coord_sender.go:239 +0x3e
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc42d4c9450, 0xc43126fc20, 0xc42d4c9440)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:215 +0xf7
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:216 +0xad

goroutine 1265915 [select]:
github.com/cockroachdb/cockroach/pkg/storage.(*baseQueue).processLoop.func1(0x7f4acf758128, 0xc42bac4720)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/queue.go:490 +0x364
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc42d621230, 0xc434c487e0, 0xc42a937a00)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:215 +0xf7
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:216 +0xad

goroutine 1264074 [semacquire]:
sync.runtime_notifyListWait(0xc42720dfd0, 0xc4000005fc)
	/usr/local/go/src/runtime/sema.go:298 +0x10b
sync.(*Cond).Wait(0xc42720dfc0)
	/usr/local/go/src/sync/cond.go:57 +0x89
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).worker(0xc4315a5c80, 0xc43126fc20)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:199 +0xac
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).Start.func2(0x7f4acf758128, 0xc42cbf2c60)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:168 +0x33
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc42d527eb0, 0xc43126fc20, 0xc42b97a700)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:215 +0xf7
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:216 +0xad

goroutine 1267014 [select]:
github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/transport.(*recvBufferReader).Read(0xc434278e80, 0xc42ae99d70, 0x5, 0x5, 0x0, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/transport/transport.go:145 +0x556
github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/transport.(*Stream).Read(0xc42fbcdc00, 0xc42ae99d70, 0x5, 0x5, 0xc430d1a190, 0x27a2eb0, 0x68f5c4)
	/go/src/github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/transport/transport.go:328 +0x59
io.ReadAtLeast(0x27b7ae0, 0xc42fbcdc00, 0xc42ae99d70, 0x5, 0x5, 0x5, 0x4, 0xc42c2d4230, 0x0)
	/usr/local/go/src/io/io.go:307 +0xa9
io.ReadFull(0x27b7ae0, 0xc42fbcdc00, 0xc42ae99d70, 0x5, 0x5, 0xc42e3eeec0, 0x1, 0xc435647cc8)
	/usr/local/go/src/io/io.go:325 +0x58
github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc.(*parser).recvMsg(0xc42ae99d60, 0x7fffffff, 0xc430d1a218, 0x20, 0x20, 0xc435647d98, 0xa, 0x6)
	/go/src/github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/rpc_util.go:255 +0x69
github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc.recv(0xc42ae99d60, 0x27ca8a0, 0x2c94a58, 0xc42fbcdc00, 0x27bf5e0, 0x2c94a58, 0x1a4f920, 0xc43260cbc0, 0x7fffffff, 0x0, ...)
	/go/src/github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/rpc_util.go:351 +0x4d
github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc.(*serverStream).RecvMsg(0xc425c62f00, 0x1a4f920, 0xc43260cbc0, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/stream.go:623 +0x11a
github.com/cockroachdb/cockroach/pkg/storage.(*multiRaftRaftMessageBatchServer).Recv(0xc42d8b9310, 0x7f4acf758128, 0xc428f71110, 0xc42f423800)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/raft.pb.go:397 +0x62
github.com/cockroachdb/cockroach/pkg/storage.(*RaftTransport).RaftMessageBatch.func1.1.1(0x27d44c0, 0xc42d8b9310, 0xc4243b92d0, 0x7f4acf758128, 0xc428f71110, 0x18, 0xd2cc14)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/raft_transport.go:300 +0x3f
github.com/cockroachdb/cockroach/pkg/storage.(*RaftTransport).RaftMessageBatch.func1.1(0x7f4acf758128, 0xc428f71110)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/raft_transport.go:323 +0x5d
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc42d8b9370, 0xc43126fb00, 0xc428f710e0)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:215 +0xf7
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:216 +0xad

goroutine 1264019 [semacquire]:
sync.runtime_notifyListWait(0xc42720dfd0, 0xc4000005cb)
	/usr/local/go/src/runtime/sema.go:298 +0x10b
sync.(*Cond).Wait(0xc42720dfc0)
	/usr/local/go/src/sync/cond.go:57 +0x89
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).worker(0xc4315a5c80, 0xc43126fc20)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:199 +0xac
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).Start.func2(0x7f4acf758128, 0xc42c5bd6e0)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:168 +0x33
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc42d527c20, 0xc43126fc20, 0xc42b97a200)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:215 +0xf7
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:216 +0xad

goroutine 1264083 [semacquire]:
sync.runtime_notifyListWait(0xc42720dfd0, 0xc4000005fe)
	/usr/local/go/src/runtime/sema.go:298 +0x10b
sync.(*Cond).Wait(0xc42720dfc0)
	/usr/local/go/src/sync/cond.go:57 +0x89
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).worker(0xc4315a5c80, 0xc43126fc20)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:199 +0xac
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).Start.func2(0x7f4acf758128, 0xc42cbf2150)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:168 +0x33
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc42d527f40, 0xc43126fc20, 0xc42b97a980)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:215 +0xf7
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:216 +0xad

goroutine 1265718 [semacquire]:
sync.runtime_notifyListWait(0xc4356f1250, 0xc40000036e)
	/usr/local/go/src/runtime/sema.go:298 +0x10b
sync.(*Cond).Wait(0xc4356f1240)
	/usr/local/go/src/sync/cond.go:57 +0x89
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).worker(0xc424620a00, 0xc434c487e0)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:199 +0xac
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).Start.func2(0x7f4acf758128, 0xc427ec4e40)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:168 +0x33
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc42d80e460, 0xc434c487e0, 0xc42aa458e0)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:215 +0xf7
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:216 +0xad

goroutine 1265164 [select]:
github.com/cockroachdb/cockroach/pkg/storage.(*baseQueue).processLoop.func1(0x7f4acf758128, 0xc424bc1170)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/queue.go:490 +0x364
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc42d620ef0, 0xc42fa002d0, 0xc42a937540)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:215 +0xf7
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:216 +0xad

goroutine 1264080 [semacquire]:
sync.runtime_notifyListWait(0xc42720dfd0, 0xc4000005e3)
	/usr/local/go/src/runtime/sema.go:298 +0x10b
sync.(*Cond).Wait(0xc42720dfc0)
	/usr/local/go/src/sync/cond.go:57 +0x89
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).worker(0xc4315a5c80, 0xc43126fc20)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:199 +0xac
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).Start.func2(0x7f4acf758128, 0xc42cbf20c0)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:168 +0x33
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc42d527f10, 0xc43126fc20, 0xc42b97a7c0)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:215 +0xf7
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:216 +0xad

goroutine 1265710 [semacquire]:
sync.runtime_notifyListWait(0xc4356f1250, 0xc40000037d)
	/usr/local/go/src/runtime/sema.go:298 +0x10b
sync.(*Cond).Wait(0xc4356f1240)
	/usr/local/go/src/sync/cond.go:57 +0x89
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).worker(0xc424620a00, 0xc434c487e0)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:199 +0xac
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).Start.func2(0x7f4acf758128, 0xc427ec4f30)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:168 +0x33
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc42d80e360, 0xc434c487e0, 0xc42aa457e0)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:215 +0xf7
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:216 +0xad

goroutine 1264015 [semacquire]:
sync.runtime_notifyListWait(0xc42720dfd0, 0xc400000608)
	/usr/local/go/src/runtime/sema.go:298 +0x10b
sync.(*Cond).Wait(0xc42720dfc0)
	/usr/local/go/src/sync/cond.go:57 +0x89
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).worker(0xc4315a5c80, 0xc43126fc20)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:199 +0xac
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).Start.func2(0x7f4acf758128, 0xc42c5bd0e0)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:168 +0x33
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc42d527be0, 0xc43126fc20, 0xc42b97a180)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:215 +0xf7
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:216 +0xad

goroutine 1268104 [select]:
github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/transport.(*recvBufferReader).Read(0xc43432ca80, 0xc42acc3eb0, 0x5, 0x5, 0x0, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/transport/transport.go:145 +0x556
github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/transport.(*Stream).Read(0xc42ae5be00, 0xc42acc3eb0, 0x5, 0x5, 0xc4268493f0, 0x6b23bb, 0xc4268495f8)
	/go/src/github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/transport/transport.go:328 +0x59
io.ReadAtLeast(0x27b7ae0, 0xc42ae5be00, 0xc42acc3eb0, 0x5, 0x5, 0x5, 0x5, 0xc426849438, 0x6a001a)
	/usr/local/go/src/io/io.go:307 +0xa9
io.ReadFull(0x27b7ae0, 0xc42ae5be00, 0xc42acc3eb0, 0x5, 0x5, 0xc426849450, 0x69f8fb, 0x40)
	/usr/local/go/src/io/io.go:325 +0x58
github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc.(*parser).recvMsg(0xc42acc3ea0, 0x7fffffff, 0x2, 0x2, 0x2, 0x0, 0x2, 0x1)
	/go/src/github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/rpc_util.go:255 +0x69
github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc.recv(0xc42acc3ea0, 0x27ca8a0, 0x2c94a58, 0xc42ae5be00, 0x27bf5e0, 0x2c94a58, 0x1a4fa00, 0xc427ec5aa0, 0x7fffffff, 0x0, ...)
	/go/src/github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/rpc_util.go:351 +0x4d
github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc.(*clientStream).RecvMsg(0xc42bb0da20, 0x1a4fa00, 0xc427ec5aa0, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/stream.go:379 +0xe9
github.com/cockroachdb/cockroach/pkg/storage.(*multiRaftRaftMessageBatchClient).Recv(0xc42d96cf10, 0xc427ec5a10, 0xc4268496d0, 0x66ffe8)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/raft.pb.go:329 +0x62
github.com/cockroachdb/cockroach/pkg/storage.(*RaftTransport).processQueue.func1.1.1(0x27d4460, 0xc42d96cf10, 0xc4300f2d40, 0xc4243b92d0, 0x7f4acf758128, 0xc427ec5a10, 0x18, 0xd2cc14)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/raft_transport.go:466 +0x49
github.com/cockroachdb/cockroach/pkg/storage.(*RaftTransport).processQueue.func1.1(0x7f4acf758128, 0xc427ec5a10)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/raft_transport.go:483 +0x66
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc42d96cf50, 0xc43126fb00, 0xc427ec59e0)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:215 +0xf7
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:216 +0xad

goroutine 1265750 [semacquire]:
sync.runtime_notifyListWait(0xc4356f1250, 0xc40000036a)
	/usr/local/go/src/runtime/sema.go:298 +0x10b
sync.(*Cond).Wait(0xc4356f1240)
	/usr/local/go/src/sync/cond.go:57 +0x89
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).worker(0xc424620a00, 0xc434c487e0)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:199 +0xac
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).Start.func2(0x7f4acf758128, 0xc42437bb90)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:168 +0x33
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc42d80e670, 0xc434c487e0, 0xc42aa45ce0)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:215 +0xf7
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:216 +0xad

goroutine 1264895 [semacquire]:
sync.runtime_notifyListWait(0xc42e3eeed0, 0xc400000148)
	/usr/local/go/src/runtime/sema.go:298 +0x10b
sync.(*Cond).Wait(0xc42e3eeec0)
	/usr/local/go/src/sync/cond.go:57 +0x89
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).worker(0xc423d7f500, 0xc42fa002d0)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:199 +0xac
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).Start.func2(0x7f4acf758128, 0xc42a5999b0)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:168 +0x33
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc42d7247f0, 0xc42fa002d0, 0xc42a97b880)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:215 +0xf7
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:216 +0xad

goroutine 1264235 [select]:
github.com/cockroachdb/cockroach/pkg/storage.(*baseQueue).processLoop.func1(0x7f4acf758128, 0xc42c5d0e70)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/queue.go:490 +0x364
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc42afebec0, 0xc43126fc20, 0xc425bf7aa0)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:215 +0xf7
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:216 +0xad

goroutine 1265464 [IO wait]:
net.runtime_pollWait(0x7f4ac8f59fa8, 0x72, 0xd)
	/usr/local/go/src/runtime/netpoll.go:164 +0x59
net.(*pollDesc).wait(0xc427d25338, 0x72, 0x27bb620, 0x27b0f78)
	/usr/local/go/src/net/fd_poll_runtime.go:75 +0x38
net.(*pollDesc).waitRead(0xc427d25338, 0xc432d6a000, 0x8000)
	/usr/local/go/src/net/fd_poll_runtime.go:80 +0x34
net.(*netFD).Read(0xc427d252d0, 0xc432d6a000, 0x8000, 0x8000, 0x0, 0x27bb620, 0x27b0f78)
	/usr/local/go/src/net/fd_unix.go:250 +0x1b7
net.(*conn).Read(0xc420491540, 0xc432d6a000, 0x8000, 0x8000, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/net.go:181 +0x70
bufio.(*Reader).Read(0xc430cc9920, 0xc429563538, 0x9, 0x9, 0x0, 0x0, 0x0)
	/usr/local/go/src/bufio/bufio.go:213 +0x312
io.ReadAtLeast(0x27b2c60, 0xc430cc9920, 0xc429563538, 0x9, 0x9, 0x9, 0x6, 0xc42001e068, 0xc42001e000)
	/usr/local/go/src/io/io.go:307 +0xa9
io.ReadFull(0x27b2c60, 0xc430cc9920, 0xc429563538, 0x9, 0x9, 0x0, 0x0, 0xc428c2ce30)
	/usr/local/go/src/io/io.go:325 +0x58
github.com/cockroachdb/cockroach/vendor/golang.org/x/net/http2.readFrameHeader(0xc429563538, 0x9, 0x9, 0x27b2c60, 0xc430cc9920, 0x0, 0xc400000000, 0xc428c2ce75, 0xc43293a3c0)
	/go/src/github.com/cockroachdb/cockroach/vendor/golang.org/x/net/http2/frame.go:237 +0x7b
github.com/cockroachdb/cockroach/vendor/golang.org/x/net/http2.(*Framer).ReadFrame(0xc429563500, 0x27bdba0, 0xc43293a3c0, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/vendor/golang.org/x/net/http2/frame.go:492 +0xa4
github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/transport.(*framer).readFrame(0xc429667620, 0xc43293a3c0, 0xc43293a3c0, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/transport/http_util.go:608 +0x2f
github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/transport.(*http2Client).reader(0xc431058480)
	/go/src/github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/transport/http2_client.go:1095 +0xcd
created by github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/transport.newHTTP2Client
	/go/src/github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/transport/http2_client.go:267 +0xce8

goroutine 1265678 [select]:
github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/transport.(*http2Server).controller(0xc427634840)
	/go/src/github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/transport/http2_server.go:956 +0x78d
created by github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/transport.newHTTP2Server
	/go/src/github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/transport/http2_server.go:225 +0x96d

goroutine 1264087 [semacquire]:
sync.runtime_notifyListWait(0xc42720dfd0, 0xc4000005eb)
	/usr/local/go/src/runtime/sema.go:298 +0x10b
sync.(*Cond).Wait(0xc42720dfc0)
	/usr/local/go/src/sync/cond.go:57 +0x89
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).worker(0xc4315a5c80, 0xc43126fc20)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:199 +0xac
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).Start.func2(0x7f4acf758128, 0xc42cbf2930)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:168 +0x33
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc42d527f90, 0xc43126fc20, 0xc42b97aa00)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:215 +0xf7
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:216 +0xad

goroutine 1265919 [select]:
github.com/cockroachdb/cockroach/pkg/storage.(*baseQueue).processLoop.func1(0x7f4acf758128, 0xc427ec56e0)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/queue.go:490 +0x364
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc42d621270, 0xc434c487e0, 0xc42a937a80)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:215 +0xf7
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:216 +0xad

goroutine 1265163 [select]:
github.com/cockroachdb/cockroach/pkg/storage.(*baseQueue).processLoop.func1(0x7f4acf758128, 0xc424bc1110)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/queue.go:490 +0x364
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc42d620ee0, 0xc42fa002d0, 0xc42a937520)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:215 +0xf7
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:216 +0xad

goroutine 1264010 [semacquire]:
sync.runtime_notifyListWait(0xc42720dfd0, 0xc400000600)
	/usr/local/go/src/runtime/sema.go:298 +0x10b
sync.(*Cond).Wait(0xc42720dfc0)
	/usr/local/go/src/sync/cond.go:57 +0x89
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).worker(0xc4315a5c80, 0xc43126fc20)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:199 +0xac
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).Start.func2(0x7f4acf758128, 0xc42c5bca80)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:168 +0x33
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc42d527b90, 0xc43126fc20, 0xc42b97a080)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:215 +0xf7
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:216 +0xad

goroutine 1264093 [select]:
github.com/cockroachdb/cockroach/pkg/storage.(*Store).startGossip.func4(0x7f4acf758128, 0xc42cbf2b40)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/store.go:1355 +0x4ee
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc42d5c2070, 0xc43126fc20, 0xc433a88cd0)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:215 +0xf7
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:216 +0xad

goroutine 1265766 [select]:
github.com/cockroachdb/cockroach/pkg/storage.(*Store).startGossip.func4(0x7f4acf758128, 0xc42bac43f0)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/store.go:1355 +0x4ee
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc42d80e7c0, 0xc434c487e0, 0xc433ad2f50)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:215 +0xf7
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:216 +0xad

goroutine 1264065 [semacquire]:
sync.runtime_notifyListWait(0xc42720dfd0, 0xc4000005f2)
	/usr/local/go/src/runtime/sema.go:298 +0x10b
sync.(*Cond).Wait(0xc42720dfc0)
	/usr/local/go/src/sync/cond.go:57 +0x89
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).worker(0xc4315a5c80, 0xc43126fc20)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:199 +0xac
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).Start.func2(0x7f4acf758128, 0xc42c5d0c30)
```

### PR DESCRIPTION
**Pull request by irfansharif**
Fixes #16227.

Account for replicas that have been created from preemptive snapshots
but have not been added to their corresponding Raft groups.

cc @tschottdorf.

### CODE REVIEW

**Comment by tschottdorf** [comment]
LGTM

File: pkg/storage/replica.go [hunk 1]
```diff
@@ -860,6 +860,12 @@ func (r *Replica) updateProposalQuotaRaftMuLocked(
 	r.mu.Lock()
 	defer r.mu.Unlock()
 
+	if r.mu.replicaID == 0 {
+		// The replica's was created from preemptive snapshot and has not been
```
Comment (tschottdorf) [inline pkg/storage/replica.go]: typo
