### PR TITLE
kv: wait for pending results before returning AmbiguousCommitError

### LINKED ISSUE #10194: : TestParallelCreateTables failed under stress
SHA: https://github.com/cockroachdb/cockroach/commits/ca89f456766a8f0381815e58aa7abfe5d3ece741

Stress build found a failed test:

```
I161025 06:57:59.264925 9214 gossip/gossip.go:237  [n?] initial resolvers: []
W161025 06:57:59.265414 9214 gossip/gossip.go:1055  [n?] no resolvers found; use --join to specify a connected node
W161025 06:57:59.268611 9214 server/status/runtime.go:116  Could not parse build timestamp: parsing time "" as "2006/01/02 15:04:05": cannot parse "" as "2006"
I161025 06:57:59.270534 9214 storage/engine/rocksdb.go:340  opening in memory rocksdb instance
I161025 06:57:59.271916 9214 server/config.go:432  1 storage engine initialized
I161025 06:57:59.291024 9214 server/node.go:422  [n?] store [n0,s0] not bootstrapped
I161025 06:57:59.348392 9391 storage/replica_proposal.go:292  [s1,r1/1:/M{in-ax}] new range lease replica {1 1 1} 1970-01-01 00:00:00 +0000 UTC 410382h58m8.328611485s following replica {0 0 0} 1970-01-01 00:00:00 +0000 UTC 0s [physicalTime=2016-10-25 06:57:59.34821409 +0000 UTC]
I161025 06:57:59.365758 9214 util/stop/stopper.go:353  stop has been called, stopping or quiescing all running tasks
I161025 06:57:59.367700 9214 server/node.go:351  [n?] **** cluster {c63f1cf4-a896-4160-8853-d44eb0bf87eb} has been created
I161025 06:57:59.368001 9214 server/node.go:352  [n?] **** add additional nodes by specifying --join=127.0.0.1:48512
I161025 06:57:59.380917 9214 base/node_id.go:62  [n1] NodeID set to 1
I161025 06:57:59.396199 9365 storage/split_queue.go:103  [n1,split,s1,r1/1:/M{in-ax}] splitting at keys [/Table/11/0 /Table/12/0 /Table/13/0 /Table/14/0]
I161025 06:57:59.397556 9214 server/node.go:435  [n1] initialized store [n1,s1]: {Capacity:536870912 Available:536870912 RangeCount:0}
I161025 06:57:59.398191 9214 server/node.go:320  [n1] node ID 1 initialized
I161025 06:57:59.398670 9214 gossip/gossip.go:280  [n1] NodeDescriptor set to node_id:1 address:<network_field:"tcp" address_field:"127.0.0.1:48512" > attrs:<> locality:<> 
I161025 06:57:59.399707 9214 storage/stores.go:296  [n1] read 0 node addresses from persistent storage
I161025 06:57:59.400356 9214 server/node.go:565  [n1] connecting to gossip network to verify cluster ID...
I161025 06:57:59.400763 9214 server/node.go:586  [n1] node connected via gossip and verified as part of cluster {"c63f1cf4-a896-4160-8853-d44eb0bf87eb"}
I161025 06:57:59.401314 9214 server/node.go:370  [n1] node=1: started with [[]=] engine(s) and attributes []
I161025 06:57:59.401671 9214 server/server.go:594  [n1] starting https server at 127.0.0.1:56573
I161025 06:57:59.401943 9214 server/server.go:595  [n1] starting grpc/postgres server at 127.0.0.1:48512
I161025 06:57:59.402217 9214 server/server.go:596  [n1] advertising CockroachDB node at 127.0.0.1:48512
I161025 06:57:59.461048 9441 sql/event_log.go:94  [n1] Event: "node_join", target: 1, info: {Descriptor:{NodeID:1 Address:{NetworkField:tcp AddressField:127.0.0.1:48512} Attrs: Locality:} ClusterID:{UUID:c63f1cf4-a896-4160-8853-d44eb0bf87eb} StartedAt:1477378679400984303}
I161025 06:57:59.517687 9365 storage/replica_command.go:2354  [n1,split,s1,r1/1:/M{in-ax}] initiating a split of this range at key /Table/11 [r2]
E161025 06:57:59.997916 9366 storage/queue.go:569  [n1,replicate] (purgatory) on [n1,s1,r1/1:/{Min-Table/11}]: 0 of 1 store with an attribute matching []; likely not enough nodes in cluster
E161025 06:57:59.999261 9351 storage/queue.go:569  [n1,replicate] (purgatory) on [n1,s1,r1/1:/{Min-Table/11}]: 0 of 1 store with an attribute matching []; likely not enough nodes in cluster
I161025 06:58:00.048556 9365 storage/replica_command.go:2354  [n1,split,s1,r1/1:/{Min-Table/11}] initiating a split of this range at key /Table/12 [r3]
E161025 06:58:00.557026 9366 storage/queue.go:569  [n1,replicate] (purgatory) on [n1,s1,r2/1:/Table/1{1-2}]: 0 of 1 store with an attribute matching []; likely not enough nodes in cluster
I161025 06:58:00.597526 9365 storage/replica_command.go:2354  [n1,split,s1,r1/1:/{Min-Table/11}] initiating a split of this range at key /Table/13 [r4]
I161025 06:58:00.811955 9365 storage/replica_command.go:2354  [n1,split,s1,r1/1:/{Min-Table/11}] initiating a split of this range at key /Table/14 [r5]
E161025 06:58:00.829660 9366 storage/queue.go:569  [n1,replicate] (purgatory) on [n1,s1,r3/1:/Table/1{2-3}]: 0 of 1 store with an attribute matching []; likely not enough nodes in cluster
E161025 06:58:01.323569 9366 storage/queue.go:569  [n1,replicate] (purgatory) on [n1,s1,r4/1:/Table/1{3-4}]: 0 of 1 store with an attribute matching []; likely not enough nodes in cluster
E161025 06:58:01.407210 9366 storage/queue.go:569  [n1,replicate] (purgatory) on [n1,s1,r5/1:/{Table/14-Max}]: 0 of 1 store with an attribute matching []; likely not enough nodes in cluster
I161025 06:58:01.420126 9214 gossip/gossip.go:237  [n?] initial resolvers: [127.0.0.1:48512]
W161025 06:58:01.420749 9214 gossip/gossip.go:1057  [n?] no incoming or outgoing connections
W161025 06:58:01.440616 9214 server/status/runtime.go:116  Could not parse build timestamp: parsing time "" as "2006/01/02 15:04:05": cannot parse "" as "2006"
I161025 06:58:01.445700 9214 storage/engine/rocksdb.go:340  opening in memory rocksdb instance
I161025 06:58:01.446787 9214 server/config.go:432  1 storage engine initialized
I161025 06:58:01.464145 9353 gossip/client.go:126  [n?] node 0: started gossip client to 127.0.0.1:48512
I161025 06:58:01.465416 9214 server/node.go:422  [n?] store [n0,s0] not bootstrapped
I161025 06:58:01.465992 9214 storage/stores.go:296  [n?] read 0 node addresses from persistent storage
I161025 06:58:01.466480 9214 server/node.go:565  [n?] connecting to gossip network to verify cluster ID...
I161025 06:58:01.475030 9455 gossip/server.go:285  [n1] received gossip from unknown node
I161025 06:58:01.484576 9214 server/node.go:586  [n?] node connected via gossip and verified as part of cluster {"c63f1cf4-a896-4160-8853-d44eb0bf87eb"}
I161025 06:58:01.489861 9523 storage/stores.go:312  [n?] wrote 1 node addresses to persistent storage
I161025 06:58:01.494395 9214 kv/dist_sender.go:330  [n?] unable to determine this node's attributes for replica selection; node is most likely bootstrapping
I161025 06:58:01.500131 9214 server/node.go:313  [n?] new node allocated ID 2
I161025 06:58:01.500476 9214 base/node_id.go:62  [n2] NodeID set to 2
I161025 06:58:01.500901 9214 gossip/gossip.go:280  [n2] NodeDescriptor set to node_id:2 address:<network_field:"tcp" address_field:"127.0.0.1:49456" > attrs:<> locality:<> 
I161025 06:58:01.501861 9214 server/node.go:370  [n2] node=2: started with [[]=] engine(s) and attributes []
I161025 06:58:01.502200 9214 server/server.go:594  [n2] starting https server at 127.0.0.1:41119
I161025 06:58:01.502469 9214 server/server.go:595  [n2] starting grpc/postgres server at 127.0.0.1:49456
I161025 06:58:01.502735 9214 server/server.go:596  [n2] advertising CockroachDB node at 127.0.0.1:49456
I161025 06:58:01.505521 9543 sql/event_log.go:94  [n2] Event: "node_join", target: 2, info: {Descriptor:{NodeID:2 Address:{NetworkField:tcp AddressField:127.0.0.1:49456} Attrs: Locality:} ClusterID:{UUID:c63f1cf4-a896-4160-8853-d44eb0bf87eb} StartedAt:1477378681501726238}
I161025 06:58:01.518333 9527 storage/stores.go:312  [n1] wrote 1 node addresses to persistent storage
I161025 06:58:01.520646 9540 server/node.go:546  [n2] bootstrapped store [n2,s2]
I161025 06:58:01.544176 9351 storage/replica_raftstorage.go:446  [n1,replicate,s1,r1/1:/{Min-Table/11}] generated snapshot 2a602de2 for range 1 at index 47 in 135.4µs.
I161025 06:58:01.551575 9214 gossip/gossip.go:237  [n?] initial resolvers: [127.0.0.1:48512]
W161025 06:58:01.552060 9214 gossip/gossip.go:1057  [n?] no incoming or outgoing connections
W161025 06:58:01.559809 9214 server/status/runtime.go:116  Could not parse build timestamp: parsing time "" as "2006/01/02 15:04:05": cannot parse "" as "2006"
I161025 06:58:01.561578 9214 storage/engine/rocksdb.go:340  opening in memory rocksdb instance
I161025 06:58:01.565700 9214 server/config.go:432  1 storage engine initialized
I161025 06:58:01.578602 9214 server/node.go:422  [n?] store [n0,s0] not bootstrapped
I161025 06:58:01.579157 9214 storage/stores.go:296  [n?] read 0 node addresses from persistent storage
I161025 06:58:01.579619 9214 server/node.go:565  [n?] connecting to gossip network to verify cluster ID...
I161025 06:58:01.607106 9351 storage/store.go:3032  [n1,replicate,s1,r1/1:/{Min-Table/11}] streamed snapshot: kv pairs: 368, log entries: 37
I161025 06:58:01.613626 9634 storage/replica_raftstorage.go:577  [n2,s2] [n2,s2,r1/?:{-}]: with replicaID [?], applying preemptive snapshot at index 47 (id=2a602de2, encoded size=16, 1 rocksdb batches, 37 log entries)
I161025 06:58:01.615435 9634 storage/replica_raftstorage.go:580  [n2,s2] [n2,s2,r1/?:/{Min-Table/11}]: with replicaID [?], applied preemptive snapshot in 0.002s
I161025 06:58:01.621991 9635 gossip/client.go:126  [n?] node 0: started gossip client to 127.0.0.1:48512
I161025 06:58:01.627670 9642 gossip/server.go:285  [n1] received gossip from unknown node
I161025 06:58:01.631401 9351 storage/replica_command.go:3232  [n1,replicate,s1,r1/1:/{Min-Table/11}] change replicas: read existing descriptor range_id:1 start_key:"" end_key:"\223" replicas:<node_id:1 store_id:1 replica_id:1 > next_replica_id:2 
I161025 06:58:01.681938 9214 server/node.go:586  [n?] node connected via gossip and verified as part of cluster {"c63f1cf4-a896-4160-8853-d44eb0bf87eb"}
I161025 06:58:01.684931 9671 storage/stores.go:312  [n?] wrote 1 node addresses to persistent storage
I161025 06:58:01.685642 9671 storage/stores.go:312  [n?] wrote 2 node addresses to persistent storage
I161025 06:58:01.712312 9351 storage/replica.go:1793  [n1,s1,r1/1:/{Min-Table/11}] proposing ADD_REPLICA {NodeID:2 StoreID:2 ReplicaID:2} for range 1: [{NodeID:1 StoreID:1 ReplicaID:1} {NodeID:2 StoreID:2 ReplicaID:2}]
I161025 06:58:01.725585 9351 storage/replica_raftstorage.go:446  [n1,replicate,s1,r2/1:/Table/1{1-2}] generated snapshot 349ed9af for range 2 at index 29 in 115.9µs.
I161025 06:58:01.734127 9214 kv/dist_sender.go:330  [n?] unable to determine this node's attributes for replica selection; node is most likely bootstrapping
I161025 06:58:01.749564 9351 storage/store.go:3032  [n1,replicate,s1,r2/1:/Table/1{1-2}] streamed snapshot: kv pairs: 11, log entries: 19
I161025 06:58:01.765058 9659 storage/replica_raftstorage.go:577  [n2,s2] [n2,s2,r2/?:{-}]: with replicaID [?], applying preemptive snapshot at index 29 (id=349ed9af, encoded size=16, 1 rocksdb batches, 19 log entries)
I161025 06:58:01.767715 9659 storage/replica_raftstorage.go:580  [n2,s2] [n2,s2,r2/?:/Table/1{1-2}]: with replicaID [?], applied preemptive snapshot in 0.002s
I161025 06:58:01.771079 9686 storage/raft_transport.go:423  [n2] raft transport stream to node 1 established
I161025 06:58:01.804600 9351 storage/replica_command.go:3232  [n1,replicate,s1,r2/1:/Table/1{1-2}] change replicas: read existing descriptor range_id:2 start_key:"\223" end_key:"\224" replicas:<node_id:1 store_id:1 replica_id:1 > next_replica_id:2 
I161025 06:58:01.844430 9214 server/node.go:313  [n?] new node allocated ID 3
I161025 06:58:01.844768 9214 base/node_id.go:62  [n3] NodeID set to 3
I161025 06:58:01.845225 9214 gossip/gossip.go:280  [n3] NodeDescriptor set to node_id:3 address:<network_field:"tcp" address_field:"127.0.0.1:36790" > attrs:<> locality:<> 
I161025 06:58:01.852779 9214 server/node.go:370  [n3] node=3: started with [[]=] engine(s) and attributes []
I161025 06:58:01.853113 9214 server/server.go:594  [n3] starting https server at 127.0.0.1:49193
I161025 06:58:01.853382 9214 server/server.go:595  [n3] starting grpc/postgres server at 127.0.0.1:36790
I161025 06:58:01.853643 9214 server/server.go:596  [n3] advertising CockroachDB node at 127.0.0.1:36790
I161025 06:58:01.864225 9616 sql/event_log.go:94  [n3] Event: "node_join", target: 3, info: {Descriptor:{NodeID:3 Address:{NetworkField:tcp AddressField:127.0.0.1:36790} Attrs: Locality:} ClusterID:{UUID:c63f1cf4-a896-4160-8853-d44eb0bf87eb} StartedAt:1477378681852640229}
I161025 06:58:01.924264 9778 storage/stores.go:312  [n1] wrote 2 node addresses to persistent storage
I161025 06:58:01.931503 9749 storage/stores.go:312  [n2] wrote 2 node addresses to persistent storage
I161025 06:58:02.008845 9613 server/node.go:546  [n3] bootstrapped store [n3,s3]
I161025 06:58:02.082714 9351 storage/replica.go:1793  [n1,s1,r2/1:/Table/1{1-2}] proposing ADD_REPLICA {NodeID:2 StoreID:2 ReplicaID:2} for range 2: [{NodeID:1 StoreID:1 ReplicaID:1} {NodeID:2 StoreID:2 ReplicaID:2}]
I161025 06:58:02.115320 9351 storage/replica_command.go:3232  [n1,replicate,s1,r2/1:/Table/1{1-2}] change replicas: read existing descriptor range_id:2 start_key:"\223" end_key:"\224" replicas:<node_id:1 store_id:1 replica_id:1 > next_replica_id:2 
I161025 06:58:02.276688 9351 storage/replica.go:1793  [n1,s1,r2/1:/Table/1{1-2}] proposing ADD_REPLICA {NodeID:2 StoreID:2 ReplicaID:2} for range 2: [{NodeID:1 StoreID:1 ReplicaID:1} {NodeID:2 StoreID:2 ReplicaID:2}]
I161025 06:58:02.301296 9351 storage/replica_raftstorage.go:446  [n1,replicate,s1,r3/1:/Table/1{2-3}] generated snapshot d584cb28 for range 3 at index 20 in 117.3µs.
I161025 06:58:02.331851 9351 storage/store.go:3032  [n1,replicate,s1,r3/1:/Table/1{2-3}] streamed snapshot: kv pairs: 25, log entries: 10
I161025 06:58:02.333853 9768 storage/replica_raftstorage.go:577  [n3,s3] [n3,s3,r3/?:{-}]: with replicaID [?], applying preemptive snapshot at index 20 (id=d584cb28, encoded size=16, 1 rocksdb batches, 10 log entries)
I161025 06:58:02.335111 9768 storage/replica_raftstorage.go:580  [n3,s3] [n3,s3,r3/?:/Table/1{2-3}]: with replicaID [?], applied preemptive snapshot in 0.001s
I161025 06:58:02.356115 9351 storage/replica_command.go:3232  [n1,replicate,s1,r3/1:/Table/1{2-3}] change replicas: read existing descriptor range_id:3 start_key:"\224" end_key:"\225" replicas:<node_id:1 store_id:1 replica_id:1 > next_replica_id:2 
I161025 06:58:02.517194 9351 storage/replica.go:1793  [n1,s1,r3/1:/Table/1{2-3}] proposing ADD_REPLICA {NodeID:3 StoreID:3 ReplicaID:2} for range 3: [{NodeID:1 StoreID:1 ReplicaID:1} {NodeID:3 StoreID:3 ReplicaID:2}]
I161025 06:58:02.527846 9351 storage/replica_raftstorage.go:446  [n1,replicate,s1,r4/1:/Table/1{3-4}] generated snapshot cadb2b02 for range 4 at index 27 in 115.3µs.
I161025 06:58:02.558957 9351 storage/store.go:3032  [n1,replicate,s1,r4/1:/Table/1{3-4}] streamed snapshot: kv pairs: 54, log entries: 17
I161025 06:58:02.565560 9760 storage/replica_raftstorage.go:577  [n3,s3] [n3,s3,r4/?:{-}]: with replicaID [?], applying preemptive snapshot at index 27 (id=cadb2b02, encoded size=16, 1 rocksdb batches, 17 log entries)
I161025 06:58:02.566873 9760 storage/replica_raftstorage.go:580  [n3,s3] [n3,s3,r4/?:/Table/1{3-4}]: with replicaID [?], applied preemptive snapshot in 0.001s
I161025 06:58:02.584367 9351 storage/replica_command.go:3232  [n1,replicate,s1,r4/1:/Table/1{3-4}] change replicas: read existing descriptor range_id:4 start_key:"\225" end_key:"\226" replicas:<node_id:1 store_id:1 replica_id:1 > next_replica_id:2 
I161025 06:58:02.670567 9745 storage/raft_transport.go:423  [n3] raft transport stream to node 1 established
I161025 06:58:02.762076 9351 storage/replica.go:1793  [n1,s1,r4/1:/Table/1{3-4}] proposing ADD_REPLICA {NodeID:3 StoreID:3 ReplicaID:2} for range 4: [{NodeID:1 StoreID:1 ReplicaID:1} {NodeID:3 StoreID:3 ReplicaID:2}]
I161025 06:58:02.784827 9366 storage/replica_raftstorage.go:446  [n1,replicate,s1,r1/1:/{Min-Table/11}] generated snapshot 51198327 for range 1 at index 64 in 138.5µs.
I161025 06:58:02.799433 9366 storage/store.go:3032  [n1,replicate,s1,r1/1:/{Min-Table/11}] streamed snapshot: kv pairs: 461, log entries: 54
I161025 06:58:02.800186 9831 storage/replica_raftstorage.go:577  [n3,s3] [n3,s3,r1/?:{-}]: with replicaID [?], applying preemptive snapshot at index 64 (id=51198327, encoded size=16, 1 rocksdb batches, 54 log entries)
I161025 06:58:02.812837 9831 storage/replica_raftstorage.go:580  [n3,s3] [n3,s3,r1/?:/{Min-Table/11}]: with replicaID [?], applied preemptive snapshot in 0.012s
I161025 06:58:02.824332 9366 storage/replica_command.go:3232  [n1,replicate,s1,r1/1:/{Min-Table/11}] change replicas: read existing descriptor range_id:1 start_key:"" end_key:"\223" replicas:<node_id:1 store_id:1 replica_id:1 > replicas:<node_id:2 store_id:2 replica_id:2 > next_replica_id:3 
I161025 06:58:03.072055 9366 storage/replica.go:1793  [n1,s1,r1/1:/{Min-Table/11}] proposing ADD_REPLICA {NodeID:3 StoreID:3 ReplicaID:3} for range 1: [{NodeID:1 StoreID:1 ReplicaID:1} {NodeID:2 StoreID:2 ReplicaID:2} {NodeID:3 StoreID:3 ReplicaID:3}]
I161025 06:58:03.138682 9351 storage/replica_raftstorage.go:446  [n1,replicate,s1,r5/1:/{Table/14-Max}] generated snapshot 65c9c635 for range 5 at index 11 in 118.8µs.
I161025 06:58:03.142771 9351 storage/store.go:3032  [n1,replicate,s1,r5/1:/{Table/14-Max}] streamed snapshot: kv pairs: 9, log entries: 1
I161025 06:58:03.159461 9862 storage/replica_raftstorage.go:577  [n3,s3] [n3,s3,r5/?:{-}]: with replicaID [?], applying preemptive snapshot at index 11 (id=65c9c635, encoded size=16, 1 rocksdb batches, 1 log entries)
I161025 06:58:03.160606 9862 storage/replica_raftstorage.go:580  [n3,s3] [n3,s3,r5/?:/{Table/14-Max}]: with replicaID [?], applied preemptive snapshot in 0.001s
I161025 06:58:03.197890 9351 storage/replica_command.go:3232  [n1,replicate,s1,r5/1:/{Table/14-Max}] change replicas: read existing descriptor range_id:5 start_key:"\226" end_key:"\377\377" replicas:<node_id:1 store_id:1 replica_id:1 > next_replica_id:2 
I161025 06:58:03.388994 9351 storage/replica.go:1793  [n1,s1,r5/1:/{Table/14-Max}] proposing ADD_REPLICA {NodeID:3 StoreID:3 ReplicaID:2} for range 5: [{NodeID:1 StoreID:1 ReplicaID:1} {NodeID:3 StoreID:3 ReplicaID:2}]
I161025 06:58:03.442312 9351 storage/queue.go:620  [n1,replicate] purgatory is now empty
I161025 06:58:03.443883 9366 storage/replica_raftstorage.go:446  [n1,replicate,s1,r2/1:/Table/1{1-2}] generated snapshot aefba278 for range 2 at index 34 in 125.6µs.
I161025 06:58:03.458170 9366 storage/store.go:3032  [n1,replicate,s1,r2/1:/Table/1{1-2}] streamed snapshot: kv pairs: 12, log entries: 24
I161025 06:58:03.463569 9908 storage/replica_raftstorage.go:577  [n3,s3] [n3,s3,r2/?:{-}]: with replicaID [?], applying preemptive snapshot at index 34 (id=aefba278, encoded size=16, 1 rocksdb batches, 24 log entries)
I161025 06:58:03.477098 9908 storage/replica_raftstorage.go:580  [n3,s3] [n3,s3,r2/?:/Table/1{1-2}]: with replicaID [?], applied preemptive snapshot in 0.001s
I161025 06:58:03.486829 9366 storage/replica_command.go:3232  [n1,replicate,s1,r2/1:/Table/1{1-2}] change replicas: read existing descriptor range_id:2 start_key:"\223" end_key:"\224" replicas:<node_id:1 store_id:1 replica_id:1 > replicas:<node_id:2 store_id:2 replica_id:2 > next_replica_id:3 
I161025 06:58:03.811188 9366 storage/replica.go:1793  [n1,s1,r2/1:/Table/1{1-2}] proposing ADD_REPLICA {NodeID:3 StoreID:3 ReplicaID:3} for range 2: [{NodeID:1 StoreID:1 ReplicaID:1} {NodeID:2 StoreID:2 ReplicaID:2} {NodeID:3 StoreID:3 ReplicaID:3}]
I161025 06:58:03.897982 9366 storage/replica_raftstorage.go:446  [n1,replicate,s1,r4/1:/Table/1{3-4}] generated snapshot f11ae8c2 for range 4 at index 37 in 122.5µs.
I161025 06:58:03.920582 9366 storage/store.go:3032  [n1,replicate,s1,r4/1:/Table/1{3-4}] streamed snapshot: kv pairs: 75, log entries: 27
I161025 06:58:03.939943 9713 storage/replica_raftstorage.go:577  [n2,s2] [n2,s2,r4/?:{-}]: with replicaID [?], applying preemptive snapshot at index 37 (id=f11ae8c2, encoded size=16, 1 rocksdb batches, 27 log entries)
I161025 06:58:03.941263 9713 storage/replica_raftstorage.go:580  [n2,s2] [n2,s2,r4/?:/Table/1{3-4}]: with replicaID [?], applied preemptive snapshot in 0.001s
I161025 06:58:03.974251 9366 storage/replica_command.go:3232  [n1,replicate,s1,r4/1:/Table/1{3-4}] change replicas: read existing descriptor range_id:4 start_key:"\225" end_key:"\226" replicas:<node_id:1 store_id:1 replica_id:1 > replicas:<node_id:3 store_id:3 replica_id:2 > next_replica_id:3 
I161025 06:58:04.273693 9366 storage/replica.go:1793  [n1,s1,r4/1:/Table/1{3-4}] proposing ADD_REPLICA {NodeID:2 StoreID:2 ReplicaID:3} for range 4: [{NodeID:1 StoreID:1 ReplicaID:1} {NodeID:3 StoreID:3 ReplicaID:2} {NodeID:2 StoreID:2 ReplicaID:3}]
I161025 06:58:04.303415 9366 storage/replica_raftstorage.go:446  [n1,replicate,s1,r5/1:/{Table/14-Max}] generated snapshot 3714aba2 for range 5 at index 14 in 162.5µs.
I161025 06:58:04.354473 9366 storage/store.go:3032  [n1,replicate,s1,r5/1:/{Table/14-Max}] streamed snapshot: kv pairs: 10, log entries: 4
I161025 06:58:04.371813 9839 storage/replica_raftstorage.go:577  [n2,s2] [n2,s2,r5/?:{-}]: with replicaID [?], applying preemptive snapshot at index 14 (id=3714aba2, encoded size=16, 1 rocksdb batches, 4 log entries)
I161025 06:58:04.373079 9839 storage/replica_raftstorage.go:580  [n2,s2] [n2,s2,r5/?:/{Table/14-Max}]: with replicaID [?], applied preemptive snapshot in 0.001s
I161025 06:58:04.390309 9366 storage/replica_command.go:3232  [n1,replicate,s1,r5/1:/{Table/14-Max}] change replicas: read existing descriptor range_id:5 start_key:"\226" end_key:"\377\377" replicas:<node_id:1 store_id:1 replica_id:1 > replicas:<node_id:3 store_id:3 replica_id:2 > next_replica_id:3 
I161025 06:58:04.868879 9366 storage/replica.go:1793  [n1,s1,r5/1:/{Table/14-Max}] proposing ADD_REPLICA {NodeID:2 StoreID:2 ReplicaID:3} for range 5: [{NodeID:1 StoreID:1 ReplicaID:1} {NodeID:3 StoreID:3 ReplicaID:2} {NodeID:2 StoreID:2 ReplicaID:3}]
I161025 06:58:04.889638 9366 storage/replica_raftstorage.go:446  [n1,replicate,s1,r3/1:/Table/1{2-3}] generated snapshot baa6bcea for range 3 at index 23 in 133µs.
I161025 06:58:04.906843 9884 storage/replica_raftstorage.go:577  [n2,s2] [n2,s2,r3/?:{-}]: with replicaID [?], applying preemptive snapshot at index 23 (id=baa6bcea, encoded size=16, 1 rocksdb batches, 13 log entries)
I161025 06:58:04.908081 9884 storage/replica_raftstorage.go:580  [n2,s2] [n2,s2,r3/?:/Table/1{2-3}]: with replicaID [?], applied preemptive snapshot in 0.001s
I161025 06:58:04.910796 9366 storage/store.go:3032  [n1,replicate,s1,r3/1:/Table/1{2-3}] streamed snapshot: kv pairs: 26, log entries: 13
I161025 06:58:04.929631 9366 storage/replica_command.go:3232  [n1,replicate,s1,r3/1:/Table/1{2-3}] change replicas: read existing descriptor range_id:3 start_key:"\224" end_key:"\225" replicas:<node_id:1 store_id:1 replica_id:1 > replicas:<node_id:3 store_id:3 replica_id:2 > next_replica_id:3 
I161025 06:58:05.482781 9366 storage/replica.go:1793  [n1,s1,r3/1:/Table/1{2-3}] proposing ADD_REPLICA {NodeID:2 StoreID:2 ReplicaID:3} for range 3: [{NodeID:1 StoreID:1 ReplicaID:1} {NodeID:3 StoreID:3 ReplicaID:2} {NodeID:2 StoreID:2 ReplicaID:3}]
I161025 06:58:06.001627 9886 sql/event_log.go:94  [n1,client=127.0.0.1:55589] Event: "create_database", target: 50, info: {DatabaseName:test Statement:CREATE DATABASE test User:root}
I161025 06:58:06.291607 9365 storage/split_queue.go:103  [n1,split,s1,r5/1:/{Table/14-Max}] splitting at keys [/Table/50/0]
I161025 06:58:06.317186 9365 storage/replica_command.go:2354  [n1,split,s1,r5/1:/{Table/14-Max}] initiating a split of this range at key /Table/50 [r6]
I161025 06:58:07.441847 9994 sql/event_log.go:94  [n3,client=127.0.0.1:40050] Event: "create_table", target: 51, info: {TableName:test.table_2 Statement:CREATE TABLE IF NOT EXISTS test.table_2 (id INT PRIMARY KEY, val INT) User:root}
I161025 06:58:08.988413 9365 storage/split_queue.go:103  [n1,split,s1,r6/1:/{Table/50-Max}] splitting at keys [/Table/51/0]
I161025 06:58:09.065094 9365 storage/replica_command.go:2354  [n1,split,s1,r6/1:/{Table/50-Max}] initiating a split of this range at key /Table/51 [r7]
I161025 06:58:10.644642 9871 sql/event_log.go:94  [n1,client=127.0.0.1:55599] Event: "create_table", target: 52, info: {TableName:test.table_3 Statement:CREATE TABLE IF NOT EXISTS test.table_3 (id INT PRIMARY KEY, val INT) User:root}
I161025 06:58:11.721428 9365 storage/split_queue.go:103  [n1,split,s1,r7/1:/{Table/51-Max}] splitting at keys [/Table/52/0]
I161025 06:58:11.751878 9365 storage/replica_command.go:2354  [n1,split,s1,r7/1:/{Table/51-Max}] initiating a split of this range at key /Table/52 [r8]
I161025 06:58:12.258886 9930 sql/event_log.go:94  [n3,client=127.0.0.1:40045] Event: "create_table", target: 51, info: {TableName:test.table_8 Statement:CREATE TABLE IF NOT EXISTS test.table_8 (id INT PRIMARY KEY, val INT) User:root}
E161025 06:58:13.887540 9413 storage/replica.go:3571  [n1,s1,r1/1:/{Min-Table/11}] could not load SystemConfig span: must retry later due to intent on SystemConfigSpan
I161025 06:58:14.472151 9930 sql/event_log.go:94  [n3,client=127.0.0.1:40045] Event: "create_table", target: 53, info: {TableName:test.table_8 Statement:CREATE TABLE IF NOT EXISTS test.table_8 (id INT PRIMARY KEY, val INT) User:root}
W161025 06:58:14.836115 10190 storage/intent_resolver.go:313  [n1,s1,r1/1:/{Min-Table/11}]: failed to push during intent resolution: failed to push "sql/executor.go:540 sql txn implicit" id=ea261bae key=/System/"desc-idgen" rw=true pri=0.10119970 iso=SERIALIZABLE stat=PENDING epo=0 ts=1477378686.423183085,1 orig=1477378686.375594272,0 max=1477378686.400577479,0 wto=false rop=false
I161025 06:58:16.536357 9948 sql/event_log.go:94  [n2,client=127.0.0.1:58306] Event: "create_table", target: 53, info: {TableName:test.table_7 Statement:CREATE TABLE IF NOT EXISTS test.table_7 (id INT PRIMARY KEY, val INT) User:root}
I161025 06:58:19.015364 9995 sql/event_log.go:94  [n3,client=127.0.0.1:40047] Event: "create_table", target: 51, info: {TableName:test.table_5 Statement:CREATE TABLE IF NOT EXISTS test.table_5 (id INT PRIMARY KEY, val INT) User:root}
I161025 06:58:21.550567 9948 sql/event_log.go:94  [n2,client=127.0.0.1:58306] Event: "create_table", target: 53, info: {TableName:test.table_7 Statement:CREATE TABLE IF NOT EXISTS test.table_7 (id INT PRIMARY KEY, val INT) User:root}
I161025 06:58:23.917686 9995 sql/event_log.go:94  [n3,client=127.0.0.1:40047] Event: "create_table", target: 53, info: {TableName:test.table_5 Statement:CREATE TABLE IF NOT EXISTS test.table_5 (id INT PRIMARY KEY, val INT) User:root}
I161025 06:58:24.306596 9630 gossip/gossip.go:1071  [n3] node has connected to cluster via gossip
I161025 06:58:24.318546 9630 storage/stores.go:312  [n3] wrote 2 node addresses to persistent storage
I161025 06:58:25.301264 9495 gossip/gossip.go:1071  [n2] node has connected to cluster via gossip
I161025 06:58:25.309255 9495 storage/stores.go:312  [n2] wrote 2 node addresses to persistent storage
I161025 06:58:26.233571 9990 sql/event_log.go:94  [n1,client=127.0.0.1:55598] Event: "create_table", target: 52, info: {TableName:test.table_0 Statement:CREATE TABLE IF NOT EXISTS test.table_0 (id INT PRIMARY KEY, val INT) User:root}
I161025 06:58:27.355019 9383 gossip/gossip.go:1071  [n1] node has connected to cluster via gossip
I161025 06:58:27.366918 9383 storage/stores.go:312  [n1] wrote 2 node addresses to persistent storage
I161025 06:58:28.680365 9929 sql/event_log.go:94  [n2,client=127.0.0.1:58308] Event: "create_table", target: 51, info: {TableName:test.table_4 Statement:CREATE TABLE IF NOT EXISTS test.table_4 (id INT PRIMARY KEY, val INT) User:root}
I161025 06:58:31.127656 9948 sql/event_log.go:94  [n2,client=127.0.0.1:58306] Event: "create_table", target: 53, info: {TableName:test.table_7 Statement:CREATE TABLE IF NOT EXISTS test.table_7 (id INT PRIMARY KEY, val INT) User:root}
I161025 06:58:32.855712 9990 sql/event_log.go:94  [n1,client=127.0.0.1:55598] Event: "create_table", target: 53, info: {TableName:test.table_0 Statement:CREATE TABLE IF NOT EXISTS test.table_0 (id INT PRIMARY KEY, val INT) User:root}
I161025 06:58:33.952471 10759 storage/raft_transport.go:423  [n3] raft transport stream to node 2 established
I161025 06:58:33.974632 10763 storage/raft_transport.go:423  [n2] raft transport stream to node 3 established
I161025 06:58:34.045353 9802 storage/replica_proposal.go:292  [n3,s3,r8/2:/{Table/52-Max}] new range lease replica {3 3 2} 2016-10-25 06:58:16.506882285 +0000 UTC 26.487551908s following replica {1 1 1} 1970-01-01 00:00:00 +0000 UTC 410382h58m16.506882285s [physicalTime=2016-10-25 06:58:34.045169836 +0000 UTC]
I161025 06:58:34.051655 9783 storage/split_queue.go:103  [n3,split,s3,r8/2:/{Table/52-Max}] splitting at keys [/Table/53/0]
I161025 06:58:34.283416 9415 storage/replica.go:1841  [n1,s1,r8/1:/{Table/52-Max}] not quiescing: 1 pending commands
I161025 06:58:34.542162 9783 storage/replica_command.go:2354  [n3,split,s3,r8/2:/{Table/52-Max}] initiating a split of this range at key /Table/53 [r21]
I161025 06:58:34.977443 9422 storage/replica_proposal.go:341  [n1,s1,r4/1:/Table/1{3-4}] range [n1,s1,r4/1:/Table/1{3-4}]: transferring raft leadership to replica ID 2
I161025 06:58:34.983501 9806 storage/replica_proposal.go:292  [n3,s3,r4/2:/Table/1{3-4}] new range lease replica {3 3 2} 2016-10-25 06:58:16.085744962 +0000 UTC 27.873103149s following replica {1 1 1} 1970-01-01 00:00:00 +0000 UTC 410382h58m16.085744962s [physicalTime=2016-10-25 06:58:34.983321844 +0000 UTC]
I161025 06:58:35.314969 9929 sql/event_log.go:94  [n2,client=127.0.0.1:58308] Event: "create_table", target: 54, info: {TableName:test.table_4 Statement:CREATE TABLE IF NOT EXISTS test.table_4 (id INT PRIMARY KEY, val INT) User:root}
E161025 06:58:35.680456 9423 storage/replica.go:3571  [n1,s1,r1/1:/{Min-Table/11}] could not load SystemConfig span: must retry later due to intent on SystemConfigSpan
I161025 06:58:38.416123 9929 sql/event_log.go:94  [n2,client=127.0.0.1:58308] Event: "create_table", target: 54, info: {TableName:test.table_4 Statement:CREATE TABLE IF NOT EXISTS test.table_4 (id INT PRIMARY KEY, val INT) User:root}
I161025 06:58:40.652944 9989 sql/event_log.go:94  [n1,client=127.0.0.1:55595] Event: "create_table", target: 52, info: {TableName:test.table_6 Statement:CREATE TABLE IF NOT EXISTS test.table_6 (id INT PRIMARY KEY, val INT) User:root}
I161025 06:58:43.047348 9930 sql/event_log.go:94  [n3,client=127.0.0.1:40045] Event: "create_table", target: 54, info: {TableName:test.table_8 Statement:CREATE TABLE IF NOT EXISTS test.table_8 (id INT PRIMARY KEY, val INT) User:root}
I161025 06:58:45.362729 9928 sql/event_log.go:94  [n2,client=127.0.0.1:58311] Event: "create_table", target: 53, info: {TableName:test.table_1 Statement:CREATE TABLE IF NOT EXISTS test.table_1 (id INT PRIMARY KEY, val INT) User:root}
I161025 06:58:47.350120 9929 sql/event_log.go:94  [n2,client=127.0.0.1:58308] Event: "create_table", target: 54, info: {TableName:test.table_4 Statement:CREATE TABLE IF NOT EXISTS test.table_4 (id INT PRIMARY KEY, val INT) User:root}
I161025 06:58:49.537974 9989 sql/event_log.go:94  [n1,client=127.0.0.1:55595] Event: "create_table", target: 54, info: {TableName:test.table_6 Statement:CREATE TABLE IF NOT EXISTS test.table_6 (id INT PRIMARY KEY, val INT) User:root}
E161025 06:58:50.027354 9424 storage/replica.go:3571  [n1,s1,r1/1:/{Min-Table/11}] could not load SystemConfig span: must retry later due to intent on SystemConfigSpan
I161025 06:58:50.825213 9783 storage/split_queue.go:103  [n3,split,s3,r21/2:/{Table/53-Max}] splitting at keys [/Table/54/0]
I161025 06:58:50.846170 9783 storage/replica_command.go:2354  [n3,split,s3,r21/2:/{Table/53-Max}] initiating a split of this range at key /Table/54 [r22]
I161025 06:58:51.183861 9929 sql/event_log.go:94  [n2,client=127.0.0.1:58308] Event: "create_table", target: 55, info: {TableName:test.table_4 Statement:CREATE TABLE IF NOT EXISTS test.table_4 (id INT PRIMARY KEY, val INT) User:root}
I161025 06:58:53.932753 9886 sql/event_log.go:94  [n1,client=127.0.0.1:55589] Event: "create_table", target: 55, info: {TableName:test.table_9 Statement:CREATE TABLE IF NOT EXISTS test.table_9 (id INT PRIMARY KEY, val INT) User:root}
I161025 06:58:55.394832 9930 sql/event_log.go:94  [n3,client=127.0.0.1:40045] Event: "create_table", target: 55, info: {TableName:test.table_8 Statement:CREATE TABLE IF NOT EXISTS test.table_8 (id INT PRIMARY KEY, val INT) User:root}
I161025 06:58:56.807306 9948 sql/event_log.go:94  [n2,client=127.0.0.1:58306] Event: "create_table", target: 54, info: {TableName:test.table_7 Statement:CREATE TABLE IF NOT EXISTS test.table_7 (id INT PRIMARY KEY, val INT) User:root}
E161025 06:58:57.239955 9428 storage/replica.go:3571  [n1,s1,r1/1:/{Min-Table/11}] could not load SystemConfig span: must retry later due to intent on SystemConfigSpan
I161025 06:58:58.492475 9929 sql/event_log.go:94  [n2,client=127.0.0.1:58308] Event: "create_table", target: 55, info: {TableName:test.table_4 Statement:CREATE TABLE IF NOT EXISTS test.table_4 (id INT PRIMARY KEY, val INT) User:root}
I161025 06:58:59.455281 9440 gossip/gossip.go:425  [n1] gossip status (ok, 3 nodes)
gossip client (0/3 cur/max conns)
gossip server (2/3 cur/max conns, infos 1061/27 sent/received, bytes 315939B/4689B sent/received)
  2: 127.0.0.1:49456 (58s)
  3: 127.0.0.1:36790 (58s)
I161025 06:58:59.486638 9886 sql/event_log.go:94  [n1,client=127.0.0.1:55589] Event: "create_table", target: 55, info: {TableName:test.table_9 Statement:CREATE TABLE IF NOT EXISTS test.table_9 (id INT PRIMARY KEY, val INT) User:root}
I161025 06:59:00.499272 9930 sql/event_log.go:94  [n3,client=127.0.0.1:40045] Event: "create_table", target: 55, info: {TableName:test.table_8 Statement:CREATE TABLE IF NOT EXISTS test.table_8 (id INT PRIMARY KEY, val INT) User:root}
I161025 06:59:01.375464 9420 storage/replica_proposal.go:292  [n1,s1,r22/1:/{Table/54-Max}] new range lease replica {1 1 1} 2016-10-25 06:58:59.555283335 +0000 UTC 10.52377989s following replica {3 3 2} 2016-10-25 06:58:16.506882285 +0000 UTC 43.04840105s [physicalTime=2016-10-25 06:59:01.375246422 +0000 UTC]
I161025 06:59:01.442443 9365 storage/split_queue.go:103  [n1,split,s1,r22/1:/{Table/54-Max}] splitting at keys [/Table/55/0]
I161025 06:59:01.513798 9365 storage/replica_command.go:2354  [n1,split,s1,r22/1:/{Table/54-Max}] initiating a split of this range at key /Table/55 [r9]
I161025 06:59:01.537607 9542 gossip/gossip.go:425  [n2] gossip status (ok, 3 nodes)
gossip client (1/3 cur/max conns)
  1: 127.0.0.1:48512 (1m0s: infos 14/604 sent/received, bytes 2374B/182600B sent/received)
gossip server (0/3 cur/max conns, infos 14/604 sent/received, bytes 2374B/182600B sent/received)
I161025 06:59:01.898299 9615 gossip/gossip.go:425  [n3] gossip status (ok, 3 nodes)
gossip client (1/3 cur/max conns)
  1: 127.0.0.1:48512 (1m0s: infos 13/563 sent/received, bytes 2315B/174435B sent/received)
gossip server (0/3 cur/max conns, infos 13/563 sent/received, bytes 2315B/174435B sent/received)
I161025 06:59:01.991249 9886 sql/event_log.go:94  [n1,client=127.0.0.1:55589] Event: "create_table", target: 56, info: {TableName:test.table_9 Statement:CREATE TABLE IF NOT EXISTS test.table_9 (id INT PRIMARY KEY, val INT) User:root}
I161025 06:59:02.042069 9803 storage/replica_proposal.go:341  [n3,s3,r4/2:/Table/1{3-4}] range [n3,s3,r4/2:/Table/1{3-4}]: transferring raft leadership to replica ID 1
I161025 06:59:02.106181 9420 storage/replica_proposal.go:292  [n1,s1,r4/1:/Table/1{3-4}] new range lease replica {1 1 1} 2016-10-25 06:59:00.49283692 +0000 UTC 10.399896168s following replica {3 3 2} 2016-10-25 06:58:16.085744962 +0000 UTC 44.407091958s [physicalTime=2016-10-25 06:59:02.028528894 +0000 UTC]
I161025 06:59:03.321572 9995 sql/event_log.go:94  [n3,client=127.0.0.1:40047] Event: "create_table", target: 56, info: {TableName:test.table_5 Statement:CREATE TABLE IF NOT EXISTS test.table_5 (id INT PRIMARY KEY, val INT) User:root}
E161025 06:59:04.410105 9415 storage/replica.go:3571  [n1,s1,r1/1:/{Min-Table/11}] could not load SystemConfig span: must retry later due to intent on SystemConfigSpan
W161025 06:59:04.545222 11519 storage/intent_resolver.go:313  [n1,s1,r1/1:/{Min-Table/11}]: failed to push during intent resolution: failed to push "sql/executor.go:540 sql txn implicit" id=7437a219 key=/System/"desc-idgen" rw=true pri=0.12563393 iso=SERIALIZABLE stat=PENDING epo=5 ts=1477378740.112545908,1 orig=1477378736.273340787,1 max=1477378705.489181427,0 wto=false rop=false
I161025 06:59:04.597226 9995 sql/event_log.go:94  [n3,client=127.0.0.1:40047] Event: "create_table", target: 56, info: {TableName:test.table_5 Statement:CREATE TABLE IF NOT EXISTS test.table_5 (id INT PRIMARY KEY, val INT) User:root}
I161025 06:59:05.192906 9365 storage/split_queue.go:103  [n1,split,s1,r9/1:/{Table/55-Max}] splitting at keys [/Table/56/0]
I161025 06:59:05.301590 9365 storage/replica_command.go:2354  [n1,split,s1,r9/1:/{Table/55-Max}] initiating a split of this range at key /Table/56 [r10]
I161025 06:59:05.971286 9929 sql/event_log.go:94  [n2,client=127.0.0.1:58308] Event: "create_table", target: 57, info: {TableName:test.table_4 Statement:CREATE TABLE IF NOT EXISTS test.table_4 (id INT PRIMARY KEY, val INT) User:root}
I161025 06:59:06.775661 9365 storage/split_queue.go:103  [n1,split,s1,r10/1:/{Table/56-Max}] splitting at keys [/Table/57/0]
I161025 06:59:06.815408 9365 storage/replica_command.go:2354  [n1,split,s1,r10/1:/{Table/56-Max}] initiating a split of this range at key /Table/57 [r11]
I161025 06:59:08.359433 9886 sql/event_log.go:94  [n1,client=127.0.0.1:55589] Event: "create_table", target: 58, info: {TableName:test.table_9 Statement:CREATE TABLE IF NOT EXISTS test.table_9 (id INT PRIMARY KEY, val INT) User:root}
I161025 06:59:08.931798 9365 storage/split_queue.go:103  [n1,split,s1,r11/1:/{Table/57-Max}] splitting at keys [/Table/58/0]
I161025 06:59:09.049453 9365 storage/replica_command.go:2354  [n1,split,s1,r11/1:/{Table/57-Max}] initiating a split of this range at key /Table/58 [r12]
I161025 06:59:10.227531 9948 sql/event_log.go:94  [n2,client=127.0.0.1:58306] Event: "create_table", target: 56, info: {TableName:test.table_7 Statement:CREATE TABLE IF NOT EXISTS test.table_7 (id INT PRIMARY KEY, val INT) User:root}
I161025 06:59:10.916738 9948 sql/event_log.go:94  [n2,client=127.0.0.1:58306] Event: "create_table", target: 59, info: {TableName:test.table_7 Statement:CREATE TABLE IF NOT EXISTS test.table_7 (id INT PRIMARY KEY, val INT) User:root}
I161025 06:59:11.213915 9365 storage/split_queue.go:103  [n1,split,s1,r12/1:/{Table/58-Max}] splitting at keys [/Table/59/0]
I161025 06:59:11.307596 9365 storage/replica_command.go:2354  [n1,split,s1,r12/1:/{Table/58-Max}] initiating a split of this range at key /Table/59 [r13]
I161025 06:59:12.872319 9214 util/stop/stopper.go:353  stop has been called, stopping or quiescing all running tasks
I161025 06:59:12.875190 11757 util/stop/stopper.go:425  quiescing; tasks left:
1      storage/queue.go:467
1      server/node.go:865
W161025 06:59:12.877282 9745 storage/raft_transport.go:428  [n3] raft transport stream to node 1 failed: EOF
W161025 06:59:12.877738 9495 gossip/gossip.go:1057  [n2] no incoming or outgoing connections
W161025 06:59:12.878303 9686 storage/raft_transport.go:428  [n2] raft transport stream to node 1 failed: EOF
W161025 06:59:12.878605 10763 storage/raft_transport.go:428  [n2] raft transport stream to node 3 failed: EOF
W161025 06:59:12.878918 10759 storage/raft_transport.go:428  [n3] raft transport stream to node 2 failed: rpc error: code = 13 desc = transport is closing
W161025 06:59:12.879212 9649 storage/raft_transport.go:428  [n1] raft transport stream to node 2 failed: rpc error: code = 13 desc = transport is closing
W161025 06:59:12.883312 9846 storage/raft_transport.go:428  [n1] raft transport stream to node 3 failed: EOF
E161025 06:59:12.920771 9369 storage/queue.go:558  [n1,timeSeriesMaintenance] on [n1,s1,r1/1:/{Min-Table/11}]: node unavailable; try another peer
I161025 06:59:12.921114 9214 util/stop/stopper.go:353  stop has been called, stopping or quiescing all running tasks
W161025 06:59:12.921838 9630 gossip/gossip.go:1057  [n3] no incoming or outgoing connections
I161025 06:59:12.933956 9214 util/stop/stopper.go:353  stop has been called, stopping or quiescing all running tasks
I161025 06:59:12.938957 9214 util/stop/stopper.go:353  stop has been called, stopping or quiescing all running tasks
	create_test.go:187: table 1: could not be created: pq: transaction commit result is ambiguous
	create_test.go:224: expected 10 tables created, only got 9
```

### PR DESCRIPTION
**Pull request by spencerkimball**
Instead of assuming the worst in the event that a failing error is
returned from a node and we still have pending RPCs, let those finish.

Fixes #10194

---

This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/10251)

### CODE REVIEW

**Comment by tamird** [comment]
Can you introduce a narrow unit test that reliably hits this?

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks pending.

---

*[pkg/kv/dist_sender.go, line 1027 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10251#-KV2DM1RPeW4OuqdLuw5:-KV2DM1RPeW4OuqdLuw6:bxhihdn) ([raw file](https://github.com/cockroachdb/cockroach/blob/d9f6c5fb64cc2c70a78b3e0bb3e3675226926f85/pkg/kv/dist_sender.go#L1027)):*
> ```Go
> 					} else if ambiguousCommit {
> 						// If we're trying to commit a transaction and we've
> 						// received an ambiguous RPC error, we must return an
> ```

"and we've received an ambiguous RPC error" it's odd that this is the verbiage used to describe a variable named `ambiguousCommit` being `true`.

---

*[pkg/kv/dist_sender.go, line 1047 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10251#-KV2Df7EmIttHTqkYhAu:-KV2Df7EmIttHTqkYhAv:b-awqcws) ([raw file](https://github.com/cockroachdb/cockroach/blob/d9f6c5fb64cc2c70a78b3e0bb3e3675226926f85/pkg/kv/dist_sender.go#L1047)):*
> ```Go
> 					log.Warningf(opts.ctx, "RPC error: %s", err)
> 				}
> 				log.Warningf(opts.ctx, "RPC error: %s", err)
> ```

Remove this or the log.V(1) copy of it above. If you end up acquiring the `git blame` here, consider using `log.ErrEvent`

---

*[pkg/kv/dist_sender.go, line 1082 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10251#-KV2DorA3Ez_Au2ab-LE:-KV2DorA3Ez_Au2ab-LF:b-vtqjze) ([raw file](https://github.com/cockroachdb/cockroach/blob/d9f6c5fb64cc2c70a78b3e0bb3e3675226926f85/pkg/kv/dist_sender.go#L1082)):*
> ```Go
> 			if pending == 0 {
> 				if ambiguousCommit {
> 					log.Infof(opts.ctx, "failing with ambiguous commit flag after all sends complete")
> ```

did you mean to remove this?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10251#-:-KV2DFPPf_byHxWjMNl7:bhx37nv)*

File: pkg/kv/dist_sender.go [hunk 1]
```diff
@@ -1040,6 +1044,7 @@ func (ds *DistSender) sendToReplicas(
 				if log.V(1) {
 					log.Warningf(opts.ctx, "RPC error: %s", err)
 				}
+				log.Warningf(opts.ctx, "RPC error: %s", err)
```
Comment (petermattis) [inline pkg/kv/dist_sender.go]: Sort of redundant with the warning at line 1045, don't you think?

Comment (spencerkimball) [inline pkg/kv/dist_sender.go]: Mistakenly included.

**Comment by spencerkimball** [comment]
I'm sure it's possible but the choreography for something like this is ridiculous.

---

Review status: 0 of 3 files reviewed at latest revision, 4 unresolved discussions, some commit checks pending.

---

*[pkg/kv/dist_sender.go, line 1027 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10251#-KV2DM1RPeW4OuqdLuw5:-KVCFiQRsV-32Id34cVT:bn3xsbp) ([raw file](https://github.com/cockroachdb/cockroach/blob/d9f6c5fb64cc2c70a78b3e0bb3e3675226926f85/pkg/kv/dist_sender.go#L1027)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> "and we've received an ambiguous RPC error" it's odd that this is the verbiage used to describe a variable named `ambiguousCommit` being `true`.
</details>
Care to suggest an improvement?

---

*[pkg/kv/dist_sender.go, line 1047 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10251#-KV2Df7EmIttHTqkYhAu:-KVCFm4Iz4q9Pnq6kKhu:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/d9f6c5fb64cc2c70a78b3e0bb3e3675226926f85/pkg/kv/dist_sender.go#L1047)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> Remove this or the log.V(1) copy of it above. If you end up acquiring the `git blame` here, consider using `log.ErrEvent`
</details>
Done.

---

*[pkg/kv/dist_sender.go, line 1082 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10251#-KV2DorA3Ez_Au2ab-LE:-KVCFnJOZmc1dQR7KgbF:b-7k5prx) ([raw file](https://github.com/cockroachdb/cockroach/blob/d9f6c5fb64cc2c70a78b3e0bb3e3675226926f85/pkg/kv/dist_sender.go#L1082)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> did you mean to remove this?
</details>
Yes it was for testing.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10251#-:-KVCFFqUhijhqh-uiSmC:b-cu1z7r)*

**Comment by spencerkimball** [comment]
@tamird I simplified this dramatically. The other directions had holes in them, so I just made the unittest more lenient.

**Comment by tamird** [comment]
What is the change here now? Everything looks reverted except a few tests and a convenience callback on transactions.

---

Reviewed 6 of 6 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10251#-:-KVCu1HoKCmBhCmuciqQ:bn26fk2)*

**Comment by spencerkimball** [comment]
Indeed. Should be easy to review. The broken test now passes because it retries the create table exec on an ambiguous result error.

**Comment by petermattis** [comment]
:lgtm:

Does this fix all of the tests which are seeing ambiguous commit errors? https://github.com/cockroachdb/cockroach/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aopen%20ambiguous%20commit%20

---

Review status: all files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

*[pkg/sql/create_test.go, line 188 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/10251#-KVGGLbjhbPdlR6EFlfL:-KVGGLbjhbPdlR6EFlfM:b-ecffj0) ([raw file](https://github.com/cockroachdb/cockroach/blob/6ba6ae17067bdbfc29fb46866ffc708a12bb1e99/pkg/sql/create_test.go#L188)):*
> ```Go
> 	for {
> 		if _, err := db.Exec(tableSQL); err != nil {
> 			if testutils.IsSQLRetryableError(err) {
> ```

Apologies for my laziness, but why are tests which use this function seeing ambiguous commits? Are they stopping nodes?

---

*[pkg/sql/create_test.go, line 192 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/10251#-KVGGWldRoj0LEhlhxDj:-KVGGWldRoj0LEhlhxDk:b-p0ig5n) ([raw file](https://github.com/cockroachdb/cockroach/blob/6ba6ae17067bdbfc29fb46866ffc708a12bb1e99/pkg/sql/create_test.go#L192)):*
> ```Go
> 			}
> 			t.Errorf("table %d: could not be created: %v", id, err)
> 			return
> ```

`return` on this code path vs `break` on the other is unnecessarily asymmetric. How about pulling the `break` out into the common path?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10251#-:-KVGGo5eVXPxTzFmzF6p:b2ahafd)*

**Comment by spencerkimball** [comment]
It fixes the create tables tests but not the others. I'll mark the appropriate ones as fixed in the PR.

---

Review status: all files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

*[pkg/sql/create_test.go, line 188 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/10251#-KVGGLbjhbPdlR6EFlfL:-KVGntiIGYXtQwBEE-EL:btc2n7g) ([raw file](https://github.com/cockroachdb/cockroach/blob/6ba6ae17067bdbfc29fb46866ffc708a12bb1e99/pkg/sql/create_test.go#L188)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary>
> Apologies for my laziness, but why are tests which use this function seeing ambiguous commits? Are they stopping nodes?
</details>
Original failures were caused by the following sort of problem:

- Request to create the table goes to n1, is eventually successful but takes too long
- Leadership changes to n2 or n3 
- `DistSender` times out and sends to n2
- n2 returns error on missing txn record (already cleaned up)
- because pending > 0 (call to n1 still outstanding), we returned `AmbiguousCommitError`

---

*[pkg/sql/create_test.go, line 192 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/10251#-KVGGWldRoj0LEhlhxDj:-KVGvPAJv5F39f6yzO-z:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/6ba6ae17067bdbfc29fb46866ffc708a12bb1e99/pkg/sql/create_test.go#L192)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary>
> `return` on this code path vs `break` on the other is unnecessarily asymmetric. How about pulling the `break` out into the common path?
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10251#-:-KVGnoZzVD7Q7FFRlbKy:b6mb9tu)*

**Comment by spencerkimball** [comment]
Fixes #10308 
Fixes #10307 
Fixes #10281 
Fixes #10194

**Comment by tamird** [comment]
Leaving "Fixes ..." as a comment doesn't trigger automatic closing of issues.

**Comment by petermattis** [comment]
Review status: 4 of 5 files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

*[pkg/sql/create_test.go, line 188 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/10251#-KVGGLbjhbPdlR6EFlfL:-KVLDldv7I6zWPtAihGr:bi3j96) ([raw file](https://github.com/cockroachdb/cockroach/blob/6ba6ae17067bdbfc29fb46866ffc708a12bb1e99/pkg/sql/create_test.go#L188)):*
<details><summary><i>Previously, spencerkimball (Spencer Kimball) wrote…</i></summary>
> Original failures were caused by the following sort of problem:
> 
> - Request to create the table goes to n1, is eventually successful but takes too long
> - Leadership changes to n2 or n3 
> - `DistSender` times out and sends to n2
> - n2 returns error on missing txn record (already cleaned up)
> - because pending > 0 (call to n1 still outstanding), we returned `AmbiguousCommitError`
> 
</details>
The above scenario is almost exactly what I was worried could be causing the double-insert problem in the Jepsen tests. In this scenario we returned an `AmbiguousCommitError`, but is that guaranteed to happen? If it doesn't it seems like the higher level could retry. Perhaps we shouldn't use the send-next timeout when the batch contains an `EndTransaction`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10251)*

**Comment by bdarnell** [comment]
It's too late to change it now, but the commit message no longer describes the actual change. In the future please remember to edit your commit message when making major changes to a commit.
