### PR TITLE
changefeedccl: fix race between GC and event decoding in regression test

### LINKED ISSUE #167508: release-26.2: ccl/changefeedccl: TestCachedEventDescriptorGivesUpdatedTimestamp failed
ccl/changefeedccl.TestCachedEventDescriptorGivesUpdatedTimestamp [failed](https://mesolite.cluster.engflow.com/invocations/default/58364688-0ab1-430b-8cd0-11ab462b032d?testReportRun=9&testReportShard=6&testReportAttempt=1#targets-Ly9wa2cvY2NsL2NoYW5nZWZlZWRjY2w6Y2hhbmdlZmVlZGNjbF90ZXN0) on release-26.2 @ [6b0453e632edd45ccfdd008f3a1bcda3e65b5608](https://github.com/cockroachdb/cockroach/commits/6b0453e632edd45ccfdd008f3a1bcda3e65b5608):

```
=== RUN   TestCachedEventDescriptorGivesUpdatedTimestamp
    test_log_scope.go:172: test logs captured to: outputs.zip/logTestCachedEventDescriptorGivesUpdatedTimestamp3221112851
    test_log_scope.go:82: use -show-logs to present logs inline
    changefeed_stmt.go:1953: requireNoFeedsFail: unexpected error: error in retrieving descs between 1775277802.906387993,0, 1775277802.944775178,0: batch timestamp 1775277802.906387993,0 must be after replica GC threshold 1775277802.999004495,0 (r8: /Table/{3-4})
    protected_timestamps_test.go:1513: -- test log scope end --
test logs left over in: outputs.zip/logTestCachedEventDescriptorGivesUpdatedTimestamp3221112851
--- FAIL: TestCachedEventDescriptorGivesUpdatedTimestamp (3.20s)
=== RUN   TestCachedEventDescriptorGivesUpdatedTimestamp/enterprise
    helpers_test.go:1579: making server as system tenant
    test_server_shim.go:638: DRPC is enabled (via testserver factory defaults)
    helpers_test.go:1655: making enterprise feed factory
    helpers_test.go:1669: pgURL enterprise root
    protected_timestamps_test.go:1471: Timestamp after DB descriptor version change: 1775277802.999004495,0
    protected_timestamps_test.go:1412: Event 1 timestamp: 1775277802.906387993,0
    protected_timestamps_test.go:1386: GCing database descriptor table at timestamp: 1775277802.999004495,0
    protected_timestamps_test.go:1502: changefeed error: error in retrieving descs between 1775277802.906387993,0, 1775277802.944775178,0: batch timestamp 1775277802.906387993,0 must be after replica GC threshold 1775277802.999004495,0 (r8: /Table/{3-4})
--- FAIL: TestCachedEventDescriptorGivesUpdatedTimestamp/enterprise (3.19s)
```

Parameters:
 - <code>attempt=1</code>
 - <code>run=9</code>
 - <code>shard=6</code>
<details><summary>Help</summary>
<p>

See also: [How To Investigate a Go Test Failure \(internal\)](https://cockroachlabs.atlassian.net/l/c/HgfXfJgM)
</p>
</details>
/cc @cockroachdb/cdc
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*TestCachedEventDescriptorGivesUpdatedTimestamp.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/bazci/githubpost/issues)

</sub>

Jira issue: CRDB-62494

### PR DESCRIPTION
**Pull request by aerfrei**
The TestCachedEventDescriptorGivesUpdatedTimestamp test could flake
because it triggered GC on system.descriptor before the first row had
been fully decoded by the changefeed consumer. DecodeKV calls
leaseMgr.Acquire which may need to read historical descriptor versions
from system.descriptor via an ExportRequest. If the GC threshold was
advanced before this Acquire completed, the read would fail with a
"batch timestamp must be after replica GC threshold" error unrelated
to the bug the test is designed to catch.

Fix this by waiting for the first row to be emitted (via BeforeEmitRow
knob) before allowing the GC to proceed, ensuring the lease manager has
already acquired any needed descriptor versions.

Also clarifies existing comments to avoid "event 1" language which was
confusing.

Fixes: https://github.com/cockroachdb/cockroach/issues/167508
Epic: none
Release note: None

### CODE REVIEW

File: pkg/ccl/changefeedccl/protected_timestamps_test.go [hunk 1]
```diff
@@ -1367,6 +1368,12 @@ func TestCachedEventDescriptorGivesUpdatedTimestamp(t *testing.T) {
 		var dbDescTS atomic.Value
 		dbDescTS.Store(hlc.Timestamp{})
 		var hasGCdDBDesc atomic.Bool
+		// event1Consumed is closed when Event 1 has been fully consumed
+		// (decoded) by the changefeed consumer. Waiting on this ensures that
+		// it is safe to GC to that timestamp. If we didn't, decoding the event
+		// would race with GC.
+		event1Consumed := make(chan struct{})
```
Comment (rharding6373) [inline pkg/ccl/changefeedccl/protected_timestamps_test.go]: nit: the channel name could be improved for clarity. One option is `firstRowDecoded`/`firstRowDecodedOnce` or `safeToGC` to convey the gating purpose of the channel.

Could also rephrase the comments to make it more clear. Since theres no `event1` or similar in the code, the comments are hard to understand.

**Review by rharding6373 — APPROVED** [review]
Overall premise LGTM, but please consider the suggestions for better naming.

File: pkg/ccl/changefeedccl/protected_timestamps_test.go (hunk 1 above)
Comment (aerfrei) [reply pkg/ccl/changefeedccl/protected_timestamps_test.go]: These are good suggestions, thanks! I was having some issues making the comments clear. I changed them not to use "event 1" terminology more generally which I think helps with readability in this comment heavy test. TFTR!
