### PR TITLE
kvcoord: optionally update range cache with descriptor returned in NLHE 

### LINKED ISSUE #75742: kvclient: requests can spuriously backoff due to stale range descriptors
**Describe the problem**

We have a backoff mechanism in the DistSender to throttle requests during a lease transfer, where the would be lease holder has not applied the lease yet. We use the following check as a proxy for this scenario:

https://github.com/cockroachdb/cockroach/blob/ba04380bfbca30bf16e15048786716bec510a263/pkg/kv/kvclient/kvcoord/dist_sender.go#L2177-L2182

It turns out that this check can be overaggressive in certain scenarios, specifically the `updatedLeaseholder` determination. This, in conjunction with a transport constructed from a stale range descriptor and stale lease information, can lead to requests being caught in series of exponential backoffs causing high (tail) latencies. 

Concretely, consider the case where there's been a lease transfer to a replica that was a LEARNER on the requesting client's range descriptor. If the client has stale lease information as well then we would omit the [leaseholder when constructing the transport](https://github.com/cockroachdb/cockroach/blob/ba04380bfbca30bf16e15048786716bec510a263/pkg/kv/kvclient/kvcoord/replica_slice.go#L61-L63). 

A concurrent request could then update the client's cached lease information with the new leaseholder. Then, when the original request receives a NLHE, it tries to update the lease information on its eviction token. We first sync the eviction token with the RangeCache before updating the lease using the NLHE. If the range cache was updated underneath us to the new lease in the NLHE, we incorrectly determine that the leaseholder wasn't updated: 

https://github.com/cockroachdb/cockroach/blob/92f0260764a8d31d28f4ecae288c19c8468c2e0e/pkg/kv/kvclient/rangecache/range_cache.go#L389-L396

Further up the stack we incorrectly detect this as the case where there is a lease transfer in progress but the would be leaseholder hasn't applied the lease yet. This results in the request getting caught in backoffs. 

The situation is further exacerbated by the leaseholder not being a part of the transport ([when we try to move it to be considered as the next replica to try](https://github.com/cockroachdb/cockroach/blob/ba04380bfbca30bf16e15048786716bec510a263/pkg/kv/kvclient/kvcoord/dist_sender.go#L2166-L2168)). We essentially end up trying all replicas until we exhaust the transport and exponentially backing off between each request. 

Once the transport is exhausted we recognize that the range descriptor was stale, evict it. The subsequent retry then succeeds the very first time. 

----

We didn't see this in the traces that we looked at, but this hazard probably also applies in the case of this TODO:

https://github.com/cockroachdb/cockroach/blob/92f0260764a8d31d28f4ecae288c19c8468c2e0e/pkg/kv/kvclient/rangecache/range_cache.go#L1355-L1363

albeit for all replicas on the transport tried after we hit this codepath, considering we're actually updating the lease information above, and would thus skip backing off in that particular iteration. 

----

We can do a few things to improve this situation. At a high level, we probably want to detect the scenario where we have newer lease information than what the routing was created with and the new lease information is incompatible with the range descriptor the routing was created with. We are guaranteed to never try the leaseholder, as it doesn't exist on the transport, so we can simply clear the routing to exit early and force the client to try again. 

We recently started returning the [range descriptor's generation in the NLHE](https://github.com/cockroachdb/cockroach/pull/73697). We could extend this to return the entire range descriptor and using it to update the RangeCache (and thus skipping the range descriptor eviction described above). 

cc @cockroachdb/kv-notifications 

Jira issue: CRDB-12812

gz#11447

### LINKED ISSUE #82802: kv: uninitialized replica can cause unbounded backoff due to stale range descriptors
Related to https://github.com/cockroachdb/cockroach/issues/75742, but not the same.

When running the test described in https://github.com/cockroachdb/cockroach/issues/79385, I ran into a `NotLeaseHolderError` loop. However, it wasn't the same one described in that issue. In my reproduction, only requests originating on the slow node got stuck. This was because the lease was not transferred to a replica that needed a snapshot.

Screen Shot 2022-06-13 at 12 48 13 AM

Looking at logspy, I found the following loop for a few different ranges. Here are the logs scoped down to a single range:
```
I220613 04:42:09.431639 91225 kv/kvclient/kvcoord/dist_sender.go:1969 ⋮ [n3,s3,r1/2:‹/{Min-System/NodeL…}›] 1943 routing to nearest replica; leaseholder not known
I220613 04:42:09.431665 91225 kv/kvclient/kvcoord/dist_sender.go:2032 ⋮ [n3,s3,r1/2:‹/{Min-System/NodeL…}›] 1944 r254: sending batch ‹1 PushTxn› to (n3,s3):1
E220613 04:42:09.431760 91225 kv/kvclient/kvcoord/dist_sender.go:2144 ⋮ [n3,s3,r1/2:‹/{Min-System/NodeL…}›] 1946 ‹[NotLeaseHolderError] r254: replica (n3,s3):1 not lease holder; replica (n4,s4):2 is›
E220613 04:42:09.431826 91225 kv/kvclient/kvcoord/dist_sender.go:2245 ⋮ [n3,s3,r1/2:‹/{Min-System/NodeL…}›] 1947 application error: ‹[NotLeaseHolderError] r254: replica (n3,s3):1 not lease holder; replica (n4,s4):2 is›
I220613 04:42:09.431929 91225 kv/kvclient/kvcoord/dist_sender.go:1652 ⋮ [n3,s3,r1/2:‹/{Min-System/NodeL…}›] 1948 evicting range desc ‹desc:r254:/Table/106/1/39{488508-540666} [(n3,s3):1, (n2,s2):5, (n8,s8):3, next=6, gen=98, sticky=1655092870.755128344,0] lease:<nil> spec desc: <nil>› after ‹failed to send RPC: sending to all replicas failed; last error: routing information detected to be stale: [NotLeaseHolderError] r254: replica (n3,s3):1 not lease holder; replica (n4,s4):2 is›

I220613 04:42:09.494195 124423 kv/kvclient/kvcoord/dist_sender.go:2032 ⋮ [n3,replicaGC,s3,r428/2:‹/Table/106/1/5{26127…-85900…}›] 2021 r1: sending batch ‹1 Scan› to (n1,s1):1
I220613 04:42:09.647134 124467 kv/kvclient/kvcoord/dist_sender.go:2032 ⋮ [n3,s3,r1/2:‹/{Min-System/NodeL…}›,range-lookup=‹/Table/106/1/21627091›] 2216 r1: sending batch ‹1 Scan› to (n1,s1):1

I220613 04:42:10.386035 91225 kv/kvclient/kvcoord/dist_sender.go:1969 ⋮ [n3,s3,r1/2:‹/{Min-System/NodeL…}›] 2835 routing to nearest replica; leaseholder not known
I220613 04:42:10.386069 91225 kv/kvclient/kvcoord/dist_sender.go:2032 ⋮ [n3,s3,r1/2:‹/{Min-System/NodeL…}›] 2836 r254: sending batch ‹1 PushTxn› to (n3,s3):1
E220613 04:42:10.386168 91225 kv/kvclient/kvcoord/dist_sender.go:2144 ⋮ [n3,s3,r1/2:‹/{Min-System/NodeL…}›] 2838 ‹[NotLeaseHolderError] r254: replica (n3,s3):1 not lease holder; replica (n4,s4):2 is›
E220613 04:42:10.386247 91225 kv/kvclient/kvcoord/dist_sender.go:2245 ⋮ [n3,s3,r1/2:‹/{Min-System/NodeL…}›] 2839 application error: ‹[NotLeaseHolderError] r254: replica (n3,s3):1 not lease holder; replica (n4,s4):2 is›
I220613 04:42:10.386377 91225 kv/kvclient/kvcoord/dist_sender.go:1652 ⋮ [n3,s3,r1/2:‹/{Min-System/NodeL…}›] 2840 evicting range desc ‹desc:r254:/Table/106/1/39{488508-540666} [(n3,s3):1, (n2,s2):5, (n8,s8):3, next=6, gen=98, sticky=1655092870.755128344,0] lease:<nil> spec desc: <nil>› after ‹failed to send RPC: sending to all replicas failed; last error: routing information detected to be stale: [NotLeaseHolderError] r254: replica (n3,s3):1 not lease holder; replica (n4,s4):2 is›
```

What's happening here is the following:
1. n3 does not know the lease for r254, so it sends to its local replica first
2. n3's replica for r254 is uninitialized, so it returns a `NotLeaseHolderError` pointing at n4. The code and explanation for this are [here](https://github.com/cockroachdb/cockroach/blob/87da966cbc15e058591d80c477c78d6059483a5c/pkg/kv/kvserver/store_send.go#L176-L194).
3. n3 receives the NotLeaseHolderError, does not find n4 in the descriptor, so [it evicts it](https://github.com/cockroachdb/cockroach/blob/87da966cbc15e058591d80c477c78d6059483a5c/pkg/kv/kvclient/rangecache/range_cache.go#L1352) before ever trying the other replicas in its cached descriptor
4. n3 performs a meta lookup and receives the same range descriptor with `(n3,s3):1, (n2,s2):5, (n8,s8):3`
5. rinse, repeat

I believe this is a special case of https://github.com/cockroachdb/cockroach/issues/72772. However, the fix for that issue (https://github.com/cockroachdb/cockroach/pull/73697) is not helping because this [specific constructor](https://github.com/cockroachdb/cockroach/blob/87da966cbc15e058591d80c477c78d6059483a5c/pkg/kv/kvserver/store_send.go#L176-L194) for NotLeaseHolderErrors does not attach a RangeDescriptor, which disables the client-side logic to detect stale NotLeaseHolderErrors.

We could fix this in either of two ways:
1. we could return a fake RangeDescriptor with a Generation of 1 in this NotLeaseHolderErrors constructor, indicating that if there's incoherence between the cache and the returned lease hint, the cache is probably more up-to-date.
2. now that we've migrated this field in, we could change the [client-side logic](https://github.com/cockroachdb/cockroach/blob/87da966cbc15e058591d80c477c78d6059483a5c/pkg/kv/kvclient/rangecache/range_cache.go#L1349) to _not_ evict the range descriptor if the Generation is not returned and the suggested lease is not part of the cached range descriptor. Essentially just `s/descGeneration != 0 && //`.

I prefer the second option. It avoids the need to construct a fake RangeDescriptor (who knows where that could leak) and it centralizes the logic for how to handle this case in the client, where it probably belongs.

cc. @arulajmani 

Jira issue: CRDB-16670

### PR DESCRIPTION
**Pull request by arulajmani**
We recently started shipping the range descriptors back on
NotLeaseHolderError. Prior to this patch, we only ever used their
generation to elide certain lease updates if they originated from a
replica that had an older (stale) view of this world.

This patch goes a step further in making use of the returned range
descriptor -- we now update the client's range cache if the returned
range descriptor is newer than what existed on the client. We do this
by picking the freshest range descriptor and lease, independently, from
the range descriptor/lease between what exists in the client's range
cache and what was returned in the NLHE. Though unlikely, independently
choosing the freshest lease/range descriptor can lead to cases where the
lease is not compatible with the range descriptor. If we detect this to
be the case, we empty out the lease and simply cache the freshest range
descriptor.

Previously, we always accepted speculative leases to be more recent than
anything already in the cache. Now, we discard speculative leases if
they're coming from a replica that has an older view of the world.
Morally, these semantics are the right way to conceptualize https://github.com/cockroachdb/cockroach/issues/72772,
given that hazard could only ever exist for speculative leases. https://github.com/cockroachdb/cockroach/issues/82802
also falls out as a special case of this conceptualization, so closing
that issue simply entails adding a regression test.

We also get rid of optimizations where we would try to identify "stale"
range descriptors when updating lease information. These no longer make
sense given we don't just update the lease, we also update the range
descriptor. These optimizations also didn't account for all possible
cases, such as when the leaseholder was present on the range
descriptor, but as a LEARNER. See https://github.com/cockroachdb/cockroach/issues/75742 for more details about how
this hazard manifests.

With this new approach we also address https://github.com/cockroachdb/cockroach/issues/82802. Instead of invalidating
the routing when a descriptor is identified as stale and using that as
a proxy to bail early when routing to replicas, we instead switch to a
more direct approach -- if at any point we detect the leaseholder isn't
included on the transport, we exit the routing logic early, and retry
at a layer above. Given our new range cache update semantics using
descriptors on NLHE errors, it's quite likely this retry circumvents a
range descriptor lookup -- instead, we'd expect this to simply amount to
trying again with a newly constructed transport. The rationale is that
even though the client may have an arbitrarily stale view of the range,
we never expect it to regress. Thus, if the leaseholder was updated on
the client and it doesn't exist on the transport, it must be the case
that the transport was constructed using a stale range descriptor and
stale leaseholder information. As such, there is likely not much value
in trying to exhaust the transport (and potentially getting caught in
backoff loops). We're much better served by bailing early and trying
again with a fresh transport.

Fixes https://github.com/cockroachdb/cockroach/issues/82802
Fixes https://github.com/cockroachdb/cockroach/issues/75742

Release note: None
Release justification: Fixes for high priority bugs in existing
functionality.

### CODE REVIEW

File: pkg/startupmigrations/migrations.go [hunk 1]
```diff
@@ -626,7 +626,7 @@ func (m *Manager) EnsureMigrations(ctx context.Context, bootstrapVersion roachpb
 		}
 
 		if log.V(1) {
-			log.Infof(ctx, "running migration %q", migration.name)
```
Comment (ajwerner) [inline pkg/startupmigrations/migrations.go:629]: why?

Comment (arulajmani) [reply pkg/startupmigrations/migrations.go]: Wasn't intentional, reverted.

**Review by erikgrinaker — APPROVED** [review]
This looks great (modulo build failures), thanks for fixing this!

> Reviewed 1 of 1 files at r1, 1 of 1 files at r2, 7 of 7 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/85503#-:-N8Y77T8B0FNUnkhx-c0:b46k5mi)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @aayushshah15 and @nvanbenschoten)

**Review by arulajmani — COMMENTED** [review]
This was missing the case where the descriptor returned in the NLHE was incompatible with what was in the token/cache, which was the reason for a fair few build failures. We now account for this case by:
- treating things as a no-op if the incompatible descriptor is older than what's in the cache. 
- invalidating the token and updating the cache with the supplied descriptor/lease pair if the descriptor is newer. 

Separately, @nvanbenschoten, after our discussion yesterday I realized that the way I've structured this code we'll never take advantage of how uninitialized replicas construct their NotLeaseHolderErrrors (https://github.com/cockroachdb/cockroach/blob/87da966cbc15e058591d80c477c78d6059483a5c/pkg/kv/kvserver/store_send.go#L176-L194 being the code snippet from the original issue). As is, even if the replica returned in the NLHE error is part of the transport, we'll try the next replica on the transport instead of the one returned by an uninitialized replica. I'm a bit partial to keeping things the way they are as it keeps things understandable, but we could add some special casing to bring this behaviour back. Do you think this optimization is worth it to do so?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/85503#-:-N8ddNuK09-H9F3aLWay:bj2rud0)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @aayushshah15, @erikgrinaker, and @nvanbenschoten)

**Review by nvb — COMMENTED** [review]
I'm still working my way through the tests, but flushing what I have so far.

> Reviewed 1 of 1 files at r1, 1 of 1 files at r2, 1 of 7 files at r3, 1 of 4 files at r4, 1 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/85503#-:-N8eQyMbCn8fBbbTeU-4:b-ij6wa2)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @aayushshah15, @arulajmani, and @erikgrinaker)

___
*[`-- commits` line 4 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/85503#-N8Zk4K0E63sp0m8ZlU8):*
Reminder to address this TODO.
___
*[`-- commits` line 36 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/85503#-N8dmtIH5k_kuUAk0_P_):*
TODO: is this still true?
___
*[`pkg/kv/kvclient/rangecache/range_cache.go` line 317 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/85503#-N8dnaMpCf8nguRr7Qsc:-N8dnaMpCf8nguRr7Qsd:bkhemu6) ([raw file](https://github.com/cockroachdb/cockroach/blob/9230f9aaef000ded75efa63258a183128ae51a75/pkg/kv/kvclient/rangecache/range_cache.go#L317)):*
> ```Go
> // information, returns nil. The result is considered immutable.
> func (et EvictionToken) Lease() *roachpb.Lease {
> 	return et.lease
> ```

nit: should this have a `if !et.Valid() {` check like we have in `Desc()`?
___
*[`pkg/kv/kvclient/rangecache/range_cache.go` line 367 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/85503#-N8e4r1I-URoFe0R7npy:-N8e4r1JCFoo47K-IvRF:b-r46ocu) ([raw file](https://github.com/cockroachdb/cockroach/blob/9230f9aaef000ded75efa63258a183128ae51a75/pkg/kv/kvclient/rangecache/range_cache.go#L367)):*
> ```Go
> // EvictionToken itself).
> //
> // The bool `updatedLeaseholder` is true if the leaseholder was updated in the
> ```

nit: this makes it sounds like a parameter. Consider `The returned bool ...`.
___
*[`pkg/kv/kvclient/rangecache/range_cache.go` line 368 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/85503#-N8e5Jyc0DtrjWA1meSa:-N8e5Jyc0DtrjWA1meSb:bxhekv1) ([raw file](https://github.com/cockroachdb/cockroach/blob/9230f9aaef000ded75efa63258a183128ae51a75/pkg/kv/kvclient/rangecache/range_cache.go#L368)):*
> ```Go
> //
> // The bool `updatedLeaseholder` is true if the leaseholder was updated in the
> // cache (i.e the passed-in lease was more recent than the cached lease).
> ```

What about if the cache had a lease that was more recent than that in both the token and the one which was handed in? We will update the token in that case, right? Will we return true?
___
*[`pkg/kv/kvclient/rangecache/range_cache.go` line 381 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/85503#-N8eLbKyCsSVtLmmAklQ:-N8eLbKyCsSVtLmmAklR:brv50ld) ([raw file](https://github.com/cockroachdb/cockroach/blob/9230f9aaef000ded75efa63258a183128ae51a75/pkg/kv/kvclient/rangecache/range_cache.go#L381)):*
> ```Go
> // in-turn will be overwritten by any subsequent update).
> func (et *EvictionToken) SyncTokenAndMaybeUpdateCache(
> 	ctx context.Context, l *roachpb.Lease, rangeDesc *roachpb.RangeDescriptor,
> ```

Is the range descriptor guaranteed to be non-empty on every error path? Even in mixed version clusters?
___
*[`pkg/kv/kvclient/rangecache/range_cache.go` line 387 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/85503#-N8e59sBBCEypVooG1yU:-N8e59sBBCEypVooG1yV:b-943me9) ([raw file](https://github.com/cockroachdb/cockroach/blob/9230f9aaef000ded75efa63258a183128ae51a75/pkg/kv/kvclient/rangecache/range_cache.go#L387)):*
> ```Go
> 	defer rdc.rangeCache.Unlock()
> 
> 	// TODO(arul): Check for compatibility between the supplied range descriptor
> ```

You were planning to address this TODO in this PR, right?
___
*[`pkg/kv/kvclient/rangecache/range_cache.go` line 391 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/85503#-N8eQXcpBK3jGP0gpgYm:-N8eQXcpBK3jGP0gpgYn:byna72g) ([raw file](https://github.com/cockroachdb/cockroach/blob/9230f9aaef000ded75efa63258a183128ae51a75/pkg/kv/kvclient/rangecache/range_cache.go#L391)):*
> ```Go
> 	// maybeUpdate does) if the descriptors are compatible.
> 
> 	stillValid, cachedEntry, rawEntry := et.syncRLocked(ctx)
> ```

How should this method behave when this sync updates the leaseholder but the `maybeUpdate` below does not? Should it return `true`?
___
*[`pkg/kv/kvclient/rangecache/range_cache.go` line 410 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/85503#-N8eLqVm-5oBOm8SoSCJ:-N8eLqVm-5oBOm8SoSCK:behpw3v) ([raw file](https://github.com/cockroachdb/cockroach/blob/9230f9aaef000ded75efa63258a183128ae51a75/pkg/kv/kvclient/rangecache/range_cache.go#L410)):*
> !descsCompatible(rangeDesc, et.Desc())

We're checking this condition twice. Should we rewrite as:
```go
if !descsCompatible(rangeDesc, et.Desc()) {
    if rangeDesc.Generation < et.Desc().Generation {
        return false
    }
    ...
}
```
___
*[`pkg/kv/kvclient/rangecache/range_cache.go` line 418 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/85503#-N8eMvELEKZGJLPvxH42:-N8eMvEM5sGKuFbt56_K:b-sxnl2i) ([raw file](https://github.com/cockroachdb/cockroach/blob/9230f9aaef000ded75efa63258a183128ae51a75/pkg/kv/kvclient/rangecache/range_cache.go#L418)):*
> ```Go
> 		// The cachedEntry wasn't updated; no need to replace it with newEntry in
> 		// the RangeCache.
> 		return updatedLeaseholder
> ```

If `!updated`, don't we know that `!updatedLeaseholder`? If so, then should we `return false`?
___
*[`pkg/kv/kvclient/rangecache/range_cache.go` line 426 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/85503#-N8ePyxTAwzJxKR02VEO:-N8ePyxTAwzJxKR02VEP:b-2bc2ul) ([raw file](https://github.com/cockroachdb/cockroach/blob/9230f9aaef000ded75efa63258a183128ae51a75/pkg/kv/kvclient/rangecache/range_cache.go#L426)):*
> ```Go
> 	et.desc = newEntry.Desc()
> 	et.lease = newEntry.leaseEvenIfSpeculative()
> 	return updatedLeaseholder
> ```

Are we ok with returning false here if we updated the descriptor but not the leaseholder? Will the client handle that case correctly?
___
*[`pkg/kv/kvclient/rangecache/range_cache.go` line 1338 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/85503#-N8eMEcM2VkUXT_wXXfn:-N8eMEcM2VkUXT_wXXfo:b-pyco7m) ([raw file](https://github.com/cockroachdb/cockroach/blob/9230f9aaef000ded75efa63258a183128ae51a75/pkg/kv/kvclient/rangecache/range_cache.go#L1338)):*
> ```Go
> // descriptor by comparing the receiver's fields to the passed-in parameters.
> // The updatedLease retval indicates whether the passed-in lease appears to be
> // newer than the lease the entry had before.
> ```

Do you want to give this paragraph a similar "If updatedLease is returned true, ..." sentence?
___
*[`pkg/kv/kvclient/rangecache/range_cache.go` line 1340 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/85503#-N8eMfhzA8dNelUWLauL:-N8eMfhzA8dNelUWLauM:b-whoqvz) ([raw file](https://github.com/cockroachdb/cockroach/blob/9230f9aaef000ded75efa63258a183128ae51a75/pkg/kv/kvclient/rangecache/range_cache.go#L1340)):*
> ```Go
> // newer than the lease the entry had before.
> //
> // The updated retval indicates if either the passed-in lease or the range
> ```

I found the combination of an `updatedLease` and an `updated` return value to be confusing. It wasn't clear from the caller whether one implied the other or why I needed to care about both. It would be good to detail that.

It's minor, but I think switching the order of these return values would help. I say that because if `updated` is a broader condition than `updatedLease`, then most callers will first consult `updated` and then only care about `updatedLease` is `updated` is true.
___
*[`pkg/kv/kvclient/rangecache/range_cache.go` line 1357 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/85503#-N8eMbYJ2Emmbw35Ozc3:-N8eMbYJ2Emmbw35Ozc4:belaz8p) ([raw file](https://github.com/cockroachdb/cockroach/blob/9230f9aaef000ded75efa63258a183128ae51a75/pkg/kv/kvclient/rangecache/range_cache.go#L1357)):*
> ```Go
> func (e *CacheEntry) maybeUpdate(
> 	ctx context.Context, l *roachpb.Lease, rangeDesc *roachpb.RangeDescriptor,
> ) (updatedLease bool, updated bool, newEntry *CacheEntry) {
> ```

nit: `) (updatedLease, updated bool, newEntry *CacheEntry) {`
___
*[`pkg/kv/kvclient/rangecache/range_cache.go` line 1363 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/85503#-N8eOR_ODe8pT5zv3vnP:-N8eOR_ODe8pT5zv3vnQ:bqwsrzj) ([raw file](https://github.com/cockroachdb/cockroach/blob/9230f9aaef000ded75efa63258a183128ae51a75/pkg/kv/kvclient/rangecache/range_cache.go#L1363)):*
> ```Go
> 	}
> 
> 	newEntry = &CacheEntry{
> ```

I feel like this method would be easier to reason about if you initially cloned the receiver and then updated to lease and desc, instead of working backwards like you're doing here (assuming both will be updated unless proven otherwise). Was there are reason to write it like this?
___
*[`pkg/kv/kvclient/rangecache/range_cache.go` line 1387 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/85503#-N8eNieJ0voWUDM6afB6:-N8eNieJ0voWUDM6afB7:b28qegw) ([raw file](https://github.com/cockroachdb/cockroach/blob/9230f9aaef000ded75efa63258a183128ae51a75/pkg/kv/kvclient/rangecache/range_cache.go#L1387)):*
> l.Equal(e.Lease())

I know if was here before, but this is suspect. It's comparing every field in the lease, which I'm not sure we ever want to do on the client. Is it needed to determine that two speculative leases are identical? If not, are there cases where the lease sequence is insufficient to distinguish the equality of leases?
___
*[`pkg/kv/kvclient/rangecache/range_cache.go` line 1411 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/85503#-N8eOwfC2ZjBY0kvRBx6:-N8eOwfC2ZjBY0kvRBx7:b-wbz1ru) ([raw file](https://github.com/cockroachdb/cockroach/blob/9230f9aaef000ded75efa63258a183128ae51a75/pkg/kv/kvclient/rangecache/range_cache.go#L1411)):*
> ```Go
> 	// down seems like the right thing to do, do we expect this to happen in the
> 	// wild?
> 	_, ok := newEntry.Desc().GetReplicaDescriptorByID(newEntry.lease.Replica.ReplicaID)
> ```

nit: why `.Desc()` and not `.desc`?

**Review by arulajmani — COMMENTED** [review]
RFAL. 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/85503#-:-N9HxYQm8dlxKUdPcAbu:by76qvq)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @aayushshah15, @erikgrinaker, and @nvanbenschoten)

___
*[`-- commits` line 4 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/85503#-N8Zk4K0E63sp0m8ZlU8):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Reminder to address this TODO.
</blockquote></details>

Oops, done. 
___
*[`-- commits` line 36 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/85503#-N8dmtIH5k_kuUAk0_P_):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

TODO: is this still true?
</blockquote></details>

I _think_ the only scenario this is possible is the following scenario:

The cache had no lease information to begin with. It receives a NLHE from a replica that has both a stale range descriptor + lease information. In such a scenario, as written, we choose to insert the lease into the cache. It's possible the stale lease and cached range descriptor are incompatible. 

In my recent round of changes, I chose to structure things such that we don't compare range descriptor generations if the cached lease is empty. The idea being that a stale range descriptor doesn't necessarily imply stale lease information, so in the absence of anything better, let's just try it. How do you feel about this? 
___
*[`pkg/kv/kvclient/rangecache/range_cache.go` line 368 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/85503#-N8e5Jyc0DtrjWA1meSa:-N9HprAPAt6YmwEmzSo8:bh5l2u5) ([raw file](https://github.com/cockroachdb/cockroach/blob/9230f9aaef000ded75efa63258a183128ae51a75/pkg/kv/kvclient/rangecache/range_cache.go#L368)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

What about if the cache had a lease that was more recent than that in both the token and the one which was handed in? We will update the token in that case, right? Will we return true?
</blockquote></details>

We'll update the token but we'll return false. This behaviour is unchanged from what existed before. However, looking at why we use this information, I don't think the caller necessarily wants to make this distinction. 

Like we discussed offline, much of this can be simplified by changing the conditional at the caller to be `lh.IsSame(curReplica)` and we can clean up the amount of state that is tracked here and passed between callers. I've added a TODO to this effect, but I'll probably get to it in a quick followup patch if that's okay. 
___
*[`pkg/kv/kvclient/rangecache/range_cache.go` line 381 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/85503#-N8eLbKyCsSVtLmmAklQ:-N9CmyxkAQbbSG-QwCQR:b-o2u7ua) ([raw file](https://github.com/cockroachdb/cockroach/blob/9230f9aaef000ded75efa63258a183128ae51a75/pkg/kv/kvclient/rangecache/range_cache.go#L381)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Is the range descriptor guaranteed to be non-empty on every error path? Even in mixed version clusters?
</blockquote></details>

This wasn't the behaviour in the patch you reviewed, but given our discussion on slack to change NLHEs returned from uninitialized replicas to not include a speculative lease, I'll describe how things look with the patch I'm going to push out. The only time we can have a non-empty range descriptor here is if we're running a 22.(1,2) mixed version cluster and an uninitialized replica on the 22.1 node returns a NLHE. That should be okay though, as we'll fail the range descriptor compatibility check below and no-op given the range descriptor's generation is 0. Further up the stack, the client will move on and try the next replica on its transport. I've modified the `TestDistSenderNLHEFromUninitializedReplicaDoesNotCauseUnboundedBackoff` test to simulate both the mixed version and the 22.2 version scenarios. 
___
*[`pkg/kv/kvclient/rangecache/range_cache.go` line 387 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/85503#-N8e59sBBCEypVooG1yU:-N9CRVrr8twnoda95i3e:b-vlqfhw) ([raw file](https://github.com/cockroachdb/cockroach/blob/9230f9aaef000ded75efa63258a183128ae51a75/pkg/kv/kvclient/rangecache/range_cache.go#L387)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

You were planning to address this TODO in this PR, right?
</blockquote></details>

I did address this below but forgot to remove the TODO from here. Fixed. 
___
*[`pkg/kv/kvclient/rangecache/range_cache.go` line 391 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/85503#-N8eQXcpBK3jGP0gpgYm:-N9Hqky649_GM2knxvFn:bon7dsx) ([raw file](https://github.com/cockroachdb/cockroach/blob/9230f9aaef000ded75efa63258a183128ae51a75/pkg/kv/kvclient/rangecache/range_cache.go#L391)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

How should this method behave when this sync updates the leaseholder but the `maybeUpdate` below does not? Should it return `true`?
</blockquote></details>

This relates to your comment above. Given this resembles the old behaviour, and it isn't a correctness issue, how do you feel about keeping things as is for now and then completely getting rid of this return value in a foOne
___
*[`pkg/kv/kvclient/rangecache/range_cache.go` line 410 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/85503#-N8eLqVm-5oBOm8SoSCJ:-N9CTOEW4WgAZne53gZ_:bs7wumx) ([raw file](https://github.com/cockroachdb/cockroach/blob/9230f9aaef000ded75efa63258a183128ae51a75/pkg/kv/kvclient/rangecache/range_cache.go#L410)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

> !descsCompatible(rangeDesc, et.Desc())

We're checking this condition twice. Should we rewrite as:
```go
if !descsCompatible(rangeDesc, et.Desc()) {
    if rangeDesc.Generation < et.Desc().Generation {
        return false
    }
    ...
}
```
</blockquote></details>

Done. 
___
*[`pkg/kv/kvclient/rangecache/range_cache.go` line 426 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/85503#-N8ePyxTAwzJxKR02VEO:-N9HknFlA4n-Jp_RJ60B:bd6iaje) ([raw file](https://github.com/cockroachdb/cockroach/blob/9230f9aaef000ded75efa63258a183128ae51a75/pkg/kv/kvclient/rangecache/range_cache.go#L426)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Are we ok with returning false here if we updated the descriptor but not the leaseholder? Will the client handle that case correctly?
</blockquote></details>

We should be okay, as the client uses the updated range descriptor to skip any replicas that exist on the transport it constructed but are no longer part of the range descriptor. This happens regardless and is agnostic to whether this function had any effect or not. 
___
*[`pkg/kv/kvclient/rangecache/range_cache.go` line 1338 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/85503#-N8eMEcM2VkUXT_wXXfn:-N9HpX4XDj43y7QWoP3J:bs7wumx) ([raw file](https://github.com/cockroachdb/cockroach/blob/9230f9aaef000ded75efa63258a183128ae51a75/pkg/kv/kvclient/rangecache/range_cache.go#L1338)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Do you want to give this paragraph a similar "If updatedLease is returned true, ..." sentence?
</blockquote></details>

Done. 
___
*[`pkg/kv/kvclient/rangecache/range_cache.go` line 1340 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/85503#-N8eMfhzA8dNelUWLauL:-N9HpPWE0JT6MgakjVjz:b-lnioii) ([raw file](https://github.com/cockroachdb/cockroach/blob/9230f9aaef000ded75efa63258a183128ae51a75/pkg/kv/kvclient/rangecache/range_cache.go#L1340)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

I found the combination of an `updatedLease` and an `updated` return value to be confusing. It wasn't clear from the caller whether one implied the other or why I needed to care about both. It would be good to detail that.

It's minor, but I think switching the order of these return values would help. I say that because if `updated` is a broader condition than `updatedLease`, then most callers will first consult `updated` and then only care about `updatedLease` is `updated` is true.
</blockquote></details>

Changed the wording in this comment to be a bit more specific and switched the order of these return values. 
___
*[`pkg/kv/kvclient/rangecache/range_cache.go` line 1363 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/85503#-N8eOR_ODe8pT5zv3vnP:-N9DQ6EM5qJmPT2ADfLF:bv2l6dp) ([raw file](https://github.com/cockroachdb/cockroach/blob/9230f9aaef000ded75efa63258a183128ae51a75/pkg/kv/kvclient/rangecache/range_cache.go#L1363)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

I feel like this method would be easier to reason about if you initially cloned the receiver and then updated to lease and desc, instead of working backwards like you're doing here (assuming both will be updated unless proven otherwise). Was there are reason to write it like this?
</blockquote></details>

The reason I wrote it this way was to preserve the behavior tested here: 

https://github.com/cockroachdb/cockroach/blob/5845f4bc637bff4595d9ad9feb5fbaade875559a/pkg/kv/kvclient/rangecache/range_cache_test.go#L1797-L1804

This seems to be related to this comment:

```	// We handle the case of a lease with the sequence equal to the existing
	// entry, but otherwise different. This results in the new lease updating the
	// entry, because the existing lease might correspond to a proposed lease that
	// a replica returned speculatively while a lease acquisition was in progress.
```

However, I don't think this test case is valid, given speculative leases should have 0 sequence number. This also ties in to your comment about `l.Equal(e.Lease()` below. Does this check out?

I'm going to simplify this logic a bit and clone the receiver like you suggest. I'll also delete the test case above. 
___
*[`pkg/kv/kvclient/rangecache/range_cache.go` line 1387 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/85503#-N8eNieJ0voWUDM6afB6:-N9DQxOT1-gdXq2Epio0:bumc7mp) ([raw file](https://github.com/cockroachdb/cockroach/blob/9230f9aaef000ded75efa63258a183128ae51a75/pkg/kv/kvclient/rangecache/range_cache.go#L1387)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

> l.Equal(e.Lease())

I know if was here before, but this is suspect. It's comparing every field in the lease, which I'm not sure we ever want to do on the client. Is it needed to determine that two speculative leases are identical? If not, are there cases where the lease sequence is insufficient to distinguish the equality of leases?
</blockquote></details>

This ties into your comment above.

**Review by nvb — COMMENTED** [review]
> Reviewed 7 of 7 files at r6, 1 of 1 files at r7, 7 of 7 files at r8, 1 of 2 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/85503)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @aayushshah15, @arulajmani, and @nvanbenschoten)

___
*[`-- commits` line 36 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/85503#-N8dmtIH5k_kuUAk0_P_):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

I _think_ the only scenario this is possible is the following scenario:

The cache had no lease information to begin with. It receives a NLHE from a replica that has both a stale range descriptor + lease information. In such a scenario, as written, we choose to insert the lease into the cache. It's possible the stale lease and cached range descriptor are incompatible. 

In my recent round of changes, I chose to structure things such that we don't compare range descriptor generations if the cached lease is empty. The idea being that a stale range descriptor doesn't necessarily imply stale lease information, so in the absence of anything better, let's just try it. How do you feel about this? 
</blockquote></details>

I think this makes sense to me.
___
*[`pkg/kv/kvclient/rangecache/range_cache.go` line 368 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/85503#-N8e5Jyc0DtrjWA1meSa:-N9XCpuHE4Bmw_zSi2qO:baygj01) ([raw file](https://github.com/cockroachdb/cockroach/blob/9230f9aaef000ded75efa63258a183128ae51a75/pkg/kv/kvclient/rangecache/range_cache.go#L368)):*
> Like we discussed offline, much of this can be simplified by changing the conditional at the caller to be lh.IsSame(curReplica) and we can clean up the amount of state that is tracked here and passed between callers. I've added a TODO to this effect, but I'll probably get to it in a quick followup patch if that's okay.

This sounds great. Removing the return value entirely will be a nice simplification. A followup patch SGTM.
___
*[`pkg/kv/kvclient/rangecache/range_cache.go` line 1431 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/85503#-N9XEp1GBdKUMhgB7roR:-N9XEp1GBdKUMhgB7roS:b-akr1ra) ([raw file](https://github.com/cockroachdb/cockroach/blob/8d9b094caa3efd18151fe673700bbcafa48ef07e/pkg/kv/kvclient/rangecache/range_cache.go#L1431)):*
> ```Go
> 	// lease regardless of the associated range descriptor's generation.
> 	if (l.Sequence != 0 && e.lease.Sequence != 0 && l.Sequence > e.lease.Sequence) ||
> 		(l.Sequence == 0 && rangeDesc.Generation >= e.desc.Generation) ||
> ```

nit: I think this can be structured differently to avoid some redundancy and more clearly demonstrate the intent:

```
if ((l.Sequence != 0 && e.lease.Sequence != 0) && l.Sequence > e.lease.Sequence) ||
    ((l.Sequence == 0 || e.lease.Sequence == 0) && rangeDesc.Generation >= e.desc.Generation) ||
    e.lease.Empty() {
```
___
*[`pkg/kv/kvserver/store_send.go` line 196 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/85503#-N9XFpvO4XpL8ZRzzDyn:-N9XFpvO4XpL8ZRzzDyo:b-jcgd4v) ([raw file](https://github.com/cockroachdb/cockroach/blob/21262eb431a013fdd496b36793ecfd53db9ebf92/pkg/kv/kvserver/store_send.go#L196)):*
> ```Go
> 			// tries will be initialized and will have useful leaseholder information
> 			// for the client.
> 			return nil, nil, roachpb.NewError(&roachpb.NotLeaseHolderError{
> ```

I was hoping that this could eliminate the "speculative lease" concept entirely. That doesn't seem to be the case, as there are other places where we return speculative leases. Can we at least unify this with the speculative lease concept? That would mean either removing the LeaseHolder field and returning `Lease: roachpb.Lease{Replica: repl.creatingReplica}` here or eliminating cases where `NotLeaseHolderError.Lease` does not refer to a committed lease and using only the `LeaseHolder` field for speculative leases. Either one seems like a simplification.

Also, since there's more discussion to be had here, consider lifting this into its own PR so that it doesn't block this one.

EDIT: I now remember why we decided to remove this — because the client will ignore the lease due to the missing range desc. My question above still stands regarding what we want to do with these two fields in `NotLeaseHolderError`. This also begs the question of whether we can remove `Replica.creatingReplica`.

**Review by arulajmani — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/85503)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @aayushshah15 and @nvanbenschoten)

___
*[`pkg/kv/kvclient/rangecache/range_cache.go` line 368 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/85503#-N8e5Jyc0DtrjWA1meSa:-N9XmGvdBbTqf84rdmjm:b-qhjy86) ([raw file](https://github.com/cockroachdb/cockroach/blob/9230f9aaef000ded75efa63258a183128ae51a75/pkg/kv/kvclient/rangecache/range_cache.go#L368)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

> Like we discussed offline, much of this can be simplified by changing the conditional at the caller to be lh.IsSame(curReplica) and we can clean up the amount of state that is tracked here and passed between callers. I've added a TODO to this effect, but I'll probably get to it in a quick followup patch if that's okay.

This sounds great. Removing the return value entirely will be a nice simplification. A followup patch SGTM.
</blockquote></details>

Sounds good :+1: 
___
*[`pkg/kv/kvclient/rangecache/range_cache.go` line 1431 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/85503#-N9XEp1GBdKUMhgB7roR:-N9XasCS5dof3HQY3Rlg:bs7wumx) ([raw file](https://github.com/cockroachdb/cockroach/blob/8d9b094caa3efd18151fe673700bbcafa48ef07e/pkg/kv/kvclient/rangecache/range_cache.go#L1431)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

nit: I think this can be structured differently to avoid some redundancy and more clearly demonstrate the intent:

```
if ((l.Sequence != 0 && e.lease.Sequence != 0) && l.Sequence > e.lease.Sequence) ||
    ((l.Sequence == 0 || e.lease.Sequence == 0) && rangeDesc.Generation >= e.desc.Generation) ||
    e.lease.Empty() {
```
</blockquote></details>

Done. 
___
*[`pkg/kv/kvserver/store_send.go` line 196 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/85503#-N9XFpvO4XpL8ZRzzDyn:-N9XnFmr5uM-rOOnblBs:bge31fd) ([raw file](https://github.com/cockroachdb/cockroach/blob/21262eb431a013fdd496b36793ecfd53db9ebf92/pkg/kv/kvserver/store_send.go#L196)):*
> or eliminating cases where NotLeaseHolderError.Lease does not refer to a committed lease and using only the LeaseHolder field for speculative leases. 

Good point on unifying the speculative lease concept -- I like your suggestion about using just the `LeaseHolder` field for speculative leases. I'll open up a followup PR with this change.

For this patch I've removed `Replica.creatingReplica` as this guy was the only place making use of it.

**Review by nvb — APPROVED** [review]
:lgtm:

> Reviewed 6 of 7 files at r12, 4 of 4 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/85503#-:-N9YjRHu83rcZOg2xZom:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @aayushshah15)

**Comment by arulajmani** [comment]
TFTRs! 

bors r+
