### PR TITLE
Remove retry loop in local sender.

### LINKED ISSUE #679: Remove retry loop in LocalSender
LocalSender has a retry loop to handle the case where a client passes an incorrect RaftID or StoreID but the requested key can still be found on the local node (this typically happens if the range has just split). This is a premature optimization, and since it prevents the RangeKeyMismatchError from reaching the DistSender, the DistSender's cache will never get updated and it will continue to use the incorrect RaftID. We should remove the retry loop and let the DistSender handle all retrying.

The tests in kv/split_test.go currently rely on the retry loop in LocalSender; before we can remove the retries we will need to change those tests to use a DistSender.

Extracted from #657.

### PR DESCRIPTION
**Pull request by spencerkimball**
The retry loop was causing successes on range splits which in turn was
preventing the remote distributed sender from invalidating its range
addressing cache.

Fixes #679

### CODE REVIEW

File: kv/txn_coord_sender_test.go [hunk 1]
```diff
@@ -35,18 +36,50 @@ import (
...
+type retryableLocalSender struct {
+	*LocalSender
+}
+
+// Send implements the client.Sender interface.
+func (rls *retryableLocalSender) Send(call *client.Call) {
+	// Instant retry with max two attempts to handle the case of a
+	// range split, which is exposed here as a RangeKeyMismatchError.
+	// If we fail with two in a row, pass the error up to caller and
+	// let the remote client requery range metadata.
```
Comment (petermattis) [inline kv/txn_coord_sender_test.go]: Will `retryableLocalSener` ever be used with a remote client? Hope the answer is no and that this is only used by test code and that the comment was copy&pasted from `localSender` without be fixed up.

**Comment by petermattis** [comment]
LGTM

File: kv/local_sender.go [hunk 2]
```diff
@@ -97,72 +97,49 @@ func (ls *LocalSender) VisitStores(visitor func(s *storage.Store) error) error {
...
+			// If the node is in "CertainNodes", we need not worry about
+			// uncertain reads any more. Setting MaxTimestamp=Timestamp
+			// for the operation accomplishes that.
+			// See proto.Transaction.CertainNodes for details.
+			if header.Txn.CertainNodes.Contains(header.Replica.NodeID) {
+				// Make sure that when this retryable function returns,
+				// MaxTimestamp is restored. On retries, there is no
+				// guarantee that the request gets routed to the same node
+				// as the replica may have moved.
+				defer func(ts proto.Timestamp) {
```
Comment (bdarnell) [inline kv/local_sender.go]: This defer can be removed.

File: kv/local_sender.go [hunk 3]
```diff
@@ -97,72 +97,49 @@ func (ls *LocalSender) VisitStores(visitor func(s *storage.Store) error) error {
...
-	// let the remote client requery range metadata.
-	retryOpts := util.RetryOptions{
-		Tag:         fmt.Sprintf("routing %s locally", call.Method),
-		MaxAttempts: 2,
-	}
-	util.RetryWithBackoff(retryOpts, func() (util.RetryStatus, error) {
-		call.Reply.Header().Error = nil
-		var err error
-		var store *storage.Store
+	call.Reply.Header().Error = nil
```
Comment (bdarnell) [inline kv/local_sender.go]: This line is no longer necessary.

File: kv/txn_coord_sender_test.go [hunk 4]
```diff
@@ -35,18 +36,50 @@ import (
 	gogoproto "github.com/gogo/protobuf/proto"
 )
 
+// retryableLocalSender provides a retry option in the event of
+// range splits.
```
Comment (bdarnell) [inline kv/txn_coord_sender_test.go]: Expand this comment: "In real-world use, the DistSender is responsible for retrying in the event of range splits, but some tests in this package do not use DistSender and instead rely on local-only retries." Consider adding a TODO to replace retryableLocalSender with DistSender if you think that is feasible (but it may be more trouble than it's worth to hook up everything DistSender needs).

**Comment by bdarnell** [comment]
LGTM. The test failure looks like the one I fixed in #689.

File: kv/local_sender.go (hunk 3 above)
Comment (spencerkimball) [inline kv/local_sender.go]: Removed and added to the retryableLocalSender

File: kv/local_sender.go (hunk 2 above)
Comment (spencerkimball) [inline kv/local_sender.go]: Cleaned up this code.

File: kv/txn_coord_sender_test.go (hunk 4 above)
Comment (spencerkimball) [inline kv/txn_coord_sender_test.go]: I'm going to leave off the TODO because it's not going to be worth the effort. Using dist sender creates a circular dependency with the server package, which is why we have some test files in this directory declaring `package kv_test`.

File: kv/txn_coord_sender_test.go (hunk 1 above)
Comment (spencerkimball) [inline kv/txn_coord_sender_test.go]: I cleaned up the comment and rearranged things so that we now create a retryableLocalSender via a `newRetryableLocalSender(*LocalSender, *testing.T)` method which should eliminate confusion about this being used anywhere outside unittests. The testing object is used to `Fatalf()` in the event of more than two attempts to send.
