### PR TITLE
bulkio: Ensure correct descriptor used when restoring.

### LINKED ISSUE #55642: Restores in 20.1: Restoring tables into cluster with different privileges may fail
Re https://github.com/cockroachlabs/support/issues/627

Restores fail due to inability to transition from OFFLINE to ONLINE state after restore runs almost to completion.
The purpose of this (high priority) issue is to figure out:

* potential impact on 20.1 customers.
* why we're seeing RESTOREs fail more than once.  Is the transaction issue very likely to occur?  Why?
* whether or not a fix can be backported to 20.1.

I think it has been fixed by https://github.com/cockroachdb/cockroach/commit/3423bb900f43e1cf1e54cf3589e574a72f7e798a, but still need to confirm root cause and from there determine potential impact.

### PR DESCRIPTION
**Pull request by miretskiy**
Fixes #55642

Prior to this change, a copy of descriptors being restored could
become out of sync with the copy stored in the jobs table.

The divergence could occur when restoring into a cluster (or db) with
a different set of privileges than the privileges stored in the descriptors
when the backup was created.

In such a case, when we attempt to restore into a database with different
set of priveleges, we would override descriptor privileges with correct
permissions, and then commit the modified descriptors to KV (and system.jobs table).
Subsequently, if the restore process gets restarted, we would ignore
the privilege updates performed before and our in-memory descriptor would be
different from the descriptor stored in KV.  This would result in an
error when attempting to mark descriptor PUBLIC:
`validating table descriptor has not changed, expected:....`

This change ensures that if we resume restore execution, then we would use
the descriptors stored in the jobs details as opposed to the ones we compute.

Release Notes: Fix a bug which could result in a failed restore when restoring
into a database with a different set of privileges than the backup privileges.

Release Justifications: Bug fix: ensure we can restore even if restoring into
a database with different set of permissions.

### CODE REVIEW

File: pkg/ccl/backupccl/restore_test.go [hunk 1]
```diff
@@ -0,0 +1,90 @@
...
+
+	ctx := context.Background()
+	dir, dirCleanupFn := testutils.TempDir(t)
+	defer dirCleanupFn()
+	params := base.TestClusterArgs{}
+	params.ServerArgs.ExternalIODir = dir
+	tc := testcluster.StartTestCluster(t, 1, params)
+	defer tc.Stopper().Stop(ctx)
+
+	tc.Server(0).JobRegistry().(*jobs.Registry).TestingResumerCreationKnobs = map[jobspb.Type]func(raw jobs.Resumer) jobs.Resumer{
```
Comment (pbardea) [inline pkg/ccl/backupccl/restore_test.go:70]: Nice test!

Not for this PR, but I think it would be nice to have this wrapping resumer injected in the registry during `backupRestoreTestSetupWithParams` so that we can get this goodness across all of the existing tests.

@dt also mentioned the idea of having "breakpoints" or knobs set during interesting points throughout the execution. Perhaps we could randomly select one of the breakpoints to return this error every time to get varied coverage on resuming the job at different points throughout the lifecycle of the job.

**Review by pbardea — APPROVED** [review]
🎉 LGTM

**Review by dt — APPROVED** [review]
👏

File: pkg/ccl/backupccl/restore_test.go (hunk 1 above)
Comment (miretskiy) [reply pkg/ccl/backupccl/restore_test.go:70]: Thanks.  I do think we should lift this case to the master.   The only thing is: i had to put it under backupccl package, and not under backupccl_test package so that I can access resumer.  The injection approach was basically copied from the import test.

**Comment by miretskiy** [comment]
tftr

File: pkg/ccl/backupccl/restore_test.go (hunk 1 above)
Comment (pbardea) [reply pkg/ccl/backupccl/restore_test.go:68]: I did a refactor of the backup tests in 20.2 to move most of them from `backupccl_test` to `backupccl` (for exactly the same reason, so that I could put testing knobs on the resumer).
