### PR TITLE
roachtest: harmonize GCE and AWS machine types

### LINKED ISSUE #106570: roachtest: kv0/enc=false/nodes=1/size=64kb/conc=4096 failed
roachtest.kv0/enc=false/nodes=1/size=64kb/conc=4096 [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyAwsBazel/10858682?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyAwsBazel/10858682?buildTab=artifacts#/kv0/enc=false/nodes=1/size=64kb/conc=4096) on release-22.2 @ [0119b326fb4e58058cd51c2e660e77343b80bc08](https://github.com/cockroachdb/cockroach/commits/0119b326fb4e58058cd51c2e660e77343b80bc08):

```
test artifacts and logs in: /artifacts/kv0/enc=false/nodes=1/size=64kb/conc=4096/run_1
(cluster.go:2173).Run: output in run_061359.349731495_n2_workload-run-kv-tole: ./workload run kv --tolerate-errors --init --histograms=perf/stats.json --concurrency=4096 --splits=1000 --duration=30m0s --read-percent=0 --min-block-bytes=65536 --max-block-bytes=65536 {pgurl:1-1} returned: context canceled
(monitor.go:127).Wait: monitor failure: monitor command failure: unexpected node event: 1: dead (exit status 137)
```
<p>Parameters: <code>ROACHTEST_arch=amd64</code>
, <code>ROACHTEST_cloud=aws</code>
, <code>ROACHTEST_cpu=8</code>
, <code>ROACHTEST_encrypted=false</code>
, <code>ROACHTEST_ssd=0</code>
</p>
<details><summary>Help</summary>
<p>

See: [roachtest README](https://github.com/cockroachdb/cockroach/blob/master/pkg/cmd/roachtest/README.md)

See: [How To Investigate \(internal\)](https://cockroachlabs.atlassian.net/l/c/SSSBr8c7)

</p>
</details>
/cc @cockroachdb/test-eng
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*kv0/enc=false/nodes=1/size=64kb/conc=4096.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)
</sub>

Jira issue: CRDB-29620

### PR DESCRIPTION
**Pull request by srosenberg**
Previously, same (performance) roachtest executed in GCE and AWS
may have used a different memory (per CPU) multiplier and/or
cpu family, e.g., cascade lake vs ice lake. In the best case,
this resulted in different performance baselines on an otherwise
equivalent machine type. In the worst case, this resulted in OOMs
due to VMs in AWS having 2x less memory per CPU.

This change harmozines GCE and AWS machine types by making them
as isomorphic as possible, wrt memory, cpu family and price.
The following heuristics are used depending on specified `MemPerCPU`:
`Standard` yields 4GB/cpu, `High` yields 8GB/cpu,
`Auto` yields 4GB/cpu up to and including 16 vCPUs, then 2GB/cpu.
`Low` is supported _only_ in GCE.
Consequently, `n2-standard` maps to `m6i`, `n2-highmem` maps to `r6i`,
`n2-custom` maps to `c6i`, modulo local SSDs in which case `m6id` is
used, etc. Note, we also force `--gce-min-cpu-platform` to `Ice Lake`;
isomorphic AWS machine types are exclusively on `Ice Lake`.

Roachprod is extended to show cpu family and architecture on `List`.
Cost estimation now correctly deals with _custom_ machine types.
Finally, we change the default zone allocation in GCE from exclusively
`us-east1-b` to ~25% `us-central1-b` and ~75% `us-east1-b`. This is
inteded to balance the quotas for local SSDs until we eventually
switch to PD-SSDs.

Epic: none
Fixes: #106570

Release note: None

### CODE REVIEW

**Comment by srosenberg** [comment]
CI smoke test in progress: [SELECT_PROBABILITY=0.4](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/11905017?buildTab=log&logFilter=debug&focusLine=6&logView=linear)

File: pkg/cmd/roachtest/cluster_test.go [hunk 1]
```diff
@@ -168,6 +168,10 @@ func TestClusterMachineType(t *testing.T) {
 		{"n2-standard-32", 32},
 		{"n2-standard-64", 64},
 		{"n2-standard-96", 96},
+		// GCE machine types
```
Comment (erikgrinaker) [inline pkg/cmd/roachtest/cluster_test.go:171]: Stray comment? There is already a comment above for "GCE machine types".

**Review by erikgrinaker — COMMENTED** [review]
WIll the global Ice Lake bump affect roachperf benchmarks? If so, should we hold this until after the 23.2 branch cut and performance regression work, to give us a stable baseline for comparisons?

File: pkg/cmd/roachtest/cluster_test.go (hunk 1 above)
Comment (srosenberg) [reply pkg/cmd/roachtest/cluster_test.go:171]: Thanks, removing.

**Comment by srosenberg** [comment]
> WIll the global Ice Lake bump affect roachperf benchmarks? If so, should we hold this until after the 23.2 branch cut and performance regression work, to give us a stable baseline for comparisons?

It might have a small bump on the cpu-bound workloads using smaller vCPU density (those are most likely `cascade lake`, previous generation.) Do you really think it would be that disruptive to hold until after 23.2? I was just planning to add an annotation, since the other improvements seem to outweigh the small (cpu) gain.

**Comment by erikgrinaker** [comment]
If the effect would be small, them probably not. Otherwise, we'll have to directly compare the release roachperf graphs with each other to detect regressions, we can't simply look at the single graph for master -- but if we're ok with the extra manual work then that's fine too.

**Review by erikgrinaker — APPROVED** [review]

**Review by herkolategan — APPROVED** [review]
> Reviewed 13 of 13 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/111140)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @erikgrinaker, @renatolabs, @smg260, and @srosenberg)

___
*[`-- commits` line 4 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/111140#-NfBu3xaAWAZPTYX0lVB):*
silly nit: "some"
___
*[`-- commits` line 26 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/111140#-NfBvtF7B7WFYtKctYI7):*
silly nit: "intended"

**Comment by srosenberg** [comment]
> If the effect would be small, them probably not. Otherwise, we'll have to directly compare the release roachperf graphs with each other to detect regressions, we can't simply look at the single graph for master -- but if we're ok with the extra manual work then that's fine too.

Right. My guess the effect is small, possibly negligible. Otherwise, I'll revert the change and postpone it until after branch cut.

File: pkg/cmd/roachtest/spec/machine_type.go [hunk 2]
```diff
@@ -61,27 +100,45 @@ func AWSMachineType(cpus int, mem MemPerCPU, arch vm.CPUArch) (string, vm.CPUArc
...
+		case Auto:
+			family = "c6i"
+		case Standard:
+			family = "m6i"
+		case High:
+			family = "r6i"
+
+		}
+		if shouldSupportLocalSSD {
+			family = family + "d"
```
Comment (renatolabs) [inline pkg/cmd/roachtest/spec/machine_type.go:115]: Can we simplify this function by only having one check at the end for `if shouldSupportLocalSSH { family += "d"  }`?

File: pkg/roachprod/vm/gce/gcloud.go [hunk 3]
```diff
@@ -126,6 +127,8 @@ type jsonVM struct {
 		ProvisioningModel         string
 	}
 	MachineType string
+	// CPU platform corresponding to machine type; see https://cloud.google.com/compute/docs/cpu-platforms
+	CpuPlatform string
```
Comment (renatolabs) [inline pkg/roachprod/vm/gce/gcloud.go:131]: Nit: probably more idiomatic to call this `CPUPlaform`: https://github.com/golang/go/wiki/CodeReviewComments#initialisms (and also more consistent with `CPUArch` and `CPUFamily`).

File: pkg/roachprod/vm/vm.go [hunk 4]
```diff
@@ -41,13 +41,35 @@ const (
...
-	ArchFIPS  = CPUArch("fips")
+	ArchARM64   = CPUArch("arm64")
+	ArchAMD64   = CPUArch("amd64")
+	ArchFIPS    = CPUArch("fips")
+	ArchUnknown = CPUArch("unknown")
 )
 
 type CPUArch string
 
+// ParseArch parses a string into a CPUArch using a simple, non-exhaustive heuristic.
```
Comment (renatolabs) [inline pkg/roachprod/vm/vm.go:52]: Would be nice to include some examples of what kinds of inputs this is known to work well: e.g., GCE tools, binary detection tool, etc.

File: pkg/roachprod/vm/gce/gcloud.go [hunk 5]
```diff
@@ -958,7 +965,13 @@ func (p *Provider) Create(
 		if opts.GeoDistributed {
 			zones = defaultZones
 		} else {
-			zones = []string{defaultZones[0]}
+			// N.B. We default to the first two regions, namely us-east1 and us-central1. In order to balance the quotas,
+			// we place ~75% of the cluster in us-east1 and ~25% in us-central1.
+			if rand.Float64() < 0.75 {
+				zones = []string{defaultZones[0]}
+			} else {
+				zones = []string{defaultZones[1]}
```
Comment (renatolabs) [inline pkg/roachprod/vm/gce/gcloud.go:973]: This won't be great if we get unlucky and run a test that takes large backups and stores them in our backup testing buckets, which are only in us-east1 (not multiregion).

**Review by renatolabs — COMMENTED** [review]
Thanks for taking the time to make sure GCE and AWS are consistent!

**Review by srosenberg — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/111140)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @erikgrinaker, @herkolategan, @renatolabs, and @smg260)

___
*[`-- commits` line 4 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/111140#-NfBu3xaAWAZPTYX0lVB):*
<details><summary><i>Previously, herkolategan (Herko Lategan) wrote…</i></summary><blockquote>

silly nit: "some"
</blockquote></details>

It's actually inteded (sic) to be same (sic), but I'll rephrase :) Basically, one roachtest executed in both clouds would have different multipliers.
___
*[`-- commits` line 26 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/111140#-NfBvtF7B7WFYtKctYI7):*
<details><summary><i>Previously, herkolategan (Herko Lategan) wrote…</i></summary><blockquote>

silly nit: "intended"
</blockquote></details>

Fixing, thanks.
___
*[`pkg/cmd/roachtest/spec/machine_type.go` line 115 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/111140#gh-1337554569:-NfNCm4ZEylcMyie815e:ba2t5cm) ([raw file](https://github.com/cockroachdb/cockroach/blob/d315ea84abe832bee3b221a86bcd0cb376a6ab65/pkg/cmd/roachtest/spec/machine_type.go#L115)):*
<details><summary><i>Previously, renatolabs (Renato Costa) wrote…</i></summary><blockquote>

Can we simplify this function by only having one check at the end for `if shouldSupportLocalSSH { family += "d"  }`?
</blockquote></details>

Yep, good catch!
___
*[`pkg/roachprod/vm/vm.go` line 52 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/111140#gh-1337560535:-NfNCsPO17X8jNJZPIk_:bcyglie) ([raw file](https://github.com/cockroachdb/cockroach/blob/d315ea84abe832bee3b221a86bcd0cb376a6ab65/pkg/roachprod/vm/vm.go#L52)):*
<details><summary><i>Previously, renatolabs (Renato Costa) wrote…</i></summary><blockquote>

Would be nice to include some examples of what kinds of inputs this is known to work well: e.g., GCE tools, binary detection tool, etc.
</blockquote></details>

Yep, good idea! 
___
*[`pkg/roachprod/vm/gce/gcloud.go` line 131 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/111140#gh-1337558030:-NfNCwJb0nQUGVmLUwYx:brrddrm) ([raw file](https://github.com/cockroachdb/cockroach/blob/d315ea84abe832bee3b221a86bcd0cb376a6ab65/pkg/roachprod/vm/gce/gcloud.go#L131)):*
<details><summary><i>Previously, renatolabs (Renato Costa) wrote…</i></summary><blockquote>

Nit: probably more idiomatic to call this `CPUPlaform`: https://github.com/golang/go/wiki/CodeReviewComments#initialisms (and also more consistent with `CPUArch` and `CPUFamily`).
</blockquote></details>

I struggled with this one; `CPUPlatform` just hurts my eyes :) I'll comply with the more idiomatic convention.
___
*[`pkg/roachprod/vm/gce/gcloud.go` line 973 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/111140#gh-1337566692:-NfND5gHC5_QjoxR-VVL:b2uy879) ([raw file](https://github.com/cockroachdb/cockroach/blob/d315ea84abe832bee3b221a86bcd0cb376a6ab65/pkg/roachprod/vm/gce/gcloud.go#L973)):*
<details><summary><i>Previously, renatolabs (Renato Costa) wrote…</i></summary><blockquote>

This won't be great if we get unlucky and run a test that takes large backups and stores them in our backup testing buckets, which are only in us-east1 (not multiregion).
</blockquote></details>

Yep, I am taking this out; to be dealt with in https://github.com/cockroachdb/cockroach/issues/111371

File: pkg/cmd/roachtest/spec/machine_type.go [hunk 6]
```diff
@@ -61,27 +87,46 @@ func AWSMachineType(cpus int, mem MemPerCPU, arch vm.CPUArch) (string, vm.CPUArc
...
+			family = "r6i"
+
+		}
 		selectedArch = vm.ArchAMD64
 	}
-	// There is no c7g.24xlarge, fall back to c6id.24xlarge.
-	if family == "c7g" && size == "24xlarge" {
-		family = "c6id"
+	// There is no m7gd.24xlarge, fall back to (c|m|r)6id.24xlarge.
+	if family == "m7gd" && size == "24xlarge" {
```
Comment (renatolabs) [inline pkg/cmd/roachtest/spec/machine_type.go:104]: This should be `m7g` and `m6i` below.

Comment (srosenberg) [reply pkg/cmd/roachtest/spec/machine_type.go:104]: Good catch, I shouldn't have hurried!

File: pkg/cmd/roachtest/spec/machine_type.go [hunk 7]
```diff
@@ -16,26 +16,52 @@ import (
...
 
-	if mem == High {
-		family = "m6i" // 4 GB RAM per CPU
+	switch mem {
+	case Auto:
+		if cpus > 16 {
+			family = "c6i" // 2 GB RAM per CPU
+
+			if arch == vm.ArchFIPS {
+				selectedArch = vm.ArchFIPS
```
Comment (renatolabs) [inline pkg/cmd/roachtest/spec/machine_type.go:50]: It seems we're only setting `selectedArch` to `vm.ArchFIPS` if `mem == Auto`. Is that intentional?

**Review by renatolabs — APPROVED** [review]

File: pkg/cmd/roachtest/spec/machine_type.go (hunk 7 above)
Comment (srosenberg) [reply pkg/cmd/roachtest/spec/machine_type.go:50]: Nope, copy/paste error. I've gone through both funcs again and simplified a bit more. I'll do another CI run before merging.

File: pkg/cmd/roachtest/spec/machine_type.go [hunk 8]
```diff
@@ -16,26 +16,51 @@ import (
...
-	if mem == High {
-		family = "m6i" // 4 GB RAM per CPU
+	switch mem {
+	case Auto:
+		if cpus > 16 {
+			family = "c6i" // 2 GB RAM per CPU
+
+			if arch == vm.ArchARM64 {
+				family = "c7g" // 2 GB RAM per CPU (graviton3)
+				selectedArch = vm.ArchARM64
```
Comment (renatolabs) [inline pkg/cmd/roachtest/spec/machine_type.go:52]: Nit: technically not needed, since this is already taken care of in the code above the switch.

**Comment by srosenberg** [comment]
Final smoke test: [SELECT_PROBABILITY=0.3](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/11969878?buildTab=log&logView=linear&focusLine=2236)

File: pkg/cmd/roachtest/spec/machine_type.go (hunk 7 above)
Comment (srosenberg) [reply pkg/cmd/roachtest/spec/machine_type.go]: Agreed, adding unit tests.

Comment (srosenberg) [reply pkg/cmd/roachtest/spec/machine_type.go]: Unit tests ended being more code than the actual implementation :)

**Review by renatolabs — APPROVED** [review]
LGTM, thanks for adding the tests!

**Comment by srosenberg** [comment]
TFTR! 

above roachtest failures are unrelated, so I am merging. I'll monitor roachperf over the weekend. If everything looks good, I'll add an annotation and get the backports merged. Otherwise, we'll revert and wait for a more opportune time window.

bors r=erikgrinaker,herkolategan,renatolabs

**Comment by srosenberg** [comment]
Hmm, let's try this again. Bors are you there?

bors r=erikgrinaker,herkolategan,renatolabs

**Comment by RaduBerinde** [comment]
I'm maintaining a list of recent changes that need to be backported, I'll add this to my list.

**Comment by srosenberg** [comment]
> above roachtest failures are unrelated, so I am merging. I'll monitor roachperf over the weekend. If everything looks good, I'll add an annotation and get the backports merged. Otherwise, we'll revert and wait for a more opportune time window.

Pretty high jump on `kv95` (most of `ycsb/[A-F]` and even `tpccbench`). On `kv95`, `n2-highcpu-32` was already over 90% cpu-utilized (see plots below). The run after the change is using `n2-custom-32` with 64GB; so that's 2x RAM, plus `ice lake` vs. `cascade lake`. The latter is only hypothesized since we didn't use to record cpu platform, but it's highly likely GCE would have provisioned `cascade lake` without `--min-cpu-platform`. I guess we should revert and circle back after the 23.2 branch is cut?


roachperf_diff

cpu_before_change

cpu_after_change

n2_highcpu_32

n2_custom_32_64gb

**Comment by RaduBerinde** [comment]
If you decide to revert, is it possible to keep most of the code changes while making the machine types what they used to be? Perhaps even controlled by a flag?

**Comment by erikgrinaker** [comment]
>I guess we should revert and circle back after the 23.2 branch is cut?

That'd make it easier to analyze performance changes for 23.2, at least. While we can often simply compare the release branches against each other (assuming they all receive this machine type bump), that isn't true for benchmarks that were added during the 23.2 cycle specifically to gauge the effect of performance work (e.g. the `cdc/workload` benchmarks).

**Comment by renatolabs** [comment]
> circle back after the 23.2 branch is cut?

We should revisit this. It still causes the occasional test failure (e.g., #113279).

**Comment by srosenberg** [comment]
> > circle back after the 23.2 branch is cut?
> 
> We should revisit this. It still causes the occasional test failure (e.g., #113279).

Yep, I'll prepare a new PR. We can wait until `23.2.1` since it appears fairly imminent.
