### PR TITLE
kvserver: skip `TestAdminScatterWithDrainingNodes` test in DRPC mode

### LINKED ISSUE #156372: kv/kvserver: TestAdminScatterWithDrainingNodes failed [drpc hanging BatchStream send]
kv/kvserver.TestAdminScatterWithDrainingNodes [failed](https://mesolite.cluster.engflow.com/invocations/default/0269317b-5783-4dd1-9e85-a9cae0ec2c22?testReportRun=3&testReportShard=42&testReportAttempt=1#targets-Ly9wa2cva3Yva3ZzZXJ2ZXI6a3ZzZXJ2ZXJfdGVzdA==) on release-25.4.0-rc @ [4f4179243a351bc48c00dd9243dc56b8af98e210](https://github.com/cockroachdb/cockroach/commits/4f4179243a351bc48c00dd9243dc56b8af98e210):

```

goroutine 60028 [select, 74 minutes]:
storj.io/drpc/drpcmanager.(*Manager).manageStream(0xc0152d6960, {0xdac7538, 0xc0130373b0}, 0xc007ce4f08)
	external/io_storj_drpc/drpcmanager/manager.go:334 +0x14e
storj.io/drpc/drpcmanager.(*Manager).manageStreams(0xc0152d6960)
	external/io_storj_drpc/drpcmanager/manager.go:323 +0xd8
created by storj.io/drpc/drpcmanager.NewWithOptions in goroutine 60006
	external/io_storj_drpc/drpcmanager/manager.go:123 +0x946

goroutine 61035 [IO wait]:
internal/poll.runtime_pollWait(0x7f352e7cd5b8, 0x72)
	GOROOT/src/runtime/netpoll.go:351 +0x85
internal/poll.(*pollDesc).wait(0xc012403420, 0x72, 0x0)
	GOROOT/src/internal/poll/fd_poll_runtime.go:84 +0xb1
internal/poll.(*pollDesc).waitRead(...)
	GOROOT/src/internal/poll/fd_poll_runtime.go:89
internal/poll.(*FD).Read(0xc012403400, {0xc00c675400, 0xc00, 0xc00})
	GOROOT/src/internal/poll/fd_unix.go:165 +0x466
net.(*netFD).Read(0xc012403400, {0xc00c675400, 0xc00, 0xc00})
	GOROOT/src/net/fd_posix.go:55 +0x4b
net.(*conn).Read(0xc00560d8d8, {0xc00c675400, 0xc00, 0xc00})
	GOROOT/src/net/net.go:189 +0xad
crypto/tls.(*atLeastReader).Read(0xc001b47980, {0xc00c675400, 0xc00, 0xc00})
	GOROOT/src/crypto/tls/conn.go:809 +0x89
bytes.(*Buffer).ReadFrom(0xc00d252d38, {0xda6de00, 0xc001b47980})
	GOROOT/src/bytes/buffer.go:211 +0x113
crypto/tls.(*Conn).readFromUntil(0xc00d252a88, {0x7f352d7e4bd0, 0xc012306240}, 0x5)
	GOROOT/src/crypto/tls/conn.go:831 +0x1da
crypto/tls.(*Conn).readRecordOrCCS(0xc00d252a88, 0x0)
	GOROOT/src/crypto/tls/conn.go:629 +0x365
crypto/tls.(*Conn).readRecord(...)
	GOROOT/src/crypto/tls/conn.go:591
crypto/tls.(*Conn).Read(0xc00d252a88, {0xc015eae000, 0x1000, 0xc015eae004?})
	GOROOT/src/crypto/tls/conn.go:1385 +0x2dd
storj.io/drpc/drpcwire.(*Reader).read(0xc0042c8770, {0xc015eae000, 0x1000, 0x1000})
	external/io_storj_drpc/drpcwire/reader.go:68 +0xaa
storj.io/drpc/drpcwire.(*Reader).ReadPacketUsing(0xc0042c8770, {0xc00ee34300, 0x0?, 0x20})
	external/io_storj_drpc/drpcwire/reader.go:113 +0x8ab
storj.io/drpc/drpcmanager.(*Manager).manageReader(0xc0075e0d20)
	external/io_storj_drpc/drpcmanager/manager.go:230 +0x199
created by storj.io/drpc/drpcmanager.NewWithOptions in goroutine 60467
	external/io_storj_drpc/drpcmanager/manager.go:122 +0x8dd

goroutine 57220 [select, 74 minutes]:
github.com/cockroachdb/cockroach/pkg/sql.(*DistSQLPlanner).initCancelingWorkers.func1({0xdac7bd8, 0xc010c04c80})
	pkg/sql/distsql_running.go:254 +0x145
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunAsyncTaskEx.func1({0xdac7bd8, 0xc010c04c80})
	pkg/util/stop/stopper.go:440 +0x116
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunAsyncTaskEx in goroutine 56818
	pkg/util/stop/stopper.go:438 +0x24f
```

Parameters:
 - <code>attempt=1</code>
 - <code>race=true</code>
 - <code>run=3</code>
 - <code>shard=42</code>
<details><summary>Help</summary>
<p>

See also: [How To Investigate a Go Test Failure \(internal\)](https://cockroachlabs.atlassian.net/l/c/HgfXfJgM)
</p>
</details>
<details><summary>Same failure on other branches</summary>
<p>

- #154316 kv/kvserver: TestAdminScatterWithDrainingNodes failed [C-bug C-test-failure O-robot P-2 T-db-server X-duplicate branch-release-25.4]
- #154312 kv/kvserver: TestAdminScatterWithDrainingNodes failed [C-bug C-test-failure O-robot P-2 T-db-server branch-master]
</p>
</details>
/cc @cockroachdb/kv-triage
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*TestAdminScatterWithDrainingNodes.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/bazci/githubpost/issues)

</sub>

Jira issue: CRDB-55974

### PR DESCRIPTION
**Pull request by cthumuluru-crdb**
`TestAdminScatterWithDrainingNodes` is failing at random when DRPC is enabled. The issue is specific to DRPC and the failure is reproducible once every 25 runs. The issue is not reproducible with cluster setting `SET CLUSTER SETTING sql.stats.flush.enabled=false` set to false to turn off stats flush.

Re-enable the test once the underlying issue is resolved.

Fixes: #156372
Epic: None
Release note: None

### CODE REVIEW

**Review by shubhamdhama — APPROVED** [review]

**Review by suj-krishnan — APPROVED** [review]
LGTM!

File: pkg/kv/kvserver/scatter_test.go [hunk 1]
```diff
@@ -45,6 +45,11 @@ func TestAdminScatterWithDrainingNodes(t *testing.T) {
 	const drainingNodeID = drainingServerIdx + 1
 	tc := testcluster.StartTestCluster(
 		t, 2, base.TestClusterArgs{
+			ServerArgs: base.TestServerArgs{
+				// TODO(server): test is timing out when DRPC is enabled.
+				// Investigate and re-enable once the issue is resolved.
```
Comment (stevendanna) [inline pkg/kv/kvserver/scatter_test.go:50]: Do we have a tracking issue for this?

Comment (Nukitt) [reply pkg/kv/kvserver/scatter_test.go:50]: [this epic](https://cockroachlabs.atlassian.net/browse/CRDB-55382) is tracking 2 dups of it @cthumuluru-crdb

**Review by Nukitt — APPROVED** [review]
:lgtm:

> @Nukitt reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/158262#-:-OepyZHb1JIl3fwOppIk:bnfp4nl)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @cthumuluru-crdb)

File: pkg/kv/kvserver/scatter_test.go (hunk 1 above)
Comment (cthumuluru-crdb) [reply pkg/kv/kvserver/scatter_test.go:50]: > Do we have a tracking issue for this?

We have a EPIC for tracking on failing tests. That doesn't include tests that are disabled due to feature parity but they do include failures like these. I'll create a ticket, add it to the queue to re-enable it.

Comment (cthumuluru-crdb) [reply pkg/kv/kvserver/scatter_test.go:50]: https://github.com/cockroachdb/cockroach/issues/158270 - ticket to track the failure and re-enable it for DRPC.
