### PR TITLE
roachtest: add withRetries for sql-stats and db-console/endpoints tests

### LINKED ISSUE #147878: roachtest: db-console/endpoints failed
roachtest.db-console/endpoints [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyAwsBazel/19868966?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyAwsBazel/19868966?buildTab=artifacts#/db-console/endpoints) on master @ [826ee929e41e2d1a1634a18348a8495c5ec5218d](https://github.com/cockroachdb/cockroach/commits/826ee929e41e2d1a1634a18348a8495c5ec5218d):

```
(db_console_endpoints.go:101).runDBConsole: failed testing endpoint /_status/metrics/{node_id} with own node ID: failed to GET https://18.227.48.132:26258/_status/metrics/3: Get "https://18.227.48.132:26258/_status/metrics/3": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
test artifacts and logs in: /artifacts/db-console/endpoints/cpu_arch=arm64/run_1
```

Parameters:
 - <code>arch=arm64</code>
 - <code>cloud=aws</code>
 - <code>coverageBuild=false</code>
 - <code>cpu=4</code>
 - <code>encrypted=false</code>
 - <code>fs=ext4</code>
 - <code>localSSD=true</code>
 - <code>metamorphicBufferedSender=true</code>
 - <code>runtimeAssertionsBuild=false</code>
 - <code>ssd=0</code>
<details><summary>Help</summary>
<p>

See: [roachtest README](https://github.com/cockroachdb/cockroach/blob/master/pkg/cmd/roachtest/README.md)

See: [How To Investigate \(internal\)](https://cockroachlabs.atlassian.net/l/c/SSSBr8c7)

_Grafana is not yet available for aws clusters_</p>
</details>
/cc @cockroachdb/obs-prs
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*db-console/endpoints.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/bazci/githubpost/issues)

</sub>

### PR DESCRIPTION
**Pull request by alyshanjahani-crl**
This commit adds a helper function withRetries and modifies db-console/endpoints to run with retries.

It also modifies sql-stats/mixed-version to use withRetries.

Fixes: #147878, #146699

Release note: None

### CODE REVIEW

**Comment by alyshanjahani-crl** [comment]
@dhartunian added retries to sql-stats roach test in https://github.com/cockroachdb/cockroach/pull/147379 (to resolve #146699 )

That PR didn't merge, instead of waiting for bors to merge it and refactoring, i just included both changes here. We can merge that separately and i can rebase though.

File: pkg/cmd/roachtest/tests/db_console_endpoints.go [hunk 1]
```diff
@@ -181,53 +181,54 @@ func testEndpoint(
...
+
+// withRetries runs the given function f with the provided retry options.
+// If f returns nil, the retry loop breaks and nil is returned.
+// If f returns an error and retries are exhausted, the last error is returned.
+func withRetries(ctx context.Context, opts retry.Options, f func() error) error {
+	var lastErr error
+	r := retry.StartWithCtx(ctx, opts)
+	for r.Next() {
+		if err := f(); err != nil {
+			lastErr = err
```
Comment (kyle-a-wong) [inline pkg/cmd/roachtest/tests/db_console_endpoints.go]: It might be worth doing something like `lastErr = errors.join(lastErr, err)` or something to keep track of all the errors. What do you think?

Comment (alyshanjahani-crl) [reply pkg/cmd/roachtest/tests/db_console_endpoints.go]: like it. Done.

**Review by kyle-a-wong — APPROVED** [review]
