### PR TITLE
ui: fix word-wrapping and tooltip spacing on jobs page

### LINKED ISSUE #35604: ui: Jobs tooltip missing spaces
Noticed by @timveil:
image

Happening on master `v19.1.0-beta.20190304`. We should add spaces after the links.

### PR DESCRIPTION
**Pull request by celiala**
- Fixed spacing for tooltip copy
- Fixed styling bug that was introduced in #35651: Job description
  previously truncated long job descriptions in collapsed view.

Tooltip copy - before:

jobs before

Tooltip copy - after:

fix tooltip-spacing

Job description - before:

broken text-wrapping

Job description - after:

fix text-overflow

Release note: None

Fixes: #35604

### CODE REVIEW

File: pkg/ui/src/views/jobs/index.tsx [hunk 1]
```diff
@@ -200,7 +200,7 @@ const jobsTableColumns: ColumnDescriptor<Job>[] = [
       // If a [SQL] job.statement exists, it means that job.description
       // is a human-readable message. Otherwise job.description is a SQL
       // statement.
-      const additionalStyle = (job.statement ? "" : "--sql");
+      const additionalStyle = (job.statement ? "" : " sql");
```
Comment (RaduBerinde) [inline pkg/ui/src/views/jobs/index.tsx]: I know very little CSS so sorry if it's a stupid question but shouldn't this be `.sql` ? Can you verify the font is still non-monospace for jobs with description?

Comment (celiala) [reply pkg/ui/src/views/jobs/index.tsx]: Doh :/ - thank you for asking this! Just pushed up a fix - RFAL, thank you!

> shouldn't this be `.sql` ?

It doesn't have to be `.sql` on the HTML side: the `.` specifies a className (`.className`), vs an id (`#idName`) -- but you were right to note that the font wasn't monospace for SQL statements! :)

> Can you verify the font is still non-monospace for jobs with description?

Double-checked that font styles are as expected for both SQL and human-readable descriptions:

Human-readable (normal font):


SQL (monospace font):

**Comment by RaduBerinde** [comment]
LGTM, thanks!

**Review by vilterp — APPROVED** [review]
Nice fix!

**Comment by celiala** [comment]
TFTRs!

bors r+
