### PR TITLE
workload/schemachange: enable create index / unique constraint

### LINKED ISSUE #127280: workload/schemachange: create inverted index on correct types, fix virtualComputedStored logic
```
 "ops": [
  "BEGIN",
  {
   "sql": "CREATE INVERTED INDEX IF NOT EXISTS index_w1_13_w1_43 ON public.table_w1_13 (\"Col13_w1_23\" ASC)"
  }
 ],
 "expectedExecErrors": "",
 "expectedCommitErrors": "",
 "message": "***UNEXPECTED ERROR; Received an unexpected execution error.: ERROR: data type text has no default operator class for access method \"gin\" (SQLSTATE 42704)",
```

Here's the table; we can see our column `\"Col13_w1_23\" STRING NOT NULL AS (lower(CAST(col13_w1_20 AS STRING))) STORED`:
``` 
"ops": [
  "BEGIN",
  {
   "sql": "CREATE TABLE public.table_w1_13 (\"col 13_w1_14\" FLOAT8, col13_w1_15 BIT(14) NOT NULL, col13_w1_16 STRING NOT NULL, col13_w1_17 INT2 NOT NULL, \"col1.3_w1_18\" STRING COLLATE de_DE, \"\\\\xfacoL1 3_w1_19\" FLOAT8 NOT NULL, col13_w1_20 VECTOR NOT NULL, \"co!l13_w1_21\" INTERVAL NOT NULL, \"col1 %p3_w1_22\" FLOAT8 NOT NULL AS (abs(\"\\\\xfacoL1 3_w1_19\")) STORED, \"Col13_w1_23\" STRING NOT NULL AS (lower(CAST(col13_w1_20 AS STRING))) STORED, INDEX (\"col1.3_w1_18\", col13_w1_17 ASC, abs(\"col 13_w1_14\") ASC), FAMILY (\"col1 %p3_w1_22\", \"col 13_w1_14\"), FAMILY (\"Col13_w1_23\", col13_w1_15, \"\\\\xfacoL1 3_w1_19\", col13_w1_16), FAMILY (\"col1.3_w1_18\", col13_w1_20), FAMILY (col13_w1_17), FAMILY (\"co!l13_w1_21\"))",
   "potentialExecErr": "0A000,42601"
  },
  "COMMIT"
 ],
```

Is there something funky with `nonIndexableType`? `ColumnTypeIsInvertedIndexable` seems to purposefully allow the string type

Jira issue: CRDB-40352

Epic CRDB-19168

### PR DESCRIPTION
**Pull request by rafiss**
This fixes the workload to detect more cases where indexes are not allowed to be created. It also adjusts the error code in one edge case so that the code is consistent for duplicate indexes.

The name formatting is adjusted in a few places, which also lets us enable ADD UNIQUE CONSTRAINT.

fixes https://github.com/cockroachdb/cockroach/issues/127280
Release note: None

### CODE REVIEW

File: pkg/workload/schemachange/error_screening.go [hunk 1]
```diff
@@ -263,7 +263,10 @@ SELECT array_agg(column_name)
 	}
 
 	for _, primaryColumn := range primaryColumns {
-		if primaryColumn == columnName {
+		// primaryColumn will be double-quoted only if it had any special
+		// characters, so compare against both the quoted	and the unquoted
+		// name.
```
Comment (annrpom) [inline pkg/workload/schemachange/error_screening.go:268]: nice catch :o

File: pkg/workload/schemachange/operation_generator.go [hunk 2]
```diff
@@ -983,10 +988,9 @@ func (og *operationGenerator) createIndex(ctx context.Context, tx pgx.Tx) (*opSt
 	// Define columns on which to create an index. Check for types which cannot be indexed.
 	duplicateRegionColumn := false
 	nonIndexableType := false
+	lastColInvertexIndexIsDescending := false
```
Comment (annrpom) [inline pkg/workload/schemachange/operation_generator.go:991]: nit: typo -- `lastColInvertedIndexIsDescending`

File: pkg/workload/schemachange/operation_generator.go [hunk 3]
```diff
@@ -1002,10 +1006,31 @@ func (og *operationGenerator) createIndex(ctx context.Context, tx pgx.Tx) (*opSt
...
+			if i == len(def.Columns)-1 {
+				// The last column cannot be descending or be present in the primary
+				// index.
+				if def.Columns[i].Direction == tree.Descending {
+					lastColInvertexIndexIsDescending = true
+				}
+				if colUsedInPrimaryIdx {
+					pkColUsedInInvertedIndex = true
+				}
+			}
```
Comment (annrpom) [inline pkg/workload/schemachange/operation_generator.go:1032]: What do you think about doing something like:
```
colUsedInPrimaryIdx, err := og.colIsPrimaryKey(ctx, tx, tableName, columnNames[i].name)
if err != nil {
   return nil, err
}
if i == len(def.Columns)-1 {
   if columnNames[i].typ.Family() == types.StringFamily {
      def.Columns[i].OpClass = "gin_trgm_ops" 
   }
	 // The last column cannot be descending or be present in the primary
	 // index.
   if def.Columns[i].Direction == tree.Descending {
	  lastColInvertexIndexIsDescending = true
   }
   if colUsedInPrimaryIdx {
	  pkColUsedInInvertedIndex = true
   }
}
```

**Review by spilchen — COMMENTED** [review]
Seems good to me. I just had one question.

> Reviewed 3 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/128245#-:-O3YpaNy0-EdrthedViW:bt1llxw)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @annrpom, @herkolategan, @rafiss, and @srosenberg)

___
*[`pkg/sql/alter_table.go` line 1743 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/128245#-O3YoB2N-F3LOlaZ-dLh:-O3YoB2N-F3LOlaZ-dLi:b-dx1bc6) ([raw file](https://github.com/cockroachdb/cockroach/blob/2da6aba0a13c528f5d8653cbfb0bb24cdd1a4958/pkg/sql/alter_table.go#L1743)):*
> ```Go
> 		}
> 		if idx.Dropped() {
> 			return false, pgerror.Newf(pgcode.DuplicateRelation, "constraint with name %q already exists and is being dropped, try again later", name)
> ```

Isn't relation just another term for a table. But we are dealing with a constraint here. I kind of think the old sqlcode was better. I'm curious why this change was needed?

**Review by annrpom — APPROVED** [review]
nice! thank you for taking care of the old formatting fix on insertRow

**Review by rafiss — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/128245)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @annrpom, @herkolategan, @spilchen, and @srosenberg)

___
*[`pkg/sql/alter_table.go` line 1743 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/128245#-O3YoB2N-F3LOlaZ-dLh:-O3YqXXC5AR42DJYqCOU:b-nd0d9n) ([raw file](https://github.com/cockroachdb/cockroach/blob/2da6aba0a13c528f5d8653cbfb0bb24cdd1a4958/pkg/sql/alter_table.go#L1743)):*
<details><summary><i>Previously, spilchen wrote…</i></summary><blockquote>

Isn't relation just another term for a table. But we are dealing with a constraint here. I kind of think the old sqlcode was better. I'm curious why this change was needed?
</blockquote></details>

the term relation is also used for indexes (as well as views and sequences). in CRDB, unique constraints and unique indexes are identical.
___
*[`pkg/workload/schemachange/operation_generator.go` line 991 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/128245#gh-1704485179:-O3Yr0Bn58FovlzYZeOy:bb7f2mf) ([raw file](https://github.com/cockroachdb/cockroach/blob/2da6aba0a13c528f5d8653cbfb0bb24cdd1a4958/pkg/workload/schemachange/operation_generator.go#L991)):*
<details><summary><i>Previously, annrpom (annie pompa) wrote…</i></summary><blockquote>

nit: typo -- `lastColInvertedIndexIsDescending`
</blockquote></details>

done
___
*[`pkg/workload/schemachange/operation_generator.go` line 1032 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/128245#gh-1704493970:-O3Yr7TlDOwOsnpJnXRz:b-8r3wev) ([raw file](https://github.com/cockroachdb/cockroach/blob/2da6aba0a13c528f5d8653cbfb0bb24cdd1a4958/pkg/workload/schemachange/operation_generator.go#L1032)):*
<details><summary><i>Previously, annrpom (annie pompa) wrote…</i></summary><blockquote>

What do you think about doing something like:
```
colUsedInPrimaryIdx, err := og.colIsPrimaryKey(ctx, tx, tableName, columnNames[i].name)
if err != nil {
   return nil, err
}
if i == len(def.Columns)-1 {
   if columnNames[i].typ.Family() == types.StringFamily {
      def.Columns[i].OpClass = "gin_trgm_ops" 
   }
	 // The last column cannot be descending or be present in the primary
	 // index.
   if def.Columns[i].Direction == tree.Descending {
	  lastColInvertexIndexIsDescending = true
   }
   if colUsedInPrimaryIdx {
	  pkColUsedInInvertedIndex = true
   }
}
```
</blockquote></details>

ah, yes definitely makes sense

**Comment by rafiss** [comment]
tftr!

bors r+
