### PR TITLE
fix #1684

### LINKED ISSUE #1684: client/admin_test.go:Example_accounting is flaky
Run it in a loop using `go test -v -run Example_accounting`. After a handful of runs one of them will hang. Here are the logs from such a failed run:

```
I0714 19:51:18.959485   34565 storage/engine/rocksdb.go:99] opening in-memory rocksdb instance
I0714 19:51:18.979530   34565 storage/range_command.go:782] range 1: new leader lease replica 1:1 19:00:00.000 +1436917879.973s
I0714 19:51:18.981070   34565 storage/range.go:1073] gossiping accounting config from store 1, range 1
I0714 19:51:18.981158   34565 storage/range.go:1073] gossiping permissions config from store 1, range 1
I0714 19:51:18.981217   34565 storage/range.go:1073] gossiping user config from store 1, range 1
I0714 19:51:18.981276   34565 storage/range.go:1073] gossiping zones config from store 1, range 1
I0714 19:51:18.981519   34565 server/node.go:293] initialized store store=1:1 ([]=): {Capacity:499099238400 Available:352367554560 RangeCount:0 XXX_unrecognized:[]}
I0714 19:51:18.982865   34565 server/node.go:223] new node allocated ID 1
I0714 19:51:18.983014   34565 gossip/gossip.go:166] gossiping node descriptor node_id:1 address:<network:"tcp" address:"127.0.0.1:60763" > attrs:<>
I0714 19:51:18.983054   34565 server/node.go:383] connecting to gossip network to verify cluster ID...
I0714 19:51:18.983257   34565 storage/range.go:1006] gossiping cluster id cluster-1 from store 1, range 1
I0714 19:51:18.983319   34565 storage/range.go:1014] gossiping sentinel from store 1, range 1
I0714 19:51:18.983347   34565 storage/range.go:1018] gossiping first range from store 1, range 1
I0714 19:51:18.983471   34565 server/node.go:400] node connected via gossip and verified as part of cluster "cluster-1"
I0714 19:51:18.983539   34565 server/node.go:258] Started node with [[]=] engine(s) and attributes []
I0714 19:51:18.983592   34565 server/server.go:199] starting https server at 127.0.0.1:60763
I0714 19:51:18.983643   34565 server/testserver.go:44] Test server listening on https: 127.0.0.1:60763
I0714 19:51:19.023152   34565 rpc/client.go:122] client 127.0.0.1:60763 connected
I0714 19:51:19.024649   34565 storage/range.go:1073] gossiping accounting config from store 1, range 1
I0714 19:51:19.044883   34565 storage/range.go:1073] gossiping accounting config from store 1, range 1
I0714 19:51:19.045320   34565 storage/split_queue.go:90] splitting range=1 ["" - "\xff\xff") at keys ["db1" "db2"]
I0714 19:51:19.047107   34565 storage/range.go:1073] gossiping accounting config from store 1, range 1
I0714 19:51:19.047388   34565 storage/range_command.go:845] initiating a split of range=1 ["" - "\xff\xff") at key "db1"
I0714 19:51:19.048928   34565 storage/range.go:1073] gossiping accounting config from store 1, range 1
I0714 19:51:19.056339   34565 storage/range.go:1073] gossiping accounting config from store 1, range 1
I0714 19:52:18.983426   34565 storage/range.go:1006] gossiping cluster id cluster-1 from store 1, range 1
W0714 19:52:18.983506   34565 storage/store.go:586] error gossiping first range data: storage/range.go:989: node is stopping
W0714 19:52:18.983563   34565 storage/store.go:606] error gossiping configs: storage/range.go:989: node is stopping
```

Notice the 60 second gap in the logs. Using `make test` causes the test to timeout after 30 seconds.

### PR DESCRIPTION
**Pull request by tbg**
resolving intents is not necessary for a transaction to complete.
however, open intents which remain unresolved may prevent tasks
from completing if they are on meta records which preclude an
outstanding request from reaching the correct range, retrying
indefinitely.
This change refactors TxnCoordSender such that a new transaction
cannot be started when the system is draining, and moves the intent
cleanup into the teardown of the heartbeat goroutine, which is now
a task.

fixes #1684 since the issue there was precisely that: a split at
["db1", "db2"] was started, and the second split would never route
to the correct range unless the intents of the first were resolved
previously (which would sometimes not happen since the stopper had
already stopped accepting "new work").

### CODE REVIEW

File: kv/txn_coord_sender.go [hunk 1]
```diff
@@ -186,19 +193,23 @@ func (tm *txnMetadata) close(trace *tracer.Trace, txn *proto.Transaction, resolv
 			}
 			call.Reply = &proto.InternalResolveIntentResponse{}
 		}
-		// We don't care about the reply channel; these are best
-		// effort. We simply fire and forget, each in its own goroutine.
+		// These are best effort. We simply fire and forget, each in its own
```
Comment (tamird) [inline kv/txn_coord_sender.go]: not exactly fire and forget since it blocks

File: kv/txn_coord_sender.go [hunk 2]
```diff
@@ -186,19 +193,23 @@ func (tm *txnMetadata) close(trace *tracer.Trace, txn *proto.Transaction, resolv
...
+		go func() {
 			sender.Send(ctx, call)
+			wg.Done()
 			if call.Reply.Header().Error != nil {
 				log.Warningf("failed to cleanup %q intent: %s", call.Args.Header().Key, call.Reply.Header().GoError())
 			}
-		})
+		}()
 	}
+	defer trace.Epoch("waiting for intent resolution")()
```
Comment (tamird) [inline kv/txn_coord_sender.go]: shouldn't be deferred

File: kv/txn_coord_sender.go [hunk 3]
```diff
@@ -666,18 +691,19 @@ func (tc *TxnCoordSender) cleanupTxn(trace *tracer.Trace, txn proto.Transaction,
...
 // and collects its stats.
-func (tc *TxnCoordSender) unregisterTxnLocked(txnMeta *txnMetadata) {
-	id := string(txnMeta.txn.ID)
-	if _, ok := tc.txns[id]; !ok {
-		return
-	}
+func (tc *TxnCoordSender) unregisterTxn(id string) {
+	tc.Lock()
+	defer tc.Unlock()
+	txnMeta := tc.txns[id] // guaranteed to exist
```
Comment (tamird) [inline kv/txn_coord_sender.go]: can you add an assertion?

File: kv/txn_coord_sender.go [hunk 4]
```diff
@@ -691,102 +717,97 @@ func (tc *TxnCoordSender) unregisterTxnLocked(txnMeta *txnMetadata) {
...
-// extant transaction, stopping in the event the transaction is
-// aborted or committed or if the TxnCoordSender is closed.
+// heartbeat periodically sends an InternalHeartbeatTxn RPC to an extant
+// transaction, stopping in the event the transaction is aborted or committed
+// after attempting to resolve the intents. When done, unregisters the
+// transaction.
 func (tc *TxnCoordSender) heartbeat(id string) {
-	tc.stopper.RunWorker(func() {
+	var tickChan <-chan time.Time
+	{
```
Comment (tamird) [inline kv/txn_coord_sender.go]: this (and the below) seem excessive - is there a good reason for it?

File: kv/txn_coord_sender.go [hunk 5]
```diff
@@ -691,102 +717,97 @@ func (tc *TxnCoordSender) unregisterTxnLocked(txnMeta *txnMetadata) {
...
+			tc.wrapped.Send(ctx, call)
+			epochEnds()
+			// If the transaction is not in pending state, then we can stop
+			// the heartbeat. It's either aborted or committed, and we resolve
+			// write intents accordingly.
+			if reply.GoError() != nil {
+				log.Warningf("heartbeat to %s failed: %s", txn, reply.GoError())
+			} else if reply.Txn != nil && reply.Txn.Status != proto.PENDING {
+				tc.cleanupTxn(trace, *reply.Txn, nil) // signal closer
+				tickChan = nil                        // wait only for the closer, no more heartbeats
```
Comment (tamird) [inline kv/txn_coord_sender.go]: why not just block on closer here? seems like the select is only ever going to trigger on ticks until it transitions to this state, so you could just
```
for range ticker.C {
 ....
  if endCond {
    resolved := <-closer
    ....
    return
  }
}
```

File: kv/txn_coord_sender_test.go [hunk 6]
```diff
@@ -334,20 +355,23 @@ func getTxn(coord *TxnCoordSender, txn *proto.Transaction) (bool, *proto.Transac
...
+			return fmt.Errorf("error getting MVCC metadata: %s", err)
 		}
-		return !ok || meta.Txn == nil
-	}, 500*time.Millisecond); err != nil {
-		t.Errorf("expected intents to be cleaned up within 500ms")
-	}
+		if !ok || meta.Txn == nil {
+			return nil
+		}
+		return errors.New("expected intents to be cleaned up within 500ms")
```
Comment (tamird) [inline kv/txn_coord_sender_test.go]: `util.SucceedsWithin` already wraps this error and includes the allotted time

**Comment by tamird** [comment]
This should also include a revert for https://github.com/cockroachdb/cockroach/pull/1693

File: kv/txn_coord_sender_test.go (hunk 6 above)
Comment (tschottdorf) [inline kv/txn_coord_sender_test.go]: done.

Comment (tschottdorf) [inline kv/txn_coord_sender_test.go]: done.

File: kv/txn_coord_sender.go (hunk 5 above)
Comment (tschottdorf) [inline kv/txn_coord_sender.go]: no, the closer is closed on various callpaths ending up in `cleanupTxn`. This is just one of them.

File: kv/txn_coord_sender.go (hunk 4 above)
Comment (tschottdorf) [inline kv/txn_coord_sender.go]: yes, see other comment.

File: kv/txn_coord_sender.go (hunk 3 above)
Comment (tschottdorf) [inline kv/txn_coord_sender.go]: sure.

File: kv/txn_coord_sender.go (hunk 2 above)
Comment (tschottdorf) [inline kv/txn_coord_sender.go]: why not?

**Comment by tschottdorf** [comment]
added the revert.

File: kv/txn_coord_sender.go (hunk 1 above)
Comment (tschottdorf) [inline kv/txn_coord_sender.go]: changing the comment.

File: kv/txn_coord_sender.go (hunk 2 above)
Comment (tamird) [inline kv/txn_coord_sender.go]: well the wording implies that we are beginning to wait. not sure if there are timing implications here

Comment (bdarnell) [inline kv/txn_coord_sender.go]: Note the doubled parentheses: we begin to wait here, and we finish waiting when the function returns. It's subtle, but this is how trace.Epoch is meant to be used (it might be more obvious if Epoch() returned an object with an End() method instead of a function)

**Comment by bdarnell** [comment]
LGTM, although this is awfully subtle. It feels like a very convoluted dance to get the intent cleanup to happen in the course of an existing Task. 

Can we add an explicit test for it (besides the flaky example tests)?

File: kv/txn_coord_sender.go [hunk 7]
```diff
@@ -463,11 +472,24 @@ func (tc *TxnCoordSender) sendOne(ctx context.Context, call proto.Call) {
...
 					tc.txns[id] = txnMeta
-					tc.heartbeat(id)
+					if !tc.stopper.RunAsyncTask(func() {
+						tc.heartbeat(id)
+					}) {
+						// The system is already draining and we can't start the
+						// heartbeat. Since the heartbeat also resolves intents,
+						// and since intent resolution may be critical for
+						// another running task (which may need to see an intent
+						// on the meta adressing records in order to hit the
```
Comment (spencerkimball) [inline kv/txn_coord_sender.go]: s/adressing/addressing/

**Comment by spencerkimball** [comment]
This seems fine, but I wonder if you shouldn't take this opportunity to solve the same problem in another way, which also move us in the direction of letting the range which handles the EndTransaction resolve all of the intents itself, instead of having the txn coordinator do it as we've been doing in the past.

The idea would be that we'd pass in all of the intents with `EndTransactionRequest` along with a bool indicating whether the txn always communicated solely with the txn coordinator sending the request. After finishing the end transaction, the range would additionally launch a goroutine to resolve intents; if all intents are resolved, the associated txn record can also be deleted.

This is something on my TODO list and would remove the problem that you're working around with this PR. I'm not sure, but I suspect checking this PR in will make that one harder to write.

**Comment by tschottdorf** [comment]
@spencerkimball I think there are some subtle changes necessary to prevent something like this from happening even with the optimization you describe. Ok, you can probably somehow force transactions (at least the ones that verify system keyspace) to stick to one coordinator (by controlling the internal client), and that lets the Range resolve the intents synchronously unless you've talked to more than one. But in a Split you might've talked to more than one, and even if not, you could still end up splitting a range which holds metadata addressing so that the intents are also split with the end of the transaction. I'm fairly glad this is a regular occurance right now and allows us to straighten those things out before they turn into cluster-munching unicorns. When the status quo works reliably, I'm all for going into the optimizations.

I think this also ties into optimizing/batching up whole transactions in one single round trip, which we should be able to do almost always. Unfortunately the missing piece here is that `TxnCoordSender` needs to know the range descriptors. Once it does though, it can take a batch, split it up into sub-batches addressed to individual ranges, and fire them off. If the whole thing is a transaction and goes to one range, intent resolution is also immediately possible. Again, fun stuff, but I'll rather do that when I know everything we have now works reliably.

By the way, I don't think this PR will make tackling those more complicated. After all, everything is pretty much the same: where previously you just spawned goroutines, now you pass something through a channel and the recipient spawns goroutines. It's all the same, really.

**Comment by tschottdorf** [comment]
@bdarnell yes, it's a bit subtle. Luckily, in practice this isn't critical to production (when the stopper isn't draining). I've updated the test so that it now runs a transaction which finishes while the system is draining.

**Comment by tschottdorf** [comment]
Had a chat with @spencerkimball today. I'll work on passing the intents along with `EndTransaction` and resolving them in the range as much as possible. That'll hopefully lead to a lot of this functionality moving to the range, and should improve the bank example as well.
