### PR TITLE
kvstreamer: fix potential deadlock

### LINKED ISSUE #74782: ccl/serverccl/statusccl: TestTenantStatusAPI failed
ccl/serverccl/statusccl.TestTenantStatusAPI [failed](https://teamcity.cockroachdb.com/viewLog.html?buildId=4108577&tab=buildLog) with [artifacts](https://teamcity.cockroachdb.com/viewLog.html?buildId=4108577&tab=artifacts#/) on master @ [c3d71ac887844bef174abb6dab2a4e1ce9270ab7](https://github.com/cockroachdb/cockroach/commits/c3d71ac887844bef174abb6dab2a4e1ce9270ab7):

```
../../../sql/conn_executor.go:1761 sql.(*connExecutor).execCmd { ex.statsCollector.PhaseTimes().SetSessionPhaseTime(sessionphase.SessionQueryServiced, timeutil.Now()) }
../../../sql/conn_executor.go:1675 sql.(*connExecutor).run { var err error }
../../../sql/conn_executor.go:680 sql.(*Server).ServeConn { }() }
../../../sql/pgwire/conn.go:665 pgwire.(*conn).processCommandsAsync.func1 { reservedOwned = false // We're about to pass ownership away. }

goroutine 876957 lock 0xc0116b9540
../../../util/mon/bytes_usage.go:652 mon.(*BytesMonitor).reserveBytes { mm.mu.Lock() } <<<<<
../../../util/mon/bytes_usage.go:651 mon.(*BytesMonitor).reserveBytes { func (mm *BytesMonitor) reserveBytes(ctx context.Context, x int64) error { }
../../../util/mon/bytes_usage.go:618 mon.(*BoundAccount).Grow { minExtra := b.mon.roundSize(x) }
../../../sql/colmem/allocator.go:127 colmem.(*Allocator).NewMemBatchWithFixedCapacity { estimatedMemoryUsage := selVectorSize(capacity) + EstimateBatchSizeBytes(typs, capacity) }
../../../sql/colmem/allocator.go:177 colmem.(*Allocator).ResetMaybeReallocate { if oldBatch == nil { }
../../../sql/colmem/allocator.go:592 colmem.(*SetAccountingHelper).ResetMaybeReallocate { ) (newBatch coldata.Batch, reallocated bool) { }
../../../sql/colfetcher/cfetcher.go:347 colfetcher.(*cFetcher).resetBatch { } }
../../../sql/colfetcher/cfetcher.go:1065 colfetcher.(*cFetcher).shiftState { func (rf *cFetcher) shiftState() { }
../../../sql/colfetcher/index_join.go:229 colfetcher.(*ColIndexJoin).Next { batch, err := s.rf.NextBatch(s.Ctx) }
../../../sql/colexec/invariants_checker.go:94 colexec.(*invariantsChecker).Next { b := i.Input.Next() }
../../../sql/colexec/colexecutils/cancel_checker.go:58 colexecutils.(*CancelChecker).Next { c.CheckEveryCall() }
../../../sql/colexec/invariants_checker.go:94 colexec.(*invariantsChecker).Next { b := i.Input.Next() }
../../../sql/colflow/stats.go:100 colflow.(*batchInfoCollector).Next { bic.stopwatch.Stop() }
../../../sql/colflow/flow_coordinator.go:239 colflow.(*BatchFlowCoordinator).nextAdapter { func (f *BatchFlowCoordinator) nextAdapter() { }
../../../sql/colexecerror/error.go:91 colexecerror.CatchVectorizedRuntimeError { operation() }
../../../sql/colflow/flow_coordinator.go:283 colflow.(*BatchFlowCoordinator).Run { err := f.next() }
../../../sql/colflow/flow_coordinator.go:243 colflow.(*BatchFlowCoordinator).next { func (f *BatchFlowCoordinator) next() error { }
../../../sql/colflow/vectorized_flow.go:259 colflow.(*vectorizedFlow).Run { f.batchFlowCoordinator.Run(ctx) }
../../../sql/distsql_running.go:566 sql.(*DistSQLPlanner).Run { // PlanAndRun. We should refactor this and get rid off ignoreClose field. }
../../../sql/distsql_running.go:1400 sql.(*DistSQLPlanner).PlanAndRun { recv.expectedRowsRead = int64(physPlan.TotalEstimatedScannedRows) }
../../../sql/conn_executor_exec.go:1411 sql.(*connExecutor).execWithDistSQLEngine { // need to have access to the main query tree. }
../../../sql/conn_executor_exec.go:1109 sql.(*connExecutor).dispatchToExecutionEngine { // plan has not been closed earlier. }
../../../sql/conn_executor_exec.go:720 sql.(*connExecutor).execStmtInOpenState {  }
../../../sql/conn_executor_exec.go:134 sql.(*connExecutor).execStmt { } else { }
../../../sql/conn_executor.go:1751 sql.(*connExecutor).execCmd.func1 {  }
../../../sql/conn_executor.go:1761 sql.(*connExecutor).execCmd { ex.statsCollector.PhaseTimes().SetSessionPhaseTime(sessionphase.SessionQueryServiced, timeutil.Now()) }
../../../sql/conn_executor.go:1675 sql.(*connExecutor).run { var err error }
../../../sql/conn_executor.go:680 sql.(*Server).ServeConn { }() }
../../../sql/pgwire/conn.go:665 pgwire.(*conn).processCommandsAsync.func1 { reservedOwned = false // We're about to pass ownership away. }

goroutine 1098442 lock 0xc010c501e0
../../../kv/kvclient/kvstreamer/streamer.go:758 kvstreamer.(*workerCoordinator).issueRequestsForAsyncProcessing { w.s.budget.mu.Lock() } <<<<<
../../../kv/kvclient/kvstreamer/streamer.go:757 kvstreamer.(*workerCoordinator).issueRequestsForAsyncProcessing { }() }
../../../kv/kvclient/kvstreamer/streamer.go:713 kvstreamer.(*workerCoordinator).mainLoop { err := w.issueRequestsForAsyncProcessing(ctx, requestsToServe, avgResponseSize) }
../../../util/stop/stopper.go:488 stop.(*Stopper).RunAsyncTaskEx.func2 { f(ctx) }





ERROR: exit status 2

1 runs completed, 1 failures, over 13s
context canceled
```
<details><summary>Help</summary>
<p>

See also: [How To Investigate a Go Test Failure \(internal\)](https://cockroachlabs.atlassian.net/l/c/HgfXfJgM)
Parameters in this failure:

- TAGS=deadlock

- GOFLAGS=-parallel=4
</p>
</details>
/cc @cockroachdb/sql-observability
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*TestTenantStatusAPI.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)
</sub>

### LINKED ISSUE #74785: kv/kvclient/kvstreamer: TestStreamerBudgetErrorInEnqueue failed
kv/kvclient/kvstreamer.TestStreamerBudgetErrorInEnqueue [failed](https://teamcity.cockroachdb.com/viewLog.html?buildId=4109087&tab=buildLog) with [artifacts](https://teamcity.cockroachdb.com/viewLog.html?buildId=4109087&tab=artifacts#/) on master @ [c3d71ac887844bef174abb6dab2a4e1ce9270ab7](https://github.com/cockroachdb/cockroach/commits/c3d71ac887844bef174abb6dab2a4e1ce9270ab7):

```
=== RUN   TestStreamerBudgetErrorInEnqueue/single_key_exceeds_limit
POTENTIAL DEADLOCK: Inconsistent locking. saw this ordering in one goroutine:
happened before
streamer.go:393 kvstreamer.(*Streamer).Enqueue { s.mu.Lock() } <<<<<
streamer.go:392 kvstreamer.(*Streamer).Enqueue { // acquisitions once pipelining is implemented. }
streamer_test.go:244 kvstreamer.TestStreamerBudgetErrorInEnqueue.func3 { reqs[0] = makeGetRequest(limitBytes + 1) }

happened after
budget.go:91 kvstreamer.(*budget).consume { b.mu.Lock() } <<<<<
budget.go:90 kvstreamer.(*budget).consume { func (b *budget) consume(ctx context.Context, bytes int64, allowDebt bool) error { }
streamer.go:510 kvstreamer.(*Streamer).Enqueue { allowDebt := len(reqs) == 1 }
streamer_test.go:244 kvstreamer.TestStreamerBudgetErrorInEnqueue.func3 { reqs[0] = makeGetRequest(limitBytes + 1) }

in another goroutine: happened before
streamer.go:758 kvstreamer.(*workerCoordinator).issueRequestsForAsyncProcessing { w.s.budget.mu.Lock() } <<<<<
streamer.go:757 kvstreamer.(*workerCoordinator).issueRequestsForAsyncProcessing { }() }
streamer.go:713 kvstreamer.(*workerCoordinator).mainLoop { err := w.issueRequestsForAsyncProcessing(ctx, requestsToServe, avgResponseSize) }
../../../util/stop/stopper.go:488 stop.(*Stopper).RunAsyncTaskEx.func2 { f(ctx) }

happened after
streamer.go:602 kvstreamer.(*Streamer).getNumRequestsInFlight { s.mu.Lock() } <<<<<
streamer.go:601 kvstreamer.(*Streamer).getNumRequestsInFlight { func (s *Streamer) getNumRequestsInFlight() int { }
streamer.go:760 kvstreamer.(*workerCoordinator).issueRequestsForAsyncProcessing {  }
streamer.go:713 kvstreamer.(*workerCoordinator).mainLoop { err := w.issueRequestsForAsyncProcessing(ctx, requestsToServe, avgResponseSize) }
../../../util/stop/stopper.go:488 stop.(*Stopper).RunAsyncTaskEx.func2 { f(ctx) }

Other goroutines holding locks:
goroutine 130808 lock 0xc001017420
streamer.go:758 kvstreamer.(*workerCoordinator).issueRequestsForAsyncProcessing { w.s.budget.mu.Lock() } <<<<<
streamer.go:757 kvstreamer.(*workerCoordinator).issueRequestsForAsyncProcessing { }() }
streamer.go:713 kvstreamer.(*workerCoordinator).mainLoop { err := w.issueRequestsForAsyncProcessing(ctx, requestsToServe, avgResponseSize) }
../../../util/stop/stopper.go:488 stop.(*Stopper).RunAsyncTaskEx.func2 { f(ctx) }





ERROR: exit status 2

1 runs completed, 1 failures, over 1s
context canceled
```
<details><summary>Help</summary>
<p>

See also: [How To Investigate a Go Test Failure \(internal\)](https://cockroachlabs.atlassian.net/l/c/HgfXfJgM)
Parameters in this failure:

- TAGS=deadlock

- GOFLAGS=-parallel=4
</p>
</details>
/cc @cockroachdb/kv
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*TestStreamerBudgetErrorInEnqueue.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)
</sub>

### LINKED ISSUE #74787: server: TestStatusAPIIndexUsage failed
server.TestStatusAPIIndexUsage [failed](https://teamcity.cockroachdb.com/viewLog.html?buildId=4109339&tab=buildLog) with [artifacts](https://teamcity.cockroachdb.com/viewLog.html?buildId=4109339&tab=artifacts#/) on master @ [c3d71ac887844bef174abb6dab2a4e1ce9270ab7](https://github.com/cockroachdb/cockroach/commits/c3d71ac887844bef174abb6dab2a4e1ce9270ab7):

```
../sql/colfetcher/cfetcher.go:347 colfetcher.(*cFetcher).resetBatch { } }
../sql/colfetcher/cfetcher.go:1065 colfetcher.(*cFetcher).shiftState { func (rf *cFetcher) shiftState() { }
../sql/colfetcher/index_join.go:229 colfetcher.(*ColIndexJoin).Next { batch, err := s.rf.NextBatch(s.Ctx) }
../sql/colexec/invariants_checker.go:94 colexec.(*invariantsChecker).Next { b := i.Input.Next() }
../sql/colexec/colexecutils/cancel_checker.go:58 colexecutils.(*CancelChecker).Next { c.CheckEveryCall() }
../sql/colexec/invariants_checker.go:94 colexec.(*invariantsChecker).Next { b := i.Input.Next() }
../sql/colflow/stats.go:100 colflow.(*batchInfoCollector).Next { bic.stopwatch.Stop() }
../sql/colexec/colexecutils/deselector.go:63 colexecutils.(*deselectorOp).Next { batch := p.Input.Next() }
../sql/colflow/colrpc/outbox.go:289 colrpc.(*Outbox).sendBatches.func1 { batch := o.Input.Next() }
../sql/colexecerror/error.go:91 colexecerror.CatchVectorizedRuntimeError { operation() }
../sql/colflow/colrpc/outbox.go:326 colrpc.(*Outbox).sendBatches { }) }
../sql/colflow/colrpc/outbox.go:413 colrpc.(*Outbox).runWithStream {  }
../sql/colflow/colrpc/outbox.go:222 colrpc.(*Outbox).Run { o.runWithStream(ctx, stream, flowCtxCancel, outboxCtxCancel) }
../sql/colflow/vectorized_flow.go:694 colflow.(*vectorizedFlowCreator).setupRemoteOutputStream.func1 { ) }
../sql/colflow/vectorized_flow.go:1268 colflow.(*vectorizedFlowCreatorHelper).accumulateAsyncComponent.func1.1 { run(ctx, flowCtxCancel) }

goroutine 12001557 lock 0xc00c92f360
../util/mon/bytes_usage.go:652 mon.(*BytesMonitor).reserveBytes { mm.mu.Lock() } <<<<<
../util/mon/bytes_usage.go:651 mon.(*BytesMonitor).reserveBytes { func (mm *BytesMonitor) reserveBytes(ctx context.Context, x int64) error { }
../util/mon/bytes_usage.go:618 mon.(*BoundAccount).Grow { minExtra := b.mon.roundSize(x) }
../util/mon/bytes_usage.go:741 mon.(*BytesMonitor).increaseBudget {  }
../util/mon/bytes_usage.go:666 mon.(*BytesMonitor).reserveBytes { if mm.mu.curAllocated > mm.mu.curBudget.used+mm.reserved.used-x { }
../util/mon/bytes_usage.go:618 mon.(*BoundAccount).Grow { minExtra := b.mon.roundSize(x) }
../sql/colmem/allocator.go:127 colmem.(*Allocator).NewMemBatchWithFixedCapacity { estimatedMemoryUsage := selVectorSize(capacity) + EstimateBatchSizeBytes(typs, capacity) }
../sql/colmem/allocator.go:177 colmem.(*Allocator).ResetMaybeReallocate { if oldBatch == nil { }
../sql/colmem/allocator.go:592 colmem.(*SetAccountingHelper).ResetMaybeReallocate { ) (newBatch coldata.Batch, reallocated bool) { }
../sql/colfetcher/cfetcher.go:347 colfetcher.(*cFetcher).resetBatch { } }
../sql/colfetcher/cfetcher.go:1065 colfetcher.(*cFetcher).shiftState { func (rf *cFetcher) shiftState() { }
../sql/colfetcher/index_join.go:229 colfetcher.(*ColIndexJoin).Next { batch, err := s.rf.NextBatch(s.Ctx) }
../sql/colexec/invariants_checker.go:94 colexec.(*invariantsChecker).Next { b := i.Input.Next() }
../sql/colexec/colexecutils/cancel_checker.go:58 colexecutils.(*CancelChecker).Next { c.CheckEveryCall() }
../sql/colexec/invariants_checker.go:94 colexec.(*invariantsChecker).Next { b := i.Input.Next() }
../sql/colflow/stats.go:100 colflow.(*batchInfoCollector).Next { bic.stopwatch.Stop() }
../sql/colexec/colexecutils/deselector.go:63 colexecutils.(*deselectorOp).Next { batch := p.Input.Next() }
../sql/colflow/colrpc/outbox.go:289 colrpc.(*Outbox).sendBatches.func1 { batch := o.Input.Next() }
../sql/colexecerror/error.go:91 colexecerror.CatchVectorizedRuntimeError { operation() }
../sql/colflow/colrpc/outbox.go:326 colrpc.(*Outbox).sendBatches { }) }
../sql/colflow/colrpc/outbox.go:413 colrpc.(*Outbox).runWithStream {  }
../sql/colflow/colrpc/outbox.go:222 colrpc.(*Outbox).Run { o.runWithStream(ctx, stream, flowCtxCancel, outboxCtxCancel) }
../sql/colflow/vectorized_flow.go:694 colflow.(*vectorizedFlowCreator).setupRemoteOutputStream.func1 { ) }
../sql/colflow/vectorized_flow.go:1268 colflow.(*vectorizedFlowCreatorHelper).accumulateAsyncComponent.func1.1 { run(ctx, flowCtxCancel) }





ERROR: exit status 2

1 runs completed, 1 failures, over 2m26s
context canceled
```
<details><summary>Help</summary>
<p>

See also: [How To Investigate a Go Test Failure \(internal\)](https://cockroachlabs.atlassian.net/l/c/HgfXfJgM)
Parameters in this failure:

- TAGS=deadlock

- GOFLAGS=-parallel=4
</p>
</details>
/cc @cockroachdb/server
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*TestStatusAPIIndexUsage.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)
</sub>

### LINKED ISSUE #74788: sql: TestMemoryLimit failed
sql.TestMemoryLimit [failed](https://teamcity.cockroachdb.com/viewLog.html?buildId=4109420&tab=buildLog) with [artifacts](https://teamcity.cockroachdb.com/viewLog.html?buildId=4109420&tab=artifacts#/) on master @ [c3d71ac887844bef174abb6dab2a4e1ce9270ab7](https://github.com/cockroachdb/cockroach/commits/c3d71ac887844bef174abb6dab2a4e1ce9270ab7):

```
../kv/kvclient/kvstreamer/budget.go:90 kvstreamer.(*budget).consume { func (b *budget) consume(ctx context.Context, bytes int64, allowDebt bool) error { }
../kv/kvclient/kvstreamer/streamer.go:510 kvstreamer.(*Streamer).Enqueue { allowDebt := len(reqs) == 1 }
row/kv_batch_streamer.go:77 row.NewTxnKVStreamer { reqs := spansToRequests(spans, false /* reverse */, keyLocking) }
rowexec/joinreader.go:896 rowexec.(*joinReader).readInput { kvBatchFetcher, err = row.NewTxnKVStreamer(jr.Ctx, jr.streamerInfo.Streamer, spans, jr.keyLocking) }
rowexec/joinreader.go:697 rowexec.(*joinReader).Next { case jrReadingInput: }
rowexec/stats.go:67 rowexec.(*inputStatCollector).Next { row, meta := isc.RowSource.Next() }
rowexec/filterer.go:82 rowexec.(*filtererProcessor).Next {  }
execinfra/base.go:187 execinfra.Run { // Emit the row; stop if no more rows are needed. }
execinfra/processorsbase.go:733 execinfra.(*ProcessorBaseNoHelper).Run { Run(pb.Ctx, pb.self, pb.Output) }
flowinfra/flow.go:453 flowinfra.(*FlowBase).Run { headProc.Run(ctx) }
distsql_running.go:566 sql.(*DistSQLPlanner).Run { // PlanAndRun. We should refactor this and get rid off ignoreClose field. }
distsql_running.go:1400 sql.(*DistSQLPlanner).PlanAndRun { recv.expectedRowsRead = int64(physPlan.TotalEstimatedScannedRows) }
conn_executor_exec.go:1411 sql.(*connExecutor).execWithDistSQLEngine { // need to have access to the main query tree. }
conn_executor_exec.go:1109 sql.(*connExecutor).dispatchToExecutionEngine { // plan has not been closed earlier. }
conn_executor_exec.go:720 sql.(*connExecutor).execStmtInOpenState {  }
conn_executor_exec.go:134 sql.(*connExecutor).execStmt { } else { }
conn_executor.go:1751 sql.(*connExecutor).execCmd.func1 {  }
conn_executor.go:1761 sql.(*connExecutor).execCmd { ex.statsCollector.PhaseTimes().SetSessionPhaseTime(sessionphase.SessionQueryServiced, timeutil.Now()) }
conn_executor.go:1675 sql.(*connExecutor).run { var err error }
conn_executor.go:680 sql.(*Server).ServeConn { }() }
pgwire/conn.go:665 pgwire.(*conn).processCommandsAsync.func1 { reservedOwned = false // We're about to pass ownership away. }

in another goroutine: happened before
../kv/kvclient/kvstreamer/streamer.go:758 kvstreamer.(*workerCoordinator).issueRequestsForAsyncProcessing { w.s.budget.mu.Lock() } <<<<<
../kv/kvclient/kvstreamer/streamer.go:757 kvstreamer.(*workerCoordinator).issueRequestsForAsyncProcessing { }() }
../kv/kvclient/kvstreamer/streamer.go:713 kvstreamer.(*workerCoordinator).mainLoop { err := w.issueRequestsForAsyncProcessing(ctx, requestsToServe, avgResponseSize) }
../util/stop/stopper.go:488 stop.(*Stopper).RunAsyncTaskEx.func2 { f(ctx) }

happened after
../kv/kvclient/kvstreamer/streamer.go:602 kvstreamer.(*Streamer).getNumRequestsInFlight { s.mu.Lock() } <<<<<
../kv/kvclient/kvstreamer/streamer.go:601 kvstreamer.(*Streamer).getNumRequestsInFlight { func (s *Streamer) getNumRequestsInFlight() int { }
../kv/kvclient/kvstreamer/streamer.go:760 kvstreamer.(*workerCoordinator).issueRequestsForAsyncProcessing {  }
../kv/kvclient/kvstreamer/streamer.go:713 kvstreamer.(*workerCoordinator).mainLoop { err := w.issueRequestsForAsyncProcessing(ctx, requestsToServe, avgResponseSize) }
../util/stop/stopper.go:488 stop.(*Stopper).RunAsyncTaskEx.func2 { f(ctx) }

Other goroutines holding locks:
goroutine 4876751 lock 0xc01427dc80
../kv/kvclient/kvstreamer/streamer.go:758 kvstreamer.(*workerCoordinator).issueRequestsForAsyncProcessing { w.s.budget.mu.Lock() } <<<<<
../kv/kvclient/kvstreamer/streamer.go:757 kvstreamer.(*workerCoordinator).issueRequestsForAsyncProcessing { }() }
../kv/kvclient/kvstreamer/streamer.go:713 kvstreamer.(*workerCoordinator).mainLoop { err := w.issueRequestsForAsyncProcessing(ctx, requestsToServe, avgResponseSize) }
../util/stop/stopper.go:488 stop.(*Stopper).RunAsyncTaskEx.func2 { f(ctx) }





ERROR: exit status 2

1 runs completed, 1 failures, over 1m14s
context canceled
```
<details><summary>Help</summary>
<p>

See also: [How To Investigate a Go Test Failure \(internal\)](https://cockroachlabs.atlassian.net/l/c/HgfXfJgM)
Parameters in this failure:

- TAGS=deadlock

- GOFLAGS=-parallel=4
</p>
</details>
/cc @cockroachdb/sql-queries
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*TestMemoryLimit.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)
</sub>

### LINKED ISSUE #74789: sql/rowexec: TestIndexJoiner failed
sql/rowexec.TestIndexJoiner [failed](https://teamcity.cockroachdb.com/viewLog.html?buildId=4109810&tab=buildLog) with [artifacts](https://teamcity.cockroachdb.com/viewLog.html?buildId=4109810&tab=artifacts#/) on master @ [c3d71ac887844bef174abb6dab2a4e1ce9270ab7](https://github.com/cockroachdb/cockroach/commits/c3d71ac887844bef174abb6dab2a4e1ce9270ab7):

```
../../kv/kvclient/kvstreamer/streamer.go:393 kvstreamer.(*Streamer).Enqueue { s.mu.Lock() } <<<<<
../../kv/kvclient/kvstreamer/streamer.go:392 kvstreamer.(*Streamer).Enqueue { // acquisitions once pipelining is implemented. }
../row/kv_batch_streamer.go:77 row.NewTxnKVStreamer { reqs := spansToRequests(spans, false /* reverse */, keyLocking) }
joinreader.go:896 rowexec.(*joinReader).readInput { kvBatchFetcher, err = row.NewTxnKVStreamer(jr.Ctx, jr.streamerInfo.Streamer, spans, jr.keyLocking) }
joinreader.go:697 rowexec.(*joinReader).Next { case jrReadingInput: }
../execinfra/base.go:187 execinfra.Run { // Emit the row; stop if no more rows are needed. }
../execinfra/processorsbase.go:733 execinfra.(*ProcessorBaseNoHelper).Run { Run(pb.Ctx, pb.self, pb.Output) }
utils_test.go:71 rowexec.runProcessorTest { p.Run(context.Background()) }
joinreader_test.go:1320 rowexec.TestIndexJoiner.func4 { ) }

happened after
../../kv/kvclient/kvstreamer/budget.go:91 kvstreamer.(*budget).consume { b.mu.Lock() } <<<<<
../../kv/kvclient/kvstreamer/budget.go:90 kvstreamer.(*budget).consume { func (b *budget) consume(ctx context.Context, bytes int64, allowDebt bool) error { }
../../kv/kvclient/kvstreamer/streamer.go:510 kvstreamer.(*Streamer).Enqueue { allowDebt := len(reqs) == 1 }
../row/kv_batch_streamer.go:77 row.NewTxnKVStreamer { reqs := spansToRequests(spans, false /* reverse */, keyLocking) }
joinreader.go:896 rowexec.(*joinReader).readInput { kvBatchFetcher, err = row.NewTxnKVStreamer(jr.Ctx, jr.streamerInfo.Streamer, spans, jr.keyLocking) }
joinreader.go:697 rowexec.(*joinReader).Next { case jrReadingInput: }
../execinfra/base.go:187 execinfra.Run { // Emit the row; stop if no more rows are needed. }
../execinfra/processorsbase.go:733 execinfra.(*ProcessorBaseNoHelper).Run { Run(pb.Ctx, pb.self, pb.Output) }
utils_test.go:71 rowexec.runProcessorTest { p.Run(context.Background()) }
joinreader_test.go:1320 rowexec.TestIndexJoiner.func4 { ) }

in another goroutine: happened before
../../kv/kvclient/kvstreamer/streamer.go:758 kvstreamer.(*workerCoordinator).issueRequestsForAsyncProcessing { w.s.budget.mu.Lock() } <<<<<
../../kv/kvclient/kvstreamer/streamer.go:757 kvstreamer.(*workerCoordinator).issueRequestsForAsyncProcessing { }() }
../../kv/kvclient/kvstreamer/streamer.go:713 kvstreamer.(*workerCoordinator).mainLoop { err := w.issueRequestsForAsyncProcessing(ctx, requestsToServe, avgResponseSize) }
../../util/stop/stopper.go:488 stop.(*Stopper).RunAsyncTaskEx.func2 { f(ctx) }

happened after
../../kv/kvclient/kvstreamer/streamer.go:602 kvstreamer.(*Streamer).getNumRequestsInFlight { s.mu.Lock() } <<<<<
../../kv/kvclient/kvstreamer/streamer.go:601 kvstreamer.(*Streamer).getNumRequestsInFlight { func (s *Streamer) getNumRequestsInFlight() int { }
../../kv/kvclient/kvstreamer/streamer.go:760 kvstreamer.(*workerCoordinator).issueRequestsForAsyncProcessing {  }
../../kv/kvclient/kvstreamer/streamer.go:713 kvstreamer.(*workerCoordinator).mainLoop { err := w.issueRequestsForAsyncProcessing(ctx, requestsToServe, avgResponseSize) }
../../util/stop/stopper.go:488 stop.(*Stopper).RunAsyncTaskEx.func2 { f(ctx) }

Other goroutines holding locks:
goroutine 603434 lock 0xc006c93180
../../kv/kvclient/kvstreamer/streamer.go:758 kvstreamer.(*workerCoordinator).issueRequestsForAsyncProcessing { w.s.budget.mu.Lock() } <<<<<
../../kv/kvclient/kvstreamer/streamer.go:757 kvstreamer.(*workerCoordinator).issueRequestsForAsyncProcessing { }() }
../../kv/kvclient/kvstreamer/streamer.go:713 kvstreamer.(*workerCoordinator).mainLoop { err := w.issueRequestsForAsyncProcessing(ctx, requestsToServe, avgResponseSize) }
../../util/stop/stopper.go:488 stop.(*Stopper).RunAsyncTaskEx.func2 { f(ctx) }





ERROR: exit status 2

1 runs completed, 1 failures, over 8s
context canceled
```
<details><summary>Help</summary>
<p>

See also: [How To Investigate a Go Test Failure \(internal\)](https://cockroachlabs.atlassian.net/l/c/HgfXfJgM)
Parameters in this failure:

- TAGS=deadlock

- GOFLAGS=-parallel=4
</p>
</details>
/cc @cockroachdb/sql-queries
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*TestIndexJoiner.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)
</sub>

### LINKED ISSUE #74790: sql/stmtdiagnostics: TestDiagnosticsRequest failed
sql/stmtdiagnostics.TestDiagnosticsRequest [failed](https://teamcity.cockroachdb.com/viewLog.html?buildId=4109990&tab=buildLog) with [artifacts](https://teamcity.cockroachdb.com/viewLog.html?buildId=4109990&tab=artifacts#/) on master @ [c3d71ac887844bef174abb6dab2a4e1ce9270ab7](https://github.com/cockroachdb/cockroach/commits/c3d71ac887844bef174abb6dab2a4e1ce9270ab7):

```
../colmem/allocator.go:592 colmem.(*SetAccountingHelper).ResetMaybeReallocate { ) (newBatch coldata.Batch, reallocated bool) { }
../colfetcher/cfetcher.go:347 colfetcher.(*cFetcher).resetBatch { } }
../colfetcher/cfetcher.go:1065 colfetcher.(*cFetcher).shiftState { func (rf *cFetcher) shiftState() { }
../colfetcher/index_join.go:229 colfetcher.(*ColIndexJoin).Next { batch, err := s.rf.NextBatch(s.Ctx) }
../colexec/invariants_checker.go:94 colexec.(*invariantsChecker).Next { b := i.Input.Next() }
../colexec/colexecutils/cancel_checker.go:58 colexecutils.(*CancelChecker).Next { c.CheckEveryCall() }
../colexec/colexecutils/operator.go:137 colexecutils.(*vectorTypeEnforcer).Next { b := e.Input.Next() }
../colexec/colexecbase/const.eg.go:479 colexecbase.constTimestampOp.Next { batch := c.Input.Next() }
../colexec/invariants_checker.go:94 colexec.(*invariantsChecker).Next { b := i.Input.Next() }
../colexec/materializer.go:265 colexec.(*Materializer).next { // Get a fresh batch. }
../colexec/materializer.go:290 colexec.(*Materializer).nextAdapter { func (m *Materializer) nextAdapter() { }
../colexecerror/error.go:91 colexecerror.CatchVectorizedRuntimeError { operation() }
../colexec/materializer.go:296 colexec.(*Materializer).Next { for m.State == execinfra.StateRunning { }
../row_source_to_plan_node.go:75 sql.(*rowSourceToPlanNode).Next { var p *execinfrapb.ProducerMetadata }
../update.go:162 sql.(*updateNode).BatchedNext { // Advance one individual row. }
../plan_batch.go:114 sql.(*serializeNode).Next { // First batch, or finished previous batch; advance one. }
../plan_node_to_row_source.go:191 sql.(*planNodeToRowSource).Next { valid, err := p.node.Next(p.params) }
../colflow/flow_coordinator.go:127 colflow.(*FlowCoordinator).next { if f.State == execinfra.StateRunning { }
../colflow/flow_coordinator.go:144 colflow.(*FlowCoordinator).nextAdapter { func (f *FlowCoordinator) nextAdapter() { }
../colexecerror/error.go:91 colexecerror.CatchVectorizedRuntimeError { operation() }
../colflow/flow_coordinator.go:149 colflow.(*FlowCoordinator).Next { func (f *FlowCoordinator) Next() (rowenc.EncDatumRow, *execinfrapb.ProducerMetadata) { }
../execinfra/base.go:187 execinfra.Run { // Emit the row; stop if no more rows are needed. }
../execinfra/processorsbase.go:733 execinfra.(*ProcessorBaseNoHelper).Run { Run(pb.Ctx, pb.self, pb.Output) }
../flowinfra/flow.go:453 flowinfra.(*FlowBase).Run { headProc.Run(ctx) }
../colflow/vectorized_flow.go:246 colflow.(*vectorizedFlow).Run { f.FlowBase.Run(ctx, doneFn) }
../distsql_running.go:566 sql.(*DistSQLPlanner).Run { // PlanAndRun. We should refactor this and get rid off ignoreClose field. }
../distsql_running.go:1400 sql.(*DistSQLPlanner).PlanAndRun { recv.expectedRowsRead = int64(physPlan.TotalEstimatedScannedRows) }
../conn_executor_exec.go:1411 sql.(*connExecutor).execWithDistSQLEngine { // need to have access to the main query tree. }
../conn_executor_exec.go:1109 sql.(*connExecutor).dispatchToExecutionEngine { // plan has not been closed earlier. }
../conn_executor_exec.go:720 sql.(*connExecutor).execStmtInOpenState {  }
../conn_executor_exec.go:134 sql.(*connExecutor).execStmt { } else { }
../conn_executor.go:1751 sql.(*connExecutor).execCmd.func1 {  }
../conn_executor.go:1761 sql.(*connExecutor).execCmd { ex.statsCollector.PhaseTimes().SetSessionPhaseTime(sessionphase.SessionQueryServiced, timeutil.Now()) }
../conn_executor.go:1675 sql.(*connExecutor).run { var err error }
../internal.go:204 sql.(*InternalExecutor).initConnEx.func1 { go func() { }

goroutine 117944 lock 0xc00287d220
../../kv/kvclient/kvstreamer/streamer.go:758 kvstreamer.(*workerCoordinator).issueRequestsForAsyncProcessing { w.s.budget.mu.Lock() } <<<<<
../../kv/kvclient/kvstreamer/streamer.go:757 kvstreamer.(*workerCoordinator).issueRequestsForAsyncProcessing { }() }
../../kv/kvclient/kvstreamer/streamer.go:713 kvstreamer.(*workerCoordinator).mainLoop { err := w.issueRequestsForAsyncProcessing(ctx, requestsToServe, avgResponseSize) }
../../util/stop/stopper.go:488 stop.(*Stopper).RunAsyncTaskEx.func2 { f(ctx) }





ERROR: exit status 2

1 runs completed, 1 failures, over 2s
context canceled
```
<details><summary>Help</summary>
<p>

See also: [How To Investigate a Go Test Failure \(internal\)](https://cockroachlabs.atlassian.net/l/c/HgfXfJgM)
Parameters in this failure:

- TAGS=deadlock

- GOFLAGS=-parallel=4
</p>
</details>
/cc @cockroachdb/sql-queries
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*TestDiagnosticsRequest.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)
</sub>

### LINKED ISSUE #74791: sql/tests: TestInvertedIndex failed
sql/tests.TestInvertedIndex [failed](https://teamcity.cockroachdb.com/viewLog.html?buildId=4109993&tab=buildLog) with [artifacts](https://teamcity.cockroachdb.com/viewLog.html?buildId=4109993&tab=artifacts#/) on master @ [c3d71ac887844bef174abb6dab2a4e1ce9270ab7](https://github.com/cockroachdb/cockroach/commits/c3d71ac887844bef174abb6dab2a4e1ce9270ab7):

```
../colexec/invariants_checker.go:94 colexec.(*invariantsChecker).Next { b := i.Input.Next() }
../colexec/colexecutils/cancel_checker.go:58 colexecutils.(*CancelChecker).Next { c.CheckEveryCall() }
../colexec/invariants_checker.go:94 colexec.(*invariantsChecker).Next { b := i.Input.Next() }
../colflow/stats.go:100 colflow.(*batchInfoCollector).Next { bic.stopwatch.Stop() }
../colflow/flow_coordinator.go:239 colflow.(*BatchFlowCoordinator).nextAdapter { func (f *BatchFlowCoordinator) nextAdapter() { }
../colexecerror/error.go:91 colexecerror.CatchVectorizedRuntimeError { operation() }
../colflow/flow_coordinator.go:283 colflow.(*BatchFlowCoordinator).Run { err := f.next() }
../colflow/flow_coordinator.go:243 colflow.(*BatchFlowCoordinator).next { func (f *BatchFlowCoordinator) next() error { }
../colflow/vectorized_flow.go:259 colflow.(*vectorizedFlow).Run { f.batchFlowCoordinator.Run(ctx) }
../distsql_running.go:566 sql.(*DistSQLPlanner).Run { // PlanAndRun. We should refactor this and get rid off ignoreClose field. }
../distsql_running.go:1400 sql.(*DistSQLPlanner).PlanAndRun { recv.expectedRowsRead = int64(physPlan.TotalEstimatedScannedRows) }
../conn_executor_exec.go:1411 sql.(*connExecutor).execWithDistSQLEngine { // need to have access to the main query tree. }
../conn_executor_exec.go:1109 sql.(*connExecutor).dispatchToExecutionEngine { // plan has not been closed earlier. }
../conn_executor_exec.go:720 sql.(*connExecutor).execStmtInOpenState {  }
../conn_executor_exec.go:134 sql.(*connExecutor).execStmt { } else { }
../conn_executor_exec.go:234 sql.(*connExecutor).execPortal { } }
../conn_executor.go:1819 sql.(*connExecutor).execCmd.func2 { res = stmtRes }
../conn_executor.go:1829 sql.(*connExecutor).execCmd { ex.statsCollector.PhaseTimes().SetSessionPhaseTime(sessionphase.SessionQueryServiced, timeutil.Now()) }
../conn_executor.go:1675 sql.(*connExecutor).run { var err error }
../conn_executor.go:680 sql.(*Server).ServeConn { }() }
../pgwire/conn.go:665 pgwire.(*conn).processCommandsAsync.func1 { reservedOwned = false // We're about to pass ownership away. }

in another goroutine: happened before
../../kv/kvclient/kvstreamer/streamer.go:758 kvstreamer.(*workerCoordinator).issueRequestsForAsyncProcessing { w.s.budget.mu.Lock() } <<<<<
../../kv/kvclient/kvstreamer/streamer.go:757 kvstreamer.(*workerCoordinator).issueRequestsForAsyncProcessing { }() }
../../kv/kvclient/kvstreamer/streamer.go:713 kvstreamer.(*workerCoordinator).mainLoop { err := w.issueRequestsForAsyncProcessing(ctx, requestsToServe, avgResponseSize) }
../../util/stop/stopper.go:488 stop.(*Stopper).RunAsyncTaskEx.func2 { f(ctx) }

happened after
../../kv/kvclient/kvstreamer/streamer.go:602 kvstreamer.(*Streamer).getNumRequestsInFlight { s.mu.Lock() } <<<<<
../../kv/kvclient/kvstreamer/streamer.go:601 kvstreamer.(*Streamer).getNumRequestsInFlight { func (s *Streamer) getNumRequestsInFlight() int { }
../../kv/kvclient/kvstreamer/streamer.go:760 kvstreamer.(*workerCoordinator).issueRequestsForAsyncProcessing {  }
../../kv/kvclient/kvstreamer/streamer.go:713 kvstreamer.(*workerCoordinator).mainLoop { err := w.issueRequestsForAsyncProcessing(ctx, requestsToServe, avgResponseSize) }
../../util/stop/stopper.go:488 stop.(*Stopper).RunAsyncTaskEx.func2 { f(ctx) }

Other goroutines holding locks:
goroutine 6302759 lock 0xc0089aaa60
../../kv/kvclient/kvstreamer/streamer.go:758 kvstreamer.(*workerCoordinator).issueRequestsForAsyncProcessing { w.s.budget.mu.Lock() } <<<<<
../../kv/kvclient/kvstreamer/streamer.go:757 kvstreamer.(*workerCoordinator).issueRequestsForAsyncProcessing { }() }
../../kv/kvclient/kvstreamer/streamer.go:713 kvstreamer.(*workerCoordinator).mainLoop { err := w.issueRequestsForAsyncProcessing(ctx, requestsToServe, avgResponseSize) }
../../util/stop/stopper.go:488 stop.(*Stopper).RunAsyncTaskEx.func2 { f(ctx) }





ERROR: exit status 2

1 runs completed, 1 failures, over 1m5s
context canceled
```
<details><summary>Help</summary>
<p>

See also: [How To Investigate a Go Test Failure \(internal\)](https://cockroachlabs.atlassian.net/l/c/HgfXfJgM)
Parameters in this failure:

- TAGS=deadlock

- GOFLAGS=-parallel=4
</p>
</details>
/cc @cockroachdb/sql-queries
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*TestInvertedIndex.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)
</sub>

### PR DESCRIPTION
**Pull request by yuzefovich**
We have two different locks in the `Streamer` infrastructure: one is for
the `Streamer` itself and another one for the `budget`. Previously,
there was no contract about which mutex needs to be acquired first which
led to the deadlock detector thinking that there is a potential deadlock
situation. This is now fixed by requiring that the `budget`'s mutex is
acquired first and by releasing the `Streamer`'s mutex in `Enqueue`
early in order to not overlap with the interaction with the `budget`.

I believe that it was a false positive (i.e. the deadlock cannot
actually occur) because without the support of pipelining, `Enqueue`
calls and asynchronous requests evaluation never overlap in time.
Still, it's good to fix the order of mutex acquisitions.

Fixes: #74782.
Fixes: #74785.
Fixes: #74787.
Fixes: #74788.
Fixes: #74789.
Fixes: #74790.
Fixes: #74791.

Release note: None

### CODE REVIEW

**Review by rharding6373 — APPROVED** [review]
The order guideline seems hard to maintain, but I don't have a better idea at the moment... thanks for the quick fix! :lgtm: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/74807#-:-MtKIJuB0lEJHn4nfDOT:btp0u3k)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @rytaft)

File: pkg/kv/kvclient/kvstreamer/streamer.go [hunk 1]
```diff
@@ -391,13 +393,22 @@ func (s *Streamer) Enqueue(
...
+	locked := true
 	defer func() {
-		if retErr != nil && s.mu.err == nil {
-			// Set the error so that mainLoop of the worker coordinator exits
-			// as soon as possible, without issuing any more requests.
-			s.mu.err = retErr
+		if retErr != nil {
+			if !locked {
+				s.mu.Lock()
+				locked = true
```
Comment (knz) [inline pkg/kv/kvclient/kvstreamer/streamer.go:401]: This is introducing a new race condition, which is objectively worse - it can only be caught by the race detector now, which is less precise/powerful than the deadlock detector.

After `s.mu.Unlock()` in the main body of the function, there's a brief amount of time where `locked` is still `true`.
If the defer is run at that moment, then this condition here `if !locked` will not fire, and `s.mu.err` below becomes a racy write.

Can't this be handled with a buffered channel for s.mu.err instead?

Comment (yuzefovich) [reply pkg/kv/kvclient/kvstreamer/streamer.go:401]: Indeed, nice catch, thanks! I opened up a fix in #75078.

> Can't this be handled with a buffered channel for s.mu.err instead?

The buffered channel could work, but it doesn't seem to be a natural fit for this since, generally speaking, we want to observe the error from multiple goroutines (`workerCoordinator.mainLoop` and `GetResults`).
