### PR TITLE
structlogging: skip hot range logging exit test

### LINKED ISSUE #149914: pkg/server/structlogging/structlogging_test: TestHotRangesLoggingJobExitProcedure failed
pkg/server/structlogging/structlogging_test.TestHotRangesLoggingJobExitProcedure [failed](https://mesolite.cluster.engflow.com/invocations/default/54d41ee4-c127-442f-adfe-677c58edf240?testReportRun=1&testReportShard=1&testReportAttempt=1#targets-Ly9wa2cvc2VydmVyL3N0cnVjdGxvZ2dpbmc6c3RydWN0bG9nZ2luZ190ZXN0) on master @ [e074bcf710e6de238a82058d3fdc802cb819a06c](https://github.com/cockroachdb/cockroach/commits/e074bcf710e6de238a82058d3fdc802cb819a06c):

```
=== RUN   TestHotRangesLoggingJobExitProcedure
    test_log_scope.go:171: test logs captured to: outputs.zip/logTestHotRangesLoggingJobExitProcedure1037732617
    test_log_scope.go:82: use -show-logs to present logs inline
    hot_ranges_log_job_test.go:42: condition failed to evaluate within 45s: from hot_ranges_log_job_test.go:53: app job status is succeeded, not running
    panic.go:635: -- test log scope end --
test logs left over in: outputs.zip/logTestHotRangesLoggingJobExitProcedure1037732617
--- FAIL: TestHotRangesLoggingJobExitProcedure (45.97s)
```

Parameters:
 - <code>attempt=1</code>
 - <code>run=1</code>
 - <code>shard=1</code>
<details><summary>Help</summary>
<p>

See also: [How To Investigate a Go Test Failure \(internal\)](https://cockroachlabs.atlassian.net/l/c/HgfXfJgM)
</p>
</details>
/cc @cockroachdb/obs-prs
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*TestHotRangesLoggingJobExitProcedure.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/bazci/githubpost/issues)

</sub>

Jira issue: CRDB-52408

### PR DESCRIPTION
**Pull request by angles-n-daemons**
We added a test which verifies the behavior of the hot range logger, specifically that it should exit for system tenants but remain running for app tenants.

For whatever reason, it ends up exiting for app tenants for a reasons not well understood, so we skip this test while we investigate in the meantime.

Fixes: #149914
Epic: none
Release note: none

### CODE REVIEW

File: pkg/server/structlogging/hot_ranges_log_job_test.go [hunk 1]
```diff
@@ -27,6 +27,7 @@ func TestHotRangesLoggingJobExitProcedure(t *testing.T) {
 	defer log.Scope(t).Close(t)
 	skip.UnderStress(t)
 	skip.UnderRace(t)
+	skip.IgnoreLint(t, "skipping exit test")
```
Comment (kyle-a-wong) [inline pkg/server/structlogging/hot_ranges_log_job_test.go]: Is there a specific reason you use `IgnoreLint` and not `skip.WithIssue(t, 149914)`?

Comment (angles-n-daemons) [reply pkg/server/structlogging/hot_ranges_log_job_test.go]: none, wasn't familiar with the skipping syntax - changed.

**Review by kyle-a-wong — APPROVED** [review]
