### PR TITLE
roachtest: deflake splits/largerange/size=32GiB

### LINKED ISSUE #148982: roachtest: splits/largerange/size=32GiB,nodes=6 failed
roachtest.splits/largerange/size=32GiB,nodes=6 [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyAzureBazel/20042635?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyAzureBazel/20042635?buildTab=artifacts#/splits/largerange/size=32GiB,nodes=6) on master @ [d94e3501a43b45740331a70ddfddd9f08f567971](https://github.com/cockroachdb/cockroach/commits/d94e3501a43b45740331a70ddfddd9f08f567971):

```
(monitor.go:241).Wait: monitor failure: rebalancing incomplete: min_range_count=196, max_range_count=556
unexpected node event: n6: cockroach process for system interface died (exit code 7)
test artifacts and logs in: /artifacts/splits/largerange/size=32GiB_nodes=6/run_1
```

Parameters:
 - <code>arch=amd64</code>
 - <code>cloud=azure</code>
 - <code>coverageBuild=false</code>
 - <code>cpu=4</code>
 - <code>encrypted=false</code>
 - <code>metamorphicBufferedSender=true</code>
 - <code>metamorphicLeases=expiration</code>
 - <code>runtimeAssertionsBuild=false</code>
 - <code>ssd=0</code>
<details><summary>Help</summary>
<p>

See: [roachtest README](https://github.com/cockroachdb/cockroach/blob/master/pkg/cmd/roachtest/README.md)

See: [How To Investigate \(internal\)](https://cockroachlabs.atlassian.net/l/c/SSSBr8c7)

_Grafana is not yet available for azure clusters_</p>
</details>
/cc @cockroachdb/kv-triage
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*splits/largerange/size=32GiB,nodes=6.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/bazci/githubpost/issues)

</sub>

Jira issue: CRDB-51908

### PR DESCRIPTION
**Pull request by iskettaneh**
This commit reduces the snapshot_rebalance.max_rate from 512 to 192. The reasons are: (1) Even on Azure and GCE, I saw that we get about 192 Mbps of an actual snapshot send rate. (2) On IBM, the rate is much lower. (3) This rate goes into calculating the snapshot sending timeout, and it should generally be lower or slightly higher than the actual snapshot sending rate. If it's 10 times lower than the actual rate, the snapshot will most likely timeout.

See this comment for the exact analysis:
https://github.com/cockroachdb/cockroach/issues/148982#issuecomment-3020552145

Fixes: #148982

Release note: None

### CODE REVIEW

**Review by pav-kv — APPROVED** [review]

File: pkg/cmd/roachtest/tests/split.go [hunk 1]
```diff
@@ -644,7 +644,7 @@ func runLargeRangeSplits(ctx context.Context, t test.Test, c cluster.Cluster, si
 			if _, err := db.ExecContext(ctx, fmt.Sprintf("SET CLUSTER SETTING kv.range.range_size_hard_cap = '%d'", rangeMaxSize*2)); err != nil {
 				return err
 			}
-			if _, err := db.ExecContext(ctx, `SET CLUSTER SETTING kv.snapshot_rebalance.max_rate='512MiB'`); err != nil {
+			if _, err := db.ExecContext(ctx, `SET CLUSTER SETTING kv.snapshot_rebalance.max_rate='192MiB'`); err != nil {
```
Comment (tbg) [inline pkg/cmd/roachtest/tests/split.go:652]: Mind leaving a comment here?

**Review by tbg — DISMISSED** [review]
I think you accidentally checked in a pprof file :)
LGTM otherwise.

**Comment by iskettaneh** [comment]
TFTR!

bors r+

**Comment by iskettaneh** [comment]
TFTR!

I addressed the comments.

bors r+
