### PR TITLE
stability: Fix range-spanning inline DeleteRange

### LINKED ISSUE #10358: code: tsdb transactions failing due to inline writes
Gamma (sha 5bc7bf1)
```
E161101 02:47:55.305985 65 storage/queue.go:558  [n5,timeSeriesMaintenance] on [n5,s5,r573/3:/System/tsd/cr.node.gossip.by…]: "/System/tsd/cr.node.gossip.bytes.received-1h/1/10s/2016-09-27T03:00:00Z": inline writes not allowed within transactions
```

This is constantly happening. Not sure if this is a misuse by the metrics code, or a deeper problem.

### PR DESCRIPTION
**Pull request by mrtracy**
Fixes a bug where DeleteRange commands with the "inline" option set were
automatically placed into a transaction, causing them to fail. This occurred
when the command spanned multiple ranges.

Modified an existing Time Series test (time series are the only current user of
inline DeleteRange) to reproduce this situation.

Fixes #10358

---
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/10400)

### CODE REVIEW

File: pkg/roachpb/api.go [hunk 1]
```diff
@@ -771,13 +771,32 @@ func NewReverseScan(key, endKey Key) Request {
...
+	// This flag indicates that the request is deleting inline MVCC values,
+	// which cannot be deleted transactionally - inline DeleteRange will thus
+	// fail if executed as part of a transaction. This alternate flag set
+	// is needed to prevent the command from being automatically wrapped into a
+	// transaction by TxnCoordSender, which can occur if the command spans
+	// multiple ranges.
+	//
+	// TODO(mrtracy): The behavior of DeleteRangeRequest with "inline" set has
+	// likely diverged enough that it should be promoted into its own command.
+	// However, it is complicated to plumb a new command through the system,
```
Comment (mrtracy) [inline pkg/roachpb/api.go]: I discussed this in person with @petermattis, and we both favored this solution to fix the immediate problem; I wanted to put out this solution for code review to see if there are any strong objections.  This is three lines of code, whereas the alternative could be hundreds of lines between new protos, boilerplate and tests.

In my personal opinion, compared to the overall complexity of the batching system this seems almost trivial - it actually seems like the flags() system was designed to provide exactly this sort of flexibility.

Comment (petermattis) [inline pkg/roachpb/api.go]: I'm in favor of the approach in this PR. Creating a whole bunch of boilerplate just so we can have a different `flags()` setting doesn't seem like a good trade-off to me. This is a conscious decision to add some technical debt, but I'm not seeing any long-term repercussions to doing so in this instance.

@mrtracy Can you add a comment to `DeleteRangeRequest.inline` noting how that field changes the semantics of `DeleteRange` requests?

Comment (mrtracy) [inline pkg/roachpb/api.go]: @petermattis I've expanded the comment on that field of DeleteRangeRequest.

@vivekmenezes the code that ends up triggering the transaction depends on the properties of the _batch_ being executed, not the specific command.  The batch's flags are computed from its component commands, and can result in a non-transaction command being upgraded to transactional.  So, not only do we want inline DeleteRange to be non-transactional, but we also have to make sure that it isn't grouped into a batch with a transactional command - that means we also have to set the `isAlone` flag on the command.  The `flags()` command allows us to do both of those things.

**Review by petermattis — APPROVED** [review]
LGTM

**Comment by tamird** [comment]
Reviewed 2 of 2 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10400)*
