### PR TITLE
server: propagate DRPC setting to explicitly started external tenants

### LINKED ISSUE #164264: testing: external tenants started via StartTenant() don't inherit cluster setting overrides from parent server
## Description

When starting external tenants via `StartTenant()` in tests, the tenants do not inherit cluster setting overrides from the parent test server. This is inconsistent with shared-process tenants, which do inherit settings from their parent.

## Expected Behavior

External tenants started via `StartTenant()` should inherit cluster setting overrides from the parent test server, matching the behavior of shared-process tenants. This should apply whenever the test doesn't explicitly configure tenant settings separately.

## Observed Behavior

External tenants ignore cluster setting overrides set on the parent test server, while shared-process tenants correctly inherit them. This inconsistency can cause tests to behave differently depending on the tenant type, and makes it harder to write tests that work uniformly across both tenant modes.

## Reproduction

Start a test server with cluster setting overrides, then start an external tenant via `StartTenant()`. The external tenant will not have the overridden settings.

## Environment

- CockroachDB version: master (development)

Epic: None

Jira issue: CRDB-60723

Epic CRDB-55382

### PR DESCRIPTION
**Pull request by Nukitt**
Previously, the DRPC setting was not propagated to external tenants 
started explicitly via `StartTenant()`.

The default tenant path (startDefaultTestTenant) already handled this by
copying ApplicationLevel settings from `ts.params.Settings` via
`TestingCopyForVirtualCluster`, but this only worked when the test
explicitly provided a Settings object. When DefaultDRPCOption was used
without explicit Settings, `ts.params.Settings` remained
nil because `makeTestConfigFromParams` receives params by value and its
internal defaulting doesn't propagate back.

Rather than copying all ApplicationLevel settings (which would conflict
with the expectation that explicitly started tenants get a clean slate),
this change specifically propagates the DRPC setting from the parent
server's DefaultDRPCOption to all tenants created via `StartTenant()`.
DRPC is a test infrastructure concern that should apply uniformly
regardless of how tenants are started.

The shared tenant path is unaffected as `makeSharedProcessTenantConfig`
already copies settings via `TestingCopyForVirtualCluster` when
testSettings is non-nil.

Epic: None
Fixes: #164264
Release note: None

### CODE REVIEW

File: pkg/server/testserver.go [hunk 1]
```diff
@@ -1745,6 +1745,12 @@ func (ts *testServer) StartTenant(
 	st := params.Settings
 	if st == nil {
 		st = cluster.MakeTestingClusterSettings()
+		// Copy test setting overrides from the parent server to this external
+		// tenant, similar to how shared-process tenants inherit settings.
+		// This ensures ApplicationLevel settings like DRPC are propagated.
+		if parentSettings := ts.ClusterSettings(); parentSettings != nil {
+			st.SV.TestingCopyForVirtualCluster(&parentSettings.SV)
+		}
```
Comment (shubhamdhama) [inline pkg/server/testserver.go]: I don't think this is correct. If a test is explicitly starting a tenant using `StartTenant`, then they should pass the settings objects (with overrides) or options like `DefaultDRPCOption` in its `TestTenantArgs`.

I'm curious about the commit message which mentions that the shared process mode copies these settings from the system tenant, can you share the code for that?

Comment (shubhamdhama) [reply pkg/server/testserver.go]: I'm assuming in this context

> inconsistent with shared-process tenants, which do inherit settings from their parent.

means the shared-process mode tenants started with `StartSharedProcessTenant`

Comment (Nukitt) [reply pkg/server/testserver.go]: [This is the PR](https://github.com/cockroachdb/cockroach/pull/117384) where we enabled for shared process. These tenants exercise a `makeSharedProcessTenantConfig` unlike the external tenants and the test args passed to `StartSharedProcessTenant` flow through to `makeSharedProcessTenantConfig` via the server controller's saved test args, affecting the tenant's final configuration.

Comment (shubhamdhama) [reply pkg/server/testserver.go]: Huh... I'm not completely onboard for having this even for the shared process but I guess it exist for convenience. Thanks for sharing the reference.

**Review by shubhamdhama — APPROVED** [review]

File: pkg/server/testserver.go (hunk 1 above)
Comment (dt) [reply pkg/server/testserver.go]: I think there's certainly an argument that a separate tenant should get a clean slate of separate settings, and customize them explicitly if they want them customized, just like a production cluster would behave. I wish I had put more detail on my motivation in the commit message on that 2024 change, but I imagine it was indeed for convenience? I did find a slack message from around that time which seems related: 

> Huh, I think maybeStartDefaultTestTenant doesn't handle ts.params.Settings consistently:
If "external" multi-tenancy is chosen , we call startDefaultTestTenant, which will explicitly setup the tenant server settings to match the test's configured settings using `tenantSettings.SV.TestingCopyForVirtualCluster` However if "shared process" is chosen (quotes on both of these since in tests everything is shared process), we just call `newTenantServer` on the controller, which, via a couple hops, calls `makeSharedProcessTenantServerConfig` and that just does `cluster.MakeClusterSettings()`, creating a brand new ClusterSettings object that is fully distinct from the one the test args setup and passed.

So maybe I was trying to fix an inconsistency in how test server handled settings for tenants but maybe my fix should have been to change ts.params or something else? My recollection here is a bit fuzzy, sorry.

Comment (cthumuluru-crdb) [reply pkg/server/testserver.go]: Separate tenants should have independent configurations (args, settings), and copying system-tenant settings may not be ideal. That said, tests that probabilistically choose a tenant mode (system-tenant-only, shared-tenant, or external-tenant) _may_ not depend on tenant specific configuration. In those cases, inheriting system-tenant settings for the secondary tenants is probably fine. Tests that require precise tenant configuration can opt into `TestControlsTenantsExplicitly`, and for those tests we should avoid copying system-tenant settings altogether. This gives us the convenience we want while still allowing tenant-specific customization when needed.

**Review by shubhamdhama — APPROVED** [review]
