### PR TITLE
import: support computed columns with UDF references

### LINKED ISSUE #157195: import: computed columns defined with udf not allowed in the import destination table
A normal computed column can be allowed in the imported table:
```sql
DROP TABLE IF EXISTS test;
CREATE TABLE test (x INT PRIMARY KEY, z INT AS (x+1) STORED);
IMPORT INTO test(x) CSV DATA ("nodelocal://1/test1.csv") WITH nullif="NULL"; 
```

This works fine. The column `z` will be auto computed.

However, if the `z` column is a computed column with UDF:

```sql
DROP TABLE IF EXISTS test;

CREATE FUNCTION add_one(x INT)
RETURNS INT
AS $$
  SELECT CASE WHEN x IS NULL THEN NULL ELSE x + 1 END;
$$ LANGUAGE SQL IMMUTABLE;

CREATE TABLE test (x INT PRIMARY KEY, z INT AS (add_one(x)) STORED);
IMPORT INTO test(x) CSV DATA ("nodelocal://1/test1.csv") WITH nullif="NULL"; 
```

This will error out: `ERROR: nodelocal://1/test1.csv: error type checking and building computed expression for IMPORT INTO: function 100107 not found`

---- 

Seems rooting from that `crosscluster.CrossClusterTypeResolver` doesn't implement `tree.FunctionReferenceResolver`, therefore the `semaCtx.FunctionResolver == nil` .

Jira issue: CRDB-56407

### PR DESCRIPTION
**Pull request by mw5h**
## Summary

IMPORT INTO fails when the destination table has computed columns that
reference user-defined functions, with error `function <oid> not found`.

This PR fixes the issue in two commits:

1. **importer: set up FunctionResolver for computed column type-checking** —
   Sets up a `DistSQLFunctionResolver` on the `SemaContext` during import so
   that UDF references (stored as OIDs) in computed column expressions can be
   resolved. Follows the existing pattern from `ColumnBackfiller.InitForDistributedUse`.

2. **schemaexpr: inline UDF calls in computed column expressions** —
   Adds UDF inlining in `MakeComputedExprs` (the shared entry point for both
   IMPORT and backfill) so that `eval.Expr` can evaluate the resulting
   expressions without requiring the full optimizer/execbuilder infrastructure.
   Only single-statement immutable SQL UDFs are supported, which is the only
   kind allowed in computed columns.

Fixes: #157195
Informs: #147472

## Test plan

- Added `TestImportIntoComputedColumnWithUDF` regression test
- Verified existing `TestImportIntoUserDefinedTypes` still passes
- Verified `schemaexpr` unit tests still pass

### CODE REVIEW

**Review by yuzefovich — COMMENTED** [review]
Nice! I have a few questions.

> @yuzefovich reviewed 6 files and all commit messages, and made 6 comments.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/165129#-:-OnTsiF4EuURG3hVpE2x:brbtvk8)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on DrewKimball and mw5h).

___
*[`pkg/sql/catalog/schemaexpr/computed_column.go` line 326 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/165129#-OnTjeks7YcMRY7wOXTB:-OnTjeks7YcMRY7wOXTC:b-f5thnp) ([raw file](https://github.com/cockroachdb/cockroach/blob/c79e1a81711caaa7369dd4227ff1cc068e032e4f/pkg/sql/catalog/schemaexpr/computed_column.go#L326)):*
> ```Go
> 		}
> 
> 		// Collect all column IDs that are referenced in the partial index
> ```

nit: (not your code, but) this comment seems stale / copied incorrectly.
___
*[`pkg/sql/catalog/schemaexpr/computed_column.go` line 383 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/165129#-OnTk98C32x5BEIkM6Kt:-OnTk98C32x5BEIkM6Ku:b5qkcfm) ([raw file](https://github.com/cockroachdb/cockroach/blob/c79e1a81711caaa7369dd4227ff1cc068e032e4f/pkg/sql/catalog/schemaexpr/computed_column.go#L383)):*
> ```Go
> 	ctx context.Context, expr tree.TypedExpr, semaCtx *tree.SemaContext,
> ) (tree.TypedExpr, error) {
> 	newExpr, err := tree.SimpleVisit(expr, func(e tree.Expr) (bool, tree.Expr, error) {
> ```

nit: it's helpful to have named return arguments
```go
(recurse bool, newExpr tree.Expr, err error)
```
___
*[`pkg/sql/catalog/schemaexpr/computed_column.go` line 433 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/165129#-OnTmzVkD97cNL06bJsk:-OnTmzVkD97cNL06bJsl:bz8q5lw) ([raw file](https://github.com/cockroachdb/cockroach/blob/c79e1a81711caaa7369dd4227ff1cc068e032e4f/pkg/sql/catalog/schemaexpr/computed_column.go#L433)):*
> ```Go
> 		// already-typed argument expressions (e.g. IndexedVar).
> 		paramMap := make(map[string]tree.Expr, len(fn.RoutineParams))
> 		for i, p := range fn.RoutineParams {
> ```

Should we be ignoring OUT parameters here? Is it possible to have a computed expression invoke a routine with OUT / INOUT parameters?
___
*[`pkg/sql/catalog/schemaexpr/computed_column.go` line 439 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/165129#-OnTnle6Ah3wlCH1cbxt:-OnTnle7A2xSgUeZmm8K:bshi6n3) ([raw file](https://github.com/cockroachdb/cockroach/blob/c79e1a81711caaa7369dd4227ff1cc068e032e4f/pkg/sql/catalog/schemaexpr/computed_column.go#L439)):*
> ```Go
> 		}
> 
> 		// Substitute parameter references in the body.
> ```

Should we do another walk over `bodyExpr` after the substitution to check that all parameter references have been replaced and returning an error if not?
___
*[`pkg/sql/logictest/testdata/logic_test/udf_unsupported` line 9 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/165129#-OnToz6q0uqP2c-SFDTX:-OnToz6q0uqP2c-SFDTY:bjohn20) ([raw file](https://github.com/cockroachdb/cockroach/blob/c79e1a81711caaa7369dd4227ff1cc068e032e4f/pkg/sql/logictest/testdata/logic_test/udf_unsupported#L9)):*
> ```
> CREATE TABLE test_tbl_t (a INT PRIMARY KEY, b INT);
> 
> # Insert rows to verify that backfills that use UDFs produce correct values.
> ```

Should we introduce some new test cases for the errors with inlining the UDF and then move test cases that now work to another file (since this one is `udf_unsupported`)?

**Review by DrewKimball — COMMENTED** [review]
> @DrewKimball reviewed 3 files and all commit messages, and made 3 comments.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/165129)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on mw5h).

___
*[`-- commits` line 51 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/165129#-OnU-Fzj8sI3OTwAEpaE:-OnU-Fzj8sI3OTwAEpaF:b-99nm70):*
I don't think this is true - on a demo cluster, I was able to create a computed column expression calling a UDF with multiple statements as well as one with a PL/pgSQL routine.
___
*[`pkg/sql/catalog/schemaexpr/computed_column.go` line 440 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/165129#-OnTvJ4i09AUOgHHrsLs:-OnTvJ4i09AUOgHHrsLt:b-ri8rnx) ([raw file](https://github.com/cockroachdb/cockroach/blob/c79e1a81711caaa7369dd4227ff1cc068e032e4f/pkg/sql/catalog/schemaexpr/computed_column.go#L440)):*
> ```Go
> 
> 		// Substitute parameter references in the body.
> 		inlined, err := tree.SimpleVisit(
> ```

I'm not sure this pattern will actually visit everything that could be in a UDF body. We should test parameter references in:
* Subquery
* The inputs + ON condition of a Join
* CTE
* GroupBy

We should also test:
* Nested routine calls
* Ordinal parameter references like `$1`
___
*[`pkg/sql/importer/import_processor.go` line 313 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/165129#-OnTmVO9ECaLFb7n2WlJ:-OnTmVO9ECaLFb7n2WlK:bv7ttb6) ([raw file](https://github.com/cockroachdb/cockroach/blob/88fc0328d5acfc7df622dda3cab97c3cd6767f43/pkg/sql/importer/import_processor.go#L313)):*
> ```Go
> 		// Release leases on any accessed descriptors now that the
> 		// resolver is configured. We do this so that leases are not
> 		// held for the entire import process.
> ```

Does this actually do anything, since the function resolver hasn't been used yet at this point?

Also a more general question: I know we do this for backfill, so not blocking. But is it correct to release leases while we're using these descriptors for routine evaluation or type casts?

**Review by mw5h — COMMENTED** [review]
> @mw5h made 4 comments.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/165129)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on DrewKimball and yuzefovich).

___
*[`-- commits` line 22 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/165129#-OncL2k_01HblSn9Kgcv:-OncL2k_01HblSn9Kgcw:b-4j28by):*
I think DrewK meant that this is not true. UDF-based computed column expressions succeed but are not backfill/import-able.
___
*[`pkg/sql/importer/read_import_base.go` line 90 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/165129#-OncMVy1C7Ub-EIT8nZH:-OncMVy1C7Ub-EIT8nZI:b2x0lfg) ([raw file](https://github.com/cockroachdb/cockroach/blob/0c1beaf9e94fa0f92294a9c47a431d720b1fbe18/pkg/sql/importer/read_import_base.go#L90)):*
> ```Go
> 	evalCtx := flowCtx.NewEvalCtx()
> 	evalCtx.Regions = makeImportRegionOperator(spec.DatabasePrimaryRegion)
> ```

Delete this blank line.
___
*[`pkg/sql/importer/read_import_base.go` line 92 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/165129#-OncMa3GAgRPnyxyLKzS:-OncMa3GAgRPnyxyLKzT:b29rgfu) ([raw file](https://github.com/cockroachdb/cockroach/blob/0c1beaf9e94fa0f92294a9c47a431d720b1fbe18/pkg/sql/importer/read_import_base.go#L92)):*
> ```Go
> 
> 	semaCtx := tree.MakeSemaContext(importResolver)
> 	conv, convErr := makeInputConverter(
> ```

I'm not seeing a reason to change the name of the error here.
___
*[`pkg/sql/importer/read_import_base.go` line 129 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/165129#-OncMsvO0ZEFHFlsVr6u:-OncMsvO0ZEFHFlsVr6v:b-mo2k9) ([raw file](https://github.com/cockroachdb/cockroach/blob/0c1beaf9e94fa0f92294a9c47a431d720b1fbe18/pkg/sql/importer/read_import_base.go#L129)):*
> ```Go
> 	// at the end is one row containing an encoded BulkOpSummary.
> 	var summary *kvpb.BulkOpSummary
> 	var err error
> ```

We shouldn't capture the error here, just return the error and let it propagate via the group.Wait() call.

**Comment by mw5h** [comment]
This should be RFAL.

**Review by mw5h — COMMENTED** [review]
> @mw5h made 6 comments and resolved 2 discussions.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/165129)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on DrewKimball and yuzefovich).

___
*[`-- commits` line 51 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/165129#-OnU-Fzj8sI3OTwAEpaE:-Onck6a_4N8cty4J2CE7:b-896fix):*
<details><summary><i>Previously, DrewKimball (Drew Kimball) wrote…</i></summary><blockquote>

I don't think this is true - on a demo cluster, I was able to create a computed column expression calling a UDF with multiple statements as well as one with a PL/pgSQL routine.
</blockquote></details>

Done.
___
*[`pkg/sql/catalog/schemaexpr/computed_column.go` line 433 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/165129#-OnTmzVkD97cNL06bJsk:-Onck8v-An4PPdmfGmo8:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/c79e1a81711caaa7369dd4227ff1cc068e032e4f/pkg/sql/catalog/schemaexpr/computed_column.go#L433)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

Should we be ignoring OUT parameters here? Is it possible to have a computed expression invoke a routine with OUT / INOUT parameters?
</blockquote></details>

Done.
___
*[`pkg/sql/catalog/schemaexpr/computed_column.go` line 439 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/165129#-OnTnle6Ah3wlCH1cbxt:-Onck9IdEjrsedz4LrPz:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/c79e1a81711caaa7369dd4227ff1cc068e032e4f/pkg/sql/catalog/schemaexpr/computed_column.go#L439)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

Should we do another walk over `bodyExpr` after the substitution to check that all parameter references have been replaced and returning an error if not?
</blockquote></details>

Done.
___
*[`pkg/sql/catalog/schemaexpr/computed_column.go` line 440 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/165129#-OnTvJ4i09AUOgHHrsLs:-Onck9oqBbXgUx8HJZig:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/c79e1a81711caaa7369dd4227ff1cc068e032e4f/pkg/sql/catalog/schemaexpr/computed_column.go#L440)):*
<details><summary><i>Previously, DrewKimball (Drew Kimball) wrote…</i></summary><blockquote>

I'm not sure this pattern will actually visit everything that could be in a UDF body. We should test parameter references in:
* Subquery
* The inputs + ON condition of a Join
* CTE
* GroupBy

We should also test:
* Nested routine calls
* Ordinal parameter references like `$1`
</blockquote></details>

Done.
___
*[`pkg/sql/logictest/testdata/logic_test/udf_unsupported` line 9 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/165129#-OnToz6q0uqP2c-SFDTX:-OnckBh343eOvqCuPlv3:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/c79e1a81711caaa7369dd4227ff1cc068e032e4f/pkg/sql/logictest/testdata/logic_test/udf_unsupported#L9)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

Should we introduce some new test cases for the errors with inlining the UDF and then move test cases that now work to another file (since this one is `udf_unsupported`)?
</blockquote></details>

Done.
___
*[`pkg/sql/importer/import_processor.go` line 313 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/165129#-OnTmVO9ECaLFb7n2WlJ:-OnckCo06wbMvYUdPalB:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/88fc0328d5acfc7df622dda3cab97c3cd6767f43/pkg/sql/importer/import_processor.go#L313)):*
<details><summary><i>Previously, DrewKimball (Drew Kimball) wrote…</i></summary><blockquote>

Does this actually do anything, since the function resolver hasn't been used yet at this point?

Also a more general question: I know we do this for backfill, so not blocking. But is it correct to release leases while we're using these descriptors for routine evaluation or type casts?
</blockquote></details>

Done.

**Review by yuzefovich — COMMENTED** [review]
> @yuzefovich reviewed 9 files and all commit messages, made 3 comments, and resolved 2 discussions.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/165129)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on DrewKimball and mw5h).

___
*[`pkg/sql/catalog/schemaexpr/computed_column.go` line 439 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/165129#-OnTnle6Ah3wlCH1cbxt:-OndF92G4dIH0OrUIpFe:bg23f44) ([raw file](https://github.com/cockroachdb/cockroach/blob/c79e1a81711caaa7369dd4227ff1cc068e032e4f/pkg/sql/catalog/schemaexpr/computed_column.go#L439)):*
<details><summary><i>Previously, mw5h (Matt White) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I don't see the check that all parameters have been replaced.
___
*[`pkg/sql/catalog/schemaexpr/computed_column.go` line 456 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/165129#-OndCo-XC6oiTjbXjdmi:-OndCo-XC6oiTjbXjdmj:b2gogax) ([raw file](https://github.com/cockroachdb/cockroach/blob/dd6ad2446a35ec1e53a3a113caf1353a08e8be53/pkg/sql/catalog/schemaexpr/computed_column.go#L456)):*
> ```Go
> 			}
> 			if i < len(funcExpr.Exprs) {
> 				paramMap[string(p.Name)] = funcExpr.Exprs[i]
> ```

It's allowed for a UDF to have unnamed parameters (i.e. `p.Name == ""`). Such unnamed IN parameters cannot be referenced in the body by name (only via $i notation which we currently don't support (#114701)), and there can be any number of unnamed parameters. The current logic probably doesn't handle the case of multiple unnamed IN parameters.
___
*[`pkg/sql/catalog/schemaexpr/computed_column.go` line 459 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/165129#-OndDu2h4XYLm36-dTip:-OndDu2h4XYLm36-dTiq:bhr8pa1) ([raw file](https://github.com/cockroachdb/cockroach/blob/dd6ad2446a35ec1e53a3a113caf1353a08e8be53/pkg/sql/catalog/schemaexpr/computed_column.go#L459)):*
> ```Go
> 			}
> 		}
> 		if len(paramMap) != len(funcExpr.Exprs) {
> ```

nit: it feels off to have the length check done after the loop given that in the loop we have bounds check on `i`, meaning that by construction `len(paramMap)` will never exceed `len(funcExpr.Exprs)` even if we have too many routine params.

**Review by mw5h — COMMENTED** [review]
> @mw5h made 3 comments and resolved 1 discussion.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/165129)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on DrewKimball and yuzefovich).

___
*[`pkg/sql/catalog/schemaexpr/computed_column.go` line 439 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/165129#-OnTnle6Ah3wlCH1cbxt:-OndTpxc4kJ3RdqA7dq7:bv8wy8j) ([raw file](https://github.com/cockroachdb/cockroach/blob/c79e1a81711caaa7369dd4227ff1cc068e032e4f/pkg/sql/catalog/schemaexpr/computed_column.go#L439)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

I don't see the check that all parameters have been replaced.
</blockquote></details>

Yeah, sorry, in the update I lost what this was referring to.
___
*[`pkg/sql/catalog/schemaexpr/computed_column.go` line 456 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/165129#-OndCo-XC6oiTjbXjdmi:-OndU-x4EdWjpKETbZBC:b-yvl7kh) ([raw file](https://github.com/cockroachdb/cockroach/blob/dd6ad2446a35ec1e53a3a113caf1353a08e8be53/pkg/sql/catalog/schemaexpr/computed_column.go#L456)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

It's allowed for a UDF to have unnamed parameters (i.e. `p.Name == ""`). Such unnamed IN parameters cannot be referenced in the body by name (only via $i notation which we currently don't support (#114701)), and there can be any number of unnamed parameters. The current logic probably doesn't handle the case of multiple unnamed IN parameters.
</blockquote></details>

Looks like $i notation works fine for SQL UDFs, just not PL/pgSQL.
___
*[`pkg/sql/catalog/schemaexpr/computed_column.go` line 459 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/165129#-OndDu2h4XYLm36-dTip:-OndU7XB69NLKl4MYkwO:b-pbdqz3) ([raw file](https://github.com/cockroachdb/cockroach/blob/dd6ad2446a35ec1e53a3a113caf1353a08e8be53/pkg/sql/catalog/schemaexpr/computed_column.go#L459)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

nit: it feels off to have the length check done after the loop given that in the loop we have bounds check on `i`, meaning that by construction `len(paramMap)` will never exceed `len(funcExpr.Exprs)` even if we have too many routine params.
</blockquote></details>

Agreed.

**Review by yuzefovich — APPROVED** [review]
Nice work! :lgtm: but might be worth waiting for Drew to take another look as well.

> @yuzefovich reviewed 4 files and all commit messages, made 2 comments, and resolved 3 discussions.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/165129#-:-OnyNDPyCwUrtJTPqdjh:bvn0qb1)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on DrewKimball and mw5h).

___
*[`pkg/sql/importer/read_import_base.go` line 92 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/165129#-OncMa3GAgRPnyxyLKzS:-OnyK1_4CMcg28pMoSaD:bcc3v7q) ([raw file](https://github.com/cockroachdb/cockroach/blob/0c1beaf9e94fa0f92294a9c47a431d720b1fbe18/pkg/sql/importer/read_import_base.go#L92)):*
<details><summary><i>Previously, mw5h (Matt White) wrote…</i></summary><blockquote>

I'm not seeing a reason to change the name of the error here.
</blockquote></details>

nit: maybe revert the change here (i.e. keep everything on a single line).

File: pkg/sql/catalog/schemaexpr/computed_column.go [hunk 1]
```diff
@@ -357,3 +367,187 @@ func MakeComputedExprs(
...
+	newExpr, err := tree.SimpleVisit(expr, func(e tree.Expr) (recurse bool, newExpr tree.Expr, err error) {
+		funcExpr, ok := e.(*tree.FuncExpr)
+		if !ok {
+			return true, e, nil
+		}
+		fn := funcExpr.ResolvedOverload()
+		if fn == nil || fn.Body == "" {
+			return true, e, nil
+		}
+		if fn.Language != tree.RoutineLangSQL {
```
Comment (DrewKimball) [inline pkg/sql/catalog/schemaexpr/computed_column.go:398]: We should probably also check for generator functions if that isn't already done elsewhere.

Comment (DrewKimball) [reply pkg/sql/catalog/schemaexpr/computed_column.go:398]: I'm also wondering if we're handling RECORD-returning routines correctly. We should test, or maybe just disallow for now.

**Review by DrewKimball — APPROVED** [review]
I have a few more suggestios for things to test/disallow, but beyond that LGTM.

File: pkg/sql/catalog/schemaexpr/computed_column.go (hunk 1 above)
Comment (mw5h) [reply pkg/sql/catalog/schemaexpr/computed_column.go:398]: Done — generators inside UDF bodies are now caught via `sanitizeExpr` (which uses `RejectSpecial`, including `RejectGenerators`). Additionally, we now validate at DDL time (CREATE TABLE / ALTER TABLE) by running `inlineUDFCalls` during expression validation, so all non-inlineable patterns (generators, multi-statement, PL/pgSQL, CTEs, subqueries, nested UDFs) are rejected upfront rather than failing during backfill.

Comment (mw5h) [reply pkg/sql/catalog/schemaexpr/computed_column.go:398]: RECORD-returning routines are handled — they return `tuple` type which never matches a valid column type, so they're rejected with a type mismatch error. Also, `RECORD` can't be used as a column type directly (`cannot use anonymous record type as table column`). Added a test for both cases.

Comment (mw5h) [reply pkg/sql/catalog/schemaexpr/computed_column.go:398]: This is RFAL when you get back.

Comment (mw5h) [reply pkg/sql/catalog/schemaexpr/computed_column.go:398]: Friendly ping @DrewKimball just in case you haven't seen this. I don't plan on backporting to 26.2, so no huge rush.

Comment (DrewKimball) [reply pkg/sql/catalog/schemaexpr/computed_column.go:398]: Sorry about that, this one slipped by me.

File: pkg/sql/logictest/testdata/logic_test/computed [hunk 2]
```diff
@@ -1531,3 +1531,275 @@ statement ok
...
+1  2
+2  4
+3  6
+4  8
+5  10
+
+# Strict UDFs (RETURNS NULL ON NULL INPUT) on a nullable column.
+# Rows with NULL input should produce NULL output.
+statement ok
+CREATE FUNCTION cc_udf_strict(x INT) RETURNS INT IMMUTABLE RETURNS NULL ON NULL INPUT LANGUAGE SQL AS $$ SELECT x + 100 $$;
```
Comment (DrewKimball) [inline pkg/sql/logictest/testdata/logic_test/computed]: nit: would be nice to use an expression that doesn't already return NULL on NULL input, like `CASE WHEN x IS NULL THEN -1 ELSE x + 100 END`

**Review by DrewKimball — APPROVED** [review]
Nice work! LGTM
