### PR TITLE
logictest: fix bug in upgrade directive

### LINKED ISSUE #100331: logictest: `query [types] nodeidx` does not seem to work as expected
[This test](https://github.com/cockroachdb/cockroach/pull/100221/files#diff-ff572f052a2c4f40cd4a964479b73e9119702d6df94374bdcec8c4146586d8a9) checks some queries made against a mixed version cluster. The summary of the test is that it generates 1 'query insight' into node 0 (22.2) and 1 query insight for node 1 (23.1), and checks that requesting cluster-wide insights in a mixed version cluster succeeds. 

Prior to applying the other changes in the patch,  line 66-67, which checks requesting cluster-wide insights using a 22.2 node in a mixed version state, should have caused a node panic. The test linked uses `user root nodeidx=i` to change which node to query from, but before that I was using `query [types] nodeidx=i`. Using nodeidx with query did not cause my test to fail as expected.  Only after switching all instances (except for checking the binary version in the beginning) to use `user root nodeidx` did the test fail.

Jira issue: CRDB-26374

### PR DESCRIPTION
**Pull request by andyyang890**
This patch fixes a subtle bug in the upgrade directive that would cause
the active database client to change to the newly upgraded node without
updating the `nodeIdx` recorded in the `logicTest` struct.

Fixes #100331

Release note: None

### CODE REVIEW

File: pkg/sql/logictest/logic.go [hunk 1]
```diff
@@ -3028,8 +3028,7 @@ func (t *logicTest) processSubtest(
 				}
 				delete(m, nodeIdx)
 			}
-			db := t.getOrOpenClient(t.user, nodeIdx)
-			t.db = db
+			t.setUser(t.user, nodeIdx)
```
Comment (rafiss) [inline pkg/sql/logictest/logic.go:3031]: do you think we should use 
```
			if t.nodeIdx == nodeIdx {
				t.setUser(t.user, nodeIdx)
			}
```

i could see people getting confused that `upgrade` changes the node you're connected to

**Review by rafiss — APPROVED** [review]
thanks, lgtm! i left a small nit

File: pkg/sql/logictest/logic.go (hunk 1 above)
Comment (andyyang890) [reply pkg/sql/logictest/logic.go]: Yeah, I agree that people might get confused if the node changes after an upgrade. Updated based on your suggestion!

**Comment by andyyang890** [comment]
bors r=rafiss
