### PR TITLE
streamingccl: add placeholder hint to fix c2c/kv0 flake

### LINKED ISSUE #94126: roachtest: c2c/kv0 failed
roachtest.c2c/kv0 [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyAwsBazel/8061576?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyAwsBazel/8061576?buildTab=artifacts#/c2c/kv0) on master @ [15bc0c4780681d95e705c22dbe2e7d8d190054ef](https://github.com/cockroachdb/cockroach/commits/15bc0c4780681d95e705c22dbe2e7d8d190054ef):

```
test artifacts and logs in: /artifacts/c2c/kv0/run_1
(test_impl.go:297).Fatalf: error scanning '&{0xc000f147e0 <nil>}': pq: crdb_internal.scan(): crdb_internal.tenant_span(): could not determine data type of placeholder $1
(1) pq: crdb_internal.scan(): crdb_internal.tenant_span(): could not determine data type of placeholder $1
Error types: (1) *pq.Error
(test_impl.go:291).Fatal: cluster.RunE: context canceled
```
<p>Parameters: <code>ROACHTEST_cloud=aws</code>
, <code>ROACHTEST_cpu=4</code>
, <code>ROACHTEST_encrypted=false</code>
, <code>ROACHTEST_fs=ext4</code>
, <code>ROACHTEST_localSSD=true</code>
, <code>ROACHTEST_ssd=0</code>
</p>
<details><summary>Help</summary>
<p>

See: [roachtest README](https://github.com/cockroachdb/cockroach/blob/master/pkg/cmd/roachtest/README.md)

See: [How To Investigate \(internal\)](https://cockroachlabs.atlassian.net/l/c/SSSBr8c7)

</p>
</details>
/cc @cockroachdb/disaster-recovery
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*c2c/kv0.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)
</sub>

Jira issue: CRDB-22700

### PR DESCRIPTION
**Pull request by msbutler**
Fixes #94126

Release note: None

### CODE REVIEW

File: pkg/cmd/roachtest/tests/cluster_to_cluster.go [hunk 1]
```diff
@@ -207,7 +207,7 @@ SELECT
         fnv64(crdb_internal.trim_tenant_prefix(key),
               substring(value from 5))
     ) AS fingerprint
-FROM crdb_internal.scan(crdb_internal.tenant_span($1))
+FROM crdb_internal.scan(crdb_internal.tenant_span($1::INT))
```
Comment (adityamaru) [inline pkg/cmd/roachtest/tests/cluster_to_cluster.go:210]: We should probably plumb the dst.name in and use that instead considering we're moving everything tenant related to be addressed by name, and generally change to using the new fingerprint method. In case you're feeling up to it, otherwise I can send out a patch separately.

**Review by adityamaru — APPROVED** [review]

File: pkg/cmd/roachtest/tests/cluster_to_cluster.go (hunk 1 above)
Comment (msbutler) [reply pkg/cmd/roachtest/tests/cluster_to_cluster.go:210]: I say let's address the immediate flake for now. I assume this whole function will get replaced once your fingerprint job is ready for large scale testing.

**Comment by msbutler** [comment]
bors r=adityamaru

File: pkg/cmd/roachtest/tests/cluster_to_cluster.go (hunk 1 above)
Comment (stevendanna) [reply pkg/cmd/roachtest/tests/cluster_to_cluster.go:210]: The advantage of having methods here that don't use the name is that if they don't need to look up the name then the function itself is a pretty clean utility function that is just constructing bytes rather than one that can fail.

Comment (adityamaru) [reply pkg/cmd/roachtest/tests/cluster_to_cluster.go:210]: >  this whole function will get replaced once your fingerprint job is ready for large scale testing

This switch can be made now, i'll send out a patch
