### PR TITLE
streamingccl: store replicated time in details

### LINKED ISSUE #103534: c2c: cutover is not resilient to node shutdown
If the coordinator node issuing revert range requests during cutover fails over, another node will be not able to resume the work. This occurs because the current implementation of cutover [uses](https://github.com/cockroachdb/cockroach/blob/master/pkg/ccl/streamingccl/streamingest/stream_ingestion_job.go#L682) the the job progress FractionCompleted oneOf f[ield](https://github.com/cockroachdb/cockroach/blob/53afe66d3d4d3b1647f3fcda73fe0e66833e81eb/pkg/jobs/jobspb/jobs.proto#L1299). Sadly, during regular ingestion, we use the progress high_water field, so when cutover begins, we write over the job progress's high water mark.

When a node then tries to resume cutover after the og coordinator dies, it can't, because it attempts to check the high water mark which is unreadible.

This was seen https://github.com/cockroachdb/cockroach/issues/103008#issuecomment-1549767358

Jira issue: CRDB-28065

Epic CRDB-25146

### PR DESCRIPTION
**Pull request by stevendanna**
The cutover process uses the progress field to record how many ranges need to be reverted. This, however, wipes out the high watermark that was previously stored in that progress field.

Here, we move the canonical copy of the high watermark to the progress details.

For clarity, we rename "high watermark" as "replicated time".

Further, we delete a long skipped test that isn't providing much value.

Fixes #103534

Epic: none

Release note: None

### CODE REVIEW

File: pkg/ccl/streamingccl/streamingest/stream_ingestion_job_test.go [hunk 1]
```diff
@@ -261,27 +261,39 @@ func TestCutoverBuiltin(t *testing.T) {
...
+			return err
+		}
+		replicatedTime = timeutil.Now().Round(time.Microsecond)
+		hlcReplicatedTime := hlc.Timestamp{WallTime: replicatedTime.UnixNano()}
+
+		progress := md.Progress
+		streamProgress := progress.Details.(*jobspb.Progress_StreamIngest).StreamIngest
+		streamProgress.ReplicatedTime = hlcReplicatedTime
+		progress.Progress = &jobspb.Progress_HighWater{
+			HighWater: &hlcReplicatedTime,
```
Comment (msbutler) [inline pkg/ccl/streamingccl/streamingest/stream_ingestion_job_test.go:276]: as I've said elsewhere, I wonder if we should not record the HighWater in Progress.

File: pkg/ccl/streamingccl/streamingest/stream_ingestion_job_test.go [hunk 2]
```diff
@@ -461,7 +473,17 @@ func TestCutoverFractionProgressed(t *testing.T) {
...
 	require.NoError(t, replicationJob.NoTxn().Update(ctx, func(txn isql.Txn, md jobs.JobMetadata, ju *jobs.JobUpdater) error {
-		return jobs.UpdateHighwaterProgressed(cutover, md, ju)
+		if err := md.CheckRunningOrReverting(); err != nil {
+			return err
+		}
+		progress := md.Progress
+		streamProgress := progress.Details.(*jobspb.Progress_StreamIngest).StreamIngest
+		streamProgress.ReplicatedTime = cutover
+		progress.Progress = &jobspb.Progress_HighWater{
+			HighWater: &cutover,
```
Comment (msbutler) [inline pkg/ccl/streamingccl/streamingest/stream_ingestion_job_test.go:483]: nit: highWater log alert.

File: pkg/ccl/streamingccl/streamingest/stream_ingestion_processor.go [hunk 3]
```diff
@@ -1156,25 +1157,54 @@ type cutoverProvider interface {
...
 		return false, err
 	}
-	progress := j.Progress()
-	var sp *jobspb.Progress_StreamIngest
-	var ok bool
-	if sp, ok = progress.GetDetails().(*jobspb.Progress_StreamIngest); !ok {
-		return false, errors.Newf("unknown progress type %T in stream ingestion job %d",
-			j.Progress().Progress, c.jobID)
+	if ingestionProgress == nil {
+		log.Warningf(ctx, "no legacy job progress recorded yet")
```
Comment (msbutler) [inline pkg/ccl/streamingccl/streamingest/stream_ingestion_processor.go:1201]: when would this occur? Like before the job info table migration? If you don't know off the top of your head, I can do some digging.

**Review by msbutler — COMMENTED** [review]
thanks for doing this! I think the only thing I'm unsure about is if we should even continue logging the hwm. I don't think we should as it opens the door to footguns, but curious why you think we should.

**Review by msbutler — COMMENTED** [review]
thanks for doing this! I think the only thing I'm unsure about is if we should even continue logging the hwm. I don't think we should as it opens the door to footguns, but curious why you think we should.

**Comment by stevendanna** [comment]
@msbutler My only hesitation about removing the high watermark completely is that it allows it to be visible in DBConsole, but I agree it is a bit of a footgun.

**Comment by msbutler** [comment]
> it allows it to be visible in DBConsole

Ah I see. FWIW, I hadn't even realized the dbconsole shows the hwm. I feel its fine to drop it from the the db console. It's a time series metric anyway, and I think the replication lag graph provides richer information.

one other thing: I think there's some roachtest code you'll need to update as well.

File: pkg/ccl/streamingccl/streamingest/stream_ingestion_processor.go (hunk 3 above)
Comment (stevendanna) [reply pkg/ccl/streamingccl/streamingest/stream_ingestion_processor.go:1201]: I would hope the only happen is during the migration which shouldn't really be that relevant for us.

File: pkg/ccl/streamingccl/streamingest/stream_ingestion_frontier_processor.go [hunk 4]
```diff
@@ -418,17 +419,20 @@ func (sf *streamIngestionFrontier) maybeUpdatePartitionProgress() error {
...
-			progress.Progress = &jobspb.Progress_HighWater{
-				HighWater: &highWatermark,
-			}
-		}
-
 		streamProgress := progress.Details.(*jobspb.Progress_StreamIngest).StreamIngest
 		streamProgress.PartitionProgress = partitionProgress
 		streamProgress.Checkpoint.ResolvedSpans = frontierResolvedSpans
 
+		// Keep the recorded replicatedTime empty until some advancement has been made
```
[the remark this answers is not in the document]
Comment (stevendanna) [reply pkg/ccl/streamingccl/streamingest/stream_ingestion_frontier_processor.go:426]: It needed to be under the definition of streamProgress so that we could be sure to set both at the same time.

File: pkg/ccl/streamingccl/streamingest/stream_ingestion_job.go [hunk 5]
```diff
@@ -307,16 +303,18 @@ func ingestWithRetries(
...
 		const msgFmt = "stream ingestion waits for retrying after error: %s"
 		log.Warningf(ctx, msgFmt, err)
-		updateRunningStatus(ctx, execCtx, ingestionJob, jobspb.ReplicationError,
+		updateRunningStatus(ctx, ingestionJob, jobspb.ReplicationError,
 			fmt.Sprintf(msgFmt, err))
 		retryCount++
 	}
 	if err != nil {
-		return err
+		updateRunningStatus(ctx, ingestionJob, jobspb.ReplicationError,
```
[the remark this answers is not in the document]
Comment (stevendanna) [reply pkg/ccl/streamingccl/streamingest/stream_ingestion_job.go:311]: I'l remove this. I was doing the rebase quickly and just didn't look carefully at this one.

**Comment by stevendanna** [comment]
Updated the roachtests and addressed comments other than the high watermark issue.  Going to spend a few minutes looking into the ux differences

**Comment by msbutler** [comment]
one more nit: update the commit/PR message to Fix the original issue? https://github.com/cockroachdb/cockroach/issues/103534

**Comment by stevendanna** [comment]
> hrm, I don't see any updates to pkg/cmd/roachtest/tests/cluster_to_cluster.go ?

Should be here: https://github.com/cockroachdb/cockroach/pull/103835/files#diff-b713f571096d10de2fe8f435442a825c8b41faaa685a6606a8432a61cf663f02

File: pkg/cmd/roachtest/tests/cluster_to_cluster.go [hunk 6]
```diff
@@ -1135,13 +1133,16 @@ func getIngestionJobID(t test.Test, dstSQL *sqlutils.SQLRunner, dstTenantName st
...
+	status         string
+	errMsg         string
+	replicatedTime time.Time
+	finishedTime   time.Time
 }
 
-func (c *streamIngesitonJobInfo) GetHighWater() time.Time    { return c.highwaterTime }
+// GetHighWater returns the replicated time. The GetHighWater name is
+// retained here as this is implementing the jobInfo interface used by
+// the latency verifier.
```
Comment (msbutler) [inline pkg/cmd/roachtest/tests/cluster_to_cluster.go:1144]: alas.

**Review by msbutler — APPROVED** [review]

**Comment by msbutler** [comment]
unrelated flake, logged issue[ here](https://github.com/cockroachdb/cockroach/issues/103896).

**Comment by msbutler** [comment]
bors retry
