### PR TITLE
roachprod: add VM reset to failure injection framework

### LINKED ISSUE #147361: roachtest: add VM restart regression test
Recent refactoring of the startup script made it non-idempotent; i.e., subsequent invocation(s) resulted in a failure. While [1] addresses the immediate fix, we're missing a regression test across all supported (cloud) providers.

[1] https://github.com/cockroachdb/cockroach/pull/147017

Jira issue: CRDB-51017

### PR DESCRIPTION
**Pull request by herkolategan**
This PR adds VM reset functionality to the failure injection framework, allowing for controlled node resets during testing.

1. Updated `roachprod` reset command to operate on a subset of nodes instead of all nodes
2. Implemented a new reset-vm failure mode that:
   - Captures running processes before reset
   - Resets specified nodes
   - Restarts processes after reset
3. Added smoke tests to validate the reset failure mode

Fixes: #147361

Epic: None
Release note: None

### CODE REVIEW

File: pkg/cmd/roachtest/tests/failure_injection.go [hunk 1]
```diff
@@ -596,6 +597,48 @@ var dmsetupDiskStallTest = func(c cluster.Cluster) failureSmokeTest {
...
+	rng, _ := randutil.NewPseudoRand()
+	rebootedNode := c.CRDBNodes().SeededRandNode(rng)
+	return failureSmokeTest{
+		testName:    failures.ResetVMFailureName,
+		failureName: failures.ResetVMFailureName,
+		args: failures.ResetVMArgs{
+			Nodes: rebootedNode.InstallNodes(),
+		},
+		validateFailure: func(ctx context.Context, l *logger.Logger, c cluster.Cluster, f *failures.Failer) error {
+			// Check that we aren't able to establish a SQL connection to the rebooted node.
```
Comment (DarrylWong) [inline pkg/cmd/roachtest/tests/failure_injection.go:739]: Was debating just allowing a smoke test to have a nil `validateFailure` when I wrote the process kill failure. Looks like we have two failure modes now that want to skip it so I should probably go ahead and do it 😃

File: pkg/roachprod/failureinjection/failures/reset.go [hunk 2]
```diff
@@ -0,0 +1,123 @@
...
+	"github.com/cockroachdb/cockroach/pkg/roachprod"
+	"github.com/cockroachdb/cockroach/pkg/roachprod/install"
+	"github.com/cockroachdb/cockroach/pkg/roachprod/logger"
+)
+
+type (
+	ResetVMArgs struct {
+		Nodes install.Nodes
+	}
+	resetVMFailure struct {
```
Comment (DarrylWong) [inline pkg/roachprod/failureinjection/failures/reset.go:21]: nit: `Failure` seems redundant since it's part of the `failures` package and implements `FailureMode`. Open to hearing a differing opinion though.

Comment (DarrylWong) [reply pkg/roachprod/failureinjection/failures/reset.go:21]: Oh 🤦 it appears I'm not consistent in naming myself. I'm guessing you based this failure on the `ProcessKillFailure` which also has the post fix.

I do see the argument that since we have `${FailureMode}Args`, `${FailureMode}Failure` makes sense. If anyone has a strong opinion, let me know since I don't 😃

File: pkg/roachprod/failureinjection/failures/reset.go [hunk 3]
```diff
@@ -0,0 +1,123 @@
...
+	return nil
+}
+
+// Recover implements FailureMode.
+func (r *resetVMFailure) Recover(ctx context.Context, l *logger.Logger, args FailureArgs) error {
+	// Restart the processes.
+	for node, processes := range r.Processes {
+		for _, p := range processes {
+			l.Printf("Restarting process %s on node %s", p.PID, p.VirtualClusterName)
+			err := r.c.WithNodes([]install.Node{node}).Start(ctx, l, install.StartOpts{
```
Comment (DarrylWong) [inline pkg/roachprod/failureinjection/failures/reset.go:84]: For a multitenant deployment, does this make sure to restart the system interface first before any secondary tenants? I'm not seeing any ordering guarantees on the `monitorChan`.

I think it's fine for now, since the rest of the framework doesn't support multitenant clusters yet. Just mostly asking since I do want to support it soon.

**Review by DarrylWong — APPROVED** [review]
Thanks for doing this in the failure injection framework, much appreciated to have another set of eyes!

Left a few comments but nothing that I think needs to be changed in this PR.

File: pkg/roachprod/failureinjection/failures/reset.go (hunk 2 above)
Comment (herkolategan) [reply pkg/roachprod/failureinjection/failures/reset.go:21]: No strong opinion here either, we could always rename later if required.

File: pkg/roachprod/failureinjection/failures/reset.go (hunk 3 above)
Comment (herkolategan) [reply pkg/roachprod/failureinjection/failures/reset.go:84]: > For a multitenant deployment, does this make sure to restart the system interface first before any secondary tenants? I'm not seeing any ordering guarantees on the monitorChan.

Good point, I wonder what CRDB does if we restart these out of order. It might be a failure of another kind. I'll check the docs a bit, and maybe have system start first.

**Review by golgeek — APPROVED** [review]

File: pkg/roachprod/failureinjection/failures/reset.go [hunk 4]
```diff
@@ -0,0 +1,123 @@
...
+
+// Cleanup implements FailureMode.
+func (r *resetVMFailure) Cleanup(ctx context.Context, l *logger.Logger, args FailureArgs) error {
+	return nil
+}
+
+// Recover implements FailureMode.
+func (r *resetVMFailure) Recover(ctx context.Context, l *logger.Logger, args FailureArgs) error {
+	// Restart the processes.
+	for node, processes := range r.Processes {
```
Comment (srosenberg) [inline pkg/roachprod/failureinjection/failures/reset.go:81]: This looks like a data race. `r.Processes` could be updated concurrently with the iterator. This reminded me of [1].

[1] https://github.com/cockroachdb/cockroach/issues/143550

File: pkg/roachprod/failureinjection/failures/reset.go [hunk 5]
```diff
@@ -0,0 +1,123 @@
...
+		for _, p := range processes {
+			l.Printf("Restarting process %s on node %s", p.PID, p.VirtualClusterName)
```
Comment (srosenberg) [inline pkg/roachprod/failureinjection/failures/reset.go]: Nit: "Starting" since presumably VM reset would have stopped them.

File: pkg/roachprod/failureinjection/failures/reset.go [hunk 6]
```diff
@@ -0,0 +1,123 @@
...
+	r.Processes = make(map[install.Node][]install.MonitorProcessRunning, 0)
+	go func() {
+		for e := range monitorChan {
+			if p, ok := e.Event.(install.MonitorProcessRunning); ok {
+				r.Processes[e.Node] = append(r.Processes[e.Node], p)
+			}
+		}
+	}()
+
+	return r.c.WithNodes(nodes).Reset(l)
```
Comment (srosenberg) [inline pkg/roachprod/failureinjection/failures/reset.go:70]: This will be an interesting injector to run because it has a non-zero chance of causing data corruption [1],

> Reset an instance only if the guest OS has crashed or is unresponsive, and you have no other options. Resetting an instance doesn't allow the guest OS to cleanly shut down. This action can discard unsaved data and might corrupt the file systems of any disks.

To reduce flakiness, we probably want to add the option to stop the crdb process before resetting the VM.

[1] https://cloud.google.com/compute/docs/instances/reset-instance

File: pkg/roachprod/failureinjection/failures/reset.go (hunk 4 above)
Comment (herkolategan) [reply pkg/roachprod/failureinjection/failures/reset.go:81]: This made me realise I have a goroutine that populates `r.Processes`, but there shouldn't be a goroutine.
```
	r.Processes = make(map[install.Node][]install.MonitorProcessRunning, 0)
	go func() {
		for e := range monitorChan {
			if p, ok := e.Event.(install.MonitorProcessRunning); ok {
				r.Processes[e.Node] = append(r.Processes[e.Node], p)
			}
		}
	}()
```
Not entirely sure why I added it, since the monitor is one-shot, it should populate the channel and terminate it, hence no goroutine required.

**Comment by herkolategan** [comment]
Added a different issue to address start order and process management options.

TFTRs!

bors r=DarrylWong,golgeek
