### PR TITLE
importccl: fix bug when rolling back imports with no timestamp

### LINKED ISSUE #59481: importccl: IMPORT INTO may leave descriptors in OFFLINE state
**Describe the problem**

There have been reports of IMPORT INTO jobs failing to bring OFFLINE descriptors back to a PUBLIC state. The OnFailOrCancel hook is failing since it is claiming that the import timestamp is not set on the job.

**To Reproduce**

Reproduction steps not yet identified.

**Expected behavior**
The IMPORT timestamp should always be set once the descriptors have been set to OFFLINE.

### PR DESCRIPTION
**Pull request by pbardea**
If a timestamp for the import was not chosen, there should be no
ingested data to rollback. However, we do want to continue with the
IMPORT cleanup to bring any OFFLINE tables back to PUBLIC.

Fixes https://github.com/cockroachdb/cockroach/issues/59481.

Release note (bug fix): Fixes a bug where some import failures would
cause tables to stay OFFLINE, when they should have been brough back to
PUBLIC.

### CODE REVIEW

File: pkg/ccl/importccl/import_stmt.go [hunk 1]
```diff
@@ -1435,6 +1435,14 @@ func (r *importResumer) Resume(ctx context.Context, execCtx interface{}) error {
 		// Now that we know all the tables are offline, pick a walltime at which we
 		// will write.
 		details.Walltime = p.ExecCfg().Clock.Now().WallTime
+		// Update the job details as soon as we've chosen a timestamp. We don't wait
+		// until below to be defensive against hard-to-reason state where the
+		// details' timestamp is not set.
+		// We have seen the scan below hang in some states, which may cause and
+		// import failure.
+		if err := r.job.WithTxn(nil).SetDetails(ctx, details); err != nil {
```
Comment (dt) [inline pkg/ccl/importccl/import_stmt.go:1443]: I don't think we need this one considering the change to when we revert. If we happen to error-out during WasEmpty checks, we actually would prefer, with your other change, to fast-skip the reverts since we never ingested?

Comment (pbardea) [reply pkg/ccl/importccl/import_stmt.go]: Agreed. Sitting on it longer, it seems like this would actually be worse, as you said. Removed this commit.

**Review by dt — APPROVED** [review]

**Comment by pbardea** [comment]
TFTR!
bors r=dt
