### PR TITLE
urlcheck: skip for pre-release and customized versions

### LINKED ISSUE #142883: testutils/lint: TestNightlyLint failed
testutils/lint.TestNightlyLint [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_LintURLsBazel/19100007?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_LintURLsBazel/19100007?buildTab=artifacts#/) on master @ [ccc3f31caec8193d217ce6866dfb3757c1ca47f6](https://github.com/cockroachdb/cockroach/commits/ccc3f31caec8193d217ce6866dfb3757c1ca47f6):

```
             1963:  https://www.cockroachlabs.com/docs/v25.2/alter-view.html
        https://www.cockroachlabs.com/docs/v25.2/alter-database.html : 404 Not Found
             772:  https://www.cockroachlabs.com/docs/v25.2/alter-database.html
        https://www.cockroachlabs.com/docs/v25.2/table-expressions.html : 404 Not Found
             487:  https://www.cockroachlabs.com/docs/v25.2/table-expressions.html
             673:  https://www.cockroachlabs.com/docs/v25.2/table-expressions.html
             1332:  https://www.cockroachlabs.com/docs/v25.2/table-expressions.html
             1523:  https://www.cockroachlabs.com/docs/v25.2/table-expressions.html
             1579:  https://www.cockroachlabs.com/docs/v25.2/table-expressions.html
             1804:  https://www.cockroachlabs.com/docs/v25.2/table-expressions.html
             2065:  https://www.cockroachlabs.com/docs/v25.2/table-expressions.html
        https://www.cockroachlabs.com/docs/v25.2/alter-table.html : 404 Not Found
             979:  https://www.cockroachlabs.com/docs/v25.2/alter-table.html
        https://www.cockroachlabs.com/docs/v25.2/drop-function.html : 404 Not Found
             1638:  https://www.cockroachlabs.com/docs/v25.2/drop-function.html
        https://www.cockroachlabs.com/docs/v25.2/show-index.html : 404 Not Found
             1251:  https://www.cockroachlabs.com/docs/v25.2/show-index.html
        https://www.cockroachlabs.com/docs/v25.2/show-databases.html : 404 Not Found
             1694:  https://www.cockroachlabs.com/docs/v25.2/show-databases.html
        https://www.cockroachlabs.com/docs/v25.2/savepoint.html : 404 Not Found
             430:  https://www.cockroachlabs.com/docs/v25.2/savepoint.html
             2348:  https://www.cockroachlabs.com/docs/v25.2/savepoint.html
        https://www.cockroachlabs.com/docs/v25.2/show-columns.html : 404 Not Found
             1458:  https://www.cockroachlabs.com/docs/v25.2/show-columns.html
        https://www.cockroachlabs.com/docs/v25.2/create-table-as.html : 404 Not Found
             1528:https://www.cockroachlabs.com/docs/v25.2/create-table-as.html
        https://www.cockroachlabs.com/docs/v25.2/show-vars.html : 404 Not Found
             1014:  https://www.cockroachlabs.com/docs/v25.2/show-vars.html
             1127:  https://www.cockroachlabs.com/docs/v25.2/show-vars.html
        https://www.cockroachlabs.com/docs/v25.2/alter-partition.html : 404 Not Found
             1199:  https://www.cockroachlabs.com/docs/v25.2/alter-partition.html
        https://www.cockroachlabs.com/docs/v25.2/show-create.html : 404 Not Found
             839:  https://www.cockroachlabs.com/docs/v25.2/show-create.html
        https://www.cockroachlabs.com/docs/v25.2/show-default-privileges : 404 Not Found
             1043:  https://www.cockroachlabs.com/docs/v25.2/show-default-privileges
        https://www.cockroachlabs.com/docs/v25.2/select-clause.html : 404 Not Found
             1580:  https://www.cockroachlabs.com/docs/v25.2/select-clause.html
        https://www.cockroachlabs.com/docs/v25.2/import-into.html : 404 Not Found
             798:  https://www.cockroachlabs.com/docs/v25.2/import-into.html
        https://www.cockroachlabs.com/docs/v25.2/grant.html : 404 Not Found
             320:  https://www.cockroachlabs.com/docs/v25.2/grant.html
        https://www.cockroachlabs.com/docs/v25.2/drop-index.html : 404 Not Found
             174:  https://www.cockroachlabs.com/docs/v25.2/drop-index.html
             1992:  https://www.cockroachlabs.com/docs/v25.2/drop-index.html
        https://www.cockroachlabs.com/docs/v25.2/alter-index.html : 404 Not Found
             522:  https://www.cockroachlabs.com/docs/v25.2/alter-index.html
        https://www.cockroachlabs.com/docs/v25.2/set-transaction.html : 404 Not Found
             1118:https://www.cockroachlabs.com/docs/v25.2/set-transaction.html
        54 errors
--- FAIL: TestNightlyLint/TestHelpURLs (1.16s)
```
<details><summary>Help</summary>
<p>

See also: [How To Investigate a Go Test Failure \(internal\)](https://cockroachlabs.atlassian.net/l/c/HgfXfJgM)
</p>
</details>
/cc @cockroachdb/test-eng
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*TestNightlyLint.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/bazci/githubpost/issues)

</sub>

Jira issue: CRDB-48562

### PR DESCRIPTION
**Pull request by rail**
Previously, the urllint tool would use the production URLs for alphas and betas. The current SLA is to have the final URLs ready only for the GA version.

This commit makes the test skipped for pre-release and customized versions.

Release note: none
Fixes: #142883

### CODE REVIEW

**Review by celiala — APPROVED** [review]
LGTM - thanks for fixing!

File: pkg/build/info.go [hunk 1]
```diff
@@ -112,8 +112,8 @@ func BinaryVersion() string {
 func VersionForURLs() string {
 	if parsedVersionTxt.IsPrerelease() {
 		phaseAndOrdinal := parsedVersionTxt.Format("%P.%o")
-		// builds prior to "alpha.1" use 'dev' in their URLs
-		if phaseAndOrdinal < "alpha.1" {
+		// builds prior to "rc.1" use 'dev' in their URLs
+		if phaseAndOrdinal < "rc.1" {
```
Comment (celiala) [inline pkg/build/info.go:116]: actually...  rc.1 is also a test release (also shipped before GA) -- so maybe conditional should be more like below?

```
if phaseAndOrdinal <= "rc.5" {
...
```

**Comment by DarrylWong** [comment]
I'll defer stamping to Celia, but thank you for fixing!

File: pkg/build/info.go (hunk 1 above)
Comment (rail) [reply pkg/build/info.go:116]: I was not sure what version to use. "rc.5" sounds extreme, maybe better to use "dev" for all pre-release versions then? At least it would be clearer comparing to "rc.5".

Comment (rail) [reply pkg/build/info.go]: It's even simpler: `if parsedVersionTxt.IsPrerelease() || parsedVersionTxt.IsCustomOrNightlyBuild()`

Comment (celiala) [reply pkg/build/info.go]: > It's even simpler: if parsedVersionTxt.IsPrerelease() || parsedVersionTxt.IsCustomOrNightlyBuild()
nice! works for me - thank you!

**Review by celiala — APPROVED** [review]
LGTM! thank you!

**Comment by rail** [comment]
bors r=celiala

**Comment by rail** [comment]
bors cancel

**Comment by rail** [comment]
This change affects some tests, that rely on the value:
```
=== RUN   TestTenantLogic_create_table/end#08
    logic.go:2733: 
         
        /var/lib/engflow/worker/work/0/exec/bazel-out/k8-fastbuild/bin/pkg/ccl/logictestccl/tests/3node-tenant/3node-tenant_test_/3node-tenant_test.runfiles/com_github_cockroachdb_cockroach/pkg/sql/logictest/testdata/logic_test/create_table:1232: 
        expected:
        pq: unimplemented: column col2 has type refcursor, which is not indexable\nHINT: You have attempted to use a feature that is not yet implemented.\nSee: https://go.crdb.dev/issue-v/35730/v25.2
        got:
        pq: unimplemented: column col2 has type refcursor, which is not indexable
        HINT: You have attempted to use a feature that is not yet implemented.
        See: https://go.crdb.dev/issue-v/35730/dev
--- FAIL: TestTenantLogic_create_table/end#08 (0.00s)
```

**Comment by rail** [comment]
I'm going to take another approach here: skip the test for pre-release versions.

**Review by celiala — APPROVED** [review]

**Comment by rail** [comment]
bors r=celiala
