### PR TITLE
ui: insights transaction details support multiple blocking transactions

### LINKED ISSUE #88264: Insights transactions details shows only 1 blocking txn
It's possible that a single transaction can be blocked by multiple transactions. The insights transaction details page and sql activity active transaction details page only show one blocking transaction. It could be blocked on completely different table and statements. This might make it challenging as the current ui makes the assumption there would only ever be 1 blocked schema/database/table.

This shows that there are 2 txn ids blocking 8a5f..
Screen Shot 2022-09-20 at 1 17 17 PM

The insights transaction details page only shows first blocking txn id instead of both in the table.
Screen Shot 2022-09-20 at 1 17 53 PM

To reproduce:
Session1:
```sql
CREATE TABLE t (id string, s string);
begin;
INSERT INTO t (id, s) VALUES ('234', 'valueSession1');
```

Session2:
```sql
begin;
UPDATE t SET s = 'valueSession2' where id = '2345';
```

Wait several seconds then continue:
Session1:
```sql
end;
```

Session3:
```sql
UPDATE t SET s = 'valueSession3' where id = '2345';
```
Wait several seconds then continue:
Session2:
```sql
end;
```

Jira issue: CRDB-19754

### PR DESCRIPTION
**Pull request by j82w**
This adds support for multiple blocking transactions for a single waiting transaction. The cards were merged into the table, and the data was piped through to show multiple rows. The total contention time was also fixed to aggregate the contention time instead of just picking the latest.

before:
https://loom.com/share/0384ed937a344e2fb0105fefbc313acb

after:
https://www.loom.com/share/78e906f50a694cd59ac893ddb9c2239a

closes #88264

Release justification: Category 2: Bug fixes and
low-risk updates to new functionality

Release note: (ui change): Add support for multiple
 blocking transaction on insights transaction
 details page. Merged the cards into the table,
 and fixed the total contention time.

### CODE REVIEW

**Review by ericharmeling — APPROVED** [review]
> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/88454)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @j82w)

___
*[`pkg/ui/workspaces/cluster-ui/src/insights/workloadInsights/util/insightsColumns.tsx` line 108 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/88454#-NC_Xlxk4TKgpWcuiJTU:-NC_Xlxk4TKgpWcuiJTV:bc3aqr8) ([raw file](https://github.com/cockroachdb/cockroach/blob/eed0fa4ea23d3c6b6c40d5f4c9e41b9983e6fc16/pkg/ui/workspaces/cluster-ui/src/insights/workloadInsights/util/insightsColumns.tsx#L108)):*
> ```XML
>   contentionStartTime: (execType: InsightExecEnum) => {
>     return makeToolTip(
>       <p>The timestamp at which the contention started for the {execType}.</p>,
> ```

nit: I believe this collection TS is just when the contention is detected.



_Suggestion:_
```XML
The timestamp at which contention was detected for the {execType}.
```
___
*[`pkg/ui/workspaces/cluster-ui/src/insights/workloadInsights/util/insightsColumns.tsx` line 126 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/88454#-NC_YDXn7Rm7GZ3H98mn:-NC_YDXn7Rm7GZ3H98mo:b-1gyp45) ([raw file](https://github.com/cockroachdb/cockroach/blob/eed0fa4ea23d3c6b6c40d5f4c9e41b9983e6fc16/pkg/ui/workspaces/cluster-ui/src/insights/workloadInsights/util/insightsColumns.tsx#L126)):*
> ```XML
>   schemaName: (execType: InsightExecEnum) => {
>     return makeToolTip(
>       <p>The schema name of the {execType} that had contention.</p>,
> ```

nit: executions don't belong to a particular schema/database/table



_Suggestion:_
```XML
  },
  schemaName: (execType: InsightExecEnum) => {
    return makeToolTip(
      <p>The name of the contended schema.</p>,
      "schemaName",
    );
  },
  databaseName: (execType: InsightExecEnum) => {
    return makeToolTip(
      <p>The name of the contended database.</p>,
      "databaseName",
    );
  },
  tableName: (execType: InsightExecEnum) => {
    return makeToolTip(
      <p>The name of the contended table.</p>,
      "tableName",
    );
  },
```

**Review by ericharmeling — APPROVED** [review]
Very nice! Thank you for making this change. I had a few comments, but they are admittedly a bit pedantic.

@stbof This could affect documentation for the insights details page.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/88454#-:-NC_ZPY7545ZQ5dj_8Ez:b-5e684n)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @j82w)

**Review by maryliag — APPROVED** [review]
Nice changes! :lgtm: 

> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/88454#-:-NC__h1vEzAHLPwTPhuh:b-cwsp2o)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @j82w)

**Comment by kevin-v-ngo** [comment]
Hi @j82w, I thought we had index as well? Or is that coming in another PR?

**Comment by j82w** [comment]
That was not in the original page. @ericharmeling is there a reason it does not display the index?

**Comment by kevin-v-ngo** [comment]
Got it. Let me know if this isn't being tracked. I can file an issue.

File: pkg/ui/workspaces/cluster-ui/src/insights/workloadInsights/util/insightsColumns.tsx [hunk 1]
```diff
@@ -111,6 +121,18 @@ export const insightsTableTitles: InsightsTableTitleType = {
...
+  databaseName: (execType: InsightExecEnum) => {
+    return makeToolTip(
+      <p>The name of the contended database.</p>,
+      "databaseName",
+    );
+  },
+  tableName: (execType: InsightExecEnum) => {
+    return makeToolTip(<p>The name of the contended table.</p>, "tableName");
+  },
   applicationName: (execType: InsightExecEnum) => {
```
Comment (ericharmeling) [inline pkg/ui/workspaces/cluster-ui/src/insights/workloadInsights/util/insightsColumns.tsx:136]: @j82w @kevin-v-ngo 
>  is there a reason it does not display the index?

The `WaitTimeInsightsPanel` displays a contended secondary index if there is one:

https://github.com/cockroachdb/cockroach/blob/master/pkg/ui/workspaces/cluster-ui/src/detailsPanels/waitTimeInsightsPanel.tsx#L114

If there isn't one, then it won't display it. We probably want an `indexName` column in the blocking transactions table too, but that value might be blank.

Comment (kevin-v-ngo) [reply pkg/ui/workspaces/cluster-ui/src/insights/workloadInsights/util/insightsColumns.tsx:136]: Is there a reason why we wouldn't have a contended index? And even key/row span? I thought contention would always be at the key level?

**Review by maryliag — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/88454)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @ericharmeling, @j82w, and @maryliag)

___
*[`pkg/ui/workspaces/cluster-ui/src/insights/workloadInsights/util/insightsColumns.tsx` line 136 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/88454#-NC_V5jETd3-fChu27rZ-r2-136:-NC_kbr9EW89rFgcYBGN:baollqe) ([raw file](https://github.com/cockroachdb/cockroach/blob/a53e0774dcb48047e6ba9a62d95098011a072db5/pkg/ui/workspaces/cluster-ui/src/insights/workloadInsights/util/insightsColumns.tsx#L136)):*
<details><summary><i>Previously, kevin-v-ngo wrote…</i></summary><blockquote>

Is there a reason why we wouldn't have a contended index? And even key/row span? I thought contention would always be at the key level?
</blockquote></details>

We don't always have a contended index because there might not be an index. For the key we removed that recently to make this page more user friendly
https://github.com/cockroachdb/cockroach/pull/87645

File: pkg/ui/workspaces/cluster-ui/src/insights/workloadInsights/util/insightsColumns.tsx (hunk 1 above)
Comment (ericharmeling) [reply pkg/ui/workspaces/cluster-ui/src/insights/workloadInsights/util/insightsColumns.tsx:136]: @kevin-v-ngo 

> Is there a reason why we wouldn't have a contended index?

I think that depends on the query. 

> And even key/row span? I thought contention would always be at the key level?

We remove the contended key from the txn insight details page. 

Discussion thread:
https://cockroachlabs.slack.com/archives/G01Q9D01NTU/p1662676417756419?thread_ts=1662662201.540079&cid=G01Q9D01NTU

PR:
https://github.com/cockroachdb/cockroach/pull/87645

**Comment by j82w** [comment]
*[`pkg/ui/workspaces/cluster-ui/src/insights/workloadInsights/util/insightsColumns.tsx` line 136 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/88454#-NC_V5jETd3-fChu27rZ-r2-136:-NC_ml3Y5Kep7wR9dwOL:bivjhm3) ([raw file](https://github.com/cockroachdb/cockroach/blob/a53e0774dcb48047e6ba9a62d95098011a072db5/pkg/ui/workspaces/cluster-ui/src/insights/workloadInsights/util/insightsColumns.tsx#L136)):*
<details><summary><i>Previously, ericharmeling (Eric Harmeling) wrote…</i></summary><blockquote>

@kevin-v-ngo 

> Is there a reason why we wouldn't have a contended index?

I think that depends on the query/table. Not all tables have secondary indexes.

> And even key/row span? I thought contention would always be at the key level?

We remove the contended key from the txn insight details page. 

Discussion thread:
https://cockroachlabs.slack.com/archives/G01Q9D01NTU/p1662676417756419?thread_ts=1662662201.540079&cid=G01Q9D01NTU

PR:
https://github.com/cockroachdb/cockroach/pull/87645
</blockquote></details>

I added the index to the table column.

**Comment by kevin-v-ngo** [comment]
> > _[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/88454)_ status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @ericharmeling, @j82w, and @maryliag)
> 
> _[`pkg/ui/workspaces/cluster-ui/src/insights/workloadInsights/util/insightsColumns.tsx` line 136 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/88454#-NC_V5jETd3-fChu27rZ-r2-136:-NC_kbr9EW89rFgcYBGN:baollqe) ([raw file](https://github.com/cockroachdb/cockroach/blob/a53e0774dcb48047e6ba9a62d95098011a072db5/pkg/ui/workspaces/cluster-ui/src/insights/workloadInsights/util/insightsColumns.tsx#L136)):_
> 
> Previously, kevin-v-ngo wrote…
> > Is there a reason why we wouldn't have a contended index? And even key/row span? I thought contention would always be at the key level?
> 
> We don't always have a contended index because there might not be an index. For the key we removed that recently to make this page more user friendly #87645

There's always an index though. Or are you not counting primary index?

**Comment by ericharmeling** [comment]
> There's always an index though. Or are you not counting primary index?

It doesn't look like `crdb_internal.ranges` (where we are pulling the schema, database, table, and index names from) records primary index names. We *could* just list "primary" when there is no other index recorded.

**Comment by j82w** [comment]
*[`pkg/ui/workspaces/cluster-ui/src/api/insightsApi.ts` line 385 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/88454#-NCa26zYB2NqtF56mu2C:-NCa26zYB2NqtF56mu2D:by5thui) ([raw file](https://github.com/cockroachdb/cockroach/blob/22fae65969c9404b8e04c23a1899c4470ae0c892/pkg/ui/workspaces/cluster-ui/src/api/insightsApi.ts#L385)):*
> ```XML
>       databaseName: value.database_name,
>       tableName: value.table_name,
>       indexName: value.index_name,
> ```

@maryliag instead of leaving the column empty when there is no index should it say "No Index"?

**Review by maryliag — COMMENTED** [review]
> Reviewed 1 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/88454)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @ericharmeling, @j82w, and @maryliag)

___
*[`pkg/ui/workspaces/cluster-ui/src/api/insightsApi.ts` line 385 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/88454#-NCa26zYB2NqtF56mu2C:-NCa8Gp_Ez5Sb0Gx4Xbg:b-fqk7bv) ([raw file](https://github.com/cockroachdb/cockroach/blob/22fae65969c9404b8e04c23a1899c4470ae0c892/pkg/ui/workspaces/cluster-ui/src/api/insightsApi.ts#L385)):*
<details><summary><i>Previously, j82w wrote…</i></summary><blockquote>

@maryliag instead of leaving the column empty when there is no index should it say "No Index"?
</blockquote></details>

I think it makes sense to show "No Index"for this case, leaving the value empty on the table would be weird. We already have precedent for this, where we have "no samples" when there isn't stats for something. We do use all lower for the "no samples" so I would say to keep consistent here and use "no index"

**Comment by j82w** [comment]
I renamed the column to secondary indexes. Primary indexes do not show up in the column.

**Review by maryliag — APPROVED** [review]
> Reviewed 5 of 5 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/88454)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @ericharmeling and @j82w)

File: pkg/ui/workspaces/cluster-ui/src/api/insightsApi.ts [hunk 2]
```diff
@@ -352,24 +356,47 @@ type TxnContentionDetailsResponseColumns = {
...
+      collectionTimeStamp: moment(value.collection_ts),
+      contentionTimeMs: contentionTimeInMs,
+      contendedKey: value.key,
+      schemaName: value.schema_name,
+      databaseName: value.database_name,
+      tableName: value.table_name,
+      secondaryIndexName:
+        value.index_name && value.index_name !== ""
+          ? value.index_name
+          : "no index",
```
Comment (ericharmeling) [inline pkg/ui/workspaces/cluster-ui/src/api/insightsApi.ts:388]:
```suggestion
          : "no secondary index",
```

**Comment by j82w** [comment]
*[`pkg/ui/workspaces/cluster-ui/src/api/insightsApi.ts` line 385 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/88454#-NCa26zYB2NqtF56mu2C:-NCaTyOW7TCqvvZPMFMa:bqmf2le) ([raw file](https://github.com/cockroachdb/cockroach/blob/22fae65969c9404b8e04c23a1899c4470ae0c892/pkg/ui/workspaces/cluster-ui/src/api/insightsApi.ts#L385)):*
<details><summary><i>Previously, maryliag (Marylia Gutierrez) wrote…</i></summary><blockquote>

I think it makes sense to show "No Index"for this case, leaving the value empty on the table would be weird. We already have precedent for this, where we have "no samples" when there isn't stats for something. We do use all lower for the "no samples" so I would say to keep consistent here and use "no index"
</blockquote></details>

@kevin-v-ngo suggested keeping the column name as "Index Name", but using "primary index" instead of "no index" to avoid confusion.

**Comment by j82w** [comment]
*[`pkg/ui/workspaces/cluster-ui/src/api/insightsApi.ts` line 388 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/88454#-NC_V5jETd3-fChu27rV-r4-388:-NCaZa5EAZIp6LsNas2g:b-rnlvca) ([raw file](https://github.com/cockroachdb/cockroach/blob/bacb4dca8519fc364ba420d95569cf8ea74a7385/pkg/ui/workspaces/cluster-ui/src/api/insightsApi.ts#L388)):*
<details><summary><i>Previously, ericharmeling (Eric Harmeling) wrote…</i></summary><blockquote>

```suggestion
          : "no secondary index",
```
</blockquote></details>

I went with Kevin's suggestion. The column name is "Index Name" with a default value of "primary index" to avoid confusion.
