### PR TITLE
schemachanger,scbuild: fix assertion bug

### LINKED ISSUE #45510: sql: cannot perform primary key changes while other schema changes are in progress
We cannot currently perform primary key changes when an in progress schema change on the same table is occuring, or when a schema change on the same table has been started earlier in the same transaction. Before we can allow this, we need to investigate the following cases and ensure that primary key changes can handle them.
- [x] preceding index creations
- [ ] preceding column creations 
- [ ] preceding constraint creation/validation
- [ ] preceding primary key changes

### LINKED ISSUE #102927: roachtest: sqlsmith/setup=tpcc/setting=ddl-nodrop failed
roachtest.sqlsmith/setup=tpcc/setting=ddl-nodrop [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/9990827?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/9990827?buildTab=artifacts#/sqlsmith/setup=tpcc/setting=ddl-nodrop) on release-22.2 @ [f16ede7f8528384522821e020f4c75fd120f40e0](https://github.com/cockroachdb/cockroach/commits/f16ede7f8528384522821e020f4c75fd120f40e0):

```
test artifacts and logs in: /artifacts/sqlsmith/setup=tpcc/setting=ddl-nodrop/run_1
(sqlsmith.go:261).func3: error: pq: internal error: building declarative schema change targets for ALTER TABLE: failed to drop all of the relevant elements: [table_id:110 index_id:9 column_id:7 ordinal_in_kind:3 kind:STORED table_id:110 index_id:10 column_id:7 ordinal_in_kind:3 kind:STORED]
stmt:
ALTER TABLE defaultdb.public.order_line DROP COLUMN ol_delivery_d;
```
<p>Parameters: <code>ROACHTEST_cloud=gce</code>
, <code>ROACHTEST_cpu=4</code>
, <code>ROACHTEST_encrypted=false</code>
, <code>ROACHTEST_ssd=0</code>
</p>
<details><summary>Help</summary>
<p>

See: [roachtest README](https://github.com/cockroachdb/cockroach/blob/master/pkg/cmd/roachtest/README.md)

See: [How To Investigate \(internal\)](https://cockroachlabs.atlassian.net/l/c/SSSBr8c7)

</p>
</details>
/cc @cockroachdb/sql-queries
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*sqlsmith/setup=tpcc/setting=ddl-nodrop.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)
</sub>

Jira issue: CRDB-27733

### LINKED ISSUE #105754: Sentry: alter_table_drop_column.go:581: building declarative schema change targets for ALTER TABLE: failed to drop all of the relevant elements: [× ×] (1) attached stack trace   -- stack trace:   | ...
This issue was auto filed by Sentry. It represents a crash or reported error on a live cluster with telemetry enabled.

Sentry Link: [https://cockroach-labs.sentry.io/issues/4281301765/?referrer=webhooks_plugin](https://cockroach-labs.sentry.io/issues/4281301765/?referrer=webhooks_plugin)

Panic Message:

```
alter_table_drop_column.go:581: building declarative schema change targets for ALTER TABLE: failed to drop all of the relevant elements: [× ×]
(1) attached stack trace
  -- stack trace:
  | github.com/cockroachdb/cockroach/pkg/sql/schemachanger/scerrors.EventLogger.HandlePanicAndLogError
  | 	github.com/cockroachdb/cockroach/pkg/sql/schemachanger/scerrors/errors.go:81
  | runtime.gopanic
  | 	GOROOT/src/runtime/panic.go:884
  | [...repeated from below...]
Wraps: (2) building declarative schema change targets for ALTER TABLE
Wraps: (3) assertion failure
Wraps: (4) attached stack trace
  -- stack trace:
  | github.com/cockroachdb/cockroach/pkg/sql/schemachanger/scbuild/internal/scbuildstmt.assertAllColumnElementsAreDropped
  | 	github.com/cockroachdb/cockroach/pkg/sql/schemachanger/scbuild/internal/scbuildstmt/alter_table_drop_column.go:581
  | github.com/cockroachdb/cockroach/pkg/sql/schemachanger/scbuild/internal/scbuildstmt.dropColumn
  | 	github.com/cockroachdb/cockroach/pkg/sql/schemachanger/scbuild/internal/scbuildstmt/alter_table_drop_column.go:315
  | github.com/cockroachdb/cockroach/pkg/sql/schemachanger/scbuild/internal/scbuildstmt.alterTableDropColumn
  | 	github.com/cockroachdb/cockroach/pkg/sql/schemachanger/scbuild/internal/scbuildstmt/alter_table_drop_column.go:45
  | reflect.Value.call
  | 	GOROOT/src/reflect/value.go:584
  | reflect.Value.Call
  | 	GOROOT/src/reflect/value.go:368
  | github.com/cockroachdb/cockroach/pkg/sql/schemachanger/scbuild/internal/scbuildstmt.AlterTable
  | 	github.com/cockroachdb/cockroach/pkg/sql/schemachanger/scbuild/internal/scbuildstmt/alter_table.go:170
  | reflect.Value.call
  | 	GOROOT/src/reflect/value.go:584
  | reflect.Value.Call
  | 	GOROOT/src/reflect/value.go:368
  | github.com/cockroachdb/cockroach/pkg/sql/schemachanger/scbuild/internal/scbuildstmt.Process
  | 	github.com/cockroachdb/cockroach/pkg/sql/schemachanger/scbuild/internal/scbuildstmt/process.go:173
  | github.com/cockroachdb/cockroach/pkg/sql/schemachanger/scbuild.Build
  | 	github.com/cockroachdb/cockroach/pkg/sql/schemachanger/scbuild/build.go:85
  | github.com/cockroachdb/cockroach/pkg/sql.(*planner).SchemaChange
  | 	github.com/cockroachdb/cockroach/pkg/sql/schema_change_plan_node.go:68
  | github.com/cockroachdb/cockroach/pkg/sql.buildOpaque
  | 	github.com/cockroachdb/cockroach/pkg/sql/opaque.go:56
  | github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder.(*Builder).tryBuildOpaque
  | 	github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder/opaque.go:70
  | github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder.(*Builder).buildStmt
  | 	github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder/builder.go:434
  | github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder.(*Builder).buildStmtAtRoot
  | 	github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder/builder.go:272
  | github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder.(*Builder).Build
  | 	github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder/builder.go:246
  | github.com/cockroachdb/cockroach/pkg/sql.(*optPlanningCtx).buildExecMemo
  | 	github.com/cockroachdb/cockroach/pkg/sql/plan_opt.go:574
  | github.com/cockroachdb/cockroach/pkg/sql.(*planner).makeOptimizerPlan
  | 	github.com/cockroachdb/cockroach/pkg/sql/plan_opt.go:238
  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).makeExecPlan
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:1978
  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).dispatchToExecutionEngine
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:1484
  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execStmtInOpenState
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:964
  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execStmt.func1
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:142
  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execWithProfiling
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:2986
  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execStmt
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:141
  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execCmd.func1
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:2175
  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execCmd
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:2180
  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).run
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:2097
  | github.com/cockroachdb/cockroach/pkg/sql.(*Server).ServeConn
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:893
  | github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*conn).processCommandsAsync.func1
  | 	github.com/cockroachdb/cockroach/pkg/sql/pgwire/conn.go:778
  | runtime.goexit
  | 	GOROOT/src/runtime/asm_amd64.s:1594
Wraps: (5) failed to drop all of the relevant elements: [× ×]
Error types: (1) *withstack.withStack (2) *errutil.withPrefix (3) *assert.withAssertionFailure (4) *withstack.withStack (5) *errutil.leafError
-- report composition:
*errutil.leafError: failed to drop all of the relevant elements: [× ×]
alter_table_drop_column.go:581: *withstack.withStack (top exception)
*assert.withAssertionFailure
*errutil.withPrefix: building declarative schema change targets for ALTER TABLE
errors.go:81: *withstack.withStack (1)
(check the extra data payloads)
```

<details>
<summary>Stacktrace (expand for inline code snippets):</summary>

[GOROOT/src/runtime/asm_amd64.s#L1593-L1595](GOROOT/src/runtime/asm_amd64.s#L1593-L1595)
[https://github.com/cockroachdb/cockroach/blob/d8d427b1574281f7dc16da266867279c13cdbfd6/pkg/sql/pgwire/conn.go#L777-L779](https://github.com/cockroachdb/cockroach/blob/d8d427b1574281f7dc16da266867279c13cdbfd6/pkg/sql/pgwire/conn.go#L777-L779)
[https://github.com/cockroachdb/cockroach/blob/d8d427b1574281f7dc16da266867279c13cdbfd6/pkg/sql/conn_executor.go#L892-L894](https://github.com/cockroachdb/cockroach/blob/d8d427b1574281f7dc16da266867279c13cdbfd6/pkg/sql/conn_executor.go#L892-L894)
[https://github.com/cockroachdb/cockroach/blob/d8d427b1574281f7dc16da266867279c13cdbfd6/pkg/sql/conn_executor.go#L2096-L2098](https://github.com/cockroachdb/cockroach/blob/d8d427b1574281f7dc16da266867279c13cdbfd6/pkg/sql/conn_executor.go#L2096-L2098)
[https://github.com/cockroachdb/cockroach/blob/d8d427b1574281f7dc16da266867279c13cdbfd6/pkg/sql/conn_executor.go#L2179-L2181](https://github.com/cockroachdb/cockroach/blob/d8d427b1574281f7dc16da266867279c13cdbfd6/pkg/sql/conn_executor.go#L2179-L2181)
[https://github.com/cockroachdb/cockroach/blob/d8d427b1574281f7dc16da266867279c13cdbfd6/pkg/sql/conn_executor.go#L2174-L2176](https://github.com/cockroachdb/cockroach/blob/d8d427b1574281f7dc16da266867279c13cdbfd6/pkg/sql/conn_executor.go#L2174-L2176)
[https://github.com/cockroachdb/cockroach/blob/d8d427b1574281f7dc16da266867279c13cdbfd6/pkg/sql/conn_executor_exec.go#L140-L142](https://github.com/cockroachdb/cockroach/blob/d8d427b1574281f7dc16da266867279c13cdbfd6/pkg/sql/conn_executor_exec.go#L140-L142)
[https://github.com/cockroachdb/cockroach/blob/d8d427b1574281f7dc16da266867279c13cdbfd6/pkg/sql/conn_executor_exec.go#L2985-L2987](https://github.com/cockroachdb/cockroach/blob/d8d427b1574281f7dc16da266867279c13cdbfd6/pkg/sql/conn_executor_exec.go#L2985-L2987)
[https://github.com/cockroachdb/cockroach/blob/d8d427b1574281f7dc16da266867279c13cdbfd6/pkg/sql/conn_executor_exec.go#L141-L143](https://github.com/cockroachdb/cockroach/blob/d8d427b1574281f7dc16da266867279c13cdbfd6/pkg/sql/conn_executor_exec.go#L141-L143)
[https://github.com/cockroachdb/cockroach/blob/d8d427b1574281f7dc16da266867279c13cdbfd6/pkg/sql/conn_executor_exec.go#L963-L965](https://github.com/cockroachdb/cockroach/blob/d8d427b1574281f7dc16da266867279c13cdbfd6/pkg/sql/conn_executor_exec.go#L963-L965)
[https://github.com/cockroachdb/cockroach/blob/d8d427b1574281f7dc16da266867279c13cdbfd6/pkg/sql/conn_executor_exec.go#L1483-L1485](https://github.com/cockroachdb/cockroach/blob/d8d427b1574281f7dc16da266867279c13cdbfd6/pkg/sql/conn_executor_exec.go#L1483-L1485)
[https://github.com/cockroachdb/cockroach/blob/d8d427b1574281f7dc16da266867279c13cdbfd6/pkg/sql/conn_executor_exec.go#L1977-L1979](https://github.com/cockroachdb/cockroach/blob/d8d427b1574281f7dc16da266867279c13cdbfd6/pkg/sql/conn_executor_exec.go#L1977-L1979)
[https://github.com/cockroachdb/cockroach/blob/d8d427b1574281f7dc16da266867279c13cdbfd6/pkg/sql/plan_opt.go#L237-L239](https://github.com/cockroachdb/cockroach/blob/d8d427b1574281f7dc16da266867279c13cdbfd6/pkg/sql/plan_opt.go#L237-L239)
[https://github.com/cockroachdb/cockroach/blob/d8d427b1574281f7dc16da266867279c13cdbfd6/pkg/sql/plan_opt.go#L573-L575](https://github.com/cockroachdb/cockroach/blob/d8d427b1574281f7dc16da266867279c13cdbfd6/pkg/sql/plan_opt.go#L573-L575)
[https://github.com/cockroachdb/cockroach/blob/d8d427b1574281f7dc16da266867279c13cdbfd6/pkg/sql/opt/optbuilder/builder.go#L245-L247](https://github.com/cockroachdb/cockroach/blob/d8d427b1574281f7dc16da266867279c13cdbfd6/pkg/sql/opt/optbuilder/builder.go#L245-L247)
[https://github.com/cockroachdb/cockroach/blob/d8d427b1574281f7dc16da266867279c13cdbfd6/pkg/sql/opt/optbuilder/builder.go#L271-L273](https://github.com/cockroachdb/cockroach/blob/d8d427b1574281f7dc16da266867279c13cdbfd6/pkg/sql/opt/optbuilder/builder.go#L271-L273)
[https://github.com/cockroachdb/cockroach/blob/d8d427b1574281f7dc16da266867279c13cdbfd6/pkg/sql/opt/optbuilder/builder.go#L433-L435](https://github.com/cockroachdb/cockroach/blob/d8d427b1574281f7dc16da266867279c13cdbfd6/pkg/sql/opt/optbuilder/builder.go#L433-L435)
[https://github.com/cockroachdb/cockroach/blob/d8d427b1574281f7dc16da266867279c13cdbfd6/pkg/sql/opt/optbuilder/opaque.go#L69-L71](https://github.com/cockroachdb/cockroach/blob/d8d427b1574281f7dc16da266867279c13cdbfd6/pkg/sql/opt/optbuilder/opaque.go#L69-L71)
[https://github.com/cockroachdb/cockroach/blob/d8d427b1574281f7dc16da266867279c13cdbfd6/pkg/sql/opaque.go#L55-L57](https://github.com/cockroachdb/cockroach/blob/d8d427b1574281f7dc16da266867279c13cdbfd6/pkg/sql/opaque.go#L55-L57)
[https://github.com/cockroachdb/cockroach/blob/d8d427b1574281f7dc16da266867279c13cdbfd6/pkg/sql/schema_change_plan_node.go#L67-L69](https://github.com/cockroachdb/cockroach/blob/d8d427b1574281f7dc16da266867279c13cdbfd6/pkg/sql/schema_change_plan_node.go#L67-L69)
[https://github.com/cockroachdb/cockroach/blob/d8d427b1574281f7dc16da266867279c13cdbfd6/pkg/sql/schemachanger/scbuild/build.go#L84-L86](https://github.com/cockroachdb/cockroach/blob/d8d427b1574281f7dc16da266867279c13cdbfd6/pkg/sql/schemachanger/scbuild/build.go#L84-L86)
[https://github.com/cockroachdb/cockroach/blob/d8d427b1574281f7dc16da266867279c13cdbfd6/pkg/sql/schemachanger/scbuild/internal/scbuildstmt/process.go#L172-L174](https://github.com/cockroachdb/cockroach/blob/d8d427b1574281f7dc16da266867279c13cdbfd6/pkg/sql/schemachanger/scbuild/internal/scbuildstmt/process.go#L172-L174)
[GOROOT/src/reflect/value.go#L367-L369](GOROOT/src/reflect/value.go#L367-L369)
[GOROOT/src/reflect/value.go#L583-L585](GOROOT/src/reflect/value.go#L583-L585)
[https://github.com/cockroachdb/cockroach/blob/d8d427b1574281f7dc16da266867279c13cdbfd6/pkg/sql/schemachanger/scbuild/internal/scbuildstmt/alter_table.go#L169-L171](https://github.com/cockroachdb/cockroach/blob/d8d427b1574281f7dc16da266867279c13cdbfd6/pkg/sql/schemachanger/scbuild/internal/scbuildstmt/alter_table.go#L169-L171)
[GOROOT/src/reflect/value.go#L367-L369](GOROOT/src/reflect/value.go#L367-L369)
[GOROOT/src/reflect/value.go#L583-L585](GOROOT/src/reflect/value.go#L583-L585)
[https://github.com/cockroachdb/cockroach/blob/d8d427b1574281f7dc16da266867279c13cdbfd6/pkg/sql/schemachanger/scbuild/internal/scbuildstmt/alter_table_drop_column.go#L44-L46](https://github.com/cockroachdb/cockroach/blob/d8d427b1574281f7dc16da266867279c13cdbfd6/pkg/sql/schemachanger/scbuild/internal/scbuildstmt/alter_table_drop_column.go#L44-L46)
[https://github.com/cockroachdb/cockroach/blob/d8d427b1574281f7dc16da266867279c13cdbfd6/pkg/sql/schemachanger/scbuild/internal/scbuildstmt/alter_table_drop_column.go#L314-L316](https://github.com/cockroachdb/cockroach/blob/d8d427b1574281f7dc16da266867279c13cdbfd6/pkg/sql/schemachanger/scbuild/internal/scbuildstmt/alter_table_drop_column.go#L314-L316)
[https://github.com/cockroachdb/cockroach/blob/d8d427b1574281f7dc16da266867279c13cdbfd6/pkg/sql/schemachanger/scbuild/internal/scbuildstmt/alter_table_drop_column.go#L580-L582](https://github.com/cockroachdb/cockroach/blob/d8d427b1574281f7dc16da266867279c13cdbfd6/pkg/sql/schemachanger/scbuild/internal/scbuildstmt/alter_table_drop_column.go#L580-L582)
[GOROOT/src/runtime/panic.go#L883-L885](GOROOT/src/runtime/panic.go#L883-L885)
[https://github.com/cockroachdb/cockroach/blob/d8d427b1574281f7dc16da266867279c13cdbfd6/pkg/sql/schemachanger/scerrors/errors.go#L80-L82](https://github.com/cockroachdb/cockroach/blob/d8d427b1574281f7dc16da266867279c13cdbfd6/pkg/sql/schemachanger/scerrors/errors.go#L80-L82)
[GOROOT/src/runtime/asm_amd64.s#L1593-L1595](GOROOT/src/runtime/asm_amd64.s#L1593-L1595)
[https://github.com/cockroachdb/cockroach/blob/d8d427b1574281f7dc16da266867279c13cdbfd6/pkg/sql/pgwire/conn.go#L777-L779](https://github.com/cockroachdb/cockroach/blob/d8d427b1574281f7dc16da266867279c13cdbfd6/pkg/sql/pgwire/conn.go#L777-L779)
[https://github.com/cockroachdb/cockroach/blob/d8d427b1574281f7dc16da266867279c13cdbfd6/pkg/sql/conn_executor.go#L892-L894](https://github.com/cockroachdb/cockroach/blob/d8d427b1574281f7dc16da266867279c13cdbfd6/pkg/sql/conn_executor.go#L892-L894)
[https://github.com/cockroachdb/cockroach/blob/d8d427b1574281f7dc16da266867279c13cdbfd6/pkg/sql/conn_executor.go#L2096-L2098](https://github.com/cockroachdb/cockroach/blob/d8d427b1574281f7dc16da266867279c13cdbfd6/pkg/sql/conn_executor.go#L2096-L2098)
[https://github.com/cockroachdb/cockroach/blob/d8d427b1574281f7dc16da266867279c13cdbfd6/pkg/sql/conn_executor.go#L2179-L2181](https://github.com/cockroachdb/cockroach/blob/d8d427b1574281f7dc16da266867279c13cdbfd6/pkg/sql/conn_executor.go#L2179-L2181)
[https://github.com/cockroachdb/cockroach/blob/d8d427b1574281f7dc16da266867279c13cdbfd6/pkg/sql/conn_executor.go#L2174-L2176](https://github.com/cockroachdb/cockroach/blob/d8d427b1574281f7dc16da266867279c13cdbfd6/pkg/sql/conn_executor.go#L2174-L2176)
[https://github.com/cockroachdb/cockroach/blob/d8d427b1574281f7dc16da266867279c13cdbfd6/pkg/sql/conn_executor_exec.go#L140-L142](https://github.com/cockroachdb/cockroach/blob/d8d427b1574281f7dc16da266867279c13cdbfd6/pkg/sql/conn_executor_exec.go#L140-L142)
[https://github.com/cockroachdb/cockroach/blob/d8d427b1574281f7dc16da266867279c13cdbfd6/pkg/sql/conn_executor_exec.go#L2985-L2987](https://github.com/cockroachdb/cockroach/blob/d8d427b1574281f7dc16da266867279c13cdbfd6/pkg/sql/conn_executor_exec.go#L2985-L2987)
[https://github.com/cockroachdb/cockroach/blob/d8d427b1574281f7dc16da266867279c13cdbfd6/pkg/sql/conn_executor_exec.go#L141-L143](https://github.com/cockroachdb/cockroach/blob/d8d427b1574281f7dc16da266867279c13cdbfd6/pkg/sql/conn_executor_exec.go#L141-L143)
[https://github.com/cockroachdb/cockroach/blob/d8d427b1574281f7dc16da266867279c13cdbfd6/pkg/sql/conn_executor_exec.go#L963-L965](https://github.com/cockroachdb/cockroach/blob/d8d427b1574281f7dc16da266867279c13cdbfd6/pkg/sql/conn_executor_exec.go#L963-L965)
[https://github.com/cockroachdb/cockroach/blob/d8d427b1574281f7dc16da266867279c13cdbfd6/pkg/sql/conn_executor_exec.go#L1483-L1485](https://github.com/cockroachdb/cockroach/blob/d8d427b1574281f7dc16da266867279c13cdbfd6/pkg/sql/conn_executor_exec.go#L1483-L1485)
[https://github.com/cockroachdb/cockroach/blob/d8d427b1574281f7dc16da266867279c13cdbfd6/pkg/sql/conn_executor_exec.go#L1977-L1979](https://github.com/cockroachdb/cockroach/blob/d8d427b1574281f7dc16da266867279c13cdbfd6/pkg/sql/conn_executor_exec.go#L1977-L1979)
[https://github.com/cockroachdb/cockroach/blob/d8d427b1574281f7dc16da266867279c13cdbfd6/pkg/sql/plan_opt.go#L237-L239](https://github.com/cockroachdb/cockroach/blob/d8d427b1574281f7dc16da266867279c13cdbfd6/pkg/sql/plan_opt.go#L237-L239)
[https://github.com/cockroachdb/cockroach/blob/d8d427b1574281f7dc16da266867279c13cdbfd6/pkg/sql/plan_opt.go#L573-L575](https://github.com/cockroachdb/cockroach/blob/d8d427b1574281f7dc16da266867279c13cdbfd6/pkg/sql/plan_opt.go#L573-L575)
[https://github.com/cockroachdb/cockroach/blob/d8d427b1574281f7dc16da266867279c13cdbfd6/pkg/sql/opt/optbuilder/builder.go#L245-L247](https://github.com/cockroachdb/cockroach/blob/d8d427b1574281f7dc16da266867279c13cdbfd6/pkg/sql/opt/optbuilder/builder.go#L245-L247)
[https://github.com/cockroachdb/cockroach/blob/d8d427b1574281f7dc16da266867279c13cdbfd6/pkg/sql/opt/optbuilder/builder.go#L271-L273](https://github.com/cockroachdb/cockroach/blob/d8d427b1574281f7dc16da266867279c13cdbfd6/pkg/sql/opt/optbuilder/builder.go#L271-L273)
[https://github.com/cockroachdb/cockroach/blob/d8d427b1574281f7dc16da266867279c13cdbfd6/pkg/sql/opt/optbuilder/builder.go#L433-L435](https://github.com/cockroachdb/cockroach/blob/d8d427b1574281f7dc16da266867279c13cdbfd6/pkg/sql/opt/optbuilder/builder.go#L433-L435)
[https://github.com/cockroachdb/cockroach/blob/d8d427b1574281f7dc16da266867279c13cdbfd6/pkg/sql/opt/optbuilder/opaque.go#L69-L71](https://github.com/cockroachdb/cockroach/blob/d8d427b1574281f7dc16da266867279c13cdbfd6/pkg/sql/opt/optbuilder/opaque.go#L69-L71)
[https://github.com/cockroachdb/cockroach/blob/d8d427b1574281f7dc16da266867279c13cdbfd6/pkg/sql/opaque.go#L55-L57](https://github.com/cockroachdb/cockroach/blob/d8d427b1574281f7dc16da266867279c13cdbfd6/pkg/sql/opaque.go#L55-L57)
[https://github.com/cockroachdb/cockroach/blob/d8d427b1574281f7dc16da266867279c13cdbfd6/pkg/sql/schema_change_plan_node.go#L67-L69](https://github.com/cockroachdb/cockroach/blob/d8d427b1574281f7dc16da266867279c13cdbfd6/pkg/sql/schema_change_plan_node.go#L67-L69)
[https://github.com/cockroachdb/cockroach/blob/d8d427b1574281f7dc16da266867279c13cdbfd6/pkg/sql/schemachanger/scbuild/build.go#L84-L86](https://github.com/cockroachdb/cockroach/blob/d8d427b1574281f7dc16da266867279c13cdbfd6/pkg/sql/schemachanger/scbuild/build.go#L84-L86)
[https://github.com/cockroachdb/cockroach/blob/d8d427b1574281f7dc16da266867279c13cdbfd6/pkg/sql/schemachanger/scbuild/internal/scbuildstmt/process.go#L172-L174](https://github.com/cockroachdb/cockroach/blob/d8d427b1574281f7dc16da266867279c13cdbfd6/pkg/sql/schemachanger/scbuild/internal/scbuildstmt/process.go#L172-L174)
[GOROOT/src/reflect/value.go#L367-L369](GOROOT/src/reflect/value.go#L367-L369)
[GOROOT/src/reflect/value.go#L583-L585](GOROOT/src/reflect/value.go#L583-L585)
[https://github.com/cockroachdb/cockroach/blob/d8d427b1574281f7dc16da266867279c13cdbfd6/pkg/sql/schemachanger/scbuild/internal/scbuildstmt/alter_table.go#L169-L171](https://github.com/cockroachdb/cockroach/blob/d8d427b1574281f7dc16da266867279c13cdbfd6/pkg/sql/schemachanger/scbuild/internal/scbuildstmt/alter_table.go#L169-L171)
[GOROOT/src/reflect/value.go#L367-L369](GOROOT/src/reflect/value.go#L367-L369)
[GOROOT/src/reflect/value.go#L583-L585](GOROOT/src/reflect/value.go#L583-L585)
[https://github.com/cockroachdb/cockroach/blob/d8d427b1574281f7dc16da266867279c13cdbfd6/pkg/sql/schemachanger/scbuild/internal/scbuildstmt/alter_table_drop_column.go#L44-L46](https://github.com/cockroachdb/cockroach/blob/d8d427b1574281f7dc16da266867279c13cdbfd6/pkg/sql/schemachanger/scbuild/internal/scbuildstmt/alter_table_drop_column.go#L44-L46)
[https://github.com/cockroachdb/cockroach/blob/d8d427b1574281f7dc16da266867279c13cdbfd6/pkg/sql/schemachanger/scbuild/internal/scbuildstmt/alter_table_drop_column.go#L314-L316](https://github.com/cockroachdb/cockroach/blob/d8d427b1574281f7dc16da266867279c13cdbfd6/pkg/sql/schemachanger/scbuild/internal/scbuildstmt/alter_table_drop_column.go#L314-L316)
[https://github.com/cockroachdb/cockroach/blob/d8d427b1574281f7dc16da266867279c13cdbfd6/pkg/sql/schemachanger/scbuild/internal/scbuildstmt/alter_table_drop_column.go#L580-L582](https://github.com/cockroachdb/cockroach/blob/d8d427b1574281f7dc16da266867279c13cdbfd6/pkg/sql/schemachanger/scbuild/internal/scbuildstmt/alter_table_drop_column.go#L580-L582)
</details>

```
GOROOT/src/runtime/asm_amd64.s in runtime.goexit at line 1594
pkg/sql/pgwire/conn.go in pkg/sql/pgwire.(*conn).processCommandsAsync.func1 at line 778
pkg/sql/conn_executor.go in pkg/sql.(*Server).ServeConn at line 893
pkg/sql/conn_executor.go in pkg/sql.(*connExecutor).run at line 2097
pkg/sql/conn_executor.go in pkg/sql.(*connExecutor).execCmd at line 2180
pkg/sql/conn_executor.go in pkg/sql.(*connExecutor).execCmd.func1 at line 2175
pkg/sql/conn_executor_exec.go in pkg/sql.(*connExecutor).execStmt at line 141
pkg/sql/conn_executor_exec.go in pkg/sql.(*connExecutor).execWithProfiling at line 2986
pkg/sql/conn_executor_exec.go in pkg/sql.(*connExecutor).execStmt.func1 at line 142
pkg/sql/conn_executor_exec.go in pkg/sql.(*connExecutor).execStmtInOpenState at line 964
pkg/sql/conn_executor_exec.go in pkg/sql.(*connExecutor).dispatchToExecutionEngine at line 1484
pkg/sql/conn_executor_exec.go in pkg/sql.(*connExecutor).makeExecPlan at line 1978
pkg/sql/plan_opt.go in pkg/sql.(*planner).makeOptimizerPlan at line 238
pkg/sql/plan_opt.go in pkg/sql.(*optPlanningCtx).buildExecMemo at line 574
pkg/sql/opt/optbuilder/builder.go in pkg/sql/opt/optbuilder.(*Builder).Build at line 246
pkg/sql/opt/optbuilder/builder.go in pkg/sql/opt/optbuilder.(*Builder).buildStmtAtRoot at line 272
pkg/sql/opt/optbuilder/builder.go in pkg/sql/opt/optbuilder.(*Builder).buildStmt at line 434
pkg/sql/opt/optbuilder/opaque.go in pkg/sql/opt/optbuilder.(*Builder).tryBuildOpaque at line 70
pkg/sql/opaque.go in pkg/sql.buildOpaque at line 56
pkg/sql/schema_change_plan_node.go in pkg/sql.(*planner).SchemaChange at line 68
pkg/sql/schemachanger/scbuild/build.go in pkg/sql/schemachanger/scbuild.Build at line 85
pkg/sql/schemachanger/scbuild/internal/scbuildstmt/process.go in pkg/sql/schemachanger/scbuild/internal/scbuildstmt.Process at line 173
GOROOT/src/reflect/value.go in reflect.Value.Call at line 368
GOROOT/src/reflect/value.go in reflect.Value.call at line 584
pkg/sql/schemachanger/scbuild/internal/scbuildstmt/alter_table.go in pkg/sql/schemachanger/scbuild/internal/scbuildstmt.AlterTable at line 170
GOROOT/src/reflect/value.go in reflect.Value.Call at line 368
GOROOT/src/reflect/value.go in reflect.Value.call at line 584
pkg/sql/schemachanger/scbuild/internal/scbuildstmt/alter_table_drop_column.go in pkg/sql/schemachanger/scbuild/internal/scbuildstmt.alterTableDropColumn at line 45
pkg/sql/schemachanger/scbuild/internal/scbuildstmt/alter_table_drop_column.go in pkg/sql/schemachanger/scbuild/internal/scbuildstmt.dropColumn at line 315
pkg/sql/schemachanger/scbuild/internal/scbuildstmt/alter_table_drop_column.go in pkg/sql/schemachanger/scbuild/internal/scbuildstmt.assertAllColumnElementsAreDropped at line 581
GOROOT/src/runtime/panic.go in runtime.gopanic at line 884
pkg/sql/schemachanger/scerrors/errors.go in pkg/sql/schemachanger/scerrors.EventLogger.HandlePanicAndLogError at line 81
GOROOT/src/runtime/asm_amd64.s in runtime.goexit at line 1594
pkg/sql/pgwire/conn.go in pkg/sql/pgwire.(*conn).processCommandsAsync.func1 at line 778
pkg/sql/conn_executor.go in pkg/sql.(*Server).ServeConn at line 893
pkg/sql/conn_executor.go in pkg/sql.(*connExecutor).run at line 2097
pkg/sql/conn_executor.go in pkg/sql.(*connExecutor).execCmd at line 2180
pkg/sql/conn_executor.go in pkg/sql.(*connExecutor).execCmd.func1 at line 2175
pkg/sql/conn_executor_exec.go in pkg/sql.(*connExecutor).execStmt at line 141
pkg/sql/conn_executor_exec.go in pkg/sql.(*connExecutor).execWithProfiling at line 2986
pkg/sql/conn_executor_exec.go in pkg/sql.(*connExecutor).execStmt.func1 at line 142
pkg/sql/conn_executor_exec.go in pkg/sql.(*connExecutor).execStmtInOpenState at line 964
pkg/sql/conn_executor_exec.go in pkg/sql.(*connExecutor).dispatchToExecutionEngine at line 1484
pkg/sql/conn_executor_exec.go in pkg/sql.(*connExecutor).makeExecPlan at line 1978
pkg/sql/plan_opt.go in pkg/sql.(*planner).makeOptimizerPlan at line 238
pkg/sql/plan_opt.go in pkg/sql.(*optPlanningCtx).buildExecMemo at line 574
pkg/sql/opt/optbuilder/builder.go in pkg/sql/opt/optbuilder.(*Builder).Build at line 246
pkg/sql/opt/optbuilder/builder.go in pkg/sql/opt/optbuilder.(*Builder).buildStmtAtRoot at line 272
pkg/sql/opt/optbuilder/builder.go in pkg/sql/opt/optbuilder.(*Builder).buildStmt at line 434
pkg/sql/opt/optbuilder/opaque.go in pkg/sql/opt/optbuilder.(*Builder).tryBuildOpaque at line 70
pkg/sql/opaque.go in pkg/sql.buildOpaque at line 56
pkg/sql/schema_change_plan_node.go in pkg/sql.(*planner).SchemaChange at line 68
pkg/sql/schemachanger/scbuild/build.go in pkg/sql/schemachanger/scbuild.Build at line 85
pkg/sql/schemachanger/scbuild/internal/scbuildstmt/process.go in pkg/sql/schemachanger/scbuild/internal/scbuildstmt.Process at line 173
GOROOT/src/reflect/value.go in reflect.Value.Call at line 368
GOROOT/src/reflect/value.go in reflect.Value.call at line 584
pkg/sql/schemachanger/scbuild/internal/scbuildstmt/alter_table.go in pkg/sql/schemachanger/scbuild/internal/scbuildstmt.AlterTable at line 170
GOROOT/src/reflect/value.go in reflect.Value.Call at line 368
GOROOT/src/reflect/value.go in reflect.Value.call at line 584
pkg/sql/schemachanger/scbuild/internal/scbuildstmt/alter_table_drop_column.go in pkg/sql/schemachanger/scbuild/internal/scbuildstmt.alterTableDropColumn at line 45
pkg/sql/schemachanger/scbuild/internal/scbuildstmt/alter_table_drop_column.go in pkg/sql/schemachanger/scbuild/internal/scbuildstmt.dropColumn at line 315
pkg/sql/schemachanger/scbuild/internal/scbuildstmt/alter_table_drop_column.go in pkg/sql/schemachanger/scbuild/internal/scbuildstmt.assertAllColumnElementsAreDropped at line 581
```

### Tags

| Tag | Value |
| --- | --- |
| Command | mt start-sql |
| Environment | v23.1.4 |
| Go Version | go1.19.4 |
| Platform | linux amd64 |
| Distribution | CCL |
| Cockroach Release | v23.1.3-121-gd8d427b1574 |
| Cockroach SHA | d8d427b1574281f7dc16da266867279c13cdbfd6 |
| # of CPUs | 32 |
| # of Goroutines | 334 |

Jira issue: CRDB-29175

### PR DESCRIPTION
**Pull request by postamar**
The declarative schema changer builder contains assertions on the state of elements and their targets and these could sometimes fail because the check which verifies that the corresponding descriptors are not already undergoing a schema change was performed later. This commit fixes this by moving the check earlier so the assertion is never reached in those cases.

This commit removes a skipped test which is superseded by a new test in the schemachanger package.

Fixes: #45510
Fixes: #102927
Fixes: #105754

Release note (bug fix): fixed a bug which manifested itself in error messages containing "failed to drop all of the relevant elements" when executing DDL statements with the declarative schema changer. What this really means is that there's a concurrent schema change that's ongoing. Instead we now behave as expected and wait for it to finish.

### CODE REVIEW

File: pkg/sql/schema_change_plan_node.go [hunk 1]
```diff
@@ -198,16 +198,11 @@ func (p *planner) waitForDescriptorSchemaChanges(
 
 	// Wait for the descriptor to no longer be claimed by a schema change.
 	start := timeutil.Now()
-	logEvery := log.Every(30 * time.Second)
+	logEvery := log.Every(10 * time.Second)
```
Comment (postamar) [inline pkg/sql/schema_change_plan_node.go:201]: 10s is more convenient than 30s when running tests and tailing the logs

File: pkg/sql/schema_change_plan_node.go [hunk 2]
```diff
@@ -218,15 +213,29 @@ func (p *planner) waitForDescriptorSchemaChanges(
...
+			wasBlocked = true
+		} else {
 			break
 		}
+		if logEvery.ShouldLog() {
+			log.Infof(ctx,
+				"schema change waiting for concurrent schema changes on descriptor %d,"+
+					" waited %v so far", descID, timeutil.Since(start),
+			)
+		}
```
Comment (postamar) [inline pkg/sql/schema_change_plan_node.go:231]: moving this to the end of the for-loop makes more sense, so that no message is logged if we're not actually waiting

**Comment by postamar** [comment]
I will backport this manually to 23.1 and 22.2.

**Review by chengxiong-ruan — APPROVED** [review]
LGTM, nice work!

**Comment by postamar** [comment]
Thanks for the review!

bors r+
