### PR TITLE
ui: fix db console bugs

### LINKED ISSUE #135290: db-console: node overview page store column re-orders on node refresh
Nodes overview page renders node stores in random order and re-renders in different order when refresh calls to `/_status/nodes_ui` are made. 

https://github.com/user-attachments/assets/498977e7-3561-46aa-a4f6-751d7443fcda

Jira issue: CRDB-44439

### PR DESCRIPTION
**Pull request by kyle-a-wong**
Fixes the following bugs

Overview page:
  - Sorting the nodes column for single region clustesr now sorts by node id. Previously, it didn't sort at all.
  - Sorting by replica count now works as expected.
  - Sorting by vCPUs now works as expected.
  - Removed sorting icons from the following columns:
    - Uptime
    - Version

Node Overview Page:
  - Fixed a bug where the store columns rendered in random order and would re-render in random order periodically.

Resolves: #135290, #134197
Epic: none
Release note (ui change): fixes UI bugs in db-console. See commit message for full list of bug fixes.

### CODE REVIEW

**Comment by kyle-a-wong** [comment]
Overview page before and after changes:
https://www.loom.com/share/94926b07fcf640a286338dd3bc322d30

Node overview page:
https://www.loom.com/share/71614ac8822843d9818704678c2669a0?sid=d16ddd13-a16c-4ccc-b171-b84f434fc2f3

File: pkg/ui/workspaces/db-console/src/redux/apiReducers.ts [hunk 1]
```diff
@@ -77,7 +78,15 @@ function rollupStoreMetrics(
 
 export const nodesReducerObj = new CachedDataReducer(
   (req: api.NodesRequestMessage, timeout?: moment.Duration) =>
-    api.getNodesUI(req, timeout).then(rollupStoreMetrics),
+    api
+      .getNodesUI(req, timeout)
+      .then(rollupStoreMetrics)
+      .then(nodeStatuses => {
+        return nodeStatuses.map(ns => {
```
Comment (dhartunian) [inline pkg/ui/workspaces/db-console/src/redux/apiReducers.ts:85]: nit: should this be a `forEach` instead of a `map`?

**Review by dhartunian — APPROVED** [review]

File: pkg/ui/workspaces/db-console/src/redux/apiReducers.ts (hunk 1 above)
Comment (kyle-a-wong) [reply pkg/ui/workspaces/db-console/src/redux/apiReducers.ts]: Done

**Comment by kyle-a-wong** [comment]
tftr!

bors r+
