### PR TITLE
bazel: fix `nogo` config

### LINKED ISSUE #76075: bazel: is `returnerrcheck` running properly?
I thought I saw this fail in GitHub CI but not regular CI.

I think it was https://github.com/cockroachdb/cockroach/pull/75961/commits/f68d807c4b7b9d81931b81ae0c2ff179a485f68c: 

* https://teamcity.cockroachdb.com/viewLog.html?buildId=4294434&buildTypeId=Cockroach_UnitTests
* https://teamcity.cockroachdb.com/viewLog.html?buildId=4294400&buildTypeId=Cockroach_GitHubCiOptional

Epic CRDB-8036

Jira issue: CRDB-12967

### LINKED ISSUE #79520: bazel: is `errcheck` lint running properly in `nogo`?
I have a [CI run](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_UnitTests/4803257?showRootCauses=false&expandBuildChangesSection=true&expandBuildProblemsSection=true&expandBuildTestsSection=true) that failed GitHub CI due to failed `errcheck` but `bazel build` with `nogo` turned on has no problem with it.

    === RUN   TestLint/TestErrCheck
    lint_test.go:1604: pkg/cmd/dev/generate.go:212:14:  tpl.Execute(out, struct { <- unchecked error
    --- FAIL: TestLint/TestErrCheck (69.49s)

Epic CRDB-8036

### PR DESCRIPTION
**Pull request by rickystewart**
When I wrote the `nogo` config originally, I identified first-party
lintable code by checking against the string
`github.com/cockroachdb/cockroach`. At some point in the last couple
months (may be related to a `rules_go` upgrade) this became
insufficient. Now I use the string `cockroach/pkg` to match for first-
party code which seems to work.

While getting these lints working again I fixed a few errors that
popped up and added one exception for already-suspect code: #79926.

Closes #79520.
Closes #76075.

Release note: None

### CODE REVIEW

File: pkg/util/log/eventpb/gen.go [hunk 1]
```diff
@@ -121,7 +121,7 @@ func run() error {
 	}
 	tmpl, err := template.New(tmplName).Funcs(tmplFuncs).Parse(tmplSrc)
 	if err != nil {
-		return errors.Wrap(err, tmplName)
+		return errors.Wrap(err, "failed to parse template")
```
Comment (miretskiy) [inline pkg/util/log/eventpb/gen.go:124]: how about `errors.Wrapf(err, "failed to parse template %q", tplName)`

**Review by miretskiy — APPROVED** [review]

**Review by knz — APPROVED** [review]
nice, thanks

**Review by mari-crl — APPROVED** [review]
Most excellent! :D :lgtm: 

> Reviewed 3 of 5 files at r1, 5 of 5 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/79929#-:-N-d74yEC0lMVKSPu6ag:b-iuuuxx)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @rickystewart)

**Comment by rickystewart** [comment]
TFTRs!

bors r=miretskiy,knz,mari-crl
