### PR TITLE
cliccl/load: fix flaky TestLoadShowBackups and TestLoadShowIncremental

### LINKED ISSUE #62111: cliccl: TestLoadShowBackups is flaky
```
⌂75% radu (master)+ ~/roach 39s # make stress PKG=./pkg/ccl/cliccl TESTS=TestLoadShowBackups
Running make with -j12
GOPATH set to /go
mkdir -p lib
rm -f lib/lib{geos,geos_c}.so
cp -L /go/native/x86_64-linux-gnu/geos/lib/lib{geos,geos_c}.so lib
GOFLAGS= go test   -mod=vendor -exec 'stress ' -tags ' gss make x86_64_linux_gnu crdb_test' -ldflags '-X github.com/cockroachdb/cockroach/pkg/build.typ=development -extldflags "" -X "github.com/cockroachdb/cockroach/pkg/build.tag=v21.1.0-alpha.3-1497-g998ba06004" -X "github.com/cockroachdb/cockroach/pkg/build.rev=998ba06004a8eac6eb2620f1e9523465a9e41b86" -X "github.com/cockroachdb/cockroach/pkg/build.cgoTargetTriple=x86_64-linux-gnu"  ' -run "TestLoadShowBackups" -timeout 0 ./pkg/ccl/cliccl  -v -args -test.timeout 30m
164 runs so far, 0 failures, over 5s
327 runs so far, 0 failures, over 10s

=== RUN   TestLoadShowBackups
    test_log_scope.go:73: test logs captured to: /tmp/logTestLoadShowBackups172353475
    test_log_scope.go:74: use -show-logs to present logs inline
    test_log_scope.go:73: test logs captured to: /tmp/logTestLoadShowBackups419037933
    test_log_scope.go:74: use -show-logs to present logs inline
=== RUN   TestLoadShowBackups/show-backups-without-backups-in-collection
[load show backups nodelocal://0/fooFolder --external-io-dir=/tmp/TestLoadShowBackups109461864]
=== RUN   TestLoadShowBackups/show-backups-with-backups-in-collection
[load show backups nodelocal://0/fooFolder --external-io-dir=/tmp/TestLoadShowBackups109461864]
    load_test.go:208: 
        	Error Trace:	load_test.go:208
        	            				load_test.go:156
        	Error:      	Not equal: 
        	            	expected: "./2021/03/16-205915.92\n./2021/03/16-205915.96\n./2021/03/16-205915.96\n"
        	            	actual  : "./2021/03/16-205915.92\n./2021/03/16-205915.96\n"
        	            	
        	            	Diff:
        	            	--- Expected
        	            	+++ Actual
        	            	@@ -2,3 +2,2 @@
        	            	 ./2021/03/16-205915.96
        	            	-./2021/03/16-205915.96
        	            	 
        	Test:       	TestLoadShowBackups/show-backups-with-backups-in-collection
=== CONT  TestLoadShowBackups
    testutils.go:210: -- test log scope end --
test logs left over in: /tmp/logTestLoadShowBackups419037933
    load_test.go:158: -- test log scope end --
--- FAIL: TestLoadShowBackups (0.21s)
    --- PASS: TestLoadShowBackups/show-backups-without-backups-in-collection (0.01s)
    --- FAIL: TestLoadShowBackups/show-backups-with-backups-in-collection (0.00s)
FAIL
```

### PR DESCRIPTION
**Pull request by Elliebababa**
Previously, TestLoadShowBackups and TestLoadShowIncremental use
timestamps as backup folder names without checking the
intervals between the timestamps. This is flaky when the interval is less
than 10 milliseconds because folder names generated in format of
DateBasedIncFolderName or DateBasedIntoFolderName will be the same.

This patch checks the intervals of generated timestamps to ensure that
the incremental backups are actually created in different folders.

Resolves: #62111

Release note: none.

### CODE REVIEW

File: pkg/ccl/cliccl/load_test.go [hunk 1]
```diff
@@ -207,3 +195,24 @@ func checkExpectedOutput(t *testing.T, expected string, out string) {
 	output := out[endOfCmd+1:]
 	require.Equal(t, expected, output)
 }
+
+// Generate n continuous TimeStamps with minimal interval of 10 milliseconds to be used in incremental backup tests.
+func generateContinuousTimeStamps(n int) []hlc.Timestamp {
```
Comment (pbardea) [inline pkg/ccl/cliccl/load_test.go:200]: Are these timestamps continuous? Maybe a name such as `generateTimestampsWithMinInterval` would be a more descriptive name? Or maybe just `generateBackupTimestamps`?

I also think it would be useful to mention that incremental backup collections are stored in a sub-directory structure that assumes that backups are taken at least 10 milliseconds apart.

File: pkg/ccl/cliccl/load_test.go [hunk 2]
```diff
@@ -207,3 +195,24 @@ func checkExpectedOutput(t *testing.T, expected string, out string) {
...
+	timeStamps := make([]hlc.Timestamp, 0, n)
+	if n == 0 {
+		return timeStamps
+	}
+	lastTS := hlc.Timestamp{WallTime: timeutil.Now().UnixNano()}
```
Comment (pbardea) [inline pkg/ccl/cliccl/load_test.go:205]: nit: this may be a bit easier to read if `lastTS` is a `time.Time` and it's only converted to an hlc.Timestamp when added to `timeStamps`.

File: pkg/ccl/cliccl/load_test.go [hunk 3]
```diff
@@ -207,3 +195,24 @@ func checkExpectedOutput(t *testing.T, expected string, out string) {
...
+	timeStamps = append(timeStamps, lastTS)
+	for {
```
Comment (pbardea) [inline pkg/ccl/cliccl/load_test.go:207]: nit: Have you considered the approach of doing a simple loop and just sleeping between the iterations? That looks like it would do what we want and may be easier to reason through:

```
for i := 0; i < n; i++ {
    timestamps = append(timestamps, hlc.Timestamp{WallTime: timeutil.Now().UnixNano()})
    time.sleep(10 * time.Millisecond)
}
```

File: pkg/ccl/cliccl/load_test.go (hunk 1 above)
Comment (pbardea) [reply pkg/ccl/cliccl/load_test.go:200]: nit: Let's also wrap the comment to be 80 chars

Comment (Elliebababa) [reply pkg/ccl/cliccl/load_test.go:200]: Done.

File: pkg/ccl/cliccl/load_test.go (hunk 3 above)
Comment (Elliebababa) [reply pkg/ccl/cliccl/load_test.go:207]: yea.. much more easier. updated

**Review by pbardea — APPROVED** [review]
LGTM

**Comment by Elliebababa** [comment]
TFTR!

bors r=pbardea
