### PR TITLE
roachtest: update hibernate test to use 6.3.1

### LINKED ISSUE #111402: roachtest: add Hibernate nightly roachtest for version 6.x
Our Hibernate test is pinned to version 5.6.15
https://github.com/cockroachdb/cockroach/blob/5eb4a53a0d1e6d2c9e49c4382f931e98bbe0968d/pkg/cmd/roachtest/tests/hibernate.go#L26

We need to also add another test for Hibernate 6.x and assess what fails. CRDB is already running on the main Hibernate repo so nothing should break but we still need to verify. Both 5.6 and 6.x are supported by Hibernate so we should have both tests.

context in https://cockroachlabs.slack.com/archives/CPD3ANLMB/p1695856646208149

Jira issue: CRDB-31885

### PR DESCRIPTION
**Pull request by andyyang890**
Fixes: #111402

Release note: None

### CODE REVIEW

**Comment by andyyang890** [comment]
Here is a successful TeamCity run of both `hibernate` and `hibernate-spatial` on this branch: https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/12375542?hideProblemsFromDependencies=false&hideTestsFromDependencies=false

**Review by herkolategan — APPROVED** [review]

**Review by rafiss — APPROVED** [review]
very nice!

File: pkg/cmd/roachtest/tests/hibernate.go [hunk 1]
```diff
@@ -26,7 +26,7 @@ var hibernateReleaseTagRegex = regexp.MustCompile(`^(?P<major>\d+)\.(?P<minor>\d
 
 // WARNING: DO NOT MODIFY the name of the below constant/variable without approval from the docs team.
 // This is used by docs automation to produce a list of supported versions for ORM's.
-var supportedHibernateTag = "5.6.15"
+var supportedHibernateTag = "6.3.1"
```
Comment (mikeCRL) [inline pkg/cmd/roachtest/tests/hibernate.go:29]: @andyyang890 I see that we pull this number into docs on the Java row [here](https://www.cockroachlabs.com/docs/stable/third-party-database-tools#data-access-frameworks-e-g-orms) for CRDB 23.1+.

1. Should I make a change to the docs code so that this new supported version is only displayed for 23.2+? What we did [for 22.2](https://github.com/cockroachdb/docs/blob/main/src/current/_includes/v22.2/misc/tooling.md?plain=1#L48) is pull this Hibernate version from the `cockroach` `release-22.2` branch, so this value won't change based on what's on `master`. I assume it would make sense to similarly freeze the 23.1 number at 5.6.15, for now, pulling directly from the `release-23.1` branch. Would you agree?

2. The resulting text in the docs (from the current `cockroachdb:master`) is "5.6.15 (must be at least 5.4.19)". Only the first version number comes from `hibernate.go`. The parenthetical minimum version is hard-coded. I assume it's OK to leave that min version of 5.4.19 as-is; can you confirm?

**Review by mikeCRL — COMMENTED** [review]
Change LGTM, but I'd like to confirm desired docs impacts with you before we merge.

File: pkg/cmd/roachtest/tests/hibernate.go (hunk 1 above)
Comment (andyyang890) [reply pkg/cmd/roachtest/tests/hibernate.go:29]: 1. Yeah I think it makes sense to pull the version from each release branch. I'll be backporting this PR eventually so `release-22.2` and `release-23.1` should be updated soon.

2. We can keep the min version for now until we find a reason we need to bump it higher.

Comment (mikeCRL) [reply pkg/cmd/roachtest/tests/hibernate.go:29]: Thanks. Raised https://github.com/cockroachdb/docs/pull/18018 and requested a quick review from my team.

**Comment by andyyang890** [comment]
TFTRs!

bors r=herkolategan,rafiss

**Review by mikeCRL — APPROVED** [review]
