### PR TITLE
sql/catalog: avoid cached lease descriptors for validation

### LINKED ISSUE #79396: sql/catalog: stale leased descriptors can lead to validation errors
**Describe the problem**

Please describe the issue you observed, and any steps we can take to reproduce it:

When running the randomized schema changer workload we found that the validation logic
can intermittently fail if the transaction looked up a leased descriptor earlier. For example,
when binding OIDs we may use an older version of a leased descriptor, versus the
one we should be validating against. When the validation logic kicks in it can then use 
the incorrect version of the descriptor for dependent objects, which can lead
to validation errors.

**To Reproduce**

The easiest reproduction is to run schemachanger/random-load concurrently 8 ways and the reproduction can be hit in < 5 minutes. Normally involving a view backreference not being found in a table descriptor.

Jira issue: CRDB-14799

### PR DESCRIPTION
**Pull request by fqazi**
Fixes: #79396

Previously, to optimize validation we would use leased
descriptors from inside the collection for validation.
This could be problematic since there are cases where
stale descriptors may be leased, for example for OID
looks up during the bind, which can cause incorrect
validation errors if any dependent objects are looked
up. To address this, this patch removes the optimization
that prefers the use of cached leased descriptors and instead
goes through the normal look-up logic.

Release note: None

Jira issue: CRDB-14800

### CODE REVIEW

**Comment by chengxiong-ruan** [comment]
*[pkg/sql/catalog/descs/validate.go, line 97 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/79397#-MzrZ10_D8kSxmDoZoLh:-MzrZ10_D8kSxmDoZoLi:b-6g0wlu) ([raw file](https://github.com/cockroachdb/cockroach/blob/400483956bbc9fe439ba95113ccc577d20627698/pkg/sql/catalog/descs/validate.go#L97)):*
> ```Go
> 		}
> 		if uc, _ := c.tc.uncommitted.getImmutableByID(desc.GetID()); uc == nil {
> 			desc, err = c.tc.uncommitted.add(desc.NewBuilder().BuildExistingMutable(), notValidatedYet)
> ```

curious what's the benefit of caching newly read descriptors into the uncommitted layer since we're not trying to update these descriptors anyway right?

File: pkg/sql/catalog/descs/validate.go [hunk 1]
```diff
@@ -79,64 +78,32 @@ var _ validate.ValidationDereferencer = &collectionBackedDereferencer{}
...
-) (catalog.Descriptor, error) {
-	if uc, status := c.tc.uncommitted.getImmutableByID(id); uc != nil {
-		if status == checkedOutAtLeastOnce {
-			return nil, nil
-		}
-		return uc, nil
-	}
-	if ld := c.tc.leased.cache.GetByID(id); ld != nil {
-		return ld.(lease.LeasedDescriptor).Underlying(), nil
-	}
```
Comment (postamar) [inline pkg/sql/catalog/descs/validate.go:136]: If you want to avoid the leased descriptor cache, shouldn't you only be removing this `if` block and leave the other one?

File: pkg/ccl/benchccl/rttanalysisccl/testdata/benchmark_expectations [hunk 2]
```diff
@@ -1,19 +1,19 @@
...
+21,AlterSurvivalGoals/alter_empty_database_from_region_to_zone
+21,AlterSurvivalGoals/alter_empty_database_from_zone_to_region
+41,AlterSurvivalGoals/alter_populated_database_from_region_to_zone
+41,AlterSurvivalGoals/alter_populated_database_from_zone_to_region
+23,AlterTableLocality/alter_from_global_to_rbr
+26,AlterTableLocality/alter_from_global_to_regional_by_table
+19,AlterTableLocality/alter_from_rbr_to_global
+19,AlterTableLocality/alter_from_rbr_to_regional_by_table
+26,AlterTableLocality/alter_from_regional_by_table_to_global
+23,AlterTableLocality/alter_from_regional_by_table_to_rbr
```
Comment (postamar) [inline pkg/ccl/benchccl/rttanalysisccl/testdata/benchmark_expectations:19]: Those are some significant performance regressions. Is this PR really the best that can be done to address the issue at hand?

**Review by postamar — CHANGES_REQUESTED** [review]
This needs either more work or more justification as to why we can't use any cache at all.

**Comment by postamar** [comment]
> curious what's the benefit of caching newly read descriptors into the uncommitted layer since we're not trying to update these descriptors anyway right?

We might want to mutate them later on in the transaction. Really the caching should be in the `kvDescriptors` layer but that would imply that and the uncommitted layer would need to talk to each other, because mutating a descriptor would have to invalidate the corresponding kv cache entry.

**Comment by postamar** [comment]
I can't even remember why or how we thought it would be OK to do this, to be honest.

File: pkg/sql/catalog/descs/validate.go (hunk 1 above)
Comment (ajwerner) [reply pkg/sql/catalog/descs/validate.go:136]: Yes, that's correct. I think it'll help some of the benchmarks too. We should still be checking the `uncommitted` set.

**Review by fqazi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/79397)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @chengxiong-ruan and @postamar)

___
*[pkg/sql/catalog/descs/validate.go, line 97 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/79397#-MzrZ10_D8kSxmDoZoLh:-MzulZsa0iyy5jbtU4Ms:b-t5qtqs) ([raw file](https://github.com/cockroachdb/cockroach/blob/400483956bbc9fe439ba95113ccc577d20627698/pkg/sql/catalog/descs/validate.go#L97)):*
<details><summary><i>Previously, chengxiong-ruan (Chengxiong Ruan) wrote…</i></summary><blockquote>

curious what's the benefit of caching newly read descriptors into the uncommitted layer since we're not trying to update these descriptors anyway right?
</blockquote></details>

I think the assumption here is that it will help future look-ups by not doing KV requests.
___
*[pkg/ccl/benchccl/rttanalysisccl/testdata/benchmark_expectations, line 19 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/79397#-MzstDFUUW78S1GJQTgk-r2-19:-MzulgxvCyn3qW3uN213:bcup4uo) ([raw file](https://github.com/cockroachdb/cockroach/blob/400d81016c27c1bf8d4b09208ccaba2f29a3f5eb/pkg/ccl/benchccl/rttanalysisccl/testdata/benchmark_expectations#L19)):*
<details><summary><i>Previously, postamar (Marius Posta) wrote…</i></summary><blockquote>

Those are some significant performance regressions. Is this PR really the best that can be done to address the issue at hand? 
</blockquote></details>

My mistake was dropping the uncommitted cache check these should be more reasonable now. Good find!

**Review by postamar — APPROVED** [review]
LGTM! I must admit, I'm pleasantly surprised by how benign the performance regressions are in this revision.

**Comment by fqazi** [comment]
@postamar TFTR!
