### PR TITLE
pkg/cmd/roachtest: Disable autocommit_before_ddl

### LINKED ISSUE #140315: roachtest: backup-restore/large-schema/tables=10000 failed
roachtest.backup-restore/large-schema/tables=10000 [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestWeeklyBazel/18692389?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestWeeklyBazel/18692389?buildTab=artifacts#/backup-restore/large-schema/tables=10000) on master @ [f7d019d5e675fa2711b61ffd54a9990b6a1a1da8](https://github.com/cockroachdb/cockroach/commits/f7d019d5e675fa2711b61ffd54a9990b6a1a1da8):

```
(assertions.go:363).Fail: 
	Error Trace:	pkg/cmd/roachtest/tests/large_schema_backup_restore.go:80
	            				pkg/cmd/roachtest/test_runner.go:1315
	            				src/runtime/asm_amd64.s:1695
	Error:      	Received unexpected error:
	            	pq: unexpected transaction status idle
	Test:       	backup-restore/large-schema/tables=10000
(require.go:1357).NoError: FailNow called
test artifacts and logs in: /artifacts/backup-restore/large-schema/tables=10000/run_1
```

Parameters:
 - <code>arch=amd64</code>
 - <code>cloud=gce</code>
 - <code>coverageBuild=false</code>
 - <code>cpu=8</code>
 - <code>encrypted=false</code>
 - <code>fs=ext4</code>
 - <code>localSSD=true</code>
 - <code>runtimeAssertionsBuild=false</code>
 - <code>ssd=0</code>
<details><summary>Help</summary>
<p>

See: [roachtest README](https://github.com/cockroachdb/cockroach/blob/master/pkg/cmd/roachtest/README.md)

See: [How To Investigate \(internal\)](https://cockroachlabs.atlassian.net/l/c/SSSBr8c7)

See: [Grafana](https://go.crdb.dev/roachtest-grafana/teamcity-18692389/backup-restore-large-schema-tables-10000/1738393058030/1738393644443)

</p>
</details>
/cc @cockroachdb/disaster-recovery
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*backup-restore/large-schema/tables=10000.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/bazci/githubpost/issues)

</sub>

Jira issue: CRDB-47085

### PR DESCRIPTION
**Pull request by benbardin**
Tested locally, test consistently fails without this change and passes with it.

Fixes: #140315
Release note: None

### CODE REVIEW

**Review by msbutler — APPROVED** [review]
Thanks for double checking!

File: pkg/cmd/roachtest/tests/large_schema_backup_restore.go [hunk 1]
```diff
@@ -56,6 +56,9 @@ func largeSchemaBackupRestore(r registry.Registry, numTables int) {
 			conn := c.Conn(ctx, t.L(), 1)
 			defer conn.Close()
 
+			_, err := conn.ExecContext(ctx, "SET autocommit_before_ddl = false")
```
Comment (rafiss) [inline pkg/cmd/roachtest/tests/large_schema_backup_restore.go:59]: might be worth a comment mentioning that creating the objects in one transaction is significantly faster

Comment (benbardin) [reply pkg/cmd/roachtest/tests/large_schema_backup_restore.go:59]: done!

Comment (dt) [reply pkg/cmd/roachtest/tests/large_schema_backup_restore.go:59]: `conn` here is a `*sql.DB` right, which is backed by a conn _pool_ isn't it? Do we need to `SET` in the tx to be sure it applies to the right conn?

Comment (benbardin) [reply pkg/cmd/roachtest/tests/large_schema_backup_restore.go:59]: oof, is it really? lemme open a new pr
