### PR TITLE
tracing: fix DRPC span naming

### LINKED ISSUE #158323: sql: TestTrace failed
sql.TestTrace [failed](https://mesolite.cluster.engflow.com/invocations/default/913f1733-e94d-49de-b251-c8fe2a31df44?testReportRun=1&testReportShard=14&testReportAttempt=1#targets-Ly9wa2cvc3FsOnNxbF90ZXN0) on master @ [dba914a42e73cbb22ca24dcc58fc89fde8be87a6](https://github.com/cockroachdb/cockroach/commits/dba914a42e73cbb22ca24dcc58fc89fde8be87a6):

```
        read-only path
        sequencing request
        acquiring latches
        scanning lock table for conflicting locks
        can't serve follower read; closed timestamp too low by: 3.667483889s; maxClosed: 1764062586.914060984,0 ts: 1764062590.081544873,0 uncertaintyLimit: 1764062590.581544873,0
        replica.Send got error: [NotLeaseHolderError] lease held by different store; r79: replica (n3,s3):2 not lease holder; current lease is repl=(n1,s1):1 seq=1 start=0,0 type=LeaseEpoch epo=1 min-exp=0,0 pro=1764062577.298034422,0 acq=Request
        error from stores.Send: [NotLeaseHolderError] lease held by different store; r79: replica (n3,s3):2 not lease holder; current lease is repl=(n1,s1):1 seq=1 start=0,0 type=LeaseEpoch epo=1 min-exp=0,0 pro=1764062577.298034422,0 acq=Request: "sql txn" meta={id=6b6eed15 key=/Min iso=Serializable pri=0.02571349 epo=0 ts=1764062590.081544873,0 min=1764062590.081544873,0 seq=0} lock=false stat=PENDING rts=1764062590.081544873,0 gul=1764062590.581544873,0 obs={n3@1764062590.081544873,0}
        node sending response
        received batch response
        [NotLeaseHolderError] lease held by different store; r79: replica (n3,s3):2 not lease holder; current lease is repl=(n1,s1):1 seq=1 start=0,0 type=LeaseEpoch epo=1 min-exp=0,0 pro=1764062577.298034422,0 acq=Request: "sql txn" meta={id=6b6eed15 key=/Min iso=Serializable pri=0.02571349 epo=0 ts=1764062590.081544873,0 min=1764062590.081544873,0 seq=0} lock=false stat=PENDING rts=1764062590.081544873,0 gul=1764062590.581544873,0 obs={n3@1764062590.081544873,0}
        backing off due to NotLeaseHolderErr with stale info (updatedLH=false intentionallySentToFollower=false leaseholderUnavailable=false)
        will retry after 48.969039ms
        application error: [NotLeaseHolderError] lease held by different store; r79: replica (n3,s3):2 not lease holder; current lease is repl=(n1,s1):1 seq=1 start=0,0 type=LeaseEpoch epo=1 min-exp=0,0 pro=1764062577.298034422,0 acq=Request: "sql txn" meta={id=6b6eed15 key=/Min iso=Serializable pri=0.02571349 epo=0 ts=1764062590.081544873,0 min=1764062590.081544873,0 seq=0} lock=false stat=PENDING rts=1764062590.081544873,0 gul=1764062590.581544873,0 obs={n3@1764062590.081544873,0}
        trying next peer (n1,s1):1
        sending request to 127.0.0.1:40349
        sending batch request
        === SPAN START: /cockroach.roachpb.KVBatch/Batch ===
        === SPAN START: /cockroach.roachpb.Internal/Batch ===
        node received request: 1 Scan
        executing Scan [/Table/106/1,/Table/106/2), [txn: 6b6eed15], [can-forward-ts], [max_span_request_keys: 0], [target_bytes: 39009]
        read-only path
        sequencing request
        acquiring latches
        scanning lock table for conflicting locks
        can drop latches early for batch (Scan [/Table/106/1,/Table/106/2), [txn: 6b6eed15], [can-forward-ts], [max_span_request_keys: 0], [target_bytes: 39009]); scanning lock table first to detect conflicts
        lock table scan stats: seeked 1 times (1 internal); stepped 0 times (0 internal)
        lock table scan complete without conflicts; dropping latches early
        executing read-only batch
        evaluated Scan command header:<key:"\362\211" end_key:"\362\212" > scan_format:BATCH_RESPONSE , txn="sql txn" meta={id=6b6eed15 key=/Min iso=Serializable pri=0.02571349 epo=0 ts=1764062590.081544873,0 min=1764062590.081544873,0 seq=0} lock=false stat=PENDING rts=1764062590.081544873,0 gul=1764062590.581544873,0 obs={n1@1764062590.142210081,0 n3@1764062590.081544873,0} : resp=header:<> col_batches:<> , err=<nil>
        n1 scan stats: stepped 0 times (0 internal); seeked 1 times (1 internal); block-bytes: (total 0 B, cached 0 B, duration 0s); points: (count 0, key-bytes 0 B, value-bytes 0 B, tombstoned: 0) ranges: (count 0), (contained-points 0, skipped-points 0) evaluated requests: 0 gets, 1 scans, 0 reverse scans
        read completed
        node sending response
        received batch response
        recording span to refresh: /Table/106/{1-2}
        ComponentStats{ID: {39a16bf5-3a98-42ce-bc8a-b979ab432b45 PROCESSOR 0 3 }, KV nodes: n1, KV regions: test, KV time: 57ms, KV rows decoded: 0, KV bytes read: 0 B, KV gRPC calls: 1, KV pairs read: 0, MVCC step count (ext/int): 0/0, MVCC seek count (ext/int): 1/1, rows output: 0}
        ComponentStats{ID: {39a16bf5-3a98-42ce-bc8a-b979ab432b45 FLOW 0 3 test}}
        execution ends
        rows affected: 0
        === SPAN START: commit sql txn ===
        AutoCommit. err: <nil>
        releasing 4 descriptors
        release: 100("defaultdb",01018016169fe7564244ed9de88124afac465d) ver=1:0,0, refcount=0
        release: 104("test",01018016169fe7564244ed9de88124afac465d) ver=1:0,0, refcount=0
        release: 105("public",01018016169fe7564244ed9de88124afac465d) ver=1:0,0, refcount=0
        release: 106("foo",01018016169fe7564244ed9de88124afac465d) ver=1:0,0, refcount=0
        [NoTxn pos:10] executing ExecStmt: SET TRACING = off
        executing: SET TRACING = off in state: NoTxn
--- FAIL: TestTrace/ShowTraceFor/TracingOn/node-2 (0.13s)
=== RUN   TestTrace/ShowTraceForVectorized/TracingOff
--- FAIL: TestTrace/ShowTraceForVectorized/TracingOff (0.27s)
```

Parameters:
 - <code>attempt=1</code>
 - <code>deadlock=true</code>
 - <code>run=1</code>
 - <code>shard=14</code>
<details><summary>Help</summary>
<p>

See also: [How To Investigate a Go Test Failure \(internal\)](https://cockroachlabs.atlassian.net/l/c/HgfXfJgM)
</p>
</details>
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*TestTrace.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/bazci/githubpost/issues)

</sub>

Jira issue: CRDB-57241

Epic CRDB-55382

### PR DESCRIPTION
**Pull request by Nukitt**
Previously, when DRPC was enabled, the server-side span naming in
`setupSpanForIncomingRPC` always used the gRPC method name
(/cockroach.roachpb.Internal/Batch) regardless of whether the request
came via gRPC or DRPC. This caused TestTrace to fail when DRPC was
enabled because it expected specific span names.

This commit fixes the issue by injecting the RPC method name into the
context in DRPC server interceptors and updates setupSpanForIncomingRPC
to use that method name for span naming. More details in : https://github.com/cockroachdb/cockroach/issues/158323#issuecomment-3890481696

Epic: CRDB-55382
Fixes: #158323
Release note: None

### CODE REVIEW

**Comment by suj-krishnan** [comment]
> The fix looks good to me, except I didn't understand the issue fully. Could you take a look at my query [here](https://github.com/cockroachdb/cockroach/issues/158323#issuecomment-3817125165)?

Thanks for the explanation. I might be missing something here but since "/cockroach.roachpb.KVBatch/Batch" is in `alwaysOptionalSpans` and we ignore optional spans in the output, why did the test fail for drpc?

**Comment by suj-krishnan** [comment]
> > The fix looks good to me, except I didn't understand the issue fully. Could you take a look at my query [here](https://github.com/cockroachdb/cockroach/issues/158323#issuecomment-3817125165)?
> 
> Thanks for the explanation. I might be missing something here but since "/cockroach.roachpb.KVBatch/Batch" is in `alwaysOptionalSpans` and we ignore optional spans in the output, why did the test fail for drpc?

Never mind! As discussed, I missed noticing that adding /cockroach.roachpb.KVBatch/Batch as an optional span was a temporary fix for the same issue.

File: pkg/util/tracing/drpcinterceptor/drpc_interceptor.go [hunk 1]
```diff
@@ -144,7 +144,7 @@ func ClientInterceptor(
 		cc *drpcclient.ClientConn,
 		invoker drpcclient.UnaryInvoker,
 	) error {
-		if tracingutil.ShouldSkipClientTracing(ctx) {
+		if tracingutil.ShouldSkipClientTracing(ctx) || tracingutil.MethodExcludedFromTracing(rpc) {
```
Comment (suj-krishnan) [inline pkg/util/tracing/drpcinterceptor/drpc_interceptor.go]: We should add unit tests that check that method exclusions work correctly in both the client and server interceptors. `TestTrace` can also flag incorrect exclusions, but as it turns out, in this case, although `/cockroach.roachpb.Internal/Batch` is marked for exclusion in the grpc interceptors, it still seems to generate span (using a different mechanism that does not use interceptors) and is therefore under expected spans, masking the exclusion issue.

**Review by suj-krishnan — COMMENTED** [review]
Another adjacent issue that came up in our offline discussion seems to be that the span for `/cockroach.roachpb.KVBatch/Batch` is different on the client and server side. If that's not by design, we should probably fix it.

**Review by yuzefovich — COMMENTED** [review]
> @yuzefovich reviewed 6 files and all commit messages, and made 3 comments.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/161930)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @cthumuluru-crdb, @dhartunian, @Nukitt, @shubhamdhama, and @visheshbardia).

___
*[`pkg/util/tracing/drpcinterceptor/drpc_interceptor.go` line 26 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/161930#-OlIEjKx-8rMZnsC106m:-OlIEjKx-8rMZnsC106n:b8a2nd9) ([raw file](https://github.com/cockroachdb/cockroach/blob/d9fbe68d1e2a5662e39d98e5bde9a6a3f8dc399b/pkg/util/tracing/drpcinterceptor/drpc_interceptor.go#L26)):*
> ```Go
> 
> // rpcMethodKey is the context key type for storing the RPC method name.
> type RpcMethodKey struct{}
> ```

nit: we usually don't export the context keys and, instead, provide exported helper method to add / get the target string from the context.
___
*[`pkg/util/tracing/drpcinterceptor/drpc_interceptor.go` line 133 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/161930#-OlI6I3b0faVUw8vvssV:-OlI6I3c2vtiA31DMiF9:b-ejfwkj) ([raw file](https://github.com/cockroachdb/cockroach/blob/d9fbe68d1e2a5662e39d98e5bde9a6a3f8dc399b/pkg/util/tracing/drpcinterceptor/drpc_interceptor.go#L133)):*
> ```Go
> // that includes the rpc method name.
> func (s *rpcContextStream) Context() context.Context {
> 	return context.WithValue(s.Stream.Context(), RpcMethodKey{}, s.rpc)
> ```

This will create a new `context.Context` object on every call - we should probably cache the object on the first call and then reuse it on later calls.
___
*[`pkg/server/node.go` line 2022 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/161930#-OlIFR9Z7bDp01b25rZB:-OlIFR9_2X5Hlyx7xVFj:b-d4dbeq) ([raw file](https://github.com/cockroachdb/cockroach/blob/d9fbe68d1e2a5662e39d98e5bde9a6a3f8dc399b/pkg/server/node.go#L2022)):*
> ```Go
> 	var newSpan *tracing.Span
> 	remoteParent := !ba.TraceInfo.Empty()
> 	// DRPC interceptors set the RPC method in the context; if present, use it.
> ```

Why do we not need to do something similar in gRPC? Is it because `grpc.UnaryServerInfo.FullMethod` always gives us the RPC method which we don't have with DRPC? It might be worth mentioning the rationale in the comment.

**Review by Nukitt — COMMENTED** [review]
> @Nukitt made 3 comments and resolved 1 discussion.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/161930)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @cthumuluru-crdb, @dhartunian, @shubhamdhama, @visheshbardia, and @yuzefovich).

___
*[`pkg/server/node.go` line 2022 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/161930#-OlIFR9Z7bDp01b25rZB:-OlKEAF0-Sg_G6DwTPM1:b125tqu) ([raw file](https://github.com/cockroachdb/cockroach/blob/d9fbe68d1e2a5662e39d98e5bde9a6a3f8dc399b/pkg/server/node.go#L2022)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

Why do we not need to do something similar in gRPC? Is it because `grpc.UnaryServerInfo.FullMethod` always gives us the RPC method which we don't have with DRPC? It might be worth mentioning the rationale in the comment.
</blockquote></details>

yup exactly, added a coment.
___
*[`pkg/util/tracing/drpcinterceptor/drpc_interceptor.go` line 26 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/161930#-OlIEjKx-8rMZnsC106m:-OlKEH6t5jE-wkiYS0AP:b-7rl0jd) ([raw file](https://github.com/cockroachdb/cockroach/blob/d9fbe68d1e2a5662e39d98e5bde9a6a3f8dc399b/pkg/util/tracing/drpcinterceptor/drpc_interceptor.go#L26)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

nit: we usually don't export the context keys and, instead, provide exported helper method to add / get the target string from the context.
</blockquote></details>

done.
___
*[`pkg/util/tracing/drpcinterceptor/drpc_interceptor.go` line 133 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/161930#-OlI6I3b0faVUw8vvssV:-OlKENpu-XvepQrer0ZU:b8vxhpp) ([raw file](https://github.com/cockroachdb/cockroach/blob/d9fbe68d1e2a5662e39d98e5bde9a6a3f8dc399b/pkg/util/tracing/drpcinterceptor/drpc_interceptor.go#L133)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

This will create a new `context.Context` object on every call - we should probably cache the object on the first call and then reuse it on later calls.
</blockquote></details>

yeah makes sense, done.

File: pkg/testutils/serverutils/test_server_shim.go [hunk 2]
```diff
@@ -244,12 +244,26 @@ var globalDefaultDRPCOptionOverride struct {
 	value base.DefaultTestDRPCOption
 }
 
+// resolvedDRPCOption caches the resolved DRPC decision after
```
Comment (suj-krishnan) [inline pkg/testutils/serverutils/test_server_shim.go]: A better way might be to expose a method from `TestClusterInterface` like `DRPCEnabled()` (similar to `StartedDefaultTestTenant`)

**Review by yuzefovich — APPROVED** [review]
> @yuzefovich reviewed 2 files and all commit messages, and resolved 2 discussions.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/161930)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @cthumuluru-crdb, @dhartunian, @Nukitt, @shubhamdhama, and @visheshbardia).

File: pkg/testutils/serverutils/test_server_shim.go (hunk 2 above)
Comment (shubhamdhama) [reply pkg/testutils/serverutils/test_server_shim.go]: +1

File: pkg/server/node.go [hunk 3]
```diff
@@ -2018,12 +2019,20 @@ func setupSpanForIncomingRPC(
 ) (context.Context, spanForRequest) {
 	var newSpan *tracing.Span
 	remoteParent := !ba.TraceInfo.Empty()
+	// DRPC server interceptors inject the method name into the context
+	// because DRPC uses different method names (/cockroach.roachpb.KVBatch/Batch).
+	// For gRPC and local requests, we fall back to tracingutil.BatchMethodName
+	// (/cockroach.roachpb.Internal/Batch), so gRPC interceptors don't need to inject it.
+	methodName := tracingutil.BatchMethodName
+	if rpc, ok := drpcinterceptor.RPCMethodFromContext(ctx); ok {
```
Comment (shubhamdhama) [inline pkg/server/node.go]: How about if we not store the value? Just store the key and check for its presence.

File: pkg/util/tracing/drpcinterceptor/drpc_interceptor.go [hunk 4]
```diff
@@ -188,7 +213,7 @@ func StreamClientInterceptor(
 		cc *drpcclient.ClientConn,
 		streamer drpcclient.Streamer,
 	) (drpc.Stream, error) {
-		if tracingutil.ShouldSkipClientTracing(ctx) {
+		if tracingutil.ShouldSkipClientTracing(ctx) || tracingutil.MethodExcludedFromTracing(rpc) {
```
Comment (shubhamdhama) [inline pkg/util/tracing/drpcinterceptor/drpc_interceptor.go]: Please move `MethodExcludedFromTracing` call to `ShouldSkipClientTracing`.

Comment (shubhamdhama) [reply pkg/util/tracing/drpcinterceptor/drpc_interceptor.go]: Hold on this for some time.

File: pkg/server/node.go (hunk 3 above)
Comment (Nukitt) [reply pkg/server/node.go]: nice idea, done.

File: pkg/testutils/serverutils/test_server_shim.go (hunk 2 above)
Comment (Nukitt) [reply pkg/testutils/serverutils/test_server_shim.go]: yup done.

**Review by suj-krishnan — APPROVED** [review]
LGTM!

File: pkg/util/tracing/drpcinterceptor/drpc_interceptor.go (hunk 4 above)
Comment (shubhamdhama) [reply pkg/util/tracing/drpcinterceptor/drpc_interceptor.go]: AFAIU, the decision to not create tracing span for `MethodsExcludedFromTracing` from injecting span into gRPC metadata doesn't have anything to do with this PR.

In spite of that, I am not sure if it's a good idea. Folks from SQL/KV may have better idea than I would from the supportability perspective but I think it's a deliberate decision to create the span even if it's excluded. This exclusion is only for inject to the other side. This span tells us the time at which RPC request was initiated from client's point of view and can be useful to track things like retry attempts.

**Review by shubhamdhama — CHANGES_REQUESTED** [review]

File: pkg/util/tracing/drpcinterceptor/drpc_interceptor.go (hunk 4 above)
Comment (Nukitt) [reply pkg/util/tracing/drpcinterceptor/drpc_interceptor.go]: Okay, ever since we added the rpc spans in optional spans for the test, we can actually incorporate this change. done.

**Review by shubhamdhama — APPROVED** [review]
🚀
