### PR TITLE
make sure all nodes survive in acceptance tests

### LINKED ISSUE #1678: acceptance test doesn't register when a node dies
I would've expected the test to fail if one of the nodes dies unexpectedly (such as happens frequently with the Put test). Instead, I'll only find out when that happens a) if Raft progress stops because the majority is gone or b) I check the logs and see that peers are unreachable.
I should add that those node failures are almost always due to panic or OOM.

### PR DESCRIPTION
**Pull request by tbg**
except where restarts are part of the test. This is going to
need to be refined in tests which actually do kill nodes on
purpose, but for now it saves us from individual nodes
dying and us not realizing.

closes #1678

[Review on Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/2833)

### CODE REVIEW

File: acceptance/build_info_test.go [hunk 1]
```diff
@@ -31,6 +31,7 @@ func TestBuildInfo(t *testing.T) {
 	l := localcluster.Create(1, stopper)
 	l.Start()
 	defer l.Stop()
+	defer assertNoEvents(t, l)
```
Comment (bdarnell) [inline acceptance/build_info_test.go]: Can we make this the default so it doesn't have to be copied into every test? If events are rare enough (so we don't overflow the buffer) we could just have `l.Stop` drain the channel  and fail if there are any unexpected events in it.

Comment (tschottdorf) [inline acceptance/build_info_test.go]: some tests actually do restart nodes (I'm assuming some more will soon). Really what we'd need is to process the Events channel inside of the `*Cluster` so that it can link intentional kills/restarts to their emitted events. After that, we should do what you suggest and fail on `Stop()` (which is what I initially wanted).

**Comment by bdarnell** [comment]
The commit message says closes #2833 but I think you mean #1678.

LGTM

**Comment by tschottdorf** [comment]
whoops, thanks. Fixed.

File: acceptance/build_info_test.go (hunk 1 above)
Comment (bdarnell) [inline acceptance/build_info_test.go]: I understand we don't want it every time; I'm just wondering if we could make this the default state which could be disabled from tests that restart nodes, instead of the other way around.

Comment (tschottdorf) [inline acceptance/build_info_test.go]: certainly possible. Actually I'm going to see how much work it is to add the "awareness" in and do the filtering on `Stop()`.

**Comment by petermattis** [comment]
Review status: 0 of 7 files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

<sup>**[acceptance/build_info_test.go, line 34 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/2833#-K0fj5FJ8FN_b_zgvYlt-r1-34)** ([raw file](https://github.com/cockroachdb/cockroach/blob/9c1195b8a7618e98ef56cab561eff7b2dfb2adb1/acceptance/build_info_test.go#L34)):</sup>
Yeah, I think we should check for no events by default. Only `gossip_peering_test.go` is currently checking for tests. Passing some flag to `localcluster.Cluster.Stop()` seems reasonable. 


---

<sup>**[acceptance/localcluster/localcluster.go, line 129 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/2833#-K0fjT5oh8CY18UQRcjb)** ([raw file](https://github.com/cockroachdb/cockroach/blob/9c1195b8a7618e98ef56cab561eff7b2dfb2adb1/acceptance/localcluster/localcluster.go#L129)):</sup>
`gossip_peerings_test.go` is performing this initialization as well. I think you can remove it from there.


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/2833)

**Comment by tschottdorf** [comment]
I've got a new version coming, but am afraid to put my laptop on the paid
Wi-Fi. Will push from NYC.

**Comment by tschottdorf** [comment]
Pushed. Still somewhat preliminary (usability would be best if restarting nodes automatically added expected events, but nodes are accessed directly for that and not through the cluster), but should do the trick for now.

**Comment by tamird** [comment]
LGTM

File: acceptance/gossip_peerings_test.go [hunk 2]
```diff
@@ -148,13 +160,21 @@ func TestGossipRestart(t *testing.T) {
 	checkRangeReplication(t, l, 10*time.Second)
 
 	log.Infof("stopping all nodes")
-	for _, node := range l.Nodes {
+	for i, node := range l.Nodes {
 		node.Stop(5)
+		expEvents = append(expEvents, []localcluster.Event{
+			{NodeIndex: i, Status: "kill"},
```
Comment (tamird) [inline acceptance/gossip_peerings_test.go]: looks like this entry doesn't get in

Comment (tschottdorf) [inline acceptance/gossip_peerings_test.go]: that's awkward. It passes locally, so I can only assume that there's some difference in docker (i'm on the latest brew locally).

File: acceptance/build_info_test.go [hunk 3]
```diff
@@ -30,7 +30,11 @@ import (
 func TestBuildInfo(t *testing.T) {
 	l := localcluster.Create(1, stopper)
 	l.Start()
-	defer l.Stop()
+	defer func() {
+		if err := l.AssertAndStop(nil); err != nil {
```
Comment (petermattis) [inline acceptance/build_info_test.go]: This would be cleaner as `defer l.AssertAndStop(t)`. You could avoiding making `localcluster` depend on `testing` by providing a small interface:

```
type logger interface {
  Fatal(args ...interface{})
}
```

File: acceptance/gossip_peerings_test.go [hunk 4]
```diff
@@ -45,11 +44,6 @@ func checkGossip(t *testing.T, l *localcluster.Cluster, d time.Duration,
 		case <-stopper:
 			t.Fatalf("interrupted")
 			return nil
-		case e := <-l.Events:
-			if log.V(1) {
-				log.Infof("%+v", e)
-			}
-			return fmt.Errorf("event: %+v", e)
```
Comment (petermattis) [inline acceptance/gossip_peerings_test.go]: I'm not sure about these changes to the gossip peerings test. I think if a test is expecting node events like this it should handle them like this instead of trying to fit within the `AssertAndStop` interface.

File: acceptance/gossip_peerings_test.go (hunk 2 above)
Comment (petermattis) [inline acceptance/gossip_peerings_test.go]: I've noticed that event notification has changed across docker releases. I think we need to be careful in not being overly strict in what we expect. The current `AssertAndStop` API might not be appropriate given the constraints we're under.

File: acceptance/gossip_peerings_test.go (hunk 4 above)
Comment (tschottdorf) [inline acceptance/gossip_peerings_test.go]: but all tests should by default make sure that they don't receive unexpected events. The only other alternative is not using `cluster.AssertAndStop(...)` but having a wrapper around `.Stop()` which lives in the acceptance tests. But then it's not obvious that in a test you're supposed to use that wrapper instead of verbatim `Stop()`. That was my motivation for `AssertAndStop`, anyway.

On a more general level, I'm not sure I want tests to even construct the expected events manually. After all, if a test calls `Nodes[3].Restart()` it should be understood that there's a restart event for that node. A logical next step would be adding the expected events to the cluster state and asserting on shutdown, which suggests that `AssertAndStop(...)` is a good middle ground for now.

File: acceptance/build_info_test.go (hunk 3 above)
Comment (bdarnell) [inline acceptance/build_info_test.go]: We have defined this interface in `util.Tester`

File: acceptance/gossip_peerings_test.go (hunk 4 above)
Comment (bdarnell) [inline acceptance/gossip_peerings_test.go]: `AssertAndStop(slice)` is inflexible since it can only do an exact match. I think I'd also prefer having tests that have particular event expectations read from the channel instead of constructing a slice to pass in to `AssertAndStop` (until `Node.Restart` and similar methods can be updated to record the correct expectations for use in `AssertAndStop`)

Comment (tschottdorf) [inline acceptance/gossip_peerings_test.go]: so you would keep AssertAndStop but only use if if nothing is expected, and then have boilerplate in each test that does non-trivial things? In an earlier comment you sounded like you'd rather avoid boilerplate in each test. My feeling is that whatever the interim solution for now is, it's going to be imperfect.

Comment (bdarnell) [inline acceptance/gossip_peerings_test.go]: I would always use AssertAndStop, but for tests that read from the events channel themselves AssertAndStop would trivially pass because the test had already drained the channel.

I want to avoid boilerplate in tests that have the default expectations. Reducing boilerplate in tests that have non-default expectations would be nice too once we have more than one such test, but it's lower priority (and ideally we'd make the default expectations smart enough that custom handling remains rare).

Comment (tschottdorf) [inline acceptance/gossip_peerings_test.go]: yeah, but note that the old version of this test simply throws away the events. It's strictly better now and draining the channel manually and asserting is just rewriting `AssertAndStop`. I'm not convinced this is better at this point, especially that once we actually have more than one or two of these tests it becomes way more valuable to deal with the expected events inside of the local cluster.

Comment (bdarnell) [inline acceptance/gossip_peerings_test.go]: Yeah, I don't feel too strongly about it since it should all be temporary.

Comment (petermattis) [inline acceptance/gossip_peerings_test.go]: I'd like to see the `AssertAndStop` functionality folded into `Stop`. That is, `Stop` always drains the events buffer looking for unexpected events. Tests which manually restart nodes should do the draining and checking themselves. This would be enforced by `Stop` causing the test to fail it the event buffer has not been drained and contains unexpected events.

**Comment by tschottdorf** [comment]
Since nobody was really satisfied with this interim solution, I'm going to go straight for the more well-rounded one in which tests don't have to specify the expected events individually (instead, restarting/stopping/... individual nodes will populate the list of expected events to be checked against on shutdown).

File: acceptance/gossip_peerings_test.go [hunk 5]
```diff
@@ -148,13 +142,13 @@ func TestGossipRestart(t *testing.T) {
 	checkRangeReplication(t, l, 10*time.Second)
 
 	log.Infof("stopping all nodes")
-	for _, node := range l.Nodes {
-		node.Stop(5)
```
Comment (tschottdorf) [inline acceptance/gossip_peerings_test.go]: note the previous bug here.

Comment (tamird) [inline acceptance/gossip_peerings_test.go]: ? the argument is the timeout

File: acceptance/localcluster/localcluster.go [hunk 6]
```diff
@@ -127,6 +130,18 @@ func Create(numNodes int, stopper chan struct{}) *Cluster {
 		client:  newDockerClient(),
 		stopper: stopper,
 		Nodes:   make([]*Container, numNodes),
+		events:  make(chan Event, 1000),
+	}
+}
+
+func (l *Cluster) expectEvent(c *Container, msgs ...string) {
+	for index, ctr := range l.Nodes {
+		if ctr != nil && c.ID != ctr.ID {
```
Comment (tamird) [inline acceptance/localcluster/localcluster.go]: `if c != nil`?

File: acceptance/gossip_peerings_test.go [hunk 7]
```diff
@@ -117,8 +113,6 @@ func TestGossipPeerings(t *testing.T) {
 	checkGossip(t, l, 20*time.Second, hasPeers(len(l.Nodes)))
 
 	// Restart another node.
-	rand.Seed(randutil.NewPseudoSeed())
```
Comment (tamird) [inline acceptance/gossip_peerings_test.go]: why did this move?

Comment (tschottdorf) [inline acceptance/gossip_peerings_test.go]: previous code. Moved back down.

File: acceptance/gossip_peerings_test.go (hunk 5 above)
Comment (tschottdorf) [inline acceptance/gossip_peerings_test.go]: haha. Changed back.

File: acceptance/localcluster/localcluster.go (hunk 6 above)
Comment (tschottdorf) [inline acceptance/localcluster/localcluster.go]: the container calls this itself, so it's never `nil`.

Comment (tamird) [inline acceptance/localcluster/localcluster.go]: okay, but `ctr` is also never nil; that slice is populated with pointers because of ergonomics, nothing else

File: acceptance/localcluster/docker.go [hunk 8]
```diff
@@ -190,32 +194,43 @@ func (c *Container) Start(binds []string, dns, vols *Container) error {
...
-	return c.client.UnpauseContainer(c.ID)
+	return c.cluster.client.UnpauseContainer(c.ID)
 }
 
 // Restart restarts a running container.
 // Container will be killed after 'timeout' seconds if it fails to stop.
 func (c *Container) Restart(timeoutSeconds int) error {
-	if err := c.client.RestartContainer(c.ID, timeoutSeconds); err != nil {
+	var exp []string
+	if err := c.Inspect(); err != nil {
```
Comment (tamird) [inline acceptance/localcluster/docker.go]: how come you had to add this?

File: acceptance/localcluster/docker.go [hunk 9]
```diff
@@ -190,32 +194,43 @@ func (c *Container) Start(binds []string, dns, vols *Container) error {
...
+		return err
+	} else if c.containerInfo.State.Running {
+		exp = append(exp, "die")
```
Comment (tamird) [inline acceptance/localcluster/docker.go]: this is awkward. why not replace this with the simpler `c.cluster.expectEvent(c, "die")`?

File: acceptance/localcluster/localcluster.go [hunk 10]
```diff
@@ -426,8 +441,33 @@ func (l *Cluster) Start() {
...
+// If the drained events (excluding "start" and "create") don't
+// match the events generated by the operations performed on the
+// nodes in the cluster (restart, kill, ...), the passed Tester
+// receives a fatal error.
+func (l *Cluster) AssertAndStop(t util.Tester) {
+	expected := l.expectedEvents
+	defer l.stop()
+	var events []Event
+	for {
+		select {
```
Comment (tamird) [inline acceptance/localcluster/localcluster.go]: nit: why not close the channel and then range over it?

File: acceptance/localcluster/localcluster.go [hunk 11]
```diff
@@ -426,8 +441,33 @@ func (l *Cluster) Start() {
...
+		case e := <-l.events:
+			if e.Status == "die" || e.Status == "restart" {
```
Comment (tamird) [inline acceptance/localcluster/localcluster.go]: this needs a comment explaining why it's ok to discard other events.

File: acceptance/localcluster/localcluster.go [hunk 12]
```diff
@@ -426,8 +441,33 @@ func (l *Cluster) Start() {
 	}
 }
 
+// AssertAndStop drains the Events channel and stops the cluster.
+// If the drained events (excluding "start" and "create") don't
+// match the events generated by the operations performed on the
+// nodes in the cluster (restart, kill, ...), the passed Tester
+// receives a fatal error.
+func (l *Cluster) AssertAndStop(t util.Tester) {
```
Comment (petermattis) [inline acceptance/localcluster/localcluster.go]: I would have just named this `Stop`.

File: acceptance/localcluster/localcluster.go (hunk 11 above)
Comment (tschottdorf) [inline acceptance/localcluster/localcluster.go]: done.

File: acceptance/localcluster/localcluster.go (hunk 12 above)
Comment (tschottdorf) [inline acceptance/localcluster/localcluster.go]: I just factored out `Assert` since it's better to explicitly call it regularly in an acceptance test I'm writing, so I'd like to stick with `AssertAndStop`.

File: acceptance/localcluster/localcluster.go (hunk 10 above)
Comment (tschottdorf) [inline acceptance/localcluster/localcluster.go]: because the channel may be written to. Also (not in this commit yet) we may want to allow for repeated assertions.

File: acceptance/localcluster/docker.go (hunk 9 above)
Comment (tschottdorf) [inline acceptance/localcluster/docker.go]: because the restart below may fail. Not sure if that's worth it, but technically we shouldn't expect events if a container operation fails.

File: acceptance/localcluster/localcluster.go (hunk 6 above)
Comment (tschottdorf) [inline acceptance/localcluster/localcluster.go]: changed as per your suggestion.

File: acceptance/localcluster/docker.go (hunk 8 above)
Comment (tschottdorf) [inline acceptance/localcluster/docker.go]: `Inspect` updates the internal container state, so if the container dies and then "restart" is called, we need a call to `Inspect` inbetween. I think Inspect() should probably just return something and not be cached.

File: acceptance/localcluster/docker.go [hunk 13]
```diff
@@ -131,22 +131,23 @@ func dockerIP() net.IP {
...
-func createContainer(client dockerclient.Client, config dockerclient.ContainerConfig) (*Container, error) {
-	id, err := client.CreateContainer(&config, "")
+func createContainer(l *Cluster, config dockerclient.ContainerConfig) (*Container, error) {
+	id, err := l.client.CreateContainer(&config, "")
 	if err != nil {
 		return nil, err
 	}
 	return &Container{
 		ID:            id,
 		containerInfo: dockerclient.ContainerInfo{Id: id},
```
Comment (tamird) [inline acceptance/localcluster/docker.go]: did you mean to remove `containerInfo` from this struct?

Comment (tschottdorf) [inline acceptance/localcluster/docker.go]: yes. Doing that now.

File: acceptance/localcluster/localcluster.go [hunk 14]
```diff
@@ -421,13 +439,59 @@ func (l *Cluster) Start() {
...
+	for {
+		select {
+		case exp := <-l.expectedEvents:
+			for {
+				select {
+				case act := <-l.events:
+					if act.Status != "die" && act.Status != "restart" {
+						continue
+					}
+					if !reflect.DeepEqual(exp, act) {
```
Comment (tamird) [inline acceptance/localcluster/localcluster.go]: nit: you probably don't need reflect here

**Comment by tamird** [comment]
LGTM. @petermattis should probably have a look.

File: acceptance/localcluster/localcluster.go (hunk 14 above)
Comment (tschottdorf) [inline acceptance/localcluster/localcluster.go]: done.

On Wed, Oct 21, 2015 at 12:51 PM, Tamir Duberstein <notifications@github.com

**Comment by petermattis** [comment]
Review status: 0 of 8 files reviewed at latest revision, 16 unresolved discussions, some commit checks pending.

---

<sup>**[acceptance/localcluster/localcluster.go, line 134 \[r4\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/2833#-K1AKE1pfgT1uXcfJKbA)** ([raw file](https://github.com/cockroachdb/cockroach/blob/6bb7694ae9be7d0f157e7afd19f0c3a296ec4c4a/acceptance/localcluster/localcluster.go#L134)):</sup>
Dangerous for this to be a channel. The test will freeze up on the 1001 expected event.


---

<sup>**[acceptance/localcluster/localcluster.go, line 145 \[r4\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/2833#-K1AKAhD0poICGgNLjMt)** ([raw file](https://github.com/cockroachdb/cockroach/blob/6bb7694ae9be7d0f157e7afd19f0c3a296ec4c4a/acceptance/localcluster/localcluster.go#L145)):</sup>
`break` after this?


---

<sup>**[acceptance/localcluster/localcluster.go, line 370 \[r4\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/2833#-K1AKmJJwCKLGJVGduE4)** ([raw file](https://github.com/cockroachdb/cockroach/blob/6bb7694ae9be7d0f157e7afd19f0c3a296ec4c4a/acceptance/localcluster/localcluster.go#L370)):</sup>
The nil check is no longer necessary.


---

<sup>**[acceptance/localcluster/localcluster.go, line 371 \[r4\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/2833#-K1AKoMx6yoeO_sjJFDH)** ([raw file](https://github.com/cockroachdb/cockroach/blob/6bb7694ae9be7d0f157e7afd19f0c3a296ec4c4a/acceptance/localcluster/localcluster.go#L371)):</sup>
Similar to `expectedEvents`, perhaps this shouldn't be a channel but simply a `[]Event`. Then you never have to worry about the channel filling up.


---

<sup>**[acceptance/localcluster/localcluster.go, line 455 \[r4\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/2833#-K1ALIflR_SucD9j_MvR)** ([raw file](https://github.com/cockroachdb/cockroach/blob/6bb7694ae9be7d0f157e7afd19f0c3a296ec4c4a/acceptance/localcluster/localcluster.go#L455)):</sup>
Is this logic correct? If there are no `expectedEvents` you won't check the `events` channel.


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/2833)

File: acceptance/localcluster/localcluster.go [hunk 15]
```diff
@@ -195,7 +213,7 @@ func (l *Cluster) initCluster() {
 	l.panicOnStop()
 
 	vols := map[string]struct{}{}
-	for i := range l.Nodes {
+	for i := 0; i < cap(l.Nodes); i++ {
```
Comment (bdarnell) [inline acceptance/localcluster/localcluster.go]: Iterating over `cap(l.Nodes)` seems delicate. I'd rather add a `numNodes` to the struct instead of hiding this in `cap(l.Nodes)` and rely on all interactions with this slice to preserve its backing array's capacity.

File: acceptance/localcluster/localcluster.go [hunk 16]
```diff
@@ -349,8 +366,8 @@ func (l *Cluster) processEvent(e dockerclient.EventOrError, monitorStopper chan
 
 	if e.Error != nil {
 		log.Errorf("monitoring error: %s", e.Error)
-		if l.Events != nil {
-			l.Events <- Event{NodeIndex: -1, Status: eventDie}
+		if l.events != nil {
```
Comment (bdarnell) [inline acceptance/localcluster/localcluster.go]: It looks like we can remove the checks for a nil events channel now.

**Comment by bdarnell** [comment]
LGTM, but I agree with Peter that if the test won't be monitoring the events as they happen then it would be better to make it a slice instead of a channel.

**Comment by tschottdorf** [comment]
having slices there means that we require locking on those, and that is prone to deadlocks since the events can happen at any time, when the lock is already held. I specifically switched away from them for that reason.

I wouldn't mind asserting the events as they happen, but that means more changes on how we use the system. Writing another acceptance test at the moment which will be more dynamic, so my interest for now is to wrap up the work and get this in. With the new test I'll likely also make some more adjustments.

File: acceptance/localcluster/localcluster.go (hunk 16 above)
Comment (tschottdorf) [inline acceptance/localcluster/localcluster.go]: done.

**Comment by tschottdorf** [comment]
Review status: 0 of 8 files reviewed at latest revision, 14 unresolved discussions, some commit checks failed.

---

<sup>**[acceptance/localcluster/localcluster.go, line 134 \[r4\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/2833#-K1AKE1pfgT1uXcfJKbA)** ([raw file](https://github.com/cockroachdb/cockroach/blob/6bb7694ae9be7d0f157e7afd19f0c3a296ec4c4a/acceptance/localcluster/localcluster.go#L134)):</sup>
agreed, but let me get to that after this PR.


---

<sup>**[acceptance/localcluster/localcluster.go, line 145 \[r4\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/2833#-K1AKAhD0poICGgNLjMt)** ([raw file](https://github.com/cockroachdb/cockroach/blob/6bb7694ae9be7d0f157e7afd19f0c3a296ec4c4a/acceptance/localcluster/localcluster.go#L145)):</sup>
sure, added.


---

<sup>**[acceptance/localcluster/localcluster.go, line 455 \[r4\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/2833#-K1ALIflR_SucD9j_MvR)** ([raw file](https://github.com/cockroachdb/cockroach/blob/6bb7694ae9be7d0f157e7afd19f0c3a296ec4c4a/acceptance/localcluster/localcluster.go#L455)):</sup>
the catcher at the end was wrong (it needs to read from `events`, not `expectedEvents`). Changed.


---

<sup>**[acceptance/localcluster/localcluster.go, line 216 \[r5\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/2833#-K0fj5FJ8FN_b_zgvYlu-r5-216)** ([raw file](https://github.com/cockroachdb/cockroach/blob/aabcdfb470532475d9f38730415a86e686c32354/acceptance/localcluster/localcluster.go#L216)):</sup>
done.


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/2833)

**Comment by petermattis** [comment]
Asserting events as they happen would be nice. Fine to wait for a future PR. Perhaps just put a comment in the code next to the channels about the danger of the fixed size buffers.


---

Review status: 0 of 8 files reviewed at latest revision, 16 unresolved discussions, some commit checks pending.

---

<sup>**[acceptance/localcluster/localcluster.go, line 474 \[r7\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/2833#-K1AsD-OvcH4pOSjvim8)** ([raw file](https://github.com/cockroachdb/cockroach/blob/f0e585dd3e4fbaca0fce58b7976bde62b4db065a/acceptance/localcluster/localcluster.go#L474)):</sup>
I think you can do `*exp != *act`.


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/2833)

**Comment by petermattis** [comment]
LGTM


---

Review status: 0 of 8 files reviewed at latest revision, 16 unresolved discussions, some commit checks pending.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/2833)
