### PR TITLE
cloud: close Reader before resetting in ResumingReader

### LINKED ISSUE #75143: pkg/cloud: ResumingReader incorrectly forgets to call `.Close()` on its ReadCloser
**Describe the problem**

Since go 1.17.6, it has become critical to call `.Close()` on the Body field of a http Response object, for otherwise we get goroutine leaks.
(see #74657, https://github.com/golang/go/issues/50652 and #75136)

Thanks to #75136, we're now doing a pretty good job of doing so in most cases, except for the following:

- `cloud/httpsink/(*httpStorage).ReadFileAt` calls `openStreamAt` which returns a http.Response
- that Response's Body is then passed as an `io.ReadCloser` to `cloud.NewResumingReader`,
- which, in turns does not call `.Close()` when the Reader is reset in `Read()`, when `RetryOnErrFn` returns true

(NB I've found it hard to read through the implementation of the methods of `cloud.ReadResumer`, it was expecting some kind of disciplined centralization of the invariants on the ReadCloser - maybe there's some improvement to make there)

cc @adityamaru for triage

### PR DESCRIPTION
**Pull request by adityamaru**
This change `Close()`s the Reader before resetting it when we
encounter a resumable error in the ResumingReader. This is particularly
important for the http external storage provide, since forgetting to
call Close() results in goroutine leaks from go1.17.6 onwards.

See: golang/go#50652

Fixes: #75143

Release note: None

### CODE REVIEW

File: pkg/cloud/cloud_io.go [hunk 1]
```diff
@@ -231,6 +231,7 @@ func (r *ResumingReader) Read(p []byte) (int, error) {
 			}
 			log.Errorf(r.Ctx, "Retry IO: error %s", lastErr)
 			lastErr = nil
+			r.Reader.Close()
```
Comment (adityamaru) [inline pkg/cloud/cloud_io.go:234]: hmm actually i think we need a nil check here incase the call to `r.Open()` failed.

**Review by knz — APPROVED** [review]
LGTM modulo the additional fix you've identified already

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/75149#-:-Mtn2BOHD4Hj9_SiBhpO:b-vfpanq)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @adityamaru and @dt)

___
*[pkg/cloud/cloud_io.go, line 234 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/75149#-Mtn-e1uz0N8Rti8-SuU-r1-234:-Mtn2AcG7QzawKbe3jZL:b2nign3) ([raw file](https://github.com/cockroachdb/cockroach/blob/3c4995cb2e97ba0f50d984adacaf72d9782a062f/pkg/cloud/cloud_io.go#L234)):*
<details><summary><i>Previously, adityamaru (Aditya Maru) wrote…</i></summary><blockquote>

hmm actually i think we need a nil check here incase the call to `r.Open()` failed.
</blockquote></details>

yep

**Comment by adityamaru** [comment]
Bazel failure is an unrelated timeout of kvserver package.

bors r=knz
