### PR TITLE
kvserver: narrow down 'finishing a proposal with outstanding reproposal'

### LINKED ISSUE #97102: kvserver: outstanding reproposal at a higher max lease index
**Describe the problem**

Fatal error on `n1` (prob. leaseholder) on this line:
https://github.com/cockroachdb/cockroach/blob/866d58a62d792f963ff963235406b53b4ccf597f/pkg/kv/kvserver/replica_application_state_machine.go#L238

```
F230214 09:41:18.245640 428 kv/kvserver/replica_application_state_machine.go:238 ⋮ [T1,n1,s1,r155/1:‹/Table/106/1/-7{76224…-57960…}›,raft] 13077  finishing proposal with outstanding reproposal at a higher max lease index: ‹Term:9 Index:13210 Type:EntryNormal Data:"\000dX\340\332\006\356\361\3140\007j\nB\000\222\001\005`\212\002h\002r\227\001\n\224\001\000\000\000\000\000\000\000\000\001\000\000\000\001&\001k\022\362\211\200\224\270\274P{\232h\373\210\000\001txn-\236\023\372a\221\014H\210\204}\017h\202*\217\"\000_\022\004\010\000\020\000\030\000 \000(\0002QF\273B\344\003\n>\n\020\236\023\372a\221\014H\210\204}\017h\202*\217\"\032\014\362\211\200\224\270\274P{\232h\373\210*\n\010\375\320\302\316\276\360\351\241\0270\341\300\016J\n\010\375\320\302\316\276\360\351\241\027P\001*\n\010\260\207\324\253\302\360\351\241\027 \277c\212\001\n\010\263\365\340\216\266\360\351\241\027"›

```

Could be related to recent changes, e.g. #94633.

**To Reproduce**

I caught this while running the following on a GCE worker (with master 9c41c487 build):

```
roachprod create -n3 local
roachprod put local ./cockroach
roachprod start --env "COCKROACH_ROCKSDB_CONCURRENCY=5" --env "COCKROACH_LOG_SST_INFO_TICKS_INTERVAL=6" local

workload run kv --init --histograms=perf/stats.json --concurrency=8196 --splits=100 --duration=30m0s --read-percent=0 --min-block-bytes=1024 --max-block-bytes=1024 --tolerate-errors=true 'postgres://root@127.0.0.1:26257?sslmode=disable'
```

Jira issue: CRDB-24511

### LINKED ISSUE #97447: roachtest: replicate/up/1to3 failed
roachtest.replicate/up/1to3 [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/8785686?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/8785686?buildTab=artifacts#/replicate/up/1to3) on master @ [286b3e235171a39b8f9910555affcc7ce310741a](https://github.com/cockroachdb/cockroach/commits/286b3e235171a39b8f9910555affcc7ce310741a):

```
test artifacts and logs in: /artifacts/replicate/up/1to3/run_1
(monitor.go:127).Wait: monitor failure: monitor command failure: unexpected node event: 2: dead (exit status 7)
```
<p>Parameters: <code>ROACHTEST_cloud=gce</code>
, <code>ROACHTEST_cpu=4</code>
, <code>ROACHTEST_encrypted=false</code>
, <code>ROACHTEST_ssd=0</code>
</p>
<details><summary>Help</summary>
<p>

See: [roachtest README](https://github.com/cockroachdb/cockroach/blob/master/pkg/cmd/roachtest/README.md)

See: [How To Investigate \(internal\)](https://cockroachlabs.atlassian.net/l/c/SSSBr8c7)

</p>
</details>
/cc @cockroachdb/kv-triage
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*replicate/up/1to3.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)
</sub>

Jira issue: CRDB-24701

### LINKED ISSUE #97612: roachtest: clearrange/checks=false/rangeTs=false failed
roachtest.clearrange/checks=false/rangeTs=false [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/8820223?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/8820223?buildTab=artifacts#/clearrange/checks=false/rangeTs=false) on master @ [0d3393b0623a5c258b25725f64f3689e2f54667b](https://github.com/cockroachdb/cockroach/commits/0d3393b0623a5c258b25725f64f3689e2f54667b):

```
test artifacts and logs in: /artifacts/clearrange/checks=false/rangeTs=false/run_1
(cluster.go:1956).Run: output in run_105101.069200958_n1-10_cockroach-workload-r: ./cockroach workload run kv --concurrency=32 --duration=1h returned: context canceled
(monitor.go:127).Wait: monitor failure: monitor command failure: unexpected node event: 10: dead (exit status 7)
```
<p>Parameters: <code>ROACHTEST_cloud=gce</code>
, <code>ROACHTEST_cpu=16</code>
, <code>ROACHTEST_encrypted=false</code>
, <code>ROACHTEST_fs=ext4</code>
, <code>ROACHTEST_localSSD=true</code>
, <code>ROACHTEST_ssd=0</code>
</p>
<details><summary>Help</summary>
<p>

See: [roachtest README](https://github.com/cockroachdb/cockroach/blob/master/pkg/cmd/roachtest/README.md)

See: [How To Investigate \(internal\)](https://cockroachlabs.atlassian.net/l/c/SSSBr8c7)

</p>
</details>
/cc @cockroachdb/storage
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*clearrange/checks=false/rangeTs=false.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)
</sub>

Jira issue: CRDB-24786

### PR DESCRIPTION
**Pull request by tbg**
In #94633, I introduced[^1] an assertion that attempted to catch cases
in which we might otherwise accidentally end up applying a proposal
twice.

This assertion had a false positive.

I was able to reproduce the failure within ~minutes via
`./experiment.sh` in #97173 as of 33dcdef.

Better testing of these cases would be desirable. Unfortunately, while
there is an abstraction over command application (`apply.Task`), most
of the logic worth testing lives in `(*replicaAppBatch)` which is
essentially a `*Replica` with more moving parts attached. This does
not lend itself well to unit testing.

I had a run[^2][^3][^4] earlier this year to make log application
standalone, but then didn't have enough time to follow through.
It would be desirable to do so at a later date, perhaps with
the explicit goals of having interactions like the one discussion
in this PR unit become testable.

[^4]: #93309
[^3]: #93266
[^2]: #93239

[^1]: https://github.com/cockroachdb/cockroach/pull/94633/files#diff-50e458584d176deae52b20a7c04461b3e4110795c8c9a307cf7ee6696ba6bc60R238

This assertion was previously trying to assert too much at a distance
and was not only incorrect, but additionally inscrutable.

It was mixing up two assertions, the first one of which is sensible:
If an entry is accepted, it must not be superseded by inflight proposal.
If this were violated, this superseded proposal could also apply,
resulting in a failure of replay protection. This assertion is now
still around as a stand-alone assertion.

The other half of the assertion was more confused: if an entry is
rejected, it was claiming that it couldn't also be superseded. The
thinking was that if a superseding log entry exists, maybe it could
apply, and that would be bad since we just told the waiting client
that their proposal got rejected.

This reasoning is incorrect, as the following example shows. Consider
the following initial situation:

    [lease seq is 1]
    log idx 99:  unrelated cmd at LAI 10000, lease seq = 1
    log idx 100: cmd X at LAI 10000, lease seq = 1

And next:

- a new lease enters the log at idx 101 (lease seq = 2)
- an identical copy of idx 100 enters the log at idx 102
- we apply idx 100, leading to superseding reproposal at idx 103

resulting in the log:

    [lease seq is 1]
    log idx 99: unrelated cmd at LAI 10000, lease seq = 1
    log idx 100: cmd X at LAI 10000, lease seq = 1
    log idx 101: lease seq = 2
    log idx 102: (same as idx 100)
    log idx 103: cmd X at LAI = 20000, lease seq = 1

During application of idx 102, we get a *permanent* rejection and yet
the entry is superseded (by the proposal at idx 103). This would
erroneously trigger the assertion, even though this is a legal sequence
of events with no detrimental outcomes: the superseding proposal will
always have the same lease sequence as its superseded copies, so it
will also fail.

I initially tried only soften the assertion a *little bit*. Observing
that the example above led to a *permanent* rejection, should we only
require that a proposal (which in this assertion is always local) is not
superseded if it got rejected due to its lease index (which implies that
it passed the lease check)? It turns out that this is primarily an
assertion on when superseded proposals are counted as "local" at this
point in the code: if there were multiple copies of this rejected
proposal in the current `appTask` (i.e. the current `CommittedEntries`
slice handed to us for application by raft), then all copies are
initially local; and a copy that successfully spawns a superseding
proposal would be made non-local from that point on. On the face
of it, All other copies in the same `appTask` would now hit the
assertion (erroneously): they are local, they are rejected, so
why don't they enter the branch? The magic ingredient is that
if an entry is superseded when we handle the lease index rejection,
we also unlink the proposal from it. So these never enter this
path since it's not local at this point.

For example, if these are the log entries to apply (all at valid lease
seq):

    log idx 99: unrelated cmd at LAI 10000
    log idx 100: cmd X at LAI 10000
    log idx 101: (identical copy of idx 100)

and idxs 99-101 are applied in one batch, then idx 100 would spawn
a reproposal at a new lease applied index:

    log idx 99: unrelated cmd at LAI 10000
    log idx 100: cmd X at LAI 10000             <- applied
    log idx 101: (identical copy of idx 100)
    log idx 100: cmd X at LAI 20000             <- not in current batch

When we apply 101, we observe an illegal lease index, but the proposal
supersedes the entry, so we mark it as non-local and don't enter the
branch that contains the assertion.

The above reasoning is very difficult to understand, and it happens
too far removed from where the interesting state changes happen.

Also, for testing purposes it is interesting to introduce "errors"
in the lease applied index assignment to artificially exercise these
reproposal mechanisms. In doing so, these assertions can trip because
the lease applied index assigned to a reproposal might accidentally
(or intentionally!) match the existing lease applied index, in which
case copies of the command in the same batch now *don't* consider
themselves superseded.

The value of this testing outweighs the very limited benefit of
this branch of the assertion. An argument could even be made that
this assertion alone as negative benefit due to its complexity.

We are removing it in this commit and will instead work towards
simplifying the mechanisms that played a role in explaining the
asssertion.

Closes https://github.com/cockroachdb/cockroach/issues/97102.
Closes https://github.com/cockroachdb/cockroach/pull/97347.
Closes #97447.
Closes #97612.

No release note because unreleased (except perhaps in an alpha).

Epic: none
Release note: None

### CODE REVIEW

File: pkg/kv/kvserver/replica_application_result.go [hunk 1]
```diff
@@ -211,30 +240,7 @@ func (r *replicaReproposer) newNotLeaseHolderError(msg string) *kvpb.NotLeaseHol
...
-		// Similarly, if the proposal associated with this rejected raft entry is
-		// superseded by a different (larger) MaxLeaseIndex than the one we decoded
-		// from the entry itself, the command must have already passed through
-		// tryReproposeWithNewLeaseIndex previously (this can happen if there are
-		// multiple copies of the command in the logs; see
-		// TestReplicaRefreshMultiple). We must not create multiple copies with
-		// multiple lease indexes, so don't repropose it again. This ensures that at
-		// any time, there is only up to a single lease index that has a chance of
-		// succeeding in the Raft log for a given command.
-		return nil
```
Comment (tbg) [inline pkg/kv/kvserver/replica_application_result.go:235]: This is the `return nil` that would then set the caller's `pErr` to `nil`.

File: pkg/kv/kvserver/replica_application_result.go [hunk 2]
```diff
@@ -104,11 +104,40 @@ func (r *Replica) prepareLocalResult(ctx context.Context, cmd *replicatedCmd) {
...
+			// Similarly, if the proposal associated with this rejected raft entry is
+			// superseded by a different (larger) MaxLeaseIndex than the one we decoded
+			// from the entry itself, the command must have already passed through
+			// tryReproposeWithNewLeaseIndex previously (this can happen if there are
+			// multiple copies of the command in the logs; see
+			// TestReplicaRefreshMultiple). We must not create multiple copies with
+			// multiple lease indexes, so don't repropose it again. This ensures that at
+			// any time, there is only up to a single lease index that has a chance of
+			// succeeding in the Raft log for a given command.
+			if !cmd.proposal.applied && !cmd.proposal.Supersedes(cmd.Cmd.MaxLeaseIndex) {
```
Comment (tbg) [inline pkg/kv/kvserver/replica_application_result.go:165]: This inverts the condition in the (now removed) early return in `tryReproposeWithNewLeaseIndex`.

File: pkg/kv/kvserver/replica_application_state_machine.go [hunk 3]
```diff
@@ -223,30 +244,21 @@ func (sm *replicaStateMachine) ApplySideEffects(
...
+				// to apply it will be rejected by the below raft lease sequence or lease
+				// index check in checkForcedErr.
+				log.Fatalf(ctx, "command already applied: %+v; unexpected successful result", cmd)
+			}
+			if cmd.proposal.Supersedes(cmd.Cmd.MaxLeaseIndex) {
+				// If an entry is superseded but it wasn't rejected, something is wrong.
+				// The superseding reproposal could apply as well, leading to doubly applying
+				// a command.
+				log.Fatalf(ctx, "applying superseded proposal: %s", formatReplicatedCmd(cmd))
+			}
```
Comment (pavelkalinnikov) [inline pkg/kv/kvserver/replica_application_state_machine.go:261]: This block is now equivalent to pre-#94633, right?

File: pkg/kv/kvserver/replica_application_result.go (hunk 1 above)
Comment (pavelkalinnikov) [reply pkg/kv/kvserver/replica_application_result.go:235]: There is another `return nil` below btw. Good that there its meaning is less overloaded now.

File: pkg/kv/kvserver/replica_application_result.go [hunk 4]
```diff
@@ -129,6 +185,26 @@ func (r *Replica) prepareLocalResult(ctx context.Context, cmd *replicatedCmd) {
...
+				// is fine, but it could bump into the closed timestamp, get an error,
+				// enter this branch, and then trip the assertion.
+				// We should be able to avoid pathologies such as this one if in
+				// `retrieveLocalProposals` we attached the proposal (and removed from
+				// the map) to the first copy of the current non-superseded entry. This
+				// avoids situations in which multiple entries deal with the same proposal
+				// within the context of an replicaAppBatch.
+				// It might be even better to remove proposals from the map not at the
+				// beginning of application, but at the end: a proposal would leave the
+				// map only once, never to return again.
```
Comment (pavelkalinnikov) [inline pkg/kv/kvserver/replica_application_result.go:207]: This. I think there should be a source-of-truth map that tracks proposals till the end of their lifetime (i.e. inserted once, deleted once). The complexity of the lifetime should be tracked at the level of one entry in this map, we shouldn't be needing to jump in/out of it and have to derive state based on implicit information like "whether it's in the map" / "in the proposal buffer" (this info can probably be abstracted away).

**Review by pav-kv — APPROVED** [review]
Is this basically a rollback to pre-#94633 state w.r.t. "finishing a proposal with outstanding reproposal" assert? (+refactoring)

File: pkg/kv/kvserver/replica_application_result.go (hunk 4 above)
Comment (tbg) [reply pkg/kv/kvserver/replica_application_result.go:207]: Will link this issue here and instead remove the part that talks about possible solutions, since we can just click the link instead.

File: pkg/kv/kvserver/replica_application_result.go [hunk 5]
```diff
@@ -211,30 +287,7 @@ func (r *replicaReproposer) newNotLeaseHolderError(msg string) *kvpb.NotLeaseHol
 func tryReproposeWithNewLeaseIndex(
```
[the remark this answers is not in the document]
Comment (tbg) [reply pkg/kv/kvserver/replica_application_result.go:287]: Good point, fixed.

**Comment by tbg** [comment]
TFTR!

> Is this basically a rollback

I checked and yes, almost. There is this part that hasn't been brought back: https://github.com/cockroachdb/cockroach/pull/97564#discussion_r1116704958

**Comment by tbg** [comment]
bors r=pavelkalinnikov
