### PR TITLE
sql: formatting of `TableIndexName` can be wrong in certain contexts

### LINKED ISSUE #58496: tree: formatting of `TableIndexName` seems wrong
**Describe the problem**

A table index name with no table specified will end up being formatted like:

`""."".<index name>` when using the `FQName` flag for formatting. That is bogus and doesn't refer to an index. There's also logic for formatting the prefix in this bogus is we have a schema, but it's not clear when that can happen. 

See the below code:
https://github.com/cockroachdb/cockroach/blob/c08088d4cc4556ac82ef29451d53278c12970c5b/pkg/sql/sem/tree/table_name.go#L191-L195. 

**Preferred Solution**

Ideally we'd annotate the `TableIndexName` tree node as at some point during planning we do end up resolving this index to a real table. If we had proper annotations then in the event log context which motivated this issue we'd be able to properly format the name. On the way to that solution, we should stop writing this bogus format which will be interpreted as an object name for an index. 

**Additional context**

This arose in the context of #58472 to fix  #57740.

### PR DESCRIPTION
**Pull request by fqazi**
Fixes: #58496

Previously, the object name information for TableIndexName,
was not populated in multiple contexts leading to incorrect
formatting of index names in event log messages. To address
this, this patch modifies code paths for resolving table
indexes to add this information during the planning phase.

Release note: None

### CODE REVIEW

File: pkg/sql/resolver.go [hunk 1]
```diff
@@ -722,6 +722,17 @@ func (p *planner) getTableAndIndex(
...
+
+	// Resolve the object name for logging if
+	// its missing.
+	if tableWithIndex.Table.ObjectName == "" {
+		tableName, err := p.getQualifiedTableName(ctx, optIdx.tab.desc)
+		if err != nil {
+			return nil, nil, err
+		}
+		tableWithIndex.Table = *tableName
+	}
```
Comment (postamar) [inline pkg/sql/resolver.go:734]: This might do the job, nonetheless there are a few things worth pointing out:
- calling `getQualifiedTableName` comes at a cost; looking up the db and schema descriptors might end up doing so from storage, even if it's unlikely;
- if `ResolveTableIndex` was able to find the index of a table, then it seems to me that it should have been able to  resolve that table in the first place. The reason I suspect this is because in CRDB, indexes are always defined within a table descriptor and can't exist independently. Looking at the signature of `ResolveTableIndex`, I further suspect that it already returns that qualified table name as its second argument.

**Review by fqazi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/61776)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @postamar)

___
*[pkg/sql/resolver.go, line 734 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/61776#-MVRlyNgRQi1nEj5gTUu-r1-734:-MVX-WoyEr8-JBfc9_ky:br4czlk) ([raw file](https://github.com/cockroachdb/cockroach/blob/beed9a4d0d08db249ea2b5602cc003d435c24ad4/pkg/sql/resolver.go#L734)):*
<details><summary><i>Previously, postamar (Marius Posta) wrote…</i></summary><blockquote>

This might do the job, nonetheless there are a few things worth pointing out:
- calling `getQualifiedTableName` comes at a cost; looking up the db and schema descriptors might end up doing so from storage, even if it's unlikely;
- if `ResolveTableIndex` was able to find the index of a table, then it seems to me that it should have been able to  resolve that table in the first place. The reason I suspect this is because in CRDB, indexes are always defined within a table descriptor and can't exist independently. Looking at the signature of `ResolveTableIndex`, I further suspect that it already returns that qualified table name as its second argument.
</blockquote></details>

Good point, yes the second argument is the qualified name. Modified the code to directly us that.

**Review by postamar — APPROVED** [review]

**Comment by fqazi** [comment]
bors r=postamar
