### PR TITLE
ci: autokill roachtest nightlies when failure rate exceeds threshold

### LINKED ISSUE #120160: ci: autokill roachtest nightlies when failure rate exceeds threshold
Nightly roachtests are fairly stable, exhibiting failure rates < 5%, on average. Occasionally, a regression, typically merged the day of the nightly run, or a infrastructure change/transient issue, can result in a cascade of failures. Such is the case demonstrated by a recent example [1], caused by [2], and another infrastructure issue, whose root cause it yet to be determined,

```
output: ERROR: (gcloud.dns.record-sets.list) RESOURCE_EXHAUSTED: Resource has been exhausted (e.g. check quota).: exit status 1
```

Since a high failure rate is likely indicative of an issue which may impact a large subset of the roachtests, the preference is to kill the CI job on the grounds of having reached a point of diminished returns. Furthermore, this reduces additional noise generated by creating multiple instances of test failures, likely caused by the same issue. Thus, the ask is to add a CLI parameter, say `failThreshold` (or `autokillThreshold`), which can be adjusted via TC. The default value can be conservatively placed around ~15%; i.e., if the number of test failures exceeds 15%, then the test runner should bail out with an appropriate exit code.

[1] https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/14291292
[2] https://github.com/cockroachdb/cockroach/issues/120124

Jira issue: CRDB-36512

### PR DESCRIPTION
**Pull request by vidit-bhat**
Nightly roachtests are fairly stable, exhibiting failure rates < 5%, on average. Occasionally, a regression, typically merged the day of the nightly run, or a infrastructure change/transient issue, can result in a cascade of failures. Since a high failure rate is likely indicative of an issue which may impact a large subset of the roachtests, the preference is to kill the CI job on the grounds of having reached a point of diminished returns.

This PR introduces a roachtest CLI argument, `auto-kill-threshold`, which when exceeded would auto-kill the nightlies.

Epic: none
Fixes: #120160 
Release note: None

### CODE REVIEW

File: pkg/cmd/roachtest/roachtestflags/flags.go [hunk 1]
```diff
@@ -357,6 +357,12 @@ var (
 		Usage: `Use SpotVM to run tests, If the provider does not support spotVM, it will be ignored`,
 	})
 
+	AutokillThreshold float64 = 1.0
+	_                         = registerRunFlag(&AutokillThreshold, FlagInfo{
+		Name:  "autokillThreshold",
+		Usage: `The threshold of a failed tests after which the nightlies will be auto-killed.`,
```
Comment (DarrylWong) [inline pkg/cmd/roachtest/roachtestflags/flags.go:363]: nit: the intention is to use this for nightlies but this should be generic enough to work for any roachtest run

File: pkg/cmd/roachtest/test_runner.go [hunk 2]
```diff
@@ -580,6 +580,10 @@ func (r *testRunner) runWorker(
 		}
 	}()
 
+	work.mu.Lock()
+	totalTestCount := work.count * len(work.mu.tests)
```
Comment (DarrylWong) [inline pkg/cmd/roachtest/test_runner.go:584]: This seems like it's only counting the number of tests given to a single worker, but we want to do this over the entire nightly run. 

https://github.com/cockroachdb/cockroach/blob/244b1a1b60c399b035377644cf09a0df53d2e066/pkg/cmd/roachtest/run.go#L114-L119

We already figure out the number of tests here, so i don't think we need to do anything special, just use that.

File: pkg/cmd/roachtest/test_runner.go [hunk 3]
```diff
@@ -892,6 +897,11 @@ func (r *testRunner) runWorker(
 				c = nil
 			}
 		}
+
+		failureRate := float64(failedTestCount) / float64(totalTestCount)
+		if failureRate > roachtestflags.AutokillThreshold {
+			return errors.Errorf("failure rate %.2f exceeds limit %.2f", failureRate, roachtestflags.AutokillThreshold)
```
Comment (DarrylWong) [inline pkg/cmd/roachtest/test_runner.go:903]: Same as above, this seems like we are failing workers, but we want to fail the entire run.

File: pkg/cmd/roachtest/roachtestflags/flags.go (hunk 1 above)
Comment (DarrylWong) [reply pkg/cmd/roachtest/roachtestflags/flags.go:363]: also, can we use `auto-kill-threshold` to keep the naming consistent?

**Review by DarrylWong — COMMENTED** [review]
I think you will also have to add some logic into `roachtest_nightly_impl.sh` to

1. Pass in the `autokillThreshold` flag to the invoke script w/ 0.15 
2. Read in a `AUTO_KILL_THRESHOLD` env variable to let you override it

**Comment by DarrylWong** [comment]
Oh, and as for how to test this, you can do a similar approach to the VM Host error, where you intentionally fail tests. Running the entire suite and making 15% of tests fail would be expensive and time consuming though. If you run just two tests, and the first one fails, we should expect the roachtest runner to cancel the second one.

You might also want to do a low probability (SELECT_PROBABILITY = 0.1) run of the suite at the end to make sure nothing broke, depending on how complex the change is.

File: pkg/cmd/roachtest/roachtestflags/flags.go (hunk 1 above)
Comment (vidit-bhat) [reply pkg/cmd/roachtest/roachtestflags/flags.go]: Updated

**Comment by vidit-bhat** [comment]
> I think you will also have to add some logic into `roachtest_nightly_impl.sh` to
> 
> 1. Pass in the `autokillThreshold` flag to the invoke script w/ 0.15
> 2. Read in a `AUTO_KILL_THRESHOLD` env variable to let you override it

Done

File: pkg/cmd/roachtest/test_runner.go (hunk 3 above)
Comment (vidit-bhat) [reply pkg/cmd/roachtest/test_runner.go]: Added a `testCount` in the `testRunner` struct which keeps track of the total number of tests in the entire run and used that to calculate the `failureRate`

File: pkg/cmd/roachtest/test_runner.go [hunk 4]
```diff
@@ -892,6 +897,12 @@ func (r *testRunner) runWorker(
 				c = nil
 			}
 		}
+
+		// stop the tests if the failure rate has been exceeded
+		failureRate := float64(len(r.status.fail)) / float64(r.testCount)
```
Comment (DarrylWong) [inline pkg/cmd/roachtest/test_runner.go:902]: Grab the lock before reading `r.status.fail`?

Comment (vidit-bhat) [reply pkg/cmd/roachtest/test_runner.go:903]: Yeah realised after pushing. Done.

File: build/teamcity/cockroach/nightlies/roachtest_nightly_impl.sh [hunk 5]
```diff
@@ -62,6 +62,7 @@ build/teamcity-roachtest-invoke.sh \
   --select-probability="${select_probability}" \
   --cloud="${CLOUD}" \
   --count="${COUNT-1}" \
+  --auto-kill-threshold="${AUTO_KILL_THRESHOLD:-0.15}" \
```
Comment (renatolabs) [inline build/teamcity/cockroach/nightlies/roachtest_nightly_impl.sh:65]: I know the issue linked to this PR does mention 15%, but I wanted to discuss this again with everyone: do we think this is a good default?

Looking at the latest nightly on GCE, I see we have 514 tests in a run so, if we use the 15% value, it would take _77_ failures before the run is aborted.

In comparison, the "bad" nightly run that motivated this issue (that was canceled manually), had _36_ test failures. It seems to me that we should be canceling builds a little more proactively.

File: pkg/cmd/roachtest/test_runner.go [hunk 6]
```diff
@@ -137,6 +137,9 @@ type testRunner struct {
 		skip    map[*testImpl]struct{}
 	}
 
+	// testCount is the total number of tests registered multiplied by the total number of times each test has to run.
+	testCount int
```
Comment (renatolabs) [inline pkg/cmd/roachtest/test_runner.go:141]: Nit: I don't think we need a new struct field for this? Maybe `runWorker` could take a `maxTotalFailures` parameter, since the value is only used in that context.

Also, `testCount` is also deceptively similar sounding to our `roachtest --count` parameter, which is different (albeit related) number.

File: pkg/cmd/roachtest/test_runner.go [hunk 7]
```diff
@@ -643,6 +648,14 @@ func (r *testRunner) runWorker(
...
 				qp.Release(alloc)
 				alloc = nil
+
+				// stop the tests if the failure rate has been exceeded
+				r.status.Lock()
+				failureRate := float64(len(r.status.fail)) / float64(r.testCount)
+				r.status.Unlock()
+				if failureRate > roachtestflags.AutoKillThreshold {
+					return errors.Errorf("failure rate %.2f exceeds limit %.2f", failureRate, roachtestflags.AutoKillThreshold)
+				}
```
Comment (renatolabs) [inline pkg/cmd/roachtest/test_runner.go:658]: I'm confused -- why do we have this logic here? It is guarded by this predicate:

```go
// We could not find a test that can reuse the cluster. Destroy the cluster
// and search for a new test.
if testToRun.noWork {
```

Shouldn't we be aborting runs regardless of cluster reuse?

File: pkg/cmd/roachtest/test_runner.go [hunk 8]
```diff
@@ -643,6 +648,14 @@ func (r *testRunner) runWorker(
 				}
 				qp.Release(alloc)
 				alloc = nil
+
+				// stop the tests if the failure rate has been exceeded
+				r.status.Lock()
+				failureRate := float64(len(r.status.fail)) / float64(r.testCount)
```
Comment (renatolabs) [inline pkg/cmd/roachtest/test_runner.go:654]: I don't have a strong opinion on this yet, so I'm curious about what others think: should all errors be the same when it comes to this (i.e., test failures and infra flakes), or should we not be counting infra flakes (would we want to abort runs if we have extra preemptions on some night for some reason, for example?)

File: build/teamcity/cockroach/nightlies/roachtest_nightly_impl.sh (hunk 5 above)
Comment (vidit-bhat) [reply build/teamcity/cockroach/nightlies/roachtest_nightly_impl.sh:65]: So something around 7% as the threshold?

File: pkg/cmd/roachtest/test_runner.go (hunk 8 above)
Comment (DarrylWong) [reply pkg/cmd/roachtest/test_runner.go:654]: I think that's reasonable to not count infra flakes. If the intention of this flag is to prevent excessive triaging and closing of issues, then it makes sense to not count infra flakes that are already rerouted to us and mostly ignored.

File: pkg/cmd/roachtest/test_runner.go (hunk 6 above)
Comment (vidit-bhat) [reply pkg/cmd/roachtest/test_runner.go:141]: Hmm, makes sense. Will update.

File: build/teamcity/cockroach/nightlies/roachtest_nightly_impl.sh (hunk 5 above)
Comment (srosenberg) [reply build/teamcity/cockroach/nightlies/roachtest_nightly_impl.sh:65]: I'd go even lower to 5%, which should still be rather conservative. The mean is somewhere below 3% and std. deviation isn't that high either.

File: pkg/cmd/roachtest/roachtestflags/flags.go [hunk 9]
```diff
@@ -357,6 +357,12 @@ var (
 		Usage: `Use SpotVM to run tests, If the provider does not support spotVM, it will be ignored`,
 	})
 
+	AutoKillThreshold float64 = 1.0
+	_                         = registerRunFlag(&AutoKillThreshold, FlagInfo{
+		Name:  "auto-kill-threshold",
+		Usage: `The failure rate threshold at which all remaining tests will be automatically terminated.`,
```
Comment (srosenberg) [inline pkg/cmd/roachtest/roachtestflags/flags.go:363]: Nit: `Percentage of failed tests before all remaining tests are automatically terminated.`

File: pkg/cmd/roachtest/test_runner.go (hunk 8 above)
Comment (srosenberg) [reply pkg/cmd/roachtest/test_runner.go:654]: Agreed. Let's exclude all _known_ infra failures since those are already handled in a specific way to prevent noise.

File: pkg/cmd/roachtest/test_runner.go (hunk 7 above)
Comment (srosenberg) [reply pkg/cmd/roachtest/test_runner.go:658]: I think it should suffice to check the threshold immediately after a test candidate was selected and before it's executed: https://github.com/cockroachdb/cockroach/blob/6210c2cd725ecb3875cad722020ea7c1d9042cec/pkg/cmd/roachtest/test_runner.go#L658-L661

File: pkg/cmd/roachtest/roachtestflags/flags.go (hunk 9 above)
Comment (vidit-bhat) [reply pkg/cmd/roachtest/roachtestflags/flags.go]: Done

File: build/teamcity/cockroach/nightlies/roachtest_nightly_impl.sh (hunk 5 above)
Comment (vidit-bhat) [reply build/teamcity/cockroach/nightlies/roachtest_nightly_impl.sh]: Set to 5%

File: pkg/cmd/roachtest/test_runner.go (hunk 6 above)
Comment (vidit-bhat) [reply pkg/cmd/roachtest/test_runner.go]: Done

File: pkg/cmd/roachtest/test_runner.go (hunk 7 above)
Comment (vidit-bhat) [reply pkg/cmd/roachtest/test_runner.go]: From my discussion with Renato I think moving it [right after the](https://github.com/cockroachdb/cockroach/blob/6210c2cd725ecb3875cad722020ea7c1d9042cec/pkg/cmd/roachtest/test_runner.go#L598) `select` block should also be fine

File: pkg/cmd/roachtest/test_runner.go (hunk 8 above)
Comment (vidit-bhat) [reply pkg/cmd/roachtest/test_runner.go]: Updated

File: pkg/cmd/roachtest/test_runner.go (hunk 7 above)
Comment (srosenberg) [reply pkg/cmd/roachtest/test_runner.go]: Yep, that should work too since _all_ clusters are destroyed (`r.cr.destroyAllClusters(ctx, l)`) upon an exceptional termination of a worker.

**Review by srosenberg — APPROVED** [review]
For smoke testing, you could trigger a manual run, e.g.,

```
roachtest run --artifacts ~/go/src/github.com/cockroachdb/cockroach/artifacts/aws --cloud aws --cpu-quota 1024 --suite nightly "." > roachtest_nightly_aws.out 2>&1
```

after randomly injecting failures via `preAllocateClusterFn` (emulating infra. flakes) and `runTest` (emulating test failure).

File: pkg/cmd/roachtest/test_runner.go [hunk 10]
```diff
@@ -1140,7 +1150,10 @@ func (r *testRunner) runTest(
 		// Only include tests with a Run function in the summary output.
 		if s.Run != nil {
 			if t.Failed() {
-				r.status.fail[t] = struct{}{}
+				errWithOwner := failuresAsErrorWithOwnership(t.failures())
+				if errWithOwner != nil && !errWithOwner.InfraFlake {
```
Comment (renatolabs) [inline pkg/cmd/roachtest/test_runner.go:1154]: I don't think this is quite right. Whether a test failure is an infra flake can be determined by the predicate `errWithOwner != nil && errWithOwner.InfraFlake`.

In this case, we want to add to the `fail` set when `not infra-flake`. So what we want is (applying De Morgan's law): `errWithOwner == nil || !errWithOwner.InfraFlake`.

**Comment by renatolabs** [comment]
Couple of git related comments:

1. Your first / main commit here still has the git message template we use:

```
<what was there before: Previously, ...>
<why it needed to change: This was inadequate because ...>
<what you did about it: To address this, this patch ...>
```

This is supposed to be a template to guide the git commit message. If the commit requires no message, the template above should be deleted (although in this case a long message would be nice). See this (internal) [document](https://cockroachlabs.atlassian.net/wiki/spaces/CRDB/pages/73072807/Git+Commit+Messages) on how we write git commit messages.

2. We generally _rebase_ feature branches against master, instead of merging master onto this branch. This avoids having a merge commit in this feature branch as it currently does. Please rebase the branch against master to make sure only the relevant commit ends up in this PR.

**Comment by vidit-bhat** [comment]
> Couple of git related comments:
> 
> 1. Your first / main commit here still has the git message template we use:
> 
> ```
> <what was there before: Previously, ...>
> <why it needed to change: This was inadequate because ...>
> <what you did about it: To address this, this patch ...>
> ```
> 
> This is supposed to be a template to guide the git commit message. If the commit requires no message, the template above should be deleted (although in this case a long message would be nice). See this (internal) [document](https://cockroachlabs.atlassian.net/wiki/spaces/CRDB/pages/73072807/Git+Commit+Messages) on how we write git commit messages.
> 
> 2. We generally _rebase_ feature branches against master, instead of merging master onto this branch. This avoids having a merge commit in this feature branch as it currently does. Please rebase the branch against master to make sure only the relevant commit ends up in this PR.

Thanks for the catch! Have updated the message and removed the merge commit.

File: pkg/cmd/roachtest/test_runner.go (hunk 10 above)
Comment (vidit-bhat) [reply pkg/cmd/roachtest/test_runner.go]: Fixed

**Review by renatolabs — APPROVED** [review]
LGTM!

Were you able to simulate the autokill functionality locally, as Stan suggested above?

**Review by DarrylWong — APPROVED** [review]
LGTM as well!
