### PR TITLE
Bug fixes for time series queries

### LINKED ISSUE #4987: ui: Stats don't display in the first ten minutes of an hour when querying specific sources
Due to a bug in the ts query system, stats will not display within the first ten minutes of an hour if specific sources are being queried.  This happens because of the following loop declaration in `ts/query.go`:

```go
for currentTimestamp := startNanos; currentTimestamp <= endNanos; currentTimestamp += r.KeyDuration() {
```

The issue occurs when `startNanos` falls in a different time slot than `endNanos`, but `startNanos + r.KeyDuration()` is greater than `endNanos`.

### LINKED ISSUE #5003: ui: chart data not showing up
Derivative isn't being passed back with the query results which means the results aren't getting matched back up with the correct queries and the charts are blank.

I think it's missing from here:
https://github.com/cockroachdb/cockroach/blob/master/ts/server.go#L95

### PR DESCRIPTION
**Pull request by mrtracy**
Fix two bugs in time series query:
- Due to an oversight while generating keys, it was possible for a query to miss
  some data. This occurred when the `start` timestamp and the `end` timestamp of the
  query were in different storage keys, and `start + KeyDuration() > end`.
- Fixed bug where the derivative function specified in a query was not reflected
  back in the response.

Fixes #4987
Fixes #5003

---

This change is [Review on Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/5014)

### CODE REVIEW

**Comment by petermattis** [comment]
LGTM

**Comment by tschottdorf** [comment]
:lgtm:

---

Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/5014#-:-KCQeYtt6OLZHKSMlNJG:1417088721)*

File: ts/query_test.go [hunk 1]
```diff
@@ -510,5 +510,12 @@ func TestQuery(t *testing.T) {
 
 	tm.assertKeyCount(31)
 	tm.assertModelCorrect()
+
+	// Assert querying data from subset of sources. Includes source with no
+	// data.
 	tm.assertQuery("test.specificmetric", []string{"source2", "source4", "source6"}, nil, nil, nil, resolution1ns, 0, 90, 7, 2)
+
+	// Assert querying data over limited range for single source. Regression for
```
Comment (tamird) [inline ts/query_test.go]: s/regression/regression test/

File: ts/query.go [hunk 2]
```diff
@@ -440,7 +440,9 @@ func (db *DB) Query(query TimeSeriesQueryRequest_Query, r Resolution,
 		b := db.db.NewBatch()
 		// Iterate over all key timestamps which may contain data for the given
 		// sources, based on the given start/end time and the resolution.
-		for currentTimestamp := startNanos; currentTimestamp <= endNanos; currentTimestamp += r.KeyDuration() {
+		startKeyNanos := startNanos - (startNanos % r.KeyDuration())
```
Comment (tamird) [inline ts/query.go]: Extract local?

File: ts/server.go [hunk 3]
```diff
@@ -89,8 +89,9 @@ func (s *Server) handleQuery(w http.ResponseWriter, r *http.Request, _ httproute
 		response.Results = append(response.Results, &TimeSeriesQueryResponse_Result{
 			Name:             q.Name,
 			Sources:          sources,
-			SourceAggregator: q.SourceAggregator,
-			Downsampler:      q.Downsampler,
+			SourceAggregator: q.GetSourceAggregator().Enum(),
```
Comment (tamird) [inline ts/server.go]: What's the difference between these styles?

Comment (mrtracy) [inline ts/server.go]: If the response had sent "nil" for any for these, the response would also contain nil. This style reflects back what the server used, even if the server used a default.

File: ts/query.go (hunk 2 above)
Comment (mrtracy) [inline ts/query.go]: What is there even to extract?  This seems fine on a single line.

File: ts/query_test.go (hunk 1 above)
Comment (mrtracy) [inline ts/query_test.go]: Done.

File: ts/query.go (hunk 2 above)
Comment (tamird) [inline ts/query.go]: nothing to do with line length. you're calling `KeyDuration` 3 times.

File: ts/server.go (hunk 3 above)
Comment (tamird) [inline ts/server.go]: Seems like we want these enums to be non-nullable. This is odd, I thought we had disabled generating these getters...

Comment (tamird) [inline ts/server.go]: Ah, they're special cased in timeseries.proto. Feel free to leave it as-is, I'll fix it in a follow-up change.

Comment (tamird) [inline ts/server.go]: Ah, I'm wrong - there are getters here because of defaults. Disregard this thread!

File: ts/query.go (hunk 2 above)
Comment (mrtracy) [inline ts/query.go]: Fair, done.
