### PR TITLE
distsql: handle implicit key cols in lookup joins

### LINKED ISSUE #31777: opt: 2 lookup columns specified, expecting at most 1
Running the hibernate test org.hibernate.test.legacy.FooBarTest.testCollectionsInSelect results in an error: `2 lookup columns specified, expecting at most 1` while executing:

```
SELECT
  foo3_.string_ AS col_0_0_
FROM
  foos AS bar0_
  INNER JOIN jointable AS bar0_1_ ON bar0_.foo_idcolumnname123 = bar0_1_.fooid
  INNER JOIN foo_dep_table AS bar0_2_
  ON bar0_.foo_idcolumnname123 = bar0_2_.fooid
  INNER JOIN bar_join_table AS bar0_3_
  ON bar0_.foo_idcolumnname123 = bar0_3_.bar_id
  LEFT JOIN baz AS baz1_ ON bar0_.baz = baz1_.baz_id_column_
  LEFT JOIN foo_array AS fooarray2_
  ON baz1_.baz_id_column_ = fooarray2_.id_ AND fooarray2_.i < 8
  LEFT JOIN foos AS foo3_ ON fooarray2_.foo = foo3_.foo_idcolumnname123
  LEFT JOIN jointable AS foo3_1_ ON foo3_.foo_idcolumnname123 = foo3_1_.fooid
  LEFT JOIN foo_dep_table AS foo3_2_
  ON foo3_.foo_idcolumnname123 = foo3_2_.fooid
WHERE
  bar0_.foo_subclass_1234 = 'B' AND bar0_.string_ = foo3_.string_;
```

[`explain (distsql)` output](https://cockroachdb.github.io/distsqlplan/decode.html#eJyc1UFvmzAUwPH7PoX1Lr08aRhIQixNsia1E1VFpoydNlQRcCu2FCPbSM2qfPfJsGnJFnuFI4Y__B6lzgu0shZZ-SQ0sC9AoUDolKyE1lLZpfGCtH4GFiA0bdcbu1wgVFIJYC9gGrMXwCAvd3uxFWUt1NsAEGphymY_3LZTzVOpDvxBSg0IN83eCMUIj8g7cvX-ijH2Kd-m2QdA2PSGEU6RR8jpGnlMoTgiyN78ebI25aMARo_4et2tbNpfOHoZ9002rbEzAMKdlN_7jtglIlsLOqWFgy5GvnDawpm20Pni7mvR3U_1IV86idFMYnSZuCvVvfXMMSJfOZnxTGZ8zswPnWDk7vomJ5vP-fWW3G7SDPCE_-OSOfaZkSdO9mImezGNbT-MUqnycAmfWHxGOA3I1z4IoookjLE0y_8zFPI1chogp-5_vuXM-Zbn8z3stFFN_fx7a_hnhmhQvNqLnNoLAqd7NdO9mvZ38W8m4dSBqH0NsXOoZOZQyfSPzb8LnQwWObXrKdqt0J1stTiTuu4cHAsEUT-K8ZdLy15V4qOS1fCY8XAzdMNCLbQZz9LxIG3HUxZ4GlNvHPrj0BtH_jjyxrE_jr3xwh8vvPHSHy-98cofr7xx4o8Tb7z-Ky6Ob34GAAD__10p2FU=)

[sql dump](https://github.com/cockroachdb/cockroach/files/2508962/dump.txt)

### PR DESCRIPTION
**Pull request by solongordon**
Non-unique indexes implicitly include all primary key columns in their
keys. The optimizer takes advantage of this when planning lookup joins,
but joinreader was not aware of this and only considered explicit key
columns, which caused an error upon execution ("2 lookup columns
specified, expecting at most 1"). I added joinreader logic to handle
this case.

Fixes #31777 

Release note (bug fix): Fixed a mismatch between lookup join planning
and execution, which could cause queries to fail with the error, "X
lookup columns specified, expecting at most Y."

### CODE REVIEW

**Comment by solongordon** [comment]
Still needs logic tests but the implementation is there. @RaduBerinde would you mind taking a quick look?

**Comment by RaduBerinde** [comment]
Looks good to me. The logic matches the one used by the optimizer to determine key columns.

**Comment by solongordon** [comment]
Great. Tests are there now, and I made the same fix to the local execution path to appease tests. PTAL.

**Review by RaduBerinde — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/31792)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/logictest/testdata/logic_test/lookup_join, line 416 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/31792#-LPbKvKWAaHYP39h73jN:-LPbKvKWAaHYP39h73jO:b9bzynq) ([raw file](https://github.com/cockroachdb/cockroach/blob/7756d4e106d930d075925a09fe535e6e4670a73e/pkg/sql/logictest/testdata/logic_test/lookup_join#L416)):*
> ```
> 
> statement ok
> INSERT INTO t VALUES (1, 2, 3)
> ```

This kind of test is very weak, we could be generating empty spans and it would work.. I'd add a few rows and use a separate table for the other side so that not all rows have a match.
___
*[pkg/sql/opt/exec/execbuilder/testdata/lookup_join, line 423 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/31792#-LPbKmR61IFvBiniC8o-:-LPbKmR61IFvBiniC8o0:bga5rg0) ([raw file](https://github.com/cockroachdb/cockroach/blob/7756d4e106d930d075925a09fe535e6e4670a73e/pkg/sql/opt/exec/execbuilder/testdata/lookup_join#L423)):*
> ```
> 
> statement ok
> INSERT INTO t VALUES (1, 2, 3)
> ```

no need for INSERTs in this file

**Review by solongordon — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/31792)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/logictest/testdata/logic_test/lookup_join, line 416 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/31792#-LPbKvKWAaHYP39h73jN:-LPbSUWG-Gg-COJcqHWI:b-dfn5i9) ([raw file](https://github.com/cockroachdb/cockroach/blob/7756d4e106d930d075925a09fe535e6e4670a73e/pkg/sql/logictest/testdata/logic_test/lookup_join#L416)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

This kind of test is very weak, we could be generating empty spans and it would work.. I'd add a few rows and use a separate table for the other side so that not all rows have a match.
</blockquote></details>

Fair point, done.

**Review by RaduBerinde — APPROVED** [review]
:lgtm:

The release note should be a "bug fix" and mention that it fixes the "x lookup columns specified, expecting at most y" error saw with some joins.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/31792#-:-LPbTNSl6xxEcIbaai4j:b-bi834v)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/sql/logictest/testdata/logic_test/lookup_join, line 416 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/31792#-LPbKvKWAaHYP39h73jN:-LPbSwdX8TnbOPMJeiO4:bsqczg8) ([raw file](https://github.com/cockroachdb/cockroach/blob/7756d4e106d930d075925a09fe535e6e4670a73e/pkg/sql/logictest/testdata/logic_test/lookup_join#L416)):*
<details><summary><i>Previously, solongordon (Solon) wrote…</i></summary><blockquote>

Fair point, done.
</blockquote></details>

[nit] could you use the same query in the execbuilder test? just to make sure the plan is what we expect.
___
*[pkg/sql/logictest/testdata/logic_test/lookup_join, line 413 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/31792#-LPbTCQGCyv2WT7uVukP:-LPbTCQGCyv2WT7uVukQ:b-cwyktu) ([raw file](https://github.com/cockroachdb/cockroach/blob/50264f6ae0ef95ee72bc78b719897b8be77e4f7f/pkg/sql/logictest/testdata/logic_test/lookup_join#L413)):*
> ```
> # https://github.com/cockroachdb/cockroach/issues/31777
> statement ok
> CREATE TABLE t (a INT PRIMARY KEY, b INT, c INT, INDEX b (b))
> ```

[nit] this index is not needed

**Review by jordanlewis — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/31792)* status: :shipit: complete! 1 of 0 LGTMs obtained

___
*[pkg/sql/logictest/testdata/logic_test/lookup_join, line 416 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/31792#-LPbKvKWAaHYP39h73jN:-LPbT2ljE_3onnh30sfX:bmirj4r) ([raw file](https://github.com/cockroachdb/cockroach/blob/7756d4e106d930d075925a09fe535e6e4670a73e/pkg/sql/logictest/testdata/logic_test/lookup_join#L416)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

[nit] could you use the same query in the execbuilder test? just to make sure the plan is what we expect.
</blockquote></details>

I'd like to see a couple of trickier tests as well. The MakeFullKey method you used isn't currently well tested, as it doesn't live in the wild (only used in zzjoin for now). Cases that come to mind:

1. multi-col primary keys where none are included in the index
2. multi-col primary keys where some are already included in the index, maybe in a non-default order - have some of the "extra" cols live in the prefix, middle, or suffix of the primary key columns.

I guess just those ideas, then.

**Review by jordanlewis — COMMENTED** [review]
Actual code :lgtm: though

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/31792#-:-LPbTw4z6MKRizQHTN37:b-4yl23b)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale)

**Review by solongordon — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/31792)* status: :shipit: complete! 2 of 0 LGTMs obtained

___
*[pkg/sql/logictest/testdata/logic_test/lookup_join, line 416 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/31792#-LPbKvKWAaHYP39h73jN:-LPbUbsj3EBW-OA3NO02:bwc0idz) ([raw file](https://github.com/cockroachdb/cockroach/blob/7756d4e106d930d075925a09fe535e6e4670a73e/pkg/sql/logictest/testdata/logic_test/lookup_join#L416)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

I'd like to see a couple of trickier tests as well. The MakeFullKey method you used isn't currently well tested, as it doesn't live in the wild (only used in zzjoin for now). Cases that come to mind:

1. multi-col primary keys where none are included in the index
2. multi-col primary keys where some are already included in the index, maybe in a non-default order - have some of the "extra" cols live in the prefix, middle, or suffix of the primary key columns.

I guess just those ideas, then.
</blockquote></details>

Yes sounds good. I'll also get some descending indexes into the mix.

**Review by solongordon — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/31792)* status: :shipit: complete! 2 of 0 LGTMs obtained

___
*[pkg/sql/logictest/testdata/logic_test/lookup_join, line 416 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/31792#-LPbKvKWAaHYP39h73jN:-LPbdWYS8SPOpNKFLX81:beft5ex) ([raw file](https://github.com/cockroachdb/cockroach/blob/7756d4e106d930d075925a09fe535e6e4670a73e/pkg/sql/logictest/testdata/logic_test/lookup_join#L416)):*
<details><summary><i>Previously, solongordon (Solon) wrote…</i></summary><blockquote>

Yes sounds good. I'll also get some descending indexes into the mix.
</blockquote></details>

Thanks for pointing out that MakeFullKey isn't used in the wild. There is definitely a bug with descending indexes. Will fix.

**Review by solongordon — COMMENTED** [review]
On closer inspection, the `MakeFullKeyFromEncDatums` function was buggy in multiple ways. I rewrote most of it.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/31792#-:-LPbnQEc6SDWL4QSEBuU:bluw6db)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale)

File: pkg/sql/sqlbase/index_encoding.go [hunk 1]
```diff
@@ -270,26 +271,17 @@ func MakeFullKeyFromEncDatums(
...
+	implicitTypes := make([]ColumnType, len(implicitValues))
+	columnTypes := tableDesc.ColumnTypes()
+	for i := range implicitValues {
+		colID := index.ExtraColumnIDs[i]
+		colIdx := colIdxMap[colID]
+		implicitTypes[i] = columnTypes[colIdx]
 	}
+
+	// Implicit key columns are all sorted ascending (the zero value).
+	implicitDirs := make([]IndexDescriptor_Direction, len(implicitValues))
```
Comment (jordanlewis) [inline pkg/sql/sqlbase/index_encoding.go]: Ditto for this - an extra allocation per lookup. A couple of other similar methods accept `nil` for their `directions` field for this same reason (presumably). I'd recommend making that change to `appendEncDatumsToKey` to avoid having to specify this slice.

File: pkg/sql/sqlbase/index_encoding.go [hunk 2]
```diff
@@ -270,26 +271,17 @@ func MakeFullKeyFromEncDatums(
...
-		}
-	}
-	implicitDirs := make([]IndexDescriptor_Direction, len(primaryImplicitIdxs))
-	for i, idx := range primaryImplicitIdxs {
-		implicitDirs[i] = primaryIndex.ColumnDirections[idx]
-	}
-	implicitTypes := make([]ColumnType, len(extraColumns))
-	for i, id := range extraColumns {
-		implicitTypes[i] = tableDesc.ColumnTypes()[id]
+	implicitTypes := make([]ColumnType, len(implicitValues))
```
Comment (jordanlewis) [inline pkg/sql/sqlbase/index_encoding.go]: This seems like something we should be passing in as an argument, rather than reconstructing every time. It's static for the whole lifetime on the lookup join, isn't it? The lookup join should have this slice created at plan time and pass it in to the key creation function, rather than having to do this allocation every time.

**Review by jordanlewis — COMMENTED** [review]
Glad to see that get rewritten, seems a lot simpler now. The tests look good.

**Review by solongordon — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/31792)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale)

___
*[pkg/sql/sqlbase/index_encoding.go, line 274 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/31792#-LPbnBugU4shBckqKCXP-r3-274:-LPbrhVI1gCjpH16tau-:bddo6p) ([raw file](https://github.com/cockroachdb/cockroach/blob/75dc942355d53514d10b1ae421757e87f95b68f6/pkg/sql/sqlbase/index_encoding.go#L274)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

This seems like something we should be passing in as an argument, rather than reconstructing every time. It's static for the whole lifetime on the lookup join, isn't it? The lookup join should have this slice created at plan time and pass it in to the key creation function, rather than having to do this allocation every time.
</blockquote></details>

Yeah, now that you mention this I question whether the `MakeFullKey...` function should even exist. I suspect `MakeKeyFromEncDatums` is sufficient and doesn't have this issue. I'll see if I can make that work.

**Comment by solongordon** [comment]
OK, farewell `MakeFullKeyFromEncDatums`.

File: pkg/sql/sqlbase/index_encoding.go [hunk 3]
```diff
@@ -164,6 +162,11 @@ func MakeKeyFromEncDatums(
 	alloc *DatumAlloc,
 ) (roachpb.Key, error) {
 	dirs := index.ColumnDirections
+	if !index.Unique {
+		// Extra columns are all ascending (the zero value).
+		extraDirs := make([]IndexDescriptor_Direction, len(index.ExtraColumnIDs))
+		dirs = append(dirs, extraDirs...)
```
Comment (jordanlewis) [inline pkg/sql/sqlbase/index_encoding.go]: I'm sorry to keep harping on the allocations, but I really do think this is a big deal - an allocation per key build is not something we want to have to do. You should pass in the directions in the arguments. Or introduce a variant that grabs it from the index descriptor and passes it on if you don't want to change the callers.

Comment (solongordon) [reply pkg/sql/sqlbase/index_encoding.go]: No need to apologize, not sure how I convinced myself this was OK. I converted it to an argument and did some rejiggering in related code to be able to pass it in easily.

**Review by jordanlewis — APPROVED** [review]
LGTM mod comment improvements we discussed if you feel like it.

**Comment by jordanlewis** [comment]
(does look like some tests need updating too)
