### PR TITLE
pkg/sql: move range unsplit logic to table gc jobs

### LINKED ISSUE #67673: sql: DROP TABLE unsplits ranges sequentially in transaction.
**Describe the problem**

We've observed a customer's cluster to be misbehaving because of this.

**To Reproduce**

Run a cluster with large latencies between nodes so that unsplitting a range is slow, and drop a table with a lot of ranges. A large table fresh from a restore should do the trick. The corresponding long-running transaction will hold locks on `system.descriptor` and `system.jobs` making them effectively unreadable for other transactions for a long period of time.

**Expected behavior**
This unsplitting could just as well be (1) parallelized, and (2) run asynchronously in a job or even a GC job.

**Additional data / screenshots**
See https://github.com/cockroachlabs/support/issues/1061 for details on the customer incident.

**Environment:**
Observed in 20.2 but this affects all versions.

### PR DESCRIPTION
**Pull request by chengxiong-ruan**
Fixes #67673
Before this fix, we unsplit ranges before a DROP TABLE
or TRUNCATE TABLE is commited. This problematic when
the table is huge and has many manually split ranges
since unsplitting a large number of ranges sequentially
is slow and transaction would hang. This fix moves the
logic to gc to do the unsplitting async.

Release not: None

### CODE REVIEW

**Comment by chengxiong-ruan** [comment]
___
*[pkg/sql/logictest/testdata/logic_test/crdb_internal, line 622 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/72908#-Monk1xL8ZhqLdfIdWPf:-Monk1xL8ZhqLdfIdWPg:b-8hpc2g) ([raw file](https://github.com/cockroachdb/cockroach/blob/5efe6ce5b189631a5d44ba77de64cf063f835b4b/pkg/sql/logictest/testdata/logic_test/crdb_internal#L622)):*
> ```
> TRUNCATE TABLE foo
> 
> # Ensure splits are not unsplit right away with the transaction.
> ```

Now that we don't unsplit until gc job runs, these ranges sticks...

**Comment by chengxiong-ruan** [comment]
___
*[pkg/bench/rttanalysis/testdata/benchmark_expectations, line 34 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/72908#-MooFZc525fqabzeKghP:-MooFZc525fqabzeKghQ:b-cjtz46) ([raw file](https://github.com/cockroachdb/cockroach/blob/1985fdc685ab06534908d2a0d9705cb9c77c68ef/pkg/bench/rttanalysis/testdata/benchmark_expectations#L34)):*
> ```
> 20,CreateRole/create_role_with_3_options
> 18,CreateRole/create_role_with_no_options
> 19,DropDatabase/drop_database_0_tables
> ```

roundtrip decreased as expected

**Comment by chengxiong-ruan** [comment]
*[a discussion](https://reviewable.io/reviews/cockroachdb/cockroach/72908#-MooVfrM6Ft3A68qZMLj:-MooVfrM6Ft3A68qZMLk:bda4unk) (no related file):*
hmm.. looks like `gcTables` is not the right place to move the logic to because `truncate` won't implicitly trigger the table gc work. I misread the code a bit >_>. 
We don't always want to unsplit for indexes gc, this could be the case for truncate table, but not for drop indexes/columns. Now need to figure out a way how to pass along the signal when do we want to unsplit.

---

**Comment by ajwerner** [comment]
Here's what I'd suggest:

1) unsplit in the job eagerly before the point where we wait for GC
2) add a job progress field that we can mark after we've finished unsplitting so we don't redo the work every time


Also, you're going to need to version gate the movement of this logic into the GC job. You can't just delete it outright. The reason is that new code might run the statement but then old code might run the job. Instead of deleting the logic as it exists now, put it behind an if check on whether the version is active and add a new version in `cockroach_versions.go`. Also add a TODO to delete the code in 22.2.

File: pkg/sql/logictest/testdata/logic_test/crdb_internal [hunk 1]
```diff
@@ -619,14 +619,19 @@ start_pretty   end_pretty
 statement ok
 TRUNCATE TABLE foo
 
-# Ensure that there are no longer any splits left over on the original indexes.
-# TRUNCATE will have created equivalent splits points on the new indexes, so
-# this test just checks that there are no more on the old indexes.
+# Ensure splits are not unsplit right away with the transaction.
+# Instead, they are now unsplit in schema change gc jobs
```
Comment (postamar) [inline pkg/sql/logictest/testdata/logic_test/crdb_internal:623]: There are several job types, one of which is `GC` and another of which is `SCHEMA CHANGE GC`. Are you sure your unsplitting logic runs in the latter and not in the former? This isn't a rethorical question btw.

File: pkg/sql/tests/data.go [hunk 2]
```diff
@@ -32,6 +32,20 @@ func CheckKeyCount(t *testing.T, kvDB *kv.DB, span roachpb.Span, numKeys int) {
...
+	if kvs, err := kvDB.Scan(context.TODO(), key, endKey, 0); err == nil && len(kvs) > 0 {
+		return kvs[len(kvs)/2].Key
+	} else if err != nil {
+		t.Fatal(err)
+	} else if len(kvs) == 0 {
+		t.Fatal("expected at least one key value pairs, but got zero")
+	}
+
+	return nil
+}
```
Comment (postamar) [inline pkg/sql/tests/data.go:47]: I'm not sure this belongs here, this function doesn't deal with SQL concepts. Probably best to move it next to your test.

File: pkg/sql/drop_test.go [hunk 3]
```diff
@@ -916,6 +916,133 @@ CREATE TABLE t.kv (k CHAR PRIMARY KEY, v CHAR);
...
+
+	const numRows = 2*row.TableTruncateChunkSize + 1
+	const numKeys = 3 * numRows
+
+	tableName := "test1"
+	if err := tests.CreateKVTable(sqlDB, tableName, numRows); err != nil {
+		t.Fatal(err)
+	}
+
+	var tableDesc = catalogkv.TestingGetTableDescriptor(kvDB, keys.SystemSQLCodec, "t", tableName)
```
Comment (postamar) [inline pkg/sql/drop_test.go:942]: nit: style: use `tableDesc := catalogkv...` instead.

File: pkg/sql/drop_test.go [hunk 4]
```diff
@@ -916,6 +916,133 @@ CREATE TABLE t.kv (k CHAR PRIMARY KEY, v CHAR);
...
+
+	nameKey := catalogkeys.MakePublicObjectNameKey(keys.SystemSQLCodec, keys.MinNonPredefinedUserDescID, tableName)
+	gr, err := kvDB.Get(ctx, nameKey)
+	if err != nil {
+		t.Fatal(err)
+	}
+	if !gr.Exists() {
+		t.Fatalf("Name entry %q does not exist", nameKey)
+	}
```
Comment (postamar) [inline pkg/sql/drop_test.go:951]: What purpose does this serve? I'm referring to everything around `nameKey`.

File: pkg/sql/drop_test.go [hunk 5]
```diff
@@ -916,6 +916,133 @@ CREATE TABLE t.kv (k CHAR PRIMARY KEY, v CHAR);
...
+			if err := r.ValueProto(&desc); err != nil {
+				t.Fatal(err)
+			}
+			hasManuallySplitRange = hasManuallySplitRange || !desc.GetStickyBit().IsEmpty()
+		}
+		require.Equal(t, hasManuallySplitRange, hasManualSplitRange)
+	}
+
+	// assert that all ranges are not manually split
+	checkManuallySplitRange(false)
```
Comment (postamar) [inline pkg/sql/drop_test.go:980]: nit: style: when passing `nil` or boolean literals, we like to follow them with a `/* */` comment with the argument name. So, here, `checkManuallySplitRange(false /* hasManualSplitRange */)`.

It sounds like a dumb rule, or at least I thought it was dumb because the IDE tells me the same thing, but I've since found it useful when reviewing.

In this case you're probably better off redefining this function as a predicate and doing `require.True` or `require.False` assertions on the return value.

File: pkg/sql/drop_test.go [hunk 6]
```diff
@@ -916,6 +916,133 @@ CREATE TABLE t.kv (k CHAR PRIMARY KEY, v CHAR);
...
+	// Disable strict GC TTL enforcement because we're going to shove a zero-value
+	// TTL into the system with AddImmediateGCZoneConfig.
+	defer sqltestutils.DisableGCTTLStrictEnforcement(t, sqlDB)()
+
+	const numRows = 2*row.TableTruncateChunkSize + 1
+	const numKeys = 3 * numRows
+
+	tableName := "test1"
+	if err := tests.CreateKVTable(sqlDB, tableName, numRows); err != nil {
+		t.Fatal(err)
```
Comment (postamar) [inline pkg/sql/drop_test.go:939]: This test will be much easier to read if you replace all these `if err := ...; err != nil { t.Fatal(err) }` blocks with `require.NoError(t, ...)`.

File: pkg/sql/drop_test.go [hunk 7]
```diff
@@ -916,6 +916,133 @@ CREATE TABLE t.kv (k CHAR PRIMARY KEY, v CHAR);
...
+	ctx := context.Background()
+
+	// Disable strict GC TTL enforcement because we're going to shove a zero-value
+	// TTL into the system with AddImmediateGCZoneConfig.
+	defer sqltestutils.DisableGCTTLStrictEnforcement(t, sqlDB)()
+
+	const numRows = 2*row.TableTruncateChunkSize + 1
+	const numKeys = 3 * numRows
+
+	tableName := "test1"
```
Comment (postamar) [inline pkg/sql/drop_test.go:937]: nit: `const tableName = "test1"`

File: pkg/sql/drop_test.go [hunk 8]
```diff
@@ -916,6 +916,133 @@ CREATE TABLE t.kv (k CHAR PRIMARY KEY, v CHAR);
...
+	}
+	if err := kvDB.AdminSplit(ctx, splitKey, hlc.MaxTimestamp); err != nil {
+		t.Fatal(err)
+	}
+
+	if _, err := sqlDB.Exec(fmt.Sprintf(`DROP TABLE t.%s`, tableName)); err != nil {
+		t.Fatal(err)
+	}
+
+	// Data hasn't been GC-ed.
```
Comment (postamar) [inline pkg/sql/drop_test.go:1005]: It's worth mentioning in this comment that the reason it hasn't been GC-ed is that the GC TTL is still set to its original high value (I think the default is 25h).

File: pkg/sql/drop_test.go [hunk 9]
```diff
@@ -916,6 +916,133 @@ CREATE TABLE t.kv (k CHAR PRIMARY KEY, v CHAR);
...
+	}
+	tableSpan = tableDesc.TableSpan(keys.SystemSQLCodec)
+	tests.CheckKeyCount(t, kvDB, tableSpan, numKeys)
+
+	// The closure pushes a zone config reducing the TTL to 0 for descriptor i.
+	pushZoneCfg := func() {
+		if _, err := sqltestutils.AddImmediateGCZoneConfig(sqlDB, tableDesc.GetID()); err != nil {
+			t.Fatal(err)
+		}
+	}
```
Comment (postamar) [inline pkg/sql/drop_test.go:1017]: Why do you need a closure to do this?

**Review by postamar — COMMENTED** [review]
I was looking at this PR at the same time as Andrew posted his comments. I agree with him that you need to version-gate this change. We need to accommodate mixed version clusters.

Practically speaking, here, bad things can happen in a cluster running a mixture of 21.2 and 22.1 nodes:
1. The execution of the `DROP TABLE` statement could be handled by a 22.1 node. It doesn't unsplit, because the binary was built with your changes. It creates a GC job, expecting that it will do the unsplitting instead.
2. Jobs end up getting executed by any random node in the cluster. This GC job could be run by a 21.2 node. This binary was built before your changes and the GC job doesn't do any unsplitting. Uh oh.  

Mixed-version clusters are an essential feature and they're also the source of a fair many bugs. It's easy to forget about the mixed-version configuration, yet instead it should be at the forefront of our minds whenever we're working on anything distributed.

**Comment by postamar** [comment]
Also: good work! 👍

**Comment by chengxiong-ruan** [comment]
Thanks for the suggestions and explaining the potential pitfalls here. Will reversion the pr :)

**Comment by chengxiong-ruan** [comment]
s/reversion/revision >_>

**Review by chengxiong-ruan — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/72908)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @chengxiong-ruan, and @postamar)

___
*[pkg/sql/drop_test.go, line 939 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/72908#-MonDjoO2bdPfANmo5YD-r3-939:-Mp766H27gZVEHpU6j8O:bmfxgaw) ([raw file](https://github.com/cockroachdb/cockroach/blob/1985fdc685ab06534908d2a0d9705cb9c77c68ef/pkg/sql/drop_test.go#L939)):*
<details><summary><i>Previously, postamar (Marius Posta) wrote…</i></summary><blockquote>

This test will be much easier to read if you replace all these `if err := ...; err != nil { t.Fatal(err) }` blocks with `require.NoError(t, ...)`.
</blockquote></details>

Done :)
___
*[pkg/sql/drop_test.go, line 951 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/72908#-MonDjoO2bdPfANmo5YD-r3-951:-Mp76DIn4m3ncPW8C3iz:b-9l03bs) ([raw file](https://github.com/cockroachdb/cockroach/blob/1985fdc685ab06534908d2a0d9705cb9c77c68ef/pkg/sql/drop_test.go#L951)):*
<details><summary><i>Previously, postamar (Marius Posta) wrote…</i></summary><blockquote>

What purpose does this serve? I'm referring to everything around `nameKey`.
</blockquote></details>

it was to verify the table key exists... but I realized this is not necessary for this test..
___
*[pkg/sql/drop_test.go, line 980 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/72908#-MonDjoO2bdPfANmo5YD-r3-980:-Mp76NEq83Xyb3dTL2HZ:bba1zyy) ([raw file](https://github.com/cockroachdb/cockroach/blob/1985fdc685ab06534908d2a0d9705cb9c77c68ef/pkg/sql/drop_test.go#L980)):*
<details><summary><i>Previously, postamar (Marius Posta) wrote…</i></summary><blockquote>

nit: style: when passing `nil` or boolean literals, we like to follow them with a `/* */` comment with the argument name. So, here, `checkManuallySplitRange(false /* hasManualSplitRange */)`.

It sounds like a dumb rule, or at least I thought it was dumb because the IDE tells me the same thing, but I've since found it useful when reviewing.

In this case you're probably better off redefining this function as a predicate and doing `require.True` or `require.False` assertions on the return value.
</blockquote></details>

Good call, fixed~
___
*[pkg/sql/drop_test.go, line 1005 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/72908#-MonDjoO2bdPfANmo5YD-r3-1005:-Mp76_PFEA6bOY0OX32L:b6i7gv4) ([raw file](https://github.com/cockroachdb/cockroach/blob/1985fdc685ab06534908d2a0d9705cb9c77c68ef/pkg/sql/drop_test.go#L1005)):*
<details><summary><i>Previously, postamar (Marius Posta) wrote…</i></summary><blockquote>

It's worth mentioning in this comment that the reason it hasn't been GC-ed is that the GC TTL is still set to its original high value (I think the default is 25h).
</blockquote></details>

I actually remove this assert, just want to make this test focus on ranges unsplitting
___
*[pkg/sql/drop_test.go, line 1017 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/72908#-MonDjoO2bdPfANmo5YD-r3-1017:-Mp76lX895pa-piaFTEF:brwtrgs) ([raw file](https://github.com/cockroachdb/cockroach/blob/1985fdc685ab06534908d2a0d9705cb9c77c68ef/pkg/sql/drop_test.go#L1017)):*
<details><summary><i>Previously, postamar (Marius Posta) wrote…</i></summary><blockquote>

Why do you need a closure to do this?
</blockquote></details>

no need indeed! removed
___
*[pkg/sql/tests/data.go, line 47 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/72908#-MonDjoO2bdPfANmo5YF-r3-47:-Mp76uOq0fAm8lBppX2T:b-uw8313) ([raw file](https://github.com/cockroachdb/cockroach/blob/1985fdc685ab06534908d2a0d9705cb9c77c68ef/pkg/sql/tests/data.go#L47)):*
<details><summary><i>Previously, postamar (Marius Posta) wrote…</i></summary><blockquote>

I'm not sure this belongs here, this function doesn't deal with SQL concepts. Probably best to move it next to your test.
</blockquote></details>

good point, moved this to the test file.

**Review by chengxiong-ruan — COMMENTED** [review]
@ajwerner @postamar I moved the call to `unsplitRangesForTable` to `schemaChangeGCResumer.Resume` after the TTL expired, I didn't put it before the resumer jumping into the job waiting loop because I couldn't find a way to simulate the async behavior in test. Would appreciate if anyone could suggest a way for that!

`SchemaChangeGCDetails` and `SchemaChangeGCProgress` are utilized to track the range unsplitting. Table IDs to unsplit are added through `planner.truncateTable` method (for truncate table), `schemaChangeResumer.Resume` method (for drop database/schema) and `SchemaChanger.exec` method (for drop table).

I added the version gate. But realized that it's possible that we queue a job when the whole cluster is not 22.1 yet, note that we unsplit ranges already. Then the cluster is promoted to 22.1 before the schema changer kick off the gc job, then gc job would try to unsplit ranges again. I think this is fine.. because the second unsplit would be just a noop and the opportunity of it is transient. Let me know if that make sense to you.

Thank you

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/72908#-:-Mp77BIwCJ5FRlmcD3Yr:bthmwml)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner and @postamar)

___
*[pkg/sql/logictest/testdata/logic_test/crdb_internal, line 623 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/72908#-Monjq0WIdDxvvWw3G7M-r3-623:-Mp7734S0epg1BXCRVMo:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/1985fdc685ab06534908d2a0d9705cb9c77c68ef/pkg/sql/logictest/testdata/logic_test/crdb_internal#L623)):*
<details><summary><i>Previously, postamar (Marius Posta) wrote…</i></summary><blockquote>

~There are several job types, one of which is `GC` and another of which is `SCHEMA CHANGE GC`. Are you sure your unsplitting logic runs in the latter and not in the former? This isn't a rethorical question btw.~

edit: nvm I had a brain fart.
</blockquote></details>

Done.

**Review by ajwerner — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/72908)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @chengxiong-ruan, and @postamar)

___
*[pkg/jobs/jobspb/jobs.proto, line 617 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/72908#-Mp8Av81-yztxH4t1nbq:-Mp8Av81-yztxH4t1nbr:bu8x1j4) ([raw file](https://github.com/cockroachdb/cockroach/blob/a62bbd07aaa186243374ee13f0b498128e3e9b1a/pkg/jobs/jobspb/jobs.proto#L617)):*
> ```
>   // UnsplitTables are the tables we want to unsplit their manually split ranges
>   repeated TableUnsplitRangesProgress unsplit_tables = 4 [(gogoproto.nullable) = false];
> ```
this feels really heavy to me. Do we really need to track a separate set of descriptors with a separate set of statuses? Could a single boolean suffice? 
___
*[pkg/sql/drop_test.go, line 986 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/72908#-Mp8B8pfD3DMNw_Ls5TY:-Mp8B8pfD3DMNw_Ls5TZ:bzan2l5) ([raw file](https://github.com/cockroachdb/cockroach/blob/a62bbd07aaa186243374ee13f0b498128e3e9b1a/pkg/sql/drop_test.go#L986)):*
> ```
> // TODO(Chengxiong): remove this test in 22.2
> func TestDropTableUnsplitRanges(t *testing.T) {
> ```
Consider refactoring all of these tests into a single test with subtests. You can share a setup helper. 

As a separate nit, please write out commentary sketching the test so that it's easy to read and comprehend. 
___
*[pkg/sql/truncate.go, line 232 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/72908#-Mp8ByalCIfaujcQdYrN:-Mp8ByalCIfaujcQdYrO:b50tv0q) ([raw file](https://github.com/cockroachdb/cockroach/blob/459aff5a609634b15be8fb2cdfbc8119ff8d45b8/pkg/sql/truncate.go#L232)):*
<details><summary><i alt="summary">Quoted 4 lines of code…</i></summary>

> ```
> 	// TODO(Chengxiong): remove this if/else block and only keeps logic in if
> 	// branch in 22.2
> 	st := p.EvalContext().Settings
> 	if st.Version.IsActive(ctx, clusterversion.UnsplitRangesInAsyncGCJobs) {
> ```
</details>

I don't really understand this different state in the job details. It's especially alarming that you've only get the table ID here. We go out of our way below to copy some of the splits from the old indexes into the new indexes. It'd be bad to unsplit those immediately. 
___
*[pkg/sql/gcjob/gc_job.go, line 214 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/72908#-Mp8CKc-9HJksOAtjXTD:-Mp8CKc-9HJksOAtjXTE:b1x0aov) ([raw file](https://github.com/cockroachdb/cockroach/blob/a62bbd07aaa186243374ee13f0b498128e3e9b1a/pkg/sql/gcjob/gc_job.go#L214)):*
> ```
> 		if expired {
> 			// TODO(Chengxiong): remove "if check" in 22.2
> 			st := p.ExecCfg().Settings
> ```
Why are we doing this here? I think I'd prefer if we just did it once, unconditionally, at the top before waiting for expiration. Given we were doing it during statement execution before, it's not going to be extra latency.
___
*[pkg/sql/gcjob/gc_job.go, line 216 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/72908#-Mp8Ac271LvE1WywmhJA:-Mp8Ac271LvE1WywmhJB:b5uswlu) ([raw file](https://github.com/cockroachdb/cockroach/blob/a62bbd07aaa186243374ee13f0b498128e3e9b1a/pkg/sql/gcjob/gc_job.go#L216)):*
<details><summary><i alt="summary">Quoted 4 lines of code…</i></summary>

> ```
> 			// TODO(Chengxiong): remove "if check" in 22.2
> 			st := p.ExecCfg().Settings
> 			if st.Version.IsActive(ctx, clusterversion.UnsplitRangesInAsyncGCJobs) {
> 				if len(progress.UnsplitTables) > 0 {
> ```
</details>


I'll be honest, I don't really care about the gc job doing extra work in the mixed version state. This check is fine, but I don't think it's necessary
___
*[pkg/sql/logictest/testdata/logic_test/crdb_internal, line 665 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/72908#-Mp8C_O04_YX6jnqc0KL:-Mp8C_O04_YX6jnqc0KM:b2de2zp) ([raw file](https://github.com/cockroachdb/cockroach/blob/a62bbd07aaa186243374ee13f0b498128e3e9b1a/pkg/sql/logictest/testdata/logic_test/crdb_internal#L665)):*
> ```
> 
> SELECT start_pretty, end_pretty FROM crdb_internal.ranges WHERE split_enforced_until IS NOT NULL
> ```
if you follow my suggestion to do it at the beginning of the gcjob, we can have this retry and retain the existing output. See the `retry` directive on `query`.

**Review by chengxiong-ruan — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/72908)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner and @postamar)

___
*[pkg/jobs/jobspb/jobs.proto, line 617 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/72908#-Mp8Av81-yztxH4t1nbq:-Mp8J6mY21v1Vnpm9rxd:bdjyzdm) ([raw file](https://github.com/cockroachdb/cockroach/blob/a62bbd07aaa186243374ee13f0b498128e3e9b1a/pkg/jobs/jobspb/jobs.proto#L617)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

> ```
>   // UnsplitTables are the tables we want to unsplit their manually split ranges
>   repeated TableUnsplitRangesProgress unsplit_tables = 4 [(gogoproto.nullable) = false];
> ```
this feels really heavy to me. Do we really need to track a separate set of descriptors with a separate set of statuses? Could a single boolean suffice? 
</blockquote></details>

@ajwerner I thought about this as well. For dropping a table/database/schema, it's sufficient to have just a boolean and assume we only unsplit the tables being dropped. However, for truncating a table that's not the case, you have track the table ID. Or maybe I misunderstood that you actually meant have a mapping  from table id to a boolean flag?
___
*[pkg/sql/drop_test.go, line 986 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/72908#-Mp8B8pfD3DMNw_Ls5TY:-Mp8KTKE1cLgCzzoePX9:b-qsnr46) ([raw file](https://github.com/cockroachdb/cockroach/blob/a62bbd07aaa186243374ee13f0b498128e3e9b1a/pkg/sql/drop_test.go#L986)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

> ```
> // TODO(Chengxiong): remove this test in 22.2
> func TestDropTableUnsplitRanges(t *testing.T) {
> ```
Consider refactoring all of these tests into a single test with subtests. You can share a setup helper. 

As a separate nit, please write out commentary sketching the test so that it's easy to read and comprehend. 
</blockquote></details>

good suggestions, will do.
___
*[pkg/sql/truncate.go, line 232 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/72908#-Mp8ByalCIfaujcQdYrN:-Mp8LZhQDR9CIdjtoCU_:b-wuijb1) ([raw file](https://github.com/cockroachdb/cockroach/blob/459aff5a609634b15be8fb2cdfbc8119ff8d45b8/pkg/sql/truncate.go#L232)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

> ```
> 	// TODO(Chengxiong): remove this if/else block and only keeps logic in if
> 	// branch in 22.2
> 	st := p.EvalContext().Settings
> 	if st.Version.IsActive(ctx, clusterversion.UnsplitRangesInAsyncGCJobs) {
> ```
I don't really understand this different state in the job details. It's especially alarming that you've only get the table ID here. We go out of our way below to copy some of the splits from the old indexes into the new indexes. It'd be bad to unsplit those immediately. 
</blockquote></details>

Ah, good call! Are you ok with scheduling a second gc job after the indexes are copied? we would still just need a table ID in the detail.
___
*[pkg/sql/gcjob/gc_job.go, line 214 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/72908#-Mp8CKc-9HJksOAtjXTD:-Mp8KYj_9ANVHhySTNPO:buod2i5) ([raw file](https://github.com/cockroachdb/cockroach/blob/a62bbd07aaa186243374ee13f0b498128e3e9b1a/pkg/sql/gcjob/gc_job.go#L214)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

> ```
> 		if expired {
> 			// TODO(Chengxiong): remove "if check" in 22.2
> 			st := p.ExecCfg().Settings
> ```
Why are we doing this here? I think I'd prefer if we just did it once, unconditionally, at the top before waiting for expiration. Given we were doing it during statement execution before, it's not going to be extra latency.
</blockquote></details>

I actually prefer doing it at the top the job as well. putting here just to make it easy to simulate the async behavior in tests. But I was definitely wrong to prioritize test over actual function code.
___
*[pkg/sql/gcjob/gc_job.go, line 216 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/72908#-Mp8Ac271LvE1WywmhJA:-Mp8KzKaB2gnJvev29pp:b-knhv8j) ([raw file](https://github.com/cockroachdb/cockroach/blob/a62bbd07aaa186243374ee13f0b498128e3e9b1a/pkg/sql/gcjob/gc_job.go#L216)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

> ```
> 			// TODO(Chengxiong): remove "if check" in 22.2
> 			st := p.ExecCfg().Settings
> 			if st.Version.IsActive(ctx, clusterversion.UnsplitRangesInAsyncGCJobs) {
> 				if len(progress.UnsplitTables) > 0 {
> ```

I'll be honest, I don't really care about the gc job doing extra work in the mixed version state. This check is fine, but I don't think it's necessary
</blockquote></details>

Feeling the same, It was just my instinct that code reviewers prefer avoiding extra workload lol.. will remove to make a cleaner here. 
___
*[pkg/sql/logictest/testdata/logic_test/crdb_internal, line 665 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/72908#-Mp8C_O04_YX6jnqc0KL:-Mp8LMovAeYKOYg4IK8S:b-7oeijk) ([raw file](https://github.com/cockroachdb/cockroach/blob/a62bbd07aaa186243374ee13f0b498128e3e9b1a/pkg/sql/logictest/testdata/logic_test/crdb_internal#L665)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

> ```
> 
> SELECT start_pretty, end_pretty FROM crdb_internal.ranges WHERE split_enforced_until IS NOT NULL
> ```
if you follow my suggestion to do it at the beginning of the gcjob, we can have this retry and retain the existing output. See the `retry` directive on `query`.
</blockquote></details>

Yeah. Will do what you suggested. thanks for pointing it out here.

**Review by ajwerner — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/72908)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @chengxiong-ruan, and @postamar)

___
*[pkg/jobs/jobspb/jobs.proto, line 617 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/72908#-Mp8Av81-yztxH4t1nbq:-Mp8cA9RAG2fWK8Jd1Io:b-wgpzkz) ([raw file](https://github.com/cockroachdb/cockroach/blob/a62bbd07aaa186243374ee13f0b498128e3e9b1a/pkg/jobs/jobspb/jobs.proto#L617)):*
<details><summary><i>Previously, chengxiong-ruan (Chengxiong Ruan) wrote…</i></summary><blockquote>

@ajwerner I thought about this as well. For dropping a table/database/schema, it's sufficient to have just a boolean and assume we only unsplit the tables being dropped. However, for truncating a table that's not the case, you have track the table ID. Or maybe I misunderstood that you actually meant have a mapping  from table id to a boolean flag?
</blockquote></details>

I was thinking like one single boolean total that corresponds to whether or not you've unsplit all of the spans that this job will eventually clear.

**Comment by chengxiong-ruan** [comment]
___
*[pkg/jobs/jobspb/jobs.proto, line 617 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/72908#-Mp8Av81-yztxH4t1nbq:-Mp8eEml37431xUqZpuu:bn3lgyw) ([raw file](https://github.com/cockroachdb/cockroach/blob/a62bbd07aaa186243374ee13f0b498128e3e9b1a/pkg/jobs/jobspb/jobs.proto#L617)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

I was thinking like one single boolean total that corresponds to whether or not you've unsplit all of the spans that this job will eventually clear.
</blockquote></details>

oh, I see. yeah we can do that. we would still keep the table id list in the details object.

**Review by chengxiong-ruan — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/72908)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner and @postamar)

___
*[pkg/sql/drop_test.go, line 986 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/72908#-Mp8B8pfD3DMNw_Ls5TY:-Mp9-IaX6qRSzEl8e2j3:b-ojr4bd) ([raw file](https://github.com/cockroachdb/cockroach/blob/a62bbd07aaa186243374ee13f0b498128e3e9b1a/pkg/sql/drop_test.go#L986)):*
<details><summary><i>Previously, chengxiong-ruan (Chengxiong Ruan) wrote…</i></summary><blockquote>

good suggestions, will do.
</blockquote></details>

tests were organized into subtests.

**Review by ajwerner — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/72908)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @chengxiong-ruan, and @postamar)

___
*[pkg/jobs/jobspb/jobs.proto, line 617 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/72908#-Mp8Av81-yztxH4t1nbq:-MpHVz_G6_UfWt3Mg77r:b5ubqcd) ([raw file](https://github.com/cockroachdb/cockroach/blob/a62bbd07aaa186243374ee13f0b498128e3e9b1a/pkg/jobs/jobspb/jobs.proto#L617)):*
<details><summary><i>Previously, chengxiong-ruan (Chengxiong Ruan) wrote…</i></summary><blockquote>

oh, I see. yeah we can do that. we would still keep the table id list in the details object.
</blockquote></details>

I'm not so sure we've reached alignment here
___
*[pkg/jobs/jobspb/jobs.proto, line 522 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/72908#-MpHVf-b0be8MIMimhWo:-MpHVf-b0be8MIMimhWp:bb8q396) ([raw file](https://github.com/cockroachdb/cockroach/blob/c756f1ea6ccca990074ba84d8436e7c0a1657632/pkg/jobs/jobspb/jobs.proto#L522)):*
> ```
>   // UnsplitTables are the tables we want to unsplit their manually split ranges
>   repeated uint32 unsplit_tables = 11 [(gogoproto.casttype) = "github.com/cockroachdb/cockroach/pkg/sql/catalog/descpb.ID"];
> ```

I'm still not clear on why this exists. It feels to me like it's both excessive and not specific enough. The GC job already has an implied set of spans it is going to GC, why not use that directly and avoid this complexity?
___
*[pkg/sql/drop_test.go, line 1464 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/72908#-MpHWH2TCRWQpjFnNVoB:-MpHWH2TCRWQpjFnNVoC:bkde4dv) ([raw file](https://github.com/cockroachdb/cockroach/blob/c756f1ea6ccca990074ba84d8436e7c0a1657632/pkg/sql/drop_test.go#L1464)):*
> ```Go
> 			query:         "DROP DATABASE t",
> 			binaryVersion: clusterversion.UnsplitRangesInAsyncGCJobs,
> 		},
> ```

Let's test truncate and drop index. They are interesting cases because they exercise the GC job cleaning up some amount of data smaller than the table itself. I think it will reveal problems and require a bit more sophistication in this test. 
___
*[pkg/sql/drop_test.go, line 1499 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/72908#-MpHW4K6EBwuMB6X_ZlF:-MpHW4K6EBwuMB6X_ZlG:btcett9) ([raw file](https://github.com/cockroachdb/cockroach/blob/c756f1ea6ccca990074ba84d8436e7c0a1657632/pkg/sql/drop_test.go#L1499)):*
<details><summary><i alt="summary">Quoted 5 lines of code…</i></summary>

> ```
> 			tableDesc := catalogkv.TestingGetTableDescriptor(kvDB, keys.SystemSQLCodec, "t", tableName)
> 
> 			tableSpan := tableDesc.TableSpan(keys.SystemSQLCodec)
> 
> 			tests.CheckKeyCount(t, kvDB, tableSpan, numKeys)
> ```
</details>

nit, I don't think these newlines help with readability
___
*[pkg/sql/drop_test.go, line 1507 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/72908#-MpHW8gaACCQtQDusMu9:-MpHW8gaACCQtQDusMuA:b-ylypyo) ([raw file](https://github.com/cockroachdb/cockroach/blob/c756f1ea6ccca990074ba84d8436e7c0a1657632/pkg/sql/drop_test.go#L1507)):*
<details><summary><i alt="summary">Quoted 7 lines of code…</i></summary>

> ```
> 			// assert that all ranges are not manually split
> 			require.False(t, hasManuallySplitRanges(ctx, t, kvDB, tableSpan))
> 
> 			// split the last range
> 			splitLastRangeInSpan(ctx, t, kvDB, tableSpan)
> 
> 			// Verify there are manually split ranges
> ```
</details>

nit: comment style is to write comments as sentences with a capital letter at the start and a period at the end.

**Review by chengxiong-ruan — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/72908)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner and @postamar)

___
*[pkg/jobs/jobspb/jobs.proto, line 617 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/72908#-Mp8Av81-yztxH4t1nbq:-MpHvNCR-DaPwtryymX2:b3b9nle) ([raw file](https://github.com/cockroachdb/cockroach/blob/a62bbd07aaa186243374ee13f0b498128e3e9b1a/pkg/jobs/jobspb/jobs.proto#L617)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

I'm not so sure we've reached alignment here
</blockquote></details>

Will remove the table lists  in the details struct.
___
*[pkg/jobs/jobspb/jobs.proto, line 522 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/72908#-MpHVf-b0be8MIMimhWo:-MpHmDtT5VWyJo5YV6i-:bvugdpf) ([raw file](https://github.com/cockroachdb/cockroach/blob/c756f1ea6ccca990074ba84d8436e7c0a1657632/pkg/jobs/jobspb/jobs.proto#L522)):*
> I'm still not clear on why this exists. It feels to me like it's both excessive and not specific enough. The GC job already has an implied set of spans it is going to GC, why not use that directly and avoid this complexity?

ah ha, now I get it after you mentioned indexes copying in `truncate table`. Will improve this
___
*[pkg/sql/drop_test.go, line 1464 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/72908#-MpHWH2TCRWQpjFnNVoB:-MpHvX0_9ijxumM3cLWA:bne5txf) ([raw file](https://github.com/cockroachdb/cockroach/blob/c756f1ea6ccca990074ba84d8436e7c0a1657632/pkg/sql/drop_test.go#L1464)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

Let's test truncate and drop index. They are interesting cases because they exercise the GC job cleaning up some amount of data smaller than the table itself. I think it will reveal problems and require a bit more sophistication in this test. 
</blockquote></details>

Good call. will do.
___
*[pkg/sql/drop_test.go, line 1499 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/72908#-MpHW4K6EBwuMB6X_ZlF:-MpHv_Gu2iXe9RM3sUv8:bm49al3) ([raw file](https://github.com/cockroachdb/cockroach/blob/c756f1ea6ccca990074ba84d8436e7c0a1657632/pkg/sql/drop_test.go#L1499)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

> ```
> 			tableDesc := catalogkv.TestingGetTableDescriptor(kvDB, keys.SystemSQLCodec, "t", tableName)
> 
> 			tableSpan := tableDesc.TableSpan(keys.SystemSQLCodec)
> 
> 			tests.CheckKeyCount(t, kvDB, tableSpan, numKeys)
> ```
nit, I don't think these newlines help with readability
</blockquote></details>

agree, will remove.
___
*[pkg/sql/drop_test.go, line 1507 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/72908#-MpHW8gaACCQtQDusMu9:-MpHvdvpAnJqB5P07zvj:b84gld2) ([raw file](https://github.com/cockroachdb/cockroach/blob/c756f1ea6ccca990074ba84d8436e7c0a1657632/pkg/sql/drop_test.go#L1507)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

> ```
> 			// assert that all ranges are not manually split
> 			require.False(t, hasManuallySplitRanges(ctx, t, kvDB, tableSpan))
> 
> 			// split the last range
> 			splitLastRangeInSpan(ctx, t, kvDB, tableSpan)
> 
> 			// Verify there are manually split ranges
> ```
nit: comment style is to write comments as sentences with a capital letter at the start and a period at the end. 
</blockquote></details>

will make them consistent. thanks.

File: pkg/sql/gcjob/gc_job.go [hunk 10]
```diff
@@ -84,6 +90,150 @@ func performGC(
...
+			return err
+		}
+
+		if err := unsplitRange(ctx, execCfg, desc); err != nil {
+			return err
+		}
+	}
+
+	return nil
+}
```
Comment (ajwerner) [inline pkg/sql/gcjob/gc_job.go:141]: this is almost identical to the function in the `sql` package hanging off of the `planner`. Can you refactor that thing to be a free-standing function which is exported and then invoke it here?

File: pkg/sql/truncate.go [hunk 11]
```diff
@@ -279,6 +285,30 @@ func (p *planner) truncateTable(ctx context.Context, id descpb.ID, jobDesc strin
...
+		details := jobspb.SchemaChangeGCDetails{
+			Indexes:  droppedIndexes,
+			ParentID: tableDesc.ID,
+		}
+		record := CreateGCJobRecord(jobDesc, p.User(), details)
+		if _, err := p.ExecCfg().JobRegistry.CreateAdoptableJobWithTxn(
+			ctx, record, p.ExecCfg().JobRegistry.MakeJobID(), p.txn); err != nil {
+			return err
+		}
+	}
```
Comment (ajwerner) [inline pkg/sql/truncate.go:310]: we already create a GC job for the indexes, don't we?

File: pkg/sql/schema_changer.go [hunk 12]
```diff
@@ -642,6 +642,7 @@ func (sc *SchemaChanger) exec(ctx context.Context) error {
 			if tableDesc.GetDropTime() > 0 {
 				dropTime = tableDesc.GetDropTime()
 			}
+
```
Comment (ajwerner) [inline pkg/sql/schema_changer.go:645]: why?

File: pkg/sql/schema_changer.go [hunk 13]
```diff
@@ -2186,6 +2187,7 @@ func (r schemaChangeResumer) Resume(ctx context.Context, execCtx interface{}) er
 		for i, table := range details.DroppedTables {
 			tablesToGC[i] = jobspb.SchemaChangeGCDetails_DroppedID{ID: table.ID, DropTime: dropTime}
 		}
+
```
Comment (ajwerner) [inline pkg/sql/schema_changer.go:2190]: why?

File: pkg/jobs/jobspb/jobs.proto [hunk 14]
```diff
@@ -602,7 +602,10 @@ message SchemaChangeGCProgress {
   repeated TableProgress tables = 2 [(gogoproto.nullable) = false];
 
   // The status of the tenant to be deleted.
- TenantProgress tenant = 3;
+  TenantProgress tenant = 3;
+
+  // Indicates whether unsplitting of tables in UnsplitTables is finished
+  bool tables_unsplit_done = 4;
```
Comment (ajwerner) [inline pkg/jobs/jobspb/jobs.proto:608]: This name is sort of bad because we also unsplit indexes.

nit: start the comment with the name of the field as it will be in go (PascalCase).

**Review by chengxiong-ruan — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/72908)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner and @postamar)

___
*[pkg/jobs/jobspb/jobs.proto, line 608 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/72908#-Mp75gue3JWnsyNDgb23-r8-608:-MpgdQfSDwBYFb8vLc5g:bh90wl7) ([raw file](https://github.com/cockroachdb/cockroach/blob/7a44da11576dc5c017de6de2b7a0cbff8006d77e/pkg/jobs/jobspb/jobs.proto#L608)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

This name is sort of bad because we also unsplit indexes.

nit: start the comment with the name of the field as it will be in go (PascalCase). 
</blockquote></details>

Good point, will do.
___
*[pkg/sql/schema_changer.go, line 645 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/72908#-Mp75gue3JWnsyNDgb26-r8-645:-Mpgdae07LZShOO91B6I:b-7xv877) ([raw file](https://github.com/cockroachdb/cockroach/blob/7a44da11576dc5c017de6de2b7a0cbff8006d77e/pkg/sql/schema_changer.go#L645)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

why?
</blockquote></details>

Oops, empty line left over between revision... will remove
___
*[pkg/sql/schema_changer.go, line 2190 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/72908#-Mp75gue3JWnsyNDgb26-r8-2190:-MpgdrcO1q8byXSmj4aW:bvu2658) ([raw file](https://github.com/cockroachdb/cockroach/blob/7a44da11576dc5c017de6de2b7a0cbff8006d77e/pkg/sql/schema_changer.go#L2190)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

why?
</blockquote></details>

same as above... will remove
___
*[pkg/sql/truncate.go, line 310 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/72908#-MonDjoO2bdPfANmo5YG-r8-310:-MpgfjhT6vxCVpR0QNFA:b-yek9mt) ([raw file](https://github.com/cockroachdb/cockroach/blob/7a44da11576dc5c017de6de2b7a0cbff8006d77e/pkg/sql/truncate.go#L310)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

we already create a GC job for the indexes, don't we?
</blockquote></details>

oh, I actually version gate the timing of creating the gc job as well. The current implementation schedule gc job before split points are copied, which is bad. So I move it here but with a version gate so that split points are copied before gc job unsplit ranges. I added a `TODO` comment to remove the old gc job creation. Let me know if this makes sense.
___
*[pkg/sql/gcjob/gc_job.go, line 141 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/72908#-Mp75gue3JWnsyNDgb24-r8-141:-Mpge9WkAi-FZpItGxvg:b-prv07o) ([raw file](https://github.com/cockroachdb/cockroach/blob/7a44da11576dc5c017de6de2b7a0cbff8006d77e/pkg/sql/gcjob/gc_job.go#L141)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

this is almost identical to the function in the `sql` package hanging off of the `planner`. Can you refactor that thing to be a free-standing function which is exported and then invoke it here?
</blockquote></details>

good point. I actually have a `TODO` comment to remove the identical one in planner. This is just to make it easier for future removing. But I will refactor it in case there'd a be bug or anything and we'd need to update both functions.

**Review by ajwerner — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/72908)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @chengxiong-ruan, and @postamar)

___
*[pkg/sql/truncate.go, line 310 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/72908#-MonDjoO2bdPfANmo5YG-r8-310:-MpgiBkM6AQKXgmZzFLo:bwlz6ii) ([raw file](https://github.com/cockroachdb/cockroach/blob/7a44da11576dc5c017de6de2b7a0cbff8006d77e/pkg/sql/truncate.go#L310)):*
<details><summary><i>Previously, chengxiong-ruan (Chengxiong Ruan) wrote…</i></summary><blockquote>

oh, I actually version gate the timing of creating the gc job as well. The current implementation schedule gc job before split points are copied, which is bad. So I move it here but with a version gate so that split points are copied before gc job unsplit ranges. I added a `TODO` comment to remove the old gc job creation. Let me know if this makes sense.
</blockquote></details>

I don't think I understand, we want a single GC job either way, right?

**Review by chengxiong-ruan — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/72908)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner and @postamar)

___
*[pkg/sql/truncate.go, line 310 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/72908#-MonDjoO2bdPfANmo5YG-r8-310:-MpgjmFUE3PAkeNjQSkZ:bgwc4g2) ([raw file](https://github.com/cockroachdb/cockroach/blob/7a44da11576dc5c017de6de2b7a0cbff8006d77e/pkg/sql/truncate.go#L310)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

I don't think I understand, we want a single GC job either way, right?
</blockquote></details>

Correct. There is a single GC job in the old and new version, but just scheduled at different point in this function.

**Review by ajwerner — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/72908)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @chengxiong-ruan, and @postamar)

___
*[pkg/sql/truncate.go, line 310 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/72908#-MonDjoO2bdPfANmo5YG-r8-310:-MpgkpRm8_sym7PL-b4y:b-82ptc9) ([raw file](https://github.com/cockroachdb/cockroach/blob/7a44da11576dc5c017de6de2b7a0cbff8006d77e/pkg/sql/truncate.go#L310)):*
<details><summary><i>Previously, chengxiong-ruan (Chengxiong Ruan) wrote…</i></summary><blockquote>

Correct. There is a single GC job in the old and new version, but just scheduled at different point in this function.
</blockquote></details>

Oh, I see. Why do that? Isn't their state identical?

**Comment by chengxiong-ruan** [comment]
___
*[pkg/sql/truncate.go, line 310 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/72908#-MonDjoO2bdPfANmo5YG-r8-310:-MpguhxQ7Fdu3tbIMF3r:bj7nsp8) ([raw file](https://github.com/cockroachdb/cockroach/blob/7a44da11576dc5c017de6de2b7a0cbff8006d77e/pkg/sql/truncate.go#L310)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

Oh, I see. Why do that? Isn't their state identical?
</blockquote></details>

as talked offline this is removed :)

**Review by ajwerner — COMMENTED** [review]
I think the test failure is a flake. I haven't digested the testing yet but the code is very close. 

> Reviewed 6 of 14 files at r7, 5 of 6 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/72908#-:-MphAGjM0A1biEGZqITY:b-xb8eak)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @chengxiong-ruan, and @postamar)

___
*[pkg/sql/drop_table.go, line 355 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/72908#-Mph9uHo3gVn9LcmpNcq:-Mph9uHo3gVn9LcmpNcr:b-tkv3g0) ([raw file](https://github.com/cockroachdb/cockroach/blob/2e50b7d0053a8a1acc63fc92d13fa34b367c9bc1/pkg/sql/drop_table.go#L355)):*
> ```
> func UnsplitRangesForTable(
> 	ctx context.Context, execCfg *ExecutorConfig, tableDesc catalog.TableDescriptor,
> ) error {
> ```
let's refactor this to take a key span instead of a descriptor. Indexes and tables both have corresponding key spans. Then that can be the only thing we need to export. 

Can we tighten the dependencies to this function to just the pieces of the execCfg in use? There isn't a ton, and there will be less if we take a key span. I think you should lift the `ForSystemTenant` check above this call as well.

**Review by chengxiong-ruan — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/72908)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner and @postamar)

___
*[pkg/sql/drop_table.go, line 355 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/72908#-Mph9uHo3gVn9LcmpNcq:-MphJX7T2_cswfeZNkuB:bfkrl8) ([raw file](https://github.com/cockroachdb/cockroach/blob/2e50b7d0053a8a1acc63fc92d13fa34b367c9bc1/pkg/sql/drop_table.go#L355)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

> ```
> func UnsplitRangesForTable(
> 	ctx context.Context, execCfg *ExecutorConfig, tableDesc catalog.TableDescriptor,
> ) error {
> ```
let's refactor this to take a key span instead of a descriptor. Indexes and tables both have corresponding key spans. Then that can be the only thing we need to export. 

Can we tighten the dependencies to this function to just the pieces of the execCfg in use? There isn't a ton, and there will be less if we take a key span. I think you should lift the `ForSystemTenant` check above this call as well. 
</blockquote></details>

good idea. made changes as suggested. for indexes, there will be more round trips to kv to scan metas, but it's fine for a async job.

File: pkg/sql/gcjob/gc_job.go [hunk 15]
```diff
@@ -84,6 +88,64 @@ func performGC(
...
+			return err
+		}); err != nil {
+			if errors.Is(err, catalog.ErrDescriptorNotFound) {
+				log.Warningf(ctx, "table descriptor %d not found while attempting to GC, skipping", droppedTable.ID)
+				continue
+			}
+			return errors.Wrapf(err, "failed to fetch table %d", droppedTable.ID)
+		}
+
+		span := table.TableSpan(execCfg.Codec)
```
Comment (ajwerner) [inline pkg/sql/gcjob/gc_job.go:114]: nit: you could just use `Codec.TablePrefix` and avoid looking up the tables.

File: pkg/sql/unsplit_range_test.go [hunk 16]
```diff
@@ -0,0 +1,460 @@
...
+			t.Fatal(err)
+		}
+		if bytes.Equal(desc.StartKey.AsRawKey(), startKey) && !desc.GetStickyBit().IsEmpty() {
+			return true
+		}
+	}
+	return false
+}
+
+// TODO(Chengxiong): remove test for old version and update this comment.
```
Comment (ajwerner) [inline pkg/sql/unsplit_range_test.go:174]: what is there to do here?

File: pkg/sql/unsplit_range_test.go [hunk 17]
```diff
@@ -0,0 +1,460 @@
...
+			})
+			tests.CheckKeyCount(t, kvDB, tableSpan, 0)
+
+			// Verify there is no manually split ranges.
+			require.False(t, hasManuallySplitRangesInSpan(ctx, t, kvDB, tableSpan))
+		})
+	}
+}
+
+// TODO(Chengxiong): remove test for old version and update this comment.
```
Comment (ajwerner) [inline pkg/sql/unsplit_range_test.go:270]: what is there to do here?

File: pkg/sql/unsplit_range_test.go [hunk 18]
```diff
@@ -0,0 +1,460 @@
...
+		},
+		{
+			name:          "drop-database-unsplit-async",
+			query:         "DROP DATABASE t",
+			binaryVersion: clusterversion.UnsplitRangesInAsyncGCJobs,
+		},
+	}
+
+	for _, testCase := range testCases {
+		t.Run(testCase.name, func(t *testing.T) {
```
Comment (ajwerner) [inline pkg/sql/unsplit_range_test.go:210]: these tests still share a very large amount of structure. Can you rework the cases to plumb through a few more arguments into the test case so that all of these can be subtests of a single test. I really don't think there's much to do to make that happen.

**Review by ajwerner — COMMENTED** [review]
code changes look more or less good to me. Let's clean up the testing and this will be good to go.

**Review by chengxiong-ruan — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/72908)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner and @postamar)

___
*[pkg/sql/unsplit_range_test.go, line 174 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/72908#-MpgD6KPYvX4Rpc5hfMO-r10-174:-MphjiyI3L2Ok4mn1kmj:b-wih2c8) ([raw file](https://github.com/cockroachdb/cockroach/blob/1b6ff9a96ce9e3087a8771be704e159b0a8263cd/pkg/sql/unsplit_range_test.go#L174)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

what is there to do here?
</blockquote></details>

sorry for the confusion, we would need to drop test cases with binary version `clusterversion.UnsplitRangesInAsyncGCJobs - 1` since we will clean the old code unsplitting synchronously.
___
*[pkg/sql/unsplit_range_test.go, line 210 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/72908#-MpgD6KPYvX4Rpc5hfMO-r10-210:-Mphk5K62H5hRTQXkR6W:bi2z5kt) ([raw file](https://github.com/cockroachdb/cockroach/blob/1b6ff9a96ce9e3087a8771be704e159b0a8263cd/pkg/sql/unsplit_range_test.go#L210)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

these tests still share a very large amount of structure. Can you rework the cases to plumb through a few more arguments into the test case so that all of these can be subtests of a single test. I really don't think there's much to do to make that happen.
</blockquote></details>

test cases merged :)
___
*[pkg/sql/unsplit_range_test.go, line 270 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/72908#-MpgD6KPYvX4Rpc5hfMO-r10-270:-Mphk6ht2pr9-gqKwDo1:b-4nq930) ([raw file](https://github.com/cockroachdb/cockroach/blob/1b6ff9a96ce9e3087a8771be704e159b0a8263cd/pkg/sql/unsplit_range_test.go#L270)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

what is there to do here?
</blockquote></details>

same :)
___
*[pkg/sql/gcjob/gc_job.go, line 114 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/72908#-Mp75gue3JWnsyNDgb24-r10-114:-MphkEefBGlj_Y2HELfB:b-e727xl) ([raw file](https://github.com/cockroachdb/cockroach/blob/1b6ff9a96ce9e3087a8771be704e159b0a8263cd/pkg/sql/gcjob/gc_job.go#L114)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

nit: you could just use `Codec.TablePrefix` and avoid looking up the tables. 
</blockquote></details>

good catch, updated!

File: pkg/sql/unsplit_range_test.go [hunk 19]
```diff
@@ -0,0 +1,320 @@
...
+			allKeyCntAfterGC:       numRows * 2,
+			indexKeyCntAfterGC:     0,
+			hasSplitOnTableAfterGC: true, // It's true since we only unsplit ranges of index foo
+			hasSplitOnKeyAfterGC:   true,
+		},
+	}
+
+	for _, testCase := range testCases {
+		t.Run(testCase.name, func(t *testing.T) {
+			defer leaktest.AfterTest(t)()
```
Comment (ajwerner) [inline pkg/sql/unsplit_range_test.go:255]: just do this one call once at the top of the outermost test (as you have). It'll slow things down otherwise.

File: pkg/sql/unsplit_range_test.go [hunk 20]
```diff
@@ -0,0 +1,320 @@
...
+	return false
+}
+
+// Test that manually split ranges get unsplit when dropping a
+// table/database/index or truncating a table It verifies that the logic is
+// working on both the old (before version `UnsplitRangesInAsyncGCJobs`) and new
+// (from versiom `UnsplitRangesInAsyncGCJobs`) pathes.
+// TODO(Chengxiong): remove test for test cases with binary version
+// `clusterversion.UnsplitRangesInAsyncGCJobs - 1` and update this comment in
+// 22.2
```
Comment (ajwerner) [inline pkg/sql/unsplit_range_test.go:162]: nit: trailing period.

File: pkg/sql/unsplit_range_test.go [hunk 21]
```diff
@@ -0,0 +1,320 @@
...
+func TestUnsplitRanges(t *testing.T) {
+	defer leaktest.AfterTest(t)()
+
+	const numRows = 2*row.TableTruncateChunkSize + 1
+	const numKeys = 3 * numRows
+	const tableName string = "test1"
+
+	testCases := []struct {
```
Comment (ajwerner) [inline pkg/sql/unsplit_range_test.go:170]: I think I'd define a struct type in this test scope:

```go
type testCase struct {
		name                   string
		query                  string
		binaryVersion          clusterversion.Key
		allKeyCntAfterGC       int  // Key count with table prefix.
		indexKeyCntAfterGC     int  // Key count with index prefix.
		hasSplitOnTableAfterGC bool // Any split on the table in general?
		hasSplitOnKeyAfterGC   bool // Any split on the range start with splitKey (where we manually split in the test)?
}
testCases := []testCase{
   // ...
}

ctx := context.Background
getMidKeyInSpan := func(/* ... */) { /* ... */ }
run := func(t *testing.T, tc testCase) {
}
for _, tc := range testCases {
     t.Run(tc.name, func(t *testing.T) { run(t, tc) })
}
```

File: pkg/sql/unsplit_range_test.go [hunk 22]
```diff
@@ -0,0 +1,320 @@
...
+		name                   string
+		query                  string
+		binaryVersion          clusterversion.Key
+		allKeyCntAfterGC       int  // Key count with table prefix.
+		indexKeyCntAfterGC     int  // Key count with index prefix.
+		hasSplitOnTableAfterGC bool // Any split on the table in general?
+		hasSplitOnKeyAfterGC   bool // Any split on the range start with splitKey (where we manually split in the test)?
```
Comment (ajwerner) [inline pkg/sql/unsplit_range_test.go:177]: I think you could use commentary to explain to a reader better how this test works. Try to come to this test with the idea that you know nothing about how it works or what it does and try to make the commentary useful enough to make it not too painful to figure out.

File: pkg/sql/table.go [hunk 23]
```diff
@@ -114,6 +114,10 @@ func (p *planner) createOrUpdateSchemaChangeJob(
 		)
 	}
 
+	// p.extendedEvalCtx.SchemaChangeJobRecords refers to schemaChangeJobRecords
+	// `of extraTxnState` in `sql.connExecutor`. `connExecutor.createJobs` is the
```
Comment (ajwerner) [inline pkg/sql/table.go:118]: the backticks here are a little weird to me. Can you take another pass on this comment?

**Review by ajwerner — COMMENTED** [review]
Just cleanliness and readability at this point. Nice!

**Review by chengxiong-ruan — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/72908)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner and @postamar)

___
*[pkg/sql/unsplit_range_test.go, line 162 at r12](https://reviewable.io/reviews/cockroachdb/cockroach/72908#-MpgD6KPYvX4Rpc5hfMO-r12-162:-Mpi_ZPAD7YyY2pyoMxs:b7ape9s) ([raw file](https://github.com/cockroachdb/cockroach/blob/af698fd497567df7eda3402e10d417f77107f0ad/pkg/sql/unsplit_range_test.go#L162)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

nit: trailing period.
</blockquote></details>

good eyes
___
*[pkg/sql/unsplit_range_test.go, line 170 at r12](https://reviewable.io/reviews/cockroachdb/cockroach/72908#-MpgD6KPYvX4Rpc5hfMO-r12-170:-Mpi_gFo3ykPYq6aIwCK:bwysonc) ([raw file](https://github.com/cockroachdb/cockroach/blob/af698fd497567df7eda3402e10d417f77107f0ad/pkg/sql/unsplit_range_test.go#L170)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

I think I'd define a struct type in this test scope:

```go
type testCase struct {
		name                   string
		query                  string
		binaryVersion          clusterversion.Key
		allKeyCntAfterGC       int  // Key count with table prefix.
		indexKeyCntAfterGC     int  // Key count with index prefix.
		hasSplitOnTableAfterGC bool // Any split on the table in general?
		hasSplitOnKeyAfterGC   bool // Any split on the range start with splitKey (where we manually split in the test)?
}
testCases := []testCase{
   // ...
}

ctx := context.Background
getMidKeyInSpan := func(/* ... */) { /* ... */ }
run := func(t *testing.T, tc testCase) {
}
for _, tc := range testCases {
     t.Run(tc.name, func(t *testing.T) { run(t, tc) })
}
```
</blockquote></details>

changed as suggested.
___
*[pkg/sql/unsplit_range_test.go, line 177 at r12](https://reviewable.io/reviews/cockroachdb/cockroach/72908#-MpgD6KPYvX4Rpc5hfMO-r12-177:-Mpi_o0k3a0ll2nw0WjA:bkuz3dv) ([raw file](https://github.com/cockroachdb/cockroach/blob/af698fd497567df7eda3402e10d417f77107f0ad/pkg/sql/unsplit_range_test.go#L177)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

I think you could use commentary to explain to a reader better how this test works. Try to come to this test with the idea that you know nothing about how it works or what it does and try to make the commentary useful enough to make it not too painful to figure out. 
</blockquote></details>

added more detailed comments!
___
*[pkg/sql/unsplit_range_test.go, line 255 at r12](https://reviewable.io/reviews/cockroachdb/cockroach/72908#-MpgD6KPYvX4Rpc5hfMO-r12-255:-Mpi_x-e8_VR22GsptT0:b-hfpv0l) ([raw file](https://github.com/cockroachdb/cockroach/blob/af698fd497567df7eda3402e10d417f77107f0ad/pkg/sql/unsplit_range_test.go#L255)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

just do this one call once at the top of the outermost test (as you have). It'll slow things down otherwise. 
</blockquote></details>

removed
___
*[pkg/sql/table.go, line 118 at r12](https://reviewable.io/reviews/cockroachdb/cockroach/72908#-Mp75gue3JWnsyNDgb27-r12-118:-Mpia-8i1C4pwULdDQq4:b-2pgs5f) ([raw file](https://github.com/cockroachdb/cockroach/blob/af698fd497567df7eda3402e10d417f77107f0ad/pkg/sql/table.go#L118)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

the backticks here are a little weird to me. Can you take another pass on this comment?
</blockquote></details>

moved the comment in the type definition.

File: pkg/sql/gcjob/gc_job.go [hunk 24]
```diff
@@ -104,6 +154,23 @@ func (r schemaChangeGCResumer) Resume(ctx context.Context, execCtx interface{})
...
+
+		if len(details.Tables) > 0 {
+			if err := unsplitRangesForTables(ctx, execCfg, details.Tables); err != nil {
+				return err
+			}
+		}
+
+		progress.RangesUnsplitDone = true
+		persistProgress(ctx, execCfg, r.jobID, progress, runningStatusGC(progress))
+	}
```
Comment (ajwerner) [inline pkg/sql/gcjob/gc_job.go:172]: okay, now this is onto mega nits.  Just making this comment to share perspective, feel free to disregard. I've come to like the readability of a pattern of functions called things like:
```
func maybeUnsplitRanges(ctx context.Context, execCfg *sql.ExecutorConfig, details ...) error {
    if progress.RangesUnsplitDone {
        return nil
    }
    // ...
}
```

It's a nice conduit for commentary.

**Review by ajwerner — APPROVED** [review]
I think one of your logic tests has a problem. Otherwise LGTM.

**Review by chengxiong-ruan — COMMENTED** [review]
It was because kvClient.ScanMetaKVs() return all ranges overlaps with the span... for index span, it could return a range with a `StartKey` outside of the index span. We should skip such range because we only care about ranges with split points as `StartKey`. There aren't such cases for `drop table/database` or `truncate table`.

Funny that I found I didn't version gate the unsplitting in `drop_index.go` because it does not use the `unsplitRangesForTable()` method >_> probably because skipping the edge range makes it a special case...

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/72908#-:-MpmuFPGBGQ5kSWp_sn6:b-avbmmg)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner and @postamar)

___
*[pkg/sql/gcjob/gc_job.go, line 172 at r15](https://reviewable.io/reviews/cockroachdb/cockroach/72908#-Mp75gue3JWnsyNDgb24-r15-172:-MpmvqGk4lWZ5BoCl6r0:b-5gkk6f) ([raw file](https://github.com/cockroachdb/cockroach/blob/3d63bcfc622ec09c5abb4726bacf70e399d80a9a/pkg/sql/gcjob/gc_job.go#L172)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

okay, now this is onto mega nits.  Just making this comment to share perspective, feel free to disregard. I've come to like the readability of a pattern of functions called things like:
```
func maybeUnsplitRanges(ctx context.Context, execCfg *sql.ExecutorConfig, details ...) error {
    if progress.RangesUnsplitDone {
        return nil
    }
    // ...
}
```

It's a nice conduit for commentary.
</blockquote></details>

I really like this idea. Made change as suggested.

**Comment by chengxiong-ruan** [comment]
rebased after https://github.com/cockroachdb/cockroach/pull/73342 is committed... hope CI will pass this time >_>

**Comment by chengxiong-ruan** [comment]
TFTR!

bors r+
