### PR TITLE
release-19.1: sql: prevent crash during logging with empty statement

### LINKED ISSUE #37461: sentry: conn_executor.go:431: panic while executing 0 statements: : caused by <redacted>
This issue was autofiled by Sentry. It represents a crash or reported error on a live cluster with telemetry enabled.

Sentry link: https://sentry.io/organizations/cockroach-labs/issues/1021346569/?referrer=webhooks_plugin

Panic message:

>conn_executor.go:431: panic while executing 0 statements: : caused by <redacted>

<details>
<summary>Stacktrace (expand for inline code snippets):</summary>

https://github.com/cockroachdb/cockroach/blob/25dd36f0139bf65b80758deeeccf35ee17ebd622/pkg/sql/conn_executor.go#L430-L432 in pkg/sql.(*Server).ServeConn.func1
/usr/local/go/src/runtime/asm_amd64.s#L521-L523 in runtime.call32
/usr/local/go/src/runtime/panic.go#L512-L514 in runtime.gopanic
/usr/local/go/src/runtime/panic.go#L81-L83 in runtime.panicmem
/usr/local/go/src/runtime/signal_unix.go#L389-L391 in runtime.sigpanic
https://github.com/cockroachdb/cockroach/blob/25dd36f0139bf65b80758deeeccf35ee17ebd622/pkg/sql/conn_executor.go#L1199-L1201 in pkg/sql.(*connExecutor).run
https://github.com/cockroachdb/cockroach/blob/25dd36f0139bf65b80758deeeccf35ee17ebd622/pkg/sql/conn_executor.go#L432-L434 in pkg/sql.(*Server).ServeConn
https://github.com/cockroachdb/cockroach/blob/25dd36f0139bf65b80758deeeccf35ee17ebd622/pkg/sql/pgwire/conn.go#L336-L338 in pkg/sql/pgwire.(*conn).serveImpl.func4
</details>

```
pkg/sql/conn_executor.go in pkg/sql.(*Server).ServeConn.func1 at line 431
/usr/local/go/src/runtime/asm_amd64.s in runtime.call32 at line 522
/usr/local/go/src/runtime/panic.go in runtime.gopanic at line 513
/usr/local/go/src/runtime/panic.go in runtime.panicmem at line 82
/usr/local/go/src/runtime/signal_unix.go in runtime.sigpanic at line 390
pkg/sql/conn_executor.go in pkg/sql.(*connExecutor).run at line 1200
pkg/sql/conn_executor.go in pkg/sql.(*Server).ServeConn at line 433
pkg/sql/pgwire/conn.go in pkg/sql/pgwire.(*conn).serveImpl.func4 at line 337
```

| Tag | Value |
|---|---|
| Cockroach Release | `v19.1.0` |
| Cockroach SHA: | 25dd36f0139bf65b80758deeeccf35ee17ebd622 |
| Platform | linux amd64 |
| Distribution | CCL |
| Environment | v19.1.0 |
| Command | server |
| Go Version | `go1.11.6`|
| # of CPUs |24 |
| # of Goroutines |309 |

### PR DESCRIPTION
**Pull request by jordanlewis**
Backport 1/1 commits from #37104.

Fixes #37461.

/cc @cockroachdb/release

---

Previously, the database would crash if a client sent an empty prepare
statement when we had high verbosity on for the conn_executor.

Release note: None

### CODE REVIEW

**Review by RaduBerinde — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/38373#-:-Li8slFG-FQ2QSztQNUP:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @RaduBerinde)

File: pkg/sql/conn_executor.go [hunk 1]
```diff
@@ -1200,6 +1200,12 @@ func (ex *connExecutor) run(
...
 				break
 			}
+
+			if portal.Stmt.AST == nil {
+				res = ex.clientComm.CreateEmptyQueryResult(pos)
+				break
+			}
+
 			if log.ExpensiveLogEnabled(ex.Ctx(), 2) {
 				log.VEventf(ex.Ctx(), 2, "portal resolved to: %s", portal.Stmt.AST.String())
```
Comment (knz) [inline pkg/sql/conn_executor.go]: tip: if you were to pass `portal.Stmt.AST` by reference without calling `String()` upfront, you could drop `ExpensiveLogEnabled`: the log event formatter would only call `String()` if the event was enabled.

Comment (jordanlewis) [reply pkg/sql/conn_executor.go]: Thanks - just want to keep this a backport for now though
