### PR TITLE
storage: deflake TestConcurrentRaftSnapshots

### LINKED ISSUE #9903: storage: TestConcurrentRaftSnapshots is flaky
From https://teamcity.cockroachdb.com/viewLog.html?buildId=30371&buildTypeId=Cockroach_UnitTests_Test

```
Stacktraces:
(new) TestConcurrentRaftSnapshots 
	client_raft_test.go:672: range 1: replica {1 1 1} not lease holder; <nil> is
```

I saw a similar failure in a different test recently where the test expected store 1 to always be the lease holder but that wasn't necessarily true under stress situations. Increasing the lease timeout might help here too.

### PR DESCRIPTION
**Pull request by petermattis**
Don't expireLeases if a store is stopped as doing so causes unexpected
lease transfers in tests.

Rework multiTestContext.addStore so that it respects the configured
RaftElectionTimeoutTicks instead of always using the defaults.

Fixes #9903

---

This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/9905)

### CODE REVIEW

File: storage/client_test.go [hunk 1]
```diff
@@ -498,7 +498,6 @@ func (t *multiTestContextKVTransport) SendNext(done chan<- kv.BatchCall) {
 		done <- kv.BatchCall{Reply: br, Err: nil}
 	}) != nil {
 		done <- kv.BatchCall{Err: roachpb.NewSendError("store is stopped")}
-		t.mtc.expireLeases()
```
Comment (bdarnell) [inline storage/client_test.go]: `multiTestContext` uses a manual clock, so leases will never expire on their own. If a node goes down while holding a lease, we need to expire its leases. This was a crude attempt to do that, by expiring leases whenever the node that DistSender told us to talk to is down. Removing this might make some other tests flaky, but I don't remember which tests. 

In general, tests using multiTestContext haven't been sensitive to spurious lease expirations. Maybe tests where this matters should be using TestCluster instead.

**Comment by bdarnell** [comment]
LGTM other than the removal of expireLeases. This makes me nervous but I'd be OK with it if everything remains stable under stress.

**Comment by petermattis** [comment]
The removal of `expireLeases`  is what fixed `TestConcurrentRaftSnapshots` flakiness. I can explain in detail why that call was causing problems if you want. Perhaps there is a better solution.

File: storage/client_test.go (hunk 1 above)
Comment (petermattis) [inline storage/client_test.go]: Understood about the manual clock. If a store is stopped, `DistSender` will send a request to another store (if one is available) and we'll get a `NotLeaseHolderError` which will expire the lease. The problem with expiring leases in this code path is that the down store may not be the lease holder. In the case of `TestConcurrentRaftSnapshots`, we replica a range to stores 1, 2, 3, 4, 5, then we stop stores 2 and 3. If a request accidentally gets directed at one of the down stores then we expire leases and any subsequent request to store 1 (which is how we direct requests in most `multiTestContext`-based tests) will die with a `NotLeaseHolderError`. 

Note that we almost never stop store 1 in `multiTestContext`-based tests. One test which does is `TestRemoveRangeWithoutGC`. I've stressed that test with this PR and it appears ok.

Comment (bdarnell) [inline storage/client_test.go]: > If a store is stopped, DistSender will send a request to another store (if one is available) and we'll get a NotLeaseHolderError which will expire the lease.

 OK, I think in that case this is safe. We've gotten a lot better about this kind of thing since this code was written. LGTM.
