### PR TITLE
Make shutdown more robust.

### LINKED ISSUE #597: Test failure in CI build 1232
The following test appears to have failed:

[#1232](https://circleci.com/gh/cockroachdb/cockroach/1232):

```
I0408 19:29:24.693501     270 multiraft.go:638] HardState updated: {Term:6 Vote:257 Commit:35 XXX_unrecognized:[]}
I0408 19:29:24.694914     270 multiraft.go:641] New Entry[0]: 6/35 EntryNormal 13d3209ccf94d81865157426e50ec28b: raft_id:1 cmd:<end_transaction:<header:<timestamp:<wall_time:0 logical:31 > cmd_id:<wall_time:1428521364676204568 random:7283855682742174347 > key:"b
I0408 19:29:24.696199     270 multiraft.go:644] Committed Entry[0]: 6/35 EntryNormal 13d3209ccf94d81865157426e50ec28b: raft_id:1 cmd:<end_transaction:<header:<timestamp:<wall_time:0 logical:31 > cmd_id:<wall_time:1428521364676204568 random:7283855682742174347 > key:"b
I0408 19:29:24.704034     270 raft.go:390] raft: 101 became follower at term 5
I0408 19:29:24.704266     270 raft.go:207] raft: newRaft 101 [peers: [101], term: 5, commit: 10, applied: 10, lastindex: 10, lastterm: 5]
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x10 pc=0xb00a56]

goroutine 1674 [running]:
github.com/cockroachdb/cockroach/multiraft.(*state).propose(0xc2080a0b70, 0xc208656900)
	/go/src/github.com/cockroachdb/cockroach/multiraft/multiraft.go:625 +0xc6
github.com/cockroachdb/cockroach/multiraft.(*state).start(0xc2080a0b70)
	/go/src/github.com/cockroachdb/cockroach/multiraft/multiraft.go:477 +0x1ad7
created by github.com/cockroachdb/cockroach/multiraft.(*MultiRaft).Start
	/go/src/github.com/cockroachdb/cockroach/multiraft/multiraft.go:149 +0x60

--
goroutine 1675 [select]:
github.com/cockroachdb/cockroach/storage.(*Store).processRaft(0xc208398160)
	/go/src/github.com/cockroachdb/cockroach/storage/store.go:1121 +0xee6
created by github.com/cockroachdb/cockroach/storage.(*Store).Start
	/go/src/github.com/cockroachdb/cockroach/storage/store.go:477 +0xc07
FAIL	github.com/cockroachdb/cockroach/storage	3.446s
=== RUN TestBatchBasics
--- PASS: TestBatchBasics (0.00s)
=== RUN TestBatchGet
--- PASS: TestBatchGet (0.00s)
=== RUN TestBatchMerge
--- PASS: TestBatchMerge (0.00s)
=== RUN TestBatchProto
--- PASS: TestBatchProto (0.00s)
=== RUN TestBatchScan
--- PASS: TestBatchScan (0.00s)
I0408 19:29:24.693501     270 multiraft.go:638] HardState updated: {Term:6 Vote:257 Commit:35 XXX_unrecognized:[]}
I0408 19:29:24.694914     270 multiraft.go:641] New Entry[0]: 6/35 EntryNormal 13d3209ccf94d81865157426e50ec28b: raft_id:1 cmd:<end_transaction:<header:<timestamp:<wall_time:0 logical:31 > cmd_id:<wall_time:1428521364676204568 random:7283855682742174347 > key:"b
I0408 19:29:24.696199     270 multiraft.go:644] Committed Entry[0]: 6/35 EntryNormal 13d3209ccf94d81865157426e50ec28b: raft_id:1 cmd:<end_transaction:<header:<timestamp:<wall_time:0 logical:31 > cmd_id:<wall_time:1428521364676204568 random:7283855682742174347 > key:"b
I0408 19:29:24.704034     270 raft.go:390] raft: 101 became follower at term 5
I0408 19:29:24.704266     270 raft.go:207] raft: newRaft 101 [peers: [101], term: 5, commit: 10, applied: 10, lastindex: 10, lastterm: 5]
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x10 pc=0xb00a56]

goroutine 1674 [running]:
github.com/cockroachdb/cockroach/multiraft.(*state).propose(0xc2080a0b70, 0xc208656900)
	/go/src/github.com/cockroachdb/cockroach/multiraft/multiraft.go:625 +0xc6
github.com/cockroachdb/cockroach/multiraft.(*state).start(0xc2080a0b70)
	/go/src/github.com/cockroachdb/cockroach/multiraft/multiraft.go:477 +0x1ad7
created by github.com/cockroachdb/cockroach/multiraft.(*MultiRaft).Start
	/go/src/github.com/cockroachdb/cockroach/multiraft/multiraft.go:149 +0x60

--
goroutine 1675 [select]:
github.com/cockroachdb/cockroach/storage.(*Store).processRaft(0xc208398160)
	/go/src/github.com/cockroachdb/cockroach/storage/store.go:1121 +0xee6
created by github.com/cockroachdb/cockroach/storage.(*Store).Start
	/go/src/github.com/cockroachdb/cockroach/storage/store.go:477 +0xc07
FAIL	github.com/cockroachdb/cockroach/storage	3.446s
=== RUN TestBatchBasics
--- PASS: TestBatchBasics (0.00s)
=== RUN TestBatchGet
--- PASS: TestBatchGet (0.00s)
=== RUN TestBatchMerge
--- PASS: TestBatchMerge (0.00s)
=== RUN TestBatchProto
--- PASS: TestBatchProto (0.00s)
=== RUN TestBatchScan
--- PASS: TestBatchScan (0.00s)

```
Please assign, take a look and update the issue accordingly.

### PR DESCRIPTION
**Pull request by bdarnell**
We had whitelisted the txnMetadata.close goroutines in leaktest, but
the fact that they were still running after shutdown would sometimes
leave other threads to be leaked, or cause nil pointer panics.

This commit adds additional checks in retry loops that may be running
after shutdown to end the loop cleanly and allow all goroutines to
exit. This lets us remove the whitelisting of txnMetadata.close.

Closes #597

### CODE REVIEW

File: kv/dist_sender.go [hunk 1]
```diff
@@ -429,6 +431,13 @@ func (ds *DistSender) Send(call *client.Call) {
 	for {
 		reply := call.Reply
 		err := util.RetryWithBackoff(retryOpts, func() (util.RetryStatus, error) {
+			select {
+			case <-ds.closer:
+				call.Reply.Header().SetGoError(util.Errorf("sender is closed"))
```
Comment (spencerkimball) [inline kv/dist_sender.go]: I'm not convinced we want to return an error to the client like this. Better to just close off the connection to the client when this happens so client retries. This sort of an error would propagate back through the kv gateway, through http and up to the application. We need a specific retry error of some sort.

Add a TODO here to return an error indicating retry.

File: kv/local_sender.go [hunk 2]
```diff
@@ -104,6 +108,12 @@ func (ls *LocalSender) Send(call *client.Call) {
 		MaxAttempts: 2,
 	}
 	util.RetryWithBackoff(retryOpts, func() (util.RetryStatus, error) {
+		select {
+		case <-ls.closer:
+			call.Reply.Header().SetGoError(util.Errorf("sender is closed"))
```
Comment (spencerkimball) [inline kv/local_sender.go]: Ditto

File: kv/txn_coord_sender.go [hunk 3]
```diff
@@ -536,7 +536,7 @@ func (tc *TxnCoordSender) heartbeat(txn *proto.Transaction, closer chan struct{}
 			// write intents accordingly.
 			if reply.GoError() != nil {
 				log.Warningf("heartbeat to %q:%q failed: %s", txn.Key, txn.ID, reply.GoError())
-			} else if reply.Txn.Status != proto.PENDING {
+			} else if reply.Txn != nil && reply.Txn.Status != proto.PENDING {
```
Comment (spencerkimball) [inline kv/txn_coord_sender.go]: How is error == nil but Txn is nil in some cases?

**Comment by spencerkimball** [comment]
LGTM

File: kv/dist_sender.go (hunk 1 above)
Comment (bdarnell) [inline kv/dist_sender.go]: I was assuming that this is a test-only issue - in production we'd either go crash-only or have a more elaborate shutdown process with a lame-duck period. I'll return a TransactionRetryError instead of a util.Errorf.

File: kv/txn_coord_sender.go (hunk 3 above)
Comment (bdarnell) [inline kv/txn_coord_sender.go]: Looks like an artifact of an earlier version of this commit; I can no longer reproduce the error that led me to make this change.

**Comment by tschottdorf** [comment]
LGTM
