### PR TITLE
sql: fix the pg text representation of tuples/arrays

### LINKED ISSUE #25522: sql: Pretty Printing of Tuples does not match postgres
We do not pretty print tuples the same way that postgres does.

Postgres:
```sql
SELECT (1, 2, 'hello', NULL, NULL), (true, NULL, (false, 6.6, false));
      row      |       row
---------------+------------------
 (1,2,hello,,) | (t,,"(f,6.6,f)")
```

Cockroach:
```sql
SELECT (1, 2, 'hello', NULL, NULL), (true, NULL, (false, 6.6, false));
+-----------------------------+--------------------------------+
| (1, 2, 'hello', NULL, NULL) |   (true, NULL, (false, 6.6,    |
|                             |            false))             |
+-----------------------------+--------------------------------+
| (1,2,'hello',,)             | (true,,(false, 6.6, false))    |
+-----------------------------+--------------------------------+
```

### PR DESCRIPTION
**Pull request by knz**
Forked off #28143.
Fixes #25522.

This patch fixes the conversion of arrays and tuples to text for the
purpose of emitting the arrays/tuples back to a client through pgwire.
This now properly supports nested arrays, arrays containing tuples,
tuples containing arrays, etc. Labels in tuples are never emitted
through pgwire.

Release note (bug fix): CockroachDB supports a wider range of tuple
and array values in query results.

### CODE REVIEW

**Comment by knz** [comment]
Now with tests. I checked that all the combinations format the same as postgres.

**Comment by knz** [comment]
welp I spoke too fast. Fixing.

**Comment by knz** [comment]
There we go. Actually once I understood how this works it's rather regular/simple.

**Comment by knz** [comment]
RFAL

File: pkg/sql/pgwire/types.go [hunk 1]
```diff
@@ -157,40 +153,24 @@ func (b *writeBuffer) writeTextDatum(
...
 			// vectors are serialized as a string of space-separated values.
-			begin, sep, end = "", " ", ""
-		}
-
-		b.variablePutbuf.WriteString(begin)
-		for i, d := range v.Array {
-			if i > 0 {
+			sep := ""
+			// TODO(justin): add a test for nested arrays.
+			for _, d := range v.Array {
```
Comment (justinj) [inline pkg/sql/pgwire/types.go]: might as well just do `if i > 0 { WriteByte(' ') }` ?

File: pkg/sql/sem/tree/format.go [hunk 2]
```diff
@@ -83,8 +83,8 @@ const (
 	FmtSymbolicSubqueries
 
 	// If set, strings will be formatted for being contents of ARRAYs.
-	// Used internally in combination with FmtArrays defined below.
-	fmtWithinArray
+	// Used internally in combination with FmtPgwireText defined below.
+	pgwireFormat
```
Comment (justinj) [inline pkg/sql/sem/tree/format.go]: I'm not especially convinced that this shouldn't be its own method or function (on `Datum`) at this point, rather than a flag on `Format`, but I don't feel particularly strongly.

**Review by justinj — APPROVED** [review]
LGTM

**Review by BramGruneir — DISMISSED** [review]
Looks good overall, but some comments.

> Reviewed 13 of 13 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28151#-:-LIv8GZqAo0QOUF-33Qd:b-d4h8p0)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/logictest/testdata/logic_test/tuple, line 712 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/28151#-LIv4p2g5mJR3LjV3YW_:-LIv4p2hACy1OAFjYLWg:b-fixufi) ([raw file](https://github.com/cockroachdb/cockroach/blob/211795dae6225f368737c188c8272bed0c6228a1/pkg/sql/logictest/testdata/logic_test/tuple#L712)):*
> ```
> ----
> r
> ("(""(1,""""2"""",3)"",""(4,""""5"""")"",""(6)"")","(7,8)","(""9"")")
> ```

This is so ugly.  :(
___
*[pkg/sql/sem/tree/datum.go, line 413 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/28151#-LIv5AhE6eNbEls2dUrx:-LIv5AhFEBccKfb-63Bg:bl6qr75) ([raw file](https://github.com/cockroachdb/cockroach/blob/211795dae6225f368737c188c8272bed0c6228a1/pkg/sql/sem/tree/datum.go#L413)):*
> ```Go
> func (d *DBool) Format(ctx *FmtCtx) {
> 	if ctx.HasFlags(pgwireFormat) {
> 		v := byte('f')
> ```

Why store this value?
```
if bool(*d) {
  ctx.WriteByte('t')
} else {
  ctx.WriteByte('f')
}
return
```
___
*[pkg/sql/sem/tree/datum.go, line 2734 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/28151#-LIv5s15D9TtPqVj-LPd:-LIv5s168fUljjqf0D_n:b-vmfwq0) ([raw file](https://github.com/cockroachdb/cockroach/blob/211795dae6225f368737c188c8272bed0c6228a1/pkg/sql/sem/tree/datum.go#L2734)):*
> ```Go
> 	ctx.WriteByte('(')
> 	comma := ""
> 	for _, v := range d.D {
> ```

Not sure if this is better, but it reads a bit nicer I think.  Also this way you don't set the comma variable each time.
```
for i, v := range d.D {
  if i > 1 {
    ctx.WriteString(", ")
  }
  ctx.FormatNode(v)
}
```

I really want a bool for first and last and I'm kinda surprised that they were not included in golang's range operator.
___
*[pkg/sql/sem/tree/datum.go, line 3026 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/28151#-LIv6Onf4M19eHDUsc_D:-LIv6Onf4M19eHDUsc_E:bgy6b99) ([raw file](https://github.com/cockroachdb/cockroach/blob/211795dae6225f368737c188c8272bed0c6228a1/pkg/sql/sem/tree/datum.go#L3026)):*
> ```Go
> 	}
> 
> 	ctx.WriteString("ARRAY[")
> ```

Here too, 
___
*[pkg/sql/sem/tree/pgwire_encode.go, line 37 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/28151#-LIv6uVN9RpNtgSUVgq6:-LIv6uVN9RpNtgSUVgq7:b2d9olx) ([raw file](https://github.com/cockroachdb/cockroach/blob/211795dae6225f368737c188c8272bed0c6228a1/pkg/sql/sem/tree/pgwire_encode.go#L37)):*
> ```Go
> 	// string printer called pgwireFormatStringInTuple().
> 	ctx.WriteByte('(')
> 	comma := ""
> ```

See my other comments, I'd rather a check on the iteration count than setting comma on each pass.  For all of the commas in this file.
___
*[pkg/sql/sem/tree/pgwire_encode.go, line 57 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/28151#-LIv7t947wOt5XL6oxZg:-LIv7t947wOt5XL6oxZh:b-2jhpy7) ([raw file](https://github.com/cockroachdb/cockroach/blob/211795dae6225f368737c188c8272bed0c6228a1/pkg/sql/sem/tree/pgwire_encode.go#L57)):*
> ```Go
> 
> func pgwireFormatStringInTuple(buf *bytes.Buffer, in string) {
> 	// TODO(knz): to be fully pg-compliant, this function should avoid
> ```

For all of these, this seems pretty easy to do.  Is there a reason to not just use a different buffer then copy from one to the other with or without the double quotes?
___
*[pkg/sql/sem/tree/pgwire_encode.go, line 111 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/28151#-LIv83ag2kZ6Crk4U3pm:-LIv83ag2kZ6Crk4U3pn:b-2guby3) ([raw file](https://github.com/cockroachdb/cockroach/blob/211795dae6225f368737c188c8272bed0c6228a1/pkg/sql/sem/tree/pgwire_encode.go#L111)):*
> ```Go
> 
> func pgwireFormatStringInArray(buf *bytes.Buffer, in string) {
> 	// TODO(knz): to be fully pg-compliant, this function should avoid
> ```

same here
___
*[pkg/util/stringencoding/string_encoding.go, line 86 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/28151#-LIv89Bf8jh5QgTySZaT:-LIv89Bf8jh5QgTySZaU:bvltn3u) ([raw file](https://github.com/cockroachdb/cockroach/blob/211795dae6225f368737c188c8272bed0c6228a1/pkg/util/stringencoding/string_encoding.go#L86)):*
> ```Go
> // EncodeChar is used internally to write out a character from
> // a larger string to a buffer.
> func EncodeChar(buf *bytes.Buffer, entireString string, currentRune rune, currentIdx int) {
> ```

This function looks like it could use a unit test.

**Review by knz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28151)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/logictest/testdata/logic_test/tuple, line 712 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/28151#-LIv4p2g5mJR3LjV3YW_:-LIvG_Sk-efV0Y387WZ-:bnyhr4n) ([raw file](https://github.com/cockroachdb/cockroach/blob/211795dae6225f368737c188c8272bed0c6228a1/pkg/sql/logictest/testdata/logic_test/tuple#L712)):*
<details><summary><i>Previously, BramGruneir (Bram Gruneir) wrote…</i></summary><blockquote>

This is so ugly.  :(
</blockquote></details>

It is ugly but it is also correct. See my other comment below.
___
*[pkg/sql/pgwire/types.go, line 165 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/28151#-LIqDEn4niVzXZkk0IUm-r1-165:-LIvGbwC3rqwV50RdPg8:b-otwob0) ([raw file](https://github.com/cockroachdb/cockroach/blob/211795dae6225f368737c188c8272bed0c6228a1/pkg/sql/pgwire/types.go#L165)):*
<details><summary><i>Previously, justinj (Justin Jaffray) wrote…</i></summary><blockquote>

might as well just do `if i > 0 { WriteByte(' ') }` ?
</blockquote></details>

This way is actually faster / more efficient. Vivek taught me this trick. I'm using it as a general-purpose pattern now.
___
*[pkg/sql/sem/tree/datum.go, line 413 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/28151#-LIv5AhE6eNbEls2dUrx:-LIvGm8u8UyNQYjxxxtO:b-9kqyhp) ([raw file](https://github.com/cockroachdb/cockroach/blob/211795dae6225f368737c188c8272bed0c6228a1/pkg/sql/sem/tree/datum.go#L413)):*
<details><summary><i>Previously, BramGruneir (Bram Gruneir) wrote…</i></summary><blockquote>

Why store this value?
```
if bool(*d) {
  ctx.WriteByte('t')
} else {
  ctx.WriteByte('f')
}
return
```

</blockquote></details>

I don't care either way. Changed.
___
*[pkg/sql/sem/tree/datum.go, line 2734 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/28151#-LIv5s15D9TtPqVj-LPd:-LIvLVR41E4MhgaxsI9A:b-otwob0) ([raw file](https://github.com/cockroachdb/cockroach/blob/211795dae6225f368737c188c8272bed0c6228a1/pkg/sql/sem/tree/datum.go#L2734)):*
<details><summary><i>Previously, BramGruneir (Bram Gruneir) wrote…</i></summary><blockquote>

Not sure if this is better, but it reads a bit nicer I think.  Also this way you don't set the comma variable each time.
```
for i, v := range d.D {
  if i > 1 {
    ctx.WriteString(", ")
  }
  ctx.FormatNode(v)
}
```

I really want a bool for first and last and I'm kinda surprised that they were not included in golang's range operator.
</blockquote></details>

This way is actually faster / more efficient. Vivek taught me this trick. I'm using it as a general-purpose pattern now.
___
*[pkg/sql/sem/tree/datum.go, line 3026 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/28151#-LIv6Onf4M19eHDUsc_D:-LIvLWCp2ED2NNKQfDPV:b-otwob0) ([raw file](https://github.com/cockroachdb/cockroach/blob/211795dae6225f368737c188c8272bed0c6228a1/pkg/sql/sem/tree/datum.go#L3026)):*
<details><summary><i>Previously, BramGruneir (Bram Gruneir) wrote…</i></summary><blockquote>

Here too, 
</blockquote></details>

This way is actually faster / more efficient. Vivek taught me this trick. I'm using it as a general-purpose pattern now.
___
*[pkg/sql/sem/tree/format.go, line 87 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/28151#-LIqDEn4niVzXZkk0IUp-r1-87:-LIvLXZX21zB5rkvixGs:b4h7d6f) ([raw file](https://github.com/cockroachdb/cockroach/blob/211795dae6225f368737c188c8272bed0c6228a1/pkg/sql/sem/tree/format.go#L87)):*
<details><summary><i>Previously, justinj (Justin Jaffray) wrote…</i></summary><blockquote>

I'm not especially convinced that this shouldn't be its own method or function (on `Datum`) at this point, rather than a flag on `Format`, but I don't feel particularly strongly.
</blockquote></details>

This combination still allows up to combine other flags (e.g. anonymize).
___
*[pkg/sql/sem/tree/pgwire_encode.go, line 37 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/28151#-LIv6uVN9RpNtgSUVgq6:-LIvLmiF0ueA1_hEucf3:bvs3kmu) ([raw file](https://github.com/cockroachdb/cockroach/blob/211795dae6225f368737c188c8272bed0c6228a1/pkg/sql/sem/tree/pgwire_encode.go#L37)):*
<details><summary><i>Previously, BramGruneir (Bram Gruneir) wrote…</i></summary><blockquote>

See my other comments, I'd rather a check on the iteration count than setting comma on each pass.  For all of the commas in this file.
</blockquote></details>

ditto my other comment
___
*[pkg/sql/sem/tree/pgwire_encode.go, line 57 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/28151#-LIv7t947wOt5XL6oxZg:-LIvLpk42U78f5fwO2zc:b-he3vx3) ([raw file](https://github.com/cockroachdb/cockroach/blob/211795dae6225f368737c188c8272bed0c6228a1/pkg/sql/sem/tree/pgwire_encode.go#L57)):*
<details><summary><i>Previously, BramGruneir (Bram Gruneir) wrote…</i></summary><blockquote>

For all of these, this seems pretty easy to do.  Is there a reason to not just use a different buffer then copy from one to the other with or without the double quotes?
</blockquote></details>

Because performance. 

@justinj has decided to do it this way originally and reasoned as follows: it is correct to add the double quotes when they are not required. Removing them is only "niceness" to the human user. I'm not revisiting this here -- we can make a separate PR for that.
___
*[pkg/sql/sem/tree/pgwire_encode.go, line 111 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/28151#-LIv83ag2kZ6Crk4U3pm:-LIvM2sZ2ROM_ZF5m_0y:b-7ropln) ([raw file](https://github.com/cockroachdb/cockroach/blob/211795dae6225f368737c188c8272bed0c6228a1/pkg/sql/sem/tree/pgwire_encode.go#L111)):*
<details><summary><i>Previously, BramGruneir (Bram Gruneir) wrote…</i></summary><blockquote>

same here
</blockquote></details>

ditto
___
*[pkg/util/stringencoding/string_encoding.go, line 86 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/28151#-LIv89Bf8jh5QgTySZaT:-LIvM6S53t2swbYkrZG3:brrza5r) ([raw file](https://github.com/cockroachdb/cockroach/blob/211795dae6225f368737c188c8272bed0c6228a1/pkg/util/stringencoding/string_encoding.go#L86)):*
<details><summary><i>Previously, BramGruneir (Bram Gruneir) wrote…</i></summary><blockquote>

This function looks like it could use a unit test.
</blockquote></details>

None of these functions are tested directly in this package. Their unit tests live in `format_test.go` in `pkg/sql/sem/tree` and `pkg/sql/lex`.

**Review by knz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28151)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/logictest/testdata/logic_test/srfs, line 543 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/28151#-LIvPAmb72BljPBPzzG9:-LIvPAmb72BljPBPzzGA:b-6yprys) ([raw file](https://github.com/cockroachdb/cockroach/blob/f052b3b0005cafb75b84cca5ce7444a6f14831d9/pkg/sql/logictest/testdata/logic_test/srfs#L543)):*
> ```
> SELECT ((i.keys).*, 123) FROM (SELECT information_schema._pg_expandarray(ARRAY[3,2,1]) AS keys) AS i
> ----
> ((3, 1),123)
> ```

Jordan just noticed there is a bug here, but unrelated to this PR. Filed as #28203

**Comment by knz** [comment]
PTAL with Justin's offline comments in mind?

**Comment by knz** [comment]
Bram gave a :+1: offline!

thanks bram
