### PR TITLE
roachtest: normalize versions in multitenant-upgrade roachtest

### LINKED ISSUE #95648: roachtest: multitenant-upgrade failed
roachtest.multitenant-upgrade [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/8395662?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/8395662?buildTab=artifacts#/multitenant-upgrade) on master @ [2861a4ee05fac1cc13f87bf00f368a65ea8700dc](https://github.com/cockroachdb/cockroach/commits/2861a4ee05fac1cc13f87bf00f368a65ea8700dc):

```
test artifacts and logs in: /artifacts/multitenant-upgrade/run_1
(assertions.go:264).Fail: 
	Error Trace:	/go/src/github.com/cockroachdb/cockroach/multitenant_upgrade.go:331
	            				/go/src/github.com/cockroachdb/cockroach/multitenant_upgrade.go:168
	            				/go/src/github.com/cockroachdb/cockroach/multitenant_upgrade.go:41
	            				/go/src/github.com/cockroachdb/cockroach/test_runner.go:943
	            				/go/src/github.com/cockroachdb/cockroach/asm_amd64.s:1594
	Error:      	Not equal: 
	            	expected: [][]string{[]string{"22.2"}}
	            	actual  : [][]string{[]string{"1000022.2"}}
	            	
	            	Diff:
	            	--- Expected
	            	+++ Actual
	            	@@ -2,3 +2,3 @@
	            	  ([]string) (len=1) {
	            	-  (string) (len=4) "22.2"
	            	+  (string) (len=9) "1000022.2"
	            	  }
	Test:       	multitenant-upgrade
(require.go:165).Equal: FailNow called
(cluster.go:1937).Run: cluster.RunE: context canceled
(cluster.go:1937).Run: cluster.RunE: context canceled
(cluster.go:1937).Run: cluster.RunE: context canceled
```
<p>Parameters: <code>ROACHTEST_cloud=gce</code>
, <code>ROACHTEST_cpu=4</code>
, <code>ROACHTEST_encrypted=false</code>
, <code>ROACHTEST_fs=ext4</code>
, <code>ROACHTEST_localSSD=true</code>
, <code>ROACHTEST_ssd=0</code>
</p>
<details><summary>Help</summary>
<p>

See: [roachtest README](https://github.com/cockroachdb/cockroach/blob/master/pkg/cmd/roachtest/README.md)

See: [How To Investigate \(internal\)](https://cockroachlabs.atlassian.net/l/c/SSSBr8c7)

</p>
</details>
/cc @cockroachdb/multi-tenant
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*multitenant-upgrade.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)
</sub>

Jira issue: CRDB-23651

### PR DESCRIPTION
**Pull request by healthy-pod**
If the multitenant-upgrade roachtest uses a mix
of release/non-release binaries, it may be using versions
that are technically the same but fail to confirm that because
version in test binaries are incremented by 1M.

This code change fixes the issue by normalizing versions before
comparing them.

Closes https://github.com/cockroachdb/cockroach/issues/95648

Epic: none
Release note: None

### CODE REVIEW

File: pkg/ccl/kvccl/kvtenantccl/tenant_upgrade_test.go [hunk 1]
```diff
@@ -170,14 +169,13 @@ func TestTenantUpgrade(t *testing.T) {
 			"SHOW CLUSTER SETTING version",
 			[][]string{{clusterversion.TestingBinaryVersion.String()}})
 	})
-
 }
 
-// Returns three versions :
-//   - v0 corresponds to the bootstrapped version of the tenant,
-//   - v1, v2 correspond to adjacent releases.
+// Returns two versions v0, v1, v2 which correspond to adjacent releases. v0 will
```
Comment (ajstorm) [inline pkg/ccl/kvccl/kvtenantccl/tenant_upgrade_test.go:174]: Is this change future-proof?  If, for example, we let MinSupportedVerion trail a few releases, would this comment still be correct?  I'd _imagine_ that the test would still do what we'd want it to do, though maybe not if we wanted to test all of the upgrade stages in between v0 and v2.

**Review by ajstorm — CHANGES_REQUESTED** [review]
I left some comments, but I think we're going to need @postamar's eyes on this too.  I know the spirit of what his PR meant to accomplish, but the details are important and subtle.  

@postamar could you please take a look?

**Comment by healthy-pod** [comment]
I agree maybe this is not the right change, maybe we should make the changes to how we test instead? I am looking for suggestions but I will leave 2 points on why I made this change to further explain how this is just a testing issue and not an actual correctness issue:
1) passing a version override using testing knobs or by setting version when creating testing cluster settings is no longer effective because the changes in `createTenantInternal` run after that (ofcourse) and do not check for any overrides. Ideally, `minVersion` and `curVersion` in `createTenantInternal` should have the testing overrides values if an override was passed.
2) checking for version equality between two servers where a server is started with a `crdb_test`-built binary and the other isn't will return different versions even if they are technically the same. I am thinking of adding another version equality function that works around this by incrementing/decrementing one of the versions by `1e6` and returning true if they become equal.

**Comment by healthy-pod** [comment]
When multiple previous releases are supported, my previous code change becomes incorrect. I removed my changes to `tenant_creation` and just made the test ignore the difference between normal versions and versions from test binaries by normalizing them.

Ready for another pass.

**Comment by renatolabs** [comment]
Drive-by comment about upgrade testing here: If we decide to merge this PR as it currently is, I'd suggest adding a note/TODO/issue to revert it at some point. I think we can agree that asserting on specific cluster versions makes for a stronger test (and having or not having the version offset is part of that); more importantly, we want to eventually live in a world where most upgrade roachtests don't have to deal with version offsetting (#92608).

I'd also make a small correction here that version offsetting does not depend on the `crdb_test` build flag; offsetting happens if the binary is not considered a release binary:

https://github.com/cockroachdb/cockroach/blob/3e65660091c0870988978032999acda5a675e5e7/pkg/clusterversion/cockroach_versions.go#L712-L717

**Comment by healthy-pod** [comment]
@renatolabs 
> I'd suggest adding a note/TODO/issue to revert it at some point

What should the trigger of this revert be? Is there something expected after which we won't need to normalize versions?

> I'd also make a small correction here that version offsetting does not depend on the crdb_test build flag; offsetting happens if the binary is not considered a release binary

👍

**Comment by renatolabs** [comment]
> What should the trigger of this revert be?

Once #92608 is closed.

**Review by ajstorm — APPROVED** [review]
I like this change much better than the initial one, but it's not clear to me that it's what we want long-term.  I'd think that the long-term fix here is to ensure that the create tenant code respects the version overrides contained in the testing knobs.  That way we won't need the offset ignoring code.  I'm OK to merge this now if we plan to add the testing knobs fix in a separate PR.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/95904#-:-NNC2Azj5CPkOyjhE432:bpsevqe)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @healthy-pod, @knz, @postamar, @smg260, and @srosenberg)

___
*[`pkg/cmd/roachtest/tests/multitenant_upgrade.go` line 315 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/95904#-NN1xZU15B90gPGr3tY9:-NN1xZU15B90gPGr3tYA:b-yvsrxh) ([raw file](https://github.com/cockroachdb/cockroach/blob/452c5eec2bdf63ef503f9f97a0fc9566b436cc5f/pkg/cmd/roachtest/tests/multitenant_upgrade.go#L315)):*
> ```Go
> ) {
> 	normalizeVersion := func(v roachpb.Version) roachpb.Version {
> 		if (v.Major - clusterversion.DevOffset) >= 0 {
> ```

Nit: it might beeasier to understand this code if it was written as:

`if v.Major > clusterversion.DevOffset {`

**Review by healthy-pod — COMMENTED** [review]
We added the tenant logical version overrides in #94973, this is not related to that. Previously (ie before #94774) we used to set the tenant logical version to be exactly the storage logical version. As in, we read the SLV and set the TLV to that. Now this is not true, it's either the SBV if it's equal to the SLV or otherwise the min version the storage binary can use to create a tenant. What happens here is:

current binary = non-release binary with version offset
predecessor binary = release binary without version offset

- storage starts with `predecessor binary` and its logical version is `predecessor binary` so SLV doesn't have offset
- storage upgrades to `current binary` but doesn't finalize so SLV is still without offset
- storage binary now though is `current binary` which is non-release and when it "calculates" the tenant creation version (instead of what used to happen previously which was just copying SLV) it will be the min supported version of `current binary` which happens to be `predecessor binary` but with offset because current binary is not a release binary even if storage didn't finalize yet.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/95904#-:-NNCk7d1EL-9HFRjqV44:b-cet5ge)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @knz, @postamar, @smg260, and @srosenberg)

**Comment by healthy-pod** [comment]
bors r=ajstorm
