### PR TITLE
roachtest: limit payload sizes in backup-restore/mixed-version

### LINKED ISSUE #120178: roachtest: backup-restore/mixed-version failed
roachtest.backup-restore/mixed-version [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/14316649?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/14316649?buildTab=artifacts#/backup-restore/mixed-version) on release-23.1.17-rc @ [cc68ca88d04a7ca8e92beb51f3dbef6493fe175c](https://github.com/cockroachdb/cockroach/commits/cc68ca88d04a7ca8e92beb51f3dbef6493fe175c):

```
(mixedversion.go:594).Run: mixed-version test failure while running step 28 (run "verify some backups"): mixed-version: error waiting for job to finish: job 950246478697365505 failed with error: importing 50 ranges: addsstable [/Table/186/1/0/0,/Table/186/1/1/0/NULL): split failed while applying backpressure to AddSSTable [/Table/186/1/0/0,/Table/186/1/1/0/NULL) on range r634:/Table/18{3/1/99-6/1/4} [(n2,s2):1, (n3,s3):5, (n1,s1):4, next=6, gen=105]: could not find valid split key
test artifacts and logs in: /artifacts/backup-restore/mixed-version/run_1
```

Parameters:
 - <code>ROACHTEST_arch=amd64</code>
 - <code>ROACHTEST_cloud=gce</code>
 - <code>ROACHTEST_cpu=4</code>
 - <code>ROACHTEST_encrypted=false</code>
 - <code>ROACHTEST_metamorphicBuild=false</code>
 - <code>ROACHTEST_ssd=0</code>
<details><summary>Help</summary>
<p>

See: [roachtest README](https://github.com/cockroachdb/cockroach/blob/master/pkg/cmd/roachtest/README.md)

See: [How To Investigate \(internal\)](https://cockroachlabs.atlassian.net/l/c/SSSBr8c7)

See: [Grafana](https://go.crdb.dev/roachtest-grafana/teamcity-14316649/backup-restore-mixed-version/1710058411100/1710062767642)

</p>
</details>
<details><summary>Same failure on other branches</summary>
<p>

~- #119856 roachtest: backup-restore/mixed-version failed [C-test-failure O-roachtest O-robot T-disaster-recovery branch-release-23.1 release-blocker]~
- #117971 roachtest: backup-restore/mixed-version failed [C-test-failure O-roachtest O-robot P-3 T-disaster-recovery X-noreuse branch-master]
</p>
</details>
/cc @cockroachdb/disaster-recovery
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*backup-restore/mixed-version.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)
</sub>

Jira issue: CRDB-36526

### PR DESCRIPTION
**Pull request by dt**
Previously it could randomly choose to revise only 100 rows with 16kb payloads in every revision. While this usually works when run on 512mb ranges, it can flake when run on 64mb ranges as that many large revisions exceeds the range's capacity.

Release note: none.
Epic: none.

### CODE REVIEW

File: pkg/cmd/roachtest/tests/mixed_version_backup.go [hunk 1]
```diff
@@ -2563,8 +2563,14 @@ func tpccWorkloadCmd(
...
 ) (init *roachtestutil.Command, run *roachtestutil.Command) {
-	bankPayload := bankPossiblePayloadBytes[testRNG.Intn(len(bankPossiblePayloadBytes))]
 	bankRows := bankPossibleRows[testRNG.Intn(len(bankPossibleRows))]
+	possiblePayloads := bankPossiblePayloadBytes
+	// force smaller row counts to use smaller payloads too to avoid making lots
+	// of large revisions of a handful of keys.
+	if bankRows < 1000 {
+		possiblePayloads = []int{16, 64}
+	}
+	bankPayload := possiblePayloads[testRNG.Intn(len(bankPossiblePayloadBytes))]
```
Comment (renatolabs) [inline pkg/cmd/roachtest/tests/mixed_version_backup.go:2573]: `len(possiblePayloads)`

**Review by msbutler — APPROVED** [review]

**Comment by dt** [comment]
TFTR!

bors r+
