### PR TITLE
Fixes #3755

### LINKED ISSUE #3755: Failed tests (11025): TestGossipStorage
The following test appears to have failed:

[#11025](https://circleci.com/gh/cockroachdb/cockroach/11025):

```
I0111 21:35:28.521653 513 gossip/server.go:135  node 1 received [127.0.0.1:54485] from node 3 (1 fresh)
I0111 21:35:28.521797 513 gossip/server.go:209  @1: distantHops: 1 from 2
I0111 21:35:28.522195 513 gossip/simulation/network.go:173  gossip network simulation: total infos sent=19, received=8
I0111 21:35:28.523048 513 gossip/server.go:156  node 1 returned 4 info(s) to node 2
==================
WARNING: DATA RACE
Read by goroutine 47:
  github.com/cockroachdb/cockroach/gossip_test.TestGossipStorage()
      /go/src/github.com/cockroachdb/cockroach/gossip/storage_test.go:73 +0x69d
  testing.tRunner()
      /tmp/workdir/go/src/testing/testing.go:456 +0xdc

Previous write by goroutine 70:
  github.com/cockroachdb/cockroach/gossip_test.(*testStorage).WriteBootstrapInfo()
      /go/src/github.com/cockroachdb/cockroach/gossip/storage_test.go:42 +0x42
  github.com/cockroachdb/cockroach/gossip.(*Gossip).updateNodeAddress()
      /go/src/github.com/cockroachdb/cockroach/gossip/gossip.go:457 +0xb1b
  github.com/cockroachdb/cockroach/gossip.(*Gossip).(github.com/cockroachdb/cockroach/gossip.updateNodeAddress)-fm()
      /go/src/github.com/cockroachdb/cockroach/gossip/gossip.go:191 +0x71
  github.com/cockroachdb/cockroach/gossip.(*infoStore).processCallbacks.func1()
      /go/src/github.com/cockroachdb/cockroach/gossip/infostore.go:247 +0xfe
  github.com/cockroachdb/cockroach/gossip.(*infoStore).processCallbacks.func2()
      /go/src/github.com/cockroachdb/cockroach/gossip/infostore.go:270 +0x166

Goroutine 47 (running) created at:
  testing.RunTests()
      /tmp/workdir/go/src/testing/testing.go:561 +0xaa3
  testing.(*M).Run()
      /tmp/workdir/go/src/testing/testing.go:494 +0xe4
  github.com/cockroachdb/cockroach/util/leaktest.TestMainWithLeakCheck()
      /go/src/github.com/cockroachdb/cockroach/util/leaktest/leaktest.go:37 +0x2e
  github.com/cockroachdb/cockroach/gossip_test.TestMain()
      /go/src/github.com/cockroachdb/cockroach/gossip/main_test.go:34 +0x2e
  main.main()
      github.com/cockroachdb/cockroach/gossip/_test/_testmain.go:112 +0x209

Goroutine 70 (finished) created at:
  github.com/cockroachdb/cockroach/gossip.(*infoStore).processCallbacks()
      /go/src/github.com/cockroachdb/cockroach/gossip/infostore.go:272 +0x56c
  github.com/cockroachdb/cockroach/gossip.(*infoStore).addInfo()
      /go/src/github.com/cockroachdb/cockroach/gossip/infostore.go:189 +0x890
  github.com/cockroachdb/cockroach/gossip.(*infoStore).combine()
      /go/src/github.com/cockroachdb/cockroach/gossip/infostore.go:310 +0x36a
  github.com/cockroachdb/cockroach/gossip.(*client).handleGossip()
      /go/src/github.com/cockroachdb/cockroach/gossip/client.go:158 +0x2d5
  github.com/cockroachdb/cockroach/gossip.(*client).gossip()
      /go/src/github.com/cockroachdb/cockroach/gossip/client.go:244 +0x7d5
--
      /go/src/github.com/cockroachdb/cockroach/gossip/client.go:73 +0x1f6
  github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker.func1()
      /go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:89 +0x5f
==================
==================
WARNING: DATA RACE
Read by goroutine 47:
  github.com/cockroachdb/cockroach/gossip_test.TestGossipStorage()
      /go/src/github.com/cockroachdb/cockroach/gossip/storage_test.go:77 +0x7e2
  testing.tRunner()
      /tmp/workdir/go/src/testing/testing.go:456 +0xdc

Previous write by goroutine 70:
  github.com/cockroachdb/cockroach/gossip_test.(*testStorage).WriteBootstrapInfo()
      /go/src/github.com/cockroachdb/cockroach/gossip/storage_test.go:43 +0xe8
  github.com/cockroachdb/cockroach/gossip.(*Gossip).updateNodeAddress()
      /go/src/github.com/cockroachdb/cockroach/gossip/gossip.go:457 +0xb1b
  github.com/cockroachdb/cockroach/gossip.(*Gossip).(github.com/cockroachdb/cockroach/gossip.updateNodeAddress)-fm()
      /go/src/github.com/cockroachdb/cockroach/gossip/gossip.go:191 +0x71
  github.com/cockroachdb/cockroach/gossip.(*infoStore).processCallbacks.func1()
      /go/src/github.com/cockroachdb/cockroach/gossip/infostore.go:247 +0xfe
  github.com/cockroachdb/cockroach/gossip.(*infoStore).processCallbacks.func2()
      /go/src/github.com/cockroachdb/cockroach/gossip/infostore.go:270 +0x166

Goroutine 47 (running) created at:
  testing.RunTests()
      /tmp/workdir/go/src/testing/testing.go:561 +0xaa3
  testing.(*M).Run()
      /tmp/workdir/go/src/testing/testing.go:494 +0xe4
  github.com/cockroachdb/cockroach/util/leaktest.TestMainWithLeakCheck()
      /go/src/github.com/cockroachdb/cockroach/util/leaktest/leaktest.go:37 +0x2e
  github.com/cockroachdb/cockroach/gossip_test.TestMain()
      /go/src/github.com/cockroachdb/cockroach/gossip/main_test.go:34 +0x2e
  main.main()
      github.com/cockroachdb/cockroach/gossip/_test/_testmain.go:112 +0x209

Goroutine 70 (finished) created at:
  github.com/cockroachdb/cockroach/gossip.(*infoStore).processCallbacks()
      /go/src/github.com/cockroachdb/cockroach/gossip/infostore.go:272 +0x56c
  github.com/cockroachdb/cockroach/gossip.(*infoStore).addInfo()
      /go/src/github.com/cockroachdb/cockroach/gossip/infostore.go:189 +0x890
  github.com/cockroachdb/cockroach/gossip.(*infoStore).combine()
      /go/src/github.com/cockroachdb/cockroach/gossip/infostore.go:310 +0x36a
  github.com/cockroachdb/cockroach/gossip.(*client).handleGossip()
      /go/src/github.com/cockroachdb/cockroach/gossip/client.go:158 +0x2d5
  github.com/cockroachdb/cockroach/gossip.(*client).gossip()
      /go/src/github.com/cockroachdb/cockroach/gossip/client.go:244 +0x7d5
--
W0111 21:35:28.562246 513 rpc/server.go:309  rpc: write response failed: write tcp 127.0.0.1:37657->127.0.0.1:60103: write: connection reset by peer
W0111 21:35:28.562788 513 rpc/server.go:309  rpc: write response failed: write tcp 127.0.0.1:37657->127.0.0.1:60104: write: broken pipe
--- PASS: TestGossipStorage (0.08s)
PASS
Found 2 data race(s)
FAIL	github.com/cockroachdb/cockroach/gossip	1.811s
=== RUN   TestParseResolverSpec
--- PASS: TestParseResolverSpec (0.00s)
=== RUN   TestGetAddress
--- PASS: TestGetAddress (0.00s)
PASS
ok  	github.com/cockroachdb/cockroach/gossip/resolver	1.043s
?   	github.com/cockroachdb/cockroach/gossip/simulation	[no test files]
=== RUN   TestKeySorting
--- PASS: TestKeySorting (0.00s)
=== RUN   TestMakeKey

```
Please assign, take a look and update the issue accordingly.

### PR DESCRIPTION
**Pull request by spencerkimball**
[Review on Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/3787)

### CODE REVIEW

**Comment by tschottdorf** [comment]
LGTM

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/3787#-:-K7rHcHYE4DyguLE1eYr:676834233)*

File: gossip/storage_test.go [hunk 1]
```diff
@@ -28,17 +29,34 @@ import (
 )
 
 type testStorage struct {
+	mu          sync.Mutex
```
Comment (BramGruneir) [inline gossip/storage_test.go]: nit: why not just embed the mutex?  
It just makes the locking/unlocking code look nicer.

**Comment by BramGruneir** [comment]
LGTM
