### PR TITLE
colexecerror: avoid debug.Stack in CatchVectorizedRuntimeError

### LINKED ISSUE #123235: sql/colexecerror: CatchVectorizedRuntimeError uses an expensive debug.Stack call
**Describe the problem**

The usage of `debug.Stack` here is problematic: https://github.com/cockroachdb/cockroach/blob/81569be4aeb61620d2fd51c41b416f7d0986698e/pkg/sql/colexecerror/error.go#L41

During a recent customer outage, we captured this profile: 
image

([Full profile available here.](https://upload.cockroachlabs.com/receive/?thread=0V65-Z35K&packageCode=y7dKw89n2aaSMsuZxpKT4CaMK2y80gTijo0AF5RauJ8#keyCode=_ylkCIwuVDCltzsGHF7NKU65IsBS1R755CGmIZWOXN8))

In the outage, the CRDB behavior was that once CPU usage became high enough, response times started to go up, and execution throughput went down. Notably, the throughput/latency impact is correlated with a large increase in concurrent open transactions.  See the [support ticket](https://cockroachdb.zendesk.com/agent/tickets/21275) for more details.

The main part of the issue here appears to be that the usage of `debug.Stack` causes lock contention due to the system calls that rely on `futex`.

**To Reproduce**

This can be seen with the `admission-control/tpcc-severe-overload` test. See [these notes](https://cockroachlabs.slack.com/archives/C0713QV7XHP/p1714166120803389).

**Expected behavior**

Make the CatchVectorizedRuntimeError less expensive.

There are two main ideas:
- Instead of inspecting the stack trace in the common case, we should be able to first check for specific error types. Note that `ExpectedError` already wraps many errors with a known type: https://github.com/cockroachdb/cockroach/blob/81569be4aeb61620d2fd51c41b416f7d0986698e/pkg/sql/colexecerror/error.go#L202-L204. The related `InternalError` function could do the same.
- In the fallback case where we must inspect the stack, use `runtime.Callers` and `runtime.CallersFrames` instead of `debug.Stack`. It should be much cheaper. (See https://github.com/golang/go/issues/56400 for some discussion on why `debug.Stack` is slower.)

In addition to these two changes, there might be ways to improve the function even more. We can use this issue to track those ideas as well.

@michae2 has some early [benchmark results](https://cockroachlabs.slack.com/archives/C0713QV7XHP/p1714174202399209) from making some of these changes.

Jira issue: CRDB-38252

### PR DESCRIPTION
**Pull request by michae2**
See individual commits for details.

Benchmarks before and after the change:

```
                                                                    │ /tmp/tmp.PrzUglo6GH/bench.catch~3 │    /tmp/tmp.PrzUglo6GH/bench.catch     │
                                                                    │              sec/op               │    sec/op      vs base                 │
CatchVectorizedRuntimeError/noError-12                                                    0.4033n ± ∞ ¹   0.4224n ± ∞ ¹        ~ (p=1.000 n=1) ²
CatchVectorizedRuntimeError/expected-12                                                 40831.00n ± ∞ ¹    98.55n ± ∞ ¹        ~ (p=1.000 n=1) ²
CatchVectorizedRuntimeError/storage-12                                                  41302.00n ± ∞ ¹    99.54n ± ∞ ¹        ~ (p=1.000 n=1) ²
CatchVectorizedRuntimeError/contextCanceled-12                                          40947.00n ± ∞ ¹    99.78n ± ∞ ¹        ~ (p=1.000 n=1) ²
CatchVectorizedRuntimeError/internalWithCode-12                                          41088.0n ± ∞ ¹    474.6n ± ∞ ¹        ~ (p=1.000 n=1) ²
CatchVectorizedRuntimeError/internal-12                                                  41032.0n ± ∞ ¹    943.0n ± ∞ ¹        ~ (p=1.000 n=1) ²
CatchVectorizedRuntimeError/runtime-12                                                    37.094µ ± ∞ ¹    1.091µ ± ∞ ¹        ~ (p=1.000 n=1) ²
SQLCatchVectorizedRuntimeError/conns=12/noError-12                                         43.83µ ± ∞ ¹    43.63µ ± ∞ ¹        ~ (p=1.000 n=1) ²
SQLCatchVectorizedRuntimeError/conns=12/expectedWithCode-12                              1234.24µ ± ∞ ¹    48.27µ ± ∞ ¹        ~ (p=1.000 n=1) ²
SQLCatchVectorizedRuntimeError/conns=12/expectedAssertion-12                             1182.11µ ± ∞ ¹    88.12µ ± ∞ ¹        ~ (p=1.000 n=1) ²
SQLCatchVectorizedRuntimeError/conns=12/internalAssertion-12                             1211.83µ ± ∞ ¹    77.58µ ± ∞ ¹        ~ (p=1.000 n=1) ²
SQLCatchVectorizedRuntimeError/conns=12/internalIndexOutOfRange-12                       1227.76µ ± ∞ ¹    82.40µ ± ∞ ¹        ~ (p=1.000 n=1) ²
SQLCatchVectorizedRuntimeError/conns=12/internalDivideByZero-12                          1224.45µ ± ∞ ¹    81.01µ ± ∞ ¹        ~ (p=1.000 n=1) ²
SQLCatchVectorizedRuntimeError/conns=12/contextCanceled-12                               1265.30µ ± ∞ ¹    44.83µ ± ∞ ¹        ~ (p=1.000 n=1) ²
SQLCatchVectorizedRuntimeError/conns=240/noError-12                                        43.78µ ± ∞ ¹    42.83µ ± ∞ ¹        ~ (p=1.000 n=1) ²
SQLCatchVectorizedRuntimeError/conns=240/expectedWithCode-12                             1210.98µ ± ∞ ¹    48.41µ ± ∞ ¹        ~ (p=1.000 n=1) ²
SQLCatchVectorizedRuntimeError/conns=240/expectedAssertion-12                            1187.21µ ± ∞ ¹    84.70µ ± ∞ ¹        ~ (p=1.000 n=1) ²
SQLCatchVectorizedRuntimeError/conns=240/internalAssertion-12                            1224.62µ ± ∞ ¹    73.85µ ± ∞ ¹        ~ (p=1.000 n=1) ²
SQLCatchVectorizedRuntimeError/conns=240/internalIndexOutOfRange-12                      1224.56µ ± ∞ ¹    81.39µ ± ∞ ¹        ~ (p=1.000 n=1) ²
SQLCatchVectorizedRuntimeError/conns=240/internalDivideByZero-12                         1259.05µ ± ∞ ¹    80.63µ ± ∞ ¹        ~ (p=1.000 n=1) ²
SQLCatchVectorizedRuntimeError/conns=240/contextCanceled-12                              1262.44µ ± ∞ ¹    47.13µ ± ∞ ¹        ~ (p=1.000 n=1) ²
SQLCatchVectorizedRuntimeError/conns=600/noError-12                                        44.98µ ± ∞ ¹    43.53µ ± ∞ ¹        ~ (p=1.000 n=1) ²
SQLCatchVectorizedRuntimeError/conns=600/expectedWithCode-12                             1231.37µ ± ∞ ¹    48.65µ ± ∞ ¹        ~ (p=1.000 n=1) ²
SQLCatchVectorizedRuntimeError/conns=600/expectedAssertion-12                            1201.74µ ± ∞ ¹    97.23µ ± ∞ ¹        ~ (p=1.000 n=1) ²
SQLCatchVectorizedRuntimeError/conns=600/internalAssertion-12                            1249.63µ ± ∞ ¹    80.46µ ± ∞ ¹        ~ (p=1.000 n=1) ²
SQLCatchVectorizedRuntimeError/conns=600/internalIndexOutOfRange-12                      1257.86µ ± ∞ ¹    77.83µ ± ∞ ¹        ~ (p=1.000 n=1) ²
SQLCatchVectorizedRuntimeError/conns=600/internalDivideByZero-12                         1251.79µ ± ∞ ¹    82.22µ ± ∞ ¹        ~ (p=1.000 n=1) ²
SQLCatchVectorizedRuntimeError/conns=600/contextCanceled-12                              1271.82µ ± ∞ ¹    51.19µ ± ∞ ¹        ~ (p=1.000 n=1) ²
geomean                                                                                    243.2µ          13.09µ        -94.62%
¹ need >= 6 samples for confidence interval at level 0.95
² need >= 4 samples to detect a difference at alpha level 0.05

                                                                    │ /tmp/tmp.PrzUglo6GH/bench.catch~3 │    /tmp/tmp.PrzUglo6GH/bench.catch     │
                                                                    │               B/op                │     B/op       vs base                 │
CatchVectorizedRuntimeError/noError-12                                                      0.000 ± ∞ ¹     0.000 ± ∞ ¹        ~ (p=1.000 n=1) ²
CatchVectorizedRuntimeError/expected-12                                                   9834.00 ± ∞ ¹     32.00 ± ∞ ¹        ~ (p=1.000 n=1) ³
CatchVectorizedRuntimeError/storage-12                                                    8880.00 ± ∞ ¹     32.00 ± ∞ ¹        ~ (p=1.000 n=1) ³
CatchVectorizedRuntimeError/contextCanceled-12                                            8840.00 ± ∞ ¹     40.00 ± ∞ ¹        ~ (p=1.000 n=1) ³
CatchVectorizedRuntimeError/internalWithCode-12                                           9.586Ki ± ∞ ¹   1.511Ki ± ∞ ¹        ~ (p=1.000 n=1) ³
CatchVectorizedRuntimeError/internal-12                                                  10.479Ki ± ∞ ¹   2.961Ki ± ∞ ¹        ~ (p=1.000 n=1) ³
CatchVectorizedRuntimeError/runtime-12                                                   10.964Ki ± ∞ ¹   2.656Ki ± ∞ ¹        ~ (p=1.000 n=1) ³
SQLCatchVectorizedRuntimeError/conns=12/noError-12                                        81.75Ki ± ∞ ¹   81.71Ki ± ∞ ¹        ~ (p=1.000 n=1) ³
SQLCatchVectorizedRuntimeError/conns=12/expectedWithCode-12                              143.04Ki ± ∞ ¹   85.28Ki ± ∞ ¹        ~ (p=1.000 n=1) ³
SQLCatchVectorizedRuntimeError/conns=12/expectedAssertion-12                              362.7Ki ± ∞ ¹   304.5Ki ± ∞ ¹        ~ (p=1.000 n=1) ³
SQLCatchVectorizedRuntimeError/conns=12/internalAssertion-12                              304.2Ki ± ∞ ¹   245.3Ki ± ∞ ¹        ~ (p=1.000 n=1) ³
SQLCatchVectorizedRuntimeError/conns=12/internalIndexOutOfRange-12                        313.0Ki ± ∞ ¹   267.2Ki ± ∞ ¹        ~ (p=1.000 n=1) ³
SQLCatchVectorizedRuntimeError/conns=12/internalDivideByZero-12                           308.3Ki ± ∞ ¹   260.7Ki ± ∞ ¹        ~ (p=1.000 n=1) ³
SQLCatchVectorizedRuntimeError/conns=12/contextCanceled-12                               128.96Ki ± ∞ ¹   80.60Ki ± ∞ ¹        ~ (p=1.000 n=1) ³
SQLCatchVectorizedRuntimeError/conns=240/noError-12                                       81.21Ki ± ∞ ¹   81.25Ki ± ∞ ¹        ~ (p=1.000 n=1) ³
SQLCatchVectorizedRuntimeError/conns=240/expectedWithCode-12                             136.02Ki ± ∞ ¹   84.99Ki ± ∞ ¹        ~ (p=1.000 n=1) ³
SQLCatchVectorizedRuntimeError/conns=240/expectedAssertion-12                             362.0Ki ± ∞ ¹   302.9Ki ± ∞ ¹        ~ (p=1.000 n=1) ³
SQLCatchVectorizedRuntimeError/conns=240/internalAssertion-12                             291.4Ki ± ∞ ¹   244.5Ki ± ∞ ¹        ~ (p=1.000 n=1) ³
SQLCatchVectorizedRuntimeError/conns=240/internalIndexOutOfRange-12                       317.1Ki ± ∞ ¹   267.0Ki ± ∞ ¹        ~ (p=1.000 n=1) ³
SQLCatchVectorizedRuntimeError/conns=240/internalDivideByZero-12                          308.4Ki ± ∞ ¹   260.4Ki ± ∞ ¹        ~ (p=1.000 n=1) ³
SQLCatchVectorizedRuntimeError/conns=240/contextCanceled-12                              145.34Ki ± ∞ ¹   81.73Ki ± ∞ ¹        ~ (p=1.000 n=1) ³
SQLCatchVectorizedRuntimeError/conns=600/noError-12                                       81.33Ki ± ∞ ¹   81.24Ki ± ∞ ¹        ~ (p=1.000 n=1) ³
SQLCatchVectorizedRuntimeError/conns=600/expectedWithCode-12                             137.49Ki ± ∞ ¹   85.05Ki ± ∞ ¹        ~ (p=1.000 n=1) ³
SQLCatchVectorizedRuntimeError/conns=600/expectedAssertion-12                             364.7Ki ± ∞ ¹   305.8Ki ± ∞ ¹        ~ (p=1.000 n=1) ³
SQLCatchVectorizedRuntimeError/conns=600/internalAssertion-12                             318.4Ki ± ∞ ¹   244.5Ki ± ∞ ¹        ~ (p=1.000 n=1) ³
SQLCatchVectorizedRuntimeError/conns=600/internalIndexOutOfRange-12                       315.8Ki ± ∞ ¹   265.4Ki ± ∞ ¹        ~ (p=1.000 n=1) ³
SQLCatchVectorizedRuntimeError/conns=600/internalDivideByZero-12                          310.9Ki ± ∞ ¹   260.2Ki ± ∞ ¹        ~ (p=1.000 n=1) ³
SQLCatchVectorizedRuntimeError/conns=600/contextCanceled-12                              133.20Ki ± ∞ ¹   80.53Ki ± ∞ ¹        ~ (p=1.000 n=1) ³
geomean                                                                                               ⁴                  -61.19%               ⁴
¹ need >= 6 samples for confidence interval at level 0.95
² all samples are equal
³ need >= 4 samples to detect a difference at alpha level 0.05
⁴ summaries must be >0 to compute geomean

                                                                    │ /tmp/tmp.PrzUglo6GH/bench.catch~3 │    /tmp/tmp.PrzUglo6GH/bench.catch    │
                                                                    │             allocs/op             │  allocs/op    vs base                 │
CatchVectorizedRuntimeError/noError-12                                                      0.000 ± ∞ ¹    0.000 ± ∞ ¹        ~ (p=1.000 n=1) ²
CatchVectorizedRuntimeError/expected-12                                                    36.000 ± ∞ ¹    3.000 ± ∞ ¹        ~ (p=1.000 n=1) ³
CatchVectorizedRuntimeError/storage-12                                                     11.000 ± ∞ ¹    3.000 ± ∞ ¹        ~ (p=1.000 n=1) ³
CatchVectorizedRuntimeError/contextCanceled-12                                             11.000 ± ∞ ¹    4.000 ± ∞ ¹        ~ (p=1.000 n=1) ³
CatchVectorizedRuntimeError/internalWithCode-12                                             35.00 ± ∞ ¹    37.00 ± ∞ ¹        ~ (p=1.000 n=1) ³
CatchVectorizedRuntimeError/internal-12                                                     46.00 ± ∞ ¹    59.00 ± ∞ ¹        ~ (p=1.000 n=1) ³
CatchVectorizedRuntimeError/runtime-12                                                      58.00 ± ∞ ¹    51.00 ± ∞ ¹        ~ (p=1.000 n=1) ³
SQLCatchVectorizedRuntimeError/conns=12/noError-12                                          838.0 ± ∞ ¹    838.0 ± ∞ ¹        ~ (p=1.000 n=1) ²
SQLCatchVectorizedRuntimeError/conns=12/expectedWithCode-12                                1110.0 ± ∞ ¹    950.0 ± ∞ ¹        ~ (p=1.000 n=1) ³
SQLCatchVectorizedRuntimeError/conns=12/expectedAssertion-12                               1.736k ± ∞ ¹   1.581k ± ∞ ¹        ~ (p=1.000 n=1) ³
SQLCatchVectorizedRuntimeError/conns=12/internalAssertion-12                               1.285k ± ∞ ¹   1.228k ± ∞ ¹        ~ (p=1.000 n=1) ³
SQLCatchVectorizedRuntimeError/conns=12/internalIndexOutOfRange-12                         1.418k ± ∞ ¹   1.425k ± ∞ ¹        ~ (p=1.000 n=1) ³
SQLCatchVectorizedRuntimeError/conns=12/internalDivideByZero-12                            1.413k ± ∞ ¹   1.411k ± ∞ ¹        ~ (p=1.000 n=1) ³
SQLCatchVectorizedRuntimeError/conns=12/contextCanceled-12                                  880.0 ± ∞ ¹    865.0 ± ∞ ¹        ~ (p=1.000 n=1) ³
SQLCatchVectorizedRuntimeError/conns=240/noError-12                                         836.0 ± ∞ ¹    836.0 ± ∞ ¹        ~ (p=1.000 n=1) ²
SQLCatchVectorizedRuntimeError/conns=240/expectedWithCode-12                               1012.0 ± ∞ ¹    949.0 ± ∞ ¹        ~ (p=1.000 n=1) ³
SQLCatchVectorizedRuntimeError/conns=240/expectedAssertion-12                              1.744k ± ∞ ¹   1.572k ± ∞ ¹        ~ (p=1.000 n=1) ³
SQLCatchVectorizedRuntimeError/conns=240/internalAssertion-12                              1.201k ± ∞ ¹   1.228k ± ∞ ¹        ~ (p=1.000 n=1) ³
SQLCatchVectorizedRuntimeError/conns=240/internalIndexOutOfRange-12                        1.518k ± ∞ ¹   1.424k ± ∞ ¹        ~ (p=1.000 n=1) ³
SQLCatchVectorizedRuntimeError/conns=240/internalDivideByZero-12                           1.429k ± ∞ ¹   1.411k ± ∞ ¹        ~ (p=1.000 n=1) ³
SQLCatchVectorizedRuntimeError/conns=240/contextCanceled-12                                 993.0 ± ∞ ¹    865.0 ± ∞ ¹        ~ (p=1.000 n=1) ³
SQLCatchVectorizedRuntimeError/conns=600/noError-12                                         838.0 ± ∞ ¹    837.0 ± ∞ ¹        ~ (p=1.000 n=1) ³
SQLCatchVectorizedRuntimeError/conns=600/expectedWithCode-12                               1038.0 ± ∞ ¹    951.0 ± ∞ ¹        ~ (p=1.000 n=1) ³
SQLCatchVectorizedRuntimeError/conns=600/expectedAssertion-12                              1.782k ± ∞ ¹   1.594k ± ∞ ¹        ~ (p=1.000 n=1) ³
SQLCatchVectorizedRuntimeError/conns=600/internalAssertion-12                              1.471k ± ∞ ¹   1.231k ± ∞ ¹        ~ (p=1.000 n=1) ³
SQLCatchVectorizedRuntimeError/conns=600/internalIndexOutOfRange-12                        1.476k ± ∞ ¹   1.417k ± ∞ ¹        ~ (p=1.000 n=1) ³
SQLCatchVectorizedRuntimeError/conns=600/internalDivideByZero-12                           1.471k ± ∞ ¹   1.411k ± ∞ ¹        ~ (p=1.000 n=1) ³
SQLCatchVectorizedRuntimeError/conns=600/contextCanceled-12                                 960.0 ± ∞ ¹    867.0 ± ∞ ¹        ~ (p=1.000 n=1) ³
geomean                                                                                               ⁴                 -18.86%               ⁴
¹ need >= 6 samples for confidence interval at level 0.95
² all samples are equal
³ need >= 4 samples to detect a difference at alpha level 0.05
⁴ summaries must be >0 to compute geomean
```

Fixes: #123235

Release note (performance improvement): Make error handling in the vectorized execution engine much cheaper. This should help avoid bad metastable regimes perpetuated by statement timeout handling consuming all CPU time, leading to more statement timeouts.

Co-authored-by: Drew Kimball <drewk@cockroachlabs.com>

### CODE REVIEW

**Comment by michae2** [comment]
Benchmark results are here: https://gist.github.com/michae2/4406203dbafc5749ad6a02f8b0ec268e

**Review by DrewKimball — APPROVED** [review]
Nice work! :lgtm:

> Reviewed 6 of 6 files at r1, 1 of 1 files at r2, 1 of 1 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/123277#-:-NwigvJZAKTRyS1GoFbs:b-8ewgme)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @michae2, @rafiss, and @yuzefovich)

___
*[`pkg/sql/colexecerror/error.go` line 74 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/123277#-NwiItxk-YmC29xEEwHK:-NwiItxk-YmC29xEEwHL:b8izdlb) ([raw file](https://github.com/cockroachdb/cockroach/blob/17b9864cad6095633303c3590bb5cea6895b1e5d/pkg/sql/colexecerror/error.go#L74)):*
> whence

Nice :)
___
*[`pkg/sql/colexecerror/error.go` line 130 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/123277#-NwiLbJHBDmTD-CkGTjH:-NwiLbJHBDmTD-CkGTjI:b5rc7n4) ([raw file](https://github.com/cockroachdb/cockroach/blob/17b9864cad6095633303c3590bb5cea6895b1e5d/pkg/sql/colexecerror/error.go#L130)):*
> ```Go
> 			return
> 		}
> 		retErr = err
> ```

Do you think it would be worth it to wrap the error here in an `alreadyCaughtErr` struct or something, so that we only have to inspect the stack once in a set of nested catchers?

**Review by petermattis — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/123277#-:-Nwj3Ypi2EGd9JVMOXY_:bnfp4nl)* status: <span>:shipit:</span> complete! 2 of 0 LGTMs obtained (waiting on @michae2, @rafiss, and @yuzefovich)

___
*[`pkg/sql/colexecerror/error.go` line 111 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/123277#-Nwj2slz9I_289dBBCXP:-Nwj2slz9I_289dBBCXQ:bdyu60a) ([raw file](https://github.com/cockroachdb/cockroach/blob/17b9864cad6095633303c3590bb5cea6895b1e5d/pkg/sql/colexecerror/error.go#L111)):*
> ```Go
> 			))
> 		}
> 		if panicEmittedFrom == "" {
> ```

Is this check and the one above for `!panicLineFound` necessary? If they were omitted we'd call `shouldCatchPanic("")` which would return false and we'd re-throw `panicObj` which should ultimately print the stack anyways. Just wondering what the value of emitting `errors.AssertFailedf` is instead. Do we even have test coverage of this code?

**Review by rafiss — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/123277)* status: <span>:shipit:</span> complete! 2 of 0 LGTMs obtained (waiting on @michae2 and @yuzefovich)

___
*[`pkg/sql/colexecerror/error.go` line 113 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/123277#-Nwjj05y5Jon5LNpulJ0:-Nwjj05y5Jon5LNpulJ1:b-jhoqrs) ([raw file](https://github.com/cockroachdb/cockroach/blob/17b9864cad6095633303c3590bb5cea6895b1e5d/pkg/sql/colexecerror/error.go#L113)):*
> ```Go
> 		if panicEmittedFrom == "" {
> 			stackTrace := string(debug.Stack())
> 			panic(errors.AssertionFailedf(
> ```

i thought `errors.AssertionFailedf` already would include the stack trace: https://github.com/cockroachdb/errors/blob/c1cc1919cf999fb018fcd038852e969e3d5631cc/errutil/assertions.go#L33-L35

(though i see this was the behavior from before your PR. we could check if we have been seeing duplicated stack traces in any error reports.)

**Review by rafiss — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/123277)* status: <span>:shipit:</span> complete! 2 of 0 LGTMs obtained (waiting on @michae2 and @yuzefovich)

___
*[`-- commits` line 2 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/123277#-Nwjk21080o2R0tR7PmE):*
could you include before/after results of this benchmark in the PR description?

helpful incantation:
```
N=10 BENCHTIMEOUT=24h PKG=./pkg/sql/colexecerror BENCHES=BenchmarkCatchVectorizedRuntimeError ./scripts/bench 'old-sha' 'new-sha'
```

**Review by yuzefovich — COMMENTED** [review]
Nice work and speed up! I have some comments.

> Reviewed 6 of 6 files at r1, 1 of 1 files at r2, 1 of 1 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/123277#-:-Nwjr5CTBgPj9epIuhlp:b-x8moke)* status: <span>:shipit:</span> complete! 2 of 0 LGTMs obtained (waiting on @DrewKimball, @michae2, @petermattis, and @rafiss)

___
*[`pkg/sql/colexecerror/error.go` line 109 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/123277#-NwjjLW57tJ9W5lL-jDn:-NwjjLW57tJ9W5lL-jDo:b-a1h5zy) ([raw file](https://github.com/cockroachdb/cockroach/blob/6492c94ec2239975ba6a9ab9bfc0fded1cfd6e25/pkg/sql/colexecerror/error.go#L109)):*
> ```Go
> 	sqlRowPackagesPrefix     = "github.com/cockroachdb/cockroach/pkg/sql/row"
> 	sqlSemPackagesPrefix     = "github.com/cockroachdb/cockroach/pkg/sql/sem"
> 	testSqlColPackagesPrefix = "pkg/sql/col"
> ```

Why do we need this addition (it kinda duplicates `sqlColPackagesPrefix`)? Because we strip the prefix when running tests via bazel? Consider leaving a comment.
___
*[`pkg/sql/colexecerror/error.go` line 78 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/123277#-NwjkTqs9m4bkS4vcXjh:-NwjkTqt01xkb4-6mBk7:bbdmsij) ([raw file](https://github.com/cockroachdb/cockroach/blob/9b1172ae94bfb222b81d3d5f6ac54c3c5d1934b2/pkg/sql/colexecerror/error.go#L78)):*
> ```Go
> 		// engine. We treat a panic from lower in the stack as unrecoverable.
> 
> 		//Find where the panic came from and only proceed if it
> ```

nit: missing spaces after the slashes in the third commit.
___
*[`pkg/sql/colexecerror/error.go` line 243 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/123277#-NwjkrdO1wJXDkFZ5lmf:-NwjkrdP2_8RTGq4z7tN:bdjbqb3) ([raw file](https://github.com/cockroachdb/cockroach/blob/9b1172ae94bfb222b81d3d5f6ac54c3c5d1934b2/pkg/sql/colexecerror/error.go#L243)):*
> ```Go
> 
> func init() {
> 	errors.RegisterWrapperDecoder(errors.GetTypeKey((*internalError)(nil)), decodeInternalError)
> ```

I think we need to register the decoder for both `internalError` and `notInternalError`.
___
*[`pkg/sql/colexecerror/error.go` line 246 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/123277#-NwjlBlc9D3wZWqZSzoH:-NwjlBlc9D3wZWqZSzoI:b-ckovhx) ([raw file](https://github.com/cockroachdb/cockroach/blob/9b1172ae94bfb222b81d3d5f6ac54c3c5d1934b2/pkg/sql/colexecerror/error.go#L246)):*
> ```Go
> }
> 
> // InternalError simply panics with the provided object. It will always be
> ```

nit: this comment needs a minor adjustment.
___
*[`pkg/sql/colexecerror/error.go` line 111 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/123277#-Nwj2slz9I_289dBBCXP:-NwjpUdf3oj46JMsdutr:b-hw9zun) ([raw file](https://github.com/cockroachdb/cockroach/blob/17b9864cad6095633303c3590bb5cea6895b1e5d/pkg/sql/colexecerror/error.go#L111)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

Is this check and the one above for `!panicLineFound` necessary? If they were omitted we'd call `shouldCatchPanic("")` which would return false and we'd re-throw `panicObj` which should ultimately print the stack anyways. Just wondering what the value of emitting `errors.AssertFailedf` is instead. Do we even have test coverage of this code?
</blockquote></details>

These two checks were added in case Go runtime ever changes so that panics are emitted from a different location than `runtime/panic.go`. We do have some sanity checks for this code in `TestCatchVectorizedRuntimeError`, but I don't think it's possible to come up with a test in which one of these two checks doesn't pass.
___
*[`pkg/sql/colexecerror/error.go` line 113 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/123277#-Nwjj05y5Jon5LNpulJ0:-NwjpwI8BKVA0USEv0OR:b-p7x0or) ([raw file](https://github.com/cockroachdb/cockroach/blob/17b9864cad6095633303c3590bb5cea6895b1e5d/pkg/sql/colexecerror/error.go#L113)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

i thought `errors.AssertionFailedf` already would include the stack trace: https://github.com/cockroachdb/errors/blob/c1cc1919cf999fb018fcd038852e969e3d5631cc/errutil/assertions.go#L33-L35

(though i see this was the behavior from before your PR. we could check if we have been seeing duplicated stack traces in any error reports.)
</blockquote></details>

Yes,  good point.`AssertionFailedf` includes the stack trace (that's why below we only call `errors.NewAssertionErrorWithWrappedErrf` when we do want to create an error that would include the stack trace), so I think we can remove two calls to `debug.Stack()` and rely on the assertion's behavior. (Given my comment above, I don't think it's actually possible to hit this code path right now, so there is no way to check for stack trace duplication.)
___
*[`pkg/sql/colexecerror/error.go` line 130 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/123277#-NwiLbJHBDmTD-CkGTjH:-NwjqbsMC8wIHtGMCEiL:b-r4g7vf) ([raw file](https://github.com/cockroachdb/cockroach/blob/17b9864cad6095633303c3590bb5cea6895b1e5d/pkg/sql/colexecerror/error.go#L130)):*
<details><summary><i>Previously, DrewKimball (Drew Kimball) wrote…</i></summary><blockquote>

Do you think it would be worth it to wrap the error here in an `alreadyCaughtErr` struct or something, so that we only have to inspect the stack once in a set of nested catchers?
</blockquote></details>

+1 - this seems like an easy extension of the current improvement. IIUC multiple nested catchers significantly exacerbated the problem we saw in the customer environment, and although we now have fast-paths for majority of errors, it'd be great to only inspect the stack once, regardless of the number of catches in it.
___
*[`pkg/sql/sem/builtins/builtins.go` line 5645 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/123277#-NwjhqRk2MYyKPz4Fp4S:-NwjhqRk2MYyKPz4Fp4T:b-pym4q9) ([raw file](https://github.com/cockroachdb/cockroach/blob/6492c94ec2239975ba6a9ab9bfc0fded1cfd6e25/pkg/sql/sem/builtins/builtins.go#L5645)):*
> ```Go
> 	),
> 
> 	"crdb_internal.force_vectorized_assertion_error": makeBuiltin(
> ```

nit: rather than introducing a new builtin, should we introduce an overload to existing `crdb_internal.force_panic` builtin where an optional second boolean argument would indicate whether the panic should be catchable by vectorized engine or not?
___
*[`pkg/sql/colexecerror/main_test.go` line 42 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/123277#-NwjiSJC5kl_0lH_oupM:-NwjiSJC5kl_0lH_oupN:bfmmld8) ([raw file](https://github.com/cockroachdb/cockroach/blob/6492c94ec2239975ba6a9ab9bfc0fded1cfd6e25/pkg/sql/colexecerror/main_test.go#L42)):*
> ```Go
> var (
> 	// testAllocator is an Allocator with an unlimited budget for use in tests.
> 	testAllocator     *colmem.Allocator
> ```

nit: we don't need most of the initialization in this file. I think it can be as short as
```
func TestMain(m *testing.M) {
	securityassets.SetLoader(securitytest.EmbeddedAssets)
	randutil.SeedForTests()
	serverutils.InitTestServerFactory(server.TestServerFactory)

	os.Exit(m.Run())
}
```

**Review by petermattis — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/123277)* status: <span>:shipit:</span> complete! 2 of 0 LGTMs obtained (waiting on @DrewKimball, @michae2, @rafiss, and @yuzefovich)

___
*[`pkg/sql/colexecerror/error.go` line 111 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/123277#-Nwj2slz9I_289dBBCXP:-NwjsGcNAvXtLtgborQ3:b-8a0tab) ([raw file](https://github.com/cockroachdb/cockroach/blob/17b9864cad6095633303c3590bb5cea6895b1e5d/pkg/sql/colexecerror/error.go#L111)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

These two checks were added in case Go runtime ever changes so that panics are emitted from a different location than `runtime/panic.go`. We do have some sanity checks for this code in `TestCatchVectorizedRuntimeError`, but I don't think it's possible to come up with a test in which one of these two checks doesn't pass.
</blockquote></details>

Ah, got it. I'd suggest a small refactor to this code. Pull the extraction of `panicEmittedFrom` into a function, and call that from a test and assert that it always finds the location. Right now you essentially have the testing in the regular code path which feels a bit strange.

**Review by yuzefovich — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/123277)* status: <span>:shipit:</span> complete! 2 of 0 LGTMs obtained (waiting on @DrewKimball, @michae2, @petermattis, and @rafiss)

___
*[`pkg/sql/colexecerror/error.go` line 111 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/123277#-Nwj2slz9I_289dBBCXP:-NwjsF4S0n6kr1RjRL-p:b-w55bob) ([raw file](https://github.com/cockroachdb/cockroach/blob/17b9864cad6095633303c3590bb5cea6895b1e5d/pkg/sql/colexecerror/error.go#L111)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

These two checks were added in case Go runtime ever changes so that panics are emitted from a different location than `runtime/panic.go`. We do have some sanity checks for this code in `TestCatchVectorizedRuntimeError`, but I don't think it's possible to come up with a test in which one of these two checks doesn't pass.
</blockquote></details>

Thinking a bit more about this, I agree that these two checks don't add that much value, so we could remove them. If callsite for panics in Go runtime ever changes, we'll easily catch the change via CI. So I'd be in favor of removing these two `if`s and simply re-panicking whenever we don't find the panic line in the stack trace.

**Review by mgartner — APPROVED** [review]
:lgtm:

> Reviewed 6 of 6 files at r1, 1 of 1 files at r2, 1 of 1 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/123277#-:-NwjuKKJ0ZTpQwzz_K0q:bnfp4nl)* status: <span>:shipit:</span> complete! 3 of 0 LGTMs obtained (waiting on @DrewKimball, @michae2, @petermattis, and @rafiss)

___
*[`pkg/sql/colexecerror/error.go` line 48 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/123277#-Nwjsmd39mfZH5SQIhI8:-Nwjsmd39mfZH5SQIhI9:bgto9hl) ([raw file](https://github.com/cockroachdb/cockroach/blob/2917eecda0b954cef30c803348db8d97656430bb/pkg/sql/colexecerror/error.go#L48)):*
> ```Go
> 			// without a stacktrace, sentry report, or "internal error" designation.
> 			var nie *notInternalError
> 			if errors.As(err, &se) || errors.As(err, &nie) {
> ```

nit: Why use `errors.As` here instead of `errors.Is` or `errors.IsAny`?

File: pkg/sql/colexecerror/error_test.go [hunk 1]
```diff
@@ -74,3 +83,149 @@ func TestNonCatchablePanicIsNotCaught(t *testing.T) {
...
+
+	for _, parallelism := range []int{1, 20, 50} {
+		numConns := runtime.GOMAXPROCS(0) * parallelism
+		b.Run(fmt.Sprintf("conns=%d", numConns), func(b *testing.B) {
+			for _, tc := range cases {
+				stmt := fmt.Sprintf(sqlFmt, tc.builtin)
+				b.Run(tc.name, func(b *testing.B) {
+					// Create as many warm connections as we will need for the benchmark.
+					conns := make(chan *gosql.DB, numConns)
+					for range numConns {
```
Comment (michae2) [inline pkg/sql/colexecerror/error_test.go:203]: Note to self: this will make backport difficult.

**Review by rafiss — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/123277)* status: <span>:shipit:</span> complete! 3 of 0 LGTMs obtained (waiting on @DrewKimball, @mgartner, @michae2, and @petermattis)

___
*[`pkg/sql/colexecerror/error.go` line 48 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/123277#-Nwjsmd39mfZH5SQIhI8:-NwkNtJ5Dwlskmyb23jb:bty2n2i) ([raw file](https://github.com/cockroachdb/cockroach/blob/2917eecda0b954cef30c803348db8d97656430bb/pkg/sql/colexecerror/error.go#L48)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

nit: Why use `errors.As` here instead of `errors.Is` or `errors.IsAny`?
</blockquote></details>

`errors.Is[Any]` requires the error (or any error in the cause chain) to exactly equal a reference error.

`errors.As` checks if the error (or any error in the cause chain) is assignable to the value pointed at by the target. 

in this case, since there is no "singleton" `notInternalError`, we need to use `As`.

**Comment by mgartner** [comment]
*[`pkg/sql/colexecerror/error.go` line 48 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/123277#-Nwjsmd39mfZH5SQIhI8:-NwlGkBdCNwO1qa7LWSb:b3tjets) ([raw file](https://github.com/cockroachdb/cockroach/blob/2917eecda0b954cef30c803348db8d97656430bb/pkg/sql/colexecerror/error.go#L48)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

`errors.Is[Any]` requires the error (or any error in the cause chain) to exactly equal a reference error.

`errors.As` checks if the error (or any error in the cause chain) is assignable to the value pointed at by the target. 

in this case, since there is no "singleton" `notInternalError`, we need to use `As`.
</blockquote></details>

Thanks for the explanation Rafi!

**Review by michae2 — COMMENTED** [review]
Thanks for all the comments! I will push an update tonight.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/123277#-:-NwlX3ZB6oPSBZMsQ3yG:byw7fe6)* status: <span>:shipit:</span> complete! 3 of 0 LGTMs obtained (waiting on @DrewKimball, @petermattis, and @rafiss)

___
*[`pkg/sql/colexecerror/error.go` line 130 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/123277#-NwiLbJHBDmTD-CkGTjH:-NwlWTfqCI_5TVi9rwAj:b-8c1oq1) ([raw file](https://github.com/cockroachdb/cockroach/blob/17b9864cad6095633303c3590bb5cea6895b1e5d/pkg/sql/colexecerror/error.go#L130)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

+1 - this seems like an easy extension of the current improvement. IIUC multiple nested catchers significantly exacerbated the problem we saw in the customer environment, and although we now have fast-paths for majority of errors, it'd be great to only inspect the stack once, regardless of the number of catches in it.
</blockquote></details>

Nice idea! @yuzefovich I think I might reuse `notInternalError` for this, do you see any problems with that?

**Review by yuzefovich — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/123277)* status: <span>:shipit:</span> complete! 3 of 0 LGTMs obtained (waiting on @DrewKimball, @michae2, @petermattis, and @rafiss)

___
*[`pkg/sql/colexecerror/error.go` line 130 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/123277#-NwiLbJHBDmTD-CkGTjH:-NwlXbMe3x-ABJooaXwB:b-kwcjgq) ([raw file](https://github.com/cockroachdb/cockroach/blob/17b9864cad6095633303c3590bb5cea6895b1e5d/pkg/sql/colexecerror/error.go#L130)):*
<details><summary><i>Previously, michae2 (Michael Erickson) wrote…</i></summary><blockquote>

Nice idea! @yuzefovich I think I might reuse `notInternalError` for this, do you see any problems with that?
</blockquote></details>

Reusing `notInternalError` would lead to a behavior change. Namely, we now won't be able to tell the difference between an expected error within vectorized engine (that should propagated as an error, without stack trace) and an unexpected error outside of the vectorized engine (which shouldn't be caught and should be propagated via panic further up). I'd introduce a new error type like Drew suggested.

**Review by michae2 — COMMENTED** [review]
TFTRs!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/123277#-:-NwnTpaw8QQDuMq-o3WL:bz5mair)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (and 3 stale) (waiting on @DrewKimball, @mgartner, @petermattis, @rafiss, and @yuzefovich)

___
*[`-- commits` line 2 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/123277#-Nwjk21080o2R0tR7PmE):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

could you include before/after results of this benchmark in the PR description?

helpful incantation:
```
N=10 BENCHTIMEOUT=24h PKG=./pkg/sql/colexecerror BENCHES=BenchmarkCatchVectorizedRuntimeError ./scripts/bench 'old-sha' 'new-sha'
```
</blockquote></details>

I'll kick off a run on a gceworker and share tomorrow.
___
*[`pkg/sql/colexecerror/error.go` line 109 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/123277#-NwjjLW57tJ9W5lL-jDn:-NwnT0cs9SuzXp9KsCfn:b-3bktpq) ([raw file](https://github.com/cockroachdb/cockroach/blob/6492c94ec2239975ba6a9ab9bfc0fded1cfd6e25/pkg/sql/colexecerror/error.go#L109)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

Why do we need this addition (it kinda duplicates `sqlColPackagesPrefix`)? Because we strip the prefix when running tests via bazel? Consider leaving a comment.
</blockquote></details>

Yes, exactly. Added a comment and I asked about it in [slack](https://cockroachlabs.slack.com/archives/C019A8NANH0/p1714544109760939).
___
*[`pkg/sql/colexecerror/error.go` line 78 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/123277#-NwjkTqs9m4bkS4vcXjh:-NwnSGA1A_4HZw5GFzOz:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/9b1172ae94bfb222b81d3d5f6ac54c3c5d1934b2/pkg/sql/colexecerror/error.go#L78)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

nit: missing spaces after the slashes in the third commit.
</blockquote></details>

Done.
___
*[`pkg/sql/colexecerror/error.go` line 243 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/123277#-NwjkrdO1wJXDkFZ5lmf:-NwnTCVH7MOvrLBw8o_5:bvc3keb) ([raw file](https://github.com/cockroachdb/cockroach/blob/9b1172ae94bfb222b81d3d5f6ac54c3c5d1934b2/pkg/sql/colexecerror/error.go#L243)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

I think we need to register the decoder for both `internalError` and `notInternalError`.
</blockquote></details>

Oh, good catch! Done.
___
*[`pkg/sql/colexecerror/error.go` line 246 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/123277#-NwjlBlc9D3wZWqZSzoH:-NwnTFkd5x7YoD4JEmBq:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/9b1172ae94bfb222b81d3d5f6ac54c3c5d1934b2/pkg/sql/colexecerror/error.go#L246)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

nit: this comment needs a minor adjustment.
</blockquote></details>

Done.
___
*[`pkg/sql/colexecerror/error.go` line 0 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/123277#gh-1584846764:-NwnSCJg31wQ4a16eZSE:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/17b9864cad6095633303c3590bb5cea6895b1e5d/pkg/sql/colexecerror/error.go#L0)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

*(Reviewable was [unable](https://github.com/Reviewable/Reviewable/issues/14) to map [this GitHub inline comment thread](https://github.com/cockroachdb/cockroach/pull/123277#discussion_r1584846764) to the right spot — sorry!)*

super nit: the comment should be updated so mention the error wrapping instead of "simply panicking."
</blockquote></details>

Done.
___
*[`pkg/sql/colexecerror/error.go` line 111 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/123277#-Nwj2slz9I_289dBBCXP:-NwnSHGG2rD5FGuTnUkQ:bq7x8hi) ([raw file](https://github.com/cockroachdb/cockroach/blob/17b9864cad6095633303c3590bb5cea6895b1e5d/pkg/sql/colexecerror/error.go#L111)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

Thinking a bit more about this, I agree that these two checks don't add that much value, so we could remove them. If callsite for panics in Go runtime ever changes, we'll easily catch the change via CI. So I'd be in favor of removing these two `if`s and simply re-panicking whenever we don't find the panic line in the stack trace.
</blockquote></details>

I removed these two checks.
___
*[`pkg/sql/colexecerror/error.go` line 113 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/123277#-Nwjj05y5Jon5LNpulJ0:-NwnSJC99fHRjZEeD1Ax:bk4qg31) ([raw file](https://github.com/cockroachdb/cockroach/blob/17b9864cad6095633303c3590bb5cea6895b1e5d/pkg/sql/colexecerror/error.go#L113)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

Yes,  good point.`AssertionFailedf` includes the stack trace (that's why below we only call `errors.NewAssertionErrorWithWrappedErrf` when we do want to create an error that would include the stack trace), so I think we can remove two calls to `debug.Stack()` and rely on the assertion's behavior. (Given my comment above, I don't think it's actually possible to hit this code path right now, so there is no way to check for stack trace duplication.)
</blockquote></details>

Removed these two checks.
___
*[`pkg/sql/colexecerror/error.go` line 130 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/123277#-NwiLbJHBDmTD-CkGTjH:-NwnSMoTCeyTVJHLqv56:butt199) ([raw file](https://github.com/cockroachdb/cockroach/blob/17b9864cad6095633303c3590bb5cea6895b1e5d/pkg/sql/colexecerror/error.go#L130)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

Reusing `notInternalError` would lead to a behavior change. Namely, we now won't be able to tell the difference between an expected error within vectorized engine (that should propagated as an error, without stack trace) and an unexpected error outside of the vectorized engine (which shouldn't be caught and should be propagated via panic further up). I'd introduce a new error type like Drew suggested.
</blockquote></details>

I tried this out, but strangely it seemed to make things slower. My guess is that we're mostly re-wrapping with materializers and columnarizers, and it looks like we already wrap with `notInternalError` in columnarizer: https://github.com/cockroachdb/cockroach/blob/af3173a899e16af30d2ca9489d8c2c926c410121/pkg/sql/colexec/columnarizer.go#L243
___
*[`pkg/sql/sem/builtins/builtins.go` line 5645 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/123277#-NwjhqRk2MYyKPz4Fp4S:-NwnTH6l9iSmCikooHUa:but9k0e) ([raw file](https://github.com/cockroachdb/cockroach/blob/6492c94ec2239975ba6a9ab9bfc0fded1cfd6e25/pkg/sql/sem/builtins/builtins.go#L5645)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

nit: rather than introducing a new builtin, should we introduce an overload to existing `crdb_internal.force_panic` builtin where an optional second boolean argument would indicate whether the panic should be catchable by vectorized engine or not?
</blockquote></details>

Good call. I added an override with a couple more options.
___
*[`pkg/sql/colexecerror/error_test.go` line 203 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/123277#gh-1585218263:-NwnTPcg0_59F416diAX:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/17b9864cad6095633303c3590bb5cea6895b1e5d/pkg/sql/colexecerror/error_test.go#L203)):*
<details><summary><i>Previously, michae2 (Michael Erickson) wrote…</i></summary><blockquote>

Note to self: this will make backport difficult.
</blockquote></details>

Done.
___
*[`pkg/sql/colexecerror/main_test.go` line 42 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/123277#-NwjiSJC5kl_0lH_oupM:-NwnTRNfB63fD5kNP9Dx:be7qhbd) ([raw file](https://github.com/cockroachdb/cockroach/blob/6492c94ec2239975ba6a9ab9bfc0fded1cfd6e25/pkg/sql/colexecerror/main_test.go#L42)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

nit: we don't need most of the initialization in this file. I think it can be as short as
```
func TestMain(m *testing.M) {
	securityassets.SetLoader(securitytest.EmbeddedAssets)
	randutil.SeedForTests()
	serverutils.InitTestServerFactory(server.TestServerFactory)

	os.Exit(m.Run())
}
```
</blockquote></details>

Thank you! Done.

**Review by yuzefovich — COMMENTED** [review]
> Reviewed 6 of 6 files at r5, 1 of 1 files at r6, 1 of 1 files at r7, 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/123277)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (and 3 stale) (waiting on @DrewKimball, @michae2, @petermattis, and @rafiss)

___
*[`pkg/sql/colexecerror/error.go` line 130 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/123277#-NwiLbJHBDmTD-CkGTjH:-NwoqoQI0pBbgKAgxqAL:b3903n7) ([raw file](https://github.com/cockroachdb/cockroach/blob/17b9864cad6095633303c3590bb5cea6895b1e5d/pkg/sql/colexecerror/error.go#L130)):*
<details><summary><i>Previously, michae2 (Michael Erickson) wrote…</i></summary><blockquote>

I tried this out, but strangely it seemed to make things slower. My guess is that we're mostly re-wrapping with materializers and columnarizers, and it looks like we already wrap with `notInternalError` in columnarizer: https://github.com/cockroachdb/cockroach/blob/af3173a899e16af30d2ca9489d8c2c926c410121/pkg/sql/colexec/columnarizer.go#L243
</blockquote></details>

Hm, we might be thinking about this differently. The idea is that in the fall back case, when we had to look at the stack via `runtime.CallersFrames` (because the panic should be caught by vec engine but wasn't produced via one of `colexecerror.*Error` calls), we will wrap the error with a special marker `alreadyCaughtError` so that the next catcher up the stack didn't have to inspect the stack (i.e. we would add another special error type to the hot path at the top of the method). This shouldn't have any influence for columnarizer-materializer pair since they already use `colexecerror` methods that wrap errors with different markers. Does this match your thinking?

That said, this would be an improvement to an edge case, so I'd be ok with leaving a TODO for it.

**Review by michae2 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/123277)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (and 3 stale) (waiting on @DrewKimball, @petermattis, and @rafiss)

___
*[`pkg/sql/colexecerror/error.go` line 130 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/123277#-NwiLbJHBDmTD-CkGTjH:-Nwp4L2l8gGeeFCQUNz7:bnkj9fh) ([raw file](https://github.com/cockroachdb/cockroach/blob/17b9864cad6095633303c3590bb5cea6895b1e5d/pkg/sql/colexecerror/error.go#L130)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

Hm, we might be thinking about this differently. The idea is that in the fall back case, when we had to look at the stack via `runtime.CallersFrames` (because the panic should be caught by vec engine but wasn't produced via one of `colexecerror.*Error` calls), we will wrap the error with a special marker `alreadyCaughtError` so that the next catcher up the stack didn't have to inspect the stack (i.e. we would add another special error type to the hot path at the top of the method). This shouldn't have any influence for columnarizer-materializer pair since they already use `colexecerror` methods that wrap errors with different markers. Does this match your thinking?

That said, this would be an improvement to an edge case, so I'd be ok with leaving a TODO for it.
</blockquote></details>

Here's what I tried: https://gist.github.com/michae2/79a2549ef925f04ef513925e46ba6e8a

**Review by yuzefovich — APPROVED** [review]
:lgtm: :rocket: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/123277#-:-Nwp6Dx91zzKMtBPdAIX:byykejp)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (and 3 stale) (waiting on @DrewKimball, @michae2, @petermattis, and @rafiss)

___
*[`pkg/sql/colexecerror/error.go` line 130 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/123277#-NwiLbJHBDmTD-CkGTjH:-Nwp5ias-SIP2u-7jzWU:b2fmry) ([raw file](https://github.com/cockroachdb/cockroach/blob/17b9864cad6095633303c3590bb5cea6895b1e5d/pkg/sql/colexecerror/error.go#L130)):*
<details><summary><i>Previously, michae2 (Michael Erickson) wrote…</i></summary><blockquote>

Here's what I tried: https://gist.github.com/michae2/79a2549ef925f04ef513925e46ba6e8a
</blockquote></details>

Huh, that's what I had in mind. Hm, I guess it's expected that this will be a bit slower if we only have one catcher in the stack trace (due to additional overhead of another `errors.As` traversal). I don't think this is important to optimize though, so let's discard this idea.

**Comment by michae2** [comment]
I've added benchmark results to the PR description, collected using:

```
N=1 BENCHTIMEOUT=24h PKG=./pkg/sql/colexecerror BENCHES=CatchVectorizedRuntimeError ./scripts/bench catch~3 catch
```

(I had to run with N=1 to avoid exhausting ports on my gceworker, so the benchstat output is missing the nice comparison, but the absolute numbers are accurate.)

**Comment by michae2** [comment]
Thanks for the reviews!

bors r=DrewKimball,petermattis,mgartner,yuzefovich

**Comment by yuzefovich** [comment]
There are some CI failures on this PR that will fail to merge.

bors r-

**Comment by yuzefovich** [comment]
For posterity, here are the number I got using `scripts/bench` with the old `benchstat` on the gceworker (comparing 1st commit against 4th):
```
name                                                             old time/op    new time/op    delta
CatchVectorizedRuntimeError/noError                                4.75ns ± 0%    4.75ns ± 0%     ~     (p=0.752 n=10+10)
CatchVectorizedRuntimeError/expected                               18.9µs ± 1%     0.5µs ± 0%  -97.47%  (p=0.000 n=10+10)
CatchVectorizedRuntimeError/storage                                16.1µs ± 2%     0.4µs ± 0%  -97.71%  (p=0.000 n=10+10)
CatchVectorizedRuntimeError/contextCanceled                        16.2µs ± 1%     0.6µs ± 0%  -96.17%  (p=0.000 n=10+9)
CatchVectorizedRuntimeError/internalWithCode                       18.9µs ± 1%     4.4µs ± 1%  -76.55%  (p=0.000 n=9+10)
CatchVectorizedRuntimeError/internal                               23.1µs ± 1%     8.8µs ± 1%  -61.77%  (p=0.000 n=10+10)
CatchVectorizedRuntimeError/runtime                                24.3µs ± 1%    10.4µs ± 1%  -57.29%  (p=0.000 n=10+9)
SQLCatchVectorizedRuntimeError/conns=1/noError                      466µs ± 4%     466µs ± 6%     ~     (p=0.739 n=10+10)
SQLCatchVectorizedRuntimeError/conns=1/expectedWithCode             967µs ± 2%     516µs ± 3%  -46.70%  (p=0.000 n=10+10)
SQLCatchVectorizedRuntimeError/conns=1/expectedAssertion           1.37ms ± 3%    0.89ms ± 2%  -34.78%  (p=0.000 n=10+10)
SQLCatchVectorizedRuntimeError/conns=1/internalAssertion           1.21ms ± 4%    0.79ms ± 3%  -35.12%  (p=0.000 n=9+9)
SQLCatchVectorizedRuntimeError/conns=1/internalIndexOutOfRange     1.27ms ± 3%    0.85ms ± 4%  -33.45%  (p=0.000 n=10+10)
SQLCatchVectorizedRuntimeError/conns=1/internalDivideByZero        1.24ms ± 2%    0.83ms ± 2%  -33.64%  (p=0.000 n=10+10)
SQLCatchVectorizedRuntimeError/conns=1/contextCanceled              905µs ± 7%     484µs ± 4%  -46.53%  (p=0.000 n=10+10)
SQLCatchVectorizedRuntimeError/conns=20/noError                     457µs ± 5%     466µs ± 6%     ~     (p=0.278 n=10+9)
SQLCatchVectorizedRuntimeError/conns=20/expectedWithCode            989µs ± 8%     546µs ± 4%  -44.82%  (p=0.000 n=10+10)
SQLCatchVectorizedRuntimeError/conns=20/expectedAssertion          1.41ms ± 5%    0.91ms ±13%  -35.48%  (p=0.000 n=10+10)
SQLCatchVectorizedRuntimeError/conns=20/internalAssertion          1.34ms ± 4%    0.82ms ± 4%  -38.89%  (p=0.000 n=10+10)
SQLCatchVectorizedRuntimeError/conns=20/internalIndexOutOfRange    1.31ms ±12%    0.94ms ± 3%  -27.96%  (p=0.000 n=10+10)
SQLCatchVectorizedRuntimeError/conns=20/internalDivideByZero       1.13ms ± 1%    0.94ms ± 3%  -17.17%  (p=0.000 n=9+10)
SQLCatchVectorizedRuntimeError/conns=20/contextCanceled             878µs ± 2%     456µs ± 5%  -48.04%  (p=0.000 n=9+10)
SQLCatchVectorizedRuntimeError/conns=50/noError                     443µs ± 6%     434µs ± 5%     ~     (p=0.247 n=10+10)
SQLCatchVectorizedRuntimeError/conns=50/expectedWithCode            932µs ± 2%     486µs ± 1%  -47.92%  (p=0.000 n=10+9)
SQLCatchVectorizedRuntimeError/conns=50/expectedAssertion          1.25ms ± 2%    0.77ms ± 5%  -38.32%  (p=0.000 n=9+10)
SQLCatchVectorizedRuntimeError/conns=50/internalAssertion          1.17ms ± 6%    0.70ms ± 4%  -40.14%  (p=0.000 n=10+10)
SQLCatchVectorizedRuntimeError/conns=50/internalIndexOutOfRange    1.24ms ± 8%    0.76ms ± 2%  -38.61%  (p=0.000 n=10+8)
SQLCatchVectorizedRuntimeError/conns=50/internalDivideByZero       1.21ms ± 4%    0.77ms ± 2%  -36.86%  (p=0.000 n=9+9)
SQLCatchVectorizedRuntimeError/conns=50/contextCanceled             943µs ± 7%     485µs ± 6%  -48.51%  (p=0.000 n=9+10)

name                                                             old alloc/op   new alloc/op   delta
CatchVectorizedRuntimeError/noError                                 0.00B          0.00B          ~     (all equal)
CatchVectorizedRuntimeError/expected                               9.83kB ± 0%    0.03kB ± 0%  -99.67%  (p=0.000 n=10+10)
CatchVectorizedRuntimeError/storage                                8.88kB ± 0%    0.03kB ± 0%  -99.64%  (p=0.000 n=10+10)
CatchVectorizedRuntimeError/contextCanceled                        8.84kB ± 0%    0.04kB ± 0%  -99.55%  (p=0.000 n=10+10)
CatchVectorizedRuntimeError/internalWithCode                       9.82kB ± 0%    1.54kB ± 0%  -84.27%  (p=0.000 n=10+10)
CatchVectorizedRuntimeError/internal                               10.7kB ± 0%     3.0kB ± 0%  -71.81%  (p=0.000 n=10+10)
CatchVectorizedRuntimeError/runtime                                11.2kB ± 0%     2.7kB ± 0%  -75.77%  (p=0.000 n=10+10)
SQLCatchVectorizedRuntimeError/conns=1/noError                     84.3kB ± 4%    85.1kB ± 5%     ~     (p=0.549 n=9+10)
SQLCatchVectorizedRuntimeError/conns=1/expectedWithCode             137kB ± 1%      87kB ± 1%  -35.93%  (p=0.000 n=8+8)
SQLCatchVectorizedRuntimeError/conns=1/expectedAssertion            374kB ± 4%     311kB ± 0%  -17.05%  (p=0.000 n=10+9)
SQLCatchVectorizedRuntimeError/conns=1/internalAssertion            297kB ± 0%     253kB ± 4%  -14.77%  (p=0.000 n=8+9)
SQLCatchVectorizedRuntimeError/conns=1/internalIndexOutOfRange      319kB ± 0%     272kB ± 0%  -14.75%  (p=0.000 n=9+9)
SQLCatchVectorizedRuntimeError/conns=1/internalDivideByZero         314kB ± 0%     267kB ± 0%  -15.06%  (p=0.000 n=8+8)
SQLCatchVectorizedRuntimeError/conns=1/contextCanceled              130kB ± 0%      83kB ± 0%  -36.57%  (p=0.000 n=8+9)
SQLCatchVectorizedRuntimeError/conns=20/noError                    83.2kB ± 0%    85.9kB ±10%     ~     (p=0.737 n=9+10)
SQLCatchVectorizedRuntimeError/conns=20/expectedWithCode            137kB ± 1%      87kB ± 0%  -36.29%  (p=0.000 n=9+8)
SQLCatchVectorizedRuntimeError/conns=20/expectedAssertion           376kB ± 4%     310kB ± 0%  -17.40%  (p=0.000 n=10+8)
SQLCatchVectorizedRuntimeError/conns=20/internalAssertion           297kB ± 0%     251kB ± 0%  -15.59%  (p=0.000 n=8+10)
SQLCatchVectorizedRuntimeError/conns=20/internalIndexOutOfRange     319kB ± 0%     272kB ± 0%  -14.77%  (p=0.000 n=10+8)
SQLCatchVectorizedRuntimeError/conns=20/internalDivideByZero        314kB ± 0%     267kB ± 0%  -15.04%  (p=0.000 n=9+9)
SQLCatchVectorizedRuntimeError/conns=20/contextCanceled             131kB ± 0%      83kB ± 0%  -36.87%  (p=0.000 n=8+8)
SQLCatchVectorizedRuntimeError/conns=50/noError                    87.0kB ± 8%    83.4kB ± 0%     ~     (p=0.128 n=10+8)
SQLCatchVectorizedRuntimeError/conns=50/expectedWithCode            137kB ± 1%      87kB ± 0%  -36.32%  (p=0.000 n=10+9)
SQLCatchVectorizedRuntimeError/conns=50/expectedAssertion           370kB ± 0%     311kB ± 0%  -16.11%  (p=0.000 n=9+9)
SQLCatchVectorizedRuntimeError/conns=50/internalAssertion           307kB ± 9%     257kB ± 6%  -16.09%  (p=0.000 n=10+10)
SQLCatchVectorizedRuntimeError/conns=50/internalIndexOutOfRange     325kB ± 4%     272kB ± 0%  -16.17%  (p=0.000 n=9+8)
SQLCatchVectorizedRuntimeError/conns=50/internalDivideByZero        316kB ± 0%     268kB ± 0%  -15.24%  (p=0.000 n=8+9)
SQLCatchVectorizedRuntimeError/conns=50/contextCanceled             134kB ±11%      83kB ± 1%  -38.13%  (p=0.000 n=9+9)

name                                                             old allocs/op  new allocs/op  delta
CatchVectorizedRuntimeError/noError                                  0.00           0.00          ~     (all equal)
CatchVectorizedRuntimeError/expected                                 36.0 ± 0%       3.0 ± 0%  -91.67%  (p=0.000 n=10+10)
CatchVectorizedRuntimeError/storage                                  11.0 ± 0%       3.0 ± 0%  -72.73%  (p=0.000 n=10+10)
CatchVectorizedRuntimeError/contextCanceled                          11.0 ± 0%       4.0 ± 0%  -63.64%  (p=0.000 n=10+10)
CatchVectorizedRuntimeError/internalWithCode                         35.0 ± 0%      37.0 ± 0%   +5.71%  (p=0.000 n=10+10)
CatchVectorizedRuntimeError/internal                                 46.0 ± 0%      59.0 ± 0%  +28.26%  (p=0.000 n=10+10)
CatchVectorizedRuntimeError/runtime                                  58.0 ± 0%      51.0 ± 0%  -12.07%  (p=0.000 n=10+10)
SQLCatchVectorizedRuntimeError/conns=1/noError                        839 ± 1%       850 ± 4%     ~     (p=0.362 n=8+10)
SQLCatchVectorizedRuntimeError/conns=1/expectedWithCode             1.00k ± 0%     0.95k ± 0%   -4.46%  (p=0.000 n=8+8)
SQLCatchVectorizedRuntimeError/conns=1/expectedAssertion            1.75k ± 6%     1.57k ± 0%  -10.37%  (p=0.000 n=9+9)
SQLCatchVectorizedRuntimeError/conns=1/internalAssertion            1.19k ± 0%     1.25k ± 7%   +5.16%  (p=0.000 n=8+9)
SQLCatchVectorizedRuntimeError/conns=1/internalIndexOutOfRange      1.41k ± 0%     1.41k ± 0%     ~     (p=0.912 n=9+9)
SQLCatchVectorizedRuntimeError/conns=1/internalDivideByZero         1.41k ± 1%     1.41k ± 0%     ~     (p=0.625 n=8+8)
SQLCatchVectorizedRuntimeError/conns=1/contextCanceled                873 ± 0%       864 ± 0%   -0.99%  (p=0.000 n=9+9)
SQLCatchVectorizedRuntimeError/conns=20/noError                       837 ± 0%       854 ± 6%     ~     (p=0.288 n=9+10)
SQLCatchVectorizedRuntimeError/conns=20/expectedWithCode            1.00k ± 0%     0.95k ± 0%   -4.87%  (p=0.000 n=9+8)
SQLCatchVectorizedRuntimeError/conns=20/expectedAssertion           1.79k ± 7%     1.58k ± 0%  -11.80%  (p=0.000 n=10+8)
SQLCatchVectorizedRuntimeError/conns=20/internalAssertion           1.19k ± 0%     1.23k ± 0%   +3.45%  (p=0.000 n=8+10)
SQLCatchVectorizedRuntimeError/conns=20/internalIndexOutOfRange     1.43k ± 0%     1.42k ± 0%   -0.21%  (p=0.010 n=10+8)
SQLCatchVectorizedRuntimeError/conns=20/internalDivideByZero        1.42k ± 0%     1.42k ± 0%     ~     (p=0.601 n=9+9)
SQLCatchVectorizedRuntimeError/conns=20/contextCanceled               885 ± 0%       868 ± 0%   -1.87%  (p=0.000 n=9+8)
SQLCatchVectorizedRuntimeError/conns=50/noError                       870 ± 6%       844 ± 0%     ~     (p=0.145 n=10+8)
SQLCatchVectorizedRuntimeError/conns=50/expectedWithCode            1.01k ± 1%     0.96k ± 0%   -5.55%  (p=0.000 n=10+9)
SQLCatchVectorizedRuntimeError/conns=50/expectedAssertion           1.76k ± 0%     1.59k ± 0%   -9.82%  (p=0.000 n=9+9)
SQLCatchVectorizedRuntimeError/conns=50/internalAssertion           1.28k ±10%     1.28k ± 7%     ~     (p=0.342 n=10+10)
SQLCatchVectorizedRuntimeError/conns=50/internalIndexOutOfRange     1.52k ±12%     1.44k ± 0%   -5.54%  (p=0.000 n=10+8)
SQLCatchVectorizedRuntimeError/conns=50/internalDivideByZero        1.45k ± 1%     1.44k ± 1%   -1.07%  (p=0.000 n=8+9)
SQLCatchVectorizedRuntimeError/conns=50/contextCanceled               944 ±17%       884 ± 1%   -6.37%  (p=0.000 n=9+9)
```

**Comment by michae2** [comment]
I made a change to the third commit (adding a new `internalError` wrapper) which should bring the behavior even closer to what it was before: now we unwrap this `internalError` wrapper immediately after catching it, so that it's not propagated upward. This also fixes a test that wasn't expecting to see the `internalError` in the error stack.

@yuzefovich does this sound sane to you?

**Review by yuzefovich — APPROVED** [review]
LGTM. I wonder whether `alreadyCaughtErr` idea would show improvement in some cases, but it doesn't need to block this PR.

> Reviewed 1 of 2 files at r9, 1 of 1 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/123277#-:-NwqqYAA6g0pMDhx-VjS:b-bmuhj2)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (and 4 stale) (waiting on @DrewKimball, @michae2, @petermattis, and @rafiss)

**Comment by michae2** [comment]
Thanks for looking at it. Trying again:

bors r=DrewKimball,petermattis,mgartner,yuzefovich

**Comment by michae2** [comment]
Third time's the charm.

bors r=DrewKimball,petermattis,mgartner,yuzefovich

**Comment by michae2** [comment]
blathers backport release-24.1.0-rc
