### PR TITLE
sql: ensure that a table can be created with a column named rowid

### LINKED ISSUE #45496: sql: you can't create a pk-less table with a column named rowid
```
root@127.0.0.1:53487/defaultdb> create table foo (rowid int);
ERROR: duplicate column name: "rowid"
```

This is caused by a leaky abstraction - we make a hidden column called `rowid` when a table doesn't have a primary key. But we should instead give the hidden column a unique name to avoid this problem.

cc @timveil @awoods187 @apantel

### PR DESCRIPTION
**Pull request by rohany**
Fixes #45496.

This PR also fixes a small bug in how indexes can be
renamed in the primary key change.

Release note (bug fix): This PR fixes a bug where a table without
a primary key and a column named "rowid" would throw an error
when being created.

### CODE REVIEW

**Comment by rohany** [comment]
Huh, seems like we had tests making sure that you couldn't create a table with just a rowid column and no primary key...

File: pkg/sql/alter_table.go [hunk 1]
```diff
@@ -527,9 +527,10 @@ func (n *alterTableNode) startExec(params runParams) error {
 			for _, idx := range indexesToRewrite {
 				// Clone the index that we want to rewrite.
 				newIndex := protoutil.Clone(idx).(*sqlbase.IndexDescriptor)
-				name := newIndex.Name + "_rewrite_for_primary_key_change"
+				basename := newIndex.Name + "_rewrite_for_primary_key_change"
+				name := basename
 				for try := 1; nameExists(name); try++ {
-					name = fmt.Sprintf("%s#%d", name, try)
+					name = fmt.Sprintf("%s#%d", basename, try)
```
Comment (otan) [inline pkg/sql/alter_table.go]: wdyt about using https://github.com/cockroachdb/cockroach/blob/b0be21ac55f839e98597a600f9f8479b0eccc5a4/pkg/sql/create_table.go#L760

File: pkg/sql/sqlbase/structured.go [hunk 2]
```diff
@@ -1243,9 +1243,18 @@ func (desc *MutableTableDescriptor) AllocateIDs() error {
...
 	if len(desc.PrimaryIndex.ColumnNames) == 0 && desc.IsPhysicalTable() {
 		// Ensure a Primary Key exists.
+		nameExists := func(name tree.Name) bool {
+			_, _, err := desc.FindColumnByName(name)
+			return err == nil
+		}
 		s := "unique_rowid()"
+		basename := "rowid"
+		name := basename
+		for try := 1; nameExists(tree.Name(name)); try++ {
```
Comment (otan) [inline pkg/sql/sqlbase/structured.go]: ditto about https://github.com/cockroachdb/cockroach/blob/b0be21ac55f839e98597a600f9f8479b0eccc5a4/pkg/sql/create_table.go#L760

File: pkg/sql/logictest/testdata/logic_test/alter_primary_key [hunk 3]
```diff
@@ -585,3 +585,14 @@ CREATE TABLE t (x INT PRIMARY KEY, y INT NOT NULL, z INT NOT NULL, FAMILY (x, y,
...
+# Ensure we don't rewrite default primary index even if its name isn't rowid.
+statement ok
+DROP TABLE IF EXISTS t;
+CREATE TABLE t (rowid INT NOT NULL);
+ALTER TABLE t ALTER PRIMARY KEY USING COLUMNS (rowid)
+
+query TT
+SELECT index_name, column_name FROM [SHOW INDEXES FROM t]
+----
+primary rowid
```
Comment (otan) [inline pkg/sql/logictest/testdata/logic_test/alter_primary_key]: maybe `SHOW CREATE TABLE t` instead? we'd be able to see all the renames going on.

**Comment by rohany** [comment]
Thanks for the pointer, updated.

File: pkg/util/unique_name.go [hunk 4]
```diff
@@ -0,0 +1,25 @@
...
+
+package util
+
+import "fmt"
+
+// GenerateUniqueConstraintName attempts to generate a unique constraint name
+// with the given prefix.
+// It will first try prefix by itself, then it will subsequently try
+// adding numeric digits at the end, starting from 1.
+func GenerateUniqueConstraintName(prefix string, nameExistsFunc func(name string) bool) string {
```
Comment (jordanlewis) [inline pkg/util/unique_name.go]: This doesn't have anything to do with constraints. I also think it should live in the SQL package, not util, to make sure random other users don't start to have expectations about it and lock us into behaving the way we do right now.

Comment (jordanlewis) [reply pkg/util/unique_name.go]: (doesn't have to be `pkg/sql` itself, but either that or a subpackage please!)

Comment (rohany) [reply pkg/util/unique_name.go]: maybe I should make it just generate unique name, because there are some uses in sqlbase. I could move it to there though, but it seems like a utility function.

Comment (jordanlewis) [reply pkg/util/unique_name.go]: `util` is where things go to die. Make a new package with a better name, maybe!

**Review by otan — APPROVED** [review]
looks lgtm to me

**Comment by rohany** [comment]
bors r=otan
