### PR TITLE
sql/pgwire: min/max report correct return type for prepared statements

### LINKED ISSUE #54016: sql/pgwire: aggregates get incorrect DataTypeSize in extended protocol
**Describe the problem**

When using a prepared statement, using an aggregate like `MAX` over an `INT4` column causes CockroachDB to return result metadata that indicates that the width of the return data is 8 bytes. That's incorrect; it should be 4 bytes. In fact, CockroachDB disagrees with itself, because in when using the binary format, it does in fact return a 4 byte value.

**To Reproduce**

Run the following Go code. Using CockroachDB 20.1.5 (though it looks like all released versions are affected).

```
package main

import (
    "context"
    "fmt"
    "log"

    "github.com/jackc/pgx/v4"
)

func main() {
    config, err := pgx.ParseConfig("postgresql://root@localhost:26257/defaultdb?sslmode=disable")
    if err != nil {
        log.Fatal("error configuring the database: ", err)
    }

    // Connect to the "bank" database.
    conn, err := pgx.ConnectConfig(context.Background(), config)
    if err != nil {
        log.Fatal("error connecting to the database: ", err)
    }
    defer conn.Close(context.Background())

    if _, err := conn.Exec(context.Background(),
        "DROP TABLE IF EXISTS accounts"); err != nil {
        log.Fatal(err)
    }

    // Create the "accounts" table.
    if _, err := conn.Exec(context.Background(),
        "CREATE TABLE IF NOT EXISTS accounts (id INT PRIMARY KEY, balance INT4)"); err != nil {
        log.Fatal(err)
    }

    // Insert two rows into the "accounts" table.
    if _, err := conn.Exec(context.Background(),
        "INSERT INTO accounts (id, balance) VALUES (1, 1000), (2, 250)"); err != nil {
        log.Fatal(err)
    }

    // Print out the balances.
    rows, err := conn.Query(context.Background(), "SELECT max(balance) FROM accounts")
    if err != nil {
        log.Fatal(err)
    }
    defer rows.Close()
    fmt.Println("Max balance:")
    for rows.Next() {
        var balance int
        if err := rows.Scan(&balance); err != nil {
            log.Fatal(err)
        }
        fmt.Printf("balance %d\n", balance)
    }
}
```

This causes the error `can't scan into dest[0]: invalid length for int8: 4`.

**Expected behavior**

The output should be `balance 1000`.

**Additional context**

Here is a PGTest file that reproduces the result. It fails against CockroachDB, but resolving this bug will fix it.

```
# This test verifies that the DataTypeSize field in the RowDescription and
# DataRow messages both agree when using the MAX aggregate on an INT4 column.

# Prepare the environment.
send
Query {"String": "DROP TABLE IF EXISTS max_test"}
----

until ignore=NoticeResponse
ReadyForQuery
----
{"Type":"CommandComplete","CommandTag":"DROP TABLE"}
{"Type":"ReadyForQuery","TxStatus":"I"}

send
Query {"String": "CREATE TABLE max_test (id INT8 PRIMARY KEY, b INT4)"}
----

until
ReadyForQuery
----
{"Type":"CommandComplete","CommandTag":"CREATE TABLE"}
{"Type":"ReadyForQuery","TxStatus":"I"}


send
Query {"String": "INSERT INTO max_test (id, b) VALUES (1, 1000), (2, 250)"}
----

until
ReadyForQuery
----
{"Type":"CommandComplete","CommandTag":"INSERT 0 2"}
{"Type":"ReadyForQuery","TxStatus":"I"}

send
Query {"String": "SELECT max(b) FROM max_test"}
----

until
ReadyForQuery
----
{"Type":"RowDescription","Fields":[{"Name":"max","TableOID":0,"TableAttributeNumber":0,"DataTypeOID":23,"DataTypeSize":4,"TypeModifier":-1,"Format":0}]}
{"Type":"DataRow","Values":[{"text":"1000"}]}
{"Type":"CommandComplete","CommandTag":"SELECT 1"}
{"Type":"ReadyForQuery","TxStatus":"I"}

# 80 = ASCII 'P' for Portal
send
Parse {"Name": "s1", "Query": "SELECT max(b) FROM max_test"}
Bind {"DestinationPortal": "p1", "PreparedStatement": "s1"}
Describe {"ObjectType": 80, "Name": "p1"}
Execute {"Portal": "p1"}
Sync
----

until ignore_table_oids
ReadyForQuery
----
{"Type":"ParseComplete"}
{"Type":"BindComplete"}
{"Type":"RowDescription","Fields":[{"Name":"max","TableOID":0,"TableAttributeNumber":0,"DataTypeOID":23,"DataTypeSize":4,"TypeModifier":-1,"Format":0}]}
{"Type":"DataRow","Values":[{"text":"1000"}]}
{"Type":"CommandComplete","CommandTag":"SELECT 1"}
{"Type":"ReadyForQuery","TxStatus":"I"}

# 80 = ASCII 'P' for Portal
# ResultFormatCodes [1] = FormatBinary
send
Parse {"Name": "s2", "Query": "SELECT max(b) FROM max_test"}
Bind {"DestinationPortal": "p2", "PreparedStatement": "s2", "ResultFormatCodes": [1]}
Describe {"ObjectType": 80, "Name": "p2"}
Execute {"Portal": "p2"}
Sync
----

until ignore_table_oids
ReadyForQuery
----
{"Type":"ParseComplete"}
{"Type":"BindComplete"}
{"Type":"RowDescription","Fields":[{"Name":"max","TableOID":0,"TableAttributeNumber":0,"DataTypeOID":23,"DataTypeSize":4,"TypeModifier":-1,"Format":1}]}
{"Type":"DataRow","Values":[{"binary":"000003e8"}]}
{"Type":"CommandComplete","CommandTag":"SELECT 1"}
{"Type":"ReadyForQuery","TxStatus":"I"}
```

### LINKED ISSUE #55313: MAX() on INT2 column returns inconsistent type
**Describe the problem**

We have a table with an INT2 column defined.

```
CREATE TABLE test (somecolumn INT2)
```

When we attempt to compute an aggregation on this column, we inconsistently receive a 2-byte field or an 8-byte field in the result.

```
SELECT MAX(somecolumn) FROM test
```

**To Reproduce**

Create table as above and select as above.
We are running with vectorize=on.

**Expected behavior**

We're running in a Java application with pgJDBC. When we receive only 2 bytes, the postgres driver throwing an `ArrayIndexOutOfBoundsException` when it tries to read the field from the `ResultSet`. The response field is being defined as an 8-byte integer.

For PostgreSQL compatibility, `MAX` and `MIN` are supposed to return the same type that was input. So, `MAX(INT2)` should return `INT2`.

**Additional data / screenshots**

**Environment:**
 - CockroachDB version 20.1.6
 - Linux
 - JDBC/pgJDBC

**Additional context**
Application crashes with exception when trying to process ResultSet.

### PR DESCRIPTION
**Pull request by rafiss**
fixes #54016
fixes #55313 

When using a prepared statement, the optimizer is used in order to
determine the type OIDs of the resulting row. Since the min/max
aggregates had an overload that used a fix return type, min/max over
INT4 columns were reported as INT8. However, when it came to execution
time, they would in fact be INT4. This confuses drivers, and in the case
of pgx and pgjdbc, causes a runtime exception because the wrong number
of bytes was returned (it had to read 4 bytes for something we reported
was an 8 byte column).

Now, the min/max overloads return the same type as the argument type.
This allows us to remove special-case logic in the vectorized engine for
int64s. It also requires an update to how the engine calculates the
return type of window functions.

Also, there is a pgwire test for checking the data type size in the
RowDescription now.

The first commit in this PR cleans up existing pgwire tests so they pass against Postgres.

Release note (bug fix): Using the min/max aggregates in a prepared
statement will now report the correct data type size.

### CODE REVIEW

**Comment by rafiss** [comment]
Or maybe an alternative is to make an overload for each of `INT2`, `INT4`, `INT8` (and give them all fixed return types) instead of just one overload for `INT`?

**Comment by ikgo** [comment]
Hi,
what a target release for the fix?

**Comment by rafiss** [comment]
@ikgo I have been focusing on other tasks, so this likely will not be fixed until after the 20.2.0 release. To help us with prioritization, could you let us know if you are blocked and don't have a workaround for this bug?

**Comment by ikgo** [comment]
hi,
this bug blocker, in my opinion.
any aggregation function in statement will forward to unpredictable behavior.
this bug block usage of pgx driver. 
many tools, like GORM2, use/move to pgx driver, so we stack with old unsupported version

to workaround issue we should rewrite queries and cast aggregate functions result to particular type. this is a lot of work and make system not maintainable.

Any ideas from your side how to workaround it?

**Comment by rafiss** [comment]
@ikgo Thanks for providing that context. I agree that it's important to fix this.

Until a fix is ready, here are some workarounds you can try:
- set `PreferSimpleProtocol` in `ConnConfig`. this affects all queries. there might be a performance impact. https://pkg.go.dev/github.com/jackc/pgx/v4#ConnConfig
- add a cast to the queries that use min or max. you mentioned that would be a lot of overhead, but it is a one-time change. the new queries will keep working even after this bug is addressed.

File: pkg/sql/sem/builtins/aggregate_builtins.go [hunk 1]
```diff
@@ -209,28 +209,18 @@ var aggregates = map[string]builtinDefinition{
...
-			// If t is an ambiguous type (like AnyCollatedString), then our aggregate
-			// does not have a fixed return type.
-			if t.IsAmbiguous() {
-				return makeAggOverloadWithReturnType(
-					[]*types.T{t}, tree.FirstNonNullReturnType(), newMaxAggregate, info, vol,
-				)
-			}
-			return makeAggOverload([]*types.T{t}, t, newMaxAggregate, info, vol)
+			return makeAggOverloadWithReturnType(
+				[]*types.T{t}, tree.IdentityReturnType(0), newMaxAggregate, info, vol,
```
Comment (otan) [inline pkg/sql/sem/builtins/aggregate_builtins.go:213]: should this be done for all `collectOverloads` aggregate/window functions?

File: docs/generated/sql/aggregates.md [hunk 2]
```diff
@@ -85,93 +85,93 @@
...
-<tr><td><a name="max"></a><code>max(arg1: <a href="string.html">string</a>) &rarr; <a href="string.html">string</a></code></td><td><span class="funcdesc"><p>Identifies the maximum selected value.</p>
+<tr><td><a name="max"></a><code>max(arg1: <a href="string.html">string</a>) &rarr; anyelement</code></td><td><span class="funcdesc"><p>Identifies the maximum selected value.</p>
 </span></td></tr>
-<tr><td><a name="max"></a><code>max(arg1: <a href="time.html">time</a>) &rarr; <a href="time.html">time</a></code></td><td><span class="funcdesc"><p>Identifies the maximum selected value.</p>
+<tr><td><a name="max"></a><code>max(arg1: <a href="time.html">time</a>) &rarr; anyelement</code></td><td><span class="funcdesc"><p>Identifies the maximum selected value.</p>
 </span></td></tr>
-<tr><td><a name="max"></a><code>max(arg1: <a href="timestamp.html">timestamp</a>) &rarr; <a href="timestamp.html">timestamp</a></code></td><td><span class="funcdesc"><p>Identifies the maximum selected value.</p>
+<tr><td><a name="max"></a><code>max(arg1: <a href="timestamp.html">timestamp</a>) &rarr; anyelement</code></td><td><span class="funcdesc"><p>Identifies the maximum selected value.</p>
```
Comment (otan) [inline docs/generated/sql/aggregates.md:108]: this looks unintended.

Comment (rafiss) [reply docs/generated/sql/aggregates.md:108]: well _technically_ it's true, since if you do max over a timestamp column but the table is empty, it returns null.

but yeah it's kinda annoying. i looked earlier into how to make the docgen stuff not do this and didn't have luck. but i think i have gained some XP so i'll try figuring it out again

File: pkg/sql/sem/builtins/aggregate_builtins.go (hunk 1 above)
Comment (rafiss) [reply pkg/sql/sem/builtins/aggregate_builtins.go:213]: hmm well i think all the other ones are appropriately special cased. avg and sum intentionally have a different return type.

File: docs/generated/sql/aggregates.md (hunk 2 above)
Comment (otan) [reply docs/generated/sql/aggregates.md:108]: NULL is still typed (in Postgres!)

```

otan=# create table agg_a(a int);
CREATE TABLE
otan=# select max(a) from agg_a;
 max
-----

(1 row)

otan=# select pg_typeof(max(a)) from agg_a;
 pg_typeof
-----------
 integer
(1 row)

```

File: pkg/sql/sem/builtins/aggregate_builtins.go (hunk 1 above)
Comment (otan) [reply pkg/sql/sem/builtins/aggregate_builtins.go:213]: i believe i meant items such as percentile_disc_impl, lag, lead, first_value, last_value, nth_value.

Comment (rafiss) [reply pkg/sql/sem/builtins/aggregate_builtins.go:213]: i see! working on it

File: docs/generated/sql/aggregates.md (hunk 2 above)
Comment (rafiss) [reply docs/generated/sql/aggregates.md:108]: yeah but CRDB doesn't have typed nulls! i mean i guess these docs were pretending we did before, so i do want to try to go back to how it was

Comment (otan) [reply docs/generated/sql/aggregates.md:108]: image

i think the optimizer has typed nulls tho :D 
one day our type system will match...

Comment (andy-kimball) [reply docs/generated/sql/aggregates.md:108]: Actually, CRDB does have typed NULL support. It's just that the `pg_typeof` is not built to take advantage of it today. But it could be. The Optimizer keeps track of all static types in the expression, for example:
```
root@:26257/management_console_test> explain (opt,types) SELECT pg_typeof(NULL::int);
                     text
-----------------------------------------------
  values
   └── tuple [type=tuple{string}]
        └── function: pg_typeof [type=string]
             └── null [type=int]
```
The optimizer knows that the NULL has type `int`. But the `pg_typeof` function has no way of passing that information in. Instead of using a runtime function (which don't preserve types), we probably should just constant fold `pg_typeof` in the optimizer, since we always statically know the right type. This would break backwards-compatibility, but could allow us to more closely match PG semantics.

**Review by yuzefovich — COMMENTED** [review]
> Reviewed 5 of 5 files at r1, 10 of 10 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/54080)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @otan and @rafiss)

___
*[pkg/sql/colexec/execgen/cmd/execgen/min_max_agg_gen.go, line 39 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/54080#-MJdBziyD4emfpT-r9yz:-MJdBziyD4emfpT-r9z-:b1nlq08) ([raw file](https://github.com/cockroachdb/cockroach/blob/f40a528237f09a21ee016fb1637f6c33602f26c8/pkg/sql/colexec/execgen/cmd/execgen/min_max_agg_gen.go#L39)):*
> ```Go
> }
> 
> func (a minMaxTmplInfo) CopyValMaybeCast(dest, src string) string {
> ```

We should now then remove this function and use `execgen.COPYVAL` instead of this custom `_COPYVAL_MAYBE_CAST` in `_tmpl.go` file.

Actually, this whole file could be cleaned up and simplified. Feel free to leave `TODO(yuzefovich)` about it.
___
*[pkg/sql/pgwire/testdata/pgtest/data_type_size, line 2 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/54080#-MJdEqas3p0hbMapFahj:-MJdEqas3p0hbMapFahk:b-vl7pxo) ([raw file](https://github.com/cockroachdb/cockroach/blob/f40a528237f09a21ee016fb1637f6c33602f26c8/pkg/sql/pgwire/testdata/pgtest/data_type_size#L2)):*
> ```
> # This test verifies that the DataTypeSize field in the RowDescription and
> # DataRow messages both agree when using the MAX aggregate on an INT4 column.
> ```

nit: it might be worth testing `min` as well, just in case.
___
*[pkg/sql/pgwire/testdata/pgtest/enum, line 96 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/54080#-MJd8osmBYZUWp1klouD:-MJd8osn9V2z942qnKN0:b-lj2qmu) ([raw file](https://github.com/cockroachdb/cockroach/blob/d8a4d5f959dc8686c9bc7aa76980421c3fa318e4/pkg/sql/pgwire/testdata/pgtest/enum#L96)):*
> ```
> ----
> 
> until ignore_table_oids ignore_type_oids noncrdb_only
> ```

Did you find this not helpful at all and that's why deleted it?
___
*[pkg/sql/sem/builtins/aggregate_builtins.go, line 213 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/54080#-MGkHGihVhqCFuBx1nZi-r2-213:-MJdEQ_4222ApnGLw6iR:bpm6xlz) ([raw file](https://github.com/cockroachdb/cockroach/blob/f40a528237f09a21ee016fb1637f6c33602f26c8/pkg/sql/sem/builtins/aggregate_builtins.go#L213)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

i see! working on it now
</blockquote></details>

I think all those cases are correctly typed already - only `min` and `max` seem to have the special case behavior.
___
*[pkg/sql/sem/tree/overload.go, line 112 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/54080#-MJdDEYc8Zn1rBC_ufZL:-MJdDEYc8Zn1rBC_ufZM:bphcj12) ([raw file](https://github.com/cockroachdb/cockroach/blob/f40a528237f09a21ee016fb1637f6c33602f26c8/pkg/sql/sem/tree/overload.go#L112)):*
> ```Go
> func (b Overload) InferReturnTypeFromArgTypes(inputTypes []*types.T) *types.T {
> 	retTyp := b.FixedReturnType()
> 	// If the output type of the aggregation depends on its inputs, then
> ```

nit: `s/aggregation/function/`.
___
*[pkg/sql/sem/tree/overload.go, line 121 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/54080#-MJdDpUo5FOFzLsmwggr:-MJdDpUo5FOFzLsmwggs:b-b45whc) ([raw file](https://github.com/cockroachdb/cockroach/blob/f40a528237f09a21ee016fb1637f6c33602f26c8/pkg/sql/sem/tree/overload.go#L121)):*
> ```Go
> 	// "TypedDummy" construct. This is because some types don't have resident
> 	// members (like an ENUM with no values), and we shouldn't error out
> 	// trying to pick an aggregate spec for those cases.
> ```

nit:  also replace `aggregate` with something.

**Review by rafiss — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/54080)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @otan, @rafiss, and @yuzefovich)

___
*[pkg/sql/pgwire/testdata/pgtest/data_type_size, line 2 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/54080#-MJdEqas3p0hbMapFahj:-MJddC4VDNEUl8bq8Jam:b-cc3yi3) ([raw file](https://github.com/cockroachdb/cockroach/blob/f40a528237f09a21ee016fb1637f6c33602f26c8/pkg/sql/pgwire/testdata/pgtest/data_type_size#L2)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

nit: it might be worth testing `min` as well, just in case.
</blockquote></details>

i thought so as well -- i added it locally
___
*[pkg/sql/pgwire/testdata/pgtest/enum, line 96 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/54080#-MJd8osmBYZUWp1klouD:-MJddKX-0Or3iuXVoMwp:bfblen0) ([raw file](https://github.com/cockroachdb/cockroach/blob/d8a4d5f959dc8686c9bc7aa76980421c3fa318e4/pkg/sql/pgwire/testdata/pgtest/enum#L96)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

Did you find this not helpful at all and that's why deleted it?
</blockquote></details>

yeah it looks like it's basically ignoring all the assertions that would be relevant so i just removed this test case
___
*[pkg/sql/sem/builtins/aggregate_builtins.go, line 213 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/54080#-MGkHGihVhqCFuBx1nZi-r2-213:-MJdzwgz-sUO36eT4_7N:b-s34t3k) ([raw file](https://github.com/cockroachdb/cockroach/blob/f40a528237f09a21ee016fb1637f6c33602f26c8/pkg/sql/sem/builtins/aggregate_builtins.go#L213)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

I think all those cases are correctly typed already - only `min` and `max` seem to have the special case behavior.
</blockquote></details>

i re-ran my pgx repro code from #54016 for first_value, last_value, and nth_value, and it didn't crash.

i'm not entirely sure why... i would have expected last_value (for example) to return int4 if the input is int4. but i guess it's fine if we actually implemented the function to return an int8. the issue with min/max is that we said we'd send an 8 byte value, but we actually sent 4 bytes.
___
*[pkg/sql/sem/tree/overload.go, line 112 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/54080#-MJdDEYc8Zn1rBC_ufZL:-MJe-YVG-HcCZwnSs0H6:bb7f2mf) ([raw file](https://github.com/cockroachdb/cockroach/blob/f40a528237f09a21ee016fb1637f6c33602f26c8/pkg/sql/sem/tree/overload.go#L112)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

nit: `s/aggregation/function/`.
</blockquote></details>

done
___
*[pkg/sql/sem/tree/overload.go, line 121 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/54080#-MJdDpUo5FOFzLsmwggr:-MJe-ZL16qolDlHbWG6O:bb7f2mf) ([raw file](https://github.com/cockroachdb/cockroach/blob/f40a528237f09a21ee016fb1637f6c33602f26c8/pkg/sql/sem/tree/overload.go#L121)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

nit:  also replace `aggregate` with something.
</blockquote></details>

done

**Review by rafiss — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/54080)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @otan and @yuzefovich)

___
*[pkg/sql/colexec/execgen/cmd/execgen/min_max_agg_gen.go, line 39 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/54080#-MJdBziyD4emfpT-r9yz:-MJe3Soy95qk_Nl8Jdyx:bb7f2mf) ([raw file](https://github.com/cockroachdb/cockroach/blob/f40a528237f09a21ee016fb1637f6c33602f26c8/pkg/sql/colexec/execgen/cmd/execgen/min_max_agg_gen.go#L39)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

We should now then remove this function and use `execgen.COPYVAL` instead of this custom `_COPYVAL_MAYBE_CAST` in `_tmpl.go` file.

Actually, this whole file could be cleaned up and simplified. Feel free to leave `TODO(yuzefovich)` about it.
</blockquote></details>

done

**Review by otan — APPROVED** [review]
> Reviewed 6 of 7 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/54080)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @otan, @rafiss, and @yuzefovich)

___
*[docs/generated/sql/functions.md, line 1085 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/54080#-MJe95rm-FcRn9bG-d4G:-MJe95rm-FcRn9bG-d4H:b-mlwrsm) ([raw file](https://github.com/cockroachdb/cockroach/blob/721dfc15a2781e646e588bcce0e519cdc771b947/docs/generated/sql/functions.md#L1085)):*
> ```Markdown
> </table>
> </span></td></tr>
> <tr><td><a name="unnest"></a><code>unnest(anyelement[], anyelement[], anyelement[]...) &rarr; tuple{anyelement AS unnest, anyelement AS unnest, anyelement AS unnest}</code></td><td><span class="funcdesc"><p>Returns the input arrays as a set of rows</p>
> ```

this should also be anyelement AS unnest...., but ok if you want to fix this in a later PR.
___
*[pkg/sql/sem/tree/overload.go, line 110 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/54080#-MJe9PQr4TNDDe0Mq34P:-MJe9PQr4TNDDe0Mq34Q:b-7uh0xc) ([raw file](https://github.com/cockroachdb/cockroach/blob/721dfc15a2781e646e588bcce0e519cdc771b947/pkg/sql/sem/tree/overload.go#L110)):*
> ```Go
> // InferReturnTypeFromArgTypes returns the type that the function returns,
> // inferring the type based on the function's inputTypes if necessary.
> func (b Overload) InferReturnTypeFromArgTypes(inputTypes []*types.T) *types.T {
> ```

nit: `InferReturnTypeFromInputArgTypes` maybe, since the `Input` is the key to this phrase here.

**Review by rafiss — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/54080)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @otan and @yuzefovich)

___
*[docs/generated/sql/functions.md, line 1085 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/54080#-MJe95rm-FcRn9bG-d4G:-MJeFIdi9kJ7BD0M3wU2:bj67okr) ([raw file](https://github.com/cockroachdb/cockroach/blob/721dfc15a2781e646e588bcce0e519cdc771b947/docs/generated/sql/functions.md#L1085)):*
<details><summary><i>Previously, otan (Oliver Tan) wrote…</i></summary><blockquote>

this should also be anyelement AS unnest...., but ok if you want to fix this in a later PR.
</blockquote></details>

added todo
___
*[pkg/sql/sem/tree/overload.go, line 110 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/54080#-MJe9PQr4TNDDe0Mq34P:-MJeATbCDE8kMnjox8-K:bdgofhk) ([raw file](https://github.com/cockroachdb/cockroach/blob/721dfc15a2781e646e588bcce0e519cdc771b947/pkg/sql/sem/tree/overload.go#L110)):*
<details><summary><i>Previously, otan (Oliver Tan) wrote…</i></summary><blockquote>

nit: `InferReturnTypeFromInputArgTypes` maybe, since the `Input` is the key to this phrase here.
</blockquote></details>

done, good point

**Review by yuzefovich — APPROVED** [review]
> Reviewed 5 of 5 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/54080)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @otan and @yuzefovich)

**Comment by rafiss** [comment]
thanks for the reviews!

bors r=otan,yuzefovich
