### PR TITLE
changefeedccl: fix initial-scan-only roachtest failure

### LINKED ISSUE #92041: ccl/changefeedccl: TestChangefeedOnlyInitialScan failed
ccl/changefeedccl.TestChangefeedOnlyInitialScan [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_StressBazel/7555874?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_StressBazel/7555874?buildTab=artifacts#/) on master @ [ea7c52e5a930be203318db6e338edd5dde7537bd](https://github.com/cockroachdb/cockroach/commits/ea7c52e5a930be203318db6e338edd5dde7537bd):

```
=== RUN   TestChangefeedOnlyInitialScan
    test_log_scope.go:161: test logs captured to: /artifacts/tmp/_tmp/905465f697dc04c39f7d8a82cb057bfe/logTestChangefeedOnlyInitialScan3703856319
    test_log_scope.go:79: use -show-logs to present logs inline
=== CONT  TestChangefeedOnlyInitialScan
    changefeed_test.go:6571: -- test log scope end --
test logs left over in: /artifacts/tmp/_tmp/905465f697dc04c39f7d8a82cb057bfe/logTestChangefeedOnlyInitialScan3703856319
--- FAIL: TestChangefeedOnlyInitialScan (91.76s)
=== RUN   TestChangefeedOnlyInitialScan/enterprise/initial_backfill_only
    changefeed_test.go:6560: 
        	Error Trace:	/home/roach/.cache/bazel/_bazel_roach/c5a4e7d36696d9cd970af2045211a7df/sandbox/processwrapper-sandbox/3141/execroot/com_github_cockroachdb_cockroach/bazel-out/k8-fastbuild/bin/pkg/ccl/changefeedccl/changefeedccl_test_/changefeedccl_test.runfiles/com_github_cockroachdb_cockroach/pkg/ccl/changefeedccl/changefeed_test.go:6560
        	Error:      	Not equal: 
        	            	expected: 5000
        	            	actual  : 0
        	Test:       	TestChangefeedOnlyInitialScan/enterprise/initial_backfill_only
        --- FAIL: TestChangefeedOnlyInitialScan/enterprise/initial_backfill_only (44.90s)
=== RUN   TestChangefeedOnlyInitialScan/enterprise/initial_scan_only
    changefeed_test.go:6560: 
        	Error Trace:	/home/roach/.cache/bazel/_bazel_roach/c5a4e7d36696d9cd970af2045211a7df/sandbox/processwrapper-sandbox/3141/execroot/com_github_cockroachdb_cockroach/bazel-out/k8-fastbuild/bin/pkg/ccl/changefeedccl/changefeedccl_test_/changefeedccl_test.runfiles/com_github_cockroachdb_cockroach/pkg/ccl/changefeedccl/changefeed_test.go:6560
        	Error:      	Not equal: 
        	            	expected: 5000
        	            	actual  : 0
        	Test:       	TestChangefeedOnlyInitialScan/enterprise/initial_scan_only
        --- FAIL: TestChangefeedOnlyInitialScan/enterprise/initial_scan_only (42.70s)
=== RUN   TestChangefeedOnlyInitialScan/enterprise
    helpers_test.go:751: making server as secondary tenant
    helpers_test.go:837: making enterprise feed factory
    helpers_test.go:851: pgURL enterprise root
    --- FAIL: TestChangefeedOnlyInitialScan/enterprise (91.55s)
```
<p>Parameters: <code>TAGS=bazel,gss,deadlock</code>
</p>
<details><summary>Help</summary>
<p>

See also: [How To Investigate a Go Test Failure \(internal\)](https://cockroachlabs.atlassian.net/l/c/HgfXfJgM)
</p>
</details>
/cc @cockroachdb/cdc
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*TestChangefeedOnlyInitialScan.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)
</sub>

Jira issue: CRDB-21535

Epic CRDB-11732

### PR DESCRIPTION
**Pull request by samiskin**
Resolves #92041

This does 3 small changes:
1. Fix the test failure, looks like it was just something that got missed in the last rebase of the initial PR
2. Make the prometheus configuration be stored even on SkipInit to avoid errors when the stats collection code attempts to run.
3. Move the test to use cloudstorage since its our fastest sink so it would better stress test the rest of the pipeline.

Release note: None

### CODE REVIEW

File: pkg/cmd/roachtest/tests/cdc.go [hunk 1]
```diff
@@ -520,15 +518,19 @@ func (ct *cdcTester) startGrafana() {
...
+		if err != nil {
+			ct.t.Errorf("error starting prometheus/grafana: %s", err)
+		}
+		nodeURLs, err := ct.cluster.ExternalIP(ct.ctx, ct.t.L(), ct.workloadNode)
+		if err != nil {
+			ct.t.Errorf("error getting grafana node external ip: %s", err)
+		}
+		ct.t.Status(fmt.Sprintf("started grafana at http://%s:3000/d/928XNlN4k/basic?from=now-15m&to=now", nodeURLs[0]))
+	} else {
+		ct.t.Status("skipping graphana installation")
```
Comment (jayshrivastava) [inline pkg/cmd/roachtest/tests/cdc.go:532]: nit: typo for `grafana`

**Review by jayshrivastava — APPROVED** [review]
