### PR TITLE
crosscluster/logical: fix ALTER .. SET REPLICATION READ VIRTUAL CLUSTER

### LINKED ISSUE #143216: PCR: allow starting a reader tenant after PCR stream has been started
ALTER VIRTUAL CLUSTER add reader tenant should work and add a reader tenant after pcr stream has already started and standby has been created.

Jira issue: CRDB-48715

### PR DESCRIPTION
**Pull request by dt**
This is in the syntax but the ALTER function was not handling this option if it was set -- the statement would silently succeed without even attempting to create a reader cluster.

This statement now attempts to create a readder cluster. If one already exists, or another virtual cluster has otherwise been created with the reader's default name, the statement will fail.

Release note (bug fix): The ALTER VIRTUAL CLUSTER SET REPLICATION READ VIRTUAL CLUSTER syntax is now supported for adding a reader virtual cluster for an existing PCR standby.
Epic: none.

### CODE REVIEW

**Review by msbutler — COMMENTED** [review]
I believe this implementation simply creates the reader tenant, but it will not activate the reader tenant which is currently done in the stream ingestion frontier here. I suppose you could activate the tenant in this cmd if there's a replicated time. But if the user runs this during the initial scan, we'll need to set the reader tenant ID in the job details so the sif conditional is hit. 

https://github.com/dt/cockroach/blob/alter-add-reader/pkg/crosscluster/physical/stream_ingestion_frontier_processor.go#L375

**Comment by dt** [comment]
> activate the reader tenant

Ah, great catch. Fixed.

**Review by msbutler — APPROVED** [review]

File: pkg/crosscluster/physical/alter_replication_job_test.go [hunk 1]
```diff
@@ -114,6 +114,30 @@ func TestAlterTenantCompleteToLatest(t *testing.T) {
...
+	jobutils.WaitForJobToRun(t, c.SrcSysSQL, jobspb.JobID(producerJobID))
+	jobutils.WaitForJobToRun(t, c.DestSysSQL, jobspb.JobID(ingestionJobID))
+
+	c.WaitUntilReplicatedTime(c.SrcCluster.Server(0).Clock().Now(), jobspb.JobID(ingestionJobID))
+	c.DestSysSQL.CheckQueryResults(t, "SELECT name FROM [SHOW TENANTS] ORDER BY name",
+		[][]string{{"destination"}, {"system"}},
+	)
+	c.DestSysSQL.Exec(t, "ALTER TENANT $1 SET REPLICATION READ VIRTUAL CLUSTER", args.DestTenantName)
+	c.DestSysSQL.CheckQueryResults(t, "SELECT name FROM [SHOW TENANTS] ORDER BY name",
+		[][]string{{"destination"}, {"destination-readonly"}, {"system"}},
```
Comment (msbutler) [inline pkg/crosscluster/physical/alter_replication_job_test.go:137]: nit: you could validate the data_state here as well.

**Comment by dt** [comment]
TFTR!

bors r+
