### PR TITLE
backup: add two-phase retry mechanism

### LINKED ISSUE #159388: backup: retry permanent errors from distsql flow for 5 minutes and only fail if no progress is made in 5 minute
We have seen large backups fail because of transient network errors, despite our best efforts to tune cloud client specific retry policies. While we could try to continue adding to non permanent bulk errors white list, maintaining a white list is hard. Instead, we could retry a backup flow for 5 minutes and only fail if no progress is made in those 5 minutes.

A workaround for gcp clusters is bumping `cloudstorage.gs.chunking.retry_timeout`

Jira issue: CRDB-57824

### PR DESCRIPTION
**Pull request by kev-cao**
This commit teaches backup to use a two-phase retry raather than the attempt-based retry we use today. Under this new retry mechanism, backup will use an attempt based retry until all nodes have reported progress. After all nodes have done so, we switch to a short duration based policy that is reset each time progress is made.

Resolves: #159388

Release note: None

### CODE REVIEW

File: pkg/backup/backup_job.go [hunk 1]
```diff
@@ -106,6 +106,139 @@ func filterSpans(includes []roachpb.Span, excludes []roachpb.Span) []roachpb.Spa
...
+		case initialState:
+			// In the initial state, we are still waiting for all nodes to return
+			// progress.
+			var numProgressedNodes int
+			for _, v := range progress {
+				if v > 0 {
+					numProgressedNodes++
+				}
+			}
+			if numProgressedNodes == numInstances && numProgressedNodes > 0 {
```
Comment (msbutler) [inline pkg/backup/backup_job.go:185]: why would numInstances ever be zero?

File: pkg/backup/backup_job.go [hunk 2]
```diff
@@ -106,6 +106,139 @@ func filterSpans(includes []roachpb.Span, excludes []roachpb.Span) []roachpb.Spa
...
+) {
+	type retryState string
+	const (
+		initialState   retryState = "initial"
+		secondaryState retryState = "secondary"
+	)
+
+	currState := initialState
+	initialPolicy, secondaryPolicy := getBackupRetryPolicies(execCtx.ExecCfg())
+	prevTotalProg := float32(0)
```
Comment (msbutler) [inline pkg/backup/backup_job.go]: shouldn't we load job.FractionCompleted() here? i'm thinking about a backup that has been pause/resumed.

File: pkg/backup/backup_job.go [hunk 3]
```diff
@@ -106,6 +106,139 @@ func filterSpans(includes []roachpb.Span, excludes []roachpb.Span) []roachpb.Spa
...
+		var progress map[execinfrapb.ComponentID]float32
+		var numInstances int
+		rowCount, progress, numInstances, err = backup(
+			ctx, execCtx, details, settings, defaultStore, resumer, latestManifest,
+		)
+		if err == nil {
+			return latestManifest, memSize, rowCount, numInstances, nil
+		}
+
+		if buildutil.CrdbTestBuild && (testKnobs == nil || !testKnobs.EnableBackupRetriesUnderTest) {
```
Comment (msbutler) [inline pkg/backup/backup_job.go]: according to claude the crdb binary created for roachtests randomly set crdbTestBuild on. let's monitor if this causes our backup roachtests to suddenly flake, and proceed from there.

File: pkg/backup/backup_job.go [hunk 4]
```diff
@@ -106,6 +106,139 @@ func filterSpans(includes []roachpb.Span, excludes []roachpb.Span) []roachpb.Spa
...
+			return nil, 0, roachpb.RowCount{}, 0, jobs.MarkAsRetryJobError(
+				errors.Wrapf(err, "backup job encountered retryable error on draining node"),
+			)
+		}
+
+		log.Dev.Warningf(ctx, "backup attempt %d failed with error: %+v", attempts, err)
+
+		mem.Shrink(ctx, memSize)
+		var readErr error
+		latestManifest, memSize, readErr = resumer.readManifestOnResume(
```
Comment (msbutler) [inline pkg/backup/backup_job.go:168]: i like that old comment, which explains why we need to reload the manifest.

File: pkg/backup/backup_test.go [hunk 5]
```diff
@@ -1612,60 +1612,109 @@ func TestBackupJobRetryReset(t *testing.T) {
...
 				defer mu.Unlock()
-				// Wait for at least 1% backup job progress, then continue sending retryable errors
-				<-waitForProgress
 				mu.retryCount++
-				// Send a retryable error
 				return syscall.ECONNRESET
 			},
+			// We include 1 additional attempt because the job will make progress,
+			// which adds one additional reset.
+			expectedAttempts: initialMaxRetries + secondaryMaxRetries + 2 + 1,
```
Comment (msbutler) [inline pkg/backup/backup_test.go:1696]: nice test! one clarification question-- i don't understand what the 2 + 1 is adding up here, given the commment.

**Review by msbutler — COMMENTED** [review]
Looks great! left a couple small comments

File: pkg/backup/backup_job.go (hunk 1 above)
Comment (kev-cao) [reply pkg/backup/backup_job.go:185]: Whenever `backup` returns a non-nil error, `numInstances` can be returned as 0.

File: pkg/backup/backup_job.go (hunk 3 above)
Comment (kev-cao) [reply pkg/backup/backup_job.go]: 🤔 I suppose since we're already checking `testKnobs.EnableBackupRetries` and it's an opt-in for tests, this isn't needed?

File: pkg/backup/backup_test.go (hunk 5 above)
Comment (kev-cao) [reply pkg/backup/backup_test.go:1696]: Oh I'll update the comment. It's because for `n` max retries, there will be `n + 1`attempts, so we have `(initialMaxRetries + 1) + (secondaryMaxRetries + 1) + 1`.

File: pkg/backup/backup_job.go (hunk 2 above)
Comment (kev-cao) [reply pkg/backup/backup_job.go]: Done

File: pkg/backup/backup_job.go [hunk 6]
```diff
@@ -106,6 +105,152 @@ func filterSpans(includes []roachpb.Span, excludes []roachpb.Span) []roachpb.Spa
...
+		secondaryState retryState = "secondary"
+	)
+
+	currState := initialState
+	initialPolicy, secondaryPolicy := getBackupRetryPolicies(execCtx.ExecCfg())
+	latestManifest = backupManifest
+
+	jobID := resumer.job.ID()
+	prevTotalProg := float32(0)
+	job, reloadErr := execCtx.ExecCfg().JobRegistry.LoadClaimedJob(ctx, jobID)
```
Comment (msbutler) [inline pkg/backup/backup_job.go]: could we simply use resumer.job.FractionCompleted() instead?

Comment (msbutler) [reply pkg/backup/backup_job.go]: it's slightly confusing to have two copies of `job` in memory.

File: pkg/backup/backup_job.go [hunk 7]
```diff
@@ -106,6 +105,152 @@ func filterSpans(includes []roachpb.Span, excludes []roachpb.Span) []roachpb.Spa
...
+		var numInstances int
+		rowCount, progress, numInstances, err = backup(
+			ctx, execCtx, details, settings, defaultStore, resumer, latestManifest,
+		)
+		if err == nil {
+			return latestManifest, memSize, rowCount, numInstances, nil
+		}
+
+		if testKnobs == nil || !testKnobs.EnableBackupRetriesUnderTest {
+			break
```
Comment (msbutler) [inline pkg/backup/backup_job.go:151]: wait, doesn't this mean we'll never exercise the retry policy in prod clusters, where `testKnobs == nil`? i think we do need that crdbtestbuild check.

Comment (kev-cao) [reply pkg/backup/backup_job.go:151]: Ugh yeah — I don't think with `buildutil.CRDBTestBuild` and `testKnobs` we have enough information to properly differentiate between prod binaries, Roachtest EA builds, and test runs.

I did poke around some more and found `bazel.InBazelTest`, which might do the trick? Gonna test this out to make sure this does what I think it does

Comment (kev-cao) [reply pkg/backup/backup_job.go:151]: Tested with a production binary, a test binary that was built with `-- --crdb_test`, and then our unit tests. Looks like `bazel.InBazelTest` is our saving grace here

Comment (msbutler) [reply pkg/backup/backup_job.go:151]: to step back, maybe we want our backup roachtests to fail quickly and keep the crdbTestBuild check? Like, if our backup roachtests are regularly hitting job level errors, we probably want to investigate?

Perhaps we should push this check to be after the IsDraining() check, so our mixed version tests don't keel over. thoughts?

Comment (kev-cao) [reply pkg/backup/backup_job.go:151]: I do see the appeal of having the roachtests fail quickly, but I also feel like our roachtests are one of our primary ways of more closely reflecting customer clusters in a testing environment. And given that, I think keeping the retry mechanism would be better aligned with that goal.

Comment (msbutler) [reply pkg/backup/backup_job.go:151]: yeah, thats a good point. our scale test should act like customer backups.

**Review by msbutler — APPROVED** [review]
LGTM!
