### PR TITLE
backupccl: allow backupRestoreTestSetup[Empty]WithParams to test within a tenant

### LINKED ISSUE #88381: backupccl: TestBackupRestoreDuringUserDefinedTypeChange panics within tenant
To reproduce, stress the test on top of https://github.com/cockroachdb/cockroach/pull/88271, with DisableTenantTestTenant set to false.

See test failure artifacts [here](https://teamcity.cockroachdb.com/viewLog.html?buildId=6543458&tab=buildResultsDiv&buildTypeId=Cockroach_BazelEssentialCi). 

Fresh build reveals more subtests hit the same panic: https://teamcity.cockroachdb.com/viewLog.html?buildId=6576285&buildTypeId=Cockroach_BazelEssentialCi

Jira issue: CRDB-19794

### PR DESCRIPTION
**Pull request by msbutler**
Previously, all backup unit tests that called backupRestoreTestSetupWithParams
and backupRestoreTestSetupEmptyWithParams were disabled to run within tenants,
signficantly decreasing test coverage.

This patch allows tests that call these helper methods to be probabilistically
run within tenants (including most data driven tests). This patch also manually
disables some of these tests to be run within tenants. Future work should
continue to enable bulk unit tests to run within tenants by default.

Fixes https://github.com/cockroachdb/cockroach/issues/88381, https://github.com/cockroachdb/cockroach/issues/88527, https://github.com/cockroachdb/cockroach/issues/88453, https://github.com/cockroachdb/cockroach/issues/88380
Release note: None

### CODE REVIEW

File: pkg/ccl/backupccl/backup_test.go [hunk 1]
```diff
@@ -7203,7 +7216,9 @@ func TestBackupExportRequestTimeout(t *testing.T) {
 
 	allowRequest := make(chan struct{})
 	defer close(allowRequest)
-	params := base.TestClusterArgs{}
+
```
Comment (msbutler) [inline pkg/ccl/backupccl/backup_test.go:7219]: nvm, I figured this flake out. Will amend the commit after this current CI run

File: pkg/ccl/backupccl/backup_test.go [hunk 2]
```diff
@@ -216,6 +216,7 @@ func TestBackupRestorePartitioned(t *testing.T) {
 	args := base.TestClusterArgs{
 		ServerArgsPerNode: map[int]base.TestServerArgs{
 			0: {
+				DisableDefaultTestTenant: true,
```
Comment (adityamaru) [inline pkg/ccl/backupccl/backup_test.go:219]: can we comment the reason on one of these disables, and if its something that we can overcome file a tracking issue that is mentioned in the comment?

File: pkg/ccl/backupccl/backup_test.go [hunk 3]
```diff
@@ -1498,6 +1501,9 @@ func TestBackupRestoreResume(t *testing.T) {
 
 	params := base.TestClusterArgs{ServerArgs: base.TestServerArgs{
 		Knobs: base.TestingKnobs{JobsTestingKnobs: jobs.NewTestingKnobsWithShortIntervals()},
+
+		// Cannot run this test within tenant because of the TestingGetPublicTableDescriptor func
```
Comment (adityamaru) [inline pkg/ccl/backupccl/backup_test.go:1505]: Is it because `TestingGetPublicTableDescriptor` doesn't take a codec? If so can we refactor it to. Otherwise lets add some more colour to this comment about what needs to change to enable this test.

File: pkg/ccl/backupccl/backup_test.go [hunk 4]
```diff
@@ -2638,6 +2645,9 @@ func TestBackupRestoreDuringUserDefinedTypeChange(t *testing.T) {
 				typeChangesFinished := make(chan struct{})
 				_, sqlDB, _, cleanupFn := backupRestoreTestSetupWithParams(t, singleNode, 0, InitManualReplication, base.TestClusterArgs{
 					ServerArgs: base.TestServerArgs{
+
+						// Disabled under tenant bc AddInStatement-schema-only subtest panicked.
```
Comment (adityamaru) [inline pkg/ccl/backupccl/backup_test.go:2649]: s/bc/because/g

Can you mention the issue you've opened to track the investigation of this here?

File: pkg/ccl/backupccl/backup_test.go [hunk 5]
```diff
@@ -6255,7 +6265,9 @@ func TestPaginatedBackupTenant(t *testing.T) {
 	withoutTS := hlc.Timestamp{}
 
 	const numAccounts = 1
-	serverArgs := base.TestServerArgs{Knobs: base.TestingKnobs{JobsTestingKnobs: jobs.NewTestingKnobsWithShortIntervals()}}
+	serverArgs := base.TestServerArgs{
+		Knobs:                    base.TestingKnobs{JobsTestingKnobs: jobs.NewTestingKnobsWithShortIntervals()},
+		DisableDefaultTestTenant: true}
```
Comment (adityamaru) [inline pkg/ccl/backupccl/backup_test.go:6270]: ditto as above, a short comment on why this is true since you've already spent the time investigating why.

File: pkg/ccl/backupccl/backup_test.go [hunk 6]
```diff
@@ -6729,8 +6741,9 @@ func TestBackupRestoreTenant(t *testing.T) {
 	defer log.Scope(t).Close(t)
 
 	params := base.TestClusterArgs{ServerArgs: base.TestServerArgs{
-		Knobs: base.TestingKnobs{JobsTestingKnobs: jobs.NewTestingKnobsWithShortIntervals()},
-	}}
+		Knobs:                    base.TestingKnobs{JobsTestingKnobs: jobs.NewTestingKnobsWithShortIntervals()},
+		DisableDefaultTestTenant: true},
```
Comment (adityamaru) [inline pkg/ccl/backupccl/backup_test.go:6745]: ditto

File: pkg/ccl/backupccl/backup_test.go [hunk 7]
```diff
@@ -8603,7 +8619,13 @@ func TestRestorePauseOnError(t *testing.T) {
 	defer jobs.TestingSetProgressThresholds()()
 
 	baseDir := "testdata"
-	args := base.TestServerArgs{ExternalIODir: baseDir, Knobs: base.TestingKnobs{JobsTestingKnobs: jobs.NewTestingKnobsWithShortIntervals()}}
+	args := base.TestServerArgs{
+		ExternalIODir: baseDir,
+
+		// Disabled to run within tenant because sometimes the job is in succeeeded
+		// state instead of paused.
+		DisableDefaultTestTenant: true,
```
Comment (adityamaru) [inline pkg/ccl/backupccl/backup_test.go:8627]: Hmm what does that have to do with running inside a tenant?

File: pkg/ccl/backupccl/backup_test.go [hunk 8]
```diff
@@ -9017,6 +9040,7 @@ func TestExcludeDataFromBackupAndRestore(t *testing.T) {
 	tc, sqlDB, iodir, cleanupFn := backupRestoreTestSetupWithParams(t, singleNode, 10,
 		InitManualReplication, base.TestClusterArgs{
 			ServerArgs: base.TestServerArgs{
+				DisableDefaultTestTenant: false,
```
Comment (adityamaru) [inline pkg/ccl/backupccl/backup_test.go:9043]: default is false, so can delete?

File: pkg/ccl/backupccl/backup_test.go [hunk 9]
```diff
@@ -9904,7 +9930,12 @@ func TestBackupRestoreTelemetryEvents(t *testing.T) {
 	defer jobs.TestingSetProgressThresholds()()
 
 	baseDir := "testdata"
-	args := base.TestServerArgs{ExternalIODir: baseDir, Knobs: base.TestingKnobs{JobsTestingKnobs: jobs.NewTestingKnobsWithShortIntervals()}}
+	args := base.TestServerArgs{
+		ExternalIODir: baseDir,
+
+		// Disabled to run within tenant because test can panic
+		DisableDefaultTestTenant: true,
```
Comment (adityamaru) [inline pkg/ccl/backupccl/backup_test.go:9937]: Can we file an issue, and mention it here so that we investigate it outside this PR.

File: pkg/ccl/backupccl/testdata/backup-restore/feature-flags [hunk 10]
```diff
@@ -1,6 +1,8 @@
 subtest backup-feature-flags
 
-new-server name=s1
+# disabeld for tenants as they can't enable/disable backup and restore features
```
Comment (adityamaru) [inline pkg/ccl/backupccl/testdata/backup-restore/feature-flags:3]: s/disabeld/disabled/g

File: pkg/ccl/backupccl/testdata/backup-restore/user-defined-functions [hunk 11]
```diff
@@ -180,31 +180,14 @@ query-sql
 WITH descs AS (
   SHOW BACKUP LATEST IN 'nodelocal://0/test/'
 )
-SELECT database_name, parent_schema_name, object_name, object_type, is_full_cluster FROM descs
+SELECT
```
Comment (adityamaru) [inline pkg/ccl/backupccl/testdata/backup-restore/user-defined-functions:183]: why did this change?

**Review by adityamaru — CHANGES_REQUESTED** [review]

File: pkg/ccl/backupccl/testdata/backup-restore/descriptor-conflicts [hunk 12]
```diff
@@ -3,8 +3,10 @@
 # appropriately during a cluster restore. The conflicting system tables in the
 # restoring cluster should be copied to a descriptor ID higher than any
 # descriptor in the backup.
+#
+# disabled for tenants because the create-dummy-system-table cmd cannot be run within a tenant
```
[the remark this answers is not in the document]
Comment (msbutler) [reply pkg/ccl/backupccl/testdata/backup-restore/descriptor-conflicts]: Initially, because of the codec, but i attempted to refactor the dd command to be MT friendly, but then ran into another snag. the following is not available to tenants
```
ALTER TABLE foo.bar.bat CONFIGURE ZONE USING gc.ttlseconds=999;
```

https://github.com/cockroachdb/cockroach/issues/49854?version=v22.2

File: pkg/ccl/backupccl/testdata/backup-restore/external-connections-nodelocal [hunk 13]
```diff
@@ -20,8 +20,14 @@ BACKUP INTO 'external://conn-foo/cluster';
...
 
 query-sql
-SELECT object_name, object_type, backup_type FROM [SHOW BACKUP LATEST IN
-'external://conn-foo/cluster'] ORDER BY object_name;
+SELECT
+  object_name, object_type, backup_type
+FROM
+ [SHOW BACKUP LATEST IN 'external://conn-foo/cluster']
+WHERE
+ object_name != 'tenant_settings'
```
[the remark this answers is not in the document]
Comment (msbutler) [reply pkg/ccl/backupccl/testdata/backup-restore/external-connections-nodelocal:29]: Done.

File: pkg/ccl/backupccl/testdata/backup-restore/feature-flags (hunk 10 above)
Comment (msbutler) [reply pkg/ccl/backupccl/testdata/backup-restore/feature-flags]: hard word to spell

File: pkg/ccl/backupccl/testdata/backup-restore/user-defined-functions (hunk 11 above)
Comment (msbutler) [reply pkg/ccl/backupccl/testdata/backup-restore/user-defined-functions:183]: got rid of the tenant_settings system table. I also don't think the test needed to show all these other rows anyway.

File: pkg/ccl/backupccl/utils_test.go [hunk 14]
```diff
@@ -188,7 +178,6 @@ func createEmptyCluster(
 	params.ServerArgs.ExternalIODir = dir
 	// Disabling the default test tenant due to test failures. More
```
[the remark this answers is not in the document]
Comment (msbutler) [reply pkg/ccl/backupccl/utils_test.go]: Done.

**Review by msbutler — COMMENTED** [review]
RFAL!

File: pkg/ccl/backupccl/backup_test.go [hunk 15]
```diff
@@ -9678,6 +9711,7 @@ func TestBackupNoOverwriteCheckpoint(t *testing.T) {
 		},
 	}
 	params.ServerArgs.Knobs = knobs
+	params.ServerArgs.DisableDefaultTestTenant = true
```
Comment (stevendanna) [inline pkg/ccl/backupccl/backup_test.go:9714]: This test has at 2 problems:

1) It accesses `tc.Server(0).ExecutorConfig().(sql.ExecutorConfig)` in order to look up the userfile we are writing to.  Locally, I've added a `tc.TenantOrServer(0)` method that returns the correct TestTenantInterface which can be used to resolve the issue.

2) It looks like when we start the test tenant, we don't copy over the  testing knobs.  If I locally add some code to copy over a few of the relevant testing knobs, the test passes.

File: pkg/ccl/backupccl/backup_test.go [hunk 16]
```diff
@@ -1502,13 +1502,23 @@ func TestBackupRestoreResume(t *testing.T) {
...
 	defer cleanupFn()
-
-	backupTableDesc := desctestutils.TestingGetPublicTableDescriptor(tc.Servers[0].DB(), keys.SystemSQLCodec, "data", "bank")
+	codec := keys.SystemSQLCodec
+	testTenants := tc.Servers[0].TestTenants()
+	clusterID := tc.Servers[0].RPCContext().LogicalClusterID.Get()
+	if len(testTenants) > 0 {
+		codec = keys.MakeSQLCodec(testTenants[0].RPCContext().TenantID)
+		clusterID = testTenants[0].RPCContext().LogicalClusterID.Get()
+	}
```
Comment (stevendanna) [inline pkg/ccl/backupccl/backup_test.go:1520]: Locally, I've added:

```
func (tc *TestCluster) TenantOrServer(idx int) serverutils.TestTenantInterface {
	s := tc.Server(idx)
	if tc.StartedDefaultTestTenant() {
		return s.TestTenants()[0]
	}
	return s
}
```

which might be a nice addition to make this a bit cleaner throughout the tests.

**Comment by stevendanna** [comment]
https://github.com/cockroachdb/cockroach/pull/88557 might help for some of the tests that aren't working because of testing hooks.

**Comment by msbutler** [comment]
RFAL!

**Comment by msbutler** [comment]
@stevendanna friendly ping on this!

**Review by adityamaru — APPROVED** [review]
LGTM to merge as a first step as we tackle the remaining TODOs and skips. Nice work!

File: pkg/ccl/backupccl/backup_test.go [hunk 17]
```diff
@@ -1501,14 +1505,17 @@ func TestBackupRestoreResume(t *testing.T) {
 	ctx := context.Background()
 
 	params := base.TestClusterArgs{ServerArgs: base.TestServerArgs{
-		Knobs: base.TestingKnobs{JobsTestingKnobs: jobs.NewTestingKnobsWithShortIntervals()},
+		DisableDefaultTestTenant: true,
```
[the remark this answers is not in the document]
Comment (msbutler) [reply pkg/ccl/backupccl/backup_test.go]: woops. removed! Seems to work locally within tenants.

**Comment by adityamaru** [comment]
@msbutler seeing TestDataDriven get pretty flaky and I suspect its this PR - https://teamcity.cockroachdb.com/viewLog.html?buildId=7032391&tab=buildResultsDiv&buildTypeId=Cockroach_Ci_TestsAwsLinuxArm64_UnitTests

**Comment by adityamaru** [comment]
Flaky behaviour started around 1300 today https://teamcity.cockroachdb.com/project.html?projectId=Cockroach_Ci_TestsAwsLinuxArm64BigVm&testNameId=-4898685845226892981&tab=testDetails&branch_Cockroach_Ci_TestsAwsLinuxArm64BigVm=%3Cdefault%3E which roughly lines up with when this was merged. Looks like when run as a tenant the DD test is timing out the package.

**Comment by msbutler** [comment]
hmmm, i'll try stressing the DD test with MT on my gce worker to see if anything shakes out.
