### PR TITLE
testserver,testtenant: fix `SQLConn()`

### LINKED ISSUE #107859: configprofiles: TestDataDriven failed
Epic: CRDB-18499

configprofiles.TestDataDriven [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_StressBazel/11116118?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_StressBazel/11116118?buildTab=artifacts#/) on master @ [f295bd861a3a427652b19c2254d2401ebb4a3c8e](https://github.com/cockroachdb/cockroach/commits/f295bd861a3a427652b19c2254d2401ebb4a3c8e):

```
=== RUN   TestDataDriven
    test_log_scope.go:167: test logs captured to: /artifacts/tmp/_tmp/f07519a9a253a7694f6e67cf7554fe40/logTestDataDriven252320693
    test_log_scope.go:81: use -show-logs to present logs inline
=== CONT  TestDataDriven
    datadriven_test.go:132: -- test log scope end --
test logs left over in: /artifacts/tmp/_tmp/f07519a9a253a7694f6e67cf7554fe40/logTestDataDriven252320693
--- FAIL: TestDataDriven (209.06s)
=== RUN   TestDataDriven/virtual-app-repl
    datadriven_test.go:84: condition failed to evaluate within 45s: expected 6 tasks to be completed, got 0
    --- FAIL: TestDataDriven/virtual-app-repl (62.77s)
=== RUN   TestDataDriven/replication-source
    datadriven_test.go:84: condition failed to evaluate within 45s: expected 6 tasks to be completed, got 0
    --- FAIL: TestDataDriven/replication-source (62.54s)
```
<p>Parameters: <code>TAGS=bazel,gss,deadlock</code>
, <code>stress=true</code>
</p>
<details><summary>Help</summary>
<p>

See also: [How To Investigate a Go Test Failure \(internal\)](https://cockroachlabs.atlassian.net/l/c/HgfXfJgM)
</p>
</details>
/cc @cockroachdb/multi-tenant @cockroachdb/server
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*TestDataDriven.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)
</sub>

Jira issue: CRDB-30225

### PR DESCRIPTION
**Pull request by knz**
Fixes #107859.
Epic: CRDB-18499

Prior to this patch, the (recently introduced) `SQLConn()` method was blind to the concept of a shared SQL port where connections get redirected to a secondary tenant based on the `cluster` URL option.

Because of this, two bad things were happening:

- `.SQLConn()` on the `ApplicationLayerInterface` of a secondary tenant with a shared SQL port would fail to connect to the right tenant.

- `.SystemLayer().SQLConn()` would fail if the cluster setting `server.controller.default_tenant` was set.

This patch fixes it.

Release note: None

### CODE REVIEW

File: pkg/server/server_controller_test.go [hunk 1]
```diff
@@ -109,3 +112,48 @@ func TestSharedProcessServerInheritsTempStorageLimit(t *testing.T) {
...
+// TestServerSQLConn checks that the SQLConn() method on the
+// SystemLayer() of TestServerInterface works even when non-specific
+// SQL connection requests are redirected to a secondary tenant.
+func TestServerSQLConn(t *testing.T) {
+	defer leaktest.AfterTest(t)()
+	defer log.Scope(t).Close(t)
+
+	const specialSize = 123123123
+
+	// Start a server with a custom temp storage limit.
```
Comment (stevendanna) [inline pkg/server/server_controller_test.go:125]: I think this is some cruft from another test?

File: pkg/server/testserver_sqlconn.go [hunk 2]
```diff
@@ -53,13 +56,19 @@ func openTestSQLConn(
 	cleanupFn := func() {}
 	var goDB *gosql.DB
 
+	opts := url.Values{}
+	if tenantName != "" {
+		opts.Add("options", fmt.Sprintf("-ccluster=%s", tenantName))
+	}
+
```
Comment (stevendanna) [inline pkg/server/testserver_sqlconn.go:63]: I could see lifting sslmode up here behind something like `if useLoopbackListner || insecure {`, but I leave that style choice to you.

**Review by stevendanna — APPROVED** [review]

**Review by knz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/108442)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @DarrylWong, @rachitgsrivastava, @stevendanna, and @yuzefovich)

___
*[`pkg/server/testserver_sqlconn.go` line 63 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/108442#gh-1288612258:-NbPtBLM60H9A7Whgucs:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/593596d8f272784fc480b57c8819e913ae28de64/pkg/server/testserver_sqlconn.go#L63)):*
<details><summary><i>Previously, stevendanna (Steven Danna) wrote…</i></summary><blockquote>

I could see lifting sslmode up here behind something like `if useLoopbackListner || insecure {`, but I leave that style choice to you.
</blockquote></details>

Done.
___
*[`pkg/server/server_controller_test.go` line 125 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/108442#gh-1288598971:-NbPtBq3As5xa9st2fi0:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/593596d8f272784fc480b57c8819e913ae28de64/pkg/server/server_controller_test.go#L125)):*
<details><summary><i>Previously, stevendanna (Steven Danna) wrote…</i></summary><blockquote>

I think this is some cruft from another test?
</blockquote></details>

Done.

**Comment by knz** [comment]
TFYR!

bors r=stevendanna
