### PR TITLE
cli: fix default log-dir logic

### LINKED ISSUE #4527: cli: allow setting --log-dir=${TMPDIR} for `cockroach start`
#4505 changed the `cockroach start` command to default the log directory to the "logs" subdirectory of the first store. The implementation isn't quite correct as it looks at the log-dir flag to see if it has changed from the default of "${TMPDIR}". But this implementation means you can't actually set `--log-dir=${TMPDIR}`. The fix is straightforward, instead of default `--log-dir` to `${TMPDIR}` we should default it to some other invalid value (e.g. perhaps the actual string `${TMPDIR}`) and then in an `OnInitialize` hook set the value to `os.TempDir()` if it hasn't changed.

### PR DESCRIPTION
**Pull request by petermattis**
Fixes #4527.

[Review on Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/4639)

### CODE REVIEW

File: util/log/file.go [hunk 1]
```diff
@@ -38,9 +39,41 @@ import (
 // MaxSize is the maximum size of a log file in bytes.
 var MaxSize uint64 = 1024 * 1024 * 10
 
-// If non-empty, overrides the choice of directory in which to write logs.
-// See createLogDirs for the full list of possible destinations.
-var logDir *string
```
Comment (petermattis) [inline util/log/file.go]: Switch `logDir` from a pointer to a value was unrelated to the rest of this change. Don't beat me up over it. The reason it was a pointer was a hold over from when this was initialized by the glog package as `var logDir = flag.String(...)`.

File: util/log/file.go [hunk 2]
```diff
@@ -38,9 +39,41 @@ import (
...
+var logDir = os.TempDir()
+var logDirSet bool
+
+// DirSet returns true of the log directory has been changed from its default.
+func DirSet() bool {
+	return logDirSet
+}
+
+type stringValue struct {
+	val *string
```
Comment (BramGruneir) [inline util/log/file.go]: Is there a reason why these need to be pointers?

File: util/log/file.go [hunk 3]
```diff
@@ -38,9 +39,41 @@ import (
...
+	set *bool
+}
+
+var _ flag.Value = &stringValue{}
+
+func newStringValue(val *string, set *bool) *stringValue {
+	return &stringValue{val: val, set: set}
+}
+
+func (s *stringValue) Set(val string) error {
```
Comment (BramGruneir) [inline util/log/file.go]: So the need to create the newStringValue is entirely for the `set`.  Why can't just detect a blank instead of adding these types?

File: util/log/file.go (hunk 2 above)
Comment (petermattis) [inline util/log/file.go]: Yes, because we want to modify `logDir`.

File: util/log/file.go (hunk 3 above)
Comment (petermattis) [inline util/log/file.go]: Detect a blank what? I'm not understanding your suggestion. 

Note that this isn't performance critical code. I was just doing what seemed convenient.

Comment (BramGruneir) [inline util/log/file.go]: Using a StringVar instead, with a default of "" and when consuming the flag just look for the empty string instead of adding in the extra logic.

Comment (petermattis) [inline util/log/file.go]: I haven't figured out how to do that. This is complicated by us wanting a different default for the `start` command vs other commands.

File: util/log/file.go [hunk 4]
```diff
@@ -38,9 +39,41 @@ import (
...
+// default is to log to stderr independent of this setting. See --logtostderr.
+var logDir = os.TempDir()
+var logDirSet bool
+
+// DirSet returns true of the log directory has been changed from its default.
+func DirSet() bool {
+	return logDirSet
+}
+
+type stringValue struct {
```
Comment (BramGruneir) [inline util/log/file.go]: Perhaps we should start moving these custom flag values to their own package, cli/flags or something like that.  StoreSpec is in server, this one is here.  Might be better to keep them together.
(not for this PR, but a subsequent one)

**Comment by BramGruneir** [comment]
LGTM
