### PR TITLE
server: add more info to max-go-limit warning

### LINKED ISSUE #130195: include --cache value in the error: WARNING: recommended default value of --max-go-memory (129Gib) was truncated to 88GiB, consider reducing --max-sql-memory and/or --cache
**Describe the problem**

Please describe the issue you observed, and any steps we can take to reproduce it:

IHAC that has a cluster with 230gb of ram per node, 45% for max-sql-memory and 25% for cache.  When they do this they get a warning in the logs
`WARNING: recommended default value of --max-go-memory (129Gib) was truncated to 88GiB, consider reducing --max-sql-memory and/or --cache`

**To Reproduce**

What did you do? Describe in your own words.

If possible, provide steps to reproduce the behavior:

Start a cluster where nodes have 230gb of memory and --max-go-memory is set to 45% and --cache is set to 25%

**Expected behavior**
We don't understand why the max-go-memory was truncated to 88GiB

**Additional data / screenshots**
If the problem is SQL-related, include a copy of the SQL query and the schema
of the supporting tables.

If a node in your cluster encountered a fatal error, supply the contents of the
log directories (at minimum of the affected node(s), but preferably all nodes).

Note that log files can contain confidential information. Please continue
creating this issue, but contact support@cockroachlabs.com to submit the log
files in private.

**Environment:**
 - CockroachDB version 23.1.19
 - Server OS: k8s

**Additional context**
What was the impact?

Customer has upgraded a cluster from 22.2 to 23.1.  Since then they started getting a message in their logs about the value of max-go-memory being truncated.  WARNING: recommended default value of --max-go-memory (129Gib) was truncated to 88GiB, consider reducing --max-sql-memory and/or --cache  There are no performance issues at this time and recently a review of the cluster was done and found it to be healthy.  These nodes have 230gb of ram.  They are wondering why this message began to pop up post 23.1 and what (if anything) should be done about it.

Jira issue: CRDB-41918

### PR DESCRIPTION
**Pull request by RaduBerinde**
Add the sql memory, cache size, and total memory to the warning issued
when `--max-go-memory` is clamped.

Fixes #130195

### CODE REVIEW

File: pkg/cli/start.go [hunk 1]
```diff
@@ -744,8 +744,10 @@ func getDefaultGoMemLimit(ctx context.Context) int64 {
 		log.Ops.Shoutf(
 			ctx, severity.WARNING, "recommended default value of "+
 				"--max-go-memory (%s) was truncated to %s, consider reducing "+
-				"--max-sql-memory and / or --cache",
+				"--max-sql-memory (%s) and / or --cache (%s); total system/cgroup memory: %s.",
```
Comment (tbg) [inline pkg/cli/start.go:747]: The args are swapped - you want the memory pool size first (since that's the sql mem according to line line 739 above), then `serverCfg.CacheSize` since that's the `--cache`, then `sysMem`.

**Review by tbg — CHANGES_REQUESTED** [review]

File: pkg/cli/start.go (hunk 1 above)
Comment (RaduBerinde) [reply pkg/cli/start.go:747]: Good catch, thanks!

**Comment by RaduBerinde** [comment]
@tbg mind stamping with an approval when you get a chance?

**Review by tbg — APPROVED** [review]
bors r+
