### PR TITLE
kvserver: attempt to deflake TestReplicaRangefeedErrors

### LINKED ISSUE #146566: kv/kvserver: TestReplicaRangefeedErrors failed
kv/kvserver.TestReplicaRangefeedErrors [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Ci_TestsAwsLinuxArm64_UnitTests/19669962?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Ci_TestsAwsLinuxArm64_UnitTests/19669962?buildTab=artifacts#/) on master @ [3610c794fff407cecd39f1c20846458e736bb8ab](https://github.com/cockroachdb/cockroach/commits/3610c794fff407cecd39f1c20846458e736bb8ab):

```
=== RUN   TestReplicaRangefeedErrors
    test_log_scope.go:165: test logs captured to: /artifacts/tmp/_tmp/52df76b8c5cd210f55c7615cbcf3fcbc/logTestReplicaRangefeedErrors1576791634
    test_log_scope.go:76: use -show-logs to present logs inline
    replica_rangefeed_test.go:1259: -- test log scope end --
test logs left over in: /artifacts/tmp/_tmp/52df76b8c5cd210f55c7615cbcf3fcbc/logTestReplicaRangefeedErrors1576791634
--- FAIL: TestReplicaRangefeedErrors (25.56s)
=== RUN   TestReplicaRangefeedErrors/REASON_LOGICAL_OPS_MISSING
    replica_rangefeed_test.go:1133: unexpected error from stream: retry rangefeed (REASON_LOGICAL_OPS_MISSING)
--- FAIL: TestReplicaRangefeedErrors/REASON_LOGICAL_OPS_MISSING (3.65s)
```
<details><summary>Help</summary>
<p>

See also: [How To Investigate a Go Test Failure \(internal\)](https://cockroachlabs.atlassian.net/l/c/HgfXfJgM)
</p>
</details>
/cc @cockroachdb/kv-triage
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*TestReplicaRangefeedErrors.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/bazci/githubpost/issues)

</sub>

Jira issue: CRDB-50598

### PR DESCRIPTION
**Pull request by miraradeva**
This test has been failing with `REASON_LOGICAL_OPS_MISSING` (#146566) coming from `waitForInitialCheckpointAcrossSpan`, which could indicate that some other request is racing with the enabling of the rangefeed and hitting an error in `handleLogicalOpLogRaftMuLocked`.

To help debug this, this commit intercepts and logs all requests to the specific test range. Additionally, the test range is modified to be a single key, to further prevent other writes from interfering with the test.

Fixes: #146566

Release note: None

### CODE REVIEW

**Review by stevendanna — APPROVED** [review]

File: pkg/kv/kvserver/replica_rangefeed_test.go [hunk 1]
```diff
@@ -1094,6 +1094,21 @@ func TestReplicaRangefeedErrors(t *testing.T) {
...
+				// This test has been failing with REASON_LOGICAL_OPS_MISSING (#146566)
+				// coming from waitForInitialCheckpointAcrossSpan, which could indicate
+				// that some other request to this range is racing with the enabling of
+				// the rangefeed and hitting an error in handleLogicalOpLogRaftMuLocked.
+				// To help debug this, we intercept all requests to this range. If the
+				// test stops flaking, we can remove this filter; it's not needed for
+				// the test functionality.
+				TestingRequestFilter: func(ctx context.Context, ba *kvpb.BatchRequest) *kvpb.Error {
+					for _, req := range ba.Requests {
+						if req.GetInner().Header().Key.Equal(startKey) {
```
[the remark this answers is not in the document]
Comment (miraradeva) [reply pkg/kv/kvserver/replica_rangefeed_test.go:1106]: This is a single-key range, so this should be sufficient, right?

**Comment by miraradeva** [comment]
Conveniently, it failed in CI. If only it was easy to find the artifacts ...

**Comment by stevendanna** [comment]
https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Ci_Tests_MaybeStressrace/19701131?buildTab=artifacts#%2Ftmp%2F_tmp%2F33e1d369c27b9c01b2b6009c561815a3%2FlogTestReplicaRangefeedErrors1672235491

**Comment by miraradeva** [comment]
@stevendanna ignoring the error seems to have done the trick, at least in this CI run. Do we want to keep the debug request logging, or remove it? I think keeping the range to a single key is a good idea regardless.

File: pkg/kv/kvserver/replica_rangefeed_test.go [hunk 2]
```diff
@@ -774,25 +774,43 @@ func TestReplicaRangefeedErrors(t *testing.T) {
...
+		}
+		if rfErr.Reason != expReason {
+			t.Fatalf("got incorrect RangeFeedRetryError reason for RangeFeed: %v; expecting %v",
+				rfErr.Reason, expReason)
+		}
+	}
+
 	waitForInitialCheckpointAcrossSpan := func(
 		t *testing.T, stream *testStream, streamErrC <-chan error, span roachpb.Span,
 	) {
```
Comment (stevendanna) [inline pkg/kv/kvserver/replica_rangefeed_test.go:797]: What do you feel about this function taking an `*kvpb.RangeFeedRetryError_Reason` argument. Callers that expect no error could pass nil, and then we could pass REASON_LOGICAL_OPS_MISSING in the one test that expect this.

I think that this function might be some sort of return argument as well to indicate it got the expected error since at this point the stream we started is dead and we probably want to skip the rest of the function.

Comment (miraradeva) [reply pkg/kv/kvserver/replica_rangefeed_test.go]: > What do you feel about this function taking an *kvpb.RangeFeedRetryError_Reason argument. Callers that expect no error could pass nil, and then we could pass REASON_LOGICAL_OPS_MISSING in the one test that expect this.

Good idea. Done.

> I think that this function might be some sort of return argument as well to indicate it got the expected error since at this point the stream we started is dead and we probably want to skip the rest of the function.

Currently, it fatals the test if it hits an unexpected error. And it did so before this change too. That's probably fine, right?

**Comment by miraradeva** [comment]
bors r=stevendanna
