### PR TITLE
sql: dump puts INTERLEAVE statements outside of CREATE TABLE statements

### LINKED ISSUE #35462: cli/dump: `cockroach dump` produces unrestorable output for `CREATE TABLE` statements with interleaved indices
Interleaved indices can't be added as part of a `CREATE TABLE` statement; this is a known limitation tracked by #9148. However, `cockroach dump` is unaware of this limitation: if you dump a table with an interleaved index, the index is emitted inline in the `CREATE TABLE`. This produces dump files that can't be restored without manual editing.

In the past we've made changes to `ShowCreateTable` and the `crdb_internal` table to produce usable `CREATE TABLE` statements in dumps (see https://github.com/cockroachdb/cockroach/commit/65c0bfbd64ca6d92ac3d2c655415a0d1433586d6). To solve this issue we either need to fix the root cause (#9148) or make another change to the dump logic to add interleaved indices after table creation instead of in the `CREATE TABLE`.

Relates to #28948 (master issue of `cockroach dump` inadequacies).

The manual edit you have to make: change
```
CREATE TABLE t (
  somecolumndef,
  somecolumndef,
  somecolumndef,
  INDEX i (somecolumndef, somecolumndef) INTERLEAVE IN PARENT t (somecolumndef)
);
```
into
```
CREATE TABLE t (
  somecolumndef,
  somecolumndef,
  somecolumndef
);
CREATE INDEX i (somecolumndef, somecolumndef) INTERLEAVE IN PARENT t (somecolumndef);

```

Full repro on a 19.1 build:
<details>
<summary>Repro steps</summary>

```
root@:26257/test> create table t1 (a int, b int, primary key (a));
CREATE TABLE

Time: 17.7833ms

root@:26257/test> create index b_idx on t1(a, b) interleave in parent t1 (a);
CREATE INDEX

Time: 191.1104ms

root@:26257/test> show create table t1;
  table_name |                      create_statement
+------------+-------------------------------------------------------------+
  t1         | CREATE TABLE t1 (
             |     a INT8 NOT NULL,
             |     b INT8 NULL,
             |     CONSTRAINT "primary" PRIMARY KEY (a ASC),
             |     INDEX b_idx (a ASC, b ASC) INTERLEAVE IN PARENT t1 (a),
             |     FAMILY "primary" (a, b)
             | )
(1 row)

Time: 4.2069ms

root@:26257/test> \q
PS C:\Users\roland\Desktop> cockroach-20190211.exe dump --insecure test
CREATE TABLE t1 (
        a INT8 NOT NULL,
        b INT8 NULL,
        CONSTRAINT "primary" PRIMARY KEY (a ASC),
        INDEX b_idx (a ASC, b ASC) INTERLEAVE IN PARENT t1 (a),
        FAMILY "primary" (a, b)
);
PS C:\Users\roland\Desktop> cockroach-20190211.exe sql --insecure
# Welcome to the cockroach SQL interface.
# All statements must be terminated by a semicolon.
# To exit: CTRL + D.
#
# Server version: CockroachDB CCL v2.2.0-alpha.20190211 (x86_64-w64-mingw32, built 2019/02/07 23:54:03, go1.11.4) (same version as client)
# Cluster ID: cf81eacb-45cd-4cfe-8113-6b1ea1f2f744
#
# Enter \? for a brief introduction.
#
root@:26257/defaultdb> create database test2; use test2;
SET

Time: 16.5387ms

root@:26257/test2> CREATE TABLE t1 (
                ->         a INT8 NOT NULL,
                ->         b INT8 NULL,
                ->         CONSTRAINT "primary" PRIMARY KEY (a ASC),
                ->         INDEX b_idx (a ASC, b ASC) INTERLEAVE IN PARENT t1 (a),
                ->         FAMILY "primary" (a, b)
                -> );
pq: unimplemented: use CREATE INDEX to make interleaved indexes
HINT: See: https://github.com/cockroachdb/cockroach/issues/9148
root@:26257/test2>
```
</details>

### PR DESCRIPTION
**Pull request by tyler314**
Fix bug where dump would include INTERLEAVE IN PARENT statements inside
of CREATE TABLE statements. CRDB currently does not support this, thus
forcing the user to manually edit the dump files to remove the
INTERLEAVE statements themselves.

Previousily, crdb_internal.go would use show_create.go to create the
SHOW CREATE TABLE statements which would include INTERLEAVE.
crdb_internal.go would also add ALTER STATEMENTs separately to the
alter_statements of the create statements of the table. This change
removes the addition of the INTERLEAVE within show_create.go, and
included the additon of adding the INTERLEAVE statements to the
alter_statements within crdb_internal.go.

A bug was also fixed in structured.go in the SQLString method that
created the SQL string out of order when a non-empty table name is
passed in. The bug caused the "ON tablename" to be printed before
the index and without space in between the two.

Resolves: #35462

Release Note (bug fix): dump now works properly when handling
INTERLEAVED tables, printing them outside of CREATE TABLE statements.

### CODE REVIEW

**Review by thoszhang — COMMENTED** [review]
This PR only affects interleaved secondary indexes (not interleaved "tables"/primary keys), right?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/39486#-:-Lm5rH5cCj7kLsf2rMm6:b4jovfy)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dt, @lucy-zhang, and @tyleroberts)

___
*[pkg/base/addr_validation_test.go, line 67 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/39486#-Lm5rkjl0Bvco3nLY9m0:-Lm5rkjl0Bvco3nLY9m1:bzbe37d) ([raw file](https://github.com/cockroachdb/cockroach/blob/fa685c8fda5d9ba95e77ac86ac25cafc23dc1b15/pkg/base/addr_validation_test.go#L67)):*
> ```Go
> 	// below, but before we test anything we need to ensure we indeed have
> 	// a reliably non-resolvable host name.
> 	var derp []net.IPAddr
> ```

What is this for?
___
*[pkg/sql/show_create.go, line 206 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/39486#-Lm5r3F7EcG4v6axLCnz:-Lm5r3F7EcG4v6axLCo-:bplo60z) ([raw file](https://github.com/cockroachdb/cockroach/blob/fa685c8fda5d9ba95e77ac86ac25cafc23dc1b15/pkg/sql/show_create.go#L206)):*
> ```Go
> 		// Only add indexes to CREATE TABLE statement if they are not associated
> 		// with an INTERLEAVE statement.
> 		if idx.ID != desc.PrimaryIndex.ID && len(idx.Interleave.Ancestors) == 0 {
> ```

Does this remove all interleaved secondary indexes from the output of `SHOW CREATE TABLE` entirely?

**Review by dt — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/39486)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dt, @lucy-zhang, and @tyleroberts)

___
*[pkg/sql/show_create.go, line 206 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/39486#-Lm5r3F7EcG4v6axLCnz:-Lm6B27Q-FdNr0q1W310:b-x0zbn8) ([raw file](https://github.com/cockroachdb/cockroach/blob/fa685c8fda5d9ba95e77ac86ac25cafc23dc1b15/pkg/sql/show_create.go#L206)):*
<details><summary><i>Previously, lucy-zhang (Lucy Zhang) wrote…</i></summary><blockquote>

Does this remove all interleaved secondary indexes from the output of `SHOW CREATE TABLE` entirely?
</blockquote></details>

Yeah, 
___
*[pkg/sql/show_create_test.go, line 37 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/39486#-Lm6B7H41P-TVxhGbiQY:-Lm6B7H41P-TVxhGbiQZ:b-nlwbm6) ([raw file](https://github.com/cockroachdb/cockroach/blob/95968ee8e14a577e3557e1bf731fafbd6dd5c3b1/pkg/sql/show_create_test.go#L37)):*
> ```Go
> 			CONSTRAINT "primary" PRIMARY KEY (id ASC),
> 			CONSTRAINT fk FOREIGN KEY (status) REFERENCES "[52 as ref]"("???"),
> 			INDEX jobs_status_created_idx (status ASC, created ASC) INTERLEAVE IN PARENT "[51 as parent]" (status),
> ```

yeah, this is not what we wanted -- we wanted to elide these _only_ in the nofks internal field, not the user-visible one.

**Review by tyler314 — COMMENTED** [review]
This also affects interleaved tables. It removes them from the CREATE TABLE statement and puts them outside in their own separate statements.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/39486#-:-Lm6E9Pi6hOtcnJ_A67O:bhwujxs)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dt and @lucy-zhang)

___
*[pkg/base/addr_validation_test.go, line 67 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/39486#-Lm5rkjl0Bvco3nLY9m0:-Lm5tTkM398fd7eeanJu:b-7c9aqg) ([raw file](https://github.com/cockroachdb/cockroach/blob/fa685c8fda5d9ba95e77ac86ac25cafc23dc1b15/pkg/base/addr_validation_test.go#L67)):*
<details><summary><i>Previously, lucy-zhang (Lucy Zhang) wrote…</i></summary><blockquote>

What is this for?
</blockquote></details>

This was something I added when I was getting an error with `make test`, I should not have committed it.
___
*[pkg/sql/show_create.go, line 206 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/39486#-Lm5r3F7EcG4v6axLCnz:-Lm6wuMf1pZWdjaTcgHB:b-azt6kc) ([raw file](https://github.com/cockroachdb/cockroach/blob/fa685c8fda5d9ba95e77ac86ac25cafc23dc1b15/pkg/sql/show_create.go#L206)):*
<details><summary><i>Previously, dt (David Taylor) wrote…</i></summary><blockquote>

Yeah, 
</blockquote></details>

Not entirely. It does remove it from the CREATE TABLE statement, but includes the INTERLEAVE statement just outside the CREATE TABLE statement. So for example, if we have these two statements:
```
CREATE TABLE t1 (
	a INT8 NOT NULL,
	b INT8 NULL,
	CONSTRAINT "primary" PRIMARY KEY (a ASC),
	FAMILY "primary" (a, b)
);

CREATE INDEX b_idx ON t1 (a ASC, b ASC) INTERLEAVE IN PARENT t1 (a);
```

A SHOW CREATE TABLE would return the following:
```
CREATE TABLE orders (
	customer INT8 NOT NULL,
	id INT8 NOT NULL,
	total DECIMAL(20,5) NULL,
	CONSTRAINT "primary" PRIMARY KEY (customer ASC, id ASC),
	FAMILY "primary" (customer, id, total)
) INTERLEAVE IN PARENT customers (customer);
```

As demonstrated in `TestDumpInterleaved` in `dump_test.go`.
___
*[pkg/sql/show_create_test.go, line 37 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/39486#-Lm6B7H41P-TVxhGbiQY:-Lm6wn3w-jF6y7hw42mH:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/95968ee8e14a577e3557e1bf731fafbd6dd5c3b1/pkg/sql/show_create_test.go#L37)):*
<details><summary><i>Previously, dt (David Taylor) wrote…</i></summary><blockquote>

yeah, this is not what we wanted -- we wanted to elide these _only_ in the nofks internal field, not the user-visible one.
</blockquote></details>

Done.

**Review by thoszhang — COMMENTED** [review]
> This also affects interleaved tables. It removes them from the CREATE TABLE statement and puts them outside in their own separate statements.

Maybe I'm wrong about how interleaving works (I couldn't actually find much about interleaved indexes in the docs), but my understanding was that there are two types of interleaving:

1. Interleaved tables: This is accomplished by `CREATE TABLE ... INTERLEAVE IN PARENT ...`, and interleaves the primary key into another table.
2. Interleaved secondary indexes: This is accomplished by `CREATE INDEX ... INTERLEAVE IN PARENT ...`, and interleaves the secondary index into another table. The problem is that we don't support the `CREATE TABLE ... (INDEX ... INTERLEAVE IN PARENT)` syntax for this when creating a table.

The behavior for interleaved _tables_ should be the same as before, right? In the tests, it looks like the `CREATE TABLE ... INTERLEAVE IN PARENT ...` statements are the same. Am I missing something?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/39486#-:-Lm77j2j8zDmzyCyjSbd:b-tae8k9)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dt, @lucy-zhang, and @tyleroberts)

___
*[pkg/cli/dump_test.go, line 454 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/39486#-Lm77TUv7awqj9tDHcV1:-Lm77TUv7awqj9tDHcV2:b-z97979) ([raw file](https://github.com/cockroachdb/cockroach/blob/5d3607f756f051825dbce70792c383df9c4bb3a0/pkg/cli/dump_test.go#L454)):*
> ```Go
> 
> 	const create = `
> 	CREATE DATABASE d;
> ```

nit: can you fix the formatting/indentation for these statements?
___
*[pkg/sql/show_create.go, line 206 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/39486#-Lm5r3F7EcG4v6axLCnz:-Lm75PzN85bUE_2tHIVR:b-a882r8) ([raw file](https://github.com/cockroachdb/cockroach/blob/fa685c8fda5d9ba95e77ac86ac25cafc23dc1b15/pkg/sql/show_create.go#L206)):*
<details><summary><i>Previously, tyleroberts (Tyler Roberts) wrote…</i></summary><blockquote>

Not entirely. It does remove it from the CREATE TABLE statement, but includes the INTERLEAVE statement just outside the CREATE TABLE statement. So for example, if we have these two statements:
```
CREATE TABLE t1 (
	a INT8 NOT NULL,
	b INT8 NULL,
	CONSTRAINT "primary" PRIMARY KEY (a ASC),
	FAMILY "primary" (a, b)
);

CREATE INDEX b_idx ON t1 (a ASC, b ASC) INTERLEAVE IN PARENT t1 (a);
```

A SHOW CREATE TABLE would return the following:
```
CREATE TABLE orders (
	customer INT8 NOT NULL,
	id INT8 NOT NULL,
	total DECIMAL(20,5) NULL,
	CONSTRAINT "primary" PRIMARY KEY (customer ASC, id ASC),
	FAMILY "primary" (customer, id, total)
) INTERLEAVE IN PARENT customers (customer);
```

As demonstrated in `TestDumpInterleaved` in `dump_test.go`.
</blockquote></details>

I'm not following your example, sorry. These look like two different tables?

Previously, the secondary indexes _had_ been omitted from the (user-facing) output of `SHOW CREATE TABLE`, but then you updated the PR to add them back, right?

**Review by tyler314 — COMMENTED** [review]
I was wrong in my last comment in this thread, you are correct. My changes move out the INTERLEAVE statements for indexes outside of the CREATE TABLE statement entirely. For the interleaving of tables, it leaves them outside of the CREATE TABLE statement in the fashion you described, that is `CREATE TABLE ... ( ... ) ... INTERLEAVE IN PARENT ...`.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/39486#-:-LmBKoI32wv25d5MZExR:b5cfe20)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dt and @lucy-zhang)

___
*[pkg/cli/dump_test.go, line 454 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/39486#-Lm77TUv7awqj9tDHcV1:-LmBLSM0E0urV6eX1VMG:b-sj7xhh) ([raw file](https://github.com/cockroachdb/cockroach/blob/5d3607f756f051825dbce70792c383df9c4bb3a0/pkg/cli/dump_test.go#L454)):*
<details><summary><i>Previously, lucy-zhang (Lucy Zhang) wrote…</i></summary><blockquote>

nit: can you fix the formatting/indentation for these statements?
</blockquote></details>

Yes, sorry I missed this.
___
*[pkg/sql/show_create.go, line 206 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/39486#-Lm5r3F7EcG4v6axLCnz:-LmBNI965l-VMh_h936o:b-2izbgb) ([raw file](https://github.com/cockroachdb/cockroach/blob/fa685c8fda5d9ba95e77ac86ac25cafc23dc1b15/pkg/sql/show_create.go#L206)):*
<details><summary><i>Previously, lucy-zhang (Lucy Zhang) wrote…</i></summary><blockquote>

I'm not following your example, sorry. These look like two different tables?

Previously, the secondary indexes _had_ been omitted from the (user-facing) output of `SHOW CREATE TABLE`, but then you updated the PR to add them back, right?
</blockquote></details>

Yes, you are correct, I was getting the two types of INTERLEAVE statements confused. The first table I have above is an interleaving of an index, while the second one is an interleaving of a table.

**Review by thoszhang — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/39486)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dt, @lucy-zhang, and @tyleroberts)

___
*[pkg/cli/dump_test.go, line 448 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/39486#-LmGb3TQAqNQgdojFWGt:-LmGb3TQAqNQgdojFWGu:bxbt7wb) ([raw file](https://github.com/cockroachdb/cockroach/blob/1e46cdbcfcecf2695db13ba5e383d729f2139966/pkg/cli/dump_test.go#L448)):*
> ```Go
> 	defer leaktest.AfterTest(t)()
> 
> 	defer leaktest.AfterTest(t)()
> ```

This is repeated.

**Review by tyler314 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/39486)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dt and @lucy-zhang)

___
*[pkg/cli/dump_test.go, line 448 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/39486#-LmGb3TQAqNQgdojFWGt:-LmGuBFkC7gwq3VFUjh7:b-avssyp) ([raw file](https://github.com/cockroachdb/cockroach/blob/1e46cdbcfcecf2695db13ba5e383d729f2139966/pkg/cli/dump_test.go#L448)):*
<details><summary><i>Previously, lucy-zhang (Lucy Zhang) wrote…</i></summary><blockquote>

This is repeated.
</blockquote></details>

Oops! Thank you!

**Review by dt — APPROVED** [review]
It'd be nice to have someone who knows the SQL side, i.e. `tree` AST-to-string stuff take a glance at all the stringifying parts where there are some sometimes easy to miss rules (using the right formatting ctx or whatever). Could ask if @mjibson or @knz has a chance to check that part?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/39486#-:-LmGxfXlC3FpqzRAQTup:b-ccrdcs)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @lucy-zhang and @tyleroberts)

___
*[pkg/cli/dump_test.go, line 491 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/39486#-LmGxWJ5C155MxJLqcfa:-LmGxWJ5C155MxJLqcfb:b-p8xwzw) ([raw file](https://github.com/cockroachdb/cockroach/blob/9fb64618bb1753692130eed561222405e4955b27/pkg/cli/dump_test.go#L491)):*
> ```Go
> 	}
> 
> 	dump2, err := c.RunWithCaptureArgs([]string{"dump", "d", "orders"})
> ```

I think it'd be interesting to see a multi-table dump here, as well as have a row in each table, so we can see the relative ordering of table vs index creation.

File: pkg/cli/dump_test.go [hunk 1]
```diff
@@ -441,3 +441,75 @@ INSERT INTO t (i, j) VALUES
 		t.Fatalf("unexpected output: %s", out)
 	}
 }
+
+func TestDumpInterleaved(t *testing.T) {
```
Comment (mjibson) [inline pkg/cli/dump_test.go]: Can you use the testdata directory for these? I think it can handle all of this.

File: pkg/sql/sqlbase/structured.go [hunk 2]
```diff
@@ -484,11 +484,11 @@ func (desc *IndexDescriptor) SQLString(tableName *tree.TableName) string {
 		f.WriteString("INVERTED ")
 	}
 	f.WriteString("INDEX ")
+	f.FormatNameP(&desc.Name)
```
Comment (mjibson) [inline pkg/sql/sqlbase/structured.go]: Add a test for this.

File: pkg/sql/show_create.go [hunk 3]
```diff
@@ -201,14 +201,22 @@ func ShowCreateTable(
 			}
 			f.WriteString(foreignKey.String())
 		}
-		if idx.ID != desc.PrimaryIndex.ID {
+		// Only add indexes to the create_statement column, and not to the
+		// create_nofks column if they are not associated with an INTERLEAVE
+		// statement.
+		if idx.ID != desc.PrimaryIndex.ID && (len(idx.Interleave.Ancestors) == 0 || ignoreFKs != IgnoreFKs) {
```
Comment (mjibson) [inline pkg/sql/show_create.go]: maybe `if interleave := len(idx.Interleave.Ancestors) == 0 || ignoreFKs != IgnoreFKs; idx.ID != desc.PrimaryIndex.ID && interleave {` then you can use `interleave` below instead of redoing the computation.

File: pkg/sql/show_create.go [hunk 4]
```diff
@@ -201,14 +201,22 @@ func ShowCreateTable(
 			}
 			f.WriteString(foreignKey.String())
 		}
-		if idx.ID != desc.PrimaryIndex.ID {
```
Comment (mjibson) [inline pkg/sql/show_create.go]: If this is changing it should also come with a test.

File: pkg/sql/crdb_internal.go [hunk 5]
```diff
@@ -1220,6 +1222,54 @@ CREATE TABLE crdb_internal.create_statements (
...
+							f.WriteString(idx.SQLString(&parentName))
+							f.WriteString(" INTERLEAVE IN PARENT ")
+							fmtCtx := tree.NewFmtCtx(tree.FmtSimple)
+							fmtCtx.FormatNode(&parentName)
+							f.WriteString(fmtCtx.CloseAndGetString())
+							f.WriteString(" (")
+							// Get all of the columns and write them.
+							for i, name := range idx.ColumnNames[:sharedPrefixLen] {
+								if i > 0 {
+									f.WriteString(", ")
```
Comment (mjibson) [inline pkg/sql/crdb_internal.go]: This doesn't seem to take into account column directions, which I assume interleaved indexes could be? If so, we need to add a test that has some ASC and DESC columns. Also use `idx.ColNamesFormat` which handles this.

File: pkg/sql/crdb_internal.go [hunk 6]
```diff
@@ -1220,6 +1222,54 @@ CREATE TABLE crdb_internal.create_statements (
...
+							var sharedPrefixLen int
+							for _, ancestor := range intl.Ancestors {
+								sharedPrefixLen += int(ancestor.SharedPrefixLen)
+							}
+							// Write the CREATE INDEX statements.
+							f.WriteString("CREATE ")
+							f.WriteString(idx.SQLString(&parentName))
+							f.WriteString(" INTERLEAVE IN PARENT ")
+							fmtCtx := tree.NewFmtCtx(tree.FmtSimple)
+							fmtCtx.FormatNode(&parentName)
```
Comment (mjibson) [inline pkg/sql/crdb_internal.go]: `parentName.Format(f)`

File: pkg/cli/dump_test.go (hunk 1 above)
Comment (mjibson) [reply pkg/cli/dump_test.go]: https://github.com/cockroachdb/cockroach/tree/master/pkg/cli/testdata/dump is what I'm referring to here.

**Review by tyler314 — COMMENTED** [review]
Can you help me understand what I neglected to test here?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/39486#-:-LmLt2VB9AHVsSFlRSYj:b5ofqq7)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dt, @lucy-zhang, and @mjibson)

___
*[pkg/cli/dump_test.go, line 445 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/39486#-LlqeS_GRUMjdnW4aC5--r4-445:-LmLFJY183rgOyqWuPRp:b-f992sl) ([raw file](https://github.com/cockroachdb/cockroach/blob/9fb64618bb1753692130eed561222405e4955b27/pkg/cli/dump_test.go#L445)):*
<details><summary><i>Previously, mjibson (Matt Jibson) wrote…</i></summary><blockquote>

https://github.com/cockroachdb/cockroach/tree/master/pkg/cli/testdata/dump is what I'm referring to here.
</blockquote></details>

It was able to handle the interleaving of indexes in tables, but not the interleaving of tables in tables.
___
*[pkg/cli/dump_test.go, line 491 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/39486#-LmGxWJ5C155MxJLqcfa:-LmLWrLC9tSAD1L8cWWE:bdui86c) ([raw file](https://github.com/cockroachdb/cockroach/blob/9fb64618bb1753692130eed561222405e4955b27/pkg/cli/dump_test.go#L491)):*
<details><summary><i>Previously, dt (David Taylor) wrote…</i></summary><blockquote>

I think it'd be interesting to see a multi-table dump here, as well as have a row in each table, so we can see the relative ordering of table vs index creation. 
</blockquote></details>

Done. Doing this also revealed a bug that I fixed.
___
*[pkg/sql/crdb_internal.go, line 1258 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/39486#-LlqeS_GRUMjdnW4aC50-r4-1258:-LmLXjSm20ss3MbqyhdI:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/9fb64618bb1753692130eed561222405e4955b27/pkg/sql/crdb_internal.go#L1258)):*
<details><summary><i>Previously, mjibson (Matt Jibson) wrote…</i></summary><blockquote>

`parentName.Format(f)`
</blockquote></details>

Done.
___
*[pkg/sql/crdb_internal.go, line 1264 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/39486#-LlqeS_GRUMjdnW4aC50-r4-1264:-LmLqLx9AADUqr_GeLor:b-prr8tj) ([raw file](https://github.com/cockroachdb/cockroach/blob/9fb64618bb1753692130eed561222405e4955b27/pkg/sql/crdb_internal.go#L1264)):*
<details><summary><i>Previously, mjibson (Matt Jibson) wrote…</i></summary><blockquote>

This doesn't seem to take into account column directions, which I assume interleaved indexes could be? If so, we need to add a test that has some ASC and DESC columns. Also use `idx.ColNamesFormat` which handles this.
</blockquote></details>

Column direction wasn't added to the parent's columns previously, should we add them now in this situation? Also, can you elaborate on what `idx.ColNamesFormat` can be used for here?
___
*[pkg/sql/show_create.go, line 207 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/39486#-LlqeS_GRUMjdnW4aC53-r4-207:-LmLYgVwEA9xUcz2J4If:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/9fb64618bb1753692130eed561222405e4955b27/pkg/sql/show_create.go#L207)):*
<details><summary><i>Previously, mjibson (Matt Jibson) wrote…</i></summary><blockquote>

maybe `if interleave := len(idx.Interleave.Ancestors) == 0 || ignoreFKs != IgnoreFKs; idx.ID != desc.PrimaryIndex.ID && interleave {` then you can use `interleave` below instead of redoing the computation.
</blockquote></details>

Done.
___
*[pkg/sql/sqlbase/structured.go, line 487 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/39486#-LlqeS_GRUMjdnW4aC54-r4-487:-LmLoMbT8QOuKuovWmAv:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/9fb64618bb1753692130eed561222405e4955b27/pkg/sql/sqlbase/structured.go#L487)):*
<details><summary><i>Previously, mjibson (Matt Jibson) wrote…</i></summary><blockquote>

Add a test for this.
</blockquote></details>

Done.

**Review by madelynnblue — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/39486)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dt, @lucy-zhang, @mjibson, and @tyleroberts)

___
*[pkg/sql/crdb_internal.go, line 1264 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/39486#-LlqeS_GRUMjdnW4aC50-r4-1264:-LmMHIIr657q6RG_Bx8q:bwdvn74) ([raw file](https://github.com/cockroachdb/cockroach/blob/9fb64618bb1753692130eed561222405e4955b27/pkg/sql/crdb_internal.go#L1264)):*
<details><summary><i>Previously, tyleroberts (Tyler Roberts) wrote…</i></summary><blockquote>

Column direction wasn't added to the parent's columns previously, should we add them now in this situation? Also, can you elaborate on what `idx.ColNamesFormat` can be used for here?
</blockquote></details>

Ah yes, so the interleave statement just names columns, no directions. However we should add a test for directions. Like:

```
create table a (i int, j int, primary key (i, j desc));
create table d (x int, y int, z int, primary key (x, y desc, z desc)) interleave in parent a (x, y);
```

Regarding idx.ColNamesFormat, I thought you could just do `idx.ColNamesFormat(f)` instead of looping yourself, but it seems that function also outputs directions which won't work here, so I guess this is fine.
___
*[pkg/sql/crdb_internal.go, line 1225 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/39486#-LmNvxAfBcDUq4Ff-uFF:-LmNvxAfBcDUq4Ff-uFG:b-l196ny) ([raw file](https://github.com/cockroachdb/cockroach/blob/ad6097043c219a0e8e8b0431de53f0add4e4f907/pkg/sql/crdb_internal.go#L1225)):*
> ```Go
> 							}
> 						}
> 						// Create CREATE INDEX commands for INTERLEAVE tables. These commands
> ```

The below code has many ways it could fail due to improper escaping. Can you add some tests (or ensure that they already exist) that have weird table/index/constraint names that are, for example, just double quote, just single quote, and some reserved keyword? This will hopefully flush out any improper escaping.
___
*[pkg/sql/crdb_internal.go, line 1266 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/39486#-LmMIVX-30GjJ03q5mTh:-LmMIVX-30GjJ03q5mTi:bi64ulk) ([raw file](https://github.com/cockroachdb/cockroach/blob/ad6097043c219a0e8e8b0431de53f0add4e4f907/pkg/sql/crdb_internal.go#L1266)):*
> ```Go
> 							f.WriteString(idx.SQLString(&tableName))
> 							f.WriteString(" INTERLEAVE IN PARENT ")
> 							fmtCtx := tree.NewFmtCtx(tree.FmtSimple)
> ```

This can be removed now.
___
*[pkg/sql/sqlbase/structured_test.go, line 2006 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/39486#-LmMJ7kQ55d0pEXaX6nE:-LmMJ7kQ55d0pEXaX6nF:btd1qo) ([raw file](https://github.com/cockroachdb/cockroach/blob/ad6097043c219a0e8e8b0431de53f0add4e4f907/pkg/sql/sqlbase/structured_test.go#L2006)):*
> ```Go
> }
> 
> func TestSQLString(t *testing.T) {
> ```

I thought we could test this in sql/parser.TestParse :(. I didn't realize it would be this complicated. I'm fine removing this since it's tested in dump above. If you decide to keep it, remove all of the zero values below.

Actually, since it looks like you had to export TblName just for this, delete this test. Not exporting TblName helps ensure that it is used correctly. Apologies for the bad request.

**Review by knz — COMMENTED** [review]
As previously my main comment on the entire endeavor is that it is courageous; this code is very hairy and has gotten too little love recently.

That being said a good way to re-take ownership over it is to chip at it incrementally so that bit by bit it gets closer to the place we want it. This includes being careful to make the core/comments more readable on the way out than the way in. See some suggestions below.

> Reviewed 1 of 7 files at r1, 3 of 7 files at r5, 4 of 4 files at r6.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/39486#-:-LmOd0es2bvINkmcyjpl:bl0ziat)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dt, @lucy-zhang, @mjibson, and @tyleroberts)

___
*[pkg/sql/crdb_internal.go, line 1198 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/39486#-LmOce2R7ilBXNAwHWky:-LmOce2R7ilBXNAwHWkz:bqofu55) ([raw file](https://github.com/cockroachdb/cockroach/blob/480d96a818b2e7020b5d62e770bb0d4818e457d1/pkg/sql/crdb_internal.go#L1198)):*
> ```Go
> 					allIdx := append(table.Indexes, table.PrimaryIndex)
> 					for i := range allIdx {
> 						idx := &allIdx[i]
> ```

I think this function is now large enough that you can pull the body of this iteration into a separate function.
___
*[pkg/sql/crdb_internal.go, line 1234 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/39486#-LmOZJWNAQ7jgqXWeqbE:-LmOZJWODxgpE98tNJjx:b-wcug0r) ([raw file](https://github.com/cockroachdb/cockroach/blob/480d96a818b2e7020b5d62e770bb0d4818e457d1/pkg/sql/crdb_internal.go#L1234)):*
> ```Go
> 							var parentName, tableName tree.TableName
> 							if lCtx != nil {
> 								parentTable, err := lCtx.getTableByID(parentTableID)
> ```

I would recommend that you:
1. take this logic out of here and into a new method of `internalLookupCtx`
2. add a few logic tests for just that method (including cases where the identifiers contain special characters)
3. change the code in `printForeignKeyConstraint` and `showCreateInterleave` to also use the new method you've just implemented

(Side question: was there a reason not to use `showCreateInterleave` here? Note that even if you could, I'd still invite you to explore how to share code between `printForeignKeyConstraint` and `showCreateInterleave` - I think it's reasonable to teach the internalLookupCtx how to produce a reasonable TableName given a table ID).
___
*[pkg/sql/crdb_internal.go, line 1263 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/39486#-LmOcln52a99A1_OLw5z:-LmOcln52a99A1_OLw6-:buikdmd) ([raw file](https://github.com/cockroachdb/cockroach/blob/480d96a818b2e7020b5d62e770bb0d4818e457d1/pkg/sql/crdb_internal.go#L1263)):*
> ```Go
> 							}
> 							// Write the CREATE INDEX statements.
> 							f.WriteString("CREATE ")
> ```

And maybe pull this create formatting code into a separate function too.
___
*[pkg/sql/crdb_internal.go, line 1264 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/39486#-LmO_68kDQkwpi62nn4J:-LmO_68kDQkwpi62nn4K:bugc7qo) ([raw file](https://github.com/cockroachdb/cockroach/blob/480d96a818b2e7020b5d62e770bb0d4818e457d1/pkg/sql/crdb_internal.go#L1264)):*
> ```Go
> 							// Write the CREATE INDEX statements.
> 							f.WriteString("CREATE ")
> 							f.WriteString(idx.SQLString(&tableName))
> ```

I am not fond of this `SQLString` methid.
If anythng the API should be something like `idx.Format(f)` instead.
It needs to obey the format flags, in particular anonymization.

Also out of curiosity please point me to where this is unit tested, I'd like to check for a few special cases in there.
___
*[pkg/sql/crdb_internal.go, line 1272 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/39486#-LmO_OqsCODQzbogIMTn:-LmO_Oqt1msjaCTU1joN:b2sbivd) ([raw file](https://github.com/cockroachdb/cockroach/blob/480d96a818b2e7020b5d62e770bb0d4818e457d1/pkg/sql/crdb_internal.go#L1272)):*
> ```Go
> 							// Get all of the columns and write them.
> 							for i, name := range idx.ColumnNames[:sharedPrefixLen] {
> 								if i > 0 {
> ```

tip:
```
comma := ""
for _, name := range ... {
    f.WriteString(comma)
    ...
    comma = ", "
}
```

this way you skip a conditional.
___
*[pkg/sql/show_create.go, line 207 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/39486#-LlqeS_GRUMjdnW4aC53-r4-207:-LmOa8S8CXSNoocRTQFn:bj6va00) ([raw file](https://github.com/cockroachdb/cockroach/blob/9fb64618bb1753692130eed561222405e4955b27/pkg/sql/show_create.go#L207)):*
<details><summary><i>Previously, tyleroberts (Tyler Roberts) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

my gosh, it is hard to read.  I'm not even sure _how_ to evaluate the correctness of this boolean predicate.

(tip: it's always better when the code makes it possible for a reviewer to understand and verify the code locally without paging in a lot of context)

In order to ease my readability I'd first rewrite like this:

```go
interleave := !idx.HasInterleaveAncestors()
if ignoreFKs != IgnoreFKs {
   // ... some explanatory comment of what's going on with "ignoreFKs" ... (what's going on really? idk)
   interleave = true
}
if desc.IsPrimaryIndex(idx) && interleave { 

   ...
```

1) Something tells me that the name `interleave` is not describing what this boolean is about.  I don't really understand it myself but depending on your reaction to the second point above, I may be able to make a suggestion.

2) something tells me that the variable name `ignoreFKs` is not describing what this variable is about. The condition above `ignoreFKs == IgnoreMissingFKs` is utterly confusing. Maybe the name should be `ignoredFKs` or `fkIgnoreMode` but even the verb "ignore" seems off. It's about avoiding printing FKs in some place isn't it? Then maybe it's `fkDisplayMode`.
___
*[pkg/sql/show_create.go, line 204 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/39486#-LmOcsFt8a2j8kdpHmC-:-LmOcsFt8a2j8kdpHmC0:b-wwnyh7) ([raw file](https://github.com/cockroachdb/cockroach/blob/480d96a818b2e7020b5d62e770bb0d4818e457d1/pkg/sql/show_create.go#L204)):*
> ```Go
> 			f.WriteString(foreignKey.String())
> 		}
> 		// Only add indexes to the create_statement column, and not to the
> ```

Ditto I think this function is now large enough that it can be split into multiple smaller functions.
___
*[pkg/sql/show_create.go, line 210 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/39486#-LmO_zY41ZIxxBNa5Xwr:-LmO_zY41ZIxxBNa5Xws:b-pfn5oz) ([raw file](https://github.com/cockroachdb/cockroach/blob/480d96a818b2e7020b5d62e770bb0d4818e457d1/pkg/sql/show_create.go#L210)):*
> ```Go
> 			// Showing the primary index is handled above.
> 			f.WriteString(",\n\t")
> 			f.WriteString(idx.SQLString(&sqlbase.AnonymousTable))
> ```

ditto my comment above about `SQLString` and `Format`.
___
*[pkg/sql/sqlbase/structured_test.go, line 2009 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/39486#-LmOc2qcBbkStyt4_xRk:-LmOc2qcBbkStyt4_xRl:b-x56377) ([raw file](https://github.com/cockroachdb/cockroach/blob/480d96a818b2e7020b5d62e770bb0d4818e457d1/pkg/sql/sqlbase/structured_test.go#L2009)):*
> ```Go
> 	colNames := []string{"derp", "foo"}
> 	indexName := "idx"
> 	tableName := tree.MakeTableName("DB", "t1")
> ```

you probably want multiple test cases, this really wants to check that the escaping is done properly for identifiers containing special characters.

Also see my comment above about displaying index definitions differently depending on the format flags. It would be better if we were testing a Format method with a format ctx as argument.

**Review by tyler314 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/39486)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dt, @knz, @lucy-zhang, @mjibson, and @tyleroberts)

___
*[pkg/sql/crdb_internal.go, line 1264 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/39486#-LlqeS_GRUMjdnW4aC50-r4-1264:-LmRQzl-11VVWFDnbTY_:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/9fb64618bb1753692130eed561222405e4955b27/pkg/sql/crdb_internal.go#L1264)):*
<details><summary><i>Previously, mjibson (Matt Jibson) wrote…</i></summary><blockquote>

Ah yes, so the interleave statement just names columns, no directions. However we should add a test for directions. Like:

```
create table a (i int, j int, primary key (i, j desc));
create table d (x int, y int, z int, primary key (x, y desc, z desc)) interleave in parent a (x, y);
```

Regarding idx.ColNamesFormat, I thought you could just do `idx.ColNamesFormat(f)` instead of looping yourself, but it seems that function also outputs directions which won't work here, so I guess this is fine.
</blockquote></details>

Done.
___
*[pkg/sql/crdb_internal.go, line 1225 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/39486#-LmNvxAfBcDUq4Ff-uFF:-LmRG8944AXnwXsCJLHO:b-f1lzbb) ([raw file](https://github.com/cockroachdb/cockroach/blob/ad6097043c219a0e8e8b0431de53f0add4e4f907/pkg/sql/crdb_internal.go#L1225)):*
<details><summary><i>Previously, mjibson (Matt Jibson) wrote…</i></summary><blockquote>

The below code has many ways it could fail due to improper escaping. Can you add some tests (or ensure that they already exist) that have weird table/index/constraint names that are, for example, just double quote, just single quote, and some reserved keyword? This will hopefully flush out any improper escaping.
</blockquote></details>

This is a good idea. I think it is also worth mentioning that I copied essentially all of this code from `showCreateInterleave`, with the motivation that I wanted to accomplish the same thing but without adding the interleave statements in the CREATE TABLE statement.
___
*[pkg/sql/crdb_internal.go, line 1266 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/39486#-LmMIVX-30GjJ03q5mTh:-LmV7pcU3lVvfcKclBtj:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/ad6097043c219a0e8e8b0431de53f0add4e4f907/pkg/sql/crdb_internal.go#L1266)):*
<details><summary><i>Previously, mjibson (Matt Jibson) wrote…</i></summary><blockquote>

This can be removed now.
</blockquote></details>

Done.
___
*[pkg/sql/crdb_internal.go, line 1198 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/39486#-LmOce2R7ilBXNAwHWky:-LmRvUBJC1yKT02MzwJn:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/480d96a818b2e7020b5d62e770bb0d4818e457d1/pkg/sql/crdb_internal.go#L1198)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

I think this function is now large enough that you can pull the body of this iteration into a separate function.
</blockquote></details>

Done.
___
*[pkg/sql/crdb_internal.go, line 1263 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/39486#-LmOcln52a99A1_OLw5z:-LmV7nrj8DdAk2yIeVvp:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/480d96a818b2e7020b5d62e770bb0d4818e457d1/pkg/sql/crdb_internal.go#L1263)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

And maybe pull this create formatting code into a separate function too.
</blockquote></details>

Done.
___
*[pkg/sql/crdb_internal.go, line 1264 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/39486#-LmO_68kDQkwpi62nn4J:-LmRN4b7DO2Fg4SGTZ-h:b-kjdma3) ([raw file](https://github.com/cockroachdb/cockroach/blob/480d96a818b2e7020b5d62e770bb0d4818e457d1/pkg/sql/crdb_internal.go#L1264)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

I am not fond of this `SQLString` methid.
If anythng the API should be something like `idx.Format(f)` instead.
It needs to obey the format flags, in particular anonymization.

Also out of curiosity please point me to where this is unit tested, I'd like to check for a few special cases in there.
</blockquote></details>

I added the test `TestSQLString` in `structured_test.go`
___
*[pkg/sql/crdb_internal.go, line 1272 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/39486#-LmO_OqsCODQzbogIMTn:-LmROdTV6AQ-_Y8wdeKW:b6zrrk4) ([raw file](https://github.com/cockroachdb/cockroach/blob/480d96a818b2e7020b5d62e770bb0d4818e457d1/pkg/sql/crdb_internal.go#L1272)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

tip:
```
comma := ""
for _, name := range ... {
    f.WriteString(comma)
    ...
    comma = ", "
}
```

this way you skip a conditional.
</blockquote></details>

Good catch!
___
*[pkg/sql/show_create.go, line 207 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/39486#-LlqeS_GRUMjdnW4aC53-r4-207:-LmR_k7jBEdd2G6unc-r:b-vn2whg) ([raw file](https://github.com/cockroachdb/cockroach/blob/9fb64618bb1753692130eed561222405e4955b27/pkg/sql/show_create.go#L207)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

my gosh, it is hard to read.  I'm not even sure _how_ to evaluate the correctness of this boolean predicate.

(tip: it's always better when the code makes it possible for a reviewer to understand and verify the code locally without paging in a lot of context)

In order to ease my readability I'd first rewrite like this:

```go
interleave := !idx.HasInterleaveAncestors()
if ignoreFKs != IgnoreFKs {
   // ... some explanatory comment of what's going on with "ignoreFKs" ... (what's going on really? idk)
   interleave = true
}
if desc.IsPrimaryIndex(idx) && interleave { 

   ...
```

1) Something tells me that the name `interleave` is not describing what this boolean is about.  I don't really understand it myself but depending on your reaction to the second point above, I may be able to make a suggestion.

2) something tells me that the variable name `ignoreFKs` is not describing what this variable is about. The condition above `ignoreFKs == IgnoreMissingFKs` is utterly confusing. Maybe the name should be `ignoredFKs` or `fkIgnoreMode` but even the verb "ignore" seems off. It's about avoiding printing FKs in some place isn't it? Then maybe it's `fkDisplayMode`.
</blockquote></details>

Yes, I agree. This boolean is all about including interleave or foreign key statements within the `CREATE` statement, as opposed to outside of it.
___
*[pkg/sql/show_create.go, line 204 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/39486#-LmOcsFt8a2j8kdpHmC-:-LmV8XVzEE-3EFlkN_RH:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/480d96a818b2e7020b5d62e770bb0d4818e457d1/pkg/sql/show_create.go#L204)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

Ditto I think this function is now large enough that it can be split into multiple smaller functions.
</blockquote></details>

Done.
___
*[pkg/sql/show_create.go, line 210 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/39486#-LmO_zY41ZIxxBNa5Xwr:-LmV8X7m1zNFwb2mIv7F:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/480d96a818b2e7020b5d62e770bb0d4818e457d1/pkg/sql/show_create.go#L210)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

ditto my comment above about `SQLString` and `Format`.
</blockquote></details>

Done.
___
*[pkg/sql/sqlbase/structured_test.go, line 2006 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/39486#-LmMJ7kQ55d0pEXaX6nE:-LmR5i314Pe_-ewJfgYJ:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/ad6097043c219a0e8e8b0431de53f0add4e4f907/pkg/sql/sqlbase/structured_test.go#L2006)):*
<details><summary><i>Previously, mjibson (Matt Jibson) wrote…</i></summary><blockquote>

I thought we could test this in sql/parser.TestParse :(. I didn't realize it would be this complicated. I'm fine removing this since it's tested in dump above. If you decide to keep it, remove all of the zero values below.

Actually, since it looks like you had to export TblName just for this, delete this test. Not exporting TblName helps ensure that it is used correctly. Apologies for the bad request.
</blockquote></details>

Done.
___
*[pkg/sql/sqlbase/structured_test.go, line 2009 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/39486#-LmOc2qcBbkStyt4_xRk:-LmR5n3p3frWoBwqsa8S:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/480d96a818b2e7020b5d62e770bb0d4818e457d1/pkg/sql/sqlbase/structured_test.go#L2009)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

you probably want multiple test cases, this really wants to check that the escaping is done properly for identifiers containing special characters.

Also see my comment above about displaying index definitions differently depending on the format flags. It would be better if we were testing a Format method with a format ctx as argument.
</blockquote></details>

Done.

**Review by tyler314 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/39486)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dt, @knz, @lucy-zhang, and @mjibson)

___
*[pkg/sql/crdb_internal.go, line 1234 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/39486#-LmOZJWNAQ7jgqXWeqbE:-LmRLwb-7O1CK32zFUor:b5x6xpq) ([raw file](https://github.com/cockroachdb/cockroach/blob/480d96a818b2e7020b5d62e770bb0d4818e457d1/pkg/sql/crdb_internal.go#L1234)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

I would recommend that you:
1. take this logic out of here and into a new method of `internalLookupCtx`
2. add a few logic tests for just that method (including cases where the identifiers contain special characters)
3. change the code in `printForeignKeyConstraint` and `showCreateInterleave` to also use the new method you've just implemented

(Side question: was there a reason not to use `showCreateInterleave` here? Note that even if you could, I'd still invite you to explore how to share code between `printForeignKeyConstraint` and `showCreateInterleave` - I think it's reasonable to teach the internalLookupCtx how to produce a reasonable TableName given a table ID).
</blockquote></details>

The `showCreateInterleave` adds the interleave statements to the `CREATE` statement itself. Where I wanted it to be removed and added to the `alter_statements`.

**Review by tyler314 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/39486)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dt, @knz, @lucy-zhang, and @mjibson)

___
*[pkg/cli/dump_test.go, line 448 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/39486#-LmGb3TQAqNQgdojFWGt:-LmWjMgH5eDJRZ4qj8mF:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/1e46cdbcfcecf2695db13ba5e383d729f2139966/pkg/cli/dump_test.go#L448)):*
<details><summary><i>Previously, tyleroberts (Tyler Roberts) wrote…</i></summary><blockquote>

Oops! Thank you!
</blockquote></details>

Done.
___
*[pkg/sql/crdb_internal.go, line 1225 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/39486#-LmNvxAfBcDUq4Ff-uFF:-LmWjNz_AFaThtR1dqxF:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/ad6097043c219a0e8e8b0431de53f0add4e4f907/pkg/sql/crdb_internal.go#L1225)):*
<details><summary><i>Previously, tyleroberts (Tyler Roberts) wrote…</i></summary><blockquote>

This is a good idea. I think it is also worth mentioning that I copied essentially all of this code from `showCreateInterleave`, with the motivation that I wanted to accomplish the same thing but without adding the interleave statements in the CREATE TABLE statement.
</blockquote></details>

Done.
___
*[pkg/sql/crdb_internal.go, line 1234 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/39486#-LmOZJWNAQ7jgqXWeqbE:-LmWjOjH0kE0ttALZiIB:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/480d96a818b2e7020b5d62e770bb0d4818e457d1/pkg/sql/crdb_internal.go#L1234)):*
<details><summary><i>Previously, tyleroberts (Tyler Roberts) wrote…</i></summary><blockquote>

The `showCreateInterleave` adds the interleave statements to the `CREATE` statement itself. Where I wanted it to be removed and added to the `alter_statements`. 
</blockquote></details>

Done.
___
*[pkg/sql/crdb_internal.go, line 1264 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/39486#-LmO_68kDQkwpi62nn4J:-LmWjH378EsAWdNuyg3p:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/480d96a818b2e7020b5d62e770bb0d4818e457d1/pkg/sql/crdb_internal.go#L1264)):*
<details><summary><i>Previously, tyleroberts (Tyler Roberts) wrote…</i></summary><blockquote>

I added the test `TestSQLString` in `structured_test.go`
</blockquote></details>

Done.
___
*[pkg/sql/crdb_internal.go, line 1272 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/39486#-LmO_OqsCODQzbogIMTn:-LmWjJ0T-3UPTmi9vLjS:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/480d96a818b2e7020b5d62e770bb0d4818e457d1/pkg/sql/crdb_internal.go#L1272)):*
<details><summary><i>Previously, tyleroberts (Tyler Roberts) wrote…</i></summary><blockquote>

Good catch!
</blockquote></details>

Done.
___
*[pkg/sql/show_create.go, line 206 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/39486#-Lm5r3F7EcG4v6axLCnz:-LmWjKO18bydiDymYQWO:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/fa685c8fda5d9ba95e77ac86ac25cafc23dc1b15/pkg/sql/show_create.go#L206)):*
<details><summary><i>Previously, tyleroberts (Tyler Roberts) wrote…</i></summary><blockquote>

Yes, you are correct, I was getting the two types of INTERLEAVE statements confused. The first table I have above is an interleaving of an index, while the second one is an interleaving of a table.
</blockquote></details>

Done.

**Review by knz — COMMENTED** [review]
I like how the PR is now reaching both the original intended goal _and_ also is increasing future maintainability of this area of the code, even more than what you found on the way in.

Tip: I recommend that you sprinkle the commit message (and comments) with an adequate nuance between the terms "clause" and "statement". The distinction is meaningful and clarifying. It will make the PR more easy to understand overall.

> Reviewed 4 of 4 files at r7.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/39486#-:-LmZixvxDEmZgAKh9HKx:bbk7eev)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dt, @lucy-zhang, @mjibson, and @tyleroberts)

___
*[pkg/sql/crdb_internal.go, line 1197 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/39486#-LmZfFIH63JdzlbcVbp8:-LmZfFIH63JdzlbcVbp9:b8che1f) ([raw file](https://github.com/cockroachdb/cockroach/blob/9bee048f7cd70970875022cf2b041a6bebab14d8/pkg/sql/crdb_internal.go#L1197)):*
> ```Go
> 					}
> 					allIdx := append(table.Indexes, table.PrimaryIndex)
> 					if err := makeCreateStatement(ctx, tn, contextName, lCtx, allIdx, table, alterStmts, validateStmts); err != nil {
> ```

"makeCreateStatement" -> "showCreateStatement"? But I think that's overloaded now. Perhaps it's worth having "showCreateStatementX" and "showCreateStatementY" with clear X and Y words to distinguish them. In any case, what you're doing here is not "make").

Also it seems that the function is not minting CREATE statements but instead ALTER statements. The word "Create" in there may be misleading?

Try to step back and think about how you'd explain this to someone. Step one is to show an example output. Step two is to describe said output in prose to a human. Chances are the description will not use the words "create" and "alter" but instead something like "DDL" or "complete table definition" or something. Then mint a name for your function.
___
*[pkg/sql/crdb_internal.go, line 1258 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/39486#-LmZfk3VCg2v_4vGjJPL:-LmZfk3W4jLAxtXEav79:b-ke4l0o) ([raw file](https://github.com/cockroachdb/cockroach/blob/9bee048f7cd70970875022cf2b041a6bebab14d8/pkg/sql/crdb_internal.go#L1258)):*
> ```Go
> 			f.FormatNameP(&fk.Name)
> 			f.WriteByte(' ')
> 			if err := printForeignKeyConstraint(ctx, &f.Buffer, contextName, idx, lCtx); err != nil {
> ```

"print" -> "format" or "show"

Also given that this is now becoming a conversation topic, it may be useful to collect these various print/format/show functions in a file of their own, with a comment at the top which explains to the reader what each function is printing/showing/formatting, with an example.

This would solve the next question: which function should I use if i need to print a specific sub-clause.
___
*[pkg/sql/crdb_internal.go, line 1281 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/39486#-LmZiFrJ38HxMaSObZN1:-LmZiFrKCkyT4lq78AIU:b-upx4o3) ([raw file](https://github.com/cockroachdb/cockroach/blob/9bee048f7cd70970875022cf2b041a6bebab14d8/pkg/sql/crdb_internal.go#L1281)):*
> ```Go
> 			f := tree.NewFmtCtx(tree.FmtSimple)
> 			intl := idx.Interleave
> 			// Get the parent table information.
> ```

So I think that the code from this line ...
___
*[pkg/sql/crdb_internal.go, line 1308 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/39486#-LmZiI-Q8iK_Lrz9lRgp:-LmZiI-Q8iK_Lrz9lRgq:bxr7uy8) ([raw file](https://github.com/cockroachdb/cockroach/blob/9bee048f7cd70970875022cf2b041a6bebab14d8/pkg/sql/crdb_internal.go#L1308)):*
> ```Go
> 				tableName.ExplicitCatalog = false
> 				tableName.ExplicitSchema = false
> 			}
> ```

... until this line should be extracted into a separate method `(*lookupContext) makeTableNameFromId(...)`

And this method could be used from a couple places. What do you think?
___
*[pkg/sql/show_create.go, line 206 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/39486#-LmZgaJo1Idb8McpHDll:-LmZgaJo1Idb8McpHDlm:b-t4espm) ([raw file](https://github.com/cockroachdb/cockroach/blob/9bee048f7cd70970875022cf2b041a6bebab14d8/pkg/sql/show_create.go#L206)):*
> ```Go
> 		// Only add indexes to the create_statement column, and not to the
> 		// create_nofks column if they are not associated with an INTERLEAVE
> 		// statement.
> ```

Can you also extend the comment to explain _why_ this is necessary. The reader needs to understand what's special about interleave without paging in too much context.
___
*[pkg/sql/show_create.go, line 209 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/39486#-LmZgo38Dt-gbp-OtXXy:-LmZgo38Dt-gbp-OtXXz:b-7y1lbw) ([raw file](https://github.com/cockroachdb/cockroach/blob/9bee048f7cd70970875022cf2b041a6bebab14d8/pkg/sql/show_create.go#L209)):*
> ```Go
> 		includeInCreateStatement := len(idx.Interleave.Ancestors) == 0
> 		if ignoreFKs != IgnoreFKs {
> 			// If we choose not to ignore the Foreign Keys, then we do want to
> ```

I can feel while reading this that you did not like writing this very tautological-sounding and boring comment. I share the pain.

The pain here is that the word "ignore" is just bad. The 6 letters i-g-n-o-r-e are used on both sides but they mean two different things and both things are totally unrelated to the meaning of the word "ignore" in English. Compare instead:

```go
if fkDisplayMode != OmitFKClausesFromCreate {
   // The caller is instructing us to not omit FK clauses from inside the CREATE.
   // (i.e. the caller does not want them as separate DDL.)
   // Since we're including FK clauses, we need to also include the PARTITION and INTERLEAVE
   // clauses as well. 
   includeInCreateStatement = true
}
```

(`ignoreFKs` -> `fkDisplayMode`; `IgnoreFKs` -> `OmitFKClausesFromCreate`)

(maybe also spell out specifically in the comment what's bad about not including them - actually I don't think anything would break if we didn't)

Also the variable name `includeInCreateStatement` is missing an object - what is being included? Maybe `includeInterleaveClause` would be clearer.
___
*[pkg/sql/show_create.go, line 237 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/39486#-LmZiqwe5p0Wo9HznUii:-LmZiqwe5p0Wo9HznUij:b-i8r1wk) ([raw file](https://github.com/cockroachdb/cockroach/blob/9bee048f7cd70970875022cf2b041a6bebab14d8/pkg/sql/show_create.go#L237)):*
> ```Go
> 	// Create the FAMILY and CONSTRAINTs of the CREATE statement
> 	makeFamily(desc, f)
> 	makeConstraint(desc, f)
> ```

`showConstraintClause`
___
*[pkg/sql/show_create.go, line 270 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/39486#-LmZedh53vrXiFfuhvIj:-LmZedh7DBFZ3Sm7rrMP:btnxv1v) ([raw file](https://github.com/cockroachdb/cockroach/blob/9bee048f7cd70970875022cf2b041a6bebab14d8/pkg/sql/show_create.go#L270)):*
> ```Go
> // makeFamily creates the FAMILY statements for a CREATE statement, writing them
> // to tree.FmtCtx f
> func makeFamily(desc *sqlbase.TableDescriptor, f *tree.FmtCtx) {
> ```

maybe `showFamilyClause`

(also use the word "clause" in the comment instead of "statement")
___
*[pkg/sql/sqlbase/structured_test.go, line 2009 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/39486#-LmOc2qcBbkStyt4_xRk:-LmZepeQ7krxlgQwSTaD:b-p9tf8q) ([raw file](https://github.com/cockroachdb/cockroach/blob/480d96a818b2e7020b5d62e770bb0d4818e457d1/pkg/sql/sqlbase/structured_test.go#L2009)):*
<details><summary><i>Previously, tyleroberts (Tyler Roberts) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

What is done precisely?

**Review by tyler314 — COMMENTED** [review]
Thank you for brining that distinction up with me, it was not something I was previously aware of.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/39486#-:-LmacsAL3ZdxRLWyunSZ:b-qu164i)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dt, @knz, @lucy-zhang, and @mjibson)

___
*[pkg/sql/crdb_internal.go, line 1197 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/39486#-LmZfFIH63JdzlbcVbp8:-Lmag5HI5pf9UKdbGjUE:bv1pv76) ([raw file](https://github.com/cockroachdb/cockroach/blob/9bee048f7cd70970875022cf2b041a6bebab14d8/pkg/sql/crdb_internal.go#L1197)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

"makeCreateStatement" -> "showCreateStatement"? But I think that's overloaded now. Perhaps it's worth having "showCreateStatementX" and "showCreateStatementY" with clear X and Y words to distinguish them. In any case, what you're doing here is not "make").

Also it seems that the function is not minting CREATE statements but instead ALTER statements. The word "Create" in there may be misleading?

Try to step back and think about how you'd explain this to someone. Step one is to show an example output. Step two is to describe said output in prose to a human. Chances are the description will not use the words "create" and "alter" but instead something like "DDL" or "complete table definition" or something. Then mint a name for your function.
</blockquote></details>

This makes a lot of sense, and thank you for taking the time to explain that to me. I think the new names are better reflections of what the functions do.
___
*[pkg/sql/crdb_internal.go, line 1258 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/39486#-LmZfk3VCg2v_4vGjJPL:-Lme1UTxEESnEpwxELU9:b-onvbrh) ([raw file](https://github.com/cockroachdb/cockroach/blob/9bee048f7cd70970875022cf2b041a6bebab14d8/pkg/sql/crdb_internal.go#L1258)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

"print" -> "format" or "show"

Also given that this is now becoming a conversation topic, it may be useful to collect these various print/format/show functions in a file of their own, with a comment at the top which explains to the reader what each function is printing/showing/formatting, with an example.

This would solve the next question: which function should I use if i need to print a specific sub-clause.
</blockquote></details>

I moved some of the more "obvious" functions into a new file titled `show_clause`. Hopefully this will remove some ambiguity about where certain functions and methods belong. `show_create` was becoming a bit crowded.
___
*[pkg/sql/crdb_internal.go, line 1281 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/39486#-LmZiFrJ38HxMaSObZN1:-LmeELvY1bJtBFajgs9Z:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/9bee048f7cd70970875022cf2b041a6bebab14d8/pkg/sql/crdb_internal.go#L1281)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

So I think that the code from this line ...
</blockquote></details>

Done.
___
*[pkg/sql/crdb_internal.go, line 1308 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/39486#-LmZiI-Q8iK_Lrz9lRgp:-LmeE02O0IS3wZJEwnEI:b-byp1b8) ([raw file](https://github.com/cockroachdb/cockroach/blob/9bee048f7cd70970875022cf2b041a6bebab14d8/pkg/sql/crdb_internal.go#L1308)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

... until this line should be extracted into a separate method `(*lookupContext) makeTableNameFromId(...)`

And this method could be used from a couple places. What do you think?
</blockquote></details>

After putting some thought into this, I do not completely agree. This logic has an `if-else` dependent on whether not the `*lookupContext` is null. I tried finding workarounds for including the not-null case in a method and the null case outside but it became complicated and didn't seem to make things that much better. I settled on creating exported functions that take the `*lookupContext` as an argument and I think it is better than what was there before.
___
*[pkg/sql/show_create.go, line 206 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/39486#-LmZgaJo1Idb8McpHDll:-Lmah46q5V3l7PnFKQet:b-l0je2s) ([raw file](https://github.com/cockroachdb/cockroach/blob/9bee048f7cd70970875022cf2b041a6bebab14d8/pkg/sql/show_create.go#L206)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

Can you also extend the comment to explain _why_ this is necessary. The reader needs to understand what's special about interleave without paging in too much context.
</blockquote></details>

Yes, I agree. I am sorry I neglected to do this in the first place.
___
*[pkg/sql/show_create.go, line 209 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/39486#-LmZgo38Dt-gbp-OtXXy:-Lmajj3K3y0NHLKAZKbn:b-d12bxd) ([raw file](https://github.com/cockroachdb/cockroach/blob/9bee048f7cd70970875022cf2b041a6bebab14d8/pkg/sql/show_create.go#L209)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

I can feel while reading this that you did not like writing this very tautological-sounding and boring comment. I share the pain.

The pain here is that the word "ignore" is just bad. The 6 letters i-g-n-o-r-e are used on both sides but they mean two different things and both things are totally unrelated to the meaning of the word "ignore" in English. Compare instead:

```go
if fkDisplayMode != OmitFKClausesFromCreate {
   // The caller is instructing us to not omit FK clauses from inside the CREATE.
   // (i.e. the caller does not want them as separate DDL.)
   // Since we're including FK clauses, we need to also include the PARTITION and INTERLEAVE
   // clauses as well. 
   includeInCreateStatement = true
}
```

(`ignoreFKs` -> `fkDisplayMode`; `IgnoreFKs` -> `OmitFKClausesFromCreate`)

(maybe also spell out specifically in the comment what's bad about not including them - actually I don't think anything would break if we didn't)

Also the variable name `includeInCreateStatement` is missing an object - what is being included? Maybe `includeInterleaveClause` would be clearer.
</blockquote></details>

This makes sense, I will include these refactors.
___
*[pkg/sql/show_create.go, line 237 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/39486#-LmZiqwe5p0Wo9HznUii:-LmdyeAE4LyOwfkDiSZT:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/9bee048f7cd70970875022cf2b041a6bebab14d8/pkg/sql/show_create.go#L237)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

`showConstraintClause`
</blockquote></details>

Done.
___
*[pkg/sql/show_create.go, line 270 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/39486#-LmZedh53vrXiFfuhvIj:-LmdzMIp-ARax8A3ZjCm:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/9bee048f7cd70970875022cf2b041a6bebab14d8/pkg/sql/show_create.go#L270)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

maybe `showFamilyClause`

(also use the word "clause" in the comment instead of "statement")
</blockquote></details>

Done.
___
*[pkg/sql/sqlbase/structured_test.go, line 2009 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/39486#-LmOc2qcBbkStyt4_xRk:-LmeGcSWAv2DrQbEUbul:b9296d7) ([raw file](https://github.com/cockroachdb/cockroach/blob/480d96a818b2e7020b5d62e770bb0d4818e457d1/pkg/sql/sqlbase/structured_test.go#L2009)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

What is done precisely?
</blockquote></details>

I added two more test cases in `interleave_index` to test column direction and a key word (unique) as a column name. I think this is sufficient for now, but what are your thoughts?

**Review by knz — COMMENTED** [review]
LGTM with nits.
There is work remaining to clear technical debt left over from #15936. See my comment below. I recommend that you separate that work into a separate PR.

> Reviewed 7 of 8 files at r8.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/39486#-:-Lmi9etVCdDdOerIAb-a:b-grdn2p)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dt, @lucy-zhang, @mjibson, and @tyleroberts)

___
*[pkg/sql/show_clause.go, line 1 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/39486#-Lmi6aIdDDM_C-ogi8AO:-Lmi6aIdDDM_C-ogi8AP:b-y93f3i) ([raw file](https://github.com/cockroachdb/cockroach/blob/8a05127bc5882b66a120048990f89538a07f218e/pkg/sql/show_clause.go#L1)):*
> ```Go
> // Copyright 2019 The Cockroach Authors.
> ```

`show_create_clauses.go`
___
*[pkg/sql/show_clause.go, line 278 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/39486#-Lmi6fS1BtgknG54Oniu:-Lmi6fS1BtgknG54Oniv:blrnnvc) ([raw file](https://github.com/cockroachdb/cockroach/blob/8a05127bc5882b66a120048990f89538a07f218e/pkg/sql/show_clause.go#L278)):*
> ```Go
> // interleaved indexes.
> func GetParentAsTableName(
> 	l *internalLookupCtx, intl sqlbase.InterleaveDescriptor, dbPrefix string,
> ```

1) you can make this a method of the `internalLookupCtx`

2) I don't think you need to export the method.
___
*[pkg/sql/show_clause.go, line 302 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/39486#-Lmi6lrKBGrjlx3R-5ZT:-Lmi6lrKBGrjlx3R-5ZU:b-7ropln) ([raw file](https://github.com/cockroachdb/cockroach/blob/8a05127bc5882b66a120048990f89538a07f218e/pkg/sql/show_clause.go#L302)):*
> ```Go
> 
> // GetTableAsTableName returns a TableName object fot a given TableDescriptor.
> func GetTableAsTableName(
> ```

ditto
___
*[pkg/sql/show_create.go, line 237 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/39486#-LmZiqwe5p0Wo9HznUii:-Lmi7LVQ0mmOBlrTIeCJ:b-ve18l) ([raw file](https://github.com/cockroachdb/cockroach/blob/9bee048f7cd70970875022cf2b041a6bebab14d8/pkg/sql/show_create.go#L237)):*
<details><summary><i>Previously, tyleroberts (Tyler Roberts) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I still see a `makeConstraint` here
___
*[pkg/sql/show_create.go, line 37 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/39486#-Lmi77fJ29B_5vqDI9D-:-Lmi77fK-p44ncwoVFxP:bvcwh57) ([raw file](https://github.com/cockroachdb/cockroach/blob/8a05127bc5882b66a120048990f89538a07f218e/pkg/sql/show_create.go#L37)):*
> ```Go
> 	// included in the back up, so some foreign key information may be
> 	// impossible to retrieve.
> 	OmitMissingFKClausesFromCreate
> ```

:sparkling_heart: 
___
*[pkg/sql/show_create.go, line 158 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/39486#-Lmi7PtfBExi53n4iLDL:-Lmi7PtfBExi53n4iLDM:bfztkix) ([raw file](https://github.com/cockroachdb/cockroach/blob/8a05127bc5882b66a120048990f89538a07f218e/pkg/sql/show_create.go#L158)):*
> ```Go
> // makeConstraint creates the CONSTRAINT clauses for a CREATE statement,
> // writing them to tree.FmtCtx f
> func makeConstraint(desc *sqlbase.TableDescriptor, f *tree.FmtCtx) {
> ```

This could also perhaps move to the new file.
___
*[pkg/sql/sqlbase/structured_test.go, line 2009 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/39486#-LmOc2qcBbkStyt4_xRk:-Lmi7grv8yuPxvN1PAgP:b-pab501) ([raw file](https://github.com/cockroachdb/cockroach/blob/480d96a818b2e7020b5d62e770bb0d4818e457d1/pkg/sql/sqlbase/structured_test.go#L2009)):*
<details><summary><i>Previously, tyleroberts (Tyler Roberts) wrote…</i></summary><blockquote>

I added two more test cases in `interleave_index` to test column direction and a key word (unique) as a column name. I think this is sufficient for now, but what are your thoughts?
</blockquote></details>

There are currently no unit tests for `(*IndexDescriptor) SQLString()` and `(*ColumnDescriptor) SQLString()`.
(I also personally _still_ am of the opinion these two methods should not exist at all. There should be Format methods taking a format context as argument. But that's not directly relevant here.)

Matt's initial request was to add the missing tests for at least one of these two methods. 
I see you have added asc/desc tests, which is part of the necessary work.
However there are other things to check as well, in particular that the names of the identifiers (index names, column names) are properly quoted when they contain special characters.

Now all this, of course, is not directly relevant to this PR because it's really about clearing leftover technical debt from #15936. 
You'd be wise to not include these changes (not even this test) in this PR. 
However the work still remains to be done, and as the person with the best recent understanding of this area of the code, you seem to be a good candidate to get this done effectively.

**Review by tyler314 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/39486)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dt, @knz, @lucy-zhang, and @mjibson)

___
*[pkg/sql/show_create.go, line 237 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/39486#-LmZiqwe5p0Wo9HznUii:-LmjLEEZ9jRMIJz3s2AT:b44u2j) ([raw file](https://github.com/cockroachdb/cockroach/blob/9bee048f7cd70970875022cf2b041a6bebab14d8/pkg/sql/show_create.go#L237)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

I still see a `makeConstraint` here
</blockquote></details>

😓
___
*[pkg/sql/show_create.go, line 37 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/39486#-Lmi77fJ29B_5vqDI9D-:-LmjKv1c6B_umpd8Nfak:b44twe) ([raw file](https://github.com/cockroachdb/cockroach/blob/8a05127bc5882b66a120048990f89538a07f218e/pkg/sql/show_create.go#L37)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

:sparkling_heart: 
</blockquote></details>

🤗
___
*[pkg/sql/show_create.go, line 158 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/39486#-Lmi7PtfBExi53n4iLDL:-LmjLZqX6rE-XXjfLkto:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/8a05127bc5882b66a120048990f89538a07f218e/pkg/sql/show_create.go#L158)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

This could also perhaps move to the new file.
</blockquote></details>

Done.
___
*[pkg/sql/sqlbase/structured_test.go, line 2009 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/39486#-LmOc2qcBbkStyt4_xRk:-LmjMGqSBOR0M4VMZK0g:b1ytbqn) ([raw file](https://github.com/cockroachdb/cockroach/blob/480d96a818b2e7020b5d62e770bb0d4818e457d1/pkg/sql/sqlbase/structured_test.go#L2009)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

There are currently no unit tests for `(*IndexDescriptor) SQLString()` and `(*ColumnDescriptor) SQLString()`.
(I also personally _still_ am of the opinion these two methods should not exist at all. There should be Format methods taking a format context as argument. But that's not directly relevant here.)

Matt's initial request was to add the missing tests for at least one of these two methods. 
I see you have added asc/desc tests, which is part of the necessary work.
However there are other things to check as well, in particular that the names of the identifiers (index names, column names) are properly quoted when they contain special characters.

Now all this, of course, is not directly relevant to this PR because it's really about clearing leftover technical debt from #15936. 
You'd be wise to not include these changes (not even this test) in this PR. 
However the work still remains to be done, and as the person with the best recent understanding of this area of the code, you seem to be a good candidate to get this done effectively. 
</blockquote></details>

The compromise I would prefer to do is leave a TODO for either my future self or someone else you encounters it.
___
*[pkg/sql/show_clause.go, line 1 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/39486#-Lmi6aIdDDM_C-ogi8AO:-LmjGcRzBKCtfsvff4DP:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/8a05127bc5882b66a120048990f89538a07f218e/pkg/sql/show_clause.go#L1)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

`show_create_clauses.go`
</blockquote></details>

Done.
___
*[pkg/sql/show_clause.go, line 278 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/39486#-Lmi6fS1BtgknG54Oniu:-LmjKsrA1uNwrJJ7bhSD:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/8a05127bc5882b66a120048990f89538a07f218e/pkg/sql/show_clause.go#L278)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

1) you can make this a method of the `internalLookupCtx`

2) I don't think you need to export the method.
</blockquote></details>

Done.
___
*[pkg/sql/show_clause.go, line 302 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/39486#-Lmi6lrKBGrjlx3R-5ZT:-LmjKtQB2guH33sQArvL:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/8a05127bc5882b66a120048990f89538a07f218e/pkg/sql/show_clause.go#L302)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.

**Review by knz — APPROVED** [review]
:lgtm: thanks for all the good work

> Reviewed 1 of 8 files at r8, 5 of 5 files at r9.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/39486#-:-Lmjdxtr43Qi_KvvYRhT:b-hkzj2x)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @dt, @lucy-zhang, @mjibson, and @tyleroberts)

___
*[pkg/sql/resolver.go, line 654 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/39486#-LmjdaW5Em2en3DKsJSd:-LmjdaWL-PYz9o9eCDHq:bfoh7z2) ([raw file](https://github.com/cockroachdb/cockroach/blob/8f46266525c329ff72374a1116b9574cad98afae/pkg/sql/resolver.go#L654)):*
> ```Go
> }
> 
> // GetParentAsTableName returns a TreeTable object of the parent table for a
> ```

update the spelling of the method name in the comment
___
*[pkg/sql/resolver.go, line 674 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/39486#-Lmjdd8b3DF2iPUGPt1G:-Lmjdd8c-VAj7EZLVoz1:b-7ropln) ([raw file](https://github.com/cockroachdb/cockroach/blob/8f46266525c329ff72374a1116b9574cad98afae/pkg/sql/resolver.go#L674)):*
> ```Go
> }
> 
> // GetTableAsTableName returns a TableName object fot a given TableDescriptor.
> ```

ditto
___
*[pkg/sql/sqlbase/structured.go, line 509 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/39486#-LmjdkhSB0xUxXvz1aCD:-LmjdkhSB0xUxXvz1aCE:b-tw8aj4) ([raw file](https://github.com/cockroachdb/cockroach/blob/8f46266525c329ff72374a1116b9574cad98afae/pkg/sql/sqlbase/structured.go#L509)):*
> ```Go
> // TODO (tyler): This method needs more thorough testing, probably in
> // todo: structured_test.go. Or possibly replace it with a format method taking
> // todo: a format context as argument
> ```

1) maybe file an issue and include the issue number here

nits:

2) missing period at end of sentence

3) "todo:" prefixes on continuation lines are not necessary

**Review by tyler314 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/39486)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @dt, @knz, @lucy-zhang, and @mjibson)

___
*[pkg/sql/resolver.go, line 654 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/39486#-LmjdaW5Em2en3DKsJSd:-Lmjfbz63_uHB06Yq6DA:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/8f46266525c329ff72374a1116b9574cad98afae/pkg/sql/resolver.go#L654)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

update the spelling of the method name in the comment
</blockquote></details>

Done.
___
*[pkg/sql/resolver.go, line 674 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/39486#-Lmjdd8b3DF2iPUGPt1G:-LmjfcDE8EXXP6MRQEkR:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/8f46266525c329ff72374a1116b9574cad98afae/pkg/sql/resolver.go#L674)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.
___
*[pkg/sql/sqlbase/structured.go, line 509 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/39486#-LmjdkhSB0xUxXvz1aCD:-Lmjg469-urSBQ2fGuQp:b-guaylk) ([raw file](https://github.com/cockroachdb/cockroach/blob/8f46266525c329ff72374a1116b9574cad98afae/pkg/sql/sqlbase/structured.go#L509)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

1) maybe file an issue and include the issue number here

nits:

2) missing period at end of sentence

3) "todo:" prefixes on continuation lines are not necessary
</blockquote></details>

Done. Issue #39771
