### PR TITLE
changefeedccl: deflake TestChangefeedSchemaTTL

### LINKED ISSUE #149167: ccl/changefeedccl: TestChangefeedSchemaTTL failed
ccl/changefeedccl.TestChangefeedSchemaTTL [failed](https://mesolite.cluster.engflow.com/invocations/default/3f4ede90-eb1c-44ac-9dbd-f8705319812d?testReportRun=2&testReportShard=4&testReportAttempt=1#targets-Ly9wa2cvY2NsL2NoYW5nZWZlZWRjY2w6Y2hhbmdlZmVlZGNjbF90ZXN0) on master @ [20aa5054030c4e802024e734ea588db21257ab3a](https://github.com/cockroachdb/cockroach/commits/20aa5054030c4e802024e734ea588db21257ab3a):

```
=== RUN   TestChangefeedSchemaTTL
    test_log_scope.go:165: test logs captured to: outputs.zip/logTestChangefeedSchemaTTL3625926609
    test_log_scope.go:76: use -show-logs to present logs inline
    changefeed_test.go:6544: -- test log scope end --
test logs left over in: outputs.zip/logTestChangefeedSchemaTTL3625926609
--- FAIL: TestChangefeedSchemaTTL (36.93s)
=== RUN   TestChangefeedSchemaTTL/sinkless
    helpers_test.go:1241: making server as system tenant
    helpers_test.go:1317: making sinkless feed factory
    helpers_test.go:1382: pgURL sinkless SinklessFeedUser
    helpers_test.go:1382: pgURL sinkless root
    testfeed_test.go:294: sinkless feed creating changefeed: CREATE CHANGEFEED FOR TABLE foo
    testfeed_test.go:245: sinkless feed closing connection due to timeout (30s): CREATE CHANGEFEED FOR TABLE foo
    changefeed_test.go:6534: 
        	Error Trace:	pkg/ccl/changefeedccl/changefeed_test.go:6534
        	            				pkg/ccl/changefeedccl/helpers_test.go:1524
        	Error:      	Expect "read tcp 127.0.0.1:39922->127.0.0.1:34233: use of closed network connection" to match "GC threshold"
        	Test:       	TestChangefeedSchemaTTL/sinkless
    testfeed_test.go:301: closing sinkless feed
--- FAIL: TestChangefeedSchemaTTL/sinkless (36.92s)
```

Parameters:
 - <code>attempt=1</code>
 - <code>deadlock=true</code>
 - <code>run=2</code>
 - <code>shard=4</code>
<details><summary>Help</summary>
<p>

See also: [How To Investigate a Go Test Failure \(internal\)](https://cockroachlabs.atlassian.net/l/c/HgfXfJgM)
</p>
</details>
<details><summary>Same failure on other branches</summary>
<p>

- #148907 ccl/changefeedccl: TestChangefeedSchemaTTL failed [A-cdc C-test-failure O-robot T-cdc branch-release-25.3 release-blocker]
</p>
</details>
/cc @cockroachdb/cdc
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*TestChangefeedSchemaTTL.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/bazci/githubpost/issues)

</sub>

Jira issue: CRDB-52029

### PR DESCRIPTION
**Pull request by fqazi**
Previously, TestChangefeedSchemaTTL started flaking when create_table_with_schema_locked was enabled by default in the test suite. This happened because schema_locked tables can cause historical versions of descriptors to be cached in the lease manager, as the changefeed logic intentionally queries prior versions. As a result, even after the test garbage-collected the descriptors table, these old versions could remain in the in-memory cache, leading to flakes. To address this, this patch adds a canary schema change, which bumps the descriptor's version. When a descriptor's version is bumped, all older cached versions are purged.

Fixes: #149167
Informs: #153138
Informs: #154229
Informs: #154304
Informs: #154931

Release note: None

### CODE REVIEW

File: pkg/ccl/changefeedccl/changefeed_test.go [hunk 1]
```diff
@@ -7074,6 +7074,15 @@ func TestChangefeedSchemaTTL(t *testing.T) {
...
 		forceTableGC(t, s.SystemServer, sqlDB, "system", "descriptor")
 
+		// Do an unnecessary version bump on the descriptor, which will purge old
+		// versions of the descriptor that the lease manager may have cached for
+		// historical queries. When schema_locked support is active, the act of
+		// detecting polling inside pauseOrResumePolling can cause old versions
+		// to be cached. The historical descriptors are cleared everytime a
+		// version bump occurs, otherwise this test can flake if the prior versions
+		// need to decode a row is already cached.
+		waitForSchemaChange(t, sqlDB, "ALTER TABLE foo OWNER TO joe")
```
Comment (andyyang890) [inline pkg/ccl/changefeedccl/changefeed_test.go:7084]: Does this mean that for a real changefeed, if this situation happened, it wouldn't fail as expected without another descriptor bump?

**Review by andyyang890 — COMMENTED** [review]
Sorry for the delay, this PR slipped through my notifications

File: pkg/ccl/changefeedccl/changefeed_test.go (hunk 1 above)
Comment (asg0451) [reply pkg/ccl/changefeedccl/changefeed_test.go:7084]: i'm curious about this too. shouldnt unlocking schema locked itself be the descriptor version bump?

Comment (fqazi) [reply pkg/ccl/changefeedccl/changefeed_test.go:7084]: >Does this mean that for a real changefeed, if this situation happened, it wouldn't fail as expected without another descriptor bump?

So, just to be clear the lease manager in this specific test ends up caching historical versions. These are only purged when a new version of a descriptor shows up. 

The problem that happens in this test is that we bump the version, the new version is acquired (based on the lease managers range feed) and the old historcial versions are purged. When this test flakes we end up with a code path that request historical version, which can end up caching this  historical descriptor before the GC. 

The extra version bump here just guarantees all historical descriptors are purged incase any else reads it.

**Review by fqazi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/154879)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @andyyang890 and @asg0451)

**Review by andyyang890 — APPROVED** [review]

**Comment by fqazi** [comment]
@andyyang890 @asg0451 TFTR!

bors r+
