### PR TITLE
cli: fix dump with interleaved primary keys

### LINKED ISSUE #48323: sql: crdb_internal.create_statements contains invalid alter statement for interleaved table
**Describe the problem**

Creating a schema like below, and then dumping the database with 'cockroach dump', will result in invalid sql. (will fail with: "duplicate constraint name: "primary")

**To Reproduce**

Here is a quick bash script that will reproduce the problem. I've reduced the table definitions as much as I could.

It will:
1. create a single node cluster
2. create a 'bugdb' database
3. create two tables in bugdb: users and sessions, with sessions interleaved in users.
4. dump the database with 'cockroachdb dump'
5. attempt to restore the dump'ed database sql. this will fail.

```
#!/bin/bash

# cleanup previous runs
echo ___ cleanup previous runs __
killall cockroach
rm -rf cockroach-data
rm -rf schema.sql

echo ___ create a single node cluster ___
./cockroach start-single-node --insecure &
sleep 1 # wait for it to finish
DBURL="postgres://root@127.0.0.1:26257?sslmode=disable"

echo ___ create a test database ___
./cockroach sql --url $DBURL -e "DROP DATABASE IF EXISTS bugdb;create database bugdb" 

echo ___ create tables ___
./cockroach sql --database=bugdb --url $DBURL << EndOfMessage
CREATE TABLE users (
	id INT8 NOT NULL DEFAULT unique_rowid(),
	name STRING NULL,
	CONSTRAINT "primary" PRIMARY KEY (id ASC),
	INDEX by_plan_next_check (name ASC)
);

CREATE TABLE sessions (
	user_id INT8 NOT NULL,
	session_id INT8 NOT NULL,

	last_access TIMESTAMP NOT NULL,
	CONSTRAINT "primary" PRIMARY KEY (user_id ASC, session_id ASC),
	FAMILY "primary" (user_id, session_id),
	FAMILY updates (last_access)
) INTERLEAVE IN PARENT users (user_id);
EndOfMessage

echo ___ dumping schema ___
./cockroach dump bugdb --url $DBURL > schema.sql

echo ___ resetting bugdb ___
./cockroach sql --url $DBURL -e "DROP DATABASE IF EXISTS bugdb;create database bugdb" 

echo ___ importing schema ___
./cockroach sql --database bugdb --url $DBURL < schema.sql`
```

**Expected behavior**
To be able to re-import sql outputted from cockroachdb dump without errors. 

**Additional data / screenshots**

Here is the output of the above bash script:

```
___ cleanup previous runs __
___ create a single node cluster ___
*
* WARNING: RUNNING IN INSECURE MODE!
* 
* - Your cluster is open for any client that can access <all your IP addresses>.
* - Any user, even root, can log in without providing a password.
* - Any user, connecting as root, can read or write any data in your cluster.
* - There is no network encryption nor authentication, and thus no confidentiality.
* 
* Check out how to secure your cluster: https://www.cockroachlabs.com/docs/v19.2/secure-a-cluster.html
*
*
* WARNING: neither --listen-addr nor --advertise-addr was specified.
* The server will advertise "machinename.local" to other nodes, is this routable?
* 
* Consider using:
* - for local-only servers:  --listen-addr=localhost
* - for multi-node clusters: --advertise-addr=<host/IP addr>
* 
*
*
* INFO: Replication was disabled for this cluster.
* When/if adding nodes in the future, update zone configurations to increase the replication factor.
*
CockroachDB node starting at 2020-05-02 17:40:48.318798 +0000 UTC (took 0.5s)
build:               CCL v19.2.2 @ 2019/12/11 01:27:47 (go1.12.12)
webui:               http://machinename.local:8080
sql:                 postgresql://root@ machinename.local:26257?sslmode=disable
RPC client flags:    ./cockroach <client cmd> --host= machinename.local:26257 --insecure
logs:                /Users/me/Desktop/snapback/bug/cockroach-data/logs
temp dir:            /Users/me/Desktop/snapback/bug/cockroach-data/cockroach-temp379259450
external I/O path:   /Users/me/Desktop/snapback/bug/cockroach-data/extern
store[0]:            path=/Users/me/Desktop/snapback/bug/cockroach-data
status:              initialized new cluster
clusterID:           1cfaa30f-e314-4cb4-abd0-ced9d2f37a59
nodeID:              1
___ create a test database ___
CREATE DATABASE
___ create tables ___
CREATE TABLE

Time: 3.889ms

CREATE TABLE

Time: 7.298ms

___ dumping schema ___
___ resetting bugdb ___
CREATE DATABASE
___ importing schema ___
CREATE TABLE

Time: 3.236ms

CREATE TABLE

Time: 7.154ms

pq: duplicate constraint name: "primary"
Error: pq: duplicate constraint name: "primary"
Failed running "sql"`
```	

**Environment:**
 - CockroachDB version 19.2.2 and 19.2.6
 - Server OS: Mac
 - Client app `cockroach sql`

**Additional context**
Can't restore backups without hand-editing dump files. Scary and error-prone.

### PR DESCRIPTION
**Pull request by rohany**
Fixes #48323.

Release note (bug fix): Fixes a bug where `cockroach dump` on tables
with interleaved primary keys would erroneously include and extra
`CREATE UNIQUE INDEX "primary" ... INTERLEAVE IN PARENT` statement
in the dump output. This made it impossible to reimport dumped data
without manual editing.

### CODE REVIEW

File: pkg/cli/dump_test.go [hunk 1]
```diff
@@ -480,7 +481,7 @@ CREATE TABLE orders (
 ) INTERLEAVE IN PARENT customers (customer);
 
 ALTER TABLE orders ADD CONSTRAINT fk_customer FOREIGN KEY (customer) REFERENCES customers(id);
-CREATE UNIQUE INDEX "primary" ON orders (customer ASC, id ASC) INTERLEAVE IN PARENT customers (customer);
+CREATE INDEX i ON orders (customer ASC, total ASC) INTERLEAVE IN PARENT customers (customer);
```
Comment (jordanlewis) [inline pkg/cli/dump_test.go:484]: Whoa, this was super broken!

**Review by jordanlewis — APPROVED** [review]

**Comment by jordanlewis** [comment]
Should we backport this?

**Comment by rohany** [comment]
Yeah we need to -- it goes back to at least 19.2.

bors r+
