### PR TITLE
sql: add checks after all referenced columns have been backfilled

### LINKED ISSUE #35193: sql: panic when inserting into column with a check referencing a column created in the same transaction
```
create table t (a int);
begin;
alter table t add column b int;
alter table t add check (a > b);
insert into t (a) values (1);
commit;
```
We should be returning some reasonable error here, since `b` hasn't been created yet (even though we _do_ allow adding the check constraint), but this panics.
```
E190225 23:29:34.400802 423 sql/conn_executor.go:707  [n1,client=127.0.0.1:49528,user=root] a SQL panic has occurred while executing "INSERT INTO t(a) VALUES (1)": could not find return column
E190225 23:29:34.401522 423 util/log/crash_reporting.go:202  [n1,client=127.0.0.1:49528,user=root] a panic has occurred!
E190225 23:29:34.407584 423 util/log/crash_reporting.go:476  [n1,client=127.0.0.1:49528,user=root] Reported as error decdd91badac4695ad31330f9e452e17
panic: could not find return column [recovered]
	panic: could not find return column [recovered]
	panic: panic while executing 1 statements: INSERT INTO _(_) VALUES (_); caused by could not find return column

goroutine 423 [running]:
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).closeWrapper(0xc0017d8000, 0x742eac0, 0xc00174f980, 0x678a600, 0x73e92f0)
	/Users/lucy/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:721 +0x36d
github.com/cockroachdb/cockroach/pkg/sql.(*Server).ServeConn.func1(0xc0017d8000, 0x742eac0, 0xc00174f980)
	/Users/lucy/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:427 +0x61
panic(0x678a600, 0x73e92f0)
	/usr/local/go/src/runtime/panic.go:513 +0x1b9
github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder.(*Builder).Build.func1(0xc001732998)
	/Users/lucy/go/src/github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder/builder.go:142 +0x9a
panic(0x678a600, 0x73e92f0)
	/usr/local/go/src/runtime/panic.go:513 +0x1b9
github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder.(*mutationBuilder).mapToReturnColID(...)
	/Users/lucy/go/src/github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder/mutation_builder.go:477
github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder.(*mutationBuilder).disambiguateColumns(0xc001260580)
	/Users/lucy/go/src/github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder/mutation_builder.go:409 +0x369
github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder.(*mutationBuilder).addCheckConstraintCols(0xc001260580)
	/Users/lucy/go/src/github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder/mutation_builder.go:379 +0x72
github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder.(*mutationBuilder).buildInsert(0xc001260580, 0x0, 0x0, 0x0)
	/Users/lucy/go/src/github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder/insert.go:592 +0x2f
github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder.(*Builder).buildInsert(0xc0013e54a0, 0xc001522820, 0xc00186d800, 0x0)
	/Users/lucy/go/src/github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder/insert.go:242 +0x606
github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder.(*Builder).buildStmt(0xc0013e54a0, 0x7434040, 0xc001522820, 0xc00186d800, 0x4)
	/Users/lucy/go/src/github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder/builder.go:205 +0x3b2
github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder.(*Builder).Build(0xc0013e54a0, 0x0, 0x0)
	/Users/lucy/go/src/github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder/builder.go:156 +0x111
github.com/cockroachdb/cockroach/pkg/sql.(*optPlanningCtx).buildExecMemo(0xc000bc9b90, 0x742eb80, 0xc001178930, 0xc001522820, 0x742eb80, 0xc001178930, 0x4060500)
	/Users/lucy/go/src/github.com/cockroachdb/cockroach/pkg/sql/plan_opt.go:384 +0x188
github.com/cockroachdb/cockroach/pkg/sql.(*planner).makeOptimizerPlan(0xc0017d8460, 0x742eb80, 0xc001178930, 0x6c9f60d, 0x19, 0xb1379ec2866e, 0xe17e25588)
	/Users/lucy/go/src/github.com/cockroachdb/cockroach/pkg/sql/plan_opt.go:146 +0xc8
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).makeExecPlan(0xc0017d8000, 0x742eb80, 0xc001178930, 0xc0017d8460, 0x6, 0x400e3af)
	/Users/lucy/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:928 +0x11b
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).dispatchToExecutionEngine(0xc0017d8000, 0x742eb80, 0xc001178930, 0xc0017d8460, 0xf498098, 0xc001510840, 0x0, 0x0)
	/Users/lucy/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:823 +0x148
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execStmtInOpenState(0xc0017d8000, 0x742eb80, 0xc001178930, 0x7434040, 0xc001522820, 0xc0018045f7, 0x1c, 0x0, 0x0, 0x0, ...)
	/Users/lucy/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:436 +0xd8c
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execStmt(0xc0017d8000, 0x742eb80, 0xc001178930, 0x7434040, 0xc001522820, 0xc0018045f7, 0x1c, 0x0, 0x0, 0x0, ...)
	/Users/lucy/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:93 +0x36f
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).run(0xc0017d8000, 0x742eac0, 0xc00174f980, 0xc000dfc0f8, 0x5400, 0x15000, 0xc000dfc190, 0xc00174a730, 0x0, 0x0)
	/Users/lucy/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:1182 +0x21e5
github.com/cockroachdb/cockroach/pkg/sql.(*Server).ServeConn(0xc000e0a000, 0x742eac0, 0xc00174f980, 0xc0017d8000, 0x5400, 0x15000, 0xc000dfc190, 0xc00174a730, 0x0, 0x0)
	/Users/lucy/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:429 +0xce
github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*conn).serveImpl.func4(0xc000e0a000, 0xc000505b00, 0xc00047a944, 0xc00174a730, 0x742eac0, 0xc00174f980, 0xc0017d8000, 0x5400, 0x15000, 0xc000dfc190, ...)
	/Users/lucy/go/src/github.com/cockroachdb/cockroach/pkg/sql/pgwire/conn.go:331 +0xcf
created by github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*conn).serveImpl
	/Users/lucy/go/src/github.com/cockroachdb/cockroach/pkg/sql/pgwire/conn.go:314 +0x1040
```
This is probably ultimately caused by the fact that we add check constraints to the table descriptor immediately, even when the columns they refer to are not yet public. We account for this in parts of the code by looking at columns in the mutations list in addition to public columns, but not everywhere.

edit: This only happens with the optimizer turned on. Otherwise, we get the error `pq: column "b" does not exist` on the insert, which is better (though cryptic-seeming).

### LINKED ISSUE #35258: sql: don't enforce checks referencing non-public columns until they are backfilled
If a check constraint is added to a column that is being added, and the constraint references a different public column, e.g.,
```
CREATE TABLE t (a INT);
ALTER TABLE t ADD COLUMN b INT, ADD CHECK (b > a);
```
then writes to column `a` that occur before the backfill for column `b` is complete can result in erroneous behavior; see #35193 for more context. This is because the check constraint is always immediately added to the table descriptor, even when some of the columns it references are not yet public. Writes to `a` will attempt to enforce the check constraint using the non-public columns, which will appear to contain NULL values if the backfill is not complete.

The solution is to wait until all dependent columns are backfilled (but not public), publish the table descriptor with the constraint on it, validate the constraint for existing rows, and then finally make all the columns public. (In a sense, this means that "fully backfilled but not public" is now a special "state" for a column/index that is relevant for constraints being added, even though it's not a state recognized by the schema changer.)

One solution @dt and I discussed is to add a new mutation type for adding constraints, whose "backfill" step is just to publish a new version of the table descriptor with the constraint on it. When a constraint is added, two mutations are queued, one to add the constraint and one to validate it. This has the advantage of easily supporting `NOT VALID` constraints later on. Another solution would be to change the existing single-mutation implementation to only add the constraint after the column backfills are complete. Either way, this won't involve changing CRUD operations to be aware of those mutations.

Waiting for all dependent schema elements to be backfilled is also going to be necessary for conforming FKs to this process of validating constraints, since it's not even possible to enforce FKs on writes unless the indexes (and columns) are backfilled.

### PR DESCRIPTION
**Pull request by thoszhang**
Previously, if a column was added with a check constraint that also referenced
another column that was public, writes to that public column would erroneously
fail (and, in the worst case, result in a panic) while the column being added
was not yet public. With this change, the schema changer will now wait to add
the check constraint to the table descriptor until after all the columns that
were added in the same transaction have been backfilled.

A new optional field has been added to `ConstraintToValidate` for the check
constraint itself, so that it can be added to the table descriptor at the
correct step in the schema change process.

I ended up adding this field to the existing mutation instead of creating a new
type of mutation to add the constraint to the descriptor, since it ultimately
seemed to me that a mutation that simply adds a schema element in its backfill
step would be too inconsistent with what mutations are, especially since all
the mutations for a single transaction are basically executed at the same time.
To support NOT VALID in the future, we could add more flags to the protobuf to
indicate that either the addition of the constraint or the validation should be
skipped, so that they can be executed separately.

Fixes #35258, fixes #35193

Release note: None

### CODE REVIEW

File: pkg/sql/backfill.go [hunk 1]
```diff
@@ -209,6 +221,39 @@ func (sc *SchemaChanger) runBackfill(
 		}
 	}
 
+	// Make check constraints public (or drop them, if it's a rollback).
+	if len(addedChecks) > 0 || len(droppedChecks) > 0 {
+		_, err := sc.leaseMgr.Publish(ctx, sc.tableID,
+			func(desc *sqlbase.MutableTableDescriptor) error {
+				checks := make([]*sqlbase.TableDescriptor_CheckConstraint, 0)
+				for _, c := range desc.Checks {
```
Comment (dt) [inline pkg/sql/backfill.go]: as discussed in person: I think we need to make the addition to the table desc idempotent -- either check the name, or update the mutation or something.

File: pkg/sql/backfill.go [hunk 2]
```diff
@@ -209,6 +221,39 @@ func (sc *SchemaChanger) runBackfill(
...
+			},
+			func(txn *client.Txn) error {
+				return nil
+			},
+		)
+		if err != nil {
+			return err
+		}
+	}
+
```
Comment (dt) [inline pkg/sql/backfill.go]: as discussed in person: do we need to explicitly wait for one version here?

**Review by dt — APPROVED** [review]

File: pkg/sql/sqlbase/structured.go [hunk 3]
```diff
@@ -584,6 +584,25 @@ func (desc *TableDescriptor) AllNonDropIndexes() []*IndexDescriptor {
 	return indexes
 }
 
+// AllPublicAndNonPublicChecks returns all the checks, including those being
+// added in the mutations.
+func (desc *TableDescriptor) AllPublicAndNonPublicChecks() []*TableDescriptor_CheckConstraint {
```
Comment (andy-kimball) [inline pkg/sql/sqlbase/structured.go]: Need a better name here, since it sounds the same as the existing `AllChecks` method. I wouldn't know which to use.

File: pkg/sql/backfill.go (hunk 1 above)
Comment (lucy-zhang) [reply pkg/sql/backfill.go]: Done.

File: pkg/sql/backfill.go (hunk 2 above)
Comment (lucy-zhang) [reply pkg/sql/backfill.go]: Yes, done.

File: pkg/sql/sqlbase/structured.go (hunk 3 above)
Comment (lucy-zhang) [reply pkg/sql/sqlbase/structured.go]: I updated it so that constraints are either "active" (should be enforced for writes) or "inactive" (queued but invisible to writes). I'm open to better suggestions.

**Comment by lucy-zhang** [comment]
This is ready for another look.

File: pkg/sql/sqlbase/structured.go (hunk 3 above)
Comment (andy-kimball) [reply pkg/sql/sqlbase/structured.go]: Seems reasonable.

**Review by vivekmenezes — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/35300)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dt, @lucy-zhang, and @vivekmenezes)

___
*[pkg/sql/backfill.go, line 208 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/35300#-L_IcEfqDJPkvH1BuFRe:-L_IcEfqDJPkvH1BuFRf:bn60ofo) ([raw file](https://github.com/cockroachdb/cockroach/blob/b2fecda92cc38efb5f73db6f19cb0e4461ef13bd/pkg/sql/backfill.go#L208)):*
> ```Go
> 			return err
> 		}
> 		version = desc.Version
> ```

Add a comment here
___
*[pkg/sql/backfill.go, line 332 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/35300#-L_IdLAXD1blgkJ473vR:-L_IdLAY4iPQmY_cnlH9:b-5t6eyy) ([raw file](https://github.com/cockroachdb/cockroach/blob/b2fecda92cc38efb5f73db6f19cb0e4461ef13bd/pkg/sql/backfill.go#L332)):*
> ```Go
> 	return desc, nil
> }
> ```

Both the above two functions have nothing to do with backfilling. I'd suggest calling them before the backfiller is called. Can you call them from RunStateMachineBeforeBackfill? Seems like you can for dropChecksInRollback. perhaps we can call  addChecks() in schemachanger.done()

**Review by thoszhang — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/35300)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dt, @lucy-zhang, and @vivekmenezes)

___
*[pkg/sql/backfill.go, line 332 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/35300#-L_IdLAXD1blgkJ473vR:-L_JKlKW94CxT2WAxuyi:byfd88s) ([raw file](https://github.com/cockroachdb/cockroach/blob/b2fecda92cc38efb5f73db6f19cb0e4461ef13bd/pkg/sql/backfill.go#L332)):*
<details><summary><i>Previously, vivekmenezes wrote…</i></summary><blockquote>

Both the above two functions have nothing to do with backfilling. I'd suggest calling them before the backfiller is called. Can you call them from RunStateMachineBeforeBackfill? Seems like you can for dropChecksInRollback. perhaps we can call  addChecks() in schemachanger.done()
</blockquote></details>

Yeah, `dropChecksInRollback()` could be moved to `RunStateMachineBeforeBackfill`. The problem is that `addChecks()` has to be called before the check is validated. So if we moved `addChecks()` to `schemachanger.done()`, validation would have to happen in `done()` as well, which seems undesirable.

We also can't call `addChecks()` before the column backfill is complete. If we do, then the constraint evaluator will see NULL values in the non-public column, even for columns which have default/computed values. In practice this might be fine for most checks, which will always pass if the expression evaluates to NULL, so we'll just let allow those writes and then find all violations at the end. But ultimately I don't think it's a good idea to have an "active" constraint that's being enforced on a column that's not fully backfilled yet. (There's a test here with an explicit NOT NULL condition that demonstrates this problem: https://github.com/cockroachdb/cockroach/pull/35300/files#diff-e38d0cfdbd3babbd39d2de3495f5ed86R1104). A similar issue exists for FKs: we don't want to add the backreference visible to updates/deletes on the referenced columns until the index on the referencing columns is fully backfilled.

**Review by thoszhang — COMMENTED** [review]
This is ready for another look. The changes were:
* restoring the function call to drop checks that failed validation to `reverseMutations()`, where it was originally, since it didn't actually seem like there was a good place to put it in any other step of the schema changer
* rebasing to incorporate #35091 (to rename constraints)
* adding more logic tests for schema change rollbacks and for the original bug in the case of computed columns
* adding more comments

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/35300#-:-L_jP1eYE4l0wgWUeQ7S:b-n6brpd)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dt, @lucy-zhang, and @vivekmenezes)

**Review by vivekmenezes — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/35300)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dt and @lucy-zhang)

___
*[pkg/sql/backfill.go, line 186 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/35300#-L_n3uinBsl1lQO2wA1j:-L_n3uinBsl1lQO2wA1k:b-mkv7ku) ([raw file](https://github.com/cockroachdb/cockroach/blob/8badb35591a8671253226ba98181b2f4ef8c39d8/pkg/sql/backfill.go#L186)):*
> ```Go
> 				if !m.Rollback {
> 					panic("trying to drop constraint through schema changer outside of a rollback")
> 				}
> ```

while I see the value of having a panic here I think it's better to return an error.
___
*[pkg/sql/backfill.go, line 269 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/35300#-L_n46q2CkZ92mO-1Q9s:-L_n46q2CkZ92mO-1Q9t:b-2a4uuj) ([raw file](https://github.com/cockroachdb/cockroach/blob/8badb35591a8671253226ba98181b2f4ef8c39d8/pkg/sql/backfill.go#L269)):*
> ```Go
> 			return nil
> 		},
> 		func(txn *client.Txn) error {
> ```

I believe you can use nil instead of using a dummy function
___
*[pkg/sql/sqlbase/structured.go, line 605 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/35300#-L_n4sQk6T0DG8MwFfYj:-L_n4sQk6T0DG8MwFfYk:b-iy5akb) ([raw file](https://github.com/cockroachdb/cockroach/blob/8badb35591a8671253226ba98181b2f4ef8c39d8/pkg/sql/sqlbase/structured.go#L605)):*
> ```Go
> 	}
> 	return checks
> }
> ```

Its better to construct the list active and inactive checks once in NewImmutableTableDescriptor() and return it here.

**Review by thoszhang — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/35300)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dt, @lucy-zhang, and @vivekmenezes)

___
*[pkg/sql/backfill.go, line 186 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/35300#-L_n3uinBsl1lQO2wA1j:-L_omdlXErlvmJdXmCRH:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/8badb35591a8671253226ba98181b2f4ef8c39d8/pkg/sql/backfill.go#L186)):*
<details><summary><i>Previously, vivekmenezes wrote…</i></summary><blockquote>

while I see the value of having a panic here I think it's better to return an error.
</blockquote></details>

Done.
___
*[pkg/sql/backfill.go, line 269 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/35300#-L_n46q2CkZ92mO-1Q9s:-L_omeazCdrwg-cciqWN:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/8badb35591a8671253226ba98181b2f4ef8c39d8/pkg/sql/backfill.go#L269)):*
<details><summary><i>Previously, vivekmenezes wrote…</i></summary><blockquote>

I believe you can use nil instead of using a dummy function
</blockquote></details>

Done.
___
*[pkg/sql/sqlbase/structured.go, line 605 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/35300#-L_n4sQk6T0DG8MwFfYj:-L_ojGAcAjliDbWWkZlj:bshcfnw) ([raw file](https://github.com/cockroachdb/cockroach/blob/8badb35591a8671253226ba98181b2f4ef8c39d8/pkg/sql/sqlbase/structured.go#L605)):*
<details><summary><i>Previously, vivekmenezes wrote…</i></summary><blockquote>

Its better to construct the list active and inactive checks once in NewImmutableTableDescriptor() and return it here.
</blockquote></details>

I made this a `TableDescriptor` method because it only gets called when when schema changes are being performed and it doesn't make sense to use `ImmutableTableDescriptor`. This is also consistent with methods like `AllNonDropIndexes()` above, though I agree there is some duplicated logic which is not ideal.

**Review by vivekmenezes — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/35300)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dt and @lucy-zhang)
