### PR TITLE
sql: fix internal error when trying to parse strings as arrays

### LINKED ISSUE #52134: sql: v20.2.0-alpha.2: could not parse value as requested type - unknown type
This issue was autofiled by Sentry. It represents a crash or reported error on a live cluster with telemetry enabled.

Sentry link: https://sentry.io/organizations/cockroach-labs/issues/1815307939/?referrer=webhooks_plugin

Panic message:

>*errors.errorString
*safedetails.withSafeDetails: unknown type %s (%T) (1)
parse_string.go:85: *withstack.withStack (top exception)
*assert.withAssertionFailure
*errutil.withMessage
*safedetails.withSafeDetails: could not parse %q as type %s (2)
datum.go:267: *withstack.withStack (3)
*pgerror.withCandidateCode: 22P02 (4)
(check the extra data payloads)

<details>
<summary>Stacktrace (expand for inline code snippets):</summary>

https://github.com/cockroachdb/cockroach/blob/d3119926d33d808c6384cf3e99a7f7435f395489/pkg/sql/sem/tree/datum.go#L266-L268 in pkg/sql/sem/tree.makeParseError
https://github.com/cockroachdb/cockroach/blob/d3119926d33d808c6384cf3e99a7f7435f395489/pkg/sql/sem/tree/parse_array.go#L160-L162 in pkg/sql/sem/tree.ParseDArrayFromString
https://github.com/cockroachdb/cockroach/blob/d3119926d33d808c6384cf3e99a7f7435f395489/pkg/sql/sem/tree/parse_string.go#L28-L30 in pkg/sql/sem/tree.ParseAndRequireString
https://github.com/cockroachdb/cockroach/blob/d3119926d33d808c6384cf3e99a7f7435f395489/pkg/sql/sem/tree/constant.go#L570-L572 in pkg/sql/sem/tree.(*StrVal).ResolveAsType
https://github.com/cockroachdb/cockroach/blob/d3119926d33d808c6384cf3e99a7f7435f395489/pkg/sql/sem/tree/constant.go#L72-L74 in pkg/sql/sem/tree.typeCheckConstant
https://github.com/cockroachdb/cockroach/blob/d3119926d33d808c6384cf3e99a7f7435f395489/pkg/sql/sem/tree/type_check.go#L1369-L1371 in pkg/sql/sem/tree.(*StrVal).TypeCheck
https://github.com/cockroachdb/cockroach/blob/d3119926d33d808c6384cf3e99a7f7435f395489/pkg/sql/sem/tree/type_check.go#L1203-L1205 in pkg/sql/sem/tree.(*ParenExpr).TypeCheck
https://github.com/cockroachdb/cockroach/blob/d3119926d33d808c6384cf3e99a7f7435f395489/pkg/sql/sem/tree/type_check.go#L517-L519 in pkg/sql/sem/tree.(*IndirectionExpr).TypeCheck
https://github.com/cockroachdb/cockroach/blob/d3119926d33d808c6384cf3e99a7f7435f395489/pkg/sql/sem/tree/type_check.go#L252-L254 in pkg/sql/sem/tree.TypeCheck
https://github.com/cockroachdb/cockroach/blob/d3119926d33d808c6384cf3e99a7f7435f395489/pkg/sql/opt/optbuilder/scope.go#L426-L428 in pkg/sql/opt/optbuilder.(*scope).resolveType
https://github.com/cockroachdb/cockroach/blob/d3119926d33d808c6384cf3e99a7f7435f395489/pkg/sql/opt/optbuilder/project.go#L149-L151 in pkg/sql/opt/optbuilder.(*Builder).analyzeSelectList
https://github.com/cockroachdb/cockroach/blob/d3119926d33d808c6384cf3e99a7f7435f395489/pkg/sql/opt/optbuilder/project.go#L83-L85 in pkg/sql/opt/optbuilder.(*Builder).analyzeProjectionList
https://github.com/cockroachdb/cockroach/blob/d3119926d33d808c6384cf3e99a7f7435f395489/pkg/sql/opt/optbuilder/select.go#L1044-L1046 in pkg/sql/opt/optbuilder.(*Builder).buildSelectClause
https://github.com/cockroachdb/cockroach/blob/d3119926d33d808c6384cf3e99a7f7435f395489/pkg/sql/opt/optbuilder/select.go#L981-L983 in pkg/sql/opt/optbuilder.(*Builder).buildSelectStmtWithoutParens
https://github.com/cockroachdb/cockroach/blob/d3119926d33d808c6384cf3e99a7f7435f395489/pkg/sql/opt/optbuilder/select.go#L954-L956 in pkg/sql/opt/optbuilder.(*Builder).buildSelect.func1
https://github.com/cockroachdb/cockroach/blob/d3119926d33d808c6384cf3e99a7f7435f395489/pkg/sql/opt/optbuilder/with.go#L28-L30 in pkg/sql/opt/optbuilder.(*Builder).processWiths
https://github.com/cockroachdb/cockroach/blob/d3119926d33d808c6384cf3e99a7f7435f395489/pkg/sql/opt/optbuilder/select.go#L953-L955 in pkg/sql/opt/optbuilder.(*Builder).buildSelect
https://github.com/cockroachdb/cockroach/blob/d3119926d33d808c6384cf3e99a7f7435f395489/pkg/sql/opt/optbuilder/builder.go#L247-L249 in pkg/sql/opt/optbuilder.(*Builder).buildStmt
https://github.com/cockroachdb/cockroach/blob/d3119926d33d808c6384cf3e99a7f7435f395489/pkg/sql/opt/optbuilder/builder.go#L211-L213 in pkg/sql/opt/optbuilder.(*Builder).buildStmtAtRoot
https://github.com/cockroachdb/cockroach/blob/d3119926d33d808c6384cf3e99a7f7435f395489/pkg/sql/opt/optbuilder/builder.go#L182-L184 in pkg/sql/opt/optbuilder.(*Builder).Build
https://github.com/cockroachdb/cockroach/blob/d3119926d33d808c6384cf3e99a7f7435f395489/pkg/sql/plan_opt.go#L349-L351 in pkg/sql.(*optPlanningCtx).buildReusableMemo
https://github.com/cockroachdb/cockroach/blob/d3119926d33d808c6384cf3e99a7f7435f395489/pkg/sql/plan_opt.go#L119-L121 in pkg/sql.(*planner).prepareUsingOptimizer
https://github.com/cockroachdb/cockroach/blob/d3119926d33d808c6384cf3e99a7f7435f395489/pkg/sql/conn_executor_prepare.go#L237-L239 in pkg/sql.(*connExecutor).populatePrepared
https://github.com/cockroachdb/cockroach/blob/d3119926d33d808c6384cf3e99a7f7435f395489/pkg/sql/conn_executor_prepare.go#L179-L181 in pkg/sql.(*connExecutor).prepare.func1
https://github.com/cockroachdb/cockroach/blob/d3119926d33d808c6384cf3e99a7f7435f395489/pkg/kv/db.go#L710-L712 in pkg/kv.(*DB).Txn.func1
https://github.com/cockroachdb/cockroach/blob/d3119926d33d808c6384cf3e99a7f7435f395489/pkg/kv/txn.go#L802-L804 in pkg/kv.(*Txn).exec
https://github.com/cockroachdb/cockroach/blob/d3119926d33d808c6384cf3e99a7f7435f395489/pkg/kv/db.go#L709-L711 in pkg/kv.(*DB).Txn
https://github.com/cockroachdb/cockroach/blob/d3119926d33d808c6384cf3e99a7f7435f395489/pkg/sql/conn_executor_prepare.go#L191-L193 in pkg/sql.(*connExecutor).prepare
https://github.com/cockroachdb/cockroach/blob/d3119926d33d808c6384cf3e99a7f7435f395489/pkg/sql/conn_executor_prepare.go#L105-L107 in pkg/sql.(*connExecutor).addPreparedStmt
https://github.com/cockroachdb/cockroach/blob/d3119926d33d808c6384cf3e99a7f7435f395489/pkg/sql/conn_executor_prepare.go#L51-L53 in pkg/sql.(*connExecutor).execPrepare
https://github.com/cockroachdb/cockroach/blob/d3119926d33d808c6384cf3e99a7f7435f395489/pkg/sql/conn_executor.go#L1436-L1438 in pkg/sql.(*connExecutor).execCmd
https://github.com/cockroachdb/cockroach/blob/d3119926d33d808c6384cf3e99a7f7435f395489/pkg/sql/conn_executor.go#L1295-L1297 in pkg/sql.(*connExecutor).run
</details>

```
pkg/sql/sem/tree/datum.go in pkg/sql/sem/tree.makeParseError at line 267
pkg/sql/sem/tree/parse_array.go in pkg/sql/sem/tree.ParseDArrayFromString at line 161
pkg/sql/sem/tree/parse_string.go in pkg/sql/sem/tree.ParseAndRequireString at line 29
pkg/sql/sem/tree/constant.go in pkg/sql/sem/tree.(*StrVal).ResolveAsType at line 571
pkg/sql/sem/tree/constant.go in pkg/sql/sem/tree.typeCheckConstant at line 73
pkg/sql/sem/tree/type_check.go in pkg/sql/sem/tree.(*StrVal).TypeCheck at line 1370
pkg/sql/sem/tree/type_check.go in pkg/sql/sem/tree.(*ParenExpr).TypeCheck at line 1204
pkg/sql/sem/tree/type_check.go in pkg/sql/sem/tree.(*IndirectionExpr).TypeCheck at line 518
pkg/sql/sem/tree/type_check.go in pkg/sql/sem/tree.TypeCheck at line 253
pkg/sql/opt/optbuilder/scope.go in pkg/sql/opt/optbuilder.(*scope).resolveType at line 427
pkg/sql/opt/optbuilder/project.go in pkg/sql/opt/optbuilder.(*Builder).analyzeSelectList at line 150
pkg/sql/opt/optbuilder/project.go in pkg/sql/opt/optbuilder.(*Builder).analyzeProjectionList at line 84
pkg/sql/opt/optbuilder/select.go in pkg/sql/opt/optbuilder.(*Builder).buildSelectClause at line 1045
pkg/sql/opt/optbuilder/select.go in pkg/sql/opt/optbuilder.(*Builder).buildSelectStmtWithoutParens at line 982
pkg/sql/opt/optbuilder/select.go in pkg/sql/opt/optbuilder.(*Builder).buildSelect.func1 at line 955
pkg/sql/opt/optbuilder/with.go in pkg/sql/opt/optbuilder.(*Builder).processWiths at line 29
pkg/sql/opt/optbuilder/select.go in pkg/sql/opt/optbuilder.(*Builder).buildSelect at line 954
pkg/sql/opt/optbuilder/builder.go in pkg/sql/opt/optbuilder.(*Builder).buildStmt at line 248
pkg/sql/opt/optbuilder/builder.go in pkg/sql/opt/optbuilder.(*Builder).buildStmtAtRoot at line 212
pkg/sql/opt/optbuilder/builder.go in pkg/sql/opt/optbuilder.(*Builder).Build at line 183
pkg/sql/plan_opt.go in pkg/sql.(*optPlanningCtx).buildReusableMemo at line 350
pkg/sql/plan_opt.go in pkg/sql.(*planner).prepareUsingOptimizer at line 120
pkg/sql/conn_executor_prepare.go in pkg/sql.(*connExecutor).populatePrepared at line 238
pkg/sql/conn_executor_prepare.go in pkg/sql.(*connExecutor).prepare.func1 at line 180
pkg/kv/db.go in pkg/kv.(*DB).Txn.func1 at line 711
pkg/kv/txn.go in pkg/kv.(*Txn).exec at line 803
pkg/kv/db.go in pkg/kv.(*DB).Txn at line 710
pkg/sql/conn_executor_prepare.go in pkg/sql.(*connExecutor).prepare at line 192
pkg/sql/conn_executor_prepare.go in pkg/sql.(*connExecutor).addPreparedStmt at line 106
pkg/sql/conn_executor_prepare.go in pkg/sql.(*connExecutor).execPrepare at line 52
pkg/sql/conn_executor.go in pkg/sql.(*connExecutor).execCmd at line 1437
pkg/sql/conn_executor.go in pkg/sql.(*connExecutor).run at line 1296
```

| Tag | Value |
|---|---|
| Cockroach Release | `v20.2.0-alpha.2` |
| Cockroach SHA: | d3119926d33d808c6384cf3e99a7f7435f395489 |
| Platform | darwin amd64 |
| Distribution | CCL |
| Environment | v20.2.0-alpha.2 |
| Command | server |
| Go Version | ``|
| # of CPUs ||
| # of Goroutines ||

### PR DESCRIPTION
**Pull request by RaduBerinde**
The parse-constant-as-type code was allowing a desired type of `Array[Any]`, and
we can't parse elements as `Any`. This resulted in an internal error, rather
than a normal query error.

Fixes #52134.

Release note (bug fix): Fixed an internal error involving string literals used
as arrays.

### CODE REVIEW

File: pkg/sql/sem/tree/constant.go [hunk 1]
```diff
@@ -63,11 +63,20 @@ func isConstant(expr Expr) bool {
...
+	}
+	return t.Family() != types.AnyFamily
+}
+
 func typeCheckConstant(
 	ctx context.Context, semaCtx *SemaContext, c Constant, desired *types.T,
 ) (ret TypedExpr, err error) {
 	avail := c.AvailableTypes()
-	if desired.Family() != types.AnyFamily {
+	if isDefiniteType(desired) {
```
Comment (rohany) [inline pkg/sql/sem/tree/constant.go:79]: I think we have a function `typ.IsAmbiguous` that does something like this already

**Review by RaduBerinde — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/52416)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @otan and @rohany)

___
*[pkg/sql/sem/tree/constant.go, line 79 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/52416#-MDzeSI39wdlZ-9UlYKw-r1-79:-MDzlv-u5KG6CiG0-lTV:bh7pl62) ([raw file](https://github.com/cockroachdb/cockroach/blob/4d7b314a097770f94fd5286a04bc42c80e26f808/pkg/sql/sem/tree/constant.go#L79)):*
<details><summary><i>Previously, rohany (Rohan Yadav) wrote…</i></summary><blockquote>

I think we have a function `typ.IsAmbiguous` that does something like this already
</blockquote></details>

Awesome!! Done.

**Review by rohany — APPROVED** [review]

**Review by otan — APPROVED** [review]
