### PR TITLE
backup: fix race condition in starting compaction job

### LINKED ISSUE #149867: roachtest: backupFixture/tpcc/warehouses=5000/incrementals=48 failed
roachtest.backupFixture/tpcc/warehouses=5000/incrementals=48 [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyAzureBazel/20141915?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyAzureBazel/20141915?buildTab=artifacts#/backupFixture/tpcc/warehouses=5000/incrementals=48) on master @ [9ddf582e7c38e1b5e844b1f6dfc014ac5f8843c0](https://github.com/cockroachdb/cockroach/commits/9ddf582e7c38e1b5e844b1f6dfc014ac5f8843c0):

```
(assertions.go:369).Fail: 
	Error Trace:	pkg/cmd/roachtest/tests/backup_fixtures.go:654
	            				pkg/cmd/roachtest/test_runner.go:1389
	            				src/runtime/asm_amd64.s:1700
	Error:      	Received unexpected error:
	            	compaction jobs failed while running incrementals: [{1088090079106859012 failed no incrementals found with the specified start time 1752128940.000000000,0}]
	            	(1) attached stack trace
	            	  -- stack trace:
	            	  | github.com/cockroachdb/cockroach/pkg/cmd/roachtest/tests.(*backupDriver).monitorBackups
	            	  | 	pkg/cmd/roachtest/tests/backup_fixtures.go:333
	            	  | github.com/cockroachdb/cockroach/pkg/cmd/roachtest/tests.registerBackupFixtures.func1
	            	  | 	pkg/cmd/roachtest/tests/backup_fixtures.go:654
	            	  | main.(*testRunner).runTest.func2
	            	  | 	pkg/cmd/roachtest/test_runner.go:1389
	            	  | runtime.goexit
	            	  | 	src/runtime/asm_amd64.s:1700
	            	Wraps: (2) compaction jobs failed while running incrementals: [{1088090079106859012 failed no incrementals found with the specified start time 1752128940.000000000,0}]
	            	Error types: (1) *withstack.withStack (2) *errutil.leafError
	Test:       	backupFixture/tpcc/warehouses=5000/incrementals=48
(require.go:1357).NoError: FailNow called
test artifacts and logs in: /artifacts/backupFixture/tpcc/warehouses=5000/incrementals=48/run_1
```

Parameters:
 - <code>arch=amd64</code>
 - <code>cloud=azure</code>
 - <code>coverageBuild=false</code>
 - <code>cpu=8</code>
 - <code>encrypted=true</code>
 - <code>fs=ext4</code>
 - <code>localSSD=false</code>
 - <code>runtimeAssertionsBuild=false</code>
 - <code>ssd=0</code>
<details><summary>Help</summary>
<p>

See: [roachtest README](https://github.com/cockroachdb/cockroach/blob/master/pkg/cmd/roachtest/README.md)

See: [How To Investigate \(internal\)](https://cockroachlabs.atlassian.net/l/c/SSSBr8c7)

_Grafana is not yet available for azure clusters_</p>
</details>
/cc @cockroachdb/disaster-recovery
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*backupFixture/tpcc/warehouses=5000/incrementals=48.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/bazci/githubpost/issues)

</sub>

Jira issue: CRDB-52373

### PR DESCRIPTION
**Pull request by kev-cao**
In #145930, scheduled compactions are blocked from running if another compaction job is running for the schedule. However, it is currently possible for there to be a race condition which results in a compaction job being unable to find an incremental backup. Take the following circumstance:

1. Compaction job A starts.
2. A scheduled backup B completes and begins considering whether a compaction job should run. It fetches the current chain to its end time and finds that it should run a compaction.
3. Compaction job A completes.
4. B starts a transaction to create the compaction job. Because A has completed, it does not block the job from being created.
5. B creates a compaction job C that has a start time that is now skipped due to A's completion.
6. When C is picked up by the job system, it resolves the backup chain again, which now no longer has its start time and it fails.

This is resolved by opening a transaction before fetching the backup chain to check for an already running compaction job ID.

Fixes: #149867, #147264

Release note: None

### CODE REVIEW

File: pkg/backup/compaction_job.go [hunk 1]
```diff
@@ -133,6 +115,25 @@ func maybeStartCompactionJob(
 				args.CompactionJobID, triggerJob.ScheduleID,
 			)
 		}
+
+		chain, _, _, _, err := getBackupChain(
+			ctx, execCfg, user, triggerJob.Destination, triggerJob.EncryptionOptions,
```
Comment (msbutler) [inline pkg/backup/compaction_job.go]: I don't think this is the right approach, as you're doing a bunch of IO to external storage within a transaction. In general when holding a transaction, we want to do as little work as possible, to prevent contention with other reader/writers.

I believe it would be better to _cancel_ compaction job C on resume with a verbose message. I think it is fine for jobs to cancel themselves, but let's check with @dt on this UX.

**Review by msbutler — CHANGES_REQUESTED** [review]

File: pkg/backup/compaction_job.go (hunk 1 above)
Comment (kev-cao) [reply pkg/backup/compaction_job.go]: Oh that's a good point. What do you think of perhaps opening two transactions instead?

1. Open transaction and inspect `schedule.CompactionJobID`. If it's not already set, set it to some sentinel value like `1`.
    a. `defer` a cleanup to reset back to 0 on any failures.
2. Close the transaction and inspect the backup chain.
3. Re-open transaction to write the job record and set `CompactionJobID`.

It does open up more transactions, but it also prevents us from cluttering the jobs table (although with sufficiently long RPOs, there probably won't be many scenarios with overlapping compaction jobs).

Comment (msbutler) [reply pkg/backup/compaction_job.go]: Your approach feels a bit complicated and could lead to deadlock if there's some failure between 1 and 3. But it does make me think of  a simpler idea: keep the current code, but also add another check of  `args.CompactionID  != 0 ` before `getBackupChain`. I think we should still check CompactionJobID in the second txn. 

i'm not sure it will catch all races, but i'm fine with an occasional failed compaction job.

Comment (kev-cao) [reply pkg/backup/compaction_job.go]: > could lead to deadlock

I believe `1a` would prevent that, unless the transaction to reset it fails. Although that could happen too at the end of a compaction job, so I think it's a type lock leak that is possible regardless.

That being said, yeah your approach is simpler and at least based on some quick whiteboarding, I think it actually does cover all the races here, barring one very specific situation. It fails if another compaction job were to start _and_ complete in-between the initial check before `getBackupChain` and the writing of the record. But realistically speaking, a compaction job would not be able to do so between these two steps.

File: pkg/backup/compaction_job.go [hunk 2]
```diff
@@ -99,6 +99,28 @@ func maybeStartCompactionJob(
 		user,
 	)
 
+	// A race condition can occur where a compaction job ends after we fetch the
+	// backup chain but before we open a transaction to write the record. As a
+	// result, the written record is based on a chain that did not include the
+	// newly completed compaction job. As a result, it is possible that the chosen
```
Comment (msbutler) [inline pkg/backup/compaction_job.go]: uber nit: you use the phrase "as a result" twice :D

File: pkg/backup/compaction_job.go [hunk 3]
```diff
@@ -119,20 +141,20 @@ func maybeStartCompactionJob(
...
-			)
+			return err
 		}
-		if args.CompactionJobID != 0 {
-			return errors.Newf(
-				"compaction job %d already running for schedule %d",
-				args.CompactionJobID, triggerJob.ScheduleID,
-			)
+
+		start, end, err := minSizeDeltaHeuristic(ctx, execCfg, chain)
```
Comment (msbutler) [inline pkg/backup/compaction_job.go]: we already have start/startTS and end/endTS above, right?

**Comment by msbutler** [comment]
also, we only need to backport this to 25.3 to fix the flakiness, right?

**Comment by kev-cao** [comment]
The check on `CompactionJobID` also exists in the 25.2 release branch: https://github.com/cockroachdb/cockroach/blob/4a1375126ca0295e1249680160c65751e178604e/pkg/backup/compaction_job.go#L130-L135

File: pkg/backup/compaction_job.go (hunk 3 above)
Comment (kev-cao) [reply pkg/backup/compaction_job.go]: Oh whoops didn't fully resolve the merge conflict

File: pkg/backup/compaction_job.go (hunk 2 above)
Comment (kev-cao) [reply pkg/backup/compaction_job.go]: Ugh I hate it when I do that, thanks for catching it

File: pkg/backup/compaction_job.go [hunk 4]
```diff
@@ -115,24 +137,17 @@ func maybeStartCompactionJob(
...
-		}
-		if args.CompactionJobID != 0 {
-			return errors.Newf(
-				"compaction job %d already running for schedule %d",
-				args.CompactionJobID, triggerJob.ScheduleID,
-			)
+			return err
 		}
+
+		log.Infof(ctx, "compacting backups from %s to %s", startTS, endTS)
```
Comment (msbutler) [inline pkg/backup/compaction_job.go]: nit: it is best practice to log stuff outside of a transaction (if the txn replays, you log twice!)

**Review by msbutler — APPROVED** [review]

**Comment by msbutler** [comment]
oh also, the commit message should be updated

**Comment by kev-cao** [comment]
TFTR!

bors r=msbutler
