### PR TITLE
changefeedccl: fix unwatched column families memory monitoring bug

### LINKED ISSUE #154776: changefeedccl: feed excluding column families leaks mem mon allocs for ignored events
Changefeeds watching a subset of a table's column families will leak the Alloc for events coming from unwatched families due to a missing Release() call in an early return [here](https://github.com/cockroachdb/cockroach/blob/c3e2217b963cc5db17053b11810a0a8893442f5d/pkg/ccl/changefeedccl/event_processing.go#L364) and [here](https://github.com/cockroachdb/cockroach/blob/c3e2217b963cc5db17053b11810a0a8893442f5d/pkg/ccl/changefeedccl/event_processing.go#L380). This has likely existed since column family support was introduced.

Found while investigating [this support issue](https://github.com/cockroachlabs/support/issues/3447).

Minimal repro:
```
create table cftest (
  id int primary key,
  pstr string,
  data string,
  FAMILY prim (id, pstr),
  FAMILY df (data)
);

insert into cftest (id, pstr, data)
select
  g,
  'hello-' || g::string,
  REPEAT('SQL', 5000)
from generate_series(1, 10000) as g;

set cluster setting changefeed.memory.per_changefeed_limit = '1MiB'; -- set this low to make it easier to hit the limit

CREATE CHANGEFEED FOR TABLE cftest family prim INTO 'null:' with initial_scan='no', diff; 
-- diff is not required to break it, but also makes it easier to hit the limt, as prev values' allocs are also leaked

update cftest set data = REPEAT('SQL2', 5000) where true;
```
-> observe sql.mem.bulk.current maxing at 1MiB (configured max), and changefeed.max_behind_nanos to start rising

Image

Jira issue: CRDB-55112

### PR DESCRIPTION
**Pull request by andyyang890**
This patch fixes a bug where the memory monitor wouldn't reclaim the
memory allocated to events corresponding to unwatched column families
for a changefeed that targets only a subset of a table's families.

Fixes #154776

Release note (bug fix): A bug where a changefeed targeting only a subset
of a table's column families could become stuck has been fixed.

### CODE REVIEW

File: pkg/ccl/changefeedccl/changefeed_memory_test.go [hunk 1]
```diff
@@ -0,0 +1,90 @@
...
+			// (~1 KiB for each of before/after).
+			data := make([]byte, 1<<10 /* 1 KiB */)
+			for i := range data {
+				data[i] = charset[rand.IntN(len(charset))]
+			}
+			sqlDB.Exec(t, `UPDATE foo SET b = $1 WHERE id = 1`, data)
+		}
+
+		// Update watched column again to verify the feed is still progressing.
+		// If the memory allocations leaked, this assertion would time out.
```
Comment (aerfrei) [inline pkg/ccl/changefeedccl/changefeed_memory_test.go]: Is there a way to get this to fail with a clearer symptom than a timeout (at least for enterprise feeds)? This is my first time looking at the memory monitor, but my sense was that since this would set a low PerChangefeedMemLimit, that the memory monitors should fail the feed once the limit is passed. But when I tried to check that on the status of the feed in this test, I saw that it was still running.

**Review by aerfrei — APPROVED** [review]

File: pkg/ccl/changefeedccl/changefeed_memory_test.go (hunk 1 above)
Comment (andyyang890) [reply pkg/ccl/changefeedccl/changefeed_memory_test.go]: If the allocations leaked, the memory monitor wouldn't fail; instead, the changefeed would get stuck, which is why the assertion would time out. I added some more explanatory comments to the test.

**Review by asg0451 — APPROVED** [review]

**Comment by andyyang890** [comment]
TFTRs!

bors r=aerfrei,asg0451
