### PR TITLE
roachtest: add RequiresDeprecatedWorkload testSpec

### LINKED ISSUE #127954: roachtest: tpchbench/sql20/nodes=3/cpu=4/sf=1 failed
roachtest.tpchbench/sql20/nodes=3/cpu=4/sf=1 [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/16270317?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/16270317?buildTab=artifacts#/tpchbench/sql20/nodes=3/cpu=4/sf=1) on master @ [c7d1ceed692d36e9d7c5a71e7122408e2e3e3b8b](https://github.com/cockroachdb/cockroach/commits/c7d1ceed692d36e9d7c5a71e7122408e2e3e3b8b):

```
(tpchbench.go:98).func1: full command output in run_083622.078447644_n4_cockroach-workload-r.log: COMMAND_PROBLEM: exit status 4
(monitor.go:154).Wait: monitor failure: monitor user task failed: t.Fatal() was called
test artifacts and logs in: /artifacts/tpchbench/sql20/nodes=3/cpu=4/sf=1/run_1
```

Parameters:
 - <code>ROACHTEST_arch=amd64</code>
 - <code>ROACHTEST_cloud=gce</code>
 - <code>ROACHTEST_coverageBuild=false</code>
 - <code>ROACHTEST_cpu=4</code>
 - <code>ROACHTEST_encrypted=false</code>
 - <code>ROACHTEST_metamorphicBuild=false</code>
 - <code>ROACHTEST_ssd=0</code>
<details><summary>Help</summary>
<p>

See: [roachtest README](https://github.com/cockroachdb/cockroach/blob/master/pkg/cmd/roachtest/README.md)

See: [How To Investigate \(internal\)](https://cockroachlabs.atlassian.net/l/c/SSSBr8c7)

See: [Grafana](https://go.crdb.dev/roachtest-grafana/teamcity-16270317/tpchbench-sql20-nodes-3-cpu-4-sf-1/1722414927425/1722415126565)

</p>
</details>
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*tpchbench/sql20/nodes=3/cpu=4/sf=1.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/bazci/githubpost/issues)
</sub>

Jira issue: CRDB-40695

### LINKED ISSUE #128172: roachtest: tpchbench/sql20/nodes=3/cpu=4/sf=1 failed
roachtest.tpchbench/sql20/nodes=3/cpu=4/sf=1 [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/16298889?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/16298889?buildTab=artifacts#/tpchbench/sql20/nodes=3/cpu=4/sf=1) on release-24.2.0-rc @ [46c11ab2cf6fa6f6adf7abb99ef72f68e4d538f8](https://github.com/cockroachdb/cockroach/commits/46c11ab2cf6fa6f6adf7abb99ef72f68e4d538f8):

```
(tpchbench.go:98).func1: full command output in run_102814.623449545_n4_cockroach-workload-r.log: COMMAND_PROBLEM: exit status 4
(monitor.go:154).Wait: monitor failure: monitor user task failed: t.Fatal() was called
test artifacts and logs in: /artifacts/tpchbench/sql20/nodes=3/cpu=4/sf=1/run_1
```

Parameters:
 - <code>ROACHTEST_arch=amd64</code>
 - <code>ROACHTEST_cloud=gce</code>
 - <code>ROACHTEST_coverageBuild=false</code>
 - <code>ROACHTEST_cpu=4</code>
 - <code>ROACHTEST_encrypted=false</code>
 - <code>ROACHTEST_fs=ext4</code>
 - <code>ROACHTEST_localSSD=true</code>
 - <code>ROACHTEST_metamorphicBuild=false</code>
 - <code>ROACHTEST_ssd=0</code>
<details><summary>Help</summary>
<p>

See: [roachtest README](https://github.com/cockroachdb/cockroach/blob/master/pkg/cmd/roachtest/README.md)

See: [How To Investigate \(internal\)](https://cockroachlabs.atlassian.net/l/c/SSSBr8c7)

See: [Grafana](https://go.crdb.dev/roachtest-grafana/teamcity-16298889/tpchbench-sql20-nodes-3-cpu-4-sf-1/1722594431874/1722594637100)

</p>
</details>
<details><summary>Same failure on other branches</summary>
<p>

- #128149 roachtest: tpchbench/sql20/nodes=3/cpu=4/sf=1 failed [C-test-failure O-roachtest O-robot T-sql-queries branch-release-24.1 release-blocker]
- #127954 roachtest: tpchbench/sql20/nodes=3/cpu=4/sf=1 failed [C-test-failure O-roachtest O-robot T-sql-queries branch-master release-blocker]
</p>
</details>
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*tpchbench/sql20/nodes=3/cpu=4/sf=1.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/bazci/githubpost/issues)
</sub>

Jira issue: CRDB-40844

### PR DESCRIPTION
**Pull request by DarrylWong**
Previously we required the workload binary to be present for all tests to run even if the test did not use it.

Now that we have removed all unnecessary usage of the deprecated workload, we can switch the validation of the workload binary to be opt in.

Fixes:  #128172, #127954
Epic: none
Release note: none

### CODE REVIEW

**Comment by DarrylWong** [comment]
Copied general approach from here: https://github.com/cockroachdb/cockroach/pull/119521/commits/b26c93bbc9db60bb7cd2e25fb8ab2e1fb497d745, but added in a hard fail to stop usage + updated the set of tests that need the testSpec.

File: pkg/cmd/roachtest/test_impl.go [hunk 1]
```diff
@@ -195,6 +195,11 @@ func (t *testImpl) StandardCockroach() string {
 }
 
 func (t *testImpl) DeprecatedWorkload() string {
+	// Fail and give a hint that the test should set `RequiresDeprecatedWorkload` so
+	// we can validate the binary exists.
+	if !t.spec.RequiresDeprecatedWorkload {
```
Comment (nameisbhaskar) [inline pkg/cmd/roachtest/test_impl.go:200]: Can we just fail here if `deprecatedWorkload` is "" instead of introducing "RequiresDeprecatedWorkload"?

File: pkg/cmd/roachtest/test_runner.go [hunk 2]
```diff
@@ -730,6 +730,11 @@ func (r *testRunner) runWorker(
 			return err
 		}
 
+		// Verify that the deprecated workload is available if needed.
+		if testToRun.spec.RequiresDeprecatedWorkload && workload[arch] == "" {
```
Comment (csgourav) [inline pkg/cmd/roachtest/test_runner.go:734]: Can we do this earlier? Maybe after test selection, if there is any test with RequiresDeprecatedWorkload, fail early or remove those from selected tests list with warning, as opposed to checking this for all the tests.

File: pkg/cmd/roachtest/test_impl.go (hunk 1 above)
Comment (DarrylWong) [reply pkg/cmd/roachtest/test_impl.go:200]: My comment is badly worded, I'll update it. I'm not guarding against the binary not existing, I'm guarding against people using the deprecated workload when not needed.

In a previous PR, I refactored almost all the `DeprecatedWorkload()` calls to just use `cockroach workload` instead. I want future tests to stop using `DeprecatedWorkload` if possible, so if a test does need it I want the test to explicitly set `RequiresDeprecatedWorkload`. 

If we just check that a `deprecatedWorkload` exists, it would be possible for a test writer to not set this spec and continue using the `deprecatedWorkload` without even knowing it's discouraged.

Let me know if that makes sense.

File: pkg/cmd/roachtest/test_runner.go (hunk 2 above)
Comment (DarrylWong) [reply pkg/cmd/roachtest/test_runner.go:734]: I just copied the approach of how we verify that other binaries, i.e. `libgeos`, exist when the test marks them as required.

I agree that it'd be nice if it could know earlier and skip/fail them right at the start though. Let me look into it! 😃

Comment (DarrylWong) [reply pkg/cmd/roachtest/test_runner.go:734]: Ah, the reason it can't be earlier is because we need to know the arch of the test, which isn't picked until right above here: 

https://github.com/cockroachdb/cockroach/blob/f91b32003f394af57d7acbda3a6f0776045c4c40/pkg/cmd/roachtest/test_runner.go#L704-L721

**Comment by renatolabs** [comment]
Would it make sense to auto-upload the `workload` binary to the workload node if the spec uses the new field?

**Comment by DarrylWong** [comment]
>Would it make sense to auto-upload the workload binary to the workload node if the spec uses the new field?

Good idea, I'll add it! It doesn't cover *all* cases unfortunately so we have to keep `DeprecatedWorkload` public.

**Review by renatolabs — APPROVED** [review]
Nice!

**Comment by DarrylWong** [comment]
[Passing run](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/16296274?buildTab=tests) of tests that use the deprecated binary

TFTR!

bors r+

**Comment by DarrylWong** [comment]
bors cancel

**Comment by DarrylWong** [comment]
Snuck in a quick fix for the tpchbench tests that use `querybench`, which need the deprecated binary.

**Comment by DarrylWong** [comment]
blathers backport 24.2.0-rc
