### PR TITLE
bench/rttanalysis: fix TestBenchmarkExpectation load and coverage

### LINKED ISSUE #167341: bench/rttanalysis: TestBenchmarkExpectationShard4 failed
bench/rttanalysis.TestBenchmarkExpectationShard4 [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Ci_TestsAwsLinuxArm64_UnitTests/21294485?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Ci_TestsAwsLinuxArm64_UnitTests/21294485?buildTab=artifacts#/) on master @ [34843985201272b0b435193796b171c5554f9108](https://github.com/cockroachdb/cockroach/commits/34843985201272b0b435193796b171c5554f9108):

```
=== RUN   TestBenchmarkExpectationShard4
    validate_benchmark_data.go:186: [/home/roach/.cache/bazel/_bazel_roach/c5a4e7d36696d9cd970af2045211a7df/sandbox/processwrapper-sandbox/20982/execroot/com_github_cockroachdb_cockroach/bazel-out/aarch64-fastbuild/bin/pkg/bench/rttanalysis/rttanalysis_test_/rttanalysis_test.runfiles/com_github_cockroachdb_cockroach/pkg/bench/rttanalysis/rttanalysis_test_/rttanalysis_test --test.v=test2json --test.bench=^$]
I260401 21:51:12.504059 1 (gostd) rand.go:288  [-] 1  random seed: 6139651169431662301
=== RUN   TestBenchmarkExpectationShard4
    test_log_scope.go:172: test logs captured to: /artifacts/tmp/_tmp/0b36cec45b89b87e5c3c5ffec983f098/logTestBenchmarkExpectationShard42141509462
    test_log_scope.go:82: use -show-logs to present logs inline
--- FAIL: TestBenchmarkExpectationShard4 (147.63s)
=== RUN   TestBenchmarkExpectationShard4/AlterTableAddForeignKey/alter_table_add_2_foreign_keys
=== RUN   TestBenchmarkExpectationShard4/AlterTableUnsplit/alter_table_unsplit_at_1_value
=== RUN   TestBenchmarkExpectationShard4/AlterTableUnsplit/alter_table_unsplit_at_2_values
=== RUN   TestBenchmarkExpectationShard4/DropRole/drop_1_role
=== RUN   TestBenchmarkExpectationShard4/Grant
=== RUN   TestBenchmarkExpectationShard4/AlterTableAddForeignKey/alter_table_add_foreign_key_with_3_columns
=== RUN   TestBenchmarkExpectationShard4/AlterTableUnsplit/alter_table_unsplit_at_3_values
=== RUN   TestBenchmarkExpectationShard4/Grant/grant_all_on_2_tables
=== RUN   TestBenchmarkExpectationShard4/RevokeRole/revoke_2_roles
=== RUN   TestBenchmarkExpectationShard4/UDFResolution/select_from_udf
=== RUN   TestBenchmarkExpectationShard4/AlterTableAddForeignKey
=== RUN   TestBenchmarkExpectationShard4/AlterTableAddForeignKey/alter_table_add_3_foreign_keys
=== RUN   TestBenchmarkExpectationShard4/AlterTableUnsplit
=== RUN   TestBenchmarkExpectationShard4/DropRole/drop_2_roles
=== RUN   TestBenchmarkExpectationShard4/RevokeRole
=== RUN   TestBenchmarkExpectationShard4/RevokeRole/revoke_1_role
=== RUN   TestBenchmarkExpectationShard4/UDFResolution
=== RUN   TestBenchmarkExpectationShard4/AlterTableAddForeignKey/alter_table_add_1_foreign_key
=== RUN   TestBenchmarkExpectationShard4/DropRole
=== RUN   TestBenchmarkExpectationShard4/DropRole/drop_3_roles
=== RUN   TestBenchmarkExpectationShard4/Grant/grant_all_on_1_table
=== RUN   TestBenchmarkExpectationShard4/Grant/grant_all_on_3_tables
```
<details><summary>Help</summary>
<p>

See also: [How To Investigate a Go Test Failure \(internal\)](https://cockroachlabs.atlassian.net/l/c/HgfXfJgM)
</p>
</details>
/cc @cockroachdb/sql-foundations
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*TestBenchmarkExpectationShard4.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/bazci/githubpost/issues)

</sub>

Jira issue: CRDB-62393

### PR DESCRIPTION
**Pull request by fqazi**
Previously, TestBenchmarkExpectation sharded tests could fail in CI due to resource exhaustion and timeouts. This was caused by two main issues:
1. execTestSubprocess did not pass the -test.run flag to the subprocess, causing each shard's subprocess to attempt to run the entire package.
2. Benchmark concurrency was tied to system.NumCPU(), which resulted in too many concurrent CockroachDB servers on high-core machines.

Additionally, TestBenchmarkExpectationShard5 was missing from the test file, meaning a portion of the benchmarks were never being validated.

This commit fixes these issues by:
- Explicitly passing the current test filter to the subprocess in execTestSubprocess.
- Capping the benchmark concurrency to 4.
- Adding the missing TestBenchmarkExpectationShard5.

Fixes: #167341

Release note: None

### CODE REVIEW

File: pkg/bench/rttanalysis/validate_benchmark_data_test.go [hunk 1]
```diff
@@ -47,3 +47,7 @@ func TestBenchmarkExpectationShard3(t *testing.T) {
 func TestBenchmarkExpectationShard4(t *testing.T) {
 	reg.RunExpectationsSharded(t, 4, shardCount)
 }
+
+func TestBenchmarkExpectationShard5(t *testing.T) {
```
Comment (rafiss) [inline pkg/bench/rttanalysis/validate_benchmark_data_test.go:95]: i wonder if there's a way we could ensure we don't miss another one if more shards are added. could there be some sort of init time check?

**Review by rafiss — COMMENTED** [review]
nice fixes!

File: pkg/bench/rttanalysis/validate_benchmark_data_test.go (hunk 1 above)
Comment (rafiss) [reply pkg/bench/rttanalysis/validate_benchmark_data_test.go:95]: I asked Claude for a suggestion:
```
  The most robust approach would be to add a test that parses the source file and verifies the count:

  func TestShardCountMatchesFunctions(t *testing.T) {
        fset := token.NewFileSet()
        f, err := parser.ParseFile(fset, "validate_benchmark_data_test.go", nil, 0)
        require.NoError(t, err)

        var count int
        for _, decl := range f.Decls {
                fn, ok := decl.(*ast.FuncDecl)
                if !ok {
                        continue
                }
                if strings.HasPrefix(fn.Name.Name, "TestBenchmarkExpectationShard") {
                        count++
                }
        }
        require.Equal(t, shardCount, count,
                "number of TestBenchmarkExpectationShard* functions must match shardCount; "+
                        "add or remove test functions to match")
  }
```

Comment (fqazi) [reply pkg/bench/rttanalysis/validate_benchmark_data_test.go:95]: I used reflection with an array to enforce this. I also added logic to ensure the shard count is from the function name. How do you feel about this init time approach?

**Review by fqazi — COMMENTED** [review]
> @fqazi made 1 comment.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/167921)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on rafiss).

File: pkg/bench/rttanalysis/validate_benchmark_data.go [hunk 2]
```diff
@@ -78,6 +78,9 @@ func runBenchmarkExpectationTests(t *testing.T, r *Registry) {
 	var results resultSet
 	var wg sync.WaitGroup
 	concurrency := ((system.NumCPU() - 1) / r.numNodes) + 1 // arbitrary
```
Comment (rafiss) [inline pkg/bench/rttanalysis/validate_benchmark_data.go]: super nit: `concurrency := min(4, ((system.NumCPU() - 1) / r.numNodes) + 1)`

File: pkg/bench/rttanalysis/validate_benchmark_data_test.go (hunk 1 above)
Comment (rafiss) [reply pkg/bench/rttanalysis/validate_benchmark_data_test.go:95]: nice!

**Review by rafiss — APPROVED** [review]
