### PR TITLE
kvclient: continue the processing loop after check failure

### LINKED ISSUE #116834: roachtest: clearrange/checks=false failed
roachtest.clearrange/checks=false [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/13213573?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/13213573?buildTab=artifacts#/clearrange/checks=false) on master @ [5f76d93b2ad8d29c14c9b176753ec33cbf81e3fe](https://github.com/cockroachdb/cockroach/commits/5f76d93b2ad8d29c14c9b176753ec33cbf81e3fe):

```
(test_runner.go:1124).runTest: test timed out (6h30m0s)
test artifacts and logs in: /artifacts/clearrange/checks=false/run_1
```

Parameters:
 - <code>ROACHTEST_arch=amd64</code>
 - <code>ROACHTEST_cloud=gce</code>
 - <code>ROACHTEST_coverageBuild=false</code>
 - <code>ROACHTEST_cpu=16</code>
 - <code>ROACHTEST_encrypted=false</code>
 - <code>ROACHTEST_fs=ext4</code>
 - <code>ROACHTEST_localSSD=true</code>
 - <code>ROACHTEST_metamorphicBuild=false</code>
 - <code>ROACHTEST_ssd=0</code>
<details><summary>Help</summary>
<p>

See: [roachtest README](https://github.com/cockroachdb/cockroach/blob/master/pkg/cmd/roachtest/README.md)

See: [How To Investigate \(internal\)](https://cockroachlabs.atlassian.net/l/c/SSSBr8c7)

See: [Grafana](https://go.crdb.dev/roachtest-grafana/teamcity-13213573/clearrange-checks-false/1703006492218/1703030055332)

</p>
</details>
/cc @cockroachdb/storage
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*clearrange/checks=false.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)
</sub>

Jira issue: CRDB-34801

### LINKED ISSUE #116839: roachtest: clearrange/zfs/checks=true failed
roachtest.clearrange/zfs/checks=true [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/13213573?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/13213573?buildTab=artifacts#/clearrange/zfs/checks=true) on master @ [5f76d93b2ad8d29c14c9b176753ec33cbf81e3fe](https://github.com/cockroachdb/cockroach/commits/5f76d93b2ad8d29c14c9b176753ec33cbf81e3fe):

```
(test_runner.go:1124).runTest: test timed out (7h0m0s)
test artifacts and logs in: /artifacts/clearrange/zfs/checks=true/run_1
```

Parameters:
 - <code>ROACHTEST_arch=amd64</code>
 - <code>ROACHTEST_cloud=gce</code>
 - <code>ROACHTEST_coverageBuild=false</code>
 - <code>ROACHTEST_cpu=16</code>
 - <code>ROACHTEST_encrypted=false</code>
 - <code>ROACHTEST_fs=zfs</code>
 - <code>ROACHTEST_localSSD=true</code>
 - <code>ROACHTEST_metamorphicBuild=false</code>
 - <code>ROACHTEST_ssd=0</code>
<details><summary>Help</summary>
<p>

See: [roachtest README](https://github.com/cockroachdb/cockroach/blob/master/pkg/cmd/roachtest/README.md)

See: [How To Investigate \(internal\)](https://cockroachlabs.atlassian.net/l/c/SSSBr8c7)

See: [Grafana](https://go.crdb.dev/roachtest-grafana/teamcity-13213573/clearrange-zfs-checks-true/1703011536811/1703036903344)

</p>
</details>
/cc @cockroachdb/storage
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*clearrange/zfs/checks=true.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)
</sub>

Jira issue: CRDB-34805

### LINKED ISSUE #117260: roachtest: clearrange/checks=true failed
roachtest.clearrange/checks=true [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/13359383?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/13359383?buildTab=artifacts#/clearrange/checks=true) on master @ [c316d6a615fa02a05357a20bf03b8a197ab27810](https://github.com/cockroachdb/cockroach/commits/c316d6a615fa02a05357a20bf03b8a197ab27810):

```
(test_runner.go:1124).runTest: test timed out (6h30m0s)
test artifacts and logs in: /artifacts/clearrange/checks=true/run_1
```

Parameters:
 - <code>ROACHTEST_arch=amd64</code>
 - <code>ROACHTEST_cloud=gce</code>
 - <code>ROACHTEST_coverageBuild=false</code>
 - <code>ROACHTEST_cpu=16</code>
 - <code>ROACHTEST_encrypted=false</code>
 - <code>ROACHTEST_fs=ext4</code>
 - <code>ROACHTEST_localSSD=true</code>
 - <code>ROACHTEST_metamorphicBuild=false</code>
 - <code>ROACHTEST_ssd=0</code>
<details><summary>Help</summary>
<p>

See: [roachtest README](https://github.com/cockroachdb/cockroach/blob/master/pkg/cmd/roachtest/README.md)

See: [How To Investigate \(internal\)](https://cockroachlabs.atlassian.net/l/c/SSSBr8c7)

See: [Grafana](https://go.crdb.dev/roachtest-grafana/teamcity-13359383/clearrange-checks-true/1704215877152/1704239442804)

</p>
</details>
/cc @cockroachdb/storage
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*clearrange/checks=true.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)
</sub>

Jira issue: CRDB-35089

### LINKED ISSUE #118134: kv: number of ranges grows linearly after upgrade to 24.1
We recently upgraded the DRT cluster from 23.2 to master (24.1) and when the upgrade was finalized, we observed that the number of ranges on the cluster started growing linearly.

image

The DRT cluster runs a workload where a new tpcc database is created and populated, then the workload is run for an hour, and finally the database is dropped before the cycle repeats.  This is expected to create MVCC garbage but that garbage is also expected to be cleaned up.  

Something seems to have broken in master where now that cleanup is no longer happening (or not happening completely).

This is being discussed in greater detail [here](https://cockroachlabs.slack.com/archives/C05FHJJ0MD0/p1705671015242739).

Jira issue: CRDB-35565

### PR DESCRIPTION
**Pull request by andrewbaptist**
Previously as part of #111953 we added a check to not process an unprocessable replica that had been added to the queue. As part of short-circuiting the replica processing, it did not correctly set the `nextTime` which resulted in it blocking the queue forever when this happened.

Fixes: #118134
Fixes: #117260
Fixes: #116839
Fixes: #116834

Epic: none

Release note: None

### CODE REVIEW

**Comment by andrewbaptist** [comment]
I'm going to validate that this fixes the clearrange issue. Specifically the bug happens if the replica becomes "unprocessable" between the "queueing" and the "processing" for example due to a lease transfer or a range merge.

**Comment by andrewbaptist** [comment]
I ran the `clearrange` test after this change and it passed 5/5 times. This isn't completely conclusive since it passed about 1/3 of the time before, but is strong evidence that this fixes it. The test takes ~2 hours to run each time so its hard to run it more than this. The code before definitely had a bug, and the refactor of this method makes it cleaner.

Let me know if you have any questions.

File: pkg/kv/kvserver/queue.go [hunk 1]
```diff
@@ -910,6 +883,38 @@ func (bq *baseQueue) processLoop(stopper *stop.Stopper) {
 	}
 }
 
+// processOne processes a replica if possible and releases the processSem when
+// the processing is complete.
+func (bq *baseQueue) processOneAsync(
+	ctx context.Context, repl replicaInQueue, stopper *stop.Stopper,
+) {
```
Comment (stevendanna) [inline pkg/kv/kvserver/queue.go:890]: I wonder if we want something in the function name that indicates we assume the semaphore is held so we can see that clearly at the call site.

**Review by stevendanna — APPROVED** [review]
Looks reasonable to me.

**Review by kvoli — APPROVED** [review]
:lgtm:

Nice find!

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/118217#-:-Novtb8Y0NNvGWzT-FZX:b-8mas0a)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @andrewbaptist)

___
*[`pkg/kv/kvserver/queue.go` line 911 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/118217#-NovtGDK9IB3lLIbtIhd:-NovtGDK9IB3lLIbtIhe:b9homj6) ([raw file](https://github.com/cockroachdb/cockroach/blob/7f79481c6508c89b0f23f8c191df695252d566f4/pkg/kv/kvserver/queue.go#L911)):*
> ```Go
> 		}); err != nil {
> 		// Release semaphore if we can't start the task, normally this only
> 		// happens during a system shutdown.
> ```

nit: it may be helpful to also note that an error won't be returned if the closure above has been called -- this removes any concern about double sem releases or `finishProcessingReplica(..)` calls.

**Comment by andrewbaptist** [comment]
bors r=kvoli, stevendanna

TFTR! I updated with your suggestions.
