### PR TITLE
roachtest: relax max range lookups for kv50/rangelookups/split

### LINKED ISSUE #39174: roachtest: kv50/rangelookups/split/nodes=8 failed
SHA: https://github.com/cockroachdb/cockroach/commits/65055d6c16bf9386d8c4f4f9cd23e0a848814dc9

Parameters:

To repro, try:

```
# Don't forget to check out a clean suitable branch and experiment with the
# stress invocation until the desired results present themselves. For example,
# using stress instead of stressrace and passing the '-p' stressflag which
# controls concurrency.
./scripts/gceworker.sh start && ./scripts/gceworker.sh mosh
cd ~/go/src/github.com/cockroachdb/cockroach && \
stdbuf -oL -eL \
make stressrace TESTS=kv50/rangelookups/split/nodes=8 PKG=roachtest TESTTIMEOUT=5m STRESSFLAGS='-maxtime 20m -timeout 10m' 2>&1 | tee /tmp/stress.log
```

Failed test: https://teamcity.cockroachdb.com/viewLog.html?buildId=1411157&tab=buildLog

```
The test failed on branch=master, cloud=gce:
test artifacts and logs in: /home/agent/work/.go/src/github.com/cockroachdb/cockroach/artifacts/20190730-1411157/kv50/rangelookups/split/nodes=8/run_1
	ts_util.go:150,kv.go:554,cluster.go:2069,errgroup.go:57: Found minute interval with 11.141667 lookup/sec above target of 10.000000 lookup/sec
	cluster.go:2090,kv.go:600,kv.go:627,test_runner.go:691: Goexit() was called

```

### PR DESCRIPTION
**Pull request by jeffrey-xiao**
This roachtest was occasionally failing because it was exceeding the maximum of 10 lookup/sec. This commit relaxes it to 15 lookup/sec. This roachtest will still detect regressions in range descriptor cache performance since the old rate was approximately 30 lookup/sec.

Also, set a minimum version on the test since they are expected to fail on 19.1 and "distsender.rangelookups" isn't available on 19.1.

Finally, remove WITH EXPIRATION with performing splits as temporary splits aren't necessary for the test.

Fixes #39174.

Release note: None

### CODE REVIEW

**Review by ajwerner — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/39402#-:-LlhGQSJ9WSSULxC4LQ1:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @nvanbenschoten)

**Review by nvb — APPROVED** [review]

File: pkg/cmd/roachtest/kv.go [hunk 1]
```diff
@@ -576,7 +576,6 @@ func registerKVRangeLookups(r *testRegistry) {
 								kv.kv
 							SPLIT AT
 								VALUES (CAST(floor(random() * 9223372036854775808) AS INT))
-							WITH EXPIRATION '1s'
```
Comment (nvanbenschoten) [inline pkg/cmd/roachtest/kv.go]: Why did we remove this?

Comment (jeffrey-xiao) [reply pkg/cmd/roachtest/kv.go]: Temporary splits weren't needed for the test and I feel like preventing automatic merges from taking place would probably be a good thing.

**Comment by jeffrey-xiao** [comment]
TFTRs!

bors r+
