### PR TITLE
sql/schemachanger: fix index creation failures after pause/resume

### LINKED ISSUE #153522: sql/schemachanger: spans are incorrectly marked as completed during backfill leading to index validation errors
The existing logic for computed completed spans in the index backfiller is correct for partial spans, but incorrect for when the last chunk of a span is completed:
https://github.com/cockroachdb/cockroach/blob/90db6eab29659bc86e8ce6d6314f559e99f1068d/pkg/sql/rowexec/indexbackfiller.go#L165

When working on the last chunk we mark the entire span as completed, which would work fine before we added concurrent ingestion support via:  https://github.com/cockroachdb/cockroach/pull/138781. This can lead to the span being marked completed as too early.

If the job is retried or paused after this is done, it will never resume properly and treat the entire span as completed. As a workaround users can currently disable index ingestion concurrency with: `SET CLUSTER SETTING bulkio.index_backfill.ingest_concurrency=1 `

The appropriate fix is to compute the completed spans as:

```
// Identify the Span for which we have constructed index entries. This is
// used for reporting progress and updating the job details.
completedSpan := roachpb.Span{Key: startKey, EndKey: ib.spec.Spans[i].EndKey}
if todo.Key != nil {
	completedSpan.EndKey = todo.Key
}
```

Jira issue: CRDB-54473

### PR DESCRIPTION
**Pull request by fqazi**
Previously, when the index backfiller was tracking completed spans, the final chunk of a span would cause an update to be emitted that incorrectly indicated the entire span was complete.  While this was not an issue with a single ingest goroutine, it caused problems with the introduction of multiple ingest goroutines. As a result, if the job was paused and resumed after this incorrect progress update, the backfiller could skip rows, leading to validation errors.  To address this, this patch ensures that progress updates for the final chunk of a span correctly report only the work completed in that chunk.

Fixes: #153522

Release note (bug fix): Addressed a bug where index creation could fail due to validation errors if the schema change was retried or paused/resumed during the backfill.

### CODE REVIEW

**Review by mgartner — APPROVED** [review]
:lgtm: I left some suggestions for improving this code too.

> @mgartner reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/153583#-:-O_Htyk46EGfSQDCuhw9:b-8yx18p)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @rytaft)

___
*[`pkg/sql/rowexec/indexbackfiller.go` line 158 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/153583#-O_HsRpj1TA2veNn2r_A:-O_HsRpj1TA2veNn2r_B:b-1qxvad) ([raw file](https://github.com/cockroachdb/cockroach/blob/ad953b7f9cbdaa48ad8ae4939f1bbde0f7afd60a/pkg/sql/rowexec/indexbackfiller.go#L158)):*
> ```Go
> 				readAsOf = ib.spec.WriteAsOf
> 			}
> 			todo.Key, entries, memUsedBuildingBatch, err = ib.buildIndexEntryBatch(ctx, todo, readAsOf)
> ```

nit: This is a good opportunity to document `(*indexBackfiller).buildIndexEntryBatch` and `(*IndexBackfiller).BuildIndexEntriesChunk`. They both return a key to resume for the next batch, but they aren't documented and the return values are unnamed so you have to read through the code to know this.

The resume key is always >todo.Key and <=todo.EndKey, is that correct? It would be good to document this as well.

I'm also questioning whether these functions should return the remaining span instead of just the resume key. That might make them easier to use and less bug prone.

File: pkg/sql/indexbackfiller_test.go [hunk 1]
```diff
@@ -670,21 +686,28 @@ func TestIndexBackfillerResumePreservesProgress(t *testing.T) {
...
-
-		// Make sure the progress update does not contain overlapping spans.
-		for i, span1 := range progressUpdate {
-			for j, span2 := range progressUpdate {
-				if i <= j {
-					continue
-				}
-				if span1.Overlaps(span2) {
-					t.Fatalf("progress update contains overlapping spans: %s and %s", span1, span2)
+		updateCount := 2
```
Comment (rafiss) [inline pkg/sql/indexbackfiller_test.go:691]: nice work improving this test!

**Review by rafiss — APPROVED** [review]

**Comment by fqazi** [comment]
@rafiss @mgartner TFTR!

bors r+
