### PR TITLE
sql: release orphaned table leases at server startup

### LINKED ISSUE #20485: sql: old table leases never deleted
If a node dies (ungracefully), the table leases it was holding at the time of its death "leak" and are never deleted from the `system.lease` table. These leaked leases will prevent a schema change on the table. This is very easy to reproduce.

When a node restarts, it should look for any leases in the `system.lease` table and delete any that are expired.

### LINKED ISSUE #23244: sql: drop table taking more than 5 minutes to drop a table with 2 rows
I've been trying to reproduce an unrelated panic by repeatedly creating and dropping the same table. Steps to reproduce the slowness are:

1. Start a local insecure cluster with 3 nodes.
2. Create a table with multiple columns.
3. Add 2 rows to the table.
4. Add an index for a column.
5. Restart every node in the cluster.
6. Drop the table.
7. Wait 1-6 minutes.

### LINKED ISSUE #32254: sql: GRANT admin TO user command hung SQL shell
**Describe the problem**

On a one-node cluster running on master (a05f15b7223642484ef0364d81ddc462c306e954), I added an enterprise license and tried adding my user to the `admin` role. However, when I did so, the command never completed in my SQL shell, it just hung there for minutes on end:

```sql
root@:26257/defaultdb> grant admin to alex;
```

The node's logs were full of the following log spam, where it just kept repeating the same message every couple hundred milliseconds ad infinitum:

```
I181113 09:24:40.895659 483 sql/lease.go:345  [n1,client=[::1]:62257,user=root] publish: descID=23 (role_members) version=2 mtime=2018-11-13 09:24:40.89189 +0000 UTC
I181113 09:24:40.901066 483 sql/lease.go:315  publish (1 leases): desc=[{role_members 23 1}]
I181113 09:24:40.901484 1659 sql/lease.go:876  new lease: 23("role_members") ver=2:1542101372.003237783,0, refcount=0
I181113 09:24:40.927960 483 sql/lease.go:315  publish (1 leases): desc=[{role_members 23 1}]
I181113 09:24:40.976218 483 sql/lease.go:315  publish (1 leases): desc=[{role_members 23 1}]
I181113 09:24:41.062664 483 sql/lease.go:315  publish (1 leases): desc=[{role_members 23 1}]
I181113 09:24:41.254359 483 sql/lease.go:315  publish (1 leases): desc=[{role_members 23 1}]
I181113 09:24:41.472894 483 sql/lease.go:315  publish (1 leases): desc=[{role_members 23 1}]
I181113 09:24:41.696796 483 sql/lease.go:315  publish (1 leases): desc=[{role_members 23 1}]
...
```

The command had successfully taken effect -- the user `alex` was able to do things that required the admin role, but the statement never finished. When I ctrl+C'ed the shell, the log spam stopped with this final message:

```
W181113 09:26:36.644777 483 sql/schema_changer.go:796  [n1,client=[::1]:62257,user=root,scExec] aborted in distSender: context canceled
```

**To Reproduce**

Start a one node cluster at the SHA above. Create a user. Set up an enterprise license. Try to grant the `admin` role to that user.

**Expected behavior**

The command to return.

@mberhault @vivekmenezes

### PR DESCRIPTION
**Pull request by vivekmenezes**
table leases created and not released when a node shuts down
ungracefully are orphaned leases. These orphaned leases can
block new schema changes run before the expiration time of
the lease. This change deletes such orphaned leases at
server startup.

This implementation is limited in that the orphaned leases are
deleted by the node when it restarts. In the future this
implementation can benefit from the leases holding
node liveness epoch in them, but that is part of a larger
future design to introduce node liveness epoch in leases.
For now, this is sufficient to maintain the current
implementation while providing for user impact in the most
common case of node restarts.

fixes #20485
fixes #32254
fixes #23244

Release note (sql change): Fix problem with schema change
getting stuck for 5 minutes when executed immediately after
a server restart.

### CODE REVIEW

**Comment by vivekmenezes** [comment]
I privately tested that this indeed solves the listed issues.

File: pkg/sql/lease.go [hunk 1]
```diff
@@ -1760,3 +1761,62 @@ func (m *LeaseManager) refreshSomeLeases(ctx context.Context) {
...
+		// doesn't implement AS OF SYSTEM TIME.
+
+		// Read orphaned leases.
+		sqlQuery := fmt.Sprintf(`
+SELECT "descID", version, expiration FROM system.lease AS OF SYSTEM TIME %d WHERE "nodeID" = %d
+`, startTime.UnixNano(), nodeID)
+		rows, _, err := m.LeaseStore.execCfg.InternalExecutor.Query(
+			ctx, "read orphaned table leases", nil /*txn*/, sqlQuery)
+		if err != nil {
+			log.Infof(ctx, "unable to read orphaned leases: %+v", err)
```
Comment (dt) [inline pkg/sql/lease.go]: Warningf?

File: pkg/sql/lease.go [hunk 2]
```diff
@@ -1760,3 +1761,62 @@ func (m *LeaseManager) refreshSomeLeases(ctx context.Context) {
...
+				version:    int(tree.MustBeDInt(row[1])),
+				expiration: tree.MustBeDTimestamp(row[2]),
+			}
+			if err := m.stopper.RunLimitedAsyncTask(
+				ctx, fmt.Sprintf("release table lease %+v", lease), sem, true /*wait*/, func(ctx context.Context) {
+					m.LeaseStore.release(ctx, m.stopper, &lease)
+					log.Infof(ctx, "released orphaned table lease: %+v", lease)
+					wg.Done()
+				}); err != nil {
+				log.Infof(ctx, "did not release orphaned table lease: %+v, err = %s", lease, err)
```
Comment (dt) [inline pkg/sql/lease.go]: ditto

File: pkg/sql/lease.go [hunk 3]
```diff
@@ -1760,3 +1761,62 @@ func (m *LeaseManager) refreshSomeLeases(ctx context.Context) {
...
+				wg.Done()
```
Comment (dt) [inline pkg/sql/lease.go]: nit: I don't think it is currently wrong but it might be simpler / less likely to be messed up in any future edits if we moved to a single `Done()`  call outside the `err != nil` check (and maybe a single `Add(len(rows))` above the loop?

**Review by dt — APPROVED** [review]

**Review by vivekmenezes — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/32988)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/lease.go, line 1789 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/32988#-LTOhDwoL4FLKM2k6d58-r1-1789:-LTVQbJR1XU-4A7xlEjI:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/5c50a0e490c823bd06e5c9c30bebd00e38ed0cdd/pkg/sql/lease.go#L1789)):*
<details><summary><i>Previously, dt (David Taylor) wrote…</i></summary><blockquote>

Warningf?
</blockquote></details>

Done.
___
*[pkg/sql/lease.go, line 1816 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/32988#-LTOhDwoL4FLKM2k6d58-r1-1816:-LTVQd-59EZkqbaY-5UK:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/5c50a0e490c823bd06e5c9c30bebd00e38ed0cdd/pkg/sql/lease.go#L1816)):*
<details><summary><i>Previously, dt (David Taylor) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.
___
*[pkg/sql/lease.go, line 1817 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/32988#-LTOhDwoL4FLKM2k6d58-r1-1817:-LTVSezTE_Zb3uz6egip:b-d8rhfm) ([raw file](https://github.com/cockroachdb/cockroach/blob/5c50a0e490c823bd06e5c9c30bebd00e38ed0cdd/pkg/sql/lease.go#L1817)):*
<details><summary><i>Previously, dt (David Taylor) wrote…</i></summary><blockquote>

nit: I don't think it is currently wrong but it might be simpler / less likely to be messed up in any future edits if we moved to a single `Done()`  call outside the `err != nil` check (and maybe a single `Add(len(rows))` above the loop?
</blockquote></details>

Good point. The original code actually had a subtle bug where if it ran through the early exit section it would return while allowing tasks to continue referencing `wg` which is on the stack.

I have to call Done() in both sections because I use RunAsyncTask.  Add(len(rows)) doesn't work because of the early exit (unless I use continue there, but that feels wrong).

**Comment by vivekmenezes** [comment]
TFTR!

**Comment by vivekmenezes** [comment]
bor r+
