### PR TITLE
geos: when loading geos, consult bazel runfiles path first before others

### LINKED ISSUE #74889: bazel: incorrect geospatial results in logictest
I hit this failure when using bazel. This is with no local changes (5ad21e3896).
```
        --- FAIL: TestLogic/local/geospatial_zm (0.23s)
            logic.go:2438: 
                 
                testdata/logic_test/geospatial_zm:381: SELECT st_length('LINESTRING M(0 0 -25, 1 1 -50, 2 2 0)')
                expected:
                    2.82842712474619
                    
                but found (query options: "") :
                    82.2650791318405
```
Test passes with make.

### PR DESCRIPTION
**Pull request by rickystewart**
Without this change, tests can find stale `libgeos` outside of the
sandbox. If the Bazel runfiles directory is available, we always want to
use if first (other than `flagLibraryDirectoryValue`, which is an
explicit flag).

Closes #74889.

Release note: None

### CODE REVIEW

**Review by otan — APPROVED** [review]
ah!

File: pkg/geo/geos/geos.go [hunk 1]
```diff
@@ -127,6 +127,12 @@ func findLibraryDirectories(flagLibraryDirectoryValue string, crdbBinaryLoc stri
 		panic(err)
 	}
 	locs := []string{}
+	// Account for the libraries to be in a bazel runfile path.
+	if bazel.BuiltWithBazel() {
```
Comment (otan) [inline pkg/geo/geos/geos.go:131]: actually, arguably after

```
if flagLibraryDirectoryValue != "" {
		locs = append(locs, flagLibraryDirectoryValue)
	}
```

is better since there's an explicit flag?

**Review by otan — CHANGES_REQUESTED** [review]

**Review by otan — APPROVED** [review]

**Comment by rickystewart** [comment]
bors r=otan
