### PR TITLE
roachtest: update cdc/initial-scan-rolling-restart

### LINKED ISSUE #166395: roachtest: cdc/initial-scan-rolling-restart/normal-checkpoint failed
roachtest.cdc/initial-scan-rolling-restart/normal-checkpoint [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/21277252?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/21277252?buildTab=artifacts#/cdc/initial-scan-rolling-restart/normal-checkpoint) on master @ [9fc2f395971bd0b3a3336570639d3547b7ac479e](https://github.com/cockroachdb/cockroach/commits/9fc2f395971bd0b3a3336570639d3547b7ac479e):

Failed with:

```
(test_runner.go:1590).runTest: test timed out (30m0s)
test artifacts and logs in: /artifacts/cdc/initial-scan-rolling-restart/normal-checkpoint/run_1
```
Cluster Node to Ip Mapping:
| Node | Public IP | Private IP |
| --- | --- | --- |
| teamcity-21277252-1774246877-07-n4cpu4-0001 | 35.231.224.65 | 10.142.15.246 |
| teamcity-21277252-1774246877-07-n4cpu4-0002 | 104.196.22.213 | 10.142.15.243 |
| teamcity-21277252-1774246877-07-n4cpu4-0003 | 34.24.31.191 | 10.142.15.242 |
| teamcity-21277252-1774246877-07-n4cpu4-0004 | 34.23.232.224 | 10.142.3.193 |

Parameters:
 - <code>arch=amd64</code>
 - <code>cloud=gce</code>
 - <code>coverageBuild=false</code>
 - <code>cpu=4</code>
 - <code>diskCount=0</code>
 - <code>encrypted=false</code>
 - <code>runtimeAssertionsBuild=false</code>
<details><summary>Help</summary>
<p>

See: [roachtest README](https://github.com/cockroachdb/cockroach/blob/master/pkg/cmd/roachtest/README.md)

See: [How To Investigate \(internal\)](https://cockroachlabs.atlassian.net/l/c/SSSBr8c7)

See: [Grafana](https://go.crdb.dev/roachtest-grafana/teamcity-21277252/cdc-initial-scan-rolling-restart-normal-checkpoint/1774247210351/1774249228785)

</p>
</details>
/cc @cockroachdb/cdc
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*cdc/initial-scan-rolling-restart/normal-checkpoint.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/bazci/githubpost/issues)

</sub>

Jira issue: CRDB-61899

### PR DESCRIPTION
**Pull request by andyyang890**
This patch updates the `cdc/initial-scan-rolling-restart` roachtest
to do frequent frontier persistence now that the legacy span-level
checkpoint is no longer written.

Fixes #166395

Release note: None

### CODE REVIEW

File: pkg/cmd/roachtest/tests/cdc.go [hunk 1]
```diff
@@ -1163,18 +1154,9 @@ func runCDCInitialScanRollingRestart(
...
-			`SET CLUSTER SETTING changefeed.span_checkpoint.interval = '5s'`,
-			`SET CLUSTER SETTING changefeed.progress.frontier_persistence.interval = '10m'`,
-		)
-	case cdcFrontierPersistence:
-		setupStmts = append(setupStmts,
-			`SET CLUSTER SETTING changefeed.span_checkpoint.interval = '0'`,
-			`SET CLUSTER SETTING changefeed.progress.frontier_persistence.interval = '5s'`,
-		)
+		// Configure frequent checkpointing.
+		`SET CLUSTER SETTING changefeed.span_checkpoint.interval = '1s'`,
```
Comment (aerfrei) [inline pkg/cmd/roachtest/tests/cdc.go:1162]: I think this could use a comment on the role of changefeed.span_checkpoint.interval when we don't actually do a span level checkpoint

**Review by aerfrei — APPROVED** [review]

File: pkg/cmd/roachtest/tests/cdc.go (hunk 1 above)
Comment (andyyang890) [reply pkg/cmd/roachtest/tests/cdc.go:1162]: Good call, I added a comment to the test and also to the setting code comment itself (didn't update the setting doc comment because it's not public and it's an implementation detail)
