### PR TITLE
roachtest: enable Go execution traces in kv/restart/nodes=12

### LINKED ISSUE #166364: roachtest: kv/restart/nodes=12 failed
roachtest.kv/restart/nodes=12 [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestWeeklyBazel/21276409?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestWeeklyBazel/21276409?buildTab=artifacts#/kv/restart/nodes=12) on master @ [f23224058c9abebd8a5c1c7a64056255ae3c0d70](https://github.com/cockroachdb/cockroach/commits/f23224058c9abebd8a5c1c7a64056255ae3c0d70):

Failed with:

```
(assertions.go:387).Fail: 
	Error Trace:	pkg/cmd/roachtest/roachtestutil/profile.go:297
	            				pkg/cmd/roachtest/roachtestutil/profile.go:303
	            				pkg/cmd/roachtest/tests/kv.go:1129
	            				pkg/cmd/roachtest/monitor.go:233
	            				external/org_golang_x_sync/errgroup/errgroup.go:93
	            				src/runtime/asm_amd64.s:1693
	Error:      	Received unexpected error:
	            	read tcp 172.17.0.3:42070->34.139.138.188:26257: i/o timeout
	Test:       	kv/restart/nodes=12
(require.go:1401).NoError: FailNow called
(monitor.go:267).Wait: monitor failure: context canceled
test artifacts and logs in: /artifacts/kv/restart/nodes=12/run_1
```
Cluster Node to Ip Mapping:
| Node | Public IP | Private IP |
| --- | --- | --- |
| teamcity-21276409-1774072671-81-n13cpu8-0001 | 35.196.55.115 | 10.142.1.186 |
| teamcity-21276409-1774072671-81-n13cpu8-0002 | 34.24.88.2 | 10.142.0.88 |
| teamcity-21276409-1774072671-81-n13cpu8-0003 | 34.139.138.188 | 10.142.1.65 |
| teamcity-21276409-1774072671-81-n13cpu8-0004 | 34.24.144.228 | 10.142.1.86 |
| teamcity-21276409-1774072671-81-n13cpu8-0005 | 34.23.46.237 | 10.142.1.188 |
| teamcity-21276409-1774072671-81-n13cpu8-0006 | 34.148.149.33 | 10.142.1.81 |
| teamcity-21276409-1774072671-81-n13cpu8-0007 | 35.185.98.85 | 10.142.1.183 |
| teamcity-21276409-1774072671-81-n13cpu8-0008 | 34.26.200.62 | 10.142.1.187 |
| teamcity-21276409-1774072671-81-n13cpu8-0009 | 35.237.150.229 | 10.142.0.8 |
| teamcity-21276409-1774072671-81-n13cpu8-0010 | 34.24.103.104 | 10.142.1.185 |
| teamcity-21276409-1774072671-81-n13cpu8-0011 | 35.237.197.182 | 10.142.0.247 |
| teamcity-21276409-1774072671-81-n13cpu8-0012 | 34.75.101.98 | 10.142.0.223 |
| teamcity-21276409-1774072671-81-n13cpu8-0013 | 34.74.56.1 | 10.142.0.242 |

Parameters:
 - <code>MetamorphicFilesystem=ext4</code>
 - <code>MetamorphicVolumeType=pd-ssd</code>
 - <code>arch=amd64</code>
 - <code>cloud=gce</code>
 - <code>coverageBuild=false</code>
 - <code>cpu=8</code>
 - <code>diskCount=0</code>
 - <code>encrypted=false</code>
 - <code>fs=ext4</code>
 - <code>localSSD=false</code>
 - <code>metamorphicLeases=default</code>
 - <code>metamorphicWriteBuffering=true</code>
 - <code>runtimeAssertionsBuild=false</code>
<details><summary>Help</summary>
<p>

See: [roachtest README](https://github.com/cockroachdb/cockroach/blob/master/pkg/cmd/roachtest/README.md)

See: [How To Investigate \(internal\)](https://cockroachlabs.atlassian.net/l/c/SSSBr8c7)

See: [Grafana](https://go.crdb.dev/roachtest-grafana/teamcity-21276409/kv-restart-nodes-12/1774109082194/1774115423389)

</p>
</details>
/cc @cockroachdb/admission-control
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*kv/restart/nodes=12.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/bazci/githubpost/issues)

</sub>

Jira issue: CRDB-61875

### PR DESCRIPTION
**Pull request by tbg**
Enable continuous Go execution tracing on all nodes in the
`kv/restart/nodes=12` test to aid diagnosis of transient resource
spikes like the one in #166364, where a CGO/memory spike on node 3
caused a TCP timeout but neither the Datadog logs nor pebble logs
revealed the trigger.

The execution tracer captures goroutine scheduling, syscalls, and
GC activity. Traces are written to disk and collected as artifacts
on test failure.

Settings added:
- `obs.execution_tracer.interval` = 10s
- `obs.execution_tracer.duration` = 10s
- `obs.execution_tracer.total_dump_size_limit` = 10 GiB

Closes https://github.com/cockroachdb/cockroach/issues/166364.

### CODE REVIEW

File: pkg/cmd/roachtest/tests/kv.go [hunk 1]
```diff
@@ -1063,6 +1063,9 @@ func registerKVRestartImpact(r registry.Registry) {
 			startOpts.RoachprodOpts.ExtraArgs = append(startOpts.RoachprodOpts.ExtraArgs,
 				"--vmodule=store_rebalancer=2,allocator=2,allocator_scorer=1,replicate_queue=2,lease=2")
 			settings := install.MakeClusterSettings()
+			settings.ClusterSettings["obs.execution_tracer.interval"] = "10s"
```
Comment (pav-kv) [inline pkg/cmd/roachtest/tests/kv.go:1068]: Is this temporary? Maybe add a small motivation comment with a link to an issue.

**Review by pav-kv — APPROVED** [review]

File: pkg/cmd/roachtest/tests/kv.go (hunk 1 above)
Comment (tbg) [reply pkg/cmd/roachtest/tests/kv.go:1068]: Done, added a comment with a link to #166364.
