### PR TITLE
sql: populate Oid on type upgrade

### LINKED ISSUE #44453: sql: restoring 2.1 backup into 20.1 cluster succeeds but seems to be in a bad state
I successfully restored a backup of a database (that I believe was created on 2.1 cluster) onto the current master (20.1). However, the system tables seem to be in a bad state.

The backup is linked to our internal wiki page about `querylog` workload (https://cockroachlabs.atlassian.net/wiki/spaces/ENG/pages/74777114/Testing+with+querylog+workload)

Once the data restored, running `SELECT column_name, data_type FROM [SHOW COLUMNS FROM <table_name>];` (for one of the newly-restored tables) crashes the cluster.

My guess is that using this particular backup might not be necessary - maybe creating any backup on 2.1 cluster and then restoring it into 20.1 will have a similar behavior, but I didn't check this.

Assigning to @dt for triage.

### PR DESCRIPTION
**Pull request by pbardea**
When types are unmarshalled, the types are upgraded and the Oid of the
internal type should be set. In 19.1, timestamps received an Oid and
they were populated by the default case in upgradeTypes. However,
a case to handle timestamps was added, but the Oids were no longer
set (as they didn't need to be anymore). However, this meant that
default case was not triggered anymore, so the Oid was no longer
set. This commit also sets the Oid in the timestamp case.

Fixes #44453.

Release note (bug fix): Restoring a backup from 2.1 to 20.1 with a
timestamp column would result in incomplete type data. This would
crash commands such as SHOW COLUMNS FROM <new_table>. This is now
fixed.

### CODE REVIEW

File: pkg/sql/types/types.go [hunk 1]
```diff
@@ -1630,6 +1630,7 @@ func (t *T) upgradeType() error {
 		if t.InternalType.Precision > 0 {
 			t.InternalType.TimePrecisionIsSet = true
 		}
+		t.InternalType.Oid = familyToOid[t.Family()]
 	case IntervalFamily:
```
Comment (jordanlewis) [inline pkg/sql/types/types.go:1634]: We also need this same thing for Intervals.

Comment (jordanlewis) [reply pkg/sql/types/types.go:1634]: Actually, I have a better idea. Can you instead remove the `default` case, and move it into an block after the switch statement, conditional on the Oid still being 0? That would protect us from future problems like this.

Comment (otan) [reply pkg/sql/types/types.go:1634]: should be able to add tests to this as well (there are upgradeType tests in types_test.go)

**Review by otan — COMMENTED** [review]
oops. thanks for catching this.

File: pkg/sql/types/types.go (hunk 1 above)
Comment (pbardea) [reply pkg/sql/types/types.go]: I added tests that test an empty type with just the family always gets the correct Oid set - this was failing on timestamps, intervals and arrays before. I also added a test that the Oid for a BitFamily type with visible varbit was not set to the default family ID, but was set to the correct one.

**Review by otan — APPROVED** [review]
LGTM

**Comment by pbardea** [comment]
TFTRs!
bors r+
