### PR TITLE
storage: De-flake TestReplicaBurstPendingCommandsAndRepropose

### LINKED ISSUE #8385: storage: TestReplicaBurstPendingCommandsAndRepropose is flaky
I've seen this on CircleCI, and reproed locally:

```
make stress STRESSFLAGS="-stderr -p 16 -maxfails 1" PKG=./storage 
TESTS=TestReplicaBurstPendingCommandsAndRepropose

--- FAIL: TestReplicaBurstPendingCommandsAndRepropose (0.01s)
	replica_test.go:6033: expected indexes [1 2 3 4 5 6 7 8 9 10], got [1 2 3 4 5 6 7 8 9 10 1 2 3 4 5 6 7 8 9 10]

2109 runs completed, 1 failures, over 33s
```

I've looked at the test a bit but didn't get very far. Ben, if you'd like me to investigate more, please assign back and I'll come with some questions.

### PR DESCRIPTION
**Pull request by bdarnell**
Fixes #8385 

I could reproduce the failure easily at first (and added logging to see the reasons of the two repropsals), but when I added enough logging to see why we might be getting new leaders I was no longer able to reproduce it.

---

This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/8419)

### CODE REVIEW

File: storage/replica_test.go [hunk 1]
```diff
@@ -5953,7 +5953,13 @@ func TestReplicaCancelRaftCommandProgress(t *testing.T) {
 func TestReplicaBurstPendingCommandsAndRepropose(t *testing.T) {
 	defer leaktest.AfterTest(t)()
 	var tc testContext
-	tc.Start(t)
+	sc := TestStoreContext()
+	// Ensure that the refresh call in this test is the only reason
+	// commands will get reproposed.
+	// TODO(bdarnell): why is this single-node test seeing a "new
+	// leader" (on rare occasions)?
```
Comment (petermattis) [inline storage/replica_test.go]: Seems worthwhile to track this down. Or file an issue.

**Comment by petermattis** [comment]
LGTM

**Comment by tamird** [comment]
This test continues to fail. Is this PR mergeable? Looks like the follow-up issue has been filed #8422.
