### PR TITLE
server: update TestRangeResponse unit test to work correctly with secondary tenant

### LINKED ISSUE #110018: server: the "range" status API endpoint should work with secondary tenants with sufficient capability
Found while investigating #110001.

**Describe the problem**

When `TestRangeResponse` in `server/storage_api` is modified to point to a secondary tenant (e.g. via #110008), the test starts failing when accessing the `/_status/range`  (NB: not `ranges`) endpoint:

```
    ranges_test.go:153: got the wrong number of ranges in the response, expected 1, actual 0
```

**How to reproduce**

from #110008 reset `DefaultTestTenant`, run the test with a test tenant and observe the failure.

**Expected behavior**

Once the tenant is granted a suitable capability, the endpoint should work properly.

Epic CRDB-38968

Jira issue: CRDB-31224

### PR DESCRIPTION
**Pull request by shaikzakiriitm**
server/storage_api: update TestRangeResponse unit test, to work correctly with secondary application tenant
What was there before: the change focuses on updating the unit test which was failing with secondary tenant while hitting the
_status/range/{id} endpoint. This was happening because the the test had a hard-coded range id `1` to be
fetched from the aforementioned endpoint. And this range id lies outside the scope of a secondary application
tenant.

resolution: made changes to the test to include a range id which lies well within the scope of the secondary tenant.
Fixes: https://github.com/cockroachdb/cockroach/issues/110018
Part of: https://cockroachlabs.atlassian.net/browse/CRDB-31224
Epic: [CRDB-38968](https://cockroachlabs.atlassian.net/browse/CRDB-38968)

Release note: None

### CODE REVIEW

File: pkg/server/storage_api/ranges_test.go [hunk 1]
```diff
@@ -133,21 +133,58 @@ func TestRangeResponse(t *testing.T) {
 	defer log.Scope(t).Close(t)
 	defer kvserver.EnableLeaseHistoryForTesting(100)()
 	srv := serverutils.StartServerOnly(t, base.TestServerArgs{
-		DefaultTestTenant: base.TestIsForStuffThatShouldWorkWithSecondaryTenantsButDoesntYet(110018),
+		DefaultTestTenant: base.TestTenantProbabilistic,
```
Comment (shubhamdhama) [inline pkg/server/storage_api/ranges_test.go:136]: We can remove this argument and use the default value.

File: pkg/server/storage_api/ranges_test.go [hunk 2]
```diff
@@ -133,21 +133,58 @@ func TestRangeResponse(t *testing.T) {
...
 	})
 	defer srv.Stopper().Stop(context.Background())
 	ts := srv.ApplicationLayer()
 
+	t.Logf("value of StartedDefaultTestTenant %v", srv.StartedDefaultTestTenant())
+
```
Comment (shubhamdhama) [inline pkg/server/storage_api/ranges_test.go:142]: When unit tests are run they print the mode of deployment

File: pkg/server/storage_api/ranges_test.go [hunk 3]
```diff
@@ -133,21 +133,58 @@ func TestRangeResponse(t *testing.T) {
...
+		// get some ranges from the given table
+		queryResult := r.Query(t, "SELECT range_id FROM [SHOW RANGES FROM TABLE t WITH DETAILS] LIMIT 1;")
+		defer queryResult.Close()
+
+		queryResult.Next()
+
+		if err := queryResult.Scan(&currentTenantRangeId); err != nil {
+			t.Fatal(err)
+		}
```
Comment (shubhamdhama) [inline pkg/server/storage_api/ranges_test.go:168]: We can replace this with
```go
		runner.QueryRow(t, query).Scan(&currentTenantRangeId)
```

File: pkg/server/storage_api/ranges_test.go [hunk 4]
```diff
@@ -133,21 +133,58 @@ func TestRangeResponse(t *testing.T) {
...
 		t.Fatal(err)
 	}
 
-	// TODO(#110018): grant a special capability to the secondary tenant
-	// before the endpoint can be accessed.
+	var isSystemTenant bool = !srv.StartedDefaultTestTenant()
+	t.Run("access range endpoint within current tenant's scope", func(t *testing.T) {
+		// Test case 1, looking for a range id which lies within the current tenant's (system or secondary tenant, chosen probabilistically) range
+		var currentTenantRangeId int64 // could be a system tenant or a secondary application tenant
+		t.Logf("Is system tenant enabled : %v", isSystemTenant)
```
Comment (shubhamdhama) [inline pkg/server/storage_api/ranges_test.go:152]: I think we can remove all these log statements (I'm not very convinced if they are adding value here).

File: pkg/server/storage_api/ranges_test.go [hunk 5]
```diff
@@ -133,21 +133,58 @@ func TestRangeResponse(t *testing.T) {
...
+			t.Fatal(err)
+		}
+		t.Logf("currentTenantRangeId : %v", currentTenantRangeId)
+		validateRangeBelongsToTenant(t, ts, fmt.Sprintf("range/%d", currentTenantRangeId))
+	})
+
+	t.Run("access range endpoint within system tenant's scope", func(t *testing.T) {
+		// Test case 2, looking for a range which lies within system tenant's range
+		if isSystemTenant {
+			validateRangeBelongsToTenant(t, ts, "range/1")
```
Comment (shubhamdhama) [inline pkg/server/storage_api/ranges_test.go:176]: I would also validate that a tenant _cannot_ access this range (it fails). And right now this test would no-op when it's not a tenant. So how about moving `t.Run` in this `if` and another one for the failure condition in a new `else` condition.

File: pkg/server/storage_api/ranges_test.go [hunk 6]
```diff
@@ -133,21 +133,58 @@ func TestRangeResponse(t *testing.T) {
...
+			t.Logf("Executing the test case 2 for range/1")
+		}
+
+	})
+}
 
+func validateRangeBelongsToTenant(
+	t *testing.T, ts serverutils.ApplicationLayerInterface, rangeQueryPath string,
```
Comment (shubhamdhama) [inline pkg/server/storage_api/ranges_test.go:184]: Just a range id would be more concise

**Review by shubhamdhama — CHANGES_REQUESTED** [review]
Congrats on your first PR 🎉 

It's a great start. I have left some minor comments.

**Comment by shubhamdhama** [comment]
I have some suggestions for the commit message too,
1. You can remove the first line of "Fix for the issue #110018". It's mentioned later in `Fixes`
2. "Part of" can be removed IMO

File: pkg/server/storage_api/ranges_test.go [hunk 7]
```diff
@@ -133,21 +133,58 @@ func TestRangeResponse(t *testing.T) {
...
+	t.Logf("value of StartedDefaultTestTenant %v", srv.StartedDefaultTestTenant())
+
 	// Perform a scan to ensure that all the raft groups are initialized.
 	if _, err := srv.SystemLayer().DB().Scan(context.Background(), keys.LocalMax, roachpb.KeyMax, 0); err != nil {
 		t.Fatal(err)
 	}
 
-	// TODO(#110018): grant a special capability to the secondary tenant
-	// before the endpoint can be accessed.
+	var isSystemTenant bool = !srv.StartedDefaultTestTenant()
```
Comment (cthumuluru-crdb) [inline pkg/server/storage_api/ranges_test.go:148]: I find this check to be fragile. It only indicates whether the default test tenant has started. Without seeing the implementation, it's unclear if `srv.ApplicationLayer()` always returns the test tenant when it is running. Since the behavior is expected to be different between the system and test tenants, how about we let the test control tenancy (`TestControlsTenantsExplicitly`) and test both?

File: pkg/server/storage_api/ranges_test.go [hunk 8]
```diff
@@ -133,21 +133,58 @@ func TestRangeResponse(t *testing.T) {
...
+		r.Exec(t, "CREATE TABLE t (x INT PRIMARY KEY, xsquared INT)")
+		for i := 0; i < 5; i++ {
+			r.Exec(t, fmt.Sprintf("ALTER TABLE t SPLIT AT VALUES (%d)", 100*i/5))
+		}
+
+		// get some ranges from the given table
+		queryResult := r.Query(t, "SELECT range_id FROM [SHOW RANGES FROM TABLE t WITH DETAILS] LIMIT 1;")
+		defer queryResult.Close()
+
+		queryResult.Next()
```
Comment (cthumuluru-crdb) [inline pkg/server/storage_api/ranges_test.go:164]: nit: Maybe fail the test if `queryResult.Next()` returns false?

File: pkg/server/storage_api/ranges_test.go (hunk 5 above)
Comment (cthumuluru-crdb) [reply pkg/server/storage_api/ranges_test.go:176]: +1

**Review by cthumuluru-crdb — CHANGES_REQUESTED** [review]

**Comment by cthumuluru-crdb** [comment]
nit: fix the commit title as per https://cockroachlabs.atlassian.net/wiki/spaces/CRDB/pages/73072807/Git+Commit+Messages#Commit-title. 

```
Use the imperative mood for titles. For example, write docs: clarify user privileges instead of other moods like docs: claried user privileges or docs: clarifies user privileges.
```

File: pkg/server/storage_api/ranges_test.go (hunk 2 above)
Comment (shaikzakiriitm) [reply pkg/server/storage_api/ranges_test.go:142]: Have removed this print statement from the test code.

I looked at the logs and I can see a log line saying something like `I250130 11:33:23.511248 2408 1@server/tenant.go:301  [n1] 194  server starting for tenant "10"` when the tenant was enabled. However, I didn't find any specific logs w.r.t. system tenant starting. Can you point me to those logs for my reference? Or is it just the absence of this very log statement points to the fact that the test is started with a system tenant? Thanks!

File: pkg/server/storage_api/ranges_test.go (hunk 6 above)
Comment (shaikzakiriitm) [reply pkg/server/storage_api/ranges_test.go:184]: IMO, even the string parameter is equally concise. But let me just pass the range id and construct the query string within the validate method.

**Comment by shaikzakiriitm** [comment]
> 1. You can remove the first line of "Fix for the issue [server: the "range" status API endpoint should work with secondary tenants with sufficient capability #110018](https://github.com/cockroachdb/cockroach/issues/110018)". It's mentioned later in `Fixes`

Done
> 2. "Part of" can be removed IMO
I wanted to link the pr with the jira ticket, hence used `Part of`. In the section `Epic`, we can only link this issue with the epic and not the original task ticket. I wanted that connection between this pr and the actual task ticket. Lmk if there is another way you would suggest this linking.

**Comment by shaikzakiriitm** [comment]
> nit: fix the commit title as per https://cockroachlabs.atlassian.net/wiki/spaces/CRDB/pages/73072807/Git+Commit+Messages#Commit-title.
> 
> ```
> Use the imperative mood for titles. For example, write docs: clarify user privileges instead of other moods like docs: claried user privileges or docs: clarifies user privileges.
> ```

done 👍

File: pkg/server/storage_api/ranges_test.go (hunk 5 above)
Comment (shaikzakiriitm) [reply pkg/server/storage_api/ranges_test.go:176]: Updated the test to include the validation that a secondary application tenant trying to access a range outside of its scope ends up failing. 
Didn't move `t.Run` within `if`. Rather, created an else block within the `t.Run` and ensured/asserted that it fails when run with `base.TestTenantAlwaysEnabled`.

File: pkg/server/storage_api/ranges_test.go (hunk 8 above)
Comment (shaikzakiriitm) [reply pkg/server/storage_api/ranges_test.go:164]: Updated the query as suggested in another comment https://github.com/cockroachdb/cockroach/pull/139841#discussion_r1933720565

Hence, this current suggestion doesn't look applicable now as we aren't calling `queryResult.Next()` anymore.

File: pkg/server/storage_api/ranges_test.go (hunk 7 above)
Comment (shaikzakiriitm) [reply pkg/server/storage_api/ranges_test.go:148]: Based on our offline discussion, I completely agree that there is a need where we should be able to identify with some certainty about what `srv.ApplicationLayer()` invocation returns (i.e. we need to know with certainty whether this method returns a system tenant or a secondary application tenant), even though the description (or contract) says that it can return either system or secondary tenant probabilistically with some randomization. This adds more clarity and disambiguates the test cases which we run. 

Looking at some other test cases like [this](https://github.com/cockroachdb/cockroach/blob/5b931856d005214057f0703890ce3a77cdc21f30/pkg/ccl/spanconfigccl/spanconfiglimiterccl/datadriven_test.go#L137-L142), apparently many such tests are already using this method `StartedDefaultTestTenant()` for the very same purpose which we are using it for i.e. to distinguish between the cases where test is run using system tenant or secondary application tenant. As mentioned in your comment and this discussion, this is not the foolproof way as the contract is a bit ambiguous. I'll file a backlog ticket for this to track it and share it here later. 

Thanks for the discussion, this is helpful.

Comment (cthumuluru-crdb) [reply pkg/server/storage_api/ranges_test.go:144]: Sure, please create a tracking ticket and we can address that separately.

File: pkg/server/storage_api/ranges_test.go [hunk 9]
```diff
@@ -143,29 +141,56 @@ func TestRangeResponse(t *testing.T) {
...
 
+	t.Run("access range endpoint within system tenant's scope", func(t *testing.T) {
+		if isSystemTenant {
+			require.NoError(t, validateRangeBelongsToTenant(ts, 1))
+			t.Logf("Executing the test case 2 for range/1")
+		} else {
+			expectedError := fmt.Errorf("got the wrong number of ranges in the response, expected %d, actual %d", 1, 0)
+			actualError := validateRangeBelongsToTenant(ts, 1)
+			require.Error(t, actualError)
+			require.Equal(t, expectedError, actualError)
```
Comment (cthumuluru-crdb) [inline pkg/server/storage_api/ranges_test.go:167]: Consider `require.ErrorContains()` with "wrong number of ranges in the response" substring.

File: pkg/server/storage_api/ranges_test.go [hunk 10]
```diff
@@ -143,29 +141,56 @@ func TestRangeResponse(t *testing.T) {
...
+		// get some ranges from the given table
+		r.QueryRow(t, "SELECT range_id FROM [SHOW RANGES FROM TABLE t WITH DETAILS] LIMIT 1;").Scan(&currentTenantRangeId)
+		t.Logf("currentTenantRangeId : %v", currentTenantRangeId)
+		require.NoError(t, validateRangeBelongsToTenant(ts, currentTenantRangeId))
+	})
 
+	t.Run("access range endpoint within system tenant's scope", func(t *testing.T) {
+		if isSystemTenant {
+			require.NoError(t, validateRangeBelongsToTenant(ts, 1))
+			t.Logf("Executing the test case 2 for range/1")
```
Comment (cthumuluru-crdb) [inline pkg/server/storage_api/ranges_test.go:162]: nit: log line may not be needed.

**Review by cthumuluru-crdb — APPROVED** [review]
Congrats on your first PR!

File: pkg/server/storage_api/ranges_test.go (hunk 9 above)
Comment (shaikzakiriitm) [reply pkg/server/storage_api/ranges_test.go:167]: This is a custom message which is added as part of the unit test returned from the invocation of `validateRangeBelongsToTenant()`. Sticking to full error message comparison as this error message is something which is articulated as part of this test and not something returned from the applicationServer or any other such component.

Comment (cthumuluru-crdb) [reply pkg/server/storage_api/ranges_test.go:167]: Please consider that comment as nit. You can also checkout `require.EqualError()` and `require.EqualErrorf()` if any of them fit better here.

File: pkg/server/storage_api/ranges_test.go [hunk 11]
```diff
@@ -143,29 +141,55 @@ func TestRangeResponse(t *testing.T) {
...
+		var currentTenantRangeId int64
+		// create a new table from the current tenant
+		r := sqlutils.MakeSQLRunner(ts.SQLConn(t))
+		r.Exec(t, "CREATE TABLE t (x INT PRIMARY KEY, xsquared INT)")
+		for i := 0; i < 5; i++ {
+			r.Exec(t, fmt.Sprintf("ALTER TABLE t SPLIT AT VALUES (%d)", 100*i/5))
+		}
+		// get some ranges from the given table
+		r.QueryRow(t, "SELECT range_id FROM [SHOW RANGES FROM TABLE t WITH DETAILS] LIMIT 1;").Scan(&currentTenantRangeId)
+		t.Logf("currentTenantRangeId : %v", currentTenantRangeId)
```
Comment (shubhamdhama) [inline pkg/server/storage_api/ranges_test.go:155]: nit: `s/%v/%d`
Also, maybe some user friendly string "Table 't' range: %s"

File: pkg/server/storage_api/ranges_test.go [hunk 12]
```diff
@@ -143,29 +141,55 @@ func TestRangeResponse(t *testing.T) {
...
+		require.NoError(t, validateRangeBelongsToTenant(ts, currentTenantRangeId))
+	})
 
+	t.Run("access range endpoint within system tenant's scope", func(t *testing.T) {
+		if isSystemTenant {
```
Comment (shubhamdhama) [inline pkg/server/storage_api/ranges_test.go:160]: nit: `isSystemTenant` is only used here, so no need to create a variable for this?

**Review by shubhamdhama — APPROVED** [review]
LGTM!

Left some nits, otherwise looks good.

**Comment by shubhamdhama** [comment]
I think you need to fixup last two commits into the first commit. The end state should contain only one commit.

**Comment by shaikzakiriitm** [comment]
bors r=shubhamdhama,cthumuluru-crdb

**Comment by shaikzakiriitm** [comment]
Thank you @shubhamdhama @cthumuluru-crdb for your feedback and reviews for my first pr.
