### PR TITLE
backupccl: fix error when the restore rollback cleanup validates uncommitted schema descriptor

### LINKED ISSUE #70049: backup/restore: rollback does not clean up properly when UDTs and UDS are used together
Sample test case derived from `TestRestoreTypeDescriptorsRollBack` in `backup_test.go`
Rollback works correctly when the type/tables are created in the public schema, however when a UDS is used, you get the error

Came up when trying to make backup/restore work with descriptor backed public schemas in https://github.com/cockroachdb/cockroach/pull/68674

```
E210910 19:22:11.666362 3044 jobs/adopt.go:420  [n1] 1  job 692162827524079617: adoption completed with error job 692162827524079617: cannot be reverted, manual cleanup may be required: schema "s" (60): not present in parent database [59] schemas mapping
E210910 19:22:11.667014 1386 sql/sqltelemetry/report.go:57  [n1,client=127.0.0.1:58894,hostssl,user=root] 2  encountered internal error:
E210910 19:22:11.667014 1386 sql/sqltelemetry/report.go:57  [n1,client=127.0.0.1:58894,hostssl,user=root] 2 +job 692162827524079617: cannot be reverted, manual cleanup may be required: schema "s" (60): not present in parent database [59] schemas mapping
E210910 19:22:11.667014 1386 sql/sqltelemetry/report.go:57  [n1,client=127.0.0.1:58894,hostssl,user=root] 2 +(1)
```

```
func TestRestoreTypeDescriptorsRollBack2(t *testing.T) {
	defer leaktest.AfterTest(t)()
	defer log.Scope(t).Close(t)

	_, tc, sqlDB, _, cleanupFn := BackupRestoreTestSetup(t, singleNode, 0, InitManualReplication)
	defer cleanupFn()

	for _, server := range tc.Servers {
		registry := server.JobRegistry().(*jobs.Registry)
		registry.TestingResumerCreationKnobs = map[jobspb.Type]func(raw jobs.Resumer) jobs.Resumer{
			jobspb.TypeRestore: func(raw jobs.Resumer) jobs.Resumer {
				r := raw.(*restoreResumer)
				r.testingKnobs.beforePublishingDescriptors = func() error {
					return errors.New("boom")
				}
				return r
			},
		}
	}

	sqlDB.Exec(t, `
CREATE DATABASE db;
CREATE SCHEMA db.s;
CREATE TYPE db.s.typ AS ENUM();
CREATE TABLE db.s.table (k INT PRIMARY KEY, v db.s.typ);
`)

	// Back up the database, drop it, and restore into it.
	sqlDB.Exec(t, `BACKUP DATABASE db TO 'nodelocal://0/test/'`)
	sqlDB.Exec(t, `DROP DATABASE db`)
	sqlDB.ExpectErr(t, "boom", `RESTORE DATABASE db FROM 'nodelocal://0/test/'`)
	sqlDB.CheckQueryResults(t, `SELECT count(*) FROM system.namespace WHERE name = 'typ'`, [][]string{{"0"}})
}
```

### PR DESCRIPTION
**Pull request by gh-casper**
Previously, during a restore rollback, we only marked database as dropped to skip pre-txn validation when we drop all descriptors that we created at the start of the restore. This is not sufficient because we will also run validation against user-defined schemas.

This patch marked schema as dropped to skip validation too.

Fixes: #70049
Release note: none.

### CODE REVIEW

File: pkg/ccl/backupccl/restore_job.go [hunk 1]
```diff
@@ -2234,24 +2234,36 @@ func (r *restoreResumer) dropDescriptors(
...
+		mutSchema.SetDropped()
+		mutSchema.MaybeIncrementVersion()
+		if err := descsCol.AddUncommittedDescriptor(mutSchema); err != nil {
+			return err
+		}
+
+		b.Del(catalogkeys.EncodeNameKey(codec, mutSchema))
+		b.Del(catalogkeys.MakeDescMetadataKey(codec, mutSchema.GetID()))
+		descsCol.AddDeletedDescriptor(mutSchema)
+		dbsWithDeletedSchemas[mutSchema.GetParentID()] = append(dbsWithDeletedSchemas[mutSchema.GetParentID()], mutSchema)
```
Comment (adityamaru) [inline pkg/ccl/backupccl/restore_job.go:2266]: I think we should store to an immutable schema descriptor in this map. Even though it doesn't change much it prevents us from unintentionally mutating the descriptor wherever we use the values in this map.

**Review by adityamaru — APPROVED** [review]
Nice!

File: pkg/ccl/backupccl/restore_job.go (hunk 1 above)
Comment (gh-casper) [reply pkg/ccl/backupccl/restore_job.go:2266]: No worry in this case because what we are adding into `dbsWithDeletedSchemas` map is catalog.Descriptor which only has immutable APIs.
