### PR TITLE
mixedversion: alllow tests to indicate minimum supported version

### LINKED ISSUE #116431: roachtest: backup-restore/mixed-version failed: begins test below min supported version
roachtest.backup-restore/mixed-version [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/13133250?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/13133250?buildTab=artifacts#/backup-restore/mixed-version) on release-23.1 @ [9fbc785c0586e64c3b2351483d62fb04b05d2836](https://github.com/cockroachdb/cockroach/commits/9fbc785c0586e64c3b2351483d62fb04b05d2836):

```
(mixedversion.go:539).Run: mixed-version test failure while running step 5 (run "maybe set custom cluster settings"): pq: unknown cluster setting 'backup.restore_span.target_size'
test artifacts and logs in: /artifacts/backup-restore/mixed-version/run_1
```
<p>Parameters: <code>ROACHTEST_arch=amd64</code>
, <code>ROACHTEST_cloud=gce</code>
, <code>ROACHTEST_cpu=4</code>
, <code>ROACHTEST_encrypted=false</code>
, <code>ROACHTEST_metamorphicBuild=false</code>
, <code>ROACHTEST_ssd=0</code>
</p>
<details><summary>Help</summary>
<p>

See: [roachtest README](https://github.com/cockroachdb/cockroach/blob/master/pkg/cmd/roachtest/README.md)

See: [How To Investigate \(internal\)](https://cockroachlabs.atlassian.net/l/c/SSSBr8c7)

See: [Grafana](https://go.crdb.dev/roachtest-grafana/teamcity-13133250/backup-restore-mixed-version/1702542221015/1702542573631)

</p>
</details>
/cc @cockroachdb/disaster-recovery
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*backup-restore/mixed-version.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)
</sub>

Jira issue: CRDB-34620

### PR DESCRIPTION
**Pull request by renatolabs**
This commit introduces the `MinimumSupportedversion` test option the
mixedversion framework. This option is expected to indicate the
minimum version of CockroachDB that should be running for the test to
run properly. When not set, this version will default to
`OldestSupportedVersion`, which is the oldest version of CockroachDB
still actively supported.

When running an upgrade test with the `mixedversion` framework, we no
longer will schedule user hooks while the cluster is upgrading from
versions older than this minimum supported version. This stops us from
running our tests in exceedingly old versions (especially in release
branches), which should reduce flakes and the likelihood that we will
"rediscover" bugs already fixed.

Note the the cluster might still be bootstrapped from older,
unsupported versions even after this change; this ensures that the
functionality tested works as expected even in clusters created using
older system schemas.

This commit also removes some similar logic in the
`backup-restore/mixed-version` roachtest; that test's behaviour should
now be automatically supported by the framework as the default.

Fixes: #116431

Release note: None

### CODE REVIEW

**Comment by renatolabs** [comment]
Taking a short break from mutators work to introduce this change, which will reduce test failures in old/unsupported releases, which are unlikely to be novel bugs we would be interested in fixing.

Mixed-version tests on this branch pass (the cdc failure is expected and also happens on master):

https://teamcity.cockroachdb.com/viewLog.html?buildId=13558028&buildTypeId=Cockroach_Nightlies_RoachtestNightlyGceBazel&tab=buildResultsDiv

Mutators work will continue once this PR lands.

File: pkg/cmd/roachtest/roachtestutil/mixedversion/planner.go [hunk 1]
```diff
@@ -368,8 +461,9 @@ func (plan *TestPlan) Steps() []testStep {
 // Versions returns the list of versions the cluster goes through in
 // the process of running this mixed-version test.
 func (plan *TestPlan) Versions() []*clusterupgrade.Version {
-	result := []*clusterupgrade.Version{plan.upgrades[0].from}
-	for _, upgrade := range plan.upgrades {
+	upgrades := plan.allUpgrades()
+	result := []*clusterupgrade.Version{upgrades[0].from}
```
Comment (srosenberg) [inline pkg/cmd/roachtest/roachtestutil/mixedversion/planner.go:465]: Not immediately clear if this list may contain duplicates?

File: pkg/cmd/roachtest/roachtestutil/mixedversion/planner.go [hunk 2]
```diff
@@ -235,13 +281,31 @@ func (p *testPlanner) changeVersionSteps(
...
 		))
 		p.currentContext.changeVersion(node, to)
-		steps = append(steps, p.hooks.MixedVersionSteps(p.currentContext)...)
+		if scheduleHooks {
+			steps = append(steps, p.hooks.MixedVersionSteps(p.currentContext)...)
+		} else if j == waitIndex {
+			// If we are not scheduling user-provided hooks, we wait a short
+			// while in this state to allow some time for background
+			// operations to run.
+			possibleWaitMinutes := []int{5, 10, 15}
```
Comment (srosenberg) [inline pkg/cmd/roachtest/roachtestutil/mixedversion/planner.go:305]: 15 mins may seem on a higher end for all upgrades, no?

File: pkg/cmd/roachtest/roachtestutil/mixedversion/planner.go [hunk 3]
```diff
@@ -200,32 +234,44 @@ func (p *testPlanner) initUpgradeSteps() []testStep {
...
 // changeVersionSteps returns the sequence of steps to be performed
 // when we are changing the version of cockroach in the nodes of a
 // cluster (either upgrading to a new binary, or downgrading to a
-// predecessor version).
+// predecessor version). If `scheduleHooks` is true, user-provided
+// mixed-version hooks will be scheduled randomly during the
+// upgrade/downgrade process.
 func (p *testPlanner) changeVersionSteps(
-	from, to *clusterupgrade.Version, label string,
+	from, to *clusterupgrade.Version, label string, scheduleHooks bool,
```
Comment (srosenberg) [inline pkg/cmd/roachtest/roachtestutil/mixedversion/planner.go:274]: Nit: maybe `addHooks`, since there isn't any explicit scheduling here, we're merely adding them as (planned) steps.

File: pkg/cmd/roachtest/roachtestutil/mixedversion/mixedversion.go [hunk 4]
```diff
@@ -1011,4 +1052,20 @@ func assertValidTest(test *Test, fatalFunc func(...interface{})) {
...
 		fatalFunc(errors.Wrap(err, "mixedversion.NewTest"))
 	}
+
+	currentVersion := clusterupgrade.CurrentVersion()
+	msv := test.options.minimumSupportedVersion
+	// The minimum supported version should be from an older major
+	// version or, if from the same major version, from an older minor
+	// version.
+	validVersion := msv.Major() < currentVersion.Major() ||
+		(msv.Major() == currentVersion.Major() && msv.Minor() < currentVersion.Minor())
```
Comment (srosenberg) [inline pkg/cmd/roachtest/roachtestutil/mixedversion/mixedversion.go:1062]: Shouldn't be `msv.Minor() <= currentVersion.Minor()`?

**Review by srosenberg — APPROVED** [review]

File: pkg/cmd/roachtest/roachtestutil/mixedversion/planner.go [hunk 5]
```diff
@@ -348,16 +415,42 @@ func (plan *TestPlan) assignIDs() {
...
+		assignIDsToSteps(upgrade.sequentialStep.steps)
+	}
+
 	assignIDsToSteps(plan.initSteps)
 	for _, upgrade := range plan.upgrades {
 		assignIDsToSteps(upgrade.sequentialStep.steps)
 	}
 }
 
+// allUpgrades returns a list of all upgrades this encoded in this
```
[the remark this answers is not in the document]
Comment (renatolabs) [reply pkg/cmd/roachtest/roachtestutil/mixedversion/planner.go]: Fixed.

File: pkg/cmd/roachtest/roachtestutil/mixedversion/planner.go (hunk 1 above)
Comment (renatolabs) [reply pkg/cmd/roachtest/roachtestutil/mixedversion/planner.go:466]: There are no duplicates (if there were, that would be an internal bug in the planner).

`allUpgrades` returns a list of all setup upgrades, followed by the test's upgrades. These run in order. An upgrade can either be run during setup or during "test" time, along with user functions.

I added a note about this in the comments, hopefully it makes this clearer.

File: pkg/cmd/roachtest/roachtestutil/mixedversion/planner.go (hunk 2 above)
Comment (renatolabs) [reply pkg/cmd/roachtest/roachtestutil/mixedversion/planner.go]: Yeah, I think it's probably fine on master, but it could add up to quite a bit in the worst case scenario in release branches (especially 23.1). I changed this to `{1,5,10}`; we can reduce it further if necessary in the future.

File: pkg/cmd/roachtest/roachtestutil/mixedversion/planner.go (hunk 3 above)
Comment (renatolabs) [reply pkg/cmd/roachtest/roachtestutil/mixedversion/planner.go:275]: I'm not a huge fan of `addHooks` because `add` is a bit generic. I understand that this is not scheduling in the OS sense (moving something from ready to "run"); `schedule` here was meant more according to this definition:

> to plan something for a particular time
> 
> https://dictionary.cambridge.org/dictionary/english/schedule

which I would argue is what this function is doing.

The planner is explicitly designed to not run anything, so hopefully "schedule" isn't too confusing. That said, I was trying to come up with a better name and nothing felt much better (`planHooks` was the best I could come up with). Let me know if you would still prefer that, I can make the change.

File: pkg/cmd/roachtest/roachtestutil/mixedversion/mixedversion.go (hunk 4 above)
Comment (renatolabs) [reply pkg/cmd/roachtest/roachtestutil/mixedversion/mixedversion.go:1062]: That would allow the case where the minimum supported version and the current version differ only on patch/prerelese, i.e., they are part of the same release series. This means that this "upgrade" would not involve running migrations or changing the cluster version.

Since everything else in `mixedversion` is designed around upgrading from one series to the next, I felt like it's best to disallow this scenario at this moment.

File: pkg/cmd/roachtest/roachtestutil/mixedversion/planner.go (hunk 3 above)
Comment (srosenberg) [reply pkg/cmd/roachtest/roachtestutil/mixedversion/planner.go:275]: Yep, it's fine as is, plus it's internal documentation. So, I should really RTFM :)

File: pkg/cmd/roachtest/roachtestutil/mixedversion/mixedversion.go (hunk 4 above)
Comment (srosenberg) [reply pkg/cmd/roachtest/roachtestutil/mixedversion/mixedversion.go:1062]: Makes sense; maybe the error message below could be made more precise in case the difference comes down to patch versions.

Comment (renatolabs) [reply pkg/cmd/roachtest/roachtestutil/mixedversion/mixedversion.go:1062]: Changed error to say `minimum supported version should be from an older release series than current version`.

**Comment by renatolabs** [comment]
TFTR!

bors r=srosenberg
