### PR TITLE
Fix unnecessary quoting of non-reserved keywords.

### LINKED ISSUE #2108: sql: fix unnecessary quoting of non reserved keywords
Only reserved keywords need to be quoted during output. Currently, `SELECT name FROM foo` will be output as `SELECT "name" FROM foo`. The existing `keywords` table needs to be extended with a `reservedKeywords` table containing only the reserved keywords.

### PR DESCRIPTION
**Pull request by petermattis**
Added a "reservedKeywords" map that is used to determine when a
parser.Name needs to be quoted. This map is automatically generated from
the reserved_keywords grammar rule.

Fixes #2108.

### CODE REVIEW

File: sql/parser/encode.go [hunk 1]
```diff
@@ -61,7 +61,7 @@ func encodeSQLString(buf []byte, in []byte) []byte {
 
 // TODO(pmattis): This method needs testing.
```
Comment (tamird) [inline sql/parser/encode.go]: looks like it's tested indirectly in `TestQualifiedNameString`

**Comment by tamird** [comment]
LGTM

File: sql/parser/encode.go (hunk 1 above)
Comment (petermattis) [inline sql/parser/encode.go]: Hmm, good point. That test is misnamed. I'll remove this comment.
