### PR TITLE
sql: remove slow functions from TestRandomSyntaxFunctions

### LINKED ISSUE #107929: sql/tests: TestRandomSyntaxFunctions failed
sql/tests.TestRandomSyntaxFunctions [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RandomSyntaxTestsBazel/11134564?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RandomSyntaxTestsBazel/11134564?buildTab=artifacts#/) on master @ [fcfa15d9694c0b840ac0c5c1b1489fa90a62efd8](https://github.com/cockroachdb/cockroach/commits/fcfa15d9694c0b840ac0c5c1b1489fa90a62efd8):

Fatal error:

```
panic: test timed out after 14m55s

```
Stack: 

```
goroutine 5187798 [running]:
testing.(*M).startAlarm.func1()
	GOROOT/src/testing/testing.go:2036 +0x8e
created by time.goFunc
	GOROOT/src/time/sleep.go:176 +0x32
```
<details><summary>Log preceding fatal error</summary>
<p>

```
    rsg_test.go:832: 45s of 5m0s: 144985 executions, 90074 successful
    rsg_test.go:832: 50s of 5m0s: 161358 executions, 100117 successful
    rsg_test.go:832: 55s of 5m0s: 178252 executions, 110757 successful
    rsg_test.go:832: 1m0s of 5m0s: 194554 executions, 120766 successful
    rsg_test.go:832: 1m5s of 5m0s: 206560 executions, 128234 successful
    rsg_test.go:832: 1m10s of 5m0s: 222997 executions, 138485 successful
    rsg_test.go:832: 1m15s of 5m0s: 239703 executions, 148821 successful
    rsg_test.go:832: 1m20s of 5m0s: 256356 executions, 159289 successful
    rsg_test.go:832: 1m25s of 5m0s: 273035 executions, 169458 successful
    rsg_test.go:832: 1m30s of 5m0s: 287272 executions, 178276 successful
    rsg_test.go:832: 1m35s of 5m0s: 304013 executions, 188607 successful
    rsg_test.go:832: 1m40s of 5m0s: 321278 executions, 199441 successful
    rsg_test.go:832: 1m45s of 5m0s: 338558 executions, 210168 successful
    rsg_test.go:832: 1m50s of 5m0s: 355607 executions, 220778 successful
    rsg_test.go:832: 1m55s of 5m0s: 372415 executions, 231119 successful
    rsg_test.go:832: 2m0s of 5m0s: 386533 executions, 239961 successful
    rsg_test.go:832: 2m5s of 5m0s: 403742 executions, 250553 successful
    rsg_test.go:832: 2m10s of 5m0s: 420319 executions, 260919 successful
    rsg_test.go:832: 2m15s of 5m0s: 436975 executions, 271183 successful
    rsg_test.go:832: 2m20s of 5m0s: 453789 executions, 281704 successful
    rsg_test.go:832: 2m25s of 5m0s: 470924 executions, 292259 successful
    rsg_test.go:832: 2m30s of 5m0s: 487276 executions, 302413 successful
    rsg_test.go:832: 2m35s of 5m0s: 502215 executions, 311581 successful
    rsg_test.go:832: 2m40s of 5m0s: 519277 executions, 322196 successful
    rsg_test.go:832: 2m45s of 5m0s: 536272 executions, 332689 successful
    rsg_test.go:832: 2m50s of 5m0s: 553185 executions, 343237 successful
    rsg_test.go:832: 2m55s of 5m0s: 570446 executions, 353916 successful
    rsg_test.go:832: 3m0s of 5m0s: 587236 executions, 364266 successful
    rsg_test.go:832: 3m5s of 5m0s: 600699 executions, 372581 successful
    rsg_test.go:832: 3m10s of 5m0s: 616980 executions, 382614 successful
    rsg_test.go:832: 3m15s of 5m0s: 634510 executions, 393535 successful
    rsg_test.go:832: 3m20s of 5m0s: 651195 executions, 403914 successful
    rsg_test.go:832: 3m25s of 5m0s: 668649 executions, 414773 successful
    rsg_test.go:832: 3m30s of 5m0s: 684841 executions, 424735 successful
    rsg_test.go:832: 3m35s of 5m0s: 700044 executions, 434308 successful
    rsg_test.go:832: 3m40s of 5m0s: 715905 executions, 444177 successful
    rsg_test.go:832: 3m45s of 5m0s: 733194 executions, 454960 successful
    rsg_test.go:832: 3m50s of 5m0s: 750034 executions, 465333 successful
    rsg_test.go:832: 3m55s of 5m0s: 767415 executions, 476100 successful
    rsg_test.go:832: 4m0s of 5m0s: 784547 executions, 486772 successful
    rsg_test.go:832: 4m5s of 5m0s: 799945 executions, 496392 successful
    rsg_test.go:832: 4m10s of 5m0s: 816287 executions, 506551 successful
    rsg_test.go:832: 4m15s of 5m0s: 832752 executions, 516803 successful
    rsg_test.go:832: 4m20s of 5m0s: 849077 executions, 526817 successful
    rsg_test.go:832: 4m25s of 5m0s: 865506 executions, 537018 successful
    rsg_test.go:832: 4m30s of 5m0s: 882249 executions, 547353 successful
    rsg_test.go:832: 4m35s of 5m0s: 899506 executions, 558164 successful
    rsg_test.go:832: 4m40s of 5m0s: 914070 executions, 567173 successful
    rsg_test.go:832: 4m45s of 5m0s: 931630 executions, 578053 successful
    rsg_test.go:832: 4m50s of 5m0s: 948722 executions, 588666 successful
```
</p>
</details>
<details><summary>Help</summary>
<p>

See also: [How To Investigate a Go Test Failure \(internal\)](https://cockroachlabs.atlassian.net/l/c/HgfXfJgM)
</p>
</details>
<details><summary>Same failure on other branches</summary>
<p>

- #107928 sql/tests: TestRandomSyntaxFunctions failed [C-test-failure O-robot T-sql-foundations branch-release-23.1]
- #95619 sql/tests: TestRandomSyntaxFunctions failed [C-test-failure O-robot T-sql-foundations branch-release-22.2]
</p>
</details>
/cc @cockroachdb/sql-foundations
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*TestRandomSyntaxFunctions.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)
</sub>

Jira issue: CRDB-30260

### PR DESCRIPTION
**Pull request by fqazi**
Previously, we could easily timeout running slower,
functions in the random syntax functions test. We
attempted to minimize this risk with resettable timeouts
which helped, but libpq has limited support for cancellation,
so we need to fully pull these out. To address this,
this patch will remove:
crdb_internal.revalidate_unique_constraints_in_all_tables
and crdb_internal.validate_ttl_scheduled_jobs from testing.

Fixes: #107929
Release note: None

### CODE REVIEW

File: pkg/sql/tests/rsg_test.go [hunk 1]
```diff
@@ -200,6 +200,14 @@ func (db *verifyFormatDB) execWithResettableTimeout(
 					return &nonCrasher{sql: sql, err: err}
 				}
 				return nil
+			case <-ctx.Done():
+				// Sanity: When our context gets cancelled and the test is
```
Comment (chrisseto) [inline pkg/sql/tests/rsg_test.go:204]: Are context cancellation and test timeout correlated? The current phrasing feels a bit ambiguous. Maybe something like "ctx is cancelled when the test is about to timeout. Log out whatever statement we're waiting on for debugging purposes. Sometimes queries won't respect cancellation due to lib/pq being weird". 

In the case that we do log out a query, are we trying to "save" the test from timing out or just leaving some breadcrumbs?

**Review by chrisseto — APPROVED** [review]
LGTM! Just some semantic questions.

File: pkg/sql/tests/rsg_test.go (hunk 1 above)
Comment (fqazi) [reply pkg/sql/tests/rsg_test.go:204]: Updated the comment				
                                 // Sanity: The context is cancelled when the test is about to
				// timeout. We will log whatever statement we're waiting on for
				// debugging purposes. Sometimes queries won't respect
				// cancellation due to lib/pq limitations.

Yes,, the goal here is to get some bread crumbs out; otherwise, we have to look at server stacks to figure out what is executing. This gives us a better understanding modulo some noise in the successful cases.

**Comment by fqazi** [comment]
@chrisseto TFTR! 

bors r+
