### PR TITLE
multiregion: fix flake in TestRegionLivenessProber

### LINKED ISSUE #114245: multiregionccl: flake in TestRegionLivenessProber
Seen [here](https://teamcity.cockroachdb.com/viewLog.html?buildId=12614413&buildTypeId=Cockroach_BazelEssentialCi) on an unrelated PR:
```
regionliveness_test.go:149: condition failed to evaluate within 45s: from regionliveness_test.go:156: dead region was not removed in time.
```

Jira issue: CRDB-33417

### PR DESCRIPTION
**Pull request by fqazi**
Previously, the TestRegionLivenessProber had too narrow of a timing window to detect region failure since the default timeout to declare a region dead was around ~40 seconds. As a result, SucceedsSoon could timeout before the failure was fully detected, leading to intermittent failures. This patch addresses this by extending the timeout for detecting the region failure.

Fixes: #114245

Release note: None

### CODE REVIEW

File: pkg/ccl/multiregionccl/regionliveness_test.go [hunk 1]
```diff
@@ -41,7 +41,7 @@ func TestRegionLivenessProber(t *testing.T) {
 	defer leaktest.AfterTest(t)()
 	defer log.Scope(t).Close(t)
 	skip.UnderStressRace(t)
-	skip.UnderStress(t)
+	//skip.UnderStress(t)
```
Comment (rafiss) [inline pkg/ccl/multiregionccl/regionliveness_test.go:44]: nit: uncomment this or delete the line.

File: pkg/ccl/multiregionccl/regionliveness_test.go [hunk 2]
```diff
@@ -168,5 +168,5 @@ func TestRegionLivenessProber(t *testing.T) {
 			}
 			return nil
 		})
-	})
+	}, time.Minute*2)
```
Comment (rafiss) [inline pkg/ccl/multiregionccl/regionliveness_test.go:171]: instead of making the test take longer, is there a way to make the timeout shorter? is that bad for other reasons?

**Review by rafiss — CHANGES_REQUESTED** [review]

**Review by fqazi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/114346)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rafiss)

___
*[`pkg/ccl/multiregionccl/regionliveness_test.go` line 171 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/114346#gh-1391580409:-Nj9Ldur0ZzplzTcPfka:bfvxa3b) ([raw file](https://github.com/cockroachdb/cockroach/blob/5ebd8ed08467f2531037de484efc189e5c19fa1f/pkg/ccl/multiregionccl/regionliveness_test.go#L171)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

instead of making the test take longer, is there a way to make the timeout shorter? is that bad for other reasons?
</blockquote></details>

Good point, reduced the TTL instead

**Review by rafiss — APPROVED** [review]
lgtm!

**Comment by fqazi** [comment]
@rafiss TFTR!

bors r+
