### PR TITLE
kv/bulk: check gc threshold in TestDuplicateHandling

### LINKED ISSUE #126929: kv/bulk: TestDuplicateHandling failed
kv/bulk.TestDuplicateHandling [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_StressBazel/16008841?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_StressBazel/16008841?buildTab=artifacts#/) on release-23.2.7-rc @ [8a4e55e40110d752c158414bfce22846faeb1722](https://github.com/cockroachdb/cockroach/commits/8a4e55e40110d752c158414bfce22846faeb1722):

```
=== RUN   TestDuplicateHandling
    test_log_scope.go:170: test logs captured to: /artifacts/tmp/_tmp/9cd32714a61c51d9ec44283a098261bc/logTestDuplicateHandling2115183443
    test_log_scope.go:81: use -show-logs to present logs inline
    test_server_shim.go:146: cluster virtualization disabled in global scope due to issue: #76378 (expected label: C-bug)
    conditional_wrap.go:190: 
        pkg/kv/bulk_test/pkg/kv/bulk/sst_batcher_test.go:201: (TestDuplicateHandling.func10)
        	NOTICE: .ClusterSettings() called via implicit interface ApplicationLayerInterface;
        HINT: consider using .ApplicationLayer().ClusterSettings() instead.
    conditional_wrap.go:194: TIP: consider replacing the test server initialization from:
            ts, ... := serverutils.StartServer(t, ...)
            defer ts.Stopper().Stop(...)
        to:
            srv, ... := serverutils.StartServer(t, ...)
            defer srv.Stopper().Stop(...)
            ts := srv.ApplicationLayer()
        
        See also: https://go.crdb.dev/p/testserver-and-cluster-virtualization
    sst_batcher_test.go:92: 
        	Error Trace:	github.com/cockroachdb/cockroach/pkg/kv/bulk_test/pkg/kv/bulk/sst_batcher_test.go:92
        	            				github.com/cockroachdb/cockroach/pkg/kv/bulk_test/pkg/kv/bulk/sst_batcher_test.go:211
        	Error:      	Not equal: 
        	            	expected: 20
        	            	actual  : 10
        	Test:       	TestDuplicateHandling
    panic.go:523: -- test log scope end --
test logs left over in: /artifacts/tmp/_tmp/9cd32714a61c51d9ec44283a098261bc/logTestDuplicateHandling2115183443
--- FAIL: TestDuplicateHandling (6.25s)
=== RUN   TestDuplicateHandling/ingestAll_does_not_error_on_key_matches_at_different_timestamps
    testing.go:1490: test executed panic(nil) or runtime.Goexit: subtest may have called FailNow on a parent test
    --- FAIL: TestDuplicateHandling/ingestAll_does_not_error_on_key_matches_at_different_timestamps (0.03s)
```

Parameters:
 - <code>TAGS=bazel,gss,deadlock</code>
 - <code>stress=true</code>
<details><summary>Help</summary>
<p>

See also: [How To Investigate a Go Test Failure \(internal\)](https://cockroachlabs.atlassian.net/l/c/HgfXfJgM)
</p>
</details>
/cc @cockroachdb/disaster-recovery
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*TestDuplicateHandling.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)
</sub>

Jira issue: CRDB-40190

### PR DESCRIPTION
**Pull request by msbutler**
TestDuplicateHandling failed recently because an unexpected number of keys were read. This _may_ have been caused by the gc threshold advancing past old revisions of certain test keys. This patch ensures the test will fail on a gc error instead. If the test fails again due to an unexpected number keys read, the gc story does not explain how this incorrect read could occur.

Fixes #126929

Epic: none

### CODE REVIEW

File: pkg/kv/bulk/sst_batcher_test.go [hunk 1]
```diff
@@ -92,23 +96,23 @@ func TestDuplicateHandling(t *testing.T) {
...
+		expectedCount   int
+		exportStartTime hlc.Timestamp
 	}
 	testCases := []testCase{
 		{
 			name:      "ingestAll does not add key-timestamp-value matches to SST",
 			ingestAll: true,
+			// Set the export startTime to ensure all revisions are read, or fail if
+			// the gc threshold has advance past the start time
+			exportStartTime: hlc.Timestamp{WallTime: int64(tsStart)},
```
Comment (stevendanna) [inline pkg/kv/bulk/sst_batcher_test.go:115]: I think you want to add this to the next test case.

**Comment by msbutler** [comment]
unrelated unit test

**Review by stevendanna — APPROVED** [review]

**Comment by msbutler** [comment]
TFTR!

bors r=stevendanna
