### PR TITLE
sql: check view owner privileges when selecting from a view

### LINKED ISSUE #164426: sql: selecting from a view after revoking the privileges of the view owner does not return an error
**Describe the problem**

When selecting from a view, all privilege checks on the underlying tables are skipped. (Note: there also is a privilege check that the user has SELECT on the _view_ itself, which is working as intended, so this isn't a complete lack of access control.) This includes the privilege checks for the view owner too. As a result, selecting from a view after revoking its owner's privileges will not return an error:

**To Reproduce**
```
statement ok
CREATE DATABASE testdb;

statement ok
USE testdb;

statement ok
CREATE ROLE view_owner;

statement ok
GRANT ALL ON DATABASE testdb TO view_owner;

statement ok
CREATE TABLE base_t (
  id INT PRIMARY KEY,
  username TEXT,
  data TEXT
);

statement ok
INSERT INTO base_t VALUES
  (1, 'table_owner', 'owner-data'),
  (2, 'view_owner', 'vowner-data'),
  (3, 'other', 'other-data');

statement ok
GRANT SELECT ON base_t TO view_owner;

statement ok
SET ROLE view_owner;

statement ok
CREATE VIEW vo_sd_view WITH (security_invoker = false) AS
  SELECT id, username, data FROM base_t;

query ITT rowsort
SELECT * FROM vo_sd_view;
----
1  table_owner   owner-data
2  view_owner    vowner-data
3  other         other-data

statement ok
SET ROLE root;

statement ok
REVOKE SELECT ON base_t FROM view_owner;

statement ok
SET ROLE view_owner;

# statement error pgcode 42501 user view_owner does not have SELECT privilege on relation base_t
statement ok
SELECT * FROM vo_sd_view;
1  table_owner   owner-data
2  view_owner    vowner-data
3  other         other-data
```

**Expected behavior**
The last select should return an error because the view owner does not have SELECT privileges on the underlying table anymore.

Jira issue: CRDB-60797

Epic CRDB-58695

### PR DESCRIPTION
**Pull request by shghasemi**
Previously, all privilege checks on underlying tables were skipped when
reading from a view. This was intended to avoid checking the invoker's
privileges, but it also meant that even the view owner's privileges were
not validated. This caused a security bug: selecting from a view would
succeed even after the view owner's SELECT privilege on the underlying
table was revoked.
    
Now, for user-created views, the view owner's (definer's) SELECT
privilege on the underlying tables is checked. This also means the
view owner's row-level security (RLS) policies are enforced rather than
 the invoker's. System views continue to skip privilege checks since they
are system-defined and always valid.
    
A new cluster setting `sql.auth.skip_all_view_privilege_checks.enabled`
(default: false) is added to revert to the previous behavior if needed.
    
Fixes: #164426
    
Release note (security update): View owner's privileges are now enforced
when reading from a view. Selecting from a view will fail if the view
owner's SELECT privilege on the underlying tables has been revoked.
    
Release note (backward-incompatible change): When selecting from a view,
the view owner's privileges on the underlying tables are now checked.
Previously, no privilege checks were performed on the underlying tables,
so a view would continue to work even after the owner lost access to the
underlying tables. This also affects row-level security (RLS): the view
owner's RLS policies are now enforced instead of the invoker's. If this
causes issues, the previous behavior can be restored by setting the
cluster setting `sql.auth.skip_all_view_privilege_checks.enabled` to
true.

### CODE REVIEW

**Review by rafiss — CHANGES_REQUESTED** [review]
this looks good so far! just had minor comments. the Queries team should probably take a look too, since this code is in the optimizer.

could you add a logictest subtest in the `views` file. for example:
```
# Regression test for #164426. When selecting from a view, verify that the view
# owner still has SELECT privilege on the underlying tables.
subtest view_owner_privilege_check

statement ok
USE test

statement ok
CREATE TABLE t_vop (a INT PRIMARY KEY, b INT);
INSERT INTO t_vop VALUES (1, 10), (2, 20);

statement ok
CREATE USER view_owner;
GRANT ALL ON TABLE t_vop TO view_owner;
GRANT CREATE ON SCHEMA public TO view_owner;

# Create a view as view_owner (root can SET ROLE to any role).
statement ok
SET ROLE view_owner

statement ok
CREATE VIEW v_vop AS SELECT a, b FROM t_vop

statement ok
SET ROLE root

# Grant SELECT on the view to testuser so they can query through it.
statement ok
GRANT SELECT ON v_vop TO testuser

# Verify the view works initially.
user testuser

query II
SELECT * FROM v_vop ORDER BY a
----
1  10
2  20

user root

# Revoke view owner's SELECT on the underlying table.
statement ok
REVOKE SELECT ON t_vop FROM view_owner

# Now querying through the view should fail because the view owner no longer
# has SELECT on the underlying table.
user testuser

statement error pgcode 42501 user view_owner does not have SELECT privilege on relation t_vop
SELECT * FROM v_vop

user root

# Re-grant SELECT to the view owner. The view should work again.
statement ok
GRANT SELECT ON t_vop TO view_owner

user testuser

query II
SELECT * FROM v_vop ORDER BY a
----
1  10
2  20

user root

# Test nested views: each level checks its own owner's privileges.
statement ok
CREATE USER view_owner2;
GRANT SELECT ON t_vop TO view_owner;
GRANT SELECT ON v_vop TO view_owner2;
GRANT CREATE ON SCHEMA public TO view_owner2;

statement ok
SET ROLE view_owner2

statement ok
CREATE VIEW v_vop_nested AS SELECT a FROM v_vop

statement ok
SET ROLE root

statement ok
GRANT SELECT ON v_vop_nested TO testuser

# Both owners have SELECT, so nested view works.
user testuser

query I
SELECT * FROM v_vop_nested ORDER BY a
----
1
2

user root

# Revoke the inner view owner's SELECT on the underlying table. The nested
# view should fail because the inner view's owner lost access.
statement ok
REVOKE SELECT ON t_vop FROM view_owner

user testuser

statement error pgcode 42501 user view_owner does not have SELECT privilege on relation t_vop
SELECT * FROM v_vop_nested
``
```


> @rafiss made 9 comments.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/164664#-:-OmjsMWnDn9hZ0RbFN0j:b-9omv1i)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on shghasemi).

___
*[`pkg/sql/opt/metadata.go` line 49 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/164664#-Omjtrq47sKtNmNLhQdo:-Omjtrq47sKtNmNLhQdp:b9odrm6) ([raw file](https://github.com/cockroachdb/cockroach/blob/ab0674a9882ab75a97a13f414bd049013201c286/pkg/sql/opt/metadata.go#L49)):*
> ```Go
> // re-check the correct user's privilege (e.g., the view owner for tables
> // accessed through a view) rather than always checking the session user.
> type PrivilegeKey struct {
> ```

nit: could this be lowercase if it's not used anywhere else?
___
*[`pkg/sql/opt/metadata.go` line 672 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/164664#-Omjuonu2S9Zc7_fOODk:-Omjuonu2S9Zc7_fOODl:b-ibg1kz) ([raw file](https://github.com/cockroachdb/cockroach/blob/ab0674a9882ab75a97a13f414bd049013201c286/pkg/sql/opt/metadata.go#L672)):*
> ```Go
> 			dataSource, ok := md.dataSourceDeps[key.ID]
> 			if !ok {
> 				// No need to check privileges because ID is not in dataSourceDeps
> ```

would an assertion error make more sense here rather than silently ignoring? i don't think this should ever happen.
___
*[`pkg/sql/opt/memo/memo.go` line 232 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/164664#-OmjubU6DWX5KaT00qVm:-OmjubU6DWX5KaT00qVn:b-kpzr0t) ([raw file](https://github.com/cockroachdb/cockroach/blob/af8b05213144285be31e2c8bf98a4307ca835b1e/pkg/sql/opt/memo/memo.go#L232)):*
> ```Go
> 
> 	// currentUser is the user under which the plan was created. SET ROLE can
> 	// change the current user, which affects privilege checks, so the memo must
> ```

do we also need to track changes to the `SkipUnderlyingViewPrivilegeChecks` cluster setting to correctly track memo staleness?
___
*[`pkg/sql/opt/optbuilder/select.go` line 366 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/164664#-Omjrv8zEgHTcSM7JFUg:-Omjrv8zEgHTcSM7JFUh:bqrmv1m) ([raw file](https://github.com/cockroachdb/cockroach/blob/7d1880e8312a8a9f0e78d756e25295ec723659ea/pkg/sql/opt/optbuilder/select.go#L366)):*
> ```Go
> 	//
> 	// The SkipAllViewPrivilegeChecks cluster setting can be used to revert to
> 	// the pre-v25.2 behavior where no privilege checks were performed on the
> ```

nit: "pre-26.2 behavior"
___
*[`pkg/sql/opt/optbuilder/select.go` line 368 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/164664#-Omjs-gm6KMwE0BA0itX:-Omjs-gm6KMwE0BA0itY:bzie3pu) ([raw file](https://github.com/cockroachdb/cockroach/blob/7d1880e8312a8a9f0e78d756e25295ec723659ea/pkg/sql/opt/optbuilder/select.go#L368)):*
> ```Go
> 	// the pre-v25.2 behavior where no privilege checks were performed on the
> 	// underlying tables.
> 	if skipAllPrivilegeChecks || view.IsSystemView() {
> ```

could we also add one more condition here so that we keep using the old behavior if `version.IsActive(v26_2)` returns false?
___
*[`pkg/sql/opt/optbuilder/select.go` line 373 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/164664#-Omjv5j_AGmnGVcCv0OE:-Omjv5j_AGmnGVcCv0OF:b-vl1sh9) ([raw file](https://github.com/cockroachdb/cockroach/blob/7d1880e8312a8a9f0e78d756e25295ec723659ea/pkg/sql/opt/optbuilder/select.go#L373)):*
> ```Go
> 			defer func() { b.skipSelectPrivilegeChecks = false }()
> 		}
> 	} else {
> ```

does this handle nested views correctly?

If a system view references a user-created view, `skipSelectPrivilegeChecks` is true (from the system view) and the user-view branch doesn't clear it. The user view's owner's privileges on underlying tables are then skipped. The else branch should consider explicitly setting `b.skipSelectPrivilegeChecks = false` and restoring it on defer.

this situation doesn't feel that realistic, so this may not be that important. but if it's easy to handle, we may as well do it.
___
*[`pkg/sql/opt/optbuilder/select.go` line 377 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/164664#-OmjsnTwAb8LdEg3mM9V:-OmjsnTwAb8LdEg3mM9W:bblz5wu) ([raw file](https://github.com/cockroachdb/cockroach/blob/7d1880e8312a8a9f0e78d756e25295ec723659ea/pkg/sql/opt/optbuilder/select.go#L377)):*
> ```Go
> 		b.checkPrivilegeUser = view.Owner()
> 		defer func() { b.checkPrivilegeUser = prevPrivilegeUser }()
> 		defer b.DisableUnsafeInternalCheck()()
> ```

based on the comment above, i thought this DisableUnsafeInternalCheck change would be in the first `if` branch. why is it here?
___
*[`pkg/sql/sqlclustersettings/clustersettings.go` line 176 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/164664#-OmjqCbx1uD50Le3l2BD:-OmjqCbx1uD50Le3l2BE:b-tsu0bq) ([raw file](https://github.com/cockroachdb/cockroach/blob/7d1880e8312a8a9f0e78d756e25295ec723659ea/pkg/sql/sqlclustersettings/clustersettings.go#L176)):*
> ```Go
> var SkipAllViewPrivilegeChecks = settings.RegisterBoolSetting(
> 	settings.ApplicationLevel,
> 	"sql.auth.skip_all_view_privilege_checks.enabled",
> ```

nit: i think "all" could give people the wrong idea. can we name it `sql.auth.skip_underlying_view_privilege_checks.enabled`

this setting should also have tests of its own

**Review by rafiss — COMMENTED** [review]
> @rafiss made 1 comment.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/164664)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on shghasemi).

___
*[`pkg/sql/opt/optbuilder/util.go` line 713 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/164664#-OmjvZGd5en6H9wZnqoQ:-OmjvZGd5en6H9wZnqoR:b-ngxrc2) ([raw file](https://github.com/cockroachdb/cockroach/blob/ab0674a9882ab75a97a13f414bd049013201c286/pkg/sql/opt/optbuilder/util.go#L713)):*
> ```Go
> }
> 
> // checkPrivilege ensures that the current user has at least one of the given
> ```

nit: the comment that says "current user" might need updating

**Review by eric-alton — COMMENTED** [review]
> @eric-alton reviewed 4 files and all commit messages, and made 4 comments.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/164664)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on rafiss, shghasemi, spilchen, and yuzefovich).

___
*[`pkg/sql/opt/optbuilder/select.go` line 373 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/164664#-Omjv5j_AGmnGVcCv0OE:-Omo7tVV5kBLr_5flmaU:b-6c12iv) ([raw file](https://github.com/cockroachdb/cockroach/blob/7d1880e8312a8a9f0e78d756e25295ec723659ea/pkg/sql/opt/optbuilder/select.go#L373)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

does this handle nested views correctly?

If a system view references a user-created view, `skipSelectPrivilegeChecks` is true (from the system view) and the user-view branch doesn't clear it. The user view's owner's privileges on underlying tables are then skipped. The else branch should consider explicitly setting `b.skipSelectPrivilegeChecks = false` and restoring it on defer.

this situation doesn't feel that realistic, so this may not be that important. but if it's easy to handle, we may as well do it.
</blockquote></details>

Nested views are an important test case, though not just the combination you referenced should be included. We should also test things like:

- definer view with same definer view referenced within it
- definer view with different definer view referenced within it
- definer view with invoker view referenced within it
- ... and so on, all combinations of definer + invoker, same authorization ID + different auth ID
___
*[`pkg/sql/sqlclustersettings/clustersettings.go` line 176 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/164664#-OmjqCbx1uD50Le3l2BD:-Omo94I61gLPiaLbjc8U:bt0mcyf) ([raw file](https://github.com/cockroachdb/cockroach/blob/7d1880e8312a8a9f0e78d756e25295ec723659ea/pkg/sql/sqlclustersettings/clustersettings.go#L176)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

nit: i think "all" could give people the wrong idea. can we name it `sql.auth.skip_underlying_view_privilege_checks.enabled`

this setting should also have tests of its own
</blockquote></details>

I understand we are trying to provide a safety net because we are changing existing behaviour, but I would still prefer to have this variable be internal-only.

What privileges does a user need to have to toggle this variable?
___
*[`-- commits` line 13 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/164664#-Omo4fuR782H1FhuYAc0:-Omo4fuR782H1FhuYAc1:b-bumkg0):*
I may get my answer when reviewing the code, but I wouldn't expect this to happen automatically. Privilege checking and application of row-level security policies should be independent operations. I might be reading too much into the statement "This also means", which suggests because you changed the privilege checking logic the row-level security logic was impacted.
___
*[`pkg/sql/opt/optbuilder/select.go` line 362 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/164664#-Omo7V2W4-F89rfUKGvK:-Omo7V2W4-F89rfUKGvL:bhjn342) ([raw file](https://github.com/cockroachdb/cockroach/blob/193f40b76f582d48a10f27adaafd06f6d2c2dae3/pkg/sql/opt/optbuilder/select.go#L362)):*
> ```Go
> 	// rather than the invoker's.
> 	//
> 	// For system views (e.g. pg_catalog.pg_description,
> ```

Is the key distinction whether it is a system view, or is it whether it is a definer view created by a role that has admin level data access?

**Review by eric-alton — COMMENTED** [review]
Please also add some error scenarios which demonstrate privilege checking at view creation time. These scenarios hopefully already exist, but it wouldn't hurt to have a few basic examples included with this change, especially demonstrating that the new variable to skip invocation-time checks does not also skip creation-time checking.

> @eric-alton made 1 comment.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/164664#-:-Omo9ZNE58BWvh-qIWgA:b-8vntx1)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on rafiss, shghasemi, spilchen, and yuzefovich).

**Review by shghasemi — COMMENTED** [review]
> @shghasemi made 4 comments and resolved 1 discussion.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/164664)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on eric-alton, rafiss, spilchen, and yuzefovich).

___
*[`pkg/sql/opt/memo/memo.go` line 232 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/164664#-OmjubU6DWX5KaT00qVm:-Omo2qhr7sx-p2-0CGyh:b-hearfn) ([raw file](https://github.com/cockroachdb/cockroach/blob/af8b05213144285be31e2c8bf98a4307ca835b1e/pkg/sql/opt/memo/memo.go#L232)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

do we also need to track changes to the `SkipUnderlyingViewPrivilegeChecks` cluster setting to correctly track memo staleness?
</blockquote></details>

Good catch. Yes, we do.
___
*[`pkg/sql/opt/optbuilder/select.go` line 377 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/164664#-OmjsnTwAb8LdEg3mM9V:-Omo3BbU-WOUutOdobqE:b-eqhka0) ([raw file](https://github.com/cockroachdb/cockroach/blob/7d1880e8312a8a9f0e78d756e25295ec723659ea/pkg/sql/opt/optbuilder/select.go#L377)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

based on the comment above, i thought this DisableUnsafeInternalCheck change would be in the first `if` branch. why is it here?
</blockquote></details>

The comment was incorrect. We need `DisableUnsafeInternalCheck` to allow reading from a system table from a user defined view. 
Example: `dev testlogic --files='inflight_trace_spans' --config=local`
___
*[`pkg/sql/opt/optbuilder/util.go` line 713 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/164664#-OmjvZGd5en6H9wZnqoQ:-Omo6EzqBGPuIA9TV8dB:bb7f2mf) ([raw file](https://github.com/cockroachdb/cockroach/blob/ab0674a9882ab75a97a13f414bd049013201c286/pkg/sql/opt/optbuilder/util.go#L713)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

nit: the comment that says "current user" might need updating
</blockquote></details>

done
___
*[`pkg/sql/sqlclustersettings/clustersettings.go` line 176 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/164664#-OmjqCbx1uD50Le3l2BD:-OmoFaSe7trHnJqUHZdt:bo1tbk7) ([raw file](https://github.com/cockroachdb/cockroach/blob/7d1880e8312a8a9f0e78d756e25295ec723659ea/pkg/sql/sqlclustersettings/clustersettings.go#L176)):*
<details><summary><i>Previously, eric-alton (Eric Alton) wrote…</i></summary><blockquote>

I understand we are trying to provide a safety net because we are changing existing behaviour, but I would still prefer to have this variable be internal-only.

What privileges does a user need to have to toggle this variable?
</blockquote></details>

Users with MODIFYCLUSTERSETTING access or admins.

From my understanding, it's possible that some of our customers are relying on this bug (e.g., they have a view without having access to the underlying table). If we don't document this setting, the customers will need to reach out to us to learn how they can fall back to the old behavior while they work to fix the access.

**Review by shghasemi — COMMENTED** [review]
Added.

> @shghasemi made 6 comments and resolved 2 discussions.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/164664#-:-OmotlZn0gxeiDQ5G7-X:bqmjwcz)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on eric-alton, rafiss, spilchen, and yuzefovich).

___
*[`-- commits` line 13 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/164664#-Omo4fuR782H1FhuYAc0:-OmoNuH-AUcaAbv-rlZ8:b-wisnfw):*
<details><summary><i>Previously, eric-alton (Eric Alton) wrote…</i></summary><blockquote>

I may get my answer when reviewing the code, but I wouldn't expect this to happen automatically. Privilege checking and application of row-level security policies should be independent operations. I might be reading too much into the statement "This also means", which suggests because you changed the privilege checking logic the row-level security logic was impacted.
</blockquote></details>

It affects the RLS too because both RLS and privileges are evaluated using `checkPrivilegeUser`. Before, we didn't set `checkPrivilegeUser = view.Owner()`, so it was set to the invoker. We skipped all privilege checks so we didn't check the invoker privileges on the table.

Now that we set `checkPrivilegeUser` for definer views, it will use definer RLS. I added a test for this in `row_level_security` logic test.
___
*[`pkg/sql/opt/metadata.go` line 672 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/164664#-Omjuonu2S9Zc7_fOODk:-OmoOU3M3NKK8YuwYU3S:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/ab0674a9882ab75a97a13f414bd049013201c286/pkg/sql/opt/metadata.go#L672)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

would an assertion error make more sense here rather than silently ignoring? i don't think this should ever happen.
</blockquote></details>

Done.
___
*[`pkg/sql/opt/optbuilder/select.go` line 368 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/164664#-Omjs-gm6KMwE0BA0itX:-OmoOawM9bmX-4oUUB6u:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/7d1880e8312a8a9f0e78d756e25295ec723659ea/pkg/sql/opt/optbuilder/select.go#L368)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

could we also add one more condition here so that we keep using the old behavior if `version.IsActive(v26_2)` returns false?
</blockquote></details>

Done.
___
*[`pkg/sql/opt/optbuilder/select.go` line 373 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/164664#-Omjv5j_AGmnGVcCv0OE:-OmoRsyJ3dOPctcJtDZN:bsyfa8y) ([raw file](https://github.com/cockroachdb/cockroach/blob/7d1880e8312a8a9f0e78d756e25295ec723659ea/pkg/sql/opt/optbuilder/select.go#L373)):*
<details><summary><i>Previously, eric-alton (Eric Alton) wrote…</i></summary><blockquote>

Nested views are an important test case, though not just the combination you referenced should be included. We should also test things like:

- definer view with same definer view referenced within it
- definer view with different definer view referenced within it
- definer view with invoker view referenced within it
- ... and so on, all combinations of definer + invoker, same authorization ID + different auth ID
</blockquote></details>

We don't have invoker views in this PR. I added an extra test for nested views in `views` logic test to include cases like "definer view with same definer view referenced within it".
___
*[`pkg/sql/opt/optbuilder/select.go` line 362 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/164664#-Omo7V2W4-F89rfUKGvK:-OmoQcNqCgRfLHIFWs12:bh6q3ib) ([raw file](https://github.com/cockroachdb/cockroach/blob/193f40b76f582d48a10f27adaafd06f6d2c2dae3/pkg/sql/opt/optbuilder/select.go#L362)):*
<details><summary><i>Previously, eric-alton (Eric Alton) wrote…</i></summary><blockquote>

Is the key distinction whether it is a system view, or is it whether it is a definer view created by a role that has admin level data access?
</blockquote></details>

Only the system views.

`crdb_internal` is a schema for internal virtual tables and views. For example `crdb_internal.transaction_statistics` is a virtual view. `pg_catalog` views are another example.  We need to skip privilege checks here to preserve the same access to these views as before.

**Review by yuzefovich — COMMENTED** [review]
Nice work! I only have some nits, and the changes look good to me.

> @yuzefovich reviewed 22 files and all commit messages, and made 5 comments.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/164664#-:-OmpqlgABhcOK1c2Pmaf:b-gqa2jr)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on eric-alton, rafiss, shghasemi, and spilchen).

___
*[`pkg/sql/logictest/testdata/logic_test/udf` line 1148 at r14](https://reviewable.io/reviews/cockroachdb/cockroach/164664#-OmppQAkEkg6aA4yrgI3:-OmppQAkEkg6aA4yrgI4:bniwa27) ([raw file](https://github.com/cockroachdb/cockroach/blob/c7810532806ebffdf1691d59f4a71aef278cd7f7/pkg/sql/logictest/testdata/logic_test/udf#L1148)):*
> ```
> # Note: Postgres fails with a different error message: "user bob does not have EXECUTE privilege on function f_scalar".
> # This is because psql will first validate access to f_scalar, but crdb first validates access to xy.
> skipif config local-mixed-25.4
> ```

nit: these two `skipif`s could be combined into one.
___
*[`pkg/sql/logictest/testdata/logic_test/views` line 2089 at r14](https://reviewable.io/reviews/cockroachdb/cockroach/164664#-Ompq1Pf67k0Hou3dTrb:-Ompq1Pf67k0Hou3dTrc:bkyi8hr) ([raw file](https://github.com/cockroachdb/cockroach/blob/c7810532806ebffdf1691d59f4a71aef278cd7f7/pkg/sql/logictest/testdata/logic_test/views#L2089)):*
> ```
> user root
> 
> # Enable skip_underlying_view_privilege_checks. testuser cannot SELECT from the view.
> ```

nit: `s/Enable/Disable/`.
___
*[`pkg/sql/logictest/testdata/logic_test/views` line 1957 at r15](https://reviewable.io/reviews/cockroachdb/cockroach/164664#-OmpqN-W1WhhJ-jzzL2k:-OmpqN-W1WhhJ-jzzL2l:b1caovt) ([raw file](https://github.com/cockroachdb/cockroach/blob/f7d54bf4a336cbf3f9c9cdae6158db256d3cc1af/pkg/sql/logictest/testdata/logic_test/views#L1957)):*
> ```
> # Regression test for #164426. When selecting from a view, verify that the view
> # owner still has SELECT privilege on the underlying tables.
> subtest view_owner_privilege_check
> ```

nit: rather than extending already-large `views` file, consider creating a fresh one for the new tests. This will result in separate generated `TestLogic...` function which can allow for better parallelism in CI.
___
*[`pkg/sql/logictest/testdata/logic_test/views` line 2073 at r15](https://reviewable.io/reviews/cockroachdb/cockroach/164664#-OmpqcEL03mQ5wtBZnZd:-OmpqcEL03mQ5wtBZnZe:b-8rikuc) ([raw file](https://github.com/cockroachdb/cockroach/blob/f7d54bf4a336cbf3f9c9cdae6158db256d3cc1af/pkg/sql/logictest/testdata/logic_test/views#L2073)):*
> ```
> user root
> 
> # Revoke the outter view owner's SELECT on the underlying table. The nested
> ```

nit: `s/outter/outer/`.

**Review by rafiss — APPROVED** [review]
the logic of the changes and the tests lgtm!

i'm less familiar with the optimizer code, but glad we have SQL Queries engineers reviewing too.

> @rafiss made 2 comments and resolved 3 discussions.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/164664#-:-OmuThj5Bpxt2UW-E5JG:blv0ev2)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on eric-alton, shghasemi, spilchen, and yuzefovich).

___
*[`pkg/sql/logictest/testdata/logic_test/views_definer_privileges` line 1 at r20](https://reviewable.io/reviews/cockroachdb/cockroach/164664#-OmuTTZN59PmqkC0rROL:-OmuTTZN59PmqkC0rROM:b-v33284) ([raw file](https://github.com/cockroachdb/cockroach/blob/3ba11aab40ac3a9397539dbc160078d0a58e4ce6/pkg/sql/logictest/testdata/logic_test/views_definer_privileges#L1)):*
> ```
> # LogicTest: !local-legacy-schema-changer
> ```

out of curiosity, why does this skip the legacy schema changer mode?

**Review by rafiss — COMMENTED** [review]
> @rafiss made 1 comment.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/164664)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on eric-alton, shghasemi, spilchen, and yuzefovich).

___
*[`pkg/sql/opt/metadata.go` line 673 at r20](https://reviewable.io/reviews/cockroachdb/cockroach/164664#-OmuVUk1EmHmhdiNHjn1:-OmuVUk1EmHmhdiNHjn2:bxkdp62) ([raw file](https://github.com/cockroachdb/cockroach/blob/3ba11aab40ac3a9397539dbc160078d0a58e4ce6/pkg/sql/opt/metadata.go#L673)):*
> ```Go
> 			if !ok {
> 				// No need to check privileges because ID is not in dataSourceDeps
> 				return errors.AssertionFailedf("Data source dependeny with ID %d does not exist.", key.ID)
> ```

nit: "dependeny" -> "dependency"

File: pkg/sql/opt/optbuilder/select.go [hunk 1]
```diff
@@ -344,15 +346,43 @@ func (b *Builder) buildView(
...
-	// When building the view, we don't want to check for the SELECT privilege
-	// on the underlying tables, just on the view itself. Checking on the
-	// underlying tables as well would defeat the purpose of having separate
-	// SELECT privileges on the view, which is intended to allow for exposing
-	// some subset of a restricted table's data to less privileged users.
-	if !b.skipSelectPrivilegeChecks {
-		b.skipSelectPrivilegeChecks = true
-		defer func() { b.skipSelectPrivilegeChecks = false }()
+	skipAllPrivilegeChecks := sqlclustersettings.SkipUnderlyingViewPrivilegeChecks.Get(&b.evalCtx.Settings.SV)
+	isActive := b.evalCtx.Settings.Version.ActiveVersion(b.ctx).IsActive(clusterversion.V26_2)
```
Comment (DrewKimball) [inline pkg/sql/opt/optbuilder/select.go:351]: Maybe it's not that important, but do we actually need to check the cluster version here? It seems fine to do a version check even if other nodes aren't yet at 26.2. In fact, it might be nice to skip the version check so that a user that regresses can catch it before the upgrade is finalized.

File: pkg/sql/opt/memo/memo.go [hunk 2]
```diff
@@ -342,7 +355,9 @@ func (m *Memo) Init(ctx context.Context, evalCtx *eval.Context) {
 		useImprovedRoutineDepsTriggersComputedCols: evalCtx.SessionData().UseImprovedRoutineDepsTriggersAndComputedCols,
 		inlineAnyUnnestSubquery:                    evalCtx.SessionData().OptimizerInlineAnyUnnestSubquery,
 		useMinRowCountAntiJoinFix:                  evalCtx.SessionData().OptimizerUseMinRowCountAntiJoinFix,
+		skipUnderlyingViewPrivilegeChecks:          sqlclustersettings.SkipUnderlyingViewPrivilegeChecks.Get(&evalCtx.Settings.SV),
```
Comment (DrewKimball) [inline pkg/sql/opt/memo/memo.go:352]: Should we make this a session setting instead?

File: pkg/sql/opt/memo/memo.go [hunk 3]
```diff
@@ -227,6 +229,17 @@ type Memo struct {
 	// memo staleness calculation.
 	txnIsoLevel isolation.Level
 
+	// currentUser is the user under which the plan was created. SET ROLE can
+	// change the current user, which affects privilege checks, so the memo must
+	// be invalidated when the current user changes.
+	currentUser username.SQLUsername
```
Comment (DrewKimball) [inline pkg/sql/opt/memo/memo.go]: You can disregard this, but I wonder if we could simplify things by only tracking the user for privileges that should be executed for a specific user. We could leave the user empty in the privilege key for other privileges and just use `CurrentUser` for them as before. I think that would make this commit unnecessary.

**Review by DrewKimball — APPROVED** [review]
LGTM. The changes look correct to me - just some suggestions.

File: pkg/sql/opt/memo/memo.go (hunk 2 above)
Comment (shghasemi) [reply pkg/sql/opt/memo/memo.go:352]: I don't believe we need session granularity for this variable. This is  a migration/compatibility escape hatch for admins. Also, we don't want to allow all users to set it since this is a security flag.

File: pkg/sql/opt/memo/memo.go (hunk 3 above)
Comment (shghasemi) [reply pkg/sql/opt/memo/memo.go]: We'll need to add a new bool flag to the builder to track if the data source privilege check is by definer or invoker. Currently, we only have the `checkPrivilegeUser` to check, and we can't tell if it's the definer or the invoker. For example: the view owner queries an invoker view. `checkPrivilegeUser` and the `SessionUser` are the  view owner, but memo should indicate an invoker privilege check.

Is there a performance benefit to not invalidating memo when user changes?

File: pkg/sql/opt/optbuilder/select.go [hunk 4]
```diff
@@ -344,15 +346,43 @@ func (b *Builder) buildView(
...
 
-	// When building the view, we don't want to check for the SELECT privilege
-	// on the underlying tables, just on the view itself. Checking on the
-	// underlying tables as well would defeat the purpose of having separate
-	// SELECT privileges on the view, which is intended to allow for exposing
-	// some subset of a restricted table's data to less privileged users.
-	if !b.skipSelectPrivilegeChecks {
-		b.skipSelectPrivilegeChecks = true
-		defer func() { b.skipSelectPrivilegeChecks = false }()
+	skipAllPrivilegeChecks := sqlclustersettings.SkipUnderlyingViewPrivilegeChecks.Get(&b.evalCtx.Settings.SV)
```
Comment (rafiss) [inline pkg/sql/opt/optbuilder/select.go]: nit: we can rename this from `skipAllPrivilegeChecks` to `skipUnderlyingPrivilegeChecks`

File: pkg/sql/opt/optbuilder/select.go (hunk 1 above)
Comment (rafiss) [reply pkg/sql/opt/optbuilder/select.go:351]: hm i was thinking that if we keep this version gate, then it means that customers would be able to do a seamless migration without any queries hitting errors. they would be be able to flip the cluster setting to preserve the old behavior _before_ the version is finalized.

but that would require them to diligently read the release notes, which may not be likely. you may be right that it's more realistic for them to discover this issue just by doing the upgrade but waiting before finalization.

i don't see this as a blocker either way. i'm fine to go with whatever behavior the Queries team prefers.

**Review by shghasemi — COMMENTED** [review]
> @shghasemi made 1 comment.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/164664)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on DrewKimball, eric-alton, rafiss, spilchen, and yuzefovich).

___
*[`pkg/sql/logictest/testdata/logic_test/views_definer_privileges` line 1 at r20](https://reviewable.io/reviews/cockroachdb/cockroach/164664#-OmuTTZN59PmqkC0rROL:-Omyv4xF5ajJ_vi6lLGU:boo2kob) ([raw file](https://github.com/cockroachdb/cockroach/blob/3ba11aab40ac3a9397539dbc160078d0a58e4ce6/pkg/sql/logictest/testdata/logic_test/views_definer_privileges#L1)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

out of curiosity, why does this skip the legacy schema changer mode?
</blockquote></details>

Enabling RLS is not supported in the legacy schema changer.

**Review by shghasemi — COMMENTED** [review]
> @shghasemi resolved 3 discussions.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/164664)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on DrewKimball, eric-alton, rafiss, spilchen, and yuzefovich).

File: pkg/sql/opt/memo/memo.go (hunk 3 above)
Comment (rafiss) [reply pkg/sql/opt/memo/memo.go]: i'm actually surprised we weren't already tracking the user here. wouldn't other privilege checks already have been affected by this? i see that `func (md *Metadata) CheckDependencies` does have a check for the user, but is that not sufficient for some reason?

i'm curious if @DrewKimball or @yuzefovich think there may have been a pre-existing bug here, if the memo was not being considered stale after running `SET ROLE`?

Comment (shghasemi) [reply pkg/sql/opt/memo/memo.go]: `CheckDependencies` calls `checkDataSourcePrivileges` which used `optCatalog.GetCurrentUser()` to check the privileges. Therefore, when reusing the memo after user switch, we'd check the current user privileges.

However, with definer views, we had to track which user to be checked for the privilege. That's why my change made it necessary to invalidate memo after user switch.

The only thing I was skeptical about, was the invoker/definer functions. Looks like we'd rebuild the functions which ends up checking the correct users.

Comment (DrewKimball) [reply pkg/sql/opt/memo/memo.go]: > Is there a performance benefit to not invalidating memo when user changes?

Let's say I have two users concurrently executing the same query (on the same objects). In the current state, I think the plan could be cached and reused across executions. With this change, we'd end up invalidating the cache entry each time the query executes under a different user. It's hard to say if this metters in the real world or not. I'm OK with the checking the user if you think it simplifies the implementation vs trying to cache plans across user switches.

File: pkg/sql/opt/optbuilder/select.go (hunk 1 above)
Comment (DrewKimball) [reply pkg/sql/opt/optbuilder/select.go:351]: I'm fine with keeping the current behavior with that justification, I don't feel strongly about the suggestion.

**Review by DrewKimball — APPROVED** [review]

File: pkg/sql/opt/optbuilder/builder.go [hunk 5]
```diff
@@ -201,6 +201,15 @@ type Builder struct {
...
 	checkExecutePrivilegeUser username.SQLUsername
 
+	// isDefinerPrivileges indicates that privilege checks are being performed
+	// as a specific definer user (e.g., a view owner or SECURITY DEFINER
+	// routine owner) rather than the session user. When true, the definer's
+	// username is stored in the privilege dependency key so that
+	// re-validation checks the definer. When false, an empty username is
+	// stored and re-validation uses the current session user, which correctly
+	// handles SET ROLE without memo invalidation.
+	isDefinerPrivileges bool
```
Comment (DrewKimball) [inline pkg/sql/opt/optbuilder/builder.go]: Maybe there's room to make this handling a bit more clear. You can leave as a TODO for me, but what do you think about doing this:
* add a `currentUser` field
* rename `checkPrivilegeUser` to `dataSourcePrivilegeUserOverride`
* rename `checkExecutePrivilegeUser` to `executePrivilegeUserOverride`

Then for a data source, if `dataSourcePrivilegeUserOverride` is set, use that for the privilege check and pass it in to `AddDependency`. Otherwise, use `currentUser` and pass an empty user to `AddDependency`. Similar for resolving the execute privilege for routines.

**Review by DrewKimball — APPROVED** [review]
I have a suggestion to make the last commit a bit more clear that you can leave as a TODO if you want. LGTM

File: pkg/sql/opt/optbuilder/builder.go (hunk 5 above)
Comment (shghasemi) [reply pkg/sql/opt/optbuilder/builder.go]: I agree. We can turn checkPrivilegeUser into a function that returns dataSourcePrivilegeUserOverride if it's set and currentUser otherwise. 

I can make the change in this PR too, it shouldn't take long. I'm going to squash these commits right before merge.

File: pkg/sql/opt/optbuilder/builder.go [hunk 6]
```diff
@@ -186,29 +186,29 @@ type Builder struct {
...
+
+	// dataSourcePrivilegeUserOverride, when set, overrides currentUser for
+	// data source (e.g., table, view) privilege checks. It is set in two
+	// cases:
+	//   1. Views: set to the view owner so that SELECT privilege on the
+	//      view's underlying tables is checked as the definer.
+	//   2. SECURITY DEFINER routines: set to the routine owner so that all
+	//      data source access within the routine body uses the definer's
+	//      privileges.
+	dataSourcePrivilegeUserOverride username.SQLUsername
```
Comment (DrewKimball) [inline pkg/sql/opt/optbuilder/builder.go:201]: I'm curious, do user-defined-types also all under this umbrella?

**Review by DrewKimball — APPROVED** [review]
Thanks for making the change!

File: pkg/sql/opt/optbuilder/builder.go (hunk 6 above)
Comment (shghasemi) [reply pkg/sql/opt/optbuilder/builder.go:201]: From what I see in the code, we only check for USAGE privileges when creating a table/view/index that references the type.
https://github.com/cockroachdb/cockroach/blob/1a5c853b8d2eb9ca1626ebcbb042a92865eaa26d/pkg/sql/drop_type.go#L160-L187

There's no USAGE privilege check in the optimizer when reading from the table/view. We only check `canResolveDescUnderSchema` which checks the session's current user USAGE privilege on the schema.
https://github.com/cockroachdb/cockroach/blob/1a5c853b8d2eb9ca1626ebcbb042a92865eaa26d/pkg/sql/schema_resolver.go#L320
https://github.com/cockroachdb/cockroach/blob/1a5c853b8d2eb9ca1626ebcbb042a92865eaa26d/pkg/sql/schema_resolver.go#L394-L414
