### PR TITLE
util/json: fix infinite loop with unterminated \u

### LINKED ISSUE #93366: sql: JSON parser seems to infinite loop on certain inputs
Try running this query on CockroachDB:

```
SELECT e'"\\u"'::JSONB
```

On my machine this never completes and is uncancellable. I assume this is a bug in the new JSON parsing library but I haven't verified it.

Jira issue: CRDB-22286

### PR DESCRIPTION
**Pull request by jordanlewis**
Closes #93366

Previously, an unterminated \u code in a JSON string would cause the database to loop forever.

Release note: None

### CODE REVIEW

File: pkg/util/json/tokenizer/scanner.go [hunk 1]
```diff
@@ -251,7 +252,7 @@ func (s *Scanner) parseStringSlow(pos int) ([]byte, int) {
 			case -1:
 				return nil, pos // Error
 			case 0:
-				break
+				break loop
```
Comment (miretskiy) [inline pkg/util/json/tokenizer/scanner.go:255]: yikes.  Good catch.

**Review by miretskiy — APPROVED** [review]

File: pkg/util/json/tokenizer/scanner.go (hunk 1 above)
Comment (miretskiy) [reply pkg/util/json/tokenizer/scanner.go:255]: How about just returning nil, pos? no need for loop label then...
I think this "optimization" about eof was not great.

Comment (jordanlewis) [reply pkg/util/json/tokenizer/scanner.go:255]: Done

**Comment by miretskiy** [comment]
I don't recall this being backported to 22.2 -- was it?

**Comment by jordanlewis** [comment]
No, I don't think the new JSON parser is in 22.2. TFTR!

bors r+

**Comment by jordanlewis** [comment]
Added another test to the error suite to be thorough at @miretskiy suggestion.

bors r+
