### PR TITLE
tree: make typeCheckSameTypedExprs order invariant for tuples

### LINKED ISSUE #109105: sql: CASE with RECORD type and NULL causes internal error with vectorized engine
**Describe the problem**

Running a query with `CASE`, where one of the branches is a `RECORD` type and another branch is `NULL`, can cause an internal error.
 
**To Reproduce**

On master or prior versions, create the following logictest:
```
statement ok
CREATE TABLE tab (b BOOL);
INSERT INTO tab VALUES (false);

query I
SELECT (CASE WHEN b THEN NULL ELSE ((ROW(1) AS a)) END).a from tab;
----
1
```
After #108387 merges, replace the last statement with:
```
SELECT (CASE WHEN b THEN ((ROW(1) AS a)) ELSE NULL END).a from tab
```

When running with the `fakedist` config (e.g., `./dev testlogic base --files=testfile --config=fakedist --stress`), this produces the following error:
```
        (XX000) internal error: unable to vectorize execution plan: (CASE WHEN "$0" THEN CAST(NULL AS RECORD) ELSE ((1,) AS a) END).a: could not identify column "a" in record data type
        expr.go:88: in processExpression()
        DETAIL: stack trace:
        github.com/cockroachdb/cockroach/pkg/sql/execinfrapb/pkg/sql/execinfrapb/expr.go:88: processExpression()
        github.com/cockroachdb/cockroach/pkg/sql/execinfrapb/pkg/sql/execinfrapb/expr.go:169: DeserializeExpr()
        github.com/cockroachdb/cockroach/pkg/sql/execinfrapb/pkg/sql/execinfrapb/expr.go:209: Init()
        github.com/cockroachdb/cockroach/pkg/sql/execinfra/processorsbase.go:173: Init()
        github.com/cockroachdb/cockroach/pkg/sql/execinfra/processorsbase.go:795: InitWithEvalCtx()
        github.com/cockroachdb/cockroach/pkg/sql/execinfra/processorsbase.go:764: Init()
        github.com/cockroachdb/cockroach/pkg/sql/rowexec/noop.go:57: newNoopProcessor()
        github.com/cockroachdb/cockroach/pkg/sql/rowexec/processors.go:127: NewProcessor()
        github.com/cockroachdb/cockroach/pkg/sql/colexec/colbuilder/execplan.go:557: func1()
        github.com/cockroachdb/cockroach/pkg/sql/colexec/colbuilder/execplan.go:111: wrapRowSources()
        github.com/cockroachdb/cockroach/pkg/sql/colexec/colbuilder/execplan.go:545: createAndWrapRowSource()
        github.com/cockroachdb/cockroach/pkg/sql/colexec/colbuilder/execplan.go:1856: wrapPostProcessSpec()
        github.com/cockroachdb/cockroach/pkg/sql/colexec/colbuilder/execplan.go:1716: NewColOperator()
        github.com/cockroachdb/cockroach/pkg/sql/colflow/vectorized_flow.go:1197: func1()
        github.com/cockroachdb/cockroach/pkg/sql/colexecerror/error.go:92: CatchVectorizedRuntimeError()
        github.com/cockroachdb/cockroach/pkg/sql/colflow/vectorized_flow.go:1132: setupFlow()
        github.com/cockroachdb/cockroach/pkg/sql/colflow/vectorized_flow.go:260: Setup()
        github.com/cockroachdb/cockroach/pkg/sql/distsql/server.go:429: setupFlow()
        github.com/cockroachdb/cockroach/pkg/sql/distsql/server.go:661: func1()
        github.com/cockroachdb/cockroach/pkg/sql/distsql/server.go:689: SetupFlow()
        github.com/cockroachdb/cockroach/pkg/sql/execinfrapb/bazel-out/darwin_arm64-fastbuild/bin/pkg/sql/execinfrapb/execinfrapb_go_proto_/github.com/cockroachdb/cockroach/pkg/sql/execinfrapb/api.pb.go:602: func1()
        github.com/cockroachdb/cockroach/pkg/util/tracing/grpcinterceptor/grpc_interceptor.go:97: func1()
        google.golang.org/grpc/external/org_golang_google_grpc/server.go:1163: func1()
        github.com/cockroachdb/cockroach/pkg/rpc/pkg/rpc/context.go:169: func3()
        google.golang.org/grpc/external/org_golang_google_grpc/server.go:1163: func1()
        github.com/cockroachdb/cockroach/pkg/rpc/pkg/rpc/auth.go:105: unaryInterceptor()
        google.golang.org/grpc/external/org_golang_google_grpc/server.go:1163: func1()
        github.com/cockroachdb/cockroach/pkg/rpc/pkg/rpc/context.go:136: 1()
        github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:336: RunTaskWithErr()
        github.com/cockroachdb/cockroach/pkg/rpc/pkg/rpc/context.go:134: func1()
        google.golang.org/grpc/external/org_golang_google_grpc/server.go:1154: func1()
        github.com/cockroachdb/cockroach/pkg/sql/execinfrapb/bazel-out/darwin_arm64-fastbuild/bin/pkg/sql/execinfrapb/execinfrapb_go_proto_/github.com/cockroachdb/cockroach/pkg/sql/execinfrapb/api.pb.go:604: _DistSQL_SetupFlow_Handler()
```

**Expected behavior**
This should not cause an internal error.

Jira issue: CRDB-30782

### PR DESCRIPTION
**Pull request by msirek**
Type checking of CASE expressions (and other expressions handled by typeCheckSameTypedExprs) does not type check tuples properly because typeCheckSameTypedTupleExprs checking is only done when the tuple is the first expression in `exprs`.

This is fixed by finding the first tuple in `exprs`, searching the slice starting at index 0, and using that to drive typeCheckSameTypedExprs.

Fixes: #109105

Release note: None

### CODE REVIEW

File: pkg/sql/sem/tree/type_check.go [hunk 1]
```diff
@@ -2564,6 +2564,15 @@ type typeCheckExprsState struct {
 	resolvableIdxs  intsets.Fast // index into exprs/typedExprs
 }
 
+func findFirstTupleIndex(exprs ...Expr) (index int, ok bool) {
+	for i, expr := range exprs {
+		if _, ok := expr.(*Tuple); ok {
```
Comment (mgartner) [inline pkg/sql/sem/tree/type_check.go:2569]: I know I'm a broken record here but we really need to stop inspecting the type of AST node to help determine the SQL type of expressions. All these cases are only partial fixes because they won't fix cases where the AST isn't Tuple but the SQL type produced is a tuple type.

This is fine for now, because it's a bit better than the current behavior. But maybe we should start labelling these places with TODOs that make it clear this is not the long-term solution? I don't want people to unknowingly repeat this pattern.

File: pkg/sql/sem/tree/type_check.go [hunk 2]
```diff
@@ -2588,8 +2597,17 @@ func typeCheckSameTypedExprs(
 	}
 
 	// Handle tuples, which will in turn call into this function recursively for each element.
-	if _, ok := exprs[0].(*Tuple); ok {
-		return typeCheckSameTypedTupleExprs(ctx, semaCtx, desired, exprs...)
+	if idx, ok := findFirstTupleIndex(exprs...); ok {
+		if _, ok := exprs[idx].(*Tuple); ok {
+			// typeCheckSameTypedTupleExprs expects the first expression in the slice
+			// to be a tuple.
+			exprs[0], exprs[idx] = exprs[idx], exprs[0]
```
Comment (mgartner) [inline pkg/sql/sem/tree/type_check.go:2604]: I'm not convinced it is safe to reorder subexpressions. Won't this change the semantics of parent nodes that pass in their `exprs` directly from an AST node, like `CoalesceExpr.TypeCheck`: https://github.com/cockroachdb/cockroach/blob/1758e91c7fe48dd3032bf9479402000eed393146/pkg/sql/sem/tree/type_check.go#L888

**Review by msirek — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/110325)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @mgartner)

___
*[`pkg/sql/sem/tree/type_check.go` line 2569 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/110325#gh-1323379399:-NeAZs7I5N8Ghkk98tk8:b40dj5e) ([raw file](https://github.com/cockroachdb/cockroach/blob/9e526be84c3a68929a27e62853784d0a31476d80/pkg/sql/sem/tree/type_check.go#L2569)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

I know I'm a broken record here but we really need to stop inspecting the type of AST node to help determine the SQL type of expressions. All these cases are only partial fixes because they won't fix cases where the AST isn't Tuple but the SQL type produced is a tuple type.

This is fine for now, because it's a bit better than the current behavior. But maybe we should start labelling these places with TODOs that make it clear this is not the long-term solution? I don't want people to unknowingly repeat this pattern.
</blockquote></details>

Thanks for pointing this out.  I agree that we want to handle other expressions that resolve to a type family of `TupleFamily`.  I've added a TODO. The whole pre-existing logic here makes the assumption that we're working with `Tuple`s, for example, the comment here:

https://github.com/msirek/cockroach/blob/9e526be84c3a68929a27e62853784d0a31476d80/pkg/sql/sem/tree/type_check.go#L2987-L2990

```go
		if !(isTuple || isNull) {
			// We avoid calling TypeCheck on Tuple exprs since that causes the
			// types to be resolved, which we only want to do later in type-checking.
			typedExpr, err := expr.TypeCheck(ctx, semaCtx, types.Any)
```
So it may be a much larger change to rework the logic to handle other expressions, and for this PR I'm just targeting the smallest/safest change to handle [#109105](https://github.com/cockroachdb/cockroach/issues/109105).
___
*[`pkg/sql/sem/tree/type_check.go` line 2604 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/110325#gh-1323379442:-NeAUbzIC4Br-RA6U4rS:b-uz62tp) ([raw file](https://github.com/cockroachdb/cockroach/blob/9e526be84c3a68929a27e62853784d0a31476d80/pkg/sql/sem/tree/type_check.go#L2604)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

I'm not convinced it is safe to reorder subexpressions. Won't this change the semantics of parent nodes that pass in their `exprs` directly from an AST node, like `CoalesceExpr.TypeCheck`: https://github.com/cockroachdb/cockroach/blob/1758e91c7fe48dd3032bf9479402000eed393146/pkg/sql/sem/tree/type_check.go#L888
</blockquote></details>

All of the type tests for `typeCheckSameTypedExprs` imply that this function finds a result type independent of the order of the input expressions, which matches my understanding of what this function is trying to do (find a common data type for all expressions in the slice). For example, both `SELECT pg_typeof(COALESCE(3, 3.3))` and `SELECT pg_typeof(COALESCE(3.3, 3))` result in a final type of `numeric` for the expression. If `typeCheckSameTypedExprs` were order dependent, we'd expect to see one result be `bigint` and the other to be `numeric`.

The line added below:
```go
typedExprs[0], typedExprs[idx] = typedExprs[idx], typedExprs[0]
```
ensures that the `typedExprs` returned to the caller match up with their corresponding untyped expressions that were passed to `typeCheckSameTypedExprs`, so there is no change in behavior in that regard.  There is no re-ordering of returned expressions relative to the input expressions.

**Review by mgartner — COMMENTED** [review]
> Reviewed 3 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/110325)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @msirek)

___
*[`pkg/sql/sem/tree/type_check.go` line 2569 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/110325#gh-1323379399:-NedxSSEAcBz_2hZ22Yx:bmeyrwp) ([raw file](https://github.com/cockroachdb/cockroach/blob/9e526be84c3a68929a27e62853784d0a31476d80/pkg/sql/sem/tree/type_check.go#L2569)):*
<details><summary><i>Previously, msirek (Mark Sirek) wrote…</i></summary><blockquote>

Thanks for pointing this out.  I agree that we want to handle other expressions that resolve to a type family of `TupleFamily`.  I've added a TODO. The whole pre-existing logic here makes the assumption that we're working with `Tuple`s, for example, the comment here:

https://github.com/msirek/cockroach/blob/9e526be84c3a68929a27e62853784d0a31476d80/pkg/sql/sem/tree/type_check.go#L2987-L2990

```go
		if !(isTuple || isNull) {
			// We avoid calling TypeCheck on Tuple exprs since that causes the
			// types to be resolved, which we only want to do later in type-checking.
			typedExpr, err := expr.TypeCheck(ctx, semaCtx, types.Any)
```
So it may be a much larger change to rework the logic to handle other expressions, and for this PR I'm just targeting the smallest/safest change to handle [#109105](https://github.com/cockroachdb/cockroach/issues/109105).
</blockquote></details>

:+1: 
___
*[`pkg/sql/sem/tree/type_check.go` line 2604 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/110325#gh-1323379442:-NedxwFABak0wBJaF4d4:b9hi2rj) ([raw file](https://github.com/cockroachdb/cockroach/blob/9e526be84c3a68929a27e62853784d0a31476d80/pkg/sql/sem/tree/type_check.go#L2604)):*
Oops, I missed that line.

> All of the type tests for `typeCheckSameTypedExprs` imply that this function finds a result type independent of the order of the input expressions, which matches my understanding of what this function is trying to do

This is currently how our type-checking works, but, as we discovered in #108387, type-checking of expressions like these is indeed order-dependent. No need to fix that now though.
___
*[`pkg/sql/logictest/testdata/logic_test/tuple` line 1278 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/110325#-NedyjSW8RRs82QsAKfu:-NedyjSW8RRs82QsAKfv:bzheimd) ([raw file](https://github.com/cockroachdb/cockroach/blob/593c830a8d9a01ebed5b061e4d15d86c8266ccd0/pkg/sql/logictest/testdata/logic_test/tuple#L1278)):*
> ```
>              WHEN a = 4 THEN ROW(1::INT, null, NULL)
>              WHEN a = 5 THEN NULL
>              ELSE NULL END) FROM t109105 ORDER BY 1;
> ```

This example errors with `42883: could not identify a comparison function for type unknown` in Postgres. So is this PR a temporary fix for the internal error in #109105? Or is there some reason we want to diverge from Postgres here?

**Review by msirek — COMMENTED** [review]
>> All of the type tests for `typeCheckSameTypedExprs` imply that this function finds a result type independent of the order of the input expressions, which matches my understanding of what this function is trying to do

>This is currently how our type-checking works, but, as we discovered in [#108387](https://github.com/cockroachdb/cockroach/pull/108387), type-checking of expressions like these is indeed order-dependent. No need to fix that now though.

Sure. Just to clarify, it is the type checking of row types in this case which tries to find a common type among all column 1 elements, and among all column 2 elements, etc.  This PR is not attempting to change that behavior, just make it consistent when the first item in the slice is a null instead of a row.  

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/110325#-:-NexDTrT9G_UgZhl8Kk5:bo3qva3)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @mgartner)

___
*[`pkg/sql/logictest/testdata/logic_test/tuple` line 1278 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/110325#-NedyjSW8RRs82QsAKfu:-NexFKjtEJswt9Y4X-TG:bwek3o5) ([raw file](https://github.com/cockroachdb/cockroach/blob/593c830a8d9a01ebed5b061e4d15d86c8266ccd0/pkg/sql/logictest/testdata/logic_test/tuple#L1278)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

This example errors with `42883: could not identify a comparison function for type unknown` in Postgres. So is this PR a temporary fix for the internal error in #109105? Or is there some reason we want to diverge from Postgres here?
</blockquote></details>

See my other comment. To match postgres, `typeCheckSameTypedTupleExprs` should be modified so that a NULL in the same column of a row expression as a non-null errors out. Similar queries such as:
```sql
SELECT (CASE WHEN a = 3 THEN ROW(1::INT, 1.1::DECIMAL, 1.1e3::FLOAT)
             WHEN a = 2 THEN ROW(NULL, NULL, 1.1e3::FLOAT)
             WHEN a = 3 THEN ROW(NULL, 1.1::DECIMAL, NULL)
             WHEN a = 4 THEN ROW(1::INT, NULL, NULL)
             ELSE ROW(1::INT, 1.1::DECIMAL, 1.1e3::FLOAT) END) FROM t109105 ORDER BY 1;
```
don't error out on v23.1 and prior (but do on postgres), so the non-erroring on comparison with null issue is pre-existing and independent of tuple typing.

The motivation behind this fix is consistent typing so the execution engine does the right thing and doesn't hit an internal error.

Note that a similar query to the one which hit the internal error does not error out on postgres:
```sql
test=# SELECT (CASE WHEN b THEN ((ROW(1))) ELSE NULL END) from t78159;
 case
------
(0 rows)
```

The effort to get the tuple typing rules to match postgres may be non-trivial, so it's better to fix the internal error in the short term, matching our current behavior, than to try a quick fix of the postres rules.

**Review by mgartner — APPROVED** [review]
:lgtm: 

> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/110325#-:-NfMBUrs6zCZQNgO5NVp:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @msirek)

**Comment by msirek** [comment]
TFTR!
bors r+
