### PR TITLE
cli: "no such host" error when starting CRDB on Mac

### LINKED ISSUE #66426: cli: "no such host" error when starting CRDB on Mac
**Repro:**
On Mac, start CRDB using this command line:
```
./cockroach start-single-node --insecure
```

EXPECTED: No error, the node should start.
ACTUAL: `ERROR: failed to start server: invalid --advertise-addr: lookup AndyK-MacBook-Pro: no such host`

This `ping` command fails on my Mac, and is presumably the reason why the host fails to resolve:
```
AndyK-MacBook-Pro:server andyk$ ping $(hostname)
ping: cannot resolve AndyK-MacBook-Pro: Unknown host
```

We should consider not using the default hostname if it doesn't resolve. Even if we can't do that for some reason, we should change the error so that it does not reference a flag that was not actually provided.

Jira issue: CRDB-8043

### PR DESCRIPTION
**Pull request by srosenberg**
When CockroachDB is started without `--advertise-addr`, it fallbacks to `--listen-addr`. If the latter is also unspecified, it defaults to the `hostname`.

Subsequently, `validateAdvertiseAddr` attempts to
resolve the hostname. If the resolution fails, the server aborts the startup sequence. This is a safe default because node discovery is compromised without a functioning DNS.

On Mac, `hostname` is resolved via mDNS / Bonjour. Unless it's suffixed with `.local`, it doesn't resolve. An obvious workaround is to add it to /etc/hosts, or to change it via `sudo hostname $USER.local`.

To make the (DEV) experience on Mac more seamless, this PR replaces DNS resolution error with a warning. Since we can't unambiguously determine if the user is running in DEV-mode, we assume that `--insecure` on Mac implies exactly that.

We also update `roachprod` to explicitly use `--advertised-addr` with `127.0.0.1`. This also fixes `roachtest` in local mode.

Fixes: #66426
Fixes: #149469
Release note: None

### CODE REVIEW

**Comment by srosenberg** [comment]
Friendly ping

**Review by DarrylWong — APPROVED** [review]

**Comment by srosenberg** [comment]
TFTR!

bors r=darrylwong

File: pkg/roachprod/install/cockroach.go [hunk 1]
```diff
@@ -1169,7 +1169,7 @@ func (c *SyncedCluster) generateStartArgs(
 	}
 
 	listenHost := ""
-	if c.IsLocal() && runtime.GOOS == "darwin " {
```
Comment (williamchoe3) [inline pkg/roachprod/install/cockroach.go:1172]: lol

**Comment by williamchoe3** [comment]
bors retry
