### PR TITLE
workload: reset w_ytd and d_ytd periodically for long running workload

### LINKED ISSUE #124259: workload: tpcc workload fails after after period with decimal errors
After running TPCC for a week, the workload starts to fail with error of the form ` workload/cli/run.go:569  [-] 1622  error in payment: update warehouse failed: ERROR: type DECIMAL(12,2): value with precision 12, scale 2 must round to an absolute value less than 10^10 (SQLSTATE 22003)`.

It appears that the accumulated balance for the warehouse grows indefinitely and eventually exceeds the decimal's bounds.

We should add an option for longer / continuous runs that avoids this, e.g. by resetting or periodically reducing this, or altering the schema, etc.

Jira issue: CRDB-38796

### PR DESCRIPTION
**Pull request by sambhav-jain-16**
Fixes: #124259

Release note: None

The tpc-c workload used to fail when ran for a long period of time with the following error:

```
 workload/cli/run.go:569  [-] 1622  error in payment: update warehouse failed: ERROR: type DECIMAL(12,2): value with precision 12, scale 2 must round to an absolute value less than 10^10 (SQLSTATE 22003)
```
The solution is to reset the `w-ytd` column in the `warehouse` table after every 24 hours period if we run the workload with `duration=0` or `duration>=4d`. Since `d_ytd` also has a similar schema, this PR also does the similar reset in `district` table. 

Due to resetting the column values periodically, this change also disables 3 consistency checks for a long duration workload which involves `w_ytd` and `d_ytd`

### CODE REVIEW

File: pkg/workload/cli/run.go [hunk 1]
```diff
@@ -140,6 +140,7 @@ func init() {
 			var genFlags *pflag.FlagSet
 			if f, ok := gen.(workload.Flagser); ok {
 				genFlags = f.Flags().FlagSet
+				gen.(workload.Flagser).Flags().AddFlag(runFlags.Lookup("duration"))
```
Comment (itsbilal) [inline pkg/workload/cli/run.go:143]: I'm not sure if this is doing anything. We add genFlags down below alongside all of runFlags to the run command already?

File: pkg/workload/tpcc/tpcc.go [hunk 2]
```diff
@@ -39,6 +39,14 @@ import (
 
 var RandomSeed = workload.NewUint64RandomSeed()
 
+const (
+	//A threshold that defines which duration is considered a long workload which is not meant for a benchmark result
```
Comment (itsbilal) [inline pkg/workload/tpcc/tpcc.go:43]: nit: space after //

File: pkg/workload/tpcc/tpcc.go [hunk 3]
```diff
@@ -114,6 +122,10 @@ type tpcc struct {
 		values [][]int
 	}
 	localsPool *sync.Pool
+
+	// In cases of longDurationWorkloadThreshold, we skip 3.3.2.1 and 3.3.2.8
```
Comment (itsbilal) [inline pkg/workload/tpcc/tpcc.go:126]: nit: can be reworded to `Set to true if duration >= longDurationWorkloadThreshold. In that case, we reset ... periodically and skip .... consistency checks`.

File: pkg/workload/tpcc/tpcc.go [hunk 4]
```diff
@@ -809,6 +826,18 @@ func (w *tpcc) Ops(
 		}
 	}
 
+	if duration, err := w.flags.GetDuration("duration"); err == nil {
+		if duration == 0 || duration >= longDurationWorkloadThreshold {
+			log.Warningf(ctx,
+				"Since the workload is set for %s duration and it's not meant for a public benchmark, "+
```
Comment (itsbilal) [inline pkg/workload/tpcc/tpcc.go:832]: How about "Warning: this workload is being used with a long or indefinite duration. This could cause it to deviate from the TPCC spec in subtle ways and is not meant for benchmarking. Consistency checks might be disabled"

File: pkg/workload/tpcc/payment.go [hunk 5]
```diff
@@ -192,11 +208,24 @@ func (p *payment) run(ctx context.Context, wID int) (interface{}, error) {
...
+			// When isLongDurationWorkload is true, we want to reset w_ytd
+			if p.config.isLongDurationWorkload && timeutil.Since(p.previousResetTime[wID]) >= warehouseWytdResetPeriod {
+
+				// Reset w_ytd to the initial value.
+				if _, err := p.resetWarehouse.ExecTx(
+					ctx, tx, wYtd, wID,
+				); err != nil {
+					return errors.Wrap(err, "reset warehouse failed")
+				}
+				p.previousResetTime[wID] = timeutil.Now()
```
Comment (itsbilal) [inline pkg/workload/tpcc/payment.go:221]: This is not concurrent-safe, as `p` is shared across workers. We'd either want to throw accesses/updates of this map behind a mutex (slow), or alternatively we can use atomics and try to take advantage of the db's txn and `SELECT` for the current value, see if it's high, then `UPDATE` it within the same timestamp. If our transaction succeeds, we can then update the value in the map using atomic operations.

You could also spin up a separate goroutine that waits on ticks from a `time.NewTimer`, and upon a tick it resets the counts of all warehouses within one transaction. That might actually be easier, as we don't need to keep track of `previousResetTime` at all.

**Review by itsbilal — COMMENTED** [review]
Great work!

File: pkg/workload/tpcc/payment.go (hunk 5 above)
Comment (sambhav-jain-16) [reply pkg/workload/tpcc/payment.go:221]: I initially thought of the second approach itself with a ticket but there can be cases of huge number of warehouses (> 100k), and updating them in a single transaction might be an issue, but that can be solved by creating batches. 

I think since there's state involved here in this implementation with the complexity of concurrency, a different goroutine with a ticker might be better approach. I'll move to that approach now. Thanks for the comment.

File: pkg/workload/cli/run.go (hunk 1 above)
Comment (sambhav-jain-16) [reply pkg/workload/cli/run.go:143]: Flags added to runFlags are not propagated to the workload flags are not accessible in the workload. That's why we need to add the `duration` flag to the generator flags.

**Comment by sambhav-jain-16** [comment]
Thanks @itsbilal for the review. I have implemented the suggestions. PTAL when available. TIA

File: pkg/workload/tpcc/payment.go [hunk 6]
```diff
@@ -140,13 +143,68 @@ func createPayment(ctx context.Context, config *tpcc, mcp *workload.MultiConnPoo
...
+				if err := p.config.executeTx(
+					ctx, p.mcp.Get(),
+					func(tx pgx.Tx) error {
+						if _, err := p.resetWorkhouse.ExecTx(
+							ctx, tx, wYtd, startRange, endRange,
+						); err != nil {
+							return errors.Wrap(err, "reset warehouse failed")
+						}
+
+						if _, err := p.resetDistrict.ExecTx(
```
Comment (sambhav-jain-16) [inline pkg/workload/tpcc/payment.go:193]: Added `d_ytd` change also here

**Review by itsbilal — APPROVED** [review]
LGTM save for one comment

File: pkg/workload/tpcc/payment.go [hunk 7]
```diff
@@ -140,13 +143,68 @@ func createPayment(ctx context.Context, config *tpcc, mcp *workload.MultiConnPoo
...
 	return p, nil
 }
 
+func (p *payment) startResetValueWorker(ctx context.Context) {
+	ticker := time.NewTicker(warehouseWytdResetPeriod)
+	defer ticker.Stop()
+
+	for {
+		select {
+		case <-ctx.Done():
```
[the remark this answers is not in the document]
Comment (sambhav-jain-16) [reply pkg/workload/tpcc/payment.go:179]: Thanks @itsbilal for the pointer.
I have implemented the wait group since I think it might be a cleaner solution if in future we might want to add for background reset tasks.

**Comment by vidit-bhat** [comment]
Let's add a summary to the PR. You can edit the first comment.

**Review by vidit-bhat — APPROVED** [review]

File: pkg/workload/tpcc/payment.go [hunk 8]
```diff
@@ -140,13 +143,71 @@ func createPayment(ctx context.Context, config *tpcc, mcp *workload.MultiConnPoo
 		VALUES ($1, $2, $3, $4, $5, $6, $7, $8)`,
 	)
 
+	if p.config.isLongDurationWorkload {
+		p.resetWorkhouse = p.sr.Define(`
```
Comment (srosenberg) [inline pkg/workload/tpcc/payment.go:147]: Nit: `Workhouse` -> `Warehouse`

File: pkg/workload/tpcc/tpcc.go [hunk 9]
```diff
@@ -39,6 +39,17 @@ import (
 
 var RandomSeed = workload.NewUint64RandomSeed()
 
+const (
+	// A threshold that defines which duration is considered a long workload which is not meant for a benchmark result
+	longDurationWorkloadThreshold = 4 * 24 * time.Hour
+
+	// The reset time period in case we are running a long duration workload.
+	warehouseWytdResetPeriod = 2 * time.Minute
```
Comment (srosenberg) [inline pkg/workload/tpcc/tpcc.go:47]: Nit: `resetValueWorkerPeriod`

File: pkg/workload/tpcc/payment.go [hunk 10]
```diff
@@ -140,13 +143,71 @@ func createPayment(ctx context.Context, config *tpcc, mcp *workload.MultiConnPoo
...
+	defer p.config.resetTableWg.Done()
+
+	for {
+		select {
+		case <-ctx.Done():
+			return
+		case <-ticker.C:
+
+			// Creating batches of maxRowsToUpdateTxn to avoid long-running txns
+			for startRange := 0; startRange <= p.config.warehouses; startRange += maxRowsToUpdateTxn {
```
Comment (srosenberg) [inline pkg/workload/tpcc/payment.go:184]: If warehouses is 0-based, then `startRange` should be exclusive of `p.config.warehouses`; i.e., otherwise, it's an empty range.

**Review by srosenberg — COMMENTED** [review]
How was this change tested?

**Comment by sambhav-jain-16** [comment]
> How was this change tested?

I tested these changes using roachprod.

File: pkg/workload/tpcc/payment.go (hunk 10 above)
Comment (sambhav-jain-16) [reply pkg/workload/tpcc/payment.go:184]: Thanks for pointing out !

**Review by srosenberg — APPROVED** [review]
