### PR TITLE
sql: add optimizer_use_limit_ordering_for_streaming_group_by session setting

### LINKED ISSUE #93410: Suboptimal query plan on grouped aggregation with LIMIT and ORDER BY
**Describe the problem**
In support issue https://github.com/cockroachlabs/support/issues/1949, a hash group-by + TopK plan is chosen over a streaming group-by when there is a LIMIT on the query because of unique constraints on certain columns, causing the number of grouping columns to be reduced by the optimizer. When one of the unique indexes is dropped, the fast query plan is picked.  

**To Reproduce**
Use the statement bundles in the support issue.

Jira issue: CRDB-22320

### PR DESCRIPTION
**Pull request by msirek**
Fixes #93410

This commit adds the `optimizer_use_limit_ordering_for_streaming_group_by` session setting that defaults to `true`. When `true`, an exploration rule which uses the ordering specified in a
`SELECT ... GROUP BY ... ORDER BY ... LIMIT n;` statement as an interesting ordering to require from the input to the group-by expression, possibly eliminating a top-k operation.  When `false`, the exploration rule is disabled.

Release note: None

### CODE REVIEW

**Review by DrewKimball — APPROVED** [review]
:lgtm:

> Reviewed 11 of 11 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/94672#-:-NKu0nn90PoYcelIB3wF:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @rharding6373)

File: pkg/sql/opt/xform/groupby_funcs.go [hunk 1]
```diff
@@ -228,6 +228,10 @@ func (c *CustomFuncs) GenerateStreamingGroupByLimitOrderingHint(
 	groupingCols opt.ColSet,
 	newOrdering props.OrderingChoice,
 ) {
+	if !c.e.evalCtx.SessionData().OptimizerUseLimitOrderingForStreamingGroupBy {
```
Comment (mgartner) [inline pkg/sql/opt/xform/groupby_funcs.go:231]: nit: add an xform test with this setting disabled and an `expect-not` to verify this works

**Review by rharding6373 — APPROVED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/94672#-:-NKy1uOdCmGVQvcjvOUb:bg7igkv)* status: :shipit: complete! 2 of 0 LGTMs obtained (waiting on @msirek)

**Review by msirek — COMMENTED** [review]
TFTRs!
bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/94672#-:-NKzlyz1DUPhS46_TNQc:bg1822s)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale) (waiting on @DrewKimball and @mgartner)

___
*[`pkg/sql/opt/xform/groupby_funcs.go` line 231 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/94672#-NKu-v2CZaA7bJObcPZv-r1-231:-NKzlfRF4yQuMKyl96fw:bb6un1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/905b302037d37bd36361e269224d5cfd602d008e/pkg/sql/opt/xform/groupby_funcs.go#L231)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

nit: add an xform test with this setting disabled and an `expect-not` to verify this works
</blockquote></details>

Done
