### PR TITLE
Release RLock before calling MaybeAdd to avoid deadlock

### LINKED ISSUE #3694: Failed tests (10801): TestGetTruncatableIndexes deadlock on store.mu
The following test appears to have failed:

[#10801](https://circleci.com/gh/cockroachdb/cockroach/10801):

```
I0108 08:59:27.579113 939 storage/replica.go:1619  gossiping system config from store 1, range 1
I0108 08:59:27.579923 939 storage/replica.go:1568  gossiping sentinel from store 1, range 1
I0108 08:59:27.580263 939 storage/replica.go:1574  gossiping first range from store 1, range 1
I0108 08:59:27.584087 939 storage/raft_log_queue.go:74  the raft group doesn't exist for range 100
I0108 08:59:27.597591 939 storage/raft_log_queue.go:133  truncating the raft log of range 1 to 22
panic: test timed out after 5m0s

goroutine 566 [running]:
testing.startAlarm.func1()
	/tmp/workdir/go/src/testing/testing.go:703 +0x16b
created by time.goFunc
	/tmp/workdir/go/src/time/sleep.go:129 +0x6e

goroutine 1 [chan receive, 4 minutes]:
testing.RunTests(0x1a691a8, 0x21162a0, 0xdb, 0xdb, 0x1)
	/tmp/workdir/go/src/testing/testing.go:562 +0xafa
testing.(*M).Run(0xc820033f10, 0x1)
	/tmp/workdir/go/src/testing/testing.go:494 +0xe5
github.com/cockroachdb/cockroach/util/leaktest.TestMainWithLeakCheck(0xc820033f10)
	/go/src/github.com/cockroachdb/cockroach/util/leaktest/leaktest.go:34 +0x2f
github.com/cockroachdb/cockroach/storage_test.TestMain(0xc820033f10)
	/go/src/github.com/cockroachdb/cockroach/storage/main_test.go:36 +0x34
main.main()
	github.com/cockroachdb/cockroach/storage/_test/_testmain.go:498 +0x20a

goroutine 17 [syscall, 4 minutes, locked to thread]:
runtime.goexit()
	/tmp/workdir/go/src/runtime/asm_amd64.s:1721 +0x1

goroutine 5 [chan receive]:
github.com/cockroachdb/cockroach/util/log.(*loggingT).flushDaemon(0x21714e0)
	/go/src/github.com/cockroachdb/cockroach/util/log/clog.go:1029 +0x76
created by github.com/cockroachdb/cockroach/util/log.init.1
	/go/src/github.com/cockroachdb/cockroach/util/log/clog.go:610 +0x117

goroutine 558 [select, 4 minutes]:
github.com/cockroachdb/cockroach/storage.(*baseQueue).processLoop.func1()
	/go/src/github.com/cockroachdb/cockroach/storage/queue.go:319 +0x427
github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker.func1(0xc8201380e0, 0xc8202da8a0)
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:89 +0x60
created by github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:90 +0x70

goroutine 552 [select, 4 minutes]:
github.com/cockroachdb/cockroach/storage.(*StorePool).start.func1()
	/go/src/github.com/cockroachdb/cockroach/storage/store_pool.go:213 +0x208
github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker.func1(0xc8201380e0, 0xc8202da1e0)
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:89 +0x60
created by github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:90 +0x70

goroutine 540 [select, 4 minutes]:
github.com/cockroachdb/cockroach/storage.(*Store).Start.func3()
	/go/src/github.com/cockroachdb/cockroach/storage/store.go:556 +0x15d
github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker.func1(0xc8201380e0, 0xc82000f0c0)
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:89 +0x60
created by github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:90 +0x70

goroutine 560 [select, 4 minutes]:
github.com/cockroachdb/cockroach/storage.(*baseQueue).processLoop.func1()
	/go/src/github.com/cockroachdb/cockroach/storage/queue.go:319 +0x427
github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker.func1(0xc8201380e0, 0xc8202da8e0)
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:89 +0x60
created by github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:90 +0x70

goroutine 562 [select, 4 minutes]:
github.com/cockroachdb/cockroach/storage.(*baseQueue).processLoop.func1()
	/go/src/github.com/cockroachdb/cockroach/storage/queue.go:319 +0x427
github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker.func1(0xc8201380e0, 0xc8202da920)
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:89 +0x60
created by github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:90 +0x70

goroutine 538 [chan receive, 4 minutes]:
github.com/cockroachdb/cockroach/util.ListenAndServe.func2()
	/go/src/github.com/cockroachdb/cockroach/util/net.go:88 +0x7b
github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker.func1(0xc8201380e0, 0xc82000f080)
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:89 +0x60
created by github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:90 +0x70

goroutine 539 [semacquire, 4 minutes]:
sync.runtime_Semacquire(0xc8202d83b8)
	/tmp/workdir/go/src/runtime/sema.go:43 +0x26
sync.(*RWMutex).Lock(0xc8202d83b0)
	/tmp/workdir/go/src/sync/rwmutex.go:87 +0xc7
github.com/cockroachdb/cockroach/storage.(*Store).processRaft.func1()
	/go/src/github.com/cockroachdb/cockroach/storage/store.go:1595 +0x17d
github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker.func1(0xc8201380e0, 0xc820277600)
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:89 +0x60
created by github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:90 +0x70

goroutine 564 [select, 4 minutes]:
github.com/cockroachdb/cockroach/storage.(*replicaScanner).waitAndProcess(0xc82016c300, 0xece21716f, 0x22bccd0e, 0x2170f60, 0xc8200156e0, 0xc8201380e0, 0xc8201a09c0, 0xc8202d83c0)
	/go/src/github.com/cockroachdb/cockroach/storage/scanner.go:176 +0x641
github.com/cockroachdb/cockroach/storage.(*replicaScanner).scanLoop.func1.1(0xc8201a09c0, 0xc8202ea240)
	/go/src/github.com/cockroachdb/cockroach/storage/scanner.go:217 +0xb0
github.com/cockroachdb/cockroach/storage.(*storeRangeSet).Visit(0xc8202ea3c0, 0xc82026ecc0)
	/go/src/github.com/cockroachdb/cockroach/storage/store.go:225 +0x45c
github.com/cockroachdb/cockroach/storage.(*replicaScanner).scanLoop.func1()
	/go/src/github.com/cockroachdb/cockroach/storage/scanner.go:219 +0x452
github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker.func1(0xc8201380e0, 0xc8202da960)
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:89 +0x60
created by github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:90 +0x70

goroutine 541 [semacquire, 4 minutes]:
sync.runtime_Semacquire(0xc8202d83bc)
	/tmp/workdir/go/src/runtime/sema.go:43 +0x26
sync.(*RWMutex).RLock(0xc8202d83b0)
	/tmp/workdir/go/src/sync/rwmutex.go:36 +0x76
github.com/cockroachdb/cockroach/storage.(*Store).LookupReplica(0xc8202d8200, 0x2b1f0e0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/storage/store.go:833 +0x63
github.com/cockroachdb/cockroach/storage.(*Store).maybeGossipFirstRange(0xc8202d8200, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/storage/store.go:668 +0x3b9
github.com/cockroachdb/cockroach/storage.(*Store).startGossip.func1()
	/go/src/github.com/cockroachdb/cockroach/storage/store.go:623 +0x2b8
github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker.func1(0xc8201380e0, 0xc82000f100)
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:89 +0x60
created by github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:90 +0x70

goroutine 535 [chan receive, 4 minutes]:
github.com/cockroachdb/cockroach/storage/engine.(*RocksDB).Open.func1(0xc8201d01e0)
	/go/src/github.com/cockroachdb/cockroach/storage/engine/rocksdb.go:123 +0x5b
created by github.com/cockroachdb/cockroach/storage/engine.(*RocksDB).Open
	/go/src/github.com/cockroachdb/cockroach/storage/engine/rocksdb.go:124 +0x581

goroutine 559 [select, 4 minutes]:
github.com/cockroachdb/cockroach/storage.(*baseQueue).processLoop.func1()
	/go/src/github.com/cockroachdb/cockroach/storage/queue.go:319 +0x427
github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker.func1(0xc8201380e0, 0xc8202da8c0)
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:89 +0x60
created by github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:90 +0x70

goroutine 542 [semacquire, 4 minutes]:
sync.runtime_Semacquire(0xc8202d83bc)
	/tmp/workdir/go/src/runtime/sema.go:43 +0x26
sync.(*RWMutex).RLock(0xc8202d83b0)
	/tmp/workdir/go/src/sync/rwmutex.go:36 +0x76
github.com/cockroachdb/cockroach/storage.(*Store).LookupReplica(0xc8202d8200, 0xc8201486a0, 0x9, 0x10, 0x0, 0x0, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/storage/store.go:833 +0x63
github.com/cockroachdb/cockroach/storage.(*Store).maybeGossipSystemConfig(0xc8202d8200, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/storage/store.go:684 +0x85
github.com/cockroachdb/cockroach/storage.(*Store).startGossip.func2()
	/go/src/github.com/cockroachdb/cockroach/storage/store.go:642 +0x2b8
github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker.func1(0xc8201380e0, 0xc82000f120)
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:89 +0x60
created by github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:90 +0x70

goroutine 551 [semacquire, 4 minutes]:
sync.runtime_Semacquire(0xc8202d83bc)
	/tmp/workdir/go/src/runtime/sema.go:43 +0x26
sync.(*RWMutex).RLock(0xc8202d83b0)
	/tmp/workdir/go/src/sync/rwmutex.go:36 +0x76
github.com/cockroachdb/cockroach/storage.(*Store).RaftStatus(0xc8202d8200, 0x1, 0x0)
	/go/src/github.com/cockroachdb/cockroach/storage/store.go:866 +0x4f
github.com/cockroachdb/cockroach/storage.getTruncatableIndexes(0xc8201a09c0, 0xc820276390, 0x8cdbc4, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/storage/raft_log_queue.go:71 +0xbd
github.com/cockroachdb/cockroach/storage.(*raftLogQueue).shouldQueue(0xc820092960, 0x0, 0xc800000030, 0xc8201a09c0, 0xc8202da700, 0xc820279500, 0xc8200156e8)
	/go/src/github.com/cockroachdb/cockroach/storage/raft_log_queue.go:111 +0x39
--
testing.tRunner(0xc820078000, 0x2116618)
	/tmp/workdir/go/src/testing/testing.go:456 +0xdd
created by testing.RunTests
	/tmp/workdir/go/src/testing/testing.go:561 +0xaa4

goroutine 563 [chan receive, 4 minutes]:
github.com/cockroachdb/cockroach/storage.(*Replica).addWriteCmd(0xc8201a09c0, 0x7fc7b1fcd9f8, 0xc82026f140, 0x0, 0x2e, 0x100000001, 0x1, 0x1, 0x0, 0x0, ...)
	/go/src/github.com/cockroachdb/cockroach/storage/replica.go:926 +0x7be
github.com/cockroachdb/cockroach/storage.(*Replica).Send(0xc8201a09c0, 0x7fc7b1fcd9f8, 0xc82026f140, 0x0, 0x2e, 0x100000001, 0x1, 0x1, 0x0, 0x0, ...)
	/go/src/github.com/cockroachdb/cockroach/storage/replica.go:628 +0x6a3
github.com/cockroachdb/cockroach/storage.(*Store).Send(0xc8202d8200, 0x7fc7b1fcd9f8, 0xc82026f140, 0x0, 0x2e, 0x100000001, 0x1, 0x1, 0x0, 0x0, ...)
	/go/src/github.com/cockroachdb/cockroach/storage/store.go:1312 +0xd81
github.com/cockroachdb/cockroach/storage.(*testSender).Send(0xc820026000, 0x7fc7b1fcd9b8, 0xc8200137c0, 0x0, 0x0, 0x100000001, 0x1, 0x1, 0x0, 0x0, ...)
	/go/src/github.com/cockroachdb/cockroach/storage/store_test.go:113 +0x6fd
github.com/cockroachdb/cockroach/client.(*DB).send(0xc820270000, 0xc8201c90e0, 0x1, 0x1, 0x1, 0x61a5a4)
	/go/src/github.com/cockroachdb/cockroach/client/db.go:482 +0x1e5
--
github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker.func1(0xc8201380e0, 0xc8202da940)
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:89 +0x60
created by github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:90 +0x70

goroutine 537 [IO wait, 4 minutes]:
net.runtime_pollWait(0x7fc7b1fcd890, 0x72, 0x7fc7b4064050)
	/tmp/workdir/go/src/runtime/netpoll.go:157 +0x63
net.(*pollDesc).Wait(0xc8201f8ae0, 0x72, 0x0, 0x0)
	/tmp/workdir/go/src/net/fd_poll_runtime.go:73 +0x56
net.(*pollDesc).WaitRead(0xc8201f8ae0, 0x0, 0x0)
	/tmp/workdir/go/src/net/fd_poll_runtime.go:78 +0x44
net.(*netFD).accept(0xc8201f8a80, 0x0, 0x7fc7b406a148, 0xc8202da260)
	/tmp/workdir/go/src/net/fd_unix.go:408 +0x2f6
net.(*TCPListener).AcceptTCP(0xc820026040, 0x60ce50, 0x0, 0x0)
	/tmp/workdir/go/src/net/tcpsock_posix.go:254 +0x77
--
github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker.func1(0xc8201380e0, 0xc8202eb500)
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:89 +0x60
created by github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:90 +0x70

goroutine 561 [select, 4 minutes]:
github.com/cockroachdb/cockroach/storage.(*baseQueue).processLoop.func1()
	/go/src/github.com/cockroachdb/cockroach/storage/queue.go:319 +0x427
github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker.func1(0xc8201380e0, 0xc8202da900)
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:89 +0x60
created by github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:90 +0x70
FAIL	github.com/cockroachdb/cockroach/storage	300.076s
=== RUN   TestBatchBasics
I0108 08:59:42.867505 997 storage/engine/rocksdb.go:137  closing in-memory rocksdb instance
--- PASS: TestBatchBasics (0.00s)
=== RUN   TestBatchGet
I0108 08:59:42.870874 997 storage/engine/rocksdb.go:137  closing in-memory rocksdb instance
--- PASS: TestBatchGet (0.01s)
=== RUN   TestBatchMerge
I0108 08:59:42.876840 997 storage/engine/rocksdb.go:137  closing in-memory rocksdb instance
--- PASS: TestBatchMerge (0.00s)
=== RUN   TestBatchProto

```
Please assign, take a look and update the issue accordingly.

### PR DESCRIPTION
**Pull request by dt**
Fixes #3694

[Review on Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/3710)

### CODE REVIEW

File: storage/store.go [hunk 1]
```diff
@@ -767,10 +768,12 @@ func (s *Store) DisableRaftLogQueue(disabled bool) {
 func (s *Store) ForceRaftLogScanAndProcess(t util.Tester) {
 	// Add each range to the queue.
 	s.mu.RLock()
-	for _, r := range s.replicas {
+	replicas := s.replicas
```
Comment (bdarnell) [inline storage/store.go]: This just copies a pointer, not the underlying map, so it is still racy to access `replicas` outside the lock. You need to copy the contents of `s.replicas` into a local slice or map before unlocking s.mu. 

Add a comment that this is pattern is necessary for `ForceRaftLogScanAndProcess` but not the other `ForceXScan` methods because the raft log queue calls back into `Store`. (although if you wanted to refactor this into a single `ForceScanQueueAndProcess` that could work for all queues, it would be fine to apply this pattern to all of them).

**Comment by dt** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[storage/store.go, line 771 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3710#-K7XhUd2-qokOdkU315m-r1-771:-K7Xkw-ul-DlBz3gny8l:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/438b2d25e02bd26e58855c2602537e95717c679b/storage/store.go#L771)):*
Done.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/3710)*

**Comment by bdarnell** [comment]
LGTM

File: storage/store.go [hunk 2]
```diff
@@ -532,6 +532,7 @@ func (s *Store) Start(stopper *stop.Stopper) error {
 			// and initialize those groups.
 			return false, nil
 		}); err != nil {
+		s.mu.Unlock()
```
Comment (BramGruneir) [inline storage/store.go]: Might it be better to turn the iterator into a sub function with a defer unlock at the start?

**Comment by BramGruneir** [comment]
One suggestion, but otherwise lgtm.

**Comment by dt** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---

*[storage/store.go, line 535 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3710#-K7XhUd2-qokOdkU315m-r2-535:-K7Xu4ZyAzSgaMjN8JrZ:-357419442) ([raw file](https://github.com/cockroachdb/cockroach/blob/cb65190f9caaf464723e7d072b1f1b69a044ef7b/storage/store.go#L535)):*
fwiw, this wasn't causing the deadlocks -- I just included it here for completeness.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/3710)*

File: storage/store.go [hunk 3]
```diff
@@ -765,13 +766,21 @@ func (s *Store) DisableRaftLogQueue(disabled bool) {
 // need their raft logs truncated and then process each of them.
 // Exposed only for testing.
 func (s *Store) ForceRaftLogScanAndProcess(t util.Tester) {
-	// Add each range to the queue.
+	// MaybeAdd can transitively call back into Store (namely RaftStatus) and end up
+	// attempting to re-acquire mu.RLock, making a deadlock is possible (if Lock called in-between).
```
Comment (tamird) [inline storage/store.go]: remove "is"

**Comment by tschottdorf** [comment]
This is the first time I've seen this `RLock() - Lock() - RLock()` type deadlock and I missed it looking at the traces for quite a bit. Makes me think that we should try to dial down the use of `RLock` until we see contention on the mutex (ideally just use a `Mutex`). @BramGruneir, you've looked at the locking story recently - do you think that's a worthwhile/realistic goal?

Thanks for the fix, @dt.

**Comment by bdarnell** [comment]
+1 to discouraging use of `RLock` without specific motivation.

**Comment by tschottdorf** [comment]
Is that also a `+1` to for `store.mu` to become a `Mutex`? I'm going to file an issue.

**Comment by dt** [comment]
RLock presumably reduces expected reader wait times.. the correctness issue is just treating it as reentrant when it isn't. I wonder there's a way to get the best of both worlds, by testing with a stricter mutex but continuing to use an RwMutex at runtime.

**Comment by dt** [comment]
Alternately I wonder if there's a way to look at stacks to see when an RLock is being treated as reentrant... sometimes (very rarely) I miss thread-local storage.

**Comment by bdarnell** [comment]
I would definitely make `Replica` use a `Mutex`. `Store.mu` makes a little more sense as a `RWMutex` since we intend to increase parallelism in the future, but it might be worth changing it to a `Mutex` for more immediate deadlock detection. `Store.mu` is on my hit list anyway; I need to refactor locking and the use of the `processRaft` goroutine.

@dt I've wanted to replace all our `sync.Mutexes` with a wrapper that adds an `AssertHeld` method; we could use a similar technique with build tags to replace `RWMutex` with a stricter version in some builds.

Maybe one day I'll get around to writing a go version of http://clang.llvm.org/docs/ThreadSafetyAnalysis.html

**Comment by BramGruneir** [comment]
I've already started work on adding an AssertHeld method for replica.  I'd like to try keeping it as an RWMutex with the added protection before giving up and converting it to just a mutex.

I'll convert it to a util class that can be used instead of a normal rwmutex so it can be reused.

**Comment by tschottdorf** [comment]
@dt 

> RLock presumably reduces expected reader wait times..

that's not necessarily true, a `RWMutex` also has some performance hit over a plain `Mutex` so it really depends. Agreed that store.mu looks like it could benefit from it, but that seems like an easy change to make when we find it matters.

> I wonder there's a way to get the best of both worlds, by testing with a stricter mutex but continuing to use an RwMutex at runtime.

Yes, you can expose the read-lock part of the `RWMutex` as a `sync.Locker` and hide the corresponding write-locker behind it with only when building with the test build tag. But that sounds like premature optimization when you can just use a `sync.Mutex` in the first place and there is no measurable performance penalty.

Of course it's possible that our locking is already twisted enough so that `sync.Mutex` is hard. But that would be an indicator that we need to simplify.

@BramGruneir 

> I've already started work on adding an AssertHeld method for replica. I'd like to try keeping it as an RWMutex with the added protection before giving up and converting it to just a mutex.

To me, keeping the `RWMutex` feels like giving up. Also curious how you're going to implement `AssertHeld` on a `RWMutex` without wrapping it into something with overhead (hence back to the thought of premature optimization). Am I overlooking something there?

**Comment by tschottdorf** [comment]
BTW, "back in the day" I came across a patch to the `sync` package which added real deadlock protection - it would track all the locks held and requested, and whenever there was a dependency cycle it would panic. This was just a hack then, but it just seemed useful to have. This could also be pulled out into an external package and some buildtag magic could possibly make that a drop-in replacement for vanilla `sync.{RW,}Mutex` with overhead only in tests. If someone's interested, I could dig it back up. But my feeling is that at this point investing energy in a simpler locking story beats coming up with more elaborate schemes.

**Comment by BramGruneir** [comment]
@tschottdorf 
For lock, it was a local bool showing a lock exists.
For rlock, it is an atomic counter, that adds and removes accordingly.  
I also wanted to put in v8 level logging to show who held/removed each lock.  Like I said, I had just started it. 
Does it add overhead?  Indeed.  But I don't think it adds that much (and could be easily removed).  Anyway, I might tinker with it a bit more, but I have no problem stripping the rlock stuff and going with just a normal lock.

**Comment by petermattis** [comment]
If you haven't done so, you should take a look at the [sync.RWMutex implementation](https://github.com/golang/go/blob/master/src/sync/rwmutex.go#L35).

**Comment by RaduBerinde** [comment]
I don't have the particular context here but I have dealt with RW Lock issues before so some of my conclusions could be helpful. Sorry in advance if some of this stuff is irrelevant.

RWLocks can provide different semantics, I have seen three implementations:

1. Read-preferring: If some readers have the lock, new readers are always allowed, even if a writer is waiting. This is a simple implementation but it can lead to indefinite writer starvation if readers keep coming and going.

2. In-between: Once a writer is waiting, no new readers get the lock until existing readers release. When the last reader releases, everybody gets woken up and waiting readers and writers all get a chance. This is what the C++ boost shared_mutex implementation does (last I checked anyway).

3. Write-preferring: Once a writer is waiting, no new readers get the lock. When the last reader releases, the writer gets the lock. Looks like this is what sync.RWMutex does if I am correctly reading the code.

The read-preferring implementation is not only reentrant (for read locking) but it allows you to acquire and release different read locks in whatever order without deadlock! That can actually pretty bad as after enough code that unintentionally relies on this is written you won't be able to change the implementation (e.g. if you find that writer starvation is an issue). Unfortunately even with the other implementations, improper read lock ordering can go unnoticed until the right sequence of events happens.

One way to solve this problem is lock ranking - every lock has a statically defined rank and the ranks of the locks that a thread grabs must always be monotonic. Defining ranks can be a bit of a pain but it forces one to have a good idea of how the locks interoperate. Checking the ranking at runtime requires maintaining the current rank per-thread. From what I can tell, this cannot be done in go without either passing a context around (https://blog.golang.org/context) or some terrible hacks (https://github.com/jtolds/gls). Lock ranking also requires that threads are released by the same context which acquired them, which prevents some otherwise legitimate patterns.

Even without implementing "full" lock ranking, it is easy to detect reentrant locking if we can somehow store the set of readlocks the current thread/context is holding.

---







*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/3710#-:-K7iZqBcN2EOWiIWMk4v:-599156208)*
