### PR TITLE
tree: improve type-checking of ParenExprs

### LINKED ISSUE #94092: sql: query triggers Internal Error
**Describe the problem**

The latest version of the CockroachDB (ce9c9bc9b0bb) shows `Internal Error` when executing the following query:

```sql
CREATE TABLE v0 (c1 INT);
INSERT INTO v0 VALUES (123);
SELECT (c1, 123) != (()) FROM v0;
```

**To Reproduce**

Here is the detail steps to reproduce the bug.

1. In operating system Ubuntu 20.04, download the CockroachDB source code from the github source.
2. Use the latest version of the CockroachDB code (tested version: ce9c9bc9b0bb)
3. Directly `make install` in the root repository folder. 
4. Run `./cockroach demo`, and then paste the PoC query to the cockroach cli environment.
5. Observe the `Internal Error` and log the stack information. 

**Expected behavior**
The `SELECT` statement should return an empty result. 

**Additional data / screenshots**

Here is the outputted stack trace:

```
ERROR: internal error: unexpected error from the vectorized engine: runtime error: index out of range [0] with length 0
SQLSTATE: XX000
DETAIL: stack trace:
github.com/cockroachdb/cockroach/pkg/sql/colexecerror/error.go:89: func1()
runtime/panic.go:884: gopanic()
runtime/panic.go:113: goPanicIndex()
github.com/cockroachdb/cockroach/pkg/sql/sem/eval/binary_op.go:173: EvalCompareTupleOp()
github.com/cockroachdb/cockroach/pkg/sql/sem/tree/eval_op_generated.go:301: Eval()
github.com/cockroachdb/cockroach/pkg/sql/sem/eval/binary_op.go:40: BinaryOp()
github.com/cockroachdb/cockroach/pkg/sql/colexec/colexeccmp/default_cmp_expr.eg.go:59: Eval()
github.com/cockroachdb/cockroach/pkg/sql/colexec/colexecprojconst/default_cmp_proj_const_op.eg.go:56: func1()
github.com/cockroachdb/cockroach/pkg/sql/colmem/allocator.go:441: PerformOperation()
github.com/cockroachdb/cockroach/pkg/sql/colexec/colexecprojconst/default_cmp_proj_const_op.eg.go:45: Next()
github.com/cockroachdb/cockroach/pkg/sql/colexec/colexecbase/simple_project.go:124: Next()
github.com/cockroachdb/cockroach/pkg/sql/colflow/stats.go:116: next()
github.com/cockroachdb/cockroach/pkg/sql/colexecerror/error.go:92: CatchVectorizedRuntimeError()
github.com/cockroachdb/cockroach/pkg/sql/colflow/stats.go:124: Next()
github.com/cockroachdb/cockroach/pkg/sql/colflow/flow_coordinator.go:252: nextAdapter()
github.com/cockroachdb/cockroach/pkg/sql/colexecerror/error.go:92: CatchVectorizedRuntimeError()
github.com/cockroachdb/cockroach/pkg/sql/colflow/flow_coordinator.go:256: next()
github.com/cockroachdb/cockroach/pkg/sql/colflow/flow_coordinator.go:294: Run()
github.com/cockroachdb/cockroach/pkg/sql/colflow/vectorized_flow.go:309: Run()
github.com/cockroachdb/cockroach/pkg/sql/distsql_running.go:815: Run()
github.com/cockroachdb/cockroach/pkg/sql/distsql_running.go:1783: PlanAndRun()
github.com/cockroachdb/cockroach/pkg/sql/distsql_running.go:1535: PlanAndRunAll()
github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:1625: execWithDistSQLEngine()
github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:1245: dispatchToExecutionEngine()
github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:737: execStmtInOpenState()
github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:130: func1()
github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:2514: execWithProfiling()
github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:129: execStmt()
github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:1955: func1()
github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:1960: execCmd()
github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:1878: run()
github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:834: ServeConn()

HINT: You have encountered an unexpected error.
```

**Environment:**
 - CockroachDB version: v23.1.0-alpha
 - Server OS: Ubuntu 20.04 LTS
 - Client app: CockroachDB demo command. (`./cockroach demo`)
 - Detailed CockroachDB version output:

```
cockroach version details:
Build Tag:        v23.1.0-alpha.1-255-gce9c9bc9b0
Build Time:       2022/12/21 18:42:53
Distribution:     CCL
Platform:         linux amd64 (x86_64-linux-gnu)
Go Version:       go1.19
C Compiler:       gcc 9.4.0
Build Commit ID:  ce9c9bc9b0bb3d2226d6326240d57539b4c99648
Build Type:       development
```

**Additional context**

The Internal Error problem is reproducible on version `v23.1 alpha`, `v22.2.0 Production Releases` and `v22.1.*`.

### PR DESCRIPTION
**Pull request by yuzefovich**
This commit makes it so that we strip parenthesis from `ParenExpr` when
type-checking a comparison op. We already do that (since 2017) in
`typeCheckComparisonOpWithSubOperator`, so it seems reasonable to also
do it in the other spot. This is needed in order for other logic (like
when handling tuple equality) to kick in.

Fixes: #94092.

Release note: None

### CODE REVIEW

**Comment by yuzefovich** [comment]
I have little confidence in this area of the code base. We could make the fix more targeted (i.e. only unwrap `ParenExpr`s if it has a `TupleExpr` inside). Curious to hear the feedback.

File: pkg/sql/sem/tree/type_check.go [hunk 1]
```diff
@@ -2175,16 +2175,27 @@ func typeCheckSubqueryWithIn(left, right *types.T) error {
 func typeCheckComparisonOp(
 	ctx context.Context, semaCtx *SemaContext, op treecmp.ComparisonOperator, left, right Expr,
 ) (_ TypedExpr, _ TypedExpr, _ *CmpOp, alwaysNull bool, _ error) {
+	// If we have a ParenExpr, unwrap it right away - we would do it anyway in
+	// ParenExpr.TypeCheck, but it could be too late for other logic in this
+	// method to kick in.
+	if p, ok := left.(*ParenExpr); ok {
```
Comment (rafiss) [inline pkg/sql/sem/tree/type_check.go:2181]: consider using `tree.StripParens` here -- it will recursively unwrap the parentheses

**Review by rafiss — COMMENTED** [review]
this change looks pretty safe to me, but i left one suggestion

**Review by yuzefovich — COMMENTED** [review]
TFTR!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/94974#-:-NLSSXCGCoVrQ0m2BYC7:b-814g8k)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @mgartner and @rafiss)

___
*[`pkg/sql/sem/tree/type_check.go` line 2181 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/94974#-NLOpgEPMcNczUHAXZQY-r1-2181:-NLSSPPW4O3DMWkxkD3w:b96ja48) ([raw file](https://github.com/cockroachdb/cockroach/blob/a6324c44f463ee025c13f13f3c8983db7a2d1395/pkg/sql/sem/tree/type_check.go#L2181)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

consider using `tree.StripParens` here -- it will recursively unwrap the parentheses
</blockquote></details>

Done. We actually already do this in `typeCheckComparisonOpWithSubOperator`, so now I'm more confident that the change is the right one to make and safe.

**Review by rafiss — APPROVED** [review]
