### PR TITLE
sqlstats: fix data race between collector and ingester

### LINKED ISSUE #146796: cli: TestImportCLI failed [data race in `StatsCollector` between `SQLStatsIngester`]
cli.TestImportCLI [failed](https://tanzanite.cluster.engflow.com/invocations/default/91b9b16a-383e-4c17-acfe-afd3c63cbda9?testReportRun=3&testReportShard=15&testReportAttempt=1#targets-Ly9wa2cvY2xpOmNsaV90ZXN0) on master @ [52c0072ad3c389a0c3146891c48c07ae137450fe](https://github.com/cockroachdb/cockroach/commits/52c0072ad3c389a0c3146891c48c07ae137450fe):

```
      pkg/sql/pgwire/server.go:970 +0xea4
  github.com/cockroachdb/cockroach/pkg/server.(*systemServerWrapper).serveConn()
      pkg/server/server_controller_sql.go:169 +0x19e
  github.com/cockroachdb/cockroach/pkg/server.(*serverController).sqlMux()
      pkg/server/server_controller_sql.go:90 +0x50b
  github.com/cockroachdb/cockroach/pkg/server.(*serverController).sqlMux-fm()
      <autogenerated>:1 +0xc4
  github.com/cockroachdb/cockroach/pkg/server.startServeSQL.func1.1()
      pkg/server/server_sql.go:1983 +0x39b
  github.com/cockroachdb/cockroach/pkg/util/netutil.(*TCPServer).ServeWith.func1()
      pkg/util/netutil/net.go:189 +0x1c6
  github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunAsyncTaskEx.func1()
      pkg/util/stop/stopper.go:438 +0x115
  github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunAsyncTaskEx.gowrap1()
      pkg/util/stop/stopper.go:439 +0x4f

Goroutine 3507 (running) created at:
  github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunAsyncTaskEx()
      pkg/util/stop/stopper.go:436 +0x24e
  github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunAsyncTask()
      pkg/util/stop/stopper.go:359 +0x1ba
  github.com/cockroachdb/cockroach/pkg/sql/sqlstats/sslocal.(*SQLStatsIngester).Start()
      pkg/sql/sqlstats/sslocal/sql_stats_ingestor.go:125 +0xaa
  github.com/cockroachdb/cockroach/pkg/sql.(*Server).Start()
      pkg/sql/conn_executor.go:683 +0xd4
  github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*Server).Start()
      pkg/sql/pgwire/server.go:512 +0x11a4
  github.com/cockroachdb/cockroach/pkg/server.(*SQLServer).preStart()
      pkg/server/server_sql.go:1630 +0x1135
  github.com/cockroachdb/cockroach/pkg/server.(*topLevelServer).PreStart()
      pkg/server/server.go:2046 +0x5424
  github.com/cockroachdb/cockroach/pkg/server.(*testServer).PreStart()
      pkg/server/testserver.go:839 +0x104
  github.com/cockroachdb/cockroach/pkg/server.(*testServer).Start()
      pkg/server/testserver.go:917 +0xca
  github.com/cockroachdb/cockroach/pkg/testutils/serverutils.(*wrap).Start()
      bazel-out/k8-fastbuild/bin/pkg/testutils/serverutils/ts_control_forwarder_generated.go:14 +0x72
  github.com/cockroachdb/cockroach/pkg/testutils/serverutils.StartServerOnlyE()
      pkg/testutils/serverutils/test_server_shim.go:274 +0x271
  github.com/cockroachdb/cockroach/pkg/cli.newCLITestWithArgs()
      testutils.go:179 +0x9f3
  github.com/cockroachdb/cockroach/pkg/cli.NewCLITest()
      testutils.go:132 +0x104
  github.com/cockroachdb/cockroach/pkg/cli.TestImportCLI()
      import_test.go:89 +0x68
  testing.tRunner()
      GOROOT/src/testing/testing.go:1690 +0x226
  testing.(*T).Run.gowrap1()
      GOROOT/src/testing/testing.go:1743 +0x44
==================
```

Parameters:
 - <code>attempt=1</code>
 - <code>race=true</code>
 - <code>run=3</code>
 - <code>shard=15</code>
<details><summary>Help</summary>
<p>

See also: [How To Investigate a Go Test Failure \(internal\)](https://cockroachlabs.atlassian.net/l/c/HgfXfJgM)
</p>
</details>
/cc @cockroachdb/sql-foundations @cockroachdb/server
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*TestImportCLI.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/bazci/githubpost/issues)

</sub>

Jira issue: CRDB-50711

### PR DESCRIPTION
**Pull request by dhartunian**
I've admittedly not been able to reproduce the data race observed in the same `*sqlstats.RecordedStmtStats` object in two different locations. One of these is now redunant. The transactionID set in the `StatsCollector` happens before the data is processed by the `SQLStatsIngester` so the setting of the transactionID in the ingester is removed. If it happens to get statements without corresponding transactionIDs, that should be a bug.

The reason this was introduced was likely
https://github.com/cockroachdb/cockroach/pull/141767 which unified the types used by the two components. Previously, they were different structs and ownership was clear and required editing the transactionID twice.

This PR also introduces a `doc.go` file to the `sslocal` package in an effort to guide the reviewer and provide context for future work. The diagram reflects the changes in this commit.

Resolves: #146796

Release note: None

### CODE REVIEW

**Review by alyshanjahani-crl — APPROVED** [review]

**Comment by dhartunian** [comment]
@alyshanjahani-crl added a test prior to my change and verified that it passes before my second commit.

I avoided making the test too contrived to force the race condition to show up, so it's more oriented towards setting expectations for the contract that the collector and ingester follow.

File: pkg/sql/sqlstats/sslocal/sql_stats_ingester_test.go [hunk 1]
```diff
@@ -349,3 +352,98 @@ func TestSQLIngester_ClearSession(t *testing.T) {
...
+			FingerprintID:            stmt.FingerprintID,
+			TransactionFingerprintID: stmt.TransactionFingerprintID,
+		})
+	}
+}
+
+// TestStatsCollectorIngester validates that all statements recorded as part of a
+// transaction through the StatsCollector are ingested into the SQLStatsIngester
+// with the correct TransactionFingerprintID.
+func TestStatsCollectorIngester(t *testing.T) {
```
Comment (alyshanjahani-crl) [inline pkg/sql/sqlstats/sslocal/sql_stats_ingester_test.go:386]: nice 👌

**Comment by dhartunian** [comment]
TFTR!

bors r=alyshanjahani-crl
