### PR TITLE
release-23.1: kvserver: deflake `TestRestoreReplicas`

### LINKED ISSUE #103251: kv/kvserver: TestRestoreReplicas failed
kv/kvserver.TestRestoreReplicas [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_StressBazel/10064002?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_StressBazel/10064002?buildTab=artifacts#/) on master @ [63eb6b86c1518fbed9db10e7d2afa1446b2b3b82](https://github.com/cockroachdb/cockroach/commits/63eb6b86c1518fbed9db10e7d2afa1446b2b3b82):

```
=== RUN   TestRestoreReplicas
    test_log_scope.go:161: test logs captured to: /artifacts/tmp/_tmp/33e1d369c27b9c01b2b6009c561815a3/logTestRestoreReplicas3865623463
    test_log_scope.go:79: use -show-logs to present logs inline
    client_raft_test.go:402: 
        	Error Trace:	github.com/cockroachdb/cockroach/pkg/kv/kvserver_test/pkg/kv/kvserver/client_raft_test.go:402
        	Error:      	Not equal: 
        	            	expected: 2
        	            	actual  : 1
        	Test:       	TestRestoreReplicas
    panic.go:540: -- test log scope end --
test logs left over in: /artifacts/tmp/_tmp/33e1d369c27b9c01b2b6009c561815a3/logTestRestoreReplicas3865623463
--- FAIL: TestRestoreReplicas (12.31s)
```
<p>Parameters: <code>TAGS=bazel,gss,race</code>
</p>
<details><summary>Help</summary>
<p>

See also: [How To Investigate a Go Test Failure \(internal\)](https://cockroachlabs.atlassian.net/l/c/HgfXfJgM)
</p>
</details>
/cc @cockroachdb/replication
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*TestRestoreReplicas.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)
</sub>

Jira issue: CRDB-27902

Epic CRDB-27234

### PR DESCRIPTION
**Pull request by erikgrinaker**
Backport 1/1 commits from #103342.

/cc @cockroachdb/release

---

We recently began eagerly initializing replicas on startup when using expiration-based leases. This can cause elections on startup such that the Raft leadership moves around for a bit before settling down at the leaseholder. This test expected the first store to be able to acquire Raft leadership and the lease, but that wouldn't hold if the second replica had already acquired leadership.

This patch changes the test to keep looking until a leaseholder is established.

Resolves #103251.
Epic: none

Release note: None

### CODE REVIEW

File: pkg/kv/kvserver/client_raft_test.go [hunk 1]
```diff
@@ -371,37 +371,39 @@ func TestRestoreReplicas(t *testing.T) {
...
-		if _, pErr := kv.SendWrapped(ctx, tc.GetFirstStoreFromServer(t, i).TestSender(), incArgs); pErr != nil {
-			failures++
-			if _, ok := pErr.GetDetail().(*kvpb.NotLeaseHolderError); !ok {
-				t.Fatalf("expected not lease holder error; got %s", pErr)
+	testutils.SucceedsSoon(t, func() error {
+		var pErr *kvpb.Error
+		for i := 0; i < tc.NumServers(); i++ {
+			_, pErr = kv.SendWrapped(ctx, tc.GetFirstStoreFromServer(t, i).TestSender(), incArgs)
+			if pErr == nil {
+				followerStore = tc.GetFirstStoreFromServer(t, 1-i)
```
Comment (aliher1911) [inline pkg/kv/kvserver/client_raft_test.go:392]: nit: `1-i` is a code golf so deserves a comment as it is not immediately obvious that tc.NumServers() == 2 and you just get another remaining node.

**Review by aliher1911 — APPROVED** [review]

File: pkg/kv/kvserver/client_raft_test.go (hunk 1 above)
Comment (erikgrinaker) [reply pkg/kv/kvserver/client_raft_test.go:392]: Too late, this is just a backport and has already merged to master.
