### PR TITLE
changefeedccl: add metrics for number of job failures and running feeds

### LINKED ISSUE #53130: changefeed: metric for failure, gauge for running
Many of our customers rely on our Prometheus endpoint for monitoring and alerting. For changefeeds, we have `changefeed_error_retries` on when we encounter retriable errors, and `changefeed.max_behind_nanos` to see if it's falling too far behind.

But if it fails permanently, we don't have a way to make them aware short of asking them to run a SQL command or check AdminUI, which isn't always possible and/or easy and we shouldn't expect users to do that (e.g. create their own endpoint that runs show jobs and returns the output).

** Deliverable **
- Add gauge for "running" changefeeds
- Add metric for "failed" changefeeds that transition to failed state

### PR DESCRIPTION
**Pull request by ajwerner**
This commit adds two new metrics:
1) changefeeds.running - gauge of the number of running CHANGEFEEDs both
     as jobs and sinkless
    
 2) changefeeds.failures - counter of the number of permanent failures of
    CHANGEFEED jobs.

Fixes #53130.
    
Release note (enterprise change): Added metrics to track the current number
of running CHANGEFEEDs and the number of failed CHANGEFEED jobs.

### CODE REVIEW

**Comment by ajwerner** [comment]
cc @mwang1026 LMK what you think about the gauge and its relationship to sinkless. I can split it out into two gauges if you'd prefer.

**Comment by mwang1026** [comment]
I don't think we need to split it out but I can check some metrics quickly. My hunch is that most people do one or the other type of changefeed.

In general what's the way to think about metrics and "breaking" changes? We should avoid them?

File: pkg/ccl/changefeedccl/changefeed_processors.go [hunk 1]
```diff
@@ -622,6 +623,9 @@ func (cf *changeFrontier) closeMetrics() {
 	// Delete this feed from the MaxBehindNanos metric so it's no longer
 	// considered by the gauge.
 	cf.metrics.mu.Lock()
+	if cf.metricsID > 0 {
+		cf.metrics.Running.Dec(1)
```
Comment (dt) [inline pkg/ccl/changefeedccl/changefeed_processors.go:627]: huh, how does this play with node crashes?

**Comment by mwang1026** [comment]
Metrics say people stick to one sink so I think one combined gauge is fine.

re: Changefeed failures, is that only enterprise changefeeds since they're the only ones that create jobs? I guess with Core if you lose a connection you can kinda know.

**Review by miretskiy — APPROVED** [review]

File: pkg/ccl/changefeedccl/changefeed_processors.go (hunk 1 above)
Comment (ajwerner) [reply pkg/ccl/changefeedccl/changefeed_processors.go:627]: I think it plays well. `Running` is a gauge, not a counter, so when a node crashes it goes to zero for that node.

**Comment by ajwerner** [comment]
> re: Changefeed failures, is that only enterprise changefeeds since they're the only ones that create jobs? I guess with Core if you lose a connection you can kinda know.

Indeed, that was my thinking. Core changefeeds aren't pets the way enterprise changefeeds are.

**Review by dt — APPROVED** [review]

**Comment by ajwerner** [comment]
TFTR!

bors r+
