### PR TITLE
kvserver: deflake TestReplicaCircuitBreaker_ExemptRequests

### LINKED ISSUE #140363: kv/kvserver: TestReplicaCircuitBreaker_ExemptRequests failed
kv/kvserver.TestReplicaCircuitBreaker_ExemptRequests [failed](https://tanzanite.cluster.engflow.com/invocations/default/bb5dd123-bba5-4fb4-888e-eb726d758ec3?testReportRun=2&testReportShard=30&testReportAttempt=1#targets-Ly9wa2cva3Yva3ZzZXJ2ZXI6a3ZzZXJ2ZXJfdGVzdA==) on master @ [507c68f8abb0c9a3f527c66cb42129c2cb096e7d](https://github.com/cockroachdb/cockroach/commits/507c68f8abb0c9a3f527c66cb42129c2cb096e7d):

```
          1421.994ms   1421.758ms    event:kv/kvserver/replica_send.go:190 [n1,s1,r75/1:/{Table/Max-Max}] replica.Send got error: result is ambiguous: replica unavailable: (n1,s1):1 unable to serve request to r75:/{Table/Max-Max} [(n1,s1):1, (n2,s2):2, next=3, gen=3, sticky=9223372036.854775807,2147483647]: lost quorum (down: (n2,s2):2); closed timestamp: 1738575736.643927123,0 (2025-02-03 09:42:16); raft status: {"id":"1","term":6,"vote":"1","commit":31,"lead":"0","leadEpoch":"0","raftState":"StateFollower","applied":31,"progress":{},"leadtransferee":"0"}: have been waiting 1.50s for slow proposal Put [/Table/Max]
    client_replica_circuit_breaker_test.go:733: result is ambiguous: replica unavailable: (n1,s1):1 unable to serve request to r75:/{Table/Max-Max} [(n1,s1):1, (n2,s2):2, next=3, gen=3, sticky=9223372036.854775807,2147483647]: lost quorum (down: (n2,s2):2); closed timestamp: 1738575736.643927123,0 (2025-02-03 09:42:16); raft status: {"id":"1","term":6,"vote":"1","commit":31,"lead":"0","leadEpoch":"0","raftState":"StateFollower","applied":31,"progress":{},"leadtransferee":"0"}: have been waiting 1.50s for slow proposal Put [/Table/Max]
    client_replica_circuit_breaker_test.go:1411: info:
             0.000ms      0.000ms    === operation:SendCtx(Get) _verbose:1
             0.078ms      0.078ms    event:kv/kvserver/replica_send.go:171 [n1,s1,r75/1:/{Table/Max-Max}] read-only path
             0.126ms      0.048ms    event:kv/kvserver/concurrency/concurrency_manager.go:209 [n1,s1,r75/1:/{Table/Max-Max}] sequencing request
             0.166ms      0.040ms    event:kv/kvserver/concurrency/concurrency_manager.go:290 [n1,s1,r75/1:/{Table/Max-Max}] acquiring latches
             0.255ms      0.089ms    event:kv/kvserver/spanlatch/manager.go:580 [n1,s1,r75/1:/{Table/Max-Max}] waiting to acquire read latch /Table/Max@1738575741.075751292,0 for request Get [/Table/Max], held by write latch /Table/Max@1738575739.652649202,0 for request Put [/Table/Max]
             1.128ms      0.873ms    event:kv/kvserver/replica_send.go:190 [n1,s1,r75/1:/{Table/Max-Max}] replica.Send got error: replica unavailable: (n1,s1):1 unable to serve request to r75:/{Table/Max-Max} [(n1,s1):1, (n2,s2):2, next=3, gen=3, sticky=9223372036.854775807,2147483647]: lost quorum (down: (n2,s2):2); closed timestamp: 1738575736.643927123,0 (2025-02-03 09:42:16); raft status: {"id":"1","term":6,"vote":"1","commit":31,"lead":"0","leadEpoch":"0","raftState":"StateFollower","applied":31,"progress":{},"leadtransferee":"0"}: encountered poisoned latch /Table/Max@1738575739.652649202,0
    client_replica_circuit_breaker_test.go:734: replica unavailable: (n1,s1):1 unable to serve request to r75:/{Table/Max-Max} [(n1,s1):1, (n2,s2):2, next=3, gen=3, sticky=9223372036.854775807,2147483647]: lost quorum (down: (n2,s2):2); closed timestamp: 1738575736.643927123,0 (2025-02-03 09:42:16); raft status: {"id":"1","term":6,"vote":"1","commit":31,"lead":"0","leadEpoch":"0","raftState":"StateFollower","applied":31,"progress":{},"leadtransferee":"0"}: encountered poisoned latch /Table/Max@1738575739.652649202,0
    --- FAIL: TestReplicaCircuitBreaker_ExemptRequests/lease-type=LeaseLeader (5.06s)
=== RUN   TestReplicaCircuitBreaker_ExemptRequests/lease-type=LeaseLeader/with-unavailable-lease/AddSSTable
    client_replica_circuit_breaker_test.go:1411: info:
             0.000ms      0.000ms    === operation:SendCtx(AddSSTable) _verbose:1
            39.115ms     39.115ms    event:kv/kvserver/replica_send.go:175 [n1,s1,r75/1:/{Table/Max-Max}] read-write path
            42.140ms      3.025ms    event:kv/kvserver/replica_send.go:190 [n1,s1,r75/1:/{Table/Max-Max}] replica.Send got error: aborted during Replica.Send: context deadline exceeded
    client_replica_circuit_breaker_test.go:698: aborted during Replica.Send: context deadline exceeded
    client_replica_circuit_breaker_test.go:704: 
        	Error Trace:	pkg/kv/kvserver/client_replica_circuit_breaker_test.go:704
        	            				pkg/kv/kvserver/client_replica_circuit_breaker_test.go:1142
        	Error:      	Received unexpected error:
        	            	aborted during Replica.Send: context deadline exceeded
        	            	(1)
        	            	  | (opaque error wrapper)
        	            	  | type name: github.com/cockroachdb/errors/withstack/*withstack.withStack
        	            	  | reportable 0:
        	            	  |
        	            	  | github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*Replica).executeBatchWithConcurrencyRetries
        	            	  | 	pkg/kv/kvserver/replica_send.go:431
        	            	  | github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*Replica).SendWithWriteBytes
        	            	  | 	pkg/kv/kvserver/replica_send.go:177
        	            	  | github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*Replica).Send
        	            	  | 	pkg/kv/kvserver/replica_send.go:115
        	            	  | github.com/cockroachdb/cockroach/pkg/kv/kvserver_test.(*circuitBreakerTest).SendCtxTS
        	            	  | 	pkg/kv/kvserver/client_replica_circuit_breaker_test.go:1293
        	            	  | github.com/cockroachdb/cockroach/pkg/kv/kvserver_test.(*circuitBreakerTest).SendCtx
        	            	  | 	pkg/kv/kvserver/client_replica_circuit_breaker_test.go:1256
        	            	  | github.com/cockroachdb/cockroach/pkg/kv/kvserver_test.TestReplicaCircuitBreaker_ExemptRequests.func1.9
        	            	  | 	pkg/kv/kvserver/client_replica_circuit_breaker_test.go:693
        	            	  | github.com/cockroachdb/cockroach/pkg/kv/kvserver_test.(*circuitBreakerTest).Run.func1
        	            	  | 	pkg/kv/kvserver/client_replica_circuit_breaker_test.go:1142
        	            	  | testing.tRunner
        	            	  | 	GOROOT/src/testing/testing.go:1689
        	            	  | runtime.goexit
        	            	  | 	src/runtime/asm_amd64.s:1695
        	            	Wraps: (2) aborted during Replica.Send
        	            	Wraps: (3) context deadline exceeded
        	            	Error types: (1) *errbase.opaqueWrapper (2) *errutil.withPrefix (3) context.deadlineExceededError
        	Test:       	TestReplicaCircuitBreaker_ExemptRequests/lease-type=LeaseLeader/with-unavailable-lease/AddSSTable
        --- FAIL: TestReplicaCircuitBreaker_ExemptRequests/lease-type=LeaseLeader/with-unavailable-lease/AddSSTable (0.06s)
```

Parameters:
 - <code>attempt=1</code>
 - <code>deadlock=true</code>
 - <code>run=2</code>
 - <code>shard=30</code>
<details><summary>Help</summary>
<p>

See also: [How To Investigate a Go Test Failure \(internal\)](https://cockroachlabs.atlassian.net/l/c/HgfXfJgM)
</p>
</details>
/cc @cockroachdb/kv-triage
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*TestReplicaCircuitBreaker_ExemptRequests.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/bazci/githubpost/issues)

</sub>

Jira issue: CRDB-47128

### PR DESCRIPTION
**Pull request by iskettaneh**
This test uses a very small context deadline when running the exemptRequests requests. However, it sometimes takes a longer time with leader leases in deadlock runs.

Release note: None

Fixes: #140363

### CODE REVIEW

File: pkg/kv/kvserver/client_replica_circuit_breaker_test.go [hunk 1]
```diff
@@ -605,6 +605,12 @@ func TestReplicaCircuitBreaker_ExemptRequests(t *testing.T) {
 	defer log.Scope(t).Close(t)
 	testutils.RunValues(t, "lease-type", roachpb.EpochAndLeaderLeaseType(),
 		func(t *testing.T, leaseType roachpb.LeaseType) {
+			if leaseType == roachpb.LeaseLeader {
```
Comment (pav-kv) [inline pkg/kv/kvserver/client_replica_circuit_breaker_test.go:608]: Would increasing the timeout help? Is that the one in this line:
https://github.com/cockroachdb/cockroach/blob/416e2691fd0f0cbde1931905e8aefbb7bbfb39a7/pkg/kv/kvserver/client_replica_circuit_breaker_test.go#L689

Easy way to check: set it notoriously low and see if the test starts failing.

Comment (iskettaneh) [reply pkg/kv/kvserver/client_replica_circuit_breaker_test.go:608]: Increasing the timeout seems to help. Setting it to 1-2 seconds seems to have stabilized the test. However, it made the test take a long time to finish because it runs many operations. I might try to increase it just for leader leases and see if it causes an increased test runtime or not

**Review by iskettaneh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/141618)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @arulajmani and @pav-kv)

**Review by pav-kv — APPROVED** [review]

**Comment by iskettaneh** [comment]
TFTR!

bors r+

**Comment by iskettaneh** [comment]
blathers backport 25.1
