### PR TITLE
backupccl: fix TestProtectedTimestampSpanSelectionDuringBackup

### LINKED ISSUE #57546: ccl/backupccl: TestProtectedTimestampSpanSelectionDuringBackup failed
[(ccl/backupccl).TestProtectedTimestampSpanSelectionDuringBackup failed](https://teamcity.cockroachdb.com/viewLog.html?buildId=2495086&tab=buildLog) on [master@aa69b42032f89d1bb777986ff7a8d4f753b71d83](https://github.com/cockroachdb/cockroach/commits/aa69b42032f89d1bb777986ff7a8d4f753b71d83):

```
=== RUN   TestProtectedTimestampSpanSelectionDuringBackup
    test_log_scope.go:72: test logs captured to: /go/src/github.com/cockroachdb/cockroach/artifacts/logTestProtectedTimestampSpanSelectionDuringBackup898532731
    test_log_scope.go:73: use -show-logs to present logs inline
n1: found liveness
n2: found liveness
n3: found liveness
=== CONT  TestProtectedTimestampSpanSelectionDuringBackup
    backup_test.go:5864: -- test log scope end --
test logs left over in: /go/src/github.com/cockroachdb/cockroach/artifacts/logTestProtectedTimestampSpanSelectionDuringBackup898532731
--- FAIL: TestProtectedTimestampSpanSelectionDuringBackup (17.40s)
=== RUN   TestProtectedTimestampSpanSelectionDuringBackup/last-index-gced
E201204 06:21:25.309528 521981 kv/kvserver/queue.go:1087  [n1,split,s1,r46/1:‹/{Table/69-Max}›] unable to split [n1,s1,r46/1:/{Table/69-Max}] at key "/Table/70": split at key /Table/70 failed: batch timestamp 1607062884.203095465,0 must be after replica GC threshold 1607062884.307758898,0
    backup_test.go:5855: error executing 'DROP INDEX foo@baz': pq: batch timestamp 1607062884.286029702,0 must be after replica GC threshold 1607062884.308103221,0
E201204 06:21:29.212540 519781 jobs/adopt.go:255  [n1] job 612736962438332417: adoption completed with error job 612736962438332417: node liveness error: restarting in background
E201204 06:21:29.212671 519537 jobs/adopt.go:255  [n1] job 612736962304737281: adoption completed with error job 612736962304737281: node liveness error: restarting in background
E201204 06:21:29.212749 521388 jobs/adopt.go:255  [n1] job 612736969564782593: adoption completed with error job 612736969564782593: node liveness error: restarting in background
E201204 06:21:29.212762 521261 jobs/adopt.go:255  [n1] job 612736968572829697: adoption completed with error job 612736968572829697: node liveness error: restarting in background
E201204 06:21:29.212793 520996 jobs/adopt.go:255  [n1] job 612736966384353281: adoption completed with error job 612736966384353281: node liveness error: restarting in background
E201204 06:21:29.212765 521402 jobs/adopt.go:255  [n1] job 612736971736416257: adoption completed with error job 612736971736416257: node liveness error: restarting in background
E201204 06:21:29.212657 520253 jobs/adopt.go:255  [n1] job 612736963711795201: adoption completed with error job 612736963711795201: node liveness error: restarting in background
E201204 06:21:29.212834 513991 jobs/adopt.go:255  [n1] job 612736947589316609: adoption completed with error job 612736947589316609: node liveness error: restarting in background
E201204 06:21:29.212862 514376 jobs/adopt.go:255  [n1] job 612736949860794369: adoption completed with error job 612736949860794369: node liveness error: restarting in background
E201204 06:21:29.212760 520544 jobs/adopt.go:255  [n1] job 612736965428379649: adoption completed with error job 612736965428379649: node liveness error: restarting in background
E201204 06:21:29.212895 511854 jobs/adopt.go:255  [n1] job 612736946318671873: adoption completed with error job 612736946318671873: node liveness error: restarting in background
    --- FAIL: TestProtectedTimestampSpanSelectionDuringBackup/last-index-gced (5.08s)

```

<details><summary>More</summary><p>
Parameters:

- GOFLAGS=-json

```
make stressrace TESTS=TestProtectedTimestampSpanSelectionDuringBackup PKG=./pkg/ccl/backupccl TESTTIMEOUT=5m STRESSFLAGS='-timeout 5m' 2>&1
```

[See this test on roachdash](https://roachdash.crdb.dev/?filter=status%3Aopen+t%3A.%2ATestProtectedTimestampSpanSelectionDuringBackup.%2A&sort=title&restgroup=false&display=lastcommented+project)
<sub>powered by [pkg/cmd/internal/issues](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)</sub></p></details>

### PR DESCRIPTION
**Pull request by adityamaru**
The flakes in #57546 are mostly because of hardcoded table IDs in the
expected values. The test runs >1K times under stress so I think we can
unskip it.

Resolves: #57546

Release justification: non-production code changes

Release note: None

### CODE REVIEW

File: pkg/ccl/backupccl/backup_test.go [hunk 1]
```diff
@@ -5790,6 +5790,12 @@ func TestProtectedTimestampsDuringBackup(t *testing.T) {
 	}
 }
 
+func getTableID(db *gosql.DB, dbName, tableName string) (tableID descpb.ID, err error) {
+	err = db.QueryRow(`SELECT table_id FROM crdb_internal.tables WHERE database_name = $1 AND name = $2`,
```
Comment (pbardea) [inline pkg/ccl/backupccl/backup_test.go:5794]: Note that we also have `catalogkv.TestingGetTableDescriptor`, which could be useful.

**Review by pbardea — APPROVED** [review]

File: pkg/ccl/backupccl/backup_test.go (hunk 1 above)
Comment (adityamaru) [reply pkg/ccl/backupccl/backup_test.go]: good point, changed!

**Comment by adityamaru** [comment]
TFTR!

bors r=pbardea
