### PR TITLE
roachtest: run rebalance/by-load/*/mixed-version on insecure mode

### LINKED ISSUE #122084: roachtest: rebalance/by-load/leases/mixed-version failed
roachtest.rebalance/by-load/leases/mixed-version [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/14772140?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/14772140?buildTab=artifacts#/rebalance/by-load/leases/mixed-version) on master @ [911f1ce389342459592d89fe7b78bcba3a2d265a](https://github.com/cockroachdb/cockroach/commits/911f1ce389342459592d89fe7b78bcba3a2d265a):

```
(mixedversion.go:592).Run: mixed-version test failure while running step 9 (run "rebalance load run"): CPU not evenly balanced after timeout: within bounds mean=69.0 tolerance=20.0% (±13.8) bounds=[55.2, 82.8]
	stores=[s1: 66 (-4.1%), s2: 78 (+14.4%), s3: 61 (-10.3%)]
test artifacts and logs in: /artifacts/rebalance/by-load/leases/mixed-version/run_1
```

Parameters:
 - <code>ROACHTEST_arch=amd64</code>
 - <code>ROACHTEST_cloud=gce</code>
 - <code>ROACHTEST_coverageBuild=false</code>
 - <code>ROACHTEST_cpu=4</code>
 - <code>ROACHTEST_encrypted=false</code>
 - <code>ROACHTEST_metamorphicBuild=false</code>
 - <code>ROACHTEST_ssd=0</code>
<details><summary>Help</summary>
<p>

See: [roachtest README](https://github.com/cockroachdb/cockroach/blob/master/pkg/cmd/roachtest/README.md)

See: [How To Investigate \(internal\)](https://cockroachlabs.atlassian.net/l/c/SSSBr8c7)

See: [Grafana](https://go.crdb.dev/roachtest-grafana/teamcity-14772140/rebalance-by-load-leases-mixed-version/1712729990208/1712730993983)

</p>
</details>
/cc @cockroachdb/kv-triage
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*rebalance/by-load/leases/mixed-version.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/bazci/githubpost/issues)
</sub>

Jira issue: CRDB-37692

### LINKED ISSUE #122179: roachtest: rebalance/by-load/replicas/mixed-version failed
roachtest.rebalance/by-load/replicas/mixed-version [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/14790158?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/14790158?buildTab=artifacts#/rebalance/by-load/replicas/mixed-version) on master @ [cead8be66c30a7377dacbf1c678911d2cb17194d](https://github.com/cockroachdb/cockroach/commits/cead8be66c30a7377dacbf1c678911d2cb17194d):

```
(mixedversion.go:592).Run: mixed-version test failure while running step 7 (run "rebalance load run"): CPU not evenly balanced after timeout: 
test artifacts and logs in: /artifacts/rebalance/by-load/replicas/mixed-version/run_1
```

Parameters:
 - <code>ROACHTEST_arch=amd64</code>
 - <code>ROACHTEST_cloud=gce</code>
 - <code>ROACHTEST_coverageBuild=false</code>
 - <code>ROACHTEST_cpu=4</code>
 - <code>ROACHTEST_encrypted=false</code>
 - <code>ROACHTEST_metamorphicBuild=false</code>
 - <code>ROACHTEST_ssd=0</code>
<details><summary>Help</summary>
<p>

See: [roachtest README](https://github.com/cockroachdb/cockroach/blob/master/pkg/cmd/roachtest/README.md)

See: [How To Investigate \(internal\)](https://cockroachlabs.atlassian.net/l/c/SSSBr8c7)

See: [Grafana](https://go.crdb.dev/roachtest-grafana/teamcity-14790158/rebalance-by-load-replicas-mixed-version/1712830286825/1712831285606)

</p>
</details>
/cc @cockroachdb/kv-triage
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*rebalance/by-load/replicas/mixed-version.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/bazci/githubpost/issues)
</sub>

Jira issue: CRDB-37746

### PR DESCRIPTION
**Pull request by kvoli**
Authentication fails if migrating from 22.2 to 23.1. Disable secure mode to avoid failing the test on this unrelated issue.

Fixes: #122179
Fixes: #122084

Release note: None

### CODE REVIEW

**Review by DarrylWong — APPROVED** [review]

File: pkg/cmd/roachtest/tests/rebalance_load.go [hunk 1]
```diff
@@ -95,7 +95,15 @@ func registerRebalanceLoad(r registry.Registry) {
 
 		if mixedVersion {
 			mvt := mixedversion.NewTest(ctx, t, t.L(), c, roachNodes, mixedversion.NeverUseFixtures,
-				mixedversion.ClusterSettingOption(install.ClusterSettingsOption(settings.ClusterSettings)),
+				mixedversion.ClusterSettingOption(
+					install.ClusterSettingsOption(settings.ClusterSettings),
+					// In 23.1, the `user_id` field was added to `system.web_sessions`.
+					// If the cluster is migrating to 23.1, auth-session login will not
+					// be aware of this new field and authentication will fail.
+					// TODO(DarrylWong): When 22.2 is no longer supported, we won't run
```
Comment (DarrylWong) [inline pkg/cmd/roachtest/tests/rebalance_load.go:103]: Thanks 😸

**Comment by kvoli** [comment]
bors r=DarrylWong

**Comment by kvoli** [comment]
TYFTR
