### PR TITLE
streamingccl: fix cross cluster replication bug

### LINKED ISSUE #113682: streamingccl: cross version replication stream fails on crdb_internal.setup_span_configs_stream()
In a test cluster replication from a 23.1.11 cluster to 23.2-alpha5 cluster, the stream failed with:
```
W231102 15:45:03.691584 587856 ccl/streamingccl/streamclient/span_config_stream_client.go:142 ⋮ [T1,Vsystem,n3,job=‹REPLICATION STREAM INGESTION id=913794457274843137›] 248
54  error when closing subscription connection: ‹ERROR: unknown function: crdb_internal.setup_span_configs_stream(): function undefined (SQLSTATE 42883)›
```

We should either add logic that informs the destination about the source cluster's version so that we can gate certain features. Or we should perform some error handling and prevent the stream from failing fatally.

Jira issue: CRDB-33108

### PR DESCRIPTION
**Pull request by adityamaru**
This change does a couple of things:

- It introduces a cluster setting to enable replication
of span configs from the source, system tenant to the
destination, system tenant. This settings is default true.
This is a new feature in 23.2 and so it seems like a good
idea to have a killswitch.

- It special cases `pgcode.UndefinedFunction` error that
is thrown if the source cluster is on a pre-23.2 version
that does not recognize `crdb_internal.setup_span_configs_stream($1)`.
In case of this error, we simply skip replicating the span
configs. This is meant to be a short term, backportable solution.

Fixes: https://github.com/cockroachdb/cockroach/issues/113682

Release note (bug fix): fixes a bug where replicating from
a source cluster that is on an older version (<23.2) than the destination
cluster would fail because of an undefined builtin function

### CODE REVIEW

File: pkg/ccl/streamingccl/settings.go [hunk 1]
```diff
@@ -119,3 +119,12 @@ var DumpFrontierEntries = settings.RegisterDurationSetting(
 	0,
 	settings.NonNegativeDuration,
 )
+
```
Comment (msbutler) [inline pkg/ccl/streamingccl/settings.go:122]: could you reword the commit message? It seems to imply that span config replication is disabled by default.

**Review by msbutler — APPROVED** [review]

File: pkg/ccl/streamingccl/settings.go (hunk 1 above)
Comment (adityamaru) [reply pkg/ccl/streamingccl/settings.go:122]: indeed, doing now

File: pkg/ccl/streamingccl/settings.go [hunk 2]
```diff
@@ -119,3 +119,12 @@ var DumpFrontierEntries = settings.RegisterDurationSetting(
...
+// ReplicateSpanConfigsEnabled controls whether we replicate span
+// configurations from the source system tenant to the destination system
+// tenant.
+var ReplicateSpanConfigsEnabled = settings.RegisterBoolSetting(settings.SystemOnly,
+	"physical_replication.span_configs.enabled",
```
Comment (stevendanna) [inline pkg/ccl/streamingccl/settings.go:127]: [consistency nits]: settings.SystemOnly on the next line like the rest, `physical_replication.consumer.span_configs.enabled`

**Review by stevendanna — COMMENTED** [review]
LGTM. A couple of minor nits.

Re testing: We'll test this via roachprod/roachtest I think.  It would be nice to unit test the client library. But I think that is going to take some changes to the library itself so we can do that on master as a potential follow-up to keep this backportable.

**Comment by adityamaru** [comment]
I don't actually think the error code makes it across the wire, I had to reach for the cluster setting in my cct test cluster. Let me test this some more locally.

**Review by stevendanna — APPROVED** [review]

**Comment by adityamaru** [comment]
blathers backport 23.2
