### PR TITLE
storage: fix crash in TestLeaseConcurrent

### LINKED ISSUE #9575: circleci: failed tests: TestLeaseConcurrent
The following test appears to have failed:

[#23143](https://circleci.com/gh/cockroachdb/cockroach/23143):

```
I160927 20:36:29.047059 1539 storage/replica.go:3295  [s1,r1:/M{in-ax}] gossiping cluster id {"395d5243-e026-46cd-b307-dcdbcbb8adaf"} from store 1, range 1
I160927 20:36:29.048959 1531 storage/replica.go:3317  [s1,r1:/M{in-ax}] gossiping sentinel from store 1, range 1
I160927 20:36:29.049332 1531 storage/replica.go:3324  [s1,r1:/M{in-ax}] gossiping first range from store 1, range 1: [{1 1 1}]
I160927 20:36:29.049827 1539 storage/replica.go:3317  [s1,r1:/M{in-ax}] gossiping sentinel from store 1, range 1
I160927 20:36:29.050150 1539 storage/replica.go:3324  [s1,r1:/M{in-ax}] gossiping first range from store 1, range 1: [{1 1 1}]
panic: (*basictracer.errAssertionFailed) (0x1afc1a0,0xc4201dbd70) [recovered]
	panic: (*basictracer.errAssertionFailed) (0x1afc1a0,0xc4201dbd70)

goroutine 1531 [running]:
panic(0x1afc1a0, 0xc4201dbd70)
	/usr/local/go/src/runtime/panic.go:500 +0x1ae
github.com/cockroachdb/cockroach/util/stop.(*Stopper).Recover(0xc42007f5f0)
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:177 +0xd8
panic(0x1afc1a0, 0xc4201dbd70)
	/usr/local/go/src/runtime/panic.go:458 +0x271
github.com/opentracing/basictracer-go.(*spanImpl).maybeAssertSanityLocked(0xc42028f560)
	/go/src/github.com/opentracing/basictracer-go/debug.go:27 +0x44a
github.com/opentracing/basictracer-go.(*spanImpl).Lock(0xc42028f560)
	/go/src/github.com/opentracing/basictracer-go/debug.go:19 +0x4d
github.com/opentracing/basictracer-go.(*spanImpl).Log(0xc42028f560, 0x0, 0x0, 0x0, 0xc4203b4c30, 0x48, 0x0, 0x0)
	/go/src/github.com/opentracing/basictracer-go/span.go:106 +0xab
github.com/opentracing/basictracer-go.(*spanImpl).LogEvent(0xc42028f560, 0xc4203b4c30, 0x48)
	/go/src/github.com/opentracing/basictracer-go/span.go:94 +0xaf
github.com/cockroachdb/cockroach/util/log.eventInternal(0x7f84c5ca93a0, 0xc420329920, 0x5e0100, 0x1cf4274, 0x1b, 0xc420269058, 0x2, 0x2)
--
github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker.func1(0xc42007f5f0, 0xc4201a8e40)
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:188 +0x8b
created by github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:189 +0x74

goroutine 1 [chan receive]:
testing.(*T).Run(0xc420292300, 0x1ce9caa, 0x13, 0x1fd4b90, 0x9cef01)
	/usr/local/go/src/testing/testing.go:647 +0x56e
testing.RunTests.func1(0xc420292300)
	/usr/local/go/src/testing/testing.go:793 +0xba
testing.tRunner(0xc420292300, 0xc420045b38)
	/usr/local/go/src/testing/testing.go:610 +0xca
testing.RunTests(0x1fd6868, 0x28f1c40, 0x14b, 0x14b, 0xc420111278)
	/usr/local/go/src/testing/testing.go:799 +0x4bb
testing.(*M).Run(0xc420045ef0, 0xc420253ce0)
	/usr/local/go/src/testing/testing.go:743 +0x130
github.com/cockroachdb/cockroach/storage_test.TestMain(0xc420045ef0)
	/go/src/github.com/cockroachdb/cockroach/storage/main_test.go:57 +0x287
main.main()
	github.com/cockroachdb/cockroach/storage/_test/_testmain.go:724 +0x1b6

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:2086 +0x1

goroutine 7 [chan receive]:
github.com/cockroachdb/cockroach/util/log.(*loggingT).flushDaemon(0x2c3b400)
	/go/src/github.com/cockroachdb/cockroach/util/log/clog.go:1032 +0x85
created by github.com/cockroachdb/cockroach/util/log.init.1
	/go/src/github.com/cockroachdb/cockroach/util/log/clog.go:613 +0xc3

goroutine 1484 [runnable]:
sync.runtime_Semacquire(0xc42007f61c)
	/usr/local/go/src/runtime/sema.go:47 +0x30
sync.(*WaitGroup).Wait(0xc42007f610)
	/usr/local/go/src/sync/waitgroup.go:131 +0xbf
github.com/cockroachdb/cockroach/util/stop.(*Stopper).Stop(0xc42007f5f0)
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:365 +0x20a
github.com/cockroachdb/cockroach/storage.(*testContext).Stop(0xc4201d8930)
	/go/src/github.com/cockroachdb/cockroach/storage/replica_test.go:260 +0x4f
github.com/cockroachdb/cockroach/storage.TestLeaseConcurrent.func1(0xc4204f2180, 0x1)
	/go/src/github.com/cockroachdb/cockroach/storage/replica_test.go:1682 +0xa18
--
testing.tRunner(0xc4204f2180, 0x1fd4b90)
	/usr/local/go/src/testing/testing.go:610 +0xca
created by testing.(*T).Run
	/usr/local/go/src/testing/testing.go:646 +0x530

goroutine 1529 [chan receive]:
github.com/cockroachdb/cockroach/storage/engine.(*RocksDB).Open.func1(0xc42051fce0)
	/go/src/github.com/cockroachdb/cockroach/storage/engine/rocksdb.go:390 +0x64
created by github.com/cockroachdb/cockroach/storage/engine.(*RocksDB).Open
	/go/src/github.com/cockroachdb/cockroach/storage/engine/rocksdb.go:391 +0xb61
FAIL	github.com/cockroachdb/cockroach/storage	10.757s
=== RUN   TestBatchBasics
I160927 20:36:41.098732 8 storage/engine/rocksdb.go:356  opening in memory rocksdb instance
I160927 20:36:41.101289 8 storage/engine/rocksdb.go:404  closing in-memory rocksdb instance
--- PASS: TestBatchBasics (0.01s)
=== RUN   TestBatchRepr
I160927 20:36:41.117073 23 storage/engine/rocksdb.go:356  opening in memory rocksdb instance
I160927 20:36:41.119211 23 storage/engine/rocksdb.go:404  closing in-memory rocksdb instance
--- PASS: TestBatchRepr (0.02s)
=== RUN   TestBatchGet
I160927 20:36:41.128152 10 storage/engine/rocksdb.go:356  opening in memory rocksdb instance

```
Please assign, take a look and update the issue accordingly.

### PR DESCRIPTION
**Pull request by RaduBerinde**
Fixes #9575.

@tschottdorf @petermattis I am not very familar with this code, I hope I'm not missing something.
I verified the raft spans show up in a local cluster, but I don't know how to trigger any of the special conditions in the code..

---

This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/9578)

### CODE REVIEW

File: storage/replica.go [hunk 1]
```diff
@@ -1587,6 +1587,12 @@ func (r *Replica) prepareRaftCommandLocked(
 		log.Infof(ctx, "prepared command %x: maxLeaseIndex=%d leaseAppliedIndex=%d",
 			idKey, r.mu.lastAssignedLeaseIndex, r.mu.state.LeaseAppliedIndex)
 	}
+
+	// Create a child span (the pendingCmd can outlive the span in the context).
+	// The span must be closed via cleanupCmdCtx when we are done with the
+	// command.
+	ctx, _ = tracing.ForkCtxSpan(ctx, "raft")
```
Comment (petermattis) [inline storage/replica.go]: Any reason you're not storing the cleanup closure in `pendingCmd`?

**Review by petermattis — APPROVED** [review]
LGTM

So many places to cleanup. Perhaps @tschottdorf has a better idea for how to make that cleaner.

**Comment by tschottdorf** [comment]
Unless I'm missing something, `tryAbandon` should already take care of these things (clearly it's failing, but this PR seems to introduce a parallel mechanism and I'd like to avoid that). It makes sure that the client waiting for a Raft command cannot go away from its notification channel if the context has leaked to the raft command application goroutine. This *should* allow the client's context Span to be used (after all, everything is serial).
The invariants here should be that a) as long as something is in `pendingCmds`, the context can be used b) once it's removed from pendingCmds, the context can only be used by the raft application goroutine until it has notified the client on the listening channel. Which of these are we screwing up, and where?

We've also been discussing loosening the restriction on spans (i.e. not fatal'ing when using a span that has been finished): https://github.com/cockroachdb/cockroach/issues/9284

I think we should push that issue forward (preferably so that this use-after-free is actually allowed, though nonsensical).

---

Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/9578#-:-KSiV5eu1I9Mh6q_5dXJ:bzgbcvi)*

**Comment by RaduBerinde** [comment]
I will work on #9284 and avoid the crash that way. But I think we should investigate why the assumptions you described above aren't holding up..

---

Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[storage/replica.go, line 1594 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/9578#-KShkx_vthjQEgfYexn1-r1-1594:-KSki3sC0pNUEaevOOAI:b-3t6scr) ([raw file](https://github.com/cockroachdb/cockroach/blob/1f01993ed6ffcc170d496550706bd9f215236383/storage/replica.go#L1594)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary>
> Any reason you're not storing the cleanup closure in `pendingCmd`?
</details>
We could, figured it's not really necessary to store more stuff

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/9578#-:-KSki8-VmINjEKZ6DiDe:b7ftn6f)*

**Comment by RaduBerinde** [comment]
Is what you said above true even when we refurbish a command? (we are using the same context in that case)

---

Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/9578#-:-KSkwK4t243vHMFONT9w:b-q0rn8k)*

**Comment by tschottdorf** [comment]
We tracked this down to the test, which does illegal things. Radu is fixing that and I'll send a PR to basictracer-go which makes the assertion more helpful when it fails by including the failing span.

---

Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/9578#-:-KSlF62y3lqabD2OuX5-:bzg0opk)*

**Comment by RaduBerinde** [comment]
Updated to fix the test instead. Cannot reproduce the failure with this fix. Thanks Tobi!

**Comment by tschottdorf** [comment]
Short and sweet. :lgtm_strong: 

---

Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[storage/replica_test.go, line 1626 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/9578#-KSlsf_aYLPuah0cWBMM:-KSlsf_bFD6MLo-3T7Sm:b4drzum) ([raw file](https://github.com/cockroachdb/cockroach/blob/3c9385d37278b0960d2ed43525ccd4eb0e190e72/storage/replica_test.go#L1626)):*
> ```Go
> 					defer tc.rng.mu.Unlock()
> 					if withError {
> 						delete(tc.rng.mu.pendingCmds, cmd.idKey)
> ```

Put a short explanation here.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/9578#-:-KSlso_pbmfXGN446DpP:boj9qzi)*

**Comment by RaduBerinde** [comment]
Review status: 1 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[storage/replica_test.go, line 1626 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/9578#-KSlsf_aYLPuah0cWBMM:-KSluiYlmXO848EJ0iIm:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/3c9385d37278b0960d2ed43525ccd4eb0e190e72/storage/replica_test.go#L1626)):*
<details><summary><i>Previously, tschottdorf (Tobias Schottdorf) wrote…</i></summary>
> Put a short explanation here.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/9578)*

**Comment by tamird** [comment]
Reviewed 1 of 2 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/9578)*
