### PR TITLE
roachtest: don't specify virtual cluster in debug zips

### LINKED ISSUE #143841: debug: `clusters/x` subfolder contains wrong tenant's info
I was looking at a debug.zip from a 25.1 MT cluster in a roachtest and was confused as data relevant to the application tenant looked strange and was missing certain jobs or tables I expected to see in it. Eventually I realized that the content of the tenant subfolder was actually just a second dump of the system tenant's tables and the virtual cluster's tables were not present in the zip at all. I've attached the zip in question, taken from our public roachtests. 

[debug.zip](https://github.com/user-attachments/files/19570456/debug.zip)

On inspecting the logs captured by the test and emitted during the production of this zip, we see the `zip` command was invoked as `cockroach debug zip debug.zip ... --url 'postgres://...options=-ccluster%3Dsystem&sslcert...'`

The `zip` command then logged it was discovering virtual clusters and then logged this line: 
```
[cluster] ... using SQL connection URL: postgresql://...&options=-ccluster%3Dsystem&options=-ccluster%3Dmixed-version-tenant-hpdr5&sslcert=...
```

It seems possible that the duplicate `ccluster` param in in this URI with contradictory argument values could be relevant here.

Jira issue: CRDB-49072

Epic CRDB-52093

### PR DESCRIPTION
**Pull request by DarrylWong**
Previously, we were always passing the system tenant when taking debug zips in case a roachtest had overriden the default virtual cluster. However, the debug zip command already attempts to fetch all virtual clusters by passing the --ccluster flag for each tenant. This behavior was suppresed due to our hard coding of the system tenant, causing all debug zips to be of the system tenant.

This changes it to instead pass nothing so the url has no existing --ccluster flag.

Fixes: https://github.com/cockroachdb/cockroach/issues/143841
Release note: none

### CODE REVIEW

File: pkg/cmd/roachtest/cluster.go [hunk 1]
```diff
@@ -1409,7 +1410,7 @@ func (c *clusterImpl) FetchDebugZip(
 			cmd := roachtestutil.NewCommand("%s debug zip", test.DefaultCockroachPath).
 				Option("include-range-info").
 				Flag("exclude-files", fmt.Sprintf("'%s'", excludeFiles)).
-				Flag("url", fmt.Sprintf("'%s'", nodePgUrl[0])).
+				Flag("url", urls[0]).
```
Comment (golgeek) [inline pkg/cmd/roachtest/cluster.go:1414]: Maybe an extra check that `len(urls) > 0` might be useful?
If I read the logic in `PgURL()` correctly, an Azure `emptyCluster` would return an empty list and no error.

**Review by golgeek — APPROVED** [review]

File: pkg/cmd/roachtest/cluster.go (hunk 1 above)
Comment (DarrylWong) [reply pkg/cmd/roachtest/cluster.go:1414]: I don't think so, since `emptyCluster` is used to indicate that there are no VMs but we are adding one to satisfy roachprod:

```
	// The cluster does not have a VM, but roachprod assumes that this is not
	// possible and implements providers on the VM level. A VM-less cluster will
	// not have access to provider info or methods. To still allow this cluster to
	// be deleted, we must create a fake VM, indicated by EmptyCluster.
	m := vm.VM{
		Name:       *resourceGroup.Name,
		Provider:   ProviderName,
		RemoteUser: remoteUser,
		VPC:        "global",
		// We add a fake availability-zone suffix since other roachprod
		// code assumes particular formats. For example, "eastus2z".
		Zone:         *resourceGroup.Location + "z",
		EmptyCluster: true,
	}
```

So calling `pgUrl` on such a cluster should return the empty string for the `ip`, which should be caught by:

https://github.com/cockroachdb/cockroach/blob/ad3bd1355463cefdc07e995765fa82adfe391d05/pkg/roachprod/roachprod.go#L758-L760

It's definitely not obvious on first glance, so I'm not opposed to adding just a general `len(urls) != 0` in `PgURL()` itself?  But I also see the argument that if roachprod clusters always having at least one VM is an invariant, then https://github.com/cockroachdb/cockroach/blob/ad3bd1355463cefdc07e995765fa82adfe391d05/pkg/roachprod/roachprod.go#L763-L765

would make that check redundant. Thoughts?

Comment (golgeek) [reply pkg/cmd/roachtest/cluster.go:1414]: Ah right, I forgot that list of clusters is always built from the list of VMs.

I would still tend to add the `len(urls) != 0` check in `PgUrl()` to make things clearer when browsing the code, but maybe it's just because I don't want to lose face.

Comment (DarrylWong) [reply pkg/cmd/roachtest/cluster.go:1414]: Done.

**Review by DarrylWong — COMMENTED** [review]
Oops noticed a regression when testing the `len(urls) = 0` case where I was no longer continuing on errors. Fixed now though.

**Review by herkolategan — APPROVED** [review]

**Comment by DarrylWong** [comment]
Unrelated test flake

TFTRs!

bors r=golgeek,herkolategan
