### PR TITLE
[release-21.2] tracing: restore trace redactability and default to "off"

### LINKED ISSUE #71694: tracing: perf regression due to trace redactability
**Describe the problem**

In #58610 we discussed trace data sent to tenants from the KV layer. This data
was not redactable and there was a concern that tenants could learn privileged
information (such as keys belonging to another tenant, for example).

We reacted to this by adding redactability for traces (#70562). Unfortunately,
this introduced inacceptably high overhead in the case in which tracing is
enabled across the board (as will be the case with the
`sql.trace.*.enable_threshold` cluster setting, which is known to see some
usage) and, on `release-21.2`, we switched to a blunter approach with degraded
observability, #71606. This degraded observability is tracked in #58610 and is
out of scope here as it does not affect master (at the time of writing).

Details on the regression can be found in
https://github.com/cockroachdb/cockroach/pull/71610. Concretely, in a simple
"select single row" end-to-end local benchmark, we see approximately a 20%
regression in average request latency.

We have to either mitigate the regression or revert the work but are then
forced to add the redactability again in some way, as for better or worse
traces as observed by tenants are an invaluable tool in CockroachDB support
today.

Epic CRDB-2574

### PR DESCRIPTION
**Pull request by dhartunian**
This PR is reverting the work in #71606 and backporting #73405 on top.

-----
Multi-tenant deployments require tracing support
in order to help customers and engineers debug query performance 
issues. This requires that trace information recorded on the KV layer 
be redacted prior to being transmitted to the tenant in order to 
guard against data leakage through the multi-tenant abstractions.

This PR reverts the work done in #71606 which dropped tenant-bound 
traces, and effectively restores #70562 which added trace redactability 
between kv and tenant. Then it applies #73405 in order to enable 
conditional redactability which defaults to "off".

### CODE REVIEW

**Comment by dhartunian** [comment]
I'm definitely open to suggestions on how to break this PR up into better chunks. Maybe the revert of #71606 and application of #71610 can be separated.

**Comment by tbg** [comment]
I'm going to leave the review to the rest of the gang since this is mostly code I wrote, but I agree with the approach.

**Comment by knz** [comment]
I'm not sure how to best review this - what are the pitfalls that a reviewer should care about?

**Review by andreimatei — COMMENTED** [review]
How come you're doing this work on the 21.2 branch, particularly since you're leaving it in an incomplete state? Wouldn't it be a better idea to figure out the story on master first?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/73117#-:-MplcLNH2zLXsUxobStD:b3tescw)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @knz)

**Review by dhartunian — COMMENTED** [review]
> How come you're doing this work on the 21.2 branch, particularly since you're leaving it in an incomplete state? Wouldn't it be a better idea to figure out the story on master first?

You raise a good point. Let me bring the `default redactability to "off"` commits to `master` first. I agree that we should keep `master` in sync as much as possible.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/73117#-:-Mple1UYDHM3Z6e5UgYP:bh3qe2g)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @knz)

**Comment by dhartunian** [comment]
I commented in #71694 with reasoning for a simpler change in the release branch. After that PR we will continue with tracing redaction improvements on `master`.

**Comment by dhartunian** [comment]
# Reviewer guide:

Commits 1-4: These revert prior reverts (yes, I'm sorry) on the release branch and restore functionality that is currently on `master` that added redactability to traces. Should not require deep review. These are originally from #70562.

1. Revert "server: don't return trace recordings to tenants"  (This was the prior commit that dropped traces from KV to tenant)
2. Revert "Revert "kvserver: redact tenant-bound trace recordings"" 
3. Revert "Revert "log,tracing: make traces redactable"" 
4. Revert "Revert "tracing: lint against non-const string to Span.Record… 

Commits 5-10: These are a rebase of a closed PR that was never merged to `release-21.2` but was considered as an alternative to dropping the kv traces before handing off to tenants.

5. log: add BenchmarkLogEntry_String (adding benchmark; test only code)
6. log: add BenchmarkEventf_WithVerboseTrace (adding benchmark; test only code)
7. log: optimize logEntry.SafeFormat (small optimization to logging code)
8. tracing: default redactability to "off" <-- **This requires review** 🚨 🚨  This commits adds functionality that makes redactablity of traces configurable
9. log: improve Event benchmark to check redactability as well (more related benchmarks; test only code)
10. caller: modernize Lookup (reviewed on `master` in https://github.com/cockroachdb/cockroach/pull/71693)

Commit 11: This is more new code that forces redactability on tenant-bound traces

11. server, tracing: force redactability on tenant spans <-- **This requires review** 🚨 🚨

**Review by abarganier — COMMENTED** [review]
Looking good. I mostly focused on the following commits:
- tracing: default redactability to "off" 
- server, tracing: force redactability on tenant spans

A nit and a couple questions. @andreimatei would you be able to give this a look as well? 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/73117#-:-MpwB1OR7xLnNeisa0Mv:b-3fgnvj)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dhartunian and @knz)

___
*[pkg/server/node_tenant.go, line 43 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/73117#-Mpw5TNC4ASDavvVCbpu:-Mpw5TNC4ASDavvVCbpv:b-j7ycue) ([raw file](https://github.com/cockroachdb/cockroach/blob/9b0bcb170fc0576b314786abc6a83282ca67dc91/pkg/server/node_tenant.go#L43)):*
> ```
> field.Value = tracingpb.MaybeRedactableString(redact.Sprint(redact.SafeString(sRedactedMarker)))
> ```
I don't think I follow this piece - is all this casting necessary for a static string we know is safe from a redaction perspective? Could we not just do `tracingpb.MaybeRedactableString(sRedactedMarker)` and achieve the same effect with respect to the underlying string? Or is this just in the name of following convention? 
___
*[pkg/util/tracing/span.go, line 82 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/73117#-MpwARIc6isjAwk52Rj0:-MpwARIc6isjAwk52Rj1:b-xf7ixa) ([raw file](https://github.com/cockroachdb/cockroach/blob/31a95293fa837130b9221b8825de43b82fe07d4d/pkg/util/tracing/span.go#L82)):*
> ```
> 	// NB: doesn't matter what sp.Tracer().Redactable() returns now, this Span's
> 	// redactability is constant across its lifetime.
> ```
Is this still true, now that we've added `func (sp *Span) Redactable() bool` above?
___
*[pkg/util/tracing/span_options.go, line 113 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/73117#-MpwArws8APuU7CeAXX3:-MpwArws8APuU7CeAXX4:b-c9i6hj) ([raw file](https://github.com/cockroachdb/cockroach/blob/31a95293fa837130b9221b8825de43b82fe07d4d/pkg/util/tracing/span_options.go#L113)):*
> ```
> WithRedactable
> ```
nit: to follow the convention set by the `ForceRealSpan` option, should this be called `WithForceRedactable`?

**Review by andreimatei — COMMENTED** [review]
> Reviewed 1 of 1 files at r5, 1 of 1 files at r6, 1 of 1 files at r7.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/73117)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andreimatei, @dhartunian, and @knz)

___
*[-- commits, line 6 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/73117#-MpwUaMI7qrN8PQvFIdK):*
something wrong here. And also in the other commits.
___
*[-- commits, line 42 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/73117#-MpwXUPsE9-lMg-tQxot):*
please post benchmark delta in commit msg
___
*[-- commits, line 57 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/73117#-MpwXqvlCYmOtVhzpeu4):*
this message seems stale
___
*[-- commits, line 71 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/73117#-MpwY14K5v2nIAUBevbv):*
I'm confused about what `old` is here
___
*[-- commits, line 87 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/73117#-MpwY9Bd43CFddR_6QOS):*
what's this? Either more words or remove.
___
*[pkg/server/node_tenant.go, line 22 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/73117#-MpwYjcQ8blh_NMpIrFR:-MpwYjcQ8blh_NMpIrFS:by84yz4) ([raw file](https://github.com/cockroachdb/cockroach/blob/9b0bcb170fc0576b314786abc6a83282ca67dc91/pkg/server/node_tenant.go#L22)):*
> ```Go
> const sRedactedMarker = "verbose trace message redacted"
> 
> func maybeRedactRecording(tenID roachpb.TenantID, rec tracing.Recording) {
> ```

this function deserves a comment
___
*[pkg/util/tracing/crdbspan.go, line 288 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/73117#-MpwbVRp-ydc6lcPGkVJ:-MpwbVRqAqPkWQI8ox_M:b-5jwigh) ([raw file](https://github.com/cockroachdb/cockroach/blob/9b0bcb170fc0576b314786abc6a83282ca67dc91/pkg/util/tracing/crdbspan.go#L288)):*
> ```Go
> }
> 
> func (s *crdbSpan) record(maybeRedactableString string) {
> ```

I'd make this take in a `tracingpb.MaybeRedactableString`, pushing the cast out.
But as I'm saying elsewhere, maybe this can stay a `RedactableString`.
___
*[pkg/util/tracing/tracingpb/recorded_span.proto, line 27 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/73117#-Mpw_w5U1rJoQZu8I_Lt:-Mpw_w5U1rJoQZu8I_Lu:be8xlqs) ([raw file](https://github.com/cockroachdb/cockroach/blob/9b0bcb170fc0576b314786abc6a83282ca67dc91/pkg/util/tracing/tracingpb/recorded_span.proto#L27)):*
> ```protobuf
>   message Field {
>     string key = 1;
>     string value = 2 [(gogoproto.nullable) = false, (gogoproto.customtype) = "MaybeRedactableString"];
> ```

why can't this stay as a `RedactableString`, and in the case where the value does not actually come from a redactable string, make it "redactable" by bookending the source with markers? Would that cost us?

The commit message doesn't make it clear where the performance cost of making events redactable is. But putting bookend markers seems cheap to me. If this works out, I think it'd be significantly clearer to do that instead of introducing this `MaybeRedactableString`. If this stays a `redact.RedactableString`, I think we can get rid of `span.RedactableLogs` too.
Does this make any sense?

**Review by dhartunian — COMMENTED** [review]
I've addressed all open queries except the question about the origin of the benchmark that Andrei brought up. Will update the thread once I get that explained.

@tbg do you happen to remember the conditions under which the first benchmark in this PR was computed: https://github.com/cockroachdb/cockroach/pull/71610

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/73117#-:-Mpxmj3ZAWMc4DXtCbdp:b-cbcpzh)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @abarganier, @andreimatei, @dhartunian, and @knz)

___
*[-- commits, line 6 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/73117#-MpwUaMI7qrN8PQvFIdK):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

something wrong here. And also in the other commits.
</blockquote></details>

Done. Restored commit messages from original PRs.
___
*[-- commits, line 42 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/73117#-MpwXUPsE9-lMg-tQxot):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

please post benchmark delta in commit msg
</blockquote></details>

Done.
___
*[-- commits, line 57 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/73117#-MpwXqvlCYmOtVhzpeu4):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

this message seems stale
</blockquote></details>

Done.
___
*[-- commits, line 87 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/73117#-MpwY9Bd43CFddR_6QOS):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

what's this? Either more words or remove.
</blockquote></details>

Added context.
___
*[pkg/server/node_tenant.go, line 22 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/73117#-MpwYjcQ8blh_NMpIrFR:-MpxSQNBC4XjbrHKvblk:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/9b0bcb170fc0576b314786abc6a83282ca67dc91/pkg/server/node_tenant.go#L22)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

this function deserves a comment
</blockquote></details>

Done.
___
*[pkg/server/node_tenant.go, line 43 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/73117#-Mpw5TNC4ASDavvVCbpu:-MpxSKom0uQvdLWREUP2:bhshlj0) ([raw file](https://github.com/cockroachdb/cockroach/blob/9b0bcb170fc0576b314786abc6a83282ca67dc91/pkg/server/node_tenant.go#L43)):*
<details><summary><i>Previously, abarganier (Alex Barganier) wrote…</i></summary><blockquote>

> ```
> field.Value = tracingpb.MaybeRedactableString(redact.Sprint(redact.SafeString(sRedactedMarker)))
> ```
I don't think I follow this piece - is all this casting necessary for a static string we know is safe from a redaction perspective? Could we not just do `tracingpb.MaybeRedactableString(sRedactedMarker)` and achieve the same effect with respect to the underlying string? Or is this just in the name of following convention? 
</blockquote></details>

You're correct, this can just be a static string that will get cast automatically. It also makes it clearer that this case is the same as the one above.
___
*[pkg/util/tracing/crdbspan.go, line 288 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/73117#-MpwbVRp-ydc6lcPGkVJ:-MpxT3i8-Yli2tkR3Yza:bvwwxn7) ([raw file](https://github.com/cockroachdb/cockroach/blob/9b0bcb170fc0576b314786abc6a83282ca67dc91/pkg/util/tracing/crdbspan.go#L288)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

I'd make this take in a `tracingpb.MaybeRedactableString`, pushing the cast out.
But as I'm saying elsewhere, maybe this can stay a `RedactableString`.
</blockquote></details>

Done.

Don't think we can make this a `RedactableString` because `spanInner.Recordf` which calls this, needs to conditionally either call `fmt.Sprintf` or `redact.Sprintf` and I think the point here is to never make something a `RedactableString` that didn't pass through `redact.Sprintf`.
___
*[pkg/util/tracing/span.go, line 82 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/73117#-MpwARIc6isjAwk52Rj0:-MpxTgAEEYO84cU4WVeF:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/31a95293fa837130b9221b8825de43b82fe07d4d/pkg/util/tracing/span.go#L82)):*
<details><summary><i>Previously, abarganier (Alex Barganier) wrote…</i></summary><blockquote>

> ```
> 	// NB: doesn't matter what sp.Tracer().Redactable() returns now, this Span's
> 	// redactability is constant across its lifetime.
> ```
Is this still true, now that we've added `func (sp *Span) Redactable() bool` above?
</blockquote></details>

Done.
___
*[pkg/util/tracing/span_options.go, line 113 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/73117#-MpwArws8APuU7CeAXX3:-MpxU-6n-IKv0IqGdYqm:b5j5q0m) ([raw file](https://github.com/cockroachdb/cockroach/blob/31a95293fa837130b9221b8825de43b82fe07d4d/pkg/util/tracing/span_options.go#L113)):*
<details><summary><i>Previously, abarganier (Alex Barganier) wrote…</i></summary><blockquote>

> ```
> WithRedactable
> ```
nit: to follow the convention set by the `ForceRealSpan` option, should this be called `WithForceRedactable`? 
</blockquote></details>

Yes, Done.
___
*[pkg/util/tracing/tracingpb/recorded_span.proto, line 27 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/73117#-Mpw_w5U1rJoQZu8I_Lt:-MpxIMZdBBoWOL0cZtjq:btssnw5) ([raw file](https://github.com/cockroachdb/cockroach/blob/9b0bcb170fc0576b314786abc6a83282ca67dc91/pkg/util/tracing/tracingpb/recorded_span.proto#L27)):*
> why can't this stay as a RedactableString, and in the case where the value does not actually come from a redactable string, make it "redactable" by bookending the source with markers? Would that cost us?

At this point, I also worry that introducing redaction to traces without some configurability will be another point version surprise to non-serverless customers so I'd prefer to avoid it.

> The commit message doesn't make it clear where the performance cost of making events redactable is. But putting bookend markers seems cheap to me. If this works out, I think it'd be significantly clearer to do that instead of introducing this MaybeRedactableString. If this stays a redact.RedactableString, I think we can get rid of span.RedactableLogs too.

I believe the performance cost is paid when calling `redact.Sprintf` which is aware of the redactability of various parameters and defaults to wrapping unknown or unsafe parameters in the brackets. Previously, when the original change was made, this cost was paid in `VEventf` and related functions that called `eventInternal`. Added a note in commit msg as well.

File: pkg/server/node_tenant_test.go [hunk 1]
```diff
@@ -45,7 +45,9 @@ func TestMaybeRedactRecording(t *testing.T) {
 			Add("tag_sensitive", tagSensitive).
 			Add("tag_not_sensitive", log.Safe(tagNotSensitive))
 		ctx := logtags.WithTags(context.Background(), tags)
-		ctx, sp := tracing.NewTracer().StartSpanCtx(ctx, "foo", tracing.WithForceRealSpan())
+		tracer := tracing.NewTracer()
+		tracer.SetRedactable(true)
```
Comment (tbg) [inline pkg/server/node_tenant_test.go:49]: nit: slightly more "idiomatic" to set the span to redactable and not the tracer, right? This is closer to production usage. Not that it would make a difference.

**Review by andreimatei — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/73117)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @abarganier, @andreimatei, @dhartunian, and @knz)

___
*[pkg/util/tracing/tracingpb/recorded_span.proto, line 27 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/73117#-Mpw_w5U1rJoQZu8I_Lt:-Mq-pElU81NykZ2Bzi5X:bek2zb) ([raw file](https://github.com/cockroachdb/cockroach/blob/9b0bcb170fc0576b314786abc6a83282ca67dc91/pkg/util/tracing/tracingpb/recorded_span.proto#L27)):*
> At this point, I also worry that introducing redaction to traces without some configurability will be another point version surprise to non-serverless customers so I'd prefer to avoid it.


I'm not saying remove any configurability. I'm saying represent "non-redactable" messages as a string without internal markers surrounded by exactly one pair of markers. Then, technically, there would be no such thing as a "non-redactable" trace. Instead there'd fine-grained redactable traces, and course-grained redactable ones (the course grained ones would basically be fully redacted if anyone redacts them). So, when redactability is enabled, the messages would be produced by `sp.Recordf`, and when it's disabled, they would be produced as `marker + escapeMarkers(entry.LegacyString) + marker`.
Generally the escaping of internal characters would be a fast no-op.
Does this compute?

File: pkg/server/node_tenant_test.go (hunk 1 above)
Comment (dhartunian) [reply pkg/server/node_tenant_test.go]: Done.

**Comment by dhartunian** [comment]
@andreimatei @tbg @abarganier @knz I've updated this PR with the work discussed in the email thread that keeps the `RedactedString` type which simplifies the implementation and keeps this code much closer in line with `master`.

Let me know if I can help with review but the two commits affected by this change are:

8. tracing: make full redaction of trace messages configurable  <-- This is where I changed the implementation to either coarsely or finely redact based on the tracer/span flag

11. server, tracing: force redactability on tenant spans <-- This is mostly the same but has changed to just flip the flag on for tenants instead of changing anything else about how redaction is applied since now we can assume that redaction is applied _in some form_ on the recorded span.

**Review by andreimatei — CHANGES_REQUESTED** [review]
I still think we should be working on master first :)

nit: when pushing updates, it's nice to rewrite all commits, so the last versions of all commits appear as a contiguous span in Reviewable. At least on master, you get that naturally by rebasing on a fresh tip before pushing.

> Reviewed 1 of 22 files at r30.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/73117#-:-MqKV5YS5XmgPcrQ4KY5:b61x26o)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @abarganier, @andreimatei, @dhartunian, @knz, and @tbg)

___
*[-- commits, line 80 at r30](https://reviewable.io/reviews/cockroachdb/cockroach/73117#-MqKr7M663rUXiiavhpa):*
I've read through the code involved and I'd like to understand more of what's going on.  It was never perfectly clear to me what cost redaction code exactly we're trying to save, and after reading a bit of code it's even more unclear to me.

When redaction is not needed, this patch replaces in `spanInner.Recordf()`:

```
 str = redact.Sprintf(format, args...)
```

with 
```
fmt.Fprintf(&b, format, args...)
```

The case that matters is when `Recordf`is called from `log.EventInternal()` (right?). That calls is:
```
sp.Recordf("%s", entry)
```
Notice the trivial format. The `entry` is a `logEntry` that already has the message stringified in it, with redactability in it or not based, I think, on the logging configuration (right?). Thus, the difference between the `redact.Sprintf` and the `fmt.Fprintf` seems superficial to my untrained eye.
`logEntry.String` does  `redact.StringWithoutMarkers(e)`, which does `redact.Sprint(f).StripMarkers()`. Where exactly does the perf difference compared to ` redact.Sprintf("%f", entry)` come from? Cause if it's simply the difference between `redact.Sprint()` and `redact.Sprint_f_("%s")`, then I think we should either a) figure out how to get rid of the difference inside the `redact` library, or b) get rid of the dummy format.
___
*[-- commits, line 126 at r30](https://reviewable.io/reviews/cockroachdb/cockroach/73117#-MqKtrFr0p1-xtHHVGdO):*
3 benchmarks? I think I only see 2?
___
*[-- commits, line 133 at r30](https://reviewable.io/reviews/cockroachdb/cockroach/73117#-MqKX3AL-_exFEhiKYQ4):*
`trace.debug.enable` is the `net/Trace` stuff, right? `net.Trace` is very expensive - and also pretty useless; it comes to dominate the benchmark. To get something more representative, you want the `threshold` cluster setting.
___
*[-- commits, line 140 at r30](https://reviewable.io/reviews/cockroachdb/cockroach/73117#-MqKsn6O6cZhKDv38oFz):*
>   The base for all 3 below benchmarks that's used is the code on
  `release-21.2` with the "drop traces for tenants" commit reverted. This
  reproduces a reasonable "base" state where tracing redaction isn't
  really introduced at all.


The base is "no redaction", and this patch improves the performance? How come?
Is "where tracing redaction isn't really introduced at all" wrong?
___
*[pkg/server/node_tenant.go, line 20 at r30](https://reviewable.io/reviews/cockroachdb/cockroach/73117#-MqKYqlV68ie2hiYrkyT:-MqKYqlV68ie2hiYrkyU:b-x7p06e) ([raw file](https://github.com/cockroachdb/cockroach/blob/e06079d3bc020e8f135339e56dec2fea23b56abf/pkg/server/node_tenant.go#L20)):*
> ```Go
> )
> 
> var sRedactedMarker = redact.RedactableString("verbose trace message redacted")
> ```

can it really not be `const` with the new type?
___
*[pkg/server/node_tenant.go, line 46 at r30](https://reviewable.io/reviews/cockroachdb/cockroach/73117#-MqKZL9Z7PvXaILoyzkv:-MqKZL9Z7PvXaILoyzkw:b-d6coiv) ([raw file](https://github.com/cockroachdb/cockroach/blob/e06079d3bc020e8f135339e56dec2fea23b56abf/pkg/server/node_tenant.go#L46)):*
> ```Go
> 					field.Value = sRedactedMarker
> 					continue
> 				} else if field.Key != tracingpb.LogMessageField {
> ```

if you're moving away from the if/else structure, do it all the way and get rid of this `else`
___
*[pkg/util/log/log_entry.go, line 136 at r30](https://reviewable.io/reviews/cockroachdb/cockroach/73117#-MqKpequ0IAjruW15ERf:-MqKpequ0IAjruW15ERg:br12stb) ([raw file](https://github.com/cockroachdb/cockroach/blob/e06079d3bc020e8f135339e56dec2fea23b56abf/pkg/util/log/log_entry.go#L136)):*
> ```Go
> // because it is significantly faster and sits in the hot path of verbose
> // tracing.
> func (e *logEntry) LegacyString() string {
> ```

well, is it "legacy" or isn't it? If this method stays as it is, I think we need to give it a better name.
But perhaps the right thing to do is make it the `String` method on `logpb.Entry` (i.e. inhibit the proto compiler for generating one).
___
*[pkg/util/log/log_entry.go, line 164 at r30](https://reviewable.io/reviews/cockroachdb/cockroach/73117#-MqKpApADN240GQxBBpC:-MqKpApBAd1Wl8hDKOfa:bih4cdp) ([raw file](https://github.com/cockroachdb/cockroach/blob/e06079d3bc020e8f135339e56dec2fea23b56abf/pkg/util/log/log_entry.go#L164)):*
> ```Go
> 
> 	if entry.Redactable {
> 		// This is true when eventInternal is called from logfDepth(),
> ```

this comment doesn't seem appropriate. I'm not sure how to improve it, but perhaps you do?
___
*[pkg/util/tracing/crdbspan.go, line 43 at r30](https://reviewable.io/reviews/cockroachdb/cockroach/73117#-MqKdQa76soX8yjhQ5vZ:-MqKdQa76soX8yjhQ5v_:b-crkos4) ([raw file](https://github.com/cockroachdb/cockroach/blob/e06079d3bc020e8f135339e56dec2fea23b56abf/pkg/util/tracing/crdbspan.go#L43)):*
> ```Go
> 	spanID       uint64 // probabilistically unique
> 	parentSpanID uint64
> 	redactable   bool // are verbose logs redactable?
> ```

nit: I think this phrasing of the comment as a question is confusing.

Also please make a reference to the `mu.recording.recordingType` field.
___
*[pkg/util/tracing/crdbspan.go, line 43 at r30](https://reviewable.io/reviews/cockroachdb/cockroach/73117#-MqKdwLuC5ws27hhA73R:-MqKdwLuC5ws27hhA73S:b-jpx272) ([raw file](https://github.com/cockroachdb/cockroach/blob/e06079d3bc020e8f135339e56dec2fea23b56abf/pkg/util/tracing/crdbspan.go#L43)):*
> ```Go
> 	spanID       uint64 // probabilistically unique
> 	parentSpanID uint64
> 	redactable   bool // are verbose logs redactable?
> ```

Are you sure we're gaining anything by capturing this snapshot of the tracer state in spans? Read-only sharing of the tracer's atomic should be cheap. In fact, in the case when spans are created but not recording (which I'm trying to make the default), you'd save by not having to populate this field.
___
*[pkg/util/tracing/span.go, line 68 at r30](https://reviewable.io/reviews/cockroachdb/cockroach/73117#-MqKfOGS7iF4mCJ-Vd7w:-MqKfOGS7iF4mCJ-Vd7x:b7r59sm) ([raw file](https://github.com/cockroachdb/cockroach/blob/e06079d3bc020e8f135339e56dec2fea23b56abf/pkg/util/tracing/span.go#L68)):*
> ```Go
> }
> 
> // Redactable returns true if this Span records
> ```

nit: wrapping
___
*[pkg/util/tracing/span.go, line 69 at r30](https://reviewable.io/reviews/cockroachdb/cockroach/73117#-MqKgqXW-FRJD35fDAo9:-MqKgqXW-FRJD35fDAoA:bj2bh3r) ([raw file](https://github.com/cockroachdb/cockroach/blob/e06079d3bc020e8f135339e56dec2fea23b56abf/pkg/util/tracing/span.go#L69)):*
> ```
> // Redactable returns true if this Span records
> // redactable logs.
> ```

That's not technically true, is it? The return value of this method has nothing to do with whether the span is recording or not.

Instead of making this a public method, consider bundling the redactability info into the result of `getSpanOrEventLog()` - maybe make that guy return a struct.
If this method is not public any more, you wouldn't have to worry about the `nil` or `noop` cases; in fact, you could make it a method on the `crdbSpan` instead, to make the tangling of the redactability concept and the existence of a `crdbSpan` painfully visible to all caller.
___
*[pkg/util/tracing/span_inner.go, line 233 at r30](https://reviewable.io/reviews/cockroachdb/cockroach/73117#-MqKa__C5aAwnFj61T-W:-MqKa__C5aAwnFj61T-X:br5elnl) ([raw file](https://github.com/cockroachdb/cockroach/blob/e06079d3bc020e8f135339e56dec2fea23b56abf/pkg/util/tracing/span_inner.go#L233)):*
> ```Go
> 	}
> 	// If the span is redactable, we pay the cost of using the redaction
> 	// library, otherwise we manually do a "coarse" redaction of the
> ```

we're not "doing a redaction" here. Redacting means stripping information. What we're doing is "making the message redactable" by marking it all as sensitive.
___
*[pkg/util/tracing/span_inner.go, line 235 at r30](https://reviewable.io/reviews/cockroachdb/cockroach/73117#-MqKat-K8IIVYWUQZoo_:-MqKat-K8IIVYWUQZooa:bfbnc6m) ([raw file](https://github.com/cockroachdb/cockroach/blob/e06079d3bc020e8f135339e56dec2fea23b56abf/pkg/util/tracing/span_inner.go#L235)):*
> ```Go
> 	// library, otherwise we manually do a "coarse" redaction of the
> 	// entire string to keep the non-redactable path fast.
> 	// Currently we expect this cost to be paid on tenant spans only.
> ```

What's a "tenant span". I think comments about how redactability fits into the bigger picture would fit much better on the tracer's field or on the `tr.SetRedactable()` method.
___
*[pkg/util/tracing/span_inner.go, line 247 at r30](https://reviewable.io/reviews/cockroachdb/cockroach/73117#-MqKb_Wo4DszLtEsrArG:-MqKb_Wo4DszLtEsrArH:b2xpong) ([raw file](https://github.com/cockroachdb/cockroach/blob/e06079d3bc020e8f135339e56dec2fea23b56abf/pkg/util/tracing/span_inner.go#L247)):*
> ```Go
> 		b := strings.Builder{}
> 		b.Write(redact.StartMarker())
> 		// TODO(davidh): Unhandled error here, not sure what I can do though...log it?
> ```

errors here are impossible because `strings.Builder` never returns an error.
If you want to be pedantic, you can write `_ /* err */ = Fprintf()`, but we never do that.
___
*[pkg/util/tracing/span_inner.go, line 254 at r30](https://reviewable.io/reviews/cockroachdb/cockroach/73117#-MqKc7hEBGKik3s0tfvB:-MqKc7hEBGKik3s0tfvC:b5dqde1) ([raw file](https://github.com/cockroachdb/cockroach/blob/e06079d3bc020e8f135339e56dec2fea23b56abf/pkg/util/tracing/span_inner.go#L254)):*
> ```Go
> 		doEscape := false
> 		// Ignore first and last index since we put markers there ourselves
> 		for i := 1; i < len(format)-1; i++ {
> ```

there's `strings.ContainsAny()`
___
*[pkg/util/tracing/span_inner.go, line 262 at r30](https://reviewable.io/reviews/cockroachdb/cockroach/73117#-MqKcFAnCVOsxwEjpeA9:-MqKcFAnCVOsxwEjpeAA:b6txqn6) ([raw file](https://github.com/cockroachdb/cockroach/blob/e06079d3bc020e8f135339e56dec2fea23b56abf/pkg/util/tracing/span_inner.go#L262)):*
> ```Go
> 		if doEscape {
> 			// Override string and redact it if we find there was a marker in
> 			// there This will only run if this particular message had a
> ```

missing periods.
Also s/Override/Overwrite.

I'd strike the second sentence.
___
*[pkg/util/tracing/span_inner.go, line 268 at r30](https://reviewable.io/reviews/cockroachdb/cockroach/73117#-MqKccmvD_aNPqFLiIeB:-MqKccmvD_aNPqFLiIeC:bozscp0) ([raw file](https://github.com/cockroachdb/cockroach/blob/e06079d3bc020e8f135339e56dec2fea23b56abf/pkg/util/tracing/span_inner.go#L268)):*
> ```Go
> 	}
> 	if s.ot.shadowSpan != nil {
> 		// TODO(obs-inf): depending on the situation it may be more appropriate to
> ```

since you're taking the blame around here, please remove the `obs-inf` from this TODO - either put a name or leave it empty. Tobi seems to have used the annotation wrongly, to refer to whom he imagined might do the work instead of referring to a person to which one can address comments.
___
*[pkg/util/tracing/span_inner.go, line 269 at r30](https://reviewable.io/reviews/cockroachdb/cockroach/73117#-MqKc_jP8NpCGFlICim5:-MqKc_jP8NpCGFlICim6:b-izywvr) ([raw file](https://github.com/cockroachdb/cockroach/blob/e06079d3bc020e8f135339e56dec2fea23b56abf/pkg/util/tracing/span_inner.go#L269)):*
> ```Go
> 	if s.ot.shadowSpan != nil {
> 		// TODO(obs-inf): depending on the situation it may be more appropriate to
> 		// redact the string here. Note that redaction markers are not stripped
> ```

I'm not sure what the "either" refers to.

Also, how come you changed this? If you want to change it, consider making it its own commit.
___
*[pkg/util/tracing/span_inner.go, line 270 at r30](https://reviewable.io/reviews/cockroachdb/cockroach/73117#-MqKcRcN2_TBlEhOuiAU:-MqKcRcN2_TBlEhOuiAV:brnpxri) ([raw file](https://github.com/cockroachdb/cockroach/blob/e06079d3bc020e8f135339e56dec2fea23b56abf/pkg/util/tracing/span_inner.go#L270)):*
> ```Go
> 		// TODO(obs-inf): depending on the situation it may be more appropriate to
> 		// redact the string here. Note that redaction markers are not stripped
> 		// here either
> ```

missing period.
___
*[pkg/util/tracing/tracer.go, line 134 at r30](https://reviewable.io/reviews/cockroachdb/cockroach/73117#-MqKa7S65f_4RBDLX2F0:-MqKa7S65f_4RBDLX2F1:b-nnbqrb) ([raw file](https://github.com/cockroachdb/cockroach/blob/e06079d3bc020e8f135339e56dec2fea23b56abf/pkg/util/tracing/tracer.go#L134)):*
> ```Go
> 	_useNetTrace int32 // updated atomically
> 
> 	_redactable int32 // updated atomically
> ```

nit: s/updated atomically/accessed atomically.

It's not just updates that need to be atomic; reads too.
___
*[pkg/util/tracing/tracer.go, line 134 at r30](https://reviewable.io/reviews/cockroachdb/cockroach/73117#-MqKaQqr5erH9-ccTtIM:-MqKaQqr5erH9-ccTtIN:bho3k7l) ([raw file](https://github.com/cockroachdb/cockroach/blob/e06079d3bc020e8f135339e56dec2fea23b56abf/pkg/util/tracing/tracer.go#L134)):*
> ```Go
> 	_useNetTrace int32 // updated atomically
> 
> 	_redactable int32 // updated atomically
> ```

please put a comment on this.
___
*[pkg/util/tracing/tracingpb/recorded_span.proto, line 76 at r30](https://reviewable.io/reviews/cockroachdb/cockroach/73117#-MqK_O8J1WYM8hnGuxee:-MqK_O8J1WYM8hnGuxef:b-ec0iy0) ([raw file](https://github.com/cockroachdb/cockroach/blob/e06079d3bc020e8f135339e56dec2fea23b56abf/pkg/util/tracing/tracingpb/recorded_span.proto#L76)):*
> ```protobuf
>   // This field was introduced in the 22.1 cycle. It can be removed in the 22.2
>   // cycle.
>   bool redactable_logs = 15;
> ```

on master, we should say that 22.2 always sets this, right?

**Review by rimadeodhar — COMMENTED** [review]
> Reviewed 3 of 3 files at r1, 5 of 5 files at r2, 19 of 19 files at r3, 2 of 2 files at r4, 1 of 1 files at r5, 1 of 1 files at r6, 1 of 1 files at r7, 19 of 19 files at r8, 1 of 1 files at r9, 8 of 9 files at r13, 30 of 30 files at r15, 5 of 19 files at r16, 1 of 2 files at r17, 2 of 19 files at r26, 12 of 22 files at r30, 1 of 2 files at r31, 1 of 3 files at r32, 8 of 8 files at r33, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/73117)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @abarganier, @andreimatei, @dhartunian, @knz, @rimadeodhar, and @tbg)

___
*[-- commits, line 6 at r33](https://reviewable.io/reviews/cockroachdb/cockroach/73117#-MqGY6Yn85fxdJucnpFg):*
Release note is still missing here?

**Review by andreimatei — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/73117)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @abarganier, @andreimatei, @dhartunian, @knz, @rimadeodhar, and @tbg)

___
*[-- commits, line 80 at r30](https://reviewable.io/reviews/cockroachdb/cockroach/73117#-MqKr7M663rUXiiavhpa):*
>  The entry is a logEntry that already has the message stringified in it, with redactability in it or not based, I think, on the logging configuration (right?)

Hmm, maybe wrong. 
Maybe the difference that matters is in `log/makeUnstructuredEntry()` between `makeRedactablePayload` vs `makeUnsafePayload`. Is that it? If that's the big one, then the comment in `span.Redactf()` that says
> 	// If the span is redactable, we pay the cost of using the redaction
	// library, otherwise we manually do a "coarse" redaction of the

is very misleading, cause the cost has already been paid.

**Review by andreimatei — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/73117)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @abarganier, @andreimatei, @dhartunian, @knz, @rimadeodhar, and @tbg)

___
*[-- commits, line 80 at r30](https://reviewable.io/reviews/cockroachdb/cockroach/73117#-MqKr7M663rUXiiavhpa):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

>  The entry is a logEntry that already has the message stringified in it, with redactability in it or not based, I think, on the logging configuration (right?)

Hmm, maybe wrong. 
Maybe the difference that matters is in `log/makeUnstructuredEntry()` between `makeRedactablePayload` vs `makeUnsafePayload`. Is that it? If that's the big one, then the comment in `span.Redactf()` that says
> 	// If the span is redactable, we pay the cost of using the redaction
	// library, otherwise we manually do a "coarse" redaction of the

is very misleading, cause the cost has already been paid.
</blockquote></details>

If this is all true, I'm thinking a better code structure would be to move away from the logging library calling `span.Recordf()` like every random schmuck. Instead, it could have a dedicated `RecordLog(logEntry)` method (with `logEntry` moved to a base package to avoid circular deps), and that method would not care more about `logEntry.payload.Redactable` rather then caring about `span.Redactable`. This way, we'd acknowledge the fact that the redactability of the `logEntry` has already taken the span's redactability into account.

**Review by dhartunian — COMMENTED** [review]
> nit: when pushing updates, it's nice to rewrite all commits, so the last versions of all commits appear as a contiguous span in Reviewable. At least on master, you get that naturally by rebasing on a fresh tip before pushing.

Thx for the tip. I will rebase entire tree before pushing.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/73117#-:-MqLP8sH52JJvYXFDl3_:btrufhu)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @abarganier, @andreimatei, @knz, @rimadeodhar, and @tbg)

___
*[-- commits, line 71 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/73117#-MpwY14K5v2nIAUBevbv):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

I'm confused about what `old` is here
</blockquote></details>

clarified in new commit msg.
___
*[-- commits, line 80 at r30](https://reviewable.io/reviews/cockroachdb/cockroach/73117#-MqKr7M663rUXiiavhpa):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

If this is all true, I'm thinking a better code structure would be to move away from the logging library calling `span.Recordf()` like every random schmuck. Instead, it could have a dedicated `RecordLog(logEntry)` method (with `logEntry` moved to a base package to avoid circular deps), and that method would not care more about `logEntry.payload.Redactable` rather then caring about `span.Redactable`. This way, we'd acknowledge the fact that the redactability of the `logEntry` has already taken the span's redactability into account.
</blockquote></details>

Ok I think I understand a bit what was going on here. The big cost does get paid in the `event_internal` call which chooses to use the FastString/LegacyString method in the non-redactable path. I do not think this code was adding anything significant unless we omit redaction markers entirely via:
`redact.RedactableString(fmt.Sprintf(format, args...))`
___
*[-- commits, line 126 at r30](https://reviewable.io/reviews/cockroachdb/cockroach/73117#-MqKtrFr0p1-xtHHVGdO):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

3 benchmarks? I think I only see 2?
</blockquote></details>

New benchmarks added in modified PR.
___
*[-- commits, line 133 at r30](https://reviewable.io/reviews/cockroachdb/cockroach/73117#-MqKX3AL-_exFEhiKYQ4):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

`trace.debug.enable` is the `net/Trace` stuff, right? `net.Trace` is very expensive - and also pretty useless; it comes to dominate the benchmark. To get something more representative, you want the `threshold` cluster setting.
</blockquote></details>

I am using the threshold setting when computing benchmarks on `release-21.2`. Will update with those.
___
*[-- commits, line 140 at r30](https://reviewable.io/reviews/cockroachdb/cockroach/73117#-MqKsn6O6cZhKDv38oFz):*
> The base is "no redaction", and this patch improves the performance? How come?
> Is "where tracing redaction isn't really introduced at all" wrong?

I'll post new benches after pushing the new code and running them on `gceworker`. I seem to get a lot of variation on my mac.
___
*[-- commits, line 6 at r33](https://reviewable.io/reviews/cockroachdb/cockroach/73117#-MqGY6Yn85fxdJucnpFg):*
<details><summary><i>Previously, rimadeodhar (Rima Deodhar) wrote…</i></summary><blockquote>

Release note is still missing here?
</blockquote></details>

Restored reverted commit msg.
___
*[pkg/server/node_tenant.go, line 20 at r30](https://reviewable.io/reviews/cockroachdb/cockroach/73117#-MqKYqlV68ie2hiYrkyT:-MqLRptp8A8xTAxkXtIR:b-1jy83j) ([raw file](https://github.com/cockroachdb/cockroach/blob/e06079d3bc020e8f135339e56dec2fea23b56abf/pkg/server/node_tenant.go#L20)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

can it really not be `const` with the new type?
</blockquote></details>

it can!
___
*[pkg/server/node_tenant.go, line 46 at r30](https://reviewable.io/reviews/cockroachdb/cockroach/73117#-MqKZL9Z7PvXaILoyzkv:-MqLRxSlDZmM7G15LO0A:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/e06079d3bc020e8f135339e56dec2fea23b56abf/pkg/server/node_tenant.go#L46)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

if you're moving away from the if/else structure, do it all the way and get rid of this `else`
</blockquote></details>

Done.
___
*[pkg/util/log/log_entry.go, line 136 at r30](https://reviewable.io/reviews/cockroachdb/cockroach/73117#-MqKpequ0IAjruW15ERf:-MqLT0HrB2rsUG9xECfS:b-g1lhn2) ([raw file](https://github.com/cockroachdb/cockroach/blob/e06079d3bc020e8f135339e56dec2fea23b56abf/pkg/util/log/log_entry.go#L136)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

well, is it "legacy" or isn't it? If this method stays as it is, I think we need to give it a better name.
But perhaps the right thing to do is make it the `String` method on `logpb.Entry` (i.e. inhibit the proto compiler for generating one).

</blockquote></details>

Renaming to `FastString`. Not sure what the consequences would be of overriding `logpb.Entry.String()` since the type is in use quite a bit still.
___
*[pkg/util/log/log_entry.go, line 164 at r30](https://reviewable.io/reviews/cockroachdb/cockroach/73117#-MqKpApADN240GQxBBpC:-MqQUN8M3vmzvBWaQ6tF:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/e06079d3bc020e8f135339e56dec2fea23b56abf/pkg/util/log/log_entry.go#L164)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

this comment doesn't seem appropriate. I'm not sure how to improve it, but perhaps you do?
</blockquote></details>

Done.
___
*[pkg/util/tracing/crdbspan.go, line 43 at r30](https://reviewable.io/reviews/cockroachdb/cockroach/73117#-MqKdwLuC5ws27hhA73R:-MqQTrOx8GHhMM1a4e3E:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/e06079d3bc020e8f135339e56dec2fea23b56abf/pkg/util/tracing/crdbspan.go#L43)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

Are you sure we're gaining anything by capturing this snapshot of the tracer state in spans? Read-only sharing of the tracer's atomic should be cheap. In fact, in the case when spans are created but not recording (which I'm trying to make the default), you'd save by not having to populate this field.
</blockquote></details>

Done.
___
*[pkg/util/tracing/crdbspan.go, line 43 at r30](https://reviewable.io/reviews/cockroachdb/cockroach/73117#-MqKdQa76soX8yjhQ5vZ:-MqQTsipEDCtPJTUivhj:bss4a2b) ([raw file](https://github.com/cockroachdb/cockroach/blob/e06079d3bc020e8f135339e56dec2fea23b56abf/pkg/util/tracing/crdbspan.go#L43)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

nit: I think this phrasing of the comment as a question is confusing.

Also please make a reference to the `mu.recording.recordingType` field.
</blockquote></details>

Removed.
___
*[pkg/util/tracing/span.go, line 68 at r30](https://reviewable.io/reviews/cockroachdb/cockroach/73117#-MqKfOGS7iF4mCJ-Vd7w:-MqLaNrV3Bk2YyJ9mwSP:b-698bvp) ([raw file](https://github.com/cockroachdb/cockroach/blob/e06079d3bc020e8f135339e56dec2fea23b56abf/pkg/util/tracing/span.go#L68)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

nit: wrapping
</blockquote></details>

This code was removed.
___
*[pkg/util/tracing/span.go, line 69 at r30](https://reviewable.io/reviews/cockroachdb/cockroach/73117#-MqKgqXW-FRJD35fDAo9:-MqLaOzRBlCsG9X11Xpr:bad6kck) ([raw file](https://github.com/cockroachdb/cockroach/blob/e06079d3bc020e8f135339e56dec2fea23b56abf/pkg/util/tracing/span.go#L69)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

> ```
> // Redactable returns true if this Span records
> // redactable logs.
> ```

That's not technically true, is it? The return value of this method has nothing to do with whether the span is recording or not.

Instead of making this a public method, consider bundling the redactability info into the result of `getSpanOrEventLog()` - maybe make that guy return a struct.
If this method is not public any more, you wouldn't have to worry about the `nil` or `noop` cases; in fact, you could make it a method on the `crdbSpan` instead, to make the tangling of the redactability concept and the existence of a `crdbSpan` painfully visible to all caller.

</blockquote></details>

Removed this code.
___
*[pkg/util/tracing/span_inner.go, line 233 at r30](https://reviewable.io/reviews/cockroachdb/cockroach/73117#-MqKa__C5aAwnFj61T-W:-MqLO8ejCM-A-cxtLBmU:b-q1bu4x) ([raw file](https://github.com/cockroachdb/cockroach/blob/e06079d3bc020e8f135339e56dec2fea23b56abf/pkg/util/tracing/span_inner.go#L233)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

we're not "doing a redaction" here. Redacting means stripping information. What we're doing is "making the message redactable" by marking it all as sensitive.
</blockquote></details>

This code is gone.
___
*[pkg/util/tracing/span_inner.go, line 235 at r30](https://reviewable.io/reviews/cockroachdb/cockroach/73117#-MqKat-K8IIVYWUQZoo_:-MqLJwv25qK_ernpZUdR:b-q1bu4x) ([raw file](https://github.com/cockroachdb/cockroach/blob/e06079d3bc020e8f135339e56dec2fea23b56abf/pkg/util/tracing/span_inner.go#L235)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

What's a "tenant span". I think comments about how redactability fits into the bigger picture would fit much better on the tracer's field or on the `tr.SetRedactable()` method.
</blockquote></details>

This code is gone.
___
*[pkg/util/tracing/span_inner.go, line 247 at r30](https://reviewable.io/reviews/cockroachdb/cockroach/73117#-MqKb_Wo4DszLtEsrArG:-MqLHvFo9H2SSgGbuVz-:b-q1bu4x) ([raw file](https://github.com/cockroachdb/cockroach/blob/e06079d3bc020e8f135339e56dec2fea23b56abf/pkg/util/tracing/span_inner.go#L247)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

errors here are impossible because `strings.Builder` never returns an error.
If you want to be pedantic, you can write `_ /* err */ = Fprintf()`, but we never do that.
</blockquote></details>

This code is gone.
___
*[pkg/util/tracing/span_inner.go, line 254 at r30](https://reviewable.io/reviews/cockroachdb/cockroach/73117#-MqKc7hEBGKik3s0tfvB:-MqLJ7LR5jXuOF9GEaEX:b-q1bu4x) ([raw file](https://github.com/cockroachdb/cockroach/blob/e06079d3bc020e8f135339e56dec2fea23b56abf/pkg/util/tracing/span_inner.go#L254)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

there's `strings.ContainsAny()`
</blockquote></details>

This code is gone.
___
*[pkg/util/tracing/span_inner.go, line 262 at r30](https://reviewable.io/reviews/cockroachdb/cockroach/73117#-MqKcFAnCVOsxwEjpeA9:-MqLJABg7hOWoK7SSiHt:b-q1bu4x) ([raw file](https://github.com/cockroachdb/cockroach/blob/e06079d3bc020e8f135339e56dec2fea23b56abf/pkg/util/tracing/span_inner.go#L262)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

missing periods.
Also s/Override/Overwrite.

I'd strike the second sentence.
</blockquote></details>

This code is gone.
___
*[pkg/util/tracing/span_inner.go, line 268 at r30](https://reviewable.io/reviews/cockroachdb/cockroach/73117#-MqKccmvD_aNPqFLiIeB:-MqLJP7S5PuoWVOgqFxP:b-3cr5wk) ([raw file](https://github.com/cockroachdb/cockroach/blob/e06079d3bc020e8f135339e56dec2fea23b56abf/pkg/util/tracing/span_inner.go#L268)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

since you're taking the blame around here, please remove the `obs-inf` from this TODO - either put a name or leave it empty. Tobi seems to have used the annotation wrongly, to refer to whom he imagined might do the work instead of referring to a person to which one can address comments.
</blockquote></details>

No longer touching this code. Comment change removed.
___
*[pkg/util/tracing/span_inner.go, line 269 at r30](https://reviewable.io/reviews/cockroachdb/cockroach/73117#-MqKc_jP8NpCGFlICim5:-MqLJREO2Z1L80H_kPV1:b-vpdxzj) ([raw file](https://github.com/cockroachdb/cockroach/blob/e06079d3bc020e8f135339e56dec2fea23b56abf/pkg/util/tracing/span_inner.go#L269)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

I'm not sure what the "either" refers to.

Also, how come you changed this? If you want to change it, consider making it its own commit.
</blockquote></details>

Undid this.
___
*[pkg/util/tracing/span_inner.go, line 270 at r30](https://reviewable.io/reviews/cockroachdb/cockroach/73117#-MqKcRcN2_TBlEhOuiAU:-MqLJSrl5jxqDxfE2Iii:b-45elh5) ([raw file](https://github.com/cockroachdb/cockroach/blob/e06079d3bc020e8f135339e56dec2fea23b56abf/pkg/util/tracing/span_inner.go#L270)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

missing period.
</blockquote></details>

Done. This message was removed.
___
*[pkg/util/tracing/tracer.go, line 134 at r30](https://reviewable.io/reviews/cockroachdb/cockroach/73117#-MqKa7S65f_4RBDLX2F0:-MqLObhR49pUABLOYfVp:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/e06079d3bc020e8f135339e56dec2fea23b56abf/pkg/util/tracing/tracer.go#L134)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

nit: s/updated atomically/accessed atomically.

It's not just updates that need to be atomic; reads too.
</blockquote></details>

Done.
___
*[pkg/util/tracing/tracer.go, line 134 at r30](https://reviewable.io/reviews/cockroachdb/cockroach/73117#-MqKaQqr5erH9-ccTtIM:-MqLOcD15yyox99zRtnp:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/e06079d3bc020e8f135339e56dec2fea23b56abf/pkg/util/tracing/tracer.go#L134)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

please put a comment on this.
</blockquote></details>

Done.
___
*[pkg/util/tracing/tracingpb/recorded_span.proto, line 27 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/73117#-Mpw_w5U1rJoQZu8I_Lt:-MqLOkA09KvVAYtzgHS0:b-jdosq9) ([raw file](https://github.com/cockroachdb/cockroach/blob/9b0bcb170fc0576b314786abc6a83282ca67dc91/pkg/util/tracing/tracingpb/recorded_span.proto#L27)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

> At this point, I also worry that introducing redaction to traces without some configurability will be another point version surprise to non-serverless customers so I'd prefer to avoid it.


I'm not saying remove any configurability. I'm saying represent "non-redactable" messages as a string without internal markers surrounded by exactly one pair of markers. Then, technically, there would be no such thing as a "non-redactable" trace. Instead there'd fine-grained redactable traces, and course-grained redactable ones (the course grained ones would basically be fully redacted if anyone redacts them). So, when redactability is enabled, the messages would be produced by `sp.Recordf`, and when it's disabled, they would be produced as `marker + escapeMarkers(entry.LegacyString) + marker`.
Generally the escaping of internal characters would be a fast no-op.
Does this compute?
</blockquote></details>

Done. This suggestion has been incorporated.
___
*[pkg/util/tracing/tracingpb/recorded_span.proto, line 76 at r30](https://reviewable.io/reviews/cockroachdb/cockroach/73117#-MqK_O8J1WYM8hnGuxee:-MqLOzzE6YxUlm5XrfAg:b-tg204j) ([raw file](https://github.com/cockroachdb/cockroach/blob/e06079d3bc020e8f135339e56dec2fea23b56abf/pkg/util/tracing/tracingpb/recorded_span.proto#L76)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

on master, we should say that 22.2 always sets this, right?
</blockquote></details>

Can you clarify what you mean here?

**Review by andreimatei — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/73117)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @abarganier, @andreimatei, @dhartunian, @knz, @rimadeodhar, and @tbg)

___
*[pkg/util/tracing/tracingpb/recorded_span.proto, line 73 at r36](https://reviewable.io/reviews/cockroachdb/cockroach/73117#-MqUqA4bEibvdq6PvuHO:-MqUqA4bEibvdq6PvuHP:b-3obrhw) ([raw file](https://github.com/cockroachdb/cockroach/blob/3881ad7eb50e9f8f96c840827602b28c40ab6d55/pkg/util/tracing/tracingpb/recorded_span.proto#L73)):*
> ```protobuf
>                                          (gogoproto.stdduration) = true];
> 
>   // RedactableLogs determines whether the verbose log messages are redactable.
> ```

I know this commit is a revert, but this comment is wrong. Please fix it somewhere.

But also, can you please explain to me if we need to introduce this field? As I understand it, the current serveless version has this field and it always sets it. The version that will roll out with this patch only needs compatibility with the serverless version, not with 21.1, right? So then, can we do without this field and assume that all the messages are redactable?
And on master (22.1), also get rid of the field and assume that we only need compatibility with versions that only have redactable traces?

**Comment by dhartunian** [comment]
@andreimatei field is removed. I agree it's unnecessary. Also added a small change on top to implement the manual improvement over `redact.Sprintf`.

**Review by andreimatei — APPROVED** [review]
:LGTM: but I wouldn't include the last commit.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/73117#-:-MqVcN2W8qeK02Ejxh7I:bjfkw95)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @abarganier, @andreimatei, @dhartunian, @knz, @rimadeodhar, and @tbg)

___
*[pkg/util/tracing/span_inner.go, line 240 at r46](https://reviewable.io/reviews/cockroachdb/cockroach/73117#-MqVbMsG7lXzUmf44u4w:-MqVbMsG7lXzUmf44u4x:b-1eq2b0) ([raw file](https://github.com/cockroachdb/cockroach/blob/609c51a5ce6d342a2249a1000be4001456c4a833/pkg/util/tracing/span_inner.go#L240)):*
> ```Go
> 		// also avoiding using `redact.Sprintf("%s"...) to save on
> 		// allocations.
> 		s := fmt.Sprintf(format, args...)
> ```

@knz, instead of this, can we teach `redact.Sprintf("%s", string)` to do this? Or, second best, add a dedicated method to `redact` to do it? I think it must be a common enough case, and I don't really want this code here - too many inscrutable lines.

I don't feel the need for this commit on 21.2, particularly since this is breaking protocol and putting release-21.2 ahead of master.
___
*[pkg/util/tracing/tracingpb/recorded_span.proto, line 76 at r44](https://reviewable.io/reviews/cockroachdb/cockroach/73117#-MqVacqa8G_KgY2As_V1:-MqVacqa8G_KgY2As_V2:btoof7p) ([raw file](https://github.com/cockroachdb/cockroach/blob/77017298edd79ad942296fdf1f736b771c105d5c/pkg/util/tracing/tracingpb/recorded_span.proto#L76)):*
> ```protobuf
>   // This field was introduced in the 22.1 release. It can be removed in the 22.2
>   // release. On 22.1 this is always set to `true`.
>   bool redactable_logs = 15;
> ```

reserve the field number. This should have been done when the commit introducing it was first reverted.
