### PR TITLE
sql: fix lease interaction with offline tables

### LINKED ISSUE #40951: backup: TableDescriptor's being seen in offline mode when they should be public
**Describe the problem**

Please describe the issue you observed, and any steps we can take to reproduce it:
There have been flakes in several tests that require the test to wait up to 5 seconds for a RESTORed/IMPORTed table to be no longer seen as offline.

**To Reproduce**

Run the `TestBackupRestoreWithConcurrentWrites` test under stress (be sure to remove the code the adds the 5 second delay).

**Expected behavior**
The table descriptor should no longer be visible in the offline state as soon as the RESTORE or IMPORT completes.

**Additional data / screenshots**
According to the [table descriptor lease RFC](https://github.com/cockroachdb/cockroach/blob/master/docs/RFCS/20151009_table_descriptor_lease.md), table leases may be held for up to 2 version changes (which may explain why we're seeing table descriptors one version behind).

Preliminary experiments have been done to add an intermediary state and `OnSuccess` of the job mark the table as `PUBLIC_STAGING` then `PUBLIC`. However, when the test is run under stress we still see failures.

**Additional context**
What was the impact?
- Test flakiness

### PR DESCRIPTION
**Pull request by pbardea**
This updates the lease management code to handle offline tables the
same way dropped tables are handled. We are not supposed to be able
to acquire a lease on offline tables (as well as dropped tables).

Fixes #40951 and therefore #40361.

Release justification: Fixes test flakes where a table descriptor lease
is being taken on an offline table.

Release note: None

### CODE REVIEW

File: pkg/sql/table.go [hunk 1]
```diff
@@ -284,7 +288,7 @@ func (tc *TableCollection) getTableVersion(
 		// Read the descriptor from the store in the face of some specific errors
 		// because of a known limitation of AcquireByName. See the known
 		// limitations of AcquireByName for details.
-		if err == errTableDropped || err == sqlbase.ErrDescriptorNotFound {
```
Comment (dt) [inline pkg/sql/table.go]: nice catch!

**Review by dt — APPROVED** [review]

**Comment by pbardea** [comment]
bors r=dt

File: pkg/ccl/importccl/import_stmt_test.go [hunk 2]
```diff
@@ -1597,7 +1597,7 @@ func TestImportIntoCSV(t *testing.T) {
 			<-importBodyFinished
 
 			err := sqlDB.DB.QueryRowContext(ctx, `SELECT 1 FROM t`).Scan(&unused)
-			if !testutils.IsError(err, "table \"t\" is offline: importing") {
+			if !testutils.IsError(err, "relation \"t\" does not exist") {
```
Comment (dt) [inline pkg/ccl/importccl/import_stmt_test.go]: not a blocker to a correctness fix, but I did kinda like the more descriptive user-visible error message (and we'd gotten feedback that liked the importing message from others as well).

Comment (pbardea) [reply pkg/ccl/importccl/import_stmt_test.go]: so the summary here is that the error we were catching was the one thrown when failing to get a lease on the table. this isn't exactly what we want - we want to see the table in the offline state and return it.

the actual PR that changed the error that we're returning here is #40285. That PR changed the logic from returning an error if the table was in a DROP of OFFLINE state to just reporting the object it was looking for as not there.

Comment (pbardea) [reply pkg/ccl/importccl/import_stmt_test.go]: Looking in more detail, it looks like that PR (40285) doesn't actually affect this as the behaviour described (returning no object found instead of the error) was always what was happening.

**Comment by nvanbenschoten** [comment]
Thanks for tracking this down @pbardea.

**Comment by nvanbenschoten** [comment]
Did you mean to close #40361 with this PR?

**Comment by pbardea** [comment]
Yep, thanks for catching that.
