### PR TITLE
fix up coalesced heartbeats

### LINKED ISSUE #1003: range replication exposed multiraft instability
From the cockroach-db mailing list, original message below. a PR is upcoming.

===

I tried to set up the cockroachdb with 3 nodes cluster. But it failed to get work.
The command and logs as below:

The 1 node:
./cockroach init --stores=hdd="/data/cockroach"
./cockroach start --stores=hdd="/data/cockroach" --insecure=true --gossip=10.200.180.17:8080 > cockroach.log 2>&1 &

The node 2 and 3:

./cockroach start --stores=hdd="/data/cockroach" --insecure=true --gossip=10.200.180.17:8080 > cockroach.log 2>&1 &

It is ok when I just start the node 2, however error logs appeared when I start the node 3.

logs on node1:

```
I0512 20:40:55.155581   12259 server.go:129] gossip: client 10.200.180.19:8080 sent 3 info(s)
I0512 20:40:57.318806   12259 server.go:129] gossip: client 10.200.180.19:8080 sent 3 info(s)
I0512 20:40:57.319084   12259 server.go:129] gossip: client 10.200.180.17:8080 sent 3 info(s)
I0512 20:40:59.482230   12259 server.go:129] gossip: client 10.200.180.18:8080 sent 3 info(s)
I0512 20:40:59.482501   12259 server.go:129] gossip: client 10.200.180.19:8080 sent 3 info(s)
I0512 20:41:00.074627   12259 store.go:559] gossiping first range on store 1, range 1
E0512 20:41:00.463670   12259 range.go:774] error executing raft command InternalLeaderLease: node 2, store 2: previous lease 1431434460.332413197,0-1431434461.461421728,0@4294967297 overlaps 1431434460.463000774,0-1431434461.463000774,0@8589934594 (effective 1431434460.463000774,0)
I0512 20:41:01.645720   12259 server.go:129] gossip: client 10.200.180.18:8080 sent 5 info(s)
```

logs on node 2:
```
I0512 20:41:30.467027   13760 store.go:581] gossiping configuration map on store 2, range 1: zones
I0512 20:41:45.462903   13760 store.go:559] gossiping first range on store 2, range 1
I0512 20:42:00.462903   13760 store.go:559] gossiping first range on store 2, range 1
W0512 20:42:00.464797   13760 range.go:904] could not acquire lease for first range gossip: node 2, store 2: previous lease 1431434520.332798243,0-1431434521.461497784,0@4294967297 overlaps 1431434520.462976694,0-1431434521.462976694,0@8589934594 (effective 1431434520.462976694,0)
W0512 20:42:00.464816   13760 store.go:523] error gossiping first range data: node 2, store 2: previous lease 1431434520.332798243,0-1431434521.461497784,0@4294967297 overlaps 1431434520.462976694,0-1431434521.462976694,0@8589934594 (effective 1431434520.462976694,0)
I0512 20:42:15.462972   13760 store.go:559] gossiping first range on store 2, range 1
I0512 20:42:30.462904   13760 store.go:581] gossiping configuration map on store 2, range 1: accounting
I0512 20:42:30.462913   13760 store.go:559] gossiping first range on store 2, range 1
W0512 20:42:30.465397   13760 range.go:904] could not acquire lease for first range gossip: node 2, store 2: previous lease 1431434550.332598686,0-1431434551.461384296,0@4294967297 overlaps 1431434550.462967396,0-1431434551.462967396,0@8589934594 (effective 1431434550.462967396,0)
W0512 20:42:30.465432   13760 store.go:542] error gossiping configs: node 2, store 2: previous lease 1431434550.332598686,0-1431434551.461384296,0@4294967297 overlaps 1431434550.462967396,0-1431434551.462967396,0@8589934594 (effective 1431434550.462967396,0)
I0512 20:42:45.462927   13760 store.go:559] gossiping first range on store 2, range 1
I0512 20:43:00.462910   13760 store.go:559] gossiping first range on store 2, range 1
W0512 20:43:00.464851   13760 range.go:904] could not acquire lease for first range gossip: node 2, store 2: previous lease 1431434580.332668066,0-1431434581.461508274,0@4294967297 overlaps 1431434580.462988615,0-1431434581.462988615,0@8589934594 (effective 1431434580.462988615,0)
```

logs on node 3:

```
I0512 20:40:19.332284   30054 node.go:255] Started node with [[hdd]=/data/cockroach] engine(s) and attributes []
I0512 20:40:19.332344   30054 server.go:175] starting http server at bc-r6app7:8080
I0512 20:40:19.332438   30054 node.go:339] bootstrapping 1 store(s)
I0512 20:40:19.334855   30054 node.go:366] bootstrapped store store=3:3 ([hdd]=/data/cockroach)
W0512 20:40:29.336628   30054 dist_sender.go:555] failed to invoke InternalMerge: replica node_id:"\002" store_id:"\002" attrs:<attrs:"hdd" >  not leader; leader is node_id:"\001" store_id:"\001" attrs:<>
I0512 20:40:29.336976   30054 retry.go:94] routing InternalMerge rpc failed; retrying immediately
I0512 20:43:15.084569   30054 multiraft.go:496] node 300000003: got message for unknown group 1; creating it
W0512 20:43:15.104981   30054 multiraft.go:209] node 300000003: not fanning out heartbeat from unknown node 200000002 (but responding anyway)
E0512 20:43:15.105439   30054 raft_transport.go:137] raft message failed: raft_transport.go:86: Unable to proxy message to node: 0
W0512 20:43:15.132829   30054 multiraft.go:209] node 300000003: not fanning out heartbeat from unknown node 200000002 (but responding anyway)
E0512 20:43:15.133203   30054 raft_transport.go:137] raft message failed: raft_transport.go:86: Unable to proxy message to node: 0
W0512 20:43:15.162966   30054 multiraft.go:209] node 300000003: not fanning out heartbeat from unknown node 200000002 (but responding anyway)
E0512 20:43:15.163421   30054 raft_transport.go:137] raft message failed: raft_transport.go:86: Unable to proxy message to node: 0
W0512 20:43:15.192925   30054 multiraft.go:209] node 300000003: not fanning out heartbeat from unknown node 200000002 (but responding anyway)
E0512 20:43:15.193529   30054 raft_transport.go:137] raft message failed: raft_transport.go:86: Unable to proxy message to node: 0
```

### PR DESCRIPTION
**Pull request by tbg**
- use multiraft.sendMessage, which will set up the transport if the recipient
  is new.
- missing To: in one of the heartbeat messages wreaked havoc

these two points were the main culprit in #1003. when starting a fresh cluster,
after 10minutes the replication queue would kick in and begin replicating the
first range two one of the two other nodes. misaddressed heartbeats would then
quickly fill the log and prevent the replication from going through.

this fixes #1003.

### CODE REVIEW

File: multiraft/multiraft.go [hunk 1]
```diff
@@ -908,8 +899,14 @@ func (s *state) sendMessage(groupID uint64, msg raftpb.Message) {
 		if log.V(4) {
 			log.Infof("node %v: connecting to new node %v", s.nodeID, nodeID)
 		}
-		if err := s.addNode(nodeID, groupID); err != nil {
-			log.Errorf("node %v: error adding node %v", s.nodeID, nodeID)
+		if err := s.addNode(nodeID); err != nil {
```
Comment (bdarnell) [inline multiraft/multiraft.go]: We should either call addNode(nodeID) or addNode(nodeID, groupID), but not both.

File: multiraft/multiraft.go [hunk 2]
```diff
@@ -908,8 +899,14 @@ func (s *state) sendMessage(groupID uint64, msg raftpb.Message) {
...
+			log.Errorf("node %v: error adding node %v: %v", s.nodeID, nodeID, err)
+		}
+		if groupID > 0 {
```
Comment (bdarnell) [inline multiraft/multiraft.go]: This should probably be `groupID != noGroup`.

**Comment by bdarnell** [comment]
The change LGTM, but we should really figure out how to write a test for this. It was broken once, it could easily break again.

LocalRPCTransport.Send should fail if `id` and `req.To` differ. (in fact, we should probably get rid of the `id` parameter and just use `req.To`)

**Comment by tschottdorf** [comment]
PTAL @bdarnell

**Comment by bdarnell** [comment]
LGTM.
