### PR TITLE
changefeedccl: signal changeAggregator shutdown from the kvfeed

### LINKED ISSUE #68791: changefeeds fail to restart/exit when encountering some schema changes
**Describe the problem**

Certain schema changes should result in a changefeed restart:

- `ALTER TABLE .. SET LOCALITY REGIONAL BY ROW`
- `ALTER TABLE .. ALTER PRIMARY KEY ...`

The restart is required to ensure that we start new rangefeeds on the new index that that these schema changes create.

Further when the user specifies `schema_change_policy=stop` schema changes such as `ALTER TABLE ... ADD COLUMN .. DEFUALT ..` should result in the changefeed permanently exiting.

However, we've observed some cases where the changefeed fails to exit or restart correctly.  In these cases, the changefeed appears to still be running, but no newly inserted rows or resolved timestamps will be sent to the sink.

Internally in nn such cases, what we've found so far is that the `kvFeed` encounters the schema change, forwards Resolved spans with the appropriate schema change boundary type set to the `changeAggregator` and attempts to exit. Further the `changeAggregator` correctly forwards the schema change boundary to the `changeFrontier`. The changeFrontier advances to the boundary and attempts to exit.  However, it appears that at this point we can become deadlocked (the exact cause of the deadlock is not known).

For example, below are some of the relevant Goroutines from a 3-node cluster where this occurred.  Nodes 1 and 2 are the nodes involved in the changefeed, with the changeAggregator running on Node 2 and the changeFrontier on Node 1.

<details><summary>Some Node 1 Goroutines</summary>

```
goroutine 17754 [chan receive, 7 minutes]:
github.com/cockroachdb/cockroach/pkg/ccl/changefeedccl.(*changeFrontier).Start.func1(0x66a3068, 0xc003f06300, 0xc0033aea80)
        /go/src/github.com/cockroachdb/cockroach/pkg/ccl/changefeedccl/changefeed_processors.go:1134 +0x48
created by github.com/cockroachdb/cockroach/pkg/ccl/changefeedccl.(*changeFrontier).Start
        /go/src/github.com/cockroachdb/cockroach/pkg/ccl/changefeedccl/changefeed_processors.go:1133 +0x43b

goroutine 17752 [select, 6 minutes]:
github.com/cockroachdb/cockroach/pkg/ccl/changefeedccl.(*kafkaSink).workerLoop(0xc0044c23c0)
        /go/src/github.com/cockroachdb/cockroach/pkg/ccl/changefeedccl/sink_kafka.go:338 +0x155
created by github.com/cockroachdb/cockroach/pkg/ccl/changefeedccl.(*kafkaSink).start
        /go/src/github.com/cockroachdb/cockroach/pkg/ccl/changefeedccl/sink_kafka.go:164 +0x8b

goroutine 17682 [chan receive, 6 minutes]:
github.com/cockroachdb/cockroach/pkg/sql/execinfra.(*RowChannel).Next(0xc003ed01e0, 0xc003747490, 0x1, 0x1, 0x4e1a45)
        /go/src/github.com/cockroachdb/cockroach/pkg/sql/execinfra/base.go:508 +0x4a
github.com/cockroachdb/cockroach/pkg/sql/execinfra.(*ProcessorBaseNoHelper).DrainHelper(0xc0033aea80, 0xc002c2a5d8)
        /go/src/github.com/cockroachdb/cockroach/pkg/sql/execinfra/processorsbase.go:571 +0xac
github.com/cockroachdb/cockroach/pkg/ccl/changefeedccl.(*changeFrontier).Next(0xc0033aea80, 0x34d10769, 0xc000bd0000, 0xc0044c23c0, 0xc000ba9380)
        /go/src/github.com/cockroachdb/cockroach/pkg/ccl/changefeedccl/changefeed_processors.go:1234 +0x4d6
github.com/cockroachdb/cockroach/pkg/sql/execinfra.DrainAndForwardMetadata(0x66a3068, 0xc003f06300, 0x66c3458, 0xc0033aea80, 0x665abc8, 0xc00350c000)
        /go/src/github.com/cockroachdb/cockroach/pkg/sql/execinfra/base.go:228 +0x63
github.com/cockroachdb/cockroach/pkg/sql/execinfra.Run(0x66a3068, 0xc003f06300, 0x66c3458, 0xc0033aea80, 0x665abc8, 0xc00350c000)
        /go/src/github.com/cockroachdb/cockroach/pkg/sql/execinfra/base.go:193 +0x105
github.com/cockroachdb/cockroach/pkg/sql/execinfra.(*ProcessorBaseNoHelper).Run(0xc0033aea80, 0x66a3068, 0xc003f06300)
        /go/src/github.com/cockroachdb/cockroach/pkg/sql/execinfra/processorsbase.go:731 +0x90
github.com/cockroachdb/cockroach/pkg/sql/flowinfra.(*FlowBase).Run(0xc00350a420, 0x66a3068, 0xc003f06300, 0x56ee700)
        /go/src/github.com/cockroachdb/cockroach/pkg/sql/flowinfra/flow.go:418 +0x2c4
github.com/cockroachdb/cockroach/pkg/sql.(*DistSQLPlanner).Run(0xc001e99590, 0xc001dff5e0, 0x0, 0xc0049d91e8, 0xc003eadc00, 0xc004222e00, 0xc0049d9088, 0x0)
        /go/src/github.com/cockroachdb/cockroach/pkg/sql/distsql_running.go:525 +0x4d7
github.com/cockroachdb/cockroach/pkg/ccl/changefeedccl/changefeeddist.StartDistChangefeed(0x66a3110, 0xc0014b4090, 0x6703180, 0xc001986468, 0x97cb833750b0001, 0xc004032ff0, 0xc002e9fa20, 0x1a, 0xc004032fc0, 0x169a4a37f1ed281a, ...)
        /go/src/github.com/cockroachdb/cockroach/pkg/ccl/changefeedccl/changefeeddist/distflow.go:144 +0xac6
github.com/cockroachdb/cockroach/pkg/ccl/changefeedccl.distChangefeedFlow(0x66a3110, 0xc0014b4090, 0x6703180, 0xc001986468, 0x97cb833750b0001, 0xc004032ff0, 0xc002e9fa20, 0x1a, 0xc004032fc0, 0x169a4a37f1ed281a, ...)
        /go/src/github.com/cockroachdb/cockroach/pkg/ccl/changefeedccl/changefeed_dist.go:117 +0x387
github.com/cockroachdb/cockroach/pkg/ccl/changefeedccl.(*changefeedResumer).resumeWithRetries(0xc002bd8490, 0x66a3110, 0xc0014b4090, 0x6703180, 0xc001986468, 0x97cb833750b0001, 0xc004032ff0, 0xc002e9fa20, 0x1a, 0xc004032fc0, ...)
        /go/src/github.com/cockroachdb/cockroach/pkg/ccl/changefeedccl/changefeed_stmt.go:681 +0x215
github.com/cockroachdb/cockroach/pkg/ccl/changefeedccl.(*changefeedResumer).Resume(0xc002bd8490, 0x66a3110, 0xc0014b4090, 0x4cabf00, 0xc001986468, 0x48ef3a0, 0x8fda5e0)
        /go/src/github.com/cockroachdb/cockroach/pkg/ccl/changefeedccl/changefeed_stmt.go:614 +0x247
github.com/cockroachdb/cockroach/pkg/jobs.(*Registry).stepThroughStateMachine.func1(0xc0017c0d40, 0x66598e0, 0xc002bd8490, 0x66a3110, 0xc0014b4090, 0x4cabf00, 0xc001986468, 0xc0014359f0)
        /go/src/github.com/cockroachdb/cockroach/pkg/jobs/registry.go:1173 +0xae
github.com/cockroachdb/cockroach/pkg/jobs.(*Registry).stepThroughStateMachine(0xc00023d1e0, 0x66a3110, 0xc0014b4000, 0x4cabf00, 0xc001986468, 0x66598e0, 0xc002bd8490, 0xc003026000, 0x502c329, 0x7, ...)
        /go/src/github.com/cockroachdb/cockroach/pkg/jobs/registry.go:1174 +0x87c
github.com/cockroachdb/cockroach/pkg/jobs.(*Registry).runJob(0xc00023d1e0, 0x66a3068, 0xc004237280, 0x66598e0, 0xc002bd8490, 0xc003026000, 0x502c329, 0x7, 0xc003b1afc0, 0x16, ...)
        /go/src/github.com/cockroachdb/cockroach/pkg/jobs/adopt.go:322 +0x46c
github.com/cockroachdb/cockroach/pkg/jobs.(*StartableJob).Start.func2(0x66beb60, 0xc0028e9650)
        /go/src/github.com/cockroachdb/cockroach/pkg/jobs/jobs.go:874 +0xf6
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunAsyncTaskEx.func2(0xc000ccc800, 0x66beb60, 0xc0028e9650, 0xc0028e94a0, 0x0, 0xc00266d3b0)
        /go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:442 +0xf3
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunAsyncTaskEx
        /go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:434 +0x22b
```

</details>

<details>
<summary>Some Node 2 Goroutines</summary>

```
goroutine 17061 [chan receive, 6 minutes]:
github.com/cockroachdb/cockroach/pkg/ccl/changefeedccl/kvfeed.Run(0x66a3068, 0xc0036b92c0, 0xc000872000, 0xc00176f380, 0xc00174a348, 0xc00174a348, 0x0, 0xc000c68d70, 0x4fff280, 0xc000ac4000, ...)
        /go/src/github.com/cockroachdb/cockroach/pkg/ccl/changefeedccl/kvfeed/kv_feed.go:112 +0x7b6
github.com/cockroachdb/cockroach/pkg/ccl/changefeedccl.(*changeAggregator).startKVFeed.func1(0x66a3068, 0xc0036b92c0)
        /go/src/github.com/cockroachdb/cockroach/pkg/ccl/changefeedccl/changefeed_processors.go:288 +0xfe
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunAsyncTaskEx.func2(0xc00176e880, 0x66a3068, 0xc0036b92c0, 0xc000b66e00, 0x0, 0xc002cd8f60)
        /go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:442 +0xf3
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunAsyncTaskEx
        /go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:434 +0x22b


goroutine 16960 [select, 6 minutes]:
github.com/cockroachdb/cockroach/pkg/ccl/changefeedccl/kvevent.(*chanBuffer).Get(0xc000ed0750, 0x66a3068, 0xc0036b92c0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /go/src/github.com/cockroachdb/cockroach/pkg/ccl/changefeedccl/kvevent/chan_buffer.go:50 +0xe7
github.com/cockroachdb/cockroach/pkg/ccl/changefeedccl/kvevent.(*throttlingBuffer).Get(0xc002cd8f30, 0x66a3068, 0xc0036b92c0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /go/src/github.com/cockroachdb/cockroach/pkg/ccl/changefeedccl/kvevent/throttling_buffer.go:30 +0xa6
github.com/cockroachdb/cockroach/pkg/ccl/changefeedccl.(*bufEventProducer).GetEvent(0xc002cd6240, 0x66a3068, 0xc0036b92c0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /go/src/github.com/cockroachdb/cockroach/pkg/ccl/changefeedccl/changefeed_processors.go:585 +0xa6
github.com/cockroachdb/cockroach/pkg/ccl/changefeedccl.(*changeAggregator).tick(0xc0040b2300, 0x0, 0xc004c7def0)
        /go/src/github.com/cockroachdb/cockroach/pkg/ccl/changefeedccl/changefeed_processors.go:466 +0x85
github.com/cockroachdb/cockroach/pkg/ccl/changefeedccl.(*changeAggregator).Next(0xc0040b2300, 0xc002b9e0c0, 0x4, 0x4, 0x0)
        /go/src/github.com/cockroachdb/cockroach/pkg/ccl/changefeedccl/changefeed_processors.go:445 +0x85
github.com/cockroachdb/cockroach/pkg/sql/execinfra.Run(0x66a3068, 0xc0036b92c0, 0x66c3418, 0xc0040b2300, 0x665abc8, 0xc002fda380)
        /go/src/github.com/cockroachdb/cockroach/pkg/sql/execinfra/base.go:186 +0x35
github.com/cockroachdb/cockroach/pkg/sql/execinfra.(*ProcessorBaseNoHelper).Run(0xc0040b2300, 0x66a3068, 0xc0036b8ac0)
        /go/src/github.com/cockroachdb/cockroach/pkg/sql/execinfra/processorsbase.go:731 +0x90
github.com/cockroachdb/cockroach/pkg/sql/flowinfra.(*FlowBase).StartInternal.func1(0xc001419520, 0x1, 0x1, 0x66a3068, 0xc0036b8ac0, 0xc0031ca9a0, 0x0)
        /go/src/github.com/cockroachdb/cockroach/pkg/sql/flowinfra/flow.go:371 +0x5c
created by github.com/cockroachdb/cockroach/pkg/sql/flowinfra.(*FlowBase).StartInternal
        /go/src/github.com/cockroachdb/cockroach/pkg/sql/flowinfra/flow.go:370 +0x2e8


goroutine 17060 [select, 7 minutes]:
github.com/cockroachdb/cockroach/pkg/ccl/changefeedccl.(*kafkaSink).workerLoop(0xc003083140)
        /go/src/github.com/cockroachdb/cockroach/pkg/ccl/changefeedccl/sink_kafka.go:338 +0x155
created by github.com/cockroachdb/cockroach/pkg/ccl/changefeedccl.(*kafkaSink).start
        /go/src/github.com/cockroachdb/cockroach/pkg/ccl/changefeedccl/sink_kafka.go:164 +0x8b
```

</details>

It appears to me that:

- the `changeFrontier` has entered a draining state and is waiting for its inputs to drain:

```
goroutine 17682 [chan receive, 6 minutes]:
github.com/cockroachdb/cockroach/pkg/sql/execinfra.(*RowChannel).Next(0xc003ed01e0, 0xc003747490, 0x1, 0x1, 0x4e1a45)
        /go/src/github.com/cockroachdb/cockroach/pkg/sql/execinfra/base.go:508 +0x4a
github.com/cockroachdb/cockroach/pkg/sql/execinfra.(*ProcessorBaseNoHelper).DrainHelper(0xc0033aea80, 0xc002c2a5d8)
        /go/src/github.com/cockroachdb/cockroach/pkg/sql/execinfra/processorsbase.go:571 +0xac
github.com/cockroachdb/cockroach/pkg/ccl/changefeedccl.(*changeFrontier).Next(0xc0033aea80, 0x34d10769, 0xc000bd0000, 0xc0044c23c0, 0xc000ba9380)
```

https://github.com/cockroachdb/cockroach/blob/4c4135e7f4edc7142051ada818aeaad0e2bed710/pkg/sql/execinfra/processorsbase.go#L567-L571

- The kvFeed is waiting for a context to cancel before it finishes exiting:

```
goroutine 17061 [chan receive, 6 minutes]:
github.com/cockroachdb/cockroach/pkg/ccl/changefeedccl/kvfeed.Run(0x66a3068, 0xc0036b92c0, 0xc000872000, 0xc00176f380, 0xc00174a348, 0xc00174a348, 0x0, 0xc000c68d70, 0x4fff280, 0xc000ac4000, ...)
        /go/src/github.com/cockroachdb/cockroach/pkg/ccl/changefeedccl/kvfeed/kv_feed.go:112 +0x7b6
```

https://github.com/cockroachdb/cockroach/blob/e723a85739a2e1b514f5de3221a2177a3a37d0e6/pkg/ccl/changefeedccl/kvfeed/kv_feed.go#L106-L115

- The changeAggregator is waiting for an event from its channel buffer (which the kvFeed is the writer for so it is likely to be blocked until ca.Ctx is cancelled:

https://github.com/cockroachdb/cockroach/blob/4c4135e7f4edc7142051ada818aeaad0e2bed710/pkg/ccl/changefeedccl/changefeed_processors.go#L466-L469

**To Reproduce**

What did you do? Describe in your own words.

If possible, provide steps to reproduce the behavior:

1. Set up CockroachDB cluster with non-trivial latency between the nodes. For example, a node in us-east1, us-west1, and europe-west2.  In the following, all commands are run from the us-east1 node.

2. Setup a kafka sink (or any other sink where you can easily observe the changefeed output).

3. Setup table and changefeed

```sql
CREATE DATABASE test;
\c test
ALTER DATABASE test PRIMARY REGION "us-west1";
ALTER DATABASE test ADD region "us-east1";
ALTER DATABASE test ADD region "europe-west2";

CREATE TABLE tab1 (pk INT PRIMARY KEY, a INT UNIQUE NOT NULL, b INT);
INSERT INTO tab1 VALUES(1, 11, 3);
INSERT INTO tab1 VALUES(2, 22, 3);
INSERT INTO tab1 VALUES(3, 33, 4);
CREATE CHANGEFEED FOR TABLE tab1 INTO 'kafka://10.142.15.195:9092' WITH updated, resolved, confluent_schema_registry = 'http://10.142.15.195:8081', format = 'experimental_avro';
```

4. You should observe the 3 rows being send to the sink followed by resolved timestamps.
5. Do the schema change:

```
ALTER TABLE tab1 ALTER PRIMARY KEY USING COLUMNS(a);
```

6. If you trigger the issue, you will observe resolved timestamps right up to the timestamp of the schema change.  The changefeed job will still show as "running" in the jobs table.  But further writes will not be sent to the sink.

**Expected behavior**

The changefeedFrontier, changefeedAggregator, and kvFeed should completely exit and either restart or report as a failed job depending on the situation.

### PR DESCRIPTION
**Pull request by stevendanna**
During acceptance testing, we observed that changefeeds did not
correctly restart on primary key changes and did not correctly stop
when schema_change_policy was set to 'stop' when the changeFrontier
and changeAggregator were running on different nodes (most production
changefeeds).

The root cause of this was a bad assumption in the changeAggregator
shutdown logic. Namely, we assumed that the changeAggregator (and kv
feed) would see context cancellations as a result of the
changeFrontier moving to draining. However, this is not guaranteed.

When the changeFrontier moves to draining, all of its inputs will be
drained. But, a DrainRequest message is only sent to the input lazily
when the next message is received from that input.

In this case of a schema change, the kv feed would stop sending
messages to the changeAggregator and thus no further messages will be
sent to the changeFrontier and the drain request is not triggered.

With this change, we now shut down the changeAggregator when the
kvfeed indicates that no more messages will be returned.

Fixes #68791

Release note (enterprise change): Fixed a bug where CHANGEFEEDs would
fail to correctly handle a primary key change.

### CODE REVIEW

File: pkg/ccl/changefeedccl/kvfeed/kv_feed.go [hunk 1]
```diff
@@ -216,8 +216,13 @@ func (f *kvFeed) run(ctx context.Context) (err error) {
 				}
 			}
 		}
+
 		// Exit if the policy says we should.
 		if boundaryType == jobspb.ResolvedSpan_RESTART || boundaryType == jobspb.ResolvedSpan_EXIT {
+			// Close the sink so it knows no more writes are expected
+			if err := f.sink.Close(ctx); err != nil {
+				log.Warningf(ctx, "failed to close buffer: %s", err)
```
Comment (miretskiy) [inline pkg/ccl/changefeedccl/kvfeed/kv_feed.go:224]: s/bufffer/sink/?

File: pkg/ccl/changefeedccl/kvfeed/kv_feed.go [hunk 2]
```diff
@@ -216,8 +216,13 @@ func (f *kvFeed) run(ctx context.Context) (err error) {
...
+			}
 			return schemaChangeDetectedError{highWater.Next()}
```
Comment (miretskiy) [inline pkg/ccl/changefeedccl/kvfeed/kv_feed.go:226]: Should we retrun combine errors?

File: pkg/ccl/changefeedccl/kvfeed/kv_feed.go [hunk 3]
```diff
@@ -108,7 +108,7 @@ func Run(ctx context.Context, cfg Config) error {
 	// down the changefeed exposes synchronization challenges.
 	var scErr schemaChangeDetectedError
 	if errors.As(err, &scErr) {
-		log.Infof(ctx, "stopping changefeed due to schema change at %v", scErr.ts)
+		log.Infof(ctx, "stopping kv feed due to schema change at %v", scErr.ts)
```
Comment (miretskiy) [inline pkg/ccl/changefeedccl/kvfeed/kv_feed.go:111]: do you know why we're just not returning an error here?

File: pkg/ccl/changefeedccl/changefeed_test.go [hunk 4]
```diff
@@ -1478,6 +1478,112 @@ func TestChangefeedFailOnTableOffline(t *testing.T) {
...
+		`test_tab: [0]->{"after": {"a": 0}}`,
+		`test_tab: [1]->{"after": {"a": 1}}`,
+	})
+	sqlDB.Exec(t, `ALTER TABLE test_tab ADD COLUMN b INT NOT NULL DEFAULT 0`)
+
+	schemaChangeTimestampRegexp := regexp.MustCompile(`schema change occurred at ([0-9]+\.[0-9]+)`)
+	waitForSchemaChangeError := func(t *testing.T, f cdctest.TestFeed) {
+		t.Helper()
+		for {
+			if _, err := f.Next(); err != nil {
```
Comment (miretskiy) [inline pkg/ccl/changefeedccl/changefeed_test.go:1574]: would it be better to query jobs table to see if the job exited w/ this error?

File: pkg/ccl/changefeedccl/kvfeed/kv_feed.go (hunk 3 above)
Comment (stevendanna) [reply pkg/ccl/changefeedccl/kvfeed/kv_feed.go:111]: I do not.  I've read through the code and I believe that it would _currently_ be OK to return early from here because the unbuffered channel we use is already acting as a synchronisation point. I've removed the <-ctx.Done() and didn't see any test failures, but I want to run that under stress a bit more just in case I missed something in my read through.

File: pkg/ccl/changefeedccl/kvfeed/kv_feed.go (hunk 1 above)
Comment (stevendanna) [reply pkg/ccl/changefeedccl/kvfeed/kv_feed.go:224]: I think I went with buffer in the log message so it wouldn't be confused with the other user of the word `sink`.

**Review by miretskiy — CHANGES_REQUESTED** [review]
> Reviewed 2 of 5 files at r1, 2 of 4 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/69234)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @miretskiy and @stevendanna)

___
*[pkg/ccl/changefeedccl/kvfeed/kv_feed.go, line 111 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/69234#-Mhn1KfDy09WqHVhpY1R-r1-111:-Mi1MreM0xpOlDVig__V:bg1ogtt) ([raw file](https://github.com/cockroachdb/cockroach/blob/da92ad3f1a229898e9deae4a5d3fd3c27fe21d04/pkg/ccl/changefeedccl/kvfeed/kv_feed.go#L111)):*
<details><summary><i>Previously, stevendanna (Steven Danna) wrote…</i></summary><blockquote>

I've updated the comment here to explain why we aren't currently just returning.
</blockquote></details>

Ack.  Thanks.
So, why don't we need to close close the write? Why do we still wait for Done and return nil?  
___
*[pkg/ccl/changefeedccl/kvfeed/kv_feed.go, line 224 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/69234#-Mhn1KfDy09WqHVhpY1R-r1-224:-Mi1NKq-9GgPpkTqAqk1:bb6sh2i) ([raw file](https://github.com/cockroachdb/cockroach/blob/da92ad3f1a229898e9deae4a5d3fd3c27fe21d04/pkg/ccl/changefeedccl/kvfeed/kv_feed.go#L224)):*
<details><summary><i>Previously, stevendanna (Steven Danna) wrote…</i></summary><blockquote>

Actually, I ended up renaming `f.sink` to `f.writer`. Let me know what you think.  I'd like to remove the "sink" terminology from this part of the code eventually just so that `sink` always means what we usually mean when we say "sink" out loud.
</blockquote></details>

Ack.

**Review by stevendanna — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/69234)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @miretskiy and @stevendanna)

___
*[pkg/ccl/changefeedccl/kvfeed/kv_feed.go, line 111 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/69234#-Mhn1KfDy09WqHVhpY1R-r1-111:-Mi1U_pb-bVQ64RmfvxQ:b-s8kc4x) ([raw file](https://github.com/cockroachdb/cockroach/blob/da92ad3f1a229898e9deae4a5d3fd3c27fe21d04/pkg/ccl/changefeedccl/kvfeed/kv_feed.go#L111)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

Ack.  Thanks.
So, why don't we need to close close the write? Why do we still wait for Done and return nil?  
</blockquote></details>

We do close the writer here: https://github.com/cockroachdb/cockroach/pull/69234/files#diff-3adb512d3390cf29b3e69f8fa5d1196a733174e5b72a32f0c97436c9054e1dceR226

Perhaps it would be more clear to close it in this if statement though?

**Review by miretskiy — APPROVED** [review]
> Reviewed 1 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/69234)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @stevendanna)

___
*[pkg/ccl/changefeedccl/changefeed_test.go, line 1578 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/69234#-Mi1sqYN-IgNitMA-LXI:-Mi1sqYO5crcRLWBdtOJ:b-pq6mqe) ([raw file](https://github.com/cockroachdb/cockroach/blob/6ff9f4d5e9e52e8ee616cacd7c9055d571d55047/pkg/ccl/changefeedccl/changefeed_test.go#L1578)):*
> ```Go
> 			if _, err := f.Next(); err != nil {
> 				require.Regexp(t, schemaChangeTimestampRegexp, err)
> 				m := schemaChangeTimestampRegexp.FindStringSubmatch(err.Error())
> ```

Curious: why do we need to search for that substring? Can we get a schema change error that doesn't have a timestamp?
___
*[pkg/ccl/changefeedccl/kvfeed/kv_feed.go, line 111 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/69234#-Mhn1KfDy09WqHVhpY1R-r1-111:-Mi1sKA85ul82SI6Y8F6:b-utspj5) ([raw file](https://github.com/cockroachdb/cockroach/blob/da92ad3f1a229898e9deae4a5d3fd3c27fe21d04/pkg/ccl/changefeedccl/kvfeed/kv_feed.go#L111)):*
<details><summary><i>Previously, stevendanna (Steven Danna) wrote…</i></summary><blockquote>

We do close the writer here: https://github.com/cockroachdb/cockroach/pull/69234/files#diff-3adb512d3390cf29b3e69f8fa5d1196a733174e5b72a32f0c97436c9054e1dceR226

Perhaps it would be more clear to close it in this if statement though?
</blockquote></details>

I think it would be clearer to close it here.  We still want to wait for ctx.Done though, right?
I think closing here and adding a comment (e.g. closing writer causes callers to realize that we'r edone, and transition to draining, cancelling this context -- something like this).
