### PR TITLE
server: fix the advisory certificate check

### LINKED ISSUE #32539: cli/start: certificate error if no IP in cert (--listen translates hostname to addr and addr not in cert)
From @SpeedyCoder on https://github.com/cockroachdb/cockroach/issues/32501#issuecomment-440706118

> Do you guys have any idea why we are seeing the warning about the listen address not being in the node certificate? We are running the container with the following command

```
command:
- "/bin/bash"
- "-ecx"
- "exec /cockroach/cockroach start --logtostderr=WARNING --certs-dir /cockroach/cockroach-certs --advertise-addr $(hostname -f) --http-addr 0.0.0.0 --join cockroachdb-0.cockroachdb,cockroachdb-1.cockroachdb,cockroachdb-2.cockroachdb --cache 25% --max-sql-memory 25%"
```

> so the `--advertise-addr` is set. I've tried setting the `--listen-addr` to `0.0.0.0`, but that didn't have any effect. Setting it to `$(hostname -f)` resolved to an IP address and complained again. The cluster seems to be working fine otherwise, it's just not very comforting seeing that message and I don't really have any idea how to get rid of it... 😅

### PR DESCRIPTION
**Pull request by knz**
Fixes #32539.

(context: `cockroach start` performs some advisory checks on the
certificates prior to starting up, to inform the user upfront if the
cert configuration is suspicious. These checks are complementary to
the actual security validation performed in the go std lib.)

Prior to this patch, the advisory cert validation was performing
checks on both the addres given to `--listen` and that given to
`--advertise` (either explicitly, or implicitly when derived from
`--listen`).

This was problematic because the listen address is really irrelevant
to security validation. What matters for node cert validation is that
the advertised address is present. So this patch removes the check on
the listen addr (recommended by @mberhault).

Additionally this patch also enhances the check on the advertise addr:
if a host name is given to `--advertise-addr` (either explicitly, or
implicitly as derived from `--listen-addr`), and the name is not
present in the cert, the validation is considered to pass if the
resolved address for the given name is present int he cert.

Release note (cli change): The advisory/informative check performed by
`cockroach start` on the validity of addresses contained in the node
certificate is relaxed to focus on the advertised node address, and to
tolerate cases when the cert contains an IP address but a hostname is
specified as advertised address.

### CODE REVIEW

File: pkg/base/addr_validation.go [hunk 1]
```diff
@@ -274,23 +277,29 @@ func (cfg *Config) CheckCertificateAddrs(ctx context.Context) {
...
 		log.Infof(ctx, "server certificate addresses: %s", addrInfo)
 
-		// Verify the compatibility. This requires that ValidateAddr() has
+		// Verify the compatibility. This requires that ValidateAddrs() has
 		// been called already.
-		var buf strings.Builder
-		notifyFunc := func(msg, host string) {
-			if buf.Len() > 0 {
-				buf.WriteString(" and ")
+		host, _, _ := net.SplitHostPort(cfg.AdvertiseAddr)
```
Comment (mberhault) [inline pkg/base/addr_validation.go]: Is there a reason you're ignoring the returned error? Have there been valid addresses we failed on?

**Review by mberhault — APPROVED** [review]

File: pkg/base/addr_validation.go (hunk 1 above)
Comment (knz) [reply pkg/base/addr_validation.go]: I'm assuming here `ValidateAddrs()` has been called already. If the syntax was not correct that would have failed before. Do you think I should still check here with a `panic("call ValidateAddrs first")`?

Comment (mberhault) [reply pkg/base/addr_validation.go]: I'm fine leaving it out, mostly curious.

Comment (knz) [reply pkg/base/addr_validation.go]: ok added the panic

**Comment by knz** [comment]
TFYR

bors r+

**Review by bdarnell — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/39166)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @knz and @mberhault)

___
*[pkg/base/addr_validation.go, line 287 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/39166#-Ll2wLkG7D3isAco1h6N:-Ll2wLkH7DDPDA563FZX:bw3wuos) ([raw file](https://github.com/cockroachdb/cockroach/blob/0819797cea7779d5214703d77aefd12890f74921/pkg/base/addr_validation.go#L287)):*
> ```Go
> 		}
> 		if err := cert.VerifyHostname(host); err != nil {
> 			// The hostname itself is not in the cert. Is the numeric address in the cert?
> ```

Does it work to advertise a name but only have an IP address in the cert? I don't think it does. If it does work, that would be a security problem since DNS is insecure (it's not actually a security hole in this method since it's just advisory and the real check is in crypto/tls, but it's also not doing anything useful to manually resolve the IP address and compare it to the cert as far as I can tell.

**Comment by knz** [comment]
Ben do you have any idea where to look in the go stdlib to check what you say?

**Comment by bdarnell** [comment]
Grep for `ResolveIP` in crypto/tls? 

But it may be more straightforward to just write a test and see what happens: advertise `localhost` but only put `127.0.0.1` in the certificate. I believe that will pass this check but fail in actual usage.

**Comment by knz** [comment]
> Does it work to advertise a name but only have an IP address in the cert?

I looked into this further: yes it works. The situation(problem?) is that it's possible for a node A to advertise some hostname HA, but use A's numeric address when connecting from B (e.g. start B with `--join=<Aaddr>`)

In that case, B will check A's identity based on `Aaddr` not HA.

Because of that situation, I think it's OK to (advisorily) verify that A's numeric address is in the cert if the hostname isn't.

We *could* (but currently don't) validate inside the crdb protocol that the address given on B's `--join` matches the advertised address on A. If we did that, we would be in the simple situation you describe.

What do you think?

**Comment by bdarnell** [comment]
This is why it's sometimes useful to have un-advertised IPs/hostnames in the cert. But that doesn't make it OK to omit the advertised hostname from the cert. In some cases the advertised address will be used, and the connection will fail unless that address is in the cert. It's possible that the cluster will still work (if there are enough nodes using the correct join address that everything can become fully connected), but I think we should still disallow advertising addresses that are not present in the cert.
