### PR TITLE
workload/schemachange: fix constraintIsPrimary name escaping

### LINKED ISSUE #127273: workload/schemachange: constraintIsPrimary should consider colname fuzzing
```	
Received unexpected error:
***UNEXPECTED ERROR; Failed to generate a random operation: CollectOne: Query: "\n\tSELECT EXISTS(\n\t        SELECT *\n\t          FROM pg_catalog.pg_constraint\n\t         WHERE conrelid = 'public.table_w0_41'::REGCLASS::INT\n\t           AND conname = 'table_w0_41_col41_w0_44_co'l4%q1_w0_42_key'\n\t           AND (contype = 'p')\n\t       );\n\t" []: ERROR: at or near "l4": syntax error (SQLSTATE 42601)
(1) forced error mark
...
Wraps: (6) CollectOne: Query: "\n\tSELECT EXISTS(\n\t        SELECT *\n\t          FROM pg_catalog.pg_constraint\n\t         WHERE conrelid = 'public.table_w0_41'::REGCLASS::INT\n\t           AND conname = 'table_w0_41_col41_w0_44_co'l4%q1_w0_42_key'\n\t           AND (contype = 'p')\n\t       );\n\t" []
Wraps: (7) ERROR: at or near "l4": syntax error (SQLSTATE 42601)
```

Theory: the constraint name was automatically generated from the column name -- which is fuzzed. We should find a way to handle this, but lexbase.EscapeSQLIdent doesn't seem to work in this case. Here is the table if needed:
```
   "sql": "CREATE TABLE public.table_w0_41 (\"co'l4%q1_w0_42\" FLOAT8 NOT NULL, \"col4\t1_w0_43\" BOOL NULL, col41_w0_44 STRING NOT NULL AS (lower(CAST(\"col4\t1_w0_43\" AS STRING))) VIRTUAL, PRIMARY KEY (col41_w0_44), INDEX (\"co'l4%q1_w0_42\" ASC, col41_w0_44) STORING (\"col4\t1_w0_43\"), INDEX (abs(\"co'l4%q1_w0_42\") ASC) STORING (\"co'l4%q1_w0_42\"), UNIQUE (col41_w0_44), INDEX (\"co'l4%q1_w0_42\"), UNIQUE (\"col4\t1_w0_43\" ASC), UNIQUE (\"col4\t1_w0_43\" DESC) STORING (\"co'l4%q1_w0_42\"), UNIQUE (col41_w0_44 DESC, \"co'l4%q1_w0_42\" DESC), FAMILY (\"co'l4%q1_w0_42\", \"col4\t1_w0_43\"))"
```

Jira issue: CRDB-40350

Epic CRDB-19168

### PR DESCRIPTION
**Pull request by rafiss**
Using a placeholder argument for the SQL string makes it so any escaping
that is needed is automatically handled in the database when the
argument is parsed, rather than needing to do it in the workload code.

This also fixes the constraintIsDropping check to also check if the
constraint is being added. Dropping the constraint in either states
is not fully supported, as per:
https://github.com/cockroachdb/cockroach/blob/a3b0aa3902155b01470c4c512d23f201c8b18f7c/pkg/sql/catalog/tabledesc/structured.go#L1271-L1278

Finally, when creaing the DROP CONSTRAINT command itself, the constraint
name needs to be treated as an identifier so it gets double-quoted.

fixes https://github.com/cockroachdb/cockroach/issues/127273
Release note: None

### CODE REVIEW

**Review by annrpom — APPROVED** [review]
LGTM; I appreciate the explanation in the issue. We should be able to enable https://github.com/cockroachdb/cockroach/blob/f59eefe12beaf41e9697d4729e0ae4474927d434/pkg/workload/schemachange/optype.go#L276 now (can we rebase and stress this op to double-check?)

**Comment by rafiss** [comment]
Thanks for the pointer to re-enable that! A few additional fixes were needed, so PTAL.

I verified this works with:
```
diff --git a/pkg/workload/schemachange/optype.go b/pkg/workload/schemachange/optype.go
index 5ea81b0437b..145ccd43c16 100644
--- a/pkg/workload/schemachange/optype.go
+++ b/pkg/workload/schemachange/optype.go
@@ -267,13 +267,13 @@ var opWeights = []int{
 	alterFunctionRename:               1,
 	alterFunctionSetSchema:            1,
 	alterTableAddColumn:               1,
-	alterTableAddConstraintForeignKey: 1,
+	alterTableAddConstraintForeignKey: 20,
 	alterTableAddConstraintUnique:     0,
 	alterTableAlterColumnType:         0, // Disabled and tracked with #66662.
 	alterTableAlterPrimaryKey:         1,
 	alterTableDropColumn:              0, // Disabled and tracked with #127286.
 	alterTableDropColumnDefault:       1,
-	alterTableDropConstraint:          0, // Disabled and tracked with #127273.
+	alterTableDropConstraint:          30,
 	alterTableDropNotNull:             1,
 	alterTableDropStored:              1,
 	alterTableLocality:                1,

```

and then `./dev test pkg/ccl/testccl/workload/schemachange/ --stress --count=100 --ignore-cache -f=TestWorkload`

**Review by annrpom — CHANGES_REQUESTED** [review]
Nice!

One more thing; roughly similar to #128095

Our workload doesn't handle transient (?) constraint checks properly

So performing a schema change like `ALTER COLUMN SET NOT NULL` will add this constraint check [cockroach/pkg/sql/catalog/tabledesc/structured.go](https://github.com/cockroachdb/cockroach/blob/a3b0aa3902155b01470c4c512d23f201c8b18f7c/pkg/sql/catalog/tabledesc/structured.go#L1833) that gets removed once the not null column is public

but `randConstraint` will pick this as a constraint from time to time; so, we get stuff like:
```
"previousStatements": [
   "ALTER TABLE schema_w0_39.table_w0_92 DROP CONSTRAINT \"col_w0_92_w1_89_auto_not_null\""
  ]
```

In that case, we would anticipate a different error code:
```
ERROR: constraint "col_w0_92_w1_89_auto_not_null" of relation "table_w0_92" does not exist (SQLSTATE 42704)
```

So perhaps we could do another query in error_screening like `SELECT $1 ilike '%auto_not_null'` and have the result of that determine whether or not we tag an op with a expected error code of `pgcode.UndefinedObject`?

**Comment by annrpom** [comment]
Or I guess the constraint could actually still exist, but then your isAddingOrDropped check handles that

**Comment by rafiss** [comment]
Yeah, seems like this is already handled, since this auto_not_null constraint should only ever exist in the "Validating" or "Dropping" state based on all the usages of `MakeNotNullCheckConstraint`.

File: pkg/workload/schemachange/operation_generator.go [hunk 1]
```diff
@@ -1791,15 +1791,15 @@ func (og *operationGenerator) dropConstraint(ctx context.Context, tx pgx.Tx) (*o
 		stmt.expectedExecErrors.add(pgcode.FeatureNotSupported)
 	}
 
-	constraintBeingDropped, err := og.constraintInDroppingState(ctx, tx, tableName, constraintName)
+	constraintBeingDropped, err := og.constraintInAddOrDropState(ctx, tx, tableName, constraintName)
 	if err != nil {
 		return nil, err
 	}
 	if constraintBeingDropped {
 		stmt.expectedExecErrors.add(pgcode.FeatureNotSupported)
```
Comment (annrpom) [inline pkg/workload/schemachange/operation_generator.go:1799]: We should also expect a `pgcode.UndefinedObject` in the case where we are trying to drop a constraint that doesn't exist

> in the case where we are trying to drop a constraint that doesn't exist

Right now, the workload can try to do something like

```
"previousStatements": [
   "ALTER TABLE schema_w0_39.table_w0_92 DROP CONSTRAINT \"col_w0_92_w1_89_auto_not_null\""
  ]
ERROR: constraint "col_w0_92_w1_89_auto_not_null" of relation "table_w0_92"
does not exist (SQLSTATE 42704)
```

Since at the time of getting this rand constraint, `col_w0_92_w1_89_auto_not_null` existed

Comment (annrpom) [reply pkg/workload/schemachange/operation_generator.go:1799]: Sorry the highlight is funky -- I meant to draw emphasis on `stmt.expectedExecErrors.add`

File: pkg/workload/schemachange/operation_generator.go [hunk 2]
```diff
@@ -1791,15 +1791,15 @@ func (og *operationGenerator) dropConstraint(ctx context.Context, tx pgx.Tx) (*o
...
 	}
 
-	constraintBeingDropped, err := og.constraintInDroppingState(ctx, tx, tableName, constraintName)
+	constraintBeingDropped, err := og.constraintInAddOrDropState(ctx, tx, tableName, constraintName)
```
[the remark this answers is not in the document]
Comment (rafiss) [reply pkg/workload/schemachange/operation_generator.go]: done

File: pkg/workload/schemachange/operation_generator.go (hunk 1 above)
Comment (rafiss) [reply pkg/workload/schemachange/operation_generator.go:1799]: ah i see, in that case i'll add that code to the potentialExecErrors

**Review by annrpom — APPROVED** [review]
Nice -- LGTM!!

**Comment by rafiss** [comment]
tftr!

bors r+
