### PR TITLE
roachtest: minor refactor to backup fixture code

### LINKED ISSUE #113815: roachtest: backupFixture/tpce/15GB/aws failed
roachtest.backupFixture/tpce/15GB/aws [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestWeeklyAwsBazel/12498383?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestWeeklyAwsBazel/12498383?buildTab=artifacts#/backupFixture/tpce/15GB/aws) on master @ [4d045594e8c65b56c82fcf2a1f14ee30cecfef3d](https://github.com/cockroachdb/cockroach/commits/4d045594e8c65b56c82fcf2a1f14ee30cecfef3d):

```
(restore.go:877).validateRestoreSpecs: invalid restoreSpecs; unspecified restoreUptoIncremental field
test artifacts and logs in: /artifacts/backupFixture/tpce/15GB/aws/run_1
```
<p>Parameters: <code>ROACHTEST_arch=amd64</code>
, <code>ROACHTEST_cloud=aws</code>
, <code>ROACHTEST_cpu=4</code>
, <code>ROACHTEST_encrypted=true</code>
, <code>ROACHTEST_fs=ext4</code>
, <code>ROACHTEST_localSSD=false</code>
, <code>ROACHTEST_metamorphicBuild=false</code>
, <code>ROACHTEST_ssd=0</code>
</p>
<details><summary>Help</summary>
<p>

See: [roachtest README](https://github.com/cockroachdb/cockroach/blob/master/pkg/cmd/roachtest/README.md)

See: [How To Investigate \(internal\)](https://cockroachlabs.atlassian.net/l/c/SSSBr8c7)

_Grafana is not yet available for aws clusters_</p>
</details>
/cc @cockroachdb/disaster-recovery
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*backupFixture/tpce/15GB/aws.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)
</sub>

Jira issue: CRDB-33174

### PR DESCRIPTION
**Pull request by adityamaru**
While generating backup fixtures we ended up refactoring some code. This change also fixes the weekly failure seen in #113815. We have not completed regenerating fixtures but this refactor seems worth checking in in the meantime.

Fixes: #113815
Release note: None

### CODE REVIEW

File: pkg/cmd/roachtest/tests/backup_fixtures.go [hunk 1]
```diff
@@ -228,70 +230,83 @@ func (bd *backupDriver) monitorBackups(ctx context.Context) {
...
+			// - restore/tpce/400GB/aws/inc-count=48/nodes=4/cpus=8
+			// - restore/tpce/400GB/aws/nodes=4/cpus=16
+			// - restore/tpce/400GB/aws/nodes=4/cpus=8
+			// - restore/tpce/400GB/aws/nodes=8/cpus=8
+			hardware:             makeHardwareSpecs(hardwareSpecs{workloadNode: true}),
+			scheduledBackupSpecs: makeBackupFixtureSpecs(scheduledBackupSpecs{}),
+			timeout:              5 * time.Hour,
+			initWorkloadViaRestore: restoreSpecs{
+				backup:                 backupSpecs{version: "v22.2.0", numBackupsInChain: 48},
+				restoreUptoIncremental: 48,
```
Comment (msbutler) [inline pkg/cmd/roachtest/tests/backup_fixtures.go:243]: why do we need to specify `restoreUpToIncremental` during fixture generation?

**Review by msbutler — APPROVED** [review]
Thanks for doing this! I left a few small clarification questions

File: pkg/cmd/roachtest/tests/backup_fixtures.go (hunk 1 above)
Comment (msbutler) [reply pkg/cmd/roachtest/tests/backup_fixtures.go:243]: hrm, I think `numBackupsInChain` identifies the bucket:
https://github.com/cockroachdb/cockroach/blob/691b544bbe40675b620e62a3505b8c7a32a5c825/pkg/cmd/roachtest/tests/restore.go#L688

Comment (msbutler) [reply pkg/cmd/roachtest/tests/backup_fixtures.go:243]: we can try deleting this `restoreUpToIncremental`  set in a follow up

Comment (adityamaru) [reply pkg/cmd/roachtest/tests/backup_fixtures.go:243]: oh the String() method of `restoreUpToIncremental`, but I think this is used to pick out the AOST I believe - https://github.com/cockroachdb/cockroach/blob/cca37917931978b791d241e877ba3f55f6cdaea3/pkg/cmd/roachtest/tests/restore.go#L701? I imagine we want all 48 incs to actually have the size of data that we claim?

Comment (msbutler) [reply pkg/cmd/roachtest/tests/backup_fixtures.go:243]: ahhhh, I see. Ok no problems in your patch. Thanks for doing this!
