### PR TITLE
kvserver: fix double span Finish on reproposals

### LINKED ISSUE #107521: kvserver: span assertions fire in replication layer
**Describe the problem**

See the detailed analysis [here](https://github.com/cockroachdb/cockroach/issues/107242#issuecomment-1647975424).

We need to make structural improvements to the span lifecycle (document, simplify, introduce invariant checks, testing, etc) that avoid this class of bugs.

See also https://github.com/cockroachdb/cockroach/issues/86547 and all the other work in CRDB-25287 (which is related and made important simplifications, but didn't focus on the span lifecycles in particular).

**To Reproduce**

Unclear

### LINKED ISSUE #108241: kv/kvnemesis: TestKVNemesisMultiNode failed
kv/kvnemesis.TestKVNemesisMultiNode [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_StressBazel/11202372?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_StressBazel/11202372?buildTab=artifacts#/) on master @ [695d4ec85157a4da0c97237e6f16bf919eebf6c5](https://github.com/cockroachdb/cockroach/commits/695d4ec85157a4da0c97237e6f16bf919eebf6c5):

Fatal error:

```
panic: use of Span after Finish. Span: /cockroach.roachpb.Internal/Batch. Finish previously called at: <stack not captured. Set debugUseAfterFinish> [recovered]
	panic: use of Span after Finish. Span: /cockroach.roachpb.Internal/Batch. Finish previously called at: <stack not captured. Set debugUseAfterFinish>

```
Stack: 

```
goroutine 6569871 [running]:
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).recover(0x1f81c6a?, {0x6976bc8, 0xc014ecf170})
	github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:230 +0x6a
panic({0x4b2d840, 0xc01b174160})
	GOROOT/src/runtime/panic.go:884 +0x212
github.com/cockroachdb/cockroach/pkg/util/tracing.(*Span).detectUseAfterFinish(0x6976bc8?)
	github.com/cockroachdb/cockroach/pkg/util/tracing/span.go:182 +0x12e
github.com/cockroachdb/cockroach/pkg/util/tracing.(*Span).Tracer(...)
	github.com/cockroachdb/cockroach/pkg/util/tracing/span.go:225
github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*replicaDecoder).createTracingSpans(0xc00a3270d8, {0x6976bc8, 0xc0204de0f0})
	github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/replica_application_decoder.go:154 +0x4f0
github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*replicaDecoder).DecodeAndBind(0xc00a326c80?, {0x6976bc8, 0xc0204de0f0}, {0xc02851e210?, 0x3?, 0x10?})
	github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/replica_application_decoder.go:63 +0x66
github.com/cockroachdb/cockroach/pkg/kv/kvserver/apply.(*Task).Decode(...)
	github.com/cockroachdb/cockroach/pkg/kv/kvserver/apply/task.go:142
github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*Replica).handleRaftReadyRaftMuLocked(_, {_, _}, {{0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...}, ...})
	github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/replica_raft.go:878 +0x73a
github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*Replica).handleRaftReady(_, {_, _}, {{0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...}, ...})
	github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/replica_raft.go:728 +0x1b0
github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*Store).processReady(0xc0165eea80, 0x2?)
	github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/store_raft.go:689 +0x14b
github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*raftSchedulerShard).worker(0xc0085cbd50, {0x6976bc8, 0xc014ecf170}, {0x695c980, 0xc0165eea80}, 0xc0165ee000)
	github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/scheduler.go:416 +0x274
github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*raftScheduler).Start.func2({0x6976bc8?, 0xc014ecf170?})
	github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/scheduler.go:321 +0x45
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunAsyncTaskEx.func2()
	github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:484 +0x146
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunAsyncTaskEx
	github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:475 +0x43b
```
<details><summary>Log preceding fatal error</summary>
<p>

```
=== RUN   TestKVNemesisMultiNode
    test_log_scope.go:167: test logs captured to: /artifacts/tmp/_tmp/1f42cf5be2fc021646bf9b2daf5eaef3/logTestKVNemesisMultiNode1784560352
    test_log_scope.go:81: use -show-logs to present logs inline
    kvnemesis_test.go:283: seed: 2381536854787156731
    test_server_shim.go:98: 
        Test server was configured to route SQL queries to a secondary tenant (virtual cluster).
        If you are only seeing a test failure when this message appears, there may be a problem
        specific to cluster virtualization or multi-tenancy.
        
        To investigate, consider using "COCKROACH_TEST_TENANT=true" to force-enable just
        the secondary tenant in all runs (or, alternatively, "false" to force-disable), or use
        "COCKROACH_INTERNAL_DISABLE_METAMORPHIC_TESTING=false" to disable all random test variables altogether.
*
* WARNING: test tenant requested by configuration, but code organization prevents start!
* OSS binaries do not include enterprise features
*
*
* WARNING: test tenant requested by configuration, but code organization prevents start!
* OSS binaries do not include enterprise features
*
*
* WARNING: test tenant requested by configuration, but code organization prevents start!
* OSS binaries do not include enterprise features
*
*
* WARNING: test tenant requested by configuration, but code organization prevents start!
* OSS binaries do not include enterprise features
*
    kvnemesis_test.go:197: kvnemesis logging to /artifacts/tmp/_tmp/1f42cf5be2fc021646bf9b2daf5eaef3/kvnemesis1734753383
```
</p>
</details>
<p>Parameters: <code>TAGS=bazel,gss,deadlock</code>
, <code>stress=true</code>
</p>
<details><summary>Help</summary>
<p>

See also: [How To Investigate a Go Test Failure \(internal\)](https://cockroachlabs.atlassian.net/l/c/HgfXfJgM)
</p>
</details>
/cc @cockroachdb/kv
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*TestKVNemesisMultiNode.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)
</sub>

Jira issue: CRDB-30377

### LINKED ISSUE #108534: kvserver: use of span after finish
On d9d421e342710ca8e2d35941f0765a68257f61c2 when running `./dev test pkg/sql -f=TestRelocateNonVoters --stress --race --cpus=4 -- --test_env=COCKROACH_TEST_TENANT=true` on the gceworker I got the following panic:
```
* ERROR: a panic has occurred!
* use of Span after Finish. Span: /cockroach.roachpb.Internal/Batch. Finish previously called at: <stack not captured. Set debugUseAfterFinish>
* (1) attached stack trace
*   -- stack trace:
*   | runtime.gopanic
*   | › GOROOT/src/runtime/panic.go:890
*   | [...repeated from below...]
* Wraps: (2) assertion failure
* Wraps: (3) attached stack trace
*   -- stack trace:
*   | github.com/cockroachdb/cockroach/pkg/util/tracing.(*Span).detectUseAfterFinish
*   | › github.com/cockroachdb/cockroach/pkg/util/tracing/span.go:182
*   | github.com/cockroachdb/cockroach/pkg/util/tracing.(*Span).RecordingType
*   | › github.com/cockroachdb/cockroach/pkg/util/tracing/span.go:442
*   | github.com/cockroachdb/cockroach/pkg/util/tracing.(*Span).IsVerbose
*   | › github.com/cockroachdb/cockroach/pkg/util/tracing/span.go:450
*   | github.com/cockroachdb/cockroach/pkg/util/log.getSpanOrEventLog
*   | › github.com/cockroachdb/cockroach/pkg/util/log/trace.go:92
*   | github.com/cockroachdb/cockroach/pkg/util/log.vEventf
*   | › github.com/cockroachdb/cockroach/pkg/util/log/trace.go:212
*   | github.com/cockroachdb/cockroach/pkg/util/log.VEvent
*   | › github.com/cockroachdb/cockroach/pkg/util/log/trace.go:231
*   | github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*propBuf).FlushLockedWithRaftGroup
*   | › github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/replica_proposal_buf.go:601
*   | github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*Replica).handleRaftReadyRaftMuLocked.func2
*   | › github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/replica_raft.go:775
*   | github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*Replica).withRaftGroupLocked
*   | › github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/replica_raft.go:1998
*   | github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*Replica).handleRaftReadyRaftMuLocked
*   | › github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/replica_raft.go:772
*   | github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*Replica).handleRaftReady
*   | › github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/replica_raft.go:728
*   | github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*Store).processReady
*   | › github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/store_raft.go:689
*   | github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*raftSchedulerShard).worker
*   | › github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/scheduler.go:416
*   | github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*raftScheduler).Start.func2
*   | › github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/scheduler.go:321
*   | github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunAsyncTaskEx.func2
*   | › github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:484
*   | runtime.goexit
*   | › src/runtime/asm_amd64.s:1594
* Wraps: (4) use of Span after Finish. Span: /cockroach.roachpb.Internal/Batch. Finish previously called at: <stack not captured. Set debugUseAfterFinish>
```

This logging seems to be added recently in 60b26ae351da815c7274fa2fd29df7881f769cb6.

Stack trace is [here](https://github.com/cockroachdb/cockroach/files/12315646/stress.zip)

Jira issue: CRDB-30511

### LINKED ISSUE #108663: roachtest: failover/chaos/read-write failed
roachtest.failover/chaos/read-write [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/11290566?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/11290566?buildTab=artifacts#/failover/chaos/read-write) on master @ [7da4ef5af83c38680c536e7c18a9db61274b9d25](https://github.com/cockroachdb/cockroach/commits/7da4ef5af83c38680c536e7c18a9db61274b9d25):

```
(failover.go:1790).sleepFor: sleep failed: context canceled
(monitor.go:140).Wait: monitor failure: unexpected node event: n5: cockroach process died (exit code 134)
(cluster.go:2279).Run: cluster.RunE: context canceled
(cluster.go:2279).Run: cluster.RunE: context canceled
(cluster.go:2279).Run: cluster.RunE: context canceled
(cluster.go:2279).Run: cluster.RunE: context canceled
test artifacts and logs in: /artifacts/failover/chaos/read-write/run_1
```
<p>Parameters: <code>ROACHTEST_arch=amd64</code>
, <code>ROACHTEST_cloud=gce</code>
, <code>ROACHTEST_cpu=2</code>
, <code>ROACHTEST_encrypted=false</code>
, <code>ROACHTEST_fs=ext4</code>
, <code>ROACHTEST_localSSD=false</code>
, <code>ROACHTEST_ssd=0</code>
</p>
<details><summary>Help</summary>
<p>

See: [roachtest README](https://github.com/cockroachdb/cockroach/blob/master/pkg/cmd/roachtest/README.md)

See: [How To Investigate \(internal\)](https://cockroachlabs.atlassian.net/l/c/SSSBr8c7)

See: [Grafana](https://go.crdb.dev/p/roachfana/teamcity-11290566-1691819282-69-n10cpu2/1691850662762/1691851254521)

</p>
</details>
/cc @cockroachdb/kv-triage
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*failover/chaos/read-write.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)
</sub>

Jira issue: CRDB-30575

### LINKED ISSUE #108696: tracing: data race in isNoop
**Describe the problem**

```
WARNING: DATA RACE
Read at 0x00c039d8fc10 by goroutine 4729:
  github.com/cockroachdb/cockroach/pkg/util/tracing.(*spanInner).isNoop()
      github.com/cockroachdb/cockroach/pkg/util/tracing/span_inner.go:60 +0x64
  github.com/cockroachdb/cockroach/pkg/util/tracing.(*Span).IsNoop()
      github.com/cockroachdb/cockroach/pkg/util/tracing/span.go:155 +0xb5
  github.com/cockroachdb/cockroach/pkg/util/tracing.(*Span).detectUseAfterFinish()
      github.com/cockroachdb/cockroach/pkg/util/tracing/span.go:171 +0xb7
  github.com/cockroachdb/cockroach/pkg/util/tracing.(*Span).RecordingType()
      github.com/cockroachdb/cockroach/pkg/util/tracing/span.go:444 +0x2e
  github.com/cockroachdb/cockroach/pkg/util/tracing.(*Span).IsVerbose()
      github.com/cockroachdb/cockroach/pkg/util/tracing/span.go:452 +0x4e
  github.com/cockroachdb/cockroach/pkg/util/log.getSpanOrEventLog()
      github.com/cockroachdb/cockroach/pkg/util/log/trace.go:92 +0x52
  github.com/cockroachdb/cockroach/pkg/util/log.logfDepthInternal()
      github.com/cockroachdb/cockroach/pkg/util/log/channels.go:101 +0x60a
  github.com/cockroachdb/cockroach/pkg/util/log.logfDepth()
      github.com/cockroachdb/cockroach/pkg/util/log/channels.go:39 +0x124
  github.com/cockroachdb/cockroach/pkg/util/log.vEventf()
      github.com/cockroachdb/cockroach/pkg/util/log/trace.go:210 +0xce
  github.com/cockroachdb/cockroach/pkg/util/log.VEvent()
      github.com/cockroachdb/cockroach/pkg/util/log/trace.go:231 +0x17cf
  github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*propBuf).FlushLockedWithRaftGroup()
      github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/replica_proposal_buf.go:601 +0x1785
  github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*Replica).handleRaftReadyRaftMuLocked.func2()
      github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/replica_raft.go:782 +0xfc
  github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*Replica).withRaftGroupLocked()
      github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/replica_raft.go:2005 +0xad
  github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*Replica).handleRaftReadyRaftMuLocked()
      github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/replica_raft.go:779 +0x39a
  github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*Replica).handleRaftReady()
      github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/replica_raft.go:735 +0x21b
  github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*Store).processReady()
      github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/store_raft.go:689 +0x1ef
  github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*raftSchedulerShard).worker()
      github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/scheduler.go:418 +0x2f5
  github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*raftScheduler).Start.func2()
      github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/scheduler.go:321 +0x9a
  github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunAsyncTaskEx.func2()
      github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:484 +0x1f6

Previous write at 0x00c039d8fc10 by goroutine 19833:
  github.com/cockroachdb/cockroach/pkg/util/tracing.(*Span).reset()
      github.com/cockroachdb/cockroach/pkg/util/tracing/span.go:686 +0x1da
  github.com/cockroachdb/cockroach/pkg/util/tracing.(*Tracer).newSpan()
      github.com/cockroachdb/cockroach/pkg/util/tracing/tracer.go:1003 +0x1ba
  github.com/cockroachdb/cockroach/pkg/util/tracing.(*Tracer).startSpanGeneric()
      github.com/cockroachdb/cockroach/pkg/util/tracing/tracer.go:1208 +0xba5
  github.com/cockroachdb/cockroach/pkg/util/tracing.(*Tracer).StartSpanCtx()
      github.com/cockroachdb/cockroach/pkg/util/tracing/tracer.go:1084 +0x104
  github.com/cockroachdb/cockroach/pkg/util/tracing.(*Tracer).StartSpan()
      github.com/cockroachdb/cockroach/pkg/util/tracing/tracer.go:968 +0x378
  github.com/cockroachdb/cockroach/pkg/util/tracing/grpcinterceptor.ClientInterceptor.func2()
      github.com/cockroachdb/cockroach/pkg/util/tracing/grpcinterceptor/grpc_interceptor.go:235 +0x2e5
  google.golang.org/grpc.(*ClientConn).Invoke()
      google.golang.org/grpc/external/org_golang_google_grpc/call.go:35 +0x26d
  github.com/cockroachdb/cockroach/pkg/rpc.(*heartbeatClient).Ping()
      github.com/cockroachdb/cockroach/pkg/rpc/bazel-out/k8-fastbuild/bin/pkg/rpc/rpc_go_proto_/github.com/cockroachdb/cockroach/pkg/rpc/heartbeat.pb.go:408 +0xf4
  github.com/cockroachdb/cockroach/pkg/rpc.runSingleHeartbeat.func2()
      github.com/cockroachdb/cockroach/pkg/rpc/pkg/rpc/peer.go:396 +0xca
  github.com/cockroachdb/cockroach/pkg/util/timeutil.RunWithTimeout()
      github.com/cockroachdb/cockroach/pkg/util/timeutil/timeout.go:29 +0x12d
  github.com/cockroachdb/cockroach/pkg/rpc.runSingleHeartbeat()
      github.com/cockroachdb/cockroach/pkg/rpc/pkg/rpc/peer.go:401 +0x732
  github.com/cockroachdb/cockroach/pkg/rpc.(*peer).runHeartbeatUntilFailure()
      github.com/cockroachdb/cockroach/pkg/rpc/pkg/rpc/peer.go:482 +0x5bb
  github.com/cockroachdb/cockroach/pkg/rpc.(*peer).runOnce()
      github.com/cockroachdb/cockroach/pkg/rpc/pkg/rpc/peer.go:344 +0x589
  github.com/cockroachdb/cockroach/pkg/rpc.(*peer).run()
      github.com/cockroachdb/cockroach/pkg/rpc/pkg/rpc/peer.go:281 +0x3da
  github.com/cockroachdb/cockroach/pkg/rpc.(*peer).launch.func1()
      github.com/cockroachdb/cockroach/pkg/rpc/pkg/rpc/peer.go:241 +0x64
  github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunAsyncTaskEx.func2()
      github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:484 +0x1f6

Goroutine 4729 (running) created at:
  github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunAsyncTaskEx()
      github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:475 +0x619
  github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*raftScheduler).Start()
      github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/scheduler.go:313 +0x406
  github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*Store).processRaft()
      github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/store_raft.go:757 +0xc4
  github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*Store).Start()
      github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/store.go:2107 +0x1364
  github.com/cockroachdb/cockroach/pkg/server.(*Node).start()
      github.com/cockroachdb/cockroach/pkg/server/node.go:658 +0x1699
  github.com/cockroachdb/cockroach/pkg/server.(*topLevelServer).PreStart()
      github.com/cockroachdb/cockroach/pkg/server/server.go:1822 +0x34ba
  github.com/cockroachdb/cockroach/pkg/server.(*testServer).Start()
      github.com/cockroachdb/cockroach/pkg/server/testserver.go:677 +0xfb
  github.com/cockroachdb/cockroach/pkg/testutils/testcluster.(*TestCluster).startServer()
      github.com/cockroachdb/cockroach/pkg/testutils/testcluster/testcluster.go:632 +0xf2
  github.com/cockroachdb/cockroach/pkg/testutils/testcluster.(*TestCluster).Start()
      github.com/cockroachdb/cockroach/pkg/testutils/testcluster/testcluster.go:407 +0x550
  github.com/cockroachdb/cockroach/pkg/testutils/serverutils.StartNewTestCluster()
      github.com/cockroachdb/cockroach/pkg/testutils/serverutils/test_cluster_shim.go:286 +0x144
  github.com/cockroachdb/cockroach/pkg/testutils/testcluster.NewTestCluster()
      github.com/cockroachdb/cockroach/pkg/testutils/testcluster/testcluster.go:364 +0x15b0
  github.com/cockroachdb/cockroach/pkg/testutils/testcluster.NewTestCluster()
      github.com/cockroachdb/cockroach/pkg/testutils/testcluster/testcluster.go:364 +0x15b0
  github.com/cockroachdb/cockroach/pkg/testutils/testcluster.testClusterFactoryImpl.NewTestCluster()
      github.com/cockroachdb/cockroach/pkg/testutils/testcluster/testcluster.go:1949 +0x8b
  github.com/cockroachdb/cockroach/pkg/testutils/testcluster.(*testClusterFactoryImpl).NewTestCluster()
      <autogenerated>:1 +0xaf
  github.com/cockroachdb/cockroach/pkg/testutils/serverutils.NewTestCluster()
      github.com/cockroachdb/cockroach/pkg/testutils/serverutils/test_cluster_shim.go:300 +0x118
  github.com/cockroachdb/cockroach/pkg/testutils/serverutils.StartNewTestCluster()
      github.com/cockroachdb/cockroach/pkg/testutils/serverutils/test_cluster_shim.go:285 +0x56
  github.com/cockroachdb/cockroach/pkg/sql_test.testCase.runTest()
      github.com/cockroachdb/cockroach/pkg/sql_test/pkg/sql/multitenant_admin_function_test.go:250 +0x1f9
  github.com/cockroachdb/cockroach/pkg/sql_test.TestRelocateNonVoters.func1()
      github.com/cockroachdb/cockroach/pkg/sql_test/pkg/sql/multitenant_admin_function_test.go:886 +0x1e4
  testing.tRunner()
      GOROOT/src/testing/testing.go:1446 +0x216
  testing.(*T).Run.func1()
      GOROOT/src/testing/testing.go:1493 +0x47

Goroutine 19833 (running) created at:
  github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunAsyncTaskEx()
      github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:475 +0x619
  github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunAsyncTask()
      github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:346 +0x386
  github.com/cockroachdb/cockroach/pkg/rpc.(*peer).launch()
      github.com/cockroachdb/cockroach/pkg/rpc/pkg/rpc/peer.go:240 +0x46
  github.com/cockroachdb/cockroach/pkg/rpc.(*Context).newPeer.func2.1()
      github.com/cockroachdb/cockroach/pkg/rpc/pkg/rpc/peer.go:197 +0x64
  runtime/pprof.Do()
      GOROOT/src/runtime/pprof/runtime.go:40 +0x122
  github.com/cockroachdb/cockroach/pkg/rpc.(*Context).newPeer.func2()
      github.com/cockroachdb/cockroach/pkg/rpc/pkg/rpc/peer.go:196 +0x3bd
  github.com/cockroachdb/cockroach/pkg/util/circuit.(*Breaker).maybeTriggerProbe()
      github.com/cockroachdb/cockroach/pkg/util/circuit/circuitbreaker.go:257 +0x321
  github.com/cockroachdb/cockroach/pkg/util/circuit.(*Breaker).Probe()
      github.com/cockroachdb/cockroach/pkg/util/circuit/circuitbreaker.go:96 +0x545
  github.com/cockroachdb/cockroach/pkg/rpc.(*Context).grpcDialNodeInternal()
      github.com/cockroachdb/cockroach/pkg/rpc/pkg/rpc/context.go:2163 +0x51c
  github.com/cockroachdb/cockroach/pkg/rpc.(*Context).GRPCDialNode()
      github.com/cockroachdb/cockroach/pkg/rpc/pkg/rpc/context.go:2114 +0x1f3
  github.com/cockroachdb/cockroach/pkg/rpc/nodedialer.(*Dialer).dial()
      github.com/cockroachdb/cockroach/pkg/rpc/nodedialer/nodedialer.go:170 +0xed
  github.com/cockroachdb/cockroach/pkg/rpc/nodedialer.(*Dialer).Dial()
      github.com/cockroachdb/cockroach/pkg/rpc/nodedialer/nodedialer.go:103 +0x1dd
  github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*RaftTransport).startProcessNewQueue.func2()
      github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/raft_transport.go:979 +0x294
  runtime/pprof.Do()
      GOROOT/src/runtime/pprof/runtime.go:40 +0x122
  github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*RaftTransport).startProcessNewQueue.func3()
      github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/raft_transport.go:1001 +0x28c
  github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunAsyncTaskEx.func2()
      github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:484 +0x1f6
```

**To Reproduce**

Caught while stressing `TestRelocateNonVoters` in `pkg/sql:sql_test`, but the failure doesn't seem specific to this test.

**Environment:**
 - CRDB `master` @ 7da4ef5a
 - gceworker

Jira issue: CRDB-30598

### LINKED ISSUE #108837: roachtest: c2c/tpcc/warehouses=1000/duration=60/cutover=30 failed - span reuse after finish
roachtest.c2c/tpcc/warehouses=1000/duration=60/cutover=30 [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/11339541?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/11339541?buildTab=artifacts#/c2c/tpcc/warehouses=1000/duration=60/cutover=30) on master @ [e0de1f12d4f496fc7e4050a33e96f8c635c7a27c](https://github.com/cockroachdb/cockroach/commits/e0de1f12d4f496fc7e4050a33e96f8c635c7a27c):

```
(assertions.go:333).Fail: 
	Error Trace:	github.com/cockroachdb/cockroach/pkg/cmd/roachtest/tests/cluster_to_cluster.go:917
	            				main/pkg/cmd/roachtest/monitor.go:119
	            				golang.org/x/sync/errgroup/external/org_golang_x_sync/errgroup/errgroup.go:75
	            				GOROOT/src/runtime/asm_amd64.s:1594
	Error:      	Received unexpected error:
	            	read tcp 172.17.0.3:37308->34.138.79.86:26257: read: connection reset by peer
	Test:       	c2c/tpcc/warehouses=1000/duration=60/cutover=30
(require.go:1360).NoError: FailNow called
(test_runner.go:1146).func1: 1 dead node(s) detected
test artifacts and logs in: /artifacts/c2c/tpcc/warehouses=1000/duration=60/cutover=30/run_1
```
<p>Parameters: <code>ROACHTEST_arch=amd64</code>
, <code>ROACHTEST_cloud=gce</code>
, <code>ROACHTEST_cpu=8</code>
, <code>ROACHTEST_encrypted=false</code>
, <code>ROACHTEST_fs=ext4</code>
, <code>ROACHTEST_localSSD=false</code>
, <code>ROACHTEST_ssd=0</code>
</p>
<details><summary>Help</summary>
<p>

See: [roachtest README](https://github.com/cockroachdb/cockroach/blob/master/pkg/cmd/roachtest/README.md)

See: [How To Investigate \(internal\)](https://cockroachlabs.atlassian.net/l/c/SSSBr8c7)

See: [Grafana](https://go.crdb.dev/p/roachfana/teamcity-11339541-1692164772-36-n9cpu8/1692179597109/1692181453643)

</p>
</details>
<details><summary>Same failure on other branches</summary>
<p>

- #108699 roachtest: c2c/tpcc/warehouses=1000/duration=60/cutover=30 failed [C-test-failure O-roachtest O-robot T-disaster-recovery branch-release-23.1]
</p>
</details>
/cc @cockroachdb/disaster-recovery
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*c2c/tpcc/warehouses=1000/duration=60/cutover=30.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)
</sub>

Jira issue: CRDB-30659

### PR DESCRIPTION
**Pull request by pav-kv**
Since #106750, `ProposalData` is being copied on superseding reproposals. The caller only knows about the original proposal, and only detaches its context / tracing span when abandoning the request (e.g. on timeout). By the time of abandoning the request, there might have been a few superseding reproposals, and the context / tracing span is being used by multiple `ProposalData` objects.

In addition to rewriting the original `proposal.ctx`, we should do the same for all the `ProposalData` objects corresponding to the same request. This commit unbinds the context for older proposals when reproposing them, and unbinds the latest reproposal context when cleaning up / abandoning the request.

Fixes #107521
Fixes #108534
Fixes #108241
Fixes #108663
Fixes #108696
Fixes #108837

Epic: CRDB-25287
Release note: none

### CODE REVIEW

File: pkg/kv/kvserver/replica_application_result.go [hunk 1]
```diff
@@ -366,17 +343,30 @@ func (r *Replica) tryReproposeWithNewLeaseIndex(ctx context.Context, origCmd *re
...
+		// proposal and the span would be finished momentarily (when we return to
+		// the caller) if we didn't unlink it here, but we want it to continue
+		// tracking newProposal. We leave it in `origP.ctx` though, since that
+		// context will become unused once the application of this (soft-failed)
+		// proposal concludes, i.e. soon after this method returns, in case there is
+		// anything left to log into it.
+		origP.sp = nil
+		origP.quotaAlloc = nil
+		origP.ec = makeEmptyEndCmds()
+		origP.doneCh = nil
```
Comment (pavelkalinnikov) [inline pkg/kv/kvserver/replica_application_result.go:361]: Alternatively, we could put all these (maybe a few other) fields, and the context, to a struct, and reference the whole struct from `ProposalData` instead of moving/copying things between proposals.

Comment (erikgrinaker) [reply pkg/kv/kvserver/replica_application_result.go:361]: I think it's fine to keep this as it is.

File: pkg/kv/kvserver/replica_application_result.go [hunk 2]
```diff
@@ -366,17 +343,30 @@ func (r *Replica) tryReproposeWithNewLeaseIndex(ctx context.Context, origCmd *re
...
+
+		// If the proposal is synchronous, the client is waiting on the original
+		// proposal. By the time it has to act on the result, a bunch of reproposals
+		// can have happened. Link them all, so that the client can see all
+		// proposals for post-processing.
+		//
+		// TODO(pavelkalinnikov): prove and assert that origP.reproposal was nil.
+		origP.reproposal = newProposal
```
Comment (erikgrinaker) [inline pkg/kv/kvserver/replica_application_result.go:369]: This will prevent garbage collection of all the intermediate reproposals. I don't think we hold on to them from anywhere else? Seems like it would be worthwhile to avoid.

I'm guessing the old proposal is discarded after we hit this code path? If so, we really only need the first and last proposal in the chain. We could e.g. have a backreference to the original proposal and update its forward reference to the latest reproposal, or we could have a cancel function that's propagated down to the active reproposal.

**Review by erikgrinaker — COMMENTED** [review]
LGTM in principle, just some minor tweaks.

File: pkg/kv/kvserver/replica_application_result.go (hunk 2 above)
Comment (pavelkalinnikov) [reply pkg/kv/kvserver/replica_application_result.go]: Reworked this bit. It became a bit more ugly, but the GC benefit seems worth it. Longer term, we should improve the lifecycle.

Comment (pavelkalinnikov) [reply pkg/kv/kvserver/replica_application_result.go]: Also, had to drop the invariant check.

**Review by erikgrinaker — COMMENTED** [review]
LGTM, but let's squash the chain/seed commits. We should also have a basic test for the proposal linking, if we can easily add one.

File: pkg/kv/kvserver/replica_raft.go [hunk 3]
```diff
@@ -327,7 +327,17 @@ func (r *Replica) evalAndPropose(
...
-		proposal.ctx = r.AnnotateCtx(context.TODO())
+		ctx := r.AnnotateCtx(context.TODO())
+		// When the caller abandons the request and returns, it Finishes the request
+		// trace. By that time, multiple reproposals can have occurred, and the
+		// latest one may be still running. Unbind context for the seed and its
+		// reproposals, so that they no longer post tracing updates through this
+		// context to a Finished span.
+		//
+		// See https://github.com/cockroachdb/cockroach/issues/107521
+		for p := proposal; p != nil; p = p.reproposal {
```
[the remark this answers is not in the document]
Comment (pavelkalinnikov) [reply pkg/kv/kvserver/replica_raft.go]: Done.

**Review by pav-kv — COMMENTED** [review]
Addressed inline comments, and squashed commits.

**Comment by pavelkalinnikov** [comment]
@erikgrinaker Ah hold on, I'm looking if I can add a test.

File: pkg/kv/kvserver/replica_application_result.go [hunk 4]
```diff
@@ -379,6 +385,27 @@ func (r *Replica) tryReproposeWithNewLeaseIndex(ctx context.Context, origCmd *re
...
+		//
+		// Unbind the latest reproposal's context so that it no longer posts updates
+		// to the tracing span (it won't apply anyway). Link to the new latest
+		// reproposal, so that the client can clear its context at post-processing.
+		//
+		// TODO(pavelkalinnikov): there should be a better way, after ProposalData
+		// lifecycle is reconsidered.
+		if last := seedP.lastReproposal; last != nil {
+			last.ctx = r.AnnotateCtx(context.TODO())
+		}
```
Comment (erikgrinaker) [inline pkg/kv/kvserver/replica_application_result.go]: Do we expect these abandoned proposals to ever be used, or are they discarded after we return here?

I think this code makes sense as defense-in-depth, but in principle we should be able to just leave it, right?

Comment (pavelkalinnikov) [reply pkg/kv/kvserver/replica_application_result.go]: Logically you're right - older proposals won't be applied so we can forget them. Physically though, I'm not sure that there isn't some kind of race in result of which an older proposal comes up and "used" (for some clean-up) even after a newer proposal has been submitted.

So yeah, this is defence in depth. Need to mark it as such in the comment, and revisit.

Comment (pavelkalinnikov) [reply pkg/kv/kvserver/replica_application_result.go]: I would really prefer having one context/trace shared by all (re-)proposals explicitly.

Comment (pavelkalinnikov) [reply pkg/kv/kvserver/replica_application_result.go]: Noted in the comment.

**Review by erikgrinaker — APPROVED** [review]
LGTM, thanks. It's possible that we prematurely clear the seed proposal's context here, which could possibly lose some trace events for the remainder of the failed application, but even if we do we likely don't care about them at this point anyway

**Comment by pavelkalinnikov** [comment]
bors r=erikgrinaker

**Comment by pavelkalinnikov** [comment]
We don't need to backport this, this refactoring is post-23.1.
