### PR TITLE
sql/schmachanger: use more friendly language for fallback

### LINKED ISSUE #97922: make new schema changer logging less alarming
**Describe the problem**

in 22.2.5 messages in the logs from the new schema changer seems to suggest a problem, while instead the true meaning of these messages is just to show that schema change is falling back to the legacy one:
``` 
I230302 14:40:35.717223 97101 sql/schemachanger/scbuild/internal/scbuildstmt/process.go:145 ⋮ [n1,client=127.0.0.1:52955,user=root] 309  failed building declarative schema change targets for GRANT with error: ‹*tree.Grant not implemented in the new schema changer›

I230302 14:41:31.380323 97101 sql/schemachanger/scbuild/internal/scbuildstmt/process.go:145 ⋮ [n1,client=127.0.0.1:52955,user=root] 320  failed building declarative schema change targets for GRANT with error: ‹*tree.Grant not implemented in the new schema changer›
```

in order to avoid confusion, can we rephrase these messages to something like:
```
declarative schema change targets for GRANT falling back to the legacy changer with message: ‹*tree.Grant not implemented in the new schema changer›
```

**Environment:**
 - CockroachDB version [22.2.5]

Jira issue: CRDB-24967

### PR DESCRIPTION
**Pull request by fqazi**
Previously, the declarative schema changer used slightly
alarming language when falling back. To address this,
this patch removes the word failure and uses softer
language. Also, the logging level is reduced to remove
this message by default.

Fixes: #97922

Release note: None

### CODE REVIEW

File: pkg/sql/schemachanger/scerrors/errors.go [hunk 1]
```diff
@@ -75,7 +75,7 @@ func (el EventLogger) HandlePanicAndLogError(ctx context.Context, err *error) {
 			log.InfofDepth(ctx, depth, "done %s in %s", el.msg, redact.Safe(timeutil.Since(el.start)))
 		}
 	case HasNotImplemented(*err):
-		log.InfofDepth(ctx, depth, "failed %s with error: %v", el.msg, *err)
+		log.InfofDepth(ctx, depth, "unsuccessful in %s with message: %v", el.msg, *err)
```
Comment (chengxiong-ruan) [inline pkg/sql/schemachanger/scerrors/errors.go:78]: How about something more straightforward like`declarative schema changer fallback %s with message:`, `unsuccessful` still sounds erroneous heh.

**Review by chengxiong-ruan — APPROVED** [review]

File: pkg/sql/schemachanger/scerrors/errors.go (hunk 1 above)
Comment (fqazi) [reply pkg/sql/schemachanger/scerrors/errors.go:78]: Adjusted to get rid of unsuccessful (the way the strings are joined doesn't help):
falling back from building declarative schema change targets for GRANT with message: ‹*tree.Grant not implemented in the new schema changer›

Comment (ajwerner) [reply pkg/sql/schemachanger/scerrors/errors.go:78]: Can we just get rid of this log message altogether? I don't think we get a ton of value from it. How about:

```
log.VEventfDepth(ctx, depth, 1, "declarative schema changer does not support %s: %v", el.msg, *err)
```

Comment (fqazi) [reply pkg/sql/schemachanger/scerrors/errors.go]: I'll go with that approach.

**Review by ajwerner — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/98112#-:-NQ21aAq7MTm-G8iE8CP:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @chengxiong-ruan)

**Review by ajwerner — APPROVED** [review]
Let's backport this

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/98112#-:-NQ21bCD7oJLbjtRB0GN:b59pcjc)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @chengxiong-ruan)

**Comment by fqazi** [comment]
@ajwerner TFTR!

bors r+

**Comment by fqazi** [comment]
blathers backport 22.2
