### PR TITLE
logictest: flush out indirect unsafe access in logictests

### LINKED ISSUE #154675: logictest: fix broken tests when unsafe internals are blocked
The stable sql interface project involves the restricting of access to the crdb_internal and system namespaces to external callers. This project is being done in two phases, the first where the ability to restrict access is available for testing, and then the second where these interfaces are actually restricted by default.

In order to accomplish the second part of this process, we need to allow all testing surfaces to succeed, which includes a number of things which attempt to read the unsafe internals. You can see examples of this breakage (and some of their possible fixes) in [this PR](https://github.com/cockroachdb/cockroach/pull/153415). One of these is is the logictests, which comprise a considerable portion of our unit testing system. Some of these inherently fail when the `allow_unsafe_internals` is defaulted to false, so we want to make sure they work appropriately.

Epic CRDB-55276
Jira issue: CRDB-55072

### LINKED ISSUE #155367: serverutils: change `allow_unsafe_internals` default value to true for tests
The stable sql interface project involves the restricting of access to the crdb_internal and system namespaces to external callers. This project is being done in two phases, the first where the ability to restrict access is available for testing, and then the second where these interfaces are actually restricted by default.

In order to accomplish the second part of this process, we need to allow all testing surfaces to succeed, which includes a number of things which attempt to read the unsafe internals. You can see examples of this breakage (and some of their possible fixes) in this PR. Since the tests are so heavily dependent on access to internal structures, part of this effort will be to allow all tests to access the unsafe internals. We'll do this likely by backing the tests with a cluster setting for the default session variable value, and setting it to true for tests.

Epic: CRDB-55276

Jira issue: CRDB-55410

### PR DESCRIPTION
**Pull request by angles-n-daemons**
We recently added a session variable which must be explicitly set
for a caller to access system and crdb_internal tables. There's a
concern however that the system will block due to "indirect" access, be
it query expansion, rewriting or anything else.

So users aren't surprised by this behavior, this PR modifies the
logictests so that by default, unless a query explicitly references the
system or crdb_internal tables, it will disallow access to the unsafe
internals. Doing so will hopefully flush out any possible instances of
unsafe access.

This PR also does a few things to make this possible:
 - Introduces a way in tests to override the session variable.
 - Adds a new knob option for the logictests, so that if there's
	 indirect access because a UDF is defined, the test writer can
	 explicitly allow for it.

Fixes: https://github.com/cockroachdb/cockroach/issues/154675
Fixes: https://github.com/cockroachdb/cockroach/issues/155367
Epic: [CRDB-55276](https://cockroachlabs.atlassian.net/browse/CRDB-55276)
Release note: None

### CODE REVIEW

**Comment by angles-n-daemons** [comment]
thanks gpt, that'll be fixed when we rebase on: https://github.com/cockroachdb/cockroach/pull/155821

**Comment by angles-n-daemons** [comment]
Unless I'm missing something, nested queries are handled by the database, not by the logic test client.

Going to remove the AI assistance label.

File: pkg/sql/sem/eval/testing_knobs.go [hunk 1]
```diff
@@ -41,6 +41,16 @@ type TestingKnobs struct {
...
+
+	// This knob needs to be used in the following ways:
+	// 1. In tests, there should be a way to override the allow unsafe variable.
+	// 2. If a test is not setup with a value, true should be the default.
+	// 3. There should be a way to setup a test so that there is no override.
+	//
+	// Conditions 2 and 3 remove the possibility for just a pointer to a boolean.
+	// If the value were nil, should the system set the override to true, or leave it nil?
+	// To fix the ambiguity, a function which returns nil can be used to indicate no override.
+	UnsafeOverride func() *bool
```
Comment (angles-n-daemons) [inline pkg/sql/sem/eval/testing_knobs.go:53]: Something this also doesn't say is that there should be a way to override an existing session's value, so it can't rely on changing the default session value.

**Review by yuzefovich — COMMENTED** [review]
> @yuzefovich reviewed 21 of 31 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/155530)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @alyshanjahani-crl, @kyle-a-wong, and @rafiss)

___
*[`-- commits` line 21 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/155530#-OdFcBJf-sxIRZarWLSZ:-OdFcBJf-sxIRZarWLS_:b445lqz):*
nit: if you want multiple issues to be auto-closed when a PR merges, then _each_ issue must be prefixed with a closing keyword (like "Fixes") in the _PR description_. (Currently only #154675 will be auto-closed.)
___
*[`pkg/sql/logictest/testdata/logic_test/bytes` line 160 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/155530#-OdFdxBh9lyqwyL9GOhL:-OdFdxBh9lyqwyL9GOhM:b-s71mt1) ([raw file](https://github.com/cockroachdb/cockroach/blob/625aad4eb271040dccd49672598a6d40db341104/pkg/sql/logictest/testdata/logic_test/bytes#L160)):*
> ```
> 
> query T
> -- allow-unsafe
> ```

This seems a bit hacky to me. A cleaner approach would be to extend `query` directive with `allow-unsafe` option - so we'd have something like `query T allow-unsafe`. `query` directive already supports some options, so it would be natural to extend it.
___
*[`pkg/sql/crdb_internal.go` line 4494 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/155530#-OdFdPOa01Jp_eILnPNW:-OdFdPOa01Jp_eILnPNX:b-mnvsad) ([raw file](https://github.com/cockroachdb/cockroach/blob/625aad4eb271040dccd49672598a6d40db341104/pkg/sql/crdb_internal.go#L4494)):*
> ```Go
> 	resultColumns: colinfo.RangesNoLeases,
> 	generator: func(ctx context.Context, p *planner, _ catalog.DatabaseDescriptor, limit int64, _ *stop.Stopper) (virtualTableGenerator, cleanupFunc, error) {
> 		defer p.DisableUnsafeInternalsCheck()()
> ```

nit: why are we allowing access to this particular virtual table? It's currently not in `SupportedCRDBInternalTables`.

**Comment by yuzefovich** [comment]
> Going to remove the AI assistance label.

IIUC the ask about AI assistance labels is to not remove labels that were added automatically but apply "AI review not helpful" label when the review was unhelpful.

**Review by angles-n-daemons — COMMENTED** [review]
I see it now, yeah I'll add that back with the additional label.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/155530#-:-OdFuMshAOVxBj90m8Q-:bstk1mk)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @alyshanjahani-crl, @kyle-a-wong, @rafiss, and @yuzefovich)

___
*[`-- commits` line 21 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/155530#-OdFcBJf-sxIRZarWLSZ:-OdFuV2tBvpqdlugrN_r:b-toegij):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

nit: if you want multiple issues to be auto-closed when a PR merges, then _each_ issue must be prefixed with a closing keyword (like "Fixes") in the _PR description_. (Currently only #154675 will be auto-closed.)
</blockquote></details>

Thanks! Updating now.
___
*[`pkg/sql/crdb_internal.go` line 4494 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/155530#-OdFdPOa01Jp_eILnPNW:-OdFrYUI5t2umqxwTIAz:b-nxhqm6) ([raw file](https://github.com/cockroachdb/cockroach/blob/625aad4eb271040dccd49672598a6d40db341104/pkg/sql/crdb_internal.go#L4494)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

nit: why are we allowing access to this particular virtual table? It's currently not in `SupportedCRDBInternalTables`.
</blockquote></details>

There's a `SHOW RANGES` type command which will fail on execution, because it uses this table under the hood. The changes we introduced for delegate behavior unblocked unsafe access primarily during planning, but this will block on `HasPrivilege` below.
___
*[`pkg/sql/logictest/testdata/logic_test/bytes` line 160 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/155530#-OdFdxBh9lyqwyL9GOhL:-OdFs-kdESqrV9P-kUO9:boc2fdb) ([raw file](https://github.com/cockroachdb/cockroach/blob/625aad4eb271040dccd49672598a6d40db341104/pkg/sql/logictest/testdata/logic_test/bytes#L160)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

This seems a bit hacky to me. A cleaner approach would be to extend `query` directive with `allow-unsafe` option - so we'd have something like `query T allow-unsafe`. `query` directive already supports some options, so it would be natural to extend it.
</blockquote></details>

Ah great point. Yeah I hadn't noticed that, seems much nicer.

**Review by yuzefovich — COMMENTED** [review]
Nice! A few more comments from me.

> @yuzefovich reviewed 8 of 31 files at r1, 1 of 1 files at r2, 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/155530#-:-OdG3U9i2YwrGxQsGs-z:b-lln2af)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @alyshanjahani-crl, @angles-n-daemons, @kyle-a-wong, and @rafiss)

___
*[`-- commits` line 21 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/155530#-OdFcBJf-sxIRZarWLSZ:-OdG0GQV1WpM9AvNzHv4:b-ewenbl):*
<details><summary><i>Previously, angles-n-daemons (Brian Dillmann) wrote…</i></summary><blockquote>

Thanks! Updating now.
</blockquote></details>

Note that the _PR description_ is the important part, not the _commit message_ (which has no influence on github auto-close behavior). (Somewhat confusingly, release notes from _commit messages_ matter, but not from the PR descriptions.)
___
*[`pkg/sql/crdb_internal.go` line 4494 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/155530#-OdFdPOa01Jp_eILnPNW:-OdG0cYo7z80IZk27wHg:bgnhfr8) ([raw file](https://github.com/cockroachdb/cockroach/blob/625aad4eb271040dccd49672598a6d40db341104/pkg/sql/crdb_internal.go#L4494)):*
<details><summary><i>Previously, angles-n-daemons (Brian Dillmann) wrote…</i></summary><blockquote>

There's a `SHOW RANGES` type command which will fail on execution, because it uses this table under the hood. The changes we introduced for delegate behavior unblocked unsafe access primarily during planning, but this will block on `HasPrivilege` below.
</blockquote></details>

nit: consider adding this context as a comment in the code.
___
*[`pkg/sql/opt/metadata.go` line 649 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/155530#-OdG1hnn7OYG56hWFscg:-OdG1hnn7OYG56hWFsch:b-16vf1a) ([raw file](https://github.com/cockroachdb/cockroach/blob/47cadd0853f689823e73d5a486e179fc55a9de51/pkg/sql/opt/metadata.go#L649)):*
> ```Go
> 
> 			// Disable unsafe internal checks for this data source.
> 			restoreUnsafeCheck = optCatalog.DisableUnsafeInternalCheck()
> ```

nit: we should just defer the restoration of unsafe check here - this will avoid some duplicated code below.
___
*[`pkg/testutils/serverutils/test_server_shim.go` line 379 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/155530#-OdG3DwDA6atkCjUXk5Q:-OdG3DwDA6atkCjUXk5R:b7qeaa7) ([raw file](https://github.com/cockroachdb/cockroach/blob/47cadd0853f689823e73d5a486e179fc55a9de51/pkg/testutils/serverutils/test_server_shim.go#L379)):*
> ```Go
> 	}
> 
> 	if evalTestingKnobs.UnsafeOverride == nil {
> ```

I'm confused - why can't we just leave `UnsafeOverride` field unset, which will mean that there is no override behavior (i.e. use the session variable)?
___
*[`pkg/sql/logictest/logic.go` line 1519 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/155530#-OdG1Bqj9mGaypxP4Mgl:-OdG1Bqj9mGaypxP4Mgm:b-y81met) ([raw file](https://github.com/cockroachdb/cockroach/blob/47cadd0853f689823e73d5a486e179fc55a9de51/pkg/sql/logictest/logic.go#L1519)):*
> ```Go
> 		}
> 		var evalTestingKnobs *eval.TestingKnobs
> 		if knobs.SQLEvalContext != nil {
> ```

nit: looks like `knobs.SQLEvalContext` should never be nil because we're explicitly initializing it at the beginning of `setSQLTestingKnobs`. We could just inline initialization of `UnsafeOverride` at the top of the method too.

**Review by angles-n-daemons — COMMENTED** [review]
great, thanks!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/155530#-:-OdKE1WFCJdW8wNjaZl8:b9y27z0)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @alyshanjahani-crl, @kyle-a-wong, @rafiss, and @yuzefovich)

___
*[`-- commits` line 21 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/155530#-OdFcBJf-sxIRZarWLSZ:-OdKE4fn1GOXZkBzMhIq:b-atvz9r):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

Note that the _PR description_ is the important part, not the _commit message_ (which has no influence on github auto-close behavior). (Somewhat confusingly, release notes from _commit messages_ matter, but not from the PR descriptions.)
</blockquote></details>

ack. thanks for the additional look
___
*[`pkg/sql/crdb_internal.go` line 4494 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/155530#-OdFdPOa01Jp_eILnPNW:-OdKE9pg2dV-2xNfN1Q0:b-1a5zpl) ([raw file](https://github.com/cockroachdb/cockroach/blob/625aad4eb271040dccd49672598a6d40db341104/pkg/sql/crdb_internal.go#L4494)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

nit: consider adding this context as a comment in the code.
</blockquote></details>

good idea, adding it now.
___
*[`pkg/sql/logictest/logic.go` line 1519 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/155530#-OdG1Bqj9mGaypxP4Mgl:-OdKG9Ed9VTAcM3PYcHy:b-y1lx7z) ([raw file](https://github.com/cockroachdb/cockroach/blob/47cadd0853f689823e73d5a486e179fc55a9de51/pkg/sql/logictest/logic.go#L1519)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

nit: looks like `knobs.SQLEvalContext` should never be nil because we're explicitly initializing it at the beginning of `setSQLTestingKnobs`. We could just inline initialization of `UnsafeOverride` at the top of the method too.
</blockquote></details>

ah nice catch, doing this now.
___
*[`pkg/sql/opt/metadata.go` line 649 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/155530#-OdG1hnn7OYG56hWFscg:-OdKGWCk6aT2SsNxyqiD:br4vg3c) ([raw file](https://github.com/cockroachdb/cockroach/blob/47cadd0853f689823e73d5a486e179fc55a9de51/pkg/sql/opt/metadata.go#L649)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

nit: we should just defer the restoration of unsafe check here - this will avoid some duplicated code below.
</blockquote></details>

We can't do it in the loop unfortunately, I was thinking about extracting this into a separate function, but wasn't sure if that was too much breakout. What do you think?
___
*[`pkg/testutils/serverutils/test_server_shim.go` line 379 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/155530#-OdG3DwDA6atkCjUXk5Q:-OdKGg8Z4G8xo3NMCYJE:b-y5tp30) ([raw file](https://github.com/cockroachdb/cockroach/blob/47cadd0853f689823e73d5a486e179fc55a9de51/pkg/testutils/serverutils/test_server_shim.go#L379)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

I'm confused - why can't we just leave `UnsafeOverride` field unset, which will mean that there is no override behavior (i.e. use the session variable)?
</blockquote></details>

Ah good question. We're soon going to flip the default to false, which would cause a lot of tests to break. Having it default to true for the test servers, so that generally all tests (excluding logictests) can safely introspect the unsafe internals is our general working plan.

**Review by yuzefovich — APPROVED** [review]
:lgtm:

> @yuzefovich reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/155530#-:-OdKMR2I9EQScqrocHwG:bnfp4nl)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @alyshanjahani-crl, @angles-n-daemons, @kyle-a-wong, and @rafiss)

___
*[`pkg/sql/opt/metadata.go` line 649 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/155530#-OdG1hnn7OYG56hWFscg:-OdKK5-g-KR83pUz_6Qp:b-ybfwnq) ([raw file](https://github.com/cockroachdb/cockroach/blob/47cadd0853f689823e73d5a486e179fc55a9de51/pkg/sql/opt/metadata.go#L649)):*
<details><summary><i>Previously, angles-n-daemons (Brian Dillmann) wrote…</i></summary><blockquote>

We can't do it in the loop unfortunately, I was thinking about extracting this into a separate function, but wasn't sure if that was too much breakout. What do you think?
</blockquote></details>

Oh, I see. We could extract the "outer" loop body into an anonymous function, and then we'd be able to defer the cleanup function within that anonymous function - this would make the code slightly more bullet-proof in case we add any more short-circuiting behavior here in the future. That said, this code hasn't been modified significantly since 2018, so the current approach seems good too, up to you.
___
*[`pkg/sql/crdb_internal.go` line 4494 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/155530#-OdKJoRlE860BuoztG5V:-OdKJoRlE860BuoztG5W:b-5forh3) ([raw file](https://github.com/cockroachdb/cockroach/blob/2270b86f6da401b0563b5ef025de6dd1c932023c/pkg/sql/crdb_internal.go#L4494)):*
> ```Go
> 	resultColumns: colinfo.RangesNoLeases,
> 	generator: func(ctx context.Context, p *planner, _ catalog.DatabaseDescriptor, limit int64, _ *stop.Stopper) (virtualTableGenerator, cleanupFunc, error) {
> 		// We have to disable the unsafe check on execution, because for this table we may have gotten to it through delegate execution, eg. SHOW RANGES.
> ```

nit: we strive for wrapping comments at 80 characters.

**Review by angles-n-daemons — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/155530)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @alyshanjahani-crl, @kyle-a-wong, @rafiss, and @yuzefovich)

___
*[`pkg/sql/crdb_internal.go` line 4494 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/155530#-OdKJoRlE860BuoztG5V:-OdKiP8yA7ROIbZWUBea:b-50h0vm) ([raw file](https://github.com/cockroachdb/cockroach/blob/2270b86f6da401b0563b5ef025de6dd1c932023c/pkg/sql/crdb_internal.go#L4494)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

nit: we strive for wrapping comments at 80 characters.
</blockquote></details>

ah got it, changing this now.
___
*[`pkg/sql/opt/metadata.go` line 649 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/155530#-OdG1hnn7OYG56hWFscg:-OdKibd21Ab90n0k82rf:bpy1928) ([raw file](https://github.com/cockroachdb/cockroach/blob/47cadd0853f689823e73d5a486e179fc55a9de51/pkg/sql/opt/metadata.go#L649)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

Oh, I see. We could extract the "outer" loop body into an anonymous function, and then we'd be able to defer the cleanup function within that anonymous function - this would make the code slightly more bullet-proof in case we add any more short-circuiting behavior here in the future. That said, this code hasn't been modified significantly since 2018, so the current approach seems good too, up to you.
</blockquote></details>

no if this seems reasonable I'm definitely for it. I (perhaps superstitiously) wanted to avoid changing the call stack.
