### PR TITLE
*: disable merge queue in more tests

### LINKED ISSUE #29085: kv: TestStopAtRangeBoundary failed under stress
SHA: https://github.com/cockroachdb/cockroach/commits/3cdd221e01048154f705e1efb130afb42338b462

Parameters:
```
TAGS=
GOFLAGS=
```

To repro, try:

```
# Don't forget to check out a clean suitable branch and experiment with the
# stress invocation until the desired results present themselves. For example,
# using stressrace instead of stress and passing the '-p' stressflag which
# controls concurrency.
./scripts/gceworker.sh start && ./scripts/gceworker.sh mosh
cd ~/go/src/github.com/cockroachdb/cockroach && \
make stress TESTS=TestStopAtRangeBoundary PKG=github.com/cockroachdb/cockroach/pkg/kv TESTTIMEOUT=5m STRESSFLAGS='-stderr=false -maxtime 20m -timeout 10m'
```

Failed test: https://teamcity.cockroachdb.com/viewLog.html?buildId=862395&tab=buildLog

```
=== RUN   TestStopAtRangeBoundary
W180827 05:10:29.886663 28782 server/status/runtime.go:294  [n?] Could not parse build timestamp: parsing time "" as "2006/01/02 15:04:05": cannot parse "" as "2006"
I180827 05:10:29.894645 28782 server/server.go:830  [n?] monitoring forward clock jumps based on server.clock.forward_jump_check_enabled
I180827 05:10:29.894783 28782 base/addr_validation.go:260  [n?] server certificate addresses: IP=127.0.0.1,::1; DNS=localhost,*.local; CN=node
I180827 05:10:29.894801 28782 base/addr_validation.go:300  [n?] web UI certificate addresses: IP=127.0.0.1,::1; DNS=localhost,*.local; CN=node
I180827 05:10:29.901077 28782 server/config.go:496  [n?] 1 storage engine initialized
I180827 05:10:29.901109 28782 server/config.go:499  [n?] RocksDB cache size: 128 MiB
I180827 05:10:29.901114 28782 server/config.go:499  [n?] store 0: in-memory, size 0 B
I180827 05:10:29.904072 28782 server/node.go:373  [n?] **** cluster 98777f96-1314-4897-9c1e-6f05d6d7f130 has been created
I180827 05:10:29.904122 28782 server/server.go:1401  [n?] **** add additional nodes by specifying --join=127.0.0.1:36689
I180827 05:10:29.904240 28782 gossip/gossip.go:382  [n1] NodeDescriptor set to node_id:1 address:<network_field:"tcp" address_field:"127.0.0.1:36689" > attrs:<> locality:<> ServerVersion:<major_val:2 minor_val:0 patch:0 unstable:12 > build_tag:"v2.1.0-alpha.20180702-2010-g3cdd221" started_at:1535346629904186585 
I180827 05:10:29.904953 28782 storage/store.go:1541  [n1,s1] [n1,s1]: failed initial metrics computation: [n1,s1]: system config not yet available
I180827 05:10:29.905010 28782 server/node.go:476  [n1] initialized store [n1,s1]: disk (capacity=512 MiB, available=512 MiB, used=0 B, logicalBytes=6.9 KiB), ranges=1, leases=0, queries=0.00, writes=0.00, bytesPerReplica={p10=7103.00 p25=7103.00 p50=7103.00 p75=7103.00 p90=7103.00 pMax=7103.00}, writesPerReplica={p10=0.00 p25=0.00 p50=0.00 p75=0.00 p90=0.00 pMax=0.00}
I180827 05:10:29.905060 28782 storage/stores.go:242  [n1] read 0 node addresses from persistent storage
I180827 05:10:29.905130 28782 server/node.go:697  [n1] connecting to gossip network to verify cluster ID...
I180827 05:10:29.906007 28782 server/node.go:722  [n1] node connected via gossip and verified as part of cluster "98777f96-1314-4897-9c1e-6f05d6d7f130"
I180827 05:10:29.906025 28782 server/node.go:546  [n1] node=1: started with [<no-attributes>=<in-mem>] engine(s) and attributes []
I180827 05:10:29.906217 28782 server/status/recorder.go:652  [n1] available memory from cgroups (8.0 EiB) exceeds system memory 16 GiB, using system memory
I180827 05:10:29.906238 28782 server/server.go:1807  [n1] Could not start heap profiler worker due to: directory to store profiles could not be determined
I180827 05:10:29.906281 28782 server/server.go:1538  [n1] starting https server at 127.0.0.1:36393 (use: 127.0.0.1:36393)
I180827 05:10:29.906293 28782 server/server.go:1540  [n1] starting grpc/postgres server at 127.0.0.1:36689
I180827 05:10:29.906304 28782 server/server.go:1541  [n1] advertising CockroachDB node at 127.0.0.1:36689
I180827 05:10:29.912311 28983 server/status/recorder.go:652  [n1,summaries] available memory from cgroups (8.0 EiB) exceeds system memory 16 GiB, using system memory
I180827 05:10:29.924332 29000 sql/event_log.go:126  [n1,intExec=optInToDiagnosticsStatReporting] Event: "set_cluster_setting", target: 0, info: {SettingName:diagnostics.reporting.enabled Value:true User:root}
I180827 05:10:29.943511 29028 sql/event_log.go:126  [n1,intExec=set-setting] Event: "set_cluster_setting", target: 0, info: {SettingName:version Value:2.0-12 User:root}
I180827 05:10:29.954946 29003 sql/event_log.go:126  [n1,intExec=disableNetTrace] Event: "set_cluster_setting", target: 0, info: {SettingName:trace.debug.enable Value:false User:root}
I180827 05:10:29.965895 29042 sql/event_log.go:126  [n1,intExec=initializeClusterSecret] Event: "set_cluster_setting", target: 0, info: {SettingName:cluster.secret Value:dad23bfa-4a24-4faf-abf5-3ca0db4b717e User:root}
I180827 05:10:29.972051 29058 sql/event_log.go:126  [n1,intExec=create-default-db] Event: "create_database", target: 50, info: {DatabaseName:defaultdb Statement:CREATE DATABASE IF NOT EXISTS defaultdb User:root}
I180827 05:10:29.974912 29062 sql/event_log.go:126  [n1,intExec=create-default-db] Event: "create_database", target: 51, info: {DatabaseName:postgres Statement:CREATE DATABASE IF NOT EXISTS postgres User:root}
I180827 05:10:29.975966 28782 server/server.go:1594  [n1] done ensuring all necessary migrations have run
I180827 05:10:29.976000 28782 server/server.go:1597  [n1] serving sql connections
I180827 05:10:29.976970 28782 storage/replica_command.go:298  [n1,s1,r1/1:/M{in-ax}] initiating a split of this range at key "a" [r2]
I180827 05:10:29.986024 29070 sql/event_log.go:126  [n1] Event: "node_join", target: 1, info: {Descriptor:{NodeID:1 Address:{NetworkField:tcp AddressField:127.0.0.1:36689} Attrs: Locality: ServerVersion:2.0-12 BuildTag:v2.1.0-alpha.20180702-2010-g3cdd221 StartedAt:1535346629904186585 LocalityAddress:[]} ClusterID:98777f96-1314-4897-9c1e-6f05d6d7f130 StartedAt:1535346629904186585 LastUp:1535346629904186585}
I180827 05:10:29.987641 29068 server/server_update.go:67  [n1] no need to upgrade, cluster already at the newest version
I180827 05:10:29.987744 28782 storage/replica_command.go:298  [n1,s1,r2/1:{a-/Max}] initiating a split of this range at key "b" [r3]
I180827 05:10:29.992945 28782 storage/replica_command.go:298  [n1,s1,r3/1:{b-/Max}] initiating a split of this range at key "c" [r4]
I180827 05:10:30.014944 29080 storage/replica_command.go:430  [merge,n1,s1,r2/1:{a-b}] initiating a merge of r3:{b-c} [(n1,s1):1, next=2, gen=1] into this range
I180827 05:10:30.018084 28782 storage/replica_command.go:298  [n1,s1,r4/1:{c-/Max}] initiating a split of this range at key "d" [r5]
W180827 05:10:30.019797 29038 storage/intent_resolver.go:668  [n1,s1] failed to push during intent resolution: failed to push "merge" id=4b94d973 key=/Local/Range"a"/RangeDescriptor rw=true pri=0.05606478 iso=SERIALIZABLE stat=PENDING epo=0 ts=1535346630.014955157,0 orig=1535346630.014955157,0 max=1535346630.014955157,0 wto=false rop=false seq=1
I180827 05:10:30.035607 28782 storage/replica_command.go:298  [n1,s1,r5/1:{d-/Max}] initiating a split of this range at key "e" [r6]
I180827 05:10:30.039925 29040 rpc/nodedialer/nodedialer.go:92  [merge,n1,s1,r2/1:{a-b}] connection to n1 established
I180827 05:10:30.042278 28902 storage/store.go:2656  [n1,s1,r2/1:{a-b}] removing replica r3/1
I180827 05:10:30.042502 28782 storage/replica_command.go:298  [n1,s1,r6/1:{e-/Max}] initiating a split of this range at key "f" [r7]
--- FAIL: TestStopAtRangeBoundary (0.19s)
=== RUN   TestStopAtRangeBoundary/reverse=true,limit=5,minResults=4
I180827 05:10:30.056508 29134 kv/dist_sender_server_test.go:1452  iteration: 0
I180827 05:10:30.056816 29134 kv/dist_sender_server_test.go:1452  iteration: 1
I180827 05:10:30.057128 28782 util/stop/stopper.go:537  quiescing; tasks left:
1      storage.intentResolver: processing intents
    --- FAIL: TestStopAtRangeBoundary/reverse=true,limit=5,minResults=4 (0.00s)
    	dist_sender_server_test.go:180: kv/dist_sender_server_test.go:1502 kv/dist_sender_server_test.go:361: scan 0 ([a c]): expected 4 rows, got 5 (0: "b2"="value"
    		1: "b1"="value"
    		2: "a3"="value"
    		3: "a2"="value"
    		4: "a1"="value")
=== RUN   TestStopAtRangeBoundary/reverse=false,limit=8,minResults=7
I180827 05:10:30.054045 29131 kv/dist_sender_server_test.go:1452  iteration: 0
    --- FAIL: TestStopAtRangeBoundary/reverse=false,limit=8,minResults=7 (0.00s)
    	dist_sender_server_test.go:211: kv/dist_sender_server_test.go:1499 kv/dist_sender_server_test.go:349: satisfied scan 2 ([a00 a01]) has ResumeSpan: a0{0-1}
=== RUN   TestStopAtRangeBoundary/reverse=true,limit=0,minResults=0
I180827 05:10:30.054417 29132 kv/dist_sender_server_test.go:1452  iteration: 0
I180827 05:10:30.054677 29132 kv/dist_sender_server_test.go:1452  iteration: 1
I180827 05:10:30.055227 29132 kv/dist_sender_server_test.go:1452  iteration: 2
I180827 05:10:30.055438 29132 kv/dist_sender_server_test.go:1452  iteration: 3
    --- FAIL: TestStopAtRangeBoundary/reverse=true,limit=0,minResults=0 (0.00s)
    	dist_sender_server_test.go:180: kv/dist_sender_server_test.go:1502 kv/dist_sender_server_test.go:361: scan 0 ([a c]): expected 2 rows, got 5 (0: "b2"="value"
    		1: "b1"="value"
    		2: "a3"="value"
    		3: "a2"="value"
    		4: "a1"="value")
=== RUN   TestStopAtRangeBoundary/reverse=false,limit=0,minResults=0
I180827 05:10:30.052932 29129 kv/dist_sender_server_test.go:1452  iteration: 0
    --- FAIL: TestStopAtRangeBoundary/reverse=false,limit=0,minResults=0 (0.00s)
    	dist_sender_server_test.go:180: kv/dist_sender_server_test.go:1499 kv/dist_sender_server_test.go:348: scan 0 ([a c]): expected 3 rows, got 5 (0: "a1"="value"
    		1: "a2"="value"
    		2: "a3"="value"
    		3: "b1"="value"
    		4: "b2"="value")

```

### LINKED ISSUE #29242: kv: TestParallelSender failed under stress
SHA: https://github.com/cockroachdb/cockroach/commits/d57a1f0f985b95226e38f20a2afa006b9e48e92e

Parameters:
```
TAGS=
GOFLAGS=
```

To repro, try:

```
# Don't forget to check out a clean suitable branch and experiment with the
# stress invocation until the desired results present themselves. For example,
# using stressrace instead of stress and passing the '-p' stressflag which
# controls concurrency.
./scripts/gceworker.sh start && ./scripts/gceworker.sh mosh
cd ~/go/src/github.com/cockroachdb/cockroach && \
make stress TESTS=TestParallelSender PKG=github.com/cockroachdb/cockroach/pkg/kv TESTTIMEOUT=5m STRESSFLAGS='-stderr=false -maxtime 20m -timeout 10m'
```

Failed test: https://teamcity.cockroachdb.com/viewLog.html?buildId=868119&tab=buildLog

```
=== RUN   TestParallelSender
W180829 05:14:46.740589 27778 server/status/runtime.go:310  [n?] Could not parse build timestamp: parsing time "" as "2006/01/02 15:04:05": cannot parse "" as "2006"
I180829 05:14:46.745319 27778 server/server.go:827  [n?] monitoring forward clock jumps based on server.clock.forward_jump_check_enabled
I180829 05:14:46.745445 27778 base/addr_validation.go:271  [n?] server certificate addresses: IP=127.0.0.1,::1; DNS=localhost,*.local; CN=node
I180829 05:14:46.745469 27778 base/addr_validation.go:311  [n?] web UI certificate addresses: IP=127.0.0.1,::1; DNS=localhost,*.local; CN=node
I180829 05:14:46.747663 27778 server/config.go:493  [n?] 1 storage engine initialized
I180829 05:14:46.747692 27778 server/config.go:496  [n?] RocksDB cache size: 128 MiB
I180829 05:14:46.747700 27778 server/config.go:496  [n?] store 0: in-memory, size 0 B
I180829 05:14:46.765372 27778 server/node.go:373  [n?] **** cluster 7a65beec-da83-4fbf-9230-8d2c0f5e47e5 has been created
I180829 05:14:46.765402 27778 server/server.go:1389  [n?] **** add additional nodes by specifying --join=127.0.0.1:45251
I180829 05:14:46.765553 27778 gossip/gossip.go:382  [n1] NodeDescriptor set to node_id:1 address:<network_field:"tcp" address_field:"127.0.0.1:45251" > attrs:<> locality:<> ServerVersion:<major_val:2 minor_val:0 patch:0 unstable:12 > build_tag:"v2.1.0-alpha.20180702-2098-gd57a1f0" started_at:1535519686765488257 
I180829 05:14:46.766569 27778 storage/store.go:1540  [n1,s1] [n1,s1]: failed initial metrics computation: [n1,s1]: system config not yet available
I180829 05:14:46.766660 27778 server/node.go:476  [n1] initialized store [n1,s1]: disk (capacity=512 MiB, available=512 MiB, used=0 B, logicalBytes=6.9 KiB), ranges=1, leases=0, queries=0.00, writes=0.00, bytesPerReplica={p10=7103.00 p25=7103.00 p50=7103.00 p75=7103.00 p90=7103.00 pMax=7103.00}, writesPerReplica={p10=0.00 p25=0.00 p50=0.00 p75=0.00 p90=0.00 pMax=0.00}
I180829 05:14:46.766719 27778 storage/stores.go:242  [n1] read 0 node addresses from persistent storage
I180829 05:14:46.766799 27778 server/node.go:697  [n1] connecting to gossip network to verify cluster ID...
I180829 05:14:46.771977 27778 server/node.go:722  [n1] node connected via gossip and verified as part of cluster "7a65beec-da83-4fbf-9230-8d2c0f5e47e5"
I180829 05:14:46.772010 27778 server/node.go:546  [n1] node=1: started with [<no-attributes>=<in-mem>] engine(s) and attributes []
I180829 05:14:46.772251 27778 server/status/recorder.go:652  [n1] available memory from cgroups (8.0 EiB) exceeds system memory 16 GiB, using system memory
I180829 05:14:46.772273 27778 server/server.go:1780  [n1] Could not start heap profiler worker due to: directory to store profiles could not be determined
I180829 05:14:46.772340 27778 server/server.go:1526  [n1] starting https server at 127.0.0.1:43859 (use: 127.0.0.1:43859)
I180829 05:14:46.772354 27778 server/server.go:1528  [n1] starting grpc/postgres server at 127.0.0.1:45251
I180829 05:14:46.772366 27778 server/server.go:1529  [n1] advertising CockroachDB node at 127.0.0.1:45251
I180829 05:14:46.773133 28001 server/status/recorder.go:652  [n1,summaries] available memory from cgroups (8.0 EiB) exceeds system memory 16 GiB, using system memory
I180829 05:14:46.827888 28034 sql/event_log.go:126  [n1,intExec=optInToDiagnosticsStatReporting] Event: "set_cluster_setting", target: 0, info: {SettingName:diagnostics.reporting.enabled Value:true User:root}
I180829 05:14:46.850400 28040 sql/event_log.go:126  [n1,intExec=set-setting] Event: "set_cluster_setting", target: 0, info: {SettingName:version Value:2.0-12 User:root}
I180829 05:14:46.856131 28046 sql/event_log.go:126  [n1,intExec=disableNetTrace] Event: "set_cluster_setting", target: 0, info: {SettingName:trace.debug.enable Value:false User:root}
I180829 05:14:46.873495 27827 sql/event_log.go:126  [n1,intExec=initializeClusterSecret] Event: "set_cluster_setting", target: 0, info: {SettingName:cluster.secret Value:edd8ffc9-2986-49b8-b86d-5c3dd96001a7 User:root}
I180829 05:14:46.882562 28060 sql/event_log.go:126  [n1,intExec=create-default-db] Event: "create_database", target: 50, info: {DatabaseName:defaultdb Statement:CREATE DATABASE IF NOT EXISTS defaultdb User:root}
I180829 05:14:46.886603 28064 sql/event_log.go:126  [n1,intExec=create-default-db] Event: "create_database", target: 51, info: {DatabaseName:postgres Statement:CREATE DATABASE IF NOT EXISTS postgres User:root}
I180829 05:14:46.887904 27778 server/server.go:1582  [n1] done ensuring all necessary migrations have run
I180829 05:14:46.887936 27778 server/server.go:1585  [n1] serving sql connections
I180829 05:14:46.888861 27778 storage/replica_command.go:298  [n1,s1,r1/1:/M{in-ax}] initiating a split of this range at key "a" [r2]
I180829 05:14:46.901750 27778 storage/replica_command.go:298  [n1,s1,r2/1:{a-/Max}] initiating a split of this range at key "b" [r3]
I180829 05:14:46.902510 28072 sql/event_log.go:126  [n1] Event: "node_join", target: 1, info: {Descriptor:{NodeID:1 Address:{NetworkField:tcp AddressField:127.0.0.1:45251} Attrs: Locality: ServerVersion:2.0-12 BuildTag:v2.1.0-alpha.20180702-2098-gd57a1f0 StartedAt:1535519686765488257 LocalityAddress:[]} ClusterID:7a65beec-da83-4fbf-9230-8d2c0f5e47e5 StartedAt:1535519686765488257 LastUp:1535519686765488257}
I180829 05:14:46.907220 27778 storage/replica_command.go:298  [n1,s1,r3/1:{b-/Max}] initiating a split of this range at key "c" [r4]
I180829 05:14:46.911299 28070 server/server_update.go:67  [n1] no need to upgrade, cluster already at the newest version
I180829 05:14:46.918082 27778 storage/replica_command.go:298  [n1,s1,r4/1:{c-/Max}] initiating a split of this range at key "d" [r5]
I180829 05:14:46.922875 27778 storage/replica_command.go:298  [n1,s1,r5/1:{d-/Max}] initiating a split of this range at key "e" [r6]
I180829 05:14:46.924530 28078 storage/replica_command.go:430  [merge,n1,s1,r3/1:{b-c}] initiating a merge of r4:{c-d} [(n1,s1):1, next=2, gen=1] into this range
I180829 05:14:46.935925 27778 storage/replica_command.go:298  [n1,s1,r6/1:{e-/Max}] initiating a split of this range at key "f" [r7]
I180829 05:14:46.948189 27778 storage/replica_command.go:298  [n1,s1,r7/1:{f-/Max}] initiating a split of this range at key "g" [r8]
I180829 05:14:46.952274 27778 storage/replica_command.go:298  [n1,s1,r8/1:{g-/Max}] initiating a split of this range at key "h" [r9]
I180829 05:14:46.968916 28132 rpc/nodedialer/nodedialer.go:92  [merge,n1,s1,r3/1:{b-c}] connection to n1 established
I180829 05:14:46.970126 27963 storage/store.go:2642  [n1,s1,r3/1:{b-c}] removing replica r4/1
W180829 05:14:46.972152 28201 storage/intent_resolver.go:668  [n1,s1] failed to push during intent resolution: failed to push "split" id=e68cd450 key=/Local/Range"g"/RangeDescriptor rw=true pri=0.04391074 iso=SERIALIZABLE stat=PENDING epo=0 ts=1535519686.952284263,0 orig=1535519686.952284263,0 max=1535519686.952284263,0 wto=false rop=false seq=1
I180829 05:14:46.973647 27778 storage/replica_command.go:298  [n1,s1,r9/1:{h-/Max}] initiating a split of this range at key "i" [r10]
I180829 05:14:46.978651 27778 storage/replica_command.go:298  [n1,s1,r10/1:{i-/Max}] initiating a split of this range at key "j" [r11]
--- FAIL: TestParallelSender (0.28s)
	dist_sender_server_test.go:1073: expected at least 9 parallel sends; got 8

```

### PR DESCRIPTION
**Pull request by benesch**
Take a more aggressive approach to disabling the merge queue in tests.
This commit disables the merge queue in all tests that send a manual
AdminSplit request, unless those tests were explicitly verified to be
safe to run with the merge queue on.

Release note: None

Fix #29085.
Fix #29242.

### CODE REVIEW

**Comment by benesch** [comment]
If this LGTY, please send this through Bors to reduce the flakiness!

File: pkg/internal/client/db.go [hunk 1]
```diff
@@ -471,6 +471,7 @@ func (db *DB) AdminMerge(ctx context.Context, key interface{}) error {
 //
 // The keys can be either byte slices or a strings.
 func (db *DB) AdminSplit(ctx context.Context, spanKey, splitKey interface{}) error {
+	return errors.New("manual split")
```
Comment (dt) [inline pkg/internal/client/db.go]: left over?

Comment (benesch) [reply pkg/internal/client/db.go]: Hahaha, thanks. That's going to cause a test failure or two.

Comment (benesch) [reply pkg/internal/client/db.go]: Done.

**Review by tbg — APPROVED** [review]
:lgtm: but please circle back to my comment about the skipped test.

bors r+

> Reviewed 19 of 21 files at r1, 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/29235#-:-LL3vtNk7WdXOKKtIVO3:b-lyc0ta)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/sql/distsql_physical_planner_test.go, line 99 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/29235#-LL3vj3A1L-Sf73GL-Ng:-LL3vj3A1L-Sf73GL-Nh:bksxyb8) ([raw file](https://github.com/cockroachdb/cockroach/blob/a5d3ae008c3f267253d680b160d9bf64c77d64b4/pkg/sql/distsql_physical_planner_test.go#L99)):*
> ```Go
> func TestPlanningDuringSplitsAndMerges(t *testing.T) {
> 	defer leaktest.AfterTest(t)()
> 	t.Skip()
> ```

Add a comment. Or unskip this? Might be spurious.

**Comment by tschottdorf** [comment]
bors r+

TestLint failed with the url checker :(

**Comment by petermattis** [comment]
I didn't look at the contents of this PR (yet), but be aware that there is also `Test{Cluster,Server}.SplitRange`. Did you also look for tests using those calls?

**Comment by tschottdorf** [comment]
The current test failure looks like it's still caused by the merge queue:

https://teamcity.cockroachdb.com/viewLog.html?buildId=869108&buildTypeId=Cockroach_UnitTests

```
 TestImportPgDump/read_data_only
```

I'll merge the other PR. Let's smoke out the remaining flakes without messing up everyone else's day.

**Comment by benesch** [comment]
> I didn't look at the contents of this PR (yet), but be aware that there is also Test{Cluster,Server}.SplitRange. Did you also look for tests using those calls?

I did, yep!

TestImportPgDump is finding a real bug with merges, I think. I've plumbed in a DisableMergeQueue knob with a TODO for now.

**Comment by benesch** [comment]
bors r=tschottdorf

**Review by benesch — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/29235)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/sql/distsql_physical_planner_test.go, line 99 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/29235#-LL3vj3A1L-Sf73GL-Ng:-LL5OPh94ZB-gzskc_b5:blz38er) ([raw file](https://github.com/cockroachdb/cockroach/blob/a5d3ae008c3f267253d680b160d9bf64c77d64b4/pkg/sql/distsql_physical_planner_test.go#L99)):*
<details><summary><i>Previously, tschottdorf (Tobias Schottdorf) wrote…</i></summary><blockquote>

Add a comment. Or unskip this? Might be spurious.
</blockquote></details>

Oops, didn't mean to commit. It's removed in the rev that's getting bors'd.

**Review by andreimatei — COMMENTED** [review]
Did you look at tests using `kv.setupMultipleRanges()`? E.g. `TestTxnCoordSenderRetries` should be in here but it's not.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/29235#-:-LL5lcUdEmQ-0OcZSGUt:b-b5qa46)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

**Review by andreimatei — COMMENTED** [review]
Also, did you check if any flake issues can be closed? "No" is a good enough answer, but I'd like to know for when looking at the ones assigned to me.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/29235#-:-LL5mEhN53r28rI2Zt5Y:bh4y31t)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

**Comment by benesch** [comment]
> Did you look at tests using kv.setupMultipleRanges()? E.g. TestTxnCoordSenderRetries should be in here but it's not.

Agh, I thought those were all covered by `startNoSplitMergeServer`. Looks like I missed these two

```
TestPropagateTxnOnError
TestTxnCoordSenderRetries
```

**Comment by benesch** [comment]
> Also, did you check if any flake issues can be closed? "No" is a good enough answer, but I'd like to know for when looking at the ones assigned to me.

There was only the one I linked in the PR description when I opened this last night. I'll do another sweep sometime this afternoon.

**Comment by benesch** [comment]
This is contingent on #29324 going in first.

**Comment by benesch** [comment]
bors r=tschottdorf
