### PR TITLE
generate-bazel-extra: make `dev gen bazel` work with custom symlink

### LINKED ISSUE #94162: bazel: make generate-bazel-extra more resilient with custom symlink
I have the following `build --symlink_prefix=bazel-` in `.bazelrc.user`, and because of this `./dev gen bazel` fails for me with
```
Target //pkg/cmd/generate-bazel-extra:generate-bazel-extra up-to-date:
  bazel-bin/pkg/cmd/generate-bazel-extra/generate-bazel-extra_/generate-bazel-extra
INFO: Elapsed time: 0.687s, Critical Path: 0.16s
INFO: 1 process: 1 internal.
INFO: Build completed successfully, 1 total action
INFO: Running command line: /bin/bash -c 'cd /Users/yuzefovich/go/src/github.com/cockroachdb/cockroach &&  bazel-bin/pkg/cmd/generate-bazel-extra/generaINFO: Build completed successfully, 1 total action
failed to run buildozer, got output: panic: fork/exec _bazel/bin/external/com_github_bazelbuild_buildtools/buildozer/buildozer_/buildozer: no such file or directory

goroutine 1 [running]:
main.runBuildozer({0x14000264000?, 0x14000264010?, 0x1400006cd58?})
	main/pkg/cmd/generate-bazel-extra/main.go:47 +0x130
main.generateTestSuites()
	main/pkg/cmd/generate-bazel-extra/main.go:263 +0x828
main.main()
	main/pkg/cmd/generate-bazel-extra/main.go:340 +0xe8
ERROR: exit status 2
```
IIRC I overriden the symlink prefix in order to be able to view source code of the CPU profiles, so it'd be nice to make `generate-bazel-extra` resilient to such setup.

### PR DESCRIPTION
**Pull request by liamgillies**
Previously, running `dev gen bazel` with a custom symlink would fail because the path to buildozer was hardcoded. This PR replaces the hardcoded path with a search to the location of generate-bazel-extra and finds buildozer from the relative resulting path.

Fixes: #94162
Release note: None

### CODE REVIEW

File: pkg/cmd/generate-bazel-extra/main.go [hunk 1]
```diff
@@ -41,8 +41,15 @@ var (
 )
 
 func runBuildozer(args []string) {
-	const buildozer = "_bazel/bin/external/com_github_bazelbuild_buildtools/buildozer/buildozer_/buildozer"
-	cmd := exec.Command(buildozer, args...)
+	var mdfindArgs = []string{"-literal", "kMDItemDisplayName == \"generate-bazel-extra\"", "kind:folder"}
```
Comment (rickystewart) [inline pkg/cmd/generate-bazel-extra/main.go:44]: `mdfind` isn't a standard Unix tool, so it won't necessarily be installed everywhere we need it.

I was expecting you would find the location of the current binary by checking `os.Args[0]`. Does that not work for some reason?

**Review by rickystewart — CHANGES_REQUESTED** [review]

File: pkg/cmd/generate-bazel-extra/main.go [hunk 2]
```diff
@@ -41,7 +41,7 @@ var (
 )
 
 func runBuildozer(args []string) {
-	const buildozer = "_bazel/bin/external/com_github_bazelbuild_buildtools/buildozer/buildozer_/buildozer"
+	var buildozer = strings.TrimSuffix(os.Args[0], "\n") + ".runfiles/../../../../../external/com_github_bazelbuild_buildtools/buildozer/buildozer_/buildozer"
```
Comment (rickystewart) [inline pkg/cmd/generate-bazel-extra/main.go:44]: Why the `strings.TrimSuffix()`? Seems like it can be removed. If you were to keep it, `strings.TrimSpace()` is probably a better choice.

**Review by rickystewart — APPROVED** [review]

File: pkg/cmd/generate-bazel-extra/main.go (hunk 2 above)
Comment (liamgillies) [reply pkg/cmd/generate-bazel-extra/main.go:44]: Turns out there wasn't even a newline, I kept it from the previous code that did have a newline so I just removed it all together.

**Comment by liamgillies** [comment]
bors r=rickystewart
