### PR TITLE
kvserver: better obs in TestTxnReadWithinUncertaintyIntervalAfterRangeMerge

### LINKED ISSUE #143260: kv/kvserver: TestTxnReadWithinUncertaintyIntervalAfterRangeMerge failed
kv/kvserver.TestTxnReadWithinUncertaintyIntervalAfterRangeMerge [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_StressBazel/19169076?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_StressBazel/19169076?buildTab=artifacts#/) on release-23.2.22-rc @ [4aa9e5385aec01f3ce06b12b37caee5a62ad43cd](https://github.com/cockroachdb/cockroach/commits/4aa9e5385aec01f3ce06b12b37caee5a62ad43cd):

```
=== RUN   TestTxnReadWithinUncertaintyIntervalAfterRangeMerge
    test_log_scope.go:165: test logs captured to: /artifacts/tmp/_tmp/33e1d369c27b9c01b2b6009c561815a3/logTestTxnReadWithinUncertaintyIntervalAfterRangeMerge3725361250
    test_log_scope.go:76: use -show-logs to present logs inline
    client_replica_test.go:1055: -- test log scope end --
test logs left over in: /artifacts/tmp/_tmp/33e1d369c27b9c01b2b6009c561815a3/logTestTxnReadWithinUncertaintyIntervalAfterRangeMerge3725361250
--- FAIL: TestTxnReadWithinUncertaintyIntervalAfterRangeMerge (31.28s)
=== RUN   TestTxnReadWithinUncertaintyIntervalAfterRangeMerge/alignLeaseholders=true
    --- FAIL: TestTxnReadWithinUncertaintyIntervalAfterRangeMerge/alignLeaseholders=true (15.96s)
=== RUN   TestTxnReadWithinUncertaintyIntervalAfterRangeMerge/alignLeaseholders=true/alsoSplit=true
    client_replica_test.go:1037: 
        	Error Trace:	github.com/cockroachdb/cockroach/pkg/kv/kvserver_test/pkg/kv/kvserver/client_replica_test.go:1037
        	            				github.com/cockroachdb/cockroach/pkg/kv/kvserver_test/pkg/kv/kvserver/client_replica_test.go:1052
        	            				github.com/cockroachdb/cockroach/pkg/testutils/subtest.go:26
        	Error:      	Object expected to be of type *kvpb.ReadWithinUncertaintyIntervalError, but was <nil>
        	Test:       	TestTxnReadWithinUncertaintyIntervalAfterRangeMerge/alignLeaseholders=true/alsoSplit=true
        --- FAIL: TestTxnReadWithinUncertaintyIntervalAfterRangeMerge/alignLeaseholders=true/alsoSplit=true (7.93s)
```

Parameters:
 - <code>TAGS=bazel,gss,deadlock</code>
 - <code>stress=true</code>
<details><summary>Help</summary>
<p>

See also: [How To Investigate a Go Test Failure \(internal\)](https://cockroachlabs.atlassian.net/l/c/HgfXfJgM)
</p>
</details>
/cc @cockroachdb/kv
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*TestTxnReadWithinUncertaintyIntervalAfterRangeMerge.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)
</sub>

Jira issue: CRDB-48728

### PR DESCRIPTION
**Pull request by tbg**
Closes #143260.

This is a complex test with a rare failure mode. Trace all of the relevant operations so that we can meaningfully engage with it.

Epic: none
Release note: none

### CODE REVIEW

File: pkg/roachpb/data.go [hunk 1]
```diff
@@ -1545,6 +1545,18 @@ func (t Transaction) SafeFormat(w redact.SafePrinter, _ rune) {
 	}
 	w.Printf("meta={%s} lock=%t stat=%s rts=%s wto=%t gul=%s",
 		t.TxnMeta, t.IsLocking(), t.Status, t.ReadTimestamp, t.WriteTooOld, t.GlobalUncertaintyLimit)
+	for i, obs := range t.ObservedTimestamps {
```
Comment (stevendanna) [inline pkg/roachpb/data.go:1548]: I'm honestly surprised the test impact of this change isn't larger. It would be nice if SafeFormat also passed us the modifiers, because then we could do thinks like only do this for `+v` instead of just `v`.  Anyway, that isn't for this PR.


For this PR, do you think it would make sense to truncate this if there was a very large number of nodes?

**Review by stevendanna — APPROVED** [review]

File: pkg/roachpb/data.go (hunk 1 above)
Comment (tbg) [reply pkg/roachpb/data.go]: Good point. I removed this, will open a separate PR.

**Comment by rickystewart** [comment]
I have a failure of this test [here](https://mesolite.cluster.engflow.com/invocations/default/567ef553-bd74-4378-a51e-4a0bff35b9f2), is it plausible this PR introduced this failure mode? (I don't see an error like this searching my email) Or if not, is it possible the observability added here allows us to diagnose an issue?

**Comment by tbg** [comment]
Ugh yeah this definitely explodes because of this PR. Let me revert.
