### PR TITLE
sql/types: reintroduce downgradeType for NAME compatibility in mixed clusters

### LINKED ISSUE #153322: roachtest: schemachange/mixed-versions failed [function doesn't exist]
roachtest.schemachange/mixed-versions [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyAzureBazel/20452368?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyAzureBazel/20452368?buildTab=artifacts#/schemachange/mixed-versions) on master @ [fe3f3462c904d4735fef481fff4536925d9d7a77](https://github.com/cockroachdb/cockroach/commits/fe3f3462c904d4735fef481fff4536925d9d7a77):

```
(mixedversion.go:889).Run: mixed-version test failure while running step 15 (run "run schemachange workload and validation in mixed version"): full command output in run_072521.579822438_n4_COCKROACHRANDOMSEED1.log: COMMAND_PROBLEM: exit status 1
test artifacts and logs in: /artifacts/schemachange/mixed-versions/run_1
```

Parameters:
 - <code>arch=amd64</code>
 - <code>cloud=azure</code>
 - <code>coverageBuild=false</code>
 - <code>cpu=4</code>
 - <code>encrypted=false</code>
 - <code>fs=ext4</code>
 - <code>localSSD=true</code>
 - <code>mvtDeploymentMode=shared-process</code>
 - <code>mvtVersions=v25.3.1 → master</code>
 - <code>runtimeAssertionsBuild=false</code>
 - <code>ssd=0</code>
<details><summary>Help</summary>
<p>

See: [roachtest README](https://github.com/cockroachdb/cockroach/blob/master/pkg/cmd/roachtest/README.md)

See: [How To Investigate \(internal\)](https://cockroachlabs.atlassian.net/l/c/SSSBr8c7)

_Grafana is not yet available for azure clusters_</p>
</details>
<details><summary>Same failure on other branches</summary>
<p>

- #153016 roachtest: schemachange/mixed-versions failed [index_key_decoding_error] [B-runtime-assertions-enabled C-test-failure O-roachtest O-robot P-2 T-sql-foundations branch-release-24.3]
</p>
</details>
/cc @cockroachdb/sql-foundations
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*schemachange/mixed-versions.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/bazci/githubpost/issues)

</sub>

Jira issue: CRDB-54354

### PR DESCRIPTION
**Pull request by spilchen**
This patch restores the `downgradeType` hook to maintain serialization compatibility for the NAME type in mixed-version clusters (v25.3 and 25.4).

In previous releases, a NAME type could be misinterpreted by older nodes. Specifically, a v25.3 node deserializing a NAME encoded by a v25.4 node would mistakenly treat it as text (`oid.T_text`). This was due to the old `upgradeType` logic overwriting the OID when no `VisibleType` was set, causing `T_name` to degrade to `T_text`. PR #148694 addressed this issue for v25.4 by changing `upgradeType` (to avoid clobbering a provided OID) and removing the `downgradeType` function.

However, the follow-up fix for mixed-version serialization (PR #152633) relied on the `InternalType.VisibleType` field to tag string types for older nodes. Because the NAME type doesn’t use a `VisibleType` (it’s represented as a STRING family with a special OID), that change didn’t cover NAME. As a result, NAME remained broken in a 25.3/25.4 mixed cluster.

This commit explicitly handles NAME during serialization. When sending a NAME type to the wire, we downgrade it to the legacy encoding: we set its type family to `Family=name` (legacy enum value 11) so that v25.3 nodes recognize it as a NAME. Additionally, if the locale is an empty string, we set it to `nil` to ensure older versions don’t misclassify the NAME as a collated string. Together, these steps preserve the correct type interpretation on older nodes.

Once all nodes are on v25.4, this compatibility shim can be removed. At that point, the improved upgrade logic in v25.4 (which no longer overrides a valid OID) means we won’t need to downgrade types for backward compatibility. We may also perform a one time descriptor migration to update any NAME descriptors to the modern format after the cluster upgrade. In short, `downgradeType` for NAME is a temporary measure to bridge the v25.3 gap.

Fixes #153322

Release note: None

### CODE REVIEW

File: pkg/sql/types/types.go [hunk 1]
```diff
@@ -2526,7 +2526,14 @@ func (t *T) IsPseudoType() bool {
 //
 // Marshal is part of the protoutil.Message interface.
 func (t *T) Size() (n int) {
-	return t.InternalType.Size()
+	// Need to first downgrade the type before delegating to InternalType,
+	// because Marshal will downgrade.
+	temp := *t
```
Comment (rafiss) [inline pkg/sql/types/types.go:2535]: this line with the pointer dereference was actually the original cause of the race condition. could we add an early-exit so we don't do anything for all types that do not have `oid == T_name`?

File: pkg/sql/types/types.go [hunk 2]
```diff
@@ -2832,12 +2839,63 @@ func (t *T) upgradeType() error {
...
+// are serialized in a format that is backwards-compatible with the previous
+// version of CRDB so that clusters can run in mixed version mode during
+// upgrade.
 //
 //	bytes, err := protoutil.Marshal(&typ)
 func (t *T) Marshal() (data []byte, err error) {
-	return protoutil.Marshal(&t.InternalType)
+	// First downgrade to a struct that will be serialized in a backwards-
+	// compatible bytes format.
+	temp := *t
```
Comment (rafiss) [inline pkg/sql/types/types.go:2885]: similar to above -- we can skip this pointer dereference if the oid is not `T_name`

**Review by rafiss — APPROVED** [review]
nice find! just had one question about skipping the `downgradeType` logic conditionally

File: pkg/sql/types/types.go (hunk 1 above)
Comment (spilchen) [reply pkg/sql/types/types.go:2535]: Good idea. I applied this comment.

File: pkg/sql/types/types.go (hunk 2 above)
Comment (spilchen) [reply pkg/sql/types/types.go:2885]: Done.

**Review by spilchen — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/154363)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @rafiss)

**Comment by spilchen** [comment]
TFTR!

bors r+
