### PR TITLE
Always make sure to clear out range cache entries which overlap on insert.

### LINKED ISSUE #1459: TestMultiRangeScanDeleteRange fails with multiple CPUs
repro: `make CPUS=2,3,4,5,6,7,8 PKG=./server TESTS=TestMultiRangeScanDeleteRange`

Subtask of #1406.

### PR DESCRIPTION
**Pull request by spencerkimball**
This bug showed up with lots of CPUs as all of the intents created when
splitting the range get resolved in parallel and end up inserting old
range descriptors after eviction was complete. This would leave
overlapping descriptors such as ""-"m", ""-"\xff\xff", which would cause
dist sender to scan indefinitely.

Fixes #1459.

### CODE REVIEW

File: kv/dist_sender.go [hunk 1]
```diff
@@ -559,10 +559,10 @@ func (ds *DistSender) sendAttempt(desc *proto.RangeDescriptor, call proto.Call)
 	return retry.Break, nil
 }
 
-// getDescriptors takes a call and looks up the corresponding range descriptors
-// associated to it. First, the range descriptor for call.Args.Key is looked up;
-// second, if call.Args.EndKey exceeds that of the returned descriptor, the
-// next descriptor is obtained as well.
+// getDescriptors takes a call and looks up the corresponding range
+// descriptors associated with it. First, the range descriptor for
```
Comment (tamird) [inline kv/dist_sender.go]: not quite, since it returns at most two descriptors, while the call may span more than two ranges

File: kv/range_cache.go [hunk 2]
```diff
@@ -195,18 +203,21 @@ func (rmc *rangeDescriptorCache) getCachedRangeDescriptor(key proto.Key) (
...
 // cache. It is assumed that the caller holds a read lock on rmc.rangeCacheMu.
-func (rmc *rangeDescriptorCache) getCachedRangeDescriptorLocked(key proto.Key) (
+func (rmc *rangeDescriptorCache) getCachedRangeDescriptorLocked(key proto.Key, inclusive bool) (
 	rangeCacheKey, *proto.RangeDescriptor) {
-	// We want to look up the range descriptor for key. The cache is
-	// indexed using the end-key of the range, but the end-key is
-	// non-inclusive. So we access the cache using key.Next().
-	metaKey := keys.RangeMetaKey(key.Next())
+	// The cache is indexed using the end-key of the range, but the
+	// end-key is non-inclusive. If inclusive is false, we access the
```
Comment (bdarnell) [inline kv/range_cache.go]: This comment is implementation-focused; could you add a comment outside the function explaining this from the caller's perspective (i.e. what it means to pass inclusive or non-inclusive, because it's hard to tell from the outside why one caller passes true and the others don't)

**Comment by bdarnell** [comment]
LGTM. Is there any way to add a test for this that doesn't depend on a race across multiple cpus?

File: kv/range_cache.go (hunk 2 above)
Comment (tamird) [inline kv/range_cache.go]: or provide a new function and use the names to convey that meaning

**Comment by tamird** [comment]
@bdarnell see my TODO just above the affected code in range_cache.go  :(

**Comment by bdarnell** [comment]
There's a typo in the commit message: "makie"

**Comment by tamird** [comment]
Hurray this is the last one.

**Comment by tschottdorf** [comment]
LGTM. I would like to see the code refactored such that concurrent lookups which would result in the same descriptor wait for the first one, but this is difficult since the key range is only known after completion of the call. The current code basically proxies the range's load to the first range while a descriptor is being updated, and that seems dangerous.

The best solution I can think of right now is to not kick out old descriptors, but instead leave them cached and mark them as stale (so that they're not returned to the client). The first attempt to look up that descriptor could then trigger the actual lookup and have all others wait. On successful lookup, replace the stale and release the lock. If that sounds reasonable, I'll file an issue.

File: kv/dist_sender_test.go [hunk 3]
```diff
@@ -454,7 +454,7 @@ func TestEvictCacheOnError(t *testing.T) {
 		if cur := ds.leaderCache.Lookup(1); reflect.DeepEqual(cur, &proto.Replica{}) && !tc.shouldClearLeader {
 			t.Errorf("%d: leader cache eviction: shouldClearLeader=%t, but value is %v", i, tc.shouldClearLeader, cur)
 		}
-		_, cachedDesc := ds.rangeCache.getCachedRangeDescriptor(call.Args.Header().Key)
+		_, cachedDesc := ds.rangeCache.getCachedRangeDescriptor(call.Args.Header().Key, false)
```
Comment (tschottdorf) [inline kv/dist_sender_test.go]: only `getCachedRangeDescriptorLocked` has the second argument.

**Comment by spencerkimball** [comment]
@tschottdorf let's not add an issue until we profile this as a real problem. Right now I agree it's a bit messy how concurrent incoming range lookups can change the cache back and forth. The whole thing is frothy, but it's also simpler than putting a gating mechanism in place. For all we know, this frothy implementation is actually more efficient under common scenarios. Let's not add complexity until there's a clear mandate.

File: kv/dist_sender_test.go [hunk 4]
```diff
@@ -376,7 +376,9 @@ func TestRetryOnDescriptorLookupError(t *testing.T) {
 	ctx := &DistSenderContext{
 		rpcSend: testFn,
 		rangeDescriptorDB: mockRangeDescriptorDB(func(_ proto.Key, _ lookupOptions) (_ []proto.RangeDescriptor, err error) {
-			err, errors = errors[0], errors[1:]
```
Comment (tamird) [inline kv/dist_sender_test.go]: why make this change?

File: kv/range_cache.go [hunk 5]
```diff
@@ -221,3 +230,38 @@ func (rmc *rangeDescriptorCache) getCachedRangeDescriptorLocked(key proto.Key) (
...
+		if log.V(1) {
+			log.Infof("considering overlapping descriptor: key=%s desc=%s", k, desc)
+		}
+		addrKey := keys.KeyAddress(key)
+		if !addrKey.Less(desc.StartKey) && !desc.EndKey.Less(addrKey) {
+			if log.V(1) {
+				log.Infof("clearing overlapping descriptor: key=%s desc=%s", k, desc)
+			}
+			rmc.rangeCache.Del(k.(rangeCacheKey))
+		}
```
Comment (tamird) [inline kv/range_cache.go]: else { log.Infof("not clearing overlapping descriptor because...") }

File: kv/dist_sender_test.go (hunk 4 above)
Comment (spencerkimball) [inline kv/dist_sender_test.go]: The previous code took me about 20 seconds to decipher.

File: kv/range_cache.go (hunk 5 above)
Comment (spencerkimball) [inline kv/range_cache.go]: This is an incredibly common case and doesn't deserve a log line. The Ceil will return the next highest descriptor. We don't clear if it's not overlapping, which is what this if statement is checking.

File: kv/dist_sender_test.go (hunk 4 above)
Comment (tamird) [inline kv/dist_sender_test.go]: fair enough, but this pattern is quite common, i don't think we want to change it everywhere

File: kv/range_cache.go (hunk 5 above)
Comment (tamird) [inline kv/range_cache.go]: don't you think it's worth having a balancing log line to the "considering" log?

File: kv/dist_sender_test.go (hunk 4 above)
Comment (spencerkimball) [inline kv/dist_sender_test.go]: Where else is it?

File: kv/range_cache.go (hunk 5 above)
Comment (spencerkimball) [inline kv/range_cache.go]: Actually, going to remove the considering log line.

File: kv/dist_sender_test.go (hunk 4 above)
Comment (tamird) [inline kv/dist_sender_test.go]: I stand corrected: just one other place.
```
$ git grep -E '\[0\], .*\[1:\]'
client/reflect.go:              tq, queue = queue[0], queue[1:]
kv/dist_sender_test.go:                 err, errors = errors[0], errors[1:]
```

Comment (tamird) [inline kv/dist_sender_test.go]: Still, I've seen this pattern elsewhere, it seems to be a go idiom

**Comment by spencerkimball** [comment]
@tamird it might be a go idiom but in the context of that awkwardly written method:

        ctx := &DistSenderContext{
               rpcSend: testFn,
               rangeDescriptorDB: mockRangeDescriptorDB(func(_ proto.Key, _ lookupOptions) (_ []proto.RangeDescriptor, err error) {
                       err, errors = errors[0], errors[1:]

it's just not clear enough what's going on. `errors` is defined out of context; err is a named return value. It's a mess. Idiom or not, the code should be readable as the final test.
