### PR TITLE
mirror: fix non-determinism in case two packages have the same path

### LINKED ISSUE #143168: mirror: non-deterministic behavior if `go mod list` produces two packages with the same path
Today, if you do `go mod download -json`, you see the following:

```
{
	"Path": "github.com/axiomhq/hyperloglog",
	"Version": "v0.2.0",
	"Info": "/Users/ricky/go/pkg/mod/cache/download/github.com/axiomhq/hyperloglog/@v/v0.2.0.info",
	"GoMod": "/Users/ricky/go/pkg/mod/cache/download/github.com/axiomhq/hyperloglog/@v/v0.2.0.mod",
	"Zip": "/Users/ricky/go/pkg/mod/cache/download/github.com/axiomhq/hyperloglog/@v/v0.2.0.zip",
	"Dir": "/Users/ricky/go/pkg/mod/github.com/axiomhq/hyperloglog@v0.2.0",
	"Sum": "h1:u1XT3yyY1rjzlWuP6NQIrV4bRYHOaqZaovqjcBEvZJo=",
	"GoModSum": "h1:GcgMjz9gaDKZ3G0UMS6Fq/VkZ4l7uGgcJyxA7M+omIM="
}
{
	"Path": "github.com/axiomhq/hyperloglog",
	"Version": "v0.0.0-20181223111420-4b99d0c2c99e",
	"Info": "/Users/ricky/go/pkg/mod/cache/download/github.com/axiomhq/hyperloglog/@v/v0.0.0-20181223111420-4b99d0c2c99e.info",
	"GoMod": "/Users/ricky/go/pkg/mod/cache/download/github.com/axiomhq/hyperloglog/@v/v0.0.0-20181223111420-4b99d0c2c99e.mod",
	"Zip": "/Users/ricky/go/pkg/mod/cache/download/github.com/axiomhq/hyperloglog/@v/v0.0.0-20181223111420-4b99d0c2c99e.zip",
	"Dir": "/Users/ricky/go/pkg/mod/github.com/axiomhq/hyperloglog@v0.0.0-20181223111420-4b99d0c2c99e",
	"Sum": "h1:190ugM9MsyFauTkR/UqcHG/mn5nmFe6SvHJqEHIrtrA=",
	"GoModSum": "h1:IOXAcuKIFq/mDyuQ4wyJuJ79XLMsmLM+5RdQ+vWrL7o="
}
```

i.e., there are two packages with the same path. The mirroring code [assumes](https://github.com/cockroachdb/cockroach/blob/65b2ed4fbdf5502f3fbe0af4ddbd30a7ac7eabb4/pkg/cmd/mirror/go/mirror.go#L163) this will not be the case and treats it as a unique key. This is typically a sensible assumption but no longer holds since we are [using](https://github.com/cockroachdb/cockroach/blob/65b2ed4fbdf5502f3fbe0af4ddbd30a7ac7eabb4/go.mod#L500) `replace` to effectively import two different versions of the same dependency.

Unfortunately this has resulted in non-determinism as the code may randomly select the "wrong" `hyperloglog`. This has resulted in a version of this library being uploaded to the bucket that was incorrect (it's labeled as being version 0.2.5, when it was actually `v0.0.0-20181223111420-4b99d0c2c99e`).

Jira issue: CRDB-48687

### PR DESCRIPTION
**Pull request by rickystewart**
This code previously assumed that `go mod download -json` would not produce two different versions of the same dependency with the same path. This is typically a sensible assumption but no longer holds in some niche scenarios. We use [replace](https://github.com/cockroachdb/cockroach/blob/65b2ed4fbdf5502f3fbe0af4ddbd30a7ac7eabb4/go.mod#L500) in `go.mod` to effectively import two different versions of the same dependency with the same path. This results in non-determinism in the mirroring code with respect to which version of the dependency we select.

We now disambiguate with a path/version pair, which will be unique. We also add some additional validation to check assumptions so if these assumptions are ever broken in the future, the tool will fail loudly instead of proceeding silently and performing a potentially harmful operation.

Fixes #143168
Epic: CRDB-17171

Release note: None

### CODE REVIEW

File: pkg/cmd/mirror/go/mirror.go [hunk 1]
```diff
@@ -206,6 +218,19 @@ func listAllModules(tmpdir string) (map[string]listedModule, error) {
...
+			// `go list` but notably NOT the output of `go mod download`!!!
+			// `go list` lists modules by their imported names,
+			// and `go mod download` lists modules by their "real"
+			// names. For example, if you do `replace A => B`, the
+			// imported name is A but the "real" name is B. The
+			// imported name (A) is unique, but the "real" name is
+			// not. We can import B many times under different
+			// imported names.
+			if _, ok := ret[mod.Path]; ok {
+				panic(fmt.Sprintf("found duplicate imported path: %s. This is a bug. Go tell dev-inf about it.", mod.Path))
```
Comment (rail) [inline pkg/cmd/mirror/go/mirror.go:232]: Yes! :)

**Review by rail — APPROVED** [review]

**Comment by rickystewart** [comment]
bors r=rail
