### PR TITLE
storage: remove optimization to use in-memory RaftCommand when sideloading SSTs

### LINKED ISSUE #36861: storage: consistency check failure during import
## To do / understand

- [x] how did `nathan-tpcc-geo:7` end up rotating into a new log file to log the fatal error without retaining any prior ones? (answer: log rotation https://github.com/cockroachdb/cockroach/issues/36861#issuecomment-483589446)
- [ ] should we change something about where the diff goes or tweak the logging somehow?
- [x] take a RocksDB checkpoint on all nodes before fatal inconsistency errors (PR: https://github.com/cockroachdb/cockroach/pull/36867)

----

This looks very similar to https://github.com/cockroachdb/cockroach/issues/35424, so it's possible that that issue wasn't fully resolved. I was most of the way through a TPC-C 4k import when a node died due to a consistency check failure.

```
F190416 01:58:51.634989 172922 storage/replica_consistency.go:220  [n5,consistencyChecker,s5,r590/1:/Table/68/1/{29/4/2…-31/4/1…}] consistency check failed with 1 inconsistent replicas
goroutine 172922 [running]:
github.com/cockroachdb/cockroach/pkg/util/log.getStacks(0xc000056301, 0xc000056300, 0x5449800, 0x1e)
        /go/src/github.com/cockroachdb/cockroach/pkg/util/log/clog.go:1020 +0xd4
github.com/cockroachdb/cockroach/pkg/util/log.(*loggingT).outputLogEntry(0x5bdd700, 0xc000000004, 0x5449860, 0x1e, 0xdc, 0xc008bfa5a0, 0x79)
        /go/src/github.com/cockroachdb/cockroach/pkg/util/log/clog.go:878 +0x93d
github.com/cockroachdb/cockroach/pkg/util/log.addStructured(0x3aa1620, 0xc0071899e0, 0x4, 0x2, 0x33b2862, 0x36, 0xc01f06cce0, 0x1, 0x1)
        /go/src/github.com/cockroachdb/cockroach/pkg/util/log/structured.go:85 +0x2d8
github.com/cockroachdb/cockroach/pkg/util/log.logDepth(0x3aa1620, 0xc0071899e0, 0x1, 0xc000000004, 0x33b2862, 0x36, 0xc01f06cce0, 0x1, 0x1)
        /go/src/github.com/cockroachdb/cockroach/pkg/util/log/log.go:71 +0x8c
github.com/cockroachdb/cockroach/pkg/util/log.Fatalf(0x3aa1620, 0xc0071899e0, 0x33b2862, 0x36, 0xc01f06cce0, 0x1, 0x1)
        /go/src/github.com/cockroachdb/cockroach/pkg/util/log/log.go:182 +0x7e
github.com/cockroachdb/cockroach/pkg/storage.(*Replica).CheckConsistency(0xc023eeb400, 0x3aa1620, 0xc0071899e0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /go/src/github.com/cockroachdb/cockroach/pkg/storage/replica_consistency.go:220 +0x6ce
github.com/cockroachdb/cockroach/pkg/storage.(*Replica).CheckConsistency(0xc023eeb400, 0x3aa1620, 0xc0071899e0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /go/src/github.com/cockroachdb/cockroach/pkg/storage/replica_consistency.go:229 +0x81b
github.com/cockroachdb/cockroach/pkg/storage.(*consistencyQueue).process(0xc0003de2a0, 0x3aa1620, 0xc0071899e0, 0xc023eeb400, 0x0, 0x0, 0x0)
        /go/src/github.com/cockroachdb/cockroach/pkg/storage/consistency_queue.go:125 +0x210
```

Cockroach SHA: 3ebed10216aa83821b68eab023d3ed650bae8913

### Notes:
Cluster: `nathan-tpcc-geo` (stopped, extended for 48h)
Cockroach nodes: `1,2,4,5,7,8,10,11`
Inconsistent range: `r590`
Replicas: `nathan-tpcc-geo:2/n2/r3`, `nathan-tpcc-geo:5/n4/r4`, and `nathan-tpcc-geo:7/n5/r1`
Inconsistent replica: `nathan-tpcc-geo:7/n5/r1`
Replicas in zones: `europe-west2-b`, `europe-west4-b`, and `asia-northeast1-b` respectively

### Initial Investigation
Unlike in the later reproductions of #35424, replica 1's Raft log is an exact prefix of replica 3 and 4's, so this doesn't look like the same issue we saw later in that issue.

I haven't looked at much else yet.

[r590 Range _ Debug _ Cockroach Console.pdf](https://github.com/cockroachdb/cockroach/files/3082891/r590.Range._.Debug._.Cockroach.Console.pdf)

### PR DESCRIPTION
**Pull request by nvb**
Fixes #36861.

This optimization relied on the fact that `RaftCommands` in `Replica.mu.proposals` were immutable over the lifetime of a Raft proposal. This invariant was violated by #35261, which allowed a lease index error to trigger an immediate reproposal. This reproposal mutated the corresponding `RaftCommand` in `Replica.mu.proposals`. Combined with aliasing between multiple Raft proposals due to reproposals from ticks, this resulted in cases where a leaseholder's Raft logs could diverge from its followers and cause Raft groups to become inconsistent.

We can justify the new cost of unmarshalling `RaftCommands` in `maybeInlineSideloadedRaftCommand` on leaseholders because https://github.com/cockroachdb/cockroach/pull/36670/files#diff-8a33b5571aa9ab154d4f3c2a16724697R230 just landed. That change removes an equally sized allocation and memory copy from the function on both leaseholders and followers.

Release note: None

### CODE REVIEW

**Review by bdarnell — APPROVED** [review]
> Reviewed 4 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/36939)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @tbg)

File: pkg/storage/replica.go [hunk 1]
```diff
@@ -297,8 +297,7 @@ type Replica struct {
 		//
 		// The *ProposalData in the map are "owned" by it. Elements from the
 		// map must only be referenced while Replica.mu is held, except if the
-		// element is removed from the map first. The notable exception is the
-		// contained RaftCommand, which we treat as immutable.
+		// element is removed from the map first.
```
Comment (tbg) [inline pkg/storage/replica.go]: Be more specific. Mention that the proposal in this map corresponds to up to one raft entry, but that there may be other raft entries for the same CmdIDKey that correspond to earlier versions of the proposal. Point at `tryReproposeWithNewLeaseIndex` and `refreshProposalsLocked`.

**Review by tbg — APPROVED** [review]

File: pkg/storage/replica.go (hunk 1 above)
Comment (nvanbenschoten) [reply pkg/storage/replica.go]: Done.

**Review by andreimatei — COMMENTED** [review]
Is there a test to be added here?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/36939#-:-LcnasRg5_nbDWexx2R8:b-rjlcrv)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @bdarnell and @tbg)

**Comment by nvanbenschoten** [comment]
> Is there a test to be added here?

I don't think a unit test would be very useful. In order to be written such that it could have hit this, it would have to be so specific and so tied to implementation details that it won't actually be testing any behavior. I imagine it would just be a maintenance burden.

A new roachtest, on the other hand, sounds like a good idea. How does a geo-distributed version of the `import/tpcc` test sound?

**Comment by tbg** [comment]
I've reopened #36861 to track exactly that. The test we used for the repro could be the one we'll want to use.
