### PR TITLE
storage: deflake TestGossipFirstRange

### LINKED ISSUE #9746: Test failure (27138) TestGossipFirstRange
The test failed due to a timeout: https://teamcity.cockroachdb.com/viewQueued.html?itemId=27138

```
[...]
W161005 11:10:37.335823 20922 ts/db.go:113 [n3,ts-poll] node unavailable; try another peer W161005 11:10:42.247232 20727 gossip/infostore.go:295 [n1] node unavailable; try another peer I161005 11:10:42.250704 20674 kv/txn_coord_sender.go:251 [n1] txn coordinator: 0.01 txn/sec, 100.00/0.00/0.00/0.00 %cmmt/cmmt1pc/abrt/abnd, 0s/0s/0s avg/σ/max duration, 0.0/0.0/0 avg/σ/max restarts (0 samples) 
I161005 11:10:42.265809 20757 kv/txn_coord_sender.go:251 [n2] txn coordinator: 0.00 txn/sec, 100.00/0.00/0.00/0.00 %cmmt/cmmt1pc/abrt/abnd, 0s/0s/0s avg/σ/max duration, 0.0/0.0/0 avg/σ/max restarts (0 samples) 
W161005 11:10:42.297219 20747 gossip/infostore.go:295 [n2] node unavailable; try another peer 
I161005 11:10:42.324938 20823 kv/txn_coord_sender.go:251 [n3] txn coordinator: 0.00 txn/sec, 100.00/0.00/0.00/0.00 %cmmt/cmmt1pc/abrt/abnd, 0s/0s/0s avg/σ/max duration, 0.0/0.0/0 avg/σ/max restarts (0 samples) 
W161005 11:10:42.329529 20919 gossip/infostore.go:295 [n3] node unavailable; try another peer 

panic: test timed out after 2m0s 
goroutine 21110  [running]: 
panic(0x1619600, 0xc420ec80a0) 
/usr/local/go/src/runtime/panic.go:500 +0x1a1 testing.startAlarm.func1() 
/usr/local/go/src/testing/testing.go:918 +0x10b created by time.goFunc 
/usr/local/go/src/time/sleep.go:154 +0x44
[...]
```

### PR DESCRIPTION
**Pull request by tamird**
The channel used in this test is unbuffered, so it was possible for an
"extra" gossip callback to fire while the test is shutting down. This
commit unregisters the gossip callback before the test exits.

Fixes #9746.

---

This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/9747)

### CODE REVIEW

**Comment by tamird** [comment]
Before this change, I was able to instantly reproduce this failure. After the change, I've run 16803 over 5 minutes without reproduction.

**Comment by knz** [comment]
Can you explain more what you did? Your PR message says you unregister the message but the code reads as if you merely delay registering the callback.

**Comment by tamird** [comment]
Note the extra `()` at the end of the line. The `defer` runs the returned function.

**Comment by tamird** [comment]
Adjust to make this more obvious.

File: storage/gossip_test.go [hunk 1]
```diff
@@ -42,15 +42,17 @@ func TestGossipFirstRange(t *testing.T) {
...
 			var desc roachpb.RangeDescriptor
 			if err := content.GetProto(&desc); err != nil {
 				errors <- err
 			} else {
 				descs <- &desc
 			}
-		})
+		},
+	)
+	defer unregister()
```
Comment (tschottdorf) [inline storage/gossip_test.go]: Isn't this still flaky, at least in theory? You read `errors` for the last time in  line 105, so anytime after that a firing callback will still lose a goroutine.

Comment (tschottdorf) [inline storage/gossip_test.go]: Works for me, but could you put the above in a comment on the `unregister()` line?

**Comment by tschottdorf** [comment]
LGTM

**Comment by knz** [comment]
Thanks for explaining. LGTM.
-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.
