### PR TITLE
kvclient: when retrying transaction bump ts to now

### LINKED ISSUE #67802: sql/tests: TestMonotonicInserts/distsql=on failed
sql/tests.TestMonotonicInserts/distsql=on [failed](https://teamcity.cockroachdb.com/viewLog.html?buildId=3200931&tab=buildLog) with [artifacts](https://teamcity.cockroachdb.com/viewLog.html?buildId=3200931&tab=artifacts#/) on master @ [9f39af35fd81a7754e6123862b63247e3277b458](https://github.com/cockroachdb/cockroach/commits/9f39af35fd81a7754e6123862b63247e3277b458):

```
Slow failing tests:
TestMonotonicInserts/distsql=on - 2317.81s

Slow passing tests:
Example_demo - 210.29s
TestMergeQueueSeesNonVoters - 195.92s
TestExternalSortRandomized - 158.21s
TestAggregatorRandom - 143.75s
TestSortRandomized - 112.27s
TestIndexCleanupAfterAlterFromRegionalByRow - 110.84s
TestExternalSortMemoryAccounting - 104.40s
TestUnorderedDistinctRandom - 99.64s
TestLearnerSnapshotFailsRollback - 97.97s
TestBackupRestoreTenant - 94.55s
TestImportAvro - 83.87s
TestRestoreOldVersions - 77.22s
TestInvertedIndex - 70.65s
TestExternalDistinctSpilling - 66.81s
TestStoreRangeMergeTimestampCache - 66.38s
TestChangefeedSchemaChangeAllowBackfill - 58.81s
TestDefaultColumns - 56.85s
TestReadWriteFile - 56.74s
TestScatterRandomizeLeases - 56.47s
TestMultiNodeExportStmt - 56.22s
```
<details><summary>Reproduce</summary>
<p>
<p>To reproduce, try:

```bash
make stressrace TESTS=TestMonotonicInserts/distsql=on PKG=./pkg/sql/tests TESTTIMEOUT=5m STRESSFLAGS='-timeout 5m' 2>&1
```
</p>
<p>Parameters in this failure:

- GOFLAGS=-json
</p>
</p>
</details>
/cc @cockroachdb/sql-queries petermattis
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*TestMonotonicInserts/distsql=on.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)
</sub>

### PR DESCRIPTION
**Pull request by aliher1911**
Previously, when transaction failed with retryable error its timestamp
was bumped by whatever event caused it like a push.
If transaction timestamp becomes fixed to closed timestamp because
transaction takes more than 3 sec to complete it enters infinite retry
loop. Refresh is now impossible and transaction restarts with the same
failure after performing its actions. This behaviour is more visible
as we are updating closed timestamp more eagerly.
To prevent such outcome, this patch changes restart timestamp to now.

Release note: None

Fixes #67802

### CODE REVIEW

**Comment by aliher1911** [comment]
I didn't change comments there yet as I want to see if bumping timestamp unconditionally is the right thing to do here.

**Review by nvb — COMMENTED** [review]
Thanks for putting this patch together. Have you tested it out with `TestMonotonicInserts` to see whether it resolves the flakiness without the need for #69042? That patch seems like it would work to avoid the flakiness, but it's fairly unfortunate that it's needed at all, and if we can avoid it, I think we should.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/69096#-:-MiJ1XE8DNWddbGqPMtC:b-l779g4)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @aliher1911 and @andreimatei)

___
*[pkg/roachpb/data.go, line 1485 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/69096#-MiJ2Gs2-dK3vfgZy71A:-MiJ2Gs2-dK3vfgZy71B:b-my09en) ([raw file](https://github.com/cockroachdb/cockroach/blob/9e02a99f329643083f25fc748cbf1f9d4b330127/pkg/roachpb/data.go#L1485)):*
> ```Go
> 		// ahead of any timestamp cache entries or newer versions which caused
> 		// the restart.
> 		now := clock.Now()
> ```

Do we want to do this for all `TransactionRetryErrors`, or only those that have the `RETRY_SERIALIZABLE` reason? I'm thinking that we probably only want this behavior for read-write contention, so only for `RETRY_SERIALIZABLE` errors.
___
*[pkg/roachpb/data.go, line 1485 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/69096#-MiJ2YQj1L3oZruBw0At:-MiJ2YQj1L3oZruBw0Au:b-3pc1sz) ([raw file](https://github.com/cockroachdb/cockroach/blob/9e02a99f329643083f25fc748cbf1f9d4b330127/pkg/roachpb/data.go#L1485)):*
> ```Go
> 		// ahead of any timestamp cache entries or newer versions which caused
> 		// the restart.
> 		now := clock.Now()
> ```

Bumping the transaction timestamp to `now()` instead of to the conflict timestamp on read-write contention is an interesting behavioral change. On the surface, it's straightforward, but there are actually a few different decisions we need to make here.

The trade-off to keep in mind while making these decisions is that bumping a transaction's timestamp as little as possible minimizes the impact it will have on other transactions when it retries. However, bumping it all the way to `now()` minimizes the chance that it will need to be bumped again on a retry. So it maximizes the chance that it will actually succeed during its next epoch.

With that in mind, the first decision is whether we should be bumping the transaction timestamp to `now()` only after a restart, or whether we should be doing the same thing during a refresh as well. There's generally symmetry between how we treat txn refreshes and retries, and we'd be breaking that here. But that difference in behavior may be justifiable, because bumping the transaction timestamp any further than necessary before a refresh also hurts the chance that it will refresh successfully. That's because it increases the window that the refresh validation could observe changes to MVCC. So it does seem like we can be more aggressive about bumping a transaction's timestamp between retries than we are when doing so before a refresh.

The other decision is whether we should be bumping the transaction timestamp to `now()` in response to any read-write contention, or only in response to "contention" with the closed timestamp. The difference between the closed timestamp and other increases to a txn's write timestamp is that the closed timestamp is guaranteed to strike again on a retry. There's no guarantee that other read-write contention due to user transactions will recur during a retry. So I think an argument could be made that we should treat the closed timestamp differently. That said, when working at this level and making these kinds of decisions, I think it's best to assume the worst-case so that we can minimize the workloads that lead to starvation. So I think it's wise to assume that read-write contention due to user transactions will recur across retries and then design around that assumption.

So all that leads me to believe that what you have here is actually a very reasonable approach (though one that's lacking some commentary :smiley:). I'd like to get @andreimatei's take on this as well, though.

File: pkg/sql/tests/monotonic_insert_test.go [hunk 1]
```diff
@@ -214,6 +213,10 @@ RETURNING val, sts, node, tb`,
 			t.Errorf("'val' column is not unique: %d results, but %d distinct:\n%s",
 				len(results), numDistinct, results)
 		}
+
+		if len(results) < len(tc.Conns)*2 {
+			t.Errorf("test succeeded less queries then number of concurrent connections")
+		}
```
Comment (aliher1911) [inline pkg/sql/tests/monotonic_insert_test.go:219]: This part should go away because it demonstrates that test will be flaking because it gets into yet unexplained wait for X seconds.

**Review by aliher1911 — COMMENTED** [review]
It definitely prevents test from failing. The downside is, test could still get starved right on the first iteration before all workers have a chance to complete the transaction, then timeout kicks in and we cancel all contexts and we end up with just 4-5 entries in the table.
I put a piece of code that demonstrate failure, but it would go away in the final version since we don't want it to fail.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/69096#-:-MiQxtQT7qfhg7zk35Rb:bostw12)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @aliher1911 and @andreimatei)

**Comment by aliher1911** [comment]
I think this change might be risky to go into current release since we haven't seen it outside of tests.
Beside the test that is now disabled it shouldn't be a problem.

**Review by andreimatei — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/69096)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @nvanbenschoten)

___
*[pkg/roachpb/data.go, line 1485 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/69096#-MiJ2YQj1L3oZruBw0At:-MiWmnFm0DxHOPL9LfqV:b67e3k1) ([raw file](https://github.com/cockroachdb/cockroach/blob/9e02a99f329643083f25fc748cbf1f9d4b330127/pkg/roachpb/data.go#L1485)):*

> With that in mind, the first decision is whether we should be bumping the transaction timestamp to now() only after a restart, or whether we should be doing the same thing during a refresh as well. There's generally symmetry between how we treat txn refreshes and retries, and we'd be breaking that here. But that difference in behavior may be justifiable, because bumping the transaction timestamp any further than necessary before a refresh also hurts the chance that it will refresh successfully. That's because it increases the window that the refresh validation could observe changes to MVCC. So it does seem like we can be more aggressive about bumping a transaction's timestamp between retries than we are when doing so before a refresh.

I agree that "symmetry between refreshes and retries" is not an important thing to maintain. I think the calculus between the two is different enough.

But I wonder about whether refreshing just above the closed timestamp is a good idea. It means if the transaction is to write any more keys, it will run into the closedts again, and have to refresh again. So I'm thinking that, unless we know that there's not going to be any more writes (i.e. we're refreshing just before or just after an `EndTxn` with no writes in the batch), we should give the txn some breathing room - perhaps half of the closed timestamp lag. This would be at the cost of increasing that chances that the refresh will fail, but it seems worth it to me.

> The other decision is whether we should be bumping the transaction timestamp to now() in response to any read-write contention, or only in response to "contention" with the closed timestamp. The difference between the closed timestamp and other increases to a txn's write timestamp is that the closed timestamp is guaranteed to strike again on a retry. There's no guarantee that other read-write contention due to user transactions will recur during a retry. So I think an argument could be made that we should treat the closed timestamp differently. That said, when working at this level and making these kinds of decisions, I think it's best to assume the worst-case so that we can minimize the workloads that lead to starvation. So I think it's wise to assume that read-write contention due to user transactions will recur across retries and then design around that assumption.

Well, if we want to "be wise and assume the worst-case", then I think we need to be more sophisticated. The worst-case is that the transaction repeatedly takes too long to execute and runs into the closed timestamp on every retry (even if we bump it to now()), ad infinitum. And in this case, I think this patch makes things worse, because it makes the looping transaction interfere with foreground traffic a lot more - before this patch, if we were just bumping to 3s in the past, there was not much interference.
The argument that this patch is making, I guess, is that the reason why a txn ran into the closedts is because it encountered lock contention and that slowed it down. And the hope is that upon retry it won't be slowed down by contention again, and so it will succeed - particularly if we give it more time by bumping the restarting txn to now(). But I find this to be a pretty weak argument.

Can you please spell out exactly the specifics of the constant retries you're observing in the test we're fixing here?

---

One thing I'm thinking about is a possible general improvement: it seems to me that writing to a key on which the writing txn already has an intent (possibly from a previous epoch) does not need to check the closed timestamp. This is because the closed timestamp for a range is not exactly a promise that the range will not accept new writes at lower timestamps; it's only a promise that the range will not accept writes to keys without intents at lower timestamps. Does this sound right?
I'm thinking that perhaps this is the optimization that would allow some looping transactions to complete.

**Review by andreimatei — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/69096)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @nvanbenschoten)

___
*[pkg/roachpb/data.go, line 1485 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/69096#-MiJ2YQj1L3oZruBw0At:-MiYDccDAAWoN1nvSSPY:bp7yazb) ([raw file](https://github.com/cockroachdb/cockroach/blob/9e02a99f329643083f25fc748cbf1f9d4b330127/pkg/roachpb/data.go#L1485)):*
> There's generally symmetry between how we treat txn refreshes and retries, and we'd be breaking that here. But that difference in behavior may be justifiable, because bumping the transaction timestamp any further than necessary before a refresh also hurts the chance that it will refresh successfully.

I had a thought here, which is that perhaps it wouldn't be hard to change the way refreshes work such that, instead of a pass/fail, they return the lowest timestamp in the [a,b) refresh interval they find. So, instead of refreshing [read_timestamp, conflict_ts], one could refresh [read_timestamp, now()) and decide what it can bump the txn timestamp to based on the result of the refresh -> if the result is below conflict_ts, then the refresh failed. If it's above, then we bump to whatever the result is.

**Review by aliher1911 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/69096)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andreimatei and @nvanbenschoten)

___
*[pkg/roachpb/data.go, line 1485 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/69096#-MiJ2YQj1L3oZruBw0At:-MjU6Y3cCVSaxr1-bmMR:b-q29567) ([raw file](https://github.com/cockroachdb/cockroach/blob/9e02a99f329643083f25fc748cbf1f9d4b330127/pkg/roachpb/data.go#L1485)):*
> Can you please spell out exactly the specifics of the constant retries you're observing in the test we're fixing here?

The change is motivated by #67802. What we observed is that sometimes test starves and all 6 contending transactions can wait for eachother for couple of seconds. Once the first one resumes it is already past the closed ts and it fails refresh immediately. Upon retry in queries cluster ts and fixes itself to the retry timestamp which guarantees that it would fail and retry on closed ts again.

So test would spin unless it hits starvation identical to the one that caused the failure. In that case, heartbeater would abort transaction and unblock the rest. This bit is just for the context here.

**Review by andreimatei — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/69096)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @aliher1911 and @nvanbenschoten)

___
*[pkg/roachpb/data.go, line 1485 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/69096#-MiJ2YQj1L3oZruBw0At:-MjUxqmn1pcP5qEjb8HY:b-yd763n) ([raw file](https://github.com/cockroachdb/cockroach/blob/9e02a99f329643083f25fc748cbf1f9d4b330127/pkg/roachpb/data.go#L1485)):*
<details><summary><i>Previously, aliher1911 (Oleg) wrote…</i></summary><blockquote>

> Can you please spell out exactly the specifics of the constant retries you're observing in the test we're fixing here?

The change is motivated by #67802. What we observed is that sometimes test starves and all 6 contending transactions can wait for eachother for couple of seconds. Once the first one resumes it is already past the closed ts and it fails refresh immediately. Upon retry in queries cluster ts and fixes itself to the retry timestamp which guarantees that it would fail and retry on closed ts again.

So test would spin unless it hits starvation identical to the one that caused the failure. In that case, heartbeater would abort transaction and unblock the rest. This bit is just for the context here.
</blockquote></details>

I've gone back and forth a lot about whether I think this patch is an improvement worth making. It seems to help when a transaction has ran into the closed timestamp because it waited on locks for a while. But it doesn't help when the transaction ran into the closed timestamp because it takes too long to run; in fact, I think it hurts those cases.
I think the real way forward for transactions starved by the closed timestamp would be ensuring that they don't need to refresh through a combination of #63796 and #52768.
What would make this patch that deals with failed refreshes non-controversial for me would be having it only apply to transactions that have spent time waiting on locks. This would exempt transactions that are just slow. But, really, I'd work on #63796 first.

As I can't make up my mind on this patch by itself, I'd say that if you two like it, that's good enough.

**Review by nvb — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/69096)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @aliher1911, @andreimatei, and @nvanbenschoten)

___
*[pkg/roachpb/data.go, line 1485 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/69096#-MiJ2YQj1L3oZruBw0At:-MksQ6CYEk4aPzc4tSlk:bsu40xn) ([raw file](https://github.com/cockroachdb/cockroach/blob/9e02a99f329643083f25fc748cbf1f9d4b330127/pkg/roachpb/data.go#L1485)):*
I'm also a little torn on this, but I'm leaning in the direction of thinking this is a worthwhile change. As Andrei pointed out, this change helps if a transaction has variable execution time across retries and one happens to go above 3s, but it doesn't help if the transaction is persistently taking too long. I'd argue that's still a worthwhile improvement because it leads to a more stable system. It means that we can now safely run txns that have a high probability of finishing in less than 3s without the risk of tail latency pushing them into a loop that they can never escape from. This tail latency may be caused by contention or by any other transient behavior in the system, either under user control (e.g. lock contention) or not (e.g. background lease transfers) — I don't think it's worth drawing a distinction and only doing this when a transaction spent time waiting on locks.

So I'd suggest proceeding with this change.

> in fact, I think it hurts those cases.

Could you explain this further? Are you saying that it hurts because the transaction will proceed to read at a higher timestamp on future retries? My instinct is to say that interaction is insignificant when a transaction is in an infinite retry loop and blocking both itself and anyone else that is touching keys that it _wrote_ to.

> I had a thought here, which is that perhaps it wouldn't be hard to change the way refreshes work such that

This is interesting. But the tradeoff here is that these refreshes would then become more disruptive to other txns, both because a refreshing txn may refresh further than it needs to in order to serialize and because it may refresh to different timestamps on different ranges and can only take advantage of the lowest timestamp across all ranges.

**Review by andreimatei — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/69096)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @aliher1911, @andreimatei, and @nvanbenschoten)

___
*[pkg/roachpb/data.go, line 1485 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/69096#-MiJ2YQj1L3oZruBw0At:-MkspczX-a4NvZKwkNNW:b-vo8dr8) ([raw file](https://github.com/cockroachdb/cockroach/blob/9e02a99f329643083f25fc748cbf1f9d4b330127/pkg/roachpb/data.go#L1485)):*
> > in fact, I think it hurts those cases.
> 
> Could you explain this further? Are you saying that it hurts because the transaction will proceed to read at a higher timestamp on future retries?

Right.

 > My instinct is to say that interaction is insignificant when a transaction is in an infinite retry loop and blocking both itself and anyone else that is touching keys that it wrote to.

People blocking on keys the slow txn _wrote_ are fucked anyway. But where the refresh policy makes a different is for txns writing to keys the slow txn is _reading_. Without the patch, the txn in question stays in the past and doesn't interact with snappy present-time writers. With this patch, it does interact with them.

But don't let this stop the train.

**Comment by aliher1911** [comment]
@nvanbenschoten Nathan, I think we have consensus that it is not universally good, but likely more good then bad let's land this. We also had an issue recently where transaction failed to proceed because transaction was infinitely retrying. Alternatively, we can try to bump transaction to now only if epoch is lower than N so that if we can't proceed first few times then try to avoid interfering with other transactions.

**Review by nvb — COMMENTED** [review]
I think what you have here is good. Let's add a bit more to the comment and then see which tests need to be updated to accommodate for the change.

> Reviewed 1 of 1 files at r2, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/69096#-:-MlpGt4-33Z8fBEoT63s:by4tc9a)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @aliher1911)

___
*[pkg/roachpb/data.go, line 1487 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/69096#-MlpGa-R6ypnDpxzQqjv:-MlpGa-R6ypnDpxzQqjw:b-zdpijw) ([raw file](https://github.com/cockroachdb/cockroach/blob/70923a8f3efef231e876c467ca6f24e1d75fbc7e/pkg/roachpb/data.go#L1487)):*
> ```Go
> 			// For RETRY_SERIALIZABLE case, we want to bump timestamp further than
> 			// timestamp cache to increase chances of retry succeeding. The tradeoff
> 			// here is that impact of this transaction on conflicting ones is increased.
> ```

Let's write a little more here about the trade-off and why this is important. You talk about "chances of retry succeeding", but this doesn't quite get at the point about how without this, the transaction may be starved indefinitely in some cases.

**Review by aliher1911 — COMMENTED** [review]
I updated comments to try to reflect the cases and what are our tradeoff there. What do you think would be the right place to test? I checked and txn_test in kvcoord seem to test transaction contention, timeouts etc behaviours so seem like relevant place.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/69096#-:-MmJxU8w6OPgcPtMpvMA:b-8y9ljf)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @aliher1911 and @nvanbenschoten)

**Review by nvb — COMMENTED** [review]
> What do you think would be the right place to test?

I'd look first at which tests fail with this change. There should be plenty of existing test coverage that exercises this code.

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/69096#-:-MmQ4PEB9_rSujKJW512:byza6y)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @aliher1911 and @nvanbenschoten)

___
*[pkg/roachpb/data.go, line 1466 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/69096#-MmQ4lQ98hbyBHU_0f-k:-MmQ4lQA0L1r_aekVAAN:b-3nrv1x) ([raw file](https://github.com/cockroachdb/cockroach/blob/6e2dde03d35f3c59f65d28f0ac5fd5bb52674dab/pkg/roachpb/data.go#L1466)):*
> ```Go
> 			// timestamp cache.
> 			// This helps transactions that had their commit timestamp fixed (See
> 			// roachpb.Transaction.CommitTimestampFixed for details on when it happens).
> ```

It also helps transactions that aren't able to refresh due to read-write contention. This is arguably the more important case.
___
*[pkg/roachpb/data.go, line 1471 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/69096#-MmQ4p77AjhRqpzzXswF:-MmQ4p77AjhRqpzzXswG:b-qtd8ps) ([raw file](https://github.com/cockroachdb/cockroach/blob/6e2dde03d35f3c59f65d28f0ac5fd5bb52674dab/pkg/roachpb/data.go#L1471)):*
> ```Go
> 			// from succeeding.
> 			// The tradeoff here is that transactions that failed because they were
> 			// waiting on locks would have a chance to retry and succeed, but
> ```

Waiting on locks or were slowed down in their first epoch for any other reason (e.g. lease transfers, network congestion, node failure, etc.).
___
*[pkg/roachpb/data.go, line 1475 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/69096#-MmQ4Kp-9A35sMQRvbeY:-MmQ4Kp-9A35sMQRvbeZ:bljwhnl) ([raw file](https://github.com/cockroachdb/cockroach/blob/6e2dde03d35f3c59f65d28f0ac5fd5bb52674dab/pkg/roachpb/data.go#L1475)):*
> ```Go
> 			// delay transactions that try to write to the keys this transaction
> 			// reads because reads are not in the past anymore.
> 			//now := clock.Now()
> ```

Did you mean to comment this out?

**Review by aliher1911 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/69096)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @aliher1911 and @nvanbenschoten)

___
*[pkg/roachpb/data.go, line 1466 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/69096#-MmQ4lQ98hbyBHU_0f-k:-MmUJljC2devEdIc7xBH:b2exkd2) ([raw file](https://github.com/cockroachdb/cockroach/blob/6e2dde03d35f3c59f65d28f0ac5fd5bb52674dab/pkg/roachpb/data.go#L1466)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

It also helps transactions that aren't able to refresh due to read-write contention. This is arguably the more important case.
</blockquote></details>

Can you elaborate about this? I thought we are specifically vulnerable here if timestamp is fixed, in general case I thought we can try to refresh span.
___
*[pkg/roachpb/data.go, line 1475 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/69096#-MmQ4Kp-9A35sMQRvbeY:-MmTsv0gAj86bgqmvJLc:b-j6v4qh) ([raw file](https://github.com/cockroachdb/cockroach/blob/6e2dde03d35f3c59f65d28f0ac5fd5bb52674dab/pkg/roachpb/data.go#L1475)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Did you mean to comment this out?
</blockquote></details>

Sorry, that was a consequence of me backing it out to compare test behaviours.

**Review by aliher1911 — COMMENTED** [review]
I don't think any existing tests actually failed with this change at least in TC. That's why I thought adding something specific would make sense. If you think about it, we don't have a test that verifies that we could never get out of retry cycle.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/69096#-:-MmUKfKG-CcNRSXRspOF:btpx7zn)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @nvanbenschoten)

**Review by nvb — COMMENTED** [review]
> Reviewed 2 of 3 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/69096)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @aliher1911 and @nvanbenschoten)

___
*[pkg/kv/kvclient/kvcoord/txn_test.go, line 900 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/69096#-MmZ0Kxw34Y_ZiVAUtri:-MmZ0Kxw34Y_ZiVAUtrj:b-5ivs81) ([raw file](https://github.com/cockroachdb/cockroach/blob/52b6e5f269283658c002e470099f7ee7a58953aa/pkg/kv/kvclient/kvcoord/txn_test.go#L900)):*
> ```Go
> }
> 
> // TestRetrySerializableBumpsToNow verifies that transaction is restarted on now rather than
> ```

s/on now/to the current HLC time/
___
*[pkg/kv/kvclient/kvcoord/txn_test.go, line 914 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/69096#-MmZ3ba01LswHyrgFQXR:-MmZ3ba01LswHyrgFQXS:b-e6kogz) ([raw file](https://github.com/cockroachdb/cockroach/blob/52b6e5f269283658c002e470099f7ee7a58953aa/pkg/kv/kvclient/kvcoord/txn_test.go#L914)):*
> ```Go
> 	defer s.Stop()
> 
> 	ctx, cancel := context.WithCancel(context.Background())
> ```

nit: do we need the `WithCancel`?
___
*[pkg/kv/kvclient/kvcoord/txn_test.go, line 919 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/69096#-MmZ3fHs8Gr1pJZL2Bfm:-MmZ3fHs8Gr1pJZL2Bfn:bn9xc1a) ([raw file](https://github.com/cockroachdb/cockroach/blob/52b6e5f269283658c002e470099f7ee7a58953aa/pkg/kv/kvclient/kvcoord/txn_test.go#L919)):*
> ```Go
> 	bumpTsCache := func(delay time.Duration) {
> 		s.Manual.Increment(delay.Nanoseconds())
> 		// We make an unrelated put which advances ts cache as a side effect
> ```

nit: punctuation.
___
*[pkg/kv/kvclient/kvcoord/txn_test.go, line 920 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/69096#-MmZ0iNV9SfHkCvct7NC:-MmZ0iNV9SfHkCvct7ND:b-zazi54) ([raw file](https://github.com/cockroachdb/cockroach/blob/52b6e5f269283658c002e470099f7ee7a58953aa/pkg/kv/kvclient/kvcoord/txn_test.go#L920)):*
> ```Go
> 		s.Manual.Increment(delay.Nanoseconds())
> 		// We make an unrelated put which advances ts cache as a side effect
> 		require.NoError(t, s.DB.Put(ctx, roachpb.Key("z"), []byte{0}))
> ```

A write won't advance the timestamp cache, only a read will. I wonder whether this is why you were seeing different things with localtestcluster vs. the other test framework. I suspect that this is actually causing the closed timestamp to increase to hlc.Now() (which you manually increased). That's a fine test, but it's not quite the same thing and it's more indirect.

Consider replacing the clock update and the `Put` with a `Get`. But note that if you do that, the two will need to touch the same set of keys.

It's also very possible that the use of the term "ts cache" is throwing me and that what you have here is doing what you're intending. Let's discuss tomorrow.
___
*[pkg/kv/kvclient/kvcoord/txn_test.go, line 928 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/69096#-MmZ3QwlC2P4q-uHXA7c:-MmZ3QwlC2P4q-uHXA7d:b54a7ro) ([raw file](https://github.com/cockroachdb/cockroach/blob/52b6e5f269283658c002e470099f7ee7a58953aa/pkg/kv/kvclient/kvcoord/txn_test.go#L928)):*
> ```Go
> 		// Fixing transaction commit timestamp to disallow read refresh
> 		_ = txn.CommitTimestamp()
> 		delay := 1 * time.Second
> ```

Could we make these functions of `closedts.TargetDuration` so that this test doesn't break if someone changes that default?
___
*[pkg/kv/kvclient/kvcoord/txn_test.go, line 935 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/69096#-MmZ3hiRACN9vjbTt-Kp:-MmZ3hiRACN9vjbTt-Kq:b-t7orq) ([raw file](https://github.com/cockroachdb/cockroach/blob/52b6e5f269283658c002e470099f7ee7a58953aa/pkg/kv/kvclient/kvcoord/txn_test.go#L935)):*
> ```Go
> 		attempt++
> 		// Doing scan to populate txn read span
> 		_, _ = txn.Scan(ctx, roachpb.Key("a"), roachpb.Key("p"), 1000)
> ```

Check the error here.
___
*[pkg/roachpb/data.go, line 1466 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/69096#-MmQ4lQ98hbyBHU_0f-k:-MmZ-bWSDQksxiKkm30z:b-y9fotf) ([raw file](https://github.com/cockroachdb/cockroach/blob/6e2dde03d35f3c59f65d28f0ac5fd5bb52674dab/pkg/roachpb/data.go#L1466)):*
<details><summary><i>Previously, aliher1911 (Oleg) wrote…</i></summary><blockquote>

Can you elaborate about this? I thought we are specifically vulnerable here if timestamp is fixed, in general case I thought we can try to refresh span.
</blockquote></details>

We can try to refresh our read spans if we haven't fixed our commit timestamp, but that can fail! And under some workloads with sufficient read-write contention, that may always fail. So if bumping the txn's timestamp all the way up to now() on a epoch increment avoids the need for a refresh, it may be key in allowing a txn to commit.
___
*[pkg/roachpb/data.go, line 1471 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/69096#-MmQ4p77AjhRqpzzXswF:-MmZ0G4wAo390-FMWu7f:b-92rxkp) ([raw file](https://github.com/cockroachdb/cockroach/blob/6e2dde03d35f3c59f65d28f0ac5fd5bb52674dab/pkg/roachpb/data.go#L1471)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Waiting on locks or were slowed down in their first epoch for any other reason (e.g. lease transfers, network congestion, node failure, etc.).
</blockquote></details>

`s/locksor/locks or/`

**Review by nvb — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/69096#-:-MmxHF7l7u5HvzusAykJ:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @aliher1911)

___
*[pkg/kv/kvclient/kvcoord/txn_test.go, line 928 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/69096#-MmZ3QwlC2P4q-uHXA7c:-MmxGqCv-UHMsReGrxgB:bn3m660) ([raw file](https://github.com/cockroachdb/cockroach/blob/52b6e5f269283658c002e470099f7ee7a58953aa/pkg/kv/kvclient/kvcoord/txn_test.go#L928)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Could we make these functions of `closedts.TargetDuration` so that this test doesn't break if someone changes that default?
</blockquote></details>

Instead of using the default value, let's use the real value for this cluster. `closedts.TargetDuration.Get(&s.Cfg.Settings.SV)`.
___
*[pkg/kv/kvclient/kvcoord/txn_test.go, line 930 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/69096#-MmxHM2DAcduQ5w7M3eY:-MmxHM2DAcduQ5w7M3eZ:b-tir443) ([raw file](https://github.com/cockroachdb/cockroach/blob/955f1a4aecb777c871e961a2b9a57a1b51f8a6d2/pkg/kv/kvclient/kvcoord/txn_test.go#L930)):*
> ```Go
> 	require.NoError(t, s.DB.Txn(ctx, func(ctx context.Context, txn *kv.Txn) error {
> 		require.Less(t, attempt, 2, "Transaction can't recover after initial retry error, too many retries")
> 		// Fixing transaction commit timestamp to disallow read refresh
> ```

nit: add punctuation to each of these comments.
___
*[pkg/kv/kvclient/kvcoord/txn_test.go, line 938 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/69096#-MmxHRUJEES6GelVyF9L:-MmxHRUJEES6GelVyF9M:b-q14ux) ([raw file](https://github.com/cockroachdb/cockroach/blob/955f1a4aecb777c871e961a2b9a57a1b51f8a6d2/pkg/kv/kvclient/kvcoord/txn_test.go#L938)):*
> ```Go
> 		bumpClosedTimestamp(delay)
> 		attempt++
> 		// Doing scan to populate txn read span
> ```

Let's move `_ = txn.CommitTimestamp()` (and its comment) right above this comment. Then add to this comment:
```go
// Perform a scan to populate the transaction's read spans and mandate a refresh
// if the transaction's write timestamp is ever bumped. Because we fixed the
// transaction's commit timestamp, it will be forced to retry.
```
___
*[pkg/kv/kvclient/kvcoord/txn_test.go, line 941 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/69096#-MmxI3o5E4nA8YrOy_3k:-MmxI3o5E4nA8YrOy_3l:bc29ml9) ([raw file](https://github.com/cockroachdb/cockroach/blob/955f1a4aecb777c871e961a2b9a57a1b51f8a6d2/pkg/kv/kvclient/kvcoord/txn_test.go#L941)):*
> ```Go
> 		_, err := txn.Scan(ctx, roachpb.Key("a"), roachpb.Key("p"), 1000)
> 		require.NoError(t, err, "Failed Scan request")
> 		require.NoError(t, txn.Put(ctx, roachpb.Key("b"), []byte(fmt.Sprintf("value-%d", attempt))))
> ```

Let's add a comment here:
```go
// Perform a write, which will run into the closed timestamp and get pushed.
```

**Comment by aliher1911** [comment]
bors r=nvanbenschoten
