### PR TITLE
ugpradeccl: fix and unskip `TestTenantUpgradeFailure`

### LINKED ISSUE #98555: ccl/kvccl/kvtenantccl: TestTenantUpgradeFailure failed
ccl/kvccl/kvtenantccl.TestTenantUpgradeFailure [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_StressBazel/9051029?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_StressBazel/9051029?buildTab=artifacts#/) on master @ [4215b86090794a78649aa4463c7bf95d74c57c37](https://github.com/cockroachdb/cockroach/commits/4215b86090794a78649aa4463c7bf95d74c57c37):

```
=== RUN   TestTenantUpgradeFailure
    test_log_scope.go:161: test logs captured to: /artifacts/tmp/_tmp/16471d5fa37cec92efcb07e68ae77ada/logTestTenantUpgradeFailure1735758781
    test_log_scope.go:79: use -show-logs to present logs inline
=== CONT  TestTenantUpgradeFailure
    tenant_upgrade_test.go:366: -- test log scope end --
--- FAIL: TestTenantUpgradeFailure (2.76s)
=== RUN   TestTenantUpgradeFailure/upgrade_tenant_have_it_crash_then_resume
    tenant_upgrade_test.go:322: expected error '.*(database is closed|failed to connect|closed network connection)+', got: pq: migration-job-mark-job-succeeded: tenant-side-limiter pool closed: shutting down
    --- FAIL: TestTenantUpgradeFailure/upgrade_tenant_have_it_crash_then_resume (2.20s)
```
<p>Parameters: <code>TAGS=bazel,gss</code>
</p>
<details><summary>Help</summary>
<p>

See also: [How To Investigate a Go Test Failure \(internal\)](https://cockroachlabs.atlassian.net/l/c/HgfXfJgM)
</p>
</details>
/cc @cockroachdb/multi-tenant
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*TestTenantUpgradeFailure.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)
</sub>

Jira issue: CRDB-25327

### PR DESCRIPTION
**Pull request by healthy-pod**
The code change unskips `TestTenantUpgradeFailure` after making the following changes to fix it:
1. Bump `slinstance.DefaultTTL.Override` from 3s to 15s
2. Ensure v2 isn't higher than `TestingBinaryVersion`

It also updates the registry override to let the test run all migrations.

Release note: None
Epic: none

Closes #98555

### CODE REVIEW

File: pkg/ccl/kvccl/kvtenantccl/upgradeccl/tenant_upgrade_test.go [hunk 1]
```diff
@@ -195,15 +194,25 @@ func v0v1v2() (roachpb.Version, roachpb.Version, roachpb.Version) {
...
+	v2 := clusterversion.TestingBinaryVersion
+	// v1 needs to be between v0 and v2. Set it to the minor release
+	// after v0 and before v2.
+	var v1 roachpb.Version
+	for _, version := range clusterversion.ListBetween(v0, v2) {
+		if version.Minor != v0.Minor {
+			v1 = version
+			break
+		}
+	}
```
Comment (knz) [inline pkg/ccl/kvccl/kvtenantccl/upgradeccl/tenant_upgrade_test.go:214]: Can you add an assert that v1 was assigned, in case the loop above turned out empty.

**Review by knz — APPROVED** [review]
Cheers

**Comment by healthy-pod** [comment]
bors r=knz

**Comment by wenyihu6** [comment]
This still seems to be flaky - https://teamcity.cockroachdb.com/viewLog.html?buildId=10747857&buildTypeId=Cockroach_BazelEssentialCi
