### PR TITLE
roachtest: require libGEOS in tests that run schemachange

### LINKED ISSUE #119123: roachtest: backup-restore/round-trip failed
roachtest.backup-restore/round-trip [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/13975278?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/13975278?buildTab=artifacts#/backup-restore/round-trip) on master @ [814a375d4c0e79d875c42452725f05f6c27294e3](https://github.com/cockroachdb/cockroach/commits/814a375d4c0e79d875c42452725f05f6c27294e3):

```
(monitor.go:153).Wait: monitor failure: full command output in run_064507.182821543_n4_COCKROACHRANDOMSEED2.log: COMMAND_PROBLEM: exit status 1
test artifacts and logs in: /artifacts/backup-restore/round-trip/run_1
```

Parameters:
 - <code>ROACHTEST_arch=amd64</code>
 - <code>ROACHTEST_cloud=gce</code>
 - <code>ROACHTEST_coverageBuild=false</code>
 - <code>ROACHTEST_cpu=4</code>
 - <code>ROACHTEST_encrypted=false</code>
 - <code>ROACHTEST_metamorphicBuild=false</code>
 - <code>ROACHTEST_ssd=0</code>
<details><summary>Help</summary>
<p>

See: [roachtest README](https://github.com/cockroachdb/cockroach/blob/master/pkg/cmd/roachtest/README.md)

See: [How To Investigate \(internal\)](https://cockroachlabs.atlassian.net/l/c/SSSBr8c7)

See: [Grafana](https://go.crdb.dev/roachtest-grafana/teamcity-13975278/backup-restore-round-trip/1707806557173/1707809125108)

</p>
</details>
/cc @cockroachdb/disaster-recovery
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*backup-restore/round-trip.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)
</sub>

Jira issue: CRDB-36042

### LINKED ISSUE #119125: roachtest: backup-restore/small-ranges failed [cannot load GEOS from dir during schemachange workload]
roachtest.backup-restore/small-ranges [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/13975278?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/13975278?buildTab=artifacts#/backup-restore/small-ranges) on master @ [814a375d4c0e79d875c42452725f05f6c27294e3](https://github.com/cockroachdb/cockroach/commits/814a375d4c0e79d875c42452725f05f6c27294e3):

```
(monitor.go:153).Wait: monitor failure: full command output in run_064605.235807506_n4_COCKROACHRANDOMSEED8.log: COMMAND_PROBLEM: exit status 1
test artifacts and logs in: /artifacts/backup-restore/small-ranges/run_1
```

Parameters:
 - <code>ROACHTEST_arch=amd64</code>
 - <code>ROACHTEST_cloud=gce</code>
 - <code>ROACHTEST_coverageBuild=false</code>
 - <code>ROACHTEST_cpu=4</code>
 - <code>ROACHTEST_encrypted=false</code>
 - <code>ROACHTEST_metamorphicBuild=false</code>
 - <code>ROACHTEST_ssd=0</code>
<details><summary>Help</summary>
<p>

See: [roachtest README](https://github.com/cockroachdb/cockroach/blob/master/pkg/cmd/roachtest/README.md)

See: [How To Investigate \(internal\)](https://cockroachlabs.atlassian.net/l/c/SSSBr8c7)

See: [Grafana](https://go.crdb.dev/roachtest-grafana/teamcity-13975278/backup-restore-small-ranges/1707806596815/1707809925045)

</p>
</details>
<details><summary>Same failure on other branches</summary>
<p>

- #118350 roachtest: backup-restore/small-ranges failed [C-test-failure O-roachtest O-robot P-2 T-disaster-recovery branch-release-23.1]
</p>
</details>
/cc @cockroachdb/disaster-recovery
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*backup-restore/small-ranges.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)
</sub>

Jira issue: CRDB-36044

### PR DESCRIPTION
**Pull request by renatolabs**
The schemachange workload started performing statements that might require libGEOS to be present in the cluster. Several tests invoke that workload without indicating that they need lib GEOS. In this commit, we update tests in this situation.

Fixes: #119123
Fixes: #119125

Release note: None

### CODE REVIEW

**Review by srosenberg — APPROVED** [review]

**Review by rafiss — APPROVED** [review]
thank you!

**Review by herkolategan — APPROVED** [review]

File: build/teamcity/cockroach/ci/tests/local_roachtest_fips_impl.sh [hunk 1]
```diff
@@ -16,6 +16,11 @@ bazel build --config=$CROSSLINUX_CONFIG --config=ci //pkg/cmd/cockroach-short \
       //pkg/cmd/roachprod \
       //pkg/cmd/workload
 
+bazel build --config=$CROSSLINUX_CONFIG --config=ci --config=force_build_cdeps //c-deps:libgeos
+
+cp _bazel/bin/c-deps/libgeos_foreign/lib/libgeos.so lib/libgeos.so
```
Comment (rickystewart) [inline build/teamcity/cockroach/ci/tests/local_roachtest_fips_impl.sh:21]: Use `BAZEL_BIN` from below instead of hard-coding `_bazel/bin`. Also, you'll want to `chmod a+w` the libraries after copying them.

**Review by rickystewart — CHANGES_REQUESTED** [review]

File: build/teamcity/cockroach/ci/tests/local_roachtest_fips_impl.sh (hunk 1 above)
Comment (renatolabs) [reply build/teamcity/cockroach/ci/tests/local_roachtest_fips_impl.sh]: Thanks! Seems like it worked now, let me know if there's anything else I should be doing differently.

**Review by rickystewart — APPROVED** [review]

**Comment by renatolabs** [comment]
TFTRs!

bors r=srosenberg,rafiss,herkolategan,rickystewart
