### PR TITLE
kvserver: unskip lease preferences during outage 

### LINKED ISSUE #88769: kvserver: TestLeasePreferencesDuringOutage is flaky
Failures generally look like the following assertion error:

```        	Error Trace:	/home/roach/.cache/bazel/_bazel_roach/c5a4e7d36696d9cd970af2045211a7df/sandbox/processwrapper-sandbox/8248/execroot/com_github_cockroachdb_cockroach/bazel-out/k8-fastbuild/bin/pkg/kv/kvserver/kvserver_test_/kvserver_test.runfiles/com_github_cockroachdb_cockroach/pkg/kv/kvserver/client_lease_test.go:929
        	Error:      	Not equal: 
        	            	expected: 1
        	            	actual  : 5
        	Test:       	TestLeasePreferencesDuringOutage
```

Some failures in TC:
* https://teamcity.cockroachdb.com/viewLog.html?buildId=6634041&buildTypeId=Cockroach_UnitTests_BazelUnitTests
* https://teamcity.cockroachdb.com/viewLog.html?buildId=6609152&buildTypeId=Cockroach_UnitTests_BazelUnitTests&tab=buildResultsDiv
* https://teamcity.cockroachdb.com/viewLog.html?buildId=6632206&tab=buildResultsDiv&buildTypeId=Cockroach_UnitTests_BazelUnitTests#testNameId-4172107706173416798

I was also able to see a failure in under 10 minutes using:

```
./dev test ./pkg/kv/kvserver/ -f TestLeasePreferencesDuringOutage --stress --timeout 10m --ignore-cache
```

Jira issue: CRDB-20009

### PR DESCRIPTION
**Pull request by kvoli**
Previously, `TestLeasePreferenceDuringOutage` would force replication
queue processing of the test range, then assert that the range
up-replicated and lease transferred to a preferred locality.

This test was skipped, and two of the assumptions it relied on to pass
were no longer true.

After https://github.com/cockroachdb/cockroach/pull/85219, the replicate queue no longer
re-processes replicas. Instead, the queue requeues replicas after
processing, at the appropriate priority. This broke the test due to the
replicate queue being disabled, making the re-queue a no-op.

After https://github.com/cockroachdb/cockroach/pull/94023, the replicate queue no longer looked for lease transfers,
after processing a replication action. Combined with https://github.com/cockroachdb/cockroach/pull/85219, the queue
would now be guaranteed to not process both up-replication and lease
transfers from a single enqueue.

Update the test to not require a manual process, instead using a queue
range filter, which allows tests which disable automatic replication, to
still process filtered ranges via the various replica queues. Also,
ensure that the non-stopped stores are considered live targets, after
simulating an outage (bumping manual clocks, stopping servers) -- so
that the expected up-replication, then lease transfer can proceed.

Fixes: https://github.com/cockroachdb/cockroach/issues/88769
Release note: None

### CODE REVIEW

File: pkg/kv/kvserver/client_lease_test.go [hunk 1]
```diff
@@ -1040,55 +1067,44 @@ func TestLeasePreferencesDuringOutage(t *testing.T) {
...
-	}
-	lastMove++
-	var leasesMsg []string
-	for _, h := range history {
-		leasesMsg = append(leasesMsg, h.String())
-	}
-	leaseHistory := strings.Join(leasesMsg, ", ")
-	require.Greater(t, lastMove, 0,
-		"must have at least one leaseholder change in history (lease history: %s)", leaseHistory)
-	require.Equal(t, tc.Target(0).NodeID, history[lastMove-1].Replica.NodeID,
```
Comment (kvoli) [inline pkg/kv/kvserver/client_lease_test.go:1090]: It wasn't guaranteed that the last leaseholder would be n1. Another node could very well have acquired the lease last, e.g., n2 (as it was stopped), before another node acquired the lease.

**Comment by kvoli** [comment]
This passes 5/5k stresses locally, yet fails reliably on CI. I'm investigating further.

**Comment by kvoli** [comment]
`dev test pkg/kv/kvserver -f TestLeasePreferencesDuringOutage -v --stress --count=1000 --cpus=8` passes, CI is still flaky. I'm thinking that this test may be failing due to CPU contention mostly.

**Comment by kvoli** [comment]
Friendly ping @andrewbaptist, I know you're tied up with bigger fish atm.

**Comment by andrewbaptist** [comment]
Sorry for the delay - I missed reviewing this one. I don't love the solution here though as it is fairly convoluted to reason about whether the range will be processed or not. (Also this would have been a good one to see @aadityasondhi way as he just worked on the disabling of queues). The concern I have is that it is like a "double-negative" to determine if a range will be processed. 

I could see a few more elegant solutions if you feel like implementing them.
1) Add a configurable parameter "ValidRangesToProcess" to the queue. Then leave the queue enabled for this test, but restrict the ranges to the ranges for the ranges we care about. This could be a useful mechanism for support cases as well and could apply to all queues. The default would be the `keys.EverythingSpan`

2) Change the disable flag to a disable func. The default func would return the value of queueConfig.disabledConfig, but it could be overridden in tests to have more complex behavior like this test requires.

3) Change the test to just submit this to the queue in a look rather than just 1 time until it succeeds. I'm not sure if this is possible, but would probably be the simplest.

I like the first one the best as I could see us using it in a lot of tests that want to see queue behavior on a specific range. Let me know what you think.

**Comment by kvoli** [comment]
> Sorry for the delay - I missed reviewing this one. I don't love the solution here though as it is fairly convoluted to reason about whether the range will be processed or not. 

I don't think this is convoluted, but perhaps I'm missing something. For testing, this and other tests use `ReplicationManual`, which will disable the queue via testing knobs.

https://github.com/cockroachdb/cockroach/blob/3e9b7de0255f64222c9cd6e8e8d7590405e2ab1c/pkg/kv/kvserver/store.go#L1600-L1602

There's a bit of machinery which validates this in the test cluster setup, and disallows running commands unless `ReplicationManual` is enabled like Split/AddVoter etc

https://github.com/cockroachdb/cockroach/blob/dc2c52da339a49405815860cbed511d364b7e146/pkg/testutils/testcluster/testcluster.go#L1877-L1879

I think keeping `ReplicationManual` is valuable. We could change the instrumentation underneath to do something similar to what you're suggesting. However, we would also want to enable a way to interact with the queue valid key spans via SQL. I don't think this is an investment we should make right now.

> Change the disable flag to a disable func. The default func would return the value of queueConfig.disabledConfig, but it could be overridden in tests to have more complex behavior like this test requires.

This idea seems reasonable, however it doesn't appear materially different from what is done here. The disabled flag is set not only by the cluster setting, but can also be set by calling `SetXQueueDisabled`, which some tests do explicitly. In order to add this function, we would need to maintain the disabled variable, the filter function and refer to the queue config on init and changes. 

> Change the test to just submit this to the queue in a look rather than just 1 time until it succeeds. I'm not sure if this is possible, but would probably be the simplest.

The replica won't be re-queued if the queue is disabled. It will hit this path:

https://github.com/cockroachdb/cockroach/blob/3e9b7de0255f64222c9cd6e8e8d7590405e2ab1c/pkg/kv/kvserver/queue.go#L657-L663

**Comment by kvoli** [comment]
Not fully deflaked here clearly, the extended CI is failing on this test. I can't reproduce it locally but I'll take another look.

**Review by andrewbaptist — APPROVED** [review]
This generally looks good. As mentioned the `BaseQueueDisabledBypassFilter` still feels like a double negative, but OK since it makes sense why you had to do this. 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/108175#-:-Ndb4TvP5joa1QEaojTp:bou1ewd)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @kvoli)

___
*[`pkg/kv/kvserver/queue.go` line 667 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/108175#-Ndax0pjB9fCW92kxv0N:-Ndax0pjB9fCW92kxv0O:blm2wsn) ([raw file](https://github.com/cockroachdb/cockroach/blob/62f0fb612e414a82a700385a74940572ce353611/pkg/kv/kvserver/queue.go#L667)):*
> ```Go
> 
> 	if disabled {
> 		// The disabed queue bypass is used when in tests which enable manual
> ```

nit: when in tests -> in tests
___
*[`pkg/kv/kvserver/queue.go` line 668 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/108175#-NdaxFGr2zmr0MEqIB66:-NdaxFGr2zmr0MEqIB67:bve70cv) ([raw file](https://github.com/cockroachdb/cockroach/blob/62f0fb612e414a82a700385a74940572ce353611/pkg/kv/kvserver/queue.go#L668)):*
> ```Go
> 	if disabled {
> 		// The disabed queue bypass is used when in tests which enable manual
> 		// replication, however still need to assert on specific range(s)
> ```

nit: Change this comment to something like "still need the specific ranges to be processed by the queue". This is more clear than talking about asserting.
___
*[`pkg/kv/kvserver/queue.go` line 743 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/108175#-Ndax71o-rI2opQNLz6C:-Ndax71pEYFqgBjI1ztn:bi99ju7) ([raw file](https://github.com/cockroachdb/cockroach/blob/62f0fb612e414a82a700385a74940572ce353611/pkg/kv/kvserver/queue.go#L743)):*
> ```Go
> 
> 	if bq.mu.disabled {
> 		// The disabed queue bypass is used when in tests which enable manual
> ```

nit: Same as above
___
*[`pkg/kv/kvserver/client_lease_test.go` line 925 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/108175#-Ndb27az84GtXOJeXlUs:-Ndb27az84GtXOJeXlUt:b-tqkvil) ([raw file](https://github.com/cockroachdb/cockroach/blob/62f0fb612e414a82a700385a74940572ce353611/pkg/kv/kvserver/client_lease_test.go#L925)):*
> ```Go
> 
> 	// This is a hefty test, so we skip it under short, race and deadlock.
> 	skip.UnderShort(t)
> ```

nit: I'm confused as to why this test needs to be skipped under all these conditions.  It isn't writing or moving a lot of data around.  Does it take a long time to run because we are waiting for the replicate_queue or stores to start/stop, or because we have 5 nodes or because we wait for them to be available after restarting? I think skipping under short makes sense, but probably not under deadlock or race.
___
*[`pkg/kv/kvserver/client_lease_test.go` line 972 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/108175#-Ndb-2nk5Irxj99oy3sd:-Ndb-2nk5Irxj99oy3se:b-3q1oha) ([raw file](https://github.com/cockroachdb/cockroach/blob/62f0fb612e414a82a700385a74940572ce353611/pkg/kv/kvserver/client_lease_test.go#L972)):*
> ```Go
> 	sv := &settings.SV
> 	kvserver.TransferExpirationLeasesFirstEnabled.Override(ctx, sv, false)
> 	kvserver.ExpirationLeasesOnly.Override(ctx, sv, false)
> ```

nit: Not part of this PR, but it would be nice to remove the two settings `TransferExpirationLeasesFirstEnabled` and `ExpirationLeasesOnly`. The first fundamentally changes how leases are transferred and can mean that the test will work differently, especially with regard to how the replicate queue and raft process loop interact. Since we are now allowing multiple passes through the replicate queue and have a success soon, I don't think this is still necessary to set.
___
*[`pkg/kv/kvserver/client_lease_test.go` line 978 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/108175#-Ndb066qB4yHG1qK72LN:-Ndb066qB4yHG1qK72LO:bd4j0bi) ([raw file](https://github.com/cockroachdb/cockroach/blob/62f0fb612e414a82a700385a74940572ce353611/pkg/kv/kvserver/client_lease_test.go#L978)):*
> ```Go
> 	// become suspect due to manual clock jumps. Disable the suspect timer to
> 	// prevent them becoming suspect when we bump the clocks.
> 	storepool.FailedReservationsTimeout.Override(ctx, sv, 0)
> ```

Do you understand why we are getting snapshot reservation failures? I wouldn't expect it in this test, but it could be due to three different things:
1) Delegated snapshot checks - if so we should probably fix the check to not fail here
2) SnapshotSend/ApplyLimit - if so it would be better to remove these limits. 
3) Suspect store (next line) - store unexpectedly becoming suspect (other than from shutdown). If so then we shouldn't need this if we are setting the TimeAfterNodeSuspect setting 

Nothing to prevent this from merging, but more curious if there is something more subtle going on here.
___
*[`pkg/kv/kvserver/client_lease_test.go` line 1092 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/108175#-Ndaz47J2PKmy4RXEM71:-Ndaz47J2PKmy4RXEM72:b-3i1wfc) ([raw file](https://github.com/cockroachdb/cockroach/blob/62f0fb612e414a82a700385a74940572ce353611/pkg/kv/kvserver/client_lease_test.go#L1092)):*
> ```Go
> 			dc, ok := servLocality.Find("dc")
> 			require.True(t, ok)
> 			if dc == "sf" {
> ```

nit: Use require.NotEqualf ?

**Review by kvoli — COMMENTED** [review]
TYFTR - I'll hold off merging until I have an conclusive answer on the snapshot throttle and skip under deadlock/race questions you had.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/108175#-:-NdetualE_rL77RqTcWp:b-jeb1mz)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andrewbaptist and @kvoli)

___
*[`pkg/kv/kvserver/queue.go` line 667 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/108175#-Ndax0pjB9fCW92kxv0N:-NdegDdtDBJT5e1v-rp5:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/62f0fb612e414a82a700385a74940572ce353611/pkg/kv/kvserver/queue.go#L667)):*
<details><summary><i>Previously, andrewbaptist (Andrew Baptist) wrote…</i></summary><blockquote>

nit: when in tests -> in tests
</blockquote></details>

Done.
___
*[`pkg/kv/kvserver/queue.go` line 668 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/108175#-NdaxFGr2zmr0MEqIB66:-NdegTv_33-7K2w6ocPF:bp1n58p) ([raw file](https://github.com/cockroachdb/cockroach/blob/62f0fb612e414a82a700385a74940572ce353611/pkg/kv/kvserver/queue.go#L668)):*
<details><summary><i>Previously, andrewbaptist (Andrew Baptist) wrote…</i></summary><blockquote>

nit: Change this comment to something like "still need the specific ranges to be processed by the queue". This is more clear than talking about asserting.
</blockquote></details>

Good suggestion, updated.
___
*[`pkg/kv/kvserver/queue.go` line 743 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/108175#-Ndax71o-rI2opQNLz6C:-NdegXnE31CCSD1yS5ES:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/62f0fb612e414a82a700385a74940572ce353611/pkg/kv/kvserver/queue.go#L743)):*
<details><summary><i>Previously, andrewbaptist (Andrew Baptist) wrote…</i></summary><blockquote>

nit: Same as above
</blockquote></details>

Done.
___
*[`pkg/kv/kvserver/client_lease_test.go` line 925 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/108175#-Ndb27az84GtXOJeXlUs:-NdeoicX3M4LN9etVEAX:bw2ca14) ([raw file](https://github.com/cockroachdb/cockroach/blob/62f0fb612e414a82a700385a74940572ce353611/pkg/kv/kvserver/client_lease_test.go#L925)):*
<details><summary><i>Previously, andrewbaptist (Andrew Baptist) wrote…</i></summary><blockquote>

nit: I'm confused as to why this test needs to be skipped under all these conditions.  It isn't writing or moving a lot of data around.  Does it take a long time to run because we are waiting for the replicate_queue or stores to start/stop, or because we have 5 nodes or because we wait for them to be available after restarting? I think skipping under short makes sense, but probably not under deadlock or race.
</blockquote></details>

Its a fair point. I'm double checking that skipping under deadlock/race is necessary now.
___
*[`pkg/kv/kvserver/client_lease_test.go` line 972 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/108175#-Ndb-2nk5Irxj99oy3sd:-NdelHqLD5B5Q8ahBreR:bqomyw4) ([raw file](https://github.com/cockroachdb/cockroach/blob/62f0fb612e414a82a700385a74940572ce353611/pkg/kv/kvserver/client_lease_test.go#L972)):*
<details><summary><i>Previously, andrewbaptist (Andrew Baptist) wrote…</i></summary><blockquote>

nit: Not part of this PR, but it would be nice to remove the two settings `TransferExpirationLeasesFirstEnabled` and `ExpirationLeasesOnly`. The first fundamentally changes how leases are transferred and can mean that the test will work differently, especially with regard to how the replicate queue and raft process loop interact. Since we are now allowing multiple passes through the replicate queue and have a success soon, I don't think this is still necessary to set.
</blockquote></details>

Good idea, these were added for backports to 22.2. The rationale was that a dead node could acquire the lease, and subsequently force waiting out the expiration. 

I've removed both these settings.
___
*[`pkg/kv/kvserver/client_lease_test.go` line 978 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/108175#-Ndb066qB4yHG1qK72LN:-NdetVBB01DRMiLBpkU3:b2gt4mk) ([raw file](https://github.com/cockroachdb/cockroach/blob/62f0fb612e414a82a700385a74940572ce353611/pkg/kv/kvserver/client_lease_test.go#L978)):*
<details><summary><i>Previously, andrewbaptist (Andrew Baptist) wrote…</i></summary><blockquote>

Do you understand why we are getting snapshot reservation failures? I wouldn't expect it in this test, but it could be due to three different things:
1) Delegated snapshot checks - if so we should probably fix the check to not fail here
2) SnapshotSend/ApplyLimit - if so it would be better to remove these limits. 
3) Suspect store (next line) - store unexpectedly becoming suspect (other than from shutdown). If so then we shouldn't need this if we are setting the TimeAfterNodeSuspect setting 

Nothing to prevent this from merging, but more curious if there is something more subtle going on here.
</blockquote></details>

I'm going to remove the failed reservation timeout override and check for flakes. 

I saw reservation timeouts and subsequent throttling, however didn't dig into the root cause as you suggest. I'll see how this looks with the override removed.
___
*[`pkg/kv/kvserver/client_lease_test.go` line 1092 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/108175#-Ndaz47J2PKmy4RXEM71:-NdehJ4UAzeFgiPrr_8T:bqldz3g) ([raw file](https://github.com/cockroachdb/cockroach/blob/62f0fb612e414a82a700385a74940572ce353611/pkg/kv/kvserver/client_lease_test.go#L1092)):*
<details><summary><i>Previously, andrewbaptist (Andrew Baptist) wrote…</i></summary><blockquote>

nit: Use require.NotEqualf ?
</blockquote></details>

This is in a `testutils.SucceedsSoon` -- adding a `require.NotEqualf(...)` would cause the test to fail if the dc were ever `sf`, rather than retry and expect it to succeed soon.

**Review by kvoli — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/108175)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andrewbaptist and @kvoli)

___
*[`pkg/kv/kvserver/client_lease_test.go` line 925 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/108175#-Ndb27az84GtXOJeXlUs:-NdjofAQB3vjZMo73N1h:b-5str6n) ([raw file](https://github.com/cockroachdb/cockroach/blob/62f0fb612e414a82a700385a74940572ce353611/pkg/kv/kvserver/client_lease_test.go#L925)):*
<details><summary><i>Previously, kvoli (Austen) wrote…</i></summary><blockquote>

Its a fair point. I'm double checking that skipping under deadlock/race is necessary now.
</blockquote></details>

Skipping under deadlock is not necessary, however skipping under stressrace seems necessary. The manual liveness heartbeats can timeout, which fails the test because we require no error.  I don't think its worth pushing these into a retry loop, if they fail its a testing problem.

I removed skip under race and deadlock.
___
*[`pkg/kv/kvserver/client_lease_test.go` line 978 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/108175#-Ndb066qB4yHG1qK72LN:-NdjoU6o1OjoF7Ts4iu4:bweh1uu) ([raw file](https://github.com/cockroachdb/cockroach/blob/62f0fb612e414a82a700385a74940572ce353611/pkg/kv/kvserver/client_lease_test.go#L978)):*
<details><summary><i>Previously, kvoli (Austen) wrote…</i></summary><blockquote>

I'm going to remove the failed reservation timeout override and check for flakes. 

I saw reservation timeouts and subsequent throttling, however didn't dig into the root cause as you suggest. I'll see how this looks with the override removed.
</blockquote></details>

I did not see any snapshot timeouts when I re-stressed the test. I removed the snapshot reservation timeout override as it isn't necessary.

**Comment by kvoli** [comment]
bors r=andrewbaptist

**Comment by kvoli** [comment]
I've tried to reproduce the failure I saw on CI for a few hours without luck. The problem from the CI logs, is that the replicate queue doesn't re-process the replica after up-replicating (we kill n2 and n3).

```
dev test pkg/kv/kvserver -f TestLeasePreferencesDuringOutage -v --stress --cpus=40 -- --define -gotags=bazel,gss,deadlock
```

Note this is stressing with more CPUs than are available (24), which has shaken out problems here in the past.

As for why it doesn't re-process, I'm not sure. I don't see any reason why it wouldn't. The possible scenarios that it wouldn't are:
1. target is suspect  -- suspect timer disabled [here](https://github.com/kvoli/cockroach/blob/65bc225c96f83b3371fdae63bbb99d50c7c84c57/pkg/kv/kvserver/client_lease_test.go#L980-L980), so shouldn't be possible.
2. target is throttled -- no indication in the logs, this would be logged [here](https://github.com/kvoli/cockroach/blob/65bc225c96f83b3371fdae63bbb99d50c7c84c57/pkg/kv/kvserver/replicate_queue.go#L683-L683).
3. Queue ended with an error (not purgatory err) -- no indication in the logs, this would be logged [here](https://github.com/kvoli/cockroach/blob/65bc225c96f83b3371fdae63bbb99d50c7c84c57/pkg/kv/kvserver/replicate_queue.go#L704-L704)


So I think there's something I'm missing here. In any case, I'm going to see how the PR CI run goes.

**Comment by kvoli** [comment]
I finally got this deflaked properly I think. The changes I made from when the PR was approved:

1. Prevent queue processing until the supposed to be live nodes, are considered live from n1. This was causing flakiness, the test bumps the clocks and this causes n1 to temporarily consider nodes unavailable.
2. Assert that the leaseholder is not n1, instead of asserting that there is a valid leaseholder in 'us'. n1 acquires the lease, up-replicates and then transfers away the lease. After this, it is possible for the lease to not be valid, or for `FindRangeLeaseHolder` to incorrectly think `n1` is still the leaseholder, despite it not being so. This is documented on the fn.

**Comment by kvoli** [comment]
ExtendedCI is failing due to timeout on an unrelated test: `TestStoreRangeMergeWithData`. The flake is from liveness being merged away and re-split #104195:

```
initiating a merge of r66:â€¹/System{\x00aaa-testing\x00\x00-/NodeLiveness}â€º [(n1,s1):1, next=2, gen=2, sticky=9223372036.854775807,2147483647] into this range (â€¹manualâ€º)
```

I think this got tested under `race` because of changes touching the replicate queue. In any case, I'm going to merge this PR. The issue is tracked under #104195.

**Comment by kvoli** [comment]
bors r=andrewbaptist

**Comment by kvoli** [comment]
The merge queue is disbaled in this test, however it does appear that liveness has been merged away. I'm going to investigate further before merging just in case this is related to the testing filter.

bors r-

**Comment by kvoli** [comment]
bors r=andrewbaptist
