### PR TITLE
obs/ash: fix tenant isolation for ASH virtual tables in shared-process mode

### LINKED ISSUE #166456: obs/ash: tenant isolation broken for ASH virtual tables in shared-process mode
**Describe the problem**

In shared-process multi-tenant mode, the ASH (Active Session History) virtual tables
`crdb_internal.node_active_session_history` and `crdb_internal.cluster_active_session_history`
do not enforce tenant isolation. A secondary tenant can see ASH samples belonging to other
tenants and the system tenant.

The root cause is that the virtual table populate functions in `pkg/sql/crdb_internal.go`
call `ListLocalActiveSessionHistory` / `ListActiveSessionHistory` without setting the
tenant context on the `ctx`. Those RPC handlers rely on `roachpb.ClientTenantFromContext(ctx)`
to determine which tenant is querying and filter samples accordingly. That context value
is normally set by the gRPC authentication interceptor in `pkg/rpc/auth.go`, but in
shared-process mode the call is in-process (not gRPC), so the interceptor never runs and
`ClientTenantFromContext` returns `ok=false`. This makes `filterByTenant = false`,
causing the handler to return all samples unfiltered.

**To Reproduce**

1. Start a CockroachDB server with `DefaultTestTenant: base.TestControlsTenantsExplicitly`
2. Enable ASH: `SET CLUSTER SETTING obs.ash.enabled = true`
3. Start two shared-process tenants (e.g. tenant IDs 10 and 11)
4. Generate work on both tenants with distinct `application_name` values
5. From tenant 10, query `SELECT * FROM crdb_internal.node_active_session_history`
6. Observe that samples with `tenant_id = 11` (and the other tenant's `app_name`) are visible

**Expected behavior**

Each secondary tenant should only see ASH samples matching its own `tenant_id`. The system
tenant should see all samples. This is the documented behavior in the code comments on
`ListLocalActiveSessionHistory`.

**Additional data / screenshots**

The fix is to propagate the planner's tenant ID into the context before calling the handler:

```go
// pkg/sql/crdb_internal.go — node_active_session_history populate function
ashCtx := roachpb.ContextWithClientTenant(ctx, p.extendedEvalCtx.Codec.TenantID)
response, err := p.extendedEvalCtx.SQLStatusServer.ListLocalActiveSessionHistory(
    ashCtx, &serverpb.ListActiveSessionHistoryRequest{},
)
```

The same fix is needed for the `cluster_active_session_history` populate function.

**Environment:**
 - CockroachDB version: master (post-ASH merge)
 - Affects: shared-process multi-tenant deployments only

**Additional context**

This does not affect separate-process tenants (each has its own sampler and ring buffer).
It only affects shared-process tenants where all tenants share a single process-wide
ASH ring buffer and rely on `ListLocalActiveSessionHistory` for tenant filtering.

No other virtual table is affected because ASH is the only one that uses
`ClientTenantFromContext` for tenant-level sample filtering in the RPC handler. Other
tables (sessions, contention events) either don't have tenant metadata or filter by
user identity instead.

Jira issue: CRDB-61923

### PR DESCRIPTION
**Pull request by alyshanjahani-crl**
The ASH virtual table populate functions in crdb_internal.go called ListLocalActiveSessionHistory and ListActiveSessionHistory without propagating the planner's tenant ID into the context. Those handlers rely on roachpb.ClientTenantFromContext to determine the requesting tenant and filter samples accordingly. That context value is normally set by the gRPC auth interceptor, but in shared-process mode the call is in-process so the interceptor never runs, causing filterByTenant to be false and returning all tenants' samples unfiltered.

Fix by wrapping the context with roachpb.ContextWithClientTenant using the planner's Codec.TenantID before calling the handler. This ensures secondary tenants only see their own ASH samples while the system tenant continues to see all samples.

Also add TestASHMultiTenantIsolation which starts two shared-process tenants, generates work on each, and verifies that each tenant only sees its own tenant_id in crdb_internal.node_active_session_history.

Fixes #166456
Release note: None

### CODE REVIEW

File: pkg/server/ash_test.go [hunk 1]
```diff
@@ -0,0 +1,174 @@
...
+		t2Rows := tenant2SQL.QueryStr(t, `
+			SELECT DISTINCT tenant_id
+			FROM crdb_internal.node_active_session_history`)
+		for _, row := range t2Rows {
+			require.Equal(t, fmt.Sprint(tenant2ID.ToUint64()), row[0],
+				"tenant 2 should only see its own tenant_id")
+		}
+	})
+
+	t.Run("tenants cannot see each other app_names", func(t *testing.T) {
```
Comment (dhartunian) [inline pkg/server/ash_test.go]: nit: "others"

File: pkg/server/ash_test.go [hunk 2]
```diff
@@ -0,0 +1,174 @@
...
+		var crossCount int
+		tenant1SQL.QueryRow(t, `
```
Comment (dhartunian) [inline pkg/server/ash_test.go:129]: nit: might be nice to make these tests like the ones above: check that unique app name is `tenant_one_app`, otherwise this test can succeed if you just write nothing.

**Review by dhartunian — APPROVED** [review]
LGTM; just a testing nit.

**Comment by alyshanjahani-crl** [comment]
TFTR!
