### PR TITLE
backupccl: fix bug in resolving encrypted backup manifests

### LINKED ISSUE #91886: backupccl: encrypted restore of an incremental backup fails
```
root@localhost:26257/defaultdb> backup into 'nodelocal://1/full' WITH incremental_location='nodelocal://1/incremental', encryption_passphrase='123';
        job_id       |  status   | fraction_completed | rows | index_entries | bytes
---------------------+-----------+--------------------+------+---------------+--------
  813950484531609601 | succeeded |                  1 |   25 |             6 |  1740
(1 row)


Time: 352ms total (execution 351ms / network 0ms)

root@localhost:26257/defaultdb> backup into latest in 'nodelocal://1/full' WITH incremental_location='nodelocal://1/incremental', encryption_passphrase='123';
        job_id       |  status   | fraction_completed | rows | index_entries | bytes
---------------------+-----------+--------------------+------+---------------+--------
  813950540301697025 | succeeded |                  1 |    0 |             0 |     0
(1 row)


Time: 165ms total (execution 164ms / network 0ms)

root@localhost:26257/defaultdb> restore from latest in 'nodelocal://1/full' WITH incremental_location='nodelocal://1/incremental', encryption_passphrase='123';
ERROR: could not find or read encryption information: no ENCRYPTION-INFO files found
```

The regression was introduced in https://github.com/cockroachdb/cockroach/pull/87311 and backported to 22.2 as well.

Jira issue: CRDB-21468

### PR DESCRIPTION
**Pull request by adityamaru**
In #87311 we refactored `ResolveBackupManifests` to concurrently load manifests from base and incremental layers by calling `FetchPreviousBackups`. The mistake in that diff was to pass in only the incremental layers of the backup to `FetchPreviousBackup` instead of passing in the base backup + incremental layers. This was silently passing all tests because in `ResolveBackupManifests` we explicitly setup the base backup layer in all the relevant slices before processing each incremental layer. The one case this was not okay in was encrypted backups. `FetchPreviousBackups` apart from doing the obvious would also read the encryption options from the base backups before reading the manifests from each layer. Now, because we stopped sending the base backup in the input slice, this step would fail since the method would go to the first incremental backup (instead of the base backup) and attempt to read the ENCRYPTION_INFO file. This file is only ever written to the base backup and so a `SHOW BACKUP` or a `RESTORE` of an encrypted backup would fail with a file not found error.

In this diff we:

1) Fix `ResolveBackupManifests` by passing in the base backup + incremental backups to `FetchPreviousBackups`.

2) Make it the callers responsibility to pass in the fully hydrated encryption options before calling `FetchPreviousBackups` so that the method is *only* fetching backup manifests.

Fixes: #91886

Release note (bug fix): fixes a bug that would cause `SHOW BACKUP` and `RESTORE` of encrypted incremental backups to fail

### CODE REVIEW

File: pkg/ccl/backupccl/backupinfo/manifest_handling.go [hunk 1]
```diff
@@ -1299,37 +1299,31 @@ func NewTimestampedCheckpointFileName() string {
 }
 
 // FetchPreviousBackups takes a list of URIs of previous backups and returns
-// their manifest as well as the encryption options of the first backup in the
-// chain.
+// their manifests. The caller is expected to pass in the fully hydrated
+// encryptionParams required to read the manifests.
 func FetchPreviousBackups(
```
Comment (adityamaru) [inline pkg/ccl/backupccl/backupinfo/manifest_handling.go:1304]: I question the need for this method anymore but wanted to keep the diff small, let me know if you'd rather i rip it out and export `GetBackupManifests`.

File: pkg/ccl/backupccl/backupdest/backup_destination.go [hunk 2]
```diff
@@ -571,43 +573,37 @@ func ResolveBackupManifests(
...
 		// Load the default backup manifests for each backup layer, this is done
 		// concurrently.
-		enc := jobspb.BackupEncryptionOptions{
-			Mode: jobspb.EncryptionMode_None,
-		}
-		if encryption != nil {
-			enc = *encryption
-		}
-		defaultManifestsForEachLayer, _, memSize, err := backupinfo.FetchPreviousBackups(ctx, mem, user,
-			mkStore, defaultURIs[1:], enc, kmsEnv)
```
Comment (adityamaru) [inline pkg/ccl/backupccl/backupdest/backup_destination.go:596]: This was the main bug.

File: pkg/ccl/backupccl/backup_job.go [hunk 3]
```diff
@@ -800,15 +800,27 @@ func getBackupDetailAndManifest(
...
+		var memSize int64
+		prevBackups, memSize, err = backupinfo.FetchPreviousBackups(ctx, &mem, user,
+			makeCloudStorage, backupDestination.PrevBackupURIs, baseEncryptionOptions, &kmsEnv)
+
+		if err != nil {
+			return jobspb.BackupDetails{}, backuppb.BackupManifest{}, err
+		}
+		defer func() {
+			mem.Shrink(ctx, memSize)
+		}()
```
Comment (stevendanna) [inline pkg/ccl/backupccl/backup_job.go:822]: [nit] Can't this be `defer mem.Shrink(ctx, memSize)`

File: pkg/ccl/backupccl/backupinfo/manifest_handling.go (hunk 1 above)
Comment (stevendanna) [reply pkg/ccl/backupccl/backupinfo/manifest_handling.go:1304]: Given that they only differ by a tracing span now, I think we should rip one of them out.  We are also updating the only call site of this function, so hopefully the diff isn't affected too much.

**Review by stevendanna — APPROVED** [review]
This looks reasonable to me.  We really need some tests here.

File: pkg/ccl/backupccl/backup_job.go (hunk 3 above)
Comment (adityamaru) [reply pkg/ccl/backupccl/backup_job.go:822]: yup, fixed.

**Review by stevendanna — APPROVED** [review]
Thanks for adding the test!

**Comment by adityamaru** [comment]
blathers backport release-22.2

**Comment by adityamaru** [comment]
TFTR!

bors r=stevendanna
