### PR TITLE
restore: skip dropped/missing descriptors during restore revert

### LINKED ISSUE #165789: roachtest: backup-restore/online-restore-recovery failed
roachtest.backup-restore/online-restore-recovery [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/21253314?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/21253314?buildTab=artifacts#/backup-restore/online-restore-recovery) on release-26.1 @ [f2b553086cb15bb7d2c2903d12051e878e47084c](https://github.com/cockroachdb/cockroach/commits/f2b553086cb15bb7d2c2903d12051e878e47084c):

Failed with:

```
(monitor.go:267).Wait: monitor failure: waiting for download job 1158301892110778371 to reach failed state: job 1158301892110778371 still in state reverting after 10m0s
test artifacts and logs in: /artifacts/backup-restore/online-restore-recovery/run_1
```
Cluster Node to Ip Mapping:
| Node | Public IP | Private IP |
| --- | --- | --- |
| teamcity-21253314-1773555109-12-n4cpu4-0001 | 34.139.63.153 | 10.142.2.118 |
| teamcity-21253314-1773555109-12-n4cpu4-0002 | 35.229.31.13 | 10.142.2.119 |
| teamcity-21253314-1773555109-12-n4cpu4-0003 | 34.26.43.139 | 10.142.2.127 |
| teamcity-21253314-1773555109-12-n4cpu4-0004 | 35.196.186.129 | 10.142.2.169 |

Parameters:
 - <code>arch=amd64</code>
 - <code>cloud=gce</code>
 - <code>coverageBuild=false</code>
 - <code>cpu=4</code>
 - <code>diskCount=0</code>
 - <code>encrypted=false</code>
 - <code>fs=ext4</code>
 - <code>localSSD=true</code>
 - <code>runtimeAssertionsBuild=false</code>
<details><summary>Help</summary>
<p>

See: [roachtest README](https://github.com/cockroachdb/cockroach/blob/master/pkg/cmd/roachtest/README.md)

See: [How To Investigate \(internal\)](https://cockroachlabs.atlassian.net/l/c/SSSBr8c7)

See: [Grafana](https://go.crdb.dev/roachtest-grafana/teamcity-21253314/backup-restore-online-restore-recovery/1773555330100/1773556900270)

</p>
</details>
/cc @cockroachdb/disaster-recovery
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*backup-restore/online-restore-recovery.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/bazci/githubpost/issues)

</sub>

Jira issue: CRDB-61592

### PR DESCRIPTION
**Pull request by kev-cao**
Previously, if a user dropped descriptors (tables, types, functions, schemas) that were created by an online restore while the download job was paused, canceling the download job would get stuck in the reverting state. This happened because both `setDescriptorsOffline` and `dropDescriptors` would fail when trying to look up descriptors that had already been dropped.

Fix this by skipping descriptors that are already dropped or not found.

Fixes: #165789

Release note: None

### CODE REVIEW

File: pkg/backup/restore_job.go [hunk 1]
```diff
@@ -3594,10 +3594,16 @@ func (r *restoreResumer) dropDescriptors(
 		// TypeDescriptors don't have a GC job process, so we can just write them
 		// as dropped here.
 		typDesc := details.TypeDescs[i]
-		mutType, err := descsCol.MutableByID(txn.KV()).Type(ctx, typDesc.ID)
+		mutType, err := descsCol.MutableByID(txn.KV()).Desc(ctx, typDesc.ID)
```
Comment (kev-cao) [inline pkg/backup/restore_job.go:3597]: I switched all the lookup calls to `Desc` so that we could do a simple comparison against `catalog.ErrDescriptorNotFound`. The type-specific lookup calls like `Database()` or `Schema()` always replace the error with a type-specific `pgcode`:
https://github.com/cockroachdb/cockroach/blob/d608df0444b8838419b12c7873750bd120115900/pkg/sql/catalog/descs/getters.go#L56-L62

I don't think there's any difference here aside from the fact that we lose the checking that the ID is specifically of that object type, but I don't think that makes much of a difference. But if anyone thinks otherwise, I'm open to changing this.

Comment (msbutler) [reply pkg/backup/restore_job.go:3597]: maybe add a comment here, the first place you do this?

**Review by msbutler — APPROVED** [review]
nice!
