### PR TITLE
storage: fail the test instead of silently logging

### LINKED ISSUE #3799: Failed tests (11192): TestReplicateAfterTruncation
The following test appears to have failed:

[#11192](https://circleci.com/gh/cockroachdb/cockroach/11192):

```
I0113 08:22:21.001775 923 storage/replica.go:1031  raft: proposing ADD_REPLICA {2 2 2} for range 1
W0113 08:22:21.006074 923 kv/dist_sender.go:635  failed to invoke BeginTransaction [/Local/Range/RangeDescriptor/"",/Min), ConditionalPut [/Local/Range/RangeDescriptor/"",/Min), Put [/Meta2/Max,/Min), Put [/Meta1/Max,/Min), EndTransaction [/Local/Range/RangeDescriptor/"",/Min): unexpected value: raw_bytes:"\340u\323\345\003\010\001\022\000\032\001\223\"\006\010\001\020\001\030\001(\002" timestamp:<wall_time:0 logical:42 > 
I0113 08:22:21.006690 923 client/db.go:485  failed batch: unexpected value: raw_bytes:"\340u\323\345\003\010\001\022\000\032\001\223\"\006\010\001\020\001\030\001(\002" timestamp:<wall_time:0 logical:42 > 
I0113 08:22:21.008837 923 storage/engine/rocksdb.go:137  closing in-memory rocksdb instance
I0113 08:22:21.009034 923 storage/engine/rocksdb.go:137  closing in-memory rocksdb instance
--- FAIL: TestReplicateAfterTruncation (0.06s)
	client_raft_test.go:483: storage/replica_command.go:1737: change replicas of 1 failed: unexpected value: raw_bytes:"\340u\323\345\003\010\001\022\000\032\001\223\"\006\010\001\020\001\030\001(\002" timestamp:<wall_time:0 logical:42 > 
=== RUN   TestStoreRangeUpReplicate
E0113 08:22:21.015205 923 gossip/gossip.go:210  different node IDs were set for the same gossip instance (2147483647, 1)
I0113 08:22:21.015977 923 raft/raft.go:446  [group 1] 1 became follower at term 5
I0113 08:22:21.016265 923 raft/raft.go:234  [group 1] newRaft 1 [peers: [1], term: 5, commit: 10, applied: 10, lastindex: 10, lastterm: 5]
I0113 08:22:21.016460 923 raft/raft.go:526  [group 1] 1 is starting a new election at term 5
I0113 08:22:21.017143 923 raft/raft.go:459  [group 1] 1 became candidate at term 6
I0113 08:22:21.017254 923 raft/raft.go:508  [group 1] 1 received vote from 1 at term 6
I0113 08:22:21.017376 923 raft/raft.go:487  [group 1] 1 became leader at term 6
I0113 08:22:21.020877 923 storage/replica.go:1611  gossiping cluster id  from store 1, range 1
--
I0113 08:22:44.115645 923 storage/engine/rocksdb.go:137  closing in-memory rocksdb instance
--- PASS: TestLogSplits (1.14s)
	<autogenerated>:28: prior leak detected, leaktest disabled
=== RUN   Example_rebalancing
--- PASS: Example_rebalancing (1.19s)
FAIL
FAIL	github.com/cockroachdb/cockroach/storage	31.375s
=== RUN   TestBatchBasics
I0113 08:22:52.206013 998 storage/engine/rocksdb.go:137  closing in-memory rocksdb instance
--- PASS: TestBatchBasics (0.01s)
=== RUN   TestBatchGet
I0113 08:22:52.213792 998 storage/engine/rocksdb.go:137  closing in-memory rocksdb instance
--- PASS: TestBatchGet (0.03s)
=== RUN   TestBatchMerge
I0113 08:22:52.244851 998 storage/engine/rocksdb.go:137  closing in-memory rocksdb instance
--- PASS: TestBatchMerge (0.00s)
=== RUN   TestBatchProto

```
Please assign, take a look and update the issue accordingly.

### PR DESCRIPTION
**Pull request by tamird**
Also closes #3799 since I've not been able to reproduce that failure.

[Review on Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/3957)

### CODE REVIEW

**Comment by vivekmenezes** [comment]
LGTM

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/3957#-:-K8thlx7jANq0qJDGuRS:676834233)*

File: storage/client_raft_test.go [hunk 1]
```diff
@@ -524,9 +523,11 @@ func TestReplicateAfterTruncation(t *testing.T) {
 		if err != nil {
 			return false
 		}
-		getResp := reply.(*roachpb.GetResponse)
-		log.Infof("read value %d", mustGetInt(getResp.Value))
-		return mustGetInt(getResp.Value) == 39
+		val := mustGetInt(reply.(*roachpb.GetResponse).Value)
+		if log.V(1) {
```
Comment (bdarnell) [inline storage/client_raft_test.go]: I'd just remove this log line instead of making it a `V(1)`. I don't think `V(1)` logs make much sense in tests because by default logs are only printed from failing tests and if a test is failing when would you not want the extra log detail?

**Comment by bdarnell** [comment]
LGTM

File: storage/client_raft_test.go (hunk 1 above)
Comment (tamird) [inline storage/client_raft_test.go]: https://github.com/cockroachdb/cockroach/pull/3961
