### PR TITLE
sql: fix panic in inverted indexes

### LINKED ISSUE #23190: sql: panic on CREATE INVERTED INDEX
**BUG REPORT**

```
I180227 15:58:05.585150 1 util/log/clog.go:1040  [config] file created at: 2018/02/27 15:58:05
I180227 15:58:05.585150 1 util/log/clog.go:1040  [config] running on machine: Laurens-MBP
I180227 15:58:05.585150 1 util/log/clog.go:1040  [config] binary: CockroachDB CCL v2.0-alpha.20180129-343-gbb1ce80a8-dirty (darwin amd64, built 2018/02/06 16:02:15, go1.9.2)
I180227 15:58:05.585150 1 util/log/clog.go:1040  [config] arguments: [cockroach start --insecure --host=localhost]
```

Created table with JSONB column and tried to create an inverted index.

1. Start three nodes locally, insecure.
2. Create database:
```
CREATE DATABASE json_test;
```
3. Create table:
```
CREATE TABLE users (                                                                                                                  profile_id UUID PRIMARY KEY DEFAULT gen_random_uuid(),                                                                                                   last_updated TIMESTAMP DEFAULT now(),                                                                                                                    user_profile JSONB                                                                                                                                     );
```
4. Insert data:
```
INSERT INTO users (user_profile) VALUES                                                                                               ('{"first_name": "Lola", "last_name": "Dog", "location": "NYC", "online" : true, "friends" : 547}'),                                                     ('{"first_name": "Ernie", "status": "Looking for treats", "location" : "Brooklyn"}'                                                                    );
```
5. Create inverted index:
```
create inverted index dogs on users(user_profile);
```
After, I got the following errors were printed to stderr:

```
driver: bad connection
warning: connection lost!
opening new connection: all session settings will be lost
warning: error retrieving the transaction status: dial tcp [::1]:26257: getsockopt: connection refused
warning: connection lost!
opening new connection: all session settings will be lost
warning: error retrieving the database name: dial tcp [::1]:26257: getsockopt: connection refused
root@:26257 ?>
```

And Node 1 and 3 crashed with the following panics: 

```
panic: initialized checksum = 5b91ac8d

goroutine 1452 [running]:
github.com/cockroachdb/cockroach/pkg/roachpb.(*Value).InitChecksum(0xc42673d370, 0xc427f433b0, 0x2c, 0x30)
	/Users/laurenhirata/go/src/github.com/cockroachdb/cockroach/pkg/roachpb/data.go:251 +0x206
github.com/cockroachdb/cockroach/pkg/roachpb.NewInitPut(0xc427f433b0, 0x2c, 0x30, 0xc425408bc0, 0x5, 0x5, 0x0, 0x0, 0x1, 0x8789608, ...)
	/Users/laurenhirata/go/src/github.com/cockroachdb/cockroach/pkg/roachpb/api.go:890 +0x4d
github.com/cockroachdb/cockroach/pkg/internal/client.(*Batch).InitPut(0xc426c21100, 0x5e048a0, 0xc424fcee00, 0x5f0a740, 0xc42671c218, 0xc42673d401)
	/Users/laurenhirata/go/src/github.com/cockroachdb/cockroach/pkg/internal/client/batch.go:454 +0x1e4
github.com/cockroachdb/cockroach/pkg/sql/distsqlrun.(*indexBackfiller).runChunk.func4(0x6ecca00, 0xc42671c1c0, 0xc4280896c0, 0x10001ff01, 0xc425408d0c)
	/Users/laurenhirata/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsqlrun/indexbackfiller.go:253 +0x105
github.com/cockroachdb/cockroach/pkg/internal/client.(*DB).Txn.func1(0x6ecca00, 0xc42671c1c0, 0xc4280896c0, 0xc425408d0c, 0x0, 0x151751ae2ec8aaf0)
	/Users/laurenhirata/go/src/github.com/cockroachdb/cockroach/pkg/internal/client/db.go:516 +0x43
github.com/cockroachdb/cockroach/pkg/internal/client.(*Txn).Exec(0xc4280896c0, 0x6ecca00, 0xc42671c1c0, 0xc428080101, 0xc420262c40, 0x0, 0x0)
	/Users/laurenhirata/go/src/github.com/cockroachdb/cockroach/pkg/internal/client/txn.go:753 +0x10c
github.com/cockroachdb/cockroach/pkg/internal/client.(*DB).Txn(0xc4206ab530, 0x6ecca00, 0xc42671c1c0, 0xc424fced40, 0x0, 0x0)
	/Users/laurenhirata/go/src/github.com/cockroachdb/cockroach/pkg/internal/client/db.go:515 +0x14b
github.com/cockroachdb/cockroach/pkg/sql/distsqlrun.(*indexBackfiller).runChunk(0xc426a3d000, 0x6eccac0, 0xc427deef00, 0xc424fcea60, 0x1, 0x1, 0xc425099968, 0x2, 0x8, 0xc425099990, ...)
	/Users/laurenhirata/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsqlrun/indexbackfiller.go:236 +0x58d
github.com/cockroachdb/cockroach/pkg/sql/distsqlrun.(*backfiller).mainLoop(0xc426a3d000, 0x6eccac0, 0xc427deef00, 0x5f36281, 0x8)
	/Users/laurenhirata/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsqlrun/backfiller.go:137 +0x5ec
github.com/cockroachdb/cockroach/pkg/sql/distsqlrun.(*backfiller).Run(0xc426a3d000, 0xc424e1a7f8)
	/Users/laurenhirata/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsqlrun/backfiller.go:89 +0x21a
created by github.com/cockroachdb/cockroach/pkg/sql/distsqlrun.(*Flow).Start
	/Users/laurenhirata/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsqlrun/flow.go:466 +0x3c5
```

```
heartbeat failed: rpc error: code = Unavailable desc = all SubConns are in TransientFailure [exhausted])
I180227 23:13:30.965400 443 storage/node_liveness.go:710  [n1,hb] retrying liveness update after storage.errRetryLiveness: result is ambiguous (error=initial connection heartbeat failed: rpc error: code = Unavailable desc = all SubConns are in TransientFailure [exhausted])
I180227 23:13:30.966840 443 storage/node_liveness.go:710  [n1,hb] retrying liveness update after storage.errRetryLiveness: result is ambiguous (error=initial connection heartbeat failed: rpc error: code = Unavailable desc = all SubConns are in TransientFailure [exhausted])
I180227 23:13:30.969412 443 storage/node_liveness.go:710  [n1,hb] retrying liveness update after storage.errRetryLiveness: result is ambiguous (error=initial connection heartbeat failed: rpc error: code = Unavailable desc = all SubConns are in TransientFailure [exhausted])
I180227 23:13:30.972162 443 storage/node_liveness.go:710  [n1,hb] retrying liveness update after storage.errRetryLiveness: result is ambiguous (erpanic: initialized checksum = 5b91ac8d

goroutine 102031 [running]:
github.com/cockroachdb/cockroach/pkg/roachpb.(*Value).InitChecksum(0xc430f87370, 0xc42f4560c0, 0x2c, 0x30)
	/Users/laurenhirata/go/src/github.com/cockroachdb/cockroach/pkg/roachpb/data.go:251 +0x206
github.com/cockroachdb/cockroach/pkg/roachpb.NewInitPut(0xc42f4560c0, 0x2c, 0x30, 0xc42c4f3fa0, 0x5, 0x5, 0x0, 0x0, 0x1, 0xfd319a8, ...)
	/Users/laurenhirata/go/src/github.com/cockroachdb/cockroach/pkg/roachpb/api.go:890 +0x4d
github.com/cockroachdb/cockroach/pkg/internal/client.(*Batch).InitPut(0xc42a4ef100, 0x5e048a0, 0xc431d485c0, 0x5f0a740, 0xc42eb070d8, 0xc430f87401)
	/Users/laurenhirata/go/src/github.com/cockroachdb/cockroach/pkg/internal/client/batch.go:454 +0x1e4
github.com/cockroachdb/cockroach/pkg/sql/distsqlrun.(*indexBackfiller).runChunk.func4(0x6ecca00, 0xc42eb07080, 0xc428ff2d00, 0x10005cc01, 0xc42c43e0cc)
	/Users/laurenhirata/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsqlrun/indexbackfiller.go:253 +0x105
github.com/cockroachdb/cockroach/pkg/internal/client.(*DB).Txn.func1(0x6ecca00, 0xc42eb07080, 0xc428ff2d00, 0xc42c43e0cc, 0x0, 0x151751b0e41758c8)
	/Users/laurenhirata/go/src/github.com/cockroachdb/cockroach/pkg/internal/client/db.go:516 +0x43
github.com/cockroachdb/cockroach/pkg/internal/client.(*Txn).Exec(0xc428ff2d00, 0x6ecca00, 0xc42eb07080, 0xc428ff0101, 0xc42c24cfe0, 0x0, 0x0)
	/Users/laurenhirata/go/src/github.com/cockroachdb/cockroach/pkg/internal/client/txn.go:753 +0x10c
github.com/cockroachdb/cockroach/pkg/internal/client.(*DB).Txn(0xc420878870, 0x6ecca00, 0xc42eb07080, 0xc431d483c0, 0x0, 0x0)
	/Users/laurenhirata/go/src/github.com/cockroachdb/cockroach/pkg/internal/client/db.go:515 +0x14b
github.com/cockroachdb/cockroach/pkg/sql/distsqlrun.(*indexBackfiller).runChunk(0xc43afe8800, 0x6eccac0, 0xc431bb3ec0, 0xc431cd3be0, 0x1, 0x1, 0xc42c4f3c88, 0x2, 0x8, 0xc42c4f3c90, ...)
	/Users/laurenhirata/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsqlrun/indexbackfiller.go:236 +0x58d
github.com/cockroachdb/cockroach/pkg/sql/distsqlrun.(*backfiller).mainLoop(0xc43afe8800, 0x6eccac0, 0xc431bb3ec0, 0x5f36281, 0x8)
	/Users/laurenhirata/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsqlrun/backfiller.go:137 +0x5ec
github.com/cockroachdb/cockroach/pkg/sql/distsqlrun.(*backfiller).Run(0xc43afe8800, 0xc42bf887f8)
	/Users/laurenhirata/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsqlrun/backfiller.go:89 +0x21a
created by github.com/cockroachdb/cockroach/pkg/sql/distsqlrun.(*Flow).Start
	/Users/laurenhirata/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsqlrun/flow.go:466 +0x3c5
```

### PR DESCRIPTION
**Pull request by m-schneider**
Before this patch, creating and inverted index on a table with rows
containing JSON would cause a panic.

Now the optimization to reduce memory allocations in
EncodeSecondaryIndexes is modified to allow us to reuse slices, but will
also return the amount of the slice used. This will make sure we don't
have duplicates from reusing a longer slice.

Closes #23190

Release note: None

### CODE REVIEW

**Comment by nvanbenschoten** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[pkg/sql/distsqlrun/indexbackfiller.go, line 189 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/23279#-L6Yt-8G17F2xXaH-y4s:-L6Yt-8G17F2xXaH-y4t:b-bfebte) ([raw file](https://github.com/cockroachdb/cockroach/blob/4b07f4b469dd1ce726ba52fca1eca0fd3f03f8a6/pkg/sql/distsqlrun/indexbackfiller.go#L189)):*
> ```Go
> 			}
> 			// We're resetting the length of this slice for variable length indexes such as inverted
> 			// indexes which can append entries to the end of the slice.
> ```

Make a note about what can go wrong if we don't do this.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/23279)*

File: pkg/sql/distsqlrun/indexbackfiller.go [hunk 1]
```diff
@@ -185,6 +185,9 @@ func (ib *indexBackfiller) runChunk(
 				ib.rowVals, secondaryIndexEntries); err != nil {
 				return nil, err
 			}
+			// We're resetting the length of this slice for variable length indexes such as inverted
+			// indexes which can append entries to the end of the slice.
+			secondaryIndexEntries = secondaryIndexEntries[:len(mutations)]
```
Comment (vivekmenezes) [inline pkg/sql/distsqlrun/indexbackfiller.go]: you're reseting these secondary indexes before using them below?

File: pkg/sql/distsqlrun/indexbackfiller.go [hunk 2]
```diff
@@ -185,6 +185,9 @@ func (ib *indexBackfiller) runChunk(
 				ib.rowVals, secondaryIndexEntries); err != nil {
```
Comment (vivekmenezes) [inline pkg/sql/distsqlrun/indexbackfiller.go]: The comment above EncodeSecondaryIndexes doesnt say that it can generate a different number of index entries as the indexes passed in. This contract has been completely broken. I'd ask that you change the comment to explain that while it's expected to be the same size passed in, it will return a different size slice. I also feel we should panic at the start of EncodeSecondaryIndexes() for len(indexes) == len(secondaryIndexes)

and a comment above the ```if len(entries) > 1 {```

and while you're at it can you change 

```
if len(entries) > 1 {
 +			secondaryIndexEntries = append(secondaryIndexEntries, entries[1:]...)
 +		}
 +		if len(entries) > 0 {
 +			secondaryIndexEntries[i] = entries[0]
```
to

```
secondaryIndexEntries[i] = entries[0]
if len(entries) > 1 {
 			secondaryIndexEntries = append(secondaryIndexEntries, entries[1:]...)
 		}
```

Comment (vivekmenezes) [reply pkg/sql/distsqlrun/indexbackfiller.go]: Do you think adding unittests to catch the same problem for all the different call sites of this function are valuable?

File: pkg/sql/logictest/testdata/logic_test/inverted_index [hunk 3]
```diff
@@ -458,3 +458,17 @@ SELECT * from d where b @> 'null' ORDER BY a;
...
+  last_updated TIMESTAMP DEFAULT now(),
+  user_profile JSONB
+);
+
+statement ok
+INSERT INTO users (user_profile) VALUES  ('{"first_name": "Lola", "last_name": "Dog", "location": "NYC", "online" : true, "friends" : 547}'),
+                                         ('{"first_name": "Ernie", "status": "Looking for treats", "location" : "Brooklyn"}');
+
+statement ok
+CREATE INVERTED INDEX dogs on users(user_profile);
```
Comment (vivekmenezes) [inline pkg/sql/logictest/testdata/logic_test/inverted_index]: you can run a select here to check that the inverted index is created properly

**Comment by m-schneider** [comment]
Review status: 0 of 2 files reviewed at latest revision, 4 unresolved discussions, some commit checks pending.

---

*[pkg/sql/distsqlrun/indexbackfiller.go, line 185 at r1](https://beta.reviewable.io/reviews/cockroachdb/cockroach/23279#-L6Y10YBjPlZBWYSJnUV-r1-185:-L6bQTTYjivnkCD9BMb3:b-pkezp9) ([raw file](https://github.com/cockroachdb/cockroach/blob/4b07f4b469dd1ce726ba52fca1eca0fd3f03f8a6/pkg/sql/distsqlrun/indexbackfiller.go#L185)):*
<details><summary><i>Previously, vivekmenezes wrote…</i></summary><blockquote>

Do you think adding unittests to catch the same problem for all the different call sites of this function are valuable?
</blockquote></details>

There's only one more call site, for this function in rowwriter which doesn't call it in a loop and file also doesn't seem to have any unit tests associated with it. 

---

*[pkg/sql/distsqlrun/indexbackfiller.go, line 189 at r1](https://beta.reviewable.io/reviews/cockroachdb/cockroach/23279#-L6Yt-8G17F2xXaH-y4s:-L6bQWDypU692LgVYmcq:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/4b07f4b469dd1ce726ba52fca1eca0fd3f03f8a6/pkg/sql/distsqlrun/indexbackfiller.go#L189)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Make a note about what can go wrong if we don't do this.
</blockquote></details>

Done.

---

*[pkg/sql/distsqlrun/indexbackfiller.go, line 190 at r1](https://beta.reviewable.io/reviews/cockroachdb/cockroach/23279#-L6Y10YBjPlZBWYSJnUV-r1-190:-L6bQoGJUXjLwL37jOkr:bks5xdc) ([raw file](https://github.com/cockroachdb/cockroach/blob/4b07f4b469dd1ce726ba52fca1eca0fd3f03f8a6/pkg/sql/distsqlrun/indexbackfiller.go#L190)):*
<details><summary><i>Previously, vivekmenezes wrote…</i></summary><blockquote>

you're reseting these secondary indexes before using them below?
</blockquote></details>

Moved it up.

---

*[pkg/sql/logictest/testdata/logic_test/inverted_index, line 474 at r1](https://beta.reviewable.io/reviews/cockroachdb/cockroach/23279#-L6Y10YBjPlZBWYSJnUW-r1-474:-L6bQzlODNxXDtP75CNP:b-f4e21j) ([raw file](https://github.com/cockroachdb/cockroach/blob/4b07f4b469dd1ce726ba52fca1eca0fd3f03f8a6/pkg/sql/logictest/testdata/logic_test/inverted_index#L474)):*
<details><summary><i>Previously, vivekmenezes wrote…</i></summary><blockquote>

you can run a select here to check that the inverted index is created properly
</blockquote></details>

Added for both values.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/cockroachdb/cockroach/23279)*

**Comment by m-schneider** [comment]
Review status: 0 of 4 files reviewed at latest revision, 4 unresolved discussions.

---

*[pkg/sql/distsqlrun/indexbackfiller.go, line 185 at r1](https://beta.reviewable.io/reviews/cockroachdb/cockroach/23279#-L6Y10YBjPlZBWYSJnUV-r1-185:-L6wcnYn4B_uNh-aBfj0:b7eaoki) ([raw file](https://github.com/cockroachdb/cockroach/blob/4b07f4b469dd1ce726ba52fca1eca0fd3f03f8a6/pkg/sql/distsqlrun/indexbackfiller.go#L185)):*
<details><summary><i>Previously, m-schneider (Masha Schneider) wrote…</i></summary><blockquote>

There's only one more call site, for this function in rowwriter which doesn't call it in a loop and file also doesn't seem to have any unit tests associated with it. 
</blockquote></details>

I added the changes we talked about including the panic in EncodeSecondaryIndexes.

---

*[pkg/sql/sqlbase/rowwriter.go, line 102 at r2](https://beta.reviewable.io/reviews/cockroachdb/cockroach/23279#-L6wdFDsAEY24dBozeBR:-L6wdFDsAEY24dBozeBS:b-9ottj3) ([raw file](https://github.com/cockroachdb/cockroach/blob/697a3693a538056033e6cee39cedaa72f01870ef/pkg/sql/sqlbase/rowwriter.go#L102)):*
> ```Go
> 	colIDtoRowIndex map[ColumnID]int, values []tree.Datum,
> ) (secondaryIndexEntries []IndexEntry, err error) {
> 	if rh.indexEntries == nil {
> ```

I changed it to this because after adding a panic, I learned that there are some code paths which already have index entries allocated.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/cockroachdb/cockroach/23279)*

File: pkg/sql/sqlbase/rowwriter.go [hunk 4]
```diff
@@ -99,7 +99,7 @@ func (rh *rowHelper) encodeIndexes(
 func (rh *rowHelper) encodeSecondaryIndexes(
 	colIDtoRowIndex map[ColumnID]int, values []tree.Datum,
 ) (secondaryIndexEntries []IndexEntry, err error) {
-	if len(rh.indexEntries) != len(rh.Indexes) {
+	if rh.indexEntries == nil {
```
Comment (vivekmenezes) [inline pkg/sql/sqlbase/rowwriter.go]: Given that we do have expected cases of rh.indexEntries != nil I feel more comfortable with you leaving the code as is ```if len(rh.indexEntries) != len(rh.Indexes) ```so as to never trigger the panic you've added to the code.

**Review by vivekmenezes — APPROVED** [review]

**Comment by m-schneider** [comment]
*[pkg/sql/sqlbase/rowwriter.go, line 102 at r2](https://beta.reviewable.io/reviews/cockroachdb/cockroach/23279#-L6wbJ8CiP8oGPUdL00h-r2-102:-L6xB_qJEbDVNKWb6xwf:b-p19d82) ([raw file](https://github.com/cockroachdb/cockroach/blob/697a3693a538056033e6cee39cedaa72f01870ef/pkg/sql/sqlbase/rowwriter.go#L102)):*
<details><summary><i>Previously, vivekmenezes wrote…</i></summary><blockquote>

Given that we do have expected cases of rh.indexEntries != nil I feel more comfortable with you leaving the code as is ```if len(rh.indexEntries) != len(rh.Indexes) ```so as to never trigger the panic you've added to the code.
</blockquote></details>

Changed it back to what it was.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/cockroachdb/cockroach/23279)*

**Review by vivekmenezes — APPROVED** [review]
LGTM

**Comment by jordanlewis** [comment]
This needs to be cherry-picked into 2.0.
