### PR TITLE
pkg/storage: remove `rocksdb` from error string

### LINKED ISSUE #72823: Cockroach v21.2 does not accept `--storage-engine=rocksdb` but error message says it does
```
$ cockroach version
Build Tag:        v21.2.0
Build Time:       2021/11/15 14:00:58
Distribution:     CCL
Platform:         darwin amd64 (x86_64-apple-darwin19)
Go Version:       go1.16.6
C Compiler:       Clang 10.0.0 
Build Commit ID:  79e5979416cb426092a83beff0be1c20aebf84c6
Build Type:       release
```

```
$ cockroach start --storage-engine=rocksdb
... snip!  ...
ERROR: invalid argument "rocksdb" for "--storage-engine" flag: invalid storage engine: rocksdb (possible values: rocksdb, pebble)
```

Culprit appears to be here: https://github.com/cockroachdb/cockroach/blob/master/pkg/storage/enginepb/engine.go#L46 

I imagine this exists in v21.1.* as well

### PR DESCRIPTION
**Pull request by nicktrav**
Fix a documentation issue where starting a Cockroach instance with a
value other than `default` or `pebble` prints an error stating that
`rocksdb` is an allowed value. Remove mention of `rocksdb`.

Fixes #72823.

Release note: None

### CODE REVIEW

File: pkg/storage/enginepb/engine.go [hunk 1]
```diff
@@ -43,7 +43,7 @@ func (e *EngineType) Set(s string) error {
 		*e = EngineTypePebble
 	default:
 		return fmt.Errorf("invalid storage engine: %s "+
-			"(possible values: rocksdb, pebble)", s)
+			"(possible values: pebble)", s)
```
Comment (nicktrav) [inline pkg/storage/enginepb/engine.go:46]: @itsbilal @sumeerbhola - is there any reason to keep this code around now that we only support a single storage engine? I noticed that it was left as part of the cleanup in #55509, so wasn't sure if there was a particular reason.

**Review by rmloveland — APPROVED** [review]
LGTM

**Comment by nicktrav** [comment]
TFTR! Will land this to at least knock out the docs issue. Can circle back if required to remove additional code.

**Comment by nicktrav** [comment]
bors r=rmloveland
