### PR TITLE
roachpb: make range/replica descriptor fields non-nullable

### LINKED ISSUE #85060: kvserver: incorrect DistSender leaseholder processing for non-`VOTER`s
`ReplicaDescriptor.Type` is a pointer rather than a scalar value:

https://github.com/cockroachdb/cockroach/blob/aee773a3234d5e8ce521359e0fb6c24d9d7c93ba/pkg/roachpb/metadata.proto#L151

We often use regular equality comparisons on replica descriptors, notably in the DistSender and gRPC transport:

https://github.com/cockroachdb/cockroach/blob/f77e393230fbedb57e5caa0ebbf26356b3899c73/pkg/kv/kvclient/kvcoord/dist_sender.go#L2209

https://github.com/cockroachdb/cockroach/blob/9ad06da853ca0f306f4baeb09b446b5d001fbc53/pkg/kv/kvclient/kvcoord/transport.go#L258

But recall that equality for pointers will check that the memory address is the same, rather than that the value is the same. Thus two identical replica descriptors with a type different from `VOTER` (the zero value) will be considered unequal if they are stored in different memory locations.

One immediate effect of this is that the DistSender will not prioritize new leaseholders with a `VOTER_INCOMING` type. In #74546, `VOTER_INCOMING` was allowed to receive the lease and thus included in the DistSender's replica list with the `RoutingPolicy_LEASEHOLDER` policy:

https://github.com/cockroachdb/cockroach/blob/f77e393230fbedb57e5caa0ebbf26356b3899c73/pkg/kv/kvclient/kvcoord/dist_sender.go#L1932-L1943

However, when it receives the NLHE it attempts to move the new leaseholder to the front of the transport list:

https://github.com/cockroachdb/cockroach/blob/f77e393230fbedb57e5caa0ebbf26356b3899c73/pkg/kv/kvclient/kvcoord/dist_sender.go#L2201-L2212

But this won't happen because the non-`nil` `Type` doesn't satisfy the equality check in `MoveToFront`:

https://github.com/cockroachdb/cockroach/blob/9ad06da853ca0f306f4baeb09b446b5d001fbc53/pkg/kv/kvclient/kvcoord/transport.go#L258

Jira issue: CRDB-18022

### PR DESCRIPTION
**Pull request by erikgrinaker**
This patch makes all fields in range/replica descriptors non-nullable,
fixing a long-standing TODO.

Additionally, this fixes a set of bugs where code would use regular
comparison operators (e.g. `==`) to compare replica descriptors, which
with nullable pointer fields would compare the memory locations rather
than the values. One practical consequence of this was that the
DistSender would fail to use a new leaseholder with a non-`VOTER` type
(e.g.  `VOTER_INCOMING`), instead continuing to try other replicas
before backing off. However, there are further issues surrounding this
bug and it will be addressed separately in a way that is more amenable
to backporting.

The preparatory work for this was done in ea720e3e.

Touches #85060.
Touches #38308.
Touches #38465.

Release note: None

### CODE REVIEW

**Comment by erikgrinaker** [comment]
I've split the DistSender fix out to #85140, since there are additional issues around these replica descriptor comparisons.

File: pkg/roachpb/data.go [hunk 1]
```diff
@@ -1906,13 +1906,8 @@ func (l Lease) Equivalent(newL Lease) bool {
...
 	// Replica's lease. We don't expect a leaseholder to ever become a LEARNER
-	// replica, but that also shouldn't prevent it from extending its lease. The
-	// code also avoids a potential bug where an unset ReplicaType and a set
-	// VOTER ReplicaType are considered distinct and non-equivalent.
-	//
-	// Change this line to the following when ReplicaType becomes non-nullable:
-	//  l.Replica.Type, newL.Replica.Type = 0, 0
-	l.Replica.Type, newL.Replica.Type = nil, nil
+	// replica, but that also shouldn't prevent it from extending its lease.
+	l.Replica.Type, newL.Replica.Type = 0, 0
```
Comment (pavelkalinnikov) [inline pkg/roachpb/data.go:1910]: What do zeroes mean here? Is there a named constant for what they represent?

File: pkg/kv/kvserver/replica_test.go [hunk 2]
```diff
@@ -13484,12 +13484,11 @@ func TestPrepareChangeReplicasTrigger(t *testing.T) {
 		chgs := make([]internalReplicationChange, 0, len(typs))
 		rDescs := make([]roachpb.ReplicaDescriptor, 0, len(typs))
 		for i, typ := range typs {
-			typ := typ // local copy - we take addr below
```
Comment (pavelkalinnikov) [inline pkg/kv/kvserver/replica_test.go:13487]: Subtle :) Nice to see it gone.

File: pkg/kv/kvserver/replica_follower_read.go [hunk 3]
```diff
@@ -73,10 +73,10 @@ func (r *Replica) canServeFollowerReadRLocked(ctx context.Context, ba *roachpb.B
 		return false
 	}
 
-	switch typ := repDesc.GetType(); typ {
```
Comment (pavelkalinnikov) [inline pkg/kv/kvserver/replica_follower_read.go:76]: optional: Personally, I would leave this assignment to avoid retyping `repDesc.Type` below (here and in a few other cases in this PR), but it seems just a taste thing.

**Review by pav-kv — APPROVED** [review]
LGTM % comments.

Also, it looks like, for ease/speed of review, this PR could be split in 2, one per proto field modified? Ok to leave as is.

File: pkg/roachpb/metadata_replicas.go [hunk 4]
```diff
@@ -97,7 +55,7 @@ func (d ReplicaSet) Descriptors() []ReplicaDescriptor {
 }
 
 func predVoterFull(rDesc ReplicaDescriptor) bool {
-	switch rDesc.GetType() {
+	switch rDesc.Type {
```
[the remark this answers is not in the document]
Comment (erikgrinaker) [reply pkg/roachpb/metadata_replicas.go:58]: Yeah, its only purpose was to convert `nil` to `VOTER`. gogoproto doesn't generate getters by default, this was a custom one. We're still stuck on the old Protobuf library and gogoproto for reasons that escape me right now.

File: pkg/roachpb/data.go (hunk 1 above)
Comment (erikgrinaker) [reply pkg/roachpb/data.go:1910]: The zero value is `VOTER`, but I think 0 better expresses the intent: we're clearing these fields because we don't care about them for comparison purposes.

File: pkg/kv/kvserver/replica_follower_read.go (hunk 3 above)
Comment (erikgrinaker) [reply pkg/kv/kvserver/replica_follower_read.go:76]: Yeah, left it like this in a few places where we reuse the value quite a lot, but I didn't see much point in it here.

**Comment by erikgrinaker** [comment]
>Also, it looks like, for ease/speed of review, this PR could be split in 2, one per proto field modified? Ok to leave as is.

Yeah, I agree. Not sure if it's worth the effort to go back and split it up, but it would've been better to submit them separately.

**Comment by erikgrinaker** [comment]
Spun up a mixed-version cluster with this PR and `master`, didn't see any issues with range descriptor incompatibilities like we did previously. Going to push this through and see if the nightlies pick up anything.

TFTR!

bors r=pavelkalinnikov
