### PR TITLE
changefeedccl: fix race on kafka startup

### LINKED ISSUE #131570: roachtest: cdc/tpcc-1000/sink=kafka failed
roachtest.cdc/tpcc-1000/sink=kafka [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/17085634?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/17085634?buildTab=artifacts#/cdc/tpcc-1000/sink=kafka) on release-24.1 @ [7df1acaa33a733960eb3968850f65c86aff93f51](https://github.com/cockroachdb/cockroach/commits/7df1acaa33a733960eb3968850f65c86aff93f51):

```
(cdc.go:553).newChangefeed: failed to create changefeed: pq: kafka server: Replication-factor is invalid
(cluster.go:2416).Run: context canceled
(cdc.go:378).Close: error shutting down prometheus/grafana: context canceled
test artifacts and logs in: /artifacts/cdc/tpcc-1000/sink=kafka/run_1
```

Parameters:
 - <code>ROACHTEST_arch=amd64</code>
 - <code>ROACHTEST_cloud=gce</code>
 - <code>ROACHTEST_coverageBuild=false</code>
 - <code>ROACHTEST_cpu=16</code>
 - <code>ROACHTEST_encrypted=false</code>
 - <code>ROACHTEST_metamorphicBuild=false</code>
 - <code>ROACHTEST_ssd=0</code>
<details><summary>Help</summary>
<p>

See: [roachtest README](https://github.com/cockroachdb/cockroach/blob/master/pkg/cmd/roachtest/README.md)

See: [How To Investigate \(internal\)](https://cockroachlabs.atlassian.net/l/c/SSSBr8c7)

See: [Grafana](https://go.crdb.dev/roachtest-grafana/teamcity-17085634/cdc-tpcc-1000-sink-kafka/1727595340099/1727595871245)

</p>
</details>
/cc @cockroachdb/cdc
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*cdc/tpcc-1000/sink=kafka.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/bazci/githubpost/issues)
</sub>

Jira issue: CRDB-42611

### PR DESCRIPTION
**Pull request by asg0451**
Wait for kafka to be available after starting it
before creating the changefeed.

Fixes: #131570

Release note: None

### CODE REVIEW

File: pkg/cmd/roachtest/tests/cdc.go [hunk 1]
```diff
@@ -3111,6 +3111,15 @@ func (k kafkaManager) start(ctx context.Context, service string, envVars ...stri
...
 	k.restart(ctx, service, envVars...)
+	// Wait for kafka to be ready. Otherwise we can sometimes try to connect to
+	// it too fast which fails the test.
+	k.waitForKafkaAvailable(ctx)
+}
+
+func (k kafkaManager) waitForKafkaAvailable(ctx context.Context) {
+	k.t.Status("waiting for kafka to be ready")
+	k.c.Run(ctx, option.WithNodes(k.kafkaSinkNodes), filepath.Join(k.binDir(), "kafka-topics"),
+		"--bootstrap-server=localhost:9092", "--list")
```
Comment (wenyihu6) [inline pkg/cmd/roachtest/tests/cdc.go:3122]: Do we need to retry if it fails on the first attempt?

Comment (asg0451) [reply pkg/cmd/roachtest/tests/cdc.go:3122]: no, this command should do retries itself for about 30 seconds.

**Review by wenyihu6 — APPROVED** [review]
nit: add comments on `kafka-topics` retries automatically

**Review by wenyihu6 — APPROVED** [review]
Double checking - I assume k.c.Run should fail when kafka-topics reports a connection issue. Is that correct, or do we need to explicitly parse the output of kafka-topics to ensure it fails?

**Comment by asg0451** [comment]
bors r=wenyihu6
