### PR TITLE
streamingccl: fix nil linter check error and stream_ingestion_test error

### LINKED ISSUE #79926: streamclient: suspect code in `random_stream_client.go`
In my testing the `nilness` linter flagged this line of code in `random_stream_client.go`:

```
					if rng.Float64() < config.dupProbability && keyValCopy != nil {
```

The problem being that it is impossible for `keyValCopy` to be non-`nil` at this point. It is declared on line 374 and is not updated prior to this check. It is later set on line 398 and read from (without a nilness check?) on line 410. This code should be updated at least so it does not trigger any `nilness` check errors.

### PR DESCRIPTION
**Pull request by gh-casper**
Previously, the stream ingestion test has no error since no
duplicate event is generated. This PR fixes this and nil linter
check error at the same time.

Release note: None
Closes: https://github.com/cockroachdb/cockroach/issues/79926

Related to https://github.com/cockroachdb/cockroach/pull/79929 which 
disables random_stream_client nil linter check. Will re-enable it after it's 
merged.

### CODE REVIEW

**Comment by gh-casper** [comment]
@rickystewart Thanks for finding this!

**Review by rickystewart — APPROVED** [review]

File: pkg/ccl/streamingccl/streamclient/random_stream_client.go [hunk 1]
```diff
@@ -407,7 +407,9 @@ func (m *randomStreamClient) Subscribe(
 			if event.Type() == streamingccl.KVEvent {
 				// Use the originally generated KeyValue copy as the KeyValue inside the event might
 				// get modified by ingestion processor's tenant rekeyer.
-				event = streamingccl.MakeKVEvent(*keyValCopy)
+				// 'keyValCopy' will only be set when it is a KV event. Copying the 'keyValCopy' again
+				// to prevent the event being modified by interceptor again.
+				event = streamingccl.MakeKVEvent(*copyKeyVal(keyValCopy))
```
Comment (miretskiy) [inline pkg/ccl/streamingccl/streamclient/random_stream_client.go:412]: perhaps are apis are not good? I don't understand why we need a copy of a copy...

**Review by gh-casper — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/79935)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @miretskiy and @samiskin)

___
*[pkg/ccl/streamingccl/streamclient/random_stream_client.go, line 412 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/79935#-N-_J_SbbR7Qkvkh-CTR-r1-412:-N-xLao5EIZiyirGxHXQ:bnb13o8) ([raw file](https://github.com/cockroachdb/cockroach/blob/090fe25673dd560a17570cbb711ebfc56718af9c/pkg/ccl/streamingccl/streamclient/random_stream_client.go#L412)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

perhaps are apis are not good? I don't understand why we need a copy of a copy...
</blockquote></details>

The reason we want to make a copy at the first place is that the generated KV event might get modified downstream. The flow looks like this: generate a event, make a copy for this event, event goes to streamclient's channel and gets modified, use the copy the create a event which will passed into interceptor which may modify the event.  In the last step, if we use MakeKVEvent to use copy's value to create a event, then the copy will be modified as well. This copy should not be modified because it will be used when we generate the next duplicate event, so we have to create another copy.



_Code quote:_
```Go
streamingccl.MakeKVEvent
```
