### PR TITLE
sqlstats: unskip tests hitting combinedstmts and stmts endpoints

### LINKED ISSUE #109184: sql stats: extend timeout for tests for `combinedstmts` endpoints
**Describe the problem**

Currently, tests which hit the `combinedstmts` endpoint will fail under stress. The current http client for the `GetJSONProtoWithAdminOption` test function is set to 10s, which isn't enough for mosts tests. The http client should have its timeout extended or provide an option to extend to a sufficient duration.

Jira issue: CRDB-30814

### PR DESCRIPTION
**Pull request by gtr**
Fixes: #109184.

Previously, tests which hit the `combinedstmts` and `statements`
endpoints were skipped under stress because they would occaisonally
fail. This commit unskips these tests and instead of unmarshalling the
metadata JSON blob, the select query directly extracts the values needed
from it.

Release note: None

### CODE REVIEW

**Comment by j82w** [comment]
*[`pkg/server/application_api/sql_stats_test.go` line 513 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/109381#-NchBu7UEB1mCBRzNS1o:-NchBu7UEB1mCBRzNS1p:b-gd06yc) ([raw file](https://github.com/cockroachdb/cockroach/blob/096560e9743becbd9999f5181767766b150bddb2/pkg/server/application_api/sql_stats_test.go#L513)):*
> ```Go
> 
> 	// Increase the timeout for the http client if under stress.
> 	additionalTimeout := 0 * time.Second
> ```

On the test that is failing can you add a custom message to the require to output the full respStatement? I think it will help understand what is causing the failure, and will be helpful in the future if the test fails.

**Review by gtr — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/109381)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @j82w)

___
*[`pkg/server/application_api/sql_stats_test.go` line 513 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/109381#-NchBu7UEB1mCBRzNS1o:-NchKFBXEtZvdrHpP3eP:b-smn7ov) ([raw file](https://github.com/cockroachdb/cockroach/blob/096560e9743becbd9999f5181767766b150bddb2/pkg/server/application_api/sql_stats_test.go#L513)):*
<details><summary><i>Previously, j82w (Jake) wrote…</i></summary><blockquote>

On the test that is failing can you add a custom message to the require to output the full respStatement? I think it will help understand what is causing the failure, and will be helpful in the future if the test fails.
</blockquote></details>

Done. Full response is printed.

**Comment by j82w** [comment]
*[`pkg/server/combined_statement_stats.go` line 801 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/109381#-NcwIIEBBe5fNG_kKSr9:-NcwIIEBBe5fNG_kKSrA:b3kl1x2) ([raw file](https://github.com/cockroachdb/cockroach/blob/96106c0aea747675455c5cebe13a8391552974cf/pkg/server/combined_statement_stats.go#L801)):*
> ```Go
> 
> 		distSQLCountStr := string(*row[4].(*tree.DString))
> 		distSQLCountInt, err := strconv.ParseInt(distSQLCountStr, 10, 64)
> ```

You could cast the value in the query `COALESCE(merged_metadata ->> 'distSQLCount'::INT,0)  AS distSQLCount,` to avoid the parse logic and if the row doesn't have any value.

File: pkg/server/combined_statement_stats.go [hunk 1]
```diff
@@ -676,18 +690,32 @@ FROM (SELECT fingerprint_id,
...
-      GROUP BY
-          fingerprint_id,
-          app_name) %s
-%s`,
+WITH Aggregated AS (
+    SELECT fingerprint_id,
+      array_agg(distinct transaction_fingerprint_id) AS txn_fingerprints,
+      app_name,
+      max(aggregated_ts) AS aggregated_ts,
+      crdb_internal.merge_stats_metadata(array_agg(metadata)) AS merged_metadata,
```
Comment (xinhaoz) [inline pkg/server/combined_statement_stats.go:698]: If this query is for the activity table, it needs to use `crdb_internal.merge_aggregated_stmt_metadata` because the metadata column in the activity table is already aggregated from the full stmts system table.

**Review by gtr — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/109381)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @j82w and @xinhaoz)

___
*[`pkg/server/combined_statement_stats.go` line 698 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/109381#gh-1307434229:-NcwMH6x7DazItQ2IXMQ:bxluer0) ([raw file](https://github.com/cockroachdb/cockroach/blob/96106c0aea747675455c5cebe13a8391552974cf/pkg/server/combined_statement_stats.go#L698)):*
<details><summary><i>Previously, xinhaoz (Xin Hao Zhang) wrote…</i></summary><blockquote>

If this query is for the activity table, it needs to use `crdb_internal.merge_aggregated_stmt_metadata` because the metadata column in the activity table is already aggregated from the full stmts system table.
</blockquote></details>

Good catch! I forgot to change the function call for this table when re-writing the query.
___
*[`pkg/server/combined_statement_stats.go` line 801 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/109381#-NcwIIEBBe5fNG_kKSr9:-NcwMCWB7i4KsiZuuGYL:b-g1hs46) ([raw file](https://github.com/cockroachdb/cockroach/blob/96106c0aea747675455c5cebe13a8391552974cf/pkg/server/combined_statement_stats.go#L801)):*
<details><summary><i>Previously, j82w (Jake) wrote…</i></summary><blockquote>

You could cast the value in the query `COALESCE(merged_metadata ->> 'distSQLCount'::INT,0)  AS distSQLCount,` to avoid the parse logic and if the row doesn't have any value.
</blockquote></details>

Makes sense, done.

**Comment by j82w** [comment]
*[`pkg/server/combined_statement_stats.go` line 654 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/109381#-NcwV3w4AnjxKVxEkFQ7:-NcwV3w4AnjxKVxEkFQ8:bs4ve4q) ([raw file](https://github.com/cockroachdb/cockroach/blob/fda4a9e6abef1fca5c272c22b5417c23ff9eafc4/pkg/server/combined_statement_stats.go#L654)):*
> ```Go
> 	const expectedNumDatums = 11
> 	const queryFormat = `
> WITH Aggregated AS (
> ```

What is the reason for converting this use a CTE? Does it impact the query plan?

**Review by gtr — COMMENTED** [review]
Bumped additional timeout to 30s.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/109381#-:-Ncwg0oF2AbicYAF_s7a:b6z2j3f)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @j82w and @xinhaoz)

___
*[`pkg/server/combined_statement_stats.go` line 654 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/109381#-NcwV3w4AnjxKVxEkFQ7:-NcwXGVvAjfWT4VIClvD:bb7ckk2) ([raw file](https://github.com/cockroachdb/cockroach/blob/fda4a9e6abef1fca5c272c22b5417c23ff9eafc4/pkg/server/combined_statement_stats.go#L654)):*
<details><summary><i>Previously, j82w (Jake) wrote…</i></summary><blockquote>

What is the reason for converting this use a CTE? Does it impact the query plan?
</blockquote></details>

I used the CTE for readability. AFAIK, using a CTE doesn't impact the query plan since its result isn't stored but rather integrated into the main query. I've revised the query, eliminating the CTE and opting for a subquery, and made some minor formatting adjustments for consistency.

**Review by gtr — COMMENTED** [review]
Changes:
- Increased timeout for `TestStatusAPIStatements` to 30s when under stress.
- Improved clarity by renaming variables and helper functions.
- Addressed transient 40001 error by filtering for statements associated with the test app name that also executed successfully (since statements which failed and then succeeded have different fingerprints). We also check that each executed statement is found in the response and if it is not, it's an error.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/109381#-:-NcxSJI7DVZ6xGzn2ksJ:b-47woti)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @j82w and @xinhaoz)

___
*[`pkg/server/application_api/sql_stats_test.go` line 642 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/109381#-NcxTD1xAoCwiXZctJVw:-NcxTD1xAoCwiXZctJVx:b-fv0uz) ([raw file](https://github.com/cockroachdb/cockroach/blob/b62647f45796a09b216b477bbbbe4fa960daa7d9/pkg/server/application_api/sql_stats_test.go#L642)):*
> ```Go
> 			actualFailed := respStatement.Key.KeyData.Failed
> 
> 			stmtJSONString := responseToJSON(respStatement)
> ```

I noticed that I'm currently marshalling to JSON (an expensive operation) irrespective of whether the expected data matches the actual data. Ideally, we should only marshal when there's a discrepancy between the expected and actual data. Outside of using a verbose `if expectedData.fullScan != actualFullScan || expectedData.FullScan != ...`, I'm uncertain about alternative approaches. I believe the current method should be fine, but I thought it was worth highlighting.

**Review by j82w — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/109381)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @gtr and @xinhaoz)

___
*[`pkg/server/combined_statement_stats.go` line 798 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/109381#-NcxVP67AO3nFycp2jFS:-NcxVP67AO3nFycp2jFT:b-24eozm) ([raw file](https://github.com/cockroachdb/cockroach/blob/b62647f45796a09b216b477bbbbe4fa960daa7d9/pkg/server/combined_statement_stats.go#L798)):*
> ```Go
> 		query := string(tree.MustBeDString(row[7]))
> 		querySummary := string(tree.MustBeDString(row[8]))
> 		databases := string(tree.MustBeDString(row[9]))
> ```

Is this still formatted correctly? Not sure how a JSON string array is converted to a a string.
___
*[`pkg/server/application_api/sql_stats_test.go` line 624 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/109381#-NcxX4UE-ZGz3ufgJ5Os:-NcxX4UE-ZGz3ufgJ5Ot:b6mlv4y) ([raw file](https://github.com/cockroachdb/cockroach/blob/b62647f45796a09b216b477bbbbe4fa960daa7d9/pkg/server/application_api/sql_stats_test.go#L624)):*
> ```Go
> 		// statement statistics received from the server response.
> 		actualResponseStatsMap := make(map[string]serverpb.StatementsResponse_CollectedStatementStatistics)
>     for _, respStatement := range resp.Statements {
> ```

nit: fix indents
___
*[`pkg/server/application_api/sql_stats_test.go` line 626 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/109381#-NcxXTPm8A6YqPn9svk1:-NcxXTPm8A6YqPn9svk2:b-db857f) ([raw file](https://github.com/cockroachdb/cockroach/blob/b62647f45796a09b216b477bbbbe4fa960daa7d9/pkg/server/application_api/sql_stats_test.go#L626)):*
> ```Go
>     for _, respStatement := range resp.Statements {
> 			// Only consider statements that were successfully executed by the test app.
> 			if respStatement.Key.KeyData.App == testAppName && !respStatement.Key.KeyData.Failed {
> ```

Please add a note of why the success check is necessary. That way if someone in the future is looking at the test they can see automatic retries are the reason.
___
*[`pkg/server/application_api/sql_stats_test.go` line 633 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/109381#-NcxWEvT0FgbPMYhqDVA:-NcxWEvT0FgbPMYhqDVB:bl5ap4h) ([raw file](https://github.com/cockroachdb/cockroach/blob/b62647f45796a09b216b477bbbbe4fa960daa7d9/pkg/server/application_api/sql_stats_test.go#L633)):*
> ```Go
> 		for respQuery, expectedData := range expectedStatementStatsMap {
> 			respStatement, exists := actualResponseStatsMap[respQuery]
> 			if !exists {
> ```

nit: require.True
___
*[`pkg/server/application_api/sql_stats_test.go` line 642 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/109381#-NcxTD1xAoCwiXZctJVw:-NcxWUvM2-rlLqeif781:b2sloh0) ([raw file](https://github.com/cockroachdb/cockroach/blob/b62647f45796a09b216b477bbbbe4fa960daa7d9/pkg/server/application_api/sql_stats_test.go#L642)):*
<details><summary><i>Previously, gtr (Gerardo Torres Castro) wrote…</i></summary><blockquote>

I noticed that I'm currently marshalling to JSON (an expensive operation) irrespective of whether the expected data matches the actual data. Ideally, we should only marshal when there's a discrepancy between the expected and actual data. Outside of using a verbose `if expectedData.fullScan != actualFullScan || expectedData.FullScan != ...`, I'm uncertain about alternative approaches. I believe the current method should be fine, but I thought it was worth highlighting.
</blockquote></details>

This is a test so deserializing a single JSON object shouldn't be an issue. If you wanted to avoid it you could use a func to make it lazy. 

```go
getStmtJsonString := func(){
    return responseToJSON(respStatement)
}
```

**Comment by j82w** [comment]
*[`pkg/server/application_api/sql_stats_test.go` line 642 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/109381#-NcxTD1xAoCwiXZctJVw:-NcxYLcOBkKSdGrH-PGf:becn365) ([raw file](https://github.com/cockroachdb/cockroach/blob/b62647f45796a09b216b477bbbbe4fa960daa7d9/pkg/server/application_api/sql_stats_test.go#L642)):*
<details><summary><i>Previously, j82w (Jake) wrote…</i></summary><blockquote>

This is a test so deserializing a single JSON object shouldn't be an issue. If you wanted to avoid it you could use a func to make it lazy. 

```go
getStmtJsonString := func(){
    return responseToJSON(respStatement)
}
```
</blockquote></details>

Ignore my func suggestion. The require doesn't take a func, so it will just get evaluated for each call instead of just once.

**Review by gtr — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/109381)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @j82w and @xinhaoz)

___
*[`pkg/server/combined_statement_stats.go` line 798 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/109381#-NcxVP67AO3nFycp2jFS:-Ncy8a5I42BrjEiTeDnD:b-u0ulj3) ([raw file](https://github.com/cockroachdb/cockroach/blob/b62647f45796a09b216b477bbbbe4fa960daa7d9/pkg/server/combined_statement_stats.go#L798)):*
<details><summary><i>Previously, j82w (Jake) wrote…</i></summary><blockquote>

Is this still formatted correctly? Not sure how a JSON string array is converted to a a string.
</blockquote></details>

Fixed. Previously this was resulting in a value like `["db1", "db2"]` now it should just be `db1,db2` which is what was returned before. 

I was wondering if it was possible to do this string array to string conversion in the SQL query above so we could skip the JSON unmarshalling but I wasn't able to find a reliable query. Using `->` we get a JSON datum so I don't think we could have avoided that but let me know what you think.
___
*[`pkg/server/application_api/sql_stats_test.go` line 624 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/109381#-NcxX4UE-ZGz3ufgJ5Os:-NcyA_N0Al9-0x9Asg7f:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/b62647f45796a09b216b477bbbbe4fa960daa7d9/pkg/server/application_api/sql_stats_test.go#L624)):*
<details><summary><i>Previously, j82w (Jake) wrote…</i></summary><blockquote>

nit: fix indents
</blockquote></details>

Done.
___
*[`pkg/server/application_api/sql_stats_test.go` line 626 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/109381#-NcxXTPm8A6YqPn9svk1:-NcyB20A-DXdj0h4Gpsx:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/b62647f45796a09b216b477bbbbe4fa960daa7d9/pkg/server/application_api/sql_stats_test.go#L626)):*
<details><summary><i>Previously, j82w (Jake) wrote…</i></summary><blockquote>

Please add a note of why the success check is necessary. That way if someone in the future is looking at the test they can see automatic retries are the reason.
</blockquote></details>

Done.
___
*[`pkg/server/application_api/sql_stats_test.go` line 633 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/109381#-NcxWEvT0FgbPMYhqDVA:-NcyAgtS0h8oZuGdKa1H:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/b62647f45796a09b216b477bbbbe4fa960daa7d9/pkg/server/application_api/sql_stats_test.go#L633)):*
<details><summary><i>Previously, j82w (Jake) wrote…</i></summary><blockquote>

nit: require.True
</blockquote></details>

Done.
___
*[`pkg/server/application_api/sql_stats_test.go` line 642 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/109381#-NcxTD1xAoCwiXZctJVw:-NcyAhfx3o01J7q-yk9W:b-bxvd9r) ([raw file](https://github.com/cockroachdb/cockroach/blob/b62647f45796a09b216b477bbbbe4fa960daa7d9/pkg/server/application_api/sql_stats_test.go#L642)):*
<details><summary><i>Previously, j82w (Jake) wrote…</i></summary><blockquote>

Ignore my func suggestion. The require doesn't take a func, so it will just get evaluated for each call instead of just once.
</blockquote></details>

Ah yes I also wanted to use the lazy func :frowning_face:. But SGTM.

**Review by j82w — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/109381)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ericharmeling, @gtr, and @xinhaoz)

___
*[`-- commits` line 12 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/109381#-NcyUSHH0lIAJCGbDLVK):*
This fixes a bug customers have reported so there should be a release note.
___
*[`pkg/server/application_api/sql_stats_test.go` line 510 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/109381#-Ncya02N-LoWFyhserrR:-Ncya02N-LoWFyhserrS:b-abb1ym) ([raw file](https://github.com/cockroachdb/cockroach/blob/308830185946919ca9331c2e134190105e6e0545/pkg/server/application_api/sql_stats_test.go#L510)):*
> ```Go
> 	additionalTimeout := 0 * time.Second
> 	if skip.Stress() {
> 		additionalTimeout = 30 * time.Second
> ```

Can there be a const for the stress timeout value? I noticed some tests seem to be using 30 and others 45 seconds.

**Review by gtr — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/109381)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ericharmeling, @j82w, and @xinhaoz)

___
*[`-- commits` line 12 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/109381#-NcyUSHH0lIAJCGbDLVK):*
<details><summary><i>Previously, j82w (Jake) wrote…</i></summary><blockquote>

This fixes a bug customers have reported so there should be a release note.
</blockquote></details>

Done.
___
*[`pkg/server/combined_statement_stats.go` line 798 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/109381#-NcxVP67AO3nFycp2jFS:-Nd0Y5KAEE7vlsaXquOY:bp7td38) ([raw file](https://github.com/cockroachdb/cockroach/blob/b62647f45796a09b216b477bbbbe4fa960daa7d9/pkg/server/combined_statement_stats.go#L798)):*
<details><summary><i>Previously, gtr (Gerardo Torres Castro) wrote…</i></summary><blockquote>

Fixed. Previously this was resulting in a value like `["db1", "db2"]` now it should just be `db1,db2` which is what was returned before. 

I was wondering if it was possible to do this string array to string conversion in the SQL query above so we could skip the JSON unmarshalling but I wasn't able to find a reliable query. Using `->` we get a JSON datum so I don't think we could have avoided that but let me know what you think.
</blockquote></details>

Following up on this: the following query worked for me:
```
defaultdb> SELECT string_agg(elem::text, ',') AS databases
           FROM json_array_elements_text(('{"db": ["mo\"vr","tb2"], "db2": ["movr","tb2"]}'::jsonb)->'db') AS elem;

  databases
-------------
  mo"vr,tb2
(1 row)
```
The queries have been updated.
___
*[`pkg/server/application_api/sql_stats_test.go` line 510 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/109381#-Ncya02N-LoWFyhserrR:-Nd0JshZ28dGw7Mgrm9w:b-nqdt8z) ([raw file](https://github.com/cockroachdb/cockroach/blob/308830185946919ca9331c2e134190105e6e0545/pkg/server/application_api/sql_stats_test.go#L510)):*
<details><summary><i>Previously, j82w (Jake) wrote…</i></summary><blockquote>

Can there be a const for the stress timeout value? I noticed some tests seem to be using 30 and others 45 seconds.
</blockquote></details>

Done. Also for that 45 second timeout, the test for which I did that times out under stress it seems to be very expensive so I skipped it.

**Review by j82w — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/109381)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ericharmeling, @gtr, and @xinhaoz)

___
*[`-- commits` line 12 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/109381#-NcyUSHH0lIAJCGbDLVK):*
<details><summary><i>Previously, gtr (Gerardo Torres Castro) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Looking at the PR it doesn't actually fix anything for users so the release note should be none like you originally had it. Can you revert it?
___
*[`pkg/server/application_api/sql_stats_test.go` line 692 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/109381#-Nd0s1e38cbq33r0bnuu:-Nd0s1e38cbq33r0bnuv:b-wjs8l2) ([raw file](https://github.com/cockroachdb/cockroach/blob/ab025e7767fdd018d3be7b81551392ee095ae231/pkg/server/application_api/sql_stats_test.go#L692)):*
> ```Go
> 
> 	// Resource-intensive test, times out under stress.
> 	skip.UnderStressRace(t, "expensive tests")
> ```

Why is this still skipped for stress race?

**Review by gtr — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/109381)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ericharmeling, @j82w, and @xinhaoz)

___
*[`-- commits` line 12 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/109381#-NcyUSHH0lIAJCGbDLVK):*
<details><summary><i>Previously, j82w (Jake) wrote…</i></summary><blockquote>

Looking at the PR it doesn't actually fix anything for users so the release note should be none like you originally had it. Can you revert it?
</blockquote></details>

Done.
___
*[`pkg/server/application_api/sql_stats_test.go` line 692 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/109381#-Nd0s1e38cbq33r0bnuu:-Nd113VfBH-no0LrA4kq:b-est9u1) ([raw file](https://github.com/cockroachdb/cockroach/blob/ab025e7767fdd018d3be7b81551392ee095ae231/pkg/server/application_api/sql_stats_test.go#L692)):*
<details><summary><i>Previously, j82w (Jake) wrote…</i></summary><blockquote>

Why is this still skipped for stress race?
</blockquote></details>

This specific test continues to time out regardless of any timeout extensions for the http client. A related test, `TestStatusAPIStatementDetails`, has also been skipped and interestingly, it queries the `stmtdetails` endpoint 10 times. This test queries the `combinedStmts` endpoint 9 times. It seems the sheer number of endpoint hits may contribute to the timeouts, as other non-skipped tests only access it between 1-4 times.

I'm open to increasing the timeout for this test specifically to 45s but let me know what you think.

**Review by j82w — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/109381#-:-Nd1M8-p5o9Qix-3_KIq:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ericharmeling and @xinhaoz)

**Comment by gtr** [comment]
TFTR!
bors r+
