### PR TITLE
sql: various enum improvements

### LINKED ISSUE #49404: sql: failing to create an enum from a physical representation should error rather than panic
We currently panic, but shouldn't.

### PR DESCRIPTION
**Pull request by rohany**
See individual commits for details.

Fixes #49404.

### CODE REVIEW

File: pkg/sql/logictest/testdata/logic_test/enums [hunk 1]
```diff
@@ -359,3 +359,16 @@ query T
 SELECT x FROM greeting_stats
 ----
 hi
+
+# Test that we can cast from enum to bytes.
+# Use a singleton enum so that the bytes encoding is simple.
```
Comment (jordanlewis) [inline pkg/sql/logictest/testdata/logic_test/enums:364]: Isn't this testing that you can cast from bytes to enum, not the opposite? We should have a test of the opposite direction too, unless I'm missing something.

Comment (rohany) [reply pkg/sql/logictest/testdata/logic_test/enums:364]: Woops, I had this backwards. I'm not sure if I want to expose casting from enum to bytes. I want to use it just internally, but I guess there isn't really a harm?

Comment (otan) [reply pkg/sql/logictest/testdata/logic_test/enums:364]: does psql support bytes to enum or vice versa?

Comment (rohany) [reply pkg/sql/logictest/testdata/logic_test/enums:364]: no, this is just for our internal representation, since we use bytes.

File: pkg/sql/sem/tree/datum.go [hunk 2]
```diff
@@ -3844,54 +3847,82 @@ func (d *DEnum) Compare(ctx *EvalContext, other Datum) int {
...
 func (d *DEnum) Next(ctx *EvalContext) (Datum, bool) {
-	idx := d.EnumTyp.EnumGetIdxOfPhysical(d.PhysicalRep)
-	physReps := d.EnumTyp.TypeMeta.EnumData.PhysicalRepresentations
-	if idx == len(physReps)-1 {
+	idx, err := d.EnumTyp.EnumGetIdxOfPhysical(d.PhysicalRep)
+	if err != nil {
+		panic(err)
+	}
+	enumData := d.EnumTyp.TypeMeta.EnumData
+	if idx == len(enumData.PhysicalRepresentations)-1 {
```
Comment (otan) [inline pkg/sql/sem/tree/datum.go:3876]: nit, maybe...: this should be `idx + 1 >= len(enumData.PhysicalRepresentations)` for safety i reckon, in case we get idx == 0 and len(enumData.PhysicalRepresentations) == 0 (may be impossible but you never know).

Comment (otan) [reply pkg/sql/sem/tree/datum.go:3876]: actuallly, meh....

File: pkg/sql/sem/tree/datum.go [hunk 3]
```diff
@@ -3844,54 +3847,82 @@ func (d *DEnum) Compare(ctx *EvalContext, other Datum) int {
...
+	}
+	return idx == len(physReps)-1
 }
 
 // IsMin implements the Datum interface.
 func (d *DEnum) IsMin(_ *EvalContext) bool {
-	return d.EnumTyp.EnumGetIdxOfPhysical(d.PhysicalRep) == 0
+	idx, err := d.EnumTyp.EnumGetIdxOfPhysical(d.PhysicalRep)
+	if err != nil {
+		panic(err)
```
Comment (otan) [inline pkg/sql/sem/tree/datum.go:3927]: for all these `panic(err)`, should we be returning `false` instead?

**Review by otan — APPROVED** [review]

File: pkg/sql/sem/tree/datum.go (hunk 3 above)
Comment (rohany) [reply pkg/sql/sem/tree/datum.go:3927]: I'm not sure, it seems like a bad state to be in for errors to get returned there, so just returning false seems disingenuous. I don't want to plumb errors out of those datum functions either though.

**Comment by rohany** [comment]
TFTR

bors r+
