### PR TITLE
server: fix clock monotonicity setup

### LINKED ISSUE #137331: roachtest: clock/monotonic/persistent failed
roachtest.clock/monotonic/persistent [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/18147340?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/18147340?buildTab=artifacts#/clock/monotonic/persistent) on master @ [e8ee6f574ddf1fce1a4cb53f392c5a9baf633b76](https://github.com/cockroachdb/cockroach/commits/e8ee6f574ddf1fce1a4cb53f392c5a9baf633b76):

```
(test_runner.go:1482).func1: failed during post test assertions (see test-post-assertions.log): dial tcp 34.148.5.94:26257: connect: connection refused
test artifacts and logs in: /artifacts/clock/monotonic/persistent/run_1
```

Parameters:
 - <code>arch=amd64</code>
 - <code>cloud=gce</code>
 - <code>coverageBuild=false</code>
 - <code>cpu=4</code>
 - <code>encrypted=false</code>
 - <code>metamorphicLeases=epoch</code>
 - <code>runtimeAssertionsBuild=false</code>
 - <code>ssd=0</code>
<details><summary>Help</summary>
<p>

See: [roachtest README](https://github.com/cockroachdb/cockroach/blob/master/pkg/cmd/roachtest/README.md)

See: [How To Investigate \(internal\)](https://cockroachlabs.atlassian.net/l/c/SSSBr8c7)

See: [Grafana](https://go.crdb.dev/roachtest-grafana/teamcity-18147340/clock-monotonic-persistent/1733997732162/1733997977427)

</p>
</details>
<details><summary>Same failure on other branches</summary>
<p>

- #136395 roachtest: clock/monotonic/persistent failed [C-bug C-test-failure O-roachtest O-robot T-kv branch-release-24.3 release-blocker]
</p>
</details>
/cc @cockroachdb/kv-triage
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*clock/monotonic/persistent.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/bazci/githubpost/issues)

</sub>

Jira issue: CRDB-45527

### PR DESCRIPTION
**Pull request by tbg**
Prior to this PR, the last line in the bash script below would find that the server had crashed with

> wall time X is not allowed to be greater than upper bound of Y.

The reason is that upon the second start, the node would persist a "temporary" `now()+5s` upper bound but then fail to update it.

This PR ensures that the update loop starts unconditionally and maintains (i.e. either updates or erases) the HLC upper bound. This likely fixes other crashes of the same sort when the cluster setting is changed while a node is going down (in which case it's conceivable that a node would boot with a persisted upper bound but without a desire to keep maintaining time timestamp).

```

roachprod wipe local
roachprod start local:1
roachprod sql local:1 -- -e "SET CLUSTER SETTING server.clock.persist_upper_bound_interval = '500ms'"
sleep 5
roachprod stop local:1
roachprod start local:1
sleep 10
roachprod sql local:1 -- -e "SELECT 1"
```

With the fix, after restarting, the server logs

> persisting HLC upper bound is enabled [every 0.50s]

a second time (the first time being when the setting is set). Without the fix, we see this log line only once, not to mention the crash.

Fixes #137331.

Epic: none
Release note (bug fix): a problem was fixed which could cause nodes running under the `server.clock.persist_upper_bound_interval` cluster setting to crash after restarts with error "wall time <timestamp> is not allowed to be greater than upper bound of <timestamp>". This problem would occur frequently in single-node clusters, but can not be ruled out on multi-node clusters. It is now fixed in both.

### CODE REVIEW

File: pkg/server/clock_monotonicity.go [hunk 1]
```diff
@@ -187,16 +186,19 @@ func periodicallyPersistHLCUpperBound(
 
 	for {
 		select {
-		case persistInterval, ok = <-persistHLCUpperBoundIntervalCh:
```
Comment (tbg) [inline pkg/server/clock_monotonicity.go:190]: NB: this channel is never closed (we have a dedicated stop channel), so I removed the `ok` variable.

File: pkg/server/clock_monotonicity.go [hunk 2]
```diff
@@ -187,16 +186,19 @@ func periodicallyPersistHLCUpperBound(
...
+				continue
 			}
+			persistInterval = updatedPersistInterval
 
+			ticker.Stop()
 			if persistInterval > 0 {
 				ticker = tickerFn(persistInterval)
 				persistHLCUpperBound()
-				log.Ops.Info(context.Background(), "persisting HLC upper bound is enabled")
+				log.Ops.Infof(context.Background(), "persisting HLC upper bound is enabled [every %.2fs]",
```
Comment (stevendanna) [inline pkg/server/clock_monotonicity.go:200]: Not for this PR, but I think we could flow workerCtx through to this function to have log tags.

**Review by stevendanna — APPROVED** [review]
Looks reasonable to me.

The `tickerFn` just for testing is a little unfortunate.

**Comment by tbg** [comment]
bors r+
TFTR!

**Comment by tbg** [comment]
blathers backport 24.3
