### PR TITLE
bench/rttanalysis: shard TestBenchmarkExpectation to avoid timeouts

### LINKED ISSUE #148384: bench/rttanalysis: TestBenchmarkExpectation failed [timeout]
bench/rttanalysis.TestBenchmarkExpectation [failed](https://mesolite.cluster.engflow.com/invocations/default/c4558e64-3bc6-4a8c-a360-21efdc7fb749?testReportRun=1&testReportShard=1&testReportAttempt=1#targets-Ly9wa2cvYmVuY2gvcnR0YW5hbHlzaXM6cnR0YW5hbHlzaXNfdGVzdA==) on master @ [352b1d2522799537674493e1b4775b259ab0c725](https://github.com/cockroachdb/cockroach/commits/352b1d2522799537674493e1b4775b259ab0c725):

```
created by golang.org/x/sync/errgroup.(*Group).Go in goroutine 937324
	external/org_golang_x_sync/errgroup/errgroup.go:75 +0x96
=== RUN   TestBenchmarkExpectation/Truncate/truncate_1_column_2_rows
		TestBenchmarkExpectation/Truncate/truncate_1_column_2_rows (15m0s)
=== RUN   TestBenchmarkExpectation/Truncate/truncate_2_column_1_rows
		TestBenchmarkExpectation/Truncate/truncate_2_column_1_rows (15m0s)
=== RUN   TestBenchmarkExpectation/AlterTableAddForeignKey/alter_table_add_1_foreign_key
		TestBenchmarkExpectation/AlterTableAddForeignKey/alter_table_add_1_foreign_key (15m0s)
=== RUN   TestBenchmarkExpectation/AlterTableAddForeignKey/alter_table_add_2_foreign_keys
		TestBenchmarkExpectation/AlterTableAddForeignKey/alter_table_add_2_foreign_keys (15m0s)
=== RUN   TestBenchmarkExpectation/AlterTableDropConstraint/alter_table_drop_1_check_constraint
		TestBenchmarkExpectation/AlterTableDropConstraint/alter_table_drop_1_check_constraint (15m0s)
=== RUN   TestBenchmarkExpectation/AlterTableAddForeignKey/alter_table_add_3_foreign_keys
		TestBenchmarkExpectation/AlterTableAddForeignKey/alter_table_add_3_foreign_keys (15m0s)
=== RUN   TestBenchmarkExpectation/SystemDatabaseQueries/select_system.users_without_schema_Name
		TestBenchmarkExpectation/SystemDatabaseQueries/select_system.users_without_schema_Name (15m0s)
=== RUN   TestBenchmarkExpectation/AlterTableAddCheckConstraint/alter_table_add_2_check_constraints
		TestBenchmarkExpectation/AlterTableAddCheckConstraint/alter_table_add_2_check_constraints (15m0s)
=== RUN   TestBenchmarkExpectation/AlterTableConfigureZone/alter_table_configure_zone_7_replicas_
		TestBenchmarkExpectation/AlterTableConfigureZone/alter_table_configure_zone_7_replicas_ (15m0s)
=== RUN   TestBenchmarkExpectation/GenerateObjects/generate_50000_tables
		TestBenchmarkExpectation/GenerateObjects/generate_50000_tables (15m0s)
=== RUN   TestBenchmarkExpectation/GenerateObjects/generate_1000_tables_-_this_test_should_use_the_same_number_of_RTTs_as_for_10_tables
		TestBenchmarkExpectation/GenerateObjects/generate_1000_tables_-_this_test_should_use_the_same_number_of_RTTs_as_for_10_tables (15m0s)
=== RUN   TestBenchmarkExpectation/AlterTableAddForeignKey/alter_table_add_foreign_key_with_3_columns
		TestBenchmarkExpectation/AlterTableAddForeignKey/alter_table_add_foreign_key_with_3_columns (15m0s)
=== RUN   TestBenchmarkExpectation/AlterTableSplit/alter_table_split_at_2_values
		TestBenchmarkExpectation/AlterTableSplit/alter_table_split_at_2_values (15m0s)
=== RUN   TestBenchmarkExpectation/SystemDatabaseQueries
		TestBenchmarkExpectation/SystemDatabaseQueries (15m0s)
=== RUN   TestBenchmarkExpectation/Truncate/truncate_1_column_1_row
		TestBenchmarkExpectation/Truncate/truncate_1_column_1_row (15m0s)
=== RUN   TestBenchmarkExpectation/AlterTableSplit
		TestBenchmarkExpectation/AlterTableSplit (15m0s)
=== RUN   TestBenchmarkExpectation/DropSequence
		TestBenchmarkExpectation/DropSequence (15m0s)
=== RUN   TestBenchmarkExpectation/GenerateObjects/generate_100_tables_from_template
		TestBenchmarkExpectation/GenerateObjects/generate_100_tables_from_template (15m0s)
=== RUN   TestBenchmarkExpectation/DropView/drop_1_view
		TestBenchmarkExpectation/DropView/drop_1_view (15m0s)
=== RUN   TestBenchmarkExpectation/SystemDatabaseQueries/select_system.users_with_schema_Name
		TestBenchmarkExpectation/SystemDatabaseQueries/select_system.users_with_schema_Name (15m0s)
=== RUN   TestBenchmarkExpectation/Truncate
		TestBenchmarkExpectation/Truncate (15m0s)
=== RUN   TestBenchmarkExpectation/AlterTableAddForeignKey
		TestBenchmarkExpectation/AlterTableAddForeignKey (15m0s)
=== RUN   TestBenchmarkExpectation/AlterTableConfigureZone
		TestBenchmarkExpectation/AlterTableConfigureZone (15m0s)
=== RUN   TestBenchmarkExpectation/DropSequence/drop_1_sequence
		TestBenchmarkExpectation/DropSequence/drop_1_sequence (15m0s)
```

Parameters:
 - <code>attempt=1</code>
 - <code>run=1</code>
 - <code>shard=1</code>
<details><summary>Help</summary>
<p>

See also: [How To Investigate a Go Test Failure \(internal\)](https://cockroachlabs.atlassian.net/l/c/HgfXfJgM)
</p>
</details>
<details><summary>Same failure on other branches</summary>
<p>

- #126750 bench/rttanalysis: TestBenchmarkExpectation failed [Jobs/jobs_page_type_filtered_no_matches] [A-jobs C-test-failure O-robot P-3 T-jobs branch-release-24.1]
</p>
</details>
/cc @cockroachdb/sql-foundations
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*TestBenchmarkExpectation.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/bazci/githubpost/issues)

</sub>

Jira issue: CRDB-51588

### PR DESCRIPTION
**Pull request by spilchen**
The TestBenchmarkExpectation benchmark has been frequently timing out after 15 minutes.  This appears to be caused by slow CI machines rather than issues with the test logic itself.

To address this, the test is now split into four shards. Each shard is executed separately and receives the full 15-minute timeout budget. This should reduce the likelihood of timeout test failures.

Fixes #148384

Release note: none
Epic: none

### CODE REVIEW

**Review by rafiss — APPROVED** [review]
i like this idea! just had minor comments

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/153721#-:-O_TXBwe7xmDnGcQFJsB:b1iel7h)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @spilchen)

___
*[`pkg/bench/rttanalysis/validate_benchmark_data_test.go` line 14 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/153721#-O_TX4MZDh577cqjlqHa:-O_TX4MZDh577cqjlqHb:b-3iqu4b) ([raw file](https://github.com/cockroachdb/cockroach/blob/eed425db4cbd8a0524a07d9ca43bc0ccbfd089f1/pkg/bench/rttanalysis/validate_benchmark_data_test.go#L14)):*
> ```Go
> 
> func TestBenchmarkExpectationShard1(t *testing.T) {
> 	reg.RunExpectations(t, 1, 4)
> ```

super nit: let's make a `const` for shardCount=4
___
*[`pkg/bench/rttanalysis/registry.go` line 84 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/153721#-O_TWc6R7Vh0_yfEQo8U:-O_TWc6R7Vh0_yfEQo8V:b-c2n26l) ([raw file](https://github.com/cockroachdb/cockroach/blob/eed425db4cbd8a0524a07d9ca43bc0ccbfd089f1/pkg/bench/rttanalysis/registry.go#L84)):*
> ```Go
> 		// Distribute test groups across shards using hash-based assignment
> 		for groupName, testCases := range r.r {
> 			h := fnv32Hash(groupName)
> ```

i'm curious if there are enough names in the registry to actually get an even number of tests across the shards? would we be able to get away with using round-robin here? (i wasn't sure why we needed to have consistent shard assignment)

File: pkg/bench/rttanalysis/registry.go [hunk 1]
```diff
@@ -53,13 +56,48 @@ func (r *Registry) Run(b *testing.B) {
 //
 // It takes a long time and thus is skipped under stress, race
 // and short.
-func (r *Registry) RunExpectations(t *testing.T) {
+//
+// When shard and totalShards are provided (> 1), only a subset of benchmarks
+// assigned to the specific shard will be run, enabling parallel execution.
+func (r *Registry) RunExpectations(t *testing.T, shard, totalShards int) {
+	defer jobs.TestingSetIDsToIgnore(map[jobspb.JobID]struct{}{3001: {}, 3002: {}})()
 	skip.UnderStress(t)
```
Comment (rickystewart) [inline pkg/bench/rttanalysis/registry.go]: Nit: `skip.UnderDuress()` is a tidier way to skip in many of these circumstances (race, deadlock, stress). You will have to keep `UnderShort()` though.

File: pkg/bench/rttanalysis/validate_benchmark_data_test.go [hunk 2]
```diff
@@ -5,14 +5,23 @@
...
 
-import (
-	"testing"
+import "testing"
 
-	"github.com/cockroachdb/cockroach/pkg/jobs"
-	"github.com/cockroachdb/cockroach/pkg/jobs/jobspb"
-)
+// NOTE: If you change the number of shards, you must also update the
+// shard_count in BUILD.bazel to match.
```
Comment (rickystewart) [inline pkg/bench/rttanalysis/validate_benchmark_data_test.go:16]: Nit, very optional: you can check the environment variable `TEST_TOTAL_SHARDS`. If it's set, it's the total number of shards (4, in this case). You can add an `init`-time assert to ensure that it's the value you expect it to be. Something like this (note, I have not tested this or made sure it compiles):

```
var _: int = func() int {
    totalShardsStr := os.GetEnv("TEST_TOTAL_SHARDS")
    var totalShards int
    if totalShardsStr != "" {
        totalShards = strconv.Atoi(totalShardsStr)
    }
    if totalShards != 0 {
        if totalShards != EXPECTED_TOTAL_SHARDS {
             panic("update shard_count in pkg/bench/rttanalysis/BUILD.bazel")
        }
    }
    return 0
}()
```

File: pkg/ccl/benchccl/rttanalysisccl/multi_region_bench_test.go [hunk 3]
```diff
@@ -55,7 +55,7 @@ var reg = rttanalysis.NewRegistry(numNodes, rttanalysis.MakeClusterConstructor(f
 	}
 }))
 
-func TestBenchmarkExpectation(t *testing.T) { reg.RunExpectations(t) }
+func TestBenchmarkExpectation(t *testing.T) { reg.RunExpectations(t, 1, 1) }
```
Comment (rickystewart) [inline pkg/ccl/benchccl/rttanalysisccl/multi_region_bench_test.go]: Nit, optional: if you keep `RunExpectations()` and have it delegate to a new function `RunExpectationsSharded(t, 1, 1)`, then you don't have to change this call. Up to you.

**Review by rickystewart — APPROVED** [review]
All of my comments are nits and could be ignored.

File: pkg/bench/rttanalysis/validate_benchmark_data_test.go (hunk 2 above)
Comment (spilchen) [reply pkg/bench/rttanalysis/validate_benchmark_data_test.go:16]: Good idea

**Review by spilchen — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/153721)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @rafiss)

___
*[`pkg/bench/rttanalysis/registry.go` line 84 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/153721#-O_TWc6R7Vh0_yfEQo8U:-O_Wv_93E-jXF7toPLEQ:b-qdipmm) ([raw file](https://github.com/cockroachdb/cockroach/blob/eed425db4cbd8a0524a07d9ca43bc0ccbfd089f1/pkg/bench/rttanalysis/registry.go#L84)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

i'm curious if there are enough names in the registry to actually get an even number of tests across the shards? would we be able to get away with using round-robin here? (i wasn't sure why we needed to have consistent shard assignment)
</blockquote></details>

There are 31 names in the registry. With the hash assignment, each shard ran: 6, 10, 4, 10. Not too bad, but the 3rd shard was under represented. It seems like the names in the registry are fairly stable, so I don't know if there is a need for consistent hashing. I changed to the round robin approach you mentioned. 
___
*[`pkg/bench/rttanalysis/validate_benchmark_data_test.go` line 14 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/153721#-O_TX4MZDh577cqjlqHa:-O_Wv0Wp-kWNVegKYcfy:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/eed425db4cbd8a0524a07d9ca43bc0ccbfd089f1/pkg/bench/rttanalysis/validate_benchmark_data_test.go#L14)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

super nit: let's make a `const` for shardCount=4
</blockquote></details>

Done.

**Comment by rafiss** [comment]
blathers backport 25.3

backporting to resolve #152227
