### PR TITLE
sql: disallow GRANT/REVOKE on system tables

### LINKED ISSUE #43842: sql: GRANT mistakenly allowed on system.lease, causing deadlocks
**Describe the problem**
We all know that there are many system tables in the database.But I've found that programs get stuck when I try to grant to certain system tables

**To Reproduce**
Start the database and enter the statement:
      GRANT GRANT, SELECT, INSERT, DELETE, UPDATE on system.lease to testuser
If possible, provide steps to reproduce the behavior:

1. Set up CockroachDB cluster
2. Send SQL statement: GRANT GRANT, SELECT, INSERT, DELETE, UPDATE on system.lease to testuser
3. We'll find that the system is stuck

**Expected behavior**
Returns a sign of success or failure in empowerment

**Environment:**
•CockroachDB version [19.2.0]
•Server OS: [Linux]
•Client app [cockroach sql]

### PR DESCRIPTION
**Pull request by RichardJCai**
Disallow GRANT/REVOKE operations on system objects to avoid potential
deadlocks related to version bumps.

Release justification: bug fix
Release note (sql change): Disallow `GRANT/REVOKE` operations on system
tables.
Release note (bug fix): Fix a bug where `GRANT/REVOKE` on the
`system.lease` table would result in a deadlock.

Fixes #43842

Picking up PR from here:
https://github.com/cockroachdb/cockroach/pull/53683

It seems like the `system.comments` migration that used the GRANT/REVOKE is gone now (comment here: https://github.com/cockroachdb/cockroach/pull/53683#issuecomment-683952999)

### CODE REVIEW

**Review by rafiss — APPROVED** [review]

File: pkg/sql/grant_revoke.go [hunk 1]
```diff
@@ -185,6 +188,15 @@ func (n *changePrivilegesNode) startExec(params runParams) error {
 	// we update them in KV below.
 	b := p.txn.NewBatch()
 	for _, descriptor := range descriptors {
+		// Disallow privilege changes on system objects. For more context, see #43842.
+		op := "REVOKE"
+		if n.isGrant {
+			op = "GRANT"
+		}
+		if descriptor.GetID() < keys.MinUserDescID {
```
Comment (ajwerner) [inline pkg/sql/grant_revoke.go:196]: I'd prefer if you checked the parent ID

**Review by ajwerner — APPROVED** [review]

File: pkg/sql/grant_revoke.go (hunk 1 above)
Comment (RichardJCai) [reply pkg/sql/grant_revoke.go:196]: Checking ParentID would fail for databases since databaseDesc.GetParentID() always returns 0.

**Comment by RichardJCai** [comment]
Thanks for the reviews! 
bors r+
