### PR TITLE
colflow,logictest: adjust a few tests for big endian due to hash computation difference

### LINKED ISSUE #146006: pkg/sql/opt/exec/execbuilder/tests/5node: tests fail on `s390x`
**[How to gain access to an s390x machine for testing (Internal link)](https://cockroachlabs.atlassian.net/wiki/spaces/devinf/pages/4536467683/Reproducing+an+issue+on+s390x)**

The following tests fail on `s390x`:

* [TestExecBuild_dist_vectorize](https://gist.github.com/rickystewart/613902d5fdff5981f206676b35f95e5e)
* [TestExecBuild_explain_analyze_plans](https://gist.github.com/rickystewart/cc75f6dfe9b719febc8f623c62c24a45)

Epic: CRDB-21133

Jira issue: CRDB-50324

### LINKED ISSUE #146108: colflow: `TestHashRouterComputesDestination` fails on `s390x`
`//pkg/sql/colflow:colflow_test` fails on `s390x` with the error:

```
--- FAIL: TestHashRouterComputesDestination (0.00s)
    test_log_scope.go:165: test logs captured to: /tmp/cockroach/_tmp/290907cbe0afac996ee165ea475a0862/logTestHashRouterComputesDestinatio\
n3587856378
    test_log_scope.go:76: use -show-logs to present logs inline
    routers_test.go:766: num val slices differ at output 0, expected: [273 252 287 212] actual: [238 260 259 267]
    panic.go:635: -- test log scope end --
```

(Repro instructions are forthcoming, I will update here when I have them)

Epic: CRDB-21133

### PR DESCRIPTION
**Pull request by yuzefovich**
**colflow: adjust TestHashRouterComputesDestination for big endian**

Also add a helper to `util/system` package to expose whether we're
running on a big endian system. (Go doesn't seem to expose this
information explicitly.)

Fixes: #146108.

**logictest: adjust a couple DistSQL tests for big endian**

Big endian systems have different hash computation, so a handful of
EXPLAIN ANALYZE (DISTSQL) tests need to be special-cases. This commit
does that for `dist_vectorize` and `explain_analyze_plans`. New `skipif`
options (`bigendian` and `littleendian`) are introduced to accommodate
this. It results in quite a bit of duplication in the expected output,
but EXPLAIN ANALYZE must be a top-level statement so we cannot check
just the annotated DistSQL plan unfortunately.

Fixes: #146006.

Release note: None

### CODE REVIEW

File: pkg/sql/colflow/routers_test.go [hunk 1]
```diff
@@ -724,6 +725,11 @@ func TestHashRouterComputesDestination(t *testing.T) {
 		valsPushed      = make([]int, numOutputs)
 	)
 
+	if system.BigEndian {
+		// On big endian architectures we expect different distribution.
```
Comment (stevendanna) [inline pkg/sql/colflow/routers_test.go]:
```suggestion
		// On big endian architectures we expect a different distribution.
```

**Review by stevendanna — APPROVED** [review]

**Review by michae2 — APPROVED** [review]
:lgtm: Nice fix! Thanks for jumping through all the hoops to set this up!

I think we need to document somewhere that big-endian systems have a different DistSQL hash function result than little-endian systems, and therefore can't be in the same cluster as little-endian systems. Would you be willing to open an issue and tag it with `docs-known-limitation`?

> Reviewed 4 of 4 files at r1, 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/148765#-:-OTZ9cfnBCHRdr8HHQeb:b9l4zdo)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @yuzefovich)

File: pkg/sql/colflow/routers_test.go (hunk 1 above)
Comment (yuzefovich) [reply pkg/sql/colflow/routers_test.go]: Done.

**Review by yuzefovich — COMMENTED** [review]
Good point, filed #148773.

TFTRs!

bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/148765#-:-OTZD-qj-JJmHd1-gvF-:b-ahk3jy)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @michae2 and @stevendanna)
