### PR TITLE
rangefeed: create catchup iterators eagerly

### LINKED ISSUE #111040: rangefeed: remove catchup iterator creation from processor work loop
Currently iterator creation is deferred to registration step to simplify iterator lifecycle management.
It must be closed if we failed to create rangefeed registration for any reason.

raftMu is held throughout the whole rangefeed request handling op so there's no issue with getting inconsistent view between iterator and events.

By moving iterator creation out of processor work loop, we remove all io dependent operation from scheduler thus removing possibilies of starving neighbour rangefeeds for extended periods of time.
This issue could be particularly bad at startup when multiple rangefeeds start at the same time.

Jira issue: CRDB-31737

Epic CRDB-26372

### LINKED ISSUE #111060: rangefeed: if catchup iterator fails to create processor is stopped
When rangefeed created it can request a catchup iterator creation from underlying store.

Recent changes to interface can cause creation to fail with error. This failure causes processor to stop immediately.

This behaviour is not correct from rangefeed client perspective. Processor can serve multiple clients at the same time and other clients should not be affected by new feed failure. The better approach should be to fail new registration instead.

There's currently no easy way to expose errors like that, what could be done instead is eager creation of iterator. In that case if iterator creation fails, we don't need to create new registration.

Jira issue: CRDB-31745

### PR DESCRIPTION
**Pull request by aliher1911**
Previously, catchup iterators were created in the main rangefeed processor work loop. This is negatively affecting scheduler based processors as this operation could be slow.
This commit makes iterator creation eager, simplifying error handling and making rangefeed times delays lower.

Epic: [CRDB-26372](https://cockroachlabs.atlassian.net/browse/CRDB-26372)

Fixes: #111060
Fixes: #111040

Release note: None

### CODE REVIEW

File: pkg/kv/kvserver/rangefeed/processor.go [hunk 1]
```diff
@@ -330,7 +331,40 @@ type IntentScannerConstructor func() IntentScanner
...
+// CatchupIteratorContainer manages catchup iterator lifecycle in during
+// rangefeed registration creation. Iterator is created by replica under the
+// lock to get a consistent state. Container is the passed to registration.
+// If registration is created successfully, iterator ownership is moved to
+// registration. If registration creation fails on any stage before that,
+// container could be closed to release iterator. Since ownership is moved
+// out of container, it is safe to close it regardless of startup success or
+// failure.
+type CatchupIteratorContainer struct {
+	syncutil.Mutex
```
Comment (miretskiy) [inline pkg/kv/kvserver/rangefeed/processor.go:345]: i'm not sure who we are trying to serialize with.... presumably registration/filter stuff running and racing with some other error encountered elsewhere...

(totally optional/): maybe `type CatchupIteratorContainer atomic.Pointer[CatchUpIterator.`

Get method  is simply swap.

File: pkg/kv/kvserver/rangefeed/processor.go [hunk 2]
```diff
@@ -330,7 +331,40 @@ type IntentScannerConstructor func() IntentScanner
...
+	Iter *CatchUpIterator
+}
+
+// Get moves iterator out of container. Calling Close on container won't close
+// the iterator after that. Safe to call on empty container.
+func (c *CatchupIteratorContainer) Get() (iter *CatchUpIterator) {
```
Comment (miretskiy) [inline pkg/kv/kvserver/rangefeed/processor.go:351]: nit: Maybe rename to Detach() or Move() or Release()?

**Review by miretskiy — COMMENTED** [review]
This is actually quite nice, small and focused.  I just have few nits, but @erikgrinaker should have final approval.

File: pkg/kv/kvserver/rangefeed/processor.go (hunk 1 above)
Comment (aliher1911) [reply pkg/kv/kvserver/rangefeed/processor.go:345]: I love the idea of atomic pointer + swap. I'll change that.

**Review by aliher1911 — COMMENTED** [review]
Let me address the nits real quick!

**Review by miretskiy — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/111045)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @aliher1911 and @erikgrinaker)

**Comment by miretskiy** [comment]
do we have an epic for this?

File: pkg/kv/kvserver/rangefeed/scheduled_processor.go [hunk 3]
```diff
@@ -322,10 +322,7 @@ func (p *ScheduledProcessor) Register(
 		// Construct the catchUpIter before notifying the registration that it
 		// has been registered. Note that if the catchUpScan is never run, then
 		// the iterator constructed here will be closed in disconnect.
-		if err := r.maybeConstructCatchUpIter(); err != nil {
-			r.disconnect(kvpb.NewError(err))
-			return nil
-		}
+		r.maybeConstructCatchUpIter()
```
Comment (erikgrinaker) [inline pkg/kv/kvserver/rangefeed/scheduled_processor.go:325]: This comment and method name is inaccurate: the iterator has already been constructed by the caller at this point. The same goes for a lot of the other related infrastructure which now appears misnamed.

File: pkg/kv/kvserver/rangefeed/processor.go [hunk 4]
```diff
@@ -330,7 +331,41 @@ type IntentScannerConstructor func() IntentScanner
...
+// rangefeed registration creation. Iterator is created by replica under the
+// lock to get a consistent state. Container is then passed to registration.
+// If registration is created successfully, iterator ownership is moved to
+// registration. If registration creation fails on any stage before that,
+// container could be closed to release iterator. Since ownership is moved
+// out of container, it is safe to close it regardless of startup success or
+// failure.
+type CatchUpIteratorContainer struct {
+	iter atomic.Pointer[CatchUpIterator]
+}
```
Comment (erikgrinaker) [inline pkg/kv/kvserver/rangefeed/processor.go:346]: Do we even need all of this synchronization? I think we can move the iterator construction into `registerWithRangefeedRaftMuLocked()` and pass it in directly, letting the registration assume ownership if `Processor.Register()` returns `true`, otherwise we can close the iterator on the failure path.

**Review by erikgrinaker — COMMENTED** [review]
Did you look at the original motivation for plumbing through the constructor in https://github.com/cockroachdb/cockroach/pull/69613? I think this is fine, because all the lifecycle events appear to synchronize with `raftMu`, but I wonder if we're missing something.

**Comment by aliher1911** [comment]
The original PR you mentioned tried to move iterator creation from registration work loop which is guaranteed to run after current raft lock was released and some data might get through. But it was passing a function instead of constructing iterator upfront. Since all possible locks are held while we are waiting for registration I don't see why we can't create iterator upfront other than trying to avoid its creation on failure path.

Container was trying to do the same, but just handling it on error paths might be better. The only difference that it was handled implicitly by defer and someone didn't start using the iterator.

Moving contruction to `registerWithRangefeedRaftMuLocked()` seems ugly as we will have to pull limiter callbacks down the stack because they are attached to the interator. So passing iterator down and letting `registerWithRangefeedRaftMuLocked()` handle closing seem not uglier than passing callback for the sake of iterator creation to me.

File: pkg/kv/kvserver/replica_rangefeed.go [hunk 5]
```diff
@@ -378,13 +375,19 @@ func (r *Replica) registerWithRangefeedRaftMuLocked(
 	ctx context.Context,
 	span roachpb.RSpan,
 	startTS hlc.Timestamp, // exclusive
-	catchUpIter rangefeed.CatchUpIteratorConstructor,
+	catchUpIter *rangefeed.CatchUpIterator,
```
Comment (erikgrinaker) [inline pkg/kv/kvserver/replica_rangefeed.go:378]: Let's specify the ownership contract in the method comment. Same for `Processor.Register()`.

File: pkg/kv/kvserver/replica_rangefeed.go [hunk 6]
```diff
@@ -378,13 +375,19 @@ func (r *Replica) registerWithRangefeedRaftMuLocked(
...
 	stream rangefeed.Stream,
 	done *future.ErrorFuture,
 ) rangefeed.Processor {
 	defer logSlowRangefeedRegistration(ctx)()
 
+	cleanupCatchUpIter := func() {
+		if catchUpIter != nil {
+			catchUpIter.Close()
+		}
+	}
```
Comment (erikgrinaker) [inline pkg/kv/kvserver/replica_rangefeed.go:389]: We could consider inverting the logic here, using `defer` for this check and instead set `catchUpIter = nil` when we successfully register. That way, we avoid messing up any future error return paths we may add later.

File: pkg/kv/kvserver/rangefeed/registry.go [hunk 7]
```diff
@@ -146,6 +136,7 @@ func newRegistration(
 	}
 	r.mu.Locker = &syncutil.Mutex{}
 	r.mu.caughtUp = true
+	r.mu.catchUpIter = catchUpIter
```
Comment (erikgrinaker) [inline pkg/kv/kvserver/rangefeed/registry.go:139]: The comment for this fields needs updating: it's now constructed on the rangefeed server goroutine, before being passed to the processor.

File: pkg/kv/kvserver/rangefeed/registry_test.go [hunk 8]
```diff
@@ -100,16 +100,16 @@ type testRegistration struct {
 	stream *testStream
 }
 
-func makeCatchUpIteratorConstructor(iter storage.SimpleMVCCIterator) CatchUpIteratorConstructor {
+func makeCatchUpIteratorConstructor(
```
Comment (erikgrinaker) [inline pkg/kv/kvserver/rangefeed/registry_test.go:103]:
```suggestion
func makeCatchUpIterator(
```

**Review by erikgrinaker — APPROVED** [review]
LGTM, thanks for the simplification.

>Moving contruction to registerWithRangefeedRaftMuLocked() seems ugly as we will have to pull limiter callbacks down the stack because they are attached to the interator. So passing iterator down and letting registerWithRangefeedRaftMuLocked() handle closing seem not uglier than passing callback for the sake of iterator creation to me.

Yeah, this is better, thanks.

**Comment by aliher1911** [comment]
bors r=erikgrinaker
