### PR TITLE
decommission: retry on errors for AllocatorCheckRange

### LINKED ISSUE #156849: roachtest: replicagc-changed-peers/restart=false failed [racing snapshots during decommission]
**Note:** This build has runtime assertions enabled. If the same failure was hit in a run without assertions enabled, there should be a similar failure without this message. If there isn&#39;t one, then this failure is likely due to an assertion violation or (assertion) timeout.

roachtest.replicagc-changed-peers/restart=false [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/20690601?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/20690601?buildTab=artifacts#/replicagc-changed-peers/restart=false) on release-24.3 @ [312bef74c778c17fb77228c22838fb3efd331562](https://github.com/cockroachdb/cockroach/commits/312bef74c778c17fb77228c22838fb3efd331562):

```
(replicagc.go:96).runReplicaGCChangedPeers: COMMAND_PROBLEM: exit status 1
test artifacts and logs in: /artifacts/replicagc-changed-peers/restart=false/run_1
```

Parameters:
 - <code>arch=amd64</code>
 - <code>cloud=gce</code>
 - <code>coverageBuild=false</code>
 - <code>cpu=4</code>
 - <code>encrypted=false</code>
 - <code>fs=ext4</code>
 - <code>localSSD=true</code>
 - <code>runtimeAssertionsBuild=true</code>
 - <code>ssd=0</code>
<details><summary>Help</summary>
<p>

See: [roachtest README](https://github.com/cockroachdb/cockroach/blob/master/pkg/cmd/roachtest/README.md)

See: [How To Investigate \(internal\)](https://cockroachlabs.atlassian.net/l/c/SSSBr8c7)

See: [Grafana](https://go.crdb.dev/roachtest-grafana/teamcity-20690601/replicagc-changed-peers-restart-false/1762262911013/1762263083185)

</p>
</details>
/cc @cockroachdb/kv-triage
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*replicagc-changed-peers/restart=false.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/bazci/githubpost/issues)

</sub>

Jira issue: CRDB-56223

### PR DESCRIPTION
**Pull request by wenyihu6**
Fixes: https://github.com/cockroachdb/cockroach/issues/156849
Release note: decommission pre-check may have failed on transient errors; this
is now fixed with a retry loop.

---

**decommission: retry on errors for AllocatorCheckRange**

Previously, the decommission pre-check would fail for a range if
evalStore.AllocatorCheckRange returned an error. However, transient errors, such
as throttled stores, are only expected to last about 5 seconds
(FailedReservationsTimeout) and can cause the pre-check to fail. This commit
adds a retry loop around AllocatorCheckRange to retry on any errors.

Alternatively, we could check for throttling errors specifically and retry only
on throttling stores, but that would require string or error comparisons, which
complicates the code. So we retry just on all errors here given this only
affects the decommission pre-check.

---

**kv: add TestDecommissionPreCheckRetryThrottledStores**

Previously, we made decommission prechecks retry on errors, since some transient
issues resolve quickly and shouldn’t cause the precheck to fail. This commit
adds a test that verifies the precheck retries when it encounters transient
throttled errors.

### CODE REVIEW

File: pkg/kv/kvserver/store.go [hunk 1]
```diff
@@ -3965,6 +3965,11 @@ func (s *Store) AllocatorCheckRange(
 	collectTraces bool,
 	overrideStorePool storepool.AllocatorStorePool,
 ) (allocatorimpl.AllocatorAction, roachpb.ReplicationTarget, tracingpb.Recording, error) {
+	// Testing knob to inject errors.
+	if injectErr := s.cfg.TestingKnobs.AllocatorCheckRangeInterceptor(); injectErr != nil {
```
Comment (pav-kv) [inline pkg/kv/kvserver/store.go]: Likely need to check nil-ness of this callback.

File: pkg/server/storage_api/decommission_test.go [hunk 2]
```diff
@@ -1050,3 +1051,52 @@ func checkRangeCheckResult(
...
+			},
+		},
+		ReplicationMode: base.ReplicationManual,
+	})
+	defer tc.Stopper().Stop(ctx)
+
+	firstSvr := tc.Server(0)
+
+	scratchKey := tc.ScratchRange(t)
+	scratchDesc := tc.LookupRangeOrFatal(t, scratchKey)
```
Comment (pav-kv) [inline pkg/server/storage_api/decommission_test.go]: `scratchDesc` is unused before it's assigned again in the next line. Can drop this line.

File: pkg/server/storage_api/decommission_test.go [hunk 3]
```diff
@@ -1050,3 +1051,52 @@ func checkRangeCheckResult(
...
+
+	// Add replicas to the scratch range on nodes 2 and 3.
+	scratchDesc = tc.AddVotersOrFatal(t, scratchKey, tc.Target(1), tc.Target(2))
+	require.Len(t, scratchDesc.InternalReplicas, 3)
+
+	// Perform decommission pre-check on node 3. AllocatorCheckRange will fail once due to the injected error, then succeed after retries.
```
Comment (pav-kv) [inline pkg/server/storage_api/decommission_test.go]: Wrap the comment?

File: pkg/server/storage_api/decommission_test.go [hunk 4]
```diff
@@ -1050,3 +1051,52 @@ func checkRangeCheckResult(
...
+// TestDecommissionPreCheckRetryThrottledStores tests that the decommission
+// pre-check retries when it encounters transient throttled errors. Regression
+// test for #156849.
+func TestDecommissionPreCheckRetryThrottledStores(t *testing.T) {
+	defer leaktest.AfterTest(t)()
+	defer log.Scope(t).Close(t)
+
+	ctx := context.Background()
+
+	var shouldReturnError atomic.Bool
```
Comment (pav-kv) [inline pkg/server/storage_api/decommission_test.go]: nit: the bool value is the negation of the name - we return an error iff `shouldReturnError` is false. Consider something like `returnedError`.

File: pkg/server/storage_api/decommission_test.go [hunk 5]
```diff
@@ -1050,3 +1051,52 @@ func checkRangeCheckResult(
...
+	require.Len(t, scratchDesc.InternalReplicas, 3)
+
+	// Perform decommission pre-check on node 3. AllocatorCheckRange will fail once due to the injected error, then succeed after retries.
+	decommissioningNodeIDs := []roachpb.NodeID{tc.Server(2).NodeID()}
+	result, err := firstSvr.DecommissionPreCheck(ctx, decommissioningNodeIDs,
+		true /* strictReadiness */, false /* collectTraces */, 0 /* maxErrors */)
+
+	require.NoError(t, err)
+	require.Greater(t, result.RangesChecked, 0)
+	require.Empty(t, result.RangesNotReady)
```
Comment (pav-kv) [inline pkg/server/storage_api/decommission_test.go:1099]: Should we also check that the atomic bool was set to true?

File: pkg/server/storage_api/decommission_test.go [hunk 6]
```diff
@@ -1050,3 +1051,52 @@ func checkRangeCheckResult(
...
+				Store: &kvserver.StoreTestingKnobs{
+					AllocatorCheckRangeInterceptor: injectError,
+				},
+			},
+		},
+		ReplicationMode: base.ReplicationManual,
+	})
+	defer tc.Stopper().Stop(ctx)
+
+	firstSvr := tc.Server(0)
```
Comment (pav-kv) [inline pkg/server/storage_api/decommission_test.go]: Used once. Could inline.

**Review by pav-kv — APPROVED** [review]

File: pkg/kv/kvserver/store.go (hunk 1 above)
Comment (wenyihu6) [reply pkg/kv/kvserver/store.go]: Good catch, fixed!

File: pkg/server/storage_api/decommission_test.go (hunk 4 above)
Comment (wenyihu6) [reply pkg/server/storage_api/decommission_test.go]: Good point, done.

File: pkg/server/storage_api/decommission_test.go (hunk 6 above)
Comment (wenyihu6) [reply pkg/server/storage_api/decommission_test.go]: Done.

File: pkg/server/storage_api/decommission_test.go (hunk 2 above)
Comment (wenyihu6) [reply pkg/server/storage_api/decommission_test.go]: Removed.

File: pkg/server/storage_api/decommission_test.go (hunk 3 above)
Comment (wenyihu6) [reply pkg/server/storage_api/decommission_test.go]: Done.

File: pkg/server/storage_api/decommission_test.go (hunk 5 above)
Comment (wenyihu6) [reply pkg/server/storage_api/decommission_test.go:1099]: Added.

**Review by wenyihu6 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/157862)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @pav-kv and @tbg)
