### PR TITLE
roachtest: use errors.Join in the monitor

### LINKED ISSUE #127633: roachtest: ycsb/C/nodes=3 failed
roachtest.ycsb/C/nodes=3 [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyAwsBazel/16191038?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyAwsBazel/16191038?buildTab=artifacts#/ycsb/C/nodes=3) on release-24.1.3-rc @ [81c0cda194e1a80e21988ad307d76c14a3a5e164](https://github.com/cockroachdb/cockroach/commits/81c0cda194e1a80e21988ad307d76c14a3a5e164):

```
(cluster.go:2398).Run: context canceled
(monitor.go:154).Wait: monitor failure: monitor user task failed: t.Fatal() was called
test artifacts and logs in: /artifacts/ycsb/C/nodes=3/run_1
```

Parameters:
 - <code>ROACHTEST_arch=amd64</code>
 - <code>ROACHTEST_cloud=aws</code>
 - <code>ROACHTEST_coverageBuild=false</code>
 - <code>ROACHTEST_cpu=8</code>
 - <code>ROACHTEST_encrypted=false</code>
 - <code>ROACHTEST_metamorphicBuild=false</code>
 - <code>ROACHTEST_ssd=0</code>
<details><summary>Help</summary>
<p>

See: [roachtest README](https://github.com/cockroachdb/cockroach/blob/master/pkg/cmd/roachtest/README.md)

See: [How To Investigate \(internal\)](https://cockroachlabs.atlassian.net/l/c/SSSBr8c7)

_Grafana is not yet available for aws clusters_</p>
</details>
/cc @cockroachdb/test-eng
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*ycsb/C/nodes=3.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/bazci/githubpost/issues)
</sub>

Jira issue: CRDB-40522

### PR DESCRIPTION
**Pull request by renatolabs**
This changes roachtest's monitor wrapper to use the `errors.Join` API instead of `errors.CombineErrors` as previously.

The main relevant distinction in this case is that `Join` is the API to use in a multi-error use-case, as is the case here. `CombineErrors`, on the other hand, is used when the secondary error is only relevant during display, for debugging purposes. In other words, it is not possible to reference the secondary error from an opaque `error` reference, making it impossible to detect flakes if the transient error is in a secondary error.

Fixes: #127633

Release note: None

### CODE REVIEW

File: pkg/cmd/roachtest/test_impl_test.go [hunk 1]
```diff
@@ -138,6 +138,22 @@ func Test_failuresMatchingError(t *testing.T) {
 			},
 			want: true,
 		},
+		{
+			name: "an error contains the expected error, as part of a multi-error",
```
Comment (srosenberg) [inline pkg/cmd/roachtest/test_impl_test.go:142]: Nit: "...expected error _type_...". Maybe it's just me, but I was staring at `targetError{errors.New("expected-error")})` and `refError: targetError{errors.New("some error")}` long enough to warrant the extra qualifier.

**Comment by srosenberg** [comment]
> This changes roachtest's monitor wrapper to use the `errors.Join` API instead of `errors.CombineErrors` as previously.
> 
> The main relevant distinction in this case is that `Join` is the API to use in a multi-error use-case, as is the case here. `CombineErrors`, on the other hand, is used when the secondary error is only relevant during display, for debugging purposes. In other words, it is not possible to reference the secondary error from an opaque `error` reference, making it impossible to detect flakes if the transient error is in a secondary error.

The subtlety of the current implementation is that `CombineErrors` doesn't implement `UnwrapMulti`, thus `failuresMatchingError` can't properly recurse into the `secondaryError` chain. While this PR fixes a specific issue observed via `Monitor`, I wonder if we need to audit other uses of `CombinerErrors`. As of this time there are only `5` occurrences of `errors.Join` in the entire codebase, including this PR; the overwhelming majority is `CombineErrors`.

**Review by srosenberg — APPROVED** [review]

**Review by DarrylWong — APPROVED** [review]

File: pkg/cmd/roachtest/test_impl_test.go (hunk 1 above)
Comment (renatolabs) [reply pkg/cmd/roachtest/test_impl_test.go]: Yes, sorry about the confusion. Updated.

**Comment by renatolabs** [comment]
> As of this time there are only 5 occurrences of errors.Join in the entire codebase, including this PR; the overwhelming majority is CombineErrors.

I noticed this as well. I assume `CombineErrors` not implementing `UnwrapMulti` is by design: a lot of times there's one "main" error, and the secondary error is included to help debugging. The fact that this hasn't come up before suggests that it hasn't been an issue in other parts of the code.

> I wonder if we need to audit other uses of CombinerErrors

For roachprod/roachtest specifically, I was thinking that it would be better to update on a case-by-case basis as needed. I think the effort of going through every occurrence, changing it, and hoping nothing breaks is not justified by an unproved benefit of improved flake detection.

**Comment by renatolabs** [comment]
TFTRs!

bors r=srosenberg,DarrylWong
