### PR TITLE
Fix broken gossip unittest verifying redundant connections are closed.

### LINKED ISSUE #3134: acceptance: TestGossipRestart is flaky
The following test appears to have failed:

[#9372](https://circleci.com/gh/cockroachdb/cockroach/9372):

```
I1113 22:25:34.976218 16983 acceptance/localcluster/docker.go:335  Get https://0.0.0.0:32774/_status/gossip/local: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
I1113 22:25:38.978110 16983 acceptance/localcluster/docker.go:335  Get https://0.0.0.0:32774/_status/gossip/local: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
I1113 22:25:42.980139 16983 acceptance/localcluster/docker.go:335  Get https://0.0.0.0:32774/_status/gossip/local: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
I1113 22:25:46.983590 16983 acceptance/localcluster/docker.go:335  Get https://0.0.0.0:32774/_status/gossip/local: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
I1113 22:25:47.084313 16983 acceptance/localcluster/localcluster.go:525  stopping
--- FAIL: TestGossipPeerings (48.24s)
	testing.go:157: acceptance/gossip_peerings_test.go:62: condition failed to evaluate within 20s: Get https://0.0.0.0:32774/_status/gossip/local: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
=== RUN   TestGossipRestart
I1113 22:26:00.715423 16983 acceptance/localcluster/localcluster.go:211  started docker-spy: 172.17.0.16
I1113 22:26:00.715449 16983 acceptance/localcluster/localcluster.go:218  initializing cluster
I1113 22:26:03.541642 16983 acceptance/localcluster/localcluster.go:328  creating ca (1024bit) in: /home/ubuntu/cockroach/.localcluster.certs.234859526
I1113 22:26:03.586416 16983 acceptance/localcluster/localcluster.go:333  creating node (1024bit) certs in: /home/ubuntu/cockroach/.localcluster.certs.234859526
I1113 22:26:05.845641 16983 acceptance/localcluster/localcluster.go:381  *** started roach0.local ***
  ui:    https://0.0.0.0:32776
  trace: https://0.0.0.0:32776/debug/requests
  logs:  /tmp/circle-artifacts.Hj6JOIi/acceptance/roach0.local/cockroach.INFO
--
I1113 22:27:52.012999 16983 acceptance/status_server_test.go:67  OK response from https://0.0.0.0:32797/_status/logs/3
I1113 22:27:52.017304 16983 acceptance/status_server_test.go:67  OK response from https://0.0.0.0:32797/_status/stacks/3
I1113 22:27:52.019672 16983 acceptance/status_server_test.go:67  OK response from https://0.0.0.0:32797/_status/nodes/3
I1113 22:27:52.120052 16983 acceptance/localcluster/localcluster.go:525  stopping
--- PASS: TestStatusServer (21.41s)
FAIL
ok github.com/cockroachdb/cockroach/acceptance 1337s

```
Please assign, take a look and update the issue accordingly.

### PR DESCRIPTION
**Pull request by spencerkimball**
The unittest allowed a case where node 1 connected and served gossip
to node 2 before node 2 connected to node 1. In this event, node 1
will never close its client as node 2 hasn't yet connected, so no
redundancy to notice. Since no further gossiping takes place, the
unittest would just get stuck until the timeout.

Cleaned up some miscellaneous log messages.

Fixes #3134

[Review on Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/3378)

### CODE REVIEW

File: gossip/gossip.go [hunk 1]
```diff
@@ -611,13 +611,13 @@ func (g *Gossip) doDisconnected(stopper *stop.Stopper, c *client) {
 }
 
 func (g *Gossip) maybeSignalStalledLocked() {
-	// If there are no outgoing hosts or sentinel gossip is missing,
+	// If there are no outgoing hosts and sentinel gossip is missing,
```
Comment (tamird) [inline gossip/gossip.go]: i think this was correct before this change

File: gossip/gossip.go [hunk 2]
```diff
@@ -656,17 +656,18 @@ func (g *Gossip) maybeWarnAboutInit(stopper *stop.Stopper) {
 		// This will never error because of infinite retries.
 		for r := retry.Start(retryOptions); r.Next(); {
 			g.mu.Lock()
+			hasConnections := g.outgoing.len() > 0 || g.incoming.len() > 0
```
Comment (tamird) [inline gossip/gossip.go]: nit: kinda weird that this doesn't match the other place that does the same thing on L617. can you make the two match?

File: gossip/gossip.go [hunk 3]
```diff
@@ -656,17 +656,18 @@ func (g *Gossip) maybeWarnAboutInit(stopper *stop.Stopper) {
...
 				break
-			}
-			// Otherwise, if all bootstrap hosts are connected, warn.
-			if triedAll {
-				log.Warningf("connected to gossip but missing sentinel. Has the cluster been initialized? " +
-					"Use \"cockroach init\" to initialize.")
+			} else if !hasConnections {
+				log.Warningf("not connected to gossip; check that gossip flag is set appropriately")
+			} else if triedAll {
+				// Otherwise, if there are connections, but no sentinel but all bootstrap hosts are connected, warn.
```
Comment (tamird) [inline gossip/gossip.go]: "but all bootstrap hosts are connected" - does this actually check for that? this looks like an earlier version of the comment snuck in.

**Comment by tschottdorf** [comment]
LGTM. I'm still seeing Goroutine floods on AWS though, so there's more in the bushes.

---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[gossip/gossip.go, line 614 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3378#-K58Ehg3OsTVfYN5yXYW-r1-614:-K58yusmbeI79VPw1Bc8:1020172138) ([raw file](https://github.com/cockroachdb/cockroach/blob/dd2e905e030030ab306fa9dc1daad980b5649bdd/gossip/gossip.go#L614)):*
also, it doesn't seem to discriminate between outgoing/incoming connections.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/3378#-:-K58zwWmqdgdSOzPWIUu:-1170425586)*

File: gossip/client.go [hunk 4]
```diff
@@ -147,7 +147,7 @@ func (c *client) handleGossip(g *Gossip, call *netrpc.Call) error {
 				log.Infof("received %d (%d fresh) info(s) from %s", infoCount, freshCount, c.addr)
 			}
 		}
-	} else {
+	} else if reply.Alternate != nil {
```
Comment (bdarnell) [inline gossip/client.go]: The relationship between this log line and `reply.Alternate` being non-nil is unclear.

File: gossip/gossip.go (hunk 1 above)
Comment (spencerkimball) [inline gossip/gossip.go]: Yeah, I changed it back.

File: gossip/gossip.go (hunk 2 above)
Comment (spencerkimball) [inline gossip/gossip.go]: OK

File: gossip/gossip.go (hunk 3 above)
Comment (spencerkimball) [inline gossip/gossip.go]: Fixed.

**Comment by spencerkimball** [comment]
This is just fixing the flaky unittest. The goroutine floods on AWS is another matter. Could you point me at some logs for your problems on AWS, as the last gossip fix should have fixed goroutine floods? Marc pointed me at another which was a forwarding loop, but that shouldn't have created goroutine floods. 

---

Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[gossip/client.go, line 150 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3378#-K58IbxpbofxScELqrC1-r1-150:-K5Bocs-Ssjv6LVaqG3g:1425262540) ([raw file](https://github.com/cockroachdb/cockroach/blob/dd2e905e030030ab306fa9dc1daad980b5649bdd/gossip/client.go#L150)):*
I backed this change out actually. It wasn't correct, but might shed some light on the forwarding loop problem.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/3378#-:-K5BlKwIzLRQ4RWGd5yu:-1359261367)*

**Comment by tschottdorf** [comment]
Working on it. It's always a bit tricky since it doesn't reproduce cleanly and the AWS binaries are usually a little behind.

---

Review status: all files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/3378#-:-K5Bp2uQxypVcjgWzGzK:-920922824)*

**Comment by bdarnell** [comment]
LGTM

**Comment by tamird** [comment]
Reviewed 3 of 3 files at r1, 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[gossip/server.go, line 93 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3378#-K5CO-NkYGFPTScoVYtP:-K5CO-NkYGFPTScoVYtQ:-1139759415) ([raw file](https://github.com/cockroachdb/cockroach/blob/73334939e06ce0d17b6bc1e9d2ecb681e90edda4/gossip/server.go#L93)):*
What's this about?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/3378)*
