### PR TITLE
sql/catalog: ensure consistent versions during type hydration

### LINKED ISSUE #159509: roachtest: schemachange/mixed-versions failed
**Note:** This build has runtime assertions enabled. If the same failure was hit in a run without assertions enabled, there should be a similar failure without this message. If there isn&#39;t one, then this failure is likely due to an assertion violation or (assertion) timeout.

roachtest.schemachange/mixed-versions [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/20862386?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/20862386?buildTab=artifacts#/schemachange/mixed-versions) on release-26.1 @ [ab4b5eef4c89dc05e88c4504eae3f83cea9a5900](https://github.com/cockroachdb/cockroach/commits/ab4b5eef4c89dc05e88c4504eae3f83cea9a5900):

Failed with:

```
(mixedversion.go:893).Run: mixed-version test failure while running step 30 (run "run schemachange workload and validation after upgrade has finalized"): full command output in run_124027.072622115_n4_COCKROACHRANDOMSEED4.log: COMMAND_PROBLEM: exit status 1
test artifacts and logs in: /artifacts/schemachange/mixed-versions/run_1
```
Cluster Node to Ip Mapping:
| Node | Public IP | Private IP |
| --- | --- | --- |
| teamcity-20862386-1765783689-57-n4cpu4-0001 | 34.23.173.135 | 10.142.1.137 |
| teamcity-20862386-1765783689-57-n4cpu4-0002 | 34.75.55.42 | 10.142.2.183 |
| teamcity-20862386-1765783689-57-n4cpu4-0003 | 35.243.192.101 | 10.142.2.182 |
| teamcity-20862386-1765783689-57-n4cpu4-0004 | 35.237.42.212 | 10.142.1.72 |

Parameters:
 - <code>arch=amd64</code>
 - <code>cloud=gce</code>
 - <code>coverageBuild=false</code>
 - <code>cpu=4</code>
 - <code>encrypted=false</code>
 - <code>mvtDeploymentMode=separate-process</code>
 - <code>mvtVersions=v25.4.1 → v26.1.0-beta.1-dev-ab4b5eef4c89dc05e88c4504eae3f83cea9a5900 (release-26.1)</code>
 - <code>runtimeAssertionsBuild=true</code>
 - <code>ssd=0</code>
<details><summary>Help</summary>
<p>

See: [roachtest README](https://github.com/cockroachdb/cockroach/blob/master/pkg/cmd/roachtest/README.md)

See: [How To Investigate \(internal\)](https://cockroachlabs.atlassian.net/l/c/SSSBr8c7)

See: [Grafana](https://go.crdb.dev/roachtest-grafana/teamcity-20862386/schemachange-mixed-versions/1765799956681/1765802809792)

</p>
</details>
<details><summary>Same failure on other branches</summary>
<p>

- #159458 roachtest: schemachange/mixed-versions failed [B-runtime-assertions-enabled C-test-failure O-roachtest O-robot T-sql-foundations branch-master release-blocker]
- #159238 roachtest: schemachange/mixed-versions failed [C-test-failure O-roachtest O-robot T-sql-foundations branch-release-25.3.6-rc release-blocker]
- #158838 roachtest: schemachange/mixed-versions failed [index_key_decoding_error: single entry value with no default column id] [B-runtime-assertions-enabled C-test-failure O-roachtest O-robot T-sql-foundations branch-release-24.3.24-rc release-blocker]
</p>
</details>
/cc @cockroachdb/sql-foundations
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*schemachange/mixed-versions.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/bazci/githubpost/issues)

</sub>

Jira issue: CRDB-57905

### PR DESCRIPTION
**Pull request by fqazi**
Previously, if a schema had references to types being dropped, for example due to functions that were being cleaned up, it was possible to encountered "descriptor is being dropped" when leasing the schema. This happened because the version of the schema could be behind that of other objects referenced. While locked leasing eliminates issues for non-dropped objects, it cannot alleviate it for any dropped descriptors that are being resolved. To address this, this patch will generate a retryable error, if we detect that a dropped type descriptor encountered after the read timestamp.

Fixes: #159509

Release note: None

### CODE REVIEW

File: pkg/sql/catalog/lease/lease_test.go [hunk 1]
```diff
@@ -4319,3 +4319,69 @@ func TestLeaseManagerTxnTimestampAdvance(t *testing.T) {
 		require.NoError(t, grp.Wait())
 	})
 }
+
+// TestLeasedDescriptorTypeHydration verifies that leased descriptors hydrated
+// with concurrent schema changes never encounter errors.
+func TestLeasedDescriptorTypeHydration(t *testing.T) {
+	defer leaktest.AfterTest(t)()
+	defer log.Scope(t).Close(t)
```
Comment (rafiss) [inline pkg/sql/catalog/lease/lease_test.go:4327]: nice test! there's a lot of concurrency so just want to to double check it's stable under stress/race/deadlock?

File: pkg/sql/catalog/descs/hydrate.go [hunk 2]
```diff
@@ -211,6 +215,27 @@ func makeImmutableTypeLookupFunc(
...
 			return nil, err
 		}
+		// If the descriptor is dropped, and we are using leased descriptors,
+		// then check if its valid against our lease timestamp. If our lease timestamp is
+		// before the drop, force a retry error, which should cause us to see a
+		// newer version of the dependent object.
+		// Note: This is a special case because type hydration cannot tolerate
+		// dropped descriptors. This already could occur by leasing any schema
+		// with type references that are being dropped.
+		if !witoutDropped && desc.Dropped() {
```
Comment (rafiss) [inline pkg/sql/catalog/descs/hydrate.go]: should it be `if !witoutDropped && !withoutLeased && desc.Dropped()`

**Review by rafiss — APPROVED** [review]
nice work!

File: pkg/sql/catalog/descs/hydrate.go (hunk 2 above)
Comment (fqazi) [reply pkg/sql/catalog/descs/hydrate.go]: Done.

Yeah that would make it more future proof.

File: pkg/sql/catalog/lease/lease_test.go (hunk 1 above)
Comment (fqazi) [reply pkg/sql/catalog/lease/lease_test.go:4327]: Done.

I ran this on engflow under stress as validation.

**Review by fqazi — COMMENTED** [review]
> @fqazi made 2 comments.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/162622)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @rafiss).
