### PR TITLE
kvserver: allow term and generation increments

### LINKED ISSUE #104477: kv/kvserver: TestReplicaTombstone failed
kv/kvserver.TestReplicaTombstone [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_StressBazel/10431502?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_StressBazel/10431502?buildTab=artifacts#/) on release-23.1 @ [1a5dc2aad16ca4185afcda75d923804324dcfeb9](https://github.com/cockroachdb/cockroach/commits/1a5dc2aad16ca4185afcda75d923804324dcfeb9):

```
=== RUN   TestReplicaTombstone
--- FAIL: TestReplicaTombstone (40.99s)
=== RUN   TestReplicaTombstone/(4)_(4.1)_raft_messages_to_newer_replicaID_
    test_log_scope.go:161: test logs captured to: /artifacts/tmp/_tmp/33e1d369c27b9c01b2b6009c561815a3/logTestReplicaTombstone_(4)_(4.1)_raft_messages_to_newer_replicaID_2468918913
    test_log_scope.go:79: use -show-logs to present logs inline
    client_replica_test.go:3654: 
        	Error Trace:	github.com/cockroachdb/cockroach/pkg/kv/kvserver_test/pkg/kv/kvserver/client_replica_test.go:3654
        	Error:      	Expect "error sending couldn't accept range_id:64 coordinator_replica:<node_id:1 store_id:1 replica_id:1 type:VOTER_FULL > recipient_replica:<node_id:3 store_id:3 replica_id:4 type:LEARNER > delegated_sender:<node_id:1 store_id:1 replica_id:1 type:VOTER_FULL > priority:REBALANCE type:INITIAL term:9 first_index:41 descriptor_generation:9 queue_on_delegate_len:-1 snap_id:b792b7c5-3e44-4ca3-b924-2e16ba3f5ed2: sender: (n1,s1):1 is not fit to send snapshot for (n1,s1):1; sender term: 10, coordinator term: 9" to match "boom"
        	Test:       	TestReplicaTombstone/(4)_(4.1)_raft_messages_to_newer_replicaID_
    panic.go:522: -- test log scope end --
test logs left over in: /artifacts/tmp/_tmp/33e1d369c27b9c01b2b6009c561815a3/logTestReplicaTombstone_(4)_(4.1)_raft_messages_to_newer_replicaID_2468918913
    --- FAIL: TestReplicaTombstone/(4)_(4.1)_raft_messages_to_newer_replicaID_ (7.44s)
```
<p>Parameters: <code>TAGS=bazel,gss,deadlock</code>
</p>
<details><summary>Help</summary>
<p>

See also: [How To Investigate a Go Test Failure \(internal\)](https://cockroachlabs.atlassian.net/l/c/HgfXfJgM)
</p>
</details>
/cc @cockroachdb/kv
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*TestReplicaTombstone.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)
</sub>

### PR DESCRIPTION
**Pull request by andrewbaptist**
Previously delegated snapshots had a check where it would not allow delegation if the term or generation were different between the sender and the recipient. This was incorrect as on the coordinator it was possible that the term and generation could increment. This change allows the sending of changes as long as the sender (leaseholder or delegate) has an equal or greater term or generation.

Epic: none
Fixes: #104477

Release note: None

### CODE REVIEW

File: pkg/kv/kvserver/replica_command.go [hunk 1]
```diff
@@ -2965,7 +2965,7 @@ func (r *Replica) validateSnapshotDelegationRequest(
 	// and then the term changes before this request is processed. In that
 	// case this code path will not be checked and the snapshot will still be
 	// sent.
-	if replTerm != req.Term {
+	if replTerm < req.Term {
```
Comment (pavelkalinnikov) [inline pkg/kv/kvserver/replica_command.go:2968]: Is the comment above up-to-date?

**Review by pav-kv — APPROVED** [review]

**Review by andrewbaptist — COMMENTED** [review]
TFTR - good catch on the comments. Snapshots are "loosely coupled" with other replica and lease movements, so it needs to be more tolerant of forward changes to these values but not backward values. 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/105044#-:-NY4BqUSDgB6bTpcdsX-:b-51yvxx)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @pavelkalinnikov)

___
*[`pkg/kv/kvserver/replica_command.go` line 2917 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/105044#gh-1232348125:-NY4BAvx2HK5oIy2-B7v:bxb8qvj) ([raw file](https://github.com/cockroachdb/cockroach/blob/d21647b3a4d36a2c05d2d825613cccc5e99e9fe0/pkg/kv/kvserver/replica_command.go#L2917)):*
<details><summary><i>Previously, pavelkalinnikov (Pavel Kalinnikov) wrote…</i></summary><blockquote>

Could you update the `validateSnapshotDelegationRequest` method comment accordingly? It currently speaks in terms of term/gen equality.

Is the comment above up-to-date? Not sure what "if there are merges or splits, it is safer to reject" means, but don't we enable this "unsafe" scenario with this change?
</blockquote></details>

Updated the comment. Forward changes to term and generation are OK, but backwards changes are not.
___
*[`pkg/kv/kvserver/replica_command.go` line 2968 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/105044#gh-1232352838:-NY4BowWCdu9gkBUEzIB:be1d7eh) ([raw file](https://github.com/cockroachdb/cockroach/blob/d21647b3a4d36a2c05d2d825613cccc5e99e9fe0/pkg/kv/kvserver/replica_command.go#L2968)):*
<details><summary><i>Previously, pavelkalinnikov (Pavel Kalinnikov) wrote…</i></summary><blockquote>

Is the comment above up-to-date?
</blockquote></details>

Update the comment here also.

**Review by pav-kv — APPROVED** [review]

**Comment by andrewbaptist** [comment]
bors r=pavelkalinnikov

**Comment by andrewbaptist** [comment]
bors retry

**Comment by kvoli** [comment]
blathers backport 23.1
