### PR TITLE
kv: Replace rpcError with roachpb.SendError

### LINKED ISSUE #6410: kv: unify `kv.rpcError` and `roachpb.SendError`
`kv.rpcError` and `roachpb.SendError` are both used to indicate that we failed to send an RPC, but they are handled differently in `DistSender`: `roachpb.SendError` invalidates the range descriptor cache but `kv.rpcError` doesn't. This means that when an `rpcError` is caused by a stale range descriptor, we may never recover. We should handle `rpcError` in the same way as `SendError` (and, if possible, combine the two into one type).

### PR DESCRIPTION
**Pull request by bdarnell**
We don't need an extra type just to make a retryable util.Errorf, and
SendError has the same semantics that are desired here.

Closes #6410

---

This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/6435)

### CODE REVIEW

**Comment by tschottdorf** [comment]
LGTM

File: kv/send.go [hunk 1]
```diff
@@ -272,13 +254,19 @@ func sendOne(opts SendOptions, rpcContext *rpc.Context, client batchClient, done
 		c := client.conn
 		for state, err := c.State(); state != grpc.Ready; state, err = c.WaitForStateChange(ctx, state) {
 			if err != nil {
-				done <- batchCall{err: newRPCError(
-					util.Errorf("rpc to %s failed: %s", addr, err))}
+				// TODO(tschottdorf): the way this is used suggests that it
```
Comment (tschottdorf) [inline kv/send.go]: Remove this TODO.
