### PR TITLE
loqrecovery: verify pending descriptor changes in raft log

### LINKED ISSUE #74630: loss of quorum recovery tools: analyze raft log for pending range descriptor and raft group updates
When validating key coverage, ensure that recovered ranges doesn't contain unapplied range descriptor changes.

If survivor replicas contain unapplied updates, their application will cause nodes to crash since they expect replica id that was overwritten by recovery procedure.

### PR DESCRIPTION
**Pull request by aliher1911**
Previously, when generating unsafe loss of quorum recovery plan recovery command could pick replicas that have unapplied changes to local range descriptor. That would cause nodes to crash because of unexpected change.
To resolve this, this patch adds a check that would extract information about descriptor changes from raft log and subsequently fail if recovered range would need to use replica with pending descriptor changes.

It adds the flag --force to allow creation of the plan when some ranges have potentially dangerous changes.

For those cases prompt will provide following info:
```
Found replica inconsistencies:

range gap /Table/{59-60}
  r88: /Table/5{8/1/"washington dc"/"Tz\xe1G\xae\x14L\x00\x80\x00\x00\x00\x00\x00\x00\xa5"-9}
  r49: /Table/6{0-1}

Only proceed as a last resort!
Proceed with plan creation [f/N] f
Plan created
To complete recovery, distribute the plan to the below nodes and invoke `debug recover apply-plan` on:
- node n6, store(s) s6
- node n5, store(s) s5
- node n1, store(s) s1
```

--confirm y together with --force:
```
Found replica inconsistencies:

range gap /Table/{59-60}
  r88: /Table/5{8/1/"washington dc"/"Tz\xe1G\xae\x14L\x00\x80\x00\x00\x00\x00\x00\x00\xa5"-9}
  r49: /Table/6{0-1}

Plan created
To complete recovery, distribute the plan to the below nodes and invoke `debug recover apply-plan` on:
- node n5, store(s) s5
- node n1, store(s) s1
- node n6, store(s) s6
```

while --confirm y without --force will result in:
```
Found replica inconsistencies:

range gap /Table/{59-60}
  r88: /Table/5{8/1/"washington dc"/"Tz\xe1G\xae\x14L\x00\x80\x00\x00\x00\x00\x00\x00\xa5"-9}
  r49: /Table/6{0-1}

ERROR: can not create plan because of errors and no --force flag is given
Failed running "debug recover make-plan"
```

Fixes: #74630

### CODE REVIEW

File: pkg/kv/kvserver/loqrecovery/collect.go [hunk 1]
```diff
@@ -62,3 +76,68 @@ func CollectReplicaInfo(
...
+		if ok, err := iter.Valid(); err != nil || !ok {
+			return false, err
+		}
+		if err := protoutil.Unmarshal(iter.UnsafeValue(), &meta); err != nil {
+			return false, errors.Wrap(err, "unable to decode raft log MVCCMetadata")
+		}
+		if err := storage.MakeValue(meta).GetProto(&ent); err != nil {
+			return false, errors.Wrap(err, "unable to unmarshal raft Entry")
+		}
+		if ent.Type != raftpb.EntryNormal || len(ent.Data) == 0 {
```
Comment (tbg) [inline pkg/kv/kvserver/loqrecovery/collect.go:114]: configuration changes come as an EntryConfChange, so you want to inspect those in particular. When you have an EntryConfChange(V1|V2), the command is nested like this:

https://github.com/cockroachdb/cockroach/blob/4df8ac262e72c58cb4e09dcf1beb0b8ff6fdde27/pkg/kv/kvserver/debug_print.go#L223-L243

File: pkg/kv/kvserver/loqrecovery/collect.go [hunk 2]
```diff
@@ -45,14 +51,22 @@ func CollectReplicaInfo(
 			if err != nil {
 				return err
 			}
+			// Check raft log for un-applied range descriptor changes. We start from
+			// the position after applied (inclusive) and stop at position after
+			// committed (exclusive) - hence +1 on index values.
+			hasUnappliedDesc, err := checkUncommittedDescriptorsInRaftLog(desc.RangeID, desc.StartKey,
+				rstate.RaftAppliedIndex+1, hstate.Commit+1, reader)
```
Comment (tbg) [inline pkg/kv/kvserver/loqrecovery/collect.go:58]: I think you'd want to check up to the end of the log here (i.e. LastIndex+1 as opposed to Commit+1). Otherwise, we have to also truncate the log because any conf change in the "uncommitted" tail would become committed on the survivor and cause the very same problems we're trying to avoid. Also, note that even though not "known committed", such an entry may in fact have committed, meaning that the meta2 record might be the "new" descriptor - however I think this is ok since the next replication change will patch up the descriptor. For splits and merges it's a whole different story though, it will require a game of non-local analysis and the ability to apply splits "offline" to get out of the situation.
For now I strongly prefer we just catch all mutations to the descriptor and bail.

File: pkg/kv/kvserver/loqrecovery/collect.go [hunk 3]
```diff
@@ -62,3 +76,68 @@ func CollectReplicaInfo(
...
+
+// checkUncommittedDescriptorsInRaftLog iterates over committed but not applied
+// part of raft log and searches for writes to range descriptor. If any value
+// referencing local range descriptor key is found then we have a potential
+// pending update.
+func checkUncommittedDescriptorsInRaftLog(
+	rangeID roachpb.RangeID,
+	rangeKey roachpb.RKey,
+	startIndex uint64,
+	endIndex uint64,
```
Comment (tbg) [inline pkg/kv/kvserver/loqrecovery/collect.go:88]: Sort of a convention at least in the raft code, which you may want to cargo cult here, is to call these `lo, hi uint64` where `lo` is inclusive, `hi` is exclusive (and note that in a comment).

File: pkg/kv/kvserver/loqrecovery/collect.go [hunk 4]
```diff
@@ -62,3 +76,68 @@ func CollectReplicaInfo(
...
 	return loqrecoverypb.NodeReplicaInfo{Replicas: replicas}, nil
 }
+
+// checkUncommittedDescriptorsInRaftLog iterates over committed but not applied
+// part of raft log and searches for writes to range descriptor. If any value
+// referencing local range descriptor key is found then we have a potential
+// pending update.
+func checkUncommittedDescriptorsInRaftLog(
+	rangeID roachpb.RangeID,
+	rangeKey roachpb.RKey,
```
Comment (tbg) [inline pkg/kv/kvserver/loqrecovery/collect.go:86]: call this `startKey` because that's what it is, it isn't really clear what a "range key" is.

File: pkg/kv/kvserver/loqrecovery/collect.go [hunk 5]
```diff
@@ -62,3 +76,68 @@ func CollectReplicaInfo(
...
+		batchReader, err := storage.NewRocksDBBatchReader(raftCmd.WriteBatch.Data)
+		if err != nil {
+			return false, errors.Wrap(err, "unable to read entries from raft command")
+		}
+		for batchReader.Next() {
+			switch batchReader.BatchType() {
+			case storage.BatchTypeValue:
+				mvccKey, err := batchReader.MVCCKey()
+				if err == nil {
+					if rangeDescKey.Equal(mvccKey.Key) {
```
Comment (tbg) [inline pkg/kv/kvserver/loqrecovery/collect.go:134]: The operation that performs the change is really the commit of such an operation, so I think you'd be looking for operations that perform an engine clear on the range descriptor key meta record, where the clear originates from this line during evaluation:

https://github.com/cockroachdb/cockroach/blob/c6dc23e9b1978e7ce0f965dd6e033c02e306a3f3/pkg/kv/kvserver/batcheval/cmd_end_transaction.go#L483-L482

which calls down to the actual clear here:

https://github.com/cockroachdb/cockroach/blob/52c2df4fb00d943328dc59df9dc210a40a556ab2/pkg/storage/mvcc.go#L3147

The distinction is important because the code here doesn't handle the case in which the intent writes are committed but the commit is not:

```
Put(txn, descKey) <-- applied
Something else    <-- committed
Commit(txn)
```

In this case the above code doesn't find anything or maybe it does, but if so I'm not sure if intentionally so.

There's also existing code (I remember that from unsafe-remove-dead-replicas) that aborts intents on the range descriptor; this should somehow play into it here since it's trying to handle similar issues (though more shallowly). I think you want to check

- is there an intent on the range desc (as of applied index)
- if not, is there a write in the raft log that will write such an intent? (I think that's your code!)
- if either of the above, check if the intent could possibly have committed (that's my suggestion above: is there a corresponding EndTxn in the tail of the log)
- if so, bail
- if not, we're fine: the txn will ultimately be aborted.

As always there is the residual risk that the txn actually did commit but we never learned about the corresponding log entry. This information gap can't be bridged unless we also add offline analysis of meta2 into the equation, which we can't right now.

Comment (aliher1911) [reply pkg/kv/kvserver/loqrecovery/collect.go]: I changed it to bail on any sequence other than a single clear lock for descriptor. We currently drop the intent if it is found. If we want to keep transaction then we might need to apply it as well as that implies other ranges has changed as well. So in those cases we'll end up with incomplete coverage.

File: pkg/kv/kvserver/loqrecovery/collect.go (hunk 2 above)
Comment (aliher1911) [reply pkg/kv/kvserver/loqrecovery/collect.go]: So all the detection was moved into checking commit triggers and bailing in presence of anything but removing other replicas.

**Comment by aliher1911** [comment]
Heads up, there are some pending changes from offline discussion.

**Comment by aliher1911** [comment]
Ok we are good to go now, CLI UI is such a chore!

**Review by tbg — APPROVED** [review]
:lgtm:

> Reviewed 21 of 21 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/74654#-:-MuzlSnP7hGJAid0YjfY:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @aliher1911 and @erikgrinaker)

___
*[pkg/cli/debug.go, line 1658 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/74654#-MuzdbgJ3jMRbleSXFx-:-MuzdbgJ3jMRbleSXFx0:b1y286z) ([raw file](https://github.com/cockroachdb/cockroach/blob/2e95596d84f0362d1df65a0dbf482499c1a82c56/pkg/cli/debug.go#L1658)):*
I would rephrase this somewhat to not throw the word "consistency" in there:

> "force creation of plan even when problems were encountered; applying this plan may result in additional problems and should be done only with care and as a last resort"
___
*[pkg/cli/debug_recover_loss_of_quorum.go, line 300 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/74654#-MuzdY2i4_NzqfHPBtyJ:-MuzdY2i4_NzqfHPBtyK:bdmhg9v) ([raw file](https://github.com/cockroachdb/cockroach/blob/2e95596d84f0362d1df65a0dbf482499c1a82c56/pkg/cli/debug_recover_loss_of_quorum.go#L300)):*
> ```Go
> 	}
> 
> 	planingErr := report.Error()
> ```

planningErr
___
*[pkg/cli/debug_recover_loss_of_quorum.go, line 311 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/74654#-Muzeagd4FQtvLeurCcw:-Muzeagd4FQtvLeurCcx:b8awdk0) ([raw file](https://github.com/cockroachdb/cockroach/blob/2e95596d84f0362d1df65a0dbf482499c1a82c56/pkg/cli/debug_recover_loss_of_quorum.go#L311)):*
> ```Go
> 	}
> 
> 	if len(plan.Updates) == 0 {
> ```

We had discussed moving this after the error handling, looks like that would still make sense since it would obviate the need to inspect `planningErr` here.
___
*[pkg/cli/debug_recover_loss_of_quorum.go, line 325 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/74654#-Muzgzqf5jdMaJ4MuRwC:-Muzgzqf5jdMaJ4MuRwD:b-lwn6gn) ([raw file](https://github.com/cockroachdb/cockroach/blob/2e95596d84f0362d1df65a0dbf482499c1a82c56/pkg/cli/debug_recover_loss_of_quorum.go#L325)):*
> ```Go
> 			// Need to warn user before they make a decision that ignoring
> 			// inconsistencies is a really bad idea.
> 			_, _ = fmt.Fprintln(stderr, "Only proceed as a last resort!")
> ```

I see you're printing this in two branches (prompt and all-yes with --force), can't you "just" print it after you've made it past this entire `confirmAction` prompt?
___
*[pkg/cli/debug_recover_loss_of_quorum.go, line 328 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/74654#-Muzf-hb7SloZbX4g9Qc:-Muzf-hb7SloZbX4g9Qd:b-mva9yj) ([raw file](https://github.com/cockroachdb/cockroach/blob/2e95596d84f0362d1df65a0dbf482499c1a82c56/pkg/cli/debug_recover_loss_of_quorum.go#L328)):*
> ```Go
> 			opts = "f/N"
> 		}
> 	input:
> ```

If you don't mind let's try to avoid the label, I am most happy when I can pretend to myself that Go doesn't have this.

```
for done := false; done; {
  switch x {
    case 'y':
      if planningErr == nil { done = true }
    case 'f':
      done = true
  }
}
```

Starting to think it would've been wise to use something like https://github.com/AlecAivazis/survey from the start (not a suggestion to do so now!).
___
*[pkg/cli/debug_recover_loss_of_quorum.go, line 338 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/74654#-MuzgXiA80ekETms1LnG:-MuzgXiA80ekETms1LnH:b-xufpqc) ([raw file](https://github.com/cockroachdb/cockroach/blob/2e95596d84f0362d1df65a0dbf482499c1a82c56/pkg/cli/debug_recover_loss_of_quorum.go#L338)):*
> ```Go
> 			// When user just hits <enter> we'll have a new line only string which
> 			// we need to turn into default option.
> 			if len(line) == 1 {
> ```

Not sure what the most canonical way to do this is, but you could also use `strings.TrimSpace(line) == ""`, idk if there is some "\r\n" vs "\n" thing going on with different platforms.
___
*[pkg/cli/debug_recover_loss_of_quorum.go, line 352 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/74654#-MuzgjDO36GtigKXYsPA:-MuzgjDO36GtigKXYsPB:b-yg808z) ([raw file](https://github.com/cockroachdb/cockroach/blob/2e95596d84f0362d1df65a0dbf482499c1a82c56/pkg/cli/debug_recover_loss_of_quorum.go#L352)):*
> ```Go
> 				break input
> 			case 'n':
> 				return nil
> ```

If the user says not to proceed, should the exit code really be zero? That seems wrong.
___
*[pkg/kv/kvserver/replica_raftstorage.go, line 1258 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/74654#-MuzhI2G0Ae_dpONqBly:-MuzhI2G0Ae_dpONqBlz:b-sx9ml9) ([raw file](https://github.com/cockroachdb/cockroach/blob/2e95596d84f0362d1df65a0dbf482499c1a82c56/pkg/kv/kvserver/replica_raftstorage.go#L1258)):*
> ```Go
> // EncodeTestRaftCommand encodes provided command as raft command by adding
> // appropriate prefix to the data. It is only used for testing to create test
> // raft log entries. No correctness guarantees are provided.
> ```

Might want to add something like:

//
// See: https://github.com/cockroachdb/cockroach/issues/75729
___
*[pkg/kv/kvserver/loqrecovery/collect.go, line 55 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/74654#-MuzhRHF1sxTAROjdwXv:-MuzhRHF1sxTAROjdwXw:b-80tms8) ([raw file](https://github.com/cockroachdb/cockroach/blob/2e95596d84f0362d1df65a0dbf482499c1a82c56/pkg/kv/kvserver/loqrecovery/collect.go#L55)):*
"position after applied (inclusive)" could be misread as meaning that "applied" itself is inclusive. Suggestion:

> We start from `applied+1` (inclusive) and read ...
___
*[pkg/kv/kvserver/loqrecovery/collect.go, line 56 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/74654#-MuzhZ0r-jEBy5ZdsqYb:-MuzhZ0r-jEBy5ZdsqYc:b-tpk11t) ([raw file](https://github.com/cockroachdb/cockroach/blob/2e95596d84f0362d1df65a0dbf482499c1a82c56/pkg/kv/kvserver/loqrecovery/collect.go#L56)):*
> ```Go
> 			// Check raft log for un-applied range descriptor changes. We start from
> 			// the position after applied (inclusive) and read until the end of the
> 			// log. We also look on potentially uncommitted entries as we have no way
> ```

look at
___
*[pkg/kv/kvserver/loqrecovery/collect.go, line 71 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/74654#-MuzhjPIEoHLG_VOrLpr:-MuzhjPIEoHLG_VOrLps:b-2ettov) ([raw file](https://github.com/cockroachdb/cockroach/blob/2e95596d84f0362d1df65a0dbf482499c1a82c56/pkg/kv/kvserver/loqrecovery/collect.go#L71)):*
> ```Go
> 				RaftAppliedIndex:          rstate.RaftAppliedIndex,
> 				RaftCommittedIndex:        hstate.Commit,
> 				HasUncommittedDescriptors: len(rangeUpdates) > 0,
> ```

HasUncommittedDescriptors is legacy now, right? It is unused, so it makes sense to me to remove it in this PR.
___
*[pkg/kv/kvserver/loqrecovery/collect.go, line 87 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/74654#-MuziP1a4mTrRpHb5K-y:-MuziP1b4Uw39py_cb-Z:bj96d0i) ([raw file](https://github.com/cockroachdb/cockroach/blob/2e95596d84f0362d1df65a0dbf482499c1a82c56/pkg/kv/kvserver/loqrecovery/collect.go#L87)):*
> ```Go
> // commit trigger content which is extracted either from EntryNormal where
> // change updates key range info (split/merge) or from EntryConfChange*
> // for changes in replica set.
> ```

Mention that `lo` is inclusive, `hi` exclusive.
___
*[pkg/kv/kvserver/loqrecovery/plan.go, line 81 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/74654#-Muzj2goExxXy72ykrE_:-Muzj2goExxXy72ykrEa:b-o1i98z) ([raw file](https://github.com/cockroachdb/cockroach/blob/2e95596d84f0362d1df65a0dbf482499c1a82c56/pkg/kv/kvserver/loqrecovery/plan.go#L81)):*
> ```Go
> 	UpdatedNodes map[roachpb.NodeID][]roachpb.StoreID
> 
> 	// KeyspaceAnomalies contains any keyspace coverage anomalies
> ```

This comment doesn't explain anything. They're also not really "anomalies", they're generally "problems", right? Should we just call this `Problems` and `[]Problem`?
___
*[pkg/kv/kvserver/loqrecovery/plan.go, line 119 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/74654#-MuzjIOQEgljLBkRomR1:-MuzjIOQEgljLBkRomR2:b-4mhwfl) ([raw file](https://github.com/cockroachdb/cockroach/blob/2e95596d84f0362d1df65a0dbf482499c1a82c56/pkg/kv/kvserver/loqrecovery/plan.go#L119)):*
> ```Go
> // they would be returned in the report, but that would not prevent us from
> // making an "unsafe" recovery plan.
> // error is returned in case of unrecoverable error in the collected data that
> ```

nit: An error
___
*[pkg/kv/kvserver/loqrecovery/plan.go, line 503 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/74654#-MuzjiW0EWQhQAIF5yx6:-MuzjiW0EWQhQAIF5yx7:b3kqx) ([raw file](https://github.com/cockroachdb/cockroach/blob/2e95596d84f0362d1df65a0dbf482499c1a82c56/pkg/kv/kvserver/loqrecovery/plan.go#L503)):*
> ```Go
> 		case loqrecoverypb.DescriptorChangeType_ReplicaChange:
> 			// Check if our own replica is being removed as part of descriptor
> 			// change
> ```

.
___
*[pkg/kv/kvserver/loqrecovery/collect_raft_log_test.go, line 213 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/74654#-MuzkyHY6Bhi64lCpz4e:-MuzkyHY6Bhi64lCpz4f:b-u5wn74) ([raw file](https://github.com/cockroachdb/cockroach/blob/2e95596d84f0362d1df65a0dbf482499c1a82c56/pkg/kv/kvserver/loqrecovery/collect_raft_log_test.go#L213)):*
> ```Go
> 	t.Helper()
> 	for _, v := range seq {
> 		if value.ChangeType == v.ChangeType {
> ```

Why not just `reflect.DeepEqual(value, v)`?
___
*[pkg/kv/kvserver/loqrecovery/collect_raft_log_test.go, line 232 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/74654#-Muzl05OELzCzTeZyL-F:-Muzl05OELzCzTeZyL-G:bec1oua) ([raw file](https://github.com/cockroachdb/cockroach/blob/2e95596d84f0362d1df65a0dbf482499c1a82c56/pkg/kv/kvserver/loqrecovery/collect_raft_log_test.go#L232)):*
> ```Go
> 	}
> 	t.Errorf("descriptor change sequence %v doesn't contain %v", seq, value)
> 	t.FailNow()
> ```

`t.Errorf(), t.FailNow()` is just `t.Fatalf(...)` so just use that.
___
*[pkg/kv/kvserver/loqrecovery/recovery_env_test.go, line 64 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/74654#-MuzlD4g7RcBp2jLgrAH:-MuzlD4g7RcBp2jLgrAI:b3kqx) ([raw file](https://github.com/cockroachdb/cockroach/blob/2e95596d84f0362d1df65a0dbf482499c1a82c56/pkg/kv/kvserver/loqrecovery/recovery_env_test.go#L64)):*
> ```Go
> }
> 
> // Raft log descriptor changes
> ```

.
___
*[pkg/kv/kvserver/loqrecovery/recovery_env_test.go, line 68 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/74654#-MuzlF6z1d00quqEhBMF:-MuzlF6z1d00quqEhBMG:b3kqx) ([raw file](https://github.com/cockroachdb/cockroach/blob/2e95596d84f0362d1df65a0dbf482499c1a82c56/pkg/kv/kvserver/loqrecovery/recovery_env_test.go#L68)):*
> ```Go
> 	// Change type determines which fields has to be set here. While this could be
> 	// error-prone, we use this for the sake of test spec brevity. Otherwise
> 	// we will need nested structures which would introduce clutter
> ```

.

**Review by aliher1911 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/74654)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @erikgrinaker and @tbg)

___
*[pkg/cli/debug.go, line 1658 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/74654#-MuzdbgJ3jMRbleSXFx-:-Mv-6kqQBaLzDsYwBmxa:b-286iut) ([raw file](https://github.com/cockroachdb/cockroach/blob/2e95596d84f0362d1df65a0dbf482499c1a82c56/pkg/cli/debug.go#L1658)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

I would rephrase this somewhat to not throw the word "consistency" in there:

> "force creation of plan even when problems were encountered; applying this plan may result in additional problems and should be done only with care and as a last resort"
</blockquote></details>

I'll put it as "override safety checks for recovered replica state" since that's what we actually do. Without getting into details of checks or effects.
___
*[pkg/cli/debug_recover_loss_of_quorum.go, line 325 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/74654#-Muzgzqf5jdMaJ4MuRwC:-Mv-7z3Q5igXhb8FNZtU:b-m1ll4n) ([raw file](https://github.com/cockroachdb/cockroach/blob/2e95596d84f0362d1df65a0dbf482499c1a82c56/pkg/cli/debug_recover_loss_of_quorum.go#L325)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

I see you're printing this in two branches (prompt and all-yes with --force), can't you "just" print it after you've made it past this entire `confirmAction` prompt?
</blockquote></details>

My thinking is that if it is printed after confirm then it will be ignored. So we ask a confirmation as 'f' instead of 'y' in this case, but if we remove the warning then it will be confusing as to why you need to press f. I'd rather push it above the confirm action then.
___
*[pkg/cli/debug_recover_loss_of_quorum.go, line 328 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/74654#-Muzf-hb7SloZbX4g9Qc:-Mv-8VHm8MwfsU-b9tNV:b-usugy1) ([raw file](https://github.com/cockroachdb/cockroach/blob/2e95596d84f0362d1df65a0dbf482499c1a82c56/pkg/cli/debug_recover_loss_of_quorum.go#L328)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

If you don't mind let's try to avoid the label, I am most happy when I can pretend to myself that Go doesn't have this.

```
for done := false; done; {
  switch x {
    case 'y':
      if planningErr == nil { done = true }
    case 'f':
      done = true
  }
}
```

Starting to think it would've been wise to use something like https://github.com/AlecAivazis/survey from the start (not a suggestion to do so now!).
</blockquote></details>

I think it depends on if we want to push cli tools further. It would be in conflict with relying on k8s and web console for management.
___
*[pkg/cli/debug_recover_loss_of_quorum.go, line 338 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/74654#-MuzgXiA80ekETms1LnG:-Mv-9YsL7kmZFn7jvD_z:bgc7vqv) ([raw file](https://github.com/cockroachdb/cockroach/blob/2e95596d84f0362d1df65a0dbf482499c1a82c56/pkg/cli/debug_recover_loss_of_quorum.go#L338)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

Not sure what the most canonical way to do this is, but you could also use `strings.TrimSpace(line) == ""`, idk if there is some "\r\n" vs "\n" thing going on with different platforms.
</blockquote></details>

:heart: 
___
*[pkg/cli/debug_recover_loss_of_quorum.go, line 352 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/74654#-MuzgjDO36GtigKXYsPA:-Mv-9e9m4G2EACuD_GKu:b-t24g9u) ([raw file](https://github.com/cockroachdb/cockroach/blob/2e95596d84f0362d1df65a0dbf482499c1a82c56/pkg/cli/debug_recover_loss_of_quorum.go#L352)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

If the user says not to proceed, should the exit code really be zero? That seems wrong.
</blockquote></details>

Fair. I finally had to go and check what does typical unix utils do on 'n' and they return 1.
___
*[pkg/kv/kvserver/loqrecovery/collect.go, line 71 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/74654#-MuzhjPIEoHLG_VOrLpr:-Mv-E5DA6MOm4hb1o9VS:bzdjlxm) ([raw file](https://github.com/cockroachdb/cockroach/blob/2e95596d84f0362d1df65a0dbf482499c1a82c56/pkg/kv/kvserver/loqrecovery/collect.go#L71)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

HasUncommittedDescriptors is legacy now, right? It is unused, so it makes sense to me to remove it in this PR.
</blockquote></details>

Can we remove that without doing any special compatibility dance here since it is not out in a wild yet? 
___
*[pkg/kv/kvserver/loqrecovery/plan.go, line 81 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/74654#-Muzj2goExxXy72ykrE_:-Mv-H3N09OA1WDzfJBtc:b-lyaqfq) ([raw file](https://github.com/cockroachdb/cockroach/blob/2e95596d84f0362d1df65a0dbf482499c1a82c56/pkg/kv/kvserver/loqrecovery/plan.go#L81)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

This comment doesn't explain anything. They're also not really "anomalies", they're generally "problems", right? Should we just call this `Problems` and `[]Problem`?
</blockquote></details>

Isn't Problem too broad, PlanningProblem maybe?
___
*[pkg/kv/kvserver/loqrecovery/collect_raft_log_test.go, line 213 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/74654#-MuzkyHY6Bhi64lCpz4e:-Mv-HPrk7REKklW8xMMJ:b-8fx2u7) ([raw file](https://github.com/cockroachdb/cockroach/blob/2e95596d84f0362d1df65a0dbf482499c1a82c56/pkg/kv/kvserver/loqrecovery/collect_raft_log_test.go#L213)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

Why not just `reflect.DeepEqual(value, v)`?
</blockquote></details>

:+1:

**Review by tbg — APPROVED** [review]
Only nits left, so feel free to merge when it looks good to you & there haven't been any nontrivial changes. I might not be back at my computer until much later.

> Reviewed 9 of 9 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/74654#-:-Mv2p0nW7GKvb-R7qTzR:b8t4xhx)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @aliher1911 and @erikgrinaker)

___
*[pkg/cli/debug.go, line 1658 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/74654#-MuzdbgJ3jMRbleSXFx-:-Mv2moUc4ti23KgAZOP-:b-4t11q4) ([raw file](https://github.com/cockroachdb/cockroach/blob/2e95596d84f0362d1df65a0dbf482499c1a82c56/pkg/cli/debug.go#L1658)):*
<details><summary><i>Previously, aliher1911 (Oleg) wrote…</i></summary><blockquote>

I'll put it as "override safety checks for recovered replica state" since that's what we actually do. Without getting into details of checks or effects.
</blockquote></details>

I think it's worth using some of the verbiage I suggested. As is, this is downplaying the risk. Oh, we're overriding some safety checks? Probably fine. We should drive home the point that this could turn what was a cluster with one unavailable range into one in which all nodes might be crash-looping on startup, which is arguably worse.
___
*[pkg/cli/debug_recover_loss_of_quorum.go, line 328 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/74654#-Muzf-hb7SloZbX4g9Qc:-Mv2nCHxE3VmZrRLdueh:b-vjnhmk) ([raw file](https://github.com/cockroachdb/cockroach/blob/2e95596d84f0362d1df65a0dbf482499c1a82c56/pkg/cli/debug_recover_loss_of_quorum.go#L328)):*
<details><summary><i>Previously, aliher1911 (Oleg) wrote…</i></summary><blockquote>

I think it depends on if we want to push cli tools further. It would be in conflict with relying on k8s and web console for management.
</blockquote></details>

Yeah, as I mentioned, not suggesting we actually do this. You are right that all of this is moot as we're trying to make this process more online over time.
___
*[pkg/cli/debug_recover_loss_of_quorum.go, line 352 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/74654#-MuzgjDO36GtigKXYsPA:-Mv2nQfE5fU7EjaaqokT:b8pzcgs) ([raw file](https://github.com/cockroachdb/cockroach/blob/2e95596d84f0362d1df65a0dbf482499c1a82c56/pkg/cli/debug_recover_loss_of_quorum.go#L352)):*
<details><summary><i>Previously, aliher1911 (Oleg) wrote…</i></summary><blockquote>

Fair. I finally had to go and check what does typical unix utils do on 'n' and they return 1.
</blockquote></details>

Out of curiosity, which one did you use to check? I had the same instinct but wasn't even sure. Make a write-protected file and `rm`?
___
*[pkg/cli/debug_recover_loss_of_quorum.go, line 345 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/74654#-Mv2ot3c8_JBdsCNmEiH:-Mv2ot3c8_JBdsCNmEiI:bm1kyza) ([raw file](https://github.com/cockroachdb/cockroach/blob/e22aa9b7a016ff2738717ac97c41d8f1cdbe2e8a/pkg/cli/debug_recover_loss_of_quorum.go#L345)):*
> ```Go
> 			}
> 		}
> 	case allYes:
> ```

nit: add a default case here too that errors out? Just makes me nervous not to see one.
___
*[pkg/cli/debug_recover_loss_of_quorum.go, line 353 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/74654#-Mv2nXmW1cmV079URQxL:-Mv2nXmW1cmV079URQxM:b-x1qans) ([raw file](https://github.com/cockroachdb/cockroach/blob/e22aa9b7a016ff2738717ac97c41d8f1cdbe2e8a/pkg/cli/debug_recover_loss_of_quorum.go#L353)):*
nit: might this be confusing? Could this be interpreted as saying that the tool was unable to do its job rather there not being anything to do? Perhaps

> Found no ranges in need of recovery, nothing to do.
___
*[pkg/kv/kvserver/loqrecovery/collect.go, line 71 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/74654#-MuzhjPIEoHLG_VOrLpr:-Mv2nkQ50v4zb-f1IEcm:b-vlj7kj) ([raw file](https://github.com/cockroachdb/cockroach/blob/2e95596d84f0362d1df65a0dbf482499c1a82c56/pkg/kv/kvserver/loqrecovery/collect.go#L71)):*
<details><summary><i>Previously, aliher1911 (Oleg) wrote…</i></summary><blockquote>

Can we remove that without doing any special compatibility dance here since it is not out in a wild yet? 
</blockquote></details>

Yes, just rip it out, it was never released and even if so, you never wrote logic that acted on it.
___
*[pkg/kv/kvserver/loqrecovery/plan.go, line 81 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/74654#-Muzj2goExxXy72ykrE_:-Mv2npvA6wQxZrlxXoIY:b-3a0gft) ([raw file](https://github.com/cockroachdb/cockroach/blob/2e95596d84f0362d1df65a0dbf482499c1a82c56/pkg/kv/kvserver/loqrecovery/plan.go#L81)):*
<details><summary><i>Previously, aliher1911 (Oleg) wrote…</i></summary><blockquote>

Isn't Problem too broad, PlanningProblem maybe?
</blockquote></details>

Not sure, it's not a planning problem, right? It's a problem in general with trying to recover this cluster, which is the scope of where this struct is defined (we happen to surface it during planning, but so what). So I'd still prefer `Problem`, but I'm fine with PlanningProblem too
___
*[pkg/kv/kvserver/loqrecovery/plan.go, line 89 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/74654#-Mv2o260BFi0gD_npG5o:-Mv2o261EHNBiXx30-vh:b-tgi0z9) ([raw file](https://github.com/cockroachdb/cockroach/blob/e22aa9b7a016ff2738717ac97c41d8f1cdbe2e8a/pkg/kv/kvserver/loqrecovery/plan.go#L89)):*
> ```Go
> // produce cluster that is partially unblocked but can have inconsistencies.
> func (p PlanningReport) Error() error {
> 	if len(p.KeyspaceProblems) > 0 {
> ```

drop the "Keyspace"?

**Review by aliher1911 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/74654)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @aliher1911, @erikgrinaker, and @tbg)

___
*[pkg/cli/debug_recover_loss_of_quorum.go, line 352 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/74654#-MuzgjDO36GtigKXYsPA:-Mv3GG5z9vunjt2IUtyP:b-af9w32) ([raw file](https://github.com/cockroachdb/cockroach/blob/2e95596d84f0362d1df65a0dbf482499c1a82c56/pkg/cli/debug_recover_loss_of_quorum.go#L352)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

Out of curiosity, which one did you use to check? I had the same instinct but wasn't even sure. Make a write-protected file and `rm`?
</blockquote></details>

I went for `apt` when it asks to install additional packages if you reject it bails with error.
___
*[pkg/kv/kvserver/loqrecovery/plan.go, line 81 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/74654#-Muzj2goExxXy72ykrE_:-Mv3KWotCAqvXjgtuV4X:b-wemlrn) ([raw file](https://github.com/cockroachdb/cockroach/blob/2e95596d84f0362d1df65a0dbf482499c1a82c56/pkg/kv/kvserver/loqrecovery/plan.go#L81)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

Not sure, it's not a planning problem, right? It's a problem in general with trying to recover this cluster, which is the scope of where this struct is defined (we happen to surface it during planning, but so what). So I'd still prefer `Problem`, but I'm fine with PlanningProblem too
</blockquote></details>

Naming is hard... I was trying to avoid using short ambiguous common names because they cause annoyances when you do refactoring in ide. They cause explosion of proposed comment changes that has to be rectified manually. Its fine in code where they are qualified, but tools are not smart enough. Anyways, wrong names are worse than ide problems so I'll make it problem and also change the error that incloses it.

**Review by tbg — APPROVED** [review]
> Reviewed 4 of 4 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/74654)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @aliher1911 and @erikgrinaker)

___
*[pkg/cli/debug_recover_loss_of_quorum.go, line 351 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/74654#-Mv3Nruz6gApYjvvwReF:-Mv3Nruz6gApYjvvwReG:b-u2z8l7) ([raw file](https://github.com/cockroachdb/cockroach/blob/a9314d01bdb34d9c3eaf96b75bac8adf7e42a277/pkg/cli/debug_recover_loss_of_quorum.go#L351)):*
> ```Go
> 		}
> 	default:
> 		return errors.New("Unexpected CLI error. Try using different --confirm option value.")
> ```

nit: this shouldn't be capitalized and no `.`, right? Since it's an error.
(not worth another trip through CI if this is the only thing)

**Comment by aliher1911** [comment]
bors r=tbg
