### PR TITLE
Ensure gossip callbacks are run in order.

### LINKED ISSUE #3697: Failed tests (10813): TestGetZoneConfig
The following test appears to have failed:

[#10813](https://circleci.com/gh/cockroachdb/cockroach/10813):

```
Wr@0.000000000,0  127.0.0.1:0  10:07:47.004077  10.41µs     ·meta descriptor lookup       kv/dist_sender.go:562
Wr@0.000000000,0  127.0.0.1:0  10:07:47.004098  1.87545ms   ·sending RPC                  kv/dist_sender.go:422
Wr@0.000000000,0  127.0.0.1:0  10:07:47.004143  0           ··sending to 127.0.0.1:45380  rpc/send.go:154

I0108 10:07:49.317899 860 storage/engine/rocksdb.go:137  closing in-memory rocksdb instance
--- FAIL: TestGetZoneConfig (17.33s)
	config_test.go:192: failed to get latest system config: sql/config_test.go:77: condition failed to evaluate true within 10s
=== RUN   TestDatabaseDescriptor
I0108 10:07:49.321931 860 rpc/clock_offset.go:153  monitoring cluster offset
I0108 10:07:49.327860 860 raft/raft.go:446  [group 1] 1 became follower at term 5
I0108 10:07:49.327920 860 raft/raft.go:234  [group 1] newRaft 1 [peers: [1], term: 5, commit: 10, applied: 10, lastindex: 10, lastterm: 5]
I0108 10:07:49.327938 860 raft/raft.go:526  [group 1] 1 is starting a new election at term 5
I0108 10:07:49.327954 860 raft/raft.go:459  [group 1] 1 became candidate at term 6
I0108 10:07:49.327968 860 raft/raft.go:508  [group 1] 1 received vote from 1 at term 6
I0108 10:07:49.327993 860 raft/raft.go:487  [group 1] 1 became leader at term 6
I0108 10:07:49.328739 860 storage/replica_command.go:1198  range 1: new leader lease replica {1 1 1} 1970-01-01 00:00:00 +0000 UTC +1452247670.328s
--
--- PASS: TestValidateTableDesc (0.00s)
=== RUN   TestColumnTypeSQLString
--- PASS: TestColumnTypeSQLString (0.01s)
=== RUN   TestInitialKeys
--- PASS: TestInitialKeys (0.00s)
FAIL
FAIL	github.com/cockroachdb/cockroach/sql	64.467s
=== RUN   TestNoLinkForbidden
--- PASS: TestNoLinkForbidden (0.12s)
=== RUN   TestDates
I0108 10:07:31.869088 854 rpc/clock_offset.go:153  monitoring cluster offset
I0108 10:07:31.873059 854 raft/raft.go:446  [group 1] 1 became follower at term 5
I0108 10:07:31.873151 854 raft/raft.go:234  [group 1] newRaft 1 [peers: [1], term: 5, commit: 10, applied: 10, lastindex: 10, lastterm: 5]
I0108 10:07:31.873227 854 raft/raft.go:526  [group 1] 1 is starting a new election at term 5
I0108 10:07:31.873261 854 raft/raft.go:459  [group 1] 1 became candidate at term 6
I0108 10:07:31.873296 854 raft/raft.go:508  [group 1] 1 received vote from 1 at term 6
I0108 10:07:31.873456 854 raft/raft.go:487  [group 1] 1 became leader at term 6

```
Please assign, take a look and update the issue accordingly.

### PR DESCRIPTION
**Pull request by petermattis**
This showed up in TestGetZoneConfig where back-to-back callbacks for the
system config were reordered causing the newer config to be called back
first and then for the older config to overwrite it. We could have fixed
the problem for system configs by changing `Gossip.updateSystemConfig`
to retrieve the most recent info from the `infoStore`. Enforcing
callback ordering seems like a safer solution for other users of the
gossip callbacks as well.

Fixes #3697.

[Review on Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/3727)

### CODE REVIEW

File: config/config.go [hunk 1]
```diff
@@ -117,6 +118,18 @@ func ObjectIDForKey(key roachpb.RKey) (uint32, bool) {
...
+func (s SystemConfig) Hash() []byte {
+	sha := sha1.New()
+	for _, kv := range s.Values {
+		_, _ = sha.Write(kv.Key)
+		// There are all kinds of different types here, so we can't use the typed
+		// getters.
+		_, _ = sha.Write(kv.Value.RawBytes)
+	}
+	return sha.Sum(nil)
+}
```
Comment (petermattis) [inline config/config.go]: This is movement of code from `Replica.loadSystemDBSpan` so that I could generate the `SystemConfig` hash in other places while debugging #3697.

File: gossip/infostore.go [hunk 2]
```diff
@@ -101,8 +105,8 @@ func (is *infoStore) String() string {
 }
 
 // newInfoStore allocates and returns a new infoStore.
-func newInfoStore(nodeID roachpb.NodeID, nodeAddr util.UnresolvedAddr) infoStore {
-	return infoStore{
+func newInfoStore(nodeID roachpb.NodeID, nodeAddr util.UnresolvedAddr) *infoStore {
+	return &infoStore{
```
Comment (petermattis) [inline gossip/infostore.go]: Returning a pointer now because of the mutexes.

File: gossip/infostore.go [hunk 3]
```diff
@@ -237,11 +241,34 @@ func (is *infoStore) processCallbacks(key string, content roachpb.Value) {
...
+	}
+	is.callbackMu.Lock()
+	is.callbackWork = append(is.callbackWork, f)
+	is.callbackMu.Unlock()
+
+	// Run callbacks in a goroutine to avoid mutex reentry. We also guarantee
+	// callbacks are run in order such that if a key is updated twice in
+	// succession, the second callback will never be run before the first.
+	go func() {
+		// Grab the callback semaphore to prevent another goroutine from invoking
```
Comment (bdarnell) [inline gossip/infostore.go]: I see what you're doing here, but I'm unfamiliar with this usage of the word "semaphore" (as a distinction from `callbackMu`). Renaming one or both variables or providing more comments might be helpful.

**Comment by bdarnell** [comment]
LGTM, but this conflicts with @nvanbenschoten 's #3522. We should decide whether we want to continue with the move to channels or if callbacks with an in-order guarantee are enough.

**Comment by nvanbenschoten** [comment]
I think we had decided that the need for updates to be run to completion before the next one begins indicates that callbacks are more well suited for this problem. If so, this is a simpler solution than mine so we should probably go with this.

That said, it looks like this also runs into the infinite buffering issue #3522 had in the case of a stalled/slow callback. I'm not sure if this is something that is possible to avoid without other tradeoffs.

**Comment by tschottdorf** [comment]
LGTM

---

Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/3727#-:-K7jetNMrWYSoRLb7xDL:676834233)*

File: gossip/infostore.go (hunk 3 above)
Comment (petermattis) [inline gossip/infostore.go]: I'm using semaphore in the sense of a gate for a limited resource (the number of goroutines invoking callbacks). More idiomatic would be to use a channel of length 1, but a mutex is simpler here. Note I don't want to hold `callbackMu` while invoking the callbacks as doing so leads to potential mutex reentrancy issues that we're trying to avoid. Let me see if I can come up with a better term than semaphore.

**Comment by petermattis** [comment]
I don't see an easy way around infinite buffering of callbacks if the callback handler is slow or blocked.

**Comment by bdarnell** [comment]
The only way to avoid infinite buffering is finite buffering, i.e. allowing slow callbacks to block gossip. I'd find that preferable to infinite buffering (and the resulting swapping or OOM), but I'm not particularly concerned about it in this case.
