### PR TITLE
server: fix flaking TestTriggerMetadataUpdateJob test

### LINKED ISSUE #133415: server: TestTriggerMetadataUpdateJob failed
server.TestTriggerMetadataUpdateJob [failed](https://mesolite.cluster.engflow.com/invocations/default/0f8357ce-4bdf-43c3-9f63-d7302aac348e?testReportRun=1&testReportShard=6&testReportAttempt=1#targets-Ly9wa2cvc2VydmVyOnNlcnZlcl90ZXN0) on release-24.3 @ [48c76930900da33349ea1d2311400bde625034d1](https://github.com/cockroachdb/cockroach/commits/48c76930900da33349ea1d2311400bde625034d1):

```
=== RUN   TestTriggerMetadataUpdateJob
    test_log_scope.go:165: test logs captured to: outputs.zip/logTestTriggerMetadataUpdateJob3829247884
    test_log_scope.go:76: use -show-logs to present logs inline
    test_server_shim.go:139: cluster virtualization disabled in global scope due to issue: #76378 (expected label: C-bug)
    api_v2_databases_metadata_test.go:838: -- test log scope end --
test logs left over in: outputs.zip/logTestTriggerMetadataUpdateJob3829247884
--- FAIL: TestTriggerMetadataUpdateJob (30.60s)
=== RUN   TestTriggerMetadataUpdateJob/staleness
    api_v2_databases_metadata_test.go:862: 
        	Error Trace:	github.com/cockroachdb/cockroach/pkg/server/api_v2_databases_metadata_test.go:862
        	            				github.com/cockroachdb/cockroach/pkg/server/api_v2_databases_metadata_test.go:836
        	Error:      	"Job is already running" does not contain "Job triggered successfully"
        	Test:       	TestTriggerMetadataUpdateJob/staleness
    --- FAIL: TestTriggerMetadataUpdateJob/staleness (1.97s)
```

Parameters:
 - <code>attempt=1</code>
 - <code>run=1</code>
 - <code>shard=6</code>
<details><summary>Help</summary>
<p>

See also: [How To Investigate a Go Test Failure \(internal\)](https://cockroachlabs.atlassian.net/l/c/HgfXfJgM)
</p>
</details>
<details><summary>Same failure on other branches</summary>
<p>

- #132910 server: TestTriggerMetadataUpdateJob failed [C-test-failure O-robot P-3 T-observability branch-master]
</p>
</details>
/cc @cockroachdb/obs-prs @cockroachdb/server
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*TestTriggerMetadataUpdateJob.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/bazci/githubpost/issues)
</sub>

Jira issue: CRDB-43594

### PR DESCRIPTION
**Pull request by kyle-a-wong**
This test is failing due to the asynchronous nature of the update table metadata job and the triggering of it via the http endpoint. The test makes assumptions about when the job is ready and able to be triggered successfully, but there is no deterministic way to determine so, making the test flake.

To fix, we wrap the API call in SucceedsSoon() to retry the request if the job isn't ready to be triggered.

Release note: None
Fixes #133415, #132910

### CODE REVIEW

File: pkg/server/api_v2_databases_metadata_test.go [hunk 1]
```diff
@@ -894,11 +898,20 @@ func makeApiRequest[T any](
 	return mdResp
 }
 
-func assertJobTriggered(t *testing.T, client http.Client, url string, c chan interface{}) {
-	resp := makeApiRequest[tmJobTriggeredResponse](t, client, url, http.MethodPost)
-	require.Contains(t, resp.Message, "Job triggered successfully")
-	require.True(t, resp.JobTriggered)
-	<-c
+func assertJobTriggered(
```
Comment (dhartunian) [inline pkg/server/api_v2_databases_metadata_test.go:901]: nit: should this function name be different? I would prefer `triggerAndWaitForJobToComplete`

File: pkg/sql/tablemetadatacache/util/util.go [hunk 2]
```diff
@@ -14,3 +14,12 @@ import "context"
 type ITableMetadataUpdater interface {
 	RunUpdater(ctx context.Context) error
 }
+
+// NoopUpdater is an implementation of ITableMetadataUpdater that performs a noop when RunUpdater is called.
```
Comment (dhartunian) [inline pkg/sql/tablemetadatacache/util/util.go:18]: This should only be used in tests right? Maybe note that.

Comment (kyle-a-wong) [reply pkg/sql/tablemetadatacache/util/util.go:18]: Done

File: pkg/server/api_v2_databases_metadata_test.go [hunk 3]
```diff
@@ -752,31 +754,34 @@ func TestGetTableMetadataUpdateJobStatus(t *testing.T) {
...
+	ts := serverutils.StartServerOnly(t, base.TestServerArgs{
+		Knobs: base.TestingKnobs{
+			TableMetadata: &tablemetadatacacheutil.TestingKnobs{
+				OnJobReady: func() {
+					jobReadyChan <- struct{}{}
+				},
+				OnJobComplete: func() {
+					jobCompletedChan <- struct{}{}
+				},
+				TableMetadataUpdater: &tablemetadatacacheutil.NoopUpdater{},
```
[the remark this answers is not in the document]
Comment (kyle-a-wong) [reply pkg/server/api_v2_databases_metadata_test.go:772]: I don't think we need to run / test the actual job here since we already have coverage for that in other tests. All we care about for these tests is the triggering of the job and not the actually updating of the tables.

File: pkg/server/api_v2_databases_metadata_test.go [hunk 4]
```diff
@@ -811,7 +816,7 @@ func TestTriggerMetadataUpdateJob(t *testing.T) {
 
 	t.Run("staleness", func(t *testing.T) {
 		assertJobTriggered(t, client, url, jobCompletedChan)
-		// Trigger again should succeed
+		// Trigger again should since the DataValidDurationSetting value is ignored by default
```
[the remark this answers is not in the document]
Comment (kyle-a-wong) [reply pkg/server/api_v2_databases_metadata_test.go]: Done

File: pkg/server/api_v2_databases_metadata_test.go (hunk 1 above)
Comment (kyle-a-wong) [reply pkg/server/api_v2_databases_metadata_test.go]: Done

File: pkg/server/api_v2_databases_metadata_test.go [hunk 5]
```diff
@@ -752,89 +754,91 @@ func TestGetTableMetadataUpdateJobStatus(t *testing.T) {
...
-		assertJobTriggered(t, client, url, jobCompletedChan)
-		// Trigger again should succeed
-		assertJobTriggered(t, client, url, jobCompletedChan)
+		triggerAndWaitForJobToComplete(t, client, url, jobCompletedChan)
+		// Triggering again should succeed since the DataValidDurationSetting value is ignored by default.
+		triggerAndWaitForJobToComplete(t, client, url, jobCompletedChan)
 
 		tablemetadatacache.DataValidDurationSetting.Override(ctx, &ts.ClusterSettings().SV, time.Minute)
-		// call trigger job api with onlyIfStale flag. This shouldn't trigger the job again since a minute hasn't passed
+		// call trigger job api with onlyIfStale flag. This shouldn't trigger the job again since a minute hasn't passed.
```
Comment (xinhaoz) [inline pkg/server/api_v2_databases_metadata_test.go:823]: nit: capitalization

File: pkg/server/api_v2_databases_metadata_test.go [hunk 6]
```diff
@@ -752,89 +754,91 @@ func TestGetTableMetadataUpdateJobStatus(t *testing.T) {
...
 			t, client, ts.AdminURL().WithPath(uri+"?onlyIfStale=somevalue").String(), http.MethodPost)
 		require.Contains(t, resp.Message, "Not enough time has elapsed since last job run")
 		require.False(t, resp.JobTriggered)
 
-		// set data_valid_duration to 1ms
 		tablemetadatacache.DataValidDurationSetting.Override(ctx, &ts.ClusterSettings().SV, time.Millisecond)
 		// call trigger job api with onlyIfStale flag. This should trigger the job again since 1ms has passed since last
-		// completion
-		assertJobTriggered(t, client, ts.AdminURL().WithPath(uri+"?onlyIfStale").String(), jobCompletedChan)
+		// completion.
```
Comment (xinhaoz) [inline pkg/server/api_v2_databases_metadata_test.go:840]: nit: same here with capitalization on `call` above.

**Review by xinhaoz — APPROVED** [review]

File: pkg/server/api_v2_databases_metadata_test.go (hunk 5 above)
Comment (kyle-a-wong) [reply pkg/server/api_v2_databases_metadata_test.go]: Done

File: pkg/server/api_v2_databases_metadata_test.go (hunk 6 above)
Comment (kyle-a-wong) [reply pkg/server/api_v2_databases_metadata_test.go:840]: Done

**Comment by kyle-a-wong** [comment]
tftr!

bors r+
