### PR TITLE
jobs: handle retryable errors waiting for jobs

### LINKED ISSUE #110642: sql/catalog/lease: TestLeaseManagerReacquire failed
sql/catalog/lease.TestLeaseManagerReacquire [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_StressBazel/11775352?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_StressBazel/11775352?buildTab=artifacts#/) on master @ [0cde11b885a5e156b970c003505acd081fb4f326](https://github.com/cockroachdb/cockroach/commits/0cde11b885a5e156b970c003505acd081fb4f326):

```
=== RUN   TestLeaseManagerReacquire
    test_log_scope.go:167: test logs captured to: /artifacts/tmp/_tmp/ce8d73b4a4081f39d36a7fa2c2508fcc/logTestLeaseManagerReacquire73285229
    test_log_scope.go:81: use -show-logs to present logs inline
    test_server_shim.go:124: automatically injected virtual cluster under test; see comment at top of test_server_shim.go for details.
    testcluster.go:495: polling for queued jobs to complete: liveness session expired 11.248409ms before transaction
    panic.go:522: -- test log scope end --
test logs left over in: /artifacts/tmp/_tmp/ce8d73b4a4081f39d36a7fa2c2508fcc/logTestLeaseManagerReacquire73285229
--- FAIL: TestLeaseManagerReacquire (37.55s)
```
<p>Parameters: <code>TAGS=bazel,gss,deadlock</code>
, <code>stress=true</code>
</p>
<details><summary>Help</summary>
<p>

See also: [How To Investigate a Go Test Failure \(internal\)](https://cockroachlabs.atlassian.net/l/c/HgfXfJgM)
</p>
</details>
/cc @cockroachdb/sql-foundations
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*TestLeaseManagerReacquire.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)
</sub>

Jira issue: CRDB-31540

### LINKED ISSUE #111166: sql/catalog/lease: TestLeaseBulkInsertWithImplicitTxn failed
sql/catalog/lease.TestLeaseBulkInsertWithImplicitTxn [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_StressBazel/11900509?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_StressBazel/11900509?buildTab=artifacts#/) on master @ [b1a641f1d27653a4e93154926be57d0cae864bd6](https://github.com/cockroachdb/cockroach/commits/b1a641f1d27653a4e93154926be57d0cae864bd6):

```
=== RUN   TestLeaseBulkInsertWithImplicitTxn
    test_log_scope.go:167: test logs captured to: /artifacts/tmp/_tmp/ce8d73b4a4081f39d36a7fa2c2508fcc/logTestLeaseBulkInsertWithImplicitTxn2251022669
    test_log_scope.go:81: use -show-logs to present logs inline
    test_server_shim.go:124: automatically injected virtual cluster under test; see comment at top of test_server_shim.go for details.
    testcluster.go:495: polling for queued jobs to complete: liveness session expired 4.30799ms before transaction
    panic.go:540: -- test log scope end --
test logs left over in: /artifacts/tmp/_tmp/ce8d73b4a4081f39d36a7fa2c2508fcc/logTestLeaseBulkInsertWithImplicitTxn2251022669
--- FAIL: TestLeaseBulkInsertWithImplicitTxn (56.64s)
```
<p>Parameters: <code>TAGS=bazel,gss</code>
, <code>stress=true</code>
</p>
<details><summary>Help</summary>
<p>

See also: [How To Investigate a Go Test Failure \(internal\)](https://cockroachlabs.atlassian.net/l/c/HgfXfJgM)
</p>
</details>
/cc @cockroachdb/sql-foundations
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*TestLeaseBulkInsertWithImplicitTxn.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)
</sub>

Jira issue: CRDB-31800

### LINKED ISSUE #112180: sql/catalog/lease: TestLeaseManagerReacquire failed
sql/catalog/lease.TestLeaseManagerReacquire [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_StressBazel/12141885?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_StressBazel/12141885?buildTab=artifacts#/) on release-23.2 @ [437fa1b407bb5078a2a98c0fb5b8e5436a3be926](https://github.com/cockroachdb/cockroach/commits/437fa1b407bb5078a2a98c0fb5b8e5436a3be926):

```
=== RUN   TestLeaseManagerReacquire
    test_log_scope.go:170: test logs captured to: /artifacts/tmp/_tmp/ce8d73b4a4081f39d36a7fa2c2508fcc/logTestLeaseManagerReacquire215498779
    test_log_scope.go:81: use -show-logs to present logs inline
    test_server_shim.go:124: automatically injected virtual cluster under test; see comment at top of test_server_shim.go for details.
    testcluster.go:479: polling for queued jobs to complete: liveness session expired 9.303521ms before transaction
    panic.go:522: -- test log scope end --
--- FAIL: TestLeaseManagerReacquire (34.12s)
```
<p>Parameters: <code>TAGS=bazel,gss,deadlock</code>
, <code>stress=true</code>
</p>
<details><summary>Help</summary>
<p>

See also: [How To Investigate a Go Test Failure \(internal\)](https://cockroachlabs.atlassian.net/l/c/HgfXfJgM)
</p>
</details>
<details><summary>Same failure on other branches</summary>
<p>

- #110642 sql/catalog/lease: TestLeaseManagerReacquire failed [C-test-failure O-robot T-sql-foundations branch-master]
</p>
</details>
/cc @cockroachdb/sql-foundations
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*TestLeaseManagerReacquire.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)
</sub>

Jira issue: CRDB-32279

### LINKED ISSUE #112377: sql/catalog/lease: TestLeaseRenewedPeriodically failed
sql/catalog/lease.TestLeaseRenewedPeriodically [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_StressBazel/12181157?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_StressBazel/12181157?buildTab=artifacts#/) on release-23.2 @ [abd56c6d6e9dbf131fc1fa0d3f8d1fbcfb7e4901](https://github.com/cockroachdb/cockroach/commits/abd56c6d6e9dbf131fc1fa0d3f8d1fbcfb7e4901):

```
=== RUN   TestLeaseRenewedPeriodically
    test_log_scope.go:170: test logs captured to: /artifacts/tmp/_tmp/ce8d73b4a4081f39d36a7fa2c2508fcc/logTestLeaseRenewedPeriodically1563480565
    test_log_scope.go:81: use -show-logs to present logs inline
    test_server_shim.go:124: automatically injected virtual cluster under test; see comment at top of test_server_shim.go for details.
    testcluster.go:479: polling for queued jobs to complete: liveness session expired 296.830235ms before transaction
    panic.go:522: -- test log scope end --
test logs left over in: /artifacts/tmp/_tmp/ce8d73b4a4081f39d36a7fa2c2508fcc/logTestLeaseRenewedPeriodically1563480565
--- FAIL: TestLeaseRenewedPeriodically (171.00s)
```
<p>Parameters: <code>TAGS=bazel,gss,deadlock</code>
, <code>stress=true</code>
</p>
<details><summary>Help</summary>
<p>

See also: [How To Investigate a Go Test Failure \(internal\)](https://cockroachlabs.atlassian.net/l/c/HgfXfJgM)
</p>
</details>
/cc @cockroachdb/sql-foundations
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*TestLeaseRenewedPeriodically.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)
</sub>

Jira issue: CRDB-32382

### LINKED ISSUE #112392: sql/catalog/lease: TestLeaseRenewedPeriodically failed
sql/catalog/lease.TestLeaseRenewedPeriodically [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_StressBazel/12189626?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_StressBazel/12189626?buildTab=artifacts#/) on master @ [96ab72f95759b6a40c5c2bc67c37101f3590ddd3](https://github.com/cockroachdb/cockroach/commits/96ab72f95759b6a40c5c2bc67c37101f3590ddd3):

```
=== RUN   TestLeaseRenewedPeriodically
    test_log_scope.go:170: test logs captured to: /artifacts/tmp/_tmp/ce8d73b4a4081f39d36a7fa2c2508fcc/logTestLeaseRenewedPeriodically3523295582
    test_log_scope.go:81: use -show-logs to present logs inline
    test_server_shim.go:124: automatically injected virtual cluster under test; see comment at top of test_server_shim.go for details.
    testcluster.go:479: liveness session expired 158.408474ms before transaction
    panic.go:540: -- test log scope end --
test logs left over in: /artifacts/tmp/_tmp/ce8d73b4a4081f39d36a7fa2c2508fcc/logTestLeaseRenewedPeriodically3523295582
--- FAIL: TestLeaseRenewedPeriodically (322.48s)
```
<p>Parameters: <code>TAGS=bazel,gss</code>
, <code>stress=true</code>
</p>
<details><summary>Help</summary>
<p>

See also: [How To Investigate a Go Test Failure \(internal\)](https://cockroachlabs.atlassian.net/l/c/HgfXfJgM)
</p>
</details>
<details><summary>Same failure on other branches</summary>
<p>

- #112377 sql/catalog/lease: TestLeaseRenewedPeriodically failed [C-test-failure O-robot T-sql-foundations branch-release-23.2 release-blocker]
</p>
</details>
/cc @cockroachdb/sql-foundations
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*TestLeaseRenewedPeriodically.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)
</sub>

Jira issue: CRDB-32394

### LINKED ISSUE #112696: sql/catalog/lease: TestLeaseBulkInsertWithImplicitTxn failed
sql/catalog/lease.TestLeaseBulkInsertWithImplicitTxn [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_StressBazel/12253333?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_StressBazel/12253333?buildTab=artifacts#/) on release-23.2 @ [c4341be986ab7fbdf86e829b54a35eaa7cf5b9fc](https://github.com/cockroachdb/cockroach/commits/c4341be986ab7fbdf86e829b54a35eaa7cf5b9fc):

```
=== RUN   TestLeaseBulkInsertWithImplicitTxn
    test_log_scope.go:170: test logs captured to: /artifacts/tmp/_tmp/ce8d73b4a4081f39d36a7fa2c2508fcc/logTestLeaseBulkInsertWithImplicitTxn2201251054
    test_log_scope.go:81: use -show-logs to present logs inline
    test_server_shim.go:124: automatically injected virtual cluster under test; see comment at top of test_server_shim.go for details.
    testcluster.go:479: polling for queued jobs to complete: liveness session expired 30.685704ms before transaction
    panic.go:522: -- test log scope end --
test logs left over in: /artifacts/tmp/_tmp/ce8d73b4a4081f39d36a7fa2c2508fcc/logTestLeaseBulkInsertWithImplicitTxn2201251054
--- FAIL: TestLeaseBulkInsertWithImplicitTxn (75.67s)
```
<p>Parameters: <code>TAGS=bazel,gss,deadlock</code>
, <code>stress=true</code>
</p>
<details><summary>Help</summary>
<p>

See also: [How To Investigate a Go Test Failure \(internal\)](https://cockroachlabs.atlassian.net/l/c/HgfXfJgM)
</p>
</details>
<details><summary>Same failure on other branches</summary>
<p>

- #111166 sql/catalog/lease: TestLeaseBulkInsertWithImplicitTxn failed [C-test-failure O-robot T-sql-foundations branch-master]
</p>
</details>
/cc @cockroachdb/sql-foundations
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*TestLeaseBulkInsertWithImplicitTxn.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)
</sub>

Jira issue: CRDB-32556

### PR DESCRIPTION
**Pull request by fqazi**
Previously, when waiting for jobs if the internal executor hit any retryable errors, we would incorrectly bubble these errors up. This would intermittently be seen in leasing tests, which intentionally disable renewals, increasing the likelihood of transaction retry errors. To address this, this patch will modify waitForJobs to handle retryable errors gracefully.

Fixes: #112392
fixes #110642
fixes #111166
fixes https://github.com/cockroachdb/cockroach/issues/112696
fixes https://github.com/cockroachdb/cockroach/issues/112180
fixes https://github.com/cockroachdb/cockroach/issues/112377

Release note: None

### CODE REVIEW

File: pkg/jobs/wait.go [hunk 1]
```diff
@@ -118,6 +119,12 @@ func (r *Registry) waitForJobsToBeTerminalOrPaused(
 			query,
 		)
 		if err != nil {
+			// While polling, we could encounter retryable errors, which may
+			// not get internally retried in the connection executor. So retry,
+			// here.
+			if errors.HasInterface(err, (*pgerror.ClientVisibleRetryError)(nil)) {
```
Comment (rafiss) [inline pkg/jobs/wait.go:125]: nice find! a few semi-related comments before we go with this:
- could you add a comment that mentions that this is safe to retry here because we use a new txn for each query?
- also i'm a bit surprised - the internal executor is supposed to retry this automatically. so it feels like something else must be going wrong if that isn't working. 
- could we avoid retry errors by making `makeWaitForJobsQuery` use a fixed timestamp?
- there should be a test that reproduces the problem reliably so we can make sure the fix works going forwards. this test would also help us understand why the internal executor did not retry.

**Review by rafiss — CHANGES_REQUESTED** [review]

File: pkg/jobs/wait.go (hunk 1 above)
Comment (fqazi) [reply pkg/jobs/wait.go:125]: > also i'm a bit surprised - the internal executor is supposed to retry this automatically. so it feels like something else must be going wrong if that isn't working.

@rafiss It's because results are returned to the client, so it's no longer safe to retry internally in this case. Let me double check and confirm that one more time too

**Review by fqazi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/112613)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dt and @rafiss)

___
*[`pkg/jobs/wait.go` line 125 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/112613#gh-1365803867:-NhEtQax5u_MsmcQKkOK:b-k1aaf9) ([raw file](https://github.com/cockroachdb/cockroach/blob/21cdfef8955dd41b79de522f541cb40de8e0b527/pkg/jobs/wait.go#L125)):*
> -   could you add a comment that mentions that this is safe to retry here because we use a new txn for each query?

Done

> also i'm a bit surprised - the internal executor is supposed to retry this automatically. so it feels like something else must be going wrong if that isn't working.

Confirmed this is linked to the results being returned.

> could we avoid retry errors by making `makeWaitForJobsQuery` use a fixed timestamp?

I think that will avoid them, but I think it will incur a latency right? i.e. We will keep on looking slowly at the past until we hit the future?

> there should be a test that reproduces the problem reliably so we can make sure the fix works going forwards. this test would also help us understand why the internal executor did not retry.

I added an internal test which forces the scenario by disabling lease renewals.

**Review by rafiss — CHANGES_REQUESTED** [review]
nice findings. i had a question about detecting the retries, but otherwise lgtm

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/112613#-:-Nhba3WZ5fqDcnUByS1Y:b5hc5d)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dt and @fqazi)

___
*[`pkg/sql/internal.go` line 1780 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/112613#-NhbYx7O5Vj4ndWK0Tto:-NhbYx7O5Vj4ndWK0Ttp:b611p6w) ([raw file](https://github.com/cockroachdb/cockroach/blob/395592fd703fcefe313fa7f40ba34414b0383690/pkg/sql/internal.go#L1780)):*
> ```Go
> 			return commitTxnFn(ctx)
> 		}); descs.IsTwoVersionInvariantViolationError(err) ||
> 			errors.HasInterface(err, (*pgerror.ClientVisibleRetryError)(nil)) {
> ```

should this if check be replaced with a call to `errIsRetriable`. it is defined as:
```
// errIsRetriable is true if the error is a client-visible retry error
// or the error is a special error that is handled internally and retried.
func errIsRetriable(err error) bool {
	return errors.HasInterface(err, (*pgerror.ClientVisibleRetryError)(nil)) ||
		errors.Is(err, retriableMinTimestampBoundUnsatisfiableError) ||
		// Note that this error is not handled internally and can make it to the
		// client in implicit transactions. This is not great; it should
		// be marked as a client visible retry error.
		errors.Is(err, descidgen.ErrDescIDSequenceMigrationInProgress) ||
		descs.IsTwoVersionInvariantViolationError(err)
}
```

or what about using `convertRetriableErrorIntoUserVisibleError` which was added in 0a1be2f1bb43c68028b37bfe2d8768be6200bddb
___
*[`pkg/jobs/registry_external_test.go` line 767 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/112613#-NhbZq8721-rmvAroAY4:-NhbZq8721-rmvAroAY5:b-jiv34u) ([raw file](https://github.com/cockroachdb/cockroach/blob/395592fd703fcefe313fa7f40ba34414b0383690/pkg/jobs/registry_external_test.go#L767)):*
> ```Go
> 		return jobs.FakeResumer{}
> 	}, jobs.UsesTenantCostControl)
> 	tc := serverutils.StartCluster(t, 3, base.TestClusterArgs{ServerArgs: args})
> ```

does this need a 3 node cluster or does single node work? (if so, use `StartServer`)

**Review by fqazi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/112613)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dt and @rafiss)

___
*[`pkg/sql/internal.go` line 1780 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/112613#-NhbYx7O5Vj4ndWK0Tto:-Ni2_4m33aB8GPXSqb1V:b30wws3) ([raw file](https://github.com/cockroachdb/cockroach/blob/395592fd703fcefe313fa7f40ba34414b0383690/pkg/sql/internal.go#L1780)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

should this if check be replaced with a call to `errIsRetriable`. it is defined as:
```
// errIsRetriable is true if the error is a client-visible retry error
// or the error is a special error that is handled internally and retried.
func errIsRetriable(err error) bool {
	return errors.HasInterface(err, (*pgerror.ClientVisibleRetryError)(nil)) ||
		errors.Is(err, retriableMinTimestampBoundUnsatisfiableError) ||
		// Note that this error is not handled internally and can make it to the
		// client in implicit transactions. This is not great; it should
		// be marked as a client visible retry error.
		errors.Is(err, descidgen.ErrDescIDSequenceMigrationInProgress) ||
		descs.IsTwoVersionInvariantViolationError(err)
}
```

or what about using `convertRetriableErrorIntoUserVisibleError` which was added in 0a1be2f1bb43c68028b37bfe2d8768be6200bddb
</blockquote></details>

Done.

Good point. I switched over to `errIsRetriable`. I think for `convertRetriableErrorIntoUserVisibleError` would need to catch bot errors in the txn
___
*[`pkg/jobs/registry_external_test.go` line 767 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/112613#-NhbZq8721-rmvAroAY4:-Ni2_Gpj-1fVaqcXKRBM:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/395592fd703fcefe313fa7f40ba34414b0383690/pkg/jobs/registry_external_test.go#L767)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

does this need a 3 node cluster or does single node work? (if so, use `StartServer`)
</blockquote></details>

Done.

**Review by rafiss — APPROVED** [review]
ty! 

> Reviewed 2 of 4 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/112613#-:-Ni63-FO4iQVjDE2Z2zF:bb7pfxl)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dt)

**Comment by fqazi** [comment]
@rafiss TFTR!

bors r+

**Comment by rafiss** [comment]
I fixed the CLA check

bors r+

**Comment by yuzefovich** [comment]
CI is red here.

bors r-

**Comment by yuzefovich** [comment]
Also @rafiss I see you added "branch-release-23.2" label - did you mean the 23.2 backport label?

**Comment by rafiss** [comment]
flake was `TestStreamingRegionalConstraint`, an unrelated issue (https://github.com/cockroachdb/cockroach/issues/112541).

bors r+

**Comment by fqazi** [comment]
Needed a rebase due to jobstest changes, bors should be happy now

bors r+
