### PR TITLE
Removed MinHops parameter from gossip.

### LINKED ISSUE #4500: circleci: failed tests (13021): TestConvergence TestGossipStorage
The following test appears to have failed:

[#13021](https://circleci.com/gh/cockroachdb/cockroach/13021):

```
I0218 22:41:13.811397 196 gossip/client.go:86  closing client to node 2 (127.0.0.1:55364): EOF
I0218 22:41:13.813903 196 gossip/server.go:197  node 2 received [127.0.0.1:50778] from node 5 (1 fresh)
I0218 22:41:13.816114 196 gossip/server.go:252  @2: distantHops: 3 from 7
I0218 22:41:13.817107 196 gossip/server.go:197  node 2 received [127.0.0.1:50778] from node 5 (0 fresh)
I0218 22:41:13.817267 196 gossip/server.go:252  @2: distantHops: 3 from 7
--- FAIL: TestConvergence (4.82s)
	convergence_test.go:33: expected a fully-connected network within 100 cycles; took 110
=== RUN   TestGossipStorage
I0218 22:41:13.820856 196 gossip/simulation/network.go:60  simulating gossip network with 3 nodes
I0218 22:41:13.828941 196 gossip/gossip.go:939  starting client to 127.0.0.1:46902
I0218 22:41:13.830024 196 gossip/gossip.go:939  starting client to 127.0.0.1:46902
I0218 22:41:13.846986 196 gossip/server.go:113  node 1 returned 4 info(s) to node 3
I0218 22:41:13.847360 196 gossip/server.go:197  node 1 received [] from node 3 (0 fresh)
I0218 22:41:13.847492 196 gossip/server.go:252  @1: distantHops: 0 from 0
I0218 22:41:13.847859 196 gossip/server.go:113  node 1 returned 4 info(s) to node 3
I0218 22:41:13.848246 196 gossip/server.go:113  node 1 returned 4 info(s) to node 2
--
I0218 22:41:13.891752 196 gossip/server.go:252  @3: distantHops: 1 from 1
I0218 22:41:13.892556 196 gossip/client.go:149  node 3 received [node:1 127.0.0.1:46902 sentinel cluster-id node:2 127.0.0.1:44639] from node 1 (2 fresh)
I0218 22:41:13.895575 196 gossip/server.go:252  @3: distantHops: 2 from 2
I0218 22:41:13.895837 196 gossip/simulation/network.go:183  gossip network simulation: total infos sent=32, received=4
==================
WARNING: DATA RACE
Write by goroutine 180:
  github.com/cockroachdb/cockroach/gossip_test.(*testStorage).WriteBootstrapInfo()
      /go/src/github.com/cockroachdb/cockroach/gossip/storage_test.go:64 +0x139
  github.com/cockroachdb/cockroach/gossip.(*Gossip).updateNodeAddress()
      /go/src/github.com/cockroachdb/cockroach/gossip/gossip.go:468 +0xc29
  github.com/cockroachdb/cockroach/gossip.(*Gossip).(github.com/cockroachdb/cockroach/gossip.updateNodeAddress)-fm()
      /go/src/github.com/cockroachdb/cockroach/gossip/gossip.go:193 +0x71
  github.com/cockroachdb/cockroach/gossip.(*infoStore).runCallbacks.func1()
      /go/src/github.com/cockroachdb/cockroach/gossip/infostore.go:270 +0x104
  github.com/cockroachdb/cockroach/gossip.(*infoStore).runCallbacks.func2()
      /go/src/github.com/cockroachdb/cockroach/gossip/infostore.go:292 +0x16a
  github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunAsyncTask.func1()
      /go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:140 +0x73

Previous read by goroutine 207:
  github.com/cockroachdb/cockroach/gossip_test.TestGossipStorage()
      /go/src/github.com/cockroachdb/cockroach/gossip/storage_test.go:111 +0x96f
  testing.tRunner()
      /usr/local/go/src/testing/testing.go:473 +0xdc

Goroutine 180 (running) created at:
  github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunAsyncTask()
      /go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:141 +0xdb
  github.com/cockroachdb/cockroach/gossip.(*infoStore).runCallbacks()
      /go/src/github.com/cockroachdb/cockroach/gossip/infostore.go:294 +0x38e
  github.com/cockroachdb/cockroach/gossip.(*infoStore).processCallbacks()
      /go/src/github.com/cockroachdb/cockroach/gossip/infostore.go:263 +0x311
  github.com/cockroachdb/cockroach/gossip.(*infoStore).addInfo()
      /go/src/github.com/cockroachdb/cockroach/gossip/infostore.go:203 +0x89e
  github.com/cockroachdb/cockroach/gossip.(*infoStore).combine()
      /go/src/github.com/cockroachdb/cockroach/gossip/infostore.go:332 +0x36f
--
  github.com/cockroachdb/cockroach/gossip.(*client).gossip.func2()
      /go/src/github.com/cockroachdb/cockroach/gossip/client.go:234 +0x62
  github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker.func1()
      /go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:98 +0x5f

Goroutine 207 (running) created at:
  testing.RunTests()
      /usr/local/go/src/testing/testing.go:582 +0xae2
  testing.(*M).Run()
      /usr/local/go/src/testing/testing.go:515 +0x11d
  github.com/cockroachdb/cockroach/util/leaktest.TestMainWithLeakCheck()
      /go/src/github.com/cockroachdb/cockroach/util/leaktest/leaktest.go:37 +0x2e
  github.com/cockroachdb/cockroach/gossip_test.TestMain()
      /go/src/github.com/cockroachdb/cockroach/gossip/main_test.go:34 +0x2e
  main.main()
      github.com/cockroachdb/cockroach/gossip/_test/_testmain.go:112 +0x20a
--
3      gossip/infostore.go:294
I0218 22:41:13.979567 196 stopper.go:273  draining; tasks left:
2      gossip/infostore.go:294
I0218 22:41:13.981285 196 gossip/server.go:197  node 1 received [127.0.0.1:40551] from node 3 (0 fresh)
I0218 22:41:13.981431 196 gossip/server.go:252  @1: distantHops: 1 from 3
--- FAIL: TestGossipStorage (0.17s)
	storage_test.go:120: 2: expected addresses: [{tcp 127.0.0.1:44639} {tcp 127.0.0.1:46902}], got: [{tcp 127.0.0.1:46902}]
FAIL
FAIL	github.com/cockroachdb/cockroach/gossip	5.558s
=== RUN   TestParseResolverSpec
--- PASS: TestParseResolverSpec (0.00s)
=== RUN   TestGetAddress
--- PASS: TestGetAddress (0.00s)
PASS
ok  	github.com/cockroachdb/cockroach/gossip/resolver	1.037s
?   	github.com/cockroachdb/cockroach/gossip/simulation	[no test files]
=== RUN   TestKeySorting
--- PASS: TestKeySorting (0.00s)
=== RUN   TestMakeKey

```
Please assign, take a look and update the issue accordingly.

### PR DESCRIPTION
**Pull request by spencerkimball**
It was originally intended to be a part of the network tightening
mechanism but ended up not being used and was getting in the way
of correctly determining which info was fresh between nodes.

The previous broken use of MinHops was preventing efficient relay
of gossip info, causing network convergence to lag.

Fixes #4500

[Review on Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/4502)

### CODE REVIEW

**Comment by spencerkimball** [comment]
@tamird weirdly when I run `gossip/simulation/gossip.go --size=medium` with this change, the grpc connections fail to close properly and it hangs when it's finished. I'm not sure why that would be the case, except perhaps this change makes things happen faster and is exercising some sort of race condition.

**Comment by tamird** [comment]
That does seem weird. I'll look into it first thing tomorrow.

---

Reviewed 9 of 9 files at r1.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[gossip/gossip.proto, line 67 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4502#-KAr2sI7QHafVDylgunO:-KAr2sI85g8a3Jd5o1ry:124549485) ([raw file](https://github.com/cockroachdb/cockroach/blob/74c8d84262c849ea87150c48244301ea390138d5/gossip/gossip.proto#L67)):*
While you're here:
`map<int32,int64> highWaterStamps = 6 [(gogoproto.castkey) = "github.com/cockroachdb/cockroach/roachpb.NodeID", (gogoproto.nullable) = false];`
or leave a todo

---

*[gossip/info.go, line 27 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4502#-KAr1y1D8M-rJWt5Vlb2:-KAr1y1D8M-rJWt5Vlb3:1370864376) ([raw file](https://github.com/cockroachdb/cockroach/blob/74c8d84262c849ea87150c48244301ea390138d5/gossip/info.go#L27)):*
`return i.Origstamp > highWaterStamp`

---

*[gossip/infostore.go, line 191 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4502#-KAr4DTs4rsv1kNCfV7Y:-KAr4DTtfWy2V1WPTA1-:2094011231) ([raw file](https://github.com/cockroachdb/cockroach/blob/74c8d84262c849ea87150c48244301ea390138d5/gossip/infostore.go#L191)):*
no need to check `ok` here

---

*[gossip/simulation/network.go, line 125 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4502#-KAr3bcBkEzPPIlfIxkT:-KAr3bcC8QZKZE1kAV7K:-1321265596) ([raw file](https://github.com/cockroachdb/cockroach/blob/6135537594bdf3936806acac05eab0a6c1f5080d/gossip/simulation/network.go#L125)):*
why make these public?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4502#-:-KAr4c2WMWldsrHGpmve:-894045113)*

**Comment by tamird** [comment]
I see a bunch of error spew at shutdown, but no hang. The error spew is sadly expected, as grpc doesn't expose a synchronous `Close` on the connections (the assumption is that these connections are forever). So we call `Close` but the connection may already be in the reconnect loop, which can produce the log spew when the remote has shut down.

Can you get a stack trace from the hang you see?

---

Review status: all files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4502#-:-KAtbjadhUaKnjrU_Din:-436314110)*

**Comment by spencerkimball** [comment]
Can't get it to fail now...

---

Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[gossip/simulation/network.go, line 125 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4502#-KAr3bcBkEzPPIlfIxkT:-KAvo-VCTsZzcVfdSMsH:1441874953) ([raw file](https://github.com/cockroachdb/cockroach/blob/6135537594bdf3936806acac05eab0a6c1f5080d/gossip/simulation/network.go#L125)):*
They're used from main package.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4502#-:-KAvo1yqwNj8ZNMv-wBu:-1966336232)*

**Comment by tamird** [comment]
LGTM. Add "Fixes #4500" to the second commit message.

---

Reviewed 9 of 9 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[gossip/convergence_test.go, line 29 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4502#-KAvsTEI6DOkpclIg6KV:-KAvsTEI6DOkpclIg6KW:1260114251) ([raw file](https://github.com/cockroachdb/cockroach/blob/ec268c198c92b74429d0a58859fd0fbb33a5e3a1/gossip/convergence_test.go#L29)):*
s/ t / _ / since it's unused

---

*[gossip/gossip.go, line 939 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4502#-KAvrZZKMJmNEyf3evQx:-KAvrZZKMJmNEyf3evQy:-1542324587) ([raw file](https://github.com/cockroachdb/cockroach/blob/ec268c198c92b74429d0a58859fd0fbb33a5e3a1/gossip/gossip.go#L939)):*
remove this

---

*[gossip/simulation/network.go, line 125 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4502#-KAr3bcBkEzPPIlfIxkT:-KAvqvDM3IzKM5qPr5RA:-1812980965) ([raw file](https://github.com/cockroachdb/cockroach/blob/6135537594bdf3936806acac05eab0a6c1f5080d/gossip/simulation/network.go#L125)):*
Huh, we have `time go build ./gossip/simulation/...` in `circle-deps.sh` but that must not build `main`.  We need to add `time go build ./gossip/simulation/gossip.go` apparently.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4502#-:-KAvsOBNq8AQlbnvj3at:-443052757)*

File: gossip/convergence_test.go [hunk 1]
```diff
@@ -45,6 +46,5 @@ func verifyConvergence(numNodes, maxCycles int, t *testing.T) {
 // actual production gossip code than seems worthwhile for a unittest.
 func TestConvergence(t *testing.T) {
 	defer leaktest.AfterTest(t)
-	t.Skipf("TODO(pmattis): #4500")
 	verifyConvergence(10, 100, t)
```
Comment (bdarnell) [inline gossip/convergence_test.go]: How many iterations are now required? Can we lower the "100" here? (it was 20 until a few weeks ago)
