### PR TITLE
kvserver: start LeaseAppliedIndex from 10

### LINKED ISSUE #131450: kvnemesis: closed timestamp regressions during test injected reproposals
**Describe the problem**

We've seen KVNemesis routinely fail due to closed timestamp regressions. For example: https://github.com/cockroachdb/cockroach/issues/118471#issuecomment-2293544809

We attempted to fix this in https://github.com/cockroachdb/cockroach/pull/121965. However, we still see this sometimes. @pav-kv has a theory about why: https://github.com/cockroachdb/cockroach/issues/118471#issuecomment-2104633621. 

Jira issue: CRDB-42546

Epic CRDB-37617

----

Note to L2 triagers: if you encounter an instance of this failure during triage, point to this issue and close the test flake with the `X-duplicate` label.

### PR DESCRIPTION
**Pull request by pav-kv**
The LAI=1 is reserved for out-of-order proposals in tests. A bunch of tests override proposal's LAI to 1, in order to force reproposals. If these modified proposals race with a "real" proposal with LAI 1, this can cause a closed timestamp regression.

Fixes #131450

### CODE REVIEW

**Comment by pav-kv** [comment]
@tbg @arulajmani An alternative fix would be making sure that the LAI override [here](https://github.com/cockroachdb/cockroach/blob/1eb07c62d7305fbf90fde9253cd61e4d49ab34e2/pkg/kv/kvserver/replica_proposal_buf.go#L716-L720) never assigns a LAI higher than the current one, so that all such proposals are guaranteed to never apply. The flake happens when we assign LAI=1 and this entry gets to be the first committed one, which makes it applied.

**Review by tbg — CHANGES_REQUESTED** [review]
I like the approach in this PR vs. adding something specific in the test to work around it, but isn't there a mixed-version concern in the code as is? Let's assume we init the LAI to 10 to make the concern clearer. There are clusters out there with replicas at an LAI of anywhere between zero and nine. Those would all hit the assertion when starting into the new binary, would they not? I would've thought that instead of the assertion we'd have this code:

```go
b.assignedLAI = max(p.leaseAppliedIndex(), stateloader.InitialLeaseAppliedIndex)
```

That way, replicas would never assign a new LAI under the initial one going forward, but they'd still boot up regardless of what LAI their state machine is initially at (and they'd also not erroneously discard commands in the log that proposed earlier that violate the minimum).

Perhaps this mixed-version concern goes away if we set the min to "1" instead of "10" but I'm not sure. The state starts out at zero, no? So I think things would still explore.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/139343#-:-OH88pZF5uK-PiFBCsMk:b-mjonia)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @arulajmani and @pav-kv)

___
*[`pkg/kv/kvserver/stateloader/initial.go` line 39 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/139343#-OH888P409zyprL0YekR:-OH888P409zyprL0YekS:b1vc84o) ([raw file](https://github.com/cockroachdb/cockroach/blob/d37140f391b353b32c1bbc6dd67637286bc711c0/pkg/kv/kvserver/stateloader/initial.go#L39)):*
> ```Go
> 	//
> 	// https://github.com/cockroachdb/cockroach/issues/70894#issuecomment-1881165404
> 	InitialLeaseAppliedIndex = 1
> ```

Should we make this 10, an arbitrary value chosen to match the first index of our raft logs?

**Review by tbg — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/139343)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @arulajmani and @pav-kv)

**Review by pav-kv — COMMENTED** [review]
Yeah, this is a valid concern. I wasn't worried too much about it because of `if buildutil.CrdbTestBuild`, but you're right that catching this flake (even in tests) wouldn't be great. Will change to `max`. Alternatively, I can remove this line.

The goal was making sure that I haven't missed any place where this field should be initialized.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/139343#-:-OH8DPWA4i34H39tlByN:b-eim7up)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @arulajmani)

**Review by pav-kv — COMMENTED** [review]
Done. @tbg PTAL

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/139343#-:-OH8NlDk8dHVVbyw-TDb:b4qv3wd)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @arulajmani and @tbg)

___
*[`pkg/kv/kvserver/stateloader/initial.go` line 39 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/139343#-OH888P409zyprL0YekR:-OH8Nms-3xtN6EuO15B6:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/d37140f391b353b32c1bbc6dd67637286bc711c0/pkg/kv/kvserver/stateloader/initial.go#L39)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

Should we make this 10, an arbitrary value chosen to match the first index of our raft logs?
</blockquote></details>

Done.

**Review by tbg — APPROVED** [review]
Oh, you're right I missed that this was in CRDB test builds only. I'm okay with it either way then. Thanks for the PR!

> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/139343#-:-OH8OCJH4g54NY3LYWNI:b-9zh63j)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @arulajmani)

File: pkg/kv/kvserver/stateloader/stateloader.go [hunk 1]
```diff
@@ -374,12 +374,13 @@ func (rsl StateLoader) SetForceFlushIndex(
 // empty storage.
 func UninitializedReplicaState(rangeID roachpb.RangeID) kvserverpb.ReplicaState {
 	return kvserverpb.ReplicaState{
-		Desc:           &roachpb.RangeDescriptor{RangeID: rangeID},
-		Lease:          &roachpb.Lease{},
-		TruncatedState: nil, // Invariant: always nil.
-		GCThreshold:    &hlc.Timestamp{},
-		Stats:          &enginepb.MVCCStats{},
-		GCHint:         &roachpb.GCHint{},
+		LeaseAppliedIndex: InitialLeaseAppliedIndex,
```
Comment (pav-kv) [inline pkg/kv/kvserver/stateloader/stateloader.go:377]: Should we leave this at zero like other fields? I'm not sure though that some proposals at low LAIs wouldn't slip through. Maybe they wouldn't since this range is not initialized yet.

Comment (pav-kv) [reply pkg/kv/kvserver/stateloader/stateloader.go]: Reversed to 0 - for uninited replicas, this index has no semantics. And the `max(..., InitialLeaseAppliedIndex)` in proposal buf `Init` is the best guarantee we won't propose low LAIs.

**Comment by pav-kv** [comment]
bors r=tbg

**Comment by pav-kv** [comment]
bors cancel

**Comment by pav-kv** [comment]
bors r=tbg

**Comment by pav-kv** [comment]
bors retry

**Comment by pav-kv** [comment]
bors cancel

**Comment by pav-kv** [comment]
bors r=tbg

**Comment by pav-kv** [comment]
Backported to `25.1`, but not to <= `24.3`, out of caution. Will do if flakes in earlier branches become a problem.
