### PR TITLE
builtins: Check max allowed points for st_generatepoints

### LINKED ISSUE #59452: geo: st_generatepoints can OOM or panic a server
# Issue

The `st_generatepoints` builtin can OOM or panic a server.

https://teamcity.cockroachdb.com//viewLog.html?buildId=2615396&buildTypeId=Cockroach_Nightlies_RandomSyntaxTests&tab=buildLog

While investigating this issue, I also discovered an unrelated panic that is inadvertently caught by the optimizer. This can also happen at runtime, panicking an actual server, by invoking it in a different way.

```
demo@127.0.0.1:26257/defaultdb> SELECT ST_GeneratePoints(geom, 10000000000000, 1996)
FROM (
    SELECT ST_Buffer(
        ST_GeomFromText(
        'LINESTRING(50 50,150 150,150 50)'),
        10, 'endcap=round join=round') AS geom
) AS s;
ERROR: internal error: runtime error: makeslice: len out of range
SQLSTATE: XX000
DETAIL: stack trace:
github.com/cockroachdb/cockroach/pkg/util/errorutil/catch.go:29: ShouldCatch()
github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder/builder.go:165: func1()
runtime/panic.go:969: gopanic()
runtime/slice.go:27: panicmakeslicelen()
runtime/slice.go:93: makeslice()
github.com/cockroachdb/cockroach/pkg/geo/geomfn/generate_points.go:124: func1()
github.com/cockroachdb/cockroach/pkg/geo/geomfn/generate_points.go:174: generateRandomPointsFromPolygon()
github.com/cockroachdb/cockroach/pkg/geo/geomfn/generate_points.go:62: generateRandomPoints()
github.com/cockroachdb/cockroach/pkg/geo/geomfn/generate_points.go:29: GenerateRandomPoints()
github.com/cockroachdb/cockroach/pkg/sql/sem/builtins/geo_builtins.go:1987: func337()
github.com/cockroachdb/cockroach/pkg/sql/sem/tree/eval.go:3978: Eval()
github.com/cockroachdb/cockroach/pkg/sql/opt/norm/fold_constants_funcs.go:576: FoldFunction()
github.com/cockroachdb/cockroach/pkg/sql/opt/norm/factory.og.go:16963: ConstructFunction()
github.com/cockroachdb/cockroach/pkg/sql/opt/norm/factory.og.go:18852: Replace()
github.com/cockroachdb/cockroach/pkg/sql/opt/norm/inline_funcs.go:93: func1()
github.com/cockroachdb/cockroach/pkg/sql/opt/norm/inline_funcs.go:95: inlineConstants()
github.com/cockroachdb/cockroach/pkg/sql/opt/norm/inline_funcs.go:55: InlineProjectionConstants()
github.com/cockroachdb/cockroach/pkg/sql/opt/norm/factory.og.go:1138: ConstructProject()
github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder/project.go:55: constructProject()
github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder/project.go:30: constructProjectForScope()
github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder/select.go:1055: buildSelectClause()
github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder/select.go:956: buildSelectStmtWithoutParens()
github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder/select.go:929: func1()
github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder/with.go:29: processWiths()
github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder/select.go:928: buildSelect()
github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder/builder.go:265: buildStmt()
github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder/builder.go:229: buildStmtAtRoot()
github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder/builder.go:200: Build()
github.com/cockroachdb/cockroach/pkg/sql/plan_opt.go:507: buildExecMemo()
github.com/cockroachdb/cockroach/pkg/sql/plan_opt.go:193: makeOptimizerPlan()
github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:910: makeExecPlan()
github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:796: dispatchToExecutionEngine()

HINT: You have encountered an unexpected error.

Please check the public issue tracker to check whether this problem is
already tracked. If you cannot find it there, please report the error
with details by creating a new issue.

If you would rather not post publicly, please contact us directly
using the support form.

We appreciate your feedback.
```

Here is how to make it panic a server:

```
demo@127.0.0.1:26257/defaultdb> create table a (a primary key) as select 10000000000000;
CREATE TABLE AS

Time: 28ms total (execution 5ms / network 22ms)

demo@127.0.0.1:26257/defaultdb> SELECT ST_GeneratePoints(geom, (select a from a limit1), 1996)
FROM (
    SELECT ST_Buffer(
        ST_GeomFromText(
        'LINESTRING(50 50,150 150,150 50)'),
        10, 'endcap=round join=round') AS geom
) AS s;
*
* ERROR: [n1,client=127.0.0.1:60358,hostssl,user=demo] a SQL panic has occurred while executing the following statement:
* SELECT st_generatepoints(geom, (SELECT a FROM a AS limit1), 1996) FROM (SELECT st_buffer(st_geomfromtext('LINESTRING(50 50,150 150,150 50)'), 10.0, 'endcap=round join=round') AS geom) AS s
*
*
* ERROR: [n1,client=127.0.0.1:60358,hostssl,user=demo] a panic has occurred!
* runtime error: makeslice: len out of range
* (1) attached stack trace
*   -- stack trace:
*   | github.com/cockroachdb/cockroach/pkg/sql.(*Server).ServeConn.func1
*   | 	/Users/jordan/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:479
*   | [...repeated from below...]
* Wraps: (2) while executing: SELECT st_generatepoints(_, (SELECT _ FROM _ AS _), _) FROM (SELECT st_buffer(st_geomfromtext(_), _, _) AS _) AS _
* Wraps: (3) attached stack trace
*   -- stack trace:
*   | github.com/cockroachdb/cockroach/pkg/sql.(*Server).ServeConn.func1
*   | 	/Users/jordan/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:479
*   | runtime.gopanic
*   | 	/usr/local/go/src/runtime/panic.go:969
*   | github.com/cockroachdb/cockroach/pkg/sql/colexecbase/colexecerror.CatchVectorizedRuntimeError.func1
*   | 	/Users/jordan/go/src/github.com/cockroachdb/cockroach/pkg/sql/colexecbase/colexecerror/error.go:60
*   | runtime.gopanic
*   | 	/usr/local/go/src/runtime/panic.go:969
*   | runtime.panicmakeslicelen
*   | 	/usr/local/go/src/runtime/slice.go:27
*   | runtime.makeslice
*   | 	/usr/local/go/src/runtime/slice.go:93
*   | github.com/cockroachdb/cockroach/pkg/geo/geomfn.generateRandomPointsFromPolygon.func1
*   | 	/Users/jordan/go/src/github.com/cockroachdb/cockroach/pkg/geo/geomfn/generate_points.go:124
*   | github.com/cockroachdb/cockroach/pkg/geo/geomfn.generateRandomPointsFromPolygon
*   | 	/Users/jordan/go/src/github.com/cockroachdb/cockroach/pkg/geo/geomfn/generate_points.go:174
*   | github.com/cockroachdb/cockroach/pkg/geo/geomfn.generateRandomPoints
*   | 	/Users/jordan/go/src/github.com/cockroachdb/cockroach/pkg/geo/geomfn/generate_points.go:62
*   | github.com/cockroachdb/cockroach/pkg/geo/geomfn.GenerateRandomPoints
*   | 	/Users/jordan/go/src/github.com/cockroachdb/cockroach/pkg/geo/geomfn/generate_points.go:29
*   | github.com/cockroachdb/cockroach/pkg/sql/sem/builtins.glob..func337
*   | 	/Users/jordan/go/src/github.com/cockroachdb/cockroach/pkg/sql/sem/builtins/geo_builtins.go:1987
*   | github.com/cockroachdb/cockroach/pkg/sql/sem/tree.(*FuncExpr).Eval
*   | 	/Users/jordan/go/src/github.com/cockroachdb/cockroach/pkg/sql/sem/tree/eval.go:3978
*   | github.com/cockroachdb/cockroach/pkg/sql.(*valuesNode).startExec
*   | 	/Users/jordan/go/src/github.com/cockroachdb/cockroach/pkg/sql/values.go:156
*   | github.com/cockroachdb/cockroach/pkg/sql.startExec.func2
*   | 	/Users/jordan/go/src/github.com/cockroachdb/cockroach/pkg/sql/plan.go:496
*   | github.com/cockroachdb/cockroach/pkg/sql.(*planVisitor).visitInternal.func1
*   | 	/Users/jordan/go/src/github.com/cockroachdb/cockroach/pkg/sql/walk.go:119
*   | github.com/cockroachdb/cockroach/pkg/sql.(*planVisitor).visitInternal
*   | 	/Users/jordan/go/src/github.com/cockroachdb/cockroach/pkg/sql/walk.go:286
*   | github.com/cockroachdb/cockroach/pkg/sql.(*planVisitor).visit
*   | 	/Users/jordan/go/src/github.com/cockroachdb/cockroach/pkg/sql/walk.go:86
*   | github.com/cockroachdb/cockroach/pkg/sql.walkPlan
*   | 	/Users/jordan/go/src/github.com/cockroachdb/cockroach/pkg/sql/walk.go:50
*   | github.com/cockroachdb/cockroach/pkg/sql.startExec
*   | 	/Users/jordan/go/src/github.com/cockroachdb/cockroach/pkg/sql/plan.go:499
*   | github.com/cockroachdb/cockroach/pkg/sql.(*planNodeToRowSource).Start
*   | 	/Users/jordan/go/src/github.com/cockroachdb/cockroach/pkg/sql/plan_node_to_row_source.go:126
*   | github.com/cockroachdb/cockroach/pkg/sql/colexec.(*Columnarizer).Init
*   | 	/Users/jordan/go/src/github.com/cockroachdb/cockroach/pkg/sql/colexec/columnarizer.go:133
*   | github.com/cockroachdb/cockroach/pkg/sql/colexecbase/colexecerror.CatchVectorizedRuntimeError
*   | 	/Users/jordan/go/src/github.com/cockroachdb/cockroach/pkg/sql/colexecbase/colexecerror/error.go:93
*   | github.com/cockroachdb/cockroach/pkg/sql/colexec.(*Materializer).Start
*   | 	/Users/jordan/go/src/github.com/cockroachdb/cockroach/pkg/sql/colexec/materializer.go:242
*   | github.com/cockroachdb/cockroach/pkg/sql/execinfra.(*ProcessorBase).Run
*   | 	/Users/jordan/go/src/github.com/cockroachdb/cockroach/pkg/sql/execinfra/processorsbase.go:764
*   | github.com/cockroachdb/cockroach/pkg/sql/flowinfra.(*FlowBase).Run
*   | 	/Users/jordan/go/src/github.com/cockroachdb/cockroach/pkg/sql/flowinfra/flow.go:380
*   | github.com/cockroachdb/cockroach/pkg/sql.(*DistSQLPlanner).Run
*   | 	/Users/jordan/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsql_running.go:361
*   | github.com/cockroachdb/cockroach/pkg/sql.(*DistSQLPlanner).PlanAndRun
*   | 	/Users/jordan/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsql_running.go:954
*   | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execWithDistSQLEngine
*   | 	/Users/jordan/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:1009
*   | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).dispatchToExecutionEngine
*   | 	/Users/jordan/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:888
*   | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execStmtInOpenState
*   | 	/Users/jordan/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:641
*   | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execStmt
*   | 	/Users/jordan/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:119
*   | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execCmd.func1
*   | 	/Users/jordan/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:1445
* Wraps: (4) runtime error: makeslice: len out of range
* Error types: (1) *withstack.withStack (2) *safedetails.withSafeDetails (3) *withstack.withStack (4) runtime.errorString
*
panic: runtime error: makeslice: len out of range [recovered]
	panic: runtime error: makeslice: len out of range [recovered]
	panic: runtime error: makeslice: len out of range
```

# Implementation Guide

ST_GeneratePoints should have a strict limit on the number of points we can generate.

We should fail with an error if we exceed this constant limit https://github.com/cockroachdb/cockroach/blob/3699ce67835301e580bace3976bb6c2f3e0a32bf/pkg/geo/geo.go#L53

Example usage

https://github.com/cockroachdb/cockroach/blob/3699ce67835301e580bace3976bb6c2f3e0a32bf/pkg/geo/geomfn/linear_reference.go#L41-L44

https://github.com/cockroachdb/cockroach/blob/3699ce67835301e580bace3976bb6c2f3e0a32bf/pkg/geo/geomfn/linear_reference_test.go#L108-L117

### PR DESCRIPTION
**Pull request by mneverov**
builtins: Check max allowed points for st_generatepoints

Previously, the number of generated points was not checked that could lead to
OOM while creating too large slices. This patch adds a validation that checks
upper bound of the given parameter (number of points to return) as well as
number of the cells to generate.

Fixes: #59452

Release note: none

### CODE REVIEW

File: pkg/geo/geomfn/generate_points.go [hunk 1]
```diff
@@ -113,14 +120,22 @@ func generateRandomPointsFromPolygon(
 		sampleWidth = int(math.Ceil(sampleNPoints / float64(sampleHeight)))
 		sampleCellSize = bboxHeight / float64(sampleHeight)
 	}
+	n := sampleHeight * sampleWidth
+	if n > geo.MaxAllowedSplitPoints {
```
Comment (otan) [inline pkg/geo/geomfn/generate_points.go:124]: thanks for doing this!

i think this one is too restrictive. what we really care about is `iterations <= nPoints*10` below.
with this the area may be small but already out of range. i think we should remove this check and restore the check for `			"Requires too many iterations over grid",	`

Comment (otan) [reply pkg/geo/geomfn/generate_points.go:124]: I see we also shuffle `n` times -- i'd also restrict shuffling to `min(n, geo.MaxAllowedSplitPoints)`

Comment (otan) [reply pkg/geo/geomfn/generate_points.go:124]: oh i see, we'd have to shuffle a lot of points. i think we should still avoid this check though; the nPoints defence i think is good enough for now.

Comment (mneverov) [reply pkg/geo/geomfn/generate_points.go:124]: hi,
```
select st_asewkt(
    st_generatepoints(
        st_geomfromtext('POLYGON((0 0,0 100,0.00001 0.00000001,0.99999 0.00000001,1 100,1 0,0 0))'),
        500, 1996
    )
);
```
this command takes ~4 GB and at least a couple of minutes to complete even with the check (I aborted the command).
If you change 500 to 5000 the server crushes immediately, without any stacktrace output :(
With the check the error is:
`ERROR: st_generatepoints(): generating random points error: generated area is too large: 500014321, max 65336`.

I agree that the check is too restrictive. Maybe, I can change MaxAllowedSplitPoints check to some other sensible number?

Comment (otan) [reply pkg/geo/geomfn/generate_points.go:124]: I've seen cases in PostGIS returning max 100, so maybe 100 should be our max :)

sounds like a good idea. do you mind also adding this to the `info` section of the builtin?

Comment (mneverov) [reply pkg/geo/geomfn/generate_points.go:124]: Ok, will remove this check, change the validation in `GenerateRandomPoints`  (nPoints must be less than 100) and add this to the info section.
Will update the PR soon, thanks!

Comment (mneverov) [reply pkg/geo/geomfn/generate_points.go:124]: Actually, I found in [postgis](https://github.com/postgis/postgis/blob/08c2363c682ff4c602288adbb90e50a024c56849/liblwgeom/lwgeom_geos.c#L1796) the 100 check you mentioned.
Looks like postgis doesn't have MaxAllowedSplitPoints check. Does it make sense to remove the `MaxAllowedSplitPoints` check at all, and change [the validation](https://github.com/cockroachdb/cockroach/pull/59973/files#diff-ad843e286e45d0fa5184d8ad9b4b5d05e2a3ef32586d5ff44dc54e1f96bea4afR156) to:
```
for nPointsGenerated, iterations := 0, 0; nPointsGenerated < nPoints && iterations <= 100; iterations++ {
```
?

Comment (otan) [reply pkg/geo/geomfn/generate_points.go:124]: It would have to be before the points are generated /the shuffle but you can remove the check after that.

Comment (mneverov) [reply pkg/geo/geomfn/generate_points.go:124]: `It would have to be before the points are generated`
oh, yes, you're right.

It were too many suggestions from my side so now i'm confused about the next action :)
I still do this `Ok, will remove this check, change the validation in GenerateRandomPoints (nPoints must be less than 100) and add this to the info section.`, right?

Comment (otan) [reply pkg/geo/geomfn/generate_points.go:124]: Sorry yeah many ways to go about this. I think we can still get to a state where the npointsgenerated is huge, so if you want to do the iterations < 100 idea but before the shuffle I'd be ok. Maybe easier to just cap the number of points to generate to be 100, and if it is over, take a random sample of points without generating the whole array.

Comment (mneverov) [reply pkg/geo/geomfn/generate_points.go:124]: got it, thanks!
will update the PR

Comment (otan) [reply pkg/geo/geomfn/generate_points.go:124]: And also sorry for the back and forth. You've helped uncover some of the mystery and we appreciate that!

Comment (mneverov) [reply pkg/geo/geomfn/generate_points.go]: no problem!

Added a new constant `maxAllowedGridSize = 100 * geo.MaxAllowedSplitPoints` to limit the generated area size.
Why 100? Tbh chosen arbitrary based on the calculations: 
the max slice size will be 6,5M. The slice stores cells which are other slices, i.e. 24bytes header. So 6,5M * 24 = 156MB to instantiate the cells slice only. I think it is reasonable amount of memory  (although might be maybe increased twice?)

When I execute 
```
select st_asewkt(st_generatepoints(st_geomfromtext('POLYGON((0 0,0 100,0.00001 0.00000001,0.99999 0.00000001,1 100,1 0,0 0))'), 65, 1996));
```
the memory profiler shows 
Screenshot from 2021-02-11 08-28-11

I mentioned the limit for the function argument in the function description, but not the 100 iterations limitation as postgis doesn't mentioned it either. Let me know if I need to add something like `The function may return less than requested number of points when calculation takes too long.`

**Review by otan — APPROVED** [review]
thanks! for now I'm happy with it as is.

bors r+
