### PR TITLE
roachprod: use az sdk for checking for live migrations

### LINKED ISSUE #145889: roachtest: tpccbench/nodes=3/cpu=16/lease=expiration failed
roachtest.tpccbench/nodes=3/cpu=16/lease=expiration [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyAzureBazel/19586452?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyAzureBazel/19586452?buildTab=artifacts#/tpccbench/nodes=3/cpu=16/lease=expiration) on master @ [9fa4a6b663c72b6d956d7c71f82c20e39856211e](https://github.com/cockroachdb/cockroach/commits/9fa4a6b663c72b6d956d7c71f82c20e39856211e):

```
(cluster.go:2385).Start: failed to wait for SQL to be ready: dial tcp 20.106.192.203:26257: connect: connection refused
test artifacts and logs in: /artifacts/tpccbench/nodes=3/cpu=16/lease=expiration/run_1
```

Parameters:
 - <code>arch=amd64</code>
 - <code>cloud=azure</code>
 - <code>coverageBuild=false</code>
 - <code>cpu=16</code>
 - <code>encrypted=false</code>
 - <code>fs=ext4</code>
 - <code>localSSD=true</code>
 - <code>runtimeAssertionsBuild=false</code>
 - <code>ssd=0</code>
<details><summary>Help</summary>
<p>

See: [roachtest README](https://github.com/cockroachdb/cockroach/blob/master/pkg/cmd/roachtest/README.md)

See: [How To Investigate \(internal\)](https://cockroachlabs.atlassian.net/l/c/SSSBr8c7)

_Grafana is not yet available for azure clusters_</p>
</details>
/cc @cockroachdb/test-eng
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*tpccbench/nodes=3/cpu=16/lease=expiration.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/bazci/githubpost/issues)

</sub>

Jira issue: CRDB-50270

### LINKED ISSUE #145950: roachtest: ycsb/F/nodes=3/cpu=32/mvcc-range-keys=global failed
roachtest.ycsb/F/nodes=3/cpu=32/mvcc-range-keys=global [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyAzureBazel/19595988?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyAzureBazel/19595988?buildTab=artifacts#/ycsb/F/nodes=3/cpu=32/mvcc-range-keys=global) on master @ [6b5994cb063e494fa7013c731170e5f539d9ba96](https://github.com/cockroachdb/cockroach/commits/6b5994cb063e494fa7013c731170e5f539d9ba96):

```
(cluster.go:2498).Run: full command output in run_101610.456325013_n4_cockroach-workload-r.log: COMMAND_PROBLEM: exit status 1
(monitor.go:149).Wait: monitor failure: monitor user task failed: t.Fatal() was called
test artifacts and logs in: /artifacts/ycsb/F/nodes=3/cpu=32/mvcc-range-keys=global/run_1
```

Parameters:
 - <code>arch=amd64</code>
 - <code>cloud=azure</code>
 - <code>coverageBuild=false</code>
 - <code>cpu=32</code>
 - <code>encrypted=false</code>
 - <code>runtimeAssertionsBuild=false</code>
 - <code>ssd=0</code>
<details><summary>Help</summary>
<p>

See: [roachtest README](https://github.com/cockroachdb/cockroach/blob/master/pkg/cmd/roachtest/README.md)

See: [How To Investigate \(internal\)](https://cockroachlabs.atlassian.net/l/c/SSSBr8c7)

_Grafana is not yet available for azure clusters_</p>
</details>
/cc @cockroachdb/test-eng
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*ycsb/F/nodes=3/cpu=32/mvcc-range-keys=global.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/bazci/githubpost/issues)

</sub>

Jira issue: CRDB-50298

### LINKED ISSUE #146036: roachtest: ycsb/F/nodes=3/cpu=32/isolation-level=read-committed failed
roachtest.ycsb/F/nodes=3/cpu=32/isolation-level=read-committed [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyAzureBazel/19606382?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyAzureBazel/19606382?buildTab=artifacts#/ycsb/F/nodes=3/cpu=32/isolation-level=read-committed) on master @ [210cac0e4000426d486e98f204864a704e66e253](https://github.com/cockroachdb/cockroach/commits/210cac0e4000426d486e98f204864a704e66e253):

```
(cluster.go:2498).Run: full command output in run_100205.712263270_n4_cockroach-workload-r.log: COMMAND_PROBLEM: exit status 1
(monitor.go:149).Wait: monitor failure: monitor user task failed: t.Fatal() was called
test artifacts and logs in: /artifacts/ycsb/F/nodes=3/cpu=32/isolation-level=read-committed/run_1
```

Parameters:
 - <code>arch=amd64</code>
 - <code>cloud=azure</code>
 - <code>coverageBuild=false</code>
 - <code>cpu=32</code>
 - <code>encrypted=false</code>
 - <code>runtimeAssertionsBuild=false</code>
 - <code>ssd=0</code>
<details><summary>Help</summary>
<p>

See: [roachtest README](https://github.com/cockroachdb/cockroach/blob/master/pkg/cmd/roachtest/README.md)

See: [How To Investigate \(internal\)](https://cockroachlabs.atlassian.net/l/c/SSSBr8c7)

_Grafana is not yet available for azure clusters_</p>
</details>
/cc @cockroachdb/test-eng
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*ycsb/F/nodes=3/cpu=32/isolation-level=read-committed.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/bazci/githubpost/issues)

</sub>

Jira issue: CRDB-50344

### PR DESCRIPTION
**Pull request by DarrylWong**
The previous approach of using the CLI did not work well on CI, as `az login` must be invoked first. `az login` only accepts auth through client id + secret, which is not set up for roachtest currently.

Instead, switch to using the azure sdk instead which allows auth through JWT. This means we must manage filtering through events for migrations ourselves as the sdk does not support JMESPath filtering.

Fixes: https://github.com/cockroachdb/cockroach/issues/146036
Fixes: https://github.com/cockroachdb/cockroach/issues/145950
Fixes: https://github.com/cockroachdb/cockroach/issues/145889
Release note: none

### CODE REVIEW

**Comment by DarrylWong** [comment]
[Tested this](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyAzureBazel/19633165?buildTab=tests&expandedTest=build%3A%28id%3A19633165%29%2Cid%3A1729#%2Facceptance%2Fstatus-server%2Frun_1%2Fartifacts.zip) by hardcoding the resource group that was migrated found in #146036:

```
+       //startTime := since.Format("2006-01-02 15:04:05.999999999 -0700")
+       // TODO: remove this
+       startTime := time.Date(2025, 5, 1, 0, 0, 0, 0, time.UTC).Format("2006-01-02 15:04:05.999999999 -0700")
 
        // Azure lets us query by either resourceID or resourceGroup. We don't keep track
        // of either but can more easily reconstruct the latter through availability zones.
@@ -153,6 +155,9 @@ func (p *Provider) GetLiveMigrationVMs(
                resourceGroups[fmt.Sprintf("%s-%s", clusterName, zone)] = struct{}{}
        }
 
+       // TODO: remove this
+       resourceGroups["teamcity-19606382-1746250736-101-n4cpu32-eastus"] = struct{}{}
+
        token, err := p.getAuthToken()
        if err != nil {
                return nil, err
```

image

File: pkg/roachprod/vm/azure/azure.go [hunk 1]
```diff
@@ -114,6 +117,16 @@ func (p *Provider) GetHostErrorVMs(
 	return nil, nil
 }
 
+type TokenCredential struct {
+	token string
+}
+
+func (t *TokenCredential) GetToken(ctx context.Context, options policy.TokenRequestOptions) (azcore.AccessToken, error) {
```
Comment (DarrylWong) [inline pkg/roachprod/vm/azure/azure.go:124]: Not sure if i'm missing something obvious as to why azure makes you implement this yourself?? Or why we even explicitly need to pass a token in the first place when the other clients just accept the subID??

Comment (srosenberg) [reply pkg/roachprod/vm/azure/azure.go:124]: 🤷

**Review by srosenberg — APPROVED** [review]

**Comment by DarrylWong** [comment]
TFTR!

bors r=srosenberg
