### PR TITLE
sql: check that incoming params are valid UTF-8

### LINKED ISSUE #16378: sql/parser: panic in encodeSQLStringWithFlags
https://sentry.io/cockroach-labs/cockroachdb/issues/288666600/

```
*errors.errorString: runtime.errorString v3.go:353
  File "github.com/cockroachdb/cockroach/pkg/sql/pgwire/v3.go", line 353, in func1
  File "github.com/cockroachdb/cockroach/pkg/sql/parser/encode.go", line 77, in encodeSQLStringWithFlags
  File "github.com/cockroachdb/cockroach/pkg/sql/parser/datum.go", line 747, in Format
  File "github.com/cockroachdb/cockroach/pkg/sql/pgwire/types.go", line 174, in writeTextDatum
  File "github.com/cockroachdb/cockroach/pkg/sql/pgwire/v3.go", line 985, in sendResponse
...
(9 additional frame(s) were not displayed)

runtime.errorString v3.go:353
```

The stack trace points to:

```
    buf.WriteString(in[start:i])
```

### PR DESCRIPTION
**Pull request by justinj**
Fixes #16378.

I think it's possible that there is a lingering issue here with regards
to the oid.T__text case, but the relevant code exists in lib/pq and I
was unable to test this case regardless.

Had to restructure the node test a little bit to easily support multiple tests,
maybe Nathan can take a look at that one since I believe he wrote it originally?

Managed to find this panic thanks to go-fuzz!

### CODE REVIEW

**Review by knz — APPROVED** [review]

File: pkg/acceptance/node_test.go [hunk 1]
```diff
@@ -47,20 +47,54 @@ const config = {
...
+  });
+}
+
+function testSendInvalidUTF8(client) {
+  return new Promise(resolve => {
+    client.query({
+      text: 'SELECT $1::STRING',
+      values: [new Buffer([167])]
+    }, function (err, results) {
+      if (!err) throw new Error('expected error!');
```
Comment (nvanbenschoten) [inline pkg/acceptance/node_test.go]: We should assert what the error is (similar to `testutils.IsError`)? We've run into issues in the past with wildcard error checks failing to catch behavior changes.

File: pkg/sql/pgwire/types.go [hunk 2]
```diff
@@ -705,14 +707,27 @@ func decodeOidDatum(id oid.Oid, code formatCode, b []byte) (parser.Datum, error)
...
+		}
 		return parser.NewDName(string(b)), nil
 	default:
 		return nil, errors.Errorf("unsupported OID %v with format code %s", id, code)
 	}
 }
 
+func validateStringBytes(b []byte) error {
+	if !utf8.Valid(b) {
+		return pgerror.NewErrorf(pgerror.CodeCharacterNotInRepertoireError, "invalid UTF-8 sequence")
```
Comment (nvanbenschoten) [inline pkg/sql/pgwire/types.go]: Let's pull this out into a var since it's constant. No need to allocate every time.

File: pkg/sql/pgwire/types.go [hunk 3]
```diff
@@ -705,14 +707,27 @@ func decodeOidDatum(id oid.Oid, code formatCode, b []byte) (parser.Datum, error)
...
+		if err := validateStringBytes(b); err != nil {
+			return nil, err
+		}
 		return parser.NewDName(string(b)), nil
 	default:
 		return nil, errors.Errorf("unsupported OID %v with format code %s", id, code)
 	}
 }
 
+func validateStringBytes(b []byte) error {
```
Comment (nvanbenschoten) [inline pkg/sql/pgwire/types.go]: Should we add a comment on here stating which types need to be valid utf-8 and which ones don't?

**Comment by justinj** [comment]
Review status: 0 of 3 files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

*[pkg/acceptance/node_test.go, line 72 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/17935#-KsQ3VdOSePaucqkUa3v-r1-72:-Ksd8oB3t0Lsf9gFyBVX:b-g6knuz) ([raw file](https://github.com/cockroachdb/cockroach/blob/8a4e38e159460901a695ed436d6d9835cd6aae33/pkg/acceptance/node_test.go#L72)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

We should assert what the error is (similar to `testutils.IsError`)? We've run into issues in the past with wildcard error checks failing to catch behavior changes.
</blockquote></details>

Good call! I've added that function.

---

*[pkg/sql/pgwire/types.go, line 724 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/17935#-KsQ3VdOSePaucqkUa3w-r1-724:-Ksd8tdqo7RCsOnhu4Mg:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/8a4e38e159460901a695ed436d6d9835cd6aae33/pkg/sql/pgwire/types.go#L724)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Should we add a comment on here stating which types need to be valid utf-8 and which ones don't?
</blockquote></details>

Done.

---

*[pkg/sql/pgwire/types.go, line 726 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/17935#-KsQ3VdOSePaucqkUa3w-r1-726:-Ksd9n2JXCw6_7ZBYn_f:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/8a4e38e159460901a695ed436d6d9835cd6aae33/pkg/sql/pgwire/types.go#L726)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Let's pull this out into a var since it's constant. No need to allocate every time.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/17935)*

**Review by nvb — APPROVED** [review]
