### PR TITLE
sql: Support NO DATA clause for materialized views

### LINKED ISSUE #74083: sql: CREATE MATERIALIZED VIEW ... WITH NO DATA is not supported
**Describe the problem**

pgdump contains the following syntax

```sql
CREATE MATERIALIZED VIEW table_name
    [ (column_name [, ...] ) ]
    [ WITH ( storage_parameter [= value] [, ... ] ) ]
    [ TABLESPACE tablespace_name ]
    AS query
    [ WITH [ NO ] DATA ]
```

Please describe the issue you observed, and any steps we can take to reproduce it:

getting error

```sql
I'm seeing a parse error upon a PGDUMP import ERROR: postgres parse error: at or near "with": syntax error
```

**To Reproduce**

import pgdump containing the syntax

**Environment:**
 - CockroachDB version unknown
 - Server OS: unknown
 - Client app`cockroach sql`

**Additional context**
What was the impact?

Possible workaround by supplying https://www.cockroachlabs.com/docs/v21.2/migrate-from-postgres.html#ignore-unsupported-statements

Jira issue: CRDB-11909

### PR DESCRIPTION
**Pull request by rimadeodhar**
This PR updates the CREATE MATERIALIZED VIEW statement
to allow creating views with no data indicated by the
WITH NO DATA clause. Such views need to be refreshed
prior to accessing them. If the user attempts to access
the view before executing a refresh, we return an error.

Resolves https://github.com/cockroachdb/cockroach/issues/74083

Release note (sql change): The CREATE MATERIALIZED VIEW
statement has been extended to support the WITH NO DATA
clause. This allows the creation of materialized views
with no data. Such views require to be refreshed atleast
once prior to access.

### CODE REVIEW

**Comment by rimadeodhar** [comment]
Please note that I still need to add logic tests and unit tests but wanted to get the review going so publishing early.

**Review by mgartner — COMMENTED** [review]
Great start!

> Reviewed 18 of 18 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/83347#-:-N5aU-Xa66aGCM9_uQNm:b-8oelpl)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rimadeodhar)

___
*[`pkg/sql/opt/optbuilder/select.go` line 493 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/83347#-N5aSPaL-Pk406Fm01Hj:-N5aSPaL-Pk406Fm01Hk:b-k2hzd5) ([raw file](https://github.com/cockroachdb/cockroach/blob/35690590d11b8b318d01999225feab0394b1e4ae/pkg/sql/opt/optbuilder/select.go#L493)):*
> ```Go
> 
> 	if refreshRequired := tab.IsRefreshRequired(); refreshRequired {
> 		// TODO(rima): Is NoData the right error code here?
> ```

Postgres uses [`55000`](https://github.com/cockroachdb/cockroach/blob/50df58d2f415a44ef15adc1482f21a18179964f3/pkg/sql/pgwire/pgcode/codes.go#L260):


```
marcus=# \set VERBOSITY verbose;

marcus=# create table t (a int);
CREATE TABLE

marcus=# create materialized view v as select * from t with no data;
CREATE MATERIALIZED VIEW

marcus=# select * from v;
ERROR:  55000: materialized view "v" has not been populated
HINT:  Use the REFRESH MATERIALIZED VIEW command.
LOCATION:  ExecOpenScanRelation, execUtils.c:738
```

It might be good to update the error message to match too.

**Comment by rimadeodhar** [comment]
I have logic, parser and pretty print tests. This is RFAL.

**Review by rimadeodhar — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/83347)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @mgartner)

___
*[`pkg/sql/opt/optbuilder/select.go` line 493 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/83347#-N5aSPaL-Pk406Fm01Hj:-N5bJkgz-RkboZpC2UhP:b-rjcplb) ([raw file](https://github.com/cockroachdb/cockroach/blob/35690590d11b8b318d01999225feab0394b1e4ae/pkg/sql/opt/optbuilder/select.go#L493)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

Postgres uses [`55000`](https://github.com/cockroachdb/cockroach/blob/50df58d2f415a44ef15adc1482f21a18179964f3/pkg/sql/pgwire/pgcode/codes.go#L260):


```
marcus=# \set VERBOSITY verbose;

marcus=# create table t (a int);
CREATE TABLE

marcus=# create materialized view v as select * from t with no data;
CREATE MATERIALIZED VIEW

marcus=# select * from v;
ERROR:  55000: materialized view "v" has not been populated
HINT:  Use the REFRESH MATERIALIZED VIEW command.
LOCATION:  ExecOpenScanRelation, execUtils.c:738
```

It might be good to update the error message to match too.
</blockquote></details>

Thanks! Updated it.

File: pkg/sql/catalog/descpb/structured.go [hunk 1]
```diff
@@ -250,6 +250,11 @@ func (desc *TableDescriptor) MaterializedView() bool {
 	return desc.IsMaterializedView
 }
 
+// IsRefreshViewRequired implements the TableDescriptor interface.
+func (desc *TableDescriptor) IsRefreshViewRequired() bool {
+	return desc.IsMaterializedView && desc.RefreshViewRequired
+}
```
Comment (postamar) [inline pkg/sql/catalog/descpb/structured.go:256]: This isn't obvious but can you implement this method on `wrapper` in `tabledesc` instead please? We're trying to keep the amount of business logic in `descpb` to a minimum.

File: pkg/sql/catalog/descpb/structured.proto [hunk 2]
```diff
@@ -980,7 +980,9 @@ message TableDescriptor {
   // as a table. The data on disk is refreshed with the REFRESH MATERIALIZED
   // VIEW command. This flag is only set when ViewQuery != "".
   optional bool is_materialized_view = 41 [(gogoproto.nullable) = false];
-
+  // RefreshViewRequired indicates if the materialized view needs to be refreshed
+  // prior to access.
+  optional bool refresh_view_required = 53 [(gogoproto.nullable) = false];
```
Comment (postamar) [inline pkg/sql/catalog/descpb/structured.proto:985]: I looked a bit into the feasibility of checking for the presence of table statistics instead of maintaining a field in the descriptor, but it doesn't seem super straightforward to do, plus having a field such as this one doesn't add much technical debt. Perhaps that's what we'll move towards in the long run. Materialized views don't exactly have a lot of polish to them, such as they are, but that's OK for the time being too.

How do you feel though about making the field a `uint64` counter instead or a boolean flag? You could the increment that counter at every refresh, instead of setting the flag to false. It feels more useful to have a counter, somehow.

File: pkg/sql/opt/cat/table.go [hunk 3]
```diff
@@ -143,6 +143,11 @@ type Table interface {
 	// IsPartitionAllBy returns true if this is a PARTITION ALL BY table. This
 	// includes REGIONAL BY ROW tables.
 	IsPartitionAllBy() bool
+
+	// IsRefreshRequired returns true if the table is a materialized view
+	// created with the NO DATA option and is yet to be refreshed. Accessing
+	// such a view prior to running refresh returns an error.
+	IsRefreshRequired() bool
```
Comment (postamar) [inline pkg/sql/opt/cat/table.go:150]: Perhaps give this method the same name as `IsRefreshViewRequired`, or vice-versa? It means the same thing, after all.

**Review by postamar — COMMENTED** [review]
Reviewing on behalf of @cockroachdb/sql-schema, this looks good to me, provided that a few minor concerns are addressed.

**Review by rafiss — CHANGES_REQUESTED** [review]
nice work, looks great except for a few small nits

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/83347#-:-N5l9pjt0Lh3hHJE18bF:b-dqwulm)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @mgartner, @postamar, @rafiss, and @rimadeodhar)

___
*[`pkg/sql/opt_catalog.go` line 2181 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/83347#-N5l8M9o6J-6TyQpwN9o:-N5l8M9o6J-6TyQpwN9p:b-z7gqet) ([raw file](https://github.com/cockroachdb/cockroach/blob/5ece7c91616ad8ca71cae724b2e9018fead2c1b6/pkg/sql/opt_catalog.go#L2181)):*
> ```Go
> 
> // IsRefreshRequired is part of the cat.Table interface.
> func (ot *optVirtualTable) IsRefreshRequired() bool {
> ```

nit: since this is for virtual tables, this can always return false
___
*[`pkg/sql/catalog/descpb/structured.proto` line 985 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/83347#-N5Lo-2RQQqHA-N2eZaI-r2-985:-N5l8crM33XNwz7sifc3:b-l9uzxn) ([raw file](https://github.com/cockroachdb/cockroach/blob/5ece7c91616ad8ca71cae724b2e9018fead2c1b6/pkg/sql/catalog/descpb/structured.proto#L985)):*
<details><summary><i>Previously, postamar (Marius Posta) wrote…</i></summary><blockquote>

I looked a bit into the feasibility of checking for the presence of table statistics instead of maintaining a field in the descriptor, but it doesn't seem super straightforward to do, plus having a field such as this one doesn't add much technical debt. So this approach should be fine.

How do you feel though about making the field a `uint64` counter instead or a boolean flag? You could the increment that counter at every refresh, instead of setting the flag to false. It feels more useful to have a counter, somehow.
</blockquote></details>

counterpoint: i don't really see why any CRL dev or end-user would care about the count, and it might be more explicit to just keep it as a flag so it's obvious why we have it.
___
*[`pkg/sql/opt/cat/table.go` line 150 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/83347#-N5Lo-2RQQqHA-N2eZaM-r2-150:-N5l9ewCEIeLo8JTek1C:b5shqej) ([raw file](https://github.com/cockroachdb/cockroach/blob/5ece7c91616ad8ca71cae724b2e9018fead2c1b6/pkg/sql/opt/cat/table.go#L150)):*
<details><summary><i>Previously, postamar (Marius Posta) wrote…</i></summary><blockquote>

Perhaps give this method the same name as `IsRefreshViewRequired`, or vice-versa? It means the same thing, after all.
</blockquote></details>

agreed on keeping names consistent

**Comment by postamar** [comment]
> counterpoint: i don't really see why any CRL dev or end-user would care about the count, and it might be more explicit to just keep it as a flag so it's obvious why we have it.

I buy that. I don't feel strongly about it being a counter. The only other use-case I could imagine is debugging an incident, and that's a weak one at that. Main thing is it's clear what it does.

**Review by rimadeodhar — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/83347)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @mgartner, @postamar, and @rafiss)

___
*[`pkg/sql/opt_catalog.go` line 1276 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/83347#-N5Lo-2RQQqHA-N2eZaS-r2-1276:-N5ufa9iArY0st-uZela:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/5ece7c91616ad8ca71cae724b2e9018fead2c1b6/pkg/sql/opt_catalog.go#L1276)):*
<details><summary><i>Previously, postamar (Marius Posta) wrote…</i></summary><blockquote>

I'd prefer it if this logic weren't duplicated and this method delegated directly to `IsRefreshViewRequired()` on `catalog.TableDescriptor` instead. Same comment applies to other method implementations for `cat.Table`.
</blockquote></details>

Done.
___
*[`pkg/sql/opt/cat/table.go` line 150 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/83347#-N5Lo-2RQQqHA-N2eZaM-r2-150:-N5ufeqR-AtaNu2n52OT:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/5ece7c91616ad8ca71cae724b2e9018fead2c1b6/pkg/sql/opt/cat/table.go#L150)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

agreed on keeping names consistent
</blockquote></details>

Done.
___
*[`pkg/sql/catalog/descpb/structured.go` line 256 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/83347#-N5Lo-2Q_6LbLQkJtQAf-r2-256:-N5ufhW140qE9Pwqeq6J:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/5ece7c91616ad8ca71cae724b2e9018fead2c1b6/pkg/sql/catalog/descpb/structured.go#L256)):*
<details><summary><i>Previously, postamar (Marius Posta) wrote…</i></summary><blockquote>

This isn't obvious but can you implement this method on `wrapper` in `tabledesc` instead please? We're trying to keep the amount of business logic in `descpb` to a minimum.
</blockquote></details>

Done.

**Review by rafiss — APPROVED** [review]
> Reviewed 7 of 18 files at r1, 11 of 15 files at r2, 14 of 14 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/83347)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @mgartner and @postamar)

**Review by rafiss — APPROVED** [review]
looks great!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/83347#-:-N6J-Cxz9owxECXoRHR_:b6lqmcl)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @mgartner and @postamar)

**Review by rafiss — APPROVED** [review]
just thought of one thing -- how would this behave in mixed-version clusters?

this  would be a good opportunity to try out the new datadriven framework that @richardjcai created for testing mixed version states

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/83347#-:-N6J-P8tCf5lagPMcYoH:b-8n3tod)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @mgartner and @postamar)

**Review by mgartner — APPROVED** [review]
Nicely done! :lgtm: 

> Reviewed 11 of 15 files at r2, 13 of 14 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/83347#-:-N6Npwt8D4ADHNGsKtib:b8ggozm)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @postamar and @rimadeodhar)

___
*[`pkg/sql/opt/optbuilder/select.go` line 112 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/83347#-N6NodS909p1N7nVXnI5:-N6NodS909p1N7nVXnI6:bctg5ha) ([raw file](https://github.com/cockroachdb/cockroach/blob/44514e1621f5843028ca14c1d4dcdd8db5d06c66/pkg/sql/opt/optbuilder/select.go#L112)):*
> ```Go
> 			b.checkPrivilege(depName, ds, privilege.UPDATE)
> 		}
> ```

nit: revert newline removal
___
*[`pkg/sql/opt/optbuilder/select.go` line 262 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/83347#-N6NoibI5bquufeq9Inr:-N6NoibI5bquufeq9Ins:b-8p83mm) ([raw file](https://github.com/cockroachdb/cockroach/blob/44514e1621f5843028ca14c1d4dcdd8db5d06c66/pkg/sql/opt/optbuilder/select.go#L262)):*
> ```Go
> 			panic(wrapped)
> 		}
> ```

nit: revert new line removal
___
*[`pkg/sql/opt/optbuilder/select.go` line 492 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/83347#-N6NpABUA_DxxTM4wVW3:-N6NpABUA_DxxTM4wVW4:bsqsih7) ([raw file](https://github.com/cockroachdb/cockroach/blob/334131783afdd09ced31186e1fc1dc10de19a385/pkg/sql/opt/optbuilder/select.go#L492)):*
> ```Go
> 	}
> 
> 	if refreshRequired := tab.IsRefreshViewRequired(); refreshRequired {
> ```

nit: simplify this to `if tab.IsRefreshViewRequired() {`

**Comment by rimadeodhar** [comment]
TFTR!

bors r+
