### PR TITLE
sql: automatically assign index names

### LINKED ISSUE #2251: sql: allow automatically generated index names
The following currently fails:

```
CREATE TABLE t (
  a INT PRIMARY KEY,
  b INT,
  UNIQUE (b)
)
```

Instead, the index name should be automatically generated.

### PR DESCRIPTION
**Pull request by tamird**
Fixes #2251.

### CODE REVIEW

File: sql/structured.go [hunk 1]
```diff
@@ -117,12 +137,29 @@ func (desc *TableDescriptor) AllocateIDs() error {
 		desc.Columns[i].ID = columnID
 	}
 
+	// Keep track of index names and unnamed indexes.
+	indexNames := make(map[string]struct{})
```
Comment (petermattis) [inline sql/structured.go]: I think this is an over optimization. Just use `TableDescriptor.FindIndexByName`. I'm not entirely sure it is correct either because you haven't passed the index names through `normalizeName`.

File: sql/structured.go [hunk 2]
```diff
@@ -51,6 +52,25 @@ func validateName(name, typ string) error {
...
 }
 
+func (desc *IndexDescriptor) allocateName(tableDesc *TableDescriptor, names map[string]struct{}) {
+	segments := make([]string, 0, len(desc.ColumnIDs)+2)
+	segments = append(segments, tableDesc.Name)
+	for _, columnName := range desc.ColumnNames {
+		segments = append(segments, columnName)
+	}
+	segments = append(segments, "idx")
+	baseName := strings.Join(segments, "_")
```
Comment (petermattis) [inline sql/structured.go]: Are you following any existing convention here, or is this your own invention. Looks fine either way, though you might want to mention in a comment if this drew inspiration from somewhere.

File: sql/structured.go [hunk 3]
```diff
@@ -51,6 +52,25 @@ func validateName(name, typ string) error {
...
+	name := baseName
+
+	_, ok := names[name]
+	for i := 1; ok; i++ {
+		name = fmt.Sprintf("%s%d", baseName, i)
+		_, ok = names[name]
+	}
```
Comment (petermattis) [inline sql/structured.go]: If you use `FindIndexByName`, I would adjust this to be something like:

```
  exists := func(name string) bool {
    idx, _ := desc.FindIndexByName(name)
    return idx != nil
  }
  for i := 1; !exists(name); i++  {
    name = fmt.Sprintf("%s%d", baseName, i)
  }
```

**Comment by petermattis** [comment]
LGTM

File: sql/structured.go (hunk 2 above)
Comment (tamird) [inline sql/structured.go]: postgres convention - added a comment

File: sql/structured.go (hunk 3 above)
Comment (tamird) [inline sql/structured.go]: done

File: sql/structured.go (hunk 1 above)
Comment (tamird) [inline sql/structured.go]: done

File: sql/structured.go [hunk 4]
```diff
@@ -51,6 +52,35 @@ func validateName(name, typ string) error {
 	return nil
 }
 
+// allocateName sets desc.Name to a value that is not equalName to any
+// of tableDesc's indexes. allocateName roughly follows PostgreSQL's
+// convention for automatically-named indexes.
+func (desc *IndexDescriptor) allocateName(tableDesc *TableDescriptor) {
+	segments := make([]string, 0, len(desc.ColumnIDs)+2)
+	segments = append(segments, tableDesc.Name)
```
Comment (petermattis) [inline sql/structured.go]: I wonder if we need to include the table name in the index name. I realize this is following postgres, but it seems like stuttering. In your examples below, you have `c.c_foo_idx`.

**Comment by petermattis** [comment]
LGTM

File: sql/structured.go (hunk 4 above)
Comment (tamird) [inline sql/structured.go]: yeah, in postgres you can `DROP INDEX c_foo_idx`, though.
