### PR TITLE
kvserver: fix asserts around log truncations

### LINKED ISSUE #43605: kvserver: invalid Raft truncation decision panic in cli unittests
I got a scary panic in the cli unittests:
```
panic: invalid truncation decision; output = 54, input: [54, 53], commit idx = 53 [recovered]
	panic: invalid truncation decision; output = 54, input: [54, 53], commit idx = 53
```
I guess what's invalid about it is that we truncate below the commit idx?

This was when I was running a `testshort` across all the packages on my laptop - so high load. I couldn't repro easily by stressing the CLI package.

Logs for the package:
https://gist.github.com/andreimatei/bd59d82032d6639951cb61724894b407

cc @nvanbenschoten @tbg @ajwerner

### PR DESCRIPTION
**Pull request by irfansharif**
Fixes #43605.

Re-work (again) the invariants around log truncations to accommodate log
truncations of new replicas without any log entries. Previously we
assumed that a replica's FirstIndex (oldest raft entry index) was
strictly less than or equal to a replica's LastIndex (latest raft entry
index). This, for unfortunate reasons, is not always true. Reproducing
the comment below:

```
// We've inherited the unfortunate semantics for {First,Last}Index from
// raft.Storage. Specifically, both {First,Last}Index are inclusive, so
// there's no way to represent an empty log. The way we've initialized
// repl.FirstIndex is to set it to the first index in the possibly-empty log
// (TruncatedState.Index + 1), and allowing LastIndex to fall behind it when
// the log is empty (TruncatedState.Index). The initialization is done when
// minting a new replica from either the truncated state of incoming
// snapshot, or using the default initial log index. This makes for the
// confusing situation where FirstIndex > LastIndex. We can detect this
// special empty log case by comparing checking if
// `FirstIndex == LastIndex + 1`. Having done that (i.e. if the raft log is
// not empty), we can assert on the following invariants:
//
//              FirstIndex    <= LastIndex                              (0)
//              NewFirstIndex >= FirstIndex                             (1)
//              NewFirstIndex <= LastIndex                              (2)
//              NewFirstIndex <= CommitIndex                            (3)
//
// (1) asserts that we're not regressing our FirstIndex
// (2) asserts that our we don't truncate past the last index we can
//     truncate away, and
// (3) is similar to (2) in that we assert that we're not truncating past
//     the last known CommitIndex.
```

We additionally include Raphael's test that was able to shake out the
panic observed in #43605 much more efficiently.

Release note: Critical bug fix that would cause panics out in the wild.

### CODE REVIEW

**Comment by irfansharif** [comment]
Question for reviewers: I don't know how I feel about backporting this diff to release-20.1. I think I'd also be ok with downgrading the panic to a `log.Warning` in release 20.1, or just removing it entirely. I expect users to run into this panic out in the wild, so something does need to happen one way or another.

**Review by nvb — COMMENTED** [review]
Thanks for tracking this down Irfan! Your analysis in https://github.com/cockroachdb/cockroach/issues/43605#issuecomment-607543473 looks sound.

> Question for reviewers: I don't know how I feel about backporting this diff to release-20.1. Given how many times I had to revise that particular block of code, I wouldn't be surprised if it catches more panics over this next development cycle.

Given that we expect users to hit this if we don't fix it, I'm ok backporting this change once we feel good about it. There are a few more weeks of testing before the release goes out the door.

> Reviewed 2 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/47143#-:-M4LP52q9wbHYStrd9vR:b-yuzage)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @irfansharif, @nvanbenschoten, and @tbg)

___
*[pkg/cmd/roachtest/many_splits.go, line 35 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/47143#-M4LIJ6i2xk1p41DXUrS:-M4LIJ6i2xk1p41DXUrT:bytvknj) ([raw file](https://github.com/cockroachdb/cockroach/blob/bfe57bc2daa88535ab56a4274d64673e0aaec746/pkg/cmd/roachtest/many_splits.go#L35)):*
> ```Go
> 
>         err := retry.ForDuration(30*time.Second, func() error {
>             t.l.Printf("waiting for up-replication\n")
> ```

Is `Cluster.waitForFullReplication()` insufficient?
___
*[pkg/cmd/roachtest/many_splits.go, line 60 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/47143#-M4LIn2RC0kU1dTUrAH2:-M4LIn2RC0kU1dTUrAH3:b-by43zd) ([raw file](https://github.com/cockroachdb/cockroach/blob/bfe57bc2daa88535ab56a4274d64673e0aaec746/pkg/cmd/roachtest/many_splits.go#L60)):*
> ```Go
>     }()
> 
>     for nodeID := 1; nodeID <= c.spec.NodeCount; nodeID++ {
> ```

If you put everything else in a monitor (see tests like those in `kv.go`), this should be done for you.
___
*[pkg/kv/kvserver/raft_log_queue.go, line 465 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/47143#-M4LJAbECY5zHk9odHnv:-M4LJAbECY5zHk9odHnw:b-8cjh7a) ([raw file](https://github.com/cockroachdb/cockroach/blob/bfe57bc2daa88535ab56a4274d64673e0aaec746/pkg/kv/kvserver/raft_log_queue.go#L465)):*
> ```Go
> 	}
> 
> 	// Invariants:	FirstIndex    <= LastIndex + 1                          (1)
> ```

nit: the spacing is off on this one.
___
*[pkg/kv/kvserver/raft_log_queue.go, line 470 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/47143#-M4LLMb75Yk2z6JYe-o_:-M4LLMb8DhiulVixiiN1:bcfgvqe) ([raw file](https://github.com/cockroachdb/cockroach/blob/bfe57bc2daa88535ab56a4274d64673e0aaec746/pkg/kv/kvserver/raft_log_queue.go#L470)):*
> ```Go
> 	//              NewFirstIndex <= CommitIndex + 1                        (4)
> 	//
> 	// Intuitively we'd expect (1) to be `FirstIndex <= LastIndex`. However, the
> ```

Ugh, the semantics around `FirstIndex` and `LastIndex` in `raft.Storage` are horrendous. Even `raft.MemoryStorage` (which is defined right next to it) is confusing to understand because of it. After staring at it for a bit, I believe the root of the problem comes from the fact that both `FirstIndex` and `LastIndex` are inclusive, so there's no good way to represent an empty log. So `FirstIndex` is set to the first index in the possibly-empty log and `LastIndex` is allowed to fall behind it when the log is empty. Since `FirstIndex` can change depending on whether the log has been truncated or not, the code we had here before didn't work in all cases and we always have to compare FirstIndex and LastIndex to detect the empty log case.

Do you think it would be easier to write this invariant if we separated out the empty log case completely? Can we detect that above here with a simple `FirstIndex == LastIndex + 1` check?

More generally, I'm wondering if we can solve this with a little more type safety going forward (not to backport). You could picture expressing `lastIndex` (and `lastTerm`, while we're here) as an `option<uint64>` and letting the unset value represent an empty log. That would force everyone who deals with the value to consider the empty log case explicitly. We're already doing something similar with `invalidLastTerm`, but of course, there's no type system to enforce proper usage of that sentinel value.

**Review by nvb — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/47143)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @irfansharif, @nvanbenschoten, and @tbg)

___
*[pkg/kv/kvserver/raft_log_queue.go, line 470 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/47143#-M4LLMb75Yk2z6JYe-o_:-M4ME3g59cCiIh5__UDu:b1jrout) ([raw file](https://github.com/cockroachdb/cockroach/blob/bfe57bc2daa88535ab56a4274d64673e0aaec746/pkg/kv/kvserver/raft_log_queue.go#L470)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Ugh, the semantics around `FirstIndex` and `LastIndex` in `raft.Storage` are horrendous. Even `raft.MemoryStorage` (which is defined right next to it) is confusing to understand because of it. After staring at it for a bit, I believe the root of the problem comes from the fact that both `FirstIndex` and `LastIndex` are inclusive, so there's no good way to represent an empty log. So `FirstIndex` is set to the first index in the possibly-empty log and `LastIndex` is allowed to fall behind it when the log is empty. Since `FirstIndex` can change depending on whether the log has been truncated or not, the code we had here before didn't work in all cases and we always have to compare FirstIndex and LastIndex to detect the empty log case.

Do you think it would be easier to write this invariant if we separated out the empty log case completely? Can we detect that above here with a simple `FirstIndex == LastIndex + 1` check?

More generally, I'm wondering if we can solve this with a little more type safety going forward (not to backport). You could picture expressing `lastIndex` (and `lastTerm`, while we're here) as an `option<uint64>` and letting the unset value represent an empty log. That would force everyone who deals with the value to consider the empty log case explicitly. We're already doing something similar with `invalidLastTerm`, but of course, there's no type system to enforce proper usage of that sentinel value.
</blockquote></details>

Here's a strawman optional library we can consider using if we feel inspired to go down this path: https://github.com/nvanbenschoten/optional.

**Review by irfansharif — COMMENTED** [review]
TFTR. Updated the invariants to consider the empty log case explicitly. I'm still a bit uneasy about pushing this into 20.1 but I'll defer to you here.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/47143#-:-M4PURL32PbSHQ5PBL7Q:bpknoq4)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @nvanbenschoten and @tbg)

___
*[pkg/cmd/roachtest/many_splits.go, line 35 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/47143#-M4LIJ6i2xk1p41DXUrS:-M4PNJeD2E-ty0wDx8lO:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/bfe57bc2daa88535ab56a4274d64673e0aaec746/pkg/cmd/roachtest/many_splits.go#L35)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Is `Cluster.waitForFullReplication()` insufficient?
</blockquote></details>

Done.
___
*[pkg/cmd/roachtest/many_splits.go, line 60 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/47143#-M4LIn2RC0kU1dTUrAH2:-M4PNIrcDbphjG_zFL-2:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/bfe57bc2daa88535ab56a4274d64673e0aaec746/pkg/cmd/roachtest/many_splits.go#L60)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

If you put everything else in a monitor (see tests like those in `kv.go`), this should be done for you.
</blockquote></details>

Done.
___
*[pkg/kv/kvserver/raft_log_queue.go, line 465 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/47143#-M4LJAbECY5zHk9odHnv:-M4PNT3K9Wl8ezyldixQ:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/bfe57bc2daa88535ab56a4274d64673e0aaec746/pkg/kv/kvserver/raft_log_queue.go#L465)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

nit: the spacing is off on this one.
</blockquote></details>

Done.
___
*[pkg/kv/kvserver/raft_log_queue.go, line 470 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/47143#-M4LLMb75Yk2z6JYe-o_:-M4PTkyICKVMYdlhSKqO:bdytjkz) ([raw file](https://github.com/cockroachdb/cockroach/blob/bfe57bc2daa88535ab56a4274d64673e0aaec746/pkg/kv/kvserver/raft_log_queue.go#L470)):*
> Do you think it would be easier to write this invariant if we separated out the empty log case completely? Can we detect that above here with a simple FirstIndex == LastIndex + 1 check?

I like that better, done. I realized I was being overly defensive about this change given the release cycle, but whether I'm explicit about it or not, I'm checking for the same things. So better to be explicit about it all.

> Here's a strawman optional library we can consider using if we feel inspired to go down this path: https://github.com/nvanbenschoten/optional.

Heh, good nerd snipe. Could be useful for us once we have a `replication` package of sorts wrapping around raft.Storage and the like.

File: pkg/cmd/roachtest/many_splits.go [hunk 1]
```diff
@@ -0,0 +1,56 @@
...
+	c.Start(ctx, t, args)
+
+	// Wait for upreplication then create many ranges.
+	func() {
+		db := c.Conn(ctx, 1)
+		defer db.Close()
+
+		waitForFullReplication(t, db)
+
+		const numRanges = 2000
```
Comment (knz) [inline pkg/cmd/roachtest/many_splits.go:32]: Are you sure about this "2000"

This will make the test run forever. Is the bug not visible with fewer ranges?

Comment (irfansharif) [reply pkg/cmd/roachtest/many_splits.go:32]:
```
20:58:47 many_splits.go:33: creating 2000 ranges...
21:00:01 many_splits.go:46: checking node 1 is live
```

It takes just over a minute now, how long is too long as far as roachtests go? It will show up with few ranges, so happy to reduce it as needed.

**Review by nvb — COMMENTED** [review]
> Reviewed 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/47143)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @irfansharif, @knz, and @tbg)

___
*[pkg/cmd/roachtest/many_splits.go, line 60 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/47143#-M4LIn2RC0kU1dTUrAH2:-M4Q-5_f414OE2KaftQA:b-1iyjz1) ([raw file](https://github.com/cockroachdb/cockroach/blob/bfe57bc2daa88535ab56a4274d64673e0aaec746/pkg/cmd/roachtest/many_splits.go#L60)):*
<details><summary><i>Previously, irfansharif (irfan sharif) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Sorry, I was unclear. I meant to put the `CREATE TABLE/ALTER TABLE SPLIT` code in a monitor and then get rid of the manual liveness checking entirely.
___
*[pkg/kv/kvserver/raft_log_queue.go, line 498 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/47143#-M4QpyEy6C9uB36qVvIe:-M4QpyEy6C9uB36qVvIf:b-r6i11y) ([raw file](https://github.com/cockroachdb/cockroach/blob/a123a5125a2aea0113e08bb4bd75b5f7cbcd7186/pkg/kv/kvserver/raft_log_queue.go#L498)):*
> ```Go
> 	empty := input.FirstIndex == input.LastIndex+1
> 	valid := empty || (decision.NewFirstIndex >= input.FirstIndex) &&
> 		(decision.NewFirstIndex <= input.LastIndex+1) &&
> ```

Do we still need the +1 in this line and the next?

**Review by irfansharif — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/47143)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @knz, @nvanbenschoten, and @tbg)

___
*[pkg/cmd/roachtest/many_splits.go, line 60 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/47143#-M4LIn2RC0kU1dTUrAH2:-M4VUCb66Cir6tKbiai6:b-yjenz2) ([raw file](https://github.com/cockroachdb/cockroach/blob/bfe57bc2daa88535ab56a4274d64673e0aaec746/pkg/cmd/roachtest/many_splits.go#L60)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Sorry, I was unclear. I meant to put the `CREATE TABLE/ALTER TABLE SPLIT` code in a monitor and then get rid of the manual liveness checking entirely.
</blockquote></details>

Ah, I should have been more familiar with this monitor machinery. Wish it had comments. Done, PTAL.
___
*[pkg/kv/kvserver/raft_log_queue.go, line 498 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/47143#-M4QpyEy6C9uB36qVvIe:-M4VULphBQ1eLnVz99v0:b-26jj0e) ([raw file](https://github.com/cockroachdb/cockroach/blob/a123a5125a2aea0113e08bb4bd75b5f7cbcd7186/pkg/kv/kvserver/raft_log_queue.go#L498)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Do we still need the +1 in this line and the next?
</blockquote></details>

:facepalm: Done.

**Review by nvb — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/47143#-:-M4VaVqT3dKa1iDp_JoN:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @irfansharif, @knz, and @tbg)

___
*[pkg/cmd/roachtest/many_splits.go, line 31 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/47143#-M4VaNDU5tPGpCVGAGNh:-M4VaNDU5tPGpCVGAGNi:b-4cww7v) ([raw file](https://github.com/cockroachdb/cockroach/blob/57eed5dd9bd989cd06435bd4c28204d914ef99bd/pkg/cmd/roachtest/many_splits.go#L31)):*
> ```Go
> 	waitForFullReplication(t, db)
> 
> 	m := newMonitor(ctx, c, c.Range(1, c.spec.NodeCount))
> ```

`s/c.Range(1, c.spec.NodeCount)/c.All()/`

**Review by irfansharif — COMMENTED** [review]
@nvanbenschoten: had to make (yet) another adjustment to the invariants, PTAL. more FirstIndex drudgery, sigh.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/47143#-:-M4VxMO9EOuk51S1RCUG:b-uzraw2)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @knz, @nvanbenschoten, and @tbg)

**Review by nvb — COMMENTED** [review]
> Reviewed 1 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/47143)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @irfansharif, @knz, @nvanbenschoten, and @tbg)

___
*[pkg/kv/kvserver/raft_log_queue.go, line 502 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/47143#-M4Vzioa8-G_bonvIITS:-M4VziobB6Oxha2palmm:b-wmdw25) ([raw file](https://github.com/cockroachdb/cockroach/blob/b011c4eb496b4179c51981c83d9e6d4cad1237cf/pkg/kv/kvserver/raft_log_queue.go#L502)):*
> ```Go
> 		(decision.NewFirstIndex <= input.LastIndex) &&
> 		(decision.NewFirstIndex <= decision.CommitIndex ||
> 			 decision.CommitIndex == 10 && decision.NewFirstIndex == decision.CommitIndex+1)
> ```

Should we pull out another condition to capture this case specification? Something like:

```
logEmpty := input.FirstIndex == input.LastIndex+1
logIndexValid := logEmpty || (decision.NewFirstIndex >= input.FirstIndex) && (decision.NewFirstIndex <= input.LastIndex)
noCommittedEntries := input.FirstIndex == input.RaftStatus.Commit+1
commitIndexValid := noCommittedEntries || (decision.NewFirstIndex <= decision.CommitIndex)
valid := logIndexValid && commitIndexValid
```

**Review by irfansharif — COMMENTED** [review]
TFTR!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/47143#-:-M4Wubd022j0wvBEBNuo:b-814g8k)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @knz, @nvanbenschoten, and @tbg)

___
*[pkg/kv/kvserver/raft_log_queue.go, line 502 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/47143#-M4Vzioa8-G_bonvIITS:-M4Wu6ix7D8QEKcIu6Fy:b-unanh1) ([raw file](https://github.com/cockroachdb/cockroach/blob/b011c4eb496b4179c51981c83d9e6d4cad1237cf/pkg/kv/kvserver/raft_log_queue.go#L502)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Should we pull out another condition to capture this case specification? Something like:

```
logEmpty := input.FirstIndex == input.LastIndex+1
logIndexValid := logEmpty || (decision.NewFirstIndex >= input.FirstIndex) && (decision.NewFirstIndex <= input.LastIndex)
noCommittedEntries := input.FirstIndex == input.RaftStatus.Commit+1
commitIndexValid := noCommittedEntries || (decision.NewFirstIndex <= decision.CommitIndex)
valid := logIndexValid && commitIndexValid
```
</blockquote></details>

Ah, I like that, thanks!

**Comment by irfansharif** [comment]
Infra flake. Rerunning.

**Comment by nvanbenschoten** [comment]
Nice job on this! You were asking earlier about whether to backport this or not. Given the state of the v20.1 release and the subtlety of this change, I'm thinking it's probably best to let this sit of master for a week or so and then try to get it in for `v20.1.1`. We know what the symptoms are if we leave this unpatched, so we should at least be able to easily identify any reports of it.

What do you think?

**Comment by irfansharif** [comment]
What do you think of my earlier suggestion? Patching up v20.1.0 to reduce the severity of the panic to a warning perhaps? Or just removing it entirely. (As opposed to hardening the panic condition that we did here.)
