### PR TITLE
roachtest: network/client-connection-timeout fix port assignment bug

### LINKED ISSUE #117869: roachtest: network/client-connection-timeout failed
roachtest.network/client-connection-timeout [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/13574516?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/13574516?buildTab=artifacts#/network/client-connection-timeout) on master @ [1898adc059e9b3026fd5a7ed88dc41cbb006abfc](https://github.com/cockroachdb/cockroach/commits/1898adc059e9b3026fd5a7ed88dc41cbb006abfc):

```
(soon.go:64).SucceedsWithin: condition failed to evaluate within 45s: from network.go:339: unexepcted count :0
test artifacts and logs in: /artifacts/network/client-connection-timeout/run_1
```

Parameters:
 - <code>ROACHTEST_arch=amd64</code>
 - <code>ROACHTEST_cloud=gce</code>
 - <code>ROACHTEST_coverageBuild=false</code>
 - <code>ROACHTEST_cpu=4</code>
 - <code>ROACHTEST_encrypted=false</code>
 - <code>ROACHTEST_metamorphicBuild=false</code>
 - <code>ROACHTEST_ssd=0</code>
<details><summary>Help</summary>
<p>

See: [roachtest README](https://github.com/cockroachdb/cockroach/blob/master/pkg/cmd/roachtest/README.md)

See: [How To Investigate \(internal\)](https://cockroachlabs.atlassian.net/l/c/SSSBr8c7)

See: [Grafana](https://go.crdb.dev/roachtest-grafana/teamcity-13574516/network-client-connection-timeout/1705512824892/1705513024358)

</p>
</details>
/cc @cockroachdb/sql-foundations
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*network/client-connection-timeout.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)
</sub>

Jira issue: CRDB-35394

### PR DESCRIPTION
**Pull request by fqazi**
Previously, this test incorrectly did not select a port for the SQL client when starting up the server, which would cause this test to fail when the client machine attempted to connect. To address this, this patch sets SQL listen port when starting the cluster to the default value.

Fixes: #117869

Release note: None

### CODE REVIEW

**Review by rafiss — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/117884)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @DarrylWong, @fqazi, and @renatolabs)

___
*[`pkg/cmd/roachtest/tests/network.go` line 327 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/117884#-NoO8OAzCRW5T6T6Sxk0:-NoO8OB-73SgK_JoRvST:b-plhw38) ([raw file](https://github.com/cockroachdb/cockroach/blob/8389c29fc01f1d4793a5f578d07a641f75e9a500/pkg/cmd/roachtest/tests/network.go#L327)):*
> ```Go
> 			return err
> 		}
> 		commandThatWillDisconnect := fmt.Sprintf(`./cockroach sql --certs-dir %s --url "postgres://root@%s:26257" -e "SELECT pg_sleep(600)"`, certsDir, ips[0])
> ```

instead of hardcoding the port above, could we just use `c.ExternalPGUrl()` here?

**Review by DarrylWong — COMMENTED** [review]
I don't think there's a reason this test needs to explicitly use `26257`.  Instead we can learn the port through the env. Left some suggestions on how to do that.

I'd also be happy to do it for you since I do notice that I missed some hardcoded `26257s`  in the`network/authentication` tests when I made the default port PR (my bad!)

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/117884#-:-NoO43PU76S34uAGzdvj:b-g7044n)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @fqazi and @renatolabs)

___
*[`pkg/cmd/roachtest/tests/network.go` line 281 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/117884#-NoO8KD_92Wj0dpEcsHU:-NoO8KD_92Wj0dpEcsHV:b-vrglo0) ([raw file](https://github.com/cockroachdb/cockroach/blob/8389c29fc01f1d4793a5f578d07a641f75e9a500/pkg/cmd/roachtest/tests/network.go#L281)):*
> ```Go
> set -e;
> sudo iptables -D INPUT -p tcp --dport 26257 -j DROP;
> sudo iptables -D OUTPUT -p tcp --dport 26257 -j DROP;
> ```

Unrelated to this test failure but these 26257s probably need to be changed as well.
___
*[`pkg/cmd/roachtest/tests/network.go` line 327 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/117884#-NoO4nhPD5Rs3t_yLfRQ:-NoO4nhPD5Rs3t_yLfRR:bynkacj) ([raw file](https://github.com/cockroachdb/cockroach/blob/8389c29fc01f1d4793a5f578d07a641f75e9a500/pkg/cmd/roachtest/tests/network.go#L327)):*
> ```Go
> 			return err
> 		}
> 		commandThatWillDisconnect := fmt.Sprintf(`./cockroach sql --certs-dir %s --url "postgres://root@%s:26257" -e "SELECT pg_sleep(600)"`, certsDir, ips[0])
> ```

instead of hardcoding the connection string `--url "postgres://root@%s:26257"`, we can get the url from the `roachtestutil.DefaultPGUrl()` helper.

i.e.



_Code snippet:_
```Go
		pgurl, err := roachtestutil.DefaultPGUrl(ctx, c, t.L(), clientNode)
		if err != nil {
			t.Fatal(err)
		}
```
___
*[`pkg/cmd/roachtest/tests/network.go` line 356 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/117884#-NoO5hD_0ss2HtGb4sE8:-NoO5hD_0ss2HtGb4sE9:b-fp7kev) ([raw file](https://github.com/cockroachdb/cockroach/blob/8389c29fc01f1d4793a5f578d07a641f75e9a500/pkg/cmd/roachtest/tests/network.go#L356)):*
> ```Go
> 
> # Drop any client traffic to CRDB.
> sudo iptables -A INPUT -p tcp --sport 26257 -j DROP;
> ```

Instead of using `26257` we get the port from `fmt.Sprintf("{pgport%s}", clientNode)`
___
*[`pkg/cmd/roachtest/tests/network.go` line 357 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/117884#-NoO6qNbBVXrau_0wOiC:-NoO6qNbBVXrau_0wOiD:bnj7hl0) ([raw file](https://github.com/cockroachdb/cockroach/blob/8389c29fc01f1d4793a5f578d07a641f75e9a500/pkg/cmd/roachtest/tests/network.go#L357)):*
> ```Go
> # Drop any client traffic to CRDB.
> sudo iptables -A INPUT -p tcp --sport 26257 -j DROP;
> sudo iptables -A OUTPUT -p tcp --dport 26257 -j DROP;
> ```

same as above

**Review by fqazi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/117884)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @DarrylWong, @rafiss, and @renatolabs)

___
*[`pkg/cmd/roachtest/tests/network.go` line 327 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/117884#-NoO4nhPD5Rs3t_yLfRQ:-NoOQ-vV5h3qJBwUgxZW:buef4bg) ([raw file](https://github.com/cockroachdb/cockroach/blob/8389c29fc01f1d4793a5f578d07a641f75e9a500/pkg/cmd/roachtest/tests/network.go#L327)):*
<details><summary><i>Previously, DarrylWong wrote…</i></summary><blockquote>

instead of hardcoding the connection string `--url "postgres://root@%s:26257"`, we can get the url from the `roachtestutil.DefaultPGUrl()` helper.

i.e.
</blockquote></details>

Yeah both of those don't work because of the certificate path on the client machine. But, I was able to use roachprod.PgURL which allows me to select that path and replaced it with that.
___
*[`pkg/cmd/roachtest/tests/network.go` line 327 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/117884#-NoO8OAzCRW5T6T6Sxk0:-NoOQ8eHEZRwLrzmZznZ:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/8389c29fc01f1d4793a5f578d07a641f75e9a500/pkg/cmd/roachtest/tests/network.go#L327)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

instead of hardcoding the port above, could we just use `c.ExternalPGUrl()` here?
</blockquote></details>

Done.
___
*[`pkg/cmd/roachtest/tests/network.go` line 356 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/117884#-NoO5hD_0ss2HtGb4sE8:-NoOQ9zRAnPeZc502Oxw:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/8389c29fc01f1d4793a5f578d07a641f75e9a500/pkg/cmd/roachtest/tests/network.go#L356)):*
<details><summary><i>Previously, DarrylWong wrote…</i></summary><blockquote>

Instead of using `26257` we get the port from `fmt.Sprintf("{pgport%s}", clientNode)`
</blockquote></details>

Done.
___
*[`pkg/cmd/roachtest/tests/network.go` line 357 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/117884#-NoO6qNbBVXrau_0wOiC:-NoOQADcA789eZgBGE9E:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/8389c29fc01f1d4793a5f578d07a641f75e9a500/pkg/cmd/roachtest/tests/network.go#L357)):*
<details><summary><i>Previously, DarrylWong wrote…</i></summary><blockquote>

same as above
</blockquote></details>

Done.

**Review by rafiss — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/117884)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @DarrylWong, @fqazi, and @renatolabs)

___
*[`pkg/cmd/roachtest/tests/network.go` line 281 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/117884#-NoO8KD_92Wj0dpEcsHU:-NoOb8k4CEq1T1HAqDzY:bup85t6) ([raw file](https://github.com/cockroachdb/cockroach/blob/8389c29fc01f1d4793a5f578d07a641f75e9a500/pkg/cmd/roachtest/tests/network.go#L281)):*
<details><summary><i>Previously, DarrylWong wrote…</i></summary><blockquote>

Unrelated to this test failure but these 26257s probably need to be changed as well.
</blockquote></details>

seems important to fix this -- this test is not actually doing anything useful otherwise. let's make sure to either fix here or file an issue if @DarrylWong is planning to fix this. (if it needs to be backported, then let's do this separately from this PR)
___
*[`pkg/cmd/roachtest/tests/network.go` line 311 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/117884#-NoOdfHt5LPNdzJwrfvs:-NoOdfHt5LPNdzJwrfvt:b-callc1) ([raw file](https://github.com/cockroachdb/cockroach/blob/7c68272d96314356b0d69a21f4bfc84e8f85501c/pkg/cmd/roachtest/tests/network.go#L311)):*
> ```Go
> 	settings := install.MakeClusterSettings(install.SecureOption(true))
> 	defaultOptions := option.DefaultStartOpts()
> 	defaultOptions.RoachprodOpts.SQLPort = config.DefaultSQLPort
> ```

now that we have the logic below, i think we need to get rid of this hardcoding.

**Comment by DarrylWong** [comment]
> if it needs to be backported, then let's do this separately from this PR

Thats a good point. It doesn't need to be backported just yet (we've been holding off to shake out flakes) but will be eventually. I can put a PR out in that case then.

**Review by fqazi — COMMENTED** [review]
Updated the other tests in the same file to avoid hard coding the port

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/117884#-:-NoPqzME1FiyUGx5mo6d:b-m1jhaj)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @DarrylWong, @rafiss, and @renatolabs)

___
*[`pkg/cmd/roachtest/tests/network.go` line 281 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/117884#-NoO8KD_92Wj0dpEcsHU:-NoPr95JDxfB20vX_g76:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/8389c29fc01f1d4793a5f578d07a641f75e9a500/pkg/cmd/roachtest/tests/network.go#L281)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

seems important to fix this -- this test is not actually doing anything useful otherwise. let's make sure to either fix here or file an issue if @DarrylWong is planning to fix this. (if it needs to be backported, then let's do this separately from this PR)
</blockquote></details>

Done.
___
*[`pkg/cmd/roachtest/tests/network.go` line 311 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/117884#-NoOdfHt5LPNdzJwrfvs:-NoPr9wM7ij4aRmcmcx9:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/7c68272d96314356b0d69a21f4bfc84e8f85501c/pkg/cmd/roachtest/tests/network.go#L311)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

now that we have the logic below, i think we need to get rid of this hardcoding.
</blockquote></details>

Done.

File: pkg/cmd/roachtest/tests/network.go [hunk 1]
```diff
@@ -350,9 +356,10 @@ sudo iptables -P INPUT ACCEPT;
 sudo iptables -P OUTPUT ACCEPT;
 
 # Drop any client traffic to CRDB.
-sudo iptables -A INPUT -p tcp --sport 26257 -j DROP;
-sudo iptables -A OUTPUT -p tcp --dport 26257 -j DROP;
-`
+sudo iptables -A INPUT -p tcp --sport {pgport%s} -j DROP;
```
Comment (rafiss) [inline pkg/cmd/roachtest/tests/network.go:359]: looks like Daryl also has this PR: https://github.com/cockroachdb/cockroach/pull/117909

but, i'm fine merging either one

**Review by rafiss — APPROVED** [review]

**Review by DarrylWong — APPROVED** [review]
Thanks!

**Comment by fqazi** [comment]
@rafiss @DarrylWong TFTR!

bors r+
