### PR TITLE
sql/pgwire: improve connection matching algorithm

### LINKED ISSUE #41999: gssapiccl: psql 11.5 and 12 don't seem to work anymore
TestComposeGSS started failing a bit ago. Upon investigation, it was due to our use of the `postgres:11` docker for psql. When that got bumped to 11.5 it started to error. The errors suggest our cmuxer is failing to recognize some connections as pgwire and is sending them over to grpc. We need to figure out what's going on here because it seems that there's a risk that our gss auth may be broken on some versions of psql, and perhaps via other ways too?

### PR DESCRIPTION
**Pull request by madelynnblue**
Postgres 11.5 and 12.0 added an encrypted GSS request. When those versions
of psql tried to auth via GSS to cockroach, it would first try encrypted
GSS, which we don't support. Our pgwire.Match function (used in cmuxing
incoming connections) didn't detect this new request code and thus sent
the connection over to grpc, resulting in a confusing error message that
would also cause psql to not fallback to unencrypted GSS.

We considered just checking for 1234 << 16 in the upper bits as forward
protecting against more new request codes, but decided that the risk
that would incorrectly match some TLS certs was not worth it.

Fixes #41999

Release note(bug fix): psql from Postgres 11.5 and 12.0 is now supported
for GSS connections.

### CODE REVIEW

**Review by bdarnell — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/42007)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @bdarnell and @mjibson)

___
*[pkg/sql/pgwire/server.go, line 107 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/42007#-LsSsD8JB2oEWT38-ypS:-LsSsD8K08slVHqutLMH:b-697dy6) ([raw file](https://github.com/cockroachdb/cockroach/blob/306c41b4db5f8c9e72c77b9cf80c83622852ee61/pkg/sql/pgwire/server.go#L107)):*
> ```Go
> 
> const (
> 	version3Major = 3
> ```

Naming nits: version30, requestCancel, and requestSSL should have a common prefix because they're comparable to each other. The naming element that marks version3Major and requestBase as different from their 32-bit counterparts should be the same between those two variables. 
___
*[pkg/sql/pgwire/server.go, line 282 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/42007#-LsSp1Uz5askqWhDExoY:-LsSp1Uz5askqWhDExoZ:b-mdgcwt) ([raw file](https://github.com/cockroachdb/cockroach/blob/306c41b4db5f8c9e72c77b9cf80c83622852ee61/pkg/sql/pgwire/server.go#L282)):*
> ```Go
> 	// known upper bits (3 for version 3.0 and 1234 for other requests).
> 	base := version >> 16
> 	return base == version3Major || base == requestBase
> ```

This also weakens the matching for version 3 (it now only matches on the major version number instead of the entire int32)

Any weakening of this matcher makes me nervous - how confident can we be that a TLS handshake will never match it? I remember looking at the TLS spec and verifying that we'd never see 0x00030000 in this spot, but 0x0003 (and 0x1234) are pretty weak validators. Since there's a small and infrequently-changing set of these, I'd rather just add a constant for GSSENCRequest and look for another 32-bit match instead of only looking at 16 bits.

**Review by madelynnblue — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/42007)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @bdarnell and @mjibson)

___
*[pkg/sql/pgwire/server.go, line 282 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/42007#-LsSp1Uz5askqWhDExoY:-LsT-dM45J41-2NcgrUi:b9y5y89) ([raw file](https://github.com/cockroachdb/cockroach/blob/306c41b4db5f8c9e72c77b9cf80c83622852ee61/pkg/sql/pgwire/server.go#L282)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

This also weakens the matching for version 3 (it now only matches on the major version number instead of the entire int32)

Any weakening of this matcher makes me nervous - how confident can we be that a TLS handshake will never match it? I remember looking at the TLS spec and verifying that we'd never see 0x00030000 in this spot, but 0x0003 (and 0x1234) are pretty weak validators. Since there's a small and infrequently-changing set of these, I'd rather just add a constant for GSSENCRequest and look for another 32-bit match instead of only looking at 16 bits. 
</blockquote></details>

Yes, I was worried about this when trying to fall asleep last night. It is somewhat absolved by the fact that it must be preceded by a successful ReadUntypedMsg call.

I thought to make the above change because it would protect against any future request codes being added (this is the second of such bugs, the first was when the cancel code was similarly causing grpc to be used). The two problems we're balancing here are the risk of a TLS cert successfully passing this Match func and future bugs due to new request codes, I can see how the TLS risk is higher and should be what we protect against. I'll hard code it.

**Comment by mjibson** [comment]
RFAL

File: pkg/sql/pgwire/server.go [hunk 1]
```diff
@@ -107,6 +107,7 @@ const (
 	version30     = 196608
 	versionSSL    = 80877103
 	versionCancel = 80877102
+	versionGSSENC = 80877104
```
Comment (jordanlewis) [inline pkg/sql/pgwire/server.go]: nit: I think future spelunkers would appreciate a comment above both this new constant and the whole block of constants explaining what they're for, how they're derived, and why you might want to add a new one.

**Review by jordanlewis — APPROVED** [review]
Code LGTM (though 👨‍🔬 🐶 on the constant itself obviously). Do we need further tests? I also added a request for improved comments on the constants themselves.

**Review by bdarnell — APPROVED** [review]
> Reviewed 1 of 2 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/42007)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @bdarnell and @mjibson)

File: pkg/sql/pgwire/server.go (hunk 1 above)
Comment (mjibson) [reply pkg/sql/pgwire/server.go]: Added comments about this.
