### PR TITLE
changefeedccl: Ensure correct file ordering.

### LINKED ISSUE #89683: changefeedccl: Async flushes may produce out of order events
Failure observed on master:
```
Failed
=== RUN   TestChangefeedNemeses/cloudstorage
    helpers_test.go:743: making server as system tenant
    helpers_test.go:830: making cloudstorage feed factory
    nemeses_test.go:40: topic foo partition : saw new row timestamp 1665420895637060333.0000000000 after 1665420896550554241.0000000000 was seen
    nemeses_test.go:40: topic foo partition : saw new row timestamp 1665420895561568242.0000000000 after 1665420896550554241.0000000000 was seen
    --- FAIL: TestChangefeedNemeses/cloudstorage (11.99s)
```

The test ran with parallel workers, and async flushing enabled.

My best guess is that async flushing could produce the following:
  k@t1 is written to sink and causes flush f1
  k@t2 is written to sink and causes flush f2
  f2 completes before f1

(thanks @ajwerner for reporting this)

  

Jira issue: CRDB-20371

### PR DESCRIPTION
**Pull request by miretskiy**
When async flushing enabled, the following sequence of events is possible (even if very unlikely):

 * k@t1 is emitted, causing async flush to write file f1 
 * k@t2 is emitted, causing async flush to write file f2 
 * f2 is written out before f1.

In this unlikely scenario -- and the reason why it's unlikely is that we have to generate megabytes of data to cause a flush, unless, file_size parameter was pathologically small -- if a client were to read the contents of the directory right after step 2, and then read directory after step 3, the client will first observe k@t2, and then observe k@t1 -- which is a violation of ordering guarantees.

This PR fixes this issue by adopting a queue so that if there is a pending flush in flight, the next flush is queued behind.

It is possible that this simple approach may result in throughput decrease.  This situation will occur if the underlying storage (s3 or gcp) cannot keep up with writing out data before the next file comes in.  However, at this point, such situation is unlikely for two reasons: one, the rest of changefeed machinery must be able to generate one or more files worth of data before the previous flush completes -- and this task in of itself is not trivial, and two, changefeed must have enough memory allocated to it so that pushback mechanism does not trigger.  The above assumption was validated in reasonably sized test -- i.e. the non-zero queue depth was never observed. Nonetheless, this PR also adds a log message which may be helpful to detect the situation when the sink might not keep up with the incoming data rate.

A more complex solution -- for example, allow unlimited inflight requests during backfill -- may be revisited later, if the above assumption proven incorrect.

Fixes #89683

Release note: None.

### CODE REVIEW

File: pkg/ccl/changefeedccl/sink_cloudstorage.go [hunk 1]
```diff
@@ -648,21 +662,55 @@ func (s *cloudStorageSink) flushFile(ctx context.Context, file *cloudStorageSink
...
-			// We must use the same type for error we store in flushErr.
-			s.flushErr.CompareAndSwap(nil, &flushError{error: err})
+	s.flushQueue.Lock()
+	defer s.flushQueue.Unlock()
+	if s.flushQueue.q == nil {
+		// Start a new go routine if the flush queue is empty.
+		s.flushGroup.Add(1)
+		go func() {
+			s.asyncFlush(file, dest)
+		}()
```
Comment (ajwerner) [inline pkg/ccl/changefeedccl/sink_cloudstorage.go:672]: Why is this not `go s.asyncFlush(file, dest)`?

File: pkg/ccl/changefeedccl/sink_cloudstorage.go [hunk 2]
```diff
@@ -648,21 +662,55 @@ func (s *cloudStorageSink) flushFile(ctx context.Context, file *cloudStorageSink
...
 
-type flushError struct {
-	error
+func (s *cloudStorageSink) asyncFlush(file *cloudStorageSinkFile, dest string) {
+	defer s.flushGroup.Done()
+
+	pop := func(err error) destFile {
+		s.flushQueue.Lock()
+		defer s.flushQueue.Unlock()
+		s.flushQueue.err = err
```
Comment (ajwerner) [inline pkg/ccl/changefeedccl/sink_cloudstorage.go:692]: check to make sure this isn't populated already? It seems to me like this is racy because you don't check for an error when you go to append to the queue. Imagine the case where you have one flush call (and so nothing in the queue) and then it gets an error and assigns here. The goroutine returns but another call to flush above launches a new goroutine which then succeeds and clobbers this error. 

I feel like you should just simplify this code so that the file currently being flushed is at the front of the queue and it gets popped after it has succeeded. I think it'll simplify some things.

File: pkg/ccl/changefeedccl/sink_cloudstorage.go [hunk 3]
```diff
@@ -648,21 +662,55 @@ func (s *cloudStorageSink) flushFile(ctx context.Context, file *cloudStorageSink
...
-	go func() {
-		defer s.flushGroup.Done()
-		// NB: must use s.flushCtx; ctx may be short lived (i.e. cancelled).
-		if err := file.flushToStorage(s.flushCtx, s.es, dest, s.metrics); err != nil {
-			log.Errorf(ctx, "error flushing file to storage: %s", err)
-			// We must use the same type for error we store in flushErr.
-			s.flushErr.CompareAndSwap(nil, &flushError{error: err})
+	s.flushQueue.Lock()
+	defer s.flushQueue.Unlock()
+	if s.flushQueue.q == nil {
```
Comment (ajwerner) [inline pkg/ccl/changefeedccl/sink_cloudstorage.go:667]: If we launch the goroutine here we don't append to the queue, so it's still nil if we were to come here again, and we'd launch yet another goroutine, which seems bad. It seems to me like we ought to just always append to the queue and then have `asyncFlush` not take arguments.

Comment (miretskiy) [reply pkg/ccl/changefeedccl/sink_cloudstorage.go]: Ack.  Goog point.

File: pkg/ccl/changefeedccl/sink_cloudstorage.go (hunk 1 above)
Comment (miretskiy) [reply pkg/ccl/changefeedccl/sink_cloudstorage.go]: why not :)

File: pkg/ccl/changefeedccl/sink_cloudstorage.go (hunk 2 above)
Comment (miretskiy) [reply pkg/ccl/changefeedccl/sink_cloudstorage.go:695]: Good catch.
The reality is that I used to have exactly that code, but undoing a more complex version, I left the complexity I should have had.

File: pkg/ccl/changefeedccl/sink_cloudstorage.go [hunk 4]
```diff
@@ -648,21 +662,62 @@ func (s *cloudStorageSink) flushFile(ctx context.Context, file *cloudStorageSink
...
-			// We must use the same type for error we store in flushErr.
-			s.flushErr.CompareAndSwap(nil, &flushError{error: err})
+	s.flushQueue.Lock()
+	defer s.flushQueue.Unlock()
+	if s.flushQueue.err != nil {
+		return s.flushQueue.err
+	}
+
+	s.flushQueue.q = append(s.flushQueue.q, destFile{file: file, dest: dest})
+	if len(s.flushQueue.q) == 1 {
```
Comment (miretskiy) [inline pkg/ccl/changefeedccl/sink_cloudstorage.go:672]: i'm going to rerun the tests to see if I can hit > 1 queued item.

Comment (miretskiy) [reply pkg/ccl/changefeedccl/sink_cloudstorage.go:672]: Still wasn't able to get that; basically, in my test, I was generating 1 file every 300ms or so, and it appear that most flushes took well under 100ms; I suppose it is possible for this queue to be non-zero; but that's fine -- as the PR says, if it becomes a problem, we can revisit.

Comment (ajwerner) [reply pkg/ccl/changefeedccl/sink_cloudstorage.go:672]: Why not just set the file size to like 1 byte in testing?

Comment (miretskiy) [reply pkg/ccl/changefeedccl/sink_cloudstorage.go:672]: Nah, i mean i wanted to see how this runs in production.   Of course we can do something like that in a unit test

Comment (miretskiy) [reply pkg/ccl/changefeedccl/sink_cloudstorage.go:672]: Verified with crazy small file size (4kb), files are queued (and then some): 
```
I221016 20:46:26.324904 164297 ccl/changefeedccl/sink_cloudstorage.go:671 ⋮ [n2,f‹eb3415c6›,job=805708385569374209] 1565589  changefeed flush queue depth 667347; ~2669388000 bytes to flush
```

**Review by ajwerner — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/90011)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @miretskiy)

___
*[`pkg/ccl/changefeedccl/sink_cloudstorage.go` line 622 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/90011#-NEc0gjFDkcwpwUFyt1x:-NEc0gjFDkcwpwUFyt1y:bnsuxl) ([raw file](https://github.com/cockroachdb/cockroach/blob/8d57dd5a0ddae86b7d03f6e838bbce5e40eff0a8/pkg/ccl/changefeedccl/sink_cloudstorage.go#L622)):*
> ```Go
> // waitAsyncFlush waits until all async flushes complete.
> func (s *cloudStorageSink) waitAsyncFlush() error {
> 	s.flushGroup.Wait()
> ```

is this definitely safe? You're not allowed to add a to a wait group while you're waiting for it. It seems to me that something could be added to the queue while a wait call is going on. This can panic! https://pkg.go.dev/sync#WaitGroup.Add

**Comment by miretskiy** [comment]
> is this definitely safe? You're not allowed to add a to a wait group while you're waiting for it. It seems to me that something could be added to the queue while a wait call is going on. This can panic! https://pkg.go.dev/sync#WaitGroup.Add

blarg -- excellent catch.

File: pkg/ccl/changefeedccl/sink_cloudstorage.go [hunk 5]
```diff
@@ -308,8 +309,19 @@ type cloudStorageSink struct {
...
-	flushGroup       sync.WaitGroup
-	flushErr         atomic.Value
+	flushQueue       struct {
+		syncutil.Mutex
+		err           error
+		q             []destFile
+		numGoRoutines int
+	}
+	// Signaled whenever changes are made to flushQueue struct.
+	flushC *sync.Cond
```
Comment (ajwerner) [inline pkg/ccl/changefeedccl/sink_cloudstorage.go:319]: nit: put this in the `flushQueue` and don't make it a pointer.

Comment (miretskiy) [reply pkg/ccl/changefeedccl/sink_cloudstorage.go:319]: ack. done.

**Review by ajwerner — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/90011)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @miretskiy)

___
*[`pkg/ccl/changefeedccl/sink_cloudstorage.go` line 624 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/90011#-NEfFitO5fO_YRpqRTNd:-NEfFitPDb25PL__pZjQ:bt4hls) ([raw file](https://github.com/cockroachdb/cockroach/blob/05b69a4788cd0a61747323befc7d4985eaea9116/pkg/ccl/changefeedccl/sink_cloudstorage.go#L624)):*
> ```Go
> 
> // waitAsyncFlush waits until all async flushes complete.
> func (s *cloudStorageSink) waitAsyncFlush() error {
> ```

is this really what you want when you call this? Don't you just want the currently in-flight files to be flushed? If it's the same thing because there's no concurrency, can you add a comment about that?
___
*[`pkg/ccl/changefeedccl/sink_cloudstorage.go` line 679 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/90011#-NEfGShl6aPS59AMkhUq:-NEfGShl6aPS59AMkhUr:bten33x) ([raw file](https://github.com/cockroachdb/cockroach/blob/05b69a4788cd0a61747323befc7d4985eaea9116/pkg/ccl/changefeedccl/sink_cloudstorage.go#L679)):*
> ```Go
> 	if len(s.flushQueue.q) == 1 {
> 		// Start a new go routine if the flush queue was empty.
> 		s.flushQueue.numGoRoutines++
> ```

This numGoRoutines makes the reasoning complex. I'm having a hard time convincing myself of correctness. Maybe it'd be better if instead you launched a goroutine for each file you wanted to flush and then broadcasted whenever the head of the queue is flushed and have the goroutine associated with the file be the only goroutine to flush the head of the queue file. Then it'd be easy to reason about. One goroutine per file, created with that file. Right now, this code which passes the responsibility to some maybe previously created goroutine is complex for no good reason. 
___
*[`pkg/ccl/changefeedccl/sink_cloudstorage.go` line 695 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/90011#-NEfGq2QCAP0qwSzAvuK:-NEfGq2QCAP0qwSzAvuL:b-ctqvmc) ([raw file](https://github.com/cockroachdb/cockroach/blob/05b69a4788cd0a61747323befc7d4985eaea9116/pkg/ccl/changefeedccl/sink_cloudstorage.go#L695)):*
> ```Go
> 		s.flushQueue.Lock()
> 		defer s.flushQueue.Unlock()
> 		defer s.flushQueue.flushC.Signal()
> ```

this seems wrong, what if you signal a waiter instead of a flusher?
___
*[`pkg/ccl/changefeedccl/sink_cloudstorage.go` line 702 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/90011#-NEfGcMv4JASmeRfUZL_:-NEfGcMv4JASmeRfUZLa:b-5gcvhd) ([raw file](https://github.com/cockroachdb/cockroach/blob/05b69a4788cd0a61747323befc7d4985eaea9116/pkg/ccl/changefeedccl/sink_cloudstorage.go#L702)):*
> ```Go
> 		s.flushQueue.Lock()
> 		defer s.flushQueue.Unlock()
> 		defer s.flushQueue.flushC.Signal()
> ```

why signal and why every time you pop? Signal goes to just one waiter. Maybe broadcast, but like, why not broadcast only when the queue is empty given that's what waiters want.

**Comment by jayshrivastava** [comment]
Looks very good to me :) I'm going to let Andrew give the final ✅

**Review by ajwerner — COMMENTED** [review]
I like this much better

**Review by ajwerner — APPROVED** [review]
Terminology nit: both writing the file and waiting for the in flight files to be written are called flush. It's sort of confusing.

File: pkg/ccl/changefeedccl/sink_cloudstorage.go [hunk 6]
```diff
@@ -325,6 +332,8 @@ var partitionDateFormats = map[string]string{
 }
 var defaultPartitionFormat = partitionDateFormats["daily"]
 
+const flushQueueDepth = 256
```
[the remark this answers is not in the document]
Comment (miretskiy) [reply pkg/ccl/changefeedccl/sink_cloudstorage.go:335]: ack; done.

File: pkg/ccl/changefeedccl/sink_cloudstorage.go [hunk 7]
```diff
@@ -695,7 +766,10 @@ func (f *cloudStorageSinkFile) flushToStorage(
 // Close implements the Sink interface.
 func (s *cloudStorageSink) Close() error {
 	s.files = nil
-	return errors.CombineErrors(s.waitAsyncFlush(), s.es.Close())
+	err := s.waitAsyncFlush(context.Background())
+	close(s.asyncFlushCh) // Signal flusher to exit.
```
[the remark this answers is not in the document]
Comment (miretskiy) [reply pkg/ccl/changefeedccl/sink_cloudstorage.go:770]: done.
