### PR TITLE
sql: change messaging for non-partitioned indexes on partitioned table

### LINKED ISSUE #43359: sql: improve sql safe updates message for preventing non-partitioned indexes
A customer recently had trouble understanding the SQL safe updates warning preventing the use of a non-partitioned secondary index. They were concerned that their actions were wrong. 

Let's iterate on this message.

### PR DESCRIPTION
**Pull request by otan**
Resolves https://github.com/cockroachdb/cockroach/issues/43359

Release justification: low risk, high benefit changes to existing
functionality

Release note (sql change): Previously, when creating a non-partitioned
index on a partitioned table with "sql_safe_updates = true", we would
error out. In the new change, we instead will send a NOTICE stating that
creating a non-partitioned index on a partitioned table stating it is
not performant.

### CODE REVIEW

**Comment by rohany** [comment]
code lgtm, but I'm worried that our current way of testing notices is not scalable/modular. Is there a way to see notice outputs without an expect test?

**Comment by otan** [comment]
i noticed that and i have an idea, i will apply in a future PR!
(i think we can also do the same thing for telemetry!)

**Comment by otan** [comment]
ok, i've made it dependent on https://github.com/cockroachdb/cockroach/pull/46228

File: pkg/sql/create_table.go [hunk 1]
```diff
@@ -176,13 +176,16 @@ func (n *createTableNode) startExec(params runParams) error {
...
 	// which is undesirable in most cases.
-	if params.SessionData().SafeUpdates && n.n.PartitionBy != nil {
+	if n.n.PartitionBy != nil {
 		for _, def := range n.n.Defs {
 			if d, ok := def.(*tree.IndexTableDef); ok {
 				if d.PartitionBy == nil {
-					return pgerror.DangerousStatementf("non-partitioned index on partitioned table")
+					params.p.SendClientNotice(
+						params.ctx,
+						pgerror.Noticef("creating non-partitioned index on partitioned table may not be performant"),
```
Comment (knz) [inline pkg/sql/create_table.go]: please provide a hint too (`errors.WithHint`) as to what should be done instead.

(Preferably with a doc link - although I think we need a separate issue+PR to introduce a standard way to populate doc links in error messages. We don't have that infrastructure right now. The nearest we have is the doc links in the sql.y.)

**Review by knz — APPROVED** [review]

**Comment by otan** [comment]
bors r=knz

**Comment by otan** [comment]
hmm, rate limit by GH on CI.... trying again....

bors r=knz

**Comment by otan** [comment]
bors r=knz

**Comment by otan** [comment]
bors r=knz

flake
