### PR TITLE
ts: fix multi-tenant KV metric double-counting in queries

### LINKED ISSUE #160479: tsdb: double counting of kv metrics
[Internal Discussion](https://cockroachlabs.slack.com/archives/C063CP41TG9/p1766504408309579)

## Summary

In UA (Unified Architecture) deployments, storage metrics like `livebytes` display approximately double the actual value in the DB Console. For example, a cluster with 13TB of data shows 26TB.

## Root Cause

The metrics recorder stores both the aggregate value (source="1") and per-tenant children (source="1-1", "1-2") for `TenantsStorageMetricsSet` metrics. When the DB Console queries without a specific TenantID, the query fetches both the aggregate and scans for per-tenant children, summing everything together.

Since these metrics use `AggGauge` where the aggregate already equals the sum of children, this results in double-counting:
  - Aggregate (source="1"): 13TB (sum of all tenants)
  - Children (source="1-1", "1-2"): 13TB total
  - Query result: 26TB

## Affected Metrics

Only the 19 metrics in `TenantsStorageMetricsSet` are affected:
  - livebytes, keybytes, valbytes, intentbytes, livecount, keycount, valcount, intentcount, lockbytes, lockcount, rangecount, leasecount, rangekeybytes, rangekeycount, rangevalbytes, rangevalcount, locklivecount, locklivebytes, pebble_blob_file_used

Jira issue: CRDB-58386

### PR DESCRIPTION
**Pull request by angles-n-daemons**
Previously, the timeseries query logic had two issues causing incorrect values in multi-tenant deployments:

1. TenantServer.Query() only filtered app-level metrics (those in tenantRegistry) by tenant ID, but store-level tenant metrics like livebytes were not filtered. This meant app tenants viewing their own data would see aggregate values instead of their tenant-specific data.

2. When no tenant filter was set (the "All" view), readFromDatabase() and readAllSourcesFromDatabase() would return both aggregate sources AND tenant-prefixed sources. Since the aggregate already contains the sum of all tenants' data, adding the tenant-prefixed sources resulted in double-counting.

This commit fixes both issues:
- TenantServer.Query() now also filters store-level tenant metrics (livebytes, keybytes, valbytes, etc.) by tenant ID
- readFromDatabase() no longer scans for tenant-prefixed sources when no tenant filter is set
- readAllSourcesFromDatabase() now filters out tenant-prefixed sources when no tenant filter is set

Fixes: #160479

Release note: None

Epic: None

### CODE REVIEW

File: pkg/ts/query.go
Comment (jasonlmfong) [inline pkg/ts/query.go]: this block can be combined with the one below which filters out tenantIDs already

File: pkg/ts/query.go [hunk 1]
```diff
@@ -851,14 +851,10 @@ func (db *DB) readFromDatabase(
...
+				// When no tenant filter is set, only retrieve the aggregate source.
+				// The aggregate already contains the sum of all tenants' data.
 				key := MakeDataKey(seriesName, source, diskResolution, currentTimestamp)
 				b.Get(key)
-				// Then we scan all keys that match the tenant source prefix since the system tenant
-				// aggregates sources across all tenants.
-				startKey := MakeDataKey(seriesName, tsutil.MakeTenantSourcePrefix(source), diskResolution, currentTimestamp)
-				endKey := MakeDataKey(seriesName, tsutil.MakeTenantSourcePrefix(source), diskResolution, currentTimestamp).PrefixEnd()
-				b.Scan(startKey, endKey)
 			}
```
Comment (jasonlmfong) [inline pkg/ts/query.go]: the if and the else can be combined now

File: pkg/ts/server.go [hunk 2]
```diff
@@ -121,15 +122,36 @@ func (t *TenantServer) Query(
...
 	// Currently, secondary tenants are only able to view their own metrics.
 	for i, q := range req.Queries {
-		// Tenant-scoped metrics get marked with the tenantID, otherwise we
-		// leave the request as-is for system-level metrics.
-		if t.tenantRegistry.Contains(q.Name) {
+		// Tenant-scoped metrics get marked with the tenantID. This includes both
+		// app-level metrics (in tenantRegistry) and store-level tenant metrics
+		// (tracked per-tenant in kvbase.TenantsStorageMetricsSet).
+		metricName := strings.TrimPrefix(q.Name, "cr.store.")
+		metricName = strings.TrimPrefix(metricName, "cr.node.")
```
Comment (jasonlmfong) [inline pkg/ts/server.go]: if we're only concerned about store metrics then we don't really need to trim cr.node prefix?

File: pkg/ts/server_test.go [hunk 3]
```diff
@@ -413,11 +414,11 @@ func TestServerQueryTenant(t *testing.T) {
 				Datapoints: []tspb.TimeSeriesDatapoint{
 					{
 						TimestampNanos: 400 * 1e9,
-						Value:          101.0,
+						Value:          100.0,
 					},
 					{
 						TimestampNanos: 500 * 1e9,
-						Value:          202.0,
+						Value:          200.0,
```
Comment (jasonlmfong) [inline pkg/ts/server_test.go]: these changes make sense, i think it's a bit unfortunate the tests don't provide a proper aggregation for me to get the full picture from just looking at the test cases though

e.g. recording 1-1, 1-2 and seeing this return the sum.

but not a big deal

**Review by jasonlmfong — COMMENTED** [review]
overall makes sense logically, some coding nits

File: pkg/ts/server.go (hunk 2 above)
Comment (angles-n-daemons) [reply pkg/ts/server.go]: this is a good point, I'll remove this.

File: pkg/ts/server_test.go (hunk 3 above)
Comment (angles-n-daemons) [reply pkg/ts/server_test.go]: Makes sense to me, I've added another test to further confirm the behavior we want.

File: pkg/ts/query.go
Comment (angles-n-daemons) [reply pkg/ts/query.go]: Ah good idea, adding

File: pkg/ts/query.go (hunk 1 above)
Comment (angles-n-daemons) [reply pkg/ts/query.go]: got it, changing this now

File: pkg/ts/server.go [hunk 4]
```diff
@@ -121,15 +122,35 @@ func (t *TenantServer) Query(
...
+		if t.tenantRegistry.Contains(q.Name) || isStoreTenantMetric(metricName) {
 			req.Queries[i].TenantID = t.tenantID
 		}
 	}
 	return t.tenantConnect.Query(ctx, req)
 }
 
+// isStoreTenantMetric returns true if the metric is a store-level metric
+// that has per-tenant data. These metrics are tracked per-tenant in
+// kvbase.TenantsStorageMetricsSet.
```
Comment (jasonlmfong) [inline pkg/ts/server.go]: i think we have this comment a little too many times lol

File: pkg/ts/server.go [hunk 5]
```diff
@@ -121,15 +122,35 @@ func (t *TenantServer) Query(
...
+	// We maintain a hardcoded list here to avoid import cycles with kvbase.
+	storeTenantMetrics := map[string]struct{}{
+		"livebytes": {}, "sysbytes": {}, "keybytes": {}, "valbytes": {},
+		"rangekeybytes": {}, "rangevalbytes": {}, "totalbytes": {},
+		"intentbytes": {}, "lockbytes": {}, "livecount": {}, "keycount": {},
+		"valcount": {}, "rangekeycount": {}, "rangevalcount": {},
+		"intentcount": {}, "lockcount": {}, "lockage": {}, "gcbytesage": {},
+		"syscount": {}, "abortspanbytes": {},
+	}
+	_, ok := storeTenantMetrics[name]
```
Comment (jasonlmfong) [inline pkg/ts/server.go]: any specific reason why we create this map in the function instead of using a package level map?

File: pkg/ts/server.go [hunk 6]
```diff
@@ -121,15 +122,35 @@ func (t *TenantServer) Query(
...
+	// These metrics are tracked per-tenant in kvbase.TenantsStorageMetricsSet.
+	// We maintain a hardcoded list here to avoid import cycles with kvbase.
+	storeTenantMetrics := map[string]struct{}{
+		"livebytes": {}, "sysbytes": {}, "keybytes": {}, "valbytes": {},
+		"rangekeybytes": {}, "rangevalbytes": {}, "totalbytes": {},
+		"intentbytes": {}, "lockbytes": {}, "livecount": {}, "keycount": {},
+		"valcount": {}, "rangekeycount": {}, "rangevalcount": {},
+		"intentcount": {}, "lockcount": {}, "lockage": {}, "gcbytesage": {},
+		"syscount": {}, "abortspanbytes": {},
+	}
```
Comment (jasonlmfong) [inline pkg/ts/server.go]: also do we want to add a comment to the kvbase file so if that one is ever updated, we should update this map too
slightly reduce the risk of drift

**Review by jasonlmfong — APPROVED** [review]
looks good, some nits left

File: pkg/ts/server.go (hunk 4 above)
Comment (angles-n-daemons) [reply pkg/ts/server.go]: Yeah, claude went a little comment-happy, let me see if I can dial it back.

File: pkg/ts/server.go (hunk 6 above)
Comment (angles-n-daemons) [reply pkg/ts/server.go]: Ah that's a good idea, adding one now.

File: pkg/ts/server.go (hunk 5 above)
Comment (angles-n-daemons) [reply pkg/ts/server.go]: No particular reason, I'll change that now.

**Review by jasonlmfong — APPROVED** [review]
lgtm!
