### PR TITLE
backupccl: remap IDs without conflicts

### LINKED ISSUE #88008: backupccl: remapping system tables with certain ID patterns can lead to uniqueness violation
https://github.com/cockroachdb/cockroach/pull/87918 found a bug when running the `multi_region_privileges` logictest where a restore fails with `restoring cluster: pq: remapping crdb_temp_system.zones: remap-crdb_temp_system.zones: duplicate key value violates unique constraint "primary"` because the system.zones table has the following IDs prior to remapping:

```
ID is 0
ID is 1
ID is 16
ID is 17
ID is 22
ID is 25
ID is 27
ID is 45
ID is 104
ID is 109
ID is 110
ID is 111
ID is 142
ID is 144
ID is 147
ID is 148
```

and the remap query is:

```
UPDATE crdb_temp_system.zones SET id = CASE
WHEN id = 4 THEN 113
WHEN id = 5 THEN 114
WHEN id = 6 THEN 115
WHEN id = 14 THEN 116
WHEN id = 21 THEN 117
WHEN id = 23 THEN 118
WHEN id = 24 THEN 119
WHEN id = 33 THEN 120
WHEN id = 37 THEN 121
WHEN id = 44 THEN 122
WHEN id = 48 THEN 123
WHEN id = 50 THEN 124
WHEN id = 51 THEN 125
WHEN id = 52 THEN 126
WHEN id = 105 THEN 105
WHEN id = 106 THEN 106
WHEN id = 107 THEN 107
WHEN id = 108 THEN 108
WHEN id = 109 THEN 109
WHEN id = 110 THEN 110
WHEN id = 111 THEN 111
WHEN id = 126 THEN 127
WHEN id = 127 THEN 128
WHEN id = 128 THEN 129
WHEN id = 129 THEN 130
WHEN id = 130 THEN 131
WHEN id = 131 THEN 132
WHEN id = 132 THEN 133
WHEN id = 133 THEN 134
WHEN id = 134 THEN 135
WHEN id = 135 THEN 136
WHEN id = 136 THEN 137
WHEN id = 137 THEN 138
WHEN id = 138 THEN 139
WHEN id = 139 THEN 140
WHEN id = 140 THEN 141
WHEN id = 141 THEN 142
WHEN id = 142 THEN 143
WHEN id = 143 THEN 144
WHEN id = 144 THEN 145
WHEN id = 145 THEN 146
WHEN id = 146 THEN 147
WHEN id = 147 THEN 148
WHEN id = 148 THEN 112
WHEN id = 149 THEN 149
WHEN id = 150 THEN 150
WHEN id = 151 THEN 151
```

ID 147 will be remapped to 148 which is a uniqueness violation because 148 has not yet been remapped.

Jira issue: CRDB-19643

### PR DESCRIPTION
**Pull request by dt**
Previously when remapping IDs in system tables during restore, we would set the old ID ot the new ID however this could fail if there was an existing ID at the new ID, even though that row was also going to be subsequently remapped in the same statement, as the uniqueness check would fail before the statement had a chance to move that row out of the way.

To avoid this, we now remap all old IDs to new IDs that are offset, then de-offset all the IDs at once, after shuffling them all around. We offset by a fixed 2^31, rather than querying the maximum in-use ID. This has the potential to be not enough if a cluster had more than 2 billion descriptors, however in that case the remapped descriptors would overflow the OID column type anyway. Thus we may as well just use 2B rather than incur extra complexity picking a dynamic offset.

Fixes #88008.

Release note: none (this is new 22.2 functionality).

### CODE REVIEW

File: pkg/ccl/backupccl/system_schema.go [hunk 1]
```diff
@@ -563,16 +563,50 @@ func rekeySystemTable(
 		sort.Sort(toRekey)
 
 		executor := execCtx.InternalExecutor
-		q := strings.Builder{}
-		fmt.Fprintf(&q, "UPDATE %s SET %s = CASE\n", tempTableName, colName)
 
+		// We will update every ID in the table from an old value to a new new value
```
Comment (adityamaru) [inline pkg/ccl/backupccl/system_schema.go:567]: nit: to a new new value

File: pkg/ccl/backupccl/system_schema.go [hunk 2]
```diff
@@ -563,16 +563,50 @@ func rekeySystemTable(
...
+		// Some of the tables use oid columns to store desc IDs rather than ints; in
+		// these tables we will need to cast to int to do the addition/subtraction
+		// of the offset, and then cast back to the desired type determined here.
+		typ := "int"
+		switch tempTableName {
+		case "crdb_temp_system.database_role_settings":
+			typ = "oid"
+		}
+
+		// We'll build one big UPDATE that moves all the IDs to their new values.
```
Comment (adityamaru) [inline pkg/ccl/backupccl/system_schema.go:589]: nit: can we also add a line that IDs that are not rekeyed are also moved to a new ID = old ID + offset

**Review by adityamaru — APPROVED** [review]
LGTM, feel free to ignore nits to avoid CI cycle. Can be picked up in a future PR.

**Comment by dt** [comment]
TFTR!

bors r+
