### PR TITLE
release-22.1:  sql: fix telemetry panic for COPY

### LINKED ISSUE #88229: sql: panic in query sampling for COPY
This issue was autofiled by Sentry. It represents a crash or reported error on a live cluster with telemetry enabled.

Sentry link: https://sentry.io/organizations/cockroach-labs/issues/3605902199/?referrer=webhooks_plugin

Panic message:

>conn_executor.go:761: runtime error: invalid memory address or nil pointer dereference
(1) attached stack trace
  -- stack trace:
  | github.com/cockroachdb/cockroach/pkg/sql.(*Server).ServeConn.func1
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:761
  | [...repeated from below...]
Wraps: (2) attached stack trace
  -- stack trace:
  | github.com/cockroachdb/cockroach/pkg/sql.(*Server).ServeConn.func1
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:761
  | runtime.gopanic
  | 	GOROOT/src/runtime/panic.go:1038
  | runtime.panicmem
  | 	GOROOT/src/runtime/panic.go:221
  | runtime.sigpanic
  | 	GOROOT/src/runtime/signal_unix.go:735
  | github.com/cockroachdb/cockroach/pkg/sql.(*planner).maybeLogStatementInternal
  | 	github.com/cockroachdb/cockroach/pkg/sql/exec_log.go:401
  | github.com/cockroachdb/cockroach/pkg/sql.(*planner).maybeLogStatement
  | 	github.com/cockroachdb/cockroach/pkg/sql/exec_log.go:165
  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execCopyIn.func5
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:2433
  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execCopyIn
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:2479
  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execCmd
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:2038
  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).run
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:1817
  | github.com/cockroachdb/cockroach/pkg/sql.(*Server).ServeConn
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:763
  | github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*conn).processCommandsAsync.func1
  | 	github.com/cockroachdb/cockroach/pkg/sql/pgwire/conn.go:728
  | runtime.goexit
  | 	GOROOT/src/runtime/asm_amd64.s:1581
Wraps: (3) runtime error: invalid memory address or nil pointer dereference
Error types: (1) *withstack.withStack (2) *withstack.withStack (3) runtime.errorString
-- report composition:
runtime.errorString
conn_executor.go:761: *withstack.withStack (top exception)
conn_executor.go:761: *withstack.withStack (1)
(check the extra data payloads)

<details>
<summary>Stacktrace (expand for inline code snippets):</summary>

https://github.com/cockroachdb/cockroach/blob/a346e7a64510df370cc945f2c771f0702cf1129d/pkg/sql/conn_executor.go#L760-L762 in pkg/sql.(*Server).ServeConn.func1
GOROOT/src/runtime/panic.go#L1037-L1039 in runtime.gopanic
GOROOT/src/runtime/panic.go#L220-L222 in runtime.panicmem
GOROOT/src/runtime/signal_unix.go#L734-L736 in runtime.sigpanic
https://github.com/cockroachdb/cockroach/blob/a346e7a64510df370cc945f2c771f0702cf1129d/pkg/sql/exec_log.go#L400-L402 in pkg/sql.(*planner).maybeLogStatementInternal
https://github.com/cockroachdb/cockroach/blob/a346e7a64510df370cc945f2c771f0702cf1129d/pkg/sql/exec_log.go#L164-L166 in pkg/sql.(*planner).maybeLogStatement
https://github.com/cockroachdb/cockroach/blob/a346e7a64510df370cc945f2c771f0702cf1129d/pkg/sql/conn_executor.go#L2432-L2434 in pkg/sql.(*connExecutor).execCopyIn.func5
https://github.com/cockroachdb/cockroach/blob/a346e7a64510df370cc945f2c771f0702cf1129d/pkg/sql/conn_executor.go#L2478-L2480 in pkg/sql.(*connExecutor).execCopyIn
https://github.com/cockroachdb/cockroach/blob/a346e7a64510df370cc945f2c771f0702cf1129d/pkg/sql/conn_executor.go#L2037-L2039 in pkg/sql.(*connExecutor).execCmd
https://github.com/cockroachdb/cockroach/blob/a346e7a64510df370cc945f2c771f0702cf1129d/pkg/sql/conn_executor.go#L1816-L1818 in pkg/sql.(*connExecutor).run
https://github.com/cockroachdb/cockroach/blob/a346e7a64510df370cc945f2c771f0702cf1129d/pkg/sql/conn_executor.go#L762-L764 in pkg/sql.(*Server).ServeConn
https://github.com/cockroachdb/cockroach/blob/a346e7a64510df370cc945f2c771f0702cf1129d/pkg/sql/pgwire/conn.go#L727-L729 in pkg/sql/pgwire.(*conn).processCommandsAsync.func1
GOROOT/src/runtime/asm_amd64.s#L1580-L1582 in runtime.goexit
</details>

```
pkg/sql/conn_executor.go in pkg/sql.(*Server).ServeConn.func1 at line 761
GOROOT/src/runtime/panic.go in runtime.gopanic at line 1038
GOROOT/src/runtime/panic.go in runtime.panicmem at line 221
GOROOT/src/runtime/signal_unix.go in runtime.sigpanic at line 735
pkg/sql/exec_log.go in pkg/sql.(*planner).maybeLogStatementInternal at line 401
pkg/sql/exec_log.go in pkg/sql.(*planner).maybeLogStatement at line 165
pkg/sql/conn_executor.go in pkg/sql.(*connExecutor).execCopyIn.func5 at line 2433
pkg/sql/conn_executor.go in pkg/sql.(*connExecutor).execCopyIn at line 2479
pkg/sql/conn_executor.go in pkg/sql.(*connExecutor).execCmd at line 2038
pkg/sql/conn_executor.go in pkg/sql.(*connExecutor).run at line 1817
pkg/sql/conn_executor.go in pkg/sql.(*Server).ServeConn at line 763
pkg/sql/pgwire/conn.go in pkg/sql/pgwire.(*conn).processCommandsAsync.func1 at line 728
GOROOT/src/runtime/asm_amd64.s in runtime.goexit at line 1581
```

| Tag | Value |
|---|---|
| Cockroach Release | `v22.1.7` |
| Cockroach SHA: | a346e7a64510df370cc945f2c771f0702cf1129d |
| Platform | linux amd64 |
| Distribution | CCL |
| Environment | v22.1.7 |
| Command | server |
| Go Version | ``|
| # of CPUs ||
| # of Goroutines ||

Jira issue: CRDB-19738

gz#14032

### PR DESCRIPTION
**Pull request by otan**
Backport 1/1 commits from #88322.

/cc @cockroachdb/release

---

Resolves #88229

Release note (bug fix): Fixed a bug where if telemetry is enabled, COPY can sometimes cause the server to crash.

Release justification: fixes a critical panic

### CODE REVIEW

File: pkg/sql/copy_in_test.go [hunk 1]
```diff
@@ -34,6 +34,7 @@ import (
 	"github.com/cockroachdb/cockroach/pkg/util/log"
 	"github.com/cockroachdb/cockroach/pkg/util/timeofday"
 	"github.com/cockroachdb/cockroach/pkg/util/timetz"
+	"github.com/cockroachdb/cockroach/vendor/github.com/jackc/pgx/v4"
```
Comment (cucaroach) [inline pkg/sql/copy_in_test.go:37]: What's with this import?

Comment (otan) [reply pkg/sql/copy_in_test.go:37]: My ide did that. I'll fix her up

**Review by rafiss — APPROVED** [review]
