### PR TITLE
backup: reset retry counter for download job when progress is detected

### LINKED ISSUE #149893: backup: download job should reset retries on progress
#148821 introduced a retry loop to the download phase of online restore, but the retry loop fails after 5 retries, regardless of progress made. This is a bit too aggressive of a policy — if we detect that progress has been made during the download phase, we should reset the retry loop like we do for the link phase/classic restore.

Epic: CRDB-51394

### PR DESCRIPTION
**Pull request by kev-cao**
In #1448821, we added a retry loop to the download phase of online restore, but the retry policy allows at most 5 retries. In the event of download progress, we want to be more lenient with the retry policy, so this commit teaches the download phase to reset the retry counter if progress is detected.

Epic: CRDB-51394

Fixes: #149893

### CODE REVIEW

File: pkg/backup/restore_online.go [hunk 1]
```diff
@@ -818,6 +821,11 @@ func (r *restoreResumer) doDownloadFilesWithRetry(
 			return nil
 		}
 		log.Warningf(ctx, "failed attempt #%d to download files: %v", rt.CurrentAttempt(), err)
```
Comment (dt) [inline pkg/backup/restore_online.go]: this attempt number is gonna be bogus once we're resetting so I might remove it from the log message since it could be confusing otherwise.

**Review by dt — APPROVED** [review]

**Comment by kev-cao** [comment]
TFTR!

bors r=dt
