### PR TITLE
catalog/lease: reduce lock contention on descVersionState

### LINKED ISSUE #111094: lease: regression in BenchmarkLeaseAcquireByNameCached from 23.1
Comparing f13c021b and 2a23692a61e72a
```
name                         old time/op    new time/op    delta
LeaseAcquireByNameCached-24     548ns ± 3%     696ns ± 9%  +26.98%  (p=0.000 n=10+10)

name                         old alloc/op   new alloc/op   delta
LeaseAcquireByNameCached-24     8.00B ± 0%     6.70B ±25%  -16.25%  (p=0.000 n=9+10)

name                         old allocs/op  new allocs/op  delta
LeaseAcquireByNameCached-24      0.00           0.00          ~     (all equal)
```
Interestingly, an automated [run](https://docs.google.com/spreadsheets/d/1bMd-A0Tf9ms1aTFm8hFn19n-VjFDudF4oYouYdHfozM/edit#gid=6) got 1500% in alloc/op increase (although the next automated [run](https://docs.google.com/spreadsheets/d/1MefIZmbARZaZbUiYvyy5jyIrD74J81LDVriqsH1ubsQ/edit#gid=6) was in line with what I reproduced manually on gceworker).

Jira issue: CRDB-31758

### PR DESCRIPTION
**Pull request by fqazi**
Recently, a regression was noticed on master related to AcquireByName being slower between builds. Using a profiler, this was tracked down to contention on descriptorVersionState's mutex.  To address this, this patch avoids acquiring this lock twice in the hot path, which resolves the regression.

After:   BenchmarkLeaseAcquireByNameCached-24    	 2378610	       451.9 ns/op
Before:  BenchmarkLeaseAcquireByNameCached-24    	 1493899	       727.9 ns/op
f13c021: BenchmarkLeaseAcquireByNameCached-24    	 2129446	       568.1 ns/op

Fixes: #111094

Release note: None

### CODE REVIEW

**Review by annrpom — COMMENTED** [review]
> Reviewed 1 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/111397)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @fqazi)

___
*[`pkg/sql/catalog/lease/name_cache.go` line 38 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/111397#-NfOO5hd9Z6NisHbg825:-NfOO5hd9Z6NisHbg826:btt51pe) ([raw file](https://github.com/cockroachdb/cockroach/blob/b0a2175a79a484d2f0d6f81258cc5135639aef0a/pkg/sql/catalog/lease/name_cache.go#L38)):*
> ```Go
> 
> // Resolves a (qualified) name to the descriptor's ID.
> // Returns a valid descriptorVersionState for descriptor with that name,
> ```

small nit: could you update this comment to reflect your change

**Review by fqazi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/111397)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @annrpom)

___
*[`pkg/sql/catalog/lease/name_cache.go` line 38 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/111397#-NfOO5hd9Z6NisHbg825:-NfO_tIA6Jbm8X-zFqhQ:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/b0a2175a79a484d2f0d6f81258cc5135639aef0a/pkg/sql/catalog/lease/name_cache.go#L38)):*
<details><summary><i>Previously, annrpom (annie pompa) wrote…</i></summary><blockquote>

small nit: could you update this comment to reflect your change
</blockquote></details>

Done.

File: pkg/sql/catalog/lease/name_cache.go [hunk 1]
```diff
@@ -47,14 +48,15 @@ func (c *nameCache) get(
 	parentSchemaID descpb.ID,
 	name string,
 	timestamp hlc.Timestamp,
-) *descriptorVersionState {
+) (desc *descriptorVersionState, expiration hlc.Timestamp) {
 	c.mu.RLock()
```
Comment (rafiss) [inline pkg/sql/catalog/lease/name_cache.go:52]: as described in As described in https://github.com/cockroachdb/cockroach/issues/109443#issuecomment-1694796474, `RWMutex` performs badly under high concurrency. Should we just change to a normal mutex?

**Review by rafiss — CHANGES_REQUESTED** [review]

File: pkg/sql/catalog/lease/name_cache.go (hunk 1 above)
Comment (fqazi) [reply pkg/sql/catalog/lease/name_cache.go:52]: Let me try this out and see how it behaves without this change.

Comment (fqazi) [reply pkg/sql/catalog/lease/name_cache.go:52]: No, it's similar to the old one: 
BenchmarkLeaseAcquireByNameCached-24    	 1624814	       734.4 ns/op

Also, there are no writes to the name cache in this scenario, so it should hit the fast path on the RWMutex (outside of system table activity).

**Review by rafiss — APPROVED** [review]
thanks for checking!

**Comment by fqazi** [comment]
@rafiss TFTR!

bors r+
