### PR TITLE
storage: fix overstimation of timeseries range stats on merge

### LINKED ISSUE #32576: kv: timeseries range stats are wildly over estimated
While running `restore2TB` as a part #32538, I was looking for any range merges on the system. About an hour into the run I saw:

`I181123 17:29:34.543462 257031 storage/merge_queue.go:271  [n10,merge,s10,r5/4:/System/tsd{-/cr.sto…}] merging ranges: /System/tsd{-/cr.store.valcount/9/10s/2018-11-23T17:00:00Z} + /System/ts{d/cr.store.valcount/9/10s/2018-11-23T17:00:00Z-e} -> /System/ts{d-e}`

Shortly before that the logs contain:

`I181123 17:29:34.368672 256982 storage/replica_command.go:306  [n10,split,s10,r5/4:/System/ts{d-e}] initiating a split of this range at key /System/tsd/cr.store.valcount/9/10s/2018-11-23T17:00:00Z [r16838]`

It looks like we merged a timeseries range a few hundred milliseconds after it was split. Not that merge queue log message is new instrumentation I added. It is performed after all of the checks for not merging.

I'm not sure what the size of `r5` was before the split or the merge, but right now it is sitting at 46.2 MiB.

### PR DESCRIPTION
**Pull request by TheSamHuang**
Previously, we overestimated MVCC stats on each merge operation because we were adding mvccVersionTimestampSize each time. Each merge is into the same key, so we are not actually incurring the metadata over each time. To address this, adding of mvccVersionTimestampSize each time was removed and a test case was added to verify correct timeseries data.

Release note: None.

### CODE REVIEW

**Comment by TheSamHuang** [comment]
New test case run result: 
```
=== RUN   TestTimeSeriesMVCCStats
=== RUN   TestTimeSeriesMVCCStats/rocksdb
=== RUN   TestTimeSeriesMVCCStats/pebble
--- PASS: TestTimeSeriesMVCCStats (0.01s)
    --- PASS: TestTimeSeriesMVCCStats/rocksdb (0.00s)
    --- PASS: TestTimeSeriesMVCCStats/pebble (0.00s)
PASS
ok  	github.com/cockroachdb/cockroach/pkg/storage	3.444s
```

File: pkg/storage/mvcc.go [hunk 1]
```diff
@@ -2171,8 +2167,11 @@ func MVCCMerge(
 	data, err := buf.marshalMeta(meta)
 	if err == nil {
 		if err = rw.Merge(metaKey, data); err == nil && ms != nil {
+			// We add only the size of value.RawBytes and do not add the
+			// mvccVersionTimestampSize as we do not incur the metadata overhead
+			// each time because each merge is into the same key.
```
Comment (TheSamHuang) [inline pkg/storage/mvcc.go:2172]: Would it make sense to add this comment here instead of at updateStatsOnMerge since this is where we are passing in `value.RawBytes`? `updateStatsOnMerge` only increments the `valSize` that is passed in.

File: pkg/storage/mvcc_test.go [hunk 2]
```diff
@@ -5248,6 +5248,58 @@ func TestResolveIntentWithLowerEpoch(t *testing.T) {
...
+
+			var secondSysBytes = ms.SysBytes
+			var secondLiveBytes = ms.LiveBytes
+			var secondValBytes = ms.ValBytes
+			if err := MVCCMerge(ctx, engine, &ms, testKey1, hlc.Timestamp{Logical: 1}, tsvalue1); err != nil {
+				t.Fatal(err)
+			}
+
+			// Ensure timeseries metrics increases as expected
+			if isSysLocal(testKey1) {
```
Comment (TheSamHuang) [inline pkg/storage/mvcc_test.go:5281]: Since `testKey1` is not system-local, this may not be necessary. I think this would only make sense if we run this test against multiple test keys instead of just the one currently, which would be ideal to cover both conditions. What do you think?

File: pkg/storage/mvcc_test.go [hunk 3]
```diff
@@ -5248,6 +5248,58 @@ func TestResolveIntentWithLowerEpoch(t *testing.T) {
 	}
 }
 
+// TestTimeSeriesMVCCStats ensures that merge operations
+// result in expected increase in timeseries data
```
Comment (irfansharif) [inline pkg/storage/mvcc_test.go:5252]: [nit] result in _an_ expected

File: pkg/storage/mvcc_test.go [hunk 4]
```diff
@@ -5248,6 +5248,58 @@ func TestResolveIntentWithLowerEpoch(t *testing.T) {
...
+
+	ctx := context.Background()
+	for _, engineImpl := range mvccEngineImpls {
+		t.Run(engineImpl.name, func(t *testing.T) {
+			engine := engineImpl.create()
+			defer engine.Close()
+			var ms = enginepb.MVCCStats{}
+
+			// Perform the same sequence of merges on the same key
+			// twice and record timeseries data
```
Comment (irfansharif) [inline pkg/storage/mvcc_test.go:5265]: [nit] here and throughout, according to our [style guide](https://cockroachlabs.atlassian.net/wiki/spaces/CRDB/pages/914260289/Code+commenting+guidelines#Engineering-standards-(checked-during-reviews)) we try and use periods at the end of sentences.

Comment (irfansharif) [inline pkg/storage/mvcc_test.go:5265]: [nit] Perform a sequence of merges on the same key and record the MVCC stats for it.

File: pkg/storage/mvcc_test.go [hunk 5]
```diff
@@ -5248,6 +5248,58 @@ func TestResolveIntentWithLowerEpoch(t *testing.T) {
...
+			var firstSysBytes = ms.SysBytes
+			var firstLiveBytes = ms.LiveBytes
+			var firstValBytes = ms.ValBytes
```
Comment (irfansharif) [inline pkg/storage/mvcc_test.go:5268]: The test as written is a bit misleading. MVCCMerge takes a pointer to this MVCCStats guy, updating it in place. So "first{Sys,Live,Val}Bytes" are actually the values before the first write (in this case it will always be 0, 0, 0. Instead of unpacking it each time, perhaps we could use something like the following instead?

```
ms := &enginepb.MVCCStats{}

// ...
initialMS := *ms // It'll still be zeros before the first write.

// MVCCMerge(..., ms, ...)
firstMS := *ms

// ...
```

And then comparing things like `firstMS.SysBytes` with `secondMS.SysBytes`?

File: pkg/storage/mvcc_test.go (hunk 2 above)
Comment (irfansharif) [reply pkg/storage/mvcc_test.go:5281]: I'd be fine with using a specific testSysKey for this this that's constructed to be a system key. I'd also be fine with using testKey1 as is and simply testing {Live,Val}Bytes, we can skip this conditional given it's always going to be false.

File: pkg/storage/mvcc.go [hunk 6]
```diff
@@ -265,12 +265,8 @@ func updateStatsForInline(
 }
 
 // updateStatsOnMerge updates metadata stats while merging inlined
-// values. Unfortunately, we're unable to keep accurate stats on merge
-// as the actual details of the merge play out asynchronously during
-// compaction. Instead, we undercount by adding only the size of the
-// value.Bytes byte slice (an estimated 12 bytes for timestamp,
-// included in valSize by caller). These errors are corrected during
-// splits and merges.
+// values. We only the size of the value.RawBytes byte slice (an
```
Comment (irfansharif) [inline pkg/storage/mvcc.go:268]: [nit] I think we're missing a word here? That aside, I think the part about being unable to keep accurate stats on merge due to async compaction still applies. The undercounting statement was incorrect previously, we were definitely overcounting before. But I think _now_ we're actually undercounting by just a tiny bit seeing as how we never add MVCCVersionTimestampSize (even for the very merge/write). We could say as much, we still expect these errors to be corrected during splits and merges.

File: pkg/storage/mvcc.go (hunk 1 above)
Comment (irfansharif) [reply pkg/storage/mvcc.go:2172]: I think this comment could be skipped entirely, instead fleshing out the comment up above. See discussion there.

File: pkg/storage/mvcc_test.go [hunk 7]
```diff
@@ -5248,6 +5248,58 @@ func TestResolveIntentWithLowerEpoch(t *testing.T) {
...
+			// Ensure timeseries metrics increases as expected
+			if isSysLocal(testKey1) {
+				var expectedSysBytes = firstSysBytes + int64(len(tsvalue1.RawBytes))
+
+				if secondSysBytes != expectedSysBytes {
+					t.Fatalf("second merged SysBytes value %v differed from expected SysBytes value %v", secondSysBytes, expectedSysBytes)
+				}
+			} else {
+				var expectedLiveBytes = firstLiveBytes + int64(len(tsvalue1.RawBytes))
+				var expectedValBytes = firstValBytes + int64(len(tsvalue1.RawBytes))
```
Comment (irfansharif) [inline pkg/storage/mvcc_test.go:5289]: I'd be curious to see if this failed previously. I expect it to given our constant addition each time.

**Review by irfansharif — COMMENTED** [review]
Nice work Sam, that was really fast! The actual code change is what we want, though I did leave a few minor nits around the test/comments themselves. I'll cc @itsbilal from storage for a second pair of eyes here seeing as how it's nominally under their domain.

File: pkg/storage/mvcc_test.go (hunk 5 above)
Comment (TheSamHuang) [reply pkg/storage/mvcc_test.go:5268]: Definitely. I was trying to move the variables declarations around to improve readability and overlooked this. Sorry about that!

Comment (TheSamHuang) [reply pkg/storage/mvcc_test.go]: Since you also suggested adding `initialMS`, are you also suggesting I should validate MVCCStats increases correctly for the first merge as well?

File: pkg/storage/mvcc_test.go (hunk 7 above)
Comment (TheSamHuang) [reply pkg/storage/mvcc_test.go]: I'll try running this new test with the previous code to confirm!

**Comment by TheSamHuang** [comment]
> Nice work Sam, that was really fast! The actual code change is what we want, though I did leave a few minor nits around the test/comments themselves. I'll cc @itsbilal from storage for a second pair of eyes here seeing as how it's nominally under their domain.

Thank you for the fast PR review! Sorry for the oversights on style/grammar, will definitely be cognizant of those areas in the future!

**Review by irfansharif — APPROVED** [review]
Heh, there's no need to apologize! This PR LGTM, but let's wait for @itsbilal to sanity check our claims. 

(Aside, pro-gamer move: if your git commit message includes "Fixes #32576" it'll auto-close the linked issue once merged.)

> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/54949#-:-MIQrZYB8_H22LzLNxWH:b-8fwu73)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @irfansharif and @TheSamHuang)

___
*[pkg/storage/mvcc.go, line 272 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/54949#-MIQpA3n9pdgNN7GIrTX:-MIQpA3n9pdgNN7GIrTY:b-kcvyby) ([raw file](https://github.com/cockroachdb/cockroach/blob/db9c393482e055c813042bcae3b5d887ebcdbb21/pkg/storage/mvcc.go#L272)):*
> ```Go
> // compaction. Instead, we undercount by adding only the size of the
> // value.Bytes byte slice (an estimated 12 bytes for timestamp,
> // included in valSize by caller). These errors are corrected during
> ```

Hm, the previous comment is pretty confusing, I'm not sure how we landed there.  The 12 bytes in the comment was referring to MVCCVersionTimestampSize, which is no longer applicable. How about something like the following instead:

```
// updateStatsOnMerge updates metadata stats while merging inlined
// values. Unfortunately, we're unable to keep accurate stats on merges as the
// actual details of the merge play out asynchronously during compaction. We
// actually undercount by only adding the size of the value.RawBytes byte slice
// (and eliding MVCCVersionTimestampSize, corresponding to the metadata overhead,
// even for the very "first" write). These errors are corrected during splits and
// merges.
```
___
*[pkg/storage/mvcc_test.go, line 5268 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/54949#-MIPVHx9wPG1NpnUBPeh-r1-5268:-MIQp3kS8I3kgo1-r6BM:b4l9mgp) ([raw file](https://github.com/cockroachdb/cockroach/blob/48aeebc3b0398cf3f29e8e94fb7ddbbe0e871c80/pkg/storage/mvcc_test.go#L5268)):*
<details><summary><i>Previously, TheSamHuang (Sam Huang) wrote…</i></summary><blockquote>

Since you suggested adding `initialMS`, are you also suggesting I should validate MVCCStats increases correctly for the first merge as well? 
</blockquote></details>

I don't think that's necessary, really what I was just trying to write a (somewhat contrived) test checking that we aren't over counting the metadata each time, like we were before. 

[nit] I see we're still doing `firstLiveBytes, firstValBytes`. If you try the suggestion above, which I also think is slightly more idiomatic, we'll be able to compare `firstMS.ValBytes` and `secondMS.ValBytes` instead of introducing four dedicated variables for it.

**Comment by TheSamHuang** [comment]
> [nit] I see we're still doing `firstLiveBytes, firstValBytes`. If you try the suggestion above, which I also think is slightly more idiomatic, we'll be able to compare `firstMS.ValBytes` and `secondMS.ValBytes` instead of introducing four dedicated variables for it.

Done! Though I didn't have to deference `ms` like in your example since it's not a pointer.

**Comment by TheSamHuang** [comment]
> Hm, the previous comment is pretty confusing, I'm not sure how we landed there. The 12 bytes in the comment was referring to MVCCVersionTimestampSize, which is no longer applicable. How about something like the following instead:

Updated the commit with the new message! Thanks for the suggestion!

**Review by itsbilal — APPROVED** [review]
:lgtm:

Thanks for correcting the overcounting!

> Reviewed 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/54949#-:-MIUj2nX-45BxBSceDEc:b-qjf1a8)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @irfansharif and @TheSamHuang)

___
*[pkg/storage/mvcc.go, line 268 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/54949#-MIPVHx9wPG1NpnUBPeg-r1-268:-MIUhL6-8I78drtky6b0:b36i2sn) ([raw file](https://github.com/cockroachdb/cockroach/blob/48aeebc3b0398cf3f29e8e94fb7ddbbe0e871c80/pkg/storage/mvcc.go#L268)):*
<details><summary><i>Previously, irfansharif (irfan sharif) wrote…</i></summary><blockquote>

[nit] I think we're missing a word here? That aside, I think the part about being unable to keep accurate stats on merge due to async compaction still applies. The undercounting statement was incorrect previously, we were definitely overcounting before. But I think _now_ we're actually undercounting by just a tiny bit seeing as how we never add MVCCVersionTimestampSize (even for the very merge/write). We could say as much, we still expect these errors to be corrected during splits and merges.
</blockquote></details>

I think it looks good to me? What do you think is the missing part?

**Review by irfansharif — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/54949)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @irfansharif, @itsbilal, and @TheSamHuang)

___
*[pkg/storage/mvcc.go, line 268 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/54949#-MIPVHx9wPG1NpnUBPeg-r1-268:-MIUmV4a9gYdfymmz2ls:b-dcghku) ([raw file](https://github.com/cockroachdb/cockroach/blob/48aeebc3b0398cf3f29e8e94fb7ddbbe0e871c80/pkg/storage/mvcc.go#L268)):*
<details><summary><i>Previously, itsbilal (Bilal Akhtar) wrote…</i></summary><blockquote>

I think it looks good to me? What do you think is the missing part?
</blockquote></details>

The review comment was from an earlier (now hidden) SHA. The new comment LGTM too.

File: pkg/storage/mvcc_test.go (hunk 7 above)
Comment (TheSamHuang) [reply pkg/storage/mvcc_test.go]: Confirming that the test does fail without the change: 
Before: 
```
=== RUN   TestTimeSeriesMVCCStats
=== RUN   TestTimeSeriesMVCCStats/rocksdb
=== RUN   TestTimeSeriesMVCCStats/pebble
--- FAIL: TestTimeSeriesMVCCStats (0.01s)
    --- FAIL: TestTimeSeriesMVCCStats/rocksdb (0.01s)
        mvcc_test.go:5282: second merged LiveBytes value 92 differed from expected LiveBytes value 80
    --- FAIL: TestTimeSeriesMVCCStats/pebble (0.00s)
        mvcc_test.go:5282: second merged LiveBytes value 92 differed from expected LiveBytes value 80
FAIL
FAIL	github.com/cockroachdb/cockroach/pkg/storage	1.203s
FAIL
make: *** [test] Error 1
```
After: 
```
=== RUN   TestTimeSeriesMVCCStats
=== RUN   TestTimeSeriesMVCCStats/rocksdb
=== RUN   TestTimeSeriesMVCCStats/pebble
--- PASS: TestTimeSeriesMVCCStats (0.01s)
    --- PASS: TestTimeSeriesMVCCStats/rocksdb (0.01s)
    --- PASS: TestTimeSeriesMVCCStats/pebble (0.00s)
PASS
ok  	github.com/cockroachdb/cockroach/pkg/storage	1.076s
```
