### PR TITLE
sql: ensure auto-retrying transactions respect the statement_timeout

### LINKED ISSUE #52845: sql: statement_timeout should not be reset after implicit transaction retries
**Describe the problem**

`statement_timeout` is a session variable that is meant to place an upper bound on how long a query can execute. However, if a query is an implicit transaction and it retries automatically, then the `statement_timeout` is reset. This means that there is no way to limit how much time the database will spend on automatically retrying a query.

**To Reproduce**

```
root@:26257/defaultdb> select crdb_internal.force_retry('5s');
  crdb_internal.force_retry
-----------------------------
                          0
(1 row)
Time: 5.001589s

root@:26257/defaultdb> set statement_timeout = '1s';
SET
Time: 290µs

root@:26257/defaultdb> select crdb_internal.force_retry('5s');
ERROR: query execution canceled due to statement timeout
SQLSTATE: 57014
```

Although the last query returned with a timeout error, this result was not received until after 5 seconds elapsed -- that is, the duration specified in the `force_retry` function.

**Expected behavior**

The timeout error in the example above should be returned after 1 second.

**Additional context**
If there are problematic queries that are retried a lot (thousands of times), then the lack of a `statement_timeout` means that these queries could starve other normal queries.

### PR DESCRIPTION
**Pull request by arulajmani**
Previously, if a statement exceeded the statement_timnout in the
conn_executor, but failed with a retryable error, we would still retry
it. This was because even though we overrode the error, we didn't
override the `fms.Event` and `fsm.EventPayload` which actually dictates
the next transition. This patch overrides them, thereby ensuring that
even if a timed out query/cancelled query encountered a retryable
error, we do not transition into retrying it.

Fixes #52845

Release justification: low risk, high benefit changes to existing functionality

Release note (bug fix): queries that can be automatically retried did
not respect the `statement_timeout` earlier, which is now fixed.

### CODE REVIEW

**Comment by arulajmani** [comment]
@andreimatei I know we talked about moving making `makeErrEvent` responsible for the overriding, but I couldn't make that work because of https://github.com/cockroachdb/cockroach/blob/41375eb9544ca30b91eb1e9087efed3221004eef/pkg/sql/conn_executor_exec.go#L618, which doesn't use that function to generate a retryable event. Left it in the `queryDone` function for now.

**Comment by rafiss** [comment]
Thanks for your work @arulajmani . Heads up I've added this PR to the list of requested backports to the 20.2 branch. #53662

File: pkg/sql/run_control_test.go [hunk 1]
```diff
@@ -848,6 +848,54 @@ func TestIdleInTransactionSessionTimeoutCommitWaitState(t *testing.T) {
...
+		t.Fatal(err)
+	}
+
+	_, err = conn.QueryContext(ctx,
+		`SET statement_timeout = '0.1s'`)
+	if err != nil {
+		t.Fatal(err)
+	}
+
+	timer := time.AfterFunc(1*time.Second, func() {
```
Comment (rafiss) [inline pkg/sql/run_control_test.go:873]: nit: could you add a comment here mentioning that this is here to verify that the timeout error is returned before the 2 second interval passed to `force_retry` elapses?

**Review by andreimatei — APPROVED** [review]
LGTM

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/53968#-:-MGnRMQN9O5j0lAIn4bj:bb6ywmx)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andreimatei, @arulajmani, and @rafiss)

___
*[pkg/sql/conn_executor_exec.go, line 394 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/53968#-MGnKqRbDrxXymFAT6Fb:-MGnKqRbDrxXymFAT6Fc:b-z5n733) ([raw file](https://github.com/cockroachdb/cockroach/blob/32fbf0868376de1fffc11c5dcf65c8e5270f0093/pkg/sql/conn_executor_exec.go#L394)):*
> ```Go
> 		// There's no need to proceed with execution if the timer has already expired.
> 		if timerDuration < 0 {
> 			ex.cancelQuery(stmt.queryID)
> ```

Is this `ex.cancelQuery()` call necessary? If it isn't, I wouldn't do it since it just leads to questions about what async work are we canceling.
___
*[pkg/sql/run_control_test.go, line 869 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/53968#-MGnNILY9mPWAGcSV6qk:-MGnNILY9mPWAGcSV6ql:b1zp2as) ([raw file](https://github.com/cockroachdb/cockroach/blob/32fbf0868376de1fffc11c5dcf65c8e5270f0093/pkg/sql/run_control_test.go#L869)):*
> ```Go
> 	_, err = conn.QueryContext(ctx,
> 		`SET statement_timeout = '0.1s'`)
> 	if err != nil {
> ```

nit: `require.NoError(t, err)`
___
*[pkg/sql/run_control_test.go, line 873 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/53968#-MGPNLLwJWyozh9DePRk-r1-873:-MGnNpAr7TmX4h83IlI2:bxcx83m) ([raw file](https://github.com/cockroachdb/cockroach/blob/32fbf0868376de1fffc11c5dcf65c8e5270f0093/pkg/sql/run_control_test.go#L873)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

nit: could you add a comment here mentioning that this is here to verify that the timeout error is returned before the 2 second interval passed to `force_retry` elapses?
</blockquote></details>

better yet, get rid of this since it's broken anyway (can't `t.Fatal()` on any goroutine but the main one) and just measure the elapsed time until you get the error. No need for asynchrony.
___
*[pkg/sql/run_control_test.go, line 878 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/53968#-MGnNYee190-xhnb2ME8:-MGnNYee190-xhnb2ME9:b-fpic5r) ([raw file](https://github.com/cockroachdb/cockroach/blob/32fbf0868376de1fffc11c5dcf65c8e5270f0093/pkg/sql/run_control_test.go#L878)):*
> ```Go
> 
> 	_, err = conn.QueryContext(ctx, `SELECT crdb_internal.force_retry('2s')`)
> 	if !testutils.IsError(err, "pq: query execution canceled due to statement timeout") {
> ```

just fyi, consider `require.Regexp(t, "pq: ...", err)`
___
*[pkg/sql/run_control_test.go, line 885 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/53968#-MGnRE8mCO6qlNpQ79iA:-MGnRE8mCO6qlNpQ79iB:b-pnsvxn) ([raw file](https://github.com/cockroachdb/cockroach/blob/32fbf0868376de1fffc11c5dcf65c8e5270f0093/pkg/sql/run_control_test.go#L885)):*
> ```Go
> 	timer.Stop()
> 
> 	// Same test as above, except in an explicit transaction.
> ```

instead of repeating, use `testutils.RunTrueAndFalse()` and construct the query dynamically.

**Review by arulajmani — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/53968)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andreimatei)

___
*[pkg/sql/conn_executor_exec.go, line 394 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/53968#-MGnKqRbDrxXymFAT6Fb:-MH8nSkr-AYTMP3_beIE:b5q275a) ([raw file](https://github.com/cockroachdb/cockroach/blob/32fbf0868376de1fffc11c5dcf65c8e5270f0093/pkg/sql/conn_executor_exec.go#L394)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

Is this `ex.cancelQuery()` call necessary? If it isn't, I wouldn't do it since it just leads to questions about what async work are we canceling.
</blockquote></details>

It was in the earlier structure, where the assumption was query timeouts were a special case of cancelled queries. I've untangled that bit by checking and overwriting for timed out queries outside the cancelled queries check in the `queryDone` function, which allows me to get rid of this `ex.cancelQuery` call here.
___
*[pkg/sql/run_control_test.go, line 878 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/53968#-MGnNYee190-xhnb2ME8:-MH8fc4E6jM4Q429t4-f:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/32fbf0868376de1fffc11c5dcf65c8e5270f0093/pkg/sql/run_control_test.go#L878)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

just fyi, consider `require.Regexp(t, "pq: ...", err)`
</blockquote></details>

Done.
___
*[pkg/sql/run_control_test.go, line 885 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/53968#-MGnRE8mCO6qlNpQ79iA:-MH8f6bX73j4ClwJf6oN:b2gzftp) ([raw file](https://github.com/cockroachdb/cockroach/blob/32fbf0868376de1fffc11c5dcf65c8e5270f0093/pkg/sql/run_control_test.go#L885)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

instead of repeating, use `testutils.RunTrueAndFalse()` and construct the query dynamically.
</blockquote></details>

Much cleaner, done!

**Comment by arulajmani** [comment]
bors r=andreimatei

**Comment by otan** [comment]
bors r-

looks like this is failing CI

**Comment by arulajmani** [comment]
Oops looks like I was branched off quite an old master, the test interface I was using was apparently changed. 

bors r=andreimatei

**Comment by otan** [comment]
do you think the test failure in https://teamcity.cockroachdb.com/viewLog.html?buildId=2269713&buildTypeId=Cockroach_UnitTests is related to this PR?

**Comment by arulajmani** [comment]
This PR might have made that test flaky, as 1ms may not be enough time to execute `SET statement_timout = 0` anymore. This PR no longer tries executing the statement if the timer has already elapse, wheras it earlier it would have been a race between the timer stopping and the statement being executed. I think we should just increase the statement timeout to something > 1ms so that this doesn't flake. I'll send out a PR.

**Comment by rafiss** [comment]
Let's also backport this PR and the test change as well (to the 20.2 branch)
