### PR TITLE
backupccl: Replace DEBUG_PAUSE_ON option with standard pause point wh…

### LINKED ISSUE #121342: ccl/backupccl: TestRestorePauseOnError failed
ccl/backupccl.TestRestorePauseOnError [failed](https://tanzanite.cluster.engflow.com/invocations/default/d9d2197a-8684-408b-aa5a-ee7f91757517?testReportRun=1&testReportShard=12&testReportAttempt=1#targets-Ly9wa2cvY2NsL2JhY2t1cGNjbDpiYWNrdXBjY2xfdGVzdA==) on master @ [a3ac7ebf958f25201c2696a17f996c0b9f86830f](https://github.com/cockroachdb/cockroach/commits/a3ac7ebf958f25201c2696a17f996c0b9f86830f):

```
=== RUN   TestRestorePauseOnError
    test_log_scope.go:170: test logs captured to: outputs.zip/logTestRestorePauseOnError98142672
    backup_test.go:9235: expected jobID 955604274711265281 to have status paused got succeeded
    testutils.go:289: no Invalid Descriptors
    panic.go:626: -- test log scope end --
test logs left over in: outputs.zip/logTestRestorePauseOnError98142672
--- FAIL: TestRestorePauseOnError (46.33s)
```

Parameters:
 - <code>attempt=1</code>
 - <code>run=1</code>
 - <code>shard=12</code>
<details><summary>Help</summary>
<p>

See also: [How To Investigate a Go Test Failure \(internal\)](https://cockroachlabs.atlassian.net/l/c/HgfXfJgM)
</p>
</details>
<details><summary>Same failure on other branches</summary>
<p>

- #121336 ccl/backupccl: TestRestorePauseOnError failed [C-test-failure O-robot T-disaster-recovery branch-release-24.1 release-blocker]
</p>
</details>
/cc @cockroachdb/disaster-recovery
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*TestRestorePauseOnError.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/bazci/githubpost/issues)
</sub>

Jira issue: CRDB-37200

### PR DESCRIPTION
**Pull request by navsetlur**
…en pausing a restore operation on error

The DEBUG_PAUSE_ON option was previously used to pause a restore operation when it failed before returning the error. We currently have a standardized way of pausing operations via the pause point interface and it made sense to update this feature to use this approach while fixing a test failure. This change removes the DEBUG_PAUSE_ON option and replaces it with a 'restore.restore_after_failure' pause point.

Fixes: #121342

Release note (enterprise): The DEBUG_PAUSE_ON option has been removed entirely and replaced with the 'restore.restore_after_failure' pause point to match other pause points used throughout the codebase. You can set this pause point by running  `SET CLUSTER SETTING jobs.debug.pausepoints = 'restore.after_restore_failure'`

### CODE REVIEW

File: pkg/ccl/backupccl/backup_test.go [hunk 1]
```diff
@@ -9167,12 +9165,14 @@ func TestRestorePauseOnError(t *testing.T) {
 			})
 	}
 
+	t.Logf("Test")
+	sqlDB.Exec(t, `SET CLUSTER SETTING jobs.debug.pausepoints = 'restore.after_restore_failure'`)
```
Comment (dt) [inline pkg/ccl/backupccl/backup_test.go:9169]: IMO you could delete the whole test?

File: pkg/ccl/backupccl/restore_job.go [hunk 2]
```diff
@@ -1716,19 +1716,14 @@ func remapPublicSchemas(
...
-		if details.DebugPauseOn == "error" {
-			const errorFmt = "job failed with error (%v) but is being paused due to the %s=%s setting"
-			log.Warningf(ctx, errorFmt, err, restoreOptDebugPauseOn, details.DebugPauseOn)
-
-			return jobs.MarkPauseRequestError(errors.Wrapf(err,
-				"pausing job due to the %s=%s setting",
-				restoreOptDebugPauseOn, details.DebugPauseOn))
+		log.Warningf(ctx, "The error was injected")
+		if err_inner := p.ExecCfg().JobRegistry.CheckPausepoint("restore.after_restore_failure"); err_inner != nil {
+			return err_inner
```
Comment (dt) [inline pkg/ccl/backupccl/restore_job.go:1723]: Does it still paue if you do errors.CombineErrors(pauseErr, err)?

File: pkg/ccl/backupccl/restore_job.go [hunk 3]
```diff
@@ -1716,19 +1716,14 @@ func remapPublicSchemas(
...
 	if err := r.doResume(ctx, execCtx); err != nil {
-		details := r.job.Details().(jobspb.RestoreDetails)
-		if details.DebugPauseOn == "error" {
-			const errorFmt = "job failed with error (%v) but is being paused due to the %s=%s setting"
-			log.Warningf(ctx, errorFmt, err, restoreOptDebugPauseOn, details.DebugPauseOn)
-
-			return jobs.MarkPauseRequestError(errors.Wrapf(err,
-				"pausing job due to the %s=%s setting",
-				restoreOptDebugPauseOn, details.DebugPauseOn))
+		log.Warningf(ctx, "The error was injected")
```
Comment (dt) [inline pkg/ccl/backupccl/restore_job.go:1721]: stray debug line?

File: pkg/ccl/backupccl/restore_job.go [hunk 4]
```diff
@@ -1716,19 +1716,14 @@ func remapPublicSchemas(
...
+		if err_inner := p.ExecCfg().JobRegistry.CheckPausepoint("restore.after_restore_failure"); err_inner != nil {
```
Comment (dt) [inline pkg/ccl/backupccl/restore_job.go:1722]: go style nit: we generally don't use snake case; maybe `pauseErr` if you are trying to avoid shadowing?

(it would be shadowing, not overwriting, as long as you're using `:=` and only in the scope of the early return, but you might still want to avoid shadowing if we want to pass along the causing error too)

File: pkg/ccl/backupccl/backup_test.go (hunk 1 above)
Comment (navsetlur) [reply pkg/ccl/backupccl/backup_test.go:9169]: do you think it's worth leaving the test for now until we know the CombineErrors is fine in master, or are you confident enough that we can drop it now

**Comment by navsetlur** [comment]
bors r=dt

File: pkg/ccl/backupccl/backup_test.go (hunk 1 above)
Comment (dt) [reply pkg/ccl/backupccl/backup_test.go:9169]: I would probably just delete it now; we don't maintain tests for other pause point calls.

**Review by dt — APPROVED** [review]

**Comment by navsetlur** [comment]
bors=dt

**Comment by navsetlur** [comment]
bors r=dt

**Comment by navsetlur** [comment]
bors r=dt
