### PR TITLE
opt: disallow fast path for cascading deletes with subqueries

### LINKED ISSUE #64179: sql: internal error: while building cascade expression: runtime error: index out of range [2] with length 2
<hidden>

### PR DESCRIPTION
**Pull request by mgartner**
Previously, the optimizer would attempt to build a fast path cascading
delete for `DELETE`s with a subquery. This caused errors when copying
the original filters for the fast path query. The cascade query is built
using a separate memo with metadata that does not include tables in the
original memo's metadata. As a result, a Scan in a cascade fast path
subquery could reference a table ID that did not exist in the metadata.

This commit prevents building fast path cascading deletes if the
delete has any subqueries.

Fixes #64179

Release note (bug fix): Cascading `DELETE`s with subqueries no longer
error. This bug was present since v21.1.0-alpha.1.

### CODE REVIEW

File: pkg/sql/opt/optbuilder/fk_cascade.go [hunk 1]
```diff
@@ -189,6 +189,9 @@ func tryNewOnDeleteFastCascadeBuilder(
 		if memo.CanBeCompositeSensitive(md, &sel.Filters) {
 			return nil, false
 		}
+		if sel.Relational().HasSubquery {
```
Comment (mgartner) [inline pkg/sql/opt/optbuilder/fk_cascade.go:192]: I considered leaving a TODO here to explain that a cascade fast path could be planned for non-correlated subqueries if we correctly replaced references to tables in Scans and other relational expressions. But I don't think there's much value in supporting that and it seems very difficult to get correct, so I doubt we'd ever want to support that.

File: pkg/sql/opt/optbuilder/testdata/fk-on-delete-cascade [hunk 2]
```diff
@@ -65,6 +65,42 @@ root
                 └── filters
                      └── child.p:9 = p:11
 
+# Delete with subquery; no fast path.
+build-cascades
+DELETE FROM parent WHERE EXISTS (SELECT p FROM parent)
```
Comment (mgartner) [inline pkg/sql/opt/optbuilder/testdata/fk-on-delete-cascade:70]: Oddly, this test doesn't error before the fix. I couldn't really figure out why exactly.

**Review by RaduBerinde — APPROVED** [review]
:lgtm: Thanks for the fix!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/64252#-:-MZGZHts-v8yqUhjZega:b-72sm86)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @mgartner and @rytaft)

___
*[pkg/sql/opt/optbuilder/testdata/fk-on-delete-cascade, line 70 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/64252#-MZFy4w_9LDEnyOGm5QJ-r1-70:-MZGZ85486M0SfixXUKe:bf494g6) ([raw file](https://github.com/cockroachdb/cockroach/blob/df3bc9051e80a31248846fe658868dfab7acbf82/pkg/sql/opt/optbuilder/testdata/fk-on-delete-cascade#L70)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

Oddly, this test doesn't error before the fix, it manages to plan a fast path cascade without running into issues with the metadata. I couldn't really figure out why exactly. 
</blockquote></details>

It's because of this: https://github.com/cockroachdb/cockroach/blob/f32a98685683b8b45ab83d67948ceddee773a7b5/pkg/sql/opt/testutils/opttester/opt_tester.go#L573

**Review by rytaft — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/64252#-:-MZI4uIOEw6Wmor3O4AK:bnfp4nl)* status: :shipit: complete! 2 of 0 LGTMs obtained (waiting on @mgartner)

**Comment by mgartner** [comment]
___
*[pkg/sql/opt/optbuilder/testdata/fk-on-delete-cascade, line 70 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/64252#-MZFy4w_9LDEnyOGm5QJ-r1-70:-MZIvM0H926A7MMHnw6l:bc9wpsp) ([raw file](https://github.com/cockroachdb/cockroach/blob/df3bc9051e80a31248846fe658868dfab7acbf82/pkg/sql/opt/optbuilder/testdata/fk-on-delete-cascade#L70)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

It's because of this: https://github.com/cockroachdb/cockroach/blob/f32a98685683b8b45ab83d67948ceddee773a7b5/pkg/sql/opt/testutils/opttester/opt_tester.go#L573
</blockquote></details>

Aha! Do you think it'd be useful to run every `build-cascades` test twice: once with the same memo with the expression tree compared to the test file (like it works now) and once with a different memo that will fail the test if an error occurs but not be compared to the test file expression? Or maybe there's a clever way to format the cascade tree when a different memo is used so that it's not difficult to read and the tests operate more similarly to production.

**Comment by mgartner** [comment]
TFTRs!

bors r+

**Comment by RaduBerinde** [comment]
___
*[pkg/sql/opt/optbuilder/testdata/fk-on-delete-cascade, line 70 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/64252#-MZFy4w_9LDEnyOGm5QJ-r1-70:-MZJBCFS1cNiS2CNYA4w:b-n9ka68) ([raw file](https://github.com/cockroachdb/cockroach/blob/df3bc9051e80a31248846fe658868dfab7acbf82/pkg/sql/opt/optbuilder/testdata/fk-on-delete-cascade#L70)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

Aha! Do you think it'd be useful to run every `build-cascades` test twice: once with the same memo with the expression tree compared to the test file (like it works now) and once with a different memo that will fail the test if an error occurs but not be compared to the test file expression? Or maybe there's a clever way to format the cascade tree when a different memo is used so that it's not difficult to read and the tests operate more similarly to production.
</blockquote></details>

I think we can just add some fake columns to the metadata (as many as were seen so far) so that the IDs don't overlap.
