### PR TITLE
opt: duplicate all table metadata fields when duplicating a scan

### LINKED ISSUE #52207: opt: copy TableMeta.PartialIndexPredicates in Metadata.AddTable to avoid panics
The `SplitDisjunction` and `SplitDisjunctionAddKey` rules duplicate their input `ScanPrivate`s in order to create a new Scan that will be `UNION`ed with the original. In order to safely duplicate the `ScanPrivate`, [a new `TableMeta` is created with new column IDs](https://github.com/cockroachdb/cockroach/blob/5011a06a25b0845ff9ebbff8e49e3aabe6da9c0d/pkg/sql/opt/xform/custom_funcs.go#L3051-L3053).

This creates problems with the current partial index implementation. For `SELECT` queries, partial index predicate expressions are built by optbuilder with the scope of the canonical scan, and stored on the table metadata. The first issue here is that duplicating table metadata with `Metadata.AddTable` does not copy the parsed predicate expressions to the new `TableMeta`. However, even if the predicate expressions were copied, they would not be scoped correctly to the new table and column IDs.

A critical problem I see is that we need a way to re-build predicate expressions when tables are duplicated, but there's no precedent or ability, as far as I know, to invoke the optbuilder during transformation.

To reproduce the problem:

```
exec-ddl
CREATE TABLE a (
  k INT PRIMARY KEY,
  i INT,
  s STRING,
  t STRING,
  INDEX idx_s (s),
  INDEX idx_i_200_to_250 (i) WHERE i > 200 AND i < 250
)
----

opt
SELECT * FROM a WHERE (i > 215 AND i < 230) OR s = 'baz'
----
```

### PR DESCRIPTION
**Pull request by mgartner**
This commit fixes incorrect duplication of `TableMeta` when duplicating
scans, such as in the `SplitDisjuction` exploration rule. Previously,
`ScalarExpr`s in the table metadata were not being duplicated when the
table metadata was duplicated. This resulted in panics when trying to
access these fields.

All the fields of `TableMeta` are now duplicated correctly. Column IDs
in `ScalarExpr` fields are remapped to the newly generated column IDs.

This commit also simplifies the explanation for when column IDs can be
reused.

Fixes #52207

Release note: None

### CODE REVIEW

File: pkg/sql/opt/metadata.go [hunk 1]
```diff
@@ -56,55 +57,18 @@ type privilegeBitmap uint32
...
-// Therefore, using the same column id to represent two different columns can
-// produce inaccurate plan costs, plans that are semantically inequivalent to
-// the original plan, or errors. Columns of different types must never use the
-// same id. Additionally, column ids cannot be overloaded within two relational
-// expressions that interact with each other.
+// An operator is allowed to reuse the column ids of its input if for every
+// output row there exists an input row having identical values for those
+// columns. For example, is it safe for a Select to use its input's column ids
+// because it only filters rows. Likewise, pass-through column ids of a Project
+// can be reused.
```
Comment (andy-kimball) [inline pkg/sql/opt/metadata.go:64]: You need to add the NULL case as well. Maybe this:
```
// An operator is allowed to reuse some or all of the column ids of an input if:
//
// 1. For every output row, there exists at least one input row having identical
//    values for those columns.
// 2. OR if no such input row exists, there is at least one output row having
//    NULL values for all those columns (e.g. when outer join NULL-extends).
//
// For example, is it safe for a Select to use its input's column ids because it
// only filters rows. Likewise, pass-through column ids of a Project can be
// reused.
```

File: pkg/sql/opt/metadata.go [hunk 2]
```diff
@@ -415,6 +379,87 @@ func (md *Metadata) AddTable(tab cat.Table, alias *tree.TableName) TableID {
...
+// ScalarExpr to new column IDs. It takes as arguments a ScalarExpr and a
+// mapping of old column IDs to new column IDs, and returns a new ScalarExpr.
+// This function is used when duplicating Constraints, ComputedCols, and
+// PartialIndexPredicates.
+//
+// The ExplicitCatalog/ExplicitSchema fields of the table's alias are honored so
+// that its original formatting is preserved for error messages,
+// pretty-printing, etc.
+func (md *Metadata) DuplicateTable(
+	tabID TableID, remapColumnIDs func(e ScalarExpr, colMap util.FastIntMap) ScalarExpr,
```
Comment (andy-kimball) [inline pkg/sql/opt/metadata.go:398]: I think I'd just use `map[opt.ColumnID]opt.ColumnID` here. Except for really small queries, `FastIntMap` will become that anyway, and it doesn't have strong-typing.

File: pkg/sql/opt/metadata.go [hunk 3]
```diff
@@ -415,6 +379,87 @@ func (md *Metadata) AddTable(tab cat.Table, alias *tree.TableName) TableID {
...
+// columns are added to the metadata with new column IDs. If mutation columns
+// are present, they are added after active columns. The ID of the new table
+// reference is returned. This function panics if a table with the given ID does
+// not exists in the metadata.
+//
+// remapColumnIDs must be a function that remaps the column IDs within a
+// ScalarExpr to new column IDs. It takes as arguments a ScalarExpr and a
+// mapping of old column IDs to new column IDs, and returns a new ScalarExpr.
+// This function is used when duplicating Constraints, ComputedCols, and
+// PartialIndexPredicates.
```
Comment (andy-kimball) [inline pkg/sql/opt/metadata.go:392]: Maybe a comment explaining why it takes a callback function rather than directly duplicating the expressions.

File: pkg/sql/opt/metadata.go (hunk 2 above)
Comment (andy-kimball) [reply pkg/sql/opt/metadata.go:398]: Hm, but I see that lower down, you replaced the existing `MapFiltersItemCols` function, which uses a `FastIntMap`. At least change this to be `opt.ColMap`, which is a nicer-looking alias.

File: pkg/sql/opt/norm/select_funcs.go [hunk 4]
```diff
@@ -39,7 +39,7 @@ func (c *CustomFuncs) MapSetOpFilterLeft(
 	filter *memo.FiltersItem, set *memo.SetPrivate,
 ) opt.ScalarExpr {
 	colMap := makeMapFromColLists(set.OutCols, set.LeftCols)
-	return c.MapFiltersItemCols(filter, colMap)
+	return c.RemapCols(filter.Condition, colMap)
```
Comment (andy-kimball) [inline pkg/sql/opt/norm/select_funcs.go:42]: I like that it turns out we already had the callback function basically written. Nice that you noticed this.

**Review by andy-kimball — APPROVED** [review]
Whoops, I just realized that I didn't use Reviewable. I'm in habit of using Github b/c of working on CC. Hopefully you'll forgive me.

LGTM, with a few small-ish comments. It turned out nicely.

File: pkg/sql/opt/metadata.go (hunk 1 above)
Comment (mgartner) [reply pkg/sql/opt/metadata.go:64]: Ahh I missed that addendum. Fixed.

File: pkg/sql/opt/metadata.go (hunk 3 above)
Comment (mgartner) [reply pkg/sql/opt/metadata.go:392]: Done.

File: pkg/sql/opt/metadata.go (hunk 2 above)
Comment (mgartner) [reply pkg/sql/opt/metadata.go:398]: Done.

File: pkg/sql/opt/norm/select_funcs.go (hunk 4 above)
Comment (mgartner) [reply pkg/sql/opt/norm/select_funcs.go:42]: Ya it was a great feeling when I realized in `DuplicateScanPrivate` that we just needed to pass `c.RemapCols` as the callback.

**Comment by mgartner** [comment]
bors r=andy-kimball
