### PR TITLE
copy: fix nil pointer in COPY telemetry logging

### LINKED ISSUE #102494: Uploading a User File Crashes v23.1.0.beta.3 Sql Servers
**Describe the problem**

When I attempt to upload a userfile to a 23.1.0.beta.3 serverless cluster, the sql pod crashes.

The user visible error is:
```
jeffswenson@crlMBP-C02FP1G5MD6TMTE5 backup-test % cockroach userfile upload -r --url 'postgresql://restore:REDACTED@restore-target-2-3.74fg.crdb.io:26257?sslmode=verify-full' backup-1682627613 userfile://defaultdb.public.backup/test
uploading: 2023/04/27-203335.91/BACKUP-LOCK-860347485150052353
E230427 21:24:22.016954 1 1@cli/clierror/check.go:35  [-] 1  unexpected EOF
ERROR: unexpected EOF
Failed running "userfile upload"
```

The stack trace from the sql server is:
```
E230427 20:43:39.282571 591 1@util/log/logcrash/crash_reporting.go:188 ⋮ [T3,nsql2,peer=‹10.0.0.245:42052›,client=142.154.197.226:63012,user=‹restore›] 16 a panic has occurred!
runtime error: invalid memory address or nil pointer dereference
(1) attached stack trace
  -- stack trace:
  | github.com/cockroachdb/cockroach/pkg/sql.(*Server).ServeConn.func1
  |     github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:865
  | [...repeated from below...]
Wraps: (2) attached stack trace
  -- stack trace:
  | github.com/cockroachdb/cockroach/pkg/sql.(*Server).ServeConn.func1
  |     github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:865
  | runtime.gopanic
  |     GOROOT/src/runtime/panic.go:884
  | runtime.panicmem
  |     GOROOT/src/runtime/panic.go:260
  | runtime.sigpanic
  |     GOROOT/src/runtime/signal_unix.go:835
  | github.com/cockroachdb/cockroach/pkg/sql.(*planner).maybeLogStatementInternal
  |     github.com/cockroachdb/cockroach/pkg/sql/exec_log.go:417
  | github.com/cockroachdb/cockroach/pkg/sql.(*planner).maybeLogStatement
  |     github.com/cockroachdb/cockroach/pkg/sql/exec_log.go:169
  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execCopyIn.func4
  |     github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:2944
  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execCopyIn
  |     github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:3105
  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execCmd
  |     github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:2310
  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).run
  |     github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:2067
  | github.com/cockroachdb/cockroach/pkg/sql.(*Server).ServeConn
  |     github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:867
  | github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*conn).processCommandsAsync.func1
  |     github.com/cockroachdb/cockroach/pkg/sql/pgwire/conn.go:738
  | runtime.goexit
  |     GOROOT/src/runtime/asm_amd64.s:1594
Wraps: (3) runtime error: invalid memory address or nil pointer dereference
Error types: (1) *withstack.withStack (2) *withstack.withStack (3) runtime.errorString
```

Here is a debug zip from my test cluster:
[gcp-global-staging-2-74fg-tenant-3-1682628632-debug-unredacted.zip](https://github.com/cockroachdb/cockroach/files/11348087/gcp-global-staging-2-74fg-tenant-3-1682628632-debug-unredacted.zip)

**Environment:**
 - CockroachDB version v23.1.0.beta.3

Jira issue: CRDB-27483

### PR DESCRIPTION
**Pull request by rafiss**
fixes https://github.com/cockroachdb/cockroach/issues/102494

Release note (bug fix): Fixed a panic that could occur while a COPY statement is logged for telemetry purposes.

### CODE REVIEW

**Review by otan — APPROVED** [review]

File: pkg/sql/conn_executor.go [hunk 1]
```diff
@@ -2945,12 +2945,10 @@ func (ex *connExecutor) execCopyIn(
 		initPlanner: func(ctx context.Context, p *planner) {
 			ex.initPlanner(ctx, p)
 		},
-		resetPlanner: func(ctx context.Context, p *planner, txn *kv.Txn, txnTS time.Time, stmtTS time.Time) {
```
Comment (otan) [inline pkg/sql/conn_executor.go:2948]: should we delete this object from the struct too?

Comment (rafiss) [reply pkg/sql/conn_executor.go:2948]: oops my fix is invalid. i forgot about the mode where we batch copies and call this `resetPlanner` in between each batch.

**Comment by rafiss** [comment]
went with a more basic fix. please take another look!

**Review by otan — APPROVED** [review]
