### PR TITLE
sql: prevent dropping enum values used in index partitioning or predicates

### LINKED ISSUE #63366: sql: PARTITIONING on an ENUM and using DROP VALUE on it returns an error
Consider:

```
SET enable_drop_enum_value = true;
create type t as enum('a', 'b', 'c');
create table tbl (pk t PRIMARY KEY) PARTITION BY LIST (pk) (PARTITION "a" VALUES IN ('a'));
alter partition "a" of table tbl configure zone using gc.ttlseconds = 1;
alter type t drop value 'a';
```

Now the tbl is broken:
```
demo@127.0.0.1:26257/defaultdb> select * from tbl;
ERROR: internal error: while decoding partition tuple: decoding: could not find [64] in enum "public.t" representation PhysicalReps: [[128] [192]]; LogicalReps: [b c]
SQLSTATE: XX000
DETAIL: stack trace:
github.com/cockroachdb/cockroach/pkg/sql/opt_catalog.go:1208: init()
github.com/cockroachdb/cockroach/pkg/sql/opt_catalog.go:800: newOptTable()
github.com/cockroachdb/cockroach/pkg/sql/opt_catalog.go:441: dataSourceForTable()
github.com/cockroachdb/cockroach/pkg/sql/opt_catalog.go:381: dataSourceForDesc()
github.com/cockroachdb/cockroach/pkg/sql/opt_catalog.go:215: ResolveDataSource()
github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder/util.go:574: resolveDataSource()
github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder/select.go:103: buildDataSource()
github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder/select.go:59: buildDataSource()
github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder/select.go:1086: buildFromTablesRightDeep()
github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder/select.go:1063: buildFromTables()
github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder/select.go:990: buildFrom()
github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder/select.go:911: buildSelectClause()
github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder/select.go:859: buildSelectStmtWithoutParens()
github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder/select.go:832: func1()
github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder/with.go:110: processWiths()
github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder/select.go:831: buildSelect()
github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder/builder.go:275: buildStmt()
github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder/builder.go:235: buildStmtAtRoot()
github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder/builder.go:209: Build()
github.com/cockroachdb/cockroach/pkg/sql/plan_opt.go:508: buildExecMemo()
github.com/cockroachdb/cockroach/pkg/sql/plan_opt.go:194: makeOptimizerPlan()
github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:940: makeExecPlan()
github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:821: dispatchToExecutionEngine()
github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:659: execStmtInOpenState()
github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:122: execStmt()
github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:1527: func1()
github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:1529: execCmd()
github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:1450: run()
github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:484: ServeConn()
github.com/cockroachdb/cockroach/pkg/sql/pgwire/conn.go:626: func1()
runtime/asm_amd64.s:1374: goexit()
```

We probably want to block DROP VALUE if any partitions depend on the enum.

Not marking as GA blocker as it is experimental.

Found this whilst debugging a concurrent ADD/DROP REGION and REGIONAL BY ROW partition interactions. Going to need to do something more nuclear there (#63368).

Epic CRDB-2451

### PR DESCRIPTION
**Pull request by ajwerner**
This commit adds logic to detect usages of enum values in partitioning clauses
and in index predicates.

Fixes #63366.

Release note (bug fix): Fixed a bug which permitted the dropping of enum values
which were in use in index predicates or partitioning values.

### CODE REVIEW

File: pkg/ccl/logictestccl/testdata/logic_test/partitioning_enum [hunk 1]
```diff
@@ -55,3 +55,29 @@ ALTER TABLE partitioned_table_3 PARTITION BY RANGE (place)
...
+
+subtest drop_enum_partitioning_value
+
+statement ok
+drop table if exists tbl;
+drop type if exists t;
+set enable_drop_enum_value = true;
+create type t as enum('a', 'b', 'c');
+create table tbl (pk t PRIMARY KEY) PARTITION BY LIST (pk) (PARTITION "a" VALUES IN ('a'));
+alter partition "a" of table tbl configure zone using gc.ttlseconds = 1;
```
Comment (otan) [inline pkg/ccl/logictestccl/testdata/logic_test/partitioning_enum:68]: nit: remove trailing `;` in all these statements in this file and below

File: pkg/sql/type_change.go [hunk 2]
```diff
@@ -902,6 +949,111 @@ func (t *typeSchemaChanger) canRemoveEnumValue(
...
+		id, err := typedesc.UserDefinedTypeOIDToID(typT.Oid())
+		if err != nil {
+			return false, errors.WithAssertionFailure(err)
+		}
+		if id != typ.GetID() {
+			continue
+		}
+		colsToCheck.Add(i)
+	}
+	makeFakeDatums := func(n int) []tree.Datum {
```
Comment (otan) [inline pkg/sql/type_change.go:981]: can you add a comment about why these fake datums are needed?

**Review by otan — APPROVED** [review]

File: pkg/ccl/logictestccl/testdata/logic_test/partitioning_enum (hunk 1 above)
Comment (postamar) [inline pkg/ccl/logictestccl/testdata/logic_test/partitioning_enum:68]: I'm genuinely curious as to why this is even needed.

File: pkg/sql/type_change.go [hunk 3]
```diff
@@ -791,6 +795,49 @@ func (t *typeSchemaChanger) canRemoveEnumValue(
 		query.WriteString(fmt.Sprintf("SELECT %s FROM [%d as t] WHERE", columns, ID))
 		firstClause := true
 		validationQueryConstructed := false
+
+		for _, idx := range desc.AllIndexes() {
```
Comment (postamar) [inline pkg/sql/type_change.go:799]: I'm curious as to why we can't restrict ourselves to `desc.NonDropIndexes()`. I suppose there's a good reason but I don't know it.

File: pkg/sql/type_change.go [hunk 4]
```diff
@@ -791,6 +795,49 @@ func (t *typeSchemaChanger) canRemoveEnumValue(
...
+						})
+				}
+			}
+			keyColumns := make([]catalog.Column, 0, idx.NumKeyColumns())
+			for i := 0; i < idx.NumKeyColumns(); i++ {
+				col, err := desc.FindColumnWithID(idx.GetKeyColumnID(i))
+				if err != nil {
+					return errors.AssertionFailedf(
+						"failed to find column with id %s (%d) in %s (%d)",
+						idx.GetKeyColumnName(i), idx.GetKeyColumnID(i), desc.GetName(), desc.GetID(),
```
Comment (postamar) [inline pkg/sql/type_change.go:820]: nit: A `return errors.WithAssertionFailure(err)` should be enough here. This shouldn't ever happen seeing that the descriptor has been validated at this point.

**Review by postamar — APPROVED** [review]
LGTM. I just have questions for my own benefit.

This kind of code makes me wish we could routinely transform the descriptor state back into a fully decorated AST (the kind that would trivially map to some `SHOW CREATE` output) because then implementing these kinds of checks becomes easy-peasy.

**Comment by postamar** [comment]
These test failures are surprising. This one particularly:
```
statement ok
CREATE DATABASE repartition_privs PRIMARY REGION "ca-central-1" REGIONS "us-east-1";
CREATE TABLE repartition_privs.rbr () LOCALITY REGIONAL BY ROW;

....

statement ok
ALTER DATABASE repartition_privs DROP REGION "us-east-1"
```

I can't help but wonder if it's even legal to just drop a region when there's a REGIONAL BY ROW table. It seems to me that this should only be possible once we've validated that the table has no rows in which the region column's value is the one to be dropped.

File: pkg/sql/type_change.go (hunk 3 above)
Comment (ajwerner) [reply pkg/sql/type_change.go:799]: That seems legit. I should add a test that I can drop the index and then the enum value in the same transaction.

File: pkg/ccl/logictestccl/testdata/logic_test/partitioning_enum (hunk 1 above)
Comment (ajwerner) [reply pkg/ccl/logictestccl/testdata/logic_test/partitioning_enum:68]: I just cargo-culted this one.

**Comment by ajwerner** [comment]
> This kind of code makes me wish we could routinely transform the descriptor state back into a fully decorated AST (the kind that would trivially map to some SHOW CREATE output) because then implementing these kinds of checks becomes easy-peasy.

I'm not seeing how it would be easy peasy. We do have logic to convert the descriptors back to SHOW CREATE but it relies on a very large pile of machinery. 

> I can't help but wonder if it's even legal to drop a region when there's a REGIONAL BY ROW table. It seems to me that this should only be possible once we've validated that the table has no rows for which the region column's value is the one to be dropped.

Err, yeah, I need to look into that 😓

**Comment by postamar** [comment]
I'm saying _writing the checks in this PR_ would be easy-peasy: for each type back-reference, visit each node of the corresponding AST, check that none match the enum value to drop.

**Comment by otan** [comment]
> I can't help but wonder if it's even legal to drop a region when there's a REGIONAL BY ROW table.

We have something that checks that no row has that value before we drop it. @arulajmani can tell you more away from code search atm :)

**Comment by ajwerner** [comment]
> > I can't help but wonder if it's even legal to drop a region when there's a REGIONAL BY ROW table.
> 
> We have something that checks that no row has that value before we drop it. @arulajmani can tell you more away from code search atm :)

It's this very code I'm changing now. I've reworked things to repartition in the same transaction that does the check. I'll see what happens with the tests but this now mostly works.

**Comment by ajwerner** [comment]
Okay, with some relatively substantial refactoring, this now, I think, does the right thing without changing the contention footprint. I removed the `waitForLeasesToUpdate` because the descs.Collection does that for you. However, we used to not be using it properly because of the `cleanupFunc` clearing that thing. That was almost definitely a bug.

File: pkg/sql/type_change.go (hunk 3 above)
Comment (ajwerner) [reply pkg/sql/type_change.go:802]: Nah, I don't want that because if we fail to drop the index, because we fail on the schema change, I don't want to corrupt the table. The darn concurrency and rollback bugs are hard to think about.

File: pkg/ccl/logictestccl/testdata/logic_test/partitioning_enum (hunk 1 above)
Comment (ajwerner) [reply pkg/ccl/logictestccl/testdata/logic_test/partitioning_enum]: Removed

File: pkg/sql/type_change.go (hunk 4 above)
Comment (ajwerner) [reply pkg/sql/type_change.go]: Done.

File: pkg/ccl/logictestccl/testdata/logic_test/partitioning_enum (hunk 1 above)
Comment (ajwerner) [reply pkg/ccl/logictestccl/testdata/logic_test/partitioning_enum]: What did these trailing semicolons do to you?

File: pkg/sql/type_change.go (hunk 2 above)
Comment (ajwerner) [reply pkg/sql/type_change.go:994]: Done.

**Review by arulajmani — APPROVED** [review]
:lgtm: 

I have a couple inline questions for my own benefit, but the change looks good. 

> Reviewed 1 of 9 files at r2, 1 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/68257#-:-MfsZURB4Avaqy-zzBWG:b-ff42rm)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ajwerner, @otan, and @postamar)

___
*[pkg/ccl/logictestccl/testdata/logic_test/partitioning_enum, line 91 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/68257#-MfrzG6HALFnZnTXxBZw:-MfrzG6HALFnZnTXxBZx:bawmcp3) ([raw file](https://github.com/cockroachdb/cockroach/blob/10440e3998179abb0d72ffc2341191111251d518/pkg/ccl/logictestccl/testdata/logic_test/partitioning_enum#L91)):*
> ```
> statement error pgcode 2BP01 could not remove enum value "a" as it is being used in the partitioning of index tbl@idx
> alter type t drop value 'a';
> ```

nit: can we add a statement that successfully drops 'c' here?
___
*[pkg/sql/database_region_change_finalizer.go, line 125 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/68257#-Mfs6s3UAAhQEhP_1JXl:-Mfs6s3UAAhQEhP_1JXm:bbvoa30) ([raw file](https://github.com/cockroachdb/cockroach/blob/e4ac9f8071ed6f2253314cfbd2ac178e5352b86d/pkg/sql/database_region_change_finalizer.go#L125)):*
> ```Go
> // advance of the type descriptor change, to ensure that the table and type
> // descriptors never become incorrect (from a query perspective). For more info,
> // see the caller. The function does not actually write anything changes to the
> ```

I'm probably missing something, but doesn't the `txn.Run` at the bottom write the changes to the store?
___
*[pkg/sql/database_region_change_finalizer.go, line 174 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/68257#-MfsXudjARktetFYZVnt:-MfsXudjARktetFYZVnu:b-dtwk83) ([raw file](https://github.com/cockroachdb/cockroach/blob/19fcb54233761729531aa6c3e84894d0989fa8b5/pkg/sql/database_region_change_finalizer.go#L174)):*
> ```
> Note that even if the caller does write
> // the returned descriptors, the mutable copies of the descriptor in the
> // collection has been modified and is being returned. 
> ```

I don't think I fully understand this part of the comment. I see what you're doing by calling this method and injecting the returned descriptors as synthetic descriptors, and why, but what I'm missing is how changing the underlying mutable copies fits into this whole thing. Could you explain the initial portion of this comment for my edification? 
___
*[pkg/sql/type_change.go, line 1020 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/68257#-MfsR3V4DEShjC8hN7MS:-MfsR3V4DEShjC8hN7MT:bsrp4qm) ([raw file](https://github.com/cockroachdb/cockroach/blob/19fcb54233761729531aa6c3e84894d0989fa8b5/pkg/sql/type_change.go#L1020)):*
> ```Go
> 		return nil
> 	}
> 	if err := partitioning.ForEachList(func(name string, values [][]byte, subPartitioning catalog.Partitioning) (err error) {
> ```

nit: long line

**Review by ajwerner — COMMENTED** [review]
TFTR! I generally added some more commentary

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/68257#-:-MfseuOPAbh9TY4EzzSY:b-ebr36q)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @arulajmani, @otan, and @postamar)

___
*[pkg/ccl/logictestccl/testdata/logic_test/partitioning_enum, line 91 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/68257#-MfrzG6HALFnZnTXxBZw:-Mfsb6T48QKnuRG45-OV:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/10440e3998179abb0d72ffc2341191111251d518/pkg/ccl/logictestccl/testdata/logic_test/partitioning_enum#L91)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

nit: can we add a statement that successfully drops 'c' here?
</blockquote></details>

Done.
___
*[pkg/sql/database_region_change_finalizer.go, line 125 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/68257#-Mfs6s3UAAhQEhP_1JXl:-Mfsb7w3AiElnlCrOVd4:b-emf6q8) ([raw file](https://github.com/cockroachdb/cockroach/blob/e4ac9f8071ed6f2253314cfbd2ac178e5352b86d/pkg/sql/database_region_change_finalizer.go#L125)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

I'm probably missing something, but doesn't the `txn.Run` at the bottom write the changes to the store?
</blockquote></details>

Whoops, stale comment. It's now `repartitionRegionalByRowTables` which does no writes. Updated.
___
*[pkg/sql/database_region_change_finalizer.go, line 174 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/68257#-MfsXudjARktetFYZVnt:-Mfsc5UZ1tUYVUkGrt5P:bf0u27e) ([raw file](https://github.com/cockroachdb/cockroach/blob/19fcb54233761729531aa6c3e84894d0989fa8b5/pkg/sql/database_region_change_finalizer.go#L174)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

> ```
> Note that even if the caller does write
> // the returned descriptors, the mutable copies of the descriptor in the
> // collection has been modified and is being returned. 
> ```

I don't think I fully understand this part of the comment. I see what you're doing by calling this method and injecting the returned descriptors as synthetic descriptors, and why, but what I'm missing is how changing the underlying mutable copies fits into this whole thing. Could you explain the initial portion of this comment for my edification? 
</blockquote></details>

I added more commentary. 
___
*[pkg/sql/type_change.go, line 1020 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/68257#-MfsR3V4DEShjC8hN7MS:-MfscKX3-pYkdynrTjBx:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/19fcb54233761729531aa6c3e84894d0989fa8b5/pkg/sql/type_change.go#L1020)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

nit: long line
</blockquote></details>

Done.

**Review by arulajmani — COMMENTED** [review]
The new commentary made me smile :100: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/68257#-:-MfswUOm8PQYUno1hmrv:brr7h91)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @arulajmani, @otan, and @postamar)

**Comment by ajwerner** [comment]
TFTR!

bors r+

**Comment by otan** [comment]
multi-region backups seem very flaky atm
* https://teamcity.cockroachdb.com/viewLog.html?buildId=3260532&tab=buildResultsDiv&buildTypeId=Cockroach_UnitTests_BazelUnitTests
* https://github.com/cockroachdb/cockroach/issues/68395
* https://github.com/cockroachdb/cockroach/issues/68341

due to
```
expected "could not remove enum value \"a\" as it is being used in the partitioning of index tbl@idx", but no error occurred
```

wonder if it's because of this PR

**Comment by ajwerner** [comment]
Will investigate
