### PR TITLE
roachtest: assign adminui ports dynamically for virtual clusters

### LINKED ISSUE #117149: roachtest: acceptance/gossip/restart-node-one failed
roachtest.acceptance/gossip/restart-node-one [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/13326663?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/13326663?buildTab=artifacts#/acceptance/gossip/restart-node-one) on master @ [c316d6a615fa02a05357a20bf03b8a197ab27810](https://github.com/cockroachdb/cockroach/commits/c316d6a615fa02a05357a20bf03b8a197ab27810):

```
(gossip.go:237).checkConnectedAndFunctional: failed to get gossip status from node 1: Get "http://104.196.154.187:26258/_status/gossip/local": dial tcp 104.196.154.187:26258: connect: connection refused
test artifacts and logs in: /artifacts/acceptance/gossip/restart-node-one/run_1
```

Parameters:
 - <code>ROACHTEST_arch=amd64</code>
 - <code>ROACHTEST_cloud=gce</code>
 - <code>ROACHTEST_coverageBuild=false</code>
 - <code>ROACHTEST_cpu=4</code>
 - <code>ROACHTEST_encrypted=false</code>
 - <code>ROACHTEST_fs=ext4</code>
 - <code>ROACHTEST_localSSD=true</code>
 - <code>ROACHTEST_metamorphicBuild=false</code>
 - <code>ROACHTEST_ssd=0</code>
<details><summary>Help</summary>
<p>

See: [roachtest README](https://github.com/cockroachdb/cockroach/blob/master/pkg/cmd/roachtest/README.md)

See: [How To Investigate \(internal\)](https://cockroachlabs.atlassian.net/l/c/SSSBr8c7)

See: [Grafana](https://go.crdb.dev/roachtest-grafana/teamcity-13326663/acceptance-gossip-restart-node-one/1703831685272/1703831900017)

</p>
</details>
/cc @cockroachdb/kv-triage
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*acceptance/gossip/restart-node-one.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)
</sub>

Jira issue: CRDB-35005

### LINKED ISSUE #117150: roachtest: multitenant/distsql failed with bad tls certificate
roachtest.multitenant/distsql/instances=20/bundle=off/timeout=0 [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/13326663?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/13326663?buildTab=artifacts#/multitenant/distsql/instances=20/bundle=off/timeout=0) on master @ [c316d6a615fa02a05357a20bf03b8a197ab27810](https://github.com/cockroachdb/cockroach/commits/c316d6a615fa02a05357a20bf03b8a197ab27810):

```
(cluster.go:2036).StartServiceForVirtualCluster: COMMAND_PROBLEM: exit status 1
test artifacts and logs in: /artifacts/multitenant/distsql/instances=20/bundle=off/timeout=0/run_1
```

Parameters:
 - <code>ROACHTEST_arch=amd64</code>
 - <code>ROACHTEST_cloud=gce</code>
 - <code>ROACHTEST_coverageBuild=false</code>
 - <code>ROACHTEST_cpu=4</code>
 - <code>ROACHTEST_encrypted=false</code>
 - <code>ROACHTEST_metamorphicBuild=false</code>
 - <code>ROACHTEST_ssd=0</code>
<details><summary>Help</summary>
<p>

See: [roachtest README](https://github.com/cockroachdb/cockroach/blob/master/pkg/cmd/roachtest/README.md)

See: [How To Investigate \(internal\)](https://cockroachlabs.atlassian.net/l/c/SSSBr8c7)

See: [Grafana](https://go.crdb.dev/roachtest-grafana/teamcity-13326663/multitenant-distsql-instances-20-bundle-off-timeout-0/1703832679884/1703832861452)

</p>
</details>
/cc @cockroachdb/sql-queries
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*multitenant/distsql/instances=20/bundle=off/timeout=0.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)
</sub>

Jira issue: CRDB-35006

### PR DESCRIPTION
**Pull request by DarrylWong**
This was originally removed in #115599 due to #114097 merging, but adminui was reverted in #117141 and mistakenly did not revert the special case for virtual clusters. We unskip the multitenant/distsql tests as well.

Release note: None
Fixes: #117150
Fixes: #117149
Epic: None

### CODE REVIEW

**Comment by DarrylWong** [comment]
[multitenant/distsql test runs](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/13454681?hideProblemsFromDependencies=false&hideTestsFromDependencies=false)

**Comment by renatolabs** [comment]
LGTM, but probably worth waiting for #117480 to merge and then unskip those tests in this PR.

File: pkg/cmd/roachtest/tests/gossip.go [hunk 1]
```diff
@@ -338,7 +339,13 @@ func runGossipRestartNodeOne(ctx context.Context, t test.Test, c cluster.Cluster
 	settings := install.MakeClusterSettings(install.NumRacksOption(c.Spec().NodeCount))
 	settings.Env = append(settings.Env, "COCKROACH_SCAN_MAX_IDLE_TIME=5ms")
 
-	c.Start(ctx, t.L(), option.DefaultStartOpts(), settings)
+	// TODO(darrylwong): remove SetDefaultSQLPort once #117125 is addressed.
```
Comment (srosenberg) [inline pkg/cmd/roachtest/tests/gossip.go:342]: Given the below assumption, is the TODO still relevant? i.e., if I understood correctly, this test fails if the invariant `adminUIPort = SQLPort + 1` doesn't hold, right?

**Review by srosenberg — APPROVED** [review]
Thanks!

File: pkg/cmd/roachtest/tests/gossip.go (hunk 1 above)
Comment (DarrylWong) [reply pkg/cmd/roachtest/tests/gossip.go:342]: Yeah that's true, if we change the port assignment logic then it will fail again.

I changed it to discover the port instead, which seems more correct to me anyway.

File: pkg/cmd/roachtest/cluster.go [hunk 2]
```diff
@@ -2490,6 +2490,12 @@ func (c *clusterImpl) ExternalAdminUIAddr(
 	return c.adminUIAddr(ctx, l, node, true)
 }
 
+func (c *clusterImpl) AdminUIPort(
```
Comment (renatolabs) [inline pkg/cmd/roachtest/cluster.go:2493]: Nit: Maybe `AdminUIPorts`, since this is returning an array of ports?

File: pkg/cmd/roachtest/cluster.go [hunk 3]
```diff
@@ -2490,6 +2490,12 @@ func (c *clusterImpl) ExternalAdminUIAddr(
...
+	ctx context.Context, l *logger.Logger, node option.NodeListOption,
```
Comment (renatolabs) [inline pkg/cmd/roachtest/cluster.go:2494]: `nodes`, since that argument is a collection?

File: pkg/roachprod/roachprod.go [hunk 4]
```diff
@@ -1074,6 +1074,28 @@ func AdminURL(
 	return urlGenerator(ctx, c, l, c.TargetNodes(), uConfig)
 }
 
+// AdminPort finds the AdminUI ports for a cluster.
+func AdminPort(
```
Comment (renatolabs) [inline pkg/roachprod/roachprod.go:1078]: Nit: plural here too.

File: pkg/roachprod/roachprod.go [hunk 5]
```diff
@@ -1074,6 +1074,28 @@ func AdminURL(
...
+	}
+	c, err := newCluster(l, clusterName, install.SecureOption(secure))
+	if err != nil {
+		return nil, err
+	}
+	var ports []int
+	for _, node := range c.Nodes {
+		port, err := c.NodeUIPort(ctx, node)
+		if err != nil {
+			return nil, err
```
Comment (renatolabs) [inline pkg/roachprod/roachprod.go:1092]: Nit: might be a good idea to include the `node` in the error message.

**Review by renatolabs — APPROVED** [review]
Thanks for the fix! Left small suggestions.

File: pkg/cmd/roachtest/cluster.go [hunk 6]
```diff
@@ -2490,6 +2490,12 @@ func (c *clusterImpl) ExternalAdminUIAddr(
...
+) ([]int, error) {
+	return roachprod.AdminPort(ctx, l, c.MakeNodes(node), c.localCertsDir != "")
```
Comment (renatolabs) [inline pkg/cmd/roachtest/cluster.go:2496]: We can use `c.IsSecure()` here.

**Comment by DarrylWong** [comment]
TFTRs

bors r=srosenberg, renatolabs

**Comment by yuzefovich** [comment]
blathers backport 23.2

**Comment by DarrylWong** [comment]
blathers backport 23.1

**Comment by DarrylWong** [comment]
blathers backport 23.1
