### PR TITLE
roachtest: fix task manager race

### LINKED ISSUE #134302: cmd/roachtest: TestRunnerTestTimeout failed
cmd/roachtest.TestRunnerTestTimeout [failed](https://tanzanite.cluster.engflow.com/invocations/default/a664d1bf-f30d-4b79-afa3-4cbd3d2a1187?testReportRun=1&testReportShard=1&testReportAttempt=1#targets-Ly9wa2cvY21kL3JvYWNodGVzdDpyb2FjaHRlc3RfdGVzdA==) on master @ [e8f6410ecd99591fd6103dd8461ea3fb0361f8d6](https://github.com/cockroachdb/cockroach/commits/e8f6410ecd99591fd6103dd8461ea3fb0361f8d6):

```
      GOROOT/src/runtime/panic.go:602 +0x5d
  github.com/cockroachdb/cockroach/pkg/cmd/roachtest.(*testRunner).runTest()
      pkg/cmd/roachtest/test_runner.go:1379 +0x1dcf
  github.com/cockroachdb/cockroach/pkg/cmd/roachtest.(*testRunner).runWorker()
      pkg/cmd/roachtest/test_runner.go:925 +0x38e4
  github.com/cockroachdb/cockroach/pkg/cmd/roachtest.(*testRunner).Run.func1()
      pkg/cmd/roachtest/test_runner.go:389 +0x5ba
  github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunAsyncTaskEx.func2()
      pkg/util/stop/stopper.go:498 +0x338
  github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunAsyncTaskEx.gowrap1()
      pkg/util/stop/stopper.go:499 +0x4f

Previous write at 0x00c00302c940 by goroutine 657:
  github.com/cockroachdb/cockroach/pkg/cmd/roachtest/roachtestutil/task.(*manager).GoWithCancel()
      pkg/cmd/roachtest/roachtestutil/task/manager.go:117 +0x7a4
  github.com/cockroachdb/cockroach/pkg/cmd/roachtest.(*testImpl).GoWithCancel()
      pkg/cmd/roachtest/test_impl.go:664 +0x1d2
  github.com/cockroachdb/cockroach/pkg/cmd/roachtest.(*testImpl).Go()
      pkg/cmd/roachtest/test_impl.go:669 +0x10c
  github.com/cockroachdb/cockroach/pkg/cmd/roachtest.TestRunnerTestTimeout.func1()
      pkg/cmd/roachtest/test_test.go:330 +0x67
  github.com/cockroachdb/cockroach/pkg/cmd/roachtest.(*testRunner).runTest.func2()
      pkg/cmd/roachtest/test_runner.go:1290 +0x1c4

Goroutine 656 (running) created at:
  github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunAsyncTaskEx()
      pkg/util/stop/stopper.go:488 +0x785
  github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunAsyncTask()
      pkg/util/stop/stopper.go:359 +0x15a4
  github.com/cockroachdb/cockroach/pkg/cmd/roachtest.(*testRunner).Run()
      pkg/cmd/roachtest/test_runner.go:378 +0x113f
  github.com/cockroachdb/cockroach/pkg/cmd/roachtest.TestRunnerTestTimeout()
      pkg/cmd/roachtest/test_test.go:341 +0x806
  testing.tRunner()
      GOROOT/src/testing/testing.go:1689 +0x21e
  testing.(*T).Run.gowrap1()
      GOROOT/src/testing/testing.go:1742 +0x44

Goroutine 657 (running) created at:
  github.com/cockroachdb/cockroach/pkg/cmd/roachtest.(*testRunner).runTest()
      pkg/cmd/roachtest/test_runner.go:1274 +0x1015
  github.com/cockroachdb/cockroach/pkg/cmd/roachtest.(*testRunner).runWorker()
      pkg/cmd/roachtest/test_runner.go:925 +0x38e4
  github.com/cockroachdb/cockroach/pkg/cmd/roachtest.(*testRunner).Run.func1()
      pkg/cmd/roachtest/test_runner.go:389 +0x5ba
  github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunAsyncTaskEx.func2()
      pkg/util/stop/stopper.go:498 +0x338
  github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunAsyncTaskEx.gowrap1()
      pkg/util/stop/stopper.go:499 +0x4f
==================
```

Parameters:
 - <code>attempt=1</code>
 - <code>race=true</code>
 - <code>run=1</code>
 - <code>shard=1</code>
<details><summary>Help</summary>
<p>

See also: [How To Investigate a Go Test Failure \(internal\)](https://cockroachlabs.atlassian.net/l/c/HgfXfJgM)
</p>
</details>
/cc @cockroachdb/test-eng
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*TestRunnerTestTimeout.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/bazci/githubpost/issues)

</sub>

Jira issue: CRDB-44013

### PR DESCRIPTION
**Pull request by herkolategan**
Previously, the cancel function slice was not wrapped in a mutex, leading to possible concurrent access. This change adds a mutex.

Fixes: #134302
Informs: #133263

Epic: None
Release note: None

### CODE REVIEW

File: pkg/cmd/roachtest/test_test.go [hunk 1]
```diff
@@ -315,19 +315,21 @@ func TestRunnerTestTimeout(t *testing.T) {
...
 	}
-	numTasks := 3
+
+	var tasksStarted atomic.Uint32
 	var tasksDone atomic.Uint32
 	test := registry.TestSpec{
 		Name:             `timeout`,
 		Owner:            OwnerUnitTest,
-		Timeout:          10 * time.Millisecond,
+		Timeout:          100 * time.Millisecond,
```
Comment (srosenberg) [inline pkg/cmd/roachtest/test_test.go:324]: Seems kinda arbitrary? Why not use a waitgroup to ensure all three tasks are started before testing the timeout in `runner.Run`? In that case, the actual `Timeout` value can be set artificially low.

Comment (herkolategan) [reply pkg/cmd/roachtest/test_test.go]: Updated, to use a channel to ensure tasks are started.

File: pkg/cmd/roachtest/test_test.go [hunk 2]
```diff
@@ -316,6 +316,7 @@ func TestRunnerTestTimeout(t *testing.T) {
 		debugMode: NoDebug,
 	}
 	numTasks := 3
+	startedTasks := make(chan struct{})
```
Comment (srosenberg) [inline pkg/cmd/roachtest/test_test.go:319]: Nit: `startedAllTasks`

**Review by srosenberg — APPROVED** [review]

**Review by DarrylWong — APPROVED** [review]

**Comment by herkolategan** [comment]
Just waiting on extended to be sure, then I'll merge.

**Comment by herkolategan** [comment]
TFTRs!

bors r=srosenberg,DarrylWong
