### PR TITLE
kvserver/rangefeed: lift CrdbTestBuild on RangefeedUseBufferedSender

### LINKED ISSUE #141465: roachtest: change-replicas/mixed-version failed
**Note:** This build has runtime assertions enabled. If the same failure was hit in a run without assertions enabled, there should be a similar failure without this message. If there isn&#39;t one, then this failure is likely due to an assertion violation or (assertion) timeout.

roachtest.change-replicas/mixed-version [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyAzureBazel/18833218?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyAzureBazel/18833218?buildTab=artifacts#/change-replicas/mixed-version) on master @ [22b262749c502d07ec7ccec5b76abd67c361ae4d](https://github.com/cockroachdb/cockroach/commits/22b262749c502d07ec7ccec5b76abd67c361ae4d):

```
(mixedversion.go:804).Run: mixed-version test failure while running step 2 (start cluster at version "v25.1.0-rc.1"): COMMAND_PROBLEM: exit status 1 [owner=test-eng]
test artifacts and logs in: /artifacts/change-replicas/mixed-version/run_1
```

Parameters:
 - <code>arch=amd64</code>
 - <code>cloud=azure</code>
 - <code>coverageBuild=false</code>
 - <code>cpu=4</code>
 - <code>encrypted=false</code>
 - <code>metamorphicBufferedSender=true</code>
 - <code>mvtDeploymentMode=shared-process</code>
 - <code>mvtVersions=v25.1.0-rc.1 → master</code>
 - <code>runtimeAssertionsBuild=true</code>
 - <code>ssd=0</code>
<details><summary>Help</summary>
<p>

See: [roachtest README](https://github.com/cockroachdb/cockroach/blob/master/pkg/cmd/roachtest/README.md)

See: [How To Investigate \(internal\)](https://cockroachlabs.atlassian.net/l/c/SSSBr8c7)

_Grafana is not yet available for azure clusters_</p>
</details>
<details><summary>Same failure on other branches</summary>
<p>

- #136441 roachtest: change-replicas/mixed-version failed [C-test-failure O-roachtest O-robot branch-release-23.1 release-blocker]
</p>
</details>
/cc @cockroachdb/test-eng
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*change-replicas/mixed-version.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/bazci/githubpost/issues)

</sub>

Jira issue: CRDB-47834

### LINKED ISSUE #141466: roachtest: import/mixed-versions failed
**Note:** This build has runtime assertions enabled. If the same failure was hit in a run without assertions enabled, there should be a similar failure without this message. If there isn&#39;t one, then this failure is likely due to an assertion violation or (assertion) timeout.

roachtest.import/mixed-versions [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyAzureBazel/18833218?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyAzureBazel/18833218?buildTab=artifacts#/import/mixed-versions) on master @ [22b262749c502d07ec7ccec5b76abd67c361ae4d](https://github.com/cockroachdb/cockroach/commits/22b262749c502d07ec7ccec5b76abd67c361ae4d):

```
(mixedversion.go:804).Run: mixed-version test failure while running step 1 (start cluster at version "v23.2.20"): COMMAND_PROBLEM: exit status 1 [owner=test-eng]
test artifacts and logs in: /artifacts/import/mixed-versions/run_1
```

Parameters:
 - <code>arch=amd64</code>
 - <code>cloud=azure</code>
 - <code>coverageBuild=false</code>
 - <code>cpu=4</code>
 - <code>encrypted=false</code>
 - <code>metamorphicBufferedSender=true</code>
 - <code>mvtDeploymentMode=shared-process</code>
 - <code>mvtVersions=v23.2.20 → v24.1.12 → v24.3.5 → v25.1.0-rc.1 → master</code>
 - <code>runtimeAssertionsBuild=true</code>
 - <code>ssd=0</code>
<details><summary>Help</summary>
<p>

See: [roachtest README](https://github.com/cockroachdb/cockroach/blob/master/pkg/cmd/roachtest/README.md)

See: [How To Investigate \(internal\)](https://cockroachlabs.atlassian.net/l/c/SSSBr8c7)

_Grafana is not yet available for azure clusters_</p>
</details>
/cc @cockroachdb/test-eng
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*import/mixed-versions.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/bazci/githubpost/issues)

</sub>

Jira issue: CRDB-47835

### LINKED ISSUE #141470: roachtest: schemachange/mixed-versions failed
**Note:** This build has runtime assertions enabled. If the same failure was hit in a run without assertions enabled, there should be a similar failure without this message. If there isn&#39;t one, then this failure is likely due to an assertion violation or (assertion) timeout.

roachtest.schemachange/mixed-versions [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/18833207?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/18833207?buildTab=artifacts#/schemachange/mixed-versions) on master @ [22b262749c502d07ec7ccec5b76abd67c361ae4d](https://github.com/cockroachdb/cockroach/commits/22b262749c502d07ec7ccec5b76abd67c361ae4d):

```
(mixedversion.go:804).Run: mixed-version test failure while running step 2 (start cluster at version "v25.1.0-rc.1"): COMMAND_PROBLEM: exit status 1 [owner=test-eng]
test artifacts and logs in: /artifacts/schemachange/mixed-versions/run_1
```

Parameters:
 - <code>arch=amd64</code>
 - <code>cloud=gce</code>
 - <code>coverageBuild=false</code>
 - <code>cpu=4</code>
 - <code>encrypted=false</code>
 - <code>metamorphicBufferedSender=true</code>
 - <code>mvtDeploymentMode=separate-process</code>
 - <code>mvtVersions=v25.1.0-rc.1 → master</code>
 - <code>runtimeAssertionsBuild=true</code>
 - <code>ssd=0</code>
<details><summary>Help</summary>
<p>

See: [roachtest README](https://github.com/cockroachdb/cockroach/blob/master/pkg/cmd/roachtest/README.md)

See: [How To Investigate \(internal\)](https://cockroachlabs.atlassian.net/l/c/SSSBr8c7)

See: [Grafana](https://go.crdb.dev/roachtest-grafana/teamcity-18833207/schemachange-mixed-versions/1739517978425/1739518134760)

</p>
</details>
<details><summary>Same failure on other branches</summary>
<p>

- #141469 roachtest: schemachange/mixed-versions failed [B-runtime-assertions-enabled C-test-failure O-roachtest O-robot T-sql-foundations branch-release-25.1.0-rc release-blocker]
</p>
</details>
/cc @cockroachdb/test-eng
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*schemachange/mixed-versions.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/bazci/githubpost/issues)

</sub>

Jira issue: CRDB-47839

### LINKED ISSUE #141471: roachtest: validate-system-schema-after-version-upgrade/separate-process failed
**Note:** This build has runtime assertions enabled. If the same failure was hit in a run without assertions enabled, there should be a similar failure without this message. If there isn&#39;t one, then this failure is likely due to an assertion violation or (assertion) timeout.

roachtest.validate-system-schema-after-version-upgrade/separate-process [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/18833207?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/18833207?buildTab=artifacts#/validate-system-schema-after-version-upgrade/separate-process) on master @ [22b262749c502d07ec7ccec5b76abd67c361ae4d](https://github.com/cockroachdb/cockroach/commits/22b262749c502d07ec7ccec5b76abd67c361ae4d):

```
(mixedversion.go:804).Run: mixed-version test failure while running step 1 (start cluster at version "v24.3.1"): COMMAND_PROBLEM: exit status 1 [owner=test-eng]
test artifacts and logs in: /artifacts/validate-system-schema-after-version-upgrade/separate-process/run_1
```

Parameters:
 - <code>arch=amd64</code>
 - <code>cloud=gce</code>
 - <code>coverageBuild=false</code>
 - <code>cpu=4</code>
 - <code>encrypted=false</code>
 - <code>metamorphicBufferedSender=true</code>
 - <code>mvtDeploymentMode=separate-process</code>
 - <code>mvtVersions=v24.3.1 → v25.1.0-rc.1 → master</code>
 - <code>runtimeAssertionsBuild=true</code>
 - <code>ssd=0</code>
<details><summary>Help</summary>
<p>

See: [roachtest README](https://github.com/cockroachdb/cockroach/blob/master/pkg/cmd/roachtest/README.md)

See: [How To Investigate \(internal\)](https://cockroachlabs.atlassian.net/l/c/SSSBr8c7)

See: [Grafana](https://go.crdb.dev/roachtest-grafana/teamcity-18833207/validate-system-schema-after-version-upgrade-separate-process/1739518536921/1739518683800)

</p>
</details>
/cc @cockroachdb/test-eng
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*validate-system-schema-after-version-upgrade/separate-process.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/bazci/githubpost/issues)

</sub>

Jira issue: CRDB-47840

### LINKED ISSUE #141475: roachtest: rebalance/by-load/replicas/mixed-version failed
**Note:** This build has runtime assertions enabled. If the same failure was hit in a run without assertions enabled, there should be a similar failure without this message. If there isn&#39;t one, then this failure is likely due to an assertion violation or (assertion) timeout.

roachtest.rebalance/by-load/replicas/mixed-version [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyAzureBazel/18833218?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyAzureBazel/18833218?buildTab=artifacts#/rebalance/by-load/replicas/mixed-version) on master @ [22b262749c502d07ec7ccec5b76abd67c361ae4d](https://github.com/cockroachdb/cockroach/commits/22b262749c502d07ec7ccec5b76abd67c361ae4d):

```
(mixedversion.go:804).Run: mixed-version test failure while running step 1 (start cluster at version "v23.2.20"): COMMAND_PROBLEM: exit status 1 [owner=test-eng]
test artifacts and logs in: /artifacts/rebalance/by-load/replicas/mixed-version/run_1
```

Parameters:
 - <code>arch=amd64</code>
 - <code>cloud=azure</code>
 - <code>coverageBuild=false</code>
 - <code>cpu=4</code>
 - <code>encrypted=false</code>
 - <code>fs=ext4</code>
 - <code>localSSD=true</code>
 - <code>metamorphicBufferedSender=true</code>
 - <code>mvtDeploymentMode=shared-process</code>
 - <code>mvtVersions=v23.2.20 → v24.1.12 → v24.3.5 → v25.1.0-rc.1 → master</code>
 - <code>runtimeAssertionsBuild=true</code>
 - <code>ssd=0</code>
<details><summary>Help</summary>
<p>

See: [roachtest README](https://github.com/cockroachdb/cockroach/blob/master/pkg/cmd/roachtest/README.md)

See: [How To Investigate \(internal\)](https://cockroachlabs.atlassian.net/l/c/SSSBr8c7)

_Grafana is not yet available for azure clusters_</p>
</details>
/cc @cockroachdb/test-eng
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*rebalance/by-load/replicas/mixed-version.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/bazci/githubpost/issues)

</sub>

Jira issue: CRDB-47844

### LINKED ISSUE #141476: roachtest: sql-stats/mixed-version failed
**Note:** This build has runtime assertions enabled. If the same failure was hit in a run without assertions enabled, there should be a similar failure without this message. If there isn&#39;t one, then this failure is likely due to an assertion violation or (assertion) timeout.

roachtest.sql-stats/mixed-version [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyAzureBazel/18833218?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyAzureBazel/18833218?buildTab=artifacts#/sql-stats/mixed-version) on master @ [22b262749c502d07ec7ccec5b76abd67c361ae4d](https://github.com/cockroachdb/cockroach/commits/22b262749c502d07ec7ccec5b76abd67c361ae4d):

```
(mixedversion.go:804).Run: mixed-version test failure while running step 2 (start cluster at version "v24.3.4"): COMMAND_PROBLEM: exit status 1 [owner=test-eng]
test artifacts and logs in: /artifacts/sql-stats/mixed-version/run_1
```

Parameters:
 - <code>arch=amd64</code>
 - <code>cloud=azure</code>
 - <code>coverageBuild=false</code>
 - <code>cpu=4</code>
 - <code>encrypted=false</code>
 - <code>fs=ext4</code>
 - <code>localSSD=true</code>
 - <code>metamorphicBufferedSender=true</code>
 - <code>mvtDeploymentMode=system-only</code>
 - <code>mvtVersions=v24.3.4 → v25.1.0-rc.1 → master</code>
 - <code>runtimeAssertionsBuild=true</code>
 - <code>ssd=0</code>
<details><summary>Help</summary>
<p>

See: [roachtest README](https://github.com/cockroachdb/cockroach/blob/master/pkg/cmd/roachtest/README.md)

See: [How To Investigate \(internal\)](https://cockroachlabs.atlassian.net/l/c/SSSBr8c7)

_Grafana is not yet available for azure clusters_</p>
</details>
<details><summary>Same failure on other branches</summary>
<p>

- #141418 roachtest: sql-stats/mixed-version failed [C-test-failure O-roachtest O-robot T-testeng branch-release-24.3 release-blocker]
</p>
</details>
/cc @cockroachdb/test-eng
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*sql-stats/mixed-version.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/bazci/githubpost/issues)

</sub>

Jira issue: CRDB-47845

### LINKED ISSUE #141478: roachtest: tpcc/mixed-headroom/n5cpu16 failed
**Note:** This build has runtime assertions enabled. If the same failure was hit in a run without assertions enabled, there should be a similar failure without this message. If there isn&#39;t one, then this failure is likely due to an assertion violation or (assertion) timeout.

roachtest.tpcc/mixed-headroom/n5cpu16 [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyAzureBazel/18833218?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyAzureBazel/18833218?buildTab=artifacts#/tpcc/mixed-headroom/n5cpu16) on master @ [22b262749c502d07ec7ccec5b76abd67c361ae4d](https://github.com/cockroachdb/cockroach/commits/22b262749c502d07ec7ccec5b76abd67c361ae4d):

```
(mixedversion.go:804).Run: mixed-version test failure while running step 2 (start cluster at version "v25.1.0-rc.1"): COMMAND_PROBLEM: exit status 1 [owner=test-eng]
test artifacts and logs in: /artifacts/tpcc/mixed-headroom/n5cpu16/run_1
```

Parameters:
 - <code>arch=amd64</code>
 - <code>cloud=azure</code>
 - <code>coverageBuild=false</code>
 - <code>cpu=16</code>
 - <code>encrypted=false</code>
 - <code>fs=ext4</code>
 - <code>localSSD=true</code>
 - <code>metamorphicBufferedSender=true</code>
 - <code>mvtDeploymentMode=system-only</code>
 - <code>mvtVersions=v25.1.0-rc.1 → master</code>
 - <code>runtimeAssertionsBuild=true</code>
 - <code>ssd=0</code>
<details><summary>Help</summary>
<p>

See: [roachtest README](https://github.com/cockroachdb/cockroach/blob/master/pkg/cmd/roachtest/README.md)

See: [How To Investigate \(internal\)](https://cockroachlabs.atlassian.net/l/c/SSSBr8c7)

_Grafana is not yet available for azure clusters_</p>
</details>
<details><summary>Same failure on other branches</summary>
<p>

- #140059 roachtest: tpcc/mixed-headroom/n5cpu16 failed [B-runtime-assertions-enabled C-test-failure O-roachtest O-robot T-testeng branch-release-24.3]
</p>
</details>
/cc @cockroachdb/test-eng
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*tpcc/mixed-headroom/n5cpu16.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/bazci/githubpost/issues)

</sub>

Jira issue: CRDB-47847

### LINKED ISSUE #141494: roachtest: ldr/mixed-version failed
**Note:** This build has runtime assertions enabled. If the same failure was hit in a run without assertions enabled, there should be a similar failure without this message. If there isn&#39;t one, then this failure is likely due to an assertion violation or (assertion) timeout.

roachtest.ldr/mixed-version [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/18833207?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/18833207?buildTab=artifacts#/ldr/mixed-version) on master @ [22b262749c502d07ec7ccec5b76abd67c361ae4d](https://github.com/cockroachdb/cockroach/commits/22b262749c502d07ec7ccec5b76abd67c361ae4d):

```
(mixedversion.go:804).Run: left: mixed-version test failure while running step 2 (start cluster at version "v25.1.0-rc.1"): COMMAND_PROBLEM: exit status 1 [owner=test-eng]
(mixedversion.go:804).Run: right: creating store-dir: context canceled [owner=test-eng]
test artifacts and logs in: /artifacts/ldr/mixed-version/run_1
```

Parameters:
 - <code>arch=amd64</code>
 - <code>cloud=gce</code>
 - <code>coverageBuild=false</code>
 - <code>cpu=4</code>
 - <code>encrypted=false</code>
 - <code>fs=ext4</code>
 - <code>localSSD=true</code>
 - <code>metamorphicBufferedSender=true</code>
 - <code>mvtDeploymentMode=system-only</code>
 - <code>mvtVersions=v25.1.0-rc.1 → master</code>
 - <code>runtimeAssertionsBuild=true</code>
 - <code>ssd=0</code>
<details><summary>Help</summary>
<p>

See: [roachtest README](https://github.com/cockroachdb/cockroach/blob/master/pkg/cmd/roachtest/README.md)

See: [How To Investigate \(internal\)](https://cockroachlabs.atlassian.net/l/c/SSSBr8c7)

See: [Grafana](https://go.crdb.dev/roachtest-grafana/teamcity-18833207/ldr-mixed-version/1739536858577/1739537026444)

</p>
</details>
/cc @cockroachdb/test-eng
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*ldr/mixed-version.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/bazci/githubpost/issues)

</sub>

Jira issue: CRDB-47857

### PR DESCRIPTION
**Pull request by wenyihu6**
**kvserver/rangefeed: lift CrdbTestBuild on RangefeedUseBufferedSender**

This patch removes the buildutil.CRDBTestBuild check for
RangefeedUseBufferedSender, as the feature is now fully
implemented and safe to use without causing panics.

Epic: none
Release note: none

---

**roachtest: use prng to enable RangefeedUseBufferedSender**

Previously, we used UsingRuntimeAssertions to determine whether
to enable RangefeedUseBufferedSender because it was gated behind
the CRDBTestBuild flag. Now that this check has been removed,
we can use prng to enable the cluster setting 50% of the time.

Note that we still need to avoid enabling the cluster setting
for mixed-version roachtests to prevent it from being applied
to versions that enforce this restriction.

Epic: none
Fixes: #141478
Fixes: #141470
Fixes: #141494
Fixes: #141476
FIxes: #141466
Fixes: #141470
Fixes: #141471
Fixes: #141475
Fixes: #141465

### CODE REVIEW

File: pkg/kv/kvserver/replica_proposal.go [hunk 1]
```diff
@@ -893,6 +893,7 @@ func (r *Replica) handleReadWriteLocalEvalResult(ctx context.Context, lResult re
 		// blocks waiting for the lease acquisition to finish but it can't finish
 		// because we're not processing raft messages due to holding
 		// processRaftMu (and running on the processRaft goroutine).
+
```
Comment (stevendanna) [inline pkg/kv/kvserver/replica_proposal.go:896]: Stray whitespace change.

**Review by stevendanna — APPROVED** [review]
LGTM! Thanks!

File: pkg/kv/kvserver/replica_proposal.go (hunk 1 above)
Comment (wenyihu6) [reply pkg/kv/kvserver/replica_proposal.go]: Done.

File: pkg/cmd/roachtest/test_runner.go [hunk 2]
```diff
@@ -931,16 +931,9 @@ func (r *testRunner) runWorker(
...
-				// if buildutil.CrdbTestBuild tag is not set.
-				// 2. There is a 50% chance that the cockroach binary used in roachtests
-				// includes the buildutil.CrdbTestBuild tag. And runtime assertion is
-				// enabled if and only if cockroach binaries used in roachtests include
-				// the buildutil.CrdbTestBuild tag.
-				useBufferedSender := roachtestutil.UsingRuntimeAssertions(t)
-				if useBufferedSender {
+				// default.
+				useBufferedSender := prng.Intn(2) == 0
+				if t.IsBuildVersion("v25.2.0") && useBufferedSender {
```
Comment (DarrylWong) [inline pkg/cmd/roachtest/test_runner.go:936]: Should we do `t.BuildVersion().AtLeast()` instead so this check doesn't break when we bump the version? Although I'm not sure if either check fixes mixed version tests. Unfortunately the build version referred to here doesn't have any knowledge of the  binaries the mixed version frame work uploads, it's essentially just a check on the version the branch is on.

Maybe the correct fix should be for the mixed version framework to ignore `c.clusterSettings`? Seems like that will always break whenever a new setting is added.

Comment (wenyihu6) [reply pkg/cmd/roachtest/test_runner.go:936]: Thanks for taking a look! 

> Should we do t.BuildVersion().AtLeast() instead so this check doesn't break when we bump the version?

https://github.com/cockroachdb/cockroach/blob/3ca9845cc23d325eafd8977d5ce76c68b6ace89d/pkg/cmd/roachtest/test_impl.go#L692 

`t.IsBuildVersion` checks for `AtLeast()`. 

> Unfortunately the build version referred to here doesn't have any knowledge of the binaries the mixed version frame work uploads, it's essentially just a check on the version the branch is on.

You are right. Just noticed this from the failing CI 😢. Will try to look into this further and figure out the next steps.

File: pkg/cmd/roachtest/test_runner.go [hunk 3]
```diff
@@ -931,16 +931,9 @@ func (r *testRunner) runWorker(
...
 				// 50% chance of enabling the rangefeed buffered sender. Disabled by
-				// default. This is the reason we check for run time assertions rather
-				// than using rand:
-				// 1. The cluster setting RangefeedUseBufferedSender validation will fail
-				// if buildutil.CrdbTestBuild tag is not set.
-				// 2. There is a 50% chance that the cockroach binary used in roachtests
-				// includes the buildutil.CrdbTestBuild tag. And runtime assertion is
-				// enabled if and only if cockroach binaries used in roachtests include
-				// the buildutil.CrdbTestBuild tag.
-				useBufferedSender := roachtestutil.UsingRuntimeAssertions(t)
```
Comment (DarrylWong) [inline pkg/cmd/roachtest/test_runner.go:942]: `UsingRuntimeAssertions` was previously gating benchmark tests from enabling buffered sender. We should probably still disable buffered senders on benchmark tests? Unless you expect there to be no performance impact.

Comment (wenyihu6) [reply pkg/cmd/roachtest/test_runner.go:942]: We don’t anticipate any negative performance impact, and it would be good to verify if there’s any regression. If we feel strongly about this, the simplest approach might be to opt into this cluster setting when `registry.MetamorphicLeases` is enabled as that registry.TestSpec tries to achieve the same thing 
https://github.com/cockroachdb/cockroach/commit/fc68b0fe8d967ab48d96a659fd5a067787e5e734.

Comment (DarrylWong) [reply pkg/cmd/roachtest/test_runner.go:942]: My concern is less about negative regressions and more about increased variance in benchmark results. i.e. someone working on improving sysbench perf would need to both know about this metamorphic setting and make sure to conditionally enable/disable it or their results will fluctuate more than expected.

That being said I'm not familiar with this work at all so I'll defer to your judgement if you think the perf impact is minimal.

Comment (wenyihu6) [reply pkg/cmd/roachtest/test_runner.go:942]: I see, that's a good point. I would need to look closer at what the sysbench perf team is analyzing to provide a better answer. I would expect the perf impact to be minimal if the tests they are running don't enable `kv.rangefeed.enabled` but not sure otherwise.

**Review by DarrylWong — APPROVED** [review]

**Comment by wenyihu6** [comment]
TFTR!

bors r=stevendanna, DarrylWong
