### PR TITLE
backupccl: breakup the txn that inserts stats during cluster restore

### LINKED ISSUE #69207: RESTORE: Restoring TableStats is slow/stuck
**Describe the problem**

The restore command is not completing, even after hours of running. 
The database is ~1GB in size, has ~2000 ranges, and ~1000 tables.

**To Reproduce**

Run `restore from 'gs://backups/2021-08-20_1';` on a test node. 

1. The process was taking hours to run. 
2. The “Statments” tab on the UI, it shows that the Execution Count for “INSERT INTO system.table_statistics” is 1M+.
3. The stack trace for the restore command was stuck on the "insertStats" function.

**Expected behavior**
The restore command to finish after 5 minutes.

**Additional data / screenshots**
I deleted the `BACKUP-STATISTICS` file in the backup folder (4.7MB). `RESTORE` now completed successfully after 5 minutes.

**Environment:**
 - CockroachDB version: v21.1.7
 - Server OS: K8s to make a backup, and Docker to restore. 

**Additional context**
What was the impact?
Unable to restore backups. 

I have also created a forum post: https://forum.cockroachlabs.com/t/restore-is-taking-a-long-time/4775

image

gz#9618

### PR DESCRIPTION
**Pull request by adityamaru**
We have seen instances of restores with hundreds of tables getting
stuck on inserting the backed up table stats into the system.table_stats
table on the restoring cluster. Previously, we would issue insert
statements for each table stat row in a single, long-running txn. If this
txn were to be retried a few times, we would observe intent buildup
on the system.table_stats ranges. Once these intents exceeded the
`max_intent_bytes` on the cluster, every subsequent txn retry would fall
back to the much more expensive ranged intent resolution. The only
remedy at this point would be to delete the BACKUP-STATISTICS file from
the bucket where the backup resides, and restore the tables with no
stats, relying on the AUTO STATS job to rebuild them gradually.

This change "batches" the insertion of the table stats to prevent the
above situation.

Fixes: #69207

Release note: None

### CODE REVIEW

**Comment by adityamaru** [comment]
I can add some checkpointing to make sure we only insert table stats once, but that would involve a proto change. I wanted to get yall temperature on backporting this form of the fix.

**Comment by adityamaru** [comment]
Hmmm for a second I thought that breaking up the txn means that we could have a PK collision if the job were to be re-resumed. The stats table has a PK on statsID, tableID, but fortunately, the `InsertNewStat` method does not insert the backed up statsID, and relies on its default `unique_row_id`. So this change is still safe.

File: pkg/ccl/backupccl/backup_test.go [hunk 1]
```diff
@@ -6146,6 +6146,85 @@ func TestBackupHandlesDroppedTypeStatsCollection(t *testing.T) {
...
+	}
+
+	for i, test := range []struct {
+		name          string
+		numTableStats int
+	}{
+		{
+			name:          "less-than-batch-size",
+			numTableStats: 5,
+		},
```
Comment (stevendanna) [inline pkg/ccl/backupccl/backup_test.go:6200]: Might want to test the `numTableStats: 0` case as well.  Although I think that the 0 case doesn't set StatsInserted so the expectations below might need to change for that.

File: pkg/ccl/backupccl/restore_job.go [hunk 2]
```diff
@@ -1805,24 +1805,41 @@ func insertStats(
 		return nil
 	}
 
-	if latestStats == nil {
-		return nil
-	}
+	// We could be restoring hundreds of tables, so insert the new stats in
+	// batches instead of all in a single, long-running txn. This prevents intent
+	// buildup in the face of txn retries.
+	batchSize := 10
```
Comment (stevendanna) [inline pkg/ccl/backupccl/restore_job.go:1811]: I could see moving the `10` out to a package-level constant: `restoreStatsInsertBatchSize`.  If 10 was an arbitrary choice, might be good to say that in the comment as well.

**Review by stevendanna — APPROVED** [review]
Overall it looks good to me.

File: pkg/ccl/backupccl/backup_test.go (hunk 1 above)
Comment (adityamaru) [reply pkg/ccl/backupccl/backup_test.go:6200]: Done!

**Comment by adityamaru** [comment]
TFTR!

bors r=stevendanna

**Comment by NikhilSharma-NS** [comment]
@adityamaru 


FYI :

Bazel CI (Cockroach) — TeamCity build failed

image

**Comment by adityamaru** [comment]
blathers backport 21.2
