### PR TITLE
sql: Allow DEFAULT/ON UPDATE types that can be assignment-cast

### LINKED ISSUE #74854: sql: allow DEFAULT/ON UPDATE types that can be assignment-cast to column type
Postgres allows creating a DEFAULT column expression of a type that is different from the column's type, as long as the type of the DEFAULT expression can be assignment-cast to the column type. CRDB does not currently allow this.

#### Example: [FLOAT4 -> INT4](https://github.com/cockroachdb/cockroach/blob/1c431f06daf63c9ddd9f73adac5e6809026b47a6/pkg/sql/sem/tree/cast.go#L409) casts are allowed in assignment contexts

In Postgres:

```
marcus=# CREATE TABLE t (a INT4 DEFAULT 1.0::FLOAT4);
CREATE TABLE
```

In CRDB:

```
defaultdb> CREATE TABLE t (a INT4 DEFAULT 1.0::FLOAT4);
ERROR: expected DEFAULT expression to have type int4, but '1.0::FLOAT4' has type float4
```

We also support ON UPDATE expressions (which Postgres does not) and these should also allowed to be typed as any type that can be assignment-cast to the column's type.

---

We must take care to disallow altering a column to a type which cannot be assignment-casted from the types of the DEFAULT and ON UPDATE expressions.

#### Example: [FLOAT4 -> BOOL](https://github.com/cockroachdb/cockroach/blob/1c431f06daf63c9ddd9f73adac5e6809026b47a6/pkg/sql/sem/tree/cast.go#L406) casts are NOT allowed in assignment contexts

In Postgres:

```
marcus=# CREATE TABLE t (a INT4 DEFAULT 1.0::FLOAT4);
CREATE TABLE

marcus=# ALTER TABLE t ALTER COLUMN a TYPE BOOL USING a::BOOL;
ERROR:  42804: default for column "a" cannot be cast automatically to type boolean
```

Jira issue: CRDB-12293

### PR DESCRIPTION
**Pull request by e-mbrown**
Resolves #74854

postgres:
```
postgres=# create table casts (b BOOL DEFAULT 'foo'::VARCHAR);
 ERROR:  column "b" is of type boolean but default expression is of type character varying>
HINT:  You will need to rewrite or cast the expression.
```
crdb:
  ```
demo@127.0.0.1:26257/movr> CREATE TABLE t (b BOOL DEFAULT 'foo'::VARCHAR);
CREATE TABLE

Time: 8ms total (execution 8ms / network 0ms)
```

Release note (sql change): A column's DEFAULT/ON UPDATE clause
can now have a type that differs from the column type, as long as
that type can be assignment-cast into the column's type. This
increases our PostgreSQL compatibility.

### CODE REVIEW

**Comment by e-mbrown** [comment]
I noticed this particular solution causes us to support use cases that postgres does not. Not sure if we want to disallow these cases.

File: pkg/sql/logictest/testdata/logic_test/cast [hunk 1]
```diff
@@ -1401,3 +1401,25 @@ select CASE WHEN false THEN 1::REGTYPE ELSE 2::REGNAMESPACE END;
...
+a INT4 DEFAULT 1.0::FLOAT4,
+b VARCHAR DEFAULT 'true'::BOOL,
+c NAME DEFAULT 'foo'::BPCHAR,
+d JSONB DEFAULT 'null'::CHAR,
+)
+
+# Due to cast context we support cases that Postgres doesn't
+statement ok
+CREATE TABLE nonpg_assn_cast (
+a BOOL DEFAULT 'foo',
```
[the remark this answers is not in the document]
Comment (e-mbrown) [reply pkg/sql/logictest/testdata/logic_test/cast]: Just realized the issue was caused by the the default/on update types being the tgttype instead of the srctype.

File: pkg/sql/catalog/tabledesc/table.go [hunk 2]
```diff
@@ -145,13 +146,22 @@ func MakeColumnDefDescs(
...
 		// Verify the default expression type is compatible with the column type
 		// and does not contain invalid functions.
 		ret.DefaultExpr, err = schemaexpr.SanitizeVarFreeExpr(
 			ctx, d.DefaultExpr.Expr, resType, "DEFAULT", semaCtx, volatility.Volatile,
 		)
 		if err != nil {
-			return nil, err
+			// Check if the default expression type can be assignment-cast into the
+			// column type. If it can allow the default and column type to differ.
+			ret.DefaultExpr, innerErr = d.DefaultExpr.Expr.TypeCheck(ctx, semaCtx, types.Any)
```
Comment (mgartner) [inline pkg/sql/catalog/tabledesc/table.go:158]: `schemaexpr.SanitizeVarFreeExpr` above could return an error for reasons other than the expression not matching the column type. For example, it could fail if the expression contains references to other columns. We only want to check if the default expression type can be assignment-cast into the column type if `schemaexpr.SanitizeVarFreeExpr` fails during type-checking. Unfortunately, this isn't easy to do from outside `schemaexpr.SanitizeVarFreeExpr`. One option is to modify `schemaexpr.SanitizeVarFreeExpr` to add a new argument, `allowAssignmentCast bool` and move his assignment-cast logic into the function directly where type-checking fails.

I think you could add a test case for this too, like:

```
CREATE TABLE fail_assn_cast (
  a BOOL,
  b STRING DEFAULT a
)
```

File: pkg/sql/logictest/testdata/logic_test/cast [hunk 3]
```diff
@@ -1401,3 +1401,28 @@ select CASE WHEN false THEN 1::REGTYPE ELSE 2::REGNAMESPACE END;
 select CASE WHEN false THEN 1::REGTYPE ELSE 2::REGPROC END;
 select CASE WHEN false THEN 1::REGTYPE ELSE 2::REGPROCEDURE END;
 select CASE WHEN false THEN 1::REGTYPE ELSE 2::REGROLE END;
+
+
+# Test that default/on update expression differing from column type
```
Comment (mgartner) [inline pkg/sql/logictest/testdata/logic_test/cast:1406]: nit: sentence seems incomplete

File: pkg/sql/logictest/testdata/logic_test/cast [hunk 4]
```diff
@@ -1401,3 +1401,28 @@ select CASE WHEN false THEN 1::REGTYPE ELSE 2::REGNAMESPACE END;
...
+statement ok
+CREATE TABLE def_assn_cast (
+a INT4 DEFAULT 1.0::FLOAT4,
```
Comment (mgartner) [inline pkg/sql/logictest/testdata/logic_test/cast:1409]: nit: indent the lines with column definitions here and below.

File: pkg/sql/catalog/tabledesc/table.go [hunk 5]
```diff
@@ -167,10 +177,20 @@ func MakeColumnDefDescs(
...
 		// Verify the on update expression type is compatible with the column type
 		// and does not contain invalid functions.
+		var innerErr error
 		ret.OnUpdateExpr, err = schemaexpr.SanitizeVarFreeExpr(
 			ctx, d.OnUpdateExpr.Expr, resType, "ON UPDATE", semaCtx, volatility.Volatile,
 		)
 		if err != nil {
+			// Check if the on update expression type can be assignment-cast into the
+			// column type. If it can allow the on update expr and column type to differ.
+			ret.OnUpdateExpr, innerErr = d.OnUpdateExpr.Expr.TypeCheck(ctx, semaCtx, types.Any)
```
Comment (mgartner) [inline pkg/sql/catalog/tabledesc/table.go:187]: Can you add tests for `ON UPDATE` too?

**Review by mgartner — CHANGES_REQUESTED** [review]
Great start!

File: pkg/sql/opt/optbuilder/scope.go [hunk 6]
```diff
@@ -476,9 +476,11 @@ func (s *scope) resolveType(expr tree.Expr, desired *types.T) tree.TypedExpr {
 // expression with no error). If the result type is types.Unknown, then
 // resolveType will wrap the expression in a type cast in order to produce the
 // desired type.
-func (s *scope) resolveAndRequireType(expr tree.Expr, desired *types.T) tree.TypedExpr {
+func (s *scope) resolveAndRequireType(
+	expr tree.Expr, desired *types.T, mutSuffix string,
+) tree.TypedExpr {
 	expr = s.walkExprTree(expr)
-	texpr, err := tree.TypeCheckAndRequire(s.builder.ctx, expr, s.builder.semaCtx, desired, s.context.String())
+	texpr, err := tree.TypeCheckAndRequire(s.builder.ctx, expr, s.builder.semaCtx, desired, s.context.String(), true, mutSuffix)
```
Comment (mgartner) [inline pkg/sql/opt/optbuilder/scope.go:483]: I don't think we can allow assignment casts here in all cases. But, taking a step back, I'm curious why the optbuilder changes were necessary. What was failing before this change?

File: pkg/sql/catalog/tabledesc/table.go [hunk 7]
```diff
@@ -168,7 +168,7 @@ func MakeColumnDefDescs(
 		// Verify the on update expression type is compatible with the column type
 		// and does not contain invalid functions.
 		ret.OnUpdateExpr, err = schemaexpr.SanitizeVarFreeExpr(
-			ctx, d.OnUpdateExpr.Expr, resType, "ON UPDATE", semaCtx, volatility.Volatile,
+			ctx, d.OnUpdateExpr.Expr, resType, "ON UPDATE", semaCtx, volatility.Volatile, true,
```
Comment (mgartner) [inline pkg/sql/catalog/tabledesc/table.go:171]: nit: It's helpful to label arguments with simple constants to make it more clear, like `true /* allowAssignmentCast */`.

File: pkg/sql/opt/optbuilder/scope.go (hunk 6 above)
Comment (e-mbrown) [reply pkg/sql/opt/optbuilder/scope.go:483]: After making the table with differing column and default types, trying to insert into the table would result in an error. This was caused by the condition in TypeCheckRequire
`if typ := typedExpr.ResolvedType(); !(typ.Equivalent(required) || typ.Family() == types.UnknownFamily) {`
I changed the function in opt builder because I noticed the mutation suffix could be passed here to be used in TypeCheckRequire. 
Would specifying that the mutation suffix has to be default or update narrow it down to only the cases we want?

Comment (mgartner) [reply pkg/sql/opt/optbuilder/scope.go:483]: Ok, I think the change required in optbuilder was simpler, though tricky to figure out. I put up a PR: https://github.com/cockroachdb/cockroach/pull/81863. If you rebase your changes on that, you shouldn't need to make any changes in optbuilder.

**Review by rafiss — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/81071)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @e-mbrown, and @mgartner)

___
*[`pkg/sql/catalog/tabledesc/table.go` line 168 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/81071#-N3R60SPAVmipOPsYJ29:-N3R60SPAVmipOPsYJ2A:b-4up5xl) ([raw file](https://github.com/cockroachdb/cockroach/blob/78745aed5d65fe4ccc29e5b205619c31eb257f94/pkg/sql/catalog/tabledesc/table.go#L168)):*
> ```Go
> 			ctx, d.DefaultExpr.Expr, resType, "DEFAULT", semaCtx, volatility.Volatile,
> 		)
> 		if err != nil {
> ```

i think it would be more readable if `var innerErr error` was here (near where the code where it's assigned), instead of having it earlier in the function
___
*[`pkg/sql/catalog/tabledesc/table.go` line 173 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/81071#-N3R5lhf4IVr18W_ue9A:-N3R5lhf4IVr18W_ue9B:bz0f2hd) ([raw file](https://github.com/cockroachdb/cockroach/blob/78745aed5d65fe4ccc29e5b205619c31eb257f94/pkg/sql/catalog/tabledesc/table.go#L173)):*
> ```Go
> 			ret.DefaultExpr, innerErr = d.DefaultExpr.Expr.TypeCheck(ctx, semaCtx, types.Any)
> 			if innerErr != nil {
> 				return nil, err
> ```

is it intentional to not return innerErr here? (i think maybe it is, but in that case, add a comment explaining why)
___
*[`pkg/sql/catalog/tabledesc/table.go` line 197 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/81071#-N3R6CoI23NwXI0yrd9J:-N3R6CoI23NwXI0yrd9K:b-4up5xl) ([raw file](https://github.com/cockroachdb/cockroach/blob/78745aed5d65fe4ccc29e5b205619c31eb257f94/pkg/sql/catalog/tabledesc/table.go#L197)):*
> ```Go
> 			ctx, d.OnUpdateExpr.Expr, resType, "ON UPDATE", semaCtx, volatility.Volatile,
> 		)
> 		if err != nil {
> ```

i think it would be more readable if `var innerErr error` was here (near where the code where it's assigned), instead of having it earlier in the function
___
*[`pkg/sql/catalog/tabledesc/table.go` line 202 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/81071#-N3R6ETGCSDvImIAceD2:-N3R6ETGCSDvImIAceD3:b39pxd1) ([raw file](https://github.com/cockroachdb/cockroach/blob/78745aed5d65fe4ccc29e5b205619c31eb257f94/pkg/sql/catalog/tabledesc/table.go#L202)):*
> ```Go
> 			ret.OnUpdateExpr, innerErr = d.OnUpdateExpr.Expr.TypeCheck(ctx, semaCtx, types.Any)
> 			if innerErr != nil {
> 				return nil, err
> ```

nit: add a comment for why we don't return innerErr
___
*[`pkg/sql/catalog/tabledesc/table.go` line 184 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/81071#-N3R6hvL3K57xvnMo-nC:-N3R6hvL3K57xvnMo-nD:b-rvj2n2) ([raw file](https://github.com/cockroachdb/cockroach/blob/e9962a86957d1fe431081376738b2588894d5c44/pkg/sql/catalog/tabledesc/table.go#L184)):*
> ```Go
> 		// and does not contain invalid functions.
> 		ret.OnUpdateExpr, err = schemaexpr.SanitizeVarFreeExpr(
> 			ctx, d.OnUpdateExpr.Expr, resType, "ON UPDATE", semaCtx, volatility.Volatile, true,
> ```

nit: add an inline comment here, and all the other places where it's called

```
SanitizeVarFreeExpr(..., true /* allowAssignmentCasts */)
```
___
*[`pkg/sql/opt/optbuilder/scope.go` line 480 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/81071#-N3R79p-CoAOTUfy1bq6:-N3R79p-CoAOTUfy1bq7:bq1vuzh) ([raw file](https://github.com/cockroachdb/cockroach/blob/e9962a86957d1fe431081376738b2588894d5c44/pkg/sql/opt/optbuilder/scope.go#L480)):*
> ```Go
> // desired type.
> func (s *scope) resolveAndRequireType(
> 	expr tree.Expr, desired *types.T, mutSuffix string,
> ```

is `mutSuffix` an accident? it doesn't seem to be used

File: pkg/sql/opt/optbuilder/scope.go [hunk 8]
```diff
@@ -478,7 +478,7 @@ func (s *scope) resolveType(expr tree.Expr, desired *types.T) tree.TypedExpr {
 // desired type.
 func (s *scope) resolveAndRequireType(expr tree.Expr, desired *types.T) tree.TypedExpr {
 	expr = s.walkExprTree(expr)
-	texpr, err := tree.TypeCheckAndRequire(s.builder.ctx, expr, s.builder.semaCtx, desired, s.context.String())
+	texpr, err := tree.TypeCheckAndRequire(s.builder.ctx, expr, s.builder.semaCtx, desired, s.context.String(), true)
```
Comment (mgartner) [inline pkg/sql/opt/optbuilder/scope.go:481]: I don't think it should be necessary to change `tree.TypeCheckAndRequire` now that https://github.com/cockroachdb/cockroach/pull/81863 is merged. Can you try passing `false` instead of `true` here and check if any tests break? If the tests pass, you can revert all changes related to `tree.TypeCheckAndRequire`. If they don't, we can do some more sleuthing to figure out the problem.

**Review by mgartner — APPROVED** [review]
LGTM. Very nice!

**Review by rafiss — APPROVED** [review]
lgtm!

> Reviewed 14 of 17 files at r10, 1 of 1 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/81071#-:-N48fRKM90u_uKSGnvDg:b-7nbn20)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @e-mbrown, and @mgartner)

**Comment by e-mbrown** [comment]
TFTR

bor r=mgartner,rafiss
