### PR TITLE
kvserver: add metric for replica circuit breaker

### LINKED ISSUE #74505: kvserver: add metrics for per-Replica circuit breakers
Part of #33007.

With #71806, Replicas can fail-fast when they detect loss of quorum. We need metrics for these circuit breakers:

- number of currently tripped breakers (gauge)
- count of trip events (i.e. transitions of a breaker from healthy to unhealthy).

We also want telemetry on the latter.

### PR DESCRIPTION
**Pull request by tbg**
Add a metric that tracks how many replicas have tripped circuit
breakers.
Add a metric that counts the trip events as well. This can highlight
problems where the circuit is tripped in error and immediately untrips
(which may not be caught by the first metric).

Also, as requested by @mwang1026, report the latter via telemetry as
well.

Fixes #74505.

Release note: None

### CODE REVIEW

**Comment by tbg** [comment]
@aliher1911 would you mind reviewing this since @erikgrinaker is out? If there are any nontrivial questions feel free to call me up so we can chat about it.

File: pkg/kv/kvserver/metrics.go [hunk 1]
```diff
@@ -1459,6 +1479,10 @@ type StoreMetrics struct {
 
 	// Closed timestamp metrics.
 	ClosedTimestampMaxBehindNanos *metric.Gauge
+
+	// Replica circuit breaker.
+	ReplicaCircuitBreakerCurTripped *metric.Gauge
+	ReplicaCircuitBreakerCumTripped *metric.Gauge
```
Comment (erikgrinaker) [inline pkg/kv/kvserver/metrics.go:1485]: `CumTripped` should be a count, not a gauge.

File: pkg/kv/kvserver/metrics.go [hunk 2]
```diff
@@ -1242,6 +1242,26 @@ throttled they do count towards 'delay.total' and 'delay.enginebackpressure'.
...
+A nonzero value indicates range or replica unavailability, and should be investigated.
+Replicas in this state will fail-fast all inbound requests.
+`,
+		Measurement: "Replicas",
+		Unit:        metric.Unit_COUNT,
+	}
+
+	// Replica circuit breaker.
+	metaReplicaCircuitBreakerCumTripped = metric.Metadata{
+		Name:        "kv.replica_circuit_breaker.num_trip_events",
```
Comment (erikgrinaker) [inline pkg/kv/kvserver/metrics.go:1260]: nit: consider `num_tripped_events` for consistency.

File: pkg/kv/kvserver/replica_init.go [hunk 3]
```diff
@@ -128,7 +129,14 @@ func newUnloadedReplica(
...
 
-	r.breaker = newReplicaCircuitBreaker(store.cfg.Settings, store.stopper, r.AmbientContext, r)
+	r.breaker = newReplicaCircuitBreaker(
+		store.cfg.Settings, store.stopper, r.AmbientContext, r, func() {
+			telemetry.Inc(telemetryTripAsync)
+			r.store.Metrics().ReplicaCircuitBreakerCumTripped.Inc(1)
+			store.Metrics().ReplicaCircuitBreakerCurTripped.Inc(1)
+		}, func() {
+			store.Metrics().ReplicaCircuitBreakerCurTripped.Dec(1)
+		})
```
Comment (erikgrinaker) [inline pkg/kv/kvserver/replica_init.go:139]: Consider either naming these closures, or adding a comment to clarify their purpose.

**Review by erikgrinaker — APPROVED** [review]
LGTM, modulo some minor comments.

**Comment by tbg** [comment]
TFTR! Comments addressed, but looks like I have something to look into:

```
Error Trace:	client_replica_circuit_breaker_test.go:121
        	Error:      	Not equal: 
        	            	expected: int(0)
        	            	actual  : int64(-1)
        	Test:       	TestReplicaCircuitBreaker_LeaseholderTripped
```

I suspect we're not always emitting the correct number of "Reset" events.

**Comment by tbg** [comment]
Got the sucker, prepended a commit.

**Review by erikgrinaker — APPROVED** [review]
Nice, thanks.

**Comment by tbg** [comment]
bors r=erikgrinaker
