### PR TITLE
tabledesc_test: deflake TestIndexDoesNotStorePrimaryKeyColumnMixedVersion

### LINKED ISSUE #116622: sql/catalog/tabledesc: TestIndexDoesNotStorePrimaryKeyColumnMixedVersion failed
sql/catalog/tabledesc.TestIndexDoesNotStorePrimaryKeyColumnMixedVersion [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_StressBazel/13176613?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_StressBazel/13176613?buildTab=artifacts#/) on master @ [1f53a61732c6f9e48622f45d276eb5e1c343ad30](https://github.com/cockroachdb/cockroach/commits/1f53a61732c6f9e48622f45d276eb5e1c343ad30):

```
=== RUN   TestIndexDoesNotStorePrimaryKeyColumnMixedVersion
    test_log_scope.go:170: test logs captured to: /artifacts/tmp/_tmp/d683b1e56197e0abcfe81bcc24d65b25/logTestIndexDoesNotStorePrimaryKeyColumnMixedVersion1813710857
    test_log_scope.go:81: use -show-logs to present logs inline
    validate_version_gating_test.go:119: 
        	Error Trace:	github.com/cockroachdb/cockroach/pkg/sql/catalog/tabledesc_test/pkg/sql/catalog/tabledesc/validate_version_gating_test.go:119
        	Error:      	An error is expected but got nil.
        	Test:       	TestIndexDoesNotStorePrimaryKeyColumnMixedVersion
    panic.go:523: -- test log scope end --
test logs left over in: /artifacts/tmp/_tmp/d683b1e56197e0abcfe81bcc24d65b25/logTestIndexDoesNotStorePrimaryKeyColumnMixedVersion1813710857
--- FAIL: TestIndexDoesNotStorePrimaryKeyColumnMixedVersion (23.26s)
```

Parameters:
 - <code>TAGS=bazel,gss,deadlock</code>
 - <code>stress=true</code>
<details><summary>Help</summary>
<p>

See also: [How To Investigate a Go Test Failure \(internal\)](https://cockroachlabs.atlassian.net/l/c/HgfXfJgM)
</p>
</details>
/cc @cockroachdb/sql-foundations
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*TestIndexDoesNotStorePrimaryKeyColumnMixedVersion.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)
</sub>

Jira issue: CRDB-34690

### PR DESCRIPTION
**Pull request by Xiang-Gu**
Previously, this test would flake under `--stress` and the root cause is because the upgrade precondition check that it relies on actually checks for corrupt descriptor at AOST '-10s', and it's possible that the corrupt descriptor was injected within the last 10s to the system, and thus the check produced a "false negative" (meaning it saw there isn't no corruption at AOST '-10s' and mistakenly assumed there isn't corruption now) and thus mistakenly allowed the cluster upgrade to proceed.

Fixes #116622
Release note: None

### CODE REVIEW

File: pkg/sql/catalog/tabledesc/validate_version_gating_test.go [hunk 1]
```diff
@@ -104,6 +105,10 @@ func TestIndexDoesNotStorePrimaryKeyColumnMixedVersion(t *testing.T) {
...
 	mustInsertDescToDB(ctx, t, sqlDB, corruptDescToInject)
+	// Upgrade precondition checks for corrupt descriptor AOST '-10s', so, we wait
+	// for 10s here to ensure the corruption will be seen by the time the upgrade
+	// precondition check runs.
+	time.Sleep(10 * time.Second)
```
Comment (rafiss) [inline pkg/sql/catalog/tabledesc/validate_version_gating_test.go:111]: i am not a fan of adding such a long sleep in tests. have you considered adding a testing hook like this?
```
diff --git a/pkg/upgrade/upgrades/first_upgrade.go b/pkg/upgrade/upgrades/first_upgrade.go
index 1505eb81702..813718b93d4 100644
--- a/pkg/upgrade/upgrades/first_upgrade.go
+++ b/pkg/upgrade/upgrades/first_upgrade.go
@@ -97,6 +97,14 @@ func upgradeDescriptors(
 	})
 }
 
+var firstUpgradeAOST = true
+
+func TestingSetFirstUpgradeAOST(enabled bool) func() {
+	old := firstUpgradeAOST
+	firstUpgradeAOST = enabled
+	return func() { firstUpgradeAOST = old }
+}
+
 // FirstUpgradeFromReleasePrecondition is the precondition check for upgrading
 // from any supported major release.
 //
@@ -118,7 +126,7 @@ func FirstUpgradeFromReleasePrecondition(
 	// a diagnostic query. If no corruptions were found back then, we assume that
 	// there are no corruptions now. Otherwise, we retry and do everything
 	// without an AOST clause henceforth.
-	withAOST := true
+	withAOST := firstUpgradeAOST
 	diagnose := func(tbl string) (hasRows bool, err error) {
 		q := fmt.Sprintf("SELECT count(*) FROM \"\".crdb_internal.%s", tbl)
 		if withAOST {
```

**Review by rafiss — CHANGES_REQUESTED** [review]

File: pkg/sql/catalog/tabledesc/validate_version_gating_test.go (hunk 1 above)
Comment (Xiang-Gu) [reply pkg/sql/catalog/tabledesc/validate_version_gating_test.go]: This is a good idea! Done

File: pkg/sql/catalog/tabledesc/validate_version_gating_test.go [hunk 2]
```diff
@@ -115,6 +114,8 @@ func TestIndexDoesNotStorePrimaryKeyColumnMixedVersion(t *testing.T) {
 
 	// Assert cluster version upgrade is blocked.
 	require.Equal(t, [][]string{{"1000023.1"}}, tdb.QueryStr(t, "SHOW CLUSTER SETTING version;"))
+	// disable AOST for upgrade precondition check to ensure it sees the injected, corrupt descriptor.
+	upgrades.TestingSetFirstUpgradePreconditionAOST(false)
```
Comment (rafiss) [inline pkg/sql/catalog/tabledesc/validate_version_gating_test.go:118]: this should be:
```
defer upgrades.TestingSetFirstUpgradePreconditionAOST(false)()
```

**Review by rafiss — CHANGES_REQUESTED** [review]

File: pkg/sql/catalog/tabledesc/validate_version_gating_test.go (hunk 2 above)
Comment (Xiang-Gu) [reply pkg/sql/catalog/tabledesc/validate_version_gating_test.go]: good catch! Fixed

**Review by rafiss — APPROVED** [review]
