### PR TITLE
roachtest/cdc: change CompatibleClouds to OnlyAzure

### LINKED ISSUE #117803: roachtest: cdc/kafka-azure failed
roachtest.cdc/kafka-azure [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/13558168?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/13558168?buildTab=artifacts#/cdc/kafka-azure) on master @ [75f19bec66a542d58680e9ccb47d57598f48fe20](https://github.com/cockroachdb/cockroach/commits/75f19bec66a542d58680e9ccb47d57598f48fe20):

```
(cdc.go:270).setupSink: error running ``az login``: COMMAND_PROBLEM: exit status 2
(cluster.go:2293).Run: context canceled
(cdc.go:381).Close: error shutting down prometheus/grafana: context canceled
test artifacts and logs in: /artifacts/cdc/kafka-azure/run_1
```

Parameters:
 - <code>ROACHTEST_arch=amd64</code>
 - <code>ROACHTEST_cloud=gce</code>
 - <code>ROACHTEST_coverageBuild=false</code>
 - <code>ROACHTEST_cpu=4</code>
 - <code>ROACHTEST_encrypted=false</code>
 - <code>ROACHTEST_fs=ext4</code>
 - <code>ROACHTEST_localSSD=true</code>
 - <code>ROACHTEST_metamorphicBuild=false</code>
 - <code>ROACHTEST_ssd=0</code>
<details><summary>Help</summary>
<p>

See: [roachtest README](https://github.com/cockroachdb/cockroach/blob/master/pkg/cmd/roachtest/README.md)

See: [How To Investigate \(internal\)](https://cockroachlabs.atlassian.net/l/c/SSSBr8c7)

See: [Grafana](https://go.crdb.dev/roachtest-grafana/teamcity-13558168/cdc-kafka-azure/1705406578399/1705406838490)

</p>
</details>
/cc @cockroachdb/cdc
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*cdc/kafka-azure.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)
</sub>

Jira issue: CRDB-35366

### PR DESCRIPTION
**Pull request by wenyihu6**
Previously, cdc/kafka-azure could be run on TeamCity agents that do not have
env var credentials configured properly. This patch fixes it by changing
CompatibleClouds to OnlyAzure so that it runs exclusively on `Roachtest Nightly - Azure`.

Fixes: https://github.com/cockroachdb/cockroach/issues/117803

Release note: none

### CODE REVIEW

File: pkg/cmd/roachtest/tests/cdc.go [hunk 1]
```diff
@@ -1629,7 +1629,7 @@ func registerCDC(r registry.Registry) {
 	r.Add(registry.TestSpec{
 		Name:             "cdc/kafka-azure",
 		Owner:            `cdc`,
-		CompatibleClouds: registry.AllExceptAWS,
+		CompatibleClouds: registry.OnlyAzure,
 		Cluster:          r.MakeClusterSpec(2, spec.GCEZones("us-east1-b")),
```
Comment (DarrylWong) [inline pkg/cmd/roachtest/tests/cdc.go:1633]: nit: `spec.GCEZones("us-east1-b")` isn't doing anything if we're running on only Azure. You'd need to add spec.AzureZones but I think you might not need it at all from skimming the test.

**Review by DarrylWong — APPROVED** [review]

File: pkg/cmd/roachtest/tests/cdc.go (hunk 1 above)
Comment (srosenberg) [reply pkg/cmd/roachtest/tests/cdc.go]: Yep, `spec.AzureZones` doesn't exist as of yet, so it will default to `defaultLocations[0]`,

```
// These default locations support availability zones. At the time of
// this comment, `westus` did not.
var defaultLocations = []string{
	"eastus",
	"westus2",
	"westeurope",
}
```

We can add `spec.AzureZones` at a later time since the default isn't likely to change any time soon.

**Review by srosenberg — APPROVED** [review]

**Review by renatolabs — APPROVED** [review]

**Comment by wenyihu6** [comment]
TFTRs!

bors r=DarrylWong,srosenberg,renatolabs
