### PR TITLE
ui: fix statement diag reports when min exec latency is null

### LINKED ISSUE #139340: UI: statement bundle silently fails when min_execution_latency is null
When the response from `_status/stmtdiagreports` returns undefined for the `report.minExecutionLatency` field, db console silently errors, resulting in the inability to download statement bundles. This results in a UX where it looks like nothing is happening when diagnostics are activated.

https://github.com/user-attachments/assets/cbe3ec1c-b215-4a78-96bf-fdc6556c577d

### PR DESCRIPTION
**Pull request by kyle-a-wong**
A bug in db console was resulting in statement diagnostics reports to not work as intended. As a result, activating diagnostics didn't result in the intended state change which showed a user that a diagnostics report is running or downloadble.

This was happening in edge cases where reports "minExecutionLatency" response field was null, but the db console expected it to be populated. Now, db console should handle this edge case.

Fixes: #139340
Epic: none
Release note (bug fix): Fixes a bug where sometimes activating diagnostics for sql activity appears unresponsive, with no state or status update upon activating. Now, the status should always reflect that diagnosticsa are active or that a statement bundle is downloadable.

### CODE REVIEW

**Comment by kyle-a-wong** [comment]
Before fix (point at drt-chaos with `./dev ui watch`:
https://www.loom.com/share/decbcf4fd6744b3c8532ffa748fdf49a?sid=c3606c4c-b1e4-4255-b07c-c3e3eb327010
After  fix:
https://www.loom.com/share/52753aac61a34eb7abcc8ef0ec2fe1d7?sid=a4bf2dec-3af5-46c1-ae9b-a80cf6a16973

File: pkg/ui/workspaces/cluster-ui/src/api/statementDiagnosticsApi.ts [hunk 1]
```diff
@@ -33,17 +33,24 @@ export async function getStatementDiagnosticsReports(): Promise<StatementDiagnos
     STATEMENT_DIAGNOSTICS_PATH,
   );
   return response.reports.map(report => {
+    const minExecutionLatency = report.min_execution_latency
```
Comment (dhartunian) [inline pkg/ui/workspaces/cluster-ui/src/api/statementDiagnosticsApi.ts:36]: I don't quite understand what's being fixed here. If the value could be missing, then the same solution with the `?` should apply. What's special about `minExecutionLatency` here? Why do you need to add to it?

Comment (kyle-a-wong) [reply pkg/ui/workspaces/cluster-ui/src/api/statementDiagnosticsApi.ts:36]: I have it as a separate variable just to make it cleaner to read so that there isn't a nested ternary inside the return statement. 

This PR is actually changing 2 things, so I'll update the commit message to be more reflective of this but, the two things being changed are:
1. if `report.min_execution_latency` is null, the returned `min_execution_latency` field is also null. I think it makes sense to return a null instead of a n empty / "0s" duration object. 
2. The returned duration object is now more precise and includes the "nanos" as part of the duration.. Previously, it only converted the seconds value but I assume that this will almost always be 0, since most queries should run in the sub seconds.

I am not sure if grpc will return 0 or null for `report.min_execution_latency.seconds` when seconds is 0 and nanos is not, but its listed as a nullable field, so i added the `?` just in case

**Review by xinhaoz — COMMENTED** [review]
TY for fixing! Can you also add to the stmt diags cypress test so we can catch this whenn we eventually enable the test on the roachprod cypress tests?

This bug is very interesting because the API has always returned "0s" when the `min_execution_latency` col is null. I wonder if something else changed recently in how we decode the protobuf to js.

File: pkg/ui/workspaces/cluster-ui/src/api/statementDiagnosticsApi.ts (hunk 1 above)
Comment (dhartunian) [reply pkg/ui/workspaces/cluster-ui/src/api/statementDiagnosticsApi.ts:36]: Thank you for the detailed explanation. That raises a followup question which is: we must have prior code in DB Console that deals with sub-second durations, is there an existing pattern/helper to leverage here besides manually adding fractional seconds via `moment`?

Looks like `DurationToMomentDuration` might do what you need here.

**Comment by kyle-a-wong** [comment]
> TY for fixing! Can you also add to the stmt diags cypress test so we can catch this whenn we eventually enable the test on the roachprod cypress tests?

Good idea, I'll add this as a separate PR, since it doesn't need to be back ported.
 
> This bug is very interesting because the API has always returned "0s" when the `min_execution_latency` col is null. I wonder if something else changed recently in how we decode the protobuf to js.

Yeah that's still unclear to me. I'm working on identifying when this started happening

**Review by dhartunian — APPROVED** [review]

**Comment by kyle-a-wong** [comment]
TFTR

bors r+

**Comment by kyle-a-wong** [comment]
bors retry

**Comment by kyle-a-wong** [comment]
After investigation, it was determined that this issue was caused as a result of this PR: https://github.com/cockroachdb/cockroach/pull/137479, where a change was introduced to not serialize zero-valued durations. This results in the decoding of the duration field to be null on the client side
