### PR TITLE
loqrecovery: deflake TestFindUpdateRaft

### LINKED ISSUE #164951: kv/kvserver/loqrecovery: TestFindUpdateRaft failed
kv/kvserver/loqrecovery.TestFindUpdateRaft [failed](https://mesolite.cluster.engflow.com/invocations/default/55837e98-aa2c-4b1b-ba82-2fee1236070d?testReportRun=1&testReportShard=1&testReportAttempt=1#targets-Ly9wa2cva3Yva3ZzZXJ2ZXIvbG9xcmVjb3Zlcnk6bG9xcmVjb3ZlcnlfdGVzdA==) on master @ [ce5df40ab9e323b8d81cf2907ccb2eb3695ec37b](https://github.com/cockroachdb/cockroach/commits/ce5df40ab9e323b8d81cf2907ccb2eb3695ec37b):

Failed with:

```
=== RUN   TestFindUpdateRaft
    test_log_scope.go:172: test logs captured to: outputs.zip/logTestFindUpdateRaft1624498671
    test_log_scope.go:82: use -show-logs to present logs inline
=== RUN   TestFindUpdateRaft/lease-type=LeaseLeader
    test_server_shim.go:146: using test tenant configuration from testserver factory defaults
    collect_raft_log_test.go:133: descriptor change sequence [] doesn't contain {ReplicaChange r82:/{Table/Max-Max} [(n1,s1):1, next=3, gen=6, sticky=9223372036.854775807,2147483647] <nil>}
```
Fatal entries found in Cockroach logs:

```
F260305 18:47:17.778700 16548 storage/pebble.go:1582  [n1,s1,pebble] 1  error during engine close: leaked snapshots: 1 open snapshots on DB 0xc00310a608
F260305 18:47:17.778700 16548 storage/pebble.go:1582  [n1,s1,pebble] 1 !goroutine 16548 [running]:
F260305 18:47:17.778700 16548 storage/pebble.go:1582  [n1,s1,pebble] 1 !github.com/cockroachdb/cockroach/pkg/util/allstacks.GetWithBuf({0x0?, 0xe2a20d?, 0xc00ed4ca18?})
F260305 18:47:17.778700 16548 storage/pebble.go:1582  [n1,s1,pebble] 1 !	pkg/util/allstacks/allstacks.go:38 +0x133
F260305 18:47:17.778700 16548 storage/pebble.go:1582  [n1,s1,pebble] 1 !github.com/cockroachdb/cockroach/pkg/util/allstacks.Get(...)
F260305 18:47:17.778700 16548 storage/pebble.go:1582  [n1,s1,pebble] 1 !	pkg/util/allstacks/allstacks.go:19
F260305 18:47:17.778700 16548 storage/pebble.go:1582  [n1,s1,pebble] 1 !github.com/cockroachdb/cockroach/pkg/util/log.(*loggerT).outputLogEntry(_, {{{0x0, 0x0}, {0x0, 0x0}, {0x0, 0x0}, {0x0, 0x0}, {0x0, ...}}, ...})
F260305 18:47:17.778700 16548 storage/pebble.go:1582  [n1,s1,pebble] 1 !	pkg/util/log/clog.go:294 +0xc6
F260305 18:47:17.778700 16548 storage/pebble.go:1582  [n1,s1,pebble] 1 !github.com/cockroachdb/cockroach/pkg/util/log.logfDepthInternal({0x6d8c3f8, 0xc00bd6ea00}, 0x2, 0x4, 0x0, 0x0?, {0x60c4b83, 0x1e}, {0xc011e98b68, 0x1, ...})
F260305 18:47:17.778700 16548 storage/pebble.go:1582  [n1,s1,pebble] 1 !	pkg/util/log/channels.go:104 +0x5a5
F260305 18:47:17.778700 16548 storage/pebble.go:1582  [n1,s1,pebble] 1 !github.com/cockroachdb/cockroach/pkg/util/log.logfDepth(...)
F260305 18:47:17.778700 16548 storage/pebble.go:1582  [n1,s1,pebble] 1 !	pkg/util/log/channels.go:34
F260305 18:47:17.778700 16548 storage/pebble.go:1582  [n1,s1,pebble] 1 !github.com/cockroachdb/cockroach/pkg/util/log.loggerDev.Fatalf(...)
F260305 18:47:17.778700 16548 storage/pebble.go:1582  [n1,s1,pebble] 1 !	bazel-out/k8-fastbuild/bin/pkg/util/log/log_channels_generated.go:466
F260305 18:47:17.778700 16548 storage/pebble.go:1582  [n1,s1,pebble] 1 !github.com/cockroachdb/cockroach/pkg/storage.(*Pebble).Close.func1(...)
F260305 18:47:17.778700 16548 storage/pebble.go:1582  [n1,s1,pebble] 1 !	pkg/storage/pebble.go:1582
F260305 18:47:17.778700 16548 storage/pebble.go:1582  [n1,s1,pebble] 1 !github.com/cockroachdb/cockroach/pkg/storage.(*Pebble).Close(0xc00ca3a388)
F260305 18:47:17.778700 16548 storage/pebble.go:1582  [n1,s1,pebble] 1 !	pkg/storage/pebble.go:1588 +0x150
F260305 18:47:17.778700 16548 storage/pebble.go:1582  [n1,s1,pebble] 1 !github.com/cockroachdb/cockroach/pkg/kv/kvserver/kvstorage.(*Engines).Close(0xc00c9b9bf8?)
F260305 18:47:17.778700 16548 storage/pebble.go:1582  [n1,s1,pebble] 1 !	pkg/kv/kvserver/kvstorage/storage.go:214 +0x5c
F260305 18:47:17.778700 16548 storage/pebble.go:1582  [n1,s1,pebble] 1 !github.com/cockroachdb/cockroach/pkg/server.(*Engines).Close(0xc0037240f0)
F260305 18:47:17.778700 16548 storage/pebble.go:1582  [n1,s1,pebble] 1 !	pkg/server/config.go:710 +0x8a
F260305 18:47:17.778700 16548 storage/pebble.go:1582  [n1,s1,pebble] 1 !github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).Stop(0xc01332e360, {0x6d8bee0, 0xb032000})
F260305 18:47:17.778700 16548 storage/pebble.go:1582  [n1,s1,pebble] 1 !	pkg/util/stop/stopper.go:600 +0x106
F260305 18:47:17.778700 16548 storage/pebble.go:1582  [n1,s1,pebble] 1 !github.com/cockroachdb/cockroach/pkg/testutils/testcluster.(*TestCluster).stopServerLocked(0xc0036eae08, 0x0)
F260305 18:47:17.778700 16548 storage/pebble.go:1582  [n1,s1,pebble] 1 !	pkg/testutils/testcluster/testcluster.go:251 +0x48
F260305 18:47:17.778700 16548 storage/pebble.go:1582  [n1,s1,pebble] 1 !github.com/cockroachdb/cockroach/pkg/testutils/testcluster.(*TestCluster).stopServers(0xc0036eae08, {0x6d8bee0, 0xb032000})
F260305 18:47:17.778700 16548 storage/pebble.go:1582  [n1,s1,pebble] 1 !	pkg/testutils/testcluster/testcluster.go:188 +0x273
F260305 18:47:17.778700 16548 storage/pebble.go:1582  [n1,s1,pebble] 1 !github.com/cockroachdb/cockroach/pkg/testutils/testcluster.(*TestCluster).Start.func3()
F260305 18:47:17.778700 16548 storage/pebble.go:1582  [n1,s1,pebble] 1 !	pkg/testutils/testcluster/testcluster.go:549 +0x25
F260305 18:47:17.778700 16548 storage/pebble.go:1582  [n1,s1,pebble] 1 !github.com/cockroachdb/cockroach/pkg/util/stop.CloserFn.Close(0xc01332e240?)
F260305 18:47:17.778700 16548 storage/pebble.go:1582  [n1,s1,pebble] 1 !	pkg/util/stop/stopper.go:103 +0x12
F260305 18:47:17.778700 16548 storage/pebble.go:1582  [n1,s1,pebble] 1 !github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).Stop(0xc01332e240, {0x6d8bbb0, 0xb032000})
F260305 18:47:17.778700 16548 storage/pebble.go:1582  [n1,s1,pebble] 1 !	pkg/util/stop/stopper.go:600 +0x106
F260305 18:47:17.778700 16548 storage/pebble.go:1582  [n1,s1,pebble] 1 !runtime.Goexit()
F260305 18:47:17.778700 16548 storage/pebble.go:1582  [n1,s1,pebble] 1 !	GOROOT/src/runtime/panic.go:615 +0x5e
F260305 18:47:17.778700 16548 storage/pebble.go:1582  [n1,s1,pebble] 1 !testing.(*common).FailNow(0xc0025be000)
F260305 18:47:17.778700 16548 storage/pebble.go:1582  [n1,s1,pebble] 1 !	GOROOT/src/testing/testing.go:1013 +0x4a
F260305 18:47:17.778700 16548 storage/pebble.go:1582  [n1,s1,pebble] 1 !testing.(*common).Fatalf(0xc0025be000, {0x616697c?, 0x0?}, {0xc011e99008?, 0x5cd740?, 0xc0025be000?})
F260305 18:47:17.778700 16548 storage/pebble.go:1582  [n1,s1,pebble] 1 !	GOROOT/src/testing/testing.go:1219 +0x59
F260305 18:47:17.778700 16548 storage/pebble.go:1582  [n1,s1,pebble] 1 !github.com/cockroachdb/cockroach/pkg/kv/kvserver/loqrecovery_test.requireContainsDescriptor(0xc0025be000, {0x2, 0xc00a5ac000, 0x0}, {0x0, 0x0, 0x0})
F260305 18:47:17.778700 16548 storage/pebble.go:1582  [n1,s1,pebble] 1 !	pkg/kv/kvserver/loqrecovery/collect_raft_log_test.go:235 +0x176
F260305 18:47:17.778700 16548 storage/pebble.go:1582  [n1,s1,pebble] 1 !github.com/cockroachdb/cockroach/pkg/kv/kvserver/loqrecovery_test.TestFindUpdateRaft.func1.2(0xc0025be000, {0x6d8bbb0?, 0xb032000?}, {0x7f878c8b8f58?, 0xc012fc5c80?})
F260305 18:47:17.778700 16548 storage/pebble.go:1582  [n1,s1,pebble] 1 !	pkg/kv/kvserver/loqrecovery/collect_raft_log_test.go:133 +0xd6
F260305 18:47:17.778700 16548 storage/pebble.go:1582  [n1,s1,pebble] 1 !github.com/cockroachdb/cockroach/pkg/kv/kvserver/loqrecovery_test.checkRaftLog(0xc0025be000, {0x6d8bbb0, 0xb032000}, 0x0, 0xc002aebf28, 0xc011e99f18, 0x3)
F260305 18:47:17.778700 16548 storage/pebble.go:1582  [n1,s1,pebble] 1 !	pkg/kv/kvserver/loqrecovery/collect_raft_log_test.go:222 +0x683
F260305 18:47:17.778700 16548 storage/pebble.go:1582  [n1,s1,pebble] 1 !github.com/cockroachdb/cockroach/pkg/kv/kvserver/loqrecovery_test.TestFindUpdateRaft.func1(0xc0025be000, 0x3)
F260305 18:47:17.778700 16548 storage/pebble.go:1582  [n1,s1,pebble] 1 !	pkg/kv/kvserver/loqrecovery/collect_raft_log_test.go:108 +0x78
F260305 18:47:17.778700 16548 storage/pebble.go:1582  [n1,s1,pebble] 1 !github.com/cockroachdb/cockroach/pkg/testutils.RunValues[...].func1()
F260305 18:47:17.778700 16548 storage/pebble.go:1582  [n1,s1,pebble] 1 !	pkg/testutils/subtest.go:23 +0x1a
F260305 18:47:17.778700 16548 storage/pebble.go:1582  [n1,s1,pebble] 1 !testing.tRunner(0xc0025be000, 0xc001742000)
F260305 18:47:17.778700 16548 storage/pebble.go:1582  [n1,s1,pebble] 1 !	GOROOT/src/testing/testing.go:1934 +0xea
F260305 18:47:17.778700 16548 storage/pebble.go:1582  [n1,s1,pebble] 1 !created by testing.(*T).Run in goroutine 9888
F260305 18:47:17.778700 16548 storage/pebble.go:1582  [n1,s1,pebble] 1 !	GOROOT/src/testing/testing.go:1997 +0x465
F260305 18:47:17.778700 16548 storage/pebble.go:1582  [n1,s1,pebble] 1 !
F260305 18:47:17.778700 16548 storage/pebble.go:1582  [n1,s1,pebble] 1 !goroutine 1 [chan receive]:
F260305 18:47:17.778700 16548 storage/pebble.go:1582  [n1,s1,pebble] 1 !testing.(*T).Run(0xc00264fc00, {0x60795c1?, 0xc00281f958?}, 0x643ced0)
F260305 18:47:17.778700 16548 storage/pebble.go:1582  [n1,s1,pebble] 1 !	GOROOT/src/testing/testing.go:2005 +0x485
F260305 18:47:17.778700 16548 storage/pebble.go:1582  [n1,s1,pebble] 1 !testing.runTests.func1(0xc00264fc00)
F260305 18:47:17.778700 16548 storage/pebble.go:1582  [n1,s1,pebble] 1 !	GOROOT/src/testing/testing.go:2477 +0x37
F260305 18:47:17.778700 16548 storage/pebble.go:1582  [n1,s1,pebble] 1 !testing.tRunner(0xc00264fc00, 0xc00281fa98)
F260305 18:47:17.778700 16548 storage/pebble.go:1582  [n1,s1,pebble] 1 !	GOROOT/src/testing/testing.go:1934 +0xea
F260305 18:47:17.778700 16548 storage/pebble.go:1582  [n1,s1,pebble] 1 !testing.runTests(0xc0026d8930, {0xaa17ee0, 0x20, 0x20}, {0xadd4880?, 0x0?, 0xadd4880?})
F260305 18:47:17.778700 16548 storage/pebble.go:1582  [n1,s1,pebble] 1 !	GOROOT/src/testing/testing.go:2475 +0x4b4
F260305 18:47:17.778700 16548 storage/pebble.go:1582  [n1,s1,pebble] 1 !testing.(*M).Run(0xc002780dc0)
F260305 18:47:17.778700 16548 storage/pebble.go:1582  [n1,s1,pebble] 1 !	GOROOT/src/testing/testing.go:2337 +0x63a
F260305 18:47:17.778700 16548 storage/pebble.go:1582  [n1,s1,pebble] 1 !github.com/cockroachdb/cockroach/pkg/kv/kvserver/loqrecovery_test.TestMain(0xc002780dc0)
F260305 18:47:17.778700 16548 storage/pebble.go:1582  [n1,s1,pebble] 1 !	pkg/kv/kvserver/loqrecovery/main_test.go:29 +0x1ab
F260305 18:47:17.778700 16548 storage/pebble.go:1582  [n1,s1,pebble] 1 !main.main()
F260305 18:47:17.778700 16548 storage/pebble.go:1582  [n1,s1,pebble] 1 !	bazel-out/k8-fastbuild/bin/pkg/kv/kvserver/loqrecovery/loqrecovery_test_/testmain.go:206 +0x487
F260305 18:47:17.778700 16548 storage/pebble.go:1582  [n1,s1,pebble] 1 !
F260305 18:47:17.778700 16548 storage/pebble.go:1582  [n1,s1,pebble] 1 !goroutine 8 [select]:
F260305 18:47:17.778700 16548 storage/pebble.go:1582  [n1,s1,pebble] 1 !go.opencensus.io/stats/view.(*worker).start(0xc000ddb180)
F260305 18:47:17.778700 16548 storage/pebble.go:1582  [n1,s1,pebble] 1 !	external/io_opencensus_go/stats/view/worker.go:292 +0x9f
F260305 18:47:17.778700 16548 storage/pebble.go:1582  [n1,s1,pebble] 1 !created by go.opencensus.io/stats/view.init.0 in goroutine 1
F260305 18:47:17.778700 16548 storage/pebble.go:1582  [n1,s1,pebble] 1 !	external/io_opencensus_go/stats/view/worker.go:34 +0x8d
F260305 18:47:17.778700 16548 storage/pebble.go:1582  [n1,s1,pebble] 1 !
F260305 18:47:17.778700 16548 storage/pebble.go:1582  [n1,s1,pebble] 1 !goroutine 12 [chan receive]:
F260305 18:47:17.778700 16548 storage/pebble.go:1582  [n1,s1,pebble] 1 !github.com/cockroachdb/cockroach/pkg/util/log.flushDaemon()
F260305 18:47:17.778700 16548 storage/pebble.go:1582  [n1,s1,pebble] 1 !	pkg/util/log/log_flush.go:123 +0x4e
F260305 18:47:17.778700 16548 storage/pebble.go:1582  [n1,s1,pebble] 1 !created by github.com/cockroachdb/cockroach/pkg/util/log.init.5 in goroutine 1
F260305 18:47:17.778700 16548 storage/pebble.go:1582  [n1,s1,pebble] 1 !	pkg/util/log/log_flush.go:78 +0x1a
F260305 18:47:17.778700 16548 storage/pebble.go:1582  [n1,s1,pebble] 1 !
F260305 18:47:17.778700 16548 storage/pebble.go:1582  [n1,s1,pebble] 1 !goroutine 13 [chan receive]:
F260305 18:47:17.778700 16548 storage/pebble.go:1582  [n1,s1,pebble] 1 !github.com/cockroachdb/cockroach/pkg/util/log.signalFlusher()
F260305 18:47:17.778700 16548 storage/pebble.go:1582  [n1,s1,pebble] 1 !	pkg/util/log/log_flush.go:147 +0x85
F260305 18:47:17.778700 16548 storage/pebble.go:1582  [n1,s1,pebble] 1 !created by github.com/cockroachdb/cockroach/pkg/util/log.init.5 in goroutine 1
F260305 18:47:17.778700 16548 storage/pebble.go:1582  [n1,s1,pebble] 1 !	pkg/util/log/log_flush.go:79 +0x26
F260305 18:47:17.778700 16548 storage/pebble.go:1582  [n1,s1,pebble] 1 !
F260305 18:47:17.778700 16548 storage/pebble.go:1582  [n1,s1,pebble] 1 !goroutine 14 [chan receive]:
F260305 18:47:17.778700 16548 storage/pebble.go:1582  [n1,s1,pebble] 1 !github.com/cockroachdb/cockroach/pkg/util/goschedstats.init.0.func1()
F260305 18:47:17.778700 16548 storage/pebble.go:1582  [n1,s1,pebble] 1 !	pkg/util/goschedstats/runnable_enabled.go:144 +0xdd
F260305 18:47:17.778700 16548 storage/pebble.go:1582  [n1,s1,pebble] 1 !created by github.com/cockroachdb/cockroach/pkg/util/goschedstats.init.0 in goroutine 1
F260305 18:47:17.778700 16548 storage/pebble.go:1582  [n1,s1,pebble] 1 !	pkg/util/goschedstats/runnable_enabled.go:136 +0x1a
F260305 18:47:17.778700 16548 storage/pebble.go:1582  [n1,s1,pebble] 1 !
F260305 18:47:17.778700 16548 storage/pebble.go:1582  [n1,s1,pebble] 1 !goroutine 16 [syscall]:
F260305 18:47:17.778700 16548 storage/pebble.go:1582  [n1,s1,pebble] 1 !os/signal.signal_recv()
F260305 18:47:17.778700 16548 storage/pebble.go:1582  [n1,s1,pebble] 1 !	GOROOT/src/runtime/sigqueue.go:152 +0x29
F260305 18:47:17.778700 16548 storage/pebble.go:1582  [n1,s1,pebble] 1 !os/signal.loop()
F260305 18:47:17.778700 16548 storage/pebble.go:1582  [n1,s1,pebble] 1 !	GOROOT/src/os/signal/signal_unix.go:23 +0x13
F260305 18:47:17.778700 16548 storage/pebble.go:1582  [n1,s1,pebble] 1 !created by os/signal.Notify.func1.1 in goroutine 13
F260305 18:47:17.778700 16548 storage/pebble.go:1582  [n1,s1,pebble] 1 !	GOROOT/src/os/signal/signal.go:152 +0x1f
F260305 18:47:17.778700 16548 storage/pebble.go:1582  [n1,s1,pebble] 1 !
F260305 18:47:17.778700 16548 storage/pebble.go:1582  [n1,s1,pebble] 1 !goroutine 9888 [chan receive]:
F260305 18:47:17.778700 16548 storage/pebble.go:1582  [n1,s1,pebble] 1 !testing.(*T).Run(0xc003ed4540, {0xc00d7a8000?, 0xc003defea8?}, 0xc001742000)
F260305 18:47:17.778700 16548 storage/pebble.go:1582  [n1,s1,pebble] 1 !	GOROOT/src/testing/testing.go:2005 +0x485
F260305 18:47:17.778700 16548 storage/pebble.go:1582  [n1,s1,pebble] 1 !github.com/cockroachdb/cockroach/pkg/testutils.RunValues[...](0xc003ed4540, {0x6056a14, 0xa}, {0xc003deff24, 0x3, 0x5cf840}, 0x643d1d8?)
F260305 18:47:17.778700 16548 storage/pebble.go:1582  [n1,s1,pebble] 1 !	pkg/testutils/subtest.go:22 +0x88
F260305 18:47:17.778700 16548 storage/pebble.go:1582  [n1,s1,pebble] 1 !github.com/cockroachdb/cockroach/pkg/kv/kvserver/loqrecovery_test.TestFindUpdateRaft(0xc003ed4540)
F260305 18:47:17.778700 16548 storage/pebble.go:1582  [n1,s1,pebble] 1 !	pkg/kv/kvserver/loqrecovery/collect_raft_log_test.go:101 +0xd4
F260305 18:47:17.778700 16548 storage/pebble.go:1582  [n1,s1,pebble] 1 !testing.tRunner(0xc003ed4540, 0x643ced0)
F260305 18:47:17.778700 16548 storage/pebble.go:1582  [n1,s1,pebble] 1 !	GOROOT/src/testing/testing.go:1934 +0xea
F260305 18:47:17.778700 16548 storage/pebble.go:1582  [n1,s1,pebble] 1 !created by testing.(*T).Run in goroutine 1
F260305 18:47:17.778700 16548 storage/pebble.go:1582  [n1,s1,pebble] 1 !	GOROOT/src/testing/testing.go:1997 +0x465
F260305 18:47:17.778700 16548 storage/pebble.go:1582  [n1,s1,pebble] 1 !
F260305 18:47:17.778700 16548 storage/pebble.go:1582  [n1,s1,pebble] 1 !goroutine 9889 [select]:
F260305 18:47:17.778700 16548 storage/pebble.go:1582  [n1,s1,pebble] 1 !github.com/cockroachdb/cockroach/pkg/util/log.(*fileSink).gcDaemon(0xc004732000, {0x6d8be00, 0xc00e22a0a0})
F260305 18:47:17.778700 16548 storage/pebble.go:1582  [n1,s1,pebble] 1 !	pkg/util/log/file_log_gc.go:20 +0x79
F260305 18:47:17.778700 16548 storage/pebble.go:1582  [n1,s1,pebble] 1 !created by github.com/cockroachdb/cockroach/pkg/util/log.applyConfigInternal in goroutine 9888
F260305 18:47:17.778700 16548 storage/pebble.go:1582  [n1,s1,pebble] 1 !	pkg/util/log/flags.go:400 +0x1295
F260305 18:47:17.778700 16548 storage/pebble.go:1582  [n1,s1,pebble] 1 !
F260305 18:47:17.778700 16548 storage/pebble.go:1582  [n1,s1,pebble] 1 !goroutine 16972 [select]:
F260305 18:47:17.778700 16548 storage/pebble.go:1582  [n1,s1,pebble] 1 !github.com/cockroachdb/pebble/vfs.(*diskHealthCheckingFile).startTicker.func1()
F260305 18:47:17.778700 16548 storage/pebble.go:1582  [n1,s1,pebble] 1 !	external/com_github_cockroachdb_pebble/vfs/disk_health.go:254 +0xb3
F260305 18:47:17.778700 16548 storage/pebble.go:1582  [n1,s1,pebble] 1 !created by github.com/cockroachdb/pebble/vfs.(*diskHealthCheckingFile).startTicker in goroutine 16548
F260305 18:47:17.778700 16548 storage/pebble.go:1582  [n1,s1,pebble] 1 !	external/com_github_cockroachdb_pebble/vfs/disk_health.go:249 +0x58
F260305 18:47:17.778700 16548 storage/pebble.go:1582  [n1,s1,pebble] 1 !
F260305 18:47:17.778700 16548 storage/pebble.go:1582  [n1,s1,pebble] 1 !goroutine 16974 [chan receive, "pebble":"gc"]:
F260305 18:47:17.778700 16548 storage/pebble.go:1582  [n1,s1,pebble] 1 !github.com/cockroachdb/pebble/internal/deletepacer.(*DeletePacer).mainLoop(0xc00dcc2f08)
F260305 18:47:17.778700 16548 storage/pebble.go:1582  [n1,s1,pebble] 1 !	external/com_github_cockroachdb_pebble/internal/deletepacer/delete_pacer.go:183 +0x33b
F260305 18:47:17.778700 16548 storage/pebble.go:1582  [n1,s1,pebble] 1 !github.com/cockroachdb/pebble/internal/deletepacer.Open.func1.1({0x6d8be38?, 0xc014dac9f0?})
F260305 18:47:17.778700 16548 storage/pebble.go:1582  [n1,s1,pebble] 1 !	external/com_github_cockroachdb_pebble/internal/deletepacer/delete_pacer.go:108 +0x17
F260305 18:47:17.778700 16548 storage/pebble.go:1582  [n1,s1,pebble] 1 !runtime/pprof.Do({0x6d8bbb0?, 0xb032000?}, {{0xc0019077c0?, 0x7f878d57de10?, 0x10000c00288c04a?}}, 0xc00288bfa0)
F260305 18:47:17.778700 16548 storage/pebble.go:1582  [n1,s1,pebble] 1 !	GOROOT/src/runtime/pprof/runtime.go:51 +0x8c
F260305 18:47:17.778700 16548 storage/pebble.go:1582  [n1,s1,pebble] 1 !github.com/cockroachdb/pebble/internal/deletepacer.Open.func1()
F260305 18:47:17.778700 16548 storage/pebble.go:1582  [n1,s1,pebble] 1 !	external/com_github_cockroachdb_pebble/internal/deletepacer/delete_pacer.go:107 +0x9c
F260305 18:47:17.778700 16548 storage/pebble.go:1582  [n1,s1,pebble] 1 !created by github.com/cockroachdb/pebble/internal/deletepacer.Open in goroutine 16548
F260305 18:47:17.778700 16548 storage/pebble.go:1582  [n1,s1,pebble] 1 !	external/com_github_cockroachdb_pebble/internal/deletepacer/delete_pacer.go:106 +0x229
F260305 18:47:17.778700 16548 storage/pebble.go:1582  [n1,s1,pebble] 1 !
F260305 18:47:17.778700 16548 storage/pebble.go:1582  [n1,s1,pebble] 1 !goroutine 9891 [select]:
F260305 18:47:17.778700 16548 storage/pebble.go:1582  [n1,s1,pebble] 1 !github.com/cockroachdb/cockroach/pkg/util/log.(*fileSink).gcDaemon(0xc0047321c0, {0x6d8be00, 0xc00e22a0a0})
F260305 18:47:17.778700 16548 storage/pebble.go:1582  [n1,s1,pebble] 1 !	pkg/util/log/file_log_gc.go:20 +0x79
F260305 18:47:17.778700 16548 storage/pebble.go:1582  [n1,s1,pebble] 1 !created by github.com/cockroachdb/cockroach/pkg/util/log.applyConfigInternal in goroutine 9888
F260305 18:47:17.778700 16548 storage/pebble.go:1582  [n1,s1,pebble] 1 !	pkg/util/log/flags.go:400 +0x1295
F260305 18:47:17.778700 16548 storage/pebble.go:1582  [n1,s1,pebble] 1 !
F260305 18:47:17.778700 16548 storage/pebble.go:1582  [n1,s1,pebble] 1 !goroutine 9890 [select]:
F260305 18:47:17.778700 16548 storage/pebble.go:1582  [n1,s1,pebble] 1 !github.com/cockroachdb/cockroach/pkg/util/log.(*fileSink).gcDaemon(0xc0047320e0, {0x6d8be00, 0xc00e22a0a0})
F260305 18:47:17.778700 16548 storage/pebble.go:1582  [n1,s1,pebble] 1 !	pkg/util/log/file_log_gc.go:20 +0x79
F260305 18:47:17.778700 16548 storage/pebble.go:1582  [n1,s1,pebble] 1 !created by github.com/cockroachdb/cockroach/pkg/util/log.applyConfigInternal in goroutine 9888
F260305 18:47:17.778700 16548 storage/pebble.go:1582  [n1,s1,pebble] 1 !	pkg/util/log/flags.go:400 +0x1295
F260305 18:47:17.778700 16548 storage/pebble.go:1582  [n1,s1,pebble] 1 !
F260305 18:47:17.778700 16548 storage/pebble.go:1582  [n1,s1,pebble] 1 !goroutine 17031 [sync.Cond.Wait, "pebble":"wal-sync"]:
F260305 18:47:17.778700 16548 storage/pebble.go:1582  [n1,s1,pebble] 1 !sync.runtime_notifyListWait(0xc0049320a8, 0x0)
F260305 18:47:17.778700 16548 storage/pebble.go:1582  [n1,s1,pebble] 1 !	GOROOT/src/runtime/sema.go:606 +0x159
F260305 18:47:17.778700 16548 storage/pebble.go:1582  [n1,s1,pebble] 1 !sync.(*Cond).Wait(0x0?)
F260305 18:47:17.778700 16548 storage/pebble.go:1582  [n1,s1,pebble] 1 !	GOROOT/src/sync/cond.go:71 +0x73
F260305 18:47:17.778700 16548 storage/pebble.go:1582  [n1,s1,pebble] 1 !github.com/cockroachdb/pebble/record.(*flusherCond).Wait(...)
F260305 18:47:17.778700 16548 storage/pebble.go:1582  [n1,s1,pebble] 1 !	external/com_github_cockroachdb_pebble/record/log_writer.go:371
F260305 18:47:17.778700 16548 storage/pebble.go:1582  [n1,s1,pebble] 1 !github.com/cockroachdb/pebble/record.(*LogWriter).flushLoop(0xc004932000, {0x56a4fc0?, 0xb032000?})
F260305 18:47:17.778700 16548 storage/pebble.go:1582  [n1,s1,pebble] 1 !	external/com_github_cockroachdb_pebble/record/log_writer.go:682 +0x785
F260305 18:47:17.778700 16548 storage/pebble.go:1582  [n1,s1,pebble] 1 !runtime/pprof.Do({0x6d8bbb0?, 0xb032000?}, {{0xc000ff8440?, 0xc0046537d0?, 0x48cd12?}}, 0xc0046537c0)
F260305 18:47:17.778700 16548 storage/pebble.go:1582  [n1,s1,pebble] 1 !	GOROOT/src/runtime/pprof/runtime.go:51 +0x8c
F260305 18:47:17.778700 16548 storage/pebble.go:1582  [n1,s1,pebble] 1 !github.com/cockroachdb/pebble/record.NewLogWriter.func2()
F260305 18:47:17.778700 16548 storage/pebble.go:1582  [n1,s1,pebble] 1 !	external/com_github_cockroachdb_pebble/record/log_writer.go:596 +0x50
F260305 18:47:17.778700 16548 storage/pebble.go:1582  [n1,s1,pebble] 1 !created by github.com/cockroachdb/pebble/record.NewLogWriter in goroutine 16548
F260305 18:47:17.778700 16548 storage/pebble.go:1582  [n1,s1,pebble] 1 !	external/com_github_cockroachdb_pebble/record/log_writer.go:595 +0x55c
F260305 18:47:17.778700 16548 storage/pebble.go:1582  [n1,s1,pebble] 1 !
F260305 18:47:17.778700 16548 storage/pebble.go:1582  [n1,s1,pebble] 1 !goroutine 19922 [select]:
F260305 18:47:17.778700 16548 storage/pebble.go:1582  [n1,s1,pebble] 1 !github.com/cockroachdb/pebble.(*DB).maybeScheduleDelayedFlush.func1()
F260305 18:47:17.778700 16548 storage/pebble.go:1582  [n1,s1,pebble] 1 !	external/com_github_cockroachdb_pebble/compaction.go:1437 +0xed
F260305 18:47:17.778700 16548 storage/pebble.go:1582  [n1,s1,pebble] 1 !created by github.com/cockroachdb/pebble.(*DB).maybeScheduleDelayedFlush in goroutine 19013
F260305 18:47:17.778700 16548 storage/pebble.go:1582  [n1,s1,pebble] 1 !	external/com_github_cockroachdb_pebble/compaction.go:1433 +0x19a
F260305 18:47:17.778700 16548 storage/pebble.go:1582  [n1,s1,pebble] 1 !
F260305 18:47:17.778700 16548 storage/pebble.go:1582  [n1,s1,pebble] 1 !goroutine 19039 [select]:
F260305 18:47:17.778700 16548 storage/pebble.go:1582  [n1,s1,pebble] 1 !github.com/cockroachdb/cockroach/pkg/util/admission.initWorkQueue.func2()
F260305 18:47:17.778700 16548 storage/pebble.go:1582  [n1,s1,pebble] 1 !	pkg/util/admission/work_queue.go:417 +0x85
F260305 18:47:17.778700 16548 storage/pebble.go:1582  [n1,s1,pebble] 1 !created by github.com/cockroachdb/cockroach/pkg/util/admission.initWorkQueue in goroutine 16548
F260305 18:47:17.778700 16548 storage/pebble.go:1582  [n1,s1,pebble] 1 !	pkg/util/admission/work_queue.go:414 +0x30d
F260305 18:47:17.778700 16548 storage/pebble.go:1582  [n1,s1,pebble] 1 !
F260305 18:47:17.778700 16548 storage/pebble.go:1582  [n1,s1,pebble] 1 !goroutine 19825 [select]:
F260305 18:47:17.778700 16548 storage/pebble.go:1582  [n1,s1,pebble] 1 !github.com/cockroachdb/pebble.(*DB).maybeScheduleDelayedFlush.func1()
F260305 18:47:17.778700 16548 storage/pebble.go:1582  [n1,s1,pebble] 1 !	external/com_github_cockroachdb_pebble/compaction.go:1437 +0xed
F260305 18:47:17.778700 16548 storage/pebble.go:1582  [n1,s1,pebble] 1 !created by github.com/cockroachdb/pebble.(*DB).maybeScheduleDelayedFlush in goroutine 19789
F260305 18:47:17.778700 16548 storage/pebble.go:1582  [n1,s1,pebble] 1 !	external/com_github_cockroachdb_pebble/compaction.go:1433 +0x19a
F260305 18:47:17.778700 16548 storage/pebble.go:1582  [n1,s1,pebble] 1 !
F260305 18:47:17.778700 16548 storage/pebble.go:1582  [n1,s1,pebble] 1 !goroutine 17017 [select]:
F260305 18:47:17.778700 16548 storage/pebble.go:1582  [n1,s1,pebble] 1 !github.com/cockroachdb/cockroach/pkg/util/timeutil.(*BroadcastTicker).run(...)
F260305 18:47:17.778700 16548 storage/pebble.go:1582  [n1,s1,pebble] 1 !	pkg/util/timeutil/ticker.go:58
F260305 18:47:17.778700 16548 storage/pebble.go:1582  [n1,s1,pebble] 1 !created by github.com/cockroachdb/cockroach/pkg/util/timeutil.NewBroadcastTicker in goroutine 16548
F260305 18:47:17.778700 16548 storage/pebble.go:1582  [n1,s1,pebble] 1 !	pkg/util/timeutil/ticker.go:52 +0xae
F260305 18:47:17.778700 16548 storage/pebble.go:1582  [n1,s1,pebble] 1 !
F260305 18:47:17.778700 16548 storage/pebble.go:1582  [n1,s1,pebble] 1 !goroutine 19044 [select]:
F260305 18:47:17.778700 16548 storage/pebble.go:1582  [n1,s1,pebble] 1 !github.com/cockroachdb/cockroach/pkg/util/admission.(*StoreGrantCoordinators).SetPebbleMetricsProvider.func1()
F260305 18:47:17.778700 16548 storage/pebble.go:1582  [n1,s1,pebble] 1 !	pkg/util/admission/store_grant_coordinator.go:158 +0x11b
F260305 18:47:17.778700 16548 storage/pebble.go:1582  [n1,s1,pebble] 1 !created by github.com/cockroachdb/cockroach/pkg/util/admission.(*StoreGrantCoordinators).SetPebbleMetricsProvider in goroutine 16548
F260305 18:47:17.778700 16548 storage/pebble.go:1582  [n1,s1,pebble] 1 !	pkg/util/admission/store_grant_coordinator.go:148 +0x40a
F260305 18:47:17.778700 16548 storage/pebble.go:1582  [n1,s1,pebble] 1 !
F260305 18:47:17.778700 16548 storage/pebble.go:1582  [n1,s1,pebble] 1 !goroutine 19733 [select]:
F260305 18:47:17.778700 16548 storage/pebble.go:1582  [n1,s1,pebble] 1 !database/sql.(*DB).connectionOpener(0xc00af44dd0, {0x6d8be00, 0xc001a1ac80})
F260305 18:47:17.778700 16548 storage/pebble.go:1582  [n1,s1,pebble] 1 !	GOROOT/src/database/sql/sql.go:1261 +0x87
F260305 18:47:17.778700 16548 storage/pebble.go:1582  [n1,s1,pebble] 1 !created by database/sql.OpenDB in goroutine 16548
F260305 18:47:17.778700 16548 storage/pebble.go:1582  [n1,s1,pebble] 1 !	GOROOT/src/database/sql/sql.go:841 +0x130
F260305 18:47:17.778700 16548 storage/pebble.go:1582  [n1,s1,pebble] 1 !
F260305 18:47:17.778700 16548 storage/pebble.go:1582  [n1,s1,pebble] 1 !goroutine 17012 [select]:
F260305 18:47:17.778700 16548 storage/pebble.go:1582  [n1,s1,pebble] 1 !github.com/cockroachdb/cockroach/pkg/util/admission.initWorkQueue.func2()
F260305 18:47:17.778700 16548 storage/pebble.go:1582  [n1,s1,pebble] 1 !	pkg/util/admission/work_queue.go:417 +0x85
F260305 18:47:17.778700 16548 storage/pebble.go:1582  [n1,s1,pebble] 1 !created by github.com/cockroachdb/cockroach/pkg/util/admission.initWorkQueue in goroutine 16548
F260305 18:47:17.778700 16548 storage/pebble.go:1582  [n1,s1,pebble] 1 !	pkg/util/admission/work_queue.go:414 +0x30d
F260305 18:47:17.778700 16548 storage/pebble.go:1582  [n1,s1,pebble] 1 !
F260305 18:47:17.778700 16548 storage/pebble.go:1582  [n1,s1,pebble] 1 !goroutine 17004 [select]:
F260305 18:47:17.778700 16548 storage/pebble.go:1582  [n1,s1,pebble] 1 !github.com/cockroachdb/cockroach/pkg/util/admission.initWorkQueue.func2()
F260305 18:47:17.778700 16548 storage/pebble.go:1582  [n1,s1,pebble] 1 !	pkg/util/admission/work_queue.go:417 +0x85
F260305 18:47:17.778700 16548 storage/pebble.go:1582  [n1,s1,pebble] 1 !created by github.com/cockroachdb/cockroach/pkg/util/admission.initWorkQueue in goroutine 16548
F260305 18:47:17.778700 16548 storage/pebble.go:1582  [n1,s1,pebble] 1 !	pkg/util/admission/work_queue.go:414 +0x30d
F260305 18:47:17.778700 16548 storage/pebble.go:1582  [n1,s1,pebble] 1 !
F260305 18:47:17.778700 16548 storage/pebble.go:1582  [n1,s1,pebble] 1 !goroutine 17015 [select]:
F260305 18:47:17.778700 16548 storage/pebble.go:1582  [n1,s1,pebble] 1 !github.com/cockroachdb/cockroach/pkg/util/admission.(*WorkQueue).startClosingEpochs.func1()
F260305 18:47:17.778700 16548 storage/pebble.go:1582  [n1,s1,pebble] 1 !	pkg/util/admission/work_queue.go:527 +0x145
F260305 18:47:17.778700 16548 storage/pebble.go:1582  [n1,s1,pebble] 1 !created by github.com/cockroachdb/cockroach/pkg/util/admission.(*WorkQueue).startClosingEpochs in goroutine 16548
F260305 18:47:17.778700 16548 storage/pebble.go:1582  [n1,s1,pebble] 1 !	pkg/util/admission/work_queue.go:498 +0x4f
F260305 18:47:17.778700 16548 storage/pebble.go:1582  [n1,s1,pebble] 1 !
F260305 18:47:17.778700 16548 storage/pebble.go:1582  [n1,s1,pebble] 1 !goroutine 17013 [select]:
F260305 18:47:17.778700 16548 storage/pebble.go:1582  [n1,s1,pebble] 1 !github.com/cockroachdb/cockroach/pkg/util/admission.(*WorkQueue).startClosingEpochs.func1()
F260305 18:47:17.778700 16548 storage/pebble.go:1582  [n1,s1,pebble] 1 !	pkg/util/admission/work_queue.go:527 +0x145
F260305 18:47:17.778700 16548 storage/pebble.go:1582  [n1,s1,pebble] 1 !created by github.com/cockroachdb/cockroach/pkg/util/admission.(*WorkQueue).startClosingEpochs in goroutine 16548
F260305 18:47:17.778700 16548 storage/pebble.go:1582  [n1,s1,pebble] 1 !	pkg/util/admission/work_queue.go:498 +0x4f
F260305 18:47:17.778700 16548 storage/pebble.go:1582  [n1,s1,pebble] 1 !
F260305 18:47:17.778700 16548 storage/pebble.go:1582  [n1,s1,pebble] 1 !goroutine 17008 [select]:
F260305 18:47:17.778700 16548 storage/pebble.go:1582  [n1,s1,pebble] 1 !github.com/cockroachdb/cockroach/pkg/util/admission.initWorkQueue.func2()
F260305 18:47:17.778700 16548 storage/pebble.go:1582  [n1,s1,pebble] 1 !	pkg/util/admission/work_queue.go:417 +0x85
F260305 18:47:17.778700 16548 storage/pebble.go:1582  [n1,s1,pebble] 1 !created by github.com/cockroachdb/cockroach/pkg/util/admission.initWorkQueue in goroutine 16548
F260305 18:47:17.778700 16548 storage/pebble.go:1582  [n1,s1,pebble] 1 !	pkg/util/admission/work_queue.go:414 +0x30d
F260305 18:47:17.778700 16548 storage/pebble.go:1582  [n1,s1,pebble] 1 !
F260305 18:47:17.778700 16548 storage/pebble.go:1582  [n1,s1,pebble] 1 !goroutine 17407 [runnable]:
F260305 18:47:17.778700 16548 storage/pebble.go:1582  [n1,s1,pebble] 1 !github.com/cockroachdb/pebble/vfs.(*diskHealthCheckingFile).startTicker.func1()
F260305 18:47:17.778700 16548 storage/pebble.go:1582  [n1,s1,pebble] 1 !	external/com_github_cockroachdb_pebble/vfs/disk_health.go:254 +0xb3
F260305 18:47:17.778700 16548 storage/pebble.go:1582  [n1,s1,pebble] 1 !created by github.com/cockroachdb/pebble/vfs.(*diskHealthCheckingFile).startTicker in goroutine 16548
F260305 18:47:17.778700 16548 storage/pebble.go:1582  [n1,s1,pebble] 1 !	external/com_github_cockroachdb_pebble/vfs/disk_health.go:249 +0x58
F260305 18:47:17.778700 16548 storage/pebble.go:1582  [n1,s1,pebble] 1 !
F260305 18:47:17.778700 16548 storage/pebble.go:1582  [n1,s1,pebble] 1 !goroutine 19042 [select]:
F260305 18:47:17.778700 16548 storage/pebble.go:1582  [n1,s1,pebble] 1 !github.com/cockroachdb/cockroach/pkg/util/admission.(*WorkQueue).startClosingEpochs.func1()
F260305 18:47:17.778700 16548 storage/pebble.go:1582  [n1,s1,pebble] 1 !	pkg/util/admission/work_queue.go:527 +0x145
F260305 18:47:17.778700 16548 storage/pebble.go:1582  [n1,s1,pebble] 1 !created by github.com/cockroachdb/cockroach/pkg/util/admission.(*WorkQueue).startClosingEpochs in goroutine 16548
F260305 18:47:17.778700 16548 storage/pebble.go:1582  [n1,s1,pebble] 1 !	pkg/util/admission/work_queue.go:498 +0x4f
F260305 18:47:17.778700 16548 storage/pebble.go:1582  [n1,s1,pebble] 1 !
F260305 18:47:17.778700 16548 storage/pebble.go:1582  [n1,s1,pebble] 1 !goroutine 9892 [select]:
F260305 18:47:17.778700 16548 storage/pebble.go:1582  [n1,s1,pebble] 1 !github.com/cockroachdb/cockroach/pkg/util/log.(*fileSink).gcDaemon(0xc0047322a0, {0x6d8be00, 0xc00e22a0a0})
F260305 18:47:17.778700 16548 storage/pebble.go:1582  [n1,s1,pebble] 1 !	pkg/util/log/file_log_gc.go:20 +0x79
F260305 18:47:17.778700 16548 storage/pebble.go:1582  [n1,s1,pebble] 1 !created by github.com/cockroachdb/cockroach/pkg/util/log.applyConfigInternal in goroutine 9888
F260305 18:47:17.778700 16548 storage/pebble.go:1582  [n1,s1,pebble] 1 !	pkg/util/log/flags.go:400 +0x1295
F260305 18:47:17.778700 16548 storage/pebble.go:1582  [n1,s1,pebble] 1 !
F260305 18:47:17.778700 16548 storage/pebble.go:1582  [n1,s1,pebble] 1 !goroutine 17010 [select]:
F260305 18:47:17.778700 16548 storage/pebble.go:1582  [n1,s1,pebble] 1 !github.com/cockroachdb/cockroach/pkg/util/admission.initWorkQueue.func2()
F260305 18:47:17.778700 16548 storage/pebble.go:1582  [n1,s1,pebble] 1 !	pkg/util/admission/work_queue.go:417 +0x85
F260305 18:47:17.778700 16548 storage/pebble.go:1582  [n1,s1,pebble] 1 !created by github.com/cockroachdb/cockroach/pkg/util/admission.initWorkQueue in goroutine 16548
F260305 18:47:17.778700 16548 storage/pebble.go:1582  [n1,s1,pebble] 1 !	pkg/util/admission/work_queue.go:414 +0x30d
F260305 18:47:17.778700 16548 storage/pebble.go:1582  [n1,s1,pebble] 1 !
F260305 18:47:17.778700 16548 storage/pebble.go:1582  [n1,s1,pebble] 1 !goroutine 17030 [select]:
F260305 18:47:17.778700 16548 storage/pebble.go:1582  [n1,s1,pebble] 1 !github.com/cockroachdb/pebble/vfs.(*diskHealthCheckingFile).startTicker.func1()
F260305 18:47:17.778700 16548 storage/pebble.go:1582  [n1,s1,pebble] 1 !	external/com_github_cockroachdb_pebble/vfs/disk_health.go:254 +0xb3
F260305 18:47:17.778700 16548 storage/pebble.go:1582  [n1,s1,pebble] 1 !created by github.com/cockroachdb/pebble/vfs.(*diskHealthCheckingFile).startTicker in goroutine 16548
F260305 18:47:17.778700 16548 storage/pebble.go:1582  [n1,s1,pebble] 1 !	external/com_github_cockroachdb_pebble/vfs/disk_health.go:249 +0x58
F260305 18:47:17.778700 16548 storage/pebble.go:1582  [n1,s1,pebble] 1 !
F260305 18:47:17.778700 16548 storage/pebble.go:1582  [n1,s1,pebble] 1 !goroutine 17006 [select]:
F260305 18:47:17.778700 16548 storage/pebble.go:1582  [n1,s1,pebble] 1 !github.com/cockroachdb/cockroach/pkg/util/admission.initWorkQueue.func2()
F260305 18:47:17.778700 16548 storage/pebble.go:1582  [n1,s1,pebble] 1 !	pkg/util/admission/work_queue.go:417 +0x85
F260305 18:47:17.778700 16548 storage/pebble.go:1582  [n1,s1,pebble] 1 !created by github.com/cockroachdb/cockroach/pkg/util/admission.initWorkQueue in goroutine 16548
F260305 18:47:17.778700 16548 storage/pebble.go:1582  [n1,s1,pebble] 1 !	pkg/util/admission/work_queue.go:414 +0x30d
F260305 18:47:17.778700 16548 storage/pebble.go:1582  [n1,s1,pebble] 1 !
F260305 18:47:17.778700 16548 storage/pebble.go:1582  [n1,s1,pebble] 1 !goroutine 17007 [select]:
F260305 18:47:17.778700 16548 storage/pebble.go:1582  [n1,s1,pebble] 1 !github.com/cockroachdb/cockroach/pkg/util/admission.(*WorkQueue).startClosingEpochs.func1()
F260305 18:47:17.778700 16548 storage/pebble.go:1582  [n1,s1,pebble] 1 !	pkg/util/admission/work_queue.go:527 +0x145
F260305 18:47:17.778700 16548 storage/pebble.go:1582  [n1,s1,pebble] 1 !created by github.com/cockroachdb/cockroach/pkg/util/admission.(*WorkQueue).startClosingEpochs in goroutine 16548
F260305 18:47:17.778700 16548 storage/pebble.go:1582  [n1,s1,pebble] 1 !	pkg/util/admission/work_queue.go:498 +0x4f
F260305 18:47:17.778700 16548 storage/pebble.go:1582  [n1,s1,pebble] 1 !
F260305 18:47:17.778700 16548 storage/pebble.go:1582  [n1,s1,pebble] 1 !goroutine 16977 [select]:
F260305 18:47:17.778700 16548 storage/pebble.go:1582  [n1,s1,pebble] 1 !github.com/cockroachdb/pebble.(*ConcurrencyLimitScheduler).periodicGranter(0xc0048b9980)
F260305 18:47:17.778700 16548 storage/pebble.go:1582  [n1,s1,pebble] 1 !	external/com_github_cockroachdb_pebble/compaction_scheduler.go:414 +0x9f
F260305 18:47:17.778700 16548 storage/pebble.go:1582  [n1,s1,pebble] 1 !created by github.com/cockroachdb/pebble.(*ConcurrencyLimitScheduler).Register in goroutine 16548
F260305 18:47:17.778700 16548 storage/pebble.go:1582  [n1,s1,pebble] 1 !	external/com_github_cockroachdb_pebble/compaction_scheduler.go:305 +0x96
F260305 18:47:17.778700 16548 storage/pebble.go:1582  [n1,s1,pebble] 1 !
F260305 18:47:17.778700 16548 storage/pebble.go:1582  [n1,s1,pebble] 1 !goroutine 17026 [chan receive, "pebble":"gc"]:
F260305 18:47:17.778700 16548 storage/pebble.go:1582  [n1,s1,pebble] 1 !github.com/cockroachdb/pebble/internal/deletepacer.(*DeletePacer).mainLoop(0xc00f18f908)
F260305 18:47:17.778700 16548 storage/pebble.go:1582  [n1,s1,pebble] 1 !	external/com_github_cockroachdb_pebble/internal/deletepacer/delete_pacer.go:183 +0x33b
F260305 18:47:17.778700 16548 storage/pebble.go:1582  [n1,s1,pebble] 1 !github.com/cockroachdb/pebble/internal/deletepacer.Open.func1.1({0x6d8be38?, 0xc014dad170?})
F260305 18:47:17.778700 16548 storage/pebble.go:1582  [n1,s1,pebble] 1 !	external/com_github_cockroachdb_pebble/internal/deletepacer/delete_pacer.go:108 +0x17
F260305 18:47:17.778700 16548 storage/pebble.go:1582  [n1,s1,pebble] 1 !runtime/pprof.Do({0x6d8bbb0?, 0xb032000?}, {{0xc0019077e0?, 0xc00dd25ee0?, 0x10000c00dd1b3b0?}}, 0xc002c597a0)
F260305 18:47:17.778700 16548 storage/pebble.go:1582  [n1,s1,pebble] 1 !	GOROOT/src/runtime/pprof/runtime.go:51 +0x8c
F260305 18:47:17.778700 16548 storage/pebble.go:1582  [n1,s1,pebble] 1 !github.com/cockroachdb/pebble/internal/deletepacer.Open.func1()
F260305 18:47:17.778700 16548 storage/pebble.go:1582  [n1,s1,pebble] 1 !	external/com_github_cockroachdb_pebble/internal/deletepacer/delete_pacer.go:107 +0x9c
F260305 18:47:17.778700 16548 storage/pebble.go:1582  [n1,s1,pebble] 1 !created by github.com/cockroachdb/pebble/internal/deletepacer.Open in goroutine 16548
F260305 18:47:17.778700 16548 storage/pebble.go:1582  [n1,s1,pebble] 1 !	external/com_github_cockroachdb_pebble/internal/deletepacer/delete_pacer.go:106 +0x229
F260305 18:47:17.778700 16548 storage/pebble.go:1582  [n1,s1,pebble] 1 !
F260305 18:47:17.778700 16548 storage/pebble.go:1582  [n1,s1,pebble] 1 !goroutine 17011 [select]:
F260305 18:47:17.778700 16548 storage/pebble.go:1582  [n1,s1,pebble] 1 !github.com/cockroachdb/cockroach/pkg/util/admission.(*WorkQueue).startClosingEpochs.func1()
F260305 18:47:17.778700 16548 storage/pebble.go:1582  [n1,s1,pebble] 1 !	pkg/util/admission/work_queue.go:527 +0x145
F260305 18:47:17.778700 16548 storage/pebble.go:1582  [n1,s1,pebble] 1 !created by github.com/cockroachdb/cockroach/pkg/util/admission.(*WorkQueue).startClosingEpochs in goroutine 16548
F260305 18:47:17.778700 16548 storage/pebble.go:1582  [n1,s1,pebble] 1 !	pkg/util/admission/work_queue.go:498 +0x4f
F260305 18:47:17.778700 16548 storage/pebble.go:1582  [n1,s1,pebble] 1 !
F260305 18:47:17.778700 16548 storage/pebble.go:1582  [n1,s1,pebble] 1 !goroutine 17022 [select]:
F260305 18:47:17.778700 16548 storage/pebble.go:1582  [n1,s1,pebble] 1 !github.com/cockroachdb/pebble/vfs.(*diskHealthCheckingFS).startTickerLocked.func1()
F260305 18:47:17.778700 16548 storage/pebble.go:1582  [n1,s1,pebble] 1 !	external/com_github_cockroachdb_pebble/vfs/disk_health.go:682 +0xf8
F260305 18:47:17.778700 16548 storage/pebble.go:1582  [n1,s1,pebble] 1 !created by github.com/cockroachdb/pebble/vfs.(*diskHealthCheckingFS).startTickerLocked in goroutine 16548
F260305 18:47:17.778700 16548 storage/pebble.go:1582  [n1,s1,pebble] 1 !	external/com_github_cockroachdb_pebble/vfs/disk_health.go:671 +0x6e
F260305 18:47:17.778700 16548 storage/pebble.go:1582  [n1,s1,pebble] 1 !
F260305 18:47:17.778700 16548 storage/pebble.go:1582  [n1,s1,pebble] 1 !goroutine 16970 [select]:
F260305 18:47:17.778700 16548 storage/pebble.go:1582  [n1,s1,pebble] 1 !github.com/cockroachdb/pebble/vfs.(*diskHealthCheckingFS).startTickerLocked.func1()
F260305 18:47:17.778700 16548 storage/pebble.go:1582  [n1,s1,pebble] 1 !	external/com_github_cockroachdb_pebble/vfs/disk_health.go:682 +0xf8
F260305 18:47:17.778700 16548 storage/pebble.go:1582  [n1,s1,pebble] 1 !created by github.com/cockroachdb/pebble/vfs.(*diskHealthCheckingFS).startTickerLocked in goroutine 16548
F260305 18:47:17.778700 16548 storage/pebble.go:1582  [n1,s1,pebble] 1 !	external/com_github_cockroachdb_pebble/vfs/disk_health.go:671 +0x6e
F260305 18:47:17.778700 16548 storage/pebble.go:1582  [n1,s1,pebble] 1 !
F260305 18:47:17.778700 16548 storage/pebble.go:1582  [n1,s1,pebble] 1 !goroutine 19041 [select]:
F260305 18:47:17.778700 16548 storage/pebble.go:1582  [n1,s1,pebble] 1 !github.com/cockroachdb/cockroach/pkg/util/admission.initWorkQueue.func2()
F260305 18:47:17.778700 16548 storage/pebble.go:1582  [n1,s1,pebble] 1 !	pkg/util/admission/work_queue.go:417 +0x85
F260305 18:47:17.778700 16548 storage/pebble.go:1582  [n1,s1,pebble] 1 !created by github.com/cockroachdb/cockroach/pkg/util/admission.initWorkQueue in goroutine 16548
F260305 18:47:17.778700 16548 storage/pebble.go:1582  [n1,s1,pebble] 1 !	pkg/util/admission/work_queue.go:414 +0x30d
F260305 18:47:17.778700 16548 storage/pebble.go:1582  [n1,s1,pebble] 1 !
F260305 18:47:17.778700 16548 storage/pebble.go:1582  [n1,s1,pebble] 1 !goroutine 17005 [select]:
F260305 18:47:17.778700 16548 storage/pebble.go:1582  [n1,s1,pebble] 1 !github.com/cockroachdb/cockroach/pkg/util/admission.(*WorkQueue).startClosingEpochs.func1()
F260305 18:47:17.778700 16548 storage/pebble.go:1582  [n1,s1,pebble] 1 !	pkg/util/admission/work_queue.go:527 +0x145
F260305 18:47:17.778700 16548 storage/pebble.go:1582  [n1,s1,pebble] 1 !created by github.com/cockroachdb/cockroach/pkg/util/admission.(*WorkQueue).startClosingEpochs in goroutine 16548
F260305 18:47:17.778700 16548 storage/pebble.go:1582  [n1,s1,pebble] 1 !	pkg/util/admission/work_queue.go:498 +0x4f
F260305 18:47:17.778700 16548 storage/pebble.go:1582  [n1,s1,pebble] 1 !
F260305 18:47:17.778700 16548 storage/pebble.go:1582  [n1,s1,pebble] 1 !goroutine 17009 [select]:
F260305 18:47:17.778700 16548 storage/pebble.go:1582  [n1,s1,pebble] 1 !github.com/cockroachdb/cockroach/pkg/util/admission.(*WorkQueue).startClosingEpochs.func1()
F260305 18:47:17.778700 16548 storage/pebble.go:1582  [n1,s1,pebble] 1 !	pkg/util/admission/work_queue.go:527 +0x145
F260305 18:47:17.778700 16548 storage/pebble.go:1582  [n1,s1,pebble] 1 !created by github.com/cockroachdb/cockroach/pkg/util/admission.(*WorkQueue).startClosingEpochs in goroutine 16548
F260305 18:47:17.778700 16548 storage/pebble.go:1582  [n1,s1,pebble] 1 !	pkg/util/admission/work_queue.go:498 +0x4f
F260305 18:47:17.778700 16548 storage/pebble.go:1582  [n1,s1,pebble] 1 !
F260305 18:47:17.778700 16548 storage/pebble.go:1582  [n1,s1,pebble] 1 !goroutine 17014 [select]:
F260305 18:47:17.778700 16548 storage/pebble.go:1582  [n1,s1,pebble] 1 !github.com/cockroachdb/cockroach/pkg/util/admission.initWorkQueue.func2()
F260305 18:47:17.778700 16548 storage/pebble.go:1582  [n1,s1,pebble] 1 !	pkg/util/admission/work_queue.go:417 +0x85
F260305 18:47:17.778700 16548 storage/pebble.go:1582  [n1,s1,pebble] 1 !created by github.com/cockroachdb/cockroach/pkg/util/admission.initWorkQueue in goroutine 16548
F260305 18:47:17.778700 16548 storage/pebble.go:1582  [n1,s1,pebble] 1 !	pkg/util/admission/work_queue.go:414 +0x30d
F260305 18:47:17.778700 16548 storage/pebble.go:1582  [n1,s1,pebble] 1 !
F260305 18:47:17.778700 16548 storage/pebble.go:1582  [n1,s1,pebble] 1 !goroutine 18933 [select]:
F260305 18:47:17.778700 16548 storage/pebble.go:1582  [n1,s1,pebble] 1 !github.com/cockroachdb/cockroach/pkg/util/hlc.(*Clock).StartMonitoringForwardClockJumps.func1()
F260305 18:47:17.778700 16548 storage/pebble.go:1582  [n1,s1,pebble] 1 !	pkg/util/hlc/hlc.go:298 +0x13d
F260305 18:47:17.778700 16548 storage/pebble.go:1582  [n1,s1,pebble] 1 !created by github.com/cockroachdb/cockroach/pkg/util/hlc.(*Clock).StartMonitoringForwardClockJumps in goroutine 16548
F260305 18:47:17.778700 16548 storage/pebble.go:1582  [n1,s1,pebble] 1 !	pkg/util/hlc/hlc.go:290 +0x106
F260305 18:47:17.778700 16548 storage/pebble.go:1582  [n1,s1,pebble] 1 !
F260305 18:47:17.778700 16548 storage/pebble.go:1582  [n1,s1,pebble] 1 !goroutine 17027 [chan receive]:
F260305 18:47:17.778700 16548 storage/pebble.go:1582  [n1,s1,pebble] 1 !github.com/cockroachdb/pebble/internal/genericcache.(*shard[...]).releaseLoop(0xc0000ec798)
F260305 18:47:17.778700 16548 storage/pebble.go:1582  [n1,s1,pebble] 1 !	external/com_github_cockroachdb_pebble/internal/genericcache/shard.go:61 +0x6f
F260305 18:47:17.778700 16548 storage/pebble.go:1582  [n1,s1,pebble] 1 !created by github.com/cockroachdb/pebble/internal/genericcache.(*shard[...]).Init in goroutine 16548
F260305 18:47:17.778700 16548 storage/pebble.go:1582  [n1,s1,pebble] 1 !	external/com_github_cockroachdb_pebble/internal/genericcache/shard.go:54 +0x1a7
F260305 18:47:17.778700 16548 storage/pebble.go:1582  [n1,s1,pebble] 1 !
F260305 18:47:17.778700 16548 storage/pebble.go:1582  [n1,s1,pebble] 1 !goroutine 16550 [select]:
F260305 18:47:17.778700 16548 storage/pebble.go:1582  [n1,s1,pebble] 1 !github.com/cockroachdb/pebble/vfs.(*diskHealthCheckingFS).startTickerLocked.func1()
F260305 18:47:17.778700 16548 storage/pebble.go:1582  [n1,s1,pebble] 1 !	external/com_github_cockroachdb_pebble/vfs/disk_health.go:682 +0xf8
F260305 18:47:17.778700 16548 storage/pebble.go:1582  [n1,s1,pebble] 1 !created by github.com/cockroachdb/pebble/vfs.(*diskHealthCheckingFS).startTickerLocked in goroutine 16548
F260305 18:47:17.778700 16548 storage/pebble.go:1582  [n1,s1,pebble] 1 !	external/com_github_cockroachdb_pebble/vfs/disk_health.go:671 +0x6e
F260305 18:47:17.778700 16548 storage/pebble.go:1582  [n1,s1,pebble] 1 !
F260305 18:47:17.778700 16548 storage/pebble.go:1582  [n1,s1,pebble] 1 !goroutine 17024 [select]:
F260305 18:47:17.778700 16548 storage/pebble.go:1582  [n1,s1,pebble] 1 !github.com/cockroachdb/pebble/vfs.(*diskHealthCheckingFile).startTicker.func1()
F260305 18:47:17.778700 16548 storage/pebble.go:1582  [n1,s1,pebble] 1 !	external/com_github_cockroachdb_pebble/vfs/disk_health.go:254 +0xb3
F260305 18:47:17.778700 16548 storage/pebble.go:1582  [n1,s1,pebble] 1 !created by github.com/cockroachdb/pebble/vfs.(*diskHealthCheckingFile).startTicker in goroutine 16548
F260305 18:47:17.778700 16548 storage/pebble.go:1582  [n1,s1,pebble] 1 !	external/com_github_cockroachdb_pebble/vfs/disk_health.go:249 +0x58
F260305 18:47:17.778700 16548 storage/pebble.go:1582  [n1,s1,pebble] 1 !
F260305 18:47:17.778700 16548 storage/pebble.go:1582  [n1,s1,pebble] 1 !goroutine 18977 [select]:
F260305 18:47:17.778700 16548 storage/pebble.go:1582  [n1,s1,pebble] 1 !github.com/cockroachdb/pebble/vfs.(*diskHealthCheckingFile).startTicker.func1()
F260305 18:47:17.778700 16548 storage/pebble.go:1582  [n1,s1,pebble] 1 !	external/com_github_cockroachdb_pebble/vfs/disk_health.go:254 +0xb3
F260305 18:47:17.778700 16548 storage/pebble.go:1582  [n1,s1,pebble] 1 !created by github.com/cockroachdb/pebble/vfs.(*diskHealthCheckingFile).startTicker in goroutine 18948
F260305 18:47:17.778700 16548 storage/pebble.go:1582  [n1,s1,pebble] 1 !	external/com_github_cockroachdb_pebble/vfs/disk_health.go:249 +0x58
F260305 18:47:17.778700 16548 storage/pebble.go:1582  [n1,s1,pebble] 1 !
F260305 18:47:17.778700 16548 storage/pebble.go:1582  [n1,s1,pebble] 1 !goroutine 17029 [select]:
F260305 18:47:17.778700 16548 storage/pebble.go:1582  [n1,s1,pebble] 1 !github.com/cockroachdb/pebble.(*ConcurrencyLimitScheduler).periodicGranter(0xc00f244420)
F260305 18:47:17.778700 16548 storage/pebble.go:1582  [n1,s1,pebble] 1 !	external/com_github_cockroachdb_pebble/compaction_scheduler.go:414 +0x9f
F260305 18:47:17.778700 16548 storage/pebble.go:1582  [n1,s1,pebble] 1 !created by github.com/cockroachdb/pebble.(*ConcurrencyLimitScheduler).Register in goroutine 16548
F260305 18:47:17.778700 16548 storage/pebble.go:1582  [n1,s1,pebble] 1 !	external/com_github_cockroachdb_pebble/compaction_scheduler.go:305 +0x96
F260305 18:47:17.778700 16548 storage/pebble.go:1582  [n1,s1,pebble] 1 !
F260305 18:47:17.778700 16548 storage/pebble.go:1582  [n1,s1,pebble] 1 !goroutine 19043 [select]:
F260305 18:47:17.778700 16548 storage/pebble.go:1582  [n1,s1,pebble] 1 !github.com/cockroachdb/cockroach/pkg/util/admission.makeStoreWorkQueue.func1()
F260305 18:47:17.778700 16548 storage/pebble.go:1582  [n1,s1,pebble] 1 !	pkg/util/admission/work_queue.go:2565 +0x85
F260305 18:47:17.778700 16548 storage/pebble.go:1582  [n1,s1,pebble] 1 !created by github.com/cockroachdb/cockroach/pkg/util/admission.makeStoreWorkQueue in goroutine 16548
F260305 18:47:17.778700 16548 storage/pebble.go:1582  [n1,s1,pebble] 1 !	pkg/util/admission/work_queue.go:2562 +0x48c
F260305 18:47:17.778700 16548 storage/pebble.go:1582  [n1,s1,pebble] 1 !
F260305 18:47:17.778700 16548 storage/pebble.go:1582  [n1,s1,pebble] 1 !goroutine 19040 [select]:
F260305 18:47:17.778700 16548 storage/pebble.go:1582  [n1,s1,pebble] 1 !github.com/cockroachdb/cockroach/pkg/util/admission.(*WorkQueue).startClosingEpochs.func1()
F260305 18:47:17.778700 16548 storage/pebble.go:1582  [n1,s1,pebble] 1 !	pkg/util/admission/work_queue.go:527 +0x145
F260305 18:47:17.778700 16548 storage/pebble.go:1582  [n1,s1,pebble] 1 !created by github.com/cockroachdb/cockroach/pkg/util/admission.(*WorkQueue).startClosingEpochs in goroutine 16548
F260305 18:47:17.778700 16548 storage/pebble.go:1582  [n1,s1,pebble] 1 !	pkg/util/admission/work_queue.go:498 +0x4f
F260305 18:47:17.778700 16548 storage/pebble.go:1582  [n1,s1,pebble] 1 !
F260305 18:47:17.778700 16548 storage/pebble.go:1582  [n1,s1,pebble] 1 !goroutine 16975 [chan receive]:
F260305 18:47:17.778700 16548 storage/pebble.go:1582  [n1,s1,pebble] 1 !github.com/cockroachdb/pebble/internal/genericcache.(*shard[...]).releaseLoop(0xc00288b798)
F260305 18:47:17.778700 16548 storage/pebble.go:1582  [n1,s1,pebble] 1 !	external/com_github_cockroachdb_pebble/internal/genericcache/shard.go:61 +0x6f
F260305 18:47:17.778700 16548 storage/pebble.go:1582  [n1,s1,pebble] 1 !created by github.com/cockroachdb/pebble/internal/genericcache.(*shard[...]).Init in goroutine 16548
F260305 18:47:17.778700 16548 storage/pebble.go:1582  [n1,s1,pebble] 1 !	external/com_github_cockroachdb_pebble/internal/genericcache/shard.go:54 +0x1a7
F260305 18:47:17.778700 16548 storage/pebble.go:1582  [n1,s1,pebble] 1 !
F260305 18:47:17.778700 16548 storage/pebble.go:1582  [n1,s1,pebble] 1 !goroutine 19898 [sync.Cond.Wait, "pebble":"wal-sync"]:
F260305 18:47:17.778700 16548 storage/pebble.go:1582  [n1,s1,pebble] 1 !sync.runtime_notifyListWait(0xc011e9a0a8, 0x73c)
F260305 18:47:17.778700 16548 storage/pebble.go:1582  [n1,s1,pebble] 1 !	GOROOT/src/runtime/sema.go:606 +0x159
F260305 18:47:17.778700 16548 storage/pebble.go:1582  [n1,s1,pebble] 1 !sync.(*Cond).Wait(0xc00c673790?)
F260305 18:47:17.778700 16548 storage/pebble.go:1582  [n1,s1,pebble] 1 !	GOROOT/src/sync/cond.go:71 +0x73
F260305 18:47:17.778700 16548 storage/pebble.go:1582  [n1,s1,pebble] 1 !github.com/cockroachdb/pebble/record.(*flusherCond).Wait(...)
F260305 18:47:17.778700 16548 storage/pebble.go:1582  [n1,s1,pebble] 1 !	external/com_github_cockroachdb_pebble/record/log_writer.go:371
F260305 18:47:17.778700 16548 storage/pebble.go:1582  [n1,s1,pebble] 1 !github.com/cockroachdb/pebble/record.(*LogWriter).flushLoop(0xc011e9a000, {0x56a4fc0?, 0xb032000?})
F260305 18:47:17.778700 16548 storage/pebble.go:1582  [n1,s1,pebble] 1 !	external/com_github_cockroachdb_pebble/record/log_writer.go:682 +0x785
F260305 18:47:17.778700 16548 storage/pebble.go:1582  [n1,s1,pebble] 1 !runtime/pprof.Do({0x6d8bbb0?, 0xb032000?}, {{0xc000ff8440?, 0x0?, 0xc00ab4efd0?}}, 0xc00ab4efc0)
F260305 18:47:17.778700 16548 storage/pebble.go:1582  [n1,s1,pebble] 1 !	GOROOT/src/runtime/pprof/runtime.go:51 +0x8c
F260305 18:47:17.778700 16548 storage/pebble.go:1582  [n1,s1,pebble] 1 !github.com/cockroachdb/pebble/record.NewLogWriter.func2()
F260305 18:47:17.778700 16548 storage/pebble.go:1582  [n1,s1,pebble] 1 !	external/com_github_cockroachdb_pebble/record/log_writer.go:596 +0x50
F260305 18:47:17.778700 16548 storage/pebble.go:1582  [n1,s1,pebble] 1 !created by github.com/cockroachdb/pebble/record.NewLogWriter in goroutine 19014
F260305 18:47:17.778700 16548 storage/pebble.go:1582  [n1,s1,pebble] 1 !	external/com_github_cockroachdb_pebble/record/log_writer.go:595 +0x55c
F260305 18:47:17.778700 16548 storage/pebble.go:1582  [n1,s1,pebble] 1 !
F260305 18:47:17.778700 16548 storage/pebble.go:1582  [n1,s1,pebble] 1 !goroutine 19897 [select]:
F260305 18:47:17.778700 16548 storage/pebble.go:1582  [n1,s1,pebble] 1 !github.com/cockroachdb/pebble/vfs.(*diskHealthCheckingFile).startTicker.func1()
F260305 18:47:17.778700 16548 storage/pebble.go:1582  [n1,s1,pebble] 1 !	external/com_github_cockroachdb_pebble/vfs/disk_health.go:254 +0xb3
F260305 18:47:17.778700 16548 storage/pebble.go:1582  [n1,s1,pebble] 1 !created by github.com/cockroachdb/pebble/vfs.(*diskHealthCheckingFile).startTicker in goroutine 19014
F260305 18:47:17.778700 16548 storage/pebble.go:1582  [n1,s1,pebble] 1 !	external/com_github_cockroachdb_pebble/vfs/disk_health.go:249 +0x58
F260305 18:47:17.778700 16548 storage/pebble.go:1582  [n1,s1,pebble] 1 !
F260305 18:47:17.778700 16548 storage/pebble.go:1582  [n1,s1,pebble] 1 !For more context, check log files in: /mnt/engflow/worker/work/1/exec/bazel-out/k8-fastbuild/testlogs/pkg/kv/kvserver/loqrecovery/loqrecovery_test/test.outputs/logTestFindUpdateRaft1624498671
F260305 18:47:17.778700 16548 storage/pebble.go:1582  [n1,s1,pebble] 1 !
F260305 18:47:17.778700 16548 storage/pebble.go:1582  [n1,s1,pebble] 1 !
F260305 18:47:17.778700 16548 storage/pebble.go:1582  [n1,s1,pebble] 1 !****************************************************************************
F260305 18:47:17.778700 16548 storage/pebble.go:1582  [n1,s1,pebble] 1 !
F260305 18:47:17.778700 16548 storage/pebble.go:1582  [n1,s1,pebble] 1 !This node experienced a fatal error (printed above), and as a result the
F260305 18:47:17.778700 16548 storage/pebble.go:1582  [n1,s1,pebble] 1 !process is terminating.
F260305 18:47:17.778700 16548 storage/pebble.go:1582  [n1,s1,pebble] 1 !
F260305 18:47:17.778700 16548 storage/pebble.go:1582  [n1,s1,pebble] 1 !Fatal errors can occur due to faulty hardware (disks, memory, clocks) or a
F260305 18:47:17.778700 16548 storage/pebble.go:1582  [n1,s1,pebble] 1 !problem in CockroachDB. With your help, the support team at Cockroach Labs
F260305 18:47:17.778700 16548 storage/pebble.go:1582  [n1,s1,pebble] 1 !will try to determine the root cause, recommend next steps, and we can
F260305 18:47:17.778700 16548 storage/pebble.go:1582  [n1,s1,pebble] 1 !improve CockroachDB based on your report.
F260305 18:47:17.778700 16548 storage/pebble.go:1582  [n1,s1,pebble] 1 !
F260305 18:47:17.778700 16548 storage/pebble.go:1582  [n1,s1,pebble] 1 !Please submit a crash report by following the instructions here:
F260305 18:47:17.778700 16548 storage/pebble.go:1582  [n1,s1,pebble] 1 !
F260305 18:47:17.778700 16548 storage/pebble.go:1582  [n1,s1,pebble] 1 !    https://github.com/cockroachdb/cockroach/issues/new/choose
F260305 18:47:17.778700 16548 storage/pebble.go:1582  [n1,s1,pebble] 1 !
F260305 18:47:17.778700 16548 storage/pebble.go:1582  [n1,s1,pebble] 1 !If you would rather not post publicly, please contact us directly at:
F260305 18:47:17.778700 16548 storage/pebble.go:1582  [n1,s1,pebble] 1 !
F260305 18:47:17.778700 16548 storage/pebble.go:1582  [n1,s1,pebble] 1 !    support@cockroachlabs.com
F260305 18:47:17.778700 16548 storage/pebble.go:1582  [n1,s1,pebble] 1 !
F260305 18:47:17.778700 16548 storage/pebble.go:1582  [n1,s1,pebble] 1 !The Cockroach Labs team appreciates your feedback.
```

Parameters:
 - <code>attempt=1</code>
 - <code>run=1</code>
 - <code>shard=1</code>
<details><summary>Help</summary>
<p>

See also: [How To Investigate a Go Test Failure \(internal\)](https://cockroachlabs.atlassian.net/l/c/HgfXfJgM)
</p>
</details>
/cc @cockroachdb/kv-triage
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*TestFindUpdateRaft.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/bazci/githubpost/issues)

</sub>

Jira issue: CRDB-61088

### PR DESCRIPTION
**Pull request by stevendanna**
This test could fail with an error such as

    error during engine close: leaked snapshots: 1 open snapshots on
    DB 0xc00310a608

This was hiding the real error:

    collect_raft_log_test.go:133: descriptor change sequence []
    doesn't contain {ReplicaChange r82:/{Table/Max-Max} [(n1,s1):1,
    next=3, gen=6, sticky=9223372036.854775807,2147483647] <nil>}

This appears to be the result of the raft log truncation queue truncating the log before the test could read the expected values.

Here, we fix this by disabling the raft truncation queue during the test. We also defer the pebble close immediately so that a test failure doesn't result in a leaked snapshot.

Fixes #164951
Release note: None

### CODE REVIEW

File: pkg/kv/kvserver/loqrecovery/collect_raft_log_test.go [hunk 1]
```diff
@@ -219,8 +221,8 @@ func checkRaftLog(
 		tc.Server(0).DB().Put(ctx, testutils.MakeKey(skey, []byte("second")), "some data"),
 		"failed to put test value")
 	reader := <-snapshots
-	assertRaftLog(t, ctx, reader)
 	defer reader.Close()
+	assertRaftLog(t, ctx, reader)
```
Comment (pav-kv) [inline pkg/kv/kvserver/loqrecovery/collect_raft_log_test.go:225]: > This was hiding the real error:

If there is a quick way to fix this too, could you do? (assuming you found a way to get through to this error)

Might be a missing `t.Helper()` or something.

**Review by pav-kv — APPROVED** [review]

File: pkg/kv/kvserver/loqrecovery/collect_raft_log_test.go (hunk 1 above)
Comment (stevendanna) [reply pkg/kv/kvserver/loqrecovery/collect_raft_log_test.go:225]: This diff is fixing it. "Hiding" was a bit strong. The error was printed, you just needed to know to ignore the big fatal log entry that our bug reporting puts into the ticket.
