### PR TITLE
server: fix NPE from HotRangesV2 API

### LINKED ISSUE #142908: dbconsole: hot ranges page causes panic on nodes in drt-scale-300.
When testing on our 300 node cluster (`drt-scale-300`) with an average CPU consumption of **22%** and QPS around **200K**, opening the Hot Ranges page triggered a critical failure. Specifically, 72 nodes and more experienced a panic with the error.

The stack trace:
```
E250314 16:23:51.445228 42894019 1@util/log/logcrash/crash_reporting.go:192 ⋮ [-] 159790 +runtime error: invalid memory address or nil pointer dereference
E250314 16:23:51.445228 42894019 1@util/log/logcrash/crash_reporting.go:192 ⋮ [-] 159790 +(1) attached stack trace
E250314 16:23:51.445228 42894019 1@util/log/logcrash/crash_reporting.go:192 ⋮ [-] 159790 +  -- stack trace:
E250314 16:23:51.445228 42894019 1@util/log/logcrash/crash_reporting.go:192 ⋮ [-] 159790 +  | runtime.gopanic
E250314 16:23:51.445228 42894019 1@util/log/logcrash/crash_reporting.go:192 ⋮ [-] 159790 +  | 	GOROOT/src/runtime/panic.go:791
E250314 16:23:51.445228 42894019 1@util/log/logcrash/crash_reporting.go:192 ⋮ [-] 159790 +  | runtime.panicmem
E250314 16:23:51.445228 42894019 1@util/log/logcrash/crash_reporting.go:192 ⋮ [-] 159790 +  | 	GOROOT/src/runtime/panic.go:262
E250314 16:23:51.445228 42894019 1@util/log/logcrash/crash_reporting.go:192 ⋮ [-] 159790 +  | runtime.sigpanic
E250314 16:23:51.445228 42894019 1@util/log/logcrash/crash_reporting.go:192 ⋮ [-] 159790 +  | 	GOROOT/src/runtime/signal_unix.go:917
E250314 16:23:51.445228 42894019 1@util/log/logcrash/crash_reporting.go:192 ⋮ [-] 159790 +  | github.com/cockroachdb/cockroach/pkg/server.(*systemStatusServer).HotRangesV2
E250314 16:23:51.445228 42894019 1@util/log/logcrash/crash_reporting.go:192 ⋮ [-] 159790 +  | 	pkg/server/status.go:2884
E250314 16:23:51.445228 42894019 1@util/log/logcrash/crash_reporting.go:192 ⋮ [-] 159790 +  | github.com/cockroachdb/cockroach/pkg/server/serverpb._Status_HotRangesV2_Handler.func1
E250314 16:23:51.445228 42894019 1@util/log/logcrash/crash_reporting.go:192 ⋮ [-] 159790 +  | 	bazel-out/k8-opt/bin/pkg/server/serverpb/serverpb_go_proto_/github.com/cockroachdb/cockroach/pkg/server/serverpb/status.pb.go:9897
E250314 16:23:51.445228 42894019 1@util/log/logcrash/crash_reporting.go:192 ⋮ [-] 159790 +  | github.com/cockroachdb/cockroach/pkg/rpc.NewServerEx.ServerInterceptor.func12
E250314 16:23:51.445228 42894019 1@util/log/logcrash/crash_reporting.go:192 ⋮ [-] 159790 +  | 	pkg/util/tracing/grpcinterceptor/grpc_interceptor.go:104
E250314 16:23:51.445228 42894019 1@util/log/logcrash/crash_reporting.go:192 ⋮ [-] 159790 +  | google.golang.org/grpc.getChainUnaryHandler.func1
E250314 16:23:51.445228 42894019 1@util/log/logcrash/crash_reporting.go:192 ⋮ [-] 159790 +  | 	external/org_golang_google_grpc/server.go:1177
E250314 16:23:51.445228 42894019 1@util/log/logcrash/crash_reporting.go:192 ⋮ [-] 159790 +  | github.com/cockroachdb/cockroach/pkg/rpc.NewServerEx.func3
E250314 16:23:51.445228 42894019 1@util/log/logcrash/crash_reporting.go:192 ⋮ [-] 159790 +  | 	pkg/rpc/context.go:166
E250314 16:23:51.445228 42894019 1@util/log/logcrash/crash_reporting.go:192 ⋮ [-] 159790 +  | google.golang.org/grpc.getChainUnaryHandler.func1
E250314 16:23:51.445228 42894019 1@util/log/logcrash/crash_reporting.go:192 ⋮ [-] 159790 +  | 	external/org_golang_google_grpc/server.go:1177
E250314 16:23:51.445228 42894019 1@util/log/logcrash/crash_reporting.go:192 ⋮ [-] 159790 +  | github.com/cockroachdb/cockroach/pkg/rpc.kvAuth.unaryInterceptor
E250314 16:23:51.445228 42894019 1@util/log/logcrash/crash_reporting.go:192 ⋮ [-] 159790 +  | 	pkg/rpc/auth.go:90
E250314 16:23:51.445228 42894019 1@util/log/logcrash/crash_reporting.go:192 ⋮ [-] 159790 +  | google.golang.org/grpc.getChainUnaryHandler.func1
E250314 16:23:51.445228 42894019 1@util/log/logcrash/crash_reporting.go:192 ⋮ [-] 159790 +  | 	external/org_golang_google_grpc/server.go:1177
E250314 16:23:51.445228 42894019 1@util/log/logcrash/crash_reporting.go:192 ⋮ [-] 159790 +  | github.com/cockroachdb/cockroach/pkg/rpc.NewServerEx.func1.1
E250314 16:23:51.445228 42894019 1@util/log/logcrash/crash_reporting.go:192 ⋮ [-] 159790 +  | 	pkg/rpc/context.go:133
E250314 16:23:51.445228 42894019 1@util/log/logcrash/crash_reporting.go:192 ⋮ [-] 159790 +  | github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunTaskWithErr
E250314 16:23:51.445228 42894019 1@util/log/logcrash/crash_reporting.go:192 ⋮ [-] 159790 +  | 	pkg/util/stop/stopper.go:350
E250314 16:23:51.445228 42894019 1@util/log/logcrash/crash_reporting.go:192 ⋮ [-] 159790 +  | github.com/cockroachdb/cockroach/pkg/rpc.NewServerEx.func1
E250314 16:23:51.445228 42894019 1@util/log/logcrash/crash_reporting.go:192 ⋮ [-] 159790 +  | 	pkg/rpc/context.go:131
E250314 16:23:51.445228 42894019 1@util/log/logcrash/crash_reporting.go:192 ⋮ [-] 159790 +  | google.golang.org/grpc.NewServer.chainUnaryServerInterceptors.chainUnaryInterceptors.func1
E250314 16:23:51.445228 42894019 1@util/log/logcrash/crash_reporting.go:192 ⋮ [-] 159790 +  | 	external/org_golang_google_grpc/server.go:1168
E250314 16:23:51.445228 42894019 1@util/log/logcrash/crash_reporting.go:192 ⋮ [-] 159790 +  | github.com/cockroachdb/cockroach/pkg/server/serverpb._Status_HotRangesV2_Handler
E250314 16:23:51.445228 42894019 1@util/log/logcrash/crash_reporting.go:192 ⋮ [-] 159790 +  | 	bazel-out/k8-opt/bin/pkg/server/serverpb/serverpb_go_proto_/github.com/cockroachdb/cockroach/pkg/server/serverpb/status.pb.go:9899
E250314 16:23:51.445228 42894019 1@util/log/logcrash/crash_reporting.go:192 ⋮ [-] 159790 +  | google.golang.org/grpc.(*Server).processUnaryRPC
E250314 16:23:51.445228 42894019 1@util/log/logcrash/crash_reporting.go:192 ⋮ [-] 159790 +  | 	external/org_golang_google_grpc/server.go:1358
E250314 16:23:51.445228 42894019 1@util/log/logcrash/crash_reporting.go:192 ⋮ [-] 159790 +  | google.golang.org/grpc.(*Server).handleStream
E250314 16:23:51.445228 42894019 1@util/log/logcrash/crash_reporting.go:192 ⋮ [-] 159790 +  | 	external/org_golang_google_grpc/server.go:1735
E250314 16:23:51.445228 42894019 1@util/log/logcrash/crash_reporting.go:192 ⋮ [-] 159790 +  | google.golang.org/grpc.(*Server).serveStreams.func1.1
E250314 16:23:51.445228 42894019 1@util/log/logcrash/crash_reporting.go:192 ⋮ [-] 159790 +  | 	external/org_golang_google_grpc/server.go:970
E250314 16:23:51.445228 42894019 1@util/log/logcrash/crash_reporting.go:192 ⋮ [-] 159790 +  | runtime.goexit
E250314 16:23:51.445228 42894019 1@util/log/logcrash/crash_reporting.go:192 ⋮ [-] 159790 +  | 	src/runtime/asm_amd64.s:1700
E250314 16:23:51.445228 42894019 1@util/log/logcrash/crash_reporting.go:192 ⋮ [-] 159790 +Wraps: (2) runtime error: invalid memory address or nil pointer dereference
E250314 16:23:51.445228 42894019 1@util/log/logcrash/crash_reporting.go:192 ⋮ [-] 159790 +Error types: (1) *withstack.withStack (2) runtime.errorString
E250314 16:23:51.446373 42894019 util/log/logcrash/crash_reporting.go:394 ⋮ [-] 159791  Queued as error ‹ad26970120134140bb7b22d68be15b20›
E250314 16:23:51.451421 1439 2@rpc/peer.go:658 ⋮ [T1,Vsystem,n28,rnode=24,raddr=‹10.128.0.52:26257›,class=default,rpc] 159792  disconnected (was healthy for 36m12.128s): operation "conn heartbeat" timed out after 6s (given timeout 6s): grpc: ‹context deadline exceeded› [code 4/DeadlineExceeded]
```

More details in [slack thread](https://cockroachlabs.slack.com/archives/C05FHJJ0MD0/p1741970434599079).

Attached is the cockroach.log file.

[cockroach.log](https://github.com/user-attachments/files/19251492/cockroach.log)

Jira issue: CRDB-48581

### PR DESCRIPTION
**Pull request by kyle-a-wong**
Fixes a bug where HotRangesV2 is throwing an NPE when localHotRanges returns an error.

Fixes: #142908
Epic: none
Release note: none

### CODE REVIEW

File: pkg/server/status.go [hunk 1]
```diff
@@ -2881,9 +2881,10 @@ func (s *systemStatusServer) HotRangesV2(
 		}
 		if local {
 			resp, err := s.localHotRanges(ctx, tenantID, requestedNodeID)
-			response.Ranges = append(response.Ranges, resp.Ranges...)
 			if err != nil {
 				response.ErrorsByNodeID[requestedNodeID] = err.Error()
```
Comment (angles-n-daemons) [inline pkg/server/status.go:2885]: Could we instead return after this? Seems no point to continuing, since we return in the success condition.

```
return response, err
```

Comment (kyle-a-wong) [reply pkg/server/status.go]: Changed to just return the err and not a response object in the case that an error is returned. The node iterator will handle mapping the errors and responses to the final response object.

**Review by angles-n-daemons — APPROVED** [review]

**Comment by kyle-a-wong** [comment]
tftr

bors r+
