### PR TITLE
sql: disallow type cast from ENUM to BYTES

### LINKED ISSUE #74316: sql: casts from ENUMs to BYTES cause internal error
For example:

```
defaultdb> create type foo as enum ('foo', 'bar');
CREATE TYPE

defaultdb> select 'foo'::text::foo;
  foo
-------
  foo
(1 row)

defaultdb> select 'foo'::foo::bytes;
ERROR: invalid cast: foo -> bytes
SQLSTATE: 42846

defaultdb> select 'foo'::bytes::foo;
ERROR: could not find [102 111 111] in enum "public.foo" representation PhysicalReps: [[64] [128]]; LogicalReps: [foo bar] goroutine 2209 [running]:
runtime/debug.Stack(0x8dd859a, 0x21, 0xc002746e78)
        /usr/local/go/src/runtime/debug/stack.go:24 +0x9f
github.com/cockroachdb/cockroach/pkg/sql/types.(*T).EnumGetIdxOfPhysical(0xc00330c540, 0xc0011b1768, 0x3, 0x8, 0x0, 0x1, 0xc000d80000)
        /go/src/github.com/cockroachdb/cockroach/pkg/sql/types/types.go:2419 +0x27e
github.com/cockroachdb/cockroach/pkg/sql/sem/tree.GetEnumComponentsFromPhysicalRep(0xc00330c540, 0xc0011b1768, 0x3, 0x8, 0xc0011b1768, 0x8, 0xc0011b1768, 0xc002746fe8, 0x4057ce5, 0xc0011b1768, ...)
        /go/src/github.com/cockroachdb/cockroach/pkg/sql/sem/tree/datum.go:4130 +0x4d
github.com/cockroachdb/cockroach/pkg/sql/sem/tree.MakeDEnumFromPhysicalRepresentation(0xc00330c540, 0xc0011b1768, 0x3, 0x8, 0x3, 0x8, 0x85f4b80)
        /go/src/github.com/cockroachdb/cockroach/pkg/sql/sem/tree/datum.go:4147 +0x76
github.com/cockroachdb/cockroach/pkg/sql/sem/tree.performCastWithoutPrecisionTruncation(0xc000938a80, 0xc85ad48, 0xc001044f70, 0xc00330c540, 0x87935c0, 0x8bc2920, 0x0, 0xc765bb0)
        /go/src/github.com/cockroachdb/cockroach/pkg/sql/sem/tree/casts.go:854 +0x7a89
github.com/cockroachdb/cockroach/pkg/sql/sem/tree.PerformCast(0xc000938a80, 0xc85ad48, 0xc001044f70, 0xc00330c540, 0xc001044f70, 0x0, 0x10, 0x8a469a0)
        /go/src/github.com/cockroachdb/cockroach/pkg/sql/sem/tree/casts.go:501 +0x4d
github.com/cockroachdb/cockroach/pkg/sql/sem/tree.(*CastExpr).Eval(0xc001e84600, 0xc000938a80, 0x1, 0xc001045140, 0xc001e84660, 0x1)
        /go/src/github.com/cockroachdb/cockroach/pkg/sql/sem/tree/eval.go:4016 +0x106
github.com/cockroachdb/cockroach/pkg/sql.(*valuesNode).startExec(0xc0014e8af0, 0xc7377b0, 0xc00218dfb0, 0xc000938a80, 0xc0012198d8, 0x0, 0x0)
        /go/src/github.com/cockroachdb/cockroach/pkg/sql/values.go:156 +0x1fc
github.com/cockroachdb/cockroach/pkg/sql.startExec.func2(0x8d60a64, 0x6, 0xc71e1e8, 0xc0014e8af0, 0x0, 0x0)
        /go/src/github.com/cockroachdb/cockroach/pkg/sql/plan.go:509 +0xcb
github.com/cockroachdb/cockroach/pkg/sql.(*planVisitor).visitInternal.func1(0xc002747af8, 0x8d60a64, 0x6, 0xc71e1e8, 0xc0014e8af0)
        /go/src/github.com/cockroachdb/cockroach/pkg/sql/walk.go:112 +0x5d
github.com/cockroachdb/cockroach/pkg/sql.(*planVisitor).visitInternal(0xc002747af8, 0xc71e1e8, 0xc0014e8af0, 0x8d60a64, 0x6)
        /go/src/github.com/cockroachdb/cockroach/pkg/sql/walk.go:289 +0x192
github.com/cockroachdb/cockroach/pkg/sql.(*planVisitor).visit(0xc002747af8, 0xc71e1e8, 0xc0014e8af0, 0xc002747bc8, 0x0)
        /go/src/github.com/cockroachdb/cockroach/pkg/sql/walk.go:79 +0x8f
github.com/cockroachdb/cockroach/pkg/sql.walkPlan(...)
        /go/src/github.com/cockroachdb/cockroach/pkg/sql/walk.go:43
github.com/cockroachdb/cockroach/pkg/sql.startExec(0xc7377b0, 0xc00218dfb0, 0xc000938a80, 0xc0012198d8, 0xc71e1e8, 0xc0014e8af0, 0xc7377b0, 0xc00218dfb0)
        /go/src/github.com/cockroachdb/cockroach/pkg/sql/plan.go:512 +0x11a
github.com/cockroachdb/cockroach/pkg/sql.(*planNodeToRowSource).Start(0xc0001bcc00, 0xc7377b0, 0xc00218dfb0)
        /go/src/github.com/cockroachdb/cockroach/pkg/sql/plan_node_to_row_source.go:142 +0xc5
github.com/cockroachdb/cockroach/pkg/sql/colexec.(*Columnarizer).Init(0xc0002f0c00, 0xc7377b0, 0xc00218dfb0)
        /go/src/github.com/cockroachdb/cockroach/pkg/sql/colexec/columnarizer.go:151 +0xf6
github.com/cockroachdb/cockroach/pkg/sql/colflow.(*batchInfoCollector).Init(0xc000e896c0, 0xc7377b0, 0xc00218dfb0)
        /go/src/github.com/cockroachdb/cockroach/pkg/sql/colflow/stats.go:86 +0x4b
github.com/cockroachdb/cockroach/pkg/sql/colflow.(*BatchFlowCoordinator).init.func1()
        /go/src/github.com/cockroachdb/cockroach/pkg/sql/colflow/flow_coordinator.go:234 +0x45
github.com/cockroachdb/cockroach/pkg/sql/colexecerror.CatchVectorizedRuntimeError(0xc002747cb8, 0x0, 0x0)
        /go/src/github.com/cockroachdb/cockroach/pkg/sql/colexecerror/error.go:91 +0x57
github.com/cockroachdb/cockroach/pkg/sql/colflow.(*BatchFlowCoordinator).init(0xc001249970, 0xc7377b0, 0xc00218dfb0, 0x16, 0xc7377b0)
        /go/src/github.com/cockroachdb/cockroach/pkg/sql/colflow/flow_coordinator.go:233 +0x65
github.com/cockroachdb/cockroach/pkg/sql/colflow.(*BatchFlowCoordinator).Run(0xc001249970, 0xc71bb68, 0xc0015bd280)
        /go/src/github.com/cockroachdb/cockroach/pkg/sql/colflow/flow_coordinator.go:274 +0x13a
github.com/cockroachdb/cockroach/pkg/sql/colflow.(*vectorizedFlow).Run(0xc00185def0, 0xc71bb68, 0xc0015bd280, 0xb70a848)
        /go/src/github.com/cockroachdb/cockroach/pkg/sql/colflow/vectorized_flow.go:258 +0x234
github.com/cockroachdb/cockroach/pkg/sql.(*DistSQLPlanner).Run(0xc001e9e000, 0xc000f77d10, 0xc001249810, 0xc002843080, 0xc001e8bc00, 0xc001219b28, 0x0, 0x0)
        /go/src/github.com/cockroachdb/cockroach/pkg/sql/distsql_running.go:535 +0x64f
github.com/cockroachdb/cockroach/pkg/sql.(*DistSQLPlanner).PlanAndRun(0xc001e9e000, 0xc7377b0, 0xc00218da10, 0xc001219b28, 0xc000f77d10, 0xc001249810, 0xc71e1e8, 0xc0014e8af0, 0x0, 0xc001e8bc00, ...)
        /go/src/github.com/cockroachdb/cockroach/pkg/sql/distsql_running.go:1276 +0x1b1
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execWithDistSQLEngine(0xc001219300, 0xc7377b0, 0xc00218da10, 0xc0012198d8, 0x3, 0x37dd2db8, 0xc001430fa0, 0xc002748800, 0xc00286d018, 0x0, ...)
        /go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:1380 +0x472
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).dispatchToExecutionEngine(0xc001219300, 0xc7377b0, 0xc00218da10, 0xc0012198d8, 0x37dd2db8, 0xc001430fa0, 0x0, 0x0)
        /go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:1071 +0x90b
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execStmtInOpenState(0xc001219300, 0xc7377b0, 0xc00218da10, 0xc7444d8, 0xc0014e89b0, 0xc0013c430f, 0x18, 0x0, 0x1, 0x0, ...)
        /go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:709 +0x11a6
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execStmt(0xc001219300, 0xc71bb68, 0xc0015bcfc0, 0xc7444d8, 0xc0014e89b0, 0xc0013c430f, 0x18, 0x0, 0x1, 0x0, ...)
        /go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:129 +0xb0a
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execCmd.func1(0xc7444d8, 0xc0014e89b0, 0xc0013c430f, 0x18, 0x0, 0x1, 0x12d238d8, 0xed95ead27, 0x0, 0x12d23cc0, ...)
        /go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:1707 +0x293
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execCmd(0xc001219300, 0xc71bb68, 0xc0015bcfc0, 0x0, 0x0)
        /go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:1709 +0x1711
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).run(0xc001219300, 0xc71bb68, 0xc000e19d00, 0xc001d70000, 0x5400, 0x15000, 0xc001d70280, 0xc00048dad0, 0x0, 0x0)
        /go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:1631 +0x22f
github.com/cockroachdb/cockroach/pkg/sql.(*Server).ServeConn(0xc0007ba700, 0xc71bb68, 0xc000e19d00, 0xc001219300, 0x5400, 0x15000, 0xc001d70280, 0xc00048dad0, 0x0, 0x0)
        /go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:670 +0xce
github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*conn).processCommandsAsync.func1(0xc001d09c84, 0xc00071b968, 0xc71bb68, 0xc000e19d00, 0xc00048dad0, 0xc0007ba700, 0xc001430900, 0xc780bb8, 0xc001d65a00, 0xc002865ce0, ...)
        /go/src/github.com/cockroachdb/cockroach/pkg/sql/pgwire/conn.go:648 +0x3f1
created by github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*conn).processCommandsAsync
        /go/src/github.com/cockroachdb/cockroach/pkg/sql/pgwire/conn.go:576 +0x191
```

```
defaultdb> select version();
                                        version
----------------------------------------------------------------------------------------
  CockroachDB CCL v21.2.3 (x86_64-apple-darwin19, built 2021/12/14 15:26:20, go1.16.6)
(1 row)
```

Epic CRDB-8948

### PR DESCRIPTION
**Pull request by ZhouXing19**
Fixes https://github.com/cockroachdb/cockroach/issues/74316

Release note (sql): Disallow type cast from ENUM to BYTES

### CODE REVIEW

File: pkg/sql/sem/tree/type_check.go [hunk 1]
```diff
@@ -450,6 +450,10 @@ func resolveCast(
 		telemetry.Inc(GetCastCounter(fromFamily, toFamily))
 		return nil
 
+	case toFamily == types.BytesFamily && fromFamily == types.EnumFamily:
```
Comment (otan) [inline pkg/sql/sem/tree/type_check.go:453]: i think we want to delete https://github.com/cockroachdb/cockroach/blob/d09d14178a72f7625d0869902b7087a3f1ee3415/pkg/sql/sem/tree/cast.go#L1350-L1360 instead

Comment (ZhouXing19) [reply pkg/sql/sem/tree/type_check.go]: Done. Thanks!

**Review by otan — APPROVED** [review]

**Comment by ZhouXing19** [comment]
TFTR!
bors=otan

**Review by mgartner — COMMENTED** [review]
Very nice, thanks!
