### PR TITLE
cli: remove mention of http-lb in --join flag.

### LINKED ISSUE #21819: http-lb type not honored
**BUG REPORT**

```
$ sudo cockroach start --insecure --join http-lb=db.example.com --cache 25%   --max-sql-memory 25% --logtostderr --verbosity 1
W180126 15:35:05.347356 1 cli/start.go:777  RUNNING IN INSECURE MODE!

- Your cluster is open for any client that can access <all your IP addresses>.
- Any user, even root, can log in without providing a password.
- Any user, connecting as root, can read or write any data in your cluster.
- There is no network encryption nor authentication, and thus no confidentiality.

Check out how to secure your cluster: https://www.cockroachlabs.com/docs/stable/secure-a-cluster.html
I180126 15:35:05.347599 1 cli/start.go:785  CockroachDB CCL v1.1.4 (linux amd64, built 2018/01/08 17:32:42, go1.8.3)
I180126 15:35:05.448047 1 server/config.go:323  available memory from cgroups (8.0 EiB) exceeds system memory 3.9 GiB, using system memory
I180126 15:35:05.448084 1 server/config.go:436  system total memory: 3.9 GiB
I180126 15:35:05.448149 1 server/config.go:438  server configuration:
max offset                500000000
cache size                988 MiB
SQL memory pool size      988 MiB
scan interval             10m0s
scan max idle time        200ms
metrics sample interval   10s
event log enabled         true
linearizable              false
I180126 15:35:05.448270 22 cli/start.go:503  starting cockroach node
I180126 15:35:05.449271 22 storage/engine/rocksdb.go:411  opening rocksdb instance at "/home/ubuntu/cockroach-data/local"
I180126 15:35:05.467110 22 server/config.go:593  [n?] initial resolvers: [http-lb=db.example.com:26257]
W180126 15:35:05.467141 22 gossip/gossip.go:1241  [n?] no incoming or outgoing connections
W180126 15:35:05.467380 40 gossip/gossip.go:1044  [n?] invalid bootstrap address: &{typ:tcp addr:http-lb=db.example.com:26257}, lookup http-lb=db.example.com: no such host
```

2. Please describe the issue you observed:

- What did you do? Starting cluster on aws behind a ELB

- What did you expect to see? the `--join http-lb=elb-public-dns-name` should try to query the http(s) interface to enumerate the existing nodes

- What did you see instead? the *type is interpolated as a plain tcp address* and the `http-lb` dosen't have the documented effect

Extract from the help:
```
Each address in the list has an optional type: [type=]<address>. An
        unspecified type means ip address or dns. Type is one of:

          - tcp: (default if type is omitted): plain ip address or hostname.
          - http-lb: HTTP load balancer: we query
                     http(s)://<address>/_status/details/local
```

### PR DESCRIPTION
**Pull request by mberhault**
The functionality was removed in #5956 in April 2016.

Fixes #21819

Release note: None

### CODE REVIEW

**Comment by mberhault** [comment]
@mrtracy since this came through an issue during your support rotation week :)

**Comment by mberhault** [comment]
@jseldess: the help text for `--join` feels a bit odd. Do you have any suggestions to improve it while I'm poking around here?

**Review by a-robinson — APPROVED** [review]

File: pkg/cli/cliflags/flags.go [hunk 1]
```diff
@@ -272,7 +272,7 @@ sessions.`,
 		Name:      "join",
 		Shorthand: "j",
 		Description: `
-The address of node which acts as bootstrap when a new node is
+The address of a node which acts as bootstrap when a new node is
```
Comment (jseldess) [inline pkg/cli/cliflags/flags.go]: What about something similar to what we have in the docs now:

>The addresses for connecting a node to a cluster.
>
>When starting a multi-node cluster for the first time, set this flag to the addresses of 3-5 of the initial nodes. Then run the cockroach init command against any of the nodes to complete cluster startup.
>
>When starting a singe-node cluster, leave this flag out. This will cause the node to initialize a new single-node cluster without needing to run the cockroach init command. 
>
>When adding a node to an existing cluster, set this flag to 3-5 of the nodes already in the cluster; it's easiest to use the same list of addresses that was used to start the initial nodes.

Followed by the `This flag can be specified separately for each address...` bit.

Thoughts?
