### PR TITLE
opt: Fix panic when hoisting expr with correlated subquery

### LINKED ISSUE #32270: opt: panic in optbuilder
```
panic: interface conversion: *memo.ProjectExpr is not opt.ScalarExpr: missing method DataType [recovered]
        panic: interface conversion: *memo.ProjectExpr is not opt.ScalarExpr: missing method DataType [recovered]
        panic: panic while executing 1 statements: SELECT _._ AS _, _._ AS _, _._ AS _, _._ AS _, CASE WHEN array_remove(CAST(CASE WHEN (SELECT _ FROM _._ LIMIT _ OFFSET _) < (SELECT _ FROM _._ LIMIT _ OFFSET _) THEN CASE WHEN (SELECT json_agg(_) FROM _._) @> (SELECT json_agg(_) FROM _._) THEN CAST(_ AS UUID[]) ELSE CAST(_ AS UUID[]) END ELSE CASE WHEN (SELECT json_agg(_) FROM _._) @> (SELECT json_agg(_) FROM _._) THEN CAST(_ AS UUID[]) ELSE CAST(_ AS UUID[]) END END AS UUID[]), CAST(CAST(_ AS UUID) AS UUID)) IS DISTINCT FROM CAST(COALESCE(CASE  [...]; caused by interface conversion: *memo.ProjectExpr is not opt.ScalarExpr: missing method DataType

goroutine 560 [running]:
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).closeWrapper(0xc008159300, 0x6e46a00, 0xc006436c80, 0x63ce9c0, 0xc008778150)
        /Users/jordan/repo/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:647 +0x36f
github.com/cockroachdb/cockroach/pkg/sql.(*Server).ServeConn.func1(0xc008159300, 0x6e46a00, 0xc006436c80)
        /Users/jordan/repo/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:388 +0x61
panic(0x63ce9c0, 0xc008778150)
        /usr/local/Cellar/go/1.11/libexec/src/runtime/panic.go:513 +0x1b9
github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder.(*Builder).Build.func1(0xc009b0eae8)
        /Users/jordan/repo/src/github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder/builder.go:137 +0x9a
panic(0x63ce9c0, 0xc008778150)
        /usr/local/Cellar/go/1.11/libexec/src/runtime/panic.go:513 +0x1b9
github.com/cockroachdb/cockroach/pkg/sql/opt/norm.(*subqueryHoister).hoistAll.func1(0x6e52ec0, 0xc0071228f8, 0xc0071228f8, 0x6e52ec0)
        /Users/jordan/repo/src/github.com/cockroachdb/cockroach/pkg/sql/opt/norm/decorrelate.go:791 +0x4e
github.com/cockroachdb/cockroach/pkg/sql/opt/norm.(*Factory).Reconstruct(0xc00815a278, 0x6e533c0, 0xc0066cf230, 0xc000457940, 0xc0066cf230, 0x4014a26)
        /Users/jordan/repo/src/github.com/cockroachdb/cockroach/pkg/sql/opt/norm/factory.og.go:12659 +0xef7f
github.com/cockroachdb/cockroach/pkg/sql/opt/norm.(*subqueryHoister).hoistAll(0xc008778120, 0x6e5e0e0, 0xc0066cf230, 0x6e5e0e0, 0xc0066cf230)
        /Users/jordan/repo/src/github.com/cockroachdb/cockroach/pkg/sql/opt/norm/decorrelate.go:789 +0x18d
github.com/cockroachdb/cockroach/pkg/sql/opt/norm.(*subqueryHoister).hoistAll.func1(0x6e533c0, 0xc0066cf230, 0xc0066cf230, 0x6e533c0)
        /Users/jordan/repo/src/github.com/cockroachdb/cockroach/pkg/sql/opt/norm/decorrelate.go:791 +0x70
github.com/cockroachdb/cockroach/pkg/sql/opt/norm.(*Factory).Reconstruct(0xc00815a278, 0x6e52940, 0xc006c82be0, 0xc000457930, 0xc006c82be0, 0x0)
        /Users/jordan/repo/src/github.com/cockroachdb/cockroach/pkg/sql/opt/norm/factory.og.go:12755 +0x68ba
github.com/cockroachdb/cockroach/pkg/sql/opt/norm.(*subqueryHoister).hoistAll(0xc008778120, 0x6e5d6c0, 0xc006c82be0, 0x6e5d6c0, 0xc006c82be0)
        /Users/jordan/repo/src/github.com/cockroachdb/cockroach/pkg/sql/opt/norm/decorrelate.go:789 +0x18d
github.com/cockroachdb/cockroach/pkg/sql/opt/norm.(*subqueryHoister).hoistAll.func1(0x6e52940, 0xc006c82be0, 0xc006c82be0, 0x6e52940)
        /Users/jordan/repo/src/github.com/cockroachdb/cockroach/pkg/sql/opt/norm/decorrelate.go:791 +0x70
github.com/cockroachdb/cockroach/pkg/sql/opt/norm.(*Factory).Reconstruct(0xc00815a278, 0x6e53740, 0xc0066cf380, 0xc000457920, 0xc0066cf380, 0x6482cc0)
        /Users/jordan/repo/src/github.com/cockroachdb/cockroach/pkg/sql/opt/norm/factory.og.go:13113 +0x8729
github.com/cockroachdb/cockroach/pkg/sql/opt/norm.(*subqueryHoister).hoistAll(0xc008778120, 0x6e5e4a0, 0xc0066cf380, 0x6e5e4a0, 0xc0066cf380)
        /Users/jordan/repo/src/github.com/cockroachdb/cockroach/pkg/sql/opt/norm/decorrelate.go:789 +0x18d
github.com/cockroachdb/cockroach/pkg/sql/opt/norm.(*subqueryHoister).hoistAll.func1(0x6e53740, 0xc0066cf380, 0xc0066cf380, 0x6e53740)
        /Users/jordan/repo/src/github.com/cockroachdb/cockroach/pkg/sql/opt/norm/decorrelate.go:791 +0x70
github.com/cockroachdb/cockroach/pkg/sql/opt/norm.(*Factory).reconstructScalarListExpr(0xc00815a278, 0xc006c82bc0, 0x1, 0x2, 0xc000457900, 0x0, 0x6e5fca0, 0xc008547b30, 0x0)
        /Users/jordan/repo/src/github.com/cockroachdb/cockroach/pkg/sql/opt/norm/factory.og.go:13388 +0xc6
github.com/cockroachdb/cockroach/pkg/sql/opt/norm.(*Factory).Reconstruct(0xc00815a278, 0x6e51b40, 0xc007b0b900, 0xc000457900, 0xc007b0b900, 0x0)
        /Users/jordan/repo/src/github.com/cockroachdb/cockroach/pkg/sql/opt/norm/factory.og.go:13105 +0x5275
github.com/cockroachdb/cockroach/pkg/sql/opt/norm.(*subqueryHoister).hoistAll(0xc008778120, 0x6e5c7c0, 0xc007b0b900, 0x6e5c7c0, 0xc007b0b900)
        /Users/jordan/repo/src/github.com/cockroachdb/cockroach/pkg/sql/opt/norm/decorrelate.go:789 +0x18d
github.com/cockroachdb/cockroach/pkg/sql/opt/norm.(*subqueryHoister).hoistAll.func1(0x6e51b40, 0xc007b0b900, 0xc007b0b900, 0x6e51b40)
        /Users/jordan/repo/src/github.com/cockroachdb/cockroach/pkg/sql/opt/norm/decorrelate.go:791 +0x70
github.com/cockroachdb/cockroach/pkg/sql/opt/norm.(*Factory).reconstructScalarListExpr(0xc00815a278, 0xc006c82ba0, 0x2, 0x2, 0xc0004578f0, 0x0, 0x0, 0x0, 0x0)
        /Users/jordan/repo/src/github.com/cockroachdb/cockroach/pkg/sql/opt/norm/factory.og.go:13388 +0xc6
github.com/cockroachdb/cockroach/pkg/sql/opt/norm.(*Factory).Reconstruct(0xc00815a278, 0x6e522c0, 0xc007b0b950, 0xc0004578f0, 0xc007b0b950, 0x0)
        /Users/jordan/repo/src/github.com/cockroachdb/cockroach/pkg/sql/opt/norm/factory.og.go:13136 +0x98c2
github.com/cockroachdb/cockroach/pkg/sql/opt/norm.(*subqueryHoister).hoistAll(0xc008778120, 0x6e5d0c0, 0xc007b0b950, 0x6e5d0c0, 0xc007b0b950)
        /Users/jordan/repo/src/github.com/cockroachdb/cockroach/pkg/sql/opt/norm/decorrelate.go:789 +0x18d
github.com/cockroachdb/cockroach/pkg/sql/opt/norm.(*subqueryHoister).hoistAll.func1(0x6e522c0, 0xc007b0b950, 0xc007b0b950, 0x6e522c0)
        /Users/jordan/repo/src/github.com/cockroachdb/cockroach/pkg/sql/opt/norm/decorrelate.go:791 +0x70
github.com/cockroachdb/cockroach/pkg/sql/opt/norm.(*Factory).Reconstruct(0xc00815a278, 0x6e52600, 0xc006c82d00, 0xc0004578e0, 0xc006c82d00, 0xc00836da40)
        /Users/jordan/repo/src/github.com/cockroachdb/cockroach/pkg/sql/opt/norm/factory.og.go:12899 +0x2fbe
github.com/cockroachdb/cockroach/pkg/sql/opt/norm.(*subqueryHoister).hoistAll(0xc008778120, 0x6e5d360, 0xc006c82d00, 0x6e5d360, 0xc006c82d00)
        /Users/jordan/repo/src/github.com/cockroachdb/cockroach/pkg/sql/opt/norm/decorrelate.go:789 +0x18d
github.com/cockroachdb/cockroach/pkg/sql/opt/norm.(*subqueryHoister).hoistAll.func1(0x6e52600, 0xc006c82d00, 0xc006c82d00, 0x6e52600)
        /Users/jordan/repo/src/github.com/cockroachdb/cockroach/pkg/sql/opt/norm/decorrelate.go:791 +0x70
github.com/cockroachdb/cockroach/pkg/sql/opt/norm.(*Factory).Reconstruct(0xc00815a278, 0x6e53740, 0xc0066cf710, 0xc0004578d0, 0xc0066cf710, 0x6482cc0)
        /Users/jordan/repo/src/github.com/cockroachdb/cockroach/pkg/sql/opt/norm/factory.og.go:13113 +0x8729
github.com/cockroachdb/cockroach/pkg/sql/opt/norm.(*subqueryHoister).hoistAll(0xc008778120, 0x6e5e4a0, 0xc0066cf710, 0x6e5e4a0, 0xc0066cf710)
        /Users/jordan/repo/src/github.com/cockroachdb/cockroach/pkg/sql/opt/norm/decorrelate.go:789 +0x18d
github.com/cockroachdb/cockroach/pkg/sql/opt/norm.(*subqueryHoister).hoistAll.func1(0x6e53740, 0xc0066cf710, 0xc0066cf710, 0x6e53740)
        /Users/jordan/repo/src/github.com/cockroachdb/cockroach/pkg/sql/opt/norm/decorrelate.go:791 +0x70
github.com/cockroachdb/cockroach/pkg/sql/opt/norm.(*Factory).reconstructScalarListExpr(0xc00815a278, 0xc006c82b80, 0x1, 0x2, 0xc0004578b0, 0x0, 0x40731f7, 0xc006226066, 0x671bbb0)
        /Users/jordan/repo/src/github.com/cockroachdb/cockroach/pkg/sql/opt/norm/factory.og.go:13388 +0xc6
github.com/cockroachdb/cockroach/pkg/sql/opt/norm.(*Factory).Reconstruct(0xc00815a278, 0x6e51b40, 0xc007b0b9f0, 0xc0004578b0, 0xc007b0b9f0, 0x6e51b40)
        /Users/jordan/repo/src/github.com/cockroachdb/cockroach/pkg/sql/opt/norm/factory.og.go:13105 +0x5275
github.com/cockroachdb/cockroach/pkg/sql/opt/norm.(*subqueryHoister).hoistAll(0xc008778120, 0x6e5c7c0, 0xc007b0b9f0, 0xc00772b900, 0x0)
        /Users/jordan/repo/src/github.com/cockroachdb/cockroach/pkg/sql/opt/norm/decorrelate.go:789 +0x18d
github.com/cockroachdb/cockroach/pkg/sql/opt/norm.(*CustomFuncs).HoistProjectSubquery(0xc00815a288, 0x6e77340, 0xc007adacb8, 0xc007c40f00, 0x2, 0x8, 0x10, 0x0, 0xc006227b6b, 0x2)
        /Users/jordan/repo/src/github.com/cockroachdb/cockroach/pkg/sql/opt/norm/decorrelate.go:165 +0x323
github.com/cockroachdb/cockroach/pkg/sql/opt/norm.(*Factory).ConstructProject(0xc00815a278, 0x6e77340, 0xc007adacb8, 0xc007c40f00, 0x2, 0x8, 0x10, 0x0, 0xc009b0e668, 0x44c8889)
        /Users/jordan/repo/src/github.com/cockroachdb/cockroach/pkg/sql/opt/norm/factory.og.go:1035 +0x860
github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder.(*Builder).constructProject(0xc008b85d10, 0x6e77340, 0xc007adacb8, 0xc007308d80, 0x8, 0x8, 0x0, 0x0)
        /Users/jordan/repo/src/github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder/project.go:61 +0x37c
github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder.(*Builder).constructProjectForScope(0xc008b85d10, 0xc008b01de0, 0xc0055ae2d0)
        /Users/jordan/repo/src/github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder/project.go:33 +0x1d1
github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder.(*Builder).buildSelectClause(0xc008b85d10, 0xc007b08d80, 0x0, 0x0, 0x0, 0xc008b01c00, 0xc009b0e908)
        /Users/jordan/repo/src/github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder/select.go:524 +0x2c1
github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder.(*Builder).buildSelect(0xc008b85d10, 0xc007b0c040, 0xc008b01c00, 0xe8)
        /Users/jordan/repo/src/github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder/select.go:449 +0x1d1
github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder.(*Builder).buildStmt(0xc008b85d10, 0x6e4a100, 0xc007b0c040, 0xc008b01c00, 0x4)
        /Users/jordan/repo/src/github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder/builder.go:187 +0xf1
github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder.(*Builder).Build(0xc008b85d10, 0x0, 0x0)
        /Users/jordan/repo/src/github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder/builder.go:144 +0xf6
github.com/cockroachdb/cockroach/pkg/sql.(*planner).makeOptimizerPlan(0xc008159718, 0x6e46ac0, 0xc009819d10, 0x6e4a100, 0xc007b0c040, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /Users/jordan/repo/src/github.com/cockroachdb/cockroach/pkg/sql/plan.go:425 +0x2ca
github.com/cockroachdb/cockroach/pkg/sql.(*planner).optionallyUseOptimizer(0xc008159718, 0x6e46ac0, 0xc009819d10, 0xc007c5e2e0, 0xd, 0xc005377017, 0x9, 0x0, 0x1, 0x0, ...)
        /Users/jordan/repo/src/github.com/cockroachdb/cockroach/pkg/sql/planner.go:552 +0xc4
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).dispatchToExecutionEngine(0xc008159300, 0x6e46ac0, 0xc009819d10, 0x6e4a100, 0xc007b0c040, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /Users/jordan/repo/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:765 +0x189
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execStmtInOpenState(0xc008159300, 0x6e46ac0, 0xc009819d10, 0x6e4a100, 0xc007b0c040, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /Users/jordan/repo/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:402 +0xaa7
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execStmt(0xc008159300, 0x6e46ac0, 0xc009819d10, 0x6e4a100, 0xc007b0c040, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /Users/jordan/repo/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:96 +0x333
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).run(0xc008159300, 0x6e46a00, 0xc006436c80, 0xc0007c9998, 0x5400, 0x15000, 0xc0007c9a30, 0xc008604300, 0x0, 0x0)
        /Users/jordan/repo/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:1113 +0x2131
github.com/cockroachdb/cockroach/pkg/sql.(*Server).ServeConn(0xc0008dcb40, 0x6e46a00, 0xc006436c80, 0xc008159300, 0x5400, 0x15000, 0xc0007c9a30, 0xc008604300, 0x0, 0x0)
        /Users/jordan/repo/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:390 +0xce
github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*conn).serveImpl.func4(0xc0008dcb40, 0x6e46a00, 0xc006436c80, 0xc008159300, 0x5400, 0x15000, 0xc0007c9a30, 0xc008604300, 0xc008604310, 0xc007c5e224)
        /Users/jordan/repo/src/github.com/cockroachdb/cockroach/pkg/sql/pgwire/conn.go:309 +0x81
created by github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*conn).serveImpl
        /Users/jordan/repo/src/github.com/cockroachdb/cockroach/pkg/sql/pgwire/conn.go:308 +0x1018```

Found with sqlsmith

### PR DESCRIPTION
**Pull request by andy-kimball**
Fixes #32270.

The panic occurs when hoisting an expression that has both a correlated
and an uncorrelated subquery. The current code panics when calling
Reconstruct on the relational input to the uncorrelated subquery. The
fix is to test for relational inputs and skip over them. They are not
correlated, and so no hoisting needs to be done within their subtree.

Release note (sql change): Fix panic when expression contains both a
correlated and uncorrelated subquery.

### CODE REVIEW

File: pkg/sql/opt/norm/decorrelate.go [hunk 1]
```diff
@@ -793,8 +793,15 @@ func (r *subqueryHoister) hoistAll(scalar opt.ScalarExpr) opt.ScalarExpr {
 	}
 
 	return r.f.Reconstruct(scalar, func(nd opt.Expr) opt.Expr {
-		// Recursively hoist subqueries in each child that contains them.
-		return r.hoistAll(nd.(opt.ScalarExpr))
+		// Recursively hoist subqueries in each scalar child that contains them.
+		// It is not necessary to descend into relational children, because only
+		// subquery scalar operators have a relational child, and they are handled
+		// above, either because they're not correlated, or because they've already
+		// been hoisted.
```
Comment (justinj) [inline pkg/sql/opt/norm/decorrelate.go]: I think the commit message explains this a little better than this comment. The comment implies that we skip over both correlated and uncorrelated relational expressions, but I think here the deal is that we (still) won't encounter correlated relational expressions, and we want to skip over the uncorrelated ones, right?

**Review by justinj — APPROVED** [review]
LGTM

**Review by rytaft — APPROVED** [review]
[nit] I think you should put the issue number in the body of the commit/PR message rather than the header so that the GitHub workflow will work correctly. If you add a line to the body of the PR message that says "Fixes #32270", the craigbot will update the issue with a reference to this PR, and close the issue when this PR merges.

Also, I think this probably deserves a release note.

Otherwise, :lgtm:, once you address Justin's comment

> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/32443#-:-LRhlfz0AFSpwuzPYWpE:b-oi4snx)* status: :shipit: complete! 1 of 0 LGTMs obtained

**Review by andy-kimball — COMMENTED** [review]
This isn't a problem in 2.1, so I don't think we use a release note in that case, do we? This bug was only introduced by my expression rewrite, so it's an intra-release bug.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/32443#-:-LRxEGRV607bxTUeZ2md:b-b1su9z)* status: :shipit: complete! 1 of 0 LGTMs obtained

___
*[pkg/sql/opt/norm/decorrelate.go, line 800 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/32443#-LRUvMR50q7K8vOpUb6f-r1-800:-LRxBE4hBFxuIjHsVKEf:b-zbyc77) ([raw file](https://github.com/cockroachdb/cockroach/blob/f61832c87473924617a3ea14e3f42625797b0991/pkg/sql/opt/norm/decorrelate.go#L800)):*
<details><summary><i>Previously, justinj (Justin Jaffray) wrote…</i></summary><blockquote>

I think the commit message explains this a little better than this comment. The comment implies that we skip over both correlated and uncorrelated relational expressions, but I think here the deal is that we (still) won't encounter correlated relational expressions, and we want to skip over the uncorrelated ones, right?
</blockquote></details>

Rewrote this.

**Review by rytaft — COMMENTED** [review]
But was the bug in the first 2.2 alpha release? If so, I would think the next alpha release should still have the release note. But it's definitely less important if the bug is not in 2.1... 

(Also - I saw that you updated the commit message, but I think you may also need to update the PR message for the issue to be closed automatically)

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/32443#-:-LSD31I2CPvTZ-OuC3-p:b-36gv76)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)
