### PR TITLE
ui, sql: fix display of "database dropped" event.

### LINKED ISSUE #18523: ui: odd events log message when dropping database
I just dropped a database in the PM cluster, and the event that showed up is below. The event shows that no tables were dropped, but there were several tables in the tpch database. Is this the behavior users would expect?

image

### PR DESCRIPTION
**Pull request by vilterp**
The DROP_DATABASE event in `system.eventlog`  was changed from having the key `DroppedTables` to having the key `DroppedTablesAndViews`. The corresponding UI code which displays the dropped tables was not changed, creating bug #18523.

This commit fixes #18523 by renaming the key to `DroppedSchemaObjects`, both in the event and in the UI code. The term "Schema Objects" accounts for the existence of sequences in addition to views and tables.

Q: is it worth adding a migration to change old events from `DroppedTablesAndViews` to `DroppedSchemaObjects`? I'm leaning toward no, since (a) it doesn't look like we added a migration when we renamed `DroppedTables` to `DroppedTablesAndViews`, and (b) without the migration, you'll still see the "drop database" event in the UI, just not the table names (but they'll be in `system.eventlog` under the old key).

Release note (admin ui change): display the names of dropped schema objects on `DROP DATABASE ... CASCADE`

### CODE REVIEW

**Comment by mrtracy** [comment]
Could you make *just* the UI backwards compatible? It could test for the presence of either the old DroppedTables info field or the new DroppedSchemaObjects.

**Comment by couchand** [comment]
Yeah, I'm a fan of @mrtracy's suggestion. I'd add that we should also handle `DroppedTablesAndViews` since we shipped a version that's recording that, too.

File: pkg/ui/src/util/events.ts [hunk 1]
```diff
@@ -27,14 +27,15 @@ export function getEventDescription(e: Event$Properties): string {
     case eventTypes.CREATE_DATABASE:
       return `Database Created: User ${info.User} created database ${info.DatabaseName}`;
     case eventTypes.DROP_DATABASE:
-      info.DroppedTables = info.DroppedTables || [];
-      let tableDropText: string = `${info.DroppedTables.length} tables were dropped: ${info.DroppedTables.join(", ")}`;
-      if (info.DroppedTables.length === 0) {
-        tableDropText = "No tables were dropped.";
-      } else if (info.DroppedTables.length === 1) {
-        tableDropText = `1 table was dropped: ${info.DroppedTables[0]}`;
+      info.DroppedSchemaObjects = info.DroppedSchemaObjects || [];
```
Comment (couchand) [inline pkg/ui/src/util/events.ts]: I find this defensiveness suspicious.  If we don't have an array here at all, doesn't that mean we just don't have the information?  I'd be inclined to just not include the second sentence in that case.

File: pkg/ui/src/util/events.ts [hunk 2]
```diff
@@ -27,14 +27,15 @@ export function getEventDescription(e: Event$Properties): string {
...
+      let tableDropText = `${info.DroppedSchemaObjects.length} schema objects ` +
+        `were dropped: ${info.DroppedSchemaObjects.join(", ")}`;
+      if (info.DroppedSchemaObjects.length === 0) {
+        tableDropText = "No schema objects were dropped.";
+      } else if (info.DroppedSchemaObjects.length === 1) {
+        tableDropText = `1 schema objects was dropped: ${info.DroppedSchemaObjects[0]}`;
```
Comment (couchand) [inline pkg/ui/src/util/events.ts]: grammar, or maybe just use `pluralize`?

**Review by couchand — COMMENTED** [review]
Is there some way to make sure this sort of bug doesn't happen again?  Can we write a test that breaks for someone if they change the schema without updating the UI?

File: pkg/ui/src/util/events.ts (hunk 1 above)
Comment (vilterp) [reply pkg/ui/src/util/events.ts]: Done.

File: pkg/ui/src/util/events.ts (hunk 2 above)
Comment (vilterp) [reply pkg/ui/src/util/events.ts]: Done.

**Comment by vilterp** [comment]
Made the UI backwards-compatible, per @mrtracy's suggestion, and added a JS unit test to show that it can handle all three formats. However, don't know how to write a test that would fail if someone changes the key on the Go side, other than an integration test which uses both Go and JS.

This is what protobufs are for — maybe the event info should be a protobuf, that's serialized as JSON into a column in the table, or something. This problem will come up again as we display richer data in the admin UI from other tables that have JSON in them, e.g. the range log.

File: pkg/ui/src/util/events.ts [hunk 3]
```diff
@@ -80,3 +63,36 @@ export function getEventDescription(e: Event$Properties): string {
...
+    eventInfo.DroppedSchemaObjects || eventInfo.DroppedTablesAndViews || eventInfo.DroppedTables;
+  if (!droppedObjects) {
+    return "";
+  }
+  if (droppedObjects.length === 0) {
+    return "No schema objects were dropped.";
+  } else if (droppedObjects.length === 1) {
+    return `1 schema object was dropped: ${droppedObjects[0]}`;
+  }
+  return `${droppedObjects.length} schema objects were dropped: ${droppedObjects.join(", ")}`;
```
Comment (couchand) [inline pkg/ui/src/util/events.ts]: but your fancy pluralize thing!

**Review by couchand — APPROVED** [review]

File: pkg/ui/src/util/events.ts [hunk 4]
```diff
@@ -80,3 +63,36 @@ export function getEventDescription(e: Event$Properties): string {
...
+  DatabaseName?: string;
+  TableName?: string;
+  IndexName?: string;
+  MutationID?: string;
+  ViewName?: string;
+  SequenceName?: string;
+  SettingName?: string;
+  Value?: string;
+  // The following are three names for the same key (it was renamed twice).
+  // All ar included for backwards compatibility.
```
Comment (couchand) [inline pkg/ui/src/util/events.ts]: s/ar/are/
