### PR TITLE
sql: fix float to integer casting

### LINKED ISSUE #112515: sql: float cast to integer is incorrect
Casting a float value to an integer is meant to round to the nearest integer, but currently, CRDB just truncates the float. See a comparison against postgres:
```
root@localhost:26257/system/defaultdb> select 0.9090909090909091::float8::int8;
  int8
--------
     0
(1 row)
```
vs
```
postgres=# select 0.9090909090909091::float8::int8;
 int8
------
    1
(1 row)
```

Jira issue: CRDB-32461

### PR DESCRIPTION
**Pull request by da-ket**
Previously, casting a float value to an integer simply truncates the float. This commit fixes that by rounding the float value to the nearest integer, rounding ties to even, as in postgres.

Epic: None
Fixes: #112515

Release note (bug fix): A bug has been fixed where casts of floats to integers
truncated the value. These casts now round a float to the nearest integer,
rounding ties to even integers.

### CODE REVIEW

**Review by da-ket — COMMENTED** [review]
Hello! The updated test code all matches with postgres.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/117798#-:-NoGVk1aBmRWW3JoW4lm:b-eu7m0k)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @DrewKimball)

___
*[`pkg/ccl/logictestccl/testdata/logic_test/udf_plpgsql` line 2419 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/117798#-NoGQhXaDbhoa7LEYeeH:-NoGQhXaDbhoa7LEYeeI:bvohnkr) ([raw file](https://github.com/cockroachdb/cockroach/blob/37fe58fbb878f72bd49fee0ef89cd0f7fca3cc8c/pkg/ccl/logictestccl/testdata/logic_test/udf_plpgsql#L2419)):*
> ```
> SELECT f();
> ----
> 106
> ```

```sql
postgres=# CREATE OR REPLACE FUNCTION f() RETURNS INT AS $$
postgres$#   BEGIN
postgres$#     RETURN 105.67::FLOAT;
postgres$#   END  
postgres$# $$ LANGUAGE PLpgSQL;
CREATE FUNCTION
postgres=# SELECT f();
  f  
-----
 106
(1 row)
```
___
*[`pkg/sql/logictest/testdata/logic_test/aggregate` line 992 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/117798#-NoGUp4z4D1zNDYz_Z3o:-NoGUp4z4D1zNDYz_Z3p:b1wsfem) ([raw file](https://github.com/cockroachdb/cockroach/blob/37fe58fbb878f72bd49fee0ef89cd0f7fca3cc8c/pkg/sql/logictest/testdata/logic_test/aggregate#L992)):*
> ```
> SELECT round(variance(n), 2), round(variance(n), 2), round(variance(p)) FROM mnop
> ----
> 0.08 0.08 9
> ```

```sql
postgres=# CREATE TABLE mnop (
postgres(#   m INT PRIMARY KEY, 
postgres(#   n FLOAT,
postgres(#   o DECIMAL,
postgres(#   p BIGINT
postgres(# )
postgres-# ;
CREATE TABLE
postgres=# INSERT INTO mnop (m, n) SELECT i, (1e9 + i/100.0)::float FROM 
postgres-#   generate_series(1, 100) AS i(i) ;
INSERT 0 100
postgres=# UPDATE mnop SET o = n::decimal, p = (n * 10)::bigint;
UPDATE 100
postgres=# select round(variance(p)) from mnop;
 round 
-------
     9
(1 row)
```
___
*[`pkg/sql/logictest/testdata/logic_test/aggregate` line 997 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/117798#-NoGVBrC9V6W5qOp0hrx:-NoGVBrC9V6W5qOp0hry:b-8q6z4c) ([raw file](https://github.com/cockroachdb/cockroach/blob/37fe58fbb878f72bd49fee0ef89cd0f7fca3cc8c/pkg/sql/logictest/testdata/logic_test/aggregate#L997)):*
> ```
> SELECT round(var_pop(n), 2), round(var_pop(n), 2), round(var_pop(p)) FROM mnop
> ----
> 0.08 0.08 9
> ```

```sql
postgres=# select round(var_pop(p)) FROM mnop;
 round 
-------
     9
(1 row)
```
___
*[`pkg/sql/logictest/testdata/logic_test/target_names` line 76 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/117798#-NoGVeEL3iidlTWxN-W8:-NoGVeEL3iidlTWxN-W9:b-h0d003) ([raw file](https://github.com/cockroachdb/cockroach/blob/37fe58fbb878f72bd49fee0ef89cd0f7fca3cc8c/pkg/sql/logictest/testdata/logic_test/target_names#L76)):*
> ```
> ----
> a   column1 cos
> 123 1       1
> ```

```sql
postgres=# SELECT (SELECT 123 AS a), 
postgres-#        (VALUES (cos(1)::INT)),
postgres-#        (SELECT cos(0)::INT);
  a  | column1 | cos 
-----+---------+-----
 123 |       1 |   1
(1 row)
```

**Review by mgartner — CHANGES_REQUESTED** [review]
Thank you for the contribution! This looks great. I left one comment about the commit message.

> Reviewed 7 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/117798#-:-NoHvDuz5xUcEeo45agC:b-447wz1)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @da-ket and @DrewKimball)

___
*[`-- commits` line 9 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/117798#-NoHuJux2CTChU768KF5):*
Can you add a release note at the bottom of the commit, like:

```
Release note (bug fix): A bug has been fix where casts of floats to integers truncated
the value. These casts now round a float to the nearest integer, rounding ties to even
integers.
```

**Review by da-ket — COMMENTED** [review]
Thank you for the review! I followed your guidance on writing the release notes.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/117798#-:-NoI940t2pBO_rEjo3Vd:b-h5dich)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @DrewKimball and @mgartner)

___
*[`-- commits` line 9 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/117798#-NoHuJux2CTChU768KF5):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

Can you add a release note at the bottom of the commit, like:

```
Release note (bug fix): A bug has been fix where casts of floats to integers truncated
the value. These casts now round a float to the nearest integer, rounding ties to even
integers.
```
</blockquote></details>

Done.

**Review by da-ket — COMMENTED** [review]
Hi @mgartner , just a gentle reminder about the pending review of this pull request.
Your feedback would be greatly appreciated!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/117798#-:-NpYsVXTE2S8_seI9ruw:buu14zf)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @DrewKimball and @mgartner)

File: pkg/sql/colexec/execgen/cmd/execgen/cast_gen_util.go [hunk 1]
```diff
@@ -271,7 +271,7 @@ func floatToInt(intWidth, floatWidth int32) castFunc {
 			if math.IsNaN(float64(%[2]s)) || %[2]s <= float%[4]d(math.MinInt%[3]d) || %[2]s >= float%[4]d(math.MaxInt%[3]d) {
 				colexecerror.ExpectedError(tree.ErrIntOutOfRange)
 			}
-			%[1]s = int%[3]d(%[2]s)
+			%[1]s = int%[3]d(math.RoundToEven(%[2]s))
```
Comment (RaduBerinde) [inline pkg/sql/colexec/execgen/cmd/execgen/cast_gen_util.go:274]: Why RoundToEven? Does postgres do that?

Comment (RaduBerinde) [reply pkg/sql/colexec/execgen/cmd/execgen/cast_gen_util.go:274]: Ah, I was reading the postgres docs for the ROUND function. I couldn't find specific documentation on casting.

**Review by da-ket — COMMENTED** [review]
Thanks for the comments!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/117798#-:-Npd-zUj08SuGdsvZ5sM:b-a09w3v)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @DrewKimball, @mgartner, and @RaduBerinde)

___
*[`pkg/sql/colexec/execgen/cmd/execgen/cast_gen_util.go` line 274 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/117798#gh-1475520144:-Npcl5Lq4mBwN65mtqtt:b-ldgxbv) ([raw file](https://github.com/cockroachdb/cockroach/blob/2b6e917c0f7ebf05ca5ecb43a970d1312bcbdfc1/pkg/sql/colexec/execgen/cmd/execgen/cast_gen_util.go#L274)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

Ah, I was reading the postgres docs for the ROUND function. I couldn't find specific documentation on casting.
</blockquote></details>

Yes, I used `RoundToEven` since postgres does do that when casting floats to integers. It isn't clearly mentioned in the documentation, but it can be found in their [code](https://github.com/postgres/postgres/blob/0b6517a3b79ae02fb95731d8b1dc70b10cf7b532/src/backend/utils/adt/float.c#L1222)  for built-in functions for float type. PostgreSQL follows the [round to nearest, ties to even rule](https://en.wikipedia.org/wiki/IEEE_754#Roundings_to_nearest) for both rounding of float types and their casting to integers. CRDB was follows the same tie-breaking rule for rounding, but it just truncates when casting. I thought the issue #112515 wants to align this difference to be consistent.

**Comment by RaduBerinde** [comment]
*[`pkg/sql/colexec/execgen/cmd/execgen/cast_gen_util.go` line 274 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/117798#gh-1475520144:-NpdJcfA4f83WaKnaBU9:b1roi3e) ([raw file](https://github.com/cockroachdb/cockroach/blob/2b6e917c0f7ebf05ca5ecb43a970d1312bcbdfc1/pkg/sql/colexec/execgen/cmd/execgen/cast_gen_util.go#L274)):*
<details><summary><i>Previously, da-ket (daket) wrote…</i></summary><blockquote>

Yes, I used `RoundToEven` since postgres does do that when casting floats to integers. It isn't clearly mentioned in the documentation, but it can be found in their [code](https://github.com/postgres/postgres/blob/0b6517a3b79ae02fb95731d8b1dc70b10cf7b532/src/backend/utils/adt/float.c#L1222)  for built-in functions for float type. PostgreSQL follows the [round to nearest, ties to even rule](https://en.wikipedia.org/wiki/IEEE_754#Roundings_to_nearest) for both rounding of float types and their casting to integers. CRDB was follows the same tie-breaking rule for rounding, but it just truncates when casting. I thought the issue #112515 wants to align this difference to be consistent.
</blockquote></details>

Makes sense, thank you!

**Review by mgartner — APPROVED** [review]
Looks great. Thanks again from contributing! I added a regression test for the change in the vectorized engine `cast_gen_util.go`. I'll go ahead and merge this once all the tests pass.


:lgtm:

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/117798#-:-Np_NPWF4XI_28AshUUu:b49db3o)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @da-ket and @DrewKimball)
