### PR TITLE
roachtest: update asyncpg blocklist

### LINKED ISSUE #73012: roachtest: asyncpg failed
roachtest.asyncpg [failed](https://teamcity.cockroachdb.com/viewLog.html?buildId=3767558&tab=buildLog) with [artifacts](https://teamcity.cockroachdb.com/viewLog.html?buildId=3767558&tab=artifacts#/asyncpg) on master @ [8ef90ca92676389da2c955054ab5d996bb9ae6ff](https://github.com/cockroachdb/cockroach/commits/8ef90ca92676389da2c955054ab5d996bb9ae6ff):

```
The test failed on branch=master, cloud=gce:
test artifacts and logs in: /home/agent/work/.go/src/github.com/cockroachdb/cockroach/artifacts/asyncpg/run_1
	orm_helpers.go:245,orm_helpers.go:171,asyncpg.go:128,asyncpg.go:139,test_runner.go:777: 
		Tests run on Cockroach v22.1.0-alpha.00000000-1437-g8ef90ca926
		Tests run against asyncpg v0.24.0
		135 Total Tests Run
		134 tests passed
		1 test failed
		34 tests skipped
		92 tests ignored
		0 tests passed unexpectedly
		1 test failed unexpectedly
		0 tests expected failed but skipped
		0 tests expected failed but not run
		---
		--- FAIL: test_pool.TestPool.test_pool_handles_transaction_exit_in_asyncgen_1 (unexpected)
		For a full summary look at the asyncpg artifacts 
		
		An updated blocklist (asyncpgBlocklist22_1) is available in the artifacts' asyncpg log
```
<details><summary>Help</summary>
<p>

See: [roachtest README](https://github.com/cockroachdb/cockroach/blob/master/pkg/cmd/roachtest/README.md)

See: [How To Investigate \(internal\)](https://cockroachlabs.atlassian.net/l/c/SSSBr8c7)

</p>
</details>
/cc @cockroachdb/sql-experience
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*asyncpg.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)
</sub>

### PR DESCRIPTION
**Pull request by RichardJCai**
Release note: None

Resolves https://github.com/cockroachdb/cockroach/issues/73012

### CODE REVIEW

File: pkg/cmd/roachtest/tests/asyncpg_blocklist.go [hunk 1]
```diff
@@ -23,7 +23,105 @@ var asyncpgBlocklists = blocklistsForVersion{
 // Please keep these lists alphabetized for easy diffing.
 // After a failed run, an updated version of this blocklist should be available
 // in the test log.
-var asyncpgBlocklist22_1 = asyncpgBlocklist21_2
```
Comment (rafiss) [inline pkg/cmd/roachtest/tests/asyncpg_blocklist.go:26]: flaky tests should be in the `ignoreList`, while tests that fail reliably should be in the `blockList`

right now looks like there's some overlap between the two lists?

**Review by rafiss — CHANGES_REQUESTED** [review]

File: pkg/cmd/roachtest/tests/asyncpg_blocklist.go (hunk 1 above)
Comment (RichardJCai) [reply pkg/cmd/roachtest/tests/asyncpg_blocklist.go:26]: Oops this should all be ignoreList, fixed.

**Review by rafiss — APPROVED** [review]

**Comment by RichardJCai** [comment]
Thanks!
bors r=rafiss
