### PR TITLE
kvserver: ignore leaseholder replica type in DistSender

### LINKED ISSUE #85060: kvserver: incorrect DistSender leaseholder processing for non-`VOTER`s
`ReplicaDescriptor.Type` is a pointer rather than a scalar value:

https://github.com/cockroachdb/cockroach/blob/aee773a3234d5e8ce521359e0fb6c24d9d7c93ba/pkg/roachpb/metadata.proto#L151

We often use regular equality comparisons on replica descriptors, notably in the DistSender and gRPC transport:

https://github.com/cockroachdb/cockroach/blob/f77e393230fbedb57e5caa0ebbf26356b3899c73/pkg/kv/kvclient/kvcoord/dist_sender.go#L2209

https://github.com/cockroachdb/cockroach/blob/9ad06da853ca0f306f4baeb09b446b5d001fbc53/pkg/kv/kvclient/kvcoord/transport.go#L258

But recall that equality for pointers will check that the memory address is the same, rather than that the value is the same. Thus two identical replica descriptors with a type different from `VOTER` (the zero value) will be considered unequal if they are stored in different memory locations.

One immediate effect of this is that the DistSender will not prioritize new leaseholders with a `VOTER_INCOMING` type. In #74546, `VOTER_INCOMING` was allowed to receive the lease and thus included in the DistSender's replica list with the `RoutingPolicy_LEASEHOLDER` policy:

https://github.com/cockroachdb/cockroach/blob/f77e393230fbedb57e5caa0ebbf26356b3899c73/pkg/kv/kvclient/kvcoord/dist_sender.go#L1932-L1943

However, when it receives the NLHE it attempts to move the new leaseholder to the front of the transport list:

https://github.com/cockroachdb/cockroach/blob/f77e393230fbedb57e5caa0ebbf26356b3899c73/pkg/kv/kvclient/kvcoord/dist_sender.go#L2201-L2212

But this won't happen because the non-`nil` `Type` doesn't satisfy the equality check in `MoveToFront`:

https://github.com/cockroachdb/cockroach/blob/9ad06da853ca0f306f4baeb09b446b5d001fbc53/pkg/kv/kvclient/kvcoord/transport.go#L258

Jira issue: CRDB-18022

### PR DESCRIPTION
**Pull request by erikgrinaker**
The DistSender could fail to prioritize a newly discovered leaseholder
from a `NotLeaseHolderError` if the leaseholder had a non-`VOTER`
replica type. Instead, it would continue to try replicas in order until
possibly exhausting the transport and backing off, leading to increased
tail latencies. This applies in particular to 22.1, where we allowed
`VOTER_INCOMING` replicas to acquire the lease (see 22b4fb51).

The primary reason is that `grpcTransport.MoveToFront()` would fail to
compare the new leaseholder replica descriptor with the one in its range
descriptor. There are two reasons why this can happen:

1. `ReplicaDescriptor.ReplicaType` is a pointer, where the zero-value
   `nil` is equivalent to `VOTER`. The equality comparison used in
   `MoveToFront()` is `==`, but pointer equality compares the memory
   address rather than the value.

2. The transport will keep using the initial range descriptor when it
   was created, and not updating it as we receive updated range
   descriptors. This means that the transport may e.g. have a `nil`
   replica type while the leaseholder has an `VOTER_INCOMING` replica
   type.

This patch fixes both issues by adding `ReplicaDescriptor.IsSame()`
which compares replica identities while ignoring the type.

Resolves #85060.
Touches #74546.

Release note (bug fix): Fixed a bug where new leaseholders (with a
`VOTER_INCOMING` type) would not always be detected properly during
query execution, leading to occasional increased tail latencies due
to unnecessary internal retries.

### CODE REVIEW

**Review by arulajmani — APPROVED** [review]
:lgtm: 

> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/85140#-:-N84VVEDB1N6uq0MWHze:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @nvanbenschoten and @pavelkalinnikov)

File: pkg/roachpb/metadata.go [hunk 1]
```diff
@@ -416,6 +416,12 @@ func (r ReplicaDescriptor) String() string {
 	return redact.StringWithoutMarkers(r)
 }
 
+// IsSame returns true if the two replica descriptors refer to the same replica,
+// ignoring the replica type.
+func (r ReplicaDescriptor) IsSame(o ReplicaDescriptor) bool {
+	return r.NodeID == o.NodeID && r.StoreID == o.StoreID && r.ReplicaID == o.ReplicaID
```
Comment (pavelkalinnikov) [inline pkg/roachpb/metadata.go:422]: What are the relations between node, store, and replica?

Comment (pavelkalinnikov) [reply pkg/roachpb/metadata.go:422]: Is `ReplicaID` local to a pair of (`NodeID`, `StoreID`)? Can it be compared without any of the two?

Comment (erikgrinaker) [reply pkg/roachpb/metadata.go:422]: One-to-many all the way down. One node can have many stores (disks), one store can have many replicas.

The node ID must be unique within the cluster. The store ID must be unique per node. The replica ID must be unique within the range. The range ID is sort of implied here, in that the replica descriptor is stored within a range descriptor.

In order to route a request to a replica we need to know all four. A replica ID won't move between nodes/stores -- if we have to move it, we'll create a new replica (with a new ID) on a different node, populate it, and then delete the old one.

Comment (erikgrinaker) [reply pkg/roachpb/metadata.go:422]: You're right in that we technically only need to compare the replica ID here, since we're operating within the context of a single range. We check the node ID and store ID just to make sure we have the right "address" for it, I suppose.

**Comment by erikgrinaker** [comment]
TFTR!

bors r=arulajmani

File: pkg/roachpb/metadata.go (hunk 1 above)
Comment (pavelkalinnikov) [reply pkg/roachpb/metadata.go:422]: Ok, so: (rangeID, replicaID) -> (nodeID, storeID), and rangeID is implied by the caller of `IsSame` (otherwise, due to locality of replicaID, it would be comparing apples to tables). Hence, is it enough to just compare `ReplicaID`s? From what you said it follows that if rangeID and replicaID are the same then nodeID and storeID are the same too.

Comment (pavelkalinnikov) [reply pkg/roachpb/metadata.go:422]: Ah, you answered this already. Were racing with the last 2 comments :)

Comment (erikgrinaker) [reply pkg/roachpb/metadata.go:422]: In principle it should be, yeah. But it's cheap enough to check the node and store too, so I don't see a strong reason not to. If there should be a mismatch for whatever reason, then there's no real point in trying to contact the replica anyway, because the transport will send it to the wrong place.
