### PR TITLE
roachtest: mvcc_gc disable lease rebalancing for stability

### LINKED ISSUE #97340: roachtest: mvcc_gc failed
roachtest.mvcc_gc [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/8757413?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/8757413?buildTab=artifacts#/mvcc_gc) on master @ [3d054f37c7c87f53cb56fac4e5500f0d1130d09a](https://github.com/cockroachdb/cockroach/commits/3d054f37c7c87f53cb56fac4e5500f0d1130d09a):

```
test artifacts and logs in: /artifacts/mvcc_gc/run_1
(mvcc_gc.go:191).assertRangesWithGCRetry: assertion still failing after 7m0s: table ranges contain range tombstones contains_estimates:0 last_update_nanos:1676824274662467696 intent_age:0 gc_bytes_age:124969876394 live_bytes:41619852 live_count:20000 key_bytes:5635492 key_count:20000 val_bytes:921026320 val_count:447970 intent_bytes:0 intent_count:0 separated_intent_count:0 range_key_count:1 range_key_bytes:33 range_val_count:1 range_val_bytes:0 sys_bytes:23296 sys_count:400 abort_span_bytes:0
(monitor.go:127).Wait: monitor failure: monitor task failed: t.Fatal() was called
```
<p>Parameters: <code>ROACHTEST_cloud=gce</code>
, <code>ROACHTEST_cpu=4</code>
, <code>ROACHTEST_encrypted=false</code>
, <code>ROACHTEST_fs=ext4</code>
, <code>ROACHTEST_localSSD=true</code>
, <code>ROACHTEST_ssd=0</code>
</p>
<details><summary>Help</summary>
<p>

See: [roachtest README](https://github.com/cockroachdb/cockroach/blob/master/pkg/cmd/roachtest/README.md)

See: [How To Investigate \(internal\)](https://cockroachlabs.atlassian.net/l/c/SSSBr8c7)

</p>
</details>
/cc @cockroachdb/kv-triage
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*mvcc_gc.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)
</sub>

Jira issue: CRDB-24645

### PR DESCRIPTION
**Pull request by aliher1911**
Test sometimes flakes if lease is moved from under GC and cleanup is not performed in time. This commit disables rebalance as it is not required to test GC functionality.
This commit also improves reliability of test by preventing a race between workload stop and table data deletion which could cause test to fail if workload doesn't terminate before clear range is performed.

Release note: None

Fixes #97340

### CODE REVIEW

File: pkg/cmd/roachtest/tests/mvcc_gc.go [hunk 1]
```diff
@@ -97,6 +97,7 @@ func runMVCCGC(ctx context.Context, t test.Test, c cluster.Cluster) {
 	setClusterSetting("storage.mvcc.range_tombstones.enabled", true)
 	setClusterSetting("kv.protectedts.poll_interval", "5s")
 	setClusterSetting("kv.mvcc_gc.queue_interval", "0s")
+	setClusterSetting("kv.allocator.load_based_lease_rebalancing.enabled", false)
```
Comment (erikgrinaker) [inline pkg/cmd/roachtest/tests/mvcc_gc.go:100]: May want to mention why we do this.

**Review by erikgrinaker — APPROVED** [review]

**Comment by aliher1911** [comment]
bors r=erikgrinaker

**Comment by aliher1911** [comment]
bors r=erikgrinaker
