### PR TITLE
bulkio: Surface errors encountered during schedule planning or execution.

### LINKED ISSUE #52916: jobs: record/surface errors encountered during planning
Currently if a scheduled job encounters errors while _planning_ the job it wants to run, it logs but otherwise does not surface that error or otherwise give any indication that it even attempted to run that schedule. We should update the schedule to record failed to create job in the `changes` field, e.g. `schedulingErrors: []{time: 2020-08... , err: "failed to create job: ...."}`.

### PR DESCRIPTION
**Pull request by miretskiy**
Fixes #52916
Fixes #53235

If an error is enountered during schedule planning, appropriate
error messages are logged to the log file(s).  However, the user
might not have access to the logs on the machine.

We now record the last "interesting" schedule event in a new
column `schedule_state` in the `system.scheduled_jobs`, and display
this event with `SHOW SCHEDULES` command.

Whenever schedule completes with an error (either due to planning
or execution), we set the `schedule_state` appropriately.
When schedule completes without errors, we clear out `schedule_state`.

Since we need to alter `system.scheduled_jobs` schema, this PR also
updates the schema to:
  * Add a `NOT NULL` constraint to an `owner` field.
  * Drop `schedule_changes` column since the more complex, protocol
    buffer based column is no longer used.

Release Notes: None

### CODE REVIEW

File: pkg/jobs/scheduled_job.go [hunk 1]
```diff
@@ -39,11 +39,11 @@ type scheduledJobRecord struct {
 	ScheduleName    string                    `col:"schedule_name"`
 	Owner           string                    `col:"owner"`
 	NextRun         time.Time                 `col:"next_run"`
+	ScheduleStatus  string                    `col:"schedule_status"`
```
Comment (dt) [inline pkg/jobs/scheduled_job.go:42]: Even though we're just doing a string _for now_ I'd put a proto message with a string in it here, just so we have flexibility later and avoid annoying schema change migrations. It doesn't need to change what we'd show since we can pb_to_json()->'message' it.

File: pkg/jobs/scheduled_job.go [hunk 2]
```diff
@@ -256,15 +247,15 @@ func (j *ScheduledJob) ScheduleExpr() string {
...
+	j.SetScheduleStatus(reason)
 }
 
 // Unpause resumes running this schedule.
 func (j *ScheduledJob) Unpause(reason string) error {
 	if err := j.SetSchedule(j.rec.ScheduleExpr); err != nil {
 		return err
 	}
-	j.AddScheduleChangeReason(reason)
+	j.SetScheduleStatus(reason)
```
Comment (dt) [inline pkg/jobs/scheduled_job.go:258]: I'm not convinced we want Unpause setting a status, or pause either. IMO i'd remove `reason` from both of these, and during inc schedule creation just call Pause + SetScheduleStatus directly.

File: pkg/jobs/job_scheduler.go [hunk 3]
```diff
@@ -254,23 +288,40 @@ func (s *jobScheduler) executeSchedules(
...
 
-		if err := txn.ReleaseSavepoint(ctx, sp); err != nil {
-			return err
+			// Failed to process schedule.
+			s.metrics.NumBadSchedules.Inc(1)
+			log.Errorf(ctx,
+				"error processing schedule %d: %+v", schedule.ScheduleID(), processErr)
+
+			// Try updating schedule record to indicate schedule execution error.
+			// We can't be sure that processSchedule didn't mutate schedule.
```
Comment (dt) [inline pkg/jobs/job_scheduler.go:304]: Eh, now this is why I don't like this ORM pattern -- here we need to load our object to act on it when all what we want is a single-roundtrip `executor.Exec(ctx, "UPDATE %s SET status =...)`. I know everything else about schedule uses its little ORM instead of using SQL so it makes sense to keep doing that here though so not suggesting otherwise, just have an axe to grind.

File: pkg/ccl/backupccl/create_scheduled_backup.go [hunk 4]
```diff
@@ -389,8 +389,8 @@ func emitSchedule(sj *jobs.ScheduledJob, backupStmt string, resultsCh chan<- tre
 	if sj.IsPaused() {
 		nextRun = tree.DNull
 		status = "PAUSED"
-		if reason := sj.LastChangeReason(); reason != "" {
-			status += ": " + reason
+		if s := sj.ScheduleStatus(); s != "" {
+			status += ": " + s
```
Comment (dt) [inline pkg/ccl/backupccl/create_scheduled_backup.go:393]: I mention below that we shouldn't stick the time in `s` but here's another reason: this will read `state: time: message` now

File: pkg/jobs/job_scheduler.go [hunk 5]
```diff
@@ -254,23 +288,40 @@ func (s *jobScheduler) executeSchedules(
...
+			// So, we reload the schedule, and try to set schedule status.
+			if err := withSavePoint(ctx, txn, func() error {
+				schedule, _, err := s.unmarshalScheduledJob(row, cols)
+				if err != nil {
+					// This really shouldn't happen since we succeeded above.
+					return err
+				}
+				schedule.SetScheduleStatus(fmt.Sprintf("schedule planning error: %s", processErr))
```
Comment (dt) [inline pkg/jobs/job_scheduler.go:312]: I might say `failed to create job: ` or something. "planning" is an internal concept and "schedule" is implied since we're in the schedule.

File: pkg/jobs/job_scheduler.go [hunk 6]
```diff
@@ -135,14 +135,14 @@ func (s *jobScheduler) processSchedule(
 			// In particular, it'd be nice to add more time when repeatedly rescheduling
 			// a job.  It would also be nice not to log each event.
 			schedule.SetNextRun(s.env.Now().Add(recheckRunningAfter))
-			schedule.AddScheduleChangeReason("reschedule: %d running", numRunning)
+			schedule.SetScheduleStatus(fmt.Sprintf("reschedule: %d running", numRunning))
```
Comment (dt) [inline pkg/jobs/job_scheduler.go:138]: I might go with `delayed due to %d already running`

File: pkg/jobs/job_scheduler.go [hunk 7]
```diff
@@ -135,14 +135,14 @@ func (s *jobScheduler) processSchedule(
...
 			stats.rescheduleWait++
 			return schedule.Update(ctx, s.InternalExecutor, txn)
 		case jobspb.ScheduleDetails_SKIP:
 			if err := schedule.ScheduleNextRun(); err != nil {
 				return err
 			}
-			schedule.AddScheduleChangeReason("rescheduled: %d running", numRunning)
+			schedule.SetScheduleStatus(fmt.Sprintf("rescheduled: %d running", numRunning))
```
Comment (dt) [inline pkg/jobs/job_scheduler.go:145]: `skipped due to %d already running`

**Review by dt — APPROVED** [review]

**Review by miretskiy — COMMENTED** [review]
> Reviewed 14 of 14 files at r1, 1 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/53159)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dt and @miretskiy)

___
*[pkg/ccl/backupccl/create_scheduled_backup.go, line 393 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/53159#-MFCvusDfUR7rrbDa3lO-r2-393:-MFGAEjV6SWYSw3HRHz7:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/53fbcdf57f981365ecbdf9da862e272ad3933425/pkg/ccl/backupccl/create_scheduled_backup.go#L393)):*
<details><summary><i>Previously, dt (David Taylor) wrote…</i></summary><blockquote>

I mention below that we shouldn't stick the time in `s` but here's another reason: this will read `state: time: message` now
</blockquote></details>

Done.
___
*[pkg/jobs/job_scheduler.go, line 138 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/53159#-MFCvusDfUR7rrbDa3lQ-r2-138:-MFG2yy7AL8cOftiAM96:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/53fbcdf57f981365ecbdf9da862e272ad3933425/pkg/jobs/job_scheduler.go#L138)):*
<details><summary><i>Previously, dt (David Taylor) wrote…</i></summary><blockquote>

I might go with `delayed due to %d already running`
</blockquote></details>

Done.
___
*[pkg/jobs/job_scheduler.go, line 145 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/53159#-MFCvusDfUR7rrbDa3lQ-r2-145:-MFG2xlr0Xpwzp2DPmPH:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/53fbcdf57f981365ecbdf9da862e272ad3933425/pkg/jobs/job_scheduler.go#L145)):*
<details><summary><i>Previously, dt (David Taylor) wrote…</i></summary><blockquote>

`skipped due to %d already running`
</blockquote></details>

Done.
___
*[pkg/jobs/job_scheduler.go, line 304 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/53159#-MFCvusDfUR7rrbDa3lQ-r2-304:-MFGAGSu9OkW4a2fgKma:b-2i2m2q) ([raw file](https://github.com/cockroachdb/cockroach/blob/53fbcdf57f981365ecbdf9da862e272ad3933425/pkg/jobs/job_scheduler.go#L304)):*
<details><summary><i>Previously, dt (David Taylor) wrote…</i></summary><blockquote>

Eh, now this is why I don't like this ORM pattern -- here we need to load our object to act on it when all what we want is a single-roundtrip `executor.Exec(ctx, "UPDATE %s SET status =...)`. I know everything else about schedule uses its little ORM instead of using SQL so it makes sense to keep doing that here though so not suggesting otherwise, just have an axe to grind. 
</blockquote></details>

Made it a bit less ORM-y.
___
*[pkg/jobs/job_scheduler.go, line 312 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/53159#-MFCvusDfUR7rrbDa3lQ-r2-312:-MFGA9JWA7SMAoXZtAzU:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/53fbcdf57f981365ecbdf9da862e272ad3933425/pkg/jobs/job_scheduler.go#L312)):*
<details><summary><i>Previously, dt (David Taylor) wrote…</i></summary><blockquote>

I might say `failed to create job: ` or something. "planning" is an internal concept and "schedule" is implied since we're in the schedule.
</blockquote></details>

Done.
___
*[pkg/jobs/scheduled_job.go, line 42 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/53159#-MFCvusE9Y1Ll-ZivLBy-r2-42:-MFGgC0-CgZpgkHFOGwr:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/53fbcdf57f981365ecbdf9da862e272ad3933425/pkg/jobs/scheduled_job.go#L42)):*
<details><summary><i>Previously, dt (David Taylor) wrote…</i></summary><blockquote>

Even though we're just doing a string _for now_ I'd put a proto message with a string in it here, just so we have flexibility later and avoid annoying schema change migrations. It doesn't need to change what we'd show since we can pb_to_json()->'message' it. 
</blockquote></details>

Done.
___
*[pkg/jobs/scheduled_job.go, line 226 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/53159#-MFCvusE9Y1Ll-ZivLBy-r2-226:-MFGex9Z764V0Ye-mRGs:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/53fbcdf57f981365ecbdf9da862e272ad3933425/pkg/jobs/scheduled_job.go#L226)):*
<details><summary><i>Previously, dt (David Taylor) wrote…</i></summary><blockquote>

eh, we should either elide the time or, if we want it, save it structured because the UI makes presentation decisions.  So i'd either skip this, or make `schedule_status` a proto with a string field and last updated ts field.
</blockquote></details>

Done.
___
*[pkg/jobs/scheduled_job.go, line 258 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/53159#-MFCvusE9Y1Ll-ZivLBy-r2-258:-MFGg4uRDUP9nzLLM2Rw:b-ixbkaj) ([raw file](https://github.com/cockroachdb/cockroach/blob/53fbcdf57f981365ecbdf9da862e272ad3933425/pkg/jobs/scheduled_job.go#L258)):*
<details><summary><i>Previously, dt (David Taylor) wrote…</i></summary><blockquote>

I'm not convinced we want Unpause setting a status, or pause either. IMO i'd remove `reason` from both of these, and during inc schedule creation just call Pause + SetScheduleStatus directly.
</blockquote></details>

Sorry, just noticed this.  Done.  Also, Unpause() is gone.  It's the same as schedule next run.

**Review by dt — APPROVED** [review]

**Review by dt — APPROVED** [review]

**Review by miretskiy — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/53159)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dt and @miretskiy)

___
*[pkg/ccl/backupccl/schedule_exec.go, line 181 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/53159#-MFGiLu08Z-f7MMAy5pP-r3-181:-MFHfsp0AiaNMxxL0-I7:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/983879fde30bbc8000e74644547a3047bc098a54/pkg/ccl/backupccl/schedule_exec.go#L181)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

good point -- cleared status
</blockquote></details>

Done.
___
*[pkg/sqlmigrations/migrations.go, line 1381 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/53159#-MFCvusE9Y1Ll-ZivLC4-r3-1381:-MFHg--w2SGwv9iXqloC:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/983879fde30bbc8000e74644547a3047bc098a54/pkg/sqlmigrations/migrations.go#L1381)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

yes
</blockquote></details>

Done.
