### PR TITLE
server: catch incomplete available memory detection by gosigar

### LINKED ISSUE #15839: server/cli: ignore the "Available memory" hint from gosigar if it's zero
Found in #15836: on OpenBSD at least gosigar has an implementation from (*Mem).Get() that doesn't fail with an error, but reports 0 available bytes. The computation for CacheSize and SQLMaxMemory derives 0 for both settings as a result.

In general a value of 0 from gosigar should be considered suspicious/invalid and just ignored in favor of the defaults. (perhaps with a warning)

### PR DESCRIPTION
**Pull request by knz**
If gosigar is told by a syscall there is 0 available memory, consider
this information as false even if there was no error.

Fixes #15839.

### CODE REVIEW

File: pkg/server/config.go [hunk 1]
```diff
@@ -237,6 +237,12 @@ func GetTotalMemory() (int64, error) {
 			humanize.IBytes(mem.Total), humanize.Bytes(math.MaxInt64))
 	}
 	totalMem := int64(mem.Total)
+	checkTotal := func(x int64) error {
```
Comment (tschottdorf) [inline pkg/server/config.go]: nit: consider making the signature here `(int64, error)`. That way you can hold up the usual convention (that you return zero when there's an error) more explicitly.

**Review by tbg — APPROVED** [review]

File: pkg/server/config.go (hunk 1 above)
Comment (knz) [inline pkg/server/config.go]: oh good idea. Done.

File: pkg/server/config.go [hunk 2]
```diff
@@ -245,35 +251,34 @@ func GetTotalMemory() (int64, error) {
...
 			if log.V(1) {
 				log.Infof(context.TODO(), "available memory from cgroups is too large and unsupported %s using system memory %s instead",
 					humanize.IBytes(cgAvlMem), humanizeutil.IBytes(totalMem))
 
 			}
-			return totalMem, nil
+			return checkTotal(totalMem)
 		}
-		if cgAvlMem > mem.Total {
+		if mem.Total > 0 && cgAvlMem > mem.Total {
```
Comment (tschottdorf) [inline pkg/server/config.go]: `mem.Total` is (intuitively, not by type) equal to `totalMem`, right? I think it would add to clarity if `mem` went out of scope after `totalMem` was a thing (even at the cost of a type conversion). Just a suggestion, might be misreading this as well.

**Review by tbg — APPROVED** [review]

File: pkg/server/config.go (hunk 2 above)
Comment (knz) [inline pkg/server/config.go]: It makes the code slightly more readable perhaps. I changed it as you suggested.

**Review by tbg — APPROVED** [review]
sorry to have so many nits for such a small change - you're still free to opt out.

File: pkg/server/config.go [hunk 3]
```diff
@@ -245,35 +256,34 @@ func GetTotalMemory() (int64, error) {
...
 			if log.V(1) {
 				log.Infof(context.TODO(), "available memory from cgroups is too large and unsupported %s using system memory %s instead",
 					humanize.IBytes(cgAvlMem), humanizeutil.IBytes(totalMem))
 
 			}
-			return totalMem, nil
+			return checkTotal(totalMem)
 		}
-		if cgAvlMem > mem.Total {
+		if totalMem > 0 && int64(cgAvlMem) > totalMem {
```
Comment (tschottdorf) [inline pkg/server/config.go]: looks like we could overflow `cgAvlMem` here and in l. 284 during the conversion?

Comment (tschottdorf) [inline pkg/server/config.go]: Ah nevermind! You check above.

File: pkg/server/config.go [hunk 4]
```diff
@@ -245,35 +256,34 @@ func GetTotalMemory() (int64, error) {
...
 			if log.V(1) {
 				log.Infof(context.TODO(), "can't parse available memory from cgroups (%s), using system memory %s instead", err,
 					humanizeutil.IBytes(totalMem))
 			}
-			return totalMem, nil
+			return checkTotal(totalMem)
 		}
 		if cgAvlMem > math.MaxInt64 {
 			if log.V(1) {
 				log.Infof(context.TODO(), "available memory from cgroups is too large and unsupported %s using system memory %s instead",
```
Comment (tschottdorf) [inline pkg/server/config.go]: this sentence would look weird because cgAvlMem pops up randomly.

**Comment by tamird** [comment]
Has this been reported upstream?

On May 10, 2017 8:15 AM, "kena" <notifications@github.com> wrote:

@knz <https://github.com/knz> requested your review on:
cockroachdb/cockroach#15841
<https://github.com/cockroachdb/cockroach/pull/15841> server: catch
incomplete available memory detection by gosigar.

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/cockroachdb/cockroach/pull/15841#event-1076303427>, or mute
the thread

File: pkg/server/config.go (hunk 4 above)
Comment (knz) [inline pkg/server/config.go]: What do you mean "looks weird"?

**Comment by knz** [comment]
@tamird yes https://github.com/elastic/gosigar/issues/72

**Comment by benesch** [comment]
FWIW I wasn't encountering this on my OpenBSD VM. I'm going to do some more digging when I have some spare time. :+1: in the meantime.

**Comment by knz** [comment]
@benesch perhaps the syscall(s) used in gosigar is sensitive to some configuration, which the gosigar openbsd support's author didn't take into account. If I were you I'd make an inventory of the syscalls in `sigar_openbsd.go` and read the man pages thoroughly.

File: pkg/server/config.go (hunk 4 above)
Comment (tschottdorf) [inline pkg/server/config.go]: the first `%s` is outside of the flow of the sentence. It would look better in parentheses, or moved up to read "available memory %s from cgroups is too large, ...". Still only a nit.

Comment (knz) [inline pkg/server/config.go]: Oh now I understand. Thanks for clarifying. Done.

**Comment by tamird** [comment]
LGTM but we should like to the upstream issue since we don't want to keep this extra layer of paranoia on top of gosigar forever.

Thanks for fixing! Please consider nominating for 1.0.1.

---

Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 5 unresolved discussions, all commit checks successful.

---

*[pkg/server/config.go, line 284 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/15841#-Kjp7cePpsp2-jBex_mx:-Kjp7cePpsp2-jBex_my:bp0g67h) ([raw file](https://github.com/cockroachdb/cockroach/blob/20826c3b918f8dbe53810eee8fe43a483ee13647/pkg/server/config.go#L284)):*
> ```Go
> 			return checkTotal(totalMem)
> 		}
> 		totalMem = int64(cgAvlMem)
> ```

why not `return checkTotal(..)` in keeping with convention elsewhere?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15841#-:-Kjp7ilBEP1iOjLGFfKm:b-rl6taz)*

**Comment by knz** [comment]
I have linked the upstream issue. TFYR!

---

Review status: all files reviewed at latest revision, 5 unresolved discussions, all commit checks successful.

---

*[pkg/server/config.go, line 284 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/15841#-Kjp7cePpsp2-jBex_mx:-KjxcWOIybj67DSUxXgZ:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/20826c3b918f8dbe53810eee8fe43a483ee13647/pkg/server/config.go#L284)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

why not `return checkTotal(..)` in keeping with convention elsewhere?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15841#-:-KjxcXbux3sIgBkkt1sl:bj4lrsm)*

**Comment by tamird** [comment]
Reviewed 1 of 1 files at r5.
Review status: all files reviewed at latest revision, 4 unresolved discussions, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15841)*
