### PR TITLE
storageccl: make the WriteBatch command idempotent

### LINKED ISSUE #13866: ccl/sqlccl: TestBackupRestoreBank failed under stress
SHA: https://github.com/cockroachdb/cockroach/commits/7819483d60fd6461f9e9f704c4e6a8df397fbb5a

Parameters:
```
COCKROACH_PROPOSER_EVALUATED_KV=true
TAGS=
GOFLAGS=-race
```

Stress build found a failed test: https://teamcity.cockroachdb.com/viewLog.html?buildId=166198&tab=buildLog

```
W170301 08:32:00.792666 12174 server/status/runtime.go:116  Could not parse build timestamp: parsing time "" as "2006/01/02 15:04:05": cannot parse "" as "2006"
I170301 08:32:00.803626 12174 server/config.go:482  1 storage engine initialized
I170301 08:32:00.804672 12174 server/node.go:443  [n?] store [n0,s0] not bootstrapped
I170301 08:32:00.825347 12174 server/node.go:372  [n?] **** cluster 40e88bcf-6d7d-43f7-9f4a-1037bda13d2b has been created
I170301 08:32:00.825453 12174 server/node.go:373  [n?] **** add additional nodes by specifying --join=127.0.0.1:38726
I170301 08:32:00.830511 12174 storage/store.go:1274  [n1] [n1,s1]: failed initial metrics computation: [n1,s1]: system config not yet available
I170301 08:32:00.830630 12174 server/node.go:456  [n1] initialized store [n1,s1]: {Capacity:536870912 Available:536870912 RangeCount:1 LeaseCount:0}
I170301 08:32:00.830780 12174 server/node.go:341  [n1] node ID 1 initialized
I170301 08:32:00.830975 12174 gossip/gossip.go:293  [n1] NodeDescriptor set to node_id:1 address:<network_field:"tcp" address_field:"127.0.0.1:38726" > attrs:<> locality:<> 
I170301 08:32:00.831689 12174 storage/stores.go:296  [n1] read 0 node addresses from persistent storage
I170301 08:32:00.831835 12174 server/node.go:605  [n1] connecting to gossip network to verify cluster ID...
I170301 08:32:00.834135 12174 server/node.go:629  [n1] node connected via gossip and verified as part of cluster "40e88bcf-6d7d-43f7-9f4a-1037bda13d2b"
I170301 08:32:00.840527 12174 server/node.go:391  [n1] node=1: started with [[]=] engine(s) and attributes []
I170301 08:32:00.866355 12174 sql/executor.go:337  [n1] creating distSQLPlanner with address {tcp 127.0.0.1:38726}
I170301 08:32:00.876906 12294 sql/event_log.go:95  [n1] Event: "node_join", target: 1, info: {Descriptor:{NodeID:1 Address:{NetworkField:tcp AddressField:127.0.0.1:38726} Attrs: Locality:} ClusterID:40e88bcf-6d7d-43f7-9f4a-1037bda13d2b StartedAt:1488357120840191979 LastUp:1488357120840191979}
I170301 08:32:00.877395 12284 storage/split_queue.go:98  [split,n1,s1,r1/1:/M{in-ax},@c42393e380] splitting at key /Table/0/0
I170301 08:32:00.903218 12284 storage/replica_command.go:2456  [split,n1,s1,r1/1:/M{in-ax},@c42393e380] initiating a split of this range at key /Table/0 [r2]
I170301 08:32:00.960317 12284 storage/split_queue.go:98  [split,n1,s1,r2/1:/{Table/0-Max},@c4232ace00] splitting at key /Table/11/0
I170301 08:32:00.960533 12284 storage/replica_command.go:2456  [split,n1,s1,r2/1:/{Table/0-Max},@c4232ace00] initiating a split of this range at key /Table/11 [r3]
I170301 08:32:00.979816 12174 server/server.go:651  [n1] starting https server at 127.0.0.1:48645
I170301 08:32:00.980071 12174 server/server.go:652  [n1] starting grpc/postgres server at 127.0.0.1:38726
I170301 08:32:00.980118 12174 server/server.go:653  [n1] advertising CockroachDB node at 127.0.0.1:38726
E170301 08:32:01.006345 12285 storage/queue.go:628  [replicate,n1,s1,r1/1:/{Min-Table/0},@c42393e380] range requires a replication change, but lacks a quorum of live replicas (0/1)
E170301 08:32:01.041926 12285 storage/queue.go:628  [replicate,n1,s1,r1/1:/{Min-Table/0},@c42393e380] range requires a replication change, but lacks a quorum of live replicas (0/1)
I170301 08:32:01.085576 12284 storage/split_queue.go:98  [split,n1,s1,r3/1:/{Table/11-Max},@c42181aa80] splitting at key /Table/12/0
I170301 08:32:01.085826 12284 storage/replica_command.go:2456  [split,n1,s1,r3/1:/{Table/11-Max},@c42181aa80] initiating a split of this range at key /Table/12 [r4]
I170301 08:32:01.257958 12284 storage/split_queue.go:98  [split,n1,s1,r4/1:/{Table/12-Max},@c423a98e00] splitting at key /Table/13/0
I170301 08:32:01.260985 12284 storage/replica_command.go:2456  [split,n1,s1,r4/1:/{Table/12-Max},@c423a98e00] initiating a split of this range at key /Table/13 [r5]
I170301 08:32:01.272997 12174 sql/event_log.go:95  [n1] Event: "alter_table", target: 12, info: {TableName:eventlog Statement:ALTER TABLE system.eventlog ALTER COLUMN uniqueID SET DEFAULT uuid_v4() User:node MutationID:0 CascadeDroppedViews:[]}
I170301 08:32:01.357237 12284 storage/split_queue.go:98  [split,n1,s1,r5/1:/{Table/13-Max},@c42042a700] splitting at key /Table/14/0
I170301 08:32:01.357505 12284 storage/replica_command.go:2456  [split,n1,s1,r5/1:/{Table/13-Max},@c42042a700] initiating a split of this range at key /Table/14 [r6]
I170301 08:32:01.467289 12174 server/server.go:779  [n1] done ensuring all necessary migrations have run
I170301 08:32:01.467409 12174 server/server.go:781  [n1] serving sql connections
W170301 08:32:01.513951 12174 gossip/gossip.go:1178  [n?] no incoming or outgoing connections
W170301 08:32:01.519674 12174 server/status/runtime.go:116  Could not parse build timestamp: parsing time "" as "2006/01/02 15:04:05": cannot parse "" as "2006"
I170301 08:32:01.547103 12174 server/config.go:482  1 storage engine initialized
I170301 08:32:01.550351 12174 server/node.go:443  [n?] store [n0,s0] not bootstrapped
I170301 08:32:01.550459 12174 storage/stores.go:296  [n?] read 0 node addresses from persistent storage
I170301 08:32:01.550598 12174 server/node.go:605  [n?] connecting to gossip network to verify cluster ID...
I170301 08:32:01.614437 12476 gossip/server.go:214  [n1] received initial cluster-verification connection from {tcp 127.0.0.1:51574}
I170301 08:32:01.615299 12431 gossip/client.go:131  [n?] started gossip client to 127.0.0.1:38726
I170301 08:32:01.617468 12461 storage/stores.go:312  [n?] wrote 1 node addresses to persistent storage
I170301 08:32:01.619606 12174 server/node.go:629  [n?] node connected via gossip and verified as part of cluster "40e88bcf-6d7d-43f7-9f4a-1037bda13d2b"
I170301 08:32:01.626041 12174 kv/dist_sender.go:368  [n?] unable to determine this node's attributes for replica selection; node is most likely bootstrapping
I170301 08:32:01.630033 12174 server/node.go:334  [n?] new node allocated ID 2
I170301 08:32:01.630366 12174 gossip/gossip.go:293  [n2] NodeDescriptor set to node_id:2 address:<network_field:"tcp" address_field:"127.0.0.1:51574" > attrs:<> locality:<> 
I170301 08:32:01.631169 12174 server/node.go:391  [n2] node=2: started with [[]=] engine(s) and attributes []
I170301 08:32:01.632193 12174 sql/executor.go:337  [n2] creating distSQLPlanner with address {tcp 127.0.0.1:51574}
I170301 08:32:01.676949 12444 storage/stores.go:312  [n1] wrote 1 node addresses to persistent storage
I170301 08:32:01.715270 12174 server/server.go:651  [n2] starting https server at 127.0.0.1:37290
I170301 08:32:01.717936 12174 server/server.go:652  [n2] starting grpc/postgres server at 127.0.0.1:51574
I170301 08:32:01.717984 12174 server/server.go:653  [n2] advertising CockroachDB node at 127.0.0.1:51574
I170301 08:32:01.748903 12174 server/server.go:779  [n2] done ensuring all necessary migrations have run
I170301 08:32:01.758192 12174 server/server.go:781  [n2] serving sql connections
I170301 08:32:01.761689 12481 sql/event_log.go:95  [n2] Event: "node_join", target: 2, info: {Descriptor:{NodeID:2 Address:{NetworkField:tcp AddressField:127.0.0.1:51574} Attrs: Locality:} ClusterID:40e88bcf-6d7d-43f7-9f4a-1037bda13d2b StartedAt:1488357121630823855 LastUp:1488357121630823855}
W170301 08:32:01.855186 12174 gossip/gossip.go:1178  [n?] no incoming or outgoing connections
W170301 08:32:01.900999 12174 server/status/runtime.go:116  Could not parse build timestamp: parsing time "" as "2006/01/02 15:04:05": cannot parse "" as "2006"
I170301 08:32:01.913236 12174 server/config.go:482  1 storage engine initialized
I170301 08:32:01.914772 12174 server/node.go:443  [n?] store [n0,s0] not bootstrapped
I170301 08:32:01.914880 12174 storage/stores.go:296  [n?] read 0 node addresses from persistent storage
I170301 08:32:01.914974 12174 server/node.go:605  [n?] connecting to gossip network to verify cluster ID...
I170301 08:32:02.014425 12478 server/node.go:586  [n2] bootstrapped store [n2,s2]
I170301 08:32:02.036956 12333 storage/replica_raftstorage.go:414  [replicate,n1,s1,r1/1:/{Min-Table/0},@c42393e380] generated preemptive snapshot fe07dd97 at index 45
I170301 08:32:02.129356 12333 storage/store.go:3295  [replicate,n1,s1,r1/1:/{Min-Table/0},@c42393e380] streamed snapshot: kv pairs: 392, log entries: 35, 14ms
I170301 08:32:02.134136 12644 storage/replica_raftstorage.go:596  [n2,s2,r1/?:{-},@c420842380] applying preemptive snapshot at index 45 (id=fe07dd97, encoded size=204104, 1 rocksdb batches, 35 log entries)
I170301 08:32:02.146259 12346 gossip/client.go:131  [n?] started gossip client to 127.0.0.1:38726
I170301 08:32:02.147732 12605 gossip/server.go:214  [n1] received initial cluster-verification connection from {tcp 127.0.0.1:33160}
I170301 08:32:02.150996 12606 storage/stores.go:312  [n?] wrote 1 node addresses to persistent storage
I170301 08:32:02.151846 12608 storage/stores.go:312  [n?] wrote 2 node addresses to persistent storage
I170301 08:32:02.152066 12174 server/node.go:629  [n?] node connected via gossip and verified as part of cluster "40e88bcf-6d7d-43f7-9f4a-1037bda13d2b"
I170301 08:32:02.157967 12174 kv/dist_sender.go:368  [n?] unable to determine this node's attributes for replica selection; node is most likely bootstrapping
I170301 08:32:02.162412 12174 server/node.go:334  [n?] new node allocated ID 3
I170301 08:32:02.162757 12174 gossip/gossip.go:293  [n3] NodeDescriptor set to node_id:3 address:<network_field:"tcp" address_field:"127.0.0.1:33160" > attrs:<> locality:<> 
I170301 08:32:02.166343 12540 storage/stores.go:312  [n1] wrote 2 node addresses to persistent storage
I170301 08:32:02.167118 12644 storage/replica_raftstorage.go:604  [n2,s2,r1/?:/{Min-Table/0},@c420842380] applied preemptive snapshot in 33ms [clear=0ms batch=0ms entries=4ms commit=1ms]
I170301 08:32:02.167767 12527 storage/stores.go:312  [n2] wrote 2 node addresses to persistent storage
I170301 08:32:02.169277 12174 server/node.go:391  [n3] node=3: started with [[]=] engine(s) and attributes []
I170301 08:32:02.169818 12174 sql/executor.go:337  [n3] creating distSQLPlanner with address {tcp 127.0.0.1:33160}
I170301 08:32:02.175932 12333 storage/replica_command.go:3312  [replicate,n1,s1,r1/1:/{Min-Table/0},@c42393e380] change replicas (remove {2 2 2}): read existing descriptor range_id:1 start_key:"" end_key:"\210" replicas:<node_id:1 store_id:1 replica_id:1 > next_replica_id:2 
I170301 08:32:02.197061 12174 server/server.go:651  [n3] starting https server at 127.0.0.1:60422
I170301 08:32:02.197144 12174 server/server.go:652  [n3] starting grpc/postgres server at 127.0.0.1:33160
I170301 08:32:02.197183 12174 server/server.go:653  [n3] advertising CockroachDB node at 127.0.0.1:33160
I170301 08:32:02.222692 12174 server/server.go:779  [n3] done ensuring all necessary migrations have run
I170301 08:32:02.225027 12174 server/server.go:781  [n3] serving sql connections
I170301 08:32:02.236396 12669 storage/replica.go:2510  [n1,s1,r1/1:/{Min-Table/0},@c42393e380] proposing ADD_REPLICA {NodeID:2 StoreID:2 ReplicaID:2}: [{NodeID:1 StoreID:1 ReplicaID:1} {NodeID:2 StoreID:2 ReplicaID:2}]
I170301 08:32:02.244425 12648 server/node.go:586  [n3] bootstrapped store [n3,s3]
I170301 08:32:02.259063 12651 sql/event_log.go:95  [n3] Event: "node_join", target: 3, info: {Descriptor:{NodeID:3 Address:{NetworkField:tcp AddressField:127.0.0.1:33160} Attrs: Locality:} ClusterID:40e88bcf-6d7d-43f7-9f4a-1037bda13d2b StartedAt:1488357122163230478 LastUp:1488357122163230478}
I170301 08:32:02.290665 12333 storage/replica_raftstorage.go:414  [replicate,n1,s1,r3/1:/Table/1{1-2},@c42181aa80] generated preemptive snapshot aabc38ff at index 16
I170301 08:32:02.296811 12789 storage/raft_transport.go:436  [n2] raft transport stream to node 1 established
I170301 08:32:02.442417 12820 storage/replica_raftstorage.go:596  [n3,s3,r3/?:{-},@c4201af180] applying preemptive snapshot at index 16 (id=aabc38ff, encoded size=7313, 1 rocksdb batches, 6 log entries)
I170301 08:32:02.443507 12820 storage/replica_raftstorage.go:604  [n3,s3,r3/?:/Table/1{1-2},@c4201af180] applied preemptive snapshot in 1ms [clear=0ms batch=0ms entries=0ms commit=0ms]
I170301 08:32:02.449960 12333 storage/store.go:3295  [replicate,n1,s1,r3/1:/Table/1{1-2},@c42181aa80] streamed snapshot: kv pairs: 10, log entries: 6, 9ms
I170301 08:32:02.463252 12333 storage/replica_command.go:3312  [replicate,n1,s1,r3/1:/Table/1{1-2},@c42181aa80] change replicas (remove {3 3 2}): read existing descriptor range_id:3 start_key:"\223" end_key:"\224" replicas:<node_id:1 store_id:1 replica_id:1 > next_replica_id:2 
I170301 08:32:03.258424 12700 storage/replica.go:2510  [n1,s1,r3/1:/Table/1{1-2},@c42181aa80] proposing ADD_REPLICA {NodeID:3 StoreID:3 ReplicaID:2}: [{NodeID:1 StoreID:1 ReplicaID:1} {NodeID:3 StoreID:3 ReplicaID:2}]
I170301 08:32:03.268094 12285 storage/replica_raftstorage.go:414  [replicate,n1,s1,r6/1:/{Table/14-Max},@c420296380] generated preemptive snapshot effb7b73 at index 13
I170301 08:32:03.271618 12285 storage/store.go:3295  [replicate,n1,s1,r6/1:/{Table/14-Max},@c420296380] streamed snapshot: kv pairs: 10, log entries: 3, 3ms
I170301 08:32:03.273771 12842 storage/replica_raftstorage.go:596  [n2,s2,r6/?:{-},@c421c74000] applying preemptive snapshot at index 13 (id=effb7b73, encoded size=1716, 1 rocksdb batches, 3 log entries)
I170301 08:32:03.274682 12842 storage/replica_raftstorage.go:604  [n2,s2,r6/?:/{Table/14-Max},@c421c74000] applied preemptive snapshot in 1ms [clear=0ms batch=0ms entries=0ms commit=0ms]
I170301 08:32:03.279545 12285 storage/replica_command.go:3312  [replicate,n1,s1,r6/1:/{Table/14-Max},@c420296380] change replicas (remove {2 2 2}): read existing descriptor range_id:6 start_key:"\226" end_key:"\377\377" replicas:<node_id:1 store_id:1 replica_id:1 > next_replica_id:2 
I170301 08:32:03.327695 12847 storage/raft_transport.go:436  [n3] raft transport stream to node 1 established
I170301 08:32:03.357349 12898 storage/replica.go:2510  [n1,s1,r6/1:/{Table/14-Max},@c420296380] proposing ADD_REPLICA {NodeID:2 StoreID:2 ReplicaID:2}: [{NodeID:1 StoreID:1 ReplicaID:1} {NodeID:2 StoreID:2 ReplicaID:2}]
I170301 08:32:03.365982 12333 storage/replica_raftstorage.go:414  [replicate,n1,s1,r6/1:/{Table/14-Max},@c420296380] generated preemptive snapshot 1708d927 at index 15
I170301 08:32:03.383572 12333 storage/store.go:3295  [replicate,n1,s1,r6/1:/{Table/14-Max},@c420296380] streamed snapshot: kv pairs: 12, log entries: 5, 9ms
I170301 08:32:03.390132 12890 storage/replica_raftstorage.go:596  [n3,s3,r6/?:{-},@c42181b180] applying preemptive snapshot at index 15 (id=1708d927, encoded size=4384, 1 rocksdb batches, 5 log entries)
I170301 08:32:03.391984 12890 storage/replica_raftstorage.go:604  [n3,s3,r6/?:/{Table/14-Max},@c42181b180] applied preemptive snapshot in 1ms [clear=0ms batch=0ms entries=0ms commit=0ms]
I170301 08:32:03.402625 12333 storage/replica_command.go:3312  [replicate,n1,s1,r6/1:/{Table/14-Max},@c420296380] change replicas (remove {3 3 3}): read existing descriptor range_id:6 start_key:"\226" end_key:"\377\377" replicas:<node_id:1 store_id:1 replica_id:1 > replicas:<node_id:2 store_id:2 replica_id:2 > next_replica_id:3 
I170301 08:32:03.444786 12867 storage/replica.go:2510  [n1,s1,r6/1:/{Table/14-Max},@c420296380] proposing ADD_REPLICA {NodeID:3 StoreID:3 ReplicaID:3}: [{NodeID:1 StoreID:1 ReplicaID:1} {NodeID:2 StoreID:2 ReplicaID:2} {NodeID:3 StoreID:3 ReplicaID:3}]
I170301 08:32:03.453837 12333 storage/replica_raftstorage.go:414  [replicate,n1,s1,r2/1:/Table/{0-11},@c4232ace00] generated preemptive snapshot f06f29fb at index 26
I170301 08:32:03.465518 12333 storage/store.go:3295  [replicate,n1,s1,r2/1:/Table/{0-11},@c4232ace00] streamed snapshot: kv pairs: 34, log entries: 16, 11ms
I170301 08:32:03.466705 12931 storage/replica_raftstorage.go:596  [n3,s3,r2/?:{-},@c421c74a80] applying preemptive snapshot at index 26 (id=f06f29fb, encoded size=23875, 1 rocksdb batches, 16 log entries)
I170301 08:32:03.468781 12931 storage/replica_raftstorage.go:604  [n3,s3,r2/?:/Table/{0-11},@c421c74a80] applied preemptive snapshot in 2ms [clear=0ms batch=0ms entries=1ms commit=0ms]
I170301 08:32:03.486158 12333 storage/replica_command.go:3312  [replicate,n1,s1,r2/1:/Table/{0-11},@c4232ace00] change replicas (remove {3 3 2}): read existing descriptor range_id:2 start_key:"\210" end_key:"\223" replicas:<node_id:1 store_id:1 replica_id:1 > next_replica_id:2 
I170301 08:32:03.524856 12934 storage/replica.go:2510  [n1,s1,r2/1:/Table/{0-11},@c4232ace00] proposing ADD_REPLICA {NodeID:3 StoreID:3 ReplicaID:2}: [{NodeID:1 StoreID:1 ReplicaID:1} {NodeID:3 StoreID:3 ReplicaID:2}]
I170301 08:32:03.528502 12333 storage/replica_raftstorage.go:414  [replicate,n1,s1,r5/1:/Table/1{3-4},@c42042a700] generated preemptive snapshot 0b1348a9 at index 27
I170301 08:32:03.534026 12333 storage/store.go:3295  [replicate,n1,s1,r5/1:/Table/1{3-4},@c42042a700] streamed snapshot: kv pairs: 71, log entries: 17, 4ms
I170301 08:32:03.542264 12946 storage/replica_raftstorage.go:596  [n2,s2,r5/?:{-},@c42080dc00] applying preemptive snapshot at index 27 (id=0b1348a9, encoded size=28784, 1 rocksdb batches, 17 log entries)
I170301 08:32:03.543828 12946 storage/replica_raftstorage.go:604  [n2,s2,r5/?:/Table/1{3-4},@c42080dc00] applied preemptive snapshot in 1ms [clear=0ms batch=0ms entries=1ms commit=0ms]
I170301 08:32:03.548228 12333 storage/replica_command.go:3312  [replicate,n1,s1,r5/1:/Table/1{3-4},@c42042a700] change replicas (remove {2 2 2}): read existing descriptor range_id:5 start_key:"\225" end_key:"\226" replicas:<node_id:1 store_id:1 replica_id:1 > next_replica_id:2 
I170301 08:32:03.582073 12896 storage/replica.go:2510  [n1,s1,r5/1:/Table/1{3-4},@c42042a700] proposing ADD_REPLICA {NodeID:2 StoreID:2 ReplicaID:2}: [{NodeID:1 StoreID:1 ReplicaID:1} {NodeID:2 StoreID:2 ReplicaID:2}]
I170301 08:32:03.587735 12333 storage/replica_raftstorage.go:414  [replicate,n1,s1,r4/1:/Table/1{2-3},@c423a98e00] generated preemptive snapshot 3ac20d80 at index 24
I170301 08:32:03.620084 12333 storage/store.go:3295  [replicate,n1,s1,r4/1:/Table/1{2-3},@c423a98e00] streamed snapshot: kv pairs: 31, log entries: 14, 27ms
I170301 08:32:03.621759 12964 storage/replica_raftstorage.go:596  [n2,s2,r4/?:{-},@c423a99180] applying preemptive snapshot at index 24 (id=3ac20d80, encoded size=21331, 1 rocksdb batches, 14 log entries)
I170301 08:32:03.623115 12964 storage/replica_raftstorage.go:604  [n2,s2,r4/?:/Table/1{2-3},@c423a99180] applied preemptive snapshot in 1ms [clear=0ms batch=0ms entries=0ms commit=0ms]
I170301 08:32:03.631145 12333 storage/replica_command.go:3312  [replicate,n1,s1,r4/1:/Table/1{2-3},@c423a98e00] change replicas (remove {2 2 2}): read existing descriptor range_id:4 start_key:"\224" end_key:"\225" replicas:<node_id:1 store_id:1 replica_id:1 > next_replica_id:2 
I170301 08:32:03.673276 13001 storage/replica.go:2510  [n1,s1,r4/1:/Table/1{2-3},@c423a98e00] proposing ADD_REPLICA {NodeID:2 StoreID:2 ReplicaID:2}: [{NodeID:1 StoreID:1 ReplicaID:1} {NodeID:2 StoreID:2 ReplicaID:2}]
I170301 08:32:03.677249 12333 storage/queue.go:693  [n1,replicate] purgatory is now empty
I170301 08:32:03.684363 12285 storage/replica_raftstorage.go:414  [replicate,n1,s1,r2/1:/Table/{0-11},@c4232ace00] generated preemptive snapshot 49a81000 at index 29
I170301 08:32:03.687329 12285 storage/store.go:3295  [replicate,n1,s1,r2/1:/Table/{0-11},@c4232ace00] streamed snapshot: kv pairs: 35, log entries: 19, 2ms
I170301 08:32:03.689903 12983 storage/replica_raftstorage.go:596  [n2,s2,r2/?:{-},@c42259c700] applying preemptive snapshot at index 29 (id=49a81000, encoded size=26843, 1 rocksdb batches, 19 log entries)
I170301 08:32:03.696929 12983 storage/replica_raftstorage.go:604  [n2,s2,r2/?:/Table/{0-11},@c42259c700] applied preemptive snapshot in 7ms [clear=0ms batch=5ms entries=1ms commit=0ms]
I170301 08:32:03.703749 12285 storage/replica_command.go:3312  [replicate,n1,s1,r2/1:/Table/{0-11},@c4232ace00] change replicas (remove {2 2 3}): read existing descriptor range_id:2 start_key:"\210" end_key:"\223" replicas:<node_id:1 store_id:1 replica_id:1 > replicas:<node_id:3 store_id:3 replica_id:2 > next_replica_id:3 
I170301 08:32:03.734484 13007 storage/replica.go:2510  [n1,s1,r2/1:/Table/{0-11},@c4232ace00] proposing ADD_REPLICA {NodeID:2 StoreID:2 ReplicaID:3}: [{NodeID:1 StoreID:1 ReplicaID:1} {NodeID:3 StoreID:3 ReplicaID:2} {NodeID:2 StoreID:2 ReplicaID:3}]
I170301 08:32:03.746971 12285 storage/replica_raftstorage.go:414  [replicate,n1,s1,r5/1:/Table/1{3-4},@c42042a700] generated preemptive snapshot ab7da3da at index 35
I170301 08:32:03.756994 12285 storage/store.go:3295  [replicate,n1,s1,r5/1:/Table/1{3-4},@c42042a700] streamed snapshot: kv pairs: 87, log entries: 25, 3ms
I170301 08:32:03.760873 13043 storage/replica_raftstorage.go:596  [n3,s3,r5/?:{-},@c4238ea380] applying preemptive snapshot at index 35 (id=ab7da3da, encoded size=41646, 1 rocksdb batches, 25 log entries)
I170301 08:32:03.764574 13043 storage/replica_raftstorage.go:604  [n3,s3,r5/?:/Table/1{3-4},@c4238ea380] applied preemptive snapshot in 3ms [clear=0ms batch=0ms entries=1ms commit=0ms]
I170301 08:32:03.769904 12285 storage/replica_command.go:3312  [replicate,n1,s1,r5/1:/Table/1{3-4},@c42042a700] change replicas (remove {3 3 3}): read existing descriptor range_id:5 start_key:"\225" end_key:"\226" replicas:<node_id:1 store_id:1 replica_id:1 > replicas:<node_id:2 store_id:2 replica_id:2 > next_replica_id:3 
I170301 08:32:03.806838 13033 storage/replica.go:2510  [n1,s1,r5/1:/Table/1{3-4},@c42042a700] proposing ADD_REPLICA {NodeID:3 StoreID:3 ReplicaID:3}: [{NodeID:1 StoreID:1 ReplicaID:1} {NodeID:2 StoreID:2 ReplicaID:2} {NodeID:3 StoreID:3 ReplicaID:3}]
I170301 08:32:03.814438 12285 storage/replica_raftstorage.go:414  [replicate,n1,s1,r4/1:/Table/1{2-3},@c423a98e00] generated preemptive snapshot 25097cfe at index 27
I170301 08:32:03.821134 12285 storage/store.go:3295  [replicate,n1,s1,r4/1:/Table/1{2-3},@c423a98e00] streamed snapshot: kv pairs: 32, log entries: 17, 6ms
I170301 08:32:03.822639 13036 storage/replica_raftstorage.go:596  [n3,s3,r4/?:{-},@c420843880] applying preemptive snapshot at index 27 (id=25097cfe, encoded size=24299, 1 rocksdb batches, 17 log entries)
I170301 08:32:03.824492 13036 storage/replica_raftstorage.go:604  [n3,s3,r4/?:/Table/1{2-3},@c420843880] applied preemptive snapshot in 2ms [clear=0ms batch=0ms entries=1ms commit=0ms]
I170301 08:32:03.828594 12285 storage/replica_command.go:3312  [replicate,n1,s1,r4/1:/Table/1{2-3},@c423a98e00] change replicas (remove {3 3 3}): read existing descriptor range_id:4 start_key:"\224" end_key:"\225" replicas:<node_id:1 store_id:1 replica_id:1 > replicas:<node_id:2 store_id:2 replica_id:2 > next_replica_id:3 
I170301 08:32:03.873145 13064 storage/replica.go:2510  [n1,s1,r4/1:/Table/1{2-3},@c423a98e00] proposing ADD_REPLICA {NodeID:3 StoreID:3 ReplicaID:3}: [{NodeID:1 StoreID:1 ReplicaID:1} {NodeID:2 StoreID:2 ReplicaID:2} {NodeID:3 StoreID:3 ReplicaID:3}]
I170301 08:32:03.891034 12285 storage/replica_raftstorage.go:414  [replicate,n1,s1,r1/1:/{Min-Table/0},@c42393e380] generated preemptive snapshot 50fa11bf at index 74
I170301 08:32:03.920843 12285 storage/store.go:3295  [replicate,n1,s1,r1/1:/{Min-Table/0},@c42393e380] streamed snapshot: kv pairs: 840, log entries: 64, 29ms
I170301 08:32:03.925025 12987 storage/replica_raftstorage.go:596  [n3,s3,r1/?:{-},@c42433a000] applying preemptive snapshot at index 74 (id=50fa11bf, encoded size=446025, 1 rocksdb batches, 64 log entries)
I170301 08:32:03.934307 12987 storage/replica_raftstorage.go:604  [n3,s3,r1/?:/{Min-Table/0},@c42433a000] applied preemptive snapshot in 9ms [clear=0ms batch=0ms entries=6ms commit=2ms]
I170301 08:32:03.939093 12285 storage/replica_command.go:3312  [replicate,n1,s1,r1/1:/{Min-Table/0},@c42393e380] change replicas (remove {3 3 3}): read existing descriptor range_id:1 start_key:"" end_key:"\210" replicas:<node_id:1 store_id:1 replica_id:1 > replicas:<node_id:2 store_id:2 replica_id:2 > next_replica_id:3 
I170301 08:32:03.959673 13067 storage/replica.go:2510  [n1,s1,r1/1:/{Min-Table/0},@c42393e380] proposing ADD_REPLICA {NodeID:3 StoreID:3 ReplicaID:3}: [{NodeID:1 StoreID:1 ReplicaID:1} {NodeID:2 StoreID:2 ReplicaID:2} {NodeID:3 StoreID:3 ReplicaID:3}]
I170301 08:32:03.966724 12285 storage/replica_raftstorage.go:414  [replicate,n1,s1,r3/1:/Table/1{1-2},@c42181aa80] generated preemptive snapshot 5d7ed248 at index 21
I170301 08:32:03.975360 12285 storage/store.go:3295  [replicate,n1,s1,r3/1:/Table/1{1-2},@c42181aa80] streamed snapshot: kv pairs: 12, log entries: 11, 3ms
I170301 08:32:03.976540 12941 storage/replica_raftstorage.go:596  [n2,s2,r3/?:{-},@c421c8e380] applying preemptive snapshot at index 21 (id=5d7ed248, encoded size=11491, 1 rocksdb batches, 11 log entries)
I170301 08:32:03.977786 12941 storage/replica_raftstorage.go:604  [n2,s2,r3/?:/Table/1{1-2},@c421c8e380] applied preemptive snapshot in 1ms [clear=0ms batch=0ms entries=0ms commit=0ms]
I170301 08:32:03.981787 12285 storage/replica_command.go:3312  [replicate,n1,s1,r3/1:/Table/1{1-2},@c42181aa80] change replicas (remove {2 2 3}): read existing descriptor range_id:3 start_key:"\223" end_key:"\224" replicas:<node_id:1 store_id:1 replica_id:1 > replicas:<node_id:3 store_id:3 replica_id:2 > next_replica_id:3 
I170301 08:32:04.022238 13041 storage/replica.go:2510  [n1,s1,r3/1:/Table/1{1-2},@c42181aa80] proposing ADD_REPLICA {NodeID:2 StoreID:2 ReplicaID:3}: [{NodeID:1 StoreID:1 ReplicaID:1} {NodeID:3 StoreID:3 ReplicaID:2} {NodeID:2 StoreID:2 ReplicaID:3}]
I170301 08:32:04.437481 13056 sql/event_log.go:95  [client=127.0.0.1:38966,user=root,n1] Event: "create_database", target: 50, info: {DatabaseName:bench Statement:CREATE DATABASE bench User:root}
I170301 08:32:04.438277 12284 storage/split_queue.go:98  [split,n1,s1,r6/1:/{Table/14-Max},@c420296380] splitting at key /Table/50/0
I170301 08:32:04.438478 12284 storage/replica_command.go:2456  [split,n1,s1,r6/1:/{Table/14-Max},@c420296380] initiating a split of this range at key /Table/50 [r7]
I170301 08:32:04.551467 13056 sql/event_log.go:95  [client=127.0.0.1:38966,user=root,n1] Event: "create_table", target: 51, info: {TableName:bench.bank Statement:CREATE TABLE bench.bank (id INT PRIMARY KEY, balance INT, payload STRING, FAMILY (id, balance, payload)) User:root}
I170301 08:32:04.560652 12284 storage/split_queue.go:98  [split,n1,s1,r7/1:/{Table/50-Max},@c42159a000] splitting at key /Table/51/0
I170301 08:32:04.560852 12284 storage/replica_command.go:2456  [split,n1,s1,r7/1:/{Table/50-Max},@c42159a000] initiating a split of this range at key /Table/51 [r8]
I170301 08:32:04.691596 13148 storage/replica_command.go:2456  [n1,s1,r7/1:/{Table/50-Max},@c42159a000] initiating a split of this range at key /Table/51/1/1 [r9]
I170301 08:32:04.822010 13089 storage/replica_command.go:2456  [n1,s1,r8/1:/{Table/51-Max},@c424631880] initiating a split of this range at key /Table/51/1/1 [r10]
I170301 08:32:04.948927 13197 storage/replica_command.go:2456  [n1,s1,r10/1:/{Table/51/1/1-Max},@c423462380] initiating a split of this range at key /Table/51/1/2 [r11]
I170301 08:32:05.045644 13289 storage/raft_transport.go:436  [n3] raft transport stream to node 2 established
I170301 08:32:05.060283 13331 storage/replica_command.go:2456  [n1,s1,r11/1:/{Table/51/1/2-Max},@c423f73500] initiating a split of this range at key /Table/51/1/3 [r12]
I170301 08:32:05.158566 13302 storage/raft_transport.go:436  [n2] raft transport stream to node 3 established
I170301 08:32:05.190946 13313 storage/replica_command.go:2456  [n1,s1,r12/1:/{Table/51/1/3-Max},@c42120c000] initiating a split of this range at key /Table/51/1/4 [r13]
I170301 08:32:05.316341 13276 storage/replica_command.go:2456  [n1,s1,r13/1:/{Table/51/1/4-Max},@c420cb9880] initiating a split of this range at key /Table/51/1/5 [r14]
I170301 08:32:05.469713 13279 storage/replica_command.go:2456  [n1,s1,r14/1:/{Table/51/1/5-Max},@c420297180] initiating a split of this range at key /Table/51/1/6 [r15]
I170301 08:32:05.562747 13438 storage/replica_command.go:2456  [n1,s1,r15/1:/{Table/51/1/6-Max},@c42393fc00] initiating a split of this range at key /Table/51/1/7 [r16]
I170301 08:32:05.702582 13421 storage/replica_command.go:2456  [n1,s1,r16/1:/{Table/51/1/7-Max},@c421d1d500] initiating a split of this range at key /Table/51/1/8 [r17]
I170301 08:32:05.845101 13589 storage/replica_command.go:2456  [n1,s1,r17/1:/{Table/51/1/8-Max},@c4242b1180] initiating a split of this range at key /Table/51/1/9 [r18]
I170301 08:32:08.240923 14352 storage/replica_command.go:2456  [n1,s1,r18/1:/{Table/51/1/9-Max},@c423ca9500] initiating a split of this range at key /Table/52/1/5 [r19]
I170301 08:32:08.530150 14554 storage/replica_command.go:2456  [n1,s1,r19/1:/{Table/52/1/5-Max},@c4242e6380] initiating a split of this range at key /Table/52/1/8 [r20]
I170301 08:32:08.585355 14553 storage/replica_command.go:2456  [n2,s2,r18/2:/Table/5{1/1/9-2/1/5},@c423b0e380] initiating a split of this range at key /Table/52/1/2 [r31]
I170301 08:32:08.862289 14636 storage/replica_command.go:2456  [n1,s1,r19/1:/Table/52/1/{5-8},@c4242e6380] initiating a split of this range at key /Table/52/1/7 [r21]
I170301 08:32:08.879809 14696 storage/replica_command.go:2456  [n1,s1,r20/1:/{Table/52/1/8-Max},@c4203e9180] initiating a split of this range at key /Table/52/1/9 [r22]
I170301 08:32:09.115686 14850 storage/replica_command.go:2456  [n1,s1,r19/1:/Table/52/1/{5-7},@c4242e6380] initiating a split of this range at key /Table/52/1/6 [r23]
I170301 08:32:09.148747 14790 storage/replica_command.go:2456  [n2,s2,r18/2:/Table/5{1/1/9-2/1/2},@c423b0e380] initiating a split of this range at key /Table/52/1/1 [r32]
I170301 08:32:09.193933 14861 storage/replica_command.go:2456  [n2,s2,r31/2:/Table/52/1/{2-5},@c424097180] initiating a split of this range at key /Table/52/1/4 [r33]
I170301 08:32:09.698210 15081 storage/replica_command.go:2456  [n2,s2,r18/2:/Table/5{1/1/9-2/1/1},@c423b0e380] initiating a split of this range at key /Table/52/1 [r34]
I170301 08:32:09.765138 15123 storage/replica_command.go:2456  [n2,s2,r31/2:/Table/52/1/{2-4},@c424097180] initiating a split of this range at key /Table/52/1/3 [r35]
I170301 08:32:10.377034 15308 storage/engine/rocksdb.go:345  opening rocksdb instance at "/go/src/github.com/cockroachdb/cockroach/artifacts/RocksDBSstFileReader753745689"
I170301 08:32:10.395747 15285 storage/engine/rocksdb.go:345  opening rocksdb instance at "/go/src/github.com/cockroachdb/cockroach/artifacts/RocksDBSstFileReader264282532"
I170301 08:32:10.409936 15319 storage/engine/rocksdb.go:345  opening rocksdb instance at "/go/src/github.com/cockroachdb/cockroach/artifacts/RocksDBSstFileReader460123315"
I170301 08:32:10.410156 15278 storage/engine/rocksdb.go:345  opening rocksdb instance at "/go/src/github.com/cockroachdb/cockroach/artifacts/RocksDBSstFileReader285648502"
I170301 08:32:10.453309 15370 storage/engine/rocksdb.go:345  opening rocksdb instance at "/go/src/github.com/cockroachdb/cockroach/artifacts/RocksDBSstFileReader070194525"
I170301 08:32:10.585648 15285 storage/engine/rocksdb.go:410  closing rocksdb instance at "/go/src/github.com/cockroachdb/cockroach/artifacts/RocksDBSstFileReader264282532"
I170301 08:32:10.588265 15309 storage/engine/rocksdb.go:345  opening rocksdb instance at "/go/src/github.com/cockroachdb/cockroach/artifacts/RocksDBSstFileReader473843992"
I170301 08:32:10.626634 15319 storage/engine/rocksdb.go:410  closing rocksdb instance at "/go/src/github.com/cockroachdb/cockroach/artifacts/RocksDBSstFileReader460123315"
I170301 08:32:10.630591 15324 storage/engine/rocksdb.go:345  opening rocksdb instance at "/go/src/github.com/cockroachdb/cockroach/artifacts/RocksDBSstFileReader059451799"
I170301 08:32:10.674870 15308 storage/engine/rocksdb.go:410  closing rocksdb instance at "/go/src/github.com/cockroachdb/cockroach/artifacts/RocksDBSstFileReader753745689"
I170301 08:32:10.682934 15370 storage/engine/rocksdb.go:410  closing rocksdb instance at "/go/src/github.com/cockroachdb/cockroach/artifacts/RocksDBSstFileReader070194525"
I170301 08:32:10.686116 15323 storage/engine/rocksdb.go:345  opening rocksdb instance at "/go/src/github.com/cockroachdb/cockroach/artifacts/RocksDBSstFileReader347168778"
I170301 08:32:10.688452 15278 storage/engine/rocksdb.go:410  closing rocksdb instance at "/go/src/github.com/cockroachdb/cockroach/artifacts/RocksDBSstFileReader285648502"
I170301 08:32:10.697876 15322 storage/engine/rocksdb.go:345  opening rocksdb instance at "/go/src/github.com/cockroachdb/cockroach/artifacts/RocksDBSstFileReader343029196"
I170301 08:32:10.698559 15321 storage/engine/rocksdb.go:345  opening rocksdb instance at "/go/src/github.com/cockroachdb/cockroach/artifacts/RocksDBSstFileReader662831585"
I170301 08:32:10.818715 15309 storage/engine/rocksdb.go:410  closing rocksdb instance at "/go/src/github.com/cockroachdb/cockroach/artifacts/RocksDBSstFileReader473843992"
I170301 08:32:10.857556 15324 storage/engine/rocksdb.go:410  closing rocksdb instance at "/go/src/github.com/cockroachdb/cockroach/artifacts/RocksDBSstFileReader059451799"
I170301 08:32:10.870358 15323 storage/engine/rocksdb.go:410  closing rocksdb instance at "/go/src/github.com/cockroachdb/cockroach/artifacts/RocksDBSstFileReader347168778"
I170301 08:32:10.915114 15321 storage/engine/rocksdb.go:410  closing rocksdb instance at "/go/src/github.com/cockroachdb/cockroach/artifacts/RocksDBSstFileReader662831585"
I170301 08:32:10.915822 15322 storage/engine/rocksdb.go:410  closing rocksdb instance at "/go/src/github.com/cockroachdb/cockroach/artifacts/RocksDBSstFileReader343029196"
I170301 08:32:14.179982 16604 storage/replica_command.go:2456  [n1,s1,r22/1:/{Table/52/1/9-Max},@c4249fd500] initiating a split of this range at key /Table/53/1/5 [r24]
I170301 08:32:14.504139 16700 storage/replica_command.go:2456  [n1,s1,r22/1:/Table/5{2/1/9-3/1/5},@c4249fd500] initiating a split of this range at key /Table/53/1/2 [r25]
I170301 08:32:14.519875 16810 storage/replica_command.go:2456  [n1,s1,r24/1:/{Table/53/1/5-Max},@c421c8ee00] initiating a split of this range at key /Table/53/1/8 [r26]
I170301 08:32:14.870902 16863 storage/replica_command.go:2456  [n1,s1,r22/1:/Table/5{2/1/9-3/1/2},@c4249fd500] initiating a split of this range at key /Table/53/1/1 [r27]
I170301 08:32:14.932756 16908 storage/replica_command.go:2456  [n1,s1,r25/1:/Table/53/1/{2-5},@c4219c0000] initiating a split of this range at key /Table/53/1/4 [r28]
I170301 08:32:14.988809 16897 storage/replica_command.go:2456  [n1,s1,r24/1:/Table/53/1/{5-8},@c421c8ee00] initiating a split of this range at key /Table/53/1/7 [r29]
I170301 08:32:15.023297 16958 storage/replica_command.go:2456  [n1,s1,r26/1:/{Table/53/1/8-Max},@c42080d500] initiating a split of this range at key /Table/53/1/9 [r30]
I170301 08:32:15.379880 17088 storage/replica_command.go:2456  [n1,s1,r24/1:/Table/53/1/{5-7},@c421c8ee00] initiating a split of this range at key /Table/53/1/6 [r51]
I170301 08:32:15.442255 12376 storage/split_queue.go:98  [split,n2,s2,r18/2:/Table/5{1/1/9-2/1},@c423b0e380] splitting at key /Table/52/0
I170301 08:32:15.454219 12376 storage/replica_command.go:2456  [split,n2,s2,r18/2:/Table/5{1/1/9-2/1},@c423b0e380] initiating a split of this range at key /Table/52 [r36]
I170301 08:32:15.569288 17218 storage/replica_command.go:2456  [n1,s1,r22/1:/Table/5{2/1/9-3/1/1},@c4249fd500] initiating a split of this range at key /Table/53/1 [r52]
I170301 08:32:15.623931 17235 storage/replica_command.go:2456  [n1,s1,r25/1:/Table/53/1/{2-4},@c4219c0000] initiating a split of this range at key /Table/53/1/3 [r53]
E170301 08:32:16.796610 12289 storage/consistency_queue.go:89  [replica consistency checker,n1,s1,r25/1:/Table/53/1/{2-3},@c4219c0000] [NotLeaseHolderError] stale proposal: command was proposed under lease repl={1 1 1} start=0.000000000,0 exp=1488357144.319031977,0 pro=1488357135.319063978,0 but is being applied under lease: repl={2 2 2} start=1488357136.706500490,0 exp=1488357145.706500490,0 pro=1488357136.706508690,0
I170301 08:32:17.091579 17692 storage/engine/rocksdb.go:345  opening rocksdb instance at "/go/src/github.com/cockroachdb/cockroach/artifacts/RocksDBSstFileReader937074398"
I170301 08:32:17.137637 17613 storage/engine/rocksdb.go:345  opening rocksdb instance at "/go/src/github.com/cockroachdb/cockroach/artifacts/RocksDBSstFileReader144111291"
I170301 08:32:17.144709 17729 storage/engine/rocksdb.go:345  opening rocksdb instance at "/go/src/github.com/cockroachdb/cockroach/artifacts/RocksDBSstFileReader186717861"
I170301 08:32:17.218237 17763 storage/engine/rocksdb.go:345  opening rocksdb instance at "/go/src/github.com/cockroachdb/cockroach/artifacts/RocksDBSstFileReader886079936"
I170301 08:32:17.248594 17766 storage/engine/rocksdb.go:345  opening rocksdb instance at "/go/src/github.com/cockroachdb/cockroach/artifacts/RocksDBSstFileReader068528159"
I170301 08:32:17.499187 17692 storage/engine/rocksdb.go:410  closing rocksdb instance at "/go/src/github.com/cockroachdb/cockroach/artifacts/RocksDBSstFileReader937074398"
I170301 08:32:17.500553 17783 storage/engine/rocksdb.go:345  opening rocksdb instance at "/go/src/github.com/cockroachdb/cockroach/artifacts/RocksDBSstFileReader854384370"
I170301 08:32:17.538425 17613 storage/engine/rocksdb.go:410  closing rocksdb instance at "/go/src/github.com/cockroachdb/cockroach/artifacts/RocksDBSstFileReader144111291"
I170301 08:32:17.555854 17782 storage/engine/rocksdb.go:345  opening rocksdb instance at "/go/src/github.com/cockroachdb/cockroach/artifacts/RocksDBSstFileReader176261545"
I170301 08:32:17.661990 17729 storage/engine/rocksdb.go:410  closing rocksdb instance at "/go/src/github.com/cockroachdb/cockroach/artifacts/RocksDBSstFileReader186717861"
I170301 08:32:17.663003 17763 storage/engine/rocksdb.go:410  closing rocksdb instance at "/go/src/github.com/cockroachdb/cockroach/artifacts/RocksDBSstFileReader886079936"
I170301 08:32:17.664255 17766 storage/engine/rocksdb.go:410  closing rocksdb instance at "/go/src/github.com/cockroachdb/cockroach/artifacts/RocksDBSstFileReader068528159"
I170301 08:32:17.678472 17669 storage/engine/rocksdb.go:345  opening rocksdb instance at "/go/src/github.com/cockroachdb/cockroach/artifacts/RocksDBSstFileReader294173428"
I170301 08:32:17.692546 17784 storage/engine/rocksdb.go:345  opening rocksdb instance at "/go/src/github.com/cockroachdb/cockroach/artifacts/RocksDBSstFileReader076664771"
I170301 08:32:17.701692 17734 storage/engine/rocksdb.go:345  opening rocksdb instance at "/go/src/github.com/cockroachdb/cockroach/artifacts/RocksDBSstFileReader582088774"
I170301 08:32:17.808727 17783 storage/engine/rocksdb.go:410  closing rocksdb instance at "/go/src/github.com/cockroachdb/cockroach/artifacts/RocksDBSstFileReader854384370"
I170301 08:32:17.811235 17782 storage/engine/rocksdb.go:410  closing rocksdb instance at "/go/src/github.com/cockroachdb/cockroach/artifacts/RocksDBSstFileReader176261545"
I170301 08:32:17.933090 17669 storage/engine/rocksdb.go:410  closing rocksdb instance at "/go/src/github.com/cockroachdb/cockroach/artifacts/RocksDBSstFileReader294173428"
I170301 08:32:18.035568 17734 storage/engine/rocksdb.go:410  closing rocksdb instance at "/go/src/github.com/cockroachdb/cockroach/artifacts/RocksDBSstFileReader582088774"
I170301 08:32:18.068715 17784 storage/engine/rocksdb.go:410  closing rocksdb instance at "/go/src/github.com/cockroachdb/cockroach/artifacts/RocksDBSstFileReader076664771"
W170301 08:32:18.420555 13302 storage/raft_transport.go:442  [n2] raft transport stream to node 3 failed: EOF
W170301 08:32:18.421639 12800 storage/raft_transport.go:442  [n1] raft transport stream to node 3 failed: EOF
W170301 08:32:18.422543 12789 storage/raft_transport.go:442  [n2] raft transport stream to node 1 failed: rpc error: code = 13 desc = transport is closing
W170301 08:32:18.422635 12768 storage/raft_transport.go:442  [n1] raft transport stream to node 2 failed: EOF
W170301 08:32:18.423160 13289 storage/raft_transport.go:442  [n3] raft transport stream to node 2 failed: EOF
W170301 08:32:18.426108 12847 storage/raft_transport.go:442  [n3] raft transport stream to node 1 failed: rpc error: code = 13 desc = transport is closing
I170301 08:32:18.428555 12128 kv/transport_race.go:71  transport race promotion: ran 98 iterations on up to 2731 requests
	<autogenerated>:14: error executing 'RESTORE DATABASE bench FROM '/go/src/github.com/cockroachdb/cockroach/artifacts/TestBackupRestoreBank804267797/1'': pq: importing 10 ranges: first of 1 errors: import can only be called on empty ranges
```

### LINKED ISSUE #13867: ccl/sqlccl: TestBackupRestoreLocal failed under stress
SHA: https://github.com/cockroachdb/cockroach/commits/7819483d60fd6461f9e9f704c4e6a8df397fbb5a

Parameters:
```
COCKROACH_PROPOSER_EVALUATED_KV=true
TAGS=deadlock
GOFLAGS=
```

Stress build found a failed test: https://teamcity.cockroachdb.com/viewLog.html?buildId=166411&tab=buildLog

```
I170301 09:52:23.895260 101 server/node.go:391  [n1] node=1: started with [[]=] engine(s) and attributes []
I170301 09:52:23.895336 101 sql/executor.go:337  [n1] creating distSQLPlanner with address {tcp 127.0.0.1:50044}
I170301 09:52:23.899505 101 server/server.go:651  [n1] starting https server at 127.0.0.1:46456
I170301 09:52:23.899607 101 server/server.go:652  [n1] starting grpc/postgres server at 127.0.0.1:50044
I170301 09:52:23.899702 101 server/server.go:653  [n1] advertising CockroachDB node at 127.0.0.1:50044
I170301 09:52:23.902486 1052 storage/split_queue.go:98  [split,n1,s1,r1/1:/M{in-ax},@c4200a4600] splitting at key /Table/0/0
I170301 09:52:23.906899 1052 storage/replica_command.go:2456  [split,n1,s1,r1/1:/M{in-ax},@c4200a4600] initiating a split of this range at key /Table/0 [r2]
E170301 09:52:23.928728 1053 storage/queue.go:628  [replicate,n1,s1,r1/1:/{Min-Table/0},@c4200a4600] range requires a replication change, but lacks a quorum of live replicas (0/1)
I170301 09:52:23.929376 1052 storage/split_queue.go:98  [split,n1,s1,r2/1:/{Table/0-Max},@c42083e900] splitting at key /Table/11/0
I170301 09:52:23.929552 1052 storage/replica_command.go:2456  [split,n1,s1,r2/1:/{Table/0-Max},@c42083e900] initiating a split of this range at key /Table/11 [r3]
E170301 09:52:23.941175 1053 storage/queue.go:628  [replicate,n1,s1,r2/1:/Table/{0-11},@c42083e900] range requires a replication change, but lacks a quorum of live replicas (0/1)
I170301 09:52:23.947220 1052 storage/split_queue.go:98  [split,n1,s1,r3/1:/{Table/11-Max},@c42083fb00] splitting at key /Table/12/0
I170301 09:52:23.947333 1052 storage/replica_command.go:2456  [split,n1,s1,r3/1:/{Table/11-Max},@c42083fb00] initiating a split of this range at key /Table/12 [r4]
I170301 09:52:23.968880 1140 sql/event_log.go:95  [n1] Event: "node_join", target: 1, info: {Descriptor:{NodeID:1 Address:{NetworkField:tcp AddressField:127.0.0.1:50044} Attrs: Locality:} ClusterID:4ff64b32-0743-4f9c-af25-ce54aab8129b StartedAt:1488361943895224003 LastUp:1488361943895224003}
I170301 09:52:23.986253 1052 storage/split_queue.go:98  [split,n1,s1,r4/1:/{Table/12-Max},@c420c36c00] splitting at key /Table/13/0
I170301 09:52:23.986369 1052 storage/replica_command.go:2456  [split,n1,s1,r4/1:/{Table/12-Max},@c420c36c00] initiating a split of this range at key /Table/13 [r5]
I170301 09:52:23.995993 101 sql/event_log.go:95  [n1] Event: "alter_table", target: 12, info: {TableName:eventlog Statement:ALTER TABLE system.eventlog ALTER COLUMN uniqueID SET DEFAULT uuid_v4() User:node MutationID:0 CascadeDroppedViews:[]}
I170301 09:52:24.010707 1052 storage/split_queue.go:98  [split,n1,s1,r5/1:/{Table/13-Max},@c420c37b00] splitting at key /Table/14/0
I170301 09:52:24.010839 1052 storage/replica_command.go:2456  [split,n1,s1,r5/1:/{Table/13-Max},@c420c37b00] initiating a split of this range at key /Table/14 [r6]
I170301 09:52:24.038703 101 server/server.go:779  [n1] done ensuring all necessary migrations have run
I170301 09:52:24.038853 101 server/server.go:781  [n1] serving sql connections
W170301 09:52:24.042201 101 gossip/gossip.go:1178  [n?] no incoming or outgoing connections
W170301 09:52:24.044235 101 server/status/runtime.go:116  Could not parse build timestamp: parsing time "" as "2006/01/02 15:04:05": cannot parse "" as "2006"
I170301 09:52:24.046024 101 server/config.go:482  1 storage engine initialized
I170301 09:52:24.047553 101 server/node.go:443  [n?] store [n0,s0] not bootstrapped
I170301 09:52:24.047696 101 storage/stores.go:296  [n?] read 0 node addresses from persistent storage
I170301 09:52:24.047809 101 server/node.go:605  [n?] connecting to gossip network to verify cluster ID...
I170301 09:52:24.053919 8558 gossip/client.go:131  [n?] started gossip client to 127.0.0.1:50044
I170301 09:52:24.054052 8949 gossip/server.go:214  [n1] received initial cluster-verification connection from {tcp 127.0.0.1:56064}
I170301 09:52:24.055123 101 server/node.go:629  [n?] node connected via gossip and verified as part of cluster "4ff64b32-0743-4f9c-af25-ce54aab8129b"
I170301 09:52:24.055466 9001 storage/stores.go:312  [n?] wrote 1 node addresses to persistent storage
I170301 09:52:24.056842 101 kv/dist_sender.go:368  [n?] unable to determine this node's attributes for replica selection; node is most likely bootstrapping
I170301 09:52:24.059936 101 server/node.go:334  [n?] new node allocated ID 2
I170301 09:52:24.060272 101 gossip/gossip.go:293  [n2] NodeDescriptor set to node_id:2 address:<network_field:"tcp" address_field:"127.0.0.1:56064" > attrs:<> locality:<> 
I170301 09:52:24.060635 101 server/node.go:391  [n2] node=2: started with [[]=] engine(s) and attributes []
I170301 09:52:24.060999 101 sql/executor.go:337  [n2] creating distSQLPlanner with address {tcp 127.0.0.1:56064}
I170301 09:52:24.062670 101 server/server.go:651  [n2] starting https server at 127.0.0.1:52686
I170301 09:52:24.062724 101 server/server.go:652  [n2] starting grpc/postgres server at 127.0.0.1:56064
I170301 09:52:24.062781 101 server/server.go:653  [n2] advertising CockroachDB node at 127.0.0.1:56064
I170301 09:52:24.065644 9454 storage/stores.go:312  [n1] wrote 1 node addresses to persistent storage
I170301 09:52:24.067305 9169 server/node.go:586  [n2] bootstrapped store [n2,s2]
I170301 09:52:24.067796 101 server/server.go:779  [n2] done ensuring all necessary migrations have run
I170301 09:52:24.067859 101 server/server.go:781  [n2] serving sql connections
I170301 09:52:24.068862 4810 storage/replica_raftstorage.go:414  [replicate,n1,s1,r3/1:/Table/1{1-2},@c42083fb00] generated preemptive snapshot 4f7cfaa5 at index 18
I170301 09:52:24.079240 9237 sql/event_log.go:95  [n2] Event: "node_join", target: 2, info: {Descriptor:{NodeID:2 Address:{NetworkField:tcp AddressField:127.0.0.1:56064} Attrs: Locality:} ClusterID:4ff64b32-0743-4f9c-af25-ce54aab8129b StartedAt:1488361944060604612 LastUp:1488361944060604612}
W170301 09:52:24.079452 101 gossip/gossip.go:1178  [n?] no incoming or outgoing connections
W170301 09:52:24.080865 101 server/status/runtime.go:116  Could not parse build timestamp: parsing time "" as "2006/01/02 15:04:05": cannot parse "" as "2006"
I170301 09:52:24.082224 101 server/config.go:482  1 storage engine initialized
I170301 09:52:24.083825 101 server/node.go:443  [n?] store [n0,s0] not bootstrapped
I170301 09:52:24.083934 101 storage/stores.go:296  [n?] read 0 node addresses from persistent storage
I170301 09:52:24.084024 101 server/node.go:605  [n?] connecting to gossip network to verify cluster ID...
I170301 09:52:24.087469 4810 storage/store.go:3295  [replicate,n1,s1,r3/1:/Table/1{1-2},@c42083fb00] streamed snapshot: kv pairs: 10, log entries: 8, 1ms
I170301 09:52:24.087915 10544 storage/replica_raftstorage.go:596  [n2,s2,r3/?:{-},@c420750000] applying preemptive snapshot at index 18 (id=4f7cfaa5, encoded size=11067, 1 rocksdb batches, 8 log entries)
I170301 09:52:24.088331 10544 storage/replica_raftstorage.go:604  [n2,s2,r3/?:/Table/1{1-2},@c420750000] applied preemptive snapshot in 0ms [clear=0ms batch=0ms entries=0ms commit=0ms]
I170301 09:52:24.089271 4810 storage/replica_command.go:3312  [replicate,n1,s1,r3/1:/Table/1{1-2},@c42083fb00] change replicas (remove {2 2 2}): read existing descriptor range_id:3 start_key:"\223" end_key:"\224" replicas:<node_id:1 store_id:1 replica_id:1 > next_replica_id:2 
I170301 09:52:24.090788 10531 gossip/client.go:131  [n?] started gossip client to 127.0.0.1:50044
I170301 09:52:24.090983 10857 gossip/server.go:214  [n1] received initial cluster-verification connection from {tcp 127.0.0.1:42696}
I170301 09:52:24.091956 101 server/node.go:629  [n?] node connected via gossip and verified as part of cluster "4ff64b32-0743-4f9c-af25-ce54aab8129b"
I170301 09:52:24.092574 10971 storage/stores.go:312  [n?] wrote 1 node addresses to persistent storage
I170301 09:52:24.093000 10971 storage/stores.go:312  [n?] wrote 2 node addresses to persistent storage
I170301 09:52:24.094413 101 kv/dist_sender.go:368  [n?] unable to determine this node's attributes for replica selection; node is most likely bootstrapping
I170301 09:52:24.099453 101 server/node.go:334  [n?] new node allocated ID 3
I170301 09:52:24.100080 101 gossip/gossip.go:293  [n3] NodeDescriptor set to node_id:3 address:<network_field:"tcp" address_field:"127.0.0.1:42696" > attrs:<> locality:<> 
I170301 09:52:24.100273 101 server/node.go:391  [n3] node=3: started with [[]=] engine(s) and attributes []
I170301 09:52:24.100354 101 sql/executor.go:337  [n3] creating distSQLPlanner with address {tcp 127.0.0.1:42696}
I170301 09:52:24.100795 11666 storage/replica.go:2510  [n1,s1,r3/1:/Table/1{1-2},@c42083fb00] proposing ADD_REPLICA {NodeID:2 StoreID:2 ReplicaID:2}: [{NodeID:1 StoreID:1 ReplicaID:1} {NodeID:2 StoreID:2 ReplicaID:2}]
I170301 09:52:24.110283 101 server/server.go:651  [n3] starting https server at 127.0.0.1:38414
I170301 09:52:24.110353 101 server/server.go:652  [n3] starting grpc/postgres server at 127.0.0.1:42696
I170301 09:52:24.110430 101 server/server.go:653  [n3] advertising CockroachDB node at 127.0.0.1:42696
I170301 09:52:24.115779 12025 storage/stores.go:312  [n1] wrote 2 node addresses to persistent storage
I170301 09:52:24.117845 4810 storage/replica_raftstorage.go:414  [replicate,n1,s1,r5/1:/Table/1{3-4},@c420c37b00] generated preemptive snapshot 1c0b7537 at index 17
I170301 09:52:24.119536 12013 storage/stores.go:312  [n2] wrote 2 node addresses to persistent storage
I170301 09:52:24.120738 4810 storage/store.go:3295  [replicate,n1,s1,r5/1:/Table/1{3-4},@c420c37b00] streamed snapshot: kv pairs: 50, log entries: 7, 1ms
I170301 09:52:24.121602 101 server/server.go:779  [n3] done ensuring all necessary migrations have run
I170301 09:52:24.121876 101 server/server.go:781  [n3] serving sql connections
I170301 09:52:24.122205 12376 storage/replica_raftstorage.go:596  [n2,s2,r5/?:{-},@c420b79800] applying preemptive snapshot at index 17 (id=1c0b7537, encoded size=13006, 1 rocksdb batches, 7 log entries)
I170301 09:52:24.122601 11701 server/node.go:586  [n3] bootstrapped store [n3,s3]
I170301 09:52:24.122879 12376 storage/replica_raftstorage.go:604  [n2,s2,r5/?:/Table/1{3-4},@c420b79800] applied preemptive snapshot in 0ms [clear=0ms batch=0ms entries=0ms commit=0ms]
I170301 09:52:24.125398 4810 storage/replica_command.go:3312  [replicate,n1,s1,r5/1:/Table/1{3-4},@c420c37b00] change replicas (remove {2 2 2}): read existing descriptor range_id:5 start_key:"\225" end_key:"\226" replicas:<node_id:1 store_id:1 replica_id:1 > next_replica_id:2 
I170301 09:52:24.126669 13296 storage/raft_transport.go:436  [n2] raft transport stream to node 1 established
I170301 09:52:24.137257 4810 storage/replica_command.go:3312  [replicate,n1,s1,r5/1:/Table/1{3-4},@c420c37b00] change replicas (remove {2 2 2}): read existing descriptor range_id:5 start_key:"\225" end_key:"\226" replicas:<node_id:1 store_id:1 replica_id:1 > next_replica_id:2 
I170301 09:52:24.139225 11705 sql/event_log.go:95  [n3] Event: "node_join", target: 3, info: {Descriptor:{NodeID:3 Address:{NetworkField:tcp AddressField:127.0.0.1:42696} Attrs: Locality:} ClusterID:4ff64b32-0743-4f9c-af25-ce54aab8129b StartedAt:1488361944100243964 LastUp:1488361944100243964}
I170301 09:52:24.155246 14569 storage/replica.go:2510  [n1,s1,r5/1:/Table/1{3-4},@c420c37b00] proposing ADD_REPLICA {NodeID:2 StoreID:2 ReplicaID:2}: [{NodeID:1 StoreID:1 ReplicaID:1} {NodeID:2 StoreID:2 ReplicaID:2}]
I170301 09:52:24.157116 1053 storage/replica_raftstorage.go:414  [replicate,n1,s1,r1/1:/{Min-Table/0},@c4200a4600] generated preemptive snapshot f5a0e08c at index 55
I170301 09:52:24.170712 1053 storage/store.go:3295  [replicate,n1,s1,r1/1:/{Min-Table/0},@c4200a4600] streamed snapshot: kv pairs: 831, log entries: 45, 5ms
I170301 09:52:24.171889 15022 storage/replica_raftstorage.go:596  [n3,s3,r1/?:{-},@c420c36300] applying preemptive snapshot at index 55 (id=f5a0e08c, encoded size=429221, 1 rocksdb batches, 45 log entries)
I170301 09:52:24.175147 15022 storage/replica_raftstorage.go:604  [n3,s3,r1/?:/{Min-Table/0},@c420c36300] applied preemptive snapshot in 3ms [clear=0ms batch=0ms entries=0ms commit=2ms]
I170301 09:52:24.176096 1053 storage/replica_command.go:3312  [replicate,n1,s1,r1/1:/{Min-Table/0},@c4200a4600] change replicas (remove {3 3 2}): read existing descriptor range_id:1 start_key:"" end_key:"\210" replicas:<node_id:1 store_id:1 replica_id:1 > next_replica_id:2 
I170301 09:52:24.182654 15569 storage/replica.go:2510  [n1,s1,r1/1:/{Min-Table/0},@c4200a4600] proposing ADD_REPLICA {NodeID:3 StoreID:3 ReplicaID:2}: [{NodeID:1 StoreID:1 ReplicaID:1} {NodeID:3 StoreID:3 ReplicaID:2}]
I170301 09:52:24.184649 4810 storage/replica_raftstorage.go:414  [replicate,n1,s1,r4/1:/Table/1{2-3},@c420c36c00] generated preemptive snapshot 1ad26e95 at index 22
I170301 09:52:24.192277 16126 storage/raft_transport.go:436  [n3] raft transport stream to node 1 established
I170301 09:52:24.193656 15817 storage/replica_raftstorage.go:596  [n3,s3,r4/?:{-},@c42156b200] applying preemptive snapshot at index 22 (id=1ad26e95, encoded size=20121, 1 rocksdb batches, 12 log entries)
I170301 09:52:24.194076 15817 storage/replica_raftstorage.go:604  [n3,s3,r4/?:/Table/1{2-3},@c42156b200] applied preemptive snapshot in 0ms [clear=0ms batch=0ms entries=0ms commit=0ms]
I170301 09:52:24.195170 4810 storage/store.go:3295  [replicate,n1,s1,r4/1:/Table/1{2-3},@c420c36c00] streamed snapshot: kv pairs: 30, log entries: 12, 7ms
I170301 09:52:24.196489 4810 storage/replica_command.go:3312  [replicate,n1,s1,r4/1:/Table/1{2-3},@c420c36c00] change replicas (remove {3 3 2}): read existing descriptor range_id:4 start_key:"\224" end_key:"\225" replicas:<node_id:1 store_id:1 replica_id:1 > next_replica_id:2 
I170301 09:52:24.205961 16931 storage/replica.go:2510  [n1,s1,r4/1:/Table/1{2-3},@c420c36c00] proposing ADD_REPLICA {NodeID:3 StoreID:3 ReplicaID:2}: [{NodeID:1 StoreID:1 ReplicaID:1} {NodeID:3 StoreID:3 ReplicaID:2}]
I170301 09:52:24.208011 1053 storage/replica_raftstorage.go:414  [replicate,n1,s1,r3/1:/Table/1{1-2},@c42083fb00] generated preemptive snapshot aa17c803 at index 21
I170301 09:52:24.208590 1053 storage/store.go:3295  [replicate,n1,s1,r3/1:/Table/1{1-2},@c42083fb00] streamed snapshot: kv pairs: 11, log entries: 11, 0ms
I170301 09:52:24.209294 16854 storage/replica_raftstorage.go:596  [n3,s3,r3/?:{-},@c4200a4900] applying preemptive snapshot at index 21 (id=aa17c803, encoded size=14035, 1 rocksdb batches, 11 log entries)
I170301 09:52:24.209678 16854 storage/replica_raftstorage.go:604  [n3,s3,r3/?:/Table/1{1-2},@c4200a4900] applied preemptive snapshot in 0ms [clear=0ms batch=0ms entries=0ms commit=0ms]
I170301 09:52:24.211475 1053 storage/replica_command.go:3312  [replicate,n1,s1,r3/1:/Table/1{1-2},@c42083fb00] change replicas (remove {3 3 3}): read existing descriptor range_id:3 start_key:"\223" end_key:"\224" replicas:<node_id:1 store_id:1 replica_id:1 > replicas:<node_id:2 store_id:2 replica_id:2 > next_replica_id:3 
I170301 09:52:24.226975 18443 storage/replica.go:2510  [n1,s1,r3/1:/Table/1{1-2},@c42083fb00] proposing ADD_REPLICA {NodeID:3 StoreID:3 ReplicaID:3}: [{NodeID:1 StoreID:1 ReplicaID:1} {NodeID:2 StoreID:2 ReplicaID:2} {NodeID:3 StoreID:3 ReplicaID:3}]
I170301 09:52:24.229821 4810 storage/replica_raftstorage.go:414  [replicate,n1,s1,r6/1:/{Table/14-Max},@c420b78600] generated preemptive snapshot cf12d30f at index 11
I170301 09:52:24.231478 4810 storage/store.go:3295  [replicate,n1,s1,r6/1:/{Table/14-Max},@c420b78600] streamed snapshot: kv pairs: 9, log entries: 1, 1ms
I170301 09:52:24.232219 18787 storage/replica_raftstorage.go:596  [n2,s2,r6/?:{-},@c420b78c00] applying preemptive snapshot at index 11 (id=cf12d30f, encoded size=504, 1 rocksdb batches, 1 log entries)
I170301 09:52:24.232701 18787 storage/replica_raftstorage.go:604  [n2,s2,r6/?:/{Table/14-Max},@c420b78c00] applied preemptive snapshot in 0ms [clear=0ms batch=0ms entries=0ms commit=0ms]
I170301 09:52:24.236095 4810 storage/replica_command.go:3312  [replicate,n1,s1,r6/1:/{Table/14-Max},@c420b78600] change replicas (remove {2 2 2}): read existing descriptor range_id:6 start_key:"\226" end_key:"\377\377" replicas:<node_id:1 store_id:1 replica_id:1 > next_replica_id:2 
I170301 09:52:24.251590 20122 storage/replica.go:2510  [n1,s1,r6/1:/{Table/14-Max},@c420b78600] proposing ADD_REPLICA {NodeID:2 StoreID:2 ReplicaID:2}: [{NodeID:1 StoreID:1 ReplicaID:1} {NodeID:2 StoreID:2 ReplicaID:2}]
I170301 09:52:24.252524 4810 storage/queue.go:693  [n1,replicate] purgatory is now empty
I170301 09:52:24.253923 1053 storage/replica_raftstorage.go:414  [replicate,n1,s1,r1/1:/{Min-Table/0},@c4200a4600] generated preemptive snapshot d044a27f at index 64
I170301 09:52:24.262800 1053 storage/store.go:3295  [replicate,n1,s1,r1/1:/{Min-Table/0},@c4200a4600] streamed snapshot: kv pairs: 837, log entries: 54, 9ms
I170301 09:52:24.263422 20198 storage/replica_raftstorage.go:596  [n2,s2,r1/?:{-},@c42146d800] applying preemptive snapshot at index 64 (id=d044a27f, encoded size=436874, 1 rocksdb batches, 54 log entries)
I170301 09:52:24.265875 20198 storage/replica_raftstorage.go:604  [n2,s2,r1/?:/{Min-Table/0},@c42146d800] applied preemptive snapshot in 2ms [clear=0ms batch=1ms entries=0ms commit=1ms]
I170301 09:52:24.268493 1053 storage/replica_command.go:3312  [replicate,n1,s1,r1/1:/{Min-Table/0},@c4200a4600] change replicas (remove {2 2 3}): read existing descriptor range_id:1 start_key:"" end_key:"\210" replicas:<node_id:1 store_id:1 replica_id:1 > replicas:<node_id:3 store_id:3 replica_id:2 > next_replica_id:3 
I170301 09:52:24.276785 21507 storage/replica.go:2510  [n1,s1,r1/1:/{Min-Table/0},@c4200a4600] proposing ADD_REPLICA {NodeID:2 StoreID:2 ReplicaID:3}: [{NodeID:1 StoreID:1 ReplicaID:1} {NodeID:3 StoreID:3 ReplicaID:2} {NodeID:2 StoreID:2 ReplicaID:3}]
I170301 09:52:24.279372 1053 storage/replica_raftstorage.go:414  [replicate,n1,s1,r4/1:/Table/1{2-3},@c420c36c00] generated preemptive snapshot 8dcadedb at index 25
I170301 09:52:24.280339 1053 storage/store.go:3295  [replicate,n1,s1,r4/1:/Table/1{2-3},@c420c36c00] streamed snapshot: kv pairs: 31, log entries: 15, 1ms
I170301 09:52:24.280945 21794 storage/replica_raftstorage.go:596  [n2,s2,r4/?:{-},@c4200a5200] applying preemptive snapshot at index 25 (id=8dcadedb, encoded size=23089, 1 rocksdb batches, 15 log entries)
I170301 09:52:24.281353 21794 storage/replica_raftstorage.go:604  [n2,s2,r4/?:/Table/1{2-3},@c4200a5200] applied preemptive snapshot in 0ms [clear=0ms batch=0ms entries=0ms commit=0ms]
I170301 09:52:24.282626 1053 storage/replica_command.go:3312  [replicate,n1,s1,r4/1:/Table/1{2-3},@c420c36c00] change replicas (remove {2 2 3}): read existing descriptor range_id:4 start_key:"\224" end_key:"\225" replicas:<node_id:1 store_id:1 replica_id:1 > replicas:<node_id:3 store_id:3 replica_id:2 > next_replica_id:3 
I170301 09:52:24.315030 23371 storage/replica.go:2510  [n1,s1,r4/1:/Table/1{2-3},@c420c36c00] proposing ADD_REPLICA {NodeID:2 StoreID:2 ReplicaID:3}: [{NodeID:1 StoreID:1 ReplicaID:1} {NodeID:3 StoreID:3 ReplicaID:2} {NodeID:2 StoreID:2 ReplicaID:3}]
I170301 09:52:24.320386 1053 storage/replica_raftstorage.go:414  [replicate,n1,s1,r6/1:/{Table/14-Max},@c420b78600] generated preemptive snapshot d17ac7f8 at index 14
I170301 09:52:24.320970 1053 storage/store.go:3295  [replicate,n1,s1,r6/1:/{Table/14-Max},@c420b78600] streamed snapshot: kv pairs: 10, log entries: 4, 0ms
I170301 09:52:24.321478 23991 storage/replica_raftstorage.go:596  [n3,s3,r6/?:{-},@c42146c900] applying preemptive snapshot at index 14 (id=d17ac7f8, encoded size=3479, 1 rocksdb batches, 4 log entries)
I170301 09:52:24.321777 23991 storage/replica_raftstorage.go:604  [n3,s3,r6/?:/{Table/14-Max},@c42146c900] applied preemptive snapshot in 0ms [clear=0ms batch=0ms entries=0ms commit=0ms]
I170301 09:52:24.322921 1053 storage/replica_command.go:3312  [replicate,n1,s1,r6/1:/{Table/14-Max},@c420b78600] change replicas (remove {3 3 3}): read existing descriptor range_id:6 start_key:"\226" end_key:"\377\377" replicas:<node_id:1 store_id:1 replica_id:1 > replicas:<node_id:2 store_id:2 replica_id:2 > next_replica_id:3 
I170301 09:52:24.337288 25348 storage/replica.go:2510  [n1,s1,r6/1:/{Table/14-Max},@c420b78600] proposing ADD_REPLICA {NodeID:3 StoreID:3 ReplicaID:3}: [{NodeID:1 StoreID:1 ReplicaID:1} {NodeID:2 StoreID:2 ReplicaID:2} {NodeID:3 StoreID:3 ReplicaID:3}]
I170301 09:52:24.340520 1053 storage/replica_raftstorage.go:414  [replicate,n1,s1,r5/1:/Table/1{3-4},@c420c37b00] generated preemptive snapshot 61963f73 at index 38
I170301 09:52:24.342510 1053 storage/store.go:3295  [replicate,n1,s1,r5/1:/Table/1{3-4},@c420c37b00] streamed snapshot: kv pairs: 91, log entries: 28, 2ms
I170301 09:52:24.346946 25726 storage/replica_raftstorage.go:596  [n3,s3,r5/?:{-},@c42156a300] applying preemptive snapshot at index 38 (id=61963f73, encoded size=48451, 1 rocksdb batches, 28 log entries)
I170301 09:52:24.347776 25726 storage/replica_raftstorage.go:604  [n3,s3,r5/?:/Table/1{3-4},@c42156a300] applied preemptive snapshot in 1ms [clear=0ms batch=0ms entries=0ms commit=0ms]
I170301 09:52:24.349412 1053 storage/replica_command.go:3312  [replicate,n1,s1,r5/1:/Table/1{3-4},@c420c37b00] change replicas (remove {3 3 3}): read existing descriptor range_id:5 start_key:"\225" end_key:"\226" replicas:<node_id:1 store_id:1 replica_id:1 > replicas:<node_id:2 store_id:2 replica_id:2 > next_replica_id:3 
I170301 09:52:24.366181 27137 storage/replica.go:2510  [n1,s1,r5/1:/Table/1{3-4},@c420c37b00] proposing ADD_REPLICA {NodeID:3 StoreID:3 ReplicaID:3}: [{NodeID:1 StoreID:1 ReplicaID:1} {NodeID:2 StoreID:2 ReplicaID:2} {NodeID:3 StoreID:3 ReplicaID:3}]
I170301 09:52:24.915399 1053 storage/replica_raftstorage.go:414  [replicate,n1,s1,r2/1:/Table/{0-11},@c42083e900] generated preemptive snapshot 73b251a9 at index 24
I170301 09:52:24.916163 1053 storage/store.go:3295  [replicate,n1,s1,r2/1:/Table/{0-11},@c42083e900] streamed snapshot: kv pairs: 33, log entries: 14, 0ms
I170301 09:52:24.918347 30665 storage/replica_raftstorage.go:596  [n3,s3,r2/?:{-},@c4213e0600] applying preemptive snapshot at index 24 (id=73b251a9, encoded size=22665, 1 rocksdb batches, 14 log entries)
I170301 09:52:24.919872 30665 storage/replica_raftstorage.go:604  [n3,s3,r2/?:/Table/{0-11},@c4213e0600] applied preemptive snapshot in 1ms [clear=0ms batch=0ms entries=1ms commit=0ms]
I170301 09:52:24.921109 1053 storage/replica_command.go:3312  [replicate,n1,s1,r2/1:/Table/{0-11},@c42083e900] change replicas (remove {3 3 2}): read existing descriptor range_id:2 start_key:"\210" end_key:"\223" replicas:<node_id:1 store_id:1 replica_id:1 > next_replica_id:2 
I170301 09:52:24.935231 31737 storage/replica.go:2510  [n1,s1,r2/1:/Table/{0-11},@c42083e900] proposing ADD_REPLICA {NodeID:3 StoreID:3 ReplicaID:2}: [{NodeID:1 StoreID:1 ReplicaID:1} {NodeID:3 StoreID:3 ReplicaID:2}]
I170301 09:52:24.937004 1053 storage/replica_raftstorage.go:414  [replicate,n1,s1,r2/1:/Table/{0-11},@c42083e900] generated preemptive snapshot 29f634e3 at index 28
I170301 09:52:24.937774 1053 storage/store.go:3295  [replicate,n1,s1,r2/1:/Table/{0-11},@c42083e900] streamed snapshot: kv pairs: 36, log entries: 18, 1ms
I170301 09:52:24.938391 31949 storage/replica_raftstorage.go:596  [n2,s2,r2/?:{-},@c420b79b00] applying preemptive snapshot at index 28 (id=29f634e3, encoded size=26535, 1 rocksdb batches, 18 log entries)
I170301 09:52:24.938930 31949 storage/replica_raftstorage.go:604  [n2,s2,r2/?:/Table/{0-11},@c420b79b00] applied preemptive snapshot in 0ms [clear=0ms batch=0ms entries=0ms commit=0ms]
I170301 09:52:24.941980 1053 storage/replica_command.go:3312  [replicate,n1,s1,r2/1:/Table/{0-11},@c42083e900] change replicas (remove {2 2 3}): read existing descriptor range_id:2 start_key:"\210" end_key:"\223" replicas:<node_id:1 store_id:1 replica_id:1 > replicas:<node_id:3 store_id:3 replica_id:2 > next_replica_id:3 
I170301 09:52:24.956870 33600 storage/replica.go:2510  [n1,s1,r2/1:/Table/{0-11},@c42083e900] proposing ADD_REPLICA {NodeID:2 StoreID:2 ReplicaID:3}: [{NodeID:1 StoreID:1 ReplicaID:1} {NodeID:3 StoreID:3 ReplicaID:2} {NodeID:2 StoreID:2 ReplicaID:3}]
I170301 09:52:25.155195 35492 sql/event_log.go:95  [client=127.0.0.1:55018,user=root,n1] Event: "create_database", target: 50, info: {DatabaseName:bench Statement:CREATE DATABASE bench User:root}
I170301 09:52:25.157473 1052 storage/split_queue.go:98  [split,n1,s1,r6/1:/{Table/14-Max},@c420b78600] splitting at key /Table/50/0
I170301 09:52:25.157624 1052 storage/replica_command.go:2456  [split,n1,s1,r6/1:/{Table/14-Max},@c420b78600] initiating a split of this range at key /Table/50 [r7]
I170301 09:52:25.184927 35492 sql/event_log.go:95  [client=127.0.0.1:55018,user=root,n1] Event: "create_table", target: 51, info: {TableName:bench.bank Statement:CREATE TABLE bench.bank (id INT PRIMARY KEY, balance INT, payload STRING, FAMILY (id, balance, payload)) User:root}
I170301 09:52:25.197408 1052 storage/split_queue.go:98  [split,n1,s1,r7/1:/{Table/50-Max},@c421fa2900] splitting at key /Table/51/0
I170301 09:52:25.197661 1052 storage/replica_command.go:2456  [split,n1,s1,r7/1:/{Table/50-Max},@c421fa2900] initiating a split of this range at key /Table/51 [r8]
I170301 09:52:25.229695 35492 sql/mon/mem_usage.go:510  [client=127.0.0.1:55018,user=root,n1] txn: memory usage increases to 49 KiB (+49680)
I170301 09:52:25.231386 35492 sql/mon/mem_usage.go:510  [client=127.0.0.1:55018,user=root,n1] txn: memory usage increases to 64 KiB (+140)
I170301 09:52:25.237835 35492 sql/mon/mem_usage.go:510  [client=127.0.0.1:55018,user=root,n1] txn: memory usage increases to 128 KiB (+140)
I170301 09:52:25.302784 49029 storage/replica_command.go:2456  [n1,s1,r8/1:/{Table/51-Max},@c421fa2600] initiating a split of this range at key /Table/51/1/100 [r9]
I170301 09:52:25.347279 52757 storage/replica_command.go:2456  [n1,s1,r9/1:/{Table/51/1/1…-Max},@c421fa2000] initiating a split of this range at key /Table/51/1/200 [r10]
I170301 09:52:25.385697 56436 storage/replica_command.go:2456  [n1,s1,r10/1:/{Table/51/1/2…-Max},@c421a49500] initiating a split of this range at key /Table/51/1/300 [r11]
I170301 09:52:25.397871 56552 storage/raft_transport.go:436  [n2] raft transport stream to node 3 established
I170301 09:52:25.415838 57899 storage/raft_transport.go:436  [n3] raft transport stream to node 2 established
I170301 09:52:25.434567 60647 storage/replica_command.go:2456  [n1,s1,r11/1:/{Table/51/1/3…-Max},@c420698000] initiating a split of this range at key /Table/51/1/400 [r12]
I170301 09:52:25.470144 64329 storage/replica_command.go:2456  [n1,s1,r12/1:/{Table/51/1/4…-Max},@c421446000] initiating a split of this range at key /Table/51/1/500 [r13]
I170301 09:52:25.508478 67821 storage/replica_command.go:2456  [n1,s1,r13/1:/{Table/51/1/5…-Max},@c421d98900] initiating a split of this range at key /Table/51/1/600 [r14]
I170301 09:52:25.590770 72300 storage/replica_command.go:2456  [n1,s1,r14/1:/{Table/51/1/6…-Max},@c421850f00] initiating a split of this range at key /Table/51/1/700 [r15]
I170301 09:52:25.642465 76104 storage/replica_command.go:2456  [n1,s1,r15/1:/{Table/51/1/7…-Max},@c421851800] initiating a split of this range at key /Table/51/1/800 [r16]
I170301 09:52:25.679092 79884 storage/replica_command.go:2456  [n1,s1,r16/1:/{Table/51/1/8…-Max},@c4216b7500] initiating a split of this range at key /Table/51/1/900 [r17]
I170301 09:52:25.779620 35492 sql/event_log.go:95  [client=127.0.0.1:55018,user=root,n1] Event: "create_index", target: 51, info: {TableName:bank IndexName:balance_idx Statement:CREATE INDEX balance_idx ON bench.bank (balance) User:root MutationID:1}
I170301 09:52:26.044291 35492 sql/event_log.go:95  Event: "finish_schema_change", target: 51, info: {MutationID:1}
W170301 09:52:26.151536 101 server/status/runtime.go:116  Could not parse build timestamp: parsing time "" as "2006/01/02 15:04:05": cannot parse "" as "2006"
I170301 09:52:26.153410 101 server/config.go:482  1 storage engine initialized
I170301 09:52:26.156022 101 server/node.go:443  [n?] store [n0,s0] not bootstrapped
I170301 09:52:26.162825 101 server/node.go:372  [n?] **** cluster 85060013-db80-49f4-a513-13974ca138d9 has been created
I170301 09:52:26.162888 101 server/node.go:373  [n?] **** add additional nodes by specifying --join=127.0.0.1:52371
I170301 09:52:26.165704 101 storage/store.go:1274  [n1] [n1,s1]: failed initial metrics computation: [n1,s1]: system config not yet available
I170301 09:52:26.165818 101 server/node.go:456  [n1] initialized store [n1,s1]: {Capacity:536870912 Available:536870912 RangeCount:1 LeaseCount:0}
I170301 09:52:26.165946 101 server/node.go:341  [n1] node ID 1 initialized
I170301 09:52:26.166044 101 gossip/gossip.go:293  [n1] NodeDescriptor set to node_id:1 address:<network_field:"tcp" address_field:"127.0.0.1:52371" > attrs:<> locality:<> 
I170301 09:52:26.166319 101 storage/stores.go:296  [n1] read 0 node addresses from persistent storage
I170301 09:52:26.166432 101 server/node.go:605  [n1] connecting to gossip network to verify cluster ID...
I170301 09:52:26.168057 101 server/node.go:629  [n1] node connected via gossip and verified as part of cluster "85060013-db80-49f4-a513-13974ca138d9"
I170301 09:52:26.168177 101 server/node.go:391  [n1] node=1: started with [[]=] engine(s) and attributes []
I170301 09:52:26.168416 101 sql/executor.go:337  [n1] creating distSQLPlanner with address {tcp 127.0.0.1:52371}
I170301 09:52:26.169733 108787 storage/split_queue.go:98  [split,n1,s1,r1/1:/M{in-ax},@c421850900] splitting at key /Table/0/0
I170301 09:52:26.170526 101 server/server.go:651  [n1] starting https server at 127.0.0.1:49909
I170301 09:52:26.170919 101 server/server.go:652  [n1] starting grpc/postgres server at 127.0.0.1:52371
I170301 09:52:26.170986 101 server/server.go:653  [n1] advertising CockroachDB node at 127.0.0.1:52371
I170301 09:52:26.173677 108787 storage/replica_command.go:2456  [split,n1,s1,r1/1:/M{in-ax},@c421850900] initiating a split of this range at key /Table/0 [r2]
I170301 09:52:26.183370 108850 sql/event_log.go:95  [n1] Event: "node_join", target: 1, info: {Descriptor:{NodeID:1 Address:{NetworkField:tcp AddressField:127.0.0.1:52371} Attrs: Locality:} ClusterID:85060013-db80-49f4-a513-13974ca138d9 StartedAt:1488361946168131853 LastUp:1488361946168131853}
I170301 09:52:26.200959 108787 storage/split_queue.go:98  [split,n1,s1,r2/1:/{Table/0-Max},@c422f7f800] splitting at key /Table/11/0
I170301 09:52:26.201057 108787 storage/replica_command.go:2456  [split,n1,s1,r2/1:/{Table/0-Max},@c422f7f800] initiating a split of this range at key /Table/11 [r3]
I170301 09:52:26.210796 101 sql/event_log.go:95  [n1] Event: "alter_table", target: 12, info: {TableName:eventlog Statement:ALTER TABLE system.eventlog ALTER COLUMN uniqueID SET DEFAULT uuid_v4() User:node MutationID:0 CascadeDroppedViews:[]}
I170301 09:52:26.214642 108787 storage/split_queue.go:98  [split,n1,s1,r3/1:/{Table/11-Max},@c42179f800] splitting at key /Table/12/0
I170301 09:52:26.214815 108787 storage/replica_command.go:2456  [split,n1,s1,r3/1:/{Table/11-Max},@c42179f800] initiating a split of this range at key /Table/12 [r4]
I170301 09:52:26.245425 108787 storage/split_queue.go:98  [split,n1,s1,r4/1:/{Table/12-Max},@c421ed8300] splitting at key /Table/13/0
I170301 09:52:26.245919 108787 storage/replica_command.go:2456  [split,n1,s1,r4/1:/{Table/12-Max},@c421ed8300] initiating a split of this range at key /Table/13 [r5]
I170301 09:52:26.261096 101 server/server.go:779  [n1] done ensuring all necessary migrations have run
I170301 09:52:26.261171 101 server/server.go:781  [n1] serving sql connections
I170301 09:52:26.262598 108787 storage/split_queue.go:98  [split,n1,s1,r5/1:/{Table/13-Max},@c421425800] splitting at key /Table/14/0
I170301 09:52:26.262820 108787 storage/replica_command.go:2456  [split,n1,s1,r5/1:/{Table/13-Max},@c421425800] initiating a split of this range at key /Table/14 [r6]
W170301 09:52:26.307296 101 gossip/gossip.go:1178  [n?] no incoming or outgoing connections
W170301 09:52:26.309364 101 server/status/runtime.go:116  Could not parse build timestamp: parsing time "" as "2006/01/02 15:04:05": cannot parse "" as "2006"
I170301 09:52:26.311149 101 server/config.go:482  1 storage engine initialized
I170301 09:52:26.319380 117408 gossip/client.go:131  [n?] started gossip client to 127.0.0.1:52371
I170301 09:52:26.319872 118644 gossip/server.go:214  [n1] received initial cluster-verification connection from {tcp 127.0.0.1:53324}
I170301 09:52:26.320429 101 server/node.go:443  [n?] store [n0,s0] not bootstrapped
I170301 09:52:26.320581 101 storage/stores.go:296  [n?] read 0 node addresses from persistent storage
I170301 09:52:26.320723 101 server/node.go:605  [n?] connecting to gossip network to verify cluster ID...
I170301 09:52:26.325338 118663 storage/stores.go:312  [n?] wrote 1 node addresses to persistent storage
I170301 09:52:26.325643 101 server/node.go:629  [n?] node connected via gossip and verified as part of cluster "85060013-db80-49f4-a513-13974ca138d9"
I170301 09:52:26.330617 101 kv/dist_sender.go:368  [n?] unable to determine this node's attributes for replica selection; node is most likely bootstrapping
I170301 09:52:26.332130 101 server/node.go:334  [n?] new node allocated ID 2
I170301 09:52:26.332238 101 gossip/gossip.go:293  [n2] NodeDescriptor set to node_id:2 address:<network_field:"tcp" address_field:"127.0.0.1:53324" > attrs:<> locality:<> 
I170301 09:52:26.332412 101 server/node.go:391  [n2] node=2: started with [[]=] engine(s) and attributes []
I170301 09:52:26.332487 101 sql/executor.go:337  [n2] creating distSQLPlanner with address {tcp 127.0.0.1:53324}
I170301 09:52:26.334204 101 server/server.go:651  [n2] starting https server at 127.0.0.1:46613
I170301 09:52:26.334267 101 server/server.go:652  [n2] starting grpc/postgres server at 127.0.0.1:53324
I170301 09:52:26.334702 101 server/server.go:653  [n2] advertising CockroachDB node at 127.0.0.1:53324
I170301 09:52:26.336004 119234 storage/stores.go:312  [n1] wrote 1 node addresses to persistent storage
I170301 09:52:26.340808 119073 server/node.go:586  [n2] bootstrapped store [n2,s2]
I170301 09:52:26.342508 101 server/server.go:779  [n2] done ensuring all necessary migrations have run
I170301 09:52:26.342951 101 server/server.go:781  [n2] serving sql connections
I170301 09:52:26.344715 110780 storage/replica_raftstorage.go:414  [replicate,n1,s1,r1/1:/{Min-Table/0},@c421850900] generated preemptive snapshot 5f873748 at index 46
W170301 09:52:26.348925 101 gossip/gossip.go:1178  [n?] no incoming or outgoing connections
I170301 09:52:26.352472 119077 sql/event_log.go:95  [n2] Event: "node_join", target: 2, info: {Descriptor:{NodeID:2 Address:{NetworkField:tcp AddressField:127.0.0.1:53324} Attrs: Locality:} ClusterID:85060013-db80-49f4-a513-13974ca138d9 StartedAt:1488361946332384712 LastUp:1488361946332384712}
W170301 09:52:26.361456 101 server/status/runtime.go:116  Could not parse build timestamp: parsing time "" as "2006/01/02 15:04:05": cannot parse "" as "2006"
I170301 09:52:26.367214 101 server/config.go:482  1 storage engine initialized
I170301 09:52:26.368530 110780 storage/store.go:3295  [replicate,n1,s1,r1/1:/{Min-Table/0},@c421850900] streamed snapshot: kv pairs: 390, log entries: 36, 4ms
I170301 09:52:26.370499 120667 storage/replica_raftstorage.go:596  [n2,s2,r1/?:{-},@c421fa3800] applying preemptive snapshot at index 46 (id=5f873748, encoded size=206336, 1 rocksdb batches, 36 log entries)
I170301 09:52:26.371805 120667 storage/replica_raftstorage.go:604  [n2,s2,r1/?:/{Min-Table/0},@c421fa3800] applied preemptive snapshot in 1ms [clear=0ms batch=0ms entries=0ms commit=1ms]
I170301 09:52:26.373166 110780 storage/replica_command.go:3312  [replicate,n1,s1,r1/1:/{Min-Table/0},@c421850900] change replicas (remove {2 2 2}): read existing descriptor range_id:1 start_key:"" end_key:"\210" replicas:<node_id:1 store_id:1 replica_id:1 > next_replica_id:2 
I170301 09:52:26.377427 120381 gossip/client.go:131  [n?] started gossip client to 127.0.0.1:52371
I170301 09:52:26.377840 121097 gossip/server.go:214  [n1] received initial cluster-verification connection from {tcp 127.0.0.1:35939}
I170301 09:52:26.378867 101 server/node.go:443  [n?] store [n0,s0] not bootstrapped
I170301 09:52:26.378982 101 storage/stores.go:296  [n?] read 0 node addresses from persistent storage
I170301 09:52:26.379446 101 server/node.go:605  [n?] connecting to gossip network to verify cluster ID...
I170301 09:52:26.379528 101 server/node.go:629  [n?] node connected via gossip and verified as part of cluster "85060013-db80-49f4-a513-13974ca138d9"
I170301 09:52:26.380350 121220 storage/stores.go:312  [n?] wrote 1 node addresses to persistent storage
I170301 09:52:26.381961 121220 storage/stores.go:312  [n?] wrote 2 node addresses to persistent storage
I170301 09:52:26.388062 101 kv/dist_sender.go:368  [n?] unable to determine this node's attributes for replica selection; node is most likely bootstrapping
I170301 09:52:26.388736 121827 storage/replica.go:2510  [n1,s1,r1/1:/{Min-Table/0},@c421850900] proposing ADD_REPLICA {NodeID:2 StoreID:2 ReplicaID:2}: [{NodeID:1 StoreID:1 ReplicaID:1} {NodeID:2 StoreID:2 ReplicaID:2}]
I170301 09:52:26.391149 122106 storage/raft_transport.go:436  [n2] raft transport stream to node 1 established
I170301 09:52:26.392023 110780 storage/replica_raftstorage.go:414  [replicate,n1,s1,r6/1:/{Table/14-Max},@c421a49200] generated preemptive snapshot 12532dee at index 11
I170301 09:52:26.392783 110780 storage/store.go:3295  [replicate,n1,s1,r6/1:/{Table/14-Max},@c421a49200] streamed snapshot: kv pairs: 9, log entries: 1, 0ms
I170301 09:52:26.393158 121613 storage/replica_raftstorage.go:596  [n2,s2,r6/?:{-},@c421447500] applying preemptive snapshot at index 11 (id=12532dee, encoded size=508, 1 rocksdb batches, 1 log entries)
I170301 09:52:26.393430 121613 storage/replica_raftstorage.go:604  [n2,s2,r6/?:/{Table/14-Max},@c421447500] applied preemptive snapshot in 0ms [clear=0ms batch=0ms entries=0ms commit=0ms]
I170301 09:52:26.395580 110780 storage/replica_command.go:3312  [replicate,n1,s1,r6/1:/{Table/14-Max},@c421a49200] change replicas (remove {2 2 2}): read existing descriptor range_id:6 start_key:"\226" end_key:"\377\377" replicas:<node_id:1 store_id:1 replica_id:1 > next_replica_id:2 
I170301 09:52:27.543398 101 server/node.go:334  [n?] new node allocated ID 3
I170301 09:52:27.543548 101 gossip/gossip.go:293  [n3] NodeDescriptor set to node_id:3 address:<network_field:"tcp" address_field:"127.0.0.1:35939" > attrs:<> locality:<> 
I170301 09:52:27.543829 101 server/node.go:391  [n3] node=3: started with [[]=] engine(s) and attributes []
I170301 09:52:27.544061 101 sql/executor.go:337  [n3] creating distSQLPlanner with address {tcp 127.0.0.1:35939}
I170301 09:52:27.544679 129626 storage/stores.go:312  [n1] wrote 2 node addresses to persistent storage
I170301 09:52:27.545470 129845 storage/stores.go:312  [n2] wrote 2 node addresses to persistent storage
I170301 09:52:27.548272 101 server/server.go:651  [n3] starting https server at 127.0.0.1:52031
I170301 09:52:27.548355 101 server/server.go:652  [n3] starting grpc/postgres server at 127.0.0.1:35939
I170301 09:52:27.548413 101 server/server.go:653  [n3] advertising CockroachDB node at 127.0.0.1:35939
I170301 09:52:27.554691 130438 storage/replica.go:2510  [n1,s1,r6/1:/{Table/14-Max},@c421a49200] proposing ADD_REPLICA {NodeID:2 StoreID:2 ReplicaID:2}: [{NodeID:1 StoreID:1 ReplicaID:1} {NodeID:2 StoreID:2 ReplicaID:2}]
I170301 09:52:27.561319 110780 storage/replica_raftstorage.go:414  [replicate,n1,s1,r2/1:/Table/{0-11},@c422f7f800] generated preemptive snapshot 6b9b8569 at index 25
I170301 09:52:27.568568 110780 storage/store.go:3295  [replicate,n1,s1,r2/1:/Table/{0-11},@c422f7f800] streamed snapshot: kv pairs: 34, log entries: 15, 5ms
I170301 09:52:27.569027 129196 sql/event_log.go:95  [n3] Event: "node_join", target: 3, info: {Descriptor:{NodeID:3 Address:{NetworkField:tcp AddressField:127.0.0.1:35939} Attrs: Locality:} ClusterID:85060013-db80-49f4-a513-13974ca138d9 StartedAt:1488361947543794049 LastUp:1488361947543794049}
I170301 09:52:27.570346 130995 storage/replica_raftstorage.go:596  [n2,s2,r2/?:{-},@c421b1c600] applying preemptive snapshot at index 25 (id=6b9b8569, encoded size=23293, 1 rocksdb batches, 15 log entries)
I170301 09:52:27.570434 129192 server/node.go:586  [n3] bootstrapped store [n3,s3]
I170301 09:52:27.570885 130995 storage/replica_raftstorage.go:604  [n2,s2,r2/?:/Table/{0-11},@c421b1c600] applied preemptive snapshot in 0ms [clear=0ms batch=0ms entries=0ms commit=0ms]
I170301 09:52:27.574217 110780 storage/replica_command.go:3312  [replicate,n1,s1,r2/1:/Table/{0-11},@c422f7f800] change replicas (remove {2 2 2}): read existing descriptor range_id:2 start_key:"\210" end_key:"\223" replicas:<node_id:1 store_id:1 replica_id:1 > next_replica_id:2 
I170301 09:52:27.574962 101 server/server.go:779  [n3] done ensuring all necessary migrations have run
I170301 09:52:27.575333 101 server/server.go:781  [n3] serving sql connections
I170301 09:52:27.592233 110780 storage/replica_command.go:3312  [replicate,n1,s1,r2/1:/Table/{0-11},@c422f7f800] change replicas (remove {2 2 2}): read existing descriptor range_id:2 start_key:"\210" end_key:"\223" replicas:<node_id:1 store_id:1 replica_id:1 > next_replica_id:2 
I170301 09:52:27.600043 134674 storage/replica.go:2510  [n1,s1,r2/1:/Table/{0-11},@c422f7f800] proposing ADD_REPLICA {NodeID:2 StoreID:2 ReplicaID:2}: [{NodeID:1 StoreID:1 ReplicaID:1} {NodeID:2 StoreID:2 ReplicaID:2}]
I170301 09:52:27.601661 110780 storage/replica_raftstorage.go:414  [replicate,n1,s1,r5/1:/Table/1{3-4},@c421425800] generated preemptive snapshot eef9fdbe at index 30
I170301 09:52:27.620506 110780 storage/store.go:3295  [replicate,n1,s1,r5/1:/Table/1{3-4},@c421425800] streamed snapshot: kv pairs: 71, log entries: 20, 1ms
I170301 09:52:27.621027 135199 storage/replica_raftstorage.go:596  [n3,s3,r5/?:{-},@c421d4e000] applying preemptive snapshot at index 30 (id=eef9fdbe, encoded size=31272, 1 rocksdb batches, 20 log entries)
I170301 09:52:27.621755 135199 storage/replica_raftstorage.go:604  [n3,s3,r5/?:/Table/1{3-4},@c421d4e000] applied preemptive snapshot in 1ms [clear=0ms batch=0ms entries=0ms commit=0ms]
I170301 09:52:27.622827 110780 storage/replica_command.go:3312  [replicate,n1,s1,r5/1:/Table/1{3-4},@c421425800] change replicas (remove {3 3 2}): read existing descriptor range_id:5 start_key:"\225" end_key:"\226" replicas:<node_id:1 store_id:1 replica_id:1 > next_replica_id:2 
I170301 09:52:27.632888 135964 storage/replica.go:2510  [n1,s1,r5/1:/Table/1{3-4},@c421425800] proposing ADD_REPLICA {NodeID:3 StoreID:3 ReplicaID:2}: [{NodeID:1 StoreID:1 ReplicaID:1} {NodeID:3 StoreID:3 ReplicaID:2}]
I170301 09:52:27.634779 108788 storage/replica_raftstorage.go:414  [replicate,n1,s1,r3/1:/Table/1{1-2},@c42179f800] generated preemptive snapshot 6fb17076 at index 18
I170301 09:52:27.635549 108788 storage/store.go:3295  [replicate,n1,s1,r3/1:/Table/1{1-2},@c42179f800] streamed snapshot: kv pairs: 11, log entries: 8, 0ms
I170301 09:52:27.636312 136221 storage/replica_raftstorage.go:596  [n3,s3,r3/?:{-},@c4216b6f00] applying preemptive snapshot at index 18 (id=6fb17076, encoded size=8523, 1 rocksdb batches, 8 log entries)
I170301 09:52:27.636648 136221 storage/replica_raftstorage.go:604  [n3,s3,r3/?:/Table/1{1-2},@c4216b6f00] applied preemptive snapshot in 0ms [clear=0ms batch=0ms entries=0ms commit=0ms]
I170301 09:52:27.637715 108788 storage/replica_command.go:3312  [replicate,n1,s1,r3/1:/Table/1{1-2},@c42179f800] change replicas (remove {3 3 2}): read existing descriptor range_id:3 start_key:"\223" end_key:"\224" replicas:<node_id:1 store_id:1 replica_id:1 > next_replica_id:2 
I170301 09:52:27.638073 136553 storage/raft_transport.go:436  [n3] raft transport stream to node 1 established
I170301 09:52:27.649957 137225 storage/replica.go:2510  [n1,s1,r3/1:/Table/1{1-2},@c42179f800] proposing ADD_REPLICA {NodeID:3 StoreID:3 ReplicaID:2}: [{NodeID:1 StoreID:1 ReplicaID:1} {NodeID:3 StoreID:3 ReplicaID:2}]
I170301 09:52:27.652392 110780 storage/replica_raftstorage.go:414  [replicate,n1,s1,r4/1:/Table/1{2-3},@c421ed8300] generated preemptive snapshot 37bed20f at index 24
I170301 09:52:27.653086 110780 storage/store.go:3295  [replicate,n1,s1,r4/1:/Table/1{2-3},@c421ed8300] streamed snapshot: kv pairs: 32, log entries: 14, 0ms
I170301 09:52:27.653999 136749 storage/replica_raftstorage.go:596  [n3,s3,r4/?:{-},@c423870300] applying preemptive snapshot at index 24 (id=37bed20f, encoded size=19666, 1 rocksdb batches, 14 log entries)
I170301 09:52:27.654425 136749 storage/replica_raftstorage.go:604  [n3,s3,r4/?:/Table/1{2-3},@c423870300] applied preemptive snapshot in 0ms [clear=0ms batch=0ms entries=0ms commit=0ms]
I170301 09:52:27.656247 110780 storage/replica_command.go:3312  [replicate,n1,s1,r4/1:/Table/1{2-3},@c421ed8300] change replicas (remove {3 3 2}): read existing descriptor range_id:4 start_key:"\224" end_key:"\225" replicas:<node_id:1 store_id:1 replica_id:1 > next_replica_id:2 
I170301 09:52:27.668436 138726 storage/replica.go:2510  [n1,s1,r4/1:/Table/1{2-3},@c421ed8300] proposing ADD_REPLICA {NodeID:3 StoreID:3 ReplicaID:2}: [{NodeID:1 StoreID:1 ReplicaID:1} {NodeID:3 StoreID:3 ReplicaID:2}]
I170301 09:52:27.670329 108788 storage/replica_raftstorage.go:414  [replicate,n1,s1,r4/1:/Table/1{2-3},@c421ed8300] generated preemptive snapshot 7337c12f at index 26
I170301 09:52:27.671485 108788 storage/store.go:3295  [replicate,n1,s1,r4/1:/Table/1{2-3},@c421ed8300] streamed snapshot: kv pairs: 34, log entries: 16, 1ms
I170301 09:52:27.672451 139016 storage/replica_raftstorage.go:596  [n2,s2,r4/?:{-},@c423870900] applying preemptive snapshot at index 26 (id=7337c12f, encoded size=22326, 1 rocksdb batches, 16 log entries)
I170301 09:52:27.672860 139016 storage/replica_raftstorage.go:604  [n2,s2,r4/?:/Table/1{2-3},@c423870900] applied preemptive snapshot in 0ms [clear=0ms batch=0ms entries=0ms commit=0ms]
I170301 09:52:27.678277 108788 storage/replica_command.go:3312  [replicate,n1,s1,r4/1:/Table/1{2-3},@c421ed8300] change replicas (remove {2 2 3}): read existing descriptor range_id:4 start_key:"\224" end_key:"\225" replicas:<node_id:1 store_id:1 replica_id:1 > replicas:<node_id:3 store_id:3 replica_id:2 > next_replica_id:3 
I170301 09:52:27.688117 140203 storage/replica.go:2510  [n1,s1,r4/1:/Table/1{2-3},@c421ed8300] proposing ADD_REPLICA {NodeID:2 StoreID:2 ReplicaID:3}: [{NodeID:1 StoreID:1 ReplicaID:1} {NodeID:3 StoreID:3 ReplicaID:2} {NodeID:2 StoreID:2 ReplicaID:3}]
I170301 09:52:27.690518 108788 storage/replica_raftstorage.go:414  [replicate,n1,s1,r3/1:/Table/1{1-2},@c42179f800] generated preemptive snapshot 7bd2b8d5 at index 21
I170301 09:52:27.691148 108788 storage/store.go:3295  [replicate,n1,s1,r3/1:/Table/1{1-2},@c42179f800] streamed snapshot: kv pairs: 12, log entries: 11, 0ms
I170301 09:52:27.694303 140462 storage/replica_raftstorage.go:596  [n2,s2,r3/?:{-},@c421b1d800] applying preemptive snapshot at index 21 (id=7bd2b8d5, encoded size=11491, 1 rocksdb batches, 11 log entries)
I170301 09:52:27.694826 140462 storage/replica_raftstorage.go:604  [n2,s2,r3/?:/Table/1{1-2},@c421b1d800] applied preemptive snapshot in 0ms [clear=0ms batch=0ms entries=0ms commit=0ms]
I170301 09:52:27.696908 108788 storage/replica_command.go:3312  [replicate,n1,s1,r3/1:/Table/1{1-2},@c42179f800] change replicas (remove {2 2 3}): read existing descriptor range_id:3 start_key:"\223" end_key:"\224" replicas:<node_id:1 store_id:1 replica_id:1 > replicas:<node_id:3 store_id:3 replica_id:2 > next_replica_id:3 
I170301 09:52:27.711462 142098 storage/replica.go:2510  [n1,s1,r3/1:/Table/1{1-2},@c42179f800] proposing ADD_REPLICA {NodeID:2 StoreID:2 ReplicaID:3}: [{NodeID:1 StoreID:1 ReplicaID:1} {NodeID:3 StoreID:3 ReplicaID:2} {NodeID:2 StoreID:2 ReplicaID:3}]
I170301 09:52:27.715028 108788 storage/replica_raftstorage.go:414  [replicate,n1,s1,r2/1:/Table/{0-11},@c422f7f800] generated preemptive snapshot 42b31013 at index 30
I170301 09:52:27.716747 108788 storage/store.go:3295  [replicate,n1,s1,r2/1:/Table/{0-11},@c422f7f800] streamed snapshot: kv pairs: 35, log entries: 20, 1ms
I170301 09:52:27.717441 141564 storage/replica_raftstorage.go:596  [n3,s3,r2/?:{-},@c42238ac00] applying preemptive snapshot at index 30 (id=42b31013, encoded size=28232, 1 rocksdb batches, 20 log entries)
I170301 09:52:27.717911 141564 storage/replica_raftstorage.go:604  [n3,s3,r2/?:/Table/{0-11},@c42238ac00] applied preemptive snapshot in 0ms [clear=0ms batch=0ms entries=0ms commit=0ms]
I170301 09:52:27.719707 108788 storage/replica_command.go:3312  [replicate,n1,s1,r2/1:/Table/{0-11},@c422f7f800] change replicas (remove {3 3 3}): read existing descriptor range_id:2 start_key:"\210" end_key:"\223" replicas:<node_id:1 store_id:1 replica_id:1 > replicas:<node_id:2 store_id:2 replica_id:2 > next_replica_id:3 
I170301 09:52:27.735699 143834 storage/replica.go:2510  [n1,s1,r2/1:/Table/{0-11},@c422f7f800] proposing ADD_REPLICA {NodeID:3 StoreID:3 ReplicaID:3}: [{NodeID:1 StoreID:1 ReplicaID:1} {NodeID:2 StoreID:2 ReplicaID:2} {NodeID:3 StoreID:3 ReplicaID:3}]
I170301 09:52:27.738928 110780 storage/queue.go:693  [n1,replicate] purgatory is now empty
I170301 09:52:27.739352 108788 storage/replica_raftstorage.go:414  [replicate,n1,s1,r6/1:/{Table/14-Max},@c421a49200] generated preemptive snapshot 06d7bd0d at index 16
I170301 09:52:27.741460 108788 storage/store.go:3295  [replicate,n1,s1,r6/1:/{Table/14-Max},@c421a49200] streamed snapshot: kv pairs: 11, log entries: 6, 0ms
I170301 09:52:27.741942 144497 storage/replica_raftstorage.go:596  [n3,s3,r6/?:{-},@c4238c6300] applying preemptive snapshot at index 16 (id=06d7bd0d, encoded size=4695, 1 rocksdb batches, 6 log entries)
I170301 09:52:27.742268 144497 storage/replica_raftstorage.go:604  [n3,s3,r6/?:/{Table/14-Max},@c4238c6300] applied preemptive snapshot in 0ms [clear=0ms batch=0ms entries=0ms commit=0ms]
I170301 09:52:27.744145 108788 storage/replica_command.go:3312  [replicate,n1,s1,r6/1:/{Table/14-Max},@c421a49200] change replicas (remove {3 3 3}): read existing descriptor range_id:6 start_key:"\226" end_key:"\377\377" replicas:<node_id:1 store_id:1 replica_id:1 > replicas:<node_id:2 store_id:2 replica_id:2 > next_replica_id:3 
I170301 09:52:27.762017 145786 storage/replica.go:2510  [n1,s1,r6/1:/{Table/14-Max},@c421a49200] proposing ADD_REPLICA {NodeID:3 StoreID:3 ReplicaID:3}: [{NodeID:1 StoreID:1 ReplicaID:1} {NodeID:2 StoreID:2 ReplicaID:2} {NodeID:3 StoreID:3 ReplicaID:3}]
I170301 09:52:27.766449 108788 storage/replica_raftstorage.go:414  [replicate,n1,s1,r1/1:/{Min-Table/0},@c421850900] generated preemptive snapshot 260e7695 at index 79
I170301 09:52:27.790272 108788 storage/store.go:3295  [replicate,n1,s1,r1/1:/{Min-Table/0},@c421850900] streamed snapshot: kv pairs: 840, log entries: 69, 23ms
I170301 09:52:27.794872 146355 storage/replica_raftstorage.go:596  [n3,s3,r1/?:{-},@c421b1d500] applying preemptive snapshot at index 79 (id=260e7695, encoded size=450993, 1 rocksdb batches, 69 log entries)
I170301 09:52:27.797447 146355 storage/replica_raftstorage.go:604  [n3,s3,r1/?:/{Min-Table/0},@c421b1d500] applied preemptive snapshot in 2ms [clear=0ms batch=1ms entries=1ms commit=1ms]
I170301 09:52:27.798734 108788 storage/replica_command.go:3312  [replicate,n1,s1,r1/1:/{Min-Table/0},@c421850900] change replicas (remove {3 3 3}): read existing descriptor range_id:1 start_key:"" end_key:"\210" replicas:<node_id:1 store_id:1 replica_id:1 > replicas:<node_id:2 store_id:2 replica_id:2 > next_replica_id:3 
I170301 09:52:27.807135 148162 storage/replica.go:2510  [n1,s1,r1/1:/{Min-Table/0},@c421850900] proposing ADD_REPLICA {NodeID:3 StoreID:3 ReplicaID:3}: [{NodeID:1 StoreID:1 ReplicaID:1} {NodeID:2 StoreID:2 ReplicaID:2} {NodeID:3 StoreID:3 ReplicaID:3}]
I170301 09:52:27.816141 108788 storage/replica_raftstorage.go:414  [replicate,n1,s1,r5/1:/Table/1{3-4},@c421425800] generated preemptive snapshot eeccd560 at index 49
I170301 09:52:27.817066 108788 storage/store.go:3295  [replicate,n1,s1,r5/1:/Table/1{3-4},@c421425800] streamed snapshot: kv pairs: 97, log entries: 39, 1ms
I170301 09:52:27.819644 148951 storage/replica_raftstorage.go:596  [n2,s2,r5/?:{-},@c42146c300] applying preemptive snapshot at index 49 (id=eeccd560, encoded size=63011, 1 rocksdb batches, 39 log entries)
I170301 09:52:27.820384 148951 storage/replica_raftstorage.go:604  [n2,s2,r5/?:/Table/1{3-4},@c42146c300] applied preemptive snapshot in 1ms [clear=0ms batch=0ms entries=0ms commit=0ms]
I170301 09:52:27.824180 108788 storage/replica_command.go:3312  [replicate,n1,s1,r5/1:/Table/1{3-4},@c421425800] change replicas (remove {2 2 3}): read existing descriptor range_id:5 start_key:"\225" end_key:"\226" replicas:<node_id:1 store_id:1 replica_id:1 > replicas:<node_id:3 store_id:3 replica_id:2 > next_replica_id:3 
I170301 09:52:27.835246 149840 storage/replica.go:2510  [n1,s1,r5/1:/Table/1{3-4},@c421425800] proposing ADD_REPLICA {NodeID:2 StoreID:2 ReplicaID:3}: [{NodeID:1 StoreID:1 ReplicaID:1} {NodeID:3 StoreID:3 ReplicaID:2} {NodeID:2 StoreID:2 ReplicaID:3}]
I170301 09:52:27.995812 152014 sql/event_log.go:95  [client=127.0.0.1:34621,user=root,n1] Event: "create_database", target: 50, info: {DatabaseName:other Statement:CREATE DATABASE other User:root}
I170301 09:52:27.998673 108787 storage/split_queue.go:98  [split,n1,s1,r6/1:/{Table/14-Max},@c421a49200] splitting at key /Table/50/0
I170301 09:52:27.998765 108787 storage/replica_command.go:2456  [split,n1,s1,r6/1:/{Table/14-Max},@c421a49200] initiating a split of this range at key /Table/50 [r7]
I170301 09:52:28.046972 152014 sql/event_log.go:95  [client=127.0.0.1:34621,user=root,n1] Event: "create_table", target: 51, info: {TableName:other.empty Statement:CREATE TABLE other.empty (a INT PRIMARY KEY) User:root}
I170301 09:52:28.048514 108787 storage/split_queue.go:98  [split,n1,s1,r7/1:/{Table/50-Max},@c421428900] splitting at key /Table/51/0
I170301 09:52:28.048605 108787 storage/replica_command.go:2456  [split,n1,s1,r7/1:/{Table/50-Max},@c421428900] initiating a split of this range at key /Table/51 [r8]
I170301 09:52:28.105252 152014 sql/event_log.go:95  [client=127.0.0.1:34621,user=root,n1] Event: "create_database", target: 52, info: {DatabaseName:bench Statement:CREATE DATABASE bench User:root}
I170301 09:52:28.121044 108787 storage/split_queue.go:98  [split,n1,s1,r8/1:/{Table/51-Max},@c424317500] splitting at key /Table/52/0
I170301 09:52:28.121215 108787 storage/replica_command.go:2456  [split,n1,s1,r8/1:/{Table/51-Max},@c424317500] initiating a split of this range at key /Table/52 [r9]
I170301 09:52:28.176499 152014 sql/event_log.go:95  [client=127.0.0.1:34621,user=root,n1] Event: "create_table", target: 53, info: {TableName:bench.empty Statement:CREATE TABLE bench.empty (a INT PRIMARY KEY) User:root}
I170301 09:52:28.181480 171659 storage/raft_transport.go:436  [n3] raft transport stream to node 2 established
I170301 09:52:28.187261 108787 storage/split_queue.go:98  [split,n1,s1,r9/1:/{Table/52-Max},@c421ed8f00] splitting at key /Table/53/0
I170301 09:52:28.187357 108787 storage/replica_command.go:2456  [split,n1,s1,r9/1:/{Table/52-Max},@c421ed8f00] initiating a split of this range at key /Table/53 [r10]
I170301 09:52:28.206344 173115 storage/raft_transport.go:436  [n2] raft transport stream to node 3 established
I170301 09:52:28.221270 175961 storage/replica_command.go:2456  [n1,s1,r9/1:/{Table/52-Max},@c421ed8f00] initiating a split of this range at key /Table/54/1/500 [r11]
I170301 09:52:28.318456 179631 storage/replica_command.go:2456  [n1,s1,r10/1:/{Table/53-Max},@c424244c00] initiating a split of this range at key /Table/54/1/500 [r12]
I170301 09:52:28.355350 182335 storage/replica_command.go:2456  [n1,s1,r12/1:/{Table/54/1/5…-Max},@c424192900] initiating a split of this range at key /Table/54/1/800 [r13]
I170301 09:52:28.359352 182108 storage/replica_command.go:2456  [n1,s1,r10/1:/Table/5{3-4/1/500},@c424244c00] initiating a split of this range at key /Table/54/1/200 [r14]
I170301 09:52:28.414553 186975 storage/replica_command.go:2456  [n1,s1,r10/1:/Table/5{3-4/1/200},@c424244c00] initiating a split of this range at key /Table/54/1/100 [r15]
I170301 09:52:28.422135 187435 storage/replica_command.go:2456  [n1,s1,r14/1:/Table/54/1/{200-500},@c423a2c300] initiating a split of this range at key /Table/54/1/400 [r16]
I170301 09:52:28.469927 191893 storage/replica_command.go:2456  [n1,s1,r12/1:/Table/54/1/{500-800},@c424192900] initiating a split of this range at key /Table/54/1/700 [r17]
I170301 09:52:28.475612 192967 storage/replica_command.go:2456  [n1,s1,r13/1:/{Table/54/1/8…-Max},@c423db7500] initiating a split of this range at key /Table/54/2 [r18]
I170301 09:52:28.513007 196271 storage/replica_command.go:2456  [n1,s1,r10/1:/Table/5{3-4/1/100},@c424244c00] initiating a split of this range at key /Table/54/1 [r19]
I170301 09:52:28.522688 195945 storage/replica_command.go:2456  [n1,s1,r14/1:/Table/54/1/{200-400},@c423a2c300] initiating a split of this range at key /Table/54/1/300 [r20]
I170301 09:52:28.591547 203976 storage/replica_command.go:2456  [n1,s1,r13/1:/Table/54/{1/800-2},@c423db7500] initiating a split of this range at key /Table/54/1/900 [r21]
I170301 09:52:28.597757 204632 storage/replica_command.go:2456  [n1,s1,r12/1:/Table/54/1/{500-700},@c424192900] initiating a split of this range at key /Table/54/1/600 [r22]
I170301 09:52:28.766954 217247 storage/engine/rocksdb.go:345  opening rocksdb instance at "/go/src/github.com/cockroachdb/cockroach/artifacts/RocksDBSstFileReader916201543"
I170301 09:52:28.768137 217272 storage/engine/rocksdb.go:345  opening rocksdb instance at "/go/src/github.com/cockroachdb/cockroach/artifacts/RocksDBSstFileReader873574417"
I170301 09:52:28.768375 218202 storage/engine/rocksdb.go:345  opening rocksdb instance at "/go/src/github.com/cockroachdb/cockroach/artifacts/RocksDBSstFileReader522496572"
I170301 09:52:28.769331 217241 storage/engine/rocksdb.go:345  opening rocksdb instance at "/go/src/github.com/cockroachdb/cockroach/artifacts/RocksDBSstFileReader953705722"
I170301 09:52:28.770834 218243 storage/engine/rocksdb.go:345  opening rocksdb instance at "/go/src/github.com/cockroachdb/cockroach/artifacts/RocksDBSstFileReader217809003"
I170301 09:52:29.029119 218202 storage/engine/rocksdb.go:410  closing rocksdb instance at "/go/src/github.com/cockroachdb/cockroach/artifacts/RocksDBSstFileReader522496572"
I170301 09:52:29.029952 217833 storage/engine/rocksdb.go:345  opening rocksdb instance at "/go/src/github.com/cockroachdb/cockroach/artifacts/RocksDBSstFileReader765232846"
I170301 09:52:29.038389 217241 storage/engine/rocksdb.go:410  closing rocksdb instance at "/go/src/github.com/cockroachdb/cockroach/artifacts/RocksDBSstFileReader953705722"
I170301 09:52:29.041165 218243 storage/engine/rocksdb.go:410  closing rocksdb instance at "/go/src/github.com/cockroachdb/cockroach/artifacts/RocksDBSstFileReader217809003"
I170301 09:52:29.041398 217247 storage/engine/rocksdb.go:410  closing rocksdb instance at "/go/src/github.com/cockroachdb/cockroach/artifacts/RocksDBSstFileReader916201543"
I170301 09:52:29.046799 218280 storage/engine/rocksdb.go:345  opening rocksdb instance at "/go/src/github.com/cockroachdb/cockroach/artifacts/RocksDBSstFileReader024853461"
I170301 09:52:29.049348 218032 storage/engine/rocksdb.go:345  opening rocksdb instance at "/go/src/github.com/cockroachdb/cockroach/artifacts/RocksDBSstFileReader139115312"
I170301 09:52:29.050083 219034 storage/engine/rocksdb.go:345  opening rocksdb instance at "/go/src/github.com/cockroachdb/cockroach/artifacts/RocksDBSstFileReader809882319"
I170301 09:52:29.129384 217272 storage/engine/rocksdb.go:410  closing rocksdb instance at "/go/src/github.com/cockroachdb/cockroach/artifacts/RocksDBSstFileReader873574417"
I170301 09:52:29.130195 219100 storage/engine/rocksdb.go:345  opening rocksdb instance at "/go/src/github.com/cockroachdb/cockroach/artifacts/RocksDBSstFileReader240308194"
I170301 09:52:29.260882 217833 storage/engine/rocksdb.go:410  closing rocksdb instance at "/go/src/github.com/cockroachdb/cockroach/artifacts/RocksDBSstFileReader765232846"
I170301 09:52:29.261452 218892 storage/engine/rocksdb.go:345  opening rocksdb instance at "/go/src/github.com/cockroachdb/cockroach/artifacts/RocksDBSstFileReader490344921"
E170301 09:52:29.281004 230260 ccl/storageccl/import.go:98  [n1,s1,r22/1:/Table/54/1/{600-700},@c423db6300] writebatch [/Table/54/1/600/0,/Table/54/1/699/0/NULL): failed to send RPC: sending to all 3 replicas failed; last error: rpc error: code = 1 desc = context canceled
I170301 09:52:29.281096 219034 storage/engine/rocksdb.go:410  closing rocksdb instance at "/go/src/github.com/cockroachdb/cockroach/artifacts/RocksDBSstFileReader809882319"
I170301 09:52:29.284266 218032 storage/engine/rocksdb.go:410  closing rocksdb instance at "/go/src/github.com/cockroachdb/cockroach/artifacts/RocksDBSstFileReader139115312"
I170301 09:52:29.286185 218280 storage/engine/rocksdb.go:410  closing rocksdb instance at "/go/src/github.com/cockroachdb/cockroach/artifacts/RocksDBSstFileReader024853461"
I170301 09:52:29.422110 218892 storage/engine/rocksdb.go:410  closing rocksdb instance at "/go/src/github.com/cockroachdb/cockroach/artifacts/RocksDBSstFileReader490344921"
I170301 09:52:29.567285 219100 storage/engine/rocksdb.go:410  closing rocksdb instance at "/go/src/github.com/cockroachdb/cockroach/artifacts/RocksDBSstFileReader240308194"
W170301 09:52:29.574363 136484 storage/raft_transport.go:442  [n1] raft transport stream to node 3 failed: rpc error: code = 13 desc = transport is closing
W170301 09:52:29.574748 136553 storage/raft_transport.go:442  [n3] raft transport stream to node 1 failed: rpc error: code = 13 desc = transport is closing
W170301 09:52:29.574858 171659 storage/raft_transport.go:442  [n3] raft transport stream to node 2 failed: rpc error: code = 13 desc = transport is closing
I170301 09:52:29.575242 109149 vendor/google.golang.org/grpc/transport/http2_server.go:323  transport: http2Server.HandleStreams failed to read frame: read tcp 127.0.0.1:52371->127.0.0.1:34577: use of closed network connection
W170301 09:52:29.575592 173115 storage/raft_transport.go:442  [n2] raft transport stream to node 3 failed: rpc error: code = 13 desc = transport is closing
W170301 09:52:29.575680 121954 storage/raft_transport.go:442  [n1] raft transport stream to node 2 failed: rpc error: code = 13 desc = transport is closing
I170301 09:52:29.576083 120411 vendor/google.golang.org/grpc/transport/http2_server.go:323  transport: http2Server.HandleStreams failed to read frame: read tcp 127.0.0.1:52371->127.0.0.1:34582: use of closed network connection
I170301 09:52:29.576169 118508 vendor/google.golang.org/grpc/transport/http2_server.go:323  transport: http2Server.HandleStreams failed to read frame: read tcp 127.0.0.1:52371->127.0.0.1:34579: use of closed network connection
W170301 09:52:29.576329 122106 storage/raft_transport.go:442  [n2] raft transport stream to node 1 failed: rpc error: code = 13 desc = transport is closing
W170301 09:52:29.584829 57899 storage/raft_transport.go:442  [n3] raft transport stream to node 2 failed: rpc error: code = 13 desc = transport is closing
W170301 09:52:29.585225 16024 storage/raft_transport.go:442  [n1] raft transport stream to node 3 failed: rpc error: code = 13 desc = transport is closing
W170301 09:52:29.585287 56552 storage/raft_transport.go:442  [n2] raft transport stream to node 3 failed: rpc error: code = 13 desc = transport is closing
W170301 09:52:29.585348 16126 storage/raft_transport.go:442  [n3] raft transport stream to node 1 failed: rpc error: code = 13 desc = transport is closing
W170301 09:52:29.585398 13190 storage/raft_transport.go:442  [n1] raft transport stream to node 2 failed: rpc error: code = 13 desc = transport is closing
W170301 09:52:29.585559 13296 storage/raft_transport.go:442  [n2] raft transport stream to node 1 failed: rpc error: code = 13 desc = transport is closing
I170301 09:52:29.585650 10300 vendor/google.golang.org/grpc/transport/http2_server.go:323  transport: http2Server.HandleStreams failed to read frame: read tcp 127.0.0.1:50044->127.0.0.1:54986: use of closed network connection
I170301 09:52:29.585694 6737 vendor/google.golang.org/grpc/transport/http2_server.go:323  transport: http2Server.HandleStreams failed to read frame: read tcp 127.0.0.1:50044->127.0.0.1:54983: use of closed network connection
I170301 09:52:29.585736 1315 vendor/google.golang.org/grpc/transport/http2_server.go:323  transport: http2Server.HandleStreams failed to read frame: read tcp 127.0.0.1:50044->127.0.0.1:54980: use of closed network connection
	sql_runner.go:52: error executing 'RESTORE DATABASE bench FROM '/go/src/github.com/cockroachdb/cockroach/artifacts/TestBackupRestoreLocal934140178'': pq: importing 11 ranges: first of 1 errors: import can only be called on empty ranges
```

### LINKED ISSUE #13893: ccl/sqlccl: TestBackupAsOfSystemTime failed under stress
SHA: https://github.com/cockroachdb/cockroach/commits/066b9480d6efa34dd2ad440b5a2b6d3cc9686441

Parameters:
```
COCKROACH_PROPOSER_EVALUATED_KV=true
TAGS=
GOFLAGS=-race
```

Stress build found a failed test: https://teamcity.cockroachdb.com/viewLog.html?buildId=168413&tab=buildLog

```
W170304 08:29:09.127749 20622 server/status/runtime.go:116  Could not parse build timestamp: parsing time "" as "2006/01/02 15:04:05": cannot parse "" as "2006"
I170304 08:29:09.140668 20622 server/config.go:482  1 storage engine 4 runs completed, 1 failures, over 1m43s
initialized
I170304 08:29:09.141868 20622 server/node.go:443  [n?] store [n0,s0] not bootstrapped
I170304 08:29:09.166105 20622 server/node.go:372  [n?] **** cluster e450285f-b6fd-4b83-b773-2b55809bc2f9 has been created
I170304 08:29:09.166208 20622 server/node.go:373  [n?] **** add additional nodes by specifying --join=127.0.0.1:36734
I170304 08:29:09.189366 20601 storage/split_queue.go:98  [split,n1,s1,r1/1:/M{in-ax},@c423dcd180] splitting at key /Table/0/0
I170304 08:29:09.189618 20622 server/node.go:456  [n1] initialized store [n1,s1]: {Capacity:536870912 Available:536870912 RangeCount:1 LeaseCount:1}
I170304 08:29:09.189797 20622 server/node.go:341  [n1] node ID 1 initialized
I170304 08:29:09.190000 20622 gossip/gossip.go:293  [n1] NodeDescriptor set to node_id:1 address:<network_field:"tcp" address_field:"127.0.0.1:36734" > attrs:<> locality:<> 
I170304 08:29:09.205029 20601 storage/replica_command.go:2456  [split,n1,s1,r1/1:/M{in-ax},@c423dcd180] initiating a split of this range at key /Table/0 [r2]
I170304 08:29:09.208710 20622 storage/stores.go:296  [n1] read 0 node addresses from persistent storage
I170304 08:29:09.210022 20622 server/node.go:605  [n1] connecting to gossip network to verify cluster ID...
I170304 08:29:09.210142 20622 server/node.go:629  [n1] node connected via gossip and verified as part of cluster "e450285f-b6fd-4b83-b773-2b55809bc2f9"
I170304 08:29:09.210565 20622 server/node.go:391  [n1] node=1: started with [[]=] engine(s) and attributes []
I170304 08:29:09.228306 20622 sql/executor.go:337  [n1] creating distSQLPlanner with address {tcp 127.0.0.1:36734}
I170304 08:29:09.248855 20712 sql/event_log.go:95  [n1] Event: "node_join", target: 1, info: {Descriptor:{NodeID:1 Address:{NetworkField:tcp AddressField:127.0.0.1:36734} Attrs: Locality:} ClusterID:e450285f-b6fd-4b83-b773-2b55809bc2f9 StartedAt:1488616149210177619 LastUp:1488616149210177619}
E170304 08:29:09.306539 20602 storage/queue.go:628  [replicate,n1,s1,r1/1:/{Min-Table/0},@c423dcd180] range requires a replication change, but lacks a quorum of live replicas (0/1)
I170304 08:29:09.322236 20601 storage/split_queue.go:98  [split,n1,s1,r2/1:/{Table/0-Max},@c42483a380] splitting at key /Table/11/0
I170304 08:29:09.323178 20601 storage/replica_command.go:2456  [split,n1,s1,r2/1:/{Table/0-Max},@c42483a380] initiating a split of this range at key /Table/11 [r3]
I170304 08:29:09.351145 20622 server/server.go:651  [n1] starting https server at 127.0.0.1:53577
I170304 08:29:09.351238 20622 server/server.go:652  [n1] starting grpc/postgres server at 127.0.0.1:36734
I170304 08:29:09.351275 20622 server/server.go:653  [n1] advertising CockroachDB node at 127.0.0.1:36734
I170304 08:29:09.641640 20601 storage/split_queue.go:98  [split,n1,s1,r3/1:/{Table/11-Max},@c422d10380] splitting at key /Table/12/0
I170304 08:29:09.641858 20601 storage/replica_command.go:2456  [split,n1,s1,r3/1:/{Table/11-Max},@c422d10380] initiating a split of this range at key /Table/12 [r4]
I170304 08:29:09.733062 20622 sql/event_log.go:95  [n1] Event: "alter_table", target: 12, info: {TableName:eventlog Statement:ALTER TABLE system.eventlog ALTER COLUMN uniqueID SET DEFAULT uuid_v4() User:node MutationID:0 CascadeDroppedViews:[]}
I170304 08:29:09.769666 20601 storage/split_queue.go:98  [split,n1,s1,r4/1:/{Table/12-Max},@c42166b880] splitting at key /Table/13/0
I170304 08:29:09.769886 20601 storage/replica_command.go:2456  [split,n1,s1,r4/1:/{Table/12-Max},@c42166b880] initiating a split of this range at key /Table/13 [r5]
I170304 08:29:09.888729 20601 storage/split_queue.go:98  [split,n1,s1,r5/1:/{Table/13-Max},@c420758000] splitting at key /Table/14/0
I170304 08:29:09.888952 20601 storage/replica_command.go:2456  [split,n1,s1,r5/1:/{Table/13-Max},@c420758000] initiating a split of this range at key /Table/14 [r6]
I170304 08:29:09.906458 20622 server/server.go:779  [n1] done ensuring all necessary migrations have run
I170304 08:29:09.906594 20622 server/server.go:781  [n1] serving sql connections
W170304 08:29:10.170563 20622 gossip/gossip.go:1178  [n?] no incoming or outgoing connections
W170304 08:29:10.195017 20622 server/status/runtime.go:116  Could not parse build timestamp: parsing time "" as "2006/01/02 15:04:05": cannot parse "" as "2006"
I170304 08:29:10.200956 20622 server/config.go:482  1 storage engine initialized
I170304 08:29:10.227842 20622 server/node.go:443  [n?] store [n0,s0] not bootstrapped
I170304 08:29:10.227955 20622 storage/stores.go:296  [n?] read 0 node addresses from persistent storage
I170304 08:29:10.228048 20622 server/node.go:605  [n?] connecting to gossip network to verify cluster ID...
I170304 08:29:10.301657 20827 gossip/client.go:131  [n?] started gossip client to 127.0.0.1:36734
I170304 08:29:10.303376 20978 gossip/server.go:214  [n1] received initial cluster-verification connection from {tcp 127.0.0.1:49131}
I170304 08:29:10.305937 20622 server/node.go:629  [n?] node connected via gossip and verified as part of cluster "e450285f-b6fd-4b83-b773-2b55809bc2f9"
I170304 08:29:10.308910 20909 storage/stores.go:312  [n?] wrote 1 node addresses to persistent storage
I170304 08:29:10.317350 20622 kv/dist_sender.go:368  [n?] unable to determine this node's attributes for replica selection; node is most likely bootstrapping
I170304 08:29:10.320943 20622 server/node.go:334  [n?] new node allocated ID 2
I170304 08:29:10.321248 20622 gossip/gossip.go:293  [n2] NodeDescriptor set to node_id:2 address:<network_field:"tcp" address_field:"127.0.0.1:49131" > attrs:<> locality:<> 
I170304 08:29:10.322046 20622 server/node.go:391  [n2] node=2: started with [[]=] engine(s) and attributes []
I170304 08:29:10.322695 20622 sql/executor.go:337  [n2] creating distSQLPlanner with address {tcp 127.0.0.1:49131}
I170304 08:29:10.340228 20917 storage/stores.go:312  [n1] wrote 1 node addresses to persistent storage
I170304 08:29:10.363219 20997 sql/event_log.go:95  [n2] Event: "node_join", target: 2, info: {Descriptor:{NodeID:2 Address:{NetworkField:tcp AddressField:127.0.0.1:49131} Attrs: Locality:} ClusterID:e450285f-b6fd-4b83-b773-2b55809bc2f9 StartedAt:1488616150321725220 LastUp:1488616150321725220}
I170304 08:29:10.364177 20622 server/server.go:651  [n2] starting https server at 127.0.0.1:54468
I170304 08:29:10.364271 20622 server/server.go:652  [n2] starting grpc/postgres server at 127.0.0.1:49131
I170304 08:29:10.364330 20622 server/server.go:653  [n2] advertising CockroachDB node at 127.0.0.1:49131
I170304 08:29:10.385743 20622 server/server.go:779  [n2] done ensuring all necessary migrations have run
I170304 08:29:10.385860 20622 server/server.go:781  [n2] serving sql connections
I170304 08:29:10.388897 20994 server/node.go:586  [n2] bootstrapped store [n2,s2]
I170304 08:29:10.460724 20446 storage/replica_raftstorage.go:414  [replicate,n1,s1,r1/1:/{Min-Table/0},@c423dcd180] generated preemptive snapshot 8aafe495 at index 47
W170304 08:29:10.566892 20622 gossip/gossip.go:1178  [n?] no incoming or outgoing connections
W170304 08:29:10.633214 20622 server/status/runtime.go:116  Could not parse build timestamp: parsing time "" as "2006/01/02 15:04:05": cannot parse "" as "2006"
I170304 08:29:10.647683 20622 server/config.go:482  1 storage engine initialized
I170304 08:29:10.656492 20622 server/node.go:443  [n?] store [n0,s0] not bootstrapped
I170304 08:29:10.656612 20622 storage/stores.go:296  [n?] read 0 node addresses from persistent storage
I170304 08:29:10.656743 20622 server/node.go:605  [n?] connecting to gossip network to verify cluster ID...
I170304 08:29:10.662114 20446 storage/store.go:3295  [replicate,n1,s1,r1/1:/{Min-Table/0},@c423dcd180] streamed snapshot: kv pairs: 392, log entries: 37, 26ms
I170304 08:29:10.664525 21047 storage/replica_raftstorage.go:596  [n2,s2,r1/?:{-},@c420b28e00] applying preemptive snapshot at index 47 (id=8aafe495, encoded size=205728, 1 rocksdb batches, 37 log entries)
I170304 08:29:10.670290 21047 storage/replica_raftstorage.go:604  [n2,s2,r1/?:/{Min-Table/0},@c420b28e00] applied preemptive snapshot in 6ms [clear=0ms batch=0ms entries=4ms commit=1ms]
I170304 08:29:10.673430 20446 storage/replica_command.go:3312  [replicate,n1,s1,r1/1:/{Min-Table/0},@c423dcd180] change replicas (remove {2 2 2}): read existing descriptor range_id:1 start_key:"" end_key:"\210" replicas:<node_id:1 store_id:1 replica_id:1 > next_replica_id:2 
I170304 08:29:10.713961 21061 storage/replica.go:2510  [n1,s1,r1/1:/{Min-Table/0},@c423dcd180] proposing ADD_REPLICA {NodeID:2 StoreID:2 ReplicaID:2}: [{NodeID:1 StoreID:1 ReplicaID:1} {NodeID:2 StoreID:2 ReplicaID:2}]
I170304 08:29:10.765627 20446 storage/replica_raftstorage.go:414  [replicate,n1,s1,r3/1:/Table/1{1-2},@c422d10380] generated preemptive snapshot b8c245a1 at index 17
I170304 08:29:10.770210 20977 storage/raft_transport.go:436  [n2] raft transport stream to node 1 established
I170304 08:29:10.781781 20446 storage/store.go:3295  [replicate,n1,s1,r3/1:/Table/1{1-2},@c422d10380] streamed snapshot: kv pairs: 10, log entries: 7, 3ms
I170304 08:29:10.783431 21088 storage/replica_raftstorage.go:596  [n2,s2,r3/?:{-},@c423927c00] applying preemptive snapshot at index 17 (id=b8c245a1, encoded size=9368, 1 rocksdb batches, 7 log entries)
I170304 08:29:10.784742 21088 storage/replica_raftstorage.go:604  [n2,s2,r3/?:/Table/1{1-2},@c423927c00] applied preemptive snapshot in 1ms [clear=0ms batch=0ms entries=0ms commit=0ms]
I170304 08:29:10.791298 20929 gossip/client.go:131  [n?] started gossip client to 127.0.0.1:36734
I170304 08:29:10.793316 20446 storage/replica_command.go:3312  [replicate,n1,s1,r3/1:/Table/1{1-2},@c422d10380] change replicas (remove {2 2 2}): read existing descriptor range_id:3 start_key:"\223" end_key:"\224" replicas:<node_id:1 store_id:1 replica_id:1 > next_replica_id:2 
I170304 08:29:10.807147 21095 gossip/server.go:214  [n1] received initial cluster-verification connection from {tcp 127.0.0.1:35640}
I170304 08:29:10.809955 21121 storage/stores.go:312  [n?] wrote 1 node addresses to persistent storage
I170304 08:29:10.810578 21121 storage/stores.go:312  [n?] wrote 2 node addresses to persistent storage
I170304 08:29:10.814916 20622 server/node.go:629  [n?] node connected via gossip and verified as part of cluster "e450285f-b6fd-4b83-b773-2b55809bc2f9"
I170304 08:29:10.932219 20622 kv/dist_sender.go:368  [n?] unable to determine this node's attributes for replica selection; node is most likely bootstrapping
I170304 08:29:11.672220 21144 storage/replica.go:2510  [n1,s1,r3/1:/Table/1{1-2},@c422d10380] proposing ADD_REPLICA {NodeID:2 StoreID:2 ReplicaID:2}: [{NodeID:1 StoreID:1 ReplicaID:1} {NodeID:2 StoreID:2 ReplicaID:2}]
I170304 08:29:11.679475 20446 storage/replica_raftstorage.go:414  [replicate,n1,s1,r6/1:/{Table/14-Max},@c420b29880] generated preemptive snapshot b8589d51 at index 11
I170304 08:29:11.681843 20446 storage/store.go:3295  [replicate,n1,s1,r6/1:/{Table/14-Max},@c420b29880] streamed snapshot: kv pairs: 9, log entries: 1, 2ms
I170304 08:29:11.683027 21189 storage/replica_raftstorage.go:596  [n2,s2,r6/?:{-},@c42166b180] applying preemptive snapshot at index 11 (id=b8589d51, encoded size=508, 1 rocksdb batches, 1 log entries)
I170304 08:29:11.683882 21189 storage/replica_raftstorage.go:604  [n2,s2,r6/?:/{Table/14-Max},@c42166b180] applied preemptive snapshot in 1ms [clear=0ms batch=0ms entries=0ms commit=0ms]
I170304 08:29:11.688670 20446 storage/replica_command.go:3312  [replicate,n1,s1,r6/1:/{Table/14-Max},@c420b29880] change replicas (remove {2 2 2}): read existing descriptor range_id:6 start_key:"\226" end_key:"\377\377" replicas:<node_id:1 store_id:1 replica_id:1 > next_replica_id:2 
I170304 08:29:11.709825 20622 server/node.go:334  [n?] new node allocated ID 3
I170304 08:29:11.710253 20622 gossip/gossip.go:293  [n3] NodeDescriptor set to node_id:3 address:<network_field:"tcp" address_field:"127.0.0.1:35640" > attrs:<> locality:<> 
I170304 08:29:11.715744 20622 server/node.go:391  [n3] node=3: started with [[]=] engine(s) and attributes []
I170304 08:29:11.716246 20622 sql/executor.go:337  [n3] creating distSQLPlanner with address {tcp 127.0.0.1:35640}
I170304 08:29:11.727385 21052 storage/stores.go:312  [n1] wrote 2 node addresses to persistent storage
I170304 08:29:11.730227 21053 storage/stores.go:312  [n2] wrote 2 node addresses to persistent storage
I170304 08:29:11.812371 20622 server/server.go:651  [n3] starting https server at 127.0.0.1:36188
I170304 08:29:11.812464 20622 server/server.go:652  [n3] starting grpc/postgres server at 127.0.0.1:35640
I170304 08:29:11.812513 20622 server/server.go:653  [n3] advertising CockroachDB node at 127.0.0.1:35640
I170304 08:29:11.873127 21266 storage/replica.go:2510  [n1,s1,r6/1:/{Table/14-Max},@c420b29880] proposing ADD_REPLICA {NodeID:2 StoreID:2 ReplicaID:2}: [{NodeID:1 StoreID:1 ReplicaID:1} {NodeID:2 StoreID:2 ReplicaID:2}]
I170304 08:29:11.877288 20622 server/server.go:779  [n3] done ensuring all necessary migrations have run
I170304 08:29:11.877379 20622 server/server.go:781  [n3] serving sql connections
I170304 08:29:11.880673 20446 storage/replica_raftstorage.go:414  [replicate,n1,s1,r4/1:/Table/1{2-3},@c42166b880] generated preemptive snapshot 0484ec8a at index 19
I170304 08:29:11.888034 21073 server/node.go:586  [n3] bootstrapped store [n3,s3]
I170304 08:29:11.888583 20446 storage/store.go:3295  [replicate,n1,s1,r4/1:/Table/1{2-3},@c42166b880] streamed snapshot: kv pairs: 25, log entries: 9, 7ms
I170304 08:29:11.889875 21164 storage/replica_raftstorage.go:596  [n2,s2,r4/?:{-},@c4244fd880] applying preemptive snapshot at index 19 (id=0484ec8a, encoded size=13738, 1 rocksdb batches, 9 log entries)
I170304 08:29:11.892983 21164 storage/replica_raftstorage.go:604  [n2,s2,r4/?:/Table/1{2-3},@c4244fd880] applied preemptive snapshot in 3ms [clear=0ms batch=0ms entries=0ms commit=2ms]
I170304 08:29:11.968660 20446 storage/replica_command.go:3312  [replicate,n1,s1,r4/1:/Table/1{2-3},@c42166b880] change replicas (remove {2 2 2}): read existing descriptor range_id:4 start_key:"\224" end_key:"\225" replicas:<node_id:1 store_id:1 replica_id:1 > next_replica_id:2 
I170304 08:29:11.988873 21204 sql/event_log.go:95  [n3] Event: "node_join", target: 3, info: {Descriptor:{NodeID:3 Address:{NetworkField:tcp AddressField:127.0.0.1:35640} Attrs: Locality:} ClusterID:e450285f-b6fd-4b83-b773-2b55809bc2f9 StartedAt:1488616151715354229 LastUp:1488616151715354229}
I170304 08:29:12.094635 20446 storage/replica_command.go:3312  [replicate,n1,s1,r4/1:/Table/1{2-3},@c42166b880] change replicas (remove {2 2 2}): read existing descriptor range_id:4 start_key:"\224" end_key:"\225" replicas:<node_id:1 store_id:1 replica_id:1 > next_replica_id:2 
I170304 08:29:12.119389 21279 storage/replica.go:2510  [n1,s1,r4/1:/Table/1{2-3},@c42166b880] proposing ADD_REPLICA {NodeID:2 StoreID:2 ReplicaID:2}: [{NodeID:1 StoreID:1 ReplicaID:1} {NodeID:2 StoreID:2 ReplicaID:2}]
I170304 08:29:12.128093 20446 storage/replica_raftstorage.go:414  [replicate,n1,s1,r5/1:/Table/1{3-4},@c420758000] generated preemptive snapshot 2b1047fb at index 31
I170304 08:29:12.261622 20446 storage/store.go:3295  [replicate,n1,s1,r5/1:/Table/1{3-4},@c420758000] streamed snapshot: kv pairs: 61, log entries: 21, 2ms
I170304 08:29:12.263164 21362 storage/replica_raftstorage.go:596  [n3,s3,r5/?:{-},@c4240c2e00] applying preemptive snapshot at index 31 (id=2b1047fb, encoded size=34319, 1 rocksdb batches, 21 log entries)
I170304 08:29:12.265024 21362 storage/replica_raftstorage.go:604  [n3,s3,r5/?:/Table/1{3-4},@c4240c2e00] applied preemptive snapshot in 2ms [clear=0ms batch=0ms entries=1ms commit=0ms]
I170304 08:29:12.269070 20446 storage/replica_command.go:3312  [replicate,n1,s1,r5/1:/Table/1{3-4},@c420758000] change replicas (remove {3 3 2}): read existing descriptor range_id:5 start_key:"\225" end_key:"\226" replicas:<node_id:1 store_id:1 replica_id:1 > next_replica_id:2 
I170304 08:29:12.298940 21321 storage/replica.go:2510  [n1,s1,r5/1:/Table/1{3-4},@c420758000] proposing ADD_REPLICA {NodeID:3 StoreID:3 ReplicaID:2}: [{NodeID:1 StoreID:1 ReplicaID:1} {NodeID:3 StoreID:3 ReplicaID:2}]
I170304 08:29:12.303619 20446 storage/replica_raftstorage.go:414  [replicate,n1,s1,r2/1:/Table/{0-11},@c42483a380] generated preemptive snapshot 5cac00af at index 24
I170304 08:29:12.318625 21328 storage/raft_transport.go:436  [n3] raft transport stream to node 1 established
I170304 08:29:12.320991 20446 storage/store.go:3295  [replicate,n1,s1,r2/1:/Table/{0-11},@c42483a380] streamed snapshot: kv pairs: 33, log entries: 14, 6ms
I170304 08:29:12.343101 21342 storage/replica_raftstorage.go:596  [n3,s3,r2/?:{-},@c42415d180] applying preemptive snapshot at index 24 (id=5cac00af, encoded size=22665, 1 rocksdb batches, 14 log entries)
I170304 08:29:12.344456 21342 storage/replica_raftstorage.go:604  [n3,s3,r2/?:/Table/{0-11},@c42415d180] applied preemptive snapshot in 1ms [clear=0ms batch=0ms entries=0ms commit=0ms]
I170304 08:29:12.349711 20446 storage/replica_command.go:3312  [replicate,n1,s1,r2/1:/Table/{0-11},@c42483a380] change replicas (remove {3 3 2}): read existing descriptor range_id:2 start_key:"\210" end_key:"\223" replicas:<node_id:1 store_id:1 replica_id:1 > next_replica_id:2 
I170304 08:29:12.377279 21393 storage/replica.go:2510  [n1,s1,r2/1:/Table/{0-11},@c42483a380] proposing ADD_REPLICA {NodeID:3 StoreID:3 ReplicaID:2}: [{NodeID:1 StoreID:1 ReplicaID:1} {NodeID:3 StoreID:3 ReplicaID:2}]
I170304 08:29:12.381298 20446 storage/queue.go:693  [n1,replicate] purgatory is now empty
I170304 08:29:12.382464 20602 storage/replica_raftstorage.go:414  [replicate,n1,s1,r1/1:/{Min-Table/0},@c423dcd180] generated preemptive snapshot 1ce588f1 at index 68
I170304 08:29:12.412627 20602 storage/store.go:3295  [replicate,n1,s1,r1/1:/{Min-Table/0},@c423dcd180] streamed snapshot: kv pairs: 837, log entries: 58, 29ms
I170304 08:29:12.433045 21366 storage/replica_raftstorage.go:596  [n3,s3,r1/?:{-},@c4244fc000] applying preemptive snapshot at index 68 (id=1ce588f1, encoded size=442267, 1 rocksdb batches, 58 log entries)
I170304 08:29:12.442999 21366 storage/replica_raftstorage.go:604  [n3,s3,r1/?:/{Min-Table/0},@c4244fc000] applied preemptive snapshot in 10ms [clear=0ms batch=0ms entries=5ms commit=4ms]
I170304 08:29:12.447091 20602 storage/replica_command.go:3312  [replicate,n1,s1,r1/1:/{Min-Table/0},@c423dcd180] change replicas (remove {3 3 3}): read existing descriptor range_id:1 start_key:"" end_key:"\210" replicas:<node_id:1 store_id:1 replica_id:1 > replicas:<node_id:2 store_id:2 replica_id:2 > next_replica_id:3 
I170304 08:29:12.517436 21258 storage/replica.go:2510  [n1,s1,r1/1:/{Min-Table/0},@c423dcd180] proposing ADD_REPLICA {NodeID:3 StoreID:3 ReplicaID:3}: [{NodeID:1 StoreID:1 ReplicaID:1} {NodeID:2 StoreID:2 ReplicaID:2} {NodeID:3 StoreID:3 ReplicaID:3}]
I170304 08:29:12.526930 20602 storage/replica_raftstorage.go:414  [replicate,n1,s1,r2/1:/Table/{0-11},@c42483a380] generated preemptive snapshot 7500549f at index 28
I170304 08:29:12.529778 20602 storage/store.go:3295  [replicate,n1,s1,r2/1:/Table/{0-11},@c42483a380] streamed snapshot: kv pairs: 34, log entries: 18, 2ms
I170304 08:29:12.531092 21415 storage/replica_raftstorage.go:596  [n2,s2,r2/?:{-},@c42290b180] applying preemptive snapshot at index 28 (id=7500549f, encoded size=26118, 1 rocksdb batches, 18 log entries)
I170304 08:29:12.532649 21415 storage/replica_raftstorage.go:604  [n2,s2,r2/?:/Table/{0-11},@c42290b180] applied preemptive snapshot in 1ms [clear=0ms batch=0ms entries=1ms commit=0ms]
I170304 08:29:12.537773 20602 storage/replica_command.go:3312  [replicate,n1,s1,r2/1:/Table/{0-11},@c42483a380] change replicas (remove {2 2 3}): read existing descriptor range_id:2 start_key:"\210" end_key:"\223" replicas:<node_id:1 store_id:1 replica_id:1 > replicas:<node_id:3 store_id:3 replica_id:2 > next_replica_id:3 
I170304 08:29:12.609336 21418 storage/replica.go:2510  [n1,s1,r2/1:/Table/{0-11},@c42483a380] proposing ADD_REPLICA {NodeID:2 StoreID:2 ReplicaID:3}: [{NodeID:1 StoreID:1 ReplicaID:1} {NodeID:3 StoreID:3 ReplicaID:2} {NodeID:2 StoreID:2 ReplicaID:3}]
I170304 08:29:12.619928 20602 storage/replica_raftstorage.go:414  [replicate,n1,s1,r6/1:/{Table/14-Max},@c420b29880] generated preemptive snapshot c5337540 at index 14
I170304 08:29:12.639562 20602 storage/store.go:3295  [replicate,n1,s1,r6/1:/{Table/14-Max},@c420b29880] streamed snapshot: kv pairs: 10, log entries: 4, 19ms
I170304 08:29:12.643385 21295 storage/replica_raftstorage.go:596  [n3,s3,r6/?:{-},@c423c55500] applying preemptive snapshot at index 14 (id=c5337540, encoded size=3483, 1 rocksdb batches, 4 log entries)
I170304 08:29:12.644337 21295 storage/replica_raftstorage.go:604  [n3,s3,r6/?:/{Table/14-Max},@c423c55500] applied preemptive snapshot in 1ms [clear=0ms batch=0ms entries=0ms commit=0ms]
I170304 08:29:12.651951 20602 storage/replica_command.go:3312  [replicate,n1,s1,r6/1:/{Table/14-Max},@c420b29880] change replicas (remove {3 3 3}): read existing descriptor range_id:6 start_key:"\226" end_key:"\377\377" replicas:<node_id:1 store_id:1 replica_id:1 > replicas:<node_id:2 store_id:2 replica_id:2 > next_replica_id:3 
I170304 08:29:12.714725 21425 storage/replica.go:2510  [n1,s1,r6/1:/{Table/14-Max},@c420b29880] proposing ADD_REPLICA {NodeID:3 StoreID:3 ReplicaID:3}: [{NodeID:1 StoreID:1 ReplicaID:1} {NodeID:2 StoreID:2 ReplicaID:2} {NodeID:3 StoreID:3 ReplicaID:3}]
I170304 08:29:12.748980 20602 storage/replica_raftstorage.go:414  [replicate,n1,s1,r3/1:/Table/1{1-2},@c422d10380] generated preemptive snapshot cd2b31ea at index 20
I170304 08:29:12.763111 20602 storage/store.go:3295  [replicate,n1,s1,r3/1:/Table/1{1-2},@c422d10380] streamed snapshot: kv pairs: 11, log entries: 10, 13ms
I170304 08:29:12.764435 21375 storage/replica_raftstorage.go:596  [n3,s3,r3/?:{-},@c423c8f500] applying preemptive snapshot at index 20 (id=cd2b31ea, encoded size=12336, 1 rocksdb batches, 10 log entries)
I170304 08:29:12.765611 21375 storage/replica_raftstorage.go:604  [n3,s3,r3/?:/Table/1{1-2},@c423c8f500] applied preemptive snapshot in 1ms [clear=0ms batch=0ms entries=0ms commit=0ms]
I170304 08:29:12.769009 20602 storage/replica_command.go:3312  [replicate,n1,s1,r3/1:/Table/1{1-2},@c422d10380] change replicas (remove {3 3 3}): read existing descriptor range_id:3 start_key:"\223" end_key:"\224" replicas:<node_id:1 store_id:1 replica_id:1 > replicas:<node_id:2 store_id:2 replica_id:2 > next_replica_id:3 
I170304 08:29:12.830057 21478 storage/replica.go:2510  [n1,s1,r3/1:/Table/1{1-2},@c422d10380] proposing ADD_REPLICA {NodeID:3 StoreID:3 ReplicaID:3}: [{NodeID:1 StoreID:1 ReplicaID:1} {NodeID:2 StoreID:2 ReplicaID:2} {NodeID:3 StoreID:3 ReplicaID:3}]
I170304 08:29:12.844140 20602 storage/replica_raftstorage.go:414  [replicate,n1,s1,r4/1:/Table/1{2-3},@c42166b880] generated preemptive snapshot 966b40b7 at index 26
I170304 08:29:12.852522 21507 storage/replica_raftstorage.go:596  [n3,s3,r4/?:{-},@c4248e6000] applying preemptive snapshot at index 26 (id=966b40b7, encoded size=22997, 1 rocksdb batches, 16 log entries)
I170304 08:29:12.853986 21507 storage/replica_raftstorage.go:604  [n3,s3,r4/?:/Table/1{2-3},@c4248e6000] applied preemptive snapshot in 1ms [clear=0ms batch=0ms entries=1ms commit=0ms]
I170304 08:29:12.866981 20602 storage/store.go:3295  [replicate,n1,s1,r4/1:/Table/1{2-3},@c42166b880] streamed snapshot: kv pairs: 31, log entries: 16, 22ms
I170304 08:29:12.869254 20602 storage/replica_command.go:3312  [replicate,n1,s1,r4/1:/Table/1{2-3},@c42166b880] change replicas (remove {3 3 3}): read existing descriptor range_id:4 start_key:"\224" end_key:"\225" replicas:<node_id:1 store_id:1 replica_id:1 > replicas:<node_id:2 store_id:2 replica_id:2 > next_replica_id:3 
I170304 08:29:12.957537 21509 storage/replica.go:2510  [n1,s1,r4/1:/Table/1{2-3},@c42166b880] proposing ADD_REPLICA {NodeID:3 StoreID:3 ReplicaID:3}: [{NodeID:1 StoreID:1 ReplicaID:1} {NodeID:2 StoreID:2 ReplicaID:2} {NodeID:3 StoreID:3 ReplicaID:3}]
I170304 08:29:12.968951 20602 storage/replica_raftstorage.go:414  [replicate,n1,s1,r5/1:/Table/1{3-4},@c420758000] generated preemptive snapshot 5f239dff at index 46
I170304 08:29:12.985152 20602 storage/store.go:3295  [replicate,n1,s1,r5/1:/Table/1{3-4},@c420758000] streamed snapshot: kv pairs: 102, log entries: 36, 15ms
I170304 08:29:12.987243 21359 storage/replica_raftstorage.go:596  [n2,s2,r5/?:{-},@c423b4f180] applying preemptive snapshot at index 46 (id=5f239dff, encoded size=61523, 1 rocksdb batches, 36 log entries)
I170304 08:29:12.989475 21359 storage/replica_raftstorage.go:604  [n2,s2,r5/?:/Table/1{3-4},@c423b4f180] applied preemptive snapshot in 2ms [clear=0ms batch=0ms entries=1ms commit=0ms]
I170304 08:29:12.994027 20602 storage/replica_command.go:3312  [replicate,n1,s1,r5/1:/Table/1{3-4},@c420758000] change replicas (remove {2 2 3}): read existing descriptor range_id:5 start_key:"\225" end_key:"\226" replicas:<node_id:1 store_id:1 replica_id:1 > replicas:<node_id:3 store_id:3 replica_id:2 > next_replica_id:3 
I170304 08:29:13.033867 21543 storage/replica.go:2510  [n1,s1,r5/1:/Table/1{3-4},@c420758000] proposing ADD_REPLICA {NodeID:2 StoreID:2 ReplicaID:3}: [{NodeID:1 StoreID:1 ReplicaID:1} {NodeID:3 StoreID:3 ReplicaID:2} {NodeID:2 StoreID:2 ReplicaID:3}]
I170304 08:29:13.434829 20601 storage/split_queue.go:98  [split,n1,s1,r6/1:/{Table/14-Max},@c420b29880] splitting at key /Table/50/0
I170304 08:29:13.435026 20601 storage/replica_command.go:2456  [split,n1,s1,r6/1:/{Table/14-Max},@c420b29880] initiating a split of this range at key /Table/50 [r7]
I170304 08:29:13.465599 21555 sql/event_log.go:95  [client=127.0.0.1:36772,user=root,n1] Event: "create_database", target: 50, info: {DatabaseName:bench Statement:CREATE DATABASE bench User:root}
I170304 08:29:13.608729 21555 sql/event_log.go:95  [client=127.0.0.1:36772,user=root,n1] Event: "create_table", target: 51, info: {TableName:bench.bank Statement:CREATE TABLE bench.bank (id INT PRIMARY KEY, balance INT, payload STRING, FAMILY (id, balance, payload)) User:root}
I170304 08:29:13.630713 20601 storage/split_queue.go:98  [split,n1,s1,r7/1:/{Table/50-Max},@c421a8ca80] splitting at key /Table/51/0
I170304 08:29:13.630919 20601 storage/replica_command.go:2456  [split,n1,s1,r7/1:/{Table/50-Max},@c421a8ca80] initiating a split of this range at key /Table/51 [r8]
I170304 08:29:14.320954 21555 sql/mon/mem_usage.go:510  [client=127.0.0.1:36772,user=root,n1] txn: memory usage increases to 49 KiB (+49680)
I170304 08:29:14.321454 21555 sql/mon/mem_usage.go:510  [client=127.0.0.1:36772,user=root,n1] txn: memory usage increases to 64 KiB (+140)
I170304 08:29:14.324810 21555 sql/mon/mem_usage.go:510  [client=127.0.0.1:36772,user=root,n1] txn: memory usage increases to 128 KiB (+140)
I170304 08:29:14.884860 21645 storage/replica_command.go:2456  [n1,s1,r8/1:/{Table/51-Max},@c4208de700] initiating a split of this range at key /Table/51/1/100 [r9]
I170304 08:29:15.071545 21690 storage/replica_command.go:2456  [n1,s1,r9/1:/{Table/51/1/1…-Max},@c421d41c00] initiating a split of this range at key /Table/51/1/200 [r10]
I170304 08:29:15.182248 21747 storage/raft_transport.go:436  [n2] raft transport stream to node 3 established
I170304 08:29:15.208013 21721 storage/raft_transport.go:436  [n3] raft transport stream to node 2 established
I170304 08:29:15.224658 21679 storage/replica_command.go:2456  [n1,s1,r10/1:/{Table/51/1/2…-Max},@c423b4e000] initiating a split of this range at key /Table/51/1/300 [r11]
I170304 08:29:15.397543 21771 storage/replica_command.go:2456  [n1,s1,r11/1:/{Table/51/1/3…-Max},@c4230fd180] initiating a split of this range at key /Table/51/1/400 [r12]
I170304 08:29:15.566043 21806 storage/replica_command.go:2456  [n1,s1,r12/1:/{Table/51/1/4…-Max},@c4248a4700] initiating a split of this range at key /Table/51/1/500 [r13]
I170304 08:29:15.739537 21822 storage/replica_command.go:2456  [n1,s1,r13/1:/{Table/51/1/5…-Max},@c424411c00] initiating a split of this range at key /Table/51/1/600 [r14]
I170304 08:29:15.917560 21895 storage/replica_command.go:2456  [n1,s1,r14/1:/{Table/51/1/6…-Max},@c421810700] initiating a split of this range at key /Table/51/1/700 [r15]
I170304 08:29:16.050650 21924 storage/replica_command.go:2456  [n1,s1,r15/1:/{Table/51/1/7…-Max},@c4230fd880] initiating a split of this range at key /Table/51/1/800 [r16]
I170304 08:29:16.193181 22003 storage/replica_command.go:2456  [n1,s1,r16/1:/{Table/51/1/8…-Max},@c424929c00] initiating a split of this range at key /Table/51/1/900 [r17]
I170304 08:29:17.146823 21947 storage/replica_command.go:2456  [n1,s1,r17/1:/{Table/51/1/9…-Max},@c422e76e00] initiating a split of this range at key /Table/52/1/500 [r18]
I170304 08:29:17.224937 22073 storage/replica_command.go:2456  [n1,s1,r17/1:/Table/5{1/1/900-2/1/500},@c422e76e00] initiating a split of this range at key /Table/52/1/200 [r19]
I170304 08:29:17.230674 22150 storage/replica_command.go:2456  [n1,s1,r18/1:/{Table/52/1/5…-Max},@c4208fa380] initiating a split of this range at key /Table/52/1/800 [r20]
I170304 08:29:17.380591 22158 storage/replica_command.go:2456  [n1,s1,r20/1:/{Table/52/1/8…-Max},@c422355c00] initiating a split of this range at key /Table/52/1/900 [r21]
I170304 08:29:17.383393 22185 storage/replica_command.go:2456  [n1,s1,r18/1:/Table/52/1/{500-800},@c4208fa380] initiating a split of this range at key /Table/52/1/700 [r22]
I170304 08:29:17.387978 22227 storage/replica_command.go:2456  [n1,s1,r17/1:/Table/5{1/1/900-2/1/200},@c422e76e00] initiating a split of this range at key /Table/52/1/100 [r23]
I170304 08:29:17.438601 22107 storage/replica_command.go:2456  [n1,s1,r19/1:/Table/52/1/{200-500},@c423b4ea80] initiating a split of this range at key /Table/52/1/400 [r24]
I170304 08:29:17.562891 22236 storage/replica_command.go:2456  [n1,s1,r18/1:/Table/52/1/{500-700},@c4208fa380] initiating a split of this range at key /Table/52/1/600 [r25]
I170304 08:29:17.658449 22357 storage/replica_command.go:2456  [n1,s1,r19/1:/Table/52/1/{200-400},@c423b4ea80] initiating a split of this range at key /Table/52/1/300 [r26]
I170304 08:29:17.941342 22312 storage/replica_command.go:2456  [n2,s2,r17/2:/Table/5{1/1/900-2/1/100},@c424b2c700] initiating a split of this range at key /Table/52/1 [r41]
I170304 08:29:18.104508 22284 storage/engine/rocksdb.go:345  opening rocksdb instance at "/go/src/github.com/cockroachdb/cockroach/artifacts/RocksDBSstFileReader849495456"
I170304 08:29:18.119107 22424 storage/engine/rocksdb.go:345  opening rocksdb instance at "/go/src/github.com/cockroachdb/cockroach/artifacts/RocksDBSstFileReader959244927"
I170304 08:29:18.119723 22517 storage/engine/rocksdb.go:345  opening rocksdb instance at "/go/src/github.com/cockroachdb/cockroach/artifacts/RocksDBSstFileReader392993746"
I170304 08:29:18.120909 22455 storage/engine/rocksdb.go:345  opening rocksdb instance at "/go/src/github.com/cockroachdb/cockroach/artifacts/RocksDBSstFileReader848514825"
I170304 08:29:18.133233 22288 storage/engine/rocksdb.go:345  opening rocksdb instance at "/go/src/github.com/cockroachdb/cockroach/artifacts/RocksDBSstFileReader927501524"
I170304 08:29:18.336966 22424 storage/engine/rocksdb.go:410  closing rocksdb instance at "/go/src/github.com/cockroachdb/cockroach/artifacts/RocksDBSstFileReader959244927"
I170304 08:29:18.345230 22517 storage/engine/rocksdb.go:410  closing rocksdb instance at "/go/src/github.com/cockroachdb/cockroach/artifacts/RocksDBSstFileReader392993746"
I170304 08:29:18.346904 22414 storage/engine/rocksdb.go:345  opening rocksdb instance at "/go/src/github.com/cockroachdb/cockroach/artifacts/RocksDBSstFileReader018756643"
I170304 08:29:18.363390 22532 storage/engine/rocksdb.go:345  opening rocksdb instance at "/go/src/github.com/cockroachdb/cockroach/artifacts/RocksDBSstFileReader006353702"
I170304 08:29:18.380363 22284 storage/engine/rocksdb.go:410  closing rocksdb instance at "/go/src/github.com/cockroachdb/cockroach/artifacts/RocksDBSstFileReader849495456"
I170304 08:29:18.383000 22428 storage/engine/rocksdb.go:345  opening rocksdb instance at "/go/src/github.com/cockroachdb/cockroach/artifacts/RocksDBSstFileReader908777549"
I170304 08:29:18.402301 22288 storage/engine/rocksdb.go:410  closing rocksdb instance at "/go/src/github.com/cockroachdb/cockroach/artifacts/RocksDBSstFileReader927501524"
I170304 08:29:18.430992 22455 storage/engine/rocksdb.go:410  closing rocksdb instance at "/go/src/github.com/cockroachdb/cockroach/artifacts/RocksDBSstFileReader848514825"
I170304 08:29:18.441378 22502 storage/engine/rocksdb.go:345  opening rocksdb instance at "/go/src/github.com/cockroachdb/cockroach/artifacts/RocksDBSstFileReader985504072"
I170304 08:29:18.446448 22462 storage/engine/rocksdb.go:345  opening rocksdb instance at "/go/src/github.com/cockroachdb/cockroach/artifacts/RocksDBSstFileReader679652871"
I170304 08:29:18.676611 22462 storage/engine/rocksdb.go:410  closing rocksdb instance at "/go/src/github.com/cockroachdb/cockroach/artifacts/RocksDBSstFileReader679652871"
I170304 08:29:18.688155 22532 storage/engine/rocksdb.go:410  closing rocksdb instance at "/go/src/github.com/cockroachdb/cockroach/artifacts/RocksDBSstFileReader006353702"
I170304 08:29:18.729528 22597 storage/engine/rocksdb.go:345  opening rocksdb instance at "/go/src/github.com/cockroachdb/cockroach/artifacts/RocksDBSstFileReader528271802"
I170304 08:29:18.742735 22627 storage/engine/rocksdb.go:345  opening rocksdb instance at "/go/src/github.com/cockroachdb/cockroach/artifacts/RocksDBSstFileReader930216913"
I170304 08:29:18.807325 22414 storage/engine/rocksdb.go:410  closing rocksdb instance at "/go/src/github.com/cockroachdb/cockroach/artifacts/RocksDBSstFileReader018756643"
I170304 08:29:18.855747 22502 storage/engine/rocksdb.go:410  closing rocksdb instance at "/go/src/github.com/cockroachdb/cockroach/artifacts/RocksDBSstFileReader985504072"
I170304 08:29:18.857249 22428 storage/engine/rocksdb.go:410  closing rocksdb instance at "/go/src/github.com/cockroachdb/cockroach/artifacts/RocksDBSstFileReader908777549"
I170304 08:29:18.868850 22639 util/stop/stopper.go:493  quiescing; tasks left:
1      server/node.go:847
I170304 08:29:18.869640 22640 util/stop/stopper.go:493  quiescing; tasks left:
2      server/node.go:847
1      storage/replica_proposal.go:372
1      storage/queue.go:523
W170304 08:29:18.870927 20974 storage/raft_transport.go:442  [n1] raft transport stream to node 2 failed: rpc error: code = 13 desc = transport is closing
W170304 08:29:18.871548 21345 storage/raft_transport.go:442  [n1] raft transport stream to node 3 failed: rpc error: code = 13 desc = transport is closing
W170304 08:29:18.874213 21328 storage/raft_transport.go:442  [n3] raft transport stream to node 1 failed: EOF
W170304 08:29:18.876794 21747 storage/raft_transport.go:442  [n2] raft transport stream to node 3 failed: rpc error: code = 13 desc = transport is closing
W170304 08:29:18.877207 21721 storage/raft_transport.go:442  [n3] raft transport stream to node 2 failed: EOF
W170304 08:29:18.877793 20977 storage/raft_transport.go:442  [n2] raft transport stream to node 1 failed: rpc error: code = 13 desc = transport is closing
I170304 08:29:18.934245 22640 util/stop/stopper.go:493  quiescing; tasks left:
2      server/node.go:847
1      storage/queue.go:523
E170304 08:29:18.934565 20953 storage/replica_command.go:1916  [replica consistency checker,n2,s2,r13/2:/Table/51/1/{500-600},@c424886700] could not run async CollectChecksum: node unavailable; try another peer
E170304 08:29:18.934707 20953 storage/replica_command.go:1916  [replica consistency checker,n2,s2,r13/2:/Table/51/1/{500-600},@c424886700] could not run async CollectChecksum: node unavailable; try another peer
I170304 08:29:18.935331 22640 util/stop/stopper.go:493  quiescing; tasks left:
2      server/node.go:847
E170304 08:29:18.936518 21218 storage/replica_proposal.go:374  [n3,s3,r13/3:/Table/51/1/{500-600},@c423b7b500] could not run async checksum computation (ID = 6aa642a6-b1b0-4605-bb74-85e8060ba580): node unavailable; try another peer
E170304 08:29:18.945591 22591 ccl/storageccl/import.go:98  [n2,s2,r21/2:/{Table/52/1/9…-Max},@c42084c380] writebatch [/Table/52/1/900/0,/Table/52/1/999/0/NULL): context canceled
I170304 08:29:18.946085 22627 storage/engine/rocksdb.go:410  closing rocksdb instance at "/go/src/github.com/cockroachdb/cockroach/artifacts/RocksDBSstFileReader930216913"
I170304 08:29:18.947341 22640 util/stop/stopper.go:493  quiescing; tasks left:
1      server/node.go:847
E170304 08:29:18.978923 20697 storage/replica_proposal.go:374  [n1,s1,r13/1:/Table/51/1/{500-600},@c424411c00] could not run async checksum computation (ID = 6aa642a6-b1b0-4605-bb74-85e8060ba580): node unavailable; try another peer
E170304 08:29:18.990626 22606 ccl/storageccl/import.go:98  [n2,s2,r24/2:/Table/52/1/{400-500},@c421837880] writebatch [/Table/52/1/400/0,/Table/52/1/499/0/NULL): context canceled
I170304 08:29:18.990822 22597 storage/engine/rocksdb.go:410  closing rocksdb instance at "/go/src/github.com/cockroachdb/cockroach/artifacts/RocksDBSstFileReader528271802"
I170304 08:29:19.490051 20673 kv/transport_race.go:71  transport race promotion: ran 30 iterations on up to 891 requests
	<autogenerated>:14: error executing 'RESTORE DATABASE bench FROM '/go/src/github.com/cockroachdb/cockroach/artifacts/TestBackupAsOfSystemTime108072876'': pq: importing 10 ranges: first of 1 errors: import can only be called on empty ranges
```

### LINKED ISSUE #13906: teamcity: failed tests on master: testrace (proposer evaluated kv)/TestBackupAsOfSystemTime
The following tests appear to have failed:

[#170441](https://teamcity.cockroachdb.com/viewLog.html?buildId=170441):

```
--- FAIL: testrace (proposer evaluated kv)/TestBackupAsOfSystemTime (9.630s)
<autogenerated>:14: error executing 'RESTORE DATABASE bench FROM '/go/src/github.com/cockroachdb/cockroach/artifacts/TestBackupAsOfSystemTime999567012'': pq: importing 10 ranges: first of 1 errors: import can only be called on empty ranges
------- Stdout: -------
W170306 17:26:42.206736 23865 server/status/runtime.go:116  Could not parse build timestamp: parsing time "" as "2006/01/02 15:04:05": cannot parse "" as "2006"
I170306 17:26:42.212559 23865 server/config.go:482  1 storage engine initialized
I170306 17:26:42.213562 23865 server/node.go:443  [n?] store [n0,s0] not bootstrapped
I170306 17:26:42.226952 23865 server/node.go:372  [n?] **** cluster 28e50305-28c0-43d3-9e92-a9ea0199a477 has been created
I170306 17:26:42.227051 23865 server/node.go:373  [n?] **** add additional nodes by specifying --join=127.0.0.1:33637
I170306 17:26:42.231886 23865 storage/store.go:1274  [n1] [n1,s1]: failed initial metrics computation: [n1,s1]: system config not yet available
I170306 17:26:42.232017 23865 server/node.go:456  [n1] initialized store [n1,s1]: {Capacity:536870912 Available:536870912 RangeCount:1 LeaseCount:0}
I170306 17:26:42.232201 23865 server/node.go:341  [n1] node ID 1 initialized
I170306 17:26:42.232389 23865 gossip/gossip.go:293  [n1] NodeDescriptor set to node_id:1 address:<network_field:"tcp" address_field:"127.0.0.1:33637" > attrs:<> locality:<> 
I170306 17:26:42.233120 23865 storage/stores.go:296  [n1] read 0 node addresses from persistent storage
I170306 17:26:42.233305 23865 server/node.go:605  [n1] connecting to gossip network to verify cluster ID...
I170306 17:26:42.234428 23865 server/node.go:629  [n1] node connected via gossip and verified as part of cluster "28e50305-28c0-43d3-9e92-a9ea0199a477"
I170306 17:26:42.234850 23865 server/node.go:391  [n1] node=1: started with [[]=] engine(s) and attributes []
I170306 17:26:42.235321 23865 sql/executor.go:337  [n1] creating distSQLPlanner with address {tcp 127.0.0.1:33637}
I170306 17:26:42.247405 23865 server/server.go:651  [n1] starting https server at 127.0.0.1:47386
I170306 17:26:42.247515 23865 server/server.go:652  [n1] starting grpc/postgres server at 127.0.0.1:33637
I170306 17:26:42.247562 23865 server/server.go:653  [n1] advertising CockroachDB node at 127.0.0.1:33637
I170306 17:26:42.249070 23883 storage/split_queue.go:98  [split,n1,s1,r1/1:/M{in-ax},@c420aa7880] splitting at key /Table/0/0
I170306 17:26:42.262802 23883 storage/replica_command.go:2456  [split,n1,s1,r1/1:/M{in-ax},@c420aa7880] initiating a split of this range at key /Table/0 [r2]
I170306 17:26:42.339090 23883 storage/split_queue.go:98  [split,n1,s1,r2/1:/{Table/0-Max},@c422c0ae00] splitting at key /Table/11/0
I170306 17:26:42.339305 23883 storage/replica_command.go:2456  [split,n1,s1,r2/1:/{Table/0-Max},@c422c0ae00] initiating a split of this range at key /Table/11 [r3]
I170306 17:26:42.359620 23972 sql/event_log.go:95  [n1] Event: "node_join", target: 1, info: {Descriptor:{NodeID:1 Address:{NetworkField:tcp AddressField:127.0.0.1:33637} Attrs: Locality:} ClusterID:28e50305-28c0-43d3-9e92-a9ea0199a477 StartedAt:1488821202234486220 LastUp:1488821202234486220}
I170306 17:26:42.385657 23865 sql/event_log.go:95  [n1] Event: "alter_table", target: 12, info: {TableName:eventlog Statement:ALTER TABLE system.eventlog ALTER COLUMN uniqueID SET DEFAULT uuid_v4() User:node MutationID:0 CascadeDroppedViews:[]}
I170306 17:26:42.398236 23883 storage/split_queue.go:98  [split,n1,s1,r3/1:/{Table/11-Max},@c422a78700] splitting at key /Table/12/0
I170306 17:26:42.398472 23883 storage/replica_command.go:2456  [split,n1,s1,r3/1:/{Table/11-Max},@c422a78700] initiating a split of this range at key /Table/12 [r4]
I170306 17:26:42.483749 23883 storage/split_queue.go:98  [split,n1,s1,r4/1:/{Table/12-Max},@c423bd9c00] splitting at key /Table/13/0
I170306 17:26:42.483971 23883 storage/replica_command.go:2456  [split,n1,s1,r4/1:/{Table/12-Max},@c423bd9c00] initiating a split of this range at key /Table/13 [r5]
I170306 17:26:42.541186 23883 storage/split_queue.go:98  [split,n1,s1,r5/1:/{Table/13-Max},@c421694e00] splitting at key /Table/14/0
I170306 17:26:42.541377 23883 storage/replica_command.go:2456  [split,n1,s1,r5/1:/{Table/13-Max},@c421694e00] initiating a split of this range at key /Table/14 [r6]
I170306 17:26:42.546545 23865 server/server.go:779  [n1] done ensuring all necessary migrations have run
I170306 17:26:42.546646 23865 server/server.go:781  [n1] serving sql connections
W170306 17:26:42.760360 23865 gossip/gossip.go:1178  [n?] no incoming or outgoing connections
W170306 17:26:42.775134 23865 server/status/runtime.go:116  Could not parse build timestamp: parsing time "" as "2006/01/02 15:04:05": cannot parse "" as "2006"
I170306 17:26:42.781524 23865 server/config.go:482  1 storage engine initialized
I170306 17:26:42.783398 23865 server/node.go:443  [n?] store [n0,s0] not bootstrapped
I170306 17:26:42.783493 23865 storage/stores.go:296  [n?] read 0 node addresses from persistent storage
I170306 17:26:42.783613 23865 server/node.go:605  [n?] connecting to gossip network to verify cluster ID...
I170306 17:26:42.857343 24196 gossip/client.go:131  [n?] started gossip client to 127.0.0.1:33637
I170306 17:26:42.858772 24221 gossip/server.go:214  [n1] received initial cluster-verification connection from {tcp 127.0.0.1:39676}
I170306 17:26:42.866494 23865 server/node.go:629  [n?] node connected via gossip and verified as part of cluster "28e50305-28c0-43d3-9e92-a9ea0199a477"
I170306 17:26:42.868031 24190 storage/stores.go:312  [n?] wrote 1 node addresses to persistent storage
I170306 17:26:42.872966 23865 kv/dist_sender.go:368  [n?] unable to determine this node's attributes for replica selection; node is most likely bootstrapping
I170306 17:26:42.881861 23865 server/node.go:334  [n?] new node allocated ID 2
I170306 17:26:42.882186 23865 gossip/gossip.go:293  [n2] NodeDescriptor set to node_id:2 address:<network_field:"tcp" address_field:"127.0.0.1:39676" > attrs:<> locality:<> 
I170306 17:26:42.882940 23865 server/node.go:391  [n2] node=2: started with [[]=] engine(s) and attributes []
I170306 17:26:42.883445 23865 sql/executor.go:337  [n2] creating distSQLPlanner with address {tcp 127.0.0.1:39676}
I170306 17:26:42.901636 24223 storage/stores.go:312  [n1] wrote 1 node addresses to persistent storage
I170306 17:26:42.941860 23865 server/server.go:651  [n2] starting https server at 127.0.0.1:60386
I170306 17:26:42.949455 23865 server/server.go:652  [n2] starting grpc/postgres server at 127.0.0.1:39676
I170306 17:26:42.949538 23865 server/server.go:653  [n2] advertising CockroachDB node at 127.0.0.1:39676
I170306 17:26:42.956774 23865 server/server.go:779  [n2] done ensuring all necessary migrations have run
I170306 17:26:42.957031 23865 server/server.go:781  [n2] serving sql connections
I170306 17:26:42.990962 24260 sql/event_log.go:95  [n2] Event: "node_join", target: 2, info: {Descriptor:{NodeID:2 Address:{NetworkField:tcp AddressField:127.0.0.1:39676} Attrs: Locality:} ClusterID:28e50305-28c0-43d3-9e92-a9ea0199a477 StartedAt:1488821202882660911 LastUp:1488821202882660911}
W170306 17:26:43.048093 23865 gossip/gossip.go:1178  [n?] no incoming or outgoing connections
W170306 17:26:43.054278 23865 server/status/runtime.go:116  Could not parse build timestamp: parsing time "" as "2006/01/02 15:04:05": cannot parse "" as "2006"
I170306 17:26:43.057039 23865 server/config.go:482  1 storage engine initialized
I170306 17:26:43.080066 23865 server/node.go:443  [n?] store [n0,s0] not bootstrapped
I170306 17:26:43.095888 23865 storage/stores.go:296  [n?] read 0 node addresses from persistent storage
I170306 17:26:43.096344 23865 server/node.go:605  [n?] connecting to gossip network to verify cluster ID...
I170306 17:26:43.121903 24241 server/node.go:586  [n2] bootstrapped store [n2,s2]
I170306 17:26:43.143274 24041 storage/replica_raftstorage.go:414  [replicate,n1,s1,r1/1:/{Min-Table/0},@c420aa7880] generated preemptive snapshot b93b1138 at index 46
I170306 17:26:43.182536 24134 gossip/client.go:131  [n?] started gossip client to 127.0.0.1:33637
I170306 17:26:43.184851 24144 gossip/server.go:214  [n1] received initial cluster-verification connection from {tcp 127.0.0.1:46071}
I170306 17:26:43.189270 23865 server/node.go:629  [n?] node connected via gossip and verified as part of cluster "28e50305-28c0-43d3-9e92-a9ea0199a477"
I170306 17:26:43.190702 24357 storage/stores.go:312  [n?] wrote 1 node addresses to persistent storage
I170306 17:26:43.191442 24357 storage/stores.go:312  [n?] wrote 2 node addresses to persistent storage
I170306 17:26:43.199054 23865 kv/dist_sender.go:368  [n?] unable to determine this node's attributes for replica selection; node is most likely bootstrapping
I170306 17:26:43.207025 23865 server/node.go:334  [n?] new node allocated ID 3
I170306 17:26:43.207466 23865 gossip/gossip.go:293  [n3] NodeDescriptor set to node_id:3 address:<network_field:"tcp" address_field:"127.0.0.1:46071" > attrs:<> locality:<> 
I170306 17:26:43.208397 23865 server/node.go:391  [n3] node=3: started with [[]=] engine(s) and attributes []
I170306 17:26:43.208963 23865 sql/executor.go:337  [n3] creating distSQLPlanner with address {tcp 127.0.0.1:46071}
I170306 17:26:43.220472 24387 storage/stores.go:312  [n1] wrote 2 node addresses to persistent storage
I170306 17:26:43.222002 24254 storage/stores.go:312  [n2] wrote 2 node addresses to persistent storage
I170306 17:26:43.255994 23865 server/server.go:651  [n3] starting https server at 127.0.0.1:56040
I170306 17:26:43.256082 23865 server/server.go:652  [n3] starting grpc/postgres server at 127.0.0.1:46071
I170306 17:26:43.256118 23865 server/server.go:653  [n3] advertising CockroachDB node at 127.0.0.1:46071
I170306 17:26:43.272054 24351 sql/event_log.go:95  [n3] Event: "node_join", target: 3, info: {Descriptor:{NodeID:3 Address:{NetworkField:tcp AddressField:127.0.0.1:46071} Attrs: Locality:} ClusterID:28e50305-28c0-43d3-9e92-a9ea0199a477 StartedAt:1488821203208011943 LastUp:1488821203208011943}
I170306 17:26:43.279009 24348 server/node.go:586  [n3] bootstrapped store [n3,s3]
I170306 17:26:43.294755 23865 server/server.go:779  [n3] done ensuring all necessary migrations have run
I170306 17:26:43.294897 23865 server/server.go:781  [n3] serving sql connections
I170306 17:26:43.329101 24041 storage/store.go:3295  [replicate,n1,s1,r1/1:/{Min-Table/0},@c420aa7880] streamed snapshot: kv pairs: 608, log entries: 36, 63ms
I170306 17:26:43.340531 24466 storage/replica_raftstorage.go:596  [n2,s2,r1/?:{-},@c420734380] applying preemptive snapshot at index 46 (id=b93b1138, encoded size=270218, 1 rocksdb batches, 36 log entries)
I170306 17:26:43.345358 24466 storage/replica_raftstorage.go:604  [n2,s2,r1/?:/{Min-Table/0},@c420734380] applied preemptive snapshot in 5ms [clear=0ms batch=0ms entries=2ms commit=1ms]
I170306 17:26:43.355374 24041 storage/replica_command.go:3312  [replicate,n1,s1,r1/1:/{Min-Table/0},@c420aa7880] change replicas (remove {2 2 2}): read existing descriptor range_id:1 start_key:"" end_key:"\210" replicas:<node_id:1 store_id:1 replica_id:1 > next_replica_id:2 
I170306 17:26:43.395220 24534 storage/replica.go:2510  [n1,s1,r1/1:/{Min-Table/0},@c420aa7880] proposing ADD_REPLICA {NodeID:2 StoreID:2 ReplicaID:2}: [{NodeID:1 StoreID:1 ReplicaID:1} {NodeID:2 StoreID:2 ReplicaID:2}]
I170306 17:26:43.413839 24505 storage/raft_transport.go:436  [n2] raft transport stream to node 1 established
I170306 17:26:43.415423 24041 storage/replica_raftstorage.go:414  [replicate,n1,s1,r4/1:/Table/1{2-3},@c423bd9c00] generated preemptive snapshot 7a04cc36 at index 20
I170306 17:26:43.549193 24520 storage/replica_raftstorage.go:596  [n3,s3,r4/?:{-},@c423968380] applying preemptive snapshot at index 20 (id=7a04cc36, encoded size=16924, 1 rocksdb batches, 10 log entries)
I170306 17:26:43.550460 24520 storage/replica_raftstorage.go:604  [n3,s3,r4/?:/Table/1{2-3},@c423968380] applied preemptive snapshot in 1ms [clear=0ms batch=0ms entries=0ms commit=0ms]
I170306 17:26:43.568191 24041 storage/store.go:3295  [replicate,n1,s1,r4/1:/Table/1{2-3},@c423bd9c00] streamed snapshot: kv pairs: 30, log entries: 10, 22ms
I170306 17:26:43.570664 24041 storage/replica_command.go:3312  [replicate,n1,s1,r4/1:/Table/1{2-3},@c423bd9c00] change replicas (remove {3 3 2}): read existing descriptor range_id:4 start_key:"\224" end_key:"\225" replicas:<node_id:1 store_id:1 replica_id:1 > next_replica_id:2 
I170306 17:26:46.250707 24491 storage/replica.go:2510  [n1,s1,r4/1:/Table/1{2-3},@c423bd9c00] proposing ADD_REPLICA {NodeID:3 StoreID:3 ReplicaID:2}: [{NodeID:1 StoreID:1 ReplicaID:1} {NodeID:3 StoreID:3 ReplicaID:2}]
I170306 17:26:46.268559 24444 storage/raft_transport.go:436  [n3] raft transport stream to node 1 established
I170306 17:26:46.296524 24041 storage/replica_raftstorage.go:414  [replicate,n1,s1,r5/1:/Table/1{3-4},@c421694e00] generated preemptive snapshot 81342359 at index 28
I170306 17:26:46.300235 24041 storage/store.go:3295  [replicate,n1,s1,r5/1:/Table/1{3-4},@c421694e00] streamed snapshot: kv pairs: 52, log entries: 18, 3ms
I170306 17:26:46.301431 24543 storage/replica_raftstorage.go:596  [n3,s3,r5/?:{-},@c422927c00] applying preemptive snapshot at index 28 (id=81342359, encoded size=25380, 1 rocksdb batches, 18 log entries)
I170306 17:26:46.302947 24543 storage/replica_raftstorage.go:604  [n3,s3,r5/?:/Table/1{3-4},@c422927c00] applied preemptive snapshot in 1ms [clear=0ms batch=0ms entries=1ms commit=0ms]
I170306 17:26:46.305851 24041 storage/replica_command.go:3312  [replicate,n1,s1,r5/1:/Table/1{3-4},@c421694e00] change replicas (remove {3 3 2}): read existing descriptor range_id:5 start_key:"\225" end_key:"\226" replicas:<node_id:1 store_id:1 replica_id:1 > next_replica_id:2 
I170306 17:26:46.334742 24573 storage/replica.go:2510  [n1,s1,r5/1:/Table/1{3-4},@c421694e00] proposing ADD_REPLICA {NodeID:3 StoreID:3 ReplicaID:2}: [{NodeID:1 StoreID:1 ReplicaID:1} {NodeID:3 StoreID:3 ReplicaID:2}]
I170306 17:26:46.339994 24041 storage/replica_raftstorage.go:414  [replicate,n1,s1,r6/1:/{Table/14-Max},@c421f7a380] generated preemptive snapshot 81d83d0a at index 13
I170306 17:26:46.342966 24041 storage/store.go:3295  [replicate,n1,s1,r6/1:/{Table/14-Max},@c421f7a380] streamed snapshot: kv pairs: 10, log entries: 3, 2ms
I170306 17:26:46.344296 24575 storage/replica_raftstorage.go:596  [n2,s2,r6/?:{-},@c423969c00] applying preemptive snapshot at index 13 (id=81d83d0a, encoded size=1720, 1 rocksdb batches, 3 log entries)
I170306 17:26:46.345683 24575 storage/replica_raftstorage.go:604  [n2,s2,r6/?:/{Table/14-Max},@c423969c00] applied preemptive snapshot in 1ms [clear=0ms batch=0ms entries=0ms commit=0ms]
I170306 17:26:46.360191 24041 storage/replica_command.go:3312  [replicate,n1,s1,r6/1:/{Table/14-Max},@c421f7a380] change replicas (remove {2 2 2}): read existing descriptor range_id:6 start_key:"\226" end_key:"\377\377" replicas:<node_id:1 store_id:1 replica_id:1 > next_replica_id:2 
I170306 17:26:46.398692 24607 storage/replica.go:2510  [n1,s1,r6/1:/{Table/14-Max},@c421f7a380] proposing ADD_REPLICA {NodeID:2 StoreID:2 ReplicaID:2}: [{NodeID:1 StoreID:1 ReplicaID:1} {NodeID:2 StoreID:2 ReplicaID:2}]
I170306 17:26:46.405771 24041 storage/replica_raftstorage.go:414  [replicate,n1,s1,r3/1:/Table/1{1-2},@c422a78700] generated preemptive snapshot f8b7d332 at index 18
I170306 17:26:46.428547 24041 storage/store.go:3295  [replicate,n1,s1,r3/1:/Table/1{1-2},@c422a78700] streamed snapshot: kv pairs: 11, log entries: 8, 19ms
I170306 17:26:46.429616 24561 storage/replica_raftstorage.go:596  [n2,s2,r3/?:{-},@c421850700] applying preemptive snapshot at index 18 (id=f8b7d332, encoded size=8523, 1 rocksdb batches, 8 log entries)
I170306 17:26:46.432603 24561 storage/replica_raftstorage.go:604  [n2,s2,r3/?:/Table/1{1-2},@c421850700] applied preemptive snapshot in 3ms [clear=0ms batch=0ms entries=0ms commit=0ms]
I170306 17:26:46.440229 24041 storage/replica_command.go:3312  [replicate,n1,s1,r3/1:/Table/1{1-2},@c422a78700] change replicas (remove {2 2 2}): read existing descriptor range_id:3 start_key:"\223" end_key:"\224" replicas:<node_id:1 store_id:1 replica_id:1 > next_replica_id:2 
I170306 17:26:46.460905 24617 storage/replica.go:2510  [n1,s1,r3/1:/Table/1{1-2},@c422a78700] proposing ADD_REPLICA {NodeID:2 StoreID:2 ReplicaID:2}: [{NodeID:1 StoreID:1 ReplicaID:1} {NodeID:2 StoreID:2 ReplicaID:2}]
I170306 17:26:46.474717 24041 storage/replica_raftstorage.go:414  [replicate,n1,s1,r2/1:/Table/{0-11},@c422c0ae00] generated preemptive snapshot 8ff23681 at index 28
I170306 17:26:46.483326 24041 storage/store.go:3295  [replicate,n1,s1,r2/1:/Table/{0-11},@c422c0ae00] streamed snapshot: kv pairs: 34, log entries: 18, 8ms
I170306 17:26:46.485102 24631 storage/replica_raftstorage.go:596  [n3,s3,r2/?:{-},@c421839180] applying preemptive snapshot at index 28 (id=8ff23681, encoded size=28906, 1 rocksdb batches, 18 log entries)
I170306 17:26:46.486751 24631 storage/replica_raftstorage.go:604  [n3,s3,r2/?:/Table/{0-11},@c421839180] applied preemptive snapshot in 1ms [clear=0ms batch=0ms entries=1ms commit=0ms]
I170306 17:26:46.495418 24041 storage/replica_command.go:3312  [replicate,n1,s1,r2/1:/Table/{0-11},@c422c0ae00] change replicas (remove {3 3 2}): read existing descriptor range_id:2 start_key:"\210" end_key:"\223" replicas:<node_id:1 store_id:1 replica_id:1 > next_replica_id:2 
I170306 17:26:46.528023 24623 storage/replica.go:2510  [n1,s1,r2/1:/Table/{0-11},@c422c0ae00] proposing ADD_REPLICA {NodeID:3 StoreID:3 ReplicaID:2}: [{NodeID:1 StoreID:1 ReplicaID:1} {NodeID:3 StoreID:3 ReplicaID:2}]
I170306 17:26:46.545234 24041 storage/queue.go:693  [n1,replicate] purgatory is now empty
I170306 17:26:46.550084 23884 storage/replica_raftstorage.go:414  [replicate,n1,s1,r3/1:/Table/1{1-2},@c422a78700] generated preemptive snapshot a8e4c29e at index 21
I170306 17:26:46.557882 23884 storage/store.go:3295  [replicate,n1,s1,r3/1:/Table/1{1-2},@c422a78700] streamed snapshot: kv pairs: 12, log entries: 11, 6ms
I170306 17:26:46.563162 24661 storage/replica_raftstorage.go:596  [n3,s3,r3/?:{-},@c4202b8700] applying preemptive snapshot at index 21 (id=a8e4c29e, encoded size=11491, 1 rocksdb batches, 11 log entries)
I170306 17:26:46.565840 24661 storage/replica_raftstorage.go:604  [n3,s3,r3/?:/Table/1{1-2},@c4202b8700] applied preemptive snapshot in 2ms [clear=0ms batch=0ms entries=1ms commit=0ms]
I170306 17:26:46.572277 23884 storage/replica_command.go:3312  [replicate,n1,s1,r3/1:/Table/1{1-2},@c422a78700] change replicas (remove {3 3 3}): read existing descriptor range_id:3 start_key:"\223" end_key:"\224" replicas:<node_id:1 store_id:1 replica_id:1 > replicas:<node_id:2 store_id:2 replica_id:2 > next_replica_id:3 
I170306 17:26:46.602180 24655 storage/replica.go:2510  [n1,s1,r3/1:/Table/1{1-2},@c422a78700] proposing ADD_REPLICA {NodeID:3 StoreID:3 ReplicaID:3}: [{NodeID:1 StoreID:1 ReplicaID:1} {NodeID:2 StoreID:2 ReplicaID:2} {NodeID:3 StoreID:3 ReplicaID:3}]
I170306 17:26:46.627276 23884 storage/replica_raftstorage.go:414  [replicate,n1,s1,r2/1:/Table/{0-11},@c422c0ae00] generated preemptive snapshot 1fe3a910 at index 31
I170306 17:26:46.655091 23884 storage/store.go:3295  [replicate,n1,s1,r2/1:/Table/{0-11},@c422c0ae00] streamed snapshot: kv pairs: 35, log entries: 21, 20ms
I170306 17:26:46.656761 24449 storage/replica_raftstorage.go:596  [n2,s2,r2/?:{-},@c423bcb180] applying preemptive snapshot at index 31 (id=1fe3a910, encoded size=31874, 1 rocksdb batches, 21 log entries)
I170306 17:26:46.658492 24449 storage/replica_raftstorage.go:604  [n2,s2,r2/?:/Table/{0-11},@c423bcb180] applied preemptive snapshot in 2ms [clear=0ms batch=0ms entries=1ms commit=0ms]
I170306 17:26:46.661647 23884 storage/replica_command.go:3312  [replicate,n1,s1,r2/1:/Table/{0-11},@c422c0ae00] change replicas (remove {2 2 3}): read existing descriptor range_id:2 start_key:"\210" end_key:"\223" replicas:<node_id:1 store_id:1 replica_id:1 > replicas:<node_id:3 store_id:3 replica_id:2 > next_replica_id:3 
I170306 17:26:46.700858 24673 storage/replica.go:2510  [n1,s1,r2/1:/Table/{0-11},@c422c0ae00] proposing ADD_REPLICA {NodeID:2 StoreID:2 ReplicaID:3}: [{NodeID:1 StoreID:1 ReplicaID:1} {NodeID:3 StoreID:3 ReplicaID:2} {NodeID:2 StoreID:2 ReplicaID:3}]
I170306 17:26:46.708003 23884 storage/replica_raftstorage.go:414  [replicate,n1,s1,r4/1:/Table/1{2-3},@c423bd9c00] generated preemptive snapshot d47191f8 at index 25
I170306 17:26:46.721334 23884 storage/store.go:3295  [replicate,n1,s1,r4/1:/Table/1{2-3},@c423bd9c00] streamed snapshot: kv pairs: 32, log entries: 15, 10ms
I170306 17:26:46.728037 24677 storage/replica_raftstorage.go:596  [n2,s2,r4/?:{-},@c423f2a000] applying preemptive snapshot at index 25 (id=d47191f8, encoded size=21100, 1 rocksdb batches, 15 log entries)
I170306 17:26:46.729579 24677 storage/replica_raftstorage.go:604  [n2,s2,r4/?:/Table/1{2-3},@c423f2a000] applied preemptive snapshot in 1ms [clear=0ms batch=0ms entries=1ms commit=0ms]
I170306 17:26:46.733197 23884 storage/replica_command.go:3312  [replicate,n1,s1,r4/1:/Table/1{2-3},@c423bd9c00] change replicas (remove {2 2 3}): read existing descriptor range_id:4 start_key:"\224" end_key:"\225" replicas:<node_id:1 store_id:1 replica_id:1 > replicas:<node_id:3 store_id:3 replica_id:2 > next_replica_id:3 
I170306 17:26:46.786630 24524 storage/replica.go:2510  [n1,s1,r4/1:/Table/1{2-3},@c423bd9c00] proposing ADD_REPLICA {NodeID:2 StoreID:2 ReplicaID:3}: [{NodeID:1 StoreID:1 ReplicaID:1} {NodeID:3 StoreID:3 ReplicaID:2} {NodeID:2 StoreID:2 ReplicaID:3}]
I170306 17:26:46.796004 23884 storage/replica_raftstorage.go:414  [replicate,n1,s1,r1/1:/{Min-Table/0},@c420aa7880] generated preemptive snapshot 40a050a5 at index 74
I170306 17:26:46.847910 23884 storage/store.go:3295  [replicate,n1,s1,r1/1:/{Min-Table/0},@c420aa7880] streamed snapshot: kv pairs: 841, log entries: 64, 51ms
I170306 17:26:46.852600 24527 storage/replica_raftstorage.go:596  [n3,s3,r1/?:{-},@c421ab5c00] applying preemptive snapshot at index 74 (id=40a050a5, encoded size=469844, 1 rocksdb batches, 64 log entries)
I170306 17:26:46.861564 24527 storage/replica_raftstorage.go:604  [n3,s3,r1/?:/{Min-Table/0},@c421ab5c00] applied preemptive snapshot in 8ms [clear=0ms batch=0ms entries=5ms commit=2ms]
I170306 17:26:46.879653 23884 storage/replica_command.go:3312  [replicate,n1,s1,r1/1:/{Min-Table/0},@c420aa7880] change replicas (remove {3 3 3}): read existing descriptor range_id:1 start_key:"" end_key:"\210" replicas:<node_id:1 store_id:1 replica_id:1 > replicas:<node_id:2 store_id:2 replica_id:2 > next_replica_id:3 
I170306 17:26:46.900122 24724 storage/replica.go:2510  [n1,s1,r1/1:/{Min-Table/0},@c420aa7880] proposing ADD_REPLICA {NodeID:3 StoreID:3 ReplicaID:3}: [{NodeID:1 StoreID:1 ReplicaID:1} {NodeID:2 StoreID:2 ReplicaID:2} {NodeID:3 StoreID:3 ReplicaID:3}]
I170306 17:26:46.914841 23884 storage/replica_raftstorage.go:414  [replicate,n1,s1,r6/1:/{Table/14-Max},@c421f7a380] generated preemptive snapshot eda7f6d3 at index 16
I170306 17:26:46.917195 23884 storage/store.go:3295  [replicate,n1,s1,r6/1:/{Table/14-Max},@c421f7a380] streamed snapshot: kv pairs: 11, log entries: 6, 2ms
I170306 17:26:46.918483 24771 storage/replica_raftstorage.go:596  [n3,s3,r6/?:{-},@c42029aa80] applying preemptive snapshot at index 16 (id=eda7f6d3, encoded size=4695, 1 rocksdb batches, 6 log entries)
I170306 17:26:46.921308 24771 storage/replica_raftstorage.go:604  [n3,s3,r6/?:/{Table/14-Max},@c42029aa80] applied preemptive snapshot in 3ms [clear=0ms batch=0ms entries=0ms commit=0ms]
I170306 17:26:46.928876 23884 storage/replica_command.go:3312  [replicate,n1,s1,r6/1:/{Table/14-Max},@c421f7a380] change replicas (remove {3 3 3}): read existing descriptor range_id:6 start_key:"\226" end_key:"\377\377" replicas:<node_id:1 store_id:1 replica_id:1 > replicas:<node_id:2 store_id:2 replica_id:2 > next_replica_id:3 
I170306 17:26:46.985167 24789 storage/replica.go:2510  [n1,s1,r6/1:/{Table/14-Max},@c421f7a380] proposing ADD_REPLICA {NodeID:3 StoreID:3 ReplicaID:3}: [{NodeID:1 StoreID:1 ReplicaID:1} {NodeID:2 StoreID:2 ReplicaID:2} {NodeID:3 StoreID:3 ReplicaID:3}]
I170306 17:26:46.999586 23884 storage/replica_raftstorage.go:414  [replicate,n1,s1,r5/1:/Table/1{3-4},@c421694e00] generated preemptive snapshot f71c9378 at index 47
I170306 17:26:47.004375 23884 storage/store.go:3295  [replicate,n1,s1,r5/1:/Table/1{3-4},@c421694e00] streamed snapshot: kv pairs: 103, log entries: 37, 4ms
I170306 17:26:47.012637 24819 storage/replica_raftstorage.go:596  [n2,s2,r5/?:{-},@c423923500] applying preemptive snapshot at index 47 (id=f71c9378, encoded size=59834, 1 rocksdb batches, 37 log entries)
I170306 17:26:47.014928 24819 storage/replica_raftstorage.go:604  [n2,s2,r5/?:/Table/1{3-4},@c423923500] applied preemptive snapshot in 2ms [clear=0ms batch=0ms entries=1ms commit=0ms]
I170306 17:26:47.018092 23884 storage/replica_command.go:3312  [replicate,n1,s1,r5/1:/Table/1{3-4},@c421694e00] change replicas (remove {2 2 3}): read existing descriptor range_id:5 start_key:"\225" end_key:"\226" replicas:<node_id:1 store_id:1 replica_id:1 > replicas:<node_id:3 store_id:3 replica_id:2 > next_replica_id:3 
I170306 17:26:47.069673 24751 storage/replica.go:2510  [n1,s1,r5/1:/Table/1{3-4},@c421694e00] proposing ADD_REPLICA {NodeID:2 StoreID:2 ReplicaID:3}: [{NodeID:1 StoreID:1 ReplicaID:1} {NodeID:3 StoreID:3 ReplicaID:2} {NodeID:2 StoreID:2 ReplicaID:3}]
I170306 17:26:47.382246 24753 sql/event_log.go:95  [client=127.0.0.1:37573,user=root,n1] Event: "create_database", target: 50, info: {DatabaseName:bench Statement:CREATE DATABASE bench User:root}
I170306 17:26:47.390722 23883 storage/split_queue.go:98  [split,n1,s1,r6/1:/{Table/14-Max},@c421f7a380] splitting at key /Table/50/0
I170306 17:26:47.393688 23883 storage/replica_command.go:2456  [split,n1,s1,r6/1:/{Table/14-Max},@c421f7a380] initiating a split of this range at key /Table/50 [r7]
I170306 17:26:47.557626 24753 sql/event_log.go:95  [client=127.0.0.1:37573,user=root,n1] Event: "create_table", target: 51, info: {TableName:bench.bank Statement:CREATE TABLE bench.bank (id INT PRIMARY KEY, balance INT, payload STRING, FAMILY (id, balance, payload)) User:root}
I170306 17:26:47.656658 23883 storage/split_queue.go:98  [split,n1,s1,r7/1:/{Table/50-Max},@c422927180] splitting at key /Table/51/0
I170306 17:26:47.656893 23883 storage/replica_command.go:2456  [split,n1,s1,r7/1:/{Table/50-Max},@c422927180] initiating a split of this range at key /Table/51 [r8]
I170306 17:26:47.990370 24753 sql/mon/mem_usage.go:510  [client=127.0.0.1:37573,user=root,n1] txn: memory usage increases to 49 KiB (+49680)
I170306 17:26:47.991008 24753 sql/mon/mem_usage.go:510  [client=127.0.0.1:37573,user=root,n1] txn: memory usage increases to 64 KiB (+140)
I170306 17:26:47.999188 24753 sql/mon/mem_usage.go:510  [client=127.0.0.1:37573,user=root,n1] txn: memory usage increases to 128 KiB (+140)
I170306 17:26:48.294285 24785 storage/replica_command.go:2456  [n1,s1,r8/1:/{Table/51-Max},@c4242d6e00] initiating a split of this range at key /Table/51/1/100 [r9]
I170306 17:26:48.418658 25019 storage/replica_command.go:2456  [n1,s1,r9/1:/{Table/51/1/1���-Max},@c421850380] initiating a split of this range at key /Table/51/1/200 [r10]
I170306 17:26:48.549748 25044 storage/raft_transport.go:436  [n2] raft transport stream to node 3 established
I170306 17:26:48.559213 25032 storage/replica_command.go:2456  [n1,s1,r10/1:/{Table/51/1/2���-Max},@c42099b180] initiating a split of this range at key /Table/51/1/300 [r11]
I170306 17:26:48.560340 25049 storage/raft_transport.go:436  [n3] raft transport stream to node 2 established
I170306 17:26:48.679254 25095 storage/replica_command.go:2456  [n1,s1,r11/1:/{Table/51/1/3���-Max},@c4228b7180] initiating a split of this range at key /Table/51/1/400 [r12]
I170306 17:26:48.802904 25128 storage/replica_command.go:2456  [n1,s1,r12/1:/{Table/51/1/4���-Max},@c4229df180] initiating a split of this range at key /Table/51/1/500 [r13]
I170306 17:26:48.977050 25118 storage/replica_command.go:2456  [n1,s1,r13/1:/{Table/51/1/5���-Max},@c422cc3180] initiating a split of this range at key /Table/51/1/600 [r14]
I170306 17:26:49.185137 25190 storage/replica_command.go:2456  [n1,s1,r14/1:/{Table/51/1/6���-Max},@c422926380] initiating a split of this range at key /Table/51/1/700 [r15]
I170306 17:26:49.317671 25168 storage/replica_command.go:2456  [n1,s1,r15/1:/{Table/51/1/7���-Max},@c4233af880] initiating a split of this range at key /Table/51/1/800 [r16]
I170306 17:26:49.475969 25315 storage/replica_command.go:2456  [n1,s1,r16/1:/{Table/51/1/8���-Max},@c4213cae00] initiating a split of this range at key /Table/51/1/900 [r17]
I170306 17:26:49.949848 25411 storage/replica_command.go:2456  [n1,s1,r17/1:/{Table/51/1/9���-Max},@c4242fc380] initiating a split of this range at key /Table/52/1/500 [r18]
I170306 17:26:50.036491 25475 storage/replica_command.go:2456  [n1,s1,r18/1:/{Table/52/1/5���-Max},@c422307500] initiating a split of this range at key /Table/52/1/800 [r19]
I170306 17:26:50.039212 25361 storage/replica_command.go:2456  [n1,s1,r17/1:/Table/5{1/1/900-2/1/500},@c4242fc380] initiating a split of this range at key /Table/52/1/200 [r20]
I170306 17:26:50.187762 25465 storage/replica_command.go:2456  [n1,s1,r17/1:/Table/5{1/1/900-2/1/200},@c4242fc380] initiating a split of this range at key /Table/52/1/100 [r21]
I170306 17:26:50.197195 25467 storage/replica_command.go:2456  [n1,s1,r20/1:/Table/52/1/{200-500},@c423923180] initiating a split of this range at key /Table/52/1/400 [r22]
I170306 17:26:50.231677 25538 storage/replica_command.go:2456  [n1,s1,r18/1:/Table/52/1/{500-800},@c422307500] initiating a split of this range at key /Table/52/1/700 [r23]
I170306 17:26:50.246556 25539 storage/replica_command.go:2456  [n1,s1,r19/1:/{Table/52/1/8���-Max},@c424018e00] initiating a split of this range at key /Table/52/1/900 [r24]
I170306 17:26:50.395211 25620 storage/replica_command.go:2456  [n1,s1,r20/1:/Table/52/1/{200-400},@c423923180] initiating a split of this range at key /Table/52/1/300 [r25]
I170306 17:26:50.418221 25604 storage/replica_command.go:2456  [n1,s1,r17/1:/Table/5{1/1/900-2/1/100},@c4242fc380] initiating a split of this range at key /Table/52/1 [r26]
I170306 17:26:50.495104 25651 storage/replica_command.go:2456  [n1,s1,r18/1:/Table/52/1/{500-700},@c422307500] initiating a split of this range at key /Table/52/1/600 [r27]
I170306 17:26:50.798126 25764 storage/engine/rocksdb.go:345  opening rocksdb instance at "/go/src/github.com/cockroachdb/cockroach/artifacts/RocksDBSstFileReader631490072"
I170306 17:26:50.800455 25827 storage/engine/rocksdb.go:345  opening rocksdb instance at "/go/src/github.com/cockroachdb/cockroach/artifacts/RocksDBSstFileReader118380695"
I170306 17:26:50.805027 25811 storage/engine/rocksdb.go:345  opening rocksdb instance at "/go/src/github.com/cockroachdb/cockroach/artifacts/RocksDBSstFileReader130643210"
I170306 17:26:50.810061 25826 storage/engine/rocksdb.go:345  opening rocksdb instance at "/go/src/github.com/cockroachdb/cockroach/artifacts/RocksDBSstFileReader161933537"
I170306 17:26:50.858435 25766 storage/engine/rocksdb.go:345  opening rocksdb instance at "/go/src/github.com/cockroachdb/cockroach/artifacts/RocksDBSstFileReader171984076"
I170306 17:26:51.002916 25826 storage/engine/rocksdb.go:410  closing rocksdb instance at "/go/src/github.com/cockroachdb/cockroach/artifacts/RocksDBSstFileReader161933537"
I170306 17:26:51.008339 25827 storage/engine/rocksdb.go:410  closing rocksdb instance at "/go/src/github.com/cockroachdb/cockroach/artifacts/RocksDBSstFileReader118380695"
I170306 17:26:51.018913 25764 storage/engine/rocksdb.go:410  closing rocksdb instance at "/go/src/github.com/cockroachdb/cockroach/artifacts/RocksDBSstFileReader631490072"
I170306 17:26:51.020770 25765 storage/engine/rocksdb.go:345  opening rocksdb instance at "/go/src/github.com/cockroachdb/cockroach/artifacts/RocksDBSstFileReader395862971"
I170306 17:26:51.023915 25784 storage/engine/rocksdb.go:345  opening rocksdb instance at "/go/src/github.com/cockroachdb/cockroach/artifacts/RocksDBSstFileReader741624798"
I170306 17:26:51.036541 25758 storage/engine/rocksdb.go:345  opening rocksdb instance at "/go/src/github.com/cockroachdb/cockroach/artifacts/RocksDBSstFileReader120513445"
I170306 17:26:51.052585 25811 storage/engine/rocksdb.go:410  closing rocksdb instance at "/go/src/github.com/cockroachdb/cockroach/artifacts/RocksDBSstFileReader130643210"
I170306 17:26:51.059598 25657 storage/engine/rocksdb.go:345  opening rocksdb instance at "/go/src/github.com/cockroachdb/cockroach/artifacts/RocksDBSstFileReader416917696"
I170306 17:26:51.079545 25766 storage/engine/rocksdb.go:410  closing rocksdb instance at "/go/src/github.com/cockroachdb/cockroach/artifacts/RocksDBSstFileReader171984076"
I170306 17:26:51.090617 25659 storage/engine/rocksdb.go:345  opening rocksdb instance at "/go/src/github.com/cockroachdb/cockroach/artifacts/RocksDBSstFileReader219587359"
I170306 17:26:51.240182 25765 storage/engine/rocksdb.go:410  closing rocksdb instance at "/go/src/github.com/cockroachdb/cockroach/artifacts/RocksDBSstFileReader395862971"
I170306 17:26:51.275833 25657 storage/engine/rocksdb.go:410  closing rocksdb instance at "/go/src/github.com/cockroachdb/cockroach/artifacts/RocksDBSstFileReader416917696"
I170306 17:26:51.326636 25823 storage/engine/rocksdb.go:345  opening rocksdb instance at "/go/src/github.com/cockroachdb/cockroach/artifacts/RocksDBSstFileReader398854642"
I170306 17:26:51.382804 25777 storage/engine/rocksdb.go:345  opening rocksdb instance at "/go/src/github.com/cockroachdb/cockroach/artifacts/RocksDBSstFileReader751199401"
I170306 17:26:51.440321 25784 storage/engine/rocksdb.go:410  closing rocksdb instance at "/go/src/github.com/cockroachdb/cockroach/artifacts/RocksDBSstFileReader741624798"
I170306 17:26:51.443971 25659 storage/engine/rocksdb.go:410  closing rocksdb instance at "/go/src/github.com/cockroachdb/cockroach/artifacts/RocksDBSstFileReader219587359"
I170306 17:26:51.459087 25758 storage/engine/rocksdb.go:410  closing rocksdb instance at "/go/src/github.com/cockroachdb/cockroach/artifacts/RocksDBSstFileReader120513445"
I170306 17:26:51.466896 25973 util/stop/stopper.go:493  quiescing; tasks left:
1      storage/replica_proposal.go:372
1      storage/replica_command.go:1915
1      storage/queue.go:523
I170306 17:26:51.467185 25972 util/stop/stopper.go:493  quiescing; tasks left:
2      storage/replica_proposal.go:372
2      server/node.go:847
I170306 17:26:51.467565 25971 util/stop/stopper.go:493  quiescing; tasks left:
2      storage/replica_command.go:1915
1      storage/queue.go:523
W170306 17:26:51.472681 25049 storage/raft_transport.go:442  [n3] raft transport stream to node 2 failed: rpc error: code = 13 desc = transport is closing
W170306 17:26:51.473025 24500 storage/raft_transport.go:442  [n1] raft transport stream to node 2 failed: rpc error: code = 13 desc = transport is closing
W170306 17:26:51.473558 25044 storage/raft_transport.go:442  [n2] raft transport stream to node 3 failed: EOF
I170306 17:26:51.474158 25809 vendor/google.golang.org/grpc/server.go:752  grpc: Server.processUnaryRPC failed to write status: stream error: code = 1 desc = "context canceled"
I170306 17:26:51.474917 25970 vendor/google.golang.org/grpc/server.go:752  grpc: Server.processUnaryRPC failed to write status: stream error: code = 1 desc = "context canceled"
I170306 17:26:51.475026 25916 vendor/google.golang.org/grpc/server.go:752  grpc: Server.processUnaryRPC failed to write status: connection error: desc = "transport: tls: use of closed connection"
I170306 17:26:51.475274 25972 util/stop/stopper.go:493  quiescing; tasks left:
2      server/node.go:847
1      storage/replica_proposal.go:372
E170306 17:26:51.476353 25807 storage/replica_command.go:1896  [replica consistency checker,n1,s1,r16/1:/Table/51/1/{800-900},@c4213cae00] could not CollectChecksum from replica {2 2 2}: rpc error: code = 13 desc = transport is closing
W170306 17:26:51.477065 24581 storage/raft_transport.go:442  [n1] raft transport stream to node 3 failed: rpc error: code = 13 desc = transport is closing
E170306 17:26:51.477493 25808 storage/replica_command.go:1896  [replica consistency checker,n1,s1,r16/1:/Table/51/1/{800-900},@c4213cae00] could not CollectChecksum from replica {3 3 3}: rpc error: code = 13 desc = transport is closing
W170306 17:26:51.477564 24444 storage/raft_transport.go:442  [n3] raft transport stream to node 1 failed: rpc error: code = 13 desc = transport is closing
W170306 17:26:51.480720 24505 storage/raft_transport.go:442  [n2] raft transport stream to node 1 failed: rpc error: code = 13 desc = transport is closing
E170306 17:26:51.481069 25915 storage/replica_command.go:1896  [replica consistency checker,n3,s3,r12/3:/Table/51/1/{400-500},@c423b0e000] could not CollectChecksum from replica {2 2 2}: rpc error: code = 13 desc = transport is closing
I170306 17:26:51.481951 25973 util/stop/stopper.go:493  quiescing; tasks left:
1      storage/replica_proposal.go:372
1      storage/replica_command.go:1915
I170306 17:26:51.482985 25973 util/stop/stopper.go:493  quiescing; tasks left:
1      storage/replica_command.go:1915
I170306 17:26:51.498095 25972 util/stop/stopper.go:493  quiescing; tasks left:
2      server/node.go:847
E170306 17:26:51.526696 25974 ccl/storageccl/import.go:98  [n2,s2,r26/2:/Table/52/1{-/100},@c423bd8380] writebatch [/Table/52/1/0/0,/Table/52/1/99/0/NULL): context canceled
I170306 17:26:51.526910 25823 storage/engine/rocksdb.go:410  closing rocksdb instance at "/go/src/github.com/cockroachdb/cockroach/artifacts/RocksDBSstFileReader398854642"
I170306 17:26:51.528233 25972 util/stop/stopper.go:493  quiescing; tasks left:
1      server/node.go:847
E170306 17:26:51.587033 25956 ccl/storageccl/import.go:98  [n2,s2,r27/2:/Table/52/1/{600-700},@c421bb9500] writebatch [/Table/52/1/600/0,/Table/52/1/699/0/NULL): context canceled
I170306 17:26:51.587266 25777 storage/engine/rocksdb.go:410  closing rocksdb instance at "/go/src/github.com/cockroachdb/cockroach/artifacts/RocksDBSstFileReader751199401"
I170306 17:26:51.748616 23839 kv/transport_race.go:71  transport race promotion: ran 48 iterations on up to 832 requests

```
Please assign, take a look and update the issue accordingly.

### PR DESCRIPTION
**Pull request by danhhz**
Delete any pre-existing data in the affected keyrange. Adjust the mvcc
stats by computing them from scratch for the to-be-deleted data and
substracting that from the total.

This makes it safe to retry the Import command, as DistSender does
(which was causing flakes).

Closes #13906.
Closes #13893.
Closes #13867.
Closes #13866.

---
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/13951)

### CODE REVIEW

**Comment by danhhz** [comment]
@bdarnell or @petermattis, could you double-check the mvcc stats math here?

File: pkg/ccl/storageccl/writebatch.go [hunk 1]
```diff
@@ -64,12 +66,22 @@ func evalWriteBatch(
...
 	iter := batch.NewIterator(false)
 	defer iter.Close()
 	iter.Seek(mvccStartKey)
 	if iter.Valid() && iter.Key().Less(mvccEndKey) {
-		return storage.EvalResult{}, errors.New("WriteBatch can only be called on empty ranges")
+		existingStats, err := iter.ComputeStats(mvccStartKey, mvccEndKey, h.Timestamp.WallTime)
+		if err != nil {
+			return storage.EvalResult{}, err
+		}
+		// TODO(dan): Ideally, this would use `batch.ClearRange` but it doesn't
```
Comment (dt) [inline pkg/ccl/storageccl/writebatch.go]: oooff. that's unfortunate.

**Review by dt — APPROVED** [review]

**Comment by tamird** [comment]
Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, 4 unresolved discussions, all commit checks successful.

---

*[pkg/ccl/storageccl/import_test.go, line 87 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/13951#-Kee3CaVgl2VYowwofWy:-Kee3CaVgl2VYowwofWz:b2kgrdg) ([raw file](https://github.com/cockroachdb/cockroach/blob/fe1e8e9350a30eed848bb4634f3e7ea0940acdbd/pkg/ccl/storageccl/import_test.go#L87)):*
> ```Go
> 	// Import may be retried by DistSender if it takes too long to return, so
> 	// make sure it's idempotent.
> 	const numIterations = 3
> ```

could elide the constant

---

*[pkg/ccl/storageccl/writebatch_test.go, line 40 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/13951#-Kee3cPfTofMR4i_KCT_:-Kee3cPfTofMR4i_KCTa:b-chu3vy) ([raw file](https://github.com/cockroachdb/cockroach/blob/fe1e8e9350a30eed848bb4634f3e7ea0940acdbd/pkg/ccl/storageccl/writebatch_test.go#L40)):*
> ```Go
> 	ctx := context.Background()
> 
> 	var data []byte
> ```

why pull this way out? just to avoid one level of nesting?

---

*[pkg/storage/engine/rocksdb.go, line 916 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/13951#-Kee3wcpXtBPk7QAyGWQ:-Kee3wcpXtBPk7QAyGWR:bsjmg58) ([raw file](https://github.com/cockroachdb/cockroach/blob/fe1e8e9350a30eed848bb4634f3e7ea0940acdbd/pkg/storage/engine/rocksdb.go#L916)):*
> ```Go
> }
> 
> func (r *rocksDBBatchIterator) getIter() *C.DBIterator {
> ```

how come this became necessary?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/13951)*

**Comment by dt** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions, all commit checks successful.

---

*[pkg/storage/engine/rocksdb.go, line 916 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/13951#-Kee3wcpXtBPk7QAyGWQ:-KeeRl6Cwg_3flzJSL0d:bn50gws) ([raw file](https://github.com/cockroachdb/cockroach/blob/fe1e8e9350a30eed848bb4634f3e7ea0940acdbd/pkg/storage/engine/rocksdb.go#L916)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

how come this became necessary?
</blockquote></details>

impl interface dbIteratorGetter, which is asserted by `ClearIterRange`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/13951)*

**Comment by tamird** [comment]
Reviewed 1 of 2 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/13951)*

**Comment by danhhz** [comment]
@petermattis or @bdarnell can you look at the mvcc stats logic here, please? This is the fix for all the backup/restore test flakes, which are still pretty frequent, so I'd love to get it in asap

(Or Tamir mentions that @mrtracy might also have enough context to do this)

**Comment by petermattis** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/13951#-:-KeoNQOuA6Na6JjjVVkL:bnfp4nl)*

**Comment by danhhz** [comment]
Thanks for the reviews, all!

---

Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/13951#-:-KeogGu7J-c3-Q-Il6cN:b35xzef)*
