### PR TITLE
sql: clarify the error message upon access to vtable with no db

### LINKED ISSUE #23958: sql: make `pg_catalog` error out cleanly when no cur db set
Currently a query on `pg_catalog` with no current db set fails with "no database specified".

The user would be better informed if the message would say instead "no current database set" and perhaps a hint to use set/use.

### PR DESCRIPTION
**Pull request by knz**
Fixes #23958.

Prior to this patch:

```
root@:26257/> select * from pg_catalog.pg_class;
pq: no database specified
```

After:

```
root@:26257/> select * from pg_catalog.pg_class;
pq: cannot access virtual schema in anonymous database
HINT: verify that the current database is set
```

Release note (sql change): the error message produced upon accessing a
virtual schema with no database prefix (e.g. when `database` is not
set) is now clarified.

### CODE REVIEW

File: pkg/sql/virtual_schema.go [hunk 1]
```diff
@@ -93,6 +94,10 @@ type virtualTableEntry struct {
 
 type virtualTableConstructor func(context.Context, *planner, string) (planNode, error)
 
+var errInvalidDbPrefix = pgerror.NewError(pgerror.CodeUndefinedObjectError,
+	"cannot access virtual schema in anonymous database",
+).SetHintf("verify that the current database is set")
```
Comment (jordanlewis) [inline pkg/sql/virtual_schema.go]: nit: is there a SetHint without the f?

**Review by jordanlewis — APPROVED** [review]

**Comment by jordanlewis** [comment]
This seems cherrypickable.

File: pkg/sql/virtual_schema.go (hunk 1 above)
Comment (knz) [reply pkg/sql/virtual_schema.go]: not yet, no
