### PR TITLE
pkg/cmd/roachtest: add multi-region restore roachtest

### LINKED ISSUE #97785: restoreccl: multi-region testing
We currently do not test multi region restore (or backup) in our nightly test suite. A nightly test could run a restore into a multi region cluster from a regular backup, or  a locality aware backup. The test should use the same fixture and hardware specs as our `restore//tpce/400GB/gce/nodes=4/cpus=8`  to make performance comparable. The test should use a basic MR setup.

The test would add value in a couple ways:
1) assert that we optimally distribute work to nodes and allow us to detect regressions in this very specific multiregion configuration.
2) make it easy to detect perf regressions specific to all MR configurations
3) make it easy to test and benchmark restore improvements in a multiregion context.

Jira issue: CRDB-24881

Epic CRDB-20915

### PR DESCRIPTION
**Pull request by benbardin**
New test name:
    `restore/tpce/400GB/aws/nodes=9/cpus=8/zones=us-east-2b,us-west-2b,eu-west-1b`

Note that this is set up with 9 nodes. That's a unique number, but seems reasonable for a three-region setup.
Initial run results:
    Usage 482244 , Nodes 9 , Duration 3312.659089;
    Throughput: 15.776651 mb / node / second

Fixes: #97785

Release note: None

### CODE REVIEW

File: pkg/cmd/roachtest/tests/restore.go [hunk 1]
```diff
@@ -296,6 +296,15 @@ func registerRestore(r registry.Registry) {
 			backup:   makeBackupSpecs(backupSpecs{}),
 			timeout:  1 * time.Hour,
 		},
+		{
+			// Benchmarks if per node throughput remains constant if the cluster
+			// is multi-region.
+			hardware: makeHardwareSpecs(hardwareSpecs{
+				nodes: 6,
+				zones: []string{"us-east-1b", "us-east-2b"}}), // These zones are AWS-specific.
```
Comment (msbutler) [inline pkg/cmd/roachtest/tests/restore.go:304]: this would make a cluster across different availability zones, not necessarily different regions (us-west...) . I think we want to use different regions?

I'm not entirely confident that a "2 region, three nodes in each region" is a representative simple MR topology, mostly bc i don't now much about mr topologies. Perhaps bring it up in discussion or demo to ask the team?

**Review by msbutler — COMMENTED** [review]
i thought this diff would be larger! Nice surprise!

Perhaps once we figure out the exact topology, could you comment or update the commit with:
-  the new test name. You can get this via `roachtest list | grep 'restore'`
-  run the test and provide the basic benchmark results that get printed at the end of the `test.log` file.

**Comment by benbardin** [comment]
Thanks for the review! Take another look when you're able? Thank you!

**Review by msbutler — APPROVED** [review]
LGTM! I suspect you'll need to rebase on [#99402](https://github.com/cockroachdb/cockroach/pull/99402)
