### PR TITLE
storage: bump FormatMajorVersion for shared storage

### LINKED ISSUE #116631: roachtest: disk-stalled/cgroup/read-write/logs-too=true failed
roachtest.disk-stalled/cgroup/read-write/logs-too=true [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/13182695?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/13182695?buildTab=artifacts#/disk-stalled/cgroup/read-write/logs-too=true) on release-23.2 @ [9a13104643153a4233d626e0d398e4b7175674bd](https://github.com/cockroachdb/cockroach/commits/9a13104643153a4233d626e0d398e4b7175674bd):

```
(disk_stall.go:216).runDiskStalledDetection: post-stall TPS 728.32 is less than 50% of pre-stall TPS 1916.32
(cluster.go:2160).Run: context canceled
test artifacts and logs in: /artifacts/disk-stalled/cgroup/read-write/logs-too=true/run_1
```

Parameters:
 - <code>ROACHTEST_arch=amd64</code>
 - <code>ROACHTEST_cloud=gce</code>
 - <code>ROACHTEST_coverageBuild=false</code>
 - <code>ROACHTEST_cpu=4</code>
 - <code>ROACHTEST_encrypted=false</code>
 - <code>ROACHTEST_fs=ext4</code>
 - <code>ROACHTEST_localSSD=false</code>
 - <code>ROACHTEST_metamorphicBuild=false</code>
 - <code>ROACHTEST_ssd=0</code>
<details><summary>Help</summary>
<p>

See: [roachtest README](https://github.com/cockroachdb/cockroach/blob/master/pkg/cmd/roachtest/README.md)

See: [How To Investigate \(internal\)](https://cockroachlabs.atlassian.net/l/c/SSSBr8c7)

See: [Grafana](https://go.crdb.dev/roachtest-grafana/teamcity-13182695/disk-stalled-cgroup-read-write-logs-too-true/1702823371368/1702824145729)

</p>
</details>
/cc @cockroachdb/storage
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*disk-stalled/cgroup/read-write/logs-too=true.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)
</sub>

Jira issue: CRDB-34697

### LINKED ISSUE #117043: roachtest: disagg-rebalance/aws/n4cpu4 failed
roachtest.disagg-rebalance/aws/n4cpu4 [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyAwsBazel/13271658?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyAwsBazel/13271658?buildTab=artifacts#/disagg-rebalance/aws/n4cpu4) on master @ [53e4efd389167110d687e5dea8bf915fe2582a25](https://github.com/cockroachdb/cockroach/commits/53e4efd389167110d687e5dea8bf915fe2582a25):

```
(cluster.go:2106).Start: COMMAND_PROBLEM: exit status 1
test artifacts and logs in: /artifacts/disagg-rebalance/aws/n4cpu4/run_1
```

Parameters:
 - <code>ROACHTEST_arch=amd64</code>
 - <code>ROACHTEST_cloud=aws</code>
 - <code>ROACHTEST_coverageBuild=false</code>
 - <code>ROACHTEST_cpu=4</code>
 - <code>ROACHTEST_encrypted=false</code>
 - <code>ROACHTEST_fs=ext4</code>
 - <code>ROACHTEST_localSSD=true</code>
 - <code>ROACHTEST_metamorphicBuild=false</code>
 - <code>ROACHTEST_ssd=0</code>
<details><summary>Help</summary>
<p>

See: [roachtest README](https://github.com/cockroachdb/cockroach/blob/master/pkg/cmd/roachtest/README.md)

See: [How To Investigate \(internal\)](https://cockroachlabs.atlassian.net/l/c/SSSBr8c7)

_Grafana is not yet available for aws clusters_</p>
</details>
/cc @cockroachdb/storage
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*disagg-rebalance/aws/n4cpu4.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)
</sub>

Jira issue: CRDB-34930

### PR DESCRIPTION
**Pull request by itsbilal**
Previously, we'd leave the FormatMajorVersion at a lower value for stores created with shared storage, than what is necessary for shared storage. This change fixes that to bump the FMV up if shared storage is being configured.

Fixes #117043
Epic: none

Release note: None

### CODE REVIEW

**Comment by itsbilal** [comment]
🤦 I tagged the wrong issue. Meant to tag #117043.

File: pkg/storage/open.go [hunk 1]
```diff
@@ -171,6 +171,9 @@ func BallastSize(size int64) ConfigOption {
 func SharedStorage(sharedStorage cloud.ExternalStorage) ConfigOption {
 	return func(cfg *engineConfig) error {
 		cfg.SharedStorage = sharedStorage
+		if cfg.Opts.FormatMajorVersion < pebble.FormatMinForSharedObjects {
```
Comment (RaduBerinde) [inline pkg/storage/open.go:174]: Only do this if sharedStorage isn't nil

**Review by RaduBerinde — APPROVED** [review]
Nice, thanks for the fix!

File: pkg/storage/open.go (hunk 1 above)
Comment (itsbilal) [reply pkg/storage/open.go]: Done.

**Comment by itsbilal** [comment]
bors r=RaduBerinde

**Review by jbowens — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/117288)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @itsbilal and @RaduBerinde)

___
*[`pkg/storage/open.go` line 175 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/117288#-NnK_0VNDESA9a_BH7Ed:-NnK_0VNDESA9a_BH7Ee:b2d03s5) ([raw file](https://github.com/cockroachdb/cockroach/blob/3ed431c3e2986957fc3331542cdb88f4360620e5/pkg/storage/open.go#L175)):*
> ```Go
> 		cfg.SharedStorage = sharedStorage
> 		if cfg.SharedStorage != nil && cfg.Opts.FormatMajorVersion < pebble.FormatMinForSharedObjects {
> 			cfg.Opts.FormatMajorVersion = pebble.FormatMinForSharedObjects
> ```

How does this interact with cluster version gates?

**Comment by RaduBerinde** [comment]
*[`pkg/storage/open.go` line 175 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/117288#-NnK_0VNDESA9a_BH7Ed:-NnKc4YL9ZUjvYlV-FmE:bootcwf) ([raw file](https://github.com/cockroachdb/cockroach/blob/3ed431c3e2986957fc3331542cdb88f4360620e5/pkg/storage/open.go#L175)):*
<details><summary><i>Previously, jbowens (Jackson Owens) wrote…</i></summary><blockquote>

How does this interact with cluster version gates?
</blockquote></details>

For now, we only configure shared storage when passing the `--experimental-shared-storage` flag. When we will promote that to a more user-friendly way of setting it up, we will require 24.1 cluster version.
