### PR TITLE
roachprod: add unimplemented error

### LINKED ISSUE #119857: roachprod: replace Provider "unimplemented" panics
Currently `roachprod` providers will panic when an unimplemented method is called, for a feature the provider does not support. This is generally not a problem when using `roachprod` from the CLI. But it does present a problem in `roachtest` which could fail a whole suite if a test is accidentally or suite/CI setup is accidentally utilising something that is not implemented for the provider.

The suggestion here is that we update the panics to rather be errors, so that the test suite can continue running and only the affected test is interrupted.

Jira issue: CRDB-36355

### PR DESCRIPTION
**Pull request by herkolategan**
Previously, providers would panic if an unimplemented method was called. This could prove problematic for roachtest that allow tests to specify a set of compatible clouds. The implementer of the test may be unaware that the method they are planning to invoke is not implemented on certain cloud providers. A panic will end up failing the whole test suite.

In this change we introduce an error that should be used instead of `panic("unimplemented")`.

Fixes: #119857

Release note: None
Epic: None

### CODE REVIEW

File: pkg/roachprod/vm/vm.go [hunk 1]
```diff
@@ -62,6 +62,12 @@ const (
 	DisksInitializedFile = "/mnt/data1/" + InitializedFile
 )
 
+// UnimplementedError is returned when a method is not implemented by a
+// provider. An error is returned instead of panicking to isolate failures to a
+// single test (in the context of `roachtest`), otherwise the entire test run
+// would fail.
+var UnimplementedError = errors.New("unimplemented")
```
Comment (herkolategan) [inline pkg/roachprod/vm/vm.go:69]: I'm considering if this should maybe rather be `rperrors.TransientFailure(errors.New("unimplemented"), "provider_problem")`, or maybe a different class of errors to route it differently.

Comment (renatolabs) [reply pkg/roachprod/vm/vm.go:69]: I wouldn't be opposed to that. I think if these errors did happen, there's a decent chance it would go unnoticed in the daily batch of cluster creation errors. But this error in particular should always be fixed.

**Review by renatolabs — APPROVED** [review]
LGTM!

**Comment by herkolategan** [comment]
TFTR!

bors r=renatolabs
