### PR TITLE
sql: fix system.namespace and crdb_internal.zones in 19.2 mixed-version state

### LINKED ISSUE #47167: sql: system.namespace is unreadable from 19.2 nodes in mixed version state
19.2 nodes in a mixed-version state with 20.1 can't read `system.descriptor` from SQL. This has cascading problems, because `crdb_internal.zones` explicitly reads `system.descriptor`, and a few things explicitly read `crdb_internal.zones`, including debug zips, admin ui, and so on.

The cause of this is that #44006 edits the `system.namespace` descriptor (which is descriptor ID 2, which is called `namespace_deprecated` in 20.1) to changes its name to `namespace_deprecated` for the purpose of making Backup not fail due to seeing descriptors with duplicate names. But the 19.2 (and prior) code expects the original `namespace` table to be named `namespace`, and does not resolve it otherwise.

### PR DESCRIPTION
**Pull request by jordanlewis**
Fixes #47167.

Previously, the system.namespace table would become inaccessible by 19.2
nodes following a 20.1 node joining the cluster. This was because of a
mistake in the namespace migration, which edited the original
system.namespace descriptor (id 2) to have its Name field set to
namespace_deprecated. This caused 19.2 nodes not to recognize it. The
reason that the migration did this (see 3c0671c) is that it's illegal
to have two descriptors with the same Name field.

This commit fixes the problem by writing the new namespace descriptor
(id 30) with a Name field set to a new value,
namespace2. This avoids the duplicate descriptor name
problem, but introduces a slight new hiccup, which is that the new
descriptor has a different Name than its actual table name, which
remains "namespace". This patch avoids this problem with a special
case. All of this special case logic can be removed in 20.2. We will
need to write a new migration for 20.2 anyway, that migrates old
namespace entries into the new format. That migration should also change
the Name of the namespace descriptor back to "namespace". The 20.1 code
will be resilient to this change, because the Name of the new namespace
descriptor is never read by 20.1.

One more detail is that this commit changes the migration key for the
migration that used to overwrite the old namespace descriptor's name
field, so that clusters that upgraded to an earlier 20.1 beta will stop
experiencing problems after changing to this version.

Release note (bug fix): fix reads from system.namespace and
crdb_internal.zones in 19.2 nodes in mixed cluster settings.

### CODE REVIEW

File: pkg/cli/zip.go [hunk 1]
```diff
@@ -64,7 +64,7 @@ var debugZipTablesPerCluster = []string{
 	"system.jobs",       // get the raw, restorable jobs records too.
 	"system.descriptor", // descriptors also contain job-like mutation state.
 	"system.namespace",
-	"system.namespace_deprecated", // TODO(sqlexec): consider removing in 20.2 or later.
+	"system.namespace_with_parent_schema", // TODO(sqlexec): consider removing in 20.2 or later.
```
Comment (knz) [inline pkg/cli/zip.go:67]: is it worth keeping `system.namespace_deprecated` alongside this, so that we get a full picture for those few customers that happen to have both? (Unless you have some confidence that your PR prevents this from even being possible)

**Review by knz — COMMENTED** [review]
Thanks for the analysis and construction of a solution.
The trick with `[%d AS namespace]` is :100: clever.

nit in commit message:

> which is that the new
descriptor has a different Name than its actual table name, which
remains "descriptor"

I suppose you mean "which remains 'namespace'"? ditto for the other reference below in the commit message.

**Review by petermattis — COMMENTED** [review]
Glad to see a fix for this put together so fast.

I'm not fond of the `namespace_with_parent_schema` name. That might be a personal gripe, but wanted to mention it in case anyone else feels similarly. I would have personally gone with something like `namespace2`. I don't feel super strongly about this, though. Feel free to ignore.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/47173#-:-M4OpTnx6AL_DXm17AZJ:bq9intd)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dt, @jordanlewis, @lucy-zhang, and @rohany)

___
*[pkg/ccl/importccl/load.go, line 62 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/47173#-M4OivkbDm2iJDRuhIF3:-M4OivkbDm2iJDRuhIF4:b-emuwia) ([raw file](https://github.com/cockroachdb/cockroach/blob/bfe6991bd67b584164b500b55fef5acf0eb27d21/pkg/ccl/importccl/load.go#L62)):*
> ```Go
> 		extraClause string
> 	}{
> 		{fmt.Sprintf("[%d AS namespace]", keys.NamespaceTableID), `AND "parentSchemaID" = 0`},
> ```

`tableName` is being aliased to `n` in the query. I think you want to keep the `n."parentSchemaID"`. It might be clearer to change the `tableName` to `[%d AS n]` and drop the alias to `n` in the query.
___
*[pkg/cli/sql_util_test.go, line 132 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/47173#-M4OlicoAq7lW8Hv1jBd:-M4OlicoAq7lW8Hv1jBe:b3or2na) ([raw file](https://github.com/cockroachdb/cockroach/blob/bfe6991bd67b584164b500b55fef5acf0eb27d21/pkg/cli/sql_util_test.go#L132)):*
> ```Go
> 	b.Reset()
> 
> 	// Use system database for sample query/output as they are fairly fixed.
> ```

This common is somewhat inaccurate in hindsight.
___
*[pkg/sql/sqlbase/metadata.go, line 254 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/47173#-M4Op30n5Hl0rX6u-4oy:-M4Op30n5Hl0rX6u-4oz:b-6ol6hg) ([raw file](https://github.com/cockroachdb/cockroach/blob/bfe6991bd67b584164b500b55fef5acf0eb27d21/pkg/sql/sqlbase/metadata.go#L254)):*
> ```Go
> 		// namespace table's Name to "namespace" again.
> 		// TODO(solon): remove this in 20.2.
> 		if d.desc.GetID() == keys.NamespaceTableID {
> ```

`s/d.desc.GetID()/t.ID`. It is quite confusing to see two different names being used for the same value in such close proximity.
___
*[pkg/sql/sqlbase/metadata.go, line 255 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/47173#-M4OmjFc-fp_hebnopEq:-M4OmjFc-fp_hebnopEr:b-zbumgx) ([raw file](https://github.com/cockroachdb/cockroach/blob/bfe6991bd67b584164b500b55fef5acf0eb27d21/pkg/sql/sqlbase/metadata.go#L255)):*
> ```Go
> 		// TODO(solon): remove this in 20.2.
> 		if d.desc.GetID() == keys.NamespaceTableID {
> 			cache[NamespaceTableName] = t.ID
> ```

Btw, I think this only works because the deprecated namespace table has already been added to the cache (i.e. it occurred earlier in `ms.descs`). Not sure if it is worthwhile, but you could alleviate that fragility by doing this in a defer block:

```
if t.ID == keys.NamespaceTableID {
  defer func() {
    cache[NamespaceTableName] = t.ID
  }()
  continue
}
```

File: pkg/sql/logictest/testdata/logic_test/crdb_internal [hunk 2]
```diff
@@ -75,10 +75,10 @@ table_id parent_id name type target_id target_name state direction
 
 # We don't select the modification time as it does not remain contant.
 query IITTITTTTTTT colnames
-SELECT table_id, parent_id, name, database_name, version, format_version, state, sc_lease_node_id, sc_lease_expiration_time, drop_time, audit_mode, schema_name FROM crdb_internal.tables WHERE NAME = 'namespace'
+SELECT table_id, parent_id, name, database_name, version, format_version, state, sc_lease_node_id, sc_lease_expiration_time, drop_time, audit_mode, schema_name FROM crdb_internal.tables WHERE NAME = 'descriptor'
```
Comment (rohany) [inline pkg/sql/logictest/testdata/logic_test/crdb_internal:78]: should we test name = namespace here still, but the output id = 2?

File: pkg/sqlmigrations/migrations.go [hunk 3]
```diff
@@ -1262,7 +1273,7 @@ func createNewSystemNamespaceDescriptor(ctx context.Context, r runner) error {
 		//    the correct ID in the new system.namespace table after all tables are
 		//    copied over.
 		nameKey := sqlbase.NewPublicTableKey(
-			sqlbase.NamespaceTable.GetParentID(), sqlbase.NamespaceTable.GetName())
+			sqlbase.NamespaceTable.GetParentID(), sqlbase.NamespaceTableName)
```
Comment (rohany) [inline pkg/sqlmigrations/migrations.go:1276]: This change seems wrong -- we want to write the new tables name, not 'namespace' here

File: pkg/sqlmigrations/migrations.go [hunk 4]
```diff
@@ -1239,8 +1249,9 @@ func createNewSystemNamespaceDescriptor(ctx context.Context, r runner) error {
 		b := txn.NewBatch()
 
 		// Retrieve the existing namespace table's descriptor and change its name to
-		// "namespace_deprecated". This prevents name collisions with the new
-		// namespace table, for instance during backup.
+		// "namespace". This corrects the behavior of this migration as it existed
+		// in 20.1 betas. The old namespace table cannot be edited without breaking
+		// explicit selects from system.namespace in 19.2.
```
Comment (rohany) [inline pkg/sqlmigrations/migrations.go:1254]: Shouldn't we get rid of this part of the migration -- all it is doing is writing the same name back to the deprecated namespace table

**Review by jordanlewis — COMMENTED** [review]
Moved to namespace2. Updated the commit message, thanks Raphael. 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/47173#-:-M4P_ujyA1glQEktdGYo:b-jdh2gy)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dt, @knz, @lucy-zhang, @petermattis, and @rohany)

___
*[pkg/ccl/importccl/load.go, line 62 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/47173#-M4OivkbDm2iJDRuhIF3:-M4PRMxN9MDTR8pjm8zO:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/bfe6991bd67b584164b500b55fef5acf0eb27d21/pkg/ccl/importccl/load.go#L62)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

`tableName` is being aliased to `n` in the query. I think you want to keep the `n."parentSchemaID"`. It might be clearer to change the `tableName` to `[%d AS n]` and drop the alias to `n` in the query.
</blockquote></details>

Done.
___
*[pkg/cli/sql_util_test.go, line 132 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/47173#-M4OlicoAq7lW8Hv1jBd:-M4PRNkj9Qw43SlJSOWX:bb77ufg) ([raw file](https://github.com/cockroachdb/cockroach/blob/bfe6991bd67b584164b500b55fef5acf0eb27d21/pkg/cli/sql_util_test.go#L132)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

This common is somewhat inaccurate in hindsight.
</blockquote></details>

Yes.
___
*[pkg/cli/zip.go, line 67 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/47173#-M4NJeyT5DPCoI6yARzC-r2-67:-M4PRPtXE5JiUTsVoKm8:b-52yk3d) ([raw file](https://github.com/cockroachdb/cockroach/blob/bfe6991bd67b584164b500b55fef5acf0eb27d21/pkg/cli/zip.go#L67)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

is it worth keeping `system.namespace_deprecated` alongside this, so that we get a full picture for those few customers that happen to have both? (Unless you have some confidence that your PR prevents this from even being possible)
</blockquote></details>

I would say no. The awkward thing about this entire migration is that `namespace_deprecated` never "truly exists" as a thing. You can't read from it. It's just the Name of the descriptor. In hindsight, this is extremely confusing.
___
*[pkg/sql/logictest/testdata/logic_test/crdb_internal, line 78 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/47173#-M4NUXhWPzsvCdkDxy8S-r2-78:-M4PRj8wD14oGa7Iba6E:b-eki9sj) ([raw file](https://github.com/cockroachdb/cockroach/blob/bfe6991bd67b584164b500b55fef5acf0eb27d21/pkg/sql/logictest/testdata/logic_test/crdb_internal#L78)):*
<details><summary><i>Previously, rohany (Rohan Yadav) wrote…</i></summary><blockquote>

should we test name = namespace here still, but the output id = 2?
</blockquote></details>

I moved it to descriptor because it was easier than having to fix this test, which is hard to fix because crdb_internal.tables does odd things to figure out the name of the table.
___
*[pkg/sql/sqlbase/metadata.go, line 254 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/47173#-M4Op30n5Hl0rX6u-4oy:-M4PRvvp2ZW1a0uZh2Pz:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/bfe6991bd67b584164b500b55fef5acf0eb27d21/pkg/sql/sqlbase/metadata.go#L254)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

`s/d.desc.GetID()/t.ID`. It is quite confusing to see two different names being used for the same value in such close proximity.
</blockquote></details>

Done.
___
*[pkg/sql/sqlbase/metadata.go, line 255 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/47173#-M4OmjFc-fp_hebnopEq:-M4PS9JK4S7Lovf6Hu_j:brz334p) ([raw file](https://github.com/cockroachdb/cockroach/blob/bfe6991bd67b584164b500b55fef5acf0eb27d21/pkg/sql/sqlbase/metadata.go#L255)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

Btw, I think this only works because the deprecated namespace table has already been added to the cache (i.e. it occurred earlier in `ms.descs`). Not sure if it is worthwhile, but you could alleviate that fragility by doing this in a defer block:

```
if t.ID == keys.NamespaceTableID {
  defer func() {
    cache[NamespaceTableName] = t.ID
  }()
  continue
}
```
</blockquote></details>

Great point, thanks.
___
*[pkg/sqlmigrations/migrations.go, line 1254 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/47173#-M4N4gWMeDZpN4bsZG0M-r2-1254:-M4PSZRU4FkCk7ee63fA:bcx6bgx) ([raw file](https://github.com/cockroachdb/cockroach/blob/bfe6991bd67b584164b500b55fef5acf0eb27d21/pkg/sqlmigrations/migrations.go#L1254)):*
<details><summary><i>Previously, rohany (Rohan Yadav) wrote…</i></summary><blockquote>

Shouldn't we get rid of this part of the migration -- all it is doing is writing the same name back to the deprecated namespace table
</blockquote></details>

The comment explains why we're doing this. It's so that people who upgraded to previous 20.1 betas don't stay broken once the complete the upgrade to 20.1.
___
*[pkg/sqlmigrations/migrations.go, line 1276 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/47173#-M4N4gWMeDZpN4bsZG0M-r2-1276:-M4PSpn24bxM8Rq_1v0X:b-kd4yi) ([raw file](https://github.com/cockroachdb/cockroach/blob/bfe6991bd67b584164b500b55fef5acf0eb27d21/pkg/sqlmigrations/migrations.go#L1276)):*
<details><summary><i>Previously, rohany (Rohan Yadav) wrote…</i></summary><blockquote>

This change seems wrong -- we want to write the new tables name, not 'namespace' here
</blockquote></details>

No, we want to write `namespace` here. The new table's name is never actually exposed to the user. The user can only see `system.namespace`. `system.namespace` resolves to the old table until 20.1 is finalized - once it's finalized, it resolves to the new table.

**Review by jordanlewis — COMMENTED** [review]
One remaining major problem with this commit (well, with the migration as a whole - this was true before my commit as well) is that users cannot read `system.namespace2` directly. They can only read `system.namespace`, which resolves to the old table until 20.1 is finalized, and to the new table when it is finalized.

However, the introspection tables contain both tables, because the introspection tables work by reading all descriptors and using their `Name` fields as the source of truth. This is confusing for both test output and potentially for users. I'm not sure if we can realistically deal with this problem right now, or whether we need to, though.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/47173#-:-M4PagavBXvdwI8WI6QG:b-4j2mb3)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dt, @knz, @lucy-zhang, @petermattis, and @rohany)

**Review by jordanlewis — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/47173)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dt, @knz, @lucy-zhang, @petermattis, and @rohany)

___
*[pkg/sql/sqlbase/metadata.go, line 255 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/47173#-M4OmjFc-fp_hebnopEq:-M4PbYKR2JC5IGniFAK4:b-lf1oeu) ([raw file](https://github.com/cockroachdb/cockroach/blob/bfe6991bd67b584164b500b55fef5acf0eb27d21/pkg/sql/sqlbase/metadata.go#L255)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

Great point, thanks.
</blockquote></details>

I updated this to just unconditionally edit the cache after the loop.

**Review by petermattis — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/47173)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dt, @knz, @lucy-zhang, and @rohany)

___
*[pkg/sql/sqlbase/metadata.go, line 255 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/47173#-M4OmjFc-fp_hebnopEq:-M4Pfv11CNijBRMlNI7K:b6sqqtx) ([raw file](https://github.com/cockroachdb/cockroach/blob/bfe6991bd67b584164b500b55fef5acf0eb27d21/pkg/sql/sqlbase/metadata.go#L255)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

I updated this to just unconditionally edit the cache after the loop.
</blockquote></details>

Ack. Even better than my suggestion.

**Review by ajwerner — APPROVED** [review]
:lgtm: 

This change makes sense to me. I'd like somebody else to also give it a good look too. 

> Reviewed 1 of 2 files at r1, 17 of 18 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/47173#-:-M4Q4Az_4I6r_bSzQDg3:bbp82qw)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @dt, @knz, @lucy-zhang, and @rohany)

___
*[pkg/sql/sqlbase/system.go, line 419 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/47173#-M4Q4Q-m5Me34by_N7pd:-M4Q4Q-m5Me34by_N7pe:bcspw4q) ([raw file](https://github.com/cockroachdb/cockroach/blob/0b89fd835c1d1023daa3fe2ecc6dc98b9c52c9cb/pkg/sql/sqlbase/system.go#L419)):*
> ```Go
> 	// back to "namespace".
> 	NamespaceTable = TableDescriptor{
> 		Name:                    "namespace2",
> ```

I could see making a const for this one too.

**Comment by jordanlewis** [comment]
I've skipped the `acceptance/version-upgrade` test, which seems to be failing on a 19.1 to 19.2 upgrade. I believe that this failure is a flake that has nothing to do with this test:

```
ERROR: cockroach server exited with error: store <no-attributes>=/home/roach/local/4/data, last used with cockroach version v19.1, is too old for running version v19.2-17 (which requires data from v19.1-1 or later)
```

@tbg I'm pointing this out, I think you changed this recently. Normally I'd investigate, but we've got to get this in soon.

**Comment by jordanlewis** [comment]
Yay tests passed.

File: pkg/sqlmigrations/migrations.go (hunk 4 above)
Comment (dt) [reply pkg/sqlmigrations/migrations.go:1293]: +1

**Review by dt — COMMENTED** [review]
LGTM except share @rohany's quesitons about the migration still writing to the old table at all?

**Comment by jordanlewis** [comment]
I wrote in Reviewable, which I guess doesn't sync back to GitHub, but the reason we write to the old table again is so that people who upgraded to previous 20.1 betas don't stay broken once the complete the upgrade to 20.1.

**Review by dt — APPROVED** [review]
Oh, good catch.

**Comment by jordanlewis** [comment]
TFTRs 🙏 

bors r+
