### PR TITLE
spanset: assert read-only batches don't access store local and unreplicated RangeID local keys

### LINKED ISSUE #156537: kvserver: assert on log engine keys in eval
For RSE, we want the invariant that command evaluation at the leaseholder produces batches that can only touch state machine engine keys. Or, easier to enumerate (there are only 3), it should not touch the raft engine keys.

https://github.com/cockroachdb/cockroach/blob/345a86b3fd12440eb33ad3f4bdd438032ea758c4/pkg/keys/doc.go#L191-L211

We know of 2 exceptions when raft engine keys are written into the eval batch, and work around them. For confidence, it would be good to confirm that there no other exceptions, or find all.

The mechanism to do that would be similar to the `spanset.Batch` here, which asserts on keys in relation to the latches: 

https://github.com/cockroachdb/cockroach/blob/345a86b3fd12440eb33ad3f4bdd438032ea758c4/pkg/kv/kvserver/replica_write.go#L811-L818

Epic: CRDB-55220

Jira issue: CRDB-56053

### PR DESCRIPTION
**Pull request by iskettaneh**
spanset: assert read-only batches don't access store local and unreplicated RangeID local keys

Similar to what we did in #157153, this commit does the same
but for read-only batches.

Testing showed no failures.

Fixes: #156537

Release note: none

### CODE REVIEW

File: pkg/kv/kvserver/replica.go [hunk 1]
```diff
@@ -2984,3 +2985,66 @@ func (r *Replica) SendStreamStats(stats *rac2.RangeSendStreamStats) {
 		r.flowControlV2.SendStreamStats(stats)
 	}
 }
+
+// overlapsUnreplicatedRangeIDLocalKeys checks if the provided span overlaps
+// with any unreplicated rangeID local keys.
+// Note that we could receive the span with a nil startKey, which has a special
+// meaning that the span represents: [endKey.Prev(), endKey).
+func overlapsUnreplicatedRangeIDLocalKeys(span spanset.TrickySpan) error {
```
Comment (pav-kv) [inline pkg/kv/kvserver/replica.go]: I assume this is just a mechanical move.

`replica.go` seems too generic, maybe place it in `replica_raftstorage.go`? At some point, we might want to have it in `kvserver` package where our storage access / separation stuff is. So, alternatively, place it right there?

**Review by pav-kv — APPROVED** [review]

**Comment by pav-kv** [comment]
For some time next (I'll file an issue): I'm thinking we could hide this asserter wrapping inside `StateEngine()` (and the equivalent of it in `LogEngine()`), so that all their uses would inherit this checking automatically. This would give the strongest confidence in that we haven't forgotten about any exceptions anywhere.

File: pkg/kv/kvserver/replica.go (hunk 1 above)
Comment (iskettaneh) [reply pkg/kv/kvserver/replica.go]: Done.

**Review by iskettaneh — COMMENTED** [review]
Agreed that having them inside the engine somehow gives us better confidence that all accesses are validated.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/158204#-:-OeqMvg-2jLsSSfudpFi:b4h8tlq)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @pav-kv)
