### PR TITLE
ui: De-duplicate and clarify time selection state

### LINKED ISSUE #75579: De-duplicate state on `timeScaleDropdown`
There are [two properties](https://github.com/cockroachdb/cockroach/blob/f18fe733c724cf51bffcde0535caa5d4bab7fa6c/pkg/ui/workspaces/db-console/src/redux/timewindow.ts#L57) on `timewindow` state, `scale` and `currentWindow`. It seems like the selected `start` and `end` times could be derived from either property. Either by reading `start` and `end` from `currentWindow`, or by reading `start = `windowEnd - windowSize` and `windowEnd` from `scale`.

In general, having duplicate sources of truth risks bugs from discrepant update cycles, and confusion about when to read from which one. And if they are not duplicates of each other, it is unclear what the distinction is and thus when to update or read from each one.

`currentWindow` was [introduced](https://github.com/cockroachdb/cockroach/pull/6790) in May 2016, and `windowEnd` on `scale` was [introduced](https://github.com/cockroachdb/cockroach/commit/7ab4eced2281861f3a894eb0435c08b3d48ecd8b#diff-b8f21fe8ebe00ca9cae54ffbc2ac45de62df40df568d45a303be9c4dffb45fd0R39) in December 2016 (both authors no longer work at CRL). Today, multiple [places](https://github.com/cockroachdb/cockroach/blob/master/pkg/ui/workspaces/cluster-ui/src/transactionsPage/transactionsPage.tsx#L113) in the code use the `toDateRange` function to derive start and end time from timescale (instead of using `currentWindow`). Further, the time picker is used in the statements and transactions page without storing the `currentWindow` state in redux at all; only `scale` is implemented. A few places use `currentWindow`, and one has a [comment](https://github.com/cockroachdb/cockroach/blob/master/pkg/ui/workspaces/db-console/src/views/shared/containers/metricDataProvider/index.tsx#L258) where `currentWindow` is used to fix a bug because `scale` was incorrect and out of sync.

It would be great if the two states could be de-duplicated without regressions (or made clearer what the distinction is, if any). This would also help https://github.com/cockroachdb/cockroach/issues/72128, to not have to also implement `currentWindow`.

### PR DESCRIPTION
**Pull request by jocrl**
Resolves https://github.com/cockroachdb/cockroach/issues/75579. This is an entirely internal refactor. https://github.com/cockroachlabs/managed-service/pull/7998 makes companion changes in managed-service.

Suggestions from comments from this PR review have been separated into [this issue](https://github.com/cockroachdb/cockroach/issues/76593).

# Commits

## Commit 1 ui: Always write to `windowEnd` on `scale`; read from `scale` for the metrics graph.

Partially addresses #75579

Previously, `windowEnd` on `scale` was not always written to, meaning that it was not always safe/correct to read off the `scale` property. `currentWindow` wasn't always safe to use either.

This commit modifies `windowEnd` to always be set, by making it an non-optional property and letting Typescript do the enforcement. It also modifies the metrics page graph to read from `scale` instead of `currentWindow`

There was a [comment](https://github.com/cockroachdb/cockroach/blob/master/pkg/ui/workspaces/db-console/src/views/shared/containers/metricDataProvider/index.tsx#L258) where `currentWindow` is used to fix a bug on the metrics page because `scale` was incorrect and out of sync. This commit does not regress that drag-to-zoom bug.

Side note about the bug: at the code state when the #70594 bug was fixed, the `windowEnd` property was not set (this commit changes `linegraph/index.tsx` to set it). Yet, even without changing `linegraph/index.tsx` to set `windowEnd`, reading the start and end times from `scale` did not recreate the drag-to-zoom granularity bug. However, reading from `scale` without setting `windowEnd` does cause a separate major bug in that the timescale endpoint is always queried with `now` as an end time instead of the time that the user selected and is displayed. This PR does not have this bug.

Release note: None

## Commit 2 ui: Make `currentWindow.end` the single source of truth

Partially addresses #75579

Previously, there are [two properties](https://github.com/cockroachdb/cockroach/blob/f18fe733c724cf51bffcde0535caa5d4bab7fa6c/pkg/ui/workspaces/db-console/src/redux/timewindow.ts#L57) on `timewindow` state, `scale` and `currentWindow`. They seemed like duplicates (see https://github.com/cockroachdb/cockroach/issues/75579 issue for further explanation). It was unclear what the distinction was, if any.

1) `currentWindow` is not used in cluster-ui
- In cluster-ui, the `currentWindow` property on state is only ever read from in [this test](https://github.com/cockroachdb/cockroach/blob/f18fe733c724cf51bffcde0535caa5d4bab7fa6c/pkg/ui/workspaces/cluster-ui/src/timeScaleDropdown/timescale.spec.tsx#L73). Further, the local variable that it is assigned to is immediately overwritten in the line right after. So to say, cluster-ui does not use the `currentWindow` state, even if there are a lot of local variables that are named `currentWindow`. `TimeWindow` is used as a type, but is not used on state.

2) `currentWindow.end` differs from `scale.windowEnd` in that the former is always a specific time which is used to do polling in the db console metrics page
- Users may select that they want the end time to be "now", or a specific end time. When "now" is selected, `scale.windowEnd` is `null`, and `currentWindow.end` is a specific time, e.g. 3.51pm on a Monday. `currentWindow.end` is continually updated according to the `windowValid` frequency on the closest `DefaultTimeScaleOption`. The continual update of `currentWindow.end` is used to poll for new data for graphs on the metrics page.
- There are two other places where the time selection component is used: the serverless metrics page (which is a completely different component from the db console metrics page), and the statements and transactions pages. Both of these other usages use completely different polling mechanisms that do not rely on `currentWindow.end` (and actually, also don't use the `windowValid` frequency).
- So to say, `currentWindow.end` is only used for the db console metrics page. `scaleChanged` and `useTimeRange` are also only used for the db console metrics page, and help with bookkeeping around updating `currentWindow.end`.

This commit thus
- deletes the `currentWindow`, `scaleChanged`, and `useTimeRange` states in cluster-ui
- nests the `currentWindow`, `scaleChanged`, and `useTimeRange` states under the `metricsTime` property in db-console

Release note: None

## Commit 3 ui: Rename variables and add comments

Finishes addressing #75579

This commit adds comments and renames various variables to better reflect their meaning and usage. https://github.com/cockroachlabs/managed-service/pull/7998 also renames `windowEnd` -> `fixedWindowEnd` in the managed-service repo.

The following renames were made:
- `scaleChanged` -> `shouldUpdateMetricsWindowFromScale`
- `useTimeRange` -> `isFixedWindow`
- `SET_WINDOW` -> `SET_METRICS_MOVING_WINDOW`, `setTimeWindow` -> `setMetricsMovingWindow`
- `SET_RANGE` -> `SET_METRICS_FIXED_WINDOW`, `setTimeRange` -> `setMetricsFixedWindow`
- `windowEnd` -> `fixedWindowEnd`, with its type changed from `moment.Moment | null` to `moment.Moment | false`. `false` indicates that the end time is a dynamically moving "now"
- `db-console/src/redux/timewindow.ts` -> `db-console/src/redux/timeScale.ts `, same for the sibling test file, `TimeWindowState` -> `TimeScaleState`, `timeWindowReducer` -> `timeScaleReducer`. To make it clear that the `scale` property is the state to use, and that `TimeWindow` is mostly just a type interface (except for the db console metrics page polling usage)
- `TimeWindowManager` -> `MetricsTimeManager`, `db-console/src/views/app/containers/timewindow/index.tsx` -> `db-console/src/views/app/containers/metricsTimeManager/index.tsx`, and the sibling test file. To distinguish from the `TimeWindow` type interface, name it for the main manager component in the file, and make it clear that this is just for the metrics page
- `db-console/src/views/cluster/containers/timescale/index.tsx` -> `db-console/src/views/cluster/containers/timeScaleDropdownWithSearchParams/index.tsx`, and the sibling `.styl` file

Release note: None

### CODE REVIEW

**Review by jocrl — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/75586)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dhartunian, @Santamaura, and @xinhaoz)

___
*[pkg/ui/workspaces/db-console/src/redux/timeScale.ts, line 74 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/75586#-MuNkVPd6ZrMi3ZedgZo:-MuNkVPe28qo2xhPB0CT:b-nw6cri) ([raw file](https://github.com/cockroachdb/cockroach/blob/528331762557f466e897ae7485601da65f43294b/pkg/ui/workspaces/db-console/src/redux/timeScale.ts#L74)):*
> ```XML
>     // True if currentWindow should be unchanging. False if
>     isFixedWindow: boolean;
>   };
> ```

In some ways the nesting doesn't feel right, because not everything in metricsTime is always updated together. I think this is a pattern that hooks help discourage. But I'm not familiar with redux patterns, and maybe with redux it's more common/recommended? I decided to do this as a cheap solution since this is already large, but open to other suggestions.



_Code quote:_
```XML
  metricsTime: {
    // Start and end times to be used for metrics page graphs
    currentWindow: TimeWindow;
    // True if scale has changed since currentWindow was generated, and it should be re-generated from scale
    shouldUpdateMetricsWindowFromScale: boolean;
    // True if currentWindow should be unchanging. False if
    isFixedWindow: boolean;
  };
```

**Review by maryliag — COMMENTED** [review]
Regarding your commit 0 suggestion with tests: the tests should be on the same commit where the change you would be testing was made

> Reviewed 11 of 26 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/75586#-:-MuQvJGLEjFHaQeSs8Eh:b-dv1o9h)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dhartunian, @jocrl, @Santamaura, and @xinhaoz)

___
*[-- commits, line 13 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/75586#-MuQveWODBVTIXE5WNPJ):*
nit: I'm assuming you will correct the messages here to include description, issue number, release note, etc
___
*[pkg/ui/workspaces/cluster-ui/src/timeScaleDropdown/utils.ts, line 115 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/75586#-MuQxuYNDIri0wBWDV93:-MuQxuYNDIri0wBWDV94:b-9vl9b1) ([raw file](https://github.com/cockroachdb/cockroach/blob/528331762557f466e897ae7485601da65f43294b/pkg/ui/workspaces/cluster-ui/src/timeScaleDropdown/utils.ts#L115)):*
> ```XML
>   // 0:00 to June 2 at 0:00 when the date is July 1 at 0:00 should return a custom timescale
>   // instead of past day.
>   // If the start is specified, and the window size matches
> ```

nit: add periods to your comments
___
*[pkg/ui/workspaces/db-console/src/redux/timeScale.ts, line 24 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/75586#-MuQyPjMAt_GJowJt8zF:-MuQyPjMAt_GJowJt8zG:b-vcs1f9) ([raw file](https://github.com/cockroachdb/cockroach/blob/528331762557f466e897ae7485601da65f43294b/pkg/ui/workspaces/db-console/src/redux/timeScale.ts#L24)):*
> ```XML
> export const SET_SCALE = "cockroachui/timewindow/SET_SCALE";
> export const SET_METRICS_MOVING_WINDOW = "cockroachui/timewindow/SET_WINDOW";
> export const SET_METRICS_FIXED_WINDOW = "cockroachui/timewindow/SET_RANGE";
> ```

can the values under `cockroachui/timewindow/` also be changed? I think it could be confusing having the two different const for the same thing
___
*[pkg/ui/workspaces/db-console/src/redux/timeScale.ts, line 66 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/75586#-MuQz15h5S_Zhyc08q2W:-MuQz15h5S_Zhyc08q2X:b-8i9mxa) ([raw file](https://github.com/cockroachdb/cockroach/blob/528331762557f466e897ae7485601da65f43294b/pkg/ui/workspaces/db-console/src/redux/timeScale.ts#L66)):*
> ```XML
>    *  Specifically, when the end is "now", scale.fixedWindowEnd is null and metricsTime.currentWindow.end is a specific time
>    *  that is continually updated in order to do polling.
>    */
> ```

can you make some way more clear the difference between comments you're adding just to ask questions during the review process and comments you intend to keep on the code itself?
___
*[pkg/ui/workspaces/db-console/src/redux/timeScale.ts, line 68 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/75586#-MuQzG-A-v-EvL3-VMgl:-MuQzG-A-v-EvL3-VMgm:b-7koouz) ([raw file](https://github.com/cockroachdb/cockroach/blob/528331762557f466e897ae7485601da65f43294b/pkg/ui/workspaces/db-console/src/redux/timeScale.ts#L68)):*
> ```XML
>    */
>   metricsTime: {
>     // Start and end times to be used for metrics page graphs
> ```

nit: period 
___
*[pkg/ui/workspaces/db-console/src/redux/timeScale.ts, line 72 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/75586#-MuQzINf9fMeWybUAwXP:-MuQzINf9fMeWybUAwXQ:b-4yp1g5) ([raw file](https://github.com/cockroachdb/cockroach/blob/528331762557f466e897ae7485601da65f43294b/pkg/ui/workspaces/db-console/src/redux/timeScale.ts#L72)):*
> ```XML
>     // True if scale has changed since currentWindow was generated, and it should be re-generated from scale
>     shouldUpdateMetricsWindowFromScale: boolean;
>     // True if currentWindow should be unchanging. False if
> ```

nit: false if?
___
*[pkg/ui/workspaces/db-console/src/views/app/containers/metricsTimeManager/index.tsx, line 28 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/75586#-MuQzipZ1MQcXFQUBssf:-MuQzipZ1MQcXFQUBssg:bf60mo5) ([raw file](https://github.com/cockroachdb/cockroach/blob/528331762557f466e897ae7485601da65f43294b/pkg/ui/workspaces/db-console/src/views/app/containers/metricsTimeManager/index.tsx#L28)):*
> ```XML
> }
> 
> interface MetricsTimeManagerState {
> ```

will we ever want to use this component for any other uses besides the Metrics page? What is the specific on this component that we want to use this for the Metrics page instead of the other component being used everywhere else?

**Review by jocrl — COMMENTED** [review]
Got it, thanks!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/75586#-:-MuRFEOS9jsF_8PPTs1L:bcr5s2o)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dhartunian, @maryliag, @Santamaura, and @xinhaoz)

___
*[-- commits, line 13 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/75586#-MuQveWODBVTIXE5WNPJ):*
<details><summary><i>Previously, maryliag (Marylia Gutierrez) wrote…</i></summary><blockquote>

nit: I'm assuming you will correct the messages here to include description, issue number, release note, etc
</blockquote></details>

Yup, I will before un-drafting
___
*[pkg/ui/workspaces/cluster-ui/src/timeScaleDropdown/timeScaleDropdown.tsx, line 182 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/75586#-MuRDIFL3ftv6AyvlgML:-MuRDIFL3ftv6AyvlgMM:b-3cld8a) ([raw file](https://github.com/cockroachdb/cockroach/blob/03370f374fb992e2299b50b4758797301ec161c0/pkg/ui/workspaces/cluster-ui/src/timeScaleDropdown/timeScaleDropdown.tsx#L182)):*
I'm very confused about the `fixedWindowEnd > moment.utc().subtract(currentScale.windowValid)` clause. What is this testing, and how is `windowValid` used here?
The only other usage of `windowValid` is in the db console metrics page, where it is used to do continuous polling. This seems like a different usage.

The existing comment confuses me in that:

> If the timescale extends into the future...

I almost wonder if the clause means to subtract windowSize (could be custom) instead of windowValid

> Otherwise set the key to "Custom" so it appears correctly

This seems to suggest that we allow end times in the future if the windowSize is not one of the defaults. However, I cannot hit this code.



_Code quote:_
```XML
    // If the timescale extends into the future then fallback to a default
    // timescale. Otherwise set the key to "Custom" so it appears correctly.
    if (
      !windowEnd ||
      windowEnd > moment.utc().subtract(currentScale.windowValid)
    ) {
```
___
*[pkg/ui/workspaces/cluster-ui/src/timeScaleDropdown/timeScaleTypes.ts, line 41 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/75586#-MuRF2KL4EuFh-VgkvEA:-MuRF2KL4EuFh-VgkvEB:b-7jpqh5) ([raw file](https://github.com/cockroachdb/cockroach/blob/528331762557f466e897ae7485601da65f43294b/pkg/ui/workspaces/cluster-ui/src/timeScaleDropdown/timeScaleTypes.ts#L41)):*
> ```XML
>   // is invalid if now > (currentWindow.end + windowValid). Default is ten
>   // seconds. If fixedWindowEnd is set this is ignored.
>   windowValid?: moment.Duration;
> ```

I want to modify the original comment below to reflect the actual `windowValid` in Cluster UI, but I don't understand the usage.
The original comment below (`now > (currentWindow.end + windowValid)`) describes the usage of `windowValid` in DB Console polling, which does not involve in this Cluster UI copy.
Instead, in Cluster UI is it used in the `arrowClick` function in `timeScaleDropdown.tsx`. I'm confused about that usage, and have added a comment-question there in `timeScaleDropdown.tsx`.



_Code quote:_
```XML
  // The length of time the global time window is valid. The current time window
  // is invalid if now > (currentWindow.end + windowValid). Default is ten
  // seconds. If fixedWindowEnd is set this is ignored.
  windowValid?: moment.Duration;
```
___
*[pkg/ui/workspaces/db-console/src/redux/timeScale.ts, line 24 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/75586#-MuQyPjMAt_GJowJt8zF:-MuR90xTB0E-PF5BEpr9:bc8flwk) ([raw file](https://github.com/cockroachdb/cockroach/blob/528331762557f466e897ae7485601da65f43294b/pkg/ui/workspaces/db-console/src/redux/timeScale.ts#L24)):*
<details><summary><i>Previously, maryliag (Marylia Gutierrez) wrote…</i></summary><blockquote>

can the values under `cockroachui/timewindow/` also be changed? I think it could be confusing having the two different const for the same thing
</blockquote></details>

Thanks, done
___
*[pkg/ui/workspaces/db-console/src/redux/timeScale.ts, line 66 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/75586#-MuQz15h5S_Zhyc08q2W:-MuRC25e5WYY1d71Tl24:bzcsd9w) ([raw file](https://github.com/cockroachdb/cockroach/blob/528331762557f466e897ae7485601da65f43294b/pkg/ui/workspaces/db-console/src/redux/timeScale.ts#L66)):*
<details><summary><i>Previously, maryliag (Marylia Gutierrez) wrote…</i></summary><blockquote>

can you make some way more clear the difference between comments you're adding just to ask questions during the review process and comments you intend to keep on the code itself?
</blockquote></details>

Yup! I've moved all my questions from the code to reviewable comments. Everything in the code is now comments that I intend to have.
___
*[pkg/ui/workspaces/db-console/src/views/app/containers/metricsTimeManager/index.tsx, line 28 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/75586#-MuQzipZ1MQcXFQUBssf:-MuRFXUR9m4p-ezh1zGo:borsju6) ([raw file](https://github.com/cockroachdb/cockroach/blob/528331762557f466e897ae7485601da65f43294b/pkg/ui/workspaces/db-console/src/views/app/containers/metricsTimeManager/index.tsx#L28)):*
> What is the specific on this component that we want to use this for the Metrics page instead of the other component being used everywhere else?

For comparison of everywhere else, the other two places of usage are currently the Statements and Transactions page, and the Severless Metrics page.

This component bakes in some specific assumptions that are only used in the DB Console Metrics page. They are:
1. The use of states on `timeScale.metricsTime` (the properties within it, not me naming it "metricsTime") in order to do polling. The Statements and Transactions, and severless Metrics pages use different mechanisms to do polling, and do not use the states that are hardcoded into the logic of this component.
2. The use of this component at all to do polling. This component works for polling by mounting a component that doesn't render anything. It's a weird pattern that I think comes from this being old 2016 code, that didn't have hooks available to share logic across components or sagas/thunk to do side effects. The Statements and Transactions, and severless Metrics pages both implement polling differently from both this component and each other, and there are even more other polling solutions scattered throughout db-console, cluster-ui, and managed-service. I don't know which polling solution would be recommended (that might be an interesting discussion to have). But I think component isn't the one to recommend.
3. Use of the `windowValid` property on the default time scale options (see `timeScaleDropdown/utils.ts`) as a polling frequency. The logic of this component and the `defaultTimeScaleOptions` assume that if the "Past 10 Minutes" is selected we want a 10 second polling frequency; if "Past 30 Minutes" is selected we want 30 seconds. This frequency is tailored particularly to the needs of the DB Console metrics page. It is way too frequent for the Statements and Transactions page, and I suspect also isn't used for the severless Metrics page. We could refactor things to decouple the polling frequency from this component, but due to reason 2 I'm more inclined to isolate this component and ignore it.

> Will we ever want to use this component for any other uses besides the Metrics page?

So yeah, given reason 2, I don't think we want to recommend this component as a solution for polling. If we do want to use this component for other uses in the future, I think it's better to leave it to that future usage to rename it and do the refactor (possibly taking into account use cases for that future use).
___
*[pkg/ui/workspaces/db-console/src/views/cluster/containers/timeScaleDropdownWithSearchParams/index.tsx, line 75 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/75586#-MuRDkzaCjC9fttDlmCG:-MuRDkzaCjC9fttDlmCH:b54zh2d) ([raw file](https://github.com/cockroachdb/cockroach/blob/528331762557f466e897ae7485601da65f43294b/pkg/ui/workspaces/db-console/src/views/cluster/containers/timeScaleDropdownWithSearchParams/index.tsx#L75)):*
I'm not clear what `sampleSize` means and how it is used here. Comments on the type defintion of `sampleSize` say it is:

> The expected duration of individual samples for queries at this time scale

This `if` block below says: if the time between now and the end (from query params, else now) is greater than the sample size.
I'm not clear what the meaning of this test is, and why it uses `sampleSize` (perhaps instead of windowSize?)



_Code quote:_
```XML
      if (
        moment.duration(now.diff(end)).asMinutes() >
        timeScale.sampleSize.asMinutes()
      ) {
```

**Review by jocrl — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/75586)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dhartunian, @maryliag, @Santamaura, and @xinhaoz)

___
*[pkg/ui/workspaces/cluster-ui/src/timeScaleDropdown/timeScaleDropdown.tsx, line 182 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/75586#-MuRDIFL3ftv6AyvlgML:-MuRL2mpEkGHeHyRc3Fg:b-w5gj4d) ([raw file](https://github.com/cockroachdb/cockroach/blob/03370f374fb992e2299b50b4758797301ec161c0/pkg/ui/workspaces/cluster-ui/src/timeScaleDropdown/timeScaleDropdown.tsx#L182)):*
<details><summary><i>Previously, jocrl (Josephine) wrote…</i></summary><blockquote>

I'm very confused about the `fixedWindowEnd > moment.utc().subtract(currentScale.windowValid)` clause. What is this testing, and how is `windowValid` used here?
The only other usage of `windowValid` is in the db console metrics page, where it is used to do continuous polling. This seems like a different usage.

The existing comment confuses me in that:

> If the timescale extends into the future...

I almost wonder if the clause means to subtract windowSize (could be custom) instead of windowValid

> Otherwise set the key to "Custom" so it appears correctly

This seems to suggest that we allow end times in the future if the windowSize is not one of the defaults. However, I cannot hit this code.
</blockquote></details>

edit: I'd like to understand the usage of `windowValid` in order to update the comment for this property in `timeScaleTypes.ts`

**Review by Azhng — COMMENTED** [review]
This is quite dense. I only took a look at the first commit, I will come back to keep on looking later today once I have time.

> Reviewed 3 of 26 files at r5.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/75586#-:-MuRZQpvBypdLYrYy9fX:bn54rpl)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @Azhng, @dhartunian, @jocrl, @maryliag, @Santamaura, and @xinhaoz)

___
*[pkg/ui/workspaces/cluster-ui/src/timeScaleDropdown/timeScaleDropdown.tsx, line 182 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/75586#-MuRDIFL3ftv6AyvlgML:-MuRQpOD4D-vOkg8iQ10:bra9kom) ([raw file](https://github.com/cockroachdb/cockroach/blob/03370f374fb992e2299b50b4758797301ec161c0/pkg/ui/workspaces/cluster-ui/src/timeScaleDropdown/timeScaleDropdown.tsx#L182)):*
<details><summary><i>Previously, jocrl (Josephine) wrote…</i></summary><blockquote>

edit: I'd like to understand the usage of `windowValid` in order to update the comment for this property in `timeScaleTypes.ts`
</blockquote></details>

Hmm looking at the `db-console` code, `windowValid` seems like should be really called `dataValidityDurationPastCurrentWindow`. 


```
                   window end              if now() is past this point, we need to issue another API call to load new data
                   v                       v
-------------------+-----------------------+------------+
^                  ^~~~~~~~~~~~~~~~~~~~~~~~~
window start       window valid duration
```


So, what this clause is checking, (that it seems like), can be rewrite as `if (windowEnd + valid duration > now() )`

In other word, I think what it's trying to do is, if we already have the time series data for the current time scale, we can just go ahead and use it.
___
*[pkg/ui/workspaces/db-console/src/views/cluster/containers/timeScaleDropdownWithSearchParams/index.tsx, line 75 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/75586#-MuRDkzaCjC9fttDlmCG:-MuRXlaW3xUDoeU4LGrp:b-qs46ic) ([raw file](https://github.com/cockroachdb/cockroach/blob/528331762557f466e897ae7485601da65f43294b/pkg/ui/workspaces/db-console/src/views/cluster/containers/timeScaleDropdownWithSearchParams/index.tsx#L75)):*
<details><summary><i>Previously, jocrl (Josephine) wrote…</i></summary><blockquote>

I'm not clear what `sampleSize` means and how it is used here. Comments on the type defintion of `sampleSize` say it is:

> The expected duration of individual samples for queries at this time scale

This `if` block below says: if the time between now and the end (from query params, else now) is greater than the sample size.
I'm not clear what the meaning of this test is, and why it uses `sampleSize` (perhaps instead of windowSize?)
</blockquote></details>

Hmm this really do puzzles me. The only case where `findClosestTimeScale` returns non `Custom` key is when it can find an option from the `TimeScaleCollection`, whose size exactly matches the `second` variable here. 

So, it seems like, the code is is trying to do a couple of following:
1. if `now < currentWindowEnd + sampleSize`, use the default time scale option, and do continuous polling
2. else, don't bother (hence the `Custom` key) 

This is quite confusing and it seems like some other places would use `windowValid` variable instead.

**Review by jocrl — COMMENTED** [review]
For sure, and it doesn't need to be today! There's no rush to look at this; I still need to write tests anyway. Thanks :)
It was definitely a brain exercise trying to understand the code, so I erred on more words trying to document my understanding. 100% appreciate suggestions to make things clearer and simpler.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/75586#-:-MuRdGRABwUmcG7nKUqM:bxi0bhe)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @Azhng, @dhartunian, @maryliag, @nathanstilwell, @Santamaura, and @xinhaoz)

___
*[pkg/ui/workspaces/cluster-ui/src/timeScaleDropdown/timeScaleDropdown.tsx, line 182 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/75586#-MuRDIFL3ftv6AyvlgML:-MuRkBDB2T0_6pQB2LcA:b-u9144s) ([raw file](https://github.com/cockroachdb/cockroach/blob/03370f374fb992e2299b50b4758797301ec161c0/pkg/ui/workspaces/cluster-ui/src/timeScaleDropdown/timeScaleDropdown.tsx#L182)):*
<details><summary><i>Previously, Azhng (Archer Zhang) wrote…</i></summary><blockquote>

Hmm looking at the `db-console` code, `windowValid` seems like should be really called `dataValidityDurationPastCurrentWindow`. 


```
                   window end              if now() is past this point, we need to issue another API call to load new data
                   v                       v
-------------------+-----------------------+------------+
^                  ^~~~~~~~~~~~~~~~~~~~~~~~~
window start       window valid duration
```


So, what this clause is checking, (that it seems like), can be rewrite as `if (windowEnd + valid duration > now() )`

In other word, I think what it's trying to do is, if we already have the time series data for the current time scale, we can just go ahead and use it.
</blockquote></details>

Hmmm. I agree with your interpretation of the `db-console` usage, and that makes sense to me (also the diagram is great!). For this `cluster-ui` usage, I agree with rewriting the if condition as `if (windowEnd + valid duration > now() )`. But what the rest of the block does if true, is to move the end of the window to start at now(). In other words,

If this:
```

                   window end      if now() is here
t0                 v               v
+------------------+---------------+-------------------+
^                  ^~~~~~~~~~~~~~~~~~~~~~~~~
window start       window valid duration
```

Turn it into this:
```
      window has been shifted       window end, == now()
t0     ---------->                 v
+----------------+-----------------+-------------------+
                 ^                  ^~~~~~~~~~~~~~~~~~~~~~~~~
                 window start       window valid duration
```

I can see a motivation of setting to now() in that you don't window end to be in the future. So e.g. if the windowEnd would exceed now(), just set it to now(). However, a more accurate test for whether moving the window right once will exceed now, is to test if `end + (distance between start and end) > now()`. And that would be checking `windowSize`, not `windowValid`.

For instance, in practice, `windowSize` for the default options is always bigger than `windowValid`. So the diagram for the if test looks like this:

```
t0  window size    window end      if now() is here
<----------------->v               v
+------------------+---------------+-------------------+
^                  ^~~~~~~~~~~~~   |
window start       window valid duration
                                   |
                   <----------------->
                   window size duration
```

In this edge case, adding the valid duration does not exceed now(), but adding the window size does. And shifting the whole window right once would bring us past `now()`. So I wonder `windowSize` is what this code means to be testing? It would mean that `windowValid` is only used for the db console metrics polling.

I tried to trigger this edge case in the code but didn't manage to. If someone else wants to try/I might try more later.
___
*[pkg/ui/workspaces/db-console/src/views/cluster/containers/timeScaleDropdownWithSearchParams/index.tsx, line 75 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/75586#-MuRDkzaCjC9fttDlmCG:-MuRniU--dABReulF9GL:b3ynevk) ([raw file](https://github.com/cockroachdb/cockroach/blob/528331762557f466e897ae7485601da65f43294b/pkg/ui/workspaces/db-console/src/views/cluster/containers/timeScaleDropdownWithSearchParams/index.tsx#L75)):*
Hmm. Yeah, so it seems to be saying if `windowEnd` is "close enough" to `now()`, just consider it `now()`. Where "close enough" is defined by being smaller that the sample size.

I'm not confident how "it is a moving now and we should do continuous polling" was determined in the past, but I'd like to make clearer by making it only controlled by the `fixedWindowEnd` property. I haven't thoroughly mapped out when`key: "Custom"` is or isn't in sync with that.

In my commit I always set `fixedWindowEnd = false` (i.e., moving now true), because three lines below `windowEnd = null` was always set.

I wonder if the conditional `"Custom"` key here mean that setting `fixedWindowEnd = false` should also be conditional...

FWIW, [this is where](https://github.com/cockroachdb/cockroach/pull/45493/files#diff-09192ae756bbd303eff95ca4b94f02b54ecb9c2fe98bf613ec4c933eabcbed22L216) the line was introduced. It looked like the previous code always set the `"Custom"` key, and the change was to fix the page not polling. (Which is also a bug I hit sometimes while refactoring! Excited to test 😛).

That PR also include a quote from @nathanstilwell that

> this code is pretty complex and takes time to wrap my head around

so we're not alone hahaha. This is the second time Nathan that I'm seeing your review on a time component PR, so added you as a reviewer to this too.

**Review by jocrl — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/75586)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @Azhng, @dhartunian, @maryliag, @nathanstilwell, @Santamaura, and @xinhaoz)

___
*[pkg/ui/workspaces/db-console/src/views/cluster/containers/timeScaleDropdownWithSearchParams/index.tsx, line 75 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/75586#-MuRDkzaCjC9fttDlmCG:-MuRrgK9As7_joc8s6-X:b17haem) ([raw file](https://github.com/cockroachdb/cockroach/blob/528331762557f466e897ae7485601da65f43294b/pkg/ui/workspaces/db-console/src/views/cluster/containers/timeScaleDropdownWithSearchParams/index.tsx#L75)):*
<details><summary><i>Previously, jocrl (Josephine) wrote…</i></summary><blockquote>

Hmm. Yeah, so it seems to be saying if `windowEnd` is "close enough" to `now()`, just consider it `now()`. Where "close enough" is defined by being smaller that the sample size.

I'm not confident how "it is a moving now and we should do continuous polling" was determined in the past, but I'd like to make clearer by making it only controlled by the `fixedWindowEnd` property. I haven't thoroughly mapped out when`key: "Custom"` is or isn't in sync with that.

In my commit I always set `fixedWindowEnd = false` (i.e., moving now true), because three lines below `windowEnd = null` was always set.

I wonder if the conditional `"Custom"` key here mean that setting `fixedWindowEnd = false` should also be conditional...

FWIW, [this is where](https://github.com/cockroachdb/cockroach/pull/45493/files#diff-09192ae756bbd303eff95ca4b94f02b54ecb9c2fe98bf613ec4c933eabcbed22L216) the line was introduced. It looked like the previous code always set the `"Custom"` key, and the change was to fix the page not polling. (Which is also a bug I hit sometimes while refactoring! Excited to test 😛).

That PR also include a quote from @nathanstilwell that

> this code is pretty complex and takes time to wrap my head around

so we're not alone hahaha. This is the second time Nathan that I'm seeing your review on a time component PR, so added you as a reviewer to this too.
</blockquote></details>

edit: added comments on the type definitions about `key: "Custom"` and `fixedWindowEnd` being in sync, and a note to make an issue about possibly de-duplicating them

**Review by Azhng — COMMENTED** [review]
> Reviewed 3 of 6 files at r6.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/75586)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @Azhng, @dhartunian, @jocrl, @maryliag, @nathanstilwell, @Santamaura, and @xinhaoz)

___
*[pkg/ui/workspaces/cluster-ui/src/timeScaleDropdown/timeScaleDropdown.tsx, line 182 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/75586#-MuRDIFL3ftv6AyvlgML:-MuSelhjAr_iu8OtOGvH:bngqyd1) ([raw file](https://github.com/cockroachdb/cockroach/blob/03370f374fb992e2299b50b4758797301ec161c0/pkg/ui/workspaces/cluster-ui/src/timeScaleDropdown/timeScaleDropdown.tsx#L182)):*
<details><summary><i>Previously, jocrl (Josephine) wrote…</i></summary><blockquote>

Hmmm. I agree with your interpretation of the `db-console` usage, and that makes sense to me (also the diagram is great!). For this `cluster-ui` usage, I agree with rewriting the if condition as `if (windowEnd + valid duration > now() )`. But what the rest of the block does if true, is to move the end of the window to start at now(). In other words,

If this:
```

                   window end      if now() is here
t0                 v               v
+------------------+---------------+-------------------+
^                  ^~~~~~~~~~~~~~~~~~~~~~~~~
window start       window valid duration
```

Turn it into this:
```
      window has been shifted       window end, == now()
t0     ---------->                 v
+----------------+-----------------+-------------------+
                 ^                  ^~~~~~~~~~~~~~~~~~~~~~~~~
                 window start       window valid duration
```

I can see a motivation of setting to now() in that you don't window end to be in the future. So e.g. if the windowEnd would exceed now(), just set it to now(). However, a more accurate test for whether moving the window right once will exceed now, is to test if `end + (distance between start and end) > now()`. And that would be checking `windowSize`, not `windowValid`.

For instance, in practice, `windowSize` for the default options is always bigger than `windowValid`. So the diagram for the if test looks like this:

```
t0  window size    window end      if now() is here
<----------------->v               v
+------------------+---------------+-------------------+
^                  ^~~~~~~~~~~~~   |
window start       window valid duration
                                   |
                   <----------------->
                   window size duration
```

In this edge case, adding the valid duration does not exceed now(), but adding the window size does. And shifting the whole window right once would bring us past `now()`. So I wonder `windowSize` is what this code means to be testing? It would mean that `windowValid` is only used for the db console metrics polling.

I tried to trigger this edge case in the code but didn't manage to. If someone else wants to try/I might try more later.
</blockquote></details>

Hmm just to confirm, you are trying to trigger the `else` clause of the `if (foundTiemScale)` condition right? 
___
*[pkg/ui/workspaces/cluster-ui/src/timeScaleDropdown/timeScaleDropdown.tsx, line 163 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/75586#-MuSfSas6SN-hPyLuPyx:-MuSfSas6SN-hPyLuPyy:bhr6t3u) ([raw file](https://github.com/cockroachdb/cockroach/blob/ce14496edd67d463c89a1af7ea08d9e56603a344/pkg/ui/workspaces/cluster-ui/src/timeScaleDropdown/timeScaleDropdown.tsx#L163)):*
> ```XML
>     switch (direction) {
>       case ArrowDirection.RIGHT:
>         if (fixedWindowEnd) {
> ```

Hmm since `fixedWindowEnd` here is derived from `moment.utc(currentWindow.end)`, and `currentWindow.end` is derived from either `currentScaled.fixedWindowEnd` or `now` at the beginning of this component, the local variable of `fixedWindowEnd` ever be `null` ?

Or in other word, is this conditional check really needed? 


Or maybe that was the reason why you mentioned in another comment below where you couldn't seem to hit that edge case?
___
*[pkg/ui/workspaces/cluster-ui/src/timeScaleDropdown/timeScaleDropdown.tsx, line 171 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/75586#-MuSYTLb65-H69q-0F7z:-MuSYTLb65-H69q-0F8-:b7etorn) ([raw file](https://github.com/cockroachdb/cockroach/blob/ce14496edd67d463c89a1af7ea08d9e56603a344/pkg/ui/workspaces/cluster-ui/src/timeScaleDropdown/timeScaleDropdown.tsx#L171)):*
> ```XML
>         break;
>       case ArrowDirection.CENTER:
>         // CENTER is used to set the time window to the current time.
> ```

I noticed that we are making multiple calls to `moment.utc()` throughout this function. (e.g. `fixedWindowEnd = moment.utc()` and `fixedWindowEnd > moment.utc().subtract(currentScale.windowValid)`. 

This might be subtle but each call to `moment.utc()` creates a slightly different timestamp as time progresses. I think it's worth for us to just only call `moment.utc()` once at the beginning of this function and store that timestamp in a variable. 
___
*[pkg/ui/workspaces/db-console/src/redux/timeScale.ts, line 74 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/75586#-MuNkVPd6ZrMi3ZedgZo:-MuSXQyV33gYGWsbImj4:b-ujf0gx) ([raw file](https://github.com/cockroachdb/cockroach/blob/528331762557f466e897ae7485601da65f43294b/pkg/ui/workspaces/db-console/src/redux/timeScale.ts#L74)):*
<details><summary><i>Previously, jocrl (Josephine) wrote…</i></summary><blockquote>

In some ways the nesting doesn't feel right, because not everything in metricsTime is always updated together. I think this is a pattern that hooks help discourage. But I'm not familiar with redux patterns, and maybe with redux it's more common/recommended? I decided to do this as a cheap solution since this is already large, but open to other suggestions.
</blockquote></details>

Thoughts on inheriting the `cluster-ui`'s `TimeWindowState` and introducing new additional fields? 
___
*[pkg/ui/workspaces/db-console/src/redux/timeScale.ts, line 115 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/75586#-MuSc-oqBvR2AazhgxYP:-MuSc-oqBvR2AazhgxYQ:bjywvd9) ([raw file](https://github.com/cockroachdb/cockroach/blob/ce14496edd67d463c89a1af7ea08d9e56603a344/pkg/ui/workspaces/db-console/src/redux/timeScale.ts#L115)):*
> ```XML
>       } else {
>         state.metricsTime.isFixedWindow = false;
>       }
> ```

Hmm is there case where the payload explicitly has `isFixedWindow` field set?
___
*[pkg/ui/workspaces/db-console/src/redux/timeScale.ts, line 124 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/75586#-MuSbafw2BoR5WnBZY52:-MuSbafw2BoR5WnBZY53:bjx3ql) ([raw file](https://github.com/cockroachdb/cockroach/blob/ce14496edd67d463c89a1af7ea08d9e56603a344/pkg/ui/workspaces/db-console/src/redux/timeScale.ts#L124)):*
> ```XML
>       state = _.cloneDeep(state);
>       state.metricsTime.currentWindow = tw;
>       state.metricsTime.shouldUpdateMetricsWindowFromScale = false;
> ```

Should we also update `isFixedWindow = false` here?
___
*[pkg/ui/workspaces/db-console/src/views/app/containers/metricsTimeManager/index.tsx, line 19 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/75586#-MuScNd8CXBKSr22h7GV:-MuScNd8CXBKSr22h7GW:b-m2grim) ([raw file](https://github.com/cockroachdb/cockroach/blob/ce14496edd67d463c89a1af7ea08d9e56603a344/pkg/ui/workspaces/db-console/src/views/app/containers/metricsTimeManager/index.tsx#L19)):*
> ```XML
> import _ from "lodash";
> 
> interface MetricsTimeManagerProps {
> ```

Ah this is awesome! Having overlapping names across two package can really makes it confusing.

**Review by jocrl — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/75586)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @Azhng, @dhartunian, @jocrl, @maryliag, @nathanstilwell, @Santamaura, and @xinhaoz)

___
*[pkg/ui/workspaces/cluster-ui/src/timeScaleDropdown/utils.ts, line 119 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/75586#-MuSnPCm0jfPIHkHcl_k:-MuSnPCm0jfPIHkHcl_l:b-dyqmzy) ([raw file](https://github.com/cockroachdb/cockroach/blob/85950fa927d78f2c01c839fb27440eaaa159b73c/pkg/ui/workspaces/cluster-ui/src/timeScaleDropdown/utils.ts#L119)):*
> ```XML
>     // Check if the end is before now. If so, it is a custom time.
>     const end = moment.unix(startSeconds + seconds);
>     if (end < moment()) {
> ```

This is just a clarifying rewrite. I've added test cases for this block and they pass both before and after the change.



_Code quote:_
```XML
    // Check if the end is before now. If so, it is a custom time.

    const end = moment.unix(startSeconds + seconds);
    if (end < moment()) {
```
___
*[pkg/ui/workspaces/db-console/src/views/cluster/containers/timeScaleDropdownWithSearchParams/index.tsx, line 75 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/75586#-MuRDkzaCjC9fttDlmCG:-MuSlWnTCqEYVg19Pg-j:b-zae8g0) ([raw file](https://github.com/cockroachdb/cockroach/blob/528331762557f466e897ae7485601da65f43294b/pkg/ui/workspaces/db-console/src/views/cluster/containers/timeScaleDropdownWithSearchParams/index.tsx#L75)):*
<details><summary><i>Previously, jocrl (Josephine) wrote…</i></summary><blockquote>

edit: added comments on the type definitions about `key: "Custom"` and `fixedWindowEnd` being in sync, and a note to make an issue about possibly de-duplicating them
</blockquote></details>

Okay. Playing around with the difference in behavior between whether we include `sampleSize` in the comparison, I'm now more convinced by my "close enough" interpretation.

I believe that `sampleSize` here just provides a buffer. If the end is within the `sampleSize` tolerance, consider that close enough to now and just set things to now. This is because `findClosestTimeScale` only checks of the end is exactly equal to "now" . The use of the `sampleSize` buffer allows users to click left, click right, then quickly refresh and still have the dropdown selection as the past ten minutes instead of a fixed time frame. Using `sampleSize` instead of a fixed interval allows this tolerance buffer to be of different sizes depending on the size of the window, though I don't know if using specifically `sampleSize `is significant.

It does mean that I should set `fixedWindowEnd` to the end time. I've done so below, and added my explanation.

I am happy with this conclusion, unless anyone has anything else to add.

**Review by matthewtodd — COMMENTED** [review]
Agreed this is quite dense. I appreciate your taking the time to wrap your head around it all, @jocrl!

> Reviewed 26 of 26 files at r5, 6 of 6 files at r6, 20 of 26 files at r7, 3 of 3 files at r8, 3 of 3 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/75586#-:-MukjUSW3dXGblGVWyI7:b-tmuwmq)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dhartunian, @jocrl, @maryliag, @nathanstilwell, @Santamaura, and @xinhaoz)

___
*[pkg/ui/workspaces/db-console/src/redux/timeScale.ts, line 62 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/75586#-Muki6T24XXah7h7brEZ:-Muki6T31f6emxsAfTeH:b1prgpq) ([raw file](https://github.com/cockroachdb/cockroach/blob/85950fa927d78f2c01c839fb27440eaaa159b73c/pkg/ui/workspaces/db-console/src/redux/timeScale.ts#L62)):*
> ```XML
>    * It is unclear if there are legitimate reasons for the two being out of sync.
>    */
>   fixedWindowEnd: moment.Moment | false;
> ```

Seeing optional properties and reading through these usage instructions makes me wonder if it would be possible to hide this complexity inside an object somehow. I think there's enough in-flight on this PR that it wouldn't make sense to add here, just wanted to register the idea for the future.

**Review by jocrl — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/75586)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @Azhng, @dhartunian, @maryliag, @matthewtodd, @nathanstilwell, @Santamaura, and @xinhaoz)

___
*[pkg/ui/workspaces/cluster-ui/src/timeScaleDropdown/timeScaleDropdown.tsx, line 182 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/75586#-MuRDIFL3ftv6AyvlgML:-MukqZaYBq6AbOwFvwcj:ba2q7zq) ([raw file](https://github.com/cockroachdb/cockroach/blob/03370f374fb992e2299b50b4758797301ec161c0/pkg/ui/workspaces/cluster-ui/src/timeScaleDropdown/timeScaleDropdown.tsx#L182)):*
<details><summary><i>Previously, Azhng (Archer Zhang) wrote…</i></summary><blockquote>

Hmm just to confirm, you are trying to trigger the `else` clause of the `if (foundTiemScale)` condition right? 
</blockquote></details>

No, I'm not. I'm curious about that `else` block, but I'm not worried about that/it's not my main concern.

My main question is why `windowValid` is used here, in order to fix the comment on the `windowValid` type definition in `cluster-ui`. The comment that was previously there described it's usage in `db-console`. This is the only usage in `cluster-ui`, but it seems like this usage would be better off using `windowSize`. So I'm not sure what to put in the comments for `windowValid` on what it means.

It's just to try to fix misleading text in the comments. So, if this is confusing, I could just delete the comment line and describe our confusion instead.
___
*[pkg/ui/workspaces/cluster-ui/src/timeScaleDropdown/timeScaleDropdown.tsx, line 163 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/75586#-MuSfSas6SN-hPyLuPyx:-MukwFcQAmBha6jdO2mV:bot58t8) ([raw file](https://github.com/cockroachdb/cockroach/blob/ce14496edd67d463c89a1af7ea08d9e56603a344/pkg/ui/workspaces/cluster-ui/src/timeScaleDropdown/timeScaleDropdown.tsx#L163)):*
> Hmm since fixedWindowEnd here is derived from moment.utc(currentWindow.end), and currentWindow.end is derived from either currentScaled.fixedWindowEnd or now at the beginning of this component, the local variable of fixedWindowEnd ever be null ?
Or in other word, is this conditional check really needed?

Ah, agreed. I've renamed the local variable `s/fixedWindowEnd/endTime`, just to distinguish that it's not the `fixedWindowEnd` property. And I've added a comment explaining that we probably don't need the `if` block.

I'm trying not to change the logic of the code beyond the bare minimum that I need, unless it's something where the change is obviously equivalent and a comment would be more complicated. For potentially impossible code paths, I'm favoring adding comments instead of having to exhaustively verify that the path is not hit. Does just adding a comment sound good to you?

> Or maybe that was the reason why you mentioned in another comment below where you couldn't seem to hit that edge case?

Mmm, renaming the variable and knowing that it's always truthy does change how you see that `if` section. I've added a comment there that the first part of the `if` clause should always be true.

```
    if (!endTime || endTime > moment.utc().subtract(currentScale.windowValid)) {
```

I don't think it has to do with not being able to hit that edge case though (I still think that's cos of the right arrow being disabled when it would go through that code path). I'm not worried about hitting that edge case though, and talk more about this lack of worry in my reply for that.



_Code quote:_
```XML
 ArrowDirection.RIGHT
```
___
*[pkg/ui/workspaces/cluster-ui/src/timeScaleDropdown/timeScaleDropdown.tsx, line 171 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/75586#-MuSYTLb65-H69q-0F7z:-Mukolgm7YFsWF9CUOki:be5jhe7) ([raw file](https://github.com/cockroachdb/cockroach/blob/ce14496edd67d463c89a1af7ea08d9e56603a344/pkg/ui/workspaces/cluster-ui/src/timeScaleDropdown/timeScaleDropdown.tsx#L171)):*
> moment.utc()

I agree with the end goal! But I'm noticing that there are multiple calls to `moment.utc()` not just in the top-level of this component, but also in the functions that are defined in this file. Solving the multiple calls to `moment.utc()` in this file/component would require refactoring those functions and their tests to pass in a `now` variable.

That's not difficult to do, but this PR is getting really big. I have a "Potential future follow-up" in the PR description, to accumulate improvement ideas from this PR that I have no intention of doing with any priority, but that we could maybe one day  do on a quick win day. Would you be comfortable shelving this in that section? I'm considering this potential bug "not any worse than before".
___
*[pkg/ui/workspaces/db-console/src/redux/timeScale.ts, line 74 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/75586#-MuNkVPd6ZrMi3ZedgZo:-MuktAGOEUEP1dr_qqDw:b-9buvkz) ([raw file](https://github.com/cockroachdb/cockroach/blob/528331762557f466e897ae7485601da65f43294b/pkg/ui/workspaces/db-console/src/redux/timeScale.ts#L74)):*
<details><summary><i>Previously, Azhng (Archer Zhang) wrote…</i></summary><blockquote>

Thoughts on inheriting the `cluster-ui`'s `TimeWindowState` and introducing new additional fields? 
</blockquote></details>

I think it's a good end goal, but this PR is getting big. Would you be down to shelve this under the "Potential future follow-up" section? I think it would make sense to do along with Matthew's comments a few lines above about simplifying the interface on TimeScale.
___
*[pkg/ui/workspaces/db-console/src/redux/timeScale.ts, line 115 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/75586#-MuSc-oqBvR2AazhgxYP:-Mul-WF13KlRTY1JPi1W:b-iejf98) ([raw file](https://github.com/cockroachdb/cockroach/blob/ce14496edd67d463c89a1af7ea08d9e56603a344/pkg/ui/workspaces/db-console/src/redux/timeScale.ts#L115)):*
> isFixedWindow
No, there isn't (only a default value in the constructor).

If you're not worried about major bugs coming from this, I'd rather ignore this weirdness for now (I'll put it in the "Potential future follow-up" section). This is just a 1-to-1 renaming of the existing implementation. At least it's only used in the metrics page, so the spaghetti is contained in the spaghetti plate 🙂.
___
*[pkg/ui/workspaces/db-console/src/redux/timeScale.ts, line 124 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/75586#-MuSbafw2BoR5WnBZY52:-Mul0QBE21bCsV0tF4GA:b-y25kno) ([raw file](https://github.com/cockroachdb/cockroach/blob/ce14496edd67d463c89a1af7ea08d9e56603a344/pkg/ui/workspaces/db-console/src/redux/timeScale.ts#L124)):*
<details><summary><i>Previously, Azhng (Archer Zhang) wrote…</i></summary><blockquote>

Should we also update `isFixedWindow = false` here?
</blockquote></details>

This is a direct rename of `s/SET_WINDOW/SET_METRICS_MOVING_WINDOW`. The prior implementation didn't set `isFixedWindow = false`, so I'm gonna say that we shouldn't here 😛. The logic for that is not the simplest and I'd rather not perturb the system. "Clean up the metrics page code" would be a pretty big task that I don't think is a priority.
___
*[pkg/ui/workspaces/db-console/src/redux/timeScale.ts, line 62 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/75586#-Muki6T24XXah7h7brEZ:-Mukrk9oDsYy8resFLBC:b8kru4t) ([raw file](https://github.com/cockroachdb/cockroach/blob/85950fa927d78f2c01c839fb27440eaaa159b73c/pkg/ui/workspaces/db-console/src/redux/timeScale.ts#L62)):*
<details><summary><i>Previously, matthewtodd (Matthew Todd) wrote…</i></summary><blockquote>

Seeing optional properties and reading through these usage instructions makes me wonder if it would be possible to hide this complexity inside an object somehow. I think there's enough in-flight on this PR that it wouldn't make sense to add here, just wanted to register the idea for the future.
</blockquote></details>

Thanks; agreed on all fronts. Will stick it in an issue for the improvement ideas that come out of this PR.

**Review by xinhaoz — COMMENTED** [review]
Thanks so much for tackling this! :pray: 

> Reviewed 6 of 26 files at r10.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/75586#-:-MuutTSV7UEoGCWHyDEm:byfi35s)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @Azhng, @dhartunian, @jocrl, @maryliag, @matthewtodd, @nathanstilwell, @Santamaura, and @xinhaoz)

___
*[pkg/ui/workspaces/cluster-ui/src/timeScaleDropdown/timeScaleDropdown.tsx, line 34 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/75586#-MuSU_mx1qcCleXWlIEH:-MuSU_mx1qcCleXWlIEI:bpjsls3) ([raw file](https://github.com/cockroachdb/cockroach/blob/03370f374fb992e2299b50b4758797301ec161c0/pkg/ui/workspaces/cluster-ui/src/timeScaleDropdown/timeScaleDropdown.tsx#L34)):*
> ```XML
> export interface TimeScaleDropdownProps {
>   currentScale: TimeScale;
>   options?: DefaultTimesScaleOptions;
> ```

Can we rename this to just `TimeScaleOptions`, as from what I understand it's not just describing the type for the default, but any options we would want to pass here. Also I think there is s a double s here in `TimesScale`.

**Review by jocrl — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/75586)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @Azhng, @dhartunian, @jocrl, @maryliag, @matthewtodd, @nathanstilwell, @Santamaura, and @xinhaoz)

___
*[pkg/ui/workspaces/cluster-ui/src/timeScaleDropdown/timeScaleDropdown.tsx, line 34 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/75586#-MuSU_mx1qcCleXWlIEH:-MuuxWbq5ztjM6I2gxMg:b-l0w3z2) ([raw file](https://github.com/cockroachdb/cockroach/blob/03370f374fb992e2299b50b4758797301ec161c0/pkg/ui/workspaces/cluster-ui/src/timeScaleDropdown/timeScaleDropdown.tsx#L34)):*
<details><summary><i>Previously, xinhaoz (Xin Hao Zhang) wrote…</i></summary><blockquote>

Can we rename this to just `TimeScaleOptions`, as from what I understand it's not just describing the type for the default, but any options we would want to pass here. Also I think there is s a double s here in `TimesScale`.
</blockquote></details>

Good catch; thanks! Done.

**Review by Santamaura — COMMENTED** [review]
Looks pretty good, thanks for the effort! Dropped just a couple of comments.

> Reviewed 23 of 26 files at r12, 3 of 3 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/75586#-:-MvU7KWG7bltwWZp8rQ_:b-2ftnd0)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @Azhng, @dhartunian, @jocrl, @maryliag, @matthewtodd, @nathanstilwell, and @xinhaoz)

___
*[pkg/ui/workspaces/cluster-ui/src/timeScaleDropdown/timeScaleDropdown.tsx, line 167 at r13](https://reviewable.io/reviews/cockroachdb/cockroach/75586#-MvU-F8SDxmHjZW6yuNO:-MvU-F8SDxmHjZW6yuNP:b-l0hmov) ([raw file](https://github.com/cockroachdb/cockroach/blob/4a45a9ccbff9f0e9ef8e0b3d7b7489f8d5d81386/pkg/ui/workspaces/cluster-ui/src/timeScaleDropdown/timeScaleDropdown.tsx#L167)):*
> ```XML
>          * Thus, it seems like this `if` condition should always be true.
>          */
>         if (endTime) {
> ```

A bit confused here, the if condition will always pass and even the comment indicates this..so is there a reason to keep it?
___
*[pkg/ui/workspaces/cluster-ui/src/timeScaleDropdown/utils.ts, line 119 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/75586#-MuSnPCm0jfPIHkHcl_k:-MvU2yrj6FD1mM5f83N8:bcl31f9) ([raw file](https://github.com/cockroachdb/cockroach/blob/85950fa927d78f2c01c839fb27440eaaa159b73c/pkg/ui/workspaces/cluster-ui/src/timeScaleDropdown/utils.ts#L119)):*
<details><summary><i>Previously, jocrl (Josephine) wrote…</i></summary><blockquote>

This is just a clarifying rewrite. I've added test cases for this block and they pass both before and after the change.
</blockquote></details>

This if check is a bit strange as we are comparing an epoch timestamp to a moment object. In your testing did the check ever come up as false? I ran some basic tests on this comparison in a moment sandbox and it always seemed to return true.

**Review by jocrl — COMMENTED** [review]
Thanks everyone! Cleaned up and undrafted; PTAL 🙏

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/75586#-:-MvyTyb0DBjB8kVrZi1c:b3rjq41)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dhartunian, @maryliag, @nathanstilwell, @Santamaura, and @xinhaoz)

___
*[pkg/ui/workspaces/cluster-ui/src/timeScaleDropdown/timeScaleDropdown.tsx, line 182 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/75586#-MuRDIFL3ftv6AyvlgML:-MvyC3_KEG__BhSsO-ir:b-ml0l1s) ([raw file](https://github.com/cockroachdb/cockroach/blob/03370f374fb992e2299b50b4758797301ec161c0/pkg/ui/workspaces/cluster-ui/src/timeScaleDropdown/timeScaleDropdown.tsx#L182)):*
<details><summary><i>Previously, jocrl (Josephine) wrote…</i></summary><blockquote>

No, I'm not. I'm curious about that `else` block, but I'm not worried about that/it's not my main concern.

My main question is why `windowValid` is used here, in order to fix the comment on the `windowValid` type definition in `cluster-ui`. The comment that was previously there described it's usage in `db-console`. This is the only usage in `cluster-ui`, but it seems like this usage would be better off using `windowSize`. So I'm not sure what to put in the comments for `windowValid` on what it means.

It's just to try to fix misleading text in the comments. So, if this is confusing, I could just delete the comment line and describe our confusion instead.
</blockquote></details>

Modified the comment.
___
*[pkg/ui/workspaces/cluster-ui/src/timeScaleDropdown/timeScaleDropdown.tsx, line 167 at r13](https://reviewable.io/reviews/cockroachdb/cockroach/75586#-MvU-F8SDxmHjZW6yuNO:-MvxyWpo5Jld8z7ey0Q3:b6e38k4) ([raw file](https://github.com/cockroachdb/cockroach/blob/4a45a9ccbff9f0e9ef8e0b3d7b7489f8d5d81386/pkg/ui/workspaces/cluster-ui/src/timeScaleDropdown/timeScaleDropdown.tsx#L167)):*
<details><summary><i>Previously, Santamaura (Alex Santamaura) wrote…</i></summary><blockquote>

A bit confused here, the if condition will always pass and even the comment indicates this..so is there a reason to keep it?
</blockquote></details>

Not much reason, other than that trying not change the code beyond what I needed to. You and Archer both brought this up though, so I've removed it.
___
*[pkg/ui/workspaces/cluster-ui/src/timeScaleDropdown/timeScaleTypes.ts, line 41 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/75586#-MuRF2KL4EuFh-VgkvEA:-Mvy83pP1ojKOIiLAWwF:b-at6pje) ([raw file](https://github.com/cockroachdb/cockroach/blob/528331762557f466e897ae7485601da65f43294b/pkg/ui/workspaces/cluster-ui/src/timeScaleDropdown/timeScaleTypes.ts#L41)):*
<details><summary><i>Previously, jocrl (Josephine) wrote…</i></summary><blockquote>

I want to modify the original comment below to reflect the actual `windowValid` in Cluster UI, but I don't understand the usage.
The original comment below (`now > (currentWindow.end + windowValid)`) describes the usage of `windowValid` in DB Console polling, which does not involve in this Cluster UI copy.
Instead, in Cluster UI is it used in the `arrowClick` function in `timeScaleDropdown.tsx`. I'm confused about that usage, and have added a comment-question there in `timeScaleDropdown.tsx`.
</blockquote></details>

Decided to just delete that part of the comment.
___
*[pkg/ui/workspaces/cluster-ui/src/timeScaleDropdown/utils.ts, line 119 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/75586#-MuSnPCm0jfPIHkHcl_k:-Mvy4Hx54u_1Nb6LNBOO:b-kru0kf) ([raw file](https://github.com/cockroachdb/cockroach/blob/85950fa927d78f2c01c839fb27440eaaa159b73c/pkg/ui/workspaces/cluster-ui/src/timeScaleDropdown/utils.ts#L119)):*
<details><summary><i>Previously, Santamaura (Alex Santamaura) wrote…</i></summary><blockquote>

This if check is a bit strange as we are comparing an epoch timestamp to a moment object. In your testing did the check ever come up as false? I ran some basic tests on this comparison in a moment sandbox and it always seemed to return true.
</blockquote></details>

Hmm. Aren't both moment objects?
`end`: https://momentjs.com/docs/#/parsing/unix-timestamp/
`moment()`: https://momentjs.com/docs/#/parsing/now/

[This particular test](https://github.com/cockroachdb/cockroach/pull/75586/files?show-viewed-files=true&file-filters%5B%5D=#diff-bd03e68c855999b02b57ad5575dfceabfc3d3688b31a1bada85a09f91b883c54R244) causes this block to come up as false, which I've confirmed by adding an else block and a console log.

That said, I'm not thoroughly sure but I don't think it's actually hit in the code, due to the ways that `findClosestTimeScale` is called. `startSeconds` needs to be passed for the outer if block to be true, and in the only time that is passed it is always custom.

In theory there might be more we could do to remove redundant paths and logic, but I'm trying not to do more than I need here.

**Review by maryliag — APPROVED** [review]
:lgtm: (from the comments I added)

I just added some tiny nits, otherwise make sure you addressed all the comments from other reviewers and get approval too

> Reviewed 19 of 26 files at r12, 1 of 3 files at r13, 5 of 5 files at r14, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/75586#-:-Mw75qqk5jMqfbRKwazz:bqjedy)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @dhartunian, @jocrl, @nathanstilwell, @Santamaura, and @xinhaoz)

___
*[pkg/ui/workspaces/cluster-ui/src/timeScaleDropdown/timescale.spec.tsx, line 209 at r14](https://reviewable.io/reviews/cockroachdb/cockroach/75586#-MvyheLHBko-FqBXtg2f:-MvyheLHBko-FqBXtg2g:be0fx5k) ([raw file](https://github.com/cockroachdb/cockroach/blob/e91b6156c74e360f8227cdafcfc3a41e02872cd7/pkg/ui/workspaces/cluster-ui/src/timeScaleDropdown/timescale.spec.tsx#L209)):*
> ```XML
>   describe("findClosestTimeScale", () => {
>     it("should find the correct time scale", () => {
>       // `seconds` != window size of any of the default options, `startSeconds` not specified
> ```

nit: period on those comments (more below)
___
*[pkg/ui/workspaces/db-console/src/redux/timeScale.ts, line 93 at r14](https://reviewable.io/reviews/cockroachdb/cockroach/75586#-Mvyg7jF0a84PZer3sq5:-Mvyg7jG3YPSO90Z8BMl:b-8so11) ([raw file](https://github.com/cockroachdb/cockroach/blob/e91b6156c74e360f8227cdafcfc3a41e02872cd7/pkg/ui/workspaces/db-console/src/redux/timeScale.ts#L93)):*
> ```XML
>     };
>     this.metricsTime = {
>       // This is explicitly initialized as undefined to match the prior implementation while satisfying Typescript
> ```

nit: period

**Review by jocrl — COMMENTED** [review]
Thanks! Addressed, and bumping @matthewtodd, @Azhng, @Santamaura, and @xinhaoz. PTAL 🙏

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/75586#-:-Mw7GuOH7VPvbibJJ48F:bsfwjco)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @dhartunian, @maryliag, @nathanstilwell, @Santamaura, and @xinhaoz)

**Review by Santamaura — APPROVED** [review]
:lgtm: now :thumbsup: 

> Reviewed 2 of 2 files at r15, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/75586#-:-MwY7DXJ3xgWjIXWOwGj:b-trxatd)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @dhartunian, @jocrl, @nathanstilwell, and @xinhaoz)

File: pkg/ui/workspaces/cluster-ui/src/timeScaleDropdown/timeScaleDropdown.tsx [hunk 1]
```diff
@@ -156,37 +156,43 @@ export const TimeScaleDropdown: React.FC<TimeScaleDropdownProps> = ({
...
         console.error("Unknown direction: ", direction);
     }
+
     // If the timescale extends into the future then fallback to a default
     // timescale. Otherwise set the key to "Custom" so it appears correctly.
-    if (
-      !windowEnd ||
-      windowEnd > moment.utc().subtract(currentScale.windowValid)
-    ) {
+    // The first `!endTime` part of the if` clause seems unnecessary since endTime is always a specific time.
```
Comment (Azhng) [inline pkg/ui/workspaces/cluster-ui/src/timeScaleDropdown/timeScaleDropdown.tsx:178]: minor nit: extra "`" after "if"

File: pkg/ui/workspaces/cluster-ui/src/timeScaleDropdown/timeScaleDropdown.tsx [hunk 2]
```diff
@@ -156,37 +156,43 @@ export const TimeScaleDropdown: React.FC<TimeScaleDropdownProps> = ({
...
         ([_, value]) => value.windowSize.asSeconds() === windowSize.asSeconds(),
       );
       if (foundTimeScale) {
+        /**
+         * This code can be hit by:
+         *  - Select a default option, then click the left arrow, then click the right arrow.
+         * This (or the parent if block) is *not* hit by:
+         *  - Select a default time, click left, select a custom time of the same range, then click right. The arrow is
+         *    not disabled, but the clause doesn't seem to be true.
+         */
```
Comment (Azhng) [inline pkg/ui/workspaces/cluster-ui/src/timeScaleDropdown/timeScaleDropdown.tsx:192]: super small nit: is changing the block comment style here on purpose?

**Review by Azhng — APPROVED** [review]
🚀

**Review by matthewtodd — APPROVED** [review]
:lgtm:

> Reviewed 18 of 26 files at r12, 1 of 3 files at r13, 5 of 5 files at r14, 2 of 2 files at r15, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/75586#-:-MwgXV8k22z2_HdSMsYn:bnfp4nl)* status: :shipit: complete! 2 of 0 LGTMs obtained (and 1 stale) (waiting on @dhartunian, @jocrl, @nathanstilwell, and @xinhaoz)

**Review by jocrl — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/75586)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 3 stale) (waiting on @Azhng, @dhartunian, @maryliag, @matthewtodd, @nathanstilwell, @Santamaura, and @xinhaoz)

___
*[pkg/ui/workspaces/cluster-ui/src/timeScaleDropdown/timeScaleDropdown.tsx, line 178 at r15](https://reviewable.io/reviews/cockroachdb/cockroach/75586#-MuNgxoVfy_OEec0Lkar-r15-178:-MwghLtp3NuWT6aXGF_R:b-7ql1td) ([raw file](https://github.com/cockroachdb/cockroach/blob/ad6e433fa5e2088b9c7909607e9e2f3c76706411/pkg/ui/workspaces/cluster-ui/src/timeScaleDropdown/timeScaleDropdown.tsx#L178)):*
<details><summary><i>Previously, Azhng (Archer Zhang) wrote…</i></summary><blockquote>

minor nit: extra "`" after "if"
</blockquote></details>

fixed
___
*[pkg/ui/workspaces/cluster-ui/src/timeScaleDropdown/timeScaleDropdown.tsx, line 192 at r15](https://reviewable.io/reviews/cockroachdb/cockroach/75586#-MuNgxoVfy_OEec0Lkar-r15-192:-Mwggul0DzDSwv6msWv3:be91q3p) ([raw file](https://github.com/cockroachdb/cockroach/blob/ad6e433fa5e2088b9c7909607e9e2f3c76706411/pkg/ui/workspaces/cluster-ui/src/timeScaleDropdown/timeScaleDropdown.tsx#L192)):*
<details><summary><i>Previously, Azhng (Archer Zhang) wrote…</i></summary><blockquote>

super small nit: is changing the block comment style here on purpose?
</blockquote></details>

Yes, it was on purpose since it's getting long. I think neither javascript nor or code conventions is opinionated on which to use in the frontend, e.g. https://github.com/cockroachdb/cockroach/blob/master/pkg/ui/workspaces/cluster-ui/src/util/proto.ts#L89

**Comment by jocrl** [comment]
___
*[pkg/ui/workspaces/cluster-ui/src/timeScaleDropdown/timeScaleDropdown.tsx, line 192 at r15](https://reviewable.io/reviews/cockroachdb/cockroach/75586#-MuNgxoVfy_OEec0Lkar-r15-192:-MwghoEh2H-EO8bZmlfP:b9jmh9) ([raw file](https://github.com/cockroachdb/cockroach/blob/ad6e433fa5e2088b9c7909607e9e2f3c76706411/pkg/ui/workspaces/cluster-ui/src/timeScaleDropdown/timeScaleDropdown.tsx#L192)):*
> javascript nor or code conventions 
edit: nor *our code conventions

**Comment by jocrl** [comment]
Thank you everyone!
bors r+
