### PR TITLE
workload/schemachange: fix and re-enable ALTER FUNCTION

### LINKED ISSUE #116794: workload/schemachange: `ALTER FUNCTION` may fail to find functions without arguments
As of https://github.com/cockroachdb/cockroach/pull/115359, the RSW supports `ALTER FUNCTION`.

On occasion, `ALTER FUNCTION` statements will fail:
```
test logs left over in: /home/chrisseto/go/src/github.com/cockroachdb/cockroach/tmp/_tmp/e2bfcb2daef366fa77f42af32e17a96d/logTestWorkload2821957365
--- FAIL: TestWorkload (35.85s)
    test_log_scope.go:170: test logs captured to: /home/chrisseto/go/src/github.com/cockroachdb/cockroach/tmp/_tmp/e2bfcb2daef366fa77f42af32e17a96d/logTestWorkload2821957365
    test_log_scope.go:81: use -show-logs to present logs inline
    schema_change_external_test.go:132:
                Error Trace:    pkg/ccl/testccl/workload/schemachange/schemachange_test_test/pkg/ccl/testccl/workload/schemachange/schema_change_external_test.go:132
                Error:          Received unexpected error:
                                ***UNEXPECTED ERROR; Received an unexpected execution error.: ERROR: unknown function: public.udf_84() (SQLSTATE 42883)
                                (1) forced error mark
                                  | "fatal error when running txn"
                                  | github.com/cockroachdb/errors/withstack/*withstack.withStack::
                                Wraps: (2)
                                Wraps: (3) attached stack trace
                                  -- stack trace:
                                  | github.com/cockroachdb/cockroach/pkg/workload/schemachange.(*opStmt).executeStmt
                                  |     github.com/cockroachdb/cockroach/pkg/workload/schemachange/operation_generator.go:3087
                                  | github.com/cockroachdb/cockroach/pkg/workload/schemachange.(*schemaChangeWorker).runInTxn
                                  |     github.com/cockroachdb/cockroach/pkg/workload/schemachange/schemachange.go:446
                                  | github.com/cockroachdb/cockroach/pkg/workload/schemachange.(*schemaChangeWorker).run
                                  |     github.com/cockroachdb/cockroach/pkg/workload/schemachange/schemachange.go:523
                                  | pkg/ccl/testccl/workload/schemachange/schemachange_test_test.TestWorkload.TestWorkload.func4.func6
                                  |     pkg/ccl/testccl/workload/schemachange/schemachange_test_test/pkg/ccl/testccl/workload/schemachange/schema_change_external_test.go:121
                                  | golang.org/x/sync/errgroup.(*Group).Go.func1
                                  |     golang.org/x/sync/errgroup/external/org_golang_x_sync/errgroup/errgroup.go:75
                                  | runtime.goexit
                                  |     src/runtime/asm_amd64.s:1650
                                Wraps: (4) ***UNEXPECTED ERROR; Received an unexpected execution error.
                                Wraps: (5) ERROR: unknown function: public.udf_84() (SQLSTATE 42883)
                                Error types: (1) *markers.withMark (2) *schemachange.ErrorState (3) *withstack.withStack (4) *errutil.withPrefix (5) *pgconn.PgError
                Test:           TestWorkload
    schema_change_external_test.go:98: backup, tracing data, and system table dumps in /home/chrisseto/go/src/github.com/cockroachdb/cockroach/tmp/_tmp/e2bfcb2daef366fa77f42af32e17a96d/logTestWorkload2821957365
    panic.go:523: -- test log scope end --
```

Unfortunately, my debug info got GC'd. I'll upload any that I manage to reproduce. From the runs that I've inspected, the referenced function exists with no arguments in the `public` schema. Notably, this issue only occurs in the `public` schema. This may be a red herring if `ALTER FUNCTION SET SCHEMA` never succeeds. 

Jira issue: CRDB-34777

Epic CRDB-19168

### PR DESCRIPTION
**Pull request by rafiss**
A few fixes were needed:
- Include UDF params when generating ALTER FUNCTION statement.
- Changed an errors.Is call to errors.HasType.
- Avoid only using the public schema when creating functions.

fixes https://github.com/cockroachdb/cockroach/issues/116794
Release note: None

### CODE REVIEW

File: pkg/workload/schemachange/generate.go [hunk 1]
```diff
@@ -187,6 +187,10 @@ func Generate[T tree.Statement](
 		aIsSuccess := a.Code == pgcode.SuccessfulCompletion
 		bIsSuccess := b.Code == pgcode.SuccessfulCompletion
 
+		if aIsSuccess && bIsSuccess {
+			// If both are valid, choose randomly.
```
Comment (annrpom) [inline pkg/workload/schemachange/generate.go:191]: Oh, right - nice & fair point

**Review by annrpom — APPROVED** [review]
lgtm!

File: pkg/workload/schemachange/operation_generator.go [hunk 2]
```diff
@@ -3916,6 +3923,9 @@ func (og *operationGenerator) createFunction(ctx context.Context, tx pgx.Tx) (*o
 			name := tree.Name(fmt.Sprintf("udf_%s", og.newUniqueSeqNumSuffix()))
 			return &name
 		},
+		"Schema": func() (string, error) {
```
Comment (annrpom) [inline pkg/workload/schemachange/operation_generator.go:3926]: oh just thought of something: is it worth to check if our schema exists? i'm asking in the case where we have selected our descriptors to get `descJSONQuery`, another worker fires of a drop schema, and then we try to create a function with that schema here

Comment (rafiss) [reply pkg/workload/schemachange/operation_generator.go:3926]: i think we're safe from this, we use same transaction to pick the schema name and create the function in that schema, so it's guaranteed that no other transaction will have dropped that schema, thanks to serializable transaction guarantees

Comment (annrpom) [reply pkg/workload/schemachange/operation_generator.go:3926]: oh true - ty for explaining why 🥇

**Comment by rafiss** [comment]
trying again 🤞 

bors r+
