### PR TITLE
roachtest: log compaction failures in backupFixture tests rather than returning an error

### LINKED ISSUE #166264: roachtest: backupFixture/tpcc/warehouses=5000/incrementals=48 failed
roachtest.backupFixture/tpcc/warehouses=5000/incrementals=48 [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyAwsBazel/21275231?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyAwsBazel/21275231?buildTab=artifacts#/backupFixture/tpcc/warehouses=5000/incrementals=48) on release-26.1.2-rc @ [6539acc10020630b6fb61f5e1e8aa06ae7820f8e](https://github.com/cockroachdb/cockroach/commits/6539acc10020630b6fb61f5e1e8aa06ae7820f8e):

Failed with:

```
(assertions.go:369).Fail: 
	Error Trace:	pkg/cmd/roachtest/tests/backup_fixtures.go:657
	            				pkg/cmd/roachtest/test_runner.go:1539
	            				src/runtime/asm_amd64.s:1693
	Error:      	Received unexpected error:
	            	compaction jobs failed while running incrementals: [{1159731710326177795 failed failed to run backup compaction: compacting span entry: read roachtest/v26.1/tpcc-5k/20260320-063339.997/incrementals/2026/03/20-064827.59/20260320/073900.00-20260320-073800.00/data/1159731480953520130.sst: read tcp 10.12.3.44:47288->52.219.108.154:443: read: connection timed out}]
	            	(1) attached stack trace
	            	  -- stack trace:
	            	  | github.com/cockroachdb/cockroach/pkg/cmd/roachtest/tests.(*backupDriver).monitorBackups
	            	  | 	pkg/cmd/roachtest/tests/backup_fixtures.go:329
	            	  | github.com/cockroachdb/cockroach/pkg/cmd/roachtest/tests.registerBackupFixtures.func1
	            	  | 	pkg/cmd/roachtest/tests/backup_fixtures.go:657
	            	  | main.(*testRunner).runTest.func2
	            	  | 	pkg/cmd/roachtest/test_runner.go:1539
	            	  | runtime.goexit
	            	  | 	src/runtime/asm_amd64.s:1693
	            	Wraps: (2) compaction jobs failed while running incrementals: [{1159731710326177795 failed failed to run backup compaction: compacting span entry: read roachtest/v26.1/tpcc-5k/20260320-063339.997/incrementals/2026/03/20-064827.59/20260320/073900.00-20260320-073800.00/data/1159731480953520130.sst: read tcp 10.12.3.44:47288->52.219.108.154:443: read: connection timed out}]
	            	Error types: (1) *withstack.withStack (2) *errutil.leafError
	Test:       	backupFixture/tpcc/warehouses=5000/incrementals=48
(require.go:1357).NoError: FailNow called
test artifacts and logs in: /artifacts/backupFixture/tpcc/warehouses=5000/incrementals=48/cpu_arch=arm64/run_1
```
Cluster Node to Ip Mapping:
| Node | Public IP | Private IP |
| --- | --- | --- |
| teamcity-21275231-1773987689-10-n5cpu8-0001 | 18.119.110.195 | 10.12.3.44 |
| teamcity-21275231-1773987689-10-n5cpu8-0002 | 3.140.186.62 | 10.12.8.74 |
| teamcity-21275231-1773987689-10-n5cpu8-0003 | 3.21.246.88 | 10.12.9.52 |
| teamcity-21275231-1773987689-10-n5cpu8-0004 | 3.15.141.132 | 10.12.5.148 |
| teamcity-21275231-1773987689-10-n5cpu8-0005 | 52.14.212.93 | 10.12.14.232 |

Parameters:
 - <code>arch=arm64</code>
 - <code>cloud=aws</code>
 - <code>coverageBuild=false</code>
 - <code>cpu=8</code>
 - <code>diskCount=0</code>
 - <code>encrypted=false</code>
 - <code>fs=ext4</code>
 - <code>localSSD=false</code>
 - <code>metamorphicWriteBuffering=true</code>
 - <code>runtimeAssertionsBuild=false</code>
<details><summary>Help</summary>
<p>

See: [roachtest README](https://github.com/cockroachdb/cockroach/blob/master/pkg/cmd/roachtest/README.md)

See: [How To Investigate \(internal\)](https://cockroachlabs.atlassian.net/l/c/SSSBr8c7)

_Grafana is not yet available for aws clusters_</p>
</details>
<details><summary>Same failure on other branches</summary>
<p>

- #166152 roachtest: backupFixture/tpcc/warehouses=5000/incrementals=48 failed [A-disaster-recovery B-runtime-assertions-enabled C-test-failure O-roachtest O-robot T-disaster-recovery branch-release-25.4.7-rc release-blocker]
</p>
</details>
/cc @cockroachdb/disaster-recovery
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*backupFixture/tpcc/warehouses=5000/incrementals=48.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/bazci/githubpost/issues)

</sub>

Jira issue: CRDB-61825

### PR DESCRIPTION
**Pull request by andrew-r-thomas**
This patch adjusts the backupFixture roachtests to log compaction failures rather than failing the test. Backup compaction needs a new retry loop that better handles spurious errors. This patch is a quick fix to make these tests less flaky in the meantime.

Fixes: #166264

Release note: None

### CODE REVIEW

File: pkg/cmd/roachtest/tests/backup_fixtures.go [hunk 1]
```diff
@@ -326,7 +326,12 @@ func (bd *backupDriver) monitorBackups(ctx context.Context) error {
 			} else if bd.sp.fixture.CompactionThreshold > 0 {
 				bd.t.L().Printf("%d compaction jobs succeeded, %d running", len(compSuccess), len(compRunning))
 				if len(compFailed) > 0 {
-					return errors.Newf("compaction jobs failed while running incrementals: %v", compFailed)
+					const msg = "compaction jobs failed while running incrementals: %v"
+					if len(compSuccess) > 0 {
+						bd.t.L().Errorf(msg, compFailed)
+					} else {
+						return errors.Newf(msg, compFailed)
+					}
```
Comment (kev-cao) [inline pkg/cmd/roachtest/tests/backup_fixtures.go]: I think we need to put this logic at the end, outside of this `for` loop. We fail the roachtest if no compactions successfully completed, but that isn't something we determine until we have finished making the fixture.

As it is, we would fail if the first compaction failed due to some transient error.

File: pkg/cmd/roachtest/tests/backup_fixtures.go [hunk 2]
```diff
@@ -326,7 +326,12 @@ func (bd *backupDriver) monitorBackups(ctx context.Context) error {
 			} else if bd.sp.fixture.CompactionThreshold > 0 {
 				bd.t.L().Printf("%d compaction jobs succeeded, %d running", len(compSuccess), len(compRunning))
 				if len(compFailed) > 0 {
-					return errors.Newf("compaction jobs failed while running incrementals: %v", compFailed)
+					const msg = "compaction jobs failed while running incrementals: %v"
+					if len(compSuccess) > 0 {
```
Comment (kev-cao) [inline pkg/cmd/roachtest/tests/backup_fixtures.go]: It might be better if instead of checking for at least one successful compaction, we should check if `compSuccess > compFailed`. I think if a fixture were to have mostly failed compactions, it'd be worth looking into.

Also a large chain with mostly failed compactions wouldn't be online-restorable anyway.

Comment (kev-cao) [reply pkg/cmd/roachtest/tests/backup_fixtures.go]: We could be even more specific by looking at the compaction window and chain length to determine some acceptable threshold, but I don't think we need to get that detailed.

**Review by msbutler — APPROVED** [review]
nice work!
