### PR TITLE
crosscluster: do not panic on poorly formatted inline certs

### LINKED ISSUE #145949: Sentry: conn_executor.go:998: runtime error: invalid memory address or nil pointer dereference (1) attached stack trace   -- stack trace:   | github.com/cockroachdb/cockroach/pkg/sql.(*Server).ServeCo...
This issue was auto filed by Sentry. It represents a crash or reported error on a live cluster with telemetry enabled.

Sentry Link: [https://cockroach-labs.sentry.io/issues/6581513449/?referrer=webhooks_plugin](https://cockroach-labs.sentry.io/issues/6581513449/?referrer=webhooks_plugin)

Panic Message:

```
conn_executor.go:998: runtime error: invalid memory address or nil pointer dereference
(1) attached stack trace
  -- stack trace:
  | github.com/cockroachdb/cockroach/pkg/sql.(*Server).ServeConn.func1
  | 	pkg/sql/conn_executor.go:998
  | [...repeated from below...]
Wraps: (2) while executing: CREATE EXTERNAL CONNECTION '_' AS '_'
Wraps: (3) attached stack trace
  -- stack trace:
  | github.com/cockroachdb/cockroach/pkg/sql.(*Server).ServeConn.func1
  | 	pkg/sql/conn_executor.go:998
  | runtime.gopanic
  | 	GOROOT/src/runtime/panic.go:770
  | github.com/cockroachdb/cockroach/pkg/sql/colexecerror.CatchVectorizedRuntimeError.func1
  | 	pkg/sql/colexecerror/error.go:137
  | runtime.gopanic
  | 	GOROOT/src/runtime/panic.go:770
  | github.com/cockroachdb/cockroach/pkg/sql/colexecerror.CatchVectorizedRuntimeError.func1
  | 	pkg/sql/colexecerror/error.go:137
  | runtime.gopanic
  | 	GOROOT/src/runtime/panic.go:770
  | runtime.panicmem
  | 	GOROOT/src/runtime/panic.go:261
  | runtime.sigpanic
  | 	GOROOT/src/runtime/signal_unix.go:881
  | encoding/pem.Encode
  | 	GOROOT/src/encoding/pem/pem.go:242
  | encoding/pem.EncodeToMemory
  | 	GOROOT/src/encoding/pem/pem.go:312
  | github.com/cockroachdb/cockroach/pkg/crosscluster/streamclient.uriWithInlineTLSCertsRemoved
  | 	pkg/crosscluster/streamclient/pgconn.go:110
  | github.com/cockroachdb/cockroach/pkg/crosscluster/streamclient.setupPGXConfig
  | 	pkg/crosscluster/streamclient/pgconn.go:48
  | github.com/cockroachdb/cockroach/pkg/crosscluster/streamclient.newPGConnForClient
  | 	pkg/crosscluster/streamclient/pgconn.go:36
  | github.com/cockroachdb/cockroach/pkg/crosscluster/streamclient.NewPartitionedStreamClient
  | 	pkg/crosscluster/streamclient/partitioned_stream_client.go:48
  | github.com/cockroachdb/cockroach/pkg/crosscluster/physical.validatePostgresConnectionURI
  | 	pkg/crosscluster/physical/external_connection.go:30
  | github.com/cockroachdb/cockroach/pkg/cloud/externalconn.(*schemeRegistration).parseAndValidateURI
  | 	pkg/cloud/externalconn/impl_registry.go:61
  | github.com/cockroachdb/cockroach/pkg/cloud/externalconn.ExternalConnectionFromURI
  | 	pkg/cloud/externalconn/impl_registry.go:135
  | github.com/cockroachdb/cockroach/pkg/sql.(*planner).createExternalConnection
  | 	pkg/sql/create_external_connection.go:119
  | github.com/cockroachdb/cockroach/pkg/sql.(*createExternalConnectionNode).startExec
  | 	pkg/sql/create_external_connection.go:40
  | github.com/cockroachdb/cockroach/pkg/sql.startExec
  | 	pkg/sql/plan.go:556
  | github.com/cockroachdb/cockroach/pkg/sql.(*planNodeToRowSource).Start
  | 	pkg/sql/plan_node_to_row_source.go:166
  | github.com/cockroachdb/cockroach/pkg/sql/colexec.(*Columnarizer).Init
  | 	pkg/sql/colexec/columnarizer.go:178
  | github.com/cockroachdb/cockroach/pkg/sql/colflow.(*batchInfoCollector).init
  | 	pkg/sql/colflow/stats.go:89
  | github.com/cockroachdb/cockroach/pkg/sql/colexecerror.CatchVectorizedRuntimeError
  | 	pkg/sql/colexecerror/error.go:162
  | github.com/cockroachdb/cockroach/pkg/sql/colflow.(*batchInfoCollector).Init
  | 	pkg/sql/colflow/stats.go:98
  | github.com/cockroachdb/cockroach/pkg/sql/colflow.(*BatchFlowCoordinator).Run.(*BatchFlowCoordinator).init.func2
  | 	pkg/sql/colflow/flow_coordinator.go:236
  | github.com/cockroachdb/cockroach/pkg/sql/colexecerror.CatchVectorizedRuntimeError
  | 	pkg/sql/colexecerror/error.go:162
  | github.com/cockroachdb/cockroach/pkg/sql/colflow.(*BatchFlowCoordinator).init
  | 	pkg/sql/colflow/flow_coordinator.go:235
  | github.com/cockroachdb/cockroach/pkg/sql/colflow.(*BatchFlowCoordinator).Run
  | 	pkg/sql/colflow/flow_coordinator.go:269
  | github.com/cockroachdb/cockroach/pkg/sql/colflow.(*vectorizedFlow).Run
  | 	pkg/sql/colflow/vectorized_flow.go:316
  | github.com/cockroachdb/cockroach/pkg/sql.(*DistSQLPlanner).Run
  | 	pkg/sql/distsql_running.go:933
  | github.com/cockroachdb/cockroach/pkg/sql.(*DistSQLPlanner).PlanAndRun
  | 	pkg/sql/distsql_running.go:2036
Wraps: (4) runtime error: invalid memory address or nil pointer dereference
Error types: (1) *withstack.withStack (2) *safedetails.withSafeDetails (3) *withstack.withStack (4) runtime.errorString
-- report composition:
runtime.errorString
conn_executor.go:998: *withstack.withStack (top exception)
*safedetails.withSafeDetails: while executing: CREATE EXTERNAL CONNECTION '_' AS '_'
conn_executor.go:998: *withstack.withStack (1)
(check the extra data payloads)
```

<details>
<summary>Stacktrace (expand for inline code snippets):</summary>

[pkg/sql/distsql_running.go#L2035-L2037](pkg/sql/distsql_running.go#L2035-L2037)
[pkg/sql/distsql_running.go#L932-L934](pkg/sql/distsql_running.go#L932-L934)
[pkg/sql/colflow/vectorized_flow.go#L315-L317](pkg/sql/colflow/vectorized_flow.go#L315-L317)
[pkg/sql/colflow/flow_coordinator.go#L268-L270](pkg/sql/colflow/flow_coordinator.go#L268-L270)
[pkg/sql/colflow/flow_coordinator.go#L234-L236](pkg/sql/colflow/flow_coordinator.go#L234-L236)
[pkg/sql/colexecerror/error.go#L161-L163](pkg/sql/colexecerror/error.go#L161-L163)
[pkg/sql/colflow/flow_coordinator.go#L235-L237](pkg/sql/colflow/flow_coordinator.go#L235-L237)
[pkg/sql/colflow/stats.go#L97-L99](pkg/sql/colflow/stats.go#L97-L99)
[pkg/sql/colexecerror/error.go#L161-L163](pkg/sql/colexecerror/error.go#L161-L163)
[pkg/sql/colflow/stats.go#L88-L90](pkg/sql/colflow/stats.go#L88-L90)
[pkg/sql/colexec/columnarizer.go#L177-L179](pkg/sql/colexec/columnarizer.go#L177-L179)
[pkg/sql/plan_node_to_row_source.go#L165-L167](pkg/sql/plan_node_to_row_source.go#L165-L167)
[pkg/sql/plan.go#L555-L557](pkg/sql/plan.go#L555-L557)
[pkg/sql/create_external_connection.go#L39-L41](pkg/sql/create_external_connection.go#L39-L41)
[pkg/sql/create_external_connection.go#L118-L120](pkg/sql/create_external_connection.go#L118-L120)
[pkg/cloud/externalconn/impl_registry.go#L134-L136](pkg/cloud/externalconn/impl_registry.go#L134-L136)
[pkg/cloud/externalconn/impl_registry.go#L60-L62](pkg/cloud/externalconn/impl_registry.go#L60-L62)
[pkg/crosscluster/physical/external_connection.go#L29-L31](pkg/crosscluster/physical/external_connection.go#L29-L31)
[pkg/crosscluster/streamclient/partitioned_stream_client.go#L47-L49](pkg/crosscluster/streamclient/partitioned_stream_client.go#L47-L49)
[pkg/crosscluster/streamclient/pgconn.go#L35-L37](pkg/crosscluster/streamclient/pgconn.go#L35-L37)
[pkg/crosscluster/streamclient/pgconn.go#L47-L49](pkg/crosscluster/streamclient/pgconn.go#L47-L49)
[pkg/crosscluster/streamclient/pgconn.go#L109-L111](pkg/crosscluster/streamclient/pgconn.go#L109-L111)
[GOROOT/src/encoding/pem/pem.go#L311-L313](GOROOT/src/encoding/pem/pem.go#L311-L313)
[GOROOT/src/encoding/pem/pem.go#L241-L243](GOROOT/src/encoding/pem/pem.go#L241-L243)
[GOROOT/src/runtime/signal_unix.go#L880-L882](GOROOT/src/runtime/signal_unix.go#L880-L882)
[GOROOT/src/runtime/panic.go#L260-L262](GOROOT/src/runtime/panic.go#L260-L262)
[GOROOT/src/runtime/panic.go#L769-L771](GOROOT/src/runtime/panic.go#L769-L771)
[pkg/sql/colexecerror/error.go#L136-L138](pkg/sql/colexecerror/error.go#L136-L138)
[GOROOT/src/runtime/panic.go#L769-L771](GOROOT/src/runtime/panic.go#L769-L771)
[pkg/sql/colexecerror/error.go#L136-L138](pkg/sql/colexecerror/error.go#L136-L138)
[GOROOT/src/runtime/panic.go#L769-L771](GOROOT/src/runtime/panic.go#L769-L771)
[pkg/sql/conn_executor.go#L997-L999](pkg/sql/conn_executor.go#L997-L999)
</details>

```
pkg/sql/distsql_running.go in pkg/sql.(*DistSQLPlanner).PlanAndRun at line 2036
pkg/sql/distsql_running.go in pkg/sql.(*DistSQLPlanner).Run at line 933
pkg/sql/colflow/vectorized_flow.go in pkg/sql/colflow.(*vectorizedFlow).Run at line 316
pkg/sql/colflow/flow_coordinator.go in pkg/sql/colflow.(*BatchFlowCoordinator).Run at line 269
pkg/sql/colflow/flow_coordinator.go in pkg/sql/colflow.(*BatchFlowCoordinator).init at line 235
pkg/sql/colexecerror/error.go in pkg/sql/colexecerror.CatchVectorizedRuntimeError at line 162
pkg/sql/colflow/flow_coordinator.go in pkg/sql/colflow.(*BatchFlowCoordinator).Run.(*BatchFlowCoordinator).init.func2 at line 236
pkg/sql/colflow/stats.go in pkg/sql/colflow.(*batchInfoCollector).Init at line 98
pkg/sql/colexecerror/error.go in pkg/sql/colexecerror.CatchVectorizedRuntimeError at line 162
pkg/sql/colflow/stats.go in pkg/sql/colflow.(*batchInfoCollector).init at line 89
pkg/sql/colexec/columnarizer.go in pkg/sql/colexec.(*Columnarizer).Init at line 178
pkg/sql/plan_node_to_row_source.go in pkg/sql.(*planNodeToRowSource).Start at line 166
pkg/sql/plan.go in pkg/sql.startExec at line 556
pkg/sql/create_external_connection.go in pkg/sql.(*createExternalConnectionNode).startExec at line 40
pkg/sql/create_external_connection.go in pkg/sql.(*planner).createExternalConnection at line 119
pkg/cloud/externalconn/impl_registry.go in pkg/cloud/externalconn.ExternalConnectionFromURI at line 135
pkg/cloud/externalconn/impl_registry.go in pkg/cloud/externalconn.(*schemeRegistration).parseAndValidateURI at line 61
pkg/crosscluster/physical/external_connection.go in pkg/crosscluster/physical.validatePostgresConnectionURI at line 30
pkg/crosscluster/streamclient/partitioned_stream_client.go in pkg/crosscluster/streamclient.NewPartitionedStreamClient at line 48
pkg/crosscluster/streamclient/pgconn.go in pkg/crosscluster/streamclient.newPGConnForClient at line 36
pkg/crosscluster/streamclient/pgconn.go in pkg/crosscluster/streamclient.setupPGXConfig at line 48
pkg/crosscluster/streamclient/pgconn.go in pkg/crosscluster/streamclient.uriWithInlineTLSCertsRemoved at line 110
GOROOT/src/encoding/pem/pem.go in encoding/pem.EncodeToMemory at line 312
GOROOT/src/encoding/pem/pem.go in encoding/pem.Encode at line 242
GOROOT/src/runtime/signal_unix.go in runtime.sigpanic at line 881
GOROOT/src/runtime/panic.go in runtime.panicmem at line 261
GOROOT/src/runtime/panic.go in runtime.gopanic at line 770
pkg/sql/colexecerror/error.go in pkg/sql/colexecerror.CatchVectorizedRuntimeError.func1 at line 137
GOROOT/src/runtime/panic.go in runtime.gopanic at line 770
pkg/sql/colexecerror/error.go in pkg/sql/colexecerror.CatchVectorizedRuntimeError.func1 at line 137
GOROOT/src/runtime/panic.go in runtime.gopanic at line 770
pkg/sql/conn_executor.go in pkg/sql.(*Server).ServeConn.func1 at line 998
```

### Tags

| Tag | Value |
| --- | --- |
| Command | server |
| Environment | v25.1.0 |
| Go Version | go1.22.8 X:nocoverageredesign |
| Platform | linux amd64 |
| Distribution | CCL |
| Cockroach Release | v25.1.0 |
| Cockroach SHA | e5ec46c9865849c0b20ffa1b351372ced6c578b4 |
| # of CPUs | 4 |
| # of Goroutines | 532 |

Jira issue: CRDB-50297

Epic CRDB-50820

### PR DESCRIPTION
**Pull request by kev-cao**
Previously, when parsing inline SSL certificates in an external connection, if the certificate was not formatted correctly we would run into a panic from a nil pointer. This fixes the parser to properly surface an error instead of crashing.

Epic: CRDB-50820

Fixes: #145949

Release note: CockroachDB now raises an error when encountering improper inline SSL credentials instead of panicking.

### CODE REVIEW

File: pkg/crosscluster/streamclient/pgconn.go [hunk 1]
```diff
@@ -62,7 +62,7 @@ func setupPGXConfig(remote url.URL, options *options) (*pgx.ConnConfig, error) {
 	config.DialFunc = dialer.DialContext
 
 	// If the user hasn't given us an application name.
-	if _, ok := config.RuntimeParams["application_name"]; !ok {
+	if _, ok := config.RuntimeParams["application_name"]; !ok && options != nil {
```
Comment (kev-cao) [inline pkg/crosscluster/streamclient/pgconn.go]: Not sure if we should return an error here if `application_name` cannot be determined?

File: pkg/crosscluster/streamclient/client_test.go [hunk 2]
```diff
@@ -326,3 +326,110 @@ func TestStreamClientAppName(t *testing.T) {
 	expectAppName(t, "$ internal repstream")
 	expectAppName(t, "$ internal repstream job id=1337", WithStreamID(1337))
 }
+
+func TestInlineSSLCertParsing(t *testing.T) {
+	defer leaktest.AfterTest(t)()
+	defer log.Scope(t).Close(t)
+
+	// These are valid but totally unused certs and keys.
```
Comment (jeffswenson) [inline pkg/crosscluster/streamclient/client_test.go:334]: nit: can you document the command you used to generate the certs in the comment?

File: pkg/crosscluster/streamclient/pgconn.go (hunk 1 above)
Comment (jeffswenson) [reply pkg/crosscluster/streamclient/pgconn.go]: nit: can options actually be null here? I would rather fix the caller than add a null check. You could also optionally make this take options by value.

File: pkg/crosscluster/streamclient/pgconn.go [hunk 3]
```diff
@@ -107,6 +107,9 @@ func uriWithInlineTLSCertsRemoved(remote url.URL) (url.URL, *tlsCerts, error) {
 		// are deprecated in the stdlib. For now, I've skipped
 		// it.
 		block, _ := pem.Decode([]byte(key))
+		if block == nil {
```
Comment (jeffswenson) [inline pkg/crosscluster/streamclient/pgconn.go:110]: We should validate we can parse the cert when the user first tries to create the external connection. Having to debug a failing job is much more annoying than seeing an create external connection failure.

File: pkg/crosscluster/streamclient/client_test.go [hunk 4]
```diff
@@ -326,3 +326,110 @@ func TestStreamClientAppName(t *testing.T) {
 	expectAppName(t, "$ internal repstream")
 	expectAppName(t, "$ internal repstream job id=1337", WithStreamID(1337))
 }
+
+func TestInlineSSLCertParsing(t *testing.T) {
```
Comment (jeffswenson) [inline pkg/crosscluster/streamclient/client_test.go:330]: Nice test!

File: pkg/crosscluster/streamclient/pgconn.go (hunk 1 above)
Comment (kev-cao) [reply pkg/crosscluster/streamclient/pgconn.go]: I don't think it can be `nil` here based on how we use the result of `processOptions`, so this is mostly a safety check. That being said, I think not using `nil` makes more sense if there's no semantic reason to do so. Will update.

File: pkg/crosscluster/streamclient/client_test.go (hunk 2 above)
Comment (kev-cao) [reply pkg/crosscluster/streamclient/client_test.go:334]: Well I technically just went to a random cert generator online 😅 I'll look up a proper command though

File: pkg/crosscluster/streamclient/pgconn.go (hunk 3 above)
Comment (kev-cao) [reply pkg/crosscluster/streamclient/pgconn.go:110]: Yeah I agree. The `nil` checks here should still be done though just for completeness and avoid panics instead of relying on an assumption that the query parameters have already been validated

**Comment by stevendanna** [comment]
Seems like we should probably backport this?

**Review by jeffswenson — APPROVED** [review]
LGTM

**Review by stevendanna — APPROVED** [review]
Thanks a ton for fixing this.

**Comment by kev-cao** [comment]
TFTR!

bors r=jeffswenson,stevendanna

**Comment by kev-cao** [comment]
bors r=jeffswenson,stevendanna
