### PR TITLE
sql: implement datetime_precision column in information_schema.columns

### LINKED ISSUE #51286: Implement the information_schema.columns.datetime_precision column
**Describe the problem**

Not sure if this is a bug or a missing feature, but since the column is there but empty, I'd say it's a bug.

The `information_schema.columns.datetime_precision` is always empty, despite its being quite useful for third party tools to reverse engineer the data type of a user table.

**To Reproduce**

```sql
CREATE TABLE ts (
  ts_p0 timestamp(0),
  ts_p1 timestamp(1),
  ts_p3 timestamp(3),
  ts_p6 timestamp(6)
);

SELECT column_name, data_type, datetime_precision 
FROM information_schema.columns
WHERE table_name = 'ts';
```

Produces:

```
column_name|data_type                  |datetime_precision|
-----------|---------------------------|------------------|
ts_p0      |timestamp without time zone|                  |
ts_p1      |timestamp without time zone|                  |
ts_p3      |timestamp without time zone|                  |
ts_p6      |timestamp without time zone|                  |
rowid      |bigint                     |                  |
```

**Expected behavior**

I would expect this outcome:

```
column_name|data_type                  |datetime_precision|
-----------|---------------------------|------------------|
ts_p0      |timestamp without time zone|                 0|
ts_p1      |timestamp without time zone|                 1|
ts_p3      |timestamp without time zone|                 3|
ts_p6      |timestamp without time zone|                 6|
rowid      |bigint                     |                  |
```

A workaround is to use the `crdb_sql_type` column, which contains a formatted version of the data type:

```sql
SELECT column_name, data_type, datetime_precision, crdb_sql_type 
FROM information_schema.columns
WHERE table_name = 'ts';
```

Producing:

```
column_name|data_type                  |datetime_precision|crdb_sql_type|
-----------|---------------------------|------------------|-------------|
ts_p0      |timestamp without time zone|                  |TIMESTAMP(0) |
ts_p1      |timestamp without time zone|                  |TIMESTAMP(1) |
ts_p3      |timestamp without time zone|                  |TIMESTAMP(3) |
ts_p6      |timestamp without time zone|                  |TIMESTAMP(6) |
rowid      |bigint                     |                  |INT8         |
```

I always feel a bit uneasy to use formatted output, as it might change incompatibly between versions, or produce unforeseen formatting caveats.

**Environment:**
 - CockroachDB version: CockroachDB CCL v20.1.3 (x86_64-unknown-linux-gnu, built 2020/06/23 08:44:08, go1.13.9)
 - Server OS: Docker
 - Client app: JDBC

### PR DESCRIPTION
**Pull request by spiffyy99**
Before: The datetime_precision column was null for all types.

Why: Useful for users to reverse engineer the data type of columns in
a user table.

Now: The datetime_precision column shows the precision for columns with
type `TIME`/`TIMETZ`, `TIMESTAMP`/`TIMESTAMPTZ` and `INTERVAL`, and is null for
any other types.

Resolves #51286

Release note (sql change): Implement the datetime_precision column in
the information_schema.columns table for time-stored values.

### CODE REVIEW

**Comment by r6min** [comment]
I believe the [docs](https://www.cockroachlabs.com/docs/v20.1/information-schema.html#columns) need to be updated as well, not sure what the process for this is.

File: pkg/sql/information_schema.go [hunk 1]
```diff
@@ -572,9 +572,21 @@ func numericScale(colType *types.T) tree.Datum {
...
 
+// datetimePrecision returns the declared or implicit precision of Time,
+// Timestamp or Interval data types. Returns false if the data type is not
+// a Time, Timestamp or Interval.
 func datetimePrecision(colType *types.T) tree.Datum {
-	// We currently do not support a datetime precision.
-	return tree.DNull
+	return dIntFnOrNull(func() (int32, bool) {
+		switch colType.Family() {
+		case types.TimeFamily, types.TimeTZFamily:
```
Comment (otan) [inline pkg/sql/information_schema.go:581]: any reason to not just do

```
		case types.TimeFamily, types.TimeTZFamily, case types.TimestampFamily, types.TimestampTZFamily, types.IntervalFamily: // you can new line between commas if you want?
```

**Comment by RichardJCai** [comment]
> I believe the [docs](https://www.cockroachlabs.com/docs/v20.1/information-schema.html#columns) need to be updated as well, not sure what the process for this is.

Docs updates based on the release notes we include.
https://wiki.crdb.io/wiki/spaces/CRDB/pages/186548364/Release+notes

**Review by otan — COMMENTED** [review]
thanks! one comment

File: pkg/sql/information_schema.go (hunk 1 above)
Comment (r6min) [reply pkg/sql/information_schema.go]: Fixed.

**Review by otan — APPROVED** [review]
