### PR TITLE
roachtest: ensure valid suspect duration in mixed version decommission

### LINKED ISSUE #107150: roachtest: decommission/mixed-versions failed
roachtest.decommission/mixed-versions [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/10967169?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/10967169?buildTab=artifacts#/decommission/mixed-versions) on master @ [06b5ba7888339ed53477ff73f9f3ae77a708ee17](https://github.com/cockroachdb/cockroach/commits/06b5ba7888339ed53477ff73f9f3ae77a708ee17):

```
(cluster.go:2282).Run: output in run_060233.263805177_n3_cockroach-node-decom: ./cockroach node decommission --wait=all --insecure 2 returned: COMMAND_PROBLEM: exit status 1
test artifacts and logs in: /artifacts/decommission/mixed-versions/run_1
```
<p>Parameters: <code>ROACHTEST_arch=amd64</code>
, <code>ROACHTEST_cloud=gce</code>
, <code>ROACHTEST_cpu=4</code>
, <code>ROACHTEST_encrypted=false</code>
, <code>ROACHTEST_ssd=0</code>
</p>
<details><summary>Help</summary>
<p>

See: [roachtest README](https://github.com/cockroachdb/cockroach/blob/master/pkg/cmd/roachtest/README.md)

See: [How To Investigate \(internal\)](https://cockroachlabs.atlassian.net/l/c/SSSBr8c7)

</p>
</details>
/cc @cockroachdb/kv-triage
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*decommission/mixed-versions.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)
</sub>

Jira issue: CRDB-29914

### PR DESCRIPTION
**Pull request by AlexTalks**
In https://github.com/cockroachdb/cockroach/pull/106859, the `decommission/mixed-versions` test was updated to
properly support the decommission pre-checks introduced in 23.1, however
in doing so there was an inadvertent bug introduced in the test due to
the `server.time_after_store_suspect` setting. While this setting can be
used to shorten the time a store is considered suspect after node
restart, there exists a discrepency in this setting between 23.1 (the
current predecessor major version) and 23.2, as 23.2 requires the
setting to have a minimum of 10s, otherwise reverting to the default of
30s, despite the fact that this validation is not performed when the
setting is actually overridden on the predecessor version.

This change corrects that mistake, setting the value to the correct
minimum version and waiting out the "suspect" time after restart before
attempting decommission.

Fixes: https://github.com/cockroachdb/cockroach/issues/107150.

Release note: None

### CODE REVIEW

File: pkg/cmd/roachtest/tests/mixed_version_decommission.go [hunk 1]
```diff
@@ -40,12 +40,13 @@ func runDecommissionMixedVersions(
...
-	// The v20.2 CLI can only be run against servers running v20.2. For this
-	// reason, we grab a handle on a specific server slated for an upgrade.
 	pinnedUpgrade := h.getRandNode()
 	t.L().Printf("pinned n%d for upgrade", pinnedUpgrade)
 
-	const suspectDuration = 5 * time.Second
+	// NB: The suspect duration must be at least 10s, as versions 23.2 and
+	// beyond will reset to the default of 30s if it fails validation, even if
+	// set by a previous version.
+	const suspectDuration = 10 * time.Second
```
Comment (andrewbaptist) [inline pkg/cmd/roachtest/tests/mixed_version_decommission.go:49]: nit: You can use the constant `liveness.minTimeUntilNodeSuspect` - although you would have to make that a public const. It might be easier to see where this comes from and if it changes later.

**Review by andrewbaptist — APPROVED** [review]
:lgtm: - although consider changing to use the constant for the suspect duration.
