### PR TITLE
logical: support rewriting fk descriptors for CREATE TABLE 

### LINKED ISSUE #152277: Attempting to create a logically replicated table with foreign key causes crash
**Describe the problem**

When using `CREATE LOGICALLY REPLICATED TABLE` across two separate physical clusters, if the source table references a table with a foreign key, a stack trace is produced.

**To Reproduce**

Create two clusters, one node per cluster is fine.  This was reproduced on v25.3.0.

On the source cluster, run these commands:

```
SET CLUSTER SETTING kv.rangefeed.enabled = true;

CREATE TABLE parent(pid UUID PRIMARY KEY); -- create a parent table to be referenced later

CREATE TABLE source(id UUID PRIMARY KEY, pid UUID REFERENCES parent(pid));
```

Then on the destination cluster, run these commands:

```
CREATE EXTERNAL CONNECTION source AS 'postgresql://root:p@172.28.128.21:26257';

CREATE LOGICALLY REPLICATED TABLE defaultdb.public.destination FROM TABLE defaultdb.public.source ON 'external://source' WITH UNIDIRECTIONAL;
```

This error is produced:

```
ERROR: internal error: restoring table desc and namespace entries: relation "destination" (104): invalid outbound foreign key "source_pid_fkey": origin table ID should be 104. got 105
SQLSTATE: XX000
DETAIL: stack trace:
pkg/sql/catalog/tabledesc/validate.go:564: validateSelfFKs()
pkg/sql/catalog/tabledesc/validate.go:896: ValidateSelf()
pkg/sql/catalog/internal/validate/validate.go:79: func1()
pkg/sql/catalog/internal/validate/validate.go:197: validateDescriptorsAtLevel()
pkg/sql/catalog/internal/validate/validate.go:75: Validate()
pkg/sql/catalog/internal/validate/validate.go:40: Self()
pkg/sql/catalog/descs/collection.go:356: WriteDescToBatch()
pkg/sql/catalog/ingesting/write_descs.go:162: WriteDescriptors()
pkg/sql/catalog/externalcatalog/external_catalog.go:163: IngestExternalCatalog()
pkg/crosscluster/logical/create_logical_replication_stmt.go:447: func1()
pkg/sql/internal.go:1944: func2()
pkg/sql/internal.go:2041: func4()
pkg/kv/txn.go:1132: exec()
pkg/kv/db.go:1074: runTxn()
pkg/kv/db.go:1037: TxnWithAdmissionControl()
pkg/kv/db.go:1012: Txn()
pkg/sql/internal.go:2028: txn()
pkg/sql/internal.go:1942: DescsTxn()
pkg/crosscluster/logical/create_logical_replication_stmt.go:437: doLDRPlan()
pkg/crosscluster/logical/create_logical_replication_stmt.go:331: func1()
pkg/sql/planhook.go:189: func1()
pkg/util/stop/stopper.go:438: func1()
src/runtime/asm_amd64.s:1700: goexit()

HINT: You have encountered an unexpected error.
```

**Expected behavior**
It should show the error message that replicating a table with a foreign key requires 

**Environment:**
 - CockroachDB version [e.g. 25.3.0]

**Additional context**
Unable to set up PCR.  Stack trace produced.

Jira issue: CRDB-53755

Epic CRDB-60163

### PR DESCRIPTION
**Pull request by DarrylWong**
This change adds a Rewrite method to the MutableDescriptor interface, which visits every descriptor ID and remaps them using the provided DescriptorRewriteFn callback. This new Rewrite method is by LDR to support rewriting FK descriptor IDs in the CREATE LOGICALLY REPLICATED TABLE flow.

See individual commits for more details.

Fixes: https://github.com/cockroachdb/cockroach/issues/152277
Release note: none

### CODE REVIEW

**Review by spilchen — COMMENTED** [review]
I assume this new rewrite logic will eventually be used within backup/restore (as per the slack conversation)? Is there a tracking issue for that? It would be nice if we didn't have to live with the dual rewrite code for long.

> @spilchen reviewed 8 files and made 5 comments.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/168338#-:-OqMPq4r-ZCdVH69t5rZ:b-8ff8hr)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on andrew-r-thomas, DarrylWong, and jeffswenson).

___
*[`pkg/sql/catalog/tabledesc/rewrite_test.go` line 35 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/168338#-OqMRq2X29tBKn-4PvoP:-OqMRq2X29tBKn-4PvoQ:brkkyyo) ([raw file](https://github.com/cockroachdb/cockroach/blob/11506586941b61fbfcfdc0dc897718554cfcfec1/pkg/sql/catalog/tabledesc/rewrite_test.go#L35)):*
> ```Go
> // implementation visits every ID properly, i.e. it's okay to construct
> // nonsensical table descriptors.
> func randomTableDesc(rng *rand.Rand) *descpb.TableDescriptor {
> ```

there was a slack discussion on this to use reflection to find all descriptor IDs and functions that should be rewritten. Is that going to be in this PR, or as a follow-up?
___
*[`pkg/sql/catalog/externalcatalog/external_catalog.go` line 187 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/168338#-OqMK95k40iOfy9jD73f:-OqMK95l8Gu61uBtq9XS:b-h6lc35) ([raw file](https://github.com/cockroachdb/cockroach/blob/11506586941b61fbfcfdc0dc897718554cfcfec1/pkg/sql/catalog/externalcatalog/external_catalog.go#L187)):*
> ```Go
> 	// Second pass to add/drop any descriptor fields as well as validation.
> 	for i, t := range tables {
> 		t.Name = ingestingUnqualifiedTableNames[i]
> ```

is the assumption that `len(tables) == len(ingestingUnqualifiedTableNames)`? Otherwise, we could reference something out of bounds. Could we add a defensive check for this?
___
*[`pkg/sql/catalog/externalcatalog/external_catalog.go` line 242 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/168338#-OqMJjhvBJ2gXpUkiXuD:-OqMJjhvBJ2gXpUkiXuE:bn1sa54) ([raw file](https://github.com/cockroachdb/cockroach/blob/11506586941b61fbfcfdc0dc897718554cfcfec1/pkg/sql/catalog/externalcatalog/external_catalog.go#L242)):*
> ```Go
> 		idRewrites[table.ID] = newID
> 	}
> 	idRewrites[tables[0].ParentID] = destDBID
> ```

we reference `tables[0]` unconditionally without checking if the slice has any elements. Does the caller assume there is at least one table to remap? We could use some defensive programming here.
___
*[`pkg/sql/catalog/externalcatalog/external_catalog.go` line 242 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/168338#-OqMLjtcATMsLiE44bQ4:-OqMLjtcATMsLiE44bQ5:b-ktfldo) ([raw file](https://github.com/cockroachdb/cockroach/blob/11506586941b61fbfcfdc0dc897718554cfcfec1/pkg/sql/catalog/externalcatalog/external_catalog.go#L242)):*
> ```Go
> 		idRewrites[table.ID] = newID
> 	}
> 	idRewrites[tables[0].ParentID] = destDBID
> ```

it's not obvious why this two map updates are needed for. Can you leave a comment here to explain it a bit?

**Comment by DarrylWong** [comment]
>there was a slack discussion on this to use reflection to find all descriptor IDs and functions that should be rewritten. Is that going to be in this PR, or as a follow-up?

Yeah I'll try to address in this PR. Have it mostly working but I'll move this to draft until its ready for another look.

File: pkg/util/walkutil/walk.go [hunk 1]
```diff
@@ -0,0 +1,102 @@
...
+			if !value.IsNil() {
+				walk(value.Elem())
+			}
+		case reflect.Struct:
+			for i := 0; i < value.NumField(); i++ {
+				if f := value.Field(i); f.CanAddr() && value.Type().Field(i).IsExported() {
+					walk(f.Addr().Elem())
+				}
+			}
+		case reflect.Interface:
```
Comment (DarrylWong) [inline pkg/util/walkutil/walk.go:73]: This function is identical to the old schemachanger walk with the exception that we now need to handle interfaces and maps.

**Review by DarrylWong — COMMENTED** [review]
> @DarrylWong made 4 comments.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/168338)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on andrew-r-thomas, jeffswenson, and spilchen).

___
*[`pkg/sql/catalog/externalcatalog/external_catalog.go` line 187 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/168338#-OqMK95k40iOfy9jD73f:-OqfVtZD6j1C0yx0YhRD:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/11506586941b61fbfcfdc0dc897718554cfcfec1/pkg/sql/catalog/externalcatalog/external_catalog.go#L187)):*
<details><summary><i>Previously, spilchen wrote…</i></summary><blockquote>

is the assumption that `len(tables) == len(ingestingUnqualifiedTableNames)`? Otherwise, we could reference something out of bounds. Could we add a defensive check for this?
</blockquote></details>

Done.
___
*[`pkg/sql/catalog/externalcatalog/external_catalog.go` line 242 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/168338#-OqMJjhvBJ2gXpUkiXuD:-OqfVpUg1QYxbbKOfpIO:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/11506586941b61fbfcfdc0dc897718554cfcfec1/pkg/sql/catalog/externalcatalog/external_catalog.go#L242)):*
<details><summary><i>Previously, spilchen wrote…</i></summary><blockquote>

we reference `tables[0]` unconditionally without checking if the slice has any elements. Does the caller assume there is at least one table to remap? We could use some defensive programming here.
</blockquote></details>

Done.
___
*[`pkg/sql/catalog/externalcatalog/external_catalog.go` line 242 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/168338#-OqMLjtcATMsLiE44bQ4:-OqfVwEABBaHwgZuo8_p:b-7apy9n) ([raw file](https://github.com/cockroachdb/cockroach/blob/11506586941b61fbfcfdc0dc897718554cfcfec1/pkg/sql/catalog/externalcatalog/external_catalog.go#L242)):*
<details><summary><i>Previously, spilchen wrote…</i></summary><blockquote>

it's not obvious why this two map updates are needed for. Can you leave a comment here to explain it a bit?
</blockquote></details>

I added a comment explaining what ID we are remapping, but the reason we need to remap it is the same as all the ids (we're replicating tables into a new cluster, so all the IDs no longer point to valid desc IDs). I opted for a high level comment in `IngestExternalCatalog` instead.
___
*[`pkg/sql/catalog/tabledesc/rewrite_test.go` line 35 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/168338#-OqMRq2X29tBKn-4PvoP:-OqfXuox3FKdciQ2MHIS:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/11506586941b61fbfcfdc0dc897718554cfcfec1/pkg/sql/catalog/tabledesc/rewrite_test.go#L35)):*
<details><summary><i>Previously, spilchen wrote…</i></summary><blockquote>

there was a slack discussion on this to use reflection to find all descriptor IDs and functions that should be rewritten. Is that going to be in this PR, or as a follow-up?
</blockquote></details>

Done.

File: pkg/sql/catalog/externalcatalog/external_catalog.go [hunk 2]
```diff
@@ -172,6 +165,115 @@ func IngestExternalCatalog(
...
+// ldrDescriptorRewriter builds a DescriptorRewriteFn for LDR ingestion.
+// IDs in the rewrite map are remapped; everything else is kept as-is.
+func ldrDescriptorRewriter(idRewrites map[descpb.ID]descpb.ID) catalog.DescriptorRewriteFn {
+	return func(id descpb.ID) (descpb.ID, error) {
+		if newID, ok := idRewrites[id]; ok {
+			return newID, nil
+		}
+		// For now, we skip rewriting unknown IDs, i.e. keep them as is. Eventually
+		// we should handle every ID explicitly and can return an error here.
+		return id, nil
```
Comment (jeffswenson) [inline pkg/sql/catalog/externalcatalog/external_catalog.go:274]: Is there a case where this would actually work without corrupting the descriptor? Maybe we should return an error here that causes the job to fail.

File: pkg/sql/catalog/catalog.go [hunk 3]
```diff
@@ -47,6 +51,10 @@ type MutableDescriptor interface {
 	// SetDeclarativeSchemaChangerState sets the state of the declarative
 	// schema change currently operating on this descriptor.
 	SetDeclarativeSchemaChangerState(*scpb.DescriptorState)
+
+	// Rewrite visits all descriptor ID references within the descriptor
+	// and remaps them using the provided DescriptorRewriteFn callback.
```
Comment (jeffswenson) [inline pkg/sql/catalog/catalog.go:56]: nit: Include a note in the comment that rewrite also mutates the descriptor so that it looks like a new descriptor. It should only be called on descriptors that are being ingested into the cluster and did not previously exist.

File: pkg/util/walkutil/walk.go [hunk 4]
```diff
@@ -0,0 +1,102 @@
...
+
+	"github.com/cockroachdb/cockroach/pkg/util/iterutil"
+	"github.com/cockroachdb/errors"
+)
+
+// Walk will use reflection to find all values which are either scalars
+// types or pointers types and pass them to f as pointers. The
+// expectation is that the input is a pointer to some structure so that
+// everything is addressable.
+func Walk(wantType reflect.Type, toWalk interface{}, f func(interface{}) error) (err error) {
```
Comment (jeffswenson) [inline pkg/util/walkutil/walk.go]: consider: you could make this a generic function.
```
func Walk[T any](toWalk any, f func(interface{}) error) (err error) {
    wantType := reflect.TypeOf((*T)(nil))
    ...
}
```

File: pkg/sql/catalog/descutil/rewrite.go [hunk 5]
```diff
@@ -0,0 +1,225 @@
...
+
+	arrayID := catid.UserDefinedOIDToID(typ.UserDefinedArrayOID())
+	newArrayID, err := rewriter(arrayID)
+	if err != nil {
+		return err
+	}
+	newArrayOID := catid.TypeIDToOID(newArrayID)
+
+	types.RemapUserDefinedTypeOIDs(typ, newOID, newArrayOID)
+	if typ.Family() == types.ArrayFamily {
```
Comment (jeffswenson) [inline pkg/sql/catalog/descutil/rewrite.go]: What about other recursive types like Tuple?

File: pkg/sql/catalog/descutil/rewrite.go [hunk 6]
```diff
@@ -0,0 +1,225 @@
...
+	var err error
+	ctx := tree.NewFmtCtx(
+		tree.FmtSerializable,
+		tree.FmtIndexedTypeFormat(func(fmtCtx *tree.FmtCtx, ref *tree.OIDTypeReference) {
+			if err != nil {
+				fmtCtx.WriteString(ref.SQLString())
+				return
+			}
+			id := catid.UserDefinedOIDToID(ref.OID)
+			if descpb.IsVirtualTable(id) {
```
Comment (jeffswenson) [inline pkg/sql/catalog/descutil/rewrite.go]: UserDefinedOIDToID(ref.OID) applies an offset to ref.OID. So IsVirtualTable(id) should probably be IsVirtualTable(ref.OID).

File: pkg/sql/catalog/externalcatalog/external_catalog.go (hunk 2 above)
Comment (DarrylWong) [reply pkg/sql/catalog/externalcatalog/external_catalog.go:274]: There's some implications w/ error handling. We currently run validation for non supported features on the ingested table, i.e. after we rewrite. If we return an error here, we would lose the more specific e.g. "TRIGGERS are not supported in LDR" error message. That being said, I'll see if moving the validation to the source cluster before we ingest would break anything. Then we should be able to throw an assertion error here.

File: pkg/util/walkutil/walk.go (hunk 4 above)
Comment (DarrylWong) [reply pkg/util/walkutil/walk.go]: Done.

File: pkg/sql/catalog/catalog.go (hunk 3 above)
Comment (DarrylWong) [reply pkg/sql/catalog/catalog.go:56]: Done.

File: pkg/sql/catalog/descutil/rewrite.go (hunk 5 above)
Comment (DarrylWong) [reply pkg/sql/catalog/descutil/rewrite.go]:
```
ERROR: unimplemented: composite types that reference user-defined types not yet supported                                                                                              
  SQLSTATE: 0A000                                                                                                                                                                        
  HINT: You have attempted to use a feature that is not yet implemented.  
```

Not supported, which is good because we don't handle it in the restore flow. I think it's probably good to future proof this for when we do implement support since it's minimal code. Added a Tuple case.

File: pkg/sql/catalog/descutil/rewrite.go (hunk 6 above)
Comment (DarrylWong) [reply pkg/sql/catalog/descutil/rewrite.go]: Fixed

File: pkg/sql/catalog/externalcatalog/external_catalog.go (hunk 2 above)
Comment (DarrylWong) [reply pkg/sql/catalog/externalcatalog/external_catalog.go:274]: I tried extracting some of the single table specific validation out in the form of unsupported features, and calling it pre ingestion. However:

1. There's some edge cases we don't handle. UDTs and VIEWS are the two that me/claude were able to think of, but there might be more. These two IDs are fine in the non CREATE TABLE flow but need to be rewritten for CREATE TABLE. I initially attempted adding validation that don't have UDTs/VIEWs anymore, but the work involved to do this feels like similar if not more effort than just supporting rewriting these IDs?
2. We can't get rid of the post ingestion validation because it's used for both the CREATE TABLE and non CREATE TABLE flows. So we are essentially double validating, which is unfortunate but maybe fine?


I can keep iterating on this though if you feel like its the right path. A simpler alternative vs doing all this could maybe just have the rewriter throw a generic "unmapped id %d references an unsupported feature" error which might be good enough. Wdyt?

Comment (jeffswenson) [reply pkg/sql/catalog/externalcatalog/external_catalog.go:274]: Can we move the destination side validation to before we execute the remapping? E.g. validate the source descriptors? I feel like a majority of our recent TA level bugs have been due to ignoring errors like this.

I'm okay with opening an issue and assigning a todo here for now.

**Review by jeffswenson — APPROVED** [review]
LGTM

Nice work!

File: pkg/sql/catalog/externalcatalog/external_catalog.go (hunk 2 above)
Comment (DarrylWong) [reply pkg/sql/catalog/externalcatalog/external_catalog.go:274]: Yeah, that's essentially what I was trying to do but it was getting complex since there are explicit edge cases we aren't checking for post ingestion (which is probably a good argument to do it). I'll open an issue since this PR is already fairly large.
