### PR TITLE
Fix the main cause of flakiness in TestReplicaRogueRemoveNode.

### LINKED ISSUE #3538: Failed tests (10381): TestReplicateRogueRemovedNode
The following test appears to have failed:

[#10381](https://circleci.com/gh/cockroachdb/cockroach/10381):

```
W1228 15:49:51.779876 977 multiraft/multiraft.go:1297  node 1 failed to send message to 3: multiraft/transport.go:157: unknown peer 3
W1228 15:49:51.788759 977 multiraft/multiraft.go:1297  node 2 failed to send message to 3: multiraft/transport.go:157: unknown peer 3
I1228 15:49:51.832610 977 storage/engine/rocksdb.go:137  closing in-memory rocksdb instance
I1228 15:49:51.832793 977 storage/engine/rocksdb.go:137  closing in-memory rocksdb instance
I1228 15:49:51.832925 977 storage/engine/rocksdb.go:137  closing in-memory rocksdb instance
--- FAIL: TestReplicateRogueRemovedNode (1.46s)
	<autogenerated>:32: storage/client_raft_test.go:1321: condition failed to evaluate within 1s: storage/client_test.go:575: expected [16 0 5], got [16 5 5]
=== RUN   TestReplicateReAddAfterDown
E1228 15:49:51.835017 977 gossip/gossip.go:180  different node IDs were set for the same gossip instance (2147483647, 1)
I1228 15:49:51.836157 977 storage/replica.go:1307  gossiping cluster id  from store 1, range 1
I1228 15:49:51.836546 977 multiraft/multiraft.go:578  node 1 starting
I1228 15:49:51.837495 977 raft/raft.go:446  [group 1] 1 became follower at term 5
I1228 15:49:51.837604 977 raft/raft.go:234  [group 1] newRaft 1 [peers: [1], term: 5, commit: 10, applied: 10, lastindex: 10, lastterm: 5]
I1228 15:49:51.837683 977 multiraft/multiraft.go:998  node 1 campaigning because initial confstate is [1]
I1228 15:49:51.837727 977 raft/raft.go:526  [group 1] 1 is starting a new election at term 5
I1228 15:49:51.837774 977 raft/raft.go:459  [group 1] 1 became candidate at term 6
--
I1228 15:50:03.929918 977 storage/engine/rocksdb.go:137  closing in-memory rocksdb instance
I1228 15:50:03.930140 977 storage/engine/rocksdb.go:137  closing in-memory rocksdb instance
--- PASS: TestLeaderAfterSplit (0.35s)
=== RUN   Example_rebalancing
--- PASS: Example_rebalancing (0.79s)
FAIL
FAIL	github.com/cockroachdb/cockroach/storage	34.112s
=== RUN   TestBatchBasics
I1228 15:49:40.422118 1039 storage/engine/rocksdb.go:137  closing in-memory rocksdb instance
--- PASS: TestBatchBasics (0.00s)
=== RUN   TestBatchGet
I1228 15:49:40.425449 1039 storage/engine/rocksdb.go:137  closing in-memory rocksdb instance
--- PASS: TestBatchGet (0.01s)
=== RUN   TestBatchMerge
I1228 15:49:40.431756 1039 storage/engine/rocksdb.go:137  closing in-memory rocksdb instance
--- PASS: TestBatchMerge (0.00s)
=== RUN   TestBatchProto

```
Please assign, take a look and update the issue accordingly.

### PR DESCRIPTION
**Pull request by bdarnell**
The major issue is that a raft group could be reawakened during the GC
processing, so a single GC queue pass was not enough.

Fixes #3538.

[Review on Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/3593)

### CODE REVIEW

**Comment by tschottdorf** [comment]
LGTM

File: storage/queue.go [hunk 1]
```diff
@@ -400,8 +401,12 @@ func (bq *baseQueue) remove(index int) {
 // Exposed for testing only.
 func (bq *baseQueue) DrainQueue(clock *hlc.Clock) {
 	bq.Lock()
-	defer bq.Unlock()
-	for repl := bq.pop(); repl != nil; repl = bq.pop() {
+	repl := bq.pop()
```
Comment (BramGruneir) [inline storage/queue.go]: The idea here was to keep the queue locked so nothing else could be added.  We don't have the controls to stop a queue from queueing while at the same time processing all existing replicas.

Comment (bdarnell) [inline storage/queue.go]: Why is that a concern? Even with a single lock acquisition new replicas could be added just before or after the call to DrainQueue. As long as we're not adding new replicas faster than we can process then then DrainQueue will process *at least* one full cycle, which is what we want.

Comment (BramGruneir) [inline storage/queue.go]: I was just worried about tests running slowly continuously adding in more replicas faster than we could drain is all.

Comment (bdarnell) [inline storage/queue.go]: If we're enqueuing things faster than we can process them then we're in trouble anyway, so I'm OK if tests time out in that case.

Comment (BramGruneir) [inline storage/queue.go]: SGTM
