### PR TITLE
backup: allow external connections to be used with online restore

### LINKED ISSUE #158511: online restore: integrate w extconn
it doesn't work right now :-) we should make it work so we have parity with the rest of our restore/backup service
cc @codingconcepts 

Jira issue: CRDB-57358

### PR DESCRIPTION
**Pull request by andrew-r-thomas**
Previously, external connections were not supported in online restore due to
external connections being unavailable during early boot. This patch
materializes external connections into their underlying uris before the restore
job accesses external storage.

Fixes: https://github.com/cockroachdb/cockroach/issues/158511

Release note (backup change): external connections can now be used with online
restore

### CODE REVIEW

File: pkg/backup/restore_job.go [hunk 1]
```diff
@@ -1899,6 +1902,40 @@ func (r *restoreResumer) doResume(ctx context.Context, execCtx interface{}) erro
...
+			if uri.Scheme == "external" {
+				err := p.ExecCfg().InternalDB.Txn(ctx, func(ctx context.Context, t isql.Txn) error {
+					ec, err := externalconn.LoadExternalConnection(ctx, uri.Host, t)
+					if err != nil {
+						return err
+					}
+					connDetails := ec.ConnectionProto()
+					switch d := connDetails.Details.(type) {
+					case *connectionpb.ConnectionDetails_SimpleURI:
+						details.URIs[i] = d.SimpleURI.URI + uri.Path
```
Comment (jeffswenson) [inline pkg/backup/restore_job.go]: If possible, I would prefer to implement this change in a way where we don't need to modify the job record. From a bootstrapping standpoint, if we can read the job record we can read the external connection. We just need to make sure the SST uri's we send during the link phase have a physical URI in them.

Comment (jeffswenson) [inline pkg/backup/restore_job.go]: What do you think of adding a method to the external connection object that translates a an external url to the corresponding real url. I'm thinking something like:

```
ec, err := externalconn.LoadExternalConnection(ctx, uri.Host, t)
if err != nil {
    return err
}
... get the URIs to the individual objects
innerUri, err := ec.Materialize(objectURI) 
if err {
   // this could be a validation error if the objectURI is not prefixed with
   // the external connection uri.
}
```

Alternatively, we may want to add this to the cloud object. Something like:
```
externalStorage.FullUri(relativeUri)
```

File: pkg/backup/restore_online_test.go [hunk 2]
```diff
@@ -792,6 +792,67 @@ func TestOnlineRestoreFailScatterNonEmptyRanges(t *testing.T) {
 	require.Greater(t, postPauseScatterRequests.Load(), postPauseSuccessfulScatters.Load())
 }
 
+func TestOnlineRestoreExtConn(t *testing.T) {
```
Comment (jeffswenson) [inline pkg/backup/restore_online_test.go]: This is a great test! One thing you may want to consider is adding a GetBackupURI that is similar to [`replicationtestutils.GetReplicationURI`](https://github.com/cockroachdb/cockroach/blob/60138fed56560113b43d06439cc1588ba602b5a2/pkg/crosscluster/replicationtestutils/uri_util.go#L33). The helper would metamorphically switch between external connections and normal connections. You can then refactor many of the online restore + normal restore tests to use the helper, which would give us a lot of test coverage for the change.

Comment (jeffswenson) [inline pkg/backup/restore_online_test.go]: Does this test pass if you undo the change that maps external connections into their inner contents?

File: pkg/backup/restore_planning.go [hunk 3]
```diff
@@ -1802,8 +1803,14 @@ func doRestorePlan(
...
 	}
 	if restoreStmt.Options.OnlineImpl() {
-		for _, uri := range defaultURIs {
-			if err := cloud.SchemeSupportsEarlyBoot(uri); err != nil {
+		for _, path := range defaultURIs {
+			uri, err := url.Parse(path)
+			if err != nil {
+				return err
+			}
+			if uri.Scheme == "external" {
```
Comment (jeffswenson) [inline pkg/backup/restore_planning.go]: We need to handle the case where the external connection refers to an inner connection type that is not supported by early boot. E.g. we can use nodelocal in testing, but online restore does not support it in production.

File: pkg/backup/restore_job.go [hunk 4]
```diff
@@ -1899,6 +1902,40 @@ func (r *restoreResumer) doResume(ctx context.Context, execCtx interface{}) erro
 		return err
 	}
 
+	if details.OnlineImpl() {
+		// check for any exteral connections, and swap the uris
+		for i, path := range details.URIs {
```
Comment (jeffswenson) [inline pkg/backup/restore_job.go]: I suspect my other comments will make this one redundant, but I think most of this change should be extracted out of `doResume` and into something like `r.materializeExternalConnection()`. `doResume` is one of the first functions that folks read when understanding what a restore job is doing, so the code should focus on communicating the high level workflow of the restore.

**Review by jeffswenson — COMMENTED** [review]
Great work! This is much better than I would expect for your first week working on the code base.

File: pkg/cloud/externalconn/connection.go [hunk 5]
```diff
@@ -38,6 +39,46 @@ type ExternalConnection interface {
 	RedactedConnectionURI() string
 }
 
+// converts a potentially modified external connection uri to the underlying uri with those
```
Comment (jeffswenson) [inline pkg/cloud/externalconn/connection.go]: nit: the convention for doc comments in golang is to start with the name of the function. E.g. `// Materialize converts a potentially modified`.

https://go.dev/doc/comment#func

File: pkg/backup/restore_planning.go [hunk 6]
```diff
@@ -1686,6 +1688,33 @@ func doRestorePlan(
 
 	var fullyResolvedSubdir string
 
+	if restoreStmt.Options.OnlineImpl() {
+		// validate uris are allowed for online restore
+		for _, path := range from {
+			uri, err := url.Parse(path)
+			if err != nil {
+				return err
```
Comment (jeffswenson) [inline pkg/backup/restore_planning.go:1693]: nit: call errors.Wrap on this error. This is especially important for errors that come from the stdlib because we need to wrap the error to get a useful stack trace.

File: pkg/backup/restore_planning.go [hunk 7]
```diff
@@ -1686,6 +1688,33 @@ func doRestorePlan(
 
 	var fullyResolvedSubdir string
 
+	if restoreStmt.Options.OnlineImpl() {
```
Comment (jeffswenson) [inline pkg/backup/restore_planning.go:1689]: nit: doRestorePlan is a long function, so most of this logic should be extracted into a helper. Maybe something like `uriCompatibleWithOnlineRestore`. Then the change to doRestorePlan becomes:

```
if restoreStmt.Options.OnlineImpl() {
for _, path := range from {
   err := r.isCompatibleWithOnlineRestore(ctx, path, ...)
   if err != nil { return err }
}
}
```

File: pkg/backup/restore_online.go [hunk 8]
```diff
@@ -456,8 +459,35 @@ func sendRemoteAddSSTable(
...
+		return err
+	}
+	if uri.Scheme == externalconn.Scheme {
+		if err := execCtx.ExecCfg().InternalDB.Txn(ctx, func(ctx context.Context, t isql.Txn) error {
+			ec, err := externalconn.LoadExternalConnection(ctx, uri.Host, t)
+			if err != nil {
+				return err
+			}
+
+			materialized, err := externalconn.Materialize(ec, uri)
```
Comment (jeffswenson) [inline pkg/backup/restore_online.go]: While I'm not worried about materializing the string every time, I do think we need to avoid retrieving the externalconn from the database every time we send a link sst request. Loading the external connection requires an RPC to the external connection table. 

It looks like we can probably keep a hostname -> external connection cache to avoid the retrievals. The fact we need a cache suggests `sendRemoteAddSSTable` is probably too low level for the URI rewriting and this mapping should happen in sendAddRemoteSSTWorker or in generateAndSendImportSpans.

**Review by jeffswenson — COMMENTED** [review]
Looking good! A few more things to resolve before we can merge it.

File: pkg/backup/restore_online.go [hunk 9]
```diff
@@ -342,6 +349,40 @@ func sendAddRemoteSSTWorker(
...
+						}); err != nil {
+							return errors.Wrap(err, "failed to load external connection")
+						}
+					}
+
+					materialized, err := externalconn.Materialize(ec, uri)
+					if err != nil {
+						return errors.Wrap(err, "failed to materialize external connection URI")
+					}
+					// revalidate
```
Comment (jeffswenson) [inline pkg/backup/restore_online.go]: nit: we should describe why we need to revalidate in the comment. Is there a specific edge case you are worried about?

File: pkg/backup/restore_online.go [hunk 10]
```diff
@@ -1080,3 +1121,31 @@ func getNumOnlineRestoreLinkWorkers(ctx context.Context, execCtx sql.JobExecCont
...
 	return defaultLinkWorkersPerNode * numNodes, nil
 }
+
+// uriCompatibleWithOnlineRestore validates that a uri scheme is supported for early boot.
+// additionally, if an external connection uri is passed, the underlying uri the
+// external connection points to will be loaded from the system table and validated
+func uriCompatibleWithOnlineRestore(ctx context.Context, txn isql.Txn, path string) error {
+	uri, err := url.Parse(path)
+	if err != nil {
+		return errors.Wrap(err, "invalid URI")
```
Comment (jeffswenson) [inline pkg/backup/restore_online.go]: nit: when the error is formatted it turns into something like

invalid URI: <error from url.Parse>

It's probably better to use an error message like:
"failed to parse uri for restore: ..."

File: pkg/cloud/externalconn/connection.go [hunk 11]
```diff
@@ -38,6 +39,46 @@ type ExternalConnection interface {
...
+		}
+		connectionName := ec.ConnectionName()
+		if uri.Host != connectionName {
+			return nil, errors.Newf("input host %s does not match connection name %s", uri.Host, connectionName)
+		}
+	}
+
+	connDetails := ec.ConnectionProto()
+	switch d := connDetails.Details.(type) {
+	case *connectionpb.ConnectionDetails_SimpleURI:
```
Comment (jeffswenson) [inline pkg/cloud/externalconn/connection.go]: consider: I think this reads a little cleaner as an early exit

```
uri, ok := d.(*connectionpb.ConnectionDetails_SimpleURI)
if !ok { 
   return nil, errors.Newf("external connection is not a uri: %v")
}
...
```

File: pkg/backup/restore_online.go [hunk 12]
```diff
@@ -306,6 +309,10 @@ func sendAddRemoteSSTWorker(
 ) func(context.Context) error {
 	return func(ctx context.Context) error {
 		testingKnobs := execCtx.ExecCfg().BackupRestoreTestingKnobs
+
+		// small cache to avoid loading external connections from system table per file
```
Comment (jeffswenson) [inline pkg/backup/restore_online.go]: nit: I don't think we need this comment. Describing it as a cache already makes it obvious why it exists. I think comments should mostly be reserved for the case where you are describing some non-local property of the code. E.g. "we validate the external connection again because its possible the external connection was modified after the restore started".

or "we need to manifest external uris to avoid a runtime dependency loop between pebble and the sql layer"

**Review by jeffswenson — APPROVED** [review]
LGTM 🥳
