### PR TITLE
cloudimpl: fix short-read on EOF of compressed GCS file

### LINKED ISSUE #56152: Error Importing TSV file uploaded to GCS with -Z (gzip at rest) option set
**Describe the problem**
When importing TSV files from GCS that were stored using `gsutil cp -Z`, the files sometimes fail to load with errors indicating truncation `error parsing row 677999: expected 3 fields, got 2`

**To Reproduce**

I found this while working with randomly-produced data, so I've left it publicly available on GCS.

If possible, provide steps to reproduce the behavior:

1. I am running a cluster with 5 nodes in GCS using the recommended k8s config.
2. Create a new database and attach to it via an SQL shell.
3. Try to run the following import statement.

```
IMPORT TABLE PrimaryBranchParams (
  commit_id INT4 NOT NULL,
  key STRING NOT NULL,
  value STRING NOT NULL,
  PRIMARY KEY (commit_id, key, value)
) CSV DATA (
'gs://skia-gold-benchmark-data/schemaV1/params/params_1317938261346792849.tsv',
'gs://skia-gold-benchmark-data/schemaV1/params/params_3344400709634359273.tsv',
'gs://skia-gold-benchmark-data/schemaV1/params/params_3794156622884343106.tsv',
'gs://skia-gold-benchmark-data/schemaV1/params/params_3344400709634359273.tsv',
'gs://skia-gold-benchmark-data/schemaV1/params/params_4244378414963744339.tsv',
'gs://skia-gold-benchmark-data/schemaV1/params/params_4883954964158297154.tsv',
'gs://skia-gold-benchmark-data/schemaV1/params/params_5529620708038318579.tsv',
'gs://skia-gold-benchmark-data/schemaV1/params/params_6092797839052470063.tsv',
'gs://skia-gold-benchmark-data/schemaV1/params/params_6893293523575469822.tsv',
'gs://skia-gold-benchmark-data/schemaV1/params/params_772841964638661580.tsv'
)
 WITH delimiter = e'\t';
```
These files contain about 700k rows each (5.1 million unique rows total). These files were uploaded to GCS using the command
`gsutil -m cp -Z tsvfiles/* [bucket]`

4. I tried this several times and saw one of two errors fairly consistently: 
```
ERROR: gs://skia-gold-benchmark-data/schemaV1/params/params_4883954964158297154.tsv: error parsing row 677999: expected 3 fields, got 2 (row: "40999\topt_Wyomi")
ERROR: gs://skia-gold-benchmark-data/schemaV1/params/params_6092797839052470063.tsv: error parsing row 672986: expected 3 fields, got 2 (row: "40999\top")

```
**Expected behavior**
As above, if you run almost the same command, but with V2 (the same files, but not compressed using gzip at rest),

```
IMPORT TABLE PrimaryBranchParams (
  commit_id INT4 NOT NULL,
  key STRING NOT NULL,
  value STRING NOT NULL,
  PRIMARY KEY (commit_id, key, value)
) CSV DATA (
'gs://skia-gold-benchmark-data/schemaV2/params/params_1317938261346792849.tsv',
'gs://skia-gold-benchmark-data/schemaV2/params/params_3344400709634359273.tsv',
'gs://skia-gold-benchmark-data/schemaV2/params/params_3794156622884343106.tsv',
'gs://skia-gold-benchmark-data/schemaV2/params/params_3344400709634359273.tsv',
'gs://skia-gold-benchmark-data/schemaV2/params/params_4244378414963744339.tsv',
'gs://skia-gold-benchmark-data/schemaV2/params/params_4883954964158297154.tsv',
'gs://skia-gold-benchmark-data/schemaV2/params/params_5529620708038318579.tsv',
'gs://skia-gold-benchmark-data/schemaV2/params/params_6092797839052470063.tsv',
'gs://skia-gold-benchmark-data/schemaV2/params/params_6893293523575469822.tsv',
'gs://skia-gold-benchmark-data/schemaV2/params/params_772841964638661580.tsv'
)
 WITH delimiter = e'\t';
```
It will succeed in a bit under 30 seconds.
As mentioned above, these files were the same as the failing case, just uploaded without -Z
`gsutil -m cp  tsvfiles/* [bucket]`

**Environment:**
 - CockroachDB version 20.1.8 (also saw this on 20.1.4, but then updated to see if it was fixed)
 - Server OS: docker image cockroachdb/cockroach:v20.1.8 using y'alls kubernetes yaml files.
 - Client app `cockroach sql`

**Additional context**
What was the impact?

Will try gzipping the content explicitly before uploading to hopefully work around this.

### PR DESCRIPTION
**Pull request by dt**
Previously the helper for reading GCS files that handled resuming after
errors would return the amount read from Read() calls that did not
return an error, or would move to its retries for those that did return
an error.

However the io.Reader interface allows a Read call to return n > 0 *and*
a non-nil error, and expects the caller to handle the n read bytes before
the error, particularly if err = EOF, where the last Read() call might
read the last X bytes and then return (X, EOF).

This changes the resuming reader to return n and err from the underlying
reader as-is if err is nil or, after this change, if it is EOF. Other
errors are left as is -- they will cause it to return 0 regardless of
n -- a future change may wish to change these as well, however EOF is
a special case in that it is expected.

Interestingly the regular underlying reader does not do this -- it seems
that it returns (n, nil) and then (0, EOF) on the next call, so this bug
wasn't caught before. However a user observed that files stored using
the SDK's native compression functionality were read incorrectly, so
it seems like the decompressing implementation of the underlying reader
does utilize the (n>0, EOF) option in the interface specification. The
included test case thus exercises this change by comparing the content
of /usr/share/dict/words as stored on GCS with and without native gzip
compression enabled (gsutil's -Z option).

Release note (bug fix): Fix a bug that could cause IMPORT to incorrectly read files stored on Google Cloud if uploaded using its compression option (gsutil -Z).

Fixes #56152

### CODE REVIEW

File: pkg/storage/cloudimpl/cloudimpltests/gcs_storage_test.go [hunk 1]
```diff
@@ -161,3 +161,37 @@ func TestFileDoesNotExist(t *testing.T) {
...
 	}
 }
+
+func TestCompressedGCS(t *testing.T) {
+	defer leaktest.AfterTest(t)()
+	user := security.RootUserName()
+	ctx := context.Background()
+
+	// gsutil cp /usr/share/dict/words gs://cockroach-fixtures/words-compressed.txt
+	gsFile1 := "gs://cockroach-fixtures/words.txt?AUTH=implicit"
```
Comment (miretskiy) [inline pkg/storage/cloudimpl/cloudimpltests/gcs_storage_test.go:171]: do we need to skip this test if we're running w/out implicit authentication configured?

**Review by miretskiy — APPROVED** [review]

**Review by adityamaru — APPROVED** [review]

File: pkg/storage/cloudimpl/cloudimpltests/gcs_storage_test.go (hunk 1 above)
Comment (dt) [reply pkg/storage/cloudimpl/cloudimpltests/gcs_storage_test.go:171]: ugh, yes. Thanks!

**Comment by dt** [comment]
TFTRs!

bors r+
