### PR TITLE
sql: allow empty search path parameters

### LINKED ISSUE #117316: sql: incorrect edge case setting search_path
**Describe the problem**

Setting the `search_path` config to empty results in an error, which is incorrect.

**To Reproduce**

On 23.1 or 23.2:

```
SELECT pg_catalog.set_config('search_path', '', false);
ERROR: set_config(): invalid value for parameter "search_path": ""
SQLSTATE: 22P02
```

**Expected behavior**

This succeeds on 22.2, and on postgres. CRDB should be able to set an empty `search_path`.

**Additional data / screenshots**

In 23.1, we introduced more sophisticated parsing for `search_path` parameters. I think that we incorrectly return an error when there is an empty string for the `search_path` parameter here: https://github.com/cockroachdb/cockroach/blob/8d065df26e25a762a1abbbf2b1e475456b341a00/pkg/sql/sessiondata/parse_search_path.go#L147

**Environment:**
 - CockroachDB version 23.1, 23.2

**Additional context**
This affects customers running on 23.1, so a solution should be backported.

Jira issue: CRDB-35120

### PR DESCRIPTION
**Pull request by rharding6373**
Before this change, when parsing search path parameters as part of setting the search path, CRDB would return an error if the parameter was empty. This PR fixes that edge case to succeed, as in postgres. This bug has been present since 23.1

Epic: None
Fixes: #117316

Release note (bug fix): Trying to set an empty search_path no longer results in an error.

### CODE REVIEW

**Review by rafiss — CHANGES_REQUESTED** [review]
thanks for the fix!

i think this problem was specific to `set_config`, so could we also add a logic test in this area: https://github.com/cockroachdb/cockroach/blob/d040e0f6cff23bfd45c733551a75e5175377b5ce/pkg/sql/logictest/testdata/logic_test/pg_builtins#L366

also, it would be good to check how the following behaves:
```
SELECT pg_catalog.set_config('search_path', '', false);
SHOW search_path;
SET search_path = '';
SHOW search_path;
```

**Review by rharding6373 — COMMENTED** [review]
Thanks for the suggestions! Added a logic test as well.

With this change, the behavior is the same as postgres:

postgres:
```
rharding=# SELECT pg_catalog.set_config('search_path', '', false);

 set_config 

------------

(1 row)

rharding=# SHOW search_path;

 search_path 

-------------

(1 row)

rharding=# SET search_path = '';

SET

rharding=# SHOW search_path;

 search_path 

-------------

 ""

(1 row)
```

CRDB:
```
defaultdb> SELECT pg\_catalog.set_config('search_path', '', false);    

                             -> SHOW search_path;                                          

                             -> SET search_path = '';                                      

                             -> SHOW search_path;                                          

  set_config

--------------

(1 row)

Time: 1ms total (execution 0ms / network 0ms)

  search_path

---------------

(1 row)

Time: 0ms total (execution 0ms / network 0ms)

SET

Time: 0ms total (execution 0ms / network 0ms)

  search_path

---------------
  ""

(1 row)

Time: 0ms total (execution 0ms / network 0ms)
```

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/117318#-:-NnKD8Gp0vVrIHaNmU3g:b9w8tx3)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained

**Review by rafiss — APPROVED** [review]
lgtm! i think the `TestParseSearchPathInConnectionString/empty_search_path_is_not_allowed` test case just needs an adjustment

**Review by rharding6373 — COMMENTED** [review]
TFTR!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/117318#-:-NnKxjym5TUo8hykydjG:b-814g8k)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained

File: pkg/sql/pgwire/conn_test.go [hunk 1]
```diff
@@ -1701,9 +1701,9 @@ func TestParseSearchPathInConnectionString(t *testing.T) {
 			expectedErr: `option "Ghi" is invalid`,
 		},
 		{
-			desc:        "empty search_path is not allowed",
-			query:       `options=-c search_path=`,
-			expectedErr: `invalid value for parameter "search_path": ""`,
+			desc:               "empty search_path is not allowed",
```
Comment (rafiss) [inline pkg/sql/pgwire/conn_test.go:1704]: nit: the description should be adjusted since this is allowed now.

**Review by rafiss — COMMENTED** [review]
just had one more nit

**Review by rharding6373 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/117318)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @rafiss)

___
*[`pkg/sql/pgwire/conn_test.go` line 1704 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/117318#gh-1442211120:-NnLAsDn7D8IKP5By0h9:b-x6rc57) ([raw file](https://github.com/cockroachdb/cockroach/blob/c6f7ce760236f151b7a152c988fbd425aa0ee3f0/pkg/sql/pgwire/conn_test.go#L1704)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

nit: the description should be adjusted since this is allowed now.
</blockquote></details>

Forgot to edit this. Thanks for catching!

**Comment by rharding6373** [comment]
TFTRs!

bors r+
