### PR TITLE
sql: Simplify expected message requirement in TestAnonymizeStatementsForReporting

### LINKED ISSUE #72284: sql: the test TestAnonymizeStatementsForReporting is overly prescriptive
Forked from #72227 (initially reported by @amitsadaphule )

**Describe the problem**

The expected output in the test `TestAnonymizeStatementsForReporting` (conn_executor_test.go) is overly prescriptive as to the result of formatting an error containing a redacted statement.

Namely, it has particular requirements about how the stack trace is formatted.

This is unnecessary for the test, which merely needs to assert that the statement is partially redacted. The test should simply assert on the beginning of the error string with `strings.HasPrefix`.

**To Reproduce**

Run `TestAnonymizeStatementsForReporting` on a non-amd64 platform.

**Expected behavior**

The test passes regardless of platform, and regardless of the particular rendering of stack traces by the errors library.

Jira issue: CRDB-11080

### PR DESCRIPTION
**Pull request by changhanlee**
fixes #72284
See commit message.

Release justification: Low impact, simplify expected message in assertion

### CODE REVIEW

File: pkg/sql/conn_executor_test.go [hunk 1]
```diff
@@ -91,32 +91,20 @@ INSERT INTO sensitive(super, sensible) VALUES('that', 'nobody', 'must', 'see')
...
-Error types: (1) *safedetails.withSafeDetails (2) *withstack.withStack (3) *errutil.leafError`
+	const expSafeRedactedMsgPrefix = `some error
+(1) while executing: INSERT INTO _(_, _) VALUES ('_', '_', __more2__)`
 
 	// Edit non-determinstic stack trace filenames from the message.
-	actSafeRedactedMessage := strings.ReplaceAll(strings.ReplaceAll(fileref.ReplaceAllString(
-		redact.Sprintf("%+v", safeErr).Redact().StripMarkers(), "...$2:NN"),
-		"asm_arm64", "asm_scrubbed"),
-		"asm_amd64", "asm_scrubbed")
+	actSafeRedactedMessage := fileref.ReplaceAllString(
```
Comment (rafiss) [inline pkg/sql/conn_executor_test.go:98]: is this still necessary now that we only look at the prefix

**Review by rafiss — COMMENTED** [review]
thanks for your contribution! i had a quick question

File: pkg/sql/conn_executor_test.go (hunk 1 above)
Comment (changhanlee) [reply pkg/sql/conn_executor_test.go]: The regexp replacement is unnecessary indeed. 
The chain `.Redact().StripMarkers()` also seems unnecessary because sql.WithAnonymizedStatement already seems to have safely redacted and stripped.

**Comment by changhanlee** [comment]
@rafiss TFYR I made changes in response to your question.

**Review by rafiss — APPROVED** [review]
thank you! this looks good. the CI failed because of a flaky test, so merging

bors r+
