### PR TITLE
backupccl: prevent restore schema_only from inserting stats

### LINKED ISSUE #87221: Check output data from `schema_only` & `verify_backup_table_data` restores
**Describe the problem**

Noticed some differences in the `estimated_row_count` of tables in a restored database between `schema_only` restores and `verify_backup_table_data` restores. There are possibly some other ux nuances here around the respective output that we could check.

**To Reproduce**

1. Create a full database backup to s3 storage. 
2. Dropped the database from the cluster.
3. Ran the following:
`RESTORE DATABASE movr FROM LATEST IN "s3://my-bucket" WITH schema_only;`
Received the following output, after the restore ran successfully:
```
        job_id       |  status   | fraction_completed | rows | index_entries | bytes
---------------------+-----------+--------------------+------+---------------+--------
  792659534950957057 | succeeded |                  1 |    0 |             0 |     0
(1 row)
```
This seems expected, no rows were restore since this was `schema_only`. 
4. Ran a show tables statement in the movr database, and received:
```
  schema_name |         table_name         | type  | owner | estimated_row_count | locality
--------------+----------------------------+-------+-------+---------------------+-----------
  public      | promo_codes                | table | root  |                1014 | NULL
  public      | rides                      | table | root  |                 631 | NULL
  public      | user_promo_codes           | table | root  |                  43 | NULL
  public      | users                      | table | root  |                 161 | NULL
  public      | vehicle_location_histories | table | root  |                4368 | NULL
  public      | vehicles                   | table | root  |                  48 | NULL
(6 rows)
```
Seeing the `estimated_row_count` with data was a little unexpected, but assumed this was read from the schema, maybe?
5. Dropped the database that the schema only restore had restored.
6. Then, I ran `RESTORE DATABASE movr FROM LATEST IN "s3://my-bucket" WITH schema_only, verify_backup_table_data; `
Received the following output, after the restore ran successfully:
```
        job_id       |  status   | fraction_completed | rows  | index_entries | bytes
---------------------+-----------+--------------------+-------+---------------+--------
  792661355235278849 | succeeded |                  1 | 14169 |          1978 |     0
(1 row)
```
This time rows were present in this output, which makes sense (I think) since this restore type is reading the SSTs.
7. Ran a show tables statement in the movr database, and received:
```
  schema_name |         table_name         | type  | owner | estimated_row_count | locality
--------------+----------------------------+-------+-------+---------------------+-----------
  public      | promo_codes                | table | root  |                   0 | NULL
  public      | rides                      | table | root  |                   0 | NULL
  public      | user_promo_codes           | table | root  |                   0 | NULL
  public      | users                      | table | root  |                   0 | NULL
  public      | vehicle_location_histories | table | root  |                   0 | NULL
  public      | vehicles                   | table | root  |                   0 | NULL
(6 rows)
```
The empty `estimated_row_count` here was **unexpected** for this restore type. Given the initial output had a row count and that the `schema_only` restore type returned and `estimated_row_count`, this seems to be missing here? 

**Expected behavior**
Consistency in the output between the two restore types, so there is a clear how the user can interpret this output. Perhaps `estimated_row_count` is meant to be present in both restore types. If so, should `rows` also be in the initial output after a `schema_only` restore?

**Environment:**
 - CockroachDB version v22.2.0-alpha.1
- roachprod cluster

Jira issue: CRDB-19219

### PR DESCRIPTION
**Pull request by msbutler**
This small patch prevents restore with schema_only from writing the backup stats from the backup manifest, leading to temporary misleading estimated row counts on restored tables.

This patch also cleans up some testing infrastucture on the restore verify-table-data tests that was necessary to prevent spurious panics before https://github.com/cockroachdb/pebble/pull/1921 landed.

Fixes #87221

### CODE REVIEW

File: pkg/ccl/backupccl/restore_job.go [hunk 1]
```diff
@@ -1586,8 +1586,11 @@ func (r *restoreResumer) doResume(ctx context.Context, execCtx interface{}) erro
 		resTotal.Add(res)
 	}
 
-	if err := insertStats(ctx, r.job, p.ExecCfg(), remappedStats); err != nil {
-		return errors.Wrap(err, "inserting table statistics")
+	if !details.SchemaOnly {
+		// Only insert table stats from the backup manifest if actual data was restored
```
Comment (adityamaru) [inline pkg/ccl/backupccl/restore_job.go:1590]: nit: period at the end of the comment

**Review by adityamaru — APPROVED** [review]
Can you add a quick test that verifies we don't write table stats, should just be a query on a system table?

**Comment by msbutler** [comment]
Done!

File: pkg/ccl/backupccl/restore_job.go (hunk 1 above)
Comment (msbutler) [reply pkg/ccl/backupccl/restore_job.go]: Done.

**Comment by msbutler** [comment]
TFTR!

bors r=adityamaru
