### PR TITLE
bazel: make `go test` process timeout before bazel kills it

### LINKED ISSUE #78185: logictest: improve observability of TeamCity timeouts
It's possible for logic tests to run longer than the time allotted for them in TC, in which case TC abruptly kills the tests and prints a timeout message to the log:

```
-- Test timed out at 2022-03-17 20:31:33 UTC --
```

[Example Log](https://gist.github.com/mgartner/06f8ffab9a9db03b06c424a46e16efd6)

From the logs, it's unclear which test(s) were running when the timeout occurred. We should ensure that `go test` timeouts first, so we get an informative stack trace that will help track down the issue.

Jira issue: CRDB-14009
Epic CRDB-8349

### PR DESCRIPTION
**Pull request by healthy-pod**
Previously, bazel will kill the test process if it goes
beyond the timeout duration set for its size. This prevented
us from knowing which tests timed out and also prevented us
from getting their stack traces.

This patch causes the `go test` process to timeout before
bazel kills it to allow us to know which test timed out and
get its stack trace.

Closes #78185

Release justification: Non-production code changes
Release note: None

### CODE REVIEW

File: pkg/cmd/generate-test-timeouts/main.go [hunk 1]
```diff
@@ -0,0 +1,87 @@
...
+import (
+	"fmt"
+	"log"
+	"os"
+	"os/exec"
+	"regexp"
+	"strings"
+
+	"github.com/alessio/shellescape"
+	"github.com/cockroachdb/errors"
```
Comment (rickystewart) [inline pkg/cmd/generate-test-timeouts/main.go:22]: Can you use the standard library `errors` instead of `cockroachdb/errors`? `cockroachdb/errors` is a pretty heavy dependency, we don't necessarily want to force people to build it.

File: build/bazelutil/bazel-generate.sh [hunk 2]
```diff
@@ -76,10 +76,13 @@ else
...
+
 if files_unchanged_from_upstream $(find_relevant ./pkg/cmd/generate-test-suites -name BUILD.bazel -or -name '*.go') $(find_relevant ./pkg -name BUILD.bazel) $(find_relevant ./pkg -name '*.bzl'); then
   echo "Skipping //pkg/cmd/generate-test-suites (relevant files are unchanged from upstream)."
 else
-  bazel build @com_github_bazelbuild_buildtools//buildozer:buildozer
   CONTENTS=$(bazel run //pkg/cmd/generate-test-suites --run_under="cd $PWD && ")
   echo "$CONTENTS" > pkg/BUILD.bazel
 fi
+
+bazel run //pkg/cmd/generate-test-timeouts --run_under="cd $PWD && "
```
Comment (rickystewart) [inline build/bazelutil/bazel-generate.sh:88]: You can put this in the branch above next to `generate-test-suites`, or in a new branch that checks `BUILD.bazel` files and `*.bzl` files. If none of the `BUILD.bazel` or `*.bzl` files have changed from `master` then `generate-test-timeouts` doesn't need to be run. 

Also we don't want to unconditionally build `buildozer`. Building small `go` executables is a non-negligible amount of latency, we don't want to force people to do this for no reason.

This is optional, but consider just merging what you currently have in `generate-test-timeouts` into `generate-test-suites`. `generate-test-suites` already depends on `buildozer` and does similar munging in the `BUILD.bazel` files, so the logic may just fit right in there.

File: pkg/cmd/generate-test-timeouts/main.go [hunk 3]
```diff
@@ -0,0 +1,87 @@
...
+}
+
+func main() {
+	testSizeToDefaultTimeout := map[string]int{
+		"small":    60,
+		"medium":   300,
+		"large":    900,
+		"enormous": 3600,
+	}
+	for _, size := range []string{"small", "medium", "large", "enormous"} {
```
Comment (rickystewart) [inline pkg/cmd/generate-test-timeouts/main.go:72]: `for size, timeout := range testSizeToDefaultTimeout`

**Review by rickystewart — CHANGES_REQUESTED** [review]

File: build/bazelutil/bazel-generate.sh (hunk 2 above)
Comment (healthy-pod) [reply build/bazelutil/bazel-generate.sh:88]: > This is optional, but consider just merging what you currently have in generate-test-timeouts into generate-test-suites. generate-test-suites already depends on buildozer and does similar munging in the BUILD.bazel files, so the logic may just fit right in there.

Right I adopted part of the code from `generate-test-suites` but I thought it might be better to separate them because `generate-test-suite` outputs something to stdout which is then forwarded to `pkg/BUILD.bazel`. Maybe I should make it write its output to `pkg/BUILD.bazel` directly (ie in the binary, instead of forwarding stdout to `pkg/BUILD.bazel`)? Then move the timeout code to the same package and rename it to `generate-test-suites-and-timeouts`?

Comment (rickystewart) [reply build/bazelutil/bazel-generate.sh:88]: > Maybe I should make it write its output to pkg/BUILD.bazel directly (ie in the binary, instead of forwarding stdout to pkg/BUILD.bazel)? Then move the timeout code to the same package and rename it to generate-test-suites-and-timeouts?

This approach makes sense to me. For the new name `generate-test-suites-and-timeouts` is not ideal since the binary actually does a few different things at this point. Maybe `generate-bazel-extra` or something like that?

Comment (healthy-pod) [reply build/bazelutil/bazel-generate.sh:88]: Should we generate timeouts when `*.bzl` files change? I can't find a reason to do that but I don't know enough about everything we are doing `.bzl` files and I am wondering because we do update `pkg/BUILD.bazel` when a `*.bzl` file changes. My current understanding is that with timeouts we are only concerned about the test target size so if `BUILD.bazel` files didn't change and our binary `pkg/cmd/generate-bazel-extra` didn't change then we are good?

Comment (rickystewart) [reply build/bazelutil/bazel-generate.sh:88]: Hmm. I'm not aware of any timeouts that would need to be updated when `.bzl` files change. But I think you do need to run `generate-test-suites` (especially the generation of `pkg/BUILD.bazel`) if `.bzl` files change.

Comment (healthy-pod) [reply build/bazelutil/bazel-generate.sh:88]: Right but I am thinking of doing this:

```
if ! (files_unchanged_from_upstream $(find_relevant ./pkg -name BUILD.bazel) $(find_relevant ./pkg/cmd/generate-bazel-extra -name BUILD.bazel -or -name '*.go')); then
  bazel build @com_github_bazelbuild_buildtools//buildozer:buildozer
  bazel run //pkg/cmd/generate-bazel-extra --run_under="cd $PWD && " -- -gen_test_suites -gen_tests_timeouts
elif files_unchanged_from_upstream $(find_relevant ./pkg -name '*.bzl'); then
  echo "Skipping //pkg/cmd/generate-bazel-extra (relevant files are unchanged from upstream)."
else
  echo "Skipping `generate tests timeouts` from //pkg/cmd/generate-bazel-extra (relevant files are unchanged from upstream)."
  bazel build @com_github_bazelbuild_buildtools//buildozer:buildozer
  bazel run //pkg/cmd/generate-bazel-extra --run_under="cd $PWD && " -- -gen_test_suites
```

so we can skip generating timeouts when we don't need to

Comment (rickystewart) [reply build/bazelutil/bazel-generate.sh:88]: Seems sensible to me.

**Comment by healthy-pod** [comment]
So this is ready for a second pass now other than GitHub CI failing. I tried to figure out what is wrong and it looks like it fails [here](https://teamcity.cockroachdb.com/viewLog.html?buildTypeId=Cockroach_UnitTests_CheckGeneratedCode&buildId=6150341&tab=buildLog&logTab=tree&filter=debug&expand=all&_focus=1040) but I wasn't able to understand how it ended in this state. Can you take a look at it when you review?

File: pkg/cmd/generate-bazel-extra/main.go [hunk 4]
```diff
@@ -38,7 +41,32 @@ func runBuildozer(args []string) {
 	}
 }
 
-func main() {
+func getTestTargets(testTargetSize string) ([]string, error) {
+	match, _ := regexp.MatchString("\\b(?:small|medium|large|enormous)\\b", testTargetSize)
```
Comment (rickystewart) [inline pkg/cmd/generate-bazel-extra/main.go:45]: Nit: Using `regexp` for this is pretty odd. I'd say factor out `testSizeToDefaultTimeout` so it is a *global* variable, and then you can do

```
if _, ok := testSizeToDefaultTimeout[testTargetSize]; !ok {
    ....
}
```

**Review by rickystewart — APPROVED** [review]
For the GitHub CI failure, that's pretty odd. I'm not seeing anything in your change that would cause the failure. Maybe try rebasing and re-running CI to see if it was intermittent?

**Comment by renatolabs** [comment]
> Closes https://github.com/cockroachdb/cockroach/issues/78185

Should this PR close that issue?

This is helping us debug bazel timeouts (which is great), but TC timeouts would still produce no stack trace. Or am I missing something?

**Comment by rickystewart** [comment]
> This is helping us debug bazel timeouts (which is great), but TC timeouts would still produce no stack trace. Or am I missing something?

Assuming TC timeouts are configured to be longer than the underlying `bazel test` timeout, there's no problem, right?

**Comment by renatolabs** [comment]
> Assuming TC timeouts are configured to be longer than the underlying bazel test timeout, there's no problem, right?

This is true; I think the issue may be that we need to update our TC timeout then. Every couple of days I see a build that times out running go tests (e.g., https://teamcity.cockroachdb.com/viewLog.html?buildId=6144348&tab=buildResultsDiv&buildTypeId=Cockroach_UnitTests_BazelUnitTests)

**Comment by rickystewart** [comment]
> > Assuming TC timeouts are configured to be longer than the underlying bazel test timeout, there's no problem, right?
> 
> This is true; I think the issue may be that we need to update our TC timeout then. Every couple of days I see a build that times out running go tests (e.g., [teamcity.cockroachdb.com/viewLog.html?buildId=6144348&tab=buildResultsDiv&buildTypeId=Cockroach_UnitTests_BazelUnitTests](https://teamcity.cockroachdb.com/viewLog.html?buildId=6144348&tab=buildResultsDiv&buildTypeId=Cockroach_UnitTests_BazelUnitTests))

Hmm, that is a pretty odd case. 2 hours is very long for the unit test job, I'm not sure why it would have stalled to such an extent.

We can look at bumping the timeout for this job, but also note I'll be increasing the size of our TeamCity agents to make these jobs faster.

**Comment by renatolabs** [comment]
> Hmm, that is a pretty odd case.

While it is odd, it's happening somewhat frequently. Here are two more cases that came to my attention just this month (that I could remember off the top of my head, it's likely there were more):

* https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_UnitTests_Test/5952358?buildTab=log&focusLine=3&linesState=309#%2FlogTestLogic_create_as3401903714
* https://teamcity.cockroachdb.com/viewLog.html?buildId=6032781&buildTypeId=Cockroach_UnitTests_Test&tab=buildLog&branch_Cockroach_UnitTests=%3Cdefault%3E

> I'll be increasing the size of our TeamCity agents to make these jobs faster.

Makes sense, hopefully that will drastically reduce these failures 👍

**Comment by rickystewart** [comment]
@sjbarag Ahmad is consistently seeing this failure to build the web UI tests in GitHub CI (NOT Bazel CI). Is this error meaningful at all to you? We are pretty perplexed because this PR doesn't touch any UI or non-Bazel stuff *at all*.

```
make: Entering directory '/go/src/github.com/cockroachdb/cockroach/pkg/ui'
[02:27:01 ]  make[1]: Entering directory '/go/src/github.com/cockroachdb/cockroach'
[02:27:01 ]  [WARNING] Makefile is deprecated and will be removed shortly.
[02:27:01 ] Running make with -j16
[02:27:01 ]  GOPATH set to /go
[02:27:01 ]  Warning: 'bazel' not found (`brew install bazelisk` for macs)
[02:27:01 ]  build/node-run.sh -C pkg/ui/workspaces/eslint-plugin-crdb yarn build
[02:27:01 ]  build/node-run.sh -C pkg/ui/workspaces/cluster-ui yarn build
[02:27:02 ]  yarn run v1.22.19
[02:27:02 ]  yarn run v1.22.19
[02:27:02 ]    $ tsc
[02:27:02 ]  $ npm-run-all -p build:typescript build:bundle
[02:27:02 ]   /bin/sh: 1: tsc: not found
[02:27:02 ]  error Command failed with exit code 127.
[02:27:02 ] info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
[02:27:02 ]  make[1]: *** [Makefile:364: pkg/ui/workspaces/eslint-plugin-crdb/dist/index.js] Error 127
[02:27:02 ]  make[1]: *** Waiting for unfinished jobs....
```

**Comment by sjbarag** [comment]
> @sjbarag Ahmad is consistently seeing this failure to build the web UI tests in GitHub CI (NOT Bazel CI). Is this error meaningful at all to you? We are pretty perplexed because this PR doesn't touch any UI or non-Bazel stuff _at all_.
> 
> ```
> make: Entering directory '/go/src/github.com/cockroachdb/cockroach/pkg/ui'
> [02:27:01 ]  make[1]: Entering directory '/go/src/github.com/cockroachdb/cockroach'
> [02:27:01 ]  [WARNING] Makefile is deprecated and will be removed shortly.
> [02:27:01 ] Running make with -j16
> [02:27:01 ]  GOPATH set to /go
> [02:27:01 ]  Warning: 'bazel' not found (`brew install bazelisk` for macs)
> [02:27:01 ]  build/node-run.sh -C pkg/ui/workspaces/eslint-plugin-crdb yarn build
> [02:27:01 ]  build/node-run.sh -C pkg/ui/workspaces/cluster-ui yarn build
> [02:27:02 ]  yarn run v1.22.19
> [02:27:02 ]  yarn run v1.22.19
> [02:27:02 ]    $ tsc
> [02:27:02 ]  $ npm-run-all -p build:typescript build:bundle
> [02:27:02 ]   /bin/sh: 1: tsc: not found
> [02:27:02 ]  error Command failed with exit code 127.
> [02:27:02 ] info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
> [02:27:02 ]  make[1]: *** [Makefile:364: pkg/ui/workspaces/eslint-plugin-crdb/dist/index.js] Error 127
> [02:27:02 ]  make[1]: *** Waiting for unfinished jobs....
> ```

There's basically no reason for `tsc` to not be found — `yarn run` adds the `node_modules/.bin/` directory to the `$PATH` before executing the script in `package.json`, and that's where `tsc` is supposed to be.  Interestingly, the most recent commit seems to have passed the "Github CI" job, and is only fialing on some Go tests: https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_BazelEssentialCi/6244028?buildTab=dependencies&mode=list

Perhaps this was a fluke?

**Comment by healthy-pod** [comment]
Wait I am confused, why does `bors` say "Build succeeded" and GitHub CI branch is `staging`? I am pretty sure I didn't `bors` this code change 🤔

**Comment by healthy-pod** [comment]
@sjbarag GitHub CI failure is back now when I rebuilt. Pretty sure the previous run was unrelated to this PR. Might have been incorrectly linked after the Teamcity disaster.

**Comment by sjbarag** [comment]
This is probably a weird side-effect `make ui-maintainer-clean` not removing `pkg/ui/workspaces/{e2e-tests,eslint-plugin-crdb}/node_modules` between TC jobs.  Filing a PR now.

**Comment by sjbarag** [comment]
https://github.com/cockroachdb/cockroach/pull/87135 should take care of it, but in the meantime I'm going to try rerunning your job with a clean state.

**Comment by healthy-pod** [comment]
@sjbarag just pointing that it's still failing if you have any other thoughts

**Comment by healthy-pod** [comment]
> @healthy-pod thanks for your work on this!
> 
> When I'm running logic tests locally through `dev`, the generation of the logic tests removes the test timeout arg:
> 
> ```
> diff --git a/pkg/ccl/logictestccl/tests/3node-tenant/BUILD.bazel b/pkg/ccl/logictestccl/tests/3node-tenant/BUILD.bazel
> index 9297caca81..e79fb00dd8 100644
> --- a/pkg/ccl/logictestccl/tests/3node-tenant/BUILD.bazel
> +++ b/pkg/ccl/logictestccl/tests/3node-tenant/BUILD.bazel
> @@ -5,7 +5,6 @@ go_test(
>      name = "3node-tenant_test",
>      size = "enormous",
>      srcs = ["generated_test.go"],
> -    args = ["-test.timeout=3595s"],
>      data = [
>          "//c-deps:libgeos",  # keep
>          "//pkg/ccl/logictestccl:testdata",  # keep
> ...
> ```

Thanks for catching this, it could have been easily missed until a test times out without a stack trace in teamcity. It should be fixed by #87299

File: pkg/kv/kvserver/BUILD.bazel [hunk 5]
```diff
@@ -319,6 +319,7 @@ go_test(
         "txn_recovery_integration_test.go",
         "txn_wait_queue_test.go",
     ],
+    args = ["-test.timeout=3595s"],
```
Comment (srosenberg) [inline pkg/kv/kvserver/BUILD.bazel:322]: @healthy-pod I am curious how these timeout values were derived?

Comment (healthy-pod) [reply pkg/kv/kvserver/BUILD.bazel:322]: [Bazel sets the test timeout based on the test size](https://bazel.build/reference/test-encyclopedia#role-test-runner). If the test size is not explicitly set then it will be `medium`. The default mappings are:
```
small: 60s timeout
medium: 300s timeout
large: 900s timeout
enormous: 3600s timeout
```

We let the `go test` process timeout 5 seconds before bazel kills it and that's how the quoted `3595s` (enormous) was derived.
