### PR TITLE
pgwire: ignore all messages after extended protocol error

### LINKED ISSUE #103936: pgwire: should not send ReadyForQuery if there's a simple query in extended protocol error state
**Describe the problem**

In https://github.com/elixir-ecto/ecto_sql/issues/473#issuecomment-1562068139 it was found that CRDB differs from the PostgreSQL wire protocol implementation. If a transaction enters into the aborted state while in the extended protocol, then all further messages should be ignored until the client sends a Sync message.

CockroachDB does ignore a simple query while in this state, but it incorrectly sends back a ReadyForQuery message to the client. This confuses some drivers.

See https://www.postgresql.org/docs/current/protocol-flow.html

**To Reproduce**

This pgwire test reproduces the problem
```
send
Query {"String": "DROP TABLE IF EXISTS t;"}
Query {"String": "CREATE TABLE t (i INT PRIMARY KEY, j INT UNIQUE);"}
Query {"String": "BEGIN"}
----

until ignore=NoticeResponse
ReadyForQuery
ReadyForQuery
ReadyForQuery
----
{"Type":"CommandComplete","CommandTag":"DROP TABLE"}
{"Type":"ReadyForQuery","TxStatus":"I"}
{"Type":"CommandComplete","CommandTag":"CREATE TABLE"}
{"Type":"ReadyForQuery","TxStatus":"I"}
{"Type":"CommandComplete","CommandTag":"BEGIN"}
{"Type":"ReadyForQuery","TxStatus":"T"}


send
Query {"String": "SAVEPOINT s"}
Parse {"Name": "s1", "Query": "INSERT INTO t VALUES ($1, $2)"}
Bind {"PreparedStatement": "s1", "Parameters": [{"text": "1"}, {"text": "2"}]}
Execute
Query {"String": "RELEASE SAVEPOINT s"}
----

until
ReadyForQuery
ReadyForQuery
----
{"Type":"CommandComplete","CommandTag":"SAVEPOINT"}
{"Type":"ReadyForQuery","TxStatus":"T"}
{"Type":"ParseComplete"}
{"Type":"BindComplete"}
{"Type":"CommandComplete","CommandTag":"INSERT 0 1"}
{"Type":"CommandComplete","CommandTag":"RELEASE"}
{"Type":"ReadyForQuery","TxStatus":"T"}

send
Query {"String": "SAVEPOINT s"}
Bind {"PreparedStatement": "s1", "Parameters": [{"text": "2"}, {"text": "2"}]}
Execute
Query {"String": "RELEASE SAVEPOINT s"}
----

# The RELEASE SAVEPOINT command should be ignored and should not return ReadyForQuery.
until
ReadyForQuery
ErrorResponse
----
{"Type":"CommandComplete","CommandTag":"SAVEPOINT"}
{"Type":"ReadyForQuery","TxStatus":"T"}
{"Type":"BindComplete"}
{"Type":"ErrorResponse","Code":"23505","ConstraintName":"t_j_key"}

send
Sync
Query {"String": "ROLLBACK TO SAVEPOINT s; RELEASE SAVEPOINT s"}
Query {"String": "ROLLBACK"}
----

until
ReadyForQuery
ReadyForQuery
ReadyForQuery
----
{"Type":"ReadyForQuery","TxStatus":"E"}
{"Type":"CommandComplete","CommandTag":"ROLLBACK"}
{"Type":"CommandComplete","CommandTag":"RELEASE"}
{"Type":"ReadyForQuery","TxStatus":"T"}
{"Type":"CommandComplete","CommandTag":"ROLLBACK"}
{"Type":"ReadyForQuery","TxStatus":"I"}
```

**Expected behavior**
The test should pass. (It can be added to **pkg/sql/pgwire/testdata/pgtest/aborted_txn**.)

Jira issue: CRDB-28264

Epic CRDB-27601

### PR DESCRIPTION
**Pull request by rafiss**
fixes https://github.com/cockroachdb/cockroach/issues/103936

The protocol says:
> When an error is detected while processing any extended-query message,
> the backend issues ErrorResponse, then reads and discards messages until
> a Sync is reached, then issues ReadyForQuery and returns to normal message
> processing.

But we were implementing this incorrectly, since we should also ignore the implicit Sync that we create after processing a simple query.

Release note (bug fix): Fixed a pgwire protocol bug where CockroachDB would not ignore the messages that it should if there was an error while in the pgwire extended protocol.

### CODE REVIEW

File: pkg/sql/conn_executor.go [hunk 1]
```diff
@@ -2289,15 +2291,18 @@ func (ex *connExecutor) execCmd() (retErr error) {
 		}
 
 	case PrepareStmt:
+		isExtendedProtocolCmd = true
```
Comment (knz) [inline pkg/sql/conn_executor.go:2294]: My recommendation would be to add the assignment to every `case` (assign false as needed) so that if any gets copy-paste d in the future the person is forced to think about whether to set this.

An alternative is to make a map type -> bool and assert in a test or init method that all the types have a decision taken about whether they are extended protocol or not.

File: pkg/sql/conn_io.go [hunk 2]
```diff
@@ -590,8 +600,12 @@ func (buf *StmtBuf) seekToNextBatch() error {
 				return err
 			}
 
-			if _, ok := buf.mu.data.Get(cmdIdx).(Sync); ok {
-				foundSync = true
+			if syncCmd, ok := buf.mu.data.Get(cmdIdx).(Sync); ok {
+				if requireClientSync && syncCmd.CameFromClient {
```
Comment (knz) [inline pkg/sql/conn_io.go:604]: I'm confused about this if...else.

Could you add comments to explain, and possibly give an explanatory name to the intermediate boolean values?

File: pkg/sql/pgwire/conn.go [hunk 3]
```diff
@@ -518,7 +518,7 @@ func (c *conn) serveImpl(
 				); err != nil {
 					return false, isSimpleQuery, err
 				}
-				return false, isSimpleQuery, c.stmtBuf.Push(ctx, sql.Sync{})
+				return false, isSimpleQuery, c.stmtBuf.Push(ctx, sql.Sync{CameFromClient: false})
```
Comment (knz) [inline pkg/sql/pgwire/conn.go:521]: Isn't the field dependent on the value of `isSimpleQuery` here?

File: pkg/sql/pgwire/conn.go [hunk 4]
```diff
@@ -555,8 +555,7 @@ func (c *conn) serveImpl(
 				// protocol and encounters an error, everything until the next sync
 				// message has to be skipped. See:
 				// https://www.postgresql.org/docs/current/10/protocol-flow.html#PROTOCOL-FLOW-EXT-QUERY
-
-				return false, isSimpleQuery, c.stmtBuf.Push(ctx, sql.Sync{})
+				return false, isSimpleQuery, c.stmtBuf.Push(ctx, sql.Sync{CameFromClient: true})
```
Comment (knz) [inline pkg/sql/pgwire/conn.go:558]: Ditto

File: pkg/sql/conn_io.go [hunk 5]
```diff
@@ -304,7 +304,12 @@ var _ Command = DeletePreparedStmt{}
 // protocol variants. So, it doesn't strictly correspond to a pgwire sync
 // message - those are not sent in the simple protocol. We synthesize Sync
 // commands though because their handling matches the simple protocol too.
-type Sync struct{}
+type Sync struct {
+	// CameFromClient specifies whether this Sync command was generated by the
+	// client during the extended protocol, or implicitly created to handle a
+	// simple protocol query.
+	CameFromClient bool
```
Comment (knz) [inline pkg/sql/conn_io.go:311]: I got myself confused multiple times during the review and had to come back here to re read the comment to understand what the field was for.

I think i would have been less confused if the name of the field contained its purpose as defined by the comment something like `ExplicitAndNotSkippableDuringErrorRecovery` .

**Review by knz — COMMENTED** [review]
This was a nice bug find. The overall structure of the fix is fine. Thanks for the test. I only have minor comments.

File: pkg/sql/pgwire/conn.go (hunk 4 above)
Comment (rafiss) [reply pkg/sql/pgwire/conn.go:558]: and similarly, in this case, we are sending Sync because there _is_ a ClientMsgSync, so this flag should be set

File: pkg/sql/conn_io.go (hunk 5 above)
Comment (rafiss) [reply pkg/sql/conn_io.go:311]: hmm i'll think of another name that might satisfy both of us. `ExplicitAndNotSkippableDuringErrorRecovery` wouldn't be my first preference, since IMHO it's a bit overly specific - it would essentially prevent this field from being used for any other purpose. more abstractly, it feels like that makes the field too strongly coupled to its usage.

File: pkg/sql/conn_executor.go (hunk 1 above)
Comment (rafiss) [reply pkg/sql/conn_executor.go:2294]: i like the map idea, thanks!

File: pkg/sql/conn_io.go (hunk 2 above)
Comment (rafiss) [reply pkg/sql/conn_io.go:604]: added commentary

File: pkg/sql/internal.go [hunk 6]
```diff
@@ -1088,6 +1088,12 @@ func (ie *InternalExecutor) execInternal(
 			}); err != nil {
 			return nil, err
 		}
+		if err := stmtBuf.Push(ctx, Sync{
```
Comment (chengxiong-ruan) [inline pkg/sql/internal.go:1091]: no relevant to your change but wondering why `if len(qargs) == 0 ` can be used determine if it's the last and only statement in the batch. Isn't it just checking if there're any arguments or placeholders?

**Review by chengxiong-ruan — APPROVED** [review]
LGTM!

File: pkg/sql/internal.go (hunk 6 above)
Comment (rafiss) [reply pkg/sql/internal.go:1091]: good question! the internal executor sits in a weird place where it needs to craft these pgwire messages itself. len(qargs) is used to determine if it should use the simple protocol or the extended protocol. (the extended protocol is essentially synonymous with using a prepared statement with placeholders.)

we know it's the last in the batch because the internal executor always sends just one query per batch.

**Comment by rafiss** [comment]
tftr!

bors r+
