### PR TITLE
roachprod-microbench: publish comparison results to InfluxDB

### LINKED ISSUE #128886: roachprod-microbench: publish comparison results to InfluxDB
At the moment the primary way to inspect microbenchmark regressions from the microbenchmark weekly job [1] is to look at the Google Sheets produced by the job. However, this does not always contain enough information to make an informed decision about a regression.

To improve upon this an effort should be made to have a way of displaying microbenchmark history alongside the results. There are a few options:

1. Something similar to `roachperf` [2]
2. Export to an existing system like Prometheus / Grafana / DataDog
3. Consider a 3rd party example like Golang's perf / microbenchmarks dashboard [3]

In regards to option 1, there are plans to deprecate `roachperf` eventually. Option 2 was considered at one point, but tools like Grafana and DataDog are not exactly meant for granular single point metrics that compare against a baseline, or have good ways of consolidating regressions and displaying the information in an easily consumable way.

This makes option 3 currently the most lucrative, and since much of the implementation details are publicly available, it's a good starting point.

Golang's perf dashboards use a combination of cloud storage and InfluxDB (timeseries database) to store its metrics. Cloud storage combined with a SQL database, that serves as a data index, is used to store the source of truth for the comparisons (the raw logs from the microbenchmarks). The comparisons (processed results comparing two revisions) are stored in InfluxDB to make it more readily available for display on the dashboards.

This issue mainly deals with the way in which we plan to store the metrics in InfluxDB for our own purposes. The format in which Golang currently inserts microbenchmark data points is fairly simple and something that we can reuse.

| Field | Desc
|------|-----
| low | lower bound of summary
| center | center of summary
| high | higher bound of summary
| upload-time | timestamp of the run
| baseline-commit | latest stable version of cockroach
| experiment-commit | revision of performance that is evaluated against the baseline
| benchmarks-commit | revision of the microbenchmark framework used (usually the same as experiment)

| Tag | Desc
|------|-----
| name | name of the microbenchmark
| unit | unit of performance measured (ex., sec/op)
| pkg | package the benchmark is from
| repository | cockroach
| branch | branch the benchmarks are from
| goarch | machine architecture
| goos | machine operating system
| machine-type | the cloud vendor's type name for the machine (ex., n2-standard-32)

InfluxDB supports both fields and tags for a datapoint. Fields are not indexed, whereas tags are. Tags are useful for searching and filtering results.

A datapoint (measurement) will typically contain the commit SHAs for both the experiment, and baseline. Where `experiment` is the version being evaluated, and `baseline` is considered the stable version to evaluate against. In addition to storing the comparison we also capture metadata regarding the conditions and environment the microbenchmark was run in.

In order to be compatible with Golang's dashboard it is necessary to consider the queries that will be run against InfluxDB [4]. We can still optionally add our own metadata or other info to the datapoints that will get written to InfluxDB.

[1] https://github.com/cockroachdb/cockroach/blob/master/build/teamcity/cockroach/nightlies/microbenchmark_weekly.sh
[2] https://roachperf.crdb.dev/
[3] https://perf.golang.org/dashboard/
[4] https://github.com/golang/build/blob/master/perf/app/dashboard.go#L300

Jira issue: CRDB-41257

### PR DESCRIPTION
**Pull request by herkolategan**
Previously, microbenchmark results were published only to Google Sheets. This was sufficient to inspect a single comparison between two runs. But a history of microbenchmarks will give much more context when investigating a regression.

The change puts in place the first steps in building microbenchmark dashboards. New InfluxDB flags have been added to the compare command. If an InfluxDB auth token is set the compare command will also publish the results to the specified InfluxDB instance.

In order to make the published comparison results compatible with the dashboard it is intended to be displayed on, the golang benchseries perf packages are used to generate the low, center, and high measurement points. These are the bounds relating to the baseline and experiment revision being compared. Additionally, the commit SHAs, timestamps and machine info is added as metadata to each point.

The golang benchseries perf implementation does not yet support packages. But since we do have duplicate benchmark names in the cockroach repo we need to discern by package. Hence, we send the package as a prefix to benchseries and extract the package and benchmark name after processing.

Resolves: #128886

Epic: None
Release note: None

### CODE REVIEW

File: pkg/cmd/roachprod-microbench/compare.go [hunk 1]
```diff
@@ -318,6 +355,171 @@ func (c *compare) compareUsingThreshold(comparisonResultsMap model.ComparisonRes
...
+	writeAPI := client.WriteAPI("cockroach", "microbench")
+	errorChan := writeAPI.Errors()
+
+	comparisons, err := c.createBenchSeries()
+	if err != nil {
+		return err
+	}
+
+	for _, cs := range comparisons {
+		cs.AddSummaries(0.95, 1000)
```
Comment (DarrylWong) [inline pkg/cmd/roachprod-microbench/compare.go:467]: Educational question: I *think* I understand the idea behind bootstrap samples, but I'm having trouble understanding what the 1000 samples are of. i.e. if a benchmark metric is sec/op, are we collecting a timeseries of that throughout the benchmark and selecting 1000 random points to construct the summary of?

Or am I completely missing what this is doing here.

**Review by DarrylWong — COMMENTED** [review]
This looks good to me so far, just a few minor questions!

File: pkg/cmd/roachprod-microbench/main.go [hunk 2]
```diff
@@ -185,18 +194,23 @@ func makeCompareCommand() *cobra.Command {
...
-	cmd.Flags().StringVar(&config.slackChannel, "slack-channel", config.slackChannel, "slack channel to post the results to")
+	cmd.Flags().StringVar(&config.sheetDesc, "sheet-desc", config.sheetDesc, "set a sheet description to publish the results to Google Sheets")
+	cmd.Flags().StringVar(&config.slackConfig.token, "slack-token", config.slackConfig.token, "pass a slack token to post the results to a slack channel")
+	cmd.Flags().StringVar(&config.slackConfig.user, "slack-user", config.slackConfig.user, "slack user to post the results as")
+	cmd.Flags().StringVar(&config.slackConfig.channel, "slack-channel", config.slackConfig.channel, "slack channel to post the results to")
+	cmd.Flags().StringVar(&config.influxConfig.host, "influx-host", config.influxConfig.host, "InfluxDB host to push the results to")
+	cmd.Flags().StringVar(&config.influxConfig.token, "influx-token", config.influxConfig.token, "pass an InfluxDB auth token to push the results to InfluxDB")
+	cmd.Flags().StringToStringVar(&config.influxConfig.metadata, "influx-metadata", config.influxConfig.metadata, "pass metadata to add to the InfluxDB measurement")
```
[the remark this answers is not in the document]
Comment (herkolategan) [reply pkg/cmd/roachprod-microbench/main.go:212]: This was mostly for testing, or if you have microbenchmark data without any metadata you could manually specify the experiment SHA etc. But from a user perspective the flag might be a bit unclear.

File: pkg/cmd/roachprod-microbench/main.go [hunk 3]
```diff
@@ -162,16 +162,25 @@ func makeCompareCommand() *cobra.Command {
 
 		comparisonResult := c.createComparisons(metricMaps, "baseline", "experiment")
 
-		var links map[string]string
-		if config.publishGoogleSheet {
-			links, err = c.publishToGoogleSheets(comparisonResult)
-			if err != nil {
-				return err
+		if c.sheetDesc != "" {
```
[the remark this answers is not in the document]
Comment (herkolategan) [reply pkg/cmd/roachprod-microbench/main.go:165]: Good catch! the logic here got muddled. Let me fix that.

File: pkg/cmd/roachprod-microbench/main.go [hunk 4]
```diff
@@ -162,16 +162,25 @@ func makeCompareCommand() *cobra.Command {
...
+			var links map[string]string
+			if config.sheetDesc != "" {
+				links, err = c.publishToGoogleSheets(comparisonResult)
+				if err != nil {
+					return err
+				}
+			}
+
+			if config.slackConfig.token != "" {
```
[the remark this answers is not in the document]
Comment (herkolategan) [reply pkg/cmd/roachprod-microbench/main.go:174]: Good point, everything below `newCompare` should be using the `c` instance. Although it ends up referencing the same value, it should be updated to use the instance instead of the config directly. And yes, we should skip Slack if no sheets were generated. Updated.

File: pkg/cmd/roachprod-microbench/compare.go (hunk 1 above)
Comment (herkolategan) [reply pkg/cmd/roachprod-microbench/compare.go:467]: I think it's more of a `resolution` for a calculation used in `benchseries.go`. For this calculation we only have 10 iterations (or values) for each revision; so no timeseries, only a single point in time. The goal of the calculation is to get a type of confidence variance for the comparison of the two runs per metric. I didn't delve to deep into the logic / algorithm, but followed the typical API usage of `benchseries`.

Comment (DarrylWong) [reply pkg/cmd/roachprod-microbench/compare.go:467]: Ah I see, since it's with replacement we can have 1000 samples even with 10 values?

**Review by DarrylWong — APPROVED** [review]
I think when you're done with all the influxDB changes, it might be good to revisit the README and documentation a bit. This change LGTM though.

File: pkg/cmd/roachprod-microbench/compare.go [hunk 5]
```diff
@@ -20,25 +21,39 @@ import (
...
-	newDir             string
-	oldDir             string
-	sheetDesc          string
-	slackUser          string
-	slackChannel       string
-	slackToken         string
-	threshold          float64
-	publishGoogleSheet bool
+	slackConfig
+	influxConfig
```
Comment (renatolabs) [inline pkg/cmd/roachprod-microbench/compare.go:40]: Nit: might be a good idea to not embed these structs, as referencing their fields directly from `compareConfig` is confusing / ambiguous.

File: pkg/cmd/roachprod-microbench/compare.go [hunk 6]
```diff
@@ -318,6 +355,171 @@ func (c *compare) compareUsingThreshold(comparisonResultsMap model.ComparisonRes
...
+
+	for k, v := range c.influxConfig.metadata {
+		benchBuf.WriteString(fmt.Sprintf("%s: %s\n", k, v))
+	}
+
+	logPaths := map[string]string{
+		"experiment": c.experimentDir,
+		"baseline":   c.baselineDir,
+	}
+	for logType, dir := range logPaths {
```
Comment (renatolabs) [inline pkg/cmd/roachprod-microbench/compare.go:389]: I assume this is true, but to confirm: the order in which we write the data to the buffer does not change anything observable from outside this function, right?

File: pkg/cmd/roachprod-microbench/compare.go [hunk 7]
```diff
@@ -318,6 +355,171 @@ func (c *compare) compareUsingThreshold(comparisonResultsMap model.ComparisonRes
...
+			continue
+		}
+		for _, rec := range records {
+			builder.Add(rec)
+		}
+	}
+
+	comparisons, err := builder.AllComparisonSeries(nil, benchseries.DUPE_REPLACE)
+	if err != nil {
+		return nil, errors.Wrap(err, "failed to creation comparison series")
```
Comment (renatolabs) [inline pkg/cmd/roachprod-microbench/compare.go:450]: Nit: `create`

**Review by renatolabs — APPROVED** [review]
Nice work! 🎉

File: pkg/cmd/roachprod-microbench/compare.go (hunk 5 above)
Comment (herkolategan) [reply pkg/cmd/roachprod-microbench/compare.go:40]: Good point, I'll name these.

File: pkg/cmd/roachprod-microbench/compare.go (hunk 6 above)
Comment (herkolategan) [reply pkg/cmd/roachprod-microbench/compare.go:389]: Yes, order should not matter here. The metadata prefixing the data within the loop is the most important aspect.

**Comment by herkolategan** [comment]
TFTRs!

bors r=DarrylWong,renatolabs
