### PR TITLE
roachtest: deflake backupFixture/tpce/15GB/aws

### LINKED ISSUE #105095: roachtest: backupFixture/tpce/15GB/aws failed
roachtest.backupFixture/tpce/15GB/aws [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestWeeklyAwsBazel/10571442?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestWeeklyAwsBazel/10571442?buildTab=artifacts#/backupFixture/tpce/15GB/aws) on master @ [795dd78a4c02f04184192b61c30bcf8fd980b5ea](https://github.com/cockroachdb/cockroach/commits/795dd78a4c02f04184192b61c30bcf8fd980b5ea):

```
(assertions.go:333).Fail: 
	Error Trace:	github.com/cockroachdb/cockroach/pkg/cmd/roachtest/tests/backup_fixtures.go:160
	            				github.com/cockroachdb/cockroach/pkg/cmd/roachtest/tests/backup_fixtures.go:135
	            				github.com/cockroachdb/cockroach/pkg/cmd/roachtest/tests/backup_fixtures.go:292
	            				main/pkg/cmd/roachtest/test_runner.go:1060
	            				GOROOT/src/runtime/asm_amd64.s:1594
	Error:      	Not equal: 
	            	expected: "v23.1.1"
	            	actual  : "v23.2.0-alpha.00000000-dev-795dd78a4c02f04184192b61c30bcf8fd980b5ea"
	            	
	            	Diff:
	            	--- Expected
	            	+++ Actual
	            	@@ -1 +1 @@
	            	-v23.1.1
	            	+v23.2.0-alpha.00000000-dev-795dd78a4c02f04184192b61c30bcf8fd980b5ea
	Test:       	backupFixture/tpce/15GB/aws
	Messages:   	cluster not running on expected binary
(require.go:165).Equal: FailNow called
test artifacts and logs in: /artifacts/backupFixture/tpce/15GB/aws/run_1
```
<p>Parameters: <code>ROACHTEST_arch=amd64</code>
, <code>ROACHTEST_cloud=aws</code>
, <code>ROACHTEST_cpu=4</code>
, <code>ROACHTEST_encrypted=true</code>
, <code>ROACHTEST_fs=ext4</code>
, <code>ROACHTEST_localSSD=false</code>
, <code>ROACHTEST_ssd=0</code>
</p>
<details><summary>Help</summary>
<p>

See: [roachtest README](https://github.com/cockroachdb/cockroach/blob/master/pkg/cmd/roachtest/README.md)

See: [How To Investigate \(internal\)](https://cockroachlabs.atlassian.net/l/c/SSSBr8c7)

</p>
</details>
/cc @cockroachdb/disaster-recovery
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*backupFixture/tpce/15GB/aws.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)
</sub>

Jira issue: CRDB-28856

### PR DESCRIPTION
**Pull request by msbutler**
Previously backupFixture/tpce/15GB/aws would fail in the aws weekly roachtest
run on master because it fails to assert that the cluster runs on release-23.1.
This patch ensures the right cockroach binary is uploaded to the roachprod
cluster running the backupFixture roachtests.

Fixes https://github.com/cockroachdb/cockroach/issues/105095

Release note: None

### CODE REVIEW

File: pkg/cmd/roachtest/tests/backup_fixtures.go [hunk 1]
```diff
@@ -132,7 +134,9 @@ func (bd *backupDriver) prepareCluster(ctx context.Context) {
 
 	bd.c.Put(ctx, bd.t.Cockroach(), "./cockroach")
```
Comment (renatolabs) [inline pkg/cmd/roachtest/tests/backup_fixtures.go:135]: Instead of putting the burden on the user to make sure their cockroach binary aligns with the version required by the test, couldn't the test stage a released binary?

Comment (msbutler) [reply pkg/cmd/roachtest/tests/backup_fixtures.go]: aha! I forgot this is now possible. This simplifies the code nicely. It's a bit goofy that one must always specify a local path to `workload` and `cockroach` even if they are not used, but that seems like a low priority ux papercut.

**Review by renatolabs — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/105571#-:-NYxyrz16fkIrgtHGf47:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @rhu713 and @smg260)

**Comment by msbutler** [comment]
TFTR!!

bors r=renatolabs

**Comment by msbutler** [comment]
bors r=renatolabs
