### PR TITLE
sql/externalcatalog: deflake TestExtractIngestExternalCatalog

### LINKED ISSUE #138639: sql/catalog/externalcatalog: TestExtractIngestExternalCatalog failed
sql/catalog/externalcatalog.TestExtractIngestExternalCatalog [failed](https://tanzanite.cluster.engflow.com/invocations/default/7ec3784f-893a-4ddb-9cc4-1b7cf3da080e?testReportRun=2&testReportShard=1&testReportAttempt=1#targets-Ly9wa2cvc3FsL2NhdGFsb2cvZXh0ZXJuYWxjYXRhbG9nOmV4dGVybmFsY2F0YWxvZ190ZXN0) on master @ [1aba4038242990fdb37a5317512fc5e82d6334fe](https://github.com/cockroachdb/cockroach/commits/1aba4038242990fdb37a5317512fc5e82d6334fe):

```
=== RUN   TestExtractIngestExternalCatalog
    test_log_scope.go:165: test logs captured to: outputs.zip/logTestExtractIngestExternalCatalog3943006934
    test_log_scope.go:76: use -show-logs to present logs inline
    external_catalog_test.go:140: -- test log scope end --
test logs left over in: outputs.zip/logTestExtractIngestExternalCatalog3943006934
--- FAIL: TestExtractIngestExternalCatalog (17.65s)
=== RUN   TestExtractIngestExternalCatalog/basic
    sql_runner.go:298: error executing 'SELECT name FROM crdb_internal.tables WHERE state = 'DROP'': pq: referenced descriptor ID 109: looking up ID 109: descriptor not found
    --- FAIL: TestExtractIngestExternalCatalog/basic (3.06s)
```

Parameters:
 - <code>attempt=1</code>
 - <code>race=true</code>
 - <code>run=2</code>
 - <code>shard=1</code>
<details><summary>Help</summary>
<p>

See also: [How To Investigate a Go Test Failure \(internal\)](https://cockroachlabs.atlassian.net/l/c/HgfXfJgM)
</p>
</details>
/cc @cockroachdb/disaster-recovery
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*TestExtractIngestExternalCatalog.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/bazci/githubpost/issues)

</sub>

Jira issue: CRDB-46176

### PR DESCRIPTION
**Pull request by msbutler**
Previoulsy, the test would always set sql.gc_job.wait_for_gc.interval to 250
ms, to speed up gc of a dropped table. Occasionally, the gc process would
complete so quickly that this post drop query would return no results, flaking
the test:
`SELECT name FROM crdb_internal.tables WHERE state = 'DROP'`

This patch introduce to branches this test can take:
- with fast gc, to test that the gc job was properly created
- without fast gc, to test that the dropped descriptors end up in the dropped
  state.

Fixes #138639

Release note: none

### CODE REVIEW

File: pkg/sql/catalog/externalcatalog/external_catalog_test.go [hunk 1]
```diff
@@ -48,7 +49,12 @@ func TestExtractIngestExternalCatalog(t *testing.T) {
 	sysDB := sqlutils.MakeSQLRunner(srv.SystemLayer().SQLConn(t))
 	sysDB.Exec(t, "SET CLUSTER SETTING sql.virtual_cluster.feature_access.zone_configs.enabled = true;")
 	sysDB.Exec(t, "SET CLUSTER SETTING sql.virtual_cluster.feature_access.zone_configs_unrestricted.enabled = true;")
-	sysDB.Exec(t, "SET CLUSTER SETTING sql.gc_job.wait_for_gc.interval = '250ms'")
+
+	rng, _ := randutil.NewTestRand()
+	fastGC := rng.Float64() < 0.5
+	if fastGC {
```
Comment (jeffswenson) [inline pkg/sql/catalog/externalcatalog/external_catalog_test.go:55]: What's the motivation for making this probabilistic? The two different modes and assertions increase the risk of the test flaking.

Comment (msbutler) [reply pkg/sql/catalog/externalcatalog/external_catalog_test.go:55]: added a bit more context to the commit message. thoughts?

**Review by jeffswenson — APPROVED** [review]
LGTM

**Comment by msbutler** [comment]
Unrelated flake.

TFTR!

bors r=jeffswenson
