### PR TITLE
sql: fix sql activity job from adding too many rows

### LINKED ISSUE #104169: sql activity: sql activity update job adding too many rows
The sql activity update job should only be adding the top 500 for each of the 6 cached columns which should put it at 3k rows per an hour. A user reported the system.statement_activity having more than 58k rows in a single hour. 

The user had over 100k rows per an hour in the system.statement_statistics so a lot of fingerprints are being generated.

Possible causes:
1. ORM is generating a lot of unique fingerprints. Each time job runs it's upserting a new top 500. Currently no work is done to remove queries no longer in the top 500 to keep overhead to a minimum.
2. User is setting unique name per query execution.

Solution:
1. In the cleanup function add a check to remove any queries not in the top 500 for the 6 columns.
2. On update delete all previous rows for that hour and then insert all new top 500.

### PR DESCRIPTION
**Pull request by j82w**
The SQL activity update job runs every 10 minutes. It always upserts the new rows into the statement_activity and transaction_activity table.

The problem is if a customer uses an ORM where it generates a lot of unique queries then the job will keep adding new rows. This causes the activity tables to grow very large. One customer had over 58k rows for a single hour. This causes the SQL Activity page to be very slow.

To prevent the table from growing the update is now done in a transaction where the first statement deletes all the rows, and the next inserts the new rows computed from the statistic table. It needs to be done in a single transaction to avoid user getting no results during the upgrade process. It also ensures that if the job fails it only deletes the older rows if inserting the new rows succeeds.

Epic: none
Fixes: #104169

Release note (sql change): Fixes the SQL Activity update job, so the
 statement_activity and transaction_activity table size is constrained
 when customer has a lot of unique queries. The prevents the SQL
 Activity page from becoming slow.

### CODE REVIEW

**Review by maryliag — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/104257)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @j82w)

___
*[`pkg/sql/sql_activity_update_job_test.go` line 304 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/104257#-NWwbCmlCn-j2rJUXCWm:-NWwbCmlCn-j2rJUXCWn:b-dmuyc1) ([raw file](https://github.com/cockroachdb/cockroach/blob/71a267e47caba1cfc926d33fdacb261076458aa1/pkg/sql/sql_activity_update_job_test.go#L304)):*
> ```Go
> 		// The max number of queries is number of top columns * max number of
> 		// queries per a column (6*3=18 for this test, 6*500=3000 default). Most of
> 		// the top queries are the same in this test so instead of getting 18 it's
> ```

by using different appname or maybe different databases can't you guarantee it will be unique?

**Comment by j82w** [comment]
*[`pkg/sql/sql_activity_update_job_test.go` line 304 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/104257#-NWwbCmlCn-j2rJUXCWm:-NWx1fxj9fPWzdvXhg7x:bej6jnb) ([raw file](https://github.com/cockroachdb/cockroach/blob/71a267e47caba1cfc926d33fdacb261076458aa1/pkg/sql/sql_activity_update_job_test.go#L304)):*
<details><summary><i>Previously, maryliag (Marylia Gutierrez) wrote…</i></summary><blockquote>

by using different appname or maybe different databases can't you guarantee it will be unique?
</blockquote></details>

No, because it needs the stats of the query to be unique.

**Review by maryliag — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/104257#-:-NWxUXC0EMOLIvd3OHqm:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @j82w)

File: pkg/sql/sql_activity_update_job.go [hunk 1]
```diff
@@ -410,25 +434,46 @@ INTO system.public.transaction_activity
...
-		nil, /* txn */
-		sessiondata.NodeUserSessionDataOverride,
-		`
+	errTxn = u.db.Txn(ctx, func(ctx context.Context, txn isql.Txn) error {
+
+		// Delete all the rows of the old data from the table for the current
+		// aggregated timestamp. This is necessary because if a customer generates
+		// a lot of fingerprints each time the upsert runs it will add all new rows
+		// instead of updating the existing one. This causes the
+		// transaction_activity to grow to large causing the UI to be slow.
```
Comment (xinhaoz) [inline pkg/sql/sql_activity_update_job.go:455]: nit `to large` -> `too large`

File: pkg/sql/sql_activity_update_job.go [hunk 2]
```diff
@@ -410,25 +434,46 @@ INTO system.public.transaction_activity
...
+		_, err := txn.ExecEx(ctx,
+			"activity-flush-txn-transfer-tops",
+			txn.KV(), /* txn */
+			sessiondata.NodeUserSessionDataOverride,
+			`DELETE FROM system.public.statement_activity WHERE aggregated_ts = $1;`,
```
Comment (xinhaoz) [inline pkg/sql/sql_activity_update_job.go:460]: Curious, is this going to cause noticeable contentiom when we are attempting to read the sql activity tables via the UI and this job is modifying the table? Also do you think it would be worthwhile to run the stmt and txn table txns concurrently?

**Comment by j82w** [comment]
*[`pkg/sql/sql_activity_update_job.go` line 460 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/104257#gh-1214724220:-NWx_mEz1RKqfeLafCL7:bp0uvca) ([raw file](https://github.com/cockroachdb/cockroach/blob/71a267e47caba1cfc926d33fdacb261076458aa1/pkg/sql/sql_activity_update_job.go#L460)):*
<details><summary><i>Previously, xinhaoz (Xin Hao Zhang) wrote…</i></summary><blockquote>

Curious, is this going to cause noticeable contentiom when we are attempting to read the sql activity tables via the UI and this job is modifying the table? Also do you think it would be worthwhile to run the stmt and txn table txns concurrently?
</blockquote></details>

Based on my understanding it shouldn't cause contention because we always read using As Of System Time.

**Comment by j82w** [comment]
*[`pkg/sql/sql_activity_update_job.go` line 460 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/104257#gh-1214724220:-NWxa1kSBiYrtK2BIA6n:bx0a109) ([raw file](https://github.com/cockroachdb/cockroach/blob/71a267e47caba1cfc926d33fdacb261076458aa1/pkg/sql/sql_activity_update_job.go#L460)):*
> Also do you think it would be worthwhile to run the stmt and txn table txns concurrently?
No, these are very heavy queries. Running them concurrently would roughly double the memory and cpu which would likely impact the latency of other queries.

**Comment by j82w** [comment]
*[`pkg/sql/sql_activity_update_job.go` line 460 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/104257#gh-1214724220:-NXAVat81t5ceQRYgzCP:bee9ynf) ([raw file](https://github.com/cockroachdb/cockroach/blob/71a267e47caba1cfc926d33fdacb261076458aa1/pkg/sql/sql_activity_update_job.go#L460)):*
Can't edit comment. Fixing formatting.
> Also do you think it would be worthwhile to run the stmt and txn table txns concurrently?  

No, these are very heavy queries. Running them concurrently would roughly double the memory and cpu which would likely impact the latency of other queries.

**Review by xinhaoz — APPROVED** [review]
