### PR TITLE
kvcoord: fix a potential persistent failure loop in `DistSender`

### LINKED ISSUE #163393: kv: potential failure loop under persistent CPU overload
**Problem**

When a node is overloaded, requests waiting in the CPU admission control queue can have their context cancelled (deadline exceeded). When this happens, the lease may have moved to another node. However, the DistSender's range cache never learns about this -- subsequent requests continue routing to the overloaded node, timeout in its queue again, and never discover the new leaseholder. This creates a persistent failure loop.

**Error generation**

The timeout errors originate in `WorkQueue.Admit()`. The main waiting path:

https://github.com/cockroachdb/cockroach/blob/21c738f6d88d12398ee45fc6e284f0b58fb443e4/pkg/util/admission/work_queue.go#L779-L828

There's also an early check before queueing, if the context is already cancelled by the time we enter `Admit()`:

https://github.com/cockroachdb/cockroach/blob/21c738f6d88d12398ee45fc6e284f0b58fb443e4/pkg/util/admission/work_queue.go#L717-L733

**DistSender behavior**

The DistSender receives the error in `sendToReplicas`. Because the error has no recognized `ErrorDetailInterface` type, it falls into the `default` case, which returns it to the caller without updating the range cache:

https://github.com/cockroachdb/cockroach/blob/21c738f6d88d12398ee45fc6e284f0b58fb443e4/pkg/kv/kvclient/kvcoord/dist_sender.go#L3099-L3109

**Impact**

The range cache retains the stale leaseholder, so every subsequent request targets the overloaded node, times out in the same queue, and never discovers the actual leaseholder. This persists until the range cache entry is evicted for some other reason or the overloaded node recovers.

**Proposed fix**

One solution is to introduce a new error type and clear the cached lease in response to this error. If we go this route, we'll need to take care that the overloaded node isn't the first one to be retried when the next request comes around.

Jira issue: CRDB-60194

### PR DESCRIPTION
**Pull request by 5hubh4m**
Currently, there are error handling paths in `DistSender` where upon a context cancelation/request timeout, the range descriptor cache entry used for sending the request is never updated. This can cause a potential failure loop where the same stale cache entry is used to send requests to the same stalled replica. This PR introduces a mechanism to address this issue.

---

**rangecache: add methods for leaseholder health tracking and shuffling**

This commit adds the relevant methods and tests to `EvictionToken` for the `DistSender` to track the health of the leaseholder and be able to randomize the leaseholder.

---

**kvcoord: fix a potential persistent failure loop in `DistSender`**

This commit actually implements the logic in `DistSender`. The "health" of the range cache entry is updated upon every successful request to the leaseholder. Upon context errors, if the leaseholder was last contacted too long ago, then we forcibly shuffle it. Also added tests that verify this behaviour. The duration after which a range cache entry is considered eligible for picking another leaseholder is configured using an environment variable. Also added a new counter for tracking how often this happens.

---

Fixes: #163393
Epic: None

### CODE REVIEW

File: pkg/kv/kvclient/kvcoord/dist_sender.go [hunk 1]
```diff
@@ -405,6 +405,18 @@ var senderConcurrencyLimit = settings.RegisterIntSetting(
 	settings.NonNegativeInt,
 )
 
+// rangeDescriptorCacheTimeout controls the timeout after which a range
+// descriptor cache entry is forcibly evicted when a context error occurs while
+// sending a request to a range using it. This can be due to request timeouts,
+// or context cancellation by the caller.
+var rangeDescriptorCacheTimeout = settings.RegisterDurationSetting(
```
Comment (tbg) [inline pkg/kv/kvclient/kvcoord/dist_sender.go]: I am not convinced we should add a setting for this. After all, it's a heuristic that only applies in very limited circumstances in which there likely has already been a period of unavailability AND we see context cancellations.

_If_ we decide it needs to be a setting, we'd need something like `kv.range_descriptor_cache.context_error_eviction_grace_period` and that is a big mouthful.

File: pkg/kv/kvclient/kvcoord/dist_sender.go [hunk 2]
```diff
@@ -2403,6 +2415,19 @@ func (ds *DistSender) sendPartialBatch(
 		log.KvExec.Fatal(ctx, "exited retry loop without an error or early exit")
 	}
 
+	// A context cancellation indicates that this request timed out due to some
+	// kind of stall, due to pathologically low timeouts, or was canceled for
+	// some other reason. We ensure that, in the presence of timeouts, the
+	// DistSender eventually updates the range cache entry and doesn't
+	// indefinitely try to send requests targeting this range using a possibly
+	// stale entry.
+	if ctx.Err() != nil &&
```
Comment (tbg) [inline pkg/kv/kvclient/kvcoord/dist_sender.go]: An alternative idea is to look at how much time elapsed between now and `tBegin` (defined above). If the context is cancelled and the request was pending for more than (say) 2s, we evict if the range descriptor was added to the cache more than 2s ago. In this proposal, we wouldn't mark the descriptor as "healthy" after each successful request. Instead, we simply protect the descriptor for the first couple of seconds of its existence in the cache.

If the range is not unavailable but there is still a steady stream of requests that spend more than 2s on the range and then hit a ctx cancellation, we evict at a rate of at most once every couple of seconds (since after an eviction, the next cached descriptor is initially protected).
Range lookups are fairly cheap, so I would be okay with that degradation in this rare case.

I'm not convinced that it's worth making cache entries mutable and adding a potential contention point in the happy case just to deal with this rare issue.

The other "failure case" of my suggestion is the false negative. If ALL traffic to a "stalled" leaseholder has a context deadline that's short enough that the inflight duration won't clear the bar for even considering eviction, we'd get stuck as well. We could get a little fancier to handle this case by saying that our inflight threshold depends inversely on the age of the descriptor, e.g. "evict a descriptor of age A (in seconds) only if the request that had its conflict canceled was inflight for at least `min(10ms, 5*time.Second/A)`. So when the descriptor is 50s old, we'd evict it even if the canceled request was inflight only for 100ms. At descriptor age 500s, we hit the 10ms inflight cutoff and stay there.

File: pkg/kv/kvclient/kvcoord/dist_sender.go [hunk 3]
```diff
@@ -2403,6 +2415,19 @@ func (ds *DistSender) sendPartialBatch(
...
+		routingTok.Valid() && routingTok.Age() > rangeDescriptorCacheTimeout.Get(&ds.st.SV) {
+		log.VEventf(ctx, 1, "evicting a cached descriptor %s with age %s due to a context error",
+			routingTok.Desc(), routingTok.Age())
+		routingTok.Evict(ctx)
```
Comment (tbg) [inline pkg/kv/kvclient/kvcoord/dist_sender.go]: Do we want to evict the whole thing or only clear the leaseholder?

Come to think of it, I think regardless of which one we choose, won't we - on the next attempt - prefer the lowest-latency replica for the leaseholder discovery? If that replica is the original one (and is the "glue trap") - we wouldn't recover, even if there were a healthy leaseholder.

What that suggests to me is that maybe what we want to do here is NOT to clear the lease or evict the whole thing - but instead treat this as a variation of a `NotLeaseholderError` with `leaseholderUnavailable=true` instead. Then we could enter this path

https://github.com/cockroachdb/cockroach/blob/bb0dca291018a903c32b4e90cb5ad436f26baf66/pkg/kv/kvclient/kvcoord/dist_sender.go#L3106

which would evict the leaseholder, BUT try the next replica which would then either have or properly redirect us at the real leaseholder. That way, we would actually recover.

**Review by tbg — DISMISSED** [review]
Thank you for getting the ball rolling! I left some suggestions to discuss further.

File: pkg/kv/kvclient/kvcoord/dist_sender.go (hunk 1 above)
Comment (5hubh4m) [reply pkg/kv/kvclient/kvcoord/dist_sender.go]: Updated to be fixed 2 second constant in the file.

File: pkg/kv/kvclient/kvcoord/dist_sender.go (hunk 3 above)
Comment (5hubh4m) [reply pkg/kv/kvclient/kvcoord/dist_sender.go]: Summarizing our discussion here for posterity:

As to evicting the leaseholder versus the whole entry–I think we need to evict the whole entry cause in the case of the entry not having the leaseholder, the DistSender just tries the "nearest" replica, which can always happen to be the same broken one, and then the issue of the stale range cache entry will persist. As already observed in the previous comment.

As for the triggering the `NotLeaseholderError` code path–this exists in the `sendToReplicas` function. This function does not have a way to remember the state of any prior failed invocations of this function so as it stands, its highly non-trivial to direct it to take this code path based on a previous timeout. The only shared state between different invocations is i) the `DistSender` `ReplicaCircuitBreaker`s (which are currently disabled) and ii) the range cache `EvictionToken`.

In the end, we decided to introduce a very small machinery in the `EvictionToken` to track the state of how recently this range cache entry was known to be healthy.

Comment (tbg) [reply pkg/kv/kvclient/kvcoord/dist_sender.go]: > As to evicting the leaseholder versus the whole entry–I think we need to evict the whole entry cause in the case of the entry not having the leaseholder, the DistSender just tries the "nearest" replica, which can always happen to be the same broken one, and then the issue of the stale range cache entry will persist. As already observed in the previous comment.

That's not how I understood the problem - when we evict an entry wholesale, a new entry will be fetched next time, but this entry also won't have a leaseholder. This is because these entries stitch together two sources of information: the range descriptor comes from the meta2 ranges, the leaseholder is discovered in a follow-up by trying a replica. Since both cases try the nearest replica, functionally I expect them to get stuck in the same manner if the closest replica is the one that never responds. So rather than evicting the entire record, it would be better to say "try anyone else but this replica as the leaseholder".

Wouldn't it be possible to shuffle the cached leaseholder instead of evicting the token? Say we have replicas on {s1,s2,s3} and we get a context cancellation error while talking to cached leaseholder s1 and it's been >2s since the last successful use of the token. Instead of throwing out the descriptor (which necessarily forgets all of the information we now have), we update the leaseholder to (randomly) one of {s2,s3} and return the cancellation error to the client. The upshot is that the next usage of the cached entry will speculatively use s2 and/or s3. One of them hopefully holds the lease (or can acquire it), and the other one is aware of that. So we either get a direct hit or a proper qualified NotLeaseholderError and our cache will converge.

**Review by tbg — COMMENTED** [review]
> @tbg reviewed 3 files and all commit messages, made 1 comment, and resolved 2 discussions.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/166760)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on 5hubh4m).

File: pkg/kv/kvclient/kvcoord/dist_sender.go (hunk 3 above)
Comment (5hubh4m) [reply pkg/kv/kvclient/kvcoord/dist_sender.go]: Done. Instead of evicting, I'm not selecting a random replica which is different from the current one.

**Review by 5hubh4m — COMMENTED** [review]
I also updated the tests using the `synctest` package  so clocks are fully deterministic.

Also added the test `TestEventuallyRecoverFromStalledLeaseholder` that just ensures that if the leaseholder is stalled, we eventually switch to another replica. This test also acts as a repro of the issue (#163393) and deterministically fails without the fix in this PR.

Added another test `TestRandomizeLeaseOnContextError` that is more targeted and just checks that we select a new leaseholder on a context error after sufficient time has passed. 

> @5hubh4m made 2 comments and resolved 1 discussion.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/166760#-:-Op-fDGT8N72ExWOQvpZ:b6lwe5i)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on tbg).

File: pkg/kv/kvclient/kvcoord/dist_sender.go [hunk 4]
```diff
@@ -2403,6 +2410,30 @@ func (ds *DistSender) sendPartialBatch(
 		log.KvExec.Fatal(ctx, "exited retry loop without an error or early exit")
 	}
 
+	// If a context error occurred and the cache entry is older than a set
```
Comment (tbg) [inline pkg/kv/kvclient/kvcoord/dist_sender.go]: // If a context error occurred and the cached leaseholder hasn't been heard from for a while, randomize the leaseholder. That way, if the cached leaseholder is "bad" (overloaded, mutex deadlock, etc), future
requests have a chance at discovering the actual leaseholder.
// Evicting the cached leaseholder would not necessarily achieve this, since on the next attempt we would preferably try the nearest locality replica, which may be the non-responsive one.

File: pkg/kv/kvclient/kvcoord/dist_sender.go [hunk 5]
```diff
@@ -447,6 +448,12 @@ var NonTransactionalWritesNotIdempotent = settings.RegisterBoolSetting(
 	false,
 )
 
+// rangeDescriptorCacheContextErrorTTL controls the timeout after which a range
```
Comment (tbg) [inline pkg/kv/kvclient/kvcoord/dist_sender.go]: This went stale with the recent changes. Suggestions:

// rangeDescriptorCacheContextErrorTTL determines the duration (since last successful contact) after which a context timeout will randomize the leaseholder.


name suggestion: randomizeLeaseholderAfterContextErrorDuration

File: pkg/kv/kvclient/kvcoord/dist_sender.go [hunk 6]
```diff
@@ -2403,6 +2410,30 @@ func (ds *DistSender) sendPartialBatch(
...
 	}
 
+	// If a context error occurred and the cache entry is older than a set
+	// duration, then we randomly select another replica as a speculative
+	// leaseholder.
+	//
+	// See the comment for the function (*EvictionToken).ExtendTTL() for an
+	// explanation.
+	if ctx.Err() != nil && routingTok.Valid() && routingTok.Age() >= rangeDescriptorCacheContextErrorTTL {
+		replicas := routingTok.Desc().Replicas().VoterDescriptors()
```
Comment (tbg) [inline pkg/kv/kvclient/kvcoord/dist_sender.go]: this block looks like it could make sense as `chosen, err := randomizeLeaseholder(routingTok, intn /* rand.Intn at caller, but deterministic from seed in unit test */)` 

so the code here could be a bit more compact:

```go
if .... {
  chosen, err := randomizeLeaseholder(routingTok)
  if err != nil {
    log.KvExec.Warningf(ctx, "unable to randomize leaseholder: %v", err)
  } else {
    log.KvExec.Infof(ctx, "randomized leaseholder for r%d to %s", routingTok.Desc().RangeID, chosen)
  }
}
```

and you could have unit testing for `randomizeLeaseholder`.

File: pkg/kv/kvclient/kvcoord/dist_sender.go [hunk 7]
```diff
@@ -2974,6 +3005,12 @@ func (ds *DistSender) sendToReplicas(
 						// routing information not exposed by the KV API.
 						br.RangeInfos = nil
 					}
+				} else {
+					// Because the request that used this range cache entry
+					// succeeded, and we received no updated range descriptors,
+					// we should renew the liveness timestamp of the cached
+					// entry.
+					routing.ExtendTTL()
```
Comment (tbg) [inline pkg/kv/kvclient/kvcoord/dist_sender.go]: concretely we're confirming that the leaseholder is reachable, can you rename to make this very explicit (even if all of the options are awkward)? `LeaseholderReachable()`? `ReachedLeaseholder()`?

File: pkg/kv/kvclient/rangecache/range_cache.go [hunk 8]
```diff
@@ -551,6 +552,43 @@ func (et *EvictionToken) RangeInfo() roachpb.RangeInfo {
...
+func (et *EvictionToken) ExtendTTL() {
+	if !et.Valid() {
+		return
+	}
+	et.entry.extendTTL()
+}
+
+// Age returns the time elapsed since the underlying cache entry was last
+// created or has it's TTL extended. Returns 0 for invalid tokens.
+func (et *EvictionToken) Age() time.Duration {
```
Comment (tbg) [inline pkg/kv/kvclient/rangecache/range_cache.go]: ditto about naming, `LastLeaseholderContact()`?

File: pkg/kv/kvclient/rangecache/range_cache.go [hunk 9]
```diff
@@ -551,6 +552,43 @@ func (et *EvictionToken) RangeInfo() roachpb.RangeInfo {
...
+	if !et.Valid() {
+		return 0
+	}
+	return et.entry.age()
```
Comment (tbg) [inline pkg/kv/kvclient/rangecache/range_cache.go]: similar comment

File: pkg/kv/kvclient/rangecache/range_cache.go [hunk 10]
```diff
@@ -1279,10 +1323,21 @@ func (rc *RangeCache) NumInFlight(name string) int {
...
+// multiple queriers for efficiency, but nobody should modify the data in the
+// lookup result.
 type cacheEntry struct {
+	// The data in the cache entry is considered immutable, and should not be
+	// updated once inserted into the cache.
+	cacheEntryData
+	// lastUpdated is the time when this cache entry was updated: either from
+	// the meta ranges, via an updated descriptor received from a replica, or
+	// because a request that used this entry was successfully evaluated.
+	lastUpdated crtime.AtomicMono
```
Comment (tbg) [inline pkg/kv/kvclient/rangecache/range_cache.go]: lastLeaseholderContact?

File: pkg/kv/kvclient/kvcoord/dist_sender_test.go [hunk 11]
```diff
@@ -1861,6 +1862,150 @@ func TestEvictCacheOnUnknownLeaseHolder(t *testing.T) {
...
+	ds := NewDistSender(cfg)
+
+	// Pre-populate the range cache with a known leaseholder.
+	ds.rangeCache.Insert(ctx, roachpb.RangeInfo{
+		Desc:  testUserRangeDescriptor3Replicas,
+		Lease: roachpb.Lease{Replica: originalLeaseholder, Sequence: 1},
+	})
+
+	testutils.SucceedsSoon(t, func() error {
+		sendCtx, cancel := context.WithTimeout(ctx, timeoutDuration)
```
Comment (tbg) [inline pkg/kv/kvclient/kvcoord/dist_sender_test.go]: For a bonus, trace this request (`ContextWithRecordingSpan`) and then check for hitting the "randomized lease" log message in the trace (`rec.FindLogMessage`).

File: pkg/kv/kvclient/kvcoord/dist_sender_test.go [hunk 12]
```diff
@@ -1861,6 +1862,150 @@ func TestEvictCacheOnUnknownLeaseHolder(t *testing.T) {
...
+	stallDuration := 5 * time.Second
+	timeoutDuration := 1 * time.Second
+	testFn := func(ctx context.Context, ba *kvpb.BatchRequest) (*kvpb.BatchResponse, error) {
+		// We wish to create an artificial stall in the leaseholder replica.
+		switch ba.Replica {
+		case originalLeaseholder:
+			select {
+			case <-ctx.Done():
+				return nil, ctx.Err()
+			case <-time.After(stallDuration):
```
Comment (tbg) [inline pkg/kv/kvclient/kvcoord/dist_sender_test.go]: This branch doesn't make sense to me. We make a new timer here every time. The context cancels after 1s (since beginning of test), so from that point `<-ctx.Done()` will always fire immediately, while we start a new 5s timer every time testFn is called, so it will never (also) fire.

Shouldn't this just be

```go
switch ba.Replica {
case originalLeaseholder:
  <-ctx.Done()
  return nil, ctx.Err()
default:
  return ba.CreateReply(), nil
}
```

File: pkg/kv/kvclient/kvcoord/dist_sender_test.go [hunk 13]
```diff
@@ -1861,6 +1862,150 @@ func TestEvictCacheOnUnknownLeaseHolder(t *testing.T) {
 	}
 }
 
+// TestEventuallyRecoverFromStalledLeaseholder verifies that when the
+// leaseholder replica is stalled indefinitely, we eventually try to contact a
+// different replica and can recover.
+func TestEventuallyRecoverFromStalledLeaseholder(t *testing.T) {
```
Comment (tbg) [inline pkg/kv/kvclient/kvcoord/dist_sender_test.go]: Looks like this test timed out in CI. It also times out locally when I run it.

File: pkg/kv/kvclient/kvcoord/dist_sender_test.go [hunk 14]
```diff
@@ -1861,6 +1862,150 @@ func TestEvictCacheOnUnknownLeaseHolder(t *testing.T) {
...
+		stallDuration := 5 * time.Second
+		timeoutDuration := 1 * time.Second
+		testFn := func(ctx context.Context, ba *kvpb.BatchRequest) (*kvpb.BatchResponse, error) {
+			// We wish to create an artificial stall in the leaseholder replica.
+			switch ba.Replica {
+			case originalLeaseholder:
+				select {
+				case <-ctx.Done():
+					return nil, ctx.Err()
+				case <-time.After(stallDuration):
```
Comment (tbg) [inline pkg/kv/kvclient/kvcoord/dist_sender_test.go]: same comment here.

File: pkg/kv/kvclient/kvcoord/dist_sender_test.go [hunk 15]
```diff
@@ -1861,6 +1862,150 @@ func TestEvictCacheOnUnknownLeaseHolder(t *testing.T) {
...
+		_, pErr := kv.SendWrapped(sendCtx, ds, get)
+		return pErr.GoError()
+	})
+}
+
+// TestRandomizeLeaseOnContextError verifies that when a context error occurs
+// and the range cache entry is older than rangeDescriptorCacheContextErrorTTL,
+// the DistSender randomly selects a different replica as a speculative
+// leaseholder and updates the cache.
+func TestRandomizeLeaseOnContextError(t *testing.T) {
```
Comment (tbg) [inline pkg/kv/kvclient/kvcoord/dist_sender_test.go]: This test currently deadlocks. Claude easily found out why: some of the timers spun up by the DistSender come from a `sync.Pool` that is outside the bubble, so fake time stalls and the test hangs (possibly non-deterministically, depending on the state of the sync.Pool at the beginning of the bubble.

> TestRandomizeLeaseOnContextError deadlocks because NewDistSender starts background goroutines (like probeStallLoop) inside the synctest bubble. probeStallLoop uses timeutil.Timer, which pools time.Timer
   objects. A pooled timer created outside the bubble makes the select non-durable, permanently blocking fake-clock advancement. The time.Sleep(rangeDescriptorCacheContextErrorTTL) on line 1991 never completes.

`synctest` is nice, but this sort of thing suggests that it is best suited to testing very contained pieces of code.

In the case at hand, I don't think we need to mock time at all? Make a cancelable context, and then have `testFn` (when on the "broken" leaseholder) immediately call the cancel function (and return `ba.CreateReply(), ctx.Err()`). That error should bubble back up to the client. Then check on the state of the cached leaseholder: should be one of the other replicas. Then repeat the call (with fresh context), and it will work.
We can record traces for both and check that the first trace hits the "randomizing leaseholder" case.

**Review by tbg — CHANGES_REQUESTED** [review]
Functionally ➕, remaining comments are about polish and testing.

**Review by tbg — APPROVED** [review]
I pushed some fixup commits to speed things along:

-  simplify/fix checks in RandomizeLeaseholder
  - use time.Time instead of raw int64 nanos (this is just a nit, I figured I might as well do it)
  - Only call MarkLeaseholderContacted when curReplica matches the cached leaseholder (not on follower reads), and move it out of the RangeInfos else branch
  - TestEventuallyRecoverFromLeaseholderContextError was very flaky due to a metamorphic variable which needed to be overridden. I added better logging in the failure case, and also tightened up the test to avoid duplication.

When you're happy with the additional commits, squash them in, and unless anything changes significantly and tests pass, :lgtm_strong:. Approving preemptively.

> @tbg reviewed 5 files and all commit messages, made 3 comments, and resolved 12 discussions.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/166760#-:-Op7m5vk5nkuj1b3xzS5:b-fgyurc)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on 5hubh4m).

___
*[`pkg/kv/kvclient/rangecache/range_cache.go` line 586 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/166760#-Op7W0ZmCjmlDyq_-Ug_:-Op7W0ZmCjmlDyq_-Uga:b-3tm0x5) ([raw file](https://github.com/cockroachdb/cockroach/blob/9dfdc7016ef98c1d96341d5329aff2d18c977327/pkg/kv/kvclient/rangecache/range_cache.go#L586)):*
> ```Go
> 	}
> 
> 	et.rdc.rangeCache.Lock()
> ```

so we check that `et.entry.desc` has more than one voter above. But we lock the cache only here. Then, in `randomizeLeaseholder`, we operate on `cachedEntry` which may have been replaced already (?). I see in `syncRLocked` that it will return `stillValid` only if the possibly updated entry in the cache is "compatible" with the descriptor in the `EvictionToken`,  but  a changing set of voters keeps it compatible. I think that means that the check above isn't ironclad. But we also don't need it, we can just lock the cache unconditionally, since this is not in the hot path, and make our life a little simpler (rather than repeating the check).

I'll push a fixup with this for your consideration.
___
*[`pkg/kv/kvclient/kvcoord/dist_sender.go` line 3005 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/166760#-Op7VgY62oPPeLz0v-1a:-Op7VgY62oPPeLz0v-1b:b-679cw5) ([raw file](https://github.com/cockroachdb/cockroach/blob/9dfdc7016ef98c1d96341d5329aff2d18c977327/pkg/kv/kvclient/kvcoord/dist_sender.go#L3005)):*
> ```Go
> 					// The request that used this range cache entry successfully
> 					// contacted the leaseholder.
> 					routing.MarkLeaseholderContacted()
> ```

I don't think this is exactly the right place - see fixup commit. We need to know that we actually talked to the leaseholder, and I don't think we should be in an `else` branch here.

**Review by 5hubh4m — COMMENTED** [review]
1. Cherry picked and squashed the fixup commits from [tbg/cockroach (distsender-retry)](https://github.com/tbg/cockroach/commits/distsender-retry).
2. Added a counter to track how many times `DistSender` has to randomize the leaseholder. Could be a meaningful obs signal. 
3. Made `randomizeLeaseholderOnContextErrorDuration` configurable using an environment variable.
4. The diffs got big enough that I split the commits into two: the `EvictionToken` changes & the `DistSender` changes.

Thank you so much for the review @tbg :raised_hands:!!! 

> @5hubh4m made 3 comments and resolved 2 discussions.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/166760#-:-Op9pulK2QizPVsJ1IRa:bxtz3sw)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on cpj2195, shailendra-patel, and tbg).

___
*[`pkg/kv/kvclient/kvcoord/dist_sender.go` line 3005 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/166760#-Op7VgY62oPPeLz0v-1a:-Op9pNhhCpcZrL_P6Wz6:bs7wumx) ([raw file](https://github.com/cockroachdb/cockroach/blob/9dfdc7016ef98c1d96341d5329aff2d18c977327/pkg/kv/kvclient/kvcoord/dist_sender.go#L3005)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

I don't think this is exactly the right place - see fixup commit. We need to know that we actually talked to the leaseholder, and I don't think we should be in an `else` branch here.
</blockquote></details>

Done. 
___
*[`pkg/kv/kvclient/rangecache/range_cache.go` line 586 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/166760#-Op7W0ZmCjmlDyq_-Ug_:-Op9pk4UELcRWSSlfu5l:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/9dfdc7016ef98c1d96341d5329aff2d18c977327/pkg/kv/kvclient/rangecache/range_cache.go#L586)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

so we check that `et.entry.desc` has more than one voter above. But we lock the cache only here. Then, in `randomizeLeaseholder`, we operate on `cachedEntry` which may have been replaced already (?). I see in `syncRLocked` that it will return `stillValid` only if the possibly updated entry in the cache is "compatible" with the descriptor in the `EvictionToken`,  but  a changing set of voters keeps it compatible. I think that means that the check above isn't ironclad. But we also don't need it, we can just lock the cache unconditionally, since this is not in the hot path, and make our life a little simpler (rather than repeating the check).

I'll push a fixup with this for your consideration.
</blockquote></details>

Done.
