### PR TITLE
roachtest: fail tests if monitor encounters an error

### LINKED ISSUE #118563: roachtest: cluster monitor hanging after unexpected node closure
roachtest.import/tpch/nodes=8 [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/13762710?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/13762710?buildTab=artifacts#/import/tpch/nodes=8) on master @ [ed3a25e3c9459cede2f80babbfc9d44a836b6c12](https://github.com/cockroachdb/cockroach/commits/ed3a25e3c9459cede2f80babbfc9d44a836b6c12):

```
VMs preempted during the test run : projects/cockroach-ephemeral/zones/us-east1-b/instances/teamcity-13762710-1706682693-107-n8cpu4-0005

**Other Failure**
(test_runner.go:1136).runTest: test timed out (10h0m0s)
test artifacts and logs in: /artifacts/import/tpch/nodes=8/run_1
```

Parameters:
 - <code>ROACHTEST_arch=amd64</code>
 - <code>ROACHTEST_cloud=gce</code>
 - <code>ROACHTEST_coverageBuild=false</code>
 - <code>ROACHTEST_cpu=4</code>
 - <code>ROACHTEST_encrypted=true</code>
 - <code>ROACHTEST_fs=ext4</code>
 - <code>ROACHTEST_localSSD=true</code>
 - <code>ROACHTEST_metamorphicBuild=false</code>
 - <code>ROACHTEST_ssd=0</code>
<details><summary>Help</summary>
<p>

See: [roachtest README](https://github.com/cockroachdb/cockroach/blob/master/pkg/cmd/roachtest/README.md)

See: [How To Investigate \(internal\)](https://cockroachlabs.atlassian.net/l/c/SSSBr8c7)

See: [Grafana](https://go.crdb.dev/roachtest-grafana/teamcity-13762710/import-tpch-nodes-8/1706720321740/1706756980821)

</p>
</details>
/cc @cockroachdb/sql-queries
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*import/tpch/nodes=8.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)
</sub>

Jira issue: CRDB-35788

### PR DESCRIPTION
**Pull request by renatolabs**
This commit updates the roachprod and roachtest monitors to 1) send an
event when the monitor is abruptly terminated (i.e., reader stream
sees an EOF when the associated context is *not* canceled); and 2)
return any errors encountered by the roachprod monitor in roachtest,
causing the currently running test to fail. The error has TestEng
ownership so that teams are not be pinged on these kinds of flakes.

The main purpose of this change is for the monitor to fail in
situations where the monitored node is preempted by the cloud
provider. Previously, these events would be ignored, leading to a test
timeout, wasting resources and leading to confusing test failures
being reported on GitHub.

Fixes: #118563.

Release note: None

### CODE REVIEW

**Comment by renatolabs** [comment]
Verified that the logic here works by simulating a VM preemption (i.e., running a roachtest and manually deleting one of the VMs on GCE). [0.1 build](https://teamcity.cockroachdb.com/viewLog.html?buildId=14122610&tab=queuedBuildOverviewTab) is also currently in progress.

Do others think this approach is reasonable? I also played with [a different approach](https://github.com/cockroachdb/cockroach/compare/master...renatolabs:cockroach:rc/roachtest-fail-test-if-preempted) where roachtest continuously monitors for preempted VMs, but I think it's more general to have the monitor cause the test to fail on errors, which should fix the timeouts we observed with VM preemption.

Let me know!

**Review by herkolategan — APPROVED** [review]
Nice, hopefully this will reduce some noise for other teams!

File: pkg/cmd/roachtest/test_runner.go [hunk 1]
```diff
@@ -1016,6 +1016,14 @@ func (r *testRunner) runTest(
...
 				if preemptedVMNames != "" {
 					failureMsg = fmt.Sprintf("VMs preempted during the test run : %s\n\n**Other Failure**\n%s", preemptedVMNames, failureMsg)
+					// Reset failures in the test so that the VM preemption
+					// error is the one that is taken into account when
+					// reporting the failure. Note any other failures that
+					// happened during the test will be present in the
+					// `failureMsg` used when reporting the issue. In addition,
+					// `failure_N.log` files should also already exist at this
+					// point.
+					t.resetFailures()
```
Comment (srosenberg) [inline pkg/cmd/roachtest/test_runner.go:1026]: Nice!

**Comment by srosenberg** [comment]
> Do others think this approach is reasonable? I also played with [a different approach](https://github.com/cockroachdb/cockroach/compare/master...renatolabs:cockroach:rc/roachtest-fail-test-if-preempted) where roachtest continuously monitors for preempted VMs, but I think it's more general to have the monitor cause the test to fail on errors, which should fix the timeouts we observed with VM preemption.
> 
> Let me know!

I like the current approach for its parsimony! It's also more general, i.e., not specific to preemption. Thus, we can now monitor (pun intended) for these types of "infra flake" while at the same time reducing the noise due to unattributed test failures.

**Review by srosenberg — APPROVED** [review]
Thanks for continuing to improve the `monitor`! :)

**Comment by renatolabs** [comment]
TFTR!

bors r=srosenberg
