### PR TITLE
storage: eagerly gossip first range in changeReplicasTrigger

### LINKED ISSUE #7297: storage: node hangs for 1 minute when first replica is deleted
While setting up sql benchmark tests for a multinode cluster I waited for one of the two joining nodes to have a replica before executing sql commands. During the tests, the first node wound up dropping its first range and adding it to one of the joining nodes. This caused the node to stall for 1 minute, pausing all sql commands issued to the cluster, while throwing the error:

    W160616 16:46:15.660980 kv/dist_sender.go:655  failed to send RPC: sending to all 1 replicas failed; last error: range 1 was not found

The node should probably be able to resolve this in a quicker manner if it's able to resolve it at all.

### PR DESCRIPTION
**Pull request by petermattis**
Fixes #7297.

---

This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/7766)

### CODE REVIEW

File: storage/replica_command.go [hunk 1]
```diff
@@ -2799,6 +2799,39 @@ func (r *Replica) changeReplicasTrigger(ctx context.Context, batch engine.Batch,
...
+	if r.RangeID == 1 && (change.ChangeType == roachpb.ADD_REPLICA ||
+		r.store.StoreID() != change.Replica.StoreID) {
+		batch.Defer(func() {
+			// We need to run the gossip in an async task because gossiping requires
+			// the range lease and we'll deadlock if we try to acquire it will
+			// holding processRaftMu. Specifically, Replica.redirectOnOrAcquireLease
+			// blocks waiting for the lease acquisition to finish but it can't finish
+			// because we're not processing raft messages due to holding
+			// processRaftMu (and running on the processRaft goroutine).
+			r.store.Stopper().RunAsyncTask(func() {
```
Comment (tschottdorf) [inline storage/replica_command.go]: Now that I see this, it would be cleaner to call `redirectOnOrAcquireLeaderLease()` before this and only do this from the replica which wins. That would also preclude stale information from being gossiped.

**Comment by tschottdorf** [comment]
LGTM mod comment.

File: storage/replica_command.go (hunk 1 above)
Comment (petermattis) [inline storage/replica_command.go]: I'm not sure I understand what you're suggesting. `maybeGossipFirstRange()` calls `getLeaseForGossip()` which calls `redirectOnOrAcquireLeaderLease()`. We only ever gossip the first range from the first range lease holder.

Comment (tschottdorf) [inline storage/replica_command.go]: I don't think that would work the way you imagine it to (but it probably does, or you wouldn't have PR'ed this, which makes me wonder what I'm missing - maybe that particular test we were looking at bumps the clock all the time). The nodes still have the (now defunct) lease, so they won't actually gossip as a result of this call as far as I can tell (because the lease for `Now()` is still held by the node just removed, and even if the nodes took into account that it had been removed, they still couldn't shorten the existing lease).

Seems worth investigating the above. My feeling is that we won't really be able to do anything useful here except for
a) gossipping the first range unconditionally from all followers (paying with the occasional stale gossip which could also cause the 1min unavailability) or
b) waiting until we've incorporated lease transfers into the rebalancing process (at which point the lease holder will never be equal to the replica which is being removed).
c) leave as is, but clearly point out that this fixes only some unit test, not reality.

Comment (petermattis) [inline storage/replica_command.go]: I ran the test with `--vmodule=replica=3` and saw log messages indicating that the first range was being gossiped from a store other than store 1. I'm happy to investigate more about how this is working. The test we're investigating is `TestUnreplicateFirstRange` which doesn't muck with clocks at all as far as I can tell.

Comment (tschottdorf) [inline storage/replica_command.go]: Are you sure? `(*multiTestContextKVTransport).SendNext` bumps the clock pretty aggressively and (I think) is involved here. Logging from `expireLeases()` should tell.

**Comment by tamird** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[storage/replica_command.go, line 2815 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7766#-KMULz-g4SZoSiWnDflK:-KMULz-g4SZoSiWnDflL:-2078813819) ([raw file](https://github.com/cockroachdb/cockroach/blob/fbe4f8e6518d665ec0f6ee1f4b9ff4a558c3b463/storage/replica_command.go#L2815)):*
> ```Go
> 	// It should be possible to set up a three-node cluster, wait for initial
> 	// replication of the first range, and then to disable the replication queue
> 	// and downreplicate so that the first range leader disappears. Subsequently
> ```

range lease holder?

---

*[storage/replica_command.go, line 2817 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7766#-KMUM4x8y-WB4t_-KY6-:-KMUM4x8y-WB4t_-KY60:-976516537) ([raw file](https://github.com/cockroachdb/cockroach/blob/fbe4f8e6518d665ec0f6ee1f4b9ff4a558c3b463/storage/replica_command.go#L2817)):*
> ```Go
> 	// and downreplicate so that the first range leader disappears. Subsequently
> 	// we should be able to verify that the first range gossip updates accordingly
> 	// in a short amount of time (and once we have lease transfers, we can check
> ```

lease transfers are already merged, no?

---

*[storage/replica_command.go, line 2823 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7766#-KMUMPUZh0GrV9STjqVf:-KMUMPUZh0GrV9STjqVg:2028273530) ([raw file](https://github.com/cockroachdb/cockroach/blob/fbe4f8e6518d665ec0f6ee1f4b9ff4a558c3b463/storage/replica_command.go#L2823)):*
> ```Go
> 		batch.Defer(func() {
> 			// We need to run the gossip in an async task because gossiping requires
> 			// the range lease and we'll deadlock if we try to acquire it will
> ```

s/will/while/

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7766#-:-KMULnASU6Km_qsvKpv0:1417088721)*

File: storage/replica_command.go (hunk 1 above)
Comment (petermattis) [inline storage/replica_command.go]: No, I'm not sure at all about the clocks. Looking at it now, you're correct that we're bumping the manual clock aggressively in this test.

Instead of this change, perhaps `redirectOnOrAcquireLease` should check to see if it acquired the lease for the first range. If this is too aggressive, we could have a bit of logic to not gossip on every lease acquisition, but only if it is not a reacquisition of the lease by the same store.

Comment (tschottdorf) [inline storage/replica_command.go]: Yeah, that does seem reasonable. The interval should be close to `0.8*(raftElectionTimeoutTicks*raftTickInterval) = 80ms*15ms` and it seems ok to have one replica gossip a relatively small payload at that frequency.

Comment (petermattis) [inline storage/replica_command.go]: Yeah. Moved this gossiping to `Replica.applyNewLeaseLocked`. Not sure if that is the right place, but it seems to work. I still need to fix the failure of `TestReplicaTSCacheLowWaterOnLease` which is due to that test using the first range.

Comment (petermattis) [inline storage/replica_command.go]: Fixed the test failure. PTAL.

**Comment by petermattis** [comment]
Review status: 0 of 2 files reviewed at latest revision, 4 unresolved discussions, all commit checks successful.

---

*[storage/replica_command.go, line 2815 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7766#-KMULz-g4SZoSiWnDflK:-KMZQJM6rG-qbuKRwi4B:-350165475) ([raw file](https://github.com/cockroachdb/cockroach/blob/fbe4f8e6518d665ec0f6ee1f4b9ff4a558c3b463/storage/replica_command.go#L2815)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> range lease holder?
</details>
This code completely changed. PTAL.

---

*[storage/replica_command.go, line 2817 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7766#-KMUM4x8y-WB4t_-KY6-:-KMZQOAPzKhbKapVFWP_:-350165475) ([raw file](https://github.com/cockroachdb/cockroach/blob/fbe4f8e6518d665ec0f6ee1f4b9ff4a558c3b463/storage/replica_command.go#L2817)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> lease transfers are already merged, no?
</details>
This code completely changed. PTAL.

---

*[storage/replica_command.go, line 2823 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7766#-KMUMPUZh0GrV9STjqVf:-KMZQP2MhCIhlwzA2JkE:-350165475) ([raw file](https://github.com/cockroachdb/cockroach/blob/fbe4f8e6518d665ec0f6ee1f4b9ff4a558c3b463/storage/replica_command.go#L2823)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> s/will/while/
</details>
This code completely changed. PTAL.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7766)*

**Comment by tamird** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 4 unresolved discussions, all commit checks successful.

---

*[storage/replica.go, line 2469 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7766#-KMZY2TzYdCZz6gD40_O:-KMZY2TzYdCZz6gD40_P:1586044357) ([raw file](https://github.com/cockroachdb/cockroach/blob/c8a5ef6ffca508228a2a4ceba524f8cea4af8846/storage/replica.go#L2469)):*
> ```Go
> 
> func (r *Replica) gossipFirstRange(ctx context.Context) {
> 	if r.store.Gossip() == nil {
> ```

comment?

---

*[storage/replica_command.go, line 1588 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7766#-KMZYDEcMWDy5an7OgpV:-KMZYDEcMWDy5an7OgpW:772327581) ([raw file](https://github.com/cockroachdb/cockroach/blob/c8a5ef6ffca508228a2a4ceba524f8cea4af8846/storage/replica_command.go#L1588)):*
> ```Go
> // r.mu needs to be locked.
> func (r *Replica) applyNewLeaseLocked(
> 	ctx context.Context, batch engine.ReadWriter,
> ```

maybe bring this in line with the style guide while you're here...this is an eyesore

---

*[storage/replica_command.go, line 1628 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7766#-KMZY9cSnhcmRIpi4iDv:-KMZY9cSnhcmRIpi4iDw:-972603086) ([raw file](https://github.com/cockroachdb/cockroach/blob/c8a5ef6ffca508228a2a4ceba524f8cea4af8846/storage/replica_command.go#L1628)):*
> ```Go
> 		// what reliable signal to use to determine that.
> 		batch.(engine.Batch).Defer(func() {
> 			r.gossipFirstRange(r.context(context.TODO()))
> ```

there's a `ctx` in scope, why not use that?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7766)*

**Comment by petermattis** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions, all commit checks successful.

---

*[storage/replica.go, line 2469 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7766#-KMZY2TzYdCZz6gD40_O:-KMZYxpwiTX6foCYhYmN:-1697778266) ([raw file](https://github.com/cockroachdb/cockroach/blob/c8a5ef6ffca508228a2a4ceba524f8cea4af8846/storage/replica.go#L2469)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> comment?
</details>
Various tests don't configure gossip, but wouldn't get here from the previous `maybeGossipFirstRange` code path but can from `applyNewLeaseLocked`.

---

*[storage/replica_command.go, line 1588 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7766#-KMZYDEcMWDy5an7OgpV:-KMZbD9o6-L-0NLrAMtn:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/c8a5ef6ffca508228a2a4ceba524f8cea4af8846/storage/replica_command.go#L1588)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> maybe bring this in line with the style guide while you're here...this is an eyesore
</details>
Done.

---

*[storage/replica_command.go, line 1628 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7766#-KMZY9cSnhcmRIpi4iDv:-KMZYvMNwMNDi-khjQOD:393523174) ([raw file](https://github.com/cockroachdb/cockroach/blob/c8a5ef6ffca508228a2a4ceba524f8cea4af8846/storage/replica_command.go#L1628)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> there's a `ctx` in scope, why not use that?
</details>
No reason, just missed it when I split up `maybeGossipFirstRange`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7766)*

**Comment by tamird** [comment]
Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7766)*

**Comment by petermattis** [comment]
@tschottdorf ?

**Comment by tschottdorf** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[storage/replica_command.go, line 1626 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7766#-KMZkUGWxPzpv7b5hIab:-KMZkUGWxPzpv7b5hIac:1252425146) ([raw file](https://github.com/cockroachdb/cockroach/blob/a6acb211dd3882479fc3f79bd08931b34e4a358a/storage/replica_command.go#L1626)):*
> ```Go
> 
> 	if r.IsFirstRange() {
> 		// Gossip the first range whenever its lease is acquired.
> ```

Perhaps add a comment that while it seems more prudent to have only the new lease holder gossip this, that actually comes with a potential issue: If a Replica is far behind and processes an old lease of itself, it will gossip (potentially overriding more recent information), and it then would *not* gossip the current lease once it catches up to it. The problem is hypothetical at this point but it's a good opportunity to point out some subtleties about Raft-triggered gossip.

You could also make the gossip conditional on the acquired lease being valid for the current HLC timestamp. But I'm ok leaving as is.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7766#-:-KMZkN0K88GK7Bj0xE3-:1417088721)*

**Comment by petermattis** [comment]
Review status: 1 of 2 files reviewed at latest revision, 2 unresolved discussions, some commit checks pending.

---

*[storage/replica_command.go, line 1626 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7766#-KMZkUGWxPzpv7b5hIab:-KMZml_h9EFfqThLYqZy:-1357242972) ([raw file](https://github.com/cockroachdb/cockroach/blob/a6acb211dd3882479fc3f79bd08931b34e4a358a/storage/replica_command.go#L1626)):*
<details><summary><i>Previously, tschottdorf (Tobias Schottdorf) wrote…</i></summary>
> Perhaps add a comment that while it seems more prudent to have only the new lease holder gossip this, that actually comes with a potential issue: If a Replica is far behind and processes an old lease of itself, it will gossip (potentially overriding more recent information), and it then would *not* gossip the current lease once it catches up to it. The problem is hypothetical at this point but it's a good opportunity to point out some subtleties about Raft-triggered gossip.
> 
> You could also make the gossip conditional on the acquired lease being valid for the current HLC timestamp. But I'm ok leaving as is.
</details>
Adding a check for `lease.Covers(r.store.Clock().Now())` is easy enough. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7766)*

**Comment by bdarnell** [comment]
Review status: 1 of 2 files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[storage/replica_command.go, line 1626 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7766#-KMZkUGWxPzpv7b5hIab:-KM_sGMXSP8NN_vPHfbJ:-50574931) ([raw file](https://github.com/cockroachdb/cockroach/blob/a6acb211dd3882479fc3f79bd08931b34e4a358a/storage/replica_command.go#L1626)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary>
> Adding a check for `lease.Covers(r.store.Clock().Now())` is easy enough. 
</details>
Doesn't this gossip every time the lease is refreshed? That seems like too much. This PR also doesn't do anything to ensure that the lease will be reacquired soon after a replication change. Something else is apparently likely enough to do a consistent operation on the first range and force a lease refresh, but it would be better to trigger a `getLeaseForGossip` as a consequence of `changeReplicasTrigger`. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7766)*

**Comment by petermattis** [comment]
Review status: 1 of 2 files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[storage/replica_command.go, line 1626 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7766#-KMZkUGWxPzpv7b5hIab:-KMaCcJ0lwwCGE0-Frve:683062322) ([raw file](https://github.com/cockroachdb/cockroach/blob/a6acb211dd3882479fc3f79bd08931b34e4a358a/storage/replica_command.go#L1626)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary>
> Doesn't this gossip every time the lease is refreshed? That seems like too much. This PR also doesn't do anything to ensure that the lease will be reacquired soon after a replication change. Something else is apparently likely enough to do a consistent operation on the first range and force a lease refresh, but it would be better to trigger a `getLeaseForGossip` as a consequence of `changeReplicasTrigger`. 
</details>
Yes, this gossips on every lease acquisition. @tschottdorf didn't think this would be overly burdensome. If it is, I think we could introduce mechanisms to only gossip when the descriptor has changed. One way to do that is to only gossip when `RangeDescriptor.NextReplicaID` changes. 

Good point about calling `getLeaseForGossip` from `changeReplicasTrigger`. I'll fix that in a follow-on PR.

Do we have internal documentation about leases? I haven't internalized all of the rules surrounding them. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7766)*

**Comment by bdarnell** [comment]
Review status: 1 of 2 files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[storage/replica_command.go, line 1626 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7766#-KMZkUGWxPzpv7b5hIab:-KMaEgS14lk7m3HWCZj8:1185478645) ([raw file](https://github.com/cockroachdb/cockroach/blob/a6acb211dd3882479fc3f79bd08931b34e4a358a/storage/replica_command.go#L1626)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary>
> Yes, this gossips on every lease acquisition. @tschottdorf didn't think this would be overly burdensome. If it is, I think we could introduce mechanisms to only gossip when the descriptor has changed. One way to do that is to only gossip when `RangeDescriptor.NextReplicaID` changes. 
> 
> Good point about calling `getLeaseForGossip` from `changeReplicasTrigger`. I'll fix that in a follow-on PR.
> 
> Do we have internal documentation about leases? I haven't internalized all of the rules surrounding them. 
</details>
There's a "Range Leases" section in the design doc.

Leases are only a few seconds; this is much more frequent than anything else we gossip. We generally do things like this in the "this replica is a new holder of the lease" block below. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7766)*

**Comment by petermattis** [comment]
Review status: 1 of 2 files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[storage/replica_command.go, line 1626 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7766#-KMZkUGWxPzpv7b5hIab:-KMatNMTNBweaFD1SQ9u:1374317503) ([raw file](https://github.com/cockroachdb/cockroach/blob/a6acb211dd3882479fc3f79bd08931b34e4a358a/storage/replica_command.go#L1626)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary>
> There's a "Range Leases" section in the design doc.
> 
> Leases are only a few seconds; this is much more frequent than anything else we gossip. We generally do things like this in the "this replica is a new holder of the lease" block below. 
</details>
Yes, this will result in much more frequent gossiping than we've done previously, but gossiping the first range descriptor once every few seconds doesn't seem like it will have any significant impact and it will make sure the first range and the key sentinel are fresh. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7766)*

**Comment by tamird** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7766)*
