### PR TITLE
sql: explain debug on selects with no table and subselects

### LINKED ISSUE #4060: SQL: `explain (debug) select 3` crashes server
eg:
```
[sql --host=127.0.0.1 --pgport=44101 --certs=/tmp/cli-test561717278 -e explain (debug) select 3]
panic: runtime error: slice bounds out of range

goroutine 277 [running]:
github.com/cockroachdb/cockroach/sql.(*selectNode).Next(0xc820742000, 0xc82010b9c0)
        /home/marc/cockroach/src/github.com/cockroachdb/cockroach/sql/select.go:122 +0x3c0
github.com/cockroachdb/cockroach/sql.(*Executor).execStmt.func1(0xece418154, 0xba13b48, 0x2162c80, 0xc820529101, 0x28)
        /home/marc/cockroach/src/github.com/cockroachdb/cockroach/sql/executor.go:422 +0x308
github.com/cockroachdb/cockroach/sql.(*Executor).execStmt.func2(0xc82059cdc0, 0x1)
        /home/marc/cockroach/src/github.com/cockroachdb/cockroach/sql/executor.go:466 +0x121
github.com/cockroachdb/cockroach/client.(*Txn).exec(0xc82059cdc0, 0xc8201e03c8, 0x14)
        /home/marc/cockroach/src/github.com/cockroachdb/cockroach/client/txn.go:405 +0x2b2
github.com/cockroachdb/cockroach/client.(*DB).Txn(0xc820332a50, 0xc8201e03c8, 0x7f2946ac3400)
        /home/marc/cockroach/src/github.com/cockroachdb/cockroach/client/db.go:463 +0x15b
github.com/cockroachdb/cockroach/sql.(*Executor).execStmt(0xc820332a50, 0x7f2948305228, 0xc8205290e0, 0xc8206be000, 0x0,
 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /home/marc/cockroach/src/github.com/cockroachdb/cockroach/sql/executor.go:463 +0x600
github.com/cockroachdb/cockroach/sql.(*Executor).execStmts(0xc820332a50, 0xc820740000, 0x19, 0xc8206be000, 0x0, 0x0, 0x0
, 0x0, 0x0, 0x0)
        /home/marc/cockroach/src/github.com/cockroachdb/cockroach/sql/executor.go:318 +0x33d
github.com/cockroachdb/cockroach/sql.(*Executor).ExecuteStatements(0xc820332a50, 0xc8205cc00d, 0x4, 0x0, 0x0, 0x0, 0x0, 
0x0, 0x0, 0x0, ...)
        /home/marc/cockroach/src/github.com/cockroachdb/cockroach/sql/executor.go:266 +0x5e5
github.com/cockroachdb/cockroach/sql/pgwire.(*v3Conn).executeStatements(0xc8201781a0, 0xc820740000, 0x19, 0x0, 0x0, 0x0,
 0x0, 0x0, 0x0, 0x7f2944146001, ...)
        /home/marc/cockroach/src/github.com/cockroachdb/cockroach/sql/pgwire/v3.go:550 +0x1fb
github.com/cockroachdb/cockroach/sql/pgwire.(*v3Conn).handleSimpleQuery(0xc8201781a0, 0xc8201781d8, 0x0, 0x0)
        /home/marc/cockroach/src/github.com/cockroachdb/cockroach/sql/pgwire/v3.go:274 +0xc5
github.com/cockroachdb/cockroach/sql/pgwire.(*v3Conn).serve(0xc8201781a0, 0xc820595ea0, 0x0, 0x0)
        /home/marc/cockroach/src/github.com/cockroachdb/cockroach/sql/pgwire/v3.go:234 +0xf21
github.com/cockroachdb/cockroach/sql/pgwire.(*Server).serveConn(0xc82035e9c0, 0x7f2944106000, 0xc8205a6840, 0x0, 0x0)
        /home/marc/cockroach/src/github.com/cockroachdb/cockroach/sql/pgwire/server.go:198 +0x963
github.com/cockroachdb/cockroach/sql/pgwire.(*Server).serve.func1(0xc82035e9c0, 0x7f2944186028, 0xc82011e140)
        /home/marc/cockroach/src/github.com/cockroachdb/cockroach/sql/pgwire/server.go:109 +0x90
created by github.com/cockroachdb/cockroach/sql/pgwire.(*Server).serve
        /home/marc/cockroach/src/github.com/cockroachdb/cockroach/sql/pgwire/server.go:114 +0x20a
```

The non-debug version of `explain` works just fine.

### PR DESCRIPTION
**Pull request by RaduBerinde**
This change adds support for EXPLAIN (DEBUG) for select statements with
no table and for subqueries in the from claue.

Fixes #4060

[Review on Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/4114)

### CODE REVIEW

File: sql/values.go [hunk 1]
```diff
@@ -98,7 +98,7 @@ func (n *valuesNode) DebugValues() debugValues {
 	return debugValues{
 		rowIdx: n.nextRow - 1,
 		key:    fmt.Sprintf("%d", n.nextRow-1),
-		value:  n.rows[n.nextRow-1],
+		value:  parser.DString(n.rows[n.nextRow-1].String()),
```
Comment (tamird) [inline sql/values.go]: Why was this necessary?

**Comment by tamird** [comment]
LGTM

**Comment by RaduBerinde** [comment]
Review status: 0 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

*[sql/values.go, line 101 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4114#-K9cTDrUVMoldIB4_W73-r1-101:-K9cXyjjC5CXQvGFbphw:-1183578896) ([raw file](https://github.com/cockroachdb/cockroach/blob/07028cbd061b4983d35c9317570d4994450f5017/sql/values.go#L101)):*
TFTR! We were returning a DTuple for a string column (and checkResultDatum in executor doesn't like DTuple)

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4114)*

**Comment by tamird** [comment]
Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[sql/values.go, line 101 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4114#-K9cTDrUVMoldIB4_W73-r1-101:-K9c__f7RK-lwCz-csHn:-987257195) ([raw file](https://github.com/cockroachdb/cockroach/blob/07028cbd061b4983d35c9317570d4994450f5017/sql/values.go#L101)):*
hm. can we change the type in this struct to string or DString, then?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4114)*

**Comment by petermattis** [comment]
LGTM

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4114#-:-K9cbseXK9B2XJ1zIFyE:676834233)*

**Comment by RaduBerinde** [comment]
*[sql/values.go, line 101 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4114#-K9cTDrUVMoldIB4_W73-r1-101:-K9cccHtOCovkXfwZG4J:-838556494) ([raw file](https://github.com/cockroachdb/cockroach/blob/07028cbd061b4983d35c9317570d4994450f5017/sql/values.go#L101)):*
Good idea. Unfortunately, there is one place where we are using DNull though. On the other hand, in some cases we already convert DNull to a DString: https://github.com/cockroachdb/cockroach/blob/ceda0060764d2d2e8eea917e8753e3e8336b6fd4/sql/scan.go#L588
(explainValue can be DNull here).

This seems strange, I don't know why we care about the output formatting/escaping for EXPLAIN (DEBUG)

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4114)*

**Comment by RaduBerinde** [comment]
*[sql/values.go, line 101 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4114#-K9cTDrUVMoldIB4_W73-r1-101:-K9cgEo-OSb5S5UnHB3j:1825764204) ([raw file](https://github.com/cockroachdb/cockroach/blob/07028cbd061b4983d35c9317570d4994450f5017/sql/values.go#L101)):*
I can change the var to `DString` if I do `value:  parser.DString(parser.DNull.String()),` in`emptyNode`, which is strange but consistent with the above, should I do that?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4114)*

**Comment by tamird** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[sql/values.go, line 101 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4114#-K9cTDrUVMoldIB4_W73-r1-101:-K9cnxr_KwwtfxX-w1LC:-662093923) ([raw file](https://github.com/cockroachdb/cockroach/blob/07028cbd061b4983d35c9317570d4994450f5017/sql/values.go#L101)):*
Yeah, I think that's the way to go. I don't think there's any point to making it a DString - just make it a string.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4114)*

**Comment by RaduBerinde** [comment]
Review status: 1 of 5 files reviewed at latest revision, 1 unresolved discussion.

---

*[sql/values.go, line 101 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4114#-K9cTDrUVMoldIB4_W73-r1-101:-K9csFsIPi69_qruL2bC:-662793750) ([raw file](https://github.com/cockroachdb/cockroach/blob/07028cbd061b4983d35c9317570d4994450f5017/sql/values.go#L101)):*
Yup. Thanks!  Updated.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4114)*

**Comment by tamird** [comment]
Reviewed 4 of 4 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4114)*
