### PR TITLE
roachtest: update sstable-corruption test to not block on quorum

### LINKED ISSUE #99280: roachtest: sstable-corruption/table failed
roachtest.sstable-corruption/table [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/9182736?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/9182736?buildTab=artifacts#/sstable-corruption/table) on master @ [78bb7696847e1d8abf5d6a199c6dd3414a568691](https://github.com/cockroachdb/cockroach/commits/78bb7696847e1d8abf5d6a199c6dd3414a568691):

```
test artifacts and logs in: /artifacts/sstable-corruption/table/run_1
(test_runner.go:1008).runTest: test timed out (10h0m0s)
```
<p>Parameters: <code>ROACHTEST_cloud=gce</code>
, <code>ROACHTEST_cpu=4</code>
, <code>ROACHTEST_encrypted=false</code>
, <code>ROACHTEST_ssd=0</code>
</p>
<details><summary>Help</summary>
<p>

See: [roachtest README](https://github.com/cockroachdb/cockroach/blob/master/pkg/cmd/roachtest/README.md)

See: [How To Investigate \(internal\)](https://cockroachlabs.atlassian.net/l/c/SSSBr8c7)

</p>
</details>
/cc @cockroachdb/storage
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*sstable-corruption/table.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)
</sub>

Jira issue: CRDB-25804

### PR DESCRIPTION
**Pull request by jbowens**
Update the sstable-corruption roachtest to no longer set a new backup schedule when restarting the cluster after corrupting sstables. If corruption caused a quorum of nodes to exit asynchronously after startup, setting the new backup schedule would block indefinitely.

Closes #99280.
Epic: None
Release note: None

### CODE REVIEW

**Review by msbutler — APPROVED** [review]

File: pkg/cmd/roachtest/tests/sstable_corruption.go [hunk 1]
```diff
@@ -124,7 +124,7 @@ func runSSTableCorruption(ctx context.Context, t test.Test, c cluster.Cluster) {
 		}
 	}
 
-	if err := c.StartE(ctx, t.L(), option.DefaultStartOpts(), install.MakeClusterSettings(), crdbNodes); err != nil {
+	if err := c.StartE(ctx, t.L(), option.DefaultStartOpts(), install.MakeClusterSettings(), crdbNodes, option.DefaultStartOptsNoBackups); err != nil {
```
Comment (msbutler) [inline pkg/cmd/roachtest/tests/sstable_corruption.go:127]: you'll need to use `option.DefaultStartOptsNoBackups()`

**Comment by jbowens** [comment]
TFTR!

bors r=msbutler
