### PR TITLE
sql: fix ALTER INDEX IF EXISTS for non-existing index

### LINKED ISSUE #42399: ALTER INDEX IF EXISTS does not seem to work
**Describe the problem**

The syntax `ALTER INDEX IF EXISTS` does not seem to work. It seems its implementation was forgotten in https://github.com/cockroachdb/cockroach/issues/2034

**To Reproduce**

Run this statement:

```sql
alter index if exists i1 rename to i2;
```

I'm expecting it to be ignored, but I'm getting:

```
SQL Error [42704]: ERROR: index "i1" does not exist
```

**Environment:**
 - CockroachDB version: CockroachDB CCL v19.2.0-rc.4 (x86_64-unknown-linux-gnu, built 2019/11/05 20:40:29, go1.12.12)
 - Server OS: Linux in DOcker
 - Client app: JDBC

### PR DESCRIPTION
**Pull request by rafiss**
Previously, if ALTER INDEX IF EXISTS was used on an
unqualified index name that did not match any index, the database would
return an "index does not exist" error.

Now, the statement succeeds, but does nothing.

Also, test edge cases around ambiguous, non-existing, and/or unqualified
index names, in both alter_index and drop_index logic tests.

Fixes #42399 

Release note (bug fix): ALTER INDEX IF EXISTS no longer fails
when using an unqualified index name that does not match any existing
index. Now it is a no-op.

### CODE REVIEW

**Review by jordanlewis — APPROVED** [review]
:lgtm: seems backport worthy!

> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/42797#-:-LudFBzt-ZxwKjsiZg43:b6ks6hg)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @apantel)

File: pkg/sql/rename_index.go [hunk 1]
```diff
@@ -36,6 +36,10 @@ type renameIndexNode struct {
 func (p *planner) RenameIndex(ctx context.Context, n *tree.RenameIndex) (planNode, error) {
 	_, tableDesc, err := expandMutableIndexName(ctx, p, n.Index, true /* requireTable */)
```
Comment (apantel) [inline pkg/sql/rename_index.go]: Could you accomplish the same thing by passing requireTable=false here?

Comment (rafiss) [reply pkg/sql/rename_index.go]: I actually ended up making this more similar to drop_index.go, and set `requireTable=!n.IfExists`

**Review by apantel — COMMENTED** [review]
LGTM

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/42797#-:-LudoXmLEfJteEbrx84d:bb6ywmx)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @apantel and @jordanlewis)

**Comment by rafiss** [comment]
thanks for the reviews!

bors r+
