### PR TITLE
logical: external conn should not require db name

### LINKED ISSUE #152395: Bidirectional LDR incorrectly requires database name in external connnection
**Describe the problem**

When setting up bidirectional LDR with a non-root user, and if the database name is excluded from the external connection URL, the table relation cannot be found.

**To Reproduce**

These are the steps to reproduce a minimal bidirectional LDR using a non-root user:

```

# Node 1
SET CLUSTER SETTING kv.rangefeed.enabled = true;
CREATE DATABASE db1;
USE db1;
CREATE TABLE mytable (id UUID PRIMARY KEY);
INSERT INTO mytable SELECT gen_random_uuid() FROM generate_series(1, 10);
CREATE USER myuser WITH PASSWORD 'p';
GRANT REPLICATIONSOURCE ON TABLE mytable TO myuser;
GRANT REPLICATIONDEST ON TABLE mytable TO myuser;

# Node 2
SET CLUSTER SETTING kv.rangefeed.enabled = true;
CREATE DATABASE db2;
CREATE USER myuser WITH PASSWORD 'p';
GRANT CREATE ON DATABASE db2 TO myuser;
CREATE EXTERNAL CONNECTION source AS 'postgresql://myuser:p@172.28.128.21:26257/db1';

# Node 1
CREATE EXTERNAL CONNECTION target AS 'postgresql://myuser:p@172.28.128.22:26257/db2';

# Node 2 as myuser
CREATE LOGICALLY REPLICATED TABLE db2.public.mytable FROM TABLE db1.public.mytable ON 'external://source' WITH bidirectional ON 'external://target';
```

If the database name is removed from the external connection on the source cluster, eg:

```
CREATE EXTERNAL CONNECTION source AS 'postgresql://myuser:p@172.28.128.21:26257'; -- Note "/db1" now missing
```

then the replication fails on the destination cluster with the following message in the logs:

```
I250823 14:49:01.088845 6590 crosscluster/logical/logical_replication_job.go:906 ⋮ [T1,Vsystem,n1,job=LOGICAL REPLICATION id=1100644735231524865] 376  hit retryable error failed to start reverse stream: ‹ERROR: failed privilege check: table or system level REPLICATIONDEST privilege required: relation "mytable" does not exist (SQLSTATE 42P01)›
```

For some reason, this isn't a problem when using the `root` user for everything.

**Expected behavior**
Because we are specifying the fully-qualified target and source table names in the `CREATE LOGICALLY REPLICATED` command, then there should be no need to specify a database in the external connection string.

**Environment:**
 - CockroachDB version: v25.3

**Additional context**
Confusing error message making LDR difficult to set up.

Jira issue: CRDB-53813

Epic CRDB-53949

### PR DESCRIPTION
**Pull request by kev-cao**
LDR currently erroneously requires the db name in the external connection with setting up a bidirectional connection. This was determined to be caused by the fact that the privilege lookup on the source cluster was using unqualified table names during the reverse stream setup. This commit fixes the issue by using fully qualified table names.

Fixes: #152395

Release note: LDR no longer requires the database name to be specified in the external connection URI when setting up a bidirectional stream.

### CODE REVIEW

File: pkg/crosscluster/logical/create_logical_replication_stmt.go [hunk 1]
```diff
@@ -359,10 +359,12 @@ func (r *ResolvedDestObjects) TargetDescription() string {
 	return targetDescription
 }
 
+// TargetTableNames returns the fully qualified names of the resolved target
+// tables.
 func (r *ResolvedDestObjects) TargetTableNames() []string {
 	var targetTableNames []string
```
Comment (stevendanna) [inline pkg/crosscluster/logical/create_logical_replication_stmt.go]: I doubt it matters, but while we are here, we could use `make` here since we know the length.

**Review by msbutler — APPROVED** [review]
Nice!
