### PR TITLE
sqlccl: speed up partitioning tests

### LINKED ISSUE #21223: teamcity: failed tests on master: test/TestRestoreDatabaseVersusTable/incomplete-db, test/TestRestoreDatabaseVersusTable, testrace/TestRestoreDatabaseVersusTable, testrace/TestRestoreDatabaseVersusTable/incomplete-db
The following tests appear to have failed:

[#466249](https://teamcity.cockroachdb.com/viewLog.html?buildId=466249):

```
--- FAIL: test/TestRestoreDatabaseVersusTable/incomplete-db (0.000s)
Test ended in panic.

------- Stdout: -------
W180104 02:49:58.098479 148255 server/status/runtime.go:109  Could not parse build timestamp: parsing time "" as "2006/01/02 15:04:05": cannot parse "" as "2006"
I180104 02:49:58.100770 148255 server/config.go:516  [n?] 1 storage engine initialized
I180104 02:49:58.100790 148255 server/config.go:519  [n?] RocksDB cache size: 128 MiB
I180104 02:49:58.100795 148255 server/config.go:519  [n?] store 0: in-memory, size 0 B
I180104 02:49:58.103764 148255 server/node.go:361  [n?] **** cluster 77658f52-43ba-433a-9fa1-6a0248307bd7 has been created
I180104 02:49:58.103794 148255 server/server.go:934  [n?] **** add additional nodes by specifying --join=127.0.0.1:46647
I180104 02:49:58.105592 148255 storage/store.go:1209  [n1,s1] [n1,s1]: failed initial metrics computation: [n1,s1]: system config not yet available
I180104 02:49:58.105691 148255 server/node.go:486  [n1] initialized store [n1,s1]: disk (capacity=512 MiB, available=512 MiB, used=0 B, logicalBytes=3.2 KiB), ranges=1, leases=0, writes=0.00, bytesPerReplica={p10=3322.00 p25=3322.00 p50=3322.00 p75=3322.00 p90=3322.00}, writesPerReplica={p10=0.00 p25=0.00 p50=0.00 p75=0.00 p90=0.00}
I180104 02:49:58.105729 148255 server/node.go:339  [n1] node ID 1 initialized
I180104 02:49:58.105795 148255 gossip/gossip.go:332  [n1] NodeDescriptor set to node_id:1 address:<network_field:"tcp" address_field:"127.0.0.1:46647" > attrs:<> locality:<> ServerVersion:<major_val:1 minor_val:1 patch:0 unstable:8 > 
I180104 02:49:58.106400 148255 storage/stores.go:331  [n1] read 0 node addresses from persistent storage
I180104 02:49:58.106517 148255 server/node.go:627  [n1] connecting to gossip network to verify cluster ID...
I180104 02:49:58.107020 148255 server/node.go:652  [n1] node connected via gossip and verified as part of cluster "77658f52-43ba-433a-9fa1-6a0248307bd7"
I180104 02:49:58.107172 148255 server/node.go:428  [n1] node=1: started with [<no-attributes>=<in-mem>] engine(s) and attributes []
I180104 02:49:58.107290 148255 sql/distsql_physical_planner.go:122  [n1] creating DistSQLPlanner with address {tcp 127.0.0.1:46647}
I180104 02:49:58.108945 148435 storage/replica_command.go:819  [split,n1,s1,r1/1:/M{in-ax}] initiating a split of this range at key /System/"" [r2]
I180104 02:49:58.110556 148255 server/server.go:1161  [n1] starting https server at 127.0.0.1:42617
I180104 02:49:58.110590 148255 server/server.go:1162  [n1] starting grpc/postgres server at 127.0.0.1:46647
I180104 02:49:58.110601 148255 server/server.go:1163  [n1] advertising CockroachDB node at 127.0.0.1:46647
E180104 02:49:58.112073 148436 storage/queue.go:668  [replicate,n1,s1,r1/1:/{Min-System/}] range requires a replication change, but lacks a quorum of live replicas (0/1)
I180104 02:49:58.112715 148435 storage/replica_command.go:819  [split,n1,s1,r2/1:/{System/-Max}] initiating a split of this range at key /System/NodeLiveness [r3]
I180104 02:49:58.119791 148435 storage/replica_command.go:819  [split,n1,s1,r3/1:/{System/NodeL…-Max}] initiating a split of this range at key /System/NodeLivenessMax [r4]
I180104 02:49:58.122339 148255 sql/event_log.go:115  [n1] Event: "alter_table", target: 12, info: {TableName:eventlog Statement:ALTER TABLE system.eventlog ALTER COLUMN "uniqueID" SET DEFAULT uuid_v4() User:node MutationID:0 CascadeDroppedViews:[]}
I180104 02:49:58.124212 148435 storage/replica_command.go:819  [split,n1,s1,r4/1:/{System/NodeL…-Max}] initiating a split of this range at key /System/tsd [r5]
I180104 02:49:58.125855 148255 sql/lease.go:348  [n1] publish: descID=12 (eventlog) version=2 mtime=2018-01-04 02:49:58.125732444 +0000 UTC
I180104 02:49:58.128028 148435 storage/replica_command.go:819  [split,n1,s1,r5/1:/{System/tsd-Max}] initiating a split of this range at key /System/"tse" [r6]
I180104 02:49:58.138775 148435 storage/replica_command.go:819  [split,n1,s1,r6/1:/{System/tse-Max}] initiating a split of this range at key /Table/SystemConfigSpan/Start [r7]
I180104 02:49:58.143909 148435 storage/replica_command.go:819  [split,n1,s1,r7/1:/{Table/System…-Max}] initiating a split of this range at key /Table/11 [r8]
W180104 02:49:58.144093 148566 storage/intent_resolver.go:324  [n1,s1] failed to push during intent resolution: failed to push "sql txn implicit" id=d4829ca7 key=/Table/SystemConfigSpan/Start rw=true pri=0.02970770 iso=SERIALIZABLE stat=PENDING epo=0 ts=1515034198.140689776,0 orig=1515034198.140689776,0 max=1515034198.140689776,0 wto=false rop=false seq=7
I180104 02:49:58.145875 148255 sql/event_log.go:115  [n1] Event: "set_cluster_setting", target: 0, info: {SettingName:diagnostics.reporting.enabled Value:true User:node}
I180104 02:49:58.149060 148435 storage/replica_command.go:819  [split,n1,s1,r8/1:/{Table/11-Max}] initiating a split of this range at key /Table/12 [r9]
I180104 02:49:58.152930 148435 storage/replica_command.go:819  [split,n1,s1,r9/1:/{Table/12-Max}] initiating a split of this range at key /Table/13 [r10]
I180104 02:49:58.153891 148255 sql/event_log.go:115  [n1] Event: "set_cluster_setting", target: 0, info: {SettingName:version Value:$1 User:node}
I180104 02:49:58.157363 148435 storage/replica_command.go:819  [split,n1,s1,r10/1:/{Table/13-Max}] initiating a split of this range at key /Table/14 [r11]
I180104 02:49:58.157717 148255 sql/event_log.go:115  [n1] Event: "set_cluster_setting", target: 0, info: {SettingName:trace.debug.enable Value:false User:node}
I180104 02:49:58.161852 148435 storage/replica_command.go:819  [split,n1,s1,r11/1:/{Table/14-Max}] initiating a split of this range at key /Table/15 [r12]
I180104 02:49:58.165200 148435 storage/replica_command.go:819  [split,n1,s1,r12/1:/{Table/15-Max}] initiating a split of this range at key /Table/16 [r13]
I180104 02:49:58.168543 148435 storage/replica_command.go:819  [split,n1,s1,r13/1:/{Table/16-Max}] initiating a split of this range at key /Table/17 [r14]
I180104 02:49:58.169406 148255 sql/event_log.go:115  [n1] Event: "alter_table", target: 4, info: {TableName:users Statement:ALTER TABLE system.users ADD COLUMN IF NOT EXISTS "isRole" BOOL NOT NULL DEFAULT false User:node MutationID:1 CascadeDroppedViews:[]}
I180104 02:49:58.171454 148255 sql/lease.go:348  [n1] publish: descID=4 (users) version=2 mtime=2018-01-04 02:49:58.171351178 +0000 UTC
I180104 02:49:58.172506 148435 storage/replica_command.go:819  [split,n1,s1,r14/1:/{Table/17-Max}] initiating a split of this range at key /Table/18 [r15]
I180104 02:49:58.178399 148255 sql/lease.go:348  [n1] publish: descID=4 (users) version=3 mtime=2018-01-04 02:49:58.17828102 +0000 UTC
I180104 02:49:58.178503 148435 storage/replica_command.go:819  [split,n1,s1,r15/1:/{Table/18-Max}] initiating a split of this range at key /Table/19 [r16]
I180104 02:49:58.182624 148255 sql/backfill.go:132  [n1] Running backfill for "users", v=3, m=1
I180104 02:49:58.182885 148435 storage/replica_command.go:819  [split,n1,s1,r16/1:/{Table/19-Max}] initiating a split of this range at key /Table/20 [r17]
I180104 02:49:58.186393 148435 storage/replica_command.go:819  [split,n1,s1,r17/1:/{Table/20-Max}] initiating a split of this range at key /Table/21 [r18]
I180104 02:49:58.189436 148435 storage/replica_command.go:819  [split,n1,s1,r18/1:/{Table/21-Max}] initiating a split of this range at key /Table/22 [r19]
I180104 02:49:58.191902 148255 sql/lease.go:348  [n1] publish: descID=4 (users) version=4 mtime=2018-01-04 02:49:58.191661185 +0000 UTC
I180104 02:49:58.192639 148435 storage/replica_command.go:819  [split,n1,s1,r19/1:/{Table/22-Max}] initiating a split of this range at key /Table/23 [r20]
I180104 02:49:58.195481 148255 sql/event_log.go:115  [n1] Event: "finish_schema_change", target: 4, info: {MutationID:1}
I180104 02:49:58.196356 148255 sql/lease.go:274  publish (count leases): descID=4 name=users version=3 count=1
I180104 02:49:58.227296 148255 server/server.go:1232  [n1] done ensuring all necessary migrations have run
I180104 02:49:58.227333 148255 server/server.go:1235  [n1] serving sql connections
I180104 02:49:58.229290 148704 sql/event_log.go:115  [n1] Event: "node_join", target: 1, info: {Descriptor:{NodeID:1 Address:{NetworkField:tcp AddressField:127.0.0.1:46647} Attrs: Locality: ServerVersion:1.1-8} ClusterID:77658f52-43ba-433a-9fa1-6a0248307bd7 StartedAt:1515034198107036249 LastUp:1515034198107036249}
W180104 02:49:58.232347 148255 server/status/runtime.go:109  Could not parse build timestamp: parsing time "" as "2006/01/02 15:04:05": cannot parse "" as "2006"
I180104 02:49:58.234362 148255 server/config.go:516  [n?] 1 storage engine initialized
I180104 02:49:58.234382 148255 server/config.go:519  [n?] RocksDB cache size: 128 MiB
I180104 02:49:58.234388 148255 server/config.go:519  [n?] store 0: in-memory, size 0 B
W180104 02:49:58.234454 148255 gossip/gossip.go:1292  [n?] no incoming or outgoing connections
I180104 02:49:58.234483 148255 server/server.go:936  [n?] no stores bootstrapped and --join flag specified, awaiting init command.
I180104 02:49:58.247505 148741 gossip/client.go:129  [n?] started gossip client to 127.0.0.1:46647
I180104 02:49:58.248935 148682 gossip/server.go:219  [n1] received initial cluster-verification connection from {tcp 127.0.0.1:38087}
I180104 02:49:58.249941 148255 storage/stores.go:331  [n?] read 0 node addresses from persistent storage
I180104 02:49:58.249987 148255 storage/stores.go:350  [n?] wrote 1 node addresses to persistent storage
I180104 02:49:58.250002 148255 server/node.go:627  [n?] connecting to gossip network to verify cluster ID...
I180104 02:49:58.250023 148255 server/node.go:652  [n?] node connected via gossip and verified as part of cluster "77658f52-43ba-433a-9fa1-6a0248307bd7"
I180104 02:49:58.250262 148827 kv/dist_sender.go:354  [n?] unable to determine this node's attributes for replica selection; node is most likely bootstrapping
I180104 02:49:58.251123 148826 kv/dist_sender.go:354  [n?] unable to determine this node's attributes for replica selection; node is most likely bootstrapping
I180104 02:49:58.251986 148255 kv/dist_sender.go:354  [n?] unable to determine this node's attributes for replica selection; node is most likely bootstrapping
I180104 02:49:58.254035 148255 server/node.go:332  [n?] new node allocated ID 2
I180104 02:49:58.254110 148255 gossip/gossip.go:332  [n2] NodeDescriptor set to node_id:2 address:<network_field:"tcp" address_field:"127.0.0.1:38087" > attrs:<> locality:<> ServerVersion:<major_val:1 minor_val:1 patch:0 unstable:8 > 
I180104 02:49:58.254173 148255 server/node.go:414  [n2] node=2: asynchronously bootstrapping engine(s) [<no-attributes>=<in-mem>]
I180104 02:49:58.254195 148255 server/node.go:428  [n2] node=2: started with [] engine(s) and attributes []
I180104 02:49:58.254239 148255 sql/distsql_physical_planner.go:122  [n2] creating DistSQLPlanner with address {tcp 127.0.0.1:38087}
I180104 02:49:58.254854 148745 storage/stores.go:350  [n1] wrote 1 node addresses to persistent storage
I180104 02:49:58.255694 148830 server/node.go:608  [n2] bootstrapped store [n2,s2]
I180104 02:49:58.257001 148255 server/server.go:1161  [n2] starting https server at 127.0.0.1:43477
I180104 02:49:58.257026 148255 server/server.go:1162  [n2] starting grpc/postgres server at 127.0.0.1:38087
I180104 02:49:58.257037 148255 server/server.go:1163  [n2] advertising CockroachDB node at 127.0.0.1:38087
I180104 02:49:58.257799 148255 server/server.go:1232  [n2] done ensuring all necessary migrations have run
I180104 02:49:58.257826 148255 server/server.go:1235  [n2] serving sql connections
I180104 02:49:58.262717 148963 sql/event_log.go:115  [n2] Event: "node_join", target: 2, info: {Descriptor:{NodeID:2 Address:{NetworkField:tcp AddressField:127.0.0.1:38087} Attrs: Locality: ServerVersion:1.1-8} ClusterID:77658f52-43ba-433a-9fa1-6a0248307bd7 StartedAt:1515034198254186007 LastUp:1515034198254186007}
W180104 02:49:58.263706 148255 server/status/runtime.go:109  Could not parse build timestamp: parsing time "" as "2006/01/02 15:04:05": cannot parse "" as "2006"
I180104 02:49:58.268300 148255 server/config.go:516  [n?] 1 storage engine initialized
I180104 02:49:58.268326 148255 server/config.go:519  [n?] RocksDB cache size: 128 MiB
I180104 02:49:58.268333 148255 server/config.go:519  [n?] store 0: in-memory, size 0 B
W180104 02:49:58.268399 148255 gossip/gossip.go:1292  [n?] no incoming or outgoing connections
I180104 02:49:58.268506 148255 server/server.go:936  [n?] no stores bootstrapped and --join flag specified, awaiting init command.
panic: test timed out after 4m0s

goroutine 148763 [running]:
testing.startAlarm.func1()
	/usr/local/go/src/testing/testing.go:1145 +0xf9
created by time.goFunc
	/usr/local/go/src/time/sleep.go:170 +0x44

goroutine 1 [chan receive]:
testing.(*T).Run(0xc4200a0780, 0x22e8ddb, 0x1e, 0x23a27c0, 0x8c7a01)
	/usr/local/go/src/testing/testing.go:790 +0x2fc
testing.runTests.func1(0xc4200a0780)
	/usr/local/go/src/testing/testing.go:1004 +0x64
testing.tRunner(0xc4200a0780, 0xc4205b9db8)
	/usr/local/go/src/testing/testing.go:746 +0xd0
testing.runTests(0xc420233b60, 0x33936e0, 0x38, 0x38, 0x0)
	/usr/local/go/src/testing/testing.go:1002 +0x2d8
testing.(*M).Run(0xc420d11f18, 0xc420016450)
	/usr/local/go/src/testing/testing.go:921 +0x111
github.com/cockroachdb/cockroach/pkg/ccl/sqlccl.TestMain(0xc4205b9f18)
	/go/src/github.com/cockroachdb/cockroach/pkg/ccl/sqlccl/main_test.go:31 +0xda
main.main()
	github.com/cockroachdb/cockroach/pkg/ccl/sqlccl/_test/_testmain.go:172 +0xdb

goroutine 6 [chan receive]:
github.com/cockroachdb/cockroach/pkg/util/log.(*loggingT).flushDaemon(0x35e09e0)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/log/clog.go:1043 +0x81
created by github.com/cockroachdb/cockroach/pkg/util/log.init.0
	/go/src/github.com/cockroachdb/cockroach/pkg/util/log/clog.go:581 +0xbf

goroutine 19 [syscall, 4 minutes]:
os/signal.signal_recv(0x0)
	/usr/local/go/src/runtime/sigqueue.go:131 +0xa6
os/signal.loop()
	/usr/local/go/src/os/signal/signal_unix.go:22 +0x22
created by os/signal.init.0
	/usr/local/go/src/os/signal/signal_unix.go:28 +0x41

goroutine 147591 [chan receive]:
testing.(*T).Run(0xc424d4e960, 0x22ca781, 0xd, 0xc4247bdd40, 0x11)
	/usr/local/go/src/testing/testing.go:790 +0x2fc
github.com/cockroachdb/cockroach/pkg/ccl/sqlccl_test.TestRestoreDatabaseVersusTable(0xc424d4e960)
	/go/src/github.com/cockroachdb/cockroach/pkg/ccl/sqlccl/backup_test.go:2125 +0x5fa
testing.tRunner(0xc424d4e960, 0x23a27c0)
	/usr/local/go/src/testing/testing.go:746 +0xd0
created by testing.(*T).Run
	/usr/local/go/src/testing/testing.go:789 +0x2de

goroutine 148863 [select]:
github.com/cockroachdb/cockroach/pkg/sql.(*DistSQLPlanner).initRunners.func1(0x33be220, 0xc4226e6450)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsql_running.go:86 +0x167
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc4202d8ea0, 0xc422d7b170, 0xc4202d8e90)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:195 +0xf3
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:188 +0xad

goroutine 50 [select, locked to thread]:
runtime.gopark(0x23a6528, 0x0, 0x22c0058, 0x6, 0x18, 0x1)
	/usr/local/go/src/runtime/proc.go:277 +0x12c
runtime.selectgo(0xc420ddcf50, 0xc42050c420)
	/usr/local/go/src/runtime/select.go:395 +0x1138
runtime.ensureSigM.func1()
	/usr/local/go/src/runtime/signal_unix.go:511 +0x220
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:2337 +0x1

goroutine 148837 [select]:
github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/transport.(*http2Server).keepalive(0xc421ba8000)
	/go/src/github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/transport/http2_server.go:935 +0x264
created by github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/transport.newHTTP2Server
	/go/src/github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/transport/http2_server.go:230 +0x8fa

goroutine 148465 [select]:
github.com/cockroachdb/cockroach/pkg/sql.(*DistSQLPlanner).initRunners.func1(0x33be220, 0xc421280900)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsql_running.go:86 +0x167
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc42031e430, 0xc42251e090, 0xc42031e420)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:195 +0xf3
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:188 +0xad

goroutine 147844 [select]:
github.com/cockroachdb/cockroach/pkg/sql.(*SchemaChangeManager).Start.func1(0x33be220, 0xc421095650)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/schema_changer.go:1023 +0x9b6
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc4234e6750, 0xc4232bc750, 0xc420940360)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:195 +0xf3
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:188 +0xad

goroutine 148913 [semacquire]:
sync.runtime_notifyListWait(0xc422b8c3d0, 0xc400000023)
	/usr/local/go/src/runtime/sema.go:507 +0x110
sync.(*Cond).Wait(0xc422b8c3c0)
	/usr/local/go/src/sync/cond.go:56 +0x80
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).worker(0xc4226c0990, 0x33be220, 0xc4226e7cb0)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:197 +0x7c
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).Start.func2(0x33be220, 0xc4226e7cb0)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:166 +0x3e
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc421824620, 0xc422d7b170, 0xc421824610)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:195 +0xf3
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:188 +0xad

goroutine 147582 [IO wait]:
internal/poll.runtime_pollWait(0x2ac064248df0, 0x72, 0xffffffffffffffff)
	/usr/local/go/src/runtime/netpoll.go:173 +0x57
internal/poll.(*pollDesc).wait(0xc42366c198, 0x72, 0xc420dd6c00, 0x0, 0x0)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:85 +0xae
internal/poll.(*pollDesc).waitRead(0xc42366c198, 0xffffffffffffff00, 0x0, 0x0)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:90 +0x3d
internal/poll.(*FD).Accept(0xc42366c180, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/internal/poll/fd_unix.go:334 +0x1e2
net.(*netFD).accept(0xc42366c180, 0xc422e60388, 0x0, 0x0)
	/usr/local/go/src/net/fd_unix.go:238 +0x42
net.(*TCPListener).accept(0xc420b0e100, 0x14b30fa, 0x893100, 0xc420dd6e80)
	/usr/local/go/src/net/tcpsock_posix.go:136 +0x2e
net.(*TCPListener).Accept(0xc420b0e100, 0x23a49a0, 0xc420c45800, 0x33ca1c0, 0xc422e60388)
	/usr/local/go/src/net/tcpsock.go:247 +0x49
github.com/cockroachdb/cockroach/vendor/github.com/cockroachdb/cmux.(*cMux).Serve(0xc420c45800, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/vendor/github.com/cockroachdb/cmux/cmux.go:124 +0x95
github.com/cockroachdb/cockroach/pkg/server.(*Server).Start.func10.1()
	/go/src/github.com/cockroachdb/cockroach/pkg/server/server.go:965 +0x2f
sync.(*Once).Do(0xc4202cb630, 0xc421328f58)
	/usr/local/go/src/sync/once.go:44 +0xbe
github.com/cockroachdb/cockroach/pkg/server.(*Server).Start.func10(0x33be220, 0xc4225c0570)
	/go/src/github.com/cockroachdb/cockroach/pkg/server/server.go:964 +0x5b
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc4202a6060, 0xc4232bc750, 0xc422a8c020)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:195 +0xf3
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:188 +0xad

goroutine 148803 [select]:
github.com/cockroachdb/cockroach/pkg/gossip.(*Gossip).bootstrap.func1(0x33be220, 0xc420c08ba0)
	/go/src/github.com/cockroachdb/cockroach/pkg/gossip/gossip.go:1151 +0x331
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc4203038b0, 0xc422d7b170, 0xc4203038a0)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:195 +0xf3
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:188 +0xad

goroutine 148274 [select]:
github.com/cockroachdb/cockroach/pkg/kv.(*TxnCoordSender).printStatsLoop(0xc4249ce540, 0x33be220, 0xc42239c690)
	/go/src/github.com/cockroachdb/cockroach/pkg/kv/txn_coord_sender.go:253 +0x1a4
github.com/cockroachdb/cockroach/pkg/kv.NewTxnCoordSender.func1(0x33be220, 0xc42239c690)
	/go/src/github.com/cockroachdb/cockroach/pkg/kv/txn_coord_sender.go:237 +0x3e
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc42026c510, 0xc42251e090, 0xc42026c500)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:195 +0xf3
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:188 +0xad

goroutine 148407 [semacquire]:
sync.runtime_notifyListWait(0xc420e08550, 0xc400000154)
	/usr/local/go/src/runtime/sema.go:507 +0x110
sync.(*Cond).Wait(0xc420e08540)
	/usr/local/go/src/sync/cond.go:56 +0x80
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).worker(0xc42251f170, 0x33be220, 0xc422ea4060)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:197 +0x7c
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).Start.func2(0x33be220, 0xc422ea4060)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:166 +0x3e
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc420350b60, 0xc42251e090, 0xc420350b50)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:195 +0xf3
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:188 +0xad

goroutine 148380 [semacquire]:
sync.runtime_notifyListWait(0xc420e08550, 0xc400000132)
	/usr/local/go/src/runtime/sema.go:507 +0x110
sync.(*Cond).Wait(0xc420e08540)
	/usr/local/go/src/sync/cond.go:56 +0x80
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).worker(0xc42251f170, 0x33be220, 0xc422ea4240)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:197 +0x7c
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).Start.func2(0x33be220, 0xc422ea4240)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:166 +0x3e
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc420350590, 0xc42251e090, 0xc420350580)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:195 +0xf3
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:188 +0xad

goroutine 148374 [semacquire]:
sync.runtime_notifyListWait(0xc420e08550, 0xc400000135)
	/usr/local/go/src/runtime/sema.go:507 +0x110
sync.(*Cond).Wait(0xc420e08540)
	/usr/local/go/src/sync/cond.go:56 +0x80
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).worker(0xc42251f170, 0x33be220, 0xc421280510)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:197 +0x7c
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).Start.func2(0x33be220, 0xc421280510)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:166 +0x3e
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc4203504a0, 0xc42251e090, 0xc420350490)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:195 +0xf3
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:188 +0xad

goroutine 147558 [select]:
github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/transport.(*http2Server).keepalive(0xc420568420)
	/go/src/github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/transport/http2_server.go:935 +0x264
created by github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/transport.newHTTP2Server
	/go/src/github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/transport/http2_server.go:230 +0x8fa

goroutine 147837 [select]:
github.com/cockroachdb/cockroach/pkg/sql.(*DistSQLPlanner).initRunners.func1(0x33be220, 0xc4210955f0)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsql_running.go:86 +0x167
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc4234e6650, 0xc4232bc750, 0xc4234e6640)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:195 +0xf3
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:188 +0xad

goroutine 148466 [select]:
github.com/cockroachdb/cockroach/pkg/sql.(*DistSQLPlanner).initRunners.func1(0x33be220, 0xc421280930)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsql_running.go:86 +0x167
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc42031e450, 0xc42251e090, 0xc42031e440)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:195 +0xf3
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:188 +0xad

goroutine 148987 [IO wait]:
internal/poll.runtime_pollWait(0x2ac064248af0, 0x72, 0xffffffffffffffff)
	/usr/local/go/src/runtime/netpoll.go:173 +0x57
internal/poll.(*pollDesc).wait(0xc4200a2598, 0x72, 0xc42301a400, 0x0, 0x0)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:85 +0xae
internal/poll.(*pollDesc).waitRead(0xc4200a2598, 0xffffffffffffff00, 0x0, 0x0)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:90 +0x3d
internal/poll.(*FD).Accept(0xc4200a2580, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/internal/poll/fd_unix.go:334 +0x1e2
net.(*netFD).accept(0xc4200a2580, 0x2ac0641e5b20, 0x0, 0x2ac0642dd0a0)
	/usr/local/go/src/net/fd_unix.go:238 +0x42
net.(*TCPListener).accept(0xc420b3e1f8, 0xc42301a688, 0x10, 0x14b3007)
	/usr/local/go/src/net/tcpsock_posix.go:136 +0x2e
net.(*TCPListener).Accept(0xc420b3e1f8, 0x23a4998, 0xc4247bd300, 0xc4204242c0, 0xc42301a6d0)
	/usr/local/go/src/net/tcpsock.go:247 +0x49
github.com/cockroachdb/cockroach/vendor/github.com/cockroachdb/cmux.(*cMux).Serve(0xc4247bd300, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/vendor/github.com/cockroachdb/cmux/cmux.go:124 +0x95
github.com/cockroachdb/cockroach/pkg/server.(*Server).Start.func9.1()
	/go/src/github.com/cockroachdb/cockroach/pkg/server/server.go:944 +0x2f
sync.(*Once).Do(0xc420424100, 0xc42301a758)
	/usr/local/go/src/sync/once.go:44 +0xbe
github.com/cockroachdb/cockroach/pkg/server.(*Server).Start.func9(0x33be220, 0xc420604540)
	/go/src/github.com/cockroachdb/cockroach/pkg/server/server.go:943 +0x5b
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc42026c610, 0xc422322fc0, 0xc423b9c3e0)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:195 +0xf3
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:188 +0xad

goroutine 148823 [select]:
github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc.(*addrConn).transportMonitor(0xc42267a400)
	/go/src/github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/clientconn.go:1002 +0x166
github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc.(*addrConn).connect.func1(0xc42267a400)
	/go/src/github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/clientconn.go:703 +0x1ce
created by github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc.(*addrConn).connect
	/go/src/github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/clientconn.go:694 +0x40d

goroutine 148875 [select]:
github.com/cockroachdb/cockroach/pkg/sql/jobs.(*Registry).Start.func2(0x33be220, 0xc422c166c0)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/jobs/registry.go:205 +0x13b
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc42042c060, 0xc422d7b170, 0xc4243cac00)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:195 +0xf3
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:188 +0xad

goroutine 148870 [select]:
github.com/cockroachdb/cockroach/pkg/sql.(*Executor).Start.func1(0x33be220, 0xc4226e7b00)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/executor.go:416 +0x122
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc4202d9010, 0xc422d7b170, 0xc422453560)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:195 +0xf3
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:188 +0xad

goroutine 148883 [semacquire]:
sync.runtime_notifyListWait(0xc422b8c3d0, 0xc40000000a)
	/usr/local/go/src/runtime/sema.go:507 +0x110
sync.(*Cond).Wait(0xc422b8c3c0)
	/usr/local/go/src/sync/cond.go:56 +0x80
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).worker(0xc4226c0990, 0x33be220, 0xc422b99e90)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:197 +0x7c
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).Start.func2(0x33be220, 0xc422b99e90)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:166 +0x3e
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc421824260, 0xc422d7b170, 0xc421824250)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:195 +0xf3
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:188 +0xad

goroutine 148774 [select]:
github.com/cockroachdb/cockroach/pkg/kv.(*TxnCoordSender).printStatsLoop(0xc422681260, 0x33be220, 0xc420c08a80)
	/go/src/github.com/cockroachdb/cockroach/pkg/kv/txn_coord_sender.go:253 +0x1a4
github.com/cockroachdb/cockroach/pkg/kv.NewTxnCoordSender.func1(0x33be220, 0xc420c08a80)
	/go/src/github.com/cockroachdb/cockroach/pkg/kv/txn_coord_sender.go:237 +0x3e
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc420302e60, 0xc422d7b170, 0xc420302e50)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:195 +0xf3
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:188 +0xad

goroutine 147741 [semacquire]:
sync.runtime_notifyListWait(0xc421c7e290, 0xc40000020a)
	/usr/local/go/src/runtime/sema.go:507 +0x110
sync.(*Cond).Wait(0xc421c7e280)
	/usr/local/go/src/sync/cond.go:56 +0x80
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).worker(0xc423f28120, 0x33be220, 0xc4225c0930)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:197 +0x7c
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).Start.func2(0x33be220, 0xc4225c0930)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:166 +0x3e
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc4202a65b0, 0xc4232bc750, 0xc4202a65a0)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:195 +0xf3
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:188 +0xad

goroutine 148726 [select]:
github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/transport.loopyWriter(0x33be220, 0xc4211c5b60, 0xc4211c5b00, 0xc421755fb8)
	/go/src/github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/transport/transport.go:750 +0x2e4
github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/transport.newHTTP2Server.func1(0xc420ed8000)
	/go/src/github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/transport/http2_server.go:227 +0x5e
created by github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/transport.newHTTP2Server
	/go/src/github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/transport/http2_server.go:226 +0x8d5

goroutine 148456 [select]:
github.com/cockroachdb/cockroach/pkg/sql.(*DistSQLPlanner).initRunners.func1(0x33be220, 0xc421280720)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsql_running.go:86 +0x167
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc42031e2f0, 0xc42251e090, 0xc42031e2e0)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:195 +0xf3
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:188 +0xad

goroutine 148401 [semacquire]:
sync.runtime_notifyListWait(0xc420e08550, 0xc400000149)
	/usr/local/go/src/runtime/sema.go:507 +0x110
sync.(*Cond).Wait(0xc420e08540)
	/usr/local/go/src/sync/cond.go:56 +0x80
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).worker(0xc42251f170, 0x33be220, 0xc422ea5bc0)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:197 +0x7c
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).Start.func2(0x33be220, 0xc422ea5bc0)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:166 +0x3e
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc420350930, 0xc42251e090, 0xc420350910)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:195 +0xf3
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:188 +0xad

goroutine 147765 [semacquire]:
sync.runtime_notifyListWait(0xc421c7e290, 0xc4000001f8)
	/usr/local/go/src/runtime/sema.go:507 +0x110
sync.(*Cond).Wait(0xc421c7e280)
	/usr/local/go/src/sync/cond.go:56 +0x80
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).worker(0xc423f28120, 0x33be220, 0xc421094b70)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:197 +0x7c
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).Start.func2(0x33be220, 0xc421094b70)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:166 +0x3e
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc4202a6960, 0xc4232bc750, 0xc4202a6950)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:195 +0xf3
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:188 +0xad

goroutine 147610 [select]:
github.com/cockroachdb/cockroach/pkg/storage/idalloc.(*Allocator).start.func1(0x33be220, 0xc420e98780)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/idalloc/id_alloc.go:138 +0x6b4
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc423258200, 0xc4232bc750, 0xc4232581f0)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:195 +0xf3
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:188 +0xad

goroutine 147805 [select]:
github.com/cockroachdb/cockroach/pkg/storage/compactor.(*Compactor).Start.func1(0x33be220, 0xc422bcf3e0)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/compactor/compactor.go:128 +0x1ad
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc4202a6f90, 0xc4232bc750, 0xc422bcf380)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:195 +0xf3
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:188 +0xad

goroutine 147617 [IO wait]:
internal/poll.runtime_pollWait(0x2ac064248eb0, 0x72, 0x0)
	/usr/local/go/src/runtime/netpoll.go:173 +0x57
internal/poll.(*pollDesc).wait(0xc42242e198, 0x72, 0xffffffffffffff00, 0x33a87a0, 0x339b760)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:85 +0xae
internal/poll.(*pollDesc).waitRead(0xc42242e198, 0xc4234b6800, 0x400, 0x400)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:90 +0x3d
internal/poll.(*FD).Read(0xc42242e180, 0xc4234b6800, 0x400, 0x400, 0x0, 0x0, 0x0)
	/usr/local/go/src/internal/poll/fd_unix.go:125 +0x18a
net.(*netFD).Read(0xc42242e180, 0xc4234b6800, 0x400, 0x400, 0x0, 0x1d319cd67538f9df, 0xc42101a9c8)
	/usr/local/go/src/net/fd_unix.go:202 +0x52
net.(*conn).Read(0xc42000e068, 0xc4234b6800, 0x400, 0x400, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/net.go:176 +0x6d
crypto/tls.(*block).readFromUntil(0xc422e82000, 0x2ac066203000, 0xc42000e068, 0x5, 0xc42000e068, 0xc42101aa68)
	/usr/local/go/src/crypto/tls/conn.go:488 +0x95
crypto/tls.(*Conn).readRecord(0xc420c4ee00, 0x23a6617, 0xc420c4ef20, 0x84a477)
	/usr/local/go/src/crypto/tls/conn.go:590 +0xe0
crypto/tls.(*Conn).Read(0xc420c4ee00, 0xc422748000, 0x8000, 0x8000, 0x0, 0x0, 0x0)
	/usr/local/go/src/crypto/tls/conn.go:1134 +0x110
bufio.(*Reader).Read(0xc421cfc540, 0xc423dd6658, 0x9, 0x9, 0x0, 0x8644f8, 0xc4200de380)
	/usr/local/go/src/bufio/bufio.go:213 +0x30b
io.ReadAtLeast(0x339d620, 0xc421cfc540, 0xc423dd6658, 0x9, 0x9, 0x9, 0xc4202f2300, 0xc42101ae28, 0xd51b5e)
	/usr/local/go/src/io/io.go:309 +0x86
io.ReadFull(0x339d620, 0xc421cfc540, 0xc423dd6658, 0x9, 0x9, 0x23a5a80, 0x1800050100, 0xc400000001)
	/usr/local/go/src/io/io.go:327 +0x58
github.com/cockroachdb/cockroach/vendor/golang.org/x/net/http2.readFrameHeader(0xc423dd6658, 0x9, 0x9, 0x339d620, 0xc421cfc540, 0x0, 0x0, 0x0, 0xc420b0e020)
	/go/src/github.com/cockroachdb/cockroach/vendor/golang.org/x/net/http2/frame.go:237 +0x7b
github.com/cockroachdb/cockroach/vendor/golang.org/x/net/http2.(*Framer).ReadFrame(0xc423dd6620, 0xc4210c8630, 0xc4210c8630, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/vendor/golang.org/x/net/http2/frame.go:492 +0xa4
github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/transport.(*http2Client).reader(0xc422956900)
	/go/src/github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/transport/http2_client.go:1118 +0xbe
created by github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/transport.newHTTP2Client
	/go/src/github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/transport/http2_client.go:266 +0xc80

goroutine 148890 [semacquire]:
sync.runtime_notifyListWait(0xc422b8c3d0, 0xc400000011)
	/usr/local/go/src/runtime/sema.go:507 +0x110
sync.(*Cond).Wait(0xc422b8c3c0)
	/usr/local/go/src/sync/cond.go:56 +0x80
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).worker(0xc4226c0990, 0x33be220, 0xc420c08540)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:197 +0x7c
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).Start.func2(0x33be220, 0xc420c08540)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:166 +0x3e
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc421824340, 0xc422d7b170, 0xc421824330)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:195 +0xf3
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:188 +0xad

goroutine 147858 [select]:
github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/transport.loopyWriter(0x33be160, 0xc423d6a500, 0xc42054bc20, 0xc42101cfb8)
	/go/src/github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/transport/transport.go:750 +0x2e4
github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/transport.newHTTP2Client.func3(0xc422956900)
	/go/src/github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/transport/http2_client.go:298 +0x5e
created by github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/transport.newHTTP2Client
	/go/src/github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/transport/http2_client.go:297 +0xdd1

goroutine 148392 [semacquire]:
sync.runtime_notifyListWait(0xc420e08550, 0xc400000151)
	/usr/local/go/src/runtime/sema.go:507 +0x110
sync.(*Cond).Wait(0xc420e08540)
	/usr/local/go/src/sync/cond.go:56 +0x80
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).worker(0xc42251f170, 0x33be220, 0xc423b96570)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:197 +0x7c
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).Start.func2(0x33be220, 0xc423b96570)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:166 +0x3e
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc420350730, 0xc42251e090, 0xc420350710)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:195 +0xf3
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:188 +0xad

goroutine 148469 [select]:
github.com/cockroachdb/cockroach/pkg/sql.(*DistSQLPlanner).initRunners.func1(0x33be220, 0xc421280960)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsql_running.go:86 +0x167
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc42031e4c0, 0xc42251e090, 0xc42031e4a0)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:195 +0xf3
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:188 +0xad

goroutine 147794 [semacquire]:
sync.runtime_notifyListWait(0xc421c7e290, 0xc4000001e4)
	/usr/local/go/src/runtime/sema.go:507 +0x110
sync.(*Cond).Wait(0xc421c7e280)
	/usr/local/go/src/sync/cond.go:56 +0x80
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).worker(0xc423f28120, 0x33be220, 0xc421cdc750)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:197 +0x7c
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).Start.func2(0x33be220, 0xc421cdc750)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:166 +0x3e
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc4202a6d60, 0xc4232bc750, 0xc4202a6d50)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:195 +0xf3
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:188 +0xad

goroutine 147834 [select]:
github.com/cockroachdb/cockroach/pkg/sql.(*DistSQLPlanner).initRunners.func1(0x33be220, 0xc421095500)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsql_running.go:86 +0x167
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc4234e65e0, 0xc4232bc750, 0xc4234e65d0)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:195 +0xf3
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:188 +0xad

goroutine 148898 [semacquire]:
sync.runtime_notifyListWait(0xc422b8c3d0, 0xc40000001e)
	/usr/local/go/src/runtime/sema.go:507 +0x110
sync.(*Cond).Wait(0xc422b8c3c0)
	/usr/local/go/src/sync/cond.go:56 +0x80
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).worker(0xc4226c0990, 0x33be220, 0xc420c086f0)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:197 +0x7c
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).Start.func2(0x33be220, 0xc420c086f0)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:166 +0x3e
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc421824440, 0xc422d7b170, 0xc421824430)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:195 +0xf3
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:188 +0xad

goroutine 147827 [select]:
github.com/cockroachdb/cockroach/pkg/server.(*Node).startWriteSummaries.func1(0x33be220, 0xc4225c1110)
	/go/src/github.com/cockroachdb/cockroach/pkg/server/node.go:755 +0x1f6
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc4234e64d0, 0xc4232bc750, 0xc420940320)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:195 +0xf3
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:188 +0xad

goroutine 148797 [select]:
github.com/cockroachdb/cockroach/pkg/kv.(*TxnCoordSender).printStatsLoop(0xc4206ce460, 0x33be220, 0xc420c607b0)
	/go/src/github.com/cockroachdb/cockroach/pkg/kv/txn_coord_sender.go:253 +0x1a4
github.com/cockroachdb/cockroach/pkg/kv.NewTxnCoordSender.func1(0x33be220, 0xc420c607b0)
	/go/src/github.com/cockroachdb/cockroach/pkg/kv/txn_coord_sender.go:237 +0x3e
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc42026d6d0, 0xc422322fc0, 0xc42026d6c0)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:195 +0xf3
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:188 +0xad

goroutine 148888 [semacquire]:
sync.runtime_notifyListWait(0xc422b8c3d0, 0xc40000000e)
	/usr/local/go/src/runtime/sema.go:507 +0x110
sync.(*Cond).Wait(0xc422b8c3c0)
	/usr/local/go/src/sync/cond.go:56 +0x80
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).worker(0xc4226c0990, 0x33be220, 0xc420c084e0)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:197 +0x7c
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).Start.func2(0x33be220, 0xc420c084e0)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:166 +0x3e
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc421824300, 0xc422d7b170, 0xc4218242f0)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:195 +0xf3
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:188 +0xad

goroutine 148390 [semacquire]:
sync.runtime_notifyListWait(0xc420e08550, 0xc40000013e)
	/usr/local/go/src/runtime/sema.go:507 +0x110
sync.(*Cond).Wait(0xc420e08540)
	/usr/local/go/src/sync/cond.go:56 +0x80
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).worker(0xc42251f170, 0x33be220, 0xc422ea4300)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:197 +0x7c
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).Start.func2(0x33be220, 0xc422ea4300)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:166 +0x3e
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc4203506d0, 0xc42251e090, 0xc4203506c0)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:195 +0xf3
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:188 +0xad

goroutine 148814 [select]:
github.com/cockroachdb/cockroach/pkg/storage.(*baseQueue).processLoop.func1(0x33be220, 0xc422f581e0)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/queue.go:514 +0x1bb
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc42276c5f0, 0xc422d7b170, 0xc420452c20)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:195 +0xf3
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:188 +0xad

goroutine 148449 [select]:
github.com/cockroachdb/cockroach/pkg/storage.(*baseQueue).maybeAddToPurgatory.func2(0x33be220, 0xc420e017d0)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/queue.go:705 +0x434
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc4203e1760, 0xc42251e090, 0xc422acce00)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:195 +0xf3
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:188 +0xad

goroutine 147761 [semacquire]:
sync.runtime_notifyListWait(0xc421c7e290, 0xc40000020b)
	/usr/local/go/src/runtime/sema.go:507 +0x110
sync.(*Cond).Wait(0xc421c7e280)
	/usr/local/go/src/sync/cond.go:56 +0x80
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).worker(0xc423f28120, 0x33be220, 0xc421cdc3c0)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:197 +0x7c
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).Start.func2(0x33be220, 0xc421cdc3c0)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:166 +0x3e
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc4202a6870, 0xc4232bc750, 0xc4202a6850)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:195 +0xf3
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:188 +0xad

goroutine 148741 [select]:
github.com/cockroachdb/cockroach/pkg/gossip.(*client).gossip(0xc42386d520, 0x33be220, 0xc420c08c60, 0xc42234db00, 0x33c97a0, 0xc421ad0000, 0xc422d7b170, 0xc42439a690, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/pkg/gossip/client.go:323 +0x350
github.com/cockroachdb/cockroach/pkg/gossip.(*client).startLocked.func1(0x33be220, 0xc420c08c60)
	/go/src/github.com/cockroachdb/cockroach/pkg/gossip/client.go:130 +0x3cd
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc423258780, 0xc422d7b170, 0xc42324b5c0)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:195 +0xf3
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:188 +0xad

goroutine 148833 [select]:
github.com/cockroachdb/cockroach/pkg/server.(*Server).refreshSettings.func2(0x33be220, 0xc4226e60f0)
	/go/src/github.com/cockroachdb/cockroach/pkg/server/settingsworker.go:112 +0x2db
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc4202d8bc0, 0xc422d7b170, 0xc4224534c0)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:195 +0xf3
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:188 +0xad

goroutine 148025 [select]:
github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/transport.(*http2Server).keepalive(0xc42325a160)
	/go/src/github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/transport/http2_server.go:935 +0x264
created by github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/transport.newHTTP2Server
	/go/src/github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/transport/http2_server.go:230 +0x8fa

goroutine 148460 [select]:
github.com/cockroachdb/cockroach/pkg/sql.(*DistSQLPlanner).initRunners.func1(0x33be220, 0xc4212807e0)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsql_running.go:86 +0x167
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc42031e390, 0xc42251e090, 0xc42031e370)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:195 +0xf3
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:188 +0xad

goroutine 148283 [chan receive]:
github.com/cockroachdb/cockroach/vendor/github.com/cockroachdb/cmux.muxListener.Accept(...)
	/go/src/github.com/cockroachdb/cockroach/vendor/github.com/cockroachdb/cmux/cmux.go:184
github.com/cockroachdb/cockroach/vendor/github.com/cockroachdb/cmux.(*muxListener).Accept(0xc420316fc0, 0x23a5908, 0xc4212c5900, 0x33c9fe0, 0xc42074c000)
	<autogenerated>:1 +0x65
github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc.(*Server).Serve(0xc4212c5900, 0x33bd3a0, 0xc420316fc0, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/server.go:463 +0x196
github.com/cockroachdb/cockroach/pkg/server.(*Server).Start.func7(0x33be220, 0xc42239c9c0)
	/go/src/github.com/cockroachdb/cockroach/pkg/server/server.go:795 +0x43
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc42026ca50, 0xc42251e090, 0xc4203170e0)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:195 +0xf3
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:188 +0xad

goroutine 148930 [semacquire]:
sync.runtime_notifyListWait(0xc422b8c3d0, 0xc400000036)
	/usr/local/go/src/runtime/sema.go:507 +0x110
sync.(*Cond).Wait(0xc422b8c3c0)
	/usr/local/go/src/sync/cond.go:56 +0x80
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).worker(0xc4226c0990, 0x33be220, 0xc420c088d0)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:197 +0x7c
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).Start.func2(0x33be220, 0xc420c088d0)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:166 +0x3e
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc421824850, 0xc422d7b170, 0xc421824840)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:195 +0xf3
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:188 +0xad

goroutine 148359 [IO wait]:
internal/poll.runtime_pollWait(0x2ac064290848, 0x72, 0xffffffffffffffff)
	/usr/local/go/src/runtime/netpoll.go:173 +0x57
internal/poll.(*pollDesc).wait(0xc4200a3a18, 0x72, 0xc422a22c00, 0x0, 0x0)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:85 +0xae
internal/poll.(*pollDesc).waitRead(0xc4200a3a18, 0xffffffffffffff00, 0x0, 0x0)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:90 +0x3d
internal/poll.(*FD).Accept(0xc4200a3a00, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/internal/poll/fd_unix.go:334 +0x1e2
net.(*netFD).accept(0xc4200a3a00, 0xc420484098, 0x0, 0x0)
	/usr/local/go/src/net/fd_unix.go:238 +0x42
net.(*TCPListener).accept(0xc420612b20, 0x14b30fa, 0x893100, 0xc422a22e80)
	/usr/local/go/src/net/tcpsock_posix.go:136 +0x2e
net.(*TCPListener).Accept(0xc420612b20, 0x23a49a0, 0xc4227f8f00, 0x33ca1c0, 0xc420484098)
	/usr/local/go/src/net/tcpsock.go:247 +0x49
github.com/cockroachdb/cockroach/vendor/github.com/cockroachdb/cmux.(*cMux).Serve(0xc4227f8f00, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/vendor/github.com/cockroachdb/cmux/cmux.go:124 +0x95
github.com/cockroachdb/cockroach/pkg/server.(*Server).Start.func10.1()
	/go/src/github.com/cockroachdb/cockroach/pkg/server/server.go:965 +0x2f
sync.(*Once).Do(0xc420268220, 0xc420ada758)
	/usr/local/go/src/sync/once.go:44 +0xbe
github.com/cockroachdb/cockroach/pkg/server.(*Server).Start.func10(0x33be220, 0xc422ea5b90)
	/go/src/github.com/cockroachdb/cockroach/pkg/server/server.go:964 +0x5b
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc42026df60, 0xc42251e090, 0xc420317f00)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:195 +0xf3
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:188 +0xad

goroutine 148703 [chan receive]:
github.com/cockroachdb/cockroach/vendor/github.com/cockroachdb/cmux.muxListener.Accept(...)
	/go/src/github.com/cockroachdb/cockroach/vendor/github.com/cockroachdb/cmux/cmux.go:184
github.com/cockroachdb/cockroach/vendor/github.com/cockroachdb/cmux.(*muxListener).Accept(0xc420316fa0, 0x2ac06433c268, 0x0, 0x30, 0xc420767180)
	<autogenerated>:1 +0x65
github.com/cockroachdb/cockroach/pkg/util/netutil.(*Server).ServeWith(0xc420612b10, 0x33be220, 0xc4243ca3c0, 0xc42251e090, 0x33bd3a0, 0xc420316fa0, 0xc4243ca3f0, 0xc4243ca3c0, 0xc420a926d0)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/netutil/net.go:119 +0x50
github.com/cockroachdb/cockroach/pkg/server.(*Server).Start.func17(0x33be220, 0xc4243ca3c0)
	/go/src/github.com/cockroachdb/cockroach/pkg/server/server.go:1245 +0x1f5
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc4236e5f30, 0xc42251e090, 0xc421831f00)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:195 +0xf3
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:188 +0xad

goroutine 147779 [semacquire]:
sync.runtime_notifyListWait(0xc421c7e290, 0xc4000001e3)
	/usr/local/go/src/runtime/sema.go:507 +0x110
sync.(*Cond).Wait(0xc421c7e280)
	/usr/local/go/src/sync/cond.go:56 +0x80
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).worker(0xc423f28120, 0x33be220, 0xc4225c0cc0)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:197 +0x7c
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).Start.func2(0x33be220, 0xc4225c0cc0)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:166 +0x3e
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc4202a6b40, 0xc4232bc750, 0xc4202a6b30)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:195 +0xf3
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:188 +0xad

goroutine 148384 [semacquire]:
sync.runtime_notifyListWait(0xc420e08550, 0xc400000139)
	/usr/local/go/src/runtime/sema.go:507 +0x110
sync.(*Cond).Wait(0xc420e08540)
	/usr/local/go/src/sync/cond.go:56 +0x80
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).worker(0xc42251f170, 0x33be220, 0xc421280570)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:197 +0x7c
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).Start.func2(0x33be220, 0xc421280570)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:166 +0x3e
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc420350610, 0xc42251e090, 0xc420350600)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:195 +0xf3
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:188 +0xad

goroutine 148399 [semacquire]:
sync.runtime_notifyListWait(0xc420e08550, 0xc40000014f)
	/usr/local/go/src/runtime/sema.go:507 +0x110
sync.(*Cond).Wait(0xc420e08540)
	/usr/local/go/src/sync/cond.go:56 +0x80
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).worker(0xc42251f170, 0x33be220, 0xc4212800f0)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:197 +0x7c
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).Start.func2(0x33be220, 0xc4212800f0)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:166 +0x3e
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc420350870, 0xc42251e090, 0xc420350860)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:195 +0xf3
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWo
```

Please assign, take a look and update the issue accordingly.

### LINKED ISSUE #21235: teamcity: failed tests on master: test/TestTimestampMismatch, testrace/TestTimestampMismatch
The following tests appear to have failed:

[#467083](https://teamcity.cockroachdb.com/viewLog.html?buildId=467083):

```
--- FAIL: test/TestTimestampMismatch (0.000s)
Test ended in panic.

------- Stdout: -------
W180104 18:29:22.854647 139653 server/status/runtime.go:109  Could not parse build timestamp: parsing time "" as "2006/01/02 15:04:05": cannot parse "" as "2006"
I180104 18:29:22.856565 139653 server/config.go:516  [n?] 1 storage engine initialized
I180104 18:29:22.856589 139653 server/config.go:519  [n?] RocksDB cache size: 128 MiB
I180104 18:29:22.856598 139653 server/config.go:519  [n?] store 0: in-memory, size 0 B
I180104 18:29:22.859327 139653 server/node.go:361  [n?] **** cluster 4e44d876-f731-4aba-9209-320fc8fd952d has been created
I180104 18:29:22.859365 139653 server/server.go:934  [n?] **** add additional nodes by specifying --join=127.0.0.1:40651
I180104 18:29:22.860088 139653 storage/store.go:1209  [n1,s1] [n1,s1]: failed initial metrics computation: [n1,s1]: system config not yet available
I180104 18:29:22.860136 139653 server/node.go:486  [n1] initialized store [n1,s1]: disk (capacity=512 MiB, available=512 MiB, used=0 B, logicalBytes=3.2 KiB), ranges=1, leases=0, writes=0.00, bytesPerReplica={p10=3322.00 p25=3322.00 p50=3322.00 p75=3322.00 p90=3322.00}, writesPerReplica={p10=0.00 p25=0.00 p50=0.00 p75=0.00 p90=0.00}
I180104 18:29:22.860158 139653 server/node.go:339  [n1] node ID 1 initialized
I180104 18:29:22.860235 139653 gossip/gossip.go:332  [n1] NodeDescriptor set to node_id:1 address:<network_field:"tcp" address_field:"127.0.0.1:40651" > attrs:<> locality:<> ServerVersion:<major_val:1 minor_val:1 patch:0 unstable:8 > 
I180104 18:29:22.861994 139653 storage/stores.go:331  [n1] read 0 node addresses from persistent storage
I180104 18:29:22.862160 139653 server/node.go:627  [n1] connecting to gossip network to verify cluster ID...
I180104 18:29:22.862359 139653 server/node.go:652  [n1] node connected via gossip and verified as part of cluster "4e44d876-f731-4aba-9209-320fc8fd952d"
I180104 18:29:22.862425 139653 server/node.go:428  [n1] node=1: started with [<no-attributes>=<in-mem>] engine(s) and attributes []
I180104 18:29:22.862523 139653 sql/distsql_physical_planner.go:122  [n1] creating DistSQLPlanner with address {tcp 127.0.0.1:40651}
I180104 18:29:22.864672 139734 storage/replica_command.go:819  [split,n1,s1,r1/1:/M{in-ax}] initiating a split of this range at key /System/"" [r2]
I180104 18:29:22.866084 139653 server/server.go:1161  [n1] starting https server at 127.0.0.1:38353
I180104 18:29:22.866111 139653 server/server.go:1162  [n1] starting grpc/postgres server at 127.0.0.1:40651
I180104 18:29:22.866120 139653 server/server.go:1163  [n1] advertising CockroachDB node at 127.0.0.1:40651
I180104 18:29:22.874728 139734 storage/replica_command.go:819  [split,n1,s1,r2/1:/{System/-Max}] initiating a split of this range at key /System/NodeLiveness [r3]
I180104 18:29:22.878164 139734 storage/replica_command.go:819  [split,n1,s1,r3/1:/{System/NodeL…-Max}] initiating a split of this range at key /System/NodeLivenessMax [r4]
W180104 18:29:22.878671 139632 storage/intent_resolver.go:324  [n1,s1] failed to push during intent resolution: failed to push "sql txn implicit" id=519fa74f key=/Table/SystemConfigSpan/Start rw=true pri=0.04014126 iso=SERIALIZABLE stat=PENDING epo=0 ts=1515090562.875722841,0 orig=1515090562.875722841,0 max=1515090562.875722841,0 wto=false rop=false seq=7
I180104 18:29:22.880169 139653 sql/event_log.go:115  [n1] Event: "alter_table", target: 12, info: {TableName:eventlog Statement:ALTER TABLE system.eventlog ALTER COLUMN "uniqueID" SET DEFAULT uuid_v4() User:node MutationID:0 CascadeDroppedViews:[]}
I180104 18:29:22.882912 139734 storage/replica_command.go:819  [split,n1,s1,r4/1:/{System/NodeL…-Max}] initiating a split of this range at key /System/tsd [r5]
I180104 18:29:22.884294 139653 sql/lease.go:348  [n1] publish: descID=12 (eventlog) version=2 mtime=2018-01-04 18:29:22.884133665 +0000 UTC
I180104 18:29:22.887308 139734 storage/replica_command.go:819  [split,n1,s1,r5/1:/{System/tsd-Max}] initiating a split of this range at key /System/"tse" [r6]
I180104 18:29:22.894996 139734 storage/replica_command.go:819  [split,n1,s1,r6/1:/{System/tse-Max}] initiating a split of this range at key /Table/SystemConfigSpan/Start [r7]
I180104 18:29:22.899290 139734 storage/replica_command.go:819  [split,n1,s1,r7/1:/{Table/System…-Max}] initiating a split of this range at key /Table/11 [r8]
W180104 18:29:22.899556 139989 storage/intent_resolver.go:324  [n1,s1] failed to push during intent resolution: failed to push "sql txn implicit" id=6a1d46ad key=/Table/SystemConfigSpan/Start rw=true pri=0.07436965 iso=SERIALIZABLE stat=PENDING epo=0 ts=1515090562.896734615,0 orig=1515090562.896734615,0 max=1515090562.896734615,0 wto=false rop=false seq=7
I180104 18:29:22.901400 139653 sql/event_log.go:115  [n1] Event: "set_cluster_setting", target: 0, info: {SettingName:diagnostics.reporting.enabled Value:true User:node}
I180104 18:29:22.903668 139734 storage/replica_command.go:819  [split,n1,s1,r8/1:/{Table/11-Max}] initiating a split of this range at key /Table/12 [r9]
I180104 18:29:22.907364 139734 storage/replica_command.go:819  [split,n1,s1,r9/1:/{Table/12-Max}] initiating a split of this range at key /Table/13 [r10]
I180104 18:29:22.909906 139653 sql/event_log.go:115  [n1] Event: "set_cluster_setting", target: 0, info: {SettingName:version Value:$1 User:node}
I180104 18:29:22.912117 139734 storage/replica_command.go:819  [split,n1,s1,r10/1:/{Table/13-Max}] initiating a split of this range at key /Table/14 [r11]
I180104 18:29:22.913886 139653 sql/event_log.go:115  [n1] Event: "set_cluster_setting", target: 0, info: {SettingName:trace.debug.enable Value:false User:node}
I180104 18:29:22.916670 139734 storage/replica_command.go:819  [split,n1,s1,r11/1:/{Table/14-Max}] initiating a split of this range at key /Table/15 [r12]
I180104 18:29:22.919848 139734 storage/replica_command.go:819  [split,n1,s1,r12/1:/{Table/15-Max}] initiating a split of this range at key /Table/16 [r13]
I180104 18:29:22.924563 139734 storage/replica_command.go:819  [split,n1,s1,r13/1:/{Table/16-Max}] initiating a split of this range at key /Table/17 [r14]
I180104 18:29:22.928232 139653 sql/event_log.go:115  [n1] Event: "alter_table", target: 4, info: {TableName:users Statement:ALTER TABLE system.users ADD COLUMN IF NOT EXISTS "isRole" BOOL NOT NULL DEFAULT false User:node MutationID:1 CascadeDroppedViews:[]}
I180104 18:29:22.928740 139734 storage/replica_command.go:819  [split,n1,s1,r14/1:/{Table/17-Max}] initiating a split of this range at key /Table/18 [r15]
I180104 18:29:22.930784 139653 sql/lease.go:348  [n1] publish: descID=4 (users) version=2 mtime=2018-01-04 18:29:22.930514239 +0000 UTC
I180104 18:29:22.931906 139734 storage/replica_command.go:819  [split,n1,s1,r15/1:/{Table/18-Max}] initiating a split of this range at key /Table/19 [r16]
I180104 18:29:22.937237 139734 storage/replica_command.go:819  [split,n1,s1,r16/1:/{Table/19-Max}] initiating a split of this range at key /Table/20 [r17]
I180104 18:29:22.937967 139653 sql/lease.go:348  [n1] publish: descID=4 (users) version=3 mtime=2018-01-04 18:29:22.93787144 +0000 UTC
I180104 18:29:22.941348 139734 storage/replica_command.go:819  [split,n1,s1,r17/1:/{Table/20-Max}] initiating a split of this range at key /Table/21 [r18]
I180104 18:29:22.942696 139653 sql/backfill.go:132  [n1] Running backfill for "users", v=3, m=1
I180104 18:29:22.944687 139734 storage/replica_command.go:819  [split,n1,s1,r18/1:/{Table/21-Max}] initiating a split of this range at key /Table/22 [r19]
I180104 18:29:22.948168 139734 storage/replica_command.go:819  [split,n1,s1,r19/1:/{Table/22-Max}] initiating a split of this range at key /Table/23 [r20]
I180104 18:29:22.951871 139653 sql/lease.go:348  [n1] publish: descID=4 (users) version=4 mtime=2018-01-04 18:29:22.951762653 +0000 UTC
I180104 18:29:22.955360 139653 sql/event_log.go:115  [n1] Event: "finish_schema_change", target: 4, info: {MutationID:1}
I180104 18:29:22.956183 139653 sql/lease.go:274  publish (count leases): descID=4 name=users version=3 count=1
panic: test timed out after 4m0s

goroutine 139984 [running]:
testing.startAlarm.func1()
	/usr/local/go/src/testing/testing.go:1145 +0xf9
created by time.goFunc
	/usr/local/go/src/time/sleep.go:170 +0x44

goroutine 1 [chan receive]:
testing.(*T).Run(0xc4200a0780, 0x22d7222, 0x15, 0x23a2ad0, 0x8c7a01)
	/usr/local/go/src/testing/testing.go:790 +0x2fc
testing.runTests.func1(0xc4200a0780)
	/usr/local/go/src/testing/testing.go:1004 +0x64
testing.tRunner(0xc4200a0780, 0xc4205a9db8)
	/usr/local/go/src/testing/testing.go:746 +0xd0
testing.runTests(0xc4204525c0, 0x33946e0, 0x38, 0x38, 0x0)
	/usr/local/go/src/testing/testing.go:1002 +0x2d8
testing.(*M).Run(0xc420cf7f18, 0xc42022d5b0)
	/usr/local/go/src/testing/testing.go:921 +0x111
github.com/cockroachdb/cockroach/pkg/ccl/sqlccl.TestMain(0xc4205a9f18)
	/go/src/github.com/cockroachdb/cockroach/pkg/ccl/sqlccl/main_test.go:31 +0xda
main.main()
	github.com/cockroachdb/cockroach/pkg/ccl/sqlccl/_test/_testmain.go:172 +0xdb

goroutine 6 [chan receive]:
github.com/cockroachdb/cockroach/pkg/util/log.(*loggingT).flushDaemon(0x35e19e0)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/log/clog.go:1043 +0x81
created by github.com/cockroachdb/cockroach/pkg/util/log.init.0
	/go/src/github.com/cockroachdb/cockroach/pkg/util/log/clog.go:581 +0xbf

goroutine 14 [syscall, 4 minutes]:
os/signal.signal_recv(0x0)
	/usr/local/go/src/runtime/sigqueue.go:131 +0xa6
os/signal.loop()
	/usr/local/go/src/os/signal/signal_unix.go:22 +0x22
created by os/signal.init.0
	/usr/local/go/src/os/signal/signal_unix.go:28 +0x41

goroutine 139687 [select]:
github.com/cockroachdb/cockroach/pkg/storage/idalloc.(*Allocator).start.func1(0x33bf220, 0xc42421c2a0)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/idalloc/id_alloc.go:138 +0x6b4
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc4204120a0, 0xc423bf45a0, 0xc420412090)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:195 +0xf3
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:188 +0xad

goroutine 50 [select, locked to thread]:
runtime.gopark(0x23a6808, 0x0, 0x22c0338, 0x6, 0x18, 0x1)
	/usr/local/go/src/runtime/proc.go:277 +0x12c
runtime.selectgo(0xc420950f50, 0xc420440480)
	/usr/local/go/src/runtime/select.go:395 +0x1138
runtime.ensureSigM.func1()
	/usr/local/go/src/runtime/signal_unix.go:511 +0x220
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:2337 +0x1

goroutine 139902 [semacquire]:
sync.runtime_notifyListWait(0xc423ceecd0, 0xc400000126)
	/usr/local/go/src/runtime/sema.go:507 +0x110
sync.(*Cond).Wait(0xc423ceecc0)
	/usr/local/go/src/sync/cond.go:56 +0x80
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).worker(0xc421f830e0, 0x33bf220, 0xc420be4990)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:197 +0x7c
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).Start.func2(0x33bf220, 0xc420be4990)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:166 +0x3e
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc4202252a0, 0xc423bf45a0, 0xc420225290)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:195 +0xf3
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:188 +0xad

goroutine 139933 [select]:
github.com/cockroachdb/cockroach/pkg/sql.(*DistSQLPlanner).initRunners.func1(0x33bf220, 0xc422ab5e30)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsql_running.go:86 +0x167
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc424ba58e0, 0xc423bf45a0, 0xc424ba58d0)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:195 +0xf3
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:188 +0xad

goroutine 139705 [select]:
github.com/cockroachdb/cockroach/pkg/server.(*Node).startComputePeriodicMetrics.func1(0x33bf220, 0xc420f5ec90)
	/go/src/github.com/cockroachdb/cockroach/pkg/server/node.go:718 +0x14f
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc424ba55e0, 0xc423bf45a0, 0xc421913e00)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:195 +0xf3
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:188 +0xad

goroutine 139924 [select]:
github.com/cockroachdb/cockroach/pkg/sql.(*DistSQLPlanner).initRunners.func1(0x33bf220, 0xc423a2acf0)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsql_running.go:86 +0x167
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc424ba57c0, 0xc423bf45a0, 0xc424ba57b0)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:195 +0xf3
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:188 +0xad

goroutine 139895 [semacquire]:
sync.runtime_notifyListWait(0xc423ceecd0, 0xc400000129)
	/usr/local/go/src/runtime/sema.go:507 +0x110
sync.(*Cond).Wait(0xc423ceecc0)
	/usr/local/go/src/sync/cond.go:56 +0x80
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).worker(0xc421f830e0, 0x33bf220, 0xc420be4a50)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:197 +0x7c
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).Start.func2(0x33bf220, 0xc420be4a50)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:166 +0x3e
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc4202251c0, 0xc423bf45a0, 0xc4202251b0)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:195 +0xf3
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:188 +0xad

goroutine 139869 [semacquire]:
sync.runtime_notifyListWait(0xc423ceecd0, 0xc40000010a)
	/usr/local/go/src/runtime/sema.go:507 +0x110
sync.(*Cond).Wait(0xc423ceecc0)
	/usr/local/go/src/sync/cond.go:56 +0x80
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).worker(0xc421f830e0, 0x33bf220, 0xc423e4ae70)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:197 +0x7c
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).Start.func2(0x33bf220, 0xc423e4ae70)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:166 +0x3e
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc4203abdc0, 0xc423bf45a0, 0xc4203abdb0)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:195 +0xf3
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:188 +0xad

goroutine 139660 [chan receive]:
github.com/cockroachdb/cockroach/pkg/server.(*Server).Start.func2(0x33bf220, 0xc4238bae10)
	/go/src/github.com/cockroachdb/cockroach/pkg/server/server.go:748 +0x53
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc4202ef280, 0xc423bf45a0, 0xc422570ee0)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:195 +0xf3
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:188 +0xad

goroutine 139928 [select]:
github.com/cockroachdb/cockroach/pkg/sql.(*DistSQLPlanner).initRunners.func1(0x33bf220, 0xc420be4ba0)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsql_running.go:86 +0x167
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc424ba5840, 0xc423bf45a0, 0xc424ba5830)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:195 +0xf3
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:188 +0xad

goroutine 139627 [IO wait]:
internal/poll.runtime_pollWait(0x7f034a6bba08, 0x72, 0x0)
	/usr/local/go/src/runtime/netpoll.go:173 +0x57
internal/poll.(*pollDesc).wait(0xc420c42118, 0x72, 0xffffffffffffff00, 0x33a97a0, 0x339c760)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:85 +0xae
internal/poll.(*pollDesc).waitRead(0xc420c42118, 0xc421c88400, 0x400, 0x400)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:90 +0x3d
internal/poll.(*FD).Read(0xc420c42100, 0xc421c88400, 0x400, 0x400, 0x0, 0x0, 0x0)
	/usr/local/go/src/internal/poll/fd_unix.go:125 +0x18a
net.(*netFD).Read(0xc420c42100, 0xc421c88400, 0x400, 0x400, 0x26, 0x8, 0x0)
	/usr/local/go/src/net/fd_unix.go:202 +0x52
net.(*conn).Read(0xc422114048, 0xc421c88400, 0x400, 0x400, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/net.go:176 +0x6d
crypto/tls.(*block).readFromUntil(0xc421886e70, 0x7f034d949498, 0xc422114048, 0x5, 0xc422114048, 0x0)
	/usr/local/go/src/crypto/tls/conn.go:488 +0x95
crypto/tls.(*Conn).readRecord(0xc423738a80, 0x23a6917, 0xc423738ba0, 0x0)
	/usr/local/go/src/crypto/tls/conn.go:590 +0xe0
crypto/tls.(*Conn).Read(0xc423738a80, 0xc423510000, 0x8000, 0x8000, 0x0, 0x0, 0x0)
	/usr/local/go/src/crypto/tls/conn.go:1134 +0x110
bufio.(*Reader).Read(0xc4249d61e0, 0xc421e20118, 0x9, 0x9, 0x28, 0x2191300, 0x0)
	/usr/local/go/src/bufio/bufio.go:213 +0x30b
io.ReadAtLeast(0x339e620, 0xc4249d61e0, 0xc421e20118, 0x9, 0x9, 0x9, 0xc421cc1de8, 0x839e1e, 0xc421cc1e97)
	/usr/local/go/src/io/io.go:309 +0x86
io.ReadFull(0x339e620, 0xc4249d61e0, 0xc421e20118, 0x9, 0x9, 0xcff5f4, 0xc424c520c0, 0xc424c50004)
	/usr/local/go/src/io/io.go:327 +0x58
github.com/cockroachdb/cockroach/vendor/golang.org/x/net/http2.readFrameHeader(0xc421e20118, 0x9, 0x9, 0x339e620, 0xc4249d61e0, 0x0, 0x0, 0xc424c520c0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/vendor/golang.org/x/net/http2/frame.go:237 +0x7b
github.com/cockroachdb/cockroach/vendor/golang.org/x/net/http2.(*Framer).ReadFrame(0xc421e200e0, 0xc424c520c0, 0xc424c520c0, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/vendor/golang.org/x/net/http2/frame.go:492 +0xa4
github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/transport.(*http2Client).reader(0xc4220a4000)
	/go/src/github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/transport/http2_client.go:1118 +0xbe
created by github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/transport.newHTTP2Client
	/go/src/github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/transport/http2_client.go:266 +0xc80

goroutine 139707 [select]:
github.com/cockroachdb/cockroach/pkg/server.(*Server).refreshSettings.func2(0x33bf220, 0xc422068c30)
	/go/src/github.com/cockroachdb/cockroach/pkg/server/settingsworker.go:112 +0x2db
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc424ba5640, 0xc423bf45a0, 0xc421913e60)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:195 +0xf3
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:188 +0xad

goroutine 139892 [semacquire]:
sync.runtime_notifyListWait(0xc423ceecd0, 0xc400000125)
	/usr/local/go/src/runtime/sema.go:507 +0x110
sync.(*Cond).Wait(0xc423ceecc0)
	/usr/local/go/src/sync/cond.go:56 +0x80
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).worker(0xc421f830e0, 0x33bf220, 0xc420be49c0)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:197 +0x7c
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).Start.func2(0x33bf220, 0xc420be49c0)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:166 +0x3e
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc420225160, 0xc423bf45a0, 0xc420225150)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:195 +0xf3
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:188 +0xad

goroutine 139692 [select]:
github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc.(*addrConn).transportMonitor(0xc421364000)
	/go/src/github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/clientconn.go:1002 +0x166
github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc.(*addrConn).connect.func1(0xc421364000)
	/go/src/github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/clientconn.go:703 +0x1ce
created by github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc.(*addrConn).connect
	/go/src/github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/clientconn.go:694 +0x40d

goroutine 139903 [semacquire]:
sync.runtime_notifyListWait(0xc423ceecd0, 0xc400000132)
	/usr/local/go/src/runtime/sema.go:507 +0x110
sync.(*Cond).Wait(0xc423ceecc0)
	/usr/local/go/src/sync/cond.go:56 +0x80
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).worker(0xc421f830e0, 0x33bf220, 0xc422ab54d0)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:197 +0x7c
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).Start.func2(0x33bf220, 0xc422ab54d0)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:166 +0x3e
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc4202252c0, 0xc423bf45a0, 0xc4202252b0)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:195 +0xf3
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:188 +0xad

goroutine 139644 [IO wait]:
internal/poll.runtime_pollWait(0x7f034d9ebdf0, 0x72, 0xffffffffffffffff)
	/usr/local/go/src/runtime/netpoll.go:173 +0x57
internal/poll.(*pollDesc).wait(0xc423c98718, 0x72, 0xc42003cc00, 0x0, 0x0)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:85 +0xae
internal/poll.(*pollDesc).waitRead(0xc423c98718, 0xffffffffffffff00, 0x0, 0x0)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:90 +0x3d
internal/poll.(*FD).Accept(0xc423c98700, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/internal/poll/fd_unix.go:334 +0x1e2
net.(*netFD).accept(0xc423c98700, 0xc420516030, 0x0, 0x0)
	/usr/local/go/src/net/fd_unix.go:238 +0x42
net.(*TCPListener).accept(0xc4203562b0, 0x14b30fa, 0x893100, 0xc42003ce80)
	/usr/local/go/src/net/tcpsock_posix.go:136 +0x2e
net.(*TCPListener).Accept(0xc4203562b0, 0x23a4c80, 0xc422157580, 0x33cb1c0, 0xc420516030)
	/usr/local/go/src/net/tcpsock.go:247 +0x49
github.com/cockroachdb/cockroach/vendor/github.com/cockroachdb/cmux.(*cMux).Serve(0xc422157580, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/vendor/github.com/cockroachdb/cmux/cmux.go:124 +0x95
github.com/cockroachdb/cockroach/pkg/server.(*Server).Start.func10.1()
	/go/src/github.com/cockroachdb/cockroach/pkg/server/server.go:965 +0x2f
sync.(*Once).Do(0xc4202b1d90, 0xc42146e758)
	/usr/local/go/src/sync/once.go:44 +0xbe
github.com/cockroachdb/cockroach/pkg/server.(*Server).Start.func10(0x33bf220, 0xc420b1dbf0)
	/go/src/github.com/cockroachdb/cockroach/pkg/server/server.go:964 +0x5b
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc4203ab5a0, 0xc423bf45a0, 0xc422574dc0)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:195 +0xf3
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:188 +0xad

goroutine 139853 [semacquire]:
sync.runtime_notifyListWait(0xc423ceecd0, 0xc40000010d)
	/usr/local/go/src/runtime/sema.go:507 +0x110
sync.(*Cond).Wait(0xc423ceecc0)
	/usr/local/go/src/sync/cond.go:56 +0x80
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).worker(0xc421f830e0, 0x33bf220, 0xc423e4af00)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:197 +0x7c
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).Start.func2(0x33bf220, 0xc423e4af00)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:166 +0x3e
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc4203abb80, 0xc423bf45a0, 0xc4203abb70)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:195 +0xf3
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:188 +0xad

goroutine 139879 [semacquire]:
sync.runtime_notifyListWait(0xc423ceecd0, 0xc400000123)
	/usr/local/go/src/runtime/sema.go:507 +0x110
sync.(*Cond).Wait(0xc423ceecc0)
	/usr/local/go/src/sync/cond.go:56 +0x80
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).worker(0xc421f830e0, 0x33bf220, 0xc423e4b3e0)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:197 +0x7c
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).Start.func2(0x33bf220, 0xc423e4b3e0)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:166 +0x3e
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc4203abff0, 0xc423bf45a0, 0xc4203abfe0)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:195 +0xf3
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:188 +0xad

goroutine 139849 [semacquire]:
sync.runtime_notifyListWait(0xc423ceecd0, 0xc400000106)
	/usr/local/go/src/runtime/sema.go:507 +0x110
sync.(*Cond).Wait(0xc423ceecc0)
	/usr/local/go/src/sync/cond.go:56 +0x80
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).worker(0xc421f830e0, 0x33bf220, 0xc423e4ae40)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:197 +0x7c
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).Start.func2(0x33bf220, 0xc423e4ae40)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:166 +0x3e
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc4203abb00, 0xc423bf45a0, 0xc4203abaf0)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:195 +0xf3
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:188 +0xad

goroutine 139843 [semacquire]:
sync.runtime_notifyListWait(0xc423ceecd0, 0xc400000101)
	/usr/local/go/src/runtime/sema.go:507 +0x110
sync.(*Cond).Wait(0xc423ceecc0)
	/usr/local/go/src/sync/cond.go:56 +0x80
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).worker(0xc421f830e0, 0x33bf220, 0xc423e4ad20)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:197 +0x7c
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).Start.func2(0x33bf220, 0xc423e4ad20)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:166 +0x3e
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc4203ab9a0, 0xc423bf45a0, 0xc4203ab990)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:195 +0xf3
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:188 +0xad

goroutine 139955 [select]:
github.com/cockroachdb/cockroach/pkg/sqlmigrations.(*Manager).EnsureMigrations.func2(0x33bf220, 0xc4242f14a0)
	/go/src/github.com/cockroachdb/cockroach/pkg/sqlmigrations/migrations.go:323 +0x100
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunAsyncTask.func1(0xc423bf45a0, 0x33bf220, 0xc4242f14a0, 0xc422ed9950, 0x29, 0x0, 0x0, 0xc422574a60)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:266 +0xe6
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunAsyncTask
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:261 +0x133

goroutine 139935 [select]:
github.com/cockroachdb/cockroach/pkg/sql.(*SchemaChangeManager).Start.func1(0x33bf220, 0xc421886090)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/schema_changer.go:1023 +0x9b6
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc424ba5910, 0xc423bf45a0, 0xc421913ee0)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:195 +0xf3
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:188 +0xad

goroutine 139873 [semacquire]:
sync.runtime_notifyListWait(0xc423ceecd0, 0xc400000120)
	/usr/local/go/src/runtime/sema.go:507 +0x110
sync.(*Cond).Wait(0xc423ceecc0)
	/usr/local/go/src/sync/cond.go:56 +0x80
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).worker(0xc421f830e0, 0x33bf220, 0xc423e4b2c0)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:197 +0x7c
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).Start.func2(0x33bf220, 0xc423e4b2c0)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:166 +0x3e
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc4203abe80, 0xc423bf45a0, 0xc4203abe60)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:195 +0xf3
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:188 +0xad

goroutine 139740 [select]:
github.com/cockroachdb/cockroach/pkg/storage.(*baseQueue).processLoop.func1(0x33bf220, 0xc422ab4000)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/queue.go:514 +0x1bb
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc4210dedd0, 0xc423bf45a0, 0xc4210b20c0)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:195 +0xf3
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:188 +0xad

goroutine 139764 [select]:
github.com/cockroachdb/cockroach/pkg/gossip.(*Gossip).bootstrap.func1(0x33bf220, 0xc422068450)
	/go/src/github.com/cockroachdb/cockroach/pkg/gossip/gossip.go:1151 +0x331
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc4202ef570, 0xc423bf45a0, 0xc4202ef550)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:195 +0xf3
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:188 +0xad

goroutine 139841 [select]:
github.com/cockroachdb/cockroach/pkg/storage.(*baseQueue).maybeAddToPurgatory.func2(0x33bf220, 0xc422de48d0)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/queue.go:705 +0x434
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc42038c900, 0xc423bf45a0, 0xc420cb6f00)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:195 +0xf3
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:188 +0xad

goroutine 139910 [select]:
github.com/cockroachdb/cockroach/pkg/storage.(*Store).Start.func2(0x33bf220, 0xc423a2ac90)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/store.go:1179 +0x122
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc4202253b0, 0xc423bf45a0, 0xc422575b00)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:195 +0xf3
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:188 +0xad

goroutine 139890 [semacquire]:
sync.runtime_notifyListWait(0xc423ceecd0, 0xc400000139)
	/usr/local/go/src/runtime/sema.go:507 +0x110
sync.(*Cond).Wait(0xc423ceecc0)
	/usr/local/go/src/sync/cond.go:56 +0x80
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).worker(0xc421f830e0, 0x33bf220, 0xc423e4b560)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:197 +0x7c
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).Start.func2(0x33bf220, 0xc423e4b560)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:166 +0x3e
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc420225120, 0xc423bf45a0, 0xc420225110)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:195 +0xf3
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:188 +0xad

goroutine 139877 [semacquire]:
sync.runtime_notifyListWait(0xc423ceecd0, 0xc400000124)
	/usr/local/go/src/runtime/sema.go:507 +0x110
sync.(*Cond).Wait(0xc423ceecc0)
	/usr/local/go/src/sync/cond.go:56 +0x80
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).worker(0xc421f830e0, 0x33bf220, 0xc423e4b380)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:197 +0x7c
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).Start.func2(0x33bf220, 0xc423e4b380)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:166 +0x3e
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc4203abfb0, 0xc423bf45a0, 0xc4203abfa0)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:195 +0xf3
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:188 +0xad

goroutine 139867 [semacquire]:
sync.runtime_notifyListWait(0xc423ceecd0, 0xc40000011a)
	/usr/local/go/src/runtime/sema.go:507 +0x110
sync.(*Cond).Wait(0xc423ceecc0)
	/usr/local/go/src/sync/cond.go:56 +0x80
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).worker(0xc421f830e0, 0x33bf220, 0xc423e4b1a0)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:197 +0x7c
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).Start.func2(0x33bf220, 0xc423e4b1a0)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:166 +0x3e
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc4203abd60, 0xc423bf45a0, 0xc4203abd50)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:195 +0xf3
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:188 +0xad

goroutine 139932 [select]:
github.com/cockroachdb/cockroach/pkg/sql.(*DistSQLPlanner).initRunners.func1(0x33bf220, 0xc422ab5dd0)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsql_running.go:86 +0x167
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc424ba58c0, 0xc423bf45a0, 0xc424ba58b0)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:195 +0xf3
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:188 +0xad

goroutine 139885 [semacquire]:
sync.runtime_notifyListWait(0xc423ceecd0, 0xc40000013a)
	/usr/local/go/src/runtime/sema.go:507 +0x110
sync.(*Cond).Wait(0xc423ceecc0)
	/usr/local/go/src/sync/cond.go:56 +0x80
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).worker(0xc421f830e0, 0x33bf220, 0xc422ab55f0)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:197 +0x7c
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).Start.func2(0x33bf220, 0xc422ab55f0)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:166 +0x3e
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc420224e20, 0xc423bf45a0, 0xc420224e10)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:195 +0xf3
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:188 +0xad

goroutine 139983 [runnable]:
github.com/cockroachdb/cockroach/pkg/sql/parser.(*sqlParserImpl).Parse(0xc420b492b8, 0x33abd20, 0xc420b49200, 0x480)
	yaccpar:156 +0x65983
github.com/cockroachdb/cockroach/pkg/sql/parser.(*Parser).parseWithDepth(0xc420b49200, 0x2, 0x233efd2, 0x5b, 0x0, 0x0, 0x0, 0x0, 0xc421f57518)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/parser/parse.go:51 +0x6b
github.com/cockroachdb/cockroach/pkg/sql/parser.parseWithDepth(0x1, 0x233efd2, 0x5b, 0x0, 0x0, 0x0, 0xc421f57540, 0xe1fcd2)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/parser/parse.go:72 +0x60
github.com/cockroachdb/cockroach/pkg/sql/parser.ParseOne(0x233efd2, 0x5b, 0x0, 0x0, 0x22cf38c, 0x10)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/parser/parse.go:78 +0x42
github.com/cockroachdb/cockroach/pkg/sql.(*planner).makeInternalPlan(0xc42334f500, 0x33bf160, 0xc420d30ec0, 0x233efd2, 0x5b, 0xc420d30f00, 0x4, 0x4, 0x3e8, 0xc421f57700, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/planner.go:255 +0x69
github.com/cockroachdb/cockroach/pkg/sql.(*planner).exec(0xc42334f500, 0x33bf160, 0xc420d30ec0, 0x233efd2, 0x5b, 0xc420d30f00, 0x4, 0x4, 0x0, 0x0, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/planner.go:333 +0x105
github.com/cockroachdb/cockroach/pkg/sql.LeaseStore.release.func1(0x33bf160, 0xc420d30ec0, 0xc424102780, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/lease.go:218 +0x361
github.com/cockroachdb/cockroach/pkg/internal/client.(*DB).Txn.func1(0x33bf160, 0xc420d30ec0, 0xc424102780, 0xc4225eeeaa, 0x0, 0x22c2453)
	/go/src/github.com/cockroachdb/cockroach/pkg/internal/client/db.go:508 +0x43
github.com/cockroachdb/cockroach/pkg/internal/client.(*Txn).Exec(0xc424102780, 0x33bf160, 0xc420d30ec0, 0xc420d30101, 0xc42201a480, 0x3b9aca00, 0x4000000000000000)
	/go/src/github.com/cockroachdb/cockroach/pkg/internal/client/txn.go:753 +0xfe
github.com/cockroachdb/cockroach/pkg/internal/client.(*DB).Txn(0xc420a70150, 0x33bf160, 0xc420d30ec0, 0xc421c54020, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/pkg/internal/client/db.go:507 +0x140
github.com/cockroachdb/cockroach/pkg/sql.LeaseStore.release(0x339efe0, 0xc4219a0b60, 0xc422156600, 0x3ff0000000000000, 0xc422156600, 0xc421ba4500, 0x45d964b800, 0x3fd0000000000000, 0xdf8475800, 0x0, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/lease.go:207 +0x2d1
github.com/cockroachdb/cockroach/pkg/sql.(*tableState).releaseLease.func1(0x33bf1a0, 0xc420016110)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/lease.go:921 +0xaa
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunAsyncTask.func1(0xc423bf45a0, 0x33bf1a0, 0xc420016110, 0xc420302600, 0x32, 0x0, 0x0, 0xc420403ae0)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:266 +0xe6
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunAsyncTask
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:261 +0x133

goroutine 139658 [semacquire]:
sync.runtime_notifyListWait(0xc4200c6d78, 0xc400000000)
	/usr/local/go/src/runtime/sema.go:507 +0x110
sync.(*Cond).Wait(0xc4200c6d68)
	/usr/local/go/src/sync/cond.go:56 +0x80
github.com/cockroachdb/cockroach/pkg/storage/engine.(*RocksDB).syncLoop(0xc4200c6c60)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/engine/rocksdb.go:625 +0xa2
created by github.com/cockroachdb/cockroach/pkg/storage/engine.(*RocksDB).open
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/engine/rocksdb.go:612 +0x4a3

goroutine 139734 [select]:
github.com/cockroachdb/cockroach/pkg/storage.(*baseQueue).processLoop.func1(0x33bf220, 0xc42421c030)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/queue.go:514 +0x1bb
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc4210ded70, 0xc423bf45a0, 0xc4210b2000)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:195 +0xf3
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:188 +0xad

goroutine 139653 [select]:
github.com/cockroachdb/cockroach/pkg/util/retry.(*Retry).Next(0xc421e71e78, 0xc420016110)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/retry/retry.go:119 +0x189
github.com/cockroachdb/cockroach/pkg/sql.LeaseStore.WaitForOneVersion(0x339efe0, 0xc4219a0b60, 0xc422156600, 0x3ff0000000000000, 0xc422156600, 0xc421ba4500, 0x45d964b800, 0x3fd0000000000000, 0xdf8475800, 0x0, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/lease.go:253 +0x2bc
github.com/cockroachdb/cockroach/pkg/sql.(*SchemaChanger).waitToUpdateLeases(0xc421e7a848, 0x33bf160, 0xc4214d8240, 0xc400000004, 0x23a3118, 0xc42059a820)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/schema_changer.go:602 +0x108
github.com/cockroachdb/cockroach/pkg/sql.(*SchemaChanger).exec.func2(0xc421e7a848, 0x33bf160, 0xc4214d8240)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/schema_changer.go:435 +0x49
github.com/cockroachdb/cockroach/pkg/sql.(*SchemaChanger).exec(0xc421e7a848, 0x33bf160, 0xc4214d8240, 0x1, 0x0, 0x0, 0x0, 0x0, 0x375438d9, 0xed1e06982, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/schema_changer.go:485 +0x444
github.com/cockroachdb/cockroach/pkg/sql.(*schemaChangerCollection).execSchemaChanges(0xc4238a90f0, 0x33bf160, 0xc4214d8240, 0xc423e706c0, 0xc4238a9000, 0xed1e00101, 0x0)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/session.go:1357 +0x4f5
github.com/cockroachdb/cockroach/pkg/sql.(*Executor).execParsed(0xc423e706c0, 0xc4238a9000, 0xc4238d4690, 0x1, 0x1, 0x0, 0x0, 0xc422081d40, 0x9f5be235370)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/executor.go:923 +0x449
github.com/cockroachdb/cockroach/pkg/sql.(*Executor).execRequest(0xc423e706c0, 0xc4238a9000, 0x23404be, 0x62, 0x0, 0x0, 0x62, 0x21c0ec0)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/executor.go:744 +0x49c
github.com/cockroachdb/cockroach/pkg/sql.(*Executor).ExecuteStatements(0xc423e706c0, 0xc4238a9000, 0x23404be, 0x62, 0x0, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/executor.go:629 +0x1bd
github.com/cockroachdb/cockroach/pkg/sql.(*Executor).ExecuteStatementsBuffered(0xc423e706c0, 0xc4238a9000, 0x23404be, 0x62, 0x0, 0x1, 0x0, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/executor.go:577 +0xe5
github.com/cockroachdb/cockroach/pkg/sqlmigrations.addRoles(0x33bf220, 0xc4242f14a0, 0x33b0ee0, 0xc422570b00, 0xc423e706c0, 0xc421ba4958, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/pkg/sqlmigrations/migrations.go:710 +0x10c
github.com/cockroachdb/cockroach/pkg/sqlmigrations.(*Manager).EnsureMigrations(0xc4225362c0, 0x33bf220, 0xc4242f14a0, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/pkg/sqlmigrations/migrations.go:378 +0xac4
github.com/cockroachdb/cockroach/pkg/server.(*Server).Start(0xc421ba4500, 0x33bf220, 0xc4242f14a0, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/pkg/server/server.go:1223 +0x32f9
github.com/cockroachdb/cockroach/pkg/server.(*TestServer).Start(0xc4234aba40, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/server/testserver.go:333 +0x137
github.com/cockroachdb/cockroach/pkg/testutils/serverutils.StartServerRaw(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/testutils/serverutils/test_server_shim.go:206 +0xef
github.com/cockroachdb/cockroach/pkg/testutils/serverutils.StartServer(0x33cfe00, 0xc4204880f0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/testutils/serverutils/test_server_shim.go:176 +0x55
github.com/cockroachdb/cockroach/pkg/testutils/testcluster.(*TestCluster).doAddServer(0xc423ecaaf0, 0x33cfe00, 0xc4204880f0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/testutils/testcluster/testcluster.go:247 +0x112
github.com/cockroachdb/cockroach/pkg/testutils/testcluster.StartTestCluster(0x33cfe00, 0xc4204880f0, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/testutils/testcluster/testcluster.go:155 +0x55a
github.com/cockroachdb/cockroach/pkg/ccl/sqlccl_test.backupRestoreTestSetupWithParams(0x33cfe00, 0xc4204880f0, 0x1, 0x1, 0x23a2ae0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/ccl/sqlccl/backup_test.go:86 +0xfe
github.com/cockroachdb/cockroach/pkg/ccl/sqlccl_test.backupRestoreTestSetup(0x33cfe00, 0xc4204880f0, 0x1, 0x1, 0x23a2ae0, 0x27d9480, 0xf, 0x3054120, 0x24, 0x2b3, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/ccl/sqlccl/backup_test.go:151 +0x96
github.com/cockroachdb/cockroach/pkg/ccl/sqlccl_test.TestTimestampMismatch(0xc4204880f0)
	/go/src/github.com/cockroachdb/cockroach/pkg/ccl/sqlccl/backup_test.go:1876 +0xa8
testing.tRunner(0xc4204880f0, 0x23a2ad0)
	/usr/local/go/src/testing/testing.go:746 +0xd0
created by testing.(*T).Run
	/usr/local/go/src/testing/testing.go:789 +0x2de

goroutine 139878 [semacquire]:
sync.runtime_notifyListWait(0xc423ceecd0, 0xc400000127)
	/usr/local/go/src/runtime/sema.go:507 +0x110
sync.(*Cond).Wait(0xc423ceecc0)
	/usr/local/go/src/sync/cond.go:56 +0x80
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).worker(0xc421f830e0, 0x33bf220, 0xc423e4b3b0)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:197 +0x7c
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).Start.func2(0x33bf220, 0xc423e4b3b0)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:166 +0x3e
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc4203abfd0, 0xc423bf45a0, 0xc4203abfc0)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:195 +0xf3
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:188 +0xad

goroutine 139719 [semacquire]:
sync.runtime_notifyListWait(0xc424829240, 0xc400000004)
	/usr/local/go/src/runtime/sema.go:507 +0x110
sync.(*Cond).Wait(0xc424829230)
	/usr/local/go/src/sync/cond.go:56 +0x80
io.(*pipe).read(0xc424829200, 0xc421e64000, 0x400, 0x400, 0x0, 0x0, 0x0)
	/usr/local/go/src/io/pipe.go:47 +0xc6
io.(*PipeReader).Read(0xc420fb42b8, 0xc421e64000, 0x400, 0x400, 0x0, 0x0, 0x0)
	/usr/local/go/src/io/pipe.go:130 +0x4c
crypto/tls.(*block).readFromUntil(0xc420f5e060, 0x7f034d949470, 0xc4203ab610, 0x5, 0xc4203ab610, 0x0)
	/usr/local/go/src/crypto/tls/conn.go:488 +0x95
crypto/tls.(*Conn).readRecord(0xc422d2fc00, 0x23a6917, 0xc422d2fd20, 0x0)
	/usr/local/go/src/crypto/tls/conn.go:590 +0xe0
crypto/tls.(*Conn).Read(0xc422d2fc00, 0xc4215e0000, 0x8000, 0x8000, 0x0, 0x0, 0x0)
	/usr/local/go/src/crypto/tls/conn.go:1134 +0x110
bufio.(*Reader).Read(0xc423ce8480, 0xc4219822d8, 0x9, 0x9, 0x28, 0x2191300, 0x0)
	/usr/local/go/src/bufio/bufio.go:213 +0x30b
io.ReadAtLeast(0x339e620, 0xc423ce8480, 0xc4219822d8, 0x9, 0x9, 0x9, 0xc42003ede8, 0x839e1e, 0xc42003ee97)
	/usr/local/go/src/io/io.go:309 +0x86
io.ReadFull(0x339e620, 0xc423ce8480, 0xc4219822d8, 0x9, 0x9, 0xcff5f4, 0xc422af02d0, 0xc422af0004)
	/usr/local/go/src/io/io.go:327 +0x58
github.com/cockroachdb/cockroach/vendor/golang.org/x/net/http2.readFrameHeader(0xc4219822d8, 0x9, 0x9, 0x339e620, 0xc423ce8480, 0x0, 0x0, 0xc422af02d0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/vendor/golang.org/x/net/http2/frame.go:237 +0x7b
github.com/cockroachdb/cockroach/vendor/golang.org/x/net/http2.(*Framer).ReadFrame(0xc4219822a0, 0xc422af02d0, 0xc422af02d0, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/vendor/golang.org/x/net/http2/frame.go:492 +0xa4
github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/transport.(*http2Client).reader(0xc422a7ea80)
	/go/src/github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/transport/http2_client.go:1118 +0xbe
created by github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/transport.newHTTP2Client
	/go/src/github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/transport/http2_client.go:266 +0xc80

goroutine 139888 [semacquire]:
sync.runtime_notifyListWait(0xc423ceecd0, 0xc400000138)
	/usr/local/go/src/runtime/sema.go:507 +0x110
sync.(*Cond).Wait(0xc423ceecc0)
	/usr/local/go/src/sync/cond.go:56 +0x80
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).worker(0xc421f830e0, 0x33bf220, 0xc423e4b500)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:197 +0x7c
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).Start.func2(0x33bf220, 0xc423e4b500)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:166 +0x3e
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc420225040, 0xc423bf45a0, 0xc420224fe0)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:195 +0xf3
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:188 +0xad

goroutine 139875 [semacquire]:
sync.runtime_notifyListWait(0xc423ceecd0, 0xc400000121)
	/usr/local/go/src/runtime/sema.go:507 +0x110
sync.(*Cond).Wait(0xc423ceecc0)
	/usr/local/go/src/sync/cond.go:56 +0x80
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).worker(0xc421f830e0, 0x33bf220, 0xc423e4b320)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:197 +0x7c
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).Start.func2(0x33bf220, 0xc423e4b320)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:166 +0x3e
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc4203abee0, 0xc423bf45a0, 0xc4203abec0)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:195 +0xf3
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:188 +0xad

goroutine 139733 [select]:
github.com/cockroachdb/cockroach/pkg/storage.(*baseQueue).processLoop.func1(0x33bf220, 0xc420be4c30)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/queue.go:514 +0x1bb
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc4210ded60, 0xc423bf45a0, 0xc4205d5fe0)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:195 +0xf3
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:188 +0xad

goroutine 139743 [IO wait]:
internal/poll.runtime_pollWait(0x7f034a6bbd08, 0x72, 0x0)
	/usr/local/go/src/runtime/netpoll.go:173 +0x57
internal/poll.(*pollDesc).wait(0xc4216dc018, 0x72, 0xffffffffffffff00, 0x33a97a0, 0x339c760)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:85 +0xae
internal/poll.(*pollDesc).waitRead(0xc4216dc018, 0xc420e49800, 0x400, 0x400)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:90 +0x3d
internal/poll.(*FD).Read(0xc4216dc000, 0xc420e49800, 0x400, 0x400, 0x0, 0x0, 0x0)
	/usr/local/go/src/internal/poll/fd_unix.go:125 +0x18a
net.(*netFD).Read(0xc4216dc000, 0xc420e49800, 0x400, 0x400, 0x301, 0x0, 0x0)
	/usr/local/go/src/net/fd_unix.go:202 +0x52
net.(*conn).Read(0xc420516030, 0xc420e49800, 0x400, 0x400, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/net.go:176 +0x6d
github.com/cockroachdb/cockroach/vendor/github.com/cockroachdb/cmux.(*MuxConn).Read(0xc422dba500, 0xc420e49800, 0x400, 0x400, 0x21bcfc0, 0xc422ab5000, 0x7f034d9494c0)
	/go/src/github.com/cockroachdb/cockroach/vendor/github.com/cockroachdb/cmux/cmux.go:218 +0x121
crypto/tls.(*block).readFromUntil(0xc422ab50e0, 0x7f034d9494c0, 0xc422dba500, 0x5, 0xc422dba500, 0x0)
	/usr/local/go/src/crypto/tls/conn.go:488 +0x95
crypto/tls.(*Conn).readRecord(0xc421c62e00, 0x23a6917, 0xc421c62f20, 0x0)
	/usr/local/go/src/crypto/tls/conn.go:590 +0xe0
crypto/tls.(*Conn).Read(0xc421c62e00, 0xc4235d0000, 0x8000, 0x8000, 0x0, 0x0, 0x0)
	/usr/local/go/src/crypto/tls/conn.go:1134 +0x110
bufio.(*Reader).Read(0xc4243d6300, 0xc423dbeab8, 0x9, 0x9, 0x28, 0x2191300, 0x0)
	/usr/local/go/src/bufio/bufio.go:213 +0x30b
io.ReadAtLeast(0x339e620, 0xc4243d6300, 0xc423dbeab8, 0x9, 0x9, 0x9, 0xc421d49bb8, 0x839e1e, 0xc421d49c67)
	/usr/local/go/src/io/io.go:309 +0x86
io.ReadFull(0x339e620, 0xc4243d6300, 0xc423dbeab8, 0x9, 0x9, 0xcff5f4, 0xc422af0300, 0xc422af0004)
	/usr/local/go/src/io/io.go:327 +0x58
github.com/cockroachdb/cockroach/vendor/golang.org/x/net/http2.readFrameHeader(0xc423dbeab8, 0x9, 0x9, 0x339e620, 0xc4243d6300, 0x0, 0x0, 0xc422af0300, 0x0)
	/go/src/github.com/cockroachdb/cockroach/vendor/golang.org/x/net/http2/frame.go:237 +0x7b
github.com/cockroachdb/cockroach/vendor/golang.org/x/net/http2.(*Framer).ReadFrame(0xc423dbea80, 0xc422af0300, 0xc422af0300, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/vendor/golang.org/x/net/http2/frame.go:492 +0xa4
github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/transport.(*http2Server).HandleStreams(0xc4200c66e0, 0xc424c52060, 0x23a5c20)
	/go/src/github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/transport/http2_server.go:393 +0x315
github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc.(*Server).serveStreams(0xc421ff8640, 0x33ca2c0, 0xc4200c66e0)
	/go/src/github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/server.go:568 +0x140
github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc.(*Server).serveHTTP2Transport(0xc421ff8640, 0x33ca740, 0xc421c62e00, 0x33a8b20, 0xc4209ead10)
	/go/src/github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/server.go:561 +0x471
github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc.(*Server).handleRawConn(0xc421ff8640, 0x33cafe0, 0xc422dba500)
	/go/src/github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/server.go:526 +0x497
created by github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc.(*Server).Serve
	/go/src/github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/server.go:495 +0x5b9

goroutine 139880 [semacquire]:
sync.runtime_notifyListWait(0xc423ceecd0, 0xc400000128)
	/usr/local/go/src/runtime/sema.go:507 +0x110
sync.(*Cond).Wait(0xc423ceecc0)
	/usr/local/go/src/sync/cond.go:56 +0x80
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).worker(0xc421f830e0, 0x33bf220, 0xc423e4b410)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:197 +0x7c
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).Start.func2(0x33bf220, 0xc423e4b410)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:166 +0x3e
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc420224110, 0xc423bf45a0, 0xc4202240e0)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:195 +0xf3
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:188 +0xad

goroutine 139909 [runnable]:
github.com/cockroachdb/cockroach/pkg/storage.(*Store).coalescedHeartbeatsLoop(0xc420277800, 0x33bf220, 0xc420f5e8a0)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/store.go:3788 +0x16d
github.com/cockroachdb/cockroach/pkg/storage.(*Store).(github.com/cockroachdb/cockroach/pkg/storage.coalescedHeartbeatsLoop)-fm(0x33bf220, 0xc420f5e8a0)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/store.go:3734 +0x3e
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc420225380, 0xc423bf45a0, 0xc420225370)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:195 +0xf3
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:188 +0xad

goroutine 139657 [select]:
github.com/cockroachdb/cockroach/pkg/sql.(*LeaseManager).RefreshLeases.func1(0x33bf220, 0xc420be4420)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/lease.go:1469 +0x912
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc4202eef20, 0xc423bf45a0, 0xc42320e630)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:195 +0xf3
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:188 +0xad

goroutine 139893 [semacquire]:
sync.runtime_notifyListWait(0xc423ceecd0, 0xc40000012b)
	/usr/local/go/src/runtime/sema.go:507 +0x110
sync.(*Cond).Wait(0xc423ceecc0)
	/usr/local/go/src/sync/cond.go:56 +0x80
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).worker(0xc421f830e0, 0x33bf220, 0xc420be49f0)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:197 +0x7c
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).Start.func2(0x33bf220, 0xc420be49f0)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:166 +0x3e
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc420225180, 0xc423bf45a0, 0xc420225170)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:195 +0xf3
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:188 +0xad

goroutine 139837 [semacquire]:
sync.runtime_notifyListWait(0xc424829180, 0xc400000004)
	/usr/local/go/src/runtime/sema.go:507 +0x110
sync.(*Cond).Wait(0xc424829170)
	/usr/local/go/src/sync/cond.go:56 +0x80
io.(*pipe).read(0xc424829140, 0xc423841000, 0x400, 0x400, 0x0, 0x0, 0x0)
	/usr/local/go/src/io/pipe.go:47 +0xc6
io.(*PipeReader).Read(0xc420fb42a0, 0xc423841000, 0x400, 0x400, 0x0, 0x0, 0x0)
	/usr/local/go/src/io/pipe.go:130 +0x4c
crypto/tls.(*block).readFromUntil(0xc420b1dc80, 0x7f034d949470, 0xc4203ab600, 0x5, 0xc4203ab600, 0x0)
	/usr/local/go/src/crypto/tls/conn.go:488 +0x95
crypto/tls.(*Conn).readRecord(0xc422d2f880, 0x23a6917, 0xc422d2f9a0, 0x0)
	/usr/local/go/src/crypto/tls/conn.go:590 +0xe0
crypto/tls.(*Conn).Read(0xc422d2f880, 0xc421f60000, 0x8000, 0x8000, 0x0, 0x0, 0x0)
	/usr/local/go/src/crypto/tls/conn.go:1134 +0x110
bufio.(*Reader).Read(0xc421f7e540, 0xc42497fa78, 0x9, 0x9, 0x28, 0x2191300, 0x0)
	/usr/local/go/src/bufio/bufio.go:213 +0x30b
io.ReadAtLeast(0x339e620, 0xc421f7e540, 0xc42497fa78, 0x9, 0x9, 0x9, 0xc423419bb8, 0x839e1e, 0xc423419c67)
	/usr/local/go/src/io/io.go:309 +0x86
io.ReadFull(0x339e620, 0xc421f7e540, 0xc42497fa78, 0x9, 0x9, 0xcff5f4, 0xc422af02a0, 0xc422af0004)
	/usr/local/go/src/io/io.go:327 +0x58
github.com/cockroachdb/cockroach/vendor/golang.org/x/net/http2.readFrameHeader(0xc42497fa78, 0x9, 0x9, 0x339e620, 0xc421f7e540, 0x0, 0x0, 0xc422af02a0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/vendor/golang.org/x/net/http2/frame.go:237 +0x7b
github.com/cockroachdb/cockroach/vendor/golang.org/x/net/http2.(*Framer).ReadFrame(0xc42497fa40, 0xc422af02a0, 0xc422af02a0, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/vendor/golang.org/x/net/http2/frame.go:492 +0xa4
github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/transport.(*http2Server).HandleStreams(0xc420cba840, 0xc422af0240, 0x23a5c20)
	/go/src/github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/transport/http2_server.go:393 +0x315
github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc.(*Server).serveStreams(0xc421ff8640, 0x33ca2c0, 0xc420cba840)
	/go/src/github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/server.go:568 +0x140
github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc.(*Server).serveHTTP2Transport(0xc421ff8640, 0x33ca740, 0xc422d2f880, 0x33a8b20, 0xc420eee9a0)
	/go/src/github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/server.go:561 +0x471
github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc.(*Server).handleRawConn(0xc421ff8640, 
```

Please assign, take a look and update the issue accordingly.

### LINKED ISSUE #21340: teamcity: failed tests on master: test/TestBackupRestoreCrossTableReferences, test/TestBackupRestoreCrossTableReferences/restore_everything_to_new_cluster, testrace/TestBackupRestoreCrossTableReferences, testrace/TestBackupRestoreCrossTableReferences/restore_everything_to_new_cluster
The following tests appear to have failed:

[#472489](https://teamcity.cockroachdb.com/viewLog.html?buildId=472489):

```
--- FAIL: test/TestBackupRestoreCrossTableReferences (0.000s)
Test ended in panic.

------- Stdout: -------
W180109 09:21:33.866105 131059 server/status/runtime.go:109  Could not parse build timestamp: parsing time "" as "2006/01/02 15:04:05": cannot parse "" as "2006"
I180109 09:21:33.867873 131059 server/config.go:516  [n?] 1 storage engine initialized
I180109 09:21:33.867889 131059 server/config.go:519  [n?] RocksDB cache size: 128 MiB
I180109 09:21:33.867894 131059 server/config.go:519  [n?] store 0: in-memory, size 0 B
I180109 09:21:33.870025 131059 server/node.go:361  [n?] **** cluster cc94dc6e-4945-4492-a9cb-b4b8b110b074 has been created
I180109 09:21:33.870050 131059 server/server.go:934  [n?] **** add additional nodes by specifying --join=127.0.0.1:38531
I180109 09:21:33.870646 131059 storage/store.go:1209  [n1,s1] [n1,s1]: failed initial metrics computation: [n1,s1]: system config not yet available
I180109 09:21:33.870687 131059 server/node.go:486  [n1] initialized store [n1,s1]: disk (capacity=512 MiB, available=512 MiB, used=0 B, logicalBytes=3.2 KiB), ranges=1, leases=0, writes=0.00, bytesPerReplica={p10=3322.00 p25=3322.00 p50=3322.00 p75=3322.00 p90=3322.00}, writesPerReplica={p10=0.00 p25=0.00 p50=0.00 p75=0.00 p90=0.00}
I180109 09:21:33.870712 131059 server/node.go:339  [n1] node ID 1 initialized
I180109 09:21:33.870763 131059 gossip/gossip.go:332  [n1] NodeDescriptor set to node_id:1 address:<network_field:"tcp" address_field:"127.0.0.1:38531" > attrs:<> locality:<> ServerVersion:<major_val:1 minor_val:1 patch:0 unstable:8 > 
I180109 09:21:33.870872 131059 storage/stores.go:331  [n1] read 0 node addresses from persistent storage
I180109 09:21:33.871012 131059 server/node.go:627  [n1] connecting to gossip network to verify cluster ID...
I180109 09:21:33.871057 131059 server/node.go:652  [n1] node connected via gossip and verified as part of cluster "cc94dc6e-4945-4492-a9cb-b4b8b110b074"
I180109 09:21:33.871098 131059 server/node.go:428  [n1] node=1: started with [<no-attributes>=<in-mem>] engine(s) and attributes []
I180109 09:21:33.871156 131059 sql/distsql_physical_planner.go:122  [n1] creating DistSQLPlanner with address {tcp 127.0.0.1:38531}
I180109 09:21:33.873570 131167 storage/replica_command.go:819  [split,n1,s1,r1/1:/M{in-ax}] initiating a split of this range at key /System/"" [r2]
E180109 09:21:33.877887 131168 storage/queue.go:668  [replicate,n1,s1,r1/1:/{Min-System/}] range requires a replication change, but lacks a quorum of live replicas (0/1)
I180109 09:21:33.878077 131167 storage/replica_command.go:819  [split,n1,s1,r2/1:/{System/-Max}] initiating a split of this range at key /System/NodeLiveness [r3]
I180109 09:21:33.878526 131059 server/server.go:1161  [n1] starting https server at 127.0.0.1:37015
I180109 09:21:33.878558 131059 server/server.go:1162  [n1] starting grpc/postgres server at 127.0.0.1:38531
I180109 09:21:33.878567 131059 server/server.go:1163  [n1] advertising CockroachDB node at 127.0.0.1:38531
I180109 09:21:33.885012 131167 storage/replica_command.go:819  [split,n1,s1,r3/1:/{System/NodeL…-Max}] initiating a split of this range at key /System/NodeLivenessMax [r4]
W180109 09:21:33.885386 131318 storage/intent_resolver.go:324  [n1,s1] failed to push during intent resolution: failed to push "sql txn implicit" id=c90ba564 key=/Table/SystemConfigSpan/Start rw=true pri=0.00854502 iso=SERIALIZABLE stat=PENDING epo=0 ts=1515489693.880886054,0 orig=1515489693.880886054,0 max=1515489693.880886054,0 wto=false rop=false seq=7
I180109 09:21:33.886974 131059 sql/event_log.go:115  [n1] Event: "alter_table", target: 12, info: {TableName:eventlog Statement:ALTER TABLE system.eventlog ALTER COLUMN "uniqueID" SET DEFAULT uuid_v4() User:node MutationID:0 CascadeDroppedViews:[]}
I180109 09:21:33.888785 131167 storage/replica_command.go:819  [split,n1,s1,r4/1:/{System/NodeL…-Max}] initiating a split of this range at key /System/tsd [r5]
I180109 09:21:33.890568 131059 sql/lease.go:348  [n1] publish: descID=12 (eventlog) version=2 mtime=2018-01-09 09:21:33.890446992 +0000 UTC
I180109 09:21:33.893688 131167 storage/replica_command.go:819  [split,n1,s1,r5/1:/{System/tsd-Max}] initiating a split of this range at key /System/"tse" [r6]
I180109 09:21:33.899470 131167 storage/replica_command.go:819  [split,n1,s1,r6/1:/{System/tse-Max}] initiating a split of this range at key /Table/SystemConfigSpan/Start [r7]
W180109 09:21:33.905327 131352 storage/intent_resolver.go:324  [n1,s1] failed to push during intent resolution: failed to push "sql txn implicit" id=d937b43c key=/Table/SystemConfigSpan/Start rw=true pri=0.06994833 iso=SERIALIZABLE stat=PENDING epo=0 ts=1515489693.900599892,0 orig=1515489693.900599892,0 max=1515489693.900599892,0 wto=false rop=false seq=7
I180109 09:21:33.905789 131167 storage/replica_command.go:819  [split,n1,s1,r7/1:/{Table/System…-Max}] initiating a split of this range at key /Table/11 [r8]
I180109 09:21:33.907332 131059 sql/event_log.go:115  [n1] Event: "set_cluster_setting", target: 0, info: {SettingName:diagnostics.reporting.enabled Value:true User:node}
I180109 09:21:33.910140 131167 storage/replica_command.go:819  [split,n1,s1,r8/1:/{Table/11-Max}] initiating a split of this range at key /Table/12 [r9]
I180109 09:21:33.913898 131167 storage/replica_command.go:819  [split,n1,s1,r9/1:/{Table/12-Max}] initiating a split of this range at key /Table/13 [r10]
I180109 09:21:33.915454 131059 sql/event_log.go:115  [n1] Event: "set_cluster_setting", target: 0, info: {SettingName:version Value:$1 User:node}
I180109 09:21:33.917611 131167 storage/replica_command.go:819  [split,n1,s1,r10/1:/{Table/13-Max}] initiating a split of this range at key /Table/14 [r11]
I180109 09:21:33.918666 131059 sql/event_log.go:115  [n1] Event: "set_cluster_setting", target: 0, info: {SettingName:trace.debug.enable Value:false User:node}
I180109 09:21:33.921998 131167 storage/replica_command.go:819  [split,n1,s1,r11/1:/{Table/14-Max}] initiating a split of this range at key /Table/15 [r12]
I180109 09:21:33.925016 131167 storage/replica_command.go:819  [split,n1,s1,r12/1:/{Table/15-Max}] initiating a split of this range at key /Table/16 [r13]
I180109 09:21:33.928482 131167 storage/replica_command.go:819  [split,n1,s1,r13/1:/{Table/16-Max}] initiating a split of this range at key /Table/17 [r14]
I180109 09:21:33.929620 131059 sql/event_log.go:115  [n1] Event: "alter_table", target: 4, info: {TableName:users Statement:ALTER TABLE system.users ADD COLUMN IF NOT EXISTS "isRole" BOOL NOT NULL DEFAULT false User:node MutationID:1 CascadeDroppedViews:[]}
I180109 09:21:33.931520 131059 sql/lease.go:348  [n1] publish: descID=4 (users) version=2 mtime=2018-01-09 09:21:33.931429583 +0000 UTC
I180109 09:21:33.932068 131167 storage/replica_command.go:819  [split,n1,s1,r14/1:/{Table/17-Max}] initiating a split of this range at key /Table/18 [r15]
I180109 09:21:33.934899 131167 storage/replica_command.go:819  [split,n1,s1,r15/1:/{Table/18-Max}] initiating a split of this range at key /Table/19 [r16]
I180109 09:21:33.935361 131059 sql/lease.go:348  [n1] publish: descID=4 (users) version=3 mtime=2018-01-09 09:21:33.93528106 +0000 UTC
I180109 09:21:33.939322 131167 storage/replica_command.go:819  [split,n1,s1,r16/1:/{Table/19-Max}] initiating a split of this range at key /Table/20 [r17]
I180109 09:21:33.941019 131059 sql/backfill.go:132  [n1] Running backfill for "users", v=3, m=1
I180109 09:21:33.944056 131167 storage/replica_command.go:819  [split,n1,s1,r17/1:/{Table/20-Max}] initiating a split of this range at key /Table/21 [r18]
I180109 09:21:33.947029 131167 storage/replica_command.go:819  [split,n1,s1,r18/1:/{Table/21-Max}] initiating a split of this range at key /Table/22 [r19]
I180109 09:21:33.949266 131059 sql/lease.go:348  [n1] publish: descID=4 (users) version=4 mtime=2018-01-09 09:21:33.949181027 +0000 UTC
I180109 09:21:33.950080 131167 storage/replica_command.go:819  [split,n1,s1,r19/1:/{Table/22-Max}] initiating a split of this range at key /Table/23 [r20]
I180109 09:21:33.952548 131059 sql/event_log.go:115  [n1] Event: "finish_schema_change", target: 4, info: {MutationID:1}
I180109 09:21:33.953232 131059 sql/lease.go:274  publish (count leases): descID=4 name=users version=3 count=1
I180109 09:21:33.981830 131059 server/server.go:1232  [n1] done ensuring all necessary migrations have run
I180109 09:21:33.981870 131059 server/server.go:1235  [n1] serving sql connections
I180109 09:21:33.983974 131557 sql/event_log.go:115  [n1] Event: "node_join", target: 1, info: {Descriptor:{NodeID:1 Address:{NetworkField:tcp AddressField:127.0.0.1:38531} Attrs: Locality: ServerVersion:1.1-8} ClusterID:cc94dc6e-4945-4492-a9cb-b4b8b110b074 StartedAt:1515489693871071403 LastUp:1515489693871071403}
I180109 09:21:33.994395 131523 sql/event_log.go:115  [client=127.0.0.1:47286,user=root,n1] Event: "create_database", target: 50, info: {DatabaseName:data Statement:CREATE DATABASE data User:root}
I180109 09:21:33.995085 131167 storage/replica_command.go:819  [split,n1,s1,r20/1:/{Table/23-Max}] initiating a split of this range at key /Table/50 [r21]
I180109 09:21:33.997759 131523 sql/event_log.go:115  [client=127.0.0.1:47286,user=root,n1] Event: "create_table", target: 51, info: {TableName:bank Statement:CREATE TABLE bank (id INT PRIMARY KEY, balance INT, payload STRING, FAMILY (id, balance, payload)) User:root}
I180109 09:21:33.998465 131167 storage/replica_command.go:819  [split,n1,s1,r21/1:/{Table/50-Max}] initiating a split of this range at key /Table/51 [r22]
I180109 09:21:34.001662 131523 storage/replica_command.go:819  [n1,s1,r22/1:/{Table/51-Max}] initiating a split of this range at key /Table/51/1/3 [r23]
I180109 09:21:34.004569 131523 storage/replica_command.go:819  [n1,s1,r23/1:/{Table/51/1/3-Max}] initiating a split of this range at key /Table/51/1/6 [r24]
I180109 09:21:34.007061 131523 storage/replica_command.go:819  [n1,s1,r24/1:/{Table/51/1/6-Max}] initiating a split of this range at key /Table/51/1/9 [r25]
I180109 09:21:34.010260 131523 storage/replica_command.go:819  [n1,s1,r25/1:/{Table/51/1/9-Max}] initiating a split of this range at key /Table/51/1/12 [r26]
I180109 09:21:34.012969 131523 storage/replica_command.go:819  [n1,s1,r26/1:/{Table/51/1/12-Max}] initiating a split of this range at key /Table/51/1/15 [r27]
I180109 09:21:34.015850 131523 storage/replica_command.go:819  [n1,s1,r27/1:/{Table/51/1/15-Max}] initiating a split of this range at key /Table/51/1/18 [r28]
I180109 09:21:34.022412 131523 storage/replica_command.go:819  [n1,s1,r28/1:/{Table/51/1/18-Max}] initiating a split of this range at key /Table/51/1/21 [r29]
I180109 09:21:34.025262 131523 storage/replica_command.go:819  [n1,s1,r29/1:/{Table/51/1/21-Max}] initiating a split of this range at key /Table/51/1/24 [r30]
I180109 09:21:34.028766 131523 storage/replica_command.go:819  [n1,s1,r30/1:/{Table/51/1/24-Max}] initiating a split of this range at key /Table/51/1/27 [r31]
I180109 09:21:34.034479 131523 sql/event_log.go:115  [client=127.0.0.1:47286,user=root,n1] Event: "create_database", target: 52, info: {DatabaseName:store Statement:CREATE DATABASE store User:root}
I180109 09:21:34.034914 131167 storage/replica_command.go:819  [split,n1,s1,r31/1:/{Table/51/1/27-Max}] initiating a split of this range at key /Table/52 [r32]
I180109 09:21:34.036720 131523 sql/event_log.go:115  [client=127.0.0.1:47286,user=root,n1] Event: "create_database", target: 53, info: {DatabaseName:storestats Statement:CREATE DATABASE storestats User:root}
I180109 09:21:34.038601 131167 storage/replica_command.go:819  [split,n1,s1,r32/1:/{Table/52-Max}] initiating a split of this range at key /Table/53 [r33]
I180109 09:21:34.039958 131523 sql/event_log.go:115  [client=127.0.0.1:47286,user=root,n1] Event: "create_table", target: 54, info: {TableName:store.customers Statement:CREATE TABLE store.customers (id INT PRIMARY KEY, email STRING UNIQUE) User:root}
I180109 09:21:34.041581 131167 storage/replica_command.go:819  [split,n1,s1,r33/1:/{Table/53-Max}] initiating a split of this range at key /Table/54 [r34]
I180109 09:21:34.043523 131523 sql/event_log.go:115  [client=127.0.0.1:47286,user=root,n1] Event: "create_table", target: 55, info: {TableName:store.orders Statement:CREATE TABLE store.orders (id INT PRIMARY KEY, placed TIMESTAMP, INDEX (placed DESC), customerid INT, FOREIGN KEY (customerid) REFERENCES store.customers) User:root}
I180109 09:21:34.044993 131167 storage/replica_command.go:819  [split,n1,s1,r34/1:/{Table/54-Max}] initiating a split of this range at key /Table/55 [r35]
I180109 09:21:34.046211 131523 sql/lease.go:348  [client=127.0.0.1:47286,user=root,n1] publish: descID=54 (customers) version=2 mtime=2018-01-09 09:21:34.04612265 +0000 UTC
I180109 09:21:34.049740 131523 sql/lease.go:348  [client=127.0.0.1:47286,user=root,n1] publish: descID=55 (orders) version=2 mtime=2018-01-09 09:21:34.049648734 +0000 UTC
I180109 09:21:34.051503 131523 sql/lease.go:348  [client=127.0.0.1:47286,user=root,n1] publish: descID=55 (orders) version=3 mtime=2018-01-09 09:21:34.051418448 +0000 UTC
I180109 09:21:34.056141 131523 sql/event_log.go:115  [client=127.0.0.1:47286,user=root,n1] Event: "create_table", target: 56, info: {TableName:data.unused Statement:CREATE TABLE data.unused (id INT PRIMARY KEY) User:root}
I180109 09:21:34.056534 131167 storage/replica_command.go:819  [split,n1,s1,r35/1:/{Table/55-Max}] initiating a split of this range at key /Table/56 [r36]
I180109 09:21:34.062748 131523 sql/event_log.go:115  [client=127.0.0.1:47286,user=root,n1] Event: "create_table", target: 57, info: {TableName:store.receipts Statement:CREATE TABLE store.receipts (id INT PRIMARY KEY, reissue INT, dest STRING, orderid INT, FOREIGN KEY (reissue) REFERENCES store.receipts (id), FOREIGN KEY (dest) REFERENCES store.customers (email), FOREIGN KEY (orderid) REFERENCES store.orders) User:root}
I180109 09:21:34.063269 131167 storage/replica_command.go:819  [split,n1,s1,r36/1:/{Table/56-Max}] initiating a split of this range at key /Table/57 [r37]
I180109 09:21:34.065818 131523 sql/lease.go:348  [client=127.0.0.1:47286,user=root,n1] publish: descID=54 (customers) version=3 mtime=2018-01-09 09:21:34.065709627 +0000 UTC
I180109 09:21:34.069744 131523 sql/lease.go:348  [client=127.0.0.1:47286,user=root,n1] publish: descID=55 (orders) version=4 mtime=2018-01-09 09:21:34.06965851 +0000 UTC
I180109 09:21:34.072953 131523 sql/lease.go:348  [client=127.0.0.1:47286,user=root,n1] publish: descID=57 (receipts) version=2 mtime=2018-01-09 09:21:34.072868353 +0000 UTC
I180109 09:21:34.075669 131523 sql/lease.go:348  [client=127.0.0.1:47286,user=root,n1] publish: descID=57 (receipts) version=3 mtime=2018-01-09 09:21:34.075588734 +0000 UTC
I180109 09:21:34.081445 131523 sql/event_log.go:115  [client=127.0.0.1:47286,user=root,n1] Event: "create_view", target: 58, info: {ViewName:store.early_customers Statement:CREATE VIEW store.early_customers AS SELECT id FROM store.customers WHERE id < 5 User:root}
I180109 09:21:34.082047 131167 storage/replica_command.go:819  [split,n1,s1,r37/1:/{Table/57-Max}] initiating a split of this range at key /Table/58 [r38]
I180109 09:21:34.083345 131523 sql/lease.go:348  [client=127.0.0.1:47286,user=root,n1] publish: descID=54 (customers) version=4 mtime=2018-01-09 09:21:34.083264848 +0000 UTC
I180109 09:21:34.090238 131523 sql/event_log.go:115  [client=127.0.0.1:47286,user=root,n1] Event: "create_view", target: 59, info: {ViewName:storestats.ordercounts Statement:CREATE VIEW storestats.ordercounts AS SELECT c.id, c.email, count(o.id) FROM store.customers AS c LEFT JOIN store.orders AS o ON o.customerid = c.id GROUP BY c.id, c.email ORDER BY c.id, c.email User:root}
I180109 09:21:34.090580 131167 storage/replica_command.go:819  [split,n1,s1,r38/1:/{Table/58-Max}] initiating a split of this range at key /Table/59 [r39]
I180109 09:21:34.093128 131523 sql/lease.go:348  [client=127.0.0.1:47286,user=root,n1] publish: descID=54 (customers) version=5 mtime=2018-01-09 09:21:34.093034984 +0000 UTC
I180109 09:21:34.099468 131523 sql/lease.go:348  [client=127.0.0.1:47286,user=root,n1] publish: descID=55 (orders) version=5 mtime=2018-01-09 09:21:34.09938499 +0000 UTC
I180109 09:21:34.105201 131523 sql/event_log.go:115  [client=127.0.0.1:47286,user=root,n1] Event: "create_view", target: 60, info: {ViewName:store.unused_view Statement:CREATE VIEW store.unused_view AS SELECT id FROM store.customers WHERE false User:root}
I180109 09:21:34.105709 131167 storage/replica_command.go:819  [split,n1,s1,r39/1:/{Table/59-Max}] initiating a split of this range at key /Table/60 [r40]
I180109 09:21:34.107552 131523 sql/lease.go:348  [client=127.0.0.1:47286,user=root,n1] publish: descID=54 (customers) version=6 mtime=2018-01-09 09:21:34.107147156 +0000 UTC
I180109 09:21:34.244458 131978 ccl/storageccl/export.go:124  [n1,s1,r35/1:/Table/5{5-6}] export [/Table/55/3,/Table/55/4)
I180109 09:21:34.244546 131974 ccl/storageccl/export.go:124  [n1,s1,r34/1:/Table/5{4-5}] export [/Table/54/1,/Table/54/2)
I180109 09:21:34.244566 131975 ccl/storageccl/export.go:124  [n1,s1,r34/1:/Table/5{4-5}] export [/Table/54/2,/Table/54/3)
I180109 09:21:34.244603 131976 ccl/storageccl/export.go:124  [n1,s1,r35/1:/Table/5{5-6}] export [/Table/55/1,/Table/55/2)
I180109 09:21:34.244665 131977 ccl/storageccl/export.go:124  [n1,s1,r35/1:/Table/5{5-6}] export [/Table/55/2,/Table/55/3)
I180109 09:21:34.247714 131986 ccl/storageccl/export.go:124  [n1,s1,r37/1:/Table/5{7-8}] export [/Table/57/3,/Table/57/4)
I180109 09:21:34.247798 131793 ccl/storageccl/export.go:124  [n1,s1,r37/1:/Table/5{7-8}] export [/Table/57/2,/Table/57/3)
I180109 09:21:34.247834 131792 ccl/storageccl/export.go:124  [n1,s1,r37/1:/Table/5{7-8}] export [/Table/57/1,/Table/57/2)
I180109 09:21:34.247837 131923 ccl/storageccl/export.go:124  [n1,s1,r37/1:/Table/5{7-8}] export [/Table/57/4,/Table/57/5)
--- FAIL: test/TestBackupRestoreCrossTableReferences/restore_everything_to_new_cluster (0.000s)
Test ended in panic.

------- Stdout: -------
W180109 09:21:34.280807 131883 server/status/runtime.go:109  Could not parse build timestamp: parsing time "" as "2006/01/02 15:04:05": cannot parse "" as "2006"
I180109 09:21:34.286423 131883 server/config.go:516  [n?] 1 storage engine initialized
I180109 09:21:34.286448 131883 server/config.go:519  [n?] RocksDB cache size: 128 MiB
I180109 09:21:34.286455 131883 server/config.go:519  [n?] store 0: in-memory, size 0 B
I180109 09:21:34.289689 131883 server/node.go:361  [n?] **** cluster 178ecce7-47ba-4782-b8a8-ffc3ab67cc8d has been created
I180109 09:21:34.289723 131883 server/server.go:934  [n?] **** add additional nodes by specifying --join=127.0.0.1:37723
I180109 09:21:34.290471 131883 storage/store.go:1209  [n1,s1] [n1,s1]: failed initial metrics computation: [n1,s1]: system config not yet available
I180109 09:21:34.290513 131883 server/node.go:486  [n1] initialized store [n1,s1]: disk (capacity=512 MiB, available=512 MiB, used=0 B, logicalBytes=3.2 KiB), ranges=1, leases=0, writes=0.00, bytesPerReplica={p10=3322.00 p25=3322.00 p50=3322.00 p75=3322.00 p90=3322.00}, writesPerReplica={p10=0.00 p25=0.00 p50=0.00 p75=0.00 p90=0.00}
I180109 09:21:34.290532 131883 server/node.go:339  [n1] node ID 1 initialized
I180109 09:21:34.290584 131883 gossip/gossip.go:332  [n1] NodeDescriptor set to node_id:1 address:<network_field:"tcp" address_field:"127.0.0.1:37723" > attrs:<> locality:<> ServerVersion:<major_val:1 minor_val:1 patch:0 unstable:8 > 
I180109 09:21:34.290730 131883 storage/stores.go:331  [n1] read 0 node addresses from persistent storage
I180109 09:21:34.290821 131883 server/node.go:627  [n1] connecting to gossip network to verify cluster ID...
I180109 09:21:34.290848 131883 server/node.go:652  [n1] node connected via gossip and verified as part of cluster "178ecce7-47ba-4782-b8a8-ffc3ab67cc8d"
I180109 09:21:34.290870 131883 server/node.go:428  [n1] node=1: started with [<no-attributes>=<in-mem>] engine(s) and attributes []
I180109 09:21:34.290915 131883 sql/distsql_physical_planner.go:122  [n1] creating DistSQLPlanner with address {tcp 127.0.0.1:37723}
I180109 09:21:34.292112 131991 storage/replica_command.go:819  [split,n1,s1,r1/1:/M{in-ax}] initiating a split of this range at key /System/"" [r2]
I180109 09:21:34.293861 131883 server/server.go:1161  [n1] starting https server at 127.0.0.1:33523
I180109 09:21:34.293897 131883 server/server.go:1162  [n1] starting grpc/postgres server at 127.0.0.1:37723
I180109 09:21:34.293913 131883 server/server.go:1163  [n1] advertising CockroachDB node at 127.0.0.1:37723
I180109 09:21:34.298352 131991 storage/replica_command.go:819  [split,n1,s1,r2/1:/{System/-Max}] initiating a split of this range at key /System/NodeLiveness [r3]
I180109 09:21:34.304120 131991 storage/replica_command.go:819  [split,n1,s1,r3/1:/{System/NodeL…-Max}] initiating a split of this range at key /System/NodeLivenessMax [r4]
W180109 09:21:34.304480 131931 storage/intent_resolver.go:324  [n1,s1] failed to push during intent resolution: failed to push "sql txn implicit" id=4c4394e4 key=/Table/SystemConfigSpan/Start rw=true pri=0.05814885 iso=SERIALIZABLE stat=PENDING epo=0 ts=1515489694.299458114,0 orig=1515489694.299458114,0 max=1515489694.299458114,0 wto=false rop=false seq=7
I180109 09:21:34.308107 131883 sql/event_log.go:115  [n1] Event: "alter_table", target: 12, info: {TableName:eventlog Statement:ALTER TABLE system.eventlog ALTER COLUMN "uniqueID" SET DEFAULT uuid_v4() User:node MutationID:0 CascadeDroppedViews:[]}
I180109 09:21:34.310130 131991 storage/replica_command.go:819  [split,n1,s1,r4/1:/{System/NodeL…-Max}] initiating a split of this range at key /System/tsd [r5]
I180109 09:21:34.312299 131883 sql/lease.go:348  [n1] publish: descID=12 (eventlog) version=2 mtime=2018-01-09 09:21:34.312155844 +0000 UTC
I180109 09:21:34.314469 131991 storage/replica_command.go:819  [split,n1,s1,r5/1:/{System/tsd-Max}] initiating a split of this range at key /System/"tse" [r6]
I180109 09:21:34.320568 131991 storage/replica_command.go:819  [split,n1,s1,r6/1:/{System/tse-Max}] initiating a split of this range at key /Table/SystemConfigSpan/Start [r7]
I180109 09:21:34.324654 131991 storage/replica_command.go:819  [split,n1,s1,r7/1:/{Table/System…-Max}] initiating a split of this range at key /Table/11 [r8]
W180109 09:21:34.324961 131901 storage/intent_resolver.go:324  [n1,s1] failed to push during intent resolution: failed to push "sql txn implicit" id=ab50d140 key=/Table/SystemConfigSpan/Start rw=true pri=0.03907741 iso=SERIALIZABLE stat=PENDING epo=0 ts=1515489694.321792062,0 orig=1515489694.321792062,0 max=1515489694.321792062,0 wto=false rop=false seq=7
I180109 09:21:34.326085 131883 sql/event_log.go:115  [n1] Event: "set_cluster_setting", target: 0, info: {SettingName:diagnostics.reporting.enabled Value:true User:node}
I180109 09:21:34.331913 131991 storage/replica_command.go:819  [split,n1,s1,r8/1:/{Table/11-Max}] initiating a split of this range at key /Table/12 [r9]
I180109 09:21:34.333873 131883 sql/event_log.go:115  [n1] Event: "set_cluster_setting", target: 0, info: {SettingName:version Value:$1 User:node}
I180109 09:21:34.335944 131991 storage/replica_command.go:819  [split,n1,s1,r9/1:/{Table/12-Max}] initiating a split of this range at key /Table/13 [r10]
I180109 09:21:34.337386 131883 sql/event_log.go:115  [n1] Event: "set_cluster_setting", target: 0, info: {SettingName:trace.debug.enable Value:false User:node}
I180109 09:21:34.339027 131991 storage/replica_command.go:819  [split,n1,s1,r10/1:/{Table/13-Max}] initiating a split of this range at key /Table/14 [r11]
I180109 09:21:34.342373 131991 storage/replica_command.go:819  [split,n1,s1,r11/1:/{Table/14-Max}] initiating a split of this range at key /Table/15 [r12]
I180109 09:21:34.344988 131991 storage/replica_command.go:819  [split,n1,s1,r12/1:/{Table/15-Max}] initiating a split of this range at key /Table/16 [r13]
I180109 09:21:34.350603 131991 storage/replica_command.go:819  [split,n1,s1,r13/1:/{Table/16-Max}] initiating a split of this range at key /Table/17 [r14]
I180109 09:21:34.350678 131883 sql/event_log.go:115  [n1] Event: "alter_table", target: 4, info: {TableName:users Statement:ALTER TABLE system.users ADD COLUMN IF NOT EXISTS "isRole" BOOL NOT NULL DEFAULT false User:node MutationID:1 CascadeDroppedViews:[]}
I180109 09:21:34.354585 131883 sql/lease.go:348  [n1] publish: descID=4 (users) version=2 mtime=2018-01-09 09:21:34.354476404 +0000 UTC
I180109 09:21:34.355122 131991 storage/replica_command.go:819  [split,n1,s1,r14/1:/{Table/17-Max}] initiating a split of this range at key /Table/18 [r15]
I180109 09:21:34.358219 131991 storage/replica_command.go:819  [split,n1,s1,r15/1:/{Table/18-Max}] initiating a split of this range at key /Table/19 [r16]
I180109 09:21:34.358564 131883 sql/lease.go:348  [n1] publish: descID=4 (users) version=3 mtime=2018-01-09 09:21:34.358476879 +0000 UTC
I180109 09:21:34.361543 131991 storage/replica_command.go:819  [split,n1,s1,r16/1:/{Table/19-Max}] initiating a split of this range at key /Table/20 [r17]
I180109 09:21:34.361787 131883 sql/backfill.go:132  [n1] Running backfill for "users", v=3, m=1
I180109 09:21:34.364537 131991 storage/replica_command.go:819  [split,n1,s1,r17/1:/{Table/20-Max}] initiating a split of this range at key /Table/21 [r18]
I180109 09:21:34.367427 131991 storage/replica_command.go:819  [split,n1,s1,r18/1:/{Table/21-Max}] initiating a split of this range at key /Table/22 [r19]
I180109 09:21:34.368597 131883 sql/lease.go:348  [n1] publish: descID=4 (users) version=4 mtime=2018-01-09 09:21:34.368520284 +0000 UTC
I180109 09:21:34.370694 131991 storage/replica_command.go:819  [split,n1,s1,r19/1:/{Table/22-Max}] initiating a split of this range at key /Table/23 [r20]
I180109 09:21:34.372378 131883 sql/event_log.go:115  [n1] Event: "finish_schema_change", target: 4, info: {MutationID:1}
I180109 09:21:34.373389 131883 sql/lease.go:274  publish (count leases): descID=4 name=users version=3 count=1
I180109 09:21:34.404168 131883 server/server.go:1232  [n1] done ensuring all necessary migrations have run
I180109 09:21:34.404199 131883 server/server.go:1235  [n1] serving sql connections
I180109 09:21:34.406024 132352 sql/event_log.go:115  [n1] Event: "node_join", target: 1, info: {Descriptor:{NodeID:1 Address:{NetworkField:tcp AddressField:127.0.0.1:37723} Attrs: Locality: ServerVersion:1.1-8} ClusterID:178ecce7-47ba-4782-b8a8-ffc3ab67cc8d StartedAt:1515489694290854334 LastUp:1515489694290854334}
I180109 09:21:34.416437 132429 sql/event_log.go:115  [client=127.0.0.1:36528,user=root,n1] Event: "create_database", target: 50, info: {DatabaseName:store Statement:CREATE DATABASE store User:root}
I180109 09:21:34.416726 131991 storage/replica_command.go:819  [split,n1,s1,r20/1:/{Table/23-Max}] initiating a split of this range at key /Table/50 [r21]
I180109 09:21:34.423891 132430 storage/replica_command.go:819  [n1,s1,r21/1:/{Table/50-Max}] initiating a split of this range at key /Table/51 [r22]
I180109 09:21:34.429545 132430 storage/replica_command.go:819  [n1,s1,r22/1:/{Table/51-Max}] initiating a split of this range at key /Table/52/2 [r23]
I180109 09:21:34.429924 132432 storage/replica_command.go:819  [n1,s1,r22/1:/{Table/51-Max}] initiating a split of this range at key /Table/51/2 [r24]
W180109 09:21:34.436625 132479 storage/replica.go:2170  [n1,s1,r22/1:/Table/5{1-2/2}] context canceled before command queue: 1 QueryTxn
I180109 09:21:34.437111 132430 storage/replica_command.go:819  [n1,s1,r23/1:/{Table/52/2-Max}] initiating a split of this range at key /Table/53/2 [r25]
I180109 09:21:34.437312 132431 storage/replica_command.go:819  [n1,s1,r23/1:/{Table/52/2-Max}] initiating a split of this range at key /Table/52/3 [r26]
W180109 09:21:34.444062 132413 storage/replica.go:2170  [n1,s1,r23/1:/Table/5{2/2-3/2}] context canceled before command queue: 1 QueryTxn
I180109 09:21:34.489572 132432 storage/replica_command.go:819  [n1,s1,r22/1:/Table/5{1-2/2}] initiating a split of this range at key /Table/51/2 [r27]
panic: test timed out after 4m0s

goroutine 132502 [running]:
testing.startAlarm.func1()
	/usr/local/go/src/testing/testing.go:1145 +0xf9
created by time.goFunc
	/usr/local/go/src/time/sleep.go:170 +0x44

goroutine 1 [chan receive]:
testing.(*T).Run(0xc4200a0690, 0x23217f9, 0x25, 0x23cc1b8, 0x8d4f01)
	/usr/local/go/src/testing/testing.go:790 +0x2fc
testing.runTests.func1(0xc4200a0690)
	/usr/local/go/src/testing/testing.go:1004 +0x64
testing.tRunner(0xc4200a0690, 0xc420683db8)
	/usr/local/go/src/testing/testing.go:746 +0xd0
testing.runTests(0xc42024acc0, 0x33ba640, 0x38, 0x38, 0x0)
	/usr/local/go/src/testing/testing.go:1002 +0x2d8
testing.(*M).Run(0xc42097bf18, 0xc4202577f0)
	/usr/local/go/src/testing/testing.go:921 +0x111
github.com/cockroachdb/cockroach/pkg/ccl/sqlccl.TestMain(0xc420683f18)
	/go/src/github.com/cockroachdb/cockroach/pkg/ccl/sqlccl/main_test.go:31 +0xda
main.main()
	github.com/cockroachdb/cockroach/pkg/ccl/sqlccl/_test/_testmain.go:172 +0xdb

goroutine 6 [chan receive]:
github.com/cockroachdb/cockroach/pkg/util/log.(*loggingT).flushDaemon(0x36075e0)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/log/clog.go:1043 +0x81
created by github.com/cockroachdb/cockroach/pkg/util/log.init.0
	/go/src/github.com/cockroachdb/cockroach/pkg/util/log/clog.go:581 +0xbf

goroutine 15 [syscall, 4 minutes]:
os/signal.signal_recv(0xc4200ec640)
	/usr/local/go/src/runtime/sigqueue.go:131 +0xa6
os/signal.loop()
	/usr/local/go/src/os/signal/signal_unix.go:22 +0x22
created by os/signal.init.0
	/usr/local/go/src/os/signal/signal_unix.go:28 +0x41

goroutine 131059 [chan receive]:
testing.(*T).Run(0xc42450c2d0, 0x2319a85, 0x21, 0xc42133f320, 0x30)
	/usr/local/go/src/testing/testing.go:790 +0x2fc
github.com/cockroachdb/cockroach/pkg/ccl/sqlccl_test.TestBackupRestoreCrossTableReferences(0xc42450c2d0)
	/go/src/github.com/cockroachdb/cockroach/pkg/ccl/sqlccl/backup_test.go:1208 +0xdfb
testing.tRunner(0xc42450c2d0, 0x23cc1b8)
	/usr/local/go/src/testing/testing.go:746 +0xd0
created by testing.(*T).Run
	/usr/local/go/src/testing/testing.go:789 +0x2de

goroutine 131032 [select]:
github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/transport.loopyWriter(0x33e5220, 0xc421482d80, 0xc421482d20, 0xc420c3bfb8)
	/go/src/github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/transport/transport.go:750 +0x2e4
github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/transport.newHTTP2Server.func1(0xc423ec4580)
	/go/src/github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/transport/http2_server.go:227 +0x5e
created by github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/transport.newHTTP2Server
	/go/src/github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/transport/http2_server.go:226 +0x8d5

goroutine 34 [select, locked to thread]:
runtime.gopark(0x23d0038, 0x0, 0x22e9164, 0x6, 0x18, 0x1)
	/usr/local/go/src/runtime/proc.go:277 +0x12c
runtime.selectgo(0xc42046af50, 0xc420440480)
	/usr/local/go/src/runtime/select.go:395 +0x1138
runtime.ensureSigM.func1()
	/usr/local/go/src/runtime/signal_unix.go:511 +0x220
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:2337 +0x1

goroutine 131818 [select]:
github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/transport.loopyWriter(0x33e5220, 0xc423d7fe00, 0xc423d7fd70, 0xc42236ffb8)
	/go/src/github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/transport/transport.go:750 +0x2e4
github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/transport.newHTTP2Server.func1(0xc423ec42c0)
	/go/src/github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/transport/http2_server.go:227 +0x5e
created by github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/transport.newHTTP2Server
	/go/src/github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/transport/http2_server.go:226 +0x8d5

goroutine 132179 [select]:
github.com/cockroachdb/cockroach/pkg/sql.(*DistSQLPlanner).initRunners.func1(0x33e5220, 0xc422be23c0)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsql_running.go:86 +0x167
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc420412430, 0xc421400a20, 0xc420412420)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:195 +0xf3
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:188 +0xad

goroutine 131229 [select]:
github.com/cockroachdb/cockroach/pkg/storage.(*Store).coalescedHeartbeatsLoop(0xc422434c00, 0x33e5220, 0xc4212bac00)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/store.go:3788 +0x16d
github.com/cockroachdb/cockroach/pkg/storage.(*Store).(github.com/cockroachdb/cockroach/pkg/storage.coalescedHeartbeatsLoop)-fm(0x33e5220, 0xc4212bac00)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/store.go:3734 +0x3e
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc421592ec0, 0xc4204ac900, 0xc421592eb0)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:195 +0xf3
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:188 +0xad

goroutine 131273 [select]:
github.com/cockroachdb/cockroach/pkg/sql.(*DistSQLPlanner).initRunners.func1(0x33e5220, 0xc4213b8780)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsql_running.go:86 +0x167
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc420412dd0, 0xc4204ac900, 0xc420412dc0)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:195 +0xf3
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:188 +0xad

goroutine 132011 [select]:
github.com/cockroachdb/cockroach/pkg/gossip.(*Gossip).manage.func1(0x33e5220, 0xc420f86000)
	/go/src/github.com/cockroachdb/cockroach/pkg/gossip/gossip.go:1189 +0x269
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc422af6460, 0xc421400a20, 0xc422af6450)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:195 +0xf3
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:188 +0xad

goroutine 131949 [select]:
github.com/cockroachdb/cockroach/pkg/sql.(*DistSQLPlanner).initRunners.func1(0x33e5220, 0xc4232441b0)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsql_running.go:86 +0x167
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc4204122f0, 0xc421400a20, 0xc4204122d0)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:195 +0xf3
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:188 +0xad

goroutine 132118 [semacquire]:
sync.runtime_notifyListWait(0xc420f8f250, 0xc40000019d)
	/usr/local/go/src/runtime/sema.go:507 +0x110
sync.(*Cond).Wait(0xc420f8f240)
	/usr/local/go/src/sync/cond.go:56 +0x80
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).worker(0xc4204ad050, 0x33e5220, 0xc423cf6a20)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:197 +0x7c
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).Start.func2(0x33e5220, 0xc423cf6a20)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:166 +0x3e
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc420b7e650, 0xc421400a20, 0xc420b7e640)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:195 +0xf3
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:188 +0xad

goroutine 132091 [IO wait]:
internal/poll.runtime_pollWait(0x2b4786dc6a30, 0x72, 0x0)
	/usr/local/go/src/runtime/netpoll.go:173 +0x57
internal/poll.(*pollDesc).wait(0xc421328118, 0x72, 0xffffffffffffff00, 0x33cf720, 0x33c2700)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:85 +0xae
internal/poll.(*pollDesc).waitRead(0xc421328118, 0xc422546c00, 0x400, 0x400)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:90 +0x3d
internal/poll.(*FD).Read(0xc421328100, 0xc422546c00, 0x400, 0x400, 0x0, 0x0, 0x0)
	/usr/local/go/src/internal/poll/fd_unix.go:125 +0x18a
net.(*netFD).Read(0xc421328100, 0xc422546c00, 0x400, 0x400, 0x0, 0xb1a2ee901e964bcb, 0xc420c3c9c8)
	/usr/local/go/src/net/fd_unix.go:202 +0x52
net.(*conn).Read(0xc421122008, 0xc422546c00, 0x400, 0x400, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/net.go:176 +0x6d
crypto/tls.(*block).readFromUntil(0xc422be2570, 0x2b4788d63000, 0xc421122008, 0x5, 0xc421122008, 0xc420c3ca68)
	/usr/local/go/src/crypto/tls/conn.go:488 +0x95
crypto/tls.(*Conn).readRecord(0xc4210c4380, 0x23d0117, 0xc4210c44a0, 0x857967)
	/usr/local/go/src/crypto/tls/conn.go:590 +0xe0
crypto/tls.(*Conn).Read(0xc4210c4380, 0xc422b86000, 0x8000, 0x8000, 0x0, 0x0, 0x0)
	/usr/local/go/src/crypto/tls/conn.go:1134 +0x110
bufio.(*Reader).Read(0xc420fd5b00, 0xc421c131b8, 0x9, 0x9, 0x0, 0x8719e8, 0xc4210c5500)
	/usr/local/go/src/bufio/bufio.go:213 +0x30b
io.ReadAtLeast(0x33c45e0, 0xc420fd5b00, 0xc421c131b8, 0x9, 0x9, 0x9, 0xc4204141e0, 0xc420c3ce28, 0xd5f04e)
	/usr/local/go/src/io/io.go:309 +0x86
io.ReadFull(0x33c45e0, 0xc420fd5b00, 0xc421c131b8, 0x9, 0x9, 0x23cf590, 0x1800050100, 0xc400000001)
	/usr/local/go/src/io/io.go:327 +0x58
github.com/cockroachdb/cockroach/vendor/golang.org/x/net/http2.readFrameHeader(0xc421c131b8, 0x9, 0x9, 0x33c45e0, 0xc420fd5b00, 0x0, 0x0, 0x0, 0xc424c0c318)
	/go/src/github.com/cockroachdb/cockroach/vendor/golang.org/x/net/http2/frame.go:237 +0x7b
github.com/cockroachdb/cockroach/vendor/golang.org/x/net/http2.(*Framer).ReadFrame(0xc421c13180, 0xc423341a40, 0xc423341a40, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/vendor/golang.org/x/net/http2/frame.go:492 +0xa4
github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/transport.(*http2Client).reader(0xc4212ce780)
	/go/src/github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/transport/http2_client.go:1118 +0xbe
created by github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/transport.newHTTP2Client
	/go/src/github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/transport/http2_client.go:266 +0xc80

goroutine 131203 [semacquire]:
sync.runtime_notifyListWait(0xc423d235d0, 0xc400000328)
	/usr/local/go/src/runtime/sema.go:507 +0x110
sync.(*Cond).Wait(0xc423d235c0)
	/usr/local/go/src/sync/cond.go:56 +0x80
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).worker(0xc42183ed80, 0x33e5220, 0xc4214b0450)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:197 +0x7c
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).Start.func2(0x33e5220, 0xc4214b0450)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:166 +0x3e
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc421592b70, 0xc4204ac900, 0xc421592b60)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:195 +0xf3
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:188 +0xad

goroutine 131272 [select]:
github.com/cockroachdb/cockroach/pkg/sql.(*DistSQLPlanner).initRunners.func1(0x33e5220, 0xc4213b8750)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsql_running.go:86 +0x167
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc420412db0, 0xc4204ac900, 0xc420412da0)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:195 +0xf3
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:188 +0xad

goroutine 132429 [select]:
github.com/cockroachdb/cockroach/pkg/sql.(*hookFnNode).Next(0xc423984cd0, 0x33e5160, 0xc4233572c0, 0xc42285c298, 0xc42285c228, 0xc423984cd0, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/planhook.go:119 +0x172
github.com/cockroachdb/cockroach/pkg/sql.forEachRow(0x33e5160, 0xc4233572c0, 0xc42285c298, 0xc42285c228, 0x33dca20, 0xc423984cd0, 0xc42269e860, 0x0, 0xc42285ce90)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/executor.go:2074 +0x5d
github.com/cockroachdb/cockroach/pkg/sql.(*Executor).execClassic(0xc423ecdd40, 0xc42285c228, 0x33dca20, 0xc423984cd0, 0x33f0e80, 0xc4231850e0, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/executor.go:2055 +0x29c
github.com/cockroachdb/cockroach/pkg/sql.(*Executor).execStmt(0xc423ecdd40, 0x33e74e0, 0xc423328f50, 0x33b16e0, 0x7, 0x7, 0xc4227bba60, 0x17, 0x150819d9007aa98d, 0x1, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/executor.go:2216 +0x709
github.com/cockroachdb/cockroach/pkg/sql.(*Executor).execStmtInOpenTxn(0xc423ecdd40, 0xc42285c000, 0x33e74e0, 0xc423328f50, 0x33b16e0, 0x7, 0x7, 0xc4227bba60, 0x17, 0x150819d9007aa98d, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/executor.go:1849 +0x758
github.com/cockroachdb/cockroach/pkg/sql.(*Executor).execSingleStatement(0xc423ecdd40, 0xc42285c000, 0x33e74e0, 0xc423328f50, 0x33b16e0, 0x7, 0x7, 0xc4227bba60, 0x17, 0x150819d9007aa98d, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/executor.go:1318 +0x6c8
github.com/cockroachdb/cockroach/pkg/sql.runTxnAttempt(0xc423ecdd40, 0xc42285c000, 0xc423984be0, 0x1, 0x1, 0xc42269f638, 0x1, 0x1, 0x0, 0x33e9c80, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/executor.go:1194 +0x41f
github.com/cockroachdb/cockroach/pkg/sql.runWithAutoRetry(0xc423ecdd40, 0xc42285c000, 0xc423984be0, 0x1, 0x1, 0xed1e60101, 0x0, 0xc42269f638, 0x3ff0000000000000, 0x970800, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/executor.go:1019 +0x3aa
github.com/cockroachdb/cockroach/pkg/sql.(*Executor).execParsed(0xc423ecdd40, 0xc42285c000, 0xc423984be0, 0x1, 0x1, 0xc42269f638, 0x0, 0xe14546, 0xbe8d404798d7786c)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/executor.go:835 +0x138
github.com/cockroachdb/cockroach/pkg/sql.(*Executor).execPrepared(0xc423ecdd40, 0xc42285c000, 0xc4216ea870, 0xc423277638, 0x9, 0xc42285e017)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/executor.go:677 +0x159
github.com/cockroachdb/cockroach/pkg/sql.(*Executor).ExecutePreparedStatement(0xc423ecdd40, 0xc42285c000, 0xc4216ea870, 0xc423277638, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/executor.go:654 +0x134
github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*v3Conn).handleExecute(0xc4231850e0, 0xc423185108, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/pgwire/v3.go:964 +0x2f6
github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*v3Conn).serve(0xc4231850e0, 0x33e5220, 0xc4242499b0, 0xc4226a60d0, 0x5400, 0x15000, 0xc423ecc178, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/pgwire/v3.go:532 +0xb6f
github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*Server).ServeConn(0xc423ecc000, 0x33e5160, 0xc422332c40, 0x33f07c0, 0xc42149f180, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/pgwire/server.go:421 +0xbae
github.com/cockroachdb/cockroach/pkg/server.(*Server).Start.func17.1(0x33f1060, 0xc420a499a0)
	/go/src/github.com/cockroachdb/cockroach/pkg/server/server.go:1249 +0x149
github.com/cockroachdb/cockroach/pkg/util/netutil.(*Server).ServeWith.func1(0xc421400a20, 0x33e5220, 0xc4241f23f0, 0xc422f7c000, 0x33f1060, 0xc420a499a0, 0xc4241f2420)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/netutil/net.go:140 +0xa9
created by github.com/cockroachdb/cockroach/pkg/util/netutil.(*Server).ServeWith
	/go/src/github.com/cockroachdb/cockroach/pkg/util/netutil/net.go:137 +0x263

goroutine 131223 [semacquire]:
sync.runtime_notifyListWait(0xc423d235d0, 0xc40000033b)
	/usr/local/go/src/runtime/sema.go:507 +0x110
sync.(*Cond).Wait(0xc423d235c0)
	/usr/local/go/src/sync/cond.go:56 +0x80
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).worker(0xc42183ed80, 0x33e5220, 0xc4213b8570)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:197 +0x7c
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).Start.func2(0x33e5220, 0xc4213b8570)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:166 +0x3e
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc421592df0, 0xc4204ac900, 0xc421592de0)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:195 +0xf3
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:188 +0xad

goroutine 131242 [select]:
github.com/cockroachdb/cockroach/pkg/sql/jobs.(*Registry).Start.func2(0x33e5220, 0xc4213a5380)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/jobs/registry.go:205 +0x13b
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc420412500, 0xc4204ac900, 0xc4211c1050)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:195 +0xf3
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:188 +0xad

goroutine 131210 [semacquire]:
sync.runtime_notifyListWait(0xc423d235d0, 0xc400000331)
	/usr/local/go/src/runtime/sema.go:507 +0x110
sync.(*Cond).Wait(0xc423d235c0)
	/usr/local/go/src/sync/cond.go:56 +0x80
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).worker(0xc42183ed80, 0x33e5220, 0xc4214b0510)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:197 +0x7c
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).Start.func2(0x33e5220, 0xc4214b0510)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:166 +0x3e
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc421592c50, 0xc4204ac900, 0xc421592c40)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:195 +0xf3
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:188 +0xad

goroutine 132431 [select]:
github.com/cockroachdb/cockroach/pkg/util/retry.(*Retry).Next(0xc4209ffe30, 0x33d0960)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/retry/retry.go:119 +0x189
github.com/cockroachdb/cockroach/pkg/storage.(*Replica).AdminSplit(0xc421170000, 0x33e5220, 0xc4211165a0, 0xc420296158, 0x2, 0x8, 0x0, 0x0, 0x0, 0xc420296158, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/replica_command.go:693 +0x12e
github.com/cockroachdb/cockroach/pkg/storage.(*Replica).executeAdminBatch(0xc421170000, 0x33e5220, 0xc4211165a0, 0x150819d901b30365, 0x0, 0x100000001, 0x1, 0x17, 0x0, 0x0, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/replica.go:2445 +0xbec
github.com/cockroachdb/cockroach/pkg/storage.(*Replica).Send(0xc421170000, 0x33e5220, 0xc4211165a0, 0x150819d901b30365, 0x0, 0x100000001, 0x1, 0x17, 0x0, 0x0, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/replica.go:1915 +0x60f
github.com/cockroachdb/cockroach/pkg/storage.(*Store).Send(0xc4200a5400, 0x33e5220, 0xc421116570, 0x150819d901b30365, 0x0, 0x100000001, 0x1, 0x17, 0x0, 0x0, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/store.go:2585 +0x688
github.com/cockroachdb/cockroach/pkg/storage.(*Stores).Send(0xc422a60a50, 0x33e5220, 0xc4211164e0, 0x0, 0x0, 0x100000001, 0x1, 0x17, 0x0, 0x0, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/stores.go:214 +0x214
github.com/cockroachdb/cockroach/pkg/server.(*Node).batchInternal.func1(0x33e5220, 0xc4211164e0, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/pkg/server/node.go:860 +0x192
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunTaskWithErr(0xc421400a20, 0x33e5220, 0xc4211164e0, 0x22f84ea, 0x10, 0xc42210cfc8, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:245 +0xf7
github.com/cockroachdb/cockroach/pkg/server.(*Node).batchInternal(0xc422a08000, 0x33e5220, 0xc4211164e0, 0xc420d94648, 0xc4211164e0, 0x14c5f7e, 0x33e5220)
	/go/src/github.com/cockroachdb/cockroach/pkg/server/node.go:847 +0x152
github.com/cockroachdb/cockroach/pkg/server.(*Node).Batch(0xc422a08000, 0x33e5220, 0xc4211164e0, 0xc420d94648, 0x1f, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/pkg/server/node.go:888 +0x99
github.com/cockroachdb/cockroach/pkg/kv.(*grpcTransport).send.func1(0xc422a24380, 0xc420d94630, 0x33e5220, 0xc4211163c0, 0x0, 0xc42210d4a8, 0x8580c8)
	/go/src/github.com/cockroachdb/cockroach/pkg/kv/transport.go:243 +0x6b0
github.com/cockroachdb/cockroach/pkg/kv.(*grpcTransport).send(0xc422a24380, 0x33e5220, 0xc4211163c0, 0xc4203b4030, 0xf, 0xc423865b80, 0x0, 0x0, 0x100000001, 0x1, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/kv/transport.go:271 +0x9a
github.com/cockroachdb/cockroach/pkg/kv.(*grpcTransport).SendNext(0xc422a24380, 0x33e5220, 0xc4211163c0, 0xc420e6c360)
	/go/src/github.com/cockroachdb/cockroach/pkg/kv/transport.go:208 +0x31b
github.com/cockroachdb/cockroach/pkg/kv.(*DistSender).sendToReplicas(0xc4218e05a0, 0x33e5220, 0xc4211163c0, 0xc4218e05f0, 0x17, 0xc4202e6280, 0x1, 0x1, 0x0, 0x0, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/kv/dist_sender.go:1246 +0x3a4
github.com/cockroachdb/cockroach/pkg/kv.(*DistSender).sendRPC(0xc4218e05a0, 0x33e5220, 0xc4211163c0, 0x17, 0xc4202e6280, 0x1, 0x1, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/kv/dist_sender.go:382 +0x27b
github.com/cockroachdb/cockroach/pkg/kv.(*DistSender).sendSingleRange(0xc4218e05a0, 0x33e5220, 0xc4211163c0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/kv/dist_sender.go:446 +0x16e
github.com/cockroachdb/cockroach/pkg/kv.(*DistSender).sendPartialBatch(0xc4218e05a0, 0x33e5220, 0xc4211163c0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/kv/dist_sender.go:1024 +0x347
github.com/cockroachdb/cockroach/pkg/kv.(*DistSender).divideAndSendBatchToRanges(0xc4218e05a0, 0x33e5220, 0xc4211163c0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/kv/dist_sender.go:700 +0x16f8
github.com/cockroachdb/cockroach/pkg/kv.(*DistSender).Send(0xc4218e05a0, 0x33e5220, 0xc4211163c0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/kv/dist_sender.go:621 +0x3f5
github.com/cockroachdb/cockroach/pkg/kv.(*TxnCoordSender).Send(0xc420e0c460, 0x33e5220, 0xc4211163c0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/kv/txn_coord_sender.go:444 +0x1ce
github.com/cockroachdb/cockroach/pkg/internal/client.(*DB).send(0xc4237fcd80, 0x33e5160, 0xc422332f40, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/internal/client/db.go:546 +0x2c9
github.com/cockroachdb/cockroach/pkg/internal/client.(*DB).(github.com/cockroachdb/cockroach/pkg/internal/client.send)-fm(0x33e5160, 0xc422332f40, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/internal/client/db.go:480 +0x76
github.com/cockroachdb/cockroach/pkg/internal/client.sendAndFill(0x33e5160, 0xc422332f40, 0xc42210f4c0, 0xc422824700, 0xc420296158, 0xc4242680a0)
	/go/src/github.com/cockroachdb/cockroach/pkg/internal/client/db.go:457 +0xf8
github.com/cockroachdb/cockroach/pkg/internal/client.(*DB).Run(0xc4237fcd80, 0x33e5160, 0xc422332f40, 0xc422824700, 0xc4202e6220, 0xc4202e6220)
	/go/src/github.com/cockroachdb/cockroach/pkg/internal/client/db.go:480 +0x94
github.com/cockroachdb/cockroach/pkg/internal/client.(*DB).AdminSplit(0xc4237fcd80, 0x33e5160, 0xc422332f40, 0x21d07a0, 0xc4202e6200, 0x21d07a0, 0xc4202e6220, 0x2, 0x2)
	/go/src/github.com/cockroachdb/cockroach/pkg/internal/client/db.go:386 +0x98
github.com/cockroachdb/cockroach/pkg/ccl/sqlccl.splitAndScatter.func2(0x8, 0x23d0180)
	/go/src/github.com/cockroachdb/cockroach/pkg/ccl/sqlccl/restore.go:676 +0x41b
github.com/cockroachdb/cockroach/vendor/golang.org/x/sync/errgroup.(*Group).Go.func1(0xc422332f80, 0xc42308cb60)
	/go/src/github.com/cockroachdb/cockroach/vendor/golang.org/x/sync/errgroup/errgroup.go:58 +0x57
created by github.com/cockroachdb/cockroach/vendor/golang.org/x/sync/errgroup.(*Group).Go
	/go/src/github.com/cockroachdb/cockroach/vendor/golang.org/x/sync/errgroup/errgroup.go:55 +0x66

goroutine 131215 [semacquire]:
sync.runtime_notifyListWait(0xc423d235d0, 0xc400000335)
	/usr/local/go/src/runtime/sema.go:507 +0x110
sync.(*Cond).Wait(0xc423d235c0)
	/usr/local/go/src/sync/cond.go:56 +0x80
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).worker(0xc42183ed80, 0x33e5220, 0xc4212bab10)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:197 +0x7c
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).Start.func2(0x33e5220, 0xc4212bab10)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:166 +0x3e
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc421592cf0, 0xc4204ac900, 0xc421592ce0)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:195 +0xf3
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:188 +0xad

goroutine 131231 [select]:
github.com/cockroachdb/cockroach/pkg/storage.(*Store).startGossip.func4(0x33e5220, 0xc423cf60c0)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/store.go:1313 +0x3e9
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc421592f00, 0xc4204ac900, 0xc420075220)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:195 +0xf3
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:188 +0xad

goroutine 131948 [select]:
github.com/cockroachdb/cockroach/pkg/sql.(*DistSQLPlanner).initRunners.func1(0x33e5220, 0xc4232441e0)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsql_running.go:86 +0x167
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc4204122c0, 0xc421400a20, 0xc4204122a0)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:195 +0xf3
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:188 +0xad

goroutine 131085 [semacquire]:
sync.runtime_notifyListWait(0xc423d235d0, 0xc400000351)
	/usr/local/go/src/runtime/sema.go:507 +0x110
sync.(*Cond).Wait(0xc423d235c0)
	/usr/local/go/src/sync/cond.go:56 +0x80
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).worker(0xc42183ed80, 0x33e5220, 0xc4228b1f20)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:197 +0x7c
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).Start.func2(0x33e5220, 0xc4228b1f20)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:166 +0x3e
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc4215926b0, 0xc4204ac900, 0xc4215926a0)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:195 +0xf3
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:188 +0xad

goroutine 131217 [semacquire]:
sync.runtime_notifyListWait(0xc423d235d0, 0xc400000333)
	/usr/local/go/src/runtime/sema.go:507 +0x110
sync.(*Cond).Wait(0xc423d235c0)
	/usr/local/go/src/sync/cond.go:56 +0x80
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).worker(0xc42183ed80, 0x33e5220, 0xc4214b0570)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:197 +0x7c
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).Start.func2(0x33e5220, 0xc4214b0570)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:166 +0x3e
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc421592d30, 0xc4204ac900, 0xc421592d20)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:195 +0xf3
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:188 +0xad

goroutine 131235 [select]:
github.com/cockroachdb/cockroach/pkg/storage/compactor.(*Compactor).Start.func1(0x33e5220, 0xc4249cb560)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/compactor/compactor.go:124 +0x1ce
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc421592fb0, 0xc4204ac900, 0xc4238e6bd0)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:195 +0xf3
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:188 +0xad

goroutine 131282 [select]:
github.com/cockroachdb/cockroach/pkg/sql.(*DistSQLPlanner).initRunners.func1(0x33e5220, 0xc42247c180)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsql_running.go:86 +0x167
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc420412ef0, 0xc4204ac900, 0xc420412ee0)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:195 +0xf3
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:188 +0xad

goroutine 131189 [semacquire]:
sync.runtime_notifyListWait(0xc423d235d0, 0xc400000352)
	/usr/local/go/src/runtime/sema.go:507 +0x110
sync.(*Cond).Wait(0xc423d235c0)
	/usr/local/go/src/sync/cond.go:56 +0x80
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).worker(0xc42183ed80, 0x33e5220, 0xc4213b81e0)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:197 +0x7c
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).Start.func2(0x33e5220, 0xc4213b81e0)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:166 +0x3e
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc4215929b0, 0xc4204ac900, 0xc4215929a0)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:195 +0xf3
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:188 +0xad

goroutine 131252 [select]:
github.com/cockroachdb/cockroach/pkg/storage.(*baseQueue).processLoop.func1(0x33e5220, 0xc4214b0db0)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/queue.go:514 +0x1bb
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc421433160, 0xc4204ac900, 0xc42033f7c0)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:195 +0xf3
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:188 +0xad

goroutine 132123 [semacquire]:
sync.runtime_notifyListWait(0xc420f8f250, 0xc400000198)
	/usr/local/go/src/runtime/sema.go:507 +0x110
sync.(*Cond).Wait(0xc420f8f240)
	/usr/local/go/src/sync/cond.go:56 +0x80
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).worker(0xc4204ad050, 0x33e5220, 0xc423286300)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:197 +0x7c
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).Start.func2(0x33e5220, 0xc423286300)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:166 +0x3e
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc420b7e6f0, 
```

Please assign, take a look and update the issue accordingly.

### LINKED ISSUE #21409: teamcity: failed tests on master: test/TestRestoreInto, testrace/TestRestoreInto
The following tests appear to have failed:

[#476276](https://teamcity.cockroachdb.com/viewLog.html?buildId=476276):

```
--- FAIL: test/TestRestoreInto (0.000s)
Test ended in panic.

------- Stdout: -------
W180111 23:29:09.406773 156445 server/status/runtime.go:109  Could not parse build timestamp: parsing time "" as "2006/01/02 15:04:05": cannot parse "" as "2006"
I180111 23:29:09.409949 156445 server/config.go:518  [n?] 1 storage engine initialized
I180111 23:29:09.409990 156445 server/config.go:521  [n?] RocksDB cache size: 128 MiB
I180111 23:29:09.410002 156445 server/config.go:521  [n?] store 0: in-memory, size 0 B
I180111 23:29:09.413913 156445 server/node.go:361  [n?] **** cluster 3bcb64eb-e486-4b16-9d1f-33cc7b045b6e has been created
I180111 23:29:09.413960 156445 server/server.go:937  [n?] **** add additional nodes by specifying --join=127.0.0.1:38647
I180111 23:29:09.414902 156445 storage/store.go:1312  [n1,s1] [n1,s1]: failed initial metrics computation: [n1,s1]: system config not yet available
I180111 23:29:09.415000 156445 server/node.go:491  [n1] initialized store [n1,s1]: disk (capacity=512 MiB, available=512 MiB, used=0 B, logicalBytes=3.2 KiB), ranges=1, leases=0, writes=0.00, bytesPerReplica={p10=3322.00 p25=3322.00 p50=3322.00 p75=3322.00 p90=3322.00}, writesPerReplica={p10=0.00 p25=0.00 p50=0.00 p75=0.00 p90=0.00}
I180111 23:29:09.415037 156445 server/node.go:339  [n1] node ID 1 initialized
I180111 23:29:09.415106 156445 gossip/gossip.go:332  [n1] NodeDescriptor set to node_id:1 address:<network_field:"tcp" address_field:"127.0.0.1:38647" > attrs:<> locality:<> ServerVersion:<major_val:1 minor_val:1 patch:0 unstable:9 > 
I180111 23:29:09.415161 156445 storage/stores.go:331  [n1] read 0 node addresses from persistent storage
I180111 23:29:09.415243 156445 server/node.go:632  [n1] connecting to gossip network to verify cluster ID...
I180111 23:29:09.415280 156445 server/node.go:657  [n1] node connected via gossip and verified as part of cluster "3bcb64eb-e486-4b16-9d1f-33cc7b045b6e"
I180111 23:29:09.415308 156445 server/node.go:433  [n1] node=1: started with [<no-attributes>=<in-mem>] engine(s) and attributes []
I180111 23:29:09.415353 156445 sql/distsql_physical_planner.go:122  [n1] creating DistSQLPlanner with address {tcp 127.0.0.1:38647}
I180111 23:29:09.417238 156429 storage/replica_command.go:819  [split,n1,s1,r1/1:/M{in-ax}] initiating a split of this range at key /System/"" [r2]
I180111 23:29:09.422017 156445 server/server.go:1164  [n1] starting https server at 127.0.0.1:34027
I180111 23:29:09.422068 156445 server/server.go:1165  [n1] starting grpc/postgres server at 127.0.0.1:38647
I180111 23:29:09.422088 156445 server/server.go:1166  [n1] advertising CockroachDB node at 127.0.0.1:38647
panic: test timed out after 4m0s

goroutine 156677 [running]:
testing.startAlarm.func1()
	/usr/local/go/src/testing/testing.go:1145 +0xf9
created by time.goFunc
	/usr/local/go/src/time/sleep.go:170 +0x44

goroutine 1 [chan receive]:
testing.(*T).Run(0xc4200ae690, 0x23384c6, 0xf, 0x24112d8, 0x367c701)
	/usr/local/go/src/testing/testing.go:790 +0x2fc
testing.runTests.func1(0xc4200ae690)
	/usr/local/go/src/testing/testing.go:1004 +0x64
testing.tRunner(0xc4200ae690, 0xc4206a3db8)
	/usr/local/go/src/testing/testing.go:746 +0xd0
testing.runTests(0xc420258300, 0x342d4a0, 0x38, 0x38, 0x0)
	/usr/local/go/src/testing/testing.go:1002 +0x2d8
testing.(*M).Run(0xc42090bf18, 0x36c9500)
	/usr/local/go/src/testing/testing.go:921 +0x111
github.com/cockroachdb/cockroach/pkg/ccl/sqlccl.TestMain(0xc4206a3f18)
	/go/src/github.com/cockroachdb/cockroach/pkg/ccl/sqlccl/main_test.go:31 +0xda
main.main()
	github.com/cockroachdb/cockroach/pkg/ccl/sqlccl/_test/_testmain.go:172 +0xdb

goroutine 6 [chan receive]:
github.com/cockroachdb/cockroach/pkg/util/log.(*loggingT).flushDaemon(0x367e6c0)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/log/clog.go:1043 +0x81
created by github.com/cockroachdb/cockroach/pkg/util/log.init.0
	/go/src/github.com/cockroachdb/cockroach/pkg/util/log/clog.go:581 +0xbf

goroutine 19 [syscall, 4 minutes]:
os/signal.signal_recv(0x0)
	/usr/local/go/src/runtime/sigqueue.go:131 +0xa6
os/signal.loop()
	/usr/local/go/src/os/signal/signal_unix.go:22 +0x22
created by os/signal.init.0
	/usr/local/go/src/os/signal/signal_unix.go:28 +0x41

goroutine 156445 [semacquire]:
sync.runtime_SemacquireMutex(0xc422cf6794, 0xc4229f8b00)
	/usr/local/go/src/runtime/sema.go:71 +0x3d
sync.(*Mutex).Lock(0xc422cf6790)
	/usr/local/go/src/sync/mutex.go:134 +0xee
github.com/cockroachdb/cockroach/pkg/util/syncutil.(*Mutex).Lock(0xc422cf6790)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/syncutil/mutex_sync.go:32 +0x2d
github.com/cockroachdb/cockroach/pkg/storage.(*Replica).propose(0xc422cf6700, 0x34589c0, 0xc42169c510, 0x0, 0x0, 0xc42035a320, 0x100000001, 0x1, 0xc42035a330, 0xc42035a340, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/replica.go:3082 +0xab4
github.com/cockroachdb/cockroach/pkg/storage.(*Replica).tryExecuteWriteBatch(0xc422cf6700, 0x34589c0, 0xc42169c510, 0x1508e542bda274de, 0x0, 0x100000001, 0x1, 0x1, 0x0, 0xc421506460, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/replica.go:2747 +0x387
github.com/cockroachdb/cockroach/pkg/storage.(*Replica).executeWriteBatch(0xc422cf6700, 0x34589c0, 0xc42169c510, 0x1508e542bda274de, 0x0, 0x100000001, 0x1, 0x1, 0x0, 0xc421506460, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/replica.go:2601 +0xae
github.com/cockroachdb/cockroach/pkg/storage.(*Replica).Send(0xc422cf6700, 0x34589c0, 0xc42169c510, 0x1508e542bda274de, 0x0, 0x100000001, 0x1, 0x1, 0x0, 0xc421506460, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/replica.go:1913 +0x6a5
github.com/cockroachdb/cockroach/pkg/storage.(*Store).Send(0xc4206fc800, 0x34589c0, 0xc42169c4b0, 0x1508e542bda274de, 0x0, 0x100000001, 0x1, 0x1, 0x0, 0xc421506460, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/store.go:2688 +0x688
github.com/cockroachdb/cockroach/pkg/storage.(*Stores).Send(0xc422f76580, 0x34589c0, 0xc42169c3f0, 0x0, 0x0, 0x100000001, 0x1, 0x1, 0x0, 0xc421506460, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/stores.go:214 +0x214
github.com/cockroachdb/cockroach/pkg/server.(*Node).batchInternal.func1(0x34589c0, 0xc42169c3f0, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/pkg/server/node.go:865 +0x192
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunTaskWithErr(0xc420bd54d0, 0x34589c0, 0xc42169c360, 0x233a906, 0x10, 0xc4226f6858, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:245 +0xf7
github.com/cockroachdb/cockroach/pkg/server.(*Node).batchInternal(0xc423c21800, 0x34589c0, 0xc42169c360, 0xc420710598, 0xc42169c360, 0x14ee93e, 0x34589c0)
	/go/src/github.com/cockroachdb/cockroach/pkg/server/node.go:852 +0x152
github.com/cockroachdb/cockroach/pkg/server.(*Node).Batch(0xc423c21800, 0x34589c0, 0xc42169c360, 0xc420710598, 0x1f, 0x91955a, 0xc423b7e000)
	/go/src/github.com/cockroachdb/cockroach/pkg/server/node.go:893 +0x99
github.com/cockroachdb/cockroach/pkg/kv.(*grpcTransport).send.func1(0xc420cbe2a0, 0xc420710580, 0x34589c0, 0xc42169c150, 0x3, 0xc4226f6d38, 0x8580c8)
	/go/src/github.com/cockroachdb/cockroach/pkg/kv/transport.go:243 +0x6f8
github.com/cockroachdb/cockroach/pkg/kv.(*grpcTransport).send(0xc420cbe2a0, 0x34589c0, 0xc42169c150, 0xc4202f2010, 0xf, 0xc423ce01e0, 0x0, 0x0, 0x100000001, 0x1, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/kv/transport.go:274 +0x9a
github.com/cockroachdb/cockroach/pkg/kv.(*grpcTransport).SendNext(0xc420cbe2a0, 0x34589c0, 0xc42169c150, 0xc4204b5bc0)
	/go/src/github.com/cockroachdb/cockroach/pkg/kv/transport.go:208 +0x31b
github.com/cockroachdb/cockroach/pkg/kv.(*DistSender).sendToReplicas(0xc4200ae870, 0x34589c0, 0xc42169c150, 0xc4200ae8c0, 0x1, 0xc4229061a0, 0x1, 0x1, 0x0, 0x0, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/kv/dist_sender.go:1246 +0x3a4
github.com/cockroachdb/cockroach/pkg/kv.(*DistSender).sendRPC(0xc4200ae870, 0x34589c0, 0xc42169c150, 0x1, 0xc4229061a0, 0x1, 0x1, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/kv/dist_sender.go:382 +0x27b
github.com/cockroachdb/cockroach/pkg/kv.(*DistSender).sendSingleRange(0xc4200ae870, 0x34589c0, 0xc42169c150, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0xc421506380, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/kv/dist_sender.go:446 +0x16e
github.com/cockroachdb/cockroach/pkg/kv.(*DistSender).sendPartialBatch(0xc4200ae870, 0x34589c0, 0xc42169c150, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0xc421506380, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/kv/dist_sender.go:1024 +0x347
github.com/cockroachdb/cockroach/pkg/kv.(*DistSender).divideAndSendBatchToRanges(0xc4200ae870, 0x34589c0, 0xc42169c150, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0xc421506380, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/kv/dist_sender.go:700 +0x16f8
github.com/cockroachdb/cockroach/pkg/kv.(*DistSender).Send(0xc4200ae870, 0x34589c0, 0xc42169c150, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0xc4215061c0, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/kv/dist_sender.go:621 +0x3f5
github.com/cockroachdb/cockroach/pkg/kv.(*TxnCoordSender).Send(0xc4228c2380, 0x34589c0, 0xc42169c150, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0xc4215061c0, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/kv/txn_coord_sender.go:444 +0x1ce
github.com/cockroachdb/cockroach/pkg/internal/client.(*DB).send(0xc420301e60, 0x3458900, 0xc422fc6d00, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0xc4215061c0, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/internal/client/db.go:546 +0x2c9
github.com/cockroachdb/cockroach/pkg/internal/client.(*Txn).Send(0xc421614300, 0x3458900, 0xc422fc6d00, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/internal/client/txn.go:953 +0x308
github.com/cockroachdb/cockroach/pkg/internal/client.(*Txn).sendEndTxnReq(0xc421614300, 0x3458900, 0xc422fc6d00, 0x2413201, 0x0, 0xc422b90980)
	/go/src/github.com/cockroachdb/cockroach/pkg/internal/client/txn.go:671 +0x1be
github.com/cockroachdb/cockroach/pkg/internal/client.(*Txn).commit(0xc421614300, 0x3458900, 0xc422fc6d00, 0xc421614338, 0xc421614338)
	/go/src/github.com/cockroachdb/cockroach/pkg/internal/client/txn.go:518 +0x51
github.com/cockroachdb/cockroach/pkg/internal/client.(*Txn).Commit(0xc421614300, 0x3458900, 0xc422fc6d00, 0xc4203e0f80, 0x0)
	/go/src/github.com/cockroachdb/cockroach/pkg/internal/client/txn.go:550 +0x3f
github.com/cockroachdb/cockroach/pkg/internal/client.(*Txn).Exec(0xc421614300, 0x3458900, 0xc422fc6d00, 0xc422fc0101, 0xc424f706b0, 0x0, 0x10048b2)
	/go/src/github.com/cockroachdb/cockroach/pkg/internal/client/txn.go:764 +0x531
github.com/cockroachdb/cockroach/pkg/internal/client.(*DB).Txn(0xc420301e60, 0x3458900, 0xc422fc6d00, 0xc420fb0de0, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/pkg/internal/client/db.go:507 +0x140
github.com/cockroachdb/cockroach/pkg/internal/client.(*LeaseManager).AcquireLease(0xc420fb08a0, 0x34589c0, 0xc4213677a0, 0xc4200140a0, 0x15, 0x15, 0x3fc3333333333333, 0x0, 0x2faf080)
	/go/src/github.com/cockroachdb/cockroach/pkg/internal/client/lease.go:95 +0xfa
github.com/cockroachdb/cockroach/pkg/sqlmigrations.(*Manager).EnsureMigrations(0xc422fc66c0, 0x34589c0, 0xc4213677a0, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/pkg/sqlmigrations/migrations.go:299 +0x611
github.com/cockroachdb/cockroach/pkg/server.(*Server).Start(0xc4226e2500, 0x34589c0, 0xc4213677a0, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/pkg/server/server.go:1226 +0x32f9
github.com/cockroachdb/cockroach/pkg/server.(*TestServer).Start(0xc421612b40, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/server/testserver.go:333 +0x137
github.com/cockroachdb/cockroach/pkg/testutils/serverutils.StartServerRaw(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/testutils/serverutils/test_server_shim.go:203 +0xef
github.com/cockroachdb/cockroach/pkg/testutils/serverutils.StartServer(0x3469740, 0xc4224b22d0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/testutils/serverutils/test_server_shim.go:173 +0x55
github.com/cockroachdb/cockroach/pkg/testutils/testcluster.(*TestCluster).doAddServer(0xc421f12230, 0x3469740, 0xc4224b22d0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/testutils/testcluster/testcluster.go:247 +0x112
github.com/cockroachdb/cockroach/pkg/testutils/testcluster.StartTestCluster(0x3469740, 0xc4224b22d0, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/testutils/testcluster/testcluster.go:155 +0x55a
github.com/cockroachdb/cockroach/pkg/ccl/sqlccl_test.backupRestoreTestSetupWithParams(0x3469740, 0xc4224b22d0, 0x1, 0x1, 0x2411300, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/ccl/sqlccl/backup_test.go:86 +0xfe
github.com/cockroachdb/cockroach/pkg/ccl/sqlccl_test.backupRestoreTestSetup(0x3469740, 0xc4224b22d0, 0x1, 0x1, 0x2411300, 0xc42156df30, 0x2212e93b0, 0xc4202ad158, 0xc42156df40, 0x8a4f76, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/ccl/sqlccl/backup_test.go:151 +0x96
github.com/cockroachdb/cockroach/pkg/ccl/sqlccl_test.TestRestoreInto(0xc4224b22d0)
	/go/src/github.com/cockroachdb/cockroach/pkg/ccl/sqlccl/backup_test.go:2033 +0xa5
testing.tRunner(0xc4224b22d0, 0x24112d8)
	/usr/local/go/src/testing/testing.go:746 +0xd0
created by testing.(*T).Run
	/usr/local/go/src/testing/testing.go:789 +0x2de

goroutine 66 [select, locked to thread]:
runtime.gopark(0x24150b0, 0x0, 0x232b1d5, 0x6, 0x18, 0x1)
	/usr/local/go/src/runtime/proc.go:277 +0x12c
runtime.selectgo(0xc420bbaf50, 0xc420078ae0)
	/usr/local/go/src/runtime/select.go:395 +0x1138
runtime.ensureSigM.func1()
	/usr/local/go/src/runtime/signal_unix.go:511 +0x220
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:2337 +0x1

goroutine 156433 [select]:
github.com/cockroachdb/cockroach/pkg/storage.(*baseQueue).processLoop.func1(0x34589c0, 0xc420632cc0)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/queue.go:514 +0x1bb
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc420383c20, 0xc420bd54d0, 0xc422b9a180)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:195 +0xf3
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:188 +0xad

goroutine 156577 [semacquire]:
sync.runtime_notifyListWait(0xc421168f50, 0xc400000007)
	/usr/local/go/src/runtime/sema.go:507 +0x110
sync.(*Cond).Wait(0xc421168f40)
	/usr/local/go/src/sync/cond.go:56 +0x80
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).worker(0xc422484120, 0x34589c0, 0xc422ad8450)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:197 +0x7c
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).Start.func2(0x34589c0, 0xc422ad8450)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:166 +0x3e
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc4203d68a0, 0xc420bd54d0, 0xc4203d6890)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:195 +0xf3
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:188 +0xad

goroutine 156363 [select]:
github.com/cockroachdb/cockroach/pkg/storage/idalloc.(*Allocator).start.func1(0x34589c0, 0xc420d28120)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/idalloc/id_alloc.go:138 +0x6b4
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc420314080, 0xc420bd54d0, 0xc420314070)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:195 +0xf3
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:188 +0xad

goroutine 156597 [semacquire]:
sync.runtime_notifyListWait(0xc421168f50, 0xc40000001d)
	/usr/local/go/src/runtime/sema.go:507 +0x110
sync.(*Cond).Wait(0xc421168f40)
	/usr/local/go/src/sync/cond.go:56 +0x80
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).worker(0xc422484120, 0x34589c0, 0xc420632a20)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:197 +0x7c
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).Start.func2(0x34589c0, 0xc420632a20)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:166 +0x3e
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc4203d6ba0, 0xc420bd54d0, 0xc4203d6b80)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:195 +0xf3
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:188 +0xad

goroutine 156661 [select]:
github.com/cockroachdb/cockroach/pkg/sql.(*DistSQLPlanner).initRunners.func1(0x34589c0, 0xc420632d80)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsql_running.go:86 +0x167
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc4203d7610, 0xc420bd54d0, 0xc4203d7600)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:195 +0xf3
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:188 +0xad

goroutine 156637 [select]:
github.com/cockroachdb/cockroach/pkg/sql.(*DistSQLPlanner).initRunners.func1(0x34589c0, 0xc420632e40)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsql_running.go:86 +0x167
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc4203d7510, 0xc420bd54d0, 0xc4203d7500)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:195 +0xf3
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:188 +0xad

goroutine 156428 [select]:
github.com/cockroachdb/cockroach/pkg/storage.(*baseQueue).processLoop.func1(0x34589c0, 0xc420632c90)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/queue.go:514 +0x1bb
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc4203839d0, 0xc420bd54d0, 0xc422b9a0e0)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:195 +0xf3
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:188 +0xad

goroutine 156668 [semacquire]:
sync.runtime_notifyListWait(0xc42395e100, 0xc400000004)
	/usr/local/go/src/runtime/sema.go:507 +0x110
sync.(*Cond).Wait(0xc42395e0f0)
	/usr/local/go/src/sync/cond.go:56 +0x80
io.(*pipe).read(0xc42395e0c0, 0xc423f2a000, 0x400, 0x400, 0x0, 0x0, 0x0)
	/usr/local/go/src/io/pipe.go:47 +0xc6
io.(*PipeReader).Read(0xc4206f4050, 0xc423f2a000, 0x400, 0x400, 0x0, 0x0, 0x0)
	/usr/local/go/src/io/pipe.go:130 +0x4c
crypto/tls.(*block).readFromUntil(0xc422ec07e0, 0x7f3cea030c38, 0xc4203d6120, 0x5, 0xc4203d6120, 0x0)
	/usr/local/go/src/crypto/tls/conn.go:488 +0x95
crypto/tls.(*Conn).readRecord(0xc422656a80, 0x2415117, 0xc422656ba0, 0x0)
	/usr/local/go/src/crypto/tls/conn.go:590 +0xe0
crypto/tls.(*Conn).Read(0xc422656a80, 0xc422bd2000, 0x8000, 0x8000, 0x0, 0x0, 0x0)
	/usr/local/go/src/crypto/tls/conn.go:1134 +0x110
bufio.(*Reader).Read(0xc4212e0360, 0xc4227ba118, 0x9, 0x9, 0x28, 0x21f67a0, 0x0)
	/usr/local/go/src/bufio/bufio.go:213 +0x30b
io.ReadAtLeast(0x3437500, 0xc4212e0360, 0xc4227ba118, 0x9, 0x9, 0x9, 0xc421c6ade8, 0x84730e, 0xc421c6ae97)
	/usr/local/go/src/io/io.go:309 +0x86
io.ReadFull(0x3437500, 0xc4212e0360, 0xc4227ba118, 0x9, 0x9, 0xd0cee4, 0xc4234a0930, 0xc4234a0004)
	/usr/local/go/src/io/io.go:327 +0x58
github.com/cockroachdb/cockroach/vendor/golang.org/x/net/http2.readFrameHeader(0xc4227ba118, 0x9, 0x9, 0x3437500, 0xc4212e0360, 0x0, 0x0, 0xc4234a0930, 0x0)
	/go/src/github.com/cockroachdb/cockroach/vendor/golang.org/x/net/http2/frame.go:237 +0x7b
github.com/cockroachdb/cockroach/vendor/golang.org/x/net/http2.(*Framer).ReadFrame(0xc4227ba0e0, 0xc4234a0930, 0xc4234a0930, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/vendor/golang.org/x/net/http2/frame.go:492 +0xa4
github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/transport.(*http2Client).reader(0xc423c22300)
	/go/src/github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/transport/http2_client.go:1118 +0xbe
created by github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/transport.newHTTP2Client
	/go/src/github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/transport/http2_client.go:266 +0xc80

goroutine 156624 [select]:
github.com/cockroachdb/cockroach/pkg/storage.(*Store).startGossip.func4(0x34589c0, 0xc422ad8a20)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/store.go:1416 +0x3e9
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc4203d6f70, 0xc420bd54d0, 0xc4215ef860)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:195 +0xf3
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:188 +0xad

goroutine 156579 [semacquire]:
sync.runtime_notifyListWait(0xc421168f50, 0xc40000001a)
	/usr/local/go/src/runtime/sema.go:507 +0x110
sync.(*Cond).Wait(0xc421168f40)
	/usr/local/go/src/sync/cond.go:56 +0x80
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).worker(0xc422484120, 0x34589c0, 0xc422ad8660)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:197 +0x7c
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).Start.func2(0x34589c0, 0xc422ad8660)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:166 +0x3e
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc4203d6910, 0xc420bd54d0, 0xc4203d6900)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:195 +0xf3
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:188 +0xad

goroutine 156608 [semacquire]:
sync.runtime_notifyListWait(0xc421168f50, 0xc400000039)
	/usr/local/go/src/runtime/sema.go:507 +0x110
sync.(*Cond).Wait(0xc421168f40)
	/usr/local/go/src/sync/cond.go:56 +0x80
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).worker(0xc422484120, 0x34589c0, 0xc422c245a0)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:197 +0x7c
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).Start.func2(0x34589c0, 0xc422c245a0)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:166 +0x3e
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc4203d6d50, 0xc420bd54d0, 0xc4203d6d40)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:195 +0xf3
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:188 +0xad

goroutine 156601 [semacquire]:
sync.runtime_notifyListWait(0xc421168f50, 0xc400000022)
	/usr/local/go/src/runtime/sema.go:507 +0x110
sync.(*Cond).Wait(0xc421168f40)
	/usr/local/go/src/sync/cond.go:56 +0x80
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).worker(0xc422484120, 0x34589c0, 0xc422c24330)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:197 +0x7c
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).Start.func2(0x34589c0, 0xc422c24330)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:166 +0x3e
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc4203d6c70, 0xc420bd54d0, 0xc4203d6c60)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:195 +0xf3
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:188 +0xad

goroutine 156708 [select]:
github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/transport.loopyWriter(0x3458900, 0xc421240180, 0xc421e8c720, 0xc422940fb8)
	/go/src/github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/transport/transport.go:750 +0x2e4
github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/transport.newHTTP2Client.func3(0xc423c22300)
	/go/src/github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/transport/http2_client.go:298 +0x5e
created by github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/transport.newHTTP2Client
	/go/src/github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/transport/http2_client.go:297 +0xdd1

goroutine 156605 [semacquire]:
sync.runtime_notifyListWait(0xc421168f50, 0xc400000038)
	/usr/local/go/src/runtime/sema.go:507 +0x110
sync.(*Cond).Wait(0xc421168f40)
	/usr/local/go/src/sync/cond.go:56 +0x80
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).worker(0xc422484120, 0x34589c0, 0xc422ad8900)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:197 +0x7c
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).Start.func2(0x34589c0, 0xc422ad8900)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:166 +0x3e
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc4203d6cf0, 0xc420bd54d0, 0xc4203d6ce0)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:195 +0xf3
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:188 +0xad

goroutine 156617 [semacquire]:
sync.runtime_notifyListWait(0xc421168f50, 0xc40000003f)
	/usr/local/go/src/runtime/sema.go:507 +0x110
sync.(*Cond).Wait(0xc421168f40)
	/usr/local/go/src/sync/cond.go:56 +0x80
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).worker(0xc422484120, 0x34589c0, 0xc422ad8990)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:197 +0x7c
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).Start.func2(0x34589c0, 0xc422ad8990)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:166 +0x3e
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc4203d6e70, 0xc420bd54d0, 0xc4203d6e60)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:195 +0xf3
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:188 +0xad

goroutine 156368 [select]:
github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/credentials.(*tlsCreds).ClientHandshake(0xc42091a028, 0x3458980, 0xc422ff84e0, 0xc4202f2010, 0xf, 0x3464b80, 0xc420bf2008, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/credentials/credentials.go:149 +0x20c
github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/transport.newHTTP2Client(0x3458900, 0xc421034880, 0xc4202f2010, 0xf, 0x0, 0x0, 0x2335b3b, 0xd, 0x0, 0x0, ...)
	/go/src/github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/transport/http2_client.go:176 +0x1b14
github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/transport.NewClientTransport(0x3458900, 0xc421c62800, 0xc4202f2010, 0xf, 0x0, 0x0, 0x2335b3b, 0xd, 0x0, 0x0, ...)
	/go/src/github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/transport/transport.go:524 +0xbe
github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc.(*addrConn).resetTransport(0xc424964000, 0xc420d28120, 0xc420bd54f0)
	/go/src/github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/clientconn.go:929 +0x2e5
github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc.(*addrConn).connect.func1(0xc424964000)
	/go/src/github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/clientconn.go:695 +0x2f
created by github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc.(*addrConn).connect
	/go/src/github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/clientconn.go:694 +0x40d

goroutine 156638 [select]:
github.com/cockroachdb/cockroach/pkg/sql.(*DistSQLPlanner).initRunners.func1(0x34589c0, 0xc420632e10)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsql_running.go:86 +0x167
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc4203d7530, 0xc420bd54d0, 0xc4203d7520)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:195 +0xf3
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:188 +0xad

goroutine 156613 [semacquire]:
sync.runtime_notifyListWait(0xc421168f50, 0xc40000003b)
	/usr/local/go/src/runtime/sema.go:507 +0x110
sync.(*Cond).Wait(0xc421168f40)
	/usr/local/go/src/sync/cond.go:56 +0x80
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).worker(0xc422484120, 0x34589c0, 0xc422c245d0)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:197 +0x7c
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).Start.func2(0x34589c0, 0xc422c245d0)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:166 +0x3e
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc4203d6df0, 0xc420bd54d0, 0xc4203d6de0)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:195 +0xf3
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:188 +0xad

goroutine 156587 [semacquire]:
sync.runtime_notifyListWait(0xc421168f50, 0xc40000002e)
	/usr/local/go/src/runtime/sema.go:507 +0x110
sync.(*Cond).Wait(0xc421168f40)
	/usr/local/go/src/sync/cond.go:56 +0x80
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).worker(0xc422484120, 0x34589c0, 0xc422c243f0)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:197 +0x7c
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).Start.func2(0x34589c0, 0xc422c243f0)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:166 +0x3e
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc4203d6a10, 0xc420bd54d0, 0xc4203d6a00)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:195 +0xf3
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:188 +0xad

goroutine 156598 [semacquire]:
sync.runtime_notifyListWait(0xc421168f50, 0xc400000024)
	/usr/local/go/src/runtime/sema.go:507 +0x110
sync.(*Cond).Wait(0xc421168f40)
	/usr/local/go/src/sync/cond.go:56 +0x80
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).worker(0xc422484120, 0x34589c0, 0xc420632a50)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:197 +0x7c
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).Start.func2(0x34589c0, 0xc420632a50)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:166 +0x3e
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc4203d6c10, 0xc420bd54d0, 0xc4203d6bb0)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:195 +0xf3
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:188 +0xad

goroutine 156470 [select]:
github.com/cockroachdb/cockroach/pkg/gossip.(*Gossip).bootstrap.func1(0x34589c0, 0xc422c24240)
	/go/src/github.com/cockroachdb/cockroach/pkg/gossip/gossip.go:1151 +0x331
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc421218d90, 0xc420bd54d0, 0xc421218d80)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:195 +0xf3
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:188 +0xad

goroutine 156570 [semacquire]:
sync.runtime_notifyListWait(0xc421168f50, 0xc40000000a)
	/usr/local/go/src/runtime/sema.go:507 +0x110
sync.(*Cond).Wait(0xc421168f40)
	/usr/local/go/src/sync/cond.go:56 +0x80
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).worker(0xc422484120, 0x34589c0, 0xc422ad84b0)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:197 +0x7c
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).Start.func2(0x34589c0, 0xc422ad84b0)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:166 +0x3e
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc4203d6750, 0xc420bd54d0, 0xc4203d6730)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:195 +0xf3
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:188 +0xad

goroutine 156663 [select]:
github.com/cockroachdb/cockroach/pkg/sql.(*DistSQLPlanner).initRunners.func1(0x34589c0, 0xc42041e930)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsql_running.go:86 +0x167
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc4203d7650, 0xc420bd54d0, 0xc4203d7640)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:195 +0xf3
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:188 +0xad

goroutine 156644 [select]:
github.com/cockroachdb/cockroach/pkg/storage.(*replicaScanner).waitAndProcess(0xc42395e300, 0x34589c0, 0xc420632c60, 0x18bd7850, 0xed1e9ea45, 0x0, 0xc420e9d1c0, 0xc420bd54d0, 0xc422cf6700, 0x8bce19)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scanner.go:207 +0x226
github.com/cockroachdb/cockroach/pkg/storage.(*replicaScanner).scanLoop.func1.1(0xc422cf6700, 0xc420e6adb0)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scanner.go:269 +0x90
github.com/cockroachdb/cockroach/pkg/storage.(*storeReplicaVisitor).Visit(0xc420e6adb0, 0xc42244e140)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/store.go:322 +0x1ba
github.com/cockroachdb/cockroach/pkg/storage.(*replicaScanner).scanLoop.func1(0x34589c0, 0xc420632c60)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scanner.go:267 +0x1f5
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc420383c50, 0xc420bd54d0, 0xc422b9a200)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:195 +0xf3
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:188 +0xad

goroutine 156622 [select]:
github.com/cockroachdb/cockroach/pkg/storage.(*Store).startGossip.func4(0x34589c0, 0xc420632bd0)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/store.go:1416 +0x3e9
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc4203d6f50, 0xc420bd54d0, 0xc4215ef7c0)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:195 +0xf3
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:188 +0xad

goroutine 156563 [semacquire]:
sync.runtime_notifyListWait(0xc421168f50, 0xc400000011)
	/usr/local/go/src/runtime/sema.go:507 +0x110
sync.(*Cond).Wait(0xc421168f40)
	/usr/local/go/src/sync/cond.go:56 +0x80
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).worker(0xc422484120, 0x34589c0, 0xc420632930)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:197 +0x7c
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).Start.func2(0x34589c0, 0xc420632930)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:166 +0x3e
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc4203d6640, 0xc420bd54d0, 0xc4203d6630)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:195 +0xf3
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:188 +0xad

goroutine 156691 [select]:
github.com/cockroachdb/cockroach/pkg/sql/distsqlrun.(*flowScheduler).Start.func1(0x34589c0, 0xc420e6a210)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsqlrun/flow_scheduler.go:125 +0x17b
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc424f70490, 0xc420bd54d0, 0xc424f70480)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:195 +0xf3
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:188 +0xad

goroutine 156347 [select]:
github.com/cockroachdb/cockroach/pkg/sql.(*LeaseManager).RefreshLeases.func1(0x34589c0, 0xc422c24090)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/lease.go:1469 +0x912
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc4212188d0, 0xc420bd54d0, 0xc423b66870)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:195 +0xf3
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:188 +0xad

goroutine 156574 [semacquire]:
sync.runtime_notifyListWait(0xc421168f50, 0xc40000001c)
	/usr/local/go/src/runtime/sema.go:507 +0x110
sync.(*Cond).Wait(0xc421168f40)
	/usr/local/go/src/sync/cond.go:56 +0x80
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).worker(0xc422484120, 0x34589c0, 0xc422c242d0)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:197 +0x7c
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).Start.func2(0x34589c0, 0xc422c242d0)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:166 +0x3e
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc4203d6840, 0xc420bd54d0, 0xc4203d6830)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:195 +0xf3
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:188 +0xad

goroutine 156575 [semacquire]:
sync.runtime_notifyListWait(0xc421168f50, 0xc40000000d)
	/usr/local/go/src/runtime/sema.go:507 +0x110
sync.(*Cond).Wait(0xc421168f40)
	/usr/local/go/src/sync/cond.go:56 +0x80
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).worker(0xc422484120, 0x34589c0, 0xc422ad8540)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:197 +0x7c
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).Start.func2(0x34589c0, 0xc422ad8540)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:166 +0x3e
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc4203d6860, 0xc420bd54d0, 0xc4203d6850)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:195 +0xf3
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:188 +0xad

goroutine 156562 [semacquire]:
sync.runtime_notifyListWait(0xc421168f50, 0xc40000000f)
	/usr/local/go/src/runtime/sema.go:507 +0x110
sync.(*Cond).Wait(0xc421168f40)
	/usr/local/go/src/sync/cond.go:56 +0x80
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).worker(0xc422484120, 0x34589c0, 0xc420632900)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:197 +0x7c
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).Start.func2(0x34589c0, 0xc420632900)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:166 +0x3e
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc4203d6620, 0xc420bd54d0, 0xc4203d6610)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:195 +0xf3
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:188 +0xad

goroutine 156345 [chan receive]:
github.com/cockroachdb/cockroach/pkg/rpc.NewContext.func1(0x34589c0, 0xc420e6a000)
	/go/src/github.com/cockroachdb/cockroach/pkg/rpc/context.go:326 +0x51
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc4212184b0, 0xc420bd54d0, 0xc420301ac0)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:195 +0xf3
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:188 +0xad

goroutine 156568 [semacquire]:
sync.runtime_notifyListWait(0xc421168f50, 0xc400000008)
	/usr/local/go/src/runtime/sema.go:507 +0x110
sync.(*Cond).Wait(0xc421168f40)
	/usr/local/go/src/sync/cond.go:56 +0x80
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).worker(0xc422484120, 0x34589c0, 0xc4206328a0)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:197 +0x7c
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).Start.func2(0x34589c0, 0xc4206328a0)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:166 +0x3e
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc4203d66f0, 0xc420bd54d0, 0xc4203d66d0)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:195 +0xf3
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:188 +0xad

goroutine 156629 [select]:
github.com/cockroachdb/cockroach/pkg/server.(*Node).startGossip.func1(0x34589c0, 0xc422c24db0)
	/go/src/github.com/cockroachdb/cockroach/pkg/server/node.go:685 +0x2dd
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc4203d72e0, 0xc420bd54d0, 0xc42263bc40)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:195 +0xf3
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:188 +0xad

goroutine 156448 [runnable]:
math/big.nat.montgomery(0xc42075c000, 0x10, 0x24, 0xc4226e7e00, 0x10, 0x26, 0xc4228172c0, 0x10, 0x14, 0xc4215289a0, ...)
	/usr/local/go/src/math/big/nat.go:202 +0x379
math/big.nat.expNNMontgomery(0xc4226e7e00, 0x10, 0x26, 0xc420dc3d40, 0x10, 0x25, 0xc4226e77c0, 0x10, 0x25, 0xc4215289a0, ...)
	/usr/local/go/src/math/big/nat.go:1108 +0x755
math/big.nat.expNN(0x0, 0x0, 0x0, 0xc420dc3d40, 0x20, 0x45, 0xc4226e77c0, 0x10, 0x25, 0xc4215289a0, ...)
	/usr/local/go/src/math/big/nat.go:918 +0xa69
math/big.(*Int).Exp(0xc42415f5f8, 0xc42415f618, 0xc420300c40, 0xc420300b80, 0xc422907480)
	/usr/local/go/src/math/big/int.go:437 +0xf6
crypto/rsa.decrypt(0x34377c0, 0xc42007aa20, 0xc4230a42a0, 0xc42415f618, 0x0, 0x0, 0x0)
	/usr/local/go/src/crypto/rsa/rsa.go:525 +0x1c4
crypto/rsa.decryptAndCheck(0x34377c0, 0xc42007aa20, 0xc4230a42a0, 0xc42415f768, 0xc42415f768, 0x100, 0x0)
	/usr/local/go/src/crypto/rsa/rsa.go:559 +0x56
crypto/rsa.SignPKCS1v15(0x34377c0, 0xc42007aa20, 0xc4230a42a0, 0x5, 0xc42042ee80, 0x20, 0x20, 0xc42415f800, 0x855b2a, 0x10, ...)
	/usr/local/go/src/crypto/rsa/pkcs1v15.go:250 +0x2ca
crypto/rsa.(*PrivateKey).Sign(0xc4230a42a0, 0x34377c0, 0xc42007aa20, 0xc42042ee80, 0x20, 0x20, 0x343f680, 0xc4214d8da0, 0xc4206c9500, 0x8fc, ...)
	/usr/local/go/src/crypto/rsa/rsa.go:105 +0x15a
crypto/tls.(*clientHandshakeState).doFullHandshake(0xc42415fe88, 0xc4203124c0, 0x31)
	/usr/local/go/src/crypto/tls/handshake_client.go:456 +0x109d
crypto/tls.(*Conn).clientHandshake(0xc422f30700, 0x24151d8, 0xc422f30820)
	/usr/local/go/src/crypto/tls/handshake_client.go:228 +0xf9b
crypto/tls.(*Conn).Handshake(0xc422f30700, 0x0, 0x0)
	/usr/local/go/src/crypto/tls/conn.go:1307 +0x18f
github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/credentials.(*tlsCreds).ClientHandshake.func1(0xc422ff8540, 0xc422f30700)
	/go/src/github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/credentials/credentials.go:147 +0x2b
created by github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/credentials.(*tlsCreds).ClientHandshake
	/go/src/github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/credentials/credentials.go:146 +0x118

goroutine 156606 [semacquire]:
sync.runtime_notifyListWait(0xc421168f50, 0xc400000035)
	/usr/local/go/src/runtime/sema.go:507 +0x110
sync.(*Cond).Wait(0xc421168f40)
	/usr/local/go/src/sync/cond.go:56 +0x80
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).worker(0xc422484120, 0x34589c0, 0xc422ad88d0)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:197 +0x7c
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).Start.func2(0x34589c0, 0xc422ad88d0)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:166 +0x3e
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc4203d6d10, 0xc420bd54d0, 0xc4203d6d00)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:195 +0xf3
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:188 +0xad

goroutine 156593 [semacquire]:
sync.runtime_notifyListWait(0xc421168f50, 0xc40000002d)
	/usr/local/go/src/runtime/sema.go:507 +0x110
sync.(*Cond).Wait(0xc421168f40)
	/usr/local/go/src/sync/cond.go:56 +0x80
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).worker(0xc422484120, 0x34589c0, 0xc422ad8870)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:197 +0x7c
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).Start.func2(0x34589c0, 0xc422ad8870)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:166 +0x3e
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc4203d6ae0, 0xc420bd54d0, 0xc4203d6ad0)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:195 +0xf3
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:188 +0xad

goroutine 156662 [select]:
github.com/cockroachdb/cockroach/pkg/sql.(*DistSQLPlanner).initRunners.func1(0x34589c0, 0xc42041e900)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsql_running.go:86 +0x167
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc4203d7630, 0xc420bd54d0, 0xc4203d7620)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:195 +0xf3
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:188 +0xad

goroutine 156614 [semacquire]:
sync.runtime_notifyListWait(0xc421168f50, 0xc400000033)
	/usr/local/go/src/runtime/sema.go:507 +0x110
sync.(*Cond).Wait(0xc421168f40)
	/usr/local/go/src/sync/cond.go:56 +0x80
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).worker(0xc422484120, 0x34589c0, 0xc420632b40)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:197 +0x7c
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).Start.func2(0x34589c0, 0xc420632b40)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:166 +0x3e
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc4203d6e10, 0xc420bd54d0, 0xc4203d6e00)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:195 +0xf3
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:188 +0xad

goroutine 156567 [semacquire]:
sync.runtime_notifyListWait(0xc421168f50, 0xc400000015)
	/usr/local/go/src/runtime/sema.go:507 +0x110
sync.(*Cond).Wait(0xc421168f40)
	/usr/local/go/src/sync/cond.go:56 +0x80
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).worker(0xc422484120, 0x34589c0, 0xc420632990)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:197 +0x7c
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).Start.func2(0x34589c0, 0xc420632990)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:166 +0x3e
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc4203d66c0, 0xc420bd54d0, 0xc4203d66b0)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:195 +0xf3
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:188 +0xad

goroutine 156664 [select]:
github.com/cockroachdb/cockroach/pkg/sql.(*DistSQLPlanner).initRunners.func1(0x34589c0, 0xc42041e840)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsql_running.go:86 +0x167
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc4203d7670, 0xc420bd54d0, 0xc4203d7660)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:195 +0xf3
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:188 +0xad

goroutine 156431 [select]:
github.com/cockroachdb/cockroach/pkg/storage.(*baseQueue).processLoop.func1(0x34589c0, 0xc422ad8b70)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/queue.go:514 +0x1bb
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc420383c00, 0xc420bd54d0, 0xc422b9a140)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:195 +0xf3
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:188 +0xad

goroutine 156453 [select]:
github.com/cockroachdb/cockroach/pkg/kv.(*TxnCoordSender).heartbeatLoop(0xc4228c2380, 0x34589c0, 0xc4213660c0, 0x4431388c927c9d9, 0xa83089c90afb8993)
	/go/src/github.com/cockroachdb/cockroach/pkg/kv/txn_coord_sender.go:657 +0x361
github.com/cockroachdb/cockroach/pkg/kv.(*TxnCoordSender).updateState.func2(0x34589c0, 0xc42169c120)
	/go/src/github.com/cockroachdb/cockroach/pkg/kv/txn_coord_sender.go:964 +0x51
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunAsyncTask.func1(0xc420bd54d0, 0x34589c0, 0xc42169c120, 0xc4205840f0, 0x29, 0x3468020, 0xc4210b4750, 0xc422906000)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:266 +0xe6
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunAsyncTask
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:261 +0x133

goroutine 156494 [semacquire]:
sync.runtime_notifyListWait(0xc421168f50, 0xc400000043)
	/usr/local/go/src/runtime/sema.go:507 +0x110
sync.(*Cond).Wait(0xc421168f40)
	/usr/local/go/src/sync/cond.go:56 +0x80
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).worker(0xc422484120, 0x34589c0, 0xc420632810)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:197 +0x7c
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).Start.func2(0x34589c0, 0xc420632810)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:166 +0x3e
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc4203d65a0, 0xc420bd54d0, 0xc4203d6590)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:195 +0xf3
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:188 +0xad

goroutine 156599 [semacquire]:
sync.runtime_notifyListWait(0xc421168f50, 0xc400000025)
	/usr/local/go/src/runtime/sema.go:507 +0x110
sync.(*Cond).Wait(0xc421168f40)
	/usr/local/go/src/sync/cond.go:56 +0x80
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).worker(0xc422484120, 0x34589c0, 0xc422c24360)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:197 +0x7c
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).Start.func2(0x34589c0, 0xc422c24360)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:166 +0x3e
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc4203d6c30, 0xc420bd54d0, 0xc4203d6c20)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:195 +0xf3
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:188 +0xad

goroutine 156642 [select]:
github.com/cockroachdb/cockroach/pkg/storage.(*baseQueue).processLoop.func1(0x34589c0, 0xc420632cf0)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/queue.go:514 +0x1bb
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc420383c30, 0xc420bd54d0, 0xc422b9a1a0)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:195 +0xf3
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:188 +0xad

goroutine 156566 [semacquire]:
sync.runtime_notifyListWait(0xc421168f50, 0xc400000013)
	/usr/local/go/src/runtime/sema.go:507 +0x110
sync.(*Cond).Wait(0xc421168f40)
	/usr/local/go/src/sync/cond.go:56 +0x80
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).worker(0xc422484120, 0x34589c0, 0xc420632960)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:197 +0x7c
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).Start.func2(0x34589c0, 0xc420632960)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:166 +0x3e
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc4203d66a0, 0xc420bd54d0, 0xc4203d6690)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:195 +0xf3
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:188 +0xad

goroutine 156611 [semacquire]:
sync.runtime_notifyListWait(0xc421168f50, 0xc40000003c)
	/usr/local/go/src/runtime/sema.go:507 +0x110
sync.(*Cond).Wait(0xc421168f40)
	/usr/local/go/src/sync/cond.go:56 +0x80
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).worker(0xc422484120, 0x34589c0, 0xc420632ba0)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:197 +0x7c
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).Start.func2(0x34589c0, 0xc420632ba0)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:166 +0x3e
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc4203d6db0, 0xc420bd54d0, 0xc4203d6da0)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:195 +0xf3
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:188 +0xad

goroutine 156706 [select]:
github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/transport.loopyWriter(0x34589c0, 0xc4234a0750, 0xc4234a06f0, 0xc422941fb8)
	/go/src/github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/transport/transport.go:750 +0x2e4
github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/transport.newHTTP2Server.func1(0xc42367c2c0)
	/go/src/github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/transport/http2_server.go:227 +0x5e
created by github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/transport.newHTTP2Server
	/go/src/github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/transport/http2_server.go:226 +0x8d5

goroutine 156596 [semacquire]:
sync.runtime_notifyListWait(0xc421168f50, 0xc400000019)
	/usr/local/go/src/runtime/sema.go:507 +0x110
sync.(*Cond).Wait(0xc421168f40)
	/usr/local/go/src/sync/cond.go:56 +0x80
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).worker(0xc422484120, 0x34589c0, 0xc4206329f0)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:197 +0x7c
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).Start.func2(0x34589c0, 0xc4206329f0)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:166 +0x3e
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc4203d6b70, 0xc420bd54d0, 0xc4203d6b50)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:195 +0xf3
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:188 +0xad

goroutine 156640 [select]:
github.com/cockroachdb/cockroach/pkg/sql.(*DistSQLPlanner).initRunners.func1(0x34589c0, 0xc4245820f0)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsql_running.go:86 +0x167
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc4203d7570, 0xc420bd54d0, 0xc4203d7560)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:195 +0xf3
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:188 +0xad

goroutine 156623 [select]:
github.com/cockroachdb/cockroach/pkg/storage.(*Store).startGossip.func4(0x34589c0, 0xc422c24660)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/store.go:1416 +0x3e9
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc4203d6f60, 0xc420bd54d0, 0xc4215ef810)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:195 +0xf3
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:188 +0xad

goroutine 156632 [select]:
github.com/cockroachdb/cockroach/pkg/storage.(*Replica).tryExecuteWriteBatch(0xc422cf6700, 0x34589c0, 0xc422cc7e60, 0x1508e542bd6746e1, 0x0, 0x100000001, 0x1, 0x1, 0x0, 0x0, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/replica.go:2773 +0x62a
github.com/cockroachdb/cockroach/pkg/storage.(*Replica).executeWriteBatch(0xc422cf6700, 0x34589c0, 0xc422cc7e60, 0x1508e542bd6746e1, 0x0, 0x100000001, 0x1, 0x1, 0x0, 0x0, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/replica.go:2601 +0xae
github.com/cockroachdb/cockroach/pkg/storage.(*Replica).Send(0xc422cf6700, 0x34589c0, 0xc422cc7e60, 0x1508e542bd6746e1, 0x0, 0x100000001, 0x1, 0x1, 0x0, 0x0, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/replica.go:1913 +0x6a5
github.com/cockroachdb/cockroach/pkg/storage.(*Store).Send(0xc4206fc800, 0x34589c0, 0xc422cc7e00, 0x1508e542bd6746e1, 0x0, 0x100000001, 0x1, 0x1, 0x0, 0x0, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/store.go:2688 +0x688
github.com/cockroachdb/cockroach/pkg/storage.(*Stores).Send(0xc422f76580, 0x34589c0, 0xc422cc7d70, 0x0, 0x0, 0x100000001, 0x1, 0x1, 0x0, 0x0, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/stores.go:214 +0x214
github.com/cockroachdb/cockroach/pkg/server.(*Node).batchInternal.func1(0x34589c0, 0xc422cc7d70, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/pkg/server/node.go:865 +0x192
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunTaskWithErr(0xc420bd54d0, 0x34589c0, 0xc422cc7d40, 0x233a906, 0x10, 0xc420915598, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:245 +0xf7
github.com/cockroachdb/cockroach/pkg/server.(*Node).batchInternal(0xc423c21800, 0x34589c0, 0xc422cc7d40, 0xc422e2f4b8, 0xc422cc7d40, 0x14ee93e, 0x34589c0)
	/go/src/github.com/cockroachdb/cockroach/pkg/server/node.go:852 +0x152
github.com/cockroachdb/cockroach/pkg/server.(*Node).Batch(0xc423c21800, 0x34589c0, 0xc422cc7d40, 0xc422e2f4b8, 0x1f, 0x91955a, 0xc42395e6c0)
	/go/src/github.com/cockroachdb/cockroach/pkg/server/node.go:893 +0x99
github.com/cockroachdb/cockroach
```

Please assign, take a look and update the issue accordingly.

### LINKED ISSUE #21423: teamcity: failed tests on master: test/TestBackupRestoreIncrementalAddTableMissing, testrace/TestBackupRestoreIncrementalAddTableMissing
The following tests appear to have failed:

[#477021](https://teamcity.cockroachdb.com/viewLog.html?buildId=477021):

```
--- FAIL: test/TestBackupRestoreIncrementalAddTableMissing (0.000s)
Test ended in panic.

------- Stdout: -------
W180112 19:51:13.440830 174980 server/status/runtime.go:109  Could not parse build timestamp: parsing time "" as "2006/01/02 15:04:05": cannot parse "" as "2006"
I180112 19:51:13.443253 174980 server/config.go:518  [n?] 1 storage engine initialized
I180112 19:51:13.443279 174980 server/config.go:521  [n?] RocksDB cache size: 128 MiB
I180112 19:51:13.443285 174980 server/config.go:521  [n?] store 0: in-memory, size 0 B
I180112 19:51:13.447618 174980 server/node.go:361  [n?] **** cluster 13e52292-9395-47cd-8b89-39b6e1559a74 has been created
I180112 19:51:13.447657 174980 server/server.go:937  [n?] **** add additional nodes by specifying --join=127.0.0.1:33205
I180112 19:51:13.448876 174980 storage/store.go:1312  [n1,s1] [n1,s1]: failed initial metrics computation: [n1,s1]: system config not yet available
I180112 19:51:13.448935 174980 server/node.go:491  [n1] initialized store [n1,s1]: disk (capacity=512 MiB, available=512 MiB, used=0 B, logicalBytes=3.2 KiB), ranges=1, leases=0, writes=0.00, bytesPerReplica={p10=3322.00 p25=3322.00 p50=3322.00 p75=3322.00 p90=3322.00}, writesPerReplica={p10=0.00 p25=0.00 p50=0.00 p75=0.00 p90=0.00}
I180112 19:51:13.448956 174980 server/node.go:339  [n1] node ID 1 initialized
I180112 19:51:13.449005 174980 gossip/gossip.go:332  [n1] NodeDescriptor set to node_id:1 address:<network_field:"tcp" address_field:"127.0.0.1:33205" > attrs:<> locality:<> ServerVersion:<major_val:1 minor_val:1 patch:0 unstable:9 > 
I180112 19:51:13.449138 174980 storage/stores.go:331  [n1] read 0 node addresses from persistent storage
I180112 19:51:13.449211 174980 server/node.go:632  [n1] connecting to gossip network to verify cluster ID...
I180112 19:51:13.449237 174980 server/node.go:657  [n1] node connected via gossip and verified as part of cluster "13e52292-9395-47cd-8b89-39b6e1559a74"
I180112 19:51:13.449256 174980 server/node.go:433  [n1] node=1: started with [<no-attributes>=<in-mem>] engine(s) and attributes []
I180112 19:51:13.449297 174980 sql/distsql_physical_planner.go:122  [n1] creating DistSQLPlanner with address {tcp 127.0.0.1:33205}
I180112 19:51:13.450857 175015 storage/replica_command.go:819  [split,n1,s1,r1/1:/M{in-ax}] initiating a split of this range at key /System/"" [r2]
I180112 19:51:13.452347 174980 server/server.go:1164  [n1] starting https server at 127.0.0.1:46301
I180112 19:51:13.452465 174980 server/server.go:1165  [n1] starting grpc/postgres server at 127.0.0.1:33205
I180112 19:51:13.452479 174980 server/server.go:1166  [n1] advertising CockroachDB node at 127.0.0.1:33205
I180112 19:51:13.464552 175015 storage/replica_command.go:819  [split,n1,s1,r2/1:/{System/-Max}] initiating a split of this range at key /System/NodeLiveness [r3]
I180112 19:51:13.465106 174980 sql/event_log.go:115  [n1] Event: "alter_table", target: 12, info: {TableName:eventlog Statement:ALTER TABLE system.eventlog ALTER COLUMN "uniqueID" SET DEFAULT uuid_v4() User:node MutationID:0 CascadeDroppedViews:[]}
I180112 19:51:13.469772 175015 storage/replica_command.go:819  [split,n1,s1,r3/1:/{System/NodeL…-Max}] initiating a split of this range at key /System/NodeLivenessMax [r4]
I180112 19:51:13.470633 174980 sql/lease.go:348  [n1] publish: descID=12 (eventlog) version=2 mtime=2018-01-12 19:51:13.469865477 +0000 UTC
I180112 19:51:13.477916 175015 storage/replica_command.go:819  [split,n1,s1,r4/1:/{System/NodeL…-Max}] initiating a split of this range at key /System/tsd [r5]
I180112 19:51:13.480019 174980 sql/event_log.go:115  [n1] Event: "set_cluster_setting", target: 0, info: {SettingName:diagnostics.reporting.enabled Value:true User:node}
I180112 19:51:13.482534 175015 storage/replica_command.go:819  [split,n1,s1,r5/1:/{System/tsd-Max}] initiating a split of this range at key /System/"tse" [r6]
I180112 19:51:13.489827 175015 storage/replica_command.go:819  [split,n1,s1,r6/1:/{System/tse-Max}] initiating a split of this range at key /Table/SystemConfigSpan/Start [r7]
I180112 19:51:13.497823 175015 storage/replica_command.go:819  [split,n1,s1,r7/1:/{Table/System…-Max}] initiating a split of this range at key /Table/11 [r8]
W180112 19:51:13.498080 175304 storage/intent_resolver.go:324  [n1,s1] failed to push during intent resolution: failed to push "sql txn implicit" id=0ade674c key=/Table/SystemConfigSpan/Start rw=true pri=0.01216517 iso=SERIALIZABLE stat=PENDING epo=0 ts=1515786673.485443784,0 orig=1515786673.485443784,0 max=1515786673.485443784,0 wto=false rop=false seq=15
I180112 19:51:13.499618 174980 sql/event_log.go:115  [n1] Event: "set_cluster_setting", target: 0, info: {SettingName:version Value:$1 User:node}
I180112 19:51:13.502515 175015 storage/replica_command.go:819  [split,n1,s1,r8/1:/{Table/11-Max}] initiating a split of this range at key /Table/12 [r9]
I180112 19:51:13.505068 174980 sql/event_log.go:115  [n1] Event: "set_cluster_setting", target: 0, info: {SettingName:trace.debug.enable Value:false User:node}
I180112 19:51:13.506370 175015 storage/replica_command.go:819  [split,n1,s1,r9/1:/{Table/12-Max}] initiating a split of this range at key /Table/13 [r10]
I180112 19:51:13.509203 175015 storage/replica_command.go:819  [split,n1,s1,r10/1:/{Table/13-Max}] initiating a split of this range at key /Table/14 [r11]
I180112 19:51:13.513390 175015 storage/replica_command.go:819  [split,n1,s1,r11/1:/{Table/14-Max}] initiating a split of this range at key /Table/15 [r12]
I180112 19:51:13.516111 175015 storage/replica_command.go:819  [split,n1,s1,r12/1:/{Table/15-Max}] initiating a split of this range at key /Table/16 [r13]
I180112 19:51:13.516693 174980 sql/event_log.go:115  [n1] Event: "alter_table", target: 4, info: {TableName:users Statement:ALTER TABLE system.users ADD COLUMN IF NOT EXISTS "isRole" BOOL NOT NULL DEFAULT false User:node MutationID:1 CascadeDroppedViews:[]}
I180112 19:51:13.520589 174980 sql/lease.go:348  [n1] publish: descID=4 (users) version=2 mtime=2018-01-12 19:51:13.520468009 +0000 UTC
I180112 19:51:13.523756 175015 storage/replica_command.go:819  [split,n1,s1,r13/1:/{Table/16-Max}] initiating a split of this range at key /Table/17 [r14]
I180112 19:51:13.526626 174980 sql/lease.go:348  [n1] publish: descID=4 (users) version=3 mtime=2018-01-12 19:51:13.526453029 +0000 UTC
I180112 19:51:13.527212 175015 storage/replica_command.go:819  [split,n1,s1,r14/1:/{Table/17-Max}] initiating a split of this range at key /Table/18 [r15]
I180112 19:51:13.530677 174980 sql/backfill.go:133  [n1] Running backfill for "users", v=3, m=1
I180112 19:51:13.530697 175015 storage/replica_command.go:819  [split,n1,s1,r15/1:/{Table/18-Max}] initiating a split of this range at key /Table/19 [r16]
I180112 19:51:13.534068 175015 storage/replica_command.go:819  [split,n1,s1,r16/1:/{Table/19-Max}] initiating a split of this range at key /Table/20 [r17]
I180112 19:51:13.536901 175015 storage/replica_command.go:819  [split,n1,s1,r17/1:/{Table/20-Max}] initiating a split of this range at key /Table/21 [r18]
I180112 19:51:13.539472 174980 sql/lease.go:348  [n1] publish: descID=4 (users) version=4 mtime=2018-01-12 19:51:13.53936217 +0000 UTC
I180112 19:51:13.540169 175015 storage/replica_command.go:819  [split,n1,s1,r18/1:/{Table/21-Max}] initiating a split of this range at key /Table/22 [r19]
I180112 19:51:13.543171 175015 storage/replica_command.go:819  [split,n1,s1,r19/1:/{Table/22-Max}] initiating a split of this range at key /Table/23 [r20]
I180112 19:51:13.543587 174980 sql/event_log.go:115  [n1] Event: "finish_schema_change", target: 4, info: {MutationID:1}
I180112 19:51:13.544512 174980 sql/lease.go:274  publish (count leases): descID=4 name=users version=3 count=1
I180112 19:51:13.574610 174980 server/server.go:1235  [n1] done ensuring all necessary migrations have run
I180112 19:51:13.574660 174980 server/server.go:1238  [n1] serving sql connections
I180112 19:51:13.576700 175452 sql/event_log.go:115  [n1] Event: "node_join", target: 1, info: {Descriptor:{NodeID:1 Address:{NetworkField:tcp AddressField:127.0.0.1:33205} Attrs: Locality: ServerVersion:1.1-9} ClusterID:13e52292-9395-47cd-8b89-39b6e1559a74 StartedAt:1515786673449242163 LastUp:1515786673449242163}
I180112 19:51:13.588856 175457 sql/event_log.go:115  [client=127.0.0.1:43210,user=root,n1] Event: "create_database", target: 50, info: {DatabaseName:data Statement:CREATE DATABASE data User:root}
I180112 19:51:13.589199 175015 storage/replica_command.go:819  [split,n1,s1,r20/1:/{Table/23-Max}] initiating a split of this range at key /Table/50 [r21]
I180112 19:51:13.592552 175457 sql/event_log.go:115  [client=127.0.0.1:43210,user=root,n1] Event: "create_table", target: 51, info: {TableName:bank Statement:CREATE TABLE bank (id INT PRIMARY KEY, balance INT, payload STRING, FAMILY (id, balance, payload)) User:root}
I180112 19:51:13.593272 175015 storage/replica_command.go:819  [split,n1,s1,r21/1:/{Table/50-Max}] initiating a split of this range at key /Table/51 [r22]
I180112 19:51:13.598043 175457 sql/event_log.go:115  [client=127.0.0.1:43210,user=root,n1] Event: "create_database", target: 52, info: {DatabaseName:data2 Statement:CREATE DATABASE data2 User:root}
I180112 19:51:13.598397 175015 storage/replica_command.go:819  [split,n1,s1,r22/1:/{Table/51-Max}] initiating a split of this range at key /Table/52 [r23]
I180112 19:51:13.602192 175457 sql/event_log.go:115  [client=127.0.0.1:43210,user=root,n1] Event: "create_table", target: 53, info: {TableName:data.t Statement:CREATE TABLE data.t (s STRING PRIMARY KEY) User:root}
I180112 19:51:13.602541 175015 storage/replica_command.go:819  [split,n1,s1,r23/1:/{Table/52-Max}] initiating a split of this range at key /Table/53 [r24]
I180112 19:51:13.614255 175590 ccl/storageccl/export.go:124  [n1,s1,r24/1:/{Table/53-Max}] export [/Table/53/1,/Table/53/2)
I180112 19:51:13.614365 175589 ccl/storageccl/export.go:124  [n1,s1,r22/1:/Table/5{1-2}] export [/Table/51/1,/Table/51/2)
panic: test timed out after 4m0s

goroutine 175572 [running]:
testing.startAlarm.func1()
	/usr/local/go/src/testing/testing.go:1145 +0xf9
created by time.goFunc
	/usr/local/go/src/time/sleep.go:170 +0x44

goroutine 1 [chan receive]:
testing.(*T).Run(0xc4200ae690, 0x23768b2, 0x2b, 0x2414418, 0x8d4f01)
	/usr/local/go/src/testing/testing.go:790 +0x2fc
testing.runTests.func1(0xc4200ae690)
	/usr/local/go/src/testing/testing.go:1004 +0x64
testing.tRunner(0xc4200ae690, 0xc420731db8)
	/usr/local/go/src/testing/testing.go:746 +0xd0
testing.runTests(0xc4204c0180, 0x34314a0, 0x39, 0x39, 0x0)
	/usr/local/go/src/testing/testing.go:1002 +0x2d8
testing.(*M).Run(0xc420abdf18, 0x2414788)
	/usr/local/go/src/testing/testing.go:921 +0x111
github.com/cockroachdb/cockroach/pkg/ccl/sqlccl.TestMain(0xc420731f18)
	/go/src/github.com/cockroachdb/cockroach/pkg/ccl/sqlccl/main_test.go:31 +0xda
main.main()
	github.com/cockroachdb/cockroach/pkg/ccl/sqlccl/_test/_testmain.go:174 +0xdb

goroutine 6 [chan receive]:
github.com/cockroachdb/cockroach/pkg/util/log.(*loggingT).flushDaemon(0x3682700)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/log/clog.go:1043 +0x81
created by github.com/cockroachdb/cockroach/pkg/util/log.init.0
	/go/src/github.com/cockroachdb/cockroach/pkg/util/log/clog.go:581 +0xbf

goroutine 7 [syscall, 4 minutes]:
os/signal.signal_recv(0x0)
	/usr/local/go/src/runtime/sigqueue.go:131 +0xa6
os/signal.loop()
	/usr/local/go/src/os/signal/signal_unix.go:22 +0x22
created by os/signal.init.0
	/usr/local/go/src/os/signal/signal_unix.go:28 +0x41

goroutine 66 [select, locked to thread]:
runtime.gopark(0x24182e8, 0x0, 0x232e255, 0x6, 0x18, 0x1)
	/usr/local/go/src/runtime/proc.go:277 +0x12c
runtime.selectgo(0xc420c54f50, 0xc420536540)
	/usr/local/go/src/runtime/select.go:395 +0x1138
runtime.ensureSigM.func1()
	/usr/local/go/src/runtime/signal_unix.go:511 +0x220
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:2337 +0x1

goroutine 174984 [select]:
github.com/cockroachdb/cockroach/pkg/sql.(*LeaseManager).RefreshLeases.func1(0x345c9e0, 0xc42067a2d0)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/lease.go:1469 +0x912
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc422df08d0, 0xc4225c21b0, 0xc42169d860)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:195 +0xf3
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:188 +0xad

goroutine 175221 [select]:
github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc.(*addrConn).transportMonitor(0xc420316200)
	/go/src/github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/clientconn.go:1002 +0x166
github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc.(*addrConn).connect.func1(0xc420316200)
	/go/src/github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/clientconn.go:703 +0x1ce
created by github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc.(*addrConn).connect
	/go/src/github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/clientconn.go:694 +0x40d

goroutine 175115 [semacquire]:
sync.runtime_notifyListWait(0xc422b342d0, 0xc400000186)
	/usr/local/go/src/runtime/sema.go:507 +0x110
sync.(*Cond).Wait(0xc422b342c0)
	/usr/local/go/src/sync/cond.go:56 +0x80
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).worker(0xc421b08090, 0x345c9e0, 0xc42201c0f0)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:197 +0x7c
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).Start.func2(0x345c9e0, 0xc42201c0f0)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:166 +0x3e
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc420440500, 0xc4225c21b0, 0xc4204404e0)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:195 +0xf3
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:188 +0xad

goroutine 175451 [chan receive]:
github.com/cockroachdb/cockroach/vendor/github.com/cockroachdb/cmux.muxListener.Accept(...)
	/go/src/github.com/cockroachdb/cockroach/vendor/github.com/cockroachdb/cmux/cmux.go:184
github.com/cockroachdb/cockroach/vendor/github.com/cockroachdb/cmux.(*muxListener).Accept(0xc421e33aa0, 0x2416490, 0xc4225c21b0, 0x345c9e0, 0xc4206db620)
	<autogenerated>:1 +0x65
github.com/cockroachdb/cockroach/pkg/util/netutil.(*Server).ServeWith(0xc4225f6108, 0x345c9e0, 0xc4206db620, 0xc4225c21b0, 0x345bb60, 0xc421e33aa0, 0xc4206db650, 0xc4206db620, 0xc423bab6d0)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/netutil/net.go:119 +0x50
github.com/cockroachdb/cockroach/pkg/server.(*Server).Start.func17(0x345c9e0, 0xc4206db620)
	/go/src/github.com/cockroachdb/cockroach/pkg/server/server.go:1248 +0x1f5
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc42024bf50, 0xc4225c21b0, 0xc420b39c00)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:195 +0xf3
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:188 +0xad

goroutine 175195 [select]:
github.com/cockroachdb/cockroach/pkg/sql.(*DistSQLPlanner).initRunners.func1(0x345c9e0, 0xc421393590)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsql_running.go:86 +0x167
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc4203d63a0, 0xc4225c21b0, 0xc4203d6390)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:195 +0xf3
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:188 +0xad

goroutine 174998 [select]:
github.com/cockroachdb/cockroach/pkg/storage.(*baseQueue).maybeAddToPurgatory.func2(0x345c9e0, 0xc422980ba0)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/queue.go:705 +0x434
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc42039c2b0, 0xc4225c21b0, 0xc420240700)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:195 +0xf3
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:188 +0xad

goroutine 175116 [semacquire]:
sync.runtime_notifyListWait(0xc422b342d0, 0xc400000187)
	/usr/local/go/src/runtime/sema.go:507 +0x110
sync.(*Cond).Wait(0xc422b342c0)
	/usr/local/go/src/sync/cond.go:56 +0x80
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).worker(0xc421b08090, 0x345c9e0, 0xc42201c120)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:197 +0x7c
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).Start.func2(0x345c9e0, 0xc42201c120)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:166 +0x3e
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc420440570, 0xc4225c21b0, 0xc420440510)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:195 +0xf3
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:188 +0xad

goroutine 175150 [semacquire]:
sync.runtime_notifyListWait(0xc422b342d0, 0xc40000016b)
	/usr/local/go/src/runtime/sema.go:507 +0x110
sync.(*Cond).Wait(0xc422b342c0)
	/usr/local/go/src/sync/cond.go:56 +0x80
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).worker(0xc421b08090, 0x345c9e0, 0xc420e6a630)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:197 +0x7c
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).Start.func2(0x345c9e0, 0xc420e6a630)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:166 +0x3e
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc420440ae0, 0xc4225c21b0, 0xc420440ad0)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:195 +0xf3
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:188 +0xad

goroutine 175209 [select]:
github.com/cockroachdb/cockroach/pkg/sql.(*Executor).Start.func1(0x345c9e0, 0xc421393620)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/executor.go:417 +0x122
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc4203d65e0, 0xc4225c21b0, 0xc42183e1e0)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:195 +0xf3
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:188 +0xad

goroutine 175235 [select]:
github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/transport.(*http2Server).keepalive(0xc423bc4160)
	/go/src/github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/transport/http2_server.go:935 +0x264
created by github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/transport.newHTTP2Server
	/go/src/github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/transport/http2_server.go:230 +0x8fa

goroutine 174980 [IO wait]:
internal/poll.runtime_pollWait(0x2b3097800908, 0x72, 0x0)
	/usr/local/go/src/runtime/netpoll.go:173 +0x57
internal/poll.(*pollDesc).wait(0xc421377918, 0x72, 0xffffffffffffff00, 0x3446760, 0x3439638)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:85 +0xae
internal/poll.(*pollDesc).waitRead(0xc421377918, 0xc421472400, 0x400, 0x400)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:90 +0x3d
internal/poll.(*FD).Read(0xc421377900, 0xc421472400, 0x400, 0x400, 0x0, 0x0, 0x0)
	/usr/local/go/src/internal/poll/fd_unix.go:125 +0x18a
net.(*netFD).Read(0xc421377900, 0xc421472400, 0x400, 0x400, 0x3f3, 0x0, 0x0)
	/usr/local/go/src/net/fd_unix.go:202 +0x52
net.(*conn).Read(0xc4204a48e0, 0xc421472400, 0x400, 0x400, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/net.go:176 +0x6d
crypto/tls.(*block).readFromUntil(0xc422fce0f0, 0x2b30989c3c30, 0xc4204a48e0, 0x5, 0xc4204a48e0, 0x2b309782cc78)
	/usr/local/go/src/crypto/tls/conn.go:488 +0x95
crypto/tls.(*Conn).readRecord(0xc421ef8000, 0x2418417, 0xc421ef8120, 0xc421472005)
	/usr/local/go/src/crypto/tls/conn.go:590 +0xe0
crypto/tls.(*Conn).Read(0xc421ef8000, 0xc42050b000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/go/src/crypto/tls/conn.go:1134 +0x110
bufio.(*Reader).Read(0xc421a8a120, 0xc4211322e0, 0x5, 0x200, 0xc423cdb528, 0x8719e8, 0x2413e20)
	/usr/local/go/src/bufio/bufio.go:213 +0x30b
io.ReadAtLeast(0x343b520, 0xc421a8a120, 0xc4211322e0, 0x5, 0x200, 0x5, 0x857967, 0xc423d6aa80, 0x20)
	/usr/local/go/src/io/io.go:309 +0x86
io.ReadFull(0x343b520, 0xc421a8a120, 0xc4211322e0, 0x5, 0x200, 0x2b309783ed18, 0x0, 0xc4201ea4a8)
	/usr/local/go/src/io/io.go:327 +0x58
github.com/cockroachdb/cockroach/vendor/github.com/lib/pq.(*conn).recvMessage(0xc4211322c0, 0xc423d6aa80, 0x202e320, 0x1, 0x36cdb98)
	/go/src/github.com/cockroachdb/cockroach/vendor/github.com/lib/pq/conn.go:947 +0x14e
github.com/cockroachdb/cockroach/vendor/github.com/lib/pq.(*conn).recv1Buf(0xc4211322c0, 0xc423d6aa80, 0xc4211322e0)
	/go/src/github.com/cockroachdb/cockroach/vendor/github.com/lib/pq/conn.go:997 +0x39
github.com/cockroachdb/cockroach/vendor/github.com/lib/pq.(*conn).recv1(0xc4211322c0, 0xc421ef8000, 0xc4211322e0)
	/go/src/github.com/cockroachdb/cockroach/vendor/github.com/lib/pq/conn.go:1018 +0x85
github.com/cockroachdb/cockroach/vendor/github.com/lib/pq.(*conn).readBindResponse(0xc4211322c0)
	/go/src/github.com/cockroachdb/cockroach/vendor/github.com/lib/pq/conn.go:1633 +0x2f
github.com/cockroachdb/cockroach/vendor/github.com/lib/pq.(*stmt).exec(0xc42132aa00, 0xc42032fb20, 0x1, 0x1)
	/go/src/github.com/cockroachdb/cockroach/vendor/github.com/lib/pq/conn.go:1270 +0x979
github.com/cockroachdb/cockroach/vendor/github.com/lib/pq.(*stmt).Exec(0xc42132aa00, 0xc42032fb20, 0x1, 0x1, 0x0, 0x0, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/vendor/github.com/lib/pq/conn.go:1228 +0xc3
github.com/cockroachdb/cockroach/vendor/github.com/lib/pq.(*conn).Exec(0xc4211322c0, 0x2341a91, 0x13, 0xc42032fb20, 0x1, 0x1, 0x0, 0x0, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/vendor/github.com/lib/pq/conn.go:893 +0x1f5
github.com/cockroachdb/cockroach/vendor/github.com/lib/pq.(*conn).ExecContext(0xc4211322c0, 0x345c960, 0xc420016108, 0x2341a91, 0x13, 0xc420601500, 0x1, 0x1, 0x0, 0x0, ...)
	/go/src/github.com/cockroachdb/cockroach/vendor/github.com/lib/pq/conn_go18.go:43 +0x224
database/sql.ctxDriverExec(0x345c960, 0xc420016108, 0x2b30977b6248, 0xc4211322c0, 0x2341a91, 0x13, 0xc420601500, 0x1, 0x1, 0x871329, ...)
	/usr/local/go/src/database/sql/ctxutil.go:31 +0x277
database/sql.(*DB).execDC.func2()
	/usr/local/go/src/database/sql/sql.go:1253 +0x99
database/sql.withLock(0x3447520, 0xc4226c1e30, 0xc423cdbba8)
	/usr/local/go/src/database/sql/sql.go:2855 +0x65
database/sql.(*DB).execDC(0xc42297e000, 0x345c960, 0xc420016108, 0xc4226c1e30, 0xc423cdbc88, 0x2341a91, 0x13, 0xc420d4df28, 0x1, 0x1, ...)
	/usr/local/go/src/database/sql/sql.go:1252 +0x4e4
database/sql.(*DB).exec(0xc42297e000, 0x345c960, 0xc420016108, 0x2341a91, 0x13, 0xc423cdbf28, 0x1, 0x1, 0x1b14701, 0xc420024070, ...)
	/usr/local/go/src/database/sql/sql.go:1238 +0x13e
database/sql.(*DB).ExecContext(0xc42297e000, 0x345c960, 0xc420016108, 0x2341a91, 0x13, 0xc420d4df28, 0x1, 0x1, 0x309aea8, 0x49, ...)
	/usr/local/go/src/database/sql/sql.go:1216 +0xe1
database/sql.(*DB).Exec(0xc42297e000, 0x2341a91, 0x13, 0xc423cdbf28, 0x1, 0x1, 0x344bce0, 0xc42283b680, 0x0, 0x0)
	/usr/local/go/src/database/sql/sql.go:1230 +0x85
github.com/cockroachdb/cockroach/pkg/testutils/sqlutils.(*SQLRunner).Exec(0xc4204a48d8, 0x346d760, 0xc4224fa000, 0x2341a91, 0x13, 0xc423cdbf28, 0x1, 0x1, 0x344bce0, 0xc42283b680)
	/go/src/github.com/cockroachdb/cockroach/pkg/testutils/sqlutils/sql_runner.go:38 +0x9e
github.com/cockroachdb/cockroach/pkg/ccl/sqlccl_test.TestBackupRestoreIncrementalAddTableMissing(0xc4224fa000)
	/go/src/github.com/cockroachdb/cockroach/pkg/ccl/sqlccl/backup_test.go:2466 +0x351
testing.tRunner(0xc4224fa000, 0x2414418)
	/usr/local/go/src/testing/testing.go:746 +0xd0
created by testing.(*T).Run
	/usr/local/go/src/testing/testing.go:789 +0x2de

goroutine 175140 [semacquire]:
sync.runtime_notifyListWait(0xc422b342d0, 0xc40000019c)
	/usr/local/go/src/runtime/sema.go:507 +0x110
sync.(*Cond).Wait(0xc422b342c0)
	/usr/local/go/src/sync/cond.go:56 +0x80
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).worker(0xc421b08090, 0x345c9e0, 0xc4220e47e0)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:197 +0x7c
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).Start.func2(0x345c9e0, 0xc4220e47e0)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:166 +0x3e
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc420440890, 0xc4225c21b0, 0xc420440880)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:195 +0xf3
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:188 +0xad

goroutine 175194 [select]:
github.com/cockroachdb/cockroach/pkg/sql.(*DistSQLPlanner).initRunners.func1(0x345c9e0, 0xc4213935c0)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsql_running.go:86 +0x167
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc4203d6370, 0xc4225c21b0, 0xc4203d6360)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:195 +0xf3
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:188 +0xad

goroutine 175179 [select]:
github.com/cockroachdb/cockroach/pkg/storage.(*Store).Start.func2(0x345c9e0, 0xc4220e49f0)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/store.go:1282 +0x122
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc420440ed0, 0xc4225c21b0, 0xc423adeec0)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:195 +0xf3
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:188 +0xad

goroutine 175022 [select]:
github.com/cockroachdb/cockroach/pkg/storage.(*replicaScanner).waitAndProcess(0xc4204a8300, 0x345c9e0, 0xc42201c6c0, 0x1ac57879, 0xed1eb08b1, 0x0, 0xc4207d2100, 0xc4225c21b0, 0xc42230f180, 0xc42230f280)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scanner.go:207 +0x226
github.com/cockroachdb/cockroach/pkg/storage.(*replicaScanner).scanLoop.func1.1(0xc42230f180, 0xc421392690)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scanner.go:269 +0x90
github.com/cockroachdb/cockroach/pkg/storage.(*storeReplicaVisitor).Visit(0xc421392690, 0xc42380a000)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/store.go:322 +0x1ba
github.com/cockroachdb/cockroach/pkg/storage.(*replicaScanner).scanLoop.func1(0x345c9e0, 0xc42201c6c0)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scanner.go:267 +0x1f5
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc422df00d0, 0xc4225c21b0, 0xc42037e1c0)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:195 +0xf3
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:188 +0xad

goroutine 175177 [select]:
github.com/cockroachdb/cockroach/pkg/storage.(*Store).raftTickLoop(0xc4211c0400, 0x345c9e0, 0xc4220e4a50)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/store.go:3850 +0x205
github.com/cockroachdb/cockroach/pkg/storage.(*Store).(github.com/cockroachdb/cockroach/pkg/storage.raftTickLoop)-fm(0x345c9e0, 0xc4220e4a50)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/store.go:3836 +0x3e
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc420440e80, 0xc4225c21b0, 0xc420440e70)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:195 +0xf3
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:188 +0xad

goroutine 175168 [semacquire]:
sync.runtime_notifyListWait(0xc422b342d0, 0xc400000166)
	/usr/local/go/src/runtime/sema.go:507 +0x110
sync.(*Cond).Wait(0xc422b342c0)
	/usr/local/go/src/sync/cond.go:56 +0x80
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).worker(0xc421b08090, 0x345c9e0, 0xc4220e4870)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:197 +0x7c
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).Start.func2(0x345c9e0, 0xc4220e4870)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:166 +0x3e
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc420440d60, 0xc4225c21b0, 0xc420440d50)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:195 +0xf3
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:188 +0xad

goroutine 175208 [select]:
github.com/cockroachdb/cockroach/pkg/sql.(*SchemaChangeManager).Start.func1(0x345c9e0, 0xc4213935f0)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/schema_changer.go:1028 +0x96d
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc4203d65d0, 0xc4225c21b0, 0xc42183e1a0)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:195 +0xf3
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:188 +0xad

goroutine 175128 [semacquire]:
sync.runtime_notifyListWait(0xc422b342d0, 0xc400000191)
	/usr/local/go/src/runtime/sema.go:507 +0x110
sync.(*Cond).Wait(0xc422b342c0)
	/usr/local/go/src/sync/cond.go:56 +0x80
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).worker(0xc421b08090, 0x345c9e0, 0xc42201c330)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:197 +0x7c
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).Start.func2(0x345c9e0, 0xc42201c330)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:166 +0x3e
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc4204406f0, 0xc4225c21b0, 0xc4204406e0)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:195 +0xf3
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:188 +0xad

goroutine 175163 [semacquire]:
sync.runtime_notifyListWait(0xc422b342d0, 0xc400000171)
	/usr/local/go/src/runtime/sema.go:507 +0x110
sync.(*Cond).Wait(0xc422b342c0)
	/usr/local/go/src/sync/cond.go:56 +0x80
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).worker(0xc421b08090, 0x345c9e0, 0xc420e6a660)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:197 +0x7c
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).Start.func2(0x345c9e0, 0xc420e6a660)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:166 +0x3e
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc420440cc0, 0xc4225c21b0, 0xc420440cb0)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:195 +0xf3
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:188 +0xad

goroutine 175214 [select]:
github.com/cockroachdb/cockroach/pkg/sql/jobs.(*Registry).Start.func2(0x345c9e0, 0xc420557950)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/jobs/registry.go:205 +0x13b
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc42186f8a0, 0xc4225c21b0, 0xc420557830)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:195 +0xf3
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:188 +0xad

goroutine 175153 [semacquire]:
sync.runtime_notifyListWait(0xc422b342d0, 0xc40000016d)
	/usr/local/go/src/runtime/sema.go:507 +0x110
sync.(*Cond).Wait(0xc422b342c0)
	/usr/local/go/src/sync/cond.go:56 +0x80
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).worker(0xc421b08090, 0x345c9e0, 0xc42201c4e0)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:197 +0x7c
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).Start.func2(0x345c9e0, 0xc42201c4e0)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:166 +0x3e
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc420440b60, 0xc4225c21b0, 0xc420440b50)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:195 +0xf3
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:188 +0xad

goroutine 175155 [semacquire]:
sync.runtime_notifyListWait(0xc422b342d0, 0xc400000168)
	/usr/local/go/src/runtime/sema.go:507 +0x110
sync.(*Cond).Wait(0xc422b342c0)
	/usr/local/go/src/sync/cond.go:56 +0x80
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).worker(0xc421b08090, 0x345c9e0, 0xc4220e48a0)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:197 +0x7c
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).Start.func2(0x345c9e0, 0xc4220e48a0)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:166 +0x3e
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc420440ba0, 0xc4225c21b0, 0xc420440b90)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:195 +0xf3
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:188 +0xad

goroutine 175200 [select]:
github.com/cockroachdb/cockroach/pkg/sql.(*DistSQLPlanner).initRunners.func1(0x345c9e0, 0xc421393530)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsql_running.go:86 +0x167
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc4203d64e0, 0xc4225c21b0, 0xc4203d64d0)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:195 +0xf3
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:188 +0xad

goroutine 175193 [select]:
github.com/cockroachdb/cockroach/pkg/sql.(*DistSQLPlanner).initRunners.func1(0x345c9e0, 0xc42201c930)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsql_running.go:86 +0x167
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc4203d6340, 0xc4225c21b0, 0xc4203d6330)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:195 +0xf3
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:188 +0xad

goroutine 175234 [select]:
github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/transport.loopyWriter(0x345c9e0, 0xc42201dcb0, 0xc42201dc50, 0xc4220b9fb8)
	/go/src/github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/transport/transport.go:750 +0x2e4
github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/transport.newHTTP2Server.func1(0xc423bc4160)
	/go/src/github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/transport/http2_server.go:227 +0x5e
created by github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/transport.newHTTP2Server
	/go/src/github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/transport/http2_server.go:226 +0x8d5

goroutine 175132 [semacquire]:
sync.runtime_notifyListWait(0xc422b342d0, 0xc40000015e)
	/usr/local/go/src/runtime/sema.go:507 +0x110
sync.(*Cond).Wait(0xc422b342c0)
	/usr/local/go/src/sync/cond.go:56 +0x80
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).worker(0xc421b08090, 0x345c9e0, 0xc4220e4810)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:197 +0x7c
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).Start.func2(0x345c9e0, 0xc4220e4810)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:166 +0x3e
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc420440770, 0xc4225c21b0, 0xc420440760)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:195 +0xf3
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:188 +0xad

goroutine 175457 [select]:
github.com/cockroachdb/cockroach/pkg/sql.(*hookFnNode).Next(0xc421679db0, 0x345c920, 0xc420a39d40, 0xc4208d15d0, 0xc4208d1558, 0xc421679db0, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/planhook.go:125 +0x172
github.com/cockroachdb/cockroach/pkg/sql.forEachRow(0x345c920, 0xc420a39d40, 0xc4208d15d0, 0xc4208d1558, 0x3453ae0, 0xc421679db0, 0xc42131c860, 0x0, 0xc4208d2310)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/executor.go:2075 +0x5d
github.com/cockroachdb/cockroach/pkg/sql.(*Executor).execClassic(0xc42381c6c0, 0xc4208d1558, 0x3453ae0, 0xc421679db0, 0x34687e0, 0xc422ff45a0, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/executor.go:2056 +0x28a
github.com/cockroachdb/cockroach/pkg/sql.(*Executor).execStmt(0xc42381c6c0, 0x345d8e0, 0xc4217e2500, 0xc42284ea20, 0x7, 0x7, 0xc42367e3a0, 0x13, 0x150927f2db7fbe3a, 0x1, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/executor.go:2217 +0x709
github.com/cockroachdb/cockroach/pkg/sql.(*Executor).execStmtInOpenTxn(0xc42381c6c0, 0xc4208d1300, 0x345d8e0, 0xc4217e2500, 0xc42284ea20, 0x7, 0x7, 0xc42367e3a0, 0x13, 0x150927f2db7fbe3a, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/executor.go:1850 +0x758
github.com/cockroachdb/cockroach/pkg/sql.(*Executor).execSingleStatement(0xc42381c6c0, 0xc4208d1300, 0x345d8e0, 0xc4217e2500, 0xc42284ea20, 0x7, 0x7, 0xc42367e3a0, 0x13, 0x150927f2db7fbe3a, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/executor.go:1319 +0x6c8
github.com/cockroachdb/cockroach/pkg/sql.runTxnAttempt(0xc42381c6c0, 0xc4208d1300, 0xc421679c70, 0x1, 0x1, 0xc42131d638, 0x1, 0x1, 0x0, 0x34614c0, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/executor.go:1195 +0x41f
github.com/cockroachdb/cockroach/pkg/sql.runWithAutoRetry(0xc42381c6c0, 0xc4208d1300, 0xc421679c70, 0x1, 0x1, 0xed1eb0101, 0x0, 0xc42131d638, 0x3ff0000000000000, 0x970800, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/executor.go:1020 +0x3aa
github.com/cockroachdb/cockroach/pkg/sql.(*Executor).execParsed(0xc42381c6c0, 0xc4208d1300, 0xc421679c70, 0x1, 0x1, 0xc42131d638, 0x0, 0xe14946, 0xbe8e624c640fb0bc)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/executor.go:836 +0x138
github.com/cockroachdb/cockroach/pkg/sql.(*Executor).execPrepared(0xc42381c6c0, 0xc4208d1300, 0xc420b6a750, 0xc420daf638, 0x9, 0xc42061f176)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/executor.go:678 +0x159
github.com/cockroachdb/cockroach/pkg/sql.(*Executor).ExecutePreparedStatement(0xc42381c6c0, 0xc4208d1300, 0xc420b6a750, 0xc420daf638, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/executor.go:655 +0x136
github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*v3Conn).handleExecute(0xc422ff45a0, 0xc422ff45c8, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/pgwire/v3.go:964 +0x2f6
github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*v3Conn).serve(0xc422ff45a0, 0x345c9e0, 0xc4223a3920, 0xc420314d60, 0x5400, 0x15000, 0xc42381ca78, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/pgwire/v3.go:532 +0xb6f
github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*Server).ServeConn(0xc42381c900, 0x345c920, 0xc420d7a780, 0x3468180, 0xc42354bc00, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/pgwire/server.go:421 +0xbae
github.com/cockroachdb/cockroach/pkg/server.(*Server).Start.func17.1(0x34689c0, 0xc423822000)
	/go/src/github.com/cockroachdb/cockroach/pkg/server/server.go:1252 +0x149
github.com/cockroachdb/cockroach/pkg/util/netutil.(*Server).ServeWith.func1(0xc4225c21b0, 0x345c9e0, 0xc4206db620, 0xc4225f6108, 0x34689c0, 0xc423822000, 0xc4206db650)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/netutil/net.go:140 +0xa9
created by github.com/cockroachdb/cockroach/pkg/util/netutil.(*Server).ServeWith
	/go/src/github.com/cockroachdb/cockroach/pkg/util/netutil/net.go:137 +0x263

goroutine 175130 [semacquire]:
sync.runtime_notifyListWait(0xc422b342d0, 0xc400000193)
	/usr/local/go/src/runtime/sema.go:507 +0x110
sync.(*Cond).Wait(0xc422b342c0)
	/usr/local/go/src/sync/cond.go:56 +0x80
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).worker(0xc421b08090, 0x345c9e0, 0xc4220e46f0)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:197 +0x7c
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).Start.func2(0x345c9e0, 0xc4220e46f0)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:166 +0x3e
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc420440730, 0xc4225c21b0, 0xc420440720)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:195 +0xf3
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:188 +0xad

goroutine 175127 [semacquire]:
sync.runtime_notifyListWait(0xc422b342d0, 0xc40000018e)
	/usr/local/go/src/runtime/sema.go:507 +0x110
sync.(*Cond).Wait(0xc422b342c0)
	/usr/local/go/src/sync/cond.go:56 +0x80
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).worker(0xc421b08090, 0x345c9e0, 0xc42201c300)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:197 +0x7c
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).Start.func2(0x345c9e0, 0xc42201c300)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:166 +0x3e
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc4204406d0, 0xc4225c21b0, 0xc4204406c0)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:195 +0xf3
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:188 +0xad

goroutine 175160 [semacquire]:
sync.runtime_notifyListWait(0xc422b342d0, 0xc400000175)
	/usr/local/go/src/runtime/sema.go:507 +0x110
sync.(*Cond).Wait(0xc422b342c0)
	/usr/local/go/src/sync/cond.go:56 +0x80
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).worker(0xc421b08090, 0x345c9e0, 0xc420e6a6c0)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:197 +0x7c
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).Start.func2(0x345c9e0, 0xc420e6a6c0)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:166 +0x3e
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc420440c60, 0xc4225c21b0, 0xc420440c50)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:195 +0xf3
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:188 +0xad

goroutine 175250 [select]:
github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/transport.(*http2Server).keepalive(0xc420582000)
	/go/src/github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/transport/http2_server.go:935 +0x264
created by github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/transport.newHTTP2Server
	/go/src/github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/transport/http2_server.go:230 +0x8fa

goroutine 175185 [semacquire]:
sync.runtime_notifyListWait(0xc4204a8100, 0xc400000003)
	/usr/local/go/src/runtime/sema.go:507 +0x110
sync.(*Cond).Wait(0xc4204a80f0)
	/usr/local/go/src/sync/cond.go:56 +0x80
io.(*pipe).read(0xc4204a80c0, 0xc421e68000, 0x400, 0x400, 0x0, 0x0, 0x0)
	/usr/local/go/src/io/pipe.go:47 +0xc6
io.(*PipeReader).Read(0xc4225f6010, 0xc421e68000, 0x400, 0x400, 0x0, 0x0, 0x0)
	/usr/local/go/src/io/pipe.go:130 +0x4c
crypto/tls.(*block).readFromUntil(0xc422029980, 0x2b30989bf9a8, 0xc420440160, 0x5, 0xc420440160, 0x0)
	/usr/local/go/src/crypto/tls/conn.go:488 +0x95
crypto/tls.(*Conn).readRecord(0xc42354a700, 0x2418417, 0xc42354a820, 0x0)
	/usr/local/go/src/crypto/tls/conn.go:590 +0xe0
crypto/tls.(*Conn).Read(0xc42354a700, 0xc4227b4000, 0x8000, 0x8000, 0x0, 0x0, 0x0)
	/usr/local/go/src/crypto/tls/conn.go:1134 +0x110
bufio.(*Reader).Read(0xc4222b6540, 0xc422c34038, 0x9, 0x9, 0x28, 0x21f9820, 0x0)
	/usr/local/go/src/bufio/bufio.go:213 +0x30b
io.ReadAtLeast(0x343b520, 0xc4222b6540, 0xc422c34038, 0x9, 0x9, 0x9, 0xc4228e1de8, 0x84730e, 0xc4228e1e97)
	/usr/local/go/src/io/io.go:309 +0x86
io.ReadFull(0x343b520, 0xc4222b6540, 0xc422c34038, 0x9, 0x9, 0xd0cee4, 0xc42074c780, 0xc420740004)
	/usr/local/go/src/io/io.go:327 +0x58
github.com/cockroachdb/cockroach/vendor/golang.org/x/net/http2.readFrameHeader(0xc422c34038, 0x9, 0x9, 0x343b520, 0xc4222b6540, 0x0, 0x0, 0xc42074c780, 0x0)
	/go/src/github.com/cockroachdb/cockroach/vendor/golang.org/x/net/http2/frame.go:237 +0x7b
github.com/cockroachdb/cockroach/vendor/golang.org/x/net/http2.(*Framer).ReadFrame(0xc422c34000, 0xc42074c780, 0xc42074c780, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/vendor/golang.org/x/net/http2/frame.go:492 +0xa4
github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/transport.(*http2Client).reader(0xc421cf6180)
	/go/src/github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/transport/http2_client.go:1118 +0xbe
created by github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/transport.newHTTP2Client
	/go/src/github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/transport/http2_client.go:266 +0xc80

goroutine 175012 [select]:
github.com/cockroachdb/cockroach/pkg/gossip.(*Gossip).manage.func1(0x345c9e0, 0xc420e6a150)
	/go/src/github.com/cockroachdb/cockroach/pkg/gossip/gossip.go:1189 +0x269
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc422df0dd0, 0xc4225c21b0, 0xc422df0dc0)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:195 +0xf3
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:188 +0xad

goroutine 175455 [chan receive]:
database/sql.(*DB).connectionOpener(0xc42297e000)
	/usr/local/go/src/database/sql/sql.go:871 +0x53
created by database/sql.Open
	/usr/local/go/src/database/sql/sql.go:609 +0x1ee

goroutine 174981 [select]:
github.com/cockroachdb/cockroach/pkg/security.(*CertificateManager).RegisterSignalHandler.func1(0xc4225c21b0, 0xc423982d80, 0xc4217e80e0)
	/go/src/github.com/cockroachdb/cockroach/pkg/security/certificate_manager.go:125 +0x10d
created by github.com/cockroachdb/cockroach/pkg/security.(*CertificateManager).RegisterSignalHandler
	/go/src/github.com/cockroachdb/cockroach/pkg/security/certificate_manager.go:123 +0xc9

goroutine 174929 [select]:
github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/transport.loopyWriter(0x345c9e0, 0xc4205e9590, 0xc4205e9530, 0xc4230d8fb8)
	/go/src/github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/transport/transport.go:750 +0x2e4
github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/transport.newHTTP2Server.func1(0xc420582000)
	/go/src/github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/transport/http2_server.go:227 +0x5e
created by github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/transport.newHTTP2Server
	/go/src/github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/transport/http2_server.go:226 +0x8d5

goroutine 175236 [select]:
github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/transport.loopyWriter(0x345c920, 0xc421323440, 0xc42074c660, 0xc4228e3fb8)
	/go/src/github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/transport/transport.go:750 +0x2e4
github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/transport.newHTTP2Client.func3(0xc421cf6180)
	/go/src/github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/transport/http2_client.go:298 +0x5e
created by github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/transport.newHTTP2Client
	/go/src/github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/transport/http2_client.go:297 +0xdd1

goroutine 175113 [semacquire]:
sync.runtime_notifyListWait(0xc422b342d0, 0xc400000182)
	/usr/local/go/src/runtime/sema.go:507 +0x110
sync.(*Cond).Wait(0xc422b342c0)
	/usr/local/go/src/sync/cond.go:56 +0x80
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).worker(0xc421b08090, 0x345c9e0, 0xc42201c090)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:197 +0x7c
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).Start.func2(0x345c9e0, 0xc42201c090)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:166 +0x3e
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc4204404a0, 0xc4225c21b0, 0xc420440490)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:195 +0xf3
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:188 +0xad

goroutine 175182 [select]:
github.com/cockroachdb/cockroach/pkg/storage.(*Store).startGossip.func4(0x345c9e0, 0xc4220e4ab0)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/store.go:1416 +0x3e9
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc420440f00, 0xc4225c21b0, 0xc420083a90)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:195 +0xf3
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:188 +0xad

goroutine 174784 [select]:
github.com/cockroachdb/cockroach/pkg/storage/idalloc.(*Allocator).start.func1(0x345c9e0, 0xc422692240)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/idalloc/id_alloc.go:138 +0x6b4
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc4221f8320, 0xc4225c21b0, 0xc4221f8310)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:195 +0xf3
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:188 +0xad

goroutine 175139 [semacquire]:
sync.runtime_notifyListWait(0xc422b342d0, 0xc400000199)
	/usr/local/go/src/runtime/sema.go:507 +0x110
sync.(*Cond).Wait(0xc422b342c0)
	/usr/local/go/src/sync/cond.go:56 +0x80
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).worker(0xc421b08090, 0x345c9e0, 0xc4220e47b0)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:197 +0x7c
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).Start.func2(0x345c9e0, 0xc4220e47b0)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:166 +0x3e
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc420440860, 0xc4225c21b0, 0xc420440850)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:195 +0xf3
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:188 +0xad

goroutine 175170 [semacquire]:
sync.runtime_notifyListWait(0xc422b342d0, 0xc400000178)
	/usr/local/go/src/runtime/sema.go:507 +0x110
sync.(*Cond).Wait(0xc422b342c0)
	/usr/local/go/src/sync/cond.go:56 +0x80
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).worker(0xc421b08090, 0x345c9e0, 0xc42201c570)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:197 +0x7c
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).Start.func2(0x345c9e0, 0xc42201c570)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:166 +0x3e
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc420440da0, 0xc4225c21b0, 0xc420440d90)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:195 +0xf3
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:188 +0xad

goroutine 175204 [select]:
github.com/cockroachdb/cockroach/pkg/sql.(*DistSQLPlanner).initRunners.func1(0x345c9e0, 0xc42067a180)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsql_running.go:86 +0x167
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc4203d6560, 0xc4225c21b0, 0xc4203d6550)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:195 +0xf3
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:188 +0xad

goroutine 175133 [semacquire]:
sync.runtime_notifyListWait(0xc422b342d0, 0xc400000162)
	/usr/local/go/src/runtime/sema.go:507 +0x110
sync.(*Cond).Wait(0xc422b342c0)
	/usr/local/go/src/sync/cond.go:56 +0x80
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).worker(0xc421b08090, 0x345c9e0, 0xc420e6a5a0)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:197 +0x7c
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).Start.func2(0x345c9e0, 0xc420e6a5a0)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:166 +0x3e
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc420440790, 0xc4225c21b0, 0xc420440780)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:195 +0xf3
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:188 +0xad

goroutine 175205 [select]:
github.com/cockroachdb/cockroach/pkg/sql.(*DistSQLPlanner).initRunners.func1(0x345c9e0, 0xc42201c8a0)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsql_running.go:86 +0x167
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc4203d6580, 0xc4225c21b0, 0xc4203d6570)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:195 +0xf3
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:188 +0xad

goroutine 175199 [select]:
github.com/cockroachdb/cockroach/pkg/sql.(*DistSQLPlanner).initRunners.func1(0x345c9e0, 0xc421393500)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsql_running.go:86 +0x167
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc4203d64c0, 0xc4225c21b0, 0xc4203d64b0)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:195 +0xf3
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:188 +0xad

goroutine 175126 [semacquire]:
sync.runtime_notifyListWait(0xc422b342d0, 0xc40000017f)
	/usr/local/go/src/runtime/sema.go:507 +0x110
sync.(*Cond).Wait(0xc422b342c0)
	/usr/local/go/src/sync/cond.go:56 +0x80
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).worker(0xc421b08090, 0x345c9e0, 0xc42201c000)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:197 +0x7c
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).Start.func2(0x345c9e0, 0xc42201c000)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:166 +0x3e
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc4204406b0, 0xc4225c21b0, 0xc4204406a0)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:195 +0xf3
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:188 +0xad

goroutine 175143 [semacquire]:
sync.runtime_notifyListWait(0xc422b342d0, 0xc400000197)
	/usr/local/go/src/runtime/sema.go:507 +0x110
sync.(*Cond).Wait(0xc422b342c0)
	/usr/local/go/src/sync/cond.go:56 +0x80
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).worker(0xc421b08090, 0x345c9e0, 0xc42201c390)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:197 +0x7c
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).Start.func2(0x345c9e0, 0xc42201c390)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:166 +0x3e
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc420440920, 0xc4225c21b0, 0xc420440910)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:195 +0xf3
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:188 +0xad

goroutine 175122 [semacquire]:
sync.runtime_notifyListWait(0xc422b342d0, 0xc40000018f)
	/usr/local/go/src/runtime/sema.go:507 +0x110
sync.(*Cond).Wait(0xc422b342c0)
	/usr/local/go/src/sync/cond.go:56 +0x80
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).worker(0xc421b08090, 0x345c9e0, 0xc4220e4630)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:197 +0x7c
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).Start.func2(0x345c9e0, 0xc4220e4630)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:166 +0x3e
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc420440630, 0xc4225c21b0, 0xc420440620)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:195 +0xf3
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:188 +0xad

goroutine 175187 [select]:
github.com/cockroachdb/cockroach/pkg/server.(*Node).startGossip.func1(0x345c9e0, 0xc42201c7e0)
	/go/src/github.com/cockroachdb/cockroach/pkg/server/node.go:685 +0x2dd
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc4203d6190, 0xc4225c21b0, 0xc42183e0c0)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:195 +0xf3
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:188 +0xad

goroutine 175014 [select]:
github.com/cockroachdb/cockroach/pkg/storage.(*baseQueue).processLoop.func1(0x345c9e0, 0xc421393440)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/queue.go:514 +0x1bb
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc422df0000, 0xc4225c21b0, 0xc42037e080)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:195 +0xf3
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:188 +0xad

goroutine 175145 [semacquire]:
sync.runtime_notifyListWait(0xc422b342d0, 0xc40000019b)
	/usr/local/go/src/runtime/sema.go:507 +0x110
sync.(*Cond).Wait(0xc422b342c0)
	/usr/local/go/src/sync/cond.go:56 +0x80
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).worker(0xc421b08090, 0x345c9e0, 0xc42201c3f0)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:197 +0x7c
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).Start.func2(0x345c9e0, 0xc42201c3f0)
	/go/src/
```

Please assign, take a look and update the issue accordingly.

### LINKED ISSUE #21471: teamcity: failed tests on v2.0-alpha.20180116: test/TestRestoreDatabaseVersusTable, test/TestRestoreDatabaseVersusTable/into_db, test/TestRestoreDatabaseVersusTable/incomplete-db, test/TestRestoreDatabaseVersusTable/tables, test/TestRestoreDatabaseVersusTable/db-exists, test/TestRestoreDatabaseVersusTable/db, test/TestRestoreDatabaseVersusTable/tables-needs-db
The following tests appear to have failed:

[#480343](https://teamcity.cockroachdb.com/viewLog.html?buildId=480343):

```
--- FAIL: test/TestRestoreDatabaseVersusTable (0.000s)
Test ended in panic.

------- Stdout: -------
W180116 16:28:44.374977 148702 server/status/runtime.go:109  Could not parse build timestamp: parsing time "" as "2006/01/02 15:04:05": cannot parse "" as "2006"
I180116 16:28:44.377172 148702 server/config.go:516  [n?] 1 storage engine initialized
I180116 16:28:44.377195 148702 server/config.go:519  [n?] RocksDB cache size: 128 MiB
I180116 16:28:44.377201 148702 server/config.go:519  [n?] store 0: in-memory, size 0 B
I180116 16:28:44.380489 148702 server/node.go:361  [n?] **** cluster 2ffe2780-b05d-49fe-a57a-d95539f9cf40 has been created
I180116 16:28:44.380533 148702 server/server.go:934  [n?] **** add additional nodes by specifying --join=127.0.0.1:45707
I180116 16:28:44.381352 148702 storage/store.go:1209  [n1,s1] [n1,s1]: failed initial metrics computation: [n1,s1]: system config not yet available
I180116 16:28:44.381408 148702 server/node.go:486  [n1] initialized store [n1,s1]: disk (capacity=512 MiB, available=512 MiB, used=0 B, logicalBytes=3.2 KiB), ranges=1, leases=0, writes=0.00, bytesPerReplica={p10=3322.00 p25=3322.00 p50=3322.00 p75=3322.00 p90=3322.00}, writesPerReplica={p10=0.00 p25=0.00 p50=0.00 p75=0.00 p90=0.00}
I180116 16:28:44.381440 148702 server/node.go:339  [n1] node ID 1 initialized
I180116 16:28:44.381493 148702 gossip/gossip.go:332  [n1] NodeDescriptor set to node_id:1 address:<network_field:"tcp" address_field:"127.0.0.1:45707" > attrs:<> locality:<> ServerVersion:<major_val:1 minor_val:1 patch:0 unstable:8 > 
I180116 16:28:44.381664 148702 storage/stores.go:331  [n1] read 0 node addresses from persistent storage
I180116 16:28:44.381776 148702 server/node.go:627  [n1] connecting to gossip network to verify cluster ID...
I180116 16:28:44.381802 148702 server/node.go:652  [n1] node connected via gossip and verified as part of cluster "2ffe2780-b05d-49fe-a57a-d95539f9cf40"
I180116 16:28:44.381836 148702 server/node.go:428  [n1] node=1: started with [<no-attributes>=<in-mem>] engine(s) and attributes []
I180116 16:28:44.381891 148702 sql/distsql_physical_planner.go:122  [n1] creating DistSQLPlanner with address {tcp 127.0.0.1:45707}
I180116 16:28:44.383402 148967 storage/replica_command.go:819  [split,n1,s1,r1/1:/M{in-ax}] initiating a split of this range at key /System/"" [r2]
I180116 16:28:44.390026 148702 server/server.go:1161  [n1] starting https server at 127.0.0.1:39153
I180116 16:28:44.390056 148702 server/server.go:1162  [n1] starting grpc/postgres server at 127.0.0.1:45707
I180116 16:28:44.390066 148702 server/server.go:1163  [n1] advertising CockroachDB node at 127.0.0.1:45707
E180116 16:28:44.391004 148968 storage/queue.go:668  [replicate,n1,s1,r1/1:/{Min-System/}] range requires a replication change, but lacks a quorum of live replicas (0/1)
I180116 16:28:44.392057 148967 storage/replica_command.go:819  [split,n1,s1,r2/1:/{System/-Max}] initiating a split of this range at key /System/NodeLiveness [r3]
I180116 16:28:44.398783 148967 storage/replica_command.go:819  [split,n1,s1,r3/1:/{System/NodeL…-Max}] initiating a split of this range at key /System/NodeLivenessMax [r4]
W180116 16:28:44.399561 149047 storage/intent_resolver.go:324  [n1,s1] failed to push during intent resolution: failed to push "sql txn implicit" id=1f3102da key=/Table/SystemConfigSpan/Start rw=true pri=0.01228340 iso=SERIALIZABLE stat=PENDING epo=0 ts=1516120124.393517247,0 orig=1516120124.393517247,0 max=1516120124.393517247,0 wto=false rop=false seq=7
I180116 16:28:44.400055 148702 sql/event_log.go:115  [n1] Event: "alter_table", target: 12, info: {TableName:eventlog Statement:ALTER TABLE system.eventlog ALTER COLUMN "uniqueID" SET DEFAULT uuid_v4() User:node MutationID:0 CascadeDroppedViews:[]}
I180116 16:28:44.403524 148967 storage/replica_command.go:819  [split,n1,s1,r4/1:/{System/NodeL…-Max}] initiating a split of this range at key /System/tsd [r5]
I180116 16:28:44.404276 148702 sql/lease.go:348  [n1] publish: descID=12 (eventlog) version=2 mtime=2018-01-16 16:28:44.404137559 +0000 UTC
I180116 16:28:44.411017 148967 storage/replica_command.go:819  [split,n1,s1,r5/1:/{System/tsd-Max}] initiating a split of this range at key /System/"tse" [r6]
I180116 16:28:44.417412 148967 storage/replica_command.go:819  [split,n1,s1,r6/1:/{System/tse-Max}] initiating a split of this range at key /Table/SystemConfigSpan/Start [r7]
I180116 16:28:44.420306 148702 sql/event_log.go:115  [n1] Event: "set_cluster_setting", target: 0, info: {SettingName:diagnostics.reporting.enabled Value:true User:node}
I180116 16:28:44.421670 148967 storage/replica_command.go:819  [split,n1,s1,r7/1:/{Table/System…-Max}] initiating a split of this range at key /Table/11 [r8]
I180116 16:28:44.425632 148967 storage/replica_command.go:819  [split,n1,s1,r8/1:/{Table/11-Max}] initiating a split of this range at key /Table/12 [r9]
I180116 16:28:44.429319 148967 storage/replica_command.go:819  [split,n1,s1,r9/1:/{Table/12-Max}] initiating a split of this range at key /Table/13 [r10]
I180116 16:28:44.430672 148702 sql/event_log.go:115  [n1] Event: "set_cluster_setting", target: 0, info: {SettingName:version Value:$1 User:node}
I180116 16:28:44.433935 148967 storage/replica_command.go:819  [split,n1,s1,r10/1:/{Table/13-Max}] initiating a split of this range at key /Table/14 [r11]
I180116 16:28:44.435240 148702 sql/event_log.go:115  [n1] Event: "set_cluster_setting", target: 0, info: {SettingName:trace.debug.enable Value:false User:node}
I180116 16:28:44.440327 148967 storage/replica_command.go:819  [split,n1,s1,r11/1:/{Table/14-Max}] initiating a split of this range at key /Table/15 [r12]
I180116 16:28:44.444271 148967 storage/replica_command.go:819  [split,n1,s1,r12/1:/{Table/15-Max}] initiating a split of this range at key /Table/16 [r13]
I180116 16:28:44.447890 148967 storage/replica_command.go:819  [split,n1,s1,r13/1:/{Table/16-Max}] initiating a split of this range at key /Table/17 [r14]
I180116 16:28:44.449926 148702 sql/event_log.go:115  [n1] Event: "alter_table", target: 4, info: {TableName:users Statement:ALTER TABLE system.users ADD COLUMN IF NOT EXISTS "isRole" BOOL NOT NULL DEFAULT false User:node MutationID:1 CascadeDroppedViews:[]}
I180116 16:28:44.451621 148967 storage/replica_command.go:819  [split,n1,s1,r14/1:/{Table/17-Max}] initiating a split of this range at key /Table/18 [r15]
I180116 16:28:44.452066 148702 sql/lease.go:348  [n1] publish: descID=4 (users) version=2 mtime=2018-01-16 16:28:44.451968724 +0000 UTC
I180116 16:28:44.455304 148967 storage/replica_command.go:819  [split,n1,s1,r15/1:/{Table/18-Max}] initiating a split of this range at key /Table/19 [r16]
I180116 16:28:44.456410 148702 sql/lease.go:348  [n1] publish: descID=4 (users) version=3 mtime=2018-01-16 16:28:44.456312308 +0000 UTC
I180116 16:28:44.458521 148967 storage/replica_command.go:819  [split,n1,s1,r16/1:/{Table/19-Max}] initiating a split of this range at key /Table/20 [r17]
I180116 16:28:44.459681 148702 sql/backfill.go:132  [n1] Running backfill for "users", v=3, m=1
I180116 16:28:44.461195 148967 storage/replica_command.go:819  [split,n1,s1,r17/1:/{Table/20-Max}] initiating a split of this range at key /Table/21 [r18]
I180116 16:28:44.467606 148967 storage/replica_command.go:819  [split,n1,s1,r18/1:/{Table/21-Max}] initiating a split of this range at key /Table/22 [r19]
I180116 16:28:44.468667 148702 sql/lease.go:348  [n1] publish: descID=4 (users) version=4 mtime=2018-01-16 16:28:44.468575266 +0000 UTC
I180116 16:28:44.470853 148967 storage/replica_command.go:819  [split,n1,s1,r19/1:/{Table/22-Max}] initiating a split of this range at key /Table/23 [r20]
I180116 16:28:44.472250 148702 sql/event_log.go:115  [n1] Event: "finish_schema_change", target: 4, info: {MutationID:1}
I180116 16:28:44.473551 148702 sql/lease.go:274  publish (count leases): descID=4 name=users version=3 count=1
I180116 16:28:44.499654 148702 server/server.go:1232  [n1] done ensuring all necessary migrations have run
I180116 16:28:44.499690 148702 server/server.go:1235  [n1] serving sql connections
I180116 16:28:44.501981 149389 sql/event_log.go:115  [n1] Event: "node_join", target: 1, info: {Descriptor:{NodeID:1 Address:{NetworkField:tcp AddressField:127.0.0.1:45707} Attrs: Locality: ServerVersion:1.1-8} ClusterID:2ffe2780-b05d-49fe-a57a-d95539f9cf40 StartedAt:1516120124381809901 LastUp:1516120124381809901}
I180116 16:28:44.512797 149363 sql/event_log.go:115  [client=127.0.0.1:53982,user=root,n1] Event: "create_database", target: 50, info: {DatabaseName:data Statement:CREATE DATABASE data User:root}
I180116 16:28:44.513124 148967 storage/replica_command.go:819  [split,n1,s1,r20/1:/{Table/23-Max}] initiating a split of this range at key /Table/50 [r21]
I180116 16:28:44.516594 149363 sql/event_log.go:115  [client=127.0.0.1:53982,user=root,n1] Event: "create_table", target: 51, info: {TableName:bank Statement:CREATE TABLE bank (id INT PRIMARY KEY, balance INT, payload STRING, FAMILY (id, balance, payload)) User:root}
I180116 16:28:44.516963 148967 storage/replica_command.go:819  [split,n1,s1,r21/1:/{Table/50-Max}] initiating a split of this range at key /Table/51 [r22]
I180116 16:28:44.523820 149363 sql/event_log.go:115  [client=127.0.0.1:53982,user=root,n1] Event: "create_database", target: 52, info: {DatabaseName:d2 Statement:CREATE DATABASE d2 User:root}
I180116 16:28:44.524163 148967 storage/replica_command.go:819  [split,n1,s1,r22/1:/{Table/51-Max}] initiating a split of this range at key /Table/52 [r23]
I180116 16:28:44.526841 149363 sql/event_log.go:115  [client=127.0.0.1:53982,user=root,n1] Event: "create_database", target: 53, info: {DatabaseName:d3 Statement:CREATE DATABASE d3 User:root}
I180116 16:28:44.527814 148967 storage/replica_command.go:819  [split,n1,s1,r23/1:/{Table/52-Max}] initiating a split of this range at key /Table/53 [r24]
I180116 16:28:44.530589 149363 sql/event_log.go:115  [client=127.0.0.1:53982,user=root,n1] Event: "create_table", target: 54, info: {TableName:d3.foo Statement:CREATE TABLE d3.foo (a INT) User:root}
I180116 16:28:44.531535 148967 storage/replica_command.go:819  [split,n1,s1,r24/1:/{Table/53-Max}] initiating a split of this range at key /Table/54 [r25]
I180116 16:28:44.533922 149363 sql/event_log.go:115  [client=127.0.0.1:53982,user=root,n1] Event: "create_database", target: 55, info: {DatabaseName:d4 Statement:CREATE DATABASE d4 User:root}
I180116 16:28:44.535456 148967 storage/replica_command.go:819  [split,n1,s1,r25/1:/{Table/54-Max}] initiating a split of this range at key /Table/55 [r26]
I180116 16:28:44.538408 149363 sql/event_log.go:115  [client=127.0.0.1:53982,user=root,n1] Event: "create_table", target: 56, info: {TableName:d4.foo Statement:CREATE TABLE d4.foo (a INT) User:root}
I180116 16:28:44.539645 148967 storage/replica_command.go:819  [split,n1,s1,r26/1:/{Table/55-Max}] initiating a split of this range at key /Table/56 [r27]
I180116 16:28:44.542084 149363 sql/event_log.go:115  [client=127.0.0.1:53982,user=root,n1] Event: "create_table", target: 57, info: {TableName:d4.bar Statement:CREATE TABLE d4.bar (a INT) User:root}
I180116 16:28:44.543349 148967 storage/replica_command.go:819  [split,n1,s1,r27/1:/{Table/56-Max}] initiating a split of this range at key /Table/57 [r28]
I180116 16:28:44.552426 149493 ccl/storageccl/export.go:124  [n1,s1,r27/1:/Table/5{6-7}] export [/Table/56/1,/Table/56/2)
I180116 16:28:44.552565 149492 ccl/storageccl/export.go:124  [n1,s1,r25/1:/Table/5{4-5}] export [/Table/54/1,/Table/54/2)
I180116 16:28:44.552588 149491 ccl/storageccl/export.go:124  [n1,s1,r22/1:/Table/5{1-2}] export [/Table/51/1,/Table/51/2)
I180116 16:28:44.552428 149494 ccl/storageccl/export.go:124  [n1,s1,r28/1:/{Table/57-Max}] export [/Table/57/1,/Table/57/2)
I180116 16:28:44.578698 149513 ccl/storageccl/export.go:124  [n1,s1,r27/1:/Table/5{6-7}] export [/Table/56/1,/Table/56/2)
I180116 16:28:44.594770 149524 ccl/storageccl/export.go:124  [n1,s1,r28/1:/{Table/57-Max}] export [/Table/57/1,/Table/57/2)
I180116 16:28:44.594837 149523 ccl/storageccl/export.go:124  [n1,s1,r27/1:/Table/5{6-7}] export [/Table/56/1,/Table/56/2)
I180116 16:28:44.613115 149501 ccl/storageccl/export.go:124  [n1,s1,r28/1:/{Table/57-Max}] export [/Table/57/1,/Table/57/2)
I180116 16:28:44.613208 149500 ccl/storageccl/export.go:124  [n1,s1,r27/1:/Table/5{6-7}] export [/Table/56/1,/Table/56/2)
--- FAIL: test/TestRestoreDatabaseVersusTable/into_db (0.000s)
Test ended in panic.

------- Stdout: -------
W180116 16:28:48.138581 157820 server/status/runtime.go:109  Could not parse build timestamp: parsing time "" as "2006/01/02 15:04:05": cannot parse "" as "2006"
I180116 16:28:48.145014 157820 server/config.go:516  [n?] 1 storage engine initialized
I180116 16:28:48.145042 157820 server/config.go:519  [n?] RocksDB cache size: 128 MiB
I180116 16:28:48.145048 157820 server/config.go:519  [n?] store 0: in-memory, size 0 B
I180116 16:28:48.148107 157820 server/node.go:361  [n?] **** cluster f8371979-8bbb-42c2-9861-24b11bebe89a has been created
I180116 16:28:48.148140 157820 server/server.go:934  [n?] **** add additional nodes by specifying --join=127.0.0.1:44949
I180116 16:28:48.149103 157820 storage/store.go:1209  [n1,s1] [n1,s1]: failed initial metrics computation: [n1,s1]: system config not yet available
I180116 16:28:48.149154 157820 server/node.go:486  [n1] initialized store [n1,s1]: disk (capacity=512 MiB, available=512 MiB, used=0 B, logicalBytes=3.2 KiB), ranges=1, leases=0, writes=0.00, bytesPerReplica={p10=3322.00 p25=3322.00 p50=3322.00 p75=3322.00 p90=3322.00}, writesPerReplica={p10=0.00 p25=0.00 p50=0.00 p75=0.00 p90=0.00}
I180116 16:28:48.149179 157820 server/node.go:339  [n1] node ID 1 initialized
I180116 16:28:48.149239 157820 gossip/gossip.go:332  [n1] NodeDescriptor set to node_id:1 address:<network_field:"tcp" address_field:"127.0.0.1:44949" > attrs:<> locality:<> ServerVersion:<major_val:1 minor_val:1 patch:0 unstable:8 > 
I180116 16:28:48.149337 157820 storage/stores.go:331  [n1] read 0 node addresses from persistent storage
I180116 16:28:48.149445 157820 server/node.go:627  [n1] connecting to gossip network to verify cluster ID...
I180116 16:28:48.149476 157820 server/node.go:652  [n1] node connected via gossip and verified as part of cluster "f8371979-8bbb-42c2-9861-24b11bebe89a"
I180116 16:28:48.149502 157820 server/node.go:428  [n1] node=1: started with [<no-attributes>=<in-mem>] engine(s) and attributes []
I180116 16:28:48.149561 157820 sql/distsql_physical_planner.go:122  [n1] creating DistSQLPlanner with address {tcp 127.0.0.1:44949}
I180116 16:28:48.151288 158031 storage/replica_command.go:819  [split,n1,s1,r1/1:/M{in-ax}] initiating a split of this range at key /System/"" [r2]
I180116 16:28:48.152525 157820 server/server.go:1161  [n1] starting https server at 127.0.0.1:39351
I180116 16:28:48.152551 157820 server/server.go:1162  [n1] starting grpc/postgres server at 127.0.0.1:44949
I180116 16:28:48.152561 157820 server/server.go:1163  [n1] advertising CockroachDB node at 127.0.0.1:44949
I180116 16:28:48.159122 158031 storage/replica_command.go:819  [split,n1,s1,r2/1:/{System/-Max}] initiating a split of this range at key /System/NodeLiveness [r3]
I180116 16:28:48.161934 157820 sql/event_log.go:115  [n1] Event: "alter_table", target: 12, info: {TableName:eventlog Statement:ALTER TABLE system.eventlog ALTER COLUMN "uniqueID" SET DEFAULT uuid_v4() User:node MutationID:0 CascadeDroppedViews:[]}
I180116 16:28:48.163240 158031 storage/replica_command.go:819  [split,n1,s1,r3/1:/{System/NodeL…-Max}] initiating a split of this range at key /System/NodeLivenessMax [r4]
I180116 16:28:48.166759 157820 sql/lease.go:348  [n1] publish: descID=12 (eventlog) version=2 mtime=2018-01-16 16:28:48.166589069 +0000 UTC
I180116 16:28:48.167948 158031 storage/replica_command.go:819  [split,n1,s1,r4/1:/{System/NodeL…-Max}] initiating a split of this range at key /System/tsd [r5]
I180116 16:28:48.172582 158031 storage/replica_command.go:819  [split,n1,s1,r5/1:/{System/tsd-Max}] initiating a split of this range at key /System/"tse" [r6]
I180116 16:28:48.181804 158031 storage/replica_command.go:819  [split,n1,s1,r6/1:/{System/tse-Max}] initiating a split of this range at key /Table/SystemConfigSpan/Start [r7]
I180116 16:28:48.183812 157820 sql/event_log.go:115  [n1] Event: "set_cluster_setting", target: 0, info: {SettingName:diagnostics.reporting.enabled Value:true User:node}
I180116 16:28:48.185801 158031 storage/replica_command.go:819  [split,n1,s1,r7/1:/{Table/System…-Max}] initiating a split of this range at key /Table/11 [r8]
I180116 16:28:48.190312 158031 storage/replica_command.go:819  [split,n1,s1,r8/1:/{Table/11-Max}] initiating a split of this range at key /Table/12 [r9]
I180116 16:28:48.194182 158031 storage/replica_command.go:819  [split,n1,s1,r9/1:/{Table/12-Max}] initiating a split of this range at key /Table/13 [r10]
I180116 16:28:48.195422 157820 sql/event_log.go:115  [n1] Event: "set_cluster_setting", target: 0, info: {SettingName:version Value:$1 User:node}
I180116 16:28:48.198615 158031 storage/replica_command.go:819  [split,n1,s1,r10/1:/{Table/13-Max}] initiating a split of this range at key /Table/14 [r11]
I180116 16:28:48.198916 157820 sql/event_log.go:115  [n1] Event: "set_cluster_setting", target: 0, info: {SettingName:trace.debug.enable Value:false User:node}
I180116 16:28:48.202975 158031 storage/replica_command.go:819  [split,n1,s1,r11/1:/{Table/14-Max}] initiating a split of this range at key /Table/15 [r12]
I180116 16:28:48.206413 158031 storage/replica_command.go:819  [split,n1,s1,r12/1:/{Table/15-Max}] initiating a split of this range at key /Table/16 [r13]
I180116 16:28:48.211016 158031 storage/replica_command.go:819  [split,n1,s1,r13/1:/{Table/16-Max}] initiating a split of this range at key /Table/17 [r14]
I180116 16:28:48.211425 157820 sql/event_log.go:115  [n1] Event: "alter_table", target: 4, info: {TableName:users Statement:ALTER TABLE system.users ADD COLUMN IF NOT EXISTS "isRole" BOOL NOT NULL DEFAULT false User:node MutationID:1 CascadeDroppedViews:[]}
I180116 16:28:48.214201 157820 sql/lease.go:348  [n1] publish: descID=4 (users) version=2 mtime=2018-01-16 16:28:48.213891792 +0000 UTC
I180116 16:28:48.215557 158031 storage/replica_command.go:819  [split,n1,s1,r14/1:/{Table/17-Max}] initiating a split of this range at key /Table/18 [r15]
I180116 16:28:48.218811 158031 storage/replica_command.go:819  [split,n1,s1,r15/1:/{Table/18-Max}] initiating a split of this range at key /Table/19 [r16]
I180116 16:28:48.223647 157820 sql/lease.go:348  [n1] publish: descID=4 (users) version=3 mtime=2018-01-16 16:28:48.223224643 +0000 UTC
I180116 16:28:48.227994 158031 storage/replica_command.go:819  [split,n1,s1,r16/1:/{Table/19-Max}] initiating a split of this range at key /Table/20 [r17]
I180116 16:28:48.228590 157820 sql/backfill.go:132  [n1] Running backfill for "users", v=3, m=1
I180116 16:28:48.231527 158031 storage/replica_command.go:819  [split,n1,s1,r17/1:/{Table/20-Max}] initiating a split of this range at key /Table/21 [r18]
I180116 16:28:48.234972 158031 storage/replica_command.go:819  [split,n1,s1,r18/1:/{Table/21-Max}] initiating a split of this range at key /Table/22 [r19]
W180116 16:28:48.237337 158299 storage/intent_resolver.go:324  [n1,s1] failed to push during intent resolution: failed to push "split" id=710285b3 key=/Local/Range/Table/21/RangeDescriptor rw=true pri=0.03966754 iso=SERIALIZABLE stat=PENDING epo=0 ts=1516120128.234995043,0 orig=1516120128.234995043,0 max=1516120128.234995043,0 wto=false rop=false seq=3
I180116 16:28:48.238261 157820 sql/lease.go:348  [n1] publish: descID=4 (users) version=4 mtime=2018-01-16 16:28:48.238167096 +0000 UTC
I180116 16:28:48.238595 158031 storage/replica_command.go:819  [split,n1,s1,r19/1:/{Table/22-Max}] initiating a split of this range at key /Table/23 [r20]
I180116 16:28:48.241703 157820 sql/event_log.go:115  [n1] Event: "finish_schema_change", target: 4, info: {MutationID:1}
I180116 16:28:48.242876 157820 sql/lease.go:274  publish (count leases): descID=4 name=users version=3 count=1
I180116 16:28:48.273211 157820 server/server.go:1232  [n1] done ensuring all necessary migrations have run
I180116 16:28:48.273253 157820 server/server.go:1235  [n1] serving sql connections
I180116 16:28:48.275247 158355 sql/event_log.go:115  [n1] Event: "node_join", target: 1, info: {Descriptor:{NodeID:1 Address:{NetworkField:tcp AddressField:127.0.0.1:44949} Attrs: Locality: ServerVersion:1.1-8} ClusterID:f8371979-8bbb-42c2-9861-24b11bebe89a StartedAt:1516120128149480129 LastUp:1516120128149480129}
W180116 16:28:48.279050 157820 server/status/runtime.go:109  Could not parse build timestamp: parsing time "" as "2006/01/02 15:04:05": cannot parse "" as "2006"
I180116 16:28:48.281448 157820 server/config.go:516  [n?] 1 storage engine initialized
I180116 16:28:48.281471 157820 server/config.go:519  [n?] RocksDB cache size: 128 MiB
I180116 16:28:48.281477 157820 server/config.go:519  [n?] store 0: in-memory, size 0 B
W180116 16:28:48.281540 157820 gossip/gossip.go:1292  [n?] no incoming or outgoing connections
I180116 16:28:48.281575 157820 server/server.go:936  [n?] no stores bootstrapped and --join flag specified, awaiting init command.
I180116 16:28:48.291341 158204 gossip/client.go:129  [n?] started gossip client to 127.0.0.1:44949
I180116 16:28:48.293688 158328 gossip/server.go:219  [n1] received initial cluster-verification connection from {tcp 127.0.0.1:45903}
I180116 16:28:48.297171 157820 storage/stores.go:331  [n?] read 0 node addresses from persistent storage
I180116 16:28:48.297224 157820 storage/stores.go:350  [n?] wrote 1 node addresses to persistent storage
I180116 16:28:48.297234 157820 server/node.go:627  [n?] connecting to gossip network to verify cluster ID...
I180116 16:28:48.297258 157820 server/node.go:652  [n?] node connected via gossip and verified as part of cluster "f8371979-8bbb-42c2-9861-24b11bebe89a"
I180116 16:28:48.297482 158351 kv/dist_sender.go:354  [n?] unable to determine this node's attributes for replica selection; node is most likely bootstrapping
I180116 16:28:48.298614 158350 kv/dist_sender.go:354  [n?] unable to determine this node's attributes for replica selection; node is most likely bootstrapping
I180116 16:28:48.299487 157820 kv/dist_sender.go:354  [n?] unable to determine this node's attributes for replica selection; node is most likely bootstrapping
I180116 16:28:48.300547 157820 server/node.go:332  [n?] new node allocated ID 2
I180116 16:28:48.300616 157820 gossip/gossip.go:332  [n2] NodeDescriptor set to node_id:2 address:<network_field:"tcp" address_field:"127.0.0.1:45903" > attrs:<> locality:<> ServerVersion:<major_val:1 minor_val:1 patch:0 unstable:8 > 
I180116 16:28:48.300675 157820 server/node.go:414  [n2] node=2: asynchronously bootstrapping engine(s) [<no-attributes>=<in-mem>]
I180116 16:28:48.300697 157820 server/node.go:428  [n2] node=2: started with [] engine(s) and attributes []
I180116 16:28:48.300806 157820 sql/distsql_physical_planner.go:122  [n2] creating DistSQLPlanner with address {tcp 127.0.0.1:45903}
I180116 16:28:48.301387 158376 storage/stores.go:350  [n1] wrote 1 node addresses to persistent storage
I180116 16:28:48.303309 157820 server/server.go:1161  [n2] starting https server at 127.0.0.1:45763
I180116 16:28:48.303336 157820 server/server.go:1162  [n2] starting grpc/postgres server at 127.0.0.1:45903
I180116 16:28:48.303345 157820 server/server.go:1163  [n2] advertising CockroachDB node at 127.0.0.1:45903
I180116 16:28:48.303574 158392 server/node.go:608  [n2] bootstrapped store [n2,s2]
I180116 16:28:48.304539 157820 server/server.go:1232  [n2] done ensuring all necessary migrations have run
I180116 16:28:48.304569 157820 server/server.go:1235  [n2] serving sql connections
I180116 16:28:48.309154 158336 sql/event_log.go:115  [n2] Event: "node_join", target: 2, info: {Descriptor:{NodeID:2 Address:{NetworkField:tcp AddressField:127.0.0.1:45903} Attrs: Locality: ServerVersion:1.1-8} ClusterID:f8371979-8bbb-42c2-9861-24b11bebe89a StartedAt:1516120128300687650 LastUp:1516120128300687650}
W180116 16:28:48.311086 157820 server/status/runtime.go:109  Could not parse build timestamp: parsing time "" as "2006/01/02 15:04:05": cannot parse "" as "2006"
I180116 16:28:48.315364 157820 server/config.go:516  [n?] 1 storage engine initialized
I180116 16:28:48.315389 157820 server/config.go:519  [n?] RocksDB cache size: 128 MiB
I180116 16:28:48.315396 157820 server/config.go:519  [n?] store 0: in-memory, size 0 B
W180116 16:28:48.315467 157820 gossip/gossip.go:1292  [n?] no incoming or outgoing connections
I180116 16:28:48.315526 157820 server/server.go:936  [n?] no stores bootstrapped and --join flag specified, awaiting init command.
I180116 16:28:48.326818 158411 gossip/client.go:129  [n?] started gossip client to 127.0.0.1:44949
I180116 16:28:48.327185 158596 gossip/server.go:219  [n1] received initial cluster-verification connection from {tcp 127.0.0.1:41455}
I180116 16:28:48.328204 157820 storage/stores.go:331  [n?] read 0 node addresses from persistent storage
I180116 16:28:48.328249 157820 storage/stores.go:350  [n?] wrote 2 node addresses to persistent storage
I180116 16:28:48.328261 157820 server/node.go:627  [n?] connecting to gossip network to verify cluster ID...
I180116 16:28:48.328284 157820 server/node.go:652  [n?] node connected via gossip and verified as part of cluster "f8371979-8bbb-42c2-9861-24b11bebe89a"
I180116 16:28:48.328524 158618 kv/dist_sender.go:354  [n?] unable to determine this node's attributes for replica selection; node is most likely bootstrapping
I180116 16:28:48.329371 158617 kv/dist_sender.go:354  [n?] unable to determine this node's attributes for replica selection; node is most likely bootstrapping
I180116 16:28:48.330119 157820 kv/dist_sender.go:354  [n?] unable to determine this node's attributes for replica selection; node is most likely bootstrapping
I180116 16:28:48.330943 157820 server/node.go:332  [n?] new node allocated ID 3
I180116 16:28:48.331011 157820 gossip/gossip.go:332  [n3] NodeDescriptor set to node_id:3 address:<network_field:"tcp" address_field:"127.0.0.1:41455" > attrs:<> locality:<> ServerVersion:<major_val:1 minor_val:1 patch:0 unstable:8 > 
I180116 16:28:48.331112 157820 server/node.go:414  [n3] node=3: asynchronously bootstrapping engine(s) [<no-attributes>=<in-mem>]
I180116 16:28:48.331133 157820 server/node.go:428  [n3] node=3: started with [] engine(s) and attributes []
I180116 16:28:48.331187 157820 sql/distsql_physical_planner.go:122  [n3] creating DistSQLPlanner with address {tcp 127.0.0.1:41455}
I180116 16:28:48.332045 158569 storage/stores.go:350  [n1] wrote 2 node addresses to persistent storage
I180116 16:28:48.332494 158378 storage/stores.go:350  [n2] wrote 2 node addresses to persistent storage
I180116 16:28:48.333695 158621 server/node.go:608  [n3] bootstrapped store [n3,s3]
I180116 16:28:48.334336 157820 server/server.go:1161  [n3] starting https server at 127.0.0.1:38685
I180116 16:28:48.334361 157820 server/server.go:1162  [n3] starting grpc/postgres server at 127.0.0.1:41455
I180116 16:28:48.334371 157820 server/server.go:1163  [n3] advertising CockroachDB node at 127.0.0.1:41455
I180116 16:28:48.336042 157820 server/server.go:1232  [n3] done ensuring all necessary migrations have run
I180116 16:28:48.336068 157820 server/server.go:1235  [n3] serving sql connections
I180116 16:28:48.336926 157837 storage/replica_raftstorage.go:540  [replicate,n1,s1,r14/1:/Table/1{7-8}] generated preemptive snapshot f64aec7c at index 16
I180116 16:28:48.338143 157820 testutils/testcluster/testcluster.go:528  [n1,s1] has 20 underreplicated ranges
I180116 16:28:48.341425 158772 sql/event_log.go:115  [n3] Event: "node_join", target: 3, info: {Descriptor:{NodeID:3 Address:{NetworkField:tcp AddressField:127.0.0.1:41455} Attrs: Locality: ServerVersion:1.1-8} ClusterID:f8371979-8bbb-42c2-9861-24b11bebe89a StartedAt:1516120128331124840 LastUp:1516120128331124840}
I180116 16:28:48.347632 157837 storage/store.go:3567  [replicate,n1,s1,r14/1:/Table/1{7-8}] streamed snapshot to (n2,s2):?: kv pairs: 10, log entries: 6, rate-limit: 8.0 MiB/sec, 1ms
I180116 16:28:48.347635 157820 testutils/testcluster/testcluster.go:528  [n1,s1] has 20 underreplicated ranges
I180116 16:28:48.347987 158803 storage/replica_raftstorage.go:746  [n2,s2,r14/?:{-}] applying preemptive snapshot at index 16 (id=f64aec7c, encoded size=2476, 1 rocksdb batches, 6 log entries)
I180116 16:28:48.348263 158803 storage/replica_raftstorage.go:752  [n2,s2,r14/?:/Table/1{7-8}] applied preemptive snapshot in 0ms [clear=0ms batch=0ms entries=0ms commit=0ms]
I180116 16:28:48.348887 157837 storage/replica_command.go:1741  [replicate,n1,s1,r14/1:/Table/1{7-8}] change replicas (ADD_REPLICA (n2,s2):2): read existing descriptor r14:/Table/1{7-8} [(n1,s1):1, next=2]
I180116 16:28:48.350793 157837 storage/replica.go:3185  [n1,s1,r14/1:/Table/1{7-8}] proposing ADD_REPLICA((n2,s2):2): updated=[(n1,s1):1 (n2,s2):2] next=3
I180116 16:28:48.351402 157837 storage/replica_raftstorage.go:540  [replicate,n1,s1,r1/1:/{Min-System/}] generated preemptive snapshot e1f75307 at index 71
I180116 16:28:48.352589 158823 storage/raft_transport.go:459  [n2] raft transport stream to node 1 established
I180116 16:28:48.361942 157837 storage/store.go:3567  [replicate,n1,s1,r1/1:/{Min-System/}] streamed snapshot to (n3,s3):?: kv pairs: 54, log entries: 48, rate-limit: 8.0 MiB/sec, 1ms
I180116 16:28:48.362387 158559 storage/replica_raftstorage.go:746  [n3,s3,r1/?:{-}] applying preemptive snapshot at index 71 (id=e1f75307, encoded size=13369, 1 rocksdb batches, 48 log entries)
I180116 16:28:48.363289 158559 storage/replica_raftstorage.go:752  [n3,s3,r1/?:/{Min-System/}] applied preemptive snapshot in 1ms [clear=0ms batch=0ms entries=0ms commit=1ms]
I180116 16:28:48.363942 157837 storage/replica_command.go:1741  [replicate,n1,s1,r1/1:/{Min-System/}] change replicas (ADD_REPLICA (n3,s3):2): read existing descriptor r1:/{Min-System/} [(n1,s1):1, next=2]
I180116 16:28:48.366319 157837 storage/replica.go:3185  [n1,s1,r1/1:/{Min-System/}] proposing ADD_REPLICA((n3,s3):2): updated=[(n1,s1):1 (n3,s3):2] next=3
I180116 16:28:48.366959 158032 storage/replica_raftstorage.go:540  [replicate,n1,s1,r1/1:/{Min-System/}] generated preemptive snapshot 00ee5272 at index 74
I180116 16:28:48.367888 158032 storage/store.go:3567  [replicate,n1,s1,r1/1:/{Min-System/}] streamed snapshot to (n2,s2):?: kv pairs: 57, log entries: 51, rate-limit: 8.0 MiB/sec, 1ms
I180116 16:28:48.367926 158765 storage/raft_transport.go:459  [n3] raft transport stream to node 1 established
I180116 16:28:48.368247 158760 storage/replica_raftstorage.go:746  [n2,s2,r1/?:{-}] applying preemptive snapshot at index 74 (id=00ee5272, encoded size=14974, 1 rocksdb batches, 51 log entries)
I180116 16:28:48.368561 158760 storage/replica_raftstorage.go:752  [n2,s2,r1/?:/{Min-System/}] applied preemptive snapshot in 0ms [clear=0ms batch=0ms entries=0ms commit=0ms]
I180116 16:28:48.369087 158032 storage/replica_command.go:1741  [replicate,n1,s1,r1/1:/{Min-System/}] change replicas (ADD_REPLICA (n2,s2):3): read existing descriptor r1:/{Min-System/} [(n1,s1):1, (n3,s3):2, next=3]
I180116 16:28:48.369837 157820 testutils/testcluster/testcluster.go:528  [n1,s1] has 20 underreplicated ranges
I180116 16:28:48.371442 158776 storage/replica.go:3185  [n1,s1,r1/1:/{Min-System/}] proposing ADD_REPLICA((n2,s2):3): updated=[(n1,s1):1 (n3,s3):2 (n2,s2):3] next=4
I180116 16:28:48.372556 157837 storage/replica_raftstorage.go:540  [replicate,n1,s1,r6/1:/{System/tse-Table/System…}] generated preemptive snapshot 3f2e384e at index 19
panic: test timed out after 4m0s

goroutine 158843 [running]:
testing.startAlarm.func1()
	/usr/local/go/src/testing/testing.go:1145 +0xf9
created by time.goFunc
	/usr/local/go/src/time/sleep.go:170 +0x44

goroutine 1 [chan receive]:
testing.(*T).Run(0xc4200a0780, 0x230e293, 0x1e, 0x23c7f38, 0x8d4f01)
	/usr/local/go/src/testing/testing.go:790 +0x2fc
testing.runTests.func1(0xc4200a0780)
	/usr/local/go/src/testing/testing.go:1004 +0x64
testing.tRunner(0xc4200a0780, 0xc4206a5db8)
	/usr/local/go/src/testing/testing.go:746 +0xd0
testing.runTests(0xc4202a2080, 0x33b3600, 0x38, 0x38, 0x0)
	/usr/local/go/src/testing/testing.go:1002 +0x2d8
testing.(*M).Run(0xc42092bf18, 0x23c81c8)
	/usr/local/go/src/testing/testing.go:921 +0x111
github.com/cockroachdb/cockroach/pkg/ccl/sqlccl.TestMain(0xc4206a5f18)
	/go/src/github.com/cockroachdb/cockroach/pkg/ccl/sqlccl/main_test.go:31 +0xda
main.main()
	github.com/cockroachdb/cockroach/pkg/ccl/sqlccl/_test/_testmain.go:172 +0xdb

goroutine 6 [chan receive]:
github.com/cockroachdb/cockroach/pkg/util/log.(*loggingT).flushDaemon(0x3600940)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/log/clog.go:1043 +0x81
created by github.com/cockroachdb/cockroach/pkg/util/log.init.0
	/go/src/github.com/cockroachdb/cockroach/pkg/util/log/clog.go:581 +0xbf

goroutine 23 [syscall, 4 minutes]:
os/signal.signal_recv(0x0)
	/usr/local/go/src/runtime/sigqueue.go:131 +0xa6
os/signal.loop()
	/usr/local/go/src/os/signal/signal_unix.go:22 +0x22
created by os/signal.init.0
	/usr/local/go/src/os/signal/signal_unix.go:28 +0x41

goroutine 148702 [chan receive]:
testing.(*T).Run(0xc422d000f0, 0x22e6b00, 0x7, 0xc42041aec0, 0x1)
	/usr/local/go/src/testing/testing.go:790 +0x2fc
github.com/cockroachdb/cockroach/pkg/ccl/sqlccl_test.TestRestoreDatabaseVersusTable(0xc422d000f0)
	/go/src/github.com/cockroachdb/cockroach/pkg/ccl/sqlccl/backup_test.go:2217 +0x808
testing.tRunner(0xc422d000f0, 0x23c7f38)
	/usr/local/go/src/testing/testing.go:746 +0xd0
created by testing.(*T).Run
	/usr/local/go/src/testing/testing.go:789 +0x2de

goroutine 52 [select, locked to thread]:
runtime.gopark(0x23cbcc0, 0x0, 0x22e54ff, 0x6, 0x18, 0x1)
	/usr/local/go/src/runtime/proc.go:277 +0x12c
runtime.selectgo(0xc42003ff50, 0xc42044ac00)
	/usr/local/go/src/runtime/select.go:395 +0x1138
runtime.ensureSigM.func1()
	/usr/local/go/src/runtime/signal_unix.go:511 +0x220
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:2337 +0x1

goroutine 158708 [semacquire]:
sync.runtime_notifyListWait(0xc422edce50, 0xc40000003b)
	/usr/local/go/src/runtime/sema.go:507 +0x110
sync.(*Cond).Wait(0xc422edce40)
	/usr/local/go/src/sync/cond.go:56 +0x80
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).worker(0xc4224a1290, 0x33de160, 0xc421c0cd50)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:197 +0x7c
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).Start.func2(0x33de160, 0xc421c0cd50)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:166 +0x3e
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc4202db080, 0xc4225a1950, 0xc4202db070)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:195 +0xf3
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:188 +0xad

goroutine 158505 [semacquire]:
sync.runtime_notifyListWait(0xc422422350, 0xc400000036)
	/usr/local/go/src/runtime/sema.go:507 +0x110
sync.(*Cond).Wait(0xc422422340)
	/usr/local/go/src/sync/cond.go:56 +0x80
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).worker(0xc421996240, 0x33de160, 0xc4226530b0)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:197 +0x7c
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).Start.func2(0x33de160, 0xc4226530b0)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:166 +0x3e
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc4208ec9a0, 0xc421bc1050, 0xc4208ec990)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:195 +0xf3
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:188 +0xad

goroutine 158333 [select]:
github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/transport.(*http2Server).keepalive(0xc421dfe160)
	/go/src/github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/transport/http2_server.go:935 +0x264
created by github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/transport.newHTTP2Server
	/go/src/github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/transport/http2_server.go:230 +0x8fa

goroutine 158015 [semacquire]:
sync.runtime_notifyListWait(0xc422242450, 0xc40000016b)
	/usr/local/go/src/runtime/sema.go:507 +0x110
sync.(*Cond).Wait(0xc422242440)
	/usr/local/go/src/sync/cond.go:56 +0x80
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).worker(0xc4226081b0, 0x33de160, 0xc4213c6a50)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:197 +0x7c
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).Start.func2(0x33de160, 0xc4213c6a50)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:166 +0x3e
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc4203c6c90, 0xc4228a1a70, 0xc4203c6c80)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:195 +0xf3
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:188 +0xad

goroutine 158070 [select]:
github.com/cockroachdb/cockroach/pkg/sql.(*SchemaChangeManager).Start.func1(0x33de160, 0xc422d02a20)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/schema_changer.go:1023 +0x9b6
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc4214b6660, 0xc4228a1a70, 0xc4202be240)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:195 +0xf3
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:188 +0xad

goroutine 158396 [select]:
github.com/cockroachdb/cockroach/pkg/server.(*Server).startSampleEnvironment.func1(0x33de160, 0xc420846ff0)
	/go/src/github.com/cockroachdb/cockroach/pkg/server/server.go:1416 +0x16c
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc420e0a540, 0xc421bc1050, 0xc423a7ef80)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:195 +0xf3
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:188 +0xad

goroutine 158468 [semacquire]:
sync.runtime_notifyListWait(0xc422422350, 0xc400000033)
	/usr/local/go/src/runtime/sema.go:507 +0x110
sync.(*Cond).Wait(0xc422422340)
	/usr/local/go/src/sync/cond.go:56 +0x80
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).worker(0xc421996240, 0x33de160, 0xc423b6c7b0)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:197 +0x7c
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).Start.func2(0x33de160, 0xc423b6c7b0)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:166 +0x3e
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc4208ec500, 0xc421bc1050, 0xc4208ec4f0)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:195 +0xf3
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:188 +0xad

goroutine 149011 [semacquire]:
sync.runtime_notifyListWait(0xc421b20590, 0xc400000236)
	/usr/local/go/src/runtime/sema.go:507 +0x110
sync.(*Cond).Wait(0xc421b20580)
	/usr/local/go/src/sync/cond.go:56 +0x80
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).worker(0xc4221ce240, 0x33de160, 0xc4225f87e0)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:197 +0x7c
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).Start.func2(0x33de160, 0xc4225f87e0)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:166 +0x3e
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc420400560, 0xc422db45a0, 0xc420400550)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:195 +0xf3
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:188 +0xad

goroutine 148982 [semacquire]:
sync.runtime_notifyListWait(0xc421b20590, 0xc400000249)
	/usr/local/go/src/runtime/sema.go:507 +0x110
sync.(*Cond).Wait(0xc421b20580)
	/usr/local/go/src/sync/cond.go:56 +0x80
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).worker(0xc4221ce240, 0x33de160, 0xc42446a120)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:197 +0x7c
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).Start.func2(0x33de160, 0xc42446a120)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:166 +0x3e
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc420400090, 0xc422db45a0, 0xc420400080)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:195 +0xf3
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:188 +0xad

goroutine 158005 [semacquire]:
sync.runtime_notifyListWait(0xc422242450, 0xc400000170)
	/usr/local/go/src/runtime/sema.go:507 +0x110
sync.(*Cond).Wait(0xc422242440)
	/usr/local/go/src/sync/cond.go:56 +0x80
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).worker(0xc4226081b0, 0x33de160, 0xc4229586f0)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:197 +0x7c
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).Start.func2(0x33de160, 0xc4229586f0)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:166 +0x3e
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc4203c6ab0, 0xc4228a1a70, 0xc4203c6aa0)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:195 +0xf3
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:188 +0xad

goroutine 158624 [select]:
github.com/cockroachdb/cockroach/pkg/server.(*Server).refreshSettings.func2(0x33de160, 0xc42518a510)
	/go/src/github.com/cockroachdb/cockroach/pkg/server/settingsworker.go:112 +0x2db
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc423ab7b60, 0xc4225a1950, 0xc4203507e0)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:195 +0xf3
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:188 +0xad

goroutine 158440 [chan receive]:
github.com/cockroachdb/cockroach/vendor/github.com/cockroachdb/cmux.muxListener.Accept(...)
	/go/src/github.com/cockroachdb/cockroach/vendor/github.com/cockroachdb/cmux/cmux.go:184
github.com/cockroachdb/cockroach/vendor/github.com/cockroachdb/cmux.(*muxListener).Accept(0xc421a56540, 0xc425609530, 0xc42475be80, 0x96d4e5, 0xc425609558)
	<autogenerated>:1 +0x65
crypto/tls.(*listener).Accept(0xc421a565a0, 0xc420014108, 0x2068180, 0x3397560, 0x22ae720)
	/usr/local/go/src/crypto/tls/tls.go:52 +0x37
net/http.(*Server).Serve(0xc42139be10, 0x33cf8a0, 0xc421a565a0, 0x0, 0x0)
	/usr/local/go/src/net/http/server.go:2695 +0x1b2
github.com/cockroachdb/cockroach/pkg/server.(*Server).Start.func5(0x33de160, 0xc4256094d0)
	/go/src/github.com/cockroachdb/cockroach/pkg/server/server.go:779 +0x42
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc4203c6880, 0xc4225a1950, 0xc421a565c0)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:195 +0xf3
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:188 +0xad

goroutine 158623 [select]:
github.com/cockroachdb/cockroach/pkg/server.(*Node).startGossip.func1(0x33de160, 0xc42518a4e0)
	/go/src/github.com/cockroachdb/cockroach/pkg/server/node.go:680 +0x2dd
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc423ab7b30, 0xc4225a1950, 0xc4203507c0)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:195 +0xf3
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:188 +0xad

goroutine 158370 [chan receive]:
github.com/cockroachdb/cockroach/vendor/github.com/cockroachdb/cmux.muxListener.Accept(...)
	/go/src/github.com/cockroachdb/cockroach/vendor/github.com/cockroachdb/cmux/cmux.go:184
github.com/cockroachdb/cockroach/vendor/github.com/cockroachdb/cmux.(*muxListener).Accept(0xc422adae20, 0x23cb0a0, 0xc4209328c0, 0x33e9f60, 0xc42324eaa0)
	<autogenerated>:1 +0x65
github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc.(*Server).Serve(0xc4209328c0, 0x33dd2e0, 0xc422adae20, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/server.go:463 +0x196
github.com/cockroachdb/cockroach/pkg/server.(*Server).Start.func7(0x33de160, 0xc4214a0fc0)
	/go/src/github.com/cockroachdb/cockroach/pkg/server/server.go:795 +0x43
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc420c96c20, 0xc421bc1050, 0xc422adaf40)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:195 +0xf3
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:188 +0xad

goroutine 158496 [semacquire]:
sync.runtime_notifyListWait(0xc422422350, 0xc400000024)
	/usr/local/go/src/runtime/sema.go:507 +0x110
sync.(*Cond).Wait(0xc422422340)
	/usr/local/go/src/sync/cond.go:56 +0x80
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).worker(0xc421996240, 0x33de160, 0xc422652ed0)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:197 +0x7c
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).Start.func2(0x33de160, 0xc422652ed0)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:166 +0x3e
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc4208ec880, 0xc421bc1050, 0xc4208ec870)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:195 +0xf3
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:188 +0xad

goroutine 158271 [semacquire]:
sync.runtime_notifyListWait(0xc422422350, 0xc400000006)
	/usr/local/go/src/runtime/sema.go:507 +0x110
sync.(*Cond).Wait(0xc422422340)
	/usr/local/go/src/sync/cond.go:56 +0x80
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).worker(0xc421996240, 0x33de160, 0xc423b6c360)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:197 +0x7c
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).Start.func2(0x33de160, 0xc423b6c360)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:166 +0x3e
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc4208ec260, 0xc421bc1050, 0xc4208ec250)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:195 +0xf3
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:188 +0xad

goroutine 158098 [select]:
github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/transport.(*http2Client).keepalive(0xc420c48d80)
	/go/src/github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/transport/http2_client.go:1266 +0x14b
created by github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/transport.newHTTP2Client
	/go/src/github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/transport/http2_client.go:302 +0xe51

goroutine 158796 [select]:
github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/transport.(*recvBufferReader).read(0xc4213d3270, 0xc4231bafd0, 0x5, 0x5, 0xf, 0xc4238fbb48, 0x8719e8)
	/go/src/github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/transport/transport.go:133 +0x28b
github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/transport.(*recvBufferReader).Read(0xc4213d3270, 0xc4231bafd0, 0x5, 0x5, 0x3, 0xc420022000, 0xc420022070)
	/go/src/github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/transport/transport.go:122 +0x67
github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/transport.(*transportReader).Read(0xc422026f30, 0xc4231bafd0, 0x5, 0x5, 0x8bcfce, 0xc421e010c8, 0xc421af6100)
	/go/src/github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/transport/transport.go:403 +0x55
io.ReadAtLeast(0x33c43a0, 0xc422026f30, 0xc4231bafd0, 0x5, 0x5, 0x5, 0xc4221e6580, 0xc421e01000, 0xc400000005)
	/usr/local/go/src/io/io.go:309 +0x86
io.ReadFull(0x33c43a0, 0xc422026f30, 0xc4231bafd0, 0x5, 0x5, 0x87495b, 0xc4238fbc40, 0x89ff20)
	/usr/local/go/src/io/io.go:327 +0x58
github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/transport.(*Stream).Read(0xc421e01000, 0xc4231bafd0, 0x5, 0x5, 0xc4238fbcc0, 0x88770a, 0xc4222663c0)
	/go/src/github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/transport/transport.go:387 +0xbf
github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc.(*parser).recvMsg(0xc4231bafc0, 0x7fffffff, 0x60, 0x58, 0x220a4a0, 0xc4238fbdb8, 0xe0000000006, 0x58)
	/go/src/github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/rpc_util.go:270 +0x65
github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc.recv(0xc4231bafc0, 0x33dd960, 0x364bc88, 0xc421e01000, 0x33cdf60, 0x364bc88, 0x21c71a0, 0xc42040a4a0, 0x7fffffff, 0xc42378c7e0, ...)
	/go/src/github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/rpc_util.go:356 +0x4d
github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc.(*serverStream).RecvMsg(0xc4237e2680, 0x21c71a0, 0xc42040a4a0, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/stream.go:644 +0x10e
github.com/cockroachdb/cockroach/pkg/storage.(*multiRaftRaftMessageBatchServer).Recv(0xc4208ecdc0, 0x33de160, 0xc422026fc0, 0xc424d00900)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/raft.pb.go:394 +0x62
github.com/cockroachdb/cockroach/pkg/storage.(*RaftTransport).RaftMessageBatch.func1.1.1(0x33e9e40, 0xc4208ecdc0, 0xc4221dc5a0, 0x33de160, 0xc422026fc0, 0x18, 0xfe67b0)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/raft_transport.go:330 +0x83
github.com/cockroachdb/cockroach/pkg/storage.(*RaftTransport).RaftMessageBatch.func1.1(0x33de160, 0xc422026fc0)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/raft_transport.go:353 +0x5d
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc4208ecde0, 0xc4228a1a70, 0xc422026f90)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:195 +0xf3
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:188 +0xad

goroutine 158720 [select]:
github.com/cockroachdb/cockroach/pkg/storage.(*Store).startGossip.func4(0x33de160, 0xc421c0d020)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/store.go:1313 +0x3e9
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc4202db1d0, 0xc4225a1950, 0xc420f92640)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:195 +0xf3
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:188 +0xad

goroutine 158821 [select]:
github.com/cockroachdb/cockroach/pkg/storage.(*RaftTransport).RaftMessageBatch(0xc422d01950, 0x33e9e40, 0xc420e0be60, 0x33cb720, 0xc422d01950)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/raft_transport.go:359 +0x215
github.com/cockroachdb/cockroach/pkg/storage._MultiRaft_RaftMessageBatch_Handler(0x22a9c60, 0xc422d01950, 0x33e7200, 0xc420a36980, 0x8580c8, 0x20)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/raft.pb.go:375 +0xb2
github.com/cockroachdb/cockroach/pkg/rpc.NewServerWithInterceptor.func2(0x22a9c60, 0xc422d01950, 0x33e7200, 0xc420a36980, 0xc421a57b80, 0x23c9b20, 0x40, 0x3f)
	/go/src/github.com/cockroachdb/cockroach/pkg/rpc/context.go:187 +0x103
github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc.(*Server).processStreamingRPC(0xc4209328c0, 0x33e92a0, 0xc4238e0160, 0xc423370900, 0xc422822390, 0x33a50c0, 0x0, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/server.go:940 +0x2e8
github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc.(*Server).handleStream(0xc4209328c0, 0x33e92a0, 0xc4238e0160, 0xc423370900, 0x0)
	/go/src/github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/server.go:1027 +0x14c1
github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc4202cc500, 0xc4209328c0, 0x33e92a0, 0xc4238e0160, 0xc423370900)
	/go/src/github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/server.go:572 +0x9f
created by github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc.(*Server).serveStreams.func1
	/go/src/github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/server.go:570 +0xa1

goroutine 158364 [chan receive]:
github.com/cockroachdb/cockroach/pkg/util/netutil.MakeServer.func2(0x33de160, 0xc4208df9b0)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/netutil/net.go:100 +0x64
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc420c96b40, 0xc421bc1050, 0xc422adad40)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:195 +0xf3
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:188 +0xad

goroutine 158668 [semacquire]:
sync.runtime_notifyListWait(0xc422edce50, 0xc400000013)
	/usr/local/go/src/runtime/sema.go:507 +0x110
sync.(*Cond).Wait(0xc422edce40)
	/usr/local/go/src/sync/cond.go:56 +0x80
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).worker(0xc4224a1290, 0x33de160, 0xc421c0c450)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:197 +0x7c
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).Start.func2(0x33de160, 0xc421c0c450)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:166 +0x3e
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc4202da9f0, 0xc4225a1950, 0xc4202da9d0)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:195 +0xf3
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:188 +0xad

goroutine 157984 [semacquire]:
sync.runtime_notifyListWait(0xc422242450, 0xc400000169)
	/usr/local/go/src/runtime/sema.go:507 +0x110
sync.(*Cond).Wait(0xc422242440)
	/usr/local/go/src/sync/cond.go:56 +0x80
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).worker(0xc4226081b0, 0x33de160, 0xc4213c6990)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:197 +0x7c
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).Start.func2(0x33de160, 0xc4213c6990)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:166 +0x3e
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc4203c6780, 0xc4228a1a70, 0xc4203c6770)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:195 +0xf3
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:188 +0xad

goroutine 158319 [select]:
github.com/cockroachdb/cockroach/pkg/storage.(*baseQueue).processLoop.func1(0x33de160, 0xc421c0d140)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/queue.go:514 +0x1bb
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc4208ec080, 0xc4225a1950, 0xc4203de180)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:195 +0xf3
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:188 +0xad

goroutine 158019 [semacquire]:
sync.runtime_notifyListWait(0xc422242450, 0xc40000017c)
	/usr/local/go/src/runtime/sema.go:507 +0x110
sync.(*Cond).Wait(0xc422242440)
	/usr/local/go/src/sync/cond.go:56 +0x80
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).worker(0xc4226081b0, 0x33de160, 0xc422d02690)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:197 +0x7c
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).Start.func2(0x33de160, 0xc422d02690)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:166 +0x3e
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc4203c6d10, 0xc4228a1a70, 0xc4203c6d00)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:195 +0xf3
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:188 +0xad

goroutine 158596 [select]:
github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/transport.(*recvBufferReader).read(0xc421a615e0, 0xc422adb050, 0x5, 0x5, 0xc42042f301, 0xc421dfd830, 0x8719e8)
	/go/src/github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/transport/transport.go:133 +0x28b
github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/transport.(*recvBufferReader).Read(0xc421a615e0, 0xc422adb050, 0x5, 0x5, 0x3, 0xc420024600, 0xc420024670)
	/go/src/github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/transport/transport.go:122 +0x67
github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/transport.(*transportReader).Read(0xc4245636e0, 0xc422adb050, 0x5, 0x5, 0x8bcfce, 0xc4201ce4c8, 0xc422a99580)
	/go/src/github.com/cockroachdb/cockroach/vendor/google.gola
```
Please assign, take a look and update the issue accordingly.

### LINKED ISSUE #21474: teamcity: failed tests on master: test/TestRestoreDatabaseVersusTable/incomplete-db, test/TestRestoreDatabaseVersusTable, testrace/TestRestoreDatabaseVersusTable, testrace/TestRestoreDatabaseVersusTable/incomplete-db
The following tests appear to have failed:

[#480492](https://teamcity.cockroachdb.com/viewLog.html?buildId=480492):

```
--- FAIL: test/TestRestoreDatabaseVersusTable/incomplete-db (0.000s)
Test ended in panic.

------- Stdout: -------
W180116 17:14:45.516590 160767 server/status/runtime.go:109  Could not parse build timestamp: parsing time "" as "2006/01/02 15:04:05": cannot parse "" as "2006"
I180116 17:14:45.520816 160767 server/config.go:518  [n?] 1 storage engine initialized
I180116 17:14:45.520851 160767 server/config.go:521  [n?] RocksDB cache size: 128 MiB
I180116 17:14:45.520860 160767 server/config.go:521  [n?] store 0: in-memory, size 0 B
I180116 17:14:45.523750 160767 server/node.go:361  [n?] **** cluster 77c09539-547a-449f-bc09-43253e3e6131 has been created
I180116 17:14:45.523785 160767 server/server.go:937  [n?] **** add additional nodes by specifying --join=127.0.0.1:40969
I180116 17:14:45.524603 160767 storage/store.go:1312  [n1,s1] [n1,s1]: failed initial metrics computation: [n1,s1]: system config not yet available
I180116 17:14:45.524657 160767 server/node.go:491  [n1] initialized store [n1,s1]: disk (capacity=512 MiB, available=512 MiB, used=0 B, logicalBytes=3.2 KiB), ranges=1, leases=0, writes=0.00, bytesPerReplica={p10=3322.00 p25=3322.00 p50=3322.00 p75=3322.00 p90=3322.00}, writesPerReplica={p10=0.00 p25=0.00 p50=0.00 p75=0.00 p90=0.00}
I180116 17:14:45.524690 160767 server/node.go:339  [n1] node ID 1 initialized
I180116 17:14:45.524746 160767 gossip/gossip.go:332  [n1] NodeDescriptor set to node_id:1 address:<network_field:"tcp" address_field:"127.0.0.1:40969" > attrs:<> locality:<> ServerVersion:<major_val:1 minor_val:1 patch:0 unstable:9 > 
I180116 17:14:45.524887 160767 storage/stores.go:331  [n1] read 0 node addresses from persistent storage
I180116 17:14:45.524944 160767 server/node.go:632  [n1] connecting to gossip network to verify cluster ID...
I180116 17:14:45.524963 160767 server/node.go:657  [n1] node connected via gossip and verified as part of cluster "77c09539-547a-449f-bc09-43253e3e6131"
I180116 17:14:45.524983 160767 server/node.go:433  [n1] node=1: started with [<no-attributes>=<in-mem>] engine(s) and attributes []
I180116 17:14:45.525020 160767 sql/distsql_physical_planner.go:122  [n1] creating DistSQLPlanner with address {tcp 127.0.0.1:40969}
I180116 17:14:45.526868 160997 storage/replica_command.go:830  [split,n1,s1,r1/1:/M{in-ax}] initiating a split of this range at key /System/"" [r2]
I180116 17:14:45.527914 160767 server/server.go:1164  [n1] starting https server at 127.0.0.1:43065
I180116 17:14:45.527940 160767 server/server.go:1165  [n1] starting grpc/postgres server at 127.0.0.1:40969
I180116 17:14:45.527951 160767 server/server.go:1166  [n1] advertising CockroachDB node at 127.0.0.1:40969
I180116 17:14:45.540109 160997 storage/replica_command.go:830  [split,n1,s1,r2/1:/{System/-Max}] initiating a split of this range at key /System/NodeLiveness [r3]
I180116 17:14:45.544115 160997 storage/replica_command.go:830  [split,n1,s1,r3/1:/{System/NodeL…-Max}] initiating a split of this range at key /System/NodeLivenessMax [r4]
W180116 17:14:45.544809 161046 storage/intent_resolver.go:320  [n1,s1] failed to push during intent resolution: failed to push "sql txn implicit" id=37d7937d key=/Table/SystemConfigSpan/Start rw=true pri=0.06125686 iso=SERIALIZABLE stat=PENDING epo=0 ts=1516122885.540368499,0 orig=1516122885.540368499,0 max=1516122885.540368499,0 wto=false rop=false seq=7
I180116 17:14:45.546140 160767 sql/event_log.go:115  [n1] Event: "alter_table", target: 12, info: {TableName:eventlog Statement:ALTER TABLE system.eventlog ALTER COLUMN "uniqueID" SET DEFAULT uuid_v4() User:node MutationID:0 CascadeDroppedViews:[]}
I180116 17:14:45.548337 160997 storage/replica_command.go:830  [split,n1,s1,r4/1:/{System/NodeL…-Max}] initiating a split of this range at key /System/tsd [r5]
I180116 17:14:45.550529 160767 sql/lease.go:348  [n1] publish: descID=12 (eventlog) version=2 mtime=2018-01-16 17:14:45.550301198 +0000 UTC
I180116 17:14:45.553137 160997 storage/replica_command.go:830  [split,n1,s1,r5/1:/{System/tsd-Max}] initiating a split of this range at key /System/"tse" [r6]
I180116 17:14:45.558984 160997 storage/replica_command.go:830  [split,n1,s1,r6/1:/{System/tse-Max}] initiating a split of this range at key /Table/SystemConfigSpan/Start [r7]
I180116 17:14:45.563072 160997 storage/replica_command.go:830  [split,n1,s1,r7/1:/{Table/System…-Max}] initiating a split of this range at key /Table/11 [r8]
I180116 17:14:45.566865 160997 storage/replica_command.go:830  [split,n1,s1,r8/1:/{Table/11-Max}] initiating a split of this range at key /Table/12 [r9]
I180116 17:14:45.566970 160767 sql/event_log.go:115  [n1] Event: "set_cluster_setting", target: 0, info: {SettingName:diagnostics.reporting.enabled Value:true User:node}
I180116 17:14:45.570827 160997 storage/replica_command.go:830  [split,n1,s1,r9/1:/{Table/12-Max}] initiating a split of this range at key /Table/13 [r10]
I180116 17:14:45.574646 160997 storage/replica_command.go:830  [split,n1,s1,r10/1:/{Table/13-Max}] initiating a split of this range at key /Table/14 [r11]
I180116 17:14:45.576203 160767 sql/event_log.go:115  [n1] Event: "set_cluster_setting", target: 0, info: {SettingName:version Value:$1 User:node}
I180116 17:14:45.578635 160997 storage/replica_command.go:830  [split,n1,s1,r11/1:/{Table/14-Max}] initiating a split of this range at key /Table/15 [r12]
I180116 17:14:45.579987 160767 sql/event_log.go:115  [n1] Event: "set_cluster_setting", target: 0, info: {SettingName:trace.debug.enable Value:false User:node}
I180116 17:14:45.584608 160997 storage/replica_command.go:830  [split,n1,s1,r12/1:/{Table/15-Max}] initiating a split of this range at key /Table/16 [r13]
I180116 17:14:45.588246 160997 storage/replica_command.go:830  [split,n1,s1,r13/1:/{Table/16-Max}] initiating a split of this range at key /Table/17 [r14]
I180116 17:14:45.592041 160997 storage/replica_command.go:830  [split,n1,s1,r14/1:/{Table/17-Max}] initiating a split of this range at key /Table/18 [r15]
I180116 17:14:45.593491 160767 sql/event_log.go:115  [n1] Event: "alter_table", target: 4, info: {TableName:users Statement:ALTER TABLE system.users ADD COLUMN IF NOT EXISTS "isRole" BOOL NOT NULL DEFAULT false User:node MutationID:1 CascadeDroppedViews:[]}
I180116 17:14:45.595607 160997 storage/replica_command.go:830  [split,n1,s1,r15/1:/{Table/18-Max}] initiating a split of this range at key /Table/19 [r16]
I180116 17:14:45.596064 160767 sql/lease.go:348  [n1] publish: descID=4 (users) version=2 mtime=2018-01-16 17:14:45.595944802 +0000 UTC
I180116 17:14:45.599054 160997 storage/replica_command.go:830  [split,n1,s1,r16/1:/{Table/19-Max}] initiating a split of this range at key /Table/20 [r17]
I180116 17:14:45.600064 160767 sql/lease.go:348  [n1] publish: descID=4 (users) version=3 mtime=2018-01-16 17:14:45.599950769 +0000 UTC
I180116 17:14:45.602855 160997 storage/replica_command.go:830  [split,n1,s1,r17/1:/{Table/20-Max}] initiating a split of this range at key /Table/21 [r18]
I180116 17:14:45.605503 160767 sql/backfill.go:133  [n1] Running backfill for "users", v=3, m=1
I180116 17:14:45.606035 160997 storage/replica_command.go:830  [split,n1,s1,r18/1:/{Table/21-Max}] initiating a split of this range at key /Table/22 [r19]
I180116 17:14:45.609247 160997 storage/replica_command.go:830  [split,n1,s1,r19/1:/{Table/22-Max}] initiating a split of this range at key /Table/23 [r20]
I180116 17:14:45.613474 160767 sql/lease.go:348  [n1] publish: descID=4 (users) version=4 mtime=2018-01-16 17:14:45.613390395 +0000 UTC
I180116 17:14:45.616319 160767 sql/event_log.go:115  [n1] Event: "finish_schema_change", target: 4, info: {MutationID:1}
I180116 17:14:45.616948 160767 sql/lease.go:274  publish (count leases): descID=4 name=users version=3 count=1
I180116 17:14:45.657110 160767 server/server.go:1235  [n1] done ensuring all necessary migrations have run
I180116 17:14:45.657164 160767 server/server.go:1238  [n1] serving sql connections
I180116 17:14:45.659530 161275 sql/event_log.go:115  [n1] Event: "node_join", target: 1, info: {Descriptor:{NodeID:1 Address:{NetworkField:tcp AddressField:127.0.0.1:40969} Attrs: Locality: ServerVersion:1.1-9} ClusterID:77c09539-547a-449f-bc09-43253e3e6131 StartedAt:1516122885524965806 LastUp:1516122885524965806}
W180116 17:14:45.663133 160767 server/status/runtime.go:109  Could not parse build timestamp: parsing time "" as "2006/01/02 15:04:05": cannot parse "" as "2006"
I180116 17:14:45.665631 160767 server/config.go:518  [n?] 1 storage engine initialized
I180116 17:14:45.665659 160767 server/config.go:521  [n?] RocksDB cache size: 128 MiB
I180116 17:14:45.665665 160767 server/config.go:521  [n?] store 0: in-memory, size 0 B
W180116 17:14:45.665722 160767 gossip/gossip.go:1292  [n?] no incoming or outgoing connections
I180116 17:14:45.665771 160767 server/server.go:939  [n?] no stores bootstrapped and --join flag specified, awaiting init command.
I180116 17:14:45.678274 161284 gossip/client.go:129  [n?] started gossip client to 127.0.0.1:40969
I180116 17:14:45.678621 161227 gossip/server.go:219  [n1] received initial cluster-verification connection from {tcp 127.0.0.1:42897}
I180116 17:14:45.679437 160767 storage/stores.go:331  [n?] read 0 node addresses from persistent storage
I180116 17:14:45.679481 160767 storage/stores.go:350  [n?] wrote 1 node addresses to persistent storage
I180116 17:14:45.679491 160767 server/node.go:632  [n?] connecting to gossip network to verify cluster ID...
I180116 17:14:45.679536 160767 server/node.go:657  [n?] node connected via gossip and verified as part of cluster "77c09539-547a-449f-bc09-43253e3e6131"
I180116 17:14:45.679764 161370 kv/dist_sender.go:354  [n?] unable to determine this node's attributes for replica selection; node is most likely bootstrapping
I180116 17:14:45.680729 161369 kv/dist_sender.go:354  [n?] unable to determine this node's attributes for replica selection; node is most likely bootstrapping
I180116 17:14:45.681470 160767 kv/dist_sender.go:354  [n?] unable to determine this node's attributes for replica selection; node is most likely bootstrapping
I180116 17:14:45.682384 160767 server/node.go:332  [n?] new node allocated ID 2
I180116 17:14:45.682485 160767 gossip/gossip.go:332  [n2] NodeDescriptor set to node_id:2 address:<network_field:"tcp" address_field:"127.0.0.1:42897" > attrs:<> locality:<> ServerVersion:<major_val:1 minor_val:1 patch:0 unstable:9 > 
I180116 17:14:45.682546 160767 server/node.go:414  [n2] node=2: asynchronously bootstrapping engine(s) [<no-attributes>=<in-mem>]
I180116 17:14:45.682566 160767 server/node.go:433  [n2] node=2: started with [] engine(s) and attributes []
I180116 17:14:45.682608 160767 sql/distsql_physical_planner.go:122  [n2] creating DistSQLPlanner with address {tcp 127.0.0.1:42897}
I180116 17:14:45.683288 161347 storage/stores.go:350  [n1] wrote 1 node addresses to persistent storage
I180116 17:14:45.685063 161307 server/node.go:613  [n2] bootstrapped store [n2,s2]
I180116 17:14:45.687530 160767 server/server.go:1164  [n2] starting https server at 127.0.0.1:45953
I180116 17:14:45.687617 160767 server/server.go:1165  [n2] starting grpc/postgres server at 127.0.0.1:42897
I180116 17:14:45.687650 160767 server/server.go:1166  [n2] advertising CockroachDB node at 127.0.0.1:42897
I180116 17:14:45.690264 160767 server/server.go:1235  [n2] done ensuring all necessary migrations have run
I180116 17:14:45.690297 160767 server/server.go:1238  [n2] serving sql connections
I180116 17:14:45.695408 161489 sql/event_log.go:115  [n2] Event: "node_join", target: 2, info: {Descriptor:{NodeID:2 Address:{NetworkField:tcp AddressField:127.0.0.1:42897} Attrs: Locality: ServerVersion:1.1-9} ClusterID:77c09539-547a-449f-bc09-43253e3e6131 StartedAt:1516122885682557741 LastUp:1516122885682557741}
W180116 17:14:45.696690 160767 server/status/runtime.go:109  Could not parse build timestamp: parsing time "" as "2006/01/02 15:04:05": cannot parse "" as "2006"
I180116 17:14:45.698776 160767 server/config.go:518  [n?] 1 storage engine initialized
I180116 17:14:45.698796 160767 server/config.go:521  [n?] RocksDB cache size: 128 MiB
I180116 17:14:45.698802 160767 server/config.go:521  [n?] store 0: in-memory, size 0 B
W180116 17:14:45.698847 160767 gossip/gossip.go:1292  [n?] no incoming or outgoing connections
I180116 17:14:45.698876 160767 server/server.go:939  [n?] no stores bootstrapped and --join flag specified, awaiting init command.
I180116 17:14:45.710733 161554 gossip/client.go:129  [n?] started gossip client to 127.0.0.1:40969
I180116 17:14:45.711017 161414 gossip/server.go:219  [n1] received initial cluster-verification connection from {tcp 127.0.0.1:34463}
I180116 17:14:45.711757 160767 storage/stores.go:331  [n?] read 0 node addresses from persistent storage
I180116 17:14:45.711816 160767 storage/stores.go:350  [n?] wrote 2 node addresses to persistent storage
I180116 17:14:45.711874 160767 server/node.go:632  [n?] connecting to gossip network to verify cluster ID...
I180116 17:14:45.711892 160767 server/node.go:657  [n?] node connected via gossip and verified as part of cluster "77c09539-547a-449f-bc09-43253e3e6131"
I180116 17:14:45.712106 161579 kv/dist_sender.go:354  [n?] unable to determine this node's attributes for replica selection; node is most likely bootstrapping
I180116 17:14:45.713023 161578 kv/dist_sender.go:354  [n?] unable to determine this node's attributes for replica selection; node is most likely bootstrapping
I180116 17:14:45.713820 160767 kv/dist_sender.go:354  [n?] unable to determine this node's attributes for replica selection; node is most likely bootstrapping
I180116 17:14:45.714644 160767 server/node.go:332  [n?] new node allocated ID 3
I180116 17:14:45.714726 160767 gossip/gossip.go:332  [n3] NodeDescriptor set to node_id:3 address:<network_field:"tcp" address_field:"127.0.0.1:34463" > attrs:<> locality:<> ServerVersion:<major_val:1 minor_val:1 patch:0 unstable:9 > 
I180116 17:14:45.714784 160767 server/node.go:414  [n3] node=3: asynchronously bootstrapping engine(s) [<no-attributes>=<in-mem>]
I180116 17:14:45.714802 160767 server/node.go:433  [n3] node=3: started with [] engine(s) and attributes []
I180116 17:14:45.714841 160767 sql/distsql_physical_planner.go:122  [n3] creating DistSQLPlanner with address {tcp 127.0.0.1:34463}
I180116 17:14:45.715269 161503 storage/stores.go:350  [n1] wrote 2 node addresses to persistent storage
I180116 17:14:45.715539 161504 storage/stores.go:350  [n2] wrote 2 node addresses to persistent storage
I180116 17:14:45.716199 161588 server/node.go:613  [n3] bootstrapped store [n3,s3]
I180116 17:14:45.720813 160767 server/server.go:1164  [n3] starting https server at 127.0.0.1:43743
I180116 17:14:45.720851 160767 server/server.go:1165  [n3] starting grpc/postgres server at 127.0.0.1:34463
I180116 17:14:45.720870 160767 server/server.go:1166  [n3] advertising CockroachDB node at 127.0.0.1:34463
I180116 17:14:45.722720 160767 server/server.go:1235  [n3] done ensuring all necessary migrations have run
I180116 17:14:45.722747 160767 server/server.go:1238  [n3] serving sql connections
I180116 17:14:45.723794 160813 storage/replica_raftstorage.go:540  [replicate,n1,s1,r17/1:/Table/2{0-1}] generated preemptive snapshot 718d016c at index 15
I180116 17:14:45.725252 160767 testutils/testcluster/testcluster.go:528  [n1,s1] has 20 underreplicated ranges
I180116 17:14:45.727847 161714 sql/event_log.go:115  [n3] Event: "node_join", target: 3, info: {Descriptor:{NodeID:3 Address:{NetworkField:tcp AddressField:127.0.0.1:34463} Attrs: Locality: ServerVersion:1.1-9} ClusterID:77c09539-547a-449f-bc09-43253e3e6131 StartedAt:1516122885714793230 LastUp:1516122885714793230}
I180116 17:14:45.733462 160813 storage/store.go:3670  [replicate,n1,s1,r17/1:/Table/2{0-1}] streamed snapshot to (n3,s3):?: kv pairs: 10, log entries: 5, rate-limit: 8.0 MiB/sec, 1ms
I180116 17:14:45.733815 161392 storage/replica_raftstorage.go:746  [n3,s3,r17/?:{-}] applying preemptive snapshot at index 15 (id=718d016c, encoded size=2411, 1 rocksdb batches, 5 log entries)
I180116 17:14:45.734554 161392 storage/replica_raftstorage.go:752  [n3,s3,r17/?:/Table/2{0-1}] applied preemptive snapshot in 1ms [clear=0ms batch=0ms entries=0ms commit=1ms]
I180116 17:14:45.734712 160767 testutils/testcluster/testcluster.go:528  [n1,s1] has 20 underreplicated ranges
I180116 17:14:45.735094 160813 storage/replica_command.go:1752  [replicate,n1,s1,r17/1:/Table/2{0-1}] change replicas (ADD_REPLICA (n3,s3):2): read existing descriptor r17:/Table/2{0-1} [(n1,s1):1, next=2]
I180116 17:14:45.736770 160813 storage/replica.go:3216  [n1,s1,r17/1:/Table/2{0-1}] proposing ADD_REPLICA((n3,s3):2): updated=[(n1,s1):1 (n3,s3):2] next=3
I180116 17:14:45.737210 160813 storage/replica_raftstorage.go:540  [replicate,n1,s1,r2/1:/System/{-NodeLive…}] generated preemptive snapshot ce98594a at index 17
panic: test timed out after 4m0s

goroutine 161566 [running]:
testing.startAlarm.func1()
	/usr/local/go/src/testing/testing.go:1145 +0xf9
created by time.goFunc
	/usr/local/go/src/time/sleep.go:170 +0x44

goroutine 1 [chan receive]:
testing.(*T).Run(0xc4200ae690, 0x2383686, 0x1e, 0x2440770, 0x8d5401)
	/usr/local/go/src/testing/testing.go:790 +0x2fc
testing.runTests.func1(0xc4200ae690)
	/usr/local/go/src/testing/testing.go:1004 +0x64
testing.tRunner(0xc4200ae690, 0xc420733db8)
	/usr/local/go/src/testing/testing.go:746 +0xd0
testing.runTests(0xc420457080, 0x34715c0, 0x39, 0x39, 0x0)
	/usr/local/go/src/testing/testing.go:1002 +0x2d8
testing.(*M).Run(0xc42087ff18, 0xc420016d10)
	/usr/local/go/src/testing/testing.go:921 +0x111
github.com/cockroachdb/cockroach/pkg/ccl/sqlccl.TestMain(0xc420733f18)
	/go/src/github.com/cockroachdb/cockroach/pkg/ccl/sqlccl/main_test.go:31 +0xda
main.main()
	github.com/cockroachdb/cockroach/pkg/ccl/sqlccl/_test/_testmain.go:174 +0xdb

goroutine 6 [chan receive]:
github.com/cockroachdb/cockroach/pkg/util/log.(*loggingT).flushDaemon(0x36c3120)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/log/clog.go:1043 +0x81
created by github.com/cockroachdb/cockroach/pkg/util/log.init.0
	/go/src/github.com/cockroachdb/cockroach/pkg/util/log/clog.go:581 +0xbf

goroutine 41 [syscall, 4 minutes]:
os/signal.signal_recv(0x0)
	/usr/local/go/src/runtime/sigqueue.go:131 +0xa6
os/signal.loop()
	/usr/local/go/src/os/signal/signal_unix.go:22 +0x22
created by os/signal.init.0
	/usr/local/go/src/os/signal/signal_unix.go:28 +0x41

goroutine 161286 [select]:
github.com/cockroachdb/cockroach/pkg/rpc.(*Context).runHeartbeat(0xc4214ad180, 0xc42378cb40, 0xc4203345d0, 0xf, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/pkg/rpc/context.go:550 +0x3ec
github.com/cockroachdb/cockroach/pkg/rpc.(*Context).GRPCDial.func1.1.1(0x349d220, 0xc422c20180)
	/go/src/github.com/cockroachdb/cockroach/pkg/rpc/context.go:484 +0x6b
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc4213d8730, 0xc420d4d5f0, 0xc422c20150)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:195 +0xf3
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:188 +0xad

goroutine 160780 [select]:
github.com/cockroachdb/cockroach/pkg/storage/idalloc.(*Allocator).start.func1(0x349d220, 0xc423352480)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/idalloc/id_alloc.go:138 +0x6b4
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc4203ba1a0, 0xc420e353b0, 0xc4203ba180)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:195 +0xf3
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:188 +0xad

goroutine 20 [select, locked to thread]:
runtime.gopark(0x24445b8, 0x0, 0x23596e6, 0x6, 0x18, 0x1)
	/usr/local/go/src/runtime/proc.go:277 +0x12c
runtime.selectgo(0xc42002af50, 0xc420536720)
	/usr/local/go/src/runtime/select.go:395 +0x1138
runtime.ensureSigM.func1()
	/usr/local/go/src/runtime/signal_unix.go:511 +0x220
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:2337 +0x1

goroutine 161435 [semacquire]:
sync.runtime_notifyListWait(0xc421212450, 0xc400000008)
	/usr/local/go/src/runtime/sema.go:507 +0x110
sync.(*Cond).Wait(0xc421212440)
	/usr/local/go/src/sync/cond.go:56 +0x80
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).worker(0xc423061440, 0x349d220, 0xc4212fa8a0)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:197 +0x7c
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).Start.func2(0x349d220, 0xc4212fa8a0)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:166 +0x3e
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc423076bf0, 0xc420d4d5f0, 0xc423076be0)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:195 +0xf3
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:188 +0xad

goroutine 161462 [semacquire]:
sync.runtime_notifyListWait(0xc421212450, 0xc400000027)
	/usr/local/go/src/runtime/sema.go:507 +0x110
sync.(*Cond).Wait(0xc421212440)
	/usr/local/go/src/sync/cond.go:56 +0x80
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).worker(0xc423061440, 0x349d220, 0xc4212fad20)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:197 +0x7c
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).Start.func2(0x349d220, 0xc4212fad20)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:166 +0x3e
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc423076f50, 0xc420d4d5f0, 0xc423076f40)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:195 +0xf3
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:188 +0xad

goroutine 160161 [chan receive]:
github.com/cockroachdb/cockroach/pkg/server.(*Server).Start.func6(0x349d220, 0xc420ca6000)
	/go/src/github.com/cockroachdb/cockroach/pkg/server/server.go:786 +0x7c
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc42043ef60, 0xc4230ec750, 0xc420569480)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:195 +0xf3
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:188 +0xad

goroutine 161542 [select]:
github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/transport.(*http2Server).keepalive(0xc4218b8780)
	/go/src/github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/transport/http2_server.go:956 +0x264
created by github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/transport.newHTTP2Server
	/go/src/github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/transport/http2_server.go:264 +0xf0e

goroutine 161657 [semacquire]:
sync.runtime_notifyListWait(0xc42363f5d0, 0xc40000002e)
	/usr/local/go/src/runtime/sema.go:507 +0x110
sync.(*Cond).Wait(0xc42363f5c0)
	/usr/local/go/src/sync/cond.go:56 +0x80
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).worker(0xc420bd3560, 0x349d220, 0xc4209952f0)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:197 +0x7c
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).Start.func2(0x349d220, 0xc4209952f0)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:166 +0x3e
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc42282b200, 0xc4248f8630, 0xc42282b1f0)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:195 +0xf3
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:188 +0xad

goroutine 161592 [select]:
github.com/cockroachdb/cockroach/pkg/server.(*Server).startSampleEnvironment.func1(0x349d220, 0xc420888810)
	/go/src/github.com/cockroachdb/cockroach/pkg/server/server.go:1419 +0x16c
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc424a7c9c0, 0xc4248f8630, 0xc4229e16e0)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:195 +0xf3
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:188 +0xad

goroutine 160993 [select]:
github.com/cockroachdb/cockroach/pkg/sql.(*DistSQLPlanner).initRunners.func1(0x349d220, 0xc423c687b0)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsql_running.go:86 +0x167
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc4202b7750, 0xc420e353b0, 0xc4202b7730)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:195 +0xf3
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:188 +0xad

goroutine 161430 [semacquire]:
sync.runtime_notifyListWait(0xc421212450, 0xc40000001d)
	/usr/local/go/src/runtime/sema.go:507 +0x110
sync.(*Cond).Wait(0xc421212440)
	/usr/local/go/src/sync/cond.go:56 +0x80
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).worker(0xc423061440, 0x349d220, 0xc420e31e00)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:197 +0x7c
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).Start.func2(0x349d220, 0xc420e31e00)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:166 +0x3e
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc423076b50, 0xc420d4d5f0, 0xc423076b40)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:195 +0xf3
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:188 +0xad

goroutine 161007 [select]:
github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc.(*addrConn).transportMonitor(0xc420849400)
	/go/src/github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/clientconn.go:1234 +0x25f
github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc.(*addrConn).connect.func1(0xc420849400)
	/go/src/github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/clientconn.go:837 +0x1ce
created by github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc.(*addrConn).connect
	/go/src/github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/clientconn.go:828 +0xeb

goroutine 161645 [semacquire]:
sync.runtime_notifyListWait(0xc42363f5d0, 0xc400000022)
	/usr/local/go/src/runtime/sema.go:507 +0x110
sync.(*Cond).Wait(0xc42363f5c0)
	/usr/local/go/src/sync/cond.go:56 +0x80
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).worker(0xc420bd3560, 0x349d220, 0xc420995080)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:197 +0x7c
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).Start.func2(0x349d220, 0xc420995080)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:166 +0x3e
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc42282b080, 0xc4248f8630, 0xc42282b070)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:195 +0xf3
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:188 +0xad

goroutine 160311 [select]:
github.com/cockroachdb/cockroach/pkg/storage.(*Store).Start.func2(0x349d220, 0xc420ca6c60)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/store.go:1282 +0x122
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc420385000, 0xc4230ec750, 0xc420b807a0)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:195 +0xf3
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:188 +0xad

goroutine 160812 [select]:
github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/transport.(*http2Client).keepalive(0xc421084480)
	/go/src/github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/transport/http2_client.go:1320 +0x14b
created by github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/transport.newHTTP2Client
	/go/src/github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/transport/http2_client.go:309 +0xe44

goroutine 160265 [semacquire]:
sync.runtime_notifyListWait(0xc42088ccd0, 0xc40000021f)
	/usr/local/go/src/runtime/sema.go:507 +0x110
sync.(*Cond).Wait(0xc42088ccc0)
	/usr/local/go/src/sync/cond.go:56 +0x80
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).worker(0xc4230edef0, 0x349d220, 0xc420ca6930)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:197 +0x7c
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).Start.func2(0x349d220, 0xc420ca6930)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:166 +0x3e
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc420384900, 0xc4230ec750, 0xc4203848f0)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:195 +0xf3
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:188 +0xad

goroutine 161723 [select]:
github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/transport.(*http2Server).keepalive(0xc423e28300)
	/go/src/github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/transport/http2_server.go:956 +0x264
created by github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/transport.newHTTP2Server
	/go/src/github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/transport/http2_server.go:264 +0xf0e

goroutine 160151 [select]:
github.com/cockroachdb/cockroach/pkg/security.(*CertificateManager).RegisterSignalHandler.func1(0xc4230ec750, 0xc421a14480, 0xc42108c0e0)
	/go/src/github.com/cockroachdb/cockroach/pkg/security/certificate_manager.go:125 +0x10d
created by github.com/cockroachdb/cockroach/pkg/security.(*CertificateManager).RegisterSignalHandler
	/go/src/github.com/cockroachdb/cockroach/pkg/security/certificate_manager.go:123 +0xc9

goroutine 160301 [semacquire]:
sync.runtime_notifyListWait(0xc42088ccd0, 0xc400000220)
	/usr/local/go/src/runtime/sema.go:507 +0x110
sync.(*Cond).Wait(0xc42088ccc0)
	/usr/local/go/src/sync/cond.go:56 +0x80
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).worker(0xc4230edef0, 0x349d220, 0xc421f44b10)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:197 +0x7c
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).Start.func2(0x349d220, 0xc421f44b10)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:166 +0x3e
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc420384ea0, 0xc4230ec750, 0xc420384e90)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:195 +0xf3
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:188 +0xad

goroutine 161611 [select]:
github.com/cockroachdb/cockroach/pkg/sql.(*SchemaChangeManager).Start.func1(0x349d220, 0xc4215babd0)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/schema_changer.go:1028 +0x96d
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc424a7cd10, 0xc4248f8630, 0xc4229e1740)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:195 +0xf3
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:188 +0xad

goroutine 161044 [select]:
github.com/cockroachdb/cockroach/pkg/sql/jobs.(*Registry).Start.func2(0x349d220, 0xc421016f30)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/jobs/registry.go:205 +0x13b
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc421d3bd10, 0xc420e353b0, 0xc421016c60)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:195 +0xf3
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:188 +0xad

goroutine 161729 [select]:
github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc.(*pickerWrapper).pick(0xc42333e3f0, 0x349d220, 0xc42333e4e0, 0xc421103201, 0x84c74a, 0xc423af0000, 0x0, 0xc42272ea00, 0xc423af0000)
	/go/src/github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/picker_wrapper.go:88 +0x4c3
github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc.(*ClientConn).getTransport(0xc422588f00, 0x349d220, 0xc42333e4e0, 0x349d401, 0xc4205e6460, 0x349d220, 0xc42333e4e0, 0x0, 0xc42125fb80)
	/go/src/github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/clientconn.go:893 +0x53
github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc.invoke(0x349d220, 0xc42333e4e0, 0x2380c60, 0x1d, 0x224aae0, 0xc42272ea20, 0x2229f60, 0xc42333e4b0, 0xc422588f00, 0x0, ...)
	/go/src/github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/call.go:255 +0x571
github.com/cockroachdb/cockroach/vendor/github.com/grpc-ecosystem/grpc-opentracing/go/otgrpc.OpenTracingClientInterceptor.func1(0x349d1e0, 0xc42272ea80, 0x2380c60, 0x1d, 0x224aae0, 0xc42272ea20, 0x2229f60, 0xc42333e4b0, 0xc422588f00, 0x2443a60, ...)
	/go/src/github.com/cockroachdb/cockroach/vendor/github.com/grpc-ecosystem/grpc-opentracing/go/otgrpc/client.go:44 +0xe27
github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc.(*ClientConn).Invoke(0xc422588f00, 0x349d1e0, 0xc42272ea80, 0x2380c60, 0x1d, 0x224aae0, 0xc42272ea20, 0x2229f60, 0xc42333e4b0, 0x0, ...)
	/go/src/github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/call.go:149 +0xdd
github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc.Invoke(0x349d1e0, 0xc42272ea80, 0x2380c60, 0x1d, 0x224aae0, 0xc42272ea20, 0x2229f60, 0xc42333e4b0, 0xc422588f00, 0x0, ...)
	/go/src/github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/call.go:159 +0xc1
github.com/cockroachdb/cockroach/pkg/rpc.(*heartbeatClient).Ping(0xc4205e6470, 0x349d1e0, 0xc42272ea80, 0xc42272ea20, 0x0, 0x0, 0x0, 0xc421c5f250, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/pkg/rpc/heartbeat.pb.go:125 +0xd2
github.com/cockroachdb/cockroach/pkg/rpc.(*Context).runHeartbeat(0xc42059a3c0, 0xc422f828c0, 0xc4202a6c30, 0xf, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/pkg/rpc/context.go:565 +0x4c8
github.com/cockroachdb/cockroach/pkg/rpc.(*Context).GRPCDial.func1.1.1(0x349d220, 0xc42333e480)
	/go/src/github.com/cockroachdb/cockroach/pkg/rpc/context.go:484 +0x6b
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc4213d99f0, 0xc420e353b0, 0xc42333e450)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:195 +0xf3
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:188 +0xad

goroutine 161231 [select]:
github.com/cockroachdb/cockroach/pkg/storage.(*baseQueue).processLoop.func1(0x349d220, 0xc423bb8a80)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/queue.go:514 +0x1bb
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc42282a130, 0xc420d4d5f0, 0xc4202bc460)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:195 +0xf3
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:188 +0xad

goroutine 161467 [semacquire]:
sync.runtime_notifyListWait(0xc421212450, 0xc40000001b)
	/usr/local/go/src/runtime/sema.go:507 +0x110
sync.(*Cond).Wait(0xc421212440)
	/usr/local/go/src/sync/cond.go:56 +0x80
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).worker(0xc423061440, 0x349d220, 0xc423bb8810)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:197 +0x7c
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).Start.func2(0x349d220, 0xc423bb8810)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:166 +0x3e
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc423076ff0, 0xc420d4d5f0, 0xc423076fe0)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:195 +0xf3
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:188 +0xad

goroutine 161484 [select]:
github.com/cockroachdb/cockroach/pkg/storage.(*Store).startGossip.func4(0x349d220, 0xc420e31fb0)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/store.go:1416 +0x3e9
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc4230771f0, 0xc420d4d5f0, 0xc42320b2c0)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:195 +0xf3
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:188 +0xad

goroutine 161350 [select]:
github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc.(*addrConn).transportMonitor(0xc420191680)
	/go/src/github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/clientconn.go:1234 +0x25f
github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc.(*addrConn).connect.func1(0xc420191680)
	/go/src/github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/clientconn.go:837 +0x1ce
created by github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc.(*addrConn).connect
	/go/src/github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/clientconn.go:828 +0xeb

goroutine 161722 [select]:
github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/transport.loopyWriter(0x349d220, 0xc42327f860, 0xc42327f800, 0xc423a24fb8)
	/go/src/github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/transport/transport.go:727 +0x3c6
github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/transport.newHTTP2Server.func2(0xc423e28300)
	/go/src/github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/transport/http2_server.go:261 +0x5e
created by github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/transport.newHTTP2Server
	/go/src/github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/transport/http2_server.go:260 +0xee9

goroutine 160962 [semacquire]:
sync.runtime_notifyListWait(0xc4210203d0, 0xc400000176)
	/usr/local/go/src/runtime/sema.go:507 +0x110
sync.(*Cond).Wait(0xc4210203c0)
	/usr/local/go/src/sync/cond.go:56 +0x80
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).worker(0xc420170a20, 0x349d220, 0xc423c685a0)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:197 +0x7c
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).Start.func2(0x349d220, 0xc423c685a0)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:166 +0x3e
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc4202b6e70, 0xc420e353b0, 0xc4202b6e60)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:195 +0xf3
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:188 +0xad

goroutine 161491 [select]:
github.com/cockroachdb/cockroach/pkg/storage.(*baseQueue).processLoop.func1(0x349d220, 0xc423bb8ab0)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/queue.go:514 +0x1bb
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc42282a170, 0xc420d4d5f0, 0xc4202bc4e0)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:195 +0xf3
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:188 +0xad

goroutine 160157 [chan receive]:
github.com/cockroachdb/cockroach/pkg/server.(*Server).Start.func2(0x349d220, 0xc421f440c0)
	/go/src/github.com/cockroachdb/cockroach/pkg/server/server.go:751 +0x53
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc42043ef20, 0xc4230ec750, 0xc420e80940)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:195 +0xf3
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:188 +0xad

goroutine 161756 [IO wait]:
internal/poll.runtime_pollWait(0x7fdafadf9b80, 0x72, 0x0)
	/usr/local/go/src/runtime/netpoll.go:173 +0x57
internal/poll.(*pollDesc).wait(0xc421c76818, 0x72, 0xffffffffffffff00, 0x3486b60, 0x3479918)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:85 +0xae
internal/poll.(*pollDesc).waitRead(0xc421c76818, 0xc423228c00, 0x400, 0x400)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:90 +0x3d
internal/poll.(*FD).Read(0xc421c76800, 0xc423228c00, 0x400, 0x400, 0x0, 0x0, 0x0)
	/usr/local/go/src/internal/poll/fd_unix.go:125 +0x18a
net.(*netFD).Read(0xc421c76800, 0xc423228c00, 0x400, 0x400, 0x0, 0xc423228c00, 0x0)
	/usr/local/go/src/net/fd_unix.go:202 +0x52
net.(*conn).Read(0xc42000e528, 0xc423228c00, 0x400, 0x400, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/net.go:176 +0x6d
crypto/tls.(*block).readFromUntil(0xc423ee2de0, 0x7fdafdf0d350, 0xc42000e528, 0x5, 0xc42000e528, 0x93)
	/usr/local/go/src/crypto/tls/conn.go:488 +0x95
crypto/tls.(*Conn).readRecord(0xc4219b8e00, 0xc420022c16, 0x400, 0x93)
	/usr/local/go/src/crypto/tls/conn.go:590 +0xe0
crypto/tls.(*Conn).readHandshake(0xc4219b8e00, 0xc4208d0616, 0xc4208d06c0, 0x8e, 0x8e)
	/usr/local/go/src/crypto/tls/conn.go:943 +0x8d
crypto/tls.(*Conn).clientHandshake(0xc4219b8e00, 0x24446e0, 0xc4219b8f20)
	/usr/local/go/src/crypto/tls/handshake_client.go:159 +0x9ca
crypto/tls.(*Conn).Handshake(0xc4219b8e00, 0x0, 0x0)
	/usr/local/go/src/crypto/tls/conn.go:1307 +0x18f
github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/credentials.(*tlsCreds).ClientHandshake.func1(0xc4221a9500, 0xc4219b8e00)
	/go/src/github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/credentials/credentials.go:147 +0x2b
created by github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/credentials.(*tlsCreds).ClientHandshake
	/go/src/github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/credentials/credentials.go:146 +0x118

goroutine 161003 [select]:
github.com/cockroachdb/cockroach/pkg/storage.(*baseQueue).processLoop.func1(0x349d220, 0xc421400f30)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/queue.go:514 +0x1bb
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc420045d20, 0xc420e353b0, 0xc4203de3c0)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:195 +0xf3
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:188 +0xad

goroutine 160120 [select]:
github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc.(*addrConn).transportMonitor(0xc42209cc80)
	/go/src/github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/clientconn.go:1234 +0x25f
github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc.(*addrConn).connect.func1(0xc42209cc80)
	/go/src/github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/clientconn.go:837 +0x1ce
created by github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc.(*addrConn).connect
	/go/src/github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/clientconn.go:828 +0xeb

goroutine 160721 [semacquire]:
sync.runtime_notifyListWait(0xc4210203d0, 0xc400000144)
	/usr/local/go/src/runtime/sema.go:507 +0x110
sync.(*Cond).Wait(0xc4210203c0)
	/usr/local/go/src/sync/cond.go:56 +0x80
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).worker(0xc420170a20, 0x349d220, 0xc4214009c0)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:197 +0x7c
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).Start.func2(0x349d220, 0xc4214009c0)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:166 +0x3e
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc4202b66a0, 0xc420e353b0, 0xc4202b6690)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:195 +0xf3
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:188 +0xad

goroutine 161403 [select]:
github.com/cockroachdb/cockroach/pkg/sql.(*DistSQLPlanner).initRunners.func1(0x349d220, 0xc421514330)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsql_running.go:86 +0x167
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc424a7c7f0, 0xc420d4d5f0, 0xc424a7c7e0)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:195 +0xf3
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:188 +0xad

goroutine 161247 [select]:
github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc.(*ccBalancerWrapper).watcher(0xc424180080)
	/go/src/github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/balancer_conn_wrappers.go:122 +0x156
created by github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc.newCCBalancerWrapper
	/go/src/github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/balancer_conn_wrappers.go:113 +0x197

goroutine 161647 [semacquire]:
sync.runtime_notifyListWait(0xc42363f5d0, 0xc400000024)
	/usr/local/go/src/runtime/sema.go:507 +0x110
sync.(*Cond).Wait(0xc42363f5c0)
	/usr/local/go/src/sync/cond.go:56 +0x80
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).worker(0xc420bd3560, 0x349d220, 0xc4209950e0)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:197 +0x7c
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).Start.func2(0x349d220, 0xc4209950e0)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:166 +0x3e
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc42282b0c0, 0xc4248f8630, 0xc42282b0b0)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:195 +0xf3
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:188 +0xad

goroutine 161620 [semacquire]:
sync.runtime_notifyListWait(0xc42363f5d0, 0xc400000009)
	/usr/local/go/src/runtime/sema.go:507 +0x110
sync.(*Cond).Wait(0xc42363f5c0)
	/usr/local/go/src/sync/cond.go:56 +0x80
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).worker(0xc420bd3560, 0x349d220, 0xc420994b40)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:197 +0x7c
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).Start.func2(0x349d220, 0xc420994b40)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:166 +0x3e
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc42282ad60, 0xc4248f8630, 0xc42282ad50)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:195 +0xf3
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:188 +0xad

goroutine 161689 [select]:
github.com/cockroachdb/cockroach/pkg/storage.(*baseQueue).processLoop.func1(0x349d220, 0xc420995980)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/queue.go:514 +0x1bb
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc42282b650, 0xc4248f8630, 0xc421aa68a0)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:195 +0xf3
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:188 +0xad

goroutine 161014 [select]:
github.com/cockroachdb/cockroach/pkg/sql.(*DistSQLPlanner).initRunners.func1(0x349d220, 0xc421fd81b0)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsql_running.go:86 +0x167
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc4202b7870, 0xc420e353b0, 0xc4202b7860)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:195 +0xf3
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:188 +0xad

goroutine 161349 [select]:
github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc.(*ccBalancerWrapper).watcher(0xc4228b2040)
	/go/src/github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/balancer_conn_wrappers.go:122 +0x156
created by github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc.newCCBalancerWrapper
	/go/src/github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/balancer_conn_wrappers.go:113 +0x197

goroutine 161454 [semacquire]:
sync.runtime_notifyListWait(0xc421212450, 0xc400000030)
	/usr/local/go/src/runtime/sema.go:507 +0x110
sync.(*Cond).Wait(0xc421212440)
	/usr/local/go/src/sync/cond.go:56 +0x80
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).worker(0xc423061440, 0x349d220, 0xc420e31f50)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:197 +0x7c
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).Start.func2(0x349d220, 0xc420e31f50)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:166 +0x3e
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc423076e50, 0xc420d4d5f0, 0xc423076e40)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:195 +0xf3
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:188 +0xad

goroutine 161477 [semacquire]:
sync.runtime_notifyListWait(0xc421212450, 0xc40000003e)
	/usr/local/go/src/runtime/sema.go:507 +0x110
sync.(*Cond).Wait(0xc421212440)
	/usr/local/go/src/sync/cond.go:56 +0x80
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).worker(0xc423061440, 0x349d220, 0xc4212faf00)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:197 +0x7c
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).Start.func2(0x349d220, 0xc4212faf00)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:166 +0x3e
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc423077130, 0xc420d4d5f0, 0xc423077120)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:195 +0xf3
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:188 +0xad

goroutine 161517 [chan receive]:
github.com/cockroachdb/cockroach/vendor/github.com/cockroachdb/cmux.muxListener.Accept(...)
	/go/src/github.com/cockroachdb/cockroach/vendor/github.com/cockroachdb/cmux/cmux.go:184
github.com/cockroachdb/cockroach/vendor/github.com/cockroachdb/cmux.(*muxListener).Accept(0xc4224d6460, 0xc423102db0, 0xc424f89680, 0x96d9ca, 0x22506c0)
	<autogenerated>:1 +0x65
crypto/tls.(*listener).Accept(0xc4224d64a0, 0xc420016108, 0x20cf040, 0x34537a0, 0x23213a0)
	/usr/local/go/src/crypto/tls/tls.go:52 +0x37
net/http.(*Server).Serve(0xc4240468f0, 0x348e120, 0xc4224d64a0, 0x0, 0x0)
	/usr/local/go/src/net/http/server.go:2695 +0x1b2
github.com/cockroachdb/cockroach/pkg/server.(*Server).Start.func5(0x349d220, 0xc423102d50)
	/go/src/github.com/cockroachdb/cockroach/pkg/server/server.go:782 +0x42
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc4213d8d30, 0xc4248f8630, 0xc4224d64c0)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:195 +0xf3
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:188 +0xad

goroutine 160910 [select]:
github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/transport.loopyWriter(0x349d160, 0xc422f30700, 0xc421caad20, 0xc42119efb8)
	/go/src/github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/transport/transport.go:727 +0x3c6
github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/transport.newHTTP2Client.func3(0xc420a18000)
	/go/src/github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/transport/http2_client.go:305 +0x5e
created by github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/transport.newHTTP2Client
	/go/src/github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/transport/http2_client.go:304 +0xdc4

goroutine 160909 [semacquire]:
sync.runtime_notifyListWait(0xc4204aa040, 0xc400000004)
	/usr/local/go/src/runtime/sema.go:507 +0x110
sync.(*Cond).Wait(0xc4204aa030)
	/usr/local/go/src/sync/cond.go:56 +0x80
io.(*pipe).read(0xc4204aa000, 0xc420652400, 0x400, 0x400, 0x0, 0x0, 0x0)
	/usr/local/go/src/io/pipe.go:47 +0xc6
io.(*PipeReader).Read(0xc42000e060, 0xc420652400, 0x400, 0x400, 0x0, 0x0, 0x0)
	/usr/local/go/src/io/pipe.go:130 +0x4c
crypto/tls.(*block).readFromUntil(0xc421400690, 0x7fdafdf0d0a0, 0xc4202b61e0, 0x5, 0xc4202b61e0, 0x0)
	/usr/local/go/src/crypto/tls/conn.go:488 +0x95
crypto/tls.(*Conn).readRecord(0xc421c78000, 0x2444617, 0xc421c78120, 0x0)
	/usr/local/go/src/crypto/tls/conn.go:590 +0xe0
crypto/tls.(*Conn).Read(0xc421c78000, 0xc42306c000, 0x8000, 0x8000, 0x0, 0x0, 0x0)
	/usr/local/go/src/crypto/tls/conn.go:1134 +0x110
bufio.(*Reader).Read(0xc422818c60, 0xc42439c038, 0x9, 0x9, 0x28, 0x2222240, 0x0)
	/usr/local/go/src/bufio/bufio.go:213 +0x30b
io.ReadAtLeast(0x347b7e0, 0xc422818c60, 0xc42439c038, 0x9, 0x9, 0x9, 0xc42119dd60, 0x84788e, 0xc42119de0f)
	/usr/local/go/src/io/io.go:309 +0x86
io.ReadFull(0x347b7e0, 0xc422818c60, 0xc42439c038, 0x9, 0x9, 0xd0e364, 0xc421caae10, 0xc421ca0004)
	/usr/local/go/src/io/io.go:327 +0x58
github.com/cockroachdb/cockroach/vendor/golang.org/x/net/http2.readFrameHeader(0xc42439c038, 0x9, 0x9, 0x347b7e0, 0xc422818c60, 0x0, 0x0, 0xc421caae10, 0x0)
	/go/src/github.com/cockroachdb/cockroach/vendor/golang.org/x/net/http2/frame.go:237 +0x7b
github.com/cockroachdb/cockroach/vendor/golang.org/x/net/http2.(*Framer).ReadFrame(0xc42439c000, 0xc421caae10, 0xc421caae10, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/vendor/golang.org/x/net/http2/frame.go:492 +0xa4
github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/transport.(*http2Server).HandleStreams(0xc4219aac00, 0xc421caade0, 0x24439a8)
	/go/src/github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/transport/http2_server.go:395 +0x3a
github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc.(*Server).serveStreams(0xc4205c06e0, 0x34a8660, 0xc4219aac00)
	/go/src/github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/server.go:634 +0xf2
github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc.(*Server).handleRawConn.func2()
	/go/src/github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/server.go:591 +0x3c
github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc.(*Server).handleRawConn.func3(0xc422792a00, 0xc4205c06e0, 0x7fdafdf66650, 0xc4219aac00)
	/go/src/github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/server.go:599 +0x27
created by github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc.(*Server).handleRawConn
	/go/src/github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/server.go:598 +0x656

goroutine 161432 [semacquire]:
sync.runtime_notifyListWait(0xc421212450, 0xc400000023)
	/usr/local/go/src/runtime/sema.go:507 +0x110
sync.(*Cond).Wait(0xc421212440)
	/usr/local/go/src/sync/cond.go:56 +0x80
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).worker(0xc423061440, 0x349d220, 0xc420e31e60)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:197 +0x7c
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).Start.func2(0x349d220, 0xc420e31e60)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:166 +0x3e
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc423076b90, 0xc420d4d5f0, 0xc423076b80)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:195 +0xf3
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:188 +0xad

goroutine 160324 [select]:
github.com/cockroachdb/cockroach/pkg/storage.(*baseQueue).processLoop.func1(0x349d220, 0xc420ca6d50)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/queue.go:514 +0x1bb
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc42048d790, 0xc4230ec750, 0xc4238a4380)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:195 +0xf3
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:188 +0xad

goroutine 160287 [semacquire]:
sync.runtime_notifyListWait(0xc42088ccd0, 0xc4000001f3)
	/usr/local/go/src/runtime/sema.go:507 +0x110
sync.(*Cond).Wait(0xc42088ccc0)
	/usr/local/go/src/sync/cond.go:56 +0x80
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).worker(0xc4230edef0, 0x349d220, 0xc420a4a4b0)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:197 +0x7c
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).Start.func2(0x349d220, 0xc420a4a4b0)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:166 +0x3e
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc420384c20, 0xc4230ec750, 0xc420384c10)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:195 +0xf3
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:188 +0xad

goroutine 160387 [select]:
github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/transport.loopyWriter(0x349d160, 0xc4220a83c0, 0xc4214008a0, 0xc42188dfb8)
	/go/src/github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/transport/transport.go:727 +0x3c6
github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/transport.newHTTP2Client.func3(0xc422184000)
	/go/src/github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/transport/http2_client.go:305 +0x5e
created by github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/transport.newHTTP2Client
	/go/src/github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/transport/http2_client.go:304 +0xdc4

goroutine 161332 [chan receive]:
github.com/cockroachdb/cockroach/pkg/util/netutil.MakeServer.func2(0x349d220, 0xc420b081b0)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/netutil/net.go:100 +0x64
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc4230b06c0, 0xc420d4d5f0, 0xc420ef6820)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:195 +0xf3
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:188 +0xad

goroutine 161600 [select]:
github.com/cockroachdb/cockroach/pkg/sql.(*DistSQLPlanner).initRunners.func1(0x349d220, 0xc4215ba8d0)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsql_running.go:86 +0x167
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc424a7cb50, 0xc4248f8630, 0xc424a7cb40)
	/go/src/github
```

Please assign, take a look and update the issue accordingly.

### PR DESCRIPTION
**Pull request by benesch**
Turning the ScanInterval way down shaves a minute or two off their
runtime.

Closes #21223.
Closes #21235.
Closes #21340.
Closes #21329.
Closes #21409.
Closes #21423.
Closes #21471.
Closes #21474.

Release note: None

### CODE REVIEW

File: pkg/ccl/sqlccl/partition_test.go [hunk 1]
```diff
@@ -1084,12 +1080,30 @@ func TestInitialPartitioning(t *testing.T) {
...
 	}}
 	tc := testcluster.StartTestCluster(t, 3, tcArgs)
-	defer tc.Stopper().Stop(context.Background())
+
 	sqlDB := sqlutils.MakeSQLRunner(tc.Conns[0])
 	sqlDB.Exec(t, `CREATE DATABASE data`)
 	sqlDB.Exec(t, `USE data`)
 
+	// Disabling store throttling vastly speeds up rebalancing.
+	sqlDB.Exec(t, `SET CLUSTER SETTING server.declined_reservation_timeout = '0s'`)
```
Comment (dt) [inline pkg/ccl/sqlccl/partition_test.go]: Hm.. can you just override directly via the *Settings in the testserverargs? IIRC these gossiped updates sometimes flake since you can't wait for them to propagate.

Comment (tschottdorf) [reply pkg/ccl/sqlccl/partition_test.go]: Overriding directly isn't a good idea as you can get that updated wiped out by Gossip updates. I think this is fine (or rather, I'll take my chances). Especially for this one it shouldn't cause a problem if it flakes? The test will take a little longer for the initial snapshots, but not for all of them.

**Review by tbg — APPROVED** [review]

File: pkg/ccl/sqlccl/partition_test.go (hunk 1 above)
Comment (dt) [reply pkg/ccl/sqlccl/partition_test.go]: 👍

**Comment by benesch** [comment]
Looks like setting the ScanInterval to 1ms can starve out other stress instances. Sigh. Hopefully 100ms is a good middle ground.

**Comment by tschottdorf** [comment]
I looked into your acceptance flake. Looks like one node just isn't becoming live again after and in fact the cluster looks completely hosed (liveness problems, etc). Perhaps there is a race in which we restart nodes faster than their ports are propagated (so that eventually there's a disconnect)? I didn't think so, but something has to be causing this.

**Comment by tschottdorf** [comment]
(Either way, nothing that should block this PR)

**Comment by benesch** [comment]
Oh, heh, I didn't even notice that acceptance test failure. A 100ms scan interval seems to have done the trick, so merging on green!

**Comment by benesch** [comment]
Thanks for the reviews, folks!
