### PR TITLE
server: add EngineStats endpoint in multitenant setup

### LINKED ISSUE #110020: server: the "enginestats" status API endpoint should work with secondary tenants with sufficient capability
Found while investigating #110001.

**Describe the problem**

When `TestStatusEngineStatsJson` in `server/storage_api` is modified to point to a secondary tenant (e.g. via #110008), the test starts failing when accessing the `/_status/enginestats` endpoint:

```
    engine_test.go:51: condition failed to evaluate within 45s: from http.go:190: status: 501 Not Implemented, content-type: application/json, body: {
          "error": "method EngineStats not implemented",
          "code": 12,
          "message": "method EngineStats not implemented",
          "details": [
          ]
        }, error: <nil>
```

**How to reproduce**

from #110008 reset `DefaultTestTenant` in `TestStatusEngineStatsJson`, run the test with a test tenant and observe the failure.

**Expected behavior**

Once the tenant is granted a suitable capability, the endpoint should work properly. It should retrieve the engine stats over the KV tenant connector over the network.

Epic CRDB-38968

Jira issue: CRDB-31226

### PR DESCRIPTION
**Pull request by shaikzakiriitm**
EngineStats endpoint was inaccessible from secondary tenant.

EngineStats endpoint provides statistics of storage layer which can help diagnose myriad of issues critical to database performance.
To address this, we created EngineStatus endpoint in tenant status server. Implementation uses tenant connector to redirect call to system status server on requested kv node. Access to this endpoint is guarded by `can_view_node_info` capability as this endpoint returns info of all stores on a given node. Updated corresponding unit tests.

Epic: CRDB-38968
Fixes: #110020

Release note: None

### CODE REVIEW

File: pkg/server/storage_api/engine_test.go [hunk 1]
```diff
@@ -19,25 +20,36 @@ import (
...
 		StoreSpecs: []base.StoreSpec{{
 			Path: dir,
 		}},
 	})
-	defer srv.Stopper().Stop(context.Background())
+	defer srv.Stopper().Stop(ctx)
+
+	if srv.DeploymentMode().IsExternal() {
+		// explicitly enabling CanViewNodeInfo capability for the secondary/application tenant
+		// when in external process mode, as shared process mode already has all capabilities.
```
Comment (shubhamdhama) [inline pkg/server/storage_api/engine_test.go:47]: Please fix the first letter of the first word of sentence to uppercase. 

Suggestion: I think at this point we don't need these two lines of comment, it's sort of a common knowledge I guess.

File: pkg/server/storage_api/engine_test.go [hunk 2]
```diff
@@ -19,25 +20,36 @@ import (
...
 	defer leaktest.AfterTest(t)()
 	defer log.Scope(t).Close(t)
+	ctx := context.Background()
 
 	dir, cleanupFn := testutils.TempDir(t)
 	defer cleanupFn()
 
 	srv := serverutils.StartServerOnly(t, base.TestServerArgs{
-		DefaultTestTenant: base.TestIsForStuffThatShouldWorkWithSecondaryTenantsButDoesntYet(110020),
+		DefaultTestTenant: base.TestTenantProbabilisticOnly,
```
Comment (shubhamdhama) [inline pkg/server/storage_api/engine_test.go:37]: You can remove this line and just go for the default.

File: pkg/server/storage_api/engine_test.go [hunk 3]
```diff
@@ -57,3 +69,26 @@ func TestStatusEngineStatsJson(t *testing.T) {
...
+	})
+	defer srv.Stopper().Stop(context.Background())
+
+	s := srv.ApplicationLayer()
+
+	var engineStats serverpb.EngineStatsResponse
+	testutils.SucceedsSoon(t, func() error {
+		actualErr := srvtestutils.GetStatusJSONProto(s, "enginestats/local", &engineStats)
+		require.Error(t, actualErr)
+		require.Contains(t, actualErr.Error(), "client tenant does not have capability to query cluster node metadata")
```
Comment (shubhamdhama) [inline pkg/server/storage_api/engine_test.go:90]: Say this callback runs for the first time—the request is expected to error, so require.Error would be fine. But if the error message doesn’t contain what you’re checking for (which I assume is why we’re using .SucceedsSoon), then require.Contains will fail the test right away and won’t retry.

To fix that, instead of using require here, just check with an if and return an error if it doesn’t match. That way .SucceedsSoon can keep retrying like it’s supposed to.

**Review by shubhamdhama — CHANGES_REQUESTED** [review]
I've left some minor comments above. The rest of the PR looks good to me.

File: pkg/rpc/auth_tenant.go [hunk 4]
```diff
@@ -124,6 +124,9 @@ func (a tenantAuthorizer) authorize(
 	case "/cockroach.server.serverpb.Status/Gossip":
 		return a.capabilitiesAuthorizer.HasNodeStatusCapability(ctx, tenID)
 
+	case "/cockroach.server.serverpb.Status/EngineStats":
```
Comment (cthumuluru-crdb) [inline pkg/rpc/auth_tenant.go:127]: nit: Maybe change this to `case "/cockroach.server.serverpb.Status/Gossip", "/cockroach.server.serverpb.Status/EngineStats": `

File: pkg/server/storage_api/engine_test.go [hunk 5]
```diff
@@ -57,3 +67,26 @@ func TestStatusEngineStatsJson(t *testing.T) {
...
+	srv := serverutils.StartServerOnly(t, base.TestServerArgs{
+		// Note: We're only testing external-process mode because shared service
+		// mode tenants have all capabilities.
+		DefaultTestTenant: base.ExternalTestTenantAlwaysEnabled,
+	})
+	defer srv.Stopper().Stop(context.Background())
+
+	s := srv.ApplicationLayer()
+
+	var engineStats serverpb.EngineStatsResponse
```
Comment (cthumuluru-crdb) [inline pkg/server/storage_api/engine_test.go:84]: I don't really follow why we have to use a retry look here?

File: pkg/server/storage_api/engine_test.go (hunk 3 above)
Comment (cthumuluru-crdb) [reply pkg/server/storage_api/engine_test.go:88]: +1. Please fix this.

**Review by cthumuluru-crdb — CHANGES_REQUESTED** [review]
Left a couple of comments. Otherwise it looks good.

**Review by cthumuluru-crdb — CHANGES_REQUESTED** [review]
Left a couple of comments. Otherwise it looks good.

File: pkg/server/storage_api/engine_test.go (hunk 3 above)
Comment (shubhamdhama) [reply pkg/server/storage_api/engine_test.go:88]: @shaikzakiriitm I mean something like this,
```
@@ -57,3 +67,26 @@ func TestStatusEngineStatsJson(t *testing.T) {
[57,67] 		t.Fatal(errors.Errorf("expected engine metrics to be correctly formatted, got:\n %s", formattedStats))
[58,68] 	}
[59,69] }
[59,70]+
[59,71]+func TestStatusEngineStatsJsonWithoutTenantCapability(t *testing.T) {
[59,72]+	defer leaktest.AfterTest(t)()
[59,73]+	defer log.Scope(t).Close(t)
[59,74]+
[59,75]+	srv := serverutils.StartServerOnly(t, base.TestServerArgs{
[59,76]+		// Note: We're only testing external-process mode because shared service
[59,77]+		// mode tenants have all capabilities.
[59,78]+		DefaultTestTenant: base.ExternalTestTenantAlwaysEnabled,
[59,79]+	})
[59,80]+	defer srv.Stopper().Stop(context.Background())
[59,81]+
[59,82]+	s := srv.ApplicationLayer()
[59,83]+
[59,84]+	var engineStats serverpb.EngineStatsResponse
[59,85]+	testutils.SucceedsSoon(t, func() error {
[59,86]+		actualErr := srvtestutils.GetStatusJSONProto(s, "enginestats/local", &engineStats)
[59,87]+		if actualErr == nil {
[59,88]+			return errors.New("expected an error but got none")
[59,89]+		}
[59,90]+		if !strings.Contains(actualErr.Error(), "client tenant does not have capability to query cluster node metadata") {
[59,91]+			return errors.New("unexpected error message: " + actualErr.Error())
[59,92]+		}
[59,93]+		return nil
[59,94]+	})
[59,95]+}
```

(generated by feeding my review comment to copilot here in this UI interface)

File: pkg/server/storage_api/engine_test.go (hunk 5 above)
Comment (shaikzakiriitm) [reply pkg/server/storage_api/engine_test.go:84]: As discussed offline, have added the comments from the other test in this file, giving some context around why `testutils.SucceedsSoon` is used.

File: pkg/server/storage_api/engine_test.go [hunk 6]
```diff
@@ -57,3 +68,33 @@ func TestStatusEngineStatsJson(t *testing.T) {
...
+	// Using SucceedsSoon because we have seen in the wild that
+	// occasionally requests don't go through with error "transport:
+	// error while dialing: connection interrupted (did the remote node
+	// shut down or are there networking issues?)"
+	testutils.SucceedsSoon(t, func() error {
+		actualErr := srvtestutils.GetStatusJSONProto(s, "enginestats/local", &engineStats)
+		// if actual err is nil, then we have a problem.
+		require.Error(t, actualErr) // this line ensures we got an error
```
Comment (shubhamdhama) [inline pkg/server/storage_api/engine_test.go:93]: nit: The comments on these two lines are not needed.

**Review by shubhamdhama — APPROVED** [review]
LGTM!

File: pkg/server/storage_api/engine_test.go (hunk 6 above)
Comment (shaikzakiriitm) [reply pkg/server/storage_api/engine_test.go]: fixed, thanks!

**Comment by shaikzakiriitm** [comment]
bors r=shubhamdhama,cthumuluru-crdb

**Review by cthumuluru-crdb — APPROVED** [review]
LGTM. Thank you!

**Comment by shaikzakiriitm** [comment]
bors r=shubhamdhama,cthumuluru-crdb
