### PR TITLE
roachtest: deflake `admission-control/multitenant-fairness`

### LINKED ISSUE #127107: roachtest: admission-control/multitenant-fairness/write-heavy/skewed failed
roachtest.admission-control/multitenant-fairness/write-heavy/skewed [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestWeeklyBazel/16058353?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestWeeklyBazel/16058353?buildTab=artifacts#/admission-control/multitenant-fairness/write-heavy/skewed) on master @ [dc3ebba01015d2c7275aa27af2a54fe88b87e901](https://github.com/cockroachdb/cockroach/commits/dc3ebba01015d2c7275aa27af2a54fe88b87e901):

```
(assertions.go:363).Fail: 
	Error Trace:	github.com/cockroachdb/cockroach/pkg/cmd/roachtest/tests/admission_control_multitenant_fairness.go:310
	            				github.com/cockroachdb/cockroach/pkg/cmd/roachtest/tests/admission_control_multitenant_fairness.go:103
	            				main/pkg/cmd/roachtest/test_runner.go:1248
	            				src/runtime/asm_amd64.s:1695
	Error:      	Received unexpected error:
	            	pq: internal error while retrieving user account memberships: operation "get-user-session" timed out after 10.001s (given timeout 10s): internal error while retrieving user account: get default settings error: interrupted during singleflight load-value:defaultsettings-roachprod-100-1: context deadline exceeded
	Test:       	admission-control/multitenant-fairness/write-heavy/skewed
(require.go:1357).NoError: FailNow called
test artifacts and logs in: /artifacts/admission-control/multitenant-fairness/write-heavy/skewed/run_1
```

Parameters:
 - <code>ROACHTEST_arch=amd64</code>
 - <code>ROACHTEST_cloud=gce</code>
 - <code>ROACHTEST_coverageBuild=false</code>
 - <code>ROACHTEST_cpu=4</code>
 - <code>ROACHTEST_encrypted=false</code>
 - <code>ROACHTEST_fs=ext4</code>
 - <code>ROACHTEST_localSSD=true</code>
 - <code>ROACHTEST_metamorphicBuild=false</code>
 - <code>ROACHTEST_ssd=0</code>
<details><summary>Help</summary>
<p>

See: [roachtest README](https://github.com/cockroachdb/cockroach/blob/master/pkg/cmd/roachtest/README.md)

See: [How To Investigate \(internal\)](https://cockroachlabs.atlassian.net/l/c/SSSBr8c7)

See: [Grafana](https://go.crdb.dev/roachtest-grafana/teamcity-16058353/admission-control-multitenant-fairness-write-heavy-skewed/1720850119494/1720851705747)

</p>
</details>
/cc @cockroachdb/storage
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*admission-control/multitenant-fairness/write-heavy/skewed.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/bazci/githubpost/issues)
</sub>

Jira issue: CRDB-40272

### PR DESCRIPTION
**Pull request by aadityasondhi**
Fixes #127107.

Release note: None

### CODE REVIEW

File: pkg/cmd/roachtest/tests/admission_control_multitenant_fairness.go [hunk 1]
```diff
@@ -307,6 +307,10 @@ func runMultiTenantFairness(
 		defer vcdb.Close()
 
 		_, err := vcdb.ExecContext(ctx, "USE kv")
+		// Retry once, since this can fail sometimes due the cluster running hot.
+		if err != nil {
+			vcdb.ExecContext(ctx, "USE kv")
```
Comment (itsbilal) [inline pkg/cmd/roachtest/tests/admission_control_multitenant_fairness.go:312]: Linter complaining about unchecked error

**Review by itsbilal — APPROVED** [review]
LGTM save for CI failure

**Comment by aadityasondhi** [comment]
TFTR.

bors r=itsbilal
