### PR TITLE
backupccl: issue protected timestamps during on restore spans

### LINKED ISSUE #91148: backupccl: issue protected timestamp for restore spans
Currently, we don't issue a protected timestamp over spans we're about to restore, which at the surface, does not seem like an issue, as restore doesn't overwrite existing keys. The lack of a PTS can cause the restore to fail, however, if the span we're restoring into has a very low gc ttl, like say 5 minutes. Specifically, if an AddSSTable request takes longer than the gc ttl, then its batch request timestamp may be earlier than the replica's gc threshold, causing the AddSStable to fail. 

We can prevent this failure by preventing the gc threshold from advancing in replicas where the restore is occuring. To do this, a pts should be issued over the whole restore span, before any restore flow begins. 

Note that the addsstable request can't merely be retried at a higher batch request TS, as all the keys in the SST have timestamps written at the batch request timestamp. Bumping the batchTS would require rewriting the SST, which seems quite expensive. 

Jira issue: CRDB-21123

### PR DESCRIPTION
**Pull request by msbutler**
Fixes #91148

Release note: None

### CODE REVIEW

File: pkg/ccl/backupccl/testdata/backup-restore/restore-protect-spans [hunk 1]
```diff
@@ -0,0 +1,55 @@
...
+SET CLUSTER SETTING jobs.debug.pausepoints = 'restore.before_flow';
+----
+
+restore expect-pausepoint tag=a
+RESTORE TABLE foo FROM LATEST IN 'nodelocal://1/full_cluster_backup/' WITH into_db='defaultdb';
+----
+job paused at pausepoint
+
+# ensure foo has adopted the ttl
+sleep ms=5000
```
Comment (msbutler) [inline pkg/ccl/backupccl/testdata/backup-restore/restore-protect-spans:41]: When I manually conduct the test in demo, the ttl was reconciled to the restored table, so i’m unsure why this job succeeds.

File: pkg/ccl/backupccl/testdata/backup-restore/restore-protect-spans [hunk 2]
```diff
@@ -0,0 +1,55 @@
+
+# tickle the unprotected timestamp bug
```
Comment (msbutler) [inline pkg/ccl/backupccl/testdata/backup-restore/restore-protect-spans:2]: this test is an attempt to tickle the original bug we observed in that big restore. in this commit, the PTS protection step in the restore job is commented out, so I'd expect the bug to get tickled. But maybe i'm not toggling the right cluster settings?

File: pkg/ccl/backupccl/testdata/backup-restore/restore-protect-spans (hunk 1 above)
Comment (stevendanna) [reply pkg/ccl/backupccl/testdata/backup-restore/restore-protect-spans:41]: Random thoughts:

- You could move the sleep to before the restore and then add a step here which prints out the span configurations, just to make sure the gc.ttl has been reconciled. 

- Does the error require that GC has actually run on the relevant ranges? Perhaps that isn't happening in this test?

File: pkg/ccl/backupccl/restore_job.go [hunk 3]
```diff
@@ -1689,7 +1742,9 @@ func (r *restoreResumer) doResume(ctx context.Context, execCtx interface{}) erro
 			return err
 		}
 	}
-
+	if err := r.execCfg.ProtectedTimestampManager.Unprotect(ctx, r.job.ID()); err != nil {
+		return err
```
Comment (stevendanna) [inline pkg/ccl/backupccl/restore_job.go:1746]: What happens to the restore if this fails?

File: pkg/ccl/backupccl/testdata/backup-restore/restore-protect-spans (hunk 1 above)
Comment (stevendanna) [reply pkg/ccl/backupccl/testdata/backup-restore/restore-protect-spans:41]: It could also be the pts cache timing: `SET CLUSTER SETTING kv.protectedts.poll_interval = '1s'`

Comment (adityamaru) [reply pkg/ccl/backupccl/testdata/backup-restore/restore-protect-spans:41]: Yeah just to second steven's comments I think this test will be better suited as a non-DD test that uses some of the utility methods in `utils_test.go`. Such as `waitForReplicaFieldToBeSet` where you can wait for the replica to have the spanconfig you expect it to have. `TestExcludeDataFromBackupDoesNotHoldupGC` is an example where this util is used.

Comment (msbutler) [reply pkg/ccl/backupccl/testdata/backup-restore/restore-protect-spans:41]: ah, yeah. that was my initial strategy, but a some of those unfamiliar utils were not quite working on the offline table. I'll take a closer look today and try to modify them to read directly from the system tables.

Comment (msbutler) [reply pkg/ccl/backupccl/testdata/backup-restore/restore-protect-spans:41]: After thinking more about this, I’ve realized the original bug is quite challenging to repro in a unit test. If we do indeed trust the PTS system, is it sufficient to merely check that  during restore, we properly add a PTS and clean it up after the restore is done?

  To directly repro the bug, we need to induce and complete a gc job on a range processing a really slow addstable request. But does this repro really add more coverage? I think we can trust that the PTS system will prevent the gc threshold from advancing on the range.

Comment (msbutler) [reply pkg/ccl/backupccl/testdata/backup-restore/restore-protect-spans:50]: see example of the alternative approach in `TestProtectRestoreSpans`

File: pkg/ccl/backupccl/backup_test.go [hunk 4]
```diff
@@ -9269,6 +9270,43 @@ func TestExcludeDataFromBackupDoesNotHoldupGC(t *testing.T) {
...
+	sqlDB.Exec(t, `SET CLUSTER SETTING jobs.debug.pausepoints = 'restore.before_flow'`)
+	var jobId jobspb.JobID
+	sqlDB.QueryRow(t, `RESTORE DATABASE data FROM LATEST IN $1 WITH detached, new_db_name=data2`, localFoo).Scan(&jobId)
+	jobutils.WaitForJobToPause(t, sqlDB, jobId)
+
+	restoreDetails := jobutils.GetJobPayload(t, sqlDB, jobId).GetRestore()
+	require.NotNil(t, restoreDetails.ProtectedTimestampRecord)
+
+	target := ptutil.GetPTSTarget(t, sqlDB, restoreDetails.ProtectedTimestampRecord)
+	targetIDs := target.GetSchemaObjects()
```
Comment (msbutler) [inline pkg/ccl/backupccl/backup_test.go:9296]: occasionally `targetIDs.IDs[0]` causes a nil pointer exception, which seems weird. still investigating why.

Comment (msbutler) [reply pkg/ccl/backupccl/backup_test.go:9300]: there was a bug in the code. Addressed.

File: pkg/ccl/backupccl/restore_job.go (hunk 3 above)
Comment (msbutler) [reply pkg/ccl/backupccl/restore_job.go]: good point. Instead we now log a warning, to follow in backup's footsteps. I believe there's some background reconciler that will remove the pts if this thing fails as well.

**Comment by msbutler** [comment]
latest CI revealed an interesting problem with the jobs protected timestamp manager. going to rework that now.

File: pkg/ccl/backupccl/testdata/backup-restore/restore-protect-spans (hunk 2 above)
Comment (msbutler) [reply pkg/ccl/backupccl/testdata/backup-restore/restore-protect-spans]: Test has been removed

**Comment by msbutler** [comment]
I took a long look at the [stress race failure ](https://teamcity.cockroachdb.com/viewLog.html?buildId=7740518&buildTypeId=Cockroach_Ci_Tests_MaybeStressrace&tab=buildLog&branch_Cockroach_Ci_Tests=%3Cdefault%3E&_focus=264#_state=264) picked up in Bazel Extended CI on my `TestProtectRestoreSpans` test, and while I can't pinpoint a root cause, I know the failure has nothing to do with protected timestamps.

Description of failure:
- when we restore system tables in the cluster restore subtest, `roleIDSeqRestoreFunc()` panics bc no ids exist in the `system.users` table. This race doesn't happen immediately -- usually takes 24 runs to observe it. 

My investigation:
- to repro the failure, I first had to disable tenants, as there's a different failure related to server startup. I plan to file a different issue.
- after removing the PTS logic from `restore_job.go` and my test, I could reproduce the failure, implying this failure is independent of my patch
- if I skip the cluster restore subtest, the test passes with flying colors
- if i only run the cluster restore subtest, a different stress failure (described in https://github.com/cockroachdb/cockroach/issues/43951) bubbles up, though with less frequency, so I'm unsure if they're related. 

My proposed next steps:
- disable stress race on this test and file separate issues for: the tenant server startup race and this mysterious oid race.

**Comment by msbutler** [comment]
@adityamaru @stevendanna friendly ping on this!

**Comment by msbutler** [comment]
I'm quite confident the stress-race failures are caused by #92848. When i disable `admission.elastic_cpu.enabled`, stress race does not seem to catch any problems.

File: pkg/ccl/backupccl/restore_job.go [hunk 5]
```diff
@@ -1353,6 +1355,57 @@ func createImportingDescriptors(
...
+		target = ptpb.MakeSchemaObjectsTarget(databaseIDs)
+	default:
+		// Else, protect individual tables.
+		tableIDs := make([]descpb.ID, 0, len(details.TableDescs))
+		for i := range details.TableDescs {
+			tableIDs = append(tableIDs, details.TableDescs[i].GetID())
+		}
+		target = ptpb.MakeSchemaObjectsTarget(tableIDs)
+	}
+	protectedTime := hlc.Timestamp{WallTime: timeutil.Now().UnixNano()}
```
Comment (adityamaru) [inline pkg/ccl/backupccl/restore_job.go:1405]: We should be protecting at `details.EndTime` right?

**Review by adityamaru — CHANGES_REQUESTED** [review]

File: pkg/ccl/backupccl/restore_job.go (hunk 5 above)
Comment (adityamaru) [reply pkg/ccl/backupccl/restore_job.go:1412]: I agree with your reasoning that this _will_ work but it is easier to reason about subsystems that work with time if they're all running as of a given snapshot which is what the `EndTime` defines for us. See for example https://github.com/cockroachdb/cockroach/pull/92788 and our existing backup code both of which work on timestamps we have deliberately picked during job record creation.

Comment (msbutler) [reply pkg/ccl/backupccl/restore_job.go:1412]: hm, i thought of another problem with `details.endtime`: it doesn't get set for non-AOST restores. Would you prefer using endtime for aost restores and time.Now() otherwise?

Comment (adityamaru) [reply pkg/ccl/backupccl/restore_job.go:1412]: oh thats a bummer, let's just leave it as is then. Anything else seems more bother than its worth considering we noop on resumptions.

**Review by adityamaru — APPROVED** [review]

File: pkg/ccl/backupccl/restore_job.go (hunk 5 above)
Comment (msbutler) [reply pkg/ccl/backupccl/restore_job.go:1412]: sounds good. thanks for reviewing!

**Comment by msbutler** [comment]
bors r=adityamaru
