### PR TITLE
kvserver: introduce stageDestroyReplica and pendingReplicaDestruction

### LINKED ISSUE #155121: Sentry: crash_reporting.go:413: error during replicaGC: context deadline exceeded (1) attached stack trace   -- stack trace:   | github.com/cockroachdb/cockroach/pkg/util/log/logcrash.ReportOrPanic   ...
This issue was auto filed by Sentry. It represents a crash or reported error on a live cluster with telemetry enabled.

Sentry Link: [https://cockroach-labs.sentry.io/issues/6932191518/?referrer=webhooks_plugin](https://cockroach-labs.sentry.io/issues/6932191518/?referrer=webhooks_plugin)

Panic Message:

```
crash_reporting.go:413: error during replicaGC: context deadline exceeded
(1) attached stack trace
  -- stack trace:
  | github.com/cockroachdb/cockroach/pkg/util/log/logcrash.ReportOrPanic
  | 	pkg/util/log/logcrash/crash_reporting.go:413
  | github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*replicaGCQueue).process
  | 	pkg/kv/kvserver/replica_gc_queue.go:324
  | github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*baseQueue).processReplica.func1
  | 	pkg/kv/kvserver/queue.go:978
  | github.com/cockroachdb/cockroach/pkg/util/timeutil.RunWithTimeout
  | 	pkg/util/timeutil/timeout.go:28
  | github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*baseQueue).processReplica
  | 	pkg/kv/kvserver/queue.go:971
  | github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*baseQueue).processOneAsyncAndReleaseSem.func1
  | 	pkg/kv/kvserver/queue.go:921
  | github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunAsyncTaskEx.func2
  | 	pkg/util/stop/stopper.go:498
  | runtime.goexit
  | 	src/runtime/asm_arm64.s:1222
Wraps: (2) secondary error attachment
  | context deadline exceeded
  | (1) context deadline exceeded
  | Error types: (1) context.deadlineExceededError
Wraps: (3) error during replicaGC: context deadline exceeded
Error types: (1) *withstack.withStack (2) *secondary.withSecondaryError (3) *errutil.leafError
-- report composition:
*errutil.leafError: error during replicaGC: context deadline exceeded
*secondary.withSecondaryError
crash_reporting.go:413: *withstack.withStack (top exception)
```

<details>
<summary>Stacktrace (expand for inline code snippets):</summary>

[src/runtime/asm_arm64.s#L1221-L1223](src/runtime/asm_arm64.s#L1221-L1223)
[pkg/util/stop/stopper.go#L497-L499](pkg/util/stop/stopper.go#L497-L499)
[pkg/kv/kvserver/queue.go#L920-L922](pkg/kv/kvserver/queue.go#L920-L922)
[pkg/kv/kvserver/queue.go#L970-L972](pkg/kv/kvserver/queue.go#L970-L972)
[pkg/util/timeutil/timeout.go#L27-L29](pkg/util/timeutil/timeout.go#L27-L29)
[pkg/kv/kvserver/queue.go#L977-L979](pkg/kv/kvserver/queue.go#L977-L979)
[pkg/kv/kvserver/replica_gc_queue.go#L323-L325](pkg/kv/kvserver/replica_gc_queue.go#L323-L325)
[pkg/util/log/logcrash/crash_reporting.go#L412-L414](pkg/util/log/logcrash/crash_reporting.go#L412-L414)
</details>

```
src/runtime/asm_arm64.s in runtime.goexit at line 1222
pkg/util/stop/stopper.go in pkg/util/stop.(*Stopper).RunAsyncTaskEx.func2 at line 498
pkg/kv/kvserver/queue.go in pkg/kv/kvserver.(*baseQueue).processOneAsyncAndReleaseSem.func1 at line 921
pkg/kv/kvserver/queue.go in pkg/kv/kvserver.(*baseQueue).processReplica at line 971
pkg/util/timeutil/timeout.go in pkg/util/timeutil.RunWithTimeout at line 28
pkg/kv/kvserver/queue.go in pkg/kv/kvserver.(*baseQueue).processReplica.func1 at line 978
pkg/kv/kvserver/replica_gc_queue.go in pkg/kv/kvserver.(*replicaGCQueue).process at line 324
pkg/util/log/logcrash/crash_reporting.go in pkg/util/log/logcrash.ReportOrPanic at line 413
```

### Tags

| Tag | Value |
| --- | --- |
| Command | server |
| Environment | v24.3.18 |
| Go Version | go1.22.8 X:nocoverageredesign |
| Platform | linux arm64 |
| Distribution | CCL |
| Cockroach Release | v24.3.18 |
| Cockroach SHA | 37439c410d4583708c898b13a2f9e906f444867b |
| # of CPUs | 32 |
| # of Goroutines | 6843 |

Jira issue: CRDB-55277

### PR DESCRIPTION
**Pull request by tbg**
This PR makes replica destruction resilient to engine errors by separating
fallible engine I/O from irreversible in-memory state changes.

Today, `destroyRaftMuLocked` builds an engine batch and commits it in one
shot. If the batch-building fails (e.g. due to I/O errors), the replica
may be left in a half-destroyed state, causing crashes or stuck replicas
(#155121, #162534).

The fix introduces a staging pattern: `stageDestroyReplica` builds the
engine batch without committing it. Callers perform sanity checks, then
stage, then (only on success) mark the replica as removed and commit via
the infallible `MustCommit`. If staging fails, the replica is untouched
and callers can return the error cleanly.

The early commits make `postDestroyRaftMuLocked` infallible (log-and-ignore
sideload cleanup errors) and introduce the staging API. The middle commits
wire it into both removal paths (initialized and uninitialized) and update
the three callers that previously crashed on removal errors (GC queue,
raft transport, `tryGetOrCreateReplica`) to handle them gracefully. The
final commit adds an integration test exercising error injection across
all three removal paths.

Part of: #162534
Fixes: #155121
Informs: #164944, #165558
Epic: none

### CODE REVIEW

File: pkg/kv/kvserver/store_remove_replica.go [hunk 1]
```diff
@@ -229,12 +231,17 @@ func (s *Store) removeInitializedReplicaRaftMuLocked(
...
+// whose destroyStatus is already set.
 func (s *Store) removeUninitializedReplicaRaftMuLocked(
 	ctx context.Context, rep *Replica, nextReplicaID roachpb.ReplicaID,
-) {
+) error {
 	rep.raftMu.AssertHeld()
 
-	// Sanity check this removal and set the destroyStatus.
+	// Sanity check this removal.
 	{
```
Comment (tbg) [inline pkg/kv/kvserver/store_remove_replica.go]: make this an anon closure so you can defer the unlocks.

File: pkg/kv/kvserver/replica_destroy.go [hunk 2]
```diff
@@ -57,12 +57,19 @@ func (s destroyStatus) Removed() bool {
 
 // postDestroyRaftMuLocked is called after the replica destruction is durably
 // written to Pebble.
-func (r *Replica) postDestroyRaftMuLocked(ctx context.Context) error {
+func (r *Replica) postDestroyRaftMuLocked(ctx context.Context) {
+	// Clearing sideloaded storage may fail (e.g. due to I/O errors), but we log
+	// and continue. The sideloaded files are keyed by the replica ID which has
```
Comment (pav-kv) [inline pkg/kv/kvserver/replica_destroy.go]: The sideloaded files are keyed by `RangeID`, so there might be an unfortunate side effect if a new replica with the same ID is created.

File: pkg/kv/kvserver/replica_destroy.go [hunk 3]
```diff
@@ -84,51 +87,121 @@ func (r *Replica) postDestroyRaftMuLocked(ctx context.Context) {
...
+//
+// This function performs engine reads (to validate replica ID and tombstone
+// state) and stages engine writes into a batch, but does not commit. If any
+// engine read fails (e.g. due to context cancellation or I/O error), the error
+// is returned and the caller can abort with no side effects.
+func stageDestroyReplica(
+	ctx context.Context,
+	bf *kvstorage.BatchFactory,
+	stateReader kvstorage.StateRO,
+	logReader kvstorage.RaftRO,
```
Comment (pav-kv) [inline pkg/kv/kvserver/replica_destroy.go]: naming convention used so far: `stateRO` and `raftRO`

File: pkg/kv/kvserver/replica_destroy.go [hunk 4]
```diff
@@ -84,51 +87,121 @@ func (r *Replica) postDestroyRaftMuLocked(ctx context.Context) {
...
+// and just needs to be written to the WAL). Callers rely on this by performing
+// irreversible in-memory state changes (e.g. setting destroyStatus) between
+// staging and committing. Making commit fallible would force callers to handle
+// rollback of those in-memory changes, adding significant complexity. If a
+// commit does fail, we are in an unrecoverable situation and must terminate.
+//
+// We sync here because we are potentially deleting sideloaded proposals from the
+// file system next. We could write the tombstone only in a synchronous batch
+// first and then delete the data alternatively, but then need to handle the case
+// in which there is both the tombstone and leftover replica data.
```
Comment (pav-kv) [inline pkg/kv/kvserver/replica_destroy.go]: pre-existing: took 4 reads until I understood what "alternatively" relates to, still not sure what "data" is (everything in the engine + sideloaded files?) and why deleting it separately from setting `RangeTombstone` is worth mentioning (worsened atomicity, no apparent benefit).

Could just state what we do and omit what we don't:

```golang
// We sync here because we are potentially deleting sideloaded proposals from
// the file system next, and don't want a crash in the middle to leave a log
// entry with a missing sideloaded file.
```

File: pkg/kv/kvserver/replica_destroy.go [hunk 5]
```diff
@@ -84,51 +87,121 @@ func (r *Replica) postDestroyRaftMuLocked(ctx context.Context) {
...
+		log.KvDistribution.Infof(ctx,
+			"removed uninitialized range in %0.0fms [clear=%0.0fms commit=%0.0fms]",
+			commitTime.Sub(p.stageTime).Seconds()*1000,
+			p.clearTime.Sub(p.stageTime).Seconds()*1000,
+			commitTime.Sub(p.clearTime).Seconds()*1000,
+		)
+	}
+}
 
+// Close closes the underlying batch. It is idempotent and safe to call after
```
Comment (pav-kv) [inline pkg/kv/kvserver/replica_destroy.go]: `batch.Close()` is not idempotent IIRC, since the underlying Pebble batch `Close()` isn't

Should the comment say that there should be no usage after `Close()`? Does the code rely on the idempotency (like an unconditional `defer Close()` that can be duplicated by a forced `Close()`)?

File: pkg/kv/kvserver/store_remove_replica.go [hunk 6]
```diff
@@ -229,45 +231,68 @@ func (s *Store) removeInitializedReplicaRaftMuLocked(
...
-) {
+) error {
 	rep.raftMu.AssertHeld()
 
-	// Sanity check this removal and set the destroyStatus.
-	{
+	// Sanity check this removal.
+	func() {
 		rep.readOnlyCmdMu.Lock()
+		defer rep.readOnlyCmdMu.Unlock()
```
Comment (pav-kv) [inline pkg/kv/kvserver/store_remove_replica.go]: Don't need mutexes for the 2 checks in this section. The signal is in `shMu` which can be read freely under `raftMu`.

The other 2 mutexes are needed only for writing `destroyStatus` below.

File: pkg/kv/kvserver/store_remove_replica.go [hunk 7]
```diff
@@ -143,6 +139,37 @@ func (s *Store) removeInitializedReplicaRaftMuLocked(
...
+	func() {
+		rep.readOnlyCmdMu.Lock()
+		defer rep.readOnlyCmdMu.Unlock()
+		rep.mu.Lock()
+		defer rep.mu.Unlock()
+		// NB: we hold raftMu throughout and destroyStatus is in shMu, so the destroyStatus
+		// did not change between the earlier sanity checks and here.
+		rep.shMu.destroyStatus.Set(kvpb.NewRangeNotFoundError(rep.RangeID, rep.StoreID()),
+			destroyReasonRemoved)
+	}()
```
Comment (pav-kv) [inline pkg/kv/kvserver/store_remove_replica.go]: Dups the inlined func in `removeUninitializedReplicaRaftMuLocked`, consider a method (with `RaftMuLocked` suffix etc).

File: pkg/kv/kvserver/store_remove_replica.go [hunk 8]
```diff
@@ -130,9 +129,6 @@ func (s *Store) removeInitializedReplicaRaftMuLocked(
 				repDesc.ReplicaID, nextReplicaID)
 		}
 
-		// Sanity checks passed. Mark the replica as removed before deleting data.
-		rep.shMu.destroyStatus.Set(kvpb.NewRangeNotFoundError(rep.RangeID, rep.StoreID()),
```
Comment (pav-kv) [inline pkg/kv/kvserver/store_remove_replica.go:132]: Same argument: now that we don't mutate `destroyStatus`, the `rep.{mu,readOnlyCmdMu}` don't need to be locked.

File: pkg/kv/kvserver/replica_destroy.go (hunk 2 above)
Comment (tbg) [reply pkg/kv/kvserver/replica_destroy.go]: I think we should be okay here. We clear the sideloaded storage when applying a snapshot, and that's guaranteed to happen before we get a newer version of this Replica. I think even without this, we would be okay, though it would be more subtle: we only ever do point lookups into the sideloaded storage based on entries we actually have, meaning we've appended before. Also, the range-index-term naming scheme unique identifies the content of a file, i.e. if it already exists, it is identical to what we were going to write. Plus, Put overwrites if necessary. But the snapshot-clear argument is the one that matters. Think I might be missing something here? Pushed a comment update.

File: pkg/kv/kvserver/replica_destroy.go (hunk 3 above)
Comment (tbg) [reply pkg/kv/kvserver/replica_destroy.go]: Done in `983d08f836a`.

File: pkg/kv/kvserver/replica_destroy.go (hunk 4 above)
Comment (tbg) [reply pkg/kv/kvserver/replica_destroy.go]: Good call, reworded in `8ac829f2de0`.

File: pkg/kv/kvserver/replica_destroy.go (hunk 5 above)
Comment (tbg) [reply pkg/kv/kvserver/replica_destroy.go]: You're right that Pebble's `writeBatch.Close()` is not idempotent (it panics on double-close). However, the `kvstorage.Batch[B].Close()` wrapper *is* idempotent — it nils out `b.state` on first call and returns early on subsequent calls (`kvstorage/storage.go:418`). So the comment was accurate at its layer.

That said, we don't actually rely on idempotency here. What we rely on is that `Close()` is safe to call after `MustCommit()` — the callers do `defer pending.Close()` and then later call `pending.MustCommit()`, so on the happy path Close runs after Commit. This works because `Commit()` does not close the batch (`pebble_batch.go:354`). This is the normal/happy path exercised by all tests, so it's well-covered.

Updated the comment to drop the idempotency claim and focus on the actual contract in `31025d725f5`.

File: pkg/kv/kvserver/store_remove_replica.go (hunk 6 above)
Comment (tbg) [reply pkg/kv/kvserver/store_remove_replica.go]: Done in `f59c751916d`. Removed closure entirely, now just inline checks with no locks.

File: pkg/kv/kvserver/store_remove_replica.go (hunk 8 above)
Comment (tbg) [reply pkg/kv/kvserver/store_remove_replica.go:132]: Done in `f59c751916d`. Dropped `readOnlyCmdMu` and `rep.mu`; kept `s.mu` scoped to just the `replicasByRangeID` check.

File: pkg/kv/kvserver/store_remove_replica.go (hunk 7 above)
Comment (tbg) [reply pkg/kv/kvserver/store_remove_replica.go]: Done in `5d894b5669c`. Extracted `setDestroyStatusRemovedRaftMuLocked` on `*Replica`. Tbh I don't love adding random methods to `*Replica` that only make sense to call in a very specific context. I could make a static method taking a `*Replica`? But that's neither here nor there too. And abstracting away from `*Replica` is just obfuscation. Wonder if there's a 100% pure way to have reuse just for the specific scope, without the kind of overhead that would result from defining a structurally identical type, etc,...

File: pkg/kv/kvserver/store_remove_replica.go [hunk 9]
```diff
@@ -113,7 +109,10 @@ func (s *Store) removeInitializedReplicaRaftMuLocked(
 		// delete random active data). Note that if the caller has !DestroyData,
 		// this means it needs to already know that the Replica is still in the
 		// Store.
-		if existing, ok := s.mu.replicasByRangeID.Load(rep.RangeID); !ok {
+		s.mu.Lock()
```
Comment (pav-kv) [inline pkg/kv/kvserver/store_remove_replica.go]: Is `s.mu` actually needed here? `replicasByRangeID` is a sync map and its comment speficically says it can be read without the mutex.

Maybe don't lock it here, and also rid of the nested `func()` which we don't need.

Comment (pav-kv) [reply pkg/kv/kvserver/store_remove_replica.go]: I wonder if there was any intention to lock it in the pre-existing code (like blocking that map mutation while we are at it), or it was an oversight.

File: pkg/kv/kvserver/client_replica_gc_test.go [hunk 10]
```diff
@@ -193,3 +194,103 @@ func TestReplicaGCQueueDropReplicaGCOnScan(t *testing.T) {
...
+
+	errInjected := errors.New("injected staging error")
+	var shouldFail atomic.Bool
+	shouldFail.Store(true)
+	var failCount atomic.Int32
+
+	knobs := &kvserver.StoreTestingKnobs{
+		// Force removal through the GC queue instead of the eager
+		// self-removal path (which fatals on error).
+		DisableEagerReplicaRemoval: true,
```
Comment (pav-kv) [inline pkg/kv/kvserver/client_replica_gc_test.go]: I was going to consider removing this knob, is it avoidable? Probably can be fixed up when needed, but maybe there is a quick workaround. E.g. make replica slow so that it doesn't hear about its removal until replica GC.

It breaks a `Store` [invariant](https://github.com/cockroachdb/cockroach/blob/8b94e5415364f62a8d8e126c938d38fe2f557f13/pkg/kv/kvserver/store.go#L850): the local replica is always part of the `RangeDescriptor`. I don't remember all details, but I was not happy how it looked w.r.t. the RSE invariant that any future replica begins its log at index > the previous replica destruction.

File: pkg/kv/kvserver/client_replica_gc_test.go [hunk 11]
```diff
@@ -193,3 +194,103 @@ func TestReplicaGCQueueDropReplicaGCOnScan(t *testing.T) {
...
+	require.NotZero(t, failCount.Swap(0), "error injection was not hit")
+
+	// The replica should still exist — the failed removal left no side effects.
+	_, err = store.GetReplica(desc.RangeID)
+	require.NoError(t, err, "replica should survive failed getOrCreateReplica removal")
+
+	// Remove error injection, force a GC scan — should succeed.
+	shouldFail.Store(false)
+
+	testutils.SucceedsSoon(t, func() error {
```
Comment (pav-kv) [inline pkg/kv/kvserver/client_replica_gc_test.go]: Curious why `SucceedsSoon` was needed. Is the effect of `MustForce...` asynchronous?

File: pkg/kv/kvserver/replica_destroy.go (hunk 2 above)
Comment (pav-kv) [reply pkg/kv/kvserver/replica_destroy.go]: Yeah, seems alright.

File: pkg/kv/kvserver/helpers_test.go [hunk 12]
```diff
@@ -80,6 +80,24 @@ func (s *Store) FindTargetAndTransferLease(
 	return transferStatus == allocator.TransferOK, err
 }
 
+// GetOrCreateReplica exposes getOrCreateReplica for use in tests. On success,
+// the returned Replica's raftMu is unlocked before returning.
+func (s *Store) GetOrCreateReplica(
+	ctx context.Context,
+	rangeID roachpb.RangeID,
+	replicaID roachpb.ReplicaID,
+	creatingReplica *roachpb.ReplicaDescriptor,
```
Comment (pav-kv) [inline pkg/kv/kvserver/helpers_test.go]: Unused? Could be nil.

File: pkg/kv/kvserver/store_create_replica.go [hunk 13]
```diff
@@ -114,7 +114,8 @@ func (s *Store) tryGetReplica(
 		if err := s.removeReplicaRaftMuLocked(
 			ctx, repl, id.ReplicaID, "superseded by newer Replica",
 		); err != nil {
-			log.KvExec.Fatalf(ctx, "failed to remove replica: %v", err)
+			repl.raftMu.Unlock()
+			return nil, err
```
Comment (pav-kv) [inline pkg/kv/kvserver/store_create_replica.go:118]: Will this error leak to the sender over the reply RPC stream or stay local? Any idea what we want for that case?

File: pkg/kv/kvserver/helpers_test.go (hunk 12 above)
Comment (tbg) [reply pkg/kv/kvserver/helpers_test.go]: will be addressed by the time I re-request review (still waiting to push).

File: pkg/kv/kvserver/client_replica_gc_test.go (hunk 11 above)
Comment (tbg) [reply pkg/kv/kvserver/client_replica_gc_test.go]: Yeah doesn't seem necessary. Will be addressed by the time I re-request review (still waiting to push).

File: pkg/kv/kvserver/store_remove_replica.go (hunk 9 above)
Comment (tbg) [reply pkg/kv/kvserver/store_remove_replica.go]: Good catch, the locking should not be necessary. Pushed a commit with rationale and the simplification you suggested.

will be addressed by the time I re-request review (still waiting to push).

File: pkg/kv/kvserver/store_create_replica.go (hunk 13 above)
Comment (tbg) [reply pkg/kv/kvserver/store_create_replica.go:118]: They'll bubble up. Most of the callers are the raft transport, which will report it to the sender, which will log it here: https://github.com/cockroachdb/cockroach/blob/b9a6a3d5e061c1f9b5cf73768386b1369afb5075/pkg/kv/kvserver/store_raft.go#L677-L679

Similarly if it happens on the snapshot apply path, the snapshot sender will receive it.

I don't think we want anything in particular for the moment other than not crashing. Ideally at some point we can quarantine the replica, something like https://github.com/cockroachdb/cockroach/issues/62199. But I don't want to get into that now.

File: pkg/kv/kvserver/client_replica_gc_test.go (hunk 10 above)
Comment (tbg) [reply pkg/kv/kvserver/client_replica_gc_test.go]: Yeah I dislike that path too. Removed with next push.

**Comment by tbg** [comment]
Pushed, clean rebase. First new commit is `kvserver: drop unused creatingReplica param from GetOrCreateReplica test helper`.

File: pkg/kv/kvserver/client_replica_gc_test.go [hunk 14]
```diff
@@ -193,3 +194,108 @@ func TestReplicaGCQueueDropReplicaGCOnScan(t *testing.T) {
...
+	// quorum (2/3).
+	preRemovalDesc, err := tc.LookupRange(k)
+	require.NoError(t, err)
+	var fromReplicaIDs []roachpb.ReplicaID
+	for _, rd := range preRemovalDesc.Replicas().Descriptors() {
+		if rd.StoreID != store.StoreID() {
+			fromReplicaIDs = append(fromReplicaIDs, rd.ReplicaID)
+		}
+	}
+	dropRaftMessagesFrom(t, ts, preRemovalDesc, fromReplicaIDs, nil)
```
Comment (pav-kv) [inline pkg/kv/kvserver/client_replica_gc_test.go:262]: Btw, there is a `tc.Partitioner()` just introduced in #166174. Though it probably would be too coarse here - we don't want to fully isolate this node (so that replica GC is able to read that the replica is removed).

(no action, just info)

File: pkg/kv/kvserver/client_replica_gc_test.go [hunk 15]
```diff
@@ -193,3 +194,108 @@ func TestReplicaGCQueueDropReplicaGCOnScan(t *testing.T) {
...
+
+	// Call RemoveReplica directly to observe the error.
+	repl, err := store.GetReplica(desc.RangeID)
+	require.NoError(t, err)
+	err = store.RemoveReplica(context.Background(), repl, desc.NextReplicaID, "test")
+	require.True(t, errors.Is(err, errInjected), "unexpected: %+v", err)
+	require.NotZero(t, failCount.Swap(0), "error injection was not hit")
+
+	// Force a GC scan — the queue should also hit the injected error.
+	store.MustForceReplicaGCScanAndProcess()
```
Comment (pav-kv) [inline pkg/kv/kvserver/client_replica_gc_test.go]: There is a chance that replica GC queue gets there by itself before us. But it would also fail, and in this case `failCount` would be > 1, which seems fine - the test code is robust.

(thinking out loud, no action)

File: pkg/kv/kvserver/replica_destroy.go [hunk 16]
```diff
@@ -55,14 +58,37 @@ func (s destroyStatus) Removed() bool {
...
+}
+
 // postDestroyRaftMuLocked is called after the replica destruction is durably
 // written to Pebble.
-func (r *Replica) postDestroyRaftMuLocked(ctx context.Context) error {
-	// TODO(#136416): at node startup, we should remove all on-disk directories
+func (r *Replica) postDestroyRaftMuLocked(ctx context.Context) {
+	// Clearing sideloaded storage may fail (e.g. due to I/O errors), but we log
+	// and continue. We've already committed the replica removal, and any future
+	// replica instantiation will go through a snapshot path which clears the
```
Comment (pav-kv) [inline pkg/kv/kvserver/replica_destroy.go:80]: > any future replica instantiation will go through a snapshot path

I think this is true. Tried to challenge this with some sequence, but couldn't think of a convincing counter-example.

One scenario that came to mind:
- pre-condition: our `r11` was split out from `r10`, but our store doesn't have `r10` and got `r11` by snapshot
- we destroy `r11` here
- after this, somehow, `r10` is created in a pre-split state (it got a slow snapshot)
- `r10` splits again and creates `r11`

But in this example, the replica ID of `r11` post split would be <= what is destroyed, so it wouldn't be created. It seems true that any higher replica ID can be created only by a snapshot: there are only 2 replica initialization paths, and we've excluded the split, so only snapshots left.

No action.

File: pkg/kv/kvserver/replica_destroy.go (hunk 2 above)
Comment (pav-kv) [reply pkg/kv/kvserver/replica_destroy.go]: The commit message got stale (still mentions ReplicaID). Update?

Same for the PR message. For the latter, I think it's best to keep it written in an overview style (high-level + why) rather than duplicate the commit sequence, since the sequence is low-level and subject to change during review. Also I had not the patience to read it, it's overwhelming as is and commits are self-sufficient.

File: pkg/kv/kvserver/replica_destroy.go [hunk 17]
```diff
@@ -84,51 +87,121 @@ func (r *Replica) postDestroyRaftMuLocked(ctx context.Context) {
...
+	initialized bool
+	stageTime   time.Time
+	clearTime   time.Time
+}
 
-	ms := r.GetMVCCStats()
-	batch := r.store.batchFactory.NewWriteBatch()
-	defer batch.Close()
+// MustCommit sync-commits the staged destruction batch and logs the result. The
+// caller should call Close when done (it is safe to call after MustCommit).
```
Comment (pav-kv) [inline pkg/kv/kvserver/replica_destroy.go]: nit: there is a mix of should/must in comments w.r.t. calling `Close`. I think it would be safe to drop this sentence. The `safe to call after MustCommit` bit is precise but not future-proof (what if there are other methods added, should they now also be covered by this comment?).

For comments about `Close` (which is a common idiom and needs no descriptions by default), I think it's enough to say:
- in the `stageDestroyReplica` comment that it must be called
- in the `Close` comment that it must be the last call on this type

Other clarifications work against it rather than help.

File: pkg/kv/kvserver/replica_destroy.go [hunk 18]
```diff
@@ -84,51 +87,121 @@ func (r *Replica) postDestroyRaftMuLocked(ctx context.Context) {
...
+
+// stageDestroyReplica builds a batch that, when committed, will destroy the
+// replica's on-disk state and install a tombstone. The returned
+// pendingReplicaDestruction must have Close called when it is no longer needed.
+//
+// This function performs engine reads (to validate replica ID and tombstone
+// state) and stages engine writes into a batch, but does not commit. If any
+// engine read fails (e.g. due to context cancellation or I/O error), the error
+// is returned and the caller can abort with no side effects.
+func stageDestroyReplica(
```
Comment (pav-kv) [inline pkg/kv/kvserver/replica_destroy.go:166]: nit: seems like this would be better off as a method of `Replica` - less bulky/ad-hoc, and less error-prone w.r.t. the passed in parameters. It doesn't seem like we use it standalone anywhere, and if/when we do we can refactor.

File: pkg/kv/kvserver/store_remove_replica.go [hunk 19]
```diff
@@ -79,68 +81,81 @@ func (s *Store) removeInitializedReplicaRaftMuLocked(
...
+	// There is a certain amount of idempotency in this method (repeat attempts
+	// to destroy an already destroyed replica are allowed when DestroyData is
+	// set, see the early return above), but if we get here then the Replica
+	// better be in the Store (since the Store enforces ownership over the
+	// keyspace, so deleting data for a Replica that's not in the Store can
+	// delete random active data). Note that if the caller has !DestroyData,
+	// this means it needs to already know that the Replica is still in the
+	// Store.
+	existing, ok := s.mu.replicasByRangeID.Load(rep.RangeID)
+	if !ok {
```
Comment (pav-kv) [inline pkg/kv/kvserver/store_remove_replica.go]: nit: the old/stateless `if existing, ok` idiom was alright/better

**Review by pav-kv — APPROVED** [review]
The "commit arc" got out of control, so I reviewed the end state. LGTM with minor nits.

File: pkg/kv/kvserver/replica_destroy.go (hunk 18 above)
Comment (tbg) [reply pkg/kv/kvserver/replica_destroy.go:166]: I'm surprised by that suggestion. I always try to keep functions honest/explicit about their actual dependencies, and try to avoid bloating `*Replica` further. Functionally, this code almost belongs in `kvstorage`. I will leave as is, since it's just a nit, but I'm curious about the rationale.

File: pkg/kv/kvserver/replica_destroy.go (hunk 17 above)
Comment (tbg) [reply pkg/kv/kvserver/replica_destroy.go]: done

File: pkg/kv/kvserver/store_remove_replica.go (hunk 19 above)
Comment (tbg) [reply pkg/kv/kvserver/store_remove_replica.go]: done.

File: pkg/kv/kvserver/replica_destroy.go (hunk 18 above)
Comment (pav-kv) [reply pkg/kv/kvserver/replica_destroy.go:166]: nit/taste obv, but rationale is: bulky (called from `Replica` twice, with identical stuff passed in), ad-hoc (lots of parameters that aren't well defined in the signature), some side effects of this type like timing things and logging when committed are not in the "pure type" style.

Comment (tbg) [reply pkg/kv/kvserver/replica_destroy.go:166]: Hmm, ok. I don't see it tbh, benefits well worth the cost IMO. The logging is not in this method BTW.
Anyway, was just curious, thank you for explaining!

File: pkg/kv/kvserver/replica_destroy.go (hunk 2 above)
Comment (tbg) [reply pkg/kv/kvserver/replica_destroy.go]: Updated.
