### PR TITLE
cloud: have resumable reader manage span lifetime

### LINKED ISSUE #153347: roachtest: restore/tpcc-5k/gce/nodes=4/cpus=8 failed
roachtest.restore/tpcc-5k/gce/nodes=4/cpus=8 [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/20452357?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/20452357?buildTab=artifacts#/restore/tpcc-5k/gce/nodes=4/cpus=8) on master @ [fe3f3462c904d4735fef481fff4536925d9d7a77](https://github.com/cockroachdb/cockroach/commits/fe3f3462c904d4735fef481fff4536925d9d7a77):

```
(monitor.go:267).Wait: monitor failure: context canceled
unexpected node event: n2: cockroach process for system interface died (exit code 134)
test artifacts and logs in: /artifacts/restore/tpcc-5k/gce/nodes=4/cpus=8/run_1
```

Parameters:
 - <code>arch=amd64</code>
 - <code>cloud=gce</code>
 - <code>coverageBuild=false</code>
 - <code>cpu=8</code>
 - <code>encrypted=false</code>
 - <code>fs=ext4</code>
 - <code>localSSD=false</code>
 - <code>runtimeAssertionsBuild=false</code>
 - <code>ssd=0</code>
<details><summary>Help</summary>
<p>

See: [roachtest README](https://github.com/cockroachdb/cockroach/blob/master/pkg/cmd/roachtest/README.md)

See: [How To Investigate \(internal\)](https://cockroachlabs.atlassian.net/l/c/SSSBr8c7)

See: [Grafana](https://go.crdb.dev/roachtest-grafana/teamcity-20452357/restore-tpcc-5k-gce-nodes-4-cpus-8/1757508254321/1757509227243)

</p>
</details>
/cc @cockroachdb/disaster-recovery
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*restore/tpcc-5k/gce/nodes=4/cpus=8.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/bazci/githubpost/issues)

</sub>

Jira issue: CRDB-54372

### PR DESCRIPTION
**Pull request by jeffswenson**
This change adds a span to the cloud.ResumableReader that is tracked for the lifetime of the reader. This ensures that if the reader implementation needs to issue a new HTTP request, the span is still valid and can be used to annotate logs.

Fixes: #153347
Release note: none

### CODE REVIEW

**Comment by jeffswenson** [comment]
https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_CloudUnitTests/20540934

File: pkg/cloud/azure/azure_storage.go [hunk 1]
```diff
@@ -366,6 +366,7 @@ func (s *azureStorage) ReadFile(
 			}
 		}
 	}
+	// BUG: we should follow the azure retry setting here.
```
Comment (msbutler) [inline pkg/cloud/azure/azure_storage.go:369]: do you understand why we don't use `NewResumingReader` here, like we do in all other implementations?

**Review by msbutler — COMMENTED** [review]
One question i'm struggling to answer is: once we enabled your http request logging package, why do we _only_ hit these SpanUseAfterFinish panics on _retries_.

In the original issue, you note that we only hit this after we add the roundtrip logging because that code injects our span infrastructure, which can detect SpanUseAfterFinish bugs, into lower level cloud io calls. That makes sense to me.

You also note in the issue, that in the gcstorage package,  we attach the `gcs.ReadFile` span to the resuming reader here:
https://github.com/jeffswenson/cockroach/blob/jeffswenson-cloud-span-lifetime/pkg/cloud/gcp/gcs_storage.go#L297

which is closed when ReadFile is returned. Doesn't that mean that the roundtripper will _always_ [fork ](https://github.com/jeffswenson/cockroach/blob/jeffswenson-cloud-span-lifetime/pkg/cloud/cloud_logging_transport.go#L54) a span that as already been finished on any read requests after ReadFile is returned? E.g. here:
https://github.com/jeffswenson/cockroach/blob/jeffswenson-cloud-span-lifetime/pkg/cloud/cloud_io.go#L332

File: pkg/cloud/azure/azure_storage.go (hunk 1 above)
Comment (jeffswenson) [reply pkg/cloud/azure/azure_storage.go:369]: I think whoever implemented it decided that the built in resume is sufficient. But the testing over on https://github.com/cockroachdb/cockroach/pull/154483 suggests it is not.

**Comment by jeffswenson** [comment]
> One question i'm struggling to answer is: once we enabled your http request logging package, why do we _only_ hit these SpanUseAfterFinish panics on _retries_.
> 
> In the original issue, you note that we only hit this after we add the roundtrip logging because that code injects our span infrastructure, which can detect SpanUseAfterFinish bugs, into lower level cloud io calls. That makes sense to me.
> 
> You also note in the issue, that in the gcstorage package, we attach the `gcs.ReadFile` span to the resuming reader here: https://github.com/jeffswenson/cockroach/blob/jeffswenson-cloud-span-lifetime/pkg/cloud/gcp/gcs_storage.go#L297
> 
> which is closed when ReadFile is returned. Doesn't that mean that the roundtripper will _always_ [fork ](https://github.com/jeffswenson/cockroach/blob/jeffswenson-cloud-span-lifetime/pkg/cloud/cloud_logging_transport.go#L54) a span that as already been finished on any read requests after ReadFile is returned? E.g. here: https://github.com/jeffswenson/cockroach/blob/jeffswenson-cloud-span-lifetime/pkg/cloud/cloud_io.go#L332

The reason it kind of worked is the logging infrastructure forks the span the moment the request starts. So we only need the span to survive until that point in time. The retries caused problems because they initiated an HTTP request after the span was already completed.

Something I admittedly have not been able to figure out is why the write path doesn't run into span use after free issues. Each chunk is its own HTTP request and the argument span is closed right away. In theory we should also need a wrapper that holds onto the span for the lifetime of the writer.

An alternative fix for this is we could ignore the span that comes in as part of the HTTP request and instead manage a span for the lifetime of the middleware (i.e. use a detached context the logging).

**Comment by jeffswenson** [comment]
The AWS and Azure writers have logic to correctly manage the span's lifetime:
https://github.com/cockroachdb/cockroach/blob/552cfcb086721820f921ed04c08af7e2df6eabcf/pkg/cloud/amazon/s3_storage.go#L821

https://github.com/cockroachdb/cockroach/blob/552cfcb086721820f921ed04c08af7e2df6eabcf/pkg/cloud/azure/azure_storage.go#L326

**Review by msbutler — APPROVED** [review]
