### PR TITLE
ttl: replace SPLIT AT with SplitTable in tests

### LINKED ISSUE #86376: sql/ttl/ttljob: TestRowLevelTTLJobRandomEntries failed
sql/ttl/ttljob.TestRowLevelTTLJobRandomEntries [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_StressBazel/6141492?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_StressBazel/6141492?buildTab=artifacts#/) on master @ [5c2c62ecf1bea60c807edc6b4da22d900ad4ae03](https://github.com/cockroachdb/cockroach/commits/5c2c62ecf1bea60c807edc6b4da22d900ad4ae03):

```
=== RUN   TestRowLevelTTLJobRandomEntries
    test_log_scope.go:162: test logs captured to: /artifacts/tmp/_tmp/74bc9dd224da62240eee8570f9dfa5ee/logTestRowLevelTTLJobRandomEntries4130734031
    test_log_scope.go:80: use -show-logs to present logs inline
=== CONT  TestRowLevelTTLJobRandomEntries
    ttljob_test.go:685: -- test log scope end --
--- FAIL: TestRowLevelTTLJobRandomEntries (51.32s)
=== RUN   TestRowLevelTTLJobRandomEntries/one_column_pk_multiple_nodes
    ttljob_test.go:546: test case: ttljob_test.testCase{desc:"one column pk multiple nodes", createTable:"CREATE TABLE tbl (\n\tid UUID PRIMARY KEY DEFAULT gen_random_uuid(),\n\ttext TEXT\n) WITH (ttl_expire_after = '30 days')", preSetup:[]string(nil), postSetup:[]string(nil), numExpiredRows:1001, numNonExpiredRows:5, numSplits:10, forceNonMultiTenant:false, numNodes:5, expirationExpression:"", addRow:(func(*ttljob_test.rowLevelTTLTestJobTestHelper, *tree.CreateTable, time.Time))(nil)}
    ttljob_test.go:679: 
        	Error Trace:	/home/roach/.cache/bazel/_bazel_roach/c5a4e7d36696d9cd970af2045211a7df/sandbox/processwrapper-sandbox/2374/execroot/com_github_cockroachdb_cockroach/bazel-out/k8-dbg/bin/pkg/sql/ttl/ttljob/ttljob_test_/ttljob_test.runfiles/com_github_cockroachdb_cockroach/pkg/sql/ttl/ttljob/ttljob_test.go:679
        	Error:      	Not equal: 
        	            	expected: 1001
        	            	actual  : 1082
        	Test:       	TestRowLevelTTLJobRandomEntries/one_column_pk_multiple_nodes
    --- FAIL: TestRowLevelTTLJobRandomEntries/one_column_pk_multiple_nodes (9.17s)
```
<p>Parameters: <code>TAGS=bazel,gss</code>
</p>
<details><summary>Help</summary>
<p>

See also: [How To Investigate a Go Test Failure \(internal\)](https://cockroachlabs.atlassian.net/l/c/HgfXfJgM)
</p>
</details>
/cc @cockroachdb/sql-experience
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*TestRowLevelTTLJobRandomEntries.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)
</sub>

Jira issue: CRDB-18727

### PR DESCRIPTION
**Pull request by ecwall**
refs https://github.com/cockroachdb/cockroach/issues/85800
fixes https://github.com/cockroachdb/cockroach/issues/86376

SPLIT AT was causing occasional test failures if it did not asynchronously
split the range before the TTL job started. SplitTable synchronously splits
the range before the test starts the TTL job.

Release justification: Fix test flake.

Release note: None

### CODE REVIEW

File: pkg/sql/ttl/ttljob/ttljob.go [hunk 1]
```diff
@@ -214,8 +214,15 @@ func (t rowLevelTTLResumer) Resume(ctx context.Context, execCtx interface{}) err
 		if err != nil {
 			return err
 		}
-		if knobs.RequireMultipleSpanPartitions && len(spanPartitions) == 0 {
-			return errors.New("multiple span partitions required")
+		expectedNumSpanPartitions := knobs.ExpectedNumSpanParitions
+		if expectedNumSpanPartitions != 0 {
+			actualNumSpanPartitions := len(spanPartitions)
+			if expectedNumSpanPartitions != actualNumSpanPartitions {
+				return errors.Newf(
```
Comment (otan) [inline pkg/sql/ttl/ttljob/ttljob.go:221]: should we make this `AssertionFailedf` which fails a bit more loudly?

File: pkg/sql/ttl/ttljob/ttljob_test.go [hunk 2]
```diff
@@ -46,6 +47,8 @@ import (
 	"github.com/stretchr/testify/require"
 )
 
+var zeroDuration time.Duration
```
Comment (otan) [inline pkg/sql/ttl/ttljob/ttljob_test.go:50]: wonder if you can make this `const` - `const zeroDuration = time.Duration(0)`

File: pkg/sql/ttl/ttljob/ttljob_test.go [hunk 3]
```diff
@@ -299,17 +345,98 @@ INSERT INTO t (id, crdb_internal_expiration) VALUES (1, now() - '1 month'), (2,
...
+	sqlDB.Exec(t, fmt.Sprintf(
+		`CREATE TABLE %s (
+			id INT PRIMARY KEY,
+			expire_at TIMESTAMP
+			) WITH (ttl_expiration_expression = 'expire_at')`,
+		tableName,
+	))
+
+	// split table
+	splitAt := 10_000
```
Comment (otan) [inline pkg/sql/ttl/ttljob/ttljob_test.go:387]: should we make `splitAt` and `rowsPerRange` const?

File: pkg/sql/ttl/ttljob/ttljob_test.go [hunk 4]
```diff
@@ -88,12 +92,18 @@ func newRowLevelTTLTestJobTestHelper(
 
 	// As `ALTER TABLE ... SPLIT AT ...` is not supported in multi-tenancy, we
```
Comment (otan) [inline pkg/sql/ttl/ttljob/ttljob_test.go:93]: this might be a problem i introduced, but this comment seems dated. maybe "we only run tests against a tenant for tests not utilising `SPLIT AT`". which your change, do multi-tenant tests work?

File: pkg/sql/exec_util.go [hunk 5]
```diff
@@ -1566,9 +1566,9 @@ type TTLTestingKnobs struct {
 	// AOSTDuration changes the AOST timestamp duration to add to the
 	// current time.
 	AOSTDuration *time.Duration
-	// RequireMultipleSpanPartitions is a flag to verify that the DistSQL will
-	// distribute the work across multiple nodes.
-	RequireMultipleSpanPartitions bool
+	// ExpectedNumSpanParitions causes the TTL job to fail if it does not match
+	// the number of DistSQL processors.
+	ExpectedNumSpanParitions int
```
Comment (otan) [inline pkg/sql/exec_util.go:1571]: nit: `Paritions` -> `Partitions`

**Review by otan — COMMENTED** [review]
in a follow up should any tests using `SPLIT AT` use the synchronous version too?

**Review by otan — APPROVED** [review]

File: pkg/sql/exec_util.go (hunk 5 above)
Comment (ecwall) [reply pkg/sql/exec_util.go:1571]: Goot catch

File: pkg/sql/ttl/ttljob/ttljob.go (hunk 1 above)
Comment (ecwall) [reply pkg/sql/ttl/ttljob/ttljob.go:221]: Yeah good idea

File: pkg/sql/ttl/ttljob/ttljob_test.go (hunk 2 above)
Comment (ecwall) [reply pkg/sql/ttl/ttljob/ttljob_test.go:50]: It looks like that doesn't help since we would need to assign the `const` to a `var` to get its address.

https://stackoverflow.com/questions/35146286/find-address-of-constant-in-go

File: pkg/sql/ttl/ttljob/ttljob_test.go (hunk 3 above)
Comment (ecwall) [reply pkg/sql/ttl/ttljob/ttljob_test.go:387]: Done

File: pkg/sql/ttl/ttljob/ttljob_test.go (hunk 4 above)
Comment (ecwall) [reply pkg/sql/ttl/ttljob/ttljob_test.go:93]: It gives this error
```
    ttljob_test.go:389: error executing 'SHOW RANGES FROM TABLE tbl': pq: RangeIterator failed to seek to /Meta2/"\x00": rpc error: code = Unauthenticated desc = requested key /Meta2/"\x00" not fully contained in tenant keyspace /Tenant/1{0-1}
```

**Comment by ecwall** [comment]
bors r=otan

**Comment by ecwall** [comment]
> in a follow up should any tests using `SPLIT AT` use the synchronous version too?

Yeah it seems in general tests should be using the synchronous version to make the behavior deterministic.
