### PR TITLE
sql: deflake TestCancelQueryPermissions

### LINKED ISSUE #73544: sql: TestCancelQueryPermissions failed
sql.TestCancelQueryPermissions [failed](https://teamcity.cockroachdb.com/viewLog.html?buildId=3859936&tab=buildLog) with [artifacts](https://teamcity.cockroachdb.com/viewLog.html?buildId=3859936&tab=artifacts#/) on master @ [f64232150885928ce2d7680136f7e0da413ac10c](https://github.com/cockroachdb/cockroach/commits/f64232150885928ce2d7680136f7e0da413ac10c):

```
=== RUN   TestCancelQueryPermissions
    test_log_scope.go:79: test logs captured to: /go/src/github.com/cockroachdb/cockroach/artifacts/logTestCancelQueryPermissions833194974
    test_log_scope.go:80: use -show-logs to present logs inline
    run_control_test.go:335: expected error 'query execution canceled', got: sql: database is closed
    run_control_test.go:368: -- test log scope end --
test logs left over in: /go/src/github.com/cockroachdb/cockroach/artifacts/logTestCancelQueryPermissions833194974
--- FAIL: TestCancelQueryPermissions (1.91s)
```
<details><summary>Help</summary>
<p>
See also: [How To Investigate a Go Test Failure \(internal\)](https://cockroachlabs.atlassian.net/l/c/HgfXfJgM)Parameters in this failure:

- GOFLAGS=-json
</p>
</details>
/cc @cockroachdb/sql-queries
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*TestCancelQueryPermissions.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)
</sub>

### PR DESCRIPTION
**Pull request by rharding6373**
Added a sleep between running the last cancel query test case and
stopping the test cluster in order to give the cancel queries a chance
to propagate before shutting down the cluster.

The issue took ~11K runs to reproduce. After adding the sleep, no
failures reproduced in >14K runs.

Fixes: 73544

Release note: None

### CODE REVIEW

File: pkg/sql/run_control_test.go [hunk 1]
```diff
@@ -365,6 +363,8 @@ GRANT admin TO has_admin2;
 			}
 		}()
 	}
+	// Give the cancel queries a chance to propagate before stopping the cluster.
+	time.Sleep(time.Second)
```
Comment (rafiss) [inline pkg/sql/run_control_test.go:367]: interesting, i thought `CANCEL QUERY` would only return success if the query had already been canceled. i guess not.

optional suggestion: to make this test a bit faster, we could move this sleep to be right after line 360 instead of here.

**Review by rafiss — APPROVED** [review]
lgtm!

**Review by rharding6373 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/74118)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rafiss)

___
*[pkg/sql/run_control_test.go, line 367 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/74118#-MrPWCVvOlmv41ur8AkD-r1-367:-MrTpPT50o0_6CD8wNIg:b-mcjoug) ([raw file](https://github.com/cockroachdb/cockroach/blob/eb649adad0dc271f370fe619b567b70846034a1d/pkg/sql/run_control_test.go#L367)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

interesting, i thought `CANCEL QUERY` would only return success if the query had already been canceled. i guess not.

optional suggestion: to make this test a bit faster, we could move this sleep to be right after line 360 instead of here.
</blockquote></details>

Maybe using `ExecSucceedsSoon` would be better here? That timeout is 45s by default, so could potentially lead to a longer test, see next paragraph. Thoughts?

Moving the sleep up into the `testCases` loop makes the test slower, as it turns out (~227 tests/m vs ~296 tests/m). The reason is that the sleep would be executed for each relevant test case (in this test suite, twice) before moving on to the next test case, whereas here it is only executed once for the entire suite. The same principle applies to `ExecSucceedsSoon`, which would block for up to 45s for each test case.

Another way I thought of to avoid the timeout, which is still potentially flaky, is to have two `WaitGroup`s, one for queries that should be successfully cancelled and one for the rest. Then we could wait for the successful group to reach 0 before stopping the cluster. But this means that if there is a bug with cancel, then you'd only find out when the test times out. I didn't think it was worth that unless it turns out the flakiness is still too high.

**Review by rafiss — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/74118)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rafiss and @rharding6373)

___
*[pkg/sql/run_control_test.go, line 367 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/74118#-MrPWCVvOlmv41ur8AkD-r1-367:-MrVYG1g126gqHcbhaex:bqjf1ei) ([raw file](https://github.com/cockroachdb/cockroach/blob/eb649adad0dc271f370fe619b567b70846034a1d/pkg/sql/run_control_test.go#L367)):*
<details><summary><i>Previously, rharding6373 (Rachael Harding) wrote…</i></summary><blockquote>

Maybe using `ExecSucceedsSoon` would be better here? That timeout is 45s by default, so could potentially lead to a longer test, see next paragraph. Thoughts?

Moving the sleep up into the `testCases` loop makes the test slower, as it turns out (~227 tests/m vs ~296 tests/m). The reason is that the sleep would be executed for each relevant test case (in this test suite, twice) before moving on to the next test case, whereas here it is only executed once for the entire suite. The same principle applies to `ExecSucceedsSoon`, which would block for up to 45s for each test case.

Another way I thought of to avoid the timeout, which is still potentially flaky, is to have two `WaitGroup`s, one for queries that should be successfully cancelled and one for the rest. Then we could wait for the successful group to reach 0 before stopping the cluster. But this means that if there is a bug with cancel, then you'd only find out when the test times out. I didn't think it was worth that unless it turns out the flakiness is still too high.
</blockquote></details>

ah ok, thanks for investigating and sorting out all those details. yeah i'd agree we don't need to spend time doing this in a more robust way right now. so i'm fine to merge like this!

**Comment by rharding6373** [comment]
TFTR!

bors r+
