### PR TITLE
backupccl: deflake TestShowBackup

### LINKED ISSUE #111015: test: TestShowBackup flakes on timestamp with not enough decimal places
In [this](https://teamcity.cockroachdb.com/viewLog.html?buildId=11864116&buildTypeId=Cockroach_BazelEssentialCi) test run, the timestamp `2023-09-21 01:13:25.3+00` did not have enough decimal places to match `^(.*\.[0-9]{2})[0-9]*\+00$`.

```
Failed
=== RUN   TestShowBackup
    test_log_scope.go:167: test logs captured to: /artifacts/tmp/_tmp/76aec2d78eb16f45b7d08dbac54800d8/logTestShowBackup3575638593
    test_log_scope.go:81: use -show-logs to present logs inline

pkg/testutils/testcluster/testcluster.go:1615: ((*TestCluster).ToggleReplicateQueues)
	NOTICE: .GetStores() called via implicit interface StorageLayerInterface;
HINT: consider using .StorageLayer().GetStores() instead.

pkg/ccl/backupccl/show_test.go:49: (TestShowBackup)
	NOTICE: .DB() called via implicit interface ApplicationLayerInterface;
HINT: consider using .ApplicationLayer().DB() instead.
TIP: consider replacing the test server initialization from:
    ts, ... := serverutils.StartServer(t, ...)
    defer ts.Stopper().Stop(...)
to:
    srv, ... := serverutils.StartServer(t, ...)
    defer srv.Stopper().Stop(...)
    ts := srv.ApplicationLayer()

See also: https://go.crdb.dev/p/testserver-and-cluster-virtualization

pkg/testutils/testcluster/testcluster.go:1615: ((*TestCluster).ToggleReplicateQueues)
	NOTICE: .GetStores() called via implicit interface StorageLayerInterface;
HINT: consider using .StorageLayer().GetStores() instead.
    show_test.go:129: 
        	Error Trace:	github.com/cockroachdb/cockroach/pkg/ccl/backupccl/show_test.go:129
        	Error:      	Expected value not to be nil.
        	Test:       	TestShowBackup
        	Messages:   	2023-09-21 01:13:25.3+00 does not match ^(.*\.[0-9]{2})[0-9]*\+00$
    testutils.go:289: no Invalid Descriptors
    testutils.go:289: no Invalid Descriptors
    panic.go:522: -- test log scope end --
test logs left over in: /artifacts/tmp/_tmp/76aec2d78eb16f45b7d08dbac54800d8/logTestShowBackup3575638593
--- FAIL: TestShowBackup (2.22s)
```

Jira issue: CRDB-31714

### PR DESCRIPTION
**Pull request by msbutler**
This patch simplifies how TestShowBackup parses the stringed timestamp: it
removes the manual splitting of date and time and parses the stringed timestamp
in one call.

Fixes: https://github.com/cockroachdb/cockroach/issues/111015

Release note: none

### CODE REVIEW

File: pkg/ccl/backupccl/show_test.go [hunk 1]
```diff
@@ -124,7 +124,7 @@ ORDER BY object_type, object_name`, full)
 	// Truncate decimal places so Go's very rigid parsing will work.
 	// TODO(bardin): Consider using a third-party library for this, or some kind
 	// of time-freezing on the test cluster.
-	truncateBackupTimeRE := regexp.MustCompile(`^(.*\.[0-9]{2})[0-9]*\+00$`)
+	truncateBackupTimeRE := regexp.MustCompile(`^(.*\.\d{2})?[0-9]*\+00$`)
```
Comment (stevendanna) [inline pkg/ccl/backupccl/show_test.go:127]: I'm not sure this is correct.  This is making the entire match group optional.

The point of this code is to get a date in a format that will be usable in the `time.Parse` call below. So, even if it did work, we'd still have a problem since our date won't work with the time.Parse call .

What's interesting is that the whole reason this occurs is because it seems our time formatting code doesn't output a fixed width format for fractional seconds.  That is very surprising to me.

We can see this truncation in action and see how very unlucky we got by hitting this. `now()` provides microsecond level percision:

```
> SELECT ts::string FROM (SELECT now()::timestamptz as ts)                                                                                                                                                        
                                -> ;                                                                                                                                                                                                               
               ts
---------------------------------
  2023-10-04 10:17:29.093215+00
(1 row)
```

So, I think to hit this we had to be at .3 seconds _to the microsecond_. Bad luck for us. If we fix the timestamp using AOST we can see the truncation:

```
> SELECT ts::string FROM (SELECT now()::timestamptz as ts)  AS OF SYSTEM TIME '2023-10-04 10:00:30.300000';                                                                                                       
             ts
----------------------------
  2023-10-04 10:00:30.3+00
(1 row)
```

Perhaps one potential option to fix this is up where we ask for the timestamp originally,  using experimental_strftime in SQL to format the date: `SELECT experimental_strftime(now()::timestamptz, '%Y-%m-%d %H:%M:%S.%f')`.  This doesn't appear to truncate:

```
> SELECT experimental_strftime(ts, '%Y-%m-%d %H:%M:%S.%f') FROM (SELECT now()::timestamptz as ts)  AS OF SYSTEM TIME '2023-10-04 10:00:30.30';                                                                    
    experimental_strftime
------------------------------
  2023-10-04 10:00:30.300000
(1 row)
```

Another option is to change this regexp to accept 1 or 2 trailing decimal places with something like (untested) `^(.*\.\d{1,2})[0-9]*\+00$`.  Then, in the parse function, we can use a format like: `"2006-01-02 15:04:05.99"`.  The 9s rather than 0s in the fractional seconds portion tells Go that there might elided trailing 0s.

Comment (stevendanna) [reply pkg/ccl/backupccl/show_test.go:127]: Actually, now that I think about it for another second, perhaps we can remove the regexp all together and change the parsing code to something like `"2006-01-02 15:04:05.999999Z07"` (in the case without strftime).

Comment (msbutler) [reply pkg/ccl/backupccl/show_test.go]: lets see!

Comment (msbutler) [reply pkg/ccl/backupccl/show_test.go]: the go playground likes your suggestion anyways https://go.dev/play/p/9K0WWyS36S_O

**Review by stevendanna — APPROVED** [review]

**Comment by msbutler** [comment]
TFTR!

bors r=stevendanna
