### PR TITLE
kvserver: tighten and de-fatal replicaGC checks

### LINKED ISSUE #94813: kvserver: v22.1.9: replica descriptor's ID has changed
This issue was autofiled by Sentry. It represents a crash or reported error on a live cluster with telemetry enabled.

Sentry link: https://sentry.io/organizations/cockroach-labs/issues/3857152295/?referrer=webhooks_plugin

Panic message:

>store_remove_replica.go:119: log.Fatal: replica descriptor's ID has changed (4 >= 4)
(1) attached stack trace
  -- stack trace:
  | github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*Store).removeInitializedReplicaRaftMuLocked
  | 	github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/store_remove_replica.go:119
  | github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*Store).RemoveReplica
  | 	github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/store_remove_replica.go:50
  | github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*replicaGCQueue).process
  | 	github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/replica_gc_queue.go:318
  | github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*baseQueue).processReplica.func1
  | 	github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/queue.go:977
  | github.com/cockroachdb/cockroach/pkg/util/contextutil.RunWithTimeout
  | 	github.com/cockroachdb/cockroach/pkg/util/contextutil/context.go:91
  | github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*baseQueue).processReplica
  | 	github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/queue.go:936
  | github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*baseQueue).processLoop.func2.1
  | 	github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/queue.go:855
  | github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunAsyncTaskEx.func2
  | 	github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:494
  | runtime.goexit
  | 	GOROOT/src/runtime/asm_amd64.s:1581
Wraps: (2) log.Fatal: replica descriptor's ID has changed (4 >= 4)
Error types: (1) *withstack.withStack (2) *errutil.leafError
-- report composition:
*errutil.leafError: log.Fatal: replica descriptor's ID has changed (4 >= 4)
store_remove_replica.go:119: *withstack.withStack (top exception)

<details>
<summary>Stacktrace (expand for inline code snippets):</summary>

https://github.com/cockroachdb/cockroach/blob/e438c2f89282e607e0e6ca1d38b2e0a622f94493/pkg/kv/kvserver/pkg/kv/kvserver/store_remove_replica.go#L118-L120 in pkg/kv/kvserver.(*Store).removeInitializedReplicaRaftMuLocked
https://github.com/cockroachdb/cockroach/blob/e438c2f89282e607e0e6ca1d38b2e0a622f94493/pkg/kv/kvserver/pkg/kv/kvserver/store_remove_replica.go#L49-L51 in pkg/kv/kvserver.(*Store).RemoveReplica
https://github.com/cockroachdb/cockroach/blob/e438c2f89282e607e0e6ca1d38b2e0a622f94493/pkg/kv/kvserver/pkg/kv/kvserver/replica_gc_queue.go#L317-L319 in pkg/kv/kvserver.(*replicaGCQueue).process
https://github.com/cockroachdb/cockroach/blob/e438c2f89282e607e0e6ca1d38b2e0a622f94493/pkg/kv/kvserver/pkg/kv/kvserver/queue.go#L976-L978 in pkg/kv/kvserver.(*baseQueue).processReplica.func1
https://github.com/cockroachdb/cockroach/blob/e438c2f89282e607e0e6ca1d38b2e0a622f94493/pkg/util/contextutil/context.go#L90-L92 in pkg/util/contextutil.RunWithTimeout
https://github.com/cockroachdb/cockroach/blob/e438c2f89282e607e0e6ca1d38b2e0a622f94493/pkg/kv/kvserver/pkg/kv/kvserver/queue.go#L935-L937 in pkg/kv/kvserver.(*baseQueue).processReplica
https://github.com/cockroachdb/cockroach/blob/e438c2f89282e607e0e6ca1d38b2e0a622f94493/pkg/kv/kvserver/pkg/kv/kvserver/queue.go#L854-L856 in pkg/kv/kvserver.(*baseQueue).processLoop.func2.1
https://github.com/cockroachdb/cockroach/blob/e438c2f89282e607e0e6ca1d38b2e0a622f94493/pkg/util/stop/stopper.go#L493-L495 in pkg/util/stop.(*Stopper).RunAsyncTaskEx.func2
GOROOT/src/runtime/asm_amd64.s#L1580-L1582 in runtime.goexit
</details>

```
pkg/kv/kvserver/pkg/kv/kvserver/store_remove_replica.go in pkg/kv/kvserver.(*Store).removeInitializedReplicaRaftMuLocked at line 119
pkg/kv/kvserver/pkg/kv/kvserver/store_remove_replica.go in pkg/kv/kvserver.(*Store).RemoveReplica at line 50
pkg/kv/kvserver/pkg/kv/kvserver/replica_gc_queue.go in pkg/kv/kvserver.(*replicaGCQueue).process at line 318
pkg/kv/kvserver/pkg/kv/kvserver/queue.go in pkg/kv/kvserver.(*baseQueue).processReplica.func1 at line 977
pkg/util/contextutil/context.go in pkg/util/contextutil.RunWithTimeout at line 91
pkg/kv/kvserver/pkg/kv/kvserver/queue.go in pkg/kv/kvserver.(*baseQueue).processReplica at line 936
pkg/kv/kvserver/pkg/kv/kvserver/queue.go in pkg/kv/kvserver.(*baseQueue).processLoop.func2.1 at line 855
pkg/util/stop/stopper.go in pkg/util/stop.(*Stopper).RunAsyncTaskEx.func2 at line 494
GOROOT/src/runtime/asm_amd64.s in runtime.goexit at line 1581
```

| Tag | Value |
|---|---|
| Cockroach Release | `v22.1.9` |
| Cockroach SHA: | e438c2f89282e607e0e6ca1d38b2e0a622f94493 |
| Platform | linux amd64 |
| Distribution | CCL |
| Environment | v22.1.9 |
| Command | server |
| Go Version | |
| # of CPUs ||
| # of Goroutines ||

Jira issue: CRDB-23154

### PR DESCRIPTION
**Pull request by tbg**
Now we return most failed checks as errors and report errors to sentry (but
without crashing).

Closes https://github.com/cockroachdb/cockroach/issues/94813.

Epic: None
Release note: None

### CODE REVIEW

File: pkg/kv/kvserver/store_remove_replica.go [hunk 1]
```diff
@@ -88,64 +88,67 @@ func (s *Store) removeInitializedReplicaRaftMuLocked(
 
 	}
 
-	// Sanity checks before committing to the removal by setting the
-	// destroy status.
-	var desc *roachpb.RangeDescriptor
+	// Another sanity check that the Replica that we're planning to remove is
+	// still the one in the Store.
 	{
+		existing, err := s.GetReplica(rep.RangeID)
```
Comment (tbg) [inline pkg/kv/kvserver/store_remove_replica.go:94]: This has to be ordered after the `return nil, nil` in the closure below. Thanks tests for pointing this out.

Comment (tbg) [reply pkg/kv/kvserver/store_remove_replica.go:94]: Actually I like this new code more, we seem to be removing already removed replicas - the old conditional was clearly put in to make that allowed, but it seems worth understanding how we end up in situations in which we're replicaGC'ing a previously replicaGC'ed replica. Perhaps some race in the replicate queue?

File: pkg/kv/kvserver/store_remove_replica.go [hunk 2]
```diff
@@ -88,64 +88,70 @@ func (s *Store) removeInitializedReplicaRaftMuLocked(
...
-	// Sanity checks before committing to the removal by setting the
-	// destroy status.
-	var desc *roachpb.RangeDescriptor
-	{
+	// Run sanity checks and on success commit to the removal by setting the
+	// destroy status. If (nil, nil) is returned, there's nothing to do.
+	desc, err := func() (*roachpb.RangeDescriptor, error) {
 		rep.readOnlyCmdMu.Lock()
+		defer rep.readOnlyCmdMu.Unlock()
+		s.mu.Lock()
```
Comment (tbg) [inline pkg/kv/kvserver/store_remove_replica.go:96]: This is apparently the right locking order...

File: pkg/kv/kvserver/replica_gc_queue.go [hunk 3]
```diff
@@ -323,6 +324,10 @@ func (rgcq *replicaGCQueue) process(
 		if err := repl.store.RemoveReplica(ctx, repl, nextReplicaID, RemoveOptions{
 			DestroyData: true,
 		}); err != nil {
+			// Should never get an error from RemoveReplica.
+			const format = "error during replicaGC: %v"
+			log.Errorf(ctx, format, err)
```
Comment (erikgrinaker) [inline pkg/kv/kvserver/replica_gc_queue.go:329]: `ReportOrPanic()` will do a `log.Warningf()`, so this seems superfluous (that should arguably be a `log.Errorf()` though).

**Review by erikgrinaker — APPROVED** [review]
LGTM, thanks!

File: pkg/kv/kvserver/replica_gc_queue.go (hunk 3 above)
Comment (tbg) [reply pkg/kv/kvserver/replica_gc_queue.go]: Agree, will send a sep PR

**Comment by tbg** [comment]
TFTR!

bors r=erikgrinaker
