### PR TITLE
atomically update error in TestFailedReplicaChange

### LINKED ISSUE #525: Data Race in client_raft_test.go related to {Set,}GoError
The following test appears to have failed:

[#1045](https://circleci.com/gh/cockroachdb/cockroach/1045):

```
I0331 16:44:31.338037     263 multiraft.go:638] HardState updated: {Term:6 Vote:257 Commit:13 XXX_unrecognized:[]}
I0331 16:44:31.338363     263 multiraft.go:641] New Entry[0]: 6/13 EntryConfChange "\b\x00\x10\x00\x18\x82\x04\"\xcd\x01\x00\x13Т\xf8\xcb5Z764c\x89,\f\xb7?\x10\x01\x1a\xb7\x01J\xb4\x01\n\x8f\x01\n\x04\b\x00\x10\x05\x12\x14\b\xb7\xb4\xd5ٌߨ\xe8\x13\x10\xbf\xee\xb2
I0331 16:44:31.338608     263 multiraft.go:644] Committed Entry[0]: 6/13 EntryConfChange "\b\x00\x10\x00\x18\x82\x04\"\xcd\x01\x00\x13Т\xf8\xcb5Z764c\x89,\f\xb7?\x10\x01\x1a\xb7\x01J\xb4\x01\n\x8f\x01\n\x04\b\x00\x10\x05\x12\x14\b\xb7\xb4\xd5ٌߨ\xe8\x13\x10\xbf\xee\xb2
W0331 16:44:31.339831     263 multiraft.go:766] aborting configuration change: client_raft_test.go:242: boom
==================
WARNING: DATA RACE
Write by goroutine 58:
  github.com/cockroachdb/cockroach/proto.(*ResponseHeader).SetGoError()
      /go/src/github.com/cockroachdb/cockroach/proto/api.go:613 +0x13b
  github.com/cockroachdb/cockroach/kv.func·007()
      /go/src/github.com/cockroachdb/cockroach/kv/local_sender.go:153 +0x77d
  github.com/cockroachdb/cockroach/util.RetryWithBackoff()
      /go/src/github.com/cockroachdb/cockroach/util/retry.go:80 +0x6d
  github.com/cockroachdb/cockroach/kv.(*LocalSender).Send()
      /go/src/github.com/cockroachdb/cockroach/kv/local_sender.go:163 +0x1dc
  github.com/cockroachdb/cockroach/kv.(*TxnCoordSender).sendOne()
--
  github.com/cockroachdb/cockroach/storage_test.TestFailedReplicaChange()
      /go/src/github.com/cockroachdb/cockroach/storage/client_raft_test.go:253 +0x571
  testing.tRunner()
      /usr/src/go/src/testing/testing.go:447 +0x133

Previous read by goroutine 37:
  github.com/cockroachdb/cockroach/proto.(*Error).Error()
      /go/src/github.com/cockroachdb/cockroach/proto/errors.go:30 +0x48
  fmt.(*pp).handleMethods()
      /usr/src/go/src/fmt/print.go:714 +0x534
  fmt.(*pp).printArg()
      /usr/src/go/src/fmt/print.go:794 +0x492
  fmt.(*pp).doPrintf()
      /usr/src/go/src/fmt/print.go:1183 +0x2ec9
  fmt.Fprintf()
      /usr/src/go/src/fmt/print.go:188 +0x88
I0331 16:44:31.338037     263 multiraft.go:638] HardState updated: {Term:6 Vote:257 Commit:13 XXX_unrecognized:[]}
I0331 16:44:31.338363     263 multiraft.go:641] New Entry[0]: 6/13 EntryConfChange "\b\x00\x10\x00\x18\x82\x04\"\xcd\x01\x00\x13Т\xf8\xcb5Z764c\x89,\f\xb7?\x10\x01\x1a\xb7\x01J\xb4\x01\n\x8f\x01\n\x04\b\x00\x10\x05\x12\x14\b\xb7\xb4\xd5ٌߨ\xe8\x13\x10\xbf\xee\xb2
I0331 16:44:31.338608     263 multiraft.go:644] Committed Entry[0]: 6/13 EntryConfChange "\b\x00\x10\x00\x18\x82\x04\"\xcd\x01\x00\x13Т\xf8\xcb5Z764c\x89,\f\xb7?\x10\x01\x1a\xb7\x01J\xb4\x01\n\x8f\x01\n\x04\b\x00\x10\x05\x12\x14\b\xb7\xb4\xd5ٌߨ\xe8\x13\x10\xbf\xee\xb2
W0331 16:44:31.339831     263 multiraft.go:766] aborting configuration change: client_raft_test.go:242: boom
==================
WARNING: DATA RACE
Write by goroutine 58:
  github.com/cockroachdb/cockroach/proto.(*ResponseHeader).SetGoError()
      /go/src/github.com/cockroachdb/cockroach/proto/api.go:613 +0x13b
  github.com/cockroachdb/cockroach/kv.func·007()
      /go/src/github.com/cockroachdb/cockroach/kv/local_sender.go:153 +0x77d
  github.com/cockroachdb/cockroach/util.RetryWithBackoff()
      /go/src/github.com/cockroachdb/cockroach/util/retry.go:80 +0x6d
  github.com/cockroachdb/cockroach/kv.(*LocalSender).Send()
      /go/src/github.com/cockroachdb/cockroach/kv/local_sender.go:163 +0x1dc
  github.com/cockroachdb/cockroach/kv.(*TxnCoordSender).sendOne()
--
  github.com/cockroachdb/cockroach/storage_test.TestFailedReplicaChange()
      /go/src/github.com/cockroachdb/cockroach/storage/client_raft_test.go:253 +0x571
  testing.tRunner()
      /usr/src/go/src/testing/testing.go:447 +0x133

Previous read by goroutine 37:
  github.com/cockroachdb/cockroach/proto.(*Error).Error()
      /go/src/github.com/cockroachdb/cockroach/proto/errors.go:30 +0x48
  fmt.(*pp).handleMethods()
      /usr/src/go/src/fmt/print.go:714 +0x534
  fmt.(*pp).printArg()
      /usr/src/go/src/fmt/print.go:794 +0x492
  fmt.(*pp).doPrintf()
      /usr/src/go/src/fmt/print.go:1183 +0x2ec9
  fmt.Fprintf()
      /usr/src/go/src/fmt/print.go:188 +0x88

```
Please assign, take a look and update the issue accordingly.

### PR DESCRIPTION
**Pull request by tbg**
possibly SetGoError() should always update errors atomically
to prevent similar issues in the future. I can add that to this
PR if it sounds like a good idea.

closes #525

### CODE REVIEW

File: storage/client_raft_test.go [hunk 1]
```diff
@@ -239,7 +241,9 @@ func TestFailedReplicaChange(t *testing.T) {
 	}()
 	storage.TestingCommandFilter = func(method string, args proto.Request, reply proto.Response) bool {
 		if method == proto.EndTransaction && args.(*proto.EndTransactionRequest).Commit == true {
-			reply.Header().SetGoError(util.Errorf("boom"))
+			oldErr := unsafe.Pointer(&reply.Header().Error)
+			newErr := proto.Error{Message: "boom"}
+			atomic.SwapPointer((*unsafe.Pointer)(oldErr), unsafe.Pointer(&newErr))
```
Comment (petermattis) [inline storage/client_raft_test.go]: Slightly odd that you're casting `oldErr` (type `unsafe.Pointer`) to the type `*unsafe.Pointer`. I think this would be more natural as:

```
  oldErr := unsafe.Pointer(reply.Header().Error)
  newErr := &proto.Error{Message: "boom"}
  atomic.SwapPointer(&oldErr, unsafe.Pointer(newErr))
```

**Comment by petermattis** [comment]
LGTM

File: storage/client_raft_test.go (hunk 1 above)
Comment (tschottdorf) [inline storage/client_raft_test.go]: Yeah, except that that doesn't actually store the new error.. I had to play around with it a fair bit to end up with the one above that actually worked.

Comment (tschottdorf) [inline storage/client_raft_test.go]: Google only led me to http://play.golang.org/p/7Q5B7jE-uz via https://groups.google.com/forum/#!topic/golang-nuts/2Abz-DnSy8w and they do the same thing. Would love to know why that's how it works and not differently.

Comment (petermattis) [inline storage/client_raft_test.go]: Ah, you're correct. This is confusing. The first argument to `swapPointer` is a pointer to the pointer to set. But that needs to be a pointer to the `Error`, not a pointer to the `unsafe.Pointer`. Only minor tweak is that you can use `StorePointer` here instead of `SwapPointer` since you aren't using the return value.

**Comment by bdarnell** [comment]
TestingCommandFilter is called in the same thread as regular command execution - if we need to atomically update things here then we have bigger problems. Maybe we need to clone a new reply proto for retries instead of resetting and reusing the same one.

**Comment by tschottdorf** [comment]
The issue here is that MultiRaft gets a hold of the `err` in a function executed on its `callbackChan`, so that's not on the main thread. That's why I suggested having atomic updates in `SetGoError()`, although we could equivalently make sure that the callback function gets a copy of the error.
At least from this issue it looks like an isolated incident.

**Comment by bdarnell** [comment]
OK. It doesn't look like the use of atomic.StorePointer actually matters here then - what's important is that there's a new copy. I think all we need to do then is remove the nil check in SetGoError (https://github.com/cockroachdb/cockroach/blob/f9f8c196a09cc3221da47763dda4dc70fca8c2be/proto/api.go#L610) so it unconditionally creates a new error object instead of reusing an old one.

**Comment by tschottdorf** [comment]
@bdarnell PTAL

**Comment by bdarnell** [comment]
LGTM
