### PR TITLE
storage: fix segfault during declined snapshots

### LINKED ISSUE #12249: storage: panic in HandleSnapshot
Found in: https://teamcity.cockroachdb.com/viewLog.html?buildId=86361&buildTypeId=Cockroach_UnitTests

```
[02:58:32] :		 [TestGossipHandlesReplacedNode] I161210 02:55:33.269359 40749 storage/replica_raftstorage.go:468  [n1,replicate,s1,r3/1:/Table/1{2-3},@c421486a00] generated preemptive snapshot 220c1297 at index 35
[02:58:32] :		 [TestGossipHandlesReplacedNode] I161210 02:55:33.273473 40757 storage/replica_raftstorage.go:468  [n2,replicate,s2,r2/2:/Table/1{1-2},@c4205e0500] generated preemptive snapshot da131f41 at index 43
[02:58:32] :		 [TestGossipHandlesReplacedNode] panic: runtime error: invalid memory address or nil pointer dereference [recovered]
[02:58:32] :		 [TestGossipHandlesReplacedNode] 	panic: runtime error: invalid memory address or nil pointer dereference
[02:58:32] :		 [TestGossipHandlesReplacedNode] [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x662718]
[02:58:32] :		 [TestGossipHandlesReplacedNode] 
[02:58:32] :		 [TestGossipHandlesReplacedNode] goroutine 40898 [running]:
[02:58:32] :		 [TestGossipHandlesReplacedNode] panic(0x1faf920, 0xc4200120f0)
[02:58:32] :		 [TestGossipHandlesReplacedNode] 	/usr/local/go/src/runtime/panic.go:500 +0x1ae
[02:58:32] :		 [TestGossipHandlesReplacedNode] github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).Recover(0xc42022a6c0)
[02:58:32] :		 [TestGossipHandlesReplacedNode] 	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:185 +0xd8
[02:58:32] :		 [TestGossipHandlesReplacedNode] panic(0x1faf920, 0xc4200120f0)
[02:58:32] :		 [TestGossipHandlesReplacedNode] 	/usr/local/go/src/runtime/panic.go:458 +0x271
[02:58:32] :		 [TestGossipHandlesReplacedNode] github.com/cockroachdb/cockroach/pkg/storage.(*Store).HandleSnapshot(0xc4216d4380, 0xc42213c6c0, 0x2ae12bc5aef0, 0xc4217c1690, 0x300e180, 0xc420012170)
[02:58:32] :		 [TestGossipHandlesReplacedNode] 	/go/src/github.com/cockroachdb/cockroach/pkg/storage/store.go:2698 +0xbc9
[02:58:32] :		 [TestGossipHandlesReplacedNode] github.com/cockroachdb/cockroach/pkg/storage.(*RaftTransport).RaftSnapshot.func1.1(0x302c780, 0xc4217c1690, 0xc421306960, 0x2ae12bc432c8, 0xc420a8c4b0, 0x65a4d0, 0xc420c53738)
[02:58:32] :		 [TestGossipHandlesReplacedNode] 	/go/src/github.com/cockroachdb/cockroach/pkg/storage/raft_transport.go:362 +0x258
[02:58:32] :		 [TestGossipHandlesReplacedNode] github.com/cockroachdb/cockroach/pkg/storage.(*RaftTransport).RaftSnapshot.func1(0x2ae12bc432c8, 0xc420a8c4b0)
[02:58:32] :		 [TestGossipHandlesReplacedNode] 	/go/src/github.com/cockroachdb/cockroach/pkg/storage/raft_transport.go:363 +0x75
[02:58:32] :		 [TestGossipHandlesReplacedNode] github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunAsyncTask.func1(0xc42022a6c0, 0x2cfd03f, 0x19, 0x16c, 0x0, 0x0, 0xc4205de2d0, 0x2ae12bc432c8, 0xc420a8c4b0)
[02:58:32] :		 [TestGossipHandlesReplacedNode] 	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:264 +0xed
[02:58:32] :		 [TestGossipHandlesReplacedNode] created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunAsyncTask
[02:58:32] :		 [TestGossipHandlesReplacedNode] 	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:265 +0x2b0
```

### PR DESCRIPTION
**Pull request by petermattis**
If a snapshot is declined, Store.reserveSnapshot does not return an
error but does return a nil cleanup function. Avoid invoking this nil
cleanup function which was never intended.

Fixes #12249

---
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/12269)

### CODE REVIEW

**Comment by tamird** [comment]
:lgtm:

This fires on non-raft snapshots, right? perhaps it wouldn't be terribly difficult to add a test for this.

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[pkg/storage/store.go, line 2665 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/12269#-KYkirnNMfcWwHnQgSZH:-KYkirnNMfcWwHnQgSZI:buftg1k) ([raw file](https://github.com/cockroachdb/cockroach/blob/846f03e42276e6c23b77ed3e5772c19d2668d15d/pkg/storage/store.go#L2665)):*
> ```Go
> 
> 	ctx := s.AnnotateCtx(stream.Context())
> 	cleanup, err := s.reserveSnapshot(ctx, header, stream)
> ```

perhaps it'd be cleaner to move sending of the `DECLINED` message out to this caller.
```
cleanup, err := s.reserveSnapshot(ctx, header)
if err != nil {
  return err
}
if cleanup == nil {
  return stream.Send(....)
}
defer cleanup()
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/12269#-:-KYkjCxg5zC2c7DiU9X2:b-q3jxdo)*

**Comment by bdarnell** [comment]
I think it would be better to change the interface of `reserveSnapshot`. Either make the sending of the message the caller's responsibility as Tamir suggested or return a "snapshot declined" error after sending the decline message.

**Comment by petermattis** [comment]
We already have tests failing reliably for this, just not 100% of the time.

---

Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[pkg/storage/store.go, line 2665 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/12269#-KYkirnNMfcWwHnQgSZH:-KYkmyDfB0-haIYrAgM8:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/846f03e42276e6c23b77ed3e5772c19d2668d15d/pkg/storage/store.go#L2665)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

perhaps it'd be cleaner to move sending of the `DECLINED` message out to this caller.
```
cleanup, err := s.reserveSnapshot(ctx, header)
if err != nil {
  return err
}
if cleanup == nil {
  return stream.Send(....)
}
defer cleanup()
```
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/12269#-:-KYkn4HKsUs8fDczI6dT:b-3vrhi7)*

**Comment by tamird** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/12269)*

**Comment by tamird** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[pkg/storage/store.go, line 2628 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/12269#-KYko9iZWIOBTVz7Yyng:-KYko9iZWIOBTVz7Yynh:bnak13w) ([raw file](https://github.com/cockroachdb/cockroach/blob/a3f722770ca961f36573f8722d6f32c3007952b5/pkg/storage/store.go#L2628)):*
> ```Go
> 
> func (s *Store) reserveSnapshot(
> 	ctx context.Context, header *SnapshotRequest_Header, stream SnapshotResponseStream,
> ```

remove the third argument

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/12269)*

**Comment by petermattis** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[pkg/storage/store.go, line 2628 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/12269#-KYko9iZWIOBTVz7Yyng:-KYkoa6G-Z3pi5z6TytT:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/a3f722770ca961f36573f8722d6f32c3007952b5/pkg/storage/store.go#L2628)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

remove the third argument
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/12269)*

**Comment by tamird** [comment]
Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/12269)*

File: pkg/storage/store.go [hunk 1]
```diff
@@ -2625,7 +2625,7 @@ func (s *Store) maybeUpdateTransaction(
 }
 
 func (s *Store) reserveSnapshot(
```
Comment (bdarnell) [inline pkg/storage/store.go]: Needs a comment explaining the `(nil, nil)` return value.

**Review by bdarnell — APPROVED** [review]

File: pkg/storage/store.go (hunk 1 above)
Comment (petermattis) [inline pkg/storage/store.go]: Done.
