### PR TITLE
roachtest: deflake replicate/wide

### LINKED ISSUE #36788: roachtest: replicate/wide failed
SHA: https://github.com/cockroachdb/cockroach/commits/509c5b130fb1ad0042beb74e083817aa68e4fc92

Parameters:

To repro, try:

```
# Don't forget to check out a clean suitable branch and experiment with the
# stress invocation until the desired results present themselves. For example,
# using stress instead of stressrace and passing the '-p' stressflag which
# controls concurrency.
./scripts/gceworker.sh start && ./scripts/gceworker.sh mosh
cd ~/go/src/github.com/cockroachdb/cockroach && \
stdbuf -oL -eL \
make stressrace TESTS=replicate/wide PKG=roachtest TESTTIMEOUT=5m STRESSFLAGS='-maxtime 20m -timeout 10m' 2>&1 | tee /tmp/stress.log
```

Failed test: https://teamcity.cockroachdb.com/viewLog.html?buildId=1237002&tab=buildLog

```
The test failed on release-19.1:
	allocator.go:354,allocator.go:362,test.go:1237: 9 unavailable ranges
	cluster.go:953,context.go:90,cluster.go:942,asm_amd64.s:522,panic.go:397,test.go:785,test.go:775,allocator.go:354,allocator.go:362,test.go:1237: dead node detection: /home/agent/work/.go/src/github.com/cockroachdb/cockroach/bin/roachprod monitor teamcity-1237002-replicate-wide --oneshot --ignore-empty-nodes: exit status 1 2: 3180
		6: 3601
		5: 3236
		3: 3258
		1: 3357
		4: 3228
		9: dead
		7: dead
		8: dead
		Error:  8: dead

```

### PR DESCRIPTION
**Pull request by petermattis**
Only fatal on non-zero unavailable ranges if that condition persists for
more than 30s.

Fixes #36788

Release note: None

### CODE REVIEW

**Comment by petermattis** [comment]
I'm running this in a loop right now. I'm not positive it fixes #36788, but there isn't much else to be done until this reproduces again.

File: pkg/cmd/roachtest/allocator.go [hunk 1]
```diff
@@ -351,7 +351,10 @@ FROM crdb_internal.kv_store_status
 			}
 			t.l.Printf("%d unavailable, %d under-replicated ranges\n", unavailable, underReplicated)
 			if unavailable != 0 {
-				t.Fatalf("%d unavailable ranges", unavailable)
+				if timeutil.Since(start) >= 30*time.Second {
```
Comment (tbg) [inline pkg/cmd/roachtest/allocator.go]: Add a comment here that a freshly started cluster might show some ranges as unavailable even though they're not.

**Review by tbg — APPROVED** [review]
Thanks!

File: pkg/cmd/roachtest/allocator.go (hunk 1 above)
Comment (petermattis) [reply pkg/cmd/roachtest/allocator.go]: Done.

**Comment by petermattis** [comment]
I haven't been able to reproduce the non-zero unavailable ranges yet (10 attempts so far). I'll keep trying, but might as well get bors going.

bors r=tbg

**Comment by petermattis** [comment]
Hmm, bors doesn't seem to have picked this up. Trying again.

bors r=tbg
