### PR TITLE
roachtest: update activerecord blocklist and ignore list

### LINKED ISSUE #84955: roachtest: activerecord failed
roachtest.activerecord [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/5840461?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/5840461?buildTab=artifacts#/activerecord) on master @ [8fd5b3500796fae41c07fffd4246648b349b6460](https://github.com/cockroachdb/cockroach/commits/8fd5b3500796fae41c07fffd4246648b349b6460):

```
test artifacts and logs in: /artifacts/activerecord/run_1
	orm_helpers.go:191,orm_helpers.go:117,activerecord.go:251,test_runner.go:896: 
		Tests run on Cockroach v22.2.0-alpha.00000000-1833-g8fd5b35007
		Tests run against activerecord 7.0.3
		7372 Total Tests Run
		7363 tests passed
		9 tests failed
		27 tests skipped
		5 tests ignored
		0 tests passed unexpectedly
		9 tests failed unexpectedly
		0 tests expected failed but skipped
		0 tests expected failed but not run
		---
		--- FAIL: ActiveRecord::CockroachDB::Migration::PGChangeSchemaTest#test_change_string_to_date (unexpected)
		--- FAIL: BasicsTest#test_default_values_are_deeply_dupped (unexpected)
		--- FAIL: ActiveRecord::CockroachDB::Migration::PGChangeSchemaTest#test_change_type_with_symbol_using_timestamp_with_timestamptz_as_default (unexpected)
		--- PASS: SerializedAttributeTest#test_unexpected_serialized_type (expected)
		--- FAIL: ActiveRecord::CockroachDB::Migration::PGChangeSchemaTest#test_change_type_with_symbol_with_timestamptz (unexpected)
		--- FAIL: ActiveRecord::CockroachDB::Migration::PGChangeSchemaTest#test_change_type_with_array (unexpected)
		--- FAIL: ActiveRecord::CockroachDB::Migration::PGChangeSchemaTest#test_change_type_with_symbol_with_timestamptz_as_default (unexpected)
		--- FAIL: ActiveRecord::CockroachDB::Migration::PGChangeSchemaTest#test_change_type_with_symbol (unexpected)
		--- FAIL: ActiveRecord::CockroachDB::Migration::PGChangeSchemaTest#test_change_type_with_symbol_using_datetime_with_timestamptz_as_default (unexpected)
		--- PASS: SerializedAttributeTestWithYamlSafeLoad#test_unexpected_serialized_type (expected)
		--- FAIL: ActiveRecord::CockroachDB::Migration::PGChangeSchemaTest#test_change_type_with_symbol_using_datetime (unexpected)
		For a full summary look at the activerecord artifacts 
		
		An updated blocklist (activeRecordBlockList22_2) is available in the artifacts' activerecord log
```
<p>Parameters: <code>ROACHTEST_cloud=gce</code>
, <code>ROACHTEST_cpu=4</code>
, <code>ROACHTEST_ssd=0</code>
</p>
<details><summary>Help</summary>
<p>

See: [roachtest README](https://github.com/cockroachdb/cockroach/blob/master/pkg/cmd/roachtest/README.md)

See: [How To Investigate \(internal\)](https://cockroachlabs.atlassian.net/l/c/SSSBr8c7)

</p>
</details>
<details><summary>Same failure on other branches</summary>
<p>

- #84954 roachtest: activerecord failed [C-test-failure O-roachtest O-robot branch-release-21.1 release-blocker]
- #82805 roachtest: activerecord failed [C-test-failure O-roachtest O-robot T-sql-experience branch-release-22.1]
- #81088 roachtest: activerecord failed [C-test-failure O-roachtest O-robot T-sql-experience branch-release-21.2]
</p>
</details>
/cc @cockroachdb/sql-experience
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*activerecord.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)
</sub>

Jira issue: CRDB-17969

### PR DESCRIPTION
**Pull request by andyyang890**
This patch updates the blocklist and ignore list for the
activerecord roachtest. This patch also eliminates the
per-version lists since each release branch uses their
own list now.

Fixes #84955

Release note: None

### CODE REVIEW

**Review by ZhouXing19 — APPROVED** [review]
LGTM!

File: pkg/cmd/roachtest/tests/activerecord_blocklist.go [hunk 1]
```diff
@@ -30,51 +21,76 @@ var activeRecordBlocklists = blocklistsForVersion{
...
-	"IgnoreFixturesTest#test_ignores_parrots_fixtures":                                       "flaky - FK constraint violated sometimes when loading all fixture data",
-}
-
-var activeRecordIgnoreList21_1 = blocklist{
-	"ActiveRecord::CockroachDB::UnloggedTablesTest#test_gracefully_handles_temporary_tables": "modified to pass on 20.2",
-	"CockroachDB::PostgresqlIntervalTest#test_interval_type":                                 "flaky",
-	"FixturesTest#test_create_fixtures":                                                      "flaky - FK constraint violated sometimes when loading all fixture data",
-	"IgnoreFixturesTest#test_ignores_books_fixtures":                                         "flaky - FK constraint violated sometimes when loading all fixture data",
-	"IgnoreFixturesTest#test_ignores_parrots_fixtures":                                       "flaky - FK constraint violated sometimes when loading all fixture data",
+var activeRecordBlocklist = blocklist{
```
Comment (rafiss) [inline pkg/cmd/roachtest/tests/activerecord_blocklist.go:24]: for the ones that have issues, the `value` of the map can just be the issue number

Comment (andyyang890) [reply pkg/cmd/roachtest/tests/activerecord_blocklist.go:24]: Fixed!

**Review by rafiss — APPROVED** [review]

**Comment by rafiss** [comment]
lgtm, thanks for these updates!

**Comment by andyyang890** [comment]
TFTRs!

bors r=ZhouXing19,rafiss

**Comment by andyyang890** [comment]
Fixed a few typos

bors r=ZhouXing19,rafiss
