### PR TITLE
storage: Cancel pending commands as soon as we get ReplicaTooOldError

### LINKED ISSUE #10698: : TestSplitSnapshotRace_SplitWins failed under stress
SHA: https://github.com/cockroachdb/cockroach/commits/76eb17b783303b2dc3055b2252a1b7814b084a6d

Stress build found a failed test:

```
I161115 08:55:59.375531 25783 storage/engine/rocksdb.go:340  opening in memory rocksdb instance
I161115 08:55:59.376604 25783 gossip/gossip.go:241  [n?] initial resolvers: []
W161115 08:55:59.376693 25783 gossip/gossip.go:1117  [n?] no resolvers found; use --join to specify a connected node
I161115 08:55:59.376827 25783 base/node_id.go:62  NodeID set to 1
I161115 08:55:59.391411 25783 storage/store.go:1188  [n1,s1]: failed initial metrics computation: [n1,s1]: system config not yet available
I161115 08:55:59.391605 25783 gossip/gossip.go:283  [n1] NodeDescriptor set to node_id:1 address:<network_field:"tcp" address_field:"127.0.0.1:39450" > attrs:<> locality:<> 
I161115 08:55:59.393279 25816 storage/replica_proposal.go:328  [s1,r1/1:/M{in-ax}] new range lease replica {1 1 1} 1970-01-01 00:00:00 +0000 UTC 900.000124ms following replica {0 0 0} 1970-01-01 00:00:00 +0000 UTC 0s [physicalTime=1970-01-01 00:00:00.000000123 +0000 UTC]
I161115 08:55:59.400319 25783 storage/engine/rocksdb.go:340  opening in memory rocksdb instance
I161115 08:55:59.401428 25783 gossip/gossip.go:241  [n?] initial resolvers: [127.0.0.1:39450]
W161115 08:55:59.401515 25783 gossip/gossip.go:1119  [n?] no incoming or outgoing connections
I161115 08:55:59.401643 25783 base/node_id.go:62  NodeID set to 2
I161115 08:55:59.406929 25713 gossip/client.go:125  [n2] started gossip client to 127.0.0.1:39450
I161115 08:55:59.409693 25783 gossip/gossip.go:283  [n2] NodeDescriptor set to node_id:2 address:<network_field:"tcp" address_field:"127.0.0.1:54139" > attrs:<> locality:<> 
I161115 08:55:59.410173 25783 storage/engine/rocksdb.go:340  opening in memory rocksdb instance
I161115 08:55:59.411144 25783 gossip/gossip.go:241  [n?] initial resolvers: [127.0.0.1:39450]
W161115 08:55:59.411250 25783 gossip/gossip.go:1119  [n?] no incoming or outgoing connections
I161115 08:55:59.411394 25783 base/node_id.go:62  NodeID set to 3
I161115 08:55:59.424993 25783 storage/store.go:1188  [n3,s3]: failed initial metrics computation: [n3,s3]: system config not yet available
I161115 08:55:59.425379 25783 gossip/gossip.go:283  [n3] NodeDescriptor set to node_id:3 address:<network_field:"tcp" address_field:"127.0.0.1:42787" > attrs:<> locality:<> 
I161115 08:55:59.428071 25783 storage/engine/rocksdb.go:340  opening in memory rocksdb instance
I161115 08:55:59.429126 25783 gossip/gossip.go:241  [n?] initial resolvers: [127.0.0.1:39450]
W161115 08:55:59.429251 25783 gossip/gossip.go:1119  [n?] no incoming or outgoing connections
I161115 08:55:59.429427 25783 base/node_id.go:62  NodeID set to 4
I161115 08:55:59.430020 25989 gossip/client.go:125  [n3] started gossip client to 127.0.0.1:39450
I161115 08:55:59.435114 25129 gossip/client.go:125  [n4] started gossip client to 127.0.0.1:39450
I161115 08:55:59.461455 25783 gossip/gossip.go:283  [n4] NodeDescriptor set to node_id:4 address:<network_field:"tcp" address_field:"127.0.0.1:49310" > attrs:<> locality:<> 
I161115 08:55:59.462863 25783 storage/engine/rocksdb.go:340  opening in memory rocksdb instance
I161115 08:55:59.466654 25783 gossip/gossip.go:241  [n?] initial resolvers: [127.0.0.1:39450]
W161115 08:55:59.466743 25783 gossip/gossip.go:1119  [n?] no incoming or outgoing connections
I161115 08:55:59.466894 25783 base/node_id.go:62  NodeID set to 5
I161115 08:55:59.475096 25993 gossip/client.go:125  [n5] started gossip client to 127.0.0.1:39450
I161115 08:55:59.475504 26132 gossip/server.go:263  [n1] refusing gossip from node 5 (max 3 conns); forwarding to 4 ({tcp 127.0.0.1:49310})
I161115 08:55:59.479229 26132 gossip/server.go:263  [n1] refusing gossip from node 5 (max 3 conns); forwarding to 2 ({tcp 127.0.0.1:54139})
I161115 08:55:59.479695 26132 gossip/server.go:263  [n1] refusing gossip from node 5 (max 3 conns); forwarding to 2 ({tcp 127.0.0.1:54139})
I161115 08:55:59.480040 25993 gossip/client.go:130  [n5] closing client to node 1 (127.0.0.1:39450): received forward from node 1 to 4 (127.0.0.1:49310)
I161115 08:55:59.480988 25783 storage/store.go:1188  [n5,s5]: failed initial metrics computation: [n5,s5]: system config not yet available
I161115 08:55:59.481187 25783 gossip/gossip.go:283  [n5] NodeDescriptor set to node_id:5 address:<network_field:"tcp" address_field:"127.0.0.1:54068" > attrs:<> locality:<> 
I161115 08:55:59.481733 25783 storage/engine/rocksdb.go:340  opening in memory rocksdb instance
I161115 08:55:59.482832 25783 gossip/gossip.go:241  [n?] initial resolvers: [127.0.0.1:39450]
W161115 08:55:59.482955 25783 gossip/gossip.go:1119  [n?] no incoming or outgoing connections
I161115 08:55:59.483100 25783 base/node_id.go:62  NodeID set to 6
I161115 08:55:59.486224 26168 gossip/client.go:125  [n5] started gossip client to 127.0.0.1:49310
I161115 08:55:59.487925 26037 gossip/client.go:125  [n6] started gossip client to 127.0.0.1:39450
I161115 08:55:59.488528 26186 gossip/server.go:263  [n1] refusing gossip from node 6 (max 3 conns); forwarding to 2 ({tcp 127.0.0.1:54139})
I161115 08:55:59.496553 26037 gossip/client.go:130  [n6] closing client to node 1 (127.0.0.1:39450): received forward from node 1 to 2 (127.0.0.1:54139)
I161115 08:55:59.497778 26040 gossip/client.go:125  [n6] started gossip client to 127.0.0.1:54139
I161115 08:55:59.505339 25783 gossip/gossip.go:283  [n6] NodeDescriptor set to node_id:6 address:<network_field:"tcp" address_field:"127.0.0.1:35846" > attrs:<> locality:<> 
I161115 08:55:59.515963 25783 storage/replica_command.go:2361  [s1,r1/1:/M{in-ax}] initiating a split of this range at key /System/Max [r2]
E161115 08:55:59.545995 25836 storage/queue.go:579  [replicate,s1,r1/1:/{Min-System/Max}] purgatory: 0 of 0 stores with an attribute matching []; likely not enough nodes in cluster
I161115 08:55:59.546345 25783 storage/replica_raftstorage.go:445  [s1,r2/1:/{System/Max-Max}] generated snapshot 589f1663 at index 11 in 151.202µs.
E161115 08:55:59.547302 25836 storage/queue.go:579  [replicate,s1,r2/1:/{System/Max-Max}] purgatory: 0 of 0 stores with an attribute matching []; likely not enough nodes in cluster
I161115 08:55:59.549223 26272 storage/replica_raftstorage.go:589  [s2,r2/?:{-}] applying preemptive snapshot at index 11 (id=589f1663, encoded size=16, 1 rocksdb batches, 1 log entries)
I161115 08:55:59.550334 26272 storage/replica_raftstorage.go:592  [s2,r2/?:/{System/Max-Max}] applied preemptive snapshot in 0.001s
I161115 08:55:59.550613 25783 storage/store.go:3134  [s1,r2/1:/{System/Max-Max}] streamed snapshot: kv pairs: 30, log entries: 1
I161115 08:55:59.555236 25783 storage/replica_command.go:3245  [s1,r2/1:/{System/Max-Max}] change replicas: read existing descriptor range_id:2 start_key:"\005" end_key:"\377\377" replicas:<node_id:1 store_id:1 replica_id:1 > next_replica_id:2 
W161115 08:55:59.558414 26308 storage/stores.go:218  range not contained in one range: [/Meta2/Max,"\x05\x00"), but have [/Min,/System/Max)
I161115 08:55:59.594116 26311 storage/replica.go:2055  [s1,r2/1:/{System/Max-Max}] proposing ADD_REPLICA {NodeID:2 StoreID:2 ReplicaID:2}: [{NodeID:1 StoreID:1 ReplicaID:1} {NodeID:2 StoreID:2 ReplicaID:2}]
W161115 08:55:59.597490 26323 storage/intent_resolver.go:314  [n1,s1,r1/1:/{Min-System/Max}]: failed to push during intent resolution: failed to push "change-replica" id=41267578 key=/Local/Range/"\x05"/RangeDescriptor rw=true pri=0.00003958 iso=SERIALIZABLE stat=PENDING epo=0 ts=0.000000123,178 orig=0.000000123,178 max=0.000000123,178 wto=false rop=false
I161115 08:55:59.599584 25783 storage/replica_raftstorage.go:445  [s1,r2/1:/{System/Max-Max}] generated snapshot c1fea976 at index 14 in 137.502µs.
I161115 08:55:59.601475 25783 storage/store.go:3134  [s1,r2/1:/{System/Max-Max}] streamed snapshot: kv pairs: 32, log entries: 4
I161115 08:55:59.602391 26239 storage/replica_raftstorage.go:589  [s3,r2/?:{-}] applying preemptive snapshot at index 14 (id=c1fea976, encoded size=16, 1 rocksdb batches, 4 log entries)
I161115 08:55:59.603467 26239 storage/replica_raftstorage.go:592  [s3,r2/?:/{System/Max-Max}] applied preemptive snapshot in 0.001s
I161115 08:55:59.605673 25783 storage/replica_command.go:3245  [s1,r2/1:/{System/Max-Max}] change replicas: read existing descriptor range_id:2 start_key:"\005" end_key:"\377\377" replicas:<node_id:1 store_id:1 replica_id:1 > replicas:<node_id:2 store_id:2 replica_id:2 > next_replica_id:3 
I161115 08:55:59.608919 26340 storage/raft_transport.go:437  raft transport stream to node 1 established
I161115 08:55:59.628092 26320 storage/replica.go:2055  [s1,r2/1:/{System/Max-Max}] proposing ADD_REPLICA {NodeID:3 StoreID:3 ReplicaID:3}: [{NodeID:1 StoreID:1 ReplicaID:1} {NodeID:2 StoreID:2 ReplicaID:2} {NodeID:3 StoreID:3 ReplicaID:3}]
I161115 08:55:59.652225 25783 storage/replica_raftstorage.go:445  [s1,r2/1:/{System/Max-Max}] generated snapshot 6911d489 at index 17 in 139.802µs.
I161115 08:55:59.657911 25783 storage/store.go:3134  [s1,r2/1:/{System/Max-Max}] streamed snapshot: kv pairs: 33, log entries: 7
I161115 08:55:59.658751 26345 storage/replica_raftstorage.go:589  [s4,r2/?:{-}] applying preemptive snapshot at index 17 (id=6911d489, encoded size=16, 1 rocksdb batches, 7 log entries)
I161115 08:55:59.659916 26345 storage/replica_raftstorage.go:592  [s4,r2/?:/{System/Max-Max}] applied preemptive snapshot in 0.001s
I161115 08:55:59.662090 25783 storage/replica_command.go:3245  [s1,r2/1:/{System/Max-Max}] change replicas: read existing descriptor range_id:2 start_key:"\005" end_key:"\377\377" replicas:<node_id:1 store_id:1 replica_id:1 > replicas:<node_id:2 store_id:2 replica_id:2 > replicas:<node_id:3 store_id:3 replica_id:3 > next_replica_id:4 
I161115 08:55:59.676099 26281 storage/raft_transport.go:437  raft transport stream to node 1 established
I161115 08:55:59.682866 26351 storage/replica.go:2055  [s1,r2/1:/{System/Max-Max}] proposing ADD_REPLICA {NodeID:4 StoreID:4 ReplicaID:4}: [{NodeID:1 StoreID:1 ReplicaID:1} {NodeID:2 StoreID:2 ReplicaID:2} {NodeID:3 StoreID:3 ReplicaID:3} {NodeID:4 StoreID:4 ReplicaID:4}]
I161115 08:55:59.702712 26389 storage/raft_transport.go:437  raft transport stream to node 1 established
I161115 08:55:59.723149 25783 storage/replica_command.go:3245  [s1,r2/1:/{System/Max-Max}] change replicas: read existing descriptor range_id:2 start_key:"\005" end_key:"\377\377" replicas:<node_id:1 store_id:1 replica_id:1 > replicas:<node_id:2 store_id:2 replica_id:2 > replicas:<node_id:3 store_id:3 replica_id:3 > replicas:<node_id:4 store_id:4 replica_id:4 > next_replica_id:5 
I161115 08:55:59.735414 26378 storage/replica.go:2055  [s1,r2/1:/{System/Max-Max}] proposing REMOVE_REPLICA {NodeID:1 StoreID:1 ReplicaID:1}: [{NodeID:4 StoreID:4 ReplicaID:4} {NodeID:2 StoreID:2 ReplicaID:2} {NodeID:3 StoreID:3 ReplicaID:3}]
I161115 08:55:59.741005 26280 storage/store.go:2986  [s1,r2/1:/{System/Max-Max}] added to replica GC queue (peer suggestion)
E161115 08:55:59.762261 25783 storage/client_test.go:997  engine 4: missing key "a"
E161115 08:55:59.762382 25783 storage/client_test.go:997  engine 5: missing key "a"
E161115 08:55:59.762632 25783 storage/client_test.go:997  engine 4: missing key "a"
E161115 08:55:59.762700 25783 storage/client_test.go:997  engine 5: missing key "a"
E161115 08:55:59.762926 25783 storage/client_test.go:997  engine 4: missing key "a"
E161115 08:55:59.762995 25783 storage/client_test.go:997  engine 5: missing key "a"
E161115 08:55:59.763209 25783 storage/client_test.go:997  engine 4: missing key "a"
E161115 08:55:59.763274 25783 storage/client_test.go:997  engine 5: missing key "a"
E161115 08:55:59.763467 25783 storage/client_test.go:997  engine 4: missing key "a"
E161115 08:55:59.763525 25783 storage/client_test.go:997  engine 5: missing key "a"
E161115 08:55:59.763795 25783 storage/client_test.go:997  engine 4: missing key "a"
E161115 08:55:59.763888 25783 storage/client_test.go:997  engine 5: missing key "a"
E161115 08:55:59.764128 25783 storage/client_test.go:997  engine 4: missing key "a"
E161115 08:55:59.764206 25783 storage/client_test.go:997  engine 5: missing key "a"
E161115 08:55:59.764407 25783 storage/client_test.go:997  engine 4: missing key "a"
E161115 08:55:59.764494 25783 storage/client_test.go:997  engine 5: missing key "a"
E161115 08:55:59.765027 25783 storage/client_test.go:997  engine 4: missing key "a"
E161115 08:55:59.765101 25783 storage/client_test.go:997  engine 5: missing key "a"
E161115 08:55:59.765341 25783 storage/client_test.go:997  engine 4: missing key "a"
E161115 08:55:59.765400 25783 storage/client_test.go:997  engine 5: missing key "a"
E161115 08:55:59.765591 25783 storage/client_test.go:997  engine 4: missing key "a"
E161115 08:55:59.765648 25783 storage/client_test.go:997  engine 5: missing key "a"
E161115 08:55:59.765852 25783 storage/client_test.go:997  engine 4: missing key "a"
E161115 08:55:59.765917 25783 storage/client_test.go:997  engine 5: missing key "a"
E161115 08:55:59.766137 25783 storage/client_test.go:997  engine 4: missing key "a"
E161115 08:55:59.766226 25783 storage/client_test.go:997  engine 5: missing key "a"
E161115 08:55:59.766434 25783 storage/client_test.go:997  engine 4: missing key "a"
E161115 08:55:59.766488 25783 storage/client_test.go:997  engine 5: missing key "a"
E161115 08:55:59.766695 25783 storage/client_test.go:997  engine 4: missing key "a"
E161115 08:55:59.766760 25783 storage/client_test.go:997  engine 5: missing key "a"
E161115 08:55:59.767081 25783 storage/client_test.go:997  engine 4: missing key "a"
E161115 08:55:59.767143 25783 storage/client_test.go:997  engine 5: missing key "a"
E161115 08:55:59.767478 25783 storage/client_test.go:997  engine 4: missing key "a"
E161115 08:55:59.767564 25783 storage/client_test.go:997  engine 5: missing key "a"
E161115 08:55:59.767874 25783 storage/client_test.go:997  engine 4: missing key "a"
E161115 08:55:59.767943 25783 storage/client_test.go:997  engine 5: missing key "a"
E161115 08:55:59.768374 25783 storage/client_test.go:997  engine 4: missing key "a"
E161115 08:55:59.768444 25783 storage/client_test.go:997  engine 5: missing key "a"
E161115 08:55:59.768952 25783 storage/client_test.go:997  engine 4: missing key "a"
E161115 08:55:59.769046 25783 storage/client_test.go:997  engine 5: missing key "a"
E161115 08:55:59.769827 25783 storage/client_test.go:997  engine 4: missing key "a"
E161115 08:55:59.769901 25783 storage/client_test.go:997  engine 5: missing key "a"
E161115 08:55:59.772146 25783 storage/client_test.go:997  engine 4: missing key "a"
E161115 08:55:59.772255 25783 storage/client_test.go:997  engine 5: missing key "a"
E161115 08:55:59.774795 25783 storage/client_test.go:997  engine 4: missing key "a"
E161115 08:55:59.774864 25783 storage/client_test.go:997  engine 5: missing key "a"
E161115 08:55:59.779544 25783 storage/client_test.go:997  engine 4: missing key "a"
E161115 08:55:59.779629 25783 storage/client_test.go:997  engine 5: missing key "a"
E161115 08:55:59.798825 25783 storage/client_test.go:997  engine 4: missing key "a"
E161115 08:55:59.798897 25783 storage/client_test.go:997  engine 5: missing key "a"
E161115 08:55:59.816055 25783 storage/client_test.go:997  engine 4: missing key "a"
E161115 08:55:59.816130 25783 storage/client_test.go:997  engine 5: missing key "a"
E161115 08:55:59.850048 25783 storage/client_test.go:997  engine 4: missing key "a"
E161115 08:55:59.850127 25783 storage/client_test.go:997  engine 5: missing key "a"
E161115 08:55:59.917611 25783 storage/client_test.go:997  engine 4: missing key "a"
E161115 08:55:59.917694 25783 storage/client_test.go:997  engine 5: missing key "a"
I161115 08:56:00.008950 26476 storage/raft_transport.go:437  raft transport stream to node 3 established
I161115 08:56:00.009218 26477 storage/raft_transport.go:437  raft transport stream to node 4 established
I161115 08:56:00.011099 26498 storage/raft_transport.go:437  raft transport stream to node 2 established
I161115 08:56:00.016842 26460 storage/raft_transport.go:437  raft transport stream to node 2 established
I161115 08:56:00.020594 25900 storage/replica_proposal.go:377  [s2,r2/2:/{System/Max-Max}] range [n2,s2,r2/2:/{System/Max-Max}]: transferring raft leadership to replica ID 4
I161115 08:56:00.023389 26017 storage/replica_proposal.go:328  [s4,r2/4:/{System/Max-Max}] new range lease replica {4 4 4} 1970-01-01 00:00:00.900000124 +0000 UTC 3.600000004s following replica {1 1 1} 1970-01-01 00:00:00 +0000 UTC 900.000124ms [physicalTime=1970-01-01 00:00:03.600000127 +0000 UTC]
I161115 08:56:00.028441 26464 storage/raft_transport.go:437  raft transport stream to node 3 established
I161115 08:56:00.030969 26428 storage/raft_transport.go:437  raft transport stream to node 4 established
E161115 08:56:00.054691 25783 storage/client_test.go:997  engine 4: missing key "a"
E161115 08:56:00.054776 25783 storage/client_test.go:997  engine 5: missing key "a"
W161115 08:56:00.189274 25817 raft/raft.go:794  [s1,r2/1:/{System/Max-Max}] 1 stepped down to follower since quorum is not active
E161115 08:56:00.323599 25783 storage/client_test.go:997  engine 4: missing key "a"
E161115 08:56:00.323681 25783 storage/client_test.go:997  engine 5: missing key "a"
E161115 08:56:00.860936 25783 storage/client_test.go:997  engine 4: missing key "a"
E161115 08:56:00.861031 25783 storage/client_test.go:997  engine 5: missing key "a"
E161115 08:56:01.861420 25783 storage/client_test.go:997  engine 4: missing key "a"
E161115 08:56:01.861502 25783 storage/client_test.go:997  engine 5: missing key "a"
E161115 08:56:02.861918 25783 storage/client_test.go:997  engine 4: missing key "a"
E161115 08:56:02.861999 25783 storage/client_test.go:997  engine 5: missing key "a"
E161115 08:56:03.862371 25783 storage/client_test.go:997  engine 4: missing key "a"
E161115 08:56:03.862445 25783 storage/client_test.go:997  engine 5: missing key "a"
E161115 08:56:04.862844 25783 storage/client_test.go:997  engine 4: missing key "a"
E161115 08:56:04.862930 25783 storage/client_test.go:997  engine 5: missing key "a"
E161115 08:56:05.863328 25783 storage/client_test.go:997  engine 4: missing key "a"
E161115 08:56:05.863412 25783 storage/client_test.go:997  engine 5: missing key "a"
E161115 08:56:06.863847 25783 storage/client_test.go:997  engine 4: missing key "a"
E161115 08:56:06.863954 25783 storage/client_test.go:997  engine 5: missing key "a"
E161115 08:56:07.870298 25783 storage/client_test.go:997  engine 4: missing key "a"
E161115 08:56:07.870387 25783 storage/client_test.go:997  engine 5: missing key "a"
E161115 08:56:08.871332 25783 storage/client_test.go:997  engine 4: missing key "a"
E161115 08:56:08.871427 25783 storage/client_test.go:997  engine 5: missing key "a"
E161115 08:56:09.871767 25783 storage/client_test.go:997  engine 4: missing key "a"
E161115 08:56:09.871847 25783 storage/client_test.go:997  engine 5: missing key "a"
E161115 08:56:10.872307 25783 storage/client_test.go:997  engine 4: missing key "a"
E161115 08:56:10.872392 25783 storage/client_test.go:997  engine 5: missing key "a"
E161115 08:56:11.872800 25783 storage/client_test.go:997  engine 4: missing key "a"
E161115 08:56:11.872887 25783 storage/client_test.go:997  engine 5: missing key "a"
E161115 08:56:12.873303 25783 storage/client_test.go:997  engine 4: missing key "a"
E161115 08:56:12.873392 25783 storage/client_test.go:997  engine 5: missing key "a"
E161115 08:56:13.873990 25783 storage/client_test.go:997  engine 4: missing key "a"
E161115 08:56:13.874073 25783 storage/client_test.go:997  engine 5: missing key "a"
E161115 08:56:14.874506 25783 storage/client_test.go:997  engine 4: missing key "a"
E161115 08:56:14.874591 25783 storage/client_test.go:997  engine 5: missing key "a"
E161115 08:56:15.874967 25783 storage/client_test.go:997  engine 4: missing key "a"
E161115 08:56:15.875048 25783 storage/client_test.go:997  engine 5: missing key "a"
E161115 08:56:16.876284 25783 storage/client_test.go:997  engine 4: missing key "a"
E161115 08:56:16.876353 25783 storage/client_test.go:997  engine 5: missing key "a"
E161115 08:56:17.876718 25783 storage/client_test.go:997  engine 4: missing key "a"
E161115 08:56:17.876794 25783 storage/client_test.go:997  engine 5: missing key "a"
E161115 08:56:18.877305 25783 storage/client_test.go:997  engine 4: missing key "a"
E161115 08:56:18.877388 25783 storage/client_test.go:997  engine 5: missing key "a"
E161115 08:56:19.877800 25783 storage/client_test.go:997  engine 4: missing key "a"
E161115 08:56:19.877892 25783 storage/client_test.go:997  engine 5: missing key "a"
E161115 08:56:20.878311 25783 storage/client_test.go:997  engine 4: missing key "a"
E161115 08:56:20.878393 25783 storage/client_test.go:997  engine 5: missing key "a"
E161115 08:56:21.878789 25783 storage/client_test.go:997  engine 4: missing key "a"
E161115 08:56:21.878869 25783 storage/client_test.go:997  engine 5: missing key "a"
I161115 08:56:22.856262 25895 gossip/gossip.go:1133  [n2] node has connected to cluster via gossip
E161115 08:56:22.879256 25783 storage/client_test.go:997  engine 4: missing key "a"
E161115 08:56:22.879335 25783 storage/client_test.go:997  engine 5: missing key "a"
I161115 08:56:23.493259 26194 gossip/gossip.go:1133  [n6] node has connected to cluster via gossip
I161115 08:56:23.745649 25812 gossip/gossip.go:1133  [n1] node has connected to cluster via gossip
E161115 08:56:23.880727 25783 storage/client_test.go:997  engine 4: missing key "a"
E161115 08:56:23.880814 25783 storage/client_test.go:997  engine 5: missing key "a"
E161115 08:56:24.881225 25783 storage/client_test.go:997  engine 4: missing key "a"
E161115 08:56:24.881304 25783 storage/client_test.go:997  engine 5: missing key "a"
E161115 08:56:25.881663 25783 storage/client_test.go:997  engine 4: missing key "a"
E161115 08:56:25.881740 25783 storage/client_test.go:997  engine 5: missing key "a"
E161115 08:56:26.882081 25783 storage/client_test.go:997  engine 4: missing key "a"
E161115 08:56:26.882161 25783 storage/client_test.go:997  engine 5: missing key "a"
E161115 08:56:27.882584 25783 storage/client_test.go:997  engine 4: missing key "a"
E161115 08:56:27.882664 25783 storage/client_test.go:997  engine 5: missing key "a"
E161115 08:56:28.883043 25783 storage/client_test.go:997  engine 4: missing key "a"
E161115 08:56:28.883124 25783 storage/client_test.go:997  engine 5: missing key "a"
I161115 08:56:29.006841 26079 gossip/gossip.go:1133  [n5] node has connected to cluster via gossip
E161115 08:56:29.883481 25783 storage/client_test.go:997  engine 4: missing key "a"
E161115 08:56:29.883565 25783 storage/client_test.go:997  engine 5: missing key "a"
E161115 08:56:30.884044 25783 storage/client_test.go:997  engine 4: missing key "a"
E161115 08:56:30.884134 25783 storage/client_test.go:997  engine 5: missing key "a"
E161115 08:56:31.886112 25783 storage/client_test.go:997  engine 4: missing key "a"
E161115 08:56:31.886188 25783 storage/client_test.go:997  engine 5: missing key "a"
E161115 08:56:32.886559 25783 storage/client_test.go:997  engine 4: missing key "a"
E161115 08:56:32.886638 25783 storage/client_test.go:997  engine 5: missing key "a"
I161115 08:56:33.668367 25887 gossip/gossip.go:1133  [n3] node has connected to cluster via gossip
E161115 08:56:33.887023 25783 storage/client_test.go:997  engine 4: missing key "a"
E161115 08:56:33.887106 25783 storage/client_test.go:997  engine 5: missing key "a"
I161115 08:56:34.325423 26007 gossip/gossip.go:1133  [n4] node has connected to cluster via gossip
E161115 08:56:34.887502 25783 storage/client_test.go:997  engine 4: missing key "a"
E161115 08:56:34.887598 25783 storage/client_test.go:997  engine 5: missing key "a"
E161115 08:56:35.887985 25783 storage/client_test.go:997  engine 4: missing key "a"
E161115 08:56:35.888068 25783 storage/client_test.go:997  engine 5: missing key "a"
E161115 08:56:36.888445 25783 storage/client_test.go:997  engine 4: missing key "a"
E161115 08:56:36.888523 25783 storage/client_test.go:997  engine 5: missing key "a"
E161115 08:56:37.889142 25783 storage/client_test.go:997  engine 4: missing key "a"
E161115 08:56:37.889221 25783 storage/client_test.go:997  engine 5: missing key "a"
E161115 08:56:38.890716 25783 storage/client_test.go:997  engine 4: missing key "a"
E161115 08:56:38.890803 25783 storage/client_test.go:997  engine 5: missing key "a"
E161115 08:56:39.891195 25783 storage/client_test.go:997  engine 4: missing key "a"
E161115 08:56:39.891285 25783 storage/client_test.go:997  engine 5: missing key "a"
E161115 08:56:40.891653 25783 storage/client_test.go:997  engine 4: missing key "a"
E161115 08:56:40.891751 25783 storage/client_test.go:997  engine 5: missing key "a"
E161115 08:56:41.894851 25783 storage/client_test.go:997  engine 4: missing key "a"
E161115 08:56:41.894929 25783 storage/client_test.go:997  engine 5: missing key "a"
E161115 08:56:42.895299 25783 storage/client_test.go:997  engine 4: missing key "a"
E161115 08:56:42.895377 25783 storage/client_test.go:997  engine 5: missing key "a"
E161115 08:56:43.895716 25783 storage/client_test.go:997  engine 4: missing key "a"
E161115 08:56:43.895820 25783 storage/client_test.go:997  engine 5: missing key "a"
I161115 08:56:44.896886 37069 util/stop/stopper.go:468  quiescing; tasks left:
2      storage/client_test.go:501
1      storage/queue.go:477
W161115 08:56:44.897114 26364 storage/replica.go:1803  [s1,r2/1:/{System/Max-Max}] shutdown cancellation of command PushTxn [/Local/Range/"\x05"/RangeDescriptor,/Min)
I161115 08:56:44.897516 37069 util/stop/stopper.go:468  quiescing; tasks left:
1      storage/queue.go:477
1      storage/client_test.go:501
I161115 08:56:44.897988 37069 util/stop/stopper.go:468  quiescing; tasks left:
1      storage/queue.go:477
E161115 08:56:44.898430 25837 storage/queue.go:568  [replicaGC,s1,r2/1:/{System/Max-Max}] result is ambiguous
I161115 08:56:44.898562 37068 util/stop/stopper.go:396  stop has been called, stopping or quiescing all running tasks
I161115 08:56:44.902314 37068 util/stop/stopper.go:396  stop has been called, stopping or quiescing all running tasks
I161115 08:56:44.903778 37068 util/stop/stopper.go:396  stop has been called, stopping or quiescing all running tasks
I161115 08:56:44.906707 37068 util/stop/stopper.go:396  stop has been called, stopping or quiescing all running tasks
I161115 08:56:44.908410 37068 util/stop/stopper.go:396  stop has been called, stopping or quiescing all running tasks
I161115 08:56:44.910024 37068 util/stop/stopper.go:396  stop has been called, stopping or quiescing all running tasks
I161115 08:56:44.925001 37068 util/stop/stopper.go:396  stop has been called, stopping or quiescing all running tasks
I161115 08:56:44.925956 25991 http2_server.go:276  transport: http2Server.HandleStreams failed to read frame: read tcp 127.0.0.1:54068->127.0.0.1:60489: use of closed network connection
I161115 08:56:44.926027 26182 http2_server.go:276  transport: http2Server.HandleStreams failed to read frame: read tcp 127.0.0.1:35846->127.0.0.1:47072: use of closed network connection
I161115 08:56:44.926149 26073 http2_client.go:1053  transport: http2Client.notifyError got notified that the client transport was broken EOF.
I161115 08:56:44.926393 26156 http2_client.go:1053  transport: http2Client.notifyError got notified that the client transport was broken EOF.
I161115 08:56:44.926704 25952 http2_server.go:276  transport: http2Server.HandleStreams failed to read frame: read tcp 127.0.0.1:49310->127.0.0.1:48799: use of closed network connection
I161115 08:56:44.927911 25921 http2_client.go:1053  transport: http2Client.notifyError got notified that the client transport was broken EOF.
I161115 08:56:44.928538 37055 http2_client.go:1053  transport: http2Client.notifyError got notified that the client transport was broken read tcp 127.0.0.1:32815->127.0.0.1:54068: read: connection reset by peer.
I161115 08:56:44.928633 26158 /go/src/google.golang.org/grpc/clientconn.go:667  grpc: addrConn.resetTransport failed to create client transport: connection error: desc = "transport: dial tcp 127.0.0.1:35846: getsockopt: connection refused"; Reconnecting to {"127.0.0.1:35846" <nil>}
I161115 08:56:44.929179 26075 /go/src/google.golang.org/grpc/clientconn.go:667  grpc: addrConn.resetTransport failed to create client transport: connection error: desc = "transport: dial tcp 127.0.0.1:54068: getsockopt: connection refused"; Reconnecting to {"127.0.0.1:54068" <nil>}
I161115 08:56:44.929727 25712 http2_server.go:276  transport: http2Server.HandleStreams failed to read frame: read tcp 127.0.0.1:54139->127.0.0.1:42830: use of closed network connection
I161115 08:56:44.930300 25790 http2_server.go:276  transport: http2Server.HandleStreams failed to read frame: read tcp 127.0.0.1:39450->127.0.0.1:60984: use of closed network connection
I161115 08:56:44.930657 26158 /go/src/google.golang.org/grpc/clientconn.go:767  grpc: addrConn.transportMonitor exits due to: context canceled
I161115 08:56:44.931115 25960 http2_server.go:276  transport: http2Server.HandleStreams failed to read frame: read tcp 127.0.0.1:42787->127.0.0.1:55920: use of closed network connection
I161115 08:56:44.931208 26003 /go/src/google.golang.org/grpc/clientconn.go:667  grpc: addrConn.resetTransport failed to create client transport: connection error: desc = "transport: dial tcp 127.0.0.1:49310: getsockopt: connection refused"; Reconnecting to {"127.0.0.1:49310" <nil>}
I161115 08:56:44.931272 26003 /go/src/google.golang.org/grpc/clientconn.go:767  grpc: addrConn.transportMonitor exits due to: grpc: the connection is closing
I161115 08:56:44.932099 26075 /go/src/google.golang.org/grpc/clientconn.go:767  grpc: addrConn.transportMonitor exits due to: context canceled
W161115 08:56:44.932514 26177 storage/raft_transport.go:443  raft transport stream to node 2 failed: EOF
W161115 08:56:44.932864 25895 gossip/gossip.go:1119  [n2] no incoming or outgoing connections
W161115 08:56:44.933033 26476 storage/raft_transport.go:443  raft transport stream to node 3 failed: rpc error: code = 13 desc = transport is closing
W161115 08:56:44.933186 26460 storage/raft_transport.go:443  raft transport stream to node 2 failed: rpc error: code = 13 desc = transport is closing
W161115 08:56:44.933386 26389 storage/raft_transport.go:443  raft transport stream to node 1 failed: rpc error: code = 13 desc = transport is closing
W161115 08:56:44.939729 26281 storage/raft_transport.go:443  raft transport stream to node 1 failed: rpc error: code = 13 desc = transport is closing
I161115 08:56:44.940123 37068 util/stop/stopper.go:396  stop has been called, stopping or quiescing all running tasks
I161115 08:56:44.940597 37068 util/stop/stopper.go:396  stop has been called, stopping or quiescing all running tasks
I161115 08:56:44.940782 37068 util/stop/stopper.go:396  stop has been called, stopping or quiescing all running tasks
I161115 08:56:44.941823 37068 util/stop/stopper.go:396  stop has been called, stopping or quiescing all running tasks
I161115 08:56:44.942188 37068 util/stop/stopper.go:396  stop has been called, stopping or quiescing all running tasks
I161115 08:56:44.942357 37068 util/stop/stopper.go:396  stop has been called, stopping or quiescing all running tasks
	<autogenerated>:12: storage/client_split_test.go:935, condition failed to evaluate within 45s: expected [0 1 1 1 0 0], got [1 1 1 1 0 0]
```

### LINKED ISSUE #11709: github.com/cockroachdb/cockroach/pkg/storage: TestSplitSnapshotRace_SnapshotWins failed under stress
SHA: https://github.com/cockroachdb/cockroach/commits/6c69da91b3b660f58d1026ed4bb8a707b559e854

Parameters:
```
COCKROACH_PROPOSER_EVALUATED_KV=false
TAGS=stress
GOFLAGS=
```

Stress build found a failed test: https://teamcity.cockroachdb.com/viewLog.html?buildId=71456&tab=buildLog

```
W161130 08:19:44.337735 44445 storage/store.go:3019  [s2] raft error: node 4 claims to not contain store 4 for replica {4 4 0}: store 4 was not found
I161130 08:19:44.344393 44507 storage/raft_transport.go:437  raft transport stream to node 4 established
W161130 08:19:44.344517 44517 storage/raft_transport.go:258  unable to accept Raft message from {NodeID:5 StoreID:5 ReplicaID:0}: no handler registered for {NodeID:4 StoreID:4 ReplicaID:0}
W161130 08:19:44.344623 44509 storage/store.go:3019  [s5] raft error: node 4 claims to not contain store 4 for replica {4 4 0}: store 4 was not found
I161130 08:19:44.387212 44469 storage/raft_transport.go:437  raft transport stream to node 4 established
W161130 08:19:44.387335 44447 storage/raft_transport.go:258  unable to accept Raft message from {NodeID:2 StoreID:2 ReplicaID:0}: no handler registered for {NodeID:4 StoreID:4 ReplicaID:0}
W161130 08:19:44.387432 44471 storage/store.go:3019  [s2] raft error: node 4 claims to not contain store 4 for replica {4 4 0}: store 4 was not found
I161130 08:19:44.444402 44580 storage/raft_transport.go:437  raft transport stream to node 4 established
W161130 08:19:44.444574 44566 storage/raft_transport.go:258  unable to accept Raft message from {NodeID:5 StoreID:5 ReplicaID:0}: no handler registered for {NodeID:4 StoreID:4 ReplicaID:0}
W161130 08:19:44.444776 44536 storage/store.go:3019  [s5] raft error: node 4 claims to not contain store 4 for replica {4 4 0}: store 4 was not found
I161130 08:19:44.536471 44537 storage/raft_transport.go:437  raft transport stream to node 4 established
W161130 08:19:44.536630 44582 storage/raft_transport.go:258  unable to accept Raft message from {NodeID:2 StoreID:2 ReplicaID:0}: no handler registered for {NodeID:4 StoreID:4 ReplicaID:0}
W161130 08:19:44.536753 44539 storage/store.go:3019  [s2] raft error: node 4 claims to not contain store 4 for replica {4 4 0}: store 4 was not found
I161130 08:19:44.544560 44583 storage/raft_transport.go:437  raft transport stream to node 4 established
W161130 08:19:44.544684 44585 storage/raft_transport.go:258  unable to accept Raft message from {NodeID:5 StoreID:5 ReplicaID:0}: no handler registered for {NodeID:4 StoreID:4 ReplicaID:0}
W161130 08:19:44.544786 44541 storage/store.go:3019  [s5] raft error: node 4 claims to not contain store 4 for replica {4 4 0}: store 4 was not found
I161130 08:19:44.636433 44601 storage/raft_transport.go:437  raft transport stream to node 4 established
W161130 08:19:44.636545 44618 storage/raft_transport.go:258  unable to accept Raft message from {NodeID:2 StoreID:2 ReplicaID:0}: no handler registered for {NodeID:4 StoreID:4 ReplicaID:0}
W161130 08:19:44.636656 44603 storage/store.go:3019  [s2] raft error: node 4 claims to not contain store 4 for replica {4 4 0}: store 4 was not found
I161130 08:19:44.644355 44619 storage/raft_transport.go:437  raft transport stream to node 4 established
W161130 08:19:44.644457 44552 storage/raft_transport.go:258  unable to accept Raft message from {NodeID:5 StoreID:5 ReplicaID:0}: no handler registered for {NodeID:4 StoreID:4 ReplicaID:0}
W161130 08:19:44.644572 44621 storage/store.go:3019  [s5] raft error: node 4 claims to not contain store 4 for replica {4 4 0}: store 4 was not found
I161130 08:19:44.736432 44622 storage/raft_transport.go:437  raft transport stream to node 4 established
W161130 08:19:44.736544 44605 storage/raft_transport.go:258  unable to accept Raft message from {NodeID:2 StoreID:2 ReplicaID:0}: no handler registered for {NodeID:4 StoreID:4 ReplicaID:0}
W161130 08:19:44.736652 44624 storage/store.go:3019  [s2] raft error: node 4 claims to not contain store 4 for replica {4 4 0}: store 4 was not found
I161130 08:19:44.744401 44625 storage/raft_transport.go:437  raft transport stream to node 4 established
W161130 08:19:44.744549 44479 storage/raft_transport.go:258  unable to accept Raft message from {NodeID:5 StoreID:5 ReplicaID:0}: no handler registered for {NodeID:4 StoreID:4 ReplicaID:0}
W161130 08:19:44.744649 44477 storage/store.go:3019  [s5] raft error: node 4 claims to not contain store 4 for replica {4 4 0}: store 4 was not found
I161130 08:19:44.836480 44649 storage/raft_transport.go:437  raft transport stream to node 4 established
W161130 08:19:44.836588 44669 storage/raft_transport.go:258  unable to accept Raft message from {NodeID:2 StoreID:2 ReplicaID:0}: no handler registered for {NodeID:4 StoreID:4 ReplicaID:0}
W161130 08:19:44.836709 44651 storage/store.go:3019  [s2] raft error: node 4 claims to not contain store 4 for replica {4 4 0}: store 4 was not found
I161130 08:19:44.844328 44670 storage/raft_transport.go:437  raft transport stream to node 4 established
W161130 08:19:44.844505 44674 storage/raft_transport.go:258  unable to accept Raft message from {NodeID:5 StoreID:5 ReplicaID:0}: no handler registered for {NodeID:4 StoreID:4 ReplicaID:0}
W161130 08:19:44.844585 44672 storage/store.go:3019  [s5] raft error: node 4 claims to not contain store 4 for replica {4 4 0}: store 4 was not found
I161130 08:19:44.936395 44706 storage/raft_transport.go:437  raft transport stream to node 4 established
W161130 08:19:44.936654 44722 storage/raft_transport.go:258  unable to accept Raft message from {NodeID:2 StoreID:2 ReplicaID:0}: no handler registered for {NodeID:4 StoreID:4 ReplicaID:0}
W161130 08:19:44.936744 44708 storage/store.go:3019  [s2] raft error: node 4 claims to not contain store 4 for replica {4 4 0}: store 4 was not found
I161130 08:19:44.944351 43641 storage/raft_transport.go:437  raft transport stream to node 4 established
W161130 08:19:44.944619 43645 storage/raft_transport.go:258  unable to accept Raft message from {NodeID:5 StoreID:5 ReplicaID:0}: no handler registered for {NodeID:4 StoreID:4 ReplicaID:0}
W161130 08:19:44.944716 43643 storage/store.go:3019  [s5] raft error: node 4 claims to not contain store 4 for replica {4 4 0}: store 4 was not found
I161130 08:19:45.036484 44640 storage/raft_transport.go:437  raft transport stream to node 4 established
W161130 08:19:45.036613 43647 storage/raft_transport.go:258  unable to accept Raft message from {NodeID:2 StoreID:2 ReplicaID:0}: no handler registered for {NodeID:4 StoreID:4 ReplicaID:0}
W161130 08:19:45.036703 44738 storage/store.go:3019  [s2] raft error: node 4 claims to not contain store 4 for replica {4 4 0}: store 4 was not found
I161130 08:19:45.045149 43648 storage/raft_transport.go:437  raft transport stream to node 4 established
W161130 08:19:45.045300 44756 storage/raft_transport.go:258  unable to accept Raft message from {NodeID:5 StoreID:5 ReplicaID:0}: no handler registered for {NodeID:4 StoreID:4 ReplicaID:0}
W161130 08:19:45.045412 44754 storage/store.go:3019  [s5] raft error: node 4 claims to not contain store 4 for replica {4 4 0}: store 4 was not found
I161130 08:19:45.086521 44739 storage/raft_transport.go:437  raft transport stream to node 4 established
W161130 08:19:45.086843 44724 storage/raft_transport.go:258  unable to accept Raft message from {NodeID:2 StoreID:2 ReplicaID:0}: no handler registered for {NodeID:4 StoreID:4 ReplicaID:0}
W161130 08:19:45.086944 44741 storage/store.go:3019  [s2] raft error: node 4 claims to not contain store 4 for replica {4 4 0}: store 4 was not found
E161130 08:19:45.092216 31664 storage/client_test.go:1002  engine 0: missing key "z"
E161130 08:19:45.092256 31664 storage/client_test.go:1002  engine 2: missing key "z"
I161130 08:19:45.145499 44712 storage/raft_transport.go:437  raft transport stream to node 4 established
W161130 08:19:45.145612 44751 storage/raft_transport.go:258  unable to accept Raft message from {NodeID:5 StoreID:5 ReplicaID:0}: no handler registered for {NodeID:4 StoreID:4 ReplicaID:0}
W161130 08:19:45.145700 44714 storage/store.go:3019  [s5] raft error: node 4 claims to not contain store 4 for replica {4 4 0}: store 4 was not found
I161130 08:19:45.236630 44776 storage/raft_transport.go:437  raft transport stream to node 4 established
W161130 08:19:45.236788 44734 storage/raft_transport.go:258  unable to accept Raft message from {NodeID:2 StoreID:2 ReplicaID:0}: no handler registered for {NodeID:4 StoreID:4 ReplicaID:0}
W161130 08:19:45.236884 44778 storage/store.go:3019  [s2] raft error: node 4 claims to not contain store 4 for replica {4 4 0}: store 4 was not found
I161130 08:19:45.244478 44735 storage/raft_transport.go:437  raft transport stream to node 4 established
W161130 08:19:45.244641 44787 storage/raft_transport.go:258  unable to accept Raft message from {NodeID:5 StoreID:5 ReplicaID:0}: no handler registered for {NodeID:4 StoreID:4 ReplicaID:0}
W161130 08:19:45.244772 44737 storage/store.go:3019  [s5] raft error: node 4 claims to not contain store 4 for replica {4 4 0}: store 4 was not found
I161130 08:19:45.286927 44715 storage/raft_transport.go:437  raft transport stream to node 4 established
W161130 08:19:45.287996 44753 storage/raft_transport.go:258  unable to accept Raft message from {NodeID:2 StoreID:2 ReplicaID:0}: no handler registered for {NodeID:4 StoreID:4 ReplicaID:0}
W161130 08:19:45.288091 44717 storage/store.go:3019  [s2] raft error: node 4 claims to not contain store 4 for replica {4 4 0}: store 4 was not found
I161130 08:19:45.294431 44834 storage/raft_transport.go:437  raft transport stream to node 4 established
W161130 08:19:45.294571 44789 storage/raft_transport.go:258  unable to accept Raft message from {NodeID:5 StoreID:5 ReplicaID:0}: no handler registered for {NodeID:4 StoreID:4 ReplicaID:0}
W161130 08:19:45.294686 44836 storage/store.go:3019  [s5] raft error: node 4 claims to not contain store 4 for replica {4 4 0}: store 4 was not found
I161130 08:19:45.436502 44840 storage/raft_transport.go:437  raft transport stream to node 4 established
W161130 08:19:45.436676 44821 storage/raft_transport.go:258  unable to accept Raft message from {NodeID:2 StoreID:2 ReplicaID:0}: no handler registered for {NodeID:4 StoreID:4 ReplicaID:0}
W161130 08:19:45.436793 44842 storage/store.go:3019  [s2] raft error: node 4 claims to not contain store 4 for replica {4 4 0}: store 4 was not found
I161130 08:19:45.444400 44805 storage/raft_transport.go:437  raft transport stream to node 4 established
W161130 08:19:45.444503 44796 storage/raft_transport.go:258  unable to accept Raft message from {NodeID:5 StoreID:5 ReplicaID:0}: no handler registered for {NodeID:4 StoreID:4 ReplicaID:0}
W161130 08:19:45.444613 44807 storage/store.go:3019  [s5] raft error: node 4 claims to not contain store 4 for replica {4 4 0}: store 4 was not found
I161130 08:19:45.536725 44891 storage/raft_transport.go:437  raft transport stream to node 4 established
W161130 08:19:45.536840 44868 storage/raft_transport.go:258  unable to accept Raft message from {NodeID:2 StoreID:2 ReplicaID:0}: no handler registered for {NodeID:4 StoreID:4 ReplicaID:0}
W161130 08:19:45.536975 44825 storage/store.go:3019  [s2] raft error: node 4 claims to not contain store 4 for replica {4 4 0}: store 4 was not found
I161130 08:19:45.544618 44826 storage/raft_transport.go:437  raft transport stream to node 4 established
W161130 08:19:45.544725 44863 storage/raft_transport.go:258  unable to accept Raft message from {NodeID:5 StoreID:5 ReplicaID:0}: no handler registered for {NodeID:4 StoreID:4 ReplicaID:0}
W161130 08:19:45.544834 44870 storage/store.go:3019  [s5] raft error: node 4 claims to not contain store 4 for replica {4 4 0}: store 4 was not found
I161130 08:19:45.638021 44892 storage/raft_transport.go:437  raft transport stream to node 4 established
W161130 08:19:45.638168 44896 storage/raft_transport.go:258  unable to accept Raft message from {NodeID:2 StoreID:2 ReplicaID:0}: no handler registered for {NodeID:4 StoreID:4 ReplicaID:0}
W161130 08:19:45.638282 44894 storage/store.go:3019  [s2] raft error: node 4 claims to not contain store 4 for replica {4 4 0}: store 4 was not found
I161130 08:19:45.644406 44871 storage/raft_transport.go:437  raft transport stream to node 4 established
W161130 08:19:45.644506 44828 storage/raft_transport.go:258  unable to accept Raft message from {NodeID:5 StoreID:5 ReplicaID:0}: no handler registered for {NodeID:4 StoreID:4 ReplicaID:0}
W161130 08:19:45.644619 44898 storage/store.go:3019  [s5] raft error: node 4 claims to not contain store 4 for replica {4 4 0}: store 4 was not found
I161130 08:19:45.736564 44808 storage/raft_transport.go:437  raft transport stream to node 4 established
W161130 08:19:45.736675 44909 storage/raft_transport.go:258  unable to accept Raft message from {NodeID:2 StoreID:2 ReplicaID:0}: no handler registered for {NodeID:4 StoreID:4 ReplicaID:0}
W161130 08:19:45.736802 44810 storage/store.go:3019  [s2] raft error: node 4 claims to not contain store 4 for replica {4 4 0}: store 4 was not found
I161130 08:19:45.744432 44939 storage/raft_transport.go:437  raft transport stream to node 4 established
W161130 08:19:45.744550 44911 storage/raft_transport.go:258  unable to accept Raft message from {NodeID:5 StoreID:5 ReplicaID:0}: no handler registered for {NodeID:4 StoreID:4 ReplicaID:0}
W161130 08:19:45.744684 44878 storage/store.go:3019  [s5] raft error: node 4 claims to not contain store 4 for replica {4 4 0}: store 4 was not found
I161130 08:19:45.786585 44919 storage/raft_transport.go:437  raft transport stream to node 4 established
W161130 08:19:45.787339 44913 storage/raft_transport.go:258  unable to accept Raft message from {NodeID:2 StoreID:2 ReplicaID:0}: no handler registered for {NodeID:4 StoreID:4 ReplicaID:0}
W161130 08:19:45.787571 44921 storage/store.go:3019  [s2] raft error: node 4 claims to not contain store 4 for replica {4 4 0}: store 4 was not found
I161130 08:19:45.844315 44985 storage/raft_transport.go:437  raft transport stream to node 4 established
W161130 08:19:45.844476 44949 storage/raft_transport.go:258  unable to accept Raft message from {NodeID:5 StoreID:5 ReplicaID:0}: no handler registered for {NodeID:4 StoreID:4 ReplicaID:0}
W161130 08:19:45.844638 44987 storage/store.go:3019  [s5] raft error: node 4 claims to not contain store 4 for replica {4 4 0}: store 4 was not found
I161130 08:19:45.886570 44971 storage/raft_transport.go:437  raft transport stream to node 4 established
W161130 08:19:45.886874 44989 storage/raft_transport.go:258  unable to accept Raft message from {NodeID:2 StoreID:2 ReplicaID:0}: no handler registered for {NodeID:4 StoreID:4 ReplicaID:0}
W161130 08:19:45.886967 44973 storage/store.go:3019  [s2] raft error: node 4 claims to not contain store 4 for replica {4 4 0}: store 4 was not found
I161130 08:19:45.894414 44974 storage/raft_transport.go:437  raft transport stream to node 4 established
W161130 08:19:45.894692 44951 storage/raft_transport.go:258  unable to accept Raft message from {NodeID:5 StoreID:5 ReplicaID:0}: no handler registered for {NodeID:4 StoreID:4 ReplicaID:0}
W161130 08:19:45.894781 44976 storage/store.go:3019  [s5] raft error: node 4 claims to not contain store 4 for replica {4 4 0}: store 4 was not found
I161130 08:19:45.994453 44990 storage/raft_transport.go:437  raft transport stream to node 4 established
W161130 08:19:45.994617 44994 storage/raft_transport.go:258  unable to accept Raft message from {NodeID:5 StoreID:5 ReplicaID:0}: no handler registered for {NodeID:4 StoreID:4 ReplicaID:0}
W161130 08:19:45.994797 44992 storage/store.go:3019  [s5] raft error: node 4 claims to not contain store 4 for replica {4 4 0}: store 4 was not found
I161130 08:19:46.036425 45003 storage/raft_transport.go:437  raft transport stream to node 4 established
W161130 08:19:46.036591 45016 storage/raft_transport.go:258  unable to accept Raft message from {NodeID:2 StoreID:2 ReplicaID:0}: no handler registered for {NodeID:4 StoreID:4 ReplicaID:0}
W161130 08:19:46.036779 45005 storage/store.go:3019  [s2] raft error: node 4 claims to not contain store 4 for replica {4 4 0}: store 4 was not found
I161130 08:19:46.086806 45017 storage/raft_transport.go:437  raft transport stream to node 4 established
W161130 08:19:46.087120 45021 storage/raft_transport.go:258  unable to accept Raft message from {NodeID:2 StoreID:2 ReplicaID:0}: no handler registered for {NodeID:4 StoreID:4 ReplicaID:0}
W161130 08:19:46.087253 45019 storage/store.go:3019  [s2] raft error: node 4 claims to not contain store 4 for replica {4 4 0}: store 4 was not found
E161130 08:19:46.092447 31664 storage/client_test.go:1002  engine 0: missing key "z"
E161130 08:19:46.092487 31664 storage/client_test.go:1002  engine 2: missing key "z"
I161130 08:19:46.094444 45047 storage/raft_transport.go:437  raft transport stream to node 4 established
W161130 08:19:46.094978 45028 storage/raft_transport.go:258  unable to accept Raft message from {NodeID:5 StoreID:5 ReplicaID:0}: no handler registered for {NodeID:4 StoreID:4 ReplicaID:0}
W161130 08:19:46.095081 45049 storage/store.go:3019  [s5] raft error: node 4 claims to not contain store 4 for replica {4 4 0}: store 4 was not found
I161130 08:19:46.236470 45069 storage/raft_transport.go:437  raft transport stream to node 4 established
W161130 08:19:46.236674 45073 storage/raft_transport.go:258  unable to accept Raft message from {NodeID:2 StoreID:2 ReplicaID:0}: no handler registered for {NodeID:4 StoreID:4 ReplicaID:0}
W161130 08:19:46.236784 45071 storage/store.go:3019  [s2] raft error: node 4 claims to not contain store 4 for replica {4 4 0}: store 4 was not found
I161130 08:19:46.244374 45090 storage/raft_transport.go:437  raft transport stream to node 4 established
W161130 08:19:46.244471 45076 storage/raft_transport.go:258  unable to accept Raft message from {NodeID:5 StoreID:5 ReplicaID:0}: no handler registered for {NodeID:4 StoreID:4 ReplicaID:0}
W161130 08:19:46.244563 45092 storage/store.go:3019  [s5] raft error: node 4 claims to not contain store 4 for replica {4 4 0}: store 4 was not found
I161130 08:19:46.294579 45077 storage/raft_transport.go:437  raft transport stream to node 4 established
W161130 08:19:46.294749 45107 storage/raft_transport.go:258  unable to accept Raft message from {NodeID:5 StoreID:5 ReplicaID:0}: no handler registered for {NodeID:4 StoreID:4 ReplicaID:0}
W161130 08:19:46.294851 44817 storage/store.go:3019  [s5] raft error: node 4 claims to not contain store 4 for replica {4 4 0}: store 4 was not found
I161130 08:19:46.336509 45093 storage/raft_transport.go:437  raft transport stream to node 4 established
W161130 08:19:46.336645 45122 storage/raft_transport.go:258  unable to accept Raft message from {NodeID:2 StoreID:2 ReplicaID:0}: no handler registered for {NodeID:4 StoreID:4 ReplicaID:0}
W161130 08:19:46.336739 45079 storage/store.go:3019  [s2] raft error: node 4 claims to not contain store 4 for replica {4 4 0}: store 4 was not found
I161130 08:19:46.386541 45156 storage/raft_transport.go:437  raft transport stream to node 4 established
W161130 08:19:46.386697 45098 storage/raft_transport.go:258  unable to accept Raft message from {NodeID:2 StoreID:2 ReplicaID:0}: no handler registered for {NodeID:4 StoreID:4 ReplicaID:0}
W161130 08:19:46.386786 45158 storage/store.go:3019  [s2] raft error: node 4 claims to not contain store 4 for replica {4 4 0}: store 4 was not found
I161130 08:19:46.394449 45170 storage/raft_transport.go:437  raft transport stream to node 4 established
W161130 08:19:46.394613 45100 storage/raft_transport.go:258  unable to accept Raft message from {NodeID:5 StoreID:5 ReplicaID:0}: no handler registered for {NodeID:4 StoreID:4 ReplicaID:0}
W161130 08:19:46.395104 45172 storage/store.go:3019  [s5] raft error: node 4 claims to not contain store 4 for replica {4 4 0}: store 4 was not found
I161130 08:19:46.536505 45139 storage/raft_transport.go:437  raft transport stream to node 4 established
W161130 08:19:46.536809 45143 storage/raft_transport.go:258  unable to accept Raft message from {NodeID:2 StoreID:2 ReplicaID:0}: no handler registered for {NodeID:4 StoreID:4 ReplicaID:0}
W161130 08:19:46.536906 45141 storage/store.go:3019  [s2] raft error: node 4 claims to not contain store 4 for replica {4 4 0}: store 4 was not found
I161130 08:19:46.544346 45173 storage/raft_transport.go:437  raft transport stream to node 4 established
W161130 08:19:46.544615 45102 storage/raft_transport.go:258  unable to accept Raft message from {NodeID:5 StoreID:5 ReplicaID:0}: no handler registered for {NodeID:4 StoreID:4 ReplicaID:0}
W161130 08:19:46.544692 45175 storage/store.go:3019  [s5] raft error: node 4 claims to not contain store 4 for replica {4 4 0}: store 4 was not found
I161130 08:19:46.594482 45190 storage/raft_transport.go:437  raft transport stream to node 4 established
W161130 08:19:46.594639 45207 storage/raft_transport.go:258  unable to accept Raft message from {NodeID:5 StoreID:5 ReplicaID:0}: no handler registered for {NodeID:4 StoreID:4 ReplicaID:0}
W161130 08:19:46.594749 45205 storage/store.go:3019  [s5] raft error: node 4 claims to not contain store 4 for replica {4 4 0}: store 4 was not found
I161130 08:19:46.636408 45105 storage/raft_transport.go:437  raft transport stream to node 4 established
W161130 08:19:46.636523 45222 storage/raft_transport.go:258  unable to accept Raft message from {NodeID:2 StoreID:2 ReplicaID:0}: no handler registered for {NodeID:4 StoreID:4 ReplicaID:0}
W161130 08:19:46.636609 45235 storage/store.go:3019  [s2] raft error: node 4 claims to not contain store 4 for replica {4 4 0}: store 4 was not found
I161130 08:19:46.736466 45246 storage/raft_transport.go:437  raft transport stream to node 4 established
W161130 08:19:46.736609 45266 storage/raft_transport.go:258  unable to accept Raft message from {NodeID:2 StoreID:2 ReplicaID:0}: no handler registered for {NodeID:4 StoreID:4 ReplicaID:0}
W161130 08:19:46.736686 45248 storage/store.go:3019  [s2] raft error: node 4 claims to not contain store 4 for replica {4 4 0}: store 4 was not found
I161130 08:19:46.744440 45255 storage/raft_transport.go:437  raft transport stream to node 4 established
W161130 08:19:46.744590 45259 storage/raft_transport.go:258  unable to accept Raft message from {NodeID:5 StoreID:5 ReplicaID:0}: no handler registered for {NodeID:4 StoreID:4 ReplicaID:0}
W161130 08:19:46.744675 45257 storage/store.go:3019  [s5] raft error: node 4 claims to not contain store 4 for replica {4 4 0}: store 4 was not found
I161130 08:19:46.836484 45192 storage/raft_transport.go:437  raft transport stream to node 4 established
W161130 08:19:46.836628 45217 storage/raft_transport.go:258  unable to accept Raft message from {NodeID:2 StoreID:2 ReplicaID:0}: no handler registered for {NodeID:4 StoreID:4 ReplicaID:0}
W161130 08:19:46.836747 45194 storage/store.go:3019  [s2] raft error: node 4 claims to not contain store 4 for replica {4 4 0}: store 4 was not found
I161130 08:19:46.844410 45261 storage/raft_transport.go:437  raft transport stream to node 4 established
W161130 08:19:46.844499 45196 storage/raft_transport.go:258  unable to accept Raft message from {NodeID:5 StoreID:5 ReplicaID:0}: no handler registered for {NodeID:4 StoreID:4 ReplicaID:0}
W161130 08:19:46.844584 45263 storage/store.go:3019  [s5] raft error: node 4 claims to not contain store 4 for replica {4 4 0}: store 4 was not found
I161130 08:19:46.936431 45265 storage/raft_transport.go:437  raft transport stream to node 4 established
W161130 08:19:46.936704 45333 storage/raft_transport.go:258  unable to accept Raft message from {NodeID:2 StoreID:2 ReplicaID:0}: no handler registered for {NodeID:4 StoreID:4 ReplicaID:0}
W161130 08:19:46.936793 45331 storage/store.go:3019  [s2] raft error: node 4 claims to not contain store 4 for replica {4 4 0}: store 4 was not found
I161130 08:19:46.944360 45284 storage/raft_transport.go:437  raft transport stream to node 4 established
W161130 08:19:46.944618 45288 storage/raft_transport.go:258  unable to accept Raft message from {NodeID:5 StoreID:5 ReplicaID:0}: no handler registered for {NodeID:4 StoreID:4 ReplicaID:0}
W161130 08:19:46.944707 45286 storage/store.go:3019  [s5] raft error: node 4 claims to not contain store 4 for replica {4 4 0}: store 4 was not found
I161130 08:19:46.986548 45334 storage/raft_transport.go:437  raft transport stream to node 4 established
W161130 08:19:46.986840 45290 storage/raft_transport.go:258  unable to accept Raft message from {NodeID:2 StoreID:2 ReplicaID:0}: no handler registered for {NodeID:4 StoreID:4 ReplicaID:0}
W161130 08:19:46.986928 45336 storage/store.go:3019  [s2] raft error: node 4 claims to not contain store 4 for replica {4 4 0}: store 4 was not found
I161130 08:19:46.994416 45306 storage/raft_transport.go:437  raft transport stream to node 4 established
W161130 08:19:46.994556 45292 storage/raft_transport.go:258  unable to accept Raft message from {NodeID:5 StoreID:5 ReplicaID:0}: no handler registered for {NodeID:4 StoreID:4 ReplicaID:0}
W161130 08:19:46.994731 45308 storage/store.go:3019  [s5] raft error: node 4 claims to not contain store 4 for replica {4 4 0}: store 4 was not found
I161130 08:19:47.087534 45348 storage/raft_transport.go:437  raft transport stream to node 4 established
W161130 08:19:47.087804 45312 storage/raft_transport.go:258  unable to accept Raft message from {NodeID:2 StoreID:2 ReplicaID:0}: no handler registered for {NodeID:4 StoreID:4 ReplicaID:0}
W161130 08:19:47.087891 45350 storage/store.go:3019  [s2] raft error: node 4 claims to not contain store 4 for replica {4 4 0}: store 4 was not found
E161130 08:19:47.092665 31664 storage/client_test.go:1002  engine 0: missing key "z"
E161130 08:19:47.092700 31664 storage/client_test.go:1002  engine 2: missing key "z"
I161130 08:19:47.144373 45355 storage/raft_transport.go:437  raft transport stream to node 4 established
W161130 08:19:47.144532 45362 storage/raft_transport.go:258  unable to accept Raft message from {NodeID:5 StoreID:5 ReplicaID:0}: no handler registered for {NodeID:4 StoreID:4 ReplicaID:0}
W161130 08:19:47.144646 45357 storage/store.go:3019  [s5] raft error: node 4 claims to not contain store 4 for replica {4 4 0}: store 4 was not found
I161130 08:19:47.186524 45358 storage/raft_transport.go:437  raft transport stream to node 4 established
W161130 08:19:47.186651 45378 storage/raft_transport.go:258  unable to accept Raft message from {NodeID:2 StoreID:2 ReplicaID:0}: no handler registered for {NodeID:4 StoreID:4 ReplicaID:0}
W161130 08:19:47.186740 45360 storage/store.go:3019  [s2] raft error: node 4 claims to not contain store 4 for replica {4 4 0}: store 4 was not found
I161130 08:19:47.244360 45230 storage/raft_transport.go:437  raft transport stream to node 4 established
W161130 08:19:47.244587 45380 storage/raft_transport.go:258  unable to accept Raft message from {NodeID:5 StoreID:5 ReplicaID:0}: no handler registered for {NodeID:4 StoreID:4 ReplicaID:0}
W161130 08:19:47.244697 45232 storage/store.go:3019  [s5] raft error: node 4 claims to not contain store 4 for replica {4 4 0}: store 4 was not found
I161130 08:19:47.336479 45375 storage/raft_transport.go:437  raft transport stream to node 4 established
W161130 08:19:47.336604 45338 storage/raft_transport.go:258  unable to accept Raft message from {NodeID:2 StoreID:2 ReplicaID:0}: no handler registered for {NodeID:4 StoreID:4 ReplicaID:0}
W161130 08:19:47.336710 45377 storage/store.go:3019  [s2] raft error: node 4 claims to not contain store 4 for replica {4 4 0}: store 4 was not found
I161130 08:19:47.344325 45426 storage/raft_transport.go:437  raft transport stream to node 4 established
W161130 08:19:47.344427 45340 storage/raft_transport.go:258  unable to accept Raft message from {NodeID:5 StoreID:5 ReplicaID:0}: no handler registered for {NodeID:4 StoreID:4 ReplicaID:0}
W161130 08:19:47.344542 45428 storage/store.go:3019  [s5] raft error: node 4 claims to not contain store 4 for replica {4 4 0}: store 4 was not found
I161130 08:19:47.436510 45341 storage/raft_transport.go:437  raft transport stream to node 4 established
W161130 08:19:47.436679 45408 storage/raft_transport.go:258  unable to accept Raft message from {NodeID:2 StoreID:2 ReplicaID:0}: no handler registered for {NodeID:4 StoreID:4 ReplicaID:0}
W161130 08:19:47.437085 45406 storage/store.go:3019  [s2] raft error: node 4 claims to not contain store 4 for replica {4 4 0}: store 4 was not found
I161130 08:19:47.444407 45409 storage/raft_transport.go:437  raft transport stream to node 4 established
W161130 08:19:47.444563 45445 storage/raft_transport.go:258  unable to accept Raft message from {NodeID:5 StoreID:5 ReplicaID:0}: no handler registered for {NodeID:4 StoreID:4 ReplicaID:0}
W161130 08:19:47.444764 45443 storage/store.go:3019  [s5] raft error: node 4 claims to not contain store 4 for replica {4 4 0}: store 4 was not found
I161130 08:19:47.536412 45417 storage/raft_transport.go:437  raft transport stream to node 4 established
W161130 08:19:47.536577 45475 storage/raft_transport.go:258  unable to accept Raft message from {NodeID:2 StoreID:2 ReplicaID:0}: no handler registered for {NodeID:4 StoreID:4 ReplicaID:0}
W161130 08:19:47.536702 45419 storage/store.go:3019  [s2] raft error: node 4 claims to not contain store 4 for replica {4 4 0}: store 4 was not found
I161130 08:19:47.544357 45463 storage/raft_transport.go:437  raft transport stream to node 4 established
W161130 08:19:47.544470 45456 storage/raft_transport.go:258  unable to accept Raft message from {NodeID:5 StoreID:5 ReplicaID:0}: no handler registered for {NodeID:4 StoreID:4 ReplicaID:0}
W161130 08:19:47.544564 45465 storage/store.go:3019  [s5] raft error: node 4 claims to not contain store 4 for replica {4 4 0}: store 4 was not found
I161130 08:19:47.636409 45491 storage/raft_transport.go:437  raft transport stream to node 4 established
W161130 08:19:47.636677 45510 storage/raft_transport.go:258  unable to accept Raft message from {NodeID:2 StoreID:2 ReplicaID:0}: no handler registered for {NodeID:4 StoreID:4 ReplicaID:0}
W161130 08:19:47.636774 45493 storage/store.go:3019  [s2] raft error: node 4 claims to not contain store 4 for replica {4 4 0}: store 4 was not found
I161130 08:19:47.644344 45496 storage/raft_transport.go:437  raft transport stream to node 4 established
W161130 08:19:47.644458 45523 storage/raft_transport.go:258  unable to accept Raft message from {NodeID:5 StoreID:5 ReplicaID:0}: no handler registered for {NodeID:4 StoreID:4 ReplicaID:0}
W161130 08:19:47.644569 45498 storage/store.go:3019  [s5] raft error: node 4 claims to not contain store 4 for replica {4 4 0}: store 4 was not found
I161130 08:19:47.738050 45524 storage/raft_transport.go:437  raft transport stream to node 4 established
W161130 08:19:47.738171 45391 storage/raft_transport.go:258  unable to accept Raft message from {NodeID:2 StoreID:2 ReplicaID:0}: no handler registered for {NodeID:4 StoreID:4 ReplicaID:0}
W161130 08:19:47.738285 45526 storage/store.go:3019  [s2] raft error: node 4 claims to not contain store 4 for replica {4 4 0}: store 4 was not found
I161130 08:19:47.748529 45511 storage/raft_transport.go:437  raft transport stream to node 4 established
W161130 08:19:47.748624 45539 storage/raft_transport.go:258  unable to accept Raft message from {NodeID:5 StoreID:5 ReplicaID:0}: no handler registered for {NodeID:4 StoreID:4 ReplicaID:0}
W161130 08:19:47.748740 45513 storage/store.go:3019  [s5] raft error: node 4 claims to not contain store 4 for replica {4 4 0}: store 4 was not found
I161130 08:19:47.836419 45561 storage/raft_transport.go:437  raft transport stream to node 4 established
W161130 08:19:47.836680 45565 storage/raft_transport.go:258  unable to accept Raft message from {NodeID:2 StoreID:2 ReplicaID:0}: no handler registered for {NodeID:4 StoreID:4 ReplicaID:0}
W161130 08:19:47.836806 45563 storage/store.go:3019  [s2] raft error: node 4 claims to not contain store 4 for replica {4 4 0}: store 4 was not found
I161130 08:19:47.844346 45566 storage/raft_transport.go:437  raft transport stream to node 4 established
W161130 08:19:47.844487 45519 storage/raft_transport.go:258  unable to accept Raft message from {NodeID:5 StoreID:5 ReplicaID:0}: no handler registered for {NodeID:4 StoreID:4 ReplicaID:0}
W161130 08:19:47.844578 45517 storage/store.go:3019  [s5] raft error: node 4 claims to not contain store 4 for replica {4 4 0}: store 4 was not found
I161130 08:19:47.886606 45550 storage/raft_transport.go:437  raft transport stream to node 4 established
W161130 08:19:47.886715 45578 storage/raft_transport.go:258  unable to accept Raft message from {NodeID:2 StoreID:2 ReplicaID:0}: no handler registered for {NodeID:4 StoreID:4 ReplicaID:0}
W161130 08:19:47.886848 45568 storage/store.go:3019  [s2] raft error: node 4 claims to not contain store 4 for replica {4 4 0}: store 4 was not found
I161130 08:19:47.944429 45520 storage/raft_transport.go:437  raft transport stream to node 4 established
W161130 08:19:47.944601 45588 storage/raft_transport.go:258  unable to accept Raft message from {NodeID:5 StoreID:5 ReplicaID:0}: no handler registered for {NodeID:4 StoreID:4 ReplicaID:0}
W161130 08:19:47.944725 45586 storage/store.go:3019  [s5] raft error: node 4 claims to not contain store 4 for replica {4 4 0}: store 4 was not found
I161130 08:19:47.986539 45551 storage/raft_transport.go:437  raft transport stream to node 4 established
W161130 08:19:47.986643 45592 storage/raft_transport.go:258  unable to accept Raft message from {NodeID:2 StoreID:2 ReplicaID:0}: no handler registered for {NodeID:4 StoreID:4 ReplicaID:0}
W161130 08:19:47.986744 45553 storage/store.go:3019  [s2] raft error: node 4 claims to not contain store 4 for replica {4 4 0}: store 4 was not found
I161130 08:19:48.044427 43392 storage/raft_transport.go:437  raft transport stream to node 4 established
W161130 08:19:48.044623 45615 storage/raft_transport.go:258  unable to accept Raft message from {NodeID:5 StoreID:5 ReplicaID:0}: no handler registered for {NodeID:4 StoreID:4 ReplicaID:0}
W161130 08:19:48.044756 45634 storage/store.go:3019  [s5] raft error: node 4 claims to not contain store 4 for replica {4 4 0}: store 4 was not found
E161130 08:19:48.092959 31664 storage/client_test.go:1002  engine 0: missing key "z"
E161130 08:19:48.093000 31664 storage/client_test.go:1002  engine 2: missing key "z"
I161130 08:19:48.136474 45616 storage/raft_transport.go:437  raft transport stream to node 4 established
W161130 08:19:48.136728 45623 storage/raft_transport.go:258  unable to accept Raft message from {NodeID:2 StoreID:2 ReplicaID:0}: no handler registered for {NodeID:4 StoreID:4 ReplicaID:0}
W161130 08:19:48.136939 45650 storage/store.go:3019  [s2] raft error: node 4 claims to not contain store 4 for replica {4 4 0}: store 4 was not found
I161130 08:19:48.144417 45651 storage/raft_transport.go:437  raft transport stream to node 4 established
W161130 08:19:48.144552 45655 storage/raft_transport.go:258  unable to accept Raft message from {NodeID:5 StoreID:5 ReplicaID:0}: no handler registered for {NodeID:4 StoreID:4 ReplicaID:0}
W161130 08:19:48.144664 45653 storage/store.go:3019  [s5] raft error: node 4 claims to not contain store 4 for replica {4 4 0}: store 4 was not found
I161130 08:19:48.236486 45669 storage/raft_transport.go:437  raft transport stream to node 4 established
W161130 08:19:48.236728 45644 storage/raft_transport.go:258  unable to accept Raft message from {NodeID:2 StoreID:2 ReplicaID:0}: no handler registered for {NodeID:4 StoreID:4 ReplicaID:0}
W161130 08:19:48.236859 45671 storage/store.go:3019  [s2] raft error: node 4 claims to not contain store 4 for replica {4 4 0}: store 4 was not found
I161130 08:19:48.244436 45585 storage/raft_transport.go:437  raft transport stream to node 4 established
W161130 08:19:48.244529 45673 storage/raft_transport.go:258  unable to accept Raft message from {NodeID:5 StoreID:5 ReplicaID:0}: no handler registered for {NodeID:4 StoreID:4 ReplicaID:0}
W161130 08:19:48.244631 45683 storage/store.go:3019  [s5] raft error: node 4 claims to not contain store 4 for replica {4 4 0}: store 4 was not found
I161130 08:19:48.336448 45674 storage/raft_transport.go:437  raft transport stream to node 4 established
W161130 08:19:48.336622 45646 storage/raft_transport.go:258  unable to accept Raft message from {NodeID:2 StoreID:2 ReplicaID:0}: no handler registered for {NodeID:4 StoreID:4 ReplicaID:0}
W161130 08:19:48.336754 45676 storage/store.go:3019  [s2] raft error: node 4 claims to not contain store 4 for replica {4 4 0}: store 4 was not found
I161130 08:19:48.344433 45647 storage/raft_transport.go:437  raft transport stream to node 4 established
W161130 08:19:48.344587 45699 storage/raft_transport.go:258  unable to accept Raft message from {NodeID:5 StoreID:5 ReplicaID:0}: no handler registered for {NodeID:4 StoreID:4 ReplicaID:0}
W161130 08:19:48.344693 45649 storage/store.go:3019  [s5] raft error: node 4 claims to not contain store 4 for replica {4 4 0}: store 4 was not found
I161130 08:19:48.394443 45733 storage/raft_transport.go:437  raft transport stream to node 4 established
W161130 08:19:48.394573 45746 storage/raft_transport.go:258  unable to accept Raft message from {NodeID:5 StoreID:5 ReplicaID:0}: no handler registered for {NodeID:4 StoreID:4 ReplicaID:0}
W161130 08:19:48.394695 45735 storage/store.go:3019  [s5] raft error: node 4 claims to not contain store 4 for replica {4 4 0}: store 4 was not found
I161130 08:19:48.436447 45723 storage/raft_transport.go:437  raft transport stream to node 4 established
W161130 08:19:48.436583 45737 storage/raft_transport.go:258  unable to accept Raft message from {NodeID:2 StoreID:2 ReplicaID:0}: no handler registered for {NodeID:4 StoreID:4 ReplicaID:0}
W161130 08:19:48.436713 45725 storage/store.go:3019  [s2] raft error: node 4 claims to not contain store 4 for replica {4 4 0}: store 4 was not found
I161130 08:19:48.536409 45780 storage/raft_transport.go:437  raft transport stream to node 4 established
W161130 08:19:48.536578 45629 storage/raft_transport.go:258  unable to accept Raft message from {NodeID:2 StoreID:2 ReplicaID:0}: no handler registered for {NodeID:4 StoreID:4 ReplicaID:0}
W161130 08:19:48.536691 45782 storage/store.go:3019  [s2] raft error: node 4 claims to not contain store 4 for replica {4 4 0}: store 4 was not found
I161130 08:19:48.544390 45784 storage/raft_transport.go:437  raft transport stream to node 4 established
W161130 08:19:48.544497 45767 storage/raft_transport.go:258  unable to accept Raft message from {NodeID:5 StoreID:5 ReplicaID:0}: no handler registered for {NodeID:4 StoreID:4 ReplicaID:0}
W161130 08:19:48.544602 45786 storage/store.go:3019  [s5] raft error: node 4 claims to not contain store 4 for replica {4 4 0}: store 4 was not found
I161130 08:19:48.636460 45768 storage/raft_transport.go:437  raft transport stream to node 4 established
W161130 08:19:48.636595 45488 storage/raft_transport.go:258  unable to accept Raft message from {NodeID:2 StoreID:2 ReplicaID:0}: no handler registered for {NodeID:4 StoreID:4 ReplicaID:0}
W161130 08:19:48.636698 45770 storage/store.go:3019  [s2] raft error: node 4 claims to not contain store 4 for replica {4 4 0}: store 4 was not found
I161130 08:19:48.644394 45787 storage/raft_transport.go:437  raft transport stream to node 4 established
W161130 08:19:48.644546 45796 storage/raft_transport.go:258  unable to accept Raft message from {NodeID:5 StoreID:5 ReplicaID:0}: no handler registered for {NodeID:4 StoreID:4 ReplicaID:0}
W161130 08:19:48.644634 45794 storage/store.go:3019  [s5] raft error: node 4 claims to not contain store 4 for replica {4 4 0}: store 4 was not found
I161130 08:19:48.736423 45827 storage/raft_transport.go:437  raft transport stream to node 4 established
W161130 08:19:48.736702 45633 storage/raft_transport.go:258  unable to accept Raft message from {NodeID:2 StoreID:2 ReplicaID:0}: no handler registered for {NodeID:4 StoreID:4 ReplicaID:0}
W161130 08:19:48.736811 45829 storage/store.go:3019  [s2] raft error: node 4 claims to not contain store 4 for replica {4 4 0}: store 4 was not found
I161130 08:19:48.744348 45858 storage/raft_transport.go:437  raft transport stream to node 4 established
W161130 08:19:48.744497 45846 storage/raft_transport.go:258  unable to accept Raft message from {NodeID:5 StoreID:5 ReplicaID:0}: no handler registered for {NodeID:4 StoreID:4 ReplicaID:0}
W161130 08:19:48.744691 45844 storage/store.go:3019  [s5] raft error: node 4 claims to not contain store 4 for replica {4 4 0}: store 4 was not found
I161130 08:19:48.836390 45859 storage/raft_transport.go:437  raft transport stream to node 4 established
W161130 08:19:48.836502 45817 storage/raft_transport.go:258  unable to accept Raft message from {NodeID:2 StoreID:2 ReplicaID:0}: no handler registered for {NodeID:4 StoreID:4 ReplicaID:0}
W161130 08:19:48.836617 45861 storage/store.go:3019  [s2] raft error: node 4 claims to not contain store 4 for replica {4 4 0}: store 4 was not found
I161130 08:19:48.844390 45862 storage/raft_transport.go:437  raft transport stream to node 4 established
W161130 08:19:48.844489 45831 storage/raft_transport.go:258  unable to accept Raft message from {NodeID:5 StoreID:5 ReplicaID:0}: no handler registered for {NodeID:4 StoreID:4 ReplicaID:0}
W161130 08:19:48.844575 45864 storage/store.go:3019  [s5] raft error: node 4 claims to not contain store 4 for replica {4 4 0}: store 4 was not found
I161130 08:19:48.936447 45875 storage/raft_transport.go:437  raft transport stream to node 4 established
W161130 08:19:48.936644 45879 storage/raft_transport.go:258  unable to accept Raft message from {NodeID:2 StoreID:2 ReplicaID:0}: no handler registered for {NodeID:4 StoreID:4 ReplicaID:0}
W161130 08:19:48.936843 45877 storage/store.go:3019  [s2] raft error: node 4 claims to not contain store 4 for replica {4 4 0}: store 4 was not found
I161130 08:19:48.944349 45838 storage/raft_transport.go:437  raft transport stream to node 4 established
W161130 08:19:48.944625 45825 storage/raft_transport.go:258  unable to accept Raft message from {NodeID:5 StoreID:5 ReplicaID:0}: no handler registered for {NodeID:4 StoreID:4 ReplicaID:0}
W161130 08:19:48.944718 45840 storage/store.go:3019  [s5] raft error: node 4 claims to not contain store 4 for replica {4 4 0}: store 4 was not found
I161130 08:19:49.036481 45906 storage/raft_transport.go:437  raft transport stream to node 4 established
W161130 08:19:49.036638 45910 storage/raft_transport.go:258  unable to accept Raft message from {NodeID:2 StoreID:2 ReplicaID:0}: no handler registered for {NodeID:4 StoreID:4 ReplicaID:0}
W161130 08:19:49.036845 45908 storage/store.go:3019  [s2] raft error: node 4 claims to not contain store 4 for replica {4 4 0}: store 4 was not found
I161130 08:19:49.044366 45841 storage/raft_transport.go:437  raft transport stream to node 4 established
W161130 08:19:49.044512 45912 storage/raft_transport.go:258  unable to accept Raft message from {NodeID:5 StoreID:5 ReplicaID:0}: no handler registered for {NodeID:4 StoreID:4 ReplicaID:0}
W161130 08:19:49.044640 45923 storage/store.go:3019  [s5] raft error: node 4 claims to not contain store 4 for replica {4 4 0}: store 4 was not found
E161130 08:19:49.093193 31664 storage/client_test.go:1002  engine 0: missing key "z"
E161130 08:19:49.093229 31664 storage/client_test.go:1002  engine 2: missing key "z"
I161130 08:19:49.136480 45938 storage/raft_transport.go:437  raft transport stream to node 4 established
W161130 08:19:49.136605 45954 storage/raft_transport.go:258  unable to accept Raft message from {NodeID:2 StoreID:2 ReplicaID:0}: no handler registered for {NodeID:4 StoreID:4 ReplicaID:0}
W161130 08:19:49.136737 45940 storage/store.go:3019  [s2] raft error: node 4 claims to not contain store 4 for replica {4 4 0}: store 4 was not found
I161130 08:19:49.144420 45941 storage/raft_transport.go:437  raft transport stream to node 4 established
W161130 08:19:49.144558 45958 storage/raft_transport.go:258  unable to accept Raft message from {NodeID:5 StoreID:5 ReplicaID:0}: no handler registered for {NodeID:4 StoreID:4 ReplicaID:0}
W161130 08:19:49.145145 45956 storage/store.go:3019  [s5] raft error: node 4 claims to not contain store 4 for replica {4 4 0}: store 4 was not found
I161130 08:19:49.236498 45903 storage/raft_transport.go:437  raft transport stream to node 4 established
W161130 08:19:49.236640 45943 storage/raft_transport.go:258  unable to accept Raft message from {NodeID:2 StoreID:2 ReplicaID:0}: no handler registered for {NodeID:4 StoreID:4 ReplicaID:0}
W161130 08:19:49.236767 45905 storage/store.go:3019  [s2] raft error: node 4 claims to not contain store 4 for replica {4 4 0}: store 4 was not found
I161130 08:19:49.244387 45944 storage/raft_transport.go:437  raft transport stream to node 4 established
W161130 08:19:49.244516 45929 storage/raft_transport.go:258  unable to accept Raft message from {NodeID:5 StoreID:5 ReplicaID:0}: no handler registered for {NodeID:4 StoreID:4 ReplicaID:0}
W161130 08:19:49.244627 45946 storage/store.go:3019  [s5] raft error: node 4 claims to not contain store 4 for replica {4 4 0}: store 4 was not found
I161130 08:19:49.336503 45991 storage/raft_transport.go:437  raft transport stream to node 4 established
W161130 08:19:49.336615 45976 storage/raft_transport.go:258  unable to accept Raft message from {NodeID:2 StoreID:2 ReplicaID:0}: no handler registered for {NodeID:4 StoreID:4 ReplicaID:0}
W161130 08:19:49.336740 45993 storage/store.go:3019  [s2] raft error: node 4 claims to not contain store 4 for replica {4 4 0}: store 4 was not found
I161130 08:19:49.344418 45977 storage/raft_transport.go:437  raft transport stream to node 4 established
W161130 08:19:49.344542 46006 storage/raft_transport.go:258  unable to accept Raft message from {NodeID:5 StoreID:5 ReplicaID:0}: no handler registered for {NodeID:4 StoreID:4 ReplicaID:0}
W161130 08:19:49.344653 45979 storage/store.go:3019  [s5] raft error: node 4 claims to not contain store 4 for replica {4 4 0}: store 4 was not found
I161130 08:19:49.437013 46026 storage/raft_transport.go:437  raft transport stream to node 4 established
W161130 08:19:49.437127 46043 storage/raft_transport.go:258  unable to accept Raft message from {NodeID:2 StoreID:2 ReplicaID:0}: no handler registered for {NodeID:4 StoreID:4 ReplicaID:0}
W161130 08:19:49.437229 46028 storage/store.go:3019  [s2] raft error: node 4 claims to not contain store 4 for replica {4 4 0}: store 4 was not found
I161130 08:19:49.444420 46044 storage/raft_transport.go:437  raft transport stream to node 4 established
W161130 08:19:49.444556 46000 storage/raft_transport.go:258  unable to accept Raft message from {NodeID:5 StoreID:5 ReplicaID:0}: no handler registered for {NodeID:4 StoreID:4 ReplicaID:0}
W161130 08:19:49.444673 46046 storage/store.go:3019  [s5] raft error: node 4 claims to not contain store 4 for replica {4 4 0}: store 4 was not found
I161130 08:19:49.536509 46001 storage/raft_transport.go:437  raft transport stream to node 4 established
W161130 08:19:49.536667 46053 storage/raft_transport.go:258  unable to accept Raft message from {NodeID:2 StoreID:2 ReplicaID:0}: no handler registered for {NodeID:4 StoreID:4 ReplicaID:0}
W161130 08:19:49.536779 46051 storage/store.go:3019  [s2] raft error: node 4 claims to not contain store 4 for replica {4 4 0}: store 4 was not found
I161130 08:19:49.544435 46054 storage/raft_transport.go:437  raft transport stream to node 4 established
W161130 08:19:49.544528 46067 storage/raft_transport.go:258  unable to accept Raft message from {NodeID:5 StoreID:5 ReplicaID:0}: no handler registered for {NodeID:4 StoreID:4 ReplicaID:0}
W161130 08:19:49.544642 46056 storage/store.go:3019  [s5] raft error: node 4 claims to not contain store 4 for replica {4 4 0}: store 4 was not found
I161130 08:19:49.636469 46087 storage/raft_transport.go:437  raft transport stream to node 4 established
W161130 08:19:49.636608 46098 storage/raft_transport.go:258  unable to accept Raft message from {NodeID:2 StoreID:2 ReplicaID:0}: no handler registered for {NodeID:4 StoreID:4 ReplicaID:0}
W161130 08:19:49.636761 46089 storage/store.go:3019  [s2] raft error: node 4 claims to not contain store 4 for replica {4 4 0}: store 4 was not found
I161130 08:19:49.644417 46099 storage/raft_transport.go:437  raft transport stream to node 4 established
W161130 08:19:49.645797 46081 storage/raft_transport.go:258  unable to accept Raft message from {NodeID:5 StoreID:5 ReplicaID:0}: no handler registered for {NodeID:4 StoreID:4 ReplicaID:0}
W161130 08:19:49.646216 46101 storage/store.go:3019  [s5] raft error: node 4 claims to not contain store 4 for replica {4 4 0}: store 4 was not found
I161130 08:19:49.694443 46090 storage/raft_transport.go:437  raft transport stream to node 4 established
W161130 08:19:49.694608 46114 storage/raft_transport.go:258  unable to accept Raft message from {NodeID:5 StoreID:5 ReplicaID:0}: no handler registered for {NodeID:4 StoreID:4 ReplicaID:0}
W161130 08:19:49.694749 46092 storage/store.go:3019  [s5] raft error: node 4 claims to not contain store 4 for replica {4 4 0}: store 4 was not found
I161130 08:19:49.736489 46130 storage/raft_transport.go:437  raft transport stream to node 4 established
W161130 08:19:49.736647 46134 storage/raft_transport.go:258  unable to accept Raft message from {NodeID:2 StoreID:2 ReplicaID:0}: no handler registered for {NodeID:4 StoreID:4 ReplicaID:0}
W161130 08:19:49.736777 46132 storage/store.go:3019  [s2] raft error: node 4 claims to not contain store 4 for replica {4 4 0}: store 4 was not found
I161130 08:19:49.794512 46142 storage/raft_transport.go:437  raft transport stream to node 4 established
W161130 08:19:49.794649 46119 storage/raft_transport.go:258  unable to accept Raft message from {NodeID:5 StoreID:5 ReplicaID:0}: no handler registered for {NodeID:4 StoreID:4 ReplicaID:0}
W161130 08:19:49.794794 46144 storage/store.go:3019  [s5] raft error: node 4 claims to not contain store 4 for replica {4 4 0}: store 4 was not found
I161130 08:19:49.836469 45856 storage/raft_transport.go:437  raft transport stream to node 4 established
W161130 08:19:49.836589 46151 storage/raft_transport.go:258  unable to accept Raft message from {NodeID:2 StoreID:2 ReplicaID:0}: no handler registered for {NodeID:4 StoreID:4 ReplicaID:0}
W161130 08:19:49.836707 46162 storage/store.go:3019  [s2] raft error: node 4 claims to not contain store 4 for replica {4 4 0}: store 4 was not found
I161130 08:19:49.936502 46015 storage/raft_transport.go:437  raft transport stream to node 4 established
W161130 08:19:49.937064 46108 storage/raft_transport.go:258  unable to accept Raft message from {NodeID:2 StoreID:2 ReplicaID:0}: no handler registered for {NodeID:4 StoreID:4 ReplicaID:0}
W161130 08:19:49.937194 46017 storage/store.go:3019  [s2] raft error: node 4 claims to not contain store 4 for replica {4 4 0}: store 4 was not found
I161130 08:19:49.944360 46152 storage/raft_transport.go:437  raft transport stream to node 4 established
W161130 08:19:49.944470 46128 storage/raft_transport.go:258  unable to accept Raft message from {NodeID:5 StoreID:5 ReplicaID:0}: no handler registered for {NodeID:4 StoreID:4 ReplicaID:0}
W161130 08:19:49.944584 46154 storage/store.go:3019  [s5] raft error: node 4 claims to not contain store 4 for replica {4 4 0}: store 4 was not found
I161130 08:19:49.986629 46226 storage/raft_transport.go:437  raft transport stream to node 4 established
W161130 08:19:49.986742 46212 storage/raft_transport.go:258  unable to accept Raft message from {NodeID:2 StoreID:2 ReplicaID:0}: no handler registered for {NodeID:4 StoreID:4 ReplicaID:0}
W161130 08:19:49.986865 46188 storage/store.go:3019  [s2] raft error: node 4 claims to not contain store 4 for replica {4 4 0}: store 4 was not found
I161130 08:19:50.044619 46213 storage/raft_transport.go:437  raft transport stream to node 4 established
W161130 08:19:50.044728 46215 storage/raft_transport.go:258  unable to accept Raft message from {NodeID:5 StoreID:5 ReplicaID:0}: no handler registered for {NodeID:4 StoreID:4 ReplicaID:0}
W161130 08:19:50.044846 46190 storage/store.go:3019  [s5] raft error: node 4 claims to not contain store 4 for replica {4 4 0}: store 4 was not found
E161130 08:19:50.093447 31664 storage/client_test.go:1002  engine 0: missing key "z"
E161130 08:19:50.093484 31664 storage/client_test.go:1002  engine 2: missing key "z"
I161130 08:19:50.136491 46191 storage/raft_transport.go:437  raft transport stream to node 4 established
W161130 08:19:50.136625 46228 storage/raft_transport.go:258  unable to accept Raft message from {NodeID:2 StoreID:2 ReplicaID:0}: no handler registered for {NodeID:4 StoreID:4 ReplicaID:0}
W161130 08:19:50.136737 46193 storage/store.go:3019  [s2] raft error: node 4 claims to not contain store 4 for replica {4 4 0}: store 4 was not found
I161130 08:19:50.144443 46229 storage/raft_transport.go:437  raft transport stream to node 4 established
W161130 08:19:50.144547 46201 storage/raft_transport.go:258  unable to accept Raft message from {NodeID:5 StoreID:5 ReplicaID:0}: no handler registered for {NodeID:4 StoreID:4 ReplicaID:0}
W161130 08:19:50.144657 46217 storage/store.go:3019  [s5] raft error: node 4 claims to not contain store 4 for replica {4 4 0}: store 4 was not found
I161130 08:19:50.237296 46244 storage/raft_transport.go:437  raft transport stream to node 4 established
W161130 08:19:50.237523 46237 storage/raft_transport.go:258  unable to accept Raft message from {NodeID:2 StoreID:2 ReplicaID:0}: no handler registered for {NodeID:4 StoreID:4 ReplicaID:0}
W161130 08:19:50.237644 46235 storage/store.go:3019  [s2] raft error: node 4 claims to not contain store 4 for replica {4 4 0}: store 4 was not found
I161130 08:19:50.244401 46207 storage/raft_transport.go:437  raft transport stream to node 4 established
W161130 08:19:50.244508 46246 storage/raft_transport.go:258  unable to accept Raft message from {NodeID:5 StoreID:5 ReplicaID:0}: no handler registered for {NodeID:4 StoreID:4 ReplicaID:0}
W161130 08:19:50.244608 46209 storage/store.go:3019  [s5] raft error: node 4 claims to not contain store 4 for replica {4 4 0}: store 4 was not found
I161130 08:19:50.336441 46286 storage/raft_transport.go:437  raft transport stream to node 4 established
W161130 08:19:50.336562 46255 storage/raft_transport.go:258  unable to accept Raft message from {NodeID:2 StoreID:2 ReplicaID:0}: no handler registered for {NodeID:4 StoreID:4 ReplicaID:0}
W161130 08:19:50.336669 46288 storage/store.go:3019  [s2] raft error: node 4 claims to not contain store 4 for replica {4 4 0}: store 4 was not found
I161130 08:19:50.344373 46322 storage/raft_transport.go:437  raft transport stream to node 4 established
W161130 08:19:50.344476 46324 storage/raft_transport.go:258  unable to accept Raft message from {NodeID:5 StoreID:5 ReplicaID:0}: no handler registered for {NodeID:4 StoreID:4 ReplicaID:0}
W161130 08:19:50.344605 46296 storage/store.go:3019  [s5] raft error: node 4 claims to not contain store 4 for replica {4 4 0}: store 4 was not found
I161130 08:19:50.436489 46264 storage/raft_transport.go:437  raft transport stream to node 4 established
W161130 08:19:50.436619 46309 storage/raft_transport.go:258  unable to accept Raft message from {NodeID:2 StoreID:2 ReplicaID:0}: no handler registered for {NodeID:4 StoreID:4 ReplicaID:0}
W161130 08:19:50.436736 46266 storage/store.go:3019  [s2] raft error: node 4 claims to not contain store 4 for replica {4 4 0}: store 4 was not found
I161130 08:19:50.444391 46310 storage/raft_transport.go:437  raft transport stream to node 4 established
W161130 08:19:50.444554 46300 storage/raft_transport.go:258  unable to accept Raft message from {NodeID:5 StoreID:5 ReplicaID:0}: no handler registered for {NodeID:4 StoreID:4 ReplicaID:0}
W161130 08:19:50.444672 46298 storage/store.go:3019  [s5] raft error: node 4 claims to not contain store 4 for replica {4 4 0}: store 4 was not found
I161130 08:19:50.536496 46370 storage/raft_transport.go:437  raft transport stream to node 4 established
W161130 08:19:50.536660 46357 storage/raft_transport.go:258  unable to accept Raft message from {NodeID:2 StoreID:2 ReplicaID:0}: no handler registered for {NodeID:4 StoreID:4 ReplicaID:0}
W161130 08:19:50.536780 46372 storage/store.go:3019  [s2] raft error: node 4 claims to not contain store 4 for replica {4 4 0}: store 4 was not found
I161130 08:19:50.544414 46358 storage/raft_transport.go:437  raft transport stream to node 4 established
W161130 08:19:50.544552 46362 storage/raft_transport.go:258  unable to accept Raft message from {NodeID:5 StoreID:5 ReplicaID:0}: no handler registered for {NodeID:4 StoreID:4 ReplicaID:0}
W161130 08:19:50.544675 46360 storage/store.go:3019  [s5] raft error: node 4 claims to not contain store 4 for replica {4 4 0}: store 4 was not found
I161130 08:19:50.636506 46363 storage/raft_transport.go:437  raft transport stream to node 4 established
W161130 08:19:50.636669 46268 storage/raft_transport.go:258  unable to accept Raft message from {NodeID:2 StoreID:2 ReplicaID:0}: no handler registered for {NodeID:4 StoreID:4 ReplicaID:0}
W161130 08:19:50.636786 46365 storage/store.go:3019  [s2] raft error: node 4 claims to not contain store 4 for replica {4 4 0}: store 4 was not found
I161130 08:19:50.644466 46317 storage/raft_transport.go:437  raft transport stream to node 4 established
W161130 08:19:50.644599 46346 storage/raft_transport.go:258  unable to accept Raft message from {NodeID:5 StoreID:5 ReplicaID:0}: no handler registered for {NodeID:4 StoreID:4 ReplicaID:0}
W161130 08:19:50.644720 46319 storage/store.go:3019  [s5] raft error: node 4 claims to not contain store 4 for replica {4 4 0}: store 4 was not found
I161130 08:19:50.736491 46351 storage/raft_transport.go:437  raft transport stream to node 4 established
W161130 08:19:50.736646 46419 storage/raft_transport.go:258  unable to accept Raft message from {NodeID:2 StoreID:2 ReplicaID:0}: no handler registered for {NodeID:4 StoreID:4 ReplicaID:0}
W161130 08:19:50.736764 46353 storage/store.go:3019  [s2] raft error: node 4 claims to not contain store 4 for replica {4 4 0}: store 4 was not found
I161130 08:19:50.744390 46391 storage/raft_transport.go:437  raft transport stream to node 4 established
W161130 08:19:50.744539 46423 storage/raft_transport.go:258  unable to accept Raft message from {NodeID:5 StoreID:5 ReplicaID:0}: no handler registered for {NodeID:4 StoreID:4 ReplicaID:0}
W161130 08:19:50.744656 46421 storage/store.go:3019  [s5] raft error: node 4 claims to not contain store 4 for replica {4 4 0}: store 4 was not found
I161130 08:19:50.836595 46392 storage/raft_transport.go:437  raft transport stream to node 4 established
W161130 08:19:50.836756 46427 storage/raft_transport.go:258  unable to accept Raft message from {NodeID:2 StoreID:2 ReplicaID:0}: no handler registered for {NodeID:4 StoreID:4 ReplicaID:0}
W161130 08:19:50.836853 46425 storage/store.go:3019  [s2] raft error: node 4 claims to not contain store 4 for replica {4 4 0}: store 4 was not found
I161130 08:19:50.844391 46428 storage/raft_transport.go:437  raft transport stream to node 4 established
W161130 08:19:50.844499 46394 storage/raft_transport.go:258  unable to accept Raft message from {NodeID:5 StoreID:5 ReplicaID:0}: no handler registered for {NodeID:4 StoreID:4 ReplicaID:0}
W161130 08:19:50.844609 46430 storage/store.go:3019  [s5] raft error: node 4 claims to not contain store 4 for replica {4 4 0}: store 4 was not found
I161130 08:19:50.936523 46467 storage/raft_transport.go:437  raft transport stream to node 4 established
W161130 08:19:50.936644 46458 storage/raft_transport.go:258  unable to accept Raft message from {NodeID:2 StoreID:2 ReplicaID:0}: no handler registered for {NodeID:4 StoreID:4 ReplicaID:0}
W161130 08:19:50.936758 46469 storage/store.go:3019  [s2] raft error: node 4 claims to not contain store 4 for replica {4 4 0}: store 4 was not found
I161130 08:19:50.944370 46470 storage/raft_transport.go:437  raft transport stream to node 4 established
W161130 08:19:50.944474 46442 storage/raft_transport.go:258  unable to accept Raft message from {NodeID:5 StoreID:5 ReplicaID:0}: no handler registered for {NodeID:4 StoreID:4 ReplicaID:0}
W161130 08:19:50.944596 46472 storage/store.go:3019  [s5] raft error: node 4 claims to not contain store 4 for replica {4 4 0}: store 4 was not found
I161130 08:19:51.036477 46443 storage/raft_transport.go:437  raft transport stream to node 4 established
W161130 08:19:51.036657 46175 storage/raft_transport.go:258  unable to accept Raft message from {NodeID:2 StoreID:2 ReplicaID:0}: no handler registered for {NodeID:4 StoreID:4 ReplicaID:0}
W161130 08:19:51.036782 46445 storage/store.go:3019  [s2] raft error: node 4 claims to not contain store 4 for replica {4 4 0}: store 4 was not found
I161130 08:19:51.044372 46459 storage/raft_transport.go:437  raft transport stream to node 4 established
W161130 08:19:51.044473 46447 storage/raft_transport.go:258  unable to accept Raft message from {NodeID:5 StoreID:5 ReplicaID:0}: no handler registered for {NodeID:4 StoreID:4 ReplicaID:0}
W161130 08:19:51.044572 46461 storage/store.go:3019  [s5] raft error: node 4 claims to not contain store 4 for replica {4 4 0}: store 4 was not found
I161130 08:19:51.093673 46523 util/stop/stopper.go:468  quiescing; tasks left:
1      storage/client_test.go:490
I161130 08:19:51.093709 46524 util/stop/stopper.go:468  quiescing; tasks left:
1      storage/queue.go:478
1      storage/client_test.go:490
W161130 08:19:51.093754 32826 storage/replica.go:1930  [s2,r11/2:{"m"-/Max},@c42104e400] shutdown cancellation after 45.6s of attempting command PushTxn [/Local/Range/"m"/RangeDescriptor,/Min)
I161130 08:19:51.093801 46524 util/stop/stopper.go:468  quiescing; tasks left:
1      storage/queue.go:478
E161130 08:19:51.093932 32204 storage/queue.go:576  [replicaGC,s2,r11/2:{"m"-/Max},@c42104e400] result is ambiguous (server shutdown)
I161130 08:19:51.093979 46522 util/stop/stopper.go:396  stop has been called, stopping or quiescing all running tasks
I161130 08:19:51.094092 46522 util/stop/stopper.go:396  stop has been called, stopping or quiescing all running tasks
I161130 08:19:51.094209 46522 util/stop/stopper.go:396  stop has been called, stopping or quiescing all running tasks
I161130 08:19:51.094340 46522 util/stop/stopper.go:396  stop has been called, stopping or quiescing all running tasks
I161130 08:19:51.094461 46522 util/stop/stopper.go:396  stop has been called, stopping or quiescing all running tasks
I161130 08:19:51.094569 46522 util/stop/stopper.go:396  stop has been called, stopping or quiescing all running tasks
I161130 08:19:51.094788 32356 vendor/google.golang.org/grpc/transport/http2_server.go:276  transport: http2Server.HandleStreams failed to read frame: read tcp 127.0.0.1:36705->127.0.0.1:52000: use of closed network connection
I161130 08:19:51.094809 32348 vendor/google.golang.org/grpc/transport/http2_server.go:276  transport: http2Server.HandleStreams failed to read frame: read tcp 127.0.0.1:37954->127.0.0.1:35175: use of closed network connection
I161130 08:19:51.094815 32128 vendor/google.golang.org/grpc/transport/http2_client.go:1053  transport: http2Client.notifyError got notified that the client transport was broken EOF.
W161130 08:19:51.094846 32469 storage/raft_transport.go:443  raft transport stream to node 3 failed: EOF
I161130 08:19:51.094869 32370 vendor/google.golang.org/grpc/clientconn.go:667  grpc: addrConn.resetTransport failed to create client transport: connection error: desc = "transport: dial tcp 127.0.0.1:36705: context canceled"; Reconnecting to {"127.0.0.1:36705" <nil>}
I161130 08:19:51.094878 32370 vendor/google.golang.org/grpc/clientconn.go:767  grpc: addrConn.transportMonitor exits due to: grpc: the connection is closing
I161130 08:19:51.094889 32062 vendor/google.golang.org/grpc/transport/http2_server.go:276  transport: http2Server.HandleStreams failed to read frame: read tcp 127.0.0.1:56412->127.0.0.1:55582: use of closed network connection
I161130 08:19:51.094897 32124 vendor/google.golang.org/grpc/transport/http2_server.go:276  transport: http2Server.HandleStreams failed to read frame: read tcp 127.0.0.1:47161->127.0.0.1:48186: use of closed network connection
I161130 08:19:51.094901 32176 vendor/google.golang.org/grpc/transport/http2_server.go:276  transport: http2Server.HandleStreams failed to read frame: read tcp 127.0.0.1:59066->127.0.0.1:60169: use of closed network connection
I161130 08:19:51.094910 46522 util/stop/stopper.go:396  stop has been called, stopping or quiescing all running tasks
I161130 08:19:51.095480 46522 util/stop/stopper.go:396  stop has been called, stopping or quiescing all running tasks
I161130 08:19:51.095562 46522 util/stop/stopper.go:396  stop has been called, stopping or quiescing all running tasks
I161130 08:19:51.095671 46522 util/stop/stopper.go:396  stop has been called, stopping or quiescing all running tasks
I161130 08:19:51.095765 46522 util/stop/stopper.go:396  stop has been called, stopping or quiescing all running tasks
I161130 08:19:51.095941 46522 util/stop/stopper.go:396  stop has been called, stopping or quiescing all running tasks
	testing.go:119: storage/client_split_test.go:980, condition failed to evaluate within 45s: expected [0 0 0 2 5 5], got [0 2 0 2 5 5]
```

### LINKED ISSUE #12258: storage: Double-applied command in TestSplitSnapshotRace_SplitWins
Found while investigating #10698 and #11709. Those issues relate to a replica not getting GC'd when it should, but while stressing the tests I saw a more worrying failure (at commit e71bf9d675):

```
--- FAIL: TestSplitSnapshotRace_SplitWins (46.82s)
	soon.go:43: storage/client_split_test.go:1001, condition failed to evaluate within 45s: expected [0 0 0 2 5 5], got [0 0 0 2 8 8]
```

That means that an `Increment(3)` command is getting applied twice. Since it happened on both of the live replicas, it's probably a reproposal and a failure of our replay protection. 

The full log follows (well, most of it. The same messages repeat for the remaining 45s)
```
I161211 12:51:34.016433 1 rand.go:76  Random seed: 5032174770022480193
I161211 12:51:34.017890 19 storage/engine/rocksdb.go:340  opening in memory rocksdb instance
I161211 12:51:34.019090 19 gossip/gossip.go:248  [n?] initial resolvers: []
W161211 12:51:34.019121 19 gossip/gossip.go:1124  [n?] no resolvers found; use --join to specify a connected node
I161211 12:51:34.019164 19 base/node_id.go:62  NodeID set to 1
I161211 12:51:34.022058 19 storage/store.go:1240  [n1,s1]: failed initial metrics computation: [n1,s1]: system config not yet available
I161211 12:51:34.022166 19 gossip/gossip.go:290  [n1] NodeDescriptor set to node_id:1 address:<network_field:"tcp" address_field:"127.0.0.1:64516" > attrs:<> locality:<> 
I161211 12:51:34.023165 66 storage/replica_proposal.go:360  [s1,r1/1:/M{in-ax},@c420206000] new range lease repl={1 1 1} start=0.000000000,0 exp=0.900000123,7 pro=0.000000123,8 following repl={0 0 0} start=0.000000000,0 exp=0.000000000,0 [physicalTime=1970-01-01 00:00:00.000000123 +0000 UTC]
I161211 12:51:34.026603 19 storage/engine/rocksdb.go:340  opening in memory rocksdb instance
I161211 12:51:34.028202 19 gossip/gossip.go:248  [n?] initial resolvers: [127.0.0.1:64516]
W161211 12:51:34.028248 19 gossip/gossip.go:1126  [n?] no incoming or outgoing connections
I161211 12:51:34.028311 19 base/node_id.go:62  NodeID set to 2
I161211 12:51:34.030249 19 storage/store.go:1240  [n2,s2]: failed initial metrics computation: [n2,s2]: system config not yet available
I161211 12:51:34.030310 19 gossip/gossip.go:290  [n2] NodeDescriptor set to node_id:2 address:<network_field:"tcp" address_field:"127.0.0.1:64518" > attrs:<> locality:<> 
I161211 12:51:34.030706 64 gossip/client.go:125  [n2] started gossip client to 127.0.0.1:64516
I161211 12:51:34.107997 19 storage/engine/rocksdb.go:340  opening in memory rocksdb instance
I161211 12:51:34.110682 19 gossip/gossip.go:248  [n?] initial resolvers: [127.0.0.1:64516]
W161211 12:51:34.110731 19 gossip/gossip.go:1126  [n?] no incoming or outgoing connections
I161211 12:51:34.110846 19 base/node_id.go:62  NodeID set to 3
I161211 12:51:34.113138 19 storage/store.go:1240  [n3,s3]: failed initial metrics computation: [n3,s3]: system config not yet available
I161211 12:51:34.113187 19 gossip/gossip.go:290  [n3] NodeDescriptor set to node_id:3 address:<network_field:"tcp" address_field:"127.0.0.1:64520" > attrs:<> locality:<> 
I161211 12:51:34.113234 30 gossip/client.go:125  [n3] started gossip client to 127.0.0.1:64516
I161211 12:51:34.115367 19 storage/engine/rocksdb.go:340  opening in memory rocksdb instance
I161211 12:51:34.116170 19 gossip/gossip.go:248  [n?] initial resolvers: [127.0.0.1:64516]
W161211 12:51:34.116182 19 gossip/gossip.go:1126  [n?] no incoming or outgoing connections
I161211 12:51:34.116208 19 base/node_id.go:62  NodeID set to 4
I161211 12:51:34.117580 19 storage/store.go:1240  [n4,s4]: failed initial metrics computation: [n4,s4]: system config not yet available
I161211 12:51:34.117624 19 gossip/gossip.go:290  [n4] NodeDescriptor set to node_id:4 address:<network_field:"tcp" address_field:"127.0.0.1:64522" > attrs:<> locality:<> 
I161211 12:51:34.117660 220 gossip/client.go:125  [n4] started gossip client to 127.0.0.1:64516
I161211 12:51:34.119796 19 storage/engine/rocksdb.go:340  opening in memory rocksdb instance
I161211 12:51:34.120718 19 gossip/gossip.go:248  [n?] initial resolvers: [127.0.0.1:64516]
W161211 12:51:34.120731 19 gossip/gossip.go:1126  [n?] no incoming or outgoing connections
I161211 12:51:34.120758 19 base/node_id.go:62  NodeID set to 5
I161211 12:51:34.123903 19 storage/store.go:1240  [n5,s5]: failed initial metrics computation: [n5,s5]: system config not yet available
I161211 12:51:34.123965 19 gossip/gossip.go:290  [n5] NodeDescriptor set to node_id:5 address:<network_field:"tcp" address_field:"127.0.0.1:64524" > attrs:<> locality:<> 
I161211 12:51:34.125761 312 gossip/client.go:125  [n5] started gossip client to 127.0.0.1:64516
I161211 12:51:34.126472 317 gossip/server.go:263  [n1] refusing gossip from node 5 (max 3 conns); forwarding to 3 ({tcp 127.0.0.1:64520})
I161211 12:51:34.126621 317 gossip/server.go:263  [n1] refusing gossip from node 5 (max 3 conns); forwarding to 3 ({tcp 127.0.0.1:64520})
I161211 12:51:34.127480 317 gossip/server.go:263  [n1] refusing gossip from node 5 (max 3 conns); forwarding to 3 ({tcp 127.0.0.1:64520})
I161211 12:51:34.127596 317 gossip/server.go:263  [n1] refusing gossip from node 5 (max 3 conns); forwarding to 3 ({tcp 127.0.0.1:64520})
I161211 12:51:34.127700 312 gossip/client.go:130  [n5] closing client to node 1 (127.0.0.1:64516): received forward from node 1 to 3 (127.0.0.1:64520)
I161211 12:51:34.128013 320 gossip/client.go:125  [n5] started gossip client to 127.0.0.1:64520
I161211 12:51:34.201028 19 storage/engine/rocksdb.go:340  opening in memory rocksdb instance
I161211 12:51:34.201857 19 gossip/gossip.go:248  [n?] initial resolvers: [127.0.0.1:64516]
W161211 12:51:34.201872 19 gossip/gossip.go:1126  [n?] no incoming or outgoing connections
I161211 12:51:34.201905 19 base/node_id.go:62  NodeID set to 6
I161211 12:51:34.203197 19 storage/store.go:1240  [n6,s6]: failed initial metrics computation: [n6,s6]: system config not yet available
I161211 12:51:34.203219 402 gossip/client.go:125  [n6] started gossip client to 127.0.0.1:64516
I161211 12:51:34.203240 19 gossip/gossip.go:290  [n6] NodeDescriptor set to node_id:6 address:<network_field:"tcp" address_field:"127.0.0.1:64526" > attrs:<> locality:<> 
I161211 12:51:34.203397 357 gossip/server.go:263  [n1] refusing gossip from node 6 (max 3 conns); forwarding to 2 ({tcp 127.0.0.1:64518})
I161211 12:51:34.203535 357 gossip/server.go:263  [n1] refusing gossip from node 6 (max 3 conns); forwarding to 2 ({tcp 127.0.0.1:64518})
I161211 12:51:34.203747 402 gossip/client.go:130  [n6] closing client to node 1 (127.0.0.1:64516): received forward from node 1 to 2 (127.0.0.1:64518)
I161211 12:51:34.203868 435 gossip/client.go:125  [n6] started gossip client to 127.0.0.1:64518
I161211 12:51:34.206290 19 storage/replica_command.go:2389  [s1,r1/1:/M{in-ax},@c420206000] initiating a split of this range at key /System/Max [r2]
E161211 12:51:34.208751 25 storage/queue.go:613  [replicate,s1,r1/1:/{Min-System/Max},@c420206000] purgatory: 0 of 0 stores with an attribute matching []; likely not enough nodes in cluster
E161211 12:51:34.208969 25 storage/queue.go:613  [replicate,s1,r2/1:/{System/Max-Max},@c420177400] purgatory: 0 of 0 stores with an attribute matching []; likely not enough nodes in cluster
E161211 12:51:34.209057 368 storage/queue.go:613  [replicate,s1,r1/1:/{Min-System/Max},@c420206000] purgatory: 0 of 0 stores with an attribute matching []; likely not enough nodes in cluster
I161211 12:51:34.209458 19 storage/replica_raftstorage.go:468  [s1,r2/1:/{System/Max-Max},@c420177400] generated preemptive snapshot 8dedd60e at index 11
I161211 12:51:34.210481 19 storage/store.go:3255  [s1,r2/1:/{System/Max-Max},@c420177400] streamed snapshot: kv pairs: 30, log entries: 1
I161211 12:51:34.210825 385 storage/replica_raftstorage.go:633  [s2,r2/?:{-},@c4202f0500] applying preemptive snapshot at index 11 (id=8dedd60e, encoded size=3539, 1 rocksdb batches, 1 log entries)
I161211 12:51:34.211104 385 storage/replica_raftstorage.go:641  [s2,r2/?:/{System/Max-Max},@c4202f0500] applied preemptive snapshot in 0ms [clear=0ms batch=0ms entries=0ms commit=0ms]
I161211 12:51:34.211728 19 storage/replica_command.go:3290  [s1,r2/1:/{System/Max-Max},@c420177400] change replicas: read existing descriptor range_id:2 start_key:"\005" end_key:"\377\377" replicas:<node_id:1 store_id:1 replica_id:1 > next_replica_id:2 
E161211 12:51:34.212050 368 storage/queue.go:613  [replicate,s1,r2/1:/{System/Max-Max},@c420177400] purgatory: 0 of 0 stores with an attribute matching []; likely not enough nodes in cluster
E161211 12:51:34.212107 368 storage/queue.go:613  [replicate,s1,r1/1:/{Min-System/Max},@c420206000] purgatory: 0 of 0 stores with an attribute matching []; likely not enough nodes in cluster
W161211 12:51:34.212464 469 storage/stores.go:218  range not contained in one range: [/Meta2/Max,"\x05\x00"), but have [/Min,/System/Max)
I161211 12:51:34.213196 473 storage/replica.go:2334  [s1,r2/1:/{System/Max-Max},@c420177400] proposing ADD_REPLICA {NodeID:2 StoreID:2 ReplicaID:2}: [{NodeID:1 StoreID:1 ReplicaID:1} {NodeID:2 StoreID:2 ReplicaID:2}]
I161211 12:51:34.213953 19 storage/replica_raftstorage.go:468  [s1,r2/1:/{System/Max-Max},@c420177400] generated preemptive snapshot f91dd110 at index 13
I161211 12:51:34.214247 490 storage/raft_transport.go:437  raft transport stream to node 1 established
I161211 12:51:34.214324 19 storage/store.go:3255  [s1,r2/1:/{System/Max-Max},@c420177400] streamed snapshot: kv pairs: 32, log entries: 3
I161211 12:51:34.214523 505 storage/replica_raftstorage.go:633  [s3,r2/?:{-},@c420a74000] applying preemptive snapshot at index 13 (id=f91dd110, encoded size=4430, 1 rocksdb batches, 3 log entries)
I161211 12:51:34.214734 505 storage/replica_raftstorage.go:641  [s3,r2/?:/{System/Max-Max},@c420a74000] applied preemptive snapshot in 0ms [clear=0ms batch=0ms entries=0ms commit=0ms]
I161211 12:51:34.215160 19 storage/replica_command.go:3290  [s1,r2/1:/{System/Max-Max},@c420177400] change replicas: read existing descriptor range_id:2 start_key:"\005" end_key:"\377\377" replicas:<node_id:1 store_id:1 replica_id:1 > replicas:<node_id:2 store_id:2 replica_id:2 > next_replica_id:3 
I161211 12:51:34.216351 521 storage/replica.go:2334  [s1,r2/1:/{System/Max-Max},@c420177400] proposing ADD_REPLICA {NodeID:3 StoreID:3 ReplicaID:3}: [{NodeID:1 StoreID:1 ReplicaID:1} {NodeID:2 StoreID:2 ReplicaID:2} {NodeID:3 StoreID:3 ReplicaID:3}]
I161211 12:51:34.217379 19 storage/replica_raftstorage.go:468  [s1,r2/1:/{System/Max-Max},@c420177400] generated preemptive snapshot db7da2f8 at index 17
I161211 12:51:34.217760 19 storage/store.go:3255  [s1,r2/1:/{System/Max-Max},@c420177400] streamed snapshot: kv pairs: 33, log entries: 7
I161211 12:51:34.218004 525 storage/replica_raftstorage.go:633  [s4,r2/?:{-},@c420b22000] applying preemptive snapshot at index 17 (id=db7da2f8, encoded size=5648, 1 rocksdb batches, 7 log entries)
I161211 12:51:34.218314 525 storage/replica_raftstorage.go:641  [s4,r2/?:/{System/Max-Max},@c420b22000] applied preemptive snapshot in 0ms [clear=0ms batch=0ms entries=0ms commit=0ms]
I161211 12:51:34.218854 19 storage/replica_command.go:3290  [s1,r2/1:/{System/Max-Max},@c420177400] change replicas: read existing descriptor range_id:2 start_key:"\005" end_key:"\377\377" replicas:<node_id:1 store_id:1 replica_id:1 > replicas:<node_id:2 store_id:2 replica_id:2 > replicas:<node_id:3 store_id:3 replica_id:3 > next_replica_id:4 
I161211 12:51:34.220350 480 storage/replica.go:2334  [s1,r2/1:/{System/Max-Max},@c420177400] proposing ADD_REPLICA {NodeID:4 StoreID:4 ReplicaID:4}: [{NodeID:1 StoreID:1 ReplicaID:1} {NodeID:2 StoreID:2 ReplicaID:2} {NodeID:3 StoreID:3 ReplicaID:3} {NodeID:4 StoreID:4 ReplicaID:4}]
I161211 12:51:34.229422 19 storage/replica_command.go:3290  [s1,r2/1:/{System/Max-Max},@c420177400] change replicas: read existing descriptor range_id:2 start_key:"\005" end_key:"\377\377" replicas:<node_id:1 store_id:1 replica_id:1 > replicas:<node_id:2 store_id:2 replica_id:2 > replicas:<node_id:3 store_id:3 replica_id:3 > replicas:<node_id:4 store_id:4 replica_id:4 > next_replica_id:5 
I161211 12:51:34.230997 563 storage/replica.go:2334  [s1,r2/1:/{System/Max-Max},@c420177400] proposing REMOVE_REPLICA {NodeID:1 StoreID:1 ReplicaID:1}: [{NodeID:4 StoreID:4 ReplicaID:4} {NodeID:2 StoreID:2 ReplicaID:2} {NodeID:3 StoreID:3 ReplicaID:3}]
I161211 12:51:34.232728 26 storage/store.go:2069  [replicaGC,s1,r2/1:/{System/Max-Max},@c420177400] removing replica
W161211 12:51:34.233087 492 storage/store.go:3121  [s2] got error from range 2, replica {1 1 1}: raft group deleted
E161211 12:51:34.233326 368 storage/queue.go:613  [replicate,s1,r1/1:/{Min-System/Max},@c420206000] purgatory: 0 of 0 stores with an attribute matching []; likely not enough nodes in cluster
E161211 12:51:34.233826 19 storage/client_test.go:1126  heartbeat failed on epoch increment
E161211 12:51:34.234258 368 storage/queue.go:613  [replicate,s1,r1/1:/{Min-System/Max},@c420206000] purgatory: 0 of 0 stores with an attribute matching []; likely not enough nodes in cluster
E161211 12:51:34.234702 19 storage/client_test.go:1126  heartbeat failed on epoch increment
E161211 12:51:34.235442 19 storage/client_test.go:1126  heartbeat failed on epoch increment
E161211 12:51:34.235600 368 storage/queue.go:613  [replicate,s1,r1/1:/{Min-System/Max},@c420206000] purgatory: 0 of 0 stores with an attribute matching []; likely not enough nodes in cluster
E161211 12:51:34.236091 368 storage/queue.go:613  [replicate,s1,r1/1:/{Min-System/Max},@c420206000] purgatory: 0 of 0 stores with an attribute matching []; likely not enough nodes in cluster
E161211 12:51:34.236594 19 storage/client_test.go:1126  heartbeat failed on epoch increment
E161211 12:51:34.237382 368 storage/queue.go:613  [replicate,s1,r1/1:/{Min-System/Max},@c420206000] purgatory: 0 of 0 stores with an attribute matching []; likely not enough nodes in cluster
E161211 12:51:34.237885 19 storage/client_test.go:1126  heartbeat failed on epoch increment
E161211 12:51:34.238480 368 storage/queue.go:613  [replicate,s1,r1/1:/{Min-System/Max},@c420206000] purgatory: 0 of 0 stores with an attribute matching []; likely not enough nodes in cluster
E161211 12:51:34.239105 19 storage/client_test.go:1126  heartbeat failed on epoch increment
I161211 12:51:34.239191 19 util/stop/stopper.go:396  stop has been called, stopping or quiescing all running tasks
E161211 12:51:34.240280 368 storage/queue.go:613  [replicate,s1,r1/1:/{Min-System/Max},@c420206000] purgatory: 0 of 0 stores with an attribute matching []; likely not enough nodes in cluster
E161211 12:51:34.240841 19 storage/client_test.go:1126  heartbeat failed on epoch increment
E161211 12:51:34.241599 19 storage/client_test.go:1126  heartbeat failed on epoch increment
E161211 12:51:34.241752 368 storage/queue.go:613  [replicate,s1,r1/1:/{Min-System/Max},@c420206000] purgatory: 0 of 0 stores with an attribute matching []; likely not enough nodes in cluster
E161211 12:51:34.242160 368 storage/queue.go:613  [replicate,s1,r1/1:/{Min-System/Max},@c420206000] purgatory: 0 of 0 stores with an attribute matching []; likely not enough nodes in cluster
E161211 12:51:34.242693 19 storage/client_test.go:1126  heartbeat failed on epoch increment
E161211 12:51:34.242775 19 storage/client_test.go:1113  node unavailable; try another peer
E161211 12:51:34.243696 368 storage/queue.go:613  [replicate,s1,r1/1:/{Min-System/Max},@c420206000] purgatory: 0 of 0 stores with an attribute matching []; likely not enough nodes in cluster
E161211 12:51:34.243810 19 storage/client_test.go:1126  heartbeat failed on epoch increment
E161211 12:51:34.244992 19 storage/client_test.go:1126  heartbeat failed on epoch increment
E161211 12:51:34.245141 368 storage/queue.go:613  [replicate,s1,r1/1:/{Min-System/Max},@c420206000] purgatory: 0 of 0 stores with an attribute matching []; likely not enough nodes in cluster
W161211 12:51:34.274427 532 storage/raft_transport.go:258  unable to accept Raft message from {NodeID:1 StoreID:1 ReplicaID:0}: no handler registered for {NodeID:4 StoreID:4 ReplicaID:0}
W161211 12:51:34.274753 547 storage/store.go:3117  [s1] raft error: node 4 claims to not contain store 4 for replica {4 4 0}: store 4 was not found
W161211 12:51:34.274802 481 storage/raft_transport.go:443  raft transport stream to node 4 failed: store 4 was not found
E161211 12:51:34.294969 368 storage/queue.go:613  [replicate,s1,r1/1:/{Min-System/Max},@c420206000] purgatory: 0 of 0 stores with an attribute matching []; likely not enough nodes in cluster
E161211 12:51:34.307698 368 storage/queue.go:613  [replicate,s1,r1/1:/{Min-System/Max},@c420206000] purgatory: 0 of 0 stores with an attribute matching []; likely not enough nodes in cluster
E161211 12:51:34.385046 368 storage/queue.go:613  [replicate,s1,r1/1:/{Min-System/Max},@c420206000] purgatory: 0 of 0 stores with an attribute matching []; likely not enough nodes in cluster
E161211 12:51:34.385664 368 storage/queue.go:613  [replicate,s1,r1/1:/{Min-System/Max},@c420206000] purgatory: 0 of 0 stores with an attribute matching []; likely not enough nodes in cluster
E161211 12:51:34.393789 368 storage/queue.go:613  [replicate,s1,r1/1:/{Min-System/Max},@c420206000] purgatory: 0 of 0 stores with an attribute matching []; likely not enough nodes in cluster
W161211 12:51:34.431959 492 storage/store.go:3121  [s2] got error from range 2, replica {1 1 1}: raft group deleted
E161211 12:51:34.474889 368 storage/queue.go:613  [replicate,s1,r1/1:/{Min-System/Max},@c420206000] purgatory: 0 of 0 stores with an attribute matching []; likely not enough nodes in cluster
E161211 12:51:34.486323 368 storage/queue.go:613  [replicate,s1,r1/1:/{Min-System/Max},@c420206000] purgatory: 0 of 0 stores with an attribute matching []; likely not enough nodes in cluster
I161211 12:51:34.513744 681 storage/raft_transport.go:437  raft transport stream to node 4 established
W161211 12:51:34.513859 708 storage/raft_transport.go:258  unable to accept Raft message from {NodeID:3 StoreID:3 ReplicaID:3}: no handler registered for {NodeID:4 StoreID:4 ReplicaID:4}
W161211 12:51:34.513952 695 storage/store.go:3117  [s3] raft error: node 4 claims to not contain store 4 for replica {4 4 4}: store 4 was not found
I161211 12:51:34.532075 682 storage/raft_transport.go:437  raft transport stream to node 4 established
W161211 12:51:34.532238 684 storage/raft_transport.go:258  unable to accept Raft message from {NodeID:2 StoreID:2 ReplicaID:2}: no handler registered for {NodeID:4 StoreID:4 ReplicaID:4}
W161211 12:51:34.532351 710 storage/store.go:3117  [s2] raft error: node 4 claims to not contain store 4 for replica {4 4 4}: store 4 was not found
E161211 12:51:34.564468 368 storage/queue.go:613  [replicate,s1,r1/1:/{Min-System/Max},@c420206000] purgatory: 0 of 0 stores with an attribute matching []; likely not enough nodes in cluster
E161211 12:51:34.564809 368 storage/queue.go:613  [replicate,s1,r1/1:/{Min-System/Max},@c420206000] purgatory: 0 of 0 stores with an attribute matching []; likely not enough nodes in cluster
E161211 12:51:34.572751 368 storage/queue.go:613  [replicate,s1,r1/1:/{Min-System/Max},@c420206000] purgatory: 0 of 0 stores with an attribute matching []; likely not enough nodes in cluster
E161211 12:51:34.658159 368 storage/queue.go:613  [replicate,s1,r1/1:/{Min-System/Max},@c420206000] purgatory: 0 of 0 stores with an attribute matching []; likely not enough nodes in cluster
E161211 12:51:34.665895 368 storage/queue.go:613  [replicate,s1,r1/1:/{Min-System/Max},@c420206000] purgatory: 0 of 0 stores with an attribute matching []; likely not enough nodes in cluster
E161211 12:51:34.747869 368 storage/queue.go:613  [replicate,s1,r1/1:/{Min-System/Max},@c420206000] purgatory: 0 of 0 stores with an attribute matching []; likely not enough nodes in cluster
E161211 12:51:34.748602 368 storage/queue.go:613  [replicate,s1,r1/1:/{Min-System/Max},@c420206000] purgatory: 0 of 0 stores with an attribute matching []; likely not enough nodes in cluster
E161211 12:51:34.752374 368 storage/queue.go:613  [replicate,s1,r1/1:/{Min-System/Max},@c420206000] purgatory: 0 of 0 stores with an attribute matching []; likely not enough nodes in cluster
I161211 12:51:34.831896 731 storage/raft_transport.go:437  raft transport stream to node 4 established
W161211 12:51:34.832073 733 storage/raft_transport.go:258  unable to accept Raft message from {NodeID:2 StoreID:2 ReplicaID:2}: no handler registered for {NodeID:4 StoreID:4 ReplicaID:4}
W161211 12:51:34.832208 760 storage/store.go:3117  [s2] raft error: node 4 claims to not contain store 4 for replica {4 4 4}: store 4 was not found
W161211 12:51:34.832291 733 storage/raft_transport.go:258  unable to accept Raft message from {NodeID:2 StoreID:2 ReplicaID:2}: no handler registered for {NodeID:4 StoreID:4 ReplicaID:4}
I161211 12:51:34.833063 104 storage/replica_proposal.go:360  [s2,r2/2:/{System/Max-Max},@c4202f0500] new range lease repl={2 2 2} start=0.900000123,8 exp=2.700000125,21 pro=1.800000125,22 following repl={1 1 1} start=0.000000000,0 exp=0.900000123,7 pro=0.000000123,8 [physicalTime=1970-01-01 00:00:03.600000127 +0000 UTC]
E161211 12:51:34.834728 368 storage/queue.go:613  [replicate,s1,r1/1:/{Min-System/Max},@c420206000] purgatory: 0 of 0 stores with an attribute matching []; likely not enough nodes in cluster
I161211 12:51:34.836503 632 storage/replica_command.go:2389  [s2,r2/2:/{System/Max-Max},@c4202f0500] initiating a split of this range at key "m" [r11]
E161211 12:51:34.845472 368 storage/queue.go:613  [replicate,s1,r1/1:/{Min-System/Max},@c420206000] purgatory: 0 of 0 stores with an attribute matching []; likely not enough nodes in cluster
E161211 12:51:34.924618 368 storage/queue.go:613  [replicate,s1,r1/1:/{Min-System/Max},@c420206000] purgatory: 0 of 0 stores with an attribute matching []; likely not enough nodes in cluster
E161211 12:51:34.925579 368 storage/queue.go:613  [replicate,s1,r1/1:/{Min-System/Max},@c420206000] purgatory: 0 of 0 stores with an attribute matching []; likely not enough nodes in cluster
I161211 12:51:34.933687 819 storage/raft_transport.go:437  raft transport stream to node 4 established
E161211 12:51:34.934634 368 storage/queue.go:613  [replicate,s1,r1/1:/{Min-System/Max},@c420206000] purgatory: 0 of 0 stores with an attribute matching []; likely not enough nodes in cluster
W161211 12:51:34.935209 836 storage/raft_transport.go:258  unable to accept Raft message from {NodeID:2 StoreID:2 ReplicaID:0}: no handler registered for {NodeID:4 StoreID:4 ReplicaID:0}
W161211 12:51:34.935372 821 storage/store.go:3117  [s2] raft error: node 4 claims to not contain store 4 for replica {4 4 0}: store 4 was not found
I161211 12:51:34.952597 19 storage/replica_raftstorage.go:468  [s2,r11/2:{"m"-/Max},@c4202f0a00] generated preemptive snapshot 69389f96 at index 10
I161211 12:51:34.953099 19 storage/store.go:3255  [s2,r11/2:{"m"-/Max},@c4202f0a00] streamed snapshot: kv pairs: 29, log entries: 0
I161211 12:51:34.953312 809 storage/replica_raftstorage.go:633  [s5,r11/?:{-},@c420176a00] applying preemptive snapshot at index 10 (id=69389f96, encoded size=3536, 1 rocksdb batches, 0 log entries)
I161211 12:51:34.953540 809 storage/replica_raftstorage.go:641  [s5,r11/?:{"m"-/Max},@c420176a00] applied preemptive snapshot in 0ms [clear=0ms batch=0ms entries=0ms commit=0ms]
I161211 12:51:34.954005 19 storage/replica_command.go:3290  [s2,r11/2:{"m"-/Max},@c4202f0a00] change replicas: read existing descriptor range_id:11 start_key:"m" end_key:"\377\377" replicas:<node_id:4 store_id:4 replica_id:1 > replicas:<node_id:2 store_id:2 replica_id:2 > replicas:<node_id:3 store_id:3 replica_id:3 > next_replica_id:4 
I161211 12:51:34.954526 855 storage/raft_transport.go:437  raft transport stream to node 4 established
W161211 12:51:34.955040 823 storage/raft_transport.go:258  unable to accept Raft message from {NodeID:2 StoreID:2 ReplicaID:2}: no handler registered for {NodeID:4 StoreID:4 ReplicaID:1}
W161211 12:51:34.955183 857 storage/store.go:3117  [s2] raft error: node 4 claims to not contain store 4 for replica {4 4 1}: store 4 was not found
I161211 12:51:34.955384 824 storage/raft_transport.go:437  raft transport stream to node 4 established
W161211 12:51:34.955559 859 storage/raft_transport.go:258  unable to accept Raft message from {NodeID:2 StoreID:2 ReplicaID:2}: no handler registered for {NodeID:4 StoreID:4 ReplicaID:1}
W161211 12:51:34.955663 811 storage/store.go:3117  [s2] raft error: node 4 claims to not contain store 4 for replica {4 4 1}: store 4 was not found
I161211 12:51:34.957018 827 storage/replica.go:2334  [s2,r11/2:{"m"-/Max},@c4202f0a00] proposing ADD_REPLICA {NodeID:5 StoreID:5 ReplicaID:4}: [{NodeID:4 StoreID:4 ReplicaID:1} {NodeID:2 StoreID:2 ReplicaID:2} {NodeID:3 StoreID:3 ReplicaID:3} {NodeID:5 StoreID:5 ReplicaID:4}]
E161211 12:51:35.014456 368 storage/queue.go:613  [replicate,s1,r1/1:/{Min-System/Max},@c420206000] purgatory: 0 of 0 stores with an attribute matching []; likely not enough nodes in cluster
I161211 12:51:35.014966 19 storage/replica_raftstorage.go:468  [s2,r11/2:{"m"-/Max},@c4202f0a00] generated preemptive snapshot 75ac0864 at index 15
I161211 12:51:35.015330 19 storage/store.go:3255  [s2,r11/2:{"m"-/Max},@c4202f0a00] streamed snapshot: kv pairs: 30, log entries: 5
I161211 12:51:35.015534 882 storage/replica_raftstorage.go:633  [s6,r11/?:{-},@c420a74500] applying preemptive snapshot at index 15 (id=75ac0864, encoded size=5036, 1 rocksdb batches, 5 log entries)
I161211 12:51:35.015770 882 storage/replica_raftstorage.go:641  [s6,r11/?:{"m"-/Max},@c420a74500] applied preemptive snapshot in 0ms [clear=0ms batch=0ms entries=0ms commit=0ms]
I161211 12:51:35.016112 19 storage/replica_command.go:3290  [s2,r11/2:{"m"-/Max},@c4202f0a00] change replicas: read existing descriptor range_id:11 start_key:"m" end_key:"\377\377" replicas:<node_id:4 store_id:4 replica_id:1 > replicas:<node_id:2 store_id:2 replica_id:2 > replicas:<node_id:3 store_id:3 replica_id:3 > replicas:<node_id:5 store_id:5 replica_id:4 > next_replica_id:5 
I161211 12:51:35.017365 885 storage/replica.go:2334  [s2,r11/2:{"m"-/Max},@c4202f0a00] proposing ADD_REPLICA {NodeID:6 StoreID:6 ReplicaID:5}: [{NodeID:4 StoreID:4 ReplicaID:1} {NodeID:2 StoreID:2 ReplicaID:2} {NodeID:3 StoreID:3 ReplicaID:3} {NodeID:5 StoreID:5 ReplicaID:4} {NodeID:6 StoreID:6 ReplicaID:5}]
I161211 12:51:35.020308 19 storage/replica_command.go:3290  [s2,r11/2:{"m"-/Max},@c4202f0a00] change replicas: read existing descriptor range_id:11 start_key:"m" end_key:"\377\377" replicas:<node_id:4 store_id:4 replica_id:1 > replicas:<node_id:2 store_id:2 replica_id:2 > replicas:<node_id:3 store_id:3 replica_id:3 > replicas:<node_id:5 store_id:5 replica_id:4 > replicas:<node_id:6 store_id:6 replica_id:5 > next_replica_id:6 
I161211 12:51:35.021605 874 storage/replica.go:2334  [s2,r11/2:{"m"-/Max},@c4202f0a00] proposing REMOVE_REPLICA {NodeID:3 StoreID:3 ReplicaID:3}: [{NodeID:4 StoreID:4 ReplicaID:1} {NodeID:2 StoreID:2 ReplicaID:2} {NodeID:6 StoreID:6 ReplicaID:5} {NodeID:5 StoreID:5 ReplicaID:4}]
I161211 12:51:35.023168 19 storage/replica_command.go:3290  [s2,r11/2:{"m"-/Max},@c4202f0a00] change replicas: read existing descriptor range_id:11 start_key:"m" end_key:"\377\377" replicas:<node_id:4 store_id:4 replica_id:1 > replicas:<node_id:2 store_id:2 replica_id:2 > replicas:<node_id:6 store_id:6 replica_id:5 > replicas:<node_id:5 store_id:5 replica_id:4 > next_replica_id:6 
I161211 12:51:35.024161 503 storage/store.go:3113  [s3,r11/3:{"m"-/Max},@c420176500] added to replica GC queue (peer suggestion)
I161211 12:51:35.025178 140 storage/store.go:2069  [replicaGC,s3,r11/3:{"m"-/Max},@c420176500] removing replica
I161211 12:51:35.026179 914 storage/replica.go:2334  [s2,r11/2:{"m"-/Max},@c4202f0a00] proposing REMOVE_REPLICA {NodeID:2 StoreID:2 ReplicaID:2}: [{NodeID:4 StoreID:4 ReplicaID:1} {NodeID:5 StoreID:5 ReplicaID:4} {NodeID:6 StoreID:6 ReplicaID:5}]
E161211 12:51:35.026486 368 storage/queue.go:613  [replicate,s1,r1/1:/{Min-System/Max},@c420206000] purgatory: 0 of 0 stores with an attribute matching []; likely not enough nodes in cluster
E161211 12:51:35.028515 368 storage/queue.go:613  [replicate,s1,r1/1:/{Min-System/Max},@c420206000] purgatory: 0 of 0 stores with an attribute matching []; likely not enough nodes in cluster
E161211 12:51:35.029213 913 storage/client_test.go:1126  heartbeat failed on epoch increment
E161211 12:51:35.030231 368 storage/queue.go:613  [replicate,s1,r1/1:/{Min-System/Max},@c420206000] purgatory: 0 of 0 stores with an attribute matching []; likely not enough nodes in cluster
I161211 12:51:35.030760 938 storage/raft_transport.go:437  raft transport stream to node 4 established
I161211 12:51:35.030922 888 storage/store.go:3113  [s2,r11/2:{"m"-/Max},@c4202f0a00] added to replica GC queue (peer suggestion)
E161211 12:51:35.030967 913 storage/client_test.go:1126  heartbeat failed on epoch increment
W161211 12:51:35.030986 925 storage/raft_transport.go:258  unable to accept Raft message from {NodeID:2 StoreID:2 ReplicaID:0}: no handler registered for {NodeID:4 StoreID:4 ReplicaID:0}
W161211 12:51:35.031072 923 storage/store.go:3117  [s2] raft error: node 4 claims to not contain store 4 for replica {4 4 0}: store 4 was not found
E161211 12:51:35.031540 368 storage/queue.go:613  [replicate,s1,r1/1:/{Min-System/Max},@c420206000] purgatory: 0 of 0 stores with an attribute matching []; likely not enough nodes in cluster
E161211 12:51:35.032220 913 storage/client_test.go:1126  heartbeat failed on epoch increment
E161211 12:51:35.032324 913 storage/client_test.go:1113  node unavailable; try another peer
E161211 12:51:35.033541 913 storage/client_test.go:1126  heartbeat failed on epoch increment
E161211 12:51:35.033785 368 storage/queue.go:613  [replicate,s1,r1/1:/{Min-System/Max},@c420206000] purgatory: 0 of 0 stores with an attribute matching []; likely not enough nodes in cluster
E161211 12:51:35.034305 368 storage/queue.go:613  [replicate,s1,r1/1:/{Min-System/Max},@c420206000] purgatory: 0 of 0 stores with an attribute matching []; likely not enough nodes in cluster
E161211 12:51:35.034748 913 storage/client_test.go:1126  heartbeat failed on epoch increment
E161211 12:51:35.108553 368 storage/queue.go:613  [replicate,s1,r1/1:/{Min-System/Max},@c420206000] purgatory: 0 of 0 stores with an attribute matching []; likely not enough nodes in cluster
E161211 12:51:35.109217 368 storage/queue.go:613  [replicate,s1,r1/1:/{Min-System/Max},@c420206000] purgatory: 0 of 0 stores with an attribute matching []; likely not enough nodes in cluster
E161211 12:51:35.111679 368 storage/queue.go:613  [replicate,s1,r1/1:/{Min-System/Max},@c420206000] purgatory: 0 of 0 stores with an attribute matching []; likely not enough nodes in cluster
I161211 12:51:35.180557 988 storage/raft_transport.go:437  raft transport stream to node 4 established
W161211 12:51:35.180762 945 storage/raft_transport.go:258  unable to accept Raft message from {NodeID:2 StoreID:2 ReplicaID:0}: no handler registered for {NodeID:4 StoreID:4 ReplicaID:0}
W161211 12:51:35.180882 990 storage/store.go:3117  [s2] raft error: node 4 claims to not contain store 4 for replica {4 4 0}: store 4 was not found
E161211 12:51:35.198523 368 storage/queue.go:613  [replicate,s1,r1/1:/{Min-System/Max},@c420206000] purgatory: 0 of 0 stores with an attribute matching []; likely not enough nodes in cluster
E161211 12:51:35.205817 368 storage/queue.go:613  [replicate,s1,r1/1:/{Min-System/Max},@c420206000] purgatory: 0 of 0 stores with an attribute matching []; likely not enough nodes in cluster
I161211 12:51:35.282018 1002 storage/raft_transport.go:437  raft transport stream to node 4 established
W161211 12:51:35.282279 1004 storage/raft_transport.go:258  unable to accept Raft message from {NodeID:2 StoreID:2 ReplicaID:0}: no handler registered for {NodeID:4 StoreID:4 ReplicaID:0}
W161211 12:51:35.282487 1027 storage/store.go:3117  [s2] raft error: node 4 claims to not contain store 4 for replica {4 4 0}: store 4 was not found
E161211 12:51:35.285013 368 storage/queue.go:613  [replicate,s1,r1/1:/{Min-System/Max},@c420206000] purgatory: 0 of 0 stores with an attribute matching []; likely not enough nodes in cluster
E161211 12:51:35.285640 368 storage/queue.go:613  [replicate,s1,r1/1:/{Min-System/Max},@c420206000] purgatory: 0 of 0 stores with an attribute matching []; likely not enough nodes in cluster
E161211 12:51:35.292169 368 storage/queue.go:613  [replicate,s1,r1/1:/{Min-System/Max},@c420206000] purgatory: 0 of 0 stores with an attribute matching []; likely not enough nodes in cluster
I161211 12:51:35.304920 1045 storage/raft_transport.go:437  raft transport stream to node 4 established
W161211 12:51:35.305160 1047 storage/raft_transport.go:258  unable to accept Raft message from {NodeID:6 StoreID:6 ReplicaID:5}: no handler registered for {NodeID:4 StoreID:4 ReplicaID:1}
W161211 12:51:35.305334 1035 storage/store.go:3117  [s6] raft error: node 4 claims to not contain store 4 for replica {4 4 1}: store 4 was not found
E161211 12:51:35.374976 368 storage/queue.go:613  [replicate,s1,r1/1:/{Min-System/Max},@c420206000] purgatory: 0 of 0 stores with an attribute matching []; likely not enough nodes in cluster
I161211 12:51:35.380884 1037 storage/raft_transport.go:437  raft transport stream to node 4 established
W161211 12:51:35.381128 1062 storage/raft_transport.go:258  unable to accept Raft message from {NodeID:2 StoreID:2 ReplicaID:0}: no handler registered for {NodeID:4 StoreID:4 ReplicaID:0}
W161211 12:51:35.381264 1021 storage/store.go:3117  [s2] raft error: node 4 claims to not contain store 4 for replica {4 4 0}: store 4 was not found
E161211 12:51:35.385969 368 storage/queue.go:613  [replicate,s1,r1/1:/{Min-System/Max},@c420206000] purgatory: 0 of 0 stores with an attribute matching []; likely not enough nodes in cluster
I161211 12:51:35.425583 1024 storage/raft_transport.go:437  raft transport stream to node 4 established
```

### PR DESCRIPTION
**Pull request by bdarnell**
They'd be canceled anyway when the ReplicaGCQueue processed them, but
canceling them is sometimes necessary to unblock operations that might
be necessary for the ReplicaGCQueue to do its job (in this case,
resolving intents on the meta records).

Fixes #10698
Fixes #11709

Return AmbiguousResultError instead of RangeNotFoundError for commands
canceled in this way. RangeNotFoundError is treated as a guarantee that
the command did not apply and triggers retries inappropriately.

Fixes #12258

Disable async intent resolution and the replication queue in the
SplitSnapshotRace tests to remove an additional source of flakiness.

---
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/12313)

### CODE REVIEW

**Comment by tamird** [comment]
Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[pkg/storage/client_split_test.go, line 929 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/12313#-KYsobTj0uaGrflV-Vx7:-KYsobTj0uaGrflV-Vx8:bdxgv8x) ([raw file](https://github.com/cockroachdb/cockroach/blob/4ef857dfb7f44337b0c5fb2603997e80b5ac66d1/pkg/storage/client_split_test.go#L929)):*
> ```Go
> 	mtc := &multiTestContext{storeConfig: &sc}
> 	mtc.Start(t, 6)
> 	defer mtc.Stop()
> ```

can you move this back above `Start`? That placement was intentional, as a failure during Start (possibly when changing things) will cause goroutine leaks otherwise.

---

*[pkg/storage/replica.go, line 761 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/12313#-KYsqAYD8kPYH4V3WT-9:-KYsqAYD8kPYH4V3WT-A:bnfdptu) ([raw file](https://github.com/cockroachdb/cockroach/blob/4ef857dfb7f44337b0c5fb2603997e80b5ac66d1/pkg/storage/replica.go#L761)):*
> ```Go
> 		resp := proposalResult{
> 			Reply:         &roachpb.BatchResponse{},
> 			Err:           roachpb.NewError(roachpb.NewAmbiguousResultError("removing replica")),
> ```

I don't understand why this was necessary - isn't it the job of `proposalRangeNoLongerExists` to ensure that this condition does not result in a re-proposal?

---

*[pkg/storage/replica_test.go, line 7136 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/12313#-KYsph_gEacXrdNVTR7G:-KYsph_gEacXrdNVTR7H:baswdfw) ([raw file](https://github.com/cockroachdb/cockroach/blob/4ef857dfb7f44337b0c5fb2603997e80b5ac66d1/pkg/storage/replica_test.go#L7136)):*
> ```Go
> 	tc.Start(t, stopper)
> 
> 	// Install a proposal function which drops all increment commands on the floor.
> ```

can you expand this comment to explain that this is done so that the increment remains "pending"?

---

*[pkg/storage/replica_test.go, line 7164 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/12313#-KYsppRQ3bI8JHwiXWyp:-KYsppRQ3bI8JHwiXWyq:bgyem88) ([raw file](https://github.com/cockroachdb/cockroach/blob/4ef857dfb7f44337b0c5fb2603997e80b5ac66d1/pkg/storage/replica_test.go#L7164)):*
> ```Go
> 	tc.repl.mu.Unlock()
> 
> 	pErr := <-errChan
> ```

probably should `select` on this channel before cancelling pending commands to assert that it remains hung until the call to cancelPendingCommandsLocked.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/12313)*

**Comment by tamird** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[pkg/storage/replica_test.go, line 7165 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/12313#-KYsqsM3oRY7vkzX4oya:-KYsqsM3oRY7vkzX4oyb:b-f84t7t) ([raw file](https://github.com/cockroachdb/cockroach/blob/4ef857dfb7f44337b0c5fb2603997e80b5ac66d1/pkg/storage/replica_test.go#L7165)):*
> ```Go
> 
> 	pErr := <-errChan
> 	if _, ok := pErr.GetDetail().(*roachpb.RangeNotFoundError); !ok {
> ```

looks like CI failed because you forgot to update this to `AmbiguousResultError`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/12313)*

**Comment by petermattis** [comment]
Review status: all files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---

*[pkg/storage/store.go, line 3105 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/12313#-KYtBpfKSabc-E-V6gox:-KYtBpfKSabc-E-V6goy:brpur83) ([raw file](https://github.com/cockroachdb/cockroach/blob/4ef857dfb7f44337b0c5fb2603997e80b5ac66d1/pkg/storage/store.go#L3105)):*
> ```Go
> 			}
> 			repl.mu.Lock()
> 			repl.cancelPendingCommandsLocked()
> ```

Are there any situations in which `ReplicaTooOldError` could be incorrect? I like that we're cancelling the pending commands earlier, but I'm worried we could cancel pending commands on a replica that is still valid. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/12313)*

**Comment by bdarnell** [comment]
Reviewed 3 of 5 files at r1.
Review status: 3 of 5 files reviewed at latest revision, 6 unresolved discussions.

---

*[pkg/storage/client_split_test.go, line 929 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/12313#-KYsobTj0uaGrflV-Vx7:-KYvWnqgqVvNQ0aLShe6:bge3p1o) ([raw file](https://github.com/cockroachdb/cockroach/blob/4ef857dfb7f44337b0c5fb2603997e80b5ac66d1/pkg/storage/client_split_test.go#L929)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

can you move this back above `Start`? That placement was intentional, as a failure during Start (possibly when changing things) will cause goroutine leaks otherwise.
</blockquote></details>

Done. Sorry, looked like a typo.

---

*[pkg/storage/replica.go, line 761 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/12313#-KYsqAYD8kPYH4V3WT-9:-KYvWwrUvd17yqvzR2xE:b-wc5qwy) ([raw file](https://github.com/cockroachdb/cockroach/blob/4ef857dfb7f44337b0c5fb2603997e80b5ac66d1/pkg/storage/replica.go#L761)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

I don't understand why this was necessary - isn't it the job of `proposalRangeNoLongerExists` to ensure that this condition does not result in a re-proposal?
</blockquote></details>

That prevents a reproposal from within the Replica; the AmbiguousResultError prevents retries at the DistSender. 

But now that I think about it, if this is doing anything I should be seeing these bubble up to the test's `t.Fatals`. The double-applied commands in #12258 must have gone away for some other reason (I think I stopped seeing them after pulling from master). In fact, addWriteCmd turns any errors after `proposalRangeNoLongerExists` into `AmbiguousResultErrors`, so it doesn't matter what error we return here. 

---

*[pkg/storage/replica_test.go, line 7136 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/12313#-KYsph_gEacXrdNVTR7G:-KYvYX5-EdbgS9NY2Zk3:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/4ef857dfb7f44337b0c5fb2603997e80b5ac66d1/pkg/storage/replica_test.go#L7136)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

can you expand this comment to explain that this is done so that the increment remains "pending"?
</blockquote></details>

Done.

---

*[pkg/storage/replica_test.go, line 7164 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/12313#-KYsppRQ3bI8JHwiXWyp:-KYvZQyGK10Aq66IBLxd:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/4ef857dfb7f44337b0c5fb2603997e80b5ac66d1/pkg/storage/replica_test.go#L7164)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

probably should `select` on this channel before cancelling pending commands to assert that it remains hung until the call to cancelPendingCommandsLocked.
</blockquote></details>

Done.

---

*[pkg/storage/replica_test.go, line 7165 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/12313#-KYsqsM3oRY7vkzX4oya:-KYvZ--LJRQGGl_S7Jan:b-feuxdd) ([raw file](https://github.com/cockroachdb/cockroach/blob/4ef857dfb7f44337b0c5fb2603997e80b5ac66d1/pkg/storage/replica_test.go#L7165)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

looks like CI failed because you forgot to update this to `AmbiguousResultError`
</blockquote></details>

Oops. Too focused on stressing the SplitSnapshotRace tests. 

---

*[pkg/storage/store.go, line 3105 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/12313#-KYtBpfKSabc-E-V6gox:-KYvYBaGKMY-j-N5cE_k:b-mfuqyx) ([raw file](https://github.com/cockroachdb/cockroach/blob/4ef857dfb7f44337b0c5fb2603997e80b5ac66d1/pkg/storage/store.go#L3105)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

Are there any situations in which `ReplicaTooOldError` could be incorrect? I like that we're cancelling the pending commands earlier, but I'm worried we could cancel pending commands on a replica that is still valid. 
</blockquote></details>

No, `ReplicaTooOldError` should always be reliable. It uses `RangeDescriptor.NextReplicaID` to distinguish old removed replicas from yet-to-be-added ones. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/12313)*

**Comment by tamird** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 5 unresolved discussions, all commit checks successful.

---

*[pkg/storage/replica.go, line 761 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/12313#-KYsqAYD8kPYH4V3WT-9:-KYw_tDcIYP29ZZdUdT5:btij99d) ([raw file](https://github.com/cockroachdb/cockroach/blob/4ef857dfb7f44337b0c5fb2603997e80b5ac66d1/pkg/storage/replica.go#L761)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

That prevents a reproposal from within the Replica; the AmbiguousResultError prevents retries at the DistSender. 

But now that I think about it, if this is doing anything I should be seeing these bubble up to the test's `t.Fatals`. The double-applied commands in #12258 must have gone away for some other reason (I think I stopped seeing them after pulling from master). In fact, addWriteCmd turns any errors after `proposalRangeNoLongerExists` into `AmbiguousResultErrors`, so it doesn't matter what error we return here. 
</blockquote></details>

Cool. Could you amend the commit message?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/12313)*

**Comment by bdarnell** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions, all commit checks successful.

---

*[pkg/storage/replica.go, line 761 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/12313#-KYsqAYD8kPYH4V3WT-9:-KYxQxBD879zBiIvNjqv:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/4ef857dfb7f44337b0c5fb2603997e80b5ac66d1/pkg/storage/replica.go#L761)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

Cool. Could you amend the commit message?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/12313)*

**Comment by petermattis** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions, all commit checks successful.

---

*[pkg/storage/store.go, line 3105 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/12313#-KYtBpfKSabc-E-V6gox:-KYxbes6m9Usx32x6HPM:b-ada4aw) ([raw file](https://github.com/cockroachdb/cockroach/blob/4ef857dfb7f44337b0c5fb2603997e80b5ac66d1/pkg/storage/store.go#L3105)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

No, `ReplicaTooOldError` should always be reliable. It uses `RangeDescriptor.NextReplicaID` to distinguish old removed replicas from yet-to-be-added ones. 
</blockquote></details>

Right, but I'm not seeing what ties the `ReplicaTooOldError` to the current replica. Is it possible the replica which sent the Raft message that generated the `ReplicaTooOldError` has been removed and replaced with a newer replica for the same range? I haven't been able to convince myself one way or another. Perhaps `ReplicaTooOldError` should contain the replica ID of the generating message.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/12313)*

**Comment by bdarnell** [comment]
Review status: 4 of 8 files reviewed at latest revision, 5 unresolved discussions, some commit checks pending.

---

*[pkg/storage/store.go, line 3105 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/12313#-KYtBpfKSabc-E-V6gox:-KZ-QsnQQW6WzJiYQuWw:b-mp42hu) ([raw file](https://github.com/cockroachdb/cockroach/blob/4ef857dfb7f44337b0c5fb2603997e80b5ac66d1/pkg/storage/store.go#L3105)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

Right, but I'm not seeing what ties the `ReplicaTooOldError` to the current replica. Is it possible the replica which sent the Raft message that generated the `ReplicaTooOldError` has been removed and replaced with a newer replica for the same range? I haven't been able to convince myself one way or another. Perhaps `ReplicaTooOldError` should contain the replica ID of the generating message.
</blockquote></details>

Ah, I see. Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/12313)*

**Comment by petermattis** [comment]
:lgtm:

---

Review status: 4 of 8 files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/12313#-:-KZ1zcIqtpONXpzn0PzP:bnfp4nl)*

**Comment by tamird** [comment]
Reviewed 4 of 4 files at r3.
Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/12313)*

File: pkg/storage/store.go [hunk 1]
```diff
@@ -3109,6 +3101,17 @@ func (s *Store) HandleRaftResponse(ctx context.Context, resp *RaftMessageRespons
...
+			// re-added rapidly), we know the replica will be removed and we
+			// can cancel any pending commands. This is sometimes necessary
+			// to unblock PushTxn operations that are necessary for the
+			// replica GC to succeed.
+			if tErr.ReplicaID == repl.mu.replicaID {
+				repl.cancelPendingCommandsLocked()
+			}
+			repl.mu.Unlock()
 			ctx = repl.AnnotateCtx(ctx)
 			added, err := s.replicaGCQueue.Add(
```
Comment (nvanbenschoten) [inline pkg/storage/store.go]: Question about this a year late: why do we still add to the `replicaGCQueue` if `tErr.ReplicaID != repl.mu.replicaID`. Was the idea just that the queue processing would be a no-op? Would it be incorrect to break early if `tErr.ReplicaID != repl.mu.replicaID` like we do for `RangeNotFoundErrors`?

I ask because I'm running into an issue where https://github.com/cockroachdb/cockroach/commit/c07f3b059377bebc37fbcfb89d273c650d74a63e#diff-f053cdaf591941e579feecd64a66ab07R3296 is setting a `destroyReasonRemovalPending` status that isn't being removed. It looks like this status can be set on re-added replicas as well. The issue goes away when I break early, but I'm not sure whether we have a reason to insert re-added replicas to the `replicaGCQueue` as well.

cc. @petermattis

Comment (nvanbenschoten) [reply pkg/storage/store.go]: Follow up: https://github.com/cockroachdb/cockroach/pull/22916.
