### PR TITLE
backupccl: deflake TestCleanupIntentsDuringBackupPerformanceRegression

### LINKED ISSUE #112812: ccl/backupccl: TestCleanupIntentsDuringBackupPerformanceRegression failed
ccl/backupccl.TestCleanupIntentsDuringBackupPerformanceRegression [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Ci_TestsGcpLinuxX8664BigVm_CclUnitTests/12282055?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Ci_TestsGcpLinuxX8664BigVm_CclUnitTests/12282055?buildTab=artifacts#/) on master @ [07915532f9a7def000127029c667c3a91ce90e47](https://github.com/cockroachdb/cockroach/commits/07915532f9a7def000127029c667c3a91ce90e47):

```
=== RUN   TestCleanupIntentsDuringBackupPerformanceRegression
    test_log_scope.go:170: test logs captured to: /artifacts/tmp/_tmp/08eca5aa191e7cb5498d48e4d60049c7/logTestCleanupIntentsDuringBackupPerformanceRegression2898872884
    test_log_scope.go:81: use -show-logs to present logs inline
    backup_intents_test.go:124: -- test log scope end --
--- FAIL: TestCleanupIntentsDuringBackupPerformanceRegression (43.72s)
test logs left over in: /artifacts/tmp/_tmp/08eca5aa191e7cb5498d48e4d60049c7/logTestCleanupIntentsDuringBackupPerformanceRegression2898872884
=== RUN   TestCleanupIntentsDuringBackupPerformanceRegression/abort=true
    backup_intents_test.go:122: 
        	Error Trace:	github.com/cockroachdb/cockroach/pkg/ccl/backupccl_test/pkg/ccl/backupccl/backup_intents_test.go:122
        	            				github.com/cockroachdb/cockroach/pkg/testutils/subtest.go:31
        	Error:      	"1100" is not greater than or equal to "1169"
        	Test:       	TestCleanupIntentsDuringBackupPerformanceRegression/abort=true
    --- FAIL: TestCleanupIntentsDuringBackupPerformanceRegression/abort=true (13.66s)
```
<details><summary>Help</summary>
<p>

See also: [How To Investigate a Go Test Failure \(internal\)](https://cockroachlabs.atlassian.net/l/c/HgfXfJgM)
</p>
</details>
/cc @cockroachdb/disaster-recovery
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*TestCleanupIntentsDuringBackupPerformanceRegression.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)
</sub>

Jira issue: CRDB-32609

### PR DESCRIPTION
**Pull request by miraradeva**
The test was counting batches of pushes for the entire duration of the test, not just the back itself. This patch resets the counters to do a more targeted assertion.

Fixes: #112812

Release note: None

### CODE REVIEW

**Review by miraradeva — COMMENTED** [review]
I actually couldn't repro on a gce worker (stressed for 1,000 runs), and I didn't see anything interesting in the logs of the failed runs. If this doesn't help, I can bump up the expected pushes after confirming it's ok.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/112995#-:-NhY0u6l5qs1NiFzrjyL:b-ds72xd)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @msbutler)

File: pkg/ccl/backupccl/backup_intents_test.go [hunk 1]
```diff
@@ -120,5 +119,12 @@ func TestCleanupIntentsDuringBackupPerformanceRegression(t *testing.T) {
 		// Each of the 1,000 transactions is expected to get pushed once, but in an
 		// actual run of the test we might see more pushes (e.g. of other transactions).
 		require.GreaterOrEqual(t, 1100, int(numPushBatches.Load()))
+
+		if !abort {
```
Comment (msbutler) [inline pkg/ccl/backupccl/backup_intents_test.go:123]: for my own clarity, we needed to move this in case it bumped numIntentResolveBatches or numPushBatches?

**Review by msbutler — APPROVED** [review]

File: pkg/ccl/backupccl/backup_intents_test.go (hunk 1 above)
Comment (miraradeva) [reply pkg/ccl/backupccl/backup_intents_test.go:123]: Yes, potentially, though not expected in the general case. I just tried to tighten the counting to include only the actual backup as much as possible.

**Comment by miraradeva** [comment]
bors r=msbutler
