### PR TITLE
sql: hoist FunctionProperties to the built-in function name, instead of individual overloads

### LINKED ISSUE #26354: sql: current_date incorrectly not marked impure
The built-in function def for `current_date` does not set the `Impure` property. This seems to be a bug.

Might need a cherry-pick

### PR DESCRIPTION
**Pull request by knz**
tldr: this patchset hoists the properties of built-in functions next to the name, instead of the level of individual overload implementation as previously.

This is a precursor to the fix to  #20511.

Fixes #26354.

cc @andy-kimball

### CODE REVIEW

**Comment by jordanlewis** [comment]
Generally :lgtm: although I didn't carefully review the whole patch on account of this mainly being a refactor.

---

Review status: 2 of 31 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---

*[docs/generated/sql/functions.md, line 1 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/26370#-LEBX6vtBiTeR9DF6WjI:-LEBX6vtBiTeR9DF6WjJ:b-rz9zoi) ([raw file](https://github.com/cockroachdb/cockroach/blob/70fbdd47353245c3f1cf98ec0aac9b95c03165f7/docs/generated/sql/functions.md#L1)):*
> ```Markdown
> ### ANYELEMENT Functions
> ```

This seems to have been wholesale deleted. was that intended?

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/26370#-:-LEBXzAv24jysbAGjIa2:b-y021bv)*

**Comment by jordanlewis** [comment]
One naming nit is that  you could just call it Overload or OverloadDef instead of OverloadDefinition since we  have to type that out a lot.

---

Review status: 2 of 31 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/26370#-:-LEBYGhW8S3aCnle-z7o:bkxsx5s)*

File: pkg/sql/opt/memo/private_defs.go [hunk 1]
```diff
@@ -31,9 +31,10 @@ type PrivateID uint32
 // operator. It provides the name and return type of the function, as well as a
 // pointer to an already resolved builtin overload definition.
 type FuncOpDef struct {
-	Name     string
-	Type     types.T
-	Overload *tree.Builtin
+	Name       string
+	Type       types.T
+	Properties *tree.FunctionProperties
```
Comment (andy-kimball) [inline pkg/sql/opt/memo/private_defs.go]: This feels clunky to me. I should be able to have a single pointer that holds onto a function definition, including its properties and its overloads. Why can't we have a `BuiltinDef` struct, like this:
```
type BuiltinDef struct {
  Props BuiltinProps
  Overloads []BuiltinOverload
}
```
This way, I can easily get a pointer to whatever I need - props, all overloads, any one overload, or the entire definition.

File: pkg/sql/sem/builtins/builtins.go [hunk 2]
```diff
@@ -94,53 +96,83 @@ func categorizeType(t types.T) string {
...
+) BuiltinDefinition {
+	return BuiltinDefinition{
+		FunctionProperties: props,
+		Overloads:          overloads,
+	}
+}
+
 // Builtins contains the built-in functions indexed by name.
-var Builtins = map[string][]tree.Builtin{
+var Builtins = map[string]BuiltinDefinition{
```
Comment (andy-kimball) [inline pkg/sql/sem/builtins/builtins.go]: Can you make this a `*BuiltinDefinition` instead? Otherwise it forces the code that accesses the map to make a copy of the struct, since you can't get a pointer to a map value.

**Comment by knz** [comment]
Review status: 2 of 31 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[docs/generated/sql/functions.md, line 1 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/26370#-LEBX6vtBiTeR9DF6WjI:-LEDtp328mKKZMOKAT2P:bfnzw7i) ([raw file](https://github.com/cockroachdb/cockroach/blob/70fbdd47353245c3f1cf98ec0aac9b95c03165f7/docs/generated/sql/functions.md#L1)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

This seems to have been wholesale deleted. was that intended?
</blockquote></details>

The functions have be re-categorized in "JSON" where they belong.

---

*[pkg/sql/opt/memo/private_defs.go, line 36 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/26370#-LEBAJMmYTpdgwUNmJwf-r6-36:-LEDtwfO5POFtoqVIg7-:bvhnzy) ([raw file](https://github.com/cockroachdb/cockroach/blob/06c32bc0982dcc68f79cfa083cc24169668a9f79/pkg/sql/opt/memo/private_defs.go#L36)):*
<details><summary><i>Previously, andy-kimball (Andy Kimball) wrote…</i></summary><blockquote>

This feels clunky to me. I should be able to have a single pointer that holds onto a function definition, including its properties and its overloads. Why can't we have a `BuiltinDef` struct, like this:
```
type BuiltinDef struct {
  Props BuiltinProps
  Overloads []BuiltinOverload
}
```
This way, I can easily get a pointer to whatever I need - props, all overloads, any one overload, or the entire definition.
</blockquote></details>

AFAIK `FuncOpDef` needs a particular overload, not the full set.
If this structhad pointed to a `*tree.FunctionDefinition` (which exists already, and does what you say you want), I'd not have needed change this.

If you want everything, change the code to use `tree.FunctionDefinition` as needed.

---

*[pkg/sql/sem/builtins/builtins.go, line 129 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/26370#-LEBAJMmYTpdgwUNmJwV-r6-129:-LEDuF3l1JLAtfNhbjMR:b-5b9sjm) ([raw file](https://github.com/cockroachdb/cockroach/blob/06c32bc0982dcc68f79cfa083cc24169668a9f79/pkg/sql/sem/builtins/builtins.go#L129)):*
<details><summary><i>Previously, andy-kimball (Andy Kimball) wrote…</i></summary><blockquote>

Can you make this a `*BuiltinDefinition` instead? Otherwise it forces the code that accesses the map to make a copy of the struct, since you can't get a pointer to a map value.
</blockquote></details>

`BuiltinDefinition` is not meant for public consumption (it's only exported to generate help strings from a different package). Use `FunctionDefinition` instead.

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/26370)*

**Comment by knz** [comment]
Renamed `OverloadDefinition` to `Overload` as requested.

**Comment by andy-kimball** [comment]
*[pkg/sql/opt/memo/private_defs.go, line 36 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/26370#-LEBAJMmYTpdgwUNmJwf-r6-36:-LEFNY4n89bseMAx_jft:b-tk1b2y) ([raw file](https://github.com/cockroachdb/cockroach/blob/06c32bc0982dcc68f79cfa083cc24169668a9f79/pkg/sql/opt/memo/private_defs.go#L36)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

AFAIK `FuncOpDef` needs a particular overload, not the full set.
If this structhad pointed to a `*tree.FunctionDefinition` (which exists already, and does what you say you want), I'd not have needed change this.

If you want everything, change the code to use `tree.FunctionDefinition` as needed.
</blockquote></details>

Yes, you're correct, we do need the overload. Perhaps I'll store the `FunctionDefinition` + int index of overload. Then I can also get rid of the `Name` field, since that's already stored in the definition as well.

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/26370)*

**Comment by knz** [comment]
Review status: 0 of 39 files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[pkg/sql/sem/builtins/builtins.go, line 129 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/26370#-LEBAJMmYTpdgwUNmJwV-r6-129:-LEFR6Xx2AK9g406qi7v:bsyw1a7) ([raw file](https://github.com/cockroachdb/cockroach/blob/06c32bc0982dcc68f79cfa083cc24169668a9f79/pkg/sql/sem/builtins/builtins.go#L129)):*
<details><summary><i>Previously, andy-kimball (Andy Kimball) wrote…</i></summary><blockquote>

OK, looks like you found a way to not export it, which clarifies its intended use. How come you can't just  use `FunctionDefinition` directly here? Looking at the latest code, it appears that we're storing almost the same thing, first as `builtinDefinition` and then as `FunctionDefinition`, and copying one to the other.
</blockquote></details>

No need to add the `Name` field in each entry of the `builtins` map since the map key already has it.

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/26370)*
