### PR TITLE
kvclient: fix verbose logging crash

### LINKED ISSUE #50918: testutils/emptypkg: TestDockerCLI failed
[(testutils/emptypkg).TestDockerCLI failed](https://teamcity.cockroachdb.com/viewLog.html?buildId=2058043&tab=buildLog) on [master@17c649468273e3c80953681e90fc997f0d75d2dd](https://github.com/cockroachdb/cockroach/commits/17c649468273e3c80953681e90fc997f0d75d2dd):

```
=== RUN   TestDockerCLI
    TestDockerCLI: test_log_scope.go:77: test logs captured to: /home/agent/work/.go/src/github.com/cockroachdb/cockroach/artifacts/acceptance/logTestDockerCLI312336098
    TestDockerCLI: test_log_scope.go:58: use -show-logs to present logs inline
--- FAIL: TestDockerCLI (378.45s)
=== RUN   TestDockerCLI/test_high_verbosity.tcl
    --- FAIL: TestDockerCLI/test_high_verbosity.tcl (33.15s)

```

<details><summary>More</summary><p>
Parameters:

- GOFLAGS=-json

```
make stressrace TESTS=TestDockerCLI PKG=./pkg/testutils/emptypkg TESTTIMEOUT=5m STRESSFLAGS='-timeout 5m' 2>&1
```

[See this test on roachdash](https://roachdash.crdb.dev/?filter=status%3Aopen+t%3A.%2ATestDockerCLI.%2A&sort=title&restgroup=false&display=lastcommented+project)
<sub>powered by [pkg/cmd/internal/issues](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)</sub></p></details>

### LINKED ISSUE #50935: runtime error: invalid memory address or nil pointer dereference
Running into the following in https://github.com/cockroachdb/cockroach/pull/50852 CI.

```
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x52484a6]

goroutine 342 [running]:
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).Recover(0xc0000ee120, 0x8bde440, 0xc000894ab0)
	/Users/irfansharif/Software/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:183 +0x11f
panic(0x7c6ce80, 0xb0c3220)
	/usr/local/Cellar/go/1.14.4/libexec/src/runtime/panic.go:969 +0x166
github.com/cockroachdb/cockroach/pkg/kv/kvclient/kvcoord.EvictionToken.Desc(...)
	/Users/irfansharif/Software/src/github.com/cockroachdb/cockroach/pkg/kv/kvclient/kvcoord/range_cache.go:243
github.com/cockroachdb/cockroach/pkg/kv/kvclient/kvcoord.(*RangeIterator).Seek(0xc001638bc0, 0x8bde440, 0xc000894ba0, 0xc000d9e420, 0x27, 0x27, 0x203000)
	/Users/irfansharif/Software/src/github.com/cockroachdb/cockroach/pkg/kv/kvclient/kvcoord/range_iter.go:178 +0x516
github.com/cockroachdb/cockroach/pkg/kv/kvclient/kvcoord.(*DistSender).divideAndSendBatchToRanges(0xc0002d9340, 0x8bde440, 0xc000894ba0, 0x161e02291a4b81c8, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/Users/irfansharif/Software/src/github.com/cockroachdb/cockroach/pkg/kv/kvclient/kvcoord/dist_sender.go:1091 +0x1fa
github.com/cockroachdb/cockroach/pkg/kv/kvclient/kvcoord.(*DistSender).Send(0xc0002d9340, 0x8bde440, 0xc000894ba0, 0x161e02291a4b81c8, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/Users/irfansharif/Software/src/github.com/cockroachdb/cockroach/pkg/kv/kvclient/kvcoord/dist_sender.go:738 +0x8e4
github.com/cockroachdb/cockroach/pkg/kv.lookupRangeFwdScan(0x8bde440, 0xc000894ba0, 0x8b52980, 0xc0002d9340, 0xc000d9e2d0, 0x26, 0x26, 0x1, 0x8, 0x1dcd6500, ...)
	/Users/irfansharif/Software/src/github.com/cockroachdb/cockroach/pkg/kv/range_lookup.go:312 +0x404
github.com/cockroachdb/cockroach/pkg/kv.RangeLookup(0x8bde440, 0xc000894ba0, 0x8b52980, 0xc0002d9340, 0xc000d9e2d0, 0x26, 0x26, 0x1, 0x8, 0x4504d00, ...)
	/Users/irfansharif/Software/src/github.com/cockroachdb/cockroach/pkg/kv/range_lookup.go:197 +0x8a5
github.com/cockroachdb/cockroach/pkg/kv/kvclient/kvcoord.(*DistSender).RangeLookup(0xc0002d9340, 0x8bde440, 0xc000894ba0, 0xc000d9e2d0, 0x26, 0x26, 0x8bde400, 0xc000894ba0, 0x7d29b40, 0x5a508a2699601, ...)
	/Users/irfansharif/Software/src/github.com/cockroachdb/cockroach/pkg/kv/kvclient/kvcoord/dist_sender.go:415 +0xd4
github.com/cockroachdb/cockroach/pkg/kv/kvclient/kvcoord.(*RangeDescriptorCache).performRangeLookup(0xc000c28de0, 0x8bde440, 0xc000894ba0, 0xc000d9e2d0, 0x26, 0x26, 0x8397900, 0xc000458b30, 0x41f642b, 0x8bde440, ...)
	/Users/irfansharif/Software/src/github.com/cockroachdb/cockroach/pkg/kv/kvclient/kvcoord/range_cache.go:707 +0x293
github.com/cockroachdb/cockroach/pkg/kv/kvclient/kvcoord.(*RangeDescriptorCache).tryLookup.func1.1.1(0x8bde400, 0xc000e32540, 0x2540be400, 0x8bde400)
	/Users/irfansharif/Software/src/github.com/cockroachdb/cockroach/pkg/kv/kvclient/kvcoord/range_cache.go:561 +0x8e
github.com/cockroachdb/cockroach/pkg/util/contextutil.RunWithTimeout(0x8bde400, 0xc000e32540, 0x81f6bb9, 0xc, 0x2540be400, 0xc000458cd0, 0x0, 0x0)
	/Users/irfansharif/Software/src/github.com/cockroachdb/cockroach/pkg/util/contextutil/context.go:135 +0x9e
github.com/cockroachdb/cockroach/pkg/kv/kvclient/kvcoord.(*RangeDescriptorCache).tryLookup.func1.1(0x8bde440, 0xc000894ab0, 0x0, 0x0)
	/Users/irfansharif/Software/src/github.com/cockroachdb/cockroach/pkg/kv/kvclient/kvcoord/range_cache.go:558 +0x2f7
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunTaskWithErr(0xc0000ee120, 0x8bde440, 0xc000894ab0, 0x821fd22, 0x18, 0xc0009e9f00, 0x0, 0x0)
	/Users/irfansharif/Software/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:302 +0xf1
github.com/cockroachdb/cockroach/pkg/kv/kvclient/kvcoord.(*RangeDescriptorCache).tryLookup.func1(0x8bde440, 0xc00089a0c0, 0xb186660, 0x0)
	/Users/irfansharif/Software/src/github.com/cockroachdb/cockroach/pkg/kv/kvclient/kvcoord/range_cache.go:546 +0xed
github.com/cockroachdb/cockroach/pkg/util/syncutil/singleflight.(*Group).doCall(0xc000c28e20, 0xc00152c280, 0xc000d9e390, 0x2d, 0xc0008542c0)
	/Users/irfansharif/Software/src/github.com/cockroachdb/cockroach/pkg/util/syncutil/singleflight/singleflight.go:128 +0x2e
created by github.com/cockroachdb/cockroach/pkg/util/syncutil/singleflight.(*Group).DoChan
	/Users/irfansharif/Software/src/github.com/cockroachdb/cockroach/pkg/util/syncutil/singleflight/singleflight.go:121 +0x2bc
```

I was running the following test to check:

```
killall -9 cockroach cockroachshort; rm -rf logs; expect -d -f pkg/cli/interactive_tests/test_high_verbosity.tcl ./cockroachshort
```

### PR DESCRIPTION
**Pull request by andreimatei**
This logging statement SIGSEGVs in the error case.

Fixes #50918
Fixes #50935

Release note: None

### CODE REVIEW

File: pkg/kv/kvclient/kvcoord/range_iter.go [hunk 1]
```diff
@@ -188,6 +184,10 @@ func (ri *RangeIterator) Seek(ctx context.Context, key roachpb.RKey, scanDir Sca
 			continue
 		}
 
+		if log.V(2) {
+			log.Infof(ctx, "key: %s, desc: %s err: %v", ri.key, rngInfo.Desc(), err)
```
Comment (irfansharif) [inline pkg/kv/kvclient/kvcoord/range_iter.go:188]: Could drop `err` entirely, it's always going to be nil.

**Review by irfansharif — APPROVED** [review]
LGTM, thanks!

**Review by andreimatei — COMMENTED** [review]
bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/50940#-:-MBGtukL3_U1yzi_XNzU:b-ydi9ay)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @irfansharif)

___
*[pkg/kv/kvclient/kvcoord/range_iter.go, line 188 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/50940#-MBG9MCCtIfpgduOhjDF-r1-188:-MBGtkiF86HAQlvKQZAd:bb7f2mf) ([raw file](https://github.com/cockroachdb/cockroach/blob/d13328072b6b6c1d94f9f3074d2fae0d969a4d86/pkg/kv/kvclient/kvcoord/range_iter.go#L188)):*
<details><summary><i>Previously, irfansharif (irfan sharif) wrote…</i></summary><blockquote>

Could drop `err` entirely, it's always going to be nil.
</blockquote></details>

done
