### PR TITLE
pkg/util/log: Implement handling for oversized log messages in bufferedSink

### LINKED ISSUE #152635: log: gracefully handle "message dropped because it is too large"
**Describe the problem**

An incident occurred due to multiple node's exiting with a exit code 6: `LoggingFileUnavailable`. Grepping the logs showed that this error was causing this exit: 
```
122363 1@util/log/event_log.go:43 ⋮ [-]   logging error: message dropped because it is too large
```
Which is en error returned [here](https://github.com/cockroachdb/cockroach/blob/9988da7ad7033edd0e20abdfbae54909688a503f/pkg/util/log/buffered_sink.go#L418). As a result of this function returning an error, the error is returned from the sink's `output` function which ultimately resulted in [this line of code ](https://github.com/cockroachdb/cockroach/blob/48ac1152f03cc2f27080d4bc361035abc016133c/pkg/util/log/clog.go#L415) being executed because `exit-on-error` was set to true in the log config. 

**To Reproduce**
Using a log config along the following:
```
sinks:
  file-groups:
    default:
      channels: [ALL]
      dir: logs
      format: crdb-v2-tty
      exit-on-error: true
      buffered-writes: false
      buffering:
        max-staleness: 1s
        flush-trigger-size: 256KiB
        max-buffer-size: 2MiB

  stderr:
    channels: [OPS] 
    format: crdb-v2-tty
```

* Start a local cluster
* run a query that is more than 2MiB. 
  * This can just be something like: `SELECT <X>;` where `<X>` is some long string that makes the query over 2 Mib.

WIth the above config, the server will crash. If you  set exit-on-error:false, it will no longer crash

**Expected behavior**
This shouldn't cause the node to crash. We should gracefully handle situations where the log is too big.

Some potential solutions may be: 
* In the buffered sink append function, don't return an error if the the message is to big, instead we may want to log the error and return
* The append function can return some type of "non critical error" that clog.outputLogEntry checks for and only exists for critical errors

**Additional context**
* It seems likely that the customer had the cluster setting: `sql.log.all_statements.enabled` set to true, which results in all executed queries to be logged (`QueryExecuted` events). This includes both queries executed from clients as well as internal query executions. 

* we aren't able to actually see which log actually causes this error. If possible, we should see if we can log part of to help debug what logs are causing this in the future.

* the customer had the max buffer size set to `50MiB` (i believe this is the default for all cloud clusters). This means that the entry being logged had to be bigger than this, which is pretty crazy. Besides `QueryExecuted` structured events, I'm not sure how a log could be this big.

Jira issue: CRDB-53951

Epic CRDB-56325

### PR DESCRIPTION
**Pull request by Abhinav1299**
Previously, when a single log message exceeded the configured max-buffer-size
for a buffered sink with exit-on-error enabled, the error would propagate up
and trigger process termination. This was overly aggressive for what amounts
to a logging configuration issue - a single oversized SQL query (e.g., with a
multi-megabyte string literal) could crash an entire CockroachDB node.

This commit modifies bufferedSink.output() to detect the errMsgTooLarge error
and handle it gracefully. When an oversized message is encountered, instead of
propagating the error, we drop the message and log a warning via Ops.Warningf()
indicating that the message exceeded the buffer size limit. This allows the
node to continue operating normally while still providing visibility into the
issue through logged warnings.

The implementation uses a two-phase approach to avoid deadlock: first, while
holding the sink's mutex, we detect the oversized message and set a flag with
the relevant information; then, after releasing the lock, we emit the warning.
This is necessary because calling Ops.Warningf() while holding the mutex would
cause the warning message to attempt re-entry into the same sink, resulting in
a deadlock when it tries to acquire the already-held lock.

This resolves https://github.com/cockroachdb/cockroach/issues/152635

Part of: CRDB-53951
Epic: CRDB-56325
Release note: None

### CODE REVIEW

File: pkg/util/log/buffered_sink_test.go [hunk 1]
```diff
@@ -630,3 +630,46 @@ func (t *testWaitGroupSink) exitCode() exit.Code {
...
+		}).
+		MaxTimes(1) // The warning may or may not be logged through this same sink
+
+	// Attempt to output the oversized message. This should succeed (return nil)
+	// and not cause the process to crash.
+	err := sink.output(oversizedMessage, sinkOutputOptions{})
+	require.NoError(t, err, "oversized message should be handled gracefully without returning an error")
+
+	// Give a moment for any async warning to be logged.
+	time.Sleep(100 * time.Millisecond)
```
Comment (kyle-a-wong) [inline pkg/util/log/buffered_sink_test.go]: Is this intended to give time for the `mock.DO()` function to be called? Instead, can we put a boolean flag into that closure and wait for it to be true?:
```
var receivedError error
...
mock.
   ...
   DO(func() { ... receivedError = true... }
..
testutils.SucceedsSoon(t, func() error {
  if !receivedError {
    return errors.New("Waiting for dropped oversized error log")
  }

  return nil
})
```

I think this is less likely to  cause a flake, compared to using time.Sleep

**Review by aa-joshi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/157964)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @Abhinav1299, @arjunmahishi, and @dhartunian)

___
*[`-- commits` line 4 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/157964#-OePk1Zx6-l1qMhL_tIw:-OePk1Zx6-l1qMhL_tIx:bcucnbd):*
Lets add details in depth about the issue and the resolution.
___
*[`pkg/util/log/buffered_sink.go` line 246 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/157964#-OePnqIvC29OB_24dqSA:-OePnqIvC29OB_24dqSB:b2hwc1o) ([raw file](https://github.com/cockroachdb/cockroach/blob/75f2048e50d5d3eb2fd79ca4e4a85422b109f139/pkg/util/log/buffered_sink.go#L246)):*
> ```Go
> 				// Set flag to log warning after releasing the lock (to avoid recursion/deadlock)
> 				logOversizedWarning = true
> 				maxSize = bs.mu.buf.maxSizeBytes
> ```

Is there any specific reason that we are capturing value as part of maxSize? Wouldn't this value available during logging time?
___
*[`pkg/util/log/buffered_sink.go` line 303 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/157964#-OePl4BzBWLTiNlFl2CX:-OePl4BzBWLTiNlFl2CY:b-wx6vdp) ([raw file](https://github.com/cockroachdb/cockroach/blob/75f2048e50d5d3eb2fd79ca4e4a85422b109f139/pkg/util/log/buffered_sink.go#L303)):*
> ```Go
> 
> 	// Log the oversized message warning after releasing the lock to avoid deadlock.
> 	// This warning will be logged through the normal logging system and will appear
> ```

What do you mean by normal logging system?

File: pkg/util/log/buffered_sink_test.go (hunk 1 above)
Comment (Abhinav1299) [reply pkg/util/log/buffered_sink_test.go]: Updated the test

**Review by Abhinav1299 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/157964)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @aa-joshi, @arjunmahishi, @dhartunian, and @kyle-a-wong)

___
*[`-- commits` line 4 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/157964#-OePk1Zx6-l1qMhL_tIw:-OeVM2-21BVEwmE5KNCl:bvnrpcm):*
<details><summary><i>Previously, aa-joshi (Akshay Joshi) wrote…</i></summary><blockquote>

Lets add details in depth about the issue and the resolution.
</blockquote></details>

updated
___
*[`pkg/util/log/buffered_sink.go` line 246 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/157964#-OePnqIvC29OB_24dqSA:-OeVM52N046viV9wicHQ:bcrf9rg) ([raw file](https://github.com/cockroachdb/cockroach/blob/75f2048e50d5d3eb2fd79ca4e4a85422b109f139/pkg/util/log/buffered_sink.go#L246)):*
<details><summary><i>Previously, aa-joshi (Akshay Joshi) wrote…</i></summary><blockquote>

Is there any specific reason that we are capturing value as part of maxSize? Wouldn't this value available during logging time?
</blockquote></details>

We can't access `bs.mu.buf.maxSizeBytes` at logging time in Ops.Warningf() because we're outside the lock, and accessing mutex-protected data without the lock will lead to a race condition. Thats the reason we capture the buffer size in `maxSize` while we still safely hold the lock.
___
*[`pkg/util/log/buffered_sink.go` line 303 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/157964#-OePl4BzBWLTiNlFl2CX:-OeVeijeEFck-jIZVRSM:b7ga238) ([raw file](https://github.com/cockroachdb/cockroach/blob/75f2048e50d5d3eb2fd79ca4e4a85422b109f139/pkg/util/log/buffered_sink.go#L303)):*
<details><summary><i>Previously, aa-joshi (Akshay Joshi) wrote…</i></summary><blockquote>

What do you mean by normal logging system?
</blockquote></details>

By normal logging I mean this log will route through OPS channel and will appear in log files file.
I'll update the wordings here.

**Review by kyle-a-wong — APPROVED** [review]
LGTM.

IMO we  should backport this to all versions, using `backport-all` label.

**Review by aa-joshi — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/157964#-:-Oeog0mP26VjA5R66W68:bnfp4nl)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @arjunmahishi, @dhartunian, and @kyle-a-wong)

**Comment by Abhinav1299** [comment]
TFTR!
bors r+
