### PR TITLE
sql: add context to planner used by schema change backfill

### LINKED ISSUE #13675: sql: backfill.go crashes when verbosity=2
The backfill code sets up a dummy planner that does not have a context. This causes crashes in `getTableLeaseByID`, `releaseLeases`.

```go
330 func (p *planner) getTableLeaseByID(tableID sqlbase.ID) (*sqlbase.TableDescriptor, error) {
331   if log.V(2) {
332     log.Infof(p.ctx(), "planner acquiring lease on table ID %d", tableID)
333   }
```

### PR DESCRIPTION
**Pull request by vivekmenezes**
fixes #13675

---
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/13899)

### CODE REVIEW

File: pkg/sql/backfill.go [hunk 1]
```diff
@@ -383,6 +383,9 @@ func (sc *SchemaChanger) truncateAndBackfillColumnsChunk(
 		p := &planner{
```
Comment (knz) [inline pkg/sql/backfill.go]: I would recommend creating a new function `makePlannerForBackfill()` which would be reused in these three locations, so that we only have one to change should the initialization parameters need updating again.

**Comment by vivekmenezes** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[pkg/sql/backfill.go, line 383 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/13899#-KeVSTHrJ15muE00cfiO-r1-383:-KeYyhQFr01W3n01q93_:b-nrxcgm) ([raw file](https://github.com/cockroachdb/cockroach/blob/753927435c7e1f9313b4383cf99c466792edf5e7/pkg/sql/backfill.go#L383)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

I would recommend creating a new function `makePlannerForBackfill()` which would be reused in these three locations, so that we only have one to change should the initialization parameters need updating again.
</blockquote></details>

Done. TYFR

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/13899)*

**Comment by tamird** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/13899)*

**Comment by knz** [comment]
:lgtm:

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/13899#-:-Ke_hMmnLOnZUaBmGVrh:bnfp4nl)*
