### PR TITLE
kvcoord: deflake TestEvictionTokenCoalesce

### LINKED ISSUE #92190: kv/kvclient/kvcoord: TestEvictionTokenCoalesce failed
kv/kvclient/kvcoord.TestEvictionTokenCoalesce [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_StressBazel/7596404?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_StressBazel/7596404?buildTab=artifacts#/) on master @ [8357abb668a5adaff781343b394b162fb1b66c6e](https://github.com/cockroachdb/cockroach/commits/8357abb668a5adaff781343b394b162fb1b66c6e):

```
=== RUN   TestEvictionTokenCoalesce
    test_log_scope.go:161: test logs captured to: /artifacts/tmp/_tmp/40ec041d13327ceafaefe721fe51f834/logTestEvictionTokenCoalesce3398992622
    test_log_scope.go:79: use -show-logs to present logs inline
    dist_sender_test.go:4375: put encountered error: operation "range lookup" timed out after 45.119s (given timeout 10s): expected 2 in-flight requests, got 1
    dist_sender_test.go:4382: -- test log scope end --
test logs left over in: /artifacts/tmp/_tmp/40ec041d13327ceafaefe721fe51f834/logTestEvictionTokenCoalesce3398992622
--- FAIL: TestEvictionTokenCoalesce (45.20s)
```
<p>Parameters: <code>TAGS=bazel,gss</code>
</p>
<details><summary>Help</summary>
<p>

See also: [How To Investigate a Go Test Failure \(internal\)](https://cockroachlabs.atlassian.net/l/c/HgfXfJgM)
</p>
</details>
/cc @cockroachdb/kv
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*TestEvictionTokenCoalesce.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)
</sub>

Jira issue: CRDB-21629

### PR DESCRIPTION
**Pull request by ajwerner**
Since https://github.com/cockroachdb/cockroach/pull/91638 there's now a case timing can lead to one request evicting a token from underneath the other and then having the two requests not end up hitting the condition we're waiting for. To deflake the test, this change ensure that the two requests synchronize on when they do their initial meta2 scan and synchronize on the initial errors which ensures that when they go back around, they both have the right eviction token.

Fixes #92190

Release note: None

### CODE REVIEW

File: pkg/kv/kvclient/kvcoord/dist_sender_test.go [hunk 1]
```diff
@@ -4286,9 +4287,37 @@ func TestEvictionTokenCoalesce(t *testing.T) {
...
 	}
 
-	sendErrors := int32(0)
-	var queriedMetaKeys sync.Map
+	// makeJoinFunc will make a function which will return once N goroutines
+	// have called it simultaneously. The first time these goroutines call
+	// this function, it will return false. After it has returned false,
+	// subsequent calls will return true.
+	const N = 2
+	makeJoinFunc := func() func() (previouslyJoined bool) {
```
Comment (nvanbenschoten) [inline pkg/kv/kvclient/kvcoord/dist_sender_test.go:4295]: Consider the following simplification using a `WaitGroup`, which avoids the mutex and condition variable pair.

```go
makeBarrier := func(n int) func() (previouslyJoined bool) {
    var wg sync.WaitGroup
    var done atomic.Bool
    wg.Add(n)
    return func() bool {
        if done.Load() {
            return true
        }
        wg.Done()
        wg.Wait()
        done.Store(true)
        return false
    }
}
```

**Review by nvb — APPROVED** [review]
Thanks for the fix!
