### PR TITLE
cli: ensure SQL commands work when `defaultdb` does not exist

### LINKED ISSUE #40967: cli: `cockroach user` and other SQL CLI commands erroneously requires defaultdb to exist
**Describe the problem**
"cockroach user set ...."  requires the  defaultdb database, but the documentation says 
"The postgres and defaultdb databases can be deleted if they are not needed."

**Please describe the issue you observed, and any steps we can take to reproduce it:**
cockroach sql --insecure --execute="create database mydatabase;"
cockroach init --insecure --host=127.0.0.1
cockroach sql --insecure --execute="drop database IF EXISTS defaultdb;"
cockroach sql --insecure --execute="drop database IF EXISTS postgres;"
cockroach user set username --insecure

Error: pq: database "defaultdb" does not exist
Failed running "user set"

**Expected behavior**
user set should not need defaultdb or the documentation should be updated  that defaultdb can not be deleted for insecure(?) cluster

**Additional data / screenshots**
**Environment:**
Build Tag:    v19.1.3
Build Time:   2019/07/08 18:24:39
Distribution: CCL
Platform:     linux amd64 (x86_64-unknown-linux-gnu)
Go Version:   go1.11.6
C Compiler:   gcc 6.3.0
Build SHA-1:  1a14d34eaa22ca5765f338ab4235766f5e293be0
Build Type:   release

### PR DESCRIPTION
**Pull request by knz**
Fixes #40967.

All the various CLI commands that establish a SQL connection require
the target database to exist. If no database is specified via
`--database` or `--url`, the server automatically defaults to
`defaultdb`.

Prior to this patch, the CLI commands that do not strictly require a
user database to function properly would fail if `defaultdb` did not
exist (e.g. because a user chooses to drop it).

This patch changes them to adopt the `system` database instead.

The two commands that are operate on a user database, namely
`cockroach sql` and `cockroach dump`, continue to work as prior.

Release justification: fixes a bug

Release note (bug fix): `cockroach zip`, `cockroach node` and
`cockroach user` now work properly if the `defaultdb` database has
been manually dropped  and the connection URL does not specify a
database. (Note that `cockroach user` is deprecated in 19.2).

### CODE REVIEW

**Comment by knz** [comment]
@mjibson @bdarnell could you perhaps review this? I am pinging you via the comment system because somehow today I am unable to use the "review request" field in the github interface.

**Comment by knz** [comment]
Also I think this should be backported to 19.1, let me know if you agree.

File: pkg/cli/sql_util.go [hunk 1]
```diff
@@ -480,27 +480,53 @@ func makeSQLConn(url string) *sqlConn {
...
 // Attempting to use security.RootUser without valid certificates will return an error.
 func getPasswordAndMakeSQLClient(appName string) (*sqlConn, error) {
-	return makeSQLClient(appName)
+	return makeSQLClient(appName, false /*forceSystemDB*/)
 }
 
 var sqlConnTimeout = envutil.EnvOrDefaultString("COCKROACH_CONNECT_TIMEOUT", "5")
 
-// makeSQLClient connects to the database using the connection
+// makeSystemSQLClient connects to the database using the connection
```
Comment (mjibson) [inline pkg/cli/sql_util.go]: This function is still called makeSQLClient

File: pkg/cli/sql_util.go [hunk 2]
```diff
@@ -480,27 +480,53 @@ func makeSQLConn(url string) *sqlConn {
...
 //
+// If forceSystemDB is set, it also connects it to the `system`
+// database. The --database flag or database part in the URL is then
+// ignored.
+//
 // The appName given as argument is added to the URL even if --url is
 // specified, but only if the URL didn't already specify
 // application_name. It is prefixed with '$ ' to mark it as internal.
-func makeSQLClient(appName string) (*sqlConn, error) {
+func makeSQLClient(appName string, forceSystemDB bool) (*sqlConn, error) {
```
Comment (mjibson) [inline pkg/cli/sql_util.go]: Optional suggestion: instead of using the frowned upon pattern of a boolean argument, may I suggest either a typed bool with consts, or otherwise just a string that passes the forced DB, which would allow for `getPasswordAndMakeSystemSQLClient` to specify the expected database itself? That may make this function clearer.

**Review by madelynnblue — APPROVED** [review]

**Review by bdarnell — APPROVED** [review]
> Reviewed 5 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/41121)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @knz)

___
*[pkg/cli/sql_util.go, line 500 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/41121#-Lpi_DsmAkeY9kjM_Uou:-Lpi_DsmAkeY9kjM_Uov:b-2p3hv3) ([raw file](https://github.com/cockroachdb/cockroach/blob/86b0f05d731d604678e24f04c3124724fc9f71dc/pkg/cli/sql_util.go#L500)):*
> ```Go
> var sqlConnTimeout = envutil.EnvOrDefaultString("COCKROACH_CONNECT_TIMEOUT", "5")
> 
> // makeSystemSQLClient connects to the database using the connection
> ```

Undo the change on this line. 
___
*[pkg/cli/sql_util.go, line 524 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/41121#-Lpi_P9D9wqO_1fhPo1k:-Lpi_P9D9wqO_1fhPo1l:b-w0zt0u) ([raw file](https://github.com/cockroachdb/cockroach/blob/86b0f05d731d604678e24f04c3124724fc9f71dc/pkg/cli/sql_util.go#L524)):*
> ```Go
> 		if baseURL.Path != "system" {
> 			if baseURL.Path != "" {
> 				fmt.Fprintf(stderr, "warning: target SQL database ignored: %q\n", baseURL.Path)
> ```

I don't think we want to be too chatty about this - we want users to be able to set COCKROACH_URL without being annoyed by these messages. I think we can either ignore the given path silently, or use it (if they set their COCKROACH_URL to a non-existent database, it's reasonable for these commands to fail).

**Review by knz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/41121)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @bdarnell and @mjibson)

___
*[pkg/cli/sql_util.go, line 500 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/41121#-LphVSrBOhW_E0NqIUkV-r1-500:-Lpih5hg3HaWocj67C_2:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/86b0f05d731d604678e24f04c3124724fc9f71dc/pkg/cli/sql_util.go#L500)):*
<details><summary><i>Previously, mjibson (Matt Jibson) wrote…</i></summary><blockquote>

This function is still called makeSQLClient
</blockquote></details>

Done.
___
*[pkg/cli/sql_util.go, line 500 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/41121#-Lpi_DsmAkeY9kjM_Uou:-Lpih5za1tJFm__2JlIz:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/86b0f05d731d604678e24f04c3124724fc9f71dc/pkg/cli/sql_util.go#L500)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

Undo the change on this line. 
</blockquote></details>

Done.
___
*[pkg/cli/sql_util.go, line 510 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/41121#-LphVSrBOhW_E0NqIUkV-r1-510:-Lpih8DyDVyeN6LdZpFn:b7n80qk) ([raw file](https://github.com/cockroachdb/cockroach/blob/86b0f05d731d604678e24f04c3124724fc9f71dc/pkg/cli/sql_util.go#L510)):*
> a typed bool with consts

Good idea, done. It is indeed clearer.
___
*[pkg/cli/sql_util.go, line 524 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/41121#-Lpi_P9D9wqO_1fhPo1k:-LpihB5cDLT_sjL4-cqd:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/86b0f05d731d604678e24f04c3124724fc9f71dc/pkg/cli/sql_util.go#L524)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

I don't think we want to be too chatty about this - we want users to be able to set COCKROACH_URL without being annoyed by these messages. I think we can either ignore the given path silently, or use it (if they set their COCKROACH_URL to a non-existent database, it's reasonable for these commands to fail). 
</blockquote></details>

Done.

**Comment by knz** [comment]
TFYRs!

bors r=bdarnell,mjibson
