### PR TITLE
changefeedccl: prevent deadlock in TestChangefeedKafkaMessageTooLarge

### LINKED ISSUE #107591: changefeedccl: flake in TestChangefeedKafkaMessageTooLarge
Found here: https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_BazelEssentialCi/11056281?hideProblemsFromDependencies=false&hideTestsFromDependencies=false&expandBuildChangesSection=true&expandBuildProblemsSection=true&expandBuildTestsSection=true

```
Failed
=== RUN   TestChangefeedKafkaMessageTooLarge/kafka/succeed_against_a_large_backfill
    helpers_test.go:745: still waiting for job status; current reverting
        --- FAIL: TestChangefeedKafkaMessageTooLarge/kafka/succeed_against_a_large_backfill (45.75s)
```

Jira issue: CRDB-30118

Epic CRDB-11732

### PR DESCRIPTION
**Pull request by jayshrivastava**
Previously, this test would deadlock due to kafka retrying messages too many times. These messages are stored in a buffer of size 1024 created by the CDC testing infra: https://github.com/cockroachdb/cockroach/blob/5c3f96d38cdc3a2d953ca3ffb1e39e97d7e5110e/pkg/ccl/changefeedccl/testfeed_test.go#L1819

The test asserts that 2000 messages pass through the buffer. When the test finishes, it stops reading from the buffer. The problem is that due to retries, there may be more messages sent to the buffer than that are read out of the buffer. Even after the 2000 messages are read and the test is shutting down, the sink may be blocked trying to put resolved messages (plus retries) in the buffer. If this happens, the changefeed resumer (same goroutine as the kafka sink) gets blocked and does not terminate when the job is cancelled at the end of the test.

This change caps the number of retries at 200 for this test, so there should be no more than 200 extra messages plus a few resolved messages during this test. This is far less than the buffer size of 1024.

See detailed explanation in #107591.

Fixes: https://github.com/cockroachdb/cockroach/issues/107591
Epic: none
Release note: None

### CODE REVIEW

File: pkg/ccl/changefeedccl/changefeed_test.go [hunk 1]
```diff
@@ -7702,8 +7702,11 @@ func TestChangefeedKafkaMessageTooLarge(t *testing.T) {
 
 			rnd, _ := randutil.NewPseudoRand()
 
+			maxFailures := 200
+			numFailures := 0
```
Comment (miretskiy) [inline pkg/ccl/changefeedccl/changefeed_test.go:7706]: Does this need to use atomics?

Comment (jayshrivastava) [reply pkg/ccl/changefeedccl/changefeed_test.go]: Yes it does

Comment (jayshrivastava) [reply pkg/ccl/changefeedccl/changefeed_test.go]: The sync producer and async producer are two separate goroutines that use it. I don't see much synchronization between them.

File: pkg/ccl/changefeedccl/changefeed_test.go [hunk 2]
```diff
@@ -7702,8 +7702,10 @@ func TestChangefeedKafkaMessageTooLarge(t *testing.T) {
 
 			rnd, _ := randutil.NewPseudoRand()
 
+			maxFailures := int64(200)
+			numFailures := atomic.Int64{}
```
Comment (miretskiy) [inline pkg/ccl/changefeedccl/changefeed_test.go:7706]: Just use car x atomic.int32

**Review by miretskiy — APPROVED** [review]

**Comment by jayshrivastava** [comment]
bors r=miretskiy
