### PR TITLE
sql: fix cast from string to array with width

### LINKED ISSUE #50132: sql: cast from string to array doesn't take into account type width
This cast works as expected when dealing with a constant string:
```
root@127.0.0.1:44725/defaultdb> select '{hello}'::varchar(2)[];
  varchar
-----------
  {he}
```

But it doesn't work in general:
```
root@127.0.0.1:44725/defaultdb> create table t (s string);
root@127.0.0.1:44725/defaultdb> insert into t values ('{hello}');
root@127.0.0.1:44725/defaultdb> select s::varchar(2)[] from t;
     s
-----------
  {hello}
(1 row)
```

### PR DESCRIPTION
**Pull request by RaduBerinde**
The code that performs a cast from string to array doesn't take into account the
width of the string type it is producing. This doesn't show up when the input is
a literal constant because the constant is first parsed as an array of (vanilla)
strings which is then subjected to a cast (to array of strings with width).

Fixes #50132.

Release note (bug fix): Fixed some cases of casting a string to a width-limited
string array.

### CODE REVIEW

File: pkg/sql/sem/tree/parse_string.go [hunk 1]
```diff
@@ -53,6 +53,12 @@ func ParseAndRequireString(t *types.T, s string, ctx ParseTimeContext) (Datum, e
 		i, err := ParseDInt(s)
 		return NewDOid(*i), err
 	case types.StringFamily:
+		// If the string type specifies a limit we truncate to that limit:
+		//   'hello'::CHAR(2) -> 'he'
+		// This is true of all the string type variants.
+		if t.Width() > 0 && int(t.Width()) < len(s) {
```
Comment (otan) [inline pkg/sql/sem/tree/parse_string.go:59]: interesting that parsing and storing strings that are too long have different results.

```
otan=# create temp table a (a varchar(1));
CREATE TABLE

otan=# insert into a values ('123');
ERROR:  value too long for type character varying(1)
```

Should this be rune count like we do here: https://github.com/cockroachdb/cockroach/blob/0f1a1631ea298c9818e4cf8e760a063cd17a9c63/pkg/sql/sqlbase/column_type_properties.go#L54 ?

**Review by otan — COMMENTED** [review]
wondering if we should backport this in case people relied on this behaviour in older versions (i hope not?!).

File: pkg/sql/sem/tree/parse_string.go (hunk 1 above)
Comment (RaduBerinde) [reply pkg/sql/sem/tree/parse_string.go:59]: Hmm. I copied this from PerformCast (string->string case). I think you're right though, postgres docs say that the limit is n "characters (not bytes)".

**Comment by RaduBerinde** [comment]
I will open a separate PR to fix the unicode stuff. And yeah, we should backport both (I already added the backport labels).

**Review by otan — APPROVED** [review]
ok! lgtm!

**Comment by RaduBerinde** [comment]
Opened #50156. I will rebase this on top of that.
