### PR TITLE
builtins: implement *_description with UDFs

### LINKED ISSUE #87947: `pg_catalog.col_description` is very slow
**Describe the problem**

Hi! 👋

The `pg_catalog.col_description` function runs very slowly, making any queries that use it take ~20 seconds per invocation.

**Reproduction**

The following SQL query is used to fetch column descriptions for all tables:

```sql
WITH
  "tabletable" as ( SELECT "table".oid,
           "table".relkind,
           "table".relname AS "table_name",
           "schema".nspname AS "table_schema"
      FROM pg_catalog.pg_class "table"
      JOIN pg_catalog.pg_namespace "schema"
          ON schema.oid = "table".relnamespace
      WHERE "table".relkind IN ('r', 't', 'v', 'm', 'f', 'p')
        AND "schema".nspname NOT LIKE 'pg_%'
        AND "schema".nspname NOT IN ('information_schema', 'hdb_catalog', 'hdb_lib', '_timescaledb_internal', 'crdb_internal')
  )
SELECT
  "table".table_schema,
  "table".table_name,
  coalesce(columns.description, '[]') as columns
FROM "tabletable" "table"

LEFT JOIN LATERAL
  ( SELECT
      pg_catalog.col_description("table".oid, "column".attnum) as description
    FROM pg_catalog.pg_attribute "column"
    WHERE "column".attrelid = "table".oid
  ) columns ON true;
```

Run on a fresh start of the DB with no tables, it takes `25ms` to run.

If I add a single table...

```sql
CREATE TABLE test (id INT);
```

then running the above query takes `21.732s`.

If I comment out the `pg_catalog.col_description` line, so the end looks like this:

```sql
LEFT JOIN LATERAL
  ( SELECT
      '' as description
      -- pg_catalog.col_description("table".oid, "column".attnum) as description
    FROM pg_catalog.pg_attribute "column"
    WHERE "column".attrelid = "table".oid
  ) columns ON true;
```

Performance is fine again, and this takes `95ms` to run.

**Expected behavior**

Would expect this function to perform much more efficiently.

**Additional context**

This function is needed for Hasura GraphQL Engine. We are currently working around this by not fetching column descriptions.

Epic CRDB-11916
Jira issue: CRDB-19609

### LINKED ISSUE #95068: sql: pg_catalog.obj_description is very slow
**Describe the problem**

A [new feature](https://github.com/django/django/commit/78f163a4fb3937aca2e71786fbdd51a0ef39629e) in Django 4.2 (to be released in April) adds `obj_description` to an introspection query. The new query takes on the order of ten seconds when running Django's test suite.

**To Reproduce**

```sql
SELECT
    c.relname,
    CASE
        WHEN c.relispartition THEN 'p'
        WHEN c.relkind IN ('m', 'v') THEN 'v'
        ELSE 't'
    END,
    obj_description(c.oid)
FROM pg_catalog.pg_class c
LEFT JOIN pg_catalog.pg_namespace n ON n.oid = c.relnamespace
WHERE c.relkind IN ('f', 'm', 'p', 'r', 'v')
    AND n.nspname NOT IN ('pg_catalog', 'pg_toast')
    AND pg_catalog.pg_table_is_visible(c.oid)
```

**Environment:**
 - CockroachDB version v22.2.2 and v22.1.13. (I haven't been unable to test nightly due to another slowdown).

**Additional context**

The run time of Django's test suite went from ~1 hour to ~7 or more hours.

#87947 may be related, however, Django's introspection query that uses `col_description` doesn't appear to be slow.

Jira issue: CRDB-23305

Epic CRDB-17785

### PR DESCRIPTION
**Pull request by rafiss**
fixes https://github.com/cockroachdb/cockroach/issues/95068
fixes https://github.com/cockroachdb/cockroach/issues/87947

These builtin functions can be implemented using UDFs, which avoids using the internal executor, and improves the amount of duplicated work.

The new benchmarks have fewer roundtrips and no longer scale based on entity count:
- django_table_introspection_1_table: 8 -> 5
- django_table_introspection_8_tables: 15 -> 5

Release note: None

### CODE REVIEW

File: pkg/sql/sem/builtins/pg_builtins.go [hunk 1]
```diff
@@ -1065,70 +1065,70 @@ var pgBuiltins = map[string]builtinDefinition{
...
-					args[0].(*tree.DOid).Oid,
-				)
-			},
+			Body: fmt.Sprintf(
+				`SELECT description
+				 FROM pg_catalog.pg_description
+				 WHERE objoid = $1
+				 AND objsubid = 0
+				 AND classoid = CASE $2
+					 WHEN 'pg_class' THEN %[1]d
```
Comment (jordanlewis) [inline pkg/sql/sem/builtins/pg_builtins.go:1118]: I think we should do this using a join on pg_class rather than a hardcoded case/when list, unless there's a strong reason to do it this way? I guess it's maybe more efficient to do it this way - but will there be any compat issues with this?

**Review by jordanlewis — APPROVED** [review]

File: pkg/sql/sem/builtins/pg_builtins.go (hunk 1 above)
Comment (rafiss) [reply pkg/sql/sem/builtins/pg_builtins.go:1118]: what did you have in mind? do you mean `AND classoid = $2::regclass::oid`? i think that will have a performance penalty, but i'll check.

Comment (jordanlewis) [reply pkg/sql/sem/builtins/pg_builtins.go:1118]: Here's how I prototyped it. It definitely might be slower.

https://github.com/jordanlewis/cockroach/blob/show-functions-and-udf-builtins/pkg/sql/sem/builtins/pg_builtins.go#L1010-L1023

Comment (rafiss) [reply pkg/sql/sem/builtins/pg_builtins.go:1118]: the roundtrips were not affected by the JOIN approach, nor was the latency in my local manual testing, so i'll do it that way
