### PR TITLE
sctest: Parallelize declarative schema change tests

### LINKED ISSUE #107552: sql: flakes in TestBackupSuccessMixedVersion
Seen here: https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_BazelEssentialCi/11043373?hideProblemsFromDependencies=false&hideTestsFromDependencies=false&expandBuildChangesSection=true&expandBuildProblemsSection=true&expandBuildTestsSection=true

Stack trace: https://gist.github.com/mgartner/cbf8e6346ee8a5e89f5f5c9023e75bae

Jira issue: CRDB-30105

### LINKED ISSUE #108005: ccl/schemachangerccl: TestBackupSuccessMixedVersion_base_alter_table_alter_primary_key_drop_rowid failed
ccl/schemachangerccl.TestBackupSuccessMixedVersion_base_alter_table_alter_primary_key_drop_rowid [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Ci_TestsGcpLinuxX8664BigVm_CclUnitTests/11151110?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Ci_TestsGcpLinuxX8664BigVm_CclUnitTests/11151110?buildTab=artifacts#/) on master @ [8d2d2bf47cb3da1c27baa140a5afb5d28a5ed8f6](https://github.com/cockroachdb/cockroach/commits/8d2d2bf47cb3da1c27baa140a5afb5d28a5ed8f6):

Fatal error:

```
panic: test timed out after 14m55s

```
Stack: 

```
goroutine 969923 [running]:
testing.(*M).startAlarm.func1()
	GOROOT/src/testing/testing.go:2036 +0x8e
created by time.goFunc
	GOROOT/src/time/sleep.go:176 +0x32
```
<details><summary>Log preceding fatal error</summary>
<p>

```
        true
    datadriven.go:143: 
        /home/roach/.cache/bazel/_bazel_roach/c5a4e7d36696d9cd970af2045211a7df/sandbox/processwrapper-sandbox/1064/execroot/com_github_cockroachdb_cockroach/bazel-out/k8-fastbuild/bin/pkg/ccl/schemachangerccl/schemachangerccl_test_/schemachangerccl_test.runfiles/com_github_cockroachdb_cockroach/pkg/sql/schemachanger/testdata/end_to_end/alter_table_alter_primary_key_drop_rowid/alter_table_alter_primary_key_drop_rowid.definition:19:
        stage-exec [2 args]
        INSERT INTO t VALUES($stageKey);
        INSERT INTO t VALUES($stageKey + 1);
        ----
        pq: INSERT has more expressions than target columns, 2 expressions for 1 targets
    datadriven.go:143: 
        /home/roach/.cache/bazel/_bazel_roach/c5a4e7d36696d9cd970af2045211a7df/sandbox/processwrapper-sandbox/1064/execroot/com_github_cockroachdb_cockroach/bazel-out/k8-fastbuild/bin/pkg/ccl/schemachangerccl/schemachangerccl_test_/schemachangerccl_test.runfiles/com_github_cockroachdb_cockroach/pkg/sql/schemachanger/testdata/end_to_end/alter_table_alter_primary_key_drop_rowid/alter_table_alter_primary_key_drop_rowid.definition:27:
        stage-query [2 args]
        SELECT count(*)=$successfulStageCount*2 FROM t;
        ----
        true
=== RUN   TestBackupSuccessMixedVersion_base_alter_table_alter_primary_key_drop_rowid/post_commit_stage_1_of_15/restore_all_tables_in_database
=== RUN   TestBackupSuccessMixedVersion_base_alter_table_alter_primary_key_drop_rowid/post_commit_stage_3_of_15/restore_all_tables_in_database
=== RUN   TestBackupSuccessMixedVersion_base_alter_table_alter_primary_key_drop_rowid/post_commit_stage_3_of_15/restore_database_with_schema_only
=== RUN   TestBackupSuccessMixedVersion_base_alter_table_alter_primary_key_drop_rowid/post_commit_stage_4_of_15/restore_all_tables_in_database
=== RUN   TestBackupSuccessMixedVersion_base_alter_table_alter_primary_key_drop_rowid/post_commit_stage_4_of_15/restore_database
=== RUN   TestBackupSuccessMixedVersion_base_alter_table_alter_primary_key_drop_rowid/post_commit_stage_6_of_15/restore_database_with_schema_only
=== RUN   TestBackupSuccessMixedVersion_base_alter_table_alter_primary_key_drop_rowid/post_commit_stage_8_of_15/restore_database
=== RUN   TestBackupSuccessMixedVersion_base_alter_table_alter_primary_key_drop_rowid/post_commit_stage_8_of_15/restore_database_with_schema_only
=== RUN   TestBackupSuccessMixedVersion_base_alter_table_alter_primary_key_drop_rowid/post_commit_stage_10_of_15/restore_database
=== RUN   TestBackupSuccessMixedVersion_base_alter_table_alter_primary_key_drop_rowid/post_commit_stage_1_of_15/restore_database
=== RUN   TestBackupSuccessMixedVersion_base_alter_table_alter_primary_key_drop_rowid/post_commit_stage_1_of_15/restore_database_with_schema_only
=== RUN   TestBackupSuccessMixedVersion_base_alter_table_alter_primary_key_drop_rowid/post_commit_stage_5_of_15/restore_database_with_schema_only
=== RUN   TestBackupSuccessMixedVersion_base_alter_table_alter_primary_key_drop_rowid/post_commit_stage_7_of_15
=== RUN   TestBackupSuccessMixedVersion_base_alter_table_alter_primary_key_drop_rowid/post_commit_stage_7_of_15/restore_database
=== RUN   TestBackupSuccessMixedVersion_base_alter_table_alter_primary_key_drop_rowid/post_commit_stage_8_of_15/restore_all_tables_in_database
=== RUN   TestBackupSuccessMixedVersion_base_alter_table_alter_primary_key_drop_rowid/post_commit_stage_10_of_15
=== RUN   TestBackupSuccessMixedVersion_base_alter_table_alter_primary_key_drop_rowid/post_commit_stage_6_of_15
=== RUN   TestBackupSuccessMixedVersion_base_alter_table_alter_primary_key_drop_rowid/post_commit_stage_9_of_15/restore_database
=== RUN   TestBackupSuccessMixedVersion_base_alter_table_alter_primary_key_drop_rowid/post_commit_stage_3_of_15
=== RUN   TestBackupSuccessMixedVersion_base_alter_table_alter_primary_key_drop_rowid/post_commit_stage_6_of_15/restore_database
=== RUN   TestBackupSuccessMixedVersion_base_alter_table_alter_primary_key_drop_rowid/post_commit_stage_9_of_15/restore_database_with_schema_only
=== RUN   TestBackupSuccessMixedVersion_base_alter_table_alter_primary_key_drop_rowid/post_commit_stage_3_of_15/restore_database
=== RUN   TestBackupSuccessMixedVersion_base_alter_table_alter_primary_key_drop_rowid/post_commit_stage_1_of_15
=== RUN   TestBackupSuccessMixedVersion_base_alter_table_alter_primary_key_drop_rowid/post_commit_stage_2_of_15/restore_all_tables_in_database
=== RUN   TestBackupSuccessMixedVersion_base_alter_table_alter_primary_key_drop_rowid/post_commit_stage_7_of_15/restore_all_tables_in_database
=== RUN   TestBackupSuccessMixedVersion_base_alter_table_alter_primary_key_drop_rowid/post_commit_stage_8_of_15
=== RUN   TestBackupSuccessMixedVersion_base_alter_table_alter_primary_key_drop_rowid/post_commit_stage_10_of_15/restore_all_tables_in_database
=== RUN   TestBackupSuccessMixedVersion_base_alter_table_alter_primary_key_drop_rowid/post_commit_stage_2_of_15/restore_database
=== RUN   TestBackupSuccessMixedVersion_base_alter_table_alter_primary_key_drop_rowid/post_commit_stage_4_of_15
=== RUN   TestBackupSuccessMixedVersion_base_alter_table_alter_primary_key_drop_rowid/post_commit_stage_4_of_15/restore_database_with_schema_only
=== RUN   TestBackupSuccessMixedVersion_base_alter_table_alter_primary_key_drop_rowid/post_commit_stage_5_of_15
=== RUN   TestBackupSuccessMixedVersion_base_alter_table_alter_primary_key_drop_rowid/post_commit_stage_5_of_15/restore_database
=== RUN   TestBackupSuccessMixedVersion_base_alter_table_alter_primary_key_drop_rowid/post_commit_stage_9_of_15
=== RUN   TestBackupSuccessMixedVersion_base_alter_table_alter_primary_key_drop_rowid/post_commit_stage_2_of_15
=== RUN   TestBackupSuccessMixedVersion_base_alter_table_alter_primary_key_drop_rowid/post_commit_stage_6_of_15/restore_all_tables_in_database
=== RUN   TestBackupSuccessMixedVersion_base_alter_table_alter_primary_key_drop_rowid/post_commit_stage_11_of_15
```
</p>
</details>
<details><summary>Help</summary>
<p>

See also: [How To Investigate a Go Test Failure \(internal\)](https://cockroachlabs.atlassian.net/l/c/HgfXfJgM)
</p>
</details>
/cc @cockroachdb/sql-foundations
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*TestBackupSuccessMixedVersion_base_alter_table_alter_primary_key_drop_rowid.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)
</sub>

Jira issue: CRDB-30283

### PR DESCRIPTION
**Pull request by Xiang-Gu**
Many of our declarative schema change tests follow the pattern of examining and testing certain behavior at each and every stage in the PostCommitPhase of the to-be-tested DDL(s). This includes our BACKUP/RESTORE, PAUSE/RESUME, and ROLLBACK testing suites. Previously, each (sub)test for each stage is run sequentially, and this commit parallelizes those (sub)tests. This can help with some of the recent timeout failures we saw.

For BACKUP/RESTORE tests, it also randomly skips some of them unless a test argument "run-all-backups" is set to true.

Fix #107552, fix #108005
Release note: None

### CODE REVIEW

**Review by rafiss — APPROVED** [review]
nice work!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/108073#-:-NawoE_y1laDMoHXCXSN:b-j4xmku)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @Xiang-Gu)

___
*[`pkg/sql/schemachanger/sctest/backup.go` line 105 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/108073#-Nawo6VV3UFeM8iJlYPS:-Nawo6VV3UFeM8iJlYPT:b-bs6800) ([raw file](https://github.com/cockroachdb/cockroach/blob/68066ef6468a8d092b03134a69d78fe9dcfa944a/pkg/sql/schemachanger/sctest/backup.go#L105)):*
> ```Go
> const runRate = .5
> 
> func maybeRandomlySkip(t *testing.T) {
> ```

did you consider if we could only do the random skipping if the number of stages is large? (say, larger than 10)

**Review by fqazi — COMMENTED** [review]
This is goodness, nice job!

> Reviewed 1 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/108073#-:-NawpjPD9DrmMU9Tb6-S:b-9k4ae2)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rafiss)

___
*[`pkg/sql/schemachanger/sctest/backup.go` line 105 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/108073#-Nawo6VV3UFeM8iJlYPS:-Nawp8KR-P-WHrWUE89u:bbmu0tr) ([raw file](https://github.com/cockroachdb/cockroach/blob/68066ef6468a8d092b03134a69d78fe9dcfa944a/pkg/sql/schemachanger/sctest/backup.go#L105)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

did you consider if we could only do the random skipping if the number of stages is large? (say, larger than 10)
</blockquote></details>

+1

Also, apply this at the stage level. So, that we have more even sampling

**Review by rafiss — APPROVED** [review]
thanks for making the change! i will merge this since the test flake is appearing more in Bazel Essential CI, so hopefully this will help

bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/108073#-:-Nayed5i6QtFm6hxzHay:b8plbis)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @fqazi)

File: pkg/sql/schemachanger/sctest/framework.go [hunk 1]
```diff
@@ -644,83 +644,90 @@ func (cs CumulativeTestCaseSpec) run(t *testing.T, fn func(t *testing.T)) bool {
...
+					StagesCount:        postCommitNonRevertibleCount,
+					After:              after,
+					DatabaseName:       dbName,
+				})
+			}
+			var hasFailed bool
+			for _, tc := range testCases {
+				fn := func(t *testing.T) {
+					t.Parallel() // SAFE FOR TESTING
+					tf(t, tc)
```
Comment (renatolabs) [inline pkg/sql/schemachanger/sctest/framework.go:717]: One unfortunate aspect of this idiom of iterating over `testCases` combined with `t.Parallel` is that it's very easy to forget that the `tc` variable will be captured by reference in this closure. As a result, this test is only testing the last `testCase`. We must copy the loop variable in the loop.

This will eventually no longer be a problem [1]; we also have a linter for this type of mistake, but it's not smart enough to detect cases like this. In the mean time, we unfortunately have to be aware of this footgun.

[1] https://github.com/golang/go/issues/60078
