### PR TITLE
filetable: allow overwrite during BACKUP and fix delete bug

### LINKED ISSUE #53995: userfile storage rejects attempts to overwrite files
BACKUP requires the ability to overwrite files in the ExternalStorage it is writing to, egs: BACKUP-CHECKPOINT is written at multiple stages throughout a BACKUP. Userfile rejects any attempts to write files with the same name twice, thereby not working well with BACKUP semantics.

### PR DESCRIPTION
**Pull request by adityamaru**
BACKUP should be able to overwrite files written to userfile.
Previously, we had an existence check preventing files with the
same name from being written again, now we Delete the old file
before attempting to write the new one (in the same txn).
This only applies to BACKUP, userfile upload still prevents dup
files from being uploaded.

This change also fixes a bug which was introduced to deletion
when we switched over to using UUIDs.

Lastly, this change removes the txn retry loop from userfile storage
and moves it to where the chunk is being written to the tables. This
was needed because txn retries were missing reading bytes between retry
runs because of the manner in which they are sent from the copy machine.

Addded BACKUP/RESTORE unit tests for userfile.

Fixes: #53995

Release justification: bug fixes and low-risk updates to new functionality

### CODE REVIEW

File: pkg/ccl/backupccl/backup_test.go [hunk 1]
```diff
@@ -283,6 +283,25 @@ func TestBackupRestoreStatementResult(t *testing.T) {
 	}
 }
 
+func TestBackupRestoreSingleUserfile(t *testing.T) {
```
Comment (adityamaru) [inline pkg/ccl/backupccl/backup_test.go:286]: The reason I marked this as a WIP is that I need some help understanding why the new userfile Backup and Restore test behaves the way it does.
- Testing locally, I am able to BACKUP/RESTORE tables and databases correctly (no error thrown).
- The commented out implementation of this test also does not raise any errors.

When I switch to using some of the more involved infrastructure we have for testing the BACKUP/RESTORE of database data, I get a  `pq: importing span /Table/53/1{-/100}: checksum mismatch for 586866600006090753.sst` when the `RESTORE` stmt is runs. All the BACKUP verification steps before it run fine. I'm wondering whether it is something to do with how userfile chunks its data, I'm not sure how to debug this further?

Comment (adityamaru) [reply pkg/ccl/backupccl/backup_test.go:286]: I also realized that if I set the splits to 0 when generating the bank data in `backupRestoreTestSetupWithParams` and remove the index created on data.bank, the restore goes through fine. I'm not sure how all these things tie together to cause that checksum mismatch.

Comment (pbardea) [reply pkg/ccl/backupccl/backup_test.go:286]: I looked into this a bit and I think it looks like it has to do with the userfile being able to handle retries. I think the fix would look something like https://github.com/cockroachdb/cockroach/pull/53940.

Comment (adityamaru) [reply pkg/ccl/backupccl/backup_test.go:286]: Thanks for looking into this Paul, I'm wondering if it is better to just eliminate the possibility of a txn retry in WriteFile and switch to using the internal executor to just `BEGIN, COMMIT/ROLLBACK`.

This also simplifies the interaction with the copy machine which wraps an `io.PipeReader` in a `noopSeeker` currently. Implementing seek on a pipe reader where we don't have access to all the data at once seems complicated? We would need some buffering/state logic. @miretskiy do you have any inputs here?

Comment (pbardea) [reply pkg/ccl/backupccl/backup_test.go:286]: Hmm, I think that the retry semantics are useful since the transaction may get a retry request. But it looks like only the creation of writer needs to be transactional, so it looks like we can move the writing of the data outside the txn?

**Comment by adityamaru** [comment]
This is RFAL. It includes the changes to the WriteFile txn semantics discussed on Slack.

**Comment by adityamaru** [comment]
stressrace is passing locally for both the unit tests locally, but its failing with a timeout when run on CI. Trying to see if it is the MultiNode one or the SingleNode one.

**Review by pbardea — APPROVED** [review]
LGTM with some nits. It would probably be best if someone more familiar with the filewriter also looked at it though.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/53926#-:-MGi-uLpBE_S4J7z4Ggi:b-q7xrs6)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @adityamaru, @dt, and @miretskiy)

___
*[pkg/storage/cloudimpl/file_table_storage.go, line 215 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/53926#-MGhzkTd4J3LJ926F1DE:-MGhzkTd4J3LJ926F1DF:b-dy7g69) ([raw file](https://github.com/cockroachdb/cockroach/blob/367e1f19e3d0e0ace525a642cd77cd566a9e8dd1/pkg/storage/cloudimpl/file_table_storage.go#L215)):*
> ```Go
> 	}()
> 
> 	_, err = f.ie.Exec(ctx, "userfile-write-file-txn", nil, `BEGIN`)
> ```

nit: /* txn */ comment here and above
___
*[pkg/storage/cloudimpl/filetable/file_table_read_writer.go, line 394 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/53926#-MGhhxsZ386jxfrUA5-S:-MGhhxsZ386jxfrUA5-T:bvg69g8) ([raw file](https://github.com/cockroachdb/cockroach/blob/367e1f19e3d0e0ace525a642cd77cd566a9e8dd1/pkg/storage/cloudimpl/filetable/file_table_read_writer.go#L394)):*
> ```Go
> var deletePayloadQueryPlaceholder = `DELETE FROM %s WHERE file_id IN (SELECT file_id FROM %s WHERE filename=$1)`
> 
> var deleteFileMetadataQueryPlaceholder = `DELETE FROM %s WHERE filename=$1`
> ```

nit: s/var/const for here and above.
___
*[pkg/storage/cloudimpl/filetable/file_table_read_writer.go, line 407 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/53926#-MGhiIRR2o4id0E7M9lE:-MGhiIRS2-MikIHJKy0O:bw1acxc) ([raw file](https://github.com/cockroachdb/cockroach/blob/367e1f19e3d0e0ace525a642cd77cd566a9e8dd1/pkg/storage/cloudimpl/filetable/file_table_read_writer.go#L407)):*
> ```Go
> 
> 	execSessionDataOverride := sessiondata.InternalExecutorOverride{User: f.username}
> 	_, err := ie.ExecEx(ctx, "delete-payload-table", nil, execSessionDataOverride,
> ```

nit: `/* txn */` comment after `nil`
___
*[pkg/storage/cloudimpl/filetable/file_table_read_writer.go, line 470 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/53926#-MGhyn5K3HfgApqUYsxe:-MGhyn5L35KaMX4_dmCA:bqa4tbt) ([raw file](https://github.com/cockroachdb/cockroach/blob/367e1f19e3d0e0ace525a642cd77cd566a9e8dd1/pkg/storage/cloudimpl/filetable/file_table_read_writer.go#L470)):*
> ```Go
> // Write inserts a single row into the Payload table as an operation in the
> // transaction txn.
> func (p *payloadWriter) Write(buf []byte, txn *kv.Txn) (int, error) {
> ```

Since this is no longer an `io.Writer`, what do you think of renaming this to `WriteChunk`? Just by looking at the interface I would expect `payloadWriter.Write` to write the entire payload, so I think renaming this would make it more clear what it's doing.
___
*[pkg/storage/cloudimpl/filetable/file_table_read_writer.go, line 515 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/53926#-MGhhcdL4EGInX2t6c7G:-MGhhcdMBHAR7Xx2i52g:byzyz5m) ([raw file](https://github.com/cockroachdb/cockroach/blob/367e1f19e3d0e0ace525a642cd77cd566a9e8dd1/pkg/storage/cloudimpl/filetable/file_table_read_writer.go#L515)):*
> ```Go
> 		fileTableName)
> 
> 	res, err := ie.QueryRowEx(ctx, "insert-file-name", nil,
> ```

nit: can we add a /* txn */ comment here to call out the nil txn.
___
*[pkg/storage/cloudimpl/filetable/file_table_read_writer.go, line 596 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/53926#-MGi-0_85fUau8VyLe24:-MGi-0_85fUau8VyLe25:bi4lqld) ([raw file](https://github.com/cockroachdb/cockroach/blob/367e1f19e3d0e0ace525a642cd77cd566a9e8dd1/pkg/storage/cloudimpl/filetable/file_table_read_writer.go#L596)):*
> ```Go
> 	if w.buf.Len() > 0 {
> 		if err := w.pw.db.Txn(w.pw.ctx, func(ctx context.Context, txn *kv.Txn) error {
> 			if n, err := w.pw.Write(w.buf.Bytes(), txn); err != nil || n != w.buf.Len() {
> ```

unrelated to this pr: if `err` is `nil` and we failed to write the entire buffer (`n != w.buf.Len()`), won't we still return `nil` here and things would have appeared to have succeeded? It shouldn't matter in this case since the payload writer always returns the length of the buffer, but it still seems like we want something like an else-if for this case and return an error like `io.ErrShortWrite`.
___
*[pkg/storage/cloudimpl/filetable/file_table_read_writer.go, line 609 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/53926#-MGhzWbM0o-YpBWXx4EM:-MGhzWbM0o-YpBWXx4EN:bgkard1) ([raw file](https://github.com/cockroachdb/cockroach/blob/367e1f19e3d0e0ace525a642cd77cd566a9e8dd1/pkg/storage/cloudimpl/filetable/file_table_read_writer.go#L609)):*
> ```Go
> 	updateFileSizeQuery := fmt.Sprintf(`UPDATE %s SET file_size=$1 WHERE filename=$2`,
> 		w.fileTableName)
> 	_, err := w.pw.ie.QueryEx(w.pw.ctx, "update-file-size", nil,
> ```

nit: /* txn */ comment
___
*[pkg/storage/cloudimpl/filetable/filetabletest/file_table_read_writer_test.go, line 262 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/53926#-MGhhMD_ASdf6NJVl6nB:-MGhhMD_ASdf6NJVl6nC:bjbm6zc) ([raw file](https://github.com/cockroachdb/cockroach/blob/367e1f19e3d0e0ace525a642cd77cd566a9e8dd1/pkg/storage/cloudimpl/filetable/filetabletest/file_table_read_writer_test.go#L262)):*
> ```Go
> 		randutil.ReadTestdataBytes(randGen, data)
> 
> 		err := kvDB.Txn(ctx, func(ctx context.Context, txn *kv.Txn) error {
> ```

Do we use this txn anymore? Do we need this anymore?

**Review by adityamaru — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/53926)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dt, @miretskiy, and @pbardea)

___
*[pkg/storage/cloudimpl/filetable/file_table_read_writer.go, line 470 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/53926#-MGhyn5K3HfgApqUYsxe:-MGiCuj83lKXWiij8RaS:b1vwk6g) ([raw file](https://github.com/cockroachdb/cockroach/blob/367e1f19e3d0e0ace525a642cd77cd566a9e8dd1/pkg/storage/cloudimpl/filetable/file_table_read_writer.go#L470)):*
<details><summary><i>Previously, pbardea (Paul Bardea) wrote…</i></summary><blockquote>

Since this is no longer an `io.Writer`, what do you think of renaming this to `WriteChunk`? Just by looking at the interface I would expect `payloadWriter.Write` to write the entire payload, so I think renaming this would make it more clear what it's doing.
</blockquote></details>

good point changed.
___
*[pkg/storage/cloudimpl/filetable/file_table_read_writer.go, line 596 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/53926#-MGi-0_85fUau8VyLe24:-MGiEfuC6JEFB8Mp2Ib2:b-10bat2) ([raw file](https://github.com/cockroachdb/cockroach/blob/367e1f19e3d0e0ace525a642cd77cd566a9e8dd1/pkg/storage/cloudimpl/filetable/file_table_read_writer.go#L596)):*
<details><summary><i>Previously, pbardea (Paul Bardea) wrote…</i></summary><blockquote>

unrelated to this pr: if `err` is `nil` and we failed to write the entire buffer (`n != w.buf.Len()`), won't we still return `nil` here and things would have appeared to have succeeded? It shouldn't matter in this case since the payload writer always returns the length of the buffer, but it still seems like we want something like an else-if for this case and return an error like `io.ErrShortWrite`.
</blockquote></details>

ah yes, nice catch, added an else if.
___
*[pkg/storage/cloudimpl/filetable/filetabletest/file_table_read_writer_test.go, line 262 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/53926#-MGhhMD_ASdf6NJVl6nB:-MGiDwBsBX7kFxyGt2mg:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/367e1f19e3d0e0ace525a642cd77cd566a9e8dd1/pkg/storage/cloudimpl/filetable/filetabletest/file_table_read_writer_test.go#L262)):*
<details><summary><i>Previously, pbardea (Paul Bardea) wrote…</i></summary><blockquote>

Do we use this txn anymore? Do we need this anymore?
</blockquote></details>

Done.

**Review by miretskiy — APPROVED** [review]
I'm giving an :lgtm: , given the time sensitive nature of this PR.  However, I do have some requests/concerns
on this PR; and I would love to see those addressed .

> Reviewed 1 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/53926#-:-MGiNwMNB97a6N2GPCk5:bdc8gh3)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @adityamaru, @dt, @miretskiy, and @pbardea)

___
*[pkg/storage/cloudimpl/file_table_storage.go, line 212 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/53926#-MGiMw379e1M9PHg4kau:-MGiMw379e1M9PHg4kav:b-t0qn4q) ([raw file](https://github.com/cockroachdb/cockroach/blob/4e07bcc60ca3a065ca86b0edef671091ff8685a0/pkg/storage/cloudimpl/file_table_storage.go#L212)):*
> ```Go
> 
> 	defer func() {
> 		_, _ = f.ie.Exec(ctx, "userfile-write-file-commit", nil /* txn */, `COMMIT`)
> ```

So, we commit regardless of the errors encountered while writing the file?

More than the question of correctness, my question above shows to me that we need nice, big, fat comment, either here or in the file table write (probably there is best) giving a nice high level overview of data writing semantics; transactions, retry, etc, etc, etc.  I think this code became already rather complex.
___
*[pkg/storage/cloudimpl/filetable/file_table_read_writer.go, line 404 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/53926#-MGiKDT-8BsjMjXoutgZ:-MGiKDT-8BsjMjXoutg_:b-8kfr1g) ([raw file](https://github.com/cockroachdb/cockroach/blob/4e07bcc60ca3a065ca86b0edef671091ff8685a0/pkg/storage/cloudimpl/filetable/file_table_read_writer.go#L404)):*
> ```Go
> 	ctx context.Context, filename string, ie *sql.InternalExecutor,
> ) error {
> 	deletePayloadQuery := fmt.Sprintf(deletePayloadQueryPlaceholder, f.GetFQPayloadTableName(),
> ```

a nit: (feel free to ignore) i think i would have added a simple getDepeteQuery/getDeletePayloiadQuery on f.
___
*[pkg/storage/cloudimpl/filetable/file_table_read_writer.go, line 846 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/53926#-MGiNFv22gkcFQ0eW-a_:-MGiNFv22gkcFQ0eW-aa:b-wf1lfx) ([raw file](https://github.com/cockroachdb/cockroach/blob/4e07bcc60ca3a065ca86b0edef671091ff8685a0/pkg/storage/cloudimpl/filetable/file_table_read_writer.go#L846)):*
> ```Go
> 	if err != nil {
> 		return nil, err
> 	}
> ```

I don't really like that we have to add this here.  Can an explicit delete file call be made by backup instead of relying (probably erroneously) on the file storage Write to "overwrite"?
___
*[pkg/storage/cloudimpl/filetable/filetabletest/file_table_read_writer_test.go, line 218 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/53926#-MGiMENU28aadDQRZrYW:-MGiMENU28aadDQRZrYX:b-s148tp) ([raw file](https://github.com/cockroachdb/cockroach/blob/4e07bcc60ca3a065ca86b0edef671091ff8685a0/pkg/storage/cloudimpl/filetable/filetabletest/file_table_read_writer_test.go#L218)):*
> ```Go
> 
> 		// Upload the same file again, and expect the old one to be overwritten.
> 		expected, err := uploadFile(ctx, testFileName, 12, 2, fileTableReadWriter, kvDB)
> ```

I would add a check to query the file uuid before we upload, and compare uuid here to really verify that the file was, indeed, overwritten.
___
*[pkg/storage/cloudimpl/filetable/filetabletest/file_table_read_writer_test.go, line 234 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/53926#-MGiMZyS7Ry6H2yadY8i:-MGiMZyS7Ry6H2yadY8j:bchittf) ([raw file](https://github.com/cockroachdb/cockroach/blob/4e07bcc60ca3a065ca86b0edef671091ff8685a0/pkg/storage/cloudimpl/filetable/filetabletest/file_table_read_writer_test.go#L234)):*
> ```Go
> 		expectedNumChunks := (12 / 2) + (12 % 2)
> 		checkNumberOfPayloadChunks(ctx, t, fileTableReadWriter.GetFQFileTableName(),
> 			fileTableReadWriter.GetFQPayloadTableName(), testFileName, expectedNumChunks, sqlDB)
> ```

This verifies that the second file uploaded has the right number of chunks.
Should you also verify the old file didn't leave any chunks behind?

**Review by adityamaru — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/53926)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @dt, @miretskiy, and @pbardea)

___
*[pkg/storage/cloudimpl/file_table_storage.go, line 212 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/53926#-MGiMw379e1M9PHg4kau:-MGiWZUy4Mg1gBmNmPfj:b-2bvl9t) ([raw file](https://github.com/cockroachdb/cockroach/blob/4e07bcc60ca3a065ca86b0edef671091ff8685a0/pkg/storage/cloudimpl/file_table_storage.go#L212)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

So, we commit regardless of the errors encountered while writing the file?

More than the question of correctness, my question above shows to me that we need nice, big, fat comment, either here or in the file table write (probably there is best) giving a nice high level overview of data writing semantics; transactions, retry, etc, etc, etc.  I think this code became already rather complex.
</blockquote></details>

As discussed offline, a defer-ed commit will rollback if an error is thrown prior to when this closure is run. I have added the comment.
___
*[pkg/storage/cloudimpl/filetable/file_table_read_writer.go, line 404 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/53926#-MGiKDT-8BsjMjXoutgZ:-MGiWUT94NOZ6cbqI-JK:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/4e07bcc60ca3a065ca86b0edef671091ff8685a0/pkg/storage/cloudimpl/filetable/file_table_read_writer.go#L404)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

a nit: (feel free to ignore) i think i would have added a simple getDepeteQuery/getDeletePayloiadQuery on f.
</blockquote></details>

Done.
___
*[pkg/storage/cloudimpl/filetable/file_table_read_writer.go, line 846 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/53926#-MGiNFv22gkcFQ0eW-a_:-MGiWjJT8B92UmRFBuG5:ba4dw0u) ([raw file](https://github.com/cockroachdb/cockroach/blob/4e07bcc60ca3a065ca86b0edef671091ff8685a0/pkg/storage/cloudimpl/filetable/file_table_read_writer.go#L846)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

I don't really like that we have to add this here.  Can an explicit delete file call be made by backup instead of relying (probably erroneously) on the file storage Write to "overwrite"?
</blockquote></details>

As discussed offline this is a change that has an impact on all the ExternalStorage implementations which allow for file overwrites. It involves finding all the places in BACKUP where we require overwrite-ability. Created an issue to switch the responsibility from the ExternalStorage to BACKUP.
___
*[pkg/storage/cloudimpl/filetable/filetabletest/file_table_read_writer_test.go, line 218 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/53926#-MGiMENU28aadDQRZrYW:-MGiZTN5E6G_tgCFbA-a:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/4e07bcc60ca3a065ca86b0edef671091ff8685a0/pkg/storage/cloudimpl/filetable/filetabletest/file_table_read_writer_test.go#L218)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

I would add a check to query the file uuid before we upload, and compare uuid here to really verify that the file was, indeed, overwritten.
</blockquote></details>

Done.
___
*[pkg/storage/cloudimpl/filetable/filetabletest/file_table_read_writer_test.go, line 234 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/53926#-MGiMZyS7Ry6H2yadY8i:-MGiZUOV7wiyvXOzYgTJ:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/4e07bcc60ca3a065ca86b0edef671091ff8685a0/pkg/storage/cloudimpl/filetable/filetabletest/file_table_read_writer_test.go#L234)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

This verifies that the second file uploaded has the right number of chunks.
Should you also verify the old file didn't leave any chunks behind?
</blockquote></details>

Done.

**Review by dt — APPROVED** [review]

**Comment by adityamaru** [comment]
TFTR!

bors r+
