### PR TITLE
distsqlrun: listen for drain signal in a stopper task

### LINKED ISSUE #16042: sql/distsqlrun: TestClusterFlow failed under stress
SHA: https://github.com/cockroachdb/cockroach/commits/4e68800f6b47c22e142b48fdb390a0e5d249a8cf

Parameters:
```
TAGS=
GOFLAGS=
```

Stress build found a failed test: https://teamcity.cockroachdb.com/viewLog.html?buildId=253314&tab=buildLog

```
W170520 06:27:16.344342 34 server/status/runtime.go:111  Could not parse build timestamp: parsing time "" as "2006/01/02 15:04:05": cannot parse "" as "2006"
I170520 06:27:16.347425 34 server/config.go:436  1 storage engine initialized
I170520 06:27:16.347991 34 server/node.go:454  [n?] store [n0,s0] not bootstrapped
I170520 06:27:16.351502 34 server/node.go:389  [n?] **** cluster 8d23d555-25e0-4bc1-a436-d7443268a614 has been created
I170520 06:27:16.351568 34 server/node.go:390  [n?] **** add additional nodes by specifying --join=127.0.0.1:58850
I170520 06:27:16.357094 34 storage/store.go:1252  [n1] [n1,s1]: failed initial metrics computation: [n1,s1]: system config not yet available
I170520 06:27:16.357124 34 server/node.go:467  [n1] initialized store [n1,s1]: {Capacity:536870912 Available:536870912 RangeCount:1 LeaseCount:0}
I170520 06:27:16.357141 34 server/node.go:351  [n1] node ID 1 initialized
I170520 06:27:16.357243 34 gossip/gossip.go:297  [n1] NodeDescriptor set to node_id:1 address:<network_field:"tcp" address_field:"127.0.0.1:58850" > attrs:<> locality:<> 
I170520 06:27:16.357387 34 storage/stores.go:296  [n1] read 0 node addresses from persistent storage
I170520 06:27:16.357462 34 server/node.go:608  [n1] connecting to gossip network to verify cluster ID...
I170520 06:27:16.358008 34 server/node.go:633  [n1] node connected via gossip and verified as part of cluster "8d23d555-25e0-4bc1-a436-d7443268a614"
I170520 06:27:16.358046 34 server/node.go:405  [n1] node=1: started with [[]=] engine(s) and attributes []
I170520 06:27:16.367253 34 sql/executor.go:349  [n1] creating distSQLPlanner with address {tcp 127.0.0.1:58850}
I170520 06:27:16.388403 34 server/server.go:736  [n1] starting https server at 127.0.0.1:60435
I170520 06:27:16.388427 34 server/server.go:737  [n1] starting grpc/postgres server at 127.0.0.1:58850
I170520 06:27:16.388442 34 server/server.go:738  [n1] advertising CockroachDB node at 127.0.0.1:58850
I170520 06:27:16.392868 34 sql/event_log.go:101  [n1] Event: "alter_table", target: 12, info: {TableName:eventlog Statement:ALTER TABLE system.eventlog ALTER COLUMN uniqueid SET DEFAULT uuid_v4() User:node MutationID:0 CascadeDroppedViews:[]}
I170520 06:27:16.397491 34 sql/lease.go:372  [n1] publish: descID=12 (eventlog) version=2 mtime=2017-05-20 06:27:16.397464916 +0000 UTC
I170520 06:27:16.412281 34 server/server.go:848  [n1] done ensuring all necessary migrations have run
I170520 06:27:16.412305 34 server/server.go:850  [n1] serving sql connections
W170520 06:27:16.418287 34 server/status/runtime.go:111  Could not parse build timestamp: parsing time "" as "2006/01/02 15:04:05": cannot parse "" as "2006"
W170520 06:27:16.418515 34 gossip/gossip.go:1196  [n?] no incoming or outgoing connections
I170520 06:27:16.419192 34 server/config.go:436  1 storage engine initialized
I170520 06:27:16.419427 34 server/node.go:454  [n?] store [n0,s0] not bootstrapped
I170520 06:27:16.419445 34 storage/stores.go:296  [n?] read 0 node addresses from persistent storage
I170520 06:27:16.419459 34 server/node.go:608  [n?] connecting to gossip network to verify cluster ID...
I170520 06:27:16.420293 386 sql/event_log.go:101  [n1] Event: "node_join", target: 1, info: {Descriptor:{NodeID:1 Address:{NetworkField:tcp AddressField:127.0.0.1:58850} Attrs: Locality:} ClusterID:8d23d555-25e0-4bc1-a436-d7443268a614 StartedAt:1495261636358019779 LastUp:1495261636358019779}
I170520 06:27:16.427636 393 gossip/client.go:131  [n?] started gossip client to 127.0.0.1:58850
I170520 06:27:16.428080 288 gossip/server.go:234  [n1] received initial cluster-verification connection from {tcp 127.0.0.1:46842}
I170520 06:27:16.428340 34 server/node.go:633  [n?] node connected via gossip and verified as part of cluster "8d23d555-25e0-4bc1-a436-d7443268a614"
I170520 06:27:16.428602 289 storage/stores.go:312  [n?] wrote 1 node addresses to persistent storage
I170520 06:27:16.429501 34 kv/dist_sender.go:367  [n?] unable to determine this node's attributes for replica selection; node is most likely bootstrapping
I170520 06:27:16.429983 34 server/node.go:344  [n?] new node allocated ID 2
I170520 06:27:16.430023 34 gossip/gossip.go:297  [n2] NodeDescriptor set to node_id:2 address:<network_field:"tcp" address_field:"127.0.0.1:46842" > attrs:<> locality:<> 
I170520 06:27:16.430065 34 server/node.go:405  [n2] node=2: started with [[]=] engine(s) and attributes []
I170520 06:27:16.430118 34 sql/executor.go:349  [n2] creating distSQLPlanner with address {tcp 127.0.0.1:46842}
I170520 06:27:16.431171 498 storage/stores.go:312  [n1] wrote 1 node addresses to persistent storage
I170520 06:27:16.442094 34 server/server.go:736  [n2] starting https server at 127.0.0.1:33202
I170520 06:27:16.442109 34 server/server.go:737  [n2] starting grpc/postgres server at 127.0.0.1:46842
I170520 06:27:16.442116 34 server/server.go:738  [n2] advertising CockroachDB node at 127.0.0.1:46842
I170520 06:27:16.444475 433 server/node.go:589  [n2] bootstrapped store [n2,s2]
I170520 06:27:16.447494 34 server/server.go:848  [n2] done ensuring all necessary migrations have run
I170520 06:27:16.447512 34 server/server.go:850  [n2] serving sql connections
I170520 06:27:16.453518 310 sql/event_log.go:101  [n2] Event: "node_join", target: 2, info: {Descriptor:{NodeID:2 Address:{NetworkField:tcp AddressField:127.0.0.1:46842} Attrs: Locality:} ClusterID:8d23d555-25e0-4bc1-a436-d7443268a614 StartedAt:1495261636430054357 LastUp:1495261636430054357}
W170520 06:27:16.454576 34 server/status/runtime.go:111  Could not parse build timestamp: parsing time "" as "2006/01/02 15:04:05": cannot parse "" as "2006"
W170520 06:27:16.454775 34 gossip/gossip.go:1196  [n?] no incoming or outgoing connections
I170520 06:27:16.455431 34 server/config.go:436  1 storage engine initialized
I170520 06:27:16.455690 34 server/node.go:454  [n?] store [n0,s0] not bootstrapped
I170520 06:27:16.455703 34 storage/stores.go:296  [n?] read 0 node addresses from persistent storage
I170520 06:27:16.455720 34 server/node.go:608  [n?] connecting to gossip network to verify cluster ID...
I170520 06:27:16.479509 384 gossip/client.go:131  [n?] started gossip client to 127.0.0.1:58850
I170520 06:27:16.480185 660 gossip/server.go:234  [n1] received initial cluster-verification connection from {tcp 127.0.0.1:60346}
I170520 06:27:16.480656 34 server/node.go:633  [n?] node connected via gossip and verified as part of cluster "8d23d555-25e0-4bc1-a436-d7443268a614"
I170520 06:27:16.480954 661 storage/stores.go:312  [n?] wrote 1 node addresses to persistent storage
I170520 06:27:16.480978 661 storage/stores.go:312  [n?] wrote 2 node addresses to persistent storage
I170520 06:27:16.481513 34 kv/dist_sender.go:367  [n?] unable to determine this node's attributes for replica selection; node is most likely bootstrapping
I170520 06:27:16.482020 34 server/node.go:344  [n?] new node allocated ID 3
I170520 06:27:16.482058 34 gossip/gossip.go:297  [n3] NodeDescriptor set to node_id:3 address:<network_field:"tcp" address_field:"127.0.0.1:60346" > attrs:<> locality:<> 
I170520 06:27:16.482118 34 server/node.go:405  [n3] node=3: started with [[]=] engine(s) and attributes []
I170520 06:27:16.482158 34 sql/executor.go:349  [n3] creating distSQLPlanner with address {tcp 127.0.0.1:60346}
I170520 06:27:16.482295 651 storage/stores.go:312  [n1] wrote 2 node addresses to persistent storage
I170520 06:27:16.482477 652 storage/stores.go:312  [n2] wrote 2 node addresses to persistent storage
I170520 06:27:16.495619 676 server/node.go:589  [n3] bootstrapped store [n3,s3]
I170520 06:27:16.497117 34 server/server.go:736  [n3] starting https server at 127.0.0.1:54620
I170520 06:27:16.497133 34 server/server.go:737  [n3] starting grpc/postgres server at 127.0.0.1:60346
I170520 06:27:16.497140 34 server/server.go:738  [n3] advertising CockroachDB node at 127.0.0.1:60346
I170520 06:27:16.498107 34 server/server.go:848  [n3] done ensuring all necessary migrations have run
I170520 06:27:16.498126 34 server/server.go:850  [n3] serving sql connections
I170520 06:27:16.503030 816 sql/event_log.go:101  [n3] Event: "node_join", target: 3, info: {Descriptor:{NodeID:3 Address:{NetworkField:tcp AddressField:127.0.0.1:60346} Attrs: Locality:} ClusterID:8d23d555-25e0-4bc1-a436-d7443268a614 StartedAt:1495261636482105193 LastUp:1495261636482105193}
I170520 06:27:16.512993 788 sql/event_log.go:101  [client=127.0.0.1:37244,user=root,n1] Event: "create_database", target: 50, info: {DatabaseName:test Statement:CREATE DATABASE IF NOT EXISTS test User:root}
I170520 06:27:16.517590 788 sql/event_log.go:101  [client=127.0.0.1:37244,user=root,n1] Event: "create_table", target: 51, info: {TableName:test.t Statement:CREATE TABLE test.t (num INT PRIMARY KEY, digitsum INT, numstr STRING, INDEX s (digitsum)) User:root}
I170520 06:27:16.533672 34 sql/distsqlrun/cluster_test.go:222  Setting up flow on 0
I170520 06:27:16.535078 34 sql/distsqlrun/cluster_test.go:229  Setting up flow on 1
I170520 06:27:16.538431 34 sql/distsqlrun/cluster_test.go:236  Running flow on 2
I170520 06:27:16.568463 278 vendor/google.golang.org/grpc/transport/http2_server.go:392  transport: http2Server.HandleStreams failed to read frame: read tcp 127.0.0.1:58850->127.0.0.1:37234: use of closed network connection
	leaktest.go:90: Leaked goroutine: goroutine 843 [select]:
		github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/transport.(*recvBufferReader).Read(0xc4208be000, 0xc421f7a0d0, 0x5, 0x5, 0x0, 0x0, 0x0)
			/go/src/github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/transport/transport.go:145 +0x556
		github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/transport.(*Stream).Read(0xc420458700, 0xc421f7a0d0, 0x5, 0x5, 0x919372, 0x91b70d, 0xc420a01180)
			/go/src/github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/transport/transport.go:328 +0x59
		io.ReadAtLeast(0x251c0e0, 0xc420458700, 0xc421f7a0d0, 0x5, 0x5, 0x5, 0x8000, 0x8000, 0x0)
			/usr/local/go/src/io/io.go:307 +0xa9
		io.ReadFull(0x251c0e0, 0xc420458700, 0xc421f7a0d0, 0x5, 0x5, 0x0, 0x0, 0x0)
			/usr/local/go/src/io/io.go:325 +0x58
		github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc.(*parser).recvMsg(0xc421f7a0c0, 0x7fffffff, 0x25173e0, 0xc420626c60, 0xc420380118, 0x9, 0x9, 0x9)
			/go/src/github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/rpc_util.go:255 +0x69
		github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc.recv(0xc421f7a0c0, 0x252eaa0, 0x29f1c00, 0xc420458700, 0x25239e0, 0x29f1c00, 0x18aec40, 0xc42022e0b0, 0x7fffffff, 0x0, ...)
			/go/src/github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/rpc_util.go:351 +0x4d
		github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc.(*clientStream).RecvMsg(0xc421758840, 0x18aec40, 0xc42022e0b0, 0x0, 0x0)
			/go/src/github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/stream.go:379 +0xe9
		github.com/cockroachdb/cockroach/pkg/sql/distsqlrun.(*distSQLFlowStreamClient).Recv(0xc42022e040, 0xc4208a9050, 0x1a18680, 0xc42175a120)
			/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsqlrun/api.pb.go:247 +0x62
		github.com/cockroachdb/cockroach/pkg/sql/distsqlrun.(*outbox).waitForDrainSignalFromConsumer.func1(0xc420eba780, 0x2537c00, 0xc42022e040, 0x0, 0x0)
			/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsqlrun/outbox.go:285 +0x52
		created by github.com/cockroachdb/cockroach/pkg/sql/distsqlrun.(*outbox).waitForDrainSignalFromConsumer
			/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsqlrun/outbox.go:298 +0x8a
```

### PR DESCRIPTION
**Pull request by RaduBerinde**
Fixes #16042.

### CODE REVIEW

File: pkg/sql/distsqlrun/flow.go [hunk 1]
```diff
@@ -47,6 +48,8 @@ type FlowID struct {
 type FlowCtx struct {
 	log.AmbientContext
 
+	stopper *stop.Stopper
```
Comment (asubiotto) [inline pkg/sql/distsqlrun/flow.go]: Why is it necessary to add this `*Stopper` to the FlowCtx? Just wondering.

**Review by asubiotto — APPROVED** [review]

File: pkg/sql/distsqlrun/flow.go (hunk 1 above)
Comment (RaduBerinde) [inline pkg/sql/distsqlrun/flow.go]: So I can call RunAsyncTask on it.. Where do you suggest I put it?

Comment (asubiotto) [inline pkg/sql/distsqlrun/flow.go]: Ah, missed that link. This seems fine although I don't know this part of the code too well. Have you considered putting it in the `outbox`?

Comment (RaduBerinde) [inline pkg/sql/distsqlrun/flow.go]: Yes. I think it belongs in flowCtx, because other processors might want to have a handle on the stopper as well (e.g. to listen for a signal to exit early).

Comment (asubiotto) [inline pkg/sql/distsqlrun/flow.go]: Makes sense.

**Comment by arjunravinarayan** [comment]
:lgtm:

Could use a slightly more verbose commit message.

---

Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16961#-:-KohZIjLuoUK0f4XY5pH:b8uevhr)*

**Comment by RaduBerinde** [comment]
TFTRs! Updated commit msg.
