### PR TITLE
sql: fix flake in TestDistributedMergeResumePreservesProgress

### LINKED ISSUE #161311: sql: TestDistributedMergeResumePreservesProgress failed
sql.TestDistributedMergeResumePreservesProgress [failed](https://mesolite.cluster.engflow.com/invocations/default/a7387d96-d783-4b00-b941-08cc13f4fabf?testReportRun=1&testReportShard=14&testReportAttempt=1#targets-Ly9wa2cvc3FsOnNxbF90ZXN0) on master @ [76b16f67838a6a3339c68a4910ba965c999a3cb7](https://github.com/cockroachdb/cockroach/commits/76b16f67838a6a3339c68a4910ba965c999a3cb7):

```
    indexbackfiller_test.go:1302: [fast checkpoint pause during map] after distributed merge map phase, manifests count: 1
    indexbackfiller_test.go:1318: [fast checkpoint pause during map] after distributed merge iteration 1, manifests count: 13
    indexbackfiller_test.go:1318: [fast checkpoint pause during map] after distributed merge iteration 2, manifests count: 13
    indexbackfiller_test.go:1318: [fast checkpoint pause during map] after distributed merge iteration 3, manifests count: 13
    indexbackfiller_test.go:1318: [fast checkpoint pause during map] after distributed merge iteration 4, manifests count: 0
    indexbackfiller_test.go:1321: [fast checkpoint pause during map] final iteration 4 completed (direct KV ingest)
    indexbackfiller_test.go:1342: [slow checkpoint pause during map] before resuming backfill, checkpointed spans: []
    indexbackfiller_test.go:1296: [slow checkpoint pause during map] before index backfill progress update, completed spans: [/Table/104/{1-2}]
    indexbackfiller_test.go:1302: [slow checkpoint pause during map] after distributed merge map phase, manifests count: 1
    indexbackfiller_test.go:1318: [slow checkpoint pause during map] after distributed merge iteration 1, manifests count: 13
    indexbackfiller_test.go:1318: [slow checkpoint pause during map] after distributed merge iteration 2, manifests count: 13
    indexbackfiller_test.go:1318: [slow checkpoint pause during map] after distributed merge iteration 3, manifests count: 13
    indexbackfiller_test.go:1318: [slow checkpoint pause during map] after distributed merge iteration 4, manifests count: 0
    indexbackfiller_test.go:1321: [slow checkpoint pause during map] final iteration 4 completed (direct KV ingest)
    indexbackfiller_test.go:1342: [slow checkpoint pause during map] before resuming backfill, checkpointed spans: [/Table/104/{1-2}]
    indexbackfiller_test.go:1302: [pause after map phase before merge] after distributed merge map phase, manifests count: 1
    indexbackfiller_test.go:1305: [pause after map phase before merge] map phase complete, blocking to allow test to pause job
    indexbackfiller_test.go:1310: [pause after map phase before merge] context cancelled (job paused), exiting hook
    indexbackfiller_test.go:1302: [pause after map phase before merge] after distributed merge map phase, manifests count: 1
    indexbackfiller_test.go:1305: [pause after map phase before merge] map phase complete, blocking to allow test to pause job
    indexbackfiller_test.go:1308: [pause after map phase before merge] unblocked by test, continuing with merge iterations
    indexbackfiller_test.go:1318: [pause after map phase before merge] after distributed merge iteration 1, manifests count: 13
    indexbackfiller_test.go:1318: [pause after map phase before merge] after distributed merge iteration 2, manifests count: 13
    indexbackfiller_test.go:1318: [pause after map phase before merge] after distributed merge iteration 3, manifests count: 13
    indexbackfiller_test.go:1318: [pause after map phase before merge] after distributed merge iteration 4, manifests count: 0
    indexbackfiller_test.go:1321: [pause after map phase before merge] final iteration 4 completed (direct KV ingest)
    indexbackfiller_test.go:1302: [pause after iteration 1 with checkpoint] after distributed merge map phase, manifests count: 1
    indexbackfiller_test.go:1318: [pause after iteration 1 with checkpoint] after distributed merge iteration 1, manifests count: 13
    indexbackfiller_test.go:1328: [pause after iteration 1 with checkpoint] iteration 1 complete, blocking to allow test to pause job
    indexbackfiller_test.go:1333: [pause after iteration 1 with checkpoint] context cancelled (job paused), exiting hook
    indexbackfiller_test.go:1302: [pause after iteration 1 with checkpoint] after distributed merge map phase, manifests count: 1
    indexbackfiller_test.go:1318: [pause after iteration 1 with checkpoint] after distributed merge iteration 1, manifests count: 13
    indexbackfiller_test.go:1328: [pause after iteration 1 with checkpoint] iteration 1 complete, blocking to allow test to pause job
    indexbackfiller_test.go:1333: [pause after iteration 3 with checkpoint] context cancelled (job paused), exiting hook
    indexbackfiller_test.go:1586: -- test log scope end --
test logs left over in: outputs.zip/logTestDistributedMergeResumePreservesProgress3618643650
--- FAIL: TestDistributedMergeResumePreservesProgress (97.73s)
=== RUN   TestDistributedMergeResumePreservesProgress/pause_after_iteration_1_with_checkpoint
    indexbackfiller_test.go:1431: checkpoint interval set to 10ms, waitForCheckpoint=true
    indexbackfiller_test.go:1252: checkpoint contains 1 SST manifests
    indexbackfiller_test.go:1457: condition failed to evaluate within 30s: from indexbackfiller_test.go:1464: expected job to be succeeded, but found status: running
--- FAIL: TestDistributedMergeResumePreservesProgress/pause_after_iteration_1_with_checkpoint (30.67s)
=== RUN   TestDistributedMergeResumePreservesProgress/pause_after_iteration_2_with_checkpoint
    indexbackfiller_test.go:1431: checkpoint interval set to 10ms, waitForCheckpoint=true
    indexbackfiller_test.go:1443: condition failed to evaluate within 30s: sql: no rows in result set
--- FAIL: TestDistributedMergeResumePreservesProgress/pause_after_iteration_2_with_checkpoint (30.56s)
=== RUN   TestDistributedMergeResumePreservesProgress/pause_after_iteration_3_with_checkpoint
    indexbackfiller_test.go:1431: checkpoint interval set to 10ms, waitForCheckpoint=true
    indexbackfiller_test.go:1443: condition failed to evaluate within 30s: sql: no rows in result set
--- FAIL: TestDistributedMergeResumePreservesProgress/pause_after_iteration_3_with_checkpoint (30.63s)
```

Parameters:
 - <code>attempt=1</code>
 - <code>run=1</code>
 - <code>shard=14</code>
<details><summary>Help</summary>
<p>

See also: [How To Investigate a Go Test Failure \(internal\)](https://cockroachlabs.atlassian.net/l/c/HgfXfJgM)
</p>
</details>
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*TestDistributedMergeResumePreservesProgress.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/bazci/githubpost/issues)

</sub>

Jira issue: CRDB-58786

### PR DESCRIPTION
**Pull request by spilchen**
Previously, this test used hooks with a select on two cases to coordinate job pause behavior:
- <-iterationContinueCh to wait for the test to signal continuation.
- <-ctx.Done() to exit when the job was paused.

The test intended to close iterationContinueCh to unblock the hook once the job had paused. However, the channel was never actually closed, which could leave the test blocked indefinitely depending on the select outcome.

The fix is to explicitly close iterationContinueCh as originally intended. Removing the ctx.Done() case ensures the test no longer masks this bug and instead relies solely on the correct signaling mechanism.

Resolves: #161311
Epic: CRDB-48845
Release note: none

### CODE REVIEW

File: pkg/sql/indexbackfiller_test.go [hunk 1]
```diff
@@ -1605,7 +1595,16 @@ func TestDistributedMergeResumePreservesProgress(t *testing.T) {
 					waitForCheckpointPersisted(t, ctx, db, jobID, nil)
 				}
 
-				pauseAndResumeJob()
+				// Pause the job while it's blocked in the hook.
+				sqlDB.Exec(t, `PAUSE JOB $1`, jobID)
+				ensureJobState("paused")
+
+				// Unblock the hook so it can exit cleanly.
+				close(state.iterationContinueCh)
```
Comment (rafiss) [inline pkg/sql/indexbackfiller_test.go:1620]: if the test fails due to an error in one of the lines before this, then this channel will never get closed. i think that could lead to the `AfterDistributedMergeIteration` goroutine being deadlocked, and the TestServer will timeout while shutting down.

i think we can address this issue by making sure the `close` is executed via `defer`

Comment (spilchen) [reply pkg/sql/indexbackfiller_test.go:1620]: Ah good catch. I added a defer to handle this.

**Review by spilchen — COMMENTED** [review]
> @spilchen made 1 comment.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/161513)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @rafiss and @spilchen).

**Review by rafiss — APPROVED** [review]
lgtm!

**Comment by spilchen** [comment]
TFTR!

bors r+
