### PR TITLE
sql: fix swallowing of errors in planVisitor

### LINKED ISSUE #12850: benchmarks: panic: attempting to move SQL txn to state NoTxn inconsistent with KV txn state: PENDING
Looks like BenchmarkBank2_Cockroach-16 produces a panic in the nightly benchmark tests. From `sql.test.stderr` in https://teamcity.cockroachdb.com/viewLog.html?buildId=114365&buildTypeId=Cockroach_BenchmarkTests&tab=artifacts:

```
panic: attempting to move SQL txn to state NoTxn inconsistent with KV txn state: PENDING (finalized: false) [recovered]
	panic: 
UPDATE bench.bank
  SET balance = CASE id WHEN $1 THEN balance-$3 WHEN $2 THEN balance+$3 END
  WHERE id IN ($1, $2) AND (SELECT balance >= $3 FROM bench.bank WHERE id = $1): attempting to move SQL txn to state NoTxn inconsistent with KV txn state: PENDING (finalized: false) [recovered]
	panic: 
UPDATE bench.bank
  SET balance = CASE id WHEN $1 THEN balance-$3 WHEN $2 THEN balance+$3 END
  WHERE id IN ($1, $2) AND (SELECT balance >= $3 FROM bench.bank WHERE id = $1): attempting to move SQL txn to state NoTxn inconsistent with KV txn state: PENDING (finalized: false)

goroutine 411743 [running]:
panic(0x189eee0, 0xc424781a50)
	/usr/local/go/src/runtime/panic.go:500 +0x1a1
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).Recover(0xc422b82000)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:185 +0x6e
panic(0x189eee0, 0xc424781a50)
	/usr/local/go/src/runtime/panic.go:458 +0x243
github.com/cockroachdb/cockroach/pkg/sql.(*Executor).ExecuteStatements.func1(0xc421009001, 0xae)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/executor.go:455 +0x149
panic(0x1857280, 0xc424781a30)
	/usr/local/go/src/runtime/panic.go:458 +0x243
github.com/cockroachdb/cockroach/pkg/sql.(*txnState).resetStateAndTxn(0xc421375668, 0x0)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/session.go:360 +0x3dc
github.com/cockroachdb/cockroach/pkg/sql.(*Executor).execRequest(0xc421d669a0, 0xc421375600, 0xc421009001, 0xae, 0x0, 0x0, 0x0, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/executor.go:689 +0xcf8
github.com/cockroachdb/cockroach/pkg/sql.(*Executor).ExecuteStatements(0xc421d669a0, 0xc421375600, 0xc421009001, 0xae, 0xc423d19410, 0x0, 0x0, 0x0, 0x632900)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/executor.go:461 +0x11f
github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*v3Conn).executeStatements(0xc421230c00, 0x7f1700249400, 0xc4251cdda0, 0xc421009001, 0xae, 0xc423d19410, 0x2b9fbc8, 0x0, 0x0, 0xc420f61000, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/pgwire/v3.go:792 +0x94
github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*v3Conn).handleExecute(0xc421230c00, 0x7f1700249400, 0xc4251cdda0, 0xc421230c28, 0x9, 0x0)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/pgwire/v3.go:778 +0x20a
github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*v3Conn).serve(0xc421230c00, 0x7f1700249400, 0xc4251cdda0, 0x5400, 0xc420ae82f8, 0x7f1700249400, 0xc42363e300, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/pgwire/v3.go:420 +0xc70
github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*Server).ServeConn(0xc420ae81c0, 0x7f1700249400, 0xc42363e300, 0x2686460, 0xc422f18000, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/pgwire/server.go:309 +0x999
github.com/cockroachdb/cockroach/pkg/server.(*Server).Start.func8.1(0x26873c0, 0xc4231604d0)
	/go/src/github.com/cockroachdb/cockroach/pkg/server/server.go:522 +0x106
github.com/cockroachdb/cockroach/pkg/util/netutil.(*Server).ServeWith.func1(0xc422b82000, 0xc4214c0060, 0x26873c0, 0xc4231604d0, 0xc42299a620)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/netutil/net.go:136 +0x95
created by github.com/cockroachdb/cockroach/pkg/util/netutil.(*Server).ServeWith
	/go/src/github.com/cockroachdb/cockroach/pkg/util/netutil/net.go:138 +0x277
```

### PR DESCRIPTION
**Pull request by andreimatei**
This reverts commit 6f0a1d902e064899c9117104afc5b6f03441a3eb.

Revert of revert. Original commit message:

sql: fix swallowing of errors in planVisitor

Before this patch, planVisitor.visit() used to make a copy of itself for
visiting the current node and recursing. That caused errors encountered
in this process to not be saved in the original visitor.err, and thus
not returned from walkPlan().  The only reason for this copy was so that
"attrs" were prepended with the node name; that can be achieved by
directly passing the current node name around.

Fixes #12850

The changes to TestRetryableErrorForWrongTxn were necessary because,
before this patch, the single query in that test was getting an id
before the subquery error was being returned (because subquery errors
were being returned late). With the patch, subquery errors are being
returned early, so the test moved to doing separate queries.

---
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/13124)

### CODE REVIEW

**Comment by andreimatei** [comment]
Radu, this is #13004. The only thing to review is `txn_restart_test.go`. I explained in the new commit msg why that needs to change :(.

**Comment by RaduBerinde** [comment]
:lgtm: The test is more clear like this anyway.

---

Review status: 0 of 3 files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/13124#-:-KbH4cUhQf7oLEEuRjaM:b-kuha06)*

File: pkg/sql/txn_restart_test.go [hunk 1]
```diff
@@ -1236,8 +1236,21 @@ INSERT INTO t.test (k, v) VALUES ('test_key', 'test_val');
...
+	// transaction than the one we initiate. We need call that function in a
+	// transaction that already has an id (so, it can't be the first query in the
+	// transaction), because the "wrong txn id" detection mechanism doesn't work
+	// when the txn doesn't have an id yet (see TODO in
+	// IsRetryableErrMeantForTxn).
+	_, err = tx.Exec(`INSERT INTO t.test (k, v) VALUES('a', 'b')`)
+	if err != nil {
+		t.Fatal(err)
+	}
+	_, err = tx.Exec(`SELECT CRDB_INTERNAL.FORCE_RETRY('500ms':::INTERVAL, $1)`, bogusTxnID)
```
Comment (tamird) [inline pkg/sql/txn_restart_test.go]: don't you need to commit or abort the txn at some point?

**Comment by andreimatei** [comment]
Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[pkg/sql/txn_restart_test.go, line 1253 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/13124#-KbH-C-k0ACWlDgKXqyU-r1-1253:-KbHCUiip_gZBj0yMZnb:b-zdqbna) ([raw file](https://github.com/cockroachdb/cockroach/blob/eafaae9c02608e6cfee938ff392cd66223874da1/pkg/sql/txn_restart_test.go#L1253)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

don't you need to commit or abort the txn at some point?
</blockquote></details>

Not particularly.  We're asserting that we're getting a non-retryable error, so this means the KV txn is rolled back and the sql txn is left in an "ABORTED" state.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/13124)*
