### PR TITLE
changefeedccl: add envelope type to encoder benchmarks

### LINKED ISSUE #151301: pkg/ccl/changefeedccl: BenchmarkEncoders failed
pkg/ccl/changefeedccl.BenchmarkEncoders [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachprodMicrobenchmarkWeeklyWip/20289400?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachprodMicrobenchmarkWeeklyWip/20289400?buildTab=artifacts#./artifacts/microbench/experiment) on master @ [ca0d4076c381609d6487040141c87e36a68b211f](https://github.com/cockroachdb/cockroach/commits/ca0d4076c381609d6487040141c87e36a68b211f):

```
BenchmarkEncoders/json/encodeValue/2cols/envelope=row/diff=false
BenchmarkEncoders/json/encodeValue/2cols/envelope=row/diff=false-32         	  261714	      4451 ns/op	    1210 B/op	      36 allocs/op
BenchmarkEncoders/json/encodeValue/2cols/envelope=row/diff=true
BenchmarkEncoders/json/encodeValue/2cols/envelope=row/diff=true-32          	  264046	      4420 ns/op	    1210 B/op	      36 allocs/op
BenchmarkEncoders/json/encodeValue/2cols/envelope=wrapped/diff=false
BenchmarkEncoders/json/encodeValue/2cols/envelope=wrapped/diff=false-32     	  220820	      5121 ns/op	    1571 B/op	      45 allocs/op
BenchmarkEncoders/json/encodeValue/2cols/envelope=wrapped/diff=true
BenchmarkEncoders/json/encodeValue/2cols/envelope=wrapped/diff=true-32      	  130863	      8595 ns/op	    2631 B/op	      75 allocs/op
    encoder_test.go:1020: column types: [refcursor int2 tuple{bpchar, time, float} int2 tuple{bpchar, time, float} time pg_lsn uuid bytes uuid tuple{bpchar, bpchar, refcursor} tsvector int bytes jsonb tuple{time, decimal, timestamp, float, int2vector}], keys: [refcursor int2 tuple{bpchar, time, float}]
BenchmarkEncoders/json/encodeKey/3cols
    encoder_test.go:982: unknown envelope type 
--- FAIL: BenchmarkEncoders/json/encodeKey/3cols
BenchmarkEncoders/json/encodeValue/3cols/envelope=row/diff=false
BenchmarkEncoders/json/encodeValue/3cols/envelope=row/diff=false-32         	   94213	     12077 ns/op	    3242 B/op	      98 allocs/op
BenchmarkEncoders/json/encodeValue/3cols/envelope=row/diff=true
BenchmarkEncoders/json/encodeValue/3cols/envelope=row/diff=true-32          	   93358	     12106 ns/op	    3242 B/op	      98 allocs/op
BenchmarkEncoders/json/encodeValue/3cols/envelope=wrapped/diff=false
BenchmarkEncoders/json/encodeValue/3cols/envelope=wrapped/diff=false-32     	   78459	     14331 ns/op	    3983 B/op	     121 allocs/op
BenchmarkEncoders/json/encodeValue/3cols/envelope=wrapped/diff=true
BenchmarkEncoders/json/encodeValue/3cols/envelope=wrapped/diff=true-32      	   46165	     25188 ns/op	    7042 B/op	     214 allocs/op
    encoder_test.go:1020: column types: [refcursor int2 tuple{bpchar, time, float} time int2 tuple{bpchar, time, float} time pg_lsn uuid bytes uuid tuple{bpchar, bpchar, refcursor} tsvector int bytes jsonb tuple{time, decimal, timestamp, float, int2vector} date tsvector bool int jsonb date tsquery pg_lsn time name tuple{bit, int2} string interval decimal tsvector], keys: [refcursor int2 tuple{bpchar, time, float} time]
BenchmarkEncoders/json/encodeKey/4cols
    encoder_test.go:982: unknown envelope type 
--- FAIL: BenchmarkEncoders/json/encodeKey/4cols
BenchmarkEncoders/json/encodeValue/4cols/envelope=row/diff=false
BenchmarkEncoders/json/encodeValue/4cols/envelope=row/diff=false-32         	   50930	     22671 ns/op	    5323 B/op	     162 allocs/op
BenchmarkEncoders/json/encodeValue/4cols/envelope=row/diff=true
BenchmarkEncoders/json/encodeValue/4cols/envelope=row/diff=true-32          	   50960	     21935 ns/op	    5323 B/op	     162 allocs/op
BenchmarkEncoders/json/encodeValue/4cols/envelope=wrapped/diff=false
BenchmarkEncoders/json/encodeValue/4cols/envelope=wrapped/diff=false-32     	   44356	     25238 ns/op	    6149 B/op	     186 allocs/op
BenchmarkEncoders/json/encodeValue/4cols/envelope=wrapped/diff=true
BenchmarkEncoders/json/encodeValue/4cols/envelope=wrapped/diff=true-32      	   27000	     42938 ns/op	   11355 B/op	     342 allocs/op
--- FAIL: BenchmarkEncoders/json
BenchmarkEncoders/csv
    encoder_test.go:1020: column types: [refcursor int2 tuple{bpchar, time, float} time], keys: [refcursor]
BenchmarkEncoders/csv/encodeValue/1cols/envelope=row/diff=false
BenchmarkEncoders/csv/encodeValue/1cols/envelope=row/diff=false-32          	  878407	      1178 ns/op	      13 B/op	       1 allocs/op
    encoder_test.go:1020: column types: [refcursor int2 int2 tuple{bpchar, time, float} time pg_lsn uuid bytes], keys: [refcursor int2]
BenchmarkEncoders/csv/encodeValue/2cols/envelope=row/diff=false
BenchmarkEncoders/csv/encodeValue/2cols/envelope=row/diff=false-32          	  526173	      2188 ns/op	      45 B/op	       5 allocs/op
    encoder_test.go:1020: column types: [refcursor int2 tuple{bpchar, time, float} int2 tuple{bpchar, time, float} time pg_lsn uuid bytes uuid tuple{bpchar, bpchar, refcursor} tsvector int bytes jsonb tuple{time, decimal, timestamp, float, int2vector}], keys: [refcursor int2 tuple{bpchar, time, float}]
BenchmarkEncoders/csv/encodeValue/3cols/envelope=row/diff=false
BenchmarkEncoders/csv/encodeValue/3cols/envelope=row/diff=false-32          	  126170	      9739 ns/op	     692 B/op	      25 allocs/op
    encoder_test.go:1020: column types: [refcursor int2 tuple{bpchar, time, float} time int2 tuple{bpchar, time, float} time pg_lsn uuid bytes uuid tuple{bpchar, bpchar, refcursor} tsvector int bytes jsonb tuple{time, decimal, timestamp, float, int2vector} date tsvector bool int jsonb date tsquery pg_lsn time name tuple{bit, int2} string interval decimal tsvector], keys: [refcursor int2 tuple{bpchar, time, float} time]
BenchmarkEncoders/csv/encodeValue/4cols/envelope=row/diff=false
BenchmarkEncoders/csv/encodeValue/4cols/envelope=row/diff=false-32          	   56528	     21029 ns/op	    1715 B/op	      66 allocs/op
--- FAIL: BenchmarkEncoders
FAIL

I250803 23:38:47.457420 1 (gostd) rand.go:268  [-] 1  random seed: -667270878070677090
```
<details><summary>Help</summary>
<p>

See also: [How To Investigate a Go Test Failure \(internal\)](https://cockroachlabs.atlassian.net/l/c/HgfXfJgM)
</p>
</details>
/cc @cockroachdb/cdc
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*BenchmarkEncoders.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/bazci/githubpost/issues)

</sub>

Jira issue: CRDB-53202

### PR DESCRIPTION
**Pull request by rharding6373**
Previously some tests in BenchmarkEncoders did not pass through an envelope type, which caused the json encoder to fail. This PR adds an envelope type based on the test case. It also adds the envelope type to the benchmark name, which should be fine since this benchmark has not worked in awhile.

Epic: none
Fixes: #151301

Release note: none

### CODE REVIEW

**Review by log-head — APPROVED** [review]
lgtm!

**Comment by rharding6373** [comment]
TFTR!

bors r=log-head

**Review by herkolategan — APPROVED** [review]
Thanks for fixing!

File: pkg/ccl/changefeedccl/encoder_test.go [hunk 1]
```diff
@@ -1029,12 +1029,15 @@ func BenchmarkEncoders(b *testing.B) {
 				b.Logf("column types: %v, keys: %v", colTypes, colTypes[:numKeyCols])
 
 				if tc.benchEncodeKey {
-					b.Run(fmt.Sprintf("encodeKey/%dcols", numKeyCols),
-						func(b *testing.B) {
-							opts := changefeedbase.EncodingOptions{Format: tc.format}
-							bench(b, encodeKey, opts, updatedRows, prevRows)
-						},
-					)
+					for _, envelope := range tc.envelopes {
```
Comment (andyyang890) [inline pkg/ccl/changefeedccl/encoder_test.go]: optional nit: you could use `testutils.RunValues` instead of doing a for loop yourself

**Comment by rharding6373** [comment]
TFTR!

bors r+
