### PR TITLE
changefeed: fix race in cloudstorage sink

### LINKED ISSUE #130651: ccl/changefeedccl: TestCloudStorageSinkFastGzip failed
ccl/changefeedccl.TestCloudStorageSinkFastGzip [failed](https://tanzanite.cluster.engflow.com/invocations/default/100c734b-6d53-4560-b66d-8aabcc37a8e5?testReportRun=1&testReportShard=1&testReportAttempt=1#targets-Ly9wa2cvY2NsL2NoYW5nZWZlZWRjY2w6Y2hhbmdlZmVlZGNjbF90ZXN0) on release-24.1 @ [332094e3e6cbd2671a96b875e8cd4f8e8784d0f5](https://github.com/cockroachdb/cockroach/commits/332094e3e6cbd2671a96b875e8cd4f8e8784d0f5):

```
=== RUN   TestCloudStorageSinkFastGzip
    test_log_scope.go:170: test logs captured to: outputs.zip/logTestCloudStorageSinkFastGzip1370509941
    test_log_scope.go:81: use -show-logs to present logs inline
=== RUN   TestCloudStorageSinkFastGzip/flush
==================
WARNING: DATA RACE
Read at 0x00c00383a350 by goroutine 61990:
  bytes.(*Buffer).Len()
      GOROOT/src/bytes/buffer.go:79 +0x2d3
  github.com/cockroachdb/cockroach/pkg/ccl/changefeedccl.(*cloudStorageSink).EmitRow()
      github.com/cockroachdb/cockroach/pkg/ccl/changefeedccl/sink_cloudstorage.go:590 +0x2a8
  github.com/cockroachdb/cockroach/pkg/ccl/changefeedccl.TestCloudStorageSinkFastGzip.func4()
      github.com/cockroachdb/cockroach/pkg/ccl/changefeedccl/sink_cloudstorage_test.go:902 +0x3de
  testing.tRunner()
      GOROOT/src/testing/testing.go:1689 +0x21e
  testing.(*T).Run.gowrap1()
      GOROOT/src/testing/testing.go:1742 +0x44

Previous write at 0x00c00383a350 by goroutine 61992:
  bytes.(*Buffer).tryGrowByReslice()
      GOROOT/src/bytes/buffer.go:117 +0xa8
  bytes.(*Buffer).Write()
      GOROOT/src/bytes/buffer.go:177 +0xbc
  github.com/klauspost/pgzip.(*Writer).Write.func1()
      github.com/klauspost/pgzip/external/com_github_klauspost_pgzip/gzip.go:374 +0x12d

Goroutine 61990 (running) created at:
  testing.(*T).Run()
      GOROOT/src/testing/testing.go:1742 +0x825
  github.com/cockroachdb/cockroach/pkg/ccl/changefeedccl.TestCloudStorageSinkFastGzip()
      github.com/cockroachdb/cockroach/pkg/ccl/changefeedccl/sink_cloudstorage_test.go:888 +0x90c
  testing.tRunner()
      GOROOT/src/testing/testing.go:1689 +0x21e
  testing.(*T).Run.gowrap1()
      GOROOT/src/testing/testing.go:1742 +0x44

Goroutine 61992 (running) created at:
  github.com/klauspost/pgzip.(*Writer).Write()
      github.com/klauspost/pgzip/external/com_github_klauspost_pgzip/gzip.go:360 +0x66a
  github.com/cockroachdb/cockroach/pkg/ccl/changefeedccl.(*cloudStorageSinkFile).Write()
      github.com/cockroachdb/cockroach/pkg/ccl/changefeedccl/sink_cloudstorage.go:107 +0xc9
  github.com/cockroachdb/cockroach/pkg/ccl/changefeedccl.(*cloudStorageSink).EmitRow()
      github.com/cockroachdb/cockroach/pkg/ccl/changefeedccl/sink_cloudstorage.go:582 +0x20d
  github.com/cockroachdb/cockroach/pkg/ccl/changefeedccl.TestCloudStorageSinkFastGzip.func4()
      github.com/cockroachdb/cockroach/pkg/ccl/changefeedccl/sink_cloudstorage_test.go:902 +0x3de
  testing.tRunner()
      GOROOT/src/testing/testing.go:1689 +0x21e
  testing.(*T).Run.gowrap1()
      GOROOT/src/testing/testing.go:1742 +0x44
==================
```

Parameters:
 - <code>attempt=1</code>
 - <code>race=true</code>
 - <code>run=1</code>
 - <code>shard=1</code>
<details><summary>Help</summary>
<p>

See also: [How To Investigate a Go Test Failure \(internal\)](https://cockroachlabs.atlassian.net/l/c/HgfXfJgM)
</p>
</details>
/cc @cockroachdb/cdc
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*TestCloudStorageSinkFastGzip.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/bazci/githubpost/issues)
</sub>

Jira issue: CRDB-42163

### LINKED ISSUE #130656: ccl/changefeedccl: Data race in fast gzip and zstd
ccl/changefeedccl.TestCloudStorageSinkFastGzip [failed](https://tanzanite.cluster.engflow.com/invocations/default/5b48ab88-1861-40bb-9ebf-2ea12732b6eb?testReportRun=1&testReportShard=6&testReportAttempt=1#targets-Ly9wa2cvY2NsL2NoYW5nZWZlZWRjY2w6Y2hhbmdlZmVlZGNjbF90ZXN0) on master @ [66ff4329d380562ec95466ba108b72be721ff6c9](https://github.com/cockroachdb/cockroach/commits/66ff4329d380562ec95466ba108b72be721ff6c9):

```
=== RUN   TestCloudStorageSinkFastGzip
    test_log_scope.go:170: test logs captured to: outputs.zip/logTestCloudStorageSinkFastGzip3133702345
    test_log_scope.go:81: use -show-logs to present logs inline
=== RUN   TestCloudStorageSinkFastGzip/flush
==================
WARNING: DATA RACE
Write at 0x00c0074b4f50 by goroutine 79744:
  bytes.(*Buffer).tryGrowByReslice()
      GOROOT/src/bytes/buffer.go:117 +0xa8
  bytes.(*Buffer).Write()
      GOROOT/src/bytes/buffer.go:177 +0xbc
  github.com/klauspost/pgzip.(*Writer).Write.func1()
      github.com/klauspost/pgzip/external/com_github_klauspost_pgzip/gzip.go:374 +0x12d

Previous read at 0x00c0074b4f50 by goroutine 79742:
  bytes.(*Buffer).Len()
      GOROOT/src/bytes/buffer.go:79 +0x2d3
  github.com/cockroachdb/cockroach/pkg/ccl/changefeedccl.(*cloudStorageSink).EmitRow()
      github.com/cockroachdb/cockroach/pkg/ccl/changefeedccl/sink_cloudstorage.go:590 +0x2a8
  github.com/cockroachdb/cockroach/pkg/ccl/changefeedccl.TestCloudStorageSinkFastGzip.func4()
      github.com/cockroachdb/cockroach/pkg/ccl/changefeedccl/sink_cloudstorage_test.go:902 +0x3de
  testing.tRunner()
      GOROOT/src/testing/testing.go:1689 +0x21e
  testing.(*T).Run.gowrap1()
      GOROOT/src/testing/testing.go:1742 +0x44

Goroutine 79744 (running) created at:
  github.com/klauspost/pgzip.(*Writer).Write()
      github.com/klauspost/pgzip/external/com_github_klauspost_pgzip/gzip.go:360 +0x66a
  github.com/cockroachdb/cockroach/pkg/ccl/changefeedccl.(*cloudStorageSinkFile).Write()
      github.com/cockroachdb/cockroach/pkg/ccl/changefeedccl/sink_cloudstorage.go:107 +0xc9
  github.com/cockroachdb/cockroach/pkg/ccl/changefeedccl.(*cloudStorageSink).EmitRow()
      github.com/cockroachdb/cockroach/pkg/ccl/changefeedccl/sink_cloudstorage.go:582 +0x20d
  github.com/cockroachdb/cockroach/pkg/ccl/changefeedccl.TestCloudStorageSinkFastGzip.func4()
      github.com/cockroachdb/cockroach/pkg/ccl/changefeedccl/sink_cloudstorage_test.go:902 +0x3de
  testing.tRunner()
      GOROOT/src/testing/testing.go:1689 +0x21e
  testing.(*T).Run.gowrap1()
      GOROOT/src/testing/testing.go:1742 +0x44

Goroutine 79742 (running) created at:
  testing.(*T).Run()
      GOROOT/src/testing/testing.go:1742 +0x825
  github.com/cockroachdb/cockroach/pkg/ccl/changefeedccl.TestCloudStorageSinkFastGzip()
      github.com/cockroachdb/cockroach/pkg/ccl/changefeedccl/sink_cloudstorage_test.go:888 +0x90c
  testing.tRunner()
      GOROOT/src/testing/testing.go:1689 +0x21e
  testing.(*T).Run.gowrap1()
      GOROOT/src/testing/testing.go:1742 +0x44
==================
```

Parameters:
 - <code>attempt=1</code>
 - <code>race=true</code>
 - <code>run=1</code>
 - <code>shard=6</code>
<details><summary>Help</summary>
<p>

See also: [How To Investigate a Go Test Failure \(internal\)](https://cockroachlabs.atlassian.net/l/c/HgfXfJgM)
</p>
</details>
<details><summary>Same failure on other branches</summary>
<p>

- #130652 ccl/changefeedccl: TestCloudStorageSinkFastGzip failed [A-cdc C-test-failure O-robot T-cdc X-duplicate branch-release-24.2 release-blocker]
- #130651 ccl/changefeedccl: TestCloudStorageSinkFastGzip failed [A-cdc C-test-failure O-robot T-cdc branch-release-24.1 release-blocker]
</p>
</details>
/cc @cockroachdb/cdc
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*TestCloudStorageSinkFastGzip.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/bazci/githubpost/issues)
</sub>

Jira issue: CRDB-42167

### PR DESCRIPTION
**Pull request by asg0451**
When using zstd or "fast" gzip compression, the
cloudstorage sink was susceptible to a data race
on its buffered data. This was due to unexpected
asynchronousness in the compression writers.

Fixes: #130656
Fixes: #130651

Release note (bug fix): Fix a data race in the cloudstorage sink.

### CODE REVIEW

File: pkg/ccl/changefeedccl/sink_cloudstorage.go [hunk 1]
```diff
@@ -102,9 +107,19 @@ var _ io.Writer = &cloudStorageSinkFile{}
 func (f *cloudStorageSinkFile) Write(p []byte) (int, error) {
 	f.rawSize += len(p)
 	if f.codec != nil {
-		return f.codec.Write(p)
+		n, err := f.codec.Write(p) // WRITE
```
Comment (rharding6373) [inline pkg/ccl/changefeedccl/sink_cloudstorage.go:110]: nit: left a debugging comment

**Review by rharding6373 — APPROVED** [review]
LGTM, nice fix! Only a couple nits

File: pkg/ccl/changefeedccl/sink_cloudstorage.go [hunk 2]
```diff
@@ -68,11 +69,15 @@ func cloudStorageFormatTime(ts hlc.Timestamp) string {
...
-	buf           bytes.Buffer
+	created     time.Time
+	codec       io.WriteCloser
+	rawSize     int
+	numMessages int
+	buf         bytes.Buffer
+	// bufLen tracks the length of buf. Because some of the codecs write to the
+	// buffer asynchronously, we can't safely call `buf.Len()` while the codec
+	// is open.
+	bufLen        int64
```
Comment (andyyang890) [inline pkg/ccl/changefeedccl/sink_cloudstorage.go:80]: How awful do you think the performance would be if we wrapped the buffer with a mutex for just the pgzip writer case? I'm a little worried we might forget to update `bufLen` somewhere in the future.

**Review by andyyang890 — APPROVED** [review]

File: pkg/ccl/changefeedccl/changefeed_test.go [hunk 3]
```diff
@@ -11573,3 +11573,46 @@ func TestChangefeedMVCCTimestampWithQueries(t *testing.T) {
 
 	cdcTest(t, testFn)
 }
+
+func TestCloudstorageParallelCompression(t *testing.T) {
+	defer leaktest.AfterTest(t)()
+	defer log.Scope(t).Close(t)
+	skip.UnlessUnderRace(t)
```
Comment (andyyang890) [inline pkg/ccl/changefeedccl/changefeed_test.go:11580]: optional super nit: add a newline before this

**Review by andyyang890 — APPROVED** [review]

**Comment by asg0451** [comment]
bors r=andyyang890
