### PR TITLE
security: fix memory accounting issue in client certificate cache

### LINKED ISSUE #151040: security: incorrect memory accounting for client certificates
The client certificate cache is a simple utility cache which keeps track of the nearest certificate expiration times by user. It does this by reading in certificates as they are used, and then updating the gauge associated with the user so that our operators can alert on expiring certificates.

It has been identified that there is a memory accounting issue with this utility class, in that if we see the same certificate multiple times, we report that our cache is growing for each one. In reality however, though we may change the reference in our cache, the old value will be cleaned up, and memory should remain relatively low.

The problems that stem from this are as follows:
1. For those using client certificates for authentication, memory accounting will say that there's a leak (though there is no actual leak).
2. Should there be enough traffic to the cluster, SQL memory reporting will be skewed due to this misrepresentation, and the actual total usage will be unknown without some work.
3. If the system believes it has run out of memory, it will start rejecting normal traffic.

Jira issue: CRDB-53044

### PR DESCRIPTION
**Pull request by angles-n-daemons**
The client certificate cache is a simple utility cache which keeps track of the nearest certificate expiration times by user. It does this by reading in certificates as they are used, and then updating the gauge associated with the user so that our operators can alert on expiring certificates.

It has been identified that there is a memory accounting issue with this utility class, in that if we see the same certificate multiple times, we report that our cache is growing for each one. In reality however, though we may change the reference in our cache, the old value will be cleaned up, and memory should remain relatively low.

This PR both fixes the accounting bug, and adds a limit so that the client certificate cache can't negatively affect SQL operation.

Epic: none
Fixes: #151040
Release note: Fixes a memory accounting issue with the client certificate cache, where we were accidentally reporting multiple allocations for the same memory.

### CODE REVIEW

**Review by fqazi — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/151041#-:-OWQoUjH0wXrLg20Nb9l:bnfp4nl)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @kyle-a-wong)

___
*[`pkg/security/certificate_manager.go` line 199 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/151041#-OWQoWgpCjii-fwyz-ti:-OWQoWgpCjii-fwyz-tj:bozjb7p) ([raw file](https://github.com/cockroachdb/cockroach/blob/ac72175a7f0be5194448b803cc0fca207ba251da/pkg/security/certificate_manager.go#L199)):*
> ```Go
> }
> 
> const certExpirationMemLimit = 1 << 29 // 512MiB
> ```

Do we want this to be a cluster setting? In case it ever becomes a problem, which seems unlikely

**Review by dhartunian — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/151041)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @angles-n-daemons and @kyle-a-wong)

___
*[`pkg/security/clientcert/cert_expiry_cache_test.go` line 336 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/151041#-OWQnaEu0Ao7tYxzQu-_:-OWQnaEu0Ao7tYxzQu-a:bfr9sye) ([raw file](https://github.com/cockroachdb/cockroach/blob/ac72175a7f0be5194448b803cc0fca207ba251da/pkg/security/clientcert/cert_expiry_cache_test.go#L336)):*
> ```Go
> 		cache.Upsert(ctx, "user1", "serial1", 100)
> 		cache.Upsert(ctx, "user1", "serial1", 100)
> 		require.Equal(t, certInfoSize+(2*gaugeSize), account.Used())
> ```

Can you add a require check between every cache upsert? it should stay the same throughout right?

Do we already verify the `Shrink` behavior somewhe

**Review by angles-n-daemons — COMMENTED** [review]
tftr! ready for another look!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/151041#-:-OWR1sLW5U_KYiobIHCo:bx47plp)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @dhartunian, @fqazi, and @kyle-a-wong)

___
*[`pkg/security/certificate_manager.go` line 199 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/151041#-OWQoWgpCjii-fwyz-ti:-OWQwa0v2mu73xhednGa:b-s6ajgn) ([raw file](https://github.com/cockroachdb/cockroach/blob/ac72175a7f0be5194448b803cc0fca207ba251da/pkg/security/certificate_manager.go#L199)):*
<details><summary><i>Previously, fqazi (Faizan Qazi) wrote…</i></summary><blockquote>

Do we want this to be a cluster setting? In case it ever becomes a problem, which seems unlikely
</blockquote></details>

That's a good idea, yeah I'll change it now.
___
*[`pkg/security/clientcert/cert_expiry_cache_test.go` line 336 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/151041#-OWQnaEu0Ao7tYxzQu-_:-OWQwcyL1L4H_OaUKQWk:brpqjwq) ([raw file](https://github.com/cockroachdb/cockroach/blob/ac72175a7f0be5194448b803cc0fca207ba251da/pkg/security/clientcert/cert_expiry_cache_test.go#L336)):*
<details><summary><i>Previously, dhartunian (David Hartunian) wrote…</i></summary><blockquote>

Can you add a require check between every cache upsert? it should stay the same throughout right?

Do we already verify the `Shrink` behavior somewhe
</blockquote></details>

Good thought, added.

The two tests above this (Purge and Clear) test that the cache shrinks. I can add checks for the size of the cache before it shrinks too.

**Review by fqazi — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/151041#-:-OWR2cqB5N_ymDg5qQPu:bnfp4nl)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @dhartunian and @kyle-a-wong)

File: pkg/security/certificate_manager.go [hunk 1]
```diff
@@ -196,15 +198,24 @@ func (cm *CertificateManager) RegisterSignalHandler(
 	})
 }
 
+var CertCacheMemLimit = settings.RegisterIntSetting(
+	settings.SystemOnly,
```
Comment (kyle-a-wong) [inline pkg/security/certificate_manager.go]: This is causing panics. I think you want `SystemVisible`

Comment (angles-n-daemons) [reply pkg/security/certificate_manager.go]: Yeah, going to change this now.

Comment (yuzefovich) [reply pkg/security/certificate_manager.go]: Given that the certificate cache is a singleton for a SQL server, this probably should have been `ApplicationLevel` - in theory, every tenant could have a different limit. Was it a conscious decision to disallow tenants from modifying this setting?

**Review by yuzefovich — COMMENTED** [review]
Thanks for the fix! I saw a couple of nits, I'll send a patch.

> Reviewed 1 of 3 files at r1, 2 of 3 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/151041#-:-OWXgIGDDDNWlijHcopP:b13ol97)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (and 1 stale)

___
*[`pkg/security/certificate_manager.go` line 203 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/151041#-OWXfZ_Z1pwq_Y4vxp9G:-OWXfZ_Z1pwq_Y4vxp9H:b-7zvhm8) ([raw file](https://github.com/cockroachdb/cockroach/blob/3cf46921b657fb68bc6ea0454b4b704ca0716d9f/pkg/security/certificate_manager.go#L203)):*
> ```Go
> var CertCacheMemLimit = settings.RegisterIntSetting(
> 	settings.SystemVisible,
> 	"security.clienc_cert.cache_memory_limit",
> ```

nit: typo in "clienc". Also we should've marked this as `ByteSizeSetting` - we're missing a validation of non-negative integer (although negative or zero as a limit would mean "no limit").
