### PR TITLE
kvserver: wait for all streams to be connected

### LINKED ISSUE #138103: kv/kvserver: TestFlowControlRaftSnapshotV2 failed
kv/kvserver.TestFlowControlRaftSnapshotV2 [failed](https://mesolite.cluster.engflow.com/invocations/default/411f3270-ac0d-42ca-bfc5-c4d92022f3d6?testReportRun=1&testReportShard=23&testReportAttempt=1#targets-Ly9wa2cva3Yva3ZzZXJ2ZXI6a3ZzZXJ2ZXJfdGVzdA==) on master @ [13b35125a8626a1ea6f11f9d3654440e74e8055b](https://github.com/cockroachdb/cockroach/commits/13b35125a8626a1ea6f11f9d3654440e74e8055b):

```
=== RUN   TestFlowControlRaftSnapshotV2
    test_log_scope.go:165: test logs captured to: outputs.zip/logTestFlowControlRaftSnapshotV22841798680
    test_log_scope.go:76: use -show-logs to present logs inline
    flow_control_integration_test.go:3088: -- test log scope end --
test logs left over in: outputs.zip/logTestFlowControlRaftSnapshotV22841798680
--- FAIL: TestFlowControlRaftSnapshotV2 (40.49s)
=== RUN   TestFlowControlRaftSnapshotV2/v2_enabled_when_leader_level=2/kvadmission.flow_control.mode=apply_to_elastic
    datadriven.go:144: 
        /var/lib/engflow/worker/work/0/exec/bazel-out/k8-fastbuild/bin/pkg/kv/kvserver/kvserver_test_/kvserver_test.runfiles/com_github_cockroachdb_cockroach/pkg/kv/kvserver/testdata/flow_control_integration_v2/raft_snapshot_v2_encoding_apply_to_elastic:1:
         
        output didn't match expected:
        @@ -207,11 +207,10 @@
         
           range_id | store_id | total_tracked_tokens  
         -----------+----------+-----------------------
           75       | 1        | 0 B                   
           75       | 2        | 0 B                   
        -  75       | 3        | 0 B                   
           75       | 4        | 0 B                   
           75       | 5        | 0 B                   
         
         
         -- Another view of tokens, using /inspectz-backed vtables.
        --- FAIL: TestFlowControlRaftSnapshotV2/v2_enabled_when_leader_level=2/kvadmission.flow_control.mode=apply_to_elastic (8.58s)
=== RUN   TestFlowControlRaftSnapshotV2/v2_enabled_when_leader_level=2
    --- FAIL: TestFlowControlRaftSnapshotV2/v2_enabled_when_leader_level=2 (21.11s)
```

Parameters:
 - <code>attempt=1</code>
 - <code>run=1</code>
 - <code>shard=23</code>
<details><summary>Help</summary>
<p>

See also: [How To Investigate a Go Test Failure \(internal\)](https://cockroachlabs.atlassian.net/l/c/HgfXfJgM)
</p>
</details>
/cc @cockroachdb/kv-triage
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*TestFlowControlRaftSnapshotV2.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/bazci/githubpost/issues)

</sub>

Jira issue: CRDB-45893

### PR DESCRIPTION
**Pull request by pav-kv**
Previously, `waitForConnectedStreams` could return prematurely when one of the streams is in `StateProbe` and about to be closed. This commit ensures we wait for the streams to be connected / in `StateReplicate`.

Fixes #138103, #139229

### CODE REVIEW

File: pkg/kv/kvserver/kvflowcontrol/rac2/range_controller.go [hunk 1]
```diff
@@ -1631,6 +1631,7 @@ func (rc *rangeController) InspectRaftMuLocked(ctx context.Context) kvflowinspec
 			}
 			streams = append(streams, kvflowinspectpb.ConnectedStream{
 				Stream:                  rc.opts.SSTokenCounter.InspectStream(rs.stream),
+				Connected:               rs.sendStream.mu.connectedState == replicate,
```
Comment (pav-kv) [inline pkg/kv/kvserver/kvflowcontrol/rac2/range_controller.go:1634]: The alternative here is not returning `ConnectedStream` if `connectedState != replicate`. Then the proto wouldn't need to change, but there would be less of an observability.

Comment (kvoli) [reply pkg/kv/kvserver/kvflowcontrol/rac2/range_controller.go:1634]: Ack, but are you certain we can backport the proto change? 

See https://cockroachlabs.atlassian.net/wiki/spaces/ENG/pages/1043235321/Database+Backport+Patch+Policy#Backporting-new-functionality-(including-modifications-to-persisted-state-%26-cross-node-RPCs). 

This is used by SQL (potentially x-node?) to populate tables but should be fine since it is just an addition. See this and other V2 functions (the V1 ones could be removed).

https://github.com/cockroachdb/cockroach/blob/ab7abe100cc99b5dfbcf65ca84ff975ee823573d/pkg/sql/crdb_internal.go#L9274-L9279

My take is that this is fine and relatively low risk because we only use these tables in tests atm and don't have public debug guidance referencing them.

**Review by kvoli — COMMENTED** [review]
There are some test diffs due to the new proto field to resolve. Also wanted to check we've thought through the proto backport w.r.t mixed minor version clusters.

> Reviewed 3 of 4 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/141365#-:-OJ--jRy6NG07TfV_E-O:b7ie9ny)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @pav-kv and @sumeerbhola)

**Review by sumeerbhola — APPROVED** [review]
:lgtm: 

> Reviewed 4 of 4 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/141365#-:-OJ4AxjJ3o1QD55Kuvqd:bg7igkv)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @pav-kv)

**Comment by pav-kv** [comment]
> There are some test diffs due to the new proto field to resolve. Also wanted to check we've thought through the proto backport w.r.t mixed minor version clusters.

Done. I think backporting is fine. With this PR, the new field is only used in unit tests. Both old/new versions ignore it in other places, so there is no behaviour change.

**Comment by pav-kv** [comment]
bors r=sumeerbhola

**Comment by pav-kv** [comment]
bors cancel

**Comment by pav-kv** [comment]
bors r=sumeerbhola

**Review by kvoli — APPROVED** [review]
:lgtm:

> Reviewed 4 of 6 files at r4, 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/141365#-:-OJOf_uv60-YeKbDTb3m:bnfp4nl)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @pav-kv)

**Comment by pav-kv** [comment]
bors retry
