### PR TITLE
sql: provide more helpful error message when creating the wrong type …

### LINKED ISSUE #69589: sql: provide more helpful error message when creating the wrong type of index
When a user attempts to create a forward index on a datatype that does not support forward indexes, the error message is not very clear:

```
defaultdb> CREATE TABLE t (j JSON, INDEX ((j->'some_key')));
ERROR: index element j->'some_key' of type jsonb is not indexable
SQLSTATE: 42P16
```

To be more helpful, the error message could mention:

* That an inverted index can be created instead.
* A hint to the docs, like we do for inverted indexes (see below).

```
defaultdb> CREATE TABLE t (a STRING, INVERTED INDEX (a));
ERROR: column a of type string is not allowed as the last column in an inverted index
SQLSTATE: 0A000
HINT: see the documentation for more information about inverted indexes: https://www.cockroachlabs.com/docs/v21.2/inverted-indexes.html
```

### PR DESCRIPTION
**Pull request by neeral**
…of index

Previously, when a user attempts to create a forward index on a datatype that
does not support forward indexes, the error message is not very clear:

```
defaultdb> CREATE TABLE t (j JSON, INDEX ((j->'some_key')));
ERROR: index element j->'some_key' of type jsonb is not indexable
SQLSTATE: 42P16
```

To be more helpful, the error message could mention that an inverted index can
be created instead and include a hint to the docs.

The existing error message was not helpful and caused confusion to users.

This fixes #69589 

Release justification: Low risk fix.

Release note (sql change): The error message when creating the wrong type of index
was not clear and it is now more helpful.

### CODE REVIEW

**Comment by neeral** [comment]
cc: @mgartner PTAL
let me know any improvements and where to add tests.

File: pkg/sql/create_index.go [hunk 1]
```diff
@@ -423,6 +423,17 @@ func replaceExpressionElemsWithVirtualCols(
 			}
 
 			if !isInverted && !colinfo.ColumnTypeIsIndexable(typ) {
+				if colinfo.ColumnTypeIsInvertedIndexable(typ) {
+					return errors.WithHint(
+						pgerror.Newf(
+							pgcode.InvalidTableDefinition,
+							"index element %s of type %s is not indexable. an inverted index can be created instead",
```
Comment (postamar) [inline pkg/sql/create_index.go:430]: May I suggest `"index element %s of type %s is not indexable in a non-inverted index"`?

**Review by postamar — COMMENTED** [review]
Thanks for doing this, this change seems reasonable.

For testing I suggest adding a case to the [inverted_index](https://github.com/cockroachdb/cockroach/blob/master/pkg/sql/logictest/testdata/logic_test/inverted_index) logic test suite that will assert on the error message you're adding.

File: pkg/sql/create_index.go [hunk 2]
```diff
@@ -423,6 +423,17 @@ func replaceExpressionElemsWithVirtualCols(
...
+							elem.Expr.String(),
+							typ.Name(),
+						),
+						"see the documentation for more information about inverted indexes: "+docs.URL("inverted-indexes.html"),
```
Comment (mgartner) [inline pkg/sql/create_index.go:434]: You can update the hint to suggest an inverted index after following @postamar's suggestion above. Something like: `you may want to create an inverted index instead. See the documentation for inverted indexes: ...`

**Comment by mgartner** [comment]
Thanks for the contribution!

Could you reword your commit message to be clear what the change is, rather than stating what the change "could" be?

For example:

```diff
- To be more helpful, the error message could mention that an inverted index can
- be created instead and include a hint to the docs.

- The existing error message was not helpful and caused confusion to users.
+ The error message now suggests creating an inverted index.
```

Also: in order for the issue to be auto-closed when this PR is merged, you'll need to update the commit message:

```diff
- This fixes #69589
- Fixes #69589
```

**Review by neeral — COMMENTED** [review]
Thanks for the review comments @mgartner and @postamar. I've addressed your comments and added a logic test case. PTAL.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/69824#-:-MjJl4q27rpNIxPQzuvC:b-l6qeo4)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @postamar)

___
*[pkg/sql/create_index.go, line 430 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/69824#-MihMho0kaEs-_fMzhYx-r1-430:-MjJRCz22M2gVwhd9wJc:b32w0x) ([raw file](https://github.com/cockroachdb/cockroach/blob/8462f14a98bb56456d8e6844e2300cfc90a2cc25/pkg/sql/create_index.go#L430)):*
<details><summary><i>Previously, postamar (Marius Posta) wrote…</i></summary><blockquote>

May I suggest `"index element %s of type %s is not indexable in a non-inverted index"`?
</blockquote></details>

OK
___
*[pkg/sql/create_index.go, line 434 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/69824#-MihMho0kaEs-_fMzhYx-r1-434:-MjJRV216tc22eOqAYYr:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/8462f14a98bb56456d8e6844e2300cfc90a2cc25/pkg/sql/create_index.go#L434)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

You can update the hint to suggest an inverted index after following @postamar's suggestion above. Something like: `you may want to create an inverted index instead. See the documentation for inverted indexes: ...`
</blockquote></details>

Done.

**Comment by mgartner** [comment]
Thanks for making the changes. This looks good to me.

Looks like the build failed due to an unrelated flaky test. I'll re-run it and merge it when it passes.

**Review by mgartner — APPROVED** [review]

**Comment by mgartner** [comment]
Thanks again for the contribution!

bors r+

**Comment by neeral** [comment]
Thanks for your help in reviewing the PR, @mgartner
