### PR TITLE
*: update to lib/pq v1.10.2

### LINKED ISSUE #65320: lib/pq is incompatible with empty resultsets in v1.9.0+
Still working on a repro, but upgrading lib/pq to v1.9.0+ results in the following error:

```
root@127.0.0.1:26257/defaultdb> create table t();
CREATE TABLE

Time: 9ms total (execution 9ms / network 0ms)

root@127.0.0.1:26257/defaultdb> select * from t;
OK

Time: 13ms
*
* ERROR: a panic has occurred!
* runtime error: invalid memory address or nil pointer dereference
* (1) attached stack trace
*   -- stack trace:
*   | runtime.sigpanic
*   | 	/usr/local/opt/go@1.15/libexec/src/runtime/signal_unix.go:742
*   | github.com/lib/pq.(*rows).Close
*   | 	/Users/otan/go/src/github.com/cockroachdb/cockroach/vendor/github.com/lib/pq/conn.go:1466
*   | github.com/cockroachdb/cockroach/pkg/cli.(*sqlRows).Close
*   | 	/Users/otan/go/src/github.com/cockroachdb/cockroach/pkg/cli/sql_util.go:589
*   | github.com/cockroachdb/cockroach/pkg/cli.(*sqlConn).getLastQueryStatistics.func1
*   | 	/Users/otan/go/src/github.com/cockroachdb/cockroach/pkg/cli/sql_util.go:392
*   | runtime.gopanic
*   | 	/usr/local/opt/go@1.15/libexec/src/runtime/panic.go:969
*   | runtime.panicmem
*   | 	/usr/local/opt/go@1.15/libexec/src/runtime/panic.go:212
*   | runtime.sigpanic
*   | 	/usr/local/opt/go@1.15/libexec/src/runtime/signal_unix.go:742
*   | github.com/lib/pq.(*rows).Columns
*   | 	/Users/otan/go/src/github.com/cockroachdb/cockroach/vendor/github.com/lib/pq/conn.go:1488
*   | github.com/cockroachdb/cockroach/pkg/cli.(*sqlRows).Columns
*   | 	/Users/otan/go/src/github.com/cockroachdb/cockroach/pkg/cli/sql_util.go:576
*   | github.com/cockroachdb/cockroach/pkg/cli.(*sqlConn).getLastQueryStatistics
*   | 	/Users/otan/go/src/github.com/cockroachdb/cockroach/pkg/cli/sql_util.go:396
*   | github.com/cockroachdb/cockroach/pkg/cli.maybeShowTimes
*   | 	/Users/otan/go/src/github.com/cockroachdb/cockroach/pkg/cli/sql_util.go:1014
*   | github.com/cockroachdb/cockroach/pkg/cli.runQueryAndFormatResults
*   | 	/Users/otan/go/src/github.com/cockroachdb/cockroach/pkg/cli/sql_util.go:940
*   | github.com/cockroachdb/cockroach/pkg/cli.(*cliState).doRunStatements
*   | 	/Users/otan/go/src/github.com/cockroachdb/cockroach/pkg/cli/sql.go:1376
*   | github.com/cockroachdb/cockroach/pkg/cli.(*cliState).doRunShell
*   | 	/Users/otan/go/src/github.com/cockroachdb/cockroach/pkg/cli/sql.go:1497
*   | github.com/cockroachdb/cockroach/pkg/cli.runInteractive
*   | 	/Users/otan/go/src/github.com/cockroachdb/cockroach/pkg/cli/sql.go:1445
*   | github.com/cockroachdb/cockroach/pkg/cli.runClient
*   | 	/Users/otan/go/src/github.com/cockroachdb/cockroach/pkg/cli/sql.go:1710
*   | github.com/cockroachdb/cockroach/pkg/cli.runDemo
*   | 	/Users/otan/go/src/github.com/cockroachdb/cockroach/pkg/cli/demo.go:386
*   | github.com/cockroachdb/cockroach/pkg/cli.init.5.func1
*   | 	/Users/otan/go/src/github.com/cockroachdb/cockroach/pkg/cli/demo.go:55
*   | github.com/cockroachdb/cockroach/pkg/cli.MaybeDecorateGRPCError.func1
*   | 	/Users/otan/go/src/github.com/cockroachdb/cockroach/pkg/cli/error.go:194
*   | github.com/spf13/cobra.(*Command).execute
*
```

Furthermore, various test breaks, e.g. `go test ./pkg/sql -run TestCleanupSchemaObjects` (see #65319)

This fixes it, which is a revert of lib/pq#1004, fixes the bug.

```
@@ -691,11 +693,8 @@ func (cn *conn) simpleQuery(q string) (res *rows, err error) {
                        // Set the result and tag to the last command complete if there wasn't a
                        // query already run. Although queries usually return from here and cede
                        // control to Next, a query with zero results does not.
-                       if t == 'C' {
+                       if t == 'C' && res.colNames == nil {
                                res.result, res.tag = cn.parseComplete(r.string())
-                               if res.colNames != nil {
-                                       return
-                               }
                        }
```

I'm guessing it's pgwire sending the wrong thing, but could be lib/pq being wrong. Either way, worth an investigation.

### PR DESCRIPTION
**Pull request by rafiss**
Fixes https://github.com/cockroachdb/cockroach/issues/65320

This gets us off the cockroachdb/pq fork.

This revealed a bug in some of the tests and `debug` code: they were not calling
rows.Close() after querying the database. The new version of
lib/pq is more strict about requiring this.

Additionally, logic tests were not checking `NextResultSet()`, which is
a bug if the test executes multiple queries at once.

Release note: none

### CODE REVIEW

**Comment by otan** [comment]
some interesting test failures

File: pkg/cli/doctor.go [hunk 1]
```diff
@@ -201,6 +201,11 @@ SELECT id, descriptor, NULL AS mod_time_logical
 FROM system.descriptor ORDER BY id`
 		}
 	}
+	if err == nil {
```
Comment (knz) [inline pkg/cli/doctor.go:204]: Here and below you can use `errors.CombineErrors` and simplify this

**Review by knz — APPROVED** [review]
LGTM with nit

File: pkg/cli/doctor.go (hunk 1 above)
Comment (rafiss) [reply pkg/cli/doctor.go:204]: good call. actually, the error checking was wrong before, since it didn't do anything if `err` was non-nil and also not an `UndefinedColumn` error

**Comment by rafiss** [comment]
bors r=knz

File: pkg/cli/doctor.go (hunk 1 above)
Comment (rafiss) [reply pkg/cli/doctor.go]: well, actually CombineErrors is tricky since calling `rows.Close()` will throw a NPE if `err` is non-nil. so we need to check if `err` is nil separately anyway.

i changed it a bit to use `QueryRow` instead, which will take care of closing rows if needed.

there was also a bug because the "column exists" check (`SELECT crdb_internal_mvcc_timestamp`) would always fail -- it needs a FROM clause.

Comment (knz) [reply pkg/cli/doctor.go]: sgtm

**Comment by rafiss** [comment]
tftr!

bors r=knz
