### PR TITLE
sql/importer: unskip TestCSVImportCanBeResumed

### LINKED ISSUE #91828: sql/importer: flake in TestCSVImportCanBeResumed [ingestKVs hangs with BulkAdderFlushesEveryBatch]
Found here: https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_BazelExtendedCi/7502297?showRootCauses=false&expandBuildChangesSection=true&expandBuildProblemsSection=true&expandBuildTestsSection=true

```
Failed
=== RUN   TestCSVImportCanBeResumed
    test_log_scope.go:161: test logs captured to: /artifacts/tmp/_tmp/375538c3f706ce59f4e97af17139af4f/logTestCSVImportCanBeResumed2019049709
    test_log_scope.go:79: use -show-logs to present logs inline
    import_processor_test.go:739: Resume pos: 10
    import_processor_test.go:745: not enough memory available to create a BulkAdder: root: memory budget exceeded: 33554432 bytes requested, 101984256 currently allocated, 134217728 bytes in budget
    panic.go:522: -- test log scope end --
test logs left over in: /artifacts/tmp/_tmp/375538c3f706ce59f4e97af17139af4f/logTestCSVImportCanBeResumed2019049709
--- FAIL: TestCSVImportCanBeResumed (1.16s)
```

cc @rafiss for triage

Jira issue: CRDB-21446

### PR DESCRIPTION
**Pull request by stevendanna**
This unskips the test and adds a memory limit. The test completed 1500+ runs under stress. I believe #93782 resolved the main source of flakiness here.

Fixes #91828

Release note: None

### CODE REVIEW

**Review by rafiss — APPROVED** [review]
thanks!

File: pkg/sql/importer/import_processor_test.go [hunk 1]
```diff
@@ -668,6 +664,7 @@ func TestCSVImportCanBeResumed(t *testing.T) {
 					BulkAdderFlushesEveryBatch: true,
 				},
 			},
+			SQLMemoryPoolSize: 1 << 30, // 1 GiB
```
Comment (adityamaru) [inline pkg/sql/importer/import_processor_test.go:667]: This LGTM, but I think in other places we've dropped how much `kv.bulk_ingest.pk_buffer_size` asks for to begin with to prevent the memory monitor from shouting at us.

Comment (stevendanna) [reply pkg/sql/importer/import_processor_test.go]: Done

**Comment by stevendanna** [comment]
Test failures look unrelated:

bors r=rafiss
