### PR TITLE
roachtest: update tpce tests with new connection options

### LINKED ISSUE #117567: roachtest: tpce/c=5000/nodes=3 failed
roachtest.tpce/c=5000/nodes=3 [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/13461006?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/13461006?buildTab=artifacts#/tpce/c=5000/nodes=3) on release-23.1 @ [5a4e1d0bbf4b0a153b4f38ed19553d8d82aa09b7](https://github.com/cockroachdb/cockroach/commits/5a4e1d0bbf4b0a153b4f38ed19553d8d82aa09b7):

```
(cluster.go:2138).Run: full command output in run_191137.534274812_n4_sudo-docker-run-cock.log: COMMAND_PROBLEM: exit status 1
(monitor.go:153).Wait: monitor failure: monitor user task failed: t.Fatal() was called
test artifacts and logs in: /artifacts/tpce/c=5000/nodes=3/run_1
```
<p>Parameters: <code>ROACHTEST_arch=amd64</code>
, <code>ROACHTEST_cloud=gce</code>
, <code>ROACHTEST_cpu=4</code>
, <code>ROACHTEST_encrypted=false</code>
, <code>ROACHTEST_fs=ext4</code>
, <code>ROACHTEST_localSSD=true</code>
, <code>ROACHTEST_metamorphicBuild=false</code>
, <code>ROACHTEST_ssd=1</code>
</p>
<details><summary>Help</summary>
<p>

See: [roachtest README](https://github.com/cockroachdb/cockroach/blob/master/pkg/cmd/roachtest/README.md)

See: [How To Investigate \(internal\)](https://cockroachlabs.atlassian.net/l/c/SSSBr8c7)

See: [Grafana](https://go.crdb.dev/roachtest-grafana/teamcity-13461006/tpce-c-5000-nodes-3/1704827456864/1704827642222)

</p>
</details>
/cc @cockroachdb/test-eng
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*tpce/c=5000/nodes=3.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)
</sub>

Jira issue: CRDB-35250

### PR DESCRIPTION
**Pull request by DarrylWong**
The tpc-e driver has been updated to accept options for a fixture bucket, port, username and password. This change adds those options accordingly to the tpce tests.

Previously, tpce hardcoded the sql port as 26257. Now that tpce can accept a port option, we can instead discover the port and pass it.

This change also includes a new SQLPort function that returns the sql port of the given nodes, as well as fixes miscellaneous function signatures to correctly say nodes instead of node.

Release note: None
Epic: None
Fixes: #117567

### CODE REVIEW

**Comment by DarrylWong** [comment]
[restore/tpce and tpce/c=5000](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/13615091?buildTab=tests&status=passed) tests passing

File: pkg/roachprod/roachprod.go [hunk 1]
```diff
@@ -1074,6 +1074,28 @@ func AdminURL(
 	return urlGenerator(ctx, c, l, c.TargetNodes(), uConfig)
 }
 
+// SQLPorts finds the SQL ports for a cluster.
```
Comment (herkolategan) [inline pkg/roachprod/roachprod.go:1077]: Super Nit: This only supports the host/storage cluster at this point, and might be beneficial if it supports passing virtual cluster info in the future. Not required for this PR though.

**Review by herkolategan — APPROVED** [review]
Nice work!

File: pkg/roachprod/roachprod.go (hunk 1 above)
Comment (DarrylWong) [reply pkg/roachprod/roachprod.go:1077]: It's now passing the `tenant` name and the `sqlinstance` down to `DiscoverService`. made the change for `AdminUIPorts` too.

Nothing right now is actually passing a non `""` or `0` value for those, but I played around with it in the `multitenant/distsql` tests and it seemed like it worked to me. It was returning different port values depending on if I passed `tenantName` or not.

File: pkg/cmd/roachtest/tests/tpce.go [hunk 2]
```diff
@@ -72,10 +97,16 @@ func initTPCESpec(
...
+	ports, err := c.SQLPorts(ctx, l, roachNodes)
+	if err != nil {
+		return nil, err
+	}
+	port := fmt.Sprintf("--pg-port=%d", ports[0])
 	return &tpceSpec{
 		loadNode:         loadNode,
 		roachNodes:       roachNodes,
 		roachNodeIPFlags: roachNodeIPFlags,
+		port:             port,
```
[the remark this answers is not in the document]
Comment (DarrylWong) [reply pkg/cmd/roachtest/tests/tpce.go]: Done.

**Review by herkolategan — COMMENTED** [review]
Great thanks! I think I had some reason for leaving `NodePort` alone during the services refactor initially, but if it's possible now then it might be worth it.

At this point `NodePort` almost starts to seem redundant since it just calls one of the discover methods? Don't want to add more out of scope work to this PR, so we could aim to replace this across roachtest/roachprod more gracefully in another PR.

If you haven't already might be worth it to run against a wider suite on roachtest since the change is a bit more global now.

File: pkg/roachprod/install/cockroach.go [hunk 3]
```diff
@@ -520,17 +520,27 @@ func (c *SyncedCluster) NodeURL(
 }
 
 // NodePort returns the system tenant's SQL port for the given node.
-func (c *SyncedCluster) NodePort(ctx context.Context, node Node) (int, error) {
-	desc, err := c.DiscoverService(ctx, node, SystemInterfaceName, ServiceTypeSQL, 0)
+func (c *SyncedCluster) NodePort(
+	ctx context.Context, node Node, virtualClusterName string, sqlInstance int,
+) (int, error) {
+	if virtualClusterName == "" {
```
Comment (herkolategan) [inline pkg/roachprod/install/cockroach.go:526]: I think `DiscoverServices` already has a check for this, https://github.com/cockroachdb/cockroach/blob/master/pkg/roachprod/install/services.go#L142

**Comment by DarrylWong** [comment]
Good call: just [kicked one off](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/13692441?hideProblemsFromDependencies=false&hideTestsFromDependencies=false)

**Review by srosenberg — APPROVED** [review]
Let's add `Fixes: https://github.com/cockroachdb/cockroach/issues/117567` to the commit message for reference.

**Comment by DarrylWong** [comment]
Done!

TFTRs!

bors r=herkolategan, srosenberg
