### PR TITLE
kvserver: circuit-break requests to unavailable ranges

### LINKED ISSUE #33007: kvserver: circuit-break requests to unavailable ranges
**Describe the problem**

I'm testing multi-region deployment. I've used [performance tuning](https://www.cockroachlabs.com/docs/stable/performance-tuning.html#multi-region-deployment) docs, installed multi-datacenter cluster. DC names are `DCPRI` and `DCSEC` with 3 virtual machines in each.  
When I shutdown system in `DCSEC`, cluster on `DCPRI` is unresponsive, no SQL's work, just waits.  Also, admin GUI timeouts.

Is it because my configuration, bug or is it expected behaviour?

Here is start parameters of cockroach instances:

```
# DCPRI/Node 1
ExecStart=/usr/local/bin/cockroach start --store=path=/data/db/database,attrs=hdd --certs-dir=/data/db/certs --log-dir=/logs/CRDB --port=26257 --http-port=8088 --locality=region=ist,datacenter=dcpri --listen-addr=10.35.14.101 --join=10.10.14.101,10.10.14.102,10.10.14.103,10.10.14.104,10.10.14.105,10.10.14.106 --cache=.35 --max-sql-memory=.25
# DCPRI/Node 4
ExecStart=/usr/local/bin/cockroach start --store=path=/data/db/database,attrs=hdd --certs-dir=/data/db/certs --log-dir=/logs/CRDB --port=26257 --http-port=8088 --locality=region=ist,datacenter=dcpri --listen-addr=10.35.14.102 --join=10.10.14.101,10.10.14.102,10.10.14.103,10.10.14.104,10.10.14.105,10.10.14.106 --cache=.35 --max-sql-memory=.25
# DCPRI/Node 3
ExecStart=/usr/local/bin/cockroach start --store=path=/data/db/database,attrs=hdd --certs-dir=/data/db/certs --log-dir=/logs/CRDB --port=26257 --http-port=8088 --locality=region=ist,datacenter=dcpri --listen-addr=10.35.14.103 --join=10.10.14.101,10.10.14.102,10.10.14.103,10.10.14.104,10.10.14.105,10.10.14.106 --cache=.35 --max-sql-memory=.25
# Node 4 DCSEC
ExecStart=/usr/local/bin/cockroach start --store=path=/data/db/database,attrs=hdd --certs-dir=/data/db/certs --log-dir=/logs/CRDB --port=26257 --http-port=8088 --locality=region=ist,datacenter=dcsec --listen-addr=10.35.14.104 --join=10.10.14.101,10.10.14.102,10.10.14.103,10.10.14.104,10.10.14.105,10.10.14.106 --cache=.35 --max-sql-memory=.25
# Node 5 DCSEC
ExecStart=/usr/local/bin/cockroach start --store=path=/data/db/database,attrs=hdd --certs-dir=/data/db/certs --log-dir=/logs/CRDB --port=26257 --http-port=8088 --locality=region=ist,datacenter=dcsec --listen-addr=10.35.14.105 --join=10.10.14.101,10.10.14.102,10.10.14.103,10.10.14.104,10.10.14.105,10.10.14.106 --cache=.35 --max-sql-memory=.25
# Node 6 DCSEC
ExecStart=/usr/local/bin/cockroach start --store=path=/data/db/database,attrs=hdd --certs-dir=/data/db/certs --log-dir=/logs/CRDB --port=26257 --http-port=8088 --locality=region=ist,datacenter=dcsec --listen-addr=10.35.14.106 --join=10.10.14.101,10.10.14.102,10.10.14.103,10.10.14.104,10.10.14.105,10.10.14.106 --cache=.35 --max-sql-memory=.25
```

Logs from the nodes in DCPRI
DCPRI/Node1:

```
W181210 15:30:45.781750 136672 vendor/google.golang.org/grpc/clientconn.go:942  Failed to dial 10.10.14.105:26257: context canceled; please retry.
W181210 15:30:45.781790 139 storage/store.go:3910  [n1,s1] handle raft ready: 1.3s [processed=0]
I181210 15:30:46.795946 136580 server/authentication.go:374  Web session error: http: named cookie not present
I181210 15:30:46.799351 136228 server/authentication.go:374  Web session error: http: named cookie not present
W181210 15:30:46.909608 136729 vendor/google.golang.org/grpc/clientconn.go:1293  grpc: addrConn.createTransport failed to connect to {10.10.14.104:26257 0  <nil>}. Err :connection error: desc = "transport: Error while dialing dial tcp 10.10.14.104:26257: connect: no route to host". Reconnecting...
W181210 15:30:46.909690 136729 vendor/google.golang.org/grpc/clientconn.go:1293  grpc: addrConn.createTransport failed to connect to {10.10.14.104:26257 0  <nil>}. Err :connection error: desc = "transport: Error while dialing cannot reuse client connection". Reconnecting...
W181210 15:30:46.909704 136729 vendor/google.golang.org/grpc/clientconn.go:942  Failed to dial 10.10.14.104:26257: grpc: the connection is closing; please retry.
W181210 15:30:46.909709 142 storage/store.go:3910  [n1,s1] handle raft ready: 1.8s [processed=0]
```

DCPRI/Node4:

```
W181210 15:31:22.968999 71750 vendor/google.golang.org/grpc/clientconn.go:1293  grpc: addrConn.createTransport failed to connect to {10.10.14.105:26257 0  <nil>}. Err :connection error: desc = "transport: Error while dialing dial tcp 10.10.14.105:26257: connect: no route to host". Reconnecting...
I181210 15:31:22.969066 136 rpc/nodedialer/nodedialer.go:91  [n4] unable to connect to n6: initial connection heartbeat failed: rpc error: code = Unavailable desc = all SubConns are in TransientFailure, latest connection error: connection error: desc = "transport: Error while dialing dial tcp 10.10.14.105:26257: connect: no route to host"
W181210 15:31:22.969068 71750 vendor/google.golang.org/grpc/clientconn.go:1293  grpc: addrConn.createTransport failed to connect to {10.10.14.105:26257 0  <nil>}. Err :connection error: desc = "transport: Error while dialing cannot reuse client connection". Reconnecting...
W181210 15:31:22.969084 136 storage/store.go:3910  [n4,s4] handle raft ready: 1.1s [processed=0]
W181210 15:31:22.969095 71750 vendor/google.golang.org/grpc/clientconn.go:942  Failed to dial 10.10.14.105:26257: context canceled; please retry.
W181210 15:31:23.772921 71770 vendor/google.golang.org/grpc/clientconn.go:1293  grpc: addrConn.createTransport failed to connect to {10.10.14.106:26257 0  <nil>}. Err :connection error: desc = "transport: Error while dialing dial tcp 10.10.14.106:26257: connect: no route to host". Reconnecting...
W181210 15:31:23.772980 71770 vendor/google.golang.org/grpc/clientconn.go:1293  grpc: addrConn.createTransport failed to connect to {10.10.14.106:26257 0  <nil>}. Err :connection error: desc = "transport: Error while dialing cannot reuse client connection". Reconnecting...
W181210 15:31:23.772988 71770 vendor/google.golang.org/grpc/clientconn.go:942  Failed to dial 10.10.14.106:26257: grpc: the connection is closing; please retry.
W181210 15:31:23.773029 112 storage/store.go:3910  [n4,s4] handle raft ready: 1.3s [processed=0]
```

DCPRI/Node3:

```
I181210 15:31:50.649944 139 server/status/runtime.go:465  [n3] runtime stats: 253 MiB RSS, 224 goroutines, 140 MiB/18 MiB/175 MiB GO alloc/idle/total, 56 MiB/72 MiB CGO alloc/total, 24.1 CGO/sec, 0.7/0.3 %(u/s)time, 0.0 %gc (0x), 108 KiB/80 KiB (r/w)net
W181210 15:31:50.941579 69897 vendor/google.golang.org/grpc/clientconn.go:1293  grpc: addrConn.createTransport failed to connect to {10.10.14.106:26257 0  <nil>}. Err :connection error: desc = "transport: Error while dialing dial tcp 10.10.14.106:26257: connect: no route to host". Reconnecting...
W181210 15:31:50.941670 69897 vendor/google.golang.org/grpc/clientconn.go:1293  grpc: addrConn.createTransport failed to connect to {10.10.14.106:26257 0  <nil>}. Err :connection error: desc = "transport: Error while dialing cannot reuse client connection". Reconnecting...
W181210 15:31:50.941683 69897 vendor/google.golang.org/grpc/clientconn.go:942  Failed to dial 10.10.14.106:26257: grpc: the connection is closing; please retry.
W181210 15:31:51.217542 69854 vendor/google.golang.org/grpc/clientconn.go:1293  grpc: addrConn.createTransport failed to connect to {10.10.14.105:26257 0  <nil>}. Err :connection error: desc = "transport: Error while dialing dial tcp 10.10.14.105:26257: connect: no route to host". Reconnecting...
W181210 15:31:51.217615 31 storage/store.go:3910  [n3,s3] handle raft ready: 1.2s [processed=0]
W181210 15:31:51.217622 69854 vendor/google.golang.org/grpc/clientconn.go:1293  grpc: addrConn.createTransport failed to connect to {10.10.14.105:26257 0  <nil>}. Err :connection error: desc = "transport: Error while dialing cannot reuse client connection". Reconnecting...
W181210 15:31:51.217648 69854 vendor/google.golang.org/grpc/clientconn.go:942  Failed to dial 10.10.14.105:26257: context canceled; please retry.
```

Epic: CRDB-2553

Jira issue: CRDB-6349

### PR DESCRIPTION
**Pull request by tbg**
Fixes #33007.
Closes #61311.

This PR uses the circuit breaker package introduced in #73641 to address
issue #33007: When a replica becomes unavailable, it should eagerly
refuse traffic that it believes would simply hang.

Concretely, every request to the Replica gets a cancelable context that
is sensitive to the circuit breaker tripping (relying on context
cancellation makes sure we don't end up with a second channel that needs
to be plumbed to everyone and their dog; Go makes it really difficult to
join two cancellation chains); if the breaker is tripped when the
request arrives, it is refused right away. In either case, the outgoing
error is augmented to carry information about the tripped breaker. This
isn't 100% trivial, since retreating from in-flight replication
typically causes an `AmbiguousResultError`, and while we could avoid it
in some cases we can't in all. A similar problem occurs when the
canceled request was waiting on a lease, in which case the result is a
NotLeaseholderError.

For any request that made it in, if it enters replication but does not
manage to succeed within `base.SlowRequestThreshold` (15s at time of
writing), the breaker is tripped, cancelling all inflight and future
requests until the breaker heals. Perhaps surprisingly, the existing
"slowness" detection (the informational "have been waiting ... for
proposal" warning in `executeWriteBatch`) was moved deeper into
replication (`refreshProposalsLocked`), where it now trips the breaker.
This has the advantage of providing a unified path for lease requests
(which don't go through `executeWriteBatch`) and pipelined writes (which
return before waiting on the inflight replication process). To make this
work, we need to pick a little fight with how leases are (not) refreshed
(#74711) and we need to remember the ticks at which a proposal was first
inserted (despite potential reproposals).

A tripped breaker deploys a background probe which sends a
`ProbeRequest` (introduced in #72972) to determine when to heal; this is
roughly the case whenever replicating a command through Raft is possible
for the Replica, either by appending to the log as the Raft leader, or
by forwarding to the Raft leader. A tiny bit of special casing allows
requests made by the probe to bypass the breaker.

As of this PR, all of this is opt-in via the
`kv.replica_circuit_breakers.enabled` cluster setting while we determine
which of the many follow-up items to target for 22.1 (see #74705).  For
example, the breaker-sensitive context cancelation is a toy
implementation that comes with too much of a performance overhead (one
extra goroutine per request); #74707 will address that.

Other things not done here that we certainly want in the 22.1 release
are UI work (#74713) and metrics (#74505).

The release note is deferred to #74705 (where breakers are turned on).

Release note: None

### CODE REVIEW

**Comment by tbg** [comment]
@cockroachdb/repl-prs this is still a draft but it is ready for a high-level review. There is a lot going on and I can easily pull 5+ pieces of this into separate PRs and am planning to do so. However, before I start that I would like to get both of you on board with the basic approach. I think we've sufficiently discussed the circuit breaker API and are happy with it; I will rewrite the internals to avoid all of the unsafe stuff so ignore the internals but give the API another look and voice any larger concerns. For the NoopWrite, there is an alternative where we don't bypass the lease. I think bypassing the lease has worked out nicely and keeps `NoopWrite` simple and possibly reusable, but on the other hand the probe may pass but for some unknown reason a lease may never be acquired. My preference is to keep NoopWrite as is but make the probe use two stages, where it issues the noop write first and a lease-requiring write second but possibly this is a bad idea and I need to sleep over it and talk it through.

**Review by erikgrinaker — COMMENTED** [review]
> Reviewed 5 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/71806)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @erikgrinaker and @tbg)

___
*[pkg/util/circuit/circuitbreaker.go, line 28 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/71806#-Mo3s0Th8t9zXmDBhS3d:-Mo3s0Th8t9zXmDBhS3e:b-5e6513) ([raw file](https://github.com/cockroachdb/cockroach/blob/fac33a5757d87494e49f52dc3e1c26065cc18c09/pkg/util/circuit/circuitbreaker.go#L28)):*
> ```Go
> // from Breaker.Err(), i.e. `errors.Is(err, ErrBreakerOpen()) can be
> // used to check whether an error originated from some Breaker.
> func ErrBreakerOpen() error {
> ```

not: why not simply export the variable?
___
*[pkg/util/circuit/circuitbreaker.go, line 56 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/71806#-Mo3swPQ8OQwyUh0Ohqv:-Mo3sYCTCO0idYRIWvEs:bg5m4qg) ([raw file](https://github.com/cockroachdb/cockroach/blob/fac33a5757d87494e49f52dc3e1c26065cc18c09/pkg/util/circuit/circuitbreaker.go#L56)):*
> ```Go
> 	Name         string
> 	ShouldTrip   func(err error) error
> 	AsyncProbe   func(report func(error), done func())
> ```

Why does this need to take a `done` closure? Since the probe is expected to keep running, can't we just clean up when the closure returns?

Ah, I suppose it's because it's the probe's responsibility to spawn the async task. Is there a reason for that, i.e. why can't the prober spawn the task? The only reason I can see is for the caller to pass in its context, but that seems like an antipattern anyway?

**Comment by tbg** [comment]
Spent some time on this again today. While putting together an end-to-end test (lose quorum, try to write and see the failfast) I realized that we do need to make all parts of the read/write pipeline aware of the circuit breaker to avoid getting stuck. I knew that we needed lease proposals to be sensitive to the breaker (so that you wouldn't get stuck trying to acquire a lease over and over when there wasn't a valid lease to begin with) but I wasn't aware of a much more basic problem: that when one command fails fast after having proposed a command, the latches stick around. They have to; but this means that the next command will get stuck on the latches. So we need to short-circuit the latch acquisition as well when the breaker trips. Of course we don't want to plumb the circuit breaker everywhere, you'd really want to rely on `context.Context` for that sort of thing. I've hacked something together in the current version of the PR (as pushed right now) which I can polish to something that should get the job done for v1. Down the road, it would be interesting to explore https://github.com/cockroachdb/cockroach/pull/66884 as an ingredient here but I don't want this to become a prerequisite.

File: pkg/kv/kvserver/client_replica_circuit_breaker_test.go [hunk 1]
```diff
@@ -119,6 +120,15 @@ func TestReplicaCircuitBreaker(t *testing.T) {
 		tc.RequireIsNotLeaseholderError(t, tc.Read(n2))
 		tc.RequireIsNotLeaseholderError(t, tc.Write(n2))
 	})
+
+	runCircuitBreakerTest(t, "leaseholder-unavailable", func(t *testing.T, ctx context.Context, tc *circuitBreakerTest) {
```
Comment (erikgrinaker) [inline pkg/kv/kvserver/client_replica_circuit_breaker_test.go:124]: This should probably go into the next commit, "wip: add leaseholder-unavailable test".

**Comment by erikgrinaker** [comment]
>when one command fails fast after having proposed a command, the latches stick around. They have to; but this means that the next command will get stuck on the latches. So we need to short-circuit the latch acquisition as well when the breaker trips. Of course we don't want to plumb the circuit breaker everywhere, you'd really want to rely on `context.Context` for that sort of thing

Ugh, this is somewhat annoying. Conceptually, cancelling the context in `Send()` when the breaker trips makes sense -- it's essentially what we want to happen. But the bookkeeping gets a bit unwieldy, as you point out. It'd be nice if we could inject a cancel trigger into the context somehow, without needing to keep track of the individual cancel functions.

I'll have to remind myself of how the latch guards are managed, but if the latches turn out to be the only problem here, is it terrible to come up with a solution at/below the Raft level that causes us to abandon proposals/commands and release latches without having to do context management higher up? Although I realize that the context approach generalizes better across failure modes.

**Comment by tbg** [comment]
Discussed this with Erik yesterday. Despite the potential perf overhead we decided that it was an important property that requests get canceled reliably on breaker tripping. We are abandoning our initial ambition to let reads that can be served succeed: this is just hard to build correctly. The main reason for reads to get stuck (no lease) is handled adequately by only circuit breaking on writes (lease acquisition is a write), but it's trickier if there is a stuck in-flight write that then prevents reads from getting their latches. We'd basically have to tell the latch manager to fail-fast a read but only if it is transitively waiting on a write's latch (write latches have to stick around on unavailable ranges, even if the client has long been fail-fasted). The "transitively" here is not something the latch manager is even concerned with today, see https://github.com/cockroachdb/cockroach/pull/73916 for a related discussion.

so:

- early in Replica.Send, check the breaker, make context cancelable and stash the cancel func somewhere on `Replica`
- on break, have the probe cancel everyone.

**Comment by tbg** [comment]
Preparing a demo now (demo.sh in PR) and debugging some issue that I think is unrelated to the circuit breakers. Essentially I'm running kv0 against a cluster that has lost quorum for some kv ranges (but there is always at least one replica left), and sometimes the workload will get stuck instead of going into a pure fail-fast regime. There aren't any stacks in DistSender or on the kvserver side when this happens, so I think I'm tickling an unrelated bug. Further evidence of this - the problem persists when I restart the down nodes. Documenting troubleshooting below.

I have n1-n5, where n1 and n2 are down. Goroutine stacks for n3-n5 have all `pgwire` serving conns in `(*readTimeoutConn).Read`; so the below comes back empty (first negative grep is for the Read call, second restricts to goroutines serving pgwire through `(*conn).serveImpl`:

```
cat goroutine* | ./scripts/sgrep '!/conn.go:362/ && /conn.go:496/'
(empty)
```

In other words, all pgwire goroutines on the server are waiting for client input.

Similarly, all connExecutors attached to these conns are in `(*StmtBuf).CurCmd`:

```
cat goroutine* | ./scripts/sgrep '/onnExecutor/ && !/conn_io.go:441/'
(empty)
```

So they are waiting to be fed the next command as well (i.e. it's not like they have one going right now):

https://github.com/cockroachdb/cockroach/blob/4ef90c25dc9914e3e7254b18ae06e02fc9c0bc53/pkg/sql/conn_io.go#L440-L441

Here's the stderr of workload including stack trace (I killed it using `SIGQUIT`): https://gist.github.com/tbg/409fac0316acb0764765f0e37116b7fd

Notably, there are 32 workers (matching the default concurrency flag on my machine) and 12 of them are stuck acquiring a connection from the pool, whereas the other 20 are stuck... doing something else, see below.

```
$ cat errors.txt | scripts/sgrep '/StmtHandle/' | grep -c 'goroutine '
32
$ cat errors.txt | scripts/sgrep '/StmtHandle/ && /..Conn..Exec/' | grep -c 'goroutine '
20
$ cat errors.txt | scripts/sgrep '/StmtHandle/ && /..Pool..Acquire/' | grep -c 'goroutine '
12
```

The 20 are all here:

https://github.com/cockroachdb/vendored/blob/master/github.com/jackc/pgconn/pgconn.go#L1437

with identical stacks (https://gist.github.com/tbg/77de5731a3971ff5235439b30259f67f). In particular, they're also waiting to receive a message from the server (recall that the server is also waiting for messages from the client).

So I think there's something wrong here, probably involving errors being returned, and perhaps prepared statements?

I tried to reproduce with this branch:

https://github.com/cockroachdb/cockroach/compare/master...tbg:stuck-workload-repro?expand=1

but it looks to be chugging along nicely, and at least six minutes in I am not seeing an obvious starvation of worker goroutines. In particular, nobody is sitting on `(*Pool).Acquire` for a long time.

**Comment by tbg** [comment]
Recording for later since I'm cleaning up the branch, [demo.sh](https://gist.github.com/d22b8b4650aa08ad2a827bf7080d8aa9)

**Comment by tbg** [comment]
Something I need to look into tomorrow: when I run the demo, and reduce duration to zero, workload stops receiving errors, as expected. But when I then re-enable the breakers, the errors don't start flowing again.

File: pkg/kv/kvserver/client_replica_circuit_breaker_test.go [hunk 2]
```diff
@@ -0,0 +1,566 @@
...
+		require.NoError(t, tc.Write(n1))
+		// Disable the probe so that when the breaker trips, it stays tripped.
+		tc.SetProbeEnabled(n1, false)
+		tc.Report(n1, errors.New("boom"))
+
+		// n1 could theoretically still serve reads (there is a valid lease
+		// and none of the latches are taken), but since it is hard to determine
+		// that upfront we currently fail all reads as well.
+		tc.RequireIsBreakerOpen(t, tc.Read(n1))
+		tc.RequireIsBreakerOpen(t, tc.Write(n1))
```
Comment (erikgrinaker) [inline pkg/kv/kvserver/client_replica_circuit_breaker_test.go:81]: I wonder if we'd want to add a latency assertion for these operations, to make sure we actually fail fast. These can be pretty annoying to test reliably, but it's an important property of the breaker that requests don't appear to hang.

File: pkg/kv/kvserver/client_replica_circuit_breaker_test.go [hunk 3]
```diff
@@ -0,0 +1,566 @@
...
+		require.NoError(t, tc.RestartServer(n2))
+		tc.UntripsSoon(t, tc.Read, n1)
+		require.NoError(t, tc.Write(n1))
+	})
+
+	// In this test, the range is on n1 and n2 and we place the lease on n2 and
+	// shut down n2 and expire the lease. n1 will be a non-leaseholder without
+	// quorum, and requests to it should trip the circuit breaker. This is an
+	// interesting test case internally because here, the request that trips the
+	// breaker is the slow lease request, and not the tests's actual write. Since
```
Comment (erikgrinaker) [inline pkg/kv/kvserver/client_replica_circuit_breaker_test.go:232]: nit: tests's -> test's

File: pkg/kv/kvserver/replica.go [hunk 4]
```diff
@@ -264,6 +264,8 @@ type Replica struct {
 	// miss out on anything.
 	raftCtx context.Context
 
+	breaker *replicaCircuitBreaker
```
Comment (erikgrinaker) [inline pkg/kv/kvserver/replica.go:267]: Needs a comment.

File: pkg/kv/kvserver/replica_circuit_breaker.go [hunk 5]
```diff
@@ -0,0 +1,183 @@
...
+var defaultReplicaCircuitBreakerSlowReplicationThreshold = envutil.EnvOrDefaultDuration(
+	"COCKROACH_REPLICA_CIRCUIT_BREAKER_SLOW_REPLICATION_THRESHOLD", 0,
+)
+
+var replicaCircuitBreakerSlowReplicationThreshold = settings.RegisterPublicDurationSettingWithExplicitUnit(
+	settings.SystemOnly,
+	"kv.replica_circuit_breaker.slow_replication_threshold",
+	"duration after which slow proposals trip the per-Replica circuit breaker (zero duration disables breakers)",
+	defaultReplicaCircuitBreakerSlowReplicationThreshold,
+	func(d time.Duration) error {
```
Comment (erikgrinaker) [inline pkg/kv/kvserver/replica_circuit_breaker.go:48]: `settings.NonNegativeDuration`

File: pkg/kv/kvserver/replica_circuit_breaker.go [hunk 6]
```diff
@@ -0,0 +1,183 @@
...
+	if !desc.IsInitialized() {
+		return nil
+	}
+	ba := roachpb.BatchRequest{}
+	ba.Timestamp = r.Clock().Now()
+	ba.RangeID = r.Desc().RangeID
+	probeReq := &roachpb.ProbeRequest{}
+	probeReq.Key = desc.StartKey.AsRawKey()
+	ba.Add(probeReq)
+	thresh, ok := r.slowReplicationThreshold(&ba)
```
Comment (erikgrinaker) [inline pkg/kv/kvserver/replica_circuit_breaker.go:169]: nit: consider doing this at the start of the function, since it negates the entire function.

File: pkg/kv/kvserver/replica_circuit_breaker.go [hunk 7]
```diff
@@ -0,0 +1,183 @@
...
+) *replicaCircuitBreaker {
+	br := &replicaCircuitBreaker{
+		stopper: stopper,
+		ambCtx:  ambientCtx,
+		r:       r,
+		st:      cs,
+	}
+
+	br.wrapped = circuit.NewBreaker(circuit.Options{
+		Name:       redact.Sprintf("breaker"), // log bridge has ctx tags
```
Comment (erikgrinaker) [inline pkg/kv/kvserver/replica_circuit_breaker.go:115]: nit: unnecessary `Sprintf()`, a literal string will autocast to `redact.RedactableString`.

File: pkg/kv/kvserver/replica_circuit_breaker.go [hunk 8]
```diff
@@ -0,0 +1,183 @@
...
+	return ctx.Value(probeKey{}) != nil
+}
+
+func withCircuitBreakerProbeMarker(ctx context.Context) context.Context {
+	return context.WithValue(ctx, probeKey{}, probeKey{})
+}
+
+func (br *replicaCircuitBreaker) asyncProbe(report func(error), done func()) {
+	bgCtx := br.ambCtx.AnnotateCtx(context.Background())
+	if err := br.stopper.RunAsyncTask(
```
Comment (erikgrinaker) [inline pkg/kv/kvserver/replica_circuit_breaker.go:139]: nit: the arguments here all fit on one line, which reads better.

File: pkg/kv/kvserver/replica_raft.go [hunk 9]
```diff
@@ -1092,9 +1107,25 @@ func (r *Replica) refreshProposalsLocked(
 		log.Fatalf(ctx, "refreshAtDelta specified for reason %s != reasonTicks", reason)
 	}
 
+	var maxInflightDurationReq *roachpb.BatchRequest
+	var maxInflightDuration time.Duration
```
Comment (erikgrinaker) [inline pkg/kv/kvserver/replica_raft.go:1111]: nit: consider calling these e.g. `maxSlowProposalDuration` or something, since they're conditional on the proposals being considered slow.

File: pkg/kv/kvserver/replica_raft.go [hunk 10]
```diff
@@ -1092,9 +1107,25 @@ func (r *Replica) refreshProposalsLocked(
...
+	var slowProposalCount int64
 	var reproposals pendingCmdSlice
 	for _, p := range r.mu.proposals {
-		if p.command.MaxLeaseIndex == 0 {
+		slowReplicationThreshold, ok := r.slowReplicationThreshold(p.Request)
+		inflightDuration := r.store.cfg.RaftTickInterval * time.Duration(r.mu.ticks-p.createdAtTicks)
```
Comment (erikgrinaker) [inline pkg/kv/kvserver/replica_raft.go:1116]: Do we really want to rely on ticks here? Since ticks are driven by the scheduler, they can drift significantly from real time if the scheduler is slow (see #66686).

File: pkg/kv/kvserver/replica_raft.go [hunk 11]
```diff
@@ -1092,9 +1107,25 @@ func (r *Replica) refreshProposalsLocked(
...
+				maxInflightDuration = inflightDuration
+				maxInflightDurationReq = p.Request
+				slowProposalCount++
+			}
+		}
+		// TODO(tbg): the enabled() call is a hack until we've figured out what to
+		// do about #74711. If leases are finished instead of reproposed, they can't
+		// ever trigger the breaker, which is bad as there usually isn't anything
+		// else around that will.
+		if p.command.MaxLeaseIndex == 0 && !r.breaker.enabled() {
```
Comment (erikgrinaker) [inline pkg/kv/kvserver/replica_raft.go:1128]: Do we plan on resolving this hack before 22.1?

File: pkg/kv/kvserver/replica_range_lease.go [hunk 12]
```diff
@@ -1216,6 +1221,11 @@ func (r *Replica) redirectOnOrAcquireLeaseForRequest(
 		// against this in checkRequestTimeRLocked). So instead of assuming
 		// anything, we iterate and check again.
 		pErr = func() (pErr *roachpb.Error) {
+			// NB: the slow request detection here is not particularly useful since
+			// it guards the actual lease proposal, which is a proposal and which
+			// thus already has a "slow message" trigger attached to it.
+			//
+			// TODO(during review): decide whether to remove this right now.
```
Comment (erikgrinaker) [inline pkg/kv/kvserver/replica_range_lease.go:1228]: One argument for keeping this is that the slow proposal logging will only log the oldest request, and so it can mask the lease acquisition. We may want to add conditional slow request logging for significant system proposals such as lease acquisitions.

Given how delicate the lease acquisition stuff is, we may want to leave this in for another major release cycle, and tear it out once we're more comfortable with the new breakers. That will also retain this logging here if we either end up disabling breakers by default, or users disable it explicitly.

File: pkg/kv/kvserver/replica_raft.go [hunk 13]
```diff
@@ -1141,6 +1172,30 @@ func (r *Replica) refreshProposalsLocked(
...
+		log.Warningf(ctx,
+			"have been waiting %.2fs for slow proposal %s",
+			maxInflightDuration.Seconds(), maxInflightDurationReq,
+		)
+		// NB: this is async because we're holding lots of locks here, and we want
+		// to avoid having to pass all the information about the replica into the
+		// breaker (since the breaker needs access to this information at will to
+		// power the probe anyway). Over time, we anticipate there being multiple
+		// mechanisms which trip the breaker.
+		r.breaker.TripAsync()
```
Comment (erikgrinaker) [inline pkg/kv/kvserver/replica_raft.go:1196]: Since this is async, could we end up logging the above multiple times if we're called again before the breaker actually trips?

File: pkg/kv/kvserver/replica_send.go [hunk 14]
```diff
@@ -126,6 +126,71 @@ func (r *Replica) sendWithRangeID(
...
+	if ch := brSig.C(); ch != nil {
+		if r.store.Stopper().RunAsyncTask(ctx, "watch", func(ctx context.Context) {
+			select {
+			case <-ctx.Done():
+				return
+			case <-ch:
+				cancel()
+			}
+		}) != nil {
+			cancel()
```
Comment (erikgrinaker) [inline pkg/kv/kvserver/replica_send.go:190]: nit: this is going to get called by the `defer` anyway.

File: pkg/kv/kvserver/replica_send.go [hunk 15]
```diff
@@ -126,6 +126,71 @@ func (r *Replica) sendWithRangeID(
 		return nil, roachpb.NewError(err)
 	}
 
+	// TODO(during review): try to move some of this code into a method to keep
```
Comment (erikgrinaker) [inline pkg/kv/kvserver/replica_send.go:129]: Yes please.

File: pkg/kv/kvserver/replica_write.go [hunk 16]
```diff
@@ -345,52 +316,52 @@ func (r *Replica) executeWriteBatch(
...
+		"raft status: %+v", redact.Safe(rs), // raft status contains no PII
 	)
+	if len(nonLiveRepls.AsProto()) > 0 {
+		err = errors.Wrapf(err, "replicas on non-live nodes: %v (lost quorum: %t)", nonLiveRepls, !canMakeProgress)
+	}
+
+	return err
+}
+
+func (r *Replica) rangeUnavailableError() error {
```
Comment (erikgrinaker) [inline pkg/kv/kvserver/replica_write.go:356]: nit: consider moving this elsewhere (preferably into `replica_circuit_breaker.go`) -- it is no longer relevant for this file.

**Comment by erikgrinaker** [comment]
This turned out really nice, it was a pleasure to review.

I'll hold off on an actual approval until it's marked as ready, but this is essentially good to go I think.

**Review by erikgrinaker — COMMENTED** [review]
This turned out really nice, it was a pleasure to review.

I'll hold off on an actual approval until it's marked as ready, but this is essentially good to go I think.

**Review by tbg — COMMENTED** [review]
Can't comment on some of your review comments any more, so here you go:

>  We should call this out in the commit message, along with the rationale -- it's fairly unfortunate, and something we should aim to improve later.

Done, and filed https://github.com/cockroachdb/cockroach/issues/74799.

> I wonder if we'd want to add a latency assertion for these operations, to make sure we actually fail fast. These can be pretty annoying to test reliably, but it's an important property of the breaker that requests don't appear to hang.

There is a 45s bound on these requests right now, so if they hang the test will fail. If they return in under 45s by chance, through some other mechanism, it's implausible that they would do so with an error from the breaker. But I understand where you're coming from. Don't want to get into that yak shave now though, and adding a (say) five second timeout doesn't really add much in my opinion. A tracing-based verification could make more sense, to check that requests that arrive when the breaker is already tripped catch a log event that we know precedes any place where the request could have blocked. I'll do that in a future PR if you don't mind, though. Added a TODO.

RFAL

File: pkg/kv/kvserver/replica_raft.go (hunk 10 above)
Comment (erikgrinaker) [reply pkg/kv/kvserver/replica_raft.go:1120]: I think it's worth making a note and revisiting later. If the scheduler is overwhelmed it could cause ranges to essentially be unavailable but the breakers would be very slow to trip. But no need to block this PR on that.

File: pkg/kv/kvserver/replica_raft.go (hunk 13 above)
Comment (erikgrinaker) [reply pkg/kv/kvserver/replica_raft.go:1200]: Yeah, 3s seems reasonably unlikely.

**Review by erikgrinaker — APPROVED** [review]
Sounds good, thanks! LGTM!

**Comment by tbg** [comment]
bors r=erikgrinaker
