### PR TITLE
schemachanger: update subzone configs with new indexID from backfill

### LINKED ISSUE #141789: schemachanger: subzone configs not properly preserved after backfill
**Describe the problem**

Tables with subzone configs do not have said configs preserved after an index backfill as the subzone configs/subzone spans do not get properly updated with the new ID.

**To Reproduce**

```
# Ensure that index ID changes due to a backfill have a properly corresponding
# zone config.
subtest backfill_idx_id

statement ok
CREATE TABLE foo(i int);

statement ok
ALTER INDEX foo@foo_pkey CONFIGURE ZONE USING gc.ttlseconds=90;

statement ok
ALTER TABLE foo ADD COLUMN j INT NOT NULL DEFAULT 42;

# Here, we can see that although the index ID changed, our corresponding
# subzone config/subzone span no longer refers to our new index
skipif config local-mixed-24.3 local-legacy-schema-changer
query B colnames
WITH subzones AS (
    SELECT
        json_array_elements(
            crdb_internal.pb_to_json('cockroach.config.zonepb.ZoneConfig', config) -> 'subzones'
        ) AS config
    FROM system.zones
    WHERE id = 'foo'::REGCLASS::OID
),
subzone_indexes AS (
    SELECT
        (config -> 'indexId')::INT AS indexID
    FROM subzones
),
primary_index AS (
    SELECT
        (crdb_internal.pb_to_json(
            'cockroach.sql.sqlbase.Descriptor',
            descriptor
        )->'table'->'primaryIndex'->>'id')::INT AS primaryID
    FROM system.descriptor
    WHERE id = 'foo'::regclass::oid
)
SELECT
    (primaryID = indexID) AS match_found
FROM primary_index, subzone_indexes;
----
match_found
false

skipif config local-mixed-24.3 local-legacy-schema-changer
query T colnames
WITH subzone_spans AS (
    SELECT json_array_elements(crdb_internal.pb_to_json('cockroach.config.zonepb.ZoneConfig', config) -> 'subzoneSpans') ->> 'key' AS key
    FROM system.zones
    WHERE id = 'bar'::REGCLASS::OID
)
SELECT crdb_internal.pretty_key(decode(key, 'base64'), 0) AS pretty_key
FROM subzone_spans;
---
pretty_key
/1
```

**Expected behavior**
`match_found` should be true and the `pretty_key` output should be `/2`

### PR DESCRIPTION
**Pull request by annrpom**
This patch ensures that we update references to any index
ID that changes in a table's zone config (due to an index backfill).

Epic: none
Fixes: https://github.com/cockroachdb/cockroach/issues/141789

Release note (bug fix): Fixed a bug where replication controls on
indexes and partitions would not get properly updated during an index
backfill (in the [Declarative Schema Changer](https://www.cockroachlabs.com/docs/stable/online-schema-changes#declarative-schema-changer)) to its new ID; effectively
discarding the replication controls set on it before the backfill.

### CODE REVIEW

File: pkg/sql/schemachanger/scbuild/internal/scbuildstmt/alter_table.go [hunk 1]
```diff
@@ -143,6 +143,15 @@ func AlterTable(b BuildCtx, n *tree.AlterTable) {
 	}
 	maybeDropRedundantPrimaryIndexes(b, tbl.TableID)
 	maybeRewriteTempIDsInPrimaryIndexes(b, tbl.TableID)
+	if hasSubzones(b, tbl.TableID) {
+		currPrimaryIndexID := getCurrentPrimaryIndexID(b, tbl.TableID)
+		latestPrimaryIndex := getLatestPrimaryIndex(b, tbl.TableID)
+		// TOOD(before merge): is this ok
```
Comment (annrpom) [inline pkg/sql/schemachanger/scbuild/internal/scbuildstmt/alter_table.go:149]: find a way to prevent this from happening for all alter table ddls; we just want to target ones that will need a zcfg change

Comment (spilchen) [reply pkg/sql/schemachanger/scbuild/internal/scbuildstmt/alter_table.go]: Could we implement a descriptor validation to catch this issue? Also, do we need to repair any descriptors that reference stale or incorrect index IDs in the zone config?

**Review by spilchen — COMMENTED** [review]
> Reviewed 1 of 4 files at r1, 1 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/141800)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @annrpom and @fqazi)

___
*[`pkg/sql/schemachanger/scbuild/internal/scbuildstmt/zone_config_helpers.go` line 1404 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/141800#-OK88lCM7eGjBdyU3RLV:-OK88lCM7eGjBdyU3RLW:b-rh76bl) ([raw file](https://github.com/cockroachdb/cockroach/blob/947f17d2e569c5304fa7793ce67fe03b66620c64/pkg/sql/schemachanger/scbuild/internal/scbuildstmt/zone_config_helpers.go#L1404)):*
> ```Go
> 		SeqNum:     mostRecentSeqNum + 1,
> 	}
> 	b.Add(tzc)
> ```

So, we don't have to delete the old TableZoneConfig. I know I commented on this before, and this was deemed okay because the seqNum is always increasing. But if you have a dsc build that has multiple adds of TableZoneConfig of the same table. How do we ensure the one with the highest sequence number is applied last? Is there a deprule that enforces this.

**Review by annrpom — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/141800)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @fqazi and @spilchen)

___
*[`pkg/sql/schemachanger/scbuild/internal/scbuildstmt/zone_config_helpers.go` line 1404 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/141800#-OK88lCM7eGjBdyU3RLV:-OKRrp9ZEILNKoh8cK1j:b-pmnd5u) ([raw file](https://github.com/cockroachdb/cockroach/blob/947f17d2e569c5304fa7793ce67fe03b66620c64/pkg/sql/schemachanger/scbuild/internal/scbuildstmt/zone_config_helpers.go#L1404)):*
<details><summary><i>Previously, spilchen wrote…</i></summary><blockquote>

So, we don't have to delete the old TableZoneConfig. I know I commented on this before, and this was deemed okay because the seqNum is always increasing. But if you have a dsc build that has multiple adds of TableZoneConfig of the same table. How do we ensure the one with the highest sequence number is applied last? Is there a deprule that enforces this.
</blockquote></details>

That's a good question -- we don't have any deprules that enforce this currently, but we do have https://github.com/cockroachdb/cockroach/issues/129482; for my understanding: I am also a bit confused as to why we would need to ensure that the highest seq num is applied last (as in: i don't fully understand where in the code that would "scramble" the order in which we deal with zone cfgs in the DSC) -- where do you expect this to occur?

**Review by fqazi — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/141800)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @spilchen)

___
*[`pkg/sql/schemachanger/scbuild/internal/scbuildstmt/zone_config_helpers.go` line 1404 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/141800#-OK88lCM7eGjBdyU3RLV:-OKRwKrxD9gbsjefbNwb:b-khzcnu) ([raw file](https://github.com/cockroachdb/cockroach/blob/947f17d2e569c5304fa7793ce67fe03b66620c64/pkg/sql/schemachanger/scbuild/internal/scbuildstmt/zone_config_helpers.go#L1404)):*
<details><summary><i>Previously, annrpom (annie pompa) wrote…</i></summary><blockquote>

That's a good question -- we don't have any deprules that enforce this currently, but we do have https://github.com/cockroachdb/cockroach/issues/129482; for my understanding: I am also a bit confused as to why we would need to ensure that the highest seq num is applied last (as in: i don't fully understand where in the code that would "scramble" the order in which we deal with zone cfgs in the DSC) -- where do you expect this to occur?
</blockquote></details>

I think the concern was rules constraining things so that they couldn't be applied in order. Or just code paths being nested in some way where elements weren't added in order. That said, I don't see the logic that used to do this anymore in the builder. But we would intentionally shuffle things on test builds before.

**Review by fqazi — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/141800#-:-OKRxVxNDufFPzW8PE1t:bnfp4nl)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @spilchen)

**Review by rafiss — APPROVED** [review]
nice work! just had one nit

i think we should leave the issue open until we finish adding the validation+repair logic. (in a separate PR)

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/141800#-:-OKS4Ken8yMfecZhGH79:b-skv6s3)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @fqazi and @spilchen)

___
*[`pkg/sql/schemachanger/scbuild/internal/scbuildstmt/zone_config_helpers.go` line 1409 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/141800#-OKS4523B-VLBYfhgkR8:-OKS4523B-VLBYfhgkR9:b-dnsb33) ([raw file](https://github.com/cockroachdb/cockroach/blob/947f17d2e569c5304fa7793ce67fe03b66620c64/pkg/sql/schemachanger/scbuild/internal/scbuildstmt/zone_config_helpers.go#L1409)):*
> ```Go
> 
> // TODO(annie): This is unused for now.
> var _ = configureZoneConfigForNewIndexPartitioning
> ```

when do we plan to start using this? i would have expected we'd need it now.
___
*[`pkg/sql/schemachanger/scbuild/internal/scbuildstmt/alter_table.go` line 209 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/141800#-OKS3Zq-EaKET6BWFhNS:-OKS3Zq-EaKET6BWFhNT:b8dlkyr) ([raw file](https://github.com/cockroachdb/cockroach/blob/947f17d2e569c5304fa7793ce67fe03b66620c64/pkg/sql/schemachanger/scbuild/internal/scbuildstmt/alter_table.go#L209)):*
> ```Go
> 		latestPrimaryIndex := getLatestPrimaryIndex(b, tableID)
> 		if err := configureZoneConfigForNewIndexBackfill(b, tableID, currPrimaryIndexID, latestPrimaryIndex.IndexID); err != nil {
> 			panic(fmt.Sprintf(
> ```

nit: use `pgerror.Wrapf` here so this is an error, and not just a string.

**Review by spilchen — APPROVED** [review]
:lgtm: I'm fine with this change if you'd like to handle validation and repair in a separate PR.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/141800#-:-OKS9kf9CvBFuvBoL_qv:b8jejxr)* status: <span>:shipit:</span> complete! 2 of 0 LGTMs obtained (waiting on @annrpom, @fqazi, and @rafiss)

___
*[`pkg/sql/schemachanger/scbuild/internal/scbuildstmt/zone_config_helpers.go` line 1404 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/141800#-OK88lCM7eGjBdyU3RLV:-OKS98kt3LQK3EENF8WZ:b7kgb19) ([raw file](https://github.com/cockroachdb/cockroach/blob/947f17d2e569c5304fa7793ce67fe03b66620c64/pkg/sql/schemachanger/scbuild/internal/scbuildstmt/zone_config_helpers.go#L1404)):*
<details><summary><i>Previously, fqazi (Faizan Qazi) wrote…</i></summary><blockquote>

I think the concern was rules constraining things so that they couldn't be applied in order. Or just code paths being nested in some way where elements weren't added in order. That said, I don't see the logic that used to do this anymore in the builder. But we would intentionally shuffle things on test builds before.
</blockquote></details>

I was thinking about future-proofing this. It is my understanding that, currently, nothing rearranges the order of the TableZoneConfig additions. However, if a mechanism (such as a deprule) is introduced in the future, how can we ensure that the additions are applied in the correct order? It seems wise to add a deprule.

**Comment by annrpom** [comment]
i put the recent change in a seperate commit i intend on squashing before merge for ease of review

**Review by annrpom — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/141800)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (and 2 stale) (waiting on @fqazi, @rafiss, and @spilchen)

___
*[`pkg/sql/schemachanger/scbuild/internal/scbuildstmt/alter_table.go` line 209 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/141800#-OKS3Zq-EaKET6BWFhNS:-OKSCgZf3bB9jS9Yy5FZ:bb7f2mf) ([raw file](https://github.com/cockroachdb/cockroach/blob/3285f3b731f6bb1c759cbbcb95ea1e0f72e7053b/pkg/sql/schemachanger/scbuild/internal/scbuildstmt/alter_table.go#L209)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

nit: use `pgerror.Wrapf` here so this is an error, and not just a string.
</blockquote></details>

done
___
*[`pkg/sql/schemachanger/scbuild/internal/scbuildstmt/zone_config_helpers.go` line 1404 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/141800#-OK88lCM7eGjBdyU3RLV:-OKSCRU075KLQN7CEdef:bpjpwns) ([raw file](https://github.com/cockroachdb/cockroach/blob/3285f3b731f6bb1c759cbbcb95ea1e0f72e7053b/pkg/sql/schemachanger/scbuild/internal/scbuildstmt/zone_config_helpers.go#L1404)):*
<details><summary><i>Previously, spilchen wrote…</i></summary><blockquote>

I was thinking about future-proofing this. It is my understanding that, currently, nothing rearranges the order of the TableZoneConfig additions. However, if a mechanism (such as a deprule) is introduced in the future, how can we ensure that the additions are applied in the correct order? It seems wise to add a deprule.
</blockquote></details>

ah ok now i understand a bit better: +1 to adding a deprule then; i'll pick up the linked issue
___
*[`pkg/sql/schemachanger/scbuild/internal/scbuildstmt/zone_config_helpers.go` line 1409 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/141800#-OKS4523B-VLBYfhgkR8:-OKSCa2b7xyheHZkIGPM:bgcd3rb) ([raw file](https://github.com/cockroachdb/cockroach/blob/3285f3b731f6bb1c759cbbcb95ea1e0f72e7053b/pkg/sql/schemachanger/scbuild/internal/scbuildstmt/zone_config_helpers.go#L1409)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

when do we plan to start using this? i would have expected we'd need it now.
</blockquote></details>

she's over here https://github.com/cockroachdb/cockroach/pull/140617 !

**Review by spilchen — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/141800)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (and 2 stale) (waiting on @fqazi and @rafiss)

___
*[`pkg/sql/schemachanger/scbuild/internal/scbuildstmt/alter_table.go` line 210 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/141800#-OKboVci5QFRhGpcE-JA:-OKboVci5QFRhGpcE-JB:b-vw51gi) ([raw file](https://github.com/cockroachdb/cockroach/blob/3f493f480591dc17d7cbf53a90fb2d6d251f55c2/pkg/sql/schemachanger/scbuild/internal/scbuildstmt/alter_table.go#L210)):*
> ```Go
> 			panic(pgerror.Wrapf(
> 				err,
> 				pgcode.Uncategorized,
> ```

Is it appropriate to add a `pgcode` to this error, particularly the uncategorized code? Could this potentially overwrite an existing `pgcode` that was already set? I'm wondering if we should use `errors.Wrapf` instead.

**Review by rafiss — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/141800)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (and 2 stale) (waiting on @fqazi and @spilchen)

___
*[`pkg/sql/schemachanger/scbuild/internal/scbuildstmt/alter_table.go` line 210 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/141800#-OKboVci5QFRhGpcE-JA:-OKcD8qL6QosDUHZysOG:b2gl7zf) ([raw file](https://github.com/cockroachdb/cockroach/blob/3f493f480591dc17d7cbf53a90fb2d6d251f55c2/pkg/sql/schemachanger/scbuild/internal/scbuildstmt/alter_table.go#L210)):*
<details><summary><i>Previously, spilchen wrote…</i></summary><blockquote>

Is it appropriate to add a `pgcode` to this error, particularly the uncategorized code? Could this potentially overwrite an existing `pgcode` that was already set? I'm wondering if we should use `errors.Wrapf` instead.
</blockquote></details>

the `pgerror.Wrap` function takes care not to overwrite the code if one was set already. 

but i agree, if we don't have a better code to add here, we should use `errors.Wrap`. that way we don't prevent a higher-up layer from adding its own pgcode.

**Review by fqazi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 4 files at r1, 2 of 4 files at r2, 7 of 7 files at r4, 7 of 7 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/141800)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (and 2 stale) (waiting on @rafiss and @spilchen)

___
*[`pkg/ccl/schemachangerccl/testdata/end_to_end/add_column_subzones/add_column_subzones.explain` line 11 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/141800#-OKghGQ59_xUJwjJXPwW:-OKghGQ59_xUJwjJXPwX:b6axxp) ([raw file](https://github.com/cockroachdb/cockroach/blob/5e4db5d78b3d7a9b5792499d52dfd7ad2b4b2f28/pkg/ccl/schemachangerccl/testdata/end_to_end/add_column_subzones/add_column_subzones.explain#L11)):*
> ```
> EXPLAIN (DDL) ALTER TABLE t ADD COLUMN w TEXT NOT NULL DEFAULT 's';
> ----
> Schema change plan for ALTER TABLE ‹defaultdb›.‹public›.‹t› ADD COLUMN ‹w› STRING NOT NULL DEFAULT ‹'s'›;
> ```

I would expect the plan here to have zone config elements? Am I missing something?

**Review by fqazi — APPROVED** [review]
:lgtm:

> Reviewed 23 of 23 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/141800#-:-OL63XeKAMb8I0c5MXQY:bnfp4nl)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @annrpom, @rafiss, and @spilchen)

**Comment by annrpom** [comment]
> but i agree, if we don't have a better code to add here, we should use errors.Wrap. that way we don't prevent a higher-up layer from adding its own pgcode.

oki makes sense (ty matt, rafi); i looked through the error codes and couldn't find a good one for this situation

> I would expect the plan here to have zone config elements? Am I missing something?

i forgot that the way we update subzone configs makes it so that we don't add the subzone config to uncommitted inside of `UpdateSubzoneConfig`; we can fix this in a later PR if desired, but we can also mock the behavior by forcing something that calls `UpdateZoneConfig`

i'm gonna squash the 2 commits and rebase! TFTRs! ('-')7

**Comment by annrpom** [comment]
failure is:

```
--- FAIL: acceptance/version-upgrade (68.67s)
  (mixedversion.go:800).Run: mixed-version test failure while running step 8 (set cluster setting "kv.snapshot_receiver.excise.enabled" to 'true' on system tenant): pq: unknown cluster setting 'kv.snapshot_receiver.excise.enabled' [owner=test-eng]
```
