### PR TITLE
workload/ycsb: Use StmtContext instead of Stmt

### LINKED ISSUE #39521: roachtest: ycsb/F/nodes=3/cpu=32 failed
SHA: https://github.com/cockroachdb/cockroach/commits/98d6832e9f9edb7e554aaa90d9d4296bb00af16e

Parameters:

To repro, try:

```
# Don't forget to check out a clean suitable branch and experiment with the
# stress invocation until the desired results present themselves. For example,
# using stress instead of stressrace and passing the '-p' stressflag which
# controls concurrency.
./scripts/gceworker.sh start && ./scripts/gceworker.sh mosh
cd ~/go/src/github.com/cockroachdb/cockroach && \
stdbuf -oL -eL \
make stressrace TESTS=ycsb/F/nodes=3/cpu=32 PKG=roachtest TESTTIMEOUT=5m STRESSFLAGS='-maxtime 20m -timeout 10m' 2>&1 | tee /tmp/stress.log
```

Failed test: https://teamcity.cockroachdb.com/viewLog.html?buildId=1433699&tab=buildLog

```
The test failed on branch=master, cloud=aws:
test artifacts and logs in: /home/agent/work/.go/src/github.com/cockroachdb/cockroach/artifacts/20190810-1433699/ycsb/F/nodes=3/cpu=32/run_1
	cluster.go:1735,ycsb.go:36,cluster.go:2078,errgroup.go:57: /home/agent/work/.go/src/github.com/cockroachdb/cockroach/bin/roachprod run teamcity-1565418008-04-n4cpu32:4 -- ./workload run ycsb --init --insert-count=1000000 --splits=100 --workload=F --concurrency=64 --histograms=perf/stats.json --ramp=1m --duration=10m {pgurl:1-3} returned:
		stderr:
		
		stdout:
		       0            0.0         1686.9      0.0      0.0      0.0      0.0 read
		     56s        0            0.0         1685.9      0.0      0.0      0.0      0.0 readModifyWrite
		     57s        0            0.0         1657.3      0.0      0.0      0.0      0.0 read
		     57s        0            0.0         1656.3      0.0      0.0      0.0      0.0 readModifyWrite
		     58s        0            0.0         1628.7      0.0      0.0      0.0      0.0 read
		     58s        0            0.0         1627.8      0.0      0.0      0.0      0.0 readModifyWrite
		     59s        0            0.0         1601.1      0.0      0.0      0.0      0.0 read
		     59s        0            0.0         1600.2      0.0      0.0      0.0      0.0 readModifyWrite
		    1m0s        0            0.0         1574.4      0.0      0.0      0.0      0.0 read
		    1m0s        0            0.0         1573.5      0.0      0.0      0.0      0.0 readModifyWrite
		Error: sql: transaction has already been committed or rolled back
		Error:  exit status 1
		: exit status 1
	cluster.go:2099,ycsb.go:39,ycsb.go:55,test_runner.go:691: Goexit() was called

```

### PR DESCRIPTION
**Pull request by jeffrey-xiao**
`StmtContext` allows `context.DeadlineExceeded` error to be returned consistently. Using `Stmt` would sometimes return `sql: transaction has already been committed or rolled back` causing the workload to fail.

Additionally, sometimes a context cancellation during a transaction can result in sql.ErrNoRows instead of the appropriat econtext.DeadlineExceeded. In this case, we just return ctx.Err().

See https://github.com/lib/pq/issues/874.

Fixes #39521. 

`workload run ycsb --drop --insert-count=1000000 --splits=100 --workload=F --concurrency=64 --ramp=1m --duration=10m` terminates successfully with this change.

Release note: None

### CODE REVIEW

**Review by ajwerner — APPROVED** [review]
:lgtm: The reason for the deadline was the `--duration` flag?

> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/39525#-:-Lm5EhIO772265wIWcu9:b2dzbzd)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @nvanbenschoten)

**Review by jeffrey-xiao — COMMENTED** [review]
`context.DeadlineExceeded` comes from the `--ramp` flag which gradually starts all workers with a `rampCtx` then restarts them with the main context.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/39525#-:-Lm5Fpvf6ftgVEzQYQl5:b-97jssi)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @nvanbenschoten)

**Review by ajwerner — APPROVED** [review]
> context.DeadlineExceeded comes from the --ramp flag which gradually starts all workers with a rampCtx then restarts them with the main context.

:ok_hand: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/39525#-:-Lm5KgWt-AhVFU0ipJM7:b3kog3w)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @nvanbenschoten)

**Review by nvb — APPROVED** [review]

File: pkg/workload/ycsb/ycsb.go [hunk 1]
```diff
@@ -585,9 +585,17 @@ func (yw *ycsbWorker) readModifyWriteRow(ctx context.Context) error {
 			updateStmt = yw.updateStmts[fieldIdx]
 			args[1] = newValue
 		}
-		_, err := tx.Stmt(updateStmt).ExecContext(ctx, args[:]...)
+		_, err := tx.StmtContext(ctx, updateStmt).ExecContext(ctx, args[:]...)
 		return err
 	})
+	if err == gosql.ErrNoRows {
```
Comment (nvanbenschoten) [inline pkg/workload/ycsb/ycsb.go]: `if err == gosql.ErrNoRows && ctx.Err() != nil {`

**Review by nvb — APPROVED** [review]
LGTM once that comment is addressed.

**Comment by jeffrey-xiao** [comment]
TFTRs!

bors r+
