### PR TITLE
c2c: dont swallow pts update error

### LINKED ISSUE #103015: streamingccl: progress update failures should eventually be raised to the job level
**Describe the problem**

Currently, failures to update the job progress are simply logged. As a result, prolonged inability to checkpoint progress is never raised to the user in the form of a paused-on-error job.  We should probably raise an error if we aren't able to checkpoint progress after some time.

https://github.com/cockroachdb/cockroach/blob/b87c8e8a6e8719a80a9c022b8d55773a91e22654/pkg/ccl/streamingccl/streamingest/stream_ingestion_frontier_processor.go#L298-L299

### LINKED ISSUE #103534: c2c: cutover is not resilient to node shutdown
If the coordinator node issuing revert range requests during cutover fails over, another node will be not able to resume the work. This occurs because the current implementation of cutover [uses](https://github.com/cockroachdb/cockroach/blob/master/pkg/ccl/streamingccl/streamingest/stream_ingestion_job.go#L682) the the job progress FractionCompleted oneOf f[ield](https://github.com/cockroachdb/cockroach/blob/53afe66d3d4d3b1647f3fcda73fe0e66833e81eb/pkg/jobs/jobspb/jobs.proto#L1299). Sadly, during regular ingestion, we use the progress high_water field, so when cutover begins, we write over the job progress's high water mark.

When a node then tries to resume cutover after the og coordinator dies, it can't, because it attempts to check the high water mark which is unreadible.

This was seen https://github.com/cockroachdb/cockroach/issues/103008#issuecomment-1549767358

Jira issue: CRDB-28065

Epic CRDB-25146

### LINKED ISSUE #103575: roachtest: c2c/shutdown/src/coordinator failed
roachtest.c2c/shutdown/src/coordinator [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/10137655?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/10137655?buildTab=artifacts#/c2c/shutdown/src/coordinator) on master @ [8f10f78aed7606edd454e886183bf22c74a3153e](https://github.com/cockroachdb/cockroach/commits/8f10f78aed7606edd454e886183bf22c74a3153e):

```
test artifacts and logs in: /artifacts/c2c/shutdown/src/coordinator/run_1
(assertions.go:262).Fail: 
	Error Trace:	github.com/cockroachdb/cockroach/pkg/cmd/roachtest/tests/cluster_to_cluster.go:974
	            				github.com/cockroachdb/cockroach/pkg/cmd/roachtest/tests/cluster_to_cluster.go:991
	            				github.com/cockroachdb/cockroach/pkg/cmd/roachtest/tests/cluster_to_cluster.go:1107
	            				github.com/cockroachdb/cockroach/pkg/cmd/roachtest/tests/jobs.go:90
	            				main/pkg/cmd/roachtest/monitor.go:105
	            				golang.org/x/sync/errgroup/external/org_golang_x_sync/errgroup/errgroup.go:75
	            				GOROOT/src/runtime/asm_amd64.s:1594
	Error:      	Not equal: 
	            	expected: "running"
	            	actual  : "succeeded"
	            	
	            	Diff:
	            	--- Expected
	            	+++ Actual
	            	@@ -1,2 +1,2 @@
	            	-(jobs.Status) (len=7) "running"
	            	+(jobs.Status) (len=9) "succeeded"
	            	 
	Test:       	c2c/shutdown/src/coordinator
(require.go:165).Equal: FailNow called
(monitor.go:127).Wait: monitor failure: monitor task failed: t.Fatal() was called
```
<p>Parameters: <code>ROACHTEST_cloud=gce</code>
, <code>ROACHTEST_cpu=8</code>
, <code>ROACHTEST_encrypted=false</code>
, <code>ROACHTEST_fs=ext4</code>
, <code>ROACHTEST_localSSD=true</code>
, <code>ROACHTEST_ssd=0</code>
</p>
<details><summary>Help</summary>
<p>

See: [roachtest README](https://github.com/cockroachdb/cockroach/blob/master/pkg/cmd/roachtest/README.md)

See: [How To Investigate \(internal\)](https://cockroachlabs.atlassian.net/l/c/SSSBr8c7)

</p>
</details>
/cc @cockroachdb/disaster-recovery
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*c2c/shutdown/src/coordinator.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)
</sub>

Jira issue: CRDB-28085

### LINKED ISSUE #103701: roachtest: c2c/shutdown/src/worker failed
roachtest.c2c/shutdown/src/worker [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/10177814?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/10177814?buildTab=artifacts#/c2c/shutdown/src/worker) on master @ [b34c137004f111b915fb346da9a4770264d6c22f](https://github.com/cockroachdb/cockroach/commits/b34c137004f111b915fb346da9a4770264d6c22f):

```
test artifacts and logs in: /artifacts/c2c/shutdown/src/worker/run_1
(assertions.go:262).Fail: 
	Error Trace:	github.com/cockroachdb/cockroach/pkg/cmd/roachtest/tests/cluster_to_cluster.go:974
	            				github.com/cockroachdb/cockroach/pkg/cmd/roachtest/tests/cluster_to_cluster.go:991
	            				github.com/cockroachdb/cockroach/pkg/cmd/roachtest/tests/cluster_to_cluster.go:1107
	            				github.com/cockroachdb/cockroach/pkg/cmd/roachtest/tests/jobs.go:90
	            				main/pkg/cmd/roachtest/monitor.go:105
	            				golang.org/x/sync/errgroup/external/org_golang_x_sync/errgroup/errgroup.go:75
	            				GOROOT/src/runtime/asm_amd64.s:1594
	Error:      	Not equal: 
	            	expected: "running"
	            	actual  : "succeeded"
	            	
	            	Diff:
	            	--- Expected
	            	+++ Actual
	            	@@ -1,2 +1,2 @@
	            	-(jobs.Status) (len=7) "running"
	            	+(jobs.Status) (len=9) "succeeded"
	            	 
	Test:       	c2c/shutdown/src/worker
(require.go:165).Equal: FailNow called
(monitor.go:127).Wait: monitor failure: monitor task failed: t.Fatal() was called
```
<p>Parameters: <code>ROACHTEST_cloud=gce</code>
, <code>ROACHTEST_cpu=8</code>
, <code>ROACHTEST_encrypted=false</code>
, <code>ROACHTEST_fs=ext4</code>
, <code>ROACHTEST_localSSD=true</code>
, <code>ROACHTEST_ssd=0</code>
</p>
<details><summary>Help</summary>
<p>

See: [roachtest README](https://github.com/cockroachdb/cockroach/blob/master/pkg/cmd/roachtest/README.md)

See: [How To Investigate \(internal\)](https://cockroachlabs.atlassian.net/l/c/SSSBr8c7)

</p>
</details>
<details><summary>Same failure on other branches</summary>
<p>

- #103699 roachtest: c2c/shutdown/src/worker failed [C-test-failure O-roachtest O-robot T-disaster-recovery branch-release-23.1 release-blocker]
</p>
</details>
/cc @cockroachdb/disaster-recovery
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*c2c/shutdown/src/worker.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)
</sub>

Jira issue: CRDB-28145

### LINKED ISSUE #103825: roachtest: c2c/shutdown/dest/worker failed
roachtest.c2c/shutdown/dest/worker [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/10217735?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/10217735?buildTab=artifacts#/c2c/shutdown/dest/worker) on master @ [775b005927ee65a7af3b9cd4078d607c770244d6](https://github.com/cockroachdb/cockroach/commits/775b005927ee65a7af3b9cd4078d607c770244d6):

```
test artifacts and logs in: /artifacts/c2c/shutdown/dest/worker/run_1
(assertions.go:262).Fail: 
	Error Trace:	github.com/cockroachdb/cockroach/pkg/cmd/roachtest/tests/cluster_to_cluster.go:567
	            				github.com/cockroachdb/cockroach/pkg/cmd/roachtest/tests/cluster_to_cluster.go:685
	            				github.com/cockroachdb/cockroach/pkg/cmd/roachtest/tests/cluster_to_cluster.go:1090
	            				main/pkg/cmd/roachtest/monitor.go:105
	            				golang.org/x/sync/errgroup/external/org_golang_x_sync/errgroup/errgroup.go:75
	            				GOROOT/src/runtime/asm_amd64.s:1594
	Error:      	Received unexpected error:
	            	expected job status succeeded, but got running
	            	(1) attached stack trace
	            	  -- stack trace:
	            	  | github.com/cockroachdb/cockroach/pkg/cmd/roachtest/tests.(*replicationDriver).stopReplicationStream.func1
	            	  | 	github.com/cockroachdb/cockroach/pkg/cmd/roachtest/tests/cluster_to_cluster.go:563
	            	  | github.com/cockroachdb/cockroach/pkg/util/retry.ForDuration
	            	  | 	github.com/cockroachdb/cockroach/pkg/util/retry/retry.go:213
	            	  | github.com/cockroachdb/cockroach/pkg/cmd/roachtest/tests.(*replicationDriver).stopReplicationStream
	            	  | 	github.com/cockroachdb/cockroach/pkg/cmd/roachtest/tests/cluster_to_cluster.go:545
	            	  | github.com/cockroachdb/cockroach/pkg/cmd/roachtest/tests.(*replicationDriver).main
	            	  | 	github.com/cockroachdb/cockroach/pkg/cmd/roachtest/tests/cluster_to_cluster.go:685
	            	  | github.com/cockroachdb/cockroach/pkg/cmd/roachtest/tests.registerClusterReplicationResilience.func1.3
	            	  | 	github.com/cockroachdb/cockroach/pkg/cmd/roachtest/tests/cluster_to_cluster.go:1090
	            	  | main.(*monitorImpl).Go.func1
	            	  | 	main/pkg/cmd/roachtest/monitor.go:105
	            	  | golang.org/x/sync/errgroup.(*Group).Go.func1
	            	  | 	golang.org/x/sync/errgroup/external/org_golang_x_sync/errgroup/errgroup.go:75
	            	  | runtime.goexit
	            	  | 	GOROOT/src/runtime/asm_amd64.s:1594
	            	Wraps: (2) expected job status succeeded, but got running
	            	Error types: (1) *withstack.withStack (2) *errutil.leafError
	Test:       	c2c/shutdown/dest/worker
(require.go:1264).NoError: FailNow called
(monitor.go:127).Wait: monitor failure: monitor task failed: context canceled while waiting for job to finish: context canceled
(test_runner.go:1109).func1: 1 dead node(s) detected
```
<p>Parameters: <code>ROACHTEST_cloud=gce</code>
, <code>ROACHTEST_cpu=8</code>
, <code>ROACHTEST_encrypted=false</code>
, <code>ROACHTEST_fs=ext4</code>
, <code>ROACHTEST_localSSD=true</code>
, <code>ROACHTEST_ssd=0</code>
</p>
<details><summary>Help</summary>
<p>

See: [roachtest README](https://github.com/cockroachdb/cockroach/blob/master/pkg/cmd/roachtest/README.md)

See: [How To Investigate \(internal\)](https://cockroachlabs.atlassian.net/l/c/SSSBr8c7)

</p>
</details>
<details><summary>Same failure on other branches</summary>
<p>

- #103765 roachtest: c2c/shutdown/dest/worker failed [C-test-failure O-roachtest O-robot T-disaster-recovery branch-release-23.1]
</p>
</details>
/cc @cockroachdb/disaster-recovery
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*c2c/shutdown/dest/worker.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)
</sub>

Jira issue: CRDB-28222

### PR DESCRIPTION
**Pull request by msbutler**
c2c: dont swallow pts update error

Fixes #103015

Release note: none

### CODE REVIEW

File: pkg/ccl/streamingccl/streamingest/stream_ingestion_frontier_processor.go [hunk 1]
```diff
@@ -288,15 +288,16 @@ func (sf *streamIngestionFrontier) Next() (
...
-		if _, err = sf.noteResolvedTimestamps(row[0]); err != nil {
+		if _, err := sf.noteResolvedTimestamps(row[0]); err != nil {
 			sf.MoveToDraining(err)
 			break
 		}
 
 		if err := sf.maybeUpdatePartitionProgress(); err != nil {
 			// Updating the partition progress isn't a fatal error.
 			log.Errorf(sf.Ctx(), "failed to update partition progress: %+v", err)
+			sf.MoveToDraining(err)
```
Comment (adityamaru) [inline pkg/ccl/streamingccl/streamingest/stream_ingestion_frontier_processor.go:299]: Do we want to always surface progress update errors or do we need some logic to only surface errors if 1 in x attempts fails? Are there any higher level retries that will prevent the job from entering a fatal state?

Comment (msbutler) [reply pkg/ccl/streamingccl/streamingest/stream_ingestion_frontier_processor.go:299]: > Do we want to always surface progress update errors or do we need some logic to only surface errors if 1 in x attempts fails?

An error here would indicate that the pts record is unreachable, which seems problematic. Changefeeds also error out in [an analogous codepath](https://github.com/cockroachdb/cockroach/blob/e8b075b44e6bea78c01c596ce4a2a54f3c057422/pkg/ccl/changefeedccl/changefeed_processors.go#L1418). Though it might be worth retrying the pts update within `maybeUpdatePartitionProgress()`. I think cdc folks have been thinking about this. I'll ping them.

The job currently has [60 retries ](https://github.com/cockroachdb/cockroach/blob/df7e2231cc3110da122bfe313044722c4818eac4/pkg/ccl/streamingccl/streamingest/stream_ingestion_job.go#L291)before it moves to a paused state.

Comment (msbutler) [reply pkg/ccl/streamingccl/streamingest/stream_ingestion_frontier_processor.go:299]: I am tempted to wait and see how CDC folks handle this [issue ](https://github.com/cockroachdb/cockroach/issues/98585), and keep the PR as is for 23.1 at least.

File: pkg/ccl/streamingccl/streamingest/stream_ingestion_frontier_processor.go [hunk 2]
```diff
@@ -288,15 +288,16 @@ func (sf *streamIngestionFrontier) Next() (
...
 
-		var err error
-		if _, err = sf.noteResolvedTimestamps(row[0]); err != nil {
+		if _, err := sf.noteResolvedTimestamps(row[0]); err != nil {
 			sf.MoveToDraining(err)
 			break
 		}
 
 		if err := sf.maybeUpdatePartitionProgress(); err != nil {
 			// Updating the partition progress isn't a fatal error.
```
Comment (stevendanna) [inline pkg/ccl/streamingccl/streamingest/stream_ingestion_frontier_processor.go:297]: This comment is incorrect now.

File: pkg/ccl/streamingccl/streamingest/stream_ingestion_frontier_processor.go [hunk 3]
```diff
@@ -288,15 +288,16 @@ func (sf *streamIngestionFrontier) Next() (
 			break
 		}
 
-		var err error
-		if _, err = sf.noteResolvedTimestamps(row[0]); err != nil {
+		if _, err := sf.noteResolvedTimestamps(row[0]); err != nil {
```
Comment (stevendanna) [inline pkg/ccl/streamingccl/streamingest/stream_ingestion_frontier_processor.go:291]: 👍 Thanks for doing this kinda of small cleanup.

File: pkg/ccl/streamingccl/streamingest/stream_ingestion_frontier_processor.go (hunk 1 above)
Comment (stevendanna) [reply pkg/ccl/streamingccl/streamingest/stream_ingestion_frontier_processor.go:299]: If we don't want to add it to this PR, let's open an issue to add some retry policy here. I'm still of the opinion that overall this PR is moving us further in the correct direction.

Comment (msbutler) [reply pkg/ccl/streamingccl/streamingest/stream_ingestion_frontier_processor.go:298]: I say we merge as is :D

**Review by msbutler — COMMENTED** [review]
removed the commit to deflake the roachtests, as stevens [PR](https://github.com/cockroachdb/cockroach/pull/103835) should fix the root problem

File: pkg/ccl/streamingccl/streamingest/stream_ingestion_frontier_processor.go (hunk 1 above)
Comment (adityamaru) [reply pkg/ccl/streamingccl/streamingest/stream_ingestion_frontier_processor.go:298]: sounds good to me

Comment (msbutler) [reply pkg/ccl/streamingccl/streamingest/stream_ingestion_frontier_processor.go:298]: added a follow up issue https://github.com/cockroachdb/cockroach/issues/103918

**Review by stevendanna — APPROVED** [review]

**Comment by msbutler** [comment]
ty for the discussion! 

bors r=stevendanna

**Comment by msbutler** [comment]
blathers backport 23.1
