### PR TITLE
util/log: skip malformed log entries while reading from file

### LINKED ISSUE #149866: roachtest: db-console/mixed-version-endpoints failed
roachtest.db-console/mixed-version-endpoints [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyAwsBazel/20141905?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyAwsBazel/20141905?buildTab=artifacts#/db-console/mixed-version-endpoints) on master @ [9ddf582e7c38e1b5e844b1f6dfc014ac5f8843c0](https://github.com/cockroachdb/cockroach/commits/9ddf582e7c38e1b5e844b1f6dfc014ac5f8843c0):

```
failed to verify response: unexpected status code: 500, body: {
  "error": "An internal server error has occurred. Please check your CockroachDB logs for more details.",
  "code": 13,
  "message": "An internal server error has occurred. Please check your CockroachDB logs for more details.",
  "details": [
  ]
}
failed to verify response: unexpected status code: 500, body: {
  "error": "An internal server error has occurred. Please check your CockroachDB logs for more details.",
  "code": 13,
  "message": "An internal server error has occurred. Please check your CockroachDB logs for more details.",
  "details": [
  ]
}
failed to verify response: unexpected status code: 500, body: {
  "error": "An internal server error has occurred. Please check your CockroachDB logs for more details.",
  "code": 13,
  "message": "An internal server error has occurred. Please check your CockroachDB logs for more details.",
  "details": [
  ]
}
failed to verify response: unexpected status code: 500, body: {
  "error": "An internal server error has occurred. Please check your CockroachDB logs for more details.",
  "code": 13,
  "message": "An internal server error has occurred. Please check your CockroachDB logs for more details.",
  "details": [
  ]
}
failed to verify response: unexpected status code: 500, body: {
  "error": "An internal server error has occurred. Please check your CockroachDB logs for more details.",
  "code": 13,
  "message": "An internal server error has occurred. Please check your CockroachDB logs for more details.",
  "details": [
  ]
}
failed to verify response: unexpected status code: 500, body: {
  "error": "An internal server error has occurred. Please check your CockroachDB logs for more details.",
  "code": 13,
  "message": "An internal server error has occurred. Please check your CockroachDB logs for more details.",
  "details": [
  ]
}
failed to verify response: unexpected status code: 500, body: {
  "error": "An internal server error has occurred. Please check your CockroachDB logs for more details.",
  "code": 13,
  "message": "An internal server error has occurred. Please check your CockroachDB logs for more details.",
  "details": [
  ]
}
test artifacts and logs in: /artifacts/db-console/mixed-version-endpoints/cpu_arch=arm64/run_1
```

Parameters:
 - <code>arch=arm64</code>
 - <code>cloud=aws</code>
 - <code>coverageBuild=false</code>
 - <code>cpu=4</code>
 - <code>encrypted=false</code>
 - <code>fs=ext4</code>
 - <code>localSSD=true</code>
 - <code>mvtDeploymentMode=system-only</code>
 - <code>mvtVersions=v25.2.2 → master</code>
 - <code>runtimeAssertionsBuild=false</code>
 - <code>ssd=0</code>
<details><summary>Help</summary>
<p>

See: [roachtest README](https://github.com/cockroachdb/cockroach/blob/master/pkg/cmd/roachtest/README.md)

See: [How To Investigate \(internal\)](https://cockroachlabs.atlassian.net/l/c/SSSBr8c7)

_Grafana is not yet available for aws clusters_</p>
</details>
<details><summary>Same failure on other branches</summary>
<p>

- #148875 roachtest: db-console/mixed-version-endpoints failed [C-test-failure O-roachtest O-robot T-observability branch-release-25.3]
</p>
</details>
/cc @cockroachdb/obs-prs
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*db-console/mixed-version-endpoints.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/bazci/githubpost/issues)

</sub>

### PR DESCRIPTION
**Pull request by aa-joshi**
Previously, readAllEntriesFromFile was returning an error if the log file contains the malformed log entry. The malformed log entry primarily could be the unexpected panic log. This would result in failure in fetching the logs from file. This was inadequate because single log line can cause failure in reading rest of the logs which are with valid format. To address this, this patch skips the malformed log entries during decode and only valid log lines are returned.

Fixes: #149866
Informs: https://github.com/cockroachdb/cockroach/issues/151493
Release note: None

### CODE REVIEW

**Review by arjunmahishi — APPROVED** [review]
Change looks good. Can we add a test for this? 
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/152973#-:-OZOOHQxAXha5Jc7zZ0f:bo8quqy)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @Abhinav1299 and @angles-n-daemons)

File: pkg/util/log/file_api.go [hunk 1]
```diff
@@ -429,6 +429,13 @@ func readAllEntriesFromFile(
 			if err == io.EOF {
 				break
 			}
+
+			// skip the malformed log entry. This is primarily observed in the
+			// panic which is unstructured.
+			// See: https://github.com/cockroachdb/cockroach/issues/151493
+			if errors.Is(err, ErrMalformedLogEntry) {
```
Comment (Abhinav1299) [inline pkg/util/log/file_api.go:436]: Should we append a warning in `entries` indicating a malformed log entry is encountered before skipping it?

**Review by aa-joshi — COMMENTED** [review]
The current fetch is tightly coupled with the logs emitted with CRDB cluster flows. I did spend some time to append unstructured log in existing setup but no luck. We'll add test in subsequent interactions if we see any issues with functionality.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/152973#-:-OZOU5Tc1iXRlWrest0f:b-cwephu)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @angles-n-daemons)

File: pkg/util/log/file_api.go (hunk 1 above)
Comment (aa-joshi) [reply pkg/util/log/file_api.go:436]: This function is used to read logs from file and used as API.  It is in log package itself. I think we should avoid log generation during reading the logs from file. Right now, it has been observed in a test. If we see it as regular occurrence of missing logs then we should come up with better approach.

**Review by aa-joshi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/152973)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @Abhinav1299 and @angles-n-daemons)

File: pkg/util/log/file_api.go (hunk 1 above)
Comment (aa-joshi) [reply pkg/util/log/file_api.go:436]: This function is used to read logs from file and used as API. It is in log package itself. I think we should avoid log generation during reading the logs from file. Right now, it has been observed in a test. If we see it as regular occurrence of missing logs then we should come up with better approach.
