### PR TITLE
sql: disallow creation of interleaved partitioned indexes

### LINKED ISSUE #60699: sql: panic when attempting to create partitioned interleaved indexes
I think the solution is to just disallow creating these, given that interleaving is deprecated.

```
root@127.0.0.1:50155/defaultdb> create table a (a int primary key);
CREATE TABLE

Time: 3ms total (execution 3ms / network 0ms)

root@127.0.0.1:50155/defaultdb> create table b (b int primary key, a int references a (a));
CREATE TABLE

Time: 37ms total (execution 9ms / network 28ms)

root@127.0.0.1:50155/defaultdb> create index i2 on b (a) interleave in parent a (a)
partition by list (a) (partition part1 VALUES IN (1));
*
* ERROR: [n1,client=127.0.0.1:50156,hostssl,user=root] Queued as error a83d84364a2f453388b87b97469952e7
*
ERROR: internal error: table descriptor is not valid: cannot set a zone config for interleaved index i2; set it on the root of the interleaved hierarchy instead
tabledesc.Mutable: {ID: 53, Version: 2, ModificationTime: "1613593140.315237000,0", ParentID: 50, ParentSchemaID: 29, State: PUBLIC, NextColumnID: 3, Columns: [{ID: 1, TypeID: 20, Null: false}, {ID: 2, TypeID: 20, Null: true}], NextFamilyID: 1, Families: [{ID: 0, Columns: [1, 2]}], Mutations: [{MutationID: 1, Direction: ADD, State: DELETE_ONLY, Index: {ID: 2, Unique: false, InterleaveParents: [{TableID: 52, IndexID: 1}], Columns: [{ID: 2, Dir: ASC}], ExtraColumns: [1], State: ADD, MutationID: 1}}], PrimaryIndex: 1, NextIndexID: 3, Indexes: [{ID: 1, Unique: true, Columns: [{ID: 1, Dir: ASC}]}], OutboundFKs: [{OriginTableID: 53, OriginColumns: [2], ReferencedTableID: 52, ReferencedColumnIDs: [1], Validity: Validated}]}
SQLSTATE: XX000
DETAIL: stack trace:
/go/src/github.com/cockroachdb/cockroach/pkg/sql/table.go:289: writeTableDescToBatch()
/go/src/github.com/cockroachdb/cockroach/pkg/sql/table.go:267: writeTableDesc()
/go/src/github.com/cockroachdb/cockroach/pkg/sql/table.go:237: writeSchemaChange()
/go/src/github.com/cockroachdb/cockroach/pkg/sql/create_table.go:1049: finalizeInterleave()
/go/src/github.com/cockroachdb/cockroach/pkg/sql/create_index.go:443: startExec()
/go/src/github.com/cockroachdb/cockroach/pkg/sql/plan.go:506: func2()
/go/src/github.com/cockroachdb/cockroach/pkg/sql/walk.go:119: func1()
/go/src/github.com/cockroachdb/cockroach/pkg/sql/walk.go:298: visitInternal()
/go/src/github.com/cockroachdb/cockroach/pkg/sql/walk.go:86: visit()
/go/src/github.com/cockroachdb/cockroach/pkg/sql/walk.go:50: walkPlan()
/go/src/github.com/cockroachdb/cockroach/pkg/sql/plan.go:509: startExec()
/go/src/github.com/cockroachdb/cockroach/pkg/sql/plan_node_to_row_source.go:125: Start()
/go/src/github.com/cockroachdb/cockroach/pkg/sql/execinfra/processorsbase.go:774: Run()
/go/src/github.com/cockroachdb/cockroach/pkg/sql/flowinfra/flow.go:392: Run()
/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsql_running.go:422: Run()
/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsql_running.go:1002: PlanAndRun()
/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:1001: execWithDistSQLEngine()
/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:872: dispatchToExecutionEngine()
/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:639: execStmtInOpenState()
/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:114: execStmt()
/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:1465: func1()
/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:1467: execCmd()
/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:1391: run()
/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:508: ServeConn()
/go/src/github.com/cockroachdb/cockroach/pkg/sql/pgwire/conn.go:630: func1()
/usr/local/go/src/runtime/asm_amd64.s:1357: goexit()

HINT: You have encountered an unexpected error.

Please check the public issue tracker to check whether this problem is
already tracked. If you cannot find it there, please report the error
with details by creating a new issue.

If you would rather not post publicly, please contact us directly
using the support form.

We appreciate your feedback.
```

### PR DESCRIPTION
**Pull request by mgartner**
Previously, creating interleaved partitioned indexes panicked. This
commit disallows their creation to prevent panicking.

Fixes #60699

Release justification: This is a low risk change that prevents panics
when attempting to create interleaved partitioned tables.

Release note (bug fix): Creating interleaved partitioned indexes is now
disallowed. Previously, the database would crash when trying to create
one.

### CODE REVIEW

**Review by otan — APPROVED** [review]

File: pkg/sql/create_index.go [hunk 1]
```diff
@@ -425,6 +425,10 @@ func (n *createIndexNode) startExec(params runParams) error {
 	}
 
 	if n.n.Interleave != nil {
+		if n.n.PartitionByIndex != nil {
```
Comment (otan) [inline pkg/sql/create_index.go:428]: oh, you also need to do this for `ALTER TABLE ... PARTITION BY ....`

Comment (mgartner) [reply pkg/sql/create_index.go:428]: That would partition the primary index, not the secondary index, right? It seems to work fine, from some simple testing.

**Review by otan — APPROVED** [review]
> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/61106)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @otan and @postamar)

**Review by RaduBerinde — APPROVED** [review]

**Comment by mgartner** [comment]
TFTR!

bors r+
