### PR TITLE
sql/backfill: Make all columns accessible when checking for uniqueness

### LINKED ISSUE #83076: Unable to add unique expression index on REGIONAL BY ROW table
Reproduction steps:

* Build a 3 node cluster with localities 'central', 'east' and 'west' and then...

```
CREATE DATABASE my_db PRIMARY REGION central REGIONS west, east;
USE my_db;
CREATE TABLE users (
   id UUID PRIMARY KEY DEFAULT gen_random_uuid(),                                                                                                                                    
   email STRING NOT NULL
);
ALTER TABLE users SET LOCALITY REGIONAL BY ROW;
```

Then trying this fails:

```
root@:26257/my_db> CREATE UNIQUE INDEX on users (LOWER(email));
ERROR: validate unique constraint: column "crdb_internal_idx_expr" does not exist
SQLSTATE: 42703CREATE UNIQUE INDEX on users (LOWER(email));
ERROR: validate unique constraint: column "crdb_internal_idx_expr" does not exist
SQLSTATE: 42703
```

It works fine as a REGIONAL BY TABLE, just not REGIONAL BY ROW.

However, if I leave it as REGIONAL BY TABLE, add the unique index and THEN make it regional by row, that works.

I am able to work around this by switching the table to REGIONAL BY TABLE, add the unique index and then switch it back, but this is not ideal.

Jira issue: CRDB-16846

### PR DESCRIPTION
**Pull request by Xiang-Gu**
We ran into a issue when attempting to create a unique expression index
on a REGIONAL BY table. The root cause is that when doing uniqueness
check for this index, we use `SELECT` on the accompanying expression
column, which is inaccessible.

This PR fixes this by making all the columns accessible on the existing
temporary table descriptor, a copy of the original one, but with all
mutations made public. Such a temporary descriptor is only used
internally for validation purpose so it's safe to do so.

Release note (bug fix): fixes the issue when creating a unique,
expression index on a REGIONAL BY table. 

Fix: #83076

### CODE REVIEW

File: pkg/sql/backfill.go [hunk 1]
```diff
@@ -1868,6 +1868,16 @@ func countIndexRowsAndMaybeCheckUniqueness(
...
 			return 0, err
 		}
+		// Mark all the columns accessible if they are not. This is to fix a bug when attempting to create a unique,
+		// expression index on a REGIONAL BY table -- the accompanying expression column is inaccessible but later
+		// we check for uniqueness on this column via a SQL `SELECT` query, which of course then errors out. Such a fix
+		// is safe since this copy ('fakeDesc') is only used internally for validation.
+		// See https://github.com/cockroachdb/cockroach/issues/83076 for details.
+		for i, col := range fakeDesc.TableDesc().Columns {
+			if col.Inaccessible {
+				fakeDesc.TableDesc().Columns[i].Inaccessible = false
```
Comment (postamar) [inline pkg/sql/backfill.go:1878]: Here `fakeDesc` is the return value of `tableDesc.MakeFirstMutationPublic` which is of type `catalog.TableDescriptor` which could be immutable as well as mutable. As it turns out, it's actually a mutable table descriptor right now but this is not guaranteed, and if it returns an immutable this code most likely won't work anymore.

I recommend getting a mutable descriptor beforehand:
```
mut, ok := fakeDesc.(*tabledesc.Mutable)
if !ok {
  mut = tabledesc.NewBuilder(fakeDesc.TableDesc()).BuildCreatedMutableTable()
}
for i := range mut.Columns {
  if col := &mut.Columns[i]; col.Inaccessible {
    col.Inaccessible = false
  }
}
desc = mut.ImmutableCopy()
```

File: pkg/sql/backfill.go [hunk 2]
```diff
@@ -1868,6 +1868,16 @@ func countIndexRowsAndMaybeCheckUniqueness(
 		if err != nil {
 			return 0, err
 		}
+		// Mark all the columns accessible if they are not. This is to fix a bug when attempting to create a unique,
+		// expression index on a REGIONAL BY table -- the accompanying expression column is inaccessible but later
+		// we check for uniqueness on this column via a SQL `SELECT` query, which of course then errors out. Such a fix
```
Comment (postamar) [inline pkg/sql/backfill.go:1873]: > which of course then errors out

I didn't find that to be obvious, to be honest. I had to dig down to `duplicateRowQuery` to understand why it errors out specifically in the case of REGIONAL BY ROW tables.

File: pkg/ccl/multiregionccl/multiregion_test.go [hunk 3]
```diff
@@ -160,3 +161,21 @@ func TestGlobalReadsAfterEnterpriseDisabled(t *testing.T) {
...
+	_, sqlDB, cleanup := multiregionccltestutils.TestingCreateMultiRegionCluster(
+		t, 3 /* numServers */, base.TestingKnobs{},
+	)
+	defer cleanup()
+	tdb := sqlutils.MakeSQLRunner(sqlDB)
+
+	tdb.Exec(t, `CREATE DATABASE test_db PRIMARY REGION "us-east1" REGIONS "us-east2"`)
+	tdb.Exec(t, `USE test_db`)
+	tdb.Exec(t, `CREATE TABLE t(s STRING) LOCALITY REGIONAL BY ROW`)
+	tdb.Exec(t, `CREATE UNIQUE INDEX idx ON t(lower(s))`)
```
Comment (postamar) [inline pkg/ccl/multiregionccl/multiregion_test.go:180]: Could this be a logic test instead? That would be preferable, if possible.

**Review by postamar — COMMENTED** [review]
This makes sense. I have only minor comments to make.

File: pkg/ccl/multiregionccl/multiregion_test.go (hunk 3 above)
Comment (otan) [reply pkg/ccl/multiregionccl/multiregion_test.go:180]: +1, the `regional_by_row` logic tests should setup a multi-region cluster.

**Review by Xiang-Gu — COMMENTED** [review]
Thanks and I've addressed the comments. RFAL again!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/83125#-:-N5BZSN2DZYFMxKLwVvf:bccvg88)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @otan, and @postamar)

___
*[`pkg/sql/backfill.go` line 1873 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/83125#-N55k9LwTGLPw9t7agmh-r1-1873:-N5BSQyT83NKW8uLHo7L:bqw6ov1) ([raw file](https://github.com/cockroachdb/cockroach/blob/5090aa9ccc589e4aa6d0eb7f76a6b80400092f19/pkg/sql/backfill.go#L1873)):*
<details><summary><i>Previously, postamar (Marius Posta) wrote…</i></summary><blockquote>

> which of course then errors out

I didn't find that to be obvious, to be honest. I had to dig down to `duplicateRowQuery` to understand why it errors out specifically in the case of REGIONAL BY ROW tables.
</blockquote></details>

sorry about this. Updated comments!
___
*[`pkg/sql/backfill.go` line 1875 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/83125#-N55k9LwTGLPw9t7agmh-r1-1875:-N5BSjfq3tQ_coEUed5r:b-7rl0jd) ([raw file](https://github.com/cockroachdb/cockroach/blob/5090aa9ccc589e4aa6d0eb7f76a6b80400092f19/pkg/sql/backfill.go#L1875)):*
<details><summary><i>Previously, postamar (Marius Posta) wrote…</i></summary><blockquote>

nit: the style guide asks that comment lines be limited 80 characters in length.
</blockquote></details>

done.
___
*[`pkg/sql/backfill.go` line 1878 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/83125#-N55k9LwTGLPw9t7agmh-r1-1878:-N5BSnEh22DnLwR-zdAk:b-7rl0jq) ([raw file](https://github.com/cockroachdb/cockroach/blob/5090aa9ccc589e4aa6d0eb7f76a6b80400092f19/pkg/sql/backfill.go#L1878)):*
<details><summary><i>Previously, postamar (Marius Posta) wrote…</i></summary><blockquote>

Here `fakeDesc` is the return value of `tableDesc.MakeFirstMutationPublic` which is of type `catalog.TableDescriptor` which could be immutable as well as mutable. As it turns out, it's actually a mutable table descriptor right now but this is not guaranteed, and if it returns an immutable this code most likely won't work anymore.

I recommend getting a mutable descriptor beforehand:
```
mut, ok := fakeDesc.(*tabledesc.Mutable)
if !ok {
  mut = tabledesc.NewBuilder(fakeDesc.TableDesc()).BuildCreatedMutableTable()
}
for i := range mut.Columns {
  if col := &mut.Columns[i]; col.Inaccessible {
    col.Inaccessible = false
  }
}
desc = mut.ImmutableCopy()
```
</blockquote></details>

done!
___
*[`pkg/ccl/multiregionccl/multiregion_test.go` line 180 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/83125#-N55k9LwTGLPw9t7agmg-r1-180:-N5BZ3TY3KjZVZQl5kYw:bn4tm8r) ([raw file](https://github.com/cockroachdb/cockroach/blob/5090aa9ccc589e4aa6d0eb7f76a6b80400092f19/pkg/ccl/multiregionccl/multiregion_test.go#L180)):*
<details><summary><i>Previously, otan (Oliver Tan) wrote…</i></summary><blockquote>

+1, the `regional_by_row` logic tests should setup a multi-region cluster.
</blockquote></details>

Done! Thanks for the lead.

**Review by postamar — APPROVED** [review]
