### PR TITLE
Close old connections when reconnecting

### LINKED ISSUE #1825: RPC client leaks connections
After running a three node cluster for some time, cockroach processes appear to hit open file limits due to a connection leak in RPC client:

Log message primary node:
`I0727 14:15:26.445935 40534 server.go:1775  http: Accept error: accept tcp 127.0.0.1:8081: too many open files; retrying in 1s`

Log message on secondary node:
`W0727 14:21:26.097987 40560 rpc/tls.go:57  connecting via tcp to localhost:8081 without TLS
W0727 14:21:26.098967 40560 rpc/client.go:219  unexpected EOF`

`lsof` on any of the processes is filled with TCP connections.

### PR DESCRIPTION
**Pull request by tamird**
Closes #1825.

OK, so I think this fixes the issue. I tried in vain to find a way to test this, but it seems that the reflection facilities in Go are just not sufficient for this purpose. I confirmed the behaviour locally with `lsof`.

### CODE REVIEW

File: rpc/client.go [hunk 1]
```diff
@@ -135,8 +134,8 @@ func NewClient(addr net.Addr, context *Context) *Client {
 	context.Stopper.RunWorker(func() {
 		c.runHeartbeat(retryOpts, context.Stopper.ShouldStop())
 
-		if client := c.conn.Load().(internalConn).client; client != nil {
-			client.Close()
+		if conn := (*internalConn)(atomic.LoadPointer(&c.conn)); conn != nil {
```
Comment (spencerkimball) [inline rpc/client.go]: Move this repeated access pattern into a separate accessor method.

Comment (tamird) [inline rpc/client.go]: Done.

**Comment by spencerkimball** [comment]
LGTM

**Comment by tschottdorf** [comment]
LGTM
