### PR TITLE
sql: fix UPSERT fast path regression

### LINKED ISSUE #13437: sql: UPSERT fast-path broken
Consider a simple table:

```
CREATE TABLE IF NOT EXISTS test.kv (
  k BIGINT NOT NULL PRIMARY KEY,
  v BYTES NOT NULL
)
```

The query `UPSERT INTO test.kv (k, v) VALUES (1, 'hello'::bytes)` should hit the UPSERT fast-path in which we blindly put the values. The fast-path is controlled by the conditional at https://github.com/cockroachdb/cockroach/blob/master/pkg/sql/tablewriter.go#L230:

```
	allColsIdentityExpr := len(tu.ri.insertCols) == len(tu.tableDesc.Columns) &&
		tu.evaler != nil && tu.evaler.isIdentityEvaler()
	if len(tu.tableDesc.Indexes) == 0 && allColsIdentityExpr {
		// Do fast-path
	}
```

But we're not taking the fast-path because `allColsIdentityExpr` is false. And that variable is false because `tu.evaler.isIdentityEvaler()` is false. Following this down we hit the code at https://github.com/cockroachdb/cockroach/blob/master/pkg/sql/upsert.go#L135-L149:

```
	helper.allExprsIdentity = true
	for i, expr := range evalExprs {
		// analyzeExpr above has normalized all direct column names to ColumnItems.
		c, ok := expr.(*parser.ColumnItem)
		if !ok {
			helper.allExprsIdentity = false
			break
		}
		if len(c.Selector) > 0 ||
			!c.TableName.TableName.Equal(upsertExcludedTable.TableName) ||
			c.ColumnName.Normalize() != parser.ReNormalizeName(updateCols[i].Name) {
			helper.allExprsIdentity = false
			break
		}
	}
```

This code always sets `helper.allExprsIdentity` to true because `evalExprs` contains `*parser.IndexedVar` exprs, not `*parser.ColumnItem`. Consulting with @danhhz, this likely regressed at some point.

In addition to fixing the regression, it would be good to add a test. Perhaps something based on `EXPLAIN(PLAN)`. At the moment `EXPLAIN(PLAN)` for the above UPSERT query doesn't show enough details of what is going on. It definitely doesn't show the scan that is being performed. That too is a deficiency that should be fixed.

Cc @knz

### PR DESCRIPTION
**Pull request by danhhz**
And add a test to prevent future regressions.

A second bug was unearthed which caused the upsert fast path to be
incorrect during schema changes. This was caught by the schema change
tests when the regression was fixed.

Closes #13437.

cc @petermattis

---
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/13488)

### CODE REVIEW

File: pkg/sql/tablewriter.go [hunk 1]
```diff
@@ -226,7 +226,10 @@ func (tu *tableUpserter) init(txn *client.Txn) error {
 	tu.indexKeyPrefix = sqlbase.MakeIndexKeyPrefix(tu.tableDesc, tu.tableDesc.PrimaryIndex.ID)
 
 	allColsIdentityExpr := len(tu.ri.insertCols) == len(tu.tableDesc.Columns) &&
-		tu.evaler != nil && tu.evaler.isIdentityEvaler()
+		tu.evaler != nil && tu.evaler.isIdentityEvaler() &&
+		// Disable the upsert fast path when columns or indexes are being added
+		// or dropped.
```
Comment (petermattis) [inline pkg/sql/tablewriter.go]: This is mildly unfortunate as the fast-path is ~2x faster than the slow-path. So adding a column will cause performance to temporarily drop in half? Is there any hope to fix this eventually? Perhaps file an issue.

File: pkg/sql/upsert_test.go [hunk 2]
```diff
@@ -0,0 +1,85 @@
...
+func TestUpsertFastPath(t *testing.T) {
+	defer leaktest.AfterTest(t)()
+
+	// This filter increments scans for every ScanRequest that hits user table
+	// data.
+	var scans int64
+	filter := func(filterArgs storagebase.FilterArgs) *roachpb.Error {
+		if filterArgs.Req.Method() == roachpb.Scan &&
+			bytes.Compare(filterArgs.Req.Header().Key, keys.UserTableDataMin) >= 0 {
+			scans++
```
Comment (petermattis) [inline pkg/sql/upsert_test.go]: I'm mildly surprised this doesn't need to be done atomically.

**Review by petermattis — APPROVED** [review]
LGTM

**Comment by danhhz** [comment]
Review status: 0 of 4 files reviewed at latest revision, 2 unresolved discussions.

---

*[pkg/sql/tablewriter.go, line 231 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/13488#-KcU4Beu8mt8mO2oR2Ik-r1-231:-KcUwtChITXsmn9e5cjn:bmru4t5) ([raw file](https://github.com/cockroachdb/cockroach/blob/301ee404bbf8ff02b3e178469e0b2a7906e297bc/pkg/sql/tablewriter.go#L231)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

This is mildly unfortunate as the fast-path is ~2x faster than the slow-path. So adding a column will cause performance to temporarily drop in half? Is there any hope to fix this eventually? Perhaps file an issue.
</blockquote></details>

IIRC, when you're adding a column, you can't set it as a user while the schema change is being run. Which I think makes it impossible to fast path during that time

---

*[pkg/sql/upsert_test.go, line 42 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/13488#-KcU4Beu8mt8mO2oR2Im-r1-42:-KcUx3aaRDq5hqhDjNlY:b-rkylp6) ([raw file](https://github.com/cockroachdb/cockroach/blob/301ee404bbf8ff02b3e178469e0b2a7906e297bc/pkg/sql/upsert_test.go#L42)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

I'm mildly surprised this doesn't need to be done atomically.
</blockquote></details>

Same. atomic'd it

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/13488)*

**Comment by petermattis** [comment]
:lgtm:

---

Review status: 0 of 4 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[pkg/sql/tablewriter.go, line 231 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/13488#-KcU4Beu8mt8mO2oR2Ik-r1-231:-KcVk9FbLxLouhcFkOqA:b26xpgw) ([raw file](https://github.com/cockroachdb/cockroach/blob/301ee404bbf8ff02b3e178469e0b2a7906e297bc/pkg/sql/tablewriter.go#L231)):*
<details><summary><i>Previously, danhhz (Daniel Harrison) wrote…</i></summary><blockquote>

IIRC, when you're adding a column, you can't set it as a user while the schema change is being run. Which I think makes it impossible to fast path during that time
</blockquote></details>

Ok, thinking about it more this makes sense, but shouldn't the conditional be part of the next line. What do mutations have to do with `allColsIdentityExpr`. I think you should let the value remain the same but change the following line to:

```
if len(tu.tableDesc.Indexes) == 0 && len(tu.tableDesc.Mutations) == 0 && allColsIdentityExpr {
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/13488#-:-KcVkeKplgtofnfLvN9H:bnfp4nl)*

**Comment by knz** [comment]
:lgtm_strong: 

---

Reviewed 3 of 4 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[pkg/sql/upsert_test.go, line 43 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/13488#-KcYN5o522Tu3oeztes2:-KcYN5o522Tu3oeztes3:b-1ugng3) ([raw file](https://github.com/cockroachdb/cockroach/blob/6295cc49621639f339ca60ae921ba6ebe339a603/pkg/sql/upsert_test.go#L43)):*
> ```Go
> 		if filterArgs.Req.Method() == roachpb.Scan &&
> 			bytes.Compare(filterArgs.Req.Header().Key, keys.UserTableDataMin) >= 0 {
> 			atomic.AddUint64(&scans, 1)
> ```

That's a very clever approach to testing this. TIL!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/13488#-:-KcYNDEgSzRLvG23ldOV:b-uwkowd)*

**Comment by petermattis** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[pkg/sql/upsert_test.go, line 43 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/13488#-KcYN5o522Tu3oeztes2:-KcYNr4WgCqciY7FTDiO:b-7y2s3b) ([raw file](https://github.com/cockroachdb/cockroach/blob/6295cc49621639f339ca60ae921ba6ebe339a603/pkg/sql/upsert_test.go#L43)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

That's a very clever approach to testing this. TIL!
</blockquote></details>

Yes, I can probably enhance this to verify that we have a 1PC transaction. See #13500.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/13488)*

**Comment by danhhz** [comment]
Thanks for the reviews!

---

Review status: 3 of 4 files reviewed at latest revision, 2 unresolved discussions.

---

*[pkg/sql/tablewriter.go, line 231 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/13488#-KcU4Beu8mt8mO2oR2Ik-r1-231:-KcYQOth1UO8znzibDzU:b-ua9p60) ([raw file](https://github.com/cockroachdb/cockroach/blob/301ee404bbf8ff02b3e178469e0b2a7906e297bc/pkg/sql/tablewriter.go#L231)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

Ok, thinking about it more this makes sense, but shouldn't the conditional be part of the next line. What do mutations have to do with `allColsIdentityExpr`. I think you should let the value remain the same but change the following line to:

```
if len(tu.tableDesc.Indexes) == 0 && len(tu.tableDesc.Mutations) == 0 && allColsIdentityExpr {
```
</blockquote></details>

I was thinking of when the mutation is a column, then it can't be specified as the identity expr by the user. But you're right that indexes don't fall into this. Moved.

I also improved this comment a bit

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/13488#-:-KcYREH1ejZXzfzr_wcq:b-hlc8bm)*
