### PR TITLE
cdc: add detail to buffer closed error

### LINKED ISSUE #71796: ccl/changefeedccl: TestChangefeedColumnFamily failed
ccl/changefeedccl.TestChangefeedColumnFamily [failed](https://teamcity.cockroachdb.com/viewLog.html?buildId=3613638&tab=buildLog) with [artifacts](https://teamcity.cockroachdb.com/viewLog.html?buildId=3613638&tab=artifacts#/) on master @ [89948a5f685b0fe274df4720745401e3f3f64093](https://github.com/cockroachdb/cockroach/commits/89948a5f685b0fe274df4720745401e3f3f64093):

```
=== RUN   TestChangefeedColumnFamily
    test_log_scope.go:79: test logs captured to: /go/src/github.com/cockroachdb/cockroach/artifacts/logTestChangefeedColumnFamily044463890
    test_log_scope.go:80: use -show-logs to present logs inline
=== CONT  TestChangefeedColumnFamily
    changefeed_test.go:1350: -- test log scope end --
test logs left over in: /go/src/github.com/cockroachdb/cockroach/artifacts/logTestChangefeedColumnFamily044463890
--- FAIL: TestChangefeedColumnFamily (7.28s)
=== RUN   TestChangefeedColumnFamily/sinkless
    changefeed_test.go:1342: expected "exactly 1 column family" error got: <nil>
    --- FAIL: TestChangefeedColumnFamily/sinkless (1.25s)
```
<details><summary>Help</summary>
<p>
See also: [How To Investigate a Go Test Failure \(internal\)](https://cockroachlabs.atlassian.net/l/c/HgfXfJgM)Parameters in this failure:

- TAGS=deadlock

- GOFLAGS=-parallel=4
</p>
</details>
<details><summary>Internal log</summary>
<p>

```
danhhz marked as alumn{us,a}; ignoring
```
</p>
</details>

/cc @cockroachdb/cdc
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*TestChangefeedColumnFamily.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)
</sub>

### LINKED ISSUE #71797: ccl/changefeedccl: TestChangefeedTruncateOrDrop failed
ccl/changefeedccl.TestChangefeedTruncateOrDrop [failed](https://teamcity.cockroachdb.com/viewLog.html?buildId=3613638&tab=buildLog) with [artifacts](https://teamcity.cockroachdb.com/viewLog.html?buildId=3613638&tab=artifacts#/) on master @ [89948a5f685b0fe274df4720745401e3f3f64093](https://github.com/cockroachdb/cockroach/commits/89948a5f685b0fe274df4720745401e3f3f64093):

```
=== RUN   TestChangefeedTruncateOrDrop
    test_log_scope.go:79: test logs captured to: /go/src/github.com/cockroachdb/cockroach/artifacts/logTestChangefeedTruncateOrDrop405996707
    test_log_scope.go:80: use -show-logs to present logs inline
=== CONT  TestChangefeedTruncateOrDrop
    changefeed_test.go:2129: -- test log scope end --
test logs left over in: /go/src/github.com/cockroachdb/cockroach/artifacts/logTestChangefeedTruncateOrDrop405996707
--- FAIL: TestChangefeedTruncateOrDrop (11.18s)
=== RUN   TestChangefeedTruncateOrDrop/sinkless
    helpers_test.go:440: Running test using tenant 10
    changefeed_test.go:2109: expected ""truncate_cascade" was truncated" error got: <nil>
    --- FAIL: TestChangefeedTruncateOrDrop/sinkless (2.66s)
```
<details><summary>Help</summary>
<p>
See also: [How To Investigate a Go Test Failure \(internal\)](https://cockroachlabs.atlassian.net/l/c/HgfXfJgM)Parameters in this failure:

- TAGS=deadlock

- GOFLAGS=-parallel=4
</p>
</details>
/cc @cockroachdb/cdc HonoreDB
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*TestChangefeedTruncateOrDrop.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)
</sub>

### LINKED ISSUE #72019: ccl/changefeedccl: TestChangefeedFailOnTableOffline failed
ccl/changefeedccl.TestChangefeedFailOnTableOffline [failed](https://teamcity.cockroachdb.com/viewLog.html?buildId=3641390&tab=buildLog) with [artifacts](https://teamcity.cockroachdb.com/viewLog.html?buildId=3641390&tab=artifacts#/) on master @ [965b99b1a05eb893ee908d852680824a0bd4ffe3](https://github.com/cockroachdb/cockroach/commits/965b99b1a05eb893ee908d852680824a0bd4ffe3):

```
=== RUN   TestChangefeedFailOnTableOffline
    test_log_scope.go:79: test logs captured to: /go/src/github.com/cockroachdb/cockroach/artifacts/logTestChangefeedFailOnTableOffline714112923
    test_log_scope.go:80: use -show-logs to present logs inline
=== CONT  TestChangefeedFailOnTableOffline
    changefeed_test.go:1502: -- test log scope end --
test logs left over in: /go/src/github.com/cockroachdb/cockroach/artifacts/logTestChangefeedFailOnTableOffline714112923
--- FAIL: TestChangefeedFailOnTableOffline (32.56s)
=== RUN   TestChangefeedFailOnTableOffline/webhook/import_fails_changefeed
    changefeed_test.go:1458: timed out waiting for changefeed to fail
        --- FAIL: TestChangefeedFailOnTableOffline/webhook/import_fails_changefeed (30.40s)
=== RUN   TestChangefeedFailOnTableOffline/webhook
    --- FAIL: TestChangefeedFailOnTableOffline/webhook (30.55s)
```
<details><summary>Help</summary>
<p>
See also: [How To Investigate a Go Test Failure \(internal\)](https://cockroachlabs.atlassian.net/l/c/HgfXfJgM)Parameters in this failure:

- GOFLAGS=-parallel=4
</p>
</details>
/cc @cockroachdb/cdc stevendanna
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*TestChangefeedFailOnTableOffline.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)
</sub>

### PR DESCRIPTION
**Pull request by HonoreDB**
When a kvfeed closes the buffer it's writing to due to an expected error,
such as a schema change, the reader may return ErrBufferClosed before the
error has propagated to be available to the caller of Get(), leading to a
race condition. Rather than force the caller to wait for an error it knows
is coming, we can decorate the ErrBufferClosed with the reason.

Fixes #71796
Fixes #71797 
Fixes #72019

Release note (bug fix): Fixed a race condition that could have caused core changefeeds whose targeted table became invalid to not explain why when shutting down.

### CODE REVIEW

**Review by miretskiy — CHANGES_REQUESTED** [review]
> Reviewed 3 of 8 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/72490)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @HonoreDB and @miretskiy)

___
*[pkg/ccl/changefeedccl/changefeed_processors.go, line 447 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/72490#-Mo02DzXEM2lHA2VLeWA:-Mo02DzY6oSrDQJ-Dvp1:b12qrj) ([raw file](https://github.com/cockroachdb/cockroach/blob/c4f7087787d0fbef4e665699cb527520faba85eb/pkg/ccl/changefeedccl/changefeed_processors.go#L447)):*
> ```Go
> 		}
> 		if err := ca.tick(); err != nil {
> 			if errors.Is(err, kvevent.ErrBufferClosed) {
> ```

Should we consider changing `ErrBufferClosed` from being a sentinel error to being a "true" error w/ additional methods?
Something like:
```
type ErrBufferClosed struct {
  reason error
}
// ... other methods required for error interface

func (e ErrBufferClosed) IsRestartRequested() bool {
   ...
}
```

then here we could do something like:

`if e := (*ErrBufferClosed)(nil); errors.As(err, &e) &&  e.IsRestartRequested() ....1
___
*[pkg/ccl/changefeedccl/kvevent/event.go, line 47 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/72490#-Mo01hqI1uq4ZgS4Xppf:-Mo01hqI1uq4ZgS4Xppg:biyg87z) ([raw file](https://github.com/cockroachdb/cockroach/blob/c4f7087787d0fbef4e665699cb527520faba85eb/pkg/ccl/changefeedccl/kvevent/event.go#L47)):*
> ```Go
> 	Drain(ctx context.Context) error
> 	// Close closes this writer. reason may be added as a detail to ErrBufferClosed.
> 	Close(ctx context.Context, reason error) error
> ```

I would prefer to have this method renamed `CloseWithReason`.

Perhaps even define a
```
var NormalRestartReason error
```
so that this "error" may be passed when we want to restart due to normal
activity (i.e. schema change).

**Comment by HonoreDB** [comment]
___
*[pkg/ccl/changefeedccl/changefeed_processors.go, line 447 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/72490#-Mo02DzXEM2lHA2VLeWA:-Mo0KhPPE9iPz2bQ3uSe:b-y6tq0a) ([raw file](https://github.com/cockroachdb/cockroach/blob/c4f7087787d0fbef4e665699cb527520faba85eb/pkg/ccl/changefeedccl/changefeed_processors.go#L447)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

Should we consider changing `ErrBufferClosed` from being a sentinel error to being a "true" error w/ additional methods?
Something like:
```
type ErrBufferClosed struct {
  reason error
}
// ... other methods required for error interface

func (e ErrBufferClosed) IsRestartRequested() bool {
   ...
}
```

then here we could do something like:

`if e := (*ErrBufferClosed)(nil); errors.As(err, &e) &&  e.IsRestartRequested() ....1
</blockquote></details>

That did seem more natural to me but I was nervous about how that would work with marshalling in mixed versions; would I need to keep both the error type and the old sentinel error around?

**Comment by miretskiy** [comment]
> That did seem more natural to me but I was nervous about how that would work with marshalling in mixed versions; would I need to keep both the error type and the old sentinel error around?

Do we ever marshal that error? change frontier detects these things by watching frontier.  Afaik, we never serialize this error message in any way...

File: pkg/ccl/changefeedccl/kvevent/event.go [hunk 1]
```diff
@@ -23,7 +23,22 @@ import (
...
 // ErrBufferClosed is returned by Readers when no more values will be
 // returned from the buffer.
-var ErrBufferClosed = errors.New("buffer closed")
+type ErrBufferClosed struct {
+	reason error
+}
+
+// Error() implements the error interface
+func (e ErrBufferClosed) Error() string {
+	return "buffer closed"
```
Comment (stevendanna) [inline pkg/ccl/changefeedccl/kvevent/event.go:32]: Should we include the message from the reason here?

File: pkg/ccl/changefeedccl/changefeed_processors.go [hunk 2]
```diff
@@ -444,17 +444,22 @@ func (ca *changeAggregator) Next() (rowenc.EncDatumRow, *execinfrapb.ProducerMet
 			return ca.ProcessRowHelper(ca.resolvedSpanBuf.Pop()), nil
 		}
 		if err := ca.tick(); err != nil {
-			if errors.Is(err, kvevent.ErrBufferClosed) {
+			var e kvevent.ErrBufferClosed
+			if errors.As(err, &e) {
```
Comment (stevendanna) [inline pkg/ccl/changefeedccl/changefeed_processors.go:448]: I think that `errors.Is` knows how to walk up this unwrap chain:

https://github.com/cockroachdb/errors/blob/72ec75208141a2b67e79909b28aea29ed2189108/markers_api.go#L35
https://github.com/cockroachdb/errors/blob/72ec75208141a2b67e79909b28aea29ed2189108/markers/markers.go#L51-L54

so you may be able to simplify some of this.

**Review by stevendanna — COMMENTED** [review]
Glad to see this taken care of!

File: pkg/ccl/changefeedccl/changefeed_processors.go (hunk 2 above)
Comment (HonoreDB) [reply pkg/ccl/changefeedccl/changefeed_processors.go:448]: I need to check both levels of error, so I can't simplify it too much, but I've added an `Is` below.

File: pkg/ccl/changefeedccl/kvevent/event.go (hunk 1 above)
Comment (HonoreDB) [reply pkg/ccl/changefeedccl/kvevent/event.go:32]: This string is only being used as a sentinel error, it's the reason that'll end up being displayed.

**Review by HonoreDB — COMMENTED** [review]
> Dismissed @miretskiy from a discussion.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/72490)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @miretskiy and @stevendanna)

___
*[pkg/ccl/changefeedccl/changefeed_processors.go, line 447 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/72490#-Mo02DzXEM2lHA2VLeWA:-MoEfX0e6ijPe7Y4nXzD:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/c4f7087787d0fbef4e665699cb527520faba85eb/pkg/ccl/changefeedccl/changefeed_processors.go#L447)):*
<details><summary><i>Previously, HonoreDB (Aaron Zinger) wrote…</i></summary><blockquote>

That did seem more natural to me but I was nervous about how that would work with marshalling in mixed versions; would I need to keep both the error type and the old sentinel error around?
</blockquote></details>

Done.
___
*[pkg/ccl/changefeedccl/kvevent/event.go, line 47 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/72490#-Mo01hqI1uq4ZgS4Xppf:-MoEfZO9DXlK366F9OdX:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/c4f7087787d0fbef4e665699cb527520faba85eb/pkg/ccl/changefeedccl/kvevent/event.go#L47)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

I would prefer to have this method renamed `CloseWithReason`.

Perhaps even define a
```
var NormalRestartReason error
```
so that this "error" may be passed when we want to restart due to normal
activity (i.e. schema change).
</blockquote></details>

Done.

**Comment by HonoreDB** [comment]
I think the build failures here are now just the ones we're also seeing intermittently on master, although it's hard to be sure. Ready for re-review.

**Review by stevendanna — APPROVED** [review]

**Review by miretskiy — APPROVED** [review]
> Reviewed 5 of 7 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/72490)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @miretskiy and @stevendanna)

___
*[pkg/ccl/changefeedccl/changefeed_processors.go, line 448 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/72490#-MnlgbRAfKwQ0X20ZAci-r2-448:-MoFFJfs1F-mddC4OwTu:b-g7aqxt) ([raw file](https://github.com/cockroachdb/cockroach/blob/ba5c8d875e298d09a1b9d2786e8082f28d4dec1e/pkg/ccl/changefeedccl/changefeed_processors.go#L448)):*
<details><summary><i alt="summary">Quoted 7 lines of code…</i></summary>

> ```
> 			if errors.As(err, &e) {
> 				// ErrBufferClosed is a signal that
> 				// our kvfeed has exited expectedly.
> 				err = e.Unwrap()
> 				if errors.Is(err, kvevent.ErrNormalRestartReason) {
> 					err = nil
> 				}
> ```
</details>


i Guess that's why I was suggesting that we add a method on the ErrBufferClosed error.
```
func (e ErrBufferClosed) IsNormalRestart() bool {
   return e.reason == nil
}
```
so that you don't need to do any additional unwrapping.

**Comment by HonoreDB** [comment]
bors r=[miretskiy, stevendanna]
