### PR TITLE
kvcoord: flush write buffer in separate batch when required

### LINKED ISSUE #150239: kvcoord: buffered writes may produce batch invalid batch
**Describe the problem**

Batches with a WaitPolicy of SkipLocked are not allowed to contain non-scan requests.  However, with the addition of the buffering of replicated locking requests, a replicated locking request could result in a buffer flush if the expected response size is above the max buffer size.  The flushed batch would thus have a SkipLocked wait policy and any previously buffered writes. This request would fail during request evaluation in DistSender. As a result no incorrect results would be produced, but the user may see their queries unnecessarily fail with buffered writes enabled.

Jira issue: CRDB-52619

Epic CRDB-49088

### PR DESCRIPTION
**Pull request by stevendanna**
Batches with a WaitPolicy of SkipLocked are not allowed to contain requests other than Get, Scan, ReverseScan, QueryIntent and EndTxn. With the addition of the buffering of replicated locking requests, a Get, Scan, or ReverseScan request could force us to flush our buffer, producing a batch that violates this prohibition.

The result is an error returned to the user.

Here, we account for this case by flushing the buffer in a separate batch when required.

Fixes #150239

Epic: none

### CODE REVIEW

**Comment by stevendanna** [comment]
This is a not-for-backport change for the issue with skip-locked.  Given that we have a good amount of time to bake, it seemed like we'd be better off for the version on master not not be setting-gated.

**Review by miraradeva — COMMENTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/150276)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @arulajmani)

___
*[`pkg/kv/kvclient/kvcoord/txn_interceptor_write_buffer.go` line 1722 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/150276#-OVIToJg6Cn7_024asv4:-OVIToJg6Cn7_024asv5:bnsdvyi) ([raw file](https://github.com/cockroachdb/cockroach/blob/68eacb86e39ee87906cedfe09f9090091ab1f062/pkg/kv/kvclient/kvcoord/txn_interceptor_write_buffer.go#L1722)):*
> ```Go
> 	// order but the iterator above returns data in key order. Here we re-sort it
> 	// which is unfortunate but required unless we make a change to the pipeliner.
> 	slices.SortFunc(reqs, func(a kvpb.RequestUnion, b kvpb.RequestUnion) int {
> ```

I know this is not part of this PR, but just wondering if this sort matches other request sorting we do elsewhere. It would be good to have a helper to do this.
___
*[`pkg/kv/kvclient/kvcoord/txn_interceptor_write_buffer.go` line 1741 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/150276#-OVIU5EO9BCI1SD7EWXi:-OVIU5EP1BIbcFDl80PP:b-9nog3v) ([raw file](https://github.com/cockroachdb/cockroach/blob/68eacb86e39ee87906cedfe09f9090091ab1f062/pkg/kv/kvclient/kvcoord/txn_interceptor_write_buffer.go#L1741)):*
> ```Go
> 		flushBatch := ba.ShallowCopy()
> 		flushBatch.WaitPolicy = 0
> 		flushBatch.Requests = reqs
> ```

Doesn't `reqs` include the flush requests and also the original batch requests? I was under the impression that we want to send the flush-only requests separately, and then the batch-only requests below.

Maybe a unit test can help see exactly what's in each batch?

**Review by stevendanna — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/150276)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @arulajmani and @miraradeva)

___
*[`pkg/kv/kvclient/kvcoord/txn_interceptor_write_buffer.go` line 1722 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/150276#-OVIToJg6Cn7_024asv4:-OVIvw_O39tJbpGenOGm:b-o58smn) ([raw file](https://github.com/cockroachdb/cockroach/blob/68eacb86e39ee87906cedfe09f9090091ab1f062/pkg/kv/kvclient/kvcoord/txn_interceptor_write_buffer.go#L1722)):*
<details><summary><i>Previously, miraradeva (Mira Radeva) wrote…</i></summary><blockquote>

I know this is not part of this PR, but just wondering if this sort matches other request sorting we do elsewhere. It would be good to have a helper to do this.
</blockquote></details>

I think it does not. It additionally sorts on key with some other callers don't do. I agree we should unify them.
___
*[`pkg/kv/kvclient/kvcoord/txn_interceptor_write_buffer.go` line 1741 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/150276#-OVIU5EO9BCI1SD7EWXi:-OVIwZOA8MoLu4XMdzzt:b-wdpvku) ([raw file](https://github.com/cockroachdb/cockroach/blob/68eacb86e39ee87906cedfe09f9090091ab1f062/pkg/kv/kvclient/kvcoord/txn_interceptor_write_buffer.go#L1741)):*
<details><summary><i>Previously, miraradeva (Mira Radeva) wrote…</i></summary><blockquote>

Doesn't `reqs` include the flush requests and also the original batch requests? I was under the impression that we want to send the flush-only requests separately, and then the batch-only requests below.

Maybe a unit test can help see exactly what's in each batch?
</blockquote></details>

I don't think so, it will only include the previously buffered requests because this flush method is only called before we add anything to the buffer from the current batch.  But, you are right that really we should have some more explicit unit tests around this that shows the two batches that get created and validates them. When taking another look, I also noted we over allocate the req's slice above in this case.

**Comment by stevendanna** [comment]
@miraradeva I've updated this with a unit test as well and some code to avoid the over allocation. Should be ready for another look.

**Review by miraradeva — APPROVED** [review]
:lgtm: Thanks for adding the test!

> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/150276#-:-OWVl1cN9f7fPuuvgbbn:b-pdmsbk)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @arulajmani)

File: pkg/kv/kvclient/kvcoord/txn_interceptor_write_buffer.go [hunk 1]
```diff
@@ -1776,16 +1784,31 @@ func (twb *txnWriteBuffer) flushBufferAndSendBatch(
...
-	br.Responses = br.Responses[numRevisionsBuffered:]
-	return br, nil
+		ba.UpdateTxn(br.Txn)
+		return twb.wrapped.SendLocked(ctx, ba)
+	} else {
+		ba = ba.ShallowCopy()
+		ba.Requests = append(reqs, ba.Requests...)
+		br, pErr := twb.wrapped.SendLocked(ctx, ba)
+		if pErr != nil {
+			return nil, twb.adjustErrorUponFlush(ctx, numRevisionsBuffered, pErr)
```
Comment (miraradeva) [inline pkg/kv/kvclient/kvcoord/txn_interceptor_write_buffer.go:1805]: Sorry, one more thing I just noticed.

Should this adjustment be done above, right after the flush batch?

Comment (stevendanna) [reply pkg/kv/kvclient/kvcoord/txn_interceptor_write_buffer.go:1805]: Good callout as it is worth thinking through again. In the case of a a two-batch flush, here was my thinking about each batch:

1) The `flushBatch` only includes things from the buffer.  The buffer is only modified on the return path, so none of the requests in it line up to the requests in the caller's batch. So in that case we unconditionally nil out the error index.

2) The next batch is the caller-supplied batch. In this case, all of the errors should line up exactly, since we aren't touching the batch (other than updating the txn), so we don't have to adjust anything.

Let me know if you think any of that is in error.

Comment (miraradeva) [reply pkg/kv/kvclient/kvcoord/txn_interceptor_write_buffer.go:1805]: Makes sense. So if we split the batch, we don't really need to call `adjustErrorUponFlush`? Maybe it's worth mentioning in a comment too.

**Comment by stevendanna** [comment]
bors r=miraradeva
