### PR TITLE
c-deps: bump rocksdb for multiple backported PRs

### LINKED ISSUE #3840: Failed tests (11329):
The following test appears to have failed:

[#11329](https://circleci.com/gh/cockroachdb/cockroach/11329):

```

```
Please assign, take a look and update the issue accordingly.

### PR DESCRIPTION
**Pull request by ajkr**
Includes the following changes, all of which have landed upstream.

- cockroachdb/rocksdb#27: "ldb: set `total_order_seek` for scans"
- cockroachdb/rocksdb#28: "Fix #3840: only `SyncClosedLogs` for multiple CFs"
- cockroachdb/rocksdb#29: "Optionally wait on bytes_per_sync to smooth I/O"
- cockroachdb/rocksdb#30: "Option string/map/file can set env from object registry"

Also made the RocksDB changes that we decided in #34897:

- Do not sync WAL before installing flush result. This is achieved by backporting cockroachdb/rocksdb#28; no configuration change is necessary.
- Do not sync WAL ever for temp stores. This is achieved by setting `wal_bytes_per_sync = 0`.
- Limit size of final syncs when generating SSTs. This is achieved by backporting cockroachdb/rocksdb#29 and turning it on with `strict_bytes_per_sync = true`.

Release note: None

### CODE REVIEW

File: c-deps/libroach/options.cc [hunk 1]
```diff
@@ -163,11 +163,21 @@ rocksdb::Options DBMakeOptions(DBOptions db_opts) {
...
+  // Enabling `strict_bytes_per_sync` prevents the situation where an SST is
+  // generated fast enough that the async writeback submissions fall behind.
+  // It enforces we wait for any previous `bytes_per_sync` sync to finish before
+  // issuing any future sync. That way we prevent situations where a huge amount
+  // of data gets written out all at once upon finishing a file (the final sync
+  // covers all the data, not just a range of size `bytes_per_sync`).
+  options.strict_bytes_per_sync = true;
+  // Do not sync the WAL periodically. We sync it every write already by calling
+  // `FlushWAL(true)` on non-temp stores. On the temp store we do not intend to
+  // sync WAL ever, so setting it to zero is fine there too.
```
Comment (petermattis) [inline c-deps/libroach/options.cc]: While we don't intend to sync the WAL on temp-stores, I wonder if not syncing can run into problems where the WAL dirty data forces the OS to flush. Hopefully we're deleting the WAL before that happens, though. Ok, I just talked myself into being ok with this.

**Review by petermattis — APPROVED** [review]
LGTM
