### PR TITLE
storage: fix `CheckSSTConflicts` intent conflict above MVCC range tombstone

### LINKED ISSUE #93934: storage: `CheckSSTConflicts` fails to handle intents above MVCC range keys
Adding `AddSSTable` support for kvnemesis (#89145) uncovered a bug in `CheckSSTConflicts` intent handling: an intent above an MVCC range tombstone would be considered a point key covered by the MVCC range tombstone due to its 0-valued timestamp, and thus not processed as an intent.

Jira issue: CRDB-22606

Epic CRDB-20465

### PR DESCRIPTION
**Pull request by erikgrinaker**
`CheckSSTConflicts` could fail to handle a point key collision with an intent written above an MVCC range tombstone, because the intent was considered to be deleted by the MVCC range tombstone.

This patch makes `MVCCRangeKeyStack.Covered()` consider a timestamp of 0 (i.e. an intent) as being above all range keys, because intents must be above all range keys by definition. Otherwise, this condition in `CheckSSTConflicts` would consider the intent as a point key deleted by an MVCC range tombstone, and therefore ignored:

```go
extValueDeletedByRange := extHasRange && extHasPoint && extRangeKeys.Covers(extKey)
```

`AddSSTable` operations are only used on offline tables, so this won't affect transaction isolation for ongoing transactions. However, it is possible (but unlikely) for a committed but unresolved write intent left behind by a past transaction to not be considered for conflict handling, and for `AddSSTable` to write below it.

Resolves #93934.

Release note (bug fix): When experimental MVCC range tombstones are enabled (they're disabled by default), a bulk ingestion (e.g. an import) could fail to take a committed-but-unresolved write intent into account during conflict checks when written above an MVCC range tombstone. It was therefore possible in very rare circumstances for the ingestion to write a value below the timestamp of the committed intent, causing the ingested value to disappear.

### CODE REVIEW

File: pkg/storage/mvcc_key.go [hunk 1]
```diff
@@ -705,8 +707,10 @@ func (v MVCCRangeKeyVersions) CloneInto(c *MVCCRangeKeyVersions) {
 }
 
 // Covers returns true if any version in the stack is above the given timestamp.
+// A timestamp of 0 (i.e. an intent) is considered to be above all timestamps,
+// and thus not covered by any range key.
 func (v MVCCRangeKeyVersions) Covers(ts hlc.Timestamp) bool {
-	return !v.IsEmpty() && ts.LessEq(v[0].Timestamp)
+	return !v.IsEmpty() && !ts.IsEmpty() && ts.LessEq(v[0].Timestamp)
```
Comment (itsbilal) [inline pkg/storage/mvcc_key.go:713]: Good catch!

**Review by itsbilal — APPROVED** [review]
Thanks for fixing this! LGTM.

**Comment by erikgrinaker** [comment]
TFTR!

bors r+
