### PR TITLE
roachtest: retry transient errors in cdc/multiple-schema-changes

### LINKED ISSUE #155830: roachtest: cdc/multiple-schema-changes failed
roachtest.cdc/multiple-schema-changes [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/20632967?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/20632967?buildTab=artifacts#/cdc/multiple-schema-changes) on release-24.3 @ [e00bb13b460c97fc32fa760d2e554d9fc5f64b88](https://github.com/cockroachdb/cockroach/commits/e00bb13b460c97fc32fa760d2e554d9fc5f64b88):

```
(test_runner.go:1306).runTest: test timed out (1h0m0s)
test artifacts and logs in: /artifacts/cdc/multiple-schema-changes/cpu_arch=arm64/run_1
```

Parameters:
 - <code>arch=arm64</code>
 - <code>cloud=gce</code>
 - <code>coverageBuild=false</code>
 - <code>cpu=16</code>
 - <code>encrypted=false</code>
 - <code>fs=ext4</code>
 - <code>localSSD=false</code>
 - <code>runtimeAssertionsBuild=false</code>
 - <code>ssd=0</code>
<details><summary>Help</summary>
<p>

See: [roachtest README](https://github.com/cockroachdb/cockroach/blob/master/pkg/cmd/roachtest/README.md)

See: [How To Investigate \(internal\)](https://cockroachlabs.atlassian.net/l/c/SSSBr8c7)

See: [Grafana](https://go.crdb.dev/roachtest-grafana/teamcity-20632967/cdc-multiple-schema-changes/1761117997055/1761121755428)

</p>
</details>
/cc @cockroachdb/cdc
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*cdc/multiple-schema-changes.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/bazci/githubpost/issues)

</sub>

Jira issue: CRDB-55642

### LINKED ISSUE #163154: roachtest: cdc/multiple-schema-changes failed
roachtest.cdc/multiple-schema-changes [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyAwsBazel/21079984?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyAwsBazel/21079984?buildTab=artifacts#/cdc/multiple-schema-changes) on release-25.4 @ [793a72339ad4d0f06887492472921a59622362c4](https://github.com/cockroachdb/cockroach/commits/793a72339ad4d0f06887492472921a59622362c4):

```
(test_runner.go:1452).runTest: test timed out (1h0m0s)
test artifacts and logs in: /artifacts/cdc/multiple-schema-changes/cpu_arch=arm64/run_1
```

Parameters:
 - <code>arch=arm64</code>
 - <code>cloud=aws</code>
 - <code>coverageBuild=false</code>
 - <code>cpu=16</code>
 - <code>encrypted=false</code>
 - <code>fs=ext4</code>
 - <code>localSSD=true</code>
 - <code>metamorphicWriteBuffering=true</code>
 - <code>runtimeAssertionsBuild=false</code>
 - <code>ssd=0</code>
<details><summary>Help</summary>
<p>

See: [roachtest README](https://github.com/cockroachdb/cockroach/blob/master/pkg/cmd/roachtest/README.md)

See: [How To Investigate \(internal\)](https://cockroachlabs.atlassian.net/l/c/SSSBr8c7)

_Grafana is not yet available for aws clusters_</p>
</details>
<details><summary>Same failure on other branches</summary>
<p>

- #158462 roachtest: cdc/multiple-schema-changes failed [A-cdc C-test-failure O-roachtest O-robot P-3 T-cdc X-duplicate branch-release-24.3.24-rc]
- #155830 roachtest: cdc/multiple-schema-changes failed [A-cdc C-test-failure O-roachtest O-robot P-3 T-cdc X-duplicate branch-release-24.3]
</p>
</details>
/cc @cockroachdb/cdc
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*cdc/multiple-schema-changes.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/bazci/githubpost/issues)

</sub>

Jira issue: CRDB-60081

### PR DESCRIPTION
**Pull request by rharding6373**
The cdc/multiple-schema-changes roachtest used ExecMultiple to run ALTER TABLE DROP col statements, which fatals on any error with no retry. A transient "connection refused" error on any ALTER causes the test to never reach the highwater check, leading to a confusing timeout.

Replace ExecMultiple with individual SucceedsSoon retry loops for each ALTER statement. Also handle the UndefinedColumn error case where a previous attempt succeeded at the KV level but the connection dropped before the response was returned.

Fixes: #155830
Fixes: #163154

Co-Authored-By: roachdev-claude <roachdev-claude-bot@cockroachlabs.com>

Release note: None

### CODE REVIEW

File: pkg/cmd/roachtest/tests/cdc.go [hunk 1]
```diff
@@ -2025,11 +2027,24 @@ func runCDCMultipleSchemaChanges(ctx context.Context, t test.Test, c cluster.Clu
 		fmt.Sprintf("CREATE CHANGEFEED FOR %s INTO 'null://'", strings.Join(tableNames, ", ")),
 	).Scan(&jobID)
 
-	alterStmts := []string{"SET sql_safe_updates = false"}
 	for _, tableName := range tableNames {
-		alterStmts = append(alterStmts, fmt.Sprintf(`ALTER TABLE %s DROP col`, tableName))
+		alterStmt := fmt.Sprintf(`ALTER TABLE %s DROP col`, tableName)
```
Comment (jeffswenson) [inline pkg/cmd/roachtest/tests/cdc.go]: nit: if we are going to retry the alter, we can use an idempotent sql statement which avoids the need to examine the error.
```
ALTER TABLE %s DROP COLUMN IF EXISTS col;
```

Comment (jeffswenson) [inline pkg/cmd/roachtest/tests/cdc.go]: The artifacts have gc'd so I can't dig into this, but I'm skeptical of fixing this with a retry. Most of the sql statements we make to the test cluster are not wrapped in retry loops. So even if this is the right fix, its not sufficient to fix the issue.

Furthermore, I don't think 'CONNECTION REFUSED' is a transient error in the context of a roachprod test. I would expect it in the context of rolling restarts, but not in a stable cluster. If we see this in a roachtest it suggests either:
1. We failed to wait for the cluster to be ready.
2. One of the nodes crashed.

File: pkg/cmd/roachtest/tests/cdc.go [hunk 2]
```diff
@@ -2025,11 +2027,24 @@ func runCDCMultipleSchemaChanges(ctx context.Context, t test.Test, c cluster.Clu
...
+		testutils.SucceedsSoon(t, func() error {
```
Comment (aerfrei) [inline pkg/cmd/roachtest/tests/cdc.go]: To me the weirdest thing about the failures we were seeing is that we don't see the errors we (presumably) got while executing these statements in ExecMultiple, instead we just see the test timeout eventually. SucceedsSoon fatals so I would think this shouldn't be an issue, but so does ExecMultiple. Any thoughts on why we saw this as a timeout? 

In the event that this retry loop still fails, I'd like to be sure we'd see a more descriptive error.

File: pkg/cmd/roachtest/tests/cdc.go (hunk 1 above)
Comment (rharding6373) [reply pkg/cmd/roachtest/tests/cdc.go]: done

File: pkg/cmd/roachtest/tests/cdc.go (hunk 2 above)
Comment (rharding6373) [reply pkg/cmd/roachtest/tests/cdc.go]: This is a good observation and relates to Jeff's point, too. I think the error you found in https://github.com/cockroachdb/cockroach/issues/153695#issuecomment-3309672838 might have been a red herring. The exec hung because it was trying to connect, then failed when the test timed out, returning "connection refused". So the real issue is what was happening that caused the connection to hang.

File: pkg/cmd/roachtest/tests/cdc.go (hunk 1 above)
Comment (rharding6373) [reply pkg/cmd/roachtest/tests/cdc.go]: I think you're right. From the little info we have on the issue at this time, it looks like 7 ALTERs succeeded, and the test hung while the 8th ALTER was trying to connect. This suggests something happened to the cluster.

One benefit of this implementation is that if it gets stuck while the ALTERs are executing, it won't wait 1h for the test to time out, but it's possible it could get stuck after and it would still take 1h to time out, so that benefit seems marginal.

Happy to close this PR if you don't think it's useful and just close the issues as not enough info, and wait to see if it happens again to reinvestigate.

**Review by rharding6373 — COMMENTED** [review]
LMK if you'd prefer to close this PR (and the related issues) as not enough info.

**Review by jeffswenson — APPROVED** [review]
LGTM
