### PR TITLE
roachtest: string match for transient errors as a fallback

### LINKED ISSUE #131094: roachtest: flake detection does not work when used with `require` API
Roachtest has automatic failure detection that relies on annotated errors to identify the types of flake, which team to assign the issue to, whether to report it or not, etc. See [github.go](https://github.com/cockroachdb/cockroach/blob/e08158eb9784e78927c960dca05879f4f3467689/pkg/cmd/roachtest/github.go#L179) for more details.

However, this does not work when the test uses the `require` API to ensure the absence of errors. For instance, if test code runs something like the following:

```go
require.NoError(t, c.SomeClusterFunction())
```

then, if `SomeClusterFunction` fails due to a flake (`registry.ErrorWithOwner` where `InfraFlake` is true), the failure will _not_ be handled as a flake. This has to do with how `require` reports errors and our implementation not being able to see the underlying error when reporting the failure.

I'm pretty sure there should be a way to fix this and support `require` in roachtests, but this will require (pun intended) some investigation.

Jira issue: CRDB-42369

### PR DESCRIPTION
**Pull request by DarrylWong**
The `require` package is commonly used through roachtest to assert that no error occured. i.e. `require.NoError(t, err)` However, this function does not preserve the error object. This causes our transient error flake detection to not work. Since `require` is an upstream dependency, we cannot easily change this.

This change adds a fallback to our flake detection that string matches for the `TRANSIENT_ERROR` message we add. If found it will mark the error as a flake to reduce noise.

However, we have seen other cases where we do not preserve the error object but the code lives somewhere that is easily changeable for us. In those cases, we ideally should fix the code instead of resorting to this fallback.

To make sure we still do that, the fallback also explicity checks for a message that `require.NoError` prepends to all errors. If we find additional cases that require this fallback, we can review and add them on a case by case basis.

Fixes: #131094
Epic: none
Release note: none

### CODE REVIEW

**Comment by DarrylWong** [comment]
First two commits are part of #132795 as the newly added tests build off of it. The core logic behind this PR is in `transientErrorOwnershipFallback` and should be reviewable without knowing the context of the other PR.

File: pkg/cmd/roachtest/test_impl.go [hunk 1]
```diff
@@ -548,6 +549,68 @@ func failuresMatchingError(failures []failure, refError any) bool {
 	return false
 }
 
+// transientErrorOwnershipFallback string matches for `TRANSIENT_ERROR` in the error
```
Comment (srosenberg) [inline pkg/cmd/roachtest/test_impl.go:552]: Nit: description is a bit fuzzy... could be made more precise. Specifically, it's not immediately clear where this so-called "string" resides since the function signature receives `[]failure`.

File: pkg/cmd/roachtest/test_impl.go [hunk 2]
```diff
@@ -548,6 +549,68 @@ func failuresMatchingError(failures []failure, refError any) bool {
...
+// message and returns a new ErrorWithOwnership if it does.
+//
+// This is needed as the `require` package does not preserve the error object needed
+// for us to properly check if it is a transient error using `failuresMatchingError`.
+// Note we only check if we also see requireNoErrorPrefix, indicating it's an error reported
```
Comment (srosenberg) [inline pkg/cmd/roachtest/test_impl.go:557]: Nit: ideally, the function header comment shouldn't have forward references to definitions inside the func. body. I would paraphrase to make it clear that that the match is _guarded_ by the unique substring which denotes that the error originated from the `require` package.

File: pkg/cmd/roachtest/test_impl.go [hunk 3]
```diff
@@ -548,6 +549,68 @@ func failuresMatchingError(failures []failure, refError any) bool {
...
+// by the require package. If we see somewhere else that does not preserve the error object,
+// we want to investigate whether it can be fixed before resorting to this fallback.
+// See: #131094
+func transientErrorOwnershipFallback(failures []failure) *registry.ErrorWithOwnership {
+	const (
+		transientErrorRegex  = "TRANSIENT_ERROR\\((.+)\\)"
+		requireNoErrorPrefix = "Received unexpected error:"
```
Comment (srosenberg) [inline pkg/cmd/roachtest/test_impl.go:564]: Nit: ambiguous name. How about `unexpectedErrPrefix` instead? The comment explains that this is a unique prefix which the context must match. The problem with the current name is it also implies another meaning, i.e., some sort of a prefix which is used to require (i.e., assert) "no error". Maybe I'm reading too much into it? :)

File: pkg/cmd/roachtest/test_impl.go [hunk 4]
```diff
@@ -548,6 +549,68 @@ func failuresMatchingError(failures []failure, refError any) bool {
...
+	)
+
+	regex, err := regexp.Compile(transientErrorRegex)
```
Comment (srosenberg) [inline pkg/cmd/roachtest/test_impl.go:567]: Nit: the cost is O(len(transientErrorRegex)) * numTests; could lift into a global to reduce to O(len(transientErrorRegex)).

File: pkg/cmd/roachtest/test_impl.go [hunk 5]
```diff
@@ -548,6 +549,68 @@ func failuresMatchingError(failures []failure, refError any) bool {
...
+	if err != nil {
+		return nil
```
Comment (srosenberg) [inline pkg/cmd/roachtest/test_impl.go:569]: Why? We don't ever expect a compilation error here.

File: pkg/cmd/roachtest/test_impl.go [hunk 6]
```diff
@@ -548,6 +549,68 @@ func failuresMatchingError(failures []failure, refError any) bool {
...
+		// We may see `TRANSIENT_ERROR` without this prefix, but don't mark it as
+		// a flake as we may be able to fix the code that doesn't preserve the error.
+		if !strings.Contains(err.Error(), requireNoErrorPrefix) {
+			return false
+		}
+
+		if match := regex.FindString(err.Error()); match != "" {
+			problemCause := strings.TrimPrefix(match, "TRANSIENT_ERROR(")
+			problemCause = strings.TrimSuffix(problemCause, ")")
+			errWithOwner = registry.ErrorWithOwner(
```
Comment (srosenberg) [inline pkg/cmd/roachtest/test_impl.go:588]: Should we check if `problemCause` happens to be empty?

**Review by srosenberg — APPROVED** [review]
It would be good to add a (mocked) roachtest using the `require` package s.t. we have e2e coverage. Otherwise, LGTM!

File: pkg/cmd/roachtest/test_impl.go (hunk 5 above)
Comment (DarrylWong) [reply pkg/cmd/roachtest/test_impl.go]: Ah true, forgot about `MustCompile`

**Comment by DarrylWong** [comment]
>It would be good to add a (mocked) roachtest using the require package s.t. we have e2e coverage.

Good idea, added.

File: pkg/cmd/roachtest/test_test.go [hunk 7]
```diff
@@ -527,3 +528,69 @@ func TestGCESameDefaultZone(t *testing.T) {
...
+				require.NoError(t, rperrors.NewSSHError(errors.New("oops")))
+			},
+		}
+		err := runner.Run(ctx, []registry.TestSpec{mockTest}, 1, /* count */
+			defaultParallelism, copt, testOpts{}, lopt)
+		require.NoError(t, err)
+	})
+
+	// Now test that if the transient error is not handled by the `require` package,
+	// but similarly lost due to casting to a string, the test runner *won't* mark
```
Comment (srosenberg) [inline pkg/cmd/roachtest/test_test.go:575]: Nice!

**Review by srosenberg — APPROVED** [review]
LGTM

**Comment by DarrylWong** [comment]
TFTR!

bors r=srosenberg
