### PR TITLE
sql: Forbid setting  of zone config for non physical tables

### LINKED ISSUE #57478: sql: setting zone configs for non-materialized views should be forbidden
> isn't it a bug that we even allow setting zone configs on (non-materialized) views in the first place? Is there any point to this? 

_Originally posted by @lucy-zhang in https://github.com/cockroachdb/cockroach/issues/57147#issuecomment-736109675_

Description: It's currently possible to run `ALTER TABLE ... CONFIGURE ZONE` statements on views. Considering that zone configs are meant to describe the physical layout of the data in a table, it doesn't make sense to me either that executing such a statement be possible on a non-physical table.

To reproduce:
```
demo@127.0.0.1:26257/movr> CREATE VIEW v AS SELECT 1; ALTER TABLE v CONFIGURE ZONE USING gc.ttlseconds = 100000;
CONFIGURE ZONE 1
```
I would instead expect an error like this:
```
ERROR: "v" is not a table
SQLSTATE: 42809
```

Looking at https://github.com/cockroachdb/cockroach/blob/master/pkg/sql/set_zone_config.go nothing is there to indicate that this behaviour is allowed for a good reason so I'm tentatively filing this as a bug despite having only a superficial understanding of things. If it turns out that it's not a bug then perhaps adding a comment to that effect in that source file might be helpful.

### PR DESCRIPTION
**Pull request by naivcit**
Fixes #57478
Release note (sql change): Setting of zone configs for non physical tables is
now forbidden .

### CODE REVIEW

**Comment by naivcit** [comment]
cc @rafiss

File: pkg/sql/set_zone_config.go [hunk 1]
```diff
@@ -342,6 +342,12 @@ func (n *setZoneConfigNode) startExec(params runParams) error {
 		return err
 	}
 
+	// If the table descriptor is resolved but is not a
+	// physical table(stored in the kv layer) then return an error
```
Comment (otan) [inline pkg/sql/set_zone_config.go:346]: can you make this:
```
	// If the table descriptor is resolved but is not a
	// physical table then return an error.
```

File: pkg/sql/set_zone_config.go [hunk 2]
```diff
@@ -342,6 +342,12 @@ func (n *setZoneConfigNode) startExec(params runParams) error {
...
+	if table != nil && !table.IsPhysicalTable() {
+		return pgerror.Newf(pgcode.WrongObjectType, `"%v" is not a physical table`, table.GetName())
```
Comment (otan) [inline pkg/sql/set_zone_config.go:348]: can you make this 
```
		return pgerror.Newf(
   pgcode.WrongObjectType,
   "cannot set a zone configuration on virtual table %s",
   table.GetName(),
)
```

**Review by otan — COMMENTED** [review]
Thanks! I have some improvements to the rror messaging.

File: pkg/sql/set_zone_config.go [hunk 3]
```diff
@@ -342,6 +342,12 @@ func (n *setZoneConfigNode) startExec(params runParams) error {
 		return err
 	}
 
+	// If the table descriptor is resolved but is not a
+	// physical table then return an error
```
Comment (otan) [inline pkg/sql/set_zone_config.go:346]: super nit: this needs a full stop (.) at the end!

**Review by otan — APPROVED** [review]
thanks!

bors r+

**Comment by naivcit** [comment]
The test **TestDropPhysicalTableGC** involves setting up zone config for a view and since we are restricting that here so I think the test case is failing . What should we do here ? cc @otan

**Comment by otan** [comment]
i've pushed a fix. we should not apply the zone config the test attempts to set up if it's a view!
