### PR TITLE
ui: Correct responses for restricted access to non-admin users

### LINKED ISSUE #48152: UI: Non-admin users will see 500s and loading states on Databases and Events
**Describe the problem**

When visiting the "Databases" and "Events" pages of the admin UI as a user that is not part of the admin role they appear broken. 

**To Reproduce**

1. Set up secure CockroachDB cluster
2. Create a normal user `CREATE USER blah WITH PASSWORD ...`
3. Log into the Admin UI as the created user
4. Navigate to either the "Databases" or "Events" page
5. See error

**Expected behavior**
I would expect to see a banner stating that my user does not have access to the requested data.
I would also expect to see 403 responses rather than 500s.
Screen Shot 2020-04-29 at 9 30 17 AM

**Additional data / screenshots**
The events page returns a 500.
Screen Shot 2020-04-29 at 9 16 08 AM
The Databases page correctly returns a 403 but does not handle it.
Screen Shot 2020-04-29 at 9 15 28 AM

**Environment:**
 - CockroachDB version 19.2.x, V20.1.0-RC.2

**Additional context**
While debugging issues with a production cluster I noticed certain pages of the admin UI where not loading and 500s coming back from the server.
This lead me to believe that something was extremely wrong.
Another SRE was unable to reproduce the problem with an admin user which led us to the conclusion that non-admin users may be problematic.
Nothing is particularly dangerous but it is quite the red herring if a cluster is already misbehaving.

### PR DESCRIPTION
**Pull request by koorosh**
Resolves #48152, #50360

Depends on https://github.com/cockroachdb/admin-ui-components/pull/37
Depends on https://github.com/cockroachdb/yarn-vendored/pull/44

Previously, request handlers for node locations and eventslogs didn't
check if the user has an admin role or not and proceeds with an attempt to query
data from tables with granted permissions for admin users only. This
error handled as server error then.

Current change validates if a user has admin role before requesting
data from tables and responds with Permission denied error when user
doesn't have an admin role.

UI changes:
- Add InlineAlert component to display redesigned messages;

**Screens**
Single info message (Restricted permissions)
Screenshot 2020-07-02 at 18 34 03

Single error message
Screenshot 2020-07-02 at 18 41 54

Multiple error messages
Screenshot 2020-07-02 at 18 24 34

### CODE REVIEW

File: pkg/server/admin.go [hunk 1]
```diff
@@ -1494,12 +1493,13 @@ func (s *adminServer) Locations(
...
 	ctx = s.server.AnnotateCtx(ctx)
-
-	userName, err := userFromContext(ctx)
+	userName, isAdmin, err := s.getUserAndRole(ctx)
 	if err != nil {
 		return nil, err
 	}
-
+	if !isAdmin {
+		return nil, errInsufficientPrivilege
```
Comment (dhartunian) [inline pkg/server/admin.go:1501]: Wondering if the better thing to do in these cases is find a good way to pass the SQL privilege error through to the UI. Otherwise we get stuck "double checking" all these instances which is both error prone and confusing.

Did you explore that option @koorosh? I think sticking to SQL as "the truth" as much as possible will be good here because the permissions model will change in the future but as long as we use the SQL-level error the UI will always be doing the right thing.

**Review by dhartunian — CHANGES_REQUESTED** [review]

File: pkg/server/admin.go (hunk 1 above)
Comment (koorosh) [reply pkg/server/admin.go:1501]: Good question. My concern is that we have `role_members` table with an explicit `isAdmin` field to indicate users' privilege. I thought it is the source of truth right now. Will it be changed in the future?

I agree that right we don't handle permission error in a generic way with other possible SQL errors but on the other hand, restricted access for querying tables isn't the only reason for permission errors (for instance, it could be restricted depending on context).

Comment (koorosh) [reply pkg/server/admin.go:1501]: @dhartunian since last discussion, there was a change on server which introduced unified validation for admin permissions (2be60c1b) so now it returns "this operation requires admin privilege" error message from server.

current: 
```
This information is not available due to the current value of the 'server.remote_debugging.mode' setting.
```

message from server:
```
RequestError: this operation requires admin privilege
```
@Annebirzin , would it be okay to show server message instead of current one?

Comment (Annebirzin) [reply pkg/server/admin.go:1501]: @koorosh yep I think this is actually more clear than the current message

**Review by dhartunian — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/50869)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @Annebirzin, @elkmaster, and @koorosh)

___
*[pkg/server/admin.go, line 1501 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/50869#-MB9j3qTCouZfgwwf9HF-r3-1501:-MKk0OVM52cz48DudQm8:bb4uzs2) ([raw file](https://github.com/cockroachdb/cockroach/blob/7d6fb82c140d1c6bb9104970d17f39676d594c31/pkg/server/admin.go#L1501)):*
<details><summary><i>Previously, Annebirzin (Anne Birzin) wrote…</i></summary><blockquote>

@koorosh yep I think this is actually more clear than the current message 
</blockquote></details>

Sounds good @koorosh, use the new `requireAdminUser` function in these places.

**Review by dhartunian — CHANGES_REQUESTED** [review]
> Reviewed 10 of 10 files at r9, 2 of 2 files at r10, 3 of 3 files at r11, 2 of 2 files at r12, 5 of 5 files at r13.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/50869)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @Annebirzin, @elkmaster, and @koorosh)

___
*[pkg/ui/src/views/cluster/containers/events/index.tsx, line 181 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/50869#-MMrCN1bDjh2kQK2c9wP:-MMrCN1bDjh2kQK2c9wQ:b-1twitq) ([raw file](https://github.com/cockroachdb/cockroach/blob/5a4ac76ef788fdeb49837c39633f822a8da464a1/pkg/ui/src/views/cluster/containers/events/index.tsx#L181)):*
> ```XML
>           loading={!events}
>           error={lastError}
>           render={this.renderContent}
> ```

I think `renderContent` needs to be bound to `this` in this component, otherwise the Events page fails to render. Or change `renderContent` so it doesn't depend on `this.props`. I wasn't able to get it to render without doing that.
___
*[pkg/ui/src/views/shared/components/loading/loading.spec.tsx, line 19 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/50869#-MMrMMqV3MwEyjWlXplV:-MMrMMqV3MwEyjWlXplW:b-9op11i) ([raw file](https://github.com/cockroachdb/cockroach/blob/d01abd67236c0235b47fff29b8dd6bd243d17405/pkg/ui/src/views/shared/components/loading/loading.spec.tsx#L19)):*
> ```XML
> import Loading from "src/views/shared/components/loading";
> import { ReactWrapper, mount } from "enzyme";
> import { InlineAlert } from "oss/src/components/inlineAlert/inlineAlert";
> ```

remove `oss`

**Comment by koorosh** [comment]
Updated PR with fix for Events page and also updated imports to use direct imports from `@cockroachlabs/admin-ui-components`

**Review by dhartunian — COMMENTED** [review]
Does this need a version bump for `admin-ui-components` to pick up latest `Loading` version?

> Reviewed 22 of 22 files at r14.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/50869#-:-MMvjtY30FtKyxS-gNCE:b-lbo1n2)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @Annebirzin, @elkmaster, and @koorosh)

**Comment by koorosh** [comment]
> Does this need a version bump for `admin-ui-components` to pick up latest `Loading` version?
> 
> >

Correct, bumped `admin-ui-components` to the `0.1.24` version (https://github.com/cockroachdb/admin-ui-components/pull/37)

**Comment by dhartunian** [comment]
@koorosh now there's a conflict w/ `yarn-vendor` can you give that an update as well since we've merged other updates recently.

**Review by dhartunian — APPROVED** [review]
:lgtm: nice work on this!

> Reviewed 29 of 29 files at r15, 1 of 2 files at r16.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/50869#-:-MNQPNkT2Ss1SbpMYmaX:b7szsbh)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @Annebirzin, @dhartunian, @elkmaster, and @koorosh)
