### PR TITLE
roachtest/pg_regress: update and improve the runner

### LINKED ISSUE #137482: roachtest: pg_regress failed
roachtest.pg_regress [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestWeeklyBazel/18179568?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestWeeklyBazel/18179568?buildTab=artifacts#/pg_regress) on master @ [49cff91f3501494deaf038671bc643c194a0e3ca](https://github.com/cockroachdb/cockroach/commits/49cff91f3501494deaf038671bc643c194a0e3ca):

```
-+--
-+you can enable alter column type general support by running ``SET enable_experimental_alter_column_type_general = true``
  -- matview rewrite when changing access method
  CREATE MATERIALIZED VIEW heapmv USING heap AS SELECT 1 AS a;
 +ERROR:  at or near "using": syntax error
@@ -264385,14 +263589,8 @@
 +ERROR:  relation "heapmv" does not exist
  -- shouldn't trigger a table_rewrite event
  alter table rewriteme alter column foo type numeric(12,4);
-+ERROR:  ALTER COLUMN TYPE from float to decimal is only supported experimentally
-+HINT:  See: https://go.crdb.dev/issue-v/49329/_version_
-+--
-+you can enable alter column type general support by running ``SET enable_experimental_alter_column_type_general = true``
  begin;
- set timezone to 'UTC';
- alter table rewriteme alter column bar type timestamp;
-@@ -530,7 +745,6 @@
+@@ -530,7 +733,6 @@
  alter table rewriteme alter column bar type timestamptz;
  set timezone to 'Europe/London';
  alter table rewriteme alter column bar type timestamp; -- does rewrite
@@ -264400,7 +263598,7 @@
  rollback;
  -- typed tables are rewritten when their type changes.  Don't emit table
  -- name, because firing order is not stable.
-@@ -541,21 +755,52 @@
+@@ -541,21 +743,52 @@
                 pg_event_trigger_table_rewrite_reason();
  END;
  $$;
@@ -264456,7 +263654,7 @@
  CREATE TABLE event_trigger_test (a integer, b text);
  CREATE OR REPLACE FUNCTION start_command()
  RETURNS event_trigger AS $$
-@@ -563,37 +808,66 @@
+@@ -563,37 +796,66 @@
  RAISE NOTICE '% - ddl_command_start', tg_tag;
  END;
  $$ LANGUAGE plpgsql;
@@ -264532,7 +263730,7 @@
  -- Check the object addresses of all the event triggers.
  SELECT
      e.evtname,
-@@ -604,13 +878,22 @@
+@@ -604,13 +866,22 @@
      LATERAL pg_identify_object_as_address('pg_event_trigger'::regclass, e.oid, 0) as b,
      LATERAL pg_get_object_address(b.type, b.object_names, b.object_args) as a
    ORDER BY e.evtname;
If the diff is expected, copy regression.diffs from the test artifacts to pkg/cmd/roachtest/testdata/regression.diffs
test artifacts and logs in: /artifacts/pg_regress/cpu_arch=arm64/run_1
```

Parameters:
 - <code>arch=arm64</code>
 - <code>cloud=gce</code>
 - <code>coverageBuild=false</code>
 - <code>cpu=4</code>
 - <code>encrypted=false</code>
 - <code>metamorphicLeases=default</code>
 - <code>runtimeAssertionsBuild=false</code>
 - <code>ssd=0</code>
<details><summary>Help</summary>
<p>

See: [roachtest README](https://github.com/cockroachdb/cockroach/blob/master/pkg/cmd/roachtest/README.md)

See: [How To Investigate \(internal\)](https://cockroachlabs.atlassian.net/l/c/SSSBr8c7)

See: [Grafana](https://go.crdb.dev/roachtest-grafana/teamcity-18179568/pg-regress/1734159526813/1734160419269)

</p>
</details>
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*pg_regress.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/bazci/githubpost/issues)

</sub>

Jira issue: CRDB-45600

### PR DESCRIPTION
**Pull request by yuzefovich**
This PR improves the pg_regress setup by splitting the large `regression.diffs` file into a separate diff file for each sub-test which should make reviewing of the changes going forward easier. Additionally it adds automatic handling of `_version_` markers. It unskips `oidjoins` file.

It also accepts diffs that have been accumulated over the last several months. Several issues have been filed to track separately.

Please see each commit for more details.

Fixes: #137482

Release note: None

### CODE REVIEW

**Comment by yuzefovich** [comment]
Hold off on reviewing for a sec - I'll make a change so that each sub test resulted in a separate diff file.

**Comment by yuzefovich** [comment]
Ok, should be RFAL.

Note that reviewing the newly-accepted diffs in the second commit is a pain, so I'd suggest not spending lots of time on that - we do have large diffs anyway, and I filed a couple of issues for new internal errors. In other commits, only `pg_regress.go` and `lint_test.go` should have meaningful changes.

File: pkg/cmd/roachtest/tests/pg_regress.go [hunk 1]
```diff
@@ -472,6 +497,8 @@ func registerPGRegress(r registry.Registry) {
 		CompatibleClouds:  registry.AllExceptAWS,
 		Suites:            registry.Suites(registry.Weekly),
 		Leases:            registry.MetamorphicLeases,
+		// TODO(#142777): matview file results in an invalid descriptor.
+		SkipPostValidations: registry.PostValidationInvalidDescriptors,
```
Comment (rafiss) [inline pkg/cmd/roachtest/tests/pg_regress.go:501]: the bug has been fixed: https://github.com/cockroachdb/cockroach/pull/143287

**Review by mgartner — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1, 1 of 1 files at r2, 3 of 191 files at r3, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/142774#-:-OM7bKrA0VzXzRUeJc7P:bnfp4nl)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @DrewKimball, @michae2, and @yuzefovich)

**Review by DrewKimball — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1, 1 of 1 files at r2, 191 of 191 files at r3, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/142774#-:-OM88W-5BPMVY8viyW24:bnfp4nl)* status: <span>:shipit:</span> complete! 2 of 0 LGTMs obtained (waiting on @michae2 and @yuzefovich)

File: pkg/cmd/roachtest/tests/pg_regress.go (hunk 1 above)
Comment (yuzefovich) [reply pkg/cmd/roachtest/tests/pg_regress.go]: Thanks!

**Comment by yuzefovich** [comment]
TFTRs!

bors r+
