### PR TITLE
gcassert: fix issues when running under bazel

### LINKED ISSUE #65485: bazel: `TestLint/TestGCAssert` fails when run under Bazel
We see a lot of error output like this:

```
...
        ../../sql/colexec/sort.eg.go:2731:	s.sortCol.Get(s.order[j]): call was not inlined
        ../../sql/colexec/sort.eg.go:2921:	s.sortCol.Get(s.order[i]): call was not inlined
        ../../sql/colexec/sort.eg.go:2922:	s.sortCol.Get(s.order[j]): call was not inlined
        ../../sql/colexec/sort.eg.go:2990:	s.sortCol.Get(s.order[i]): call was not inlined
        ../../sql/colexec/sort.eg.go:2991:	s.sortCol.Get(s.order[j]): call was not inlined
        ../../sql/colexec/sort.eg.go:3051:	s.sortCol.Get(s.order[i]): call was not inlined
...
```

The same errors don't appear when the lint test is run outside the Bazel context. We're not sure if these errors are spurious or false alarms.

Epic CRDB-8349
Jira issue: CRDB-7629

### PR DESCRIPTION
**Pull request by healthy-pod**
This code change fixes issues when running gcassert under bazel by ensuring that we generate go and cgo files, and pass a path to C and C++ compilers to the lint test process.

With these changes,  `gcassert` can run as part of the `Lint` build config and doesn't need its own build config so the gcassert build config scripts are deleted.

Release note: None
Epic: CRDB-8349

Closes #65485

### CODE REVIEW

**Review by rickystewart — COMMENTED** [review]
What the hell is going on with the update to `dev`??

**Comment by healthy-pod** [comment]
> What the hell is going on with the update to dev??

just testing 😄

**Comment by healthy-pod** [comment]
This is ready for review. Generated code and GitHub CI failures should be fixed when I merge jordanlewis/gcassert#12 and point to it instead of my fork.

File: build/teamcity/cockroach/ci/tests/lint_impl.sh [hunk 1]
```diff
@@ -2,8 +2,14 @@
 
 set -xeuo pipefail
 
+# GCAssert requirements -- start
+PATH="$(dirname $(bazel run @go_sdk//:bin/go --run_under=realpath)):$PATH"
```
Comment (rickystewart) [inline build/teamcity/cockroach/ci/tests/lint_impl.sh:6]: `export PATH=`

File: go.mod [hunk 2]
```diff
@@ -159,7 +159,7 @@ require (
 	github.com/jackc/pgx/v5 v5.3.1
 	github.com/jaegertracing/jaeger v1.18.1
 	github.com/jordan-wright/email v4.0.1-0.20210109023952-943e75fe5223+incompatible
-	github.com/jordanlewis/gcassert v0.0.0-20221027203946-81f097ad35a0
+	github.com/jordanlewis/gcassert v0.0.0-20230607150025-9012d8e73bdd
```
Comment (rickystewart) [inline go.mod:162]: We don't need to/shouldn't be updating `gcassert` any more, right? The `bazel` patches that were applied are all faulty and we don't seem to be using them anyway.

File: pkg/cmd/generate-cgo/main.go [hunk 3]
```diff
@@ -148,11 +148,19 @@ import "C"
 			krbDir = filepath.Join(bazelBin, "c-deps/libkrb5_foreign")
 		}
 	}
-	cppFlags := fmt.Sprintf("-I%s", filepath.Join(jemallocDir, "include"))
-	ldFlags := fmt.Sprintf("-L%s -L%s", filepath.Join(jemallocDir, "lib"), filepath.Join(projDir, "lib"))
+
+	tempToPersistentDirs := make(map[string]string, 3)
```
Comment (rickystewart) [inline pkg/cmd/generate-cgo/main.go:152]: Nit: `srcToPersistentDirs` seems more appopriate as a name since these files don't come from "temporary" directories.

**Review by rickystewart — CHANGES_REQUESTED** [review]
Commit message and PR description are no longer accurate

File: pkg/cmd/generate-cgo/main.go (hunk 3 above)
Comment (healthy-pod) [reply pkg/cmd/generate-cgo/main.go]: Done

File: go.mod (hunk 2 above)
Comment (healthy-pod) [reply go.mod:162]: We still need to update gcassert to pull changes where we get the logs and can run in debug mode. In the current version we do not capture build logs.

**Comment by healthy-pod** [comment]
> Commit message and PR description are no longer accurate
Updated

**Review by rickystewart — APPROVED** [review]

**Comment by healthy-pod** [comment]
TFTR!

bors r=rickystewart

**Comment by yuzefovich** [comment]
Nice work figuring this out!
