### PR TITLE
builtins: fix memory accounting of `st_collect` and `st_makeline` aggregates

### LINKED ISSUE #109116: roachtest/sqlsmith: OOM when evaluating `st_memcollect` aggregate
roachtest.sqlsmith/setup=tpch-sf1/setting=no-mutations [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/11410901?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/11410901?buildTab=artifacts#/sqlsmith/setup=tpch-sf1/setting=no-mutations) on release-23.1.9-rc @ [a0eff4730a6500f3445ae41a3e47b34c28cf3278](https://github.com/cockroachdb/cockroach/commits/a0eff4730a6500f3445ae41a3e47b34c28cf3278):

```
(sqlsmith.go:282).func3: ping node 1: dial tcp 34.23.102.59:26257: connect: connection refused
HINT: node likely crashed, check logs in artifacts > logs/1.unredacted
previous sql:
WITH
	"w/it h😟81" ("c\vol491")
		AS (
			SELECT
				*
			FROM
				(
					VALUES
						(NULL),
						(
							'BOX(-0.22392328152777835 -0.39599448563740064,0.007659298615001586 -0.18962916840600474)':::BOX2D
						),
						(NULL),
						('BOX(-1.2996181592206124 -0.6879894787445656,-0.8318198726567448 1.3661561918143115)':::BOX2D)
				)
					AS "t'ab""208" ("c\vol491")
		),
	with82 ("c o
l492")
		AS (
			SELECT
				'01060000800900000001030000800100000004000000EE8EDE397C93F6C15973A0B62512F2C1DC4CBA3C0D85F34102999A932689FCC1A71E4587F1CE00C2008861C2878A6841920C585002260042F0F9E09155AECF412E6395762D16E0C1EE8EDE397C93F6C15973A0B62512F2C1DC4CBA3C0D85F3410103000080010000000600000066A0055862F7F9C1787A127048E0FBC102451A194DCCEBC150359F86A043D641483F7D23747AE5C1C252683D1DD4014278C3D3F7C7FED0C1EE176875D4B50042CBD15C6FA6F201C2405859FAC63DE2C14AA257008BB1F241D0F0EE4281C9C1C1BEC0C1F9EDF2FDC18839C553C60BE9415401B6DE9C3AF8C166A0055862F7F9C1787A127048E0FBC102451A194DCCEBC101030000800100000005000000509026EB4A61C8C130B1C538477CCBC1A81DF022DD67ECC188B338C652AED14170C9A70E6354E84158FCA5CA7509FE411CFF94C033BEFBC1DC06900C77A9F94114CB40866E7E01C270558B216D0AFCC148E5BB663D85F941C01B42267949B641509026EB4A61C8C130B1C538477CCBC1A81DF022DD67ECC10103000080010000000B000000A8AAF5CED9E3FEC1907B10FE4D12C0411069BFF0F3D1F9C1B0499182B2B6C741208EACCF7792B84128EBDF719CBDF34162A9E898495BF6413404002B38BEF5C156BC909429DEF3C1A8A845C54B9DFE41A6DAD70540C4F2C1640EE772C2E50042C4A3D72F238CF14180FB04C27110A1C1BCA6C45104B1F5C13C86B554A10FE741ACACC0D59F36E241CC4CE4A4773FF0411483A74637BCE341C4F0D70F89950042CACA32837BA1EDC1D483D83590DEDDC19656C96992EAF14138F7C1252B7BE8412501008413F201C2FC8B219AA4F7FC411270E88A608CFEC1E8F4A9295133FBC1302CD321BA3FEA41FC7375227AE3E8C1A8AAF5CED9E3FEC1907B10FE4D12C0411069BFF0F3D1F9C10103000080010000000600000009B9C789D31AF5C1B0B32C116CB4E241C8700D3AE4ABF4C1B6C688AB793DF4411625DC0C1BE7EEC1C650B59736FAEBC146E5814BE0BF014204FC650F2ECBFA417423CB938C7DDEC1A20E70F3EEFE01C2405FFDD936C0FF416BA82E61D688FBC1B4B8F4123758FAC1D4317A01FB97EC41A2E441A74825024209B9C789D31AF5C1B0B32C116CB4E241C8700D3AE4ABF4C10103000080010000000D0000000425781D5466FCC1A30F3A50D0EEF6C1F80E8ED0D78BF1C19CF2C4A42E48F1C13E63083BB3F8F5C1840D04622D02F141CE1D5AED752EF2C1B25DFA36DD7001C2D604160254A7F141A0AF2E8574C1D2C1AE3A080A962300C274AD289D1525DCC180484F1F566AF64194A84C53FE44F7C15C68D4513F25F8C198D01BD94E2AF541C0226A3C08FCCAC11E08B302DFE6F7C118507CBDDDC60142465343E34D7CF14106302D953A0BFBC160D0F6AE4311F141C80A030C6C56FD41C0B0034BA66DA0417E5D283E2842E9C1A6DB4E8B5F090042C0A19B458347AEC16CC046D3D2FEFDC12CC77F5756A5FC416838E437988EFF41F2972DF01DF901C25672F68FCBBDF7410F43A305E5C1F8C14122818A778801C25CA2A391BEBFE341AE16527B36C3F6C10425781D5466FCC1A30F3A50D0EEF6C1F80E8ED0D78BF1C10103000080010000000C000000C2E30622906CE1C110D5090BC3C3C5C1A0FA8BE4023BF3C1DE84B235622E00C236410617CC9FF1C130E4D0F934EDEE41D8B43BE82C61D3C15BD5741BCA6B02C26843D75FAD1FEAC19086BA3AE65ED6419CC4DAAAFCF3EAC122D5604DF983F74166B774BB8D92F9418C1EAE3FE80300C2A41D35386B6FE04194A6B14CAC99F441AC32590B7CE6DEC166A9BDE4D49B014288599043E1AFED41405ED0E2F9BABFC1A45F588CF45EFB41D69CEFD14F0CFA41A654C941EFD7F641E828DC8561E1FAC160D86E35829BE1414E5FCE529D7BF9414F9ADD2A46F301C28D7CEC4A4E9B01C2E8C3F9EC6A5CFF41E066E1654388FC4112A6ED043EDD00C26AC4F44C6A01F141C28BA91EA107FBC1C2E30622906CE1C110D5090BC3C3C5C1A0FA8BE4023BF3C10103000080010000000D000000882A8BA45D1400C2AE795B5B17FDEEC1B7A78DDAB7A8F7C10092D20BBF9BA6412427A21F87E8F5C13055C7BEE725F2C160045E14436FC541EA2EB8614EDFF1C1E049402280BFE04148FE658E15A9D0C1E0649FF12989C1C1643081906F7FFC41B8B71DCE4575E641E0113118D68BF2C10D9CBB5F157902C2286ABD3F6ED4EC41B0FAD300D26BEBC14CE26D126A5FFA41F823453D8320DB41D04BD5A6FCFFC841E0B5ED251331B3410815DB6470FEF141886F30743005E44144D7AE4D3CA5F341E891E7434F0CD6C1A456662227470242564E2260EF7B024272282D7AE182FAC15C182B13E7B7F041F89E6971FB9DF241328B96EE37A8FBC168A2FD0FF952E84172F5A8AD19CAF0412C42151DA154F4C1308804308682C94146AAB29C89D30142882A8BA45D1400C2AE795B5B17FDEEC1B7A78DDAB7A8F7C10103000080010000000B0000000144B2D1DF13F9C1D558DF67694300C27CB81B7CFB19F54158D064DA0979E94111406299CF80FEC1BA249E4A3738F4419CB74D7A22EEF4417AFBA06D843B00C2941A4B825012FC41D08AD792F6DAF141B7E3C89001D0F8C188A64183AE4AE4C1485F03E722CAF54162A22EF2313BF9C1F80B79BB1AC1FF4100CC2524235AFE41CC1344ABB182E6C188454AFCC36EEB41D408BC1A3C8AE0C1044AE506AF18FC4196F1EB87C2CCF2C1AC5AE58DA36CE5C1B8FC662E5947EC4140BEAB37292AE341060656610D34E7C14C5F0E385207EF41686FB0271ACEF5C100F91BCC92CD01C2603F80BB7650D541E34A5E86CC7100C20144B2D1DF13F9C1D558DF67694300C27CB81B7CFB19F541':::GEOMETRY
					AS "c o
l492"
			FROM
				"w/it h😟81" AS cte_ref28, defaultdb.public.part@[0] AS tab209
		)
SELECT
	st_memcollect("c'te_ref29"."c o
l492"::GEOMETRY)::GEOMETRY AS "c\\u8AE7o'l493"
FROM
	with82 AS "c'te_ref29"
WHERE
	true
GROUP BY
	"c'te_ref29"."c o
l492"
HAVING
	every(true::BOOL)::BOOL;ping node 1: dial tcp 34.23.102.59:26257: connect: connection refused
HINT: node likely crashed, check logs in artifacts > logs/1.unredacted
(test_runner.go:1120).func1: 1 dead node(s) detected
test artifacts and logs in: /artifacts/sqlsmith/setup=tpch-sf1/setting=no-mutations/run_1
```
<p>Parameters: <code>ROACHTEST_arch=amd64</code>
, <code>ROACHTEST_cloud=gce</code>
, <code>ROACHTEST_cpu=4</code>
, <code>ROACHTEST_encrypted=false</code>
, <code>ROACHTEST_ssd=0</code>
</p>
<details><summary>Help</summary>
<p>

See: [roachtest README](https://github.com/cockroachdb/cockroach/blob/master/pkg/cmd/roachtest/README.md)

See: [How To Investigate \(internal\)](https://cockroachlabs.atlassian.net/l/c/SSSBr8c7)

See: [Grafana](https://go.crdb.dev/p/roachfana/teamcity-11410901-1692596581-16-n4cpu4/1692599121543/1692599684412)

</p>
</details>
/cc @cockroachdb/sql-queries
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*sqlsmith/setup=tpch-sf1/setting=no-mutations.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)
</sub>

Jira issue: CRDB-30788

### PR DESCRIPTION
**Pull request by yuzefovich**
This commit tightens the memory accounting done by the `stCollectAgg`. This aggregate is special because it can append an arbitrary number of `geom.T` objects, and previously we didn't account for each of them as best as we could nor did we account for the overhead of the large backing slice inside of the GeometryCollection.

It also fixes the memory accounting done by the `stMakeLineAgg`. In particular, previously we only accounted for the length rather than capacity of the `float64` slice. We also incorrectly were emptying the account on `Reset` even though we're keeping the reference to the underlying slice.

These bugs seem like edge cases, so I decided to not include the release note.

Fixes: #109116.

Release note: None

### CODE REVIEW

File: pkg/sql/sem/builtins/aggregate_builtins.go [hunk 1]
```diff
@@ -858,34 +858,60 @@ func (agg *stMakeLineAgg) Add(
...
 	}
-	return nil
+}
+
+const floatSize = int64(unsafe.Sizeof(float64(0)))
+
+func (agg *stMakeLineAgg) appendFlatCoords(ctx context.Context, g geom.T) error {
+	capBefore := int64(cap(agg.flatCoords))
+	agg.flatCoords = append(agg.flatCoords, g.FlatCoords()...)
+	capAfter := int64(cap(agg.flatCoords))
```
Comment (otan) [inline pkg/sql/sem/builtins/aggregate_builtins.go:872]: should we do this to simplify the math + don't overallocate early

```go
coords := g.FlatCoords()
if err := agg.acc.Grow(ctx, floatSize*len(coords); err != nil {
   return err
}
agg.flatCoords = append(aggs.flatCoords, coords)
return nil
```

File: pkg/sql/sem/builtins/aggregate_builtins.go [hunk 2]
```diff
@@ -1048,27 +1084,49 @@ func (agg *stCollectAgg) Add(
...
+func (agg *stCollectAgg) geometryCollectionPush(
+	ctx context.Context, gc *geom.GeometryCollection, t geom.T,
+) error {
+	// geom.GeometryCollection.geoms can have non-trivial overhead, so we
+	// account for that.
+	capBefore := int64(cap(gc.Geoms()))
+	if err := gc.Push(t); err != nil {
+		return err
+	}
+	capAfter := int64(cap(gc.Geoms()))
```
Comment (otan) [inline pkg/sql/sem/builtins/aggregate_builtins.go:1103]: do you care about accounting for nested geometries? because this won't do that, e.g. `select 'geometrycollection(geometrycollection(point empty))'::geometry;`

**Review by otan — COMMENTED** [review]
some minor questions for you to consider

**Review by yuzefovich — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/109300)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @otan)

___
*[`pkg/sql/sem/builtins/aggregate_builtins.go` line 872 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/109300#gh-1302485345:-NcY0thl8GoL5hOMRrV9:bikmaq8) ([raw file](https://github.com/cockroachdb/cockroach/blob/b441460a281a48709b15225c63556c7dde3ddab1/pkg/sql/sem/builtins/aggregate_builtins.go#L872)):*
<details><summary><i>Previously, otan (Oliver Tan) wrote…</i></summary><blockquote>

should we do this to simplify the math + don't overallocate early

```go
coords := g.FlatCoords()
if err := agg.acc.Grow(ctx, floatSize*len(coords); err != nil {
   return err
}
agg.flatCoords = append(aggs.flatCoords, coords)
return nil
```
</blockquote></details>

This way we'd only be accounting for `len` rather than `cap` of the slice, and the difference can be on the order of 100k leading to under-accounting on the order of MB, so I think some extra math is worth it. After-the-fact accounting is a bit unfortunate, but we do that in many other places too, and from anecdotal evidence it's better to be precise with after-the-fact accounting rather than under-account before the allocation.
___
*[`pkg/sql/sem/builtins/aggregate_builtins.go` line 1103 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/109300#gh-1302486620:-NcY1r_yBbDogV_9_RxX:btvjpqn) ([raw file](https://github.com/cockroachdb/cockroach/blob/b441460a281a48709b15225c63556c7dde3ddab1/pkg/sql/sem/builtins/aggregate_builtins.go#L1103)):*
<details><summary><i>Previously, otan (Oliver Tan) wrote…</i></summary><blockquote>

do you care about accounting for nested geometries? because this won't do that, e.g. `select 'geometrycollection(geometrycollection(point empty))'::geometry;`
</blockquote></details>

Hm, I'm not sure whether it's important or not. `geometryCollectionPush` is called roughly from two places:
- from `Add` method directly, and in this case we already performed the accounting for each `geom.T` object being pushed, so I think we're good here
- from `multiToCollection` method, and here we're creating new `geom.T` objects, but internally they reference `flatCoords` slices from `geom.T` objects that were previously `Add`ed (for which we did the precise memory accounting). This case is a bit blurry.

I'm leaning towards keeping it as is in order to not double count stuff and since this change on its own addresses the heap profile I was looking at. WDYT?

**Review by otan — APPROVED** [review]
sgtm

**Comment by yuzefovich** [comment]
TFTR!

bors r+
