### PR TITLE
roachprod: RAID0 only network disks if both local and network are present

### LINKED ISSUE #98783: roachprod,roachtest: don't RAID0 local SSD and PD/EBS
**Describe the problem**

See https://github.com/cockroachdb/cockroach/pull/98782.

**To Reproduce**

Run the test in https://github.com/cockroachdb/cockroach/issues/97019.

**Expected**

I think RAID'ing wildly different storage media together should be a very explicit opt-in. Also, nobody will take this opt-in, so it maybe shouldn't even be possible.

When multiple EBS/PD-SSD volumes are created however, it makes some sense to RAID them together, however again I am skeptical (read: totally critical) of that being a good default.

Some discussion in https://github.com/cockroachdb/cockroach/pull/98782#issuecomment-1475600391.

Jira issue: CRDB-25519

### PR DESCRIPTION
**Pull request by nameisbhaskar**
Today, if a machine has both local and network disks, both the disks are selected for RAID'ing.

But, RAID'ing different types of disks causes performance differences.

To address this, local disks are ignored for RAID'ing only if network disks are present.

Fixes: #98783
Epic: none

### CODE REVIEW

File: pkg/roachprod/vm/aws/support.go [hunk 1]
```diff
@@ -69,7 +80,8 @@ if [ "${#disks[@]}" -eq "0" ]; then
   echo "No disks mounted, creating ${mountpoint}"
   mkdir -p ${mountpoint}
   chmod 777 ${mountpoint}
-elif [ "${#disks[@]}" -eq "1" ] || [ -n "$use_multiple_disks" ]; then
+elif [ "${#disks[@]}" -eq "1" ] || [ "${#ebs_volumes[@]}" -eq "1" ] || [ -n "$use_multiple_disks" ]; then
+	# only 1 disk or 1 ebs volume - cannot select RAID'ing
```
Comment (srosenberg) [inline pkg/roachprod/vm/aws/support.go:84]: What about the case when the second conjunct is true, i.e., `ebs_volumes` has 1, yet there are multiple disks, i.e., `disk` has > 1?

**Comment by srosenberg** [comment]
We should resolve this TODO [1] and do a full run in both GCE and AWS. Have you thought how to test this definitively? Note that the startup script is captured by the `journalctl` log (see `FetchJournalctl`). However, we don't save these _unless_ a test failed (see `collectArtifacts`). Maybe we change that behavior, at least for the test runs? This way we can post-analyze all the startup scripts to ensure there were no "funny" RAID`ing. What do you think?

[1] https://github.com/cockroachdb/cockroach/blob/41da9eccc216413c09cc66ad4c6bfa5f92c506e3/pkg/cmd/roachtest/tests/restore.go#L537-L544

**Comment by nameisbhaskar** [comment]
> We should resolve this TODO [1] and do a full (test) run in both GCE and AWS. Have you thought how to test this definitively? Note that the startup script is captured by the `journalctl` log (see `FetchJournalctl`). However, we don't save these _unless_ a test failed (see `collectArtifacts`). Maybe we change that behavior, at least for the test runs? This way we can post-analyze all the startup scripts to ensure there were no "funny" RAID`ing. What do you think?
> 
> [1]
> 
> https://github.com/cockroachdb/cockroach/blob/41da9eccc216413c09cc66ad4c6bfa5f92c506e3/pkg/cmd/roachtest/tests/restore.go#L537-L544

Regarding testing, I have tested roachprod deployment with different disk configuration. Here are the scenarios and the expected behaviour as per my understanding:
1. (local SSD = 0, Network Disk - 1) - no RAID'ing
2. (local SSD = 1, Network Disk - 0) - no RAID'ing 
4. (local SSD >= 1, Network Disk = 1) - no RAID'ing
3. (local SSD > 1, Network Disk = 0) - local SSDs selected for RAID'ing
5. (local SSD >= 0, Network Disk > 1) - network disks selected for RAID'ing
Please let me know if this is the correct assumption. Also, if there are a combination of SSDs and 1 network disk, all the disks will be mounted. Is that also the expected behaviour?

**Comment by nameisbhaskar** [comment]
made some changes to only use network disk if present:
#   (local SSD = 0, Network Disk - 1)  - no RAID'ing and mount network disk
#   (local SSD = 1, Network Disk - 0)  - no RAID'ing and mount local SSD
#   (local SSD >= 1, Network Disk = 1) - no RAID'ing and mount network disk
#   (local SSD > 1, Network Disk = 0)  - local SSDs selected for RAID'ing
#   (local SSD >= 0, Network Disk > 1) - network disks selected for RAID'ing

**Review by srosenberg — APPROVED** [review]
Looks good, thanks!

**Comment by nameisbhaskar** [comment]
Thanks for reviewing and approving the change @srosenberg !

**Comment by nameisbhaskar** [comment]
bors r=srosenberg

**Comment by renatolabs** [comment]
Nice work!

Sorry if I missed something, but should we do something for Azure as well?

**Comment by nameisbhaskar** [comment]
> Nice work!
> 
> Sorry if I missed something, but should we do something for Azure as well?

Azure does not have the RAID'ing implemented.
