### PR TITLE
workload: fix max ops

### LINKED ISSUE #142553: roachtest: kv/quiescence/nodes=3 failed [workload timeout]
**Note:** This build has runtime assertions enabled. If the same failure was hit in a run without assertions enabled, there should be a similar failure without this message. If there isn&#39;t one, then this failure is likely due to an assertion violation or (assertion) timeout.

roachtest.kv/quiescence/nodes=3 [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyAzureBazel/19045613?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyAzureBazel/19045613?buildTab=artifacts#/kv/quiescence/nodes=3) on master @ [2362ac69262c53be08f010fcde76371592d311ef](https://github.com/cockroachdb/cockroach/commits/2362ac69262c53be08f010fcde76371592d311ef):

```
(test_runner.go:1378).runTest: test timed out (3h0m0s)
test artifacts and logs in: /artifacts/kv/quiescence/nodes=3/run_1
```

Parameters:
 - <code>arch=amd64</code>
 - <code>cloud=azure</code>
 - <code>coverageBuild=false</code>
 - <code>cpu=4</code>
 - <code>encrypted=false</code>
 - <code>metamorphicBufferedSender=false</code>
 - <code>runtimeAssertionsBuild=true</code>
 - <code>ssd=0</code>
<details><summary>Help</summary>
<p>

See: [roachtest README](https://github.com/cockroachdb/cockroach/blob/master/pkg/cmd/roachtest/README.md)

See: [How To Investigate \(internal\)](https://cockroachlabs.atlassian.net/l/c/SSSBr8c7)

_Grafana is not yet available for azure clusters_</p>
</details>
/cc @cockroachdb/kv-triage
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*kv/quiescence/nodes=3.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/bazci/githubpost/issues)

</sub>

Jira issue: CRDB-48410

### PR DESCRIPTION
**Pull request by herkolategan**
This change fixes a bug introduced by #142258, that removed the done check when waiting for the worker / op functions to finish. This is fixed by cancelling the context when all operations / workers have finished as it was previously.

Fixes: #142553

Epic: None
Release note: None

### CODE REVIEW

File: pkg/workload/cli/run.go [hunk 1]
```diff
@@ -581,11 +582,16 @@ func runRun(gen workload.Generator, urls []string, dbName string) error {
 
 	everySecond := log.Every(*displayEvery)
 
-	// durationCtx implements the --duration timeout
-	durationCtx, _ := context.WithCancel(ctx) // nolint:lostcancel
+	// doneCtx implements the --duration timeout
+	doneCtx, doneCancel := context.WithCancel(ctx)
 	if *duration > 0 {
-		durationCtx, _ = context.WithTimeout(ctx, *duration+*ramp) // nolint:lostcancel
+		doneCtx, doneCancel = context.WithTimeout(ctx, *duration+*ramp)
```
Comment (golgeek) [inline pkg/workload/cli/run.go:588]: _[disclaimer]
This is 100% a personal preference that makes the logic appear much more complicated and you should probably not take it into consideration.
[/disclaimer]_

I would not override the `context.WithCancel(ctx)` here. While it is totally fine with the current logic, it might become misleading in the future when adding more code.

```
	var (
		doneCtx, timeoutCtx       context.Context
		doneCancel, timeoutCancel context.CancelFunc
	)

	doneCtx, doneCancel = context.WithCancel(ctx)
	defer doneCancel()

	if *duration > 0 {
		timeoutCtx, timeoutCancel = context.WithTimeout(doneCtx, *duration+*ramp)
		defer timeoutCancel()
	}

  go func() {
		wg.Wait()
		doneCancel()
	}()

	for {
		select {
		case <-doneCtx.Done():
			cancelWorkers()
      ...
		case <-timeoutCtx.Done():
			cancelWorkers()
      ...
		}
	}
```

This would leave a clear distinction between work is done and timeout (for logging) and for future code injected in there.

**Review by DarrylWong — APPROVED** [review]

**Review by golgeek — APPROVED** [review]

**Review by sean- — CHANGES_REQUESTED** [review]
Hold on - that last commit didn't fix one of the combinations of flag usage.

**Review by sean- — APPROVED** [review]
LGTM

File: pkg/workload/cli/run.go (hunk 1 above)
Comment (herkolategan) [reply pkg/workload/cli/run.go]: 100% agree, it's better not to override variables in conditional branches, to avoid possible confusion.
