### PR TITLE
intentresolver: fix testrace flake by extending timeouts

### LINKED ISSUE #35064: teamcity: failed test: TestCleanupIntents
The following tests appear to have failed on master (testrace): TestCleanupIntents/#02, TestCleanupIntents/#00, TestCleanupIntents/#01, TestCleanupIntents

You may want to check [for open issues](https://github.com/cockroachdb/cockroach/issues?q=is%3Aissue+is%3Aopen+TestCleanupIntents).

[#1144299](https://teamcity.cockroachdb.com/viewLog.html?buildId=1144299):

```
TestCleanupIntents/#00
--- FAIL: testrace/TestCleanupIntents/#00 (0.000s)
Test ended in panic.




TestCleanupIntents/#02
...github.com/cockroachdb/cockroach/pkg/internal/client/requestbatcher/batcher.go:187 +0x56
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunAsyncTask.func1(0xc0002a2b40, 0x16a8f80, 0xc000034118, 0xc00003c330, 0x22, 0x0, 0x0, 0xc00046c170)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:325 +0xf4
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunAsyncTask
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:320 +0x14e

goroutine 1140 [select]:
github.com/cockroachdb/cockroach/pkg/internal/client/requestbatcher.(*RequestBatcher).run(0xc0005440d0, 0x16a8f80, 0xc000034118)
	/go/src/github.com/cockroachdb/cockroach/pkg/internal/client/requestbatcher/batcher.go:368 +0x3e3
github.com/cockroachdb/cockroach/pkg/internal/client/requestbatcher.(*RequestBatcher).run-fm(0x16a8f80, 0xc000034118)
	/go/src/github.com/cockroachdb/cockroach/pkg/internal/client/requestbatcher/batcher.go:187 +0x56
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunAsyncTask.func1(0xc0002a2b40, 0x16a8f80, 0xc000034118, 0xc00003c2d0, 0x22, 0x0, 0x0, 0xc00046c0e0)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:325 +0xf4
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunAsyncTask
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:320 +0x14e

goroutine 1143 [runnable]:
github.com/cockroachdb/cockroach/pkg/internal/client/requestbatcher.(*RequestBatcher).run(0xc000544270, 0x16a8f80, 0xc000034118)
	/go/src/github.com/cockroachdb/cockroach/pkg/internal/client/requestbatcher/batcher.go:368 +0x3e3
github.com/cockroachdb/cockroach/pkg/internal/client/requestbatcher.(*RequestBatcher).run-fm(0x16a8f80, 0xc000034118)
	/go/src/github.com/cockroachdb/cockroach/pkg/internal/client/requestbatcher/batcher.go:187 +0x56
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunAsyncTask.func1(0xc0002a2b40, 0x16a8f80, 0xc000034118, 0xc00003c360, 0x22, 0x0, 0x0, 0xc00046c190)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:325 +0xf4
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunAsyncTask
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:320 +0x14e

goroutine 1116 [select]:
github.com/cockroachdb/cockroach/pkg/internal/client/requestbatcher.(*RequestBatcher).run(0xc0000a2d00, 0x16a8f80, 0xc000034118)
	/go/src/github.com/cockroachdb/cockroach/pkg/internal/client/requestbatcher/batcher.go:368 +0x3e3
github.com/cockroachdb/cockroach/pkg/internal/client/requestbatcher.(*RequestBatcher).run-fm(0x16a8f80, 0xc000034118)
	/go/src/github.com/cockroachdb/cockroach/pkg/internal/client/requestbatcher/batcher.go:187 +0x56
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunAsyncTask.func1(0xc0002a2b40, 0x16a8f80, 0xc000034118, 0xc00044e000, 0x22, 0x0, 0x0, 0xc0001e4070)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:325 +0xf4
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunAsyncTask
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:320 +0x14e

goroutine 1139 [select]:
github.com/cockroachdb/cockroach/pkg/internal/client/requestbatcher.(*RequestBatcher).run(0xc000544000, 0x16a8f80, 0xc000034118)
	/go/src/github.com/cockroachdb/cockroach/pkg/internal/client/requestbatcher/batcher.go:368 +0x3e3
github.com/cockroachdb/cockroach/pkg/internal/client/requestbatcher.(*RequestBatcher).run-fm(0x16a8f80, 0xc000034118)
	/go/src/github.com/cockroachdb/cockroach/pkg/internal/client/requestbatcher/batcher.go:187 +0x56
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunAsyncTask.func1(0xc0002a2b40, 0x16a8f80, 0xc000034118, 0xc00003c2a0, 0x22, 0x0, 0x0, 0xc00046c0d0)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:325 +0xf4
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunAsyncTask
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:320 +0x14e



TestCleanupIntents
--- FAIL: test/TestCleanupIntents (0.040s)
Test ended in panic.




TestCleanupIntents/#01
--- FAIL: testrace/TestCleanupIntents/#01 (0.000s)
Test ended in panic.




TestCleanupIntents
--- FAIL: testrace/TestCleanupIntents (0.000s)
Test ended in panic.





```

Please assign, take a look and update the issue accordingly.

### PR DESCRIPTION
**Pull request by ajwerner**
The unit tests which failed assumed that all messages intents in a single call
to ResolveIntents could be queued within the batch timeout and idle window which
is by default rather short (10 and 5 ms respectively). The testing validation
logic is rather strict and assumes that the batch will fire due to size rather
than time constraints. The fix is to allow the test to increase these values to
make the test more robust to load. Before this change the flake was reproducible
running testrace within several hundred iterations. After the test it has not
failed after running over 20k test race iterations from two concurrently running
executions.

Fixes #35064.

Release note: None

### CODE REVIEW

**Comment by tbg** [comment]
in your CI:

```
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xcf5ecb]

goroutine 1039 [running]:
testing.tRunner.func1(0xc00038f300)
	/usr/local/go/src/testing/testing.go:792 +0x387
panic(0xe6ddc0, 0x1a180a0)
	/usr/local/go/src/runtime/panic.go:513 +0x1b9
github.com/cockroachdb/cockroach/pkg/storage/intentresolver.TestCleanupIntents.func2(0xc00038f300)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/intentresolver/intent_resolver_test.go:697 +0x5b
testing.tRunner(0xc00038f300, 0xc0002647c0)
	/usr/local/go/src/testing/testing.go:827 +0xbf
created by testing.(*T).Run
	/usr/local/go/src/testing/testing.go:878 +0x35c
```

File: pkg/storage/intentresolver/intent_resolver.go [hunk 1]
```diff
@@ -82,14 +82,17 @@ const (
...
 
+var (
 	// intentResolutionBatchWait is used to configure the RequestBatcher which
 	// batches intent resolution requests across transactions. Intent resolution
 	// needs to occur in a relatively short period of time after the completion
 	// of a transaction in order to minimize the contention footprint of the write
 	// for other contending reads or writes. The chosen value was selected based
 	// on some light experimentation to ensure that performance does not degrade
-	// in the face of highly contended workloads.
+	// in the face of highly contended workloads. This setting is a var rather
```
Comment (tbg) [inline pkg/storage/intentresolver/intent_resolver.go]: I would greatly prefer if you added that to the `intentResolver` itself (unexported) instead so that your test can manipulate it directly. The pattern here is kind of dirty, and while sometimes it's the right thing to do just to "get things done" it seems that here you have everything in place to avoid it. I think your `before` would take the `*intentResolver` and `after` would go away.

**Comment by ajwerner** [comment]
TFTR! I shouldn't push PRs just before going to bed. Firstly I forgot to git add the change to fix the panic and secondly yes the injection was sloppy. 

Given that the setting is passed along to the requestbatcher which I wasn't eager to fully re-create inside of the before func. I instead exposed the parameters for batching timeout which also adds symmetry to the gc batcher. Hopefully this feels a little bit better.

**Review by tbg — APPROVED** [review]
:lgtm:, thanks for polishing this.

> I shouldn't push PRs just before going to bed

It also never works out for me when I do it.

I also agree with your comment in the commit message that if this becomes flaky again, the test should be weakened as opposed to adding hacks. But hope this just works in eternity.

> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/35085#-:-LZBp9_W8krGHPbkQ_7n:b-wljxah)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ajwerner)
