### PR TITLE
jobs, importccl: fix import job not honouring `default_int_size`

### LINKED ISSUE #67627: import pgdump: does not appear to honor sql.defaults.default_int_size or default_int_size
**Describe the problem**

When importing tables using IMPORT PGDUMP that have data types as INTEGER or INT, the import does not appear to honor the cluster setting `sql.defaults.default_int_size` (nor the session variable `default_int_size`) when translating the default integer size as described in:

https://www.cockroachlabs.com/docs/v21.1/int.html#considerations-for-64-bit-signed-integers

**To Reproduce**

Start a single-node CockroachDB instance
```
shell> cockroach start-single-node --insecure
```

Create a DDL-only SQL file to import
```
shell> mkdir -p  ./cockroach-data/extern/
shell> cat <<EOF > ./cockroach-data/extern/default_int.sql
CREATE TABLE default_int (
    id INTEGER PRIMARY KEY,
    id2 INT,
    val text
);
EOF
```

Set the default int size to 4 bytes
```
sql> set cluster setting sql.defaults.default_int_size = 4;
sql> set default_int_size = 4;
```

Create the table via the SQL CLI and observe the default int size is honored
```
sql> CREATE TABLE default_int (
    id INTEGER PRIMARY KEY,
    id2 INT,
    val text
);
CREATE TABLE

sql> \d default_int
  column_name | data_type | is_nullable | column_default | generation_expression |  indices  | is_hidden
--------------+-----------+-------------+----------------+-----------------------+-----------+------------
  id          | INT4      |    false    | NULL           |                       | {primary} |   false
  id2         | INT4      |    true     | NULL           |                       | {}        |   false
  val         | STRING    |    true     | NULL           |                       | {}        |   false
```

Create the table via IMPORT PGDUMP and observe the default size is not honored
```
sql> drop table default_int;
DROP TABLE

sql> import pgdump 'nodelocal://1/default_int.sql';
        job_id       |  status   | fraction_completed | rows | index_entries | bytes
---------------------+-----------+--------------------+------+---------------+--------
  675740487399178241 | succeeded |                  1 |    0 |             0 |     0

sql> \d default_int
  column_name | data_type | is_nullable | column_default | generation_expression |  indices  | is_hidden
--------------+-----------+-------------+----------------+-----------------------+-----------+------------
  id          | INT8      |    false    | NULL           |                       | {primary} |   false
  id2         | INT8      |    true     | NULL           |                       | {}        |   false
  val         | STRING    |    true     | NULL           |                       | {}        |   false
```

**Environment** 
```
sql> select version();
                                         version
-----------------------------------------------------------------------------------------
  CockroachDB CCL v21.1.5 (x86_64-apple-darwin19, built 2021/07/02 04:00:15, go1.15.11)
```

**What was the impact?**
For applications that are dependent on 4-byte integer sizes, and migrations from PostgreSQL, the workaround would be to either modify the pgdump file using sed, etc to change `integer` and `int` into an explicit `int4`. Or to pre-create the tables using a DDL-only pgdump, then import the data using IMPORT INTO. However this second approach requires the data to be exported from PostgreSQL in a delimited format (CSV, TSV) which is more error prone than using a native pg_dump export. Therefore, the workarounds both make the migration from PostrgreSQL to CockroachDB more complex and error prone.

Epic CRDB-8816

### PR DESCRIPTION
**Pull request by annezhu98**
Previously, when importing tables with columns of data types INT or INTEGER through `IMPORT PGDUMP`, the cluster setting `sql.defaults.default_int_size` and session variable `default_int_size` were ignored. This commit fixes the issue by propagating session data to the import job.

Resolves: #67627

Release note (bug fix): importing tables via `IMPORT PGDUMP` or `IMPORT MYSQL` should honour cluster setting `sql.defaults.default_int_size` and session variable `default_int_size`.

### CODE REVIEW

File: pkg/ccl/importccl/read_import_pgdump.go [hunk 1]
```diff
@@ -583,6 +584,18 @@ func readPostgresStmt(
 		} else {
 			schemaObjects.createTbl[schemaQualifiedName] = nil
 		}
+		for _, def := range stmt.Defs {
```
Comment (adityamaru) [inline pkg/ccl/importccl/read_import_pgdump.go:587]: Should we move this before when we store stmt in the map above? Let's also add a comment why we're doing this.

Can we use `NakedIntTypeFromDefaultIntSize` when resolving the int type?

File: pkg/jobs/jobspb/jobs.proto [hunk 2]
```diff
@@ -277,7 +277,9 @@ message ImportDetails {
     (gogoproto.customtype) = "github.com/cockroachdb/cockroach/pkg/util/uuid.UUID"
   ];
 
-  // next val: 25
+  int32 default_int_size = 25;
```
Comment (adityamaru) [inline pkg/jobs/jobspb/jobs.proto:280]: lets add a comment:
"DefaultIntSize is the integer type that a "naked" int will be resolved to during the import. This is set based on the session variable `DefaultIntSize` when the import is planned.

File: pkg/ccl/importccl/read_import_mysql.go [hunk 3]
```diff
@@ -480,6 +480,14 @@ func mysqlTableToCockroach(
 			}
 			def.DefaultExpr.Expr = expr
 		}
+		if def.Type.(*types.T).Equal(types.Int) && p != nil {
+			switch p.ExtendedEvalContext().SessionData.DefaultIntSize {
```
Comment (adityamaru) [inline pkg/ccl/importccl/read_import_mysql.go:484]: ditto as below, can we use the helper?

File: pkg/ccl/importccl/import_table_creation.go [hunk 4]
```diff
@@ -146,6 +146,7 @@ func MakeSimpleTableDescriptor(
 	tableID descpb.ID,
 	fks fkHandler,
 	walltime int64,
+	sessionData *sessiondata.SessionData,
```
Comment (adityamaru) [inline pkg/ccl/importccl/import_table_creation.go:149]: hmm I'm a little confused why we're plumbing the session data through this method. Does `DefaultIntSize` get used somewhere that stems from this method? My understanding is that by the time we reach here the `*tree.CreateTable` column definitions already have the types set to the correct int types.

We explicitly set the types for the bundle formats, do we need to do anything for `IMPORT TABLE`?

**Comment by adityamaru** [comment]
Let's also add some tests for PGDUMP, MYSQL, and IMPORT TABLE! `SHOW COLUMNS` should allow you to verify if we're respecting the session var when import is planned.

File: pkg/ccl/importccl/read_import_pgdump.go (hunk 1 above)
Comment (annezhu98) [reply pkg/ccl/importccl/read_import_pgdump.go]: Done.

File: pkg/jobs/jobspb/jobs.proto (hunk 2 above)
Comment (annezhu98) [reply pkg/jobs/jobspb/jobs.proto:283]: Done.

File: pkg/ccl/importccl/read_import_mysql.go (hunk 3 above)
Comment (annezhu98) [reply pkg/ccl/importccl/read_import_mysql.go]: Done.

File: pkg/ccl/importccl/import_table_creation.go (hunk 4 above)
Comment (annezhu98) [reply pkg/ccl/importccl/import_table_creation.go]: You're correct! We don't need to plumb session data here.

Table creation for `IMPORT TABLE` happens in the planning stage, where we have access to the session data, hence no changes are needed.

File: pkg/ccl/importccl/import_stmt_test.go [hunk 5]
```diff
@@ -7023,3 +7023,96 @@ func TestImportJobEventLogging(t *testing.T) {
...
+			// Set up clean testing environment.
+			sqlDB.Exec(t, `DROP TABLE IF EXISTS default_int`)
+
+			sqlDB.Exec(t, fmt.Sprintf("set cluster setting sql.defaults.default_int_size = %d;", test.defaultIntSize))
+			sqlDB.Exec(t, fmt.Sprintf("set default_int_size = %d;", test.defaultIntSize))
+
+			sqlDB.Exec(t, test.query, srv.URL)
+
+			// Verify that the columns have the expected data type
+			colDefs := sqlDB.QueryStr(t, "SHOW COLUMNS FROM default_int")
```
Comment (adityamaru) [inline pkg/ccl/importccl/import_stmt_test.go:7110]: can we change this query to:
`select data_type from [SHOW COLUMNS FROM default_int];`

I don't think we would see a `row_id` column since you're explicitly specifying a PK?

File: pkg/ccl/importccl/import_stmt_test.go [hunk 6]
```diff
@@ -7023,3 +7023,96 @@ func TestImportJobEventLogging(t *testing.T) {
...
+			defaultIntSize: 4,
+		},
+		{
+			name:           "import table from mysqldump with default int8",
+			query:          `IMPORT TABLE default_int FROM MYSQLDUMP ($1)`,
+			defaultIntSize: 8,
+		},
+	}
+
+	for _, test := range tests {
```
Comment (adityamaru) [inline pkg/ccl/importccl/import_stmt_test.go:7099]: can we restructure this test to loop over []int{4, 8} We can then reduce the number of `tests` to half cause we'd only have to write each case once?

Also can we add a non-bundle case too? CSV maybe? Since it'll need a separate data source (srv won't work) maybe you can just have a different `t.Run` outside this loop?

File: pkg/ccl/importccl/import_stmt_test.go [hunk 7]
```diff
@@ -7023,3 +7023,96 @@ func TestImportJobEventLogging(t *testing.T) {
 		string(jobs.StatusRunning)}
 	backupccl.CheckEmittedEvents(t, expectedStatus, beforeSecondImport.UnixNano(), jobID, "import", "IMPORT")
 }
+
+func TestImportIntCols(t *testing.T) {
```
Comment (adityamaru) [inline pkg/ccl/importccl/import_stmt_test.go:7027]: can we rename to `TestImportDefautIntSizeSetting`, thanks!

File: pkg/ccl/importccl/import_table_creation.go (hunk 4 above)
Comment (adityamaru) [reply pkg/ccl/importccl/import_table_creation.go]: 👍

File: pkg/ccl/importccl/import_stmt_test.go (hunk 5 above)
Comment (annezhu98) [reply pkg/ccl/importccl/import_stmt_test.go]: for some reason `rowid` column exists in tables created via mysql dump but not pgdump

File: pkg/ccl/importccl/import_stmt_test.go (hunk 6 above)
Comment (annezhu98) [reply pkg/ccl/importccl/import_stmt_test.go:7088]: Done.

File: pkg/ccl/importccl/import_stmt_test.go (hunk 7 above)
Comment (annezhu98) [reply pkg/ccl/importccl/import_stmt_test.go]: Done.

File: pkg/ccl/importccl/import_stmt_test.go [hunk 8]
```diff
@@ -7023,3 +7023,91 @@ func TestImportJobEventLogging(t *testing.T) {
...
+)
+CSV DATA ($1)
+`,
+			nonBundledFormat: true,
+		},
+	}
+
+	for _, test := range tests {
+		t.Run(test.name, func(t *testing.T) {
+			for _, defaultIntSize := range intSizes {
```
Comment (adityamaru) [inline pkg/ccl/importccl/import_stmt_test.go:7090]: if you move this loop header outside the t.Run closure then we can have more descriptive test names incase one of them fails.

The name would be `fmt.Sprintf("%s_intsize=%d", test.name, defaultIntSize)`

**Review by adityamaru — APPROVED** [review]
Nice work on this, LGTM bar the one comment 🙂

File: pkg/ccl/importccl/import_stmt_test.go (hunk 8 above)
Comment (annezhu98) [reply pkg/ccl/importccl/import_stmt_test.go]: Done.

**Comment by adityamaru** [comment]
Will need a rebase on master to solve the conflict. LGTM.
