### PR TITLE
server: refactor TestSpanStatsFanOutFaultTolerance

### LINKED ISSUE #128750: server: TestSpanStatsFanOutFaultTolerance failed
server.TestSpanStatsFanOutFaultTolerance [failed](https://tanzanite.cluster.engflow.com/invocations/default/74e9f517-8dbe-425f-a72f-33d8bfac47fb?testReportRun=2&testReportShard=15&testReportAttempt=1#targets-Ly9wa2cvc2VydmVyOnNlcnZlcl90ZXN0) on release-24.2 @ [b8b31aaa48e6ab9e4d4c301e1c5a739901cb72b8](https://github.com/cockroachdb/cockroach/commits/b8b31aaa48e6ab9e4d4c301e1c5a739901cb72b8):

```
=== RUN   TestSpanStatsFanOutFaultTolerance
    test_log_scope.go:170: test logs captured to: outputs.zip/logTestSpanStatsFanOutFaultTolerance558590717
    test_log_scope.go:81: use -show-logs to present logs inline
    span_stats_test.go:296: 
        	Error Trace:	github.com/cockroachdb/cockroach/pkg/server_test/pkg/server/span_stats_test.go:296
        	            				github.com/cockroachdb/cockroach/pkg/server_test/pkg/server/span_stats_test.go:331
        	Error:      	Not equal: 
        	            	expected: 3
        	            	actual  : 4
        	Test:       	TestSpanStatsFanOutFaultTolerance
    panic.go:626: -- test log scope end --
test logs left over in: outputs.zip/logTestSpanStatsFanOutFaultTolerance558590717
--- FAIL: TestSpanStatsFanOutFaultTolerance (267.52s)
=== RUN   TestSpanStatsFanOutFaultTolerance/partial-fanout-failure
    test_server_shim.go:144: cluster virtualization disabled in global scope due to issue: #76378 (expected label: C-bug)
    testing.go:1576: test executed panic(nil) or runtime.Goexit: subtest may have called FailNow on a parent test
    --- FAIL: TestSpanStatsFanOutFaultTolerance/partial-fanout-failure (127.13s)
```

Parameters:
 - <code>attempt=1</code>
 - <code>race=true</code>
 - <code>run=2</code>
 - <code>shard=15</code>
<details><summary>Help</summary>
<p>

See also: [How To Investigate a Go Test Failure \(internal\)](https://cockroachlabs.atlassian.net/l/c/HgfXfJgM)
</p>
</details>
/cc @cockroachdb/obs-prs
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*TestSpanStatsFanOutFaultTolerance.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/bazci/githubpost/issues)
</sub>

Jira issue: CRDB-41180

### LINKED ISSUE #131082: server: TestSpanStatsFanOutFaultTolerance failed
server.TestSpanStatsFanOutFaultTolerance [failed](https://tanzanite.cluster.engflow.com/invocations/default/ca1bb24e-c6ec-46cc-ba49-2dbb392d9a62?testReportRun=2&testReportShard=3&testReportAttempt=1#targets-Ly9wa2cvc2VydmVyOnNlcnZlcl90ZXN0) on master @ [c6122f6e6f0d35249a5eef8cab22db49dc43a626](https://github.com/cockroachdb/cockroach/commits/c6122f6e6f0d35249a5eef8cab22db49dc43a626):

```
=== RUN   TestSpanStatsFanOutFaultTolerance
    test_log_scope.go:170: test logs captured to: outputs.zip/logTestSpanStatsFanOutFaultTolerance2180574155
    test_log_scope.go:81: use -show-logs to present logs inline
    span_stats_test.go:314: 
        	Error Trace:	github.com/cockroachdb/cockroach/pkg/server_test/pkg/server/span_stats_test.go:314
        	            				github.com/cockroachdb/cockroach/pkg/server_test/pkg/server/span_stats_test.go:351
        	Error:      	"0" is not greater than "0"
        	Test:       	TestSpanStatsFanOutFaultTolerance
    panic.go:626: -- test log scope end --
test logs left over in: outputs.zip/logTestSpanStatsFanOutFaultTolerance2180574155
--- FAIL: TestSpanStatsFanOutFaultTolerance (702.78s)
=== RUN   TestSpanStatsFanOutFaultTolerance/partial-fanout-failure
    test_server_shim.go:144: cluster virtualization disabled in global scope due to issue: #76378 (expected label: C-bug)
    testing.go:1576: test executed panic(nil) or runtime.Goexit: subtest may have called FailNow on a parent test
    --- FAIL: TestSpanStatsFanOutFaultTolerance/partial-fanout-failure (362.81s)
```

Parameters:
 - <code>attempt=1</code>
 - <code>race=true</code>
 - <code>run=2</code>
 - <code>shard=3</code>
<details><summary>Help</summary>
<p>

See also: [How To Investigate a Go Test Failure \(internal\)](https://cockroachlabs.atlassian.net/l/c/HgfXfJgM)
</p>
</details>
<details><summary>Same failure on other branches</summary>
<p>

- #128750 server: TestSpanStatsFanOutFaultTolerance failed [C-test-failure O-robot P-2 T-observability branch-release-24.2 release-blocker]
</p>
</details>
/cc @cockroachdb/obs-prs
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*TestSpanStatsFanOutFaultTolerance.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/bazci/githubpost/issues)
</sub>

Jira issue: CRDB-42361

### PR DESCRIPTION
**Pull request by dhartunian**
No need to run this under stress or race since it's testing a manually constructed failure scenario.

Fixed incorrect `t` being used in test validations which would mask which subtest was failing.

Added more logging to test cases that have failed before.

Resolves: #128750
Resolves: #131082

Release note: None

### CODE REVIEW

File: pkg/server/span_stats_test.go [hunk 1]
```diff
@@ -402,15 +402,21 @@ func TestSpanStatsMultiStoreReplicationOff(t *testing.T) {
 func TestSpanStatsFanOutFaultTolerance(t *testing.T) {
 	defer leaktest.AfterTest(t)()
 	defer log.Scope(t).Close(t)
-	skip.UnderStressWithIssue(t, 108534)
+
+	// This test simulates a specific set of failures and verifies that
+	// the response collects them appropriately. It is flaky under stress
+	// and race.
+	skip.UnderStress(t)
+	skip.UnderRace(t)
```
Comment (kyle-a-wong) [inline pkg/server/span_stats_test.go:410]: nit: there is also skip.UnderDuress() which includes `syncutil.DeadlockEnabled`. Not sure if you want to skip under deadlock too

**Review by kyle-a-wong — APPROVED** [review]

File: pkg/server/span_stats_test.go (hunk 1 above)
Comment (dhartunian) [reply pkg/server/span_stats_test.go:410]: I'll just skip the specific scenarios that I've seen it fail under for now.
