### PR TITLE
roachtest: prevent GC on failed fixture restores

### LINKED ISSUE #160073: roachtest: lock backup fixtures from GC after failed restore
If a restore from our backup fixtures fail in a roachtest, we should flag the fixture in question to prevent it from being GC'd. This gives us a bigger window of time to investigate restore failures before the backup is cleaned up after the next fixture is generated.

Jira issue: CRDB-58143

### PR DESCRIPTION
**Pull request by kev-cao**
This commit teaches our fixture roachtests to flag fixtures for GC protection. This gives developers a larger grace period to investigate failed restore roachtests before GC deletes the fixture.

Resolves: #160073

Release note: None

### CODE REVIEW

File: pkg/cmd/roachtest/tests/restore.go [hunk 1]
```diff
@@ -873,6 +875,9 @@ func (rd *restoreDriver) run(ctx context.Context, target string) error {
 	_, err = conn.ExecContext(
 		ctx, rd.restoreCmd(ctx, target, "WITH unsafe_restore_incompatible_version"),
 	)
+	if err != nil {
+		rd.flagFixturePreventGC(ctx)
+	}
```
Comment (kev-cao) [inline pkg/cmd/roachtest/tests/restore.go:880]: It'd be nice to have a more unified interface for running a restore. We currently have `runDetached`, `run`, and `executeTestRestorePhase`.

File: pkg/roachprod/blobfixture/registry.go [hunk 2]
```diff
@@ -185,6 +185,36 @@ func (r *Registry) URI(path string) url.URL {
 	return copy
 }
 
+// OpenFixtureMeta opens an existing fixture metadata for modification.
+func (r *Registry) OpenFixtureMeta(
```
Comment (jeffswenson) [inline pkg/roachprod/blobfixture/registry.go]: It feels a little weird to me to create a ScratchHandle for an existing fixture in order to run a single command on it. What do you think of exposing a `registry.Update(metadata)` command instead of giving a way to recreate a scratch handle?

File: pkg/roachprod/blobfixture/metadata.go [hunk 3]
```diff
@@ -43,6 +43,12 @@ type FixtureMetadata struct {
 
 	// FingerprintTime is the aost used by the fingerprint command.
 	FingerprintTime string `json:"fingerprint_time,omitempty"`
+
+	// PreventGC indicates that this fixture should not be garbage collected. This
+	// can be set by tests using this fixture that want to ensure the fixture
+	// remains available for investigation purposes in the event of failure. The
+	// fixture will be subject to GC a week after this flag is set.
+	PreventGC *time.Time `json:"prevent_gc,omitempty"`
```
Comment (jeffswenson) [inline pkg/roachprod/blobfixture/metadata.go]: nit: Instead of `prevent_gc`, what do you think of the name `gc_after`? We would set it to now()+7 days instead of the time the failure occurred. Alternatively, we could name this something like `last_failure_at`.

**Review by jeffswenson — APPROVED** [review]
LGTM

File: pkg/roachprod/blobfixture/metadata.go (hunk 3 above)
Comment (kev-cao) [reply pkg/roachprod/blobfixture/metadata.go]: Hmm, I see, so that way you could combine the logic with the current 7-day logic. We'd have to put in a default for now then since the fields would be empty until all the other fixtures expire.

File: pkg/roachprod/blobfixture/registry.go (hunk 2 above)
Comment (kev-cao) [reply pkg/roachprod/blobfixture/registry.go]: I did think it was a bit off to re-use `ScratchHandle`, namely because `ScratchHandle` is mostly intended for on-creation use, since you can set `ReadyAt` and `CreatedAt`. Opening an existing fixture shouldn't expose those.

At the same time, creating another handle for it seemed like overkill. I think exposing a single method for it sounds good to me, although maybe instead of `Update`, it should be specific to laying that GC protection? ~~Given the context of the other comment, maybe `ExtendGC`?~~ Maybe `MarkFailure`

File: pkg/roachprod/blobfixture/metadata.go (hunk 3 above)
Comment (kev-cao) [reply pkg/roachprod/blobfixture/metadata.go]: After going back to the code and re-reading it, realized that I forgot that the current 7-day GC is only for leaked fixtures. There's also the GC due to obsolescence as well.

So I don't think `gc_after` is great just because it implies the fixture is kept available until then, which isn't the case.

I think going with `last_failure_at` works though.

> We would set it to now()+7 days instead of the time the failure occurred.

I do think we should set it at the time the failure occurred, because the one week grace period is to provide us enough time to investigate the failure.

**Review by jeffswenson — APPROVED** [review]
LGTM

Nice work 🥳

**Comment by kev-cao** [comment]
TFTR!

bors r=jeffswenson
