### PR TITLE
sql: skip TestShowFingerprintsDuringSchemaChange under deadlock

### LINKED ISSUE #121445: sql: TestShowTenantFingerprintsProtectsTimestamp failed
sql.TestShowTenantFingerprintsProtectsTimestamp [failed](https://tanzanite.cluster.engflow.com/invocations/default/d863d545-fae5-4177-a0f7-5ec8a17834d4?testReportRun=1&testReportShard=3&testReportAttempt=1#targets-Ly9wa2cvc3FsOnNxbF90ZXN0) on master @ [7fc4c7bcbbf0c75a62d056da0bf79a5a32714650](https://github.com/cockroachdb/cockroach/commits/7fc4c7bcbbf0c75a62d056da0bf79a5a32714650):

```
=== RUN   TestShowTenantFingerprintsProtectsTimestamp
    test_log_scope.go:170: test logs captured to: outputs.zip/logTestShowTenantFingerprintsProtectsTimestamp3949282097
    test_log_scope.go:81: use -show-logs to present logs inline
    show_fingerprints_test.go:179: 
        	Error Trace:	github.com/cockroachdb/cockroach/pkg/sql/show_fingerprints_test.go:179
        	Error:      	Received unexpected error:
        	            	TransactionRetryWithProtoRefreshError: TransactionRetryError: retry txn (RETRY_SERIALIZABLE - failed preemptive refresh due to encountered recently written committed value /Table/47/1/"\xc9"/0 @1711957719.740410065,1): "sql txn" meta={id=b27a321a key=/Table/62/1/0/0 iso=Serializable pri=0.00484297 epo=0 ts=1711957719.772835382,2 min=1711957719.665188781,0 seq=111} lock=true stat=PENDING rts=1711957719.665188781,0 wto=false gul=1711957720.165188781,0
        	Test:       	TestShowTenantFingerprintsProtectsTimestamp
    panic.go:626: -- test log scope end --
test logs left over in: outputs.zip/logTestShowTenantFingerprintsProtectsTimestamp3949282097
--- FAIL: TestShowTenantFingerprintsProtectsTimestamp (4.02s)
```

Parameters:
 - <code>attempt=1</code>
 - <code>deadlock=true</code>
 - <code>run=1</code>
 - <code>shard=3</code>
<details><summary>Help</summary>
<p>

See also: [How To Investigate a Go Test Failure \(internal\)](https://cockroachlabs.atlassian.net/l/c/HgfXfJgM)
</p>
</details>
/cc @cockroachdb/sql-queries
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*TestShowTenantFingerprintsProtectsTimestamp.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/bazci/githubpost/issues)
</sub>

Jira issue: CRDB-37265

### PR DESCRIPTION
**Pull request by navsetlur**
This test fails sometimes under the deadlock flag because the CREATE TENANT call doesn't commit its transaction in time. This causes setup to fail and has no bearing on the actual test itself. Test doesn't fail outside of this one scenario, so skipping it.

Release note: None
Fixes: https://github.com/cockroachdb/cockroach/issues/121445

### CODE REVIEW

File: pkg/sql/show_fingerprints_test.go [hunk 1]
```diff
@@ -140,6 +141,11 @@ func TestShowTenantFingerprintsProtectsTimestamp(t *testing.T) {
 	defer leaktest.AfterTest(t)()
 	defer log.Scope(t).Close(t)
 
+	// Under deadlock there isn't enough time for the CREATE TENANT txn to commit
+	// due to the intervals we lower to speed up this test. There is no difference
+	// otherwise when running this test under deadlock
+	skip.UnderDeadlockWithIssue(t, 121445, "Deadlock makes txns take too long to commit")
```
Comment (msbutler) [inline pkg/sql/show_fingerprints_test.go:147]: nit: we use the withIssue tag to track an open issue that will be closed when we remove the skip line. Since this pr just closes  121445, no need to tag it.

**Review by msbutler — APPROVED** [review]

**Comment by navsetlur** [comment]
bors r=msbutler

**Comment by navsetlur** [comment]
blathers backport 24.1
