### PR TITLE
sql: fix `SHOW SCHEMAS` database name resolution bug

### LINKED ISSUE #105906: sql: `SHOW SCHEMAS FROM db_name` resolves wrong target database
**Describe the problem**
`SHOW SCHEMAS FROM db_name` would return schemas in current database if the `db_name` is the same name as an existing schema in current database, even `db_name` is a real database name.

**To Reproduce**
```
root@localhost:26257/defaultdb> create database sc1;
CREATE DATABASE

root@localhost:26257/defaultdb> create schema sc1;
CREATE SCHEMA

root@localhost:26257/defaultdb> show schemas from sc1; -- it returns schemas from defaultdb instead of database sc1
     schema_name     | owner
---------------------+--------
  crdb_internal      | NULL
  information_schema | NULL
  pg_catalog         | NULL
  pg_extension       | NULL
  public             | admin
  sc1                | root
```

**Expected behavior**
it should only show schemas from the target database.

**Environment:**
 - any active version

Jira issue: CRDB-29266

### PR DESCRIPTION
**Pull request by andyyang890**
This patch fixes a bug in the `SHOW SCHEMAS FROM db_name` logic where a schema with the name `db_name` in the current database would result in the current database's schemas being erroneously returned instead. The logic will now simply look up the database name instead of using the schema lookup logic.

Fixes #105906 

Release note (bug fix): `SHOW SCHEMAS FROM db_name` will no longer incorrectly show schemas from the current database when the current database has a schema named `db_name`.

### CODE REVIEW

File: pkg/sql/opt/cat/catalog.go [hunk 1]
```diff
@@ -83,6 +83,14 @@ type Flags struct {
 // returned by the Resolve methods (schemas and data sources) *must* be
 // immutable after construction, and therefore also thread-safe.
 type Catalog interface {
+	// ResolveDatabase locates a database with the given name and returns it.
+	// If no name is provided, it will return the current database.
+	// An error is returned if no database with the given name exists or in the
+	// case of an empty name, there is no current database.
+	// TODO(yang): This function can be extended if needed in the future
+	// to return a new cat.Database type similar to cat.Schema.
+	ResolveDatabase(ctx context.Context, flags Flags, name string) (tree.Name, error)
```
Comment (chengxiong-ruan) [inline pkg/sql/opt/cat/catalog.go:92]: nit: I think this more a `LookupDatabaseName` than resolving :)
my 2c is that we can just call it `DatabaseExists` for now... Your call.

File: pkg/sql/logictest/testdata/logic_test/database [hunk 2]
```diff
@@ -361,3 +366,24 @@ database_name       owner     primary_region  secondary_region  regions  surviva
 ifnotexistsownerdb  testuser  NULL            NULL              {}       NULL
 
 subtest end
+
+subtest regression_105906
+
+statement ok
+CREATE SCHEMA regression_105906
```
Comment (chengxiong-ruan) [inline pkg/sql/logictest/testdata/logic_test/database:373]: Can you also add test cases where database name need to be double quoted? for example "regression 105906" ? Thanks

File: pkg/sql/opt/cat/catalog.go (hunk 1 above)
Comment (andyyang890) [reply pkg/sql/opt/cat/catalog.go]: Changed to `LookupDatabaseName`! I think `DatabaseExists` would imply it just returns a `bool` or `error`, which I also considered but it wouldn't work in this case because we want it to work for the empty string (i.e return current database name) too.

File: pkg/sql/logictest/testdata/logic_test/database (hunk 2 above)
Comment (andyyang890) [reply pkg/sql/logictest/testdata/logic_test/database:373]: Added!

**Review by chengxiong-ruan — APPROVED** [review]
LGTM!

**Comment by andyyang890** [comment]
TFTR!

bors r=chengxiong-ruan
