### PR TITLE
roachtest: update sqlalchemy roachtest to use SQLA 1.4

### LINKED ISSUE #66075: roachtest: sqlalchemy failed
roachtest.sqlalchemy [failed](https://teamcity.cockroachdb.com/viewLog.html?buildId=3047287&tab=buildLog) with [artifacts](https://teamcity.cockroachdb.com/viewLog.html?buildId=3047287&tab=artifacts#/sqlalchemy) on release-21.1 @ [00b770d51383793d83c6c886357788dc211f7158](https://github.com/cockroachdb/cockroach/commits/00b770d51383793d83c6c886357788dc211f7158):

```
The test failed on branch=release-21.1, cloud=gce:
test artifacts and logs in: /home/agent/work/.go/src/github.com/cockroachdb/cockroach/artifacts/sqlalchemy/run_1
	orm_helpers.go:178,orm_helpers.go:154,sqlalchemy.go:212,sqlalchemy.go:38,test_runner.go:767: No tests ran! Fix the testing commands.
```
<details><summary>Reproduce</summary>
<p>
<p>To reproduce, try:

```bash
# From https://go.crdb.dev/p/roachstress, perhaps edited lightly.
caffeinate ./roachstress.sh sqlalchemy
```
</p>
</p>
</details>
/cc @cockroachdb/sql-experience
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*sqlalchemy.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)
</sub>

### PR DESCRIPTION
**Pull request by arulajmani**
This was failing because we reorganized the project and bumped the
SQL Alchemy supported version to 1.4.17.

Fixes #66075

Release note: None

### CODE REVIEW

File: pkg/cmd/roachtest/sqlalchemy.go [hunk 1]
```diff
@@ -22,7 +22,7 @@ import (
 var sqlAlchemyResultRegex = regexp.MustCompile(`^(?P<test>test.*::.*::[^ \[\]]*(?:\[.*])?) (?P<result>\w+)\s+\[.+]$`)
 var sqlAlchemyReleaseTagRegex = regexp.MustCompile(`^rel_(?P<major>\d+)_(?P<minor>\d+)_(?P<point>\d+)$`)
 
-var supportedSQLAlchemyTag = "rel_1_3_24"
+var supportedSQLAlchemyTag = "rel_1_4_17"
```
Comment (rafiss) [inline pkg/cmd/roachtest/sqlalchemy.go:25]: nice -- should we also pin the version of sqlalchemy-cockroachdb under test in this script?

**Review by rafiss — APPROVED** [review]
ty! 

needs a backport to 20.2 and 21.1 as well

File: pkg/cmd/roachtest/sqlalchemy.go (hunk 1 above)
Comment (arulajmani) [reply pkg/cmd/roachtest/sqlalchemy.go:25]: Talked offline, we'll keep it at master for now and monitor how things go with Gord's work on the adapter.

**Comment by arulajmani** [comment]
TFTR! 

bors r=rafiss
