### PR TITLE
physical: fix blocked span reconciliation jobs after stream of system

### LINKED ISSUE #155444: AUTO SPAN CONFIG RECONCILIATION job breaks after PCR cutover
**Describe the problem**

After cutting over to a replicated virtual cluster, any zone configuration changes are not taking effect.  The span configurations are not updated and the `AUTO SPAN CONFIG RECONCILIATION` continues to fail.

**To Reproduce**

Create a source cluster and run these commands:

```
SET CLUSTER SETTING kv.rangefeed.enabled = true;

CREATE TABLE t(id UUID PRIMARY KEY);
ALTER TABLE t CONFIGURE ZONE USING num_replicas = 1;
```

Create a destination cluster and run these commands:

```
CREATE VIRTUAL CLUSTER mycopy FROM REPLICATION OF system ON ('postgresql://<user>:<password>@<address>:26257');
<allow some time>
ALTER VIRTUAL CLUSTER mycopy COMPLETE REPLICATION TO LATEST; 
<allow some time>
ALTER VIRTUAL CLUSTER mycopy START SERVICE SHARED;
<allow some time>
```

Connect to the `mycopy` virtual cluster and attempt to remove the table's zone configuration:

```
ALTER TABLE t CONFIGURE ZONE DISCARD;
```

Despite this, the number of replicas will remain at 1.

This appears to be caused by the `AUTO SPAN CONFIG RECONCILIATION` continually failing with this error message in the logs:

```
spanconfig/spanconfigjob/job.go:189 ⋮ [T3,Vmycopy,n1,job=AUTO SPAN CONFIG RECONCILIATION id=1115639736903467009] 893  reconciler failed with failed to generate SystemTarget records: secondary tenant 3 cannot target another tenant with ID system, retrying...
```

and

```
E251015 14:15:15.633230 47563 jobs/registry.go:1638 ⋮ [T3,Vmycopy,n1,job=1115639736903467009] 1234  AUTO SPAN CONFIG RECONCILIATION job 1115639736903467009: stepping through state reverting with unexpected error: reconciliation unsuccessful, failing job
E251015 14:15:15.633230 47563 jobs/registry.go:1638 ⋮ [T3,Vmycopy,n1,job=1115639736903467009] 1234 +(1) forced error mark
E251015 14:15:15.633230 47563 jobs/registry.go:1638 ⋮ [T3,Vmycopy,n1,job=1115639736903467009] 1234 +  | ‹"permanent job error"›
E251015 14:15:15.633230 47563 jobs/registry.go:1638 ⋮ [T3,Vmycopy,n1,job=1115639736903467009] 1234 +  | github.com/cockroachdb/errors/withstack/*withstack.withStack::
E251015 14:15:15.633230 47563 jobs/registry.go:1638 ⋮ [T3,Vmycopy,n1,job=1115639736903467009] 1234 +Wraps: (2) attached stack trace
E251015 14:15:15.633230 47563 jobs/registry.go:1638 ⋮ [T3,Vmycopy,n1,job=1115639736903467009] 1234 +  -- stack trace:
E251015 14:15:15.633230 47563 jobs/registry.go:1638 ⋮ [T3,Vmycopy,n1,job=1115639736903467009] 1234 +  | github.com/cockroachdb/cockroach/pkg/spanconfig/spanconfigjob.(*resumer).Resume
E251015 14:15:15.633230 47563 jobs/registry.go:1638 ⋮ [T3,Vmycopy,n1,job=1115639736903467009] 1234 +  |         pkg/spanconfig/spanconfigjob/job.go:195
E251015 14:15:15.633230 47563 jobs/registry.go:1638 ⋮ [T3,Vmycopy,n1,job=1115639736903467009] 1234 +  | github.com/cockroachdb/cockroach/pkg/jobs.(*Registry).stepThroughStateMachine.func2
E251015 14:15:15.633230 47563 jobs/registry.go:1638 ⋮ [T3,Vmycopy,n1,job=1115639736903467009] 1234 +  |         pkg/jobs/registry.go:1683
E251015 14:15:15.633230 47563 jobs/registry.go:1638 ⋮ [T3,Vmycopy,n1,job=1115639736903467009] 1234 +  | github.com/cockroachdb/cockroach/pkg/jobs.(*Registry).stepThroughStateMachine
E251015 14:15:15.633230 47563 jobs/registry.go:1638 ⋮ [T3,Vmycopy,n1,job=1115639736903467009] 1234 +  |         pkg/jobs/registry.go:1684
E251015 14:15:15.633230 47563 jobs/registry.go:1638 ⋮ [T3,Vmycopy,n1,job=1115639736903467009] 1234 +  | github.com/cockroachdb/cockroach/pkg/jobs.(*Registry).runJob
E251015 14:15:15.633230 47563 jobs/registry.go:1638 ⋮ [T3,Vmycopy,n1,job=1115639736903467009] 1234 +  |         pkg/jobs/adopt.go:410
E251015 14:15:15.633230 47563 jobs/registry.go:1638 ⋮ [T3,Vmycopy,n1,job=1115639736903467009] 1234 +  | github.com/cockroachdb/cockroach/pkg/jobs.(*Registry).resumeJob.func1
E251015 14:15:15.633230 47563 jobs/registry.go:1638 ⋮ [T3,Vmycopy,n1,job=1115639736903467009] 1234 +  |         pkg/jobs/adopt.go:263
E251015 14:15:15.633230 47563 jobs/registry.go:1638 ⋮ [T3,Vmycopy,n1,job=1115639736903467009] 1234 +  | github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunAsyncTaskEx.func1
E251015 14:15:15.633230 47563 jobs/registry.go:1638 ⋮ [T3,Vmycopy,n1,job=1115639736903467009] 1234 +  |         pkg/util/stop/stopper.go:438
E251015 14:15:15.633230 47563 jobs/registry.go:1638 ⋮ [T3,Vmycopy,n1,job=1115639736903467009] 1234 +  | runtime.goexit
E251015 14:15:15.633230 47563 jobs/registry.go:1638 ⋮ [T3,Vmycopy,n1,job=1115639736903467009] 1234 +  |         src/runtime/asm_amd64.s:1700
E251015 14:15:15.633230 47563 jobs/registry.go:1638 ⋮ [T3,Vmycopy,n1,job=1115639736903467009] 1234 +Wraps: (3) reconciliation unsuccessful, failing job
E251015 14:15:15.633230 47563 jobs/registry.go:1638 ⋮ [T3,Vmycopy,n1,job=1115639736903467009] 1234 +Error types: (1) *markers.withMark (2) *withstack.withStack (3) *errutil.leafError
I251015 14:15:16.074225 47563 1@jobs/structured_log.go:49 ⋮ [T3,Vmycopy,n1,job=1115639736903467009] 1235 ={"Timestamp":1760537716074186473,"EventType":"status_change","JobID":1115639736903467009,"JobType":"AUTO SPAN CONFIG RECONCILIATION","Description":"state changed to: reverting","PreviousStatus":"running","NewStatus":"reverting","RunNum":0,"Error":"‹reconciliation unsuccessful, failing job›","FinalResumeErr":"‹reconciliation unsuccessful, failing job›"}
E251015 14:15:16.075490 47563 jobs/registry.go:1638 ⋮ [T3,Vmycopy,n1,job=1115639736903467009] 1236  AUTO SPAN CONFIG RECONCILIATION job 1115639736903467009: stepping through state failed with unexpected error: reconciliation unsuccessful, failing job
```

**Expected behavior**
The zone configuration changes should apply as normal.

**Environment:**
 - CockroachDB version v25.3.2 (latest GA)

Jira issue: CRDB-55437

### PR DESCRIPTION
**Pull request by kev-cao**
If PCR streams from a system tenant, then the span config reconciliation job on the destination tenant after cutover will repeatedly fail. This is due to the fact that the producer job on the source system tenant is also replicated to the destination tenant, along with its corresponding PTS. As the PTS targets specifically the system tenant, the span reconciliation job on the destination tenant is unable to validate the span configuration as a non-system tenant is attempting to apply a configuration on another tenant.

Fixes: #155444

Release note: None

### CODE REVIEW

File: pkg/crosscluster/producer/producer_job.go [hunk 1]
```diff
@@ -133,6 +133,23 @@ func (p *producerJobResumer) Resume(ctx context.Context, execCtx interface{}) er
...
+	// associated PTS. After cutover, this blocks span config reconciliation since
+	// a tenant cannot lay a PTS on spans that another tenant owns. The producer
+	// job of course is not needed on the destination tenant, so we check for a
+	// mismatched cluster ID here and fast-exit the job.
+	if p.job.Payload().CreationClusterID != execCfg.NodeInfo.LogicalClusterID() {
+		log.Dev.Infof(
+			ctx, "replication stream %d skipping resume on cluster %s (belongs to cluster %s)",
+			p.job.ID(), execCfg.NodeInfo.LogicalClusterID(), p.job.Payload().CreationClusterID,
+		)
+		if err := p.releaseProtectedTimestamp(ctx, execCfg); err != nil {
```
Comment (msbutler) [inline pkg/crosscluster/producer/producer_job.go]: hrm, why not return an error, inducing the OnFailOrCancel routine? This is what backup does: https://github.com/msbutler/cockroach/blob/master/pkg/backup/backup_job.go#L892

File: pkg/crosscluster/physical/stream_ingestion_job_test.go [hunk 2]
```diff
@@ -742,3 +742,80 @@ func TestPhysicalReplicationGatewayRoute(t *testing.T) {
...
+func TestPhysicalReplicationStreamOfSystemTenant(t *testing.T) {
+	defer leaktest.AfterTest(t)()
+	defer log.Scope(t).Close(t)
+
+	// This test verifies that the span reconciliation job on a promoted standby
+	// tenant that was streaming from a system tenant is able to make progress.
+	// See https://github.com/cockroachdb/cockroach/issues/155444 for more
+	// details.
+	ctx := context.Background()
+	primarySrv, primaryDB, _ := serverutils.StartServer(t, base.TestServerArgs{
```
Comment (msbutler) [inline pkg/crosscluster/physical/stream_ingestion_job_test.go]: why not use reuse the e2e test infra? it's able to stream from a system tenant:
https://github.com/msbutler/cockroach/blob/master/pkg/crosscluster/physical/replication_stream_e2e_test.go#L1348

Comment (kev-cao) [reply pkg/crosscluster/physical/stream_ingestion_job_test.go]: Oh yeah that's nice — I did have to modify a blurb to include the `DestTenantServer` so that I could access the job registry. RFAL

File: pkg/crosscluster/physical/stream_ingestion_job_test.go [hunk 3]
```diff
@@ -742,3 +743,75 @@ func TestPhysicalReplicationGatewayRoute(t *testing.T) {
 	progress := jobutils.GetJobProgress(t, systemDB, jobspb.JobID(jobID))
 	require.Empty(t, progress.Details.(*jobspb.Progress_StreamIngest).StreamIngest.PartitionConnUris)
 }
+
+func TestPhysicalReplicationStreamOfSystemTenant(t *testing.T) {
```
Comment (msbutler) [inline pkg/crosscluster/physical/stream_ingestion_job_test.go]: nit: the name of the test should be more reflective of the reconciliation job stuff. we already have a general test around streaming from a a system tenant

File: pkg/crosscluster/physical/stream_ingestion_job_test.go [hunk 4]
```diff
@@ -742,3 +743,75 @@ func TestPhysicalReplicationGatewayRoute(t *testing.T) {
...
+
+	replicationtestutils.WaitUntilStartTimeReached(t, c.DestSysSQL, jobspb.JobID(consumerJobID))
+	srcTime := c.SrcCluster.Server(0).Clock().Now()
+	c.Cutover(ctx, producerJobID, consumerJobID, srcTime.GoTime(), false /* async */)
+	defer c.StartDestTenant(ctx, nil /* withTestingKnobs */, 0 /* server */)()
+
+	// We speed up the span config reconciliation job manager so that it will
+	// quickly detect the missing reconciliation job on the tenant (the previous
+	// one was canceled as it was replicated) and spin up a new one.
+	c.DestSysSQL.Exec(t, "ALTER TENANT ALL SET CLUSTER SETTING spanconfig.reconciliation_job.check_interval = '10ms'")
```
Comment (msbutler) [inline pkg/crosscluster/physical/stream_ingestion_job_test.go:777]: should we do this before cutover, to ensure we don't get caught waiting for 10 minutes?

File: pkg/crosscluster/physical/stream_ingestion_job_test.go [hunk 5]
```diff
@@ -742,3 +743,75 @@ func TestPhysicalReplicationGatewayRoute(t *testing.T) {
...
+	defer cleanup()
+
+	producerJobID, consumerJobID := c.StartStreamReplication(ctx)
+	jobutils.WaitForJobToRun(c.T, c.SrcSysSQL, jobspb.JobID(producerJobID))
+	jobutils.WaitForJobToRun(c.T, c.DestSysSQL, jobspb.JobID(consumerJobID))
+
+	replicationtestutils.WaitUntilStartTimeReached(t, c.DestSysSQL, jobspb.JobID(consumerJobID))
+	srcTime := c.SrcCluster.Server(0).Clock().Now()
+	c.Cutover(ctx, producerJobID, consumerJobID, srcTime.GoTime(), false /* async */)
+	defer c.StartDestTenant(ctx, nil /* withTestingKnobs */, 0 /* server */)()
```
Comment (msbutler) [inline pkg/crosscluster/physical/stream_ingestion_job_test.go]: what's the purpose of this defer?

File: pkg/crosscluster/physical/stream_ingestion_job_test.go [hunk 6]
```diff
@@ -742,3 +743,75 @@ func TestPhysicalReplicationGatewayRoute(t *testing.T) {
...
+
+	// We speed up the span config reconciliation job manager so that it will
+	// quickly detect the missing reconciliation job on the tenant (the previous
+	// one was canceled as it was replicated) and spin up a new one.
+	c.DestSysSQL.Exec(t, "ALTER TENANT ALL SET CLUSTER SETTING spanconfig.reconciliation_job.check_interval = '10ms'")
+
+	registry := c.DestTenantServer.JobRegistry().(*jobs.Registry)
+	// We nudge the adoption queue to pick up the replicated stream producer job
+	// so that it will be dropped.
+	registry.TestingNudgeAdoptionQueue()
```
Comment (msbutler) [inline pkg/crosscluster/physical/stream_ingestion_job_test.go:782]: do we need to manually nudge the adoption queue, given that we job intervals have already been sped up via the test driver?

File: pkg/crosscluster/physical/stream_ingestion_job_test.go (hunk 5 above)
Comment (kev-cao) [reply pkg/crosscluster/physical/stream_ingestion_job_test.go]: `StartDestTenant` returns a cleanup function, so just deferring that.

File: pkg/crosscluster/physical/stream_ingestion_job_test.go (hunk 4 above)
Comment (kev-cao) [reply pkg/crosscluster/physical/stream_ingestion_job_test.go:777]: Oh the cluster setting actually has [a listener set up on it](https://github.com/kev-cao/cockroach/blob/2593003795fcb177bd0caa1d23dd40fe856b2e28/pkg/spanconfig/spanconfigmanager/manager.go#L114-L116) so that it runs a job check on change, which then resets the timer so I think either is fine.

File: pkg/crosscluster/physical/stream_ingestion_job_test.go (hunk 6 above)
Comment (kev-cao) [reply pkg/crosscluster/physical/stream_ingestion_job_test.go:782]: Yeah probably don't need to. I was seeing if I could shave some time off the test, and it gave me 3 seconds back. But ran it again, and it didn't change anything, so probably just some noise on my machine at the time.

Comment (msbutler) [reply pkg/crosscluster/physical/stream_ingestion_job_test.go:782]: you could run this with --count=100 to get a more confident answer on the runtime impact

File: pkg/crosscluster/physical/stream_ingestion_job_test.go (hunk 5 above)
Comment (msbutler) [reply pkg/crosscluster/physical/stream_ingestion_job_test.go]: oh i see. for the dull, maybe return cleanup as var and call `defer cleanup()` in the next line.

File: pkg/crosscluster/replicationtestutils/testutils.go [hunk 7]
```diff
@@ -186,19 +187,18 @@ func (c *TenantStreamingClusters) init(ctx context.Context) {
 func (c *TenantStreamingClusters) StartDestTenant(
 	ctx context.Context, withTestingKnobs *base.TestingKnobs, server int,
 ) func() {
+	var err error
+	var testKnobs base.TestingKnobs
```
Comment (msbutler) [inline pkg/crosscluster/replicationtestutils/testutils.go:191]: just to confirm this change was necessary to get access to the destination tenant's jobregistry, right?

**Review by msbutler — APPROVED** [review]

File: pkg/crosscluster/replicationtestutils/testutils.go (hunk 7 above)
Comment (kev-cao) [reply pkg/crosscluster/replicationtestutils/testutils.go:191]: Yup

**Comment by msbutler** [comment]
@kev-cao caught this after merge: i don't think this needs a release note

**Comment by msbutler** [comment]
the commit message is the source of truth for docs. i would update the backport commit messages. don't worry about master.
