### PR TITLE
crosscluster/physical: fix ingest retry progress bug

### LINKED ISSUE #167384: roachtest: c2c/MultiRegion/SameRegions/kv0 failed
roachtest.c2c/MultiRegion/SameRegions/kv0 [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/21295070?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/21295070?buildTab=artifacts#/c2c/MultiRegion/SameRegions/kv0) on release-26.1 @ [1b15dfff1274b7bb24d5be06462805c54b6ee6f3](https://github.com/cockroachdb/cockroach/commits/1b15dfff1274b7bb24d5be06462805c54b6ee6f3):

Failed with:

```
(latency_verifier.go:211).assertValid: stream-ingestion: max latency was more than allowed: 5m26.470996721s vs 2m0s
(monitor.go:267).Wait: monitor failure: monitor user task failed: t.Fatal() was called
test artifacts and logs in: /artifacts/c2c/MultiRegion/SameRegions/kv0/run_1
```
Cluster Node to Ip Mapping:
| Node | Public IP | Private IP |
| --- | --- | --- |
| teamcity-21295070-1775110026-41-n9cpu8-geo-0001 | 34.169.188.144 | 10.138.0.43 |
| teamcity-21295070-1775110026-41-n9cpu8-geo-0002 | 136.118.241.23 | 10.138.0.68 |
| teamcity-21295070-1775110026-41-n9cpu8-geo-0003 | 136.117.16.56 | 10.138.0.69 |
| teamcity-21295070-1775110026-41-n9cpu8-geo-0004 | 34.55.15.185 | 10.128.0.40 |
| teamcity-21295070-1775110026-41-n9cpu8-geo-0005 | 35.226.128.239 | 10.128.0.175 |
| teamcity-21295070-1775110026-41-n9cpu8-geo-0006 | 104.198.15.170 | 10.138.15.201 |
| teamcity-21295070-1775110026-41-n9cpu8-geo-0007 | 136.109.230.48 | 10.138.15.200 |
| teamcity-21295070-1775110026-41-n9cpu8-geo-0008 | 136.118.181.167 | 10.138.0.44 |
| teamcity-21295070-1775110026-41-n9cpu8-geo-0009 | 34.127.113.53 | 10.138.15.202 |

Parameters:
 - <code>arch=amd64</code>
 - <code>cloud=gce</code>
 - <code>coverageBuild=false</code>
 - <code>cpu=8</code>
 - <code>diskCount=0</code>
 - <code>encrypted=false</code>
 - <code>fs=ext4</code>
 - <code>localSSD=false</code>
 - <code>metamorphicLeases=leader</code>
 - <code>runtimeAssertionsBuild=false</code>
<details><summary>Help</summary>
<p>

See: [roachtest README](https://github.com/cockroachdb/cockroach/blob/master/pkg/cmd/roachtest/README.md)

See: [How To Investigate \(internal\)](https://cockroachlabs.atlassian.net/l/c/SSSBr8c7)

See: [Grafana](https://go.crdb.dev/roachtest-grafana/teamcity-21295070/c2c-multiregion-sameregions-kv0/1775115216292/1775116350954)

</p>
</details>
/cc @cockroachdb/disaster-recovery
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*c2c/MultiRegion/SameRegions/kv0.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/bazci/githubpost/issues)

</sub>

Jira issue: CRDB-62425

### PR DESCRIPTION
**Pull request by andrew-r-thomas**
This patch fixes two bugs in `ingestWithRetries`.
1. the resumer's job never has its in memory progress updated within a
   single resume, as the frontier processor writes progress updates
   directly to the db via job id.
2. `previousPersistedSpans` is never updated, which, in combination with
   the above, means, unless the job is resumed more than once, the
   branch to reset the retrier is never taken, as they are both always
   zero-values.

The fix is to refresh the resumer's job and update the previous value
each loop iteration.

Fixes: #167384

Release note: None

### CODE REVIEW

File: pkg/crosscluster/physical/stream_ingestion_job.go [hunk 1]
```diff
@@ -413,13 +413,22 @@ func ingestWithRetries(
 		}
 		log.Dev.Infof(ctx, "hit retryable error %s", err)
 
+		// Reload the job's in-memory progress from the database so that we see accurate progress.
+		if updateErr := resumer.job.NoTxn().Update(ctx, func(_ isql.Txn, _ jobs.JobMetadata, _ *jobs.JobUpdater) error {
```
Comment (dt) [inline pkg/crosscluster/physical/stream_ingestion_job.go]: I think we have a Load() fn rather than relying on side effect of a noop update. For extra credit  I think we could even just load the progress proto with the infostorage helper but that might make this a bigger change/less backportable.

Comment (dt) [reply pkg/crosscluster/physical/stream_ingestion_job.go]: https://github.com/cockroachdb/cockroach/blob/cd06503a6b5f92978fb3efb703ad3ab846ff7df7/pkg/jobs/registry.go#L866 is the one I was thinking of.

Comment (andrew-r-thomas) [reply pkg/crosscluster/physical/stream_ingestion_job.go]: Yeah, forgot the job struct has a pointer to the registry too

Comment (dt) [reply pkg/crosscluster/physical/stream_ingestion_job.go]: execCfg has it too. But https://github.com/cockroachdb/cockroach/blob/cd06503a6b5f92978fb3efb703ad3ab846ff7df7/pkg/jobs/job_info_storage.go#L771 is another option.

File: pkg/crosscluster/physical/replication_stream_e2e_test.go [hunk 2]
```diff
@@ -1637,9 +1637,8 @@ func splitPrimaryKeyIndexSpan(
 
 func TestAlterExternalConnection(t *testing.T) {
 	defer leaktest.AfterTest(t)()
-	skip.UnderDeadlock(t)
-	skip.UnderRace(t)
 	defer log.Scope(t).Close(t)
+	skip.UnderDuress(t)
```
Comment (andrew-r-thomas) [inline pkg/crosscluster/physical/replication_stream_e2e_test.go]: Because we weren't updating the previous value in our retry loop, after this test resumes the job after some progress, the retry reset branch is taken *every* time, which gave it effectively infinite retries. This test is now flaky under stress with the fix

**Review by dt — APPROVED** [review]

File: pkg/crosscluster/physical/stream_ingestion_job.go [hunk 3]
```diff
@@ -413,13 +413,28 @@ func ingestWithRetries(
...
+		// Reload the job's in-memory progress from the database so that we see accurate progress.
+		reloadErr := execCtx.ExecCfg().InternalDB.Txn(ctx, func(ctx context.Context, t isql.Txn) error {
+			job, err := execCtx.ExecCfg().JobRegistry.LoadClaimedJobWithTxn(ctx, resumer.job.ID(), t)
+			if err != nil {
+				return err
+			}
+			resumer.job = job
+			return nil
+		})
+		if reloadErr != nil {
```
Comment (msbutler) [inline pkg/crosscluster/physical/stream_ingestion_job.go:424]: wrap this in best effort? whenever we log an error, that's usually a good candidate for the besteffort wrapper

File: pkg/crosscluster/physical/replication_stream_e2e_test.go [hunk 4]
```diff
@@ -1693,3 +1692,107 @@ func TestAlterExternalConnection(t *testing.T) {
...
+	// Disable replanning to prevent further restarts.
+	serverutils.SetClusterSetting(t, c.DestCluster, "stream_replication.replan_flow_threshold", 0)
+	serverutils.SetClusterSetting(t, c.DestCluster, "stream_replication.replan_flow_frequency", time.Minute*10)
+	close(turnOffReplanning)
+
+	// Let the job resume and make progress after the replan.
+	resumeTarget := c.DestSysServer.Clock().Now()
+	c.WaitUntilReplicatedTime(resumeTarget, jobspb.JobID(ingestionJobID))
+
+	// Verify that progress entries are strictly non-decreasing after the
```
Comment (msbutler) [inline pkg/crosscluster/physical/replication_stream_e2e_test.go]: instead of adding a new test, could we instead add this assertion to the autoreplan test?

File: pkg/crosscluster/physical/replication_stream_e2e_test.go (hunk 2 above)
Comment (msbutler) [reply pkg/crosscluster/physical/replication_stream_e2e_test.go]: hrm, so you're diff is simply skipping this under stress, but that means this test could still flake on a non stress run. i'm also not totally following why this patch made this test flaky. could your clarify the root cause of the test flake, and deflake it in this commit? Ideally we don't backport a skipped test.

**Review by msbutler — COMMENTED** [review]
thanks for jumping on this!

**Comment by msbutler** [comment]
also, we only need to backport this to 25.4, which is when the regression began.

File: pkg/crosscluster/physical/stream_ingestion_job.go (hunk 3 above)
Comment (andrew-r-thomas) [reply pkg/crosscluster/physical/stream_ingestion_job.go:424]: I had this as besteffort initially, and maybe im missing something about how backports work, but besteffort only made it into a release branch in 26.2, would we still be able to backport to 26.1 and 25.4 if we had it here?

Comment (msbutler) [reply pkg/crosscluster/physical/stream_ingestion_job.go:424]: ah, i suppose we can merge and backport this code without best effort, but then have a follow up PR with bestEffort on master.

**Comment by dt** [comment]
> we only need to backport this to 25.4

The `previousPersistedSpans` never being set bug is on 25.2 and 24.3 as well.

**Comment by msbutler** [comment]
> The previousPersistedSpans never being set bug is on 25.2 and 24.3 as well.

oh right.....hrm, i guess we need to test this as well somehow.

**Comment by msbutler** [comment]
the original sin: i added new logic without a unit test https://github.com/cockroachdb/cockroach/pull/124926

Edit: there is a unit test here! i wonder why it failed to catch this bug.

**Comment by msbutler** [comment]
oh wait, why is this unit test passing? `TestTenantStreamingJobRetryReset`

File: pkg/crosscluster/physical/replication_stream_e2e_test.go (hunk 2 above)
Comment (andrew-r-thomas) [reply pkg/crosscluster/physical/replication_stream_e2e_test.go]: ok i think we're just forgetting to wait for the job to pause here. the test is panicing at the very bottom `WaitUntilReplicatedTime`, because we race between resuming the job in the test after fixing the connection and the retry loop tearing down/pausing after exhausting retries, so that resume can occasionally (eg under `--stress`) becomes a noop, and the job stays paused. before the fix, the test essentially had infinite retries, so the resume was still a noop, but it kept retrying long enough to pick up the fixed connection

Comment (msbutler) [reply pkg/crosscluster/physical/replication_stream_e2e_test.go]: ah, makes sense. thanks for digging into this!

**Comment by andrew-r-thomas** [comment]
unrelated flakes, one was a backup test timeout (big combinatorial test), second was a kv test, rerunning again

**Review by msbutler — APPROVED** [review]
awesome work on this!

**Comment by andrew-r-thomas** [comment]
thank you!

/trunk merge
