### PR TITLE
kvserver: respect draining status on a node for lease transfers with …

### LINKED ISSUE #66103: kv: ranges with leaseholder preferences applied don't lease transfer cleanly during graceful drain
**Describe the problem**

Ranges with leaseholder preferences applied don't lease transfer cleanly during graceful drain. The impact is that graceful restart of nodes holding leases of ranges with leaseholder preferences applied is not totally graceful. There may be a short blip in availability when the node is eventually killed (as in some production envs (k8s self-hosted + CC) there is a timeout on how long graceful drain is waited for (after N seconds SIGKILL is sent)).

**To Reproduce**

All nodes running `v21.1.1`:

```
$ cockroach version
Build Tag:        v21.1.1
Build Time:       2021/05/24 15:00:00
Distribution:     CCL
Platform:         darwin amd64 (x86_64-apple-darwin19)
Go Version:       go1.15.11
C Compiler:       Clang 10.0.0 
Build Commit ID:  f6630b3f524f3a5e52b330220037af01369b1ff2
Build Type:       release
```

n1 started with `cockroach start --insecure --listen-addr=localhost --logtostderr --locality dc=test --join=localhost:26257,localhost:26258,localhost:26259`.

n2 started with `cockroach start  --join=localhost:26257,localhost:26258,localhost:26259 --listen-addr localhost:26258 --insecure --http-addr localhost:8081 --logtostderr`.

n3 started with `cockroach start --join --join=localhost:26257,localhost:26258,localhost:26259 --listen-addr localhost:26259 --insecure --http-addr localhost:8082 --logtostderr`.

Create table with leaseholder preference like this:

```
root@:26257/defaultdb> create database test;
CREATE DATABASE

Time: 150ms total (execution 150ms / network 0ms)

root@:26257/defaultdb> use test;
SET

Time: 41ms total (execution 41ms / network 0ms)

root@:26257/test> CREATE TABLE kv (
        k STRING PRIMARY KEY,
        v STRING);
CREATE TABLE
root@:26257/test> ALTER TABLE kv CONFIGURE ZONE USING lease_preferences = '[[+dc=test]]', constraints = '{+dc=test: 1}', num_replicas =3;
CONFIGURE ZONE 1

Time: 103ms total (execution 103ms / network 0ms
```

Send SIGTERM to n1. Logs show:

```
I210604 21:00:12.826634 2508 1@server/drain.go:157 ⋮ [server drain process] 571  drain remaining: 1
I210604 21:00:12.844215 2508 1@server/drain.go:159 ⋮ [server drain process] 572  drain details: range lease iterations: 1
I210604 21:00:13.061474 2509 1@cli/start.go:831 ⋮ [-] 573  210 running tasks
I210604 21:00:14.196713 2508 1@server/drain.go:157 ⋮ [server drain process] 575  drain remaining: 1
I210604 21:00:14.196785 2508 1@server/drain.go:159 ⋮ [server drain process] 576  drain details: range lease iterations: 1
I210604 21:00:15.674465 2508 1@server/drain.go:157 ⋮ [server drain process] 579  drain remaining: 1
I210604 21:00:15.674535 2508 1@server/drain.go:159 ⋮ [server drain process] 580  drain details: range lease iterations: 1
I210604 21:00:17.228686 2508 1@server/drain.go:157 ⋮ [server drain process] 582  drain remaining: 1
I210604 21:00:17.248249 2508 1@server/drain.go:159 ⋮ [server drain process] 583  drain details: range lease iterations: 1
I210604 21:00:17.874708 508 2@kv/kvprober/kvprober.go:216 ⋮ [n1,kvprober] 584  kv.Get(‹/Table/34›), r=30 returned success in 431µs
I210604 21:00:18.061499 2509 1@cli/start.go:831 ⋮ [-] 585  210 running tasks
I210604 21:00:18.679080 2508 1@server/drain.go:157 ⋮ [server drain process] 587  drain remaining: 1
I210604 21:00:18.698056 2508 1@server/drain.go:159 ⋮ [server drain process] 588  drain details: range lease iterations: 1
```

The drain never completes. Looks racy like the lease is transferred but then is transferred back due to the leaseholder preference:

```
root@:26258/test> select range_id, start_pretty, end_pretty, lease_holder, replicas from crdb_internal.ranges where range_id = '37';
  range_id | start_pretty | end_pretty | lease_holder | replicas
-----------+--------------+------------+--------------+-----------
        37 | /Table/53    | /Max       |            1 | {1,2,3}
(1 row)

Time: 5ms total (execution 5ms / network 0ms)

root@:26258/test> select range_id, start_pretty, end_pretty, lease_holder, replicas from crdb_internal.ranges where range_id = '37';
  range_id | start_pretty | end_pretty | lease_holder | replicas
-----------+--------------+------------+--------------+-----------
        37 | /Table/53    | /Max       |            2 | {1,2,3}
(1 row)

Time: 124ms total (execution 124ms / network 0ms)

root@:26258/test> select range_id, start_pretty, end_pretty, lease_holder, replicas from crdb_internal.ranges where range_id = '37';
  range_id | start_pretty | end_pretty | lease_holder | replicas
-----------+--------------+------------+--------------+-----------
        37 | /Table/53    | /Max       |            1 | {1,2,3}
(1 row)

Time: 5ms total (execution 5ms / network 0ms)
```

If you run the following command, the drain immediately finishes:

```
root@:26258/test> ALTER TABLE kv CONFIGURE ZONE DISCARD;
CONFIGURE ZONE 1

Time: 99ms total (execution 99ms / network 0ms)
```

**Expected behavior**
SIGTERM would lead to graceful drain of all range leases held by the node.

### PR DESCRIPTION
**Pull request by lunevalex**
…lease preferences

Fixes #66103

Lease transfer logic in the allocator did not consider the health of
the node when transferring a lease from a node outside of preference
to a node inside of preference. This would have prevented a node with
a lease preference from draining gracefully, as it would shed leases
and then get them back.

Release note (bug fix): Allows a node with lease preferences to drain
gracefully.

### CODE REVIEW

File: pkg/kv/kvserver/allocator.go [hunk 1]
```diff
@@ -1288,7 +1288,12 @@ func (a *Allocator) TransferLeaseTarget(
 		if preferred[0].StoreID == leaseStoreID {
 			return roachpb.ReplicaDescriptor{}
 		}
-		return preferred[0]
+		// Verify that the preferred replica is eligible to receive the lease.
+		preferred, _ = a.storePool.liveAndDeadReplicas(preferred)
+		if len(preferred) == 1 {
+			return preferred[0]
+		}
+		return roachpb.ReplicaDescriptor{}
```
Comment (tbg) [inline pkg/kv/kvserver/allocator.go:1296]: There's a behavior change here that I'm not sure we want in the common case in which there is a single preferred replica that is draining. Prior to this PR, it would fall through and consider moving the lease elsewhere. Now, it will decide not to move the lease. Do we want to preserve the old behavior?

Comment (lunevalex) [reply pkg/kv/kvserver/allocator.go:1296]: Once we are in the `len(preferred) == 1` branch of the code we always return either the preferred lease holder or an empty `ReplicaDescriptor`, this PR does not change that behavior. In your example the draining code calls shedLease, which will pass in `checkTransferLeaseSource=false`, which means the lease holder will get removing from the existing list of candidates before checking for lease preferences, so it falls through that way.

**Review by tbg — APPROVED** [review]

**Comment by lunevalex** [comment]
TFTR!

bors r+

**Comment by rafiss** [comment]
Just wondering: is this something we'd like to backport to 21.1 and 20.2? If I understand correctly, the problem was originally reported since it affected CC upgrades.

**Comment by lunevalex** [comment]
> Just wondering: is this something we'd like to backport to 21.1 and 20.2? If I understand correctly, the problem was originally reported since it affected CC upgrades.

yes we should
