### PR TITLE
changefeedccl: revert Dial() to fetch all metadata topics 

### LINKED ISSUE #116358: roachtest: cdc/kafka-auth failed
roachtest.cdc/kafka-auth [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyAzureBazel/13122805?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyAzureBazel/13122805?buildTab=artifacts#/cdc/kafka-auth) on master @ [4a10b8fc0b7bb5b5cb30ebc65a8b1c4f19daa562](https://github.com/cockroachdb/cockroach/commits/4a10b8fc0b7bb5b5cb30ebc65a8b1c4f19daa562):

```
(cdc.go:1030).runCDCKafkaAuth: create changefeed with insecure TLS transport and no auth: pq: kafka server: Replication-factor is invalid
(cluster.go:2160).Run: context canceled
test artifacts and logs in: /artifacts/cdc/kafka-auth/run_1
```

Parameters:
 - <code>ROACHTEST_arch=amd64</code>
 - <code>ROACHTEST_cloud=azure</code>
 - <code>ROACHTEST_coverageBuild=false</code>
 - <code>ROACHTEST_cpu=4</code>
 - <code>ROACHTEST_encrypted=false</code>
 - <code>ROACHTEST_metamorphicBuild=false</code>
 - <code>ROACHTEST_ssd=0</code>
<details><summary>Help</summary>
<p>

See: [roachtest README](https://github.com/cockroachdb/cockroach/blob/master/pkg/cmd/roachtest/README.md)

See: [How To Investigate \(internal\)](https://cockroachlabs.atlassian.net/l/c/SSSBr8c7)

_Grafana is not yet available for azure clusters_</p>
</details>
/cc @cockroachdb/cdc
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*cdc/kafka-auth.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)
</sub>

Jira issue: CRDB-34591

### PR DESCRIPTION
**Pull request by wenyihu6**
Patch (https://github.com/cockroachdb/cockroach/pull/114740) changed Dial() in pkg/ccl/changefeedccl/sink_kafka.go to refresh
metadata exclusively for kafkaSink.topics() rather than for all topics. This
triggered a sarama error ( an invalid replication factor in Kafka servers). It
seems hard to get to the bottom of it given that there are too many unknowns
from sarama and kafka side (More in https://github.com/cockroachdb/cockroach/issues/116872). We decided to revert back to what
Dial() previously did in sarama code and will continue investigating afterwards.

Part of: https://github.com/cockroachdb/cockroach/issues/116872
Fixes: https://github.com/cockroachdb/cockroach/issues/116358
Release note: None

### CODE REVIEW

File: pkg/ccl/changefeedccl/sink_kafka.go [hunk 1]
```diff
@@ -257,10 +257,21 @@ func (s *kafkaSink) Dial() error {
...
-		// RefreshMetadata manually to check for any connection error.
-		return errors.CombineErrors(err, client.Close())
+	if err = client.RefreshMetadata(); err != nil {
+		// Dial() seems to be a weird state while topics are still setting up and
+		// calling RefreshMetadata with specific topics s.Topics() here triggered a
+		// sarama error (pq: kafka server: Replication-factor is invalid). To match
+		// the previous behaviour in sarama prior to #114740 during Dial(), we
+		// manually fetch metadata for all topics just during Dial(). See more in
+		// #116872.
+		if errors.Is(err, sarama.ErrLeaderNotAvailable) || errors.Is(err, sarama.ErrReplicaNotAvailable) ||
```
Comment (wenyihu6) [inline pkg/ccl/changefeedccl/sink_kafka.go:267]: Alternatively, we could temporarily change config.Metadata.Full to true temporarily during Dial() and change it back to config.Metadata.Full to false after Dial() if we think this way is too hacky.

Comment (jayshrivastava) [reply pkg/ccl/changefeedccl/sink_kafka.go:266]: I'm okay with the current implementation. To be safe, I would prefer to always have `config.Metadata.Full=false`.

**Review by jayshrivastava — APPROVED** [review]
I'm happy with this change. Looking at the code path, it doesn't look like sarama fetches all topics when you pass empty args to `RefreshMetadata`. And, it shouldn't fetch all of them every since we have `config.Metadata.Full=false`. Finally, we swallow the transient errors exactly how sarama does.

**Comment by wenyihu6** [comment]
I think with the current approach where we manually call RefreshMetadata with empty topics, it fetches all topics since we are passing an empty argument. RefreshMetadata doesn't check for `config.Metadata.Full=false` ; the check is done before RefreshMetadata is called. The current approach is mocking the behaviour as if `config.Metadata.Full` is set to true https://github.com/IBM/sarama/blob/4d31d23ca31a68788d4249cfc8f44e619cea2d3a/client.go#L217-L226.

**Comment by wenyihu6** [comment]
*[`pkg/ccl/changefeedccl/sink_kafka.go` line 267 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/116414#gh-1433161173:-NmCVhndDbPHeTIcuxom:bb6sh2i) ([raw file](https://github.com/cockroachdb/cockroach/blob/07ab1f9766cc7e8dfb246a88c7868166ade914ce/pkg/ccl/changefeedccl/sink_kafka.go#L267)):*
<details><summary><i>Previously, jayshrivastava (Jayant) wrote…</i></summary><blockquote>

I'm okay with the current implementation. To be safe, I would prefer to always have `config.Metadata.Full=false`. 
</blockquote></details>

Ack.

**Comment by wenyihu6** [comment]
TFTR!

bros r=jayshrivastava

**Comment by wenyihu6** [comment]
TFTR!

bors r=jayshrivastava
