### PR TITLE
roachtest: prevent costfuzz/workload-replay from running in public TC…

### LINKED ISSUE #107252: roachtest: costfuzz/workload-replay failed
roachtest.costfuzz/workload-replay [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/10983916?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/10983916?buildTab=artifacts#/costfuzz/workload-replay) on master @ [c6f4c0ed6e39ec4795755b8b477e6cac0abf818f](https://github.com/cockroachdb/cockroach/commits/c6f4c0ed6e39ec4795755b8b477e6cac0abf818f):

```
The details about this test failure have been omitted; consult the log for more details
```
<p>Parameters: <code>ROACHTEST_arch=amd64</code>
, <code>ROACHTEST_cloud=gce</code>
, <code>ROACHTEST_cpu=4</code>
, <code>ROACHTEST_encrypted=false</code>
, <code>ROACHTEST_ssd=0</code>
</p>
<details><summary>Help</summary>
<p>

See: [roachtest README](https://github.com/cockroachdb/cockroach/blob/master/pkg/cmd/roachtest/README.md)

See: [How To Investigate \(internal\)](https://cockroachlabs.atlassian.net/l/c/SSSBr8c7)

</p>
</details>
/cc @cockroachdb/sql-queries
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*costfuzz/workload-replay.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)
</sub>

Jira issue: CRDB-29965

### PR DESCRIPTION
**Pull request by smg260**
… builds.

Release note: none
Fixes: #107252

### CODE REVIEW

File: pkg/cmd/roachtest/tests/costfuzz.go [hunk 1]
```diff
@@ -35,6 +36,13 @@ func registerCostFuzz(r registry.Registry) {
 		case sqlsmith.SeedMultiRegionSetupName:
 			clusterSpec = r.MakeClusterSpec(9, spec.Geo(), spec.GatherCores())
 		case "workload-replay":
+			// When running in CI, only allow running in the private roachtest, which
+			// has the required credentials.
+			if os.Getenv("TC_BUILD_ID") != "" && os.Getenv("ROACHTEST_PRIVATE") != "1" {
+				fmt.Println("Skipping costfuzz/workload-replay in public CI roachtest")
+				continue
```
Comment (renatolabs) [inline pkg/cmd/roachtest/tests/costfuzz.go:43]: Setting a `Skip` reason instead of not registering the test at all is probably friendlier to folks looking at the list of tests in the nightly build.

**Review by renatolabs — APPROVED** [review]
Thanks for fixing!

**Review by herkolategan — APPROVED** [review]
LGTM!
Awesome, thanks for fixing!

File: pkg/cmd/roachtest/tests/costfuzz.go (hunk 1 above)
Comment (smg260) [reply pkg/cmd/roachtest/tests/costfuzz.go:43]: I thought about that but then it would try and allocate a cluster before skipping - though it's probably better for consistency. Updating.

Comment (renatolabs) [reply pkg/cmd/roachtest/tests/costfuzz.go]: I meant setting the `Skip` field on the `TestSpec` struct, in which case the cluster won't be allocated.
