### PR TITLE
lint: fix `TestForbiddenImports`

### LINKED ISSUE #132258: lint: `TestForbiddenImports` is not working correctly
The test works differently under `dev lint` and `go test`.

Under `go test` the following legitimate errors are surfaced:

```
   gen-lint_test.go:1911: 
        github.com/cockroachdb/cockroach/pkg/build/engflow: log <- please use "util/log" instead of "log"
    gen-lint_test.go:1911: 
        github.com/cockroachdb/cockroach/pkg/ccl/crosscluster/logical: github.com/cockroachdb/errors/issuelink <- please use "github.com/cockroachdb/errors" instead of "github.com/cockroachdb/errors/issuelink"
    gen-lint_test.go:1911: 
        github.com/cockroachdb/cockroach/pkg/ccl/crosscluster/streamclient: github.com/pkg/errors <- please use "github.com/cockroachdb/errors" instead of "github.com/pkg/errors"
    gen-lint_test.go:1911: 
        github.com/cockroachdb/cockroach/pkg/raft/confchange: errors <- please use "github.com/cockroachdb/errors" instead of "errors"
    gen-lint_test.go:1911: 
        github.com/cockroachdb/cockroach/pkg/raft/raftlogger: log <- please use "util/log" instead of "log"
    gen-lint_test.go:1911: 
        github.com/cockroachdb/cockroach/pkg/raft/rafttest: errors <- please use "github.com/cockroachdb/errors" instead of "errors"
    gen-lint_test.go:1911: 
        github.com/cockroachdb/cockroach/pkg/raft/rafttest: log <- please use "util/log" instead of "log"
    gen-lint_test.go:1911: 
        github.com/cockroachdb/cockroach/pkg/raft: errors <- please use "github.com/cockroachdb/errors" instead of "errors"
    gen-lint_test.go:1911: 
        github.com/cockroachdb/cockroach/pkg/sql/tablemetadatacache: errors <- please use "github.com/cockroachdb/errors" instead of "errors"
    gen-lint_test.go:1911: 
        github.com/cockroachdb/cockroach/pkg/workload/debug: log <- please use "util/log" instead of "log"
--- FAIL: TestLint (0.00s)
    --- PASS: TestLint/TestForbiddenImportsSQLShell (0.95s)
    --- FAIL: TestLint/TestForbiddenImports (5.41s)
```

Under `dev lint`, these errors do not appear.

The issue is the following missing line of code:

```
diff --git a/pkg/testutils/lint/lint_test.go b/pkg/testutils/lint/lint_test.go
index c208019aefe..e82fe465595 100644
--- a/pkg/testutils/lint/lint_test.go
+++ b/pkg/testutils/lint/lint_test.go
@@ -1865,6 +1865,7 @@ func TestLint(t *testing.T) {
                        pkgs, err := packages.Load(
                                &packages.Config{
                                        Mode: packages.NeedImports | packages.NeedName,
+                                       Dir: crdbDir,
                                },
                                pkgPath,
                        )
```

Jira issue: CRDB-42905

### PR DESCRIPTION
**Pull request by rickystewart**
We need to set `Dir` in the `packages.Load()` call or else the whole thing doesn't work. It would be really nice if it threw an error instead of simply doing nothing, but it is what it is. To guard against this in the future I added an error if the list is empty.

Fix the test then all existing violations, except for `raftlogger` and `rafttest` which will need some extra TLC by the owning team (see #132262)

Closes #132258

Epic: none
Release note: None

### CODE REVIEW

File: pkg/testutils/lint/lint_test.go [hunk 1]
```diff
@@ -1865,12 +1865,16 @@ func TestLint(t *testing.T) {
...
 				&packages.Config{
 					Mode: packages.NeedImports | packages.NeedName,
+					Dir:  crdbDir,
 				},
 				pkgPath,
 			)
 			if err != nil {
 				return errors.Wrapf(err, "error loading package %s", pkgPath)
 			}
+			if len(pkgs) == 0 {
```
Comment (herkolategan) [inline pkg/testutils/lint/lint_test.go:1875]: Small Nit: A comment explaining why this is check is required might help future readers. But definitely already much better than failing silently.

**Review by herkolategan — APPROVED** [review]
Linter changes look good to me, and works as expected now, Thanks!

**Review by rail — APPROVED** [review]

**Review by pav-kv — COMMENTED** [review]
LGTM for `pkg/raft`.

**Comment by rickystewart** [comment]
TFTRs!

bors r=rail,herkolategan

**Comment by rickystewart** [comment]
blathers backport 24.2
