### PR TITLE
changefeedccl: remove test race initial scan only csv

### LINKED ISSUE #157170: ccl/changefeedccl: TestChangefeedOnlyInitialScanCSV failed
ccl/changefeedccl.TestChangefeedOnlyInitialScanCSV [failed](https://mesolite.cluster.engflow.com/invocations/default/24909baa-f0e1-4c87-8dab-35b58c1550ce?testReportRun=3&testReportShard=1&testReportAttempt=1#targets-Ly9wa2cvY2NsL2NoYW5nZWZlZWRjY2w6Y2hhbmdlZmVlZGNjbF90ZXN0) on release-25.4.0-rc @ [4f4179243a351bc48c00dd9243dc56b8af98e210](https://github.com/cockroachdb/cockroach/commits/4f4179243a351bc48c00dd9243dc56b8af98e210):

```
=== RUN   TestChangefeedOnlyInitialScanCSV
    test_log_scope.go:171: test logs captured to: outputs.zip/logTestChangefeedOnlyInitialScanCSV3971836438
    test_log_scope.go:82: use -show-logs to present logs inline
    changefeed_test.go:10062: -- test log scope end --
test logs left over in: outputs.zip/logTestChangefeedOnlyInitialScanCSV3971836438
--- FAIL: TestChangefeedOnlyInitialScanCSV (2.18s)
=== RUN   TestChangefeedOnlyInitialScanCSV/kafka/initial_backfill_only_with_csv_multiple_tables
    changefeed_test.go:10044: 
        	Error Trace:	pkg/ccl/changefeedccl/changefeed_test.go:10044
        	            				pkg/ccl/changefeedccl/changefeed_test.go:10056
        	Error:      	Not equal: 
        	            	expected: 6
        	            	actual  : 2
        	Test:       	TestChangefeedOnlyInitialScanCSV/kafka/initial_backfill_only_with_csv_multiple_tables
--- FAIL: TestChangefeedOnlyInitialScanCSV/kafka/initial_backfill_only_with_csv_multiple_tables (0.45s)
=== RUN   TestChangefeedOnlyInitialScanCSV/kafka
    helpers_test.go:1394: making server as system tenant
    helpers_test.go:1470: making kafka feed factory
    testfeed_test.go:341: creating external connection
    testfeed_test.go:344: ran create external connection
    testfeed_test.go:341: creating external connection
    testfeed_test.go:344: ran create external connection
    testfeed_test.go:341: creating external connection
    testfeed_test.go:344: ran create external connection
--- FAIL: TestChangefeedOnlyInitialScanCSV/kafka (1.77s)
```

Parameters:
 - <code>attempt=1</code>
 - <code>run=3</code>
 - <code>shard=1</code>
<details><summary>Help</summary>
<p>

See also: [How To Investigate a Go Test Failure \(internal\)](https://cockroachlabs.atlassian.net/l/c/HgfXfJgM)
</p>
</details>
/cc @cockroachdb/cdc
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*TestChangefeedOnlyInitialScanCSV.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/bazci/githubpost/issues)

</sub>

Jira issue: CRDB-56392

### PR DESCRIPTION
**Pull request by log-head**
Previously, there was a race condition between two goroutines in the test. One is calling Next() on a feed which the other closes.

This patch replaces ignored goroutine error with deterministic read. Avoids race where the feed is closed while draining.

Fixes: #157170

Release note: None

### CODE REVIEW

File: pkg/ccl/changefeedccl/changefeed_test.go [hunk 1]
```diff
@@ -10142,32 +10142,29 @@ func TestChangefeedOnlyInitialScanCSV(t *testing.T) {
...
-							return err
-						}
-						if len(m.Resolved) > 0 {
-							continue
-						}
-						actualMessages = append(actualMessages, string(m.Value))
-					}
-				})
-				defer func(expectedPayload []string) {
+				defer func() {
```
Comment (aerfrei) [inline pkg/ccl/changefeedccl/changefeed_test.go]: nit: I think it might be nice to do this cleanup after each setup. e.g. we create the feed, and then in the following line do `defer closeFeed(t, feed)` and similarly with table creation, instead of this deferred anonymous cleanup function.

File: pkg/ccl/changefeedccl/changefeed_test.go [hunk 2]
```diff
@@ -10142,32 +10142,29 @@ func TestChangefeedOnlyInitialScanCSV(t *testing.T) {
...
+					}
+					var actual []string
+					for _, m := range msgs {
+						actual = append(actual, string(m.Value))
 					}
-				}(testData.expectedPayload)
+					sort.Strings(testData.expectedPayload)
+					sort.Strings(actual)
+					if !reflect.DeepEqual(testData.expectedPayload, actual) {
+						return errors.Newf("mismatch")
```
Comment (aerfrei) [inline pkg/ccl/changefeedccl/changefeed_test.go]: nit: maybe we can check if the length of actual is less than the expected length, in that case retry with a more descriptive error ("fewer changefeed messages than expected, retrying"), but otherwise, if the lengths are equal or even if len(actual)>len(expected), do a fatal error.

File: pkg/ccl/changefeedccl/changefeed_test.go [hunk 3]
```diff
@@ -10142,32 +10142,29 @@ func TestChangefeedOnlyInitialScanCSV(t *testing.T) {
...
-						}
-						actualMessages = append(actualMessages, string(m.Value))
-					}
-				})
-				defer func(expectedPayload []string) {
+				defer func() {
 					closeFeed(t, feed)
 					sqlDB.Exec(t, `DROP TABLE foo`)
 					sqlDB.Exec(t, `DROP TABLE bar`)
-					_ = g.Wait()
```
Comment (aerfrei) [inline pkg/ccl/changefeedccl/changefeed_test.go:10164]: I think if we moved this wait further up in this deferred function (e.g. we only do the check after the changefeed completed and don't drop the table or close the feed until after the check) that might also solve the issue. That being said, this seems like a weird pattern, so I think it's better to change it as you did. Nice!

I was curious why they did it this way, and I think I found out why. Theoretically, this makes sure that we actually wait for the changefeed to finish (as long as it takes) instead of just waiting for up to the timeout, but it seems remarkably unlikely that these test feeds will take any significant amount of time to finish so it doesn't seem to justify the weird pattern.

**Review by aerfrei — APPROVED** [review]

File: pkg/ccl/changefeedccl/changefeed_test.go (hunk 2 above)
Comment (log-head) [reply pkg/ccl/changefeedccl/changefeed_test.go]: Good suggestion! I found that it added a lot of complexity using a retry. readNextMessage already times out after 30s if the number of messages is less than expected. I added a wrapper in the error in this case, clarifying that it timed out waiting for enough messages.
```
operation "withTimeout-1140950072276418561" timed out after 30s (given timeout 30s): fewer changefeed messages than expected (timed out waiting)
```

File: pkg/ccl/changefeedccl/changefeed_test.go [hunk 4]
```diff
@@ -10131,43 +10131,43 @@ func TestChangefeedOnlyInitialScanCSV(t *testing.T) {
...
-							return err
-						}
-						if len(m.Resolved) > 0 {
-							continue
+				err := withTimeout(feed, assertPayloadsTimeout(), func(ctx context.Context) error {
+					msgs, err := readNextMessages(ctx, feed, len(testData.expectedPayload))
+					if err != nil {
+						if ctxErr := ctx.Err(); ctxErr != nil {
+							if errors.Is(ctxErr, context.DeadlineExceeded) {
+								return errors.New("fewer changefeed messages than expected (timed out waiting)")
```
Comment (rharding6373) [inline pkg/ccl/changefeedccl/changefeed_test.go]: Suggestion: include # of messages received and # of messages expected in the error for more information.

File: pkg/ccl/changefeedccl/changefeed_test.go [hunk 5]
```diff
@@ -10131,43 +10131,43 @@ func TestChangefeedOnlyInitialScanCSV(t *testing.T) {
...
-					closeFeed(t, feed)
-					sqlDB.Exec(t, `DROP TABLE foo`)
-					sqlDB.Exec(t, `DROP TABLE bar`)
-					_ = g.Wait()
-					require.Equal(t, len(expectedPayload), len(actualMessages))
-					sort.Strings(expectedPayload)
-					sort.Strings(actualMessages)
-					for i := range expectedPayload {
-						require.Equal(t, expectedPayload[i], actualMessages[i])
+					var actual []string
```
Comment (rharding6373) [inline pkg/ccl/changefeedccl/changefeed_test.go]: nit: Since we know how long the slice of actual messages should be, we can preallocate the slice here. See https://goperf.dev/01-common-patterns/mem-prealloc/ for examples.

File: pkg/ccl/changefeedccl/changefeed_test.go [hunk 6]
```diff
@@ -10131,43 +10131,43 @@ func TestChangefeedOnlyInitialScanCSV(t *testing.T) {
...
+					for _, m := range msgs {
+						actual = append(actual, string(m.Value))
+					}
+					sort.Strings(testData.expectedPayload)
+					sort.Strings(actual)
+					if !reflect.DeepEqual(testData.expectedPayload, actual) {
+						return errors.Newf("mismatch")
```
Comment (rharding6373) [inline pkg/ccl/changefeedccl/changefeed_test.go]: You could make the error message more descriptive here by including the expected and actual messages. Then debugging an error in the future will be easier.

File: pkg/ccl/changefeedccl/changefeed_test.go (hunk 4 above)
Comment (log-head) [reply pkg/ccl/changefeedccl/changefeed_test.go]: New error message when too few messages
`operation "withTimeout-1141143604194279425" timed out after 30s (given timeout 30s): got 5 of 6 expected changefeed messages: stopping job due to TestFeed timeout`

**Review by log-head — COMMENTED** [review]
Updated error messages and preallocated slice length.

**Review by rharding6373 — APPROVED** [review]
Thanks for making the updates! :lgtm: 

> @rharding6373 made 1 comment.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/160793#-:-OisFoRQ8HSs0beVOTSD:b-q8fgyi)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @aerfrei and @log-head).
