### PR TITLE
Split gossip.Key{ClusterID,Sentinel}.

### LINKED ISSUE #1056: Multi-node testing: killing first node after sentinel replication wedges entire cluster
Steps taken:
- init node 0
- start nodes 1, 2, 3
- wait until sentinel range is replicated (by watching /_status/gossip, confirm 3 replicas)
- kill node 0
- after approx 90s, nodes 1, 2 and 3 log: "missing sentinel gossip X; assuming partition and reconnecting"
- restart node 0
- node 0 tries to connect to the gossip network but fails with the same message.

Result: all nodes are assuming partition and are attempting to reconnect to gossip. Cluster is dead.

### PR DESCRIPTION
**Pull request by bdarnell**
KeyClusterID is now gossiped by any node with a replica of the first
range, instead of just the lease holder. Gossip is considered
"connected" as soon as the cluster ID is seen, which allows the node to
complete the startup process and acquire the lease.

KeySentinel continues to be gossiped only by the first range lease
holder, and is used to detect partitions in the gossip network.

Slightly generalize the gossip acceptance tests and increase the
timeout. Fix an error-handling bug in server/raft_transport.go.
Improve error messages from util.SucceedsWithin.

Fixes #1056.

### CODE REVIEW

File: util/testing.go [hunk 1]
```diff
@@ -149,5 +149,5 @@ func SucceedsWithin(t Tester, duration time.Duration, fn func() error) {
 		}
 		time.Sleep(wait)
 	}
-	t.Fatalf("condition failed to evaluate within %s: %s", duration, lastErr)
+	t.Fatal(ErrorfSkipFrames(1, "condition failed to evaluate within %s: %s", duration, lastErr))
```
Comment (tamird) [inline util/testing.go]: neat

File: acceptance/run.sh [hunk 2]
```diff
@@ -3,4 +3,4 @@
 cd $(dirname $0)/..
 build/builder.sh make install
 set -x
-go test -v -tags acceptance ./acceptance ${GOFLAGS} -run "${TESTS:-.*}" -timeout ${TESTTIMEOUT:-1m} ${TESTFLAGS}
```
Comment (tamird) [inline acceptance/run.sh]: did you intend for this to be in the final version of this?

File: acceptance/gossip_peerings_test.go [hunk 3]
```diff
@@ -99,5 +123,42 @@ func TestGossipPeerings(t *testing.T) {
...
+	checkRangeReplication(t, l, 10*time.Second)
+
+	log.Infof("stopping all nodes")
+	for _, node := range l.Nodes {
+		node.Stop(5)
+	}
+
+	log.Infof("restarting all nodes")
+	for _, node := range l.Nodes {
+		node.Restart(5)
```
Comment (tamird) [inline acceptance/gossip_peerings_test.go]: should this `Start` rather than `Restart`?

Comment (tamird) [inline acceptance/gossip_peerings_test.go]: Ergh, seems that's quite a different thing

File: acceptance/gossip_peerings_test.go [hunk 4]
```diff
@@ -83,14 +107,14 @@ func TestGossipPeerings(t *testing.T) {
 	l.Start()
 	defer l.Stop()
 
-	checkGossipPeerings(t, l, 20*time.Second)
+	checkGossip(t, l, 20*time.Second, hasPeers(len(l.Nodes)))
```
Comment (tamird) [inline acceptance/gossip_peerings_test.go]: `hasPeers(len(l.Nodes))` can be extracted

**Comment by tamird** [comment]
LGTM

File: acceptance/gossip_peerings_test.go [hunk 5]
```diff
@@ -22,35 +22,56 @@ package acceptance
...
+	if _, ok := infos[gossip.KeyClusterID]; !ok {
+		return util.Errorf("cluster ID not found")
+	}
+	return nil
+}
 
+// checkGossip fetches the gossip infoStore from each node and invokes the given
+// function. The test passes if the function returns 0 for every node,
+// retrying for up to the given duration.
+func checkGossip(t *testing.T, l *localcluster.Cluster, d time.Duration,
```
Comment (tamird) [inline acceptance/gossip_peerings_test.go]: maybe move this up near the declaration of `checkGossipFunc` so that the comment is near that type

**Comment by petermattis** [comment]
LGTM

File: storage/range.go [hunk 6]
```diff
@@ -909,12 +909,20 @@ func (r *Range) maybeGossipFirstRange() error {
 	if !r.IsFirstRange() {
 		return nil
 	}
+
 	ctx := r.context()
+
+	// Gossip the cluster ID from all replicas of the first range.
+	log.Infof("gossiping first range from store %d, range %d", r.rm.StoreID(), r.Desc().RaftID)
```
Comment (spencerkimball) [inline storage/range.go]: Do you think we should move the various and sundry log messages about gossiping into gossip? I think a node gossiping information should probably always be recorded in its logs, and that would make all of those events consistent.

**Comment by spencerkimball** [comment]
LGTM

File: acceptance/gossip_peerings_test.go (hunk 4 above)
Comment (bdarnell) [inline acceptance/gossip_peerings_test.go]: Yeah, it's a little repetitive but I don't think it's bad enough to pull out and name. And we will presumably have other tests where the number of peers is not constant.

File: acceptance/gossip_peerings_test.go (hunk 3 above)
Comment (bdarnell) [inline acceptance/gossip_peerings_test.go]: Yeah, Start() takes some extra arguments; Restart() just reuses the configuration that was originally passed to Start().

File: acceptance/run.sh (hunk 2 above)
Comment (bdarnell) [inline acceptance/run.sh]: Yes. All the acceptance tests are unfortunately quite slow; we're already up to 55s on my machine.

File: storage/range.go (hunk 6 above)
Comment (bdarnell) [inline storage/range.go]: Perhaps, especially now that we can pass additional information like the range ID through a Context object.

File: acceptance/gossip_peerings_test.go (hunk 5 above)
Comment (bdarnell) [inline acceptance/gossip_peerings_test.go]: Moved.

Comment (tamird) [inline acceptance/gossip_peerings_test.go]: :+1:
