### PR TITLE
sql: return pgerror when creating ARRAY of type VOID

### LINKED ISSUE #84224: Internal error with VOID type in ARRAY
**Describe the problem**
The VOID type appears not to be supported in arrays, and a simple test throws an internal error:
```
root@localhost:26257/defaultdb> SELECT ARRAY[''::VOID];
ERROR: internal error: oid 0 couldn't be mapped to array oid
SQLSTATE: XX000
DETAIL: stack trace:
github.com/cockroachdb/cockroach/pkg/sql/types/oid.go:230: CalcArrayOid()
github.com/cockroachdb/cockroach/pkg/sql/types/types.go:1119: MakeArray()
github.com/cockroachdb/cockroach/pkg/sql/sem/tree/type_check.go:1596: TypeCheck()
github.com/cockroachdb/cockroach/pkg/sql/sem/tree/type_check.go:267: TypeCheck()
github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder/scope.go:462: resolveType()
github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder/project.go:160: analyzeSelectList()
github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder/project.go:94: analyzeProjectionList()
github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder/select.go:992: buildSelectClause()
github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder/select.go:929: buildSelectStmtWithoutParens()
github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder/select.go:902: func1()
github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder/with.go:115: processWiths()
github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder/select.go:901: buildSelect()
github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder/builder.go:282: buildStmt()
github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder/builder.go:242: buildStmtAtRoot()
github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder/builder.go:216: Build()
github.com/cockroachdb/cockroach/pkg/sql/plan_opt.go:552: buildExecMemo()
github.com/cockroachdb/cockroach/pkg/sql/plan_opt.go:225: makeOptimizerPlan()
github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:1363: makeExecPlan()
github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:1045: dispatchToExecutionEngine()
github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:690: execStmtInOpenState()
github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:145: execStmt()
github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:1892: func1()
github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:1896: execCmd()
github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:1818: run()
github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:757: ServeConn()
github.com/cockroachdb/cockroach/pkg/sql/pgwire/conn.go:724: func1()
runtime/asm_amd64.s:1581: goexit()
```
Either a nicer error message should be returned indicating VOID is not supported in arrays, or array support should be added.

**Environment:**
 - CockroachDB version 22.1

Jira issue: CRDB-17526

### PR DESCRIPTION
**Pull request by mgartner**
Arrays of type `VOID` are not supported. This commit replaces an
internal error with a user error when trying to create them.

Fixes #84224

Release note: None

### CODE REVIEW

File: pkg/sql/sem/tree/type_check.go [hunk 1]
```diff
@@ -1943,6 +1943,9 @@ func (expr *Array) TypeCheck(
 		return nil, err
 	}
 
+	if typ.Family() == types.VoidFamily {
+		return nil, pgerror.Newf(pgcode.UndefinedObject, "array of type VOID does not exist")
```
Comment (mw5h) [inline pkg/sql/sem/tree/type_check.go]: Does not exist? Shouldn't this be unsupported?

Comment (mgartner) [reply pkg/sql/sem/tree/type_check.go]: Fixed.

**Comment by mgartner** [comment]
TFTR!

bors r+

**Review by Uzair5162 — APPROVED** [review]
