### PR TITLE
backupccl: backup correctly tries reading in from base directory if l…

### LINKED ISSUE #77312: backupccl: directory does not exist error is not correctly caught when reading checkpoint/latest files
When reading in the checkpoint/latest files, we first try reading in from the progress/latest directory. However, in order to not break previous backups, where checkpoint/latest files don't exist in the progress/latest directory, we also read in from the base directory in the scenario that we did not find a file in our first attempt. However if the first attempt fails due to another error, it will not attempt again.

However, we currently only catch for `cloud.ErrFileDoesNotExist` and not for `not a directory`. On an old backup, the progress/latest will never exist, so it will never attempt the base directory even if it exists there. For checkpoint files, this will cause the backup to start over. For latest files, it may break usage of the latest file.

**To Reproduce**
Via @adityamaru 

1. take a cluster backup on 21.2 to ‘nodelocal://0/foo’
2. take an incremental backup to the same collection
3. stop the 21.2 cluster
4. start a master cluster with the same cockroach-data/
5. create a table
6. backup into latest in 'nodelocal://0/foo'

**Expected behavior**
Step 6 should correctly find the latest file and take a incremental backup like normal. Instead it errors out and throws `ERROR: open <filepath>/LATEST: not a directory`

To fix this we can either catch the error or always attempt to read in from the base directory on error. Always reading from the base directory would be the easiest fix, and only cause an extra read in the rare case that the latest/checkpoint is wrong (say corrupted or checksum mismatch), and the BACKUP/RESTORE would error out anyway.

However if we want to continue only retrying if it was a file/directory not found, we would have to catch it at the external_storage level for each storage and wrap it as we currently are only catching `ErrFileDoesNotExist`. This should still be fairly easy to do but just not as trivial as the solution above.

Jira issue: CRDB-13525

### PR DESCRIPTION
**Pull request by DarrylWong**
…atest/checkpoint files aren't found

Before, we only tried reading from the base directory if we caught a ErrFileDoesNotExist error. However
this does not account for the potential error thrown when the progress/latest directories don't exist.
This changes it so we now correctly retry reading from the base directory.

We also put the latest directory inside of a metadata directory, in order to avoid any potential
conflicts with there being a latest file and latest directory in the same base directory.

Also wraps errors in findLatestFile and readLatestCheckpointFile for more clarity when both base and
latest/progress directories fail to read.

Fixes https://github.com/cockroachdb/cockroach/issues/77312

Epic CRDB-7586

Release justification: Low risk bug fix
Release note: none

### CODE REVIEW

**Comment by DarrylWong** [comment]
Didn't do too much testing since it was getting late, but basically I just went with the first easier solution (where we just always try reading from base directory on error) just to confirm that it was indeed the problem. Just running a few tests it seemed like it didn't break anything and the original issue seemed fixed. But i'll give it some more testing tomorrow and figure out what solution we want to go with.

File: pkg/ccl/backupccl/backup_destination.go [hunk 1]
```diff
@@ -344,13 +344,12 @@ func readLatestFile(
 func findLatestFile(
 	ctx context.Context, exportStore cloud.ExternalStorage,
 ) (ioctx.ReadCloserCtx, error) {
-	latestFile, err := exportStore.ReadFile(ctx, latestHistoryDirectory+"/"+latestFileName)
+	latestFile, err := exportStore.ReadFile(ctx, backupMetadataDirectory+"/"+latestHistoryDirectory+"/"+latestFileName)
```
Comment (adityamaru) [inline pkg/ccl/backupccl/backup_destination.go:347]: can we just define `latestHistoryDirectory` var as `backupMetadataDirectory/latest`. I think it is easier to read that way.

File: pkg/ccl/backupccl/backup_destination.go [hunk 2]
```diff
@@ -344,13 +344,12 @@ func readLatestFile(
...
 	if err != nil {
-		if !errors.Is(err, cloud.ErrFileDoesNotExist) {
-			return nil, err
-		}
-
 		latestFile, err = exportStore.ReadFile(ctx, latestFileName)
+		if err != nil {
+			return nil, errors.Wrap(err, "Latest file could not be read in base or metadata directory")
```
Comment (adityamaru) [inline pkg/ccl/backupccl/backup_destination.go:351]: nit: s/Latest/LATEST/g

File: pkg/ccl/backupccl/backup_job.go [hunk 3]
```diff
@@ -810,15 +809,13 @@ func (b *backupResumer) deleteCheckpoint(
 		defer exportStore.Close()
 		// The checkpoint in the base directory should only exist if the cluster
```
Comment (adityamaru) [inline pkg/ccl/backupccl/backup_job.go:810]: nit: comment is outdated, can we update it to say that we first attempt to delete from base directory to account for older backups, and then from the progress directory

File: pkg/ccl/backupccl/backup_job.go [hunk 4]
```diff
@@ -810,15 +809,13 @@ func (b *backupResumer) deleteCheckpoint(
...
 		// version isn't BackupDoesNotOverwriteLatestAndCheckpoint.
-		if !cfg.Settings.Version.IsActive(ctx, clusterversion.BackupDoesNotOverwriteLatestAndCheckpoint) {
-			err = exportStore.Delete(ctx, backupProgressDirectory)
-			if err != nil {
-				return err
-			}
+		err = exportStore.Delete(ctx, backupManifestCheckpointName)
+		if err != nil {
+			log.Warningf(ctx, "unable to delete checkpointed backup in base directory descriptor: %+v", err)
```
Comment (adityamaru) [inline pkg/ccl/backupccl/backup_job.go:814]: nit: unable to delete checkpointed backup descriptor file in base directory

File: pkg/ccl/backupccl/manifest_handling.go [hunk 5]
```diff
@@ -1276,6 +1280,7 @@ func writeNewCheckpointFile(
 	filename string,
 	descBuf []byte,
 ) error {
+	filename = strings.TrimPrefix(filename, "/")
```
Comment (adityamaru) [inline pkg/ccl/backupccl/manifest_handling.go:1283]: can we add a comment about why we're doing this? I'd also love a test if there was something that was failing before this.

**Review by adityamaru — COMMENTED** [review]
Thanks for doing this. Would it be possible to write a unit test that blocks the cluster from upgrading past the `BackupDoesNotOverwriteLatestAndCheckpoint` version, taking a backup, then allowing it to upgrade, and running an incremental on the same chain?

File: pkg/ccl/backupccl/backup_destination.go (hunk 2 above)
Comment (DarrylWong) [reply pkg/ccl/backupccl/backup_destination.go]: Wasn't 100% sure what you meant by this, did you mean in place of "latest file" or the "metadata directory"

File: pkg/ccl/backupccl/manifest_handling.go (hunk 5 above)
Comment (DarrylWong) [reply pkg/ccl/backupccl/manifest_handling.go:1286]: So the thing that was failing was userfile specific, since userfile is the only one where it doesn't have file system semantics. So it could happen for anything where you pass a file path. For example I only used BACKUP INTO when testing but thats different than BACKUP TO for how it formats the path, so thats why I never caught the bug.

So I guess I could easily just write a test case that does BACKUP TO and SHOW BACKUP on a userfile to see if it works in that case, but I'm not sure if that really addresses the root issue?

File: pkg/ccl/backupccl/backup_destination.go (hunk 2 above)
Comment (adityamaru) [reply pkg/ccl/backupccl/backup_destination.go]: ahh just change `Latest` to `LATEST` since thats the sentinel file name we use.

**Review by adityamaru — APPROVED** [review]
I'd still like to see the test we discussed earlier in this PR, but happy to do that as a fast follow.
