### PR TITLE
pgwire: limit size of SSL frames sent

### LINKED ISSUE #147890: A query with a specific row size hangs the connection
**Describe the problem**

Bug reported in https://github.com/psycopg/psycopg/issues/1107

A query with a very specific row size hangs a CockroachDB connection when run twice. The same query works as expected in PostgreSQL.

**To Reproduce**

<details>
<summary>The following script reproduces the condition.</summary>

```python
import os

os.environ["PSYCOPG_IMPL"] = "python"

import asyncio
import logging
import psycopg
from psycopg import pq
from psycopg.pq._debug import PGconnDebug

pq.PGconn = PGconnDebug

logging.basicConfig(level=logging.DEBUG)
logging.getLogger("psycopg").setLevel(logging.DEBUG)

# Test CRDB with 1, Postgres with 0
if 1:
    DB_HOST = "127.0.0.1"
    DB_USER = "issue"
    DB_PASSWORD = "issue"
    DB_SSLMODE = "require"
    DB_NAME = "issue"
    DB_PORT = 26257
else:
    DB_HOST = "127.0.0.1"
    DB_USER = "piro"
    DB_PASSWORD = ""
    DB_SSLMODE = "require"
    DB_NAME = "psycopg3_test"
    DB_PORT = 5432

dsn = " ".join(
    [
        f"user={DB_USER}",
        f"password={DB_PASSWORD}",
        f"host=localhost",
        f"hostaddr={DB_HOST}",
        f"port={DB_PORT}",
        f"dbname={DB_NAME}",
    ]
)

logging.info("DB_DSN: %s", dsn)

# Fake query to hit bug
# return with 8 colums
# return with 238 lines
# return with 166 char in colum value
# return with 15 char min in colum name

query = """
    SELECT
        '000000000000000000000' AS aaaaaaaa,
        '000000000000000000000' AS b,
        '000000000000000000000' AS c,
        '000000000000000000000' AS d,
        '000000000000000000000' AS e,
        '000000000000000000000' AS f,
        '000000000000000000000' AS g,
        '0000000000000000000' AS h
    FROM generate_series(1, 238)
"""


def main() -> None:
    with psycopg.connect(
        dsn, sslmode=DB_SSLMODE, autocommit=True
    ) as conn:
        conn.pgconn.trace(2)
        conn.pgconn.set_trace_flags(
            pq.Trace.SUPPRESS_TIMESTAMPS | pq.Trace.REGRESS_MODE
        )

        for i in range(0, 3):
            logging.info("connection: %s", conn)
            logging.info("querying")
            cur = conn.execute(query)
            logging.info("queried")
            r = cur.fetchall()
            logging.info("total result: %s", len(r))


if __name__ == "__main__":
    main()
```

</details>

Run a CRDB server in a docker using

```
docker run --rm -p 8080:8080 -p 26257:26257 -e COCKROACH_USER=issue -e COCKROACH_DATABASE=issue -e COCKROACH_PASSWORD=issue -it cockroachdb/cockroach:latest-v25.1 start-single-node
```

Run the script: it will hang.

I have run the script against CRDB and PG:

```
python -u test-1107.py 2>test-sync-bad.txt  # with "if 1", ctrl-c when hangs
python -u test-1107.py 2>test-sync-ok.txt  # with "if 0"
```

Comparing the resulting files I can see that CRDB ends up returning one `DataRow` message less, and the query ends up hung in ACTIVE state.

**Environment:**
 - CockroachDB 25.1 (likely other affected)
 - Server OS: Docker Linux
 - Client app: Psycopg 3 on Linux

Jira issue: CRDB-51297

Epic CRDB-49398

### PR DESCRIPTION
**Pull request by fqazi**
Previously, CRDB bumped up the result buffer size
(sql.defaults.results_buffer.size) from 16k to a higher value. After this change we started seeing asynchronous libpq clients start hanging because they can only consume 8 kilobytes of data at a time. As a result large SSL frames can be problematic in this configuration. To address this, this patch limits CRDB to sending the result buffer at 8 kilobytes at a time.

Fixes: #147890

Release note (bug fix): Addressed a bug where libpq clients using the async API could hang with large result sets (psycopg, activerecord, ruby-pg)

### CODE REVIEW

**Comment by fqazi** [comment]
Sadly one of the acceptance tests was disabled because a bug was found in node-postgres: https://github.com/brianc/node-postgres/issues/3487. We can re-enable it once its fixed or add a work around in CRDB.

File: pkg/acceptance/testdata/node/base-test.js [hunk 1]
```diff
@@ -71,6 +71,10 @@ describe('arrays', () => {
   });
 });
 
+// Temporarily disabled until https://github.com/brianc/node-postgres/issues/3487
+// gets resolved. The binary encoding in node-postgres was regressed at some
+// point leading to protocol violation errors.g
+/*
```
Comment (rafiss) [inline pkg/acceptance/testdata/node/base-test.js:77]: nice find!

**Review by rafiss — APPROVED** [review]
great work tracking this down!

**Comment by rafiss** [comment]
do you know how far we should backport this?

**Comment by fqazi** [comment]
> do you know how far we should backport this?

 @rafiss  We need to go till 24.1 because of: https://github.com/cockroachdb/cockroach/pull/124633

**Comment by fqazi** [comment]
@rafiss TFTR!

bors r+

**Comment by fqazi** [comment]
blathers auth-check

**Comment by fqazi** [comment]
blathers backport 25.1

**Comment by yuzefovich** [comment]
For posterity (no action needed), I tracked down a regression on a microbenchmark that emits a lot of data in the output to this change:
```
args: benchdiff "--run=^BenchmarkRenderPlanning/rows=512/renders=4096" "--old=c52adfc3^" "--new=c52adfc3" "./pkg/sql/colexec/colbuilder" "-b"

name                                     old time/op    new time/op    delta
RenderPlanning/rows=512/renders=4096-24     218ms ± 2%     238ms ± 1%  +9.06%  (p=0.000 n=9+10)

name                                     old alloc/op   new alloc/op   delta
RenderPlanning/rows=512/renders=4096-24     382MB ± 0%     381MB ± 0%    ~     (p=0.143 n=10+10)

name                                     old allocs/op  new allocs/op  delta
RenderPlanning/rows=512/renders=4096-24      157k ± 0%      149k ± 9%    ~     (p=0.143 n=10+10)
```
