### PR TITLE
restore: gracefully handle lookup of dropped temp system tables

### LINKED ISSUE #148088: restore: stuck in state reverting after lookup on dropped temp system tables
**Describe the problem**

If temporary system databases have already been dropped and restore goes into the `reverting` state, the cleanup process will attempt to lookup the temporary system tables and fail (in `setDescriptorsOffline` in Online Restore and `dropDescriptors` in Classic Restore). This forces the restore job into an endless retry loop.

**To Reproduce**

**Classic Restore:**

1. Perform a full cluster backup.
2. Restore from the full cluster backup.
3. Force an error _after_ system tables have been dropped, the easiest way is by adding an error return after these lines: https://github.com/cockroachdb/cockroach/blob/9b3b2bc0a873e19704babd230c08c7a5bc62f35e/pkg/backup/restore_job.go#L2070-L2082
4. Watch the job go into the `reverting` state and get stuck.

**Online Restore:**

1. Perform a full cluster backup.
2. Set the pausepoint `jobs.debug.pausepoints = 'restore.before_download'`.
3. Restore from the full cluster backup with option `experimental deferred copy`.
4. Wait for the download job to pause.
5. Delete an SST from the backup.
6. Remove the pausepoint and resume the download job.
7. Wait for the download job to fail and it will get stuck in the `reverting` state.

**Root Cause**

After dropping the system tables, GC will begin cleaning up the descriptors. It is very likely that by the time that restore recovery begins looking up the descriptors in the restore details to drop them, some of the temporary system tables have already been GC'd and therefore deleted from `system.descriptor`. This causes the lookup to fail and stop the cleanup.

Jira issue: CRDB-51393

Epic CRDB-51394

### PR DESCRIPTION
**Pull request by kev-cao**
Previously, if a lookup was attempted on a dropped system table (e.g. during cleanup after a failed restore), an error would be surfaced. This caused the restore jobs in the reverting state to be stuck in a retry loop. However, if we are attempting to do cleanup, we can simply skip any dropped descriptors, which this commit teaches restore to do.

Epic: CRDB-51394

Fixes: #148088

Release note: Restore no longer gets stuck in the reverting state after failed cleanup of dropped temporary system tables.

### CODE REVIEW

**Review by msbutler — APPROVED** [review]
Nice! a couple things. Could you split this up into 2 commits: 1) for the regular restore changes, 2) for the online restore changes. They have different backport considerations.

Also, we don't backport to rc branches, except in extraordinary circumstances. Lets auto backport to 25.2 for now.

**Review by msbutler — COMMENTED** [review]
oh, looks like you have a good test failure to look into

File: pkg/backup/restore_online_test.go [hunk 1]
```diff
@@ -204,12 +204,71 @@ func TestOnlineRestoreRecovery(t *testing.T) {
...
-	parsedURI, err := url.Parse(strings.Replace(uri, "'", "", -1))
-	sqlDB.QueryRow(t, filePathQuery).Scan(&filePath)
+	var filePath, spanStart, spanEnd string
+	// TODO (kev-cao): We should update this query to delete a random SST file
+	// instead of only a user-table. However, this will require further
+	// investigation into https://github.com/cockroachdb/cockroach/pull/148098.
+	filePathQuery := fmt.Sprintf(
+		`SELECT path, start_pretty, end_pretty FROM
+		(
+			SELECT row_number() OVER (), *
```
Comment (msbutler) [inline pkg/backup/restore_online_test.go:263]: just curious: why do we need this OVER() clause? could we simply order by end key and grab the file with the largest end key?

**Review by msbutler — APPROVED** [review]
nice investigation!

File: pkg/backup/restore_online_test.go (hunk 1 above)
Comment (kev-cao) [reply pkg/backup/restore_online_test.go:263]: Oh this was the result of just trying out different queries and it sorta converged on this. Sorting by largest end key is simpler though, updating

Comment (kev-cao) [reply pkg/backup/restore_online_test.go:263]: Oh actually, this doesn't work because a span ending in `Tenant/3/Table/106` actually comes _before_ a span ending in `Tenant/3/Table/6`.

Comment (msbutler) [reply pkg/backup/restore_online_test.go:263]: so, what exactly does this OVER() thing do? why is it guaranteed to grab a non system table file?

Comment (kev-cao) [reply pkg/backup/restore_online_test.go:263]: The output of `SHOW BACKUP FILES` does order everything as you would expect, but it lists all the system tables first (`SHOW BACKUP FILES` iterates over `BackupManifest_Files` that are sorted with `FileCmp`). So if we always grab the last file, then unless there are no user-tables, it is guaranteed to be an SST file covering a user table.

`row_number() OVER ()` just numbers each row in the original output so that I can then reverse the order.

**Comment by kev-cao** [comment]
TFTR!

bors r=msbutler

**Comment by kev-cao** [comment]
bors r=msbutler
