### PR TITLE
sql: fast path pg_roles lookup for system roles

### LINKED ISSUE #167379: roachtest: backup-restore/small-ranges failed
**Note:** This build has runtime assertions enabled. If the same failure was hit in a run without assertions enabled, there should be a similar failure without this message. If there isn&#39;t one, then this failure is likely due to an assertion violation or (assertion) timeout.

roachtest.backup-restore/small-ranges [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/21294949?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/21294949?buildTab=artifacts#/backup-restore/small-ranges) on master @ [f664d721208396abddf8e14e862ca09f4c07eec5](https://github.com/cockroachdb/cockroach/commits/f664d721208396abddf8e14e862ca09f4c07eec5):

Failed with:

```
(test_runner.go:2684).func1: task ``run-schemachange`` returned error: full command output in run_064457.236307962_n4_COCKROACHRANDOMSEED5.log: COMMAND_PROBLEM: exit status 134
(monitor.go:267).Wait: monitor failure: error waiting for job 1163401288921808899 to finish: context canceled
test artifacts and logs in: /artifacts/backup-restore/small-ranges/run_1
```
Cluster Node to Ip Mapping:
| Node | Public IP | Private IP |
| --- | --- | --- |
| teamcity-21294949-1775110919-18-n4cpu4-0001 | 104.196.35.201 | 10.142.3.94 |
| teamcity-21294949-1775110919-18-n4cpu4-0002 | 34.26.245.247 | 10.142.3.93 |
| teamcity-21294949-1775110919-18-n4cpu4-0003 | 34.148.11.186 | 10.142.3.95 |
| teamcity-21294949-1775110919-18-n4cpu4-0004 | 34.75.244.233 | 10.142.0.232 |

Parameters:
 - <code>arch=amd64</code>
 - <code>cloud=gce</code>
 - <code>coverageBuild=false</code>
 - <code>cpu=4</code>
 - <code>diskCount=0</code>
 - <code>encrypted=true</code>
 - <code>fs=ext4</code>
 - <code>localSSD=true</code>
 - <code>runtimeAssertionsBuild=true</code>
<details><summary>Help</summary>
<p>

See: [roachtest README](https://github.com/cockroachdb/cockroach/blob/master/pkg/cmd/roachtest/README.md)

See: [How To Investigate \(internal\)](https://cockroachlabs.atlassian.net/l/c/SSSBr8c7)

See: [Grafana](https://go.crdb.dev/roachtest-grafana/teamcity-21294949/backup-restore-small-ranges/1775111963979/1775113223868)

See: [Datadog Logs](https://us5.datadoghq.com/logs?query=service%3Aroachtest+%40cluster%3Ateamcity-21294949-1775110919-18-n4cpu4&from_ts=1775111963979&to_ts=1775113223868&live=false&storage=flex_tier)

</p>
</details>
<details><summary>Same failure on other branches</summary>
<p>

- #164995 roachtest: backup-restore/small-ranges failed [A-disaster-recovery B-runtime-assertions-enabled C-test-failure O-roachtest O-robot P-2 T-sql-foundations branch-release-26.1]
</p>
</details>
/cc @cockroachdb/disaster-recovery
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*backup-restore/small-ranges.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/bazci/githubpost/issues)

</sub>

Jira issue: CRDB-62422

### LINKED ISSUE #167516: roachtest: backup-restore/online-restore failed
**Note:** This build has runtime assertions enabled. If the same failure was hit in a run without assertions enabled, there should be a similar failure without this message. If there isn&#39;t one, then this failure is likely due to an assertion violation or (assertion) timeout.

roachtest.backup-restore/online-restore [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/21298227?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/21298227?buildTab=artifacts#/backup-restore/online-restore) on master @ [6cea22fb85383a186fefaa5d87f69db0ecb215c7](https://github.com/cockroachdb/cockroach/commits/6cea22fb85383a186fefaa5d87f69db0ecb215c7):

Failed with:

```
(test_runner.go:2684).func1: task ``run-schemachange`` returned error: full command output in run_075306.696826775_n4_COCKROACHRANDOMSEED7.log: COMMAND_PROBLEM: exit status 134
(monitor.go:267).Wait: monitor failure: error waiting for job 1163981387680055297 to finish: context canceled
test artifacts and logs in: /artifacts/backup-restore/online-restore/run_1
```
Cluster Node to Ip Mapping:
| Node | Public IP | Private IP |
| --- | --- | --- |
| teamcity-21298227-1775283892-28-n4cpu4-0001 | 35.237.92.85 | 10.142.0.171 |
| teamcity-21298227-1775283892-28-n4cpu4-0002 | 34.23.9.241 | 10.142.0.169 |
| teamcity-21298227-1775283892-28-n4cpu4-0003 | 35.237.141.37 | 10.142.2.178 |
| teamcity-21298227-1775283892-28-n4cpu4-0004 | 35.185.90.243 | 10.142.0.42 |

Parameters:
 - <code>arch=amd64</code>
 - <code>cloud=gce</code>
 - <code>coverageBuild=false</code>
 - <code>cpu=4</code>
 - <code>diskCount=0</code>
 - <code>encrypted=true</code>
 - <code>fs=ext4</code>
 - <code>localSSD=true</code>
 - <code>metamorphicWriteBuffering=true</code>
 - <code>runtimeAssertionsBuild=true</code>
<details><summary>Help</summary>
<p>

See: [roachtest README](https://github.com/cockroachdb/cockroach/blob/master/pkg/cmd/roachtest/README.md)

See: [How To Investigate \(internal\)](https://cockroachlabs.atlassian.net/l/c/SSSBr8c7)

See: [Grafana](https://go.crdb.dev/roachtest-grafana/teamcity-21298227/backup-restore-online-restore/1775288817735/1775290081189)

See: [Datadog Logs](https://us5.datadoghq.com/logs?query=service%3Aroachtest+%40cluster%3Ateamcity-21298227-1775283892-28-n4cpu4&from_ts=1775288817735&to_ts=1775290081189&live=false&storage=flex_tier)

</p>
</details>
<details><summary>Same failure on other branches</summary>
<p>

- #164609 roachtest: backup-restore/online-restore failed [C-test-failure O-roachtest O-robot P-2 T-sql-foundations branch-release-26.1.1-rc]
</p>
</details>
/cc @cockroachdb/disaster-recovery
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*backup-restore/online-restore.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/bazci/githubpost/issues)

</sub>

Jira issue: CRDB-62502

### PR DESCRIPTION
**Pull request by fqazi**
This commit adds a fast path for resolving the names of well-known system roles (node, root, admin, public) from their OIDs.

When querying views like information_schema.routines, CockroachDB evaluates pg_has_role() for every builtin function. Because built-in functions are owned by 'node', this triggered thousands of internal queries to the pg_catalog.pg_roles virtual table, causing severe RPC stalls and watchdog timeouts on larger clusters. By resolving these common system OIDs in memory without a query, we eliminate this N+1 query explosion.

Fixes: #167516
Fixes: #167379

Release note (performance improvement): Improve performance of information_schema.routines when querying role information for builtins.

### CODE REVIEW

File: pkg/sql/sem/builtins/pg_builtins.go [hunk 1]
```diff
@@ -515,12 +515,22 @@ func getNameForArg(
...
+			}
+		}
 		arg = tree.NewDString(u.Normalized())
 		query = fmt.Sprintf("SELECT %s FROM pg_catalog.%s WHERE %s = $1 LIMIT 1", pgCol, pgTable, pgCol)
 	case *tree.DOid:
 		if t.Oid == username.PublicRoleID {
 			return username.PublicRole, nil
 		}
+		if pgTable == "pg_roles" {
+			if name, ok := evalCtx.Planner.RoleNameFromOID(ctx, t.Oid); ok {
```
Comment (rafiss) [inline pkg/sql/sem/builtins/pg_builtins.go]: what's the benefit for adding this to the `Planner` interface versus just having the logic inlined here?

mapping OID to role name seems like something that's specific to these PG builtins. also, the function only works for 3 hardcoded role names, and IMO leaving that in the interface could be misleading for callers who might think it can map any OID.

**Review by rafiss — COMMENTED** [review]
great find! just confirming no need to backport this since i think this only became a problem after https://github.com/cockroachdb/cockroach/pull/167128

File: pkg/sql/sem/builtins/pg_builtins.go (hunk 1 above)
Comment (fqazi) [reply pkg/sql/sem/builtins/pg_builtins.go]: The makeOidHasher call we need is private, so we can't import it into the sem/builtins sadly :(. I renamed the function to make it clear that it only resolves system rolenames.

**Review by fqazi — COMMENTED** [review]
> @fqazi made 1 comment.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/167810)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on rafiss).

**Review by rafiss — APPROVED** [review]
ah thanks for explaining. makes sense!
