### PR TITLE
kvserver: remove TestReplicaRemovalClosesProposalQuota

### LINKED ISSUE #96932: kv/kvserver: TestReplicaRemovalClosesProposalQuota failed
kv/kvserver.TestReplicaRemovalClosesProposalQuota [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_StressBazel/8657147?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_StressBazel/8657147?buildTab=artifacts#/) on master @ [9ea0ef2f6a8e31e22c7350de5cacd9c5992d07a0](https://github.com/cockroachdb/cockroach/commits/9ea0ef2f6a8e31e22c7350de5cacd9c5992d07a0):

```
        goroutine 6 [chan receive]:
        github.com/cockroachdb/cockroach/pkg/util/log.flushDaemon()
        	github.com/cockroachdb/cockroach/pkg/util/log/log_flush.go:75 +0x5a
        created by github.com/cockroachdb/cockroach/pkg/util/log.init.5
        	github.com/cockroachdb/cockroach/pkg/util/log/log_flush.go:41 +0x25
        goroutine 7 [chan receive, 5 minutes]:
        github.com/cockroachdb/cockroach/pkg/util/log.signalFlusher()
        	github.com/cockroachdb/cockroach/pkg/util/log/log_flush.go:98 +0xdc
        created by github.com/cockroachdb/cockroach/pkg/util/log.init.5
        	github.com/cockroachdb/cockroach/pkg/util/log/log_flush.go:42 +0x31
        goroutine 34 [syscall, 5 minutes]:
        os/signal.signal_recv()
        	GOROOT/src/runtime/sigqueue.go:152 +0x2f
        os/signal.loop()
        	GOROOT/src/os/signal/signal_unix.go:23 +0x19
        created by os/signal.Notify.func1.1
        	GOROOT/src/os/signal/signal.go:151 +0x2a
        goroutine 11 [chan receive]:
        github.com/cockroachdb/cockroach/pkg/util/goschedstats.init.0.func1()
        	github.com/cockroachdb/cockroach/pkg/util/goschedstats/runnable.go:165 +0x125
        created by github.com/cockroachdb/cockroach/pkg/util/goschedstats.init.0
        	github.com/cockroachdb/cockroach/pkg/util/goschedstats/runnable.go:157 +0x25
        goroutine 52 [select]:
        go.opencensus.io/stats/view.(*worker).start(0xc000e96300)
        	go.opencensus.io/stats/view/external/io_opencensus_go/stats/view/worker.go:276 +0xad
        created by go.opencensus.io/stats/view.init.0
        	go.opencensus.io/stats/view/external/io_opencensus_go/stats/view/worker.go:34 +0x8d
        goroutine 647956 [select]:
        github.com/cockroachdb/cockroach/pkg/util/log.(*fileSink).gcDaemon(0xc010e7aea0, {0x7227c78, 0xc004902340})
        	github.com/cockroachdb/cockroach/pkg/util/log/file_log_gc.go:25 +0x7f
        created by github.com/cockroachdb/cockroach/pkg/util/log.ApplyConfig
        	github.com/cockroachdb/cockroach/pkg/util/log/flags.go:306 +0x112a
        goroutine 647957 [select]:
        github.com/cockroachdb/cockroach/pkg/util/log.(*fileSink).gcDaemon(0xc010e7af70, {0x7227c78, 0xc004902340})
        	github.com/cockroachdb/cockroach/pkg/util/log/file_log_gc.go:25 +0x7f
        created by github.com/cockroachdb/cockroach/pkg/util/log.ApplyConfig
        	github.com/cockroachdb/cockroach/pkg/util/log/flags.go:306 +0x112a
        goroutine 647954 [select]:
        github.com/cockroachdb/cockroach/pkg/util/log.(*fileSink).gcDaemon(0xc010e7ac30, {0x7227c78, 0xc004902340})
        	github.com/cockroachdb/cockroach/pkg/util/log/file_log_gc.go:25 +0x7f
        created by github.com/cockroachdb/cockroach/pkg/util/log.ApplyConfig
        	github.com/cockroachdb/cockroach/pkg/util/log/flags.go:306 +0x112a
        goroutine 647955 [select]:
        github.com/cockroachdb/cockroach/pkg/util/log.(*fileSink).gcDaemon(0xc010e7add0, {0x7227c78, 0xc004902340})
        	github.com/cockroachdb/cockroach/pkg/util/log/file_log_gc.go:25 +0x7f
        created by github.com/cockroachdb/cockroach/pkg/util/log.ApplyConfig
        	github.com/cockroachdb/cockroach/pkg/util/log/flags.go:306 +0x112a
    panic.go:522: -- test log scope end --
test logs left over in: /artifacts/tmp/_tmp/33e1d369c27b9c01b2b6009c561815a3/logTestReplicaRemovalClosesProposalQuota1378195204
--- FAIL: TestReplicaRemovalClosesProposalQuota (46.01s)
```
<p>Parameters: <code>TAGS=bazel,gss</code>
</p>
<details><summary>Help</summary>
<p>

See also: [How To Investigate a Go Test Failure \(internal\)](https://cockroachlabs.atlassian.net/l/c/HgfXfJgM)
</p>
</details>
/cc @cockroachdb/replication
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*TestReplicaRemovalClosesProposalQuota.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)
</sub>

Jira issue: CRDB-24415

### PR DESCRIPTION
**Pull request by tbg**
As this test explained in its comment, the circumstances it was
seeking to test were very rarely met and even if the behavior
were missing, this wouldn't cause any problems.

The test has been skipped (accidentally) for a long time, was flaky even
then (leaking trace spans, see below), and it's not easy to
enact the situation the test wishes to construct in an idiomatic way.

It's pretty clear that the lines the test wants are present:

https://github.com/cockroachdb/cockroach/blob/736a67e0d36cc545bf74d65db069ee895ff9bea0/pkg/kv/kvserver/replica_destroy.go#L174-L176

It's better to remove the test at this point.

Closes #96932.

Also, fix a buglet that the test "accidentally" uncovered:

Previously, if `evalAndPropose` returned with an error while trying to
propose a pipelined write, it would leak the trace span.

Make sure this doesn't happen. The test that exercised this got deleted
in the previous commit, but this is still a bug that could cause a
larger leak if a condition were ever added to `evalAndPropose` which
could cause a large amount of errors (perhaps spread out over a longer
time period) in production clusters.

Unfortunately, writing a test for this is likely to be a net negative;
if the reviewer feels strongly I can add a testing knob to inject an
error in the right place in this method and exercise it that way.

Touches https://github.com/cockroachdb/cockroach/issues/96932.

Epic: none
Release note: None

### CODE REVIEW

File: pkg/kv/kvserver/replica_raft.go [hunk 1]
```diff
@@ -200,6 +202,12 @@ func (r *Replica) evalAndPropose(
 		// Fork the proposal's context span so that the proposal's context
 		// can outlive the original proposer's context.
 		proposal.ctx, proposal.sp = tracing.ForkSpan(ctx, "async consensus")
+		if proposal.sp != nil {
+			// We can't leak this span if we fail to hand the proposal to the
+			// replication layer, so finish it later in this method if we are to
+			// return with an error. (On success, we'll reset this to a noop).
+			maybeFinishSpan = proposal.sp.Finish
```
Comment (pavelkalinnikov) [inline pkg/kv/kvserver/replica_raft.go:209]: Would this do what you want it to do?

https://go.dev/play/p/c_1PTKWUmBx

Comment (tbg) [reply pkg/kv/kvserver/replica_raft.go:209]: 😶‍🌫️ thanks for catching that, fixed. Annoying that making this testable is a large refactor away.

**Review by pav-kv — APPROVED** [review]

**Comment by tbg** [comment]
bors r=pavelkalinnikov
