### PR TITLE
sql: only re-use resolved routine type when flag is set

### LINKED ISSUE #142615: sql: v24.1.14: nil pointer regression due to a type-checking logic change
This issue was auto filed by Sentry. It represents a crash or reported error on a live cluster with telemetry enabled.

Sentry Link: [https://cockroach-labs.sentry.io/issues/6382290044/?referrer=webhooks_plugin](https://cockroach-labs.sentry.io/issues/6382290044/?referrer=webhooks_plugin)

Panic Message:

```
catch.go:24: runtime error: invalid memory address or nil pointer dereference
(1)
Wraps: (2) assertion failure
Wraps: (3) attached stack trace
  -- stack trace:
  | github.com/cockroachdb/cockroach/pkg/util/errorutil.ShouldCatch
  | 	github.com/cockroachdb/cockroach/pkg/util/errorutil/catch.go:24
  | github.com/cockroachdb/cockroach/pkg/sql.setupGenerator.func3.1.1
  | 	github.com/cockroachdb/cockroach/pkg/sql/virtual_table.go:130
  | runtime.gopanic
  | 	GOROOT/src/runtime/panic.go:770
  | runtime.panicmem
  | 	GOROOT/src/runtime/panic.go:261
  | runtime.sigpanic
  | 	GOROOT/src/runtime/signal_unix.go:881
  | github.com/cockroachdb/cockroach/pkg/sql/sem/builtins.init.func503
  | 	github.com/cockroachdb/cockroach/pkg/sql/sem/builtins/builtins.go:2189
  | github.com/cockroachdb/cockroach/pkg/sql/sem/eval.(*evaluator).EvalFuncExpr
  | 	github.com/cockroachdb/cockroach/pkg/sql/sem/eval/expr.go:484
  | github.com/cockroachdb/cockroach/pkg/sql/sem/tree.(*FuncExpr).Eval
  | 	github.com/cockroachdb/cockroach/bazel-out/k8-opt/bin/pkg/sql/sem/tree/eval_expr_generated.go:277
  | github.com/cockroachdb/cockroach/pkg/sql/sem/eval.(*evaluator).evalFuncArgs
  | 	github.com/cockroachdb/cockroach/pkg/sql/sem/eval/expr.go:501
  | github.com/cockroachdb/cockroach/pkg/sql/sem/eval.(*evaluator).EvalFuncExpr
  | 	github.com/cockroachdb/cockroach/pkg/sql/sem/eval/expr.go:466
  | github.com/cockroachdb/cockroach/pkg/sql/sem/tree.(*FuncExpr).Eval
  | 	github.com/cockroachdb/cockroach/bazel-out/k8-opt/bin/pkg/sql/sem/tree/eval_expr_generated.go:277
  | github.com/cockroachdb/cockroach/pkg/sql/sem/eval.Expr
  | 	github.com/cockroachdb/cockroach/pkg/sql/sem/eval/expr.go:21
  | github.com/cockroachdb/cockroach/pkg/sql/catalog/schemaexpr.deserializeExprForFormatting
  | 	github.com/cockroachdb/cockroach/pkg/sql/catalog/schemaexpr/expr.go:318
  | github.com/cockroachdb/cockroach/pkg/sql/catalog/schemaexpr.formatExprForDisplayImpl
  | 	github.com/cockroachdb/cockroach/pkg/sql/catalog/schemaexpr/expr.go:256
  | github.com/cockroachdb/cockroach/pkg/sql/catalog/schemaexpr.FormatExprForDisplay
  | 	github.com/cockroachdb/cockroach/pkg/sql/catalog/schemaexpr/expr.go:213
  | github.com/cockroachdb/cockroach/pkg/sql.init.func770
  | 	github.com/cockroachdb/cockroach/pkg/sql/pg_catalog.go:377
  | github.com/cockroachdb/cockroach/pkg/sql.makeAllRelationsVirtualTableWithDescriptorIDIndex.func1.1
  | 	github.com/cockroachdb/cockroach/pkg/sql/pg_catalog.go:1187
  | github.com/cockroachdb/cockroach/pkg/sql.forEachTableDescWithTableLookupInternalFromDescriptors
  | 	github.com/cockroachdb/cockroach/pkg/sql/information_schema.go:2846
  | github.com/cockroachdb/cockroach/pkg/sql.forEachTableDescWithTableLookupInternal
  | 	github.com/cockroachdb/cockroach/pkg/sql/information_schema.go:2719
  | github.com/cockroachdb/cockroach/pkg/sql.forEachTableDescWithTableLookup
  | 	github.com/cockroachdb/cockroach/pkg/sql/information_schema.go:2690
  | github.com/cockroachdb/cockroach/pkg/sql.makeAllRelationsVirtualTableWithDescriptorIDIndex.func1
  | 	github.com/cockroachdb/cockroach/pkg/sql/pg_catalog.go:1181
  | github.com/cockroachdb/cockroach/pkg/sql.(*virtualDefEntry).getPlanInfo.func1.1
  | 	github.com/cockroachdb/cockroach/pkg/sql/virtual_schema.go:656
  | github.com/cockroachdb/cockroach/pkg/sql.setupGenerator.func3.1
  | 	github.com/cockroachdb/cockroach/pkg/sql/virtual_table.go:138
  | github.com/cockroachdb/cockroach/pkg/sql.setupGenerator.func3
  | 	github.com/cockroachdb/cockroach/pkg/sql/virtual_table.go:139
  | github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunAsyncTaskEx.func2
  | 	github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:480
  | runtime.goexit
  | 	src/runtime/asm_amd64.s:1695
Wraps: (4) runtime error: invalid memory address or nil pointer dereference
  | -- cause hidden behind barrier
  | runtime error: invalid memory address or nil pointer dereference
  | (1) runtime error: invalid memory address or nil pointer dereference
  | Error types: (1) runtime.errorString
Error types: (1) *colexecerror.notInternalError (2) *assert.withAssertionFailure (3) *withstack.withStack (4) *barriers.barrierErr
-- report composition:
*barriers.barrierErr: masked error: runtime error: invalid memory address or nil pointer dereference
catch.go:24: *withstack.withStack (top exception)
*assert.withAssertionFailure
*colexecerror.notInternalError
```

<details>
<summary>Stacktrace (expand for inline code snippets):</summary>

[src/runtime/asm_amd64.s#L1694-L1696](src/runtime/asm_amd64.s#L1694-L1696)
[https://github.com/cockroachdb/cockroach/blob/c8459c085e2258f589949e970a527a0342871276/pkg/util/stop/stopper.go#L479-L481](https://github.com/cockroachdb/cockroach/blob/c8459c085e2258f589949e970a527a0342871276/pkg/util/stop/stopper.go#L479-L481)
[https://github.com/cockroachdb/cockroach/blob/c8459c085e2258f589949e970a527a0342871276/pkg/sql/virtual_table.go#L138-L140](https://github.com/cockroachdb/cockroach/blob/c8459c085e2258f589949e970a527a0342871276/pkg/sql/virtual_table.go#L138-L140)
[https://github.com/cockroachdb/cockroach/blob/c8459c085e2258f589949e970a527a0342871276/pkg/sql/virtual_table.go#L137-L139](https://github.com/cockroachdb/cockroach/blob/c8459c085e2258f589949e970a527a0342871276/pkg/sql/virtual_table.go#L137-L139)
[https://github.com/cockroachdb/cockroach/blob/c8459c085e2258f589949e970a527a0342871276/pkg/sql/virtual_schema.go#L655-L657](https://github.com/cockroachdb/cockroach/blob/c8459c085e2258f589949e970a527a0342871276/pkg/sql/virtual_schema.go#L655-L657)
[https://github.com/cockroachdb/cockroach/blob/c8459c085e2258f589949e970a527a0342871276/pkg/sql/pg_catalog.go#L1180-L1182](https://github.com/cockroachdb/cockroach/blob/c8459c085e2258f589949e970a527a0342871276/pkg/sql/pg_catalog.go#L1180-L1182)
[https://github.com/cockroachdb/cockroach/blob/c8459c085e2258f589949e970a527a0342871276/pkg/sql/information_schema.go#L2689-L2691](https://github.com/cockroachdb/cockroach/blob/c8459c085e2258f589949e970a527a0342871276/pkg/sql/information_schema.go#L2689-L2691)
[https://github.com/cockroachdb/cockroach/blob/c8459c085e2258f589949e970a527a0342871276/pkg/sql/information_schema.go#L2718-L2720](https://github.com/cockroachdb/cockroach/blob/c8459c085e2258f589949e970a527a0342871276/pkg/sql/information_schema.go#L2718-L2720)
[https://github.com/cockroachdb/cockroach/blob/c8459c085e2258f589949e970a527a0342871276/pkg/sql/information_schema.go#L2845-L2847](https://github.com/cockroachdb/cockroach/blob/c8459c085e2258f589949e970a527a0342871276/pkg/sql/information_schema.go#L2845-L2847)
[https://github.com/cockroachdb/cockroach/blob/c8459c085e2258f589949e970a527a0342871276/pkg/sql/pg_catalog.go#L1186-L1188](https://github.com/cockroachdb/cockroach/blob/c8459c085e2258f589949e970a527a0342871276/pkg/sql/pg_catalog.go#L1186-L1188)
[https://github.com/cockroachdb/cockroach/blob/c8459c085e2258f589949e970a527a0342871276/pkg/sql/pg_catalog.go#L376-L378](https://github.com/cockroachdb/cockroach/blob/c8459c085e2258f589949e970a527a0342871276/pkg/sql/pg_catalog.go#L376-L378)
[https://github.com/cockroachdb/cockroach/blob/c8459c085e2258f589949e970a527a0342871276/pkg/sql/catalog/schemaexpr/expr.go#L212-L214](https://github.com/cockroachdb/cockroach/blob/c8459c085e2258f589949e970a527a0342871276/pkg/sql/catalog/schemaexpr/expr.go#L212-L214)
[https://github.com/cockroachdb/cockroach/blob/c8459c085e2258f589949e970a527a0342871276/pkg/sql/catalog/schemaexpr/expr.go#L255-L257](https://github.com/cockroachdb/cockroach/blob/c8459c085e2258f589949e970a527a0342871276/pkg/sql/catalog/schemaexpr/expr.go#L255-L257)
[https://github.com/cockroachdb/cockroach/blob/c8459c085e2258f589949e970a527a0342871276/pkg/sql/catalog/schemaexpr/expr.go#L317-L319](https://github.com/cockroachdb/cockroach/blob/c8459c085e2258f589949e970a527a0342871276/pkg/sql/catalog/schemaexpr/expr.go#L317-L319)
[https://github.com/cockroachdb/cockroach/blob/c8459c085e2258f589949e970a527a0342871276/pkg/sql/sem/eval/expr.go#L20-L22](https://github.com/cockroachdb/cockroach/blob/c8459c085e2258f589949e970a527a0342871276/pkg/sql/sem/eval/expr.go#L20-L22)
[https://github.com/cockroachdb/cockroach/blob/c8459c085e2258f589949e970a527a0342871276/bazel-out/k8-opt/bin/pkg/sql/sem/tree/eval_expr_generated.go#L276-L278](https://github.com/cockroachdb/cockroach/blob/c8459c085e2258f589949e970a527a0342871276/bazel-out/k8-opt/bin/pkg/sql/sem/tree/eval_expr_generated.go#L276-L278)
[https://github.com/cockroachdb/cockroach/blob/c8459c085e2258f589949e970a527a0342871276/pkg/sql/sem/eval/expr.go#L465-L467](https://github.com/cockroachdb/cockroach/blob/c8459c085e2258f589949e970a527a0342871276/pkg/sql/sem/eval/expr.go#L465-L467)
[https://github.com/cockroachdb/cockroach/blob/c8459c085e2258f589949e970a527a0342871276/pkg/sql/sem/eval/expr.go#L500-L502](https://github.com/cockroachdb/cockroach/blob/c8459c085e2258f589949e970a527a0342871276/pkg/sql/sem/eval/expr.go#L500-L502)
[https://github.com/cockroachdb/cockroach/blob/c8459c085e2258f589949e970a527a0342871276/bazel-out/k8-opt/bin/pkg/sql/sem/tree/eval_expr_generated.go#L276-L278](https://github.com/cockroachdb/cockroach/blob/c8459c085e2258f589949e970a527a0342871276/bazel-out/k8-opt/bin/pkg/sql/sem/tree/eval_expr_generated.go#L276-L278)
[https://github.com/cockroachdb/cockroach/blob/c8459c085e2258f589949e970a527a0342871276/pkg/sql/sem/eval/expr.go#L483-L485](https://github.com/cockroachdb/cockroach/blob/c8459c085e2258f589949e970a527a0342871276/pkg/sql/sem/eval/expr.go#L483-L485)
[https://github.com/cockroachdb/cockroach/blob/c8459c085e2258f589949e970a527a0342871276/pkg/sql/sem/builtins/builtins.go#L2188-L2190](https://github.com/cockroachdb/cockroach/blob/c8459c085e2258f589949e970a527a0342871276/pkg/sql/sem/builtins/builtins.go#L2188-L2190)
[GOROOT/src/runtime/signal_unix.go#L880-L882](GOROOT/src/runtime/signal_unix.go#L880-L882)
[GOROOT/src/runtime/panic.go#L260-L262](GOROOT/src/runtime/panic.go#L260-L262)
[GOROOT/src/runtime/panic.go#L769-L771](GOROOT/src/runtime/panic.go#L769-L771)
[https://github.com/cockroachdb/cockroach/blob/c8459c085e2258f589949e970a527a0342871276/pkg/sql/virtual_table.go#L129-L131](https://github.com/cockroachdb/cockroach/blob/c8459c085e2258f589949e970a527a0342871276/pkg/sql/virtual_table.go#L129-L131)
[https://github.com/cockroachdb/cockroach/blob/c8459c085e2258f589949e970a527a0342871276/pkg/util/errorutil/catch.go#L23-L25](https://github.com/cockroachdb/cockroach/blob/c8459c085e2258f589949e970a527a0342871276/pkg/util/errorutil/catch.go#L23-L25)
</details>

```
src/runtime/asm_amd64.s in runtime.goexit at line 1695
pkg/util/stop/stopper.go in pkg/util/stop.(*Stopper).RunAsyncTaskEx.func2 at line 480
pkg/sql/virtual_table.go in pkg/sql.setupGenerator.func3 at line 139
pkg/sql/virtual_table.go in pkg/sql.setupGenerator.func3.1 at line 138
pkg/sql/virtual_schema.go in pkg/sql.(*virtualDefEntry).getPlanInfo.func1.1 at line 656
pkg/sql/pg_catalog.go in pkg/sql.makeAllRelationsVirtualTableWithDescriptorIDIndex.func1 at line 1181
pkg/sql/information_schema.go in pkg/sql.forEachTableDescWithTableLookup at line 2690
pkg/sql/information_schema.go in pkg/sql.forEachTableDescWithTableLookupInternal at line 2719
pkg/sql/information_schema.go in pkg/sql.forEachTableDescWithTableLookupInternalFromDescriptors at line 2846
pkg/sql/pg_catalog.go in pkg/sql.makeAllRelationsVirtualTableWithDescriptorIDIndex.func1.1 at line 1187
pkg/sql/pg_catalog.go in pkg/sql.init.func770 at line 377
pkg/sql/catalog/schemaexpr/expr.go in pkg/sql/catalog/schemaexpr.FormatExprForDisplay at line 213
pkg/sql/catalog/schemaexpr/expr.go in pkg/sql/catalog/schemaexpr.formatExprForDisplayImpl at line 256
pkg/sql/catalog/schemaexpr/expr.go in pkg/sql/catalog/schemaexpr.deserializeExprForFormatting at line 318
pkg/sql/sem/eval/expr.go in pkg/sql/sem/eval.Expr at line 21
bazel-out/k8-opt/bin/pkg/sql/sem/tree/eval_expr_generated.go in pkg/sql/sem/tree.(*FuncExpr).Eval at line 277
pkg/sql/sem/eval/expr.go in pkg/sql/sem/eval.(*evaluator).EvalFuncExpr at line 466
pkg/sql/sem/eval/expr.go in pkg/sql/sem/eval.(*evaluator).evalFuncArgs at line 501
bazel-out/k8-opt/bin/pkg/sql/sem/tree/eval_expr_generated.go in pkg/sql/sem/tree.(*FuncExpr).Eval at line 277
pkg/sql/sem/eval/expr.go in pkg/sql/sem/eval.(*evaluator).EvalFuncExpr at line 484
pkg/sql/sem/builtins/builtins.go in pkg/sql/sem/builtins.init.func503 at line 2189
GOROOT/src/runtime/signal_unix.go in runtime.sigpanic at line 881
GOROOT/src/runtime/panic.go in runtime.panicmem at line 261
GOROOT/src/runtime/panic.go in runtime.gopanic at line 770
pkg/sql/virtual_table.go in pkg/sql.setupGenerator.func3.1.1 at line 130
pkg/util/errorutil/catch.go in pkg/util/errorutil.ShouldCatch at line 24
```

### Tags

| Tag | Value |
| --- | --- |
| Command | server |
| Environment | v24.1.14 |
| Go Version | go1.22.5 X:nocoverageredesign |
| Platform | linux amd64 |
| Distribution | CCL |
| Cockroach Release | v24.1.14 |
| Cockroach SHA | c8459c085e2258f589949e970a527a0342871276 |
| # of CPUs | 16 |
| # of Goroutines | 3952 |

Jira issue: CRDB-48445

### PR DESCRIPTION
**Pull request by DrewKimball**
This commit adds a `RoutineUseResolvedType` flag to the `SemaContext` properties to indicate that type-checking for a routine that has already been resolved to a concrete type should short-circuit. This is used to determine the column type for a `Values` operator which depends on a RECORD-returning routine, which only determines its type after the body is built. This will prevent regressions in other code paths that do not desire this short-circuiting behavior.

Fixes #142615

Release note (bug fix): Fixed a bug in `v24.1.14`, `v24.3.7`, `v24.3.8`, and `v25.1` which could cause a nil-pointer error when a column's default expression contained a volatile expression (like `nextval`) as a UDF argument.

### CODE REVIEW

File: pkg/sql/sem/tree/type_check.go [hunk 1]
```diff
@@ -96,6 +96,12 @@ type SemaProperties struct {
 	// IgnoreUnpreferredOverloads is set to true when "unpreferred" overloads
 	// should not be used during type-checking and overload resolution.
 	IgnoreUnpreferredOverloads bool
+
+	// RoutineUseResolvedType is set to true when type-checking for a routine
+	// should reuse the already resolved type, if any. This is used to handle
+	// "re-type-checking" that occurs for a RECORD-returning routine, for which
+	// the return type is not known until the routine body is built.
+	RoutineUseResolvedType bool
```
Comment (mgartner) [inline pkg/sql/sem/tree/type_check.go:104]: Does it make sense to use ScalarAncestors here? The special case is a bit confusing to me - it only applies to routines within a VALUES expression?

**Review by mgartner — APPROVED** [review]
LGTM

**Comment by DrewKimball** [comment]
TFTR!

bors r=mgartner
