### PR TITLE
opt: revert planning regression for queries with many indexes

### LINKED ISSUE #111118: opt/bench: regression in BenchmarkPhases/many-columns-and-indexes
Comparing f13c021b and 2a23692a61e72a:
```
name                                                     old time/op    new time/op    delta
Phases/many-columns-and-indexes-a/Simple/Explore-24         447µs ± 1%     488µs ± 0%    +9.20%  (p=0.000 n=9+8)
Phases/many-columns-and-indexes-a/Simple/ExecBuild-24       453µs ± 0%     497µs ± 0%    +9.63%  (p=0.000 n=10+10)
Phases/many-columns-and-indexes-a/Prepared/Explore-24       388µs ± 0%     432µs ± 0%   +11.36%  (p=0.000 n=9+10)
Phases/many-columns-and-indexes-a/Prepared/ExecBuild-24     394µs ± 0%     439µs ± 0%   +11.28%  (p=0.000 n=10+10)
Phases/many-columns-and-indexes-b/Simple/Explore-24         532µs ± 0%     582µs ± 0%    +9.52%  (p=0.000 n=10+10)
Phases/many-columns-and-indexes-b/Simple/ExecBuild-24       543µs ± 1%     594µs ± 1%    +9.35%  (p=0.000 n=10+10)
Phases/many-columns-and-indexes-b/Prepared/Explore-24       441µs ± 1%     492µs ± 0%   +11.44%  (p=0.000 n=10+9)
Phases/many-columns-and-indexes-b/Prepared/ExecBuild-24     449µs ± 0%     501µs ± 1%   +11.70%  (p=0.000 n=10+10)
Phases/many-columns-and-indexes-c/Simple/Explore-24         346ms ± 1%     347ms ± 1%      ~     (p=0.203 n=10+8)
Phases/many-columns-and-indexes-c/Simple/ExecBuild-24       348ms ± 1%     345ms ± 2%      ~     (p=0.123 n=10+10)
Phases/many-columns-and-indexes-c/Prepared/Explore-24       333ms ± 2%     346ms ± 1%    +3.84%  (p=0.000 n=10+10)
Phases/many-columns-and-indexes-c/Prepared/ExecBuild-24     336ms ± 0%     346ms ± 1%    +3.05%  (p=0.000 n=7+10)

name                                                     old alloc/op   new alloc/op   delta
Phases/many-columns-and-indexes-a/Simple/Explore-24        39.4kB ± 0%    53.0kB ± 0%   +34.48%  (p=0.000 n=10+10)
Phases/many-columns-and-indexes-a/Simple/ExecBuild-24      40.2kB ± 0%    53.8kB ± 0%   +33.81%  (p=0.000 n=10+10)
Phases/many-columns-and-indexes-a/Prepared/Explore-24      5.36kB ± 0%   18.81kB ± 0%  +250.92%  (p=0.000 n=10+10)
Phases/many-columns-and-indexes-a/Prepared/ExecBuild-24    6.16kB ± 0%   19.61kB ± 0%  +218.43%  (p=0.000 n=10+10)
Phases/many-columns-and-indexes-b/Simple/Explore-24        47.7kB ± 0%    61.3kB ± 0%   +28.47%  (p=0.000 n=10+10)
Phases/many-columns-and-indexes-b/Simple/ExecBuild-24      48.8kB ± 0%    62.4kB ± 0%   +27.79%  (p=0.000 n=10+10)
Phases/many-columns-and-indexes-b/Prepared/Explore-24      7.88kB ± 0%   21.33kB ± 0%  +170.77%  (p=0.000 n=8+10)
Phases/many-columns-and-indexes-b/Prepared/ExecBuild-24    9.01kB ± 0%   22.47kB ± 0%  +149.31%  (p=0.000 n=10+10)
Phases/many-columns-and-indexes-c/Simple/Explore-24         110MB ± 0%     111MB ± 0%    +0.50%  (p=0.000 n=10+9)
Phases/many-columns-and-indexes-c/Simple/ExecBuild-24       110MB ± 0%     111MB ± 0%    +0.49%  (p=0.000 n=10+10)
Phases/many-columns-and-indexes-c/Prepared/Explore-24       109MB ± 0%     109MB ± 0%    +0.49%  (p=0.000 n=9+10)
Phases/many-columns-and-indexes-c/Prepared/ExecBuild-24     109MB ± 0%     109MB ± 0%    +0.50%  (p=0.000 n=10+10)

name                                                     old allocs/op  new allocs/op  delta
Phases/many-columns-and-indexes-a/Simple/Explore-24          76.0 ± 0%     111.0 ± 0%   +46.05%  (p=0.000 n=10+10)
Phases/many-columns-and-indexes-a/Simple/ExecBuild-24        87.0 ± 0%     122.0 ± 0%   +40.23%  (p=0.000 n=10+10)
Phases/many-columns-and-indexes-a/Prepared/Explore-24        28.0 ± 0%      61.0 ± 0%  +117.86%  (p=0.000 n=10+10)
Phases/many-columns-and-indexes-a/Prepared/ExecBuild-24      39.0 ± 0%      72.0 ± 0%   +84.62%  (p=0.000 n=10+10)
Phases/many-columns-and-indexes-b/Simple/Explore-24           131 ± 0%       166 ± 0%   +27.02%  (p=0.000 n=10+10)
Phases/many-columns-and-indexes-b/Simple/ExecBuild-24         146 ± 0%       181 ± 0%   +23.97%  (p=0.000 n=10+8)
Phases/many-columns-and-indexes-b/Prepared/Explore-24        46.0 ± 0%      79.0 ± 0%   +71.74%  (p=0.000 n=10+10)
Phases/many-columns-and-indexes-b/Prepared/ExecBuild-24      61.0 ± 0%      94.0 ± 0%   +54.10%  (p=0.000 n=10+10)
Phases/many-columns-and-indexes-c/Simple/Explore-24          750k ± 0%      763k ± 0%    +1.75%  (p=0.000 n=10+10)
Phases/many-columns-and-indexes-c/Simple/ExecBuild-24        750k ± 0%      763k ± 0%    +1.75%  (p=0.000 n=8+10)
Phases/many-columns-and-indexes-c/Prepared/Explore-24        744k ± 0%      757k ± 0%    +1.76%  (p=0.000 n=10+10)
Phases/many-columns-and-indexes-c/Prepared/ExecBuild-24      744k ± 0%      758k ± 0%    +1.76%  (p=0.000 n=10+10)
```
(comparison of the whole benchmark is [here](https://gist.github.com/yuzefovich/3b930facc2d1148f13d40e0ab2663c99)).

**Bisected the regression to 452a2de1fb99885b74cd590b72c912e76f25f360**
<details>
```

name                                                     old time/op    new time/op    delta
Phases/many-columns-and-indexes-a/Simple/Explore-24         436µs ± 0%     483µs ± 0%   +10.92%  (p=0.000 n=10+9)
Phases/many-columns-and-indexes-a/Simple/ExecBuild-24       445µs ± 2%     493µs ± 1%   +10.58%  (p=0.000 n=10+10)
Phases/many-columns-and-indexes-a/Prepared/Explore-24       380µs ± 1%     425µs ± 0%   +11.69%  (p=0.000 n=10+8)
Phases/many-columns-and-indexes-a/Prepared/ExecBuild-24     384µs ± 0%     432µs ± 0%   +12.31%  (p=0.000 n=10+10)
Phases/many-columns-and-indexes-b/Simple/Explore-24         522µs ± 1%     576µs ± 0%   +10.43%  (p=0.000 n=10+10)
Phases/many-columns-and-indexes-b/Simple/ExecBuild-24       533µs ± 0%     588µs ± 1%   +10.39%  (p=0.000 n=9+10)
Phases/many-columns-and-indexes-b/Prepared/Explore-24       429µs ± 0%     482µs ± 0%   +12.20%  (p=0.000 n=10+10)
Phases/many-columns-and-indexes-b/Prepared/ExecBuild-24     438µs ± 0%     490µs ± 1%   +11.90%  (p=0.000 n=10+10)
Phases/many-columns-and-indexes-c/Simple/Explore-24         348ms ± 1%     347ms ± 1%      ~     (p=0.780 n=10+9)
Phases/many-columns-and-indexes-c/Simple/ExecBuild-24       349ms ± 1%     350ms ± 2%      ~     (p=0.739 n=10+10)
Phases/many-columns-and-indexes-c/Prepared/Explore-24       328ms ± 2%     330ms ± 2%      ~     (p=0.684 n=10+10)
Phases/many-columns-and-indexes-c/Prepared/ExecBuild-24     330ms ± 2%     326ms ± 0%      ~     (p=0.122 n=10+8)

name                                                     old alloc/op   new alloc/op   delta
Phases/many-columns-and-indexes-a/Simple/Explore-24        39.4kB ± 0%    52.8kB ± 0%   +34.02%  (p=0.000 n=10+10)
Phases/many-columns-and-indexes-a/Simple/ExecBuild-24      40.2kB ± 0%    53.6kB ± 0%   +33.35%  (p=0.000 n=10+10)
Phases/many-columns-and-indexes-a/Prepared/Explore-24      5.36kB ± 0%   18.75kB ± 0%  +249.84%  (p=0.000 n=10+10)
Phases/many-columns-and-indexes-a/Prepared/ExecBuild-24    6.16kB ± 0%   19.55kB ± 0%  +217.52%  (p=0.000 n=10+10)
Phases/many-columns-and-indexes-b/Simple/Explore-24        47.7kB ± 0%    61.1kB ± 0%   +28.09%  (p=0.000 n=10+9)
Phases/many-columns-and-indexes-b/Simple/ExecBuild-24      48.8kB ± 0%    62.2kB ± 0%   +27.44%  (p=0.000 n=9+10)
Phases/many-columns-and-indexes-b/Prepared/Explore-24      7.88kB ± 0%   21.27kB ± 0%  +169.94%  (p=0.000 n=10+9)
Phases/many-columns-and-indexes-b/Prepared/ExecBuild-24    9.01kB ± 0%   22.41kB ± 0%  +148.58%  (p=0.000 n=10+10)
Phases/many-columns-and-indexes-c/Simple/Explore-24         107MB ± 0%     107MB ± 0%    +0.14%  (p=0.000 n=10+9)
Phases/many-columns-and-indexes-c/Simple/ExecBuild-24       107MB ± 0%     108MB ± 0%    +0.14%  (p=0.000 n=9+10)
Phases/many-columns-and-indexes-c/Prepared/Explore-24       106MB ± 0%     106MB ± 0%    +0.14%  (p=0.000 n=10+10)
Phases/many-columns-and-indexes-c/Prepared/ExecBuild-24     106MB ± 0%     106MB ± 0%    +0.14%  (p=0.000 n=10+10)

name                                                     old allocs/op  new allocs/op  delta
Phases/many-columns-and-indexes-a/Simple/Explore-24          76.0 ± 0%     109.0 ± 0%   +43.42%  (p=0.000 n=10+10)
Phases/many-columns-and-indexes-a/Simple/ExecBuild-24        87.0 ± 0%     120.0 ± 0%   +37.93%  (p=0.000 n=10+10)
Phases/many-columns-and-indexes-a/Prepared/Explore-24        28.0 ± 0%      61.0 ± 0%  +117.86%  (p=0.000 n=10+10)
Phases/many-columns-and-indexes-a/Prepared/ExecBuild-24      39.0 ± 0%      72.0 ± 0%   +84.62%  (p=0.000 n=10+10)
Phases/many-columns-and-indexes-b/Simple/Explore-24           131 ± 0%       164 ± 0%   +25.19%  (p=0.000 n=10+10)
Phases/many-columns-and-indexes-b/Simple/ExecBuild-24         146 ± 0%       179 ± 0%   +22.60%  (p=0.000 n=10+8)
Phases/many-columns-and-indexes-b/Prepared/Explore-24        46.0 ± 0%      79.0 ± 0%   +71.74%  (p=0.000 n=10+10)
Phases/many-columns-and-indexes-b/Prepared/ExecBuild-24      61.0 ± 0%      94.0 ± 0%   +54.10%  (p=0.000 n=10+10)
Phases/many-columns-and-indexes-c/Simple/Explore-24          735k ± 0%      735k ± 0%    +0.05%  (p=0.000 n=10+9)
Phases/many-columns-and-indexes-c/Simple/ExecBuild-24        735k ± 0%      735k ± 0%    +0.05%  (p=0.000 n=9+10)
Phases/many-columns-and-indexes-c/Prepared/Explore-24        729k ± 0%      729k ± 0%    +0.05%  (p=0.000 n=10+8)
Phases/many-columns-and-indexes-c/Prepared/ExecBuild-24      729k ± 0%      729k ± 0%    +0.05%  (p=0.000 n=10+10)
```

</details>

Jira issue: CRDB-31774

### PR DESCRIPTION
**Pull request by DrewKimball**
Index visibility is tracked in the optimizer using a map from index ordinal to visibility. This caused a regression in some planning benchmarks due to allocations for the map. This patch replaces the map with a pair of int sets, which track (a) whether the visibility of an index has been cached and (b) whether the index is not visible. This avoids most allocations, since index ordinals start at 0 for the primary index and increment from there.

Fixes #111118

Release note: None

### CODE REVIEW

**Comment by DrewKimball** [comment]
```
name                                                   old time/op    new time/op    delta
Phases/many-columns-and-indexes-a/Prepared/Explore-10     256µs ± 0%     237µs ± 0%   -7.20%  (p=0.000 n=9+8)

name                                                   old alloc/op   new alloc/op   delta
Phases/many-columns-and-indexes-a/Prepared/Explore-10    18.1kB ± 0%     5.4kB ± 0%  -69.95%  (p=0.000 n=10+10)

name                                                   old allocs/op  new allocs/op  delta
Phases/many-columns-and-indexes-a/Prepared/Explore-10      47.0 ± 0%      28.0 ± 0%  -40.43%  (p=0.000 n=10+10)
```

**Review by msirek — DISMISSED** [review]
Nice fix!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/111698#-:-NfsFyleCTRWlJS6WOQ8:b-k6moza)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @DrewKimball)

___
*[`pkg/sql/opt/table_meta.go` line 261 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/111698#-NfsG0XUAGRIPTsE8FZW:-NfsG0XUAGRIPTsE8FZX:bz1jbu8) ([raw file](https://github.com/cockroachdb/cockroach/blob/81e0c5a46adbae8202900e4f7929b59d2535ab23/pkg/sql/opt/table_meta.go#L261)):*
> ```Go
> 		tm.cachedIndexVisibility.Add(indexOrd)
> 		tm.notVisibleIndexes.Add(indexOrd)
> 	}
> ```

I believe this should be 
```
	tm.cachedIndexVisibility.Add(indexOrd)
	if isNotVisible {
		tm.notVisibleIndexes.Add(indexOrd)
	}
```

File: pkg/sql/opt/table_meta.go [hunk 1]
```diff
@@ -210,9 +211,13 @@ type TableMeta struct {
...
-	// notVisibleIndexMap stores information about index invisibility which maps
-	// from index ordinal to index invisibility.
-	notVisibleIndexMap map[cat.IndexOrdinal]bool
+	// notVisibleIndexes stores the ordinals of indexes that have been marked as
+	// not visible. This avoids recomputation and ensure a consistent answer
+	// within a query for indexes with fractional visibility.
+	notVisibleIndexes intsets.Fast
+	// cachedIndexVisibility indicates whether the visibility of given index
+	// ordinal has been cached in notVisibleIndexes.
+	cachedIndexVisibility intsets.Fast
```
Comment (mgartner) [inline pkg/sql/opt/table_meta.go:220]: nit: purely stylistic, but this might be a good spot for a nested struct:

```go
  indexVisibility struct {
    notVisible intsets.Fast
    isCached   intsets.Fast
  }
```

File: pkg/sql/opt/table_meta.go [hunk 2]
```diff
@@ -254,7 +255,10 @@ func (tm *TableMeta) IsIndexNotVisible(indexOrd cat.IndexOrdinal, rng *rand.Rand
 			isNotVisible = true
 		}
 	}
-	tm.notVisibleIndexMap[indexOrd] = isNotVisible
+	if isNotVisible {
+		tm.cachedIndexVisibility.Add(indexOrd)
```
Comment (mgartner) [inline pkg/sql/opt/table_meta.go:259]: Don't we want to set `tm.cachedIndexVisibility` even if the index is visible to avoid re-rolling the dice next time `IsIndexNotVisible` is called?

**Review by DrewKimball — COMMENTED** [review]
TFTR

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/111698#-:-Ngz_vwpADfedTgmbXRC:bb73zsl)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @mgartner and @msirek)

___
*[`pkg/sql/opt/table_meta.go` line 220 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/111698#gh-1362815080:-Ngz_Glz30r48cKbwblT:b-h43rks) ([raw file](https://github.com/cockroachdb/cockroach/blob/81e0c5a46adbae8202900e4f7929b59d2535ab23/pkg/sql/opt/table_meta.go#L220)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

nit: purely stylistic, but this might be a good spot for a nested struct:

```go
  indexVisibility struct {
    notVisible intsets.Fast
    isCached   intsets.Fast
  }
```
</blockquote></details>

Sounds good, done.
___
*[`pkg/sql/opt/table_meta.go` line 259 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/111698#gh-1362816019:-NgzZTjL0PkG7qK_aYQi:b5j5q0m) ([raw file](https://github.com/cockroachdb/cockroach/blob/81e0c5a46adbae8202900e4f7929b59d2535ab23/pkg/sql/opt/table_meta.go#L259)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

Don't we want to set `tm.cachedIndexVisibility` even if the index is visible to avoid re-rolling the dice next time `IsIndexNotVisible` is called?
</blockquote></details>

Yes, Done.
___
*[`pkg/sql/opt/table_meta.go` line 261 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/111698#-NfsG0XUAGRIPTsE8FZW:-NgzZTUsCHJH8V4PEV4q:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/81e0c5a46adbae8202900e4f7929b59d2535ab23/pkg/sql/opt/table_meta.go#L261)):*
<details><summary><i>Previously, msirek (Mark Sirek) wrote…</i></summary><blockquote>

I believe this should be 
```
	tm.cachedIndexVisibility.Add(indexOrd)
	if isNotVisible {
		tm.notVisibleIndexes.Add(indexOrd)
	}
```
</blockquote></details>

Done.

**Review by mgartner — APPROVED** [review]
Very nice! :lgtm: 

> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/111698#-:-Nh3o5nu6Tv6z7vOvoqa:bup7q37)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @msirek)

**Comment by DrewKimball** [comment]
TFTR!

bors r+

**Comment by DrewKimball** [comment]
bors r=mgartner
