### PR TITLE
sql: add timeout for PCR reader catalog lease acquisition

### LINKED ISSUE #141565: cli: TestUnavailableZip failed
cli.TestUnavailableZip [failed](https://tanzanite.cluster.engflow.com/invocations/default/c8b30906-1529-446f-bc0e-f9f80109b37f?testReportRun=3&testReportShard=13&testReportAttempt=1#targets-Ly9wa2cvY2xpOmNsaV90ZXN0) on master @ [34e34c2d5b9598441b935f03a794277e9329a256](https://github.com/cockroachdb/cockroach/commits/34e34c2d5b9598441b935f03a794277e9329a256):

Fatal error:

```
panic: test timed out after 25m0s
running tests:
	TestUnavailableZip (25m0s)
	TestUnavailableZip/server_2 (24m18s)

```
Stack: 

```
goroutine 47759229 [running]:
testing.(*M).startAlarm.func1()
	GOROOT/src/testing/testing.go:2366 +0x385
created by time.goFunc
	GOROOT/src/time/sleep.go:177 +0x2d
```
<details><summary>Log preceding fatal error</summary>
<p>

```
=== RUN   TestUnavailableZip
    test_log_scope.go:165: test logs captured to: outputs.zip/logTestUnavailableZip2140135756
    test_log_scope.go:76: use -show-logs to present logs inline
    test_log_scope.go:165: test logs captured to: outputs.zip/logTestUnavailableZip1305647791
=== RUN   TestUnavailableZip/server_1
[debug --host=127.0.0.1:46475 --insecure=true zip --concurrency=1 --cpu-profile-duration=0 /dev/null --timeout=.5s]
=== RUN   TestUnavailableZip/server_2
[debug --host=127.190.153.84:33639 --insecure=true zip --concurrency=1 --cpu-profile-duration=0 /dev/null --timeout=.5s]
```
</p>
</details>

Parameters:
 - <code>attempt=1</code>
 - <code>deadlock=true</code>
 - <code>run=3</code>
 - <code>shard=13</code>
<details><summary>Help</summary>
<p>

See also: [How To Investigate a Go Test Failure \(internal\)](https://cockroachlabs.atlassian.net/l/c/HgfXfJgM)
</p>
</details>
/cc @cockroachdb/obs-prs @cockroachdb/server @cockroachdb/obs-india-prs
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*TestUnavailableZip.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/bazci/githubpost/issues)

</sub>

Jira issue: CRDB-47900

### PR DESCRIPTION
**Pull request by fqazi**
Previously, the logic to determine if a PCR reader catalog was in use could become stuck if an availability issue occurred with the leasing subsystem. This was because we could end up waiting indefinitely for the lease in failure scenarios like TestUnavailableZipDir, and the statement_timeout is not active this early. To address this, this patch adds a 30-second timeout for obtaining a lease on the system database when detecting PCR reader catalogs.

Fixes: #141565

Release note: None

### CODE REVIEW

**Review by rafiss — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/143669)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @aa-joshi, @Abhinav1299, @angles-n-daemons, and @arjunmahishi)

___
*[`pkg/sql/conn_executor.go` line 3837 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/143669#-ONGteb01D7PRKQNKz9B:-ONGteb01D7PRKQNKz9C:bbkxg0g) ([raw file](https://github.com/cockroachdb/cockroach/blob/0f3354b8ddc807d16b5e56b32f44a282e43c0159/pkg/sql/conn_executor.go#L3837)):*
> ```Go
> // we are connecting to a PCR reader catalog, if this has not been attempted
> // before.
> func (ex *connExecutor) maybeInitPCRReaderCatalog(ctx context.Context) {
> ```

is this safe to call concurrently?

i'm wondering if the init needs to happen inside of a `sync.Once`, so that way if there are concurrent calls that all try to initialize it, they will block until the init is done.

**Review by fqazi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/143669)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @aa-joshi, @Abhinav1299, @angles-n-daemons, @arjunmahishi, and @rafiss)

___
*[`pkg/sql/conn_executor.go` line 3837 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/143669#-ONGteb01D7PRKQNKz9B:-ONI0K1X3H7M-5oFGJW7:b4crcre) ([raw file](https://github.com/cockroachdb/cockroach/blob/0f3354b8ddc807d16b5e56b32f44a282e43c0159/pkg/sql/conn_executor.go#L3837)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

is this safe to call concurrently?

i'm wondering if the init needs to happen inside of a `sync.Once`, so that way if there are concurrent calls that all try to initialize it, they will block until the init is done.
</blockquote></details>

Done.

Good point changed this to a sync.Once

**Review by rafiss — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/143669)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @aa-joshi, @Abhinav1299, @angles-n-daemons, and @arjunmahishi)

___
*[`pkg/sql/conn_executor.go` line 3857 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/143669#-ONM0s2B0zWz2V29zEj4:-ONM0s2B0zWz2V29zEj5:b5mekro) ([raw file](https://github.com/cockroachdb/cockroach/blob/f1c965a371d19cd999693f1755eb1fc751051cab/pkg/sql/conn_executor.go#L3857)):*
> ```Go
> 		// unless there is some availability issue.
> 		const initPCRReaderCatalogTimeout = 30 * time.Second
> 		err := timeutil.RunWithTimeout(ctx, "detect-pcr-reader-catalog", initPCRReaderCatalogTimeout,
> ```

one more thing i wanted to ask: what if we keep the initialization code in `newConnExecutor`, but add the 30 second timeout there. does that resolve the test issue as well?

**Review by fqazi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/143669)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @aa-joshi, @Abhinav1299, @angles-n-daemons, @arjunmahishi, and @rafiss)

___
*[`pkg/sql/conn_executor.go` line 3857 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/143669#-ONM0s2B0zWz2V29zEj4:-ONM7XrFD_QaVuJnTgix:b38846e) ([raw file](https://github.com/cockroachdb/cockroach/blob/f1c965a371d19cd999693f1755eb1fc751051cab/pkg/sql/conn_executor.go#L3857)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

one more thing i wanted to ask: what if we keep the initialization code in `newConnExecutor`, but add the 30 second timeout there. does that resolve the test issue as well?
</blockquote></details>

Yeah that also resolves the issue, I'll move it back there

**Review by rafiss — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/143669)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @aa-joshi, @Abhinav1299, @angles-n-daemons, @arjunmahishi, and @fqazi)

___
*[`pkg/sql/conn_executor.go` line 3857 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/143669#-ONM0s2B0zWz2V29zEj4:-ONM7z-CD5q5eRh1GZqo:b9aw32k) ([raw file](https://github.com/cockroachdb/cockroach/blob/f1c965a371d19cd999693f1755eb1fc751051cab/pkg/sql/conn_executor.go#L3857)):*
<details><summary><i>Previously, fqazi (Faizan Qazi) wrote…</i></summary><blockquote>

Yeah that also resolves the issue, I'll move it back there
</blockquote></details>

thanks, i'd be more comfortable with that since lazy initialization usually leads to added complexity

**Review by fqazi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/143669)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @aa-joshi, @Abhinav1299, @angles-n-daemons, @arjunmahishi, and @rafiss)

___
*[`pkg/sql/conn_executor.go` line 3857 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/143669#-ONM0s2B0zWz2V29zEj4:-ONPSmK0EnLYzK07YX6I:b-lgt74a) ([raw file](https://github.com/cockroachdb/cockroach/blob/f1c965a371d19cd999693f1755eb1fc751051cab/pkg/sql/conn_executor.go#L3857)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

thanks, i'd be more comfortable with that since lazy initialization usually leads to added complexity
</blockquote></details>

Done.

I also reduced the timeout to 10 seconds.

File: pkg/sql/conn_executor.go [hunk 1]
```diff
@@ -3852,6 +3843,34 @@ func (ex *connExecutor) initEvalCtx(ctx context.Context, evalCtx *extendedEvalCo
 	evalCtx.copyFromExecCfg(ex.server.cfg)
 }
 
+// maybeInitPCRReaderCatalog leases the system database to determine if
```
Comment (rafiss) [inline pkg/sql/conn_executor.go:3846]: nit: the comment should say `initPCRReaderCatalog`, not `maybeInitPCRReaderCatalog`

**Review by rafiss — APPROVED** [review]

**Comment by fqazi** [comment]
@rafiss TFTR!

bors r+
