### PR TITLE
cli: fix import CLI test deadlock

### LINKED ISSUE #65588: cli: deadlock in TestImportCLI
I was working in an unrelated PR which causes certain CLI commands to fail.
As I was attempting to debug this, my troubleshooting steps were seriously impeded by a deadlock in `TestImportCLI`.

The problem is this code in `runImportCLICommand()`:

```go
  wg.Add(1)

  go λ() {
    out, err = c.RunWithCapture(cliCmd)
    require.NoError(t, err)
    wg.Done()
  }()
```

When the command encounters an error, `require.NoError` stops the goroutine, and `wg.Done` is never called, and the test deadlocks.

This needs to be changed to only check the error after the goroutine terminates.
Additionally, the remainder of the code underneath must properly handle the case when the import command fails to update `knobs.uploadComplete`. For this a `select` should be used that combines a read on an error channel.

### PR DESCRIPTION
**Pull request by adityamaru**
Fixes: #65588

Release note: None

### CODE REVIEW

File: pkg/cli/import_test.go [hunk 1]
```diff
@@ -41,24 +40,34 @@ func runImportCLICommand(
...
-	var wg sync.WaitGroup
-	wg.Add(1)
 
+	errCh := make(chan error)
+	defer close(errCh)
 	go func() {
 		out, err = c.RunWithCapture(cliCmd)
-		require.NoError(t, err)
-		wg.Done()
+		errCh <- err
```
Comment (knz) [inline pkg/cli/import_test.go:48]: This will leak a goroutine if the code below stops (e.g. at require.NoError) before it reads.

You can avert that:
- by adding a buffer of 1 in the channel in the `make` above, OR
- by closing the channel here after writing to it and deferring a read from the channel in the function above before creating the goroutine

Comment (adityamaru) [reply pkg/cli/import_test.go:48]: oh interesting, in the buffer of 1 case, I think I also need to remove the `defer close(errCh)` too? Otherwise, the `require.NoError` would cause the test to return, closing the channel, and then the goroutine would panic on write to a closed channel.

Comment (knz) [reply pkg/cli/import_test.go:48]: you only `close` inside the goroutine, not the outer function. (With a defer to tolerate panics inside the goroutine)

**Review by knz — APPROVED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/65651)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @adityamaru)

**Review by knz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/65651)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @adityamaru)

___
*[pkg/cli/import_test.go, line 56 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/65651#-Mac4QpLD-bohkHfqJY-:-Mac4QpLD-bohkHfqJY0:b-ymr2rt) ([raw file](https://github.com/cockroachdb/cockroach/blob/6c861caedc0816cc15438d749332a71c0a701f1e/pkg/cli/import_test.go#L56)):*
> ```Go
> 	case <-knobs.uploadComplete:
> 	case err := <-errCh:
> 		t.Fatalf("%s: import command returned before expected", err.Error())
> ```

if the goroutine panics, then this read will read with `err == nil` (because the err channel will be closed before a value is written to it), and consequently the `err.Error()` call will panic.

Just don't use `err.Error()`, ever. Use `Fatalf("... %v", err)` and that will do the right thing.

**Review by knz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/65651)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @adityamaru)

___
*[pkg/cli/import_test.go, line 65 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/65651#-Mac4dyH8H1LM-dPEMeU:-Mac4dyI1UZUE8LhDUbf:b-7ropln) ([raw file](https://github.com/cockroachdb/cockroach/blob/6c861caedc0816cc15438d749332a71c0a701f1e/pkg/cli/import_test.go#L65)):*
> ```Go
> 	case knobs.pauseAfterUpload <- struct{}{}:
> 	case err := <-errCh:
> 		t.Fatalf("%s: import command returned before expected", err.Error())
> ```

ditto

**Comment by adityamaru** [comment]
TFTR!

bors r=knz
