### PR TITLE
roachtest: jepsen returns with exit code 255 when encountering unhandled exceptions

### LINKED ISSUE #99681: roachtest: jepsen returns with exit code 255 when encountering unhandled exceptions
When encountering an unhandled exception, Jepsen returns a `255` exit code [1]

This is problematic for roachtest error categorisation, as `255` will be marked as an SSH flake. 

The jepsen roachtest should check specifically for `255` when running the jepsen jar file, and wrap into a different error. We may also need to "unmark" the error as an SSH flake which happens automatically when a 255 exit code is encountered in roachprod

We could also change the jepsen code to return something other than 255.

[1] - https://github.com/cockroachdb/jepsen/blob/3d7c345d6958f067edb097f9b82ab8e7a4a752c7/jepsen/src/jepsen/cli.clj#L278-L280

Jira issue: CRDB-26021

### PR DESCRIPTION
**Pull request by srosenberg**
Jepsen exits with `255` if an uhandled exception is raised. The error code is typically associated with SSH errors. Thus, the framework ends up misclassifying it as an SSH flake.

This change wraps the jepsen runner script with a remapping of the exit code so that `255` is now mapped into `254`.

In the process of testing the change, a couple of other issues were uncovered. `FetchLogs` now correctly skips downloading non-existent logs. Also, as of [1], Jepsen should be compiled and executed with JDK 1.17+, so we updated `tc-nightly-main` [2].

[1] https://github.com/cockroachdb/jepsen/commit/d3e8f55208fbc509d55684e4506daee9ad94e49f
[2] https://github.com/cockroachdb/jepsen/commit/50a97a184ae689e235a9b4838231c1199570668a

Epic: none
Fixes: #99681
Release note: None

### CODE REVIEW

**Comment by srosenberg** [comment]
[GCE SMOKE TEST](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/19920825?buildTab=log&logFilter=debug&focusLine=6&logView=linear)

File: pkg/cmd/roachtest/tests/jepsen.go [hunk 1]
```diff
@@ -119,7 +119,7 @@ func initJepsen(ctx context.Context, t test.Test, c cluster.Cluster, j jepsenCon
 	// so do it before the initialization check for ease of iteration.
 	if err := c.GitClone(
 		ctx, t.L(),
-		"https://github.com/cockroachdb/jepsen", "/mnt/data1/jepsen", "tc-nightly", controller,
+		"https://github.com/cockroachdb/jepsen", "/mnt/data1/jepsen", repoBranch, controller,
```
Comment (DarrylWong) [inline pkg/cmd/roachtest/tests/jepsen.go]: nit: could also replace the github link with `jepsenRepo`

**Review by DarrylWong — APPROVED** [review]

File: pkg/roachprod/roachprod.go [hunk 2]
```diff
@@ -3026,40 +3026,48 @@ func FetchLogs(
...
 					l.Printf("failed to fetch log directory %s: %v", logDir, err)
 					if ctx.Err() != nil {
 						return errors.Wrap(err, "cluster.FetchLogs")
 					}
 				}
 			}
-
-			if err := c.Run(ctx, l, l.Stdout, l.Stderr, install.WithNodes(c.Nodes), "", fmt.Sprintf("mkdir -p logs/redacted && %s debug merge-logs --redact logs/*.log > logs/redacted/combined.log", test.DefaultCockroachPath)); err != nil {
+			// Create a single redacted log.
+			if err := c.Run(ctx, l, l.Stdout, l.Stderr, install.WithNodes(nodes), "", fmt.Sprintf("mkdir -p logs/redacted && %s debug merge-logs --redact logs/*.log > logs/redacted/combined.log", test.DefaultCockroachPath)); err != nil {
```
Comment (DarrylWong) [inline pkg/roachprod/roachprod.go]: `test.DefaultCockroachPath` 👀 

We probably shouldn't be importing `roachtest/test` here. Just ran into a cyclical import on an unrelated change because of this.

Comment (srosenberg) [reply pkg/roachprod/roachprod.go]: Oops, good find!

**Comment by srosenberg** [comment]
All of the jepsens passed, so hopefully no regressions with this change 🤞 

pass

File: pkg/roachprod/roachprod.go (hunk 2 above)
Comment (srosenberg) [reply pkg/roachprod/roachprod.go]: Removed and added `disallowed_imports_test`.

**Comment by srosenberg** [comment]
TFTR!

bors r=darrylwong
