### PR TITLE
jobs: fix TestJitterCalculation failed

### LINKED ISSUE #128381: jobs: TestJitterCalculation failed
jobs.TestJitterCalculation [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Ci_TestsAwsLinuxArm64_UnitTests/16347664?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Ci_TestsAwsLinuxArm64_UnitTests/16347664?buildTab=artifacts#/) on master @ [9915bd965cab50ff5e7c9214447a360deec67cd5](https://github.com/cockroachdb/cockroach/commits/9915bd965cab50ff5e7c9214447a360deec67cd5):

```
=== RUN   TestJitterCalculation
--- FAIL: TestJitterCalculation (0.00s)
=== RUN   TestJitterCalculation/small
    registry_test.go:1236: 
        	Error Trace:	github.com/cockroachdb/cockroach/pkg/jobs/registry_test.go:1236
        	Error:      	Should not be: 1000000
        	Test:       	TestJitterCalculation/small
    --- FAIL: TestJitterCalculation/small (0.00s)
```
<details><summary>Help</summary>
<p>

See also: [How To Investigate a Go Test Failure \(internal\)](https://cockroachlabs.atlassian.net/l/c/HgfXfJgM)
</p>
</details>
/cc @cockroachdb/jobs @cockroachdb/disaster-recovery
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*TestJitterCalculation.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/bazci/githubpost/issues)
</sub>

Jira issue: CRDB-40985

### LINKED ISSUE #157113: jobs: TestJitterCalculation failed
jobs.TestJitterCalculation [failed](https://mesolite.cluster.engflow.com/invocations/default/4af14eb6-8d2a-4c5b-9910-d0c494001096?testReportRun=3&testReportShard=11&testReportAttempt=1#targets-Ly9wa2cvam9iczpqb2JzX3Rlc3Q=) on release-24.3.23-rc @ [312bef74c778c17fb77228c22838fb3efd331562](https://github.com/cockroachdb/cockroach/commits/312bef74c778c17fb77228c22838fb3efd331562):

```
=== RUN   TestJitterCalculation
--- FAIL: TestJitterCalculation (0.00s)
=== RUN   TestJitterCalculation/small
    registry_test.go:1234: 
        	Error Trace:	pkg/jobs/registry_test.go:1234
        	Error:      	Should not be: 1000000
        	Test:       	TestJitterCalculation/small
    --- FAIL: TestJitterCalculation/small (0.00s)
```

Parameters:
 - <code>attempt=1</code>
 - <code>race=true</code>
 - <code>run=3</code>
 - <code>shard=11</code>
<details><summary>Help</summary>
<p>

See also: [How To Investigate a Go Test Failure \(internal\)](https://cockroachlabs.atlassian.net/l/c/HgfXfJgM)
</p>
</details>
/cc @cockroachdb/jobs @cockroachdb/disaster-recovery
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*TestJitterCalculation.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/bazci/githubpost/issues)

</sub>

Jira issue: CRDB-56367

### PR DESCRIPTION
**Pull request by jeffswenson**
This test will sometimes fail due to a randomly picking a value that
rounds to 1/2. The frequency of this is a bit higher than one would
expect because the rounding behavior depends on the width of the
duration, not the width of a float64. The test was adjusted to retry
if the jittered value equals the input.

Release note: none
Fixes: #128381
Fixes: #157113

### CODE REVIEW

File: pkg/jobs/registry_test.go [hunk 1]
```diff
@@ -688,6 +689,12 @@ func TestJitterCalculation(t *testing.T) {
 		return time.Duration(float64(input) * minFactor), time.Duration(float64(input) * maxFactor)
 	}
 
+	// Chosen by a fair dice roll. We use a determinstic seed to avoid the case
+	// where the test flakes because the random value rounds to 1/2. This is more
+	// common than you would expect because its probability is based on the width
+	// of the duration, not the width of the random float.
+	rand.Seed(4)
```
Comment (stevendanna) [inline pkg/jobs/registry_test.go]: I was a little concerned that setting this global seed might impact other randomized tests. But then I read that perhaps this isn't doing what we want in the first place:

```
// As of Go 1.24 [Seed] is a no-op. To restore the previous behavior set
// GODEBUG=randseednop=0.
```

Comment (jeffswenson) [reply pkg/jobs/registry_test.go]: Good point on both counts. I switched strategies and rewrote the test to retry cases where input == output.

**Review by stevendanna — APPROVED** [review]
LGTM.

Might be worth a comment on why we might need to retry.

**Comment by jeffswenson** [comment]
Thanks for a review! I added a comment.
