### PR TITLE
server: fix TestReportUsage

### LINKED ISSUE #38174: server: TestDiagnosticsResponse leaks a goroutine
It currently fails on master with the following leak. It only seems to fail on OSX, not on Linux.
I've bisected it to #37272
@sploiselle you want it? Or we can pass to @dt.

```
make testshort PKG=./pkg/server TESTS=TestDiagnosticsResponse

    leaktest.go:122: Leaked goroutine: goroutine 807 [chan receive]:
        net/http.(*Transport).getConn.func2.1(0xc000c9b4a0, 0x85fb2e0, 0x0, 0x0, 0x67c4ddd, 0x4, 0xc001160b40, 0x12, 0x68758f8)
        	/Users/andrei/go/src/net/http/transport.go:965 +0x4a
        created by net/http.(*Transport).getConn.func2
        	/Users/andrei/go/src/net/http/transport.go:964 +0xa6


        Leaked goroutine: goroutine 854 [IO wait]:
        internal/poll.runtime_pollWait(0xddc20f0, 0x77, 0xc000dfdb00)
        	/Users/andrei/go/src/runtime/netpoll.go:173 +0x66
        internal/poll.(*pollDesc).wait(0xc001012898, 0x77, 0xc000e39300, 0x403820e, 0xc000e39340)
        	/Users/andrei/go/src/internal/poll/fd_poll_runtime.go:85 +0x9a
        internal/poll.(*pollDesc).waitWrite(0xc001012898, 0x0, 0xc000dfdb00, 0x422118f)
        	/Users/andrei/go/src/internal/poll/fd_poll_runtime.go:94 +0x3d
        internal/poll.(*FD).WaitWrite(0xc001012880, 0x68755c0, 0x6e23da0)
        	/Users/andrei/go/src/internal/poll/fd_unix.go:497 +0x37
        net.(*netFD).connect(0xc001012880, 0x6e23da0, 0xc00141bec0, 0x0, 0x0, 0x6df55e0, 0xc001160b60, 0x0, 0x0, 0x0, ...)
        	/Users/andrei/go/src/net/fd_unix.go:152 +0x272
        net.(*netFD).dial(0xc001012880, 0x6e23da0, 0xc00141bec0, 0x6e3b3e0, 0x0, 0x6e3b3e0, 0xc0011783c0, 0x0, 0xc000e39590, 0x423ed6e)
        	/Users/andrei/go/src/net/sock_posix.go:149 +0xff
        net.socket(0x6e23da0, 0xc00141bec0, 0x6728782, 0x3, 0x2, 0x1, 0x0, 0x0, 0x6e3b3e0, 0x0, ...)
        	/Users/andrei/go/src/net/sock_posix.go:70 +0x1ab
        net.internetSocket(0x6e23da0, 0xc00141bec0, 0x6728782, 0x3, 0x6e3b3e0, 0x0, 0x6e3b3e0, 0xc0011783c0, 0x1, 0x0, ...)
        	/Users/andrei/go/src/net/ipsock_posix.go:141 +0x141
        net.(*sysDialer).doDialTCP(0xc001012800, 0x6e23da0, 0xc00141bec0, 0x0, 0xc0011783c0, 0x6404700, 0x8662190, 0x0)
        	/Users/andrei/go/src/net/tcpsock_posix.go:65 +0xc2
        net.(*sysDialer).dialTCP(0xc001012800, 0x6e23da0, 0xc00141bec0, 0x0, 0xc0011783c0, 0xc000e397c8, 0x4213a78, 0xbf392611079ea50c)
        	/Users/andrei/go/src/net/tcpsock_posix.go:61 +0xd7
        net.(*sysDialer).dialSingle(0xc001012800, 0x6e23da0, 0xc00141bec0, 0x6e060e0, 0xc0011783c0, 0x0, 0x0, 0x0, 0x0)
        	/Users/andrei/go/src/net/dial.go:556 +0x348
        net.(*sysDialer).dialSerial(0xc001012800, 0x6e23da0, 0xc00141bec0, 0xc00115a430, 0x1, 0x1, 0x0, 0x0, 0x0, 0x0)
        	/Users/andrei/go/src/net/dial.go:524 +0x227
        net.(*Dialer).DialContext(0xc0000ee2a0, 0x6e23d60, 0xc0000de008, 0x6728782, 0x3, 0xc001160b40, 0x12, 0x0, 0x0, 0x0, ...)
        	/Users/andrei/go/src/net/dial.go:406 +0x639
        net.(*Dialer).DialContext-fm(0x6e23d60, 0xc0000de008, 0x6728782, 0x3, 0xc001160b40, 0x12, 0x40070f3, 0x42bf929, 0xc0000de008, 0x6404820)
        	/Users/andrei/go/src/net/http/transport.go:48 +0x73
        net/http.(*Transport).dial(0x85fb2e0, 0x6e23d60, 0xc0000de008, 0x6728782, 0x3, 0xc001160b40, 0x12, 0xc001728a50, 0xc000e1cc68, 0x424840b, ...)
        	/Users/andrei/go/src/net/http/transport.go:916 +0x20f
        net/http.(*Transport).dialConn(0x85fb2e0, 0x6e23d60, 0xc0000de008, 0x0, 0x67c4ddd, 0x4, 0xc001160b40, 0x12, 0x6e50640, 0xc0002deb80, ...)
        	/Users/andrei/go/src/net/http/transport.go:1240 +0x313
        net/http.(*Transport).getConn.func4(0x85fb2e0, 0x6e23d60, 0xc0000de008, 0xc001178300, 0xc000c9b4a0)
        	/Users/andrei/go/src/net/http/transport.go:999 +0x6e
        created by net/http.(*Transport).getConn
        	/Users/andrei/go/src/net/http/transport.go:998 +0x3d7

        Leaked goroutine: goroutine 855 [select]:
        net.(*netFD).connect.func2(0x6e23da0, 0xc00141bec0, 0xc001012880, 0xc000c9b6e0, 0xc000c9b680)
        	/Users/andrei/go/src/net/fd_unix.go:129 +0xba
        created by net.(*netFD).connect
        	/Users/andrei/go/src/net/fd_unix.go:128 +0x25f
```

### LINKED ISSUE #38176: server: TestReportUsage failed under stress
SHA: https://github.com/cockroachdb/cockroach/commits/cee0b362d9f982446444b4a704db86e0cbac7c6d

Parameters:
```
TAGS=
GOFLAGS=
```

To repro, try:

```
# Don't forget to check out a clean suitable branch and experiment with the
# stress invocation until the desired results present themselves. For example,
# using stress instead of stressrace and passing the '-p' stressflag which
# controls concurrency.
./scripts/gceworker.sh start && ./scripts/gceworker.sh mosh
cd ~/go/src/github.com/cockroachdb/cockroach && \
stdbuf -oL -eL \
make stressrace TESTS=TestReportUsage PKG=github.com/cockroachdb/cockroach/pkg/server TESTTIMEOUT=5m STRESSFLAGS='-maxtime 20m -timeout 10m' 2>&1 | tee /tmp/stress.log
```

Failed test: https://teamcity.cockroachdb.com/viewLog.html?buildId=1339976&tab=buildLog

```
3      storage.IntentResolver: processing intents
2      [async] closedts-rangefeed-subscriber
1      node.Node: writing summary
1      [async] intent_resolver_ir_batcher
1      [async] intent_resolver_gc_batcher
W190615 06:12:14.624248 46550 storage/intentresolver/intent_resolver.go:822  failed to gc transaction record: could not GC completed transaction anchored at /Table/SystemConfigSpan/Start: node unavailable; try another peer
I190615 06:12:14.624270 46030 util/stop/stopper.go:546  quiescing; tasks left:
5      [async] storage.IntentResolver: cleanup txn records
3      storage.IntentResolver: processing intents
2      [async] closedts-rangefeed-subscriber
1      node.Node: writing summary
1      [async] intent_resolver_ir_batcher
1      [async] intent_resolver_gc_batcher
I190615 06:12:14.624297 46030 util/stop/stopper.go:546  quiescing; tasks left:
4      [async] storage.IntentResolver: cleanup txn records
3      storage.IntentResolver: processing intents
2      [async] closedts-rangefeed-subscriber
1      node.Node: writing summary
1      [async] intent_resolver_ir_batcher
1      [async] intent_resolver_gc_batcher
I190615 06:12:14.624323 46030 util/stop/stopper.go:546  quiescing; tasks left:
3      storage.IntentResolver: processing intents
3      [async] storage.IntentResolver: cleanup txn records
2      [async] closedts-rangefeed-subscriber
1      node.Node: writing summary
1      [async] intent_resolver_ir_batcher
1      [async] intent_resolver_gc_batcher
I190615 06:12:14.624352 46030 util/stop/stopper.go:546  quiescing; tasks left:
3      storage.IntentResolver: processing intents
2      [async] storage.IntentResolver: cleanup txn records
2      [async] closedts-rangefeed-subscriber
1      node.Node: writing summary
1      [async] intent_resolver_ir_batcher
1      [async] intent_resolver_gc_batcher
I190615 06:12:14.624383 46030 util/stop/stopper.go:546  quiescing; tasks left:
3      storage.IntentResolver: processing intents
2      [async] closedts-rangefeed-subscriber
1      node.Node: writing summary
1      [async] storage.IntentResolver: cleanup txn records
1      [async] intent_resolver_ir_batcher
1      [async] intent_resolver_gc_batcher
I190615 06:12:14.624418 46030 util/stop/stopper.go:546  quiescing; tasks left:
3      storage.IntentResolver: processing intents
2      [async] closedts-rangefeed-subscriber
1      node.Node: writing summary
1      [async] intent_resolver_ir_batcher
1      [async] intent_resolver_gc_batcher
W190615 06:12:14.624464 46284 server/node.go:839  [n1,summaries] error recording initial status summaries: failed to send RPC: sending to all 1 replicas failed; last error: (err: [NotLeaseHolderError] r3: replica (n1,s1):1 not lease holder; lease holder unknown) <nil>
I190615 06:12:14.624491 46030 util/stop/stopper.go:546  quiescing; tasks left:
3      storage.IntentResolver: processing intents
2      [async] closedts-rangefeed-subscriber
1      [async] intent_resolver_ir_batcher
1      [async] intent_resolver_gc_batcher
I190615 06:12:14.624538 46030 util/stop/stopper.go:546  quiescing; tasks left:
3      storage.IntentResolver: processing intents
2      [async] closedts-rangefeed-subscriber
1      [async] intent_resolver_gc_batcher
I190615 06:12:14.624559 46030 util/stop/stopper.go:546  quiescing; tasks left:
3      storage.IntentResolver: processing intents
2      [async] closedts-rangefeed-subscriber
I190615 06:12:14.634404 46030 util/stop/stopper.go:546  quiescing; tasks left:
2      storage.IntentResolver: processing intents
2      [async] closedts-rangefeed-subscriber
I190615 06:12:14.634451 46030 util/stop/stopper.go:546  quiescing; tasks left:
2      [async] closedts-rangefeed-subscriber
1      storage.IntentResolver: processing intents
I190615 06:12:14.634479 46030 util/stop/stopper.go:546  quiescing; tasks left:
1      [async] closedts-rangefeed-subscriber
--- FAIL: TestReportUsage (0.19s)
    updates_test.go:404: error applying zone config "constraints: [+zone=somestring, +somestring]" to "TABLE system.rangelog": pq: constraint "+zone=somestring" matches no existing nodes within the cluster - did you enter it correctly?

```

### PR DESCRIPTION
**Pull request by tbg**
- Fixes a goroutine leak under darwin (when dialing
tcp://instance-data.ec2.internal:80 as we happen to try we end up with
TCP-level timeouts, and that apparently takes long on OSX unless we
override the default)

- Works around a gossip-related flake.

Fixes #38174.
Fixes #38176.

Release note: None

### CODE REVIEW

File: pkg/server/updates.go [hunk 1]
```diff
@@ -454,7 +455,20 @@ func (s *Server) reportDiagnostics(ctx context.Context) {
 		return
 	}
 	addInfoToURL(ctx, reportingURL, s, report.Node)
-	res, err := http.Post(reportingURL.String(), "application/x-protobuf", bytes.NewReader(b))
+
+	const timeout = 3 * time.Second
+	client := &http.Client{
```
Comment (dt) [inline pkg/server/updates.go]: Do we need this one? *this* conn shouldn't fail in weird ways should it?

**Review by dt — APPROVED** [review]

File: pkg/server/updates.go (hunk 1 above)
Comment (tbg) [reply pkg/server/updates.go]: We don't need it for the test, but using a client without a timeout also seemed like a bad idea. Let me know if you have concerns about this and I'll follow up.

**Comment by tbg** [comment]
bors r=dt
TFTR!
