### PR TITLE
sql: fix error log spam from SHOW CREATE

### LINKED ISSUE #83351: sql: scary warning log when reading `crdb_internal.create_statements`
**Describe the problem**
I think this is fallout from the 32-bit OID change (https://github.com/cockroachdb/cockroach/pull/82568). 

```
W220624 19:56:35.015463 19589 sql/show_create_clauses.go:164 ⋮ [n1,client=127.0.0.1:57011,user=root] 144  error deserializing user defined types for view ‹ranges› (4294967248): ‹crdb_internal.range_stats›(): column ‹"start_key"› does not exist
W220624 19:56:35.015463 19589 sql/show_create_clauses.go:164 ⋮ [n1,client=127.0.0.1:57011,user=root] 144 +(1) candidate pg code: 22023
W220624 19:56:35.015463 19589 sql/show_create_clauses.go:164 ⋮ [n1,client=127.0.0.1:57011,user=root] 144 +Wraps: (2) attached stack trace
W220624 19:56:35.015463 19589 sql/show_create_clauses.go:164 ⋮ [n1,client=127.0.0.1:57011,user=root] 144 +  -- stack trace:
W220624 19:56:35.015463 19589 sql/show_create_clauses.go:164 ⋮ [n1,client=127.0.0.1:57011,user=root] 144 +  | github.com/cockroachdb/cockroach/pkg/sql/sem/tree.(*FuncExpr).TypeCheck
W220624 19:56:35.015463 19589 sql/show_create_clauses.go:164 ⋮ [n1,client=127.0.0.1:57011,user=root] 144 +  | 	github.com/cockroachdb/cockroach/pkg/sql/sem/tree/type_check.go:1040
W220624 19:56:35.015463 19589 sql/show_create_clauses.go:164 ⋮ [n1,client=127.0.0.1:57011,user=root] 144 +  | github.com/cockroachdb/cockroach/pkg/sql/sem/tree.typeCheckOverloadedExprs
W220624 19:56:35.015463 19589 sql/show_create_clauses.go:164 ⋮ [n1,client=127.0.0.1:57011,user=root] 144 +  | 	github.com/cockroachdb/cockroach/pkg/sql/sem/tree/overload.go:635
W220624 19:56:35.015463 19589 sql/show_create_clauses.go:164 ⋮ [n1,client=127.0.0.1:57011,user=root] 144 +  | github.com/cockroachdb/cockroach/pkg/sql/sem/tree.(*BinaryExpr).TypeCheck
W220624 19:56:35.015463 19589 sql/show_create_clauses.go:164 ⋮ [n1,client=127.0.0.1:57011,user=root] 144 +  | 	github.com/cockroachdb/cockroach/pkg/sql/sem/tree/type_check.go:310
W220624 19:56:35.015463 19589 sql/show_create_clauses.go:164 ⋮ [n1,client=127.0.0.1:57011,user=root] 144 +  | github.com/cockroachdb/cockroach/pkg/sql/sem/tree.(*ParenExpr).TypeCheck
W220624 19:56:35.015463 19589 sql/show_create_clauses.go:164 ⋮ [n1,client=127.0.0.1:57011,user=root] 144 +  | 	github.com/cockroachdb/cockroach/pkg/sql/sem/tree/type_check.go:1334
W220624 19:56:35.015463 19589 sql/show_create_clauses.go:164 ⋮ [n1,client=127.0.0.1:57011,user=root] 144 +  | github.com/cockroachdb/cockroach/pkg/sql/sem/tree.(*CastExpr).TypeCheck
W220624 19:56:35.015463 19589 sql/show_create_clauses.go:164 ⋮ [n1,client=127.0.0.1:57011,user=root] 144 +  | 	github.com/cockroachdb/cockroach/pkg/sql/sem/tree/type_check.go:572
W220624 19:56:35.015463 19589 sql/show_create_clauses.go:164 ⋮ [n1,client=127.0.0.1:57011,user=root] 144 +  | github.com/cockroachdb/cockroach/pkg/sql/sem/tree.TypeCheck
W220624 19:56:35.015463 19589 sql/show_create_clauses.go:164 ⋮ [n1,client=127.0.0.1:57011,user=root] 144 +  | 	github.com/cockroachdb/cockroach/pkg/sql/sem/tree/type_check.go:266
W220624 19:56:35.015463 19589 sql/show_create_clauses.go:164 ⋮ [n1,client=127.0.0.1:57011,user=root] 144 +  | github.com/cockroachdb/cockroach/pkg/sql.formatViewQueryTypesForDisplay.func1
W220624 19:56:35.015463 19589 sql/show_create_clauses.go:164 ⋮ [n1,client=127.0.0.1:57011,user=root] 144 +  | 	github.com/cockroachdb/cockroach/pkg/sql/show_create_clauses.go:218
W220624 19:56:35.015463 19589 sql/show_create_clauses.go:164 ⋮ [n1,client=127.0.0.1:57011,user=root] 144 +  | github.com/cockroachdb/cockroach/pkg/sql/sem/tree.(*simpleVisitor).VisitPre
W220624 19:56:35.015463 19589 sql/show_create_clauses.go:164 ⋮ [n1,client=127.0.0.1:57011,user=root] 144 +  | 	github.com/cockroachdb/cockroach/pkg/sql/sem/tree/walk.go:1710
W220624 19:56:35.015463 19589 sql/show_create_clauses.go:164 ⋮ [n1,client=127.0.0.1:57011,user=root] 144 +  | github.com/cockroachdb/cockroach/pkg/sql/sem/tree.WalkExpr
W220624 19:56:35.015463 19589 sql/show_create_clauses.go:164 ⋮ [n1,client=127.0.0.1:57011,user=root] 144 +  | 	github.com/cockroachdb/cockroach/pkg/sql/sem/tree/walk.go:824
W220624 19:56:35.015463 19589 sql/show_create_clauses.go:164 ⋮ [n1,client=127.0.0.1:57011,user=root] 144 +  | github.com/cockroachdb/cockroach/pkg/sql/sem/tree.(*BinaryExpr).Walk
W220624 19:56:35.015463 19589 sql/show_create_clauses.go:164 ⋮ [n1,client=127.0.0.1:57011,user=root] 144 +  | 	github.com/cockroachdb/cockroach/pkg/sql/sem/tree/walk.go:68
W220624 19:56:35.015463 19589 sql/show_create_clauses.go:164 ⋮ [n1,client=127.0.0.1:57011,user=root] 144 +  | github.com/cockroachdb/cockroach/pkg/sql/sem/tree.WalkExpr
W220624 19:56:35.015463 19589 sql/show_create_clauses.go:164 ⋮ [n1,client=127.0.0.1:57011,user=root] 144 +  | 	github.com/cockroachdb/cockroach/pkg/sql/sem/tree/walk.go:827
W220624 19:56:35.015463 19589 sql/show_create_clauses.go:164 ⋮ [n1,client=127.0.0.1:57011,user=root] 144 +  | github.com/cockroachdb/cockroach/pkg/sql/sem/tree.(*SelectClause).walkStmt
W220624 19:56:35.015463 19589 sql/show_create_clauses.go:164 ⋮ [n1,client=127.0.0.1:57011,user=root] 144 +  | 	github.com/cockroachdb/cockroach/pkg/sql/sem/tree/walk.go:1397
W220624 19:56:35.015463 19589 sql/show_create_clauses.go:164 ⋮ [n1,client=127.0.0.1:57011,user=root] 144 +  | github.com/cockroachdb/cockroach/pkg/sql/sem/tree.walkStmt
W220624 19:56:35.015463 19589 sql/show_create_clauses.go:164 ⋮ [n1,client=127.0.0.1:57011,user=root] 144 +  | 	github.com/cockroachdb/cockroach/pkg/sql/sem/tree/walk.go:1695
W220624 19:56:35.015463 19589 sql/show_create_clauses.go:164 ⋮ [n1,client=127.0.0.1:57011,user=root] 144 +  | github.com/cockroachdb/cockroach/pkg/sql/sem/tree.(*Select).walkStmt
W220624 19:56:35.015463 19589 sql/show_create_clauses.go:164 ⋮ [n1,client=127.0.0.1:57011,user=root] 144 +  | 	github.com/cockroachdb/cockroach/pkg/sql/sem/tree/walk.go:1321
W220624 19:56:35.015463 19589 sql/show_create_clauses.go:164 ⋮ [n1,client=127.0.0.1:57011,user=root] 144 +  | github.com/cockroachdb/cockroach/pkg/sql/sem/tree.walkStmt
W220624 19:56:35.015463 19589 sql/show_create_clauses.go:164 ⋮ [n1,client=127.0.0.1:57011,user=root] 144 +  | 	github.com/cockroachdb/cockroach/pkg/sql/sem/tree/walk.go:1695
W220624 19:56:35.015463 19589 sql/show_create_clauses.go:164 ⋮ [n1,client=127.0.0.1:57011,user=root] 144 +  | github.com/cockroachdb/cockroach/pkg/sql/sem/tree.SimpleStmtVisit
W220624 19:56:35.015463 19589 sql/show_create_clauses.go:164 ⋮ [n1,client=127.0.0.1:57011,user=root] 144 +  | 	github.com/cockroachdb/cockroach/pkg/sql/sem/tree/walk.go:1742
W220624 19:56:35.015463 19589 sql/show_create_clauses.go:164 ⋮ [n1,client=127.0.0.1:57011,user=root] 144 +  | github.com/cockroachdb/cockroach/pkg/sql.formatViewQueryTypesForDisplay
W220624 19:56:35.015463 19589 sql/show_create_clauses.go:164 ⋮ [n1,client=127.0.0.1:57011,user=root] 144 +  | 	github.com/cockroachdb/cockroach/pkg/sql/show_create_clauses.go:248
W220624 19:56:35.015463 19589 sql/show_create_clauses.go:164 ⋮ [n1,client=127.0.0.1:57011,user=root] 144 +  | github.com/cockroachdb/cockroach/pkg/sql.formatViewQueryForDisplay
W220624 19:56:35.015463 19589 sql/show_create_clauses.go:164 ⋮ [n1,client=127.0.0.1:57011,user=root] 144 +  | 	github.com/cockroachdb/cockroach/pkg/sql/show_create_clauses.go:162
W220624 19:56:35.015463 19589 sql/show_create_clauses.go:164 ⋮ [n1,client=127.0.0.1:57011,user=root] 144 +  | github.com/cockroachdb/cockroach/pkg/sql.ShowCreateView
W220624 19:56:35.015463 19589 sql/show_create_clauses.go:164 ⋮ [n1,client=127.0.0.1:57011,user=root] 144 +  | 	github.com/cockroachdb/cockroach/pkg/sql/show_create_clauses.go:131
W220624 19:56:35.015463 19589 sql/show_create_clauses.go:164 ⋮ [n1,client=127.0.0.1:57011,user=root] 144 +  | github.com/cockroachdb/cockroach/pkg/sql.glob..func37
W220624 19:56:35.015463 19589 sql/show_create_clauses.go:164 ⋮ [n1,client=127.0.0.1:57011,user=root] 144 +  | 	github.com/cockroachdb/cockroach/pkg/sql/crdb_internal.go:2594
W220624 19:56:35.015463 19589 sql/show_create_clauses.go:164 ⋮ [n1,client=127.0.0.1:57011,user=root] 144 +  | github.com/cockroachdb/cockroach/pkg/sql.makeAllRelationsVirtualTableWithDescriptorIDIndex.func1.1
W220624 19:56:35.015463 19589 sql/show_create_clauses.go:164 ⋮ [n1,client=127.0.0.1:57011,user=root] 144 +  | 	github.com/cockroachdb/cockroach/pkg/sql/pg_catalog.go:1085
W220624 19:56:35.015463 19589 sql/show_create_clauses.go:164 ⋮ [n1,client=127.0.0.1:57011,user=root] 144 +  | github.com/cockroachdb/cockroach/pkg/sql.forEachTableDescWithTableLookupInternalFromDescriptors.func1
W220624 19:56:35.015463 19589 sql/show_create_clauses.go:164 ⋮ [n1,client=127.0.0.1:57011,user=root] 144 +  | 	github.com/cockroachdb/cockroach/pkg/sql/information_schema.go:2426
W220624 19:56:35.015463 19589 sql/show_create_clauses.go:164 ⋮ [n1,client=127.0.0.1:57011,user=root] 144 +  | github.com/cockroachdb/cockroach/pkg/sql.forEachTableDescWithTableLookupInternalFromDescriptors
W220624 19:56:35.015463 19589 sql/show_create_clauses.go:164 ⋮ [n1,client=127.0.0.1:57011,user=root] 144 +  | 	github.com/cockroachdb/cockroach/pkg/sql/information_schema.go:2436
W220624 19:56:35.015463 19589 sql/show_create_clauses.go:164 ⋮ [n1,client=127.0.0.1:57011,user=root] 144 +  | github.com/cockroachdb/cockroach/pkg/sql.forEachTableDescWithTableLookupInternal
W220624 19:56:35.015463 19589 sql/show_create_clauses.go:164 ⋮ [n1,client=127.0.0.1:57011,user=root] 144 +  | 	github.com/cockroachdb/cockroach/pkg/sql/information_schema.go:2364
W220624 19:56:35.015463 19589 sql/show_create_clauses.go:164 ⋮ [n1,client=127.0.0.1:57011,user=root] 144 +  | github.com/cockroachdb/cockroach/pkg/sql.forEachTableDescWithTableLookup
W220624 19:56:35.015463 19589 sql/show_create_clauses.go:164 ⋮ [n1,client=127.0.0.1:57011,user=root] 144 +  | 	github.com/cockroachdb/cockroach/pkg/sql/information_schema.go:2314
W220624 19:56:35.015463 19589 sql/show_create_clauses.go:164 ⋮ [n1,client=127.0.0.1:57011,user=root] 144 +  | github.com/cockroachdb/cockroach/pkg/sql.makeAllRelationsVirtualTableWithDescriptorIDIndex.func1
W220624 19:56:35.015463 19589 sql/show_create_clauses.go:164 ⋮ [n1,client=127.0.0.1:57011,user=root] 144 +  | 	github.com/cockroachdb/cockroach/pkg/sql/pg_catalog.go:1083
W220624 19:56:35.015463 19589 sql/show_create_clauses.go:164 ⋮ [n1,client=127.0.0.1:57011,user=root] 144 +  | github.com/cockroachdb/cockroach/pkg/sql.(*virtualDefEntry).getPlanInfo.func1.1
W220624 19:56:35.015463 19589 sql/show_create_clauses.go:164 ⋮ [n1,client=127.0.0.1:57011,user=root] 144 +  | 	github.com/cockroachdb/cockroach/pkg/sql/virtual_schema.go:573
W220624 19:56:35.015463 19589 sql/show_create_clauses.go:164 ⋮ [n1,client=127.0.0.1:57011,user=root] 144 +  | github.com/cockroachdb/cockroach/pkg/sql.setupGenerator.func3
W220624 19:56:35.015463 19589 sql/show_create_clauses.go:164 ⋮ [n1,client=127.0.0.1:57011,user=root] 144 +  | 	github.com/cockroachdb/cockroach/pkg/sql/virtual_table.go:127
W220624 19:56:35.015463 19589 sql/show_create_clauses.go:164 ⋮ [n1,client=127.0.0.1:57011,user=root] 144 +  | github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunAsyncTaskEx.func2
W220624 19:56:35.015463 19589 sql/show_create_clauses.go:164 ⋮ [n1,client=127.0.0.1:57011,user=root] 144 +  | 	github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:494
W220624 19:56:35.015463 19589 sql/show_create_clauses.go:164 ⋮ [n1,client=127.0.0.1:57011,user=root] 144 +Wraps: (3) ‹crdb_internal.range_stats›()
W220624 19:56:35.015463 19589 sql/show_create_clauses.go:164 ⋮ [n1,client=127.0.0.1:57011,user=root] 144 +Wraps: (4) candidate pg code: 42703
W220624 19:56:35.015463 19589 sql/show_create_clauses.go:164 ⋮ [n1,client=127.0.0.1:57011,user=root] 144 +Wraps: (5) attached stack trace
W220624 19:56:35.015463 19589 sql/show_create_clauses.go:164 ⋮ [n1,client=127.0.0.1:57011,user=root] 144 +  -- stack trace:
W220624 19:56:35.015463 19589 sql/show_create_clauses.go:164 ⋮ [n1,client=127.0.0.1:57011,user=root] 144 +  | github.com/cockroachdb/cockroach/pkg/sql/sem/tree.(*ColumnItem).TypeCheck
W220624 19:56:35.015463 19589 sql/show_create_clauses.go:164 ⋮ [n1,client=127.0.0.1:57011,user=root] 144 +  | 	github.com/cockroachdb/cockroach/pkg/sql/sem/tree/type_check.go:1354
W220624 19:56:35.015463 19589 sql/show_create_clauses.go:164 ⋮ [n1,client=127.0.0.1:57011,user=root] 144 +  | github.com/cockroachdb/cockroach/pkg/sql/sem/tree.(*UnresolvedName).TypeCheck
W220624 19:56:35.015463 19589 sql/show_create_clauses.go:164 ⋮ [n1,client=127.0.0.1:57011,user=root] 144 +  | 	github.com/cockroachdb/cockroach/pkg/sql/sem/tree/type_check.go:1373
W220624 19:56:35.015463 19589 sql/show_create_clauses.go:164 ⋮ [n1,client=127.0.0.1:57011,user=root] 144 +  | github.com/cockroachdb/cockroach/pkg/sql/sem/tree.typeCheckOverloadedExprs
W220624 19:56:35.015463 19589 sql/show_create_clauses.go:164 ⋮ [n1,client=127.0.0.1:57011,user=root] 144 +  | 	github.com/cockroachdb/cockroach/pkg/sql/sem/tree/overload.go:635
W220624 19:56:35.015463 19589 sql/show_create_clauses.go:164 ⋮ [n1,client=127.0.0.1:57011,user=root] 144 +  | github.com/cockroachdb/cockroach/pkg/sql/sem/tree.(*FuncExpr).TypeCheck
W220624 19:56:35.015463 19589 sql/show_create_clauses.go:164 ⋮ [n1,client=127.0.0.1:57011,user=root] 144 +  | 	github.com/cockroachdb/cockroach/pkg/sql/sem/tree/type_check.go:1038
W220624 19:56:35.015463 19589 sql/show_create_clauses.go:164 ⋮ [n1,client=127.0.0.1:57011,user=root] 144 +  | github.com/cockroachdb/cockroach/pkg/sql/sem/tree.typeCheckOverloadedExprs
W220624 19:56:35.015463 19589 sql/show_create_clauses.go:164 ⋮ [n1,client=127.0.0.1:57011,user=root] 144 +  | 	github.com/cockroachdb/cockroach/pkg/sql/sem/tree/overload.go:635
W220624 19:56:35.015463 19589 sql/show_create_clauses.go:164 ⋮ [n1,client=127.0.0.1:57011,user=root] 144 +  | github.com/cockroachdb/cockroach/pkg/sql/sem/tree.(*BinaryExpr).TypeCheck
W220624 19:56:35.015463 19589 sql/show_create_clauses.go:164 ⋮ [n1,client=127.0.0.1:57011,user=root] 144 +  | 	github.com/cockroachdb/cockroach/pkg/sql/sem/tree/type_check.go:310
W220624 19:56:35.015463 19589 sql/show_create_clauses.go:164 ⋮ [n1,client=127.0.0.1:57011,user=root] 144 +  | github.com/cockroachdb/cockroach/pkg/sql/sem/tree.(*ParenExpr).TypeCheck
W220624 19:56:35.015463 19589 sql/show_create_clauses.go:164 ⋮ [n1,client=127.0.0.1:57011,user=root] 144 +  | 	github.com/cockroachdb/cockroach/pkg/sql/sem/tree/type_check.go:1334
W220624 19:56:35.015463 19589 sql/show_create_clauses.go:164 ⋮ [n1,client=127.0.0.1:57011,user=root] 144 +  | github.com/cockroachdb/cockroach/pkg/sql/sem/tree.(*CastExpr).TypeCheck
W220624 19:56:35.015463 19589 sql/show_create_clauses.go:164 ⋮ [n1,client=127.0.0.1:57011,user=root] 144 +  | 	github.com/cockroachdb/cockroach/pkg/sql/sem/tree/type_check.go:572
W220624 19:56:35.015463 19589 sql/show_create_clauses.go:164 ⋮ [n1,client=127.0.0.1:57011,user=root] 144 +  | github.com/cockroachdb/cockroach/pkg/sql/sem/tree.TypeCheck
W220624 19:56:35.015463 19589 sql/show_create_clauses.go:164 ⋮ [n1,client=127.0.0.1:57011,user=root] 144 +  | 	github.com/cockroachdb/cockroach/pkg/sql/sem/tree/type_check.go:266
W220624 19:56:35.015463 19589 sql/show_create_clauses.go:164 ⋮ [n1,client=127.0.0.1:57011,user=root] 144 +  | github.com/cockroachdb/cockroach/pkg/sql.formatViewQueryTypesForDisplay.func1
W220624 19:56:35.015463 19589 sql/show_create_clauses.go:164 ⋮ [n1,client=127.0.0.1:57011,user=root] 144 +  | 	github.com/cockroachdb/cockroach/pkg/sql/show_create_clauses.go:218
W220624 19:56:35.015463 19589 sql/show_create_clauses.go:164 ⋮ [n1,client=127.0.0.1:57011,user=root] 144 +  | github.com/cockroachdb/cockroach/pkg/sql/sem/tree.(*simpleVisitor).VisitPre
W220624 19:56:35.015463 19589 sql/show_create_clauses.go:164 ⋮ [n1,client=127.0.0.1:57011,user=root] 144 +  | 	github.com/cockroachdb/cockroach/pkg/sql/sem/tree/walk.go:1710
W220624 19:56:35.015463 19589 sql/show_create_clauses.go:164 ⋮ [n1,client=127.0.0.1:57011,user=root] 144 +  | github.com/cockroachdb/cockroach/pkg/sql/sem/tree.WalkExpr
W220624 19:56:35.015463 19589 sql/show_create_clauses.go:164 ⋮ [n1,client=127.0.0.1:57011,user=root] 144 +  | 	github.com/cockroachdb/cockroach/pkg/sql/sem/tree/walk.go:824
W220624 19:56:35.015463 19589 sql/show_create_clauses.go:164 ⋮ [n1,client=127.0.0.1:57011,user=root] 144 +  | github.com/cockroachdb/cockroach/pkg/sql/sem/tree.(*BinaryExpr).Walk
W220624 19:56:35.015463 19589 sql/show_create_clauses.go:164 ⋮ [n1,client=127.0.0.1:57011,user=root] 144 +  | 	github.com/cockroachdb/cockroach/pkg/sql/sem/tree/walk.go:68
W220624 19:56:35.015463 19589 sql/show_create_clauses.go:164 ⋮ [n1,client=127.0.0.1:57011,user=root] 144 +  | github.com/cockroachdb/cockroach/pkg/sql/sem/tree.WalkExpr
W220624 19:56:35.015463 19589 sql/show_create_clauses.go:164 ⋮ [n1,client=127.0.0.1:57011,user=root] 144 +  | 	github.com/cockroachdb/cockroach/pkg/sql/sem/tree/walk.go:827
W220624 19:56:35.015463 19589 sql/show_create_clauses.go:164 ⋮ [n1,client=127.0.0.1:57011,user=root] 144 +  | github.com/cockroachdb/cockroach/pkg/sql/sem/tree.(*SelectClause).walkStmt
W220624 19:56:35.015463 19589 sql/show_create_clauses.go:164 ⋮ [n1,client=127.0.0.1:57011,user=root] 144 +  | 	github.com/cockroachdb/cockroach/pkg/sql/sem/tree/walk.go:1397
W220624 19:56:35.015463 19589 sql/show_create_clauses.go:164 ⋮ [n1,client=127.0.0.1:57011,user=root] 144 +  | github.com/cockroachdb/cockroach/pkg/sql/sem/tree.walkStmt
W220624 19:56:35.015463 19589 sql/show_create_clauses.go:164 ⋮ [n1,client=127.0.0.1:57011,user=root] 144 +  | 	github.com/cockroachdb/cockroach/pkg/sql/sem/tree/walk.go:1695
W220624 19:56:35.015463 19589 sql/show_create_clauses.go:164 ⋮ [n1,client=127.0.0.1:57011,user=root] 144 +  | github.com/cockroachdb/cockroach/pkg/sql/sem/tree.(*Select).walkStmt
W220624 19:56:35.015463 19589 sql/show_create_clauses.go:164 ⋮ [n1,client=127.0.0.1:57011,user=root] 144 +  | 	github.com/cockroachdb/cockroach/pkg/sql/sem/tree/walk.go:1321
W220624 19:56:35.015463 19589 sql/show_create_clauses.go:164 ⋮ [n1,client=127.0.0.1:57011,user=root] 144 +  | github.com/cockroachdb/cockroach/pkg/sql/sem/tree.walkStmt
W220624 19:56:35.015463 19589 sql/show_create_clauses.go:164 ⋮ [n1,client=127.0.0.1:57011,user=root] 144 +  | 	github.com/cockroachdb/cockroach/pkg/sql/sem/tree/walk.go:1695
W220624 19:56:35.015463 19589 sql/show_create_clauses.go:164 ⋮ [n1,client=127.0.0.1:57011,user=root] 144 +  | github.com/cockroachdb/cockroach/pkg/sql/sem/tree.SimpleStmtVisit
W220624 19:56:35.015463 19589 sql/show_create_clauses.go:164 ⋮ [n1,client=127.0.0.1:57011,user=root] 144 +  | 	github.com/cockroachdb/cockroach/pkg/sql/sem/tree/walk.go:1742
W220624 19:56:35.015463 19589 sql/show_create_clauses.go:164 ⋮ [n1,client=127.0.0.1:57011,user=root] 144 +  | github.com/cockroachdb/cockroach/pkg/sql.formatViewQueryTypesForDisplay
W220624 19:56:35.015463 19589 sql/show_create_clauses.go:164 ⋮ [n1,client=127.0.0.1:57011,user=root] 144 +  | 	github.com/cockroachdb/cockroach/pkg/sql/show_create_clauses.go:248
W220624 19:56:35.015463 19589 sql/show_create_clauses.go:164 ⋮ [n1,client=127.0.0.1:57011,user=root] 144 +  | github.com/cockroachdb/cockroach/pkg/sql.formatViewQueryForDisplay
W220624 19:56:35.015463 19589 sql/show_create_clauses.go:164 ⋮ [n1,client=127.0.0.1:57011,user=root] 144 +  | 	github.com/cockroachdb/cockroach/pkg/sql/show_create_clauses.go:162
W220624 19:56:35.015463 19589 sql/show_create_clauses.go:164 ⋮ [n1,client=127.0.0.1:57011,user=root] 144 +  | github.com/cockroachdb/cockroach/pkg/sql.ShowCreateView
W220624 19:56:35.015463 19589 sql/show_create_clauses.go:164 ⋮ [n1,client=127.0.0.1:57011,user=root] 144 +  | 	github.com/cockroachdb/cockroach/pkg/sql/show_create_clauses.go:131
W220624 19:56:35.015463 19589 sql/show_create_clauses.go:164 ⋮ [n1,client=127.0.0.1:57011,user=root] 144 +  | github.com/cockroachdb/cockroach/pkg/sql.glob..func37
W220624 19:56:35.015463 19589 sql/show_create_clauses.go:164 ⋮ [n1,client=127.0.0.1:57011,user=root] 144 +  | 	github.com/cockroachdb/cockroach/pkg/sql/crdb_internal.go:2594
W220624 19:56:35.015463 19589 sql/show_create_clauses.go:164 ⋮ [n1,client=127.0.0.1:57011,user=root] 144 +  | github.com/cockroachdb/cockroach/pkg/sql.makeAllRelationsVirtualTableWithDescriptorIDIndex.func1.1
W220624 19:56:35.015463 19589 sql/show_create_clauses.go:164 ⋮ [n1,client=127.0.0.1:57011,user=root] 144 +  | 	github.com/cockroachdb/cockroach/pkg/sql/pg_catalog.go:1085
W220624 19:56:35.015463 19589 sql/show_create_clauses.go:164 ⋮ [n1,client=127.0.0.1:57011,user=root] 144 +  | github.com/cockroachdb/cockroach/pkg/sql.forEachTableDescWithTableLookupInternalFromDescriptors.func1
W220624 19:56:35.015463 19589 sql/show_create_clauses.go:164 ⋮ [n1,client=127.0.0.1:57011,user=root] 144 +  | 	github.com/cockroachdb/cockroach/pkg/sql/information_schema.go:2426
W220624 19:56:35.015463 19589 sql/show_create_clauses.go:164 ⋮ [n1,client=127.0.0.1:57011,user=root] 144 +  | github.com/cockroachdb/cockroach/pkg/sql.forEachTableDescWithTableLookupInternalFromDescriptors
W220624 19:56:35.015463 19589 sql/show_create_clauses.go:164 ⋮ [n1,client=127.0.0.1:57011,user=root] 144 +  | 	github.com/cockroachdb/cockroach/pkg/sql/information_schema.go:2436
W220624 19:56:35.015463 19589 sql/show_create_clauses.go:164 ⋮ [n1,client=127.0.0.1:57011,user=root] 144 +  | github.com/cockroachdb/cockroach/pkg/sql.forEachTableDescWithTableLookupInternal
W220624 19:56:35.015463 19589 sql/show_create_clauses.go:164 ⋮ [n1,client=127.0.0.1:57011,user=root] 144 +  | 	github.com/cockroachdb/cockroach/pkg/sql/information_schema.go:2364
W220624 19:56:35.015463 19589 sql/show_create_clauses.go:164 ⋮ [n1,client=127.0.0.1:57011,user=root] 144 +  | github.com/cockroachdb/cockroach/pkg/sql.forEachTableDescWithTableLookup
W220624 19:56:35.015463 19589 sql/show_create_clauses.go:164 ⋮ [n1,client=127.0.0.1:57011,user=root] 144 +  | 	github.com/cockroachdb/cockroach/pkg/sql/information_schema.go:2314
W220624 19:56:35.015463 19589 sql/show_create_clauses.go:164 ⋮ [n1,client=127.0.0.1:57011,user=root] 144 +  | github.com/cockroachdb/cockroach/pkg/sql.makeAllRelationsVirtualTableWithDescriptorIDIndex.func1
W220624 19:56:35.015463 19589 sql/show_create_clauses.go:164 ⋮ [n1,client=127.0.0.1:57011,user=root] 144 +  | 	github.com/cockroachdb/cockroach/pkg/sql/pg_catalog.go:1083
W220624 19:56:35.015463 19589 sql/show_create_clauses.go:164 ⋮ [n1,client=127.0.0.1:57011,user=root] 144 +  | github.com/cockroachdb/cockroach/pkg/sql.(*virtualDefEntry).getPlanInfo.func1.1
W220624 19:56:35.015463 19589 sql/show_create_clauses.go:164 ⋮ [n1,client=127.0.0.1:57011,user=root] 144 +  | 	github.com/cockroachdb/cockroach/pkg/sql/virtual_schema.go:573
W220624 19:56:35.015463 19589 sql/show_create_clauses.go:164 ⋮ [n1,client=127.0.0.1:57011,user=root] 144 +  | github.com/cockroachdb/cockroach/pkg/sql.setupGenerator.func3
W220624 19:56:35.015463 19589 sql/show_create_clauses.go:164 ⋮ [n1,client=127.0.0.1:57011,user=root] 144 +  | 	github.com/cockroachdb/cockroach/pkg/sql/virtual_table.go:127
W220624 19:56:35.015463 19589 sql/show_create_clauses.go:164 ⋮ [n1,client=127.0.0.1:57011,user=root] 144 +  | github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunAsyncTaskEx.func2
W220624 19:56:35.015463 19589 sql/show_create_clauses.go:164 ⋮ [n1,client=127.0.0.1:57011,user=root] 144 +  | 	github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:494
W220624 19:56:35.015463 19589 sql/show_create_clauses.go:164 ⋮ [n1,client=127.0.0.1:57011,user=root] 144 +Wraps: (6) column ‹"start_key"› does not exist
W220624 19:56:35.015463 19589 sql/show_create_clauses.go:164 ⋮ [n1,client=127.0.0.1:57011,user=root] 144 +Error types: (1) *pgerror.withCandidateCode (2) *withstack.withStack (3) *errutil.withPrefix (4) *pgerror.withCandidateCode (5) *withstack.withStack (6) *errutil.leafError
```

**To Reproduce**

`select * from crdb_internal.create_statements;` and look in the logs.

**Expected behavior**
No warnings.

### PR DESCRIPTION
**Pull request by rafiss**
fixes https://github.com/cockroachdb/cockroach/issues/83351

Since the fix in https://github.com/cockroachdb/cockroach/pull/82763,
the error that was previously ignored started showing up in logs.

This fix updates the visit function used by
crdb_internal.create_statements so it doesn't result in errors.

Release note: None

### CODE REVIEW

File: pkg/sql/show_create_clauses.go [hunk 1]
```diff
@@ -213,30 +213,41 @@ func formatViewQueryTypesForDisplay(
 	desc catalog.TableDescriptor,
 ) (string, error) {
 	replaceFunc := func(expr tree.Expr) (recurse bool, newExpr tree.Expr, err error) {
+		var innerExpr tree.Expr
```
Comment (ajwerner) [inline pkg/sql/show_create_clauses.go:216]: How do you feel about adding a little commentary that this dance is about resolving UDTs used in these types of expressions so that logical values and type names are formatted properly for display and that non-UDT types don't require any extra work?

**Review by ajwerner — APPROVED** [review]
Any interest in adding a test by taking the synthetic descriptor we were having trouble with and running it through the `SHOW CREATE` code?

Code itself LGTM

File: pkg/sql/show_create_clauses.go (hunk 1 above)
Comment (rafiss) [reply pkg/sql/show_create_clauses.go]: added

**Comment by rafiss** [comment]
tftr!  

bors r=ajwerner
