### PR TITLE
cli: avoid creating thousands of sstables for debug commands

### LINKED ISSUE #4493: storage/engine: rocksdb runs out of file descriptors
After running a cluster for a while and trying to print the keys using the command `./cockroach debug keys /tmp/data1`, I was presented with the following error:

```
Error: storage/engine/rocksdb.go:117: could not open rocksdb instance: IO error: /tmp/data1/000309.sst: Too many open files
```

The dump ran fine when I cleared the store, ran the cluster for less time, and ran the command again.

### PR DESCRIPTION
**Pull request by petermattis**
Pass a non-zero memtable-budget when opening a RocksDB instance. When
RocksDB opens it scans the wal loading entries into the memtable. By
setting a memtable-budget of zero we were causing these entries to
immediately be flushed. If there were thousands of entries in your wal
you would create thousands of sstables. This affected the `debug
{keys,raft-log,range-descriptors}` commands.

Fixes #4493.

---

This change is [Review on Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/5098)

### CODE REVIEW

**Comment by BramGruneir** [comment]
LGTM

File: cli/debug.go [hunk 1]
```diff
@@ -56,6 +57,8 @@ func printKey(kv engine.MVCCKeyValue) (bool, error) {
 }
 
 func runDebugKeys(cmd *cobra.Command, args []string) error {
+	initCacheSize()
```
Comment (bdarnell) [inline cli/debug.go]: Why does `runDebugKeys` do this but the other commands don't? It seems like it would be better for `openStore` to ensure that the flags have been set.

**Comment by bdarnell** [comment]
LGTM. Should `NewRocksDB` panic when given a zero `MemtableBudget`?
