### PR TITLE
sql,opt: re-enable 1pc for small delRange ops

### LINKED ISSUE #41320: sql: allow deleteRangeNode to autoCommit transactions
`deleteRangeNode` currently has the following restriction:
https://github.com/cockroachdb/cockroach/blob/445ec411db8cde8cc090c7ffcd7ac70be9b21954/pkg/sql/delete_range.go#L29-L31

This has huge performance implications, as it means that no point `DELETE` statement can run as a 1PC transaction. This results in roughly a 50% performance hit for delete-heavy workloads on tables without secondary indexes.

The comment says that we delete in batches and we won't know whether or not there is more work to do until after a batch is returned. I don't fully understand this. If the comment is talking about `b.Header.MaxSpanRequestKeys = TableTruncateChunkSize` then I don't think this needs to preclude attempting a 1PC transaction. I _think_ the kv implementation is smart enough to handle 1PC transactions with key limits. If it's not, we should make it work to support this case.

For context, we have heard in the past from people running Cockroach that deletes are slower than inserts, which has never made sense to me. This explains why this is the case. Sysbench adds more weight to this claim. `oltp_delete` without a secondary index is the only sysbench workload that we are slower on than similarly architected databases. If we could run point `DELETE` statements as 1PC transactions then we would immediately close this gap.

@jordanlewis I noticed that some of this changed in https://github.com/cockroachdb/cockroach/pull/36728. Do you have context on this? Did that cause a regression in this behavior?

### PR DESCRIPTION
**Pull request by jordanlewis**
This commit tells the optimizer to enable autoCommit on delRange
operations if it can prove that the number of returned keys is low
enough.

Closes #41320.

Release justification: high-priority fix to performance regression
Release note: None

### CODE REVIEW

File: pkg/sql/opt/exec/execbuilder/mutation.go [hunk 1]
```diff
@@ -331,8 +331,15 @@ func (b *Builder) buildDeleteRange(del *memo.DeleteExpr) (execPlan, error) {
 	scan := del.Input.(*memo.ScanExpr)
 	tab := b.mem.Metadata().Table(scan.Table)
 	needed, _ := b.getColumns(scan.Cols, scan.Table)
+	var indexCols opt.ColSet
+	numCols := scan.Constraint.Columns.Count()
+	for i := 0; i < numCols; i++ {
+		indexCols.Add(scan.Constraint.Columns.Get(i).ID())
+	}
+	maxKeys := int(scan.Constraint.CalculateMaxResults(
```
Comment (jordanlewis) [inline pkg/sql/opt/exec/execbuilder/mutation.go]: This section doesn't really work right - I'm not quite sure how to construct the proper parameters to `CalculateMaxResults` here. @RaduBerinde could you please advise?

**Comment by jordanlewis** [comment]
RFAL

**Review by nvb — APPROVED** [review]
:lgtm: thanks @jordanlewis!

@raduberinde should also sign off on the optimizer portion though.

> Reviewed 3 of 6 files at r1, 2 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/41324#-:-LqSZsBD9VyeUYX_tLyo:b-ddvixb)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @jordanlewis, @nvanbenschoten, and @RaduBerinde)

___
*[pkg/sql/delete_range.go, line 30 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/41324#-LqSZBva9J5wWr4O_IJ7:-LqSZBva9J5wWr4O_IJ8:b-e46s4k) ([raw file](https://github.com/cockroachdb/cockroach/blob/3767d50fa793cf9cafd7ab4eb7dcf28e8e424f65/pkg/sql/delete_range.go#L30)):*
> ```Go
> // instead of many point deletes.
> //
> // Note: deleteRangeNode can't autocommit, because it has to delete in batches,
> ```

You can delete this comment now.
___
*[pkg/sql/opt/exec/execbuilder/testdata/delete_range, line 16 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/41324#-LqSZk2k0U9TlIeKWmUI:-LqSZk2k0U9TlIeKWmUJ:baxdacl) ([raw file](https://github.com/cockroachdb/cockroach/blob/3767d50fa793cf9cafd7ab4eb7dcf28e8e424f65/pkg/sql/opt/exec/execbuilder/testdata/delete_range#L16)):*
> ```
> query TT
> SELECT operation, message FROM [SHOW KV TRACE FOR SESSION]
> WHERE message LIKE '%DelRange%'
> ```

Can you also test against the batches sent? ` OR message LIKE '%sending batch%'`

**Review by jordanlewis — COMMENTED** [review]
Done, TFTRs

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/41324#-:-LqcMyzu7Jmuv2ZnH5xN:bexegp4)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @nvanbenschoten and @RaduBerinde)
