### PR TITLE
kvserver: fix a span-use-after-Finish in closedts nudging 

### LINKED ISSUE #74012: server: TestHealthAPI failed
server.TestHealthAPI [failed](https://teamcity.cockroachdb.com/viewLog.html?buildId=3946704&tab=buildLog) with [artifacts](https://teamcity.cockroachdb.com/viewLog.html?buildId=3946704&tab=artifacts#/) on master @ [3f95a4bd83cce2952a12497de82692866b4da659](https://github.com/cockroachdb/cockroach/commits/3f95a4bd83cce2952a12497de82692866b4da659):

```
=== RUN   TestHealthAPI
    test_log_scope.go:79: test logs captured to: /artifacts/tmp/_tmp/ab5462d2cb3989e2a33018db970f23de/logTestHealthAPI2335388422
    test_log_scope.go:80: use -show-logs to present logs inline
    admin_test.go:1407: observed error: status: 503 Service Unavailable, content-type: application/json, body: {
          "error": "node is not healthy",
          "code": 14,
          "message": "node is not healthy",
          "details": [
          ]
        }, error: <nil>
```
<details><summary>Help</summary>
<p>
See also: [How To Investigate a Go Test Failure \(internal\)](https://cockroachlabs.atlassian.net/l/c/HgfXfJgM)Parameters in this failure:

- TAGS=bazel,gss
</p>
</details>
/cc @cockroachdb/server
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*TestHealthAPI.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)
</sub>

### PR DESCRIPTION
**Pull request by andreimatei**
The process of "nudging" a replica to close a timestamp was spawning an
async task without waiting for it to finish. The task was capturing the
caller's ctx, and using its span. That span might Finish()
asynchronously, leading to use-after-Finish().
This patch fixes the bug by creating a dedicated span for the task.

Fixes #74012

Release note: None

### CODE REVIEW

File: pkg/kv/kvserver/replica_rangefeed.go [hunk 1]
```diff
@@ -656,10 +657,12 @@ func (r *Replica) handleClosedTimestampUpdateRaftMuLocked(
 		// Ignore the result of DoChan since, to keep this all async, it always
 		// returns nil and any errors are logged by the closure passed to the
 		// `DoChan` call.
-		_, _ = m.RangeFeedSlowClosedTimestampNudge.DoChan(key, func() (interface{}, error) {
+		taskCtx, sp := tracing.EnsureForkSpan(ctx, r.AmbientContext.Tracer, key)
```
Comment (tbg) [inline pkg/kv/kvserver/replica_rangefeed.go:660]: Would it be marginally better to make the forked span inside of the task? (So that non-leaders don't make an extra span)? Or is that not possible because of use-after-finish?

**Review by tbg — APPROVED** [review]

**Review by erikgrinaker — APPROVED** [review]
>kvserver: make a long-running's taks sterile 

s/taks/task

**Review by andreimatei — COMMENTED** [review]
> s/taks/task

done


TFTRs!

bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/74099#-:-MrShib72jOI1SBuToDv:b-bhf04f)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @tbg)

___
*[pkg/kv/kvserver/replica_rangefeed.go, line 660 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/74099#-MrOYjmcbSg3IjTStcwc-r2-660:-MrSh1m37qh8WWzjPAl7:bk6i3yb) ([raw file](https://github.com/cockroachdb/cockroach/blob/63864541db6b2f818ccee2ee755226f31a40ab2a/pkg/kv/kvserver/replica_rangefeed.go#L660)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

Would it be marginally better to make the forked span inside of the task? (So that non-leaders don't make an extra span)? Or is that not possible because of use-after-finish?
</blockquote></details>

Right - it's not possible without cooperation from the `singleflight` library. By the time the closure is called, it's too late.
