### PR TITLE
streamingest: c2c UX fixes

### LINKED ISSUE #94706: c2c: print the cutover timestamp on cutover, avoid printing job ids
users working with c2c SQL commands should not see job ids, remove those from create/alter/etc.

when cutting over, print the cutover timestamp (that is sometimes picked by LATEST).

### PR DESCRIPTION
**Pull request by lidorcarmel**
CREATE TENANT FROM REPLICATION: currently has an output (the job ids of the producer and consumer). This PR removes the output.

ALTER TENANT PAUSE/RESUME: currently prints the job id, and this PR removes the output.

ALTER TENANT COMPLETE: currently prints the job id. This PR changes the output to be the cutover timestamp. The rational is that the user may not know the cutover time because LATEST or NOW() etc. was used.

Fixes: #94706

Epic: CRDB-18752

Release note: None

### CODE REVIEW

File: pkg/ccl/streamingccl/streamingest/alter_replication_job.go [hunk 1]
```diff
@@ -25,13 +26,14 @@ import (
...
+	"github.com/cockroachdb/cockroach/pkg/util/timeutil"
 	"github.com/cockroachdb/errors"
 )
 
 const alterReplicationJobOp = "ALTER TENANT REPLICATION"
 
-var alterReplicationJobHeader = colinfo.ResultColumns{
-	{Name: "replication_job_id", Typ: types.Int},
+var alterReplicationCutoverHeader = colinfo.ResultColumns{
+	{Name: "cutover_time", Typ: types.TimestampTZ},
```
Comment (stevendanna) [inline pkg/ccl/streamingccl/streamingest/alter_replication_job.go:36]: I think we lose precision here if we had a logical component to the cutover timestamp.

Comment (lidorcarmel) [reply pkg/ccl/streamingccl/streamingest/alter_replication_job.go:36]: interesting, thanks. I did not think about that.. we're also losing nanos when cutting over to a time from SHOW. I might nag you tomorrow about this if I don't have a better way.

Comment (lidorcarmel) [reply pkg/ccl/streamingccl/streamingest/alter_replication_job.go:36]: I guess we have at least a couple of options:
1. print a not-so-pretty hlc such as this:

```
root@127.0.0.1:26257/defaultdb> SELECT cluster_logical_timestamp();

    cluster_logical_timestamp
----------------------------------
  1671493837007535000.0000000000
(1 row)
```
2. print a less accurate timestamp (current pr) without logical and without nanos:
```
root@127.0.0.1:26257/defaultdb> alter tenant dest5 complete replication to latest;

          cutover_time
---------------------------------
  2022-12-06 00:25:02.098763+00
(1 row)
```
similar to:
```
root@127.0.0.1:26257/defaultdb> SELECT hlc_to_timestamp(cluster_logical_timestamp());

        hlc_to_timestamp
---------------------------------
  2022-12-19 23:50:55.100638+00
(1 row)
```

I was thinking that we need something that users can understand and not hlc.

in which scenarios are we going to have issues because of accuracy?

Comment (stevendanna) [reply pkg/ccl/streamingccl/streamingest/alter_replication_job.go:35]: > in which scenarios are we going to have issues because of accuracy?

I think the main use of this time in a context where the accuracy may matter is if you are using it to do comparisons using AOST queries or crdb_internal.fingeprint or similar.  In that context, the loss of accuracy is likely OK provided that the timestamp printed is inside the GC window on both sides and if we are inaccurate in the correct direction.

Comment (lidorcarmel) [reply pkg/ccl/streamingccl/streamingest/alter_replication_job.go]: updated, PTAL.
pretty time for replication and retained times, hlc for cutover.

**Review by stevendanna — APPROVED** [review]
This seems reasonable to me. Thanks for digging into it.

**Comment by lidorcarmel** [comment]
TFTR!!
bors r+
