### PR TITLE
catalog/lease: avoid panics on failed graceful shutdown

### LINKED ISSUE #163561: roachtest: c2c/mixed-version failed
**Note:** This build has runtime assertions enabled. If the same failure was hit in a run without assertions enabled, there should be a similar failure without this message. If there isn&#39;t one, then this failure is likely due to an assertion violation or (assertion) timeout.

roachtest.c2c/mixed-version [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/21109736?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/21109736?buildTab=artifacts#/c2c/mixed-version) on release-26.1.0-rc @ [3b61854ae28ed972d6f26a2b72f24bf8fb513e42](https://github.com/cockroachdb/cockroach/commits/3b61854ae28ed972d6f26a2b72f24bf8fb513e42):

Failed with:

```
(test_monitor.go:35).func1: test monitor: unexpected node event: n8: cockroach process for system interface died (exit code 134)
(mixedversion.go:893).Run: source: context canceled
(mixedversion.go:893).Run: dest: context canceled while waiting for job to reach state running: context canceled
test artifacts and logs in: /artifacts/c2c/mixed-version/run_1
```
Cluster Node to Ip Mapping:
| Node | Public IP | Private IP |
| --- | --- | --- |
| teamcity-21109736-1771227205-29-n9cpu8-0001 | 35.243.157.232 | 10.142.3.21 |
| teamcity-21109736-1771227205-29-n9cpu8-0002 | 35.237.176.132 | 10.142.2.119 |
| teamcity-21109736-1771227205-29-n9cpu8-0003 | 35.196.251.103 | 10.142.2.136 |
| teamcity-21109736-1771227205-29-n9cpu8-0004 | 35.237.101.176 | 10.142.2.135 |
| teamcity-21109736-1771227205-29-n9cpu8-0005 | 34.73.13.131 | 10.142.2.140 |
| teamcity-21109736-1771227205-29-n9cpu8-0006 | 34.26.44.214 | 10.142.3.23 |
| teamcity-21109736-1771227205-29-n9cpu8-0007 | 34.23.240.86 | 10.142.3.22 |
| teamcity-21109736-1771227205-29-n9cpu8-0008 | 34.26.138.39 | 10.142.2.134 |
| teamcity-21109736-1771227205-29-n9cpu8-0009 | 34.75.1.76 | 10.142.3.34 |

Parameters:
 - <code>arch=amd64</code>
 - <code>cloud=gce</code>
 - <code>coverageBuild=false</code>
 - <code>cpu=8</code>
 - <code>diskCount=0</code>
 - <code>encrypted=false</code>
 - <code>fs=ext4</code>
 - <code>localSSD=true</code>
 - <code>mvtDeploymentMode=system-only</code>
 - <code>mvtVersions=v25.4.3 → v26.1.0-dev-3b61854ae28ed972d6f26a2b72f24bf8fb513e42 (release-26.1.0-rc)</code>
 - <code>runtimeAssertionsBuild=true</code>
<details><summary>Help</summary>
<p>

See: [roachtest README](https://github.com/cockroachdb/cockroach/blob/master/pkg/cmd/roachtest/README.md)

See: [How To Investigate \(internal\)](https://cockroachlabs.atlassian.net/l/c/SSSBr8c7)

See: [Grafana](https://go.crdb.dev/roachtest-grafana/teamcity-21109736/c2c-mixed-version/1771230672853/1771231373997)

</p>
</details>
<details><summary>Same failure on other branches</summary>
<p>

- #161569 roachtest: c2c/mixed-version failed [A-disaster-recovery B-runtime-assertions-enabled C-test-failure O-roachtest O-robot P-3 T-disaster-recovery branch-release-24.3.25-rc]
- #155754 roachtest: c2c/mixed-version failed [A-disaster-recovery B-runtime-assertions-enabled C-test-failure O-roachtest O-robot P-3 T-disaster-recovery branch-release-25.2]
</p>
</details>
/cc @cockroachdb/disaster-recovery
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*c2c/mixed-version.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/bazci/githubpost/issues)

</sub>

Jira issue: CRDB-60290

### PR DESCRIPTION
**Pull request by fqazi**
Previously, the closer used for the memory monitors in the lease manager unconditionally used the Stop method. This caused the bound account to be cleared. If we failed to stop other goroutines then queries executing still panic while releasing leases. To address this, this patch opts for a graceful shutdown if the bound account is empty. Otherwise, it uses an emergency stop only on the BytesMonitor, which allows memory to be freed but not allocated.

Fixes: #163561

Release note: None

### CODE REVIEW

**Review by spilchen — COMMENTED** [review]
Looks good. I just had one question.

> @spilchen reviewed 1 file and made 2 comments.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/163972#-:-OlwhWJC-GNxV3loJc_7:b-uvtebo)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on fqazi).

___
*[`pkg/sql/catalog/lease/lease.go` line 1985 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/163972#-OlwfOfECKkUbWebt6TY:-OlwfOfECKkUbWebt6TZ:bxr7yx7) ([raw file](https://github.com/cockroachdb/cockroach/blob/3d7c1efefaa32a7e8580b27179cbe51a4a8e9430/pkg/sql/catalog/lease/lease.go#L1985)):*
> ```Go
> 		// panics in other code paths.
> 		if lm.boundAccount.Used() > 0 {
> 			lm.bytesMonitor.EmergencyStop(ctx)
> ```

I see a lot of uses cases of EmergencyStop() do so if we are already panic'ing. Is that true for the case in the issue? If so, would it be better to have called `recover()` instead of the Used() byte count.

File: pkg/sql/catalog/lease/lease_test.go [hunk 1]
```diff
@@ -4385,3 +4387,92 @@ func TestLeasedDescriptorTypeHydration(t *testing.T) {
...
+
+	// Acquire a lease and confirm the memory usage has gone up.
+	l, err := lm.Acquire(ctx, lease.TimestampToReadTimestamp(app.Clock().Now()), tableID)
+	require.NoError(t, err)
+	lastMemoryUsage := monitor.AllocBytes()
+	require.Greater(t, lastMemoryUsage, int64(0))
+	// After stopping allocations should be blocked.
+	stopper.Stop(ctx)
+	err = lm.TestingGetBoundAccount().Grow(ctx, 1204)
+	require.ErrorContains(t, err, "memory budget exceeded:", "allocations should blocked")
```
Comment (rafiss) [inline pkg/sql/catalog/lease/lease_test.go]: nit: "should be"

File: pkg/sql/catalog/lease/lease.go [hunk 2]
```diff
@@ -1957,19 +1957,34 @@ func NewLeaseManager(
...
 	lm.boundAccount = lm.bytesMonitor.MakeConcurrentBoundAccount()
 	// Add a stopper for the bound account that we are using to
 	// track memory usage.
 	lm.stopper.AddCloser(stop.CloserFn(func() {
+		// If there are outstanding leases, we cannot close the account and
+		// properly stop it. This can happen if draining failed for some reason.
+		// The safest option is to emergency-stop the monitor, which prevents
+		// panics in other code paths.
+		if lm.boundAccount.Used() > 0 {
+			lm.bytesMonitor.EmergencyStop(ctx)
```
Comment (rafiss) [inline pkg/sql/catalog/lease/lease.go]: is there an issue with re-using the `ctx` here? it might already be cancelled

it looks like some other `Closer`s use context.Background()

File: pkg/sql/catalog/lease/lease.go [hunk 3]
```diff
@@ -1957,19 +1957,34 @@ func NewLeaseManager(
 	lm.descDelCh = make(chan descpb.ID)
 	lm.descMetaDataUpdateCh = make(chan *descriptorTxnUpdate)
 	lm.rangefeedErrCh = make(chan error)
+	// Allow the bytes monitor to allocate extra memory
+	// with smaller allocations (default).
+	bytesMonitorIncrement := int64(0)
```
Comment (rafiss) [inline pkg/sql/catalog/lease/lease.go:1963]: i wasn't familiar with the Increment setting, so i asked claude to help write a comment. does this make sense?
```
  // Set the pool allocation block size for the bytes monitor. By default
  // (Increment=0), the monitor uses DefaultPoolAllocationSize. Setting
  // Increment to 1 disables allocation buffering for exact accounting in tests.
```

Comment (fqazi) [reply pkg/sql/catalog/lease/lease.go:1963]: Yes, and I updated the description.

File: pkg/sql/catalog/lease/lease.go (hunk 2 above)
Comment (fqazi) [reply pkg/sql/catalog/lease/lease.go]: Done.

Good catch, yes Background is much safer here.

**Review by fqazi — COMMENTED** [review]
> @fqazi made 3 comments and resolved 1 discussion.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/163972)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on rafiss and spilchen).

___
*[`pkg/sql/catalog/lease/lease.go` line 1985 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/163972#-OlwfOfECKkUbWebt6TY:-Om9yinMBrN3luxG3Kdx:bk2qjo8) ([raw file](https://github.com/cockroachdb/cockroach/blob/3d7c1efefaa32a7e8580b27179cbe51a4a8e9430/pkg/sql/catalog/lease/lease.go#L1985)):*
<details><summary><i>Previously, spilchen wrote…</i></summary><blockquote>

I see a lot of uses cases of EmergencyStop() do so if we are already panic'ing. Is that true for the case in the issue? If so, would it be better to have called `recover()` instead of the Used() byte count.
</blockquote></details>

Sadly, we failed to drain the client connections because an unrelated error was hit in that code path. So, we have no way of knowing it failed. Also, I think that path also has a timeout, so the risk is always there.

**Review by rafiss — APPROVED** [review]
:lgtm:

> @rafiss made 1 comment.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/163972#-:-OmALld-38iqAKp-Vn_z:bnfp4nl)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on spilchen).
