### PR TITLE
streamingccl: prevent node lag replanning starvation

### LINKED ISSUE #114341: roachtest: c2c/BulkOps/full failed
roachtest.c2c/BulkOps/full [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/12647615?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/12647615?buildTab=artifacts#/c2c/BulkOps/full) on master @ [063fa2b8930019a16adc0bca5b8363d8e80f3132](https://github.com/cockroachdb/cockroach/commits/063fa2b8930019a16adc0bca5b8363d8e80f3132):

```
(assertions.go:333).Fail: 
	Error Trace:	github.com/cockroachdb/cockroach/pkg/cmd/roachtest/tests/cluster_to_cluster.go:750
	            				github.com/cockroachdb/cockroach/pkg/cmd/roachtest/tests/cluster_to_cluster.go:971
	            				github.com/cockroachdb/cockroach/pkg/cmd/roachtest/tests/cluster_to_cluster.go:1264
	            				main/pkg/cmd/roachtest/monitor.go:119
	            				golang.org/x/sync/errgroup/external/org_golang_x_sync/errgroup/errgroup.go:75
	            				src/runtime/asm_amd64.s:1650
	Error:      	Received unexpected error:
	            	expected job status succeeded, but got running
	            	(1) attached stack trace
	            	  -- stack trace:
	            	  | github.com/cockroachdb/cockroach/pkg/cmd/roachtest/tests.(*replicationDriver).stopReplicationStream.func1
	            	  | 	github.com/cockroachdb/cockroach/pkg/cmd/roachtest/tests/cluster_to_cluster.go:746
	            	  | github.com/cockroachdb/cockroach/pkg/util/retry.ForDuration
	            	  | 	github.com/cockroachdb/cockroach/pkg/util/retry/retry.go:213
	            	  | github.com/cockroachdb/cockroach/pkg/cmd/roachtest/tests.(*replicationDriver).stopReplicationStream
	            	  | 	github.com/cockroachdb/cockroach/pkg/cmd/roachtest/tests/cluster_to_cluster.go:728
	            	  | github.com/cockroachdb/cockroach/pkg/cmd/roachtest/tests.(*replicationDriver).main
	            	  | 	github.com/cockroachdb/cockroach/pkg/cmd/roachtest/tests/cluster_to_cluster.go:971
	            	  | github.com/cockroachdb/cockroach/pkg/cmd/roachtest/tests.registerClusterToCluster.func1.1
	            	  | 	github.com/cockroachdb/cockroach/pkg/cmd/roachtest/tests/cluster_to_cluster.go:1264
	            	  | main.(*monitorImpl).Go.func1
	            	  | 	main/pkg/cmd/roachtest/monitor.go:119
	            	  | golang.org/x/sync/errgroup.(*Group).Go.func1
	            	  | 	golang.org/x/sync/errgroup/external/org_golang_x_sync/errgroup/errgroup.go:75
	            	  | runtime.goexit
	            	  | 	src/runtime/asm_amd64.s:1650
	            	Wraps: (2) expected job status succeeded, but got running
	            	Error types: (1) *withstack.withStack (2) *errutil.leafError
	Test:       	c2c/BulkOps/full
(require.go:1360).NoError: FailNow called
(monitor.go:153).Wait: monitor failure: monitor user task failed: t.Fatal() was called
test artifacts and logs in: /artifacts/c2c/BulkOps/full/run_1
```
<p>Parameters: <code>ROACHTEST_arch=amd64</code>
, <code>ROACHTEST_cloud=gce</code>
, <code>ROACHTEST_cpu=8</code>
, <code>ROACHTEST_encrypted=false</code>
, <code>ROACHTEST_fs=ext4</code>
, <code>ROACHTEST_localSSD=false</code>
, <code>ROACHTEST_metamorphicBuild=true</code>
, <code>ROACHTEST_ssd=0</code>
</p>
<details><summary>Help</summary>
<p>

See: [roachtest README](https://github.com/cockroachdb/cockroach/blob/master/pkg/cmd/roachtest/README.md)

See: [How To Investigate \(internal\)](https://cockroachlabs.atlassian.net/l/c/SSSBr8c7)

See: [Grafana](https://go.crdb.dev/roachtest-grafana/teamcity-12647615/c2c-bulkops-full/1699871639416/1699874926034)

</p>
</details>
/cc @cockroachdb/disaster-recovery
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*c2c/BulkOps/full.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)
</sub>

Jira issue: CRDB-33470

### PR DESCRIPTION
**Pull request by msbutler**
This patch prevents the lastNodeLagCheck time from updating every time the frontier processor receives a checkpoint, which can happen every few seconds. This previously prevented the node lag replanning check to trigger because this time needed to be older than 10 minutes. Rather, this timestamp should only update if we actually compute the lag check.

Fixes #114341

Release note: none

### CODE REVIEW

File: pkg/ccl/streamingccl/streamingest/stream_ingestion_frontier_processor.go [hunk 1]
```diff
@@ -535,26 +535,27 @@ func (sf *streamIngestionFrontier) maybePersistFrontierEntries() error {
 }
 
 func (sf *streamIngestionFrontier) maybeCheckForLaggingNodes() error {
-	defer func() {
-		sf.lastNodeLagCheck = timeutil.Now()
-	}()
+	ctx := sf.Ctx()
+	log.VEventf(ctx, 2, "consider lag replanning check")
```
Comment (stevendanna) [inline pkg/ccl/streamingccl/streamingest/stream_ingestion_frontier_processor.go:539]: I'd probably remove this one since you log before every return.

File: pkg/ccl/streamingccl/streamingest/stream_ingestion_frontier_processor.go [hunk 2]
```diff
@@ -535,26 +535,27 @@ func (sf *streamIngestionFrontier) maybePersistFrontierEntries() error {
...
 		log.VEventf(ctx, 2, "skipping lagging nodes check as hwm has yet to advance past %s", sf.replicatedTimeAtStart)
 		return nil
 	}
-
+	defer func() {
+		sf.lastNodeLagCheck = timeutil.Now()
+	}()
 	executionDetails := constructSpanFrontierExecutionDetailsWithFrontier(sf.spec.PartitionSpecs, sf.frontier)
-
+	log.VEvent(ctx, 2, "about to check for lagging nodes")
```
Comment (stevendanna) [inline pkg/ccl/streamingccl/streamingest/stream_ingestion_frontier_processor.go:556]: I'd probably change this one to "checking for lagging nodes"

File: pkg/ccl/streamingccl/streamingest/stream_ingestion_frontier_processor.go [hunk 3]
```diff
@@ -535,26 +535,27 @@ func (sf *streamIngestionFrontier) maybePersistFrontierEntries() error {
...
+		log.VEventf(ctx, 2, "skipping lag replanning check: maxLag %d; checkFreq %.2f; last node check %s; time since last check %.2f",
+			maxLag, checkFreq.Minutes(), sf.lastNodeLagCheck, timeutil.Since(sf.lastNodeLagCheck).Minutes())
 		return nil
 	}
-
-	ctx := sf.Ctx()
-
 	// Don't check for lagging nodes if the hwm has yet to advance.
 	if sf.replicatedTimeAtStart.Equal(sf.persistedReplicatedTime) {
 		log.VEventf(ctx, 2, "skipping lagging nodes check as hwm has yet to advance past %s", sf.replicatedTimeAtStart)
```
Comment (stevendanna) [inline pkg/ccl/streamingccl/streamingest/stream_ingestion_frontier_processor.go:549]: For consistency with the one above, perhaps "skipping lag replanning check: hwm has not advanced past %s"

**Review by stevendanna — APPROVED** [review]
Aha, thanks for looking into this. Left some nits about the logging.

File: pkg/ccl/streamingccl/streamingest/stream_ingestion_frontier_processor.go (hunk 1 above)
Comment (msbutler) [reply pkg/ccl/streamingccl/streamingest/stream_ingestion_frontier_processor.go]: Done.

File: pkg/ccl/streamingccl/streamingest/stream_ingestion_frontier_processor.go (hunk 2 above)
Comment (msbutler) [reply pkg/ccl/streamingccl/streamingest/stream_ingestion_frontier_processor.go]: Done.

File: pkg/ccl/streamingccl/streamingest/stream_ingestion_frontier_processor.go (hunk 3 above)
Comment (msbutler) [reply pkg/ccl/streamingccl/streamingest/stream_ingestion_frontier_processor.go]: Done.

**Comment by msbutler** [comment]
TFTR!

bors r=stevendanna
