### PR TITLE
tree: fix vectorized COALESCE and NULLIF type checking with VOID

### LINKED ISSUE #83754: sql: lookup for ComparisonExpr ((column1)[void] IS DISTINCT FROM (NULL)[unknown])[bool]'s CmpOp failed
roachtest.sqlsmith/setup=empty/setting=no-mutations [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/5633774?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/5633774?buildTab=artifacts#/sqlsmith/setup=empty/setting=no-mutations) on master @ [3c9b17113488d2ee6929936aa6ec48396f3ed71c](https://github.com/cockroachdb/cockroach/commits/3c9b17113488d2ee6929936aa6ec48396f3ed71c):

```
test artifacts and logs in: /artifacts/sqlsmith/setup=empty/setting=no-mutations/run_1
	sqlsmith.go:265,sqlsmith.go:325,test_runner.go:896: error: pq: internal error: lookup for ComparisonExpr ((column1)[void] IS DISTINCT FROM (NULL)[unknown])[bool]'s CmpOp failed
		stmt:
		SELECT
			COALESCE(tab_115318.col_199168, NULL) AS col_199169
		FROM
			(VALUES ('':::VOID), (NULL), (NULL), ('':::VOID)) AS tab_115318 (col_199168)
		WHERE
			(NULL OR true)
		ORDER BY
			tab_115318.col_199168 ASC,
			tab_115318.col_199168,
			tab_115318.col_199168 DESC,
			tab_115318.col_199168 ASC,
			tab_115318.col_199168 DESC,
			tab_115318.col_199168;
```
<p>Parameters: <code>ROACHTEST_cloud=gce</code>
, <code>ROACHTEST_cpu=4</code>
, <code>ROACHTEST_ssd=0</code>
</p>
<details><summary>Help</summary>
<p>

See: [roachtest README](https://github.com/cockroachdb/cockroach/blob/master/pkg/cmd/roachtest/README.md)

See: [How To Investigate \(internal\)](https://cockroachlabs.atlassian.net/l/c/SSSBr8c7)

</p>
</details>
/cc @cockroachdb/sql-queries
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*sqlsmith/setup=empty/setting=no-mutations.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)
</sub>

Epic: CRDB-14914

Jira issue: CRDB-17240

### PR DESCRIPTION
**Pull request by msirek**
Fixes #83754

Previously, the COALESCE and NULLIF operators could error out in
vectorized execution when comparing a VOID datum with NULL.

This occurred due to the unique property of a VOID, that it
can't be compared with another VOID using any of the normal operators
such as `=`, `<`, `>`..., or even IS [NOT] [DISTINCT FROM], for example:
```
SELECT ''::VOID IS DISTINCT FROM ''::VOID;
ERROR: unsupported comparison operator: <void> IS DISTINCT FROM <void>
SQLSTATE: 22023
```
Processing of COALESCE in the columnar execution engine for an
expression like `COALESCE(void_col, NULL)` builds an IS DISTINCT FROM
operation between the VOID column and NULL here:
https://github.com/cockroachdb/cockroach/blob/ea559dfe0ba57259ca71d3c8ca1de6388954ea73/pkg/sql/colexec/colbuilder/execplan.go#L2122-L2129

This comparison is assumed to be OK, but fails with an internal error
because comparison with `UnknownType` is only implicitly supported if
the type can be compared with itself.

To address this, this patch modifies vectorized COALESCE to use the
IS NOT NULL operator internally instead of IS DISTINCT FROM whenever    
the latter is not a valid comparison.
A similar problem with NULLIF, which internally uses `=`, is fixed.
Type checking of NULLIF is enhanced in the parser so incompatible
comparisons can be caught prior to execution time.

Release note (bug fix): This patch fixes vectorized evaluation of
COALESCE involving expressions of type VOID and enhances type checking
of NULLIF expressions with VOID, so incompatible comparisons can
be caught during query compilation instead of during query execution.

### CODE REVIEW

**Review by yuzefovich — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/83868)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @mgartner, @msirek, and @otan)

___
*[`pkg/sql/logictest/testdata/logic_test/void` line 76 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/83868#-N6Fdtkh7xW-y24cMcvK:-N6Fdtkh7xW-y24cMcvL:b-rfihj) ([raw file](https://github.com/cockroachdb/cockroach/blob/2a4526bd5f29efd94cd8008c837379df53b366d1/pkg/sql/logictest/testdata/logic_test/void#L76)):*
> ```
> 
> statement ok
> SET vectorize=off
> ```

nit: you should do something like this:
```
SET vectorize=on

<query>

SET vectorize=off

< query>

RESET vectorize
```
when you want to control the vectorize mode precisely, compare the results for two engines, and so that the setup is left unchanged in the end.

As it is written currently, the first execution can happen with any `vectorize` mode (depending on the config), the second one is guaranteed to be `vectorize=off`, and `vectorize=off` remains for all configs for the rest of the file (should new queries are added to the file).

File: pkg/sql/sem/tree/eval.go [hunk 1]
```diff
@@ -1651,6 +1651,8 @@ var CmpOps = cmpOpFixups(map[treecmp.ComparisonOperatorSymbol]cmpOpOverload{
 		makeIsFn(types.TimestampTZ, types.Timestamp, volatility.Stable),
 		makeIsFn(types.Time, types.TimeTZ, volatility.Stable),
 		makeIsFn(types.TimeTZ, types.Time, volatility.Stable),
+		makeIsFn(types.Unknown, types.Void, volatility.LeakProof),
```
Comment (otan) [inline pkg/sql/sem/tree/eval.go:1654]: can we fix type resolution to instead evaluate NULL as a VOID? i wonder if this also gets fixed by adding void here (it might not)

https://github.com/cockroachdb/cockroach/blob/c48196c300087cc1682689e7cb6f4231d5bae69a/pkg/sql/sem/tree/constant.go#L480

**Review by msirek — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/83868)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @mgartner, @msirek, and @otan)

___
*[`pkg/sql/sem/tree/eval.go` line 1654 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/83868#-N6FcakAscTxS1cYBPwc-r1-1654:-N6Fh3Wk91ejSGeJ5RpT:b-129x7h) ([raw file](https://github.com/cockroachdb/cockroach/blob/2a4526bd5f29efd94cd8008c837379df53b366d1/pkg/sql/sem/tree/eval.go#L1654)):*
<details><summary><i>Previously, otan (Oliver Tan) wrote…</i></summary><blockquote>

can we fix type resolution to instead evaluate NULL as a VOID? i wonder if this also gets fixed by adding void here (it might not)

https://github.com/cockroachdb/cockroach/blob/c48196c300087cc1682689e7cb6f4231d5bae69a/pkg/sql/sem/tree/constant.go#L480
</blockquote></details>

If I understand correctly, you're suggesting adding `types.Void, ` at the end of this slice.  This does not fix the error, and the code in `eval.go` is still required.

And, adding this would mean that type annotation on any string, such as `'foo':::VOID` would now succeed.  Is this what we want? 
Support for type annotation of the empty string to VOID is already added through #82965.

**Comment by otan** [comment]
*[`pkg/sql/sem/tree/eval.go` line 1654 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/83868#-N6FcakAscTxS1cYBPwc-r1-1654:-N6FmQKI4_1p4podAd_H:bk8hdpd) ([raw file](https://github.com/cockroachdb/cockroach/blob/2a4526bd5f29efd94cd8008c837379df53b366d1/pkg/sql/sem/tree/eval.go#L1654)):*
<details><summary><i>Previously, msirek (Mark Sirek) wrote…</i></summary><blockquote>

If I understand correctly, you're suggesting adding `types.Void, ` at the end of this slice.  This does not fix the error, and the code in `eval.go` is still required.

And, adding this would mean that type annotation on any string, such as `'foo':::VOID` would now succeed.  Is this what we want? 
Support for type annotation of the empty string to VOID is already added through #82965.


</blockquote></details>

i guess why do we special case Unknown for void but not the others? Ideally this comparison is fixed during type checking

**Comment by otan** [comment]
*[`pkg/sql/sem/tree/eval.go` line 1654 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/83868#-N6FcakAscTxS1cYBPwc-r1-1654:-N6FmZ9aDEU7BqnIjHhL:b-5l7u2q) ([raw file](https://github.com/cockroachdb/cockroach/blob/2a4526bd5f29efd94cd8008c837379df53b366d1/pkg/sql/sem/tree/eval.go#L1654)):*
<details><summary><i>Previously, otan (Oliver Tan) wrote…</i></summary><blockquote>

i guess why do we special case Unknown for void but not the others? Ideally this comparison is fixed during type checking
</blockquote></details>

Sorry by "comparison is fixed" i mean "comparison is made and evaluated to be a void comparison"

**Review by msirek — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/83868)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @mgartner, @msirek, and @otan)

___
*[`pkg/sql/sem/tree/eval.go` line 1654 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/83868#-N6FcakAscTxS1cYBPwc-r1-1654:-N6Fmd_93na5iY-X1Llt:b-ojute) ([raw file](https://github.com/cockroachdb/cockroach/blob/2a4526bd5f29efd94cd8008c837379df53b366d1/pkg/sql/sem/tree/eval.go#L1654)):*

> i guess why do we special case Unknown for void but not the others?

Because all other types are equivalent to each other, causing this line to be `true` for each of the inputs:
https://github.com/cockroachdb/cockroach/blob/94fe056cbc7f1245266ca7ea293650b370ee239a/pkg/sql/sem/tree/overload.go#L298
`a[i].Typ.Equivalent(typ)` is `false` when `a[i].Typ` is void and `type` is void.  But this is by design:
```
select ''::VOID = ''::VOID;
ERROR: unsupported comparison operator: <void> = <void>
SQLSTATE: 22023
```
So, VOID is just a special type.

**Review by msirek — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/83868)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @mgartner, @otan, and @yuzefovich)

___
*[`pkg/sql/logictest/testdata/logic_test/void` line 76 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/83868#-N6Fdtkh7xW-y24cMcvK:-N6FoQ7q2oKnvV716iES:b-o7myk8) ([raw file](https://github.com/cockroachdb/cockroach/blob/2a4526bd5f29efd94cd8008c837379df53b366d1/pkg/sql/logictest/testdata/logic_test/void#L76)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

nit: you should do something like this:
```
SET vectorize=on

<query>

SET vectorize=off

< query>

RESET vectorize
```
when you want to control the vectorize mode precisely, compare the results for two engines, and so that the setup is left unchanged in the end.

As it is written currently, the first execution can happen with any `vectorize` mode (depending on the config), the second one is guaranteed to be `vectorize=off`, and `vectorize=off` remains for all configs for the rest of the file (should new queries are added to the file).
</blockquote></details>

Fixed it, thanks!

**Comment by otan** [comment]
*[`pkg/sql/sem/tree/eval.go` line 1654 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/83868#-N6FcakAscTxS1cYBPwc-r1-1654:-N6FornF7N53gXlVZzPP:b-fykozh) ([raw file](https://github.com/cockroachdb/cockroach/blob/2a4526bd5f29efd94cd8008c837379df53b366d1/pkg/sql/sem/tree/eval.go#L1654)):*
<details><summary><i>Previously, msirek (Mark Sirek) wrote…</i></summary><blockquote>


> i guess why do we special case Unknown for void but not the others?

Because all other types are equivalent to each other, causing this line to be `true` for each of the inputs:
https://github.com/cockroachdb/cockroach/blob/94fe056cbc7f1245266ca7ea293650b370ee239a/pkg/sql/sem/tree/overload.go#L298
`a[i].Typ.Equivalent(typ)` is `false` when `a[i].Typ` is void and `type` is void.  But this is by design:
```
select ''::VOID = ''::VOID;
ERROR: unsupported comparison operator: <void> = <void>
SQLSTATE: 22023
```
So, VOID is just a special type.
</blockquote></details>

interesting... `select ''::VOID = ''::VOID;` is equating the values of the types though, not the types itself.
i'd argue `types.VoidFamily.Equivalent(types.VoidFamily)` should be true...

**Comment by otan** [comment]
*[`pkg/sql/sem/tree/eval.go` line 1654 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/83868#-N6FcakAscTxS1cYBPwc-r1-1654:-N6Fpdmo9nAfpCY2H7b_:b-p3m21a) ([raw file](https://github.com/cockroachdb/cockroach/blob/2a4526bd5f29efd94cd8008c837379df53b366d1/pkg/sql/sem/tree/eval.go#L1654)):*
<details><summary><i>Previously, otan (Oliver Tan) wrote…</i></summary><blockquote>

interesting... `select ''::VOID = ''::VOID;` is equating the values of the types though, not the types itself.
i'd argue `types.VoidFamily.Equivalent(types.VoidFamily)` should be true...
</blockquote></details>

i think this may stem from the fact that `IS` is different to `=`. 

In `pg`:
```
otan=# select ''::void = null::void;
ERROR:  operator does not exist: void = void
LINE 1: select ''::void = null::void;
```

which is different to `Is`:
```
otan=# select ''::void IS null;
 ?column?
----------
 f
(1 row)
```

so maybe adding this `makeIsFn` is necessary anyway as fixing type resolution to recognise the NULL case is different. 

It may be worth adding a comment about why this is special cased. Sorry for making a seemingly big deal about two lines of code, I really just wanted to dig into the special case!

**Review by msirek — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/83868)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @mgartner, @otan, and @yuzefovich)

___
*[`pkg/sql/sem/tree/eval.go` line 1654 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/83868#-N6FcakAscTxS1cYBPwc-r1-1654:-N6FpNZv5x8PkxdNJkP2:b-6nfdtp) ([raw file](https://github.com/cockroachdb/cockroach/blob/2a4526bd5f29efd94cd8008c837379df53b366d1/pkg/sql/sem/tree/eval.go#L1654)):*
> select ''::VOID = ''::VOID; is equating the values of the types though, not the types itself.

Yes, I know, but in the process of testing if the `=` operator can be applied we check if the types are equivalent.  This applies to any of the operators, such as IS DISTINCT FROM, which is the operator we care about here.  

> which is different to Is:
> otan=# select ''::void IS null;

This example is comparing VoidType with UnknownType, not VoidType with VoidType.

> i'd argue types.VoidFamily.Equivalent(types.VoidFamily) should be true...

If that were the case, then we'd have different behavior from postgres, which treats them not as equivalent:
```
postgres=# select ''::void is distinct from ''::void;
ERROR:  operator does not exist: void = void
LINE 1: select ''::void is distinct from ''::void;
                        ^
HINT:  No operator matches the given name and argument types. You might need to add explicit type casts.
postgres=# 

```

**Review by otan — APPROVED** [review]
please add a comment as per comment below

**Review by msirek — COMMENTED** [review]
Added:
```
		// Void is unique in that it is not equivalent with itself, so implicit
		// equivalence with Unknown in function ArgTypes.MatchAt due to the check
		// `(typ.Family() == types.UnknownFamily || a[i].Typ.Equivalent(typ))` does
		// not occur. Therefore, to allow the comparison
		// `''::VOID IS DISTINCT FROM NULL`, an explicit equivalence with Unknown is
		// added:
		makeIsFn(types.Unknown, types.Void, volatility.LeakProof),
		makeIsFn(types.Void, types.Unknown, volatility.LeakProof),
```

Do you have an opinion on whether we should support type annotation to VOID on any string to match CAST?
Currently only `'':::VOID` is legal, but since `'foo'::VOID` is legal, should `'foo':::VOID` also be legal? In #82965 we decided to only allow `'':::VOID` since that's what SQLSmith needed, and '' is a valid string representation of a VOID literal, but perhaps type annotation should have the same behavior as CAST.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/83868#-:-N6J5V0nC4yEdNtYrBKX:b-c8o1r4)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @mgartner, @otan, and @yuzefovich)

**Review by msirek — COMMENTED** [review]
bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/83868#-:-N6UaiiQ9jD7cJIYpd0-:b-ydi9ay)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @mgartner, @otan, and @yuzefovich)

**Comment by mgartner** [comment]
*[`pkg/sql/sem/tree/eval.go` line 1654 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/83868#-N6FcakAscTxS1cYBPwc-r1-1654:-N6hT_g32wzUVeX7Yrk_:bsbivft) ([raw file](https://github.com/cockroachdb/cockroach/blob/2a4526bd5f29efd94cd8008c837379df53b366d1/pkg/sql/sem/tree/eval.go#L1654)):*
<details><summary><i>Previously, msirek (Mark Sirek) wrote…</i></summary><blockquote>

> select ''::VOID = ''::VOID; is equating the values of the types though, not the types itself.

Yes, I know, but in the process of testing if the `=` operator can be applied we check if the types are equivalent.  This applies to any of the operators, such as IS DISTINCT FROM, which is the operator we care about here.  

> which is different to Is:
> otan=# select ''::void IS null;

This example is comparing VoidType with UnknownType, not VoidType with VoidType.

> i'd argue types.VoidFamily.Equivalent(types.VoidFamily) should be true...

If that were the case, then we'd have different behavior from postgres, which treats them not as equivalent:
```
postgres=# select ''::void is distinct from ''::void;
ERROR:  operator does not exist: void = void
LINE 1: select ''::void is distinct from ''::void;
                        ^
HINT:  No operator matches the given name and argument types. You might need to add explicit type casts.
postgres=# 

```
</blockquote></details>

I'm not convinced that PG supports the `[VOID] IS DISTINCT FROM [UNKNOWN]` operator:

```
marcus=# select ''::void is distinct from null::unknown;
ERROR:  42883: operator does not exist: void = unknown
LINE 1: select ''::void is distinct from null::unknown;
                        ^
HINT:  No operator matches the given name and argument types. You might need to add explicit type casts.
LOCATION:  op_error, parse_oper.c:656
```

When `NULL` is explicitly cast to the unknown type, the comparison fails. Which raises the question: which operator overload is being used for `''::VOID IS DISTINCT FROM NULL`... Maybe this inconsistent behavior is a bug in Postgres?

**Review by msirek — COMMENTED** [review]
@mgartner @yuzefovich  Please take a look at the new fix.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/83868#-:-N6kLx4Z1hmbCcPvOK2P:bswe82z)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @mgartner, @otan, and @yuzefovich)

___
*[`pkg/sql/sem/tree/eval.go` line 1654 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/83868#-N6FcakAscTxS1cYBPwc-r1-1654:-N6kIoAgCM5lM1Uw10Nm:bbcbbbl) ([raw file](https://github.com/cockroachdb/cockroach/blob/2a4526bd5f29efd94cd8008c837379df53b366d1/pkg/sql/sem/tree/eval.go#L1654)):*
> I'm not convinced that PG supports the [VOID] IS DISTINCT FROM [UNKNOWN] operator:

You're right! I found they're normalizing this to an IS NOT NULL operator when one side is NULL. The code only looks for constant NULL, not a type-cast, so is using IS DISTINCT FROM when the cast is present.
The root problem for this case is COALESCE uses IS DISTINCT FROM when vectorized, but in the row engine evaluates each expression in the COALESCE directly into a `Datum`, then compares that `Datum` directly in Go code with `DNull`:
https://github.com/cockroachdb/cockroach/blob/5a9ec7c691ab2fbfc33a79867844ee3a4a4165b2/pkg/sql/sem/eval/expr.go#L187-L194

It's now fixed by using IS NOT NULL in place of IS DISTINCT FROM NULL. 
PTAL

**Review by yuzefovich — APPROVED** [review]
:lgtm: but it's worth to get another approval too.

> Reviewed 6 of 6 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/83868#-:-N6km3r_4seNoN_hnmDf:bw86djs)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @mgartner and @otan)

**Comment by mgartner** [comment]
*[`pkg/sql/colexec/colbuilder/execplan.go` line 2128 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/83868#-N6nPXtgBq2znwPoUltH:-N6nPXtgBq2znwPoUltI:b53qoar) ([raw file](https://github.com/cockroachdb/cockroach/blob/4fb8726ae4a46a71b442e07a091c2eb9ab8a2b81/pkg/sql/colexec/colbuilder/execplan.go#L2128)):*
> ```Go
> 		for i := range whens {
> 			whens[i] = &tree.When{
> 				Cond: tree.NewTypedIsNotNullExpr(t.Exprs[i].(tree.TypedExpr)),
> ```

I hate to throw a wrench in this, but `x IS NOT NULL` and `x IS DISTINCT FROM NULL` are not equivalent when `x` is a tuple (learned this lesson in #48299). In Postgres:

```
marcus=# SELECT (NULL, NULL) IS NOT NULL;
 ?column?
----------
 f
(1 row)

marcus=# SELECT (NULL, NULL) IS DISTINCT FROM NULL;
 ?column?
----------
 t
(1 row)
```

So we can't make this transformation in all cases. A good test case to add would be the example in PG below. Notice how `(NULL, NULL)` is returned.

```
marcus=# SELECT COALESCE((NULL, NULL), (1, 2));
 coalesce
----------
 (,)
(1 row)
```

An alternative would be to use `IS NOT NULL` only if `t.Exprs[i]` is type `VOID`, and use `IS DISTINCT FROM` otherwise.

Or, since we know that any value of type `VOID` (or the singular value? or the empty value?) is always distinct from `NULL`, can we simply fold the coalesce into `t.Exprs[i]` when it is of type void? The optimizer could also make this transformation in a normalization rule.

Maybe there is a better idea if we think those alternatives are too hacky.

**Comment by mgartner** [comment]
*[`pkg/sql/sem/tree/eval.go` line 1654 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/83868#-N6FcakAscTxS1cYBPwc-r1-1654:-N6nRfIU6FzV2XjIpgsK:b-7uqz39) ([raw file](https://github.com/cockroachdb/cockroach/blob/2a4526bd5f29efd94cd8008c837379df53b366d1/pkg/sql/sem/tree/eval.go#L1654)):*
<details><summary><i>Previously, msirek (Mark Sirek) wrote…</i></summary><blockquote>

> I'm not convinced that PG supports the [VOID] IS DISTINCT FROM [UNKNOWN] operator:

You're right! I found they're normalizing this to an IS NOT NULL operator when one side is NULL. The code only looks for constant NULL, not a type-cast, so is using IS DISTINCT FROM when the cast is present.
The root problem for this case is COALESCE uses IS DISTINCT FROM when vectorized, but in the row engine evaluates each expression in the COALESCE directly into a `Datum`, then compares that `Datum` directly in Go code with `DNull`:
https://github.com/cockroachdb/cockroach/blob/5a9ec7c691ab2fbfc33a79867844ee3a4a4165b2/pkg/sql/sem/eval/expr.go#L187-L194

It's now fixed by using IS NOT NULL in place of IS DISTINCT FROM NULL. 
PTAL
</blockquote></details>

Thanks for investigating deeper!

**Review by msirek — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/83868)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @mgartner, @otan, and @yuzefovich)

___
*[`pkg/sql/colexec/colbuilder/execplan.go` line 2128 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/83868#-N6nPXtgBq2znwPoUltH:-N6oNnyfDNsRUvmd02QN:bkjybfs) ([raw file](https://github.com/cockroachdb/cockroach/blob/4fb8726ae4a46a71b442e07a091c2eb9ab8a2b81/pkg/sql/colexec/colbuilder/execplan.go#L2128)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

I hate to throw a wrench in this, but `x IS NOT NULL` and `x IS DISTINCT FROM NULL` are not equivalent when `x` is a tuple (learned this lesson in #48299). In Postgres:

```
marcus=# SELECT (NULL, NULL) IS NOT NULL;
 ?column?
----------
 f
(1 row)

marcus=# SELECT (NULL, NULL) IS DISTINCT FROM NULL;
 ?column?
----------
 t
(1 row)
```

So we can't make this transformation in all cases. A good test case to add would be the example in PG below. Notice how `(NULL, NULL)` is returned.

```
marcus=# SELECT COALESCE((NULL, NULL), (1, 2));
 coalesce
----------
 (,)
(1 row)
```

An alternative would be to use `IS NOT NULL` only if `t.Exprs[i]` is type `VOID`, and use `IS DISTINCT FROM` otherwise.

Or, since we know that any value of type `VOID` (or the singular value? or the empty value?) is always distinct from `NULL`, can we simply fold the coalesce into `t.Exprs[i]` when it is of type void? The optimizer could also make this transformation in a normalization rule.

Maybe there is a better idea if we think those alternatives are too hacky.

</blockquote></details>

Thanks for catching this!  I'm not sure what the 100% best option is, but I've updated the fix to use `IS DISTINCT FROM` if it can (by checking if the type is compatible with comparison to NULL), and if not, `IS NOT NULL`. `VOID` should be the only type this applies to, but if another type is added which is similar to `VOID`, this should automatically handle it too.

**Comment by rytaft** [comment]
Can we get this merged? @mgartner do you still need to sign off?

**Review by mgartner — APPROVED** [review]
:lgtm: 

> Reviewed 1 of 5 files at r5, 3 of 3 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/83868#-:-N7GrCSBENdYhfD_DAtI:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @msirek, @otan, and @yuzefovich)

___
*[`-- commits` line 27 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/83868#-N7GojVL8KiW5SD2NgRn):*
nit: mention that `IS NOT NULL` is only used when `IS DISTINCT FROM NULL` is not a valid comparison.

**Review by msirek — COMMENTED** [review]
TFTRs!
bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/83868#-:-N7H0vDm0c-fwt9MprEd:bg1822s)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale) (waiting on @otan and @yuzefovich)

___
*[`-- commits` line 27 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/83868#-N7GojVL8KiW5SD2NgRn):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

nit: mention that `IS NOT NULL` is only used when `IS DISTINCT FROM NULL` is not a valid comparison.
</blockquote></details>

Done
