### PR TITLE
sql,opt: add support for AddGeometryColumn function

### LINKED ISSUE #48061: builtins: unable to perform DDLs using InternalExecutor from builtins
Consider https://github.com/cockroachdb/cockroach/compare/master...otan-cockroach:add_geometry_column.

In that commit, we are trying to implement [AddGeometryColumn](https://postgis.net/docs/AddGeometryColumn.html). However, when performing the DDL for ADD COLUMN, we don't see the column come about until another DDL is performed:

```
root@127.0.0.1:55945/movr> create table test_table(a int);
CREATE TABLE
root@127.0.0.1:55945/movr> select addgeometrycolumn('test_table', 'geom2', 4326, 'GEOMETRY', 2);
ALTER TABLE test_table ADD COLUMN geom2 GEOMETRY(GEOMETRY,4326)
  addgeometrycolumn
---------------------
root@127.0.0.1:55945/movr> \d test_table
  column_name | data_type | is_nullable | column_default | generation_expression |  indices  | is_hidden
--------------+-----------+-------------+----------------+-----------------------+-----------+------------
  a           | INT8      |    true     | NULL           |                       | {}        |   false
  rowid       | INT8      |    false    | unique_rowid() |                       | {primary} |   true
(2 rows)
root@127.0.0.1:55945/movr> select addgeometrycolumn('test_table', 'geom2', 4326, 'GEOMETRY', 2);
ERROR: addgeometrycolumn(): addgeometrycolumn: duplicate: column "geom2" in the middle of being added, not yet public
root@127.0.0.1:55945/movr> create table a (a int);
CREATE TABLE
root@127.0.0.1:55945/movr> select addgeometrycolumn('test_table', 'geom2', 4326, 'GEOMETRY', 2); -- NOW it exists.
ERROR: addgeometrycolumn(): addgeometrycolumn: duplicate column name: "geom2"
root@127.0.0.1:55945/movr>
```

According to @ajwerner 

> Yeah so I think the problem is that the extra txn state isn't propagating from the internal executor back to the user's transaction here
> I think we're going to need to find a way to rewrite that query at planning time to make infrastructure work correctly
> You can't just run it in the internal executor 

From looking at the pg_proc table after importing PostGIS, we can see that `AddGeometryColumn` is implemented as a user defined function that calls `ALTER TABLE` underneath, so it makes sense to me that we should be able to perform DDLs from any builtin at some time in the future.

Another @ajwerner quote:

> on a very high level I think I might agree with you that we'll need to find a way to support that functionality but the answer does not need to be that it needs to use the internal executor

### PR DESCRIPTION
**Pull request by rytaft**
This commit adds support for the `AddGeometryColumn` function, which
executes an `ALTER TABLE ... ADD COLUMN` statement to add a geometry
column to a table as a side effect of executing the function. The
function itself returns a string with metadata summarizing the schema
change.

Since we don't yet support UDFs in CockroachDB, this commit adds support
for `AddGeometryColumn` (and future similar functions) by building the DDL
statement in the `optbuilder` phase of the optimizer and hoisting it into a
CTE before execution. The limitation with this approach is that all
arguments to the function must be constant.

Fixes #48061

Release note (sql change): Added support for the AddGeometryColumn
function, which adds a new geometry column to an existing table and
returns metadata about the column created. This improves compatibility
with PostGIS.

### CODE REVIEW

**Review by RaduBerinde — COMMENTED** [review]
This is cool! It worked out better than I expected!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/49456#-:-M7yBxELAvvPIB-0pJ3n:b-esl3fv)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andy-kimball, @otan, @RaduBerinde, and @rytaft)

___
*[pkg/sql/opt/exec/execbuilder/testdata/sql_fn, line 22 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/49456#-M7yBSVu5-1gH_iPq3lI:-M7yBSVu5-1gH_iPq3lJ:b-tye6wt) ([raw file](https://github.com/cockroachdb/cockroach/blob/6a04e310465d7bc1a06a568df7913defe009ec1e/pkg/sql/opt/exec/execbuilder/testdata/sql_fn#L22)):*
> ```
>                   CONSTRAINT "primary" PRIMARY KEY (k ASC),
>                   FAMILY "primary" (k, geom1)
> )
> ```

[nit] this formatting is weird, is this what -rewrite does? If yes, maybe file an issue. Could do `SELECT create_statement FROM [ SHOW CREATE TABLE t ]` to work around.
___
*[pkg/sql/opt/optbuilder/groupby.go, line 839 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/49456#-M7yA4g_0HUERJILZvop:-M7yA4g_0HUERJILZvoq:b24aff8) ([raw file](https://github.com/cockroachdb/cockroach/blob/6a04e310465d7bc1a06a568df7913defe009ec1e/pkg/sql/opt/optbuilder/groupby.go#L839)):*
> ```Go
> }
> 
> func isSqlFn(def *tree.FunctionDefinition) bool {
> ```

[nit] we usually don't camelcase acronyms (`isSQLFn`, `buildSQLFn` etc)
___
*[pkg/sql/opt/optbuilder/scope.go, line 1252 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/49456#-M7yAfQrCQe2QkpXziKf:-M7yAfQrCQe2QkpXziKg:b-y5dshk) ([raw file](https://github.com/cockroachdb/cockroach/blob/6a04e310465d7bc1a06a568df7913defe009ec1e/pkg/sql/opt/optbuilder/scope.go#L1252)):*
> ```Go
> }
> 
> func (s *scope) replaceSqlFn(f *tree.FuncExpr, def *tree.FunctionDefinition) tree.Expr {
> ```

[nit] this should have a comment. It should explain what we're replacing them with and it should refer to `sqlFnInfo / SqlClass` for more info.
___
*[pkg/sql/opt/optbuilder/sql_fn.go, line 23 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/49456#-M7y9zskB7haiNfv-c5M:-M7y9zskB7haiNfv-c5N:b-t4c6ef) ([raw file](https://github.com/cockroachdb/cockroach/blob/6a04e310465d7bc1a06a568df7913defe009ec1e/pkg/sql/opt/optbuilder/sql_fn.go#L23)):*
> ```Go
> )
> 
> // sqlFnInfo stores information about a SQL statement function call.
> ```

Need more words here, maybe an example (or refer to `SqlClass` documentation)
___
*[pkg/sql/sem/tree/function_definition.go, line 125 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/49456#-M7yAGZm5m3FQ1L_ZGRi:-M7yAGZm5m3FQ1L_ZGRj:bgeug6n) ([raw file](https://github.com/cockroachdb/cockroach/blob/6a04e310465d7bc1a06a568df7913defe009ec1e/pkg/sql/sem/tree/function_definition.go#L125)):*
> ```Go
> 	// GeneratorClass is a builtin generator function.
> 	GeneratorClass
> 	// SqlClass is a builtin function that executes a SQL statement.
> ```

An example here would be nice, given that it's a new concept we are introducing.

**Review by rytaft — COMMENTED** [review]
TFTR! Updated.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/49456#-:-M7yXP-b-WdhDqGMdAyM:b-p0fj95)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andy-kimball and @otan)

___
*[pkg/sql/opt/exec/execbuilder/testdata/sql_fn, line 22 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/49456#-M7yBSVu5-1gH_iPq3lI:-M7yQqvyA3d2vcJyIE2S:b-hd4nl5) ([raw file](https://github.com/cockroachdb/cockroach/blob/6a04e310465d7bc1a06a568df7913defe009ec1e/pkg/sql/opt/exec/execbuilder/testdata/sql_fn#L22)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

[nit] this formatting is weird, is this what -rewrite does? If yes, maybe file an issue. Could do `SELECT create_statement FROM [ SHOW CREATE TABLE t ]` to work around.
</blockquote></details>

Done. Filed #49460.
___
*[pkg/sql/opt/optbuilder/groupby.go, line 839 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/49456#-M7yA4g_0HUERJILZvop:-M7yRg58Cr8Wf103TI0X:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/6a04e310465d7bc1a06a568df7913defe009ec1e/pkg/sql/opt/optbuilder/groupby.go#L839)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

[nit] we usually don't camelcase acronyms (`isSQLFn`, `buildSQLFn` etc)
</blockquote></details>

Done.
___
*[pkg/sql/opt/optbuilder/scope.go, line 1252 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/49456#-M7yAfQrCQe2QkpXziKf:-M7ySU3v2RzOSsn61JjW:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/6a04e310465d7bc1a06a568df7913defe009ec1e/pkg/sql/opt/optbuilder/scope.go#L1252)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

[nit] this should have a comment. It should explain what we're replacing them with and it should refer to `sqlFnInfo / SqlClass` for more info.
</blockquote></details>

Done.
___
*[pkg/sql/opt/optbuilder/sql_fn.go, line 23 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/49456#-M7y9zskB7haiNfv-c5M:-M7ySopW1hZ7w-JHvIdk:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/6a04e310465d7bc1a06a568df7913defe009ec1e/pkg/sql/opt/optbuilder/sql_fn.go#L23)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

Need more words here, maybe an example (or refer to `SqlClass` documentation)
</blockquote></details>

Done.
___
*[pkg/sql/sem/tree/function_definition.go, line 125 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/49456#-M7yAGZm5m3FQ1L_ZGRi:-M7yTFws-3KXOFe-clWv:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/6a04e310465d7bc1a06a568df7913defe009ec1e/pkg/sql/sem/tree/function_definition.go#L125)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

An example here would be nice, given that it's a new concept we are introducing.
</blockquote></details>

Done.

**Review by RaduBerinde — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/49456#-:-M7ygo05BCecwr_HsjEW:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @andy-kimball and @otan)

File: pkg/sql/sem/builtins/geo_builtins.go [hunk 1]
```diff
@@ -1445,3 +1708,76 @@ func initGeoBuiltins() {
 		builtins[k] = v
 	}
 }
+
+// addGeometryColumnSql returns the SQL statement that should be executed to
+// add a geometry column.
+func addGeometryColumnSql(
```
Comment (otan) [inline pkg/sql/sem/builtins/geo_builtins.go:1714]: nit: should this be `addGeometryColumnSQL`

**Review by otan — APPROVED** [review]
lgtm! thanks!

**Review by rytaft — COMMENTED** [review]
TFTR!

bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/49456#-:-M80id9R80sBJnjUzq91:b-oduykh)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @andy-kimball)

___
*[pkg/sql/sem/builtins/geo_builtins.go, line 1714 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/49456#-M7y87rC9ULSouwtkmdN-r2-1714:-M80iZa09ets-WRdodWE:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/665bf5597937d93d76183953a32734ab2372c8ee/pkg/sql/sem/builtins/geo_builtins.go#L1714)):*
<details><summary><i>Previously, otan (Oliver Tan) wrote…</i></summary><blockquote>

nit: should this be `addGeometryColumnSQL`
</blockquote></details>

Done.
