### PR TITLE
kvcoord: Fix mux rangefeed startup deadlock

### LINKED ISSUE #111111: roachtest: cdc/scan/catchup/nodes=5/cpu=16/rows=1G/ranges=100k/protocol=mux/format=json/sink=null failed
roachtest.cdc/scan/catchup/nodes=5/cpu=16/rows=1G/ranges=100k/protocol=mux/format=json/sink=null [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/11880874?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/11880874?buildTab=artifacts#/cdc/scan/catchup/nodes=5/cpu=16/rows=1G/ranges=100k/protocol=mux/format=json/sink=null) on master @ [6a2097e4c2b6537be84f265bd55ac23d2cf83351](https://github.com/cockroachdb/cockroach/commits/6a2097e4c2b6537be84f265bd55ac23d2cf83351):

```
(test_runner.go:1141).runTest: test timed out (2h0m0s)
(monitor.go:153).Wait: monitor failure: unexpected node event: n6: cockroach process died (exit code 137)
test artifacts and logs in: /artifacts/cdc/scan/catchup/nodes=5/cpu=16/rows=1G/ranges=100k/protocol=mux/format=json/sink=null/run_1
```
<p>Parameters: <code>ROACHTEST_arch=amd64</code>
, <code>ROACHTEST_cloud=gce</code>
, <code>ROACHTEST_cpu=16</code>
, <code>ROACHTEST_encrypted=false</code>
, <code>ROACHTEST_ssd=0</code>
</p>
<details><summary>Help</summary>
<p>

See: [roachtest README](https://github.com/cockroachdb/cockroach/blob/master/pkg/cmd/roachtest/README.md)

See: [How To Investigate \(internal\)](https://cockroachlabs.atlassian.net/l/c/SSSBr8c7)

See: [Grafana](https://go.crdb.dev/roachtest-grafana/teamcity-11880874/cdc-scan-catchup-nodes-5-cpu-16-rows-1g-ranges-100k-protocol-mu/1695385002726/1695392522693)

</p>
</details>
/cc @cockroachdb/cdc
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*cdc/scan/catchup/nodes=5/cpu=16/rows=1G/ranges=100k/protocol=mux/format=json/sink=null.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)
</sub>

Jira issue: CRDB-31771

### LINKED ISSUE #111165: roachtest: c2c/weekly/kv50 failed
roachtest.c2c/weekly/kv50 [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestWeeklyAwsBazel/11896234?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestWeeklyAwsBazel/11896234?buildTab=artifacts#/c2c/weekly/kv50) on master @ [b1a641f1d27653a4e93154926be57d0cae864bd6](https://github.com/cockroachdb/cockroach/commits/b1a641f1d27653a4e93154926be57d0cae864bd6):

```
(soon.go:64).SucceedsWithin: condition failed to evaluate within 6h0m0s: from cluster_to_cluster.go:661: no replicated time
(monitor.go:153).Wait: monitor failure: monitor user task failed: t.Fatal() was called
test artifacts and logs in: /artifacts/c2c/weekly/kv50/run_1
```
<p>Parameters: <code>ROACHTEST_arch=amd64</code>
, <code>ROACHTEST_cloud=aws</code>
, <code>ROACHTEST_cpu=8</code>
, <code>ROACHTEST_encrypted=false</code>
, <code>ROACHTEST_fs=ext4</code>
, <code>ROACHTEST_localSSD=false</code>
, <code>ROACHTEST_ssd=0</code>
</p>
<details><summary>Help</summary>
<p>

See: [roachtest README](https://github.com/cockroachdb/cockroach/blob/master/pkg/cmd/roachtest/README.md)

See: [How To Investigate \(internal\)](https://cockroachlabs.atlassian.net/l/c/SSSBr8c7)

_Grafana is not yet available for aws clusters_</p>
</details>
/cc @cockroachdb/disaster-recovery
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*c2c/weekly/kv50.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)
</sub>

Jira issue: CRDB-31799

### PR DESCRIPTION
**Pull request by miretskiy**
Previous PR #110919 modified rangefeed startup logic to rely on rate limit, instead of a semaphore.

The issue exposed by catchup scan rate limiter is that it allowed many more (100/sec vs 8 prior) catchup scans to be started.  If the range resides on a local node, a local "bypass" rpc is created instead (rpc/context.go) and this RPC bypass is implemented via buffered channels.

The deadlock occurs when the client attempts to send request to the server, while holding the lock, but blocks (because channel is full -- i.e. we have sent 128 outstanding requests), and the server blocks for the same reason because the client mux goroutine is blocked attempting to acquire the lock to lookup the stream for the rangefeed message.

The fix moves the state shared by the sender and the consumer -- namely the stream map -- outside of the sender lock.

This fix adds a test that reliably fails under deadlock detection.

Fixes  #111111
Fixes #111165

Release note: None

### CODE REVIEW

**Comment by miretskiy** [comment]
Large scale roachtest (issue #111111 ) no longer fails:

Screenshot 2023-09-26 at 7 41 25 PM

File: pkg/kv/kvclient/kvcoord/dist_sender_mux_rangefeed.go [hunk 1]
```diff
@@ -555,8 +555,10 @@ func (m *rangefeedMuxer) restartActiveRangeFeed(
 // on this node connection.  If no error returned, registers stream
 // with this connection.  Otherwise, stream is not registered.
 func (c *muxStream) startRangeFeed(
-	streamID int64, stream *activeMuxRangeFeed, req *kvpb.RangeFeedRequest,
+	streamID int64, stream *activeMuxRangeFeed, req *kvpb.RangeFeedRequest, beforeSend func(),
 ) error {
+	c.streams.Store(streamID, unsafe.Pointer(stream))
```
Comment (aliher1911) [inline pkg/kv/kvclient/kvcoord/dist_sender_mux_rangefeed.go:560]: Wouldn't that be a problem if we do `startRangeFeed()` while we are closing?
We will add stream to streams, realize that `c.mu.closed == true` return an error but keep stream in the map.
Outer loop will keep trying, but `close()` loop will also add this feed to its `toRestart` result to trigger restarts.

**Review by aliher1911 — CHANGES_REQUESTED** [review]
Some nits about naming/comments, but I'd mostly like to get more clarity on how start/close interact as it is not obvious.

**Review by miretskiy — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/111312)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @aliher1911)

___
*[`pkg/kv/kvclient/kvcoord/dist_sender_mux_rangefeed.go` line 560 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/111312#gh-1338413638:-NfLVJ-R3x9Idf3rsZLT:bw0xw2v) ([raw file](https://github.com/cockroachdb/cockroach/blob/5620728f536ef0f08463712298f2710760ee8654/pkg/kv/kvclient/kvcoord/dist_sender_mux_rangefeed.go#L560)):*
<details><summary><i>Previously, aliher1911 (Oleg) wrote…</i></summary><blockquote>

Wouldn't that be a problem if we do `startRangeFeed()` while we are closing?
We will add stream to streams, realize that `c.mu.closed == true` return an error but keep stream in the map.
Outer loop will keep trying, but `close()` loop will also add this feed to its `toRestart` result to trigger restarts.
</blockquote></details>

Good point re errClosed -- I meant to always undo this insert.  Fixed.
___
*[`pkg/kv/kvclient/kvcoord/dist_sender_rangefeed.go` line 104 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/111312#gh-1338330235:-NfLVv_eBmfoJrIxrBT6:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/5620728f536ef0f08463712298f2710760ee8654/pkg/kv/kvclient/kvcoord/dist_sender_rangefeed.go#L104)):*
<details><summary><i>Previously, aliher1911 (Oleg) wrote…</i></summary><blockquote>

Worth mentioning that this knob is mux rangefeed specific as the knob above.
</blockquote></details>

Done.
___
*[`pkg/kv/kvclient/kvcoord/dist_sender_rangefeed.go` line 1007 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/111312#gh-1338353677:-NfLVyZh8CXfhljZhcmg:bja4szh) ([raw file](https://github.com/cockroachdb/cockroach/blob/5620728f536ef0f08463712298f2710760ee8654/pkg/kv/kvclient/kvcoord/dist_sender_rangefeed.go#L1007)):*
<details><summary><i>Previously, aliher1911 (Oleg) wrote…</i></summary><blockquote>

Second argument deserves name and also some explanation or reference why we use burst as 0. I think we had a discussion that having it as 0 will cause some undesired effects?
</blockquote></details>

Nah -- there are no undesired effects; It will simply result in smooth x/second rate, without bursts.
I changed the code back to return just 1 number and added comment on 0 burst rate at call sites.
___
*[`pkg/kv/kvclient/kvcoord/dist_sender_rangefeed.go` line 1028 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/111312#gh-1338349429:-NfLX3-T4UJBxcQZhXXP:b-7rl0jd) ([raw file](https://github.com/cockroachdb/cockroach/blob/5620728f536ef0f08463712298f2710760ee8654/pkg/kv/kvclient/kvcoord/dist_sender_rangefeed.go#L1028)):*
<details><summary><i>Previously, aliher1911 (Oleg) wrote…</i></summary><blockquote>

nit: Name is misleading. I see we use the same value for threshold and logging period, but function arg should reflect that it's a logging period not a acquisition threshold.

loggingMinInterval?
</blockquote></details>

done.

File: pkg/kv/kvclient/kvcoord/dist_sender_mux_rangefeed.go (hunk 1 above)
Comment (miretskiy) [reply pkg/kv/kvclient/kvcoord/dist_sender_mux_rangefeed.go:578]: Good points.  Addressed (I hope); added with large comment.

**Review by aliher1911 — APPROVED** [review]
Now I like the `defer` order!

Thanks fixing this.
