### PR TITLE
kvcoord: provide local node ID to DistSender in shared-process mode

### LINKED ISSUE #109522: multitenant: DistSQL may not send to the local node in a multiregion shared-process multitenancy cluster
While trying to enable the multi-region tests under the default test tenant I noticed some strange behaviour, and an opportunity for improvement in how we handle multi-region clusters under multi-tenancy.  The way distSQL works in multi-region clusters is that we try and route the query to the local node if at all possible.  This is handled in the `sendToReplicas()` function with this block of code:

https://github.com/cockroachdb/cockroach/blob/7e4233d09edef5420b8f12d917112ce762ac1855/pkg/kv/kvclient/kvcoord/dist_sender.go#L2167-L2191

One problem with this code in shared-process multi-tenancy is that we rely on a call to `getNodeID()`, and that function has not yet been updated for shared-process multi-tenancy:

https://github.com/cockroachdb/cockroach/blob/7e4233d09edef5420b8f12d917112ce762ac1855/pkg/kv/kvclient/kvcoord/dist_sender.go#L718-L728

As a result, distSQL queries will not try and send the query to the node-local replica for shared-process multitenancy.  This may result in a regression for customers moving to the UA for MR use cases.

Epic: CRDB-26687

Jira issue: CRDB-30964

### PR DESCRIPTION
**Pull request by yuzefovich**
This commit makes it so that the DistSender of SQL pods running in shared-process mode have access to the node ID of the local KV node. The node ID is used to preferentially route requests to replicas available on the local node. Previously, this optimization was only available in single-tenant mode, and now it'll be also available in shared-process multi-tenant. The optimization doesn't exist in separate-process multi-tenant, so in that mode we continue to return `0` as the node ID which makes it so that replicas are picked randomly.

For testing, this commit extends existing `TestSecondaryTenantFollowerReadsRouting` to also have a shared-process test configuration. There were a few gotchas in that adjustment:
- for simplicity, we need to create a single region cluster so that latency and locality don't come into consideration when choosing the replica (we want to make sure that the local replica is used if available)
- starting shared-process virtual cluster on a multi node cluster can be racy if we want to provide testing knobs, so we have to start the service on the gateway node first. (If we don't start with the gateway, then the server controller on the gateway could start the tenant server with empty knobs _before_ we explicitly start the service there.)
- previously the test relied on retrieving the follower reads metric counters from all nodes and asserting only for `n2` it increased. However, in shared-process config it is now possible for an internal query (e.g. issued by auto stats collection) to be served via follower reads too, which would increment the counter confusing the test. As a result, this commit adjusts the test to audit the trace of the query and verify that the single follower read was served specifically by `n2`.

Fixes: #109522.

Release note: None

### CODE REVIEW

File: pkg/server/tenant.go [hunk 1]
```diff
@@ -1125,11 +1125,24 @@ func makeTenantSQLServerArgs(
...
+	// provide that without accessing the gossip.
+	//
+	// In separate-process mode, not knowing the node ID, and thus not being
+	// able to take advantage of this optimization is okay, given tenants not
+	// running in-process with KV instances have no such optimization to take
+	// advantage of to begin with.
+	var nodeIDGetter func() roachpb.NodeID
+	if serviceMode == mtinfopb.ServiceModeShared {
+		nodeIDGetter = baseCfg.IDContainer.Get
+	}
```
Comment (stevendanna) [inline pkg/server/tenant.go:1139]: Rather than rely on the service mode, could we pass this in via tenantServerDeps?  We already have other mixed-process vs separate process differences encapsulated in that struct.

**Review by yuzefovich — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/111447)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @stevendanna)

___
*[`pkg/server/tenant.go` line 1139 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/111447#gh-1341956746:-NfsIXVb1uORwpIshC8E:b-yw5wpu) ([raw file](https://github.com/cockroachdb/cockroach/blob/5b78731230243e1cb1fc611455d63818c58ac8e5/pkg/server/tenant.go#L1139)):*
<details><summary><i>Previously, stevendanna (Steven Danna) wrote…</i></summary><blockquote>

Rather than rely on the service mode, could we pass this in via tenantServerDeps?  We already have other mixed-process vs separate process differences encapsulated in that struct.
</blockquote></details>

Nice, done. There is a failure in Extended CI that I want understand before requesting the review, so I'm keeping it as a draft for now.

**Comment by yuzefovich** [comment]
The failure under stress doesn't make sense - it suggests that the follower reads counter _decreased_ on at least one of the nodes, how is that possible?

I was able to repro it on gceworker too
```
    --- FAIL: TestSecondaryTenantFollowerReadsRouting/shared-process (9.75s)
        followerreads_test.go:1119: 
            	Error Trace:	github.com/cockroachdb/cockroach/pkg/ccl/kvccl/kvfollowerreadsccl/followerreads_test.go:1119
            	Error:      	Not equal: 
            	            	expected: 1
            	            	actual  : 0
            	Test:       	TestSecondaryTenantFollowerReadsRouting/shared-process
            	Messages:   	on n3
```

**Review by yuzefovich — COMMENTED** [review]
I think I figured out the reason for test being a bit flaky for shared-process config, it should be solid now. RFAL.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/111447#-:-NgHT-0P0skudHEm431y:b-ce2fw0)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @knz and @stevendanna)

**Review by stevendanna — APPROVED** [review]
