### PR TITLE
sql: Fix privilege checks to consider direct/indirect roles

### LINKED ISSUE #57621: sql: privilege inquiry functions don't take role into account
**Describe the problem**

The privilege inquiry functions (e.g. `has_schema_privilege`) check if a user has a privilege on the given schema. It can be called in two ways:
- `has_schema_privilege(user, schema_name, privilege_type)`
- `has_schema_privilege(schema_name, privilege_type)`

In the second way, the user is assumed to be the current user. However, the implementation only checks for the privileges assigned to the _user_, and not the roles that the user belongs to.

**To Reproduce**

```
# Start a fresh cluster and connect as root.

root@:26257/defaultdb> create database my_db;
CREATE DATABASE

root@:26257/defaultdb> CREATE USER my_user;
CREATE ROLE

root@:26257/defaultdb> CREATE ROLE my_role;
CREATE ROLE

root@:26257/defaultdb> GRANT ALL ON DATABASE my_db TO my_role;
GRANT

root@:26257/defaultdb> GRANT my_role TO my_user;
GRANT

# Disconnect, then reconnect with my_user to my_db.
# ./cockroach sql --insecure -u my_user -d my_db

my_user@:26257/my_db> select has_schema_privilege('my_role', 'public', 'usage');
  has_schema_privilege
------------------------
          true

my_user@:26257/my_db> select has_schema_privilege('public', 'usage');
  has_schema_privilege
------------------------
         false
```

**Expected behavior**
`select has_schema_privilege('public', 'usage');` should return `true`.

**Environment:**
Affects version 20.2

### PR DESCRIPTION
**Pull request by angelapwen**
Resolves #57621 

Previously, privilege inquiry functions  only looked for whether
the user passed in in the first argument or current user had
privileges on schemas, databases, tables, etc. with the built-ins
such as `has_schema_privileges`, which was incorrect. This change
makes sure that all roles the user is a direct or indirect member
of are checked for privileges as well.

Release note (bug fix): The has_${OBJECT}_privilege built-in methods
such as `has_schema_privilege` now additionally checks whether roles
the user is a direct or indirect member of also have privileges on
the object. Previously only one user was checked which was incorrect.
This bug has been present since version 2.0 but became more
prominent as of v20.2 when role-based access control was included in
CockroachDB Core.

### CODE REVIEW

File: pkg/sql/exec_util.go [hunk 1]
```diff
@@ -1057,6 +1057,17 @@ func golangFillQueryArguments(args ...interface{}) (tree.Datums, error) {
...
+				case val.Type().Elem().Kind() == reflect.String:
+					a := tree.NewDArray(types.String)
+					// TODO(angelaw): Ranging through val seems to require pointer arithmetic so did it this way
+					for s := range args {
+						// It is a bit hacky though...
+						if err := a.Append(tree.NewDString(reflect.ValueOf(s).String())); err != nil {
+							return nil, err
+						}
+					}
+					res[i] = a
```
Comment (rafiss) [inline pkg/sql/exec_util.go:1069]: no need to set res[i] here -- that can happen on line 1073 if we just make the variable `d = tree.NewDArray(types.String)`

also i think it would be a bug to return early here, since it has to go through the rest of the outer for loop

File: pkg/sql/exec_util.go [hunk 2]
```diff
@@ -1057,6 +1057,17 @@ func golangFillQueryArguments(args ...interface{}) (tree.Datums, error) {
 				switch {
 				case val.IsNil():
 					d = tree.DNull
+				case val.Type().Elem().Kind() == reflect.String:
+					a := tree.NewDArray(types.String)
+					// TODO(angelaw): Ranging through val seems to require pointer arithmetic so did it this way
+					for s := range args {
```
Comment (rafiss) [inline pkg/sql/exec_util.go:1063]: I think this loop needs to look more like this:

```
					for i := 0; i < val.Len(); i += 1 {
						a.Append(tree.NewDString(val.Index(i).String()))
					}
			
```

dealing with reflected types is weird.. but the idea is that instead of using the built in slice operations like `len()` or the `[]` index access, there are separate functions for that

also note that we don't want to loop over `args` since the array is just one of the arguments to `golangFillQueryArguments`

**Review by rafiss — CHANGES_REQUESTED** [review]
i think i have an idea for how this could work!

File: pkg/sql/exec_util.go [hunk 3]
```diff
@@ -1057,6 +1057,17 @@ func golangFillQueryArguments(args ...interface{}) (tree.Datums, error) {
...
+						// It is a bit hacky though...
+						if err := a.Append(tree.NewDString(reflect.ValueOf(s).String())); err != nil {
```
Comment (angelapwen) [inline pkg/sql/exec_util.go:1065]: Print debugging — this line doesn't end up appending what I want as `s` just becomes `ARRAY['<int Value>']`

Comment (rafiss) [reply pkg/sql/exec_util.go:1065]: ah yeah, since `for s := range args` will just loop over the indexes of `args`

File: pkg/sql/exec_util.go (hunk 1 above)
Comment (angelapwen) [reply pkg/sql/exec_util.go:1069]: I originally had done that, but `d` is a `tree.Datum` and doesn't have an `Append` method so I thought I'd make it a separate method. I see what you mean about returning too early though.

Comment (rafiss) [reply pkg/sql/exec_util.go:1069]: ooh got it. then i guess instead of `res[i] = a` this line should just be `d = a`

File: pkg/sql/exec_util.go (hunk 2 above)
Comment (rafiss) [reply pkg/sql/exec_util.go:1063]: to be safe, we also should check if the result of `val.Index(i)` is `nil`, and if so we'd want to append `tree.DNull` in the array instead of a `DString`

Comment (angelapwen) [reply pkg/sql/exec_util.go]: `val.Index(i)` is a string which can't be `nil` in Go I believe — I added a check for `isValid` but I'm not sure it's necessary at all.

File: pkg/sql/exec_util.go [hunk 4]
```diff
@@ -1057,6 +1057,20 @@ func golangFillQueryArguments(args ...interface{}) (tree.Datums, error) {
 				switch {
 				case val.IsNil():
 					d = tree.DNull
+				case val.Type().Elem().Kind() == reflect.String:
+					a := tree.NewDArray(types.String)
+					for i := 0; i < val.Len(); i++ {
```
Comment (rafiss) [inline pkg/sql/exec_util.go:1062]: looks like `i` is already used as the outer loop variable. so we need a different name here

File: pkg/sql/exec_util.go [hunk 5]
```diff
@@ -1057,6 +1057,20 @@ func golangFillQueryArguments(args ...interface{}) (tree.Datums, error) {
...
+						if !val.Index(i).IsValid() {
```
Comment (rafiss) [inline pkg/sql/exec_util.go:1063]: i think an invalid object doesn't need to be handled separately, so we can just remove this check. looks like the docs say that we can assume that a value returned by `.index(i)` is valid

File: pkg/sql/sem/builtins/pg_builtins.go [hunk 6]
```diff
@@ -531,13 +531,25 @@ func evalPrivilegeCheck(
...
 	}
+
+	allRoleMemberships, err := ctx.Planner.MemberOfWithAdminOption(ctx.Context, user)
+	if err != nil {
+		return nil, err
+	}
+
+	// Slice containing all roles user is a direct and indirect member of.
+	allRoles := []string{security.PublicRole, user.Normalized()}
+	for role, _ := range allRoleMemberships {
```
Comment (rafiss) [inline pkg/sql/sem/builtins/pg_builtins.go:542]: nit: don't need the second `_`

**Review by rafiss — CHANGES_REQUESTED** [review]
code looks good! just need to add logic tests

File: pkg/sql/exec_util.go (hunk 4 above)
Comment (angelapwen) [reply pkg/sql/exec_util.go]: Ah, yes, noticed that in the TeamCity failure — resolved

**Comment by angelapwen** [comment]
Thanks @rafiss for review! I added logic tests checking for appropriate privilege inquiry responses in direct and indirect role membership.

File: pkg/sql/logictest/testdata/logic_test/privilege_builtins [hunk 7]
```diff
@@ -1056,3 +1056,53 @@ query B
...
 ----
 true
+
+# Regression test for #58254.
+
+user root
+
+statement ok
+DROP DATABASE IF EXISTS my_db;
+CREATE DATABASE my_db;
```
Comment (rafiss) [inline pkg/sql/logictest/testdata/logic_test/privilege_builtins:1066]: could you also create a user-defined schema within my_db? the permissions are computed differently for those

File: pkg/sql/logictest/testdata/logic_test/privilege_builtins [hunk 8]
```diff
@@ -1056,3 +1056,53 @@ query B
...
+
+statement ok
+CREATE ROLE my_role;
+
+statement ok
+GRANT ALL ON DATABASE my_db TO my_role;
```
Comment (rafiss) [inline pkg/sql/logictest/testdata/logic_test/privilege_builtins:1072]: just to exercise more of the logic, maybe this test could just `GRANT SELECT ON DATABASE my_db TO my_role`? and further down, it could `GRANT ALL ON DATABASE my_db TO testuser2`.

then it could check that testuser has SELECT privilege on my_db but does not have CREATE privilege, while testuser2 has both.

(and similar for the user-defined schema that you make as per my earlier comment)

the idea here is to make sure that privilege inheritance is additive -- testuser2 should also be able to get its own privileges separately from whatever it inherits.

File: pkg/sql/logictest/testdata/logic_test/privilege_builtins [hunk 9]
```diff
@@ -1056,3 +1056,53 @@ query B
 SELECT has_column_privilege('hcp_test'::REGCLASS, 4, 'SELECT')
 ----
 true
+
+# Regression test for #58254.
```
Comment (rafiss) [inline pkg/sql/logictest/testdata/logic_test/privilege_builtins:1060]: nit: could the comment say that it tests privilege inheritance for roles? (you can keep the issue number too, the idea is just to save people a copy+paste)

**Review by rafiss — CHANGES_REQUESTED** [review]
it all looks good to me! just had an idea for the test

File: pkg/sql/logictest/testdata/logic_test/privilege_builtins (hunk 9 above)
Comment (angelapwen) [reply pkg/sql/logictest/testdata/logic_test/privilege_builtins]: Done!

File: pkg/sql/logictest/testdata/logic_test/privilege_builtins (hunk 7 above)
Comment (angelapwen) [reply pkg/sql/logictest/testdata/logic_test/privilege_builtins:1066]: Done!

File: pkg/sql/logictest/testdata/logic_test/privilege_builtins (hunk 8 above)
Comment (angelapwen) [reply pkg/sql/logictest/testdata/logic_test/privilege_builtins]: I've done this for the user-defined schema, but had trouble confirming for the database privileges because the only options for [`has_database_privilege` builtin are CREATE, CONNECT, TEMPORARY, and TEMP](https://github.com/cockroachdb/cockroach/blob/c18a8d3fdc9828ca154ab95634b2c7f0c2fe0477/pkg/sql/sem/builtins/pg_builtins.go#L1320). Of these, only CREATE can be granted. If I grant CREATE, then testing the remaining 3 options results in the following:
- CONNECT always returns true as the comment states all users have CONNECT privilege for all databases.
- TEMPORARY and TEMP follow the same privilege check under the hood as CREATE.

So it doesn't seem possible to test one privilege but not another for this built-in on a database.

Comment (rafiss) [reply pkg/sql/logictest/testdata/logic_test/privilege_builtins]: interesting, i didn't know that's how has_database_privilege worked! no need to test that here then

**Review by rafiss — APPROVED** [review]
lgtm! thanks for all your work on this

**Comment by rafiss** [comment]
I will create a backport PR for this as well

**Comment by angelapwen** [comment]
bors r=rafiss
