### PR TITLE
acceptance: start local cluster in parallel

### LINKED ISSUE #10512: teamcity: failed tests on master: acceptance/TestNodeRestart
The following tests appear to have failed:

[#43011](https://teamcity.cockroachdb.com/viewLog.html?buildId=43011):

```
--- FAIL: acceptance/TestNodeRestart (56.143s)
	testing.go:117: acceptance/util_test.go:404, condition failed to evaluate within 45s: failed to send RPC: rpc error: code = 1 desc = context canceled

```
Please assign, take a look and update the issue accordingly.

### PR DESCRIPTION
**Pull request by jordanlewis**
This changes the local cluster setup process so that each Cockroach
Docker container is started in parallel. On my machine, this reduces the
time it takes to run the 3-node cluster tests by 2 seconds each.

Also, fix a bug in `util_test` that would cause a connection error
during local cluster startup to be unrecoverable due to a cancelled
context. This likely fixes #10512 and other similar issues.

---
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/10463)

### CODE REVIEW

**Review by a-robinson — APPROVED** [review]

File: pkg/acceptance/cluster/localcluster.go [hunk 1]
```diff
@@ -651,9 +653,15 @@ func (l *LocalCluster) Start() {
 
 	l.monitorCtx, l.monitorCtxCancelFunc = context.WithCancel(context.Background())
 	go l.monitor()
+	var wg sync.WaitGroup
+	wg.Add(len(l.Nodes))
 	for _, node := range l.Nodes {
-		l.startNode(node)
+		go func(node *testNode) {
```
Comment (tschottdorf) [inline pkg/acceptance/cluster/localcluster.go]: Probably want to sprinkle some commentary on `startNode` and `createRoach` that they might be called in parallel. I did a cursory review and nothing looks obviously racy.

Comment (a-robinson) [inline pkg/acceptance/cluster/localcluster.go]: Yeah, it looked like only reads to me, but a comment would be reasonable

Comment (jordanlewis) [inline pkg/acceptance/cluster/localcluster.go]: Done.
