### PR TITLE
sql/catalog: stop hiding constraints on hidden columns

### LINKED ISSUE #80035: sql: constraints which involve NOT VISIBLE columns do not appear in SHOW CONSTRAINTS
**Describe the problem**

Please describe the issue you observed, and any steps we can take to reproduce it:
Currently trying to implement cockroachdb on the headless CMS Strapi (https://github.com/strapi/strapi/pull/12346). They use knex but I am still having trouble with table constraints not showing up

**To Reproduce**
Currently we are making this table
```
CREATE TABLE public.admin_permissions_role_links (
permission_id INT8 NULL,
role_id INT8 NULL,
rowid INT8 NOT VISIBLE NOT NULL DEFAULT unique_rowid(),
CONSTRAINT "primary" PRIMARY KEY (rowid ASC),
CONSTRAINT admin_permissions_role_links_fk FOREIGN KEY (permission_id) REFERENCES public.admin_permissions(id) ON DELETE CASCADE NOT VALID,
CONSTRAINT admin_permissions_role_links_inv_fk FOREIGN KEY (role_id) REFERENCES public.admin_roles(id) ON DELETE CASCADE NOT VALID,
INDEX admin_permissions_role_links_fk (permission_id ASC),
INDEX admin_permissions_role_links_inv_fk (role_id ASC),
FAMILY "primary" (permission_id, role_id, rowid)
)
```
You can see that there should be a constraint on the primary key
`CONSTRAINT "primary" PRIMARY KEY (rowid ASC),`

However if you run the above command then do:
` show constraints from admin_permissions_role_links`

You can see that the constraint isn't even there?
image

**Expected behavior**
The constraint should be listed when running `show constraints` 

**Environment:**
 - CockroachDB version: 21.2.4
 - Server OS: Windows 10
 - Client app: cockroach sql

### PR DESCRIPTION
**Pull request by rafiss**
fixes #80035

In 9d61c05 (from 2017), constraints that only included hidden columns
were excluded from all introspection. The rationale was that hidden
columns are not in SHOW COLUMNS or information_schema.columns, so
neither should the constraints.

However, that rationale is not true any more. Hidden columns are shown
in those places now. Also, we've seen that tools can get confused when
we don't report these constraints.

Release note (sql change): Constraints that only include hidden columns are
no longer excluded in SHOW CONSTRAINTS. This behavior can be changed
using the show_primary_key_constraint_on_hidden_columns session
variable.

Release note (bug fix): Fixed a bug that allowed duplicate constraint
names for the same table if the constraints were on hidden columns.

### CODE REVIEW

**Review by ajwerner — COMMENTED** [review]
This feels like a potentially breaking change. I'd be reticent to backport it by default in 21.2 which is already released. I think it's okay for 22.1. How about a session variable to enable this behavior which defaults to off in 21.2 and on in 22.1 and master?

> Reviewed 4 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/80154#-:-N03f-ih0B2v1S8LYTeH:blz15m4)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dt and @otan)

**Comment by rafiss** [comment]
It's slightly annoying to plumb the session variable all the way down to here. i'm actually not sure how to do it for the Validate calls in pkg/sql/catalog/internal/validate/validate.go or pkg/sql/catalog/internal/catkv/descriptors.go

i'm not sure though; it feels more broken to not be including these constraints. for example, this is a place that seems straight up broken right now: https://github.com/cockroachdb/cockroach/blob/659e9fce5f41d075547a0b9703583b0fd1db3e2d/pkg/sql/alter_table.go#L981-L988

i just discovered this now. it looks like it could potentially generate a CHECK constraint name with the same name as a constraint on a hidden column. i'll try to play around and see what happens if i do this.

**Comment by rafiss** [comment]
Here's some behavior right now that feels incorrect to me:
```
root@:26257/defaultdb> create table t ( a int, b int);
CREATE TABLE

root@:26257/defaultdb> alter table t rename constraint t_pkey to something_else;
ERROR: constraint "t_pkey" of relation "t" does not exist
SQLSTATE: 42704

root@:26257/defaultdb> create unique index t_pkey on t(a);
ERROR: index with name "t_pkey" already exists
SQLSTATE: 42P07
```

Another sketchy one:
```
root@:26257/defaultdb> create table t2 ( a int, b int, primary key (a));
CREATE TABLE

root@:26257/defaultdb> alter table t2 rename constraint t2_pkey to my_key;
ALTER TABLE

root@:26257/defaultdb> show constraints from t2;
  table_name | constraint_name | constraint_type |       details       | validated
-------------+-----------------+-----------------+---------------------+------------
  t2         | my_key          | PRIMARY KEY     | PRIMARY KEY (a ASC) |   true
(1 row)

root@:26257/defaultdb> alter table t2 alter column a set not visible;
ALTER TABLE

root@:26257/defaultdb> show constraints from t2;
SHOW CONSTRAINTS 0

root@:26257/defaultdb> alter table t2 rename constraint my_key to another_key;
ERROR: constraint "my_key" of relation "t2" does not exist
SQLSTATE: 42704
```

And then you can do even worse:
```
root@:26257/defaultdb> alter table t2 add constraint my_key CHECK(b > 0);
ALTER TABLE

root@:26257/defaultdb> show create table t2;
  table_name |              create_statement
-------------+---------------------------------------------
  t2         | CREATE TABLE public.t2 (
             |     a INT8 NOT VISIBLE NOT NULL,
             |     b INT8 NULL,
             |     CONSTRAINT my_key PRIMARY KEY (a ASC),
             |     CONSTRAINT my_key CHECK (b > 0:::INT8)
             | )
(1 row)

root@:26257/defaultdb> alter table t2 alter column a set visible;
ERROR: relation "t2" (106): duplicate constraint name: "my_key"
SQLSTATE: 42710
```

**Comment by rafiss** [comment]
So I'm still against making this behind a session variable. I don't even know what we'd call it. Maybe it'd be `check_duplicate_constraint_names_on_hidden_columns_sometimes` 😅

**Comment by ajwerner** [comment]
It just feels like totally possible we're going to break some tool out there that currently works, and that scares me.

**Comment by rafiss** [comment]
How about I keep the current parts of the change as is, but add in a session variable to specifically gate the pg_constraint populate logic in `pg_catalog.go` (to decide to show constraints on hidden columns or not)?

**Comment by rafiss** [comment]
Please take another look

File: pkg/sql/vars.go [hunk 1]
```diff
@@ -2067,6 +2067,23 @@ var varGen = map[string]sessionVar{
 		},
 		GlobalDefault: globalFalse,
 	},
+
+	// CockroachDB extension.
+	`show_primary_key_constraint_on_hidden_columns`: {
+		GetStringVal: makePostgresBoolGetStringValFn(`show_primary_key_constraint_on_hidden_columns`),
```
Comment (otan) [inline pkg/sql/vars.go:2073]: should we call this `show_primary_key_constraint_on_not_visible_columns `?

**Review by otan — APPROVED** [review]

**Review by ajwerner — APPROVED** [review]
:lgtm:

> Reviewed 1 of 5 files at r1, 5 of 6 files at r2, 1 of 1 files at r3, 5 of 5 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/80154#-:-N0aYGpRAF2Px1uNYSQ0:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @dt and @rafiss)

___
*[`pkg/sql/sessiondatapb/local_only_session_data.proto` line 253 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/80154#-N0aY5LMBmOdcy0bT0VR:-N0aY5LMBmOdcy0bT0VS:b-xrato5) ([raw file](https://github.com/cockroachdb/cockroach/blob/4d599e577b99d27b5d33117a23d2edabfd25e39d/pkg/sql/sessiondatapb/local_only_session_data.proto#L253)):*
> ```protobuf
>   // at the risk of data corruption if the same row is modified multiple times.
>   bool multiple_modifications_of_table = 68;
>   // c controls whether SHOW CONSTRAINTS
> ```

nit: `s|// c|// ShowPrimaryKeyConstraintOnHiddenColumns|`

**Comment by rafiss** [comment]
tftr!

bors r=otan,ajwerner

**Comment by ajwerner** [comment]
Looks like merge skew: `pkg/sql/vars.go:2085:3: cannot use func literal (type func(*extendedEvalContext) (string, error)) as type func(*extendedEvalContext, *kv.Txn) (string, error) in field value`

bors r-

**Comment by rafiss** [comment]
bors r=otan,ajwerner
