### PR TITLE
changefeedccl: fix panic when setting min_checkpoint_frequency < 10ns

### LINKED ISSUE #143436: changefeedccl: setting min_checkpoint_frequency < 10ns panics
Steps to repro:
```
CREATE CHANGEFEED FOR TABLE foo WITH min_checkpoint_frequency='1ns'
```

Panic:
```
* ERROR: a panic has occurred!
* panic: invalid argument to Int63n
* (1) attached stack trace
*   -- stack trace:
*   | runtime.gopanic
*   | 	GOROOT/src/runtime/panic.go:791
*   | github.com/cockroachdb/cockroach/pkg/util/ctxgroup.Group.Wait
*   | 	pkg/util/ctxgroup/ctxgroup.go:150
*   | github.com/cockroachdb/cockroach/pkg/util/ctxgroup.GoAndWait
*   | 	pkg/util/ctxgroup/ctxgroup.go:223
*   | github.com/cockroachdb/cockroach/pkg/ccl/changefeedccl.startDistChangefeed
*   | 	pkg/ccl/changefeedccl/changefeed_dist.go:337
*   | github.com/cockroachdb/cockroach/pkg/ccl/changefeedccl.distChangefeedFlow
*   | 	pkg/ccl/changefeedccl/changefeed_dist.go:137
*   | github.com/cockroachdb/cockroach/pkg/ccl/changefeedccl.coreChangefeed
*   | 	pkg/ccl/changefeedccl/changefeed_stmt.go:370
*   | github.com/cockroachdb/cockroach/pkg/ccl/changefeedccl.changefeedPlanHook.func1
*   | 	pkg/ccl/changefeedccl/changefeed_stmt.go:233
*   | github.com/cockroachdb/cockroach/pkg/ccl/changefeedccl.changefeedPlanHook.func2
*   | 	pkg/ccl/changefeedccl/changefeed_stmt.go:330
*   | github.com/cockroachdb/cockroach/pkg/sql.(*hookFnNode).startExec.func1
*   | 	pkg/sql/planhook.go:187
*   | [...repeated from below...]
* Wraps: (2) attached stack trace
*   -- stack trace:
*   | runtime.gopanic
*   | 	GOROOT/src/runtime/panic.go:791
*   | math/rand.(*Rand).Int63n
*   | 	GOROOT/src/math/rand/rand.go:122
*   | math/rand.Int63n
*   | 	GOROOT/src/math/rand/rand.go:443
*   | github.com/cockroachdb/cockroach/pkg/ccl/changefeedccl.nextFlushWithJitter
*   | 	pkg/ccl/changefeedccl/changefeed_processors.go:710
*   | github.com/cockroachdb/cockroach/pkg/ccl/changefeedccl.(*changeAggregator).noteResolvedSpan.func2
*   | 	pkg/ccl/changefeedccl/changefeed_processors.go:898
*   | github.com/cockroachdb/cockroach/pkg/ccl/changefeedccl.(*changeAggregator).noteResolvedSpan
*   | 	pkg/ccl/changefeedccl/changefeed_processors.go:904
*   | github.com/cockroachdb/cockroach/pkg/ccl/changefeedccl.(*changeAggregator).tick
*   | 	pkg/ccl/changefeedccl/changefeed_processors.go:844
*   | github.com/cockroachdb/cockroach/pkg/ccl/changefeedccl.(*changeAggregator).Next
*   | 	pkg/ccl/changefeedccl/changefeed_processors.go:754
*   | github.com/cockroachdb/cockroach/pkg/ccl/changefeedccl.(*changeFrontier).Next
*   | 	pkg/ccl/changefeedccl/changefeed_processors.go:1558
*   | github.com/cockroachdb/cockroach/pkg/sql/execinfra.Run
*   | 	pkg/sql/execinfra/base.go:193
*   | github.com/cockroachdb/cockroach/pkg/sql/execinfra.(*ProcessorBaseNoHelper).Run
*   | 	pkg/sql/execinfra/processorsbase.go:743
*   | github.com/cockroachdb/cockroach/pkg/sql/flowinfra.(*FlowBase).Run
*   | 	pkg/sql/flowinfra/flow.go:574
*   | github.com/cockroachdb/cockroach/pkg/sql.(*DistSQLPlanner).Run
*   | 	pkg/sql/distsql_running.go:985
*   | github.com/cockroachdb/cockroach/pkg/ccl/changefeedccl.startDistChangefeed.func1
*   | 	pkg/ccl/changefeedccl/changefeed_dist.go:333
*   | github.com/cockroachdb/cockroach/pkg/util/ctxgroup.GoAndWait.Group.GoCtx.func1
*   | 	pkg/util/ctxgroup/ctxgroup.go:199
*   | golang.org/x/sync/errgroup.(*Group).Go.func1
*   | 	external/org_golang_x_sync/errgroup/errgroup.go:78
*   | runtime.goexit
*   | 	src/runtime/asm_arm64.s:1223
* Wraps: (3) panic: invalid argument to Int63n
* Error types: (1) *withstack.withStack (2) *withstack.withStack (3) *errutil.leafError
*
```

Cause appears to be default value of `changefeed.aggregator.flush_jitter` being 0.1, which after being multiplied with the `min_checkpoint_frequency`, is rounded to zero when converted back to an int64:
https://github.com/cockroachdb/cockroach/blob/f6187144b3adb682b89ac032d618c1dbe7020239/pkg/ccl/changefeedccl/changefeed_processors.go#L710

Note: If `changefeed.aggregator.flush_jitter` is set higher, then this panic could happen even if with larger values of `min_checkpoint_frequency`.

Jira issue: CRDB-48833

### PR DESCRIPTION
**Pull request by KeithCh**
Previously when min_checkpoint_frequency is set to
be less than 10ns, it would cause a panic if
we're using the default
changefeed.aggregator.flush_jitter value of 0.1.

This fix would also prevent panics from happening
if min_checkpoint_frequency > 10ns but
flush_jitter is set too low.

Release note (bug fix): Fixed a bug where using
values changefeed.aggregator.flush_jitter,
min_checkpoint_frequency such that
changefeed.aggregator.flush_jitter *
min_checkpoint_frequency < 1 would cause a panic.
Jitter will now be disabled in this case.

Fixes: https://github.com/cockroachdb/cockroach/issues/143436

### CODE REVIEW

File: pkg/ccl/changefeedccl/changefeed_test.go [hunk 1]
```diff
@@ -8886,6 +8886,18 @@ func TestFlushJitter(t *testing.T) {
 			expectedFlushDuration: 100 * time.Millisecond,
 			expectedErr:           false,
 		},
+		{
```
Comment (andyyang890) [inline pkg/ccl/changefeedccl/changefeed_test.go:8889]: nit: these cases should probably go under the `// Enable Jitter.` comment below

File: pkg/ccl/changefeedccl/changefeed_processors.go [hunk 2]
```diff
@@ -711,10 +711,11 @@ func nextFlushWithJitter(s timeutil.TimeSource, d time.Duration, j float64) (tim
 	if j < 0 || d < 0 {
 		return s.Now(), errors.AssertionFailedf("invalid jitter value: %f, duration: %s", j, d)
 	}
-	if j == 0 || d == 0 {
+	dFraction := int64(j * float64(d))
+	if j == 0 || d == 0 || dFraction == 0 {
```
Comment (andyyang890) [inline pkg/ccl/changefeedccl/changefeed_processors.go:715]: you'll only need to check if `dFraction == 0` because if either `j` or `d` is zero the product will be zero right

File: pkg/ccl/changefeedccl/changefeed_processors.go [hunk 3]
```diff
@@ -711,10 +711,11 @@ func nextFlushWithJitter(s timeutil.TimeSource, d time.Duration, j float64) (tim
 	if j < 0 || d < 0 {
 		return s.Now(), errors.AssertionFailedf("invalid jitter value: %f, duration: %s", j, d)
 	}
-	if j == 0 || d == 0 {
+	dFraction := int64(j * float64(d))
```
Comment (andyyang890) [inline pkg/ccl/changefeedccl/changefeed_processors.go:714]: nit: s/dFraction/maxJitter

File: pkg/ccl/changefeedccl/changefeed_processors.go (hunk 2 above)
Comment (KeithCh) [reply pkg/ccl/changefeedccl/changefeed_processors.go:715]: Not necessarily, say j = 1, d = 0.1
dFraction = int64(0.1*float64(1)) = int64(0.1) = 0

File: pkg/ccl/changefeedccl/changefeed_test.go (hunk 1 above)
Comment (KeithCh) [reply pkg/ccl/changefeedccl/changefeed_test.go:8889]: We expect these cases to not have jitter though (it falls into the `dFraction == 0 case`).

Comment (andyyang890) [reply pkg/ccl/changefeedccl/changefeed_test.go:8889]: I interpreted "enable jitter" to mean setting `jitter` to some non-zero value but nbd lol

File: pkg/ccl/changefeedccl/changefeed_processors.go (hunk 2 above)
Comment (KeithCh) [reply pkg/ccl/changefeedccl/changefeed_processors.go]: Ah yes you're correct

File: pkg/ccl/changefeedccl/changefeed_test.go (hunk 1 above)
Comment (KeithCh) [reply pkg/ccl/changefeedccl/changefeed_test.go:8889]: I can move it since it looks like other test cases is like this, I'll add a comment as well.

File: pkg/ccl/changefeedccl/changefeed_processors.go (hunk 2 above)
Comment (KeithCh) [reply pkg/ccl/changefeedccl/changefeed_processors.go]: I misread that as a statement as opposed to a question

File: pkg/ccl/changefeedccl/changefeed_processors.go [hunk 4]
```diff
@@ -711,10 +711,11 @@ func nextFlushWithJitter(s timeutil.TimeSource, d time.Duration, j float64) (tim
 	if j < 0 || d < 0 {
 		return s.Now(), errors.AssertionFailedf("invalid jitter value: %f, duration: %s", j, d)
 	}
-	if j == 0 || d == 0 {
+	maxJitter := int64(j * float64(d))
+	if j == 0 || d == 0 || maxJitter == 0 {
```
Comment (andyyang890) [inline pkg/ccl/changefeedccl/changefeed_processors.go:715]: as discussed in https://github.com/cockroachdb/cockroach/pull/144304#discussion_r2042256161:
```suggestion
	if maxJitter == 0 {
```

File: pkg/ccl/changefeedccl/changefeed_test.go [hunk 5]
```diff
@@ -8911,6 +8911,18 @@ func TestFlushJitter(t *testing.T) {
 			expectedFlushDuration: 100 * time.Millisecond,
 			expectedErr:           false,
 		},
+		{ // Expect actual jitter to be 0 since flushFrequency * jitter < 1
```
Comment (andyyang890) [inline pkg/ccl/changefeedccl/changefeed_test.go:8914]: nit: put comment above the brace

**Review by andyyang890 — APPROVED** [review]

**Comment by KeithCh** [comment]
bors r=andyyang890

**Comment by KeithCh** [comment]
blathers backport 24.1

**Comment by KeithCh** [comment]
blathers backport 24.1

**Comment by KeithCh** [comment]
blathers backport 24.1
