### PR TITLE
sql: fix tuple IS NULL logic

### LINKED ISSUE #46675: sql: wrong implementation of NULL predicate for row value expressions
**Describe the problem**

It appears that the NULL predicate is not implemented correctly (or not at all?) for row value expressions.

**To Reproduce**

Run this query:

```sql
select a, b, 
  (a, b) is null, 
  (a, b) is not null,
  not ((a, b) is null),
  not ((a, b) is not null)
from (
  values (1, 1), (1, null), (null, 1), (null, null)
) as t (a, b)
```

And get the following, wrong result:

```
a|b|?column?|?column?|?column?|?column?|
-|-|--------|--------|--------|--------|
1|1|false   |true    |true    |false   |
1| |false   |true    |true    |false   |
 |1|false   |true    |true    |false   |
 | |false   |true    |true    |false   |
```

**Expected behavior**

It should either work as in the SQL standard (ISO/IEC 9075-2:2016(E)
8.8 &lt;null predicate>) / PostgreSQL:

```
a|b|?column?|?column?|?column?|?column?|
-|-|--------|--------|--------|--------|
1|1|false   |true    |true    |false   |
1| |false   |false   |true    |true    |
 |1|false   |false   |true    |true    |
 | |true    |false   |false   |true    |
```

Or raise an error

**Environment:**
 - CockroachDB version: CockroachDB CCL v19.2.5 (x86_64-unknown-linux-gnu, built 2020/03/16 18:27:12, go1.12.12)
 - Server OS: See above (using docker)
 - Client app: JDBC

### PR DESCRIPTION
**Pull request by mgartner**
Previously, we treated all cases of `x IS NULL` as `x IS NOT DISTINCT
FROM NULL`, and all cases of `x IS NOT NULL` as `x IS DISTINCT FROM
NULL`. However, these transformations are not equivalent when `x` is a
tuple.

If all elements of `x` are `NULL`, then `x IS NULL` should evaluate to
true, but `x IS DISTINCT FROM NULL` should evaluate to false. If one
element of `x` is `NULL` and one is not null, then `x IS NOT NULL`
should evaluate to false, but `x IS DISTINCT FROM NULL` should evaluate
to true. Therefore, they are not equivalent.

Below is a table of the correct semantics for tuple expressions.

| Tuple        | IS NOT DISTINCT FROM NULL | IS NULL   | IS DISTINCT FROM NULL | IS NOT NULL |
| ------------ | ------------------------- | --------- | --------------------- | ----------- |
| (1, 1)       | false                     | false     | true                  | true        |
| (1, NULL)    | false                     | **false** | true                  | **false**   |
| (NULL, NULL) | false                     | true      | true                  | false       |

Notice that `IS NOT DISTINCT FROM NULL` is always the inverse of
`IS DISTINCT FROM NULL`. However, `IS NULL` and `IS NOT NULL` are not
inverses given the tuple `(1, NULL)`.

This commit introduces new tree expressions for `IS NULL` and `IS NOT
NULL`. These operators have evaluation logic that is different from `IS
NOT DISTINCT FROM NULL` and `IS DISTINCT FROM NULL`, respectively. While
an expression such as `x IS NOT DISTINCT FROM NULL` is parsed as a
`tree.ComparisonExpr` with a `tree.IsNotDisinctFrom` operator,
execbuiler will output the simpler `tree.IsNullExpr` when the two
expressions are equivalent - when x is not a tuple.

This commit also introduces new optimizer expression types,
`IsTupleNull` and `IsTupleNotNull`. Normalization rules have been added
for folding these expressions into boolean values when possible.

Fixes   #46675
Informs #46908
Informs #12022

Release note (bug fix): Fixes incorrect logic for `IS NULL` and `IS NOT
NULL` operators with tuples, correctly differentiating them from `IS NOT
DISTINCT FROM NULL` and `IS DISTINCT FROM NULL`, respectively.

### CODE REVIEW

**Comment by mgartner** [comment]
@RaduBerinde Here's my first stab at the tuple IS NULL bug. You don't need to look too thoroughly, but it would be great if you could let me know if I'm on the right track. Note I've only made the changes for `IS NULL` not `IS NOT NULL`—I want to make sure I'm on the right track first.

File: pkg/sql/opt/norm/fold_constants.go [hunk 1]
```diff
@@ -66,6 +66,29 @@ func (c *CustomFuncs) IsConstValueOrTuple(input opt.ScalarExpr) bool {
...
+		if e.Op() != opt.NullOp {
+			return false
+		}
+	}
+	return true
+}
+
+// IsNonNullTuple returns true if the input tuple has one non-null constant
+// value.
+func (c *CustomFuncs) IsNonNullTuple(input opt.ScalarExpr) bool {
```
Comment (mgartner) [inline pkg/sql/opt/norm/fold_constants.go:82]: We currently only fold `tuple IS NULL` to `true` if `tuple` has only constants. I'm not sure why we don't fold in the case of `(1, col1) IS NULL` to `False`.

So I'm a bit scared of this change because we will now fold `(1, col1) IS NULL` to `False`. Is there a reason not to do this folding?

**Review by RaduBerinde — COMMENTED** [review]
Yeah this is definitely on the right track!

I really like the "unary" tree operators

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/48299#-:-M6HKPvs5el7k2yWF8vJ:bmez0ph)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @mgartner)

___
*[pkg/sql/opt/norm/fold_constants.go, line 73 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/48299#-M6HLAFJEKW81fZWO86F:-M6HLAFJEKW81fZWO86G:bkj3043) ([raw file](https://github.com/cockroachdb/cockroach/blob/00258203d4656b0b97fbda11587f58e7eaadadc5/pkg/sql/opt/norm/fold_constants.go#L73)):*
> ```Go
> 	tup := input.(*memo.TupleExpr)
> 	for _, e := range tup.Elems {
> 		if e.Op() != opt.NullOp {
> ```

What if the input is a variable or some other non-const expression? It could still be Null after evaluation
___
*[pkg/sql/opt/norm/fold_constants.go, line 82 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/48299#-M6HLx0W1EwTFj4ac0Dq:-M6HLx0W1EwTFj4ac0Dr:b-b9mupm) ([raw file](https://github.com/cockroachdb/cockroach/blob/00258203d4656b0b97fbda11587f58e7eaadadc5/pkg/sql/opt/norm/fold_constants.go#L82)):*
> ```Go
> // IsNonNullTuple returns true if the input tuple has one non-null constant
> // value.
> func (c *CustomFuncs) IsNonNullTuple(input opt.ScalarExpr) bool {
> ```

These methods should document that they are meant to have yes/maybe semantics (ie allow false positives).

I think it's fine to fold `(1,x) IS NULL` to false. But not `(x,y)`..

**Review by mgartner — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/48299)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @mgartner)

___
*[pkg/sql/logictest/testdata/logic_test/alter_table, line 933 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/48299#-M6ph47y3ZPcawmc3ZJW:-M6ph47y3ZPcawmc3ZJX:b37uo13) ([raw file](https://github.com/cockroachdb/cockroach/blob/bacea2d791e198a6eb9efd44a6d89534c117cb29/pkg/sql/logictest/testdata/logic_test/alter_table#L933)):*
> ```
> INSERT INTO t VALUES (1), (NULL)
> 
> statement error validation of NOT NULL constraint failed: validation of CHECK "a IS DISTINCT FROM NULL" failed
> ```

@raduberinde The deeper I get into this, the more I think this is not a great solution. For example, I don't love how this error message changes, but I don't see a way around it.

**Review by mgartner — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/48299)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @mgartner)

___
*[pkg/sql/logictest/testdata/logic_test/alter_table, line 933 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/48299#-M6ph47y3ZPcawmc3ZJW:-M6pnFdm9l5T3wT_U4Db:b-aoa1o8) ([raw file](https://github.com/cockroachdb/cockroach/blob/bacea2d791e198a6eb9efd44a6d89534c117cb29/pkg/sql/logictest/testdata/logic_test/alter_table#L933)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

@raduberinde The deeper I get into this, the more I think this is not a great solution. For example, I don't love how this error message changes, but I don't see a way around it.
</blockquote></details>

Maybe we can convert an `Is`/`IsNot` back into a `tree.IsNullExpr`/`tree.IsNotNullExpr` when the right side is a null in execbuilder? I'm not sure if that's safe, though.

**Review by RaduBerinde — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/48299)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @mgartner)

___
*[pkg/sql/logictest/testdata/logic_test/alter_table, line 933 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/48299#-M6ph47y3ZPcawmc3ZJW:-M6pth-1B0LiqfInQzmb:b-q6v8i0) ([raw file](https://github.com/cockroachdb/cockroach/blob/bacea2d791e198a6eb9efd44a6d89534c117cb29/pkg/sql/logictest/testdata/logic_test/alter_table#L933)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

Maybe we can convert an `Is`/`IsNot` back into a `tree.IsNullExpr`/`tree.IsNotNullExpr` when the right side is a null in execbuilder? I'm not sure if that's safe, though.
</blockquote></details>

Yeah I think we should do that (but only if the type of the left side is not of tuple type).

**Review by yuzefovich — COMMENTED** [review]
Nice work!

nit: I usually don't link the issue numbers in the commit message and do link them only in the PR description. This way those issues don't get a lot of spam whenever the commits are amended.

> Reviewed 2 of 54 files at r2, 15 of 51 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/48299#-:-M78b3gJA4Z0gzgy7d5Y:b-j9pzbu)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @mgartner and @yuzefovich)

___
*[pkg/sql/colexec/execplan.go, line 1113 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/48299#-M78bL4d2FRlTk9apxLH:-M78bL4d2FRlTk9apxLI:b-ci217m) ([raw file](https://github.com/cockroachdb/cockroach/blob/39cfab0bdfea4d6d3b38d8dbeac3ef228e91965f/pkg/sql/colexec/execplan.go#L1113)):*
> ```Go
> 	}
> 	err = ppr.planPostProcessSpec(ctx, flowCtx, post, streamingMemAccount)
> 	if err != nil && processorConstructor == nil {
> ```

Why do you want to add this? I think it's a good idea, but I would like to know what prompted you to add this. In our unit tests we "expect" that the wrapping might fail (with a panic), and the unit tests are expected to catch those panics.
___
*[pkg/sql/colexec/execplan.go, line 1485 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/48299#-M78byMs21Iz5UXME-tM:-M78byMs21Iz5UXME-tN:b-9nuj8d) ([raw file](https://github.com/cockroachdb/cockroach/blob/39cfab0bdfea4d6d3b38d8dbeac3ef228e91965f/pkg/sql/colexec/execplan.go#L1485)):*
> ```Go
> 			ctx, evalCtx, t.TypedInnerExpr(), columnTypes, input, acc,
> 		)
> 		_, negate := expr.(*tree.IsNotNullExpr)
> ```

nit: this will always be `false`.
___
*[pkg/sql/colexec/execplan.go, line 1525 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/48299#-M78e4yR6b2GqFaMU2pD:-M78e4yR6b2GqFaMU2pE:bmbtuls) ([raw file](https://github.com/cockroachdb/cockroach/blob/39cfab0bdfea4d6d3b38d8dbeac3ef228e91965f/pkg/sql/colexec/execplan.go#L1525)):*
> ```Go
> 					return nil, resultIdx, ct, internalMemUsed, err
> 				}
> 				// IS NULL is replaced with IS NOT DISTINCT FROM NULL, so we want to
> ```

nit: this comment is no longer valid and should be removed.
___
*[pkg/sql/colexec/execplan.go, line 1625 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/48299#-M78cCEz6LPETbim1-vX:-M78cCEz6LPETbim1-vY:b-b5gdue) ([raw file](https://github.com/cockroachdb/cockroach/blob/39cfab0bdfea4d6d3b38d8dbeac3ef228e91965f/pkg/sql/colexec/execplan.go#L1625)):*
> ```Go
> 	case *tree.BinaryExpr:
> 		return planProjectionExpr(ctx, evalCtx, t.Operator, t.ResolvedType(), t.TypedLeft(), t.TypedRight(), columnTypes, input, acc)
> 	case *tree.IsNullExpr:
> ```

nit: I'd probably extract a helper function here to remove duplication.
___
*[pkg/sql/colexec/execplan.go, line 1680 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/48299#-M78cLlEBAhZLdaTpO5w:-M78cLlEBAhZLdaTpO5x:b-hy3sfz) ([raw file](https://github.com/cockroachdb/cockroach/blob/39cfab0bdfea4d6d3b38d8dbeac3ef228e91965f/pkg/sql/colexec/execplan.go#L1680)):*
> ```Go
> 		}
> 		typs = appendOneType(typs, t.ResolvedType())
> 		resultIdx = len(typs) - 1
> ```

super nit: you could move this line before `appendOneType` line and remove `-1` part.

**Review by mgartner — COMMENTED** [review]
TFTR Yahor! And for the suggestion to keep issue links out of commits.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/48299#-:-M79IBJU0VQRn6AIg0Ps:b-qiqclt)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @RaduBerinde and @yuzefovich)

___
*[pkg/sql/colexec/execplan.go, line 1113 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/48299#-M78bL4d2FRlTk9apxLH:-M799k3_3xTkScyp9P-f:b-qxosz1) ([raw file](https://github.com/cockroachdb/cockroach/blob/39cfab0bdfea4d6d3b38d8dbeac3ef228e91965f/pkg/sql/colexec/execplan.go#L1113)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

Why do you want to add this? I think it's a good idea, but I would like to know what prompted you to add this. In our unit tests we "expect" that the wrapping might fail (with a panic), and the unit tests are expected to catch those panics.
</blockquote></details>

As I started adding support for IsNullExpr and IsNotNull to `colexec`, the test cases in `is_null_ops_test.go` would fail with a nil pointer exception here: https://github.com/cockroachdb/cockroach/blob/91b28807a29d122f4e161dd819bef6e86a291824/pkg/sql/colexec/execplan.go#L484

It took me quite some time to track down exactly what the problem was—was just the IsNullExpr logic missing, or were the tests also broken, or something else?

With this change, the "real" err is propagated in the output of the failing test, which looks like `unable to columnarize filter expression "@1 IS NULL": unhandled selection expression type: *tree.IsNullExpr`.

I don't feel too strongly, but I'd hate for someone to spend more time than needed chasing down this nil pointer exception when a new expression is added.
___
*[pkg/sql/colexec/execplan.go, line 1485 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/48299#-M78byMs21Iz5UXME-tM:-M79Bn_L5voVLjAKNahd:b9mwu4f) ([raw file](https://github.com/cockroachdb/cockroach/blob/39cfab0bdfea4d6d3b38d8dbeac3ef228e91965f/pkg/sql/colexec/execplan.go#L1485)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

nit: this will always be `false`.
</blockquote></details>

Oops, good catch. Must have been some copy-pasta :spaghetti: 
___
*[pkg/sql/colexec/execplan.go, line 1525 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/48299#-M78e4yR6b2GqFaMU2pD:-M79Cal5BnYi1YkqOmCM:b-h4putg) ([raw file](https://github.com/cockroachdb/cockroach/blob/39cfab0bdfea4d6d3b38d8dbeac3ef228e91965f/pkg/sql/colexec/execplan.go#L1525)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

nit: this comment is no longer valid and should be removed.
</blockquote></details>

I've updated it instead. I think it's worth keeping since I think it was attempting to explain why we **negate** in the case of IS DISTINCT FROM, instead of IS **NOT** DISTINCT FROM, since that's a bit confusing. What do you think?
___
*[pkg/sql/colexec/execplan.go, line 1625 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/48299#-M78cCEz6LPETbim1-vX:-M79F4KX-ptqnLDLImPU:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/39cfab0bdfea4d6d3b38d8dbeac3ef228e91965f/pkg/sql/colexec/execplan.go#L1625)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

nit: I'd probably extract a helper function here to remove duplication.
</blockquote></details>

Done.
___
*[pkg/sql/colexec/execplan.go, line 1680 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/48299#-M78cLlEBAhZLdaTpO5w:-M79FG0H11etGXNyWuE0:b6dfw1p) ([raw file](https://github.com/cockroachdb/cockroach/blob/39cfab0bdfea4d6d3b38d8dbeac3ef228e91965f/pkg/sql/colexec/execplan.go#L1680)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

super nit: you could move this line before `appendOneType` line and remove `-1` part.
</blockquote></details>

Happy to do so, but can you explain the reason? I made this change here and throughout the file because it was easier for me to reason about `resultIdx` being the index of the last element of the newly expanded `typs`. But I don't have the context of the rest of the `colexec` code.

Would you like me to revert all the places I've made a similar change in this file?
___
*[pkg/sql/opt/norm/fold_constants.go, line 73 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/48299#-M6HLAFJEKW81fZWO86F:-M79G82o8fq3xxN54J-G:b-n0agzw) ([raw file](https://github.com/cockroachdb/cockroach/blob/00258203d4656b0b97fbda11587f58e7eaadadc5/pkg/sql/opt/norm/fold_constants.go#L73)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

What if the input is a variable or some other non-const expression? It could still be Null after evaluation
</blockquote></details>

Correct. That is why we return false, since we cannot guarantee that all elements are NULL.
___
*[pkg/sql/opt/norm/fold_constants.go, line 82 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/48299#-M6HLx0W1EwTFj4ac0Dq:-M79GJku2sGMpe2S1hqM:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/00258203d4656b0b97fbda11587f58e7eaadadc5/pkg/sql/opt/norm/fold_constants.go#L82)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

These methods should document that they are meant to have yes/maybe semantics (ie allow false positives).

I think it's fine to fold `(1,x) IS NULL` to false. But not `(x,y)`..
</blockquote></details>

Done.

**Review by yuzefovich — APPROVED** [review]
`colexec` changes LGTM.

> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/48299#-:-M79O8B3CRDO0-YXjL5N:b-jkjp7d)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @mgartner and @RaduBerinde)

___
*[pkg/sql/colexec/execplan.go, line 1113 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/48299#-M78bL4d2FRlTk9apxLH:-M79Mhdo6QLB3Imd-LAR:bnipyrr) ([raw file](https://github.com/cockroachdb/cockroach/blob/39cfab0bdfea4d6d3b38d8dbeac3ef228e91965f/pkg/sql/colexec/execplan.go#L1113)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

As I started adding support for IsNullExpr and IsNotNull to `colexec`, the test cases in `is_null_ops_test.go` would fail with a nil pointer exception here: https://github.com/cockroachdb/cockroach/blob/91b28807a29d122f4e161dd819bef6e86a291824/pkg/sql/colexec/execplan.go#L484

It took me quite some time to track down exactly what the problem was—was just the IsNullExpr logic missing, or were the tests also broken, or something else?

With this change, the "real" err is propagated in the output of the failing test, which looks like `unable to columnarize filter expression "@1 IS NULL": unhandled selection expression type: *tree.IsNullExpr`.

I don't feel too strongly, but I'd hate for someone to spend more time than needed chasing down this nil pointer exception when a new expression is added.


</blockquote></details>

Got it, I agree it's a good idea to add this. Could you please leave this TODO here for me?
`TODO(yuzefovich): update unit tests to remove panic-catcher when fallback to rowexec is not allowed.`
___
*[pkg/sql/colexec/execplan.go, line 1525 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/48299#-M78e4yR6b2GqFaMU2pD:-M79N2uFAYPZTg1s14a3:b-ehus7p) ([raw file](https://github.com/cockroachdb/cockroach/blob/39cfab0bdfea4d6d3b38d8dbeac3ef228e91965f/pkg/sql/colexec/execplan.go#L1525)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

I've updated it instead. I think it's worth keeping since I think it was attempting to explain why we **negate** in the case of IS DISTINCT FROM, instead of IS **NOT** DISTINCT FROM, since that's a bit confusing. What do you think?
</blockquote></details>

Nice, good point.
___
*[pkg/sql/colexec/execplan.go, line 1680 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/48299#-M78cLlEBAhZLdaTpO5w:-M79N6UF5g5W_UbJpwGZ:bkw637s) ([raw file](https://github.com/cockroachdb/cockroach/blob/39cfab0bdfea4d6d3b38d8dbeac3ef228e91965f/pkg/sql/colexec/execplan.go#L1680)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

Happy to do so, but can you explain the reason? I made this change here and throughout the file because it was easier for me to reason about `resultIdx` being the index of the last element of the newly expanded `typs`. But I don't have the context of the rest of the `colexec` code.

Would you like me to revert all the places I've made a similar change in this file?
</blockquote></details>

I think adding `appendOneType` helper is very good idea, my comment was to have
```
resultIdx = len(typs) - 1
typs = appendOneType(typs, t.ResolvedType())
```
and not the other way around.

For some reason, it reads more "naturally" to me, but it's no big deal. It's up to you whether you wanna do this line switch throughout this file.

**Review by yuzefovich — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/48299)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @mgartner and @RaduBerinde)

___
*[pkg/sql/colexec/execplan.go, line 1680 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/48299#-M78cLlEBAhZLdaTpO5w:-M79OVneCa4DaSaXxxT3:b-90qkkt) ([raw file](https://github.com/cockroachdb/cockroach/blob/39cfab0bdfea4d6d3b38d8dbeac3ef228e91965f/pkg/sql/colexec/execplan.go#L1680)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

I think adding `appendOneType` helper is very good idea, my comment was to have
```
resultIdx = len(typs) - 1
typs = appendOneType(typs, t.ResolvedType())
```
and not the other way around.

For some reason, it reads more "naturally" to me, but it's no big deal. It's up to you whether you wanna do this line switch throughout this file.
</blockquote></details>

I guess the reason for my such preference is that in this file we tend to have the following pattern

```
result index assignment
operator creation
type schema update
```
for example
```
	outputIdx := len(columnTypes)
	op, err = GetCastOperator(colmem.NewAllocator(ctx, acc), input, inputIdx, outputIdx, fromType, toType)
	typs = appendOneType(columnTypes, toType)
```
We don't follow the pattern religiously though, so it's not a problem if we deviate from it.

**Review by mgartner — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/48299)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @RaduBerinde and @yuzefovich)

___
*[pkg/sql/colexec/execplan.go, line 1113 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/48299#-M78bL4d2FRlTk9apxLH:-M7E2E19AnPRlCEn_zVd:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/39cfab0bdfea4d6d3b38d8dbeac3ef228e91965f/pkg/sql/colexec/execplan.go#L1113)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

Got it, I agree it's a good idea to add this. Could you please leave this TODO here for me?
`TODO(yuzefovich): update unit tests to remove panic-catcher when fallback to rowexec is not allowed.`
</blockquote></details>

Done.
___
*[pkg/sql/colexec/execplan.go, line 1680 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/48299#-M78cLlEBAhZLdaTpO5w:-M7E2LRdE6L1rgZK2_hr:bdii4h8) ([raw file](https://github.com/cockroachdb/cockroach/blob/39cfab0bdfea4d6d3b38d8dbeac3ef228e91965f/pkg/sql/colexec/execplan.go#L1680)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

I guess the reason for my such preference is that in this file we tend to have the following pattern

```
result index assignment
operator creation
type schema update
```
for example
```
	outputIdx := len(columnTypes)
	op, err = GetCastOperator(colmem.NewAllocator(ctx, acc), input, inputIdx, outputIdx, fromType, toType)
	typs = appendOneType(columnTypes, toType)
```
We don't follow the pattern religiously though, so it's not a problem if we deviate from it.
</blockquote></details>

Thanks, this context was helpful. I've made the changes to follow this pattern.

**Review by mgartner — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/48299)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @RaduBerinde and @yuzefovich)

*[a discussion](https://reviewable.io/reviews/cockroachdb/cockroach/48299#-M7EJYbp0o0SdbizWc7R:-M7EJYbp0o0SdbizWc7S:b-njbx40) (no related file):*
@raduberinde I'm just now realizing that it appears that Postgres will normalize `(a, b) IS NULL` to `((a IS NULL) AND (b IS NULL))`. I'm wondering if it would simplify this change if we did something similar.

I _think_ we'd still need to parse the `IS NULL` into a `tree.IsNullExpr` to differentiate from a `IsNotDistinctFrom` comparison expr. But if we added normalization rules that removed the tuple completely, then `execbuilder` could avoid ever creating `tree.IsNullExpr` (it could panic if it ever saw a `opt.IsTupleNullOp`), and maybe we could remove a lot of the evaluation-related code in this PR (`eval.go`, `colexec`, etc.).

I'm curious what you think.

---

**Review by yuzefovich — APPROVED** [review]
> Reviewed 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/48299)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @RaduBerinde)

**Review by rytaft — APPROVED** [review]
:lgtm:  This looks like it was a lot of work!

> Reviewed 3 of 54 files at r2, 8 of 51 files at r3, 11 of 11 files at r6.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/48299#-:-M7G2dVcDLxKPDw3JZIq:bdxh2et)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @mgartner and @RaduBerinde)

*[a discussion](https://reviewable.io/reviews/cockroachdb/cockroach/48299#-M7EJYbp0o0SdbizWc7R:-M7G2Mjk8W17doFv7SBs:b-d8upji) (no related file):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

@raduberinde I'm just now realizing that it appears that Postgres will normalize `(a, b) IS NULL` to `((a IS NULL) AND (b IS NULL))`. I'm wondering if it would simplify this change if we did something similar.

I _think_ we'd still need to parse the `IS NULL` into a `tree.IsNullExpr` to differentiate from a `IsNotDistinctFrom` comparison expr. But if we added normalization rules that removed the tuple completely, then `execbuilder` could avoid ever creating `tree.IsNullExpr` (it could panic if it ever saw a `opt.IsTupleNullOp`), and maybe we could remove a lot of the evaluation-related code in this PR (`eval.go`, `colexec`, etc.).

I'm curious what you think.
</blockquote></details>

Removing the need for new execution code sounds like a good idea to me, but would be interested to hear @raduberinde's opinion. 

---
___
*[pkg/sql/opt/norm/fold_constants.go, line 69 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/48299#-M7FwL2m32q4UnEMm6co:-M7FwL2n5tBKVencBOMw:b45k9te) ([raw file](https://github.com/cockroachdb/cockroach/blob/0347d40a11abe1090050c03c1c95414f0650f8e1/pkg/sql/opt/norm/fold_constants.go#L69)):*
> ```Go
> }
> 
> // HasOneNullElement returns true if the input tuple has one constant, null
> ```

one -> at least one
___
*[pkg/sql/opt/norm/fold_constants.go, line 73 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/48299#-M7FwPpE8g-ndIkSTSkT:-M7FwPpFEdAuAKc9GMO-:bktvt4c) ([raw file](https://github.com/cockroachdb/cockroach/blob/0347d40a11abe1090050c03c1c95414f0650f8e1/pkg/sql/opt/norm/fold_constants.go#L73)):*
> ```Go
> // For example, given the tuple (1, x), it will return false because x is not
> // guaranteed to be null.
> func (c *CustomFuncs) HasOneNullElement(input opt.ScalarExpr) bool {
> ```

I'd change this to `HasNullElement`, since it can have more than one
___
*[pkg/sql/opt/norm/fold_constants.go, line 97 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/48299#-M7FwdYX91diPdCiyO81:-M7FwdYY5gKIeKt9FUHU:b45k9te) ([raw file](https://github.com/cockroachdb/cockroach/blob/0347d40a11abe1090050c03c1c95414f0650f8e1/pkg/sql/opt/norm/fold_constants.go#L97)):*
> ```Go
> }
> 
> // HasOneNonNullElement returns true if the input tuple has one constant,
> ```

one -> at least one
___
*[pkg/sql/opt/norm/fold_constants.go, line 101 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/48299#-M7FwfNV9hElF4ONq6NP:-M7FwfNV9hElF4ONq6NQ:bvu4s0d) ([raw file](https://github.com/cockroachdb/cockroach/blob/0347d40a11abe1090050c03c1c95414f0650f8e1/pkg/sql/opt/norm/fold_constants.go#L101)):*
> ```Go
> // be non-null. For example, given the tuple (NULL, x), it will return false
> // because x is not guaranteed to be non-null.
> func (c *CustomFuncs) HasOneNonNullElement(input opt.ScalarExpr) bool {
> ```

I'd change this to `HasNonNullElement` for the same reason as above
___
*[pkg/sql/opt/norm/fold_constants.go, line 104 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/48299#-M7FxFF2DvKhY2ENW72a:-M7FxFF2DvKhY2ENW72b:b-is1ff4) ([raw file](https://github.com/cockroachdb/cockroach/blob/0347d40a11abe1090050c03c1c95414f0650f8e1/pkg/sql/opt/norm/fold_constants.go#L104)):*
> ```Go
> 	tup := input.(*memo.TupleExpr)
> 	for _, e := range tup.Elems {
> 		if e.Op() != opt.NullOp && (opt.IsConstValueOp(e) || e.Op() == opt.TupleOp || e.Op() == opt.ArrayOp) {
> ```

Does it matter whether the tuple/array is constant (or has at least one non-null constant)?

edit: I saw that you have tests showing that it doesn't matter, so might be worth giving that example here.
___
*[pkg/sql/opt/norm/testdata/rules/comp, line 411 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/48299#-M7FyfdK5lik0z7KrV_m:-M7FyfdK5lik0z7KrV_n:bw6ij83) ([raw file](https://github.com/cockroachdb/cockroach/blob/0347d40a11abe1090050c03c1c95414f0650f8e1/pkg/sql/opt/norm/testdata/rules/comp#L411)):*
> ```
> 
> norm expect=FoldNonNullTupleIsTupleNull
> SELECT ((NULL, NULL), NULL) IS NULL AS r
> ```

So this is the same behavior as Postgres? Weird...
___
*[pkg/sql/opt/ops/scalar.opt, line 428 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/48299#-M7FzI-m5gNGbj7CO-jC:-M7FzI-n-6XZivufRjBt:blgrik7) ([raw file](https://github.com/cockroachdb/cockroach/blob/0347d40a11abe1090050c03c1c95414f0650f8e1/pkg/sql/opt/ops/scalar.opt#L428)):*
> ```
> 
> # Is maps to the IS NOT DISTINCT FROM operator which is equivalent to IS for
> # non-tuples.
> ```

Might be worth adding a pointer to the tuple-specific operators above
___
*[pkg/sql/opt/ops/scalar.opt, line 436 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/48299#-M7FzOEzBVhXRNMKQ_ib:-M7FzOF-6IRhjtKKweEk:b-7ropln) ([raw file](https://github.com/cockroachdb/cockroach/blob/0347d40a11abe1090050c03c1c95414f0650f8e1/pkg/sql/opt/ops/scalar.opt#L436)):*
> ```
> 
> # IsNot is the inverse of Is. It maps to the IS DISTINCT FROM operator which is
> # equivalent to IS NOT for non-tuples.
> ```

ditto
___
*[pkg/sql/sem/tree/testdata/eval/is, line 362 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/48299#-M7G25Yq9-DZX3qlto1m:-M7G25Yq9-DZX3qlto1n:b-sgz94j) ([raw file](https://github.com/cockroachdb/cockroach/blob/0347d40a11abe1090050c03c1c95414f0650f8e1/pkg/sql/sem/tree/testdata/eval/is#L362)):*
> ```
> false
> 
> # Tuple with no NULLS.
> ```

These tests make my brain hurt 😆

**Review by RaduBerinde — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/48299)* status: :shipit: complete! 2 of 0 LGTMs obtained (waiting on @mgartner)

*[a discussion](https://reviewable.io/reviews/cockroachdb/cockroach/48299#-M7EJYbp0o0SdbizWc7R:-M7GLiVrB9yVRK0hdQih:b-1fuz9x) (no related file):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

Removing the need for new execution code sounds like a good idea to me, but would be interested to hear @raduberinde's opinion. 
</blockquote></details>

^We talked offline - such a rule would only apply for static tuples, not those that are the result of a more complex scalar expression (e.g. inside a `case` or from a subquery).

Fantastic job! :lgtm_strong: Thanks for working through some tedious details!

[nit] I'd mention in the commit message that we execbuild to the simpler `IS (NOT) NULL` variants when we know they are equivalent.

---
___
*[pkg/sql/logictest/testdata/logic_test/check_constraints, line 334 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/48299#-M7GOH2sAUfnPD5QFZLH:-M7GOH2sAUfnPD5QFZLI:bds3i29) ([raw file](https://github.com/cockroachdb/cockroach/blob/0347d40a11abe1090050c03c1c95414f0650f8e1/pkg/sql/logictest/testdata/logic_test/check_constraints#L334)):*
> ```
> 
> statement ok
> CREATE TABLE t46675isnotnull (k int, a int, CHECK ((k, a) IS NOT NULL))
> ```

Nice test!
___
*[pkg/sql/opt/norm/fold_constants.go, line 73 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/48299#-M6HLAFJEKW81fZWO86F:-M7GPOeNARCbPjtk5Zx2:b-xyq8jg) ([raw file](https://github.com/cockroachdb/cockroach/blob/00258203d4656b0b97fbda11587f58e7eaadadc5/pkg/sql/opt/norm/fold_constants.go#L73)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

Correct. That is why we return false, since we cannot guarantee that all elements are NULL.
</blockquote></details>

:thumbsup: Great descriptions!
___
*[pkg/sql/opt/ops/scalar.opt, line 306 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/48299#-M7GOSzzD1F9IyI2u9Kv:-M7GOSzzD1F9IyI2u9Kw:b-1dfywx) ([raw file](https://github.com/cockroachdb/cockroach/blob/0347d40a11abe1090050c03c1c95414f0650f8e1/pkg/sql/opt/ops/scalar.opt#L306)):*
> ```
> 
> # IsTupleNull is the boolean expression with a tuple input that evaluates to
> # true if all elements in the tuple are null.
> ```

if the tuple is null or all the elements in the tuple are null.
___
*[pkg/sql/opt/ops/scalar.opt, line 313 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/48299#-M7GOWWX6PPEJO6kZhJ6:-M7GOWWYC91bqTJv6IHT:bxpg3p3) ([raw file](https://github.com/cockroachdb/cockroach/blob/0347d40a11abe1090050c03c1c95414f0650f8e1/pkg/sql/opt/ops/scalar.opt#L313)):*
> ```
> 
> # IsTupleNotNull is the boolean expression with a tuple input that evaluates to
> # true if all elements in the tuple are not null.
> ```

if the tuple is not null and all the elements are not null.
___
*[pkg/sql/sem/tree/expr.go, line 267 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/48299#-M7GMWPFB513QWz8Caiw:-M7GMWPFB513QWz8Caix:bardlnh) ([raw file](https://github.com/cockroachdb/cockroach/blob/0347d40a11abe1090050c03c1c95414f0650f8e1/pkg/sql/sem/tree/expr.go#L267)):*
> ```Go
> 
> // IsNullExpr represents an IS NULL expression.
> type IsNullExpr struct {
> ```

[nit] Mention that this is equivalent to `IS NOT DISTINCT FROM NULL`, except for tuples.
___
*[pkg/sql/sem/tree/expr.go, line 295 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/48299#-M7GMaaM1EZQiCvydzYW:-M7GMaaM1EZQiCvydzYX:b7ds6yy) ([raw file](https://github.com/cockroachdb/cockroach/blob/0347d40a11abe1090050c03c1c95414f0650f8e1/pkg/sql/sem/tree/expr.go#L295)):*
> ```Go
> 
> // IsNotNullExpr represents an IS NOT NULL expression.
> type IsNotNullExpr struct {
> ```

[nit] Mention that this is equivalent to `IS DISTINCT FROM NULL`, except for tuples.
___
*[pkg/sql/sem/tree/expr.go, line 482 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/48299#-M7GMuOo3rvfxg2yXV7p:-M7GMuOo3rvfxg2yXV7q:b-7mcfi9) ([raw file](https://github.com/cockroachdb/cockroach/blob/0347d40a11abe1090050c03c1c95414f0650f8e1/pkg/sql/sem/tree/expr.go#L482)):*
> ```Go
> func (node *ComparisonExpr) Format(ctx *FmtCtx) {
> 	opStr := node.Operator.String()
> 	if node.Operator == IsDistinctFrom && (node.Right == DBoolTrue || node.Right == DBoolFalse) {
> ```

[nit] Add a comment here explaining that IS / IS NOT are equivalent when the RHS is true/false and we prefer the easier to read variant. (and copy it to the corresponding code in pretty.go)

**Review by mgartner — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/48299)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @RaduBerinde, @rytaft, and @yuzefovich)

*[a discussion](https://reviewable.io/reviews/cockroachdb/cockroach/48299#-M7EJYbp0o0SdbizWc7R:-M7KciK97aq_tAiyTpxZ:b-hlc8bm) (no related file):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

^We talked offline - such a rule would only apply for static tuples, not those that are the result of a more complex scalar expression (e.g. inside a `case` or from a subquery).

Fantastic job! :lgtm_strong: Thanks for working through some tedious details!

[nit] I'd mention in the commit message that we execbuild to the simpler `IS (NOT) NULL` variants when we know they are equivalent.
</blockquote></details>

Thanks for the reviews!

---
___
*[pkg/sql/opt/norm/fold_constants.go, line 69 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/48299#-M7FwL2m32q4UnEMm6co:-M7K95Ws498VS1FHzUrf:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/0347d40a11abe1090050c03c1c95414f0650f8e1/pkg/sql/opt/norm/fold_constants.go#L69)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

one -> at least one
</blockquote></details>

Done.
___
*[pkg/sql/opt/norm/fold_constants.go, line 73 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/48299#-M7FwPpE8g-ndIkSTSkT:-M7K96nZCljScEdGbT-r:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/0347d40a11abe1090050c03c1c95414f0650f8e1/pkg/sql/opt/norm/fold_constants.go#L73)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

I'd change this to `HasNullElement`, since it can have more than one
</blockquote></details>

Done.
___
*[pkg/sql/opt/norm/fold_constants.go, line 97 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/48299#-M7FwdYX91diPdCiyO81:-M7K9MET8AXC1COgRtgO:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/0347d40a11abe1090050c03c1c95414f0650f8e1/pkg/sql/opt/norm/fold_constants.go#L97)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

one -> at least one
</blockquote></details>

Done.
___
*[pkg/sql/opt/norm/fold_constants.go, line 101 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/48299#-M7FwfNV9hElF4ONq6NP:-M7K9MqM-gar834srWKc:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/0347d40a11abe1090050c03c1c95414f0650f8e1/pkg/sql/opt/norm/fold_constants.go#L101)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

I'd change this to `HasNonNullElement` for the same reason as above
</blockquote></details>

Done.
___
*[pkg/sql/opt/norm/fold_constants.go, line 104 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/48299#-M7FxFF2DvKhY2ENW72a:-M7KGc3g-FXrP_GHtmM0:b82xqul) ([raw file](https://github.com/cockroachdb/cockroach/blob/0347d40a11abe1090050c03c1c95414f0650f8e1/pkg/sql/opt/norm/fold_constants.go#L104)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

Does it matter whether the tuple/array is constant (or has at least one non-null constant)?

edit: I saw that you have tests showing that it doesn't matter, so might be worth giving that example here.
</blockquote></details>

Correct. `(k, (NULL, NULL)) IS NULL` can be folded to false, because the `IS NULL` only cares after the first-level elements, not nested ones. An inner tuple will make this evaluate to false, regardless of its contents.

I've added some more commentary to try to make this more clear.
___
*[pkg/sql/opt/norm/testdata/rules/comp, line 411 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/48299#-M7FyfdK5lik0z7KrV_m:-M7KTdKRCt9q0fA2conX:b6z74y1) ([raw file](https://github.com/cockroachdb/cockroach/blob/0347d40a11abe1090050c03c1c95414f0650f8e1/pkg/sql/opt/norm/testdata/rules/comp#L411)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

So this is the same behavior as Postgres? Weird...
</blockquote></details>

Ya it's confusing. A tuple filled with NULLs is null, but a tuple filled with tuples filled with NULLs is not null.
___
*[pkg/sql/opt/ops/scalar.opt, line 306 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/48299#-M7GOSzzD1F9IyI2u9Kv:-M7KYLcJ0ZdC3ywFRln3:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/0347d40a11abe1090050c03c1c95414f0650f8e1/pkg/sql/opt/ops/scalar.opt#L306)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

if the tuple is null or all the elements in the tuple are null.
</blockquote></details>

Done.
___
*[pkg/sql/opt/ops/scalar.opt, line 313 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/48299#-M7GOWWX6PPEJO6kZhJ6:-M7KZ86w3aHqNvAFHBgY:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/0347d40a11abe1090050c03c1c95414f0650f8e1/pkg/sql/opt/ops/scalar.opt#L313)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

if the tuple is not null and all the elements are not null.
</blockquote></details>

Done.
___
*[pkg/sql/opt/ops/scalar.opt, line 428 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/48299#-M7FzI-m5gNGbj7CO-jC:-M7KZWJ4EgomF7k_lTwW:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/0347d40a11abe1090050c03c1c95414f0650f8e1/pkg/sql/opt/ops/scalar.opt#L428)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

Might be worth adding a pointer to the tuple-specific operators above
</blockquote></details>

Done.
___
*[pkg/sql/opt/ops/scalar.opt, line 436 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/48299#-M7FzOEzBVhXRNMKQ_ib:-M7KZYdx9zymasm9m_CI:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/0347d40a11abe1090050c03c1c95414f0650f8e1/pkg/sql/opt/ops/scalar.opt#L436)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.
___
*[pkg/sql/sem/tree/expr.go, line 267 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/48299#-M7GMWPFB513QWz8Caiw:-M7K_21SAImgBSAO33PE:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/0347d40a11abe1090050c03c1c95414f0650f8e1/pkg/sql/sem/tree/expr.go#L267)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

[nit] Mention that this is equivalent to `IS NOT DISTINCT FROM NULL`, except for tuples.
</blockquote></details>

Done.
___
*[pkg/sql/sem/tree/expr.go, line 295 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/48299#-M7GMaaM1EZQiCvydzYW:-M7K_2s79Vasm2ruDYaK:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/0347d40a11abe1090050c03c1c95414f0650f8e1/pkg/sql/sem/tree/expr.go#L295)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

[nit] Mention that this is equivalent to `IS DISTINCT FROM NULL`, except for tuples.
</blockquote></details>

Done.
___
*[pkg/sql/sem/tree/expr.go, line 482 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/48299#-M7GMuOo3rvfxg2yXV7p:-M7K_kHDDzKLm1psKIOS:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/0347d40a11abe1090050c03c1c95414f0650f8e1/pkg/sql/sem/tree/expr.go#L482)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

[nit] Add a comment here explaining that IS / IS NOT are equivalent when the RHS is true/false and we prefer the easier to read variant. (and copy it to the corresponding code in pretty.go)
</blockquote></details>

Done.
___
*[pkg/sql/sem/tree/testdata/eval/is, line 362 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/48299#-M7G25Yq9-DZX3qlto1m:-M7K_sTw5J_TfIa6mDkP:b4li6zw) ([raw file](https://github.com/cockroachdb/cockroach/blob/0347d40a11abe1090050c03c1c95414f0650f8e1/pkg/sql/sem/tree/testdata/eval/is#L362)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

These tests make my brain hurt 😆
</blockquote></details>

Haha, tell me about it...
