### PR TITLE
changefeedccl: fix mvcc_timestamp being zero when used with cdc queries

### LINKED ISSUE #146823: changefeedccl: mvcc_timestamp option produces unexpected output in cdc queries
The `mvcc_timestamp` option always results in a value of "0.0000000000" when used in a changefeed using cdc queries.

Example:
```
> create changefeed with mvcc_timestamp as select * from t;
-- outputs:
{"__crdb__": {"mvcc_timestamp": "0.0000000000"}, "a": "hi"}

-- vs
>  create changefeed for t with mvcc_timestamp;
{"after": {"a": "hi", "rowid": 1072370442457710593}, "mvcc_timestamp": "1747331887557930000.0000000000"}
```

`updated` does not appear to suffer from this same problem.

ref: https://cockroachlabs.slack.com/archives/C9TGBJB44/p1747330574825959

Jira issue: CRDB-50729

### PR DESCRIPTION
**Pull request by asg0451**
Fix a bug where the mvcc_timestamp was emitted as zero
when used with cdc queries.

Fixes: #146823

Release note (bug fix): The mvcc_timestamp is now
emitted correctly when used with cdc queries.

### CODE REVIEW

File: pkg/ccl/changefeedccl/changefeed_test.go [hunk 1]
```diff
@@ -11546,3 +11546,30 @@ func TestChangefeedAsSelectForEmptyTable(t *testing.T) {
...
+func TestChangefeedMVCCTimestampWithQueries(t *testing.T) {
+	defer leaktest.AfterTest(t)()
+	defer log.Scope(t).Close(t)
+
+	ctx := context.Background()
+
+	testFn := func(t *testing.T, s TestServer, f cdctest.TestFeedFactory) {
+		sqlDB := sqlutils.MakeSQLRunner(s.DB)
+		sqlDB.Exec(t, `CREATE TABLE foo (key INT PRIMARY KEY);`)
+		sqlDB.Exec(t, `INSERT INTO foo VALUES (1), (2), (3);`)
```
Comment (andyyang890) [inline pkg/ccl/changefeedccl/changefeed_test.go:11559]: nit: technically don't need 3 rows

File: pkg/ccl/changefeedccl/changefeed_test.go [hunk 2]
```diff
@@ -11546,3 +11546,30 @@ func TestChangefeedAsSelectForEmptyTable(t *testing.T) {
...
+		msgs, err := readNextMessages(ctx, feed, 1)
+		require.NoError(t, err)
+
+		var m map[string]any
+		require.NoError(t, gojson.Unmarshal(msgs[0].Value, &m))
+		ts := m["__crdb__"].(map[string]any)["mvcc_timestamp"].(string)
+		assertReasonableMVCCTimestamp(t, ts)
+	}
+
+	cdcTest(t, testFn, feedTestForceSink("kafka"))
```
Comment (andyyang890) [inline pkg/ccl/changefeedccl/changefeed_test.go:11574]: nit: remove sink restriction

**Review by andyyang890 — APPROVED** [review]
