### PR TITLE
sql: support partial indexes and user defined types

### LINKED ISSUE #51804: sql: allow user defined types in partial indexes
* Tests should be added throughout `sql` and `opt` to support user defined types
  * `opt/partialidx`
  * `logictest/testdata/partial_index`
* Backfill should follow this pattern: https://github.com/cockroachdb/cockroach/pull/51865/files#diff-008234c9a29752f8b897974c95348fa4
* Fix known issue with `type resolver:

```
root@127.0.0.1:64056/defaultdb> set experimental_partial_indexes=on;
SET

Time: 282µs

root@127.0.0.1:64056/defaultdb> set experimental_enable_enums=on;
SET

Time: 240µs

root@127.0.0.1:64056/defaultdb> CREATE TYPE bug_status AS ENUM ('new', 'open', 'closed');
CREATE TYPE

Time: 2.195ms

root@127.0.0.1:64056/defaultdb> create table t (a int, b bug_status, index (a) where b = 'new');
ERROR: type id 52 does not exist
SQLSTATE: 42704
```

### PR DESCRIPTION
**Pull request by mgartner**
#### schemaexpr: return serialized expressions from schemaexpr functions

This commit updates most public functions within `schemaexpr` that
return `tree.Expr` or `tree.TypedExpr` to return serialized expressions
instead. These functions perform type-checking by replacing
`tree.ColumnItem`s with `dummyColumn`s, which do not support evaluation
and should not be leaked outside of this package. Additionally, all the
callers of these functions require only serialized expressions. These
changes result in a more safe and better encapsulated API.

Note that there are two public functions in `schemaexpr` that return
`tree.TypeExpr`, `MakeComputedExprs` and `MakePartialIndexExprs`. The
expressions returned from these functions do no contain `dummyColumn`s
and they do support evaluation, so these are an exception.

This commit also renames `ColumnDescriptor.SQLString` to make it clear
that it does not serialize user defined types in a human-readable
format, and to avoid giving the impression that it is meant to adhere to
interfaces that require a `SQLString()` function, like
`ResolvableTypeReference`. The `schemaexpr.FormatColumnForDisplay`
function should be used to format a `ColumnDesciptor` in cases where
human-readability is required.

Release note: None

#### sql: format human-readable UDTs in partial index predicates

This commit fixes the formatting of partial indexes in `SHOW CREATE`
statements so that user defined types are human readable. Prior to this
change, values and type annotations within partial index predicates were
not human readable. For example, an `ENUM` within a partial index
predicate would be formatted as:

    INDEX i (a) WHERE b = b'\x40':::@52

The new `schemaexpr.FormatIndexForDisplay` function relies on a
`tree.SemaContext`'s type resolver to make both the `ENUM` value and
type annotation more user friendly:

    INDEX i (a) WHERE b = 'foo':::my_enum

Release note: None

#### sql: add tests for enums within partial index predicates

This commit adds tests to ensure that partial indexes remain consistent
when their predicates expressions reference user defined types.

Fixes #51804

Release note: None

### CODE REVIEW

File: pkg/sql/information_schema.go [hunk 1]
```diff
@@ -386,19 +386,19 @@ https://www.postgresql.org/docs/9.5/infoschema-columns.html`,
...
 					if err != nil {
 						return err
 					}
-					colDefault = tree.NewDString(tree.SerializeForDisplay(colExpr))
+					colDefault = tree.NewDString(colExpr)
 				}
 				colComputed := emptyString
 				if column.ComputeExpr != nil {
-					colExpr, err := schemaexpr.DeserializeTableDescExpr(ctx, &p.semaCtx, table, *column.ComputeExpr)
+					colExpr, err := schemaexpr.FormatExprForDisplayWithoutTypeAnnotations(ctx, table, *column.ComputeExpr, &p.semaCtx)
```
Comment (rohany) [inline pkg/sql/information_schema.go:397]: Why without type annotations here?

File: pkg/sql/logictest/testdata/logic_test/partial_index [hunk 2]
```diff
@@ -605,18 +605,90 @@ INSERT INTO k VALUES (1, 1), (6, 6)
...
 statement ok
 INSERT INTO k VALUES (1, 1), (7, 7)
 
-query II
+query II rowsort
 SELECT * FROM k@a_b_gt_5 WHERE b > 5
 ----
 7  7
 
+# Test partial indexes with an ENUM in the predicate.
```
Comment (rohany) [inline pkg/sql/logictest/testdata/logic_test/partial_index:620]: add a subtest

**Review by rohany — APPROVED** [review]
lgtm!

thanks for the cleanup along the way. I like returning strings from those functions -- it felt too weird to let these un evaluatable expressions lie around

File: pkg/sql/information_schema.go (hunk 1 above)
Comment (mgartner) [reply pkg/sql/information_schema.go:397]: If you look at the code this replaces, it serialized using `tree.AsString` rather than `tree.SerializeForDisplay`. We're using `FormatExprForDisplayWithoutTypeAnnotations` here to prevent regressing on these changes: https://github.com/cockroachdb/cockroach/pull/50502

Comment (rohany) [reply pkg/sql/information_schema.go:397]: Ah, forgot about that.

File: pkg/sql/logictest/testdata/logic_test/partial_index (hunk 2 above)
Comment (mgartner) [reply pkg/sql/logictest/testdata/logic_test/partial_index:620]: I added it, but what is the benefit? `pkg/sql/logictest/logic.go` doesn't explain much. Is it just the additional label on failures like: `---FAIL: TestLogic/local/partial_index/enum`. I can't seem to run only the tests in the subtest with `make test PKG='./pkg/sql/logictest' TESTS='TestLogic/local/partial_index/enum'`—it runs all the tests in the `partial_index` file.

Comment (rohany) [reply pkg/sql/logictest/testdata/logic_test/partial_index:620]: yeah the additional label, and you can run subtests with the `SUBTESTS=...` flag to the make testlogic incantation

**Comment by mgartner** [comment]
bors r=rohany
