### PR TITLE
ui: add checks for values

### LINKED ISSUE #99538: sql activity: TypeError: Cannot read properties of undefined (reading 'data')
**Describe the problem**

A type error was encountered on the SQL Activity page on serverless.

**To Reproduce**
User appears to have been on `/account` and then switched over to `/sql-activity` when a `TypeError` was thrown:
```
TypeError: Cannot read properties of undefined (reading 'data')
  at <anonymous> @ https://cockroachlabs.cloud/assets/admin-ui-22-2.3f732429d80a4fa60862.js:1495:18661
  at <anonymous> @ https://cockroachlabs.cloud/assets/admin-ui-22-2.3f732429d80a4fa60862.js:1380:1707
  at <anonymous> @ https://cockroachlabs.cloud/assets/admin-ui-22-2.3f732429d80a4fa60862.js:1380:1128
  at <anonymous> @ https://cockroachlabs.cloud/assets/admin-ui-22-2.3f732429d80a4fa60862.js:1380:1837
  at <anonymous> @ https://cockroachlabs.cloud/assets/admin-ui-22-2.3f732429d80a4fa60862.js:1380:1128
  at Function.mapToProps @ https://cockroachlabs.cloud/assets/admin-ui-22-2.3f732429d80a4fa60862.js:1662:2096
  at $e @ https://cockroachlabs.cloud/assets/common.f0b78a59b800a2132f9b.js:2569:8576
  at $e.mapToProps @ https://cockroachlabs.cloud/assets/common.f0b78a59b800a2132f9b.js:2569:8726
  at $e @ https://cockroachlabs.cloud/assets/common.f0b78a59b800a2132f9b.js:2569:8576
  at At @ https://cockroachlabs.cloud/assets/common.f0b78a59b800a2132f9b.js:2569:9952
```

**Additional data / screenshots**
- [DataDog error](https://cockroachlabs-prod.datadoghq.com/rum/explorer?query=%28%40view.name%3A%28%22%2Fcluster%2F%3Acluster%2Fdatabases%2F%3Adb%22%20OR%20%22%2Fcluster%2F%3Acluster%2Finsights%22%20OR%20%22%2Fcluster%2F%3Acluster%2Fsql-activity%22%20OR%20%22%2Fcluster%2F%3Acluster%2Fdatabases%2F%3Adb%2F%3Aschema%2F%3Atable%22%20OR%20%22%2Fcluster%2F%3Acluster%2Fdatabases%22%29%20OR%20%40view.error.count%3A%3E0%20%40view.name%3A%28%22%2Fcluster%2F%3Acluster%2Fdatabases%2F%3Adb%22%20OR%20%22%2Fcluster%2F%3Acluster%2Finsights%22%20OR%20%22%2Fcluster%2F%3Acluster%2Fsql-activity%22%20OR%20%22%2Fcluster%2F%3Acluster%2Fdatabases%2F%3Adb%2F%3Aschema%2F%3Atable%22%20OR%20%22%2Fcluster%2F%3Acluster%2Fdatabases%22%29%29%20%40type%3Aview&cols=&event=AgAAAYb_fCXI45Wt2gAAAAAAAAAYAAAAAEFZYl9mQ1hJQUFEQzdpZk40Wl9JY3U1TwAAACQAAAAAMDE4NmZmYmQtZmY2YS00MjE0LTkyODAtOTAyNjBmOTM5ZjA5&index=%2A&p_tab=issues&sort_by=%40view.error.count&sort_order=desc&type=rum&viz=stream&from_ts=1679313600000&to_ts=1679356800000&live=false)
- [DataDog Replay](https://cockroachlabs-prod.datadoghq.com/rum/replay/sessions/f821b6e1-6715-4613-a262-170f95dfd205?seed=537f5484-ec21-4f6d-825e-ca3843d96dba&ts=1679323572390&from=1679323572262)

**Environment:**
 - CockroachDB version: Cockroach Serverless
 - Server OS: Mac OS X 10.15.7

Jira issue: CRDB-25919

### LINKED ISSUE #99539: insights: cannot read properties of undefined (reading 'split')
**Describe the problem**

A type error was encountered on the SQL Activity page on serverless.

**To Reproduce**

I'm unable to view the replay but it appears that soon after a route change to `/insights`, the user encountered the following error:
```
TypeError: Cannot read properties of undefined (reading 'split')
  at q.isOptionSelected @ https://cockroachlabs.cloud/assets/admin-ui-22-2.3f732429d80a4fa60862.js:1495:5832
  at <anonymous> @ https://cockroachlabs.cloud/assets/admin-ui-22-2.3f732429d80a4fa60862.js:1495:7241
  at Array.map @ <anonymous>
  at q.render @ https://cockroachlabs.cloud/assets/admin-ui-22-2.3f732429d80a4fa60862.js:1495:7197
  at Dl @ https://cockroachlabs.cloud/assets/common.29615ddb65bbd14ef358.js:2498:68424
  at Nl @ https://cockroachlabs.cloud/assets/common.29615ddb65bbd14ef358.js:2498:68203
  at Ji @ https://cockroachlabs.cloud/assets/common.29615ddb65bbd14ef358.js:2502:10265
  at fr @ https://cockroachlabs.cloud/assets/common.29615ddb65bbd14ef358.js:2502:996
  at He @ https://cockroachlabs.cloud/assets/common.29615ddb65bbd14ef358.js:2502:924
  at tn @ https://cockroachlabs.cloud/assets/common.29615ddb65bbd14ef358.js:2502:774
```
Based on the stack trace, it most likely has to do with either the txn or stmt insight selectors. `isOptionSelected` suggests it may be from a column selector.

**Additional data / screenshots**
- [DataDog error](https://cockroachlabs-prod.datadoghq.com/rum/explorer?query=%28%40view.name%3A%28%22%2Fcluster%2F%3Acluster%2Fdatabases%2F%3Adb%22%20OR%20%22%2Fcluster%2F%3Acluster%2Finsights%22%20OR%20%22%2Fcluster%2F%3Acluster%2Fsql-activity%22%20OR%20%22%2Fcluster%2F%3Acluster%2Fdatabases%2F%3Adb%2F%3Aschema%2F%3Atable%22%20OR%20%22%2Fcluster%2F%3Acluster%2Fdatabases%22%29%20OR%20%40view.error.count%3A%3E0%20%40view.name%3A%28%22%2Fcluster%2F%3Acluster%2Fdatabases%2F%3Adb%22%20OR%20%22%2Fcluster%2F%3Acluster%2Finsights%22%20OR%20%22%2Fcluster%2F%3Acluster%2Fsql-activity%22%20OR%20%22%2Fcluster%2F%3Acluster%2Fdatabases%2F%3Adb%2F%3Aschema%2F%3Atable%22%20OR%20%22%2Fcluster%2F%3Acluster%2Fdatabases%22%29%29%20%40type%3Aview&cols=&event=AgAAAYcRaE0s9JAHNwAAAAAAAAAYAAAAAEFZY1JhTFFnQUFBVGpBVGVrTFFva2dBQwAAACQAAAAAMDE4NzExYjgtY2FlOC00MzU1LWEzYjMtZGY2N2E4MmM3YjAy&index=%2A&p_tab=error_details&sort_by=%40view.error.count&sort_order=desc&type=rum&viz=stream&from_ts=1679616000000&to_ts=1679659200000&live=false)

**Environment:**
 - CockroachDB version: Cockroach Serverless
 - Server OS: Mac OS X 10.12.7

Jira issue: CRDB-25920

### LINKED ISSUE #99655: insights: TypeError: Cannot read properties of undefined (reading 'toString')
**Describe the problem**

A type error was encountered on the SQL Activity page on serverless.

**To Reproduce**

The user appears to have loaded the `/insights` page and the following error was encountered:
```
TypeError: Cannot read properties of undefined (reading 'toString')
  at <anonymous> @ https://cockroachlabs.cloud/assets/admin-ui-22-2.3f732429d80a4fa60862.js:1495:3486
  at Array.forEach @ <anonymous>
  at E @ https://cockroachlabs.cloud/assets/admin-ui-22-2.3f732429d80a4fa60862.js:1495:3439
  at <anonymous> @ https://cockroachlabs.cloud/assets/admin-ui-22-2.3f732429d80a4fa60862.js:1495:185370
  at fi @ https://cockroachlabs.cloud/assets/common.29615ddb65bbd14ef358.js:2502:7028
  at g.unstable_runWithPriority @ https://cockroachlabs.cloud/assets/common.29615ddb65bbd14ef358.js:2573:3960
  at vu @ https://cockroachlabs.cloud/assets/common.29615ddb65bbd14ef358.js:2498:39689
  at Zr @ https://cockroachlabs.cloud/assets/common.29615ddb65bbd14ef358.js:2502:6466
  at Ul @ https://cockroachlabs.cloud/assets/common.29615ddb65bbd14ef358.js:2500:11247
  at <anonymous> @ https://cockroachlabs.cloud/assets/common.29615ddb65bbd14ef358.js:2498:39915
```

**Additional data / screenshots**
- [DataDog error](https://cockroachlabs-prod.datadoghq.com/rum/explorer?query=%28%40view.name%3A%28%22%2Fcluster%2F%3Acluster%2Fdatabases%2F%3Adb%22%20OR%20%22%2Fcluster%2F%3Acluster%2Finsights%22%20OR%20%22%2Fcluster%2F%3Acluster%2Fsql-activity%22%20OR%20%22%2Fcluster%2F%3Acluster%2Fdatabases%2F%3Adb%2F%3Aschema%2F%3Atable%22%20OR%20%22%2Fcluster%2F%3Acluster%2Fdatabases%22%29%20OR%20%40view.error.count%3A%3E0%20%40view.name%3A%28%22%2Fcluster%2F%3Acluster%2Fdatabases%2F%3Adb%22%20OR%20%22%2Fcluster%2F%3Acluster%2Finsights%22%20OR%20%22%2Fcluster%2F%3Acluster%2Fsql-activity%22%20OR%20%22%2Fcluster%2F%3Acluster%2Fdatabases%2F%3Adb%2F%3Aschema%2F%3Atable%22%20OR%20%22%2Fcluster%2F%3Acluster%2Fdatabases%22%29%29%20%40view.name%3A%22%2Fcluster%2F%3Acluster%2Finsights%22%20%40type%3Aview&cols=&event=AgAAAYcT_8OBwW7D2gAAAAAAAAAYAAAAAEFZY1RfOE9CQUFBb2ZGYm5nb3lBbWdMZQAAACQAAAAAMDE4NzE0NTktMGIzYS00MzJjLWJjNzktOWQ4N2JhMTgyMWY3&index=%2A&p_tab=issues&sort_by=%40view.error.count&sort_order=desc&type=rum&viz=stream&from_ts=1679659200000&to_ts=1679702400000&live=false)
- [DataDog replay](https://cockroachlabs-prod.datadoghq.com/rum/replay/sessions/71b0f3ac-5ab9-4a4e-ba43-4e3f51cf07fa?seed=ca6cc757-c08e-4ea2-9193-86c3b93648c0&ts=1679667740771)

**Environment:**
 - CockroachDB version: Cockroach Serverless
- Server OS: Mac OS X 10.15.7

Jira issue: CRDB-26006

### PR DESCRIPTION
**Pull request by maryliag**
Fixes #99655
Fixes #99538
Fixes #99539

Add checks to usages that could cause
`Cannot read properties of undefined`.

Release note: None

### CODE REVIEW

**Review by gtr — APPROVED** [review]
:lgtm: Thanks!

> Reviewed 32 of 53 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/99962#-:-NRiiQOi13NvEq4kkzPM:b-g2a5fb)* status: :shipit: complete! 1 of 0 LGTMs obtained

File: pkg/ui/workspaces/db-console/src/redux/indexUsageStats/indexUsageStatsSagas.ts [hunk 1]
```diff
@@ -36,7 +36,7 @@ export const selectIndexStatsKeys = createSelector(
 );
 
 export const KeyToTableRequest = (key: string): TableIndexStatsRequest => {
-  const s = key.split("/");
+  const s = key?.split("/");
```
Comment (xinhaoz) [inline pkg/ui/workspaces/db-console/src/redux/indexUsageStats/indexUsageStatsSagas.ts:39]: IDK if this is the right way to approach addressing these issues. How come we can't track down where we actually might be reading `null` or `undefined` in the issues linked? Now we have issues where this will case `s` to be null, and we're accessing `s[0]` right below this.

I think there's a lint rule we can introduce that will warn us if we're reading a potentially null field. I'd prefer tracking down the cause in the issues linked, addressing just those, and then introducing the lint rule and fixing the problems that is flagged by that. WDYT?

Comment (maryliag) [reply pkg/ui/workspaces/db-console/src/redux/indexUsageStats/indexUsageStatsSagas.ts:39]: The error message itself doesn't have enough info that allow us to know what is the exact place of the error, so it would be a guess at this point, so this is why I added on some other places too. 
I can do another pass over all the code to make sure I didn't added on places that could cause an issue like the one you pointed.
We can add a lint for that, but the end result would still be adding the checks on all places. I will keep this PR focused on the check itself and look into the lint in another PR.

Comment (xinhaoz) [reply pkg/ui/workspaces/db-console/src/redux/indexUsageStats/indexUsageStatsSagas.ts:39]: Sounds good! I'd just like to avoid a world where we always use `?` even unnecessarily, instead of properly typing things as nullish / not nullish and respecting that. As long as something like this does not become the norm and it's just a bandaid for the existing issues.

**Comment by maryliag** [comment]
TFTR!
bors r+
