### PR TITLE
cluster-ui: misc v2 db pages styling adjustments

### LINKED ISSUE #132595: ui: db pages design alignment
This is a tracking issue for databases page fixes to reach design alignment.

---------------------------------------------------

Last Refresh should be aligned with the databases count text

Table Last refreshed message
- [x] Show relative time by default, move timestamp to tooltip
- [ ] Add docs link to https://www.cockroachlabs.com/docs/stable/ui-databases-page.html#refresh-data
- [ ] Refresh button hover state [Figma](https://www.figma.com/design/lBTLTVQlvBDi5JOiCPnx2i/CRDB-Design_System-CURRENT?m=auto&node-id=10126-17542&t=q38c9RWjjit9uPbj-1)
- [x] Add spinner icon when cached data is refreshing
- [x] Add job progress percent to hover state
- [x] 16px of spacing between table and pagination/last updated row
- [x] Error format change - 
```
Last refresh failed to retrieve data about this table. The data shown is as of [last updated timestamp].
Refresh error: [Error message]
```

Tables
- [x] “Table Count” column header -> “Tables”
- [x] Search input on focus border is clipped
- [x] Right align all number cells (size, tables)
- [x] Align actions / info outside of table area (last refreshed, reset index stats)

Breadcrumb
- [x] Add “database” suffix to the breadcrumb after DB name

Copy
- [x] % of Live data - change to current format 
- [x] correct hover text to “The number of ranges in the table.”
- [x] for consistency, add hover text to Columns (“The number of columns in the table.”) and Indexes (“The number of indexes in the table.”)

Grants
- [x] Remove header

Epic: CRDB-37558

Jira issue: CRDB-43171

### PR DESCRIPTION
**Pull request by xinhaoz**
ui: regions label adjustments

- Ensure the regions label text isn't condensed to
1 character per row by providing a min width.
- Remove unnecessary widths on tables

Epic: none
Release note: None

------------------------------------------------------------

cluster-ui: misc v2 db pages styling adjustments

Misc formatting
- Fix page heading font styling
- Fix search bar on focus border being cut off
- Add `database` suffix to breadcrumb for db details page
- Format live data percentage by adding `live data` and
`total` as suffixes to numerator / denom respectively
- Don't show db and table breadcrumb as not found when
data is still being loaded
- Put reset index action in row outside / on top of table
- Add spinner state to refresh button when cached data is
refreshing

Table last updated/refreshed message & tooltip:
- Align data last refreshed time with page count
- Move full timestamp in table metadata tooltip
- Better error message formatting
- Show job progress when running

Grants
- Remove "Grants" header

Epic: [CRDB-37558](https://cockroachlabs.atlassian.net/browse/CRDB-37558)
Fixes: https://github.com/cockroachdb/cockroach/issues/132595

Release note (ui change): In the v2 database and db details
pages, the refresh button tooltip will now include the cache
refresh progress when the job is running as well as when the
update started.

### CODE REVIEW

**Comment by xinhaoz** [comment]
Last refresh failed to retrieve data about this

Refreshing data

**Comment by xinhaoz** [comment]
https://www.loom.com/share/82791ea81fb443ba855a44e3898f6e58

File: pkg/ui/workspaces/cluster-ui/src/components/liveDataPercent/liveDataPercent.tsx [hunk 1]
```diff
@@ -0,0 +1,28 @@
...
+  // Float between 0-1.
+  liveBytes: number;
+  totalBytes: number;
+};
+
+export const LiveDataPercent: React.FC<Props> = ({ liveBytes, totalBytes }) => {
+  return (
+    <div>
+      <Row justify={"end"}>
+        {Percentage(liveBytes, liveBytes ? totalBytes : 1, 1)}
```
Comment (kyle-a-wong) [inline pkg/ui/workspaces/cluster-ui/src/components/liveDataPercent/liveDataPercent.tsx:21]: nit: Am I correct in saying that this is trying to handle the case where if liveBytes == 0, Percentage will return `0%` instead of `--%`? if so, maybe this will make that more clear:

```suggestion
        {liveBytes ? Percentage(liveBytes, totalBytes, 1) : '0%'}
```

File: pkg/ui/workspaces/cluster-ui/src/components/tableMetadataLastUpdated/tableMetadataJobProgress.tsx [hunk 2]
```diff
@@ -0,0 +1,40 @@
...
+
+import moment from "moment-timezone";
+import React from "react";
+
+import { Timestamp } from "src/timestamp";
+import { DATE_WITH_SECONDS_FORMAT_24_TZ } from "src/util";
+
+import styles from "./tableMetadataJobProgress.module.scss";
+
+// This message is displayed when the job is running.
```
Comment (kyle-a-wong) [inline pkg/ui/workspaces/cluster-ui/src/components/tableMetadataLastUpdated/tableMetadataJobProgress.tsx:14]: nit: What message is this referring to?

File: pkg/ui/workspaces/cluster-ui/src/databaseDetailsV2/index.tsx [hunk 3]
```diff
@@ -57,25 +57,23 @@ export const DatabaseDetailsPageV2 = () => {
...
+    data?.metadata.dbName ?? "Database Not Found"
+  );
 
   const breadCrumbItems = [
     { name: "Databases", link: DB_PAGE_PATH },
     {
-      name: dbName,
-      link: null,
+      name: <>Database: {dbName}</>,
+      link: "",
```
Comment (kyle-a-wong) [inline pkg/ui/workspaces/cluster-ui/src/databaseDetailsV2/index.tsx:70]: whats the difference between `null` and `""` for a link?

**Review by kyle-a-wong — APPROVED** [review]
Just a couple nits, but looks good overall

File: pkg/ui/workspaces/cluster-ui/src/databaseDetailsV2/index.tsx (hunk 3 above)
Comment (xinhaoz) [reply pkg/ui/workspaces/cluster-ui/src/databaseDetailsV2/index.tsx:70]: I was having issues with the typing of the prop passed which expected this to be a string value and not null. Providing the empty string will still remoce the link from the breadcrumb item.

**Comment by xinhaoz** [comment]
Failure is unrelated to UI pkg.
bors r+
