### PR TITLE
sql, ui: include distsql queries in `sql.{service,exec}.latency` metrics 

### LINKED ISSUE #31093: UI: Service latency appears to exclude DistSQL queries
**Describe the problem**

When troubleshooting a user's cluster, @vilterp and I observed that service latency appears to exclude distsql latency.

**To Reproduce**
Compare [internal statement statistics](https://docs.google.com/spreadsheets/d/19Yjg0-2Cu3edtohGrvJQ16QZsRmLPjoRIuDaaU9dJCs/edit?usp=sharing) (CRDB only) to the screenshot below.

screen shot 2018-10-08 at 2 17 27 pm

Note that roughly 1/3 of the queries in the internal_statement_statistics table had latency >1s, yet the sql p99 latency graph shows latency of ~100ms, while the distsql p99 latency shows 10s+.

**Expected behavior**
I'd expect that the Service Latency: SQL 99th percentile graph would average all statements. Instead, it appears to exclude distSQL queries.

**Environment:**
v2.0.6

### PR DESCRIPTION
**Pull request by vilterp**
Fixes #31093

Previously, the `sql.{service,exec}.latency` histogram metrics only
included local queries; distributed queries' latencies were recorded in
the `sql.distsql.{service,exec}.latency` metrics.

However, the UI had assumed that the `sql.service.latency` included all
SQL statements both local and distributed, and therefore had a graph of
it on the Overview dashboard, as well as having its most recent value
in the sidebar of the time series area.

With this change, the latencies of all statements are recorded in
`sql.{service,exec}.latency`, changing those metrics to mean what we had
assumed they meant. DistSQL queries will no longer be left out of this
prominent graph and sidebar metric.

Release note (admin ui change): The "service latency: {90,99}th
percentile" graphs on the Overview and SQL dashboard, as well as the P50
and P99 latency numbers in the time series area sidebar, now reflect
latencies of both local and distributed queries. Previously, they only
included local queries.

The second commit could also just remove those graphs entirely.

### CODE REVIEW

**Review by jordanlewis — APPROVED** [review]
LGTM, quick gut check from @andreimatei would be good too - maybe there's some reason why this wasn't done at first?

**Comment by andreimatei** [comment]
LGTM.
The changed code probably comes from a time where the engines were thoroughly distinct in the public psyche.

File: pkg/ui/src/views/cluster/containers/nodeGraphs/dashboards/sql.tsx [hunk 1]
```diff
@@ -138,7 +138,7 @@ export default function (props: GraphDashboardProps) {
     </LineGraph>,
 
     <LineGraph
-      title="Service Latency: DistSQL, 99th percentile"
+      title="Service Latency: Distributed SQL, 99th percentile"
```
Comment (couchand) [inline pkg/ui/src/views/cluster/containers/nodeGraphs/dashboards/sql.tsx]: I'd be in favor of just dropping these charts. @piyush-singh @Amruta-Ranade thoughts?

**Review by couchand — APPROVED** [review]

File: pkg/ui/src/views/cluster/containers/nodeGraphs/dashboards/sql.tsx (hunk 1 above)
Comment (vilterp) [reply pkg/ui/src/views/cluster/containers/nodeGraphs/dashboards/sql.tsx]: I agree. Given that you have the statements page if you want more of a breakdown, I don't think users really need this. The metric is still being recorded; it's accessible via the custom graph page.

Comment (piyush-singh) [reply pkg/ui/src/views/cluster/containers/nodeGraphs/dashboards/sql.tsx]: Agreed, especially since we have made a concerted effort to remove language that mentions DistSQL elsewhere. Good to remove on my end!

Comment (vilterp) [reply pkg/ui/src/views/cluster/containers/nodeGraphs/dashboards/sql.tsx]: Cool, thanks. They're gone!

**Comment by vilterp** [comment]
bors r+

Doubt that the `TestStoreRangeMergeWatcher` failure is related to this.
