### PR TITLE
kvstorage: assert each engine only access its spans

### LINKED ISSUE #158281: kvserver: key assertions in all state/raft engine accesses
In #156537, we added engine key assertions in a couple of request evaluation code paths, and confirmed that there are no new exceptions there. There are a lot more places where we access engines separately and want to be sure that we don't access keys from a wrong engine.

All these places use one of the `Store.{State,Log}Engine()` methods (see WIP #97627). It might be infeasible to keep doing the same "forbidden keys" assertion wrapping [#157153] at these many call sites, but we can hide this inside two specialized `storage.Engine` implementations returned by `{State,Log}Engine()`. This would automatically cover all cases.

Note that we don't yet have a raft engine key assertions. This issue also implies adding them.

Epic: CRDB-55220
Jira issue: CRDB-57216

### PR DESCRIPTION
**Pull request by iskettaneh**
The commit adds engine assertions to assert that Log engine only accesses log engine spans, and state engine only accesses state engine spans.

Fixes: https://github.com/cockroachdb/cockroach/issues/158281

Release notes: None

### CODE REVIEW

File: pkg/kv/kvserver/spanset/engine.go [hunk 1]
```diff
@@ -0,0 +1,287 @@
...
+	"github.com/cockroachdb/cockroach/pkg/storage/enginepb"
+	"github.com/cockroachdb/cockroach/pkg/storage/fs"
+	"github.com/cockroachdb/cockroach/pkg/util/hlc"
+	"github.com/cockroachdb/pebble"
+	"github.com/cockroachdb/pebble/metrics"
+)
+
+// SpanSetEngine wraps an Engine and asserts that it does not access spans that
+// do not belong to it.
+type SpanSetEngine struct {
```
Comment (pav-kv) [inline pkg/kv/kvserver/spanset/engine.go]: No need to export?

**Review by RaduBerinde — COMMENTED** [review]
> @RaduBerinde made 4 comments.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/160043)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @iskettaneh, @jbowens, and @pav-kv).

___
*[`pkg/storage/engine.go` line 926 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/160043#-OhB636H2MI_iRHzNOSP:-OhB636H2MI_iRHzNOSQ:bq602ex) ([raw file](https://github.com/cockroachdb/cockroach/blob/62fe51a0f701f7f83b678e95178426a4ffdcce80/pkg/storage/engine.go#L926)):*
> ```Go
> 
> // EngineWithoutRW is the interface that wraps the engine functions.
> type EngineWithoutRW interface {
> ```

[nit] I don't think this interface is very useful.. The wrapper can just not use the Reader/Writer functionality.
___
*[`pkg/kv/kvserver/kvstorage/storage.go` line 129 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/160043#-OhBCaDZ8sDuypBA9BWf:-OhBCaDZ8sDuypBA9BWg:b-uppkd2) ([raw file](https://github.com/cockroachdb/cockroach/blob/61ec9a6fd195bd898ad90b8dfa252ed44f350b5b/pkg/kv/kvserver/kvstorage/storage.go#L129)):*
> ```Go
> // engine reside in the same physical engine.
> func MakeEngines(eng storage.Engine) Engines {
> 	if util.RaceEnabled {
> ```

Should this be `buildutil.CrdbTestBuild`? Race gets much more limited coverage (e.g. nothing in roachtests)
___
*[`pkg/kv/kvserver/spanset/engine.go` line 23 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/160043#-OhB6hs_2iv4JsmQdnOK:-OhB6hs_2iv4JsmQdnOL:brwokyx) ([raw file](https://github.com/cockroachdb/cockroach/blob/62fe51a0f701f7f83b678e95178426a4ffdcce80/pkg/kv/kvserver/spanset/engine.go#L23)):*
> ```Go
> // do not belong to it.
> type SpanSetEngine struct {
> 	storage.Reader
> ```

[nit] It would be more clear if we just embedded the `ReadWriter` (from this package) and initialized it with `makeSpanSetReadWriterAt`
___
*[`pkg/kv/kvserver/spanset/engine.go` line 39 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/160043#-OhB7HYJ3nNpamfn-iJb:-OhB7HYJ3nNpamfn-iJc:b2e1m0e) ([raw file](https://github.com/cockroachdb/cockroach/blob/62fe51a0f701f7f83b678e95178426a4ffdcce80/pkg/kv/kvserver/spanset/engine.go#L39)):*
> ```Go
> 	return &SpanSetEngine{
> 		e:      engine,
> 		Reader: NewReader(engine, spans, hlc.Timestamp{}),
> ```

[nit] It should be enough to create a reader-writer

**Review by pav-kv — COMMENTED** [review]
> @pav-kv made 1 comment.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/160043)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @iskettaneh, @jbowens, and @RaduBerinde).

___
*[`pkg/storage/engine.go` line 926 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/160043#-OhB636H2MI_iRHzNOSP:-OhBFg_s-PflkzmWgeff:bwcnlqo) ([raw file](https://github.com/cockroachdb/cockroach/blob/62fe51a0f701f7f83b678e95178426a4ffdcce80/pkg/storage/engine.go#L926)):*
> The wrapper can just not use the Reader/Writer functionality.

In what sense? A lot of code passes around `Engine` as `Reader/Writer`. In those places where `engines.LogEngine()` or `engines.StateEngine()` is transparently converted to `Reader/Writer`, we would like the wrapped readers and writers.

**Review by iskettaneh — COMMENTED** [review]
> @iskettaneh made 2 comments and resolved 2 discussions.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/160043)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @jbowens, @pav-kv, and @RaduBerinde).

___
*[`pkg/kv/kvserver/kvstorage/storage.go` line 129 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/160043#-OhBCaDZ8sDuypBA9BWf:-OhBN51xBCVvywgHAO6A:b-wu5nbb) ([raw file](https://github.com/cockroachdb/cockroach/blob/61ec9a6fd195bd898ad90b8dfa252ed44f350b5b/pkg/kv/kvserver/kvstorage/storage.go#L129)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

Should this be `buildutil.CrdbTestBuild`? Race gets much more limited coverage (e.g. nothing in roachtests)
</blockquote></details>

I am following the same pattern that we do for Batch Eval assertions. But I get your point. I could leave a TODO to do that and make sure that it doesn't cause any test regressions due to the extra assertions. But I am not very worried because a lot of our "unit" tests use a full testCluster, which is a full CRDB cluster running locally. 
___
*[`pkg/storage/engine.go` line 926 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/160043#-OhB636H2MI_iRHzNOSP:-OhBNlmZ6zVp9k7WZGxR:b-75c2x7) ([raw file](https://github.com/cockroachdb/cockroach/blob/62fe51a0f701f7f83b678e95178426a4ffdcce80/pkg/storage/engine.go#L926)):*
<details><summary><i>Previously, pav-kv (Pavel Kalinnikov) wrote…</i></summary><blockquote>

> The wrapper can just not use the Reader/Writer functionality.

In what sense? A lot of code passes around `Engine` as `Reader/Writer`. In those places where `engines.LogEngine()` or `engines.StateEngine()` is transparently converted to `Reader/Writer`, we would like the wrapped readers and writers.
</blockquote></details>

Also, we already have SpansetReader and SpansetWriter (which has reader/writer assertions), and we didn't want to reimplement them here.

**Review by iskettaneh — COMMENTED** [review]
> @iskettaneh made 1 comment.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/160043)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @jbowens, @pav-kv, and @RaduBerinde).

___
*[`pkg/storage/engine.go` line 926 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/160043#-OhB636H2MI_iRHzNOSP:-OhBRWma4-Dr38hS841p:b-3it4lp) ([raw file](https://github.com/cockroachdb/cockroach/blob/62fe51a0f701f7f83b678e95178426a4ffdcce80/pkg/storage/engine.go#L926)):*
<details><summary><i>Previously, iskettaneh wrote…</i></summary><blockquote>

Also, we already have SpansetReader and SpansetWriter (which has reader/writer assertions), and we didn't want to reimplement them here.
</blockquote></details>

I see what happened! Initially when I was prototyping this change, I anonymous embedded Engine and ReadWriter fields. This caused a conflict. However, now that I only anonymous embedded the ReadWriter, there is no duplicate and I can keep the Engine interface unchanged. Thanks for pointing this out.

File: pkg/kv/kvserver/spanset/engine.go [hunk 2]
```diff
@@ -0,0 +1,285 @@
...
+	storage.ReadWriter
```
Comment (pav-kv) [inline pkg/kv/kvserver/spanset/engine.go]: We can also embed the local `ReadWriter` here directly (like all other composed types in this package), and init it with the "make" function?

File: pkg/kv/kvserver/spanset/engine.go [hunk 3]
```diff
@@ -0,0 +1,285 @@
...
+	"github.com/cockroachdb/cockroach/pkg/storage/enginepb"
+	"github.com/cockroachdb/cockroach/pkg/storage/fs"
+	"github.com/cockroachdb/cockroach/pkg/util/hlc"
+	"github.com/cockroachdb/pebble"
+	"github.com/cockroachdb/pebble/metrics"
+)
+
+// SpanSetEngine wraps an Engine and asserts that it does not access spans that
+// do not belong to it.
+type SpanSetEngine struct {
```
Comment (pav-kv) [inline pkg/kv/kvserver/spanset/engine.go]: Do we need to export this? `NewSpanSetEngine` hides it behind an interface. There is some conversion outside the package, but I suggested there how to avoid.

File: pkg/kv/kvserver/spanset/engine.go [hunk 4]
```diff
@@ -0,0 +1,285 @@
...
+
+// NewSpanSetEngine creates a new SpanSetEngine wrapper.
+func NewSpanSetEngine(engine storage.Engine) storage.Engine {
+	spans := &SpanSet{}
+	// For engines, we disable undeclared access assertions as we only care about
+	// preventing access to spans that don't belong to this engine.
+	spans.DisableUndeclaredAccessAssertions()
+	return &SpanSetEngine{
+		e:          engine,
+		ReadWriter: NewReadWriter(engine, spans),
```
Comment (pav-kv) [inline pkg/kv/kvserver/spanset/engine.go]: nit: match the declaration order

File: pkg/kv/kvserver/kvstorage/storage.go [hunk 5]
```diff
@@ -121,8 +126,20 @@ type Engines struct {
 // MakeEngines creates an Engines handle in which both state machine and log
 // engine reside in the same physical engine.
 func MakeEngines(eng storage.Engine) Engines {
-	// TODO(#158281): in test builds, wrap the engines in a way that allows
-	// verifying that all accesses touch the correct subset of keys.
+	if util.RaceEnabled {
+		// Wrap the engines with span set engines to catch incorrect engine
+		// accesses.
+		wrappedStateEngine := spanset.NewSpanSetEngine(eng)
+		wrappedStateEngine.(*spanset.SpanSetEngine).AddForbiddenMatcher(validateIsStateEngineSpan)
```
Comment (pav-kv) [inline pkg/kv/kvserver/kvstorage/storage.go]: Make `NewSpanSetEngine` return the raw type, instead of casting?

Alternatively (better I think), pass the validator into `NewSpanSetEngine`. This wrapper is a no-op without a validator, so one can say it's required to provide one as part of this engine creation.

File: pkg/kv/kvserver/spanset/batch.go [hunk 6]
```diff
@@ -975,6 +975,19 @@ func DisableReaderAssertions(reader storage.Reader) storage.Reader {
 	}
 }
 
+// DisableWriterAssertions unwraps any storage.Writer implementations that may
+// assert access against a given SpanSet.
+func DisableWriterAssertions(writer storage.Writer) storage.Writer {
+	switch v := writer.(type) {
+	case spanSetWriter:
+		return DisableWriterAssertions(v.w)
+	case *spanSetBatch:
```
Comment (pav-kv) [inline pkg/kv/kvserver/spanset/batch.go]: Bit weird that one is a pointer, another one is by value. Does it have to do with how we define methods on those types (receiver being pointer or value)?

Maybe something can be TODOne to unify.

File: pkg/kv/kvserver/spanset/batch.go [hunk 7]
```diff
@@ -975,6 +975,19 @@ func DisableReaderAssertions(reader storage.Reader) storage.Reader {
 	}
 }
 
+// DisableWriterAssertions unwraps any storage.Writer implementations that may
+// assert access against a given SpanSet.
+func DisableWriterAssertions(writer storage.Writer) storage.Writer {
+	switch v := writer.(type) {
```
Comment (pav-kv) [inline pkg/kv/kvserver/spanset/batch.go:987]: Do we catch the `spanSetWriteBatch` here?

File: pkg/kv/kvserver/spanset/batch.go [hunk 8]
```diff
@@ -994,10 +1007,24 @@ func DisableReadWriterAssertions(rw storage.ReadWriter) storage.ReadWriter {
 // wrapper with the latch assertion disabled.
 func DisableUndeclaredSpanAssertions(rw storage.ReadWriter) storage.ReadWriter {
 	switch v := rw.(type) {
+	case *storage.OpLoggerBatch:
```
Comment (pav-kv) [inline pkg/kv/kvserver/spanset/batch.go]: Is this fix related to the PR, or a drive-by?

**Review by pav-kv — COMMENTED** [review]
Looks good, dumping comments for now. Need to look more carefully at the second commit again.

File: pkg/kv/kvserver/kvstorage/storage.go (hunk 5 above)
Comment (iskettaneh) [reply pkg/kv/kvserver/kvstorage/storage.go]: Done.

File: pkg/kv/kvserver/spanset/batch.go (hunk 7 above)
Comment (iskettaneh) [reply pkg/kv/kvserver/spanset/batch.go:987]: Good catch. I made this to fix this test: TestDestroyReplica, and I realized that I didn't fix it (now it's fixed)

File: pkg/kv/kvserver/spanset/batch.go (hunk 6 above)
Comment (iskettaneh) [reply pkg/kv/kvserver/spanset/batch.go]: Agreed. This was the state of these functions before doing this work. I left a TODO to address it.

File: pkg/kv/kvserver/spanset/batch.go (hunk 8 above)
Comment (iskettaneh) [reply pkg/kv/kvserver/spanset/batch.go]: This is related to the PR. In the replica_write, we first get the Batch (now includes the forbidden assertions), then we wrap it by OpLoggerBatch, then we wrap it by the spanset batch (for undeclared assertions).

File: pkg/kv/kvserver/spanset/engine.go (hunk 3 above)
Comment (iskettaneh) [reply pkg/kv/kvserver/spanset/engine.go]: Good point. This will make it similar to the other SpanSet types. Done!

File: pkg/kv/kvserver/spanset/engine.go (hunk 2 above)
Comment (iskettaneh) [reply pkg/kv/kvserver/spanset/engine.go]: What do you mean by embed the local `ReadWriter`? I am doing it this way (anonymously) to avoid reimplementing all readers and writers functions

**Review by iskettaneh — COMMENTED** [review]
> @iskettaneh made 6 comments and resolved 1 discussion.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/160043)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @jbowens, @pav-kv, and @RaduBerinde).

File: pkg/kv/kvserver/spanset/engine.go (hunk 2 above)
Comment (pav-kv) [reply pkg/kv/kvserver/spanset/engine.go]: Yeah, I mean do the same but use a concrete type which we're using here (which also implements `storage.ReadWriter`):

```golang
type SpanSetEngine struct {
	ReadWriter // our package's ReadWriter
	...
}
```

File: pkg/kv/kvserver/spanset/engine.go [hunk 9]
```diff
@@ -0,0 +1,291 @@
...
+		e:          engine,
+		spans:      spans,
+	}
+}
+
+// AddForbiddenMatcher adds a forbidden matcher to the underlying SpanSet.
+func (s *spanSetEngine) AddForbiddenMatcher(matcher func(TrickySpan) error) {
+	s.spans.AddForbiddenMatcher(matcher)
+}
```
Comment (pav-kv) [inline pkg/kv/kvserver/spanset/engine.go]: Probably not needed now that we pass the matchers to the constructor. Easy to add later if needed.

File: pkg/kv/kvserver/kvstorage/storage.go [hunk 10]
```diff
@@ -121,8 +126,18 @@ type Engines struct {
 // MakeEngines creates an Engines handle in which both state machine and log
 // engine reside in the same physical engine.
 func MakeEngines(eng storage.Engine) Engines {
-	// TODO(#158281): in test builds, wrap the engines in a way that allows
-	// verifying that all accesses touch the correct subset of keys.
+	if util.RaceEnabled {
+		// Wrap the engines with span set engines to catch incorrect engine
+		// accesses.
+		wrappedStateEngine := spanset.NewSpanSetEngine(eng, validateIsStateEngineSpan)
+		wrappedLogEngine := spanset.NewSpanSetEngine(eng, validateIsRaftEngineSpan)
```
Comment (pav-kv) [inline pkg/kv/kvserver/kvstorage/storage.go]: Final touch / brevity nits:

`spanset.NewEngine` (typical Go thing is to remove parts of the name that are already in the package name)

Also don't need the vars:

```golang
return Engines {
	stateEngine: spanset.NewEngine(eng, validateIsStateEngineSpan),
	logEngine:   spanset.NewEngine(eng, validateIsRaftEngineSpan),
	todoEngine:  eng,
}
```

Same below.

File: pkg/kv/kvserver/kvstorage/storage.go [hunk 11]
```diff
@@ -178,3 +205,128 @@ func (e *Engines) TODOEngine() storage.Engine {
 func (e *Engines) Separated() bool {
 	return e.separated
 }
+
+// validateIsStateEngineSpan asserts that the provided span only overlaps with
+// keys in the State engine and returns an error if not.
+// Note that we could receive the span with a nil startKey, which has a special
+// meaning that the span represents: [endKey.Prev(), endKey).
+func validateIsStateEngineSpan(span spanset.TrickySpan) error {
```
Comment (pav-kv) [inline pkg/kv/kvserver/kvstorage/storage.go:208]: Was this not merged yet? Rebase?

File: pkg/kv/kvserver/kvstorage/destroy_test.go [hunk 12]
```diff
@@ -139,7 +140,7 @@ func (r *replicaInfo) createStateMachine(ctx context.Context, t *testing.T, w st
 	// TODO(pav-kv): figure out whether LastReplicaGCTimestamp should be in the
 	// log or state engine.
 	require.NoError(t, storage.MVCCBlindPutProto(
-		ctx, w,
+		ctx, spanset.DisableWriterAssertions(w),
```
Comment (pav-kv) [inline pkg/kv/kvserver/kvstorage/destroy_test.go:143]: Oh nice, so this machinery did catch something :)

File: pkg/kv/kvserver/spanset/batch.go [hunk 13]
```diff
@@ -975,10 +975,26 @@ func DisableReaderAssertions(reader storage.Reader) storage.Reader {
...
 
+// DisableWriterAssertions unwraps any storage.Writer implementations that may
+// assert access against a given SpanSet.
+func DisableWriterAssertions(writer storage.Writer) storage.Writer {
+	switch v := writer.(type) {
+	case spanSetWriter:
+		return DisableWriterAssertions(v.w)
+	case *spanSetBatch:
+		return DisableWriterAssertions(v.spanSetWriter.w)
+	case *spanSetWriteBatch:
```
Comment (pav-kv) [inline pkg/kv/kvserver/spanset/batch.go:990]: nit: order cases from small to large (Writer, WriteBatch, Batch). A trick to not forget anything.

File: pkg/kv/kvserver/spanset/batch.go (hunk 8 above)
Comment (pav-kv) [reply pkg/kv/kvserver/spanset/batch.go]: Oof. How do we know we haven't missed anything here? Do we need to assume we know all the possible wrappers?

I wonder if there is any other robust way to do this.

> then we wrap it by the spanset batch (for undeclared assertions)

Are you saying we wrap into spanset types twice, with `OpLoggerBatch` in the middle? But then aren't we dropping the `OpLoggerBatch` from the chain when we ultimately return a fork of the bottom-most wrapper (or is it the topmost)?

Need a good comment somewhere.

File: pkg/kv/kvserver/spanset/batch.go [hunk 14]
```diff
@@ -994,10 +1010,24 @@ func DisableReadWriterAssertions(rw storage.ReadWriter) storage.ReadWriter {
 // wrapper with the latch assertion disabled.
 func DisableUndeclaredSpanAssertions(rw storage.ReadWriter) storage.ReadWriter {
 	switch v := rw.(type) {
+	case *storage.OpLoggerBatch:
+		// OpLoggerBatch embeds a storage.Batch.
+		result := DisableUndeclaredSpanAssertions(v.Batch)
+		return result
```
Comment (pav-kv) [inline pkg/kv/kvserver/spanset/batch.go]: nit: variable not needed, return

same below

File: pkg/kv/kvserver/kvstorage/storage.go (hunk 11 above)
Comment (pav-kv) [reply pkg/kv/kvserver/kvstorage/storage.go:208]: Ah got it, it's a move. No changes in it I guess?

File: pkg/kv/kvserver/kvstorage/storage.go (hunk 10 above)
Comment (iskettaneh) [reply pkg/kv/kvserver/kvstorage/storage.go]: Done.

File: pkg/kv/kvserver/kvstorage/storage.go (hunk 11 above)
Comment (iskettaneh) [reply pkg/kv/kvserver/kvstorage/storage.go:208]: Correct. No changes in it at all

File: pkg/kv/kvserver/spanset/batch.go (hunk 8 above)
Comment (iskettaneh) [reply pkg/kv/kvserver/spanset/batch.go]: A few comments about this:
1) How do we know if we haven't missed anything? Good question, but keep in mind that if we miss anything, we will "forget" to disable the assertion (not the opposite). So safety is still here. Worst thing that could happen is that a test fails, and we realize that we forgot some wrapper.
2) This is only temporary: Note that disabling forbidden spans is only temporary (we will eventually move all of the callers to their appropriate engine). Eventually, we will only have the disable undeclared spans calls. For these ones, we can drop the OpLoggerBatch because it will be wrapped by the undeclared span check last.
3) But then aren't we dropping the `OpLoggerBatch` from the chain? Good catch. I created a similar trick to what we have done before using a "shallowcopy"

So in summary I did the following:

1) I removed the `OpLoggerBatch` case from `DisableUndeclaredSpanAssertions `(similar to how it was before).
2) There is an existing TODO for `DisableForbiddenSpanAssertions` to fix all of its callers. After that, we can remove this function.
3) Fixed `OpLoggerBatch` being dropped when calling the `DisableForbiddenSpanAssertions`.

File: pkg/kv/kvserver/spanset/engine.go (hunk 2 above)
Comment (iskettaneh) [reply pkg/kv/kvserver/spanset/engine.go]: Oh I see. Done

File: pkg/kv/kvserver/spanset/engine.go (hunk 9 above)
Comment (iskettaneh) [reply pkg/kv/kvserver/spanset/engine.go]: Done.

File: pkg/kv/kvserver/kvstorage/destroy_test.go (hunk 12 above)
Comment (iskettaneh) [reply pkg/kv/kvserver/kvstorage/destroy_test.go:143]: Yes! It also caught the point span engine keys.

**Review by iskettaneh — COMMENTED** [review]
Thank you for the review!

> @iskettaneh made 7 comments and resolved 2 discussions.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/160043#-:-OhBtIuWBeoLexBTpNir:b-rrkdbt)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @jbowens, @pav-kv, and @RaduBerinde).

File: pkg/kv/kvserver/spanset/engine.go [hunk 15]
```diff
@@ -0,0 +1,289 @@
...
+) (total, remote, external uint64, _ error) {
+	if err := s.spans.CheckAllowed(SpanReadOnly, TrickySpan{Key: from, EndKey: to}); err != nil {
+		return 0, 0, 0, err
+	}
+	return s.e.ApproximateDiskBytes(from, to)
+}
+
+// NewSnapshot implements the storage.EngineWithoutRW interface.
+func (s *spanSetEngine) NewSnapshot(keyRanges ...roachpb.Span) storage.Reader {
+	return NewReader(s.e.NewSnapshot(keyRanges...), s.spans, hlc.Timestamp{})
```
Comment (pav-kv) [inline pkg/kv/kvserver/spanset/engine.go:128]: `CheckAllowed` in this one too?

File: pkg/kv/kvserver/spanset/engine.go [hunk 16]
```diff
@@ -0,0 +1,289 @@
...
+func (s *spanSetEngine) IngestLocalFilesToWriter(
+	ctx context.Context, paths []string, clearedSpans []roachpb.Span, writer storage.Writer,
+) error {
+	return s.e.IngestLocalFilesToWriter(ctx, paths, clearedSpans, writer)
+}
+
+// ScanStorageInternalKeys implements the storage.EngineWithoutRW interface.
+func (s *spanSetEngine) ScanStorageInternalKeys(
+	start, end roachpb.Key, megabytesPerSecond int64,
+) ([]enginepb.StorageInternalKeysMetrics, error) {
```
Comment (pav-kv) [inline pkg/kv/kvserver/spanset/engine.go:240]: `CheckAllowed` here?

File: pkg/kv/kvserver/spanset/engine.go [hunk 17]
```diff
@@ -0,0 +1,289 @@
...
+
+// IngestExternalFiles implements the storage.EngineWithoutRW interface.
+func (s *spanSetEngine) IngestExternalFiles(
+	ctx context.Context, external []pebble.ExternalFile,
+) (pebble.IngestOperationStats, error) {
+	return s.e.IngestExternalFiles(ctx, external)
+}
+
+// IngestLocalFilesToWriter implements the storage.EngineWithoutRW interface.
+func (s *spanSetEngine) IngestLocalFilesToWriter(
```
Comment (pav-kv) [inline pkg/kv/kvserver/spanset/engine.go:231]: We probably can't check much for the ingestions, but some things we can like `exciseSpan` and `clearedSpans` here. Do?

File: pkg/kv/kvserver/spanset/batch.go [hunk 18]
```diff
@@ -975,10 +975,26 @@ func DisableReaderAssertions(reader storage.Reader) storage.Reader {
 	}
 }
 
+// DisableWriterAssertions unwraps any storage.Writer implementations that may
+// assert access against a given SpanSet.
+func DisableWriterAssertions(writer storage.Writer) storage.Writer {
```
Comment (pav-kv) [inline pkg/kv/kvserver/spanset/batch.go:986]: I lost mental model for whether we want to disable only one type of assertion, or all. Seems different between various `Disable` helpers.

Also, do we need to support `OpLoggerBatch` in all, or one is sufficient?

Is the intention to support every possible combination/nesting of wrappers, or only the currently used ones?

File: pkg/kv/kvserver/spanset/batch.go [hunk 19]
```diff
@@ -1011,10 +1036,25 @@ func DisableUndeclaredSpanAssertions(rw storage.ReadWriter) storage.ReadWriter {
...
+		innerBatch := DisableForbiddenSpanAssertions(v.Batch).(storage.Batch)
+		return v.ShallowCopyWithBatch(innerBatch)
+
 	case *spanSetBatch:
 		newSnapSetBatch := v.shallowCopy()
 		newSnapSetBatch.spans.DisableForbiddenSpansAssertions()
+
+		// Recursively disable on the underlying batch in case there are
+		// nested spanSetBatches.
+		newSnapSetBatch.b = DisableForbiddenSpanAssertions(v.b).(storage.Batch)
```
Comment (pav-kv) [inline pkg/kv/kvserver/spanset/batch.go]: typo (pre-existing): `Snap` -> `Span`

File: pkg/kv/kvserver/spanset/batch.go [hunk 20]
```diff
@@ -1011,10 +1036,25 @@ func DisableUndeclaredSpanAssertions(rw storage.ReadWriter) storage.ReadWriter {
...
+		// Update the reader and writer to point to the recursively processed batch.
+		newSnapSetBatch.spanSetReader.r = newSnapSetBatch.b
+		newSnapSetBatch.spanSetWriteBatch.spanSetWriter.w = newSnapSetBatch.b
+		newSnapSetBatch.spanSetWriteBatch.wb = newSnapSetBatch.b
```
Comment (pav-kv) [inline pkg/kv/kvserver/spanset/batch.go]: unactionable, just comment: Took me a few minutes to comprehend this block. Probably there is a better abstraction (e.g. as suggested in previous PR could use a `make` func instead of a clone-and-modify concept).

File: pkg/kv/kvserver/spanset/batch.go (hunk 8 above)
Comment (pav-kv) [reply pkg/kv/kvserver/spanset/batch.go]: I haven't followed all the `OpLoggerBatch` logic, but I like both arguments about this being temporary and conservative.

**Review by pav-kv — APPROVED** [review]
LGTM, thanks for this work. Left a few small suggestions, and open questions which I don't think are blocking this PR.

If there is a way to somehow not employ knowledge of the `OpLogBatch`, it would be good (TODO?).

File: pkg/kv/kvserver/spanset/engine.go (hunk 17 above)
Comment (pav-kv) [reply pkg/kv/kvserver/spanset/engine.go:231]: Actually, `clearedSpans` will itself be written to a batch, which will already assert. So maybe skip this one. But the `exciseSpan` seems assertable.
