### PR TITLE
demo: fix `--global` with `--multitenant=true`

### LINKED ISSUE #135043: demo: cockroach demo with the experimental global flag hangs
**Describe the problem**

Attempting to run the following command seems to hang indefinitely:
```
./cockroach demo --global --nodes 9 --no-example-database --insecure
```

It only hangs on master. The command works fine on previous branches.

**To Reproduce**
On latest master, run `./cockroach demo --global --nodes 9 --no-example-database --insecure`. The command hangs indefinitely. Attempting to trace the problem, it looks like it runs into an issue while spinning the tenant servers. 

**Expected behavior**
The command should set up a simulated MR cluster.

Jira issue: CRDB-44336

### PR DESCRIPTION
**Pull request by shubhamdhama**
After the system tenant is running on all nodes, the initialization gets stuck after the `demoapp` tenant is running on node 1 and during the startup of tenant servers on other nodes. The logs show that node 1 was rejecting connection attempts made by the initializing SQL server for `demoapp` from nodes 2 and 3.

```log
kv/kvclient/kvtenant/connector.go:1019 ⋮ [n3,tenant-connector] 13444  error dialing tenant KV address ‹127.0.0.1:26362›: initial connection heartbeat failed: grpc: ‹connection error: desc = "transport: authentication handshake failed: read tcp 127.0.0.1:49534->127.0.0.1:26362: read: connection reset by peer"› [code 14/Unavailable]
```

This was because those connections didn't set the right header required by `delayingConn` on the listener side. The cause was that the `InjectedLatencyOracle` was passed down as `nil`, and due to this, the right dialer for those connections wasn't set up:
https://github.com/cockroachdb/cockroach/blob/5c0c6d3a29d77ae9d9dc381875eb03ba3c0a76f3/pkg/rpc/context.go#L1590-L1600

Why was it passed down as `nil`?

In the `demo_cluster.go`, the main startup/orchestrator function [`transientCluster.Start`](https://github.com/cockroachdb/cockroach/blob/86cd9acda8ba46ff245ac62e078a18816f3f89da/pkg/cli/democluster/demo_cluster.go#L391-L396) creates a tenant sequentially on all nodes while passing the right parameters, including the needed knob:
https://github.com/cockroachdb/cockroach/blob/86cd9acda8ba46ff245ac62e078a18816f3f89da/pkg/cli/democluster/demo_cluster.go#L565-L580

However, there is a race condition with the [monitor that watches](https://github.com/cockroachdb/cockroach/blob/c68c559859be738efead9971f5e11f62a8c69d06/pkg/server/server_controller.go#L203-L222) for tenant entries in the `system.tenants` table and starts the server on other nodes if they aren't running. This path gets its `testArgs` in [`testServer.PreStart`](https://github.com/cockroachdb/cockroach/blob/7f44c4912b3d8f385dc404571e3b74f72ac05247/pkg/server/testserver.go#L786-L804) using the `testServer.getSharedProcessDefaultTenantArgs` function, which not only misses copying the `InjectedLatencyOracle` but also uses the wrong tenant name, causing the problem of the wrong key name in `ts.topLevelServer.serverController.mu.testArgs[args.TenantName] = args`.

The fix here is simple, but we could also explore using a knob that would disable this monitor.

Fixes: #135043
Epic: none
Release note: none

### CODE REVIEW

File: pkg/base/test_server_args.go [hunk 1]
```diff
@@ -157,6 +157,8 @@ type TestServerArgs struct {
 	// below for alternative options that suits your test case.
 	DefaultTestTenant DefaultTestTenantOptions
 
+	DefaultTenantName roachpb.TenantName
```
Comment (shubhamdhama) [inline pkg/base/test_server_args.go:160]: I'll put some commentary here.

File: pkg/server/testserver.go [hunk 2]
```diff
@@ -645,6 +650,10 @@ func (ts *testServer) getSharedProcessDefaultTenantArgs() base.TestSharedProcess
 	if ts.params.Knobs.Server != nil {
 		args.Knobs.Server.(*TestingKnobs).DiagnosticsTestingKnobs = ts.params.Knobs.Server.(*TestingKnobs).DiagnosticsTestingKnobs
 		args.Knobs.LicenseTestingKnobs = ts.params.Knobs.LicenseTestingKnobs
+		args.Knobs.Server.(*TestingKnobs).ContextTestingKnobs.InjectedLatencyOracle =
+			ts.params.Knobs.Server.(*TestingKnobs).ContextTestingKnobs.InjectedLatencyOracle
+		args.Knobs.Server.(*TestingKnobs).ContextTestingKnobs.InjectedLatencyEnabled =
+			ts.params.Knobs.Server.(*TestingKnobs).ContextTestingKnobs.InjectedLatencyEnabled
```
Comment (shubhamdhama) [inline pkg/server/testserver.go:656]: This can be de-duplicated, but I'm also thinking of some extra minor extra refactor in separate PR. I'll share the link here.

**Review by stevendanna — APPROVED** [review]
I agree that it would perhaps be nice to solve the underlying race, but this seems like a good change regardless and does work around the problem.

Nice debugging here.

File: pkg/server/testserver.go [hunk 3]
```diff
@@ -1546,23 +1548,23 @@ func (ts *testServer) StartTenant(
...
+		if row == nil {
 			// Tenant doesn't exist. Create it.
 			if _, err := ie.Exec(
 				ctx, "testserver-create-tenant", nil /* txn */, "SELECT crdb_internal.create_tenant($1, $2)",
 				params.TenantID.ToUint64(), params.TenantName,
 			); err != nil {
 				return nil, err
 			}
-		} else if params.TenantName != "" {
+		} else if params.TenantName != "" && params.TenantName != roachpb.TenantName(tree.MustBeDString(row[0])) {
```
Comment (shubhamdhama) [inline pkg/server/testserver.go:1567]: Is this even used? Renaming tenant isn't supported in external mode.

File: pkg/server/testserver.go (hunk 2 above)
Comment (shubhamdhama) [reply pkg/server/testserver.go]: I end up doing this in this PR only

**Comment by shubhamdhama** [comment]
Thanks for the review!

bors r=stevendanna
