### PR TITLE
sql: TestRelocateNonVoters clean up learners before disabling all queues

### LINKED ISSUE #161363: sql: TestRelocateNonVoters failed [trying to add NON_VOTER to a store that already has a LEARNER]
sql.TestRelocateNonVoters [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Ci_TestsAwsLinuxArm64_UnitTests/20994170?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Ci_TestsAwsLinuxArm64_UnitTests/20994170?buildTab=artifacts#/) on release-26.1 @ [0fc80f178e797c71cd2e78958a27974352f65bae](https://github.com/cockroachdb/cockroach/commits/0fc80f178e797c71cd2e78958a27974352f65bae):

```
=== RUN   TestRelocateNonVoters
    test_log_scope.go:171: test logs captured to: /artifacts/tmp/_tmp/f4d1e5a362e4384d18c9c26e2defb957/logTestRelocateNonVoters1600281478
    test_log_scope.go:82: use -show-logs to present logs inline
    multitenant_admin_function_test.go:966: -- test log scope end --
test logs left over in: /artifacts/tmp/_tmp/f4d1e5a362e4384d18c9c26e2defb957/logTestRelocateNonVoters1600281478
--- FAIL: TestRelocateNonVoters (69.15s)
=== RUN   TestRelocateNonVoters/ALTER_RANGE_x_RELOCATE_NONVOTERS
    multitenant_admin_function_test.go:383: condition failed to evaluate within 45s: from multitenant_admin_function_test.go:420: expected "ok" to be contained in result "trying to add({ChangeType:ADD_NON_VOTER Target:n1,s1}) to a store that already has a LEARNER" tenant=secondary query=``ALTER RANGE (SELECT min(range_id) FROM [SHOW RANGES FROM TABLE t]) RELOCATE NONVOTERS FROM 5 TO 1;`` leaseholder=4 replicas=[2 3 4 5] voting_replicas=[2 3 4] non_voting_replicas=[5] fromReplica=5 toReplica=1 row=0 col=2
--- FAIL: TestRelocateNonVoters/ALTER_RANGE_x_RELOCATE_NONVOTERS (59.06s)
```
<details><summary>Help</summary>
<p>

See also: [How To Investigate a Go Test Failure \(internal\)](https://cockroachlabs.atlassian.net/l/c/HgfXfJgM)
</p>
</details>
/cc @cockroachdb/sql-foundations
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*TestRelocateNonVoters.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/bazci/githubpost/issues)

</sub>

Jira issue: CRDB-58824

### PR DESCRIPTION
**Pull request by shghasemi**
There are a couple of ways a learner can be left behind before this test disables all queues. Previously, the test would disable all queues without checking on the learners. This changes, allows for the test to wait for learners to be cleaned up.

Fixes: #161363

Release note: None

### CODE REVIEW

**Review by miraradeva — APPROVED** [review]
:lgtm: Thanks for fixing! Feel free to ping KV again if it continues to fail.

> @miraradeva reviewed 1 file and all commit messages, and made 2 comments.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/162342#-:-Ok_X05vAK_B-eeWGJOC:b-jep9yg)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @shghasemi).

___
*[`pkg/sql/multitenant_admin_function_test.go` line 938 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/162342#-Ok_WcFHA4WBi3X2pgyi:-Ok_WcFHA4WBi3X2pgyj:b1qxq9f) ([raw file](https://github.com/cockroachdb/cockroach/blob/2e7854012865d888dcc2d99df40a7c764115468d/pkg/sql/multitenant_admin_function_test.go#L938)):*
> ```Go
> 					require.NoErrorf(t, err, message)
> 					testutils.SucceedsSoon(t, func() error {
> 						// check for learners before disabling the replicate queues to allow cleanup of learners
> ```

nit: Can you make sure the comment matches the style guide? (Capital letter at the start of the sentence, full stop at the end, and wrap around at 80 characters.)

File: pkg/sql/multitenant_admin_function_test.go [hunk 1]
```diff
@@ -934,6 +934,21 @@ func TestRelocateNonVoters(t *testing.T) {
 					require.NoErrorf(t, err, message)
 					err = testCluster.WaitForFullReplication()
 					require.NoErrorf(t, err, message)
+					testutils.SucceedsSoon(t, func() error {
+						// check for learners before disabling the replicate queues to allow cleanup of learners
+						rows, err := db.QueryContext(ctx,
+							`SELECT learner_replicas FROM [SHOW RANGES FROM INDEX t@primary WITH DETAILS]`)
+						require.NoError(t, err)
```
Comment (rafiss) [inline pkg/sql/multitenant_admin_function_test.go]: when using SucceedsSoon, we need to avoid `require.NoError`. otherwise the retry wrapper won't actually retry in this case.

Comment (rafiss) [reply pkg/sql/multitenant_admin_function_test.go]: instead, return the error.

Comment (shghasemi) [reply pkg/sql/multitenant_admin_function_test.go]: done

**Review by rafiss — APPROVED** [review]
:lgtm: thanks!

> @rafiss made 1 comment.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/162342#-:-OkdgAhN2i2sLswnrOzT:brfqlux)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @miraradeva and @shghasemi).
