### PR TITLE
backupccl: fix incorrect schema ID used during object collision check

### LINKED ISSUE #93731: backupccl: TestDataDriven/in-progress-restores is flaky
Example build: https://teamcity.cockroachdb.com/viewLog.html?buildId=7977403&tab=buildResultsDiv&buildTypeId=Cockroach_UnitTests_BazelUnitTests

Error is `Expect "pq: referenced schema ID 109: descriptor is a *dbdesc.immutable: unexpected descriptor type" to match "pause point .* hit$"`

Jira issue: CRDB-22504
Epic CRDB-22861

### PR DESCRIPTION
**Pull request by adityamaru**
Previously, when restoring tables, we would use the schema ID in the backed
up table descriptor when checking if a table with the same name existed in
the db.schema we were about to restore to. The schema ID in the backed up table
descriptor could mean something entirely different in the restoring cluster.
In the red-green test added as part of this PR, the schema ID in the backed up
descriptor collides with the database ID in the restoring cluster. This results
in the collision check failing because it attempts to resolve a schema with an
ID corresponding to a database.

To fix this we tighten the rules for when we need to perform collission checks.
If the table is being restored into an existing schema in the restoring cluster,
then we check for a collission using the existing schema's ID. If the table is
being restored into a schema that is also being restored then we do not need to
perform any collission checks. A similar refactor is done for types as well.

Fixes: https://github.com/cockroachdb/cockroach/issues/93731

Release note (bug fix): restoring a backup with user defined schemas could occassionally
fail due to incorrect schema ID resolution

### CODE REVIEW

File: pkg/ccl/backupccl/restore_planning.go [hunk 1]
```diff
@@ -392,12 +392,28 @@ func allocateDescriptorRewrites(
...
-				if err != nil {
-					return err
+				//
+				// If we are restoring the table into a schema that is also being
+				// restored then we do not need to check for collisions as the backing
+				// up cluster would enforce uniqueness of table names in a schema.
+				rw, ok := descriptorRewrites[table.GetParentSchemaID()]
+				restoringIntoExistingSchema := ok && rw.ToExisting
+				isSystemTable := table.GetParentID() == keys.SystemDatabaseID &&
+					table.GetParentSchemaID() == keys.SystemPublicSchemaID
```
Comment (msbutler) [inline pkg/ccl/backupccl/restore_planning.go:406]: why check for both the `ParentID` and the `ParentSchemaID`?

File: pkg/ccl/backupccl/restore_planning.go [hunk 2]
```diff
@@ -392,12 +392,28 @@ func allocateDescriptorRewrites(
...
 				// This would fail the CPut later anyway, but this yields a prettier error.
-				tableName := tree.NewUnqualifiedTableName(tree.Name(table.GetName()))
-				err := descs.CheckObjectNameCollision(ctx, col, txn.KV(), parentID, table.GetParentSchemaID(), tableName)
-				if err != nil {
-					return err
+				//
+				// If we are restoring the table into a schema that is also being
+				// restored then we do not need to check for collisions as the backing
+				// up cluster would enforce uniqueness of table names in a schema.
+				rw, ok := descriptorRewrites[table.GetParentSchemaID()]
```
Comment (msbutler) [inline pkg/ccl/backupccl/restore_planning.go:403]: nit: rename `ok` to `restoringParentSchema`?

Comment (msbutler) [reply pkg/ccl/backupccl/restore_planning.go:403]: also, I think i'm confused: it seems we're conducting this collision check only if we're also restoring its schema which is in `descriptorRewrites`. That seems to contradict the comment above. We should only run the check if the table's schema's ID is _not_ in `descriptorRewrites`, correct?

**Review by msbutler — COMMENTED** [review]
if you refactor export request logic, I'll deal with this monster.

File: pkg/ccl/backupccl/restore_planning.go (hunk 1 above)
Comment (adityamaru) [reply pkg/ccl/backupccl/restore_planning.go:406]: Unfortunately, the system database still has a pseudo public schema, i.e. the schema is not backed by a descriptor and so it will not end up `descriptorRewrites`. If the table we are restoring is part of the system database and part of this pseudo schema we want to check for collisions. If for some reason, a UDS ended up in the system database then that would be in `descriptorRewrites` and it would be treated like any other regular schema.

File: pkg/ccl/backupccl/restore_planning.go (hunk 2 above)
Comment (adityamaru) [reply pkg/ccl/backupccl/restore_planning.go:403]: Both schemas that are being restored and existing schemas in the restoring cluster are in `descriptorRewrites`. The presence of the schema in `descriptorRewrites` is not what determines if we are going to create a new descriptor or map to an existing one. It is the `ToExisting` field on the rewrite that is used to determine this. Does that make sense?

**Review by msbutler — APPROVED** [review]
Thanks for the additional commentary!

I imagine it's quite hard to create a red-green test for the system table case-- did you add that special casing bc some other tests blow up without it?

**Comment by adityamaru** [comment]
> did you add that special casing bc some other tests blow up without it?

Yup `TestBackupRestoreSystemTables` has a subtest that exercises this.

**Comment by adityamaru** [comment]
TFTR!

bors r=msbutler

**Comment by adityamaru** [comment]
blathers backport 23.1 23.1.0
