### PR TITLE
roachtest: Fix random node selection logic in LDR Network Partition test

### LINKED ISSUE #128444: roachtest: ldr/kv0/workload=both/network_partition failed
roachtest.ldr/kv0/workload=both/network_partition [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyAzureBazel/16356876?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyAzureBazel/16356876?buildTab=artifacts#/ldr/kv0/workload=both/network_partition) on master @ [7917e91eadb2f622faadf635a3e13c384e42070e](https://github.com/cockroachdb/cockroach/commits/7917e91eadb2f622faadf635a3e13c384e42070e):

```
(test_runner.go:1309).runTest: test timed out (1h0m0s)
test artifacts and logs in: /artifacts/ldr/kv0/workload=both/network_partition/run_1
```

Parameters:
 - <code>ROACHTEST_arch=amd64</code>
 - <code>ROACHTEST_cloud=azure</code>
 - <code>ROACHTEST_coverageBuild=false</code>
 - <code>ROACHTEST_cpu=8</code>
 - <code>ROACHTEST_encrypted=false</code>
 - <code>ROACHTEST_fs=ext4</code>
 - <code>ROACHTEST_localSSD=false</code>
 - <code>ROACHTEST_metamorphicBuild=false</code>
 - <code>ROACHTEST_ssd=0</code>
<details><summary>Help</summary>
<p>

See: [roachtest README](https://github.com/cockroachdb/cockroach/blob/master/pkg/cmd/roachtest/README.md)

See: [How To Investigate \(internal\)](https://cockroachlabs.atlassian.net/l/c/SSSBr8c7)

_Grafana is not yet available for azure clusters_</p>
</details>
/cc @cockroachdb/disaster-recovery
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*ldr/kv0/workload=both/network_partition.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/bazci/githubpost/issues)
</sub>

Jira issue: CRDB-41018

### PR DESCRIPTION
**Pull request by navsetlur**
There was an edge case with selecting random nodes that would cause it to occasionally spin forever. Logic is fixed now.

Release note: none
Fixes: #128444

### CODE REVIEW

File: pkg/cmd/roachtest/option/node_list_option.go [hunk 1]
```diff
@@ -85,11 +85,14 @@ func (n NodeListOption) SeededRandList(rand *rand.Rand, size int) (NodeListOptio
 
 	nodes := make(map[int]struct{}, size)
 	for range size {
-		node := n[rand.Intn(len(n))]
-		for _, ok := nodes[node]; ok; {
-			node = n[rand.Intn(len(n))]
+		for {
```
Comment (renatolabs) [inline pkg/cmd/roachtest/option/node_list_option.go:88]: This function seems more complicated than it needs to be. Isn't the entire function equivalent to the following?

```go
nodes := append([]int{}, n...)
rand.Shuffle(len(nodes), func(i, j int) { nodes[i], nodes[j] = nodes[j], nodes[i] })
return nodes[:size]
```

Comment (navsetlur) [reply pkg/cmd/roachtest/option/node_list_option.go:88]: I'd say so. Didn't know about rand.shuffle, will fix

**Review by renatolabs — APPROVED** [review]

**Comment by navsetlur** [comment]
bors r=renatolabs
