### PR TITLE
roachtest: add delay after adding constraints.

### LINKED ISSUE #105505: roachtest: replicagc-changed-peers/restart=false failed
roachtest.replicagc-changed-peers/restart=false [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/10657405?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/10657405?buildTab=artifacts#/replicagc-changed-peers/restart=false) on master @ [7fd4c21157221eae9e7d5892d89d2b5a671aba3e](https://github.com/cockroachdb/cockroach/commits/7fd4c21157221eae9e7d5892d89d2b5a671aba3e):

```
(replicagc.go:209).waitForZeroReplicas: replica count on n3 didn't drop to zero: 3
(test_runner.go:1122).func1: 2 dead node(s) detected
test artifacts and logs in: /artifacts/replicagc-changed-peers/restart=false/run_1
```
<p>Parameters: <code>ROACHTEST_arch=amd64</code>
, <code>ROACHTEST_cloud=gce</code>
, <code>ROACHTEST_cpu=4</code>
, <code>ROACHTEST_encrypted=false</code>
, <code>ROACHTEST_ssd=0</code>
</p>
<details><summary>Help</summary>
<p>

See: [roachtest README](https://github.com/cockroachdb/cockroach/blob/master/pkg/cmd/roachtest/README.md)

See: [How To Investigate \(internal\)](https://cockroachlabs.atlassian.net/l/c/SSSBr8c7)

</p>
</details>
/cc @cockroachdb/replication
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*replicagc-changed-peers/restart=false.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)
</sub>

Jira issue: CRDB-29086

### LINKED ISSUE #105506: roachtest: replicagc-changed-peers/restart=true failed
roachtest.replicagc-changed-peers/restart=true [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/10657405?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/10657405?buildTab=artifacts#/replicagc-changed-peers/restart=true) on master @ [7fd4c21157221eae9e7d5892d89d2b5a671aba3e](https://github.com/cockroachdb/cockroach/commits/7fd4c21157221eae9e7d5892d89d2b5a671aba3e):

```
(replicagc.go:209).waitForZeroReplicas: replica count on n3 didn't drop to zero: 3
(test_runner.go:1122).func1: 2 dead node(s) detected
test artifacts and logs in: /artifacts/replicagc-changed-peers/restart=true/run_1
```
<p>Parameters: <code>ROACHTEST_arch=amd64</code>
, <code>ROACHTEST_cloud=gce</code>
, <code>ROACHTEST_cpu=4</code>
, <code>ROACHTEST_encrypted=false</code>
, <code>ROACHTEST_ssd=0</code>
</p>
<details><summary>Help</summary>
<p>

See: [roachtest README](https://github.com/cockroachdb/cockroach/blob/master/pkg/cmd/roachtest/README.md)

See: [How To Investigate \(internal\)](https://cockroachlabs.atlassian.net/l/c/SSSBr8c7)

</p>
</details>
/cc @cockroachdb/replication
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*replicagc-changed-peers/restart=true.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)
</sub>

Jira issue: CRDB-29087

### PR DESCRIPTION
**Pull request by andrewbaptist**
Fixes: #105506.
Fixes: #105505.

Add a delay after adding the constraints before recommissioning the
node. This allows the constraints to propagate to all nodes and avoids
replicas being added back to the node.

Epic: none

Release note: None

### CODE REVIEW

**Comment by andrewbaptist** [comment]
After adding the 1 min sleep, the test passed 10 times in a row. I don't think this test was intended to test constraint propagation and it will be less flakey going forward with this change.

File: pkg/cmd/roachtest/tests/replicagc.go [hunk 1]
```diff
@@ -271,6 +271,8 @@ func (h *replicagcTestHelper) isolateDeadNodes(ctx context.Context, runNode int)
 			h.t.Fatal(err)
 		}
 	}
+	// Wait to make sure the new constraints are read by all nodes.
+	time.Sleep(time.Minute)
```
Comment (kvoli) [inline pkg/cmd/roachtest/tests/replicagc.go:275]: Just checking this couldn't be made shorter? A minute seems like a long time.

**Review by kvoli — APPROVED** [review]

**Comment by andrewbaptist** [comment]
bors r=kvoli

TFTR. It takes ~30 sec until the constraints propagate to other nodes. I don't understand why it is taking this long, but I didn't want to leave this somewhat flakey by cutting it too close. I didn't look into where this is cached/sent from in detail.
