### PR TITLE
sql/schemachanger: create partial index with inserts can fail

### LINKED ISSUE #110198: sql/schemachanger: CREATE INDEX with partial indexes with concurrent inserts can fail
Previously, when the declarative schema changer was creating temporary indexes for partial indexes, the index expression was not copied over. As a result, when new inserts came in during index creation, we would capture writes which were not relevant to the index partial expression. This would cause partial index creation to fail during validation since the combined merged index (backfilled and temporary index) would have extra rows.

Jira issue: CRDB-31317

Epic CRDB-30350

### PR DESCRIPTION
**Pull request by fqazi**
Previously, the temporary index created during CREATE INDEX with partial indexes did not correctly copy over the predicate. If an insert and a CREATE INDEX (for partial indexes) were run concurrently, the CREATE INDEX could fail since the temporary index would contain extra rows. Eventually, validation would fail. This patch copies the embedded expression for partial indexes to address this.

Fixes: #110198

Release note (bug fix): CREATE INDEX for partial indexes could fail with "ERROR: duplicate key value violates unique constraint" if concurrent inserts happened simultaneously.

### CODE REVIEW

File: pkg/sql/schemachanger/scbuild/internal/scbuildstmt/helpers.go [hunk 1]
```diff
@@ -684,18 +684,21 @@ func makeTempIndexSpec(src indexSpec) indexSpec {
...
 	if src.secondary != nil {
 		srcIdx = newTempSpec.secondary.Index
+		expr = newTempSpec.secondary.EmbeddedExpr
 		isSecondary = true
 	}
 	tempID := srcIdx.TemporaryIndexID
 	newTempSpec.temporary = &scpb.TemporaryIndex{
 		Index:                    srcIdx,
 		IsUsingSecondaryEncoding: isSecondary,
+		EmbeddedExpr:             expr,
```
Comment (ecwall) [inline pkg/sql/schemachanger/scbuild/internal/scbuildstmt/helpers.go:701]: Can the indexSpec be marked as temporary instead of copying parts of the top level spec into the temporary section?

**Review by fqazi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/110216)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ecwall)

___
*[`pkg/sql/schemachanger/scbuild/internal/scbuildstmt/helpers.go` line 701 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/110216#gh-1319874332:-NdpEza-9AzgxV9gKoF-:b-or027m) ([raw file](https://github.com/cockroachdb/cockroach/blob/62c146bb4e2b8083d75f5467e6d7d76403b21901/pkg/sql/schemachanger/scbuild/internal/scbuildstmt/helpers.go#L701)):*
<details><summary><i>Previously, ecwall (Evan Wall) wrote…</i></summary><blockquote>

Can the indexSpec be marked as temporary instead of copying parts of the top level spec into the temporary section?
</blockquote></details>

So, I think you are suggesting that an indexSpec for a temporary is a copy with just a flag flipped. I think that works for some things, but then there are a bunch of rewrites that happen below to assign IDs. Also, the apply I think would need to generate a TemporryIndex element from the original/primary secondary index elements.

I think in an ideal world SecondaryIndex == TemporaryIndex in terms of content minus the encoding indicator. But we also can't poke at scpb since that's written to descriptors :(

File: pkg/sql/schemachanger/scpb/elements.proto [hunk 2]
```diff
@@ -279,6 +279,7 @@ message SecondaryIndex {
 message TemporaryIndex {
   Index embedded_index = 1 [(gogoproto.nullable) = false, (gogoproto.embed) = true];
   bool is_using_secondary_encoding = 2;
+  Expression embedded_expr = 3 [(gogoproto.nullable) = true];
```
Comment (Xiang-Gu) [inline pkg/sql/schemachanger/scpb/elements.proto:282]: nit: add some comments around this new field
nit: if you really intend this to be embedded (via `(gogoproto.embed) = true`), then consider change the name?

File: pkg/sql/schemachanger/testdata/end_to_end/create_index/create_index.definition [hunk 3]
```diff
@@ -10,13 +10,14 @@ INSERT INTO t VALUES($stageKey + 1, 'b');
 INSERT INTO t VALUES($stageKey + 2, 'c');
 DELETE FROM t WHERE v = 'a' and k=$stageKey;
 INSERT INTO t VALUES($stageKey, 'a');
-UPDATE t SET v='a' WHERE k > 0;
+UPDATE t SET v='a' WHERE k % 2 = 0 
 ----
 
+
 # Each insert will be injected thrice per stage, so we should always,
 # see a count of 2.
```
Comment (Xiang-Gu) [inline pkg/sql/schemachanger/testdata/end_to_end/create_index/create_index.definition:18]: can we add or modify the comments to help readers understand why a count of 2?

File: pkg/sql/schemachanger/testdata/end_to_end/create_index/create_index.definition [hunk 4]
```diff
@@ -10,13 +10,14 @@ INSERT INTO t VALUES($stageKey + 1, 'b');
 INSERT INTO t VALUES($stageKey + 2, 'c');
 DELETE FROM t WHERE v = 'a' and k=$stageKey;
 INSERT INTO t VALUES($stageKey, 'a');
-UPDATE t SET v='a' WHERE k > 0;
+UPDATE t SET v='a' WHERE k % 2 = 0
```
Comment (chrisseto) [inline pkg/sql/schemachanger/testdata/end_to_end/create_index/create_index.definition:13]: Can you add a note as to why `% 2` is being used in favor of `> 0`?

**Review by fqazi — COMMENTED** [review]
> Reviewed 2 of 5 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/110216)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @chrisseto, @ecwall, and @Xiang-Gu)

___
*[`pkg/sql/schemachanger/testdata/end_to_end/create_index/create_index.definition` line 13 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/110216#gh-1321860500:-NeA_9OyAITn2nwUBsxs:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/62c146bb4e2b8083d75f5467e6d7d76403b21901/pkg/sql/schemachanger/testdata/end_to_end/create_index/create_index.definition#L13)):*
<details><summary><i>Previously, chrisseto (Chris Seto) wrote…</i></summary><blockquote>

Can you add a note as to why `% 2` is being used in favor of `> 0`?
</blockquote></details>

Done.
___
*[`pkg/sql/schemachanger/testdata/end_to_end/create_index/create_index.definition` line 18 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/110216#gh-1321751383:-NeA_A-L2_p-mzYSBiNH:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/62c146bb4e2b8083d75f5467e6d7d76403b21901/pkg/sql/schemachanger/testdata/end_to_end/create_index/create_index.definition#L18)):*
<details><summary><i>Previously, Xiang-Gu (Xiang Gu) wrote…</i></summary><blockquote>

can we add or modify the comments to help readers understand why a count of 2?
</blockquote></details>

Done.

**Review by Xiang-Gu — APPROVED** [review]

**Review by chrisseto — APPROVED** [review]
LGTM!

**Review by rafiss — APPROVED** [review]
nice finds!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/110216#-:-NeEEMuf-9gc3PBIfiN2:b-x56zjv)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @chrisseto, @ecwall, and @Xiang-Gu)

**Comment by fqazi** [comment]
@Xiang-Gu @chrisseto @rafiss @ecwall TFTR!

bors r+

**Comment by daniel-crlabs** [comment]
@fqazi @rafiss Any idea when this fix will be released? We have customers running into this issue duplicate key value violates unique constraint and having to disable it with what's shown below (customer is on `23.1.11`)

```
SET use_declarative_schema_changer = off;
```

Once the customers do the above they are able to create the index. Are there any negative consequences to disabling the declarative schema changer in this scenario (creating indexes)? Can they safely move forward with `SET use_declarative_schema_changer = off` for any session where they this king of index? Example below:

```
CREATE INDEX index_name_here 
ON table_name_here (bucketnum, keyname) 
WHERE (validstate = 3) AND (versioned = true);
```

**Comment by daniel-crlabs** [comment]
Thank you, I'll let them know
