### PR TITLE
cli: split the notions of "interactive session" and "terminal output"

### LINKED ISSUE #19775: sql_safe_updates documentation is incorrect
**bug report (documentation)**

The documentation for [`sql_safe_updates`](https://www.cockroachlabs.com/docs/stable/set-vars.html) reads:

> `true` for interactive sessions from the built-in SQL client, `false` for sessions from other clients

This appears to be incorrect, the variable is set to `true` even for non-interactive sessions:

```
$ cockroach sql --insecure -e 'DROP DATABASE IF EXISTS public'
# Server version: CockroachDB CCL v1.1.2 (linux amd64, built 2017/11/02 19:32:03, go1.8.3) (same version as client)
# Cluster ID: e39bd61a-bb22-49ea-ab30-2f2133f7f663
Error: pq: rejected: DROP DATABASE on non-empty database without explicit CASCADE (sql_safe_updates = true)
Failed running "sql"
$
```

### PR DESCRIPTION
**Pull request by knz**
Fixes #19775.
Informs https://github.com/cockroachdb/docs/issues/2263 & https://github.com/cockroachdb/docs/issues/2248

Prior to this patch, a single boolean notion "interactive session" was
used to decide default settings for client commands that issue SQL
queries. This characteristic was decided based on whether both standard
input and standard output are on a terminal.

This characterisation was erroneous however as it didn't properly
account for the following:

- sessions started with `cockroach sql -e`, or non-interactive
  commands like `cockroach node`. These are definitely
  non-interactive, even if the standard input is a terminal.
- sessions started with `cockroach sql >foo.out`, i.e. letting the
  human enter commands from standard input but redirecting output to a
  file. These are arguably interactive and should benefit from the
  various defaults meant to help human users.

To achieve this, this patch separates the notions:

- an *interactive session* is one where the `cockroach` command is
  confident there's a user *manually entering queries*, looking at
  results in-between inputs. This is only decided to be true if 1) the
  `cockroach sql` command is used, 2) the standard input is a terminal
  3) `-e` is not used.
- a session with *terminal output* is where the `cockroach` command
  is confident there's a user *looking at the output*.

These characteristics are then used as follows to decide defaults:

| Setting                        | New default                                             | Previous bug(s) |
|--------------------------------|---------------------------------------------------------|------------------|
| `sql_safe_updates` (session)   | true when the session is interactive and `--unsafe-updates` not given, false otherwise. | defaulted to true always, not only when interactive |
| `check_syntax` (client)        | true when the session is interactive, false otherwise.  | erroneously false when inputting from user with output redirected |
| `errexit` (client)             | false when the session is interactive, true otherwise.  | erroneously true when inputting from user with output redirected |
| `display_format` (client)      | `pretty` when the output goes to a terminal and `--display-format` not given, `tsv` otherwise. | erroneously `tsv` when outputing to terminal with input redirected |
| `show_times` (client)          | true when the output goes to a terminal and `display_format` is `pretty`, false otherwise.     | erroneously false when outputting to terminal with input redirected |
| Input line editor              | true when the session is both interactive and outputting on a terminal, false otherwise.       | N/A |
| `smart_prompt` (client)        | true when the input line editor is enabled.             | N/A |
| Display of input prompt        | true when the input line editor is enabled.             | N/A |
| Storing the input history      | true when the input line editor is enabled.             | N/A |
| `echo` (client)                | always false unless `--echo-sql` given.                 | N/A |

Release note (bug fix, cli change):

- The session variable `sql_safe_updates` defaults to `false` unless
  the shell is truly interactive (using `cockroach sql`, `-e` not
  provided, standard input not redirected) and `--unsafe-updates` is
  not provided.
  Previously it would always default to `true` unless `--unsafe-updates`
  was set.

- The client-side option `errexit` defaults to `false` only if the
  shell is truly interactive, not only when the input is not
  redirected as previously.

- The client-side option `display_format` defaults to `pretty` in
  every case where the output goes to a terminal, not only when the
  input is not redirected as previously.

- `check_syntax`, `smart_prompt` (client-side options), together with
  the interactive line editor, are only enabled if the session is
  interactive and output goes to a terminal.

### CODE REVIEW

**Comment by knz** [comment]
Request to cherry-pick this into 1.1.

File: pkg/cli/sql.go [hunk 1]
```diff
@@ -647,7 +658,7 @@ func (c *cliState) doStartLine(nextState cliStateEnum) cliStateEnum {
 	c.partialLines = c.partialLines[:0]
 	c.partialStmtsLen = 0
 
-	if isInteractive {
+	if c.ins != noLineEditor {
```
Comment (jordanlewis) [inline pkg/cli/sql.go]: nit: this read clearer before - could you add a bool for this with a descriptive name? like hasLineEditor.

**Review by jordanlewis — APPROVED** [review]
LGTM!

**Comment by bdarnell** [comment]
:lgtm:, but -1 on cherry-picking to 1.1.

---

Review status: 0 of 10 files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/20805#-:-L0euCKG0j8MyQk4TuFV:blw0a5x)*

**Comment by knz** [comment]
TFYRs!
