### PR TITLE
rpc,server: fix endpoint telemetry test for DRPC

### LINKED ISSUE #161590: server: enable DRPC for TestEndpointTelemetryBasic
**Describe the problem**

We currently have DRPC disabled for `TestEndpointTelemetryBasic` since it fails when it is turned on.

**To Reproduce**

`./dev test pkg/server-f TestEndpointTelemetryBasic -- --test_env=COCKROACH_TEST_DRPC=true`

**Expected behavior**

The test should pass with DRPC enabled.

Epic: CRDB-55382

Jira issue: CRDB-58972

### PR DESCRIPTION
**Pull request by Nukitt**
`TestEndpointTelemetryBasic` was failing when DRPC was enabled because the HTTP gateway uses a different telemetry counter path under DRPC `(http.drpc-gateway.*)` than under gRPC `(http.grpc-gateway.*)`. The gRPC gateway increments counters via a `grpc.UnaryInterceptor` on the loopback ClientConn, while the DRPC gateway uses `drpcGatewayRequestCounterInterceptor` which writes to a separate counter namespace.

This change pins the `TestEndpointTelemetryBasic` to gRPC since it specifically validates the gRPC gateway telemetry path. We separately add `TestDRPCEndpointTelemetryBasic` in `drpc_test.go` that validates the equivalent telemetry under DRPC using the `http.drpc-gateway` counters.

Epic: CRDB-55382
Fixes: #161590
Release note: None

### CODE REVIEW

File: pkg/server/drpc_test.go [hunk 1]
```diff
@@ -275,3 +278,34 @@ func TestDialDRPC_InterceptorsAreSet(t *testing.T) {
...
+	}
+	require.GreaterOrEqual(t, telemetry.Read(rpc.GetDRPCGatewayEndpointCounter(
+		"/cockroach.server.serverpb.Admin/Locations",
+	)), int32(1))
+
+	var resp serverpb.StatementsResponse
+	if err := srvtestutils.GetStatusJSONProto(s, "statements", &resp); err != nil {
+		t.Fatal(err)
+	}
+	require.Equal(t, int32(1), telemetry.Read(rpc.GetDRPCGatewayEndpointCounter(
```
Comment (cthumuluru-crdb) [inline pkg/server/drpc_test.go]: How about creating a function to return the counter to read from? That way you can turn the test into a table test with both DRPC enabled and disabled.

File: pkg/rpc/metrics.go [hunk 2]
```diff
@@ -607,15 +607,15 @@ func drpcGatewayRequestCounterInterceptor(
...
 		}
 	}
 	return invoker(ctx, rpc, enc, in, out, cc)
 }
 
-// getDRPCGatewayEndpointCounter returns a telemetry Counter corresponding to
+// GetDRPCGatewayEndpointCounter returns a telemetry Counter corresponding to
 // the given DRPC method.
-func getDRPCGatewayEndpointCounter(method string) telemetry.Counter {
+func GetDRPCGatewayEndpointCounter(method string) telemetry.Counter {
```
Comment (cthumuluru-crdb) [inline pkg/rpc/metrics.go]: Is it possible to avoid exporting this function?

**Review by cthumuluru-crdb — CHANGES_REQUESTED** [review]

File: pkg/server/drpc_test.go (hunk 1 above)
Comment (Nukitt) [reply pkg/server/drpc_test.go]: done.

File: pkg/rpc/metrics.go (hunk 2 above)
Comment (Nukitt) [reply pkg/rpc/metrics.go]: yeah, done.

**Review by cthumuluru-crdb — APPROVED** [review]
LGTM!
