### PR TITLE
parser,tree: use string_or_placeholder for LDR options

### LINKED ISSUE #126311: sql/tests: TestRandomSyntaxGeneration failed
sql/tests.TestRandomSyntaxGeneration [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RandomSyntaxTestsBazel/15840910?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RandomSyntaxTestsBazel/15840910?buildTab=artifacts#/) on master @ [d2a5af43be05ade40531e6e0ef23c5880faa4494](https://github.com/cockroachdb/cockroach/commits/d2a5af43be05ade40531e6e0ef23c5880faa4494):

```
    rsg_test.go:116: Last executed (4): COMMENT ON CONSTRAINT CONSTRAINTS ON RESTART . BETWEEN IS 'string'
    rsg_test.go:116: Last executed (5): IMPORT INTO POSITION ( TIMESTAMP , VARIABLES ) TRANSACTIONS DATA ( CALLED )
    rsg_test.go:116: Last executed (6): CREATE DATABASE IF NOT EXISTS ident
    rsg_test.go:116: Last executed (7): DROP OWNED BY SESSION_USER , CURRENT_USER , DEPENDS
    rsg_test.go:116: Last executed (8): CREATE DATABASE IF NOT EXISTS ident
    rsg_test.go:116: Last executed (9): REASSIGN OWNED BY RECURRING , CURRENT_USER , SESSION_USER , SESSION_USER TO SESSION_USER
    rsg_test.go:116: Last executed (10): REASSIGN OWNED BY ident , CURRENT_USER TO BEFORE
    rsg_test.go:116: Last executed (11): CREATE DATABASE IF NOT EXISTS ident
    rsg_test.go:116: Last executed (12): CREATE DATABASE IF NOT EXISTS ident
    rsg_test.go:116: Last executed (13): CREATE DATABASE IF NOT EXISTS ident
    rsg_test.go:116: Last executed (14): DROP TABLE IF EXISTS TIMESTAMP . CROSS . FAMILY RESTRICT
    rsg_test.go:116: Last executed (15): COPY NOVIEWCLUSTERSETTING ( NEW_KMS ) TO STDOUT DESTINATION = ident FREEZE error FORCE NOT NULL error CSV
    rsg_test.go:116: Last executed (16): ANALYSE RESTART . ident . ident
    rsg_test.go:116: Last executed (17): CREATE DATABASE IF NOT EXISTS ident
    rsg_test.go:116: Last executed (18): CREATE DATABASE IF NOT EXISTS ident
    rsg_test.go:116: Last executed (19): UNLISTEN FAMILY . INTERSECT . OUTER
    rsg_test.go:116: Last executed (20): CREATE DATABASE IF NOT EXISTS ident
    rsg_test.go:116: Last executed (21): CREATE DATABASE IF NOT EXISTS ident
    rsg_test.go:116: Last executed (22): MOVE LAST IN CREATEDB
    rsg_test.go:116: Last executed (23): CREATE DATABASE IF NOT EXISTS ident
    rsg_test.go:116: Last executed (24): COMMENT ON INDEX INDEX_BEFORE_PAREN . GROUPING IS 'string'
    rsg_test.go:116: Last executed (25): COMMENT ON COLUMN FAMILY . SERIALIZABLE . JOB . SMALLINT IS NULL
    rsg_test.go:116: Last executed (26): COPY FAMILY ( INOUT , PHYSICAL ) TO error
    rsg_test.go:116: Last executed (27): CREATE DATABASE IF NOT EXISTS ident
    rsg_test.go:116: Last executed (28): ANALYSE INDEX_BEFORE_NAME_THEN_PAREN . INTEGER
    rsg_test.go:116: Last executed (29): CREATE DATABASE IF NOT EXISTS ident
    rsg_test.go:116: Last executed (30): DROP OWNED BY SESSION_USER , DEFAULTS RESTRICT
    rsg_test.go:116: Last executed (31): CREATE DATABASE IF NOT EXISTS ident
    rsg_test.go:116: Last executed (32): IMPORT TREAT NOCREATEROLE WITH OPTIONS ( 'string' , 'string' )
    rsg_test.go:116: Last executed (33): CREATE DATABASE IF NOT EXISTS ident
    rsg_test.go:116: Last executed (34): CREATE DATABASE IF NOT EXISTS ident
    rsg_test.go:116: Last executed (35): CREATE DATABASE IF NOT EXISTS ident
    rsg_test.go:116: Last executed (36): EXPLAIN ANALYZE ( KEYS , ident ) EXECUTE error
    rsg_test.go:116: Last executed (37): IMPORT INTO NOTHING_AFTER_RETURNING . ILIKE ( BOX2D ) CYCLE DATA ( BOOLEAN , FAMILY , PLACEHOLDER , PLACEHOLDER , ident ) WITH OPTIONS ( 'string' = PLACEHOLDER , 'string' = PLACEHOLDER )
    rsg_test.go:116: Last executed (38): UNLISTEN PRECISION . ident . LOCAL
    rsg_test.go:116: Last executed (39): CREATE DATABASE IF NOT EXISTS ident
    rsg_test.go:116: Last executed (40): EXPLAIN ANALYZE ( NOMODIFYCLUSTERSETTING ) EXECUTE ident DISCARD ROWS
    rsg_test.go:116: Last executed (41): CREATE DATABASE IF NOT EXISTS ident
    rsg_test.go:116: Last executed (42): CREATE DATABASE IF NOT EXISTS ident
    rsg_test.go:116: Last executed (43): FETCH IN CANCELQUERY
    rsg_test.go:116: Last executed (44): DROP OWNED BY CURRENT_USER , ident , CURRENT_USER , CURRENT_USER , SESSION_USER RESTRICT
    rsg_test.go:116: Last executed (45): COPY FAMILY . PRIMARY ( ident , INT , IF ) TO error
    rsg_test.go:116: Last executed (46): MOVE - -101 IN ident
    rsg_test.go:116: Last executed (47): COPY GROUPING ( ident , ident , ident , BOX2D , ident ) FROM error
    rsg_test.go:116: Last executed (48): REFRESH MATERIALIZED VIEW CONCURRENTLY NOTHING_AFTER_RETURNING . DESTINATION WITH NO DATA
    rsg_test.go:116: Last executed (49): EXECUTE UNLOGGED ( UNIQUE ( error IS NULL ) DISCARD ROWS
    rsg_test.go:119: Currently active statements: map[]
    rsg_test.go:355: -- test log scope end --
test logs left over in: /artifacts/tmp/_tmp/d437d2c847dfedbc4972f231c3331c8e/logTestRandomSyntaxGeneration3759645010
--- FAIL: TestRandomSyntaxGeneration (301.51s)
```
<details><summary>Help</summary>
<p>

See also: [How To Investigate a Go Test Failure \(internal\)](https://cockroachlabs.atlassian.net/l/c/HgfXfJgM)
</p>
</details>
/cc @cockroachdb/sql-foundations
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*TestRandomSyntaxGeneration.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/bazci/githubpost/issues)
</sub>

Jira issue: CRDB-39844

### PR DESCRIPTION
**Pull request by rafiss**
Using a d_expr is too broad here, since it makes it possible to use an invalid type. Using string_or_placeholder matches what we do for other options lists in the grammar.

fixes https://github.com/cockroachdb/cockroach/issues/126311
Release note: None

### CODE REVIEW

**Review by Jeremyyang920 — APPROVED** [review]
Thanks for updating!

File: pkg/sql/sem/tree/create_logical_replication.go [hunk 1]
```diff
@@ -49,7 +49,7 @@ func (node *CreateLogicalReplicationStream) Format(ctx *FmtCtx) {
 	ctx.FormatNode(&node.Into)
 
 	if !node.Options.IsDefault() {
-		ctx.WriteString(" WITH ")
+		ctx.WriteString(" WITH OPTIONS ")
```
Comment (Jeremyyang920) [inline pkg/sql/sem/tree/create_logical_replication.go:52]: You may need to rewrite the parser test, since it should fail now that "OPTION" is going to be written.

Comment (Jeremyyang920) [reply pkg/sql/sem/tree/create_logical_replication.go:52]: Oh I think this actually won't work since there is not a parser case for it. Might need to do
ctx.WriteString(" WITH OPTIONS (")
ctx.FormatNode(&node.Options)
ctx.WriteString(")")

since there is a case for WITH OPTIONS ( logical_replication_options_list).

Comment (rafiss) [reply pkg/sql/sem/tree/create_logical_replication.go]: yeah that's definitely correct. we need the parens.
