### PR TITLE
roachprod: fail early on startup script errors and make them observable

### LINKED ISSUE #120007: roachprod: fail early on startup script errors and make them observable
When a new VM is provisioned with roachprod, a startup script is executed[^1]. Currently, there are at least two points in which we want to improve this:

* The script does not run with `set -e`, meaning any commands that fail will not cause the entire script to fail. This could lead to bugs that are subtle and hard to diagnose.
* Failures are mostly invisible to roachprod. If the script fails and we never create a `.roachprod-inititialized` file, VM creation will just fail when the check for that file times out[^2]. The actual reason for the failure is hidden.

In order to make this process more understandable, we want to be able to use `set -e` in these scripts, and also capture their output. If the script fails, we can display the output the user, which will likely contain the reason for the failure.

[^1]: for instance, for GCE, see https://github.com/cockroachdb/cockroach/blob/549a5c20283de78604d19716963eae482ff19532/pkg/roachprod/vm/gce/utils.go#L41-L238.

[^2]: see https://github.com/cockroachdb/cockroach/blob/549a5c20283de78604d19716963eae482ff19532/pkg/roachprod/install/cluster_synced.go#L1360.

Jira issue: CRDB-36432

### PR DESCRIPTION
**Pull request by vidit-bhat**
Previously, when a new VM was provisioned with roachprod a startup script was executed without `set -e` and failures if any weren't captured. This patch fixes these issues by executing the script using `set -eux` and redirecting failure outputs to a `/var/log/roachprod_startup.log`.

Epic: none
Fixes: #120007
Release note: None

### CODE REVIEW

File: pkg/roachprod/vm/gce/utils.go [hunk 1]
```diff
@@ -31,7 +31,11 @@ import (
 const gceDiskStartupScriptTemplate = `#!/usr/bin/env bash
 # Script for setting up a GCE machine for roachprod use.
 
-set -x
+# ensure any failure fails the entire script
+set -eux
+
```
Comment (nameisbhaskar) [inline pkg/roachprod/vm/gce/utils.go:36]: Can we add a message in the beginning "Sending output to /var/log/roachprod_startup.log"?

File: pkg/roachprod/vm/gce/utils.go [hunk 2]
```diff
@@ -31,7 +31,11 @@ import (
...
+# Redirect output to a log file
+exec > /var/log/roachprod_startup.log 2>&1
```
Comment (renatolabs) [inline pkg/roachprod/vm/gce/utils.go:38]: Related to @nameisbhaskar's comment: I think it would be nice to log both to the file _and_ to stdout/err as before. The advantage is that then the output of the startup script will be available on google cloud's logs which is useful.

I believe you can achieve that with something like:

```bash
set -eux

exec &> >(tee {{ .StartupLogs }})

# rest of the script
```

**Review by renatolabs — COMMENTED** [review]
Thanks for working on this issue!

I think there's still a little more work to complete the task.

* It should be straightforward to add the same logic in the other cloud providers. As hinted in my other comment, the path to the startup script logs can be passed as parameter to the template so we don't have to copy paste that path.
* The `Wait` function can now produce a better error message. When `Wait` fails, we can include the last `N` (maybe 20?) lines of the log file, with a message indicating that the user can view the entire output in `/var/log/roachprod_startup.log`.

We should also do a 10% run of the roachtest nightly build on this branch. Some commands on the startup script might have been failing (without meaningful consequences) without us knowing, and that would now lead to cluster creation failures.

File: pkg/roachprod/vm/gce/utils.go (hunk 2 above)
Comment (vidit-bhat) [reply pkg/roachprod/vm/gce/utils.go]: Updated

File: pkg/roachprod/vm/gce/utils.go (hunk 1 above)
Comment (vidit-bhat) [reply pkg/roachprod/vm/gce/utils.go:36]: Done in another way

File: pkg/roachprod/install/cluster_synced.go [hunk 3]
```diff
@@ -1421,6 +1421,13 @@ func (c *SyncedCluster) Wait(ctx context.Context, l *logger.Logger) error {
 			}
 			res.Err = errors.Wrapf(res.Err, "timed out after 5m")
 			l.Printf("  %2d: %v", node, res.Err)
+			logContent, err := c.getLogTail(ctx, node, 20)
+			if err != nil {
+				l.Printf("  %2d: %v (failed to retrieve log tail: %v)", node, res.Err, err)
```
Comment (srosenberg) [inline pkg/roachprod/install/cluster_synced.go:1426]: `res.Err` has already been logged above; it's unaffected by the `getLogTail` call.

File: pkg/roachprod/vm/gce/utils.go [hunk 4]
```diff
@@ -31,7 +31,11 @@ import (
 const gceDiskStartupScriptTemplate = `#!/usr/bin/env bash
 # Script for setting up a GCE machine for roachprod use.
 
-set -x
+# ensure any failure fails the entire script
+set -eux
+
+# Redirect output to stdout/err and a log file
+exec &> >(tee {{ .StartupLogs }})
```
Comment (srosenberg) [inline pkg/roachprod/vm/gce/utils.go:38]: What if a VM is restarted? It would be nice to append vs. overwrite. It would also be nice to have a timestamp as a frame of reference.

**Review by renatolabs — COMMENTED** [review]
Nice!

I think the main thing is to handle restarts as Stan mentioned by appending instead of overwriting + printing a timestamp (`echo "startup script starting: $(date -u)"` or something along those lines).

**Comment by renatolabs** [comment]
I was playing with this branch locally and realized we need to make a few changes to the GCE startup script to be compatible with `set -e`. While I haven't looked yet, it's fair to assume the same is true for the other cloud providers.

Ping me if you have questions or would like some help making the changes!

**Comment by vidit-bhat** [comment]
Tested out the changes by creating clusters on all 3 clouds. PTAL.

File: pkg/roachprod/install/cluster_synced.go [hunk 5]
```diff
@@ -1420,7 +1420,16 @@ func (c *SyncedCluster) Wait(ctx context.Context, l *logger.Logger) error {
...
 			}
 			res.Err = errors.Wrapf(res.Err, "timed out after 5m")
+			logContent, err := c.runCmdOnSingleNode(ctx, nil, node, fmt.Sprintf("tail -n %d %s", 20, vm.StartupLogs), cmdOptsWithDebugDisabled())
+			if err != nil {
+				res.Err = errors.CombineErrors(res.Err, err)
+			} else if logContent.Err != nil {
+				res.Err = errors.CombineErrors(res.Err, logContent.Err)
+			} else {
+				res.Err = errors.Wrapf(res.Err, "last 20 lines of log:\n%s", logContent.Stdout)
+			}
```
Comment (renatolabs) [inline pkg/roachprod/install/cluster_synced.go:1430]: Adding an error for the fetching of logs using the `CombineErrors` API is not ideal: in the current code, it won't show up at all because we're printing the error with `%v` (see [this table](https://github.com/cockroachdb/errors?tab=readme-ov-file#what-comes-out-of-an-error)). We also don't want to use `%+v` there because it would make the output very verbose.

I suggest we just _log_ the last 20 lines (or the error fetching them) instead of wrapping the error. Something like the following diff:

```diff
diff --git a/pkg/roachprod/install/cluster_synced.go b/pkg/roachprod/install/cluster_synced.go
index 49119734bb7..b2d3c43da50 100644
--- a/pkg/roachprod/install/cluster_synced.go
+++ b/pkg/roachprod/install/cluster_synced.go
@@ -1421,15 +1421,13 @@ func (c *SyncedCluster) Wait(ctx context.Context, l *logger.Logger) error {
 			}
 			res.Err = errors.Wrapf(res.Err, "timed out after 5m")
 			logContent, err := c.runCmdOnSingleNode(ctx, nil, node, fmt.Sprintf("tail -n %d %s", 20, vm.StartupLogs), cmdOptsWithDebugDisabled())
-			if err != nil {
-				res.Err = errors.CombineErrors(res.Err, err)
-			} else if logContent.Err != nil {
-				res.Err = errors.CombineErrors(res.Err, logContent.Err)
+			if err := errors.CombineErrors(err, res.Err); err != nil {
+				l.Printf("could not fetch startup logs: %v", err)
 			} else {
-				res.Err = errors.Wrapf(res.Err, "last 20 lines of log:\n%s", logContent.Stdout)
+				l.Printf("startup failed, last 20 lines of output:\n%s", logContent.CombinedOut)
+				l.Printf("  %2d: view the full log in %s", node, vm.StartupLogs)
 			}
 			l.Printf("  %2d: %v", node, res.Err)
-			l.Printf("  %2d: view the full log in %s", node, vm.StartupLogs)
 			return res, nil
 		})
```

Note also that we need to use `CombinedOut` there, not `Stdout` (a tricky part of that API).

**Review by renatolabs — COMMENTED** [review]
Nice! A couple of things before we merge:

* Let's also change this line below to check for the existence of `vm.OSInitializedFile`. The GCE script will create the `DisksInitializedFile` as soon as the disks are setup, but if there's an error _after_ disk setup, roachprod wouldn't know.

https://github.com/cockroachdb/cockroach/blob/3c5e4adbaeb883c44a5ab6a940f2eeaf5de76b3c/pkg/roachprod/install/cluster_synced.go#L1409

* Let's run a `SELECT_PROBABILITY=0.3` on all clouds to be safe.

File: pkg/roachprod/install/cluster_synced.go (hunk 5 above)
Comment (vidit-bhat) [reply pkg/roachprod/install/cluster_synced.go:1430]: Thanks for the information. A few TILs.

File: pkg/roachprod/vm/gce/utils.go [hunk 6]
```diff
@@ -31,7 +31,14 @@ import (
...
 
-set -x
+# ensure any failure fails the entire script
+set -eux
+
+# Log the startup of the script with a timestamp
+echo "startup script starting: $(date -u)" | tee -a {{ .StartupLogs }}
+
+# Redirect output to stdout/err and a log file
+exec &> >(tee -a {{ .StartupLogs }})
```
[the remark this answers is not in the document]
Comment (vidit-bhat) [reply pkg/roachprod/vm/gce/utils.go:38]: Done

File: pkg/roachprod/vm/gce/utils.go [hunk 7]
```diff
@@ -270,7 +286,9 @@ sysctl --system  # reload sysctl settings
 sudo ua enable fips --assume-yes
 {{ end }}
 
-sudo -u {{ .SharedUser }} bash -c "mkdir ~/.ssh && chmod 700 ~/.ssh"
+if [ ! -d "/home/{{ .SharedUser }}/.ssh" ]; then
+    sudo -u {{ .SharedUser }} bash -c "mkdir ~/.ssh && chmod 700 ~/.ssh"
+fi
```
[the remark this answers is not in the document]
Comment (vidit-bhat) [reply pkg/roachprod/vm/gce/utils.go]: Done

File: pkg/roachprod/install/cluster_synced.go [hunk 8]
```diff
@@ -1422,6 +1422,13 @@ func (c *SyncedCluster) Wait(ctx context.Context, l *logger.Logger) error {
 				return res, nil
 			}
 			res.Err = errors.Wrapf(res.Err, "timed out after 5m")
+			logContent, err := c.runCmdOnSingleNode(ctx, nil, node, fmt.Sprintf("tail -n %d %s", 20, vm.StartupLogs), cmdOptsWithDebugDisabled())
+			if err = errors.CombineErrors(err, res.Err); err != nil {
```
Comment (renatolabs) [inline pkg/roachprod/install/cluster_synced.go:1426]: I realize my diff had this mistake (apologies), but I think the `CombineErrors` here should have been with `err` and `logContent.Err` (not `res`).

File: pkg/roachprod/vm/gce/utils.go [hunk 9]
```diff
@@ -31,7 +31,16 @@ import (
...
+# ensure any failure fails the entire script
+set -eux
+
+# Redirect output to stdout/err and a log file
+exec &> >(tee -a {{ .StartupLogs }})
+
+# Log the startup of the script with a timestamp
+echo "startup script starting: $(date -u)"
+
+sudo -u {{ .SharedUser }} bash -c "mkdir -p ~/.ssh && chmod 700 ~/.ssh"
```
Comment (renatolabs) [inline pkg/roachprod/vm/gce/utils.go:43]: The appending of the public key to `authorized_keys` is the key part to also move up, as that is what enables the caller to access the VM.

**Comment by vidit-bhat** [comment]
I ran the nightlies for all 3 clouds
- [GCE](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/16845749?hideProblemsFromDependencies=false&hideTestsFromDependencies=false&expandBuildChangesSection=true&expandBuildTestsSection=true)
- [AWS](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyAwsBazel/16843388?buildTab=overview&hideProblemsFromDependencies=false&expandBuildTestsSection=true&hideTestsFromDependencies=false&expandBuildChangesSection=true)
- [Azure](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyAzureBazel/16843389?hideProblemsFromDependencies=false&hideTestsFromDependencies=false&expandBuildChangesSection=true)

@renatolabs

**Review by renatolabs — APPROVED** [review]
Thanks for iterating, LGTM!

**Comment by vidit-bhat** [comment]
TFTR!

bors r=renatolabs
