### PR TITLE
cli: Fix number of args expected by `debug gossip-values`

### LINKED ISSUE #24751: cli: `cockroach debug gossip-values` no longer works without a positional argument
...and the command doesn't actually use any positional arguments. This does not appear to be broken in any actual releases.

### PR DESCRIPTION
**Pull request by a-robinson**
Fixes #24751

Release note: None

It looks like the problem is that my original usage string (`gossip-values <directory>`) was badly copied and pasted from other debug commands, and then assumed necessary by #24399 when in reality no positional argument is used by the command.

### CODE REVIEW

File: pkg/cli/debug.go [hunk 1]
```diff
@@ -885,15 +885,14 @@ func runDebugSSTables(cmd *cobra.Command, args []string) error {
...
-	Use:   "gossip-values <directory>",
+	Use:   "gossip-values",
 	Short: "dump all the values in a node's gossip instance",
 	Long: `
 Pretty-prints the values in a node's gossip instance.
 
 Can connect to a running server to get the values or can be provided with
 a JSON file captured from a node's /_status/gossip/ debug endpoint.
 `,
-	Args: cobra.ExactArgs(1),
```
Comment (nvanbenschoten) [inline pkg/cli/debug.go]: Make this `Args: cobra.NoArgs,` so that we still have argument count validation.

Comment (a-robinson) [reply pkg/cli/debug.go]: Done.

**Review by nvb — APPROVED** [review]
