### PR TITLE
sql: bugfix to primary key updates w/ mutations

### LINKED ISSUE #16828: sql: primary key updates during index backfills are broken
The secondary index update algorithm used in `RowUpdater.UpdateRow` does not take into account the state of a secondary index during an index backfill, and can produce incorrect update failures.

For example, consider the following scenario:

```
CREATE TABLE test (k INT PRIMARY KEY, v INT);
INSERT INTO test VALUES (1, 2);
-- begin index backfill: `CREATE INDEX foo ON test(v)`
-- before backfill starts, execute:
UPDATE test SET k=3 WHERE v=2;
```
If performed in the correct sequence, the `UPDATE` will produce the following error:

```
pq: got 3 values but expected 2
```

I haven't tracked down the precise cause of this, but it's basically because the `RowUpdater` isn't sufficiently aware of all of the possible states an index backfill can be in.

### PR DESCRIPTION
**Pull request by jordanlewis**
Previously, updating the primary key of a row with active column or
index mutations could lead to incorrect behavior that manifested as
spurious user-facing errors. No data was corrupted, but errors were
incorrectly thrown until the corresponding backfill completed.

Also, some small cleanup to nearby files.

Fixes #16828.

cc @danhhz @dt

### CODE REVIEW

File: pkg/sql/descriptor_mutation_test.go [hunk 1]
```diff
@@ -324,6 +324,19 @@ CREATE TABLE t.test (k CHAR PRIMARY KEY, v CHAR, i CHAR DEFAULT 'i', FAMILY (k),
...
+			// Update primary key of row "c" to be "d"
+			mTest.Exec(`UPDATE t.test SET k = 'd' WHERE v = 'x'`)
+			// Make column "i" live so that it is read.
+			mTest.makeMutationsActive()
+			if state == sqlbase.DescriptorMutation_DELETE_ONLY {
+				mTest.CheckQueryResults(starQuery, [][]string{{"d", "x", "NULL"}})
+			} else {
+				mTest.CheckQueryResults(starQuery, [][]string{{"d", "x", "i"}})
+			}
+			mTest.checkTableSize(afterDeleteKeys)
```
Comment (vivekmenezes) [inline pkg/sql/descriptor_mutation_test.go]: Can you move this entire test to above the DELETE test and just after UPSERT/UPDATE test above. That way it's in the right spot and you don't need to call checkTableSize twice.

File: pkg/sql/descriptor_mutation_test.go [hunk 2]
```diff
@@ -481,6 +494,23 @@ CREATE TABLE t.test (k CHAR PRIMARY KEY, v CHAR, INDEX foo (v));
...
+			// Make index "foo" live so that we can read it.
+			mTest.makeMutationsActive()
+			// Updating the primary key for a row when we're in delete-only won't
+			// create a new index entry, and will delete the old one. Otherwise it'll
+			// create a new entry and delete the old one.
+			if state == sqlbase.DescriptorMutation_DELETE_ONLY {
+				mTest.CheckQueryResults(indexQuery, [][]string{})
+			} else {
+				mTest.CheckQueryResults(indexQuery, [][]string{{"w"}, {"z"}})
+			}
```
Comment (vivekmenezes) [inline pkg/sql/descriptor_mutation_test.go]: same here. move it to the UPDATE section

File: pkg/sql/sqlbase/rowwriter.go [hunk 3]
```diff
@@ -434,6 +437,10 @@ func MakeRowUpdater(
 		}
 	}
 
+	// Columns of the table to update, including those in delete/write-only state
+	tableCols := make([]ColumnDescriptor, 0, len(tableDesc.Columns)+len(tableDesc.Mutations))
+	tableCols = append(tableCols, tableDesc.Columns...)
```
Comment (vivekmenezes) [inline pkg/sql/sqlbase/rowwriter.go]: for performance reasons how about:
```
tableCols := tableDesc.Columns
if len(tableDesc.Mutations) > 0 {
tableCols = make([]ColumnDescriptor, 0, len(tableDesc.Columns)+len(tableDesc.Mutations))
 tableCols = append(tableCols, tableDesc.Columns...)
}
```

**Review by vivekmenezes — APPROVED** [review]
Hey thanks for fixing this. Nice!

**Comment by jordanlewis** [comment]
Thanks for the review - done on all counts.
