### PR TITLE
importccl: unskip most tests in TestImportData

### LINKED ISSUE #51811: importccl: TestImportData is skipped
As of 8/23/19 (05dbe09): `	t.Skipf("failing on teamcity with testrace")`

Note that this is unconditionally skipped, not just skipped under testrace, despite what the message says.

### PR DESCRIPTION
**Pull request by pbardea**
This commit is a collection of small fix-ups to the TestImportData tests
that have rotted a bit while being skipped.

A few tests seem actually broken and issues have been filed for those.

Fixes #51811.

Release justification: test only change
Release note: None

### CODE REVIEW

File: pkg/ccl/importccl/import_stmt_test.go [hunk 1]
```diff
@@ -1271,19 +1264,18 @@ func TestImportUserDefinedTypes(t *testing.T) {
...
 )`
-	testPgdumpCreateWeather = `CREATE TABLE weather (
+	testPgdumpCreateWeather = `CREATE TABLE public.weather (
 	city VARCHAR(80) NULL,
 	temp_lo INT8 NULL,
 	temp_hi INT8 NULL,
 	prcp FLOAT4 NULL,
 	date DATE NULL,
-	CONSTRAINT weather_city_fkey FOREIGN KEY (city) REFERENCES cities(city),
-	INDEX weather_auto_index_weather_city_fkey (city ASC),
```
Comment (adityamaru) [inline pkg/ccl/importccl/import_stmt_test.go:1286]: just curious, why have you dropped this INDEX? Same in one other spot above.

**Review by adityamaru — APPROVED** [review]

File: pkg/ccl/importccl/import_stmt_test.go (hunk 1 above)
Comment (pbardea) [reply pkg/ccl/importccl/import_stmt_test.go:1286]: This was changed in https://github.com/cockroachdb/cockroach/pull/50771

**Comment by pbardea** [comment]
TFTR!
bors r=adityamaru
