### PR TITLE
kvserver: check PROSCRIBED lease status over UNUSABLE

### LINKED ISSUE #98698: kvserver: `side-transport update saw closed timestamp regression` during roachtest
Test Eng has in-progress work to randomly enable runtime assertions (`crdb_test` build tag)  in roachtests [1], and in the process of testing that, there was a failure in the `failover/non-system/blackhole-recv` roachtest where a node crashed with the following error:

```
kv/kvserver/replica_closedts.go:263 â‹® [T1,n6] 2003  side-transport update saw closed timestamp regression on r1049: (lai=429, ts=1678502687.228717404,0) -> (lai=428, ts=1678502687.708863313,0)
kv/kvserver/replica_closedts.go:263 â‹® [T1,n6] 2003 !goroutine 1045566 [running]:
kv/kvserver/replica_closedts.go:263 â‹® [T1,n6] 2003 !github.com/cockroachdb/cockroach/pkg/util/log.getStacks(0x1)
kv/kvserver/replica_closedts.go:263 â‹® [T1,n6] 2003 !	github.com/cockroachdb/cockroach/pkg/util/log/get_stacks.go:25 +0x89
kv/kvserver/replica_closedts.go:263 â‹® [T1,n6] 2003 !github.com/cockroachdb/cockroach/pkg/util/log.(*loggerT).outputLogEntry(0xc000b73c00, {{{0x0, 0x0}, {0x0, 0x0}, {0x0, 0x0}, {0x0, 0x0}}, 0x174b3d4de64f480d, ...})
kv/kvserver/replica_closedts.go:263 â‹® [T1,n6] 2003 !	github.com/cockroachdb/cockroach/pkg/util/log/clog.go:262 +0x97
kv/kvserver/replica_closedts.go:263 â‹® [T1,n6] 2003 !github.com/cockroachdb/cockroach/pkg/util/log.logfDepthInternal({0x6e7a3d0, 0xc006245d10}, 0x2, 0x4, 0x0, 0x0?, {0x5b4cbd0, 0x60}, {0xc00228b9e8, 0x5, ...})
kv/kvserver/replica_closedts.go:263 â‹® [T1,n6] 2003 !	github.com/cockroachdb/cockroach/pkg/util/log/channels.go:106 +0x645
kv/kvserver/replica_closedts.go:263 â‹® [T1,n6] 2003 !github.com/cockroachdb/cockroach/pkg/util/log.logfDepth(...)
kv/kvserver/replica_closedts.go:263 â‹® [T1,n6] 2003 !	github.com/cockroachdb/cockroach/pkg/util/log/channels.go:39
kv/kvserver/replica_closedts.go:263 â‹® [T1,n6] 2003 !github.com/cockroachdb/cockroach/pkg/util/log.Fatalf(...)
kv/kvserver/replica_closedts.go:263 â‹® [T1,n6] 2003 !	github.com/cockroachdb/cockroach/bazel-out/k8-opt/bin/pkg/util/log/log_channels_generated.go:848
kv/kvserver/replica_closedts.go:263 â‹® [T1,n6] 2003 !github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*sidetransportAccess).assertNoRegression(0x50f5620?, {0x6e7a3d0, 0xc006245d10}, {{0x174b3d4d0ace695c, 0x0, 0x0}, 0x1ad}, {{0x174b3d4d276cdb51, 0x0, 0x0}, ...})
kv/kvserver/replica_closedts.go:263 â‹® [T1,n6] 2003 !	github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/replica_closedts.go:263 +0x1eb
kv/kvserver/replica_closedts.go:263 â‹® [T1,n6] 2003 !github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*sidetransportAccess).forward(0xc0058a0598, {0x6e7a3d0, 0xc006245d10}, {0x20000c002539100?, 0xffffffff?, 0xff?}, 0x1ac, 0x0)
kv/kvserver/replica_closedts.go:263 â‹® [T1,n6] 2003 !	github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/replica_closedts.go:237 +0x15d
kv/kvserver/replica_closedts.go:263 â‹® [T1,n6] 2003 !github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*Replica).ForwardSideTransportClosedTimestamp(...)
kv/kvserver/replica_closedts.go:263 â‹® [T1,n6] 2003 !	github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/replica_closedts.go:138
kv/kvserver/replica_closedts.go:263 â‹® [T1,n6] 2003 !github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*Stores).ForwardSideTransportClosedTimestampForRange.func1(0xc009d26bb8?)
kv/kvserver/replica_closedts.go:263 â‹® [T1,n6] 2003 !	github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/stores.go:132 +0x8a
kv/kvserver/replica_closedts.go:263 â‹® [T1,n6] 2003 !github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*Stores).VisitStores.func1(0xc009d26bb8?, 0xa60a968?)
kv/kvserver/replica_closedts.go:263 â‹® [T1,n6] 2003 !	github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/stores.go:149 +0x29
kv/kvserver/replica_closedts.go:263 â‹® [T1,n6] 2003 !github.com/cockroachdb/cockroach/pkg/util/syncutil.(*IntMap).Range(0xc00571f7d0?, 0xc00228bc48)
kv/kvserver/replica_closedts.go:263 â‹® [T1,n6] 2003 !	github.com/cockroachdb/cockroach/pkg/util/syncutil/int_map.go:352 +0x1fa
kv/kvserver/replica_closedts.go:263 â‹® [T1,n6] 2003 !github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*Stores).VisitStores(0x67e?, 0xc002539100?)
kv/kvserver/replica_closedts.go:263 â‹® [T1,n6] 2003 !	github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/stores.go:148 +0x54
kv/kvserver/replica_closedts.go:263 â‹® [T1,n6] 2003 !github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*Stores).ForwardSideTransportClosedTimestampForRange(0x5099580?, {0x6e7a3d0, 0xc006245d10}, 0x6e7a3d0?, {0xc006245d10?, 0x203000?, 0x0?}, 0x1?)
kv/kvserver/replica_closedts.go:263 â‹® [T1,n6] 2003 !	github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/stores.go:129 +0x96
kv/kvserver/replica_closedts.go:263 â‹® [T1,n6] 2003 !github.com/cockroachdb/cockroach/pkg/kv/kvserver/closedts/sidetransport.(*incomingStream).processUpdate(0xc004fff6b0, {0x6e7a3d0, 0xc006245d10}, 0xc003735a40)
kv/kvserver/replica_closedts.go:263 â‹® [T1,n6] 2003 !	github.com/cockroachdb/cockroach/pkg/kv/kvserver/closedts/sidetransport/receiver.go:252 +0x675
kv/kvserver/replica_closedts.go:263 â‹® [T1,n6] 2003 !github.com/cockroachdb/cockroach/pkg/kv/kvserver/closedts/sidetransport.(*incomingStream).Run.func1({0x6e7a3d0, 0xc006245d10})
kv/kvserver/replica_closedts.go:263 â‹® [T1,n6] 2003 !	github.com/cockroachdb/cockroach/pkg/kv/kvserver/closedts/sidetransport/receiver.go:328 +0x1b8
kv/kvserver/replica_closedts.go:263 â‹® [T1,n6] 2003 !github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunAsyncTaskEx.func2()
kv/kvserver/replica_closedts.go:263 â‹® [T1,n6] 2003 !	github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:470 +0x146
kv/kvserver/replica_closedts.go:263 â‹® [T1,n6] 2003 !created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunAsyncTaskEx
kv/kvserver/replica_closedts.go:263 â‹® [T1,n6] 2003 !	github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:461 +0x43b
```

I don't think the failure is related to the fact that we were using a `crdb_test` build per se, so I wanted to bring this to kv-repl's attention so that you can take a closer look.

I ran the test a couple more times and did not see the same issue happen again, but I can help with reproduction efforts if needed.

Artifacts (n6 is the one that crashes):
<https://teamcity.cockroachdb.com/viewLog.html?buildId=9006960&buildTypeId=Cockroach_Nightlies_RoachtestNightlyGceBazel&tab=artifacts#%2Ffailover%2Fnon-system%2Fblackhole-recv>

[1] #98351

Jira issue: CRDB-25452

### LINKED ISSUE #99931: roachtest: failover/system-non-liveness/blackhole-recv failed
roachtest.failover/system-non-liveness/blackhole-recv [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/9306440?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/9306440?buildTab=artifacts#/failover/system-non-liveness/blackhole-recv) on release-23.1 @ [a34af06d8e7230e4052db80d55da21a06013f81b](https://github.com/cockroachdb/cockroach/commits/a34af06d8e7230e4052db80d55da21a06013f81b):

```
test artifacts and logs in: /artifacts/failover/system-non-liveness/blackhole-recv/run_1
(cluster.go:1977).Run: output in run_131047.746528933_n7_cockroach-workload-r: ./cockroach workload run kv --read-percent 50 --duration 20m --concurrency 256 --max-rate 2048 --timeout 1m --tolerate-errors --histograms=perf/stats.json {pgurl:1-3} returned: context canceled
(monitor.go:127).Wait: monitor failure: monitor command failure: unexpected node event: 6: dead (exit status 7)
(cluster.go:1977).Run: cluster.RunE: context canceled
(cluster.go:1387).FailOnInvalidDescriptors: invalid descriptors check failed: pq: replica unavailable: (n4,s4):4 unable to serve request to r9:/Table/{5-6} [(n4,s4):4, (n5,s5):2, (n6,s6):3, next=7, gen=18]: lost quorum (down: (n5,s5):2,(n6,s6):3); closed timestamp: 1680096374.884386491,0 (2023-03-29 13:26:14); raft status: {"id":"4","term":13,"vote":"0","commit":120,"lead":"0","raftState":"StatePreCandidate","applied":120,"progress":{},"leadtransferee":"0"}: have been waiting 62.00s for slow proposal RequestLease [/Table/5,/Min)
```
<p>Parameters: <code>ROACHTEST_cloud=gce</code>
, <code>ROACHTEST_cpu=4</code>
, <code>ROACHTEST_encrypted=false</code>
, <code>ROACHTEST_fs=ext4</code>
, <code>ROACHTEST_localSSD=true</code>
, <code>ROACHTEST_ssd=0</code>
</p>
<details><summary>Help</summary>
<p>

See: [roachtest README](https://github.com/cockroachdb/cockroach/blob/master/pkg/cmd/roachtest/README.md)

See: [How To Investigate \(internal\)](https://cockroachlabs.atlassian.net/l/c/SSSBr8c7)

</p>
</details>
/cc @cockroachdb/kv-triage
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*failover/system-non-liveness/blackhole-recv.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)
</sub>

Jira issue: CRDB-26147

### LINKED ISSUE #100101: roachtest: failover/non-system/blackhole-recv failed
roachtest.failover/non-system/blackhole-recv [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/9329923?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/9329923?buildTab=artifacts#/failover/non-system/blackhole-recv) on release-23.1 @ [aec78f33d45a8376a0ecec885688bae60dbfb85c](https://github.com/cockroachdb/cockroach/commits/aec78f33d45a8376a0ecec885688bae60dbfb85c):

```
test artifacts and logs in: /artifacts/failover/non-system/blackhole-recv/run_1
(cluster.go:1977).Run: output in run_125335.248437892_n5_sudo-iptables-F: sudo iptables -F returned: context canceled
(cluster.go:1977).Run: output in run_124335.247893726_n7_cockroach-workload-r: ./cockroach workload run kv --read-percent 50 --duration 20m --concurrency 256 --max-rate 2048 --timeout 1m --tolerate-errors --histograms=perf/stats.json {pgurl:1-3} returned: context canceled
(monitor.go:127).Wait: monitor failure: monitor command failure: unexpected node event: 6: dead (exit status 7)
(cluster.go:1977).Run: cluster.RunE: context canceled
```
<p>Parameters: <code>ROACHTEST_cloud=gce</code>
, <code>ROACHTEST_cpu=4</code>
, <code>ROACHTEST_encrypted=false</code>
, <code>ROACHTEST_fs=ext4</code>
, <code>ROACHTEST_localSSD=true</code>
, <code>ROACHTEST_ssd=0</code>
</p>
<details><summary>Help</summary>
<p>

See: [roachtest README](https://github.com/cockroachdb/cockroach/blob/master/pkg/cmd/roachtest/README.md)

See: [How To Investigate \(internal\)](https://cockroachlabs.atlassian.net/l/c/SSSBr8c7)

</p>
</details>
/cc @cockroachdb/kv-triage
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*failover/non-system/blackhole-recv.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)
</sub>

Jira issue: CRDB-26249

Epic CRDB-27234

### PR DESCRIPTION
**Pull request by pav-kv**
The PROSCRIBED lease status, just like EXPIRED, puts a lease to a definitely invalid state. The UNUSABLE state (when request timestamp is in stasis period) is less of a clear cut: we still own the lease but callers may use or not use it depending on context.

For example, the closed timestamp side-transport ignores the UNUSABLE state (because we still own the lease), and takes it as usable for its purposes. Because of the order in which the checks were made, this has lead to a bug: a PROSCRIBED lease is reported as UNUSABLE during stasis periods, the closed timestamp side-transport then considers it usable, and updates closed timestamps when it shouldn't.

This commit fixes the bug by swapping the order of checks in the leaseStatus method. The order now goes from "hard" checks like EXPIRED and PROSCRIBED, to "softer" UNUSABLE, and (when the softness is put to the limit) VALID.

Fixes #98698
Fixes #99931
Fixes #100101
Epic: none

Release note (bug fix): a bug is fixed in closed timestamp updates within its side-transport. Previously, during asymmetric partitions, a node that transfers a lease away, and misses a liveness heartbeat, could then erroneously update the closed timestamp during the stasis period of its liveness. This could lead to closed timestamp invariant violation, and node crashes; in extreme cases this could lead to inconsistencies in read-only queries.

### CODE REVIEW

**Comment by erikgrinaker** [comment]
>some callers may treat it as invalid, and some may thinks it's still valid.

It isn't really considered valid as such, I think the crucial point is that it's treated as _ours_. A `PROSCRIBED` lease isn't still ours because we may have transferred it away, but an `UNUSABLE` lease is still ours for the interval even though we can't use it (noone else can have an overlapping lease).

This probably also deserves a test case for the precedence.

**Comment by pavelkalinnikov** [comment]
Yeah, adding test in the meantime. Wanted to put the fix for review ASAP.

File: pkg/kv/kvserver/replica_range_lease.go [hunk 1]
```diff
@@ -615,21 +615,21 @@ func (p *pendingLeaseRequest) newResolvedHandle(pErr *kvpb.Error) *leaseRequestH
 // EXPIRED status is that it reflects that a new lease with a start timestamp
 // greater than or equal to now can be acquired non-cooperatively.
 //
-// If the lease is not EXPIRED, the request timestamp is taken into account. The
-// expiration timestamp is adjusted for clock offset; if the request timestamp
-// falls into the so-called "stasis period" at the end of the lifetime of the
-// lease, or if the request timestamp is beyond the end of the lifetime of the
-// lease, the status is UNUSABLE. Callers typically want to react to an UNUSABLE
-// lease status by extending the lease, if they are in a position to do so.
+// For non-expired leases, the lease's start timestamp is checked against the
```
Comment (erikgrinaker) [inline pkg/kv/kvserver/replica_range_lease.go:618]:
```suggestion
// If the lease is not EXPIRED, the lease's start timestamp is checked against the
```

**Review by erikgrinaker — APPROVED** [review]
LGTM modulo my comment above about valid/owned and a test.

**Comment by erikgrinaker** [comment]
How does this interact with clock skew, btw? The stasis period exists because it's possible for someone else to believe their lease has already started while we also believe that ours hasn't ended. Can this also cause violations, such that we should exclude the `UNUSABLE` state from the side transport entirely, or is this handled by the closed timestamp protocol?

**Comment by pavelkalinnikov** [comment]
@erikgrinaker Is your question basically: why [this](https://github.com/cockroachdb/cockroach/blob/793b4c8bfc6e9dbf7a05289f3e61035796476cc5/pkg/kv/kvserver/replica_closedts.go#L61-L62) comment? I don't know, it would be nice to explain in this comment why it's safe to close timestamps in the stasis.

I think the reason it's ok is that the closed timestamp are "logical". They fall between the lease start and expiration timestamp. They aren't concerned with clock skew? Stasis is there to make sure there aren't **requests** served around the lease transfer times?

**Comment by erikgrinaker** [comment]
> Yeah, I think it's the LAI that saves us, because presumably an unusable lease can't increment the LAI.

Does it though? In the scenario we've seen, the old leaseholder must have been able to increment its LAI, despite the lease being in `PROSCRIBED` and then `UNUSABLE`, otherwise we wouldn't have seen the regression.

I think the coordination here happens either by a lease transfer revoking the current lease (which will/should immediately halt the closed ts transport from sending future updates), or by the next lease necessarily having a greater start time than our expiration time, where the LAI is communicated via Raft, and the side transport is prevented from sending further updates beyond the expiration time. So the problem is simply that we keep sending updates after we transferred the lease, which we fix here. So I don't think `UNUSABLE` is a problem here.

There's also this:

https://github.com/cockroachdb/cockroach/blob/bfc5603a3cfb98e4172a201d3ff9d44a213adb2f/pkg/kv/kvserver/kvserverpb/lease_status.go#L51-L53

**Comment by pavelkalinnikov** [comment]
> Does it though? In the scenario we've seen, the old leaseholder must have been able to increment its LAI, despite the lease being in `PROSCRIBED` and then `UNUSABLE`, otherwise we wouldn't have seen the regression.

The old leaseholder was sending the old LAI. But the timestamp was high, getting into the territory of the next lease.
The new leaseholder was sending new LAIs, and later timestamps (which is a correct behaviour).

**Comment by tbg** [comment]
> I think the reason it's ok is that the closed timestamps are "logical". They fall between the lease start and expiration timestamp. 

Are you sure that's true? I don't think closed timestamps are constrained to the by the lease start, as the lease plays no role here:

https://github.com/cockroachdb/cockroach/blob/fad7ac8303582228b010375c60820d4a6a798570/pkg/kv/kvserver/closedts/sidetransport/sender.go#L331-L338

We do make sure that the resulting timestamp isn't past the lease expiration,

https://github.com/cockroachdb/cockroach/blob/793b4c8bfc6e9dbf7a05289f3e61035796476cc5/pkg/kv/kvserver/replica_closedts.go#L68-L71

but I don't see a corresponding check for the start time.

Assuming a fixed closed timestamp lag time L, I agree that continuing to close during stasis doesn't seem to be an issue. The largest timestamp that can be closed by the old leaseholder is `endStasis-L` and the new leaseholder can only close `>= nextLeaseStart-L` (with the same or larger LAI). So these can't invert, I think this is morally what you're saying with the start time, but `nextLeaseStart-L` is clearly "in some old lease".

But also, closed timestamp lag time is a cluster setting and propagates async, so can't the old leaseholder be closing out `endStasis - L` but the new leaseholder closes out `nextLeaseStart - 10L` (cluster setting set to 10x the original)? These can obviously invert...

**Comment by tbg** [comment]
I'm probably missing something in that last bit because shouldn't changing the cluster setting trigger the assertion even if no lease changes hands then? Since the leaseholder's closed timestamp will regress against itself.

**Review by tbg — APPROVED** [review]

File: pkg/kv/kvserver/replica_range_lease_test.go [hunk 2]
```diff
@@ -0,0 +1,150 @@
...
+	r1 := roachpb.ReplicaDescriptor{NodeID: 1, StoreID: 1, ReplicaID: 1}
+	ts := []hlc.ClockTimestamp{
+		{WallTime: 500, Logical: 0},  // before lease start
+		{WallTime: 1000, Logical: 0}, // lease start
+		{WallTime: 2000, Logical: 0}, // within lease
+		{WallTime: 2950, Logical: 0}, // within stasis
+		{WallTime: 3000, Logical: 0}, // lease expiration
+		{WallTime: 3500, Logical: 0}, // expired
+		{WallTime: 5000, Logical: 0}, // next expiration
+	}
```
Comment (erikgrinaker) [inline pkg/kv/kvserver/replica_range_lease_test.go:55]: nit: Would be good to name these. It's hard to read the integer indexes below.

File: pkg/kv/kvserver/replica_range_lease_test.go [hunk 3]
```diff
@@ -0,0 +1,150 @@
...
+		// Epoch-based lease, VALID.
+		{lease: epoLease, now: ts[2], liveness: curLiveness, want: kvserverpb.LeaseState_VALID},
+
+		// Epoch-based lease, ERROR.
+		{lease: epoLease, now: ts[2], want: kvserverpb.LeaseState_ERROR,
+			wantErr: "liveness record not found"},
+		{lease: epoLease, now: ts[2], liveness: oldLiveness, want: kvserverpb.LeaseState_ERROR,
+			wantErr: "node liveness info for n1 is stale"},
+	} {
+		t.Run("", func(t *testing.T) {
```
Comment (erikgrinaker) [inline pkg/kv/kvserver/replica_range_lease_test.go:125]: nit: Instead of comments above the test cases, consider adding a `desc` field and use that as the test name too. It's annoying to debug failures when you have to count to find the correct case.

**Review by erikgrinaker — APPROVED** [review]
LGTM. A couple of test nits, but we can address those in a follow-up PR. Thanks for adding this test!

**Comment by pavelkalinnikov** [comment]
TFTRs!

bors r=erikgrinaker,tbg
