### PR TITLE
rttanalysis: fix timeout for BenchmarkVirtualTableQueries

### LINKED ISSUE #161766: pkg/bench/rttanalysis: BenchmarkVirtualTableQueries failed
pkg/bench/rttanalysis.BenchmarkVirtualTableQueries [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachprodMicrobenchmarkWeeklyWip/21021417?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachprodMicrobenchmarkWeeklyWip/21021417?buildTab=artifacts#./artifacts/microbench/experiment) on master @ [867004a4311025b7e0de44bc8c72fcbc8442f041](https://github.com/cockroachdb/cockroach/commits/867004a4311025b7e0de44bc8c72fcbc8442f041):

```
BenchmarkVirtualTableQueries timed out after 20m1s
```
<details><summary>Help</summary>
<p>

See also: [How To Investigate a Go Test Failure \(internal\)](https://cockroachlabs.atlassian.net/l/c/HgfXfJgM)
</p>
</details>
/cc @cockroachdb/sql-foundations
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*BenchmarkVirtualTableQueries.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/bazci/githubpost/issues)

</sub>

Jira issue: CRDB-59067

### PR DESCRIPTION
**Pull request by fqazi**
Previously, versions of BenchmarkVirtualTableQueries ran for nightly benchmark comparisons could fail because this test is fairly slow. To address this, this patch limits the number of iterations, and improves logic inside the create trigger test. The show_create_trigger test would previously create a 100 triggers serially, which would take a long time, versus a single transaction. With these changes the benchmark completes in ~700 seconds.

Fixes: #161766

Release note: None

### CODE REVIEW

File: pkg/bench/rttanalysis/orm_queries_bench_test.go [hunk 1]
```diff
@@ -1165,17 +1170,27 @@ BEGIN
 END;
 $$ LANGUAGE plpgsql;
 `)
+	// Second Exec: SET first so session has unsafe_always, then BEGIN; COMMIT; so
+	// resetExtraTxnState runs and schemaChangerState is recreated with that mode,
+	// then BEGIN; CREATE TRIGGER... COMMIT; so triggers use the declarative schema changer.
+	createTrigger.WriteString("SET use_declarative_schema_changer = 'unsafe_always';")
+	createTrigger.WriteString("SET autocommit_before_ddl = false;")
+	createTrigger.WriteString("BEGIN; COMMIT;")
```
Comment (rafiss) [inline pkg/bench/rttanalysis/orm_queries_bench_test.go]: is this `begin; commit;` line actually needed? that's pretty surprising.

File: pkg/bench/rttanalysis/virtual_table_bench_test.go [hunk 2]
```diff
@@ -11,6 +11,11 @@ import (
 	"github.com/cockroachdb/cockroach/pkg/sql/scheduledlogging"
 )
 
+// BenchmarkVirtualTableQueries is a benchmark for the crdb_internal virtual tables.
+// It is used to test the performance of the crdb_internal virtual tables used by
+// SHOW CREATE ALL ROUTINES, SHOW CREATE ALL TRIGGERS, and scheduled telemetry logging.
+// Limit the number of iterations to 20x to avoid timing out on CI.
+// benchmark-ci: benchtime=20x
```
Comment (rafiss) [inline pkg/bench/rttanalysis/virtual_table_bench_test.go:18]: this new annotation seems useful. did it help? can you apply it to all the other rttanalysis benchmarks?

File: pkg/bench/rttanalysis/orm_queries_bench_test.go [hunk 3]
```diff
@@ -1165,17 +1170,27 @@ BEGIN
...
+	createTrigger.WriteString("BEGIN;")
 	for i := 0; i < n; i++ {
 		b.WriteString(fmt.Sprintf(`
 CREATE TABLE t%d (a INT, b INT);
-
+`, i))
+		createTrigger.WriteString(fmt.Sprintf(`
```
Comment (rafiss) [inline pkg/bench/rttanalysis/orm_queries_bench_test.go]: using one big string for all the create statements isn't needed now. let's break it into individual slice appends.

e.g. it could be:
```
  stmts := []string{b.String()}
  stmts = append(stmts, "SET use_declarative_schema_changer = 'unsafe_always'")
  stmts = append(stmts, "SET autocommit_before_ddl = false")
  stmts = append(stmts, "BEGIN")
  for i := 0; i < n; i++ {
      stmts = append(stmts, fmt.Sprintf(`CREATE TRIGGER trigger_%d ...`, i, i))
  }
  stmts = append(stmts, "COMMIT")
  return stmts
```

File: pkg/bench/rttanalysis/orm_queries_bench_test.go (hunk 1 above)
Comment (fqazi) [reply pkg/bench/rttanalysis/orm_queries_bench_test.go]: Done.

This wasn't needed.

File: pkg/bench/rttanalysis/orm_queries_bench_test.go (hunk 3 above)
Comment (fqazi) [reply pkg/bench/rttanalysis/orm_queries_bench_test.go]: Done.

File: pkg/bench/rttanalysis/virtual_table_bench_test.go (hunk 2 above)
Comment (fqazi) [reply pkg/bench/rttanalysis/virtual_table_bench_test.go:18]: Done.

I applied this to a number of other tests in the same package, along with comment headers.

**Review by fqazi — COMMENTED** [review]
> @fqazi made 3 comments.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/165823)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on rafiss).

**Review by rafiss — APPROVED** [review]
:lgtm:

> @rafiss made 1 comment.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/165823#-:-OoVTNcy2IBTHs9N7wwL:bnfp4nl)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained.
