### PR TITLE
acceptance: Move HostConfig.NetworkMode setting into createContainer

### LINKED ISSUE #4894: circleci: docker flakiness
Every now and then (but often enough to fail a significant amount of builds due to the sheer volume of iterations this bug gets), Gossip doesn't join up:
```
I160306 00:51:43.699152 cli/start.go:129  [build] alpha.v1-676-g3325b63 @ 2016/03/06 00:37:29 (go1.6)
I160306 00:51:43.701589 server/context.go:223  1 storage engine initialized
I160306 00:51:43.701841 cli/start.go:143  starting cockroach node
E160306 00:51:43.896722 gossip/gossip.go:733  invalid bootstrap address: &{typ:tcp addr:roach0.local:26257 exhausted:false}, lookup roach0.local: no such host
I160306 00:51:43.900384 storage/engine/rocksdb.go:106  opening rocksdb instance at "/data2.0"
I160306 00:51:43.909866 server/node.go:353  store store=0:0 ([]=/data2.0) not bootstrapped
I160306 00:51:43.910160 storage/stores.go:289  read 0 node addresses from persistent storage
I160306 00:51:43.911156 server/node.go:486  connecting to gossip network to verify cluster ID...
```

Note `E160306 00:51:43.896722 gossip/gossip.go:733  invalid bootstrap address: &{typ:tcp addr:roach0.local:26257 exhausted:false}, lookup roach0.local: no such host` which suggests that there's maybe a DNS issue with `docker-spy` and a subsequent failure in Gossip to retry in a speedy manner.

Repros locally, for example

```
while [ $? -eq 0 ]; do rm -rf ./acceptance/Test*; make acceptance TESTS=GossipPeerings TESTFLAGS='-v -l .'; done
```

### PR DESCRIPTION
**Pull request by bdarnell**
This puts the containers used for cross-language testing on the same
network as the nodes and gets the tests passing reliably for me.
(I don't understand why the tests were passing some of the time before).

Removed redundant alias specification and restricted the DNS search path
to avoid querying outside networks.

Fixes #4894

[Review on Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/4953)

### CODE REVIEW

**Comment by tamird** [comment]
LGTM

File: acceptance/cluster/localcluster.go [hunk 1]
```diff
@@ -336,7 +335,6 @@ func (l *LocalCluster) createRoach(node *testNode, vols *Container, cmd ...strin
 
 	hostConfig := container.HostConfig{
 		PublishAllPorts: true,
-		NetworkMode:     container.NetworkMode(l.networkID),
```
Comment (petermattis) [inline acceptance/cluster/localcluster.go]: How is `l.networkID` being used after this removal?

Comment (tamird) [inline acceptance/cluster/localcluster.go]: It's in createContainer (as mentioned in the commit message)

Comment (petermattis) [inline acceptance/cluster/localcluster.go]: Ah, just missed that (I read the commit message, but wasn't reading the code properly).

**Comment by petermattis** [comment]
LGTM. Did you test this with a fouled up "domain" specification in `/etc/resolv.conf` like I had?

**Comment by bdarnell** [comment]
I've added two new commits that seem to have fixed the issues that were blocking this PR (but I've had to rebuild several times to get green, for failures that are not obviously related). I don't quite understand how things were working before; the old code just looks wrong to me.

**Comment by tamird** [comment]
Reviewed 2 of 2 files at r1, 2 of 2 files at r2, 2 of 2 files at r3, 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4953)*

**Comment by tschottdorf** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r3, 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4953#-:-KCTu1SuC1xtQE1yrK2_:1417088721)*

**Comment by petermattis** [comment]
LGTM
