### PR TITLE
storage: Fix circuit breaker flake in TestReplicateReAddAfterDown

### LINKED ISSUE #10758: teamcity: failed tests on master: test/TestReplicateReAddAfterDown
The following tests appear to have failed:

[#50491](https://teamcity.cockroachdb.com/viewLog.html?buildId=50491):

```
--- FAIL: test/TestReplicateReAddAfterDown (0.003s)
	client_test.go:927: [n1,s1,r1/1:/M{in-ax}]: change replicas aborted due to failed preemptive snapshot: breaker open

```
Please assign, take a look and update the issue accordingly.

### PR DESCRIPTION
**Pull request by a-robinson**
Fixes #10758. It's very possible that fixing the circuit breaker will cause other flakes in our code base to become more frequent, so feel free to point me at anything that seems to have gotten worse lately and I'll take a look. We may want to start injecting circuit breakers that won't trip into RaftTransport for the sake of avoiding flakes like this.

As for the mechanism of the fix, it might seem like it'd be better to add retries to [the call that's being blocked by the circuit breaker](https://github.com/cockroachdb/cockroach/blob/master/pkg/storage/client_test.go#L918), but we don't really know how many times to retry given that the circuit breaker's backoff is based on time rather than number of attempts.

@tamird

---
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/10773)

### CODE REVIEW

File: pkg/storage/client_raft_test.go [hunk 1]
```diff
@@ -2363,6 +2363,16 @@ func TestReplicateReAddAfterDown(t *testing.T) {
...
 
+	// Disable the raft transport circuit breakers from ever tripping in order to
+	// prevent errors from when a store is down from causing a connection attempt
+	// to get rejected after the store is back up. This is needed because
+	// mtc.replicateRange calls log.Fatal if any single attempt to send an
+	// ADD_REPLICA request fails.
+	downedStoreIdx := 2
+	for _, transport := range mtc.transports {
+		transport.GetCircuitBreaker(roachpb.NodeID(downedStoreIdx + 1)).ShouldTrip = nil
+	}
```
Comment (petermattis) [inline pkg/storage/client_raft_test.go]: I wonder if this should be done inside `multiTestContext` itself.

**Review by petermattis — APPROVED** [review]
LGTM

File: pkg/storage/client_raft_test.go (hunk 1 above)
Comment (a-robinson) [inline pkg/storage/client_raft_test.go]: Yeah, I was wondering that too. I played around with doing it for resetting circuit breakers before realizing that resetting them wasn't enough. I've moved this back into a helper.

File: pkg/storage/client_test.go [hunk 2]
```diff
@@ -841,6 +841,18 @@ func (m *multiTestContext) restartStore(i int) {
...
+// reject requests just because past connections to the given store have failed.
+// If you're stopping store and restarting them, you may want to use this to
+// ensure that errors from when the store was down don't cause other nodes to
+// avoid opening new connections to it.
+func (m *multiTestContext) disableCircuitBreakersToStore(i int) {
+	nodeID := roachpb.NodeID(i + 1)
+	for _, transport := range m.transports {
+		transport.GetCircuitBreaker(nodeID).ShouldTrip = nil
+	}
+}
```
Comment (petermattis) [inline pkg/storage/client_test.go]: This is cleaner, but I was actually wondering if we should always disable circuit breakers in `multiTestContext`-based tests. Is it useful to be testing them there? We already have this funky transport in `multiTestContext`.

Comment (a-robinson) [inline pkg/storage/client_test.go]: Ah, yeah. That's basically what I was wondering about in my PR description. It'd be a little clunky to do it like this, though, since we'd have to do it for the cross-product of nodes, and some nodes can be added after the multiTestContext is created.

We'd want to change the way the breakers are constructed. I was thinking that may involve a fair amount of work so I was just proposing it rather than doing it, but now I see that we already have a BreakerFactory in place :) Switched over to always disabling the breakers. I've been running `make stress` on the storage package for about five minutes now after making this change and still haven't run into any failures, so it looks like this may not have broken any tests' assumptions, which is a pleasant surprise.

**Comment by petermattis** [comment]
:lgtm:

I see that `TestReportUnreachableHeartbeats` manually trips a circuit breaker. Does that still work? Seems like it should, just want to verify.

---

Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10773#-:-KWnnENLCgHXV15E83ti:b-2pj6uk)*

**Comment by a-robinson** [comment]
Yeah, that still works just fine.

**Comment by tamird** [comment]
Reviewed 1 of 2 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[pkg/storage/client_test.go, line 849 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/10773#-KWoJK14h-s10OdDSO2r:-KWoJK15htk3UkGOnJ45:b8qd689) ([raw file](https://github.com/cockroachdb/cockroach/blob/e01b5e1cbd376ed99b4a1dae9c3fe8d045e6b846/pkg/storage/client_test.go#L849)):*
> ```Go
> // ensure that errors from when the store was down don't cause other nodes to
> // avoid opening new connections to it.
> func (m *multiTestContext) disableCircuitBreakersToStore(i int) {
> ```

is this in the wrong commit? woof, and then it's gone in the next commit.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10773)*

**Comment by a-robinson** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[pkg/storage/client_test.go, line 849 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/10773#-KWoJK14h-s10OdDSO2r:-KWoLa-S4gtma5hUyNtc:b7ha7v4) ([raw file](https://github.com/cockroachdb/cockroach/blob/e01b5e1cbd376ed99b4a1dae9c3fe8d045e6b846/pkg/storage/client_test.go#L849)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> is this in the wrong commit? woof, and then it's gone in the next commit.
</details>
Whoops, my bad.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10773)*
