### PR TITLE
ccl/multiregionccl: TestRegionLivenessProber fix flake

### LINKED ISSUE #116629: ccl/multiregionccl: TestRegionLivenessProber failed
ccl/multiregionccl.TestRegionLivenessProber [failed](https://tanzanite.cluster.engflow.com/invocations/default/628f4b1e-e8b7-41f6-a501-bf15569cbdae?testReportRun=16&testReportShard=11&testReportAttempt=1#targets-Ly9wa2cvY2NsL211bHRpcmVnaW9uY2NsOm11bHRpcmVnaW9uY2NsX3Rlc3Q=) on master @ [1f53a61732c6f9e48622f45d276eb5e1c343ad30](https://github.com/cockroachdb/cockroach/commits/1f53a61732c6f9e48622f45d276eb5e1c343ad30):

```
=== RUN   TestRegionLivenessProber
    test_log_scope.go:170: test logs captured to: outputs.zip/logTestRegionLivenessProber1923685213
    test_log_scope.go:81: use -show-logs to present logs inline

pkg/ccl/multiregionccl_test/pkg/ccl/multiregionccl/regionliveness_test.go:93: (TestRegionLivenessProber)
	NOTICE: .Locality() called via implicit interface ApplicationLayerInterface;
HINT: consider using .ApplicationLayer().Locality() instead.
TIP: consider replacing the test server initialization from:
    ts, ... := serverutils.StartServer(t, ...)
    defer ts.Stopper().Stop(...)
to:
    srv, ... := serverutils.StartServer(t, ...)
    defer srv.Stopper().Stop(...)
    ts := srv.ApplicationLayer()

See also: https://go.crdb.dev/p/testserver-and-cluster-virtualization

pkg/ccl/multiregionccl_test/pkg/ccl/multiregionccl/regionliveness_test.go:93: (TestRegionLivenessProber)
	NOTICE: .Locality() called via implicit interface ApplicationLayerInterface;
HINT: consider using .ApplicationLayer().Locality() instead.
TIP: consider replacing the test server initialization from:
    ts, ... := serverutils.StartServer(t, ...)
    defer ts.Stopper().Stop(...)
to:
    srv, ... := serverutils.StartServer(t, ...)
    defer srv.Stopper().Stop(...)
    ts := srv.ApplicationLayer()

See also: https://go.crdb.dev/p/testserver-and-cluster-virtualization

pkg/ccl/multiregionccl_test/pkg/ccl/multiregionccl/regionliveness_test.go:93: (TestRegionLivenessProber)
	NOTICE: .Locality() called via implicit interface ApplicationLayerInterface;
HINT: consider using .ApplicationLayer().Locality() instead.
TIP: consider replacing the test server initialization from:
    ts, ... := serverutils.StartServer(t, ...)
    defer ts.Stopper().Stop(...)
to:
    srv, ... := serverutils.StartServer(t, ...)
    defer srv.Stopper().Stop(...)
    ts := srv.ApplicationLayer()

See also: https://go.crdb.dev/p/testserver-and-cluster-virtualization
    regionliveness_test.go:115: 
        	Error Trace:	github.com/cockroachdb/cockroach/pkg/ccl/multiregionccl_test/pkg/ccl/multiregionccl/regionliveness_test.go:115
        	Error:      	Received unexpected error:
        	            	pq: count-lease timed out reading from a region: operation "count-leases-region" timed out after 501ms (given timeout 500ms): count-leases: failed to read query result: query execution canceled
        	Test:       	TestRegionLivenessProber
    panic.go:523: -- test log scope end --
test logs left over in: outputs.zip/logTestRegionLivenessProber1923685213
--- FAIL: TestRegionLivenessProber (69.09s)
```

Parameters:
 - <code>attempt=1</code>
 - <code>run=16</code>
 - <code>shard=11</code>
<details><summary>Help</summary>
<p>

See also: [How To Investigate a Go Test Failure \(internal\)](https://cockroachlabs.atlassian.net/l/c/HgfXfJgM)
</p>
</details>
/cc @cockroachdb/sql-foundations
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*TestRegionLivenessProber.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)
</sub>

Jira issue: CRDB-34695

### PR DESCRIPTION
**Pull request by fqazi**
This patch does the following to improve test reliability:

1. Moves the regionliveness table timeout interval into a clustersetting, so it can be adjusted after the setup phase. This is a generally useful change, since it allows this timeout to be fully tuneable.
2. Updates TestRegionLivenessProber to adopt this new cluster setting after the setup phase is complete. Reducing the surface area that the shorter timeout used by the test applies. Additionally, the timeout is increased to reduce the odds of it triggering as well.

Fixes: #116629

### CODE REVIEW

**Review by rafiss — COMMENTED** [review]
hm i'm not sure i follow. why is the cluster setting less flaky than the testing hook?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/116842#-:-Nm76VDuCcfDSnshoYJB:bwqatm)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained

**Review by fqazi — COMMENTED** [review]
Its more a surface area reduction, since it only applies on parts of the test that need the shorter probe interval

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/116842#-:-Nm76jMW4yfue4nK4-Qx:b-1qq1yi)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained

File: pkg/ccl/multiregionccl/regionliveness_test.go [hunk 1]
```diff
@@ -43,6 +43,10 @@ import (
 	"github.com/stretchr/testify/require"
 )
 
+const (
+	TestingRegionLivenessProbeTimeout = time.Second * 2
```
Comment (rafiss) [inline pkg/ccl/multiregionccl/regionliveness_test.go:47]: nit: this should be lower-case

File: pkg/sql/regionliveness/prober.go [hunk 2]
```diff
@@ -38,6 +38,12 @@ var RegionLivenessEnabled = settings.RegisterBoolSetting(settings.ApplicationLev
 	false, /* disabled */
 	settings.WithVisibility(settings.Reserved))
 
+var RegionLivenessProbeTimeout = settings.RegisterDurationSetting(settings.ApplicationLevel,
+	"sql.region_liveness.probe.timeout",
+	"enables region liveness for system databases (experimental)",
```
Comment (rafiss) [inline pkg/sql/regionliveness/prober.go:43]: the description is incorrect - this is a timeout, not an enable/disable. also, i think we can remove the word experimental from this description, since this is a hidden setting anyway

File: pkg/sql/regionliveness/prober.go [hunk 3]
```diff
@@ -206,7 +203,8 @@ func (l *livenessProber) QueryLiveness(ctx context.Context, txn *kv.Txn) (LiveRe
 // GetTableTimeout gets maximum timeout waiting on a table before issuing
 // liveness queries.
 func (l *livenessProber) GetTableTimeout() (bool, time.Duration) {
```
Comment (rafiss) [inline pkg/sql/regionliveness/prober.go:205]: nit: i think `GetTableTimeout` is a strange name. would `GetProbeTimeout` make more sense?

File: pkg/ccl/multiregionccl/regionliveness_test.go [hunk 4]
```diff
@@ -114,6 +117,11 @@ func TestRegionLivenessProber(t *testing.T) {
 		_, err = tenantSQL[0].Exec(fmt.Sprintf("ALTER DATABASE system ADD REGION '%s'", expectedRegions[i]))
 		require.NoError(t, err)
 	}
+	// Override the table timeout probe for testing.
```
Comment (rafiss) [inline pkg/ccl/multiregionccl/regionliveness_test.go:120]: would we need to override it in the system tenant too?

**Review by rafiss — CHANGES_REQUESTED** [review]

**Review by fqazi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/116842)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @fqazi and @rafiss)

___
*[`pkg/sql/regionliveness/prober.go` line 43 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/116842#gh-1432965284:-Nm7j2e91aVHw6otnpgQ:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/56e19a4ecfe8dcc10118b78feb138bb278ef3489/pkg/sql/regionliveness/prober.go#L43)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

the description is incorrect - this is a timeout, not an enable/disable. also, i think we can remove the word experimental from this description, since this is a hidden setting anyway
</blockquote></details>

Done.
___
*[`pkg/ccl/multiregionccl/regionliveness_test.go` line 120 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/116842#gh-1432967151:-Nm7hy0i-Xpoxcsj2ema:b7i0qxu) ([raw file](https://github.com/cockroachdb/cockroach/blob/56e19a4ecfe8dcc10118b78feb138bb278ef3489/pkg/ccl/multiregionccl/regionliveness_test.go#L120)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

would we need to override it in the system tenant too?
</blockquote></details>

The failure is only simulated on the tenant so it should be good.

**Review by rafiss — APPROVED** [review]
> Reviewed 2 of 3 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/116842)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @fqazi)

**Comment by fqazi** [comment]
bore r+

@rafiss TFTR!
