### PR TITLE
roachtest: skip loading `version` key from `system.tenant_settings`

### LINKED ISSUE #126619: roachtest: backup-restore/mixed-version failed
roachtest.backup-restore/mixed-version [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/15916952?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/15916952?buildTab=artifacts#/backup-restore/mixed-version) on master @ [7461a85f839c50edbdea502fe09794739a99632e](https://github.com/cockroachdb/cockroach/commits/7461a85f839c50edbdea502fe09794739a99632e):

```
(mixedversion.go:620).Run: mixed-version test failure while running step 47 (run "verify all backups"): 4 errors during restore:
1: master: backup 5_v24.1.1-to-master_full-planned-and-executed-on-master-incremental-planned-and-executed-on-v24.1.1_cluster: restored system table system.tenant_settings is missing a row: ["2023-04-27T21:42:08.92022","version",null,0,"\u0012\b\b\u0016\u0010\u0002\u0018\u0000 b","m"] (artifacts collected in restore_failure_1)
2: master: backup 6_v24.1.1-to-master_all-planned-on-master-executed-on-v24.1.1_cluster: restored system table system.tenant_settings is missing a row: ["2023-04-27T21:42:08.92022","version",null,0,"\u0012\b\b\u0016\u0010\u0002\u0018\u0000 b","m"] (artifacts collected in restore_failure_2)
3: master: backup 7_v24.1.1-to-master_full-planned-and-executed-on-v24.1.1-incremental-planned-and-executed-on-master_cluster: restored system table system.tenant_settings is missing a row: ["2023-04-27T21:42:08.92022","version",null,0,"\u0012\b\b\u0016\u0010\u0002\u0018\u0000 b","m"] (artifacts collected in restore_failure_3)
4: master: backup 8_v24.1.1-to-master_full-planned-and-executed-on-master-incremental-planned-and-executed-on-v24.1.1_cluster: restored system table system.tenant_settings is missing a row: ["2023-04-27T21:42:08.92022","version",null,0,"\u0012\b\b\u0016\u0010\u0002\u0018\u0000 b","m"] (artifacts collected in restore_failure_4)
test artifacts and logs in: /artifacts/backup-restore/mixed-version/run_1
```

Parameters:
 - <code>ROACHTEST_arch=amd64</code>
 - <code>ROACHTEST_cloud=gce</code>
 - <code>ROACHTEST_coverageBuild=false</code>
 - <code>ROACHTEST_cpu=4</code>
 - <code>ROACHTEST_encrypted=true</code>
 - <code>ROACHTEST_fs=ext4</code>
 - <code>ROACHTEST_localSSD=true</code>
 - <code>ROACHTEST_metamorphicBuild=false</code>
 - <code>ROACHTEST_ssd=0</code>
<details><summary>Help</summary>
<p>

See: [roachtest README](https://github.com/cockroachdb/cockroach/blob/master/pkg/cmd/roachtest/README.md)

See: [How To Investigate \(internal\)](https://cockroachlabs.atlassian.net/l/c/SSSBr8c7)

See: [Grafana](https://go.crdb.dev/roachtest-grafana/teamcity-15916952/backup-restore-mixed-version/1719986026110/1719992737255)

</p>
</details>
<details><summary>Same failure on other branches</summary>
<p>

- #125677 roachtest: backup-restore/mixed-version failed [C-test-failure O-roachtest O-robot T-disaster-recovery branch-release-23.1 release-blocker]
</p>
</details>
/cc @cockroachdb/disaster-recovery
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*backup-restore/mixed-version.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/bazci/githubpost/issues)
</sub>

Jira issue: CRDB-40008

### PR DESCRIPTION
**Pull request by renatolabs**
When validating cluster restores, we no longer want to ensure that the `version` key in the `system.tenant_settings` table is restored. As of the changes in #125881, that row is no longer restored.

Fixes: #126619

Release note: None

### CODE REVIEW

File: pkg/cmd/roachtest/tests/mixed_version_backup.go [hunk 1]
```diff
@@ -804,10 +815,23 @@ func (sc *systemTableContents) commentsHandler(
...
 }
 
+// tenantSettingsHandler deletes a `version` key from the
+// system.tenant_settings table, if any. This row is not restored as
+// of 24.2+ so it shouldn't be validated after restore.
+func (sc *systemTableContents) tenantSettingsHandler(
+	values []interface{}, columns []string,
+) ([]interface{}, error) {
+	return newSystemTableRow(sc.table, values, columns).
+		Matches("name", "version").
```
Comment (srosenberg) [inline pkg/cmd/roachtest/tests/mixed_version_backup.go:825]: The _name_ of the column we want is `name`? 🤯

**Review by srosenberg — APPROVED** [review]

**Review by stevendanna — APPROVED** [review]

**Comment by renatolabs** [comment]
TFTRs!

bors r=srosenberg,stevendanna
