### PR TITLE
spanset: assert that batches don't access store local and unreplicated RangeID local keys

### LINKED ISSUE #156537: kvserver: assert on log engine keys in eval
For RSE, we want the invariant that command evaluation at the leaseholder produces batches that can only touch state machine engine keys. Or, easier to enumerate (there are only 3), it should not touch the raft engine keys.

https://github.com/cockroachdb/cockroach/blob/345a86b3fd12440eb33ad3f4bdd438032ea758c4/pkg/keys/doc.go#L191-L211

We know of 2 exceptions when raft engine keys are written into the eval batch, and work around them. For confidence, it would be good to confirm that there no other exceptions, or find all.

The mechanism to do that would be similar to the `spanset.Batch` here, which asserts on keys in relation to the latches: 

https://github.com/cockroachdb/cockroach/blob/345a86b3fd12440eb33ad3f4bdd438032ea758c4/pkg/kv/kvserver/replica_write.go#L811-L818

Epic: CRDB-55220

Jira issue: CRDB-56053

### PR DESCRIPTION
**Pull request by iskettaneh**
This PR adds the following test-only assertions:
1) Generated batches don't touch store-local keys.
2) Generated batches don't touch unreplicated RangeID local keys.

We disable the check in exactly 3 locations we know that we currently
touch those keys.

Fixes: #156537

Release note: None

### CODE REVIEW

File: pkg/kv/kvserver/replica_write.go [hunk 1]
```diff
@@ -884,3 +889,132 @@ func releaseMVCCStats(ms *enginepb.MVCCStats) {
...
+func overlapsStoreLocalKeys(span roachpb.Span) error {
+	// If we receive a nil start key. It means that the span is effectively:
+	// {endKey.Prev(), endKey}. However, since we can't get the Prev() key, we
+	// set the startKey pessimistically to Prevish(roachpb.PrevishKeyLength).
+	if span.Key == nil {
+		span.Key = span.EndKey.Prevish(roachpb.PrevishKeyLength)
+	}
+
+	if span.EndKey == nil {
+		span.EndKey = span.Key.Next()
```
Comment (pav-kv) [inline pkg/kv/kvserver/replica_write.go]: This could allocate twice. Not a huge deal in tests, but still: how about doing the comparisons statelessly? Could we use the existing `overlaps` func? Also, we can probably avoid `Prevish`. 

For the `{Key: nil, EndKey: x}` case, essentially, the bad case is `start < x <= end` (as opposed to `start <= x < end` for `{Key: x, EndKey: nil}`).

File: pkg/kv/kvserver/replica_write.go [hunk 2]
```diff
@@ -884,3 +889,132 @@ func releaseMVCCStats(ms *enginepb.MVCCStats) {
...
+		startRangeID, _, _, _, err := keys.DecodeRangeIDKey(modifiedSpan.Key)
+		if err != nil {
+			// If the conservative start key is not a RangeID key, then this span
+			// cannot overlap with any rangeID local keys.
+			return nil //nolint:returnerrcheck
+		}
+
+		if modifiedSpan.Overlaps(getRangeIDLocalSpan(startRangeID)) {
+			return errors.Errorf("overlapping an unreplicated rangeID span")
+		}
```
Comment (pav-kv) [inline pkg/kv/kvserver/replica_write.go]: It seems like `DecodeRangeIDKey` gives us all we need. The `infix` bit is equal to [localRangeIDUnreplicatedInfix](https://github.com/cockroachdb/cockroach/blob/2b759bf2e7d059bdb53caf40a626ad00fa8bc85e/pkg/keys/constants.go#L111) when we're in the unreplicated space. But it's a bit annoying that, due to the `(x-eps,x]` semantics of our span, we should be checking `start < x <= end` here, which means `"u" < infix+suffix+detail <= "v"`.

But we know that `infix+suffix+detail` can't equal `u` or `v`, because `suffix` must't be empty (`DecodeRangeIDKey` would return an error).

So... looks like it's sufficient to check that `infix == "u"`?

File: pkg/kv/kvserver/spanset/spanset.go [hunk 3]
```diff
@@ -83,8 +83,14 @@ type Span struct {
...
-	spans           [NumSpanAccess][NumSpanScope][]Span
-	allowUndeclared bool
+	spans [NumSpanAccess][NumSpanScope][]Span
+	// forbiddenSpansMatchers are functions that return an error if the given span
+	// shouldn't be accessed (forbidden). This allows for complex pattern matching
+	// like forbidding specific keys across all range IDs without enumerating them
+	// explicitly.
+	forbiddenSpansMatchers []func(roachpb.Span) error
+	allowUndeclared        bool
+	allowForbidden         bool
```
Comment (pav-kv) [inline pkg/kv/kvserver/spanset/spanset.go]: Pre-existing, but made stronger in this PR: it seems that this type shouldn't mix the job of representing a set of spans and that of [test-only] verifying it / forbidding keys. There seems to be a clear subset of methods that add/canonicalize/access spans without having an opinion on them, and then the "check" methods that verify stuff. I would make the latter the responsibility of a wrapper (either existing one like `spanSetBatch`, or make a new one).

Ideally need a prereq PR/commit that does that separation.

File: pkg/kv/kvserver/spanset/spanset.go [hunk 4]
```diff
@@ -382,11 +382,20 @@ func (s *SpanSet) checkAllowed(
...
+// represent: [EndKey.Prev(), EndKey).
+func Contains(s1, s2 roachpb.Span) bool {
+	if s1.Key == nil {
+		// In this case, s1 can only contain s2 is a point span that equals s1.
+		if s2.Key == nil {
+			return s1.EndKey.Compare(s2.EndKey) == 0
+		}
+		return s2.Key.IsPrev(s1.EndKey) &&
+			(s2.EndKey == nil || s1.EndKey.Compare(s2.EndKey) == 0)
+	}
```
Comment (pav-kv) [inline pkg/kv/kvserver/spanset/spanset.go]: Was this a fix of some bug? Would be good to see tests added in a pre-commit, so that it's visible in this commit what it fixes.

File: pkg/kv/kvserver/spanset/spanset_test.go [hunk 5]
```diff
@@ -394,3 +394,237 @@ func TestSpanSetWriteImpliesRead(t *testing.T) {
...
+	testCases := []struct {
+		name     string
+		s1       roachpb.Span
+		s2       roachpb.Span
+		expected bool
+	}{
+		{
+			name:     "s1 contains s2 exactly",
+			s1:       roachpb.Span{Key: roachpb.Key("a"), EndKey: roachpb.Key("c")},
+			s2:       roachpb.Span{Key: roachpb.Key("a"), EndKey: roachpb.Key("c")},
```
Comment (pav-kv) [inline pkg/kv/kvserver/spanset/spanset_test.go]: nit: avoid the boilerplate for ease of reading these tests. For inspiration, could make a similar helper to [this](https://github.com/cockroachdb/cockroach/blob/72e57349caf8c63e567a3eae6c8600bf96fa9623/pkg/kv/kvserver/spanset/merge_test.go#L61-L87) one in this package (or perhaps just use it - maybe need to support the nil start `Key` though).

Same for both tests.

File: pkg/keys/keys.go [hunk 6]
```diff
@@ -308,6 +308,21 @@ func DecodeRangeIDKey(
 	return roachpb.RangeID(rangeInt), infix, suffix, b, nil
 }
 
+// DecodeRangeIDPrefix parses a local range ID prefix into range ID.
+func DecodeRangeIDPrefix(key roachpb.Key) (rangeID roachpb.RangeID, err error) {
```
Comment (pav-kv) [inline pkg/keys/keys.go]: nit: return value names are not needed because the types are self-explanatory

File: pkg/kv/kvserver/batcheval/cmd_truncate_log.go [hunk 7]
```diff
@@ -118,7 +118,8 @@ func TruncateLog(
 	// are not tracked in the raft log delta. The delta will be adjusted below
 	// raft.
 	// We can pass zero as nowNanos because we're only interested in SysBytes.
-	ms, err := storage.ComputeStats(ctx, readWriter, start, end, 0 /* nowNanos */)
+	ms, err := storage.ComputeStats(ctx,
```
Comment (pav-kv) [inline pkg/kv/kvserver/batcheval/cmd_truncate_log.go]: `TODO(sep-raft-log)` (or link the issue I filed) here that we need to plumb the raft engine in here, instead of using the state machine engine `readWriter`.

File: pkg/kv/kvserver/replica_write.go [hunk 8]
```diff
@@ -884,3 +889,108 @@ func releaseMVCCStats(ms *enginepb.MVCCStats) {
...
+	localStoreSpan := roachpb.Span{
+		Key:    keys.LocalStorePrefix,
+		EndKey: keys.LocalStoreMax,
+	}
+
+	if spanset.Overlaps(localStoreSpan, span) {
+		return errors.Errorf("overlaps with store local keys")
+	}
+
+	return nil
```
Comment (pav-kv) [inline pkg/kv/kvserver/replica_write.go:953]: Does the order matter here, or you made the `Overlaps` symmetric? Could be also:

```golang
if spanset.Overlaps(span, roachpb.Span{
	Key:    keys.LocalStorePrefix,
	EndKey: keys.LocalStoreMax,
}) {
	return error
}
return nil
```

File: pkg/kv/kvserver/replica_write.go [hunk 9]
```diff
@@ -884,3 +889,108 @@ func releaseMVCCStats(ms *enginepb.MVCCStats) {
...
+	// unreplicated RangeID span for a given RangeID.
+	getRangeIDLocalSpan := func(rangeID roachpb.RangeID) roachpb.Span {
+		return roachpb.Span{Key: keys.MakeRangeIDUnreplicatedPrefix(rangeID),
+			EndKey: keys.MakeRangeIDUnreplicatedPrefix(rangeID).PrefixEnd()}
+	}
+
+	fullRangeIDLocalSpans := roachpb.Span{
+		Key:    keys.MakeRangeIDUnreplicatedPrefix(0),
+		EndKey: keys.LocalRangePrefix,
+	}
```
Comment (pav-kv) [inline pkg/kv/kvserver/replica_write.go:901]: Is the key "skew" intentional?

Consider the layout (visual [here](https://github.com/cockroachdb/cockroach/pull/144429/files)). Shrunk to the relevant keys:

```
"\x01" : Local
  "i" [VarInt] : RangeID
    "r" : Replicated
    "u" : Unreplicated
  "k" : Range
  "s" : Store

"\x02" : Meta1
...
```

```
- Local
	- "i" RangeID
		- 0
			- "r"
			- "u"  // Start
		- 1
			- "r"
			- "u"
		...
	"j" // not used
  "k" : Range // End
  "s" : Store

"\x02" : Meta1
...
```

So `fullRangeIDLocalSpans` kind of starts within a `Local/RangeID=0/Unreplicated` subtree, exits into the `Local` subtree, crosses all other non-zero `RangeID`s, then the non-existent "j" after "i", and ends at "k".

So it's a bit off, in a sense that partially excludes the `RangeID` 0, and includes "reserved" space. Should we make it exactly the `Local/RangeID` subtree (`LocalRangeIDPrefix` and its `PrefixEnd()`)?

File: pkg/kv/kvserver/replica_write.go [hunk 10]
```diff
@@ -884,3 +889,108 @@ func releaseMVCCStats(ms *enginepb.MVCCStats) {
...
+	// rangeID, then there is no overlap with any rangeID local keys.
+	if !spanset.Overlaps(fullRangeIDLocalSpans, span) {
+		return nil
+	}
+
+	// Overlapping the full rangeID local span. We must be overlapping rangeID
+	// local keys.
+	if spanset.Contains(span, fullRangeIDLocalSpans) {
+		return errors.Errorf("overlapping an unreplicated rangeID span")
+	}
```
Comment (pav-kv) [inline pkg/kv/kvserver/replica_write.go]: `Contains` can return true if `A == B`, right? But we're specifically interested whether there are parts of `A` that are inside `B`, as well as outside.

File: pkg/kv/kvserver/replica_write.go (hunk 9 above)
Comment (pav-kv) [reply pkg/kv/kvserver/replica_write.go:901]: I wonder if we can do something simpler, more tied to the "tree" way of looking at this.

1. First, check whether we're fully inside or fully outside `Local/RangeID`. We can't be partially inside it, or cover it fully.
2. If fully inside, do the `RangeID`-based checks.

After getting inside `Local/RangeID`, I think we can afford a simplified check which does not depend much on the nil-ness of keys. Inside `Local/RangeID`, we know that all keys *must* have an encoded RangeID. Since we know the reader must be trying to avoid the unreplicated part, they can't be using things like `RangeID+1` or `-1` in keys: both start end end key must be using the same `RangeID`.

File: pkg/kv/kvserver/replica_write.go [hunk 11]
```diff
@@ -884,3 +889,108 @@ func releaseMVCCStats(ms *enginepb.MVCCStats) {
...
+
+	// One last case to check. If the start key is just at the end of some RangeID
+	// local key, we need to check if the span is overlapping some RangeID local
+	// keys that are ahead of startKey (on the next RangeID).
+	if span.EndKey != nil {
+		endRangeID, err := keys.DecodeRangeIDPrefix(span.EndKey)
+		if err != nil {
+			panic(err) // cannot happen
```
Comment (pav-kv) [inline pkg/kv/kvserver/replica_write.go]: Return `AssertionFailedf` instead of panics?

File: pkg/kv/kvserver/spanset/batch.go [hunk 12]
```diff
@@ -888,6 +888,64 @@ func DisableReadWriterAssertions(rw storage.ReadWriter) storage.ReadWriter {
...
+		return &spanSetBatch{
+			ReadWriter: ReadWriter{
+				spanSetReader: spanSetReader{r: v.b, spans: readSpans, spansOnly: v.spansOnly, ts: v.ts},
+				spanSetWriter: spanSetWriter{w: v.b, spans: writeSpans, spansOnly: v.spansOnly, ts: v.ts},
+			},
+			b:         v.b,
+			spans:     readSpans, // Use the read spans as the main spans
+			spansOnly: v.spansOnly,
+			ts:        v.ts,
+		}
```
Comment (pav-kv) [inline pkg/kv/kvserver/spanset/batch.go]: Looks a bit error-prone to do this twice here (e.g. I can't even tell the difference between this method and the above).

Probably worth factoring out most of this cloning (e.g. as a method of `spanSetBatch`), and if there is a difference - make it easy to spot.

File: pkg/kv/kvserver/spanset/batch.go [hunk 13]
```diff
@@ -888,6 +888,64 @@ func DisableReadWriterAssertions(rw storage.ReadWriter) storage.ReadWriter {
...
+// The returned batch shares the same underlying storage.Batch but has its own
+// SpanSet copies with assertions disabled.
+func DisableForbiddenSpanAssertionsOnBatch(rw storage.ReadWriter) storage.ReadWriter {
+	switch v := rw.(type) {
+	case *spanSetBatch:
+		// Clone the span sets and disable assertions on the copies
+		readSpans := v.ReadWriter.spanSetReader.spans.Copy()
+		writeSpans := v.ReadWriter.spanSetWriter.spans.Copy()
+		readSpans.DisableForbiddenSpansAssertions()
+		writeSpans.DisableForbiddenSpansAssertions()
```
Comment (pav-kv) [inline pkg/kv/kvserver/spanset/batch.go]: I wonder whether the copying is needed, or we could just refer to the same span sets. Is it "just in case"? We use this func as an ephemeral decorator, scoped to a single call that does not change the `SpanSet`.

File: pkg/kv/kvserver/spanset/batch.go [hunk 14]
```diff
@@ -888,6 +888,64 @@ func DisableReadWriterAssertions(rw storage.ReadWriter) storage.ReadWriter {
...
+// the same underlying storage.Batch but has its own SpanSet copies with
+// assertions disabled.
+func DisableLatchAssertions(rw storage.ReadWriter) storage.ReadWriter {
+	switch v := rw.(type) {
+	case *spanSetBatch:
+		// Clone the span sets and disable assertions on the copies
+		readSpans := v.ReadWriter.spanSetReader.spans.Copy()
+		writeSpans := v.ReadWriter.spanSetWriter.spans.Copy()
+		readSpans.DisableUndeclaredAccessAssertions()
+		writeSpans.DisableUndeclaredAccessAssertions()
```
Comment (pav-kv) [inline pkg/kv/kvserver/spanset/batch.go]: Do we need this cloning if the assertions are disabled on these spans?

File: pkg/kv/kvserver/spanset/spanset.go (hunk 4 above)
Comment (pav-kv) [reply pkg/kv/kvserver/spanset/spanset.go]: Probably, this function didn't intend to be symmetric (e.g. for efficiency: fewer checks to make, code to write/read). It just happens that its signature invites error. Semantically, this is:

```golang
func Contains(s1 roachpb.Span, s2 TrickySpan) bool { }

// TrickySpan is blah, but also [x-eps,x).
type TrickySpan roachpb.Span
```

So if we make a type for the tricky span, we can afford asymmetry, and I would say it's even welcome here.

Rn the semantics are:

```golang
func Contains(s1, s2 TrickySpan) bool { }
```

but the `roachpb.Span` type misleads to think that these are normal spans.

File: pkg/kv/kvserver/spanset/spanset_test.go [hunk 15]
```diff
@@ -394,3 +394,237 @@ func TestSpanSetWriteImpliesRead(t *testing.T) {
...
+	defer leaktest.AfterTest(t)()
+
+	testCases := []struct {
+		name     string
+		s1       roachpb.Span
+		s2       roachpb.Span
+		expected bool
+	}{
+		{
+			name:     "s1 contains s2 exactly",
```
Comment (pav-kv) [inline pkg/kv/kvserver/spanset/spanset_test.go]: Opinion, feel free to ignore: this `name` pattern is not needed in most cases. Go `testing` converts whitespace to underscores etc, so this name is not very searchable when the test fails (unless one avoids characters that it modifies). I just say `t.Run("", func)` and rely on `testing` to number the tests by index. The specifics of the test cases is then put in comments, e.g.:

```golang
for _, tc := range []struct {
	...
} {
	{s1: "a-c", s2: "a-c", want: true}, // equal spans
	{s1: "a-c", s2: "a-d", want: true}, // prefix
	// NB: even these comments are not needed because the cases are
	// "readable" and self-explanatory.
} {
	t.Run("", func ... {
		// If you want to make a case identifiable on a failure:
		t.Logf("s1: %q, s2: %q", tc.s1, tc.s2)
		...
	})
}
```

File: pkg/kv/kvserver/replica_write.go (hunk 8 above)
Comment (pav-kv) [reply pkg/kv/kvserver/replica_write.go:953]: See the comment in `Overlaps` though why I think the order can/should matter.

File: pkg/kv/kvserver/replica_write.go (hunk 9 above)
Comment (iskettaneh) [reply pkg/kv/kvserver/replica_write.go:901]: I followed your recommendation, and it made things a lot simpler!

File: pkg/kv/kvserver/replica_write.go (hunk 11 above)
Comment (iskettaneh) [reply pkg/kv/kvserver/replica_write.go]: Done.

File: pkg/kv/kvserver/replica_write.go (hunk 8 above)
Comment (iskettaneh) [reply pkg/kv/kvserver/replica_write.go:953]: Now I made sure that ordering matters, and that the ordering is correct.

File: pkg/kv/kvserver/batcheval/cmd_truncate_log.go (hunk 7 above)
Comment (iskettaneh) [reply pkg/kv/kvserver/batcheval/cmd_truncate_log.go]: Done.

File: pkg/kv/kvserver/spanset/batch.go (hunk 14 above)
Comment (iskettaneh) [reply pkg/kv/kvserver/spanset/batch.go]: I refactored the code a bit. Now this function is lightweight.

File: pkg/kv/kvserver/spanset/batch.go (hunk 13 above)
Comment (iskettaneh) [reply pkg/kv/kvserver/spanset/batch.go]: You are right. Copying is not really needed. I modified it and it's simpler and lighter now.

File: pkg/kv/kvserver/spanset/batch.go (hunk 12 above)
Comment (iskettaneh) [reply pkg/kv/kvserver/spanset/batch.go]: Good point. I have refactored the code.

File: pkg/kv/kvserver/spanset/spanset.go (hunk 3 above)
Comment (iskettaneh) [reply pkg/kv/kvserver/spanset/spanset.go]: Will do it in another PR

File: pkg/kv/kvserver/spanset/spanset.go (hunk 4 above)
Comment (iskettaneh) [reply pkg/kv/kvserver/spanset/spanset.go]: Done. You were right, the changes I made was to make these helper functions accept the TrickySpan either as the first or second parameter. I followed your suggestion with the TrickySpan.

File: pkg/kv/kvserver/spanset/spanset_test.go (hunk 15 above)
Comment (iskettaneh) [reply pkg/kv/kvserver/spanset/spanset_test.go]: Done.

**Review by iskettaneh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/157153)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @pav-kv)

File: pkg/kv/kvserver/spanset/spanset.go [hunk 16]
```diff
@@ -331,27 +349,37 @@ func (s *SpanSet) CheckAllowedAt(
...
+		}
 	}
 
-	scope := SpanGlobal
-	if (span.Key != nil && keys.IsLocal(span.Key)) ||
-		(span.EndKey != nil && keys.IsLocal(span.EndKey)) {
-		scope = SpanLocal
-	}
+	// Unless explicitly disabled, check if we access any undeclared spans.
+	if !s.allowUndeclared {
```
Comment (pav-kv) [inline pkg/kv/kvserver/spanset/spanset.go]: nit: not necessary to indent a large block at the end of the func. Pretty much the previous code can be left as is:

```golang
// forbidden matchers checks

is s.allowUndeclared {
	return nil
}

// undeclared checks
```

File: pkg/kv/kvserver/spanset/spanset.go [hunk 17]
```diff
@@ -76,6 +76,11 @@ type Span struct {
 	Timestamp hlc.Timestamp
 }
 
+// TrickySpan represents a span that supports a special encoding where a nil
+// start key with a non-nil end key represents the point span:
+// [EndKey.Prev(), EndKey).
+type TrickySpan roachpb.Span
```
Comment (pav-kv) [inline pkg/kv/kvserver/spanset/spanset.go:82]: Hahaha, I didn't literally mean the `TrickySpan` name 😆 But now that I think of it... can't think of a better name, so this will do!

Can it be unexported? Though there is some external use, like the "forbidden" callbacks, so perhaps not.

File: pkg/kv/kvserver/spanset/spanset_test.go [hunk 18]
```diff
@@ -394,3 +395,162 @@ func TestSpanSetWriteImpliesRead(t *testing.T) {
...
+		// s1 contains s2.
+		{s1: makeSpanHelper(t, "a-d"), s2: makeSpanHelper(t, "b-c"), expected: true},
+		// s1 contains point s2.
+		{s1: makeSpanHelper(t, "a-d"), s2: makeSpanHelper(t, "a-X"), expected: true},
+		// Point s1 contains point s2.
+		{s1: makeSpanHelper(t, "a-X"), s2: makeSpanHelper(t, "a-X"), expected: true},
+		// s1 contains point s2 with nil startKey.
+		{s1: makeSpanHelper(t, "a-d"), s2: makeSpanHelper(t, "X-d"), expected: true},
+		// Point s1 contains point s2 with nil startKey.
+		{s1: makeSpanHelper(t, "a-X"), s2: roachpb.Span{EndKey: roachpb.Key("a").Next()}, expected: true},
```
Comment (pav-kv) [inline pkg/kv/kvserver/spanset/spanset_test.go]: Can make one more step to de-boilerplate these tests: call `makeSpanHelper`s in the body, and leave only the strings here.

I can see that one of the reasons to not do this could be the `roachpb.Key("a").Next()` in this line, i.e. some need for hand-crafted keys. But in this instance, it can be `s2: "X-a\x00"`.

File: pkg/kv/kvserver/spanset/spanset.go [hunk 19]
```diff
@@ -382,24 +387,63 @@ func (s *SpanSet) checkAllowed(
...
-// supports spans with a nil start key and a non-nil end key (e.g. "[nil, c)").
-// In this form, s2.Key (inclusive) is considered to be the previous key to
-// s2.EndKey (exclusive).
-func contains(s1, s2 roachpb.Span) bool {
-	if s2.Key != nil {
-		// The common case.
-		return s1.Contains(s2)
+// Contains returns whether s1 contains s2, where s2 can be a TrickySpan.
+func Contains(s1 roachpb.Span, s2 TrickySpan) bool {
+	s2Span := roachpb.Span(s2)
```
Comment (pav-kv) [inline pkg/kv/kvserver/spanset/spanset.go]: nit: defer this conversion as far down the stack as possible and best avoid it. The idea is that the type carries semantics, so we don't want to lose/disperse it in the first line.

```golang
if s2.Key != nil { // TrickySpan is a normal roachpb.Span
	return s1.Contains(roachpb.Span(s2))
}

// below, it's only Key/EndKey arithmetics, so we don't
// need s2 to be roachpb.Span.
```

Same in the funcs below.

File: pkg/kv/kvserver/spanset/spanset.go [hunk 20]
```diff
@@ -353,7 +358,7 @@ func (s *SpanSet) checkAllowed(
 	if !s.allowForbidden {
 		// Check if the span is forbidden.
 		for _, matcher := range s.forbiddenSpansMatchers {
-			if err := matcher(span); err != nil {
+			if err := matcher(TrickySpan(span)); err != nil {
```
Comment (pav-kv) [inline pkg/kv/kvserver/spanset/spanset.go]: I think we should make the `span` in this method signature a `TrickySpan`. More generally, do this all the way up the stack to where the span is created. Those places ([example](https://github.com/cockroachdb/cockroach/blob/560b635c16f790db75a0fdc7492be9ecd8e96fa6/pkg/kv/kvserver/spanset/batch.go#L284)) where it is created with a nil `Key` will now start making sense, because the `TrickySpan` type is a hint that it's legal.

File: pkg/kv/kvserver/spanset/spanset.go [hunk 21]
```diff
@@ -382,24 +387,63 @@ func (s *SpanSet) checkAllowed(
...
+
+	if s1.EndKey == nil {
+		// s1 is a point span, overlaps with s2 iff s1.Key is the prev of s2.EndKey
+		return s1.Key.IsPrev(s2Span.EndKey)
 	}
 
-	return s1.Key.Compare(s2.EndKey) < 0 && s1.EndKey.Compare(s2.EndKey) >= 0
+	// s1 is [s1.Key, s1.EndKey), s2 is [s2.EndKey.Prev(), s2.EndKey)
+	// They overlap iff s2.EndKey.Prev() is in [s1.Key, s1.EndKey).
+	return s1.Key.Compare(s2Span.EndKey) < 0 && s1.EndKey.Compare(s2Span.EndKey) >= 0
```
Comment (pav-kv) [inline pkg/kv/kvserver/spanset/spanset.go]: This is a copy of the corresponding part of `Contains`. Which makes sense: the `[x-eps,x)` span is infinitely small, so the only way it can overlap someone is by being contained.

Could be worth pointing out something like that. Maybe not worth factoring out a func for that though.

File: pkg/kv/kvserver/spanset/spanset.go [hunk 22]
```diff
@@ -382,24 +387,63 @@ func (s *SpanSet) checkAllowed(
...
+// PartiallyOverlaps returns whether s1 partially overlaps s2,
+// where s2 can be a TrickySpan. If true, it means that s1 and s2 overlap, but
+// neither s1 nor s2 contain one another.
+func PartiallyOverlaps(s1 roachpb.Span, s2 TrickySpan) bool {
+	s2Span := roachpb.Span(s2)
+
+	// The common case: both spans have non-nil start keys.
+	if s2Span.Key != nil {
+		return s1.Overlaps(s2Span) && !s1.Contains(s2Span) && !s2Span.Contains(s1)
+	}
```
Comment (pav-kv) [inline pkg/kv/kvserver/spanset/spanset.go:429]: Could remove a bunch of comparisons from this (admittedly harder to read though, but there are other benefits: see other comments):

```golang
if s1.EndKey == nil || s2.EndKey == nil || s2.Key == nil {
	return false // because everything is a point key or infinitely small
}

cmpKey := s1.Key.Compare(s2.Key)
cmpEndKey := s2.EndKey.Compare(s1.EndKey)
if cmpKey * cmpEndKey <= 0 {
	// 0 means one span is a prefix/suffix of another, or they are equal
	// -1 means one span "wraps" another from both ends
	return false
}
// Remaining 2 cases. First:
//    s1:     [--------) 
// or s1:           [--------)
//    s2: [-------)
if cmpKey > 0 { // NB: cmpEndKey > 0, too
	return s1.Key.Compare(s2.EndKey) < 0
}
// Second:
//    s1:      [-----) 
// or s1: [-----)
//    s2:          [-------)
return s1.EndKey.Compare(s2.Key) > 0
```

Also, note that most of this func could be a non-`TrickySpan` function. The only special case is `s2.Key == nil` in which we return false.

File: pkg/kv/kvserver/spanset/spanset_test.go [hunk 23]
```diff
@@ -394,3 +395,162 @@ func TestSpanSetWriteImpliesRead(t *testing.T) {
...
+	}
+}
+
+// Test that Contains correctly determines if s1 contains s2, including
+// support for spans with nil start/end keys.
+func TestContains(t *testing.T) {
+	defer leaktest.AfterTest(t)()
+
+	testCases := []struct {
+		name     string
```
Comment (pav-kv) [inline pkg/kv/kvserver/spanset/spanset_test.go]: unused now

File: pkg/kv/kvserver/replica_write.go [hunk 24]
```diff
@@ -884,3 +889,76 @@ func releaseMVCCStats(ms *enginepb.MVCCStats) {
...
+	if spanset.PartiallyOverlaps(fullRangeIDLocalSpans, span) {
+		return errors.Errorf("partially overlapping the unreplicated rangeID span")
+	}
+
+	// At this point, we know that either we are containing the
+	// fullRangeIDLocalSpans, or we are completely within fullRangeIDLocalSpans.
+	// Check to see if we fully contain fullRangeIDLocalSpans.
+	if !spanset.Contains(fullRangeIDLocalSpans, span) {
+		return errors.Errorf("completely containing the unreplicated rangeID span")
+	}
```
Comment (pav-kv) [inline pkg/kv/kvserver/replica_write.go:916]: Here we end up comparing `Key` and `EndKey`s a bunch of times, even though we probably need to do <= 3 or so comparisons to distinguish the 3 cases.

I wonder if it would make sense to have a func which tells us the relative position of two spans. Could be `enum`, some bools, or a bitmask.

In some very general sense, we're interested in 3 bits of info (`A` and `B` are spans/sets, `{-,*}` are set subtraction and intersection):

1. `A - B` is non-empty
2. `B - A` is non-empty
3. `A * B` is non-empty

Then:

```
- if not (3)     : no overlap, return nil
- if (1) and (2) : partial overlap, error
- if not (1)     : our set is >= the big one -> error
```

See my comment in the `PartiallyOverlaps` func: if we follow the flow in it, all cases are covered there. We will also need just one func (slightly more general, but that's fine) and one test.

File: pkg/kv/kvserver/replica_write.go [hunk 25]
```diff
@@ -884,3 +889,76 @@ func releaseMVCCStats(ms *enginepb.MVCCStats) {
...
+
+	// We make an assumption here that whoever if the span in inside
```
Comment (pav-kv) [inline pkg/kv/kvserver/replica_write.go]: nit: the sentence needs a fix

File: pkg/kv/kvserver/replica_write.go [hunk 26]
```diff
@@ -884,3 +889,76 @@ func releaseMVCCStats(ms *enginepb.MVCCStats) {
...
+	// fullRangeIDLocalSpans, we expect that (a) The start key is not nil, and
```
Comment (pav-kv) [inline pkg/kv/kvserver/replica_write.go]: Why do we assume (a)? IIUC, `Key == nil` can be used in cases like `SeekLE`, which I don't know off hand we wouldn't be using here.

If `Key` is nil, I think it's ok to devise `rangeID` from the `EndKey`, given (b). How about:

```golang
rangeIDKey := span.Key
if rangeIDKey == nil {
	rangeIDKey = span.EndKey
}
rangeID, err := keys.DecodeRangeIDPrefix(rangeIDKey)
if err != nil {
	return errors.NewAssertionErrorWithWrappedErrf(err,
		"could not decode range ID for span: %s", span)
}
```

File: pkg/kv/kvserver/replica_write.go [hunk 27]
```diff
@@ -884,3 +889,76 @@ func releaseMVCCStats(ms *enginepb.MVCCStats) {
 	ms.Reset()
 	mvccStatsPool.Put(ms)
 }
+
+// overlapsUnreplicatedRangeIDLocalKeys checks if the provided span overlaps
+// with any unreplicated rangeID local keys.
+// Note that we could receive the span with a nil startKey, which has a special
+// meaning that the span represents: [endKey.Prev(), endKey).
+func overlapsUnreplicatedRangeIDLocalKeys(span spanset.TrickySpan) error {
```
Comment (pav-kv) [inline pkg/kv/kvserver/replica_write.go:897]: Like the new impl, much more comprehensible. Thanks!

File: pkg/kv/kvserver/replica_write.go [hunk 28]
```diff
@@ -884,3 +889,76 @@ func releaseMVCCStats(ms *enginepb.MVCCStats) {
...
+	// getRangeIDLocalSpan is a helper function that returns the full
+	// unreplicated RangeID span for a given RangeID.
+	getRangeIDLocalSpan := func(rangeID roachpb.RangeID) roachpb.Span {
+		return roachpb.Span{Key: keys.MakeRangeIDUnreplicatedPrefix(rangeID),
+			EndKey: keys.MakeRangeIDUnreplicatedPrefix(rangeID).PrefixEnd()}
+	}
```
Comment (pav-kv) [inline pkg/kv/kvserver/replica_write.go]: This is used once, and too far away from the definition. Collocate, or better inline?

File: pkg/kv/kvserver/replica_write.go (hunk 24 above)
Comment (pav-kv) [reply pkg/kv/kvserver/replica_write.go:916]: Could use `enum` trick with bitsets:

```golang
type SpanDiff byte

// Names are hard here.
const (
	DiffRHSOnly SpanDiff = 1 << iota
	DiffLHSOnly
	DiffBoth
)

func (p Placement) Overlaps() bool { return p & DiffBoth != 0 }

func (p Placement) PartialOverlaps() bool {
	const mask = DiffBoth | DiffRHSOnly | DiffLSHOnly
	return p & mask == mask
}

// etc (e.g. Contains, Contained)

switch diff := Diff(s1, s2) { // hame is hard
case !diff.Overlaps():
	return nil
case diff.PartialOverlaps():
	return error
case !diff.Contains():
	return error
}
```

**Review by pav-kv — COMMENTED** [review]
This is nearing the LGTM, thanks for making it cleaner each time.

File: pkg/kv/kvserver/replica_write.go [hunk 29]
```diff
@@ -884,3 +889,76 @@ func releaseMVCCStats(ms *enginepb.MVCCStats) {
...
+
+	// If the provided span is completely outside the rangeID local spans for any
+	// rangeID, then there is no overlap with any rangeID local keys.
+	if !spanset.Overlaps(fullRangeIDLocalSpans, span) {
+		return nil
+	}
+
+	// If we are partially overlapping the full rangeID local span. We must be
+	// overlapping rangeID local keys.
+	if spanset.PartiallyOverlaps(fullRangeIDLocalSpans, span) {
```
Comment (pav-kv) [inline pkg/kv/kvserver/replica_write.go]: Probably don't need the `PartiallyOverlaps` btw?

```golang
if !Overlaps {
	return nil
}
// We overlap. The only valid case is when we're strictly inside.
if !Contains(fullThing, span) {
	return error
}
// Can we jump straight to the rangeID computation?
// We haven't covered the case when fullThing == span, but it will
// trip on the rangeID computation if it's the case.
```

File: pkg/kv/kvserver/replica_write.go (hunk 27 above)
Comment (iskettaneh) [reply pkg/kv/kvserver/replica_write.go:897]: Thank you!

File: pkg/kv/kvserver/replica_write.go (hunk 28 above)
Comment (iskettaneh) [reply pkg/kv/kvserver/replica_write.go]: Done.

File: pkg/kv/kvserver/replica_write.go (hunk 29 above)
Comment (iskettaneh) [reply pkg/kv/kvserver/replica_write.go]: Good point!

File: pkg/kv/kvserver/replica_write.go (hunk 24 above)
Comment (iskettaneh) [reply pkg/kv/kvserver/replica_write.go:916]: Can you take a look at the function now? It has less checks and I think it's decently readable.

File: pkg/kv/kvserver/replica_write.go (hunk 25 above)
Comment (iskettaneh) [reply pkg/kv/kvserver/replica_write.go]: I changed it

File: pkg/kv/kvserver/replica_write.go (hunk 26 above)
Comment (iskettaneh) [reply pkg/kv/kvserver/replica_write.go]: Done.

File: pkg/kv/kvserver/spanset/spanset.go (hunk 17 above)
Comment (iskettaneh) [reply pkg/kv/kvserver/spanset/spanset.go:82]: Yeah I don't think we can unexport it.

File: pkg/kv/kvserver/spanset/spanset.go (hunk 20 above)
Comment (iskettaneh) [reply pkg/kv/kvserver/spanset/spanset.go]: Done.

File: pkg/kv/kvserver/spanset/spanset.go (hunk 19 above)
Comment (iskettaneh) [reply pkg/kv/kvserver/spanset/spanset.go]: Done! With the new helper function, I think you are going to like how Contains and Overlaps look now!

File: pkg/kv/kvserver/spanset/spanset.go (hunk 21 above)
Comment (iskettaneh) [reply pkg/kv/kvserver/spanset/spanset.go]: Done.

File: pkg/kv/kvserver/spanset/spanset.go (hunk 22 above)
Comment (iskettaneh) [reply pkg/kv/kvserver/spanset/spanset.go:429]: I completely removed PartiallyOverlaps() now.

File: pkg/kv/kvserver/spanset/spanset_test.go (hunk 23 above)
Comment (iskettaneh) [reply pkg/kv/kvserver/spanset/spanset_test.go]: Done.

File: pkg/kv/kvserver/spanset/spanset_test.go (hunk 18 above)
Comment (iskettaneh) [reply pkg/kv/kvserver/spanset/spanset_test.go]: Done.

**Review by iskettaneh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/157153)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @pav-kv)

File: pkg/kv/kvserver/spanset/spanset.go [hunk 30]
```diff
@@ -352,6 +380,8 @@ func (s *SpanSet) checkAllowed(
 	}
 
 	return errors.Errorf("cannot %s undeclared span %s\ndeclared:\n%s\nstack:\n%s", access, span, s, debugutil.Stack())
+
+	return nil
```
Comment (pav-kv) [inline pkg/kv/kvserver/spanset/spanset.go]: Duplicate `return`, drop?

File: pkg/kv/kvserver/spanset/batch.go [hunk 31]
```diff
@@ -888,6 +888,59 @@ func DisableReadWriterAssertions(rw storage.ReadWriter) storage.ReadWriter {
 	}
 }
 
+func disableAssertionHelper(
+	rw storage.ReadWriter, disableAssertion func(spans *SpanSet),
```
Comment (pav-kv) [inline pkg/kv/kvserver/spanset/batch.go]: nit: maybe this callback is a somewhat too much indirection (also would be good to not pay for it in the happy case). Consider something more direct, like:

```golang
func DisableLatchAssertions(rw storage.ReadWriter) storage.ReadWriter {
	switch v := rw.(type) {
	case *spanSetBatch:
		batch := v.clone()
		batch...DisableUndeclaredAccessAssertions()

	default:
		return rw
	}
}

func DisableForbiddenSpanAssertionsOnBatch(rw storage.ReadWriter) storage.ReadWriter {
	// same, but the other "disable" inside
}
```

File: pkg/kv/kvserver/spanset/batch.go [hunk 32]
```diff
@@ -888,6 +888,59 @@ func DisableReadWriterAssertions(rw storage.ReadWriter) storage.ReadWriter {
...
+) storage.ReadWriter {
+	switch v := rw.(type) {
+	case *spanSetBatch:
+		// Create a SpanSet wrapper that will be used to disable a specific
+		// assertion ephemerally.
+		spans := &SpanSet{
+			spans:                  v.ReadWriter.spanSetReader.spans.spans,
+			forbiddenSpansMatchers: v.ReadWriter.spanSetReader.spans.forbiddenSpansMatchers,
+			allowForbidden:         v.ReadWriter.spanSetReader.spans.allowForbidden,
+			allowUndeclared:        v.ReadWriter.spanSetReader.spans.allowUndeclared,
```
Comment (pav-kv) [inline pkg/kv/kvserver/spanset/batch.go]: I wonder whether we need these bools. The same effect could be achieved by clearing `spans` / `forbiddenSpansMatches` (or not setting them in the first place when we clone).

I don't know if we can do it for both or just `allowForbidden`. See if makes sense.

File: pkg/kv/kvserver/spanset/batch.go [hunk 33]
```diff
@@ -888,6 +888,59 @@ func DisableReadWriterAssertions(rw storage.ReadWriter) storage.ReadWriter {
...
+
+		// Create a new spanSetBatch with the modified span sets.
+		return &spanSetBatch{
+			ReadWriter: ReadWriter{
+				spanSetReader: spanSetReader{r: v.b, spans: spans, spansOnly: v.spansOnly, ts: v.ts},
+				spanSetWriter: spanSetWriter{w: v.b, spans: spans, spansOnly: v.spansOnly, ts: v.ts},
+			},
+			b:         v.b,
+			spans:     spans,
+			spansOnly: v.spansOnly,
```
Comment (pav-kv) [inline pkg/kv/kvserver/spanset/batch.go]: Btw, this `spansOnly bool` is always true, and seems like in all things in this package. TODO to remove it or to fix. Looks like a lot of code can be removed as a result, and I wonder if the code originally intended to do something else, we lost this intent somewhere along the line, or it was half-done from the beginning.

File: pkg/kv/kvserver/spanset/batch.go [hunk 34]
```diff
@@ -888,6 +888,59 @@ func DisableReadWriterAssertions(rw storage.ReadWriter) storage.ReadWriter {
...
+		}
+
+		// Call the function that will disable some assertion.
+		disableAssertion(spans)
+
+		// Create a new spanSetBatch with the modified span sets.
+		return &spanSetBatch{
+			ReadWriter: ReadWriter{
+				spanSetReader: spanSetReader{r: v.b, spans: spans, spansOnly: v.spansOnly, ts: v.ts},
+				spanSetWriter: spanSetWriter{w: v.b, spans: spans, spansOnly: v.spansOnly, ts: v.ts},
```
Comment (pav-kv) [inline pkg/kv/kvserver/spanset/batch.go]: Both reader and writer use the same `spans`, although they shouldn't have been the same originally.

We're probably getting away with this when we disable the latch assertions (these spans are effectively ignored), but the forbidden spans disabling could be corrupting this?

File: pkg/kv/kvserver/spanset/spanset_test.go [hunk 35]
```diff
@@ -381,16 +382,132 @@ func TestSpanSetWriteImpliesRead(t *testing.T) {
...
+func TestContains(t *testing.T) {
+	defer leaktest.AfterTest(t)()
+
+	testCases := []struct {
+		s1       string
+		s2       string
+		expected bool
+	}{
+		// s1 equals s2.
+		{s1: "a-c", s2: "a-c", expected: true},
```
Comment (pav-kv) [inline pkg/kv/kvserver/spanset/spanset_test.go]: Wonder if we can merge this test with `TestOverlaps`, so that we have less copy-paste, and can compare the two funcs side-by-side (and not forget any edge cases):

```golang
{s1: "a-c", s2: "a-c", contains: true, overlaps: true},
...
```

Additionally, we can assert in `t.Run` that the "logical" relation (if contains, then also overlaps) between the two holds:

```
require.True(t, !tc.contains || tc.overlaps)
```

File: pkg/kv/kvserver/replica_write.go (hunk 27 above)
Comment (iskettaneh) [reply pkg/kv/kvserver/replica_write.go:897]: Thank you!

File: pkg/kv/kvserver/replica_write.go (hunk 28 above)
Comment (iskettaneh) [reply pkg/kv/kvserver/replica_write.go]: Done.

File: pkg/kv/kvserver/replica_write.go (hunk 29 above)
Comment (iskettaneh) [reply pkg/kv/kvserver/replica_write.go]: Good point!

File: pkg/kv/kvserver/replica_write.go (hunk 24 above)
Comment (iskettaneh) [reply pkg/kv/kvserver/replica_write.go:916]: Can you take a look at the function now? It has less checks and I think it's decently readable.

File: pkg/kv/kvserver/replica_write.go (hunk 25 above)
Comment (iskettaneh) [reply pkg/kv/kvserver/replica_write.go]: I changed it

File: pkg/kv/kvserver/replica_write.go (hunk 26 above)
Comment (iskettaneh) [reply pkg/kv/kvserver/replica_write.go]: Done.

File: pkg/kv/kvserver/spanset/batch.go (hunk 31 above)
Comment (iskettaneh) [reply pkg/kv/kvserver/spanset/batch.go]: I refactored the code a bit and I introduced SpanSet ShallowCopy which helped clean things up.

File: pkg/kv/kvserver/spanset/batch.go (hunk 32 above)
Comment (iskettaneh) [reply pkg/kv/kvserver/spanset/batch.go]: With the new refactoring, I believe things are clearer now.

File: pkg/kv/kvserver/spanset/batch.go (hunk 34 above)
Comment (iskettaneh) [reply pkg/kv/kvserver/spanset/batch.go]: I refactored the code a bit and I introduced SpanSet ShallowCopy which helped clean things up.

File: pkg/kv/kvserver/spanset/batch.go (hunk 33 above)
Comment (iskettaneh) [reply pkg/kv/kvserver/spanset/batch.go]: I added a TODO to address that. I think some of these fields aren't even read.

File: pkg/kv/kvserver/spanset/spanset.go (hunk 17 above)
Comment (iskettaneh) [reply pkg/kv/kvserver/spanset/spanset.go:82]: Yeah I don't think we can unexport it.

File: pkg/kv/kvserver/replica_write.go (hunk 27 above)
Comment (iskettaneh) [reply pkg/kv/kvserver/replica_write.go:897]: Thank you!

File: pkg/kv/kvserver/replica_write.go (hunk 28 above)
Comment (iskettaneh) [reply pkg/kv/kvserver/replica_write.go]: Done.

File: pkg/kv/kvserver/replica_write.go (hunk 29 above)
Comment (iskettaneh) [reply pkg/kv/kvserver/replica_write.go]: Good point!

File: pkg/kv/kvserver/replica_write.go (hunk 24 above)
Comment (iskettaneh) [reply pkg/kv/kvserver/replica_write.go:916]: Can you take a look at the function now? It has less checks and I think it's decently readable.

File: pkg/kv/kvserver/replica_write.go (hunk 25 above)
Comment (iskettaneh) [reply pkg/kv/kvserver/replica_write.go]: I changed it

File: pkg/kv/kvserver/replica_write.go (hunk 26 above)
Comment (iskettaneh) [reply pkg/kv/kvserver/replica_write.go]: Done.

File: pkg/kv/kvserver/spanset/batch.go (hunk 31 above)
Comment (iskettaneh) [reply pkg/kv/kvserver/spanset/batch.go]: I refactored the code a bit and I introduced SpanSet ShallowCopy which helped clean things up.

File: pkg/kv/kvserver/spanset/batch.go (hunk 32 above)
Comment (iskettaneh) [reply pkg/kv/kvserver/spanset/batch.go]: With the new refactoring, I believe things are clearer now.

File: pkg/kv/kvserver/spanset/batch.go (hunk 34 above)
Comment (iskettaneh) [reply pkg/kv/kvserver/spanset/batch.go]: I refactored the code a bit and I introduced SpanSet ShallowCopy which helped clean things up.

File: pkg/kv/kvserver/spanset/batch.go (hunk 33 above)
Comment (iskettaneh) [reply pkg/kv/kvserver/spanset/batch.go]: I added a TODO to address that. I think some of these fields aren't even read.

File: pkg/kv/kvserver/spanset/spanset.go (hunk 17 above)
Comment (iskettaneh) [reply pkg/kv/kvserver/spanset/spanset.go:82]: Yeah I don't think we can unexport it.

File: pkg/kv/kvserver/spanset/spanset.go (hunk 20 above)
Comment (iskettaneh) [reply pkg/kv/kvserver/spanset/spanset.go]: Done.

File: pkg/kv/kvserver/spanset/spanset.go (hunk 19 above)
Comment (iskettaneh) [reply pkg/kv/kvserver/spanset/spanset.go]: Done! With the new helper function, I think you are going to like how Contains and Overlaps look now!

File: pkg/kv/kvserver/spanset/spanset.go (hunk 21 above)
Comment (iskettaneh) [reply pkg/kv/kvserver/spanset/spanset.go]: Done.

File: pkg/kv/kvserver/spanset/batch.go (hunk 33 above)
Comment (pav-kv) [reply pkg/kv/kvserver/spanset/batch.go]: Fixing this separately in #158131. Some finding in #158132.
Closing this comment, not actionable in this PR.

File: pkg/kv/kvserver/replica_write.go (hunk 27 above)
Comment (iskettaneh) [reply pkg/kv/kvserver/replica_write.go:897]: Thank you!

File: pkg/kv/kvserver/replica_write.go (hunk 28 above)
Comment (iskettaneh) [reply pkg/kv/kvserver/replica_write.go]: Done.

File: pkg/kv/kvserver/replica_write.go (hunk 29 above)
Comment (iskettaneh) [reply pkg/kv/kvserver/replica_write.go]: Good point!

File: pkg/kv/kvserver/replica_write.go (hunk 24 above)
Comment (iskettaneh) [reply pkg/kv/kvserver/replica_write.go:916]: Can you take a look at the function now? It has less checks and I think it's decently readable.

File: pkg/kv/kvserver/replica_write.go (hunk 25 above)
Comment (iskettaneh) [reply pkg/kv/kvserver/replica_write.go]: I changed it

File: pkg/kv/kvserver/replica_write.go (hunk 26 above)
Comment (iskettaneh) [reply pkg/kv/kvserver/replica_write.go]: Done.

File: pkg/kv/kvserver/spanset/batch.go (hunk 31 above)
Comment (iskettaneh) [reply pkg/kv/kvserver/spanset/batch.go]: I refactored the code a bit and I introduced SpanSet ShallowCopy which helped clean things up.

File: pkg/kv/kvserver/spanset/batch.go (hunk 32 above)
Comment (iskettaneh) [reply pkg/kv/kvserver/spanset/batch.go]: With the new refactoring, I believe things are clearer now.

File: pkg/kv/kvserver/spanset/batch.go (hunk 34 above)
Comment (iskettaneh) [reply pkg/kv/kvserver/spanset/batch.go]: I refactored the code a bit and I introduced SpanSet ShallowCopy which helped clean things up.

File: pkg/kv/kvserver/spanset/batch.go (hunk 33 above)
Comment (iskettaneh) [reply pkg/kv/kvserver/spanset/batch.go]: I added a TODO to address that. I think some of these fields aren't even read.

File: pkg/kv/kvserver/spanset/spanset.go (hunk 17 above)
Comment (iskettaneh) [reply pkg/kv/kvserver/spanset/spanset.go:82]: Yeah I don't think we can unexport it.

File: pkg/kv/kvserver/spanset/spanset.go (hunk 20 above)
Comment (iskettaneh) [reply pkg/kv/kvserver/spanset/spanset.go]: Done.

File: pkg/kv/kvserver/spanset/spanset.go (hunk 19 above)
Comment (iskettaneh) [reply pkg/kv/kvserver/spanset/spanset.go]: Done! With the new helper function, I think you are going to like how Contains and Overlaps look now!

File: pkg/kv/kvserver/spanset/spanset.go (hunk 21 above)
Comment (iskettaneh) [reply pkg/kv/kvserver/spanset/spanset.go]: Done.

File: pkg/kv/kvserver/replica_write.go (hunk 27 above)
Comment (iskettaneh) [reply pkg/kv/kvserver/replica_write.go:897]: Thank you!

File: pkg/kv/kvserver/replica_write.go (hunk 28 above)
Comment (iskettaneh) [reply pkg/kv/kvserver/replica_write.go]: Done.

File: pkg/kv/kvserver/replica_write.go (hunk 29 above)
Comment (iskettaneh) [reply pkg/kv/kvserver/replica_write.go]: Good point!

File: pkg/kv/kvserver/replica_write.go (hunk 24 above)
Comment (iskettaneh) [reply pkg/kv/kvserver/replica_write.go:916]: Can you take a look at the function now? It has less checks and I think it's decently readable.

File: pkg/kv/kvserver/replica_write.go (hunk 25 above)
Comment (iskettaneh) [reply pkg/kv/kvserver/replica_write.go]: I changed it

File: pkg/kv/kvserver/replica_write.go (hunk 26 above)
Comment (iskettaneh) [reply pkg/kv/kvserver/replica_write.go]: Done.

File: pkg/kv/kvserver/spanset/batch.go (hunk 31 above)
Comment (iskettaneh) [reply pkg/kv/kvserver/spanset/batch.go]: I refactored the code a bit and I introduced SpanSet ShallowCopy which helped clean things up.

File: pkg/kv/kvserver/spanset/batch.go (hunk 32 above)
Comment (iskettaneh) [reply pkg/kv/kvserver/spanset/batch.go]: With the new refactoring, I believe things are clearer now.

File: pkg/kv/kvserver/spanset/batch.go (hunk 34 above)
Comment (iskettaneh) [reply pkg/kv/kvserver/spanset/batch.go]: I refactored the code a bit and I introduced SpanSet ShallowCopy which helped clean things up.

File: pkg/kv/kvserver/spanset/batch.go (hunk 33 above)
Comment (iskettaneh) [reply pkg/kv/kvserver/spanset/batch.go]: I added a TODO to address that. I think some of these fields aren't even read.

File: pkg/kv/kvserver/spanset/spanset.go (hunk 17 above)
Comment (iskettaneh) [reply pkg/kv/kvserver/spanset/spanset.go:82]: Yeah I don't think we can unexport it.

File: pkg/kv/kvserver/spanset/spanset.go (hunk 20 above)
Comment (iskettaneh) [reply pkg/kv/kvserver/spanset/spanset.go]: Done.

File: pkg/kv/kvserver/spanset/spanset.go (hunk 19 above)
Comment (iskettaneh) [reply pkg/kv/kvserver/spanset/spanset.go]: Done! With the new helper function, I think you are going to like how Contains and Overlaps look now!

File: pkg/kv/kvserver/spanset/spanset.go (hunk 21 above)
Comment (iskettaneh) [reply pkg/kv/kvserver/spanset/spanset.go]: Done.

File: pkg/kv/kvserver/replica_write.go (hunk 27 above)
Comment (iskettaneh) [reply pkg/kv/kvserver/replica_write.go:897]: Thank you!

File: pkg/kv/kvserver/replica_write.go (hunk 28 above)
Comment (iskettaneh) [reply pkg/kv/kvserver/replica_write.go]: Done.

File: pkg/kv/kvserver/replica_write.go (hunk 29 above)
Comment (iskettaneh) [reply pkg/kv/kvserver/replica_write.go]: Good point!

File: pkg/kv/kvserver/replica_write.go (hunk 24 above)
Comment (iskettaneh) [reply pkg/kv/kvserver/replica_write.go:916]: Can you take a look at the function now? It has less checks and I think it's decently readable.

File: pkg/kv/kvserver/replica_write.go (hunk 25 above)
Comment (iskettaneh) [reply pkg/kv/kvserver/replica_write.go]: I changed it

File: pkg/kv/kvserver/replica_write.go (hunk 26 above)
Comment (iskettaneh) [reply pkg/kv/kvserver/replica_write.go]: Done.

File: pkg/kv/kvserver/spanset/batch.go (hunk 31 above)
Comment (iskettaneh) [reply pkg/kv/kvserver/spanset/batch.go]: I refactored the code a bit and I introduced SpanSet ShallowCopy which helped clean things up.

File: pkg/kv/kvserver/spanset/batch.go (hunk 32 above)
Comment (iskettaneh) [reply pkg/kv/kvserver/spanset/batch.go]: With the new refactoring, I believe things are clearer now.

File: pkg/kv/kvserver/spanset/batch.go (hunk 34 above)
Comment (iskettaneh) [reply pkg/kv/kvserver/spanset/batch.go]: I refactored the code a bit and I introduced SpanSet ShallowCopy which helped clean things up.

File: pkg/kv/kvserver/spanset/batch.go (hunk 33 above)
Comment (iskettaneh) [reply pkg/kv/kvserver/spanset/batch.go]: I added a TODO to address that. I think some of these fields aren't even read.

File: pkg/kv/kvserver/spanset/spanset.go (hunk 17 above)
Comment (iskettaneh) [reply pkg/kv/kvserver/spanset/spanset.go:82]: Yeah I don't think we can unexport it.

File: pkg/kv/kvserver/spanset/spanset.go (hunk 20 above)
Comment (iskettaneh) [reply pkg/kv/kvserver/spanset/spanset.go]: Done.

File: pkg/kv/kvserver/spanset/spanset.go (hunk 19 above)
Comment (iskettaneh) [reply pkg/kv/kvserver/spanset/spanset.go]: Done! With the new helper function, I think you are going to like how Contains and Overlaps look now!

File: pkg/kv/kvserver/spanset/spanset.go (hunk 21 above)
Comment (iskettaneh) [reply pkg/kv/kvserver/spanset/spanset.go]: Done.

File: pkg/kv/kvserver/replica_write.go (hunk 27 above)
Comment (iskettaneh) [reply pkg/kv/kvserver/replica_write.go:897]: Thank you!

File: pkg/kv/kvserver/replica_write.go (hunk 28 above)
Comment (iskettaneh) [reply pkg/kv/kvserver/replica_write.go]: Done.

File: pkg/kv/kvserver/replica_write.go (hunk 29 above)
Comment (iskettaneh) [reply pkg/kv/kvserver/replica_write.go]: Good point!

File: pkg/kv/kvserver/replica_write.go (hunk 24 above)
Comment (iskettaneh) [reply pkg/kv/kvserver/replica_write.go:916]: Can you take a look at the function now? It has less checks and I think it's decently readable.

File: pkg/kv/kvserver/replica_write.go (hunk 25 above)
Comment (iskettaneh) [reply pkg/kv/kvserver/replica_write.go]: I changed it

File: pkg/kv/kvserver/replica_write.go (hunk 26 above)
Comment (iskettaneh) [reply pkg/kv/kvserver/replica_write.go]: Done.

File: pkg/kv/kvserver/spanset/batch.go (hunk 31 above)
Comment (iskettaneh) [reply pkg/kv/kvserver/spanset/batch.go]: I refactored the code a bit and I introduced SpanSet ShallowCopy which helped clean things up.

File: pkg/kv/kvserver/spanset/batch.go (hunk 32 above)
Comment (iskettaneh) [reply pkg/kv/kvserver/spanset/batch.go]: With the new refactoring, I believe things are clearer now.

File: pkg/kv/kvserver/spanset/batch.go (hunk 34 above)
Comment (iskettaneh) [reply pkg/kv/kvserver/spanset/batch.go]: I refactored the code a bit and I introduced SpanSet ShallowCopy which helped clean things up.

File: pkg/kv/kvserver/spanset/batch.go (hunk 33 above)
Comment (iskettaneh) [reply pkg/kv/kvserver/spanset/batch.go]: I added a TODO to address that. I think some of these fields aren't even read.

File: pkg/kv/kvserver/spanset/spanset.go (hunk 17 above)
Comment (iskettaneh) [reply pkg/kv/kvserver/spanset/spanset.go:82]: Yeah I don't think we can unexport it.

File: pkg/kv/kvserver/spanset/spanset.go (hunk 20 above)
Comment (iskettaneh) [reply pkg/kv/kvserver/spanset/spanset.go]: Done.

File: pkg/kv/kvserver/spanset/spanset.go (hunk 19 above)
Comment (iskettaneh) [reply pkg/kv/kvserver/spanset/spanset.go]: Done! With the new helper function, I think you are going to like how Contains and Overlaps look now!

File: pkg/kv/kvserver/spanset/spanset.go (hunk 21 above)
Comment (iskettaneh) [reply pkg/kv/kvserver/spanset/spanset.go]: Done.

File: pkg/kv/kvserver/replica_write.go (hunk 27 above)
Comment (iskettaneh) [reply pkg/kv/kvserver/replica_write.go:897]: Thank you!

File: pkg/kv/kvserver/replica_write.go (hunk 28 above)
Comment (iskettaneh) [reply pkg/kv/kvserver/replica_write.go]: Done.

File: pkg/kv/kvserver/replica_write.go (hunk 29 above)
Comment (iskettaneh) [reply pkg/kv/kvserver/replica_write.go]: Good point!

File: pkg/kv/kvserver/replica_write.go (hunk 24 above)
Comment (iskettaneh) [reply pkg/kv/kvserver/replica_write.go:916]: Can you take a look at the function now? It has less checks and I think it's decently readable.

File: pkg/kv/kvserver/replica_write.go (hunk 25 above)
Comment (iskettaneh) [reply pkg/kv/kvserver/replica_write.go]: I changed it

File: pkg/kv/kvserver/replica_write.go (hunk 26 above)
Comment (iskettaneh) [reply pkg/kv/kvserver/replica_write.go]: Done.

File: pkg/kv/kvserver/spanset/batch.go (hunk 31 above)
Comment (iskettaneh) [reply pkg/kv/kvserver/spanset/batch.go]: I refactored the code a bit and I introduced SpanSet ShallowCopy which helped clean things up.

File: pkg/kv/kvserver/spanset/batch.go (hunk 32 above)
Comment (iskettaneh) [reply pkg/kv/kvserver/spanset/batch.go]: With the new refactoring, I believe things are clearer now.

File: pkg/kv/kvserver/spanset/batch.go (hunk 34 above)
Comment (iskettaneh) [reply pkg/kv/kvserver/spanset/batch.go]: I refactored the code a bit and I introduced SpanSet ShallowCopy which helped clean things up.

File: pkg/kv/kvserver/spanset/batch.go (hunk 33 above)
Comment (iskettaneh) [reply pkg/kv/kvserver/spanset/batch.go]: I added a TODO to address that. I think some of these fields aren't even read.

File: pkg/kv/kvserver/spanset/spanset.go (hunk 17 above)
Comment (iskettaneh) [reply pkg/kv/kvserver/spanset/spanset.go:82]: Yeah I don't think we can unexport it.

File: pkg/kv/kvserver/spanset/spanset.go (hunk 20 above)
Comment (iskettaneh) [reply pkg/kv/kvserver/spanset/spanset.go]: Done.

File: pkg/kv/kvserver/spanset/spanset.go (hunk 19 above)
Comment (iskettaneh) [reply pkg/kv/kvserver/spanset/spanset.go]: Done! With the new helper function, I think you are going to like how Contains and Overlaps look now!

File: pkg/kv/kvserver/spanset/spanset.go (hunk 21 above)
Comment (iskettaneh) [reply pkg/kv/kvserver/spanset/spanset.go]: Done.

File: pkg/kv/kvserver/replica_write.go (hunk 27 above)
Comment (iskettaneh) [reply pkg/kv/kvserver/replica_write.go:897]: Thank you!

File: pkg/kv/kvserver/replica_write.go (hunk 28 above)
Comment (iskettaneh) [reply pkg/kv/kvserver/replica_write.go]: Done.

File: pkg/kv/kvserver/replica_write.go (hunk 29 above)
Comment (iskettaneh) [reply pkg/kv/kvserver/replica_write.go]: Good point!

File: pkg/kv/kvserver/replica_write.go (hunk 24 above)
Comment (iskettaneh) [reply pkg/kv/kvserver/replica_write.go:916]: Can you take a look at the function now? It has less checks and I think it's decently readable.

File: pkg/kv/kvserver/replica_write.go (hunk 25 above)
Comment (iskettaneh) [reply pkg/kv/kvserver/replica_write.go]: I changed it

File: pkg/kv/kvserver/replica_write.go (hunk 26 above)
Comment (iskettaneh) [reply pkg/kv/kvserver/replica_write.go]: Done.

File: pkg/kv/kvserver/spanset/batch.go (hunk 31 above)
Comment (iskettaneh) [reply pkg/kv/kvserver/spanset/batch.go]: I refactored the code a bit and I introduced SpanSet ShallowCopy which helped clean things up.

File: pkg/kv/kvserver/spanset/batch.go (hunk 32 above)
Comment (iskettaneh) [reply pkg/kv/kvserver/spanset/batch.go]: With the new refactoring, I believe things are clearer now.

File: pkg/kv/kvserver/spanset/batch.go (hunk 34 above)
Comment (iskettaneh) [reply pkg/kv/kvserver/spanset/batch.go]: I refactored the code a bit and I introduced SpanSet ShallowCopy which helped clean things up.

File: pkg/kv/kvserver/spanset/batch.go (hunk 33 above)
Comment (iskettaneh) [reply pkg/kv/kvserver/spanset/batch.go]: I added a TODO to address that. I think some of these fields aren't even read.

File: pkg/kv/kvserver/spanset/spanset.go (hunk 17 above)
Comment (iskettaneh) [reply pkg/kv/kvserver/spanset/spanset.go:82]: Yeah I don't think we can unexport it.

File: pkg/kv/kvserver/spanset/spanset.go (hunk 20 above)
Comment (iskettaneh) [reply pkg/kv/kvserver/spanset/spanset.go]: Done.

File: pkg/kv/kvserver/spanset/spanset.go (hunk 19 above)
Comment (iskettaneh) [reply pkg/kv/kvserver/spanset/spanset.go]: Done! With the new helper function, I think you are going to like how Contains and Overlaps look now!

File: pkg/kv/kvserver/spanset/spanset.go (hunk 21 above)
Comment (iskettaneh) [reply pkg/kv/kvserver/spanset/spanset.go]: Done.

File: pkg/kv/kvserver/replica_write.go (hunk 27 above)
Comment (iskettaneh) [reply pkg/kv/kvserver/replica_write.go:897]: Thank you!

File: pkg/kv/kvserver/replica_write.go (hunk 28 above)
Comment (iskettaneh) [reply pkg/kv/kvserver/replica_write.go]: Done.

File: pkg/kv/kvserver/replica_write.go (hunk 29 above)
Comment (iskettaneh) [reply pkg/kv/kvserver/replica_write.go]: Good point!

File: pkg/kv/kvserver/replica_write.go (hunk 24 above)
Comment (iskettaneh) [reply pkg/kv/kvserver/replica_write.go:916]: Can you take a look at the function now? It has less checks and I think it's decently readable.

File: pkg/kv/kvserver/replica_write.go (hunk 25 above)
Comment (iskettaneh) [reply pkg/kv/kvserver/replica_write.go]: I changed it

File: pkg/kv/kvserver/replica_write.go (hunk 26 above)
Comment (iskettaneh) [reply pkg/kv/kvserver/replica_write.go]: Done.

File: pkg/kv/kvserver/spanset/batch.go (hunk 31 above)
Comment (iskettaneh) [reply pkg/kv/kvserver/spanset/batch.go]: I refactored the code a bit and I introduced SpanSet ShallowCopy which helped clean things up.

File: pkg/kv/kvserver/spanset/batch.go (hunk 32 above)
Comment (iskettaneh) [reply pkg/kv/kvserver/spanset/batch.go]: With the new refactoring, I believe things are clearer now.

File: pkg/kv/kvserver/spanset/batch.go (hunk 34 above)
Comment (iskettaneh) [reply pkg/kv/kvserver/spanset/batch.go]: I refactored the code a bit and I introduced SpanSet ShallowCopy which helped clean things up.

File: pkg/kv/kvserver/spanset/batch.go (hunk 33 above)
Comment (iskettaneh) [reply pkg/kv/kvserver/spanset/batch.go]: I added a TODO to address that. I think some of these fields aren't even read.

File: pkg/kv/kvserver/spanset/spanset.go (hunk 17 above)
Comment (iskettaneh) [reply pkg/kv/kvserver/spanset/spanset.go:82]: Yeah I don't think we can unexport it.

File: pkg/kv/kvserver/spanset/spanset.go (hunk 20 above)
Comment (iskettaneh) [reply pkg/kv/kvserver/spanset/spanset.go]: Done.

File: pkg/kv/kvserver/spanset/spanset.go (hunk 19 above)
Comment (iskettaneh) [reply pkg/kv/kvserver/spanset/spanset.go]: Done! With the new helper function, I think you are going to like how Contains and Overlaps look now!

File: pkg/kv/kvserver/spanset/spanset.go (hunk 21 above)
Comment (iskettaneh) [reply pkg/kv/kvserver/spanset/spanset.go]: Done.

File: pkg/kv/kvserver/spanset/batch.go (hunk 31 above)
Comment (iskettaneh) [reply pkg/kv/kvserver/spanset/batch.go]: I refactored the code a bit and I introduced SpanSet ShallowCopy which helped clean things up.

File: pkg/kv/kvserver/spanset/batch.go (hunk 32 above)
Comment (iskettaneh) [reply pkg/kv/kvserver/spanset/batch.go]: With the new refactoring, I believe things are clearer now.

File: pkg/kv/kvserver/spanset/batch.go (hunk 34 above)
Comment (iskettaneh) [reply pkg/kv/kvserver/spanset/batch.go]: I refactored the code a bit and I introduced SpanSet ShallowCopy which helped clean things up.

File: pkg/kv/kvserver/spanset/batch.go (hunk 33 above)
Comment (iskettaneh) [reply pkg/kv/kvserver/spanset/batch.go]: I added a TODO to address that. I think some of these fields aren't even read.

File: pkg/kv/kvserver/spanset/spanset.go (hunk 30 above)
Comment (iskettaneh) [reply pkg/kv/kvserver/spanset/spanset.go]: Oh yes this was fixed in a commit after that, but now I fixed it in the commit that introduced it.

File: pkg/kv/kvserver/spanset/spanset_test.go (hunk 35 above)
Comment (iskettaneh) [reply pkg/kv/kvserver/spanset/spanset_test.go]: I personally like to split them into two tests since they logically assert on two different functions. If you feel strongly about it, I can merge them.

**Review by iskettaneh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/157153)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @pav-kv)

File: pkg/kv/kvserver/spanset/batch.go (hunk 31 above)
Comment (iskettaneh) [reply pkg/kv/kvserver/spanset/batch.go]: I refactored the code a bit and I introduced SpanSet ShallowCopy which helped clean things up.

File: pkg/kv/kvserver/spanset/batch.go (hunk 32 above)
Comment (iskettaneh) [reply pkg/kv/kvserver/spanset/batch.go]: With the new refactoring, I believe things are clearer now.

File: pkg/kv/kvserver/spanset/batch.go (hunk 34 above)
Comment (iskettaneh) [reply pkg/kv/kvserver/spanset/batch.go]: I refactored the code a bit and I introduced SpanSet ShallowCopy which helped clean things up.

File: pkg/kv/kvserver/spanset/batch.go (hunk 33 above)
Comment (iskettaneh) [reply pkg/kv/kvserver/spanset/batch.go]: I added a TODO to address that. I think some of these fields aren't even read.

File: pkg/kv/kvserver/spanset/spanset.go (hunk 30 above)
Comment (iskettaneh) [reply pkg/kv/kvserver/spanset/spanset.go]: Oh yes this was fixed in a commit after that, but now I fixed it in the commit that introduced it.

File: pkg/kv/kvserver/spanset/spanset_test.go (hunk 35 above)
Comment (iskettaneh) [reply pkg/kv/kvserver/spanset/spanset_test.go]: I personally like to split them into two tests since they logically assert on two different functions. If you feel strongly about it, I can merge them.

**Review by iskettaneh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/157153)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @pav-kv)

File: pkg/kv/kvserver/spanset/batch.go [hunk 36]
```diff
@@ -766,7 +766,9 @@ func NewReadWriterAt(rw storage.ReadWriter, spans *SpanSet, ts hlc.Timestamp) st
 
 type spanSetBatch struct {
 	ReadWriter
-	b     storage.Batch
+	b storage.Batch
+	// TODO(ibrahim): The fields spans, spansOnly, and ts don't seem to be used.
+	// Consider removing them and performing the necessary clean ups.
```
Comment (pav-kv) [inline pkg/kv/kvserver/spanset/batch.go]: or making them used as intended

File: pkg/kv/kvserver/spanset/spanset.go [hunk 37]
```diff
@@ -155,7 +163,19 @@ func (s *SpanSet) Copy() *SpanSet {
...
+	return n
+}
+
+// ShallowCopy performs a shallow SpanSet copy.
+func (s *SpanSet) ShallowCopy() *SpanSet {
+	n := New()
+	n.spans = s.spans
+	n.forbiddenSpansMatchers = s.forbiddenSpansMatchers
+	n.allowUndeclared = s.allowUndeclared
+	n.allowForbidden = s.allowForbidden
```
Comment (pav-kv) [inline pkg/kv/kvserver/spanset/spanset.go]: Should we just say:

```golang
n := New()
*n = *s
return n
```

File: pkg/kv/kvserver/spanset/spanset.go [hunk 38]
```diff
@@ -201,14 +221,22 @@ func (s *SpanSet) AddMVCC(access SpanAccess, span roachpb.Span, timestamp hlc.Ti
...
 // Merge merges all spans in s2 into s. s2 is not modified.
 func (s *SpanSet) Merge(s2 *SpanSet) {
 	for sa := SpanAccess(0); sa < NumSpanAccess; sa++ {
 		for ss := SpanScope(0); ss < NumSpanScope; ss++ {
 			s.spans[sa][ss] = append(s.spans[sa][ss], s2.spans[sa][ss]...)
 		}
 	}
+	s.forbiddenSpansMatchers = append(s.forbiddenSpansMatchers, s2.forbiddenSpansMatchers...)
 	s.allowUndeclared = s2.allowUndeclared
+	s.allowForbidden = s2.allowForbidden
```
Comment (pav-kv) [inline pkg/kv/kvserver/spanset/spanset.go:243]: pre-existing: the logic is fragile. Maybe it should be

```golang
s.allowUndeclared = s.allowUndeclared || s2.allowUndeclared
// same for allowForbidden
```

A TODO to figure that out would be good. Yet another reason to segregate the data structure from assertions.

File: pkg/kv/kvserver/spanset/batch.go [hunk 39]
```diff
@@ -838,6 +840,22 @@ func (s spanSetBatch) ClearRawEncodedRange(start, end []byte) error {
 	return s.b.ClearRawEncodedRange(start, end)
 }
 
+// clone returns a shallow copy of the spanSetBatch. The returned batch shares
+// the same underlying storage.Batch but has its own spanSetBatch wrapper with
+// a new copy of the SpanSet that uses a shallow copy of the underlying spans.
+func (s spanSetBatch) clone() *spanSetBatch {
+	return &spanSetBatch{
```
Comment (pav-kv) [inline pkg/kv/kvserver/spanset/batch.go]: Maybe say (so that we don't forget any fields here):

```golang
b := s
b.spanSetReader.spans = b.spanSetReader.spans.ShallowCopy()
b.spanSetWriter.spans = b.spanSetWriter.spans.ShallowCopy()
b.spans = b.spans.ShallowCopy()
return &b
```

File: pkg/kv/kvserver/spanset/batch.go [hunk 40]
```diff
@@ -838,6 +840,22 @@ func (s spanSetBatch) ClearRawEncodedRange(start, end []byte) error {
 	return s.b.ClearRawEncodedRange(start, end)
 }
 
+// clone returns a shallow copy of the spanSetBatch. The returned batch shares
+// the same underlying storage.Batch but has its own spanSetBatch wrapper with
+// a new copy of the SpanSet that uses a shallow copy of the underlying spans.
+func (s spanSetBatch) clone() *spanSetBatch {
```
Comment (pav-kv) [inline pkg/kv/kvserver/spanset/batch.go]: nit: rename also to `shallowCopy()`?

File: pkg/kv/kvserver/spanset/spanset.go [hunk 41]
```diff
@@ -392,16 +397,11 @@ func (s *SpanSet) checkAllowed(
...
-// In this form, s2.Key (inclusive) is considered to be the previous key to
-// s2.EndKey (exclusive).
-func contains(s1, s2 roachpb.Span) bool {
-	if s2.Key != nil {
-		// The common case.
-		return s1.Contains(s2)
-	}
-
+// doesNormalSpanContainPointTrickySpan takes a normal span (s1) that has
+// both Key and EndKey not nil, and takes a tricky span s2, where the Key is
```
Comment (pav-kv) [inline pkg/kv/kvserver/spanset/spanset.go]: `s1.EndKey` can be nil. Can just say that it's a normal `Span`.

File: pkg/kv/kvserver/spanset/spanset.go [hunk 42]
```diff
@@ -412,6 +412,28 @@ func contains(s1, s2 roachpb.Span) bool {
...
+
+// Overlaps returns whether s1 overlaps s2, where s2 can be a TrickySpan.
+func Overlaps(s1 roachpb.Span, s2 TrickySpan) bool {
+	// The common case: both spans have non-nil start keys.
+	if s2.Key != nil {
+		return s1.Overlaps(roachpb.Span(s2))
+	}
+
+	// s2 is a TrickySpan with nil Key and non-nil EndKey.
+	return doesNormalSpanContainPointTrickySpan(s1, s2)
```
Comment (pav-kv) [inline pkg/kv/kvserver/spanset/spanset.go:433]: Comment why it's legit? Something like: s2 is an infinitely small span, so it overlaps s1 iff it is contained in it.

File: pkg/kv/kvserver/spanset/spanset_test.go [hunk 43]
```diff
@@ -203,25 +204,25 @@ func TestSpanSetCheckAllowedAtTimestamps(t *testing.T) {
 	ss.AddNonMVCC(SpanReadWrite, roachpb.Span{Key: keys.RangeGCThresholdKey(1)})
 
 	var allowedRO = []struct {
```
Comment (pav-kv) [inline pkg/kv/kvserver/spanset/spanset_test.go:206]: No tests here with `TrickySpan{EndKey: something}`. Could be good to add some. We have good coverage for it, so optional / TODO.

More generally, would be also good to de-boilerplate these tests. Also feel free to ignore / TODO.

Same below.

File: pkg/kv/kvserver/spanset/spanset_test.go (hunk 35 above)
Comment (pav-kv) [reply pkg/kv/kvserver/spanset/spanset_test.go]: At your discretion, but my opinion: I think in situations like this it's justifiable: concentrate the combinatorics in one place. As a reader, I'd be happier to review/maintain one list rather than two. Plus, the benefit that we can check relations between the two funcs, as an extra assertion.

This relates to one of my previous points (in this instance an overkill, but consider this logically): these 2 funcs could be one - `DiffSpans(s1, s2) -> descriptor` where the "descriptor" tells us everything about the relative position of the two spans. From it, we can say whether they overlap, contained, etc. So logically it's one test: for 2 spans - what "descriptor" do we expect.

The way I would write (and [self-]review) this test is:
1. Have the first span fixed, and the second one "slide" left to right to cross/not-cross it in all possible ways.
	- Sliding in the `(Key, EndKey)` tuple order.
	- I.e. first "slide" a point `TrickySpan`
	- Then a point key
	- Then some (Key, EndKey) spans visiting us in some corner-casey positions.
2. Do the same with the first span being a point key.

File: pkg/kv/kvserver/batcheval/cmd_end_transaction.go [hunk 44]
```diff
@@ -1340,8 +1340,10 @@ func splitTriggerHelper(
 	if err != nil {
 		return enginepb.MVCCStats{}, result.Result{}, errors.Wrap(err, "unable to fetch last replica GC timestamp")
 	}
+
 	if err := storage.MVCCPutProto(
-		ctx, batch, keys.RangeLastReplicaGCTimestampKey(split.RightDesc.RangeID), hlc.Timestamp{},
+		ctx, spanset.DisableForbiddenSpanAssertionsOnBatch(batch),
```
Comment (pav-kv) [inline pkg/kv/kvserver/batcheval/cmd_end_transaction.go]: In `DisableForbiddenSpanAssertionsOnBatch` definition, pop in a TODO to eliminate all its users?

File: pkg/kv/kvserver/replica_test.go [hunk 45]
```diff
@@ -15197,3 +15197,110 @@ func TestLeaderlessWatcherInit(t *testing.T) {
...
 }
+
+// TestOverlapsUnreplicatedRangeIDLocalKeys verifies that the function
+// overlapsUnreplicatedRangeIDLocalKeys() successfully catches any overlap with
+// unreplicated rangeID local keys.
+func TestOverlapsUnreplicatedRangeIDLocalKeys(t *testing.T) {
+	defer leaktest.AfterTest(t)()
+	defer log.Scope(t).Close(t)
+	testCases := []struct {
+		name      string
```
Comment (pav-kv) [inline pkg/kv/kvserver/replica_test.go]: unused

File: pkg/kv/kvserver/replica_test.go [hunk 46]
```diff
@@ -15197,3 +15197,110 @@ func TestLeaderlessWatcherInit(t *testing.T) {
...
+		span      roachpb.Span
+		expectErr bool
+	}{
+		// Span before local RangeID.
+		{span: roachpb.Span{Key: roachpb.KeyMin, EndKey: keys.LocalRangeIDPrefix.AsRawKey()},
```
Comment (pav-kv) [inline pkg/kv/kvserver/replica_test.go]: A little inlined helper above would help de-boilerplating this:

```golang
s := func(start, end roachpb.Key) roachpb.Span {
	return roachpb.Span{...}
}

...
{span: s(roachpb.KeyMin, keys.LocalRangeIDPrefix.AsRawKey())}
...
```

File: pkg/kv/kvserver/replica_test.go [hunk 47]
```diff
@@ -15197,3 +15197,110 @@ func TestLeaderlessWatcherInit(t *testing.T) {
...
+			expectErr: false},
```
Comment (pav-kv) [inline pkg/kv/kvserver/replica_test.go]: Another good pattern for tests: in situations with "expect error", where a good half of the cases are "no error", it's fine to drop "expectErr: false" in favour of the default.

super-nit: also make the name short like `notOK bool`

File: pkg/kv/kvserver/replica_test.go [hunk 48]
```diff
@@ -15197,3 +15197,110 @@ func TestLeaderlessWatcherInit(t *testing.T) {
...
+		// Span after local RangeID.
+		{span: roachpb.Span{Key: keys.LocalRangePrefix, EndKey: roachpb.KeyMax},
```
Comment (pav-kv) [inline pkg/kv/kvserver/replica_test.go]: Tighten this one up to `LocalRangeIDPrefix.PrefixEnd()`?

File: pkg/kv/kvserver/replica_write.go [hunk 49]
```diff
@@ -884,3 +889,66 @@ func releaseMVCCStats(ms *enginepb.MVCCStats) {
...
+
+	// If the provided span is completely outside the rangeID local spans for any
+	// rangeID, then there is no overlap with any rangeID local keys.
+	if !spanset.Overlaps(fullRangeIDLocalSpans, span) {
+		return nil
+	}
+
+	// At this point, we know that either we are containing the
+	// fullRangeIDLocalSpans, or we are completely within fullRangeIDLocalSpans.
+	// Check to see if we fully contain fullRangeIDLocalSpans.
```
Comment (pav-kv) [inline pkg/kv/kvserver/replica_write.go]: We only know that we overlap. So, by this check, we're (correctly) excluding a bit more cases. We say that the only correct overlap is that we are inside the RangeID-local subtree.

File: pkg/keys/constants.go [hunk 50]
```diff
@@ -163,6 +163,7 @@ var (
 	//
 	// LocalStorePrefix is the prefix identifying per-store data.
 	LocalStorePrefix = makeKey(LocalPrefix, roachpb.Key("s"))
+	LocalStoreMax    = roachpb.Key(LocalStorePrefix).PrefixEnd()
```
Comment (pav-kv) [inline pkg/keys/constants.go]: nit: `LocalStorePrefixEnd`

File: pkg/kv/kvserver/replica_test.go [hunk 51]
```diff
@@ -15197,3 +15197,110 @@ func TestLeaderlessWatcherInit(t *testing.T) {
...
+}
+
+// TestOverlapsStoreLocalKeys verifies that the function
+// overlapsStoreLocalKeys() successfully catches any overlap with
+// store local keys.
+func TestOverlapsStoreLocalKeys(t *testing.T) {
+	defer leaktest.AfterTest(t)()
+	defer log.Scope(t).Close(t)
+	testCases := []struct {
+		name      string
```
Comment (pav-kv) [inline pkg/kv/kvserver/replica_test.go]: unused

File: pkg/kv/kvserver/replica_test.go [hunk 52]
```diff
@@ -15197,3 +15197,110 @@ func TestLeaderlessWatcherInit(t *testing.T) {
...
+		// Span after store local span.
+		{span: roachpb.Span{Key: keys.LocalStoreMax, EndKey: roachpb.KeyMax}, expectErr: false},
+		// Span Contains store local span.
+		{span: roachpb.Span{Key: roachpb.KeyMin, EndKey: roachpb.KeyMax}, expectErr: true},
+		// Span partially overlaps with store local span.
+		{span: roachpb.Span{Key: roachpb.KeyMin, EndKey: keys.StoreIdentKey()}, expectErr: true},
+		{span: roachpb.Span{Key: keys.StoreIdentKey(), EndKey: roachpb.KeyMax}, expectErr: true},
+		// Span overlaps with store local keys.
+		{span: roachpb.Span{Key: keys.StoreGossipKey(), EndKey: keys.StoreIdentKey()}, expectErr: true},
+		// Point span before store local span.
```
Comment (pav-kv) [inline pkg/kv/kvserver/replica_test.go]: Readability: group these tests in some way, e.g.

```golang
// Not overlapping the Store-local span.
{span: s(roachpb.KeyMin, keys.LocalStorePrefix},
{span: s(keys.LocalStoreMax, roachpb.KeyMax},
...
// Overlapping the Store-local span in various ways (left to right).
{span: s(something, something), notOk: true},
...
// TrickySpans (ordered left to right).
{span: s(nil, MinKey)},
{span: s(nil, LocalStorePrefix)},
{span: s(nil, LocalStorePrefix.Next()), notOk: true},
...
```

File: pkg/kv/kvserver/replica_test.go [hunk 53]
```diff
@@ -15197,3 +15197,110 @@ func TestLeaderlessWatcherInit(t *testing.T) {
...
+// unreplicated rangeID local keys.
+func TestOverlapsUnreplicatedRangeIDLocalKeys(t *testing.T) {
+	defer leaktest.AfterTest(t)()
+	defer log.Scope(t).Close(t)
+	testCases := []struct {
+		name      string
+		span      roachpb.Span
+		expectErr bool
+	}{
+		// Span before local RangeID.
```
Comment (pav-kv) [inline pkg/kv/kvserver/replica_test.go]: Same readability suggestion as in the below test: try grouping the tests logically, so that it's less flat.

```golang
// Spans outside the RangeID-local subtree.
{span: s(KeyMin, LocalRangeIDPrefix)}
{span: s(LocalRangeIDPrefix.PrefixEnd(), KeyMax)}
...
// Partial overlaps with RangeID-local subtree (ordered left to right).
{},
{},
// Below, cases when we are inside the RangeID-local subtree.

// Some groups here, e.g.
// 1. Good, only touch one RangeID and not touch its unreplicated.
// 2. Bad, touch unreplicated for one RangeID.
// 3. Bad, span multiple RangeIDs.
...
```

File: pkg/kv/kvserver/replica_test.go [hunk 54]
```diff
@@ -15197,3 +15197,110 @@ func TestLeaderlessWatcherInit(t *testing.T) {
...
+		// Span contains the full local RangeID span.
+		{span: roachpb.Span{Key: roachpb.KeyMin, EndKey: roachpb.KeyMax},
+			expectErr: true},
+		// Span partially overlaps the full RangeID span.
+		{span: roachpb.Span{Key: roachpb.KeyMin, EndKey: keys.RaftTruncatedStateKey(1)},
+			expectErr: true},
+		{span: roachpb.Span{Key: keys.RaftTruncatedStateKey(1), EndKey: roachpb.KeyMax},
+			expectErr: true},
+		// Span inside unreplicated local RangeID span.
+		{span: roachpb.Span{Key: keys.RangeTombstoneKey(1), EndKey: keys.RaftTruncatedStateKey(1)},
```
Comment (pav-kv) [inline pkg/kv/kvserver/replica_test.go]: Somewhere here need a test that spans at least 2 range IDs.

**Review by pav-kv — COMMENTED** [review]
The non-test parts LGTM, minor suggestions. Request to clean up the tests a bit, so that I can make a final (self-convincing) pass on them and LGTM tomorrow.

File: pkg/kv/kvserver/spanset/spanset_test.go (hunk 35 above)
Comment (pav-kv) [reply pkg/kv/kvserver/spanset/spanset_test.go]: If you end up with two tests, consider incorporating the latter thing about having more structure in the sequence, so that it's easy to follow the flow (and give a hint in the comment how to "scan" it).

File: pkg/kv/kvserver/spanset/spanset_test.go [hunk 55]
```diff
@@ -381,16 +388,106 @@ func TestSpanSetWriteImpliesRead(t *testing.T) {
...
+	var start roachpb.Key
+	var end roachpb.Key
+
+	if parts[0] != "X" {
+		start = roachpb.Key(parts[0])
+	}
+
+	if parts[1] != "X" {
+		end = roachpb.Key(parts[1])
+	}
```
Comment (pav-kv) [inline pkg/kv/kvserver/spanset/spanset_test.go:421]: style nit / opinion (feel free to ignore, just noticed the pattern in this PR, e.g. in `overlapsUnreplicatedRangeIDLocalKeys` too):

In simple code, vertical sparseness / empty lines is often not needed (makes "value" per screen lower). Empty lines is a tool to communicate/separate slightly more medium-size blocks of logically related code, offering some "structure" to the reader.

E.g. here I would recommend making it one block, because it's all about converting `parts` to `span`:

```golang
var span roachpb.Span
if parts[0] != "X" {
	span.Key = roachpb.Key(parts[0])
}
if parts[1] != "X" {
	span.EndKey = roachpb.Key(parts[1])
}
return span
```

As an extension to this (more applies to other places: `Contains/Overlaps` and the two matcher funcs), comments are another "separator" which we can play with to show structure:

```
// Need to do this and that for some reasons.
this()
that()
// And do something different, but still related to this block.
still()
related()

// And here is a comment after a break. Which emphasizes the
// 2-level structure. Above, there is a "block" with 2 sub-blocks.
// Now, it's a new "higher-level" block.
totally()
different()
thing()
```

File: pkg/kv/kvserver/replica_write.go [hunk 56]
```diff
@@ -884,3 +889,66 @@ func releaseMVCCStats(ms *enginepb.MVCCStats) {
...
+
+	// If the provided span is completely outside the rangeID local spans for any
+	// rangeID, then there is no overlap with any rangeID local keys.
+	if !spanset.Overlaps(fullRangeIDLocalSpans, span) {
+		return nil
+	}
+
+	// At this point, we know that we overlap with fullRangeIDLocalSpans. If we
+	// are not completely within fullRangeIDLocalSpans, return an error as we
+	// collide with at least one unreplicated RangeIDLocal key.
```
Comment (pav-kv) [inline pkg/kv/kvserver/replica_write.go]: Technically, it's possible that we don't collide. E.g. you can imagine a little span that begins before the RangeID-local space, and slightly moves into it without touching the first range's unreplicated.

We just make it a "policy" here that it shouldn't be possible, i.e. the spans are sensibly respecting the "tree" structure, and a span that begins outside the subtree and ends inside (or vice versa) doesn't make logical sense.

Dunno it there is a concise way to say this, see if you can compress it :)

File: pkg/kv/kvserver/replica_test.go [hunk 57]
```diff
@@ -15197,3 +15197,123 @@ func TestLeaderlessWatcherInit(t *testing.T) {
...
+		// Full spans overlapping with Store-local span.
+		{span: s(roachpb.KeyMin, roachpb.Key(keys.LocalStorePrefix).Next()), notOK: true},
+		{span: s(keys.LocalStorePrefix, keys.LocalStoreMax), notOK: true},
+		{span: s(keys.StoreGossipKey(), keys.StoreIdentKey()), notOK: true},
+		{span: s(keys.LocalStoreMax.Prevish(1), roachpb.KeyMax), notOK: true},
+
+		// Point spans not overlapping with Store-local span.
+		{span: s(roachpb.KeyMin, nil)},
+		{span: s(roachpb.Key(keys.LocalStorePrefix).Prevish(1), nil)},
+		{span: s(keys.LocalStoreMax.Next(), nil)},
```
Comment (pav-kv) [inline pkg/kv/kvserver/replica_test.go:15300]: Add `LocalStoreMax` here too, since it's not inclusive?

File: pkg/kv/kvserver/replica_test.go [hunk 58]
```diff
@@ -15197,3 +15197,123 @@ func TestLeaderlessWatcherInit(t *testing.T) {
...
+				require.NoErrorf(t, err, "expected no error for span %s", tc.span)
+			}
+		})
+	}
+}
+
+// TestOverlapsStoreLocalKeys verifies that the function
+// overlapsStoreLocalKeys() successfully catches any overlap with
+// store local keys.
+func TestOverlapsStoreLocalKeys(t *testing.T) {
```
Comment (pav-kv) [inline pkg/kv/kvserver/replica_test.go:15274]: Nice, thanks a lot for the clean up! Was able to review this test in a minute and spot an edge case to add.

File: pkg/kv/kvserver/replica_test.go [hunk 59]
```diff
@@ -15197,3 +15197,123 @@ func TestLeaderlessWatcherInit(t *testing.T) {
...
+	}
+
+	for _, tc := range testCases {
+		t.Run("", func(t *testing.T) {
+			err := overlapsStoreLocalKeys(spanset.TrickySpan(tc.span))
+			if tc.notOK {
+				require.Errorf(t, err, "expected error for span %s", tc.span)
+			} else {
+				require.NoErrorf(t, err, "expected no error for span %s", tc.span)
+			}
```
Comment (pav-kv) [inline pkg/kv/kvserver/replica_test.go]: optional (2 patterns too):

```golang
require.Equal(t, tc.notOk, err != nil, tc.span)
```

Same above.

File: pkg/kv/kvserver/replica_test.go [hunk 60]
```diff
@@ -15197,3 +15197,123 @@ func TestLeaderlessWatcherInit(t *testing.T) {
...
+		return roachpb.Span{Key: start, EndKey: end}
+	}
+
+	testCases := []struct {
+		span  roachpb.Span
+		notOk bool
+	}{
+		// Full spans not overlapping with unreplicated local RangeID spans.
+		{span: s(roachpb.KeyMin, keys.LocalRangeIDPrefix.AsRawKey())},
+		{span: s(keys.RangeForceFlushKey(1), keys.RangeLeaseKey(1))},
```
Comment (pav-kv) [inline pkg/kv/kvserver/replica_test.go:15217]: Can add a "typical" one here: a full replicated span (which includes both ForceFlush and RangeLease keys).

File: pkg/kv/kvserver/batcheval/cmd_truncate_log.go [hunk 61]
```diff
@@ -118,7 +118,9 @@ func TruncateLog(
 	// are not tracked in the raft log delta. The delta will be adjusted below
 	// raft.
 	// We can pass zero as nowNanos because we're only interested in SysBytes.
-	ms, err := storage.ComputeStats(ctx, readWriter, start, end, 0 /* nowNanos */)
+	// TODO(#157895): Use the log engine here instead of the state machine engine.
```
Comment (pav-kv) [inline pkg/kv/kvserver/batcheval/cmd_truncate_log.go]: Likely can unTODO this, since this PR is merged.

File: pkg/keys/keys.go [hunk 62]
```diff
@@ -308,6 +308,21 @@ func DecodeRangeIDKey(
...
+		return 0, errors.Errorf("key %s does not have %s prefix", key, LocalRangeIDPrefix)
+	}
+	// Cut the prefix, the Range ID, and the infix specifier.
+	b := key[len(LocalRangeIDPrefix):]
+	_, rangeInt, err := encoding.DecodeUvarintAscending(b)
+	if err != nil {
+		return 0, err
+	}
+
+	return roachpb.RangeID(rangeInt), nil
```
Comment (pav-kv) [inline pkg/keys/keys.go]: Can return without checking:

```golang
return roachpb.RangeID(rangeInt), err
```

Pretty sure `DecodeUvarint` already returns zero on error (it's conventional, so we can do it transitively), but even if not, no big deal.

File: pkg/kv/kvserver/replica_test.go [hunk 63]
```diff
@@ -15197,3 +15197,123 @@ func TestLeaderlessWatcherInit(t *testing.T) {
...
+
+		// Point spans overlapping with unreplicated local RangeID spans.
+		{span: s(keys.RangeTombstoneKey(1), nil), notOk: true},
+		{span: s(keys.RaftTruncatedStateKey(1), nil), notOk: true},
+		{span: s(keys.RaftTruncatedStateKey(2), nil), notOk: true},
+
+		// Tricky spans not overlapping with unreplicated local RangeID spans.
+		{span: s(nil, keys.LocalRangeIDPrefix.AsRawKey())},
+		{span: s(nil, keys.RangeForceFlushKey(1))},
+		{span: s(nil, keys.LocalRangeIDPrefix.AsRawKey().PrefixEnd().Next())},
```
Comment (pav-kv) [inline pkg/kv/kvserver/replica_test.go:15252]: Can add one without `Next()`, it should be legit too (IIUC it will take a different branch in the func).

File: pkg/kv/kvserver/replica_test.go [hunk 64]
```diff
@@ -15197,3 +15197,123 @@ func TestLeaderlessWatcherInit(t *testing.T) {
...
+
+		// Tricky spans overlapping with unreplicated local RangeID spans.
```
Comment (pav-kv) [inline pkg/kv/kvserver/replica_test.go:15254]: A couple of corner cases would be good: for the beginning and ending of the unreplicated span.

Applies to a few blocks here. Could be convenient to pre-compute a couple of `var`s for some unreplicated span and use it in a few places:

```golang
r1Unrepl := roachpb.Span{...}

{span: s(r1Unrepl.Key.Prev(), nil)},
{span: s(r1Unrepl.EndKey, nil)},
{span: s(nil, r1Unrepl.EndKey), notOk: true},
// etc
```

File: pkg/kv/kvserver/replica_test.go [hunk 65]
```diff
@@ -15197,3 +15197,123 @@ func TestLeaderlessWatcherInit(t *testing.T) {
...
+		{span: s(keys.RangeForceFlushKey(1), nil)},
+		{span: s(keys.LocalRangeIDPrefix.AsRawKey().PrefixEnd(), nil)},
+		{span: s(roachpb.KeyMax, nil)},
+
+		// Point spans overlapping with unreplicated local RangeID spans.
+		{span: s(keys.RangeTombstoneKey(1), nil), notOk: true},
+		{span: s(keys.RaftTruncatedStateKey(1), nil), notOk: true},
+		{span: s(keys.RaftTruncatedStateKey(2), nil), notOk: true},
+
+		// Tricky spans not overlapping with unreplicated local RangeID spans.
```
Comment (pav-kv) [inline pkg/kv/kvserver/replica_test.go]: A couple of corner cases around the unreplicated span edges.

File: pkg/kv/kvserver/replica_test.go [hunk 66]
```diff
@@ -15197,3 +15197,123 @@ func TestLeaderlessWatcherInit(t *testing.T) {
...
+		{span: s(keys.LocalRangeIDPrefix.AsRawKey().PrefixEnd(), roachpb.KeyMax)},
+
+		// Full spans overlapping with unreplicated local RangeID spans.
+		{span: s(roachpb.KeyMin, keys.RaftTruncatedStateKey(1)), notOk: true},
+		{span: s(keys.LocalRangeIDPrefix.AsRawKey(), keys.LocalRangeIDPrefix.AsRawKey().PrefixEnd()),
+			notOk: true},
+		{span: s(keys.RaftTruncatedStateKey(1), keys.RaftTruncatedStateKey(2)), notOk: true},
+		{span: s(keys.RaftTruncatedStateKey(1), roachpb.KeyMax), notOk: true},
+
+		// Point spans not overlapping with unreplicated local RangeID spans.
```
Comment (pav-kv) [inline pkg/kv/kvserver/replica_test.go]: A couple of corner cases around the unreplicated span edges.

Applies to a few blocks here. Could be convenient to pre-compute a couple of `var`s for some unreplicated span and use it in a few places:

```golang
r1Unrepl := roachpb.Span{...}

{span: s(r1Unrepl.Key.Prev(), nil)},
{span: s(r1Unrepl.EndKey, nil)},

// further down
{span: s(nil, r1Unrepl.EndKey), notOk: true},
// etc
```

File: pkg/kv/kvserver/spanset/spanset_test.go [hunk 67]
```diff
@@ -381,16 +388,106 @@ func TestSpanSetWriteImpliesRead(t *testing.T) {
...
+
+	testCases := []struct {
+		s1       string
+		s2       string
+		contains bool
+		overlaps bool
+	}{
+		// s1 is a full span, and s2 is a tricky span with nil StartKey.
+		{s1: "b-d", s2: "X-a", contains: false, overlaps: false},
+		{s1: "b-d", s2: "X-b", contains: false, overlaps: false},
```
Comment (pav-kv) [inline pkg/kv/kvserver/spanset/spanset_test.go:442]: Add

```
{s1: "b-d", s2: "X-b\x00", contains: true, overlaps: true},
```

Maybe a few more corner cases with `\x00` in other blocks below. Those are interesting cases, when we have a key and its `Next()`. Perhaps not in all groups, but in the point tricky spans for sure because there is a line checking `IsPrev` in the func.

File: pkg/kv/kvserver/spanset/batch.go [hunk 68]
```diff
@@ -888,6 +902,42 @@ func DisableReadWriterAssertions(rw storage.ReadWriter) storage.ReadWriter {
...
+	}
+}
+
+// DisableForbiddenSpanAssertionsOnBatch returns a new batch wrapper with
+// forbidden span assertions disabled. It does not modify the original batch.
+// The returned batch shares the same underlying storage.Batch but has its own
+// SpanSet wrapper with the forbidden span assertion disabled.
+// TODO(ibrahim): We eventually want to eliminate all the users of this
+// function.
+func DisableForbiddenSpanAssertionsOnBatch(rw storage.ReadWriter) storage.ReadWriter {
```
Comment (pav-kv) [inline pkg/kv/kvserver/spanset/batch.go]: nit: the two "disable" methods could be named in a similar style e.g.

`DisableUndeclaredSpanAssertions`
`DisableForbiddenSpanAssertions`

or if you fancy brevity:

`NoUndeclaredSpanAsserts`
`NoForbiddenSpanAsserts`

File: pkg/kv/kvserver/spanset/spanset.go [hunk 69]
```diff
@@ -396,3 +455,8 @@ func (s *SpanSet) Validate() error {
 func (s *SpanSet) DisableUndeclaredAccessAssertions() {
 	s.allowUndeclared = true
 }
+
+// DisableForbiddenAssertions disables forbidden spans assertions.
```
Comment (pav-kv) [inline pkg/kv/kvserver/spanset/spanset.go]: Sync the comment with the name?

**Review by pav-kv — APPROVED** [review]
LGTM, thanks for this change! Some last suggestions included, apply as many as makes sense.

File: pkg/kv/kvserver/replica_test.go (hunk 58 above)
Comment (iskettaneh) [reply pkg/kv/kvserver/replica_test.go:15274]: Thank you!
