### PR TITLE
decider: ignore EnsureSafeSplitKey on error

### LINKED ISSUE #42903: roachtest: splits/load/uniform/nodes=3 failed
SHA: https://github.com/cockroachdb/cockroach/commits/d3574ad671bd3631e780510235485681720c2b8f

Parameters:

To repro, try:

```
# Don't forget to check out a clean suitable branch and experiment with the
# stress invocation until the desired results present themselves. For example,
# using stress instead of stressrace and passing the '-p' stressflag which
# controls concurrency.
./scripts/gceworker.sh start && ./scripts/gceworker.sh mosh
cd ~/go/src/github.com/cockroachdb/cockroach && \
stdbuf -oL -eL \
make stressrace TESTS=splits/load/uniform/nodes=3 PKG=roachtest TESTTIMEOUT=5m STRESSFLAGS='-maxtime 20m -timeout 10m' 2>&1 | tee /tmp/stress.log
```

Failed test: https://teamcity.cockroachdb.com/viewLog.html?buildId=1622074&tab=artifacts#/splits/load/uniform/nodes=3

```
The test failed on branch=master, cloud=gce:
test artifacts and logs in: /home/agent/work/.go/src/github.com/cockroachdb/cockroach/artifacts/20191203-1622074/splits/load/uniform/nodes=3/run_1
	cluster.go:2163,split.go:205,split.go:50,test_runner.go:697: kv.kv has 1 ranges, expected between 11 and 2147483647 splits

```

### PR DESCRIPTION
**Pull request by tbg**
Fixes #42903.

Load based splitting would previously not split when EnsureSafeSplitKey
returns an error. However such an error only meant that the key in
question wasn't even a SQL key, which is the case most of the time,
at least in simple workloads such as kv (the SQL layer will send
single-element scans, but without specifying the column family).

No release note since not released.

Release note: None

### CODE REVIEW

**Review by nvb — APPROVED** [review]
:lgtm: though this would probably be pretty easy to test.

> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/43078#-:-Lvkh8cX6XEO50EiEt8g:bmgqvsy)* status: :shipit: complete! 1 of 0 LGTMs obtained

**Comment by tbg** [comment]
You're right, test added. TFTR!

File: pkg/storage/split/decider.go [hunk 1]
```diff
@@ -165,10 +165,16 @@ func (d *Decider) MaybeSplitKey(now time.Time) roachpb.Key {
 		//
 		// We take the risk that the result may sometimes not be a good split
 		// point (or even in this range).
-		var err error
-		key, err = keys.EnsureSafeSplitKey(d.mu.splitFinder.Key())
-		if err != nil {
-			key = nil
+		//
+		// Note that we ignore EnsureSafeSplitKey when it returns an error since
```
Comment (RaduBerinde) [inline pkg/storage/split/decider.go]: I don't get it - the comment above says that we don't want to allow mid-row splits and that SQL even crashes.. If this changed we should update that comment

Comment (RaduBerinde) [reply pkg/storage/split/decider.go]: Oh, or we know for sure that in the error case the key is "in-between" rows? Seems like we should fix `EnsureSafeSplitKey` to not return an error at all, or at least explain this in its comment

Comment (tbg) [reply pkg/storage/split/decider.go]: SQL sort of forces us to avoid mid-column family splits and we can't do so because you can't tell the column family suffix if you don't know the SQL schema. Also SQL issues plenty of scans that don't have the column family in the start key, so that's what the split finder sees. So when it sees a key that doesn't look like a SQL key, it has to assume that it doesn't cut columns in half, or it couldn't split most of the time (as we saw in the test this commit fixes). This probably holds but if you issued unfortunate batch requests you can definitely trick it into still splitting between col families.

I'm pretty unhappy about the situation in here and it seems reasonable to make SQL resilient to col families being split between ranges, not because I love that, but because I don't see any other way 😞

Comment (RaduBerinde) [reply pkg/storage/split/decider.go]: Bleah. I would put these details in an issue and mention the issue in the comment.

**Comment by tbg** [comment]
bors r=nvanbenschoten
