### PR TITLE
workload/schemachange: disable inserts due to flakes

### LINKED ISSUE #91859: schemachange: flake in TestWorkload
Found here: https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_BazelExtendedCi/7504393?buildTab=overview&showRootCauses=false&expandBuildProblemsSection=true&expandBuildTestsSection=true&expandBuildChangesSection=true

Log file: https://teamcity.cockroachdb.com/repository/download/Cockroach_Ci_TestsAwsLinuxArm64_UnitTests/7504392:id/bazel-testlogs/pkg/ccl/testccl/workload/schemachange/schemachange_test/test.log

```
    schema_change_external_test.go:108: 
        	Error Trace:	/home/roach/.cache/bazel/_bazel_roach/c5a4e7d36696d9cd970af2045211a7df/sandbox/processwrapper-sandbox/6265/execroot/com_github_cockroachdb_cockroach/bazel-out/aarch64-fastbuild/bin/pkg/ccl/testccl/workload/schemachange/schemachange_test_/schemachange_test.runfiles/com_github_cockroachdb_cockroach/pkg/ccl/testccl/workload/schemachange/schema_change_external_test.go:108
        	Error:      	Received unexpected error:
        	            	***UNEXPECTED ERROR; Received an unexpected execution error.: ERROR: integer out of range (SQLSTATE 22003)
        	            	(1) forced error mark
        	            	  | "fatal error when running txn"
        	            	  | github.com/cockroachdb/errors/withstack/*withstack.withStack::
        	            	Wraps: (2)
        	            	Wraps: (3) attached stack trace
        	            	  -- stack trace:
        	            	  | github.com/cockroachdb/cockroach/pkg/workload/schemachange.(*opStmt).executeStmt
        	            	  | 	github.com/cockroachdb/cockroach/pkg/workload/schemachange/operation_generator.go:2699
        	            	  | github.com/cockroachdb/cockroach/pkg/workload/schemachange.(*schemaChangeWorker).runInTxn
        	            	  | 	github.com/cockroachdb/cockroach/pkg/workload/schemachange/schemachange.go:368
        	            	  | github.com/cockroachdb/cockroach/pkg/workload/schemachange.(*schemaChangeWorker).run
        	            	  | 	github.com/cockroachdb/cockroach/pkg/workload/schemachange/schemachange.go:410
        	            	  | pkg/ccl/testccl/workload/schemachange/schemachange_test_test.TestWorkload.func3.1
        	            	  | 	pkg/ccl/testccl/workload/schemachange/schemachange_test_test/pkg/ccl/testccl/workload/schemachange/schema_change_external_test.go:97
        	            	  | golang.org/x/sync/errgroup.(*Group).Go.func1
        	            	  | 	golang.org/x/sync/errgroup/external/org_golang_x_sync/errgroup/errgroup.go:75
        	            	  | runtime.goexit
        	            	  | 	GOROOT/src/runtime/asm_arm64.s:1172
        	            	Wraps: (4) ***UNEXPECTED ERROR; Received an unexpected execution error.
        	            	Wraps: (5) ERROR: integer out of range (SQLSTATE 22003)
        	            	Error types: (1) *markers.withMark (2) *schemachange.ErrorState (3) *withstack.withStack (4) *errutil.withPrefix (5) *pgconn.PgError
        	Test:       	TestWorkload
```

cc @postamar for triage

Jira issue: CRDB-21461

### PR DESCRIPTION
**Pull request by fqazi**
Fixes: #91859

We started seeing flakes on the insert part of this workload, so let's temporarily disable them until we can find the cycles to the root cause of them. This patch temporarily disables the inserts in the workload.

Release note: None

### CODE REVIEW

File: pkg/workload/schemachange/operation_generator.go [hunk 1]
```diff
@@ -275,9 +275,9 @@ var opWeights = []int{
 	renameView:              1,
 	setColumnDefault:        1,
 	setColumnNotNull:        1,
-	setColumnType:           0,  // Disabled and tracked with #66662.
-	survive:                 0,  // Disabled and tracked with #83831
-	insertRow:               10, // Temporarily reduced because of #80820
+	setColumnType:           0, // Disabled and tracked with #66662.
+	survive:                 0, // Disabled and tracked with #83831
+	insertRow:               0, // Disabled and tracked with
```
Comment (Xiang-Gu) [inline pkg/workload/schemachange/operation_generator.go:280]: nit: you missed the issue number

**Review by Xiang-Gu — APPROVED** [review]

File: pkg/workload/schemachange/operation_generator.go (hunk 1 above)
Comment (fqazi) [reply pkg/workload/schemachange/operation_generator.go]: Fixed, forgot to paste it.

**Comment by fqazi** [comment]
blathers backport 22.2
