### PR TITLE
roachtest: add an ignore list to psycopg

### LINKED ISSUE #35053: roachtest: psycopg failed
SHA: https://github.com/cockroachdb/cockroach/commits/bd80a74f882a583d6bb2a04dfdb57b49254bc7ba

Parameters:

To repro, try:

```
# Don't forget to check out a clean suitable branch and experiment with the
# stress invocation until the desired results present themselves. For example,
# using stress instead of stressrace and passing the '-p' stressflag which
# controls concurrency.
./scripts/gceworker.sh start && ./scripts/gceworker.sh mosh
cd ~/go/src/github.com/cockroachdb/cockroach && \
stdbuf -oL -eL \
make stressrace TESTS=psycopg PKG=roachtest TESTTIMEOUT=5m STRESSFLAGS='-maxtime 20m -timeout 10m' 2>&1 | tee /tmp/stress.log
```

Failed test: https://teamcity.cockroachdb.com/viewLog.html?buildId=1143393&tab=buildLog

```
The test failed on master:
	psycopg.go:235,psycopg.go:246,test.go:1212: 
		Tests run on Cockroach v2.2.0-alpha.20190211-218-gbd80a74
		678 Total Tests Run
		345 tests passed
		333 tests failed
		0 tests passed unexpectedly
		1 tests failed unexpectedly
		0 tests expected failed, but not run 
		For a full summary look at the logs. 
		
		An updated blacklist (psycopgBlackList2_2) is available in the logs

```

### PR DESCRIPTION
**Pull request by BramGruneir**
There is one flaky test in the psycopg unit tests which adds failures to our
nightlies.  This will now allow for either a pass or fail. It shows up in
the raw test results as a SKIP.

Also cleaned up the output to allow for plural/singular tests/test.

Fixes #35053.

Release note: None

### CODE REVIEW

File: pkg/cmd/roachtest/hibernate.go [hunk 1]
```diff
@@ -257,11 +257,23 @@ echo "ext {
 		fmt.Fprintf(&bResults, "%d Total Tests Run\n",
 			passExpectedCount+passUnexpectedCount+failExpectedCount+failUnexpectedCount,
 		)
-		fmt.Fprintf(&bResults, "%d tests passed\n", passUnexpectedCount+passExpectedCount)
-		fmt.Fprintf(&bResults, "%d tests failed\n", failUnexpectedCount+failExpectedCount)
-		fmt.Fprintf(&bResults, "%d tests passed unexpectedly\n", passUnexpectedCount)
-		fmt.Fprintf(&bResults, "%d tests failed unexpectedly\n", failUnexpectedCount)
-		fmt.Fprintf(&bResults, "%d tests expected failed, but not run \n", notRunCount)
+		fmt.Fprintf(&bResults, "%d %s passed\n",
```
Comment (knz) [inline pkg/cmd/roachtest/hibernate.go]: maybe factor:

```
p := func(msg text, count int) {
  fmt.Fprintf(&bResults, "%d %s %s\n", count, plural("test", "tests", count), msg)
}
```

then below

```
p("passed", passUnexpectedCount+passExpectedCount)
p("failed", failUnexpectedCount+failExpectedCount)
... etc ...
```

**Review by BramGruneir — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/35218)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @knz)

___
*[pkg/cmd/roachtest/hibernate.go, line 260 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/35218#-LZfi4yxVwxfeqEwPNkH-r1-260:-LZfnZE53ZgD0MM4rezc:biyplym) ([raw file](https://github.com/cockroachdb/cockroach/blob/b9b8e2b84944f2d37cb4636dbf2e40dbe1e442c7/pkg/cmd/roachtest/hibernate.go#L260)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

maybe factor:

```
p := func(msg text, count int) {
  fmt.Fprintf(&bResults, "%d %s %s\n", count, plural("test", "tests", count), msg)
}
```

then below

```
p("passed", passUnexpectedCount+passExpectedCount)
p("failed", failUnexpectedCount+failExpectedCount)
... etc ...
```

</blockquote></details>

That's much cleaner, and I moved the plural function directly into that as well.
___
*[pkg/cmd/roachtest/psycopg.go, line 219 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/35218#-LZfi4yxVwxfeqEwPNkI-r1-219:-LZfoiMy3oJev7nYsuJo:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/b9b8e2b84944f2d37cb4636dbf2e40dbe1e442c7/pkg/cmd/roachtest/psycopg.go#L219)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.
