### PR TITLE
util: Fix interval division with float rounds differently from PostgreSQL

### LINKED ISSUE #66118: sql: interval division with float rounds differently from Python & PostgreSQL
see https://github.com/cockroachdb/cockroach/issues/66118#issuecomment-856366411 for solution

----

**Describe the problem**

Interval division with a float rounds differently from Python & PostgreSQL.

**To Reproduce**

```sql
CREATE TABLE "test1" (
    "id" serial NOT NULL PRIMARY KEY,
    "duration" interval NOT NULL
);

INSERT INTO "test1" ("duration") VALUES ('0 days 0.253000 seconds'::interval);

SELECT ("duration" / 3.2) FROM "test1";
     ?column?
-------------------
  00:00:00.079063
```

**Expected behavior**

Expected result of SELECT query: `00:00:00.079062`.

**Environment:**
 - CockroachDB version: 21.1.1 (and older versions)

**Additional context**

A Django test fails:
```
======================================================================
FAIL: test_durationfield_multiply_divide (expressions.tests.FTimeDeltaTests) (expr=3.2)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/tim/code/django/tests/expressions/tests.py", line 1565, in test_durationfield_multiply_divide
    self.assertEqual(
AssertionError: datetime.timedelta(microseconds=79063) != datetime.timedelta(microseconds=79062)
```

### PR DESCRIPTION
**Pull request by TszKitLo40**
Before this commit, the nanos will be rounded in `MakeDuration`.
This commit round down nanos before `rounded` is called in the div of duration.

Fixes #66118

Release note (bug fix): Fixed a bug with PostgreSQL compatibility where
dividing an interval by a number would round to the nearest Microsecond
instead of always rounding down.

### CODE REVIEW

File: pkg/sql/logictest/testdata/logic_test/interval [hunk 1]
```diff
@@ -367,3 +367,22 @@ subtest regression_62369
 
 query error "10000000000000000000000000000000000": value out of range
 SELECT INTERVAL '10000000000000000000000000000000000 year'
+
+statement ok
+CREATE TABLE regression_66118 (
```
Comment (otan) [inline pkg/sql/logictest/testdata/logic_test/interval:372]: can you make this

```
query TT
SELECT i / 2 FROM ( VALUES
  ('0 days 0.253000 seconds'::interval),
  (INTERVAL '0.000001'::interval)
) regression_66118(i)
----

```

this expresses the test in a fewer number of lines.

File: pkg/util/duration/duration.go [hunk 2]
```diff
@@ -621,7 +621,7 @@ func (d Duration) DivFloat(x float64) Duration {
 	dayInt, dayFrac := math.Modf((float64(d.Days) / x) + (monthFrac * DaysPerMonth))
 
 	return MakeDuration(
-		int64((float64(d.nanos)/x)+(dayFrac*float64(nanosInDay))),
+		int64(float64((time.Duration(float64(d.nanos)/x) * time.Nanosecond).Truncate(time.Microsecond).Nanoseconds())+(dayFrac*float64(nanosInDay))),
```
Comment (otan) [inline pkg/util/duration/duration.go:624]: Can you pull out `(time.Duration(float64(d.nanos)/x) * time.Nanosecond).Truncate(time.Microsecond).Nanoseconds()` into a separate variable to make it easier to read, i.e.:

```
// We ensure we round down nanoseconds when doing division to
// match PostgreSQL.
retNanos := time.Duration(float64(d.nanos)/x).Truncate(time.Milliseconds)

return MakeDuration(
   ...,
  float64(retNanos.Nanoseconds()) + (dayFrac*float64(nanosInDay),
   ...,
)
```

**Review by otan — COMMENTED** [review]
thanks! couple of comments!

please also add a release note to your commit:

```
Release note (bug fix): Fixed a bug with PostgreSQL compatibility where
dividing an interval by a number would round to the nearest Microsecond
instead of always rounding down.
```

**Comment by TszKitLo40** [comment]
> thanks! couple of comments!
> 
> please also add a release note to your commit:
> 
> ```
> Release note (bug fix): Fixed a bug with PostgreSQL compatibility where
> dividing an interval by a number would round to the nearest Microsecond
> instead of always rounding down.
> ```

Can I just modify the PR description or need to modify the commit message?

**Review by otan — COMMENTED** [review]
both is good!

File: pkg/sql/logictest/testdata/logic_test/interval (hunk 1 above)
Comment (TszKitLo40) [reply pkg/sql/logictest/testdata/logic_test/interval:372]: Should the create table statement be needed?

**Review by otan — APPROVED** [review]
lgtm! thanks.

bors r+

File: pkg/util/duration/duration.go [hunk 3]
```diff
@@ -619,9 +619,12 @@ func (d Duration) MulFloat(x float64) Duration {
 func (d Duration) DivFloat(x float64) Duration {
 	monthInt, monthFrac := math.Modf(float64(d.Months) / x)
 	dayInt, dayFrac := math.Modf((float64(d.Days) / x) + (monthFrac * DaysPerMonth))
+	// We ensure we round down nanoseconds when doing division to
+	// match PostgreSQL.
+	retNanos := time.Duration(float64(d.nanos)/x).Truncate(time.Millisecond)
```
Comment (otan) [inline pkg/util/duration/duration.go:624]: oops, this should be `Truncate(time.Microsecond)`

**Review by otan — CHANGES_REQUESTED** [review]
Sorry, one of the test changes pointed out your fix is not sufficient!

File: pkg/sql/logictest/testdata/logic_test/datetime [hunk 4]
```diff
@@ -1523,7 +1523,7 @@ ORDER BY
 01:00:00               00:30:00          02:00:00                00:30:00          02:00:00                04:14:01.320914                 00:14:10.32
 1 day                  12:00:00          2 days                  12:00:00          2 days                  4 days 05:36:31.701948          05:40:07.68
 1 mon                  15 days           2 mons                  15 days           2 mons                  4 mons 7 days 00:15:51.058425   7 days 02:03:50.4
-1 mon 2 days 04:00:00  16 days 02:00:00  2 mons 4 days 08:00:00  16 days 02:00:00  2 mons 4 days 08:00:00  4 mons 15 days 28:24:59.745978  7 days 14:20:47.04
+1 mon 2 days 04:00:00  16 days 02:00:00  2 mons 4 days 08:00:00  16 days 02:00:00  2 mons 4 days 08:00:00  4 mons 15 days 28:24:59.745977  7 days 14:20:47.04
```
Comment (otan) [inline pkg/sql/logictest/testdata/logic_test/datetime:1526]: hmm, this does not match postgresql.

in particular, psql returns: 
```
otan=# select '1 month 2 days 4 hours'::INTERVAL / .2362;
            ?column?
--------------------------------
 4 mons 15 days 28:24:59.778753
(1 row)
```

I'm not sure what's broken, but do you mind taking a look while you're here? Here is the PostgreSQL implementation of integer division: https://github.com/postgres/postgres/blob/e56bce5d43789cce95d099554ae9593ada92b3b7/src/backend/utils/adt/timestamp.c#L3266-L3304

Comment (otan) [reply pkg/sql/logictest/testdata/logic_test/datetime:1526]: i feel like the answer is:

```
retNanos := time.Duration( int64(time.Duration(float64(d.nanos)).Microseconds()) / x) * time.Microsecond)
```

note the difference here -- we're dividing the microseconds by x, rather than the nanoseconds!

File: pkg/util/duration/duration.go [hunk 5]
```diff
@@ -617,16 +617,34 @@ func (d Duration) MulFloat(x float64) Duration {
...
 // DivFloat returns a Duration representing a time length of d/x.
 func (d Duration) DivFloat(x float64) Duration {
-	monthInt, monthFrac := math.Modf(float64(d.Months) / x)
-	dayInt, dayFrac := math.Modf((float64(d.Days) / x) + (monthFrac * DaysPerMonth))
+	// In order to keep it compatible with PostgreSQL, we use the same logic.
+	// Refer to https://github.com/postgres/postgres/blob/e56bce5d43789cce95d099554ae9593ada92b3b7/src/backend/utils/adt/timestamp.c#L3266-L3304.
+	month := int32(float64(d.Months) / x)
+	day := int32(float64(d.Days) / x)
+
+	monthRemainerDays := (float64(d.Months)/x - float64(month)) * DaysPerMonth
```
Comment (otan) [inline pkg/util/duration/duration.go:625]: nit: `remainderDays`

File: pkg/util/duration/duration.go [hunk 6]
```diff
@@ -617,16 +617,34 @@ func (d Duration) MulFloat(x float64) Duration {
...
+	monthRemainerDays = tsround(monthRemainerDays)
+	secRemainder := (float64(d.Days)/x - float64(day) +
+		monthRemainerDays - float64(int64(monthRemainerDays))) * SecsPerDay
+	secRemainder = tsround(secRemainder)
+	if math.Abs(secRemainder) >= SecsPerDay {
+		day += int32(secRemainder / SecsPerDay)
+		secRemainder -= float64(int32(secRemainder/SecsPerDay) * SecsPerDay)
+	}
+	day += int32(monthRemainerDays)
+	ret := time.Duration(int64(math.RoundToEven(float64(time.Duration(d.nanos).Microseconds())/x+secRemainder*MicrosPerMilli*MillisPerSec))) * time.Microsecond
```
Comment (otan) [inline pkg/util/duration/duration.go:635]: this is pretty hard to read, can we break it down?

```
secs := time.Duration(math.RoundToEven(float64(time.Duration(d.nanos).Microseconds()) / x) * time.Microsecond
secs += time.Duration(secRemainder * time.Second)
```

File: pkg/util/duration/duration.go [hunk 7]
```diff
@@ -617,16 +617,34 @@ func (d Duration) MulFloat(x float64) Duration {
...
-		int64((float64(d.nanos)/x)+(dayFrac*float64(nanosInDay))),
-		int64(dayInt),
-		int64(monthInt),
+		ret.Nanoseconds(),
+		int64(day),
+		int64(month),
 	)
 }
 
+func tsround(f float64) float64 {
```
Comment (otan) [inline pkg/util/duration/duration.go:644]: let's rename this to `secRoundToEven`:

```
// secRoundToEven rounds a given time to the nearest second.
func secRoundToEven(f float64) float64 {
  ....
}
```

this should be math.RoundToEven, right? since that's what we do for `rint`

File: pkg/sql/logictest/testdata/logic_test/interval [hunk 8]
```diff
@@ -367,3 +367,12 @@ subtest regression_62369
 
 query error "10000000000000000000000000000000000": value out of range
 SELECT INTERVAL '10000000000000000000000000000000000 year'
+
+query T
+SELECT i / 2 FROM ( VALUES
+  ('0 days 0.253000 seconds'::interval),
+  (INTERVAL '0.000001'::interval)
```
Comment (otan) [inline pkg/sql/logictest/testdata/logic_test/interval:374]: can you add cases for 0.000002 all the way up to 0.00001?

Comment (TszKitLo40) [reply pkg/sql/logictest/testdata/logic_test/interval:374]: do you mean the case like '0.000002'::interval?

Comment (otan) [reply pkg/sql/logictest/testdata/logic_test/interval:374]: yep!

File: pkg/util/duration/duration.go (hunk 6 above)
Comment (TszKitLo40) [reply pkg/util/duration/duration.go:635]: I think it should be break it down to``

File: pkg/sql/logictest/testdata/logic_test/interval [hunk 9]
```diff
@@ -367,3 +367,14 @@ subtest regression_62369
 
 query error "10000000000000000000000000000000000": value out of range
 SELECT INTERVAL '10000000000000000000000000000000000 year'
+
+query T
+SELECT i / 2 FROM ( VALUES
+  ('0 days 0.253000 seconds'::interval),
+  (INTERVAL '0.000001'::interval),
+  (INTERVAL '0.000002'::interval)
```
Comment (otan) [inline pkg/sql/logictest/testdata/logic_test/interval:375]: by all the way up to 0.00001, i meant 0.000003, 0.000004, 0.000005, etc as well!

File: pkg/util/duration/duration.go [hunk 10]
```diff
@@ -617,16 +617,35 @@ func (d Duration) MulFloat(x float64) Duration {
...
+	secRemainder := (float64(d.Days)/x - float64(day) +
+		remainderDays - float64(int64(remainderDays))) * SecsPerDay
+	secRemainder = secRoundToEven(secRemainder)
+	if math.Abs(secRemainder) >= SecsPerDay {
+		day += int32(secRemainder / SecsPerDay)
+		secRemainder -= float64(int32(secRemainder/SecsPerDay) * SecsPerDay)
+	}
+	day += int32(remainderDays)
+	microSecs := float64(time.Duration(d.nanos).Microseconds())/x + secRemainder*MicrosPerMilli*MillisPerSec
+	ret := time.Duration(int64(math.RoundToEven(microSecs))) * time.Microsecond
```
Comment (otan) [inline pkg/util/duration/duration.go:636]: nit: i don't think we should call this `ret`. it should be `secsDuration`, or something more descriptive. we are not returning `ret`

File: pkg/util/duration/duration.go [hunk 11]
```diff
@@ -617,16 +617,35 @@ func (d Duration) MulFloat(x float64) Duration {
...
-		int64((float64(d.nanos)/x)+(dayFrac*float64(nanosInDay))),
-		int64(dayInt),
-		int64(monthInt),
+		ret.Nanoseconds(),
+		int64(day),
+		int64(month),
 	)
 }
 
+func secRoundToEven(f float64) float64 {
```
Comment (otan) [inline pkg/util/duration/duration.go:645]: can you add a comment here:

```
// secRoundToEven rounds the given float to the nearest second,
// assuming the input float is a microsecond representation of
// time
// This maps to the TSROUND macro in Postgres.
```

**Review by otan — COMMENTED** [review]
sorry, should be the last bits to clean this up!

File: pkg/sql/logictest/testdata/logic_test/interval (hunk 9 above)
Comment (TszKitLo40) [reply pkg/sql/logictest/testdata/logic_test/interval:375]: from 0.000001 to 0.000009?

**Review by otan — APPROVED** [review]
awesome, thanks for persevering.

let's hope we're good this time...

bors r+
