### PR TITLE
roachprod, roachtest: use same cluster name sanitization

### LINKED ISSUE #122633: roachprod,roachtest: bug when choosing a username with invalid characters
When roachtest creates a cluster, it sanitizes the name to make sure the cluster name is a valid resource name in the clouds supported (see [1]). However, `roachprod`, on the other hand, also performs a validation that cluster names should be prefixed by the username that created them.

The consequence of this combined behaviour is that when a user passes a custom (and invalid) username either via `ROACHPROD_USER` or with the `--user` command line flag, the cluster will fail to be created:

<details>
<summary>Reproduction command</summary>

```console
$ roachtest run acceptance/version-upgrade --cockroach ./artifacts/cockroach --user renato.test
Locating and verifying binaries for os="linux", arch="amd64"
WARN: unable to find "cockroach-ea" for "amd64": binary or library "cockroach-ea" not found (or was not executable)

Found the following binaries:
        cockroach "amd64" at: /home/rc/go/src/github.com/cockroachdb/cockroach/artifacts/cockroach
        workload "amd64" at: /home/rc/go/src/github.com/cockroachdb/cockroach/bin/workload
        libraries "amd64" at: /home/rc/go/src/github.com/cockroachdb/cockroach/lib/libgeos.so, /home/rc/go/src/github.com/cockroachdb/cockroach/lib/libgeos_c.so
AMD64 clusters will be provisioned with probability 1.00

Running tests which match regex "acceptance/version-upgrade" and are compatible with cloud "gce".

HTTP server listening on port 39073 on all network interfaces: http://:39073/
16:04:11 run.go:357: test runner logs in: artifacts/_runner-logs/test_runner-1713456251.log
test runner logs in: artifacts/_runner-logs/test_runner-1713456251.log
16:04:11 run.go:151: global random seed: 3909152466501170706
16:04:11 test_runner.go:330: test_run_id: renato.test-1713456251
test_run_id: renato.test-1713456251
16:04:11 work_pool.go:204: [w0] Acquired quota for 16 CPUs
16:04:11 cluster.go:3011: [w0] Using randomly chosen arch="amd64", acceptance/version-upgrade
16:04:11 test_runner.go:482: [w0] Creating new cluster for test acceptance/version-upgrade: n4cpu4 (arch="amd64")
16:04:11 cluster.go:956: [w0] Attempting cluster creation (attempt #1/3)
16:04:11 cluster.go:975: [w0] cluster creation failed, cleaning up in case it was partially created: malformed cluster name renato-test-1713456251-01-n4cpu4, did you mean one of [renato.test-test-1713456251-01-n4cpu4]
16:04:11 cluster.go:1742: [w0] destroying cluster renato-test-1713456251-01-n4cpu4 [tag:] (4 nodes)...
16:04:19 cluster.go:1748: [w0] error destroying cluster renato-test-1713456251-01-n4cpu4 [tag:] (4 nodes): cluster renato-test-1713456251-01-n4cpu4 does not exist
16:04:19 cluster.go:956: [w0] Attempting cluster creation (attempt #2/3)
16:04:19 cluster.go:975: [w0] cluster creation failed, cleaning up in case it was partially created: malformed cluster name renato-test-1713456251-02-n4cpu4, did you mean one of [renato.test-test-1713456251-02-n4cpu4]
16:04:19 cluster.go:1742: [w0] destroying cluster renato-test-1713456251-02-n4cpu4 [tag:] (4 nodes)...
16:04:28 cluster.go:1748: [w0] error destroying cluster renato-test-1713456251-02-n4cpu4 [tag:] (4 nodes): cluster renato-test-1713456251-02-n4cpu4 does not exist
16:04:28 cluster.go:956: [w0] Attempting cluster creation (attempt #3/3)
16:04:28 cluster.go:975: [w0] cluster creation failed, cleaning up in case it was partially created: malformed cluster name renato-test-1713456251-03-n4cpu4, did you mean one of [renato.test-test-1713456251-03-n4cpu4]
16:04:28 cluster.go:1742: [w0] destroying cluster renato-test-1713456251-03-n4cpu4 [tag:] (4 nodes)...
16:04:36 cluster.go:1748: [w0] error destroying cluster renato-test-1713456251-03-n4cpu4 [tag:] (4 nodes): cluster renato-test-1713456251-03-n4cpu4 does not exist
16:04:36 test_runner.go:704: [w0] Unable to create (or reuse) cluster for test acceptance/version-upgrade due to: malformed cluster name renato-test-1713456251-03-n4cpu4, did you mean one of [renato.test-test-1713456251-03-n4cpu4].
Unable to create (or reuse) cluster for test acceptance/version-upgrade due to: malformed cluster name renato-test-1713456251-03-n4cpu4, did you mean one of [renato.test-test-1713456251-03-n4cpu4].
16:04:36 test_impl.go:414: test failure #1: full stack retained in failure_1.log: (test_runner.go:768).func4: malformed cluster name renato-test-1713456251-03-n4cpu4, did you mean one of [renato.test-test-1713456251-03-n4cpu4] [owner=test-eng]
16:04:36 github.go:300: skipping GitHub issue posting (GitHub API token not set)
16:04:36 test_runner.go:851: [w0] test failed: acceptance/version-upgrade (run 1)
16:04:36 test_runner.go:629: [w0] Releasing quota for 16 CPUs
16:04:36 test_runner.go:641: [w0] No work remaining; runWorker is bailing out...
No work remaining; runWorker is bailing out...
16:04:36 test_runner.go:549: [w0] Worker exiting; no cluster to destroy.
16:04:36 test_runner.go:382: PASS
PASS
16:04:36 test_runner.go:385: 1 clusters could not be created
1 clusters could not be created
16:04:36 run.go:185: runTests destroying all clusters
Error: some clusters could not be created
```
</details>

This issue encompasses the following improvements:

* Have a single place where names are sanitized. Roachprod and roachtest have their own functions doing essentially the same.
* Roachprod should verify that the cluster name has a prefix of the sanitized version of the username.
* Roachtest should not retry cluster creation if the reason for failure is a malformed name.

[1]
https://github.com/cockroachdb/cockroach/blob/46e5956a108f7f903fa40bd4e78b97a2c15fe7f1/pkg/cmd/roachtest/cluster.go#L534-L543

Jira issue: CRDB-38009

### PR DESCRIPTION
**Pull request by DarrylWong**
Previously, roachtest had it's own function to sanitize cluster names, while roachprod had it's own function to verify (but not sanitize) cluster names. This change removes both and opts instead to use vm.DNSSafeName.

This change also introduces MalformedClusterNameError which gives a hint on what is wrong with the name and
tells roachtest not to retry cluster creation.

Fixes: #122633
Epic: none
Release note: none

### CODE REVIEW

File: pkg/roachprod/vm/vm.go [hunk 1]
```diff
@@ -710,21 +710,31 @@ func ExpandZonesFlag(zoneFlag []string) (zones []string, err error) {
...
+// DNSSafeName takes a string and returns a cleaned version of the string that can be used in DNS entries.
 // Unsafe characters are dropped. No length check is performed.
-func DNSSafeAccount(account string) string {
+func DNSSafeName(name string) string {
 	safe := func(r rune) rune {
 		switch {
 		case r >= 'a' && r <= 'z':
 			return r
 		case r >= 'A' && r <= 'Z':
 			return unicode.ToLower(r)
```
Comment (srosenberg) [inline pkg/roachprod/vm/vm.go:721]: Nice! This is indeed more efficient than `strings.ToLower` when it's known that the char sequence is ascii. It's essentially inlined to this `r += 'a' - 'A'`.

File: pkg/roachprod/roachprod.go [hunk 2]
```diff
@@ -118,26 +130,28 @@ func verifyClusterName(l *logger.Logger, clusterName, username string) error {
...
 	}
 
 	// Suggest acceptable cluster names.
 	var suggestions []string
 	for _, account := range accounts {
 		suggestions = append(suggestions, fmt.Sprintf("%s-%s", account, suffix))
 	}
-	return fmt.Errorf("malformed cluster name %s, did you mean one of %s",
-		clusterName, suggestions)
+	return &MalformedClusterNameError{name: clusterName, reason: reason, suggestions: suggestions}
```
Comment (srosenberg) [inline pkg/roachprod/roachprod.go:154]: Let's add a unit test for `verifyClusterName`.

File: pkg/cmd/roachtest/cluster.go [hunk 3]
```diff
@@ -973,6 +966,9 @@ func (f *clusterFactory) newCluster(
 			// or a destroy from the previous iteration failed.
 			return nil, nil, err
 		}
+		if errors.HasType(err, (*roachprod.MalformedClusterNameError)(nil)) {
```
Comment (srosenberg) [inline pkg/cmd/roachtest/cluster.go:969]: Let's add a unit test to cover this case.

**Review by srosenberg — APPROVED** [review]
Could use a couple of new unit tests (for `verifyClusterName` and `newCluster`), otherwise looks great!

File: pkg/roachprod/roachprod.go [hunk 4]
```diff
@@ -66,6 +66,21 @@ const (
...
+	suggestions []string
+}
+
+func (e *MalformedClusterNameError) Error() string {
+	return fmt.Sprintf("Malformed cluster name %s, %s. Did you mean one of %s", e.name, e.reason, e.suggestions)
+}
+
+// _findActiveAccounts is a test only variable, used for mocking a provider finding
+// active accounts in a unit test, where we don't want to actually access a provider.
+var _findActiveAccounts func(l *logger.Logger) (map[string]string, error)
```
Comment (DarrylWong) [inline pkg/roachprod/roachprod.go:82]: Is it okay to do this for a package variable? I couldn't think of an easier way to mock `vm.FindActiveAccounts`. AFAICT, the tests in a package are run sequentially, so no concurrency in accessing this.

File: pkg/roachprod/roachprod.go (hunk 2 above)
Comment (DarrylWong) [reply pkg/roachprod/roachprod.go:166]: Done, although I have a question about the validity of my approach.

File: pkg/cmd/roachtest/cluster.go (hunk 3 above)
Comment (DarrylWong) [reply pkg/cmd/roachtest/cluster.go:969]: I gave it a shot, but I wasn't sure how to feasibly do this without mocking a ton of things. There already is a way to mock cluster creation via `TestSpec` + `r.MakeClusterSpec(0)`, but that skips `roachprod.Create` and this entire retry loop where we validate the cluster name.

I could mock `roachprod.Create` to just return a `MalformedclusterNameError`, but I don't think that test would be very useful.

File: pkg/roachprod/roachprod.go (hunk 4 above)
Comment (srosenberg) [reply pkg/roachprod/roachprod.go:82]: Yep, this is a totally legit. way of mocking which is also used sometimes for dependency injection. E.g., `InitTestConnectorFactory` [1] is used to inject (or mock) a test-specific implementation of the KV connector.

However, we could initialize it with the _actual_ implementation, i.e.,

```
var _findActiveAccounts = vm.FindActiveAccounts
```

and get rid of the conditional logic below.

[1] https://github.com/cockroachdb/cockroach/blob/6ec873aa0fc35a968e8daf3abd23ba895e4512fc/pkg/kv/kvclient/kvtenant/test_utils.go#L16

File: pkg/roachprod/roachprod.go [hunk 5]
```diff
@@ -90,17 +102,29 @@ func verifyClusterName(l *logger.Logger, clusterName, username string) error {
...
+		if cleanAccount != username {
+			l.Printf("WARN: using `%s' as username instead of `%s'", cleanAccount, username)
+		}
+		accounts = []string{cleanAccount}
 	} else {
 		seenAccounts := map[string]bool{}
-		active, err := vm.FindActiveAccounts(l)
+		var active map[string]string
+		var err error
+		if _findActiveAccounts != nil {
```
Comment (srosenberg) [inline pkg/roachprod/roachprod.go:114]: Can elide this check and just use `active, err = _findActiveAccounts(l)` as per above comment.

**Comment by srosenberg** [comment]
I am guessing `check_generated_code` failed because you forgot to run,

```
./dev generate bazel
```

which creates the missing `roachprod_test` package,

```
--- a/pkg/roachprod/BUILD.bazel
+++ b/pkg/roachprod/BUILD.bazel
@@ -1,4 +1,4 @@
-load("@io_bazel_rules_go//go:def.bzl", "go_library")
+load("@io_bazel_rules_go//go:def.bzl", "go_library", "go_test")

 go_library(
     name = "roachprod",
@@ -38,3 +38,13 @@ go_library(
         "@org_golang_x_sys//unix",
     ],
 )
+
+go_test(
+    name = "roachprod_test",
+    srcs = ["roachprod_test.go"],
+    embed = [":roachprod"],
+    deps = [
+        "//pkg/roachprod/logger",
+        "@com_github_stretchr_testify//assert",
+    ],
+)
```

File: pkg/cmd/roachtest/cluster.go (hunk 3 above)
Comment (srosenberg) [reply pkg/cmd/roachtest/cluster.go:969]: > I could mock roachprod.Create to just return a MalformedclusterNameError, but I don't think that test would be very useful.

That would have been my suggestion as well. I think it would be useful to unit test `roachprod.Create` especially in the context of [1]; i.e., `ClusterAlreadyExistsError`, `MalformedClusterNameError` and potentially future type of errors are non-retryable, so we should be able to cover the fact via a unit test. For now, the mock could randomly return the two non-retryable errors, and we assert that the mock is invoked exactly once, i.e., no retries. Wdyt?

[1] https://github.com/cockroachdb/cockroach/issues/114523

Comment (DarrylWong) [reply pkg/cmd/roachtest/cluster.go:973]: Done. I was trying to add a case where it _didn't_ error out and that was quite tricky to do without mocking a bunch of things. Mocking the two non-retryable errors cases was simple though.

File: pkg/roachprod/roachprod.go (hunk 4 above)
Comment (DarrylWong) [reply pkg/roachprod/roachprod.go]: Done! Thanks for tip

**Review by srosenberg — APPROVED** [review]
LGTM. Thanks for adding the unit tests!

**Comment by DarrylWong** [comment]
TFTR!

bors r=srosenberg

**Comment by DarrylWong** [comment]
🥺 

bors retry
