### PR TITLE
changefeedccl: Rely on optimizer and distSQL when evaluating CDC expressions.

### LINKED ISSUE #90416: cdc: expressions with exist clauses cause a panic
**Describe the problem**
```sql
CREATE CHANGEFEED WITH schema_change_policy='stop' AS SELECT 1 FROM foo WHERE EXISTS (SELECT true);
```

Kills the cockroach. Tested on release-22.2 branch.

Jira issue: CRDB-20757

### LINKED ISSUE #90455: cdc: cdceval type resolution has trouble with nullable columns
```
root@localhost:26257/defaultdb> select s, s || s from manystrings limit 3;
    s   |  ?column?
--------+-------------
        |
  NULL  | NULL
  hello | hellohello
(3 rows)


Time: 1ms total (execution 1ms / network 0ms)

root@localhost:26257/defaultdb> create changefeed with schema_change_policy='stop' as select s || s from manystrings;
{"key":"[807033528558616577]","table":"manystrings","value":"{\"column_1\": \"\"}"}
(error encountered after some results were delivered)
ERROR: while evaluating projection: SELECT s || s FROM [122 AS manystrings]: ambiguous binary operator: <unknown> || <unknown>
```

Jira issue: CRDB-20778

Epic CRDB-17161

### LINKED ISSUE #90714: cdc: cannot use UDT cast in changefeed expression
When you create a changefeed expression which references UDTs, some weird behavior occurs:
```
CREATE TYPE status AS ENUM ('inactive', 'active');

CREATE TYPE priority AS ENUM ('high', 'low');

CREATE TABLE foo (
    a INT PRIMARY KEY,
    b status,
    c priority,
    FAMILY only_b (b),
    FAMILY only_c (c)
);      


root@localhost:26257/defaultdb> CREATE CHANGEFEED WITH split_column_families AS SELECT 'inactive'::status, c FROM foo;
ERROR: undefined object with OID 100113
SQLSTATE: 42704
```

Also this:
```
root@localhost:26257/defaultdb> CREATE CHANGEFEED WITH split_column_families, schema_change_policy='stop'  AS SELECT 'inactive'::status from foo;
ERROR: expressions can't reference columns from more than one column family
SQLSTATE: 22023
```

Neither of these errors should happen since the changefeed expressions are valid.

Jira issue: CRDB-20905

Epic CRDB-17161

### PR DESCRIPTION
**Pull request by miretskiy**
Previous PRs (#82562) introduced CDC expressions.

This PR builds on that and replaces majority of hand written
evaluation logic in favor of tighter integration with
optimizer and dist SQL processors.

CDC expression, which is really a simplified `SELECT` statement,
is now  planned by the optimizer `sql.PlanCDCExpression`.
The resulting plan is then fed to the distSQL, to produce
a specialized CDC execution plan (`sql.RunCDCEvaluation`).

The execution plan is special in that it is guaranteed to be
a local execution plan, and changefeed is expected to "feed"
the data (encoded row) directly into the execution pipeline,
with change aggregators consuming resulting projection.

The benefit of this approach is that expression optimization,
and evaluation is now handled by optimizer and distSQL.
The responsibility of CDC evaluation package is to make sure
that CDC expression is "sane" and to setup CDC specific functions.

Since the whole expression is not yet fully planned
by distSQL (i.e. we don't have changefeed operator implemented yet),
the integration between CDC expressions and optimizer/execInfra
is not yet complete.  In particular, this
PR does not replace current distSQL execution for CDC --
namely, we still keep the same execution model using hand planned
`ChangeFrontierProcessor` and `ChangeAggretagorProcessor`.
It augments existing model, while tightening the integration.

Still, this is an improvement over previous state.  The follow on work
will complete integration.

Some changes enabled by this implementation include the replacement
of `cdc_prev()` function which returned JSONb representation of the
previous row, with a `cdc_prev` tuple.  This makes changefeed
expressions more natural since tuples are strongly typed:

```
SELECT * FROM tbl WHERE col != cdc_prev.col`
```

In addition, by using tuple to represent the state of the previous row,
we can now leverage existing SQL functions.  For example, to emit
previus row as JSONb we can do:

```
SELECT *, row_to_json(cdc_prev.*) AS prevJson FROM tbl
```

Fixes #90416
Fixes #90714
Fixes #90455
Informs #90442
Informs CRDB-18978
Informs CRDB-17161

Release note (enterprise change): CDC expressions are now planned and
evaluated using SQL optimizer and distSQL execution. The state
of the previous row is now exposed as `cdc_prev` tuple.

Release note (backward incompatible change): The replacement of
cdc_prev() function in favor a cdc_prev tuple is an incompatible
change that may break changefeeds that use old cdc_prev() function.

### CODE REVIEW

**Review by yuzefovich — COMMENTED** [review]
Didn't finish reading through the last commit, but pushing what I have so far. Cool stuff!

> Reviewed 14 of 14 files at r1, 3 of 13 files at r2, 48 of 48 files at r4, 13 of 13 files at r5, 13 of 40 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/85177#-:-NH23TKt26DlKDuWbhoq:b-k1kq86)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @DrewKimball, @HonoreDB, @miretskiy, and @rytaft)

___
*[`-- commits` line 12 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/85177#-NH1Pgob06CpJnYHLnGq):*
nit: leftover in the commit message.
___
*[`-- commits` line 31 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/85177#-NH1j-UhD7HG3zIgid1k):*
nit: `s/notes/note/`.
___
*[`pkg/ccl/changefeedccl/changefeed_dist.go` line 178 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/85177#-NH1pq7k2dnjACpSl_bK:-NH1pq7k2dnjACpSl_bL:b-vf13fi) ([raw file](https://github.com/cockroachdb/cockroach/blob/4f20450e82be3d5d497dae4ad259ff78c41eb732/pkg/ccl/changefeedccl/changefeed_dist.go#L178)):*
> ```Go
> // Usually, this is just the primary index span.
> // However, if details.Select is not empty, the set of spans returned may be
> // restricted to satisfy predicate in the select clause.  In that case,
> ```

nit: I think the last sentence is no longer applicable.
___
*[`pkg/ccl/changefeedccl/changefeed_dist.go` line 249 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/85177#-NH1q5Gi1SYdZSeowdJx:-NH1q5Gi1SYdZSeowdJy:b-7yrehi) ([raw file](https://github.com/cockroachdb/cockroach/blob/4f20450e82be3d5d497dae4ad259ff78c41eb732/pkg/ccl/changefeedccl/changefeed_dist.go#L249)):*
> ```Go
> 
> 	if schemaTS.IsEmpty() {
> 		schemaTS = details.StatementTime
> ```

Is it guaranteed that `details.StatementTime` is set?
___
*[`pkg/ccl/changefeedccl/changefeed_stmt.go` line 887 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/85177#-NH1qV_rDgvC3FJlzLed:-NH1qV_rDgvC3FJlzLee:b2wfx7y) ([raw file](https://github.com/cockroachdb/cockroach/blob/4f20450e82be3d5d497dae4ad259ff78c41eb732/pkg/ccl/changefeedccl/changefeed_stmt.go#L887)):*
> ```Go
> 	statementTime hlc.Timestamp,
> ) (*cdceval.NormalizedSelectClause, error) {
> 	// TODO -- DO NOT MERGE -- figure out includeVirtual/keyOnly business.
> ```

nit: just pointing this out.
___
*[`pkg/ccl/changefeedccl/event_processing.go` line 293 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/85177#-NH1qqI7-AfjhPMyjbzQ:-NH1qqI7-AfjhPMyjbzR:bd0rep2) ([raw file](https://github.com/cockroachdb/cockroach/blob/4f20450e82be3d5d497dae4ad259ff78c41eb732/pkg/ccl/changefeedccl/event_processing.go#L293)):*
> ```Go
> 		// it would be superfluous to also encode prevRow.
> 		updatedRow, prevRow = projection, cdcevent.Row{}
> 		log.Infof(ctx, "DBG: Got Row: %s", updatedRow.DebugString())
> ```

nit: this probably needs an adjustment.
___
*[`pkg/ccl/changefeedccl/event_processing.go` line 376 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/85177#-NH1r5nK3NdSFoGpWsGu:-NH1r5nK3NdSFoGpWsGv:bbx0hq4) ([raw file](https://github.com/cockroachdb/cockroach/blob/4f20450e82be3d5d497dae4ad259ff78c41eb732/pkg/ccl/changefeedccl/event_processing.go#L376)):*
> ```Go
> }
> 
> // Close is a noop for the kvEventToRowConsumer because it
> ```

nit: the comment is no longer true.
___
*[`pkg/ccl/changefeedccl/cdceval/doc.go` line 31 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/85177#-NH1rsMt7oRyldHrbhju:-NH1rsMt7oRyldHrbhjv:boaiol1) ([raw file](https://github.com/cockroachdb/cockroach/blob/4f20450e82be3d5d497dae4ad259ff78c41eb732/pkg/ccl/changefeedccl/cdceval/doc.go#L31)):*
> ```Go
> 
> Then, once aggregators start up, they will once again plan the expression
> (sql.PlanCDCExpression), but this time each incoming KV event will be evaluated
> ```

nit: I think something is missing after "will be evaluated".
___
*[`pkg/ccl/changefeedccl/cdceval/expr_eval.go` line 46 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/85177#-NH1sQ_4D1UixLBBqyWG:-NH1sQ_4D1UixLBBqyWH:bgxdl6h) ([raw file](https://github.com/cockroachdb/cockroach/blob/4f20450e82be3d5d497dae4ad259ff78c41eb732/pkg/ccl/changefeedccl/cdceval/expr_eval.go#L46)):*
> ```Go
> 	fnResolver CDCFunctionResolver
> 
> 	// rowCh receives projection datums (or nil if filtered out)
> ```

nit: missing period.
___
*[`pkg/ccl/changefeedccl/cdceval/expr_eval.go` line 123 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/85177#-NH1suzO6xSduDwBTK6q:-NH1suzO6xSduDwBTK6r:b-pbn6kn) ([raw file](https://github.com/cockroachdb/cockroach/blob/4f20450e82be3d5d497dae4ad259ff78c41eb732/pkg/ccl/changefeedccl/cdceval/expr_eval.go#L123)):*
> ```Go
> 			return cdcevent.Row{}, nil
> 		}
> 		row = row[1:]
> ```

nit: add a quick comment to say that we need to remove the temporary boolean value to not be emitted to the client.
___
*[`pkg/ccl/changefeedccl/cdceval/expr_eval.go` line 138 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/85177#-NH1t5OM0A6Nyg9WQ5Zt:-NH1t5OM0A6Nyg9WQ5Zu:b8zaf8l) ([raw file](https://github.com/cockroachdb/cockroach/blob/4f20450e82be3d5d497dae4ad259ff78c41eb732/pkg/ccl/changefeedccl/cdceval/expr_eval.go#L138)):*
> ```Go
> }
> 
> // sameVersion returns true row descriptor versions match this evaluator versions.
> ```

nit: `s/true row/true if row/`.

nit: maybe worth mentioning that we don't care whether current and previous versions match between each other.
___
*[`pkg/ccl/changefeedccl/cdceval/expr_eval.go` line 167 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/85177#-NH1u93vEKGJTot7Ma2i:-NH1u93vEKGJTot7Ma2j:bnefvjz) ([raw file](https://github.com/cockroachdb/cockroach/blob/4f20450e82be3d5d497dae4ad259ff78c41eb732/pkg/ccl/changefeedccl/cdceval/expr_eval.go#L167)):*
> ```Go
> func (e *Evaluator) preparePlan(ctx context.Context, plan *sql.CDCExpressionPlan) error {
> 	return plannerExec(
> 		ctx, e.execCfg, e.user, e.currDesc.SchemaTS, sessiondatapb.SessionData{},
> ```

Something that we might want to try is to disable the usage of the vectorized engine since it would still effectively "degrade" to row-at-a-time model due to `MustBeStreaming` returning `true`. I'm not sure whether we'd see better performance or better allocations profile, but it might be worthy of a TODO to check.

Update: saw that we disable it in `plannerExec`.
___
*[`pkg/ccl/changefeedccl/cdceval/expr_eval.go` line 253 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/85177#-NH1wA4O-P8tvQCps5E2:-NH1wA4O-P8tvQCps5E3:bksa8go) ([raw file](https://github.com/cockroachdb/cockroach/blob/4f20450e82be3d5d497dae4ad259ff78c41eb732/pkg/ccl/changefeedccl/cdceval/expr_eval.go#L253)):*
> ```Go
> 	input.InitWithNumSenders(inputTypes, 1)
> 
> 	// write sends result of the evaluation into row channel.
> ```

nit: `s/write/writer/`.
___
*[`pkg/ccl/changefeedccl/cdceval/plan.go` line 91 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/85177#-NH20-TX9vR7NYa8wXkz:-NH20-TX9vR7NYa8wXl-:byzu74o) ([raw file](https://github.com/cockroachdb/cockroach/blob/4f20450e82be3d5d497dae4ad259ff78c41eb732/pkg/ccl/changefeedccl/cdceval/plan.go#L91)):*
> ```Go
> 			case pgcode.UndefinedColumn:
> 				return errors.WithHintf(err,
> 					"column nay not exist in the target column family %q", target.FamilyName)
> ```

nit: `s/nay/may/`.

nit: should we add this hint only if the table has multiple column families? Is that information easily available here?
___
*[`pkg/ccl/changefeedccl/cdceval/plan.go` line 170 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/85177#-NH21FY59TGszaIj4M_z:-NH21FY59TGszaIj4Ma-:b-o9njvo) ([raw file](https://github.com/cockroachdb/cockroach/blob/4f20450e82be3d5d497dae4ad259ff78c41eb732/pkg/ccl/changefeedccl/cdceval/plan.go#L170)):*
> ```Go
> 	}
> 
> 	scopedTable := &tree.SelectClause{
> ```

nit: maybe add an example in the comment here?
___
*[`pkg/ccl/changefeedccl/cdceval/plan.go` line 199 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/85177#-NH21NSXEzXY2jlB6H5d:-NH21NSXEzXY2jlB6H5e:b-z5wyv7) ([raw file](https://github.com/cockroachdb/cockroach/blob/4f20450e82be3d5d497dae4ad259ff78c41eb732/pkg/ccl/changefeedccl/cdceval/plan.go#L199)):*
> ```Go
> 
> // plannerExec is a helper which invokes provided function inside
> // a DescTxn transaction to ensure that descriptors get acquired
> ```

nit: `s/DescTxn/sql.DescsTxn/`.
___
*[`pkg/ccl/changefeedccl/cdceval/plan.go` line 215 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/85177#-NH21TLoDr2Q5c_qkD-o:-NH21TLoDr2Q5c_qkD-p:b-gt8r9u) ([raw file](https://github.com/cockroachdb/cockroach/blob/4f20450e82be3d5d497dae4ad259ff78c41eb732/pkg/ccl/changefeedccl/cdceval/plan.go#L215)):*
> ```Go
> 			}
> 
> 			sd.VectorizeMode = sessiondatapb.VectorizeOff
> ```

Interesting, so we do disable the vectorized engine. Maybe add a comment for why.
___
*[`pkg/sql/distsql_plan_changefeed.go` line 146 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/85177#-NH1jJaeAFC71x1hJPE1:-NH1jJaeAFC71x1hJPE2:b-wvt7by) ([raw file](https://github.com/cockroachdb/cockroach/blob/0522b1e1839c98c7fb8a37376e16bde418d7fdc1/pkg/sql/distsql_plan_changefeed.go#L146)):*
> ```Go
> 
> 	planCtx := p.DistSQLPlanner().NewPlanningCtx(ctx, &p.extendedEvalCtx, p, p.txn, DistributionTypeNone)
> 	planCtx.isLocal = true
> ```

nit: this isn't strictly needed with `DistributionTypeNone`.
___
*[`pkg/sql/distsql_plan_changefeed.go` line 149 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/85177#-NH1jLaX2hfdDcIS5Zll:-NH1jLaX2hfdDcIS5Zlm:buzf8p7) ([raw file](https://github.com/cockroachdb/cockroach/blob/0522b1e1839c98c7fb8a37376e16bde418d7fdc1/pkg/sql/distsql_plan_changefeed.go#L149)):*
> ```Go
> 
> 	return CDCExpressionPlan{
> 		Plan:         p.curPlan.main,
> ```

We don't expect to see subqueries, right? It would probably be good to add assertions that all slices in `p.curPlan` are zero-lengths (i.e. no subqueries, cascades, nor checks).
___
*[`pkg/sql/distsql_plan_changefeed.go` line 208 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/85177#-NH1jONx8HsCtjSlZzc8:-NH1jONx8HsCtjSlZzc9:bdiusg) ([raw file](https://github.com/cockroachdb/cockroach/blob/0522b1e1839c98c7fb8a37376e16bde418d7fdc1/pkg/sql/distsql_plan_changefeed.go#L208)):*
> ```Go
> 
> // cdcValuesNode replaces regular scanNode with cdc specific implementation
> // which returns values from the execinfra.RowSource.
> ```

nit: maybe expand on what the input `RowSource` is producing. IIRC it would be a source that never ends, right?
___
*[`pkg/sql/distsql_plan_changefeed.go` line 273 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/85177#-NH1kxi28jyv0mx0UgoX:-NH1kxi28jyv0mx0UgoY:b-vhqn2u) ([raw file](https://github.com/cockroachdb/cockroach/blob/0522b1e1839c98c7fb8a37376e16bde418d7fdc1/pkg/sql/distsql_plan_changefeed.go#L273)):*
> ```Go
> // Close implements planNode.
> func (n *cdcValuesNode) Close(ctx context.Context) {
> }
> ```

nit: the contract of `RowSource` says that unless we call `Next` until `Next` returns `nil, nil`, we must call `ConsumerDone`. I think it'd be cleaner to just do it here even if this might not be strictly necessary.
___
*[`pkg/sql/distsql_plan_changefeed.go` line 295 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/85177#-NH1lYct34sEcfHM9fHK:-NH1lYct34sEcfHM9fHL:byb0grk) ([raw file](https://github.com/cockroachdb/cockroach/blob/0522b1e1839c98c7fb8a37376e16bde418d7fdc1/pkg/sql/distsql_plan_changefeed.go#L295)):*
> ```Go
> 	ds, err := c.newCDCDataSource(desc)
> 	if err != nil {
> 		return nil, *name, err
> ```

nit: maybe `s/*name/cat.DataSourceName{}/`?
___
*[`pkg/sql/distsql_plan_changefeed.go` line 326 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/85177#-NH1lneB5QStesDQhorU:-NH1lneB5QStesDQhorV:ba4k3bs) ([raw file](https://github.com/cockroachdb/cockroach/blob/0522b1e1839c98c7fb8a37376e16bde418d7fdc1/pkg/sql/distsql_plan_changefeed.go#L326)):*
> ```Go
> 	desc.Indexes = desc.Indexes[:0]
> 	updated := tabledesc.NewBuilder(desc).BuildImmutableTable()
> 	return newOptTable(updated, c.codec(), nil, emptyZoneConfig)
> ```

nit: add an inline comment about what `nil` is.
___
*[`pkg/sql/plan_node_to_row_source.go` line 94 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/85177#-NH1k5E_ClnHq_eitzyb:-NH1k5E_ClnHq_eitzyc:b-jajh4o) ([raw file](https://github.com/cockroachdb/cockroach/blob/0522b1e1839c98c7fb8a37376e16bde418d7fdc1/pkg/sql/plan_node_to_row_source.go#L94)):*
> ```Go
> 	switch p.node.(type) {
> 	case *hookFnNode, *cdcValuesNode:
> 		// hookFnNode is special because it might be blocked forever if we decide to
> ```

nit: say something about `cdcValuesNode` too.
___
*[`pkg/sql/walk.go` line 479 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/85177#-NH1kGp6EBfCgUrF2tQU:-NH1kGp6EBfCgUrF2tQV:b-fdxhze) ([raw file](https://github.com/cockroachdb/cockroach/blob/0522b1e1839c98c7fb8a37376e16bde418d7fdc1/pkg/sql/walk.go#L479)):*
> ```Go
> 	reflect.TypeOf(&zigzagJoinNode{}):                          "zigzag join",
> 	reflect.TypeOf(&schemaChangePlanNode{}):                    "schema change",
> 	reflect.TypeOf(&cdcValuesNode{}):                           "wrapped streaming node",
> ```

nit: let's keep it sorted since it looks like it is already sorted except for the last two lines.
___
*[`pkg/sql/opt/exec/execbuilder/scalar.go` line 727 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/85177#-NH1kXpu0-TyU7Hht16P:-NH1kXpu0-TyU7Hht16Q:b-57hjcs) ([raw file](https://github.com/cockroachdb/cockroach/blob/0522b1e1839c98c7fb8a37376e16bde418d7fdc1/pkg/sql/opt/exec/execbuilder/scalar.go#L727)):*
> ```Go
> 		ef := ref.(exec.Factory)
> 		eb := New(ctx, ef, &o, f.Memo(), b.catalog, newRightSide,
> 			b.evalCtx, b.semaCtx, false /* allowAutoCommit */, b.IsANSIDML)
> ```

Should this change be in the first commit.
___
*[`pkg/sql/distsql_plan_changefeed_test.go` line 93 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/85177#-NH1mgyJDs4Dv2KAWOZ6:-NH1mgyK8SCcNv0pwoCg:box8681) ([raw file](https://github.com/cockroachdb/cockroach/blob/0522b1e1839c98c7fb8a37376e16bde418d7fdc1/pkg/sql/distsql_plan_changefeed_test.go#L93)):*
> ```Go
> 	}
> 
> 	for _, tc := range []struct {
> ```

Nice tests! I think we're missing some cases where multiple different tables are used by the query, right? It'd be good to add a case with two tables when both are existing as well as when one is not found. Or this checked elsewhere?
___
*[`pkg/sql/opt/lookupjoin/constraint_builder_test.go` line 324 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/85177#-NH1PtqZ2Vd73oivObqu:-NH1PtqZ2Vd73oivObqv:bg465pa) ([raw file](https://github.com/cockroachdb/cockroach/blob/427892a7831af1f4e2f60c4b39e518c256715a8b/pkg/sql/opt/lookupjoin/constraint_builder_test.go#L324)):*
> ```Go
> 	execBld := execbuilder.New(
> 		context.Background(), nil /* execFactory */, nil /* optimizer */, f.Memo(), nil, /* catalog */
> 		e, evalCtx, nil /*semaCtx */, false, /* allowAutoCommit */
> ```

nit: add a space before `semaCtx`.

**Review by miretskiy — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/85177)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @DrewKimball, @HonoreDB, @rytaft, and @yuzefovich)

___
*[`pkg/ccl/changefeedccl/changefeed_dist.go` line 249 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/85177#-NH1q5Gi1SYdZSeowdJx:-NH52adn3YS9akMiBhx3:b-yw2clk) ([raw file](https://github.com/cockroachdb/cockroach/blob/4f20450e82be3d5d497dae4ad259ff78c41eb732/pkg/ccl/changefeedccl/changefeed_dist.go#L249)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

Is it guaranteed that `details.StatementTime` is set?
</blockquote></details>

Yes; always.
___
*[`pkg/ccl/changefeedccl/changefeed_stmt.go` line 887 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/85177#-NH1qV_rDgvC3FJlzLed:-NH53K5zC0CDTlJ3KGIK:b-ucfkn4) ([raw file](https://github.com/cockroachdb/cockroach/blob/4f20450e82be3d5d497dae4ad259ff78c41eb732/pkg/ccl/changefeedccl/changefeed_stmt.go#L887)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

nit: just pointing this out.
</blockquote></details>

Thanks.
___
*[`pkg/ccl/changefeedccl/event_processing.go` line 293 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/85177#-NH1qqI7-AfjhPMyjbzQ:-NH53LTz-vWMw6ci4d7V:bse48gv) ([raw file](https://github.com/cockroachdb/cockroach/blob/4f20450e82be3d5d497dae4ad259ff78c41eb732/pkg/ccl/changefeedccl/event_processing.go#L293)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

nit: this probably needs an adjustment.
</blockquote></details>

left over.  Thanks.
___
*[`pkg/ccl/changefeedccl/cdceval/expr_eval.go` line 167 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/85177#-NH1u93vEKGJTot7Ma2i:-NH54_dr6edtEA2UK1Tr:bb6sh2i) ([raw file](https://github.com/cockroachdb/cockroach/blob/4f20450e82be3d5d497dae4ad259ff78c41eb732/pkg/ccl/changefeedccl/cdceval/expr_eval.go#L167)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

Something that we might want to try is to disable the usage of the vectorized engine since it would still effectively "degrade" to row-at-a-time model due to `MustBeStreaming` returning `true`. I'm not sure whether we'd see better performance or better allocations profile, but it might be worthy of a TODO to check.

Update: saw that we disable it in `plannerExec`.
</blockquote></details>

Ack.
___
*[`pkg/ccl/changefeedccl/cdceval/plan.go` line 91 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/85177#-NH20-TX9vR7NYa8wXkz:-NH54oy69WIzKsc3heeW:bvfnicg) ([raw file](https://github.com/cockroachdb/cockroach/blob/4f20450e82be3d5d497dae4ad259ff78c41eb732/pkg/ccl/changefeedccl/cdceval/plan.go#L91)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

nit: `s/nay/may/`.

nit: should we add this hint only if the table has multiple column families? Is that information easily available here?
</blockquote></details>

Done; good idea.
___
*[`pkg/ccl/changefeedccl/cdceval/plan.go` line 215 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/85177#-NH21TLoDr2Q5c_qkD-o:-NH4dM2VD-wetVH1G5An:baumysc) ([raw file](https://github.com/cockroachdb/cockroach/blob/4f20450e82be3d5d497dae4ad259ff78c41eb732/pkg/ccl/changefeedccl/cdceval/plan.go#L215)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

Interesting, so we do disable the vectorized engine. Maybe add a comment for why.
</blockquote></details>

We are definitely a row-by-row execution mode now.  Added comment.
___
*[`pkg/sql/distsql_plan_changefeed.go` line 146 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/85177#-NH1jJaeAFC71x1hJPE1:-NH4dpYR9a6VDHED3nPa:brpmqc3) ([raw file](https://github.com/cockroachdb/cockroach/blob/0522b1e1839c98c7fb8a37376e16bde418d7fdc1/pkg/sql/distsql_plan_changefeed.go#L146)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

nit: this isn't strictly needed with `DistributionTypeNone`.
</blockquote></details>

removed.
___
*[`pkg/sql/distsql_plan_changefeed.go` line 149 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/85177#-NH1jLaX2hfdDcIS5Zll:-NH4drcZ1lCLppUjXcNN:b-sowv30) ([raw file](https://github.com/cockroachdb/cockroach/blob/0522b1e1839c98c7fb8a37376e16bde418d7fdc1/pkg/sql/distsql_plan_changefeed.go#L149)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

We don't expect to see subqueries, right? It would probably be good to add assertions that all slices in `p.curPlan` are zero-lengths (i.e. no subqueries, cascades, nor checks).
</blockquote></details>

Ack.  Good idea re extra checks.  Added.
___
*[`pkg/sql/distsql_plan_changefeed.go` line 208 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/85177#-NH1jONx8HsCtjSlZzc8:-NH4eUxR5DcAzkRpXgES:bpwd2tz) ([raw file](https://github.com/cockroachdb/cockroach/blob/0522b1e1839c98c7fb8a37376e16bde418d7fdc1/pkg/sql/distsql_plan_changefeed.go#L208)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

nit: maybe expand on what the input `RowSource` is producing. IIRC it would be a source that never ends, right?
</blockquote></details>

Correct.  Added
___
*[`pkg/sql/walk.go` line 479 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/85177#-NH1kGp6EBfCgUrF2tQU:-NH4fKfXEinzErqfsHgv:bs7wumb) ([raw file](https://github.com/cockroachdb/cockroach/blob/0522b1e1839c98c7fb8a37376e16bde418d7fdc1/pkg/sql/walk.go#L479)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

nit: let's keep it sorted since it looks like it is already sorted except for the last two lines.
</blockquote></details>

Done.
___
*[`pkg/sql/opt/exec/execbuilder/scalar.go` line 727 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/85177#-NH1kXpu0-TyU7Hht16P:-NH4hlLfAdzZlYfIJ2Xh:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/0522b1e1839c98c7fb8a37376e16bde418d7fdc1/pkg/sql/opt/exec/execbuilder/scalar.go#L727)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

Should this change be in the first commit.
</blockquote></details>

Done.
___
*[`pkg/sql/distsql_plan_changefeed_test.go` line 93 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/85177#-NH1mgyJDs4Dv2KAWOZ6:-NH4hq3s1gzuyJtWsXQG:bi2mkx0) ([raw file](https://github.com/cockroachdb/cockroach/blob/0522b1e1839c98c7fb8a37376e16bde418d7fdc1/pkg/sql/distsql_plan_changefeed_test.go#L93)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

Nice tests! I think we're missing some cases where multiple different tables are used by the query, right? It'd be good to add a case with two tables when both are existing as well as when one is not found. Or this checked elsewhere?
</blockquote></details>

We only support single table.  I check to make sure we only have a single scan operation.  Added a tests.

**Review by yuzefovich — APPROVED** [review]
I only have questions and nits, so :lgtm:

It would still be good to get an approval from @rytaft or @drewkimball on the optimizer / AST node / opt catalog changes.

> Reviewed 25 of 40 files at r6, 11 of 11 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/85177#-:-NHaOQd06IbnA7itTd_F:b-8shjlg)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @DrewKimball, @HonoreDB, @miretskiy, and @rytaft)

___
*[`pkg/ccl/changefeedccl/event_processing.go` line 288 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/85177#-NH_zxtI-FUTShZKUdCQ:-NH_zxtI-FUTShZKUdCR:b-hxv4mt) ([raw file](https://github.com/cockroachdb/cockroach/blob/7c7622f3d0489c171a5fabd687d39b3f0095c607/pkg/ccl/changefeedccl/event_processing.go#L288)):*
> ```Go
> 
> 		if !matches {
> 			// TODO(yevgeniy): Add metrics
> ```

nit: it seems like it might be worth tracking the metric for the number of filtered out events, so maybe keep the TODO?
___
*[`pkg/ccl/changefeedccl/cdceval/doc.go` line 47 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/85177#-NHa-efA9-t-4iKXGUVe:-NHa-efA9-t-4iKXGUVf:b-gr3f0q) ([raw file](https://github.com/cockroachdb/cockroach/blob/9b2726933a94d5f8f0b2d83cc53e065bef5dc519/pkg/ccl/changefeedccl/cdceval/doc.go#L47)):*
> ```Go
> Evaluator is the gateway into the evaluation logic;  it takes care of running
> execution flow, caching (to reuse the same plan as long as the descriptor version
> does not change, etc).
> ```

nit: probably "not change, etc)" -> "not change), etc".
___
*[`pkg/ccl/changefeedccl/cdceval/doc.go` line 74 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/85177#-NHa-xXC1eS4a3KFz7IW:-NHa-xXC1eS4a3KFz7IX:bgh1yfh) ([raw file](https://github.com/cockroachdb/cockroach/blob/9b2726933a94d5f8f0b2d83cc53e065bef5dc519/pkg/ccl/changefeedccl/cdceval/doc.go#L74)):*
> ```Go
> Virtual computed columns can be easily supported but currently are not.
> To support virtual computed columns we must ensure that the expression in that
> column references only the target changefeed column familiy.
> ```

nit: `s/familiy/family/`.
___
*[`pkg/ccl/changefeedccl/cdceval/expr_eval.go` line 109 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/85177#-NHa0l6X3NjL9V8eaEDI:-NHa0l6X3NjL9V8eaEDJ:buecw80) ([raw file](https://github.com/cockroachdb/cockroach/blob/9b2726933a94d5f8f0b2d83cc53e065bef5dc519/pkg/ccl/changefeedccl/cdceval/expr_eval.go#L109)):*
> ```Go
> 	// Push data into dist SQL.
> 	if st := e.input.Push(updatedRow.EncDatums(), nil); st != execinfra.NeedMoreRows {
> 		return cdcevent.Row{}, errors.AssertionFailedf("unexpected consumer status %s", st)
> ```

Is this always an assertion failure? What happens if the "main" context is canceled? What if the node where the coordinator runs is being drained?
___
*[`pkg/ccl/changefeedccl/cdceval/expr_eval.go` line 300 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/85177#-NHa2TskBoXxDSW9QPsL:-NHa2TskBoXxDSW9QPsM:b2sh1of) ([raw file](https://github.com/cockroachdb/cockroach/blob/9b2726933a94d5f8f0b2d83cc53e065bef5dc519/pkg/ccl/changefeedccl/cdceval/expr_eval.go#L300)):*
> ```Go
> }
> 
> // setupContext configures evaluation context with the provided row information.
> ```

nit: `s/setupContext/setupContextForRow/`.
___
*[`pkg/ccl/changefeedccl/cdceval/plan.go` line 101 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/85177#-NHa7qJa-YMcBgWm_eH3:-NHa7qJa-YMcBgWm_eH4:b-hfy8gp) ([raw file](https://github.com/cockroachdb/cockroach/blob/9b2726933a94d5f8f0b2d83cc53e065bef5dc519/pkg/ccl/changefeedccl/cdceval/plan.go#L101)):*
> ```Go
> }
> 
> // newCDCPlanExpr construct sql.CDCExpression from the specified NormalizedSelectClause.
> ```

nit: `s/construct/constructs/`.
___
*[`pkg/ccl/changefeedccl/cdceval/plan.go` line 206 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/85177#-NHa8XUh-slhOhaAC1AW:-NHa8XUh-slhOhaAC1AX:b-4rfuup) ([raw file](https://github.com/cockroachdb/cockroach/blob/9b2726933a94d5f8f0b2d83cc53e065bef5dc519/pkg/ccl/changefeedccl/cdceval/plan.go#L206)):*
> ```Go
> // a DescsTxn transaction to ensure that descriptors get acquired
> // as of correct schema timestamp.
> func plannerExec(
> ```

nit: `plannerExec` is a bit confusing name (i.e. does it have something to do with the execution of some plan or not?), maybe rename it to something like `fnWithPlanner`?
___
*[`pkg/ccl/changefeedccl/cdceval/validation.go` line 238 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/85177#-NHa9eLA85lMbjtpxXby:-NHa9eLA85lMbjtpxXbz:bkkh6ds) ([raw file](https://github.com/cockroachdb/cockroach/blob/9b2726933a94d5f8f0b2d83cc53e065bef5dc519/pkg/ccl/changefeedccl/cdceval/validation.go#L238)):*
> ```Go
> func requiresPrev(stmt tree.Statement) (requiresPrev bool) {
> 	// Quick check to see if we need cdc_prev access; no need to do full
> 	// normalization since at this time expression was already normalized.
> ```

Can we somehow assert that the expression is already normalized? Alternatively, it seems like this method is called in two places where we construct `NormalizedSelectClause` - should we instead have a constructor method that would return `*NormalizedSelectClause` and would internally do this "requires prev" check? This way it'll be more explicit that the expression must be normalized when the constructor is called.
___
*[`pkg/ccl/changefeedccl/cdcevent/event.go` line 130 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/85177#-NHaD9JA0M_dW7nmgKDS:-NHaD9JA0M_dW7nmgKDT:bruidp1) ([raw file](https://github.com/cockroachdb/cockroach/blob/9b2726933a94d5f8f0b2d83cc53e065bef5dc519/pkg/ccl/changefeedccl/cdcevent/event.go#L130)):*
> ```Go
> 
> // CopyInto decodes and copies encdatums to specified tuple.
> func (r Row) CopyInto(row *tree.DTuple) error {
> ```

I can't seem to find where this `DTuple` is allocated and where `setPrevFuncForEventDescriptor` is defined.

nit: maybe also do `s/row/tuple/` to disambiguate with the receiver better?
___
*[`pkg/ccl/changefeedccl/cdcevent/event.go` line 162 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/85177#-NHaDedQ1vHH3SHg0oIn:-NHaDedQ1vHH3SHg0oIo:bh8aohq) ([raw file](https://github.com/cockroachdb/cockroach/blob/9b2726933a94d5f8f0b2d83cc53e065bef5dc519/pkg/ccl/changefeedccl/cdcevent/event.go#L162)):*
> ```Go
> 
> // String returns debug string describing event source.
> func (m Metadata) String() string {
> ```

nit: should this be then named `DebugString` similar to below?
___
*[`pkg/ccl/changefeedccl/cdcevent/projection.go` line 85 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/85177#-NHaECX97Cobh-nkvCO-:-NHaECX97Cobh-nkvCO0:bdd5mb5) ([raw file](https://github.com/cockroachdb/cockroach/blob/9b2726933a94d5f8f0b2d83cc53e065bef5dc519/pkg/ccl/changefeedccl/cdcevent/projection.go#L85)):*
> ```Go
> }
> 
> // setKeysFromRow sets this projection keys from keys in the specified row.
> ```

nit: the comment is confusing - the previous version where we had this function inlined in `Project` seemed cleaner.
___
*[`pkg/sql/distsql_plan_changefeed.go` line 59 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/85177#-NHaJR839K-I734AMUeh:-NHaJR839K-I734AMUei:bqca6pw) ([raw file](https://github.com/cockroachdb/cockroach/blob/9b2726933a94d5f8f0b2d83cc53e065bef5dc519/pkg/sql/distsql_plan_changefeed.go#L59)):*
> ```Go
> 	ctx context.Context, localPlanner interface{}, cdcExpr CDCExpression,
> ) (cdcPlan CDCExpressionPlan, _ error) {
> 	p := localPlanner.(*planner)
> ```

nit: maybe return an assertion failure error if it's not a `planner`?
___
*[`pkg/sql/distsql_plan_changefeed.go` line 115 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/85177#-NHaK1bhBjTLW9QRr9vP:-NHaK1bhBjTLW9QRr9vQ:b-9alez2) ([raw file](https://github.com/cockroachdb/cockroach/blob/9b2726933a94d5f8f0b2d83cc53e065bef5dc519/pkg/sql/distsql_plan_changefeed.go#L115)):*
> ```Go
> 			// Because the walk is top down, the top node is the node containing the
> 			// list of columns to return.
> 			if len(presentation) == 0 {
> ```

Is it possible that `planColumns` return zero length slice? Maybe we should check for `presentation` being `nil` here? I guess not but thought I'd still ask.
___
*[`pkg/ccl/changefeedccl/cdceval/plan_test.go` line 49 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/85177#-NHaNLZt0APZXxPb_ZD-:-NHaNLZt0APZXxPb_ZD0:by3br03) ([raw file](https://github.com/cockroachdb/cockroach/blob/9b2726933a94d5f8f0b2d83cc53e065bef5dc519/pkg/ccl/changefeedccl/cdceval/plan_test.go#L49)):*
> ```Go
> 		`CREATE TYPE alt.status AS ENUM ('alt_open', 'alt_closed', 'alt_inactive')`,
> 		`CREATE TABLE foo (a INT PRIMARY KEY, status status, alt alt.status, extra STRING,
>      FAMILY main (a, status, alt),
> ```

nit: seems like an indentation is off.

**Review by miretskiy — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/85177)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @DrewKimball, @HonoreDB, @rytaft, and @yuzefovich)

___
*[`pkg/ccl/changefeedccl/event_processing.go` line 288 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/85177#-NH_zxtI-FUTShZKUdCQ:-NHjG_4A72YtcnfvPXhB:b2oxaga) ([raw file](https://github.com/cockroachdb/cockroach/blob/7c7622f3d0489c171a5fabd687d39b3f0095c607/pkg/ccl/changefeedccl/event_processing.go#L288)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

nit: it seems like it might be worth tracking the metric for the number of filtered out events, so maybe keep the TODO?
</blockquote></details>

Definitely.  Didn't mean to drop the todo.
___
*[`pkg/ccl/changefeedccl/cdceval/expr_eval.go` line 109 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/85177#-NHa0l6X3NjL9V8eaEDI:-NHjHiSVD5R8KK8tMGhP:b-e541iq) ([raw file](https://github.com/cockroachdb/cockroach/blob/9b2726933a94d5f8f0b2d83cc53e065bef5dc519/pkg/ccl/changefeedccl/cdceval/expr_eval.go#L109)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

Is this always an assertion failure? What happens if the "main" context is canceled? What if the node where the coordinator runs is being drained?
</blockquote></details>

This used to be the case before I added ConsumerDone call as you requested; now, it seems this
may no longer be the case.  Still, I think returning error here is correct -- we will shutdown evaluator, and the whole flow, and then restart the flow (because all errors are now treated as retryable).
I augmented input initialization code with a  hopefully useful comment below:

Going to add a test around shutdown as well.

```
// The row channel created below will have exactly 1 sender (this evaluator).
// The buffer size parameter doesn't matter much, as long as it is greater
// than 0 to make sure that if the main context is cancelled and the flow
// exits, that we can still push data into the row channel without blocking,
// so that we notice cancellation request when we try to read the result of
// the evaluation.
const numSenders = 1
const bufSize = 16
var input execinfra.RowChannel
input.InitWithBufSizeAndNumSenders(inputTypes, bufSize, numSenders)
```
___
*[`pkg/ccl/changefeedccl/cdceval/plan.go` line 206 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/85177#-NHa8XUh-slhOhaAC1AW:-NHjLvOn7lvQTepd85IB:b-p3gjsw) ([raw file](https://github.com/cockroachdb/cockroach/blob/9b2726933a94d5f8f0b2d83cc53e065bef5dc519/pkg/ccl/changefeedccl/cdceval/plan.go#L206)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

nit: `plannerExec` is a bit confusing name (i.e. does it have something to do with the execution of some plan or not?), maybe rename it to something like `fnWithPlanner`?
</blockquote></details>

renamed to `withPlanner`.
___
*[`pkg/ccl/changefeedccl/cdceval/validation.go` line 238 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/85177#-NHa9eLA85lMbjtpxXby:-NI-gQooCmlF0CUFuPF7:b-taktyn) ([raw file](https://github.com/cockroachdb/cockroach/blob/9b2726933a94d5f8f0b2d83cc53e065bef5dc519/pkg/ccl/changefeedccl/cdceval/validation.go#L238)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

Can we somehow assert that the expression is already normalized? Alternatively, it seems like this method is called in two places where we construct `NormalizedSelectClause` - should we instead have a constructor method that would return `*NormalizedSelectClause` and would internally do this "requires prev" check? This way it'll be more explicit that the expression must be normalized when the constructor is called.
</blockquote></details>

I reworked the code a bit.  No longer have boolean indicating if the expression should be normalized.
Now, when changefeed created, normalization step is done -- which rewrites the expression; and the rewritten expression gets written to jobs record.  Thereafter, there is no longer the need to normalize.
I also split the method into 2 helpers -- yes, there is a bit more repetition, but the code is better imo.
Let me know what you think.
___
*[`pkg/ccl/changefeedccl/cdcevent/event.go` line 130 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/85177#-NHaD9JA0M_dW7nmgKDS:-NHkV17e9R2Q2C6K-dis:b69quzt) ([raw file](https://github.com/cockroachdb/cockroach/blob/9b2726933a94d5f8f0b2d83cc53e065bef5dc519/pkg/ccl/changefeedccl/cdcevent/event.go#L130)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

I can't seem to find where this `DTuple` is allocated and where `setPrevFuncForEventDescriptor` is defined.

nit: maybe also do `s/row/tuple/` to disambiguate with the receiver better?
</blockquote></details>

rename done; DTuple allocated as part of the row eval context; setPrevFuncForEventDescriptor defined
as part of function_resolver -- 
___
*[`pkg/ccl/changefeedccl/cdcevent/event.go` line 162 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/85177#-NHaDedQ1vHH3SHg0oIn:-NHkVEFg0YN_QiUGyF_C:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/9b2726933a94d5f8f0b2d83cc53e065bef5dc519/pkg/ccl/changefeedccl/cdcevent/event.go#L162)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

nit: should this be then named `DebugString` similar to below?
</blockquote></details>

Done.
___
*[`pkg/ccl/changefeedccl/cdcevent/projection.go` line 85 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/85177#-NHaECX97Cobh-nkvCO-:-NHjP0hz5j6ADMyFgt7C:bl3pqfw) ([raw file](https://github.com/cockroachdb/cockroach/blob/9b2726933a94d5f8f0b2d83cc53e065bef5dc519/pkg/ccl/changefeedccl/cdcevent/projection.go#L85)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

nit: the comment is confusing - the previous version where we had this function inlined in `Project` seemed cleaner.
</blockquote></details>

reverted to previous version
___
*[`pkg/sql/distsql_plan_changefeed.go` line 115 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/85177#-NHaK1bhBjTLW9QRr9vP:-NHjPhJD34adS_JrLKDt:b-dds7u) ([raw file](https://github.com/cockroachdb/cockroach/blob/9b2726933a94d5f8f0b2d83cc53e065bef5dc519/pkg/sql/distsql_plan_changefeed.go#L115)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

Is it possible that `planColumns` return zero length slice? Maybe we should check for `presentation` being `nil` here? I guess not but thought I'd still ask.
</blockquote></details>

Well, planColumns can return noColumns which is non-nil, 0 length slice.  That's why I check for length, and not for being nil. I do check below to make sure that presentation has at least 1 column.
___
*[`pkg/ccl/changefeedccl/cdceval/plan_test.go` line 49 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/85177#-NHaNLZt0APZXxPb_ZD-:-NHjQ96W9747jj8p4Kcs:bwgo4ns) ([raw file](https://github.com/cockroachdb/cockroach/blob/9b2726933a94d5f8f0b2d83cc53e065bef5dc519/pkg/ccl/changefeedccl/cdceval/plan_test.go#L49)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

nit: seems like an indentation is off.
</blockquote></details>

Hmm.. Indentation is okay in goland.. Anyway, reformatted.

**Review by HonoreDB — COMMENTED** [review]
> Reviewed 7 of 14 files at r1, 8 of 48 files at r4, 3 of 13 files at r5, 12 of 40 files at r6, 2 of 11 files at r7, 34 of 34 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/85177)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @DrewKimball, @miretskiy, @rytaft, and @yuzefovich)

___
*[`pkg/ccl/changefeedccl/cdceval/expr_eval.go` line 119 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/85177#-NI37e_Q03fawgGXyyN_:-NI37e_R6fSyvMRGesJf:b-uerqp5) ([raw file](https://github.com/cockroachdb/cockroach/blob/a3516f00fc14c95b974b30fb85040026e4639027/pkg/ccl/changefeedccl/cdceval/expr_eval.go#L119)):*
> ```Go
> 		return cdcevent.Row{}, err
> 	case row := <-e.rowCh:
> 		if !tree.MustBeDBool(row[0]) {
> ```

nonblocking: could be worth a tiny optimization here to do `row[0] != tree.DBoolTrue` since boolean datums are always unwrapped and always the same global variables. Or since we're controlling it anyway in the `predicateAsProjection` function, just set it to whatever sentinel value you want.
___
*[`pkg/ccl/changefeedccl/cdceval/functions.go` line 36 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/85177#-NI3Btwn6AF1s231Z5YZ:-NI3Btwn6AF1s231Z5Y_:bzhu69l) ([raw file](https://github.com/cockroachdb/cockroach/blob/a3516f00fc14c95b974b30fb85040026e4639027/pkg/ccl/changefeedccl/cdceval/functions.go#L36)):*
> ```Go
> //
> // Any builtin stable (or volatile) function that accesses eval.Context will
> // have to have an override due to the fact that we should not manipulate
> ```

Wouldn't it be easier to make a deep copy of the eval context and manipulate it as we please? I feel like there's a method for that already.
___
*[`pkg/ccl/changefeedccl/cdceval/functions.go` line 236 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/85177#-NI3CK1lDoChcO4gztSO:-NI3CK1m9yqLmf6-nC1n:b-h1tdkd) ([raw file](https://github.com/cockroachdb/cockroach/blob/a3516f00fc14c95b974b30fb85040026e4639027/pkg/ccl/changefeedccl/cdceval/functions.go#L236)):*
> ```Go
> 				return nil, pgerror.Newf(pgcode.UndefinedFunction, "function %q unsupported by CDC", fn.Name)
> 			}
> 			if overload.Volatility > fnVolatility {
> ```

Do we still need to be setting volatility at the function level like this? Might be a separate PR, but I feel like we have enough machinery now to pick out specific overloads.
___
*[`pkg/ccl/changefeedccl/cdceval/validation.go` line 152 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/85177#-NI3EvUY6zHY9ujmv-M0:-NI3EvUY6zHY9ujmv-M1:b6wrynk) ([raw file](https://github.com/cockroachdb/cockroach/blob/a3516f00fc14c95b974b30fb85040026e4639027/pkg/ccl/changefeedccl/cdceval/validation.go#L152)):*
> ```Go
> 
> 	if cv.seenStar {
> 		if nonKeyColSet.Len() > 0 && numReferencedNonKeyFamilies > 1 {
> ```

This looks redundant, I don't think nonKeyColSet can be empty if numReferencedNonKeyFamilies > 1. Also, if we're allowing star with `numReferencedNonKeyFamilies == 1` that's a change to previous logic and the error message should change (or maybe just be removed since we should catch > 1 cases later.) Was that intentional? It does arguably seem okay to use * along explicit column references from a single family since that's similar to using it with a single family feed.
___
*[`pkg/ccl/changefeedccl/cdceval/validation.go` line 193 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/85177#-NI3GPiOB7PV5oHoPqER:-NI3GPiOB7PV5oHoPqES:bm5jsix) ([raw file](https://github.com/cockroachdb/cockroach/blob/a3516f00fc14c95b974b30fb85040026e4639027/pkg/ccl/changefeedccl/cdceval/validation.go#L193)):*
> ```Go
> 			"expressions can't reference columns from more than one column family")
> 	}
> 	if len(referencedFamilies) == 0 {
> ```

We previously supported expressions that don't reference any columns, does this break that? 
___
*[`pkg/ccl/changefeedccl/cdceval/validation.go` line 344 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/85177#-NI3HQ1O7DqtNcZS7dn8:-NI3HQ1O7DqtNcZS7dn9:b-83sjo4) ([raw file](https://github.com/cockroachdb/cockroach/blob/a3516f00fc14c95b974b30fb85040026e4639027/pkg/ccl/changefeedccl/cdceval/validation.go#L344)):*
> ```Go
> 								pgerror.Newf(pgcode.AmbiguousColumn,
> 									"ambiguous cdc_prev column collides with CDC reserved keyword.  "+
> 										"Disambiguate with %s.cdc_prev", desc.TableName)
> ```

Nice.
___
*[`pkg/ccl/changefeedccl/cdceval/validation.go` line 478 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/85177#-NI3IF9yDABe2SlU_umX:-NI3IF9yDABe2SlU_umY:b-qb39qu) ([raw file](https://github.com/cockroachdb/cockroach/blob/a3516f00fc14c95b974b30fb85040026e4639027/pkg/ccl/changefeedccl/cdceval/validation.go#L478)):*
> ```Go
> 		// That's a bit of a mouthful, but all we're doing here is adding
> 		// another table sub-select to the query to produce cdc_prev tuple:
> 		// SELECT ... FROM tbl, (SELECT ((crdb_internal.cdc_prev_row()).*)) AS cdc_prev
> ```

Another way to do this could be a top-level `var prevTupleExpr = parse("(SELECT ((crdb_internal.cdc_prev_row()).*)) AS cdc_prev")`
___
*[`pkg/ccl/changefeedccl/cdcevent/projection.go` line 81 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/85177#-NI3K7n41Iab-r7QbB8H:-NI3K7n41Iab-r7QbB8I:b-27l5si) ([raw file](https://github.com/cockroachdb/cockroach/blob/a3516f00fc14c95b974b30fb85040026e4639027/pkg/ccl/changefeedccl/cdcevent/projection.go#L81)):*
> ```Go
> 	}
> 
> 	return pgerror.Newf(pgcode.DatatypeMismatch,
> ```

Removing the implicit cast?
___
*[`pkg/ccl/changefeedccl/cdceval/expr_eval_test.go` line 364 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/85177#-NI3Ma3z4HsESteKXbsQ:-NI3Ma3z4HsESteKXbsR:buhn28n) ([raw file](https://github.com/cockroachdb/cockroach/blob/a3516f00fc14c95b974b30fb85040026e4639027/pkg/ccl/changefeedccl/cdceval/expr_eval_test.go#L364)):*
> ```Go
> 				"INSERT INTO foo (a, b) VALUES (1,  'hello')",
> 			},
> 			stmt: "SELECT a,  b % 'hel' AS trigram FROM foo",
> ```

Does this work now or does it still always match when running in a job?

**Review by miretskiy — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/85177)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @DrewKimball, @HonoreDB, @rytaft, and @yuzefovich)

___
*[`pkg/ccl/changefeedccl/cdceval/expr_eval.go` line 119 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/85177#-NI37e_Q03fawgGXyyN_:-NI3VnK58d73Y08F4wOE:b-uz64zg) ([raw file](https://github.com/cockroachdb/cockroach/blob/a3516f00fc14c95b974b30fb85040026e4639027/pkg/ccl/changefeedccl/cdceval/expr_eval.go#L119)):*
<details><summary><i>Previously, HonoreDB (Aaron Zinger) wrote…</i></summary><blockquote>

nonblocking: could be worth a tiny optimization here to do `row[0] != tree.DBoolTrue` since boolean datums are always unwrapped and always the same global variables. Or since we're controlling it anyway in the `predicateAsProjection` function, just set it to whatever sentinel value you want.
</blockquote></details>

where is it specified that they are always unwrapped? Anyways, I'd rather not jump into micro optimization.
___
*[`pkg/ccl/changefeedccl/cdceval/functions.go` line 36 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/85177#-NI3Btwn6AF1s231Z5YZ:-NI3WBAY7r_0rQuRVqyL:bow97cp) ([raw file](https://github.com/cockroachdb/cockroach/blob/a3516f00fc14c95b974b30fb85040026e4639027/pkg/ccl/changefeedccl/cdceval/functions.go#L36)):*
<details><summary><i>Previously, HonoreDB (Aaron Zinger) wrote…</i></summary><blockquote>

Wouldn't it be easier to make a deep copy of the eval context and manipulate it as we please? I feel like there's a method for that already.
</blockquote></details>

Updated comment; no we should not take deep copy -- added comment explain that this creates data races, plus dist sql makes a copy anyway.
___
*[`pkg/ccl/changefeedccl/cdceval/functions.go` line 236 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/85177#-NI3CK1lDoChcO4gztSO:-NI3WO2n2UCk6lksPlY0:b9t9ddi) ([raw file](https://github.com/cockroachdb/cockroach/blob/a3516f00fc14c95b974b30fb85040026e4639027/pkg/ccl/changefeedccl/cdceval/functions.go#L236)):*
<details><summary><i>Previously, HonoreDB (Aaron Zinger) wrote…</i></summary><blockquote>

Do we still need to be setting volatility at the function level like this? Might be a separate PR, but I feel like we have enough machinery now to pick out specific overloads.
</blockquote></details>

I'm okay with leaving it to the next PR if needed.
___
*[`pkg/ccl/changefeedccl/cdceval/validation.go` line 152 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/85177#-NI3EvUY6zHY9ujmv-M0:-NI3WukG1EWyEuHrsd6d:b-fytqri) ([raw file](https://github.com/cockroachdb/cockroach/blob/a3516f00fc14c95b974b30fb85040026e4639027/pkg/ccl/changefeedccl/cdceval/validation.go#L152)):*
<details><summary><i>Previously, HonoreDB (Aaron Zinger) wrote…</i></summary><blockquote>

This looks redundant, I don't think nonKeyColSet can be empty if numReferencedNonKeyFamilies > 1. Also, if we're allowing star with `numReferencedNonKeyFamilies == 1` that's a change to previous logic and the error message should change (or maybe just be removed since we should catch > 1 cases later.) Was that intentional? It does arguably seem okay to use * along explicit column references from a single family since that's similar to using it with a single family feed.
</blockquote></details>

I think this was intentional.
`CREATE TABLE baz (a INT PRIMARY KEY, b INT, c STRING, FAMILY most (a, b), FAMILY only_c (c))`

`SELECT *, c FROM foo` fails this check w/out numReferencedNonKeyFamilies.
(target family is only_c, nonKeyColSet is 1, and we've seen * -- which now refers to a, b, c)
___
*[`pkg/ccl/changefeedccl/cdceval/validation.go` line 193 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/85177#-NI3GPiOB7PV5oHoPqER:-NI3bCe7EtVc3z395qHw:bvu00d8) ([raw file](https://github.com/cockroachdb/cockroach/blob/a3516f00fc14c95b974b30fb85040026e4639027/pkg/ccl/changefeedccl/cdceval/validation.go#L193)):*
<details><summary><i>Previously, HonoreDB (Aaron Zinger) wrote…</i></summary><blockquote>

We previously supported expressions that don't reference any columns, does this break that? 
</blockquote></details>

Added a test.  I think things still work.  The check above 
`	if nonKeyColSet.Len() == 0 {`
will catch the case when the expression didn't reference any columns (select pi() ...)
___
*[`pkg/ccl/changefeedccl/cdceval/validation.go` line 344 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/85177#-NI3HQ1O7DqtNcZS7dn8:-NI3bRhk6xE6Vu-aqGvz:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/a3516f00fc14c95b974b30fb85040026e4639027/pkg/ccl/changefeedccl/cdceval/validation.go#L344)):*
<details><summary><i>Previously, HonoreDB (Aaron Zinger) wrote…</i></summary><blockquote>

Nice.
</blockquote></details>

Done.
___
*[`pkg/ccl/changefeedccl/cdceval/validation.go` line 478 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/85177#-NI3IF9yDABe2SlU_umX:-NI3bU7Q1_lK4Mq6-Uqo:bgrabja) ([raw file](https://github.com/cockroachdb/cockroach/blob/a3516f00fc14c95b974b30fb85040026e4639027/pkg/ccl/changefeedccl/cdceval/validation.go#L478)):*
<details><summary><i>Previously, HonoreDB (Aaron Zinger) wrote…</i></summary><blockquote>

Another way to do this could be a top-level `var prevTupleExpr = parse("(SELECT ((crdb_internal.cdc_prev_row()).*)) AS cdc_prev")`
</blockquote></details>

Hmm... I like parse() idea... Alas, it doesn't work quite well:
First, I can't just parse `"(SELECT ((crdb_internal.cdc_prev_row()).*)) AS cdc_prev")` -- This is neither
an expression nor a statement.  I have to parse something like `"SELECT * FROM (SELECT ((crdb_internal.cdc_prev_row()).*)) AS cdc_prev")`' and once I do that, I get statement, from which I need
to yank out the first table.. The expression for this would look something like this:
`prevTupleExpr.AST.(*tree.Select).Select.(*tree.SelectClause).From.Tables[0]`
Arguably, pretty ugly (and of course, if I want to be safe, every cast must be done with ok check.
So, I just don't think that in the end, things are much clearer.  As I say above: it's a mouthful, but at least
it's all very explicit.

As to having it as a global -- been there, done that; Took few hours to confirm though.  Comment added.
Basically, we can't have it as a global variable because the underlying function reference gets replaced
with function definition (i.e. concrete type) -- this causes failures when the underlying type changes (i.e. new version of event descriptor)
___
*[`pkg/ccl/changefeedccl/cdcevent/projection.go` line 81 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/85177#-NI3K7n41Iab-r7QbB8H:-NI7daHw0lkzd0ZOC2AE:bqlkmiw) ([raw file](https://github.com/cockroachdb/cockroach/blob/a3516f00fc14c95b974b30fb85040026e4639027/pkg/ccl/changefeedccl/cdcevent/projection.go#L81)):*
<details><summary><i>Previously, HonoreDB (Aaron Zinger) wrote…</i></summary><blockquote>

Removing the implicit cast?
</blockquote></details>

Yeah -- optimizer should  generate plan that performs appropriate casts.
___
*[`pkg/ccl/changefeedccl/cdceval/expr_eval_test.go` line 364 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/85177#-NI3Ma3z4HsESteKXbsQ:-NI7ds4P4W9qVT4EdFYO:b3uud4b) ([raw file](https://github.com/cockroachdb/cockroach/blob/a3516f00fc14c95b974b30fb85040026e4639027/pkg/ccl/changefeedccl/cdceval/expr_eval_test.go#L364)):*
<details><summary><i>Previously, HonoreDB (Aaron Zinger) wrote…</i></summary><blockquote>

Does this work now or does it still always match when running in a job?
</blockquote></details>

I'm sorry -- not sure I understand your question.  Is this about session data (that still needs to happen). 
But the test does seem to work.

**Review by rytaft — COMMENTED** [review]
Nice! I may have some more comments, but pushing what I have for now. My main concern is the new machinery for disallowing stable folds. I'm not sure why you can't use the existing machinery.

> Reviewed 7 of 14 files at r1, 1 of 48 files at r4, 3 of 13 files at r5, 12 of 40 files at r6, 2 of 11 files at r7, 31 of 34 files at r8, 3 of 3 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/85177#-:-NI8XAk5AzMfMo1bIMYJ:b-6yq4wi)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @DrewKimball, @HonoreDB, @miretskiy, and @yuzefovich)

___
*[`pkg/ccl/changefeedccl/event_processing.go` line 294 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/85177#-NI80Suu30ugr9It-T5X:-NI80Suu30ugr9It-T5Y:b-3grm6t) ([raw file](https://github.com/cockroachdb/cockroach/blob/f03a9a11a8e80b18553528d93f8d704a695b04ec/pkg/ccl/changefeedccl/event_processing.go#L294)):*
> ```Go
> 		// Clear out prevRow.  Projection can already emit previous row; thus
> 		// it would be superfluous to also encode prevRow.
> 		updatedRow, prevRow = projection, cdcevent.Row{}
> ```

Then perhaps "updatedRow" isn't the best name if it can include other things too?
___
*[`pkg/ccl/changefeedccl/cdceval/doc.go` line 32 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/85177#-NI81d4HDStTwoF4PYo0:-NI81d4I2G8tdRtcJi2x:b-8qwjmd) ([raw file](https://github.com/cockroachdb/cockroach/blob/f03a9a11a8e80b18553528d93f8d704a695b04ec/pkg/ccl/changefeedccl/cdceval/doc.go#L32)):*
> ```Go
> Then, once aggregators start up, they will once again plan the expression
> (sql.PlanCDCExpression), but this time each incoming KV event will be evaluated
> by dist sql to produce final result (projection).
> ```

nit: dist sql -> DistSQL
___
*[`pkg/ccl/changefeedccl/cdceval/doc.go` line 47 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/85177#-NI81xUj6Q0YWp8XvAng:-NI81xUk9pGn8Qht4zg_:b8o2m3r) ([raw file](https://github.com/cockroachdb/cockroach/blob/f03a9a11a8e80b18553528d93f8d704a695b04ec/pkg/ccl/changefeedccl/cdceval/doc.go#L47)):*
> ```Go
> Evaluator is the gateway into the evaluation logic;  it takes care of running
> execution flow, caching (to reuse the same plan as long as the descriptor version
> does not change), etc.
> ```

Do we need to worry about other things changing? The memo that is stored in the query plan cache gets invalidated whenever a variety of other things change, such as stats, etc.
___
*[`pkg/ccl/changefeedccl/cdceval/expr_eval.go` line 175 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/85177#-NI899vy3JU3k7KQMLJK:-NI899vy3JU3k7KQMLJL:br9ywdz) ([raw file](https://github.com/cockroachdb/cockroach/blob/f03a9a11a8e80b18553528d93f8d704a695b04ec/pkg/ccl/changefeedccl/cdceval/expr_eval.go#L175)):*
> ```Go
> 			semaCtx := execCtx.SemaCtx()
> 			semaCtx.FunctionResolver = &e.fnResolver
> 			semaCtx.Properties.Require("cdc", rejectInvalidCDCExprs)
> ```

should you call `configSemaForCDC` to allow cleanup? Or we don't care about restoring it after?
___
*[`pkg/ccl/changefeedccl/cdceval/expr_eval.go` line 211 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/85177#-NI878lA5RaNFOdSxYLF:-NI878lA5RaNFOdSxYLG:bow1bic) ([raw file](https://github.com/cockroachdb/cockroach/blob/f03a9a11a8e80b18553528d93f8d704a695b04ec/pkg/ccl/changefeedccl/cdceval/expr_eval.go#L211)):*
> ```Go
> 		nameUseCount[as]++
> 		if useCount > 0 {
> 			as = fmt.Sprintf("%s_%d", as, useCount)
> ```

do you have tests for this?
___
*[`pkg/ccl/changefeedccl/cdceval/functions.go` line 37 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/85177#-NI8B5Qk240eqQwW7J0M:-NI8B5Qk240eqQwW7J0N:b-9dy9f9) ([raw file](https://github.com/cockroachdb/cockroach/blob/f03a9a11a8e80b18553528d93f8d704a695b04ec/pkg/ccl/changefeedccl/cdceval/functions.go#L37)):*
> ```Go
> // Any builtin stable (or volatile) function that accesses eval.Context will
> // have to have an override due to the fact that we should not manipulate
> // underlying eval.Context directly (this is due to the fact that dist SQL copies eval
> ```

nit: dist SQL -> DistSQL
___
*[`pkg/ccl/changefeedccl/cdceval/validation.go` line 158 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/85177#-NI8H2kK0jc02QapVV0b:-NI8H2kK0jc02QapVV0c:b-jd094m) ([raw file](https://github.com/cockroachdb/cockroach/blob/f03a9a11a8e80b18553528d93f8d704a695b04ec/pkg/ccl/changefeedccl/cdceval/validation.go#L158)):*
> ```Go
> 		if !cv.splitColFams {
> 			return target, pgerror.Newf(pgcode.InvalidParameterValue,
> 				"targeting a table with multiple column families requires "+
> ```

do you know that there are multiple column families here? Doesn't seem like it...
___
*[`pkg/sql/distsql_plan_changefeed.go` line 87 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/85177#-NI8OWTz4UyL-9y-DCdI:-NI8OWTz4UyL-9y-DCdJ:bqtrdqe) ([raw file](https://github.com/cockroachdb/cockroach/blob/f03a9a11a8e80b18553528d93f8d704a695b04ec/pkg/sql/distsql_plan_changefeed.go#L87)):*
> ```Go
> 	}
> 
> 	const allowAutoCommit = false
> ```

why is allowAutoCommit false?
___
*[`pkg/sql/distsql_plan_changefeed.go` line 320 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/85177#-NI8QKa03mSg2S7s62F3:-NI8QKa03mSg2S7s62F4:bd4ivpa) ([raw file](https://github.com/cockroachdb/cockroach/blob/f03a9a11a8e80b18553528d93f8d704a695b04ec/pkg/sql/distsql_plan_changefeed.go#L320)):*
> ```Go
> // TODO(yevgeniy): We should be able to use secondary indexes provided
> // the CDC expression access only the columns available in that secondary index.
> func (c *cdcOptCatalog) newCDCDataSource(original catalog.TableDescriptor) (cat.DataSource, error) {
> ```

You could also use this approach to hide all columns not included in the target column family

(not necessary for this PR, but an option for the future)
___
*[`pkg/sql/distsql_plan_changefeed.go` line 325 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/85177#-NI8RDziEE6ZkUjP13EW:-NI8RDziEE6ZkUjP13EX:bj7ep3q) ([raw file](https://github.com/cockroachdb/cockroach/blob/f03a9a11a8e80b18553528d93f8d704a695b04ec/pkg/sql/distsql_plan_changefeed.go#L325)):*
> ```Go
> 	desc.Indexes = desc.Indexes[:0]
> 	updated := tabledesc.NewBuilder(desc).BuildImmutableTable()
> 	return newOptTable(updated, c.codec(), nil /* stats */, emptyZoneConfig)
> ```

Is there a reason you don't want to include stats? Do you expect that the optimizer will always return the correct plan regardless of stats?
___
*[`pkg/sql/opt/norm/fold_constants_funcs.go` line 684 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/85177#-NI8Ts4W5kog4MTfHvBM:-NI8Ts4W5kog4MTfHvBN:bhh7ohl) ([raw file](https://github.com/cockroachdb/cockroach/blob/f03a9a11a8e80b18553528d93f8d704a695b04ec/pkg/sql/opt/norm/fold_constants_funcs.go#L684)):*
> ```Go
> 	}
> 
> 	if private.Overload.InhibitStableFolds {
> ```

Instead of introducing this new machinery, can you use the existing machinery with `factory.FoldingControl().DisallowStableFolds()`?

**Review by miretskiy — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/85177)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @DrewKimball, @HonoreDB, @rytaft, and @yuzefovich)

___
*[`pkg/ccl/changefeedccl/event_processing.go` line 294 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/85177#-NI80Suu30ugr9It-T5X:-NI9gbSO-Pm6punElo8u:bmfe0oe) ([raw file](https://github.com/cockroachdb/cockroach/blob/f03a9a11a8e80b18553528d93f8d704a695b04ec/pkg/ccl/changefeedccl/event_processing.go#L294)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

Then perhaps "updatedRow" isn't the best name if it can include other things too?
</blockquote></details>

It is updated row though if you are not using expressions... I think I would prefer to keep the name, and updated/prev is fairly standard naming in cdc.
___
*[`pkg/ccl/changefeedccl/cdceval/doc.go` line 47 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/85177#-NI81xUj6Q0YWp8XvAng:-NI9guMlD-rAlMIlwT6n:b8st9fv) ([raw file](https://github.com/cockroachdb/cockroach/blob/f03a9a11a8e80b18553528d93f8d704a695b04ec/pkg/ccl/changefeedccl/cdceval/doc.go#L47)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

Do we need to worry about other things changing? The memo that is stored in the query plan cache gets invalidated whenever a variety of other things change, such as stats, etc.
</blockquote></details>

No, I don't think we need to worry about it.  Every time underlying descriptor changes, we replan the whole thing -- creating new planner (and new memo, etc) 
___
*[`pkg/ccl/changefeedccl/cdceval/expr_eval.go` line 175 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/85177#-NI899vy3JU3k7KQMLJK:-NI9h3o71iJn9VTwOuwS:bz0nuw1) ([raw file](https://github.com/cockroachdb/cockroach/blob/f03a9a11a8e80b18553528d93f8d704a695b04ec/pkg/ccl/changefeedccl/cdceval/expr_eval.go#L175)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

should you call `configSemaForCDC` to allow cleanup? Or we don't care about restoring it after?
</blockquote></details>

No, we actually don't want to clean up here at all (we want to use the same context when we try to execute flow).  Also, this method does  more things -- including annotations setup.
___
*[`pkg/ccl/changefeedccl/cdceval/expr_eval.go` line 211 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/85177#-NI878lA5RaNFOdSxYLF:-NI9h_5z6EdOLJR8NOV_:b-vzb3j5) ([raw file](https://github.com/cockroachdb/cockroach/blob/f03a9a11a8e80b18553528d93f8d704a695b04ec/pkg/ccl/changefeedccl/cdceval/expr_eval.go#L211)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

do you have tests for this?
</blockquote></details>

Yes (e.g. `main/same_column_many_times` test in expr_eval_test)
___
*[`pkg/ccl/changefeedccl/cdceval/validation.go` line 158 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/85177#-NI8H2kK0jc02QapVV0b:-NI9i4pL9Ws7F7d-g7AY:b-2b7y76) ([raw file](https://github.com/cockroachdb/cockroach/blob/f03a9a11a8e80b18553528d93f8d704a695b04ec/pkg/ccl/changefeedccl/cdceval/validation.go#L158)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

do you know that there are multiple column families here? Doesn't seem like it...
</blockquote></details>

We do I think -- we check to see if table has 1 family above.



_Code quote:_
```Go
	if len(allFamilies) == 1 {
		// There is only 1 column family, so use that.
		target.Type = jobspb.ChangefeedTargetSpecification_PRIMARY_FAMILY_ONLY
		return target, nil
	}
```
___
*[`pkg/sql/distsql_plan_changefeed.go` line 87 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/85177#-NI8OWTz4UyL-9y-DCdI:-NI9hrHG-xz6VFExvv9h:b7pvnku) ([raw file](https://github.com/cockroachdb/cockroach/blob/f03a9a11a8e80b18553528d93f8d704a695b04ec/pkg/sql/distsql_plan_changefeed.go#L87)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

why is allowAutoCommit false?
</blockquote></details>

Well, it's probably a no-op since we never commit anything (it's a select);
and I didn't want to pass in stray bool argument to runExecBuilder method.
Do you think it should be `true`?
___
*[`pkg/sql/distsql_plan_changefeed.go` line 320 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/85177#-NI8QKa03mSg2S7s62F3:-NI9e07R67zmhmMt4Bbg:br85wg6) ([raw file](https://github.com/cockroachdb/cockroach/blob/f03a9a11a8e80b18553528d93f8d704a695b04ec/pkg/sql/distsql_plan_changefeed.go#L320)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

You could also use this approach to hide all columns not included in the target column family

(not necessary for this PR, but an option for the future)
</blockquote></details>

Yeah -- I was considering this; but figured since I already have to do rewriting on cdc side, mide as well.
___
*[`pkg/sql/distsql_plan_changefeed.go` line 325 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/85177#-NI8RDziEE6ZkUjP13EW:-NI9e7852irmZOyAT7FT:b-xiwokj) ([raw file](https://github.com/cockroachdb/cockroach/blob/f03a9a11a8e80b18553528d93f8d704a695b04ec/pkg/sql/distsql_plan_changefeed.go#L325)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

Is there a reason you don't want to include stats? Do you expect that the optimizer will always return the correct plan regardless of stats?
</blockquote></details>

Good question... I'm not 100% sure on this; but given the fact that I only keep primary index, (and no subselects/joins/etc), I suspect there can only be 1 plan and so, I don't need stats.  I maybe wrong though.  Do you think these stats are needed here?
___
*[`pkg/sql/opt/norm/fold_constants_funcs.go` line 684 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/85177#-NI8Ts4W5kog4MTfHvBM:-NI9eN1QCqSpQ2zmeO7S:b1ppw5v) ([raw file](https://github.com/cockroachdb/cockroach/blob/f03a9a11a8e80b18553528d93f8d704a695b04ec/pkg/sql/opt/norm/fold_constants_funcs.go#L684)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

Instead of introducing this new machinery, can you use the existing machinery with `factory.FoldingControl().DisallowStableFolds()`?
</blockquote></details>

I used to have this call.  However, I realized that having stable folds might be
beneficial since we have fair number of stable functions which could be folded (to_char, quote, etc, etc, etc).

Now, the only "problem" is that I chose to allow some of the standard functions, s.a. transaction_timestamp() -- and override those to return MVCC timestamp of the event (see functions.go in this PR).
Of course, these functions are stable, but they cannot be folded by optimizer since the value
depends on the data that we will feed as we receive events.

There were 2 choices: 
  1. Disallow transaction/statement_timestamp functions and force people to use CDC specific override (e.g. cdc_mvcc_timestamp() or some such).  It's a reasonable option; the downside is that e.g. transaction_timestamp() is well documented/understood function, and so, it might make sense to keep it because it keeps CDC expression very close to the regular SQL  select clause.
  2. Basically, this approach, that allows for escape hatch for some of the stable functions.

It's not too late to choose the first option, if you feel strongly against introducing this escape hatch.
Thoughts?

**Review by rytaft — COMMENTED** [review]
Very close! Just one question about function resolution in the execbuilder

> Reviewed 4 of 4 files at r11, 3 of 3 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/85177#-:-NIDc9iB3Me3Wrfvm0Yp:bf9f5ul)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @DrewKimball, @HonoreDB, @miretskiy, and @yuzefovich)

___
*[`pkg/ccl/changefeedccl/cdceval/functions.go` line 86 at r12](https://reviewable.io/reviews/cockroachdb/cockroach/85177#-NIDYTVT-7IqTHJ9Y-dk:-NIDYTVT-7IqTHJ9Y-dl:b6dygvc) ([raw file](https://github.com/cockroachdb/cockroach/blob/e2f40b68bc22caea8e376ecb1b88b64485211c09/pkg/ccl/changefeedccl/cdceval/functions.go#L86)):*
> ```Go
> 			},
> 			Info:       "Returns true if the event is a deletion",
> 			Volatility: volatility.Volatile,
> ```

nit: add comment here to explain
___
*[`pkg/ccl/changefeedccl/cdceval/functions.go` line 176 at r12](https://reviewable.io/reviews/cockroachdb/cockroach/85177#-NIDY_9p3fO1-W_23GNj:-NIDY_9p3fO1-W_23GNk:b6dygvc) ([raw file](https://github.com/cockroachdb/cockroach/blob/e2f40b68bc22caea8e376ecb1b88b64485211c09/pkg/ccl/changefeedccl/cdceval/functions.go#L176)):*
> ```Go
> 			},
> 			Info:             "Returns previous value of a row as tuple",
> 			Volatility:       volatility.Volatile,
> ```

nit: add comment here to explain
___
*[`pkg/ccl/changefeedccl/cdceval/validation.go` line 158 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/85177#-NI8H2kK0jc02QapVV0b:-NIDWBLAAZFNEUJz-1W3:bvdfvex) ([raw file](https://github.com/cockroachdb/cockroach/blob/f03a9a11a8e80b18553528d93f8d704a695b04ec/pkg/ccl/changefeedccl/cdceval/validation.go#L158)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

We do I think -- we check to see if table has 1 family above.
</blockquote></details>

Ah thanks missed that
___
*[`pkg/sql/distsql_plan_changefeed.go` line 87 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/85177#-NI8OWTz4UyL-9y-DCdI:-NIDWIizAKSAUN2n7UPE:bqiqdmu) ([raw file](https://github.com/cockroachdb/cockroach/blob/f03a9a11a8e80b18553528d93f8d704a695b04ec/pkg/sql/distsql_plan_changefeed.go#L87)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

Well, it's probably a no-op since we never commit anything (it's a select);
and I didn't want to pass in stray bool argument to runExecBuilder method.
Do you think it should be `true`?
</blockquote></details>

Oh ok -- that's fine then. You could also do `false /* allowAutoCommit */`, but this is fine as-is
___
*[`pkg/sql/distsql_plan_changefeed.go` line 320 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/85177#-NI8QKa03mSg2S7s62F3:-NIDWbI2DSXx11cJty4e:b-lsmpod) ([raw file](https://github.com/cockroachdb/cockroach/blob/f03a9a11a8e80b18553528d93f8d704a695b04ec/pkg/sql/distsql_plan_changefeed.go#L320)):*
> since I already have to do rewriting on cdc side

I wonder if it's possible in the future to do almost all rewriting in the optimizer. E.g. you could specify your CDC rewrites as normalization rules. But this is definitely not needed for this PR.

Another advantage of showing only target columns is then you could rely on the optimizer for * expansion. But up to you (and feel free to save for the future)
___
*[`pkg/sql/distsql_plan_changefeed.go` line 325 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/85177#-NI8RDziEE6ZkUjP13EW:-NIDXBuC2Gm4IHi5TJAg:b-qe0bat) ([raw file](https://github.com/cockroachdb/cockroach/blob/f03a9a11a8e80b18553528d93f8d704a695b04ec/pkg/sql/distsql_plan_changefeed.go#L325)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

Good question... I'm not 100% sure on this; but given the fact that I only keep primary index, (and no subselects/joins/etc), I suspect there can only be 1 plan and so, I don't need stats.  I maybe wrong though.  Do you think these stats are needed here?
</blockquote></details>

No I think they are probably not needed now, but if in the future you want to consider secondary indexes you'll probably want to include stats.
___
*[`pkg/sql/opt/exec/execbuilder/builder.go` line 259 at r12](https://reviewable.io/reviews/cockroachdb/cockroach/85177#-NIDbbZF4qbLreuBnU-D:-NIDbbZG6CjVeRucss34:bgybt2h) ([raw file](https://github.com/cockroachdb/cockroach/blob/e2f40b68bc22caea8e376ecb1b88b64485211c09/pkg/sql/opt/exec/execbuilder/builder.go#L259)):*
> ```Go
> 
> func (b *Builder) wrapFunction(fnName string) tree.ResolvableFunctionReference {
> 	if b.semaCtx != nil && b.semaCtx.FunctionResolver != nil {
> ```

any reason we can't use the catalog function resolver here (like you did when folding)? Then we wouldn't need to plumb the semaCtx
___
*[`pkg/sql/opt/norm/fold_constants_funcs.go` line 684 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/85177#-NI8Ts4W5kog4MTfHvBM:-NIDXSfS7lkYzHRUMkI3:b64b3vz) ([raw file](https://github.com/cockroachdb/cockroach/blob/f03a9a11a8e80b18553528d93f8d704a695b04ec/pkg/sql/opt/norm/fold_constants_funcs.go#L684)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

I used to have this call.  However, I realized that having stable folds might be
beneficial since we have fair number of stable functions which could be folded (to_char, quote, etc, etc, etc).

Now, the only "problem" is that I chose to allow some of the standard functions, s.a. transaction_timestamp() -- and override those to return MVCC timestamp of the event (see functions.go in this PR).
Of course, these functions are stable, but they cannot be folded by optimizer since the value
depends on the data that we will feed as we receive events.

There were 2 choices: 
  1. Disallow transaction/statement_timestamp functions and force people to use CDC specific override (e.g. cdc_mvcc_timestamp() or some such).  It's a reasonable option; the downside is that e.g. transaction_timestamp() is well documented/understood function, and so, it might make sense to keep it because it keeps CDC expression very close to the regular SQL  select clause.
  2. Basically, this approach, that allows for escape hatch for some of the stable functions.

It's not too late to choose the first option, if you feel strongly against introducing this escape hatch.
Thoughts?
</blockquote></details>

We discussed this offline

**Review by miretskiy — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/85177)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @DrewKimball, @HonoreDB, @rytaft, and @yuzefovich)

___
*[`pkg/sql/distsql_plan_changefeed.go` line 87 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/85177#-NI8OWTz4UyL-9y-DCdI:-NIESDk4A6MJPgvJ1CZy:bfem5q7) ([raw file](https://github.com/cockroachdb/cockroach/blob/f03a9a11a8e80b18553528d93f8d704a695b04ec/pkg/sql/distsql_plan_changefeed.go#L87)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

Oh ok -- that's fine then. You could also do `false /* allowAutoCommit */`, but this is fine as-is
</blockquote></details>

I don't know why .. but I just dislike those inline /* */ style comments -- I think constants
are better.
___
*[`pkg/sql/distsql_plan_changefeed.go` line 320 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/85177#-NI8QKa03mSg2S7s62F3:-NIESK_214tpZtmcG5MM:b-aotnkp) ([raw file](https://github.com/cockroachdb/cockroach/blob/f03a9a11a8e80b18553528d93f8d704a695b04ec/pkg/sql/distsql_plan_changefeed.go#L320)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

> since I already have to do rewriting on cdc side

I wonder if it's possible in the future to do almost all rewriting in the optimizer. E.g. you could specify your CDC rewrites as normalization rules. But this is definitely not needed for this PR.

Another advantage of showing only target columns is then you could rely on the optimizer for * expansion. But up to you (and feel free to save for the future)
</blockquote></details>

Ack -- agree.  That's a very, very interesting idea!  Dealing with "*" was part of the complexity I had to tackle.
Idea bout a custom function/norm rule is rather neat.
___
*[`pkg/sql/opt/exec/execbuilder/builder.go` line 259 at r12](https://reviewable.io/reviews/cockroachdb/cockroach/85177#-NIDbbZF4qbLreuBnU-D:-NIES_CD0KMk914XI471:bxt8g7o) ([raw file](https://github.com/cockroachdb/cockroach/blob/e2f40b68bc22caea8e376ecb1b88b64485211c09/pkg/sql/opt/exec/execbuilder/builder.go#L259)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

any reason we can't use the catalog function resolver here (like you did when folding)? Then we wouldn't need to plumb the semaCtx
</blockquote></details>

That's a ... good question!   I think I did it so long ago... I don't think I realized that solution back then!
This is done now and the first commit to plumb semactx removed.
I had to add custom resolve implementation in cdcOptCatalog (to still provide access to CDC overrides), but no changes in execbuilder other than what you describe above.
Yay.

**Review by rytaft — APPROVED** [review]
:lgtm_strong: 

> Reviewed 17 of 17 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/85177#-:-NIExVv01YV2oqHpDmTX:b-uwkowd)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @DrewKimball, @HonoreDB, and @yuzefovich)

___
*[`pkg/sql/opt/exec/execbuilder/builder.go` line 259 at r12](https://reviewable.io/reviews/cockroachdb/cockroach/85177#-NIDbbZF4qbLreuBnU-D:-NIExKRK5h-QPfE4YDUt:b2bfcgi) ([raw file](https://github.com/cockroachdb/cockroach/blob/e2f40b68bc22caea8e376ecb1b88b64485211c09/pkg/sql/opt/exec/execbuilder/builder.go#L259)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

That's a ... good question!   I think I did it so long ago... I don't think I realized that solution back then!
This is done now and the first commit to plumb semactx removed.
I had to add custom resolve implementation in cdcOptCatalog (to still provide access to CDC overrides), but no changes in execbuilder other than what you describe above.
Yay.
</blockquote></details>

Hooray! :partying_face:

**Review by yuzefovich — COMMENTED** [review]
> Reviewed 21 of 34 files at r8, 1 of 3 files at r10, 2 of 4 files at r11, 1 of 3 files at r12, 6 of 17 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/85177)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @DrewKimball, @HonoreDB, @miretskiy, and @rytaft)

___
*[`pkg/ccl/changefeedccl/cdceval/expr_eval.go` line 109 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/85177#-NHa0l6X3NjL9V8eaEDI:-NIF39Oe1fxmKgA3WT8K:b-mjaa2s) ([raw file](https://github.com/cockroachdb/cockroach/blob/9b2726933a94d5f8f0b2d83cc53e065bef5dc519/pkg/ccl/changefeedccl/cdceval/expr_eval.go#L109)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

This used to be the case before I added ConsumerDone call as you requested; now, it seems this
may no longer be the case.  Still, I think returning error here is correct -- we will shutdown evaluator, and the whole flow, and then restart the flow (because all errors are now treated as retryable).
I augmented input initialization code with a  hopefully useful comment below:

Going to add a test around shutdown as well.

```
// The row channel created below will have exactly 1 sender (this evaluator).
// The buffer size parameter doesn't matter much, as long as it is greater
// than 0 to make sure that if the main context is cancelled and the flow
// exits, that we can still push data into the row channel without blocking,
// so that we notice cancellation request when we try to read the result of
// the evaluation.
const numSenders = 1
const bufSize = 16
var input execinfra.RowChannel
input.InitWithBufSizeAndNumSenders(inputTypes, bufSize, numSenders)
```


</blockquote></details>

Sorry, I responded below that we should probably remove that `ConsumerDone` call after all. Interested to hear how things will change once we do remove it.

My initial comment here was focused on whether it is an "assertion" or a "regular" error, I wasn't questioning whether it is an error.
___
*[`pkg/ccl/changefeedccl/cdceval/validation.go` line 238 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/85177#-NHa9eLA85lMbjtpxXby:-NIEzIOd535nEDPrn3bB:b-vs1prh) ([raw file](https://github.com/cockroachdb/cockroach/blob/9b2726933a94d5f8f0b2d83cc53e065bef5dc519/pkg/ccl/changefeedccl/cdceval/validation.go#L238)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

I reworked the code a bit.  No longer have boolean indicating if the expression should be normalized.
Now, when changefeed created, normalization step is done -- which rewrites the expression; and the rewritten expression gets written to jobs record.  Thereafter, there is no longer the need to normalize.
I also split the method into 2 helpers -- yes, there is a bit more repetition, but the code is better imo.
Let me know what you think.
</blockquote></details>

Looks good!
___
*[`pkg/sql/distsql_plan_changefeed.go` line 273 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/85177#-NH1kxi28jyv0mx0UgoX:-NIF0B1CCzE5MEe2pcPu:b-15rhr6) ([raw file](https://github.com/cockroachdb/cockroach/blob/0522b1e1839c98c7fb8a37376e16bde418d7fdc1/pkg/sql/distsql_plan_changefeed.go#L273)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

nit: the contract of `RowSource` says that unless we call `Next` until `Next` returns `nil, nil`, we must call `ConsumerDone`. I think it'd be cleaner to just do it here even if this might not be strictly necessary.
</blockquote></details>

Actually, on a second thought, it might be better to not call `ConsumerDone` here.

IIUC here is the structure of things: we have `kvEventToRowConsumer` which takes a single `kvevent.Event`, decodes KVs into `updatedRow`. This row is `Push`ed into `RowChannel` which is then read by `cdcValuesNode`. The structure of that flow is: `DistSQLReceiver <- (arbitrary DistSQL processors) <- planNodeToRowSource <- cdcValuesNode <- RowChannel`. Importantly, `RowChannel` is added as the "input to drain" by `planNodeToRowSource` (in `SetInput`), so `planNodeToRowSource` will call `ConsumerDone` or `ConsumerClosed` (depending on why the flow is being shutdown).

Thus, it is not necessary to do so in `cdcValuesNode.Close`. Furthermore, previously we had bugs around this behavior (#88964, fixed in 59b6f53a0ff8aed57a3b374349f1484a7cf69e34) because the processors are shutdown (and possibly released to their pools) at the end of `DistSQLPLanner.Run` whereas the `planNode` tree is closed later. I don't think there is a possibility of a bug here because this `RowChannel` is not reused in any way after the flow is cleaned up, but it might be better to keep things in sync between what `cdcValuesNode` and `rowSourceToPlanNode` do (because they are similar). It would probably be good to add a quick comment into `cdcValuesNode.Close` about this (similar to what we have in `rowSourceToPlanNode`).
___
*[`pkg/sql/walk.go` line 371 at r13](https://reviewable.io/reviews/cockroachdb/cockroach/85177#-NIF3vSNByyNKldGuUow:-NIF3vSNByyNKldGuUox:byce7uz) ([raw file](https://github.com/cockroachdb/cockroach/blob/47d9437108778be5e0615924f1ae05a66765f069/pkg/sql/walk.go#L371)):*
> ```Go
> 	reflect.TypeOf(&cancelQueriesNode{}):                       "cancel queries",
> 	reflect.TypeOf(&cancelSessionsNode{}):                      "cancel sessions",
> 	reflect.TypeOf(&cdcValuesNode{}):                           "wrapped streaming node",
> ```

Is it possible to `EXPLAIN` the plan for the transformation, before actually creating it?

**Review by miretskiy — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/85177)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @DrewKimball, @HonoreDB, @rytaft, and @yuzefovich)

___
*[`pkg/ccl/changefeedccl/cdceval/expr_eval.go` line 109 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/85177#-NHa0l6X3NjL9V8eaEDI:-NIFDkGi6VMtmOSCbBPm:b92etei) ([raw file](https://github.com/cockroachdb/cockroach/blob/9b2726933a94d5f8f0b2d83cc53e065bef5dc519/pkg/ccl/changefeedccl/cdceval/expr_eval.go#L109)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

Sorry, I responded below that we should probably remove that `ConsumerDone` call after all. Interested to hear how things will change once we do remove it.

My initial comment here was focused on whether it is an "assertion" or a "regular" error, I wasn't questioning whether it is an error.
</blockquote></details>

You were right re assertion failure -- I changed that.  And I've removed consumer done call.  Everything still worked after I removed this call.  I just think that this whole operation is so tightly controlled by cdc eval -- 1 row pushed, 1 row read -- that the shutdown issues probably not going to happen (famous words :) )
___
*[`pkg/ccl/changefeedccl/cdceval/validation.go` line 238 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/85177#-NHa9eLA85lMbjtpxXby:-NIFEANh-D2RJkFw-qR1:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/9b2726933a94d5f8f0b2d83cc53e065bef5dc519/pkg/ccl/changefeedccl/cdceval/validation.go#L238)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

Looks good!
</blockquote></details>

Done.
___
*[`pkg/sql/distsql_plan_changefeed.go` line 273 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/85177#-NH1kxi28jyv0mx0UgoX:-NIFEkqB1SqGJB59aMqH:bc4o624) ([raw file](https://github.com/cockroachdb/cockroach/blob/0522b1e1839c98c7fb8a37376e16bde418d7fdc1/pkg/sql/distsql_plan_changefeed.go#L273)):*
> RowChannel is added as the "input to drain" by planNodeToRowSource (in SetInput), so planNodeToRowSource will call ConsumerDone or ConsumerClosed (depending on why the flow is being shutdown).

Comment added, and I "stole" a good portion of your excellent explanation above to put that into the comment.
___
*[`pkg/sql/walk.go` line 371 at r13](https://reviewable.io/reviews/cockroachdb/cockroach/85177#-NIF3vSNByyNKldGuUow:-NIFEugA38bMEZtI1rTx:b-x6i18k) ([raw file](https://github.com/cockroachdb/cockroach/blob/47d9437108778be5e0615924f1ae05a66765f069/pkg/sql/walk.go#L371)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

Is it possible to `EXPLAIN` the plan for the transformation, before actually creating it?
</blockquote></details>

I absolutely have this on my todo.  Eventually, we do want to support explain changefeed.

**Review by rytaft — APPROVED** [review]
> Reviewed 15 of 15 files at r14, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/85177)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @DrewKimball, @HonoreDB, and @yuzefovich)

File: pkg/ccl/changefeedccl/cdceval/expr_eval_test.go [hunk 1]
```diff
@@ -290,57 +330,84 @@ CREATE TABLE foo (
...
 		{
-			testName:   "main/btrim_wrong_type",
+			testName:   "main/trigram",
 			familyName: "main",
 			actions: []string{
-				"INSERT INTO foo (a, b) VALUES (1, '   spaced out      ')",
+				"INSERT INTO foo (a, b) VALUES (1,  'hello')",
 			},
-			predicate: "SELECT btrim(a) FROM _",
+			stmt: "SELECT a,  b % 'hel' AS trigram FROM foo",
```
Comment (HonoreDB) [inline pkg/ccl/changefeedccl/cdceval/expr_eval_test.go:364]: The current bug with string % is that it always returns true when the expression is being evaluated in a job, because it depends on a session variable that defaults to 0.3 but isn't being set so it's using a similarity threshold of 0. I think this PR probably doesn't fix this, so I think either remove this test or (if I'm wrong) add a test case where it's false using an enterprise feed like environment.

**Review by HonoreDB — APPROVED** [review]

**Review by yuzefovich — APPROVED** [review]
> Reviewed 2 of 34 files at r8, 1 of 4 files at r11, 1 of 3 files at r12, 11 of 17 files at r13, 15 of 15 files at r14, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/85177)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @DrewKimball, @HonoreDB, @miretskiy, and @rytaft)

File: pkg/ccl/changefeedccl/cdceval/expr_eval_test.go (hunk 1 above)
Comment (miretskiy) [reply pkg/ccl/changefeedccl/cdceval/expr_eval_test.go:364]: Ack; going to disable the test.

**Comment by shermanCRL** [comment]
Addresses https://github.com/cockroachdb/cockroach/issues/31214
