### PR TITLE
sql: restart rangefeed on descriptor table on error

### LINKED ISSUE #118625: ccl/backupccl: TestRestoreAsOfSystemTimeGCBounds failed
ccl/backupccl.TestRestoreAsOfSystemTimeGCBounds [failed](https://tanzanite.cluster.engflow.com/invocations/default/e28999f8-4d51-4e92-b3d9-a9e402595828?testReportRun=30&testReportShard=1&testReportAttempt=1#targets-Ly9wa2cvY2NsL2JhY2t1cGNjbDpiYWNrdXBjY2xfdGVzdA==) on master @ [fce4d4723519bc4ca6e9ef5da0ae19960c84752c](https://github.com/cockroachdb/cockroach/commits/fce4d4723519bc4ca6e9ef5da0ae19960c84752c):

Fatal error:

```
panic: test timed out after 14m57s
running tests:
	TestRestoreAsOfSystemTimeGCBounds (14m55s)

```
Stack: 

```
goroutine 559425 [running]:
testing.(*M).startAlarm.func1()
	GOROOT/src/testing/testing.go:2259 +0x3b9
created by time.goFunc
	GOROOT/src/time/sleep.go:176 +0x2d
```
<details><summary>Log preceding fatal error</summary>
<p>

```
=== RUN   TestRestoreAsOfSystemTimeGCBounds
    test_log_scope.go:170: test logs captured to: outputs.zip/logTestRestoreAsOfSystemTimeGCBounds3423607260
    test_log_scope.go:81: use -show-logs to present logs inline
    test_server_shim.go:157: automatically injected a shared process virtual cluster under test; see comment at top of test_server_shim.go for details.
```
</p>
</details>

Parameters:
 - <code>attempt=1</code>
 - <code>run=30</code>
 - <code>shard=1</code>
<details><summary>Help</summary>
<p>

See also: [How To Investigate a Go Test Failure \(internal\)](https://cockroachlabs.atlassian.net/l/c/HgfXfJgM)
</p>
</details>
/cc @cockroachdb/disaster-recovery
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*TestRestoreAsOfSystemTimeGCBounds.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)
</sub>

Jira issue: CRDB-35813

### PR DESCRIPTION
**Pull request by stevendanna**
Previously, if the rangefeed encountered a terminal error, it would remain offline. In at least one test, this led in our version check on drop to hang forever since it is the rangefeed that is responsible for driving the purging of leases on drop.

Now, we restart the feed.

Fixes #118625.

Release note: None

### CODE REVIEW

File: pkg/sql/catalog/lease/lease.go [hunk 1]
```diff
@@ -1655,14 +1668,24 @@ func (m *Manager) handleRangeFeedAvailability(ctx context.Context) {
...
+	defer m.mu.Unlock()
+	m.restartLeasingRangeFeedLocked(ctx)
+}
+
+func (m *Manager) restartLeasingRangeFeedLocked(ctx context.Context) {
+	log.Warning(ctx, "attempting restart of leasing range feed")
+	// Attempt a range feed restart if it has been down too long.
+	m.watchForUpdates(ctx)
+	// Track when the last restart occurred.
+	m.mu.rangeFeedIsUnavailableAt = timeutil.Now()
```
Comment (stevendanna) [inline pkg/sql/catalog/lease/lease.go:1686]: Seems to me like we we should also be resetting the number of checkpoints but the existing code didn't.

**Review by fqazi — APPROVED** [review]
@stevendanna Nice find! We should also backport this to 24.1. The original fix was aimed at a weird thing we saw where the rangefeed hung without any error, but we should also restart when errors are reported back.

:lgtm_strong: 

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/128577#-:-O3lvsT18kpzN_ec46P3:bz49ks7)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @stevendanna)

___
*[`pkg/sql/catalog/lease/lease.go` line 1686 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/128577#gh-1709337524:-O3lvfyV2OAQywt3Muah:bu550au) ([raw file](https://github.com/cockroachdb/cockroach/blob/13b0e2de2f51cc5b522e7e8f3b05dff543333208/pkg/sql/catalog/lease/lease.go#L1686)):*
<details><summary><i>Previously, stevendanna (Steven Danna) wrote…</i></summary><blockquote>

Seems to me like we we should also be resetting the number of checkpoints but the existing code didn't.
</blockquote></details>

I think the assumption in the original logic was that the range feed wasn't seeing any checkpoints for a long time, so it would be zero. We can just reset them again here.

**Comment by stevendanna** [comment]
bors r=fqazi
