### PR TITLE
sql/pgwire: proper error handling in COPY FROM

### LINKED ISSUE #16393: sql/pgwire: wrong protocol state after COPY FROM error
Our pgwire implementation seems to get out of sync with `psql` when a `COPY FROM` operation returns an error half way through:

```
test=> create table z(a int);
CREATE TABLE
test=> copy z(a) from stdin;
Enter data to be copied followed by a newline.
End with a backslash and a period on a line by itself.
>> not an int
>> \.
ERROR:  could not parse 'not an int' as type int: strconv.ParseInt: parsing "not an int": invalid syntax
message type 0x5a arrived from server while idle
```

In that example, the connection seems to stay in sync after receiving the unexpected message. In this next example, the connection gets hopelessly confused until I close and re-open `psql`:

```
test=> copy z(a) from stdin;
Enter data to be copied followed by a newline.
End with a backslash and a period on a line by itself.
>> 1 2
>> \.
ERROR:  could not parse '1 2' as type int: strconv.ParseInt: parsing "1 2": invalid syntax
test=> select * from z;
test=> ;
 a
---
(0 rows)

test=> select * from z;
test=> ;
 a
---
(0 rows)
```

Notice that the results from each `select` don't return until i send another `;` to the server.

### PR DESCRIPTION
**Pull request by jordanlewis**
Previously, there was a small bug in the pgwire implementation for `COPY
FROM` that would cause pgwire connections to get into a bad state if a
backend error was encountered during the operation.

Fixes #16393.

Obviously, this needs a test - not really sure the best way to test it though. Maybe a new expect test?

### CODE REVIEW

**Comment by mjibson** [comment]
Code LGTM, but I agree this needs a test. I think your idea of an expect test is best.

**Comment by jordanlewis** [comment]
PTAL added a test

**Comment by jordanlewis** [comment]
Gentle ping @mjibson

**Comment by mjibson** [comment]
Sorry, forgot to hit the submit button.

**Comment by jordanlewis** [comment]
Done - TFTR

**Comment by jordanlewis** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[pkg/acceptance/psql_test.go, line 83 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16398#-Km8YmWsXywu1QOKmTMS-r1-83:-KmHPVJUlidr7uHr32CE:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/db06606e7e8cc7a8671cf0da9a8b988c65ce55a0/pkg/acceptance/psql_test.go#L83)):*
<details><summary><i>Previously, mjibson (Matt Jibson) wrote…</i></summary><blockquote>

Add a `SELECT` and grep to verify that the rope row wasn't inserted.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16398)*

File: pkg/sql/pgwire/v3.go [hunk 1]
```diff
@@ -407,6 +413,9 @@ func (c *v3Conn) serve(ctx context.Context, draining func() bool, reserved mon.B
 				return err
 			}
 		}
+		if c.doNotSendReadyForQuery {
```
Comment (knz) [inline pkg/sql/pgwire/v3.go]: The assignment here should be unconditional.
