### PR TITLE
roachtest: increase flexibility of profileTopStatements

### LINKED ISSUE #133522: roachtest: perturbation/metamorphic/elasticWorkload failed
roachtest.perturbation/metamorphic/elasticWorkload [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/17460847?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/17460847?buildTab=artifacts#/perturbation/metamorphic/elasticWorkload) on master @ [7495c0390f93478bc0f961285f41cd4ec85a6a76](https://github.com/cockroachdb/cockroach/commits/7495c0390f93478bc0f961285f41cd4ec85a6a76):

```
(assertions.go:363).Fail: 
	Error Trace:	github.com/cockroachdb/cockroach/pkg/cmd/roachtest/tests/admission_control_latency.go:903
	            				main/pkg/cmd/roachtest/test_runner.go:1287
	            				src/runtime/asm_amd64.s:1695
	Error:      	Should be true
	Test:       	perturbation/metamorphic/elasticWorkload
	Messages:   	FAILURE: follower-read  : Increase 5.9960 > 5.0000 BASE: 7.666466ms SCORE: 45.967942ms
	            	
	            	FAILURE: read           : Increase 6.0530 > 5.0000 BASE: 7.64883ms SCORE: 46.298221ms
(require.go:1950).True: FailNow called
test artifacts and logs in: /artifacts/perturbation/metamorphic/elasticWorkload/run_1
```

Parameters:
 - <code>ROACHTEST_arch=amd64</code>
 - <code>ROACHTEST_cloud=gce</code>
 - <code>ROACHTEST_coverageBuild=false</code>
 - <code>ROACHTEST_cpu=16</code>
 - <code>ROACHTEST_encrypted=false</code>
 - <code>ROACHTEST_fs=ext4</code>
 - <code>ROACHTEST_localSSD=true</code>
 - <code>ROACHTEST_runtimeAssertionsBuild=false</code>
 - <code>ROACHTEST_ssd=1</code>
<details><summary>Help</summary>
<p>

See: [roachtest README](https://github.com/cockroachdb/cockroach/blob/master/pkg/cmd/roachtest/README.md)

See: [How To Investigate \(internal\)](https://cockroachlabs.atlassian.net/l/c/SSSBr8c7)

See: [Grafana](https://go.crdb.dev/roachtest-grafana/teamcity-17460847/perturbation-metamorphic-elasticworkload/1729959700813/1729961913368)

</p>
</details>
/cc @cockroachdb/kv-triage
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*perturbation/metamorphic/elasticWorkload.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/bazci/githubpost/issues)

</sub>

Jira issue: CRDB-43658

### PR DESCRIPTION
**Pull request by andrewbaptist**
Previously the function profileTopStatements had a number of hard-coded constants. This change adds the ability to modify the paramaters to it by adding profile options. Additionally the
perturbation/metamorphic/elasticWorkload test is changed to increase the min latency for profiling to 100ms. This will prevent excessive profiles from being collected.

Fixes: #133522

Release note: None

### CODE REVIEW

**Comment by andrewbaptist** [comment]
@pav-kv with Austen out can you take a look at this. Thanks!

File: pkg/cmd/roachtest/tests/util.go [hunk 1]
```diff
@@ -155,49 +205,44 @@ func profileTopStatements(
...
-	minNumExpectedStmts := 1000
-
-	// minimumLatency is the minimum P99 latency in seconds. Anything lower than
-	// this is rounded up to this value.
-	minimumLatency := 0.001
-
-	// multipleFromP99 is the multiple of the P99 latency that the statement
-	// must exceed in order to be collected.
-	multipleFromP99 := 10
+	// The default values for the profile options trace statements over 30ms.
```
Comment (pav-kv) [inline pkg/cmd/roachtest/tests/util.go:208]: 50ms?

**Review by pav-kv — APPROVED** [review]

**Comment by andrewbaptist** [comment]
TFTR!

bors r=pav-kv
