### PR TITLE
util/retry: deflake TestRetryExceedsMaxBackoff

### LINKED ISSUE #5209: stress: failed test in cockroach/util/retry/retry.test: TestRetryExceedsMaxBackoff
Binary: cockroach/static-tests.tar.gz sha: https://github.com/cockroachdb/cockroach/commits/b1125fa08614aa770703b67a18dfb9856e2cd4ad

Stress build found a failed test:

```
=== RUN   TestRetryExceedsMaxBackoff
--- FAIL: TestRetryExceedsMaxBackoff (1.00s)
	retry_test.go:44: expected retry loop to run for 20ms, actually ran for 1.00013201s
```

Run Details:

```
6485 runs so far, 0 failures, over 5s
12793 runs so far, 0 failures, over 10s
18870 runs so far, 0 failures, over 15s
24458 runs so far, 0 failures, over 20s
29262 runs so far, 0 failures, over 25s
34010 runs so far, 0 failures, over 30s
38666 runs so far, 0 failures, over 35s
43233 runs so far, 0 failures, over 40s
47710 runs so far, 0 failures, over 45s
52148 runs so far, 0 failures, over 50s
56451 runs so far, 0 failures, over 55s
60675 runs so far, 0 failures, over 1m0s
64817 runs so far, 0 failures, over 1m5s
68960 runs so far, 0 failures, over 1m10s
72934 runs so far, 0 failures, over 1m15s
76099 runs so far, 0 failures, over 1m20s
79977 runs so far, 0 failures, over 1m25s
83575 runs so far, 0 failures, over 1m31s
83576 runs completed, 1 failures, over 1m31s
FAIL
```
Please assign, take a look and update the issue accordingly.

### PR DESCRIPTION
**Pull request by petermattis**
Remove usage of time.After from the test and only test the computation
of the backoff durations.

Fixes #5209.

---

This change is [Review on Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/5247)

### CODE REVIEW

**Comment by bdarnell** [comment]
LGTM

File: util/retry/retry_test.go [hunk 1]
```diff
@@ -19,35 +19,24 @@ package retry
...
-		t.Errorf("expected retry loop to run for %s, actually ran for %s", expDuration, duration)
+		MaxBackoff:     time.Microsecond * 100,
+		Multiplier:     2,
+		MaxRetries:     10,
 	}
 
-	if expAttempts := opts.MaxRetries + 1; attempts != expAttempts {
-		t.Errorf("expected %d attempts, got %d attempts", expAttempts, attempts)
+	r := Start(opts)
+	r.opts.RandomizationFactor = 0
```
Comment (bdarnell) [inline util/retry/retry_test.go]: Why change this after starting instead of putting it in `opts` to begin with?

Comment (petermattis) [inline util/retry/retry_test.go]: Because `Start` treats `r.opts.RandomizationFactor == 0` as requesting the default randomization factor of `0.15`. https://github.com/cockroachdb/cockroach/blob/master/util/retry/retry.go#L52-L54

Comment (bdarnell) [inline util/retry/retry_test.go]: Ah. That's unfortunate, especially since this appears to be the only place in which we actually use a non-default randomization factor.

Comment (petermattis) [inline util/retry/retry_test.go]: Yeah. I could remove this and check that the backoff duration is within +/- 15% of the expected value, but that seems like I'd just be duplicating the code in `Retry.retryIn()`. I don't think this is worth that kind of effort.
