### PR TITLE
gossip,testcluster: Use more loopback IP addresses in tests

### LINKED ISSUE #9016: stress: failed test in cockroach/testutils/testcluster/testcluster.test: TestStopServer
Binary: cockroach/static-tests.tar.gz sha: https://github.com/cockroachdb/cockroach/commits/613e0865daf0bed9404170caec18db57362112e7

Stress build found a failed test:

```
=== RUN   TestStopServer
I160901 05:26:46.387931 1709 storage/engine/rocksdb.go:354  opening in memory rocksdb instance
I160901 05:26:46.391245 1709 gossip/gossip.go:230  [n?] initial resolvers: []
W160901 05:26:46.394072 1709 gossip/gossip.go:1041  [n?] no resolvers found; use --join to specify a connected node
W160901 05:26:46.405792 1709 server/status/runtime.go:109  Could not parse build timestamp: parsing time "" as "2006/01/02 15:04:05": cannot parse "" as "2006"
I160901 05:26:46.406440 1709 server/node.go:413  [n?] store store=0:0 not bootstrapped
I160901 05:26:46.408579 1841 storage/replica_trigger.go:308  new range lease replica {1 1 1} 1970-01-01 00:00:00 +0000 UTC 409085h26m55.408102132s following replica {0 0 0} 1970-01-01 00:00:00 +0000 UTC 0s [physicalTime=2016-09-01 05:26:46.408547354 +0000 UTC]
I160901 05:26:46.409164 1709 server/node.go:345  [n?] **** cluster {c49e4249-1ee8-4ab2-ab32-d8ed3f39596a} has been created
I160901 05:26:46.409190 1709 server/node.go:346  [n?] **** add additional nodes by specifying --join=127.0.0.1:37339
I160901 05:26:46.409424 1709 gossip/gossip.go:264  [n?] NodeID set to 1
I160901 05:26:46.409898 1709 storage/store.go:980  [n?] store=1:1: failed initial metrics computation: store=1:1: system config not yet available
I160901 05:26:46.409922 1709 server/node.go:426  [n?] initialized store store=1:1: {Capacity:536870912 Available:536870912 RangeCount:0}
I160901 05:26:46.409959 1709 server/node.go:318  [n?] node ID 1 initialized
I160901 05:26:46.409996 1709 gossip/gossip.go:278  [n?] NodeDescriptor set to node_id:1 address:<network_field:"tcp" address_field:"127.0.0.1:37339" > attrs:<> 
I160901 05:26:46.410041 1709 storage/stores.go:313  read 0 node addresses from persistent storage
I160901 05:26:46.410083 1709 server/node.go:554  [n?] connecting to gossip network to verify cluster ID...
I160901 05:26:46.410213 1709 server/node.go:575  [n?] node connected via gossip and verified as part of cluster {"c49e4249-1ee8-4ab2-ab32-d8ed3f39596a"}
I160901 05:26:46.410232 1709 server/node.go:364  [n?] node=1: started with [[]=] engine(s) and attributes []
I160901 05:26:46.410251 1709 server/server.go:488  [n1] starting https server at 127.0.0.1:41730
I160901 05:26:46.410261 1709 server/server.go:489  [n1] starting grpc/postgres server at 127.0.0.1:37339
I160901 05:26:46.410325 1890 storage/split_queue.go:99  splitting store=1:1 1{/Min-/Max} at keys [/Table/11/0 /Table/12/0 /Table/13/0 /Table/14/0]
I160901 05:26:46.410476 1884 sql/event_log.go:109  [n1] Event: "node_join", target: 1, info: {Descriptor:{NodeID:1 Address:{NetworkField:tcp AddressField:127.0.0.1:37339} Attrs:} ClusterID:{UUID:c49e4249-1ee8-4ab2-ab32-d8ed3f39596a} StartedAt:1472707606410217759}
I160901 05:26:46.412638 1884 sql/event_log.go:109  [n1] Event: "node_join", target: 1, info: {Descriptor:{NodeID:1 Address:{NetworkField:tcp AddressField:127.0.0.1:37339} Attrs:} ClusterID:{UUID:c49e4249-1ee8-4ab2-ab32-d8ed3f39596a} StartedAt:1472707606410217759}
I160901 05:26:46.414050 1890 storage/replica_command.go:2213  [n1,s1,r1{/Min-/Max}] initiating a split of this range at key /Table/11
E160901 05:26:46.424775 1892 storage/queue.go:516  [replicate] (purgatory) on store=1:1 1{/Min-/Table/11}: 0 of 1 store with an attribute matching []; likely not enough nodes in cluster
E160901 05:26:46.424868 1923 storage/queue.go:516  [replicate] (purgatory) on store=1:1 1{/Min-/Table/11}: 0 of 1 store with an attribute matching []; likely not enough nodes in cluster
I160901 05:26:46.425443 1890 storage/replica_command.go:2213  [n1,s1,r2{/Table/11-/Max}] initiating a split of this range at key /Table/12
E160901 05:26:46.429894 1892 storage/queue.go:516  [replicate] (purgatory) on store=1:1 2{/Table/11-/Table/12}: 0 of 1 store with an attribute matching []; likely not enough nodes in cluster
I160901 05:26:46.430394 1890 storage/replica_command.go:2213  [n1,s1,r3{/Table/12-/Max}] initiating a split of this range at key /Table/13
W160901 05:26:46.430633 1900 storage/intent_resolver.go:344  could not GC completed transaction: end key /Local/Range/"\x93"/"rdsc\x00" must be greater than start /Local/Range/"\x93"/RangeDescriptor
E160901 05:26:46.435493 1892 storage/queue.go:516  [replicate] (purgatory) on store=1:1 3{/Table/12-/Table/13}: 0 of 1 store with an attribute matching []; likely not enough nodes in cluster
I160901 05:26:46.436560 1890 storage/replica_command.go:2213  [n1,s1,r4{/Table/13-/Max}] initiating a split of this range at key /Table/14
W160901 05:26:46.437141 1902 storage/intent_resolver.go:344  could not GC completed transaction: end key /Local/Range/"\x94"/"rdsc\x00" must be greater than start /Local/Range/"\x94"/RangeDescriptor
E160901 05:26:46.442554 1892 storage/queue.go:516  [replicate] (purgatory) on store=1:1 4{/Table/13-/Table/14}: 0 of 1 store with an attribute matching []; likely not enough nodes in cluster
E160901 05:26:46.443779 1892 storage/queue.go:516  [replicate] (purgatory) on store=1:1 5{/Table/14-/Max}: 0 of 1 store with an attribute matching []; likely not enough nodes in cluster
W160901 05:26:46.443816 1904 storage/intent_resolver.go:344  could not GC completed transaction: end key /Local/Range/"\x95"/"rdsc\x00" must be greater than start /Local/Range/"\x95"/RangeDescriptor
I160901 05:26:46.475125 1709 storage/engine/rocksdb.go:354  opening in memory rocksdb instance
I160901 05:26:46.477912 1709 gossip/gossip.go:230  [n?] initial resolvers: [%!s(*resolver.socketResolver=&{tcp 127.0.0.1:37339})]
W160901 05:26:46.477949 1709 gossip/gossip.go:1043  [n?] no incoming or outgoing connections
W160901 05:26:46.478385 1709 server/status/runtime.go:109  Could not parse build timestamp: parsing time "" as "2006/01/02 15:04:05": cannot parse "" as "2006"
I160901 05:26:46.478829 1709 server/node.go:413  [n?] store store=0:0 not bootstrapped
I160901 05:26:46.478853 1709 storage/stores.go:313  read 0 node addresses from persistent storage
I160901 05:26:46.478875 1709 server/node.go:554  [n?] connecting to gossip network to verify cluster ID...
I160901 05:26:46.499584 1963 gossip/client.go:125  [n?] node 0: started gossip client to 127.0.0.1:37339
I160901 05:26:46.500132 1942 gossip/server.go:274  [n1] node 1: received gossip from unknown node
I160901 05:26:46.500475 1709 server/node.go:575  [n?] node connected via gossip and verified as part of cluster {"c49e4249-1ee8-4ab2-ab32-d8ed3f39596a"}
I160901 05:26:46.500795 1943 storage/stores.go:328  wrote 1 node addresses to persistent storage
I160901 05:26:46.502558 1709 kv/dist_sender.go:344  [n?] unable to determine this node's attributes for replica selection; node is most likely bootstrapping
I160901 05:26:46.503419 1709 server/node.go:312  [n?] new node allocated ID 2
I160901 05:26:46.503447 1709 gossip/gossip.go:264  [n?] NodeID set to 2
I160901 05:26:46.503511 1709 gossip/gossip.go:278  [n?] NodeDescriptor set to node_id:2 address:<network_field:"tcp" address_field:"127.0.0.1:37166" > attrs:<> 
I160901 05:26:46.503582 1709 server/node.go:364  [n?] node=2: started with [[]=] engine(s) and attributes []
I160901 05:26:46.503618 1709 server/server.go:488  [n2] starting https server at 127.0.0.1:36307
I160901 05:26:46.503638 1709 server/server.go:489  [n2] starting grpc/postgres server at 127.0.0.1:37166
I160901 05:26:46.504588 2005 sql/event_log.go:109  [n2] Event: "node_join", target: 2, info: {Descriptor:{NodeID:2 Address:{NetworkField:tcp AddressField:127.0.0.1:37166} Attrs:} ClusterID:{UUID:c49e4249-1ee8-4ab2-ab32-d8ed3f39596a} StartedAt:1472707606503561500}
I160901 05:26:46.538553 1990 storage/stores.go:328  wrote 1 node addresses to persistent storage
I160901 05:26:46.548577 1709 storage/engine/rocksdb.go:354  opening in memory rocksdb instance
I160901 05:26:46.549561 2002 gossip/gossip.go:264  [n2] NodeID set to 2
I160901 05:26:46.549705 2002 server/node.go:535  [n2] bootstrapped store store=2:2
I160901 05:26:46.559785 1709 gossip/gossip.go:230  [n?] initial resolvers: [%!s(*resolver.socketResolver=&{tcp 127.0.0.1:37339})]
W160901 05:26:46.559817 1709 gossip/gossip.go:1043  [n?] no incoming or outgoing connections
W160901 05:26:46.560247 1709 server/status/runtime.go:109  Could not parse build timestamp: parsing time "" as "2006/01/02 15:04:05": cannot parse "" as "2006"
I160901 05:26:46.560822 1709 server/node.go:413  [n?] store store=0:0 not bootstrapped
I160901 05:26:46.560844 1709 storage/stores.go:313  read 0 node addresses from persistent storage
I160901 05:26:46.560863 1709 server/node.go:554  [n?] connecting to gossip network to verify cluster ID...
I160901 05:26:46.582518 2102 gossip/client.go:125  [n?] node 0: started gossip client to 127.0.0.1:37339
I160901 05:26:46.583183 2020 gossip/server.go:274  [n1] node 1: received gossip from unknown node
I160901 05:26:46.587780 1709 server/node.go:575  [n?] node connected via gossip and verified as part of cluster {"c49e4249-1ee8-4ab2-ab32-d8ed3f39596a"}
I160901 05:26:46.587889 1249 storage/stores.go:328  wrote 1 node addresses to persistent storage
I160901 05:26:46.587938 1249 storage/stores.go:328  wrote 2 node addresses to persistent storage
I160901 05:26:46.589123 1980 storage/replica_raftstorage.go:492  generated snapshot for range 1 at index 36 in 1.718608ms. encoded size=118757, 417 KV pairs, 26 log entries
I160901 05:26:46.590943 2124 storage/replica_raftstorage.go:631  store=2:2 1{/Min-/Min}: with replicaID [?], applying preemptive snapshot at index 36 (encoded size=118757, 417 KV pairs, 26 log entries)
I160901 05:26:46.592639 2124 storage/replica_raftstorage.go:634  store=2:2 1{/Min-/Table/11}: with replicaID [?], applied preemptive snapshot in 0.002s
I160901 05:26:46.598946 1709 kv/dist_sender.go:344  [n?] unable to determine this node's attributes for replica selection; node is most likely bootstrapping
I160901 05:26:46.599377 1923 storage/replica_command.go:3073  change replicas of 1: read existing descriptor range_id:1 start_key:"" end_key:"\223" replicas:<node_id:1 store_id:1 replica_id:1 > next_replica_id:2 
I160901 05:26:46.600005 1709 server/node.go:312  [n?] new node allocated ID 3
I160901 05:26:46.600024 1709 gossip/gossip.go:264  [n?] NodeID set to 3
I160901 05:26:46.600055 1709 gossip/gossip.go:278  [n?] NodeDescriptor set to node_id:3 address:<network_field:"tcp" address_field:"127.0.0.1:40560" > attrs:<> 
I160901 05:26:46.600131 1709 server/node.go:364  [n?] node=3: started with [[]=] engine(s) and attributes []
I160901 05:26:46.600148 1709 server/server.go:488  [n3] starting https server at 127.0.0.1:33735
I160901 05:26:46.600158 1709 server/server.go:489  [n3] starting grpc/postgres server at 127.0.0.1:40560
I160901 05:26:46.601118 2138 sql/event_log.go:109  [n3] Event: "node_join", target: 3, info: {Descriptor:{NodeID:3 Address:{NetworkField:tcp AddressField:127.0.0.1:40560} Attrs:} ClusterID:{UUID:c49e4249-1ee8-4ab2-ab32-d8ed3f39596a} StartedAt:1472707606600116408}
I160901 05:26:46.605516 1916 storage/stores.go:328  wrote 2 node addresses to persistent storage
I160901 05:26:46.605972 1917 storage/stores.go:328  wrote 2 node addresses to persistent storage
I160901 05:26:46.620081 1923 storage/replica.go:1551  [n1,s1,r1{/Min-/Table/11}] proposing ADD_REPLICA {NodeID:2 StoreID:2 ReplicaID:2} for range 1: [{NodeID:1 StoreID:1 ReplicaID:1} {NodeID:2 StoreID:2 ReplicaID:2}]
I160901 05:26:46.620784 2135 gossip/gossip.go:264  [n3] NodeID set to 3
I160901 05:26:46.620971 2135 server/node.go:535  [n3] bootstrapped store store=3:3
W160901 05:26:46.623617 2088 storage/intent_resolver.go:344  could not GC completed transaction: end key /Local/Range/""/"rdsc\x00" must be greater than start /Local/Range/""/RangeDescriptor
I160901 05:26:46.624143 2230 storage/replica_raftstorage.go:492  generated snapshot for range 2 at index 14 in 126.688µs. encoded size=2678, 10 KV pairs, 4 log entries
I160901 05:26:46.624804 2129 storage/replica_raftstorage.go:631  store=2:2 2{/Min-/Min}: with replicaID [?], applying preemptive snapshot at index 14 (encoded size=2678, 10 KV pairs, 4 log entries)
I160901 05:26:46.625080 2129 storage/replica_raftstorage.go:634  store=2:2 2{/Table/11-/Table/12}: with replicaID [?], applied preemptive snapshot in 0.000s
I160901 05:26:46.625573 1923 storage/replica_command.go:3073  change replicas of 2: read existing descriptor range_id:2 start_key:"\223" end_key:"\224" replicas:<node_id:1 store_id:1 replica_id:1 > next_replica_id:2 
I160901 05:26:46.625656 2244 storage/raft_transport.go:378  raft transport stream to node 1 established
I160901 05:26:46.628718 2231 storage/replica_trigger.go:458  unable to gossip first range; hasLease=false, err=<nil>
I160901 05:26:46.630579 1923 storage/replica.go:1551  [n1,s1,r2{/Table/11-/Table/12}] proposing ADD_REPLICA {NodeID:2 StoreID:2 ReplicaID:2} for range 2: [{NodeID:1 StoreID:1 ReplicaID:1} {NodeID:2 StoreID:2 ReplicaID:2}]
W160901 05:26:46.633512 2081 storage/intent_resolver.go:344  could not GC completed transaction: end key /Local/Range/"\x93"/"rdsc\x00" must be greater than start /Local/Range/"\x93"/RangeDescriptor
I160901 05:26:46.663490 2265 storage/replica_raftstorage.go:492  generated snapshot for range 3 at index 18 in 199.1µs. encoded size=6682, 25 KV pairs, 8 log entries
I160901 05:26:46.664065 1921 storage/replica_raftstorage.go:631  store=3:3 3{/Min-/Min}: with replicaID [?], applying preemptive snapshot at index 18 (encoded size=6682, 25 KV pairs, 8 log entries)
I160901 05:26:46.664787 1921 storage/replica_raftstorage.go:634  store=3:3 3{/Table/12-/Table/13}: with replicaID [?], applied preemptive snapshot in 0.001s
I160901 05:26:46.665251 1923 storage/replica_command.go:3073  change replicas of 3: read existing descriptor range_id:3 start_key:"\224" end_key:"\225" replicas:<node_id:1 store_id:1 replica_id:1 > next_replica_id:2 
I160901 05:26:46.668334 1923 storage/replica.go:1551  [n1,s1,r3{/Table/12-/Table/13}] proposing ADD_REPLICA {NodeID:3 StoreID:3 ReplicaID:2} for range 3: [{NodeID:1 StoreID:1 ReplicaID:1} {NodeID:3 StoreID:3 ReplicaID:2}]
I160901 05:26:46.670166 2279 storage/replica_raftstorage.go:492  generated snapshot for range 4 at index 19 in 581.682µs. encoded size=10311, 54 KV pairs, 9 log entries
W160901 05:26:46.670413 2278 storage/intent_resolver.go:344  could not GC completed transaction: end key /Local/Range/"\x94"/"rdsc\x00" must be greater than start /Local/Range/"\x94"/RangeDescriptor
I160901 05:26:46.670683 2267 storage/replica_raftstorage.go:631  store=3:3 4{/Min-/Min}: with replicaID [?], applying preemptive snapshot at index 19 (encoded size=10311, 54 KV pairs, 9 log entries)
I160901 05:26:46.670961 2267 storage/replica_raftstorage.go:634  store=3:3 4{/Table/13-/Table/14}: with replicaID [?], applied preemptive snapshot in 0.000s
I160901 05:26:46.671376 1923 storage/replica_command.go:3073  change replicas of 4: read existing descriptor range_id:4 start_key:"\225" end_key:"\226" replicas:<node_id:1 store_id:1 replica_id:1 > next_replica_id:2 
I160901 05:26:46.674314 1923 storage/replica.go:1551  [n1,s1,r4{/Table/13-/Table/14}] proposing ADD_REPLICA {NodeID:3 StoreID:3 ReplicaID:2} for range 4: [{NodeID:1 StoreID:1 ReplicaID:1} {NodeID:3 StoreID:3 ReplicaID:2}]
I160901 05:26:46.675705 2293 storage/replica_raftstorage.go:492  generated snapshot for range 5 at index 11 in 95.774µs. encoded size=531, 8 KV pairs, 1 log entries
W160901 05:26:46.675903 2291 storage/intent_resolver.go:344  could not GC completed transaction: end key /Local/Range/"\x95"/"rdsc\x00" must be greater than start /Local/Range/"\x95"/RangeDescriptor
I160901 05:26:46.676185 2294 storage/replica_raftstorage.go:631  store=2:2 5{/Min-/Min}: with replicaID [?], applying preemptive snapshot at index 11 (encoded size=531, 8 KV pairs, 1 log entries)
I160901 05:26:46.676476 2294 storage/replica_raftstorage.go:634  store=2:2 5{/Table/14-/Max}: with replicaID [?], applied preemptive snapshot in 0.000s
I160901 05:26:46.679714 1923 storage/replica_command.go:3073  change replicas of 5: read existing descriptor range_id:5 start_key:"\226" end_key:"\377\377" replicas:<node_id:1 store_id:1 replica_id:1 > next_replica_id:2 
I160901 05:26:46.683366 2282 storage/raft_transport.go:378  raft transport stream to node 1 established
I160901 05:26:46.685365 1923 storage/replica.go:1551  [n1,s1,r5{/Table/14-/Max}] proposing ADD_REPLICA {NodeID:2 StoreID:2 ReplicaID:2} for range 5: [{NodeID:1 StoreID:1 ReplicaID:1} {NodeID:2 StoreID:2 ReplicaID:2}]
I160901 05:26:46.686313 1923 storage/queue.go:562  [replicate] purgatory is now empty
I160901 05:26:46.688706 2272 storage/replica_raftstorage.go:492  generated snapshot for range 1 at index 52 in 1.66407ms. encoded size=173247, 582 KV pairs, 42 log entries
W160901 05:26:46.696117 2285 storage/intent_resolver.go:344  could not GC completed transaction: end key /Local/Range/"\x96"/"rdsc\x00" must be greater than start /Local/Range/"\x96"/RangeDescriptor
I160901 05:26:46.698447 2287 storage/replica_raftstorage.go:631  store=3:3 1{/Min-/Min}: with replicaID [?], applying preemptive snapshot at index 52 (encoded size=173247, 582 KV pairs, 42 log entries)
I160901 05:26:46.699650 2287 storage/replica_raftstorage.go:634  store=3:3 1{/Min-/Table/11}: with replicaID [?], applied preemptive snapshot in 0.001s
I160901 05:26:46.700148 1892 storage/replica_command.go:3073  change replicas of 1: read existing descriptor range_id:1 start_key:"" end_key:"\223" replicas:<node_id:1 store_id:1 replica_id:1 > replicas:<node_id:2 store_id:2 replica_id:2 > next_replica_id:3 
I160901 05:26:46.703759 1892 storage/replica.go:1551  [n1,s1,r1{/Min-/Table/11}] proposing ADD_REPLICA {NodeID:3 StoreID:3 ReplicaID:3} for range 1: [{NodeID:1 StoreID:1 ReplicaID:1} {NodeID:2 StoreID:2 ReplicaID:2} {NodeID:3 StoreID:3 ReplicaID:3}]
I160901 05:26:46.705344 2224 storage/replica_trigger.go:458  unable to gossip first range; hasLease=false, err=<nil>
W160901 05:26:46.706052 2306 storage/intent_resolver.go:344  could not GC completed transaction: end key /Local/Range/""/"rdsc\x00" must be greater than start /Local/Range/""/RangeDescriptor
I160901 05:26:46.706106 2297 storage/replica_raftstorage.go:492  generated snapshot for range 2 at index 16 in 230.687µs. encoded size=3893, 12 KV pairs, 6 log entries
I160901 05:26:46.706696 2324 storage/replica_raftstorage.go:631  store=3:3 2{/Min-/Min}: with replicaID [?], applying preemptive snapshot at index 16 (encoded size=3893, 12 KV pairs, 6 log entries)
I160901 05:26:46.707015 2324 storage/replica_raftstorage.go:634  store=3:3 2{/Table/11-/Table/12}: with replicaID [?], applied preemptive snapshot in 0.000s
I160901 05:26:46.707696 1892 storage/replica_command.go:3073  change replicas of 2: read existing descriptor range_id:2 start_key:"\223" end_key:"\224" replicas:<node_id:1 store_id:1 replica_id:1 > replicas:<node_id:2 store_id:2 replica_id:2 > next_replica_id:3 
I160901 05:26:46.717038 2298 storage/replica_trigger.go:458  unable to gossip first range; hasLease=false, err=<nil>
I160901 05:26:46.717823 1892 storage/replica.go:1551  [n1,s1,r2{/Table/11-/Table/12}] proposing ADD_REPLICA {NodeID:3 StoreID:3 ReplicaID:3} for range 2: [{NodeID:1 StoreID:1 ReplicaID:1} {NodeID:2 StoreID:2 ReplicaID:2} {NodeID:3 StoreID:3 ReplicaID:3}]
W160901 05:26:46.720947 2299 storage/intent_resolver.go:344  could not GC completed transaction: end key /Local/Range/"\x93"/"rdsc\x00" must be greater than start /Local/Range/"\x93"/RangeDescriptor
I160901 05:26:46.721363 2151 storage/replica_raftstorage.go:492  generated snapshot for range 5 at index 13 in 135.89µs. encoded size=1751, 10 KV pairs, 3 log entries
I160901 05:26:46.722982 2301 storage/replica_raftstorage.go:631  store=3:3 5{/Min-/Min}: with replicaID [?], applying preemptive snapshot at index 13 (encoded size=1751, 10 KV pairs, 3 log entries)
I160901 05:26:46.723292 2301 storage/replica_raftstorage.go:634  store=3:3 5{/Table/14-/Max}: with replicaID [?], applied preemptive snapshot in 0.000s
I160901 05:26:46.723746 1892 storage/replica_command.go:3073  change replicas of 5: read existing descriptor range_id:5 start_key:"\226" end_key:"\377\377" replicas:<node_id:1 store_id:1 replica_id:1 > replicas:<node_id:2 store_id:2 replica_id:2 > next_replica_id:3 
I160901 05:26:46.728867 1892 storage/replica.go:1551  [n1,s1,r5{/Table/14-/Max}] proposing ADD_REPLICA {NodeID:3 StoreID:3 ReplicaID:3} for range 5: [{NodeID:1 StoreID:1 ReplicaID:1} {NodeID:2 StoreID:2 ReplicaID:2} {NodeID:3 StoreID:3 ReplicaID:3}]
I160901 05:26:46.731773 2326 storage/replica_raftstorage.go:492  generated snapshot for range 4 at index 30 in 323.331µs. encoded size=19955, 81 KV pairs, 20 log entries
I160901 05:26:46.732405 2232 storage/replica_raftstorage.go:631  store=2:2 4{/Min-/Min}: with replicaID [?], applying preemptive snapshot at index 30 (encoded size=19955, 81 KV pairs, 20 log entries)
I160901 05:26:46.732906 2232 storage/replica_raftstorage.go:634  store=2:2 4{/Table/13-/Table/14}: with replicaID [?], applied preemptive snapshot in 0.000s
I160901 05:26:46.733620 1892 storage/replica_command.go:3073  change replicas of 4: read existing descriptor range_id:4 start_key:"\225" end_key:"\226" replicas:<node_id:1 store_id:1 replica_id:1 > replicas:<node_id:3 store_id:3 replica_id:2 > next_replica_id:3 
W160901 05:26:46.734536 2302 storage/intent_resolver.go:344  could not GC completed transaction: end key /Local/Range/"\x96"/"rdsc\x00" must be greater than start /Local/Range/"\x96"/RangeDescriptor
I160901 05:26:46.741735 1892 storage/replica.go:1551  [n1,s1,r4{/Table/13-/Table/14}] proposing ADD_REPLICA {NodeID:2 StoreID:2 ReplicaID:3} for range 4: [{NodeID:1 StoreID:1 ReplicaID:1} {NodeID:3 StoreID:3 ReplicaID:2} {NodeID:2 StoreID:2 ReplicaID:3}]
W160901 05:26:46.743953 2255 storage/intent_resolver.go:344  could not GC completed transaction: end key /Local/Range/"\x95"/"rdsc\x00" must be greater than start /Local/Range/"\x95"/RangeDescriptor
I160901 05:26:46.744764 2303 storage/replica_raftstorage.go:492  generated snapshot for range 3 at index 20 in 178.166µs. encoded size=7897, 27 KV pairs, 10 log entries
I160901 05:26:46.745509 2152 storage/replica_raftstorage.go:631  store=2:2 3{/Min-/Min}: with replicaID [?], applying preemptive snapshot at index 20 (encoded size=7897, 27 KV pairs, 10 log entries)
I160901 05:26:46.745890 2152 storage/replica_raftstorage.go:634  store=2:2 3{/Table/12-/Table/13}: with replicaID [?], applied preemptive snapshot in 0.000s
I160901 05:26:46.746626 1892 storage/replica_command.go:3073  change replicas of 3: read existing descriptor range_id:3 start_key:"\224" end_key:"\225" replicas:<node_id:1 store_id:1 replica_id:1 > replicas:<node_id:3 store_id:3 replica_id:2 > next_replica_id:3 
I160901 05:26:46.754751 1892 storage/replica.go:1551  [n1,s1,r3{/Table/12-/Table/13}] proposing ADD_REPLICA {NodeID:2 StoreID:2 ReplicaID:3} for range 3: [{NodeID:1 StoreID:1 ReplicaID:1} {NodeID:3 StoreID:3 ReplicaID:2} {NodeID:2 StoreID:2 ReplicaID:3}]
W160901 05:26:46.767163 2225 storage/intent_resolver.go:344  could not GC completed transaction: end key /Local/Range/"\x94"/"rdsc\x00" must be greater than start /Local/Range/"\x94"/RangeDescriptor
I160901 05:26:46.963039 1976 http2_client.go:1053  transport: http2Client.notifyError got notified that the client transport was broken EOF.
I160901 05:26:46.963094 2153 http2_client.go:1053  transport: http2Client.notifyError got notified that the client transport was broken EOF.
I160901 05:26:46.963101 1974 http2_server.go:276  transport: http2Server.HandleStreams failed to read frame: read tcp 127.0.0.1:37166->127.0.0.1:38565: use of closed network connection
I160901 05:26:46.963110 1239 http2_client.go:1053  transport: http2Client.notifyError got notified that the client transport was broken EOF.
W160901 05:26:46.963189 2244 storage/raft_transport.go:383  raft transport stream to node 1 failed: rpc error: code = 13 desc = transport is closing
I160901 05:26:46.963207 2012 /go/src/google.golang.org/grpc/clientconn.go:667  grpc: addrConn.resetTransport failed to create client transport: connection error: desc = "transport: dial tcp 127.0.0.1:37166: operation was canceled"; Reconnecting to {"127.0.0.1:37166" <nil>}
I160901 05:26:46.963221 2012 /go/src/google.golang.org/grpc/clientconn.go:767  grpc: addrConn.transportMonitor exits due to: grpc: the connection is closing
W160901 05:26:46.963228 2170 storage/raft_transport.go:383  raft transport stream to node 2 failed: rpc error: code = 13 desc = transport is closing
I160901 05:26:46.963287 2345 /go/src/google.golang.org/grpc/clientconn.go:667  grpc: addrConn.resetTransport failed to create client transport: connection error: desc = "transport: write tcp 127.0.0.1:38828->127.0.0.1:37166: write: connection reset by peer"; Reconnecting to {"127.0.0.1:37166" <nil>}
I160901 05:26:46.974456 1729 /go/src/google.golang.org/grpc/clientconn.go:667  grpc: addrConn.resetTransport failed to create client transport: connection error: desc = "transport: write tcp 127.0.0.1:38826->127.0.0.1:37166: write: broken pipe"; Reconnecting to {"127.0.0.1:37166" <nil>}
I160901 05:26:46.990386 2345 /go/src/google.golang.org/grpc/clientconn.go:767  grpc: addrConn.transportMonitor exits due to: context canceled
I160901 05:26:46.990689 1898 http2_server.go:276  transport: http2Server.HandleStreams failed to read frame: read tcp 127.0.0.1:37339->127.0.0.1:55468: use of closed network connection
I160901 05:26:46.990728 1924 http2_client.go:1053  transport: http2Client.notifyError got notified that the client transport was broken EOF.
W160901 05:26:46.990858 2282 storage/raft_transport.go:383  raft transport stream to node 1 failed: EOF
I160901 05:26:46.990977 1242 http2_client.go:1053  transport: http2Client.notifyError got notified that the client transport was broken EOF.
I160901 05:26:46.991046 2109 http2_server.go:276  transport: http2Server.HandleStreams failed to read frame: read tcp 127.0.0.1:37339->127.0.0.1:55614: use of closed network connection
I160901 05:26:46.991056 1729 /go/src/google.golang.org/grpc/clientconn.go:767  grpc: addrConn.transportMonitor exits due to: context canceled
I160901 05:26:46.991179 2104 /go/src/google.golang.org/grpc/clientconn.go:667  grpc: addrConn.resetTransport failed to create client transport: connection error: desc = "transport: dial tcp 127.0.0.1:37339: getsockopt: connection refused"; Reconnecting to {"127.0.0.1:37339" <nil>}
I160901 05:26:46.991628 2104 /go/src/google.golang.org/grpc/clientconn.go:767  grpc: addrConn.transportMonitor exits due to: context canceled
I160901 05:26:46.991638 2168 http2_server.go:276  transport: http2Server.HandleStreams failed to read frame: read tcp 127.0.0.1:40560->127.0.0.1:33168: use of closed network connection
--- FAIL: TestStopServer (0.61s)
	testcluster_test.go:226: Expected error from server with text "connection refused", got error with text "status: 404 Not Found, body: 404 page not found\n"
FAIL


ERROR: exit status 1
```

Run Details:

```
32 runs so far, 0 failures, over 5s
65 runs so far, 0 failures, over 10s
109 runs so far, 0 failures, over 15s
142 runs so far, 0 failures, over 20s
180 runs so far, 0 failures, over 25s
221 runs so far, 0 failures, over 30s
257 runs so far, 0 failures, over 35s
297 runs so far, 0 failures, over 40s
336 runs so far, 0 failures, over 45s
371 runs so far, 0 failures, over 50s
408 runs so far, 0 failures, over 55s
446 runs so far, 0 failures, over 1m0s
486 runs so far, 0 failures, over 1m5s
522 runs so far, 0 failures, over 1m10s
563 runs so far, 0 failures, over 1m15s
600 runs so far, 0 failures, over 1m20s
637 runs so far, 0 failures, over 1m25s
676 runs so far, 0 failures, over 1m30s
713 runs so far, 0 failures, over 1m35s
752 runs so far, 0 failures, over 1m40s
791 runs so far, 0 failures, over 1m45s
829 runs so far, 0 failures, over 1m50s
868 runs so far, 0 failures, over 1m55s
904 runs so far, 0 failures, over 2m0s
944 runs so far, 0 failures, over 2m5s
982 runs so far, 0 failures, over 2m10s
1019 runs so far, 0 failures, over 2m15s
1058 runs so far, 0 failures, over 2m20s
1094 runs so far, 0 failures, over 2m25s
1133 runs so far, 0 failures, over 2m30s
1171 runs so far, 0 failures, over 2m35s
1210 runs so far, 0 failures, over 2m40s
1246 runs so far, 0 failures, over 2m45s
1287 runs so far, 0 failures, over 2m50s
1324 runs so far, 0 failures, over 2m55s
1361 runs so far, 0 failures, over 3m0s
1401 runs so far, 0 failures, over 3m5s
1435 runs so far, 0 failures, over 3m10s
1476 runs so far, 0 failures, over 3m15s
1514 runs so far, 0 failures, over 3m20s
1551 runs so far, 0 failures, over 3m25s
1590 runs so far, 0 failures, over 3m30s
1625 runs so far, 0 failures, over 3m35s
1668 runs so far, 0 failures, over 3m40s
1703 runs so far, 0 failures, over 3m45s
1740 runs so far, 0 failures, over 3m50s
1782 runs so far, 0 failures, over 3m55s
1816 runs so far, 0 failures, over 4m0s
1857 runs so far, 0 failures, over 4m5s
1894 runs so far, 0 failures, over 4m10s
1934 runs so far, 0 failures, over 4m15s
1972 runs so far, 0 failures, over 4m20s
2008 runs so far, 0 failures, over 4m25s
2047 runs so far, 0 failures, over 4m30s
2085 runs so far, 0 failures, over 4m35s
2121 runs so far, 0 failures, over 4m40s
2161 runs so far, 0 failures, over 4m45s
2198 runs so far, 0 failures, over 4m50s
2239 runs so far, 0 failures, over 4m55s
2273 runs so far, 0 failures, over 5m0s
2315 runs so far, 0 failures, over 5m5s
2352 runs so far, 0 failures, over 5m10s
2389 runs so far, 0 failures, over 5m15s
2427 runs so far, 0 failures, over 5m20s
2466 runs so far, 0 failures, over 5m25s
2503 runs so far, 0 failures, over 5m30s
2542 runs so far, 0 failures, over 5m35s
2580 runs so far, 0 failures, over 5m40s
2620 runs so far, 0 failures, over 5m45s
2656 runs so far, 0 failures, over 5m50s
2695 runs so far, 0 failures, over 5m55s
2734 runs so far, 0 failures, over 6m0s
2770 runs so far, 0 failures, over 6m5s
2810 runs so far, 0 failures, over 6m10s
2847 runs so far, 0 failures, over 6m15s
2885 runs so far, 0 failures, over 6m20s
2921 runs so far, 0 failures, over 6m25s
2959 runs so far, 0 failures, over 6m30s
3000 runs so far, 0 failures, over 6m35s
3036 runs so far, 0 failures, over 6m40s
3077 runs so far, 0 failures, over 6m45s
3113 runs so far, 0 failures, over 6m50s
3150 runs so far, 0 failures, over 6m55s
3191 runs so far, 0 failures, over 7m0s
3229 runs so far, 0 failures, over 7m5s
3265 runs so far, 0 failures, over 7m10s
3304 runs so far, 0 failures, over 7m15s
3340 runs so far, 0 failures, over 7m20s
3381 runs so far, 0 failures, over 7m25s
3418 runs so far, 0 failures, over 7m30s
3457 runs so far, 0 failures, over 7m35s
3494 runs so far, 0 failures, over 7m40s
3533 runs so far, 0 failures, over 7m45s
3570 runs so far, 0 failures, over 7m50s
3607 runs so far, 0 failures, over 7m55s
3647 runs so far, 0 failures, over 8m0s
3684 runs so far, 0 failures, over 8m5s
3724 runs so far, 0 failures, over 8m10s
3757 runs so far, 0 failures, over 8m15s
3798 runs so far, 0 failures, over 8m20s
3837 runs so far, 0 failures, over 8m25s
3874 runs so far, 0 failures, over 8m30s
3913 runs so far, 0 failures, over 8m35s
3950 runs so far, 0 failures, over 8m40s
3991 runs so far, 0 failures, over 8m45s
4024 runs so far, 0 failures, over 8m50s
4063 runs so far, 0 failures, over 8m55s
4101 runs so far, 0 failures, over 9m0s
4107 runs completed, 1 failures, over 9m1s
FAIL
```
Please assign, take a look and update the issue accordingly.

### LINKED ISSUE #9256: stress: failed test in cockroach/testutils/testcluster/testcluster.test: TestBasicManualReplication
Binary: cockroach/static-tests.tar.gz sha: https://github.com/cockroachdb/cockroach/commits/81586586550885fe7acc0b352a03d541e633505b

Stress build found a failed test:

```
=== RUN   TestBasicManualReplication
I160910 05:04:28.649417 303 storage/engine/rocksdb.go:356  opening in memory rocksdb instance
I160910 05:04:28.652083 303 gossip/gossip.go:230  [n?] initial resolvers: []
W160910 05:04:28.652109 303 gossip/gossip.go:1041  [n?] no resolvers found; use --join to specify a connected node
W160910 05:04:28.652585 303 server/status/runtime.go:109  Could not parse build timestamp: parsing time "" as "2006/01/02 15:04:05": cannot parse "" as "2006"
I160910 05:04:28.653132 303 server/node.go:413  [n?] store [n0,s0] not bootstrapped
I160910 05:04:28.655417 704 storage/replica_trigger.go:308  new range lease replica {1 1 1} 1970-01-01 00:00:00 +0000 UTC 409301h4m37.654932072s following replica {0 0 0} 1970-01-01 00:00:00 +0000 UTC 0s [physicalTime=2016-09-10 05:04:28.655383501 +0000 UTC]
I160910 05:04:28.656010 303 server/node.go:345  [n?] **** cluster {ecd165d7-6063-4b00-ba71-9cc5718976a0} has been created
I160910 05:04:28.656024 303 server/node.go:346  [n?] **** add additional nodes by specifying --join=127.0.0.1:35050
I160910 05:04:28.656242 303 gossip/gossip.go:264  [n?] NodeID set to 1
I160910 05:04:28.656773 303 storage/store.go:1004  [n?] [n1,s1]: failed initial metrics computation: [n1,s1]: system config not yet available
I160910 05:04:28.656794 303 server/node.go:426  [n?] initialized store [n1,s1]: {Capacity:536870912 Available:536870912 RangeCount:0}
I160910 05:04:28.656813 303 server/node.go:318  [n?] node ID 1 initialized
I160910 05:04:28.656842 303 gossip/gossip.go:278  [n?] NodeDescriptor set to node_id:1 address:<network_field:"tcp" address_field:"127.0.0.1:35050" > attrs:<> 
I160910 05:04:28.656880 303 storage/stores.go:313  read 0 node addresses from persistent storage
I160910 05:04:28.656928 303 server/node.go:554  [n?] connecting to gossip network to verify cluster ID...
I160910 05:04:28.657803 303 server/node.go:575  [n?] node connected via gossip and verified as part of cluster {"ecd165d7-6063-4b00-ba71-9cc5718976a0"}
I160910 05:04:28.657845 303 server/node.go:364  [n?] node=1: started with [[]=] engine(s) and attributes []
I160910 05:04:28.657978 303 server/server.go:488  [n1] starting https server at 127.0.0.1:43098
I160910 05:04:28.658099 529 sql/event_log.go:109  [n1] Event: "node_join", target: 1, info: {Descriptor:{NodeID:1 Address:{NetworkField:tcp AddressField:127.0.0.1:35050} Attrs:} ClusterID:{UUID:ecd165d7-6063-4b00-ba71-9cc5718976a0} StartedAt:1473483868657818807}
W160910 05:04:28.658983 529 kv/dist_sender.go:695  [n1] 1 retries for an RPC at sequence 4, last error was: <nil>, remaining key ranges {"/Table/2/1/1/\"eventlog\"/3/1" "/Table/2/1/1/\"eventlog\"/3/1/NULL"}: Get [/Table/2/1/1/"eventlog"/3/1,/Min)
I160910 05:04:28.665919 529 sql/event_log.go:109  [n1] Event: "node_join", target: 1, info: {Descriptor:{NodeID:1 Address:{NetworkField:tcp AddressField:127.0.0.1:35050} Attrs:} ClusterID:{UUID:ecd165d7-6063-4b00-ba71-9cc5718976a0} StartedAt:1473483868657818807}
I160910 05:04:28.668830 303 server/server.go:489  [n1] starting grpc/postgres server at 127.0.0.1:35050
I160910 05:04:28.669329 303 storage/engine/rocksdb.go:356  opening in memory rocksdb instance
W160910 05:04:28.669359 529 kv/dist_sender.go:695  [n1] 1 retries for an RPC at sequence 9, last error was: <nil>, remaining key ranges {"/Table/2/1/1/\"eventlog\"/3/1" "/Table/2/1/1/\"eventlog\"/3/1/NULL"}: Get [/Table/2/1/1/"eventlog"/3/1,/Min)
I160910 05:04:28.673004 303 gossip/gossip.go:230  [n?] initial resolvers: [%!s(*resolver.socketResolver=&{tcp 127.0.0.1:35050})]
W160910 05:04:28.673034 303 gossip/gossip.go:1043  [n?] no incoming or outgoing connections
W160910 05:04:28.673540 303 server/status/runtime.go:109  Could not parse build timestamp: parsing time "" as "2006/01/02 15:04:05": cannot parse "" as "2006"
I160910 05:04:28.674121 303 server/node.go:413  [n?] store [n0,s0] not bootstrapped
I160910 05:04:28.674143 303 storage/stores.go:313  read 0 node addresses from persistent storage
I160910 05:04:28.674170 303 server/node.go:554  [n?] connecting to gossip network to verify cluster ID...
I160910 05:04:28.693910 840 gossip/client.go:125  [n?] node 0: started gossip client to 127.0.0.1:35050
I160910 05:04:28.694143 853 gossip/server.go:274  [n1] node 1: received gossip from unknown node
I160910 05:04:28.694414 303 server/node.go:575  [n?] node connected via gossip and verified as part of cluster {"ecd165d7-6063-4b00-ba71-9cc5718976a0"}
I160910 05:04:28.694500 541 storage/stores.go:328  wrote 1 node addresses to persistent storage
I160910 05:04:28.695548 303 kv/dist_sender.go:343  [n?] unable to determine this node's attributes for replica selection; node is most likely bootstrapping
I160910 05:04:28.696318 303 server/node.go:312  [n?] new node allocated ID 2
I160910 05:04:28.696333 303 gossip/gossip.go:264  [n?] NodeID set to 2
I160910 05:04:28.696365 303 gossip/gossip.go:278  [n?] NodeDescriptor set to node_id:2 address:<network_field:"tcp" address_field:"127.0.0.1:46555" > attrs:<> 
I160910 05:04:28.696421 303 server/node.go:364  [n?] node=2: started with [[]=] engine(s) and attributes []
I160910 05:04:28.696444 303 server/server.go:488  [n2] starting https server at 127.0.0.1:42922
I160910 05:04:28.696453 303 server/server.go:489  [n2] starting grpc/postgres server at 127.0.0.1:46555
I160910 05:04:28.696539 887 sql/event_log.go:109  [n2] Event: "node_join", target: 2, info: {Descriptor:{NodeID:2 Address:{NetworkField:tcp AddressField:127.0.0.1:46555} Attrs:} ClusterID:{UUID:ecd165d7-6063-4b00-ba71-9cc5718976a0} StartedAt:1473483868706331110}
I160910 05:04:28.696956 788 storage/stores.go:328  wrote 1 node addresses to persistent storage
I160910 05:04:28.697018 303 storage/engine/rocksdb.go:356  opening in memory rocksdb instance
W160910 05:04:28.707756 887 kv/dist_sender.go:695  [n2] 1 retries for an RPC at sequence 4, last error was: <nil>, remaining key ranges {"/Table/2/1/1/\"eventlog\"/3/1" "/Table/2/1/1/\"eventlog\"/3/1/NULL"}: Get [/Table/2/1/1/"eventlog"/3/1,/Min)
I160910 05:04:28.708013 884 gossip/gossip.go:264  [n2] NodeID set to 2
I160910 05:04:28.708205 884 server/node.go:535  [n2] bootstrapped store [n2,s2]
I160910 05:04:28.715318 303 gossip/gossip.go:230  [n?] initial resolvers: [%!s(*resolver.socketResolver=&{tcp 127.0.0.1:35050})]
W160910 05:04:28.715339 303 gossip/gossip.go:1043  [n?] no incoming or outgoing connections
W160910 05:04:28.721864 303 server/status/runtime.go:109  Could not parse build timestamp: parsing time "" as "2006/01/02 15:04:05": cannot parse "" as "2006"
I160910 05:04:28.722365 303 server/node.go:413  [n?] store [n0,s0] not bootstrapped
I160910 05:04:28.722384 303 storage/stores.go:313  read 0 node addresses from persistent storage
I160910 05:04:28.722398 303 server/node.go:554  [n?] connecting to gossip network to verify cluster ID...
I160910 05:04:28.736577 1009 gossip/client.go:125  [n?] node 0: started gossip client to 127.0.0.1:35050
I160910 05:04:28.736772 1017 gossip/server.go:274  [n1] node 1: received gossip from unknown node
I160910 05:04:28.737879 303 server/node.go:575  [n?] node connected via gossip and verified as part of cluster {"ecd165d7-6063-4b00-ba71-9cc5718976a0"}
I160910 05:04:28.738146 903 storage/stores.go:328  wrote 1 node addresses to persistent storage
I160910 05:04:28.738350 903 storage/stores.go:328  wrote 2 node addresses to persistent storage
I160910 05:04:28.743967 303 kv/dist_sender.go:343  [n?] unable to determine this node's attributes for replica selection; node is most likely bootstrapping
I160910 05:04:28.744775 303 server/node.go:312  [n?] new node allocated ID 3
I160910 05:04:28.744794 303 gossip/gossip.go:264  [n?] NodeID set to 3
I160910 05:04:28.744829 303 gossip/gossip.go:278  [n?] NodeDescriptor set to node_id:3 address:<network_field:"tcp" address_field:"127.0.0.1:41560" > attrs:<> 
I160910 05:04:28.744887 303 server/node.go:364  [n?] node=3: started with [[]=] engine(s) and attributes []
I160910 05:04:28.744912 303 server/server.go:488  [n3] starting https server at 127.0.0.1:37920
I160910 05:04:28.744922 303 server/server.go:489  [n3] starting grpc/postgres server at 127.0.0.1:41560
I160910 05:04:28.745856 878 storage/stores.go:328  wrote 2 node addresses to persistent storage
I160910 05:04:28.745894 794 sql/event_log.go:109  [n3] Event: "node_join", target: 3, info: {Descriptor:{NodeID:3 Address:{NetworkField:tcp AddressField:127.0.0.1:41560} Attrs:} ClusterID:{UUID:ecd165d7-6063-4b00-ba71-9cc5718976a0} StartedAt:1473483868744868677}
I160910 05:04:28.746115 879 storage/stores.go:328  wrote 2 node addresses to persistent storage
I160910 05:04:28.748263 791 gossip/gossip.go:264  [n3] NodeID set to 3
I160910 05:04:28.748440 791 server/node.go:535  [n3] bootstrapped store [n3,s3]
W160910 05:04:28.748837 794 kv/dist_sender.go:695  [n3] 1 retries for an RPC at sequence 4, last error was: <nil>, remaining key ranges {"/Table/2/1/1/\"eventlog\"/3/1" "/Table/2/1/1/\"eventlog\"/3/1/NULL"}: Get [/Table/2/1/1/"eventlog"/3/1,/Min)
I160910 05:04:28.768769 912 storage/replica_raftstorage.go:492  generated snapshot for range 1 at index 34 in 2.851338ms. encoded size=174985, 578 KV pairs, 24 log entries
I160910 05:04:28.773460 1107 storage/replica_raftstorage.go:631  [n2,s2,r1{-}]: with replicaID [?], applying preemptive snapshot at index 34 (encoded size=174985, 578 KV pairs, 24 log entries)
I160910 05:04:28.776573 1107 storage/replica_raftstorage.go:634  [n2,s2,r1{/Min-/Max}]: with replicaID [?], applied preemptive snapshot in 0.003s
I160910 05:04:28.777132 303 storage/replica_command.go:3101  change replicas: read existing descriptor range_id:1 start_key:"" end_key:"\377\377" replicas:<node_id:1 store_id:1 replica_id:1 > next_replica_id:2 
W160910 05:04:28.777963 303 kv/dist_sender.go:695  1 retries for an RPC at sequence 4, last error was: <nil>, remaining key ranges {"/Table/2/1/0/\"system\"/3/1" "/Table/2/1/0/\"system\"/3/1/NULL"}: Get [/Table/2/1/0/"system"/3/1,/Min)
W160910 05:04:28.779646 303 kv/dist_sender.go:695  1 retries for an RPC at sequence 9, last error was: <nil>, remaining key ranges {"/Min" "\"\\x00\""}: EndTransaction [/Local/Range/""/RangeDescriptor,/Min)
I160910 05:04:28.779817 303 storage/replica.go:1608  [n1,s1,r1{/Min-/Max}] proposing ADD_REPLICA {NodeID:2 StoreID:2 ReplicaID:2} for range 1: [{NodeID:1 StoreID:1 ReplicaID:1} {NodeID:2 StoreID:2 ReplicaID:2}]
I160910 05:04:28.798616 1130 storage/replica_raftstorage.go:492  generated snapshot for range 1 at index 37 in 2.778303ms. encoded size=177252, 586 KV pairs, 27 log entries
I160910 05:04:28.800516 1098 storage/replica_raftstorage.go:631  [n3,s3,r1{-}]: with replicaID [?], applying preemptive snapshot at index 37 (encoded size=177252, 586 KV pairs, 27 log entries)
I160910 05:04:28.802295 1098 storage/replica_raftstorage.go:634  [n3,s3,r1{/Min-/Max}]: with replicaID [?], applied preemptive snapshot in 0.002s
I160910 05:04:28.802732 303 storage/replica_command.go:3101  change replicas: read existing descriptor range_id:1 start_key:"" end_key:"\377\377" replicas:<node_id:1 store_id:1 replica_id:1 > replicas:<node_id:2 store_id:2 replica_id:2 > next_replica_id:3 
I160910 05:04:28.803808 1101 storage/raft_transport.go:395  raft transport stream to node 1 established
I160910 05:04:28.804934 1104 storage/replica_trigger.go:468  unable to gossip first range; hasLease=false, err=<nil>
W160910 05:04:28.805537 303 kv/dist_sender.go:695  1 retries for an RPC at sequence 4, last error was: <nil>, remaining key ranges {"/Table/2/1/0/\"system\"/3/1" "/Table/2/1/0/\"system\"/3/1/NULL"}: Get [/Table/2/1/0/"system"/3/1,/Min)
W160910 05:04:28.807288 303 kv/dist_sender.go:695  1 retries for an RPC at sequence 9, last error was: <nil>, remaining key ranges {"/Min" "\"\\x00\""}: EndTransaction [/Local/Range/""/RangeDescriptor,/Min)
I160910 05:04:28.807506 303 storage/replica.go:1608  [n1,s1,r1{/Min-/Max}] proposing ADD_REPLICA {NodeID:3 StoreID:3 ReplicaID:3} for range 1: [{NodeID:1 StoreID:1 ReplicaID:1} {NodeID:2 StoreID:2 ReplicaID:2} {NodeID:3 StoreID:3 ReplicaID:3}]
I160910 05:04:28.808775 1131 storage/replica_trigger.go:468  unable to gossip first range; hasLease=false, err=<nil>
I160910 05:04:28.809535 748 storage/replica_trigger.go:339  range 1: replicaID 1 transfer raft leadership to replicaID 2
I160910 05:04:28.809586 1136 storage/raft_transport.go:395  raft transport stream to node 1 established
I160910 05:04:28.809865 928 storage/replica_trigger.go:308  [n2,s2,r1{/Min-/Max}] new range lease replica {2 2 2} 2016-09-10 05:04:28.808811323 +0000 UTC 9.05s following replica {1 1 1} 1970-01-01 00:00:00 +0000 UTC 409301h4m37.654932072s [physicalTime=2016-09-10 05:04:28.809828945 +0000 UTC]
I160910 05:04:28.811065 1037 storage/replica_trigger.go:468  unable to gossip first range; hasLease=false, err=<nil>
I160910 05:04:28.811276 303 storage/replica_command.go:3101  change replicas: read existing descriptor range_id:1 start_key:"" end_key:"\377\377" replicas:<node_id:1 store_id:1 replica_id:1 > replicas:<node_id:2 store_id:2 replica_id:2 > replicas:<node_id:3 store_id:3 replica_id:3 > next_replica_id:4 
W160910 05:04:28.812034 303 kv/dist_sender.go:695  1 retries for an RPC at sequence 4, last error was: <nil>, remaining key ranges {"/Min" "\"\\x00\""}: Get [/Local/Range/""/RangeDescriptor,/Min)
I160910 05:04:28.812577 303 storage/replica_command.go:3101  change replicas: read existing descriptor range_id:1 start_key:"" end_key:"\377\377" replicas:<node_id:1 store_id:1 replica_id:1 > replicas:<node_id:2 store_id:2 replica_id:2 > replicas:<node_id:3 store_id:3 replica_id:3 > next_replica_id:4 
W160910 05:04:28.815858 303 kv/dist_sender.go:695  1 retries for an RPC at sequence 9, last error was: <nil>, remaining key ranges {"/Table/3/1/13/2/1" "/Table/3/1/13/2/1/NULL"}: Get [/Table/3/1/13/2/1,/Min)
I160910 05:04:28.818122 1019 storage/replica.go:1608  [n2,s2,r1{/Min-/Max}] proposing REMOVE_REPLICA {NodeID:1 StoreID:1 ReplicaID:1} for range 1: [{NodeID:3 StoreID:3 ReplicaID:3} {NodeID:2 StoreID:2 ReplicaID:2}]
I160910 05:04:28.819573 1236 storage/replica_trigger.go:468  unable to gossip first range; hasLease=false, err=<nil>
I160910 05:04:28.820456 1138 storage/store.go:2516  [n1,s1] [n1,s1,r1{/Min-/Max}]: replica {1 1 1} too old, added to replica GC queue
I160910 05:04:28.823241 303 stopper.go:408  quiesceing; tasks left:
1      storage/queue.go:443
W160910 05:04:28.823319 1101 storage/raft_transport.go:400  raft transport stream to node 1 failed: EOF
W160910 05:04:28.823455 1136 storage/raft_transport.go:400  raft transport stream to node 1 failed: EOF
W160910 05:04:28.823631 1088 storage/raft_transport.go:400  raft transport stream to node 2 failed: rpc error: code = 13 desc = transport is closing
I160910 05:04:28.823808 1158 storage/raft_transport.go:395  raft transport stream to node 3 established
E160910 05:04:28.824329 367 storage/queue.go:518  [replicaGC] on [n1,s1,r1{/Min-/Max}]: failed to send RPC: sending to all 3 replicas failed; last error: rpc error: code = 9 desc = grpc: the client connection is closing
I160910 05:04:28.824472 873 http2_server.go:276  transport: http2Server.HandleStreams failed to read frame: read tcp 127.0.0.1:35050->127.0.0.1:53118: use of closed network connection
I160910 05:04:28.824519 650 http2_server.go:276  transport: http2Server.HandleStreams failed to read frame: read tcp 127.0.0.1:35050->127.0.0.1:53092: use of closed network connection
I160910 05:04:28.824546 305 http2_client.go:1053  transport: http2Client.notifyError got notified that the client transport was broken EOF.
I160910 05:04:28.824558 874 http2_client.go:1053  transport: http2Client.notifyError got notified that the client transport was broken EOF.
I160910 05:04:28.824693 1011 /go/src/google.golang.org/grpc/clientconn.go:667  grpc: addrConn.resetTransport failed to create client transport: connection error: desc = "transport: dial tcp 127.0.0.1:35050: getsockopt: connection refused"; Reconnecting to {"127.0.0.1:35050" <nil>}
I160910 05:04:28.824721 842 /go/src/google.golang.org/grpc/clientconn.go:667  grpc: addrConn.resetTransport failed to create client transport: connection error: desc = "transport: dial tcp 127.0.0.1:35050: getsockopt: connection refused"; Reconnecting to {"127.0.0.1:35050" <nil>}
I160910 05:04:28.825147 303 stopper.go:408  quiesceing; tasks left:
2      server/node.go:835
I160910 05:04:28.825310 842 /go/src/google.golang.org/grpc/clientconn.go:767  grpc: addrConn.transportMonitor exits due to: context canceled
W160910 05:04:28.825388 1158 storage/raft_transport.go:400  raft transport stream to node 3 failed: rpc error: code = 13 desc = transport is closing
I160910 05:04:28.838224 1022 storage/raft_transport.go:395  raft transport stream to node 2 established
W160910 05:04:28.838664 1022 storage/raft_transport.go:400  raft transport stream to node 2 failed: rpc error: code = 2 desc = node unavailable; try another peer
I160910 05:04:29.722893 1190 gossip/client.go:125  [n3] node 3: started gossip client to 127.0.0.1:46555
I160910 05:04:29.826854 1011 /go/src/google.golang.org/grpc/clientconn.go:667  grpc: addrConn.resetTransport failed to create client transport: connection error: desc = "transport: dial tcp 127.0.0.1:35050: getsockopt: connection refused"; Reconnecting to {"127.0.0.1:35050" <nil>}
W160910 05:04:30.723017 1200 gossip/client.go:119  [n3] node 3: failed to start gossip client: rpc error: code = 14 desc = grpc: the connection is unavailable
I160910 05:04:31.438558 1011 /go/src/google.golang.org/grpc/clientconn.go:667  grpc: addrConn.resetTransport failed to create client transport: connection error: desc = "transport: dial tcp 127.0.0.1:35050: getsockopt: connection refused"; Reconnecting to {"127.0.0.1:35050" <nil>}
W160910 05:04:31.710013 934 raft/raft.go:666  [n2,s2,r1{/Min-/Max}] 2 stepped down to follower since quorum is not active
I160910 05:04:31.755814 1149 storage/raft_transport.go:395  raft transport stream to node 2 established
I160910 05:04:32.723686 1246 gossip/client.go:125  [n3] node 3: started gossip client to 127.0.0.1:46555
I160910 05:04:33.642202 1011 /go/src/google.golang.org/grpc/clientconn.go:667  grpc: addrConn.resetTransport failed to create client transport: connection error: desc = "transport: dial tcp 127.0.0.1:35050: getsockopt: connection refused"; Reconnecting to {"127.0.0.1:35050" <nil>}
W160910 05:04:33.697077 886 gossip/infostore.go:295  [n2] node unavailable; try another peer
I160910 05:04:34.749964 1325 storage/raft_transport.go:395  raft transport stream to node 2 established
I160910 05:04:35.724384 1152 gossip/client.go:125  [n3] node 3: started gossip client to 127.0.0.1:46555
I160910 05:04:37.854456 1011 /go/src/google.golang.org/grpc/clientconn.go:667  grpc: addrConn.resetTransport failed to create client transport: connection error: desc = "transport: dial tcp 127.0.0.1:35050: getsockopt: connection refused"; Reconnecting to {"127.0.0.1:35050" <nil>}
W160910 05:04:38.696970 886 gossip/infostore.go:295  [n2] node unavailable; try another peer
I160910 05:04:38.697435 888 server/status/runtime.go:207  runtime stats: 174 MiB RSS, 160 goroutines, 8.9 MiB/8.2 MiB/29 MiB GO alloc/idle/total, 42 MiB/50 MiB CGO alloc/total, 0.00cgo/sec, 0.00/0.00 %(u/s)time, 0.00 %gc (13x)
W160910 05:04:38.700910 890 server/node.go:670  [n2] error recording status summaries: node unavailable; try another peer
W160910 05:04:38.714256 889 ts/db.go:104  node unavailable; try another peer
I160910 05:04:38.725103 1163 gossip/client.go:125  [n3] node 3: started gossip client to 127.0.0.1:46555
I160910 05:04:38.747200 795 server/status/runtime.go:207  runtime stats: 174 MiB RSS, 160 goroutines, 9.0 MiB/8.2 MiB/29 MiB GO alloc/idle/total, 42 MiB/50 MiB CGO alloc/total, 0.00cgo/sec, 0.00/0.00 %(u/s)time, 0.00 %gc (13x)
I160910 05:04:39.751208 1379 storage/raft_transport.go:395  raft transport stream to node 2 established
I160910 05:04:41.727289 1364 gossip/client.go:125  [n3] node 3: started gossip client to 127.0.0.1:46555
W160910 05:04:43.697009 886 gossip/infostore.go:295  [n2] node unavailable; try another peer
I160910 05:04:44.065053 1011 /go/src/google.golang.org/grpc/clientconn.go:667  grpc: addrConn.resetTransport failed to create client transport: connection error: desc = "transport: dial tcp 127.0.0.1:35050: getsockopt: connection refused"; Reconnecting to {"127.0.0.1:35050" <nil>}
I160910 05:04:44.727990 1285 gossip/client.go:125  [n3] node 3: started gossip client to 127.0.0.1:46555
I160910 05:04:45.549836 1385 storage/raft_transport.go:395  raft transport stream to node 2 established
I160910 05:04:47.735995 1410 gossip/client.go:125  [n3] node 3: started gossip client to 127.0.0.1:46555
W160910 05:04:48.697539 886 gossip/infostore.go:295  [n2] node unavailable; try another peer
I160910 05:04:48.697718 888 server/status/runtime.go:207  runtime stats: 174 MiB RSS, 161 goroutines, 12 MiB/6.0 MiB/29 MiB GO alloc/idle/total, 42 MiB/50 MiB CGO alloc/total, 72.40cgo/sec, 0.00/0.00 %(u/s)time, 0.00 %gc (0x)
W160910 05:04:48.700948 890 server/node.go:670  [n2] error recording status summaries: node unavailable; try another peer
W160910 05:04:48.714259 889 ts/db.go:104  node unavailable; try another peer
I160910 05:04:48.748550 795 server/status/runtime.go:207  runtime stats: 174 MiB RSS, 161 goroutines, 12 MiB/6.0 MiB/29 MiB GO alloc/idle/total, 42 MiB/50 MiB CGO alloc/total, 72.39cgo/sec, 0.00/0.00 %(u/s)time, 0.00 %gc (0x)
I160910 05:04:49.550009 1390 storage/raft_transport.go:395  raft transport stream to node 2 established
I160910 05:04:50.736678 1403 gossip/client.go:125  [n3] node 3: started gossip client to 127.0.0.1:46555
W160910 05:04:53.697021 886 gossip/infostore.go:295  [n2] node unavailable; try another peer
I160910 05:04:53.737378 1360 gossip/client.go:125  [n3] node 3: started gossip client to 127.0.0.1:46555
I160910 05:04:54.951013 1312 storage/raft_transport.go:395  raft transport stream to node 2 established
I160910 05:04:55.742623 1462 gossip/client.go:125  [n3] node 3: started gossip client to 127.0.0.1:35050
I160910 05:04:55.761129 1463 http2_client.go:1053  transport: http2Client.notifyError got notified that the client transport was broken EOF.
I160910 05:04:55.761316 1011 /go/src/google.golang.org/grpc/clientconn.go:667  grpc: addrConn.resetTransport failed to create client transport: connection error: desc = "transport: dial tcp 127.0.0.1:35050: getsockopt: connection refused"; Reconnecting to {"127.0.0.1:35050" <nil>}
I160910 05:04:56.741270 1436 gossip/client.go:125  [n3] node 3: started gossip client to 127.0.0.1:46555
I160910 05:04:56.761439 1011 /go/src/google.golang.org/grpc/clientconn.go:667  grpc: addrConn.resetTransport failed to create client transport: connection error: desc = "transport: dial tcp 127.0.0.1:35050: getsockopt: connection refused"; Reconnecting to {"127.0.0.1:35050" <nil>}
W160910 05:04:57.741403 1422 gossip/client.go:119  [n3] node 3: failed to start gossip client: rpc error: code = 14 desc = grpc: the connection is unavailable
I160910 05:04:58.442157 1011 /go/src/google.golang.org/grpc/clientconn.go:667  grpc: addrConn.resetTransport failed to create client transport: connection error: desc = "transport: dial tcp 127.0.0.1:35050: getsockopt: connection refused"; Reconnecting to {"127.0.0.1:35050" <nil>}
W160910 05:04:58.700252 886 gossip/infostore.go:295  [n2] node unavailable; try another peer
I160910 05:04:58.700439 888 server/status/runtime.go:207  runtime stats: 174 MiB RSS, 161 goroutines, 13 MiB/5.2 MiB/29 MiB GO alloc/idle/total, 42 MiB/50 MiB CGO alloc/total, 7.40cgo/sec, 0.00/0.00 %(u/s)time, 0.00 %gc (0x)
W160910 05:04:58.700872 890 server/node.go:670  [n2] error recording status summaries: node unavailable; try another peer
W160910 05:04:58.714226 889 ts/db.go:104  node unavailable; try another peer
I160910 05:04:58.751984 795 server/status/runtime.go:207  runtime stats: 174 MiB RSS, 161 goroutines, 13 MiB/5.2 MiB/29 MiB GO alloc/idle/total, 42 MiB/50 MiB CGO alloc/total, 7.40cgo/sec, 0.00/0.00 %(u/s)time, 0.00 %gc (0x)
I160910 05:04:58.752137 1513 storage/raft_transport.go:395  raft transport stream to node 2 established
I160910 05:04:59.742618 1477 gossip/client.go:125  [n3] node 3: started gossip client to 127.0.0.1:46555
I160910 05:05:00.564477 1011 /go/src/google.golang.org/grpc/clientconn.go:667  grpc: addrConn.resetTransport failed to create client transport: connection error: desc = "transport: dial tcp 127.0.0.1:35050: getsockopt: connection refused"; Reconnecting to {"127.0.0.1:35050" <nil>}
I160910 05:05:01.949950 1540 storage/raft_transport.go:395  raft transport stream to node 2 established
I160910 05:05:02.743822 1544 gossip/client.go:125  [n3] node 3: started gossip client to 127.0.0.1:46555
W160910 05:05:03.697030 886 gossip/infostore.go:295  [n2] node unavailable; try another peer
I160910 05:05:05.337868 1011 /go/src/google.golang.org/grpc/clientconn.go:667  grpc: addrConn.resetTransport failed to create client transport: connection error: desc = "transport: dial tcp 127.0.0.1:35050: getsockopt: connection refused"; Reconnecting to {"127.0.0.1:35050" <nil>}
I160910 05:05:05.744719 1535 gossip/client.go:125  [n3] node 3: started gossip client to 127.0.0.1:46555
I160910 05:05:06.949892 1517 storage/raft_transport.go:395  raft transport stream to node 2 established
I160910 05:05:08.697202 888 server/status/runtime.go:207  runtime stats: 174 MiB RSS, 161 goroutines, 14 MiB/4.6 MiB/29 MiB GO alloc/idle/total, 42 MiB/50 MiB CGO alloc/total, 7.80cgo/sec, 0.00/0.00 %(u/s)time, 0.00 %gc (0x)
W160910 05:05:08.697533 886 gossip/infostore.go:295  [n2] node unavailable; try another peer
W160910 05:05:08.701319 890 server/node.go:670  [n2] error recording status summaries: node unavailable; try another peer
W160910 05:05:08.714248 889 ts/db.go:104  node unavailable; try another peer
I160910 05:05:08.745435 1597 gossip/client.go:125  [n3] node 3: started gossip client to 127.0.0.1:46555
I160910 05:05:08.746654 795 server/status/runtime.go:207  runtime stats: 174 MiB RSS, 161 goroutines, 14 MiB/4.6 MiB/29 MiB GO alloc/idle/total, 42 MiB/50 MiB CGO alloc/total, 7.80cgo/sec, 0.00/0.00 %(u/s)time, 0.00 %gc (0x)
I160910 05:05:10.949904 1612 storage/raft_transport.go:395  raft transport stream to node 2 established
I160910 05:05:11.746240 1620 gossip/client.go:125  [n3] node 3: started gossip client to 127.0.0.1:46555
I160910 05:05:12.282805 1011 /go/src/google.golang.org/grpc/clientconn.go:667  grpc: addrConn.resetTransport failed to create client transport: connection error: desc = "transport: dial tcp 127.0.0.1:35050: getsockopt: connection refused"; Reconnecting to {"127.0.0.1:35050" <nil>}
W160910 05:05:13.697055 886 gossip/infostore.go:295  [n2] node unavailable; try another peer
I160910 05:05:14.747018 1636 gossip/client.go:125  [n3] node 3: started gossip client to 127.0.0.1:46555
I160910 05:05:15.150073 1557 storage/raft_transport.go:395  raft transport stream to node 2 established
I160910 05:05:17.747673 1559 gossip/client.go:125  [n3] node 3: started gossip client to 127.0.0.1:46555
W160910 05:05:18.697177 886 gossip/infostore.go:295  [n2] node unavailable; try another peer
I160910 05:05:18.697243 888 server/status/runtime.go:207  runtime stats: 174 MiB RSS, 161 goroutines, 14 MiB/4.0 MiB/29 MiB GO alloc/idle/total, 42 MiB/50 MiB CGO alloc/total, 6.40cgo/sec, 0.00/0.00 %(u/s)time, 0.00 %gc (0x)
W160910 05:05:18.700879 890 server/node.go:670  [n2] error recording status summaries: node unavailable; try another peer
W160910 05:05:18.714407 889 ts/db.go:104  node unavailable; try another peer
I160910 05:05:18.746772 795 server/status/runtime.go:207  runtime stats: 174 MiB RSS, 161 goroutines, 14 MiB/4.0 MiB/29 MiB GO alloc/idle/total, 42 MiB/50 MiB CGO alloc/total, 6.40cgo/sec, 0.00/0.00 %(u/s)time, 0.00 %gc (0x)
I160910 05:05:18.749996 1643 storage/raft_transport.go:395  raft transport stream to node 2 established
I160910 05:05:20.748533 1647 gossip/client.go:125  [n3] node 3: started gossip client to 127.0.0.1:46555
I160910 05:05:22.549955 1685 storage/raft_transport.go:395  raft transport stream to node 2 established
W160910 05:05:23.697042 886 gossip/infostore.go:295  [n2] node unavailable; try another peer
I160910 05:05:23.749187 1656 gossip/client.go:125  [n3] node 3: started gossip client to 127.0.0.1:46555
I160910 05:05:23.991967 1011 /go/src/google.golang.org/grpc/clientconn.go:667  grpc: addrConn.resetTransport failed to create client transport: connection error: desc = "transport: dial tcp 127.0.0.1:35050: getsockopt: connection refused"; Reconnecting to {"127.0.0.1:35050" <nil>}
I160910 05:05:26.749857 1734 gossip/client.go:125  [n3] node 3: started gossip client to 127.0.0.1:46555
I160910 05:05:26.749990 1691 storage/raft_transport.go:395  raft transport stream to node 2 established
I160910 05:05:28.697005 886 gossip/gossip.go:422  [n2] gossip status (ok, 3 nodes)
gossip client (0/3 cur/max conns)
gossip server (0/3 cur/max conns, infos 13/17 sent/received, bytes 4832B/5345B sent/received)
W160910 05:05:28.697067 886 gossip/infostore.go:295  [n2] node unavailable; try another peer
I160910 05:05:28.697120 888 server/status/runtime.go:207  runtime stats: 174 MiB RSS, 161 goroutines, 15 MiB/3.2 MiB/29 MiB GO alloc/idle/total, 42 MiB/50 MiB CGO alloc/total, 8.80cgo/sec, 0.00/0.00 %(u/s)time, 0.00 %gc (0x)
W160910 05:05:28.700878 890 server/node.go:670  [n2] error recording status summaries: node unavailable; try another peer
W160910 05:05:28.710014 949 storage/store.go:1061  [n2,s2] error gossiping system config: node unavailable; try another peer
W160910 05:05:28.710055 948 gossip/infostore.go:295  [n2] node unavailable; try another peer
W160910 05:05:28.710103 948 storage/store.go:1042  [n2,s2] error gossiping first range data: node unavailable; try another peer
W160910 05:05:28.714287 889 ts/db.go:104  node unavailable; try another peer
I160910 05:05:28.745988 793 gossip/gossip.go:422  [n3] gossip status (ok, 3 nodes)
gossip client (0/3 cur/max conns)
gossip server (0/3 cur/max conns, infos 332/30 sent/received, bytes 147902B/16592B sent/received)
I160910 05:05:28.746684 795 server/status/runtime.go:207  runtime stats: 174 MiB RSS, 161 goroutines, 15 MiB/3.2 MiB/29 MiB GO alloc/idle/total, 42 MiB/50 MiB CGO alloc/total, 8.80cgo/sec, 0.00/0.00 %(u/s)time, 0.00 %gc (0x)
F160910 05:05:28.749694 1072 storage/replica.go:2831  [n3,s3,r1{/Min-/Max}] store 3 belongs to cluster {ecd165d7-6063-4b00-ba71-9cc5718976a0}, but attempted to join cluster 925ec2b5-1966-4a8c-97bc-7459644d7ff6 via gossip
goroutine 1072 [running]:
github.com/cockroachdb/cockroach/util/log.getStacks(0x401, 0x2caf6f2a, 0x22a9260, 0xc420c23968)
	/go/src/github.com/cockroachdb/cockroach/util/log/clog.go:880 +0xa5
github.com/cockroachdb/cockroach/util/log.(*loggingT).outputLogEntry(0x22aa360, 0xc400000003, 0x1c53302, 0x12, 0xb0f, 0xc421172dc0, 0xa6)
	/go/src/github.com/cockroachdb/cockroach/util/log/clog.go:745 +0x78d
github.com/cockroachdb/cockroach/util/log.addStructured(0x7f307b769b00, 0xc420a20de0, 0x3, 0x2, 0x1662b4d, 0x4b, 0xc420c23cc8, 0x3, 0x3)
	/go/src/github.com/cockroachdb/cockroach/util/log/structured.go:72 +0x1f3
github.com/cockroachdb/cockroach/util/log.logDepth(0x7f307b769b00, 0xc420a20de0, 0x1, 0xc400000003, 0x1662b4d, 0x4b, 0xc420c23cc8, 0x3, 0x3)
	/go/src/github.com/cockroachdb/cockroach/util/log/log.go:88 +0x8c
github.com/cockroachdb/cockroach/util/log.Fatalf(0x7f307b769b00, 0xc420a20de0, 0x1662b4d, 0x4b, 0xc420c23cc8, 0x3, 0x3)
	/go/src/github.com/cockroachdb/cockroach/util/log/log.go:172 +0x7e
github.com/cockroachdb/cockroach/storage.(*Replica).maybeGossipFirstRange(0xc42017f200, 0x0)
	/go/src/github.com/cockroachdb/cockroach/storage/replica.go:2831 +0x650
github.com/cockroachdb/cockroach/storage.(*Store).maybeGossipFirstRange(0xc420e01400, 0xc420c8faa0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/storage/store.go:1084 +0x192
github.com/cockroachdb/cockroach/storage.(*Store).startGossip.func1()
	/go/src/github.com/cockroachdb/cockroach/storage/store.go:1041 +0x20d
github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker.func1(0xc421104ab0, 0xc4211d2cb0)
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:187 +0x7d
created by github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:188 +0x66

goroutine 1 [chan receive, 1 minutes]:
testing.(*T).Run(0xc42009e0c0, 0x1633682, 0x1a, 0x176cc00, 0xc420283c01)
	/usr/local/go/src/testing/testing.go:647 +0x316
testing.RunTests.func1(0xc42009e0c0)
	/usr/local/go/src/testing/testing.go:793 +0x6d
testing.tRunner(0xc42009e0c0, 0xc420332e00)
	/usr/local/go/src/testing/testing.go:610 +0x81
testing.RunTests(0x176dc98, 0x1f5b980, 0x4, 0x4, 0x22f7be0)
	/usr/local/go/src/testing/testing.go:799 +0x2f5
testing.(*M).Run(0xc420332ef8, 0x22f77c0)
	/usr/local/go/src/testing/testing.go:743 +0x85
github.com/cockroachdb/cockroach/testutils/testcluster.TestMain(0xc420332ef8)
	/go/src/github.com/cockroachdb/cockroach/testutils/testcluster/main_test.go:34 +0x92
main.main()
	github.com/cockroachdb/cockroach/testutils/testcluster/_test/_testmain.go:58 +0xc6

goroutine 17 [syscall, 1 minutes, locked to thread]:
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:2086 +0x1

goroutine 18 [chan receive]:
github.com/cockroachdb/cockroach/util/log.(*loggingT).flushDaemon(0x22aa360)
	/go/src/github.com/cockroachdb/cockroach/util/log/clog.go:1032 +0x77
created by github.com/cockroachdb/cockroach/util/log.init.1
	/go/src/github.com/cockroachdb/cockroach/util/log/clog.go:613 +0x95

goroutine 303 [semacquire]:
sync.runtime_notifyListWait(0xc421226c90, 0x0)
	/usr/local/go/src/runtime/sema.go:267 +0x122
sync.(*Cond).Wait(0xc421226c80)
	/usr/local/go/src/sync/cond.go:57 +0x80
github.com/cockroachdb/cockroach/util/stop.(*Stopper).Quiesce(0xc421216990)
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:410 +0x1f5
github.com/cockroachdb/cockroach/util/stop.(*Stopper).Stop(0xc421216990)
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:352 +0x17f
github.com/cockroachdb/cockroach/testutils/testcluster.(*TestCluster).stopServers(0xc420014300)
	/go/src/github.com/cockroachdb/cockroach/testutils/testcluster/testcluster.go:84 +0xba
github.com/cockroachdb/cockroach/testutils/testcluster.(*TestCluster).(github.com/cockroachdb/cockroach/testutils/testcluster.stopServers)-fm()
	/go/src/github.com/cockroachdb/cockroach/testutils/testcluster/testcluster.go:154 +0x2a
github.com/cockroachdb/cockroach/util/stop.CloserFn.Close(0xc421238f50)
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:86 +0x19
github.com/cockroachdb/cockroach/util/stop.(*Stopper).Stop(0xc420184120)
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:358 +0x214
github.com/cockroachdb/cockroach/testutils/testcluster.TestBasicManualReplication(0xc420c720c0)
	/go/src/github.com/cockroachdb/cockroach/testutils/testcluster/testcluster_test.go:170 +0x37a
testing.tRunner(0xc420c720c0, 0x176cc00)
	/usr/local/go/src/testing/testing.go:610 +0x81
created by testing.(*T).Run
	/usr/local/go/src/testing/testing.go:646 +0x2ec

goroutine 662 [IO wait]:
net.runtime_pollWait(0x7f307b76ac38, 0x72, 0x5)
	/usr/local/go/src/runtime/netpoll.go:160 +0x59
net.(*pollDesc).wait(0xc420b5b5d0, 0x72, 0xc421585598, 0xc4200100b8)
	/usr/local/go/src/net/fd_poll_runtime.go:73 +0x38
net.(*pollDesc).waitRead(0xc420b5b5d0, 0x1f6ebc0, 0xc4200100b8)
	/usr/local/go/src/net/fd_poll_runtime.go:78 +0x34
net.(*netFD).Read(0xc420b5b570, 0xc42168a000, 0x2000, 0x2000, 0x0, 0x1f6ebc0, 0xc4200100b8)
	/usr/local/go/src/net/fd_unix.go:243 +0x1a1
net.(*conn).Read(0xc420c501b0, 0xc42168a000, 0x2000, 0x2000, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/net.go:173 +0x70
github.com/cockroachdb/cmux.(*MuxConn).Read(0xc4203f3810, 0xc42168a000, 0x2000, 0x2000, 0x1597740, 0x0, 0x7f307b643d28)
	/go/src/github.com/cockroachdb/cmux/cmux.go:218 +0x113
crypto/tls.(*block).readFromUntil(0xc4216203f0, 0x7f307b643d28, 0xc4203f3810, 0x5, 0xc4203f3810, 0x0)
	/usr/local/go/src/crypto/tls/conn.go:472 +0x91
crypto/tls.(*Conn).readRecord(0xc421600000, 0x176e617, 0xc421600100, 0x0)
	/usr/local/go/src/crypto/tls/conn.go:574 +0xc4
crypto/tls.(*Conn).Read(0xc421600000, 0xc421646000, 0x8000, 0x8000, 0x0, 0x0, 0x0)
	/usr/local/go/src/crypto/tls/conn.go:1109 +0x116
bufio.(*Reader).fill(0xc421642360)
	/usr/local/go/src/bufio/bufio.go:97 +0x10c
bufio.(*Reader).Read(0xc421642360, 0xc420b770b8, 0x9, 0x9, 0x0, 0xc42003b800, 0x0)
	/usr/local/go/src/bufio/bufio.go:209 +0x1bc
io.ReadAtLeast(0x1f67300, 0xc421642360, 0xc420b770b8, 0x9, 0x9, 0x9, 0xc421585b18, 0x6a7399, 0xc421585b30)
	/usr/local/go/src/io/io.go:307 +0xa4
io.ReadFull(0x1f67300, 0xc421642360, 0xc420b770b8, 0x9, 0x9, 0x6a7399, 0xc421639604, 0xc4204d0ea0)
	/usr/local/go/src/io/io.go:325 +0x58
golang.org/x/net/http2.readFrameHeader(0xc420b770b8, 0x9, 0x9, 0x1f67300, 0xc421642360, 0x0, 0xc400000000, 0xc421585c80, 0xef082f)
	/go/src/golang.org/x/net/http2/frame.go:237 +0x7b
golang.org/x/net/http2.(*Framer).ReadFrame(0xc420b77080, 0x1f70a40, 0xc420dffe90, 0x0, 0x0)
	/go/src/golang.org/x/net/http2/frame.go:464 +0xa4
google.golang.org/grpc/transport.(*framer).readFrame(0xc421620960, 0xc420dffe90, 0xc420dffe90, 0x0, 0x0)
	/go/src/google.golang.org/grpc/transport/http_util.go:505 +0x2f
google.golang.org/grpc/transport.(*http2Server).HandleStreams(0xc421484510, 0xc4216209f0)
	/go/src/google.golang.org/grpc/transport/http2_server.go:260 +0x200
google.golang.org/grpc.(*Server).serveStreams(0xc420a705a0, 0x1f80b20, 0xc421484510)
	/go/src/google.golang.org/grpc/server.go:424 +0x160
google.golang.org/grpc.(*Server).serveNewHTTP2Transport(0xc420a705a0, 0x1f80dc0, 0xc421600000, 0x1f6de00, 0xc421475290)
	/go/src/google.golang.org/grpc/server.go:411 +0x3da
google.golang.org/grpc.(*Server).handleRawConn(0xc420a705a0, 0x1f80e20, 0xc4203f3810)
	/go/src/google.golang.org/grpc/server.go:388 +0x470
created by google.golang.org/grpc.(*Server).Serve
	/go/src/google.golang.org/grpc/server.go:357 +0x1a9

goroutine 1069 [select, 1 minutes]:
github.com/cockroachdb/cockroach/storage.(*Store).raftSnapshotStatusLoop.func1()
	/go/src/github.com/cockroachdb/cockroach/storage/store.go:2659 +0x211
github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker.func1(0xc421104ab0, 0xc4211d2c70)
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:187 +0x7d
created by github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:188 +0x66

goroutine 1063 [select]:
github.com/cockroachdb/cockroach/storage.(*raftScheduler).worker(0xc421207c00, 0xc421104ab0)
	/go/src/github.com/cockroachdb/cockroach/storage/scheduler.go:168 +0x3e7
github.com/cockroachdb/cockroach/storage.(*raftScheduler).Start.func1()
	/go/src/github.com/cockroachdb/cockroach/storage/scheduler.go:160 +0x33
github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker.func1(0xc421104ab0, 0xc420955240)
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:187 +0x7d
created by github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:188 +0x66

goroutine 990 [IO wait]:
net.runtime_pollWait(0x7f307b76a878, 0x72, 0x13)
	/usr/local/go/src/runtime/netpoll.go:160 +0x59
net.(*pollDesc).wait(0xc4207647d0, 0x72, 0xc420e4d598, 0xc4200100b8)
	/usr/local/go/src/net/fd_poll_runtime.go:73 +0x38
net.(*pollDesc).waitRead(0xc4207647d0, 0x1f6ebc0, 0xc4200100b8)
	/usr/local/go/src/net/fd_poll_runtime.go:78 +0x34
net.(*netFD).Read(0xc420764770, 0xc4203e6800, 0x400, 0x400, 0x0, 0x1f6ebc0, 0xc4200100b8)
	/usr/local/go/src/net/fd_unix.go:243 +0x1a1
net.(*conn).Read(0xc42037a078, 0xc4203e6800, 0x400, 0x400, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/net.go:173 +0x70
github.com/cockroachdb/cmux.(*MuxConn).Read(0xc42123abb0, 0xc4203e6800, 0x400, 0x400, 0x1597740, 0x0, 0x7f307b643d28)
	/go/src/github.com/cockroachdb/cmux/cmux.go:218 +0x113
crypto/tls.(*block).readFromUntil(0xc421082f00, 0x7f307b643d28, 0xc42123abb0, 0x5, 0xc42123abb0, 0x0)
	/usr/local/go/src/crypto/tls/conn.go:472 +0x91
crypto/tls.(*Conn).readRecord(0xc420c62380, 0x176e617, 0xc420c62480, 0x0)
	/usr/local/go/src/crypto/tls/conn.go:574 +0xc4
crypto/tls.(*Conn).Read(0xc420c62380, 0xc420fd6000, 0x8000, 0x8000, 0x0, 0x0, 0x0)
	/usr/local/go/src/crypto/tls/conn.go:1109 +0x116
bufio.(*Reader).fill(0xc420310540)
	/usr/local/go/src/bufio/bufio.go:97 +0x10c
bufio.(*Reader).Read(0xc420310540, 0xc420af46f8, 0x9, 0x9, 0x631600, 0xc42148cf70, 0x0)
	/usr/local/go/src/bufio/bufio.go:209 +0x1bc
io.ReadAtLeast(0x1f67300, 0xc420310540, 0xc420af46f8, 0x9, 0x9, 0x9, 0xc420e4dae8, 0x6457d0, 0xc42023da40)
	/usr/local/go/src/io/io.go:307 +0xa4
io.ReadFull(0x1f67300, 0xc420310540, 0xc420af46f8, 0x9, 0x9, 0xc42148cf70, 0x0, 0x1)
	/usr/local/go/src/io/io.go:325 +0x58
golang.org/x/net/http2.readFrameHeader(0xc420af46f8, 0x9, 0x9, 0x1f67300, 0xc420310540, 0x0, 0xc400000000, 0xc420e4dc80, 0xef07f9)
	/go/src/golang.org/x/net/http2/frame.go:237 +0x7b
golang.org/x/net/http2.(*Framer).ReadFrame(0xc420af46c0, 0x2c, 0x2c, 0x0, 0x0)
	/go/src/golang.org/x/net/http2/frame.go:464 +0xa4
google.golang.org/grpc/transport.(*framer).readFrame(0xc420734570, 0xc420dff980, 0xc420dff980, 0x0, 0x0)
	/go/src/google.golang.org/grpc/transport/http_util.go:505 +0x2f
google.golang.org/grpc/transport.(*http2Server).HandleStreams(0xc4203fc510, 0xc420734600)
	/go/src/google.golang.org/grpc/transport/http2_server.go:260 +0x200
google.golang.org/grpc.(*Server).serveStreams(0xc420a02dc0, 0x1f80b20, 0xc4203fc510)
	/go/src/google.golang.org/grpc/server.go:424 +0x160
google.golang.org/grpc.(*Server).serveNewHTTP2Transport(0xc420a02dc0, 0x1f80dc0, 0xc420c62380, 0x1f6de00, 0xc42017c790)
	/go/src/google.golang.org/grpc/server.go:411 +0x3da
google.golang.org/grpc.(*Server).handleRawConn(0xc420a02dc0, 0x1f80e20, 0xc42123abb0)
	/go/src/google.golang.org/grpc/server.go:388 +0x470
created by google.golang.org/grpc.(*Server).Serve
	/go/src/google.golang.org/grpc/server.go:357 +0x1a9

goroutine 891 [select]:
github.com/cockroachdb/cockroach/sql.(*SchemaChangeManager).Start.func1()
	/go/src/github.com/cockroachdb/cockroach/sql/schema_changer.go:704 +0x12c1
github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker.func1(0xc421216990, 0xc421225d40)
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:187 +0x7d
created by github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:188 +0x66

goroutine 1068 [select]:
github.com/cockroachdb/cockroach/storage.(*Store).raftTickLoop.func1()
	/go/src/github.com/cockroachdb/cockroach/storage/store.go:2629 +0x334
github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker.func1(0xc421104ab0, 0xc4211d2c60)
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:187 +0x7d
created by github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:188 +0x66

goroutine 838 [select]:
github.com/cockroachdb/cockroach/gossip.(*Gossip).manage.func1()
	/go/src/github.com/cockroachdb/cockroach/gossip/gossip.go:948 +0x2fb
github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker.func1(0xc421216990, 0xc4207f3ca0)
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:187 +0x7d
created by github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:188 +0x66

goroutine 889 [select]:
github.com/cockroachdb/cockroach/ts.(*poller).start.func1()
	/go/src/github.com/cockroachdb/cockroach/ts/db.go:81 +0x16f
github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker.func1(0xc421216990, 0xc4212bad20)
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:187 +0x7d
created by github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:188 +0x66

goroutine 839 [select, 1 minutes]:
github.com/cockroachdb/cockroach/storage.(*bookie).start.func1()
	/go/src/github.com/cockroachdb/cockroach/storage/reservation.go:274 +0x217
github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker.func1(0xc421216990, 0xc421224c00)
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:187 +0x7d
created by github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:188 +0x66

goroutine 888 [select]:
github.com/cockroachdb/cockroach/server.(*Server).startSampleEnvironment.func1()
	/go/src/github.com/cockroachdb/cockroach/server/server.go:623 +0x16b
github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker.func1(0xc421216990, 0xc421225d00)
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:187 +0x7d
created by github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:188 +0x66

goroutine 890 [select]:
github.com/cockroachdb/cockroach/server.(*Node).startWriteSummaries.func1()
	/go/src/github.com/cockroachdb/cockroach/server/node.go:667 +0x309
github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker.func1(0xc421216990, 0xc421225d20)
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:187 +0x7d
created by github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:188 +0x66

goroutine 885 [select]:
github.com/cockroachdb/cockroach/server.(*Node).startComputePeriodicMetrics.func1()
	/go/src/github.com/cockroachdb/cockroach/server/node.go:631 +0x252
github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker.func1(0xc421216990, 0xc421225c40)
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:187 +0x7d
created by github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:188 +0x66

goroutine 1065 [select]:
github.com/cockroachdb/cockroach/storage.(*raftScheduler).worker(0xc421207c00, 0xc421104ab0)
	/go/src/github.com/cockroachdb/cockroach/storage/scheduler.go:168 +0x3e7
github.com/cockroachdb/cockroach/storage.(*raftScheduler).Start.func1()
	/go/src/github.com/cockroachdb/cockroach/storage/scheduler.go:160 +0x33
github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker.func1(0xc421104ab0, 0xc420955280)
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:187 +0x7d
created by github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:188 +0x66

goroutine 1062 [select]:
github.com/cockroachdb/cockroach/storage.(*raftScheduler).worker(0xc421207c00, 0xc421104ab0)
	/go/src/github.com/cockroachdb/cockroach/storage/scheduler.go:168 +0x3e7
github.com/cockroachdb/cockroach/storage.(*raftScheduler).Start.func1()
	/go/src/github.com/cockroachdb/cockroach/storage/scheduler.go:160 +0x33
github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker.func1(0xc421104ab0, 0xc420955220)
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:187 +0x7d
created by github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:188 +0x66

goroutine 1061 [select]:
github.com/cockroachdb/cockroach/storage.(*raftScheduler).worker(0xc421207c00, 0xc421104ab0)
	/go/src/github.com/cockroachdb/cockroach/storage/scheduler.go:168 +0x3e7
github.com/cockroachdb/cockroach/storage.(*raftScheduler).Start.func1()
	/go/src/github.com/cockroachdb/cockroach/storage/scheduler.go:160 +0x33
github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker.func1(0xc421104ab0, 0xc420955200)
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:187 +0x7d
created by github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:188 +0x66

goroutine 1066 [select]:
github.com/cockroachdb/cockroach/storage.(*raftScheduler).worker(0xc421207c00, 0xc421104ab0)
	/go/src/github.com/cockroachdb/cockroach/storage/scheduler.go:168 +0x3e7
github.com/cockroachdb/cockroach/storage.(*raftScheduler).Start.func1()
	/go/src/github.com/cockroachdb/cockroach/storage/scheduler.go:160 +0x33
github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker.func1(0xc421104ab0, 0xc4209552a0)
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:187 +0x7d
created by github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:188 +0x66

goroutine 1005 [chan receive, 1 minutes]:
github.com/cockroachdb/cockroach/gossip.(*server).start.func3()
	/go/src/github.com/cockroachdb/cockroach/gossip/server.go:370 +0x66
github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker.func1(0xc421104ab0, 0xc421100ae0)
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:187 +0x7d
created by github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:188 +0x66

goroutine 843 [select]:
github.com/cockroachdb/cockroach/rpc.(*Context).runHeartbeat(0xc420bc2280, 0xc42000be00, 0xc4212118c0, 0xf, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/rpc/context.go:294 +0x645
github.com/cockroachdb/cockroach/rpc.(*Context).GRPCDial.func1.1.1()
	/go/src/github.com/cockroachdb/cockroach/rpc/context.go:217 +0x69
github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker.func1(0xc421216990, 0xc4211c6570)
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:187 +0x7d
created by github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:188 +0x66

goroutine 1064 [select]:
github.com/cockroachdb/cockroach/storage.(*raftScheduler).worker(0xc421207c00, 0xc421104ab0)
	/go/src/github.com/cockroachdb/cockroach/storage/scheduler.go:168 +0x3e7
github.com/cockroachdb/cockroach/storage.(*raftScheduler).Start.func1()
	/go/src/github.com/cockroachdb/cockroach/storage/scheduler.go:160 +0x33
github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker.func1(0xc421104ab0, 0xc420955260)
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:187 +0x7d
created by github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:188 +0x66

goroutine 886 [select]:
github.com/cockroachdb/cockroach/server.(*Node).startGossip.func1()
	/go/src/github.com/cockroachdb/cockroach/server/node.go:591 +0x465
github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker.func1(0xc421216990, 0xc42046ce70)
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:187 +0x7d
created by github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:188 +0x66

goroutine 991 [select, 1 minutes]:
google.golang.org/grpc/transport.(*http2Server).controller(0xc4203fc510)
	/go/src/google.golang.org/grpc/transport/http2_server.go:673 +0x69c
created by google.golang.org/grpc/transport.newHTTP2Server
	/go/src/google.golang.org/grpc/transport/http2_server.go:139 +0x767

goroutine 1046 [select]:
github.com/cockroachdb/cockroach/storage.(*raftScheduler).worker(0xc421207c00, 0xc421104ab0)
	/go/src/github.com/cockroachdb/cockroach/storage/scheduler.go:168 +0x3e7
github.com/cockroachdb/cockroach/storage.(*raftScheduler).Start.func1()
	/go/src/github.com/cockroachdb/cockroach/storage/scheduler.go:160 +0x33
github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker.func1(0xc421104ab0, 0xc420955000)
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:187 +0x7d
created by github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:188 +0x66

goroutine 1045 [select]:
github.com/cockroachdb/cockroach/storage.(*raftScheduler).worker(0xc421207c00, 0xc421104ab0)
	/go/src/github.com/cockroachdb/cockroach/storage/scheduler.go:168 +0x3e7
github.com/cockroachdb/cockroach/storage.(*raftScheduler).Start.func1()
	/go/src/github.com/cockroachdb/cockroach/storage/scheduler.go:160 +0x33
github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker.func1(0xc421104ab0, 0xc420954fe0)
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:187 +0x7d
created by github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:188 +0x66

goroutine 830 [select]:
github.com/cockroachdb/cockroach/storage.(*raftScheduler).worker(0xc421207c00, 0xc421104ab0)
	/go/src/github.com/cockroachdb/cockroach/storage/scheduler.go:168 +0x3e7
github.com/cockroachdb/cockroach/storage.(*raftScheduler).Start.func1()
	/go/src/github.com/cockroachdb/cockroach/storage/scheduler.go:160 +0x33
github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker.func1(0xc421104ab0, 0xc420954ee0)
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:187 +0x7d
created by github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:188 +0x66

goroutine 1071 [select]:
github.com/cockroachdb/cockroach/storage.(*Store).Start.func3()
	/go/src/github.com/cockroachdb/cockroach/storage/store.go:964 +0x165
github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker.func1(0xc421104ab0, 0xc420955340)
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:187 +0x7d
created by github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:188 +0x66

goroutine 1043 [select]:
github.com/cockroachdb/cockroach/storage.(*raftScheduler).worker(0xc421207c00, 0xc421104ab0)
	/go/src/github.com/cockroachdb/cockroach/storage/scheduler.go:168 +0x3e7
github.com/cockroachdb/cockroach/storage.(*raftScheduler).Start.func1()
	/go/src/github.com/cockroachdb/cockroach/storage/scheduler.go:160 +0x33
github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker.func1(0xc421104ab0, 0xc420954fa0)
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:187 +0x7d
created by github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:188 +0x66

goroutine 1042 [select]:
github.com/cockroachdb/cockroach/storage.(*raftScheduler).worker(0xc421207c00, 0xc421104ab0)
	/go/src/github.com/cockroachdb/cockroach/storage/scheduler.go:168 +0x3e7
github.com/cockroachdb/cockroach/storage.(*raftScheduler).Start.func1()
	/go/src/github.com/cockroachdb/cockroach/storage/scheduler.go:160 +0x33
github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker.func1(0xc421104ab0, 0xc420954f80)
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:187 +0x7d
created by github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:188 +0x66

goroutine 655 [select, 1 minutes]:
github.com/cockroachdb/cockroach/storage.(*bookie).start.func1()
	/go/src/github.com/cockroachdb/cockroach/storage/reservation.go:274 +0x217
github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker.func1(0xc421216990, 0xc420bfab80)
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:187 +0x7d
created by github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:188 +0x66

goroutine 992 [IO wait]:
net.runtime_pollWait(0x7f307b76a1b8, 0x72, 0x12)
	/usr/local/go/src/runtime/netpoll.go:160 +0x59
net.(*pollDesc).wait(0xc4211d0990, 0x72, 0xc4211ef828, 0xc4200100b8)
	/usr/local/go/src/net/fd_poll_runtime.go:73 +0x38
net.(*pollDesc).waitRead(0xc4211d0990, 0x1f6ebc0, 0xc4200100b8)
	/usr/local/go/src/net/fd_poll_runtime.go:78 +0x34
net.(*netFD).Read(0xc4211d0930, 0xc4204cfc00, 0x400, 0x400, 0x0, 0x1f6ebc0, 0xc4200100b8)
	/usr/local/go/src/net/fd_unix.go:243 +0x1a1
net.(*conn).Read(0xc42037a068, 0xc4204cfc00, 0x400, 0x400, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/net.go:173 +0x70
crypto/tls.(*block).readFromUntil(0xc4210831d0, 0x7f307b643d00, 0xc42037a068, 0x5, 0xc42037a068, 0xc4211701a0)
	/usr/local/go/src/crypto/tls/conn.go:472 +0x91
crypto/tls.(*Conn).readRecord(0xc420c62000, 0x176e617, 0xc420c62100, 0xc420b1cfc0)
	/usr/local/go/src/crypto/tls/conn.go:574 +0xc4
crypto/tls.(*Conn).Read(0xc420c62000, 0xc420ff6000, 0x8000, 0x8000, 0x0, 0x0, 0x0)
	/usr/local/go/src/crypto/tls/conn.go:1109 +0x116
bufio.(*Reader).fill(0xc420310840)
	/usr/local/go/src/bufio/bufio.go:97 +0x10c
bufio.(*Reader).Read(0xc420310840, 0xc420af47b8, 0x9, 0x9, 0xc4211efca8, 0x6457d0, 0xc420c11e80)
	/usr/local/go/src/bufio/bufio.go:209 +0x1bc
io.ReadAtLeast(0x1f67300, 0xc420310840, 0xc420af47b8, 0x9, 0x9, 0x9, 0xc421621240, 0xc421621238, 0x1f6b1c0)
	/usr/local/go/src/io/io.go:307 +0xa4
io.ReadFull(0x1f67300, 0xc420310840, 0xc420af47b8, 0x9, 0x9, 0xc4211efeb0, 0xeec4b0, 0xc4201d0ff0)
	/usr/local/go/src/io/io.go:325 +0x58
golang.org/x/net/http2.readFrameHeader(0xc420af47b8, 0x9, 0x9, 0x1f67300, 0xc420310840, 0x0, 0xc400000000, 0xc4211701a0, 0xc)
	/go/src/golang.org/x/net/http2/frame.go:237 +0x7b
golang.org/x/net/http2.(*Framer).ReadFrame(0xc420af4780, 0x0, 0x0, 0x0, 0x0)
	/go/src/golang.org/x/net/http2/frame.go:464 +0xa4
google.golang.org/grpc/transport.(*framer).readFrame(0xc420734690, 0xc421131680, 0xc421131680, 0x0, 0x0)
	/go/src/google.golang.org/grpc/transport/http_util.go:505 +0x2f
google.golang.org/grpc/transport.(*http2Client).reader(0xc420279d00)
	/go/src/google.golang.org/grpc/transport/http2_client.go:921 +0xb6
created by google.golang.org/grpc/transport.newHTTP2Client
	/go/src/google.golang.org/grpc/transport/http2_client.go:203 +0x8b1

goroutine 1007 [select]:
github.com/cockroachdb/cockroach/gossip.(*Gossip).manage.func1()
	/go/src/github.com/cockroachdb/cockroach/gossip/gossip.go:948 +0x2fb
github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker.func1(0xc421104ab0, 0xc4207f29e0)
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:187 +0x7d
created by github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:188 +0x66

goroutine 832 [select]:
github.com/cockroachdb/cockroach/storage.(*raftScheduler).worker(0xc421207c00, 0xc421104ab0)
	/go/src/github.com/cockroachdb/cockroach/storage/scheduler.go:168 +0x3e7
github.com/cockroachdb/cockroach/storage.(*raftScheduler).Start.func1()
	/go/src/github.com/cockroachdb/cockroach/storage/scheduler.go:160 +0x33
github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker.func1(0xc421104ab0, 0xc420954f20)
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:187 +0x7d
created by github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:188 +0x66

goroutine 1000 [chan receive, 1 minutes]:
github.com/cockroachdb/cmux.(*muxListener).Accept(0xc421100980, 0xc420b012f0, 0x14d4320, 0x1f516d0, 0x1557520)
	<autogenerated>:9 +0x7f
net/http.(*Server).Serve(0xc4210ceb80, 0x1f79300, 0xc421100980, 0x0, 0x0)
	/usr/local/go/src/net/http/server.go:2273 +0x1ce
github.com/cockroachdb/cockroach/server.(*Server).Start.func4()
	/go/src/github.com/cockroachdb/cockroach/server/server.go:394 +0x3c
github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker.func1(0xc421104ab0, 0xc4211009e0)
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:187 +0x7d
created by github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:188 +0x66

goroutine 993 [select, 1 minutes]:
google.golang.org/grpc/transport.(*http2Client).controller(0xc420279d00)
	/go/src/google.golang.org/grpc/transport/http2_client.go:999 +0x59d
created by google.golang.org/grpc/transport.newHTTP2Client
	/go/src/google.golang.org/grpc/transport/http2_client.go:233 +0xe78

goroutine 1060 [select]:
github.com/cockroachdb/cockroach/storage.(*raftScheduler).worker(0xc421207c00, 0xc421104ab0)
	/go/src/github.com/cockroachdb/cockroach/storage/scheduler.go:168 +0x3e7
github.com/cockroachdb/cockroach/storage.(*raftScheduler).Start.func1()
	/go/src/github.com/cockroachdb/cockroach/storage/scheduler.go:160 +0x33
github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker.func1(0xc421104ab0, 0xc4209551e0)
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:187 +0x7d
created by github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:188 +0x66

goroutine 1047 [select]:
github.com/cockroachdb/cockroach/storage.(*raftScheduler).worker(0xc421207c00, 0xc421104ab0)
	/go/src/github.com/cockroachdb/cockroach/storage/scheduler.go:168 +0x3e7
github.com/cockroachdb/cockroach/storage.(*raftScheduler).Start.func1()
	/go/src/github.com/cockroachdb/cockroach/storage/scheduler.go:160 +0x33
github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker.func1(0xc421104ab0, 0xc420955020)
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:187 +0x7d
created by github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:188 +0x66

goroutine 1044 [select]:
github.com/cockroachdb/cockroach/storage.(*raftScheduler).worker(0xc421207c00, 0xc421104ab0)
	/go/src/github.com/cockroachdb/cockroach/storage/scheduler.go:168 +0x3e7
github.com/cockroachdb/cockroach/storage.(*raftScheduler).Start.func1()
	/go/src/github.com/cockroachdb/cockroach/storage/scheduler.go:160 +0x33
github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker.func1(0xc421104ab0, 0xc420954fc0)
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:187 +0x7d
created by github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:188 +0x66

goroutine 833 [select]:
github.com/cockroachdb/cockroach/storage.(*raftScheduler).worker(0xc421207c00, 0xc421104ab0)
	/go/src/github.com/cockroachdb/cockroach/storage/scheduler.go:168 +0x3e7
github.com/cockroachdb/cockroach/storage.(*raftScheduler).Start.func1()
	/go/src/github.com/cockroachdb/cockroach/storage/scheduler.go:160 +0x33
github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker.func1(0xc421104ab0, 0xc420954f40)
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:187 +0x7d
created by github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:188 +0x66

goroutine 1011 [select]:
google.golang.org/grpc.(*addrConn).resetTransport(0xc420b09400, 0xc420015900, 0x0, 0x0)
	/go/src/google.golang.org/grpc/clientconn.go:683 +0x70f
google.golang.org/grpc.(*addrConn).transportMonitor(0xc420b09400)
	/go/src/google.golang.org/grpc/clientconn.go:763 +0x362
google.golang.org/grpc.(*ClientConn).resetAddrConn.func1(0xc420b09400)
	/go/src/google.golang.org/grpc/clientconn.go:479 +0x1de
created by google.golang.org/grpc.(*ClientConn).resetAddrConn
	/go/src/google.golang.org/grpc/clientconn.go:480 +0x3c7

goroutine 792 [select]:
github.com/cockroachdb/cockroach/server.(*Node).startComputePeriodicMetrics.func1()
	/go/src/github.com/cockroachdb/cockroach/server/node.go:631 +0x252
github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker.func1(0xc421104ab0, 0xc4212ac340)
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:187 +0x7d
created by github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:188 +0x66

goroutine 831 [select]:
github.com/cockroachdb/cockroach/storage.(*raftScheduler).worker(0xc421207c00, 0xc421104ab0)
	/go/src/github.com/cockroachdb/cockroach/storage/scheduler.go:168 +0x3e7
github.com/cockroachdb/cockroach/storage.(*raftScheduler).Start.func1()
	/go/src/github.com/cockroachdb/cockroach/storage/scheduler.go:160 +0x33
github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker.func1(0xc421104ab0, 0xc420954f00)
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:187 +0x7d
created by github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:188 +0x66

goroutine 817 [chan receive]:
github.com/cockroachdb/cockroach/server.(*Server).Start.func6()
	/go/src/github.com/cockroachdb/cockroach/server/server.go:407 +0xcc
github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker.func1(0xc421216990, 0xc421224920)
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:187 +0x7d
created by github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:188 +0x66

goroutine 829 [select]:
github.com/cockroachdb/cockroach/storage.(*raftScheduler).worker(0xc421207c00, 0xc421104ab0)
	/go/src/github.com/cockroachdb/cockroach/storage/scheduler.go:168 +0x3e7
github.com/cockroachdb/cockroach/storage.(*raftScheduler).Start.func1()
	/go/src/github.com/cockroachdb/cockroach/storage/scheduler.go:160 +0x33
github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker.func1(0xc421104ab0, 0xc420954ec0)
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:187 +0x7d
created by github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:188 +0x66

goroutine 1049 [select]:
github.com/cockroachdb/cockroach/storage.(*raftScheduler).worker(0xc421207c00, 0xc421104ab0)
	/go/src/github.com/cockroachdb/cockroach/storage/scheduler.go:168 +0x3e7
github.com/cockroachdb/cockroach/storage.(*raftScheduler).Start.func1()
	/go/src/github.com/cockroachdb/cockroach/storage/scheduler.go:160 +0x33
github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker.func1(0xc421104ab0, 0xc420955060)
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:187 +0x7d
created by github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:188 +0x66

goroutine 1051 [select]:
github.com/cockroachdb/cockroach/storage.(*raftScheduler).worker(0xc421207c00, 0xc421104ab0)
	/go/src/github.com/cockroachdb/cockroach/storage/scheduler.go:168 +0x3e7
github.com/cockroachdb/cockroach/storage.(*raftScheduler).Start.func1()
	/go/src/github.com/cockroachdb/cockroach/storage/scheduler.go:160 +0x33
github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker.func1(0xc421104ab0, 0xc4209550a0)
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:187 +0x7d
created by github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:188 +0x66

goroutine 1052 [select]:
github.com/cockroachdb/cockroach/storage.(*raftScheduler).worker(0xc421207c00, 0xc421104ab0)
	/go/src/github.com/cockroachdb/cockroach/storage/scheduler.go:168 +0x3e7
github.com/cockroachdb/cockroach/storage.(*raftScheduler).Start.func1()
	/go/src/github.com/cockroachdb/cockroach/storage/scheduler.go:160 +0x33
github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker.func1(0xc421104ab0, 0xc4209550c0)
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:187 +0x7d
created by github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:188 +0x66

goroutine 1054 [select]:
github.com/cockroachdb/cockroach/storage.(*raftScheduler).worker(0xc421207c00, 0xc421104ab0)
	/go/src/github.com/cockroachdb/cockroach/storage/scheduler.go:168 +0x3e7
github.com/cockroachdb/cockroach/storage.(*raftScheduler).Start.func1()
	/go/src/github.com/cockroachdb/cockroach/storage/scheduler.go:160 +0x33
github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker.func1(0xc421104ab0, 0xc420955100)
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:187 +0x7d
created by github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:188 +0x66

goroutine 1053 [select]:
github.com/cockroachdb/cockroach/storage.(*raftScheduler).worker(0xc421207c00, 0xc421104ab0)
	/go/src/github.com/cockroachdb/cockroach/storage/scheduler.go:168 +0x3e7
github.com/cockroachdb/cockroach/storage.(*raftScheduler).Start.func1()
	/go/src/github.com/cockroachdb/cockroach/storage/scheduler.go:160 +0x33
github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker.func1(0xc421104ab0, 0xc4209550e0)
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:187 +0x7d
created by github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:188 +0x66

goroutine 1055 [select]:
github.com/cockroachdb/cockroach/storage.(*raftScheduler).worker(0xc421207c00, 0xc421104ab0)
	/go/src/github.com/cockroachdb/cockroach/storage/scheduler.go:168 +0x3e7
github.com/cockroachdb/cockroach/storage.(*raftScheduler).Start.func1()
	/go/src/github.com/cockroachdb/cockroach/storage/scheduler.go:160 +0x33
github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker.func1(0xc421104ab0, 0xc420955120)
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:187 +0x7d
created by github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:188 +0x66

goroutine 1056 [select]:
github.com/cockroachdb/cockroach/storage.(*raftScheduler).worker(0xc421207c00, 0xc421104ab0)
	/go/src/github.com/cockroachdb/cockroach/storage/scheduler.go:168 +0x3e7
github.com/cockroachdb/cockroach/storage.(*raftScheduler).Start.func1()
	/go/src/github.com/cockroachdb/cockroach/storage/scheduler.go:160 +0x33
github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker.func1(0xc421104ab0, 0xc420955160)
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:187 +0x7d
created by github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:188 +0x66

goroutine 1058 [select]:
github.com/cockroachdb/cockroach/storage.(*raftScheduler).worker(0xc421207c00, 0xc421104ab0)
	/go/src/github.com/cockroachdb/cockroach/storage/scheduler.go:168 +0x3e7
github.com/cockroachdb/cockroach/storage.(*raftScheduler).Start.func1()
	/go/src/github.com/cockroachdb/cockroach/storage/scheduler.go:160 +0x33
github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker.func1(0xc421104ab0, 0xc4209551a0)
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:187 +0x7d
created by github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:188 +0x66

goroutine 1057 [select]:
github.com/cockroachdb/cockroach/storage.(*raftScheduler).worker(0xc421207c00, 0xc421104ab0)
	/go/src/github.com/cockroachdb/cockroach/storage/scheduler.go:168 +0x3e7
github.com/cockroachdb/cockroach/storage.(*raftScheduler).Start.func1()
	/go/src/github.com/cockroachdb/cockroach/storage/scheduler.go:160 +0x33
github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker.func1(0xc421104ab0, 0xc420955180)
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:187 +0x7d
created by github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:188 +0x66

goroutine 1059 [select]:
github.com/cockroachdb/cockroach/storage.(*raftScheduler).worker(0xc421207c00, 0xc421104ab0)
	/go/src/github.com/cockroachdb/cockroach/storage/scheduler.go:168 +0x3e7
github.com/cockroachdb/cockroach/storage.(*raftScheduler).Start.func1()
	/go/src/github.com/cockroachdb/cockroach/storage/scheduler.go:160 +0x33
github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker.func1(0xc421104ab0, 0xc4209551c0)
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:187 +0x7d
created by github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:188 +0x66

goroutine 1050 [select]:
github.com/cockroachdb/cockroach/storage.(*raftScheduler).worker(0xc421207c00, 0xc421104ab0)
	/go/src/github.com/cockroachdb/cockroach/storage/scheduler.go:168 +0x3e7
github.com/cockroachdb/cockroach/storage.(*raftScheduler).Start.func1()
	/go/src/github.com/cockroachdb/cockroach/storage/scheduler.go:160 +0x33
github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker.func1(0xc421104ab0, 0xc420955080)
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:187 +0x7d
created by github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:188 +0x66

goroutine 1048 [select]:
github.com/cockroachdb/cockroach/storage.(*raftScheduler).worker(0xc421207c00, 0xc421104ab0)
	/go/src/github.com/cockroachdb/cockroach/storage/scheduler.go:168 +0x3e7
github.com/cockroachdb/cockroach/storage.(*raftScheduler).Start.func1()
	/go/src/github.com/cockroachdb/cockroach/storage/scheduler.go:160 +0x33
github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker.func1(0xc421104ab0, 0xc420955040)
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:187 +0x7d
created by github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:188 +0x66

goroutine 910 [semacquire]:
sync.runtime_Semacquire(0xc421210a8c)
	/usr/local/go/src/runtime/sema.go:47 +0x30
sync.(*WaitGroup).Wait(0xc421210a80)
	/usr/local/go/src/sync/waitgroup.go:131 +0x97
google.golang.org/grpc.(*Server).serveStreams(0xc420a705a0, 0x1f80b20, 0xc4211045a0)
	/go/src/google.golang.org/grpc/server.go:425 +0x16e
google.golang.org/grpc.(*Server).serveNewHTTP2Transport(0xc420a705a0, 0x1f80dc0, 0xc420b40380, 0x1f6de00, 0xc42021da20)
	/go/src/google.golang.org/grpc/server.go:411 +0x3da
google.golang.org/grpc.(*Server).handleRawConn(0xc420a705a0, 0x1f80e20, 0xc42021c160)
	/go/src/google.golang.org/grpc/server.go:388 +0x470
created by google.golang.org/grpc.(*Server).Serve
	/go/src/google.golang.org/grpc/server.go:357 +0x1a9

goroutine 818 [chan receive, 1 minutes]:
github.com/cockroachdb/cockroach/storage/engine.(*RocksDB).Open.func1(0xc42119d2c0)
	/go/src/github.com/cockroachdb/cockroach/storage/engine/rocksdb.go:390 +0x44
created by github.com/cockroachdb/cockroach/storage/engine.(*RocksDB).Open
	/go/src/github.com/cockroachdb/cockroach/storage/engine/rocksdb.go:391 +0x6eb

goroutine 828 [select]:
github.com/cockroachdb/cockroach/storage.(*raftScheduler).worker(0xc421207c00, 0xc421104ab0)
	/go/src/github.com/cockroachdb/cockroach/storage/scheduler.go:168 +0x3e7
github.com/cockroachdb/cockroach/storage.(*raftScheduler).Start.func1()
	/go/src/github.com/cockroachdb/cockroach/storage/scheduler.go:160 +0x33
github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker.func1(0xc421104ab0, 0xc420954ea0)
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:187 +0x7d
created by github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:188 +0x66

goroutine 208 [select, 1 minutes]:
github.com/cockroachdb/cockroach/storage.(*StorePool).start.func1()
	/go/src/github.com/cockroachdb/cockroach/storage/store_pool.go:340 +0x3da
github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker.func1(0xc421104ab0, 0xc4211003c0)
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:187 +0x7d
created by github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:188 +0x66

goroutine 812 [chan receive, 1 minutes]:
github.com/cockroachdb/cockroach/util/netutil.MakeServer.func2()
	/go/src/github.com/cockroachdb/cockroach/util/netutil/net.go:100 +0x70
github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker.func1(0xc421216990, 0xc4212246e0)
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:187 +0x7d
created by github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:188 +0x66

goroutine 811 [chan receive, 1 minutes]:
github.com/cockroachdb/cockroach/util/netutil.MakeServer.func2()
	/go/src/github.com/cockroachdb/cockroach/util/netutil/net.go:100 +0x70
github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker.func1(0xc421216990, 0xc421224680)
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:187 +0x7d
created by github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:188 +0x66

goroutine 809 [select]:
github.com/cockroachdb/cockroach/sql.(*LeaseManager).RefreshLeases.func1()
	/go/src/github.com/cockroachdb/cockroach/sql/lease.go:1143 +0xcc1
github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker.func1(0xc421216990, 0xc421212d20)
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:187 +0x7d
created by github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:188 +0x66

goroutine 810 [select]:
github.com/cockroachdb/cockroach/sql.NewExecutor.func1()
	/go/src/github.com/cockroachdb/cockroach/sql/executor.go:270 +0x175
github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker.func1(0xc421216990, 0xc42121bc80)
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:187 +0x7d
created by github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:188 +0x66

goroutine 807 [select, 1 minutes]:
github.com/cockroachdb/cockroach/storage.(*StorePool).start.func1()
	/go/src/github.com/cockroachdb/cockroach/storage/store_pool.go:340 +0x3da
github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker.func1(0xc421216990, 0xc4212242a0)
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:187 +0x7d
created by github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:188 +0x66

goroutine 1238 [select]:
github.com/cockroachdb/cockroach/storage.(*Replica).addWriteCmd(0xc4205a4240, 0x7f307b769b00, 0xc4211302a0, 0x1472ddc59786a858, 0x0, 0x200000002, 0x2, 0x1, 0x0, 0x0, ...)
	/go/src/github.com/cockroachdb/cockroach/storage/replica.go:1464 +0x521
github.com/cockroachdb/cockroach/storage.(*Replica).Send(0xc4205a4240, 0x7f307b769b00, 0xc4211302a0, 0x1472ddc59786a858, 0x0, 0x200000002, 0x2, 0x1, 0x0, 0x0, ...)
	/go/src/github.com/cockroachdb/cockroach/storage/replica.go:1024 +0x277
github.com/cockroachdb/cockroach/storage.(*Store).Send(0xc420d11680, 0x7f307b769b00, 0xc421130240, 0x1472ddc59786a858, 0x0, 0x200000002, 0x2, 0x1, 0x0, 0x0, ...)
	/go/src/github.com/cockroachdb/cockroach/storage/store.go:2112 +0x75e
github.com/cockroachdb/cockroach/storage.(*Stores).Send(0xc4212466c0, 0x7f307b769b00, 0xc4211301e0, 0x0, 0x0, 0x200000002, 0x2, 0x1, 0x0, 0x0, ...)
	/go/src/github.com/cockroachdb/cockroach/storage/stores.go:182 +0x202
github.com/cockroachdb/cockroach/server.(*Node).Batch.func3()
	/go/src/github.com/cockroachdb/cockroach/server/node.go:823 +0x304
github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunTask(0xc421216990, 0xc4215e2890, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:215 +0x100
github.com/cockroachdb/cockroach/server.(*Node).Batch(0xc4210fa000, 0x7f307b769b00, 0xc4212ebef0, 0xc420a02a28, 0x0, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/server/node.go:835 +0x275
github.com/cockroachdb/cockroach/kv.(*grpcTransport).SendNext(0xc420e03140, 0xc42061b8c0)
	/go/src/github.com/cockroachdb/cockroach/kv/transport.go:175 +0x1d6
github.com/cockroachdb/cockroach/kv.(*DistSender).sendToReplicas(0xc421104090, 0x7f307b769b00, 0xc4212ebef0, 0x2540be400, 0x0, 0x1, 0xc4212e5c20, 0x3, 0x3, 0x0, ...)
	/go/src/github.com/cockroachdb/cockroach/kv/dist_sender.go:1024 +0x1f9
github.com/cockroachdb/cockroach/kv.(*DistSender).sendRPC(0xc421104090, 0x7f307b769b00, 0xc4212ebef0, 0x1, 0xc4212e5c20, 0x3, 0x3, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/cockroachdb/cockroach/kv/dist_sender.go:377 +0x161
github.com/cockroachdb/cockroach/kv.(*DistSender).sendSingleRange(0xc421104090, 0x7f307b769b00, 0xc4212ebef0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/cockroachdb/cockroach/kv/dist_sender.go:483 +0x257
github.com/cockroachdb/cockroach/kv.(*DistSender).sendChunk.func2(0xc4215e36f8, 0xc4215e35b8, 0xc4215e3c20, 0xc421104090, 0xc4215e3c10, 0xd, 0xc42152ce43)
	/go/src/github.com/cockroachdb/cockroach/kv/dist_sender.go:777 +0x18e
github.com/cockroachdb/cockroach/kv.(*DistSender).sendChunk(0xc421104090, 0x7f307b769b00, 0xc4212ebef0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/cockroachdb/cockroach/kv/dist_sender.go:778 +0x6aa
github.com/cockroachdb/cockroach/kv.(*DistSender).Send(0xc421104090, 0x7f307b769b00, 0xc4212ebef0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/cockroachdb/cockroach/kv/dist_sender.go:594 +0x1d6
github.com/cockroachdb/cockroach/kv.(*TxnCoordSender).Send(0xc42123a210, 0x7f307b769b00, 0xc4212ebef0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/cockroachdb/cockroach/kv/txn_coord_sender.go:391 +0x5de
github.com/cockroachdb/cockroach/internal/client.(*DB).send(0xc421229450, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/cockroachdb/cockroach/internal/client/db.go:497 +0xe1
github.com/cockroachdb/cockroach/internal/client.(*DB).(github.com/cockroachdb/cockroach/internal/client.send)-fm(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/cockroachdb/cockroach/internal/client/db.go:435 +0x58
github.com/cockroachdb/cockroach/internal/client.sendAndFill(0xc4215e45f8, 0xc421596000, 0x0, 0xc42152cf10)
	/go/src/github.com/cockroachdb/cockroach/internal/client/db.go:417 +0x168
github.com/cockroachdb/cockroach/internal/client.(*DB).Run(0xc421229450, 0xc421596000, 0x1, 0x1)
	/go/src/github.com/cockroachdb/cockroach/internal/client/db.go:435 +0x75
github.com/cockroachdb/cockroach/storage.(*intentResolver).maybePushTransactions(0xc421224a20, 0x7f307b769b00, 0xc4212ebd10, 0xc4200a7cb0, 0x1, 0x1, 0x1472ddc5976c16c5, 0x29, 0x200000002, 0x2, ...)
	/go/src/github.com/cockroachdb/cockroach/storage/intent_resolver.go:230 +0xa9e
github.com/cockroachdb/cockroach/storage.(*intentResolver).processWriteIntentError(0xc421224a20, 0x7f307b769b00, 0xc4212ebd10, 0xc4212e5b30, 0x1f81d00, 0xc42148ff80, 0x1472ddc5976c16c5, 0x29, 0x200000002, 0x2, ...)
	/go/src/github.com/cockroachdb/cockroach/storage/intent_resolver.go:89 +0x18e
github.com/cockroachdb/cockroach/storage.(*Store).Send(0xc420d11680, 0x7f307b769b00, 0xc4212ebd10, 0x1472ddc5976c16c5, 0x28, 0x200000002, 0x2, 0x1, 0x0, 0x0, ...)
	/go/src/github.com/cockroachdb/cockroach/storage/store.go:2139 +0xca3
github.com/cockroachdb/cockroach/storage.(*Stores).Send(0xc4212466c0, 0x7f307b769b00, 0xc4212ebcb0, 0x0, 0x0, 0x200000002, 0x2, 0x1, 0x0, 0x0, ...)
	/go/src/github.com/cockroachdb/cockroach/storage/stores.go:182 +0x202
github.com/cockroachdb/cockroach/server.(*Node).Batch.func3()
	/go/src/github.com/cockroachdb/cockroach/server/node.go:823 +0x304
github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunTask(0xc421216990, 0xc4215e58b8, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:215 +0x100
github.com/cockroachdb/cockroach/server.(*Node).Batch(0xc4210fa000, 0x7f307b769b00, 0xc4212ebad0, 0xc42158a070, 0x0, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/server/node.go:835 +0x275
github.com/cockroachdb/cockroach/roachpb._Internal_Batch_Handler(0x15f7980, 0xc4210fa000, 0x7f307b769b00, 0xc4212ebad0, 0xc4212e58b0, 0x0, 0x0, 0x0, 0xc420068c00, 0xc4207f2f3e)
	/go/src/github.com/cockroachdb/cockroach/roachpb/api.pb.go:1497 +0x27d
google.golang.org/grpc.(*Server).processUnaryRPC(0xc420a705a0, 0x1f80b20, 0xc4211045a0, 0xc4214ff2c0, 0xc4212131d0, 0x1f523e0, 0x0, 0x0, 0x0)
	/go/src/google.golang.org/grpc/server.go:611 +0xc50
google.golang.org/grpc.(*Server).handleStream(0xc420a705a0, 0x1f80b20, 0xc4211045a0, 0xc4214ff2c0, 0x0)
	/go/src/google.golang.org/grpc/server.go:769 +0x6b0
google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc421210a80, 0xc420a705a0, 0x1f80b20, 0xc4211045a0, 0xc4214ff2c0)
	/go/src/google.golang.org/grpc/server.go:422 +0xab
created by google.golang.org/grpc.(*Server).serveStreams.func1
	/go/src/google.golang.org/grpc/server.go:423 +0xa3

goroutine 808 [select]:
github.com/cockroachdb/cockroach/kv.(*TxnCoordSender).startStats(0xc42123a210)
	/go/src/github.com/cockroachdb/cockroach/kv/txn_coord_sender.go:208 +0xa63
github.com/cockroachdb/cockroach/kv.(*TxnCoordSender).(github.com/cockroachdb/cockroach/kv.startStats)-fm()
	/go/src/github.com/cockroachdb/cockroach/kv/txn_coord_sender.go:193 +0x2a
github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker.func1(0xc421216990, 0xc4207f3500)
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:187 +0x7d
created by github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:188 +0x66

goroutine 207 [chan receive, 1 minutes]:
github.com/cockroachdb/cockroach/rpc.NewContext.func1()
	/go/src/github.com/cockroachdb/cockroach/rpc/context.go:134 +0x76
github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker.func1(0xc421104ab0, 0xc4211999a0)
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:187 +0x7d
created by github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:188 +0x66

goroutine 793 [select]:
github.com/cockroachdb/cockroach/server.(*Node).startGossip.func1()
	/go/src/github.com/cockroachdb/cockroach/server/node.go:591 +0x465
github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker.func1(0xc421104ab0, 0xc421213e00)
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:187 +0x7d
created by github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:188 +0x66

goroutine 1012 [runnable]:
github.com/cockroachdb/cockroach/rpc.(*Context).runHeartbeat(0xc420147280, 0xc420ac8d00, 0xc4212baff0, 0xf, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/rpc/context.go:294 +0x645
github.com/cockroachdb/cockroach/rpc.(*Context).GRPCDial.func1.1.1()
	/go/src/github.com/cockroachdb/cockroach/rpc/context.go:217 +0x69
github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker.func1(0xc421104ab0, 0xc420b01650)
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:187 +0x7d
created by github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:188 +0x66

goroutine 1188 [select]:
google.golang.org/grpc/transport.(*http2Server).controller(0xc421484510)
	/go/src/google.golang.org/grpc/transport/http2_server.go:673 +0x69c
created by google.golang.org/grpc/transport.newHTTP2Server
	/go/src/google.golang.org/grpc/transport/http2_server.go:139 +0x767

goroutine 997 [chan receive, 1 minutes]:
github.com/cockroachdb/cockroach/util/netutil.MakeServer.func2()
	/go/src/github.com/cockroachdb/cockroach/util/netutil/net.go:100 +0x70
github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker.func1(0xc421104ab0, 0xc421100800)
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:187 +0x7d
created by github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:188 +0x66

goroutine 998 [chan receive, 1 minutes]:
github.com/cockroachdb/cockroach/server.(*Server).Start.func2()
	/go/src/github.com/cockroachdb/cockroach/server/server.go:378 +0x64
github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker.func1(0xc421104ab0, 0xc421100960)
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:187 +0x7d
created by github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:188 +0x66

goroutine 999 [IO wait, 1 minutes]:
net.runtime_pollWait(0x7f307b76a6f8, 0x72, 0x0)
	/usr/local/go/src/runtime/netpoll.go:160 +0x59
net.(*pollDesc).wait(0xc421207b10, 0x72, 0xc420160e08, 0xc4200100b8)
	/usr/local/go/src/net/fd_poll_runtime.go:73 +0x38
net.(*pollDesc).waitRead(0xc421207b10, 0x1f6ebc0, 0xc4200100b8)
	/usr/local/go/src/net/fd_poll_runtime.go:78 +0x34
net.(*netFD).accept(0xc421207ab0, 0x0, 0x1f6bf80, 0xc421100d60)
	/usr/local/go/src/net/fd_unix.go:419 +0x238
net.(*TCPListener).accept(0xc42037a100, 0xc420160ef0, 0xc420160f00, 0x6456d0)
	/usr/local/go/src/net/tcpsock_posix.go:132 +0x2e
net.(*TCPListener).Accept(0xc42037a100, 0x176b6f0, 0xc421203c00, 0xc4207f36a0, 0x0)
	/usr/local/go/src/net/tcpsock.go:222 +0x49
github.com/cockroachdb/cmux.(*cMux).Serve(0xc421203c00, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cmux/cmux.go:124 +0xa4
github.com/cockroachdb/cockroach/server.(*Server).Start.func3()
	/go/src/github.com/cockroachdb/cockroach/server/server.go:390 +0x2f
github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker.func1(0xc421104ab0, 0xc4211009c0)
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:187 +0x7d
created by github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:188 +0x66

goroutine 996 [chan receive, 1 minutes]:
github.com/cockroachdb/cockroach/util/netutil.MakeServer.func2()
	/go/src/github.com/cockroachdb/cockroach/util/netutil/net.go:100 +0x70
github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker.func1(0xc421104ab0, 0xc4211007a0)
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:187 +0x7d
created by github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:188 +0x66

goroutine 1008 [select, 1 minutes]:
github.com/cockroachdb/cockroach/storage.(*bookie).start.func1()
	/go/src/github.com/cockroachdb/cockroach/storage/reservation.go:274 +0x217
github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker.func1(0xc421104ab0, 0xc421100d20)
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:187 +0x7d
created by github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:188 +0x66

goroutine 1351 [select]:
github.com/cockroachdb/cockroach/storage.(*pendingLeaseRequest).InitOrJoinRequest.func1()
	/go/src/github.com/cockroachdb/cockroach/storage/replica_range_lease.go:138 +0x619
github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunAsyncTask.func1(0xc421104ab0, 0x1c530cb, 0x1e, 0xa8, 0xc42046d4d0)
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:231 +0x95
created by github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunAsyncTask
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:232 +0xbc

goroutine 995 [select]:
github.com/cockroachdb/cockroach/sql.NewExecutor.func1()
	/go/src/github.com/cockroachdb/cockroach/sql/executor.go:270 +0x175
github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker.func1(0xc421104ab0, 0xc42119c2a0)
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:187 +0x7d
created by github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:188 +0x66

goroutine 209 [select]:
github.com/cockroachdb/cockroach/kv.(*TxnCoordSender).startStats(0xc4211f6bb0)
	/go/src/github.com/cockroachdb/cockroach/kv/txn_coord_sender.go:208 +0xa63
github.com/cockroachdb/cockroach/kv.(*TxnCoordSender).(github.com/cockroachdb/cockroach/kv.startStats)-fm()
	/go/src/github.com/cockroachdb/cockroach/kv/txn_coord_sender.go:193 +0x2a
github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker.func1(0xc421104ab0, 0xc4207f2220)
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:187 +0x7d
created by github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:188 +0x66

goroutine 897 [chan receive, 1 minutes]:
github.com/cockroachdb/cockroach/storage/engine.(*RocksDB).Open.func1(0xc420c8fbc0)
	/go/src/github.com/cockroachdb/cockroach/storage/engine/rocksdb.go:390 +0x44
created by github.com/cockroachdb/cockroach/storage/engine.(*RocksDB).Open
	/go/src/github.com/cockroachdb/cockroach/storage/engine/rocksdb.go:391 +0x6eb

goroutine 994 [select]:
github.com/cockroachdb/cockroach/sql.(*LeaseManager).RefreshLeases.func1()
	/go/src/github.com/cockroachdb/cockroach/sql/lease.go:1143 +0xcc1
github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker.func1(0xc421104ab0, 0xc420c1dec0)
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:187 +0x7d
created by github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:188 +0x66

goroutine 1002 [chan receive, 1 minutes]:
github.com/cockroachdb/cockroach/server.(*Server).Start.func6()
	/go/src/github.com/cockroachdb/cockroach/server/server.go:405 +0x6d
github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker.func1(0xc421104ab0, 0xc421100a40)
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:187 +0x7d
created by github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:188 +0x66

goroutine 1001 [chan receive, 1 minutes]:
github.com/cockroachdb/cmux.(*muxListener).Accept(0xc4211009a0, 0xc42037a100, 0xc420b01380, 0x14d4320, 0x1f516d0)
	<autogenerated>:9 +0x7f
crypto/tls.(*listener).Accept(0xc421100a00, 0xc420b01350, 0x14d4320, 0x1f516d0, 0x1557520)
	/usr/local/go/src/crypto/tls/tls.go:52 +0x37
net/http.(*Server).Serve(0xc4210ceb00, 0x1f72f00, 0xc421100a00, 0x0, 0x0)
	/usr/local/go/src/net/http/server.go:2273 +0x1ce
github.com/cockroachdb/cockroach/server.(*Server).Start.func5()
	/go/src/github.com/cockroachdb/cockroach/server/server.go:401 +0x42
github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker.func1(0xc421104ab0, 0xc421100a20)
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:187 +0x7d
created by github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:188 +0x66

goroutine 1003 [chan receive]:
github.com/cockroachdb/cmux.(*muxListener).Accept(0xc4211008c0, 0x176da10, 0xc420a02dc0, 0x1f80e20, 0xc42010cb00)
	<autogenerated>:9 +0x7f
google.golang.org/grpc.(*Server).Serve(0xc420a02dc0, 0x1f79300, 0xc4211008c0, 0x0, 0x0)
	/go/src/google.golang.org/grpc/server.go:348 +0x15a
github.com/cockroachdb/cockroach/server.(*Server).Start.func7()
	/go/src/github.com/cockroachdb/cockroach/server/server.go:412 +0x43
github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker.func1(0xc421104ab0, 0xc421100a60)
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:187 +0x7d
created by github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:188 +0x66

goroutine 1004 [chan receive, 1 minutes]:
github.com/cockroachdb/cmux.(*muxListener).Accept(0xc4211008a0, 0xc4207f36b0, 0x0, 0xc42003a800, 0x0)
	<autogenerated>:9 +0x7f
github.com/cockroachdb/cockroach/util/netutil.(*Server).ServeWith(0xc42037a0e0, 0xc421104ab0, 0x1f79300, 0xc4211008a0, 0xc4207f36b0, 0xc4203f6f98, 0x6456d0)
	/go/src/github.com/cockroachdb/cockroach/util/netutil/net.go:117 +0x5d
github.com/cockroachdb/cockroach/server.(*Server).Start.func8()
	/go/src/github.com/cockroachdb/cockroach/server/server.go:420 +0xb5
github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker.func1(0xc421104ab0, 0xc420b009c0)
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:187 +0x7d
created by github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:188 +0x66

goroutine 1006 [runnable]:
github.com/cockroachdb/cockroach/gossip.(*Gossip).bootstrap.func1()
	/go/src/github.com/cockroachdb/cockroach/gossip/gossip.go:911 +0x47d
github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker.func1(0xc421104ab0, 0xc4207f29d0)
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:187 +0x7d
created by github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:188 +0x66

goroutine 896 [chan receive, 1 minutes]:
database/sql.(*DB).connectionOpener(0xc42123aa50)
	/usr/local/go/src/database/sql/sql.go:730 +0x4a
created by database/sql.Open
	/usr/local/go/src/database/sql/sql.go:493 +0x1e9

goroutine 1067 [select]:
github.com/cockroachdb/cockroach/storage.(*raftScheduler).worker(0xc421207c00, 0xc421104ab0)
	/go/src/github.com/cockroachdb/cockroach/storage/scheduler.go:168 +0x3e7
github.com/cockroachdb/cockroach/storage.(*raftScheduler).Start.func1()
	/go/src/github.com/cockroachdb/cockroach/storage/scheduler.go:160 +0x33
github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker.func1(0xc421104ab0, 0xc4209552c0)
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:187 +0x7d
created by github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:188 +0x66

goroutine 895 [select]:
github.com/cockroachdb/cockroach/rpc.(*Context).runHeartbeat(0xc420bc2280, 0xc42000bf00, 0xc4207f3bf0, 0xf, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/rpc/context.go:294 +0x645
github.com/cockroachdb/cockroach/rpc.(*Context).GRPCDial.func1.1.1()
	/go/src/github.com/cockroachdb/cockroach/rpc/context.go:217 +0x69
github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker.func1(0xc421216990, 0xc42046d230)
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:187 +0x7d
created by github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:188 +0x66

goroutine 1213 [select]:
google.golang.org/grpc.(*addrConn).transportMonitor(0xc4214aedc0)
	/go/src/google.golang.org/grpc/clientconn.go:720 +0x63e
created by google.golang.org/grpc.(*ClientConn).resetAddrConn
	/go/src/google.golang.org/grpc/clientconn.go:467 +0x6e2

goroutine 1212 [select]:
google.golang.org/grpc/transport.(*http2Client).controller(0xc420711100)
	/go/src/google.golang.org/grpc/transport/http2_client.go:999 +0x59d
created by google.golang.org/grpc/transport.newHTTP2Client
	/go/src/google.golang.org/grpc/transport/http2_client.go:233 +0xe78

goroutine 656 [select]:
github.com/cockroachdb/cockroach/storage.(*raftScheduler).worker(0xc421251810, 0xc421216990)
	/go/src/github.com/cockroachdb/cockroach/storage/scheduler.go:168 +0x3e7
github.com/cockroachdb/cockroach/storage.(*raftScheduler).Start.func1()
	/go/src/github.com/cockroachdb/cockroach/storage/scheduler.go:160 +0x33
github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker.func1(0xc421216990, 0xc420bfac40)
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:187 +0x7d
created by github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:188 +0x66

goroutine 657 [select]:
github.com/cockroachdb/cockroach/storage.(*raftScheduler).worker(0xc421251810, 0xc421216990)
	/go/src/github.com/cockroachdb/cockroach/storage/scheduler.go:168 +0x3e7
github.com/cockroachdb/cockroach/storage.(*raftScheduler).Start.func1()
	/go/src/github.com/cockroachdb/cockroach/storage/scheduler.go:160 +0x33
github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker.func1(0xc421216990, 0xc420bfac60)
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:187 +0x7d
created by github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:188 +0x66

goroutine 914 [select]:
github.com/cockroachdb/cockroach/storage.(*raftScheduler).worker(0xc421251810, 0xc421216990)
	/go/src/github.com/cockroachdb/cockroach/storage/scheduler.go:168 +0x3e7
github.com/cockroachdb/cockroach/storage.(*raftScheduler).Start.func1()
	/go/src/github.com/cockroachdb/cockroach/storage/scheduler.go:160 +0x33
github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker.func1(0xc421216990, 0xc420bfac80)
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:187 +0x7d
created by github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:188 +0x66

goroutine 915 [select]:
github.com/cockroachdb/cockroach/storage.(*raftScheduler).worker(0xc421251810, 0xc421216990)
	/go/src/github.com/cockroachdb/cockroach/storage/scheduler.go:168 +0x3e7
github.com/cockroachdb/cockroach/storage.(*raftScheduler).Start.func1()
	/go/src/github.com/cockroachdb/cockroach/storage/scheduler.go:160 +0x33
github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker.func1(0xc421216990, 0xc420bfaca0)
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:187 +0x7d
created by github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:188 +0x66

goroutine 916 [select]:
github.com/cockroachdb/cockroach/storage.(*raftScheduler).worker(0xc421251810, 0xc421216990)
	/go/src/github.com/cockroachdb/cockroach/storage/scheduler.go:168 +0x3e7
github.com/cockroachdb/cockroach/storage.(*raftScheduler).Start.func1()
	/go/src/github.com/cockroachdb/cockroach/storage/scheduler.go:160 +0x33
github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker.func1(0xc421216990, 0xc420bfacc0)
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:187 +0x7d
created by github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:188 +0x66

goroutine 917 [select]:
github.com/cockroachdb/cockroach/storage.(*raftScheduler).worker(0xc421251810, 0xc421216990)
	/go/src/github.com/cockroachdb/cockroach/storage/scheduler.go:168 +0x3e7
github.com/cockroachdb/cockroach/storage.(*raftScheduler).Start.func1()
	/go/src/github.com/cockroachdb/cockroach/storage/scheduler.go:160 +0x33
github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker.func1(0xc421216990, 0xc420bface0)
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:187 +0x7d
created by github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:188 +0x66

goroutine 918 [select]:
github.com/cockroachdb/cockroach/storage.(*raftScheduler).worker(0xc421251810, 0xc421216990)
	/go/src/github.com/cockroachdb/cockroach/storage/scheduler.go:168 +0x3e7
github.com/cockroachdb/cockroach/storage.(*raftScheduler).Start.func1()
	/go/src/github.com/cockroachdb/cockroach/storage/scheduler.go:160 +0x33
github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker.func1(0xc421216990, 0xc420bfad00)
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:187 +0x7d
created by github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:188 +0x66

goroutine 919 [select]:
github.com/cockroachdb/cockroach/storage.(*raftScheduler).worker(0xc421251810, 0xc421216990)
	/go/src/github.com/cockroachdb/cockroach/storage/scheduler.go:168 +0x3e7
github.com/cockroachdb/cockroach/storage.(*raftScheduler).Start.func1()
	/go/src/github.com/cockroachdb/cockroach/storage/scheduler.go:160 +0x33
github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker.func1(0xc421216990, 0xc420bfad20)
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:187 +0x7d
created by github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:188 +0x66

goroutine 920 [select]:
github.com/cockroachdb/cockroach/storage.(*raftScheduler).worker(0xc421251810, 0xc421216990)
	/go/src/github.com/cockroachdb/cockroach/storage/scheduler.go:168 +0x3e7
github.com/cockroachdb/cockroach/storage.(*raftScheduler).Start.func1()
	/go/src/github.com/cockroachdb/cockroach/storage/scheduler.go:160 +0x33
github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker.func1(0xc421216990, 0xc420bfad40)
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:187 +0x7d
created by github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:188 +0x66

goroutine 921 [select]:
github.com/cockroachdb/cockroach/storage.(*raftScheduler).worker(0xc421251810, 0xc421216990)
	/go/src/github.com/cockroachdb/cockroach/storage/scheduler.go:168 +0x3e7
github.com/cockroachdb/cockroach/storage.(*raftScheduler).Start.func1()
	/go/src/github.com/cockroachdb/cockroach/storage/scheduler.go:160 +0x33
github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker.func1(0xc421216990, 0xc420bfad60)
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:187 +0x7d
created by github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:188 +0x66

goroutine 922 [select]:
github.com/cockroachdb/cockroach/storage.(*raftScheduler).worker(0xc421251810, 0xc421216990)
	/go/src/github.com/cockroachdb/cockroach/storage/scheduler.go:168 +0x3e7
github.com/cockroachdb/cockroach/storage.(*raftScheduler).Start.func1()
	/go/src/github.com/cockroachdb/cockroach/storage/scheduler.go:160 +0x33
github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker.func1(0xc421216990, 0xc420bfad80)
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:187 +0x7d
created by github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:188 +0x66

goroutine 923 [select]:
github.com/cockroachdb/cockroach/storage.(*raftScheduler).worker(0xc421251810, 0xc421216990)
	/go/src/github.com/cockroachdb/cockroach/storage/scheduler.go:168 +0x3e7
github.com/cockroachdb/cockroach/storage.(*raftScheduler).Start.func1()
	/go/src/github.com/cockroachdb/cockroach/storage/scheduler.go:160 +0x33
github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker.func1(0xc421216990, 0xc420bfada0)
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:187 +0x7d
created by github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:188 +0x66

goroutine 924 [select]:
github.com/cockroachdb/cockroach/storage.(*raftScheduler).worker(0xc421251810, 0xc421216990)
	/go/src/github.com/cockroachdb/cockroach/storage/scheduler.go:168 +0x3e7
github.com/cockroachdb/cockroach/storage.(*raftScheduler).Start.func1()
	/go/src/github.com/cockroachdb/cockroach/storage/scheduler.go:160 +0x33
github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker.func1(0xc421216990, 0xc420bfadc0)
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:187 +0x7d
created by github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:188 +0x66

goroutine 925 [select]:
github.com/cockroachdb/cockroach/storage.(*raftScheduler).worker(0xc421251810, 0xc421216990)
	/go/src/github.com/cockroachdb/cockroach/storage/scheduler.go:168 +0x3e7
github.com/cockroachdb/cockroach/storage.(*raftScheduler).Start.func1()
	/go/src/github.com/cockroachdb/cockroach/storage/scheduler.go:160 +0x33
github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker.func1(0xc421216990, 0xc420bfade0)
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:187 +0x7d
created by github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:188 +0x66

goroutine 926 [select]:
github.com/cockroachdb/cockroach/storage.(*raftScheduler).worker(0xc421251810, 0xc421216990)
	/go/src/github.com/cockroachdb/cockroach/storage/scheduler.go:168 +0x3e7
github.com/cockroachdb/cockroach/storage.(*raftScheduler).Start.func1()
	/go/src/github.com/cockroachdb/cockroach/storage/scheduler.go:160 +0x33
github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker.func1(0xc421216990, 0xc420bfae00)
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:187 +0x7d
created by github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:188 +0x66

goroutine 927 [select]:
github.com/cockroachdb/cockroach/storage.(*raftScheduler).worker(0xc421251810, 0xc421216990)
	/go/src/github.com/cockroachdb/cockroach/storage/scheduler.go:168 +0x3e7
github.com/cockroachdb/cockroach/storage.(*raftScheduler).Start.func1()
	/go/src/github.com/cockroachdb/cockroach/storage/scheduler.go:160 +0x33
github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker.func1(0xc421216990, 0xc420bfae20)
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:187 +0x7d
created by github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:188 +0x66

goroutine 928 [select]:
github.com/cockroachdb/cockroach/storage.(*raftScheduler).worker(0xc421251810, 0xc421216990)
	/go/src/github.com/cockroachdb/cockroach/storage/scheduler.go:168 +0x3e7
github.com/cockroachdb/cockroach/storage.(*raftScheduler).Start.func1()
	/go/src/github.com/cockroachdb/cockroach/storage/scheduler.go:160 +0x33
github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker.func1(0xc421216990, 0xc420bfae40)
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:187 +0x7d
created by github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:188 +0x66

goroutine 929 [select]:
github.com/cockroachdb/cockroach/storage.(*raftScheduler).worker(0xc421251810, 0xc421216990)
	/go/src/github.com/cockroachdb/cockroach/storage/scheduler.go:168 +0x3e7
github.com/cockroachdb/cockroach/storage.(*raftScheduler).Start.func1()
	/go/src/github.com/cockroachdb/cockroach/storage/scheduler.go:160 +0x33
github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker.func1(0xc421216990, 0xc420bfae60)
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:187 +0x7d
created by github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:188 +0x66

goroutine 930 [select]:
github.com/cockroachdb/cockroach/storage.(*raftScheduler).worker(0xc421251810, 0xc421216990)
	/go/src/github.com/cockroachdb/cockroach/storage/scheduler.go:168 +0x3e7
github.com/cockroachdb/cockroach/storage.(*raftScheduler).Start.func1()
	/go/src/github.com/cockroachdb/cockroach/storage/scheduler.go:160 +0x33
github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker.func1(0xc421216990, 0xc420bfae80)
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:187 +0x7d
created by github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:188 +0x66

goroutine 931 [select]:
github.com/cockroachdb/cockroach/storage.(*raftScheduler).worker(0xc421251810, 0xc421216990)
	/go/src/github.com/cockroachdb/cockroach/storage/scheduler.go:168 +0x3e7
github.com/cockroachdb/cockroach/storage.(*raftScheduler).Start.func1()
	/go/src/github.com/cockroachdb/cockroach/storage/scheduler.go:160 +0x33
github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker.func1(0xc421216990, 0xc420bfaea0)
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:187 +0x7d
created by github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:188 +0x66

goroutine 932 [select]:
github.com/cockroachdb/cockroach/storage.(*raftScheduler).worker(0xc421251810, 0xc421216990)
	/go/src/github.com/cockroachdb/cockroach/storage/scheduler.go:168 +0x3e7
github.com/cockroachdb/cockroach/storage.(*raftScheduler).Start.func1()
	/go/src/github.com/cockroachdb/cockroach/storage/scheduler.go:160 +0x33
github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker.func1(0xc421216990, 0xc420bfaec0)
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:187 +0x7d
created by github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:188 +0x66

goroutine 933 [select]:
github.com/cockroachdb/cockroach/storage.(*raftScheduler).worker(0xc421251810, 0xc421216990)
	/go/src/github.com/cockroachdb/cockroach/storage/scheduler.go:168 +0x3e7
github.com/cockroachdb/cockroach/storage.(*raftScheduler).Start.func1()
	/go/src/github.com/cockroachdb/cockroach/storage/scheduler.go:160 +0x33
github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker.func1(0xc421216990, 0xc420bfaee0)
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:187 +0x7d
created by github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:188 +0x66

goroutine 934 [select]:
github.com/cockroachdb/cockroach/storage.(*raftScheduler).worker(0xc421251810, 0xc421216990)
	/go/src/github.com/cockroachdb/cockroach/storage/scheduler.go:168 +0x3e7
github.com/cockroachdb/cockroach/storage.(*raftScheduler).Start.func1()
	/go/src/github.com/cockroachdb/cockroach/storage/scheduler.go:160 +0x33
github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker.func1(0xc421216990, 0xc420bfaf00)
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:187 +0x7d
created by github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:188 +0x66

goroutine 935 [select]:
github.com/cockroachdb/cockroach/storage.(*raftScheduler).worker(0xc421251810, 0xc421216990)
	/go/src/github.com/cockroachdb/cockroach/storage/scheduler.go:168 +0x3e7
github.com/cockroachdb/cockroach/storage.(*raftScheduler).Start.func1()
	/go/src/github.com/cockroachdb/cockroach/storage/scheduler.go:160 +0x33
github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker.func1(0xc421216990, 0xc420bfaf20)
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:187 +0x7d
created by github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:188 +0x66

goroutine 936 [select]:
github.com/cockroachdb/cockroach/storage.(*raftScheduler).worker(0xc421251810, 0xc421216990)
	/go/src/github.com/cockroachdb/cockroach/storage/scheduler.go:168 +0x3e7
github.com/cockroachdb/cockroach/storage.(*raftScheduler).Start.func1()
	/go/src/github.com/cockroachdb/cockroach/storage/scheduler.go:160 +0x33
github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker.func1(0xc421216990, 0xc420bfaf40)
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:187 +0x7d
created by github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:188 +0x66

goroutine 937 [select]:
github.com/cockroachdb/cockroach/storage.(*raftScheduler).worker(0xc421251810, 0xc421216990)
	/go/src/github.com/cockroachdb/cockroach/storage/scheduler.go:168 +0x3e7
github.com/cockroachdb/cockroach/storage.(*raftScheduler).Start.func1()
	/go/src/github.com/cockroachdb/cockroach/storage/scheduler.go:160 +0x33
github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker.func1(0xc421216990, 0xc420bfaf60)
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:187 +0x7d
created by github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:188 +0x66

goroutine 938 [select]:
github.com/cockroachdb/cockroach/storage.(*raftScheduler).worker(0xc421251810, 0xc421216990)
	/go/src/github.com/cockroachdb/cockroach/storage/scheduler.go:168 +0x3e7
github.com/cockroachdb/cockroach/storage.(*raftScheduler).Start.func1()
	/go/src/github.com/cockroachdb/cockroach/storage/scheduler.go:160 +0x33
github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker.func1(0xc421216990, 0xc420bfaf80)
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:187 +0x7d
created by github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:188 +0x66

goroutine 939 [select]:
github.com/cockroachdb/cockroach/storage.(*raftScheduler).worker(0xc421251810, 0xc421216990)
	/go/src/github.com/cockroachdb/cockroach/storage/scheduler.go:168 +0x3e7
github.com/cockroachdb/cockroach/storage.(*raftScheduler).Start.func1()
	/go/src/github.com/cockroachdb/cockroach/storage/scheduler.go:160 +0x33
github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker.func1(0xc421216990, 0xc420bfafa0)
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:187 +0x7d
created by github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:188 +0x66

goroutine 940 [select]:
github.com/cockroachdb/cockroach/storage.(*raftScheduler).worker(0xc421251810, 0xc421216990)
	/go/src/github.com/cockroachdb/cockroach/storage/scheduler.go:168 +0x3e7
github.com/cockroachdb/cockroach/storage.(*raftScheduler).Start.func1()
	/go/src/github.com/cockroachdb/cockroach/storage/scheduler.go:160 +0x33
github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker.func1(0xc421216990, 0xc420bfafc0)
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:187 +0x7d
created by github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:188 +0x66

goroutine 941 [select]:
github.com/cockroachdb/cockroach/storage.(*raftScheduler).worker(0xc421251810, 0xc421216990)
	/go/src/github.com/cockroachdb/cockroach/storage/scheduler.go:168 +0x3e7
github.com/cockroachdb/cockroach/storage.(*raftScheduler).Start.func1()
	/go/src/github.com/cockroachdb/cockroach/storage/scheduler.go:160 +0x33
github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker.func1(0xc421216990, 0xc420bfafe0)
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:187 +0x7d
created by github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:188 +0x66

goroutine 942 [select]:
github.com/cockroachdb/cockroach/storage.(*raftScheduler).worker(0xc421251810, 0xc421216990)
	/go/src/github.com/cockroachdb/cockroach/storage/scheduler.go:168 +0x3e7
github.com/cockroachdb/cockroach/storage.(*raftScheduler).Start.func1()
	/go/src/github.com/cockroachdb/cockroach/storage/scheduler.go:160 +0x33
github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker.func1(0xc421216990, 0xc420bfb000)
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:187 +0x7d
created by github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:188 +0x66

goroutine 943 [select]:
github.com/cockroachdb/cockroach/storage.(*raftScheduler).worker(0xc421251810, 0xc421216990)
	/go/src/github.com/cockroachdb/cockroach/storage/scheduler.go:168 +0x3e7
github.com/cockroachdb/cockroach/storage.(*raftScheduler).Start.func1()
	/go/src/github.com/cockroachdb/cockroach/storage/scheduler.go:160 +0x33
github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker.func1(0xc421216990, 0xc420bfb020)
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:187 +0x7d
created by github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:188 +0x66

goroutine 944 [select]:
github.com/cockroachdb/cockroach/storage.(*Store).raftTickLoop.func1()
	/go/src/github.com/cockroachdb/cockroach/storage/store.go:2629 +0x334
github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker.func1(0xc421216990, 0xc4211d2e70)
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:187 +0x7d
created by github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:188 +0x66

goroutine 945 [select, 1 minutes]:
github.com/cockroachdb/cockroach/storage.(*Store).raftSnapshotStatusLoop.func1()
	/go/src/github.com/cockroachdb/cockroach/storage/store.go:2659 +0x211
github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker.func1(0xc421216990, 0xc4211d2e80)
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:187 +0x7d
created by github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:188 +0x66

goroutine 947 [select]:
github.com/cockroachdb/cockroach/storage.(*Store).Start.func3()
	/go/src/github.com/cockroachdb/cockroach/storage/store.go:964 +0x165
github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker.func1(0xc421216990, 0xc420bfb080)
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:187 +0x7d
created by github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:188 +0x66

goroutine 948 [select]:
github.com/cockroachdb/cockroach/storage.(*Store).startGossip.func1()
	/go/src/github.com/cockroachdb/cockroach/storage/store.go:1039 +0x314
github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker.func1(0xc421216990, 0xc4211d2eb0)
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:187 +0x7d
created by github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:188 +0x66

goroutine 949 [select]:
github.com/cockroachdb/cockroach/storage.(*Store).startGossip.func2()
	/go/src/github.com/cockroachdb/cockroach/storage/store.go:1058 +0x314
github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker.func1(0xc421216990, 0xc4211d2ec0)
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:187 +0x7d
created by github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:188 +0x66

goroutine 961 [select, 1 minutes]:
github.com/cockroachdb/cockroach/storage.(*baseQueue).processLoop.func1()
	/go/src/github.com/cockroachdb/cockroach/storage/queue.go:418 +0x2cc
github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker.func1(0xc421216990, 0xc4201c9c60)
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:187 +0x7d
created by github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:188 +0x66

goroutine 954 [select, 1 minutes]:
github.com/cockroachdb/cockroach/storage.(*baseQueue).processLoop.func1()
	/go/src/github.com/cockroachdb/cockroach/storage/queue.go:418 +0x2cc
github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker.func1(0xc421216990, 0xc4201c9ac0)
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:187 +0x7d
created by github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:188 +0x66

goroutine 955 [select, 1 minutes]:
github.com/cockroachdb/cockroach/storage.(*baseQueue).processLoop.func1()
	/go/src/github.com/cockroachdb/cockroach/storage/queue.go:418 +0x2cc
github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker.func1(0xc421216990, 0xc4201c9b00)
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:187 +0x7d
created by github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:188 +0x66

goroutine 956 [select, 1 minutes]:
github.com/cockroachdb/cockroach/storage.(*baseQueue).processLoop.func1()
	/go/src/github.com/cockroachdb/cockroach/storage/queue.go:418 +0x2cc
github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker.func1(0xc421216990, 0xc4201c9b40)
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:187 +0x7d
created by github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:188 +0x66

goroutine 957 [select, 1 minutes]:
github.com/cockroachdb/cockroach/storage.(*baseQueue).processLoop.func1()
	/go/src/github.com/cockroachdb/cockroach/storage/queue.go:418 +0x2cc
github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker.func1(0xc421216990, 0xc4201c9b60)
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:187 +0x7d
created by github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:188 +0x66

goroutine 958 [select, 1 minutes]:
github.com/cockroachdb/cockroach/storage.(*baseQueue).processLoop.func1()
	/go/src/github.com/cockroachdb/cockroach/storage/queue.go:418 +0x2cc
github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker.func1(0xc421216990, 0xc4201c9b80)
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:187 +0x7d
created by github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:188 +0x66

goroutine 959 [select, 1 minutes]:
github.com/cockroachdb/cockroach/storage.(*baseQueue).processLoop.func1()
	/go/src/github.com/cockroachdb/cockroach/storage/queue.go:418 +0x2cc
github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker.func1(0xc421216990, 0xc4201c9ba0)
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:187 +0x7d
created by github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:188 +0x66

goroutine 962 [select, 1 minutes]:
github.com/cockroachdb/cockroach/storage.(*replicaScanner).waitAndProcess(0xc42073a800, 0xecf658b5c, 0xc42a505742, 0x22a9260, 0xc421246340, 0xc421216990, 0x0, 0x61ad43)
	/go/src/github.com/cockroachdb/cockroach/storage/scanner.go:201 +0x237
github.com/cockroachdb/cockroach/storage.(*replicaScanner).scanLoop.func1()
	/go/src/github.com/cockroachdb/cockroach/storage/scanner.go:264 +0x311
github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker.func1(0xc421216990, 0xc4201c9c80)
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:187 +0x7d
created by github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:188 +0x66

goroutine 827 [select, 1 minutes]:
github.com/cockroachdb/cockroach/storage.(*bookie).start.func1()
	/go/src/github.com/cockroachdb/cockroach/storage/reservation.go:274 +0x217
github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker.func1(0xc421104ab0, 0xc420954dc0)
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:187 +0x7d
created by github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:188 +0x66

goroutine 795 [select]:
github.com/cockroachdb/cockroach/server.(*Server).startSampleEnvironment.func1()
	/go/src/github.com/cockroachdb/cockroach/server/server.go:623 +0x16b
github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker.func1(0xc421104ab0, 0xc4212ac3e0)
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:187 +0x7d
created by github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:188 +0x66

goroutine 796 [select]:
github.com/cockroachdb/cockroach/storage.(*Replica).redirectOnOrAcquireLease(0xc42017f200, 0x7f307b769b00, 0xc42046d020, 0xc421230140)
	/go/src/github.com/cockroachdb/cockroach/storage/replica.go:750 +0x4ec
github.com/cockroachdb/cockroach/storage.(*Replica).addWriteCmd(0xc42017f200, 0x7f307b769b00, 0xc42046d020, 0x1472ddc7e76bbfe5, 0x0, 0x300000003, 0x3, 0x1, 0x0, 0x0, ...)
	/go/src/github.com/cockroachdb/cockroach/storage/replica.go:1437 +0x18a
github.com/cockroachdb/cockroach/storage.(*Replica).Send(0xc42017f200, 0x7f307b769b00, 0xc42046d020, 0x1472ddc7e76bbfe5, 0x0, 0x300000003, 0x3, 0x1, 0x0, 0x0, ...)
	/go/src/github.com/cockroachdb/cockroach/storage/replica.go:1024 +0x277
github.com/cockroachdb/cockroach/storage.(*Store).Send(0xc420e01400, 0x7f307b769b00, 0xc42046cfc0, 0x1472ddc7e76bbfe5, 0x0, 0x300000003, 0x3, 0x1, 0x0, 0x0, ...)
	/go/src/github.com/cockroachdb/cockroach/storage/store.go:2112 +0x75e
github.com/cockroachdb/cockroach/storage.(*Stores).Send(0xc421203ac0, 0x7f307b769b00, 0xc42046cf60, 0x0, 0x0, 0x300000003, 0x3, 0x1, 0x0, 0x0, ...)
	/go/src/github.com/cockroachdb/cockroach/storage/stores.go:182 +0x202
github.com/cockroachdb/cockroach/server.(*Node).Batch.func3()
	/go/src/github.com/cockroachdb/cockroach/server/node.go:823 +0x304
github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunTask(0xc421104ab0, 0xc420495d18, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:215 +0x100
github.com/cockroachdb/cockroach/server.(*Node).Batch(0xc4207e2000, 0x7f307b769b00, 0xc42046c420, 0xc4211e05c8, 0x0, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/server/node.go:835 +0x275
github.com/cockroachdb/cockroach/kv.(*grpcTransport).SendNext(0xc420d4cf40, 0xc4207673e0)
	/go/src/github.com/cockroachdb/cockroach/kv/transport.go:175 +0x1d6
github.com/cockroachdb/cockroach/kv.(*DistSender).sendToReplicas(0xc4212b82d0, 0x7f307b769b00, 0xc42046c420, 0x2540be400, 0x0, 0x1, 0xc4212e5900, 0x3, 0x3, 0x0, ...)
	/go/src/github.com/cockroachdb/cockroach/kv/dist_sender.go:1024 +0x1f9
github.com/cockroachdb/cockroach/kv.(*DistSender).sendRPC(0xc4212b82d0, 0x7f307b769b00, 0xc42046c420, 0x1, 0xc4212e5900, 0x3, 0x3, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/cockroachdb/cockroach/kv/dist_sender.go:377 +0x161
github.com/cockroachdb/cockroach/kv.(*DistSender).sendSingleRange(0xc4212b82d0, 0x7f307b769b00, 0xc42046c420, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/cockroachdb/cockroach/kv/dist_sender.go:483 +0x257
github.com/cockroachdb/cockroach/kv.(*DistSender).sendChunk.func2(0xc420496b80, 0xc420496a40, 0xc4204970a8, 0xc4212b82d0, 0xc420497098, 0x40, 0xc421639d20)
	/go/src/github.com/cockroachdb/cockroach/kv/dist_sender.go:777 +0x18e
github.com/cockroachdb/cockroach/kv.(*DistSender).sendChunk(0xc4212b82d0, 0x7f307b769b00, 0xc42046c420, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/cockroachdb/cockroach/kv/dist_sender.go:778 +0x6aa
github.com/cockroachdb/cockroach/kv.(*DistSender).Send(0xc4212b82d0, 0x7f307b769b00, 0xc42046c420, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/cockroachdb/cockroach/kv/dist_sender.go:594 +0x1d6
github.com/cockroachdb/cockroach/kv.(*TxnCoordSender).Send(0xc4211f6bb0, 0x7f307b769b00, 0xc42046c420, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/cockroachdb/cockroach/kv/txn_coord_sender.go:391 +0x5de
github.com/cockroachdb/cockroach/internal/client.(*DB).send(0xc420921310, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/cockroachdb/cockroach/internal/client/db.go:497 +0xe1
github.com/cockroachdb/cockroach/internal/client.(*DB).(github.com/cockroachdb/cockroach/internal/client.send)-fm(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/cockroachdb/cockroach/internal/client/db.go:435 +0x58
github.com/cockroachdb/cockroach/internal/client.sendAndFill(0xc420497a80, 0xc4216aec00, 0x0, 0xc420d2bbc8)
	/go/src/github.com/cockroachdb/cockroach/internal/client/db.go:417 +0x168
github.com/cockroachdb/cockroach/internal/client.(*DB).Run(0xc420921310, 0xc4216aec00, 0x1, 0x1)
	/go/src/github.com/cockroachdb/cockroach/internal/client/db.go:435 +0x75
github.com/cockroachdb/cockroach/ts.(*DB).StoreData(0xc42037a098, 0x1, 0xc420226a00, 0xd8, 0x13b, 0x8d7352, 0xc420d2bdd8)
	/go/src/github.com/cockroachdb/cockroach/ts/db.go:143 +0x77c
github.com/cockroachdb/cockroach/ts.(*poller).poll.func1()
	/go/src/github.com/cockroachdb/cockroach/ts/db.go:100 +0x7d
github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunTask(0xc421104ab0, 0xc420497e58, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:215 +0x100
github.com/cockroachdb/cockroach/ts.(*poller).poll(0xc421213f50)
	/go/src/github.com/cockroachdb/cockroach/ts/db.go:103 +0x4e
github.com/cockroachdb/cockroach/ts.(*poller).start.func1()
	/go/src/github.com/cockroachdb/cockroach/ts/db.go:83 +0x11c
github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker.func1(0xc421104ab0, 0xc4212389f0)
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:187 +0x7d
created by github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:188 +0x66

goroutine 797 [select]:
github.com/cockroachdb/cockroach/storage.(*Replica).redirectOnOrAcquireLease(0xc42017f200, 0x7f307b769b00, 0xc42046d9b0, 0xc4212527c0)
	/go/src/github.com/cockroachdb/cockroach/storage/replica.go:750 +0x4ec
github.com/cockroachdb/cockroach/storage.(*Replica).addWriteCmd(0xc42017f200, 0x7f307b769b00, 0xc42046d9b0, 0x1472ddc7e7b9f429, 0x0, 0x300000003, 0x3, 0x1, 0x0, 0x0, ...)
	/go/src/github.com/cockroachdb/cockroach/storage/replica.go:1437 +0x18a
github.com/cockroachdb/cockroach/storage.(*Replica).Send(0xc42017f200, 0x7f307b769b00, 0xc42046d9b0, 0x1472ddc7e7b9f429, 0x0, 0x300000003, 0x3, 0x1, 0x0, 0x0, ...)
	/go/src/github.com/cockroachdb/cockroach/storage/replica.go:1024 +0x277
github.com/cockroachdb/cockroach/storage.(*Store).Send(0xc420e01400, 0x7f307b769b00, 0xc42046d950, 0x1472ddc7e7b9f429, 0x0, 0x300000003, 0x3, 0x1, 0x0, 0x0, ...)
	/go/src/github.com/cockroachdb/cockroach/storage/store.go:2112 +0x75e
github.com/cockroachdb/cockroach/storage.(*Stores).Send(0xc421203ac0, 0x7f307b769b00, 0xc42046d8f0, 0x0, 0x0, 0x300000003, 0x3, 0x1, 0x0, 0x0, ...)
	/go/src/github.com/cockroachdb/cockroach/storage/stores.go:182 +0x202
github.com/cockroachdb/cockroach/server.(*Node).Batch.func3()
	/go/src/github.com/cockroachdb/cockroach/server/node.go:823 +0x304
github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunTask(0xc421104ab0, 0xc420b57cf8, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:215 +0x100
github.com/cockroachdb/cockroach/server.(*Node).Batch(0xc4207e2000, 0x7f307b769b00, 0xc42046d620, 0xc4211e0668, 0x0, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/server/node.go:835 +0x275
github.com/cockroachdb/cockroach/kv.(*grpcTransport).SendNext(0xc420d4d500, 0xc420767980)
	/go/src/github.com/cockroachdb/cockroach/kv/transport.go:175 +0x1d6
github.com/cockroachdb/cockroach/kv.(*DistSender).sendToReplicas(0xc4212b82d0, 0x7f307b769b00, 0xc42046d620, 0x2540be400, 0x0, 0x1, 0xc4212e5db0, 0x3, 0x3, 0x0, ...)
	/go/src/github.com/cockroachdb/cockroach/kv/dist_sender.go:1024 +0x1f9
github.com/cockroachdb/cockroach/kv.(*DistSender).sendRPC(0xc4212b82d0, 0x7f307b769b00, 0xc42046d620, 0x1, 0xc4212e5db0, 0x3, 0x3, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/cockroachdb/cockroach/kv/dist_sender.go:377 +0x161
github.com/cockroachdb/cockroach/kv.(*DistSender).sendSingleRange(0xc4212b82d0, 0x7f307b769b00, 0xc42046d620, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/cockroachdb/cockroach/kv/dist_sender.go:483 +0x257
github.com/cockroachdb/cockroach/kv.(*DistSender).sendChunk.func2(0xc420b58b60, 0xc420b58a20, 0xc420b59088, 0xc4212b82d0, 0xc420b59078, 0x16, 0xc4212524c0)
	/go/src/github.com/cockroachdb/cockroach/kv/dist_sender.go:777 +0x18e
github.com/cockroachdb/cockroach/kv.(*DistSender).sendChunk(0xc4212b82d0, 0x7f307b769b00, 0xc42046d620, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/cockroachdb/cockroach/kv/dist_sender.go:778 +0x6aa
github.com/cockroachdb/cockroach/kv.(*DistSender).Send(0xc4212b82d0, 0x7f307b769b00, 0xc42046d620, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/cockroachdb/cockroach/kv/dist_sender.go:594 +0x1d6
github.com/cockroachdb/cockroach/kv.(*TxnCoordSender).Send(0xc4211f6bb0, 0x7f307b769b00, 0xc42046d620, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/cockroachdb/cockroach/kv/txn_coord_sender.go:391 +0x5de
github.com/cockroachdb/cockroach/internal/client.(*DB).send(0xc420921310, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/cockroachdb/cockroach/internal/client/db.go:497 +0xe1
github.com/cockroachdb/cockroach/internal/client.(*DB).(github.com/cockroachdb/cockroach/internal/client.send)-fm(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/cockroachdb/cockroach/internal/client/db.go:435 +0x58
github.com/cockroachdb/cockroach/internal/client.sendAndFill(0xc420b59a60, 0xc4216af200, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/internal/client/db.go:417 +0x168
github.com/cockroachdb/cockroach/internal/client.(*DB).Run(0xc420921310, 0xc4216af200, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/internal/client/db.go:435 +0x75
github.com/cockroachdb/cockroach/internal/client.runOneResult(0x1f67a80, 0xc420921310, 0xc4216af200, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/cockroachdb/cockroach/internal/client/db.go:524 +0x87
github.com/cockroachdb/cockroach/internal/client.(*DB).PutInline(0xc420921310, 0x157c1e0, 0xc4212524e0, 0x158cb20, 0xc420428d00, 0x1c538c0, 0x61b9fc)
	/go/src/github.com/cockroachdb/cockroach/internal/client/db.go:250 +0xc9
github.com/cockroachdb/cockroach/server.(*Node).writeSummaries.func1()
	/go/src/github.com/cockroachdb/cockroach/server/node.go:694 +0x111
github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunTask(0xc421104ab0, 0xc420b59df0, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:215 +0x100
github.com/cockroachdb/cockroach/server.(*Node).writeSummaries(0xc4207e2000, 0xc420c8faa0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/server/node.go:705 +0x69
github.com/cockroachdb/cockroach/server.(*Node).startWriteSummaries.func1()
	/go/src/github.com/cockroachdb/cockroach/server/node.go:669 +0x1f9
github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker.func1(0xc421104ab0, 0xc4212ac400)
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:187 +0x7d
created by github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:188 +0x66

goroutine 798 [select]:
github.com/cockroachdb/cockroach/sql.(*SchemaChangeManager).Start.func1()
	/go/src/github.com/cockroachdb/cockroach/sql/schema_changer.go:704 +0x12c1
github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker.func1(0xc421104ab0, 0xc4212ac420)
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:187 +0x7d
created by github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:188 +0x66

goroutine 799 [IO wait]:
net.runtime_pollWait(0x7f307b76a7b8, 0x72, 0x0)
	/usr/local/go/src/runtime/netpoll.go:160 +0x59
net.(*pollDesc).wait(0xc421207aa0, 0x72, 0xc4209ba608, 0xc4200100b8)
	/usr/local/go/src/net/fd_poll_runtime.go:73 +0x38
net.(*pollDesc).waitRead(0xc421207aa0, 0x1f6ebc0, 0xc4200100b8)
	/usr/local/go/src/net/fd_poll_runtime.go:78 +0x34
net.(*netFD).accept(0xc421207a40, 0x0, 0x1f6bf80, 0xc420bfdba0)
	/usr/local/go/src/net/fd_unix.go:419 +0x238
net.(*TCPListener).accept(0xc42037a0e8, 0x624f5e, 0xc4209ba6b8, 0xd7eadb)
	/usr/local/go/src/net/tcpsock_posix.go:132 +0x2e
net.(*TCPListener).Accept(0xc42037a0e8, 0x176b6f8, 0xc421203bc0, 0x1f81060, 0xc420b0a220)
	/usr/local/go/src/net/tcpsock.go:222 +0x49
github.com/cockroachdb/cmux.(*cMux).Serve(0xc421203bc0, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cmux/cmux.go:124 +0xa4
github.com/cockroachdb/cockroach/server.(*Server).Start.func11()
	/go/src/github.com/cockroachdb/cockroach/server/server.go:495 +0x2f
github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker.func1(0xc421104ab0, 0xc4212ac440)
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:187 +0x7d
created by github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:188 +0x66

goroutine 1026 [select]:
github.com/cockroachdb/cockroach/rpc.(*Context).runHeartbeat(0xc420147280, 0xc420ac8100, 0xc4207f2920, 0xf, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/rpc/context.go:294 +0x645
github.com/cockroachdb/cockroach/rpc.(*Context).GRPCDial.func1.1.1()
	/go/src/github.com/cockroachdb/cockroach/rpc/context.go:217 +0x69
github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker.func1(0xc421104ab0, 0xc4211c67e0)
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:187 +0x7d
created by github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:188 +0x66

goroutine 801 [select, 1 minutes]:
google.golang.org/grpc.(*addrConn).transportMonitor(0xc420b083c0)
	/go/src/google.golang.org/grpc/clientconn.go:720 +0x63e
google.golang.org/grpc.(*ClientConn).resetAddrConn.func1(0xc420b083c0)
	/go/src/google.golang.org/grpc/clientconn.go:479 +0x1de
created by google.golang.org/grpc.(*ClientConn).resetAddrConn
	/go/src/google.golang.org/grpc/clientconn.go:480 +0x3c7

goroutine 1027 [chan receive, 1 minutes]:
database/sql.(*DB).connectionOpener(0xc4211f6370)
	/usr/local/go/src/database/sql/sql.go:730 +0x4a
created by database/sql.Open
	/usr/local/go/src/database/sql/sql.go:493 +0x1e9

goroutine 1073 [select]:
github.com/cockroachdb/cockroach/storage.(*Replica).redirectOnOrAcquireLease(0xc42017f200, 0x7f307b769b00, 0xc4208fd2c0, 0x6457d0)
	/go/src/github.com/cockroachdb/cockroach/storage/replica.go:750 +0x4ec
github.com/cockroachdb/cockroach/storage.(*Replica).getLeaseForGossip.func1()
	/go/src/github.com/cockroachdb/cockroach/storage/replica.go:2779 +0x6f
github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunTask(0xc421104ab0, 0xc42151bdb0, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:215 +0x100
github.com/cockroachdb/cockroach/storage.(*Replica).getLeaseForGossip(0xc42017f200, 0x7f307b769b00, 0xc4208fd2c0, 0x10, 0x0)
	/go/src/github.com/cockroachdb/cockroach/storage/replica.go:2810 +0x112
github.com/cockroachdb/cockroach/storage.(*Store).maybeGossipSystemConfig(0xc420e01400, 0xc420c8faa0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/storage/store.go:1107 +0x98
github.com/cockroachdb/cockroach/storage.(*Store).startGossip.func2()
	/go/src/github.com/cockroachdb/cockroach/storage/store.go:1060 +0x20d
github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker.func1(0xc421104ab0, 0xc4211d2cc0)
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:187 +0x7d
created by github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:188 +0x66

goroutine 1085 [select, 1 minutes]:
github.com/cockroachdb/cockroach/storage.(*baseQueue).processLoop.func1()
	/go/src/github.com/cockroachdb/cockroach/storage/queue.go:418 +0x2cc
github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker.func1(0xc421104ab0, 0xc4210cd5e0)
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:187 +0x7d
created by github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:188 +0x66

goroutine 1078 [select, 1 minutes]:
github.com/cockroachdb/cockroach/storage.(*baseQueue).processLoop.func1()
	/go/src/github.com/cockroachdb/cockroach/storage/queue.go:418 +0x2cc
github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker.func1(0xc421104ab0, 0xc4210cd4c0)
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:187 +0x7d
created by github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:188 +0x66

goroutine 1079 [select, 1 minutes]:
github.com/cockroachdb/cockroach/storage.(*baseQueue).processLoop.func1()
	/go/src/github.com/cockroachdb/cockroach/storage/queue.go:418 +0x2cc
github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker.func1(0xc421104ab0, 0xc4210cd4e0)
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:187 +0x7d
created by github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:188 +0x66

goroutine 1080 [select]:
github.com/cockroachdb/cockroach/storage.(*baseQueue).processLoop.func1()
	/go/src/github.com/cockroachdb/cockroach/storage/queue.go:418 +0x2cc
github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker.func1(0xc421104ab0, 0xc4210cd500)
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:187 +0x7d
created by github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:188 +0x66

goroutine 1081 [select, 1 minutes]:
github.com/cockroachdb/cockroach/storage.(*baseQueue).processLoop.func1()
	/go/src/github.com/cockroachdb/cockroach/storage/queue.go:418 +0x2cc
github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker.func1(0xc421104ab0, 0xc4210cd520)
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:187 +0x7d
created by github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:188 +0x66

goroutine 1082 [select]:
github.com/cockroachdb/cockroach/storage.(*Replica).redirectOnOrAcquireLease(0xc42017f200, 0x7f307b769b00, 0xc420734780, 0xc4212b9680)
	/go/src/github.com/cockroachdb/cockroach/storage/replica.go:750 +0x4ec
github.com/cockroachdb/cockroach/storage.(*Replica).addReadOnlyCmd(0xc42017f200, 0x7f307b769b00, 0xc420734780, 0x1472ddcb65a6941d, 0x0, 0x300000003, 0x3, 0x1, 0x0, 0x0, ...)
	/go/src/github.com/cockroachdb/cockroach/storage/replica.go:1356 +0x497
github.com/cockroachdb/cockroach/storage.(*Replica).Send(0xc42017f200, 0x7f307b769b00, 0xc420734780, 0x1472ddcb65a6941d, 0x0, 0x300000003, 0x3, 0x1, 0x0, 0x0, ...)
	/go/src/github.com/cockroachdb/cockroach/storage/replica.go:1027 +0x481
github.com/cockroachdb/cockroach/storage.(*Store).Send(0xc420e01400, 0x7f307b769b00, 0xc420734660, 0x1472ddcb65a6941d, 0x0, 0x300000003, 0x3, 0x1, 0x0, 0x0, ...)
	/go/src/github.com/cockroachdb/cockroach/storage/store.go:2112 +0x75e
github.com/cockroachdb/cockroach/storage.(*Stores).Send(0xc421203ac0, 0x7f307b769b00, 0xc420734540, 0x0, 0x0, 0x300000003, 0x3, 0x1, 0x0, 0x0, ...)
	/go/src/github.com/cockroachdb/cockroach/storage/stores.go:182 +0x202
github.com/cockroachdb/cockroach/server.(*Node).Batch.func3()
	/go/src/github.com/cockroachdb/cockroach/server/node.go:823 +0x304
github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunTask(0xc421104ab0, 0xc420c07cd8, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:215 +0x100
github.com/cockroachdb/cockroach/server.(*Node).Batch(0xc4207e2000, 0x7f307b769b00, 0xc420734360, 0xc421218708, 0x0, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/server/node.go:835 +0x275
github.com/cockroachdb/cockroach/kv.(*grpcTransport).SendNext(0xc420bccc00, 0xc420015080)
	/go/src/github.com/cockroachdb/cockroach/kv/transport.go:175 +0x1d6
github.com/cockroachdb/cockroach/kv.(*DistSender).sendToReplicas(0xc4212b82d0, 0x7f307b769b00, 0xc420734360, 0x2540be400, 0x0, 0x1, 0xc42091eb90, 0x3, 0x3, 0x0, ...)
	/go/src/github.com/cockroachdb/cockroach/kv/dist_sender.go:1024 +0x1f9
github.com/cockroachdb/cockroach/kv.(*DistSender).sendRPC(0xc4212b82d0, 0x7f307b769b00, 0xc420734360, 0x1, 0xc42091eb90, 0x3, 0x3, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/cockroachdb/cockroach/kv/dist_sender.go:377 +0x161
github.com/cockroachdb/cockroach/kv.(*DistSender).sendSingleRange(0xc4212b82d0, 0x7f307b769b00, 0xc420734360, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/cockroachdb/cockroach/kv/dist_sender.go:483 +0x257
github.com/cockroachdb/cockroach/kv.(*DistSender).sendChunk.func2(0xc420c08b40, 0xc420c08a00, 0xc420c09068, 0xc4212b82d0, 0xc420c09058, 0x0, 0xc4211700b8)
	/go/src/github.com/cockroachdb/cockroach/kv/dist_sender.go:777 +0x18e
github.com/cockroachdb/cockroach/kv.(*DistSender).sendChunk(0xc4212b82d0, 0x7f307b769b00, 0xc420734360, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/cockroachdb/cockroach/kv/dist_sender.go:778 +0x6aa
github.com/cockroachdb/cockroach/kv.(*DistSender).Send(0xc4212b82d0, 0x7f307b769b00, 0xc420734360, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/cockroachdb/cockroach/kv/dist_sender.go:594 +0x1d6
github.com/cockroachdb/cockroach/kv.(*TxnCoordSender).Send(0xc4211f6bb0, 0x7f307b769b00, 0xc420734360, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/cockroachdb/cockroach/kv/txn_coord_sender.go:391 +0x5de
github.com/cockroachdb/cockroach/internal/client.(*DB).send(0xc420921310, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/cockroachdb/cockroach/internal/client/db.go:497 +0xe1
github.com/cockroachdb/cockroach/internal/client.(*DB).(github.com/cockroachdb/cockroach/internal/client.send)-fm(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/cockroachdb/cockroach/internal/client/db.go:435 +0x58
github.com/cockroachdb/cockroach/internal/client.sendAndFill(0xc420c09a40, 0xc42043e000, 0x0, 0xc420c15c08)
	/go/src/github.com/cockroachdb/cockroach/internal/client/db.go:417 +0x168
github.com/cockroachdb/cockroach/internal/client.(*DB).Run(0xc420921310, 0xc42043e000, 0x1, 0x1)
	/go/src/github.com/cockroachdb/cockroach/internal/client/db.go:435 +0x75
github.com/cockroachdb/cockroach/storage.(*replicaGCQueue).process(0xc4211f71e0, 0x7f307b769b00, 0xc4207342d0, 0x1472ddcb65a56075, 0x0, 0xc42017f200, 0xc420441000, 0x13, 0x20, 0x5f89d8, ...)
	/go/src/github.com/cockroachdb/cockroach/storage/replica_gc_queue.go:169 +0x1c3
github.com/cockroachdb/cockroach/storage.(*baseQueue).processReplica(0xc4211f71e0, 0xc42017f200, 0xc421203740, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/storage/queue.go:501 +0x3c0
github.com/cockroachdb/cockroach/storage.(*baseQueue).processLoop.func1.2()
	/go/src/github.com/cockroachdb/cockroach/storage/queue.go:439 +0x58
github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunTask(0xc421104ab0, 0xc420c09e58, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:215 +0x100
github.com/cockroachdb/cockroach/storage.(*baseQueue).processLoop.func1()
	/go/src/github.com/cockroachdb/cockroach/storage/queue.go:443 +0x296
github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker.func1(0xc421104ab0, 0xc4210cd540)
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:187 +0x7d
created by github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:188 +0x66

goroutine 1083 [select, 1 minutes]:
github.com/cockroachdb/cockroach/storage.(*baseQueue).processLoop.func1()
	/go/src/github.com/cockroachdb/cockroach/storage/queue.go:418 +0x2cc
github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker.func1(0xc421104ab0, 0xc4210cd560)
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:187 +0x7d
created by github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:188 +0x66

goroutine 1084 [select]:
github.com/cockroachdb/cockroach/storage.(*replicaScanner).waitAndProcess(0xc4210cec80, 0xecf658b93, 0xc42d353d90, 0x22a9260, 0xc421203740, 0xc421104ab0, 0xc42017f200, 0xc420b8dea8)
	/go/src/github.com/cockroachdb/cockroach/storage/scanner.go:201 +0x237
github.com/cockroachdb/cockroach/storage.(*replicaScanner).scanLoop.func1.1(0xc42017f200, 0xc420b00ae0)
	/go/src/github.com/cockroachdb/cockroach/storage/scanner.go:259 +0x7c
github.com/cockroachdb/cockroach/storage.(*storeRangeSet).Visit(0xc420b00cf0, 0xc42027be00)
	/go/src/github.com/cockroachdb/cockroach/storage/store.go:246 +0x21b
github.com/cockroachdb/cockroach/storage.(*replicaScanner).scanLoop.func1()
	/go/src/github.com/cockroachdb/cockroach/storage/scanner.go:261 +0x233
github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker.func1(0xc421104ab0, 0xc4210cd580)
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:187 +0x7d
created by github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:188 +0x66

goroutine 1086 [select, 1 minutes]:
github.com/cockroachdb/cockroach/storage.(*replicaScanner).waitAndProcess(0xc4210ced00, 0xecf658b5c, 0xc42cad0c3a, 0x22a9260, 0xc421203740, 0xc421104ab0, 0x0, 0x61ad43)
	/go/src/github.com/cockroachdb/cockroach/storage/scanner.go:201 +0x237
github.com/cockroachdb/cockroach/storage.(*replicaScanner).scanLoop.func1()
	/go/src/github.com/cockroachdb/cockroach/storage/scanner.go:264 +0x311
github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker.func1(0xc421104ab0, 0xc4210cd600)
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:187 +0x7d
created by github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:188 +0x66

goroutine 1211 [IO wait]:
net.runtime_pollWait(0x7f307b76a3f8, 0x72, 0x3)
	/usr/local/go/src/runtime/netpoll.go:160 +0x59
net.(*pollDesc).wait(0xc4214c2ae0, 0x72, 0xc420a82828, 0xc4200100b8)
	/usr/local/go/src/net/fd_poll_runtime.go:73 +0x38
net.(*pollDesc).waitRead(0xc4214c2ae0, 0x1f6ebc0, 0xc4200100b8)
	/usr/local/go/src/net/fd_poll_runtime.go:78 +0x34
net.(*netFD).Read(0xc4214c2a80, 0xc4214b9800, 0x400, 0x400, 0x0, 0x1f6ebc0, 0xc4200100b8)
	/usr/local/go/src/net/fd_unix.go:243 +0x1a1
net.(*conn).Read(0xc42154a040, 0xc4214b9800, 0x400, 0x400, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/net.go:173 +0x70
crypto/tls.(*block).readFromUntil(0xc420d22cf0, 0x7f307b643d00, 0xc42154a040, 0x5, 0xc42154a040, 0xc42152d260)
	/usr/local/go/src/crypto/tls/conn.go:472 +0x91
crypto/tls.(*Conn).readRecord(0xc4214c8700, 0x176e617, 0xc4214c8800, 0x6458e0)
	/usr/local/go/src/crypto/tls/conn.go:574 +0xc4
crypto/tls.(*Conn).Read(0xc4214c8700, 0xc421656000, 0x8000, 0x8000, 0x0, 0x0, 0x0)
	/usr/local/go/src/crypto/tls/conn.go:1109 +0x116
bufio.(*Reader).fill(0xc420265b00)
	/usr/local/go/src/bufio/bufio.go:97 +0x10c
bufio.(*Reader).Read(0xc420265b00, 0xc42092a278, 0x9, 0x9, 0xc420a82ca8, 0x6457d0, 0xc420bcc300)
	/usr/local/go/src/bufio/bufio.go:209 +0x1bc
io.ReadAtLeast(0x1f67300, 0xc420265b00, 0xc42092a278, 0x9, 0x9, 0x9, 0x30, 0xc421131b08, 0x1f6b1c0)
	/usr/local/go/src/io/io.go:307 +0xa4
io.ReadFull(0x1f67300, 0xc420265b00, 0xc42092a278, 0x9, 0x9, 0xc420a82eb0, 0xeec4b0, 0xc4216442d0)
	/usr/local/go/src/io/io.go:325 +0x58
golang.org/x/net/http2.readFrameHeader(0xc42092a278, 0x9, 0x9, 0x1f67300, 0xc420265b00, 0x0, 0xc400000000, 0xc42152d260, 0xc)
	/go/src/golang.org/x/net/http2/frame.go:237 +0x7b
golang.org/x/net/http2.(*Framer).ReadFrame(0xc42092a240, 0x0, 0x0, 0x0, 0x0)
	/go/src/golang.org/x/net/http2/frame.go:464 +0xa4
google.golang.org/grpc/transport.(*framer).readFrame(0xc421130540, 0xc421245170, 0xc421245170, 0x0, 0x0)
	/go/src/google.golang.org/grpc/transport/http_util.go:505 +0x2f
google.golang.org/grpc/transport.(*http2Client).reader(0xc420711100)
	/go/src/google.golang.org/grpc/transport/http2_client.go:921 +0xb6
created by google.golang.org/grpc/transport.newHTTP2Client
	/go/src/google.golang.org/grpc/transport/http2_client.go:203 +0x8b1

goroutine 1214 [select]:
github.com/cockroachdb/cockroach/rpc.(*Context).runHeartbeat(0xc420147280, 0xc4215fe000, 0xc4211b2050, 0xf, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/rpc/context.go:294 +0x645
github.com/cockroachdb/cockroach/rpc.(*Context).GRPCDial.func1.1.1()
	/go/src/github.com/cockroachdb/cockroach/rpc/context.go:217 +0x69
github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker.func1(0xc421104ab0, 0xc4211305d0)
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:187 +0x7d
created by github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:188 +0x66

goroutine 1207 [select]:
github.com/cockroachdb/cockroach/rpc.(*Context).runHeartbeat(0xc420bc2280, 0xc420710b00, 0xc4207f2700, 0xf, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/rpc/context.go:294 +0x645
github.com/cockroachdb/cockroach/rpc.(*Context).GRPCDial.func1.1.1()
	/go/src/github.com/cockroachdb/cockroach/rpc/context.go:217 +0x69
github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker.func1(0xc421216990, 0xc4204b1f80)
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:187 +0x7d
created by github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:188 +0x66


ERROR: exit status 255
```

Run Details:

```
32 runs so far, 0 failures, over 5s
64 runs so far, 0 failures, over 10s
105 runs so far, 0 failures, over 15s
144 runs so far, 0 failures, over 20s
177 runs so far, 0 failures, over 25s
220 runs so far, 0 failures, over 30s
256 runs so far, 0 failures, over 35s
295 runs so far, 0 failures, over 40s
334 runs so far, 0 failures, over 45s
369 runs so far, 0 failures, over 50s
409 runs so far, 0 failures, over 55s
446 runs so far, 0 failures, over 1m0s
487 runs so far, 0 failures, over 1m5s
524 runs so far, 0 failures, over 1m10s
559 runs so far, 0 failures, over 1m15s
600 runs so far, 0 failures, over 1m20s
635 runs so far, 0 failures, over 1m25s
675 runs so far, 0 failures, over 1m30s
711 runs so far, 0 failures, over 1m35s
749 runs so far, 0 failures, over 1m40s
786 runs so far, 0 failures, over 1m45s
823 runs so far, 0 failures, over 1m50s
858 runs so far, 0 failures, over 1m55s
895 runs so far, 0 failures, over 2m0s
931 runs so far, 0 failures, over 2m5s
966 runs so far, 0 failures, over 2m10s
1001 runs so far, 0 failures, over 2m15s
1033 runs so far, 0 failures, over 2m20s
1068 runs so far, 0 failures, over 2m25s
1099 runs so far, 0 failures, over 2m30s
1133 runs so far, 0 failures, over 2m35s
1166 runs so far, 0 failures, over 2m40s
1197 runs so far, 0 failures, over 2m45s
1232 runs so far, 0 failures, over 2m50s
1262 runs so far, 0 failures, over 2m55s
1297 runs so far, 0 failures, over 3m0s
1329 runs so far, 0 failures, over 3m5s
1360 runs so far, 0 failures, over 3m10s
1393 runs so far, 0 failures, over 3m15s
1427 runs so far, 0 failures, over 3m20s
1453 runs completed, 1 failures, over 3m24s
FAIL
```
Please assign, take a look and update the issue accordingly.

### PR DESCRIPTION
**Pull request by bdarnell**
This mitigates issues seen when running the gossip and testcluster tests
under stress. It cannot be turned on by default because it breaks
certificate validation, so it is only used for the specific tests that
have seen issues.

Fixes #9016
Fixes #9256

---

This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/9457)

### CODE REVIEW

**Comment by petermattis** [comment]
LGTM

File: util/unresolved_addr.go [hunk 1]
```diff
@@ -21,10 +21,28 @@ import (
...
 )
 
-// TestAddr is an address to use for test servers. Listening on port 0 causes
-// the kernel to allocate an unused port.
+// TestAddr is an address to use for test servers. Listening on port 0
+// causes the kernel to allocate an unused port.
 var TestAddr = NewUnresolvedAddr("tcp", "127.0.0.1:0")
 
+// IsolatedTestAddr is initialized in testaddr_*.go
+
```
Comment (tamird) [inline util/unresolved_addr.go]: is this line missing a `//` ?

File: util/unresolved_addr.go [hunk 2]
```diff
@@ -21,10 +21,28 @@ import (
...
+// IsolatedTestAddr guarantee that the chosen port is not in use when
+// allocated, but IsolatedTestAddr draws from a larger pool of
+// addresses so that when tests are run in a tight loop the system is
+// less likely to run out of available ports or give a port to one
+// test immediately after it was closed by another.
+//
+// IsolatedTestAddr should be used for tests that open and close a
+// large number of sockets, or tests which stop a server and rely on
+// seeing a "connection refused" error afterwards. It cannot be used
+// with tests that operate in secure mode since our test certificates
```
Comment (tamird) [inline util/unresolved_addr.go]: we could probably change that, right?

File: util/unresolved_addr.go [hunk 3]
```diff
@@ -21,10 +21,28 @@ import (
...
+// are only valid for 127.0.0.1.
+var IsolatedTestAddr *UnresolvedAddr
```
Comment (tamird) [inline util/unresolved_addr.go]: this probably wants to be `net.Addr` rather than `*UnresolvedAddr`

**Review by tamird — COMMENTED** [review]
LGTM but I think we can get rid of TestAddr entirely if we change the test certificates to be more permissive -- is there any reason not to do so?

File: util/unresolved_addr.go (hunk 1 above)
Comment (bdarnell) [inline util/unresolved_addr.go]: No, it's deliberate - the docstring starts on the following line; the preceding comment is for readers of the source but is not a part of the godoc documentation.

File: util/unresolved_addr.go (hunk 2 above)
Comment (bdarnell) [inline util/unresolved_addr.go]: Theoretically, but we'd need to list all the IPs we want to use individually. Wildcards are not supported in certificates when using literal IPs.

File: util/unresolved_addr.go (hunk 3 above)
Comment (bdarnell) [inline util/unresolved_addr.go]: I was following the example of TestAddr (which I had originally planned to replace entirely before I discovered the cert issue).
