### PR TITLE
builtins: fix st_asmvtgeom to return NULL for empty geometry

### LINKED ISSUE #106884: roachtest/sqlsmith: error when parsing empty string as geometry on remote node
roachtest.sqlsmith/setup=seed/setting=no-mutations [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/10927781?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/10927781?buildTab=artifacts#/sqlsmith/setup=seed/setting=no-mutations) on master @ [c609b823b0a1fda5b7d605e4645cd452a6009961](https://github.com/cockroachdb/cockroach/commits/c609b823b0a1fda5b7d605e4645cd452a6009961):

```
(sqlsmith.go:255).func3: error: pq: internal error: unable to vectorize execution plan: st_distancespheroid('':::GEOMETRY, '010400004009000000010100004094B6AF287E2CE24118CCCB3E2DF7FAC1F2A022E40786E0C10101000040F688CA0FD0D9F9C1E09FE29D8352E24148B7F6A16B7801420101000040E04A38C25B47BAC130CA9DEC93410142E404B8B5BCE2F4C10101000040E8E2CEF5175200426CBFE7E5B72902C268F4240B189BDD410101000040B4EB7AE630DF014203CF82CAD4DAFDC1F617E2830873F9410101000040CFFC5B46DA4BFFC1A221CFC39137F2411EF215A53DACF24101010000400ECAF201E709FCC1701CB129E104EDC1A0FF43871378CBC10101000040081277EF4DCAD441FCF0227BFBAC01427384AE810B4A00C201010000408C7EB4E1E943FBC1E2E4BC4C4221F541AE5931626832FA41':::GEOMETRY): st_distancespheroid(): could not parse geometry: geo: parsing empty string to geo type
stmt:
SELECT
	NULL AS "c%43ol19368",
	t😼ab7523._int8 AS col19369,
	t😼ab7523._decimal AS col19370,
	t😼ab7523._jsonb AS col19371,
	t😼ab7523._enum AS col19372,
	t😼ab7523._inet AS col19373,
	t😼ab7523._timestamptz AS "😓Col19374",
	text(t😼ab7523.tableoid::OID)::STRING AS " col19375",
	7846:::INT8 AS "co\\U0001872Fl͓19376",
	NULL AS col19377,
	t😼ab7523._float4 AS col19378,
	'-41 years -11 mons -890 days -08:03:10.907113':::INTERVAL AS col19379,
	st_distancespheroid(st_asmvtgeom('01060000C000000000':::GEOMETRY::GEOMETRY, 'BOX(-2.4310452547766257 -0.7340617188515679,1.4606149586106913 1.509111744681483)':::BOX2D::BOX2D, 7410621793587869914:::INT8::INT8)::GEOMETRY::GEOMETRY, '010400004009000000010100004094B6AF287E2CE24118CCCB3E2DF7FAC1F2A022E40786E0C10101000040F688CA0FD0D9F9C1E09FE29D8352E24148B7F6A16B7801420101000040E04A38C25B47BAC130CA9DEC93410142E404B8B5BCE2F4C10101000040E8E2CEF5175200426CBFE7E5B72902C268F4240B189BDD410101000040B4EB7AE630DF014203CF82CAD4DAFDC1F617E2830873F9410101000040CFFC5B46DA4BFFC1A221CFC39137F2411EF215A53DACF24101010000400ECAF201E709FCC1701CB129E104EDC1A0FF43871378CBC10101000040081277EF4DCAD441FCF0227BFBAC01427384AE810B4A00C201010000408C7EB4E1E943FBC1E2E4BC4C4221F541AE5931626832FA41':::GEOMETRY::GEOMETRY)::FLOAT8
		AS "coL19380"
FROM
	defaultdb.public.seed@[0] AS t😼ab7523;
test artifacts and logs in: /artifacts/sqlsmith/setup=seed/setting=no-mutations/run_1
```
<p>Parameters: <code>ROACHTEST_arch=amd64</code>
, <code>ROACHTEST_cloud=gce</code>
, <code>ROACHTEST_cpu=4</code>
, <code>ROACHTEST_encrypted=false</code>
, <code>ROACHTEST_ssd=0</code>
</p>
<details><summary>Help</summary>
<p>

See: [roachtest README](https://github.com/cockroachdb/cockroach/blob/master/pkg/cmd/roachtest/README.md)

See: [How To Investigate \(internal\)](https://cockroachlabs.atlassian.net/l/c/SSSBr8c7)

</p>
</details>
/cc @cockroachdb/sql-queries
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*sqlsmith/setup=seed/setting=no-mutations.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)
</sub>

Jira issue: CRDB-29751

### PR DESCRIPTION
**Pull request by yuzefovich**
Previously, when `st_asmvtgeom` resulted in an empty geometry, we would create an empty `DGeometry` object, which is different from `DNull`. This is incorrect (different from postgres) and could lead to internal errors in distributed plans. This is now fixed. No release note given that this is a new feature.

Fixes: #106884.

Release note: None

### CODE REVIEW

File: pkg/sql/sem/builtins/geo_builtins.go [hunk 1]
```diff
@@ -7898,3 +7882,16 @@ func geosVersion() string {
...
 }
+
+func asMVTGeometry(
+	g geo.Geometry, bounds geo.CartesianBoundingBox, extent int, buffer int, clipGeometry bool,
+) (tree.Datum, error) {
+	newGeom, err := geomfn.AsMVTGeometry(g, bounds, extent, buffer, clipGeometry)
+	if err != nil {
+		return nil, err
+	}
+	if newGeom == nil {
```
Comment (otan) [inline pkg/sql/sem/builtins/geo_builtins.go:7893]: if you wanted to micro optimise, you could leave the return of AsMVTGeometry as an empty geometry struct instead of making it a pointer and do `if newGeom ==  geo.Geometry {` (there's prior art doing this iirc and it makes a sizable difference)

**Review by otan — APPROVED** [review]
you have a habit of ccing me on issues whilst I'm browsing emails on my lunch break haha! lgtm, thanks for getting to this so quick

**Review by yuzefovich — COMMENTED** [review]
TFTR!

bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/107515#-:-NaCoJaD5_-qKPxRrlya:b-oduykh)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @otan)

___
*[`pkg/sql/sem/builtins/geo_builtins.go` line 7893 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/107515#gh-1272941545:-NaCnzlGBaXuzJsCeGrd:bkdm9ke) ([raw file](https://github.com/cockroachdb/cockroach/blob/2227520d0be1014bce7eaee78aaad1db1e67fd81/pkg/sql/sem/builtins/geo_builtins.go#L7893)):*
<details><summary><i>Previously, otan (Oliver Tan) wrote…</i></summary><blockquote>

if you wanted to micro optimise (the pointer allocation can be significant), you could leave ~the return of AsMVTGeometry as an empty geometry struct instead of making it a pointer and do `if newGeom ==  (geo.Geometry{}) {` (there's prior art doing this iirc and it makes a sizable difference)~ use something like

```go

	newGeom, err := geomfn.AsMVTGeometry(g, bounds, extent, buffer, clipGeometry)
	if err != nil {
					if geo.IsEmptyGeometryError(err) {
						return tree.DNull, nil
					}
          return nil, err
   }

   //...
```

instead of making `AsMVTGeometry` return a pointer, and `return nil, nil` to

```go
	if geometrySmallerThanHalfBoundingBox(gt, bbox, extent) {
		return geo.Geometry{}, NewEmptyGeometryError()
	}
```
</blockquote></details>

It seems like there are more cases when empty geometry is returned (according to the unit tests in `geomfn` package), so instead I switched to calling `geo.Geometry.Empty` here.
