### PR TITLE
democluster: deflake TestTransientClusterSimulateLatencies

### LINKED ISSUE #99426: cli: Example_demo_locality failed
cli.Example_demo_locality [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Ci_TestsAwsLinuxArm64_UnitTests/9220864?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Ci_TestsAwsLinuxArm64_UnitTests/9220864?buildTab=artifacts#/) on release-23.1 @ [310a949162d4d530677147626bc7a72289c987b0](https://github.com/cockroachdb/cockroach/commits/310a949162d4d530677147626bc7a72289c987b0):

Fatal error:

```
panic: test timed out after 14m55s

```
Stack: 

```
goroutine 437362 [running]:
testing.(*M).startAlarm.func1()
	GOROOT/src/testing/testing.go:2036 +0x88
created by time.goFunc
	GOROOT/src/time/sleep.go:176 +0x38
```
<details><summary>Log preceding fatal error</summary>
<p>

```
=== RUN   Example_demo_locality
[demo --nodes 3 --multitenant=false -e select node_id, locality from crdb_internal.gossip_nodes order by node_id]
[demo --nodes 9 --multitenant=false -e select node_id, locality from crdb_internal.gossip_nodes order by node_id]
*
* ERROR: initialization timeout while waiting for server 0 readiness
*
```
</p>
</details>
<details><summary>Help</summary>
<p>

See also: [How To Investigate a Go Test Failure \(internal\)](https://cockroachlabs.atlassian.net/l/c/HgfXfJgM)
</p>
</details>
/cc @cockroachdb/sql-sessions @cockroachdb/server @cockroachdb/server
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*Example_demo_locality.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)
</sub>

Jira issue: CRDB-25874

### LINKED ISSUE #99768: cli/democluster: TestTransientClusterSimulateLatencies failed
cli/democluster.TestTransientClusterSimulateLatencies [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_StressBazel/9283877?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_StressBazel/9283877?buildTab=artifacts#/) on master @ [143b63a6a27aeb286637dd2e5abddafdf0c51874](https://github.com/cockroachdb/cockroach/commits/143b63a6a27aeb286637dd2e5abddafdf0c51874):

```
=== RUN   TestTransientClusterSimulateLatencies
    test_log_scope.go:161: test logs captured to: /artifacts/tmp/_tmp/1937dc802442f15720877ed362f2998f/logTestTransientClusterSimulateLatencies1498444968
    test_log_scope.go:79: use -show-logs to present logs inline
    demo_cluster_test.go:188: 
        	Error Trace:	github.com/cockroachdb/cockroach/pkg/cli/democluster/demo_cluster_test.go:188
        	Error:      	Received unexpected error:
        	            	initialization timeout while waiting for server 0 readiness
        	            	(1) attached stack trace
        	            	  -- stack trace:
        	            	  | github.com/cockroachdb/cockroach/pkg/cli/democluster.(*transientCluster).waitForSQLReadiness
        	            	  | 	github.com/cockroachdb/cockroach/pkg/cli/democluster/demo_cluster.go:782
        	            	  | github.com/cockroachdb/cockroach/pkg/cli/democluster.(*transientCluster).Start.func7
        	            	  | 	github.com/cockroachdb/cockroach/pkg/cli/democluster/demo_cluster.go:383
        	            	  | github.com/cockroachdb/cockroach/pkg/cli/democluster.(*transientCluster).Start
        	            	  | 	github.com/cockroachdb/cockroach/pkg/cli/democluster/demo_cluster.go:389
        	            	  | github.com/cockroachdb/cockroach/pkg/cli/democluster.TestTransientClusterSimulateLatencies
        	            	  | 	github.com/cockroachdb/cockroach/pkg/cli/democluster/demo_cluster_test.go:188
        	            	  | testing.tRunner
        	            	  | 	GOROOT/src/testing/testing.go:1446
        	            	  | runtime.goexit
        	            	  | 	GOROOT/src/runtime/asm_amd64.s:1594
        	            	Wraps: (2) initialization timeout while waiting for server 0 readiness
        	            	Error types: (1) *withstack.withStack (2) *errutil.leafError
        	Test:       	TestTransientClusterSimulateLatencies
    panic.go:522: -- test log scope end --
test logs left over in: /artifacts/tmp/_tmp/1937dc802442f15720877ed362f2998f/logTestTransientClusterSimulateLatencies1498444968
--- FAIL: TestTransientClusterSimulateLatencies (31.64s)
```
<p>Parameters: <code>TAGS=bazel,gss,deadlock</code>
</p>
<details><summary>Help</summary>
<p>

See also: [How To Investigate a Go Test Failure \(internal\)](https://cockroachlabs.atlassian.net/l/c/HgfXfJgM)
</p>
</details>
/cc @cockroachdb/sql-sessions @cockroachdb/server @cockroachdb/server
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*TestTransientClusterSimulateLatencies.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)
</sub>

Jira issue: CRDB-26062

### LINKED ISSUE #99903: cli: Example_demo_locality failed
cli.Example_demo_locality [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_StressBazel/9307389?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_StressBazel/9307389?buildTab=artifacts#/) on master @ [bb5c97b5d2073a27e7ec88654b05ac913112f610](https://github.com/cockroachdb/cockroach/commits/bb5c97b5d2073a27e7ec88654b05ac913112f610):

```
=== RUN   Example_demo_locality
[demo --nodes 3 --multitenant=false -e select node_id, locality from crdb_internal.gossip_nodes order by node_id]
[demo --nodes 9 --multitenant=false -e select node_id, locality from crdb_internal.gossip_nodes order by node_id]
*
* ERROR: initialization timeout while waiting for server 0 readiness
*
[demo --nodes 3 --multitenant=false --demo-locality=region=us-east1:region=us-east2:region=us-east3 -e select node_id, locality from crdb_internal.gossip_nodes order by node_id]
--- FAIL: Example_demo_locality (92.73s)
got:
demo --nodes 3 --multitenant=false -e select node_id, locality from crdb_internal.gossip_nodes order by node_id
node_id	locality
1	region=us-east1,az=b
2	region=us-east1,az=c
3	region=us-east1,az=d
demo --nodes 9 --multitenant=false -e select node_id, locality from crdb_internal.gossip_nodes order by node_id
ERROR: initialization timeout while waiting for server 0 readiness
demo --nodes 3 --multitenant=false --demo-locality=region=us-east1:region=us-east2:region=us-east3 -e select node_id, locality from crdb_internal.gossip_nodes order by node_id
node_id	locality
1	region=us-east1
2	region=us-east2
3	region=us-east3
want:
demo --nodes 3 --multitenant=false -e select node_id, locality from crdb_internal.gossip_nodes order by node_id
node_id	locality
1	region=us-east1,az=b
2	region=us-east1,az=c
3	region=us-east1,az=d
demo --nodes 9 --multitenant=false -e select node_id, locality from crdb_internal.gossip_nodes order by node_id
node_id	locality
1	region=us-east1,az=b
2	region=us-east1,az=c
3	region=us-east1,az=d
4	region=us-west1,az=a
5	region=us-west1,az=b
6	region=us-west1,az=c
7	region=europe-west1,az=b
8	region=europe-west1,az=c
9	region=europe-west1,az=d
demo --nodes 3 --multitenant=false --demo-locality=region=us-east1:region=us-east2:region=us-east3 -e select node_id, locality from crdb_internal.gossip_nodes order by node_id
node_id	locality
1	region=us-east1
2	region=us-east2
3	region=us-east3
```
<p>Parameters: <code>TAGS=bazel,gss,deadlock</code>
</p>
<details><summary>Help</summary>
<p>

See also: [How To Investigate a Go Test Failure \(internal\)](https://cockroachlabs.atlassian.net/l/c/HgfXfJgM)
</p>
</details>
<details><summary>Same failure on other branches</summary>
<p>

- #99426 cli: Example_demo_locality failed [C-test-failure O-robot branch-release-23.1]
</p>
</details>
/cc @cockroachdb/sql-sessions @cockroachdb/server @cockroachdb/server
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*Example_demo_locality.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)
</sub>

Jira issue: CRDB-26126

### LINKED ISSUE #100389: cli/democluster: TestTransientClusterSimulateLatencies failed
cli/democluster.TestTransientClusterSimulateLatencies [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_StressBazel/9374924?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_StressBazel/9374924?buildTab=artifacts#/) on release-23.1 @ [5d5abe704b0551556c35d51aa673d3162f493aa8](https://github.com/cockroachdb/cockroach/commits/5d5abe704b0551556c35d51aa673d3162f493aa8):

```
=== RUN   TestTransientClusterSimulateLatencies
    test_log_scope.go:161: test logs captured to: /artifacts/tmp/_tmp/1937dc802442f15720877ed362f2998f/logTestTransientClusterSimulateLatencies2953166516
    test_log_scope.go:79: use -show-logs to present logs inline
    demo_cluster_test.go:188: 
        	Error Trace:	github.com/cockroachdb/cockroach/pkg/cli/democluster/demo_cluster_test.go:188
        	Error:      	Received unexpected error:
        	            	initialization timeout while waiting for server 0 readiness
        	            	(1) attached stack trace
        	            	  -- stack trace:
        	            	  | github.com/cockroachdb/cockroach/pkg/cli/democluster.(*transientCluster).waitForSQLReadiness
        	            	  | 	github.com/cockroachdb/cockroach/pkg/cli/democluster/demo_cluster.go:782
        	            	  | github.com/cockroachdb/cockroach/pkg/cli/democluster.(*transientCluster).Start.func7
        	            	  | 	github.com/cockroachdb/cockroach/pkg/cli/democluster/demo_cluster.go:383
        	            	  | github.com/cockroachdb/cockroach/pkg/cli/democluster.(*transientCluster).Start
        	            	  | 	github.com/cockroachdb/cockroach/pkg/cli/democluster/demo_cluster.go:389
        	            	  | github.com/cockroachdb/cockroach/pkg/cli/democluster.TestTransientClusterSimulateLatencies
        	            	  | 	github.com/cockroachdb/cockroach/pkg/cli/democluster/demo_cluster_test.go:188
        	            	  | testing.tRunner
        	            	  | 	GOROOT/src/testing/testing.go:1446
        	            	  | runtime.goexit
        	            	  | 	GOROOT/src/runtime/asm_amd64.s:1594
        	            	Wraps: (2) initialization timeout while waiting for server 0 readiness
        	            	Error types: (1) *withstack.withStack (2) *errutil.leafError
        	Test:       	TestTransientClusterSimulateLatencies
    panic.go:522: -- test log scope end --
test logs left over in: /artifacts/tmp/_tmp/1937dc802442f15720877ed362f2998f/logTestTransientClusterSimulateLatencies2953166516
--- FAIL: TestTransientClusterSimulateLatencies (31.28s)
```
<p>Parameters: <code>TAGS=bazel,gss,deadlock</code>
</p>
<details><summary>Help</summary>
<p>

See also: [How To Investigate a Go Test Failure \(internal\)](https://cockroachlabs.atlassian.net/l/c/HgfXfJgM)
</p>
</details>
<details><summary>Same failure on other branches</summary>
<p>

- #99768 cli/democluster: TestTransientClusterSimulateLatencies failed [C-test-failure GA-blocker O-robot T-kv branch-master skipped-test]
</p>
</details>
/cc @cockroachdb/sql-sessions @cockroachdb/server @cockroachdb/server
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*TestTransientClusterSimulateLatencies.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)
</sub>

Jira issue: CRDB-26404

### PR DESCRIPTION
**Pull request by rafiss**
fixes https://github.com/cockroachdb/cockroach/issues/99768
fixes https://github.com/cockroachdb/cockroach/issues/100389
fixes https://github.com/cockroachdb/cockroach/issues/99903
fixes https://github.com/cockroachdb/cockroach/issues/99426

This increases the timeout and only skips the test under deadlock, rather than entirely.

Release note: None

### CODE REVIEW

**Review by ecwall — APPROVED** [review]

**Comment by rafiss** [comment]
tftr!

bors r+

File: pkg/cli/demo_locality_test.go [hunk 1]
```diff
@@ -17,14 +17,19 @@ import (
 	"github.com/cockroachdb/cockroach/pkg/cli/democluster"
 	"github.com/cockroachdb/cockroach/pkg/security/securityassets"
 	"github.com/cockroachdb/cockroach/pkg/util/log"
+	"github.com/cockroachdb/cockroach/pkg/util/syncutil"
 )
 
-var _ = skipExample_demo_locality
-
-func skipExample_demo_locality() {
+func Example_demo_locality() {
```
Comment (chengxiong-ruan) [inline pkg/cli/demo_locality_test.go:23]: not familiar with this test. but looks like this is not a test or used anywhere. could you educate me how does this work?

Comment (rafiss) [reply pkg/cli/demo_locality_test.go:23]: it's actually part of the go language. (something i didn't realize until i also saw these tests and were confused how they ran)

https://go.dev/blog/examples

**Comment by rafiss** [comment]
error was
```
  Cannot find commit 7d4fcfc92df4bec8491676f47d1047cc60d7acd3 in the https://github.com/cockroachdb/cockroach repository, possible reason: refs/heads/staging branch was updated and the commit selected for the build is not reachable anymore
  Failed to perform checkout on agent: Cannot find commit 7d4fcfc92df4bec8491676f47d1047cc60d7acd3 in the https://github.com/cockroachdb/cockroach repository, possible reason: refs/heads/staging branch was updated and the commit selected for the build is not reachable anymore
  
```

bors r+ single on
