### PR TITLE
cmd/roachtest: cdc tests reduce bank workload concurrency

### LINKED ISSUE #160001: roachtest: cdc/multi-table-pts-benchmark/per-table-pts=false/num-tables=5000/num-ranges=10 failed
roachtest.cdc/multi-table-pts-benchmark/per-table-pts=false/num-tables=5000/num-ranges=10 [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyAwsBazel/20895736?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyAwsBazel/20895736?buildTab=artifacts#/cdc/multi-table-pts-benchmark/per-table-pts=false/num-tables=5000/num-ranges=10) on release-26.1 @ [a281110ba2a9f256ddcd4385250ce798d9fc0f2b](https://github.com/cockroachdb/cockroach/commits/a281110ba2a9f256ddcd4385250ce798d9fc0f2b):

Failed with:

```
(cdc.go:1847).runCDCMultiTablePTSBenchmark: failed to initialize bank tables: full command output in run_080332.773658808_n4_cockroach-workload-i.log: COMMAND_PROBLEM: exit status 1
(cdc.go:402).Close: error shutting down prometheus/grafana: context canceled
test artifacts and logs in: /artifacts/cdc/multi-table-pts-benchmark/per-table-pts=false/num-tables=5000/num-ranges=10/cpu_arch=arm64/run_1
```
Cluster Node to Ip Mapping:
| Node | Public IP | Private IP |
| --- | --- | --- |
| teamcity-20895736-1766387361-52-n4cpu16-0001 | 3.144.243.87 | 10.12.11.58 |
| teamcity-20895736-1766387361-52-n4cpu16-0002 | 18.217.25.190 | 10.12.2.241 |
| teamcity-20895736-1766387361-52-n4cpu16-0003 | 3.135.211.203 | 10.12.15.130 |
| teamcity-20895736-1766387361-52-n4cpu16-0004 | 3.149.242.234 | 10.12.1.192 |

Parameters:
 - <code>arch=arm64</code>
 - <code>cloud=aws</code>
 - <code>coverageBuild=false</code>
 - <code>cpu=16</code>
 - <code>encrypted=false</code>
 - <code>fs=ext4</code>
 - <code>localSSD=true</code>
 - <code>runtimeAssertionsBuild=false</code>
 - <code>ssd=0</code>
<details><summary>Help</summary>
<p>

See: [roachtest README](https://github.com/cockroachdb/cockroach/blob/master/pkg/cmd/roachtest/README.md)

See: [How To Investigate \(internal\)](https://cockroachlabs.atlassian.net/l/c/SSSBr8c7)

_Grafana is not yet available for aws clusters_</p>
</details>
<details><summary>Same failure on other branches</summary>
<p>

- #159675 roachtest: cdc/multi-table-pts-benchmark/per-table-pts=false/num-tables=5000/num-ranges=10 failed [A-cdc C-test-failure O-roachtest O-robot T-cdc branch-master release-blocker]
</p>
</details>
/cc @cockroachdb/cdc
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*cdc/multi-table-pts-benchmark/per-table-pts=false/num-tables=5000/num-ranges=10.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/bazci/githubpost/issues)

</sub>

Jira issue: CRDB-58114

### PR DESCRIPTION
**Pull request by log-head**
While some cdc roachtests ran the bank workload with a large number of tables, there were flakes where importing a bank table hit the limit of retries (100).

This patch reduces the workload's import data loader concurrency for these tests from 32 to 8.

Fixes: #160001
Release note: None

### CODE REVIEW

File: pkg/ccl/workloadccl/fixture.go [hunk 1]
```diff
@@ -419,6 +419,7 @@ func ImportFixture(
 			concurrencyLimit = importLimit
 		}
 	}
+	log.Dev.Infof(ctx, `importing with concurrency limit %d`, concurrencyLimit)
```
Comment (aerfrei) [inline pkg/ccl/workloadccl/fixture.go:422]: I was trying to do a sanity check and make sure we saw this log in the tests, but the actual files in the artifacts in teamcity are very short and don't seem to have general logs in them. Have you ran this locally and seen this log?

File: pkg/cmd/roachtest/tests/cdc.go [hunk 2]
```diff
@@ -1841,7 +1841,7 @@ func runCDCMultiTablePTSBenchmark(
 	// TODO(#158779): When we add back per-table PTS, make sure that this test
 	// sets the cluster setting according to params.perTablePTS.
 
-	initCmd := fmt.Sprintf("./cockroach workload init bank --rows=%d --ranges=%d --tables=%d {pgurl%s}",
+	initCmd := fmt.Sprintf("./cockroach workload init bank --rows=%d --ranges=%d --tables=%d --import-concurrency-limit=8 {pgurl%s}",
```
Comment (aerfrei) [inline pkg/cmd/roachtest/tests/cdc.go]: The bank workload itself takes this flag, not only in the context of fixtures. (Look for workload.ImportDataLoaderConcurrencyFlag which is a string "import-concurrency-limit"). Is this using fixtures or does it create the workload setup from scratch every time? TBH I am a little confused about how fixtures work but if you saw that other log, I guess this does ultimately use fixtures.

File: pkg/ccl/workloadccl/fixture.go (hunk 1 above)
Comment (log-head) [reply pkg/ccl/workloadccl/fixture.go:422]: Yes, I have seen this log. You can see it in teamcity too. It's just in logs specific to the workload. https://teamcity.cockroachdb.com/repository/download/Cockroach_Nightlies_RoachtestNightlyAwsBazel/20946815:id/cdc/frontier-persistence-benchmark/interval%3D5s/tables%3D10000/ranges%3D1/run_2/artifacts.zip!/run_180109.689958568_n4_cockroach-workload-i.log

File: pkg/cmd/roachtest/tests/cdc.go (hunk 2 above)
Comment (log-head) [reply pkg/cmd/roachtest/tests/cdc.go]: tldr; yes, this uses fixtures.

My brief reading into this, `workload init` auto-selects IMPORT if the workload generator supports fixtures. That's determined by `SupportsFixtures(gen Generator)`, which uses fixtures if `FillBatch` (a func to populate) has been set in the generator. Which it is in bank.go, `func (b *bank) Tables()`. 

Then, when using the fixture, it will use the `import-concurrency-limit` flag, if passed, for the actual import operation; otherwise, it uses the default value of 32 set in the generator.

**Review by aerfrei — APPROVED** [review]

**Review by herkolategan — APPROVED** [review]

File: pkg/cmd/roachtest/tests/cdc.go (hunk 2 above)
Comment (andyyang890) [inline pkg/cmd/roachtest/tests/cdc.go]: Should we lower the default from 32? As far as I can tell, we're currently the only user of multi-table bank workloads, and I'd like to avoid other teams encountering a similar issue in the future.

https://github.com/cockroachdb/cockroach/blob/7608143ac62ab0ab1c412b488abf09593e5d6e62/pkg/workload/bank/bank.go#L76

Comment (andyyang890) [inline pkg/cmd/roachtest/tests/cdc.go]: For my own education, do you mind explaining how you determined this was the cause of the failure and also how you determined 8 would be a good limit?

Comment (log-head) [reply pkg/cmd/roachtest/tests/cdc.go]: First, just looking at the code of the importing fixture for the bank workload. This is where the tables (eg bank.bank_0, bank.bank_1, ...) are created.

The error looks like
`Error: importing fixture: importing table bank_981: pq: have retried transaction: unnamed (id: cf30c933-fb95-47e0-b77d-948301876c76) 101 times, most recently because of the retryable error:... WriteTooOldError: write for key /Table/3/2/0/0 at timestamp 1766390738.599991381,2 too old...`. 

This retry error in general comes from contention on the same key(s). This key, `/Table/3/2/0/0`, `/Table/3` is the `system.descriptor` table. `/2` is "_not a real index. It is a special ID used to construct index entries that inform the lease subsystem of descriptor updates within a transaction. The value for such an entry is a descpb.DescriptorUpdates message._" (pkg/keys/constants.go). The upshot, as far I can tell, is that if there are lots of descriptor updates when there are so many tables created concurrently. One of the transactions to create a table keeps getting bumped and retries. So, if it isn't able to commit the transaction after 100 attempts, that seems like too much contention. Which is why I decided to reduce the concurrency.

I wasn't able to get a reproduction running this again, so I'm unable to tell for sure that 8 will be a good limit. It seemed significantly reduced enough to remove this error, if this is the cause.

Comment (log-head) [reply pkg/cmd/roachtest/tests/cdc.go]: Seems reasonable.

Comment (log-head) [reply pkg/cmd/roachtest/tests/cdc.go]: Also, there was this comment already in the bank workload fixture's generator func, which sets the default to 32, that indicates that concurrency limitations should be considered.
pkg/workload/bank/bank.go
```
// Because this workload can create a large number of objects, the import
// concurrent may need to be limited.
```

**Review by log-head — COMMENTED** [review]
@andyyang890 I changed the default to be 8 and responded to your questions.

File: pkg/cmd/roachtest/tests/cdc.go (hunk 2 above)
Comment (andyyang890) [reply pkg/cmd/roachtest/tests/cdc.go]: Nice ok, seems reasonable

**Review by andyyang890 — APPROVED** [review]

**Comment by log-head** [comment]
You shall pass
