### PR TITLE
sql: fix SHOW COMPLETIONS slice bounds out of range

### LINKED ISSUE #96708: sql: v22.2.2: out of range in SHOW COMPLETIONS
This issue was autofiled by Sentry. It represents a crash or reported error on a live cluster with telemetry enabled.

Sentry link: https://cockroach-labs.sentry.io/issues/3921603022/?referrer=webhooks_plugin

Panic message:

>conn_executor.go:830: runtime error: slice bounds out of range [:145] with capacity 144
(1) attached stack trace
  -- stack trace:
  | github.com/cockroachdb/cockroach/pkg/sql.(*Server).ServeConn.func1
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:830
  | [...repeated from below...]
Wraps: (2) while executing: SHOW COMPLETIONS AT OFFSET 145 FOR '_'
Wraps: (3) attached stack trace
  -- stack trace:
  | github.com/cockroachdb/cockroach/pkg/sql.(*Server).ServeConn.func1
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:830
  | runtime.gopanic
  | 	GOROOT/src/runtime/panic.go:884
  | runtime.goPanicSliceAcap
  | 	GOROOT/src/runtime/panic.go:139
  | github.com/cockroachdb/cockroach/pkg/sql/delegate.RunShowCompletions
  | 	github.com/cockroachdb/cockroach/pkg/sql/delegate/show_completions.go:73
  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).runShowCompletions
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:1972
  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).runObserverStatement
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:1834
  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execStmt
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:111
  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execCmd.func1
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:1932
  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execCmd
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:1936
  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).run
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:1858
  | github.com/cockroachdb/cockroach/pkg/sql.(*Server).ServeConn
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:832
  | github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*conn).processCommandsAsync.func1
  | 	github.com/cockroachdb/cockroach/pkg/sql/pgwire/conn.go:728
  | runtime.goexit
  | 	GOROOT/src/runtime/asm_amd64.s:1594
Wraps: (4) runtime error: slice bounds out of range [:145] with capacity 144
Error types: (1) *withstack.withStack (2) *safedetails.withSafeDetails (3) *withstack.withStack (4) runtime.boundsError
-- report composition:
runtime.boundsError
conn_executor.go:830: *withstack.withStack (top exception)
*safedetails.withSafeDetails: while executing: SHOW COMPLETIONS AT OFFSET 145 FOR '_'
conn_executor.go:830: *withstack.withStack (1)
(check the extra data payloads)

<details>
<summary>Stacktrace (expand for inline code snippets):</summary>

https://github.com/cockroachdb/cockroach/blob/07a53a36601e9ca5fcffcff55f69b43c6dfbf1c1/pkg/sql/conn_executor.go#L829-L831 in pkg/sql.(*Server).ServeConn.func1
GOROOT/src/runtime/panic.go#L883-L885 in runtime.gopanic
GOROOT/src/runtime/panic.go#L138-L140 in runtime.goPanicSliceAcap
https://github.com/cockroachdb/cockroach/blob/07a53a36601e9ca5fcffcff55f69b43c6dfbf1c1/pkg/sql/delegate/show_completions.go#L72-L74 in pkg/sql/delegate.RunShowCompletions
https://github.com/cockroachdb/cockroach/blob/07a53a36601e9ca5fcffcff55f69b43c6dfbf1c1/pkg/sql/conn_executor_exec.go#L1971-L1973 in pkg/sql.(*connExecutor).runShowCompletions
https://github.com/cockroachdb/cockroach/blob/07a53a36601e9ca5fcffcff55f69b43c6dfbf1c1/pkg/sql/conn_executor_exec.go#L1833-L1835 in pkg/sql.(*connExecutor).runObserverStatement
https://github.com/cockroachdb/cockroach/blob/07a53a36601e9ca5fcffcff55f69b43c6dfbf1c1/pkg/sql/conn_executor_exec.go#L110-L112 in pkg/sql.(*connExecutor).execStmt
https://github.com/cockroachdb/cockroach/blob/07a53a36601e9ca5fcffcff55f69b43c6dfbf1c1/pkg/sql/conn_executor.go#L1931-L1933 in pkg/sql.(*connExecutor).execCmd.func1
https://github.com/cockroachdb/cockroach/blob/07a53a36601e9ca5fcffcff55f69b43c6dfbf1c1/pkg/sql/conn_executor.go#L1935-L1937 in pkg/sql.(*connExecutor).execCmd
https://github.com/cockroachdb/cockroach/blob/07a53a36601e9ca5fcffcff55f69b43c6dfbf1c1/pkg/sql/conn_executor.go#L1857-L1859 in pkg/sql.(*connExecutor).run
https://github.com/cockroachdb/cockroach/blob/07a53a36601e9ca5fcffcff55f69b43c6dfbf1c1/pkg/sql/conn_executor.go#L831-L833 in pkg/sql.(*Server).ServeConn
https://github.com/cockroachdb/cockroach/blob/07a53a36601e9ca5fcffcff55f69b43c6dfbf1c1/pkg/sql/pgwire/conn.go#L727-L729 in pkg/sql/pgwire.(*conn).processCommandsAsync.func1
GOROOT/src/runtime/asm_amd64.s#L1593-L1595 in runtime.goexit
</details>

```
pkg/sql/conn_executor.go in pkg/sql.(*Server).ServeConn.func1 at line 830
GOROOT/src/runtime/panic.go in runtime.gopanic at line 884
GOROOT/src/runtime/panic.go in runtime.goPanicSliceAcap at line 139
pkg/sql/delegate/show_completions.go in pkg/sql/delegate.RunShowCompletions at line 73
pkg/sql/conn_executor_exec.go in pkg/sql.(*connExecutor).runShowCompletions at line 1972
pkg/sql/conn_executor_exec.go in pkg/sql.(*connExecutor).runObserverStatement at line 1834
pkg/sql/conn_executor_exec.go in pkg/sql.(*connExecutor).execStmt at line 111
pkg/sql/conn_executor.go in pkg/sql.(*connExecutor).execCmd.func1 at line 1932
pkg/sql/conn_executor.go in pkg/sql.(*connExecutor).execCmd at line 1936
pkg/sql/conn_executor.go in pkg/sql.(*connExecutor).run at line 1858
pkg/sql/conn_executor.go in pkg/sql.(*Server).ServeConn at line 832
pkg/sql/pgwire/conn.go in pkg/sql/pgwire.(*conn).processCommandsAsync.func1 at line 728
GOROOT/src/runtime/asm_amd64.s in runtime.goexit at line 1594
```

| Tag | Value |
|---|---|
| Cockroach Release | `v22.2.2` |
| Cockroach SHA: | 07a53a36601e9ca5fcffcff55f69b43c6dfbf1c1 |
| Platform | linux amd64 |
| Distribution | CCL |
| Environment | v22.2.2 |
| Command | server |
| Go Version | ``|
| # of CPUs ||
| # of Goroutines ||

Jira issue: CRDB-24288

### PR DESCRIPTION
**Pull request by ecwall**
Fixes #96708

Previously SHOW COMPLETIONS could error on input where the offset is greater than the number of runes, but less than or equal to the number of bytes.

This PR fixes the issue by comparing the offset to the number of runes instead of number of bytes.

Release note (bug fix): Fix SHOW COMPLETIONS slice bounds out of range.

### CODE REVIEW

**Comment by ecwall** [comment]
This only affects 22.2 because SHOW COMPLETIONS was rewritten in 23.1+.

File: pkg/sql/delegate/show_completions_test.go [hunk 1]
```diff
@@ -30,8 +31,7 @@ func TestCompletions(t *testing.T) {
 			expectedCompletions: []string{"CREATE", "CREATEDB", "CREATELOGIN", "CREATEROLE"},
 		},
 		{
-			stmt:                "creat ",
-			expectedCompletions: []string{},
```
Comment (rafiss) [inline pkg/sql/delegate/show_completions_test.go:34]: nit: seems useful to be explicit that the expected completions are an empty slice (and same for below tests)

**Review by rafiss — APPROVED** [review]
lgtm! just had a minor comment about being explicit in the test's expected values

File: pkg/sql/delegate/show_completions_test.go (hunk 1 above)
Comment (ecwall) [reply pkg/sql/delegate/show_completions_test.go:34]: The function returns `nil`, not empty, which made the assertion confusing. I will add explicit `nil` though.

**Comment by ecwall** [comment]
bors r=rafiss

**Comment by ecwall** [comment]
bors r=rafiss
