### PR TITLE
roachtest: use internal name when setting PanicOnAssertions

### LINKED ISSUE #143642: roachtest: schemachange/secondary-index-multi-version failed
roachtest.schemachange/secondary-index-multi-version [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/19243121?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/19243121?buildTab=artifacts#/schemachange/secondary-index-multi-version) on master @ [80ae3796dff84f3770b964e66b223e74765d7f0c](https://github.com/cockroachdb/cockroach/commits/80ae3796dff84f3770b964e66b223e74765d7f0c):

```
(mixedversion.go:829).Run: mixed-version test failure while running step 1 (start cluster at version "v23.1.30"): COMMAND_PROBLEM: exit status 1 [owner=test-eng]
test artifacts and logs in: /artifacts/schemachange/secondary-index-multi-version/run_1
```

Parameters:
 - <code>arch=amd64</code>
 - <code>cloud=gce</code>
 - <code>coverageBuild=false</code>
 - <code>cpu=4</code>
 - <code>encrypted=false</code>
 - <code>metamorphicBufferedSender=true</code>
 - <code>mvtDeploymentMode=separate-process</code>
 - <code>mvtVersions=v23.1.30 → v23.2.21 → v24.1.14 → v24.3.8 → master</code>
 - <code>runtimeAssertionsBuild=false</code>
 - <code>ssd=0</code>
<details><summary>Help</summary>
<p>

See: [roachtest README](https://github.com/cockroachdb/cockroach/blob/master/pkg/cmd/roachtest/README.md)

See: [How To Investigate \(internal\)](https://cockroachlabs.atlassian.net/l/c/SSSBr8c7)

See: [Grafana](https://go.crdb.dev/roachtest-grafana/teamcity-19243121/schemachange-secondary-index-multi-version/1743150387299/1743150539950)

</p>
</details>
/cc @cockroachdb/test-eng
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*schemachange/secondary-index-multi-version.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/bazci/githubpost/issues)

</sub>

Jira issue: CRDB-48959

### LINKED ISSUE #143647: roachtest: sql-stats/mixed-version failed
roachtest.sql-stats/mixed-version [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/19243121?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/19243121?buildTab=artifacts#/sql-stats/mixed-version) on master @ [80ae3796dff84f3770b964e66b223e74765d7f0c](https://github.com/cockroachdb/cockroach/commits/80ae3796dff84f3770b964e66b223e74765d7f0c):

```
(mixedversion.go:829).Run: mixed-version test failure while running step 2 (start cluster at version "v23.1.10"): COMMAND_PROBLEM: exit status 1 [owner=test-eng]
test artifacts and logs in: /artifacts/sql-stats/mixed-version/run_1
```

Parameters:
 - <code>arch=amd64</code>
 - <code>cloud=gce</code>
 - <code>coverageBuild=false</code>
 - <code>cpu=4</code>
 - <code>encrypted=false</code>
 - <code>fs=ext4</code>
 - <code>localSSD=true</code>
 - <code>metamorphicBufferedSender=true</code>
 - <code>mvtDeploymentMode=shared-process</code>
 - <code>mvtVersions=v23.1.10 → v23.2.14 → v24.1.12 → v24.3.1 → master</code>
 - <code>runtimeAssertionsBuild=false</code>
 - <code>ssd=0</code>
<details><summary>Help</summary>
<p>

See: [roachtest README](https://github.com/cockroachdb/cockroach/blob/master/pkg/cmd/roachtest/README.md)

See: [How To Investigate \(internal\)](https://cockroachlabs.atlassian.net/l/c/SSSBr8c7)

See: [Grafana](https://go.crdb.dev/roachtest-grafana/teamcity-19243121/sql-stats-mixed-version/1743163821731/1743163992191)

</p>
</details>
<details><summary>Same failure on other branches</summary>
<p>

- #141418 roachtest: sql-stats/mixed-version failed [C-test-failure O-roachtest O-robot T-observability branch-release-24.3 target-release-25.1.1 target-release-25.1.2 v25.2.0-prerelease]
</p>
</details>
/cc @cockroachdb/test-eng
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*sql-stats/mixed-version.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/bazci/githubpost/issues)

</sub>

Jira issue: CRDB-48964

### PR DESCRIPTION
**Pull request by DarrylWong**
The user visible name for setting PanicOnAssertions was not added until 23.2. Attempting to use this on mixed version tests that upgrade from an earlier version will throw an unknown cluster setting error.

Fixes: https://github.com/cockroachdb/cockroach/issues/143647
Fixes: https://github.com/cockroachdb/cockroach/issues/143642
Release note: none

### CODE REVIEW

File: pkg/roachprod/install/cockroach.go [hunk 1]
```diff
@@ -1394,7 +1394,9 @@ func (c *SyncedCluster) generateClusterSettingCmd(
 		"enterprise.license":   license,
 		// N.B. We now enable `PanicOnAssertions` for all roachprod clusters.
 		// (See https://github.com/cockroachdb/cockroach/issues/136858)
-		"debug.panic_on_failed_assertions.enabled": "true",
+		// Use the internal name instead of the user visible name, which wasn't
+		// added until 23.2, to avoid breaking mixed version tests.
+		"debug.panic_on_failed_assertions": "true",
```
Comment (srosenberg) [inline pkg/roachprod/install/cockroach.go:1399]: The only side-effect is you get deprecation warning. The rename happened in [1].

[1] https://github.com/cockroachdb/cockroach/pull/109074

**Review by srosenberg — APPROVED** [review]
Thanks!

**Comment by DarrylWong** [comment]
TFTR!

bors r=srosenberg p=99
