### PR TITLE
server: de-flake TestClusterAPI

### LINKED ISSUE #19934: server: TestClusterAPI failed under stress
SHA: https://github.com/cockroachdb/cockroach/commits/b663a0cf109292ddbc22a872f0e301d92460b1aa

Parameters:
```
TAGS=
GOFLAGS=
```

Stress build found a failed test: https://teamcity.cockroachdb.com/viewLog.html?buildId=403306&tab=buildLog

```

```

### LINKED ISSUE #19935: server: TestClusterAPI/reportingOn=false failed under stress
SHA: https://github.com/cockroachdb/cockroach/commits/b663a0cf109292ddbc22a872f0e301d92460b1aa

Parameters:
```
TAGS=
GOFLAGS=
```

Stress build found a failed test: https://teamcity.cockroachdb.com/viewLog.html?buildId=403306&tab=buildLog

```

```

### LINKED ISSUE #19936: server: TestClusterAPI/reportingOn=false/enterpriseOn=false failed under stress
SHA: https://github.com/cockroachdb/cockroach/commits/b663a0cf109292ddbc22a872f0e301d92460b1aa

Parameters:
```
TAGS=
GOFLAGS=
```

Stress build found a failed test: https://teamcity.cockroachdb.com/viewLog.html?buildId=403306&tab=buildLog

```

```

### PR DESCRIPTION
**Pull request by tbg**
The test was overriding a settings value, but with the right interleaving
with a SQL migration that also updated it, the test would get stuck
with a `true` when it wanted a `false`. Repeatedly override the settings
value until the right result comes out instead.

Fixes #19934.
Fixes #19935.
Fixes #19936.

Release note: None

### CODE REVIEW

File: pkg/server/admin_test.go [hunk 1]
```diff
@@ -1060,6 +1059,10 @@ func TestClusterAPI(t *testing.T) {
 			// We need to retry, because the cluster ID isn't set until after
 			// bootstrapping.
 			testutils.SucceedsSoon(t, func() error {
+				// In particular, we need to repeatedly set this value, as there is
```
Comment (nvanbenschoten) [inline pkg/server/admin_test.go]: Would it be possible to detect when the SQL migration is complete and just wait for that right after starting the server?

Comment (tschottdorf) [reply pkg/server/admin_test.go]: I've switched to using `SET CLUSTER SETTING` which doesn't have this problem in the first place. Thanks for giving me that *brilliant* idea 😄
