### PR TITLE
release-22.1: xform: hoist projection from join only for canonical scans/selects

### LINKED ISSUE #79943: opt: join reordering and project pull-ups causes OOM
roachtest.sqlsmith/setup=rand-tables/setting=no-ddl [failed](https://teamcity.cockroachdb.com/viewLog.html?buildId=4888455&tab=buildLog) with [artifacts](https://teamcity.cockroachdb.com/viewLog.html?buildId=4888455&tab=artifacts#/sqlsmith/setup=rand-tables/setting=no-ddl) on master @ [cc07b5e7e670097560cb8412b380484773df1e96](https://github.com/cockroachdb/cockroach/commits/cc07b5e7e670097560cb8412b380484773df1e96):

```
The test failed on branch=master, cloud=gce:
test artifacts and logs in: /artifacts/sqlsmith/setup=rand-tables/setting=no-ddl/run_1
	sqlsmith.go:284,sqlsmith.go:304,test_runner.go:875: ping node 1: dial tcp 35.231.160.85:26257: connect: connection refused
		previous sql:
		WITH
			with_29360 (col_177842, col_177843)
				AS (
					SELECT
						NULL AS col_177842, (NULL, ARRAY[(-22928):::INT8,(-17919):::INT8]) AS col_177843
					FROM
						defaultdb.public.table1@[0] AS tab_93041,
						defaultdb.public.table2@table2_col2_16_col2_11_col2_8_col2_0_key AS tab_93042,
						defaultdb.public.table2@[0] AS tab_93043,
						defaultdb.public.table2@table2_col2_16_col2_11_col2_8_col2_0_key AS tab_93044
					WHERE
						EXISTS(
							WITH
								with_29359 (col_177840)
									AS (
										SELECT
											*
										FROM
											(VALUES ((-0.6331317560465642):::FLOAT8), (NULL)) AS tab_93045 (col_177840)
									)
							SELECT
								'0107000020E610000000000000':::GEOGRAPHY AS col_177841
							FROM
								with_29359 AS cte_ref_8529
						)
				)
		SELECT
			'tvg':::rand_typ_1 AS col_177844,
			('1994-10-29':::DATE, ARRAY[(-4656):::INT8,(-4371):::INT8,(-19496):::INT8]) AS col_177845,
			cte_ref_8530.col_177843 AS col_177846,
			'tvg':::rand_typ_1 AS col_177847,
			cte_ref_8531.col_177843 AS col_177848,
			'tvg':::rand_typ_1 AS col_177849
		FROM
			with_29360 AS cte_ref_8530, with_29360 AS cte_ref_8531, with_29360 AS cte_ref_8532
		ORDER BY
			cte_ref_8532.col_177842 DESC;
```
<details><summary>Help</summary>
<p>

See: [roachtest README](https://github.com/cockroachdb/cockroach/blob/master/pkg/cmd/roachtest/README.md)

See: [How To Investigate \(internal\)](https://cockroachlabs.atlassian.net/l/c/SSSBr8c7)

</p>
</details>
/cc @cockroachdb/sql-queries
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*sqlsmith/setup=rand-tables/setting=no-ddl.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)
</sub>

### PR DESCRIPTION
**Pull request by msirek**
Backport 1/1 commits from #80212.

/cc @cockroachdb/release

---

Fixes #79943

Previously, HoistProjectFromInnerJoin would explore joins with the right
input projection pulled up to the parent of the join, no matter the type
of relation underneath the projection.

This was inadequate because queries involving many joins may invoke the
ReorderJoins rule many times, which creates many new join expressions
(orders of magnitude greater than the number of joins in the query),
which need to be explored. Each of those may trigger projection pull-up,
adding a new join expression to a memo group, further increasing the
search space. Each of those added join expressions may themselves have a
subtree of joins below them involving projections which may fire the
rule again, leading to an explosion of rule firings and a query which
never completes optimization (hangs).

To address this, this patch alters the conditions required to fire
HoistProjectFromInnerJoin so that when the right input of the join is a
projection, the input to the projection must be a canonical scan or a
select from a canonical scan.

HoistProjectFromInnerJoin, added through #59780, is meant to enable more
lookup joins because converting a projection on the right side of a join
into a canonical scan allows GenerateLookupJoins to fire. Likewise,
other join transformations such as SplitDisjunctionOfJoinTerms may
require either a canonical scan or a select from a canonical scan as
join inputs in order to fire.  Other cases are unlikely to cause any new
join transformations to fire since those rules check for canonical scans
as input, so skipping their exploration will not result in any missed
optimizations.

Release note (bug fix): Prior to this fix, queries with many joins and
projections of multicolumn expressions, e.g. col1 + col2, either
present in the query or within a virtual column definition, could
experience very long optimization times or hangs, where the query is
never sent for execution.

**sql: Add disable_hoist_projection_in_join_limitation session flag**

This commit adds the disable_hoist_projection_in_join_limitation session flag.
    
Release note: none

**opttester: support session settings in opt tests**

This commit adds the set opttest flag which can be used to set
session flags via "set=flagname=value".

Release note: none

Release justification: Low risk fix for lengthy exploration time on complex queries.

### CODE REVIEW

**Review by mgartner — CHANGES_REQUESTED** [review]
We're probably going to want the feature flag in 22.2+ for backward compatibility (and it might be useful in that version too), so can you first make a PR of the second commit onto master, then you can backport the two commits to 22.1 and 21.2.

> Reviewed 9 of 9 files at r1, 5 of 6 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/85871#-:-N97vch9DnZMR6UL2XNQ:bnvg93r)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @msirek and @rytaft)

___
*[`pkg/sql/vars.go` line 2104 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/85871#-N97sc992GFTfafymrP2:-N97sc992GFTfafymrP3:bsvq631) ([raw file](https://github.com/cockroachdb/cockroach/blob/55a604297d32cf620063ecc1013cbbfe1fb9d33a/pkg/sql/vars.go#L2104)):*
> ```Go
> 	},
> 	// CockroachDB extension.
> 	`disable_80212`: {
> ```

I don't think we should start a new precedent of including issue numbers in these session settings. Can we name this something descriptive like `disable_hoist_projection_in_join_limitation`?
___
*[`pkg/sql/logictest/testdata/logic_test/information_schema` line 4719 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/85871#-N97rTJyDozr4RINzemX:-N97rTJzCZM1evzxk7OS:b68v14f) ([raw file](https://github.com/cockroachdb/cockroach/blob/5754453ca8e117cbc66aeef9d103df392249edf5/pkg/sql/logictest/testdata/logic_test/information_schema#L4719)):*
> ```
> default_transaction_use_follower_reads                off
> default_with_oids                                     off
> disable_80212                                         off
> ```

Looks like this ended up in the wrong commit.
___
*[`pkg/sql/logictest/testdata/logic_test/pg_catalog` line 4147 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/85871#-N97rVgM4BLc4zaSG0C8:-N97rVgM4BLc4zaSG0C9:bbznsy8) ([raw file](https://github.com/cockroachdb/cockroach/blob/5754453ca8e117cbc66aeef9d103df392249edf5/pkg/sql/logictest/testdata/logic_test/pg_catalog#L4147)):*
> ```
> default_transaction_use_follower_reads                off                 NULL      NULL        NULL        string
> default_with_oids                                     off                 NULL      NULL        NULL        string
> disable_80212                                         off                 NULL      NULL        NULL        string
> ```

These also look like the belong in the other commit.
___
*[`pkg/sql/logictest/testdata/logic_test/show_source` line 50 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/85871#-N97rYWT--GDTVcEn8G0:-N97rYWT--GDTVcEn8G1:b-nwm6r8) ([raw file](https://github.com/cockroachdb/cockroach/blob/5754453ca8e117cbc66aeef9d103df392249edf5/pkg/sql/logictest/testdata/logic_test/show_source#L50)):*
> ```
> default_transaction_use_follower_reads                off
> default_with_oids                                     off
> disable_80212                                         off
> ```

Move to other commit.
___
*[`pkg/sql/opt/exec/execbuilder/testdata/tpch_vec` line 978 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/85871#-N97uRgN4mkSppVS6gSM:-N97uRgN4mkSppVS6gSN:b-2t1yi0) ([raw file](https://github.com/cockroachdb/cockroach/blob/55a604297d32cf620063ecc1013cbbfe1fb9d33a/pkg/sql/opt/exec/execbuilder/testdata/tpch_vec#L978)):*
> ```
> # projMultFloat64Float64ConstOp should be pulled up above hashAggregator.
> query T
> EXPLAIN (VEC) SELECT s_name, s_address FROM supplier, nation WHERE s_suppkey IN ( SELECT ps_suppkey FROM partsupp WHERE ps_partkey IN ( SELECT p_partkey FROM part WHERE p_name LIKE 'forest%') AND ps_availqty > ( SELECT 0.5 * sum(l_quantity) FROM lineitem WHERE l_partkey = ps_partkey AND l_suppkey = ps_suppkey AND l_shipdate >= DATE '1994-01-01' AND l_shipdate < DATE '1994-01-01' + INTERVAL '1' YEAR)) AND s_nationkey = n_nationkey AND n_name = 'CANADA' ORDER BY s_name
> ```

It's a bit odd to test this optimizer feature flag in a vectorized test. Maybe a better alternative is to test it directly after this test: https://github.com/cockroachdb/cockroach/pull/80212/files#diff-44bcfa2ab084e41d496509be77c589bc68e8e2d7a95baa536f526666a9ab670dR10287-R10308 and add an opttest flag `disable_hoist_projection_in_join_limitation` that sets the session setting.
___
*[`pkg/sql/opt/xform/join_funcs.go` line 1850 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/85871#-N97v8bs0dmJskWbxand:-N97v8bs0dmJskWbxane:bbx6bi8) ([raw file](https://github.com/cockroachdb/cockroach/blob/55a604297d32cf620063ecc1013cbbfe1fb9d33a/pkg/sql/opt/xform/join_funcs.go#L1850)):*
> ```Go
> // for this are if `relation` is a canonical scan or a select from a canonical
> // scan, or the disable_80212 session flag is true.
> func (c *CustomFuncs) HoistOfProjectionAllowed(relation memo.RelExpr) (ok bool) {
> ```

nit: If you rename `HoistOfProjectionAllowed` to `CanHoistProjectInput` then the description becomes less awkward.

**Review by msirek — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/85871)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @mgartner, @msirek, and @rytaft)

___
*[`pkg/sql/opt/exec/execbuilder/testdata/tpch_vec` line 978 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/85871#-N97uRgN4mkSppVS6gSM:-N9853nFES_cQLNCBdFQ:b-9jykh5) ([raw file](https://github.com/cockroachdb/cockroach/blob/55a604297d32cf620063ecc1013cbbfe1fb9d33a/pkg/sql/opt/exec/execbuilder/testdata/tpch_vec#L978)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

It's a bit odd to test this optimizer feature flag in a vectorized test. Maybe a better alternative is to test it directly after this test: https://github.com/cockroachdb/cockroach/pull/80212/files#diff-44bcfa2ab084e41d496509be77c589bc68e8e2d7a95baa536f526666a9ab670dR10287-R10308 and add an opttest flag `disable_hoist_projection_in_join_limitation` that sets the session setting.
</blockquote></details>

OK.  Is there a way to set a session var in a rules test?  I am getting error messages trying to do it.

**Comment by mgartner** [comment]
*[`pkg/sql/opt/exec/execbuilder/testdata/tpch_vec` line 978 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/85871#-N97uRgN4mkSppVS6gSM:-N995NKD0MYuItaQYwbm:bn2xm1p) ([raw file](https://github.com/cockroachdb/cockroach/blob/55a604297d32cf620063ecc1013cbbfe1fb9d33a/pkg/sql/opt/exec/execbuilder/testdata/tpch_vec#L978)):*
<details><summary><i>Previously, msirek (Mark Sirek) wrote…</i></summary><blockquote>

OK.  Is there a way to set a session var in a rules test?  I am getting error messages trying to do it.
</blockquote></details>

You'll have to use an opt test flag to set the session setting. Here's a good example of how to add one: https://github.com/cockroachdb/cockroach/commit/f983edb2276b029f6129e10855a6cc146a2f70cf#diff-4209b5d6c01f4aa8ff55822acca76e8baf6ac1d6b457a5d916269c698ed4b736

**Review by msirek — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/85871)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @mgartner, @msirek, and @rytaft)

___
*[`pkg/sql/opt/exec/execbuilder/testdata/tpch_vec` line 978 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/85871#-N97uRgN4mkSppVS6gSM:-N996N5N9jUHBdNE7bqi:b4t2bus) ([raw file](https://github.com/cockroachdb/cockroach/blob/55a604297d32cf620063ecc1013cbbfe1fb9d33a/pkg/sql/opt/exec/execbuilder/testdata/tpch_vec#L978)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

You'll have to use an opt test flag to set the session setting. Here's a good example of how to add one: https://github.com/cockroachdb/cockroach/commit/f983edb2276b029f6129e10855a6cc146a2f70cf#diff-4209b5d6c01f4aa8ff55822acca76e8baf6ac1d6b457a5d916269c698ed4b736
</blockquote></details>

Thanks.. I think I figured it out already.. am about to open a PR for it.

**Review by msirek — COMMENTED** [review]
Done

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/85871#-:-N99gi6P-xONPKuMIzye:bb6un1j)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @mgartner and @rytaft)

___
*[`pkg/sql/vars.go` line 2104 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/85871#-N97sc992GFTfafymrP2:-N99gPQj38ClO5V_KWm3:bb6un1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/55a604297d32cf620063ecc1013cbbfe1fb9d33a/pkg/sql/vars.go#L2104)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

I don't think we should start a new precedent of including issue numbers in these session settings. Can we name this something descriptive like `disable_hoist_projection_in_join_limitation`?
</blockquote></details>

Done
___
*[`pkg/sql/logictest/testdata/logic_test/information_schema` line 4719 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/85871#-N97rTJyDozr4RINzemX:-N99gS15CQkcFW2HqVtZ:b-7ql1td) ([raw file](https://github.com/cockroachdb/cockroach/blob/5754453ca8e117cbc66aeef9d103df392249edf5/pkg/sql/logictest/testdata/logic_test/information_schema#L4719)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

Looks like this ended up in the wrong commit.
</blockquote></details>

fixed
___
*[`pkg/sql/logictest/testdata/logic_test/pg_catalog` line 4147 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/85871#-N97rVgM4BLc4zaSG0C8:-N99gTaX-wrjSKM7oQ1N:b-7ql1td) ([raw file](https://github.com/cockroachdb/cockroach/blob/5754453ca8e117cbc66aeef9d103df392249edf5/pkg/sql/logictest/testdata/logic_test/pg_catalog#L4147)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

These also look like the belong in the other commit.
</blockquote></details>

fixed
___
*[`pkg/sql/logictest/testdata/logic_test/show_source` line 50 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/85871#-N97rYWT--GDTVcEn8G0:-N99gY8w5yZrYOANNXsV:b-7ql1td) ([raw file](https://github.com/cockroachdb/cockroach/blob/5754453ca8e117cbc66aeef9d103df392249edf5/pkg/sql/logictest/testdata/logic_test/show_source#L50)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

Move to other commit.
</blockquote></details>

fixed
___
*[`pkg/sql/opt/xform/join_funcs.go` line 1850 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/85871#-N97v8bs0dmJskWbxand:-N99gb26BCm0e0FdHp5w:bb7f2mf) ([raw file](https://github.com/cockroachdb/cockroach/blob/55a604297d32cf620063ecc1013cbbfe1fb9d33a/pkg/sql/opt/xform/join_funcs.go#L1850)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

nit: If you rename `HoistOfProjectionAllowed` to `CanHoistProjectInput` then the description becomes less awkward.
</blockquote></details>

done

**Review by msirek — COMMENTED** [review]
@mgartner This should be in sync with the 22.2 PR now (minus removal of old opttest flags dealing with session settings).  Please let me know if you have any more comments.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/85871#-:-NABaMgy-DKjLHveezVJ:bk1gygj)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @mgartner and @rytaft)

**Review by mgartner — APPROVED** [review]
Very nice - thanks for backporting!

File: pkg/sql/opt/xform/join_funcs.go [hunk 1]
```diff
@@ -1818,3 +1818,40 @@ func (c *CustomFuncs) splitValues(
 	}
 	return localVals, remoteVals
 }
+
+// getfilteredCanonicalScan looks at a *ScanExpr or *SelectExpr "relation" and
+// returns the input *ScanExpr and FiltersExpr, along with ok=true, if the Scan
+// is a canonical scan. If "relation" is a different type, or if it's a
+// *SelectExpr with an Input other than a *ScanExpr, ok=false is returned. Scans
+// or Selects with no filters may return filters as nil.
+func (c *CustomFuncs) getfilteredCanonicalScan(
```
Comment (mgartner) [inline pkg/sql/opt/xform/join_funcs.go:1827]: Just noticed it should be `getFiltered...` not `getfiltered...`. No need to change this for the backport since that's how it's spelled on master, but you can fix on master in a future PR if you'd like.

Comment (msirek) [reply pkg/sql/opt/xform/join_funcs.go:1827]: > Just noticed it should be `getFiltered...` not `getfiltered...`. No need to change this for the backport since that's how it's spelled on master, but you can fix on master in a future PR if you'd like.

OK, thanks.

**Review by msirek — COMMENTED** [review]
TFTR!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/85871#-:-NAMGRb_-yly_FIvQaYm:b-814g8k)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @mgartner and @rytaft)
