### PR TITLE
catalog/lease: update locked timestamps when updates are received

### LINKED ISSUE #153826: sql/catalog/lease: TestLeaseManagerLockedTimestampBasic failed
sql/catalog/lease.TestLeaseManagerLockedTimestampBasic [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Ci_TestsAwsLinuxArm64_UnitTests/20495911?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Ci_TestsAwsLinuxArm64_UnitTests/20495911?buildTab=artifacts#/) on master @ [3b1e9fa063036c453ff4ee103c633851186946cf](https://github.com/cockroachdb/cockroach/commits/3b1e9fa063036c453ff4ee103c633851186946cf):

```
created by github.com/cockroachdb/pebble/internal/genericcache.(*shard[...]).Init in goroutine 16504
	external/com_github_cockroachdb_pebble/internal/genericcache/shard.go:54 +0x17c

goroutine 17438 [select]:
github.com/cockroachdb/cockroach/pkg/util/admission.(*WorkQueue).startClosingEpochs.func1()
	pkg/util/admission/work_queue.go:479 +0x140
created by github.com/cockroachdb/cockroach/pkg/util/admission.(*WorkQueue).startClosingEpochs in goroutine 16504
	pkg/util/admission/work_queue.go:450 +0x5c

goroutine 16648 [chan receive, 14 minutes]:
github.com/cockroachdb/pebble/internal/genericcache.(*shard[...]).releaseLoop(0x4002ff1d60)
	external/com_github_cockroachdb_pebble/internal/genericcache/shard.go:61 +0x6c
created by github.com/cockroachdb/pebble/internal/genericcache.(*shard[...]).Init in goroutine 16504
	external/com_github_cockroachdb_pebble/internal/genericcache/shard.go:54 +0x17c

goroutine 16663 [chan receive, 14 minutes]:
github.com/cockroachdb/pebble/internal/genericcache.(*shard[...]).releaseLoop(0x40025a2fb0)
	external/com_github_cockroachdb_pebble/internal/genericcache/shard.go:61 +0x6c
created by github.com/cockroachdb/pebble/internal/genericcache.(*shard[...]).Init in goroutine 16504
	external/com_github_cockroachdb_pebble/internal/genericcache/shard.go:54 +0x17c

goroutine 16668 [select]:
github.com/cockroachdb/pebble.(*ConcurrencyLimitScheduler).periodicGranter(0x4003c30fc0)
	external/com_github_cockroachdb_pebble/compaction_scheduler.go:414 +0x9c
created by github.com/cockroachdb/pebble.(*ConcurrencyLimitScheduler).Register in goroutine 16504
	external/com_github_cockroachdb_pebble/compaction_scheduler.go:305 +0x98

goroutine 16666 [chan receive, 14 minutes]:
github.com/cockroachdb/pebble/internal/genericcache.(*shard[...]).releaseLoop(0x40024337b0)
	external/com_github_cockroachdb_pebble/internal/genericcache/shard.go:61 +0x6c
created by github.com/cockroachdb/pebble/internal/genericcache.(*shard[...]).Init in goroutine 16504
	external/com_github_cockroachdb_pebble/internal/genericcache/shard.go:54 +0x17c

goroutine 16649 [chan receive, 14 minutes]:
github.com/cockroachdb/pebble/internal/genericcache.(*shard[...]).releaseLoop(0x4002ff1d60)
	external/com_github_cockroachdb_pebble/internal/genericcache/shard.go:61 +0x6c
created by github.com/cockroachdb/pebble/internal/genericcache.(*shard[...]).Init in goroutine 16504
	external/com_github_cockroachdb_pebble/internal/genericcache/shard.go:54 +0x17c

goroutine 16593 [select]:
github.com/cockroachdb/pebble.(*ConcurrencyLimitScheduler).periodicGranter(0x40023864e0)
	external/com_github_cockroachdb_pebble/compaction_scheduler.go:414 +0x9c
created by github.com/cockroachdb/pebble.(*ConcurrencyLimitScheduler).Register in goroutine 16504
	external/com_github_cockroachdb_pebble/compaction_scheduler.go:305 +0x98

goroutine 17167 [select]:
github.com/cockroachdb/pebble/vfs.(*diskHealthCheckingFile).startTicker.func1()
	external/com_github_cockroachdb_pebble/vfs/disk_health.go:254 +0x98
created by github.com/cockroachdb/pebble/vfs.(*diskHealthCheckingFile).startTicker in goroutine 16504
	external/com_github_cockroachdb_pebble/vfs/disk_health.go:249 +0x64
```
<details><summary>Help</summary>
<p>

See also: [How To Investigate a Go Test Failure \(internal\)](https://cockroachlabs.atlassian.net/l/c/HgfXfJgM)
</p>
</details>
/cc @cockroachdb/sql-foundations
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*TestLeaseManagerLockedTimestampBasic.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/bazci/githubpost/issues)

</sub>

Jira issue: CRDB-54615

### LINKED ISSUE #154075: sql/catalog/lease: TestLeaseManagerLockedTimestampBasic failed
sql/catalog/lease.TestLeaseManagerLockedTimestampBasic [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Ci_TestsAwsLinuxArm64_UnitTests/20515344?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Ci_TestsAwsLinuxArm64_UnitTests/20515344?buildTab=artifacts#/) on release-25.4 @ [a701dbe5b831d9f3a2164b44e8cf433e45c92d1c](https://github.com/cockroachdb/cockroach/commits/a701dbe5b831d9f3a2164b44e8cf433e45c92d1c):

```
created by github.com/cockroachdb/cockroach/pkg/util/admission.(*WorkQueue).startClosingEpochs in goroutine 12832
	pkg/util/admission/work_queue.go:450 +0x5c

goroutine 13759 [select]:
github.com/cockroachdb/cockroach/pkg/util/admission.initWorkQueue.func2()
	pkg/util/admission/work_queue.go:402 +0x7c
created by github.com/cockroachdb/cockroach/pkg/util/admission.initWorkQueue in goroutine 12832
	pkg/util/admission/work_queue.go:399 +0x2ec

goroutine 12983 [chan receive, 14 minutes]:
github.com/cockroachdb/pebble/internal/genericcache.(*shard[...]).releaseLoop(0x400267cf90)
	external/com_github_cockroachdb_pebble/internal/genericcache/shard.go:61 +0x6c
created by github.com/cockroachdb/pebble/internal/genericcache.(*shard[...]).Init in goroutine 12832
	external/com_github_cockroachdb_pebble/internal/genericcache/shard.go:54 +0x17c

goroutine 12982 [chan receive, 14 minutes]:
github.com/cockroachdb/pebble/internal/genericcache.(*shard[...]).releaseLoop(0x40044bc500)
	external/com_github_cockroachdb_pebble/internal/genericcache/shard.go:61 +0x6c
created by github.com/cockroachdb/pebble/internal/genericcache.(*shard[...]).Init in goroutine 12832
	external/com_github_cockroachdb_pebble/internal/genericcache/shard.go:54 +0x17c

goroutine 12977 [select]:
github.com/cockroachdb/pebble/vfs.(*diskHealthCheckingFile).startTicker.func1()
	external/com_github_cockroachdb_pebble/vfs/disk_health.go:254 +0x98
created by github.com/cockroachdb/pebble/vfs.(*diskHealthCheckingFile).startTicker in goroutine 12832
	external/com_github_cockroachdb_pebble/vfs/disk_health.go:249 +0x64

goroutine 13006 [chan receive, 14 minutes]:
github.com/cockroachdb/pebble/internal/genericcache.(*shard[...]).releaseLoop(0x0)
	external/com_github_cockroachdb_pebble/internal/genericcache/shard.go:61 +0x6c
created by github.com/cockroachdb/pebble/internal/genericcache.(*shard[...]).Init in goroutine 12832
	external/com_github_cockroachdb_pebble/internal/genericcache/shard.go:54 +0x17c

goroutine 12969 [select]:
github.com/cockroachdb/cockroach/pkg/util/admission.(*WorkQueue).startClosingEpochs.func1()
	pkg/util/admission/work_queue.go:479 +0x140
created by github.com/cockroachdb/cockroach/pkg/util/admission.(*WorkQueue).startClosingEpochs in goroutine 12832
	pkg/util/admission/work_queue.go:450 +0x5c

goroutine 12967 [select]:
github.com/cockroachdb/cockroach/pkg/util/admission.(*WorkQueue).startClosingEpochs.func1()
	pkg/util/admission/work_queue.go:479 +0x140
created by github.com/cockroachdb/cockroach/pkg/util/admission.(*WorkQueue).startClosingEpochs in goroutine 12832
	pkg/util/admission/work_queue.go:450 +0x5c

goroutine 12976 [select]:
github.com/cockroachdb/pebble/vfs.(*diskHealthCheckingFS).startTickerLocked.func1()
	external/com_github_cockroachdb_pebble/vfs/disk_health.go:677 +0xb8
created by github.com/cockroachdb/pebble/vfs.(*diskHealthCheckingFS).startTickerLocked in goroutine 12832
	external/com_github_cockroachdb_pebble/vfs/disk_health.go:666 +0x7c
```
<details><summary>Help</summary>
<p>

See also: [How To Investigate a Go Test Failure \(internal\)](https://cockroachlabs.atlassian.net/l/c/HgfXfJgM)
</p>
</details>
<details><summary>Same failure on other branches</summary>
<p>

- #153826 sql/catalog/lease: TestLeaseManagerLockedTimestampBasic failed [C-test-failure O-robot P-2 T-sql-foundations branch-master]
</p>
</details>
/cc @cockroachdb/sql-foundations
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*TestLeaseManagerLockedTimestampBasic.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/bazci/githubpost/issues)

</sub>

Jira issue: CRDB-54801

### PR DESCRIPTION
**Pull request by fqazi**
Previously, the lease manager would increase its locked read time stamp was when a check point occurred on the range feed. This was not adequate because this could cause schema changes could be slowed down if the old version of descriptors was held. While the current design does not intentionally reserve, previous versions, a later update will start holding old versions intentionally to serve queries. To address this, this patch has schema changes write the list of descriptors modified to a special key `/Table/Descriptors/2/<First ID in Schema Change`, which will be used by the lease manager range feed to to update timestamps. Additionally, this patch also deflakes and fixes
`TestLeaseManagerLockedTimestampBasic`, which was not setup correctly.

Informs: #153618
Fixes: #153826
Fixes: https://github.com/cockroachdb/cockroach/issues/154075

Release note: None

### CODE REVIEW

**Review by rafiss — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/153961)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @aerfrei, @alyshanjahani-crl, @kev-cao, and @mgartner)

___
*[`pkg/keys/constants.go` line 432 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/153961#-O_x4tOT272pjiASc4fg:-O_x4tOT272pjiASc4fh:bvk97ke) ([raw file](https://github.com/cockroachdb/cockroach/blob/bcb3498d253ec60cccf65d4177252d6bacde301f/pkg/keys/constants.go#L432)):*
> ```Go
> 	DescriptorTableDescriptorColID           = 2
> 	DescriptorTableDescriptorColFamID        = 2
> 	DescriptorTableDescriptorUpdateIndexID   = 2
> ```

this one is a little special since it's not a real index, so maybe deserves its own comment
___
*[`pkg/spanconfig/spanconfigsqlwatcher/sqlwatcher.go` line 202 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/153961#-O_x53Dp6nwzMbzbyTSU:-O_x53Dp6nwzMbzbyTSV:b-azwzh5) ([raw file](https://github.com/cockroachdb/cockroach/blob/bcb3498d253ec60cccf65d4177252d6bacde301f/pkg/spanconfig/spanconfigsqlwatcher/sqlwatcher.go#L202)):*
> ```Go
> 		if isUpdateKey, err := s.codec.DecodeDescUpdateKey(ev.Key); isUpdateKey || err != nil {
> 			if err != nil {
> 				log.Dev.Errorf(ctx, "failed to decode descriptor update key: %v", err)
> ```

nit: let's make it a warning
___
*[`pkg/sql/catalog/descs/collection.go` line 388 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/153961#-O_x5ViI4RLe4MQnSmg9:-O_x5ViN4uW2e5jCNsDi:bdan27c) ([raw file](https://github.com/cockroachdb/cockroach/blob/bcb3498d253ec60cccf65d4177252d6bacde301f/pkg/sql/catalog/descs/collection.go#L388)):*
> ```Go
> // know which descriptors were updated by this transaction. This allows it to
> // transactionally make these descriptors available.
> func (tc *Collection) EmitDescriptorUpdatesKey(ctx context.Context, txn *kv.Txn) error {
> ```

just a sanity check for my understanding -- do we need the version bumps for `system.users`, `system.role_options`, etc tables to be covered here? those have some special logic
___
*[`pkg/sql/catalog/descs/collection.go` line 391 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/153961#-O_xIfhm90x48XLgJODV:-O_xIfhm90x48XLgJODW:brpk17u) ([raw file](https://github.com/cockroachdb/cockroach/blob/bcb3498d253ec60cccf65d4177252d6bacde301f/pkg/sql/catalog/descs/collection.go#L391)):*
> ```Go
> 	// This key is only emitted for 25.4 and above. Additionally, PCR
> 	// reader catalog can update a large number of descriptors in a transaction,
> 	// and are exempt from this logic.
> ```

should we also have a cluster setting here, so we can backport to 25.4 and keep it off by default?

or is there a different setting that's already gating this?
___
*[`pkg/sql/catalog/descpb/structured.proto` line 1949 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/153961#-O_x5M0IEeZnCHM5_E1H:-O_x5M0IEeZnCHM5_E1I:b3gouit) ([raw file](https://github.com/cockroachdb/cockroach/blob/bcb3498d253ec60cccf65d4177252d6bacde301f/pkg/sql/catalog/descpb/structured.proto#L1949)):*
> ```proto
> 
>   repeated uint32 descriptor_ids = 1 [(gogoproto.nullable) = false, (gogoproto.customname) = "DescriptorIDs", (gogoproto.casttype) = "ID"];
>   repeated uint32 descriptor_versions = 2  [(gogoproto.nullable) = false, (gogoproto.casttype) = "DescriptorVersion"];
> ```

nit: the customized name should be `DescriptorVersions`
___
*[`pkg/sql/catalog/lease/lease.go` line 1336 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/153961#-O_xEM4vCRkpwbO0qTBc:-O_xEM4vCRkpwbO0qTBd:b-gzmaav) ([raw file](https://github.com/cockroachdb/cockroach/blob/bcb3498d253ec60cccf65d4177252d6bacde301f/pkg/sql/catalog/lease/lease.go#L1336)):*
> ```Go
> )
> 
> type descriptorTxnUpdate struct {
> ```

nit: let's add a comment to say what this represents
___
*[`pkg/sql/catalog/lease/lease.go` line 1340 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/153961#-O_xEENu24pLu0sLdfIe:-O_xEENu24pLu0sLdfIf:b-hbj1tg) ([raw file](https://github.com/cockroachdb/cockroach/blob/bcb3498d253ec60cccf65d4177252d6bacde301f/pkg/sql/catalog/lease/lease.go#L1340)):*
> ```Go
> 	timestamp hlc.Timestamp
> 	key       roachpb.Key
> 	mu        syncutil.Mutex
> ```

nit: can we put the fields that need to be protected by the mutex inside of an inner struct? e.g.

```
type descriptorTxnUpdate struct {
  mu struct {
    syncutil.Mutex
    // other fields
  }
}
```
___
*[`pkg/sql/catalog/lease/lease.go` line 1980 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/153961#-O_xG74CEzpnGEbZMDF8:-O_xG74CEzpnGEbZMDF9:b-kgmzzw) ([raw file](https://github.com/cockroachdb/cockroach/blob/bcb3498d253ec60cccf65d4177252d6bacde301f/pkg/sql/catalog/lease/lease.go#L1980)):*
> ```Go
> }
> 
> // hasDescUpdateBeenApplied checks if a descriptor update has been applied.
> ```

nit: upate this comment to explain what `remaining` means.
___
*[`pkg/sql/catalog/lease/lease.go` line 1990 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/153961#-O_xG1ntCQCOGTY6D7Vl:-O_xG1nuBylwGEXoThgU:b-1r5rbp) ([raw file](https://github.com/cockroachdb/cockroach/blob/bcb3498d253ec60cccf65d4177252d6bacde301f/pkg/sql/catalog/lease/lease.go#L1990)):*
> ```Go
> 		if descVersionState == nil || descVersionState.GetVersion() < requiredVersion {
> 			// If a descriptor is missing, we still consider it as applied, since
> 			// we will lease a newer version.
> ```

i don't follow -- if we consider it as applied, why do we also add it to `remaining`?
___
*[`pkg/sql/catalog/lease/lease.go` line 1999 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/153961#-O_xGAn34FZwAnmoenhl:-O_xGAn34FZwAnmoenhm:b-z8gpmu) ([raw file](https://github.com/cockroachdb/cockroach/blob/bcb3498d253ec60cccf65d4177252d6bacde301f/pkg/sql/catalog/lease/lease.go#L1999)):*
> ```Go
> }
> 
> // getDescriptorTxnUpdateEntry
> ```

nit: finish the comment -- this function returns the transaction update record for a given timestamp.
___
*[`pkg/sql/catalog/lease/lease.go` line 2004 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/153961#-O_xGgYX8WFduDgoCoZM:-O_xGgYX8WFduDgoCoZN:bsv53ly) ([raw file](https://github.com/cockroachdb/cockroach/blob/bcb3498d253ec60cccf65d4177252d6bacde301f/pkg/sql/catalog/lease/lease.go#L2004)):*
> ```Go
> 	defer m.mu.Unlock()
> 	key := &descriptorTxnUpdate{timestamp: timestamp}
> 	entry, hasTS := m.mu.descriptorTxnUpdatesToProcess.Get(key)
> ```

is Get just a point lookup here? wouldn't we need to get the `floor`?
___
*[`pkg/sql/catalog/lease/lease.go` line 2035 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/153961#-O_xH4w70F2Pgh0HzIVQ:-O_xH4w70F2Pgh0HzIVR:b-eojz2h) ([raw file](https://github.com/cockroachdb/cockroach/blob/bcb3498d253ec60cccf65d4177252d6bacde301f/pkg/sql/catalog/lease/lease.go#L2035)):*
> ```Go
> 				return false
> 			}
> 			// Otherwise, let's remove this descriptor.
> ```

i don't think order matters for this list, right? we can instead swap with the element at the end and reduce the size by one
___
*[`pkg/sql/catalog/lease/lease.go` line 2064 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/153961#-O_xHNS5BUb_CB0pnRFN:-O_xHNS5BUb_CB0pnRFO:b-7s79b5) ([raw file](https://github.com/cockroachdb/cockroach/blob/bcb3498d253ec60cccf65d4177252d6bacde301f/pkg/sql/catalog/lease/lease.go#L2064)):*
> ```Go
> 			break
> 		}
> 		removeEntry := func() bool {
> ```

nit: let's call it `shouldRemoveEntry`
___
*[`pkg/sql/catalog/lease/lease.go` line 2297 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/153961#-O_xHc9X595VqPhfsSNu:-O_xHc9X595VqPhfsSNv:bg6zw4a) ([raw file](https://github.com/cockroachdb/cockroach/blob/bcb3498d253ec60cccf65d4177252d6bacde301f/pkg/sql/catalog/lease/lease.go#L2297)):*
> ```Go
> 		} else if isUpdateKey, err := m.Codec().DecodeDescUpdateKey(ev.Key); err != nil || isUpdateKey {
> 			if err != nil {
> 				log.Dev.Infof(ctx, "unable to decode update metadata key %v", ev.Key)
> ```

nit: let's make this a warning
___
*[`pkg/sql/catalog/lease/lease.go` line 2308 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/153961#-O_xHjrwAhYXGAyqP--8:-O_xHjrwAhYXGAyqP--9:bg6zw4a) ([raw file](https://github.com/cockroachdb/cockroach/blob/bcb3498d253ec60cccf65d4177252d6bacde301f/pkg/sql/catalog/lease/lease.go#L2308)):*
> ```Go
> 			err := ev.Value.GetProto(&descUpdates)
> 			if err != nil {
> 				log.Dev.Infof(ctx, "unable to decode descriptor update value %v", err)
> ```

nit: let's make this a warning
___
*[`pkg/sql/catalog/lease/lease.go` line 2312 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/153961#-O_xHqeA6E-zgxdmDAPb:-O_xHqeA6E-zgxdmDAPc:b6jw2i6) ([raw file](https://github.com/cockroachdb/cockroach/blob/bcb3498d253ec60cccf65d4177252d6bacde301f/pkg/sql/catalog/lease/lease.go#L2312)):*
> ```Go
> 			}
> 			select {
> 			case <-ctx.Done():
> ```

do we also need to wait on `s.ShouldQuiesce`?
___
*[`pkg/sql/catalog/lease/lease.go` line 2313 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/153961#-O_xHydPC02cFNrNh8CR:-O_xHydPC02cFNrNh8CS:bn3a9bh) ([raw file](https://github.com/cockroachdb/cockroach/blob/bcb3498d253ec60cccf65d4177252d6bacde301f/pkg/sql/catalog/lease/lease.go#L2313)):*
> ```Go
> 			select {
> 			case <-ctx.Done():
> 			case m.descMetaDataUpdateCh <- &descriptorTxnUpdate{
> ```

nit: make a separate variable for the `descriptorTxnUpdate` -- it's a bit hard to read with the `:` at the end of the inlined struct
___
*[`pkg/sql/catalog/lease/lease.go` line 2321 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/153961#-O_xI7BGCNbi1vGSzhv0:-O_xI7BH00y-0hiKw3Hg:b4drbud) ([raw file](https://github.com/cockroachdb/cockroach/blob/bcb3498d253ec60cccf65d4177252d6bacde301f/pkg/sql/catalog/lease/lease.go#L2321)):*
> ```Go
> 			return
> 		}
> 		// Check if its the special descrip
> ```

nit: incomplete comment -- but also, looks like there's no special code here.
___
*[`pkg/sql/catalog/lease/lease.go` line 2629 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/153961#-O_xILVIByz-p-ldTWUR:-O_xILVIByz-p-ldTWUS:b-6ph1rc) ([raw file](https://github.com/cockroachdb/cockroach/blob/bcb3498d253ec60cccf65d4177252d6bacde301f/pkg/sql/catalog/lease/lease.go#L2629)):*
> ```Go
> 	})
> 	if err != nil {
> 		log.Dev.Infof(ctx, "unable to delete update keys from storage %s", err)
> ```

nit: make it a warning, and use `%v`

also to make it more clear, say "unable to delete descriptor update keys from storage: %v`
___
*[`pkg/backup/backup_test.go` line 6662 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/153961#-O_xIVeaAF76n2YdgPLi:-O_xIVeaAF76n2YdgPLj:bsb8apv) ([raw file](https://github.com/cockroachdb/cockroach/blob/9ba78935de47e8ebe142f4291e7a3cd80cab141a/pkg/backup/backup_test.go#L6662)):*
> ```Go
> 	expected = nil
> 	for _, resume := range []exportResumePoint{
> 		{mkSpan(id2, "/Tenant/10/Table/3", "/Tenant/10/Table/4"), withoutTS},
> ```

why did this get removed? should we just make a narrower range instead?

**Review by fqazi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/153961)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @aerfrei, @alyshanjahani-crl, @kev-cao, @mgartner, and @rafiss)

___
*[`pkg/keys/constants.go` line 432 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/153961#-O_x4tOT272pjiASc4fg:-OaKsE3-5pt8tXEHQEX4:brle7zn) ([raw file](https://github.com/cockroachdb/cockroach/blob/bcb3498d253ec60cccf65d4177252d6bacde301f/pkg/keys/constants.go#L432)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

this one is a little special since it's not a real index, so maybe deserves its own comment
</blockquote></details>

Done.

Added the comment:
```
// DescriptorTableDescriptorUpdateIndexID is not a real index. It is a special
// ID used to construct index entries that inform the lease subsystem of  
// descriptor updates within a transaction. The value for such an entry is a  
// descpb.DescriptorUpdates message.
```
___
*[`pkg/sql/catalog/descs/collection.go` line 388 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/153961#-O_x5ViI4RLe4MQnSmg9:-OaL6BXPAUCdMkLiGwhT:bbs4m1a) ([raw file](https://github.com/cockroachdb/cockroach/blob/bcb3498d253ec60cccf65d4177252d6bacde301f/pkg/sql/catalog/descs/collection.go#L388)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

just a sanity check for my understanding -- do we need the version bumps for `system.users`, `system.role_options`, etc tables to be covered here? those have some special logic
</blockquote></details>

Those will be in the uncommitted set and get the same behavior here. There is a seperate list that excludes changes the version behavior.
___
*[`pkg/sql/catalog/descs/collection.go` line 391 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/153961#-O_xIfhm90x48XLgJODV:-OaKu6X8CNw0Gkuve_SE:bq0xyou) ([raw file](https://github.com/cockroachdb/cockroach/blob/bcb3498d253ec60cccf65d4177252d6bacde301f/pkg/sql/catalog/descs/collection.go#L391)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

should we also have a cluster setting here, so we can backport to 25.4 and keep it off by default?

or is there a different setting that's already gating this?
</blockquote></details>

Done.


There should have been a check against: `lease.LockedLeaseTimestamp.Get(&tc.settings.SV)` here.
___
*[`pkg/sql/catalog/lease/lease.go` line 1336 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/153961#-O_xEM4vCRkpwbO0qTBc:-OaLOiEF1lBmeMOvUKZC:bbpvma5) ([raw file](https://github.com/cockroachdb/cockroach/blob/bcb3498d253ec60cccf65d4177252d6bacde301f/pkg/sql/catalog/lease/lease.go#L1336)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

nit: let's add a comment to say what this represents
</blockquote></details>

Added the comment:

// descriptorTxnUpdate tracks updates to a set of descriptors in the// system.descriptors by a transaction, that should be made available  
// atomically.
___
*[`pkg/sql/catalog/lease/lease.go` line 1340 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/153961#-O_xEENu24pLu0sLdfIe:-OaKv6i19BuMxistFvIv:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/bcb3498d253ec60cccf65d4177252d6bacde301f/pkg/sql/catalog/lease/lease.go#L1340)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

nit: can we put the fields that need to be protected by the mutex inside of an inner struct? e.g.

```
type descriptorTxnUpdate struct {
  mu struct {
    syncutil.Mutex
    // other fields
  }
}
```
</blockquote></details>

Done.
___
*[`pkg/sql/catalog/lease/lease.go` line 1980 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/153961#-O_xG74CEzpnGEbZMDF8:-OaKyd4w32Ay8dpdWC-4:b-46dhfp) ([raw file](https://github.com/cockroachdb/cockroach/blob/bcb3498d253ec60cccf65d4177252d6bacde301f/pkg/sql/catalog/lease/lease.go#L1980)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

nit: upate this comment to explain what `remaining` means.
</blockquote></details>

// hasDescUpdateBeenApplied checks if all versions of a descriptor update are// present. If not, it returns a new descpb.DescriptorUpdates containing the// versions that are still missing.
___
*[`pkg/sql/catalog/lease/lease.go` line 1990 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/153961#-O_xG1ntCQCOGTY6D7Vl:-OaKywVj5XkVmQavrNZ6:b-3254uk) ([raw file](https://github.com/cockroachdb/cockroach/blob/bcb3498d253ec60cccf65d4177252d6bacde301f/pkg/sql/catalog/lease/lease.go#L1990)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

i don't follow -- if we consider it as applied, why do we also add it to `remaining`?
</blockquote></details>

Done.

Good point, yes it should be safe to remove.
___
*[`pkg/sql/catalog/lease/lease.go` line 1999 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/153961#-O_xGAn34FZwAnmoenhl:-OaKz63TCVswkB-gbQmK:b-p2cfyi) ([raw file](https://github.com/cockroachdb/cockroach/blob/bcb3498d253ec60cccf65d4177252d6bacde301f/pkg/sql/catalog/lease/lease.go#L1999)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

nit: finish the comment -- this function returns the transaction update record for a given timestamp.
</blockquote></details>

Done.

// getDescriptorTxnUpdateEntry returns the descriptorTxnUpdate entry for the given timestamp,// if there are any pending updates.
___
*[`pkg/sql/catalog/lease/lease.go` line 2004 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/153961#-O_xGgYX8WFduDgoCoZM:-OaKzDQdA0UuBCTZqupF:b173f6a) ([raw file](https://github.com/cockroachdb/cockroach/blob/bcb3498d253ec60cccf65d4177252d6bacde301f/pkg/sql/catalog/lease/lease.go#L2004)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

is Get just a point lookup here? wouldn't we need to get the `floor`?
</blockquote></details>

Yes, it's just a point look up. The timestamp from the descriptor will end up matching the timestamp for the special update key.
___
*[`pkg/sql/catalog/lease/lease.go` line 2035 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/153961#-O_xH4w70F2Pgh0HzIVQ:-OaL-FRiCt7zNaLFmua7:bqmkk4l) ([raw file](https://github.com/cockroachdb/cockroach/blob/bcb3498d253ec60cccf65d4177252d6bacde301f/pkg/sql/catalog/lease/lease.go#L2035)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

i don't think order matters for this list, right? we can instead swap with the element at the end and reduce the size by one
</blockquote></details>

Done.

Good point, that would reduce allocations too.
___
*[`pkg/sql/catalog/lease/lease.go` line 2312 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/153961#-O_xHqeA6E-zgxdmDAPb:-OaL06V22m8G3Jb8a1Jw:b-6glipj) ([raw file](https://github.com/cockroachdb/cockroach/blob/bcb3498d253ec60cccf65d4177252d6bacde301f/pkg/sql/catalog/lease/lease.go#L2312)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

do we also need to wait on `s.ShouldQuiesce`?
</blockquote></details>

Done.

Probably safer to wait for that too
___
*[`pkg/sql/catalog/lease/lease.go` line 2321 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/153961#-O_xI7BGCNbi1vGSzhv0:-OaL0P5lAoTfFg5P1ZPB:bk3wf62) ([raw file](https://github.com/cockroachdb/cockroach/blob/bcb3498d253ec60cccf65d4177252d6bacde301f/pkg/sql/catalog/lease/lease.go#L2321)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

nit: incomplete comment -- but also, looks like there's no special code here.
</blockquote></details>

Done.

Should have been above:
```
		// Check first if it is the special descriptor metadata key used to track
		// descriptors modified by transactions.
```
___
*[`pkg/backup/backup_test.go` line 6662 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/153961#-O_xIVeaAF76n2YdgPLi:-OaL2K7Z9-1xiT7XhzPe:bkbrey9) ([raw file](https://github.com/cockroachdb/cockroach/blob/9ba78935de47e8ebe142f4291e7a3cd80cab141a/pkg/backup/backup_test.go#L6662)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

why did this get removed? should we just make a narrower range instead?
</blockquote></details>

There is explicit logic in this test to exclude export requests that look like leasing. So, because we only get the primary index on the descriptor table, that excludes it.

```
// Check if export request is from a lease for a descriptor to avoid picking
// up on wrong export requests
func isLeasingExportRequest(r *kvpb.ExportRequest) bool {
	_, tenantID, _ := keys.DecodeTenantPrefix(r.Key)
	codec := keys.MakeSQLCodec(tenantID)
	return bytes.HasPrefix(r.Key, codec.DescMetadataPrefix()) &&
		r.EndKey.Equal(r.Key.PrefixEnd())
}
```

**Comment by fqazi** [comment]
@rafiss RFAL

**Review by rafiss — APPROVED** [review]
nice work!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/153961#-:-OazTit3DL_cIoLwbvzM:b-j4xmku)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @aerfrei, @alyshanjahani-crl, @kev-cao, and @mgartner)

___
*[`pkg/sql/catalog/lease/lease.go` line 2042 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/153961#-OazTUvE4Vcq1ZySwQJm:-OazTUvF8-T0O2OglnLM:b3d6j0a) ([raw file](https://github.com/cockroachdb/cockroach/blob/809fa641fbcac961f2addb26bb8a6311d140ddf5/pkg/sql/catalog/lease/lease.go#L2042)):*
> ```Go
> 			// Otherwise, let's move this version to the end first.
> 			if idx != len(entry.mu.DescriptorIDs)-1 {
> 				entry.mu.DescriptorIDs[idx], entry.mu.DescriptorIDs[len(entry.mu.DescriptorIDs)-1] =
> ```

nit: this would be much more readable with a variable such as:
```
endIdx := len(entry.mu.DescriptorIDs)-1
```

File: pkg/sql/vecindex/manager_test.go [hunk 1]
```diff
@@ -117,11 +117,6 @@ func TestVectorManager(t *testing.T) {
 	}).BuildCreatedMutable()
 
 	err := internalDB.DescsTxn(ctx, func(ctx context.Context, txn descs.Txn) (err error) {
-		defer func() {
```
Comment (rafiss) [inline pkg/sql/vecindex/manager_test.go:120]: is this change intentional? should it be a separate PR?

Comment (fqazi) [reply pkg/sql/vecindex/manager_test.go:120]: Yes, the incorrect commit breaks EmitDescriptorUpdatesKey if we flip the setting on. Though its disabled by default in this PR.

**Review by fqazi — COMMENTED** [review]
> @fqazi reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/153961)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @aerfrei, @alyshanjahani-crl, @kev-cao, @mgartner, and @rafiss)

**Comment by fqazi** [comment]
@rafiss TFTR!

bors r+
