### PR TITLE
sql: dropping and creating view in a single transaction behaves wrong.

### LINKED ISSUE #60737: schema: DROP and CREATE view within transaction drops the view
**Describe the problem**
Dropping and recreating a view within a transaction just drops the view.

**To Reproduce**
```
CREATE TABLE foo (a TEXT, b TEXT);
CREATE VIEW foo_view AS SELECT a FROM foo;
BEGIN;
    DROP VIEW IF EXISTS foo_view;
    CREATE VIEW IF NOT EXISTS foo_view AS SELECT a, b FROM foo;
COMMIT;

SELECT * FROM foo_view;
-- ERROR: relation "foo_view" does not exist
-- SQLSTATE: 42P01
```
**Expected behavior**
The view should be replaced, with the same behavior as a single `CREATE OR REPLACE VIEW...` statement.

**Environment:**
 - CockroachDB version 20.2.4

### PR DESCRIPTION
**Pull request by fqazi**
Fixes: #60737

Previously, when dropping and creating a view/table/sequence with if
exists clause in a single transaction would drop the view and not
create the view again, since we would see a descriptor in a dropping
state as created. Similarly, if the dropped object was a different
type we would silently ignore the error for the IF NOT EXISTS case.
To address this incorrect behaviour, this patch will return a
ObjectNotInPrerequisiteState if a descriptor in a dropping state is
found. Secondly, if the IF NOT EXISTS flag is specified we will
validate that the types match otherwise return WrongObjectType.

  Release note (bug fix): Dropping and recreating a view/table/sequence
  in a transaction will now correctly error out if a conflicting object
  exists or if the drop is incomplete.

  Release justification: Low risk change to address a high severity
  issue where users could have failures due to incorrect behaviour.

### CODE REVIEW

File: pkg/sql/create_view.go [hunk 1]
```diff
@@ -116,6 +116,22 @@ func (n *createViewNode) startExec(params runParams) error {
...
+				return err
+			}
+			desc, err := params.p.Descriptors().GetMutableTableVersionByID(params.ctx, id, params.p.txn)
+			if err != nil {
+				return err
+			}
+
+			if desc.Dropped() {
+				return pgerror.Newf(pgcode.ObjectNotInPrerequisiteState,
+					"view %q is being dropped, try again later",
```
Comment (postamar) [inline pkg/sql/create_view.go:131]: I believe it's possible that `desc` isn't a view, for example:
```
CREATE TABLE foo (a INT);
BEGIN;
  DROP TABLE IF EXISTS foo;
  CREATE VIEW IF NOT EXISTS foo AS SELECT 1;
COMMIT;
```

Comment (fqazi) [reply pkg/sql/create_view.go:131]: Good find, yes I need to check IsView on the descriptor.

**Review by ajwerner — COMMENTED** [review]
Seems like we have the same problem for tables and sequences. How do you feel about pushing this check into `getTableCreateParams` and taking a `tree.DesiredObjectKind` to validate the existence of the thing and its type. If we do that and we return a more specific error in the case of the existing object either being the wrong type or being in the wrong state then we shouldn't need to change the callers

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/61135#-:-MUPX9-c4fcDqf88_6b7:b-zbvrne)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @postamar)

**Comment by fqazi** [comment]
> Seems like we have the same problem for tables and sequences. How do you feel about pushing this check into `getTableCreateParams` and taking a `tree.DesiredObjectKind` to validate the existence of the thing and its type. If we do that and we return a more specific error in the case of the existing object either being the wrong type or being in the wrong state then we shouldn't need to change the callers
> 
> > _[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/61135#-:-MUPX9-c4fcDqf88_6b7:b-zbvrne)_ status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @postamar)

I'll push the check down and surface the correct errors. Thanks for the quick review.

**Review by fqazi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/61135)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner and @postamar)

___
*[pkg/sql/create_view.go, line 131 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/61135#-MUPO8USZvz6uSX6GG6U-r1-131:-MUU9F0840HxevafAcPD:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/5189c4f086f5527fdea965af816d9fb0f34a775a/pkg/sql/create_view.go#L131)):*
<details><summary><i>Previously, fqazi (Faizan Qazi) wrote…</i></summary><blockquote>

Good find, yes I need to check IsView on the descriptor.
</blockquote></details>

Done.

**Review by ajwerner — COMMENTED** [review]
> Reviewed 3 of 8 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/61135)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @fqazi and @postamar)

___
*[pkg/sql/create_table.go, line 205 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/61135#-MUUmSmh2V0mcnre925O:-MUUmSmh2V0mcnre925P:b-qrmn3q) ([raw file](https://github.com/cockroachdb/cockroach/blob/21bec5d53a28a0ab33857951cdde17a68896e352/pkg/sql/create_table.go#L205)):*
<details><summary><i alt="summary">Quoted 6 lines of code…</i></summary>

> ```
> 		desc, err := catalogkv.GetAnyDescriptorByID(params.ctx, params.p.txn, params.ExecCfg().Codec, id, catalogkv.Immutable)
> 		if err != nil {
> 			return nil, 0, sqlerrors.WrapErrorWhileConstructingObjectAlreadyExistsErr(err)
> 		}
> 		// Check if the type of object doesn't match
> 		var tableDescriptor, isTableDescriptor = desc.(catalog.TableDescriptor)
> ```
</details>


I won't lie, the fact that this is using `catalogkv` at this layer makes me very sad. In principle this should be using:

```
desc, err := params.p.Descriptors.GetImmutableTableByID(params.ctx, params.p.txn, id, tree.ObjectLookupFlags{
    CommonLookupFlags: tree.CommonLookupFlags{
         AvoidCache: true,
    },
    DesiredTableDescKind: kind
})
```
However, the above is busted because the descriptor collection totally ignores that `DesiredTableDescKind` which is a really awful API that we desperately need to do something about.  

Another wart about this `catalogkv` call is it can happily return `nil, nil` if the thing doesn't exist. That's a weird case that you won't expect. I can't think of why it would happen. 

Given that, I still think you should use the above API but not set the flag with kind, and put a `TODO` comment complaining about how it doesn't work. 
___
*[pkg/sql/create_table.go, line 215 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/61135#-MUUjZt6-cFb_7OYEw8A:-MUUjZt6-cFb_7OYEw8B:b-vhok8c) ([raw file](https://github.com/cockroachdb/cockroach/blob/21bec5d53a28a0ab33857951cdde17a68896e352/pkg/sql/create_table.go#L215)):*
> ```
> 		var tableDescriptor, isTableDescriptor = desc.(catalog.TableDescriptor)
> 		var mismatchedType = true
> ```

nit use `:=` assignment

Further nit, giving the scoping, I'd pull the type assertion into the if statement. I also have a tendency to like scopes to clarify the grouping of the intention of code.

I'd probably type this all as:

```
// Ensure that the descriptor that does exist has the appropriate type. 
{
  mismatchedType := true
  if tableDescriptor, ok := desc.(catalog.TableDescriptor); ok {
        mismatchedType = false
	switch kind {
	case tree.ResolveRequireTableDesc:
		mismatchedType = !tableDescriptor.IsTable()
	case tree.ResolveRequireViewDesc:
		mismatchedType = !tableDescriptor.IsView()
	case tree.ResolveRequireSequenceDesc:
		mismatchedType = !tableDescriptor.IsSequence()
	}
	// If kind any is passed then there will never be a mismatch
	// and we can return an exists error.
  }
  // Only complain about mismatched types for
  // if not exists clauses.
  if mismatchedType && ifNotExists {
	return nil, 0, pgerror.Newf(pgcode.WrongObjectType,
		"%q is not a %s",
		tableName.Table(),
		kind))
  }
}
```
___
*[pkg/sql/create_table.go, line 239 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/61135#-MUUoLHe6Eb9iXEQ1yxz:-MUUoLHf9fQxQAbb3hL8:b6lxyt2) ([raw file](https://github.com/cockroachdb/cockroach/blob/21bec5d53a28a0ab33857951cdde17a68896e352/pkg/sql/create_table.go#L239)):*
> ```Go
> 				"%q is not a %s",
> 				tableName.Table(),
> 				kind.String())
> ```

another nit here is that you shouldn't call `String()` here. Firsltly %s implies calling the `String()` method. The reasons to do it would be to avoid an allocation of this `kind` variable but I couldn't care less about allocation on these schema change paths. The reason not to do it is if this error gets logged and redacted we won't get access to that kind but kind is going to be marked as a safe type for redaction so it would show up in the redacted logs if it isn't passed to the error as a string. 
___
*[pkg/sql/create_table.go, line 246 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/61135#-MUUoiCA0RfDqRYuH1aP:-MUUoiCA0RfDqRYuH1aQ:b-dpgh0y) ([raw file](https://github.com/cockroachdb/cockroach/blob/21bec5d53a28a0ab33857951cdde17a68896e352/pkg/sql/create_table.go#L246)):*
> ```Go
> 			return nil, 0, pgerror.Newf(pgcode.ObjectNotInPrerequisiteState,
> 				"%s %q is being dropped, try again later",
> 				kind.String(),
> ```

same `String()` nit.

**Review by fqazi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/61135)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner and @postamar)

___
*[pkg/sql/create_table.go, line 205 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/61135#-MUUmSmh2V0mcnre925O:-MUV55FtAlmrNFhNbepa:b-dfg9j0) ([raw file](https://github.com/cockroachdb/cockroach/blob/21bec5d53a28a0ab33857951cdde17a68896e352/pkg/sql/create_table.go#L205)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

> ```
> 		desc, err := catalogkv.GetAnyDescriptorByID(params.ctx, params.p.txn, params.ExecCfg().Codec, id, catalogkv.Immutable)
> 		if err != nil {
> 			return nil, 0, sqlerrors.WrapErrorWhileConstructingObjectAlreadyExistsErr(err)
> 		}
> 		// Check if the type of object doesn't match
> 		var tableDescriptor, isTableDescriptor = desc.(catalog.TableDescriptor)
> ```

I won't lie, the fact that this is using `catalogkv` at this layer makes me very sad. In principle this should be using:

```
desc, err := params.p.Descriptors.GetImmutableTableByID(params.ctx, params.p.txn, id, tree.ObjectLookupFlags{
    CommonLookupFlags: tree.CommonLookupFlags{
         AvoidCache: true,
    },
    DesiredTableDescKind: kind
})
```
However, the above is busted because the descriptor collection totally ignores that `DesiredTableDescKind` which is a really awful API that we desperately need to do something about.  

Another wart about this `catalogkv` call is it can happily return `nil, nil` if the thing doesn't exist. That's a weird case that you won't expect. I can't think of why it would happen. 

Given that, I still think you should use the above API but not set the flag with kind, and put a `TODO` comment complaining about how it doesn't work. 
</blockquote></details>

This wasn't feasible so keeping with kv API. Opened a follow on an issue for it.

**Review by ajwerner — APPROVED** [review]
The release justification police are holding this back, you'll need it on the commits and the PR :/ 
While you're at it, this deserves a release note as it fixes a pretty severe bug. 

I'm thinking we should backport this to the last two versions too as it's pretty awful (tagged it thusly). 

> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/61135#-:-MUVHLe71G7rdqyksjEY:b-bkt0gd)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner and @postamar)
