### PR TITLE
sql/parser: bugfix in comparison simplification

### LINKED ISSUE #14687: sql: comparison broken against division with column dividend and negative divisor
Check out the following query, which implies that we think `0 < -10` in some circumstances:

```
root@:26257/test> SELECT i / -1, 0 < i / -1 from (select 10 as i);
+-----------+-----------------+
| i / (- 1) | 0 < (i / (- 1)) |
+-----------+-----------------+
|       -10 | true            |
+-----------+-----------------+
(1 row)
```

Note that this works correctly with multiplication.

In Postgres, for the record, the (obviously correct) result is:

```
jordan=# SELECT i / -1, 0 < i / -1 from (select 10 as i) as foo;
 ?column? | ?column?
----------+----------
      -10 | f
(1 row)
```

### PR DESCRIPTION
**Pull request by jordanlewis**
Previously, simplifying an inequality with a division on one side that
had a negative divisor and variable dividend resulted in an incorrect
output.

This caused queries like `SELECT 0 < (SELECT 10) / -1` to return an
incorrect result - in this case, `true` instead of `false`.

This bug occurred during the "comparison rotation" phase of expression
simplification that attempts to isolate a variable to the left side of a
comparison between a constant and a binary expression containing the
variable. This phase algebraically transforms an expression like
`0 < x + 1` to `0 - 1 < x` by reversing the binary operator on the right
side and effectively applying the result to both sides.

When it encountered a division like `0 < x / 1`, the algorithm in effect
tried to multiply both sides of the equation by the divisor, which seems
correct. However, it was missing a crucial rule of algebraic
manipulation of inequalities: when multiplying both sides by a negative
number, the direction of the inequality *must be flipped*.

This deficiency is now corrected by flipping the inequality during the
transformation if the divisor is negative.

Fixes #14687.

### CODE REVIEW

**Comment by petermattis** [comment]
:lgtm:

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14702#-:-Kh7tZWXMWMWUUdd5djy:bnfp4nl)*

**Comment by eisenstatdavid** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[pkg/sql/parser/normalize.go, line 319 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/14702#-Kh7vuLOlZIYhb971Gzt:-Kh7vuLOlZIYhb971Gzu:bel0ohh) ([raw file](https://github.com/cockroachdb/cockroach/blob/53e06acb1b7b25867a00772cb9d703dc07c238ff/pkg/sql/parser/normalize.go#L319)):*
> ```Go
> 							return expr
> 						}
> 						if divisor.Compare(v.ctx, NewDInt(0)) < 0 {
> ```

Can we avoid the allocation for `NewDInt(0)`?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14702#-:-Kh7w4qhoKHO2svF40OV:bnfp4nl)*

**Comment by jordanlewis** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[pkg/sql/parser/normalize.go, line 319 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/14702#-Kh7vuLOlZIYhb971Gzt:-Kh7yQkNmuAfjwn0SMAE:b-3k5uva) ([raw file](https://github.com/cockroachdb/cockroach/blob/53e06acb1b7b25867a00772cb9d703dc07c238ff/pkg/sql/parser/normalize.go#L319)):*
<details><summary><i>Previously, eisenstatdavid (David Eisenstat) wrote…</i></summary><blockquote>

Can we avoid the allocation for `NewDInt(0)`?
</blockquote></details>

I don't think so, unless there's a DZero constant hanging around somewhere. I wonder if we should add some kind of constant pool actually for low integer datums the way Python does.

I grepped for `NewDInt(0)` and there are 7 instances of it in the code - I'll add a constant in a separate PR, next to `DBoolTrue` and `DBoolFalse`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14702)*

**Comment by jordanlewis** [comment]
TFTRs!

---

Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14702#-:-Kh7zAbvxx6ARI7pV5sr:bz5mair)*

File: pkg/sql/parser/normalize.go [hunk 1]
```diff
@@ -307,6 +307,30 @@ func (expr *ComparisonExpr) normalize(v *normalizeVisitor) TypedExpr {
...
+						if divisor.Compare(v.ctx, NewDInt(0)) < 0 {
+							if !exprCopied {
+								exprCopy := *expr
+								expr = &exprCopy
+								exprCopied = true
+							}
+
+							invertedOp, err := invertComparisonOp(expr.Operator)
+							if err != nil {
+								v.err = nil
```
Comment (tamird) [inline pkg/sql/parser/normalize.go]: this looks wrong.
