### PR TITLE
ci: check that generated documentation is up-to-date

### LINKED ISSUE #137133: ci: post-`release-24.1` CI checks are missing verification that the generated files in `docs/generated/sql` are up-to-date
**Describe the problem**

The logic you see [here](https://github.com/cockroachdb/cockroach/blob/release-23.2/build/teamcity/cockroach/ci/builds/build_linux_x86_64.sh#L55) appears to be missing in post-`release-24.1` versions of the checks. This resulted in the `release-23.1` [backport](https://github.com/cockroachdb/cockroach/pull/137111) of [this PR](https://github.com/cockroachdb/cockroach/pull/137058) failing to pass CI, when the original PR and other backports (incorrectly) passed CI fine.

We need to make sure CI includes this check, and fix-forward `master` to make up for incorrectness that has already been introduced. We also need to backport this all the way back to `release-24.1` and fix any incorrectness that leaked onto those branches.

Jira issue: CRDB-45399

### PR DESCRIPTION
**Pull request by rickystewart**
Since `release-24.1`, CI has been missing a set of checks that
ensure the generated documentation files are configured correctly
with respect to `BUILD.bazel` and the checked-in files. Here we add
them back in and fix the skew that has already been introduced.

Closes: #137133

Epic: none
Release note: None

### CODE REVIEW

File: build/github/build.sh [hunk 1]
```diff
@@ -48,3 +48,59 @@ bazel build \
...
+    fi
+done
+# Ensure the generated docs are inclusive of what we have in tree: list all
+# generated files in a few subdirectories and make sure they're all in the
+# build output.
+for FILE in $(ls docs/generated/http/*.md | xargs -n1 basename)
+do
+    if [[ ! -f $BAZEL_BIN/docs/generated/http/$FILE ]]
+    then
+        echo "File $BAZEL_BIN/docs/generated/http/$FILE does not exist as a generated artifact; it is checked in at `docs/generated/http`, but is not being built. Is docs/generated/http/BUILD.bazel up-to-date?"
```
Comment (jlinder) [inline build/github/build.sh:81]:
```suggestion
        echo "File $BAZEL_BIN/docs/generated/http/$FILE does not exist as a generated artifact; it is checked in under `docs/generated/http`, but is not being built. Is docs/generated/http/BUILD.bazel up-to-date?"
```

File: build/github/build.sh [hunk 2]
```diff
@@ -48,3 +48,59 @@ bazel build \
...
+        FAILED=1
+    fi
+done
+for FILE in $(ls docs/generated/sql/*.md | xargs -n1 basename)
+do
+    if [[ ! -f $BAZEL_BIN/docs/generated/sql/$FILE ]]
+    then
+        echo "File $BAZEL_BIN/docs/generated/sql/$FILE does not exist as a generated artifact; it is checked in at `docs/generated/sql`, but is not being built. Is docs/generated/sql/BUILD.bazel up-to-date?"
```
Comment (jlinder) [inline build/github/build.sh:89]:
```suggestion
        echo "File $BAZEL_BIN/docs/generated/sql/$FILE does not exist as a generated artifact; it is checked in under `docs/generated/sql`, but is not being built. Is docs/generated/sql/BUILD.bazel up-to-date?"
```

File: build/github/build.sh [hunk 3]
```diff
@@ -48,3 +48,59 @@ bazel build \
...
+        FAILED=1
+    fi
+done
+for FILE in $(ls docs/generated/sql/bnf/*.bnf | xargs -n1 basename)
+do
+    if [[ ! -f $BAZEL_BIN/docs/generated/sql/bnf/$FILE ]]
+    then
+        echo "File $BAZEL_BIN/docs/generated/sql/bnf/$FILE does not exist as a generated artifact; it is checked in at `docs/generated/sql/bnf`, but is not being built. Is docs/generated/sql/bnf/BUILD.bazel up-to-date?"
```
Comment (jlinder) [inline build/github/build.sh:97]:
```suggestion
        echo "File $BAZEL_BIN/docs/generated/sql/bnf/$FILE does not exist as a generated artifact; it is checked in at `docs/generated/sql/bnf`, but is not being built. Is docs/generated/sql/bnf/BUILD.bazel up-to-date?"
```

**Review by jlinder — APPROVED** [review]
A few grammatical suggestions. Good either way.

**Comment by rickystewart** [comment]
TFTR!

bors r=jlinder
