### PR TITLE
storage: check for uninitialized raft group

### LINKED ISSUE #16184: storage: TestStoreRangeMergeStats failed under stress
SHA: https://github.com/cockroachdb/cockroach/commits/db8da7c6f9551b69fd464803133db170001e3470

Parameters:
```
TAGS=
GOFLAGS=
```

Stress build found a failed test: https://teamcity.cockroachdb.com/viewLog.html?buildId=258479&tab=buildLog

```

I170527 06:51:56.624866 24456 storage/store.go:1256  [n1,s1]: failed initial metrics computation: [n1,s1]: system config not yet available
I170527 06:51:56.626375 24456 storage/replica_command.go:2633  [s1,r1/1:/M{in-ax}] initiating a split of this range at key "b" [r2]
I170527 06:51:56.683290 24456 storage/replica_command.go:3123  [s1,r1/1:{/Min-b}] initiating a merge of [n1,s1,r2/1:{b-/Max}] into this range
W170527 06:51:56.684178 24456 storage/stores.go:218  range not contained in one range: [/Min,"b\x00"), but have [/Min,"b")
I170527 06:51:56.687787 24494 storage/store.go:2146  [s1,r1/1:{/Min-b}] removing replica
E170527 06:51:56.687987 24475 storage/queue.go:636  [raftlog,s1,r2/1:{b-/Max}] result is ambiguous (removing replica)
E170527 06:51:56.688145 24495 util/log/crash_reporting.go:81  a panic has occurred!
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0xe9656d]

goroutine 24495 [running]:
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).Recover(0xc4211f6000, 0x7f2d09758410, 0xc420f9e4b0)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:200 +0xb1
panic(0x195b7a0, 0x275b120)
	/usr/local/go/src/runtime/panic.go:489 +0x2cf
github.com/cockroachdb/cockroach/pkg/storage.(*Replica).updateProposalQuotaRaftMuLocked(0xc420634700, 0x7f2d09758410, 0xc4210289c0, 0x1)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/replica.go:909 +0xdd
github.com/cockroachdb/cockroach/pkg/storage.(*Replica).handleRaftReadyRaftMuLocked(0xc420634700, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/replica.go:2997 +0x1c70
github.com/cockroachdb/cockroach/pkg/storage.(*Replica).handleRaftReady(0xc420634700, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/replica.go:2944 +0xe0
github.com/cockroachdb/cockroach/pkg/storage.(*Store).processReady(0xc42046cc00, 0x2)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/store.go:3417 +0x131
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).worker(0xc420654240, 0xc4211f6000)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:217 +0x270
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).Start.func2(0x7f2d09758410, 0xc420f9e4b0)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:168 +0x33
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc420337dd0, 0xc4211f6000, 0xc4202f51c0)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:215 +0xf7
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:216 +0xad

goroutine 1 [chan receive]:
testing.(*T).Run(0xc4204de4e0, 0x1b2f2cf, 0x18, 0x1be83d8, 0xc4205bda01)
	/usr/local/go/src/testing/testing.go:698 +0x2f4
testing.runTests.func1(0xc4204de4e0)
	/usr/local/go/src/testing/testing.go:882 +0x67
testing.tRunner(0xc4204de4e0, 0xc4205bdb78)
	/usr/local/go/src/testing/testing.go:657 +0x96
testing.runTests(0xc4201da840, 0x2776ba0, 0x1b3, 0x1b3, 0xc4205bdc00)
	/usr/local/go/src/testing/testing.go:888 +0x2c1
testing.(*M).Run(0xc4205c3f20, 0xc4205bdd70)
	/usr/local/go/src/testing/testing.go:822 +0xfc
github.com/cockroachdb/cockroach/pkg/storage_test.TestMain(0xc4205bdf20)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/main_test.go:59 +0x20a
main.main()
	github.com/cockroachdb/cockroach/pkg/storage/_test/_testmain.go:922 +0xf7

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:2197 +0x1

goroutine 5 [chan receive]:
github.com/cockroachdb/cockroach/pkg/util/log.(*loggingT).flushDaemon(0x2c1d540)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/log/clog.go:1057 +0x77
created by github.com/cockroachdb/cockroach/pkg/util/log.init.1
	/go/src/github.com/cockroachdb/cockroach/pkg/util/log/clog.go:603 +0xd9

goroutine 11 [syscall]:
os/signal.signal_recv(0x0)
	/usr/local/go/src/runtime/sigqueue.go:116 +0x104
os/signal.loop()
	/usr/local/go/src/os/signal/signal_unix.go:22 +0x22
created by os/signal.init.1
	/usr/local/go/src/os/signal/signal_unix.go:28 +0x41

goroutine 24471 [select]:
github.com/cockroachdb/cockroach/pkg/storage.(*baseQueue).processLoop.func1(0x7f2d09758410, 0xc42023c4b0)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/queue.go:490 +0x364
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc420228070, 0xc4211f6000, 0xc4202260c0)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:215 +0xf7
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:216 +0xad

goroutine 24474 [select]:
github.com/cockroachdb/cockroach/pkg/storage.(*baseQueue).processLoop.func1(0x7f2d09758410, 0xc42023c660)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/queue.go:490 +0x364
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc4202280a0, 0xc4211f6000, 0xc420226120)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:215 +0xf7
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:216 +0xad

goroutine 24478 [runnable]:
github.com/cockroachdb/cockroach/pkg/storage.(*replicaScanner).waitAndProcess(0xc42001cf00, 0x7f2d09758410, 0xc42023c210, 0xed0bb190c, 0xc425443a72, 0x2c1bc80, 0xc420344040, 0xc4211f6000, 0xc420400e00, 0xc420400f00)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scanner.go:210 +0x241
github.com/cockroachdb/cockroach/pkg/storage.(*replicaScanner).scanLoop.func1.1(0xc420400e00, 0xc421308ff0)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scanner.go:272 +0x90
github.com/cockroachdb/cockroach/pkg/storage.(*storeReplicaVisitor).Visit(0xc421308ff0, 0xc4201a2140)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/store.go:358 +0x2ff
github.com/cockroachdb/cockroach/pkg/storage.(*replicaScanner).scanLoop.func1(0x7f2d09758410, 0xc42023c210)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scanner.go:274 +0x238
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc4202280e0, 0xc4211f6000, 0xc4202261c0)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:215 +0xf7
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:216 +0xad

goroutine 24485 [semacquire]:
sync.runtime_notifyListWait(0xc420344490, 0xc400000108)
	/usr/local/go/src/runtime/sema.go:298 +0x10b
sync.(*Cond).Wait(0xc420344480)
	/usr/local/go/src/sync/cond.go:57 +0x89
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).worker(0xc420654240, 0xc4211f6000)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:199 +0xac
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).Start.func2(0x7f2d09758410, 0xc420f9e240)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:168 +0x33
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc420337d30, 0xc4211f6000, 0xc4202f5060)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:215 +0xf7
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:216 +0xad

goroutine 24460 [select]:
github.com/cockroachdb/cockroach/pkg/kv.(*TxnCoordSender).printStatsLoop(0xc4204405b0, 0x7f2d09758410, 0xc42033de00)
	/go/src/github.com/cockroachdb/cockroach/pkg/kv/txn_coord_sender.go:255 +0xb4a
github.com/cockroachdb/cockroach/pkg/kv.NewTxnCoordSender.func1(0x7f2d09758410, 0xc42033de00)
	/go/src/github.com/cockroachdb/cockroach/pkg/kv/txn_coord_sender.go:239 +0x3e
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc420336620, 0xc4211f6000, 0xc420336610)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:215 +0xf7
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:216 +0xad

goroutine 24457 [chan receive]:
github.com/cockroachdb/cockroach/pkg/storage/engine.(*RocksDB).open.func2(0xc4208be000)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/engine/rocksdb.go:430 +0x44
created by github.com/cockroachdb/cockroach/pkg/storage/engine.(*RocksDB).open
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/engine/rocksdb.go:431 +0x4c1

goroutine 24487 [semacquire]:
sync.runtime_notifyListWait(0xc420344490, 0xc40000010a)
	/usr/local/go/src/runtime/sema.go:298 +0x10b
sync.(*Cond).Wait(0xc420344480)
	/usr/local/go/src/sync/cond.go:57 +0x89
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).worker(0xc420654240, 0xc4211f6000)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:199 +0xac
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).Start.func2(0x7f2d09758410, 0xc420f9e2a0)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:168 +0x33
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc420337d50, 0xc4211f6000, 0xc4202f50a0)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:215 +0xf7
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:216 +0xad

goroutine 24531 [semacquire]:
sync.runtime_notifyListWait(0xc420344490, 0xc4000000e4)
	/usr/local/go/src/runtime/sema.go:298 +0x10b
sync.(*Cond).Wait(0xc420344480)
	/usr/local/go/src/sync/cond.go:57 +0x89
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).worker(0xc420654240, 0xc4211f6000)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:199 +0xac
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).Start.func2(0x7f2d09758410, 0xc420f9e840)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:168 +0x33
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc4201a6170, 0xc4211f6000, 0xc4202f5760)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:215 +0xf7
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:216 +0xad

goroutine 24486 [semacquire]:
sync.runtime_notifyListWait(0xc420344490, 0xc400000109)
	/usr/local/go/src/runtime/sema.go:298 +0x10b
sync.(*Cond).Wait(0xc420344480)
	/usr/local/go/src/sync/cond.go:57 +0x89
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).worker(0xc420654240, 0xc4211f6000)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:199 +0xac
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).Start.func2(0x7f2d09758410, 0xc420f9e270)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:168 +0x33
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc420337d40, 0xc4211f6000, 0xc4202f5080)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:215 +0xf7
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:216 +0xad

goroutine 24567 [select]:
github.com/cockroachdb/cockroach/pkg/storage.(*idAllocator).start.func1(0x7f2d09758410, 0xc420f9f830)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/id_alloc.go:133 +0x729
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc4202ac540, 0xc4211f6000, 0xc4202ac530)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:215 +0xf7
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:216 +0xad

goroutine 24475 [select]:
github.com/cockroachdb/cockroach/pkg/storage.(*baseQueue).processLoop.func1(0x7f2d09758410, 0xc42023c690)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/queue.go:490 +0x364
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc4202280b0, 0xc4211f6000, 0xc420226140)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:215 +0xf7
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:216 +0xad

goroutine 24578 [select]:
github.com/cockroachdb/cockroach/pkg/kv.(*TxnCoordSender).heartbeatLoop(0xc4204405b0, 0x7f2d09758410, 0xc420216030, 0x4431a66e4f1046e, 0xe8a5f4d45b033a98)
	/go/src/github.com/cockroachdb/cockroach/pkg/kv/txn_coord_sender.go:691 +0x3d9
github.com/cockroachdb/cockroach/pkg/kv.(*TxnCoordSender).updateState.func2(0x7f2d097583d0, 0xc4201af2c0)
	/go/src/github.com/cockroachdb/cockroach/pkg/kv/txn_coord_sender.go:982 +0x4a
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunAsyncTask.func1(0xc4211f6000, 0x7f2d097583d0, 0xc4201af2c0, 0x24c272c, 0x16, 0x3d7, 0x279fae0, 0xc4202f40f8, 0xc420251620)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:294 +0xf3
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunAsyncTask
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:295 +0x14a

goroutine 24462 [semacquire]:
sync.runtime_notifyListWait(0xc420344490, 0xc400000101)
	/usr/local/go/src/runtime/sema.go:298 +0x10b
sync.(*Cond).Wait(0xc420344480)
	/usr/local/go/src/sync/cond.go:57 +0x89
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).worker(0xc420654240, 0xc4211f6000)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:199 +0xac
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).Start.func2(0x7f2d09758410, 0xc420f9e090)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:168 +0x33
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc420337cc0, 0xc4211f6000, 0xc4202f4f80)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:215 +0xf7
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:216 +0xad

goroutine 24456 [runnable]:
github.com/cockroachdb/cockroach/pkg/storage.(*Replica).tryExecuteWriteBatch(0xc420400e00, 0x7f2d09758410, 0xc42038ab70, 0xdf, 0x4, 0x100000001, 0x1, 0x1, 0x0, 0xc42043eb60, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/replica.go:2457 +0xcf2
github.com/cockroachdb/cockroach/pkg/storage.(*Replica).executeWriteBatch(0xc420400e00, 0x7f2d09758410, 0xc42038ab70, 0xdf, 0x4, 0x100000001, 0x1, 0x1, 0x0, 0xc42043eb60, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/replica.go:2285 +0x98
github.com/cockroachdb/cockroach/pkg/storage.(*Replica).Send(0xc420400e00, 0x7f2d09758410, 0xc42038ab70, 0xdf, 0x4, 0x100000001, 0x1, 0x1, 0x0, 0xc42043eb60, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/replica.go:1619 +0x229
github.com/cockroachdb/cockroach/pkg/storage.(*Store).Send(0xc42046cc00, 0x7f2d09758410, 0xc42038ab40, 0xdf, 0x4, 0x100000001, 0x1, 0x1, 0x0, 0xc42043eb60, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/store.go:2562 +0x7ae
github.com/cockroachdb/cockroach/pkg/storage.(*Stores).Send(0xc42007a100, 0x7f2d09758410, 0xc42038aae0, 0x0, 0x0, 0x100000001, 0x1, 0x1, 0x0, 0xc42043eb60, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/stores.go:187 +0x1cf
github.com/cockroachdb/cockroach/pkg/kv.(*senderTransport).SendNext(0xc4203c75e0, 0x7f2d09758410, 0xc42038aae0, 0xc420935500)
	/go/src/github.com/cockroachdb/cockroach/pkg/kv/transport.go:409 +0x1d3
github.com/cockroachdb/cockroach/pkg/kv.(*DistSender).sendToReplicas(0xc42056a900, 0x7f2d097583d0, 0xc420494cc0, 0x1dcd6500, 0xc421308870, 0xc42056a948, 0x1, 0xc4202f5420, 0x1, 0x1, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/kv/dist_sender.go:1154 +0x5a2
github.com/cockroachdb/cockroach/pkg/kv.(*DistSender).sendRPC(0xc42056a900, 0x7f2d097583d0, 0xc420494cc0, 0x1, 0xc4202f5420, 0x1, 0x1, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/kv/dist_sender.go:408 +0x311
github.com/cockroachdb/cockroach/pkg/kv.(*DistSender).sendSingleRange(0xc42056a900, 0x7f2d097583d0, 0xc4201af2c0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0xc42043e9c0, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/kv/dist_sender.go:473 +0x16e
github.com/cockroachdb/cockroach/pkg/kv.(*DistSender).sendPartialBatch(0xc42056a900, 0x7f2d097583d0, 0xc4201af2c0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0xc42043e9c0, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/kv/dist_sender.go:939 +0x3ce
github.com/cockroachdb/cockroach/pkg/kv.(*DistSender).divideAndSendBatchToRanges(0xc42056a900, 0x7f2d097583d0, 0xc4201af2c0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0xc42043e9c0, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/kv/dist_sender.go:809 +0x9cd
github.com/cockroachdb/cockroach/pkg/kv.(*DistSender).Send(0xc42056a900, 0x7f2d097583d0, 0xc4201af2c0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0xc42043e8f0, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/kv/dist_sender.go:623 +0x323
github.com/cockroachdb/cockroach/pkg/kv.(*TxnCoordSender).Send(0xc4204405b0, 0x7f2d097583d0, 0xc4201af2c0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0xc420951ad0, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/kv/txn_coord_sender.go:480 +0x382
github.com/cockroachdb/cockroach/pkg/internal/client.(*DB).send(0xc4202f4720, 0x7f2d097583d0, 0xc4201af2c0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0xc420951ad0, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/internal/client/db.go:528 +0x21a
github.com/cockroachdb/cockroach/pkg/internal/client.(*Txn).send(0xc4202dba20, 0x7f2d097583d0, 0xc4201af2c0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/internal/client/txn.go:864 +0x32e
github.com/cockroachdb/cockroach/pkg/internal/client.(*Txn).(github.com/cockroachdb/cockroach/pkg/internal/client.send)-fm(0x7f2d097583d0, 0xc4201af2c0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/internal/client/txn.go:434 +0x76
github.com/cockroachdb/cockroach/pkg/internal/client.sendAndFill(0x7f2d097583d0, 0xc4201af2c0, 0xc4209861f0, 0xc42025d100, 0x11, 0x0)
	/go/src/github.com/cockroachdb/cockroach/pkg/internal/client/db.go:436 +0xf7
github.com/cockroachdb/cockroach/pkg/internal/client.(*Txn).Run(0xc4202dba20, 0x7f2d097583d0, 0xc4201af2c0, 0xc42025d100, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/pkg/internal/client/txn.go:434 +0xda
github.com/cockroachdb/cockroach/pkg/storage.(*Replica).AdminMerge.func1(0x7f2d097583d0, 0xc4201af2c0, 0xc4202dba20, 0xa343d2, 0xc4202dba50)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/replica_command.go:3185 +0x7e1
github.com/cockroachdb/cockroach/pkg/internal/client.(*DB).Txn.func1(0x7f2d097583d0, 0xc4201af2c0, 0xc4202dba20, 0xc4202608c8, 0x19a0680, 0xc4202608e0)
	/go/src/github.com/cockroachdb/cockroach/pkg/internal/client/db.go:490 +0x43
github.com/cockroachdb/cockroach/pkg/internal/client.(*Txn).Exec(0xc4202dba20, 0x7f2d097583d0, 0xc4201af2c0, 0xc420010101, 0xc4202608f0, 0xc4213081b0, 0x1)
	/go/src/github.com/cockroachdb/cockroach/pkg/internal/client/txn.go:640 +0xb6
github.com/cockroachdb/cockroach/pkg/internal/client.(*DB).Txn(0xc4202f4720, 0x7f2d097583d0, 0xc4201af2c0, 0xc420250f60, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/pkg/internal/client/db.go:491 +0x142
github.com/cockroachdb/cockroach/pkg/storage.(*Replica).AdminMerge(0xc420400e00, 0x7f2d09758410, 0xc4213081b0, 0x2c5a7e0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/replica_command.go:3186 +0x2df
github.com/cockroachdb/cockroach/pkg/storage.(*Replica).executeAdminBatch(0xc420400e00, 0x7f2d09758410, 0xc4213081b0, 0xdf, 0x0, 0x0, 0x0, 0x1, 0x0, 0x0, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/replica.go:2149 +0x7d8
github.com/cockroachdb/cockroach/pkg/storage.(*Replica).Send(0xc420400e00, 0x7f2d09758410, 0xc4213081b0, 0xdf, 0x0, 0x0, 0x0, 0x1, 0x0, 0x0, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/replica.go:1625 +0x66c
github.com/cockroachdb/cockroach/pkg/storage.(*Store).Send(0xc42046cc00, 0x7f2d09758410, 0xc421309650, 0xdf, 0x0, 0x0, 0x0, 0x1, 0x0, 0x0, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/store.go:2562 +0x7ae
github.com/cockroachdb/cockroach/pkg/internal/client.Wrap.func1(0x7f2d09751918, 0xc420016e28, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/internal/client/sender.go:88 +0xe5
github.com/cockroachdb/cockroach/pkg/internal/client.SenderFunc.Send(0xc420250ea0, 0x7f2d09751918, 0xc420016e28, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/internal/client/sender.go:50 +0x75
github.com/cockroachdb/cockroach/pkg/internal/client.SendWrappedWith(0x7f2d09751918, 0xc420016e28, 0x27822a0, 0xc420250ea0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/internal/client/sender.go:64 +0x143
github.com/cockroachdb/cockroach/pkg/internal/client.SendWrapped(0x7f2d09751918, 0xc420016e28, 0x27822a0, 0xc420250ea0, 0x279c1a0, 0xc420197f80, 0x0, 0x598f, 0x77)
	/go/src/github.com/cockroachdb/cockroach/pkg/internal/client/sender.go:81 +0xaf
github.com/cockroachdb/cockroach/pkg/storage_test.TestStoreRangeMergeStats(0xc4208eaf70)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/client_merge_test.go:419 +0x8c3
testing.tRunner(0xc4208eaf70, 0x1be83d8)
	/usr/local/go/src/testing/testing.go:657 +0x96
created by testing.(*T).Run
	/usr/local/go/src/testing/testing.go:697 +0x2ca

goroutine 24473 [select]:
github.com/cockroachdb/cockroach/pkg/storage.(*baseQueue).processLoop.func1(0x7f2d09758410, 0xc42023c630)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/queue.go:490 +0x364
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc420228090, 0xc4211f6000, 0xc420226100)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:215 +0xf7
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:216 +0xad

goroutine 24465 [semacquire]:
sync.runtime_notifyListWait(0xc420344490, 0xc400000100)
	/usr/local/go/src/runtime/sema.go:298 +0x10b
sync.(*Cond).Wait(0xc420344480)
	/usr/local/go/src/sync/cond.go:57 +0x89
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).worker(0xc420654240, 0xc4211f6000)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:199 +0xac
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).Start.func2(0x7f2d09758410, 0xc420f9e030)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:168 +0x33
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc420337cf0, 0xc4211f6000, 0xc4202f4fe0)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:215 +0xf7
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:216 +0xad

goroutine 24464 [semacquire]:
sync.runtime_notifyListWait(0xc420344490, 0xc400000103)
	/usr/local/go/src/runtime/sema.go:298 +0x10b
sync.(*Cond).Wait(0xc420344480)
	/usr/local/go/src/sync/cond.go:57 +0x89
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).worker(0xc420654240, 0xc4211f6000)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:199 +0xac
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).Start.func2(0x7f2d09758410, 0xc420f9e120)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:168 +0x33
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc420337ce0, 0xc4211f6000, 0xc4202f4fc0)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:215 +0xf7
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:216 +0xad

goroutine 24461 [chan receive]:
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).Start.func1(0x7f2d09758410, 0xc420f9e060)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:158 +0x55
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc420337cb0, 0xc4211f6000, 0xc4202f4f40)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:215 +0xf7
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:216 +0xad

goroutine 24477 [select]:
github.com/cockroachdb/cockroach/pkg/storage.(*baseQueue).processLoop.func1(0x7f2d09758410, 0xc42023c900)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/queue.go:490 +0x364
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc4202280d0, 0xc4211f6000, 0xc4202261a0)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:215 +0xf7
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:216 +0xad

goroutine 24463 [semacquire]:
sync.runtime_notifyListWait(0xc420344490, 0xc400000102)
	/usr/local/go/src/runtime/sema.go:298 +0x10b
sync.(*Cond).Wait(0xc420344480)
	/usr/local/go/src/sync/cond.go:57 +0x89
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).worker(0xc420654240, 0xc4211f6000)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:199 +0xac
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).Start.func2(0x7f2d09758410, 0xc420f9e0c0)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:168 +0x33
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc420337cd0, 0xc4211f6000, 0xc4202f4fa0)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:215 +0xf7
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:216 +0xad

goroutine 24484 [semacquire]:
sync.runtime_notifyListWait(0xc420344490, 0xc400000106)
	/usr/local/go/src/runtime/sema.go:298 +0x10b
sync.(*Cond).Wait(0xc420344480)
	/usr/local/go/src/sync/cond.go:57 +0x89
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).worker(0xc420654240, 0xc4211f6000)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:199 +0xac
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).Start.func2(0x7f2d09758410, 0xc420f9e210)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:168 +0x33
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc420337d20, 0xc4211f6000, 0xc4202f5040)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:215 +0xf7
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:216 +0xad

goroutine 24472 [select]:
github.com/cockroachdb/cockroach/pkg/storage.(*baseQueue).processLoop.func1(0x7f2d09758410, 0xc42023c540)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/queue.go:490 +0x364
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc420228080, 0xc4211f6000, 0xc4202260e0)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:215 +0xf7
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:216 +0xad

goroutine 24476 [select]:
github.com/cockroachdb/cockroach/pkg/storage.(*baseQueue).processLoop.func1(0x7f2d09758410, 0xc42023c8d0)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/queue.go:490 +0x364
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc4202280c0, 0xc4211f6000, 0xc420226180)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:215 +0xf7
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:216 +0xad

goroutine 24483 [semacquire]:
sync.runtime_notifyListWait(0xc420344490, 0xc400000105)
	/usr/local/go/src/runtime/sema.go:298 +0x10b
sync.(*Cond).Wait(0xc420344480)
	/usr/local/go/src/sync/cond.go:57 +0x89
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).worker(0xc420654240, 0xc4211f6000)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:199 +0xac
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).Start.func2(0x7f2d09758410, 0xc420f9e1e0)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:168 +0x33
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc420337d10, 0xc4211f6000, 0xc4202f5020)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:215 +0xf7
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:216 +0xad

goroutine 24458 [chan receive]:
github.com/cockroachdb/cockroach/pkg/rpc.NewContext.func1(0x7f2d09758410, 0xc42033d410)
	/go/src/github.com/cockroachdb/cockroach/pkg/rpc/context.go:186 +0x76
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc420336060, 0xc4211f6000, 0xc4202f4100)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:215 +0xf7
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:216 +0xad

goroutine 24482 [semacquire]:
sync.runtime_notifyListWait(0xc420344490, 0xc400000104)
	/usr/local/go/src/runtime/sema.go:298 +0x10b
sync.(*Cond).Wait(0xc420344480)
	/usr/local/go/src/sync/cond.go:57 +0x89
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).worker(0xc420654240, 0xc4211f6000)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:199 +0xac
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).Start.func2(0x7f2d09758410, 0xc420f9e1b0)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:168 +0x33
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc420337d00, 0xc4211f6000, 0xc4202f5000)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:215 +0xf7
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:216 +0xad

goroutine 24488 [semacquire]:
sync.runtime_notifyListWait(0xc420344490, 0xc40000010b)
	/usr/local/go/src/runtime/sema.go:298 +0x10b
sync.(*Cond).Wait(0xc420344480)
	/usr/local/go/src/sync/cond.go:57 +0x89
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).worker(0xc420654240, 0xc4211f6000)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:199 +0xac
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).Start.func2(0x7f2d09758410, 0xc420f9e2d0)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:168 +0x33
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc420337d60, 0xc4211f6000, 0xc4202f50c0)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:215 +0xf7
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:216 +0xad

goroutine 24530 [semacquire]:
sync.runtime_notifyListWait(0xc420344490, 0xc4000000fb)
	/usr/local/go/src/runtime/sema.go:298 +0x10b
sync.(*Cond).Wait(0xc420344480)
	/usr/local/go/src/sync/cond.go:57 +0x89
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).worker(0xc420654240, 0xc4211f6000)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:199 +0xac
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).Start.func2(0x7f2d09758410, 0xc420f9eba0)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:168 +0x33
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc4201a6130, 0xc4211f6000, 0xc4202f5740)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:215 +0xf7
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:216 +0xad

goroutine 24580 [runnable]:
github.com/cockroachdb/cockroach/pkg/storage.(*Replica).beginCmds(0xc420400e00, 0x7f2d09758410, 0xc420216d20, 0xc42040b0a0, 0xc421097080, 0x1, 0x8, 0xc4203378d0)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/replica.go:1928 +0xcd3
github.com/cockroachdb/cockroach/pkg/storage.(*Replica).tryExecuteWriteBatch(0xc420400e00, 0x7f2d09758410, 0xc420216d20, 0xdf, 0x1e, 0x100000001, 0x1, 0x1, 0x0, 0x0, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/replica.go:2376 +0x1039
github.com/cockroachdb/cockroach/pkg/storage.(*Replica).executeWriteBatch(0xc420400e00, 0x7f2d09758410, 0xc420216d20, 0xdf, 0x1e, 0x100000001, 0x1, 0x1, 0x0, 0x0, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/replica.go:2285 +0x98
github.com/cockroachdb/cockroach/pkg/storage.(*Replica).Send(0xc420400e00, 0x7f2d09758410, 0xc420216d20, 0xdf, 0x1e, 0x100000001, 0x1, 0x1, 0x0, 0x0, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/replica.go:1619 +0x229
github.com/cockroachdb/cockroach/pkg/storage.(*Store).Send(0xc42046cc00, 0x7f2d09758410, 0xc420216510, 0xdf, 0x1e, 0x100000001, 0x1, 0x1, 0x0, 0x0, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/store.go:2562 +0x7ae
github.com/cockroachdb/cockroach/pkg/storage.(*Stores).Send(0xc42007a100, 0x7f2d09758410, 0xc4202163f0, 0x0, 0x0, 0x100000001, 0x1, 0x1, 0x0, 0x0, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/stores.go:187 +0x1cf
github.com/cockroachdb/cockroach/pkg/kv.(*senderTransport).SendNext(0xc42030a500, 0x7f2d09758410, 0xc4202163f0, 0xc421096600)
	/go/src/github.com/cockroachdb/cockroach/pkg/kv/transport.go:409 +0x1d3
github.com/cockroachdb/cockroach/pkg/kv.(*DistSender).sendToReplicas(0xc42056a900, 0x7f2d097583d0, 0xc4203d3e40, 0x1dcd6500, 0xc421308870, 0xc42056a948, 0x1, 0xc4202140c0, 0x1, 0x1, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/kv/dist_sender.go:1154 +0x5a2
github.com/cockroachdb/cockroach/pkg/kv.(*DistSender).sendRPC(0xc42056a900, 0x7f2d097583d0, 0xc4203d3e40, 0x1, 0xc4202140c0, 0x1, 0x1, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/kv/dist_sender.go:408 +0x311
github.com/cockroachdb/cockroach/pkg/kv.(*DistSender).sendSingleRange(0xc42056a900, 0x7f2d09758410, 0xc4202161b0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/kv/dist_sender.go:473 +0x16e
github.com/cockroachdb/cockroach/pkg/kv.(*DistSender).sendPartialBatch(0xc42056a900, 0x7f2d09758410, 0xc4202161b0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/kv/dist_sender.go:939 +0x3ce
github.com/cockroachdb/cockroach/pkg/kv.(*DistSender).divideAndSendBatchToRanges(0xc42056a900, 0x7f2d09758410, 0xc4202161b0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/kv/dist_sender.go:809 +0x9cd
github.com/cockroachdb/cockroach/pkg/kv.(*DistSender).Send(0xc42056a900, 0x7f2d09758410, 0xc4202161b0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/kv/dist_sender.go:623 +0x323
github.com/cockroachdb/cockroach/pkg/kv.(*TxnCoordSender).Send(0xc4204405b0, 0x7f2d09758410, 0xc4202161b0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/kv/txn_coord_sender.go:480 +0x382
github.com/cockroachdb/cockroach/pkg/internal/client.(*DB).send(0xc4202f4720, 0x7f2d0966c3f0, 0xc4210964e0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/internal/client/db.go:528 +0x21a
github.com/cockroachdb/cockroach/pkg/internal/client.(*DB).(github.com/cockroachdb/cockroach/pkg/internal/client.send)-fm(0x7f2d0966c3f0, 0xc4210964e0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/internal/client/db.go:464 +0x76
github.com/cockroachdb/cockroach/pkg/internal/client.sendAndFill(0x7f2d0966c3f0, 0xc4210964e0, 0xc4206cce70, 0xc4207c2700, 0x1, 0xc420336080)
	/go/src/github.com/cockroachdb/cockroach/pkg/internal/client/db.go:436 +0xf7
github.com/cockroachdb/cockroach/pkg/internal/client.(*DB).Run(0xc4202f4720, 0x7f2d0966c3f0, 0xc4210964e0, 0xc4207c2700, 0x1, 0xc420336070)
	/go/src/github.com/cockroachdb/cockroach/pkg/internal/client/db.go:464 +0x9d
github.com/cockroachdb/cockroach/pkg/storage.(*intentResolver).maybePushTransactions(0xc421308e40, 0x7f2d0966c3f0, 0xc4210964e0, 0xc42093a510, 0x1, 0x1, 0xdf, 0x18, 0x0, 0x0, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/intent_resolver.go:202 +0xc39
github.com/cockroachdb/cockroach/pkg/storage.(*intentResolver).processIntents(0xc421308e40, 0x7f2d09751918, 0xc420016e40, 0xc420400e00, 0x279cb00, 0xc4204949c0, 0xc42093a510, 0x1, 0x1, 0xdf, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/intent_resolver.go:286 +0x199
github.com/cockroachdb/cockroach/pkg/storage.(*intentResolver).processIntentsAsync.func1(0x7f2d09751918, 0xc420016e40)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/intent_resolver.go:258 +0x7f
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunLimitedAsyncTask.func1(0xc4211f6000, 0x7f2d09751918, 0xc420016e40, 0x24c1ee3, 0x1a, 0x103, 0xc42035c360, 0x0, 0x0, 0xc42038a630)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:359 +0x120
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunLimitedAsyncTask
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:360 +0x285

goroutine 24581 [semacquire]:
sync.runtime_Semacquire(0xc420400f04)
	/usr/local/go/src/runtime/sema.go:47 +0x34
sync.(*RWMutex).RLock(0xc420400ef8)
	/usr/local/go/src/sync/rwmutex.go:43 +0x49
github.com/cockroachdb/cockroach/pkg/storage.(*Replica).ownsValidLease(0xc420400e00, 0xdf, 0x30, 0xc420400f00)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/replica.go:1045 +0x5c
github.com/cockroachdb/cockroach/pkg/storage.(*Store).LeaseCount.func1(0xc420400e00, 0xc420217320)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/store.go:2367 +0x44
github.com/cockroachdb/cockroach/pkg/storage.(*storeReplicaVisitor).Visit(0xc420217320, 0xc421228d30)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/store.go:358 +0x2ff
github.com/cockroachdb/cockroach/pkg/storage.(*Store).LeaseCount(0xc42046cc00, 0x1)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/store.go:2371 +0xc6
github.com/cockroachdb/cockroach/pkg/storage.(*Store).Capacity(0xc42046cc00, 0x69cd7c, 0xc420eeb6c0, 0xc4200107d8, 0x69d3dc, 0xc420eeb6c0)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/store.go:2278 +0xcb
github.com/cockroachdb/cockroach/pkg/storage.(*Store).Descriptor(0xc42046cc00, 0x0, 0xc420010780, 0xc4211f6001)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/store.go:2305 +0x2f
github.com/cockroachdb/cockroach/pkg/storage.(*Store).GossipStore(0xc42046cc00, 0x7f2d09758410, 0xc42038ab70, 0xc420eeb768, 0x10)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/store.go:1388 +0x7b
github.com/cockroachdb/cockroach/pkg/storage.(*Store).maybeGossipOnCapacityChange.func1(0x7f2d09758410, 0xc42038ab70)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/store.go:1457 +0x42
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunAsyncTask.func1(0xc4211f6000, 0x7f2d09758410, 0xc42038ab70, 0x24c1511, 0x10, 0x5b4, 0x279fae0, 0xc4202f40f8, 0xc420261c20)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:294 +0xf3
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunAsyncTask
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:295 +0x14a

goroutine 24529 [semacquire]:
sync.runtime_notifyListWait(0xc420344490, 0xc4000000f9)
	/usr/local/go/src/runtime/sema.go:298 +0x10b
sync.(*Cond).Wait(0xc420344480)
	/usr/local/go/src/sync/cond.go:57 +0x89
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).worker(0xc420654240, 0xc4211f6000)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:199 +0xac
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).Start.func2(0x7f2d09758410, 0xc420f9eb70)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:168 +0x33
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc4201a60a0, 0xc4211f6000, 0xc4202f5720)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:215 +0xf7
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:216 +0xad

goroutine 24546 [select]:
github.com/cockroachdb/cockroach/pkg/storage.(*Store).startGossip.func4(0x7f2d09758410, 0xc421309d70)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/store.go:1355 +0x4ee
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc4201a6540, 0xc4211f6000, 0xc4203c0140)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:215 +0xf7
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:216 +0xad

goroutine 24544 [select]:
github.com/cockroachdb/cockroach/pkg/storage.(*Store).startCoalescedHeartbeatsLoop.func1(0x7f2d09758410, 0xc420f9ebd0)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/store.go:3524 +0x167
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc4201a6500, 0xc4211f6000, 0xc4201a64e0)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:215 +0xf7
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:216 +0xad

goroutine 24542 [semacquire]:
sync.runtime_Semacquire(0xc4206542c4)
	/usr/local/go/src/runtime/sema.go:47 +0x34
sync.(*WaitGroup).Wait(0xc4206542b8)
	/usr/local/go/src/sync/waitgroup.go:131 +0x7a
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).Wait(0xc420654240, 0x7f2d09758410, 0xc420f9ec60)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:174 +0x31
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).Wait-fm(0x7f2d09758410, 0xc420f9ec60)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/store.go:3476 +0x3e
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc4201a6470, 0xc4211f6000, 0xc4201a6420)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:215 +0xf7
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:216 +0xad

goroutine 24540 [semacquire]:
sync.runtime_notifyListWait(0xc420344490, 0xc4000000fe)
	/usr/local/go/src/runtime/sema.go:298 +0x10b
sync.(*Cond).Wait(0xc420344480)
	/usr/local/go/src/sync/cond.go:57 +0x89
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).worker(0xc420654240, 0xc4211f6000)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:199 +0xac
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).Start.func2(0x7f2d09758410, 0xc420f9ec00)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:168 +0x33
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc4201a63d0, 0xc4211f6000, 0xc4202f58a0)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:215 +0xf7
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:216 +0xad

goroutine 24528 [semacquire]:
sync.runtime_notifyListWait(0xc420344490, 0xc4000000f8)
	/usr/local/go/src/runtime/sema.go:298 +0x10b
sync.(*Cond).Wait(0xc420344480)
	/usr/local/go/src/sync/cond.go:57 +0x89
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).worker(0xc420654240, 0xc4211f6000)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:199 +0xac
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).Start.func2(0x7f2d09758410, 0xc420f9eb40)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:168 +0x33
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc4201a6050, 0xc4211f6000, 0xc4202f56e0)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:215 +0xf7
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:216 +0xad

goroutine 24527 [semacquire]:
sync.runtime_notifyListWait(0xc420344490, 0xc4000000f6)
	/usr/local/go/src/runtime/sema.go:298 +0x10b
sync.(*Cond).Wait(0xc420344480)
	/usr/local/go/src/sync/cond.go:57 +0x89
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).worker(0xc420654240, 0xc4211f6000)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:199 +0xac
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).Start.func2(0x7f2d09758410, 0xc420f9eb10)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:168 +0x33
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc4201a6030, 0xc4211f6000, 0xc4202f56c0)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:215 +0xf7
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:216 +0xad

goroutine 24526 [semacquire]:
sync.runtime_notifyListWait(0xc420344490, 0xc4000000f4)
	/usr/local/go/src/runtime/sema.go:298 +0x10b
sync.(*Cond).Wait(0xc420344480)
	/usr/local/go/src/sync/cond.go:57 +0x89
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).worker(0xc420654240, 0xc4211f6000)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:199 +0xac
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).Start.func2(0x7f2d09758410, 0xc420f9eae0)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:168 +0x33
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc420337fe0, 0xc4211f6000, 0xc4202f56a0)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:215 +0xf7
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:216 +0xad

goroutine 24525 [semacquire]:
sync.runtime_notifyListWait(0xc420344490, 0xc4000000f2)
	/usr/local/go/src/runtime/sema.go:298 +0x10b
sync.(*Cond).Wait(0xc420344480)
	/usr/local/go/src/sync/cond.go:57 +0x89
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).worker(0xc420654240, 0xc4211f6000)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:199 +0xac
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).Start.func2(0x7f2d09758410, 0xc420f9eab0)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:168 +0x33
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc420337fd0, 0xc4211f6000, 0xc4202f5680)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:215 +0xf7
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:216 +0xad

goroutine 24500 [semacquire]:
sync.runtime_notifyListWait(0xc420344490, 0xc4000000d7)
	/usr/local/go/src/runtime/sema.go:298 +0x10b
sync.(*Cond).Wait(0xc420344480)
	/usr/local/go/src/sync/cond.go:57 +0x89
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).worker(0xc420654240, 0xc4211f6000)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:199 +0xac
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).Start.func2(0x7f2d09758410, 0xc420f9e5d0)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:168 +0x33
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc420337e30, 0xc4211f6000, 0xc4202f5280)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:215 +0xf7
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:216 +0xad

goroutine 24499 [semacquire]:
sync.runtime_notifyListWait(0xc420344490, 0xc4000000d6)
	/usr/local/go/src/runtime/sema.go:298 +0x10b
sync.(*Cond).Wait(0xc420344480)
	/usr/local/go/src/sync/cond.go:57 +0x89
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).worker(0xc420654240, 0xc4211f6000)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:199 +0xac
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).Start.func2(0x7f2d09758410, 0xc420f9e5a0)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:168 +0x33
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc420337e20, 0xc4211f6000, 0xc4202f5260)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:215 +0xf7
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:216 +0xad

goroutine 24498 [semacquire]:
sync.runtime_notifyListWait(0xc420344490, 0xc4000000d5)
	/usr/local/go/src/runtime/sema.go:298 +0x10b
sync.(*Cond).Wait(0xc420344480)
	/usr/local/go/src/sync/cond.go:57 +0x89
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).worker(0xc420654240, 0xc4211f6000)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:199 +0xac
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).Start.func2(0x7f2d09758410, 0xc420f9e570)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:168 +0x33
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc420337e00, 0xc4211f6000, 0xc4202f5240)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:215 +0xf7
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:216 +0xad

goroutine 24497 [semacquire]:
sync.runtime_notifyListWait(0xc420344490, 0xc4000000d4)
	/usr/local/go/src/runtime/sema.go:298 +0x10b
sync.(*Cond).Wait(0xc420344480)
	/usr/local/go/src/sync/cond.go:57 +0x89
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).worker(0xc420654240, 0xc4211f6000)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:199 +0xac
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).Start.func2(0x7f2d09758410, 0xc420f9e540)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:168 +0x33
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc420337df0, 0xc4211f6000, 0xc4202f5220)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:215 +0xf7
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:216 +0xad

goroutine 24496 [semacquire]:
sync.runtime_notifyListWait(0xc420344490, 0xc4000000d3)
	/usr/local/go/src/runtime/sema.go:298 +0x10b
sync.(*Cond).Wait(0xc420344480)
	/usr/local/go/src/sync/cond.go:57 +0x89
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).worker(0xc420654240, 0xc4211f6000)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:199 +0xac
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).Start.func2(0x7f2d09758410, 0xc420f9e4e0)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:168 +0x33
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc420337de0, 0xc4211f6000, 0xc4202f5200)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:215 +0xf7
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:216 +0xad

goroutine 24494 [runnable]:
sync.runtime_Semacquire(0xc420400f00)
	/usr/local/go/src/runtime/sema.go:47 +0x34
sync.(*RWMutex).Lock(0xc420400ef8)
	/usr/local/go/src/sync/rwmutex.go:91 +0x6e
github.com/cockroachdb/cockroach/pkg/util/syncutil.(*RWMutex).Lock(0xc420400ef8)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/syncutil/mutex_sync.go:70 +0x2d
github.com/cockroachdb/cockroach/pkg/storage.(*Replica).handleRaftReadyRaftMuLocked(0xc420400e00, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/replica.go:3151 +0xfb3
github.com/cockroachdb/cockroach/pkg/storage.(*Replica).handleRaftReady(0xc420400e00, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/replica.go:2944 +0xe0
github.com/cockroachdb/cockroach/pkg/storage.(*Store).processReady(0xc42046cc00, 0x1)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/store.go:3417 +0x131
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).worker(0xc420654240, 0xc4211f6000)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:217 +0x270
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).Start.func2(0x7f2d09758410, 0xc420f9e480)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:168 +0x33
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc420337dc0, 0xc4211f6000, 0xc4202f51a0)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:215 +0xf7
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:216 +0xad

goroutine 24493 [semacquire]:
sync.runtime_notifyListWait(0xc420344490, 0xc400000110)
	/usr/local/go/src/runtime/sema.go:298 +0x10b
sync.(*Cond).Wait(0xc420344480)
	/usr/local/go/src/sync/cond.go:57 +0x89
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).worker(0xc420654240, 0xc4211f6000)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:199 +0xac
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).Start.func2(0x7f2d09758410, 0xc420f9e420)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:168 +0x33
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc420337db0, 0xc4211f6000, 0xc4202f5180)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:215 +0xf7
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:216 +0xad

goroutine 24548 [select]:
github.com/cockroachdb/cockroach/pkg/storage.(*Store).startGossip.func4(0x7f2d09758410, 0xc421309da0)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/store.go:1355 +0x4ee
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc4201a65b0, 0xc4211f6000, 0xc4203c01e0)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:215 +0xf7
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:216 +0xad

goroutine 24547 [select]:
github.com/cockroachdb/cockroach/pkg/storage.(*Store).startGossip.func4(0x7f2d09758410, 0xc420f9ecc0)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/store.go:1355 +0x4ee
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc4201a6590, 0xc4211f6000, 0xc4203c0190)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:215 +0xf7
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:216 +0xad

goroutine 24545 [select]:
github.com/cockroachdb/cockroach/pkg/storage.(*Store).Start.func2(0x7f2d09758410, 0xc421309d40)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/store.go:1226 +0x165
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc4201a6520, 0xc4211f6000, 0xc4202f5900)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:215 +0xf7
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:216 +0xad

goroutine 24543 [select]:
github.com/cockroachdb/cockroach/pkg/storage.(*Store).raftTickLoop.func1(0x7f2d09758410, 0xc420f9ec90)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/store.go:3493 +0x337
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc4201a64c0, 0xc4211f6000, 0xc4201a64a0)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:215 +0xf7
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:216 +0xad

goroutine 24541 [semacquire]:
sync.runtime_notifyListWait(0xc420344490, 0xc4000000ff)
	/usr/local/go/src/runtime/sema.go:298 +0x10b
sync.(*Cond).Wait(0xc420344480)
	/usr/local/go/src/sync/cond.go:57 +0x89
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).worker(0xc420654240, 0xc4211f6000)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:199 +0xac
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).Start.func2(0x7f2d09758410, 0xc420f9ec30)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:168 +0x33
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc4201a6400, 0xc4211f6000, 0xc4202f58e0)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:215 +0xf7
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:216 +0xad

goroutine 24539 [semacquire]:
sync.runtime_notifyListWait(0xc420344490, 0xc4000000fd)
	/usr/local/go/src/runtime/sema.go:298 +0x10b
sync.(*Cond).Wait(0xc420344480)
	/usr/local/go/src/sync/cond.go:57 +0x89
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).worker(0xc420654240, 0xc4211f6000)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:199 +0xac
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).Start.func2(0x7f2d09758410, 0xc421309d10)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:168 +0x33
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc4201a6350, 0xc4211f6000, 0xc4202f5880)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:215 +0xf7
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:216 +0xad

goroutine 24538 [semacquire]:
sync.runtime_notifyListWait(0xc420344490, 0xc4000000fc)
	/usr/local/go/src/runtime/sema.go:298 +0x10b
sync.(*Cond).Wait(0xc420344480)
	/usr/local/go/src/sync/cond.go:57 +0x89
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).worker(0xc420654240, 0xc4211f6000)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:199 +0xac
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).Start.func2(0x7f2d09758410, 0xc421309ce0)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:168 +0x33
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc4201a6320, 0xc4211f6000, 0xc4202f5860)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:215 +0xf7
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:216 +0xad

goroutine 24537 [semacquire]:
sync.runtime_notifyListWait(0xc420344490, 0xc4000000fa)
	/usr/local/go/src/runtime/sema.go:298 +0x10b
sync.(*Cond).Wait(0xc420344480)
	/usr/local/go/src/sync/cond.go:57 +0x89
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).worker(0xc420654240, 0xc4211f6000)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:199 +0xac
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).Start.func2(0x7f2d09758410, 0xc421309cb0)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:168 +0x33
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc4201a62c0, 0xc4211f6000, 0xc4202f5840)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:215 +0xf7
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:216 +0xad

goroutine 24536 [semacquire]:
sync.runtime_notifyListWait(0xc420344490, 0xc4000000f7)
	/usr/local/go/src/runtime/sema.go:298 +0x10b
sync.(*Cond).Wait(0xc420344480)
	/usr/local/go/src/sync/cond.go:57 +0x89
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).worker(0xc420654240, 0xc4211f6000)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:199 +0xac
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).Start.func2(0x7f2d09758410, 0xc421309c80)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:168 +0x33
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc4201a6290, 0xc4211f6000, 0xc4202f5820)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:215 +0xf7
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:216 +0xad

goroutine 24535 [semacquire]:
sync.runtime_notifyListWait(0xc420344490, 0xc4000000f5)
	/usr/local/go/src/runtime/sema.go:298 +0x10b
sync.(*Cond).Wait(0xc420344480)
	/usr/local/go/src/sync/cond.go:57 +0x89
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).worker(0xc420654240, 0xc4211f6000)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:199 +0xac
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).Start.func2(0x7f2d09758410, 0xc421309c50)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:168 +0x33
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc4201a6250, 0xc4211f6000, 0xc4202f5800)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:215 +0xf7
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:216 +0xad

goroutine 24534 [semacquire]:
sync.runtime_notifyListWait(0xc420344490, 0xc4000000f3)
	/usr/local/go/src/runtime/sema.go:298 +0x10b
sync.(*Cond).Wait(0xc420344480)
	/usr/local/go/src/sync/cond.go:57 +0x89
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).worker(0xc420654240, 0xc4211f6000)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:199 +0xac
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).Start.func2(0x7f2d09758410, 0xc421309c20)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:168 +0x33
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc4201a6230, 0xc4211f6000, 0xc4202f57c0)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:215 +0xf7
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:216 +0xad

goroutine 24533 [semacquire]:
sync.runtime_notifyListWait(0xc420344490, 0xc4000000f1)
	/usr/local/go/src/runtime/sema.go:298 +0x10b
sync.(*Cond).Wait(0xc420344480)
	/usr/local/go/src/sync/cond.go:57 +0x89
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).worker(0xc420654240, 0xc4211f6000)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:199 +0xac
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).Start.func2(0x7f2d09758410, 0xc421309bf0)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:168 +0x33
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc4201a6210, 0xc4211f6000, 0xc4202f57a0)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:215 +0xf7
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:216 +0xad

goroutine 24532 [semacquire]:
sync.runtime_notifyListWait(0xc420344490, 0xc4000000ef)
	/usr/local/go/src/runtime/sema.go:298 +0x10b
sync.(*Cond).Wait(0xc420344480)
	/usr/local/go/src/sync/cond.go:57 +0x89
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).worker(0xc420654240, 0xc4211f6000)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:199 +0xac
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).Start.func2(0x7f2d09758410, 0xc421309bc0)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:168 +0x33
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc4201a61f0, 0xc4211f6000, 0xc4202f5780)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:215 +0xf7
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:216 +0xad

goroutine 24524 [semacquire]:
sync.runtime_notifyListWait(0xc420344490, 0xc4000000f0)
	/usr/local/go/src/runtime/sema.go:298 +0x10b
sync.(*Cond).Wait(0xc420344480)
	/usr/local/go/src/sync/cond.go:57 +0x89
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).worker(0xc420654240, 0xc4211f6000)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:199 +0xac
```

### LINKED ISSUE #16185: storage: TestGossipFirstRange failed under stress
SHA: https://github.com/cockroachdb/cockroach/commits/db8da7c6f9551b69fd464803133db170001e3470

Parameters:
```
TAGS=
GOFLAGS=-race
```

Stress build found a failed test: https://teamcity.cockroachdb.com/viewLog.html?buildId=258586&tab=buildLog

```

I170527 07:30:48.955791 68114 server/config.go:439  1 storage engine initialized
I170527 07:30:48.957039 68114 server/node.go:454  [n?] store [n0,s0] not bootstrapped
I170527 07:30:49.029937 68114 server/node.go:389  [n?] **** cluster 2b53681e-6f39-4ee6-91e7-d09a65a31e19 has been created
I170527 07:30:49.030038 68114 server/node.go:390  [n?] **** add additional nodes by specifying --join=127.0.0.1:41294
I170527 07:30:49.046722 68114 storage/store.go:1256  [n1] [n1,s1]: failed initial metrics computation: [n1,s1]: system config not yet available
I170527 07:30:49.046882 68114 server/node.go:467  [n1] initialized store [n1,s1]: {Capacity:536870912 Available:536870912 RangeCount:1 LeaseCount:0}
I170527 07:30:49.047640 68114 server/node.go:351  [n1] node ID 1 initialized
I170527 07:30:49.047929 68114 gossip/gossip.go:297  [n1] NodeDescriptor set to node_id:1 address:<network_field:"tcp" address_field:"127.0.0.1:41294" > attrs:<> locality:<> 
I170527 07:30:49.048548 68114 storage/stores.go:296  [n1] read 0 node addresses from persistent storage
I170527 07:30:49.048844 68114 server/node.go:608  [n1] connecting to gossip network to verify cluster ID...
I170527 07:30:49.049011 68114 server/node.go:633  [n1] node connected via gossip and verified as part of cluster "2b53681e-6f39-4ee6-91e7-d09a65a31e19"
I170527 07:30:49.049283 68114 server/node.go:405  [n1] node=1: started with [[]=] engine(s) and attributes []
I170527 07:30:49.054898 68114 sql/executor.go:355  [n1] creating distSQLPlanner with address {tcp 127.0.0.1:41294}
I170527 07:30:49.120348 68114 server/server.go:737  [n1] starting https server at 127.0.0.1:49195
I170527 07:30:49.120442 68114 server/server.go:738  [n1] starting grpc/postgres server at 127.0.0.1:41294
I170527 07:30:49.120478 68114 server/server.go:739  [n1] advertising CockroachDB node at 127.0.0.1:41294
I170527 07:30:49.246604 68114 sql/event_log.go:101  [n1] Event: "alter_table", target: 12, info: {TableName:eventlog Statement:ALTER TABLE system.eventlog ALTER COLUMN uniqueid SET DEFAULT uuid_v4() User:node MutationID:0 CascadeDroppedViews:[]}
I170527 07:30:49.427488 68114 sql/lease.go:372  [n1] publish: descID=12 (eventlog) version=2 mtime=2017-05-27 07:30:49.427364426 +0000 UTC
I170527 07:30:49.536617 68114 server/server.go:850  [n1] done ensuring all necessary migrations have run
I170527 07:30:49.536748 68114 server/server.go:852  [n1] serving sql connections
I170527 07:30:49.567919 68399 sql/event_log.go:101  [n1] Event: "node_join", target: 1, info: {Descriptor:{NodeID:1 Address:{NetworkField:tcp AddressField:127.0.0.1:41294} Attrs: Locality:} ClusterID:2b53681e-6f39-4ee6-91e7-d09a65a31e19 StartedAt:1495870249049051536 LastUp:1495870249049051536}
W170527 07:30:49.636701 68114 server/status/runtime.go:111  Could not parse build timestamp: parsing time "" as "2006/01/02 15:04:05": cannot parse "" as "2006"
W170527 07:30:49.639374 68114 gossip/gossip.go:1196  [n?] no incoming or outgoing connections
I170527 07:30:49.640662 68114 server/config.go:439  1 storage engine initialized
I170527 07:30:49.641902 68114 server/node.go:454  [n?] store [n0,s0] not bootstrapped
I170527 07:30:49.642048 68114 storage/stores.go:296  [n?] read 0 node addresses from persistent storage
I170527 07:30:49.642380 68114 server/node.go:608  [n?] connecting to gossip network to verify cluster ID...
I170527 07:30:49.778539 68443 gossip/client.go:131  [n?] started gossip client to 127.0.0.1:41294
I170527 07:30:49.780920 68517 gossip/server.go:234  [n1] received initial cluster-verification connection from {tcp 127.0.0.1:36729}
I170527 07:30:49.803732 68114 server/node.go:633  [n?] node connected via gossip and verified as part of cluster "2b53681e-6f39-4ee6-91e7-d09a65a31e19"
I170527 07:30:49.804561 68420 storage/stores.go:312  [n?] wrote 1 node addresses to persistent storage
I170527 07:30:49.829569 68114 kv/dist_sender.go:370  [n?] unable to determine this node's attributes for replica selection; node is most likely bootstrapping
I170527 07:30:49.837525 68114 server/node.go:344  [n?] new node allocated ID 2
I170527 07:30:49.837830 68114 gossip/gossip.go:297  [n2] NodeDescriptor set to node_id:2 address:<network_field:"tcp" address_field:"127.0.0.1:36729" > attrs:<> locality:<> 
I170527 07:30:49.838652 68114 server/node.go:405  [n2] node=2: started with [[]=] engine(s) and attributes []
I170527 07:30:49.843572 67712 storage/stores.go:312  [n1] wrote 1 node addresses to persistent storage
I170527 07:30:49.847369 68114 sql/executor.go:355  [n2] creating distSQLPlanner with address {tcp 127.0.0.1:36729}
I170527 07:30:49.879872 68114 server/server.go:737  [n2] starting https server at 127.0.0.1:55424
I170527 07:30:49.879988 68114 server/server.go:738  [n2] starting grpc/postgres server at 127.0.0.1:36729
I170527 07:30:49.880031 68114 server/server.go:739  [n2] advertising CockroachDB node at 127.0.0.1:36729
I170527 07:30:49.930032 68114 server/server.go:850  [n2] done ensuring all necessary migrations have run
I170527 07:30:49.930170 68114 server/server.go:852  [n2] serving sql connections
I170527 07:30:49.989582 68561 sql/event_log.go:101  [n2] Event: "node_join", target: 2, info: {Descriptor:{NodeID:2 Address:{NetworkField:tcp AddressField:127.0.0.1:36729} Attrs: Locality:} ClusterID:2b53681e-6f39-4ee6-91e7-d09a65a31e19 StartedAt:1495870249838435475 LastUp:1495870249838435475}
W170527 07:30:49.994612 68114 server/status/runtime.go:111  Could not parse build timestamp: parsing time "" as "2006/01/02 15:04:05": cannot parse "" as "2006"
W170527 07:30:49.996445 68114 gossip/gossip.go:1196  [n?] no incoming or outgoing connections
I170527 07:30:49.997645 68114 server/config.go:439  1 storage engine initialized
I170527 07:30:49.998911 68114 server/node.go:454  [n?] store [n0,s0] not bootstrapped
I170527 07:30:49.999031 68114 storage/stores.go:296  [n?] read 0 node addresses from persistent storage
I170527 07:30:49.999131 68114 server/node.go:608  [n?] connecting to gossip network to verify cluster ID...
I170527 07:30:50.130852 68504 server/node.go:589  [n2] bootstrapped store [n2,s2]
I170527 07:30:50.212111 68363 gossip/client.go:131  [n?] started gossip client to 127.0.0.1:41294
I170527 07:30:50.215865 68710 gossip/server.go:234  [n1] received initial cluster-verification connection from {tcp 127.0.0.1:41450}
I170527 07:30:50.220058 68114 server/node.go:633  [n?] node connected via gossip and verified as part of cluster "2b53681e-6f39-4ee6-91e7-d09a65a31e19"
I170527 07:30:50.221820 68712 storage/stores.go:312  [n?] wrote 1 node addresses to persistent storage
I170527 07:30:50.222434 68712 storage/stores.go:312  [n?] wrote 2 node addresses to persistent storage
I170527 07:30:50.233858 68114 kv/dist_sender.go:370  [n?] unable to determine this node's attributes for replica selection; node is most likely bootstrapping
I170527 07:30:50.268950 68114 server/node.go:344  [n?] new node allocated ID 3
I170527 07:30:50.269273 68114 gossip/gossip.go:297  [n3] NodeDescriptor set to node_id:3 address:<network_field:"tcp" address_field:"127.0.0.1:41450" > attrs:<> locality:<> 
I170527 07:30:50.270213 68114 server/node.go:405  [n3] node=3: started with [[]=] engine(s) and attributes []
I170527 07:30:50.272729 68114 sql/executor.go:355  [n3] creating distSQLPlanner with address {tcp 127.0.0.1:41450}
I170527 07:30:50.277215 68410 storage/stores.go:312  [n1] wrote 2 node addresses to persistent storage
I170527 07:30:50.305458 68114 server/server.go:737  [n3] starting https server at 127.0.0.1:54458
I170527 07:30:50.305600 68114 server/server.go:738  [n3] starting grpc/postgres server at 127.0.0.1:41450
I170527 07:30:50.306166 68114 server/server.go:739  [n3] advertising CockroachDB node at 127.0.0.1:41450
I170527 07:30:50.326805 68114 server/server.go:850  [n3] done ensuring all necessary migrations have run
I170527 07:30:50.326938 68114 server/server.go:852  [n3] serving sql connections
I170527 07:30:50.354651 68411 storage/stores.go:312  [n2] wrote 2 node addresses to persistent storage
I170527 07:30:50.376542 68738 server/node.go:589  [n3] bootstrapped store [n3,s3]
I170527 07:30:50.409265 68853 storage/replica_raftstorage.go:416  [n1,s1,r1/1:/M{in-ax}] generated preemptive snapshot 2af17a80 at index 59
I170527 07:30:50.469527 68680 sql/event_log.go:101  [n3] Event: "node_join", target: 3, info: {Descriptor:{NodeID:3 Address:{NetworkField:tcp AddressField:127.0.0.1:41450} Attrs: Locality:} ClusterID:2b53681e-6f39-4ee6-91e7-d09a65a31e19 StartedAt:1495870250269903446 LastUp:1495870250269903446}
I170527 07:30:50.602804 68853 storage/store.go:3352  [n1,s1,r1/1:/M{in-ax}] streamed snapshot to (n2,s2):?: kv pairs: 723, log entries: 8, rate-limit: 2.0 MiB/sec, 38ms
I170527 07:30:50.604662 68894 storage/replica_raftstorage.go:597  [n2,s2,r1/?:{-}] applying preemptive snapshot at index 59 (id=2af17a80, encoded size=181138, 1 rocksdb batches, 8 log entries)
I170527 07:30:50.607960 68894 storage/replica_raftstorage.go:605  [n2,s2,r1/?:/M{in-ax}] applied preemptive snapshot in 3ms [clear=0ms batch=0ms entries=1ms commit=1ms]
I170527 07:30:50.612164 68853 storage/replica_command.go:3538  [n1,s1,r1/1:/M{in-ax}] change replicas (ADD_REPLICA (n2,s2):2): read existing descriptor r1:/M{in-ax} [(n1,s1):1, next=2]
I170527 07:30:50.637105 68863 storage/replica.go:2836  [n1,s1,r1/1:/M{in-ax}] proposing ADD_REPLICA (n2,s2):2: [(n1,s1):1 (n2,s2):2]
I170527 07:30:50.674778 68954 storage/raft_transport.go:436  [n2] raft transport stream to node 1 established
I170527 07:30:51.200763 68962 storage/replica_raftstorage.go:416  [n1,s1,r1/1:/M{in-ax}] generated preemptive snapshot 17ae614b at index 68
I170527 07:30:51.367344 68962 storage/store.go:3352  [n1,s1,r1/1:/M{in-ax}] streamed snapshot to (n3,s3):?: kv pairs: 984, log entries: 10, rate-limit: 2.0 MiB/sec, 16ms
I170527 07:30:51.370778 68980 storage/replica_raftstorage.go:597  [n3,s3,r1/?:{-}] applying preemptive snapshot at index 68 (id=17ae614b, encoded size=207927, 1 rocksdb batches, 10 log entries)
I170527 07:30:51.374122 68980 storage/replica_raftstorage.go:605  [n3,s3,r1/?:/M{in-ax}] applied preemptive snapshot in 3ms [clear=0ms batch=0ms entries=1ms commit=1ms]
I170527 07:30:51.382287 68962 storage/replica_command.go:3538  [n1,s1,r1/1:/M{in-ax}] change replicas (ADD_REPLICA (n3,s3):3): read existing descriptor r1:/M{in-ax} [(n1,s1):1, (n2,s2):2, next=3]
I170527 07:30:51.417374 68995 storage/replica.go:2836  [n1,s1,r1/1:/M{in-ax}] proposing ADD_REPLICA (n3,s3):3: [(n1,s1):1 (n2,s2):2 (n3,s3):3]
I170527 07:30:52.377195 68986 storage/raft_transport.go:436  [n3] raft transport stream to node 1 established
I170527 07:30:52.562001 68925 storage/replica_command.go:3538  [n2,s2,r1/2:/M{in-ax}] change replicas (REMOVE_REPLICA (n1,s1):1): read existing descriptor r1:/M{in-ax} [(n1,s1):1, (n2,s2):2, (n3,s3):3, next=4]
I170527 07:30:52.623699 69058 storage/replica.go:2836  [n2,s2,r1/2:/M{in-ax}] proposing REMOVE_REPLICA (n1,s1):1: [(n3,s3):3 (n2,s2):2]
I170527 07:30:52.666704 68271 storage/store.go:2146  [replicaGC,n1,s1,r1/1:/M{in-ax}] removing replica
I170527 07:30:52.667802 68271 storage/replica.go:714  [replicaGC,n1,s1,r1/1:/M{in-ax}] removed 85 (75+10) keys in 1ms [clear=0ms commit=1ms]
E170527 07:30:52.668466 68237 util/log/crash_reporting.go:81  a panic has occurred!
E170527 07:30:52.699321 68237 util/log/crash_reporting.go:171  Reported as error 6c55b5b022fa4b0ea829fc42a42a5d8a
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x129eeea]

goroutine 68237 [running]:
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).Recover(0xc421cfa140, 0x7f05de30c350, 0xc4202a4420)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:200 +0x10d
panic(0x20d6700, 0x3103180)
	/usr/local/go/src/runtime/panic.go:489 +0x2f0
github.com/cockroachdb/cockroach/pkg/storage.(*Replica).updateProposalQuotaRaftMuLocked(0xc4204c8000, 0x7f05de30c350, 0xc420283d70, 0x1)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/replica.go:909 +0x13a
github.com/cockroachdb/cockroach/pkg/storage.(*Replica).handleRaftReadyRaftMuLocked(0xc4204c8000, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/replica.go:2997 +0x249c
github.com/cockroachdb/cockroach/pkg/storage.(*Replica).handleRaftReady(0xc4204c8000, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/replica.go:2944 +0xf5
github.com/cockroachdb/cockroach/pkg/storage.(*Store).processReady(0xc420263400, 0x1)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/store.go:3417 +0x17e
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).worker(0xc4204a6120, 0xc421cfa140)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:217 +0x342
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).Start.func2(0x7f05de30c350, 0xc4202a4420)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:168 +0x4b
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc4201cf7c0, 0xc421cfa140, 0xc42036cc00)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:215 +0x161
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:216 +0xbb

goroutine 1 [chan receive]:
testing.(*T).Run(0xc4203f0750, 0x22a59f5, 0x14, 0x23643c8, 0xc42068f901)
	/usr/local/go/src/testing/testing.go:698 +0x582
testing.runTests.func1(0xc4203f0750)
	/usr/local/go/src/testing/testing.go:882 +0xab
testing.tRunner(0xc4203f0750, 0xc42068fad0)
	/usr/local/go/src/testing/testing.go:657 +0x108
testing.runTests(0xc4201b2340, 0x311ec00, 0x1b3, 0x1b3, 0xc42068fb50)
	/usr/local/go/src/testing/testing.go:888 +0x4e1
testing.(*M).Run(0xc4205a9f28, 0x0)
	/usr/local/go/src/testing/testing.go:822 +0x1c4
github.com/cockroachdb/cockroach/pkg/storage_test.TestMain(0xc42068ff28)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/main_test.go:59 +0x308
main.main()
	github.com/cockroachdb/cockroach/pkg/storage/_test/_testmain.go:922 +0x210

goroutine 17 [syscall, 2 minutes, locked to thread]:
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:2197 +0x1

goroutine 19 [chan receive]:
github.com/cockroachdb/cockroach/pkg/util/log.(*loggingT).flushDaemon(0x35c7640)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/log/clog.go:1057 +0x85
created by github.com/cockroachdb/cockroach/pkg/util/log.init.1
	/go/src/github.com/cockroachdb/cockroach/pkg/util/log/clog.go:603 +0x13a

goroutine 5 [syscall, 2 minutes]:
os/signal.signal_recv(0x6d0101)
	/usr/local/go/src/runtime/sigqueue.go:116 +0x104
os/signal.loop()
	/usr/local/go/src/os/signal/signal_unix.go:22 +0x30
created by os/signal.init.1
	/usr/local/go/src/os/signal/signal_unix.go:28 +0x4f

goroutine 68571 [semacquire]:
sync.runtime_notifyListWait(0xc4219fdbd0, 0xc400000049)
	/usr/local/go/src/runtime/sema.go:298 +0x11a
sync.(*Cond).Wait(0xc4219fdbc0)
	/usr/local/go/src/sync/cond.go:57 +0x97
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).worker(0xc4208da2d0, 0xc420cf8a00)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:199 +0xe2
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).Start.func2(0x7f05de30c350, 0xc4209b6330)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:168 +0x4b
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc4203a23c0, 0xc420cf8a00, 0xc4201f3d60)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:215 +0x161
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:216 +0xbb

goroutine 68614 [semacquire]:
sync.runtime_notifyListWait(0xc4219fdbd0, 0xc400000031)
	/usr/local/go/src/runtime/sema.go:298 +0x11a
sync.(*Cond).Wait(0xc4219fdbc0)
	/usr/local/go/src/sync/cond.go:57 +0x97
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).worker(0xc4208da2d0, 0xc420cf8a00)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:199 +0xe2
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).Start.func2(0x7f05de30c350, 0xc42168e300)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:168 +0x4b
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc4203a2720, 0xc420cf8a00, 0xc4202b0120)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:215 +0x161
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:216 +0xbb

goroutine 68589 [semacquire]:
sync.runtime_notifyListWait(0xc4219fdbd0, 0xc400000061)
	/usr/local/go/src/runtime/sema.go:298 +0x11a
sync.(*Cond).Wait(0xc4219fdbc0)
	/usr/local/go/src/sync/cond.go:57 +0x97
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).worker(0xc4208da2d0, 0xc420cf8a00)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:199 +0xe2
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).Start.func2(0x7f05de30c350, 0xc420231d70)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:168 +0x4b
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc4203a2570, 0xc420cf8a00, 0xc420088260)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:215 +0x161
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:216 +0xbb

goroutine 68541 [select]:
github.com/cockroachdb/cockroach/pkg/sql.(*distSQLPlanner).initRunners.func1(0x7f05de30c350, 0xc4204aba40)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsql_running.go:83 +0x1cb
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc420314990, 0xc420cf8a00, 0xc420314980)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:215 +0x161
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:216 +0xbb

goroutine 68553 [select]:
github.com/cockroachdb/cockroach/pkg/sql.(*distSQLPlanner).initRunners.func1(0x7f05de30c350, 0xc420231710)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsql_running.go:83 +0x1cb
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc420314b50, 0xc420cf8a00, 0xc420314b40)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:215 +0x161
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:216 +0xbb

goroutine 68751 [select]:
github.com/cockroachdb/cockroach/pkg/sql.(*distSQLPlanner).initRunners.func1(0x7f05de30c350, 0xc4202834a0)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsql_running.go:83 +0x1cb
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc4201f48e0, 0xc42070ebe0, 0xc4201f48d0)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:215 +0x161
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:216 +0xbb

goroutine 68115 [chan receive]:
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).Start.func1(0x7f05de30c350, 0xc4202a4060)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:158 +0x74
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc4201cf510, 0xc421cfa140, 0xc42036c520)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:215 +0x161
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:216 +0xbb

goroutine 68696 [runnable]:
github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/transport.(*http2Server).keepalive(0xc4200131e0)
	/go/src/github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/transport/http2_server.go:894 +0x662
created by github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/transport.newHTTP2Server
	/go/src/github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/transport/http2_server.go:226 +0xfa9

goroutine 68832 [semacquire]:
sync.runtime_notifyListWait(0xc4215e5c10, 0xc40000001b)
	/usr/local/go/src/runtime/sema.go:298 +0x11a
sync.(*Cond).Wait(0xc4215e5c00)
	/usr/local/go/src/sync/cond.go:57 +0x97
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).worker(0xc42075b290, 0xc42070ebe0)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:199 +0xe2
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).Start.func2(0x7f05de30c350, 0xc42135e570)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:168 +0x4b
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc42038f850, 0xc42070ebe0, 0xc4202cbf20)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:215 +0x161
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:216 +0xbb

goroutine 68292 [select]:
github.com/cockroachdb/cockroach/pkg/server.(*Server).startSampleEnvironment.func1(0x7f05de30c350, 0xc4216fc480)
	/go/src/github.com/cockroachdb/cockroach/pkg/server/server.go:947 +0x1ce
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc4201e05c0, 0xc421cfa140, 0xc4203504a0)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:215 +0x161
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:216 +0xbb

goroutine 68887 [select]:
github.com/cockroachdb/cockroach/pkg/storage.(*Store).startGossip.func4(0x7f05de30c350, 0xc420f8ede0)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/store.go:1355 +0x64e
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc42038fb00, 0xc42070ebe0, 0xc42029b810)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:215 +0x161
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:216 +0xbb

goroutine 68900 [IO wait]:
net.runtime_pollWait(0x7f05de397bf0, 0x72, 0x6fb8ba)
	/usr/local/go/src/runtime/netpoll.go:164 +0x5e
net.(*pollDesc).wait(0xc420b931e8, 0x72, 0x3123fd8, 0xffffffffffffffff)
	/usr/local/go/src/net/fd_poll_runtime.go:75 +0x5b
net.(*pollDesc).waitRead(0xc420b931e8, 0xc4219f4000, 0x8000)
	/usr/local/go/src/net/fd_poll_runtime.go:80 +0x42
net.(*netFD).Read(0xc420b93180, 0xc4219f4000, 0x8000, 0x8000, 0x0, 0x312e600, 0x3123fd8)
	/usr/local/go/src/net/fd_unix.go:250 +0x22b
net.(*conn).Read(0xc420086108, 0xc4219f4000, 0x8000, 0x8000, 0x71, 0x0, 0x2366428)
	/usr/local/go/src/net/net.go:181 +0x97
net.(*TCPConn).Read(0xc420086108, 0xc4219f4000, 0x8000, 0x8000, 0x1, 0x31263c0, 0xc420078040)
	<autogenerated>:72 +0x73
github.com/cockroachdb/cockroach/vendor/github.com/cockroachdb/cmux.(*MuxConn).Read(0xc420d9ac80, 0xc4219f4000, 0x8000, 0x8000, 0xc4213d1488, 0xa150d6, 0xc4213d1488)
	/go/src/github.com/cockroachdb/cockroach/vendor/github.com/cockroachdb/cmux/cmux.go:218 +0x183
crypto/tls.(*block).readFromUntil(0xc421d4c390, 0x7f05de3a0b58, 0xc420d9ac80, 0x5, 0xc420d9ac80, 0x6b5e80)
	/usr/local/go/src/crypto/tls/conn.go:488 +0x114
crypto/tls.(*Conn).readRecord(0xc42130b180, 0x2366617, 0xc42130b2a0, 0x0)
	/usr/local/go/src/crypto/tls/conn.go:590 +0x13d
crypto/tls.(*Conn).Read(0xc42130b180, 0xc4208b0000, 0x8000, 0x8000, 0x0, 0x0, 0x0)
	/usr/local/go/src/crypto/tls/conn.go:1134 +0x190
bufio.(*Reader).Read(0xc421e76900, 0xc421a0e118, 0x9, 0x9, 0x6ac9f2, 0x1d54f80, 0x7f05bef87208)
	/usr/local/go/src/bufio/bufio.go:213 +0x7e7
io.ReadAtLeast(0x3125cc0, 0xc421e76900, 0xc421a0e118, 0x9, 0x9, 0x9, 0x69d06c, 0xc4213d1a10, 0xc4213d1a10)
	/usr/local/go/src/io/io.go:307 +0xb7
io.ReadFull(0x3125cc0, 0xc421e76900, 0xc421a0e118, 0x9, 0x9, 0x0, 0x1, 0xc4201eb4c0)
	/usr/local/go/src/io/io.go:325 +0x73
github.com/cockroachdb/cockroach/vendor/golang.org/x/net/http2.readFrameHeader(0xc421a0e118, 0x9, 0x9, 0x3125cc0, 0xc421e76900, 0x0, 0xc400000000, 0xd28c17, 0xc420a3cb00)
	/go/src/github.com/cockroachdb/cockroach/vendor/golang.org/x/net/http2/frame.go:237 +0xa3
github.com/cockroachdb/cockroach/vendor/golang.org/x/net/http2.(*Framer).ReadFrame(0xc421a0e0e0, 0x0, 0x31263c0, 0xc420078040, 0xc42172f780)
	/go/src/github.com/cockroachdb/cockroach/vendor/golang.org/x/net/http2/frame.go:492 +0x118
github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/transport.(*framer).readFrame(0xc422474a80, 0xc422474ab0, 0xc422474ab0, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/transport/http_util.go:608 +0x53
github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/transport.(*http2Server).HandleStreams(0xc420c8d340, 0xc422474c00, 0x2365810)
	/go/src/github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/transport/http2_server.go:375 +0x3e6
github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc.(*Server).serveStreams(0xc420edca20, 0x3145560, 0xc420c8d340)
	/go/src/github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/server.go:545 +0x1e8
github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc.(*Server).serveHTTP2Transport(0xc420edca20, 0x3146100, 0xc42130b180, 0x312da80, 0xc42048f080)
	/go/src/github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/server.go:526 +0x6f9
github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc.(*Server).handleRawConn(0xc420edca20, 0x3147300, 0xc420d9ac80)
	/go/src/github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/server.go:493 +0x5f4
created by github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc.(*Server).Serve
	/go/src/github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/server.go:462 +0x69c

goroutine 68794 [select]:
github.com/cockroachdb/cockroach/pkg/storage.(*baseQueue).processLoop.func1(0x7f05de30c350, 0xc420af3170)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/queue.go:490 +0x468
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc42036ef90, 0xc42070ebe0, 0xc420281c80)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:215 +0x161
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:216 +0xbb

goroutine 68638 [select]:
github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/transport.(*http2Client).controller(0xc4207ea000)
	/go/src/github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/transport/http2_client.go:1168 +0x912
created by github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/transport.newHTTP2Client
	/go/src/github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/transport/http2_client.go:297 +0x1692

goroutine 68373 [IO wait]:
net.runtime_pollWait(0x7f05de3981f0, 0x72, 0x6fb8ba)
	/usr/local/go/src/runtime/netpoll.go:164 +0x5e
net.(*pollDesc).wait(0xc4200ba148, 0x72, 0x3123fd8, 0xffffffffffffffff)
	/usr/local/go/src/net/fd_poll_runtime.go:75 +0x5b
net.(*pollDesc).waitRead(0xc4200ba148, 0xc4208e6000, 0x400)
	/usr/local/go/src/net/fd_poll_runtime.go:80 +0x42
net.(*netFD).Read(0xc4200ba0e0, 0xc4208e6000, 0x400, 0x400, 0x0, 0x312e600, 0x3123fd8)
	/usr/local/go/src/net/fd_unix.go:250 +0x22b
net.(*conn).Read(0xc42000e098, 0xc4208e6000, 0x400, 0x400, 0x102, 0x6ac5f4, 0x1d56480)
	/usr/local/go/src/net/net.go:181 +0x97
net.(*TCPConn).Read(0xc42000e098, 0xc4208e6000, 0x400, 0x400, 0xc4213bb6e8, 0xa150d6, 0xc4213bb6e8)
	<autogenerated>:72 +0x73
crypto/tls.(*block).readFromUntil(0xc4202d01b0, 0x7f05da985aa8, 0xc42000e098, 0x5, 0xc42000e098, 0x6b5e80)
	/usr/local/go/src/crypto/tls/conn.go:488 +0x114
crypto/tls.(*Conn).readRecord(0xc4201dee00, 0x2366617, 0xc4201def20, 0xc42036eb70)
	/usr/local/go/src/crypto/tls/conn.go:590 +0x13d
crypto/tls.(*Conn).Read(0xc4201dee00, 0xc420702000, 0x8000, 0x8000, 0x0, 0x0, 0x0)
	/usr/local/go/src/crypto/tls/conn.go:1134 +0x190
bufio.(*Reader).Read(0xc421903b60, 0xc420204498, 0x9, 0x9, 0x69ce1b, 0xc420020600, 0xc420020600)
	/usr/local/go/src/bufio/bufio.go:213 +0x7e7
io.ReadAtLeast(0x3125cc0, 0xc421903b60, 0xc420204498, 0x9, 0x9, 0x9, 0x0, 0x0, 0xc4213bbc50)
	/usr/local/go/src/io/io.go:307 +0xb7
io.ReadFull(0x3125cc0, 0xc421903b60, 0xc420204498, 0x9, 0x9, 0x6efaa3, 0xc42006bd40, 0xffffffff)
	/usr/local/go/src/io/io.go:325 +0x73
github.com/cockroachdb/cockroach/vendor/golang.org/x/net/http2.readFrameHeader(0xc420204498, 0x9, 0x9, 0x3125cc0, 0xc421903b60, 0x0, 0x0, 0xc4213bbd70, 0x69d0f4)
	/go/src/github.com/cockroachdb/cockroach/vendor/golang.org/x/net/http2/frame.go:237 +0xa3
github.com/cockroachdb/cockroach/vendor/golang.org/x/net/http2.(*Framer).ReadFrame(0xc420204460, 0x0, 0x31263c0, 0xc420078040, 0x0)
	/go/src/github.com/cockroachdb/cockroach/vendor/golang.org/x/net/http2/frame.go:492 +0x118
github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/transport.(*framer).readFrame(0xc4216fdc20, 0xc4214c5bf0, 0xc4214c5b00, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/transport/http_util.go:608 +0x53
github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/transport.(*http2Client).reader(0xc4213c8300)
	/go/src/github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/transport/http2_client.go:1095 +0x15b
created by github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/transport.newHTTP2Client
	/go/src/github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/transport/http2_client.go:267 +0x12ec

goroutine 68806 [semacquire]:
sync.runtime_notifyListWait(0xc4215e5c10, 0xc400000044)
	/usr/local/go/src/runtime/sema.go:298 +0x11a
sync.(*Cond).Wait(0xc4215e5c00)
	/usr/local/go/src/sync/cond.go:57 +0x97
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).worker(0xc42075b290, 0xc42070ebe0)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:199 +0xe2
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).Start.func2(0x7f05de30c350, 0xc4212e81b0)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:168 +0x4b
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc4202ae3f0, 0xc42070ebe0, 0xc420351d60)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:215 +0x161
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:216 +0xbb

goroutine 68889 [select]:
github.com/cockroachdb/cockroach/pkg/storage.(*Store).startGossip.func4(0x7f05de30c350, 0xc420f8ee10)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/store.go:1355 +0x64e
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc42038fb20, 0xc42070ebe0, 0xc42029b8b0)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:215 +0x161
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:216 +0xbb

goroutine 68254 [semacquire]:
sync.runtime_notifyListWait(0xc4206e0510, 0xc40000007a)
	/usr/local/go/src/runtime/sema.go:298 +0x11a
sync.(*Cond).Wait(0xc4206e0500)
	/usr/local/go/src/sync/cond.go:57 +0x97
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).worker(0xc4204a6120, 0xc421cfa140)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:199 +0xe2
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).Start.func2(0x7f05de30c350, 0xc4203d24b0)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:168 +0x4b
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc4201cf8e0, 0xc421cfa140, 0xc42036ce60)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:215 +0x161
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:216 +0xbb

goroutine 68690 [select]:
github.com/cockroachdb/cockroach/pkg/gossip.(*Gossip).bootstrap.func1(0x7f05de30c350, 0xc42085b200)
	/go/src/github.com/cockroachdb/cockroach/pkg/gossip/gossip.go:1064 +0x5e0
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc42020eba0, 0xc42070ebe0, 0xc42020eb90)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:215 +0x161
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:216 +0xbb

goroutine 68768 [select]:
github.com/cockroachdb/cockroach/pkg/sql.(*distSQLPlanner).initRunners.func1(0x7f05de30c350, 0xc420425ad0)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsql_running.go:83 +0x1cb
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc4201f4c40, 0xc42070ebe0, 0xc4201f4c30)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:215 +0x161
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:216 +0xbb

goroutine 68428 [select]:
github.com/cockroachdb/cockroach/pkg/storage.(*baseQueue).processLoop.func1(0x7f05de30c350, 0xc421ef7770)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/queue.go:490 +0x468
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc4203029c0, 0xc420cf8a00, 0xc42031a740)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:215 +0x161
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:216 +0xbb

goroutine 68323 [select]:
github.com/cockroachdb/cockroach/pkg/sql.(*distSQLPlanner).initRunners.func1(0x7f05de30c350, 0xc4213cc090)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsql_running.go:83 +0x1cb
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc4201e0a10, 0xc421cfa140, 0xc4201e09f0)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:215 +0x161
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:216 +0xbb

goroutine 68617 [semacquire]:
sync.runtime_notifyListWait(0xc4219fdbd0, 0xc40000005c)
	/usr/local/go/src/runtime/sema.go:298 +0x11a
sync.(*Cond).Wait(0xc4219fdbc0)
	/usr/local/go/src/sync/cond.go:57 +0x97
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).worker(0xc4208da2d0, 0xc420cf8a00)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:199 +0xe2
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).Start.func2(0x7f05de30c350, 0xc42168e390)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:168 +0x4b
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc4203a2750, 0xc420cf8a00, 0xc4202b01a0)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:215 +0x161
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:216 +0xbb

goroutine 68449 [select]:
github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/transport.(*http2Server).keepalive(0xc420c8d600)
	/go/src/github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/transport/http2_server.go:894 +0x662
created by github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/transport.newHTTP2Server
	/go/src/github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/transport/http2_server.go:226 +0xfa9

goroutine 68839 [semacquire]:
sync.runtime_notifyListWait(0xc4215e5c10, 0xc400000019)
	/usr/local/go/src/runtime/sema.go:298 +0x11a
sync.(*Cond).Wait(0xc4215e5c00)
	/usr/local/go/src/sync/cond.go:57 +0x97
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).worker(0xc42075b290, 0xc42070ebe0)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:199 +0xe2
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).Start.func2(0x7f05de30c350, 0xc42135e510)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:168 +0x4b
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc42038f8d0, 0xc42070ebe0, 0xc4203120a0)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:215 +0x161
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:216 +0xbb

goroutine 68477 [chan receive]:
github.com/cockroachdb/cockroach/vendor/github.com/cockroachdb/cmux.(*muxListener).Accept(0xc420331080, 0x23657d8, 0xc420edca20, 0x3147300, 0xc420d9ac80)
	<autogenerated>:9 +0x9f
github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc.(*Server).Serve(0xc420edca20, 0x313d400, 0xc420331080, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/server.go:432 +0x1f8
github.com/cockroachdb/cockroach/pkg/server.(*Server).Start.func7(0x7f05de30c350, 0xc4207ede00)
	/go/src/github.com/cockroachdb/cockroach/pkg/server/server.go:559 +0x8d
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc42026f000, 0xc420cf8a00, 0xc420331260)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:215 +0x161
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:216 +0xbb

goroutine 68500 [IO wait]:
net.runtime_pollWait(0x7f05da8c4488, 0x72, 0x6fb8ba)
	/usr/local/go/src/runtime/netpoll.go:164 +0x5e
net.(*pollDesc).wait(0xc4210a1728, 0x72, 0x3123fd8, 0xffffffffffffffff)
	/usr/local/go/src/net/fd_poll_runtime.go:75 +0x5b
net.(*pollDesc).waitRead(0xc4210a1728, 0xc420e00000, 0x8000)
	/usr/local/go/src/net/fd_poll_runtime.go:80 +0x42
net.(*netFD).Read(0xc4210a16c0, 0xc420e00000, 0x8000, 0x8000, 0x0, 0x312e600, 0x3123fd8)
	/usr/local/go/src/net/fd_unix.go:250 +0x22b
net.(*conn).Read(0xc42000e278, 0xc420e00000, 0x8000, 0x8000, 0x248, 0x0, 0x2366428)
	/usr/local/go/src/net/net.go:181 +0x97
net.(*TCPConn).Read(0xc42000e278, 0xc420e00000, 0x8000, 0x8000, 0x1, 0x31263c0, 0xc420078040)
	<autogenerated>:72 +0x73
github.com/cockroachdb/cockroach/vendor/github.com/cockroachdb/cmux.(*MuxConn).Read(0xc4203e1a40, 0xc420e00000, 0x8000, 0x8000, 0xc420d19488, 0xa150d6, 0xc420d19488)
	/go/src/github.com/cockroachdb/cockroach/vendor/github.com/cockroachdb/cmux/cmux.go:218 +0x183
crypto/tls.(*block).readFromUntil(0xc4213b66f0, 0x7f05de3a0b58, 0xc4203e1a40, 0x5, 0xc4203e1a40, 0x0)
	/usr/local/go/src/crypto/tls/conn.go:488 +0x114
crypto/tls.(*Conn).readRecord(0xc4217bc700, 0x2366617, 0xc4217bc820, 0xc420e0000d)
	/usr/local/go/src/crypto/tls/conn.go:590 +0x13d
crypto/tls.(*Conn).Read(0xc4217bc700, 0xc421966000, 0x8000, 0x8000, 0x0, 0x0, 0x0)
	/usr/local/go/src/crypto/tls/conn.go:1134 +0x190
bufio.(*Reader).Read(0xc420dffce0, 0xc421962118, 0x9, 0x9, 0x6ac9f2, 0x1d54f80, 0x7f05d89de3c8)
	/usr/local/go/src/bufio/bufio.go:213 +0x7e7
io.ReadAtLeast(0x3125cc0, 0xc420dffce0, 0xc421962118, 0x9, 0x9, 0x9, 0x69d06c, 0xc420d19a10, 0xc420d19a10)
	/usr/local/go/src/io/io.go:307 +0xb7
io.ReadFull(0x3125cc0, 0xc420dffce0, 0xc421962118, 0x9, 0x9, 0xc420670001, 0x7f05de458e10, 0x0)
	/usr/local/go/src/io/io.go:325 +0x73
github.com/cockroachdb/cockroach/vendor/golang.org/x/net/http2.readFrameHeader(0xc421962118, 0x9, 0x9, 0x3125cc0, 0xc420dffce0, 0x0, 0xc400000000, 0xd28c17, 0xc42082c4b0)
	/go/src/github.com/cockroachdb/cockroach/vendor/golang.org/x/net/http2/frame.go:237 +0xa3
github.com/cockroachdb/cockroach/vendor/golang.org/x/net/http2.(*Framer).ReadFrame(0xc4219620e0, 0x3130a40, 0xc42082c4b0, 0x0, 0xc420a3d300)
	/go/src/github.com/cockroachdb/cockroach/vendor/golang.org/x/net/http2/frame.go:492 +0x118
github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/transport.(*framer).readFrame(0xc42082c480, 0xc42082c4b0, 0xc42082c4b0, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/transport/http_util.go:608 +0x53
github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/transport.(*http2Server).HandleStreams(0xc420c8d600, 0xc42082c600, 0x2365810)
	/go/src/github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/transport/http2_server.go:375 +0x3e6
github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc.(*Server).serveStreams(0xc4213b2480, 0x3145560, 0xc420c8d600)
	/go/src/github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/server.go:545 +0x1e8
github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc.(*Server).serveHTTP2Transport(0xc4213b2480, 0x3146100, 0xc4217bc700, 0x312da80, 0xc420383a20)
	/go/src/github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/server.go:526 +0x6f9
github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc.(*Server).handleRawConn(0xc4213b2480, 0x3147300, 0xc4203e1a40)
	/go/src/github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/server.go:493 +0x5f4
created by github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc.(*Server).Serve
	/go/src/github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/server.go:462 +0x69c

goroutine 68512 [select]:
github.com/cockroachdb/cockroach/pkg/sql.(*distSQLPlanner).initRunners.func1(0x7f05de30c350, 0xc42085a090)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsql_running.go:83 +0x1cb
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc4203147f0, 0xc420cf8a00, 0xc4203147e0)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:215 +0x161
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:216 +0xbb

goroutine 68335 [select]:
github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/transport.(*http2Client).keepalive(0xc4213c8300)
	/go/src/github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/transport/http2_client.go:1214 +0x6e6
created by github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/transport.newHTTP2Client
	/go/src/github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/transport/http2_client.go:299 +0x1789

goroutine 68805 [semacquire]:
sync.runtime_notifyListWait(0xc4215e5c10, 0xc400000043)
	/usr/local/go/src/runtime/sema.go:298 +0x11a
sync.(*Cond).Wait(0xc4215e5c00)
	/usr/local/go/src/sync/cond.go:57 +0x97
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).worker(0xc42075b290, 0xc42070ebe0)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:199 +0xe2
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).Start.func2(0x7f05de30c350, 0xc420af2660)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:168 +0x4b
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc4202ae3e0, 0xc42070ebe0, 0xc420351d20)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:215 +0x161
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:216 +0xbb

goroutine 68106 [select]:
github.com/cockroachdb/cockroach/pkg/server.(*Server).refreshSettings.func2(0x7f05de30c350, 0xc420b98090)
	/go/src/github.com/cockroachdb/cockroach/pkg/server/settingsworker.go:113 +0x48f
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc4203dfcf0, 0xc421cfa140, 0xc4203056e0)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:215 +0x161
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:216 +0xbb

goroutine 68294 [select]:
github.com/cockroachdb/cockroach/pkg/server.(*Node).startWriteSummaries.func1(0x7f05de30c350, 0xc4216fc510)
	/go/src/github.com/cockroachdb/cockroach/pkg/server/node.go:739 +0x3b5
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc4201e05f0, 0xc421cfa140, 0xc4203504c0)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:215 +0x161
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:216 +0xbb

goroutine 68606 [semacquire]:
sync.runtime_notifyListWait(0xc4219fdbd0, 0xc400000036)
	/usr/local/go/src/runtime/sema.go:298 +0x11a
sync.(*Cond).Wait(0xc4219fdbc0)
	/usr/local/go/src/sync/cond.go:57 +0x97
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).worker(0xc4208da2d0, 0xc420cf8a00)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:199 +0xe2
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).Start.func2(0x7f05de30c350, 0xc4209b6630)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:168 +0x4b
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc4203a26a0, 0xc420cf8a00, 0xc420088b60)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:215 +0x161
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:216 +0xbb

goroutine 68308 [select]:
github.com/cockroachdb/cockroach/pkg/sql.(*distSQLPlanner).initRunners.func1(0x7f05de30c350, 0xc420d1b5c0)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsql_running.go:83 +0x1cb
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc4201e07c0, 0xc421cfa140, 0xc4201e07b0)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:215 +0x161
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:216 +0xbb

goroutine 69017 [select]:
github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/transport.(*recvBufferReader).Read(0xc421913080, 0xc420369630, 0x5, 0x5, 0x0, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/transport/transport.go:145 +0x70a
github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/transport.(*Stream).Read(0xc420af4400, 0xc420369630, 0x5, 0x5, 0x1d54f80, 0x7f05ce775ec8, 0xc4204a6138)
	/go/src/github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/transport/transport.go:328 +0x79
io.ReadAtLeast(0x312aac0, 0xc420af4400, 0xc420369630, 0x5, 0x5, 0x5, 0xc4215d9b48, 0x6b16f1, 0xc420545860)
	/usr/local/go/src/io/io.go:307 +0xb7
io.ReadFull(0x312aac0, 0xc420af4400, 0xc420369630, 0x5, 0x5, 0x6ef638, 0xc4206e0510, 0xc4215d9bc0)
	/usr/local/go/src/io/io.go:325 +0x73
github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc.(*parser).recvMsg(0xc420369620, 0x7fffffff, 0x34, 0x34, 0xc4215d9d18, 0x69ce1b, 0x6840ad, 0xc41ffed572)
	/go/src/github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/rpc_util.go:255 +0xa0
github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc.recv(0xc420369620, 0x313da00, 0x3f88010, 0xc420af4400, 0x3132580, 0x3f88010, 0x21bdce0, 0xc4202551a0, 0x7fffffff, 0x0, ...)
	/go/src/github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/rpc_util.go:351 +0x61
github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc.(*serverStream).RecvMsg(0xc420739280, 0x21bdce0, 0xc4202551a0, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/stream.go:623 +0x1cf
github.com/cockroachdb/cockroach/pkg/storage.(*multiRaftRaftMessageBatchServer).Recv(0xc4202dcee0, 0x7f05de30c350, 0xc420851a10, 0xc421180900)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/raft.pb.go:397 +0x86
github.com/cockroachdb/cockroach/pkg/storage.(*RaftTransport).RaftMessageBatch.func1.1.1(0x31471e0, 0xc4202dcee0, 0xc420662180, 0x7f05de30c350, 0xc420851a10, 0x18, 0xc42100a778)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/raft_transport.go:300 +0x61
github.com/cockroachdb/cockroach/pkg/storage.(*RaftTransport).RaftMessageBatch.func1.1(0x7f05de30c350, 0xc420851a10)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/raft_transport.go:323 +0x75
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc4202dcf00, 0xc421cfa140, 0xc420851950)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:215 +0x161
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:216 +0xbb

goroutine 68820 [semacquire]:
sync.runtime_notifyListWait(0xc4215e5c10, 0xc40000002b)
	/usr/local/go/src/runtime/sema.go:298 +0x11a
sync.(*Cond).Wait(0xc4215e5c00)
	/usr/local/go/src/sync/cond.go:57 +0x97
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).worker(0xc42075b290, 0xc42070ebe0)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:199 +0xe2
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).Start.func2(0x7f05de30c350, 0xc4212e86c0)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:168 +0x4b
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc42038f790, 0xc42070ebe0, 0xc4202cbb80)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:215 +0x161
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:216 +0xbb

goroutine 68401 [select]:
github.com/cockroachdb/cockroach/pkg/security.(*CertificateManager).RegisterSignalHandler.func1(0xc420cf8a00, 0xc421268a80, 0xc4200d1ce0)
	/go/src/github.com/cockroachdb/cockroach/pkg/security/certificate_manager.go:127 +0x511
created by github.com/cockroachdb/cockroach/pkg/security.(*CertificateManager).RegisterSignalHandler
	/go/src/github.com/cockroachdb/cockroach/pkg/security/certificate_manager.go:140 +0xf1

goroutine 68566 [semacquire]:
sync.runtime_notifyListWait(0xc4219fdbd0, 0xc400000046)
	/usr/local/go/src/runtime/sema.go:298 +0x11a
sync.(*Cond).Wait(0xc4219fdbc0)
	/usr/local/go/src/sync/cond.go:57 +0x97
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).worker(0xc4208da2d0, 0xc420cf8a00)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:199 +0xe2
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).Start.func2(0x7f05de30c350, 0xc421ef76e0)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:168 +0x4b
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc4203a2360, 0xc420cf8a00, 0xc4201f39e0)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:215 +0x161
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:216 +0xbb

goroutine 68256 [semacquire]:
sync.runtime_notifyListWait(0xc4206e0510, 0xc40000007c)
	/usr/local/go/src/runtime/sema.go:298 +0x11a
sync.(*Cond).Wait(0xc4206e0500)
	/usr/local/go/src/sync/cond.go:57 +0x97
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).worker(0xc4204a6120, 0xc421cfa140)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:199 +0xe2
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).Start.func2(0x7f05de30c350, 0xc4203d2540)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:168 +0x4b
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc4201cf900, 0xc421cfa140, 0xc42036cea0)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:215 +0x161
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:216 +0xbb

goroutine 68658 [chan receive]:
database/sql.(*DB).connectionOpener(0xc42070eb40)
	/usr/local/go/src/database/sql/sql.go:837 +0x6e
created by database/sql.Open
	/usr/local/go/src/database/sql/sql.go:582 +0x318

goroutine 68430 [select]:
github.com/cockroachdb/cockroach/pkg/storage.(*baseQueue).processLoop.func1(0x7f05de30c350, 0xc421ef77a0)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/queue.go:490 +0x468
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc4203029e0, 0xc420cf8a00, 0xc42031a7a0)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:215 +0x161
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:216 +0xbb

goroutine 68515 [select]:
github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/transport.(*recvBufferReader).Read(0xc42172fc40, 0xc4201f3b90, 0x5, 0x5, 0x0, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/transport/transport.go:145 +0x70a
github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/transport.(*Stream).Read(0xc420768600, 0xc4201f3b90, 0x5, 0x5, 0x679aa3, 0xc421412bd0, 0x20c24a0)
	/go/src/github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/transport/transport.go:328 +0x79
io.ReadAtLeast(0x312aac0, 0xc420768600, 0xc4201f3b90, 0x5, 0x5, 0x5, 0x11991b7, 0x30dd0fed, 0xc421412be8)
	/usr/local/go/src/io/io.go:307 +0xb7
io.ReadFull(0x312aac0, 0xc420768600, 0xc4201f3b90, 0x5, 0x5, 0xc, 0x0, 0xc4207b3c08)
	/usr/local/go/src/io/io.go:325 +0x73
github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc.(*parser).recvMsg(0xc4201f3b80, 0x7fffffff, 0x6ef17e, 0xc420570540, 0x6d127c, 0x6efaa3, 0x69d06c, 0xc4207b3c60)
	/go/src/github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/rpc_util.go:255 +0xa0
github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc.recv(0xc4201f3b80, 0x313da00, 0x3f88010, 0xc420768600, 0x3132580, 0x3f88010, 0x21b4f20, 0xc4214311d0, 0x7fffffff, 0x0, ...)
	/go/src/github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/rpc_util.go:351 +0x61
github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc.(*clientStream).RecvMsg(0xc420c8d8c0, 0x21b4f20, 0xc4214311d0, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/stream.go:379 +0x1da
github.com/cockroachdb/cockroach/pkg/gossip.(*gossipGossipClient).Recv(0xc4202434d0, 0x7f05de30c350, 0xc42082c960, 0xc42073c780)
	/go/src/github.com/cockroachdb/cockroach/pkg/gossip/gossip.pb.go:194 +0x86
github.com/cockroachdb/cockroach/pkg/gossip.(*client).gossip.func2.1(0x3146160, 0xc4202434d0, 0xc421090f70, 0x7f05de30c350, 0xc42082c960, 0xc42073c780, 0xc420d34768, 0x69c742)
	/go/src/github.com/cockroachdb/cockroach/pkg/gossip/client.go:313 +0x43
github.com/cockroachdb/cockroach/pkg/gossip.(*client).gossip.func2(0x7f05de30c350, 0xc42082c960)
	/go/src/github.com/cockroachdb/cockroach/pkg/gossip/client.go:321 +0xe6
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc4202435a0, 0xc420cf8a00, 0xc42172fcc0)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:215 +0x161
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:216 +0xbb

goroutine 68506 [select]:
github.com/cockroachdb/cockroach/pkg/server.(*Node).startGossip.func1(0x7f05de30c350, 0xc421ef69c0)
	/go/src/github.com/cockroachdb/cockroach/pkg/server/node.go:661 +0x5cc
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc420314620, 0xc420cf8a00, 0xc4203985a0)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:215 +0x161
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:216 +0xbb

goroutine 68218 [semacquire]:
sync.runtime_notifyListWait(0xc4206e0510, 0xc400000095)
	/usr/local/go/src/runtime/sema.go:298 +0x11a
sync.(*Cond).Wait(0xc4206e0500)
	/usr/local/go/src/sync/cond.go:57 +0x97
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).worker(0xc4204a6120, 0xc421cfa140)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:199 +0xe2
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).Start.func2(0x7f05de30c350, 0xc42007df80)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:168 +0x4b
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc4201cf680, 0xc421cfa140, 0xc42036c8e0)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:215 +0x161
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:216 +0xbb

goroutine 69077 [runnable]:
github.com/cockroachdb/cockroach/pkg/storage_test.TestGossipFirstRange.func1(0xc4201eb650, 0xb, 0xc420269a20, 0x1f, 0x20, 0x14c26611bf6bf478, 0x0)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/gossip_test.go:56 +0x177
github.com/cockroachdb/cockroach/pkg/gossip.(*infoStore).runCallbacks.func1()
	/go/src/github.com/cockroachdb/cockroach/pkg/gossip/infostore.go:277 +0x10b
github.com/cockroachdb/cockroach/pkg/gossip.(*infoStore).runCallbacks.func2(0x7f05de307058, 0xc420078d68)
	/go/src/github.com/cockroachdb/cockroach/pkg/gossip/infostore.go:299 +0x161
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunAsyncTask.func1(0xc421cfa140, 0x7f05de307058, 0xc420078d68, 0x2e646e5, 0x13, 0x12d, 0x0, 0x0, 0xc4201eb7e0)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:294 +0x101
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunAsyncTask
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:295 +0x173

goroutine 68833 [semacquire]:
sync.runtime_notifyListWait(0xc4215e5c10, 0xc40000001f)
	/usr/local/go/src/runtime/sema.go:298 +0x11a
sync.(*Cond).Wait(0xc4215e5c00)
	/usr/local/go/src/sync/cond.go:57 +0x97
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).worker(0xc42075b290, 0xc42070ebe0)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:199 +0xe2
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).Start.func2(0x7f05de30c350, 0xc42135e630)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:168 +0x4b
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc42038f860, 0xc42070ebe0, 0xc4202cbf60)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:215 +0x161
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:216 +0xbb

goroutine 68757 [select]:
github.com/cockroachdb/cockroach/pkg/sql.(*distSQLPlanner).initRunners.func1(0x7f05de30c350, 0xc420283350)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsql_running.go:83 +0x1cb
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc4201f4a00, 0xc42070ebe0, 0xc4201f49d0)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:215 +0x161
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:216 +0xbb

goroutine 68234 [semacquire]:
sync.runtime_notifyListWait(0xc4206e0510, 0xc4000000a7)
	/usr/local/go/src/runtime/sema.go:298 +0x11a
sync.(*Cond).Wait(0xc4206e0500)
	/usr/local/go/src/sync/cond.go:57 +0x97
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).worker(0xc4204a6120, 0xc421cfa140)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:199 +0xe2
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).Start.func2(0x7f05de30c350, 0xc4202a4330)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:168 +0x4b
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc4201cf790, 0xc421cfa140, 0xc42036cba0)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:215 +0x161
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:216 +0xbb

goroutine 68576 [semacquire]:
sync.runtime_notifyListWait(0xc4219fdbd0, 0xc400000038)
	/usr/local/go/src/runtime/sema.go:298 +0x11a
sync.(*Cond).Wait(0xc4219fdbc0)
	/usr/local/go/src/sync/cond.go:57 +0x97
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).worker(0xc4208da2d0, 0xc420cf8a00)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:199 +0xe2
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).Start.func2(0x7f05de30c350, 0xc42168e180)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:168 +0x4b
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc4203a2420, 0xc420cf8a00, 0xc4201f3e80)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:215 +0x161
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:216 +0xbb

goroutine 68507 [select]:
github.com/cockroachdb/cockroach/pkg/server.(*Server).startSampleEnvironment.func1(0x7f05de30c350, 0xc4216fd950)
	/go/src/github.com/cockroachdb/cockroach/pkg/server/server.go:947 +0x1ce
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc420314760, 0xc420cf8a00, 0xc420398640)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:215 +0x161
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:216 +0xbb

goroutine 68104 [select]:
github.com/cockroachdb/cockroach/pkg/kv.(*TxnCoordSender).printStatsLoop(0xc4201848f0, 0x7f05de30c350, 0xc420b98030)
	/go/src/github.com/cockroachdb/cockroach/pkg/kv/txn_coord_sender.go:255 +0xfce
github.com/cockroachdb/cockroach/pkg/kv.NewTxnCoordSender.func1(0x7f05de30c350, 0xc420b98030)
	/go/src/github.com/cockroachdb/cockroach/pkg/kv/txn_coord_sender.go:239 +0x56
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc4203dfa60, 0xc421cfa140, 0xc4203dfa50)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:215 +0x161
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:216 +0xbb

goroutine 68260 [semacquire]:
sync.runtime_Semacquire(0xc4204a61a4)
	/usr/local/go/src/runtime/sema.go:47 +0x34
sync.(*WaitGroup).Wait(0xc4204a6198)
	/usr/local/go/src/sync/waitgroup.go:131 +0xc2
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).Wait(0xc4204a6120, 0x7f05de30c350, 0xc4203d25d0)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:174 +0x3f
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).Wait-fm(0x7f05de30c350, 0xc4203d25d0)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/store.go:3476 +0x56
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc4201cf960, 0xc421cfa140, 0xc4201cf950)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:215 +0x161
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:216 +0xbb

goroutine 68510 [select]:
github.com/cockroachdb/cockroach/pkg/sql.(*distSQLPlanner).initRunners.func1(0x7f05de30c350, 0xc4216fd920)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsql_running.go:83 +0x1cb
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc4203147b0, 0xc420cf8a00, 0xc4203147a0)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:215 +0x161
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:216 +0xbb

goroutine 68479 [chan receive]:
github.com/cockroachdb/cockroach/pkg/gossip.(*server).start.func3(0x7f05de30c350, 0xc420a73200)
	/go/src/github.com/cockroachdb/cockroach/pkg/gossip/server.go:386 +0x94
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc42026f150, 0xc420cf8a00, 0xc420331360)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:215 +0x161
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:216 +0xbb

goroutine 68328 [select]:
github.com/cockroachdb/cockroach/pkg/sql.(*Executor).Start.func1(0x7f05de30c350, 0xc4213cc3c0)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/executor.go:372 +0x19d
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc4201e0ad0, 0xc421cfa140, 0xc420350540)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:215 +0x161
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:216 +0xbb

goroutine 68760 [select]:
github.com/cockroachdb/cockroach/pkg/sql.(*SchemaChangeManager).Start.func1(0x7f05de30c350, 0xc420283c80)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/schema_changer.go:807 +0x1f0c
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc4201f4a70, 0xc42070ebe0, 0xc4202de820)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:215 +0x161
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:216 +0xbb

goroutine 68967 [IO wait]:
```

### LINKED ISSUE #16193: storage: TestReplicaRemovalCampaign failed under stress
SHA: https://github.com/cockroachdb/cockroach/commits/db8da7c6f9551b69fd464803133db170001e3470

Parameters:
```
TAGS=deadlock
GOFLAGS=
```

Stress build found a failed test: https://teamcity.cockroachdb.com/viewLog.html?buildId=259106&tab=buildLog

```

I170528 08:12:50.809264 1009177 gossip/gossip.go:297  [n1] NodeDescriptor set to node_id:1 address:<network_field:"tcp" address_field:"127.0.0.1:48425" > attrs:<> locality:<> 
W170528 08:12:50.821005 1009177 gossip/gossip.go:1196  [n2] no incoming or outgoing connections
I170528 08:12:50.821258 1009177 storage/store.go:1256  [n2,s2]: failed initial metrics computation: [n2,s2]: system config not yet available
I170528 08:12:50.821355 1009177 gossip/gossip.go:297  [n2] NodeDescriptor set to node_id:2 address:<network_field:"tcp" address_field:"127.0.0.1:58422" > attrs:<> locality:<> 
I170528 08:12:50.822734 1012550 gossip/client.go:131  [n2] started gossip client to 127.0.0.1:48425
I170528 08:12:50.841234 1013097 storage/replica_raftstorage.go:416  [s1,r1/1:/M{in-ax}] generated preemptive snapshot 015e7678 at index 14
I170528 08:12:50.842014 1013097 storage/store.go:3352  [s1,r1/1:/M{in-ax}] streamed snapshot to (n2,s2):?: kv pairs: 32, log entries: 4, rate-limit: 2.0 MiB/sec, 1ms
I170528 08:12:50.842361 1013136 storage/replica_raftstorage.go:597  [s2,r1/?:{-}] applying preemptive snapshot at index 14 (id=015e7678, encoded size=5089, 1 rocksdb batches, 4 log entries)
I170528 08:12:50.842932 1013136 storage/replica_raftstorage.go:605  [s2,r1/?:/M{in-ax}] applied preemptive snapshot in 0ms [clear=0ms batch=0ms entries=0ms commit=0ms]
I170528 08:12:50.844007 1013097 storage/replica_command.go:3538  [s1,r1/1:/M{in-ax}] change replicas (ADD_REPLICA (n2,s2):2): read existing descriptor r1:/M{in-ax} [(n1,s1):1, next=2]
I170528 08:12:50.846776 1013387 storage/replica.go:2836  [s1,r1/1:/M{in-ax}] proposing ADD_REPLICA (n2,s2):2: [(n1,s1):1 (n2,s2):2]
I170528 08:12:50.973082 1013709 storage/raft_transport.go:436  raft transport stream to node 1 established
I170528 08:12:50.991429 1009177 storage/replica_command.go:2633  [s1,r1/1:/M{in-ax}] initiating a split of this range at key "m" [r2]
E170528 08:12:51.003320 1011773 storage/queue.go:636  [replicate,s1,r1/1:{/Min-m}] range requires a replication change, but lacks a quorum of live replicas (0/2)
E170528 08:12:51.004502 1011773 storage/queue.go:636  [replicate,s1,r2/1:{m-/Max}] range requires a replication change, but lacks a quorum of live replicas (0/2)
I170528 08:12:51.009013 1009177 storage/store.go:2146  removing replica
I170528 08:12:51.009322 1009177 storage/replica.go:714  removed 28 (20+8) keys in 0ms [clear=0ms commit=0ms]
E170528 08:12:51.009551 1011612 util/log/crash_reporting.go:81  a panic has occurred!
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0xe99e4d]

goroutine 1011612 [running]:
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).Recover(0xc430db6120, 0x7f93ce0f3ea8, 0xc430d00330)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:200 +0xb1
panic(0x195f420, 0x2760120)
	/usr/local/go/src/runtime/panic.go:489 +0x2cf
github.com/cockroachdb/cockroach/pkg/storage.(*Replica).updateProposalQuotaRaftMuLocked(0xc42aba8e00, 0x7f93ce0f3ea8, 0xc42f342e70, 0x1)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/replica.go:909 +0xdd
github.com/cockroachdb/cockroach/pkg/storage.(*Replica).handleRaftReadyRaftMuLocked(0xc42aba8e00, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/replica.go:2997 +0x1c70
github.com/cockroachdb/cockroach/pkg/storage.(*Replica).handleRaftReady(0xc42aba8e00, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/replica.go:2944 +0xe0
github.com/cockroachdb/cockroach/pkg/storage.(*Store).processReady(0xc42f3a8000, 0x2)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/store.go:3417 +0x131
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).worker(0xc42c9b4180, 0xc430db6120)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:217 +0x270
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).Start.func2(0x7f93ce0f3ea8, 0xc430d00330)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:168 +0x33
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc420faedb0, 0xc430db6120, 0xc420233de0)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:215 +0xf7
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:216 +0xad

goroutine 1 [chan receive]:
testing.(*T).Run(0xc4203e0f70, 0x1b3771c, 0x1a, 0x1bed1d8, 0xc4206efa01)
	/usr/local/go/src/testing/testing.go:698 +0x2f4
testing.runTests.func1(0xc4203e0f70)
	/usr/local/go/src/testing/testing.go:882 +0x67
testing.tRunner(0xc4203e0f70, 0xc4206efb78)
	/usr/local/go/src/testing/testing.go:657 +0x96
testing.runTests(0xc4200fb0e0, 0x277bbe0, 0x1b3, 0x1b3, 0xc4206efc00)
	/usr/local/go/src/testing/testing.go:888 +0x2c1
testing.(*M).Run(0xc4206e9f20, 0xc4206efd70)
	/usr/local/go/src/testing/testing.go:822 +0xfc
github.com/cockroachdb/cockroach/pkg/storage_test.TestMain(0xc4206eff20)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/main_test.go:59 +0x20a
main.main()
	github.com/cockroachdb/cockroach/pkg/storage/_test/_testmain.go:922 +0xf7

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:2197 +0x1

goroutine 45 [chan receive]:
github.com/cockroachdb/cockroach/pkg/util/log.(*loggingT).flushDaemon(0x2c22400)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/log/clog.go:1057 +0x77
created by github.com/cockroachdb/cockroach/pkg/util/log.init.1
	/go/src/github.com/cockroachdb/cockroach/pkg/util/log/clog.go:603 +0xd9

goroutine 54 [syscall]:
os/signal.signal_recv(0xc4200cdfc0)
	/usr/local/go/src/runtime/sigqueue.go:116 +0x104
os/signal.loop()
	/usr/local/go/src/os/signal/signal_unix.go:22 +0x22
created by os/signal.init.1
	/usr/local/go/src/os/signal/signal_unix.go:28 +0x41

goroutine 1012454 [semacquire]:
sync.runtime_notifyListWait(0xc42f66bbd0, 0xc40000004b)
	/usr/local/go/src/runtime/sema.go:298 +0x10b
sync.(*Cond).Wait(0xc42f66bbc0)
	/usr/local/go/src/sync/cond.go:57 +0x89
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).worker(0xc42c9b4880, 0xc430db6480)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:199 +0xac
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).Start.func2(0x7f93ce0f3ea8, 0xc42f91c240)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:168 +0x33
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc42f9c07e0, 0xc430db6480, 0xc42f6470c0)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:215 +0xf7
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:216 +0xad

goroutine 1011574 [select]:
github.com/cockroachdb/cockroach/pkg/rpc.(*Context).runHeartbeat(0xc42c9b4000, 0xc42ffee040, 0xc430c66360, 0xf, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/pkg/rpc/context.go:371 +0x801
github.com/cockroachdb/cockroach/pkg/rpc.(*Context).GRPCDial.func1.2.1(0x7f93ce0f3ea8, 0xc42f42e030)
	/go/src/github.com/cockroachdb/cockroach/pkg/rpc/context.go:307 +0x6b
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc420fae050, 0xc430db6000, 0xc42d5de5d0)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:215 +0xf7
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:216 +0xad

goroutine 1012481 [semacquire]:
sync.runtime_notifyListWait(0xc42f66bbd0, 0x26)
	/usr/local/go/src/runtime/sema.go:298 +0x10b
sync.(*Cond).Wait(0xc42f66bbc0)
	/usr/local/go/src/sync/cond.go:57 +0x89
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).worker(0xc42c9b4880, 0xc430db6480)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:199 +0xac
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).Start.func2(0x7f93ce0f3ea8, 0xc42f91c750)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:168 +0x33
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc42f9c0990, 0xc430db6480, 0xc42f647420)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:215 +0xf7
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:216 +0xad

goroutine 1012419 [select]:
github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/transport.(*http2Client).controller(0xc43024e480)
	/go/src/github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/transport/http2_client.go:1168 +0x65a
created by github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/transport.newHTTP2Client
	/go/src/github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/transport/http2_client.go:297 +0xe2d

goroutine 1012463 [semacquire]:
sync.runtime_notifyListWait(0xc42f66bbd0, 0x14)
	/usr/local/go/src/runtime/sema.go:298 +0x10b
sync.(*Cond).Wait(0xc42f66bbc0)
	/usr/local/go/src/sync/cond.go:57 +0x89
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).worker(0xc42c9b4880, 0xc430db6480)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:199 +0xac
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).Start.func2(0x7f93ce0f3ea8, 0xc42f91c3f0)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:168 +0x33
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc42f9c0870, 0xc430db6480, 0xc42f6471e0)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:215 +0xf7
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:216 +0xad

goroutine 1011553 [chan receive]:
github.com/cockroachdb/cockroach/pkg/util/netutil.ListenAndServeGRPC.func1(0x7f93ce0f3ea8, 0xc430befb00)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/netutil/net.go:51 +0x6f
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc430c662a0, 0xc430db6000, 0xc430bef920)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:215 +0xf7
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:216 +0xad

goroutine 1011658 [semacquire]:
sync.runtime_notifyListWait(0xc42ff9f190, 0x1e)
	/usr/local/go/src/runtime/sema.go:298 +0x10b
sync.(*Cond).Wait(0xc42ff9f180)
	/usr/local/go/src/sync/cond.go:57 +0x89
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).worker(0xc42c9b4180, 0xc430db6120)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:199 +0xac
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).Start.func2(0x7f93ce0f3ea8, 0xc430d003c0)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:168 +0x33
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc420faf270, 0xc430db6120, 0xc42f8345a0)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:215 +0xf7
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:216 +0xad

goroutine 1012501 [semacquire]:
sync.runtime_notifyListWait(0xc42f66bbd0, 0x3a)
	/usr/local/go/src/runtime/sema.go:298 +0x10b
sync.(*Cond).Wait(0xc42f66bbc0)
	/usr/local/go/src/sync/cond.go:57 +0x89
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).worker(0xc42c9b4880, 0xc430db6480)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:199 +0xac
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).Start.func2(0x7f93ce0f3ea8, 0xc42f91cb10)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:168 +0x33
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc42f9c0ad0, 0xc430db6480, 0xc42f6476e0)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:215 +0xf7
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:216 +0xad

goroutine 1011626 [semacquire]:
sync.runtime_notifyListWait(0xc42ff9f190, 0x3c)
	/usr/local/go/src/runtime/sema.go:298 +0x10b
sync.(*Cond).Wait(0xc42ff9f180)
	/usr/local/go/src/sync/cond.go:57 +0x89
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).worker(0xc42c9b4180, 0xc430db6120)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:199 +0xac
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).Start.func2(0x7f93ce0f3ea8, 0xc430d00ba0)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:168 +0x33
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc420faeeb0, 0xc430db6120, 0xc42f8341a0)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:215 +0xf7
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:216 +0xad

goroutine 1011651 [semacquire]:
sync.runtime_notifyListWait(0xc42ff9f190, 0x23)
	/usr/local/go/src/runtime/sema.go:298 +0x10b
sync.(*Cond).Wait(0xc42ff9f180)
	/usr/local/go/src/sync/cond.go:57 +0x89
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).worker(0xc42c9b4180, 0xc430db6120)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:199 +0xac
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).Start.func2(0x7f93ce0f3ea8, 0xc430d004b0)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:168 +0x33
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc420faf1d0, 0xc430db6120, 0xc42f8344c0)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:215 +0xf7
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:216 +0xad

goroutine 1011650 [semacquire]:
sync.runtime_notifyListWait(0xc42ff9f190, 0x22)
	/usr/local/go/src/runtime/sema.go:298 +0x10b
sync.(*Cond).Wait(0xc42ff9f180)
	/usr/local/go/src/sync/cond.go:57 +0x89
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).worker(0xc42c9b4180, 0xc430db6120)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:199 +0xac
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).Start.func2(0x7f93ce0f3ea8, 0xc430d00480)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:168 +0x33
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc420faf1c0, 0xc430db6120, 0xc42f8344a0)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:215 +0xf7
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:216 +0xad

goroutine 1013640 [select]:
github.com/cockroachdb/cockroach/pkg/storage.(*RaftTransport).RaftMessageBatch(0xc430d44000, 0x27a2180, 0xc42f7ff1d0, 0x278b260, 0xc430d44000)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/raft_transport.go:329 +0x210
github.com/cockroachdb/cockroach/pkg/storage._MultiRaft_RaftMessageBatch_Handler(0x1aeb720, 0xc430d44000, 0x279f360, 0xc428f64c80, 0xc42a0b2f70, 0x2)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/raft.pb.go:378 +0xb7
github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc.(*Server).processStreamingRPC(0xc42f2f6900, 0x27a0500, 0xc42fc06160, 0xc42e7d1f00, 0xc430bee4e0, 0x276c620, 0x0, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/server.go:879 +0xa41
github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc.(*Server).handleStream(0xc42f2f6900, 0x27a0500, 0xc42fc06160, 0xc42e7d1f00, 0x0)
	/go/src/github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/server.go:973 +0x1539
github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc430c66460, 0xc42f2f6900, 0x27a0500, 0xc42fc06160, 0xc42e7d1f00)
	/go/src/github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/server.go:537 +0xa9
created by github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc.(*Server).serveStreams.func1
	/go/src/github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/server.go:538 +0xa1

goroutine 1012782 [select]:
github.com/cockroachdb/cockroach/pkg/storage.(*replicaScanner).waitAndProcess(0xc42adf95c0, 0x7f93ce0f3ea8, 0xc42f588390, 0xed0bc7d82, 0xc43125d9e9, 0x2c20cc0, 0xc430cae000, 0xc430db6480, 0x0, 0xc42df43f78)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scanner.go:210 +0x241
github.com/cockroachdb/cockroach/pkg/storage.(*replicaScanner).scanLoop.func1(0x7f93ce0f3ea8, 0xc42f588390)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scanner.go:277 +0x362
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc42f8a0990, 0xc430db6480, 0xc42f420ca0)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:215 +0xf7
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:216 +0xad

goroutine 1012504 [semacquire]:
sync.runtime_notifyListWait(0xc42f66bbd0, 0x3d)
	/usr/local/go/src/runtime/sema.go:298 +0x10b
sync.(*Cond).Wait(0xc42f66bbc0)
	/usr/local/go/src/sync/cond.go:57 +0x89
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).worker(0xc42c9b4880, 0xc430db6480)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:199 +0xac
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).Start.func2(0x7f93ce0f3ea8, 0xc42f91cba0)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:168 +0x33
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc42f9c0b00, 0xc430db6480, 0xc42f647740)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:215 +0xf7
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:216 +0xad

goroutine 1012248 [select]:
github.com/cockroachdb/cockroach/pkg/kv.(*TxnCoordSender).printStatsLoop(0xc42f986ea0, 0x7f93ce0f3ea8, 0xc42f323530)
	/go/src/github.com/cockroachdb/cockroach/pkg/kv/txn_coord_sender.go:255 +0xb47
github.com/cockroachdb/cockroach/pkg/kv.NewTxnCoordSender.func1(0x7f93ce0f3ea8, 0xc42f323530)
	/go/src/github.com/cockroachdb/cockroach/pkg/kv/txn_coord_sender.go:239 +0x3e
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc430c66bf0, 0xc430db6480, 0xc430c66be0)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:215 +0xf7
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:216 +0xad

goroutine 1011655 [semacquire]:
sync.runtime_notifyListWait(0xc42ff9f190, 0x27)
	/usr/local/go/src/runtime/sema.go:298 +0x10b
sync.(*Cond).Wait(0xc42ff9f180)
	/usr/local/go/src/sync/cond.go:57 +0x89
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).worker(0xc42c9b4180, 0xc430db6120)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:199 +0xac
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).Start.func2(0x7f93ce0f3ea8, 0xc430d00570)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:168 +0x33
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc420faf230, 0xc430db6120, 0xc42f834540)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:215 +0xf7
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:216 +0xad

goroutine 1012508 [select]:
github.com/cockroachdb/cockroach/pkg/storage.(*Store).raftTickLoop.func1(0x7f93ce0f3ea8, 0xc42f91cc60)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/store.go:3493 +0x337
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc42f9c0b60, 0xc430db6480, 0xc42f9c0b50)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:215 +0xf7
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:216 +0xad

goroutine 1012436 [chan receive]:
github.com/cockroachdb/cockroach/pkg/gossip.(*server).start.func3(0x7f93ce0f3ea8, 0xc42f323e00)
	/go/src/github.com/cockroachdb/cockroach/pkg/gossip/server.go:386 +0x66
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc42f9c0640, 0xc430db6000, 0xc42f646e80)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:215 +0xf7
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:216 +0xad

goroutine 1013667 [select]:
github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc.newClientStream.func3(0x27a23c0, 0xc43024e480, 0xc42e95b040, 0xc42b6ea6e0, 0xc42ce76300)
	/go/src/github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/stream.go:244 +0x3c9
created by github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc.newClientStream
	/go/src/github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/stream.go:263 +0xd8b

goroutine 1012670 [select]:
github.com/cockroachdb/cockroach/pkg/gossip.(*server).Gossip(0xc4243ac1e0, 0x27a1160, 0xc42f9c1c50, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/pkg/gossip/server.go:200 +0x579
github.com/cockroachdb/cockroach/pkg/gossip._Gossip_Gossip_Handler(0x1ae4620, 0xc4243ac1e0, 0x279f360, 0xc42c9b4d00, 0x0, 0x3fc3333333333333)
	/go/src/github.com/cockroachdb/cockroach/pkg/gossip/gossip.pb.go:211 +0xb7
github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc.(*Server).processStreamingRPC(0xc42f2f6900, 0x27a0500, 0xc42fc06160, 0xc42e211e00, 0xc430beea50, 0x2764200, 0x0, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/server.go:879 +0xa41
github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc.(*Server).handleStream(0xc42f2f6900, 0x27a0500, 0xc42fc06160, 0xc42e211e00, 0x0)
	/go/src/github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/server.go:973 +0x1539
github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc430c66460, 0xc42f2f6900, 0x27a0500, 0xc42fc06160, 0xc42e211e00)
	/go/src/github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/server.go:537 +0xa9
created by github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc.(*Server).serveStreams.func1
	/go/src/github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/server.go:538 +0xa1

goroutine 1011646 [semacquire]:
sync.runtime_notifyListWait(0xc42ff9f190, 0x1d)
	/usr/local/go/src/runtime/sema.go:298 +0x10b
sync.(*Cond).Wait(0xc42ff9f180)
	/usr/local/go/src/sync/cond.go:57 +0x89
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).worker(0xc42c9b4180, 0xc430db6120)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:199 +0xac
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).Start.func2(0x7f93ce0f3ea8, 0xc42d5df7d0)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:168 +0x33
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc420faf180, 0xc430db6120, 0xc42f834420)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:215 +0xf7
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:216 +0xad

goroutine 1012776 [select]:
github.com/cockroachdb/cockroach/pkg/storage.(*baseQueue).processLoop.func1(0x7f93ce0f3ea8, 0xc42f588480)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/queue.go:490 +0x364
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc42f8a0930, 0xc430db6480, 0xc42f420be0)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:215 +0xf7
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:216 +0xad

goroutine 1013714 [select]:
github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc.newClientStream.func3(0x27a23c0, 0xc42ce3a180, 0xc4291c9ba0, 0xc42b6ea9a0, 0xc42ce76500)
	/go/src/github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/stream.go:244 +0x3c9
created by github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc.newClientStream
	/go/src/github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/stream.go:263 +0xd8b

goroutine 1012460 [semacquire]:
sync.runtime_notifyListWait(0xc42f66bbd0, 0x11)
	/usr/local/go/src/runtime/sema.go:298 +0x10b
sync.(*Cond).Wait(0xc42f66bbc0)
	/usr/local/go/src/sync/cond.go:57 +0x89
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).worker(0xc42c9b4880, 0xc430db6480)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:199 +0xac
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).Start.func2(0x7f93ce0f3ea8, 0xc42f91c360)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:168 +0x33
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc42f9c0840, 0xc430db6480, 0xc42f647180)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:215 +0xf7
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:216 +0xad

goroutine 1012486 [semacquire]:
sync.runtime_notifyListWait(0xc42f66bbd0, 0x2b)
	/usr/local/go/src/runtime/sema.go:298 +0x10b
sync.(*Cond).Wait(0xc42f66bbc0)
	/usr/local/go/src/sync/cond.go:57 +0x89
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).worker(0xc42c9b4880, 0xc430db6480)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:199 +0xac
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).Start.func2(0x7f93ce0f3ea8, 0xc42f91c840)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:168 +0x33
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc42f9c09e0, 0xc430db6480, 0xc42f6474e0)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:215 +0xf7
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:216 +0xad

goroutine 1011660 [select]:
github.com/cockroachdb/cockroach/pkg/storage.(*Store).raftTickLoop.func1(0x7f93ce0f3ea8, 0xc42d5df830)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/store.go:3493 +0x337
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc420faf2c0, 0xc430db6120, 0xc420faf2a0)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:215 +0xf7
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:216 +0xad

goroutine 1011361 [select]:
github.com/cockroachdb/cockroach/pkg/kv.(*TxnCoordSender).printStatsLoop(0xc42f9864e0, 0x7f93ce0f3ea8, 0xc430d00030)
	/go/src/github.com/cockroachdb/cockroach/pkg/kv/txn_coord_sender.go:255 +0xb47
github.com/cockroachdb/cockroach/pkg/kv.NewTxnCoordSender.func1(0x7f93ce0f3ea8, 0xc430d00030)
	/go/src/github.com/cockroachdb/cockroach/pkg/kv/txn_coord_sender.go:239 +0x3e
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc430d38710, 0xc430db6120, 0xc430d38700)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:215 +0xf7
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:216 +0xad

goroutine 1008785 [select]:
github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/transport.(*http2Client).controller(0xc42ce3a180)
	/go/src/github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/transport/http2_client.go:1168 +0x65a
created by github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/transport.newHTTP2Client
	/go/src/github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/transport/http2_client.go:297 +0xe2d

goroutine 1011603 [semacquire]:
sync.runtime_notifyListWait(0xc42ff9f190, 0xc400000047)
	/usr/local/go/src/runtime/sema.go:298 +0x10b
sync.(*Cond).Wait(0xc42ff9f180)
	/usr/local/go/src/sync/cond.go:57 +0x89
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).worker(0xc42c9b4180, 0xc430db6120)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:199 +0xac
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).Start.func2(0x7f93ce0f3ea8, 0xc430d00180)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:168 +0x33
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc420faed10, 0xc430db6120, 0xc420233a60)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:215 +0xf7
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:216 +0xad

goroutine 1012458 [semacquire]:
sync.runtime_notifyListWait(0xc42f66bbd0, 0x4e)
	/usr/local/go/src/runtime/sema.go:298 +0x10b
sync.(*Cond).Wait(0xc42f66bbc0)
	/usr/local/go/src/sync/cond.go:57 +0x89
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).worker(0xc42c9b4880, 0xc430db6480)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:199 +0xac
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).Start.func2(0x7f93ce0f3ea8, 0xc42f91c300)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:168 +0x33
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc42f9c0820, 0xc430db6480, 0xc42f647140)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:215 +0xf7
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:216 +0xad

goroutine 1013643 [select]:
github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/transport.(*recvBufferReader).Read(0xc42f1f5cc0, 0xc42f3e4c70, 0x5, 0x5, 0x0, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/transport/transport.go:145 +0x556
github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/transport.(*Stream).Read(0xc42e7d1f00, 0xc42f3e4c70, 0x5, 0x5, 0xc42896b990, 0x2770e90, 0xc42e171c10)
	/go/src/github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/transport/transport.go:328 +0x59
io.ReadAtLeast(0x2785a20, 0xc42e7d1f00, 0xc42f3e4c70, 0x5, 0x5, 0x5, 0xc42e171c58, 0xa370bc, 0x1968140)
	/usr/local/go/src/io/io.go:307 +0xa9
io.ReadFull(0x2785a20, 0xc42e7d1f00, 0xc42f3e4c70, 0x5, 0x5, 0x0, 0x0, 0xc42e171cc8)
	/usr/local/go/src/io/io.go:325 +0x58
github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc.(*parser).recvMsg(0xc42f3e4c60, 0x7fffffff, 0xc42896b8c8, 0x20, 0x20, 0xc42e171d98, 0x12, 0x6)
	/go/src/github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/rpc_util.go:255 +0x69
github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc.recv(0xc42f3e4c60, 0x27989a0, 0x2c5fd78, 0xc42e7d1f00, 0x278d520, 0x2c5fd78, 0x1a46840, 0xc42f4c0220, 0x7fffffff, 0x0, ...)
	/go/src/github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/rpc_util.go:351 +0x4d
github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc.(*serverStream).RecvMsg(0xc428f64c80, 0x1a46840, 0xc42f4c0220, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/stream.go:623 +0x11a
github.com/cockroachdb/cockroach/pkg/storage.(*multiRaftRaftMessageBatchServer).Recv(0xc42f7ff1d0, 0x7f93ce0f3ea8, 0xc42f553b00, 0xc428a68000)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/raft.pb.go:397 +0x62
github.com/cockroachdb/cockroach/pkg/storage.(*RaftTransport).RaftMessageBatch.func1.1.1(0x27a2180, 0xc42f7ff1d0, 0xc430d44000, 0x7f93ce0f3ea8, 0xc42f553b00, 0x18, 0xd2b534)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/raft_transport.go:300 +0x3f
github.com/cockroachdb/cockroach/pkg/storage.(*RaftTransport).RaftMessageBatch.func1.1(0x7f93ce0f3ea8, 0xc42f553b00)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/raft_transport.go:323 +0x5d
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc42f7ff220, 0xc430db6000, 0xc42f553ad0)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:215 +0xf7
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:216 +0xad

goroutine 1011663 [select]:
github.com/cockroachdb/cockroach/pkg/storage.(*Store).Start.func2(0x7f93ce0f3ea8, 0xc42d5df890)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/store.go:1226 +0x165
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc420faf300, 0xc430db6120, 0xc42f8345e0)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:215 +0xf7
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:216 +0xad

goroutine 1011604 [semacquire]:
sync.runtime_notifyListWait(0xc42ff9f190, 0xc400000049)
	/usr/local/go/src/runtime/sema.go:298 +0x10b
sync.(*Cond).Wait(0xc42ff9f180)
	/usr/local/go/src/sync/cond.go:57 +0x89
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).worker(0xc42c9b4180, 0xc430db6120)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:199 +0xac
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).Start.func2(0x7f93ce0f3ea8, 0xc430d001b0)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:168 +0x33
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc420faed20, 0xc430db6120, 0xc420233aa0)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:215 +0xf7
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:216 +0xad

goroutine 1011636 [semacquire]:
sync.runtime_notifyListWait(0xc42ff9f190, 0xc400000048)
	/usr/local/go/src/runtime/sema.go:298 +0x10b
sync.(*Cond).Wait(0xc42ff9f180)
	/usr/local/go/src/sync/cond.go:57 +0x89
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).worker(0xc42c9b4180, 0xc430db6120)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:199 +0xac
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).Start.func2(0x7f93ce0f3ea8, 0xc42d5df5f0)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:168 +0x33
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc420faefe0, 0xc430db6120, 0xc42f8342e0)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:215 +0xf7
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:216 +0xad

goroutine 1012775 [select]:
github.com/cockroachdb/cockroach/pkg/storage.(*baseQueue).processLoop.func1(0x7f93ce0f3ea8, 0xc42f588450)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/queue.go:490 +0x364
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc42f8a0920, 0xc430db6480, 0xc42f420bc0)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:215 +0xf7
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:216 +0xad

goroutine 1012453 [semacquire]:
sync.runtime_notifyListWait(0xc42f66bbd0, 0xc40000004a)
	/usr/local/go/src/runtime/sema.go:298 +0x10b
sync.(*Cond).Wait(0xc42f66bbc0)
	/usr/local/go/src/sync/cond.go:57 +0x89
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).worker(0xc42c9b4880, 0xc430db6480)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:199 +0xac
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).Start.func2(0x7f93ce0f3ea8, 0xc42f91c210)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:168 +0x33
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc42f9c07d0, 0xc430db6480, 0xc42f6470a0)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:215 +0xf7
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:216 +0xad

goroutine 1011608 [semacquire]:
sync.runtime_notifyListWait(0xc42ff9f190, 0xc400000050)
	/usr/local/go/src/runtime/sema.go:298 +0x10b
sync.(*Cond).Wait(0xc42ff9f180)
	/usr/local/go/src/sync/cond.go:57 +0x89
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).worker(0xc42c9b4180, 0xc430db6120)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:199 +0xac
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).Start.func2(0x7f93ce0f3ea8, 0xc430d00270)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:168 +0x33
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc420faed60, 0xc430db6120, 0xc420233b20)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:215 +0xf7
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:216 +0xad

goroutine 1013972 [select]:
github.com/cockroachdb/cockroach/pkg/storage.(*idAllocator).start.func1(0x7f93ce0f3ea8, 0xc42f2165d0)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/id_alloc.go:133 +0x729
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc42f736960, 0xc430db6120, 0xc42f736950)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:215 +0xf7
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:216 +0xad

goroutine 1013662 [select]:
github.com/cockroachdb/cockroach/pkg/storage.(*RaftTransport).processQueue(0xc430d44000, 0x7f9300000002, 0xc427b7be00, 0xc42f10fc80, 0x27a2120, 0xc42f85fd50, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/raft_transport.go:494 +0x697
github.com/cockroachdb/cockroach/pkg/storage.(*RaftTransport).connectAndProcess.func1(0xc430d44000, 0x2, 0x7f93ce0f3ea8, 0xc42f6615c0, 0x1, 0x0, 0xc42f0d4000, 0xc427b7be00, 0xc42f10fc80, 0x0, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/raft_transport.go:439 +0x32e
github.com/cockroachdb/cockroach/pkg/storage.(*RaftTransport).connectAndProcess(0xc430d44000, 0x7f93ce0f3ea8, 0xc42f6615c0, 0x2, 0xc427b7be00, 0xc42f10fc80)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/raft_transport.go:440 +0xe9
github.com/cockroachdb/cockroach/pkg/storage.(*RaftTransport).SendAsync.func2.1(0x7f93ce0f3ea8, 0xc42f6615c0)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/raft_transport.go:574 +0x60
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc42f85fcb0, 0xc430db6000, 0xc42f661590)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:215 +0xf7
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:216 +0xad

goroutine 1011628 [semacquire]:
sync.runtime_notifyListWait(0xc42ff9f190, 0x3e)
	/usr/local/go/src/runtime/sema.go:298 +0x10b
sync.(*Cond).Wait(0xc42ff9f180)
	/usr/local/go/src/sync/cond.go:57 +0x89
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).worker(0xc42c9b4180, 0xc430db6120)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:199 +0xac
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).Start.func2(0x7f93ce0f3ea8, 0xc430d00c00)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:168 +0x33
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc420faeed0, 0xc430db6120, 0xc42f8341e0)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:215 +0xf7
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:216 +0xad

goroutine 1011657 [semacquire]:
sync.runtime_notifyListWait(0xc42ff9f190, 0x29)
	/usr/local/go/src/runtime/sema.go:298 +0x10b
sync.(*Cond).Wait(0xc42ff9f180)
	/usr/local/go/src/sync/cond.go:57 +0x89
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).worker(0xc42c9b4180, 0xc430db6120)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:199 +0xac
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).Start.func2(0x7f93ce0f3ea8, 0xc430d005d0)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:168 +0x33
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc420faf260, 0xc430db6120, 0xc42f834580)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:215 +0xf7
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:216 +0xad

goroutine 1012462 [semacquire]:
sync.runtime_notifyListWait(0xc42f66bbd0, 0x13)
	/usr/local/go/src/runtime/sema.go:298 +0x10b
sync.(*Cond).Wait(0xc42f66bbc0)
	/usr/local/go/src/sync/cond.go:57 +0x89
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).worker(0xc42c9b4880, 0xc430db6480)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:199 +0xac
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).Start.func2(0x7f93ce0f3ea8, 0xc42f91c3c0)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:168 +0x33
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc42f9c0860, 0xc430db6480, 0xc42f6471c0)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:215 +0xf7
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:216 +0xad

goroutine 1012474 [semacquire]:
sync.runtime_notifyListWait(0xc42f66bbd0, 0x1f)
	/usr/local/go/src/runtime/sema.go:298 +0x10b
sync.(*Cond).Wait(0xc42f66bbc0)
	/usr/local/go/src/sync/cond.go:57 +0x89
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).worker(0xc42c9b4880, 0xc430db6480)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:199 +0xac
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).Start.func2(0x7f93ce0f3ea8, 0xc42f91c600)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:168 +0x33
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc42f9c0920, 0xc430db6480, 0xc42f647340)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:215 +0xf7
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:216 +0xad

goroutine 1012408 [IO wait]:
net.runtime_pollWait(0x7f93c9d3e8e8, 0x72, 0x0)
	/usr/local/go/src/runtime/netpoll.go:164 +0x59
net.(*pollDesc).wait(0xc42ce3e7d8, 0x72, 0x0, 0xc42f646b00)
	/usr/local/go/src/net/fd_poll_runtime.go:75 +0x38
net.(*pollDesc).waitRead(0xc42ce3e7d8, 0xffffffffffffffff, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:80 +0x34
net.(*netFD).accept(0xc42ce3e770, 0x0, 0x27868a0, 0xc42f646b00)
	/usr/local/go/src/net/fd_unix.go:430 +0x1e5
net.(*TCPListener).accept(0xc42a6be1c8, 0xc420042df8, 0xb27a37, 0x6b8f70)
	/usr/local/go/src/net/tcpsock_posix.go:136 +0x2e
net.(*TCPListener).Accept(0xc42a6be1c8, 0x1bee3e0, 0xc42e146c60, 0x27a2480, 0xc42a6be1e0)
	/usr/local/go/src/net/tcpsock.go:228 +0x49
github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc.(*Server).Serve(0xc42e146c60, 0x27978e0, 0xc42a6be1c8, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/server.go:432 +0x189
github.com/cockroachdb/cockroach/pkg/util/netutil.ListenAndServeGRPC.func2(0x7f93ce0f3ea8, 0xc42f323590)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/netutil/net.go:58 +0x3c
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc42f9c0290, 0xc430db6000, 0xc42f646920)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:215 +0xf7
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:216 +0xad

goroutine 1011562 [select]:
github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/transport.(*http2Server).controller(0xc42fc06160)
	/go/src/github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/transport/http2_server.go:956 +0x78d
created by github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/transport.newHTTP2Server
	/go/src/github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/transport/http2_server.go:225 +0x96d

goroutine 1011622 [semacquire]:
sync.runtime_notifyListWait(0xc42ff9f190, 0x38)
	/usr/local/go/src/runtime/sema.go:298 +0x10b
sync.(*Cond).Wait(0xc42ff9f180)
	/usr/local/go/src/sync/cond.go:57 +0x89
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).worker(0xc42c9b4180, 0xc430db6120)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:199 +0xac
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).Start.func2(0x7f93ce0f3ea8, 0xc430d009f0)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:168 +0x33
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc420faee50, 0xc430db6120, 0xc42f834120)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:215 +0xf7
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:216 +0xad

goroutine 1011597 [semacquire]:
sync.runtime_notifyListWait(0xc42ff9f190, 0xc400000042)
	/usr/local/go/src/runtime/sema.go:298 +0x10b
sync.(*Cond).Wait(0xc42ff9f180)
	/usr/local/go/src/sync/cond.go:57 +0x89
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).worker(0xc42c9b4180, 0xc430db6120)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:199 +0xac
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).Start.func2(0x7f93ce0f3ea8, 0xc42f6600c0)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:168 +0x33
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc420faecb0, 0xc430db6120, 0xc420233900)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:215 +0xf7
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:216 +0xad

goroutine 1011777 [select]:
github.com/cockroachdb/cockroach/pkg/storage.(*baseQueue).processLoop.func1(0x7f93ce0f3ea8, 0xc42f82e030)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/queue.go:490 +0x364
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc420fafad0, 0xc430db6120, 0xc42f835080)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:215 +0xf7
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:216 +0xad

goroutine 1013675 [select]:
github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/transport.(*recvBufferReader).Read(0xc42f070080, 0xc42f3b5810, 0x5, 0x5, 0x0, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/transport/transport.go:145 +0x556
github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/transport.(*Stream).Read(0xc42ce76400, 0xc42f3b5810, 0x5, 0x5, 0xc42896bb20, 0x2770e90, 0xc42e113c10)
	/go/src/github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/transport/transport.go:328 +0x59
io.ReadAtLeast(0x2785a20, 0xc42ce76400, 0xc42f3b5810, 0x5, 0x5, 0x5, 0xc42e113c58, 0xa370bc, 0x1968140)
	/usr/local/go/src/io/io.go:307 +0xa9
io.ReadFull(0x2785a20, 0xc42ce76400, 0xc42f3b5810, 0x5, 0x5, 0x0, 0x0, 0xc42e113cc8)
	/usr/local/go/src/io/io.go:325 +0x58
github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc.(*parser).recvMsg(0xc42f3b5800, 0x7fffffff, 0xc42896b8c8, 0x20, 0x20, 0xc42e113d98, 0x14, 0x6)
	/go/src/github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/rpc_util.go:255 +0x69
github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc.recv(0xc42f3b5800, 0x27989a0, 0x2c5fd78, 0xc42ce76400, 0x278d520, 0x2c5fd78, 0x1a46840, 0xc42ce3dd00, 0x7fffffff, 0x0, ...)
	/go/src/github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/rpc_util.go:351 +0x4d
github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc.(*serverStream).RecvMsg(0xc42aa44400, 0x1a46840, 0xc42ce3dd00, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/stream.go:623 +0x11a
github.com/cockroachdb/cockroach/pkg/storage.(*multiRaftRaftMessageBatchServer).Recv(0xc42f85fe30, 0x7f93ce0f3ea8, 0xc42f661950, 0xc43024fe00)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/raft.pb.go:397 +0x62
github.com/cockroachdb/cockroach/pkg/storage.(*RaftTransport).RaftMessageBatch.func1.1.1(0x27a2180, 0xc42f85fe30, 0xc430d44000, 0x7f93ce0f3ea8, 0xc42f661950, 0x18, 0xd2b534)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/raft_transport.go:300 +0x3f
github.com/cockroachdb/cockroach/pkg/storage.(*RaftTransport).RaftMessageBatch.func1.1(0x7f93ce0f3ea8, 0xc42f661950)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/raft_transport.go:323 +0x5d
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc42f85fe70, 0xc430db6000, 0xc42f661920)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:215 +0xf7
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:216 +0xad

goroutine 1012499 [semacquire]:
sync.runtime_notifyListWait(0xc42f66bbd0, 0x38)
	/usr/local/go/src/runtime/sema.go:298 +0x10b
sync.(*Cond).Wait(0xc42f66bbc0)
	/usr/local/go/src/sync/cond.go:57 +0x89
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).worker(0xc42c9b4880, 0xc430db6480)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:199 +0xac
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).Start.func2(0x7f93ce0f3ea8, 0xc42f91cab0)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:168 +0x33
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc42f9c0ab0, 0xc430db6480, 0xc42f6476a0)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:215 +0xf7
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:216 +0xad

goroutine 1011641 [semacquire]:
sync.runtime_notifyListWait(0xc42ff9f190, 0xc400000053)
	/usr/local/go/src/runtime/sema.go:298 +0x10b
sync.(*Cond).Wait(0xc42ff9f180)
	/usr/local/go/src/sync/cond.go:57 +0x89
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).worker(0xc42c9b4180, 0xc430db6120)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:199 +0xac
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).Start.func2(0x7f93ce0f3ea8, 0xc42d5df6e0)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:168 +0x33
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc420faf090, 0xc430db6120, 0xc42f834380)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:215 +0xf7
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:216 +0xad

goroutine 1011772 [select]:
github.com/cockroachdb/cockroach/pkg/storage.(*baseQueue).processLoop.func1(0x7f93ce0f3ea8, 0xc430d00a80)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/queue.go:490 +0x364
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc420fafa70, 0xc430db6120, 0xc42f834fa0)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:215 +0xf7
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:216 +0xad

goroutine 1011649 [semacquire]:
sync.runtime_notifyListWait(0xc42ff9f190, 0x21)
	/usr/local/go/src/runtime/sema.go:298 +0x10b
sync.(*Cond).Wait(0xc42ff9f180)
	/usr/local/go/src/sync/cond.go:57 +0x89
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).worker(0xc42c9b4180, 0xc430db6120)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:199 +0xac
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).Start.func2(0x7f93ce0f3ea8, 0xc430d00450)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:168 +0x33
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc420faf1b0, 0xc430db6120, 0xc42f834480)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:215 +0xf7
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:216 +0xad

goroutine 1009179 [chan receive]:
github.com/cockroachdb/cockroach/pkg/rpc.NewContext.func1(0x7f93ce0f3ea8, 0xc430d00000)
	/go/src/github.com/cockroachdb/cockroach/pkg/rpc/context.go:186 +0x76
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc430d38180, 0xc430db6000, 0xc430ebc1c0)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:215 +0xf7
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:216 +0xad

goroutine 1012459 [semacquire]:
sync.runtime_notifyListWait(0xc42f66bbd0, 0x10)
	/usr/local/go/src/runtime/sema.go:298 +0x10b
sync.(*Cond).Wait(0xc42f66bbc0)
	/usr/local/go/src/sync/cond.go:57 +0x89
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).worker(0xc42c9b4880, 0xc430db6480)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:199 +0xac
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).Start.func2(0x7f93ce0f3ea8, 0xc42f91c330)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:168 +0x33
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc42f9c0830, 0xc430db6480, 0xc42f647160)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:215 +0xf7
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:216 +0xad

goroutine 1012420 [select]:
github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/transport.(*http2Client).keepalive(0xc43024e480)
	/go/src/github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/transport/http2_client.go:1214 +0x4ed
created by github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/transport.newHTTP2Client
	/go/src/github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/transport/http2_client.go:299 +0xeee

goroutine 1012621 [select]:
github.com/cockroachdb/cockroach/pkg/storage.(*NodeLiveness).StartHeartbeat.func1(0x7f93ce0f3ea8, 0xc42f91d020)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/node_liveness.go:261 +0x29a
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc42f9c16d0, 0xc430db6480, 0xc42e0541e0)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:215 +0xf7
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:216 +0xad

goroutine 1011605 [semacquire]:
sync.runtime_notifyListWait(0xc42ff9f190, 0xc40000004b)
	/usr/local/go/src/runtime/sema.go:298 +0x10b
sync.(*Cond).Wait(0xc42ff9f180)
	/usr/local/go/src/sync/cond.go:57 +0x89
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).worker(0xc42c9b4180, 0xc430db6120)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:199 +0xac
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).Start.func2(0x7f93ce0f3ea8, 0xc430d001e0)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:168 +0x33
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc420faed30, 0xc430db6120, 0xc420233ac0)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:215 +0xf7
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:216 +0xad

goroutine 1009183 [chan receive]:
github.com/cockroachdb/cockroach/pkg/storage/engine.(*RocksDB).open.func2(0xc430ce0160)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/engine/rocksdb.go:430 +0x44
created by github.com/cockroachdb/cockroach/pkg/storage/engine.(*RocksDB).open
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/engine/rocksdb.go:431 +0x4c1

goroutine 1012472 [semacquire]:
sync.runtime_notifyListWait(0xc42f66bbd0, 0x1d)
	/usr/local/go/src/runtime/sema.go:298 +0x10b
sync.(*Cond).Wait(0xc42f66bbc0)
	/usr/local/go/src/sync/cond.go:57 +0x89
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).worker(0xc42c9b4880, 0xc430db6480)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:199 +0xac
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).Start.func2(0x7f93ce0f3ea8, 0xc42f91c5a0)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:168 +0x33
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc42f9c0900, 0xc430db6480, 0xc42f647300)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:215 +0xf7
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:216 +0xad

goroutine 1012438 [select]:
github.com/cockroachdb/cockroach/pkg/gossip.(*Gossip).manage.func1(0x7f93ce0f3ea8, 0xc42f323fb0)
	/go/src/github.com/cockroachdb/cockroach/pkg/gossip/gossip.go:1093 +0x325
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc42f9c0680, 0xc430db6000, 0xc42f9c0670)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:215 +0xf7
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:216 +0xad

goroutine 1011613 [semacquire]:
sync.runtime_notifyListWait(0xc42ff9f190, 0x59)
	/usr/local/go/src/runtime/sema.go:298 +0x10b
sync.(*Cond).Wait(0xc42ff9f180)
	/usr/local/go/src/sync/cond.go:57 +0x89
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).worker(0xc42c9b4180, 0xc430db6120)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:199 +0xac
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).Start.func2(0x7f93ce0f3ea8, 0xc430d00360)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:168 +0x33
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc420faedc0, 0xc430db6120, 0xc42f834000)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:215 +0xf7
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:216 +0xad

goroutine 1013709 [select]:
github.com/cockroachdb/cockroach/pkg/storage.(*RaftTransport).processQueue(0xc430d44000, 0xc400000001, 0xc42df84360, 0xc42f070280, 0x27a2120, 0xc42f7362e0, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/raft_transport.go:494 +0x697
github.com/cockroachdb/cockroach/pkg/storage.(*RaftTransport).connectAndProcess.func1(0xc430d44000, 0x1, 0x7f93ce0f3ea8, 0xc42f661d70, 0x0, 0x0, 0xc42f26e500, 0xc42df84360, 0xc42f070280, 0x0, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/raft_transport.go:439 +0x32e
github.com/cockroachdb/cockroach/pkg/storage.(*RaftTransport).connectAndProcess(0xc430d44000, 0x7f93ce0f3ea8, 0xc42f661d70, 0x1, 0xc42df84360, 0xc42f070280)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/raft_transport.go:440 +0xe9
github.com/cockroachdb/cockroach/pkg/storage.(*RaftTransport).SendAsync.func2.1(0x7f93ce0f3ea8, 0xc42f661d70)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/raft_transport.go:574 +0x60
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc42f736240, 0xc430db6000, 0xc42f661d40)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:215 +0xf7
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:216 +0xad

goroutine 1011774 [select]:
github.com/cockroachdb/cockroach/pkg/storage.(*baseQueue).processLoop.func1(0x7f93ce0f3ea8, 0xc430d00a20)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/queue.go:490 +0x364
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc420fafa90, 0xc430db6120, 0xc42f835020)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:215 +0xf7
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:216 +0xad

goroutine 1011616 [semacquire]:
sync.runtime_notifyListWait(0xc42ff9f190, 0x3f)
	/usr/local/go/src/runtime/sema.go:298 +0x10b
sync.(*Cond).Wait(0xc42ff9f180)
	/usr/local/go/src/sync/cond.go:57 +0x89
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).worker(0xc42c9b4180, 0xc430db6120)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:199 +0xac
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).Start.func2(0x7f93ce0f3ea8, 0xc42f660180)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:168 +0x33
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc420faedf0, 0xc430db6120, 0xc42f834060)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:215 +0xf7
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:216 +0xad

goroutine 1011571 [select]:
github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc.(*addrConn).transportMonitor(0xc4291c9d40)
	/go/src/github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/clientconn.go:908 +0x694
created by github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc.(*ClientConn).resetAddrConn
	/go/src/github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/clientconn.go:625 +0x73c

goroutine 1009177 [sleep]:
time.Sleep(0x989680)
	/usr/local/go/src/runtime/time.go:59 +0xf9
github.com/cockroachdb/cockroach/pkg/storage_test.TestReplicaRemovalCampaign.func1(0xc42f986000, 0xc430d38018, 0x1, 0x8, 0xc430d38080, 0x1, 0x8, 0xc42febff4a, 0xc42febff70)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/client_raft_test.go:2018 +0x4db
github.com/cockroachdb/cockroach/pkg/storage_test.TestReplicaRemovalCampaign(0xc42f986000)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/client_raft_test.go:2031 +0x184
testing.tRunner(0xc42f986000, 0x1bed1d8)
	/usr/local/go/src/testing/testing.go:657 +0x96
created by testing.(*T).Run
	/usr/local/go/src/testing/testing.go:697 +0x2ca

goroutine 1012502 [semacquire]:
sync.runtime_notifyListWait(0xc42f66bbd0, 0x3b)
	/usr/local/go/src/runtime/sema.go:298 +0x10b
sync.(*Cond).Wait(0xc42f66bbc0)
	/usr/local/go/src/sync/cond.go:57 +0x89
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).worker(0xc42c9b4880, 0xc430db6480)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:199 +0xac
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).Start.func2(0x7f93ce0f3ea8, 0xc42f91cb40)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:168 +0x33
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc42f9c0ae0, 0xc430db6480, 0xc42f647700)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:215 +0xf7
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:216 +0xad

goroutine 1012550 [select]:
github.com/cockroachdb/cockroach/pkg/gossip.(*client).gossip(0xc42f987520, 0x7f93ce0f3ea8, 0xc42f91ce10, 0xc43024e300, 0x27a1100, 0xc42f9c1730, 0xc430db6000, 0xc42f9c16f0, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/pkg/gossip/client.go:325 +0x3e2
github.com/cockroachdb/cockroach/pkg/gossip.(*client).startLocked.func1(0x7f93ce0f3ea8, 0xc42f91ce10)
	/go/src/github.com/cockroachdb/cockroach/pkg/gossip/client.go:132 +0x410
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc42f9c1220, 0xc430db6000, 0xc42f613640)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:215 +0xf7
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:216 +0xad

goroutine 1012482 [semacquire]:
sync.runtime_notifyListWait(0xc42f66bbd0, 0x27)
	/usr/local/go/src/runtime/sema.go:298 +0x10b
sync.(*Cond).Wait(0xc42f66bbc0)
	/usr/local/go/src/sync/cond.go:57 +0x89
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).worker(0xc42c9b4880, 0xc430db6480)
```

### PR DESCRIPTION
**Pull request by irfansharif**
Fixes #16184.
Fixes #16185.
Fixes #16193.

Check to see if replica hasn't been destroyed before updating proposal
quota, the resulting nil RaftStatus causes panics if a leader replica is
being destroyed.

### CODE REVIEW

File: pkg/storage/replica.go [hunk 1]
```diff
@@ -905,6 +905,10 @@ func (r *Replica) updateProposalQuotaRaftMuLocked(
 	// ourselves via looking at MsgAppResp messages would be overkill. Perhaps
 	// another accessor on RawNode.
 	status := r.raftStatusRLocked()
+	if status == nil {
```
Comment (tschottdorf) [inline pkg/storage/replica.go]: should this be higher up? Or, in case we don't have a Raft group, what happens in the code above this?

**Review by tbg — APPROVED** [review]

File: pkg/storage/replica.go (hunk 1 above)
Comment (irfansharif) [inline pkg/storage/replica.go]: it should be fine here, if we get to this codepath if you look we're not actually doing anything above. The mistake here was assuming proper initialization but as is in the case of the failures above, does not happen if the replica is destroyed ([here](https://github.com/irfansharif/cockroach/blob/79d6e2207fcb7c2977591ae856a6b0fbcda6a0d3/pkg/storage/replica.go#L2990-L2992), then [here](https://github.com/irfansharif/cockroach/blob/79d6e2207fcb7c2977591ae856a6b0fbcda6a0d3/pkg/storage/replica.go#L457) never reaching [here](https://github.com/irfansharif/cockroach/blob/79d6e2207fcb7c2977591ae856a6b0fbcda6a0d3/pkg/storage/replica.go#L486)).

Comment (tschottdorf) [inline pkg/storage/replica.go]: If the replica got destroyed, wouldn't the correct next step be destroying the quota pool as well? Otherwise (ok, and this is probably hard to get in practice) a replica could be destroyed but some goroutines are still waiting for quota and will never get it?

**Comment by tamird** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[pkg/storage/replica.go, line 908 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16187#-Kl9pDcDm2sS8OcJR7bW-r1-908:-KlAHlJFsM4d3aYU70yE:b8ez4oa) ([raw file](https://github.com/cockroachdb/cockroach/blob/79d6e2207fcb7c2977591ae856a6b0fbcda6a0d3/pkg/storage/replica.go#L908)):*
<details><summary><i>Previously, tschottdorf (Tobias Schottdorf) wrote…</i></summary><blockquote>

If the replica got destroyed, wouldn't the correct next step be destroying the quota pool as well? Otherwise (ok, and this is probably hard to get in practice) a replica could be destroyed but some goroutines are still waiting for quota and will never get it?
</blockquote></details>

This certainly needs a comment. For one, I can't tell what this means, particularly since the above code block prescribes that this replica is a leader or follower, both of which contradict this clause (which implies that the replica is being GC'ed).

Naively, I echo @tschottdorf's suggestion that this should result in some resource cleanup, though perhaps that's already being done elsewhere.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16187)*

**Comment by irfansharif** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[pkg/storage/replica.go, line 908 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16187#-Kl9pDcDm2sS8OcJR7bW-r1-908:-KlAdo_X80no-Yg5CPX3:b-7estr9) ([raw file](https://github.com/cockroachdb/cockroach/blob/79d6e2207fcb7c2977591ae856a6b0fbcda6a0d3/pkg/storage/replica.go#L908)):*
> replica could be destroyed but some goroutines are still waiting for quota and will never get it?

This is plausible, yes. Added.

>  I can't tell what this means, particularly since the above code block prescribes that this replica is a leader or follower, both of which contradict this clause (which implies that the replica is being GC'ed).

I was actually incorrect in saying this was due to improper initialization, the failure here occurs when a leader replica is being removed/destroyed (as in `Store.removeReplicaImpl`).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16187)*

**Comment by tamird** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[pkg/storage/replica.go, line 899 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/16187#-KlBOjEnZerd8ZrPhums:-KlBOjEoKsEQsbaHVx5i:b-eu0chb) ([raw file](https://github.com/cockroachdb/cockroach/blob/03302c551a4deb9353d8667ee4d6dd39b98cda0f/pkg/storage/replica.go#L899)):*
> ```Go
> 		// We're a follower.
> 		return
> 	}
> ```

how does the new case relate to this if statement? is it equivalent as an `else if` here?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16187)*

**Comment by irfansharif** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[pkg/storage/replica.go, line 899 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/16187#-KlBOjEnZerd8ZrPhums:-KlBm1d69v76TXa6jAtH:bg92lcq) ([raw file](https://github.com/cockroachdb/cockroach/blob/03302c551a4deb9353d8667ee4d6dd39b98cda0f/pkg/storage/replica.go#L899)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

how does the new case relate to this if statement? is it equivalent as an `else if` here?
</blockquote></details>

you _can_ make this into an `else if` but the if statement here deals with leadership transitions or the lack thereof as seen by followers, old leaders and new. The fall through case when the replication is _still_ the leader is where we need to close the quota pool if destroyed, so it should be fine as is.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16187)*

**Comment by irfansharif** [comment]
okay to merge?

File: pkg/storage/replica.go [hunk 2]
```diff
@@ -900,11 +900,25 @@ func (r *Replica) updateProposalQuotaRaftMuLocked(
...
+		return
+	}
+
 	// TODO(peter): Can we avoid retrieving the Raft status on every invocation
 	// in order to avoid the associated allocation? Tracking the progress
 	// ourselves via looking at MsgAppResp messages would be overkill. Perhaps
 	// another accessor on RawNode.
 	status := r.raftStatusRLocked()
+	if status == nil {
+		log.Fatal(ctx, "leader with nil internalRaftGroup")
```
Comment (tschottdorf) [inline pkg/storage/replica.go]: While this comment is true, what you're really complaining about is "leader with nil RaftStatus".

File: pkg/storage/replica.go [hunk 3]
```diff
@@ -900,11 +900,25 @@ func (r *Replica) updateProposalQuotaRaftMuLocked(
 
 	// We're still the leader.
 
+	// We need to check if the replica is being destroyed and if so, close the
+	// quota pool and unblock ongoing quota acquisition goroutines (if any).
+	if r.mu.destroyed != nil {
```
Comment (tschottdorf) [inline pkg/storage/replica.go]: Strikes me as odd that we need to do this here, and there is still a potential problem here that leaves clients hanging if the replica gets destroyed but this code path is never taken. Having taken a rough look at the ways in which replicas can get destroyed unfortunately convinced me that you shouldn't be burdened with addressing that as well - it's a bit of a mess.

**Comment by tschottdorf** [comment]
LGTM

**Comment by bdarnell** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions, all commit checks successful.

---

*[pkg/storage/replica.go, line 905 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/16187#-Kl9pDcDm2sS8OcJR7bW-r2-905:-KlM7eUZQOlhDPNMGRIo:bg12vwz) ([raw file](https://github.com/cockroachdb/cockroach/blob/03302c551a4deb9353d8667ee4d6dd39b98cda0f/pkg/storage/replica.go#L905)):*
<details><summary><i>Previously, tschottdorf (Tobias Schottdorf) wrote…</i></summary><blockquote>

Strikes me as odd that we need to do this here, and there is still a potential problem here that leaves clients hanging if the replica gets destroyed but this code path is never taken. Having taken a rough look at the ways in which replicas can get destroyed unfortunately convinced me that you shouldn't be burdened with addressing that as well - it's a bit of a mess.
</blockquote></details>

Yeah, it seems weird that we could "still be the leader" on a replica that's destroyed. Should we be closing proposalQuota in `Store.removeReplicaImpl`? I think there are only three ways a replica can be destroyed (the normal case in `Store.removeReplicaImpl`, `maybeSetCorrupt`, and merges), so it shouldn't be too bad to ensure that we clear our leader status and close the proposalQuota whenever the replica is destroyed. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16187)*

**Comment by irfansharif** [comment]
Review status: 0 of 1 files reviewed at latest revision, 4 unresolved discussions, some commit checks pending.

---

*[pkg/storage/replica.go, line 905 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/16187#-Kl9pDcDm2sS8OcJR7bW-r2-905:-KlM9zkml7QUBWeZ32Ym:b-vjhw0a) ([raw file](https://github.com/cockroachdb/cockroach/blob/03302c551a4deb9353d8667ee4d6dd39b98cda0f/pkg/storage/replica.go#L905)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

Yeah, it seems weird that we could "still be the leader" on a replica that's destroyed. Should we be closing proposalQuota in `Store.removeReplicaImpl`? I think there are only three ways a replica can be destroyed (the normal case in `Store.removeReplicaImpl`, `maybeSetCorrupt`, and merges), so it shouldn't be too bad to ensure that we clear our leader status and close the proposalQuota whenever the replica is destroyed. 
</blockquote></details>

this is a half measure. short of clearing the leader status before destroying the replica (or closing the pool before/after we destroy a replica) this patch should address the flakiness people are sure to run into tomorrow. added a TODO to follow up on points mentioned here.

---

*[pkg/storage/replica.go, line 919 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/16187#-Kl9pDcDm2sS8OcJR7bW-r2-919:-KlMA2kNdAqrDPegwt7b:b-a2ujfl) ([raw file](https://github.com/cockroachdb/cockroach/blob/03302c551a4deb9353d8667ee4d6dd39b98cda0f/pkg/storage/replica.go#L919)):*
<details><summary><i>Previously, tschottdorf (Tobias Schottdorf) wrote…</i></summary><blockquote>

While this comment is true, what you're really complaining about is "leader with nil RaftStatus".
</blockquote></details>

Changed.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16187)*
