### PR TITLE
changefeedccl: deflake TestShowChangefeedJobsRedacted

### LINKED ISSUE #151280: ccl/changefeedccl: TestShowChangefeedJobsRedacted failed
ccl/changefeedccl.TestShowChangefeedJobsRedacted [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Ci_TestsAwsLinuxArm64_UnitTests/20288446?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Ci_TestsAwsLinuxArm64_UnitTests/20288446?buildTab=artifacts#/) on master @ [a4ad94ae1379daa20b467c89d09de27ba8e2356d](https://github.com/cockroachdb/cockroach/commits/a4ad94ae1379daa20b467c89d09de27ba8e2356d):

```
=== RUN   TestShowChangefeedJobsRedacted
    test_log_scope.go:171: test logs captured to: /artifacts/tmp/_tmp/875edb2a1d3b708cdd086a008bbab2b7/logTestShowChangefeedJobsRedacted1840918762
    test_log_scope.go:82: use -show-logs to present logs inline
    helpers_test.go:1383: making server as secondary tenant
    changefeed_stmt.go:1584: requireNoFeedsFail: unexpected error: recv msg error: grpc: context canceled [code 1/Canceled]
    show_changefeed_jobs_test.go:232: -- test log scope end --
test logs left over in: /artifacts/tmp/_tmp/875edb2a1d3b708cdd086a008bbab2b7/logTestShowChangefeedJobsRedacted1840918762
--- FAIL: TestShowChangefeedJobsRedacted (1.73s)
```
<details><summary>Help</summary>
<p>

See also: [How To Investigate a Go Test Failure \(internal\)](https://cockroachlabs.atlassian.net/l/c/HgfXfJgM)
</p>
</details>
/cc @cockroachdb/cdc
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*TestShowChangefeedJobsRedacted.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/bazci/githubpost/issues)

</sub>

Jira issue: CRDB-53159

### PR DESCRIPTION
**Pull request by KeithCh**
This test was failing when all of the subtests were passing, which
points to that the test was not cleaned up correctly.

This commit uses the cdctest helper, and has run successfully over
4000 time without a flake.

Fixes: #151280
Release note: none

### CODE REVIEW

**Review by log-head — APPROVED** [review]
lgtm!

File: pkg/ccl/changefeedccl/show_changefeed_jobs_test.go [hunk 1]
```diff
@@ -213,22 +213,28 @@ func TestShowChangefeedJobsRedacted(t *testing.T) {
...
+			testutils.SucceedsWithin(t, func() error {
+				var status string
+				sqlDB.QueryRow(t, "SELECT status FROM [SHOW CHANGEFEED JOB $1]", jobID).Scan(&status)
+				if status != "canceled" {
+					return errors.Newf("expected job status canceled, got %s", status)
+				}
+				return nil
+			}, 1*time.Minute)
 			replacer := strings.NewReplacer(apiSecret, "redacted", certSecret, "redacted")
 			expectedSinkURI := replacer.Replace(tc.uri)
```
Comment (andyyang890) [inline pkg/ccl/changefeedccl/show_changefeed_jobs_test.go]: Not code that you wrote but could you delete the unused `expectedSinkURI` and `expectedDescription` fields in the test cases?

File: pkg/ccl/changefeedccl/show_changefeed_jobs_test.go [hunk 2]
```diff
@@ -213,22 +213,28 @@ func TestShowChangefeedJobsRedacted(t *testing.T) {
 			sqlDB.QueryRow(t, createStmt).Scan(&jobID)
 			var sinkURI, description string
 			sqlDB.QueryRow(t, "SELECT sink_uri, description from [SHOW CHANGEFEED JOB $1]", jobID).Scan(&sinkURI, &description)
+			sqlDB.Query(t, "CANCEL ALL CHANGEFEED JOBS")
```
Comment (andyyang890) [inline pkg/ccl/changefeedccl/show_changefeed_jobs_test.go]: > The changefeeds created in the test were not shutting down before
the test was complete. This caused the overall test to fail even though
the subtests were all passing.

Could you say more about why this would cause the test to fail?

Comment (KeithCh) [reply pkg/ccl/changefeedccl/show_changefeed_jobs_test.go]: This test also will flake with a different issue
```
panic: found 1 short-living non-stopped monitors in flow-c57120f9
	flow-c57120f9 0 B
	    changefntr-mem 0 B
```
My hypothesis for that was the changefeed did not have time to shut down properly before the test was over, which is why I added the `SucceedsWithin`. What I noticed is that all subsequent test runs no longer had the original error, and only the panic above (frequency of the panic did not change). This change should also handle the panic, but something is holding a txn in that table, and is blocking the read from the jobs table.

There might be some extra changes that are not needed like removing the extra subtest case, which I'll do before I make it ready for review again.

Comment (KeithCh) [reply pkg/ccl/changefeedccl/show_changefeed_jobs_test.go]: Changed to use `cdctest`, which removed the flakes (over 4000+ runs).

File: pkg/ccl/changefeedccl/show_changefeed_jobs_test.go [hunk 3]
```diff
@@ -166,69 +165,63 @@ func TestShowChangefeedJobsRedacted(t *testing.T) {
...
+			{
+				name: "sasl_password",
+				uri:  fmt.Sprintf("kafka://nope/?sasl_enabled=true&sasl_handshake=false&sasl_password=%s&sasl_user=aa", apiSecret),
+			},
+			{
+				name: "ca_cert",
+				uri:  fmt.Sprintf("kafka://nope?ca_cert=%s&tls_enabled=true", certSecret),
+			},
+			{
+				name: "api_secret",
```
Comment (andyyang890) [inline pkg/ccl/changefeedccl/show_changefeed_jobs_test.go]: super nit: can we keep this in the same order

**Review by andyyang890 — APPROVED** [review]
Nice!

**Comment by KeithCh** [comment]
bors r=log-head,andyyang890 TFTRs!
