### PR TITLE
roachtest: update django version

### LINKED ISSUE #86010: roachtest: django failed
roachtest.django [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/6064717?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/6064717?buildTab=artifacts#/django) on master @ [773f7d4445ce3e0e806b7a182adba70a0f270f19](https://github.com/cockroachdb/cockroach/commits/773f7d4445ce3e0e806b7a182adba70a0f270f19):

```
test artifacts and logs in: /artifacts/django/run_1
	orm_helpers.go:141,orm_helpers.go:117,django.go:223,django.go:234,test_runner.go:896: No tests ran! Fix the testing commands.
```
<p>Parameters: <code>ROACHTEST_cloud=gce</code>
, <code>ROACHTEST_cpu=16</code>
, <code>ROACHTEST_ssd=0</code>
</p>
<details><summary>Help</summary>
<p>

See: [roachtest README](https://github.com/cockroachdb/cockroach/blob/master/pkg/cmd/roachtest/README.md)

See: [How To Investigate \(internal\)](https://cockroachlabs.atlassian.net/l/c/SSSBr8c7)

</p>
</details>
/cc @cockroachdb/sql-experience
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*django.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)
</sub>

Jira issue: CRDB-18524

### PR DESCRIPTION
**Pull request by ZhouXing19**
fixes https://github.com/cockroachdb/cockroach/issues/86010

Release justification: bug fix
Release note: none

### CODE REVIEW

**Review by ecwall — APPROVED** [review]

**Comment by ZhouXing19** [comment]
TFTR!
bors r=ecwall

File: pkg/cmd/roachtest/tests/django.go [hunk 1]
```diff
@@ -27,8 +27,8 @@ import (
 var djangoReleaseTagRegex = regexp.MustCompile(`^(?P<major>\d+)\.(?P<minor>\d+)(\.(?P<point>\d+))?$`)
 var djangoCockroachDBReleaseTagRegex = regexp.MustCompile(`^(?P<major>\d+)\.(?P<minor>\d+)$`)
 
-var djangoSupportedTag = "cockroach-4.0.x"
-var djangoCockroachDBSupportedTag = "4.0.*"
+var djangoSupportedTag = "cockroach-4.1.x"
+var djangoCockroachDBSupportedTag = "4.1"
```
Comment (timgraham) [inline pkg/cmd/roachtest/tests/django.go:31]: This should be `4.1.*` (with dot star) to always use the latest minor release of django-cockroachdb.
