### PR TITLE
sql: fix multiplication incorrect of float and interval

### LINKED ISSUE #37540: sql: incorrect float * interval with
```
SELECT .5 * '1 mon 2 day 2:00:00'::INTERVAL
```

postgres:
```
16 days 01:00:00
```

cockroach:
```
1 day 01:00:00
```

Cockroach doesn't do the same month -> day conversion during float multiply that postgres does.

### PR DESCRIPTION
**Pull request by hueypark**
Fixes #37540

Release note (bug fix): fix multiplication incorrect of float and interval

### CODE REVIEW

File: pkg/util/duration/duration.go [hunk 1]
```diff
@@ -30,6 +30,8 @@ const (
 	daysInMonth   = 30
 	nanosInDay    = 24 * int64(time.Hour) // Try as I might, couldn't do this without the cast.
 	nanosInMonth  = daysInMonth * nanosInDay
+	nanosInHour   = nanosInMinute * 60
```
Comment (mjibson) [inline pkg/util/duration/duration.go]: These should be moved to somewhere in duration_test.go since they are only used in tests.

Comment (hueypark) [reply pkg/util/duration/duration.go]: Thank you. I've fixed this problem.

**Review by madelynnblue — APPROVED** [review]
