### PR TITLE
crosscluster: fix TestStandbyReadTSPollerJob test flake

### LINKED ISSUE #131611: ccl/crosscluster/physical: TestStandbyReadTSPollerJob failed
ccl/crosscluster/physical.TestStandbyReadTSPollerJob [failed](https://mesolite.cluster.engflow.com/invocations/default/54ae3aad-9890-411d-be15-8902df428ecf?testReportRun=1&testReportShard=13&testReportAttempt=1#targets-Ly9wa2cvY2NsL2Nyb3NzY2x1c3Rlci9waHlzaWNhbDpwaHlzaWNhbF90ZXN0) on master @ [9497f05a5c1b316fbc5fe6cd833ed43e6c118a79](https://github.com/cockroachdb/cockroach/commits/9497f05a5c1b316fbc5fe6cd833ed43e6c118a79):

```
=== RUN   TestStandbyReadTSPollerJob
    test_log_scope.go:170: test logs captured to: outputs.zip/logTestStandbyReadTSPollerJob2930340887
    test_log_scope.go:81: use -show-logs to present logs inline
    standby_read_ts_poller_job_test.go:62: error scanning '&{0xc00cddfe60 <nil>}': pq: database "defaultdb" does not exist
    panic.go:626: -- test log scope end --
test logs left over in: outputs.zip/logTestStandbyReadTSPollerJob2930340887
--- FAIL: TestStandbyReadTSPollerJob (6.20s)
```

Parameters:
 - <code>attempt=1</code>
 - <code>run=1</code>
 - <code>shard=13</code>
<details><summary>Help</summary>
<p>

See also: [How To Investigate a Go Test Failure \(internal\)](https://cockroachlabs.atlassian.net/l/c/HgfXfJgM)
</p>
</details>
/cc @cockroachdb/disaster-recovery
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*TestStandbyReadTSPollerJob.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/bazci/githubpost/issues)
</sub>

Jira issue: CRDB-42634

### PR DESCRIPTION
**Pull request by azhu-crl**
This patch reduces the runtime of this test from 50s to 15s. To cut the
remaining fat:
- Each WaitForReplicatedTime call takes about 5s. Other tests take this long
  too.
- We wait 5 seconds for the AOST the reader tenant uses to observe the
  replicated data.

Fixes: https://github.com/cockroachdb/cockroach/issues/131611
Release note: None

### CODE REVIEW

File: pkg/ccl/crosscluster/physical/standby_read_ts_poller_job_test.go [hunk 1]
```diff
@@ -54,23 +51,28 @@ func TestStandbyReadTSPollerJob(t *testing.T) {
...
+	srcTime = c.SrcCluster.Server(0).Clock().Now()
+	c.WaitUntilReplicatedTime(srcTime, jobspb.JobID(ingestionJobID))
+
 	pollInterval := time.Microsecond
 	serverutils.SetClusterSetting(t, c.DestCluster, "bulkio.stream_ingestion.standby_read_ts_poll_interval", pollInterval)
 
+	waitForPollerJobToStart(t, c)
+
 	var jobID jobspb.JobID
 	c.ReaderTenantSQL.QueryRow(t, `
```
Comment (msbutler) [inline pkg/ccl/crosscluster/physical/standby_read_ts_poller_job_test.go:69]: could we push this logic around waiting for the poller job to run into your `waitForPollerJobToStart` helper, and maybe rename it to `waitForPollerToRun`?

File: pkg/ccl/crosscluster/physical/standby_read_ts_poller_job_test.go [hunk 2]
```diff
@@ -54,23 +51,28 @@ func TestStandbyReadTSPollerJob(t *testing.T) {
 	readerTenantName := fmt.Sprintf("%s-readonly", args.DestTenantName)
 	c.ConnectToReaderTenant(ctx, readerTenantID, readerTenantName, 0)
 
+	c.SrcTenantSQL.Exec(t, `
+USE defaultdb;
+CREATE TABLE a (i INT PRIMARY KEY);
```
Comment (msbutler) [inline pkg/ccl/crosscluster/physical/standby_read_ts_poller_job_test.go:56]: i'm trying to understand what the minimum change necessary to deflake this:
- did we only need to add the `waitUntilReplicatedTime` msg?
- or did we also need to push up this create table stmt as well?

File: pkg/ccl/crosscluster/replicationtestutils/testutils.go [hunk 3]
```diff
@@ -208,6 +208,10 @@ func (c *TenantStreamingClusters) ConnectToReaderTenant(
 		TenantName:  roachpb.TenantName(tenantName),
 		UseDatabase: "defaultdb",
 	})
+	c.DestSysSQL.Exec(c.T, `ALTER TENANT $1 SET CLUSTER SETTING jobs.registry.interval.adopt = '1s'`, tenantName)
+	c.DestSysSQL.Exec(c.T, `ALTER TENANT $1 SET CLUSTER SETTING bulkio.stream_ingestion.standby_read_ts_poll_interval = '500ms'`, tenantName)
+	// TODO(annezhu): speed up the ts we use for historical queries.
```
Comment (msbutler) [inline pkg/ccl/crosscluster/replicationtestutils/testutils.go:213]: @fqazi any tips for speeding up the rate that `watchForUpdates` gets called by the lease manager, so the historical timestamp doesn't lag too far behind? I tried bumping the usual rangefeed settings, but that didn't help. nor did `SET CLUSTER SETTING sql.catalog.descriptor_lease_duration='30s';`

Comment (fqazi) [reply pkg/ccl/crosscluster/replicationtestutils/testutils.go:213]: Its probably linked to the closed timestamp, we can try reducing: kv.rangefeed.closed_timestamp_refresh_interval setting. Since that determines the timestamp that we are selecting, we pick the next closed one to ensure no updates show up.

Comment (msbutler) [reply pkg/ccl/crosscluster/replicationtestutils/testutils.go]: alas, that didn't work. We'll look into this outside of this PR.

**Comment by msbutler** [comment]
created a tracking issue for further reducing the runtime of these e2e tests: https://github.com/cockroachdb/cockroach/issues/132159

**Review by dt — APPROVED** [review]

**Comment by msbutler** [comment]
TFTR!

bors r=dt
