### PR TITLE
release-22.1: sql: better instruction for creating HSI in mixed version cluster

### LINKED ISSUE #83447: sql: bad version-gating of new hash-sharded behaviour
**Describe the problem**

Although we have been careful to version-gate the hash-sharding implementation in 22.1, it appears there's still at least one mixed-version cluster bug.

**To Reproduce**

```
$ roachprod create $CLUSTER -n 3
$ roachprod stage $CLUSTER release v21.2.10
$ roachprod sql $CLUSTER:1
```
At which point we disable auto-upgrades:
```
root@localhost:26257/defaultdb> SET CLUSTER SETTING cluster.preserve_downgrade_option = '21.2';
```
Now lets replace all the binaries:
```
$ roachprod stage $CLUSTER release v22.1.2
$ roachprod stop $CLUSTER:3
$ roachprod start $CLUSTER:3
$ roachprod stop $CLUSTER:2
$ roachprod start $CLUSTER:2
$ roachprod stop $CLUSTER:1
$ roachprod start $CLUSTER:1
```
I checked that the cluster version was still 21.2 and tried to create a hash-sharded index:
```
$ roachprod sql $CLUSTER:1
root@localhost:26257/defaultdb> SHOW CLUSTER SETTINGS;
...
  version                                                                   | 21.2                                                               | m            | set the active cluster version in the format '<major>.<minor>'
(206 rows)


Time: 11ms total (execution 3ms / network 8ms)

root@localhost:26257/defaultdb> CREATE TABLE kv (k INT PRIMARY KEY, v STRING);                 
CREATE TABLE


Time: 11ms total (execution 11ms / network 0ms)

root@localhost:26257/defaultdb> ALTER TABLE kv ALTER PRIMARY KEY USING COLUMNS (k) USING HASH WITH BUCKET_COUNT = 8;
ERROR: relation "kv" (52): primary index column "crdb_internal_k_shard_8" cannot be virtual
```

**Expected behavior**
The ALTER PRIMARY KEY statement should not fail with a validation error. (edited)

Jira issue: CRDB-17074

### PR DESCRIPTION
**Pull request by chengxiong-ruan**
Backport 1/1 commits from #83521.
Fixes #83447

/cc @cockroachdb/release

---

Previously, we threw out an error indicating virtual columns not allowed in
primary key when creating hash sharded index in mixed version cluster with
upgrading from pre-22.1. With this commit, we will return better instructions
with options of what to do insteading confusing them with validation errors.
We still keep the validation as the last line of guard.

Note that, we won't prevent user from doing the work around in which a stored
shard column is created manually.

Release justification: There was a support issue where user got confused by
the insufficient validation error message. This commit adds more helpful
instructions to better educate users what is happening.

Release note (sql change): Previously, we simply threw a descriptor validation
error when a user tries to create hash sharded index in a mixed version cluster
upgrading from pre-22.1, which is confusing to user. Now, we return a message
instructing users to run the statement from a pre-22.1 node before the upgrade
is finalized or just wait until the upgrade is finalied.

### CODE REVIEW

File: pkg/sql/create_index.go [hunk 1]
```diff
@@ -585,6 +590,15 @@ func maybeCreateAndAddShardCol(
...
 		return nil, err
 	}
+
+	if !cv.IsActive(clusterversion.Start22_1) {
+		return nil, pgerror.Newf(
+			pgcode.FeatureNotSupported,
+			"cannot create hash sharded index on a node running binary newer than 21.2 in a mixed version cluster "+
+				"during a cluster upgrade from pre-22.1. Please run the schema change on a node still running pre-22.1 binary "+
+				"or wait until the cluster upgrade finalized to 22.1. Hash sharded indexes have been improved in 22.1 to use "+
+				"a virtual column and can be added more efficiently")
```
Comment (postamar) [inline pkg/sql/create_index.go:600]: Use `errors.WithHint` and `errors.WithDetail` to break down this message into smaller parts, this is too long.

File: pkg/sql/schema_changer_test.go [hunk 2]
```diff
@@ -8286,6 +8286,46 @@ func TestVirtualColumnNotAllowedInPkeyBefore22_1(t *testing.T) {
...
+		BinaryVersionOverride:          clusterversion.ByKey(clusterversion.V21_2),
+	}
+
+	s, sqlDB, _ := serverutils.StartServer(t, params)
+	defer s.Stopper().Stop(ctx)
+
+	expectedErrMsg := "pq: cannot create hash sharded index on a node running binary newer than 21.2 in a mixed version cluster " +
+		"during a cluster upgrade from pre-22.1. Please run the schema change on a node still running pre-22.1 binary " +
+		"or wait until the cluster upgrade finalized to 22.1. Hash sharded indexes have been improved in 22.1 to use " +
+		"a virtual column and can be added more efficiently"
```
Comment (postamar) [inline pkg/sql/schema_changer_test.go:8307]: nit: consider defining your error message as a `const` in `create_index.go` or use `require.Regexp` instead.

File: pkg/sql/create_index.go [hunk 3]
```diff
@@ -585,6 +590,15 @@ func maybeCreateAndAddShardCol(
 	if err != nil && !columnIsUndefined {
 		return nil, err
 	}
+
+	if !cv.IsActive(clusterversion.Start22_1) {
```
Comment (postamar) [inline pkg/sql/create_index.go:594]: Your builds are all failing because for some reason you're not importing `clusterversion`. I'm surprised that your IDE did not add the import for you, actually.

**Review by postamar — APPROVED** [review]

File: pkg/sql/create_index.go (hunk 3 above)
Comment (chengxiong-ruan) [reply pkg/sql/create_index.go:595]: oh...I created this pr from the other pr with the backporting tool... crdb is evolving

**Comment by chengxiong-ruan** [comment]
TFTR!
