### PR TITLE
sql: allow inverted indexes on mixed-case cols

### LINKED ISSUE #42944: Create inverted index ignores the case of the column name
**Describe the problem**

No inverted index creation is possible, if column name is case-sensitive.

**To Reproduce**

Table:
```SQL
CREATE TABLE phone (
  id UUID NOT NULL DEFAULT gen_random_uuid(),
  "idPerms" JSONB NOT NULL
);
```
Create index ignores the case (see column name in the error):
```SQL
create inverted index on phone ("idPerms");
pq: verify-inverted-idx-count: column "idperms" does not exist
```
But for non existing field another error appears:
```SQL
create inverted index on phone ("Test");
pq: index "phone_Test_idx" contains unknown column "Test"
```
For secondary index case matters and I get the right error message:
```SQL
create index on phone ("idPerms");
pq: unimplemented: column idPerms is of type jsonb and thus is not indexable
HINT: You have attempted to use a feature that is not yet implemented.
See: https://github.com/cockroachdb/cockroach/issues/35730
```

It works, if column name is case-sensitive, but lower cased:
```SQL
CREATE TABLE phone2 (
  id UUID NOT NULL DEFAULT gen_random_uuid(),
  "idperms" JSONB NOT NULL
);
CREATE TABLE

Time: 14.222225ms

create inverted index on phone2 ("idperms");
CREATE INDEX
```

**Expected behavior**
Yeah, that I can create an index for JSONB column with case-sensitive name.

**Additional data / screenshots**
-

**Environment:**
 - CockroachDB version: cockroachdb/cockroach:v19.2.0 from docker hub
 - Server OS: ubuntu 18.04
 - Client app: `cockroach sql`

**Additional context**
No index creation possible for a standard field of every table.

### PR DESCRIPTION
**Pull request by jordanlewis**
Closes #42944.

Previously, a bug prevented creation of inverted indexes on columns with
mixed-case identifiers. Now, the bug is fixed.

Release note (bug fix): it is now possible to create inverted indexes on
columns whose names are mixed-case.

### CODE REVIEW

File: pkg/sql/backfill.go [hunk 1]
```diff
@@ -1243,7 +1243,7 @@ func (sc *SchemaChanger) validateInvertedIndexes(
 				row, err := ie.QueryRowEx(ctx, "verify-inverted-idx-count", txn,
 					sqlbase.InternalExecutorSessionDataOverride{},
 					fmt.Sprintf(
-						`SELECT coalesce(sum_int(crdb_internal.json_num_index_entries(%s)), 0) FROM [%d AS t]`,
+						`SELECT coalesce(sum_int(crdb_internal.json_num_index_entries(%q)), 0) FROM [%d AS t]`,
```
Comment (rohany) [inline pkg/sql/backfill.go]: Does this still execute if no rows were backfilled?

**Comment by rohany** [comment]
Wow, what a silly bug...

File: pkg/sql/backfill.go (hunk 1 above)
Comment (jordanlewis) [reply pkg/sql/backfill.go]: Yes.

**Comment by rohany** [comment]
LGTM

**Comment by jordanlewis** [comment]
bors r+

tftr!
