### PR TITLE
cloud: fix missing shared config profile error on kms backups

### LINKED ISSUE #134214: backupccl: failing to initialize aws config during backup to s3
**Describe the problem**

On a cluster running `v24.3-alpha`, backup jobs are failing with a `could not initialize aws config: failed to get shared config profile, default`. Cluster was originally not running for 3-4 weeks, then restarted and upgraded to `v24.3-alpha`. A file is seen being written to S3 before it fails.

Slack threads:
\- https://cockroachlabs.slack.com/archives/C063CP41TG9/p1730495556648999

**Environment:**
 - CockroachDB version: `v24.3-alpha`
 - Server OS: unknown

Jira issue: CRDB-43979

### PR DESCRIPTION
**Pull request by kev-cao**
Backups with KMS keys fail due to a missing shared config profile `default` after the upgrade to the AWS SDK V2. This is due to a bad port over to the V2 SDK where we enforce that the `default` shared config must be used for implicit auth on AWS KMS. As we now use `config.LoadDefaultConfig` to load the client configuration, it will automatically attempt to load the shared config but ignore the error if it does not exist. We should not explicitly specify that the shared config must be used or else it will error upon failing to find it.

Fixes: #134214

Epic: none

Release note (bug fix): Fixed AWS backup/restore with kms failing due to missing shared config.

### CODE REVIEW

File: pkg/cloud/amazon/aws_kms.go [hunk 1]
```diff
@@ -185,7 +185,6 @@ func MakeAWSKMS(ctx context.Context, uri string, env cloud.KMSEnv) (cloud.KMS, e
 			return nil, errors.New(
 				"implicit credentials disallowed for s3 due to --external-io-disable-implicit-credentials flag")
 		}
-		addLoadOption(config.WithSharedConfigProfile(config.DefaultSharedConfigProfile))
```
Comment (msbutler) [inline pkg/cloud/amazon/aws_kms.go:188]: nice sleuthing! is it possible to add a unit test that would have failed due to this bug? See the Cloud Unit test nightly  suite: https://teamcity.cockroachdb.com/viewType.html?buildTypeId=Cockroach_Nightlies_CloudUnitTests&branch_Cockroach_Nightlies=129938&tab=buildTypeStatusDiv

File: pkg/cloud/amazon/aws_kms_test.go [hunk 2]
```diff
@@ -98,8 +98,7 @@ func TestEncryptDecryptAWS(t *testing.T) {
 		// https://docs.aws.com/cli/latest/userguide/cli-configure-role.html
 		// We only run this test if default role exists.
 		ctx := context.Background()
-		cfg, err := config.LoadDefaultConfig(ctx,
-			config.WithSharedConfigProfile(config.DefaultSharedConfigProfile))
```
Comment (kev-cao) [inline pkg/cloud/amazon/aws_kms_test.go:102]: Our `implicit` tests shouldn't be enforcing that a `DefaultSharedConfigProfile` is loaded

File: pkg/cloud/amazon/s3_storage_test.go [hunk 3]
```diff
@@ -64,13 +64,9 @@ func skipIfNoDefaultConfig(t *testing.T, ctx context.Context) {
 	t.Helper()
 	const helpMsg = "we only run this test if a default role exists, " +
 		"refer to https://docs.aws.com/cli/latest/userguide/cli-configure-role.html"
-	config, err := config.LoadDefaultConfig(ctx,
-		config.WithSharedConfigProfile(config.DefaultSharedConfigProfile))
-	if err != nil && err.Error() == "failed to get shared config profile, default" {
-		skip.IgnoreLintf(t, "%s: %s", helpMsg, err)
-	}
```
Comment (kev-cao) [inline pkg/cloud/amazon/s3_storage_test.go:71]: Same reasoning here — we should not enforce that a `DefaultSharedConfigProfile` exists as for auth implicit tests it shouldn't need to

**Review by msbutler — APPROVED** [review]
Nice!

**Comment by kev-cao** [comment]
TFTR!

bors r=msbutler
