### PR TITLE
sql: ensure that the GC deadline has expired before truncating table

### LINKED ISSUE #20745: teamcity: failed tests on master: test/TestTruncateWhileColumnBackfill, test/TestTruncateWhileColumnBackfill
The following tests appear to have failed:

[#444469](https://teamcity.cockroachdb.com/viewLog.html?buildId=444469):

```
--- FAIL: test/TestTruncateWhileColumnBackfill (0.000s)
Test ended in panic.

------- Stdout: -------
W171215 01:25:42.190106 86899 server/status/runtime.go:109  Could not parse build timestamp: parsing time "" as "2006/01/02 15:04:05": cannot parse "" as "2006"
I171215 01:25:42.192814 86899 server/config.go:521  [n?] 1 storage engine initialized
I171215 01:25:42.192870 86899 server/config.go:524  [n?] RocksDB cache size: 128 MiB
I171215 01:25:42.192895 86899 server/config.go:524  [n?] store 0: in-memory, size 0 B
I171215 01:25:42.196601 86899 server/node.go:362  [n?] **** cluster 57ebcdb5-4022-47e2-9502-4c4008264b25 has been created
I171215 01:25:42.196651 86899 server/server.go:927  [n?] **** add additional nodes by specifying --join=127.0.0.1:41199
I171215 01:25:42.197805 86899 storage/store.go:1202  [n1,s1] [n1,s1]: failed initial metrics computation: [n1,s1]: system config not yet available
I171215 01:25:42.197874 86899 server/node.go:487  [n1] initialized store [n1,s1]: disk (capacity=512 MiB, available=512 MiB, used=0 B, logicalBytes=3.2 KiB), ranges=1, leases=0, writes=0.00, bytesPerReplica={p10=3322.00 p25=3322.00 p50=3322.00 p75=3322.00 p90=3322.00}, writesPerReplica={p10=0.00 p25=0.00 p50=0.00 p75=0.00 p90=0.00}
I171215 01:25:42.197913 86899 server/node.go:340  [n1] node ID 1 initialized
I171215 01:25:42.197984 86899 gossip/gossip.go:333  [n1] NodeDescriptor set to node_id:1 address:<network_field:"tcp" address_field:"127.0.0.1:41199" > attrs:<> locality:<> ServerVersion:<major_val:1 minor_val:1 patch:0 unstable:6 > 
I171215 01:25:42.198154 86899 storage/stores.go:332  [n1] read 0 node addresses from persistent storage
I171215 01:25:42.198250 86899 server/node.go:628  [n1] connecting to gossip network to verify cluster ID...
I171215 01:25:42.199629 86899 server/node.go:653  [n1] node connected via gossip and verified as part of cluster "57ebcdb5-4022-47e2-9502-4c4008264b25"
I171215 01:25:42.199660 86899 server/node.go:429  [n1] node=1: started with [<no-attributes>=<in-mem>] engine(s) and attributes []
I171215 01:25:42.199734 86899 sql/distsql_physical_planner.go:121  [n1] creating DistSQLPlanner with address {tcp 127.0.0.1:41199}
I171215 01:25:42.203757 86899 server/server.go:1153  [n1] starting https server at 127.0.0.1:33127
I171215 01:25:42.203800 86899 server/server.go:1154  [n1] starting grpc/postgres server at 127.0.0.1:41199
I171215 01:25:42.203821 86899 server/server.go:1155  [n1] advertising CockroachDB node at 127.0.0.1:41199
W171215 01:25:42.203849 86899 sql/jobs/registry.go:219  [n1] unable to get node liveness: node not in the liveness table
I171215 01:25:42.206006 87102 storage/replica_command.go:1231  [split,n1,s1,r1/1:/M{in-ax}] initiating a split of this range at key /System/"" [r2]
I171215 01:25:42.216044 87102 storage/replica_command.go:1231  [split,n1,s1,r2/1:/{System/-Max}] initiating a split of this range at key /System/NodeLiveness [r3]
W171215 01:25:42.219012 87148 storage/intent_resolver.go:324  [n1,s1] failed to push during intent resolution: failed to push "sql txn implicit" id=7f1c4727 key=/Table/SystemConfigSpan/Start rw=true pri=0.00858754 iso=SERIALIZABLE stat=PENDING epo=0 ts=1513301142.209756000,0 orig=1513301142.209756000,0 max=1513301142.209756000,0 wto=false rop=false seq=7
I171215 01:25:42.220256 86899 sql/event_log.go:113  [n1] Event: "alter_table", target: 12, info: {TableName:eventlog Statement:ALTER TABLE system.eventlog ALTER COLUMN "uniqueID" SET DEFAULT uuid_v4() User:node MutationID:0 CascadeDroppedViews:[]}
I171215 01:25:42.225454 87102 storage/replica_command.go:1231  [split,n1,s1,r3/1:/{System/NodeL…-Max}] initiating a split of this range at key /System/NodeLivenessMax [r4]
I171215 01:25:42.231211 86899 sql/event_log.go:113  [n1] Event: "set_cluster_setting", target: 0, info: {SettingName:diagnostics.reporting.enabled Value:true User:node}
I171215 01:25:42.238065 87102 storage/replica_command.go:1231  [split,n1,s1,r4/1:/{System/NodeL…-Max}] initiating a split of this range at key /System/tsd [r5]
I171215 01:25:42.260913 86899 sql/event_log.go:113  [n1] Event: "set_cluster_setting", target: 0, info: {SettingName:version Value:$1 User:node}
I171215 01:25:42.265390 87102 storage/replica_command.go:1231  [split,n1,s1,r5/1:/{System/tsd-Max}] initiating a split of this range at key /System/"tse" [r6]
I171215 01:25:42.266529 87132 sql/lease.go:348  [n1] publish: descID=12 (eventlog) version=2 mtime=2017-12-15 01:25:42.266216349 +0000 UTC
W171215 01:25:42.268114 86944 storage/intent_resolver.go:324  [n1,s1] failed to push during intent resolution: failed to push "sql txn implicit" id=d76c2a6d key=/Table/SystemConfigSpan/Start rw=true pri=0.07386268 iso=SERIALIZABLE stat=PENDING epo=0 ts=1513301142.262537313,0 orig=1513301142.262537313,0 max=1513301142.262537313,0 wto=false rop=false seq=8
I171215 01:25:42.274909 86899 sql/event_log.go:113  [n1] Event: "set_cluster_setting", target: 0, info: {SettingName:trace.debug.enable Value:false User:node}
I171215 01:25:42.275028 87102 storage/replica_command.go:1231  [split,n1,s1,r6/1:/{System/tse-Max}] initiating a split of this range at key /Table/SystemConfigSpan/Start [r7]
I171215 01:25:42.282562 87102 storage/replica_command.go:1231  [split,n1,s1,r7/1:/{Table/System…-Max}] initiating a split of this range at key /Table/11 [r8]
I171215 01:25:42.286117 86899 server/server.go:1213  [n1] done ensuring all necessary migrations have run
I171215 01:25:42.286200 86899 server/server.go:1216  [n1] serving sql connections
I171215 01:25:42.287664 87102 storage/replica_command.go:1231  [split,n1,s1,r8/1:/{Table/11-Max}] initiating a split of this range at key /Table/12 [r9]
I171215 01:25:42.289261 87209 sql/event_log.go:113  [n1] Event: "node_join", target: 1, info: {Descriptor:{NodeID:1 Address:{NetworkField:tcp AddressField:127.0.0.1:41199} Attrs: Locality: ServerVersion:1.1-6} ClusterID:57ebcdb5-4022-47e2-9502-4c4008264b25 StartedAt:1513301142199638603 LastUp:1513301142199638603}
I171215 01:25:42.292741 87102 storage/replica_command.go:1231  [split,n1,s1,r9/1:/{Table/12-Max}] initiating a split of this range at key /Table/13 [r10]
I171215 01:25:42.302789 87102 storage/replica_command.go:1231  [split,n1,s1,r10/1:/{Table/13-Max}] initiating a split of this range at key /Table/14 [r11]
I171215 01:25:42.311422 87102 storage/replica_command.go:1231  [split,n1,s1,r11/1:/{Table/14-Max}] initiating a split of this range at key /Table/15 [r12]
I171215 01:25:42.319972 87102 storage/replica_command.go:1231  [split,n1,s1,r12/1:/{Table/15-Max}] initiating a split of this range at key /Table/16 [r13]
I171215 01:25:42.328219 87102 storage/replica_command.go:1231  [split,n1,s1,r13/1:/{Table/16-Max}] initiating a split of this range at key /Table/17 [r14]
W171215 01:25:42.338920 87184 storage/intent_resolver.go:324  [n1,s1] failed to push during intent resolution: failed to push "split" id=86dc40c7 key=/Local/Range/Table/16/RangeDescriptor rw=true pri=0.00213734 iso=SERIALIZABLE stat=PENDING epo=0 ts=1513301142.334086436,1 orig=1513301142.328261058,0 max=1513301142.328261058,0 wto=false rop=false seq=3
I171215 01:25:42.341396 87102 storage/replica_command.go:1231  [split,n1,s1,r14/1:/{Table/17-Max}] initiating a split of this range at key /Table/18 [r15]
I171215 01:25:42.346740 87102 storage/replica_command.go:1231  [split,n1,s1,r15/1:/{Table/18-Max}] initiating a split of this range at key /Table/19 [r16]
W171215 01:25:42.356818 87259 storage/intent_resolver.go:324  [n1,s1] failed to push during intent resolution: failed to push "split" id=b18b29b5 key=/Local/Range/Table/18/RangeDescriptor rw=true pri=0.04764581 iso=SERIALIZABLE stat=PENDING epo=0 ts=1513301142.350123292,1 orig=1513301142.346771611,0 max=1513301142.346771611,0 wto=false rop=false seq=3
I171215 01:25:42.361783 87102 storage/replica_command.go:1231  [split,n1,s1,r16/1:/{Table/19-Max}] initiating a split of this range at key /Table/20 [r17]
I171215 01:25:42.369543 87102 storage/replica_command.go:1231  [split,n1,s1,r17/1:/{Table/20-Max}] initiating a split of this range at key /Table/21 [r18]
I171215 01:25:42.418544 87348 sql/event_log.go:113  [client=127.0.0.1:52988,user=root,n1] Event: "create_database", target: 50, info: {DatabaseName:t Statement:CREATE DATABASE t User:root}
I171215 01:25:42.419648 87102 storage/replica_command.go:1231  [split,n1,s1,r18/1:/{Table/21-Max}] initiating a split of this range at key /Table/50 [r19]
I171215 01:25:42.423707 87348 sql/event_log.go:113  [client=127.0.0.1:52988,user=root,n1] Event: "create_table", target: 51, info: {TableName:t.test Statement:CREATE TABLE t.test (k INT PRIMARY KEY, v INT) User:root}
I171215 01:25:42.425175 87102 storage/replica_command.go:1231  [split,n1,s1,r19/1:/{Table/50-Max}] initiating a split of this range at key /Table/51 [r20]
I171215 01:25:42.657488 87348 sql/event_log.go:113  [client=127.0.0.1:52988,user=root,n1] Event: "alter_table", target: 51, info: {TableName:test Statement:ALTER TABLE t.test ADD COLUMN x DECIMAL NOT NULL DEFAULT 1.4 User:root MutationID:1 CascadeDroppedViews:[]}
I171215 01:25:42.665468 87348 sql/event_log.go:113  [client=127.0.0.1:52988,user=root,n1] Event: "alter_table", target: 51, info: {TableName:test Statement:ALTER TABLE t.test DROP COLUMN v User:root MutationID:2 CascadeDroppedViews:[]}
I171215 01:25:42.681450 87132 sql/lease.go:348  [n1] publish: descID=51 (test) version=2 mtime=2017-12-15 01:25:42.681270351 +0000 UTC
I171215 01:25:42.687495 87132 sql/lease.go:274  publish (count leases): descID=51 name=test version=1 count=1
I171215 01:25:42.737165 87132 sql/lease.go:348  [n1] publish: descID=51 (test) version=3 mtime=2017-12-15 01:25:42.736999559 +0000 UTC
I171215 01:25:42.739108 87132 sql/lease.go:274  publish (count leases): descID=51 name=test version=2 count=1
I171215 01:25:42.780821 87132 sql/backfill.go:132  [n1] Running backfill for "test", v=3, m=1
W171215 01:25:42.808111 87132 sql/schema_changer.go:1108  [n1] Error executing schema change: context deadline exceeded
E171215 01:25:42.808908 86903 sql/lease.go:1495  /Table/3/1/52/2/1: received invalid table descriptor: name:"test" id:52 parent_id:50 version:1 up_version:true modification_time:<wall_time:1513301142736999559 > columns:<name:"k" id:1 type:<semantic_type:INT width:0 precision:0 visible_type:NONE > nullable:false hidden:false > columns:<name:"x" id:3 type:<semantic_type:DECIMAL width:0 precision:0 visible_type:NONE > nullable:false default_expr:"1.4:::DECIMAL" hidden:false > next_column_id:4 families:<name:"primary" id:0 column_names:"k" column_names:"v" column_names:"x" column_ids:1 column_ids:2 column_ids:3 default_column_id:2 > next_family_id:1 primary_index:<name:"primary" id:1 unique:true column_names:"k" column_directions:ASC column_ids:1 foreign_key:<table:0 index:0 name:"" validity:Validated shared_prefix_len:0 on_delete:NO_ACTION on_update:NO_ACTION > interleave:<> partitioning:<num_columns:0 > > next_index_id:2 privileges:<users:<user:"root" privileges:2 > > lease:<node_id:1 expiration_time:1513301442678442039 > next_mutation_id:3 format_version:3 state:ADD view_query:"" mutationJobs:<mutation_id:1 job_id:305498497506246657 > mutationJobs:<mutation_id:2 job_id:305498497545404417 > gc_deadline:0 
I171215 01:25:42.812462 87102 storage/replica_command.go:1231  [split,n1,s1,r20/1:/{Table/51-Max}] initiating a split of this range at key /Table/52 [r21]
E171215 01:25:42.816554 87132 sql/schema_changer.go:1038  [n1] /Table/3/1/52/2/1: received invalid table descriptor: name:"test" id:52 parent_id:50 version:1 up_version:true modification_time:<wall_time:1513301142736999559 > columns:<name:"k" id:1 type:<semantic_type:INT width:0 precision:0 visible_type:NONE > nullable:false hidden:false > columns:<name:"x" id:3 type:<semantic_type:DECIMAL width:0 precision:0 visible_type:NONE > nullable:false default_expr:"1.4:::DECIMAL" hidden:false > next_column_id:4 families:<name:"primary" id:0 column_names:"k" column_names:"v" column_names:"x" column_ids:1 column_ids:2 column_ids:3 default_column_id:2 > next_family_id:1 primary_index:<name:"primary" id:1 unique:true column_names:"k" column_directions:ASC column_ids:1 foreign_key:<table:0 index:0 name:"" validity:Validated shared_prefix_len:0 on_delete:NO_ACTION on_update:NO_ACTION > interleave:<> partitioning:<num_columns:0 > > next_index_id:2 privileges:<users:<user:"root" privileges:2 > > lease:<node_id:1 expiration_time:1513301442678442039 > next_mutation_id:3 format_version:3 state:ADD view_query:"" mutationJobs:<mutation_id:1 job_id:305498497506246657 > mutationJobs:<mutation_id:2 job_id:305498497545404417 > gc_deadline:0 
E171215 01:25:42.817203 87132 sql/schema_changer.go:1038  [n1] /Table/3/1/52/2/1: received invalid table descriptor: name:"test" id:52 parent_id:50 version:1 up_version:true modification_time:<wall_time:1513301142736999559 > columns:<name:"k" id:1 type:<semantic_type:INT width:0 precision:0 visible_type:NONE > nullable:false hidden:false > columns:<name:"x" id:3 type:<semantic_type:DECIMAL width:0 precision:0 visible_type:NONE > nullable:false default_expr:"1.4:::DECIMAL" hidden:false > next_column_id:4 families:<name:"primary" id:0 column_names:"k" column_names:"v" column_names:"x" column_ids:1 column_ids:2 column_ids:3 default_column_id:2 > next_family_id:1 primary_index:<name:"primary" id:1 unique:true column_names:"k" column_directions:ASC column_ids:1 foreign_key:<table:0 index:0 name:"" validity:Validated shared_prefix_len:0 on_delete:NO_ACTION on_update:NO_ACTION > interleave:<> partitioning:<num_columns:0 > > next_index_id:2 privileges:<users:<user:"root" privileges:2 > > lease:<node_id:1 expiration_time:1513301442678442039 > next_mutation_id:3 format_version:3 state:ADD view_query:"" mutationJobs:<mutation_id:1 job_id:305498497506246657 > mutationJobs:<mutation_id:2 job_id:305498497545404417 > gc_deadline:0 
E171215 01:25:42.817741 86903 sql/lease.go:1495  /Table/3/1/52/2/1: received invalid table descriptor: name:"test" id:52 parent_id:50 version:1 up_version:true modification_time:<wall_time:1513301142736999559 > columns:<name:"k" id:1 type:<semantic_type:INT width:0 precision:0 visible_type:NONE > nullable:false hidden:false > columns:<name:"x" id:3 type:<semantic_type:DECIMAL width:0 precision:0 visible_type:NONE > nullable:false default_expr:"1.4:::DECIMAL" hidden:false > next_column_id:4 families:<name:"primary" id:0 column_names:"k" column_names:"v" column_names:"x" column_ids:1 column_ids:2 column_ids:3 default_column_id:2 > next_family_id:1 primary_index:<name:"primary" id:1 unique:true column_names:"k" column_directions:ASC column_ids:1 foreign_key:<table:0 index:0 name:"" validity:Validated shared_prefix_len:0 on_delete:NO_ACTION on_update:NO_ACTION > interleave:<> partitioning:<num_columns:0 > > next_index_id:2 privileges:<users:<user:"root" privileges:2 > > lease:<node_id:1 expiration_time:1513301442678442039 > next_mutation_id:3 format_version:3 state:ADD view_query:"" mutationJobs:<mutation_id:1 job_id:305498497506246657 > mutationJobs:<mutation_id:2 job_id:305498497545404417 > gc_deadline:0 
I171215 01:25:42.821134 87132 sql/lease.go:348  [n1] publish: descID=51 (test) version=4 mtime=2017-12-15 01:25:42.820990954 +0000 UTC
F171215 01:25:42.823354 87132 sql/tablewriter.go:811  [n1] not past the GC deadline: name:"test" id:51 parent_id:50 version:4 up_version:false modification_time:<wall_time:1513301142820990954 > columns:<name:"k" id:1 type:<semantic_type:INT width:0 precision:0 visible_type:NONE > nullable:false hidden:false > next_column_id:4 families:<name:"primary" id:0 column_names:"k" column_names:"v" column_names:"x" column_ids:1 column_ids:2 column_ids:3 default_column_id:2 > next_family_id:1 primary_index:<name:"primary" id:1 unique:true column_names:"k" column_directions:ASC column_ids:1 foreign_key:<table:0 index:0 name:"" validity:Validated shared_prefix_len:0 on_delete:NO_ACTION on_update:NO_ACTION > interleave:<> partitioning:<num_columns:0 > > next_index_id:2 privileges:<users:<user:"root" privileges:2 > > mutations:<column:<name:"x" id:3 type:<semantic_type:DECIMAL width:0 precision:0 visible_type:NONE > nullable:false default_expr:"1.4:::DECIMAL" hidden:false > state:DELETE_AND_WRITE_ONLY direction:ADD mutation_id:1 > mutations:<column:<name:"v" id:2 type:<semantic_type:INT width:0 precision:0 visible_type:NONE > nullable:true hidden:false > state:DELETE_AND_WRITE_ONLY direction:DROP mutation_id:2 > lease:<node_id:1 expiration_time:1513301442818592368 > next_mutation_id:3 format_version:3 state:DROP view_query:"" mutationJobs:<mutation_id:1 job_id:305498497506246657 > mutationJobs:<mutation_id:2 job_id:305498497545404417 > gc_deadline:1513391142804594514 
goroutine 87132 [running]:
github.com/cockroachdb/cockroach/pkg/util/log.getStacks(0x304d401, 0x1500535f202dc1f9, 0x2b1c5aa, 0x12)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/log/clog.go:831 +0xcf
github.com/cockroachdb/cockroach/pkg/util/log.(*loggingT).outputLogEntry(0x304d420, 0xc400000004, 0x2b1c5aa, 0x12, 0x32b, 0xc421d8f200, 0x58f)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/log/clog.go:736 +0x5fc
github.com/cockroachdb/cockroach/pkg/util/log.addStructured(0x2e322a0, 0xc4214ba500, 0x4, 0x2, 0x1f296cd, 0x1c, 0xc4244ae188, 0x1, 0x1)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/log/structured.go:153 +0x308
github.com/cockroachdb/cockroach/pkg/util/log.logDepth(0x2e322a0, 0xc4214ba500, 0x1, 0xe00000004, 0x1f296cd, 0x1c, 0xc4244ae188, 0x1, 0x1)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/log/log.go:56 +0x8c
github.com/cockroachdb/cockroach/pkg/util/log.Fatalf(0x2e322a0, 0xc4214ba500, 0x1f296cd, 0x1c, 0xc4244ae188, 0x1, 0x1)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/log/log.go:150 +0x7e
github.com/cockroachdb/cockroach/pkg/sql.(*tableDeleter).deleteAllRowsFast(0xc4236f9900, 0x2e322a0, 0xc4214ba500, 0xc4224dd0a8, 0x1, 0x8, 0xc4224dd0c0, 0x1, 0x1, 0x258, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/tablewriter.go:811 +0x5b0
github.com/cockroachdb/cockroach/pkg/sql.(*tableDeleter).deleteAllRows(0xc4236f9900, 0x2e322a0, 0xc4214ba500, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x258, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/tablewriter.go:782 +0x270
github.com/cockroachdb/cockroach/pkg/sql.truncateTableInChunks.func1(0x2e322a0, 0xc4214ba500, 0xc422bb1680, 0x1, 0xc4224dd0a4)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/truncate.go:358 +0x2f7
github.com/cockroachdb/cockroach/pkg/internal/client.(*DB).Txn.func1(0x2e322a0, 0xc4214ba500, 0xc422bb1680, 0xc4224dd0a4, 0x1f07aed, 0x7)
	/go/src/github.com/cockroachdb/cockroach/pkg/internal/client/db.go:508 +0x43
github.com/cockroachdb/cockroach/pkg/internal/client.(*Txn).Exec(0xc422bb1680, 0x2e322a0, 0xc4214ba500, 0xc4214b0101, 0xc42036bed0, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/pkg/internal/client/txn.go:753 +0xf6
github.com/cockroachdb/cockroach/pkg/internal/client.(*DB).Txn(0xc424b9f5f0, 0x2e322a0, 0xc4214ba500, 0xc4225c2a20, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/pkg/internal/client/db.go:507 +0x140
github.com/cockroachdb/cockroach/pkg/sql.truncateTableInChunks(0x2e32360, 0xc421c6b860, 0xc424ab6600, 0xc424b9f5f0, 0x0, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/truncate.go:349 +0x17e
github.com/cockroachdb/cockroach/pkg/sql.(*SchemaChanger).maybeAddDropRename(0xc424b9f5e0, 0x2e32360, 0xc421c6b860, 0xc42036a400, 0xc4236d9b60, 0xc424ab6600, 0xc4236d9b60, 0x0, 0xc4244af188)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/schema_changer.go:291 +0x6b2
github.com/cockroachdb/cockroach/pkg/sql.(*SchemaChanger).exec(0xc424b9f5e0, 0x2e32360, 0xc421c6b860, 0xc423762200, 0x0, 0x0, 0x0, 0x30c7f200, 0xed1c51b96, 0x0, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/schema_changer.go:397 +0x226
github.com/cockroachdb/cockroach/pkg/sql.(*SchemaChangeManager).Start.func1(0x2e32360, 0xc4206a4060)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/schema_changer.go:1103 +0x652
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc42052fa40, 0xc423fe47e0, 0xc422f11540)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:196 +0xf3
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:189 +0xad

goroutine 1 [chan receive]:
testing.(*T).Run(0xc4202d6690, 0x1f2eb57, 0x1f, 0x1fe6548, 0x83b601)
	/usr/local/go/src/testing/testing.go:790 +0x2fc
testing.runTests.func1(0xc4202d6690)
	/usr/local/go/src/testing/testing.go:1004 +0x64
testing.tRunner(0xc4202d6690, 0xc4205b7db8)
	/usr/local/go/src/testing/testing.go:746 +0xd0
testing.runTests(0xc42056e480, 0x2e0e3c0, 0xcb, 0xcb, 0x0)
	/usr/local/go/src/testing/testing.go:1002 +0x2d8
testing.(*M).Run(0xc420c99f18, 0xc4205b7f30)
	/usr/local/go/src/testing/testing.go:921 +0x111
github.com/cockroachdb/cockroach/pkg/sql_test.TestMain(0xc4205b7f18)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/main_test.go:36 +0xb8
main.main()
	github.com/cockroachdb/cockroach/pkg/sql/_test/_testmain.go:452 +0xdb

goroutine 7 [chan receive]:
github.com/cockroachdb/cockroach/pkg/util/log.(*loggingT).flushDaemon(0x304d420)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/log/clog.go:1003 +0x81
created by github.com/cockroachdb/cockroach/pkg/util/log.init.0
	/go/src/github.com/cockroachdb/cockroach/pkg/util/log/clog.go:579 +0xbf

goroutine 8 [syscall, 1 minutes]:
os/signal.signal_recv(0xc4202adca0)
	/usr/local/go/src/runtime/sigqueue.go:131 +0xa6
os/signal.loop()
	/usr/local/go/src/os/signal/signal_unix.go:22 +0x22
created by os/signal.init.0
	/usr/local/go/src/os/signal/signal_unix.go:28 +0x41

goroutine 36 [select, locked to thread]:
runtime.gopark(0x1fe8560, 0x0, 0x1f05da8, 0x6, 0x18, 0x1)
	/usr/local/go/src/runtime/proc.go:277 +0x12c
runtime.selectgo(0xc420a08f50, 0xc4204c8780)
	/usr/local/go/src/runtime/select.go:395 +0x1138
runtime.ensureSigM.func1()
	/usr/local/go/src/runtime/signal_unix.go:511 +0x220
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:2337 +0x1

goroutine 86615 [IO wait]:
internal/poll.runtime_pollWait(0x2aea4269f1f0, 0x72, 0x0)
	/usr/local/go/src/runtime/netpoll.go:173 +0x57
internal/poll.(*pollDesc).wait(0xc421700018, 0x72, 0xffffffffffffff00, 0x2e1d720, 0x2e11a80)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:85 +0xae
internal/poll.(*pollDesc).waitRead(0xc421700018, 0xc4227ec800, 0x400, 0x400)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:90 +0x3d
internal/poll.(*FD).Read(0xc421700000, 0xc4227ec800, 0x400, 0x400, 0x0, 0x0, 0x0)
	/usr/local/go/src/internal/poll/fd_unix.go:125 +0x18a
net.(*netFD).Read(0xc421700000, 0xc4227ec800, 0x400, 0x400, 0x301, 0x0, 0x0)
	/usr/local/go/src/net/fd_unix.go:202 +0x52
net.(*conn).Read(0xc420e94008, 0xc4227ec800, 0x400, 0x400, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/net.go:176 +0x6d
github.com/cockroachdb/cockroach/vendor/github.com/cockroachdb/cmux.(*MuxConn).Read(0xc4205aa000, 0xc4227ec800, 0x400, 0x400, 0x1e28a40, 0xc421e2e000, 0x2aea438ff028)
	/go/src/github.com/cockroachdb/cockroach/vendor/github.com/cockroachdb/cmux/cmux.go:218 +0x121
crypto/tls.(*block).readFromUntil(0xc421e2e0f0, 0x2aea438ff028, 0xc4205aa000, 0x5, 0xc4205aa000, 0x0)
	/usr/local/go/src/crypto/tls/conn.go:488 +0x95
crypto/tls.(*Conn).readRecord(0xc420032e00, 0x1fe8617, 0xc420032f20, 0x0)
	/usr/local/go/src/crypto/tls/conn.go:590 +0xe0
crypto/tls.(*Conn).Read(0xc420032e00, 0xc421afc000, 0x8000, 0x8000, 0x0, 0x0, 0x0)
	/usr/local/go/src/crypto/tls/conn.go:1134 +0x110
bufio.(*Reader).Read(0xc423958e40, 0xc4226a8818, 0x9, 0x9, 0x28, 0x1e042e0, 0x0)
	/usr/local/go/src/bufio/bufio.go:213 +0x30b
io.ReadAtLeast(0x2e138a0, 0xc423958e40, 0xc4226a8818, 0x9, 0x9, 0x9, 0xc422803bb8, 0x7addde, 0xc422803c67)
	/usr/local/go/src/io/io.go:309 +0x86
io.ReadFull(0x2e138a0, 0xc423958e40, 0xc4226a8818, 0x9, 0x9, 0xc98ea4, 0xc425a63c80, 0xc425a60004)
	/usr/local/go/src/io/io.go:327 +0x58
github.com/cockroachdb/cockroach/vendor/golang.org/x/net/http2.readFrameHeader(0xc4226a8818, 0x9, 0x9, 0x2e138a0, 0xc423958e40, 0x0, 0x0, 0xc425a63c80, 0x0)
	/go/src/github.com/cockroachdb/cockroach/vendor/golang.org/x/net/http2/frame.go:237 +0x7b
github.com/cockroachdb/cockroach/vendor/golang.org/x/net/http2.(*Framer).ReadFrame(0xc4226a87e0, 0xc425a63c80, 0xc425a63c80, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/vendor/golang.org/x/net/http2/frame.go:492 +0xa4
github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/transport.(*http2Server).HandleStreams(0xc42412c000, 0xc421e99dd0, 0x1fe79b0)
	/go/src/github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/transport/http2_server.go:393 +0x315
github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc.(*Server).serveStreams(0xc420778140, 0x2e3cb60, 0xc42412c000)
	/go/src/github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/server.go:568 +0x140
github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc.(*Server).serveHTTP2Transport(0xc420778140, 0x2e3cfe0, 0xc420032e00, 0x2e1cae0, 0xc42280abb0)
	/go/src/github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/server.go:561 +0x471
github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc.(*Server).handleRawConn(0xc420778140, 0x2e3d880, 0xc4205aa000)
	/go/src/github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/server.go:526 +0x497
created by github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc.(*Server).Serve
	/go/src/github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/server.go:495 +0x5b9

goroutine 87019 [semacquire]:
sync.runtime_notifyListWait(0xc423782040, 0xc400000004)
	/usr/local/go/src/runtime/sema.go:507 +0x110
sync.(*Cond).Wait(0xc423782030)
	/usr/local/go/src/sync/cond.go:56 +0x80
io.(*pipe).read(0xc423782000, 0xc420099c00, 0x400, 0x400, 0x0, 0x0, 0x0)
	/usr/local/go/src/io/pipe.go:47 +0xc6
io.(*PipeReader).Read(0xc4216b8000, 0xc420099c00, 0x400, 0x400, 0x0, 0x0, 0x0)
	/usr/local/go/src/io/pipe.go:130 +0x4c
crypto/tls.(*block).readFromUntil(0xc423f09950, 0x2aea426e54c8, 0xc42052e0d0, 0x5, 0xc42052e0d0, 0x0)
	/usr/local/go/src/crypto/tls/conn.go:488 +0x95
crypto/tls.(*Conn).readRecord(0xc421400a80, 0x1fe8617, 0xc421400ba0, 0x0)
	/usr/local/go/src/crypto/tls/conn.go:590 +0xe0
crypto/tls.(*Conn).Read(0xc421400a80, 0xc4230a8000, 0x8000, 0x8000, 0x0, 0x0, 0x0)
	/usr/local/go/src/crypto/tls/conn.go:1134 +0x110
bufio.(*Reader).Read(0xc4213a8d20, 0xc4211fa038, 0x9, 0x9, 0x28, 0x1e042e0, 0x0)
	/usr/local/go/src/bufio/bufio.go:213 +0x30b
io.ReadAtLeast(0x2e138a0, 0xc4213a8d20, 0xc4211fa038, 0x9, 0x9, 0x9, 0xc420895bb8, 0x7addde, 0xc420895c67)
	/usr/local/go/src/io/io.go:309 +0x86
io.ReadFull(0x2e138a0, 0xc4213a8d20, 0xc4211fa038, 0x9, 0x9, 0xc98ea4, 0xc422a6e960, 0xc422a60004)
	/usr/local/go/src/io/io.go:327 +0x58
github.com/cockroachdb/cockroach/vendor/golang.org/x/net/http2.readFrameHeader(0xc4211fa038, 0x9, 0x9, 0x2e138a0, 0xc4213a8d20, 0x0, 0x0, 0xc422a6e960, 0x0)
	/go/src/github.com/cockroachdb/cockroach/vendor/golang.org/x/net/http2/frame.go:237 +0x7b
github.com/cockroachdb/cockroach/vendor/golang.org/x/net/http2.(*Framer).ReadFrame(0xc4211fa000, 0xc422a6e960, 0xc422a6e960, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/vendor/golang.org/x/net/http2/frame.go:492 +0xa4
github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/transport.(*http2Server).HandleStreams(0xc420612b00, 0xc422a6e900, 0x1fe79b0)
	/go/src/github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/transport/http2_server.go:393 +0x315
github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc.(*Server).serveStreams(0xc420778140, 0x2e3cb60, 0xc420612b00)
	/go/src/github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/server.go:568 +0x140
github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc.(*Server).serveHTTP2Transport(0xc420778140, 0x2e3cfe0, 0xc421400a80, 0x2e1cae0, 0xc422284d10)
	/go/src/github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/server.go:561 +0x471
github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc.(*Server).handleRawConn(0xc420778140, 0x2e3db20, 0xc42052e0d0)
	/go/src/github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/server.go:526 +0x497
created by github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc.(*Server).Serve
	/go/src/github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/server.go:495 +0x5b9

goroutine 86946 [select]:
github.com/cockroachdb/cockroach/pkg/gossip.(*Gossip).bootstrap.func1(0x2e32360, 0xc423f08240)
	/go/src/github.com/cockroachdb/cockroach/pkg/gossip/gossip.go:1138 +0x331
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc4234d0150, 0xc423fe47e0, 0xc4234d0140)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:196 +0xf3
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:189 +0xad

goroutine 87120 [select]:
github.com/cockroachdb/cockroach/pkg/sql.(*DistSQLPlanner).initRunners.func1(0x2e32360, 0xc421e98030)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsql_running.go:86 +0x167
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc42052f880, 0xc423fe47e0, 0xc42052f870)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:196 +0xf3
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:189 +0xad

goroutine 86904 [semacquire]:
sync.runtime_notifyListWait(0xc4200ae958, 0xc400000000)
	/usr/local/go/src/runtime/sema.go:507 +0x110
sync.(*Cond).Wait(0xc4200ae948)
	/usr/local/go/src/sync/cond.go:56 +0x80
github.com/cockroachdb/cockroach/pkg/storage/engine.(*RocksDB).syncLoop(0xc4200ae840)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/engine/rocksdb.go:501 +0xa2
created by github.com/cockroachdb/cockroach/pkg/storage/engine.(*RocksDB).open
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/engine/rocksdb.go:488 +0x4b3

goroutine 87044 [semacquire]:
sync.runtime_notifyListWait(0xc421d84410, 0xc400000192)
	/usr/local/go/src/runtime/sema.go:507 +0x110
sync.(*Cond).Wait(0xc421d84400)
	/usr/local/go/src/sync/cond.go:56 +0x80
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).worker(0xc424bae360, 0x2e32360, 0xc422d73c20)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:198 +0x7c
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).Start.func2(0x2e32360, 0xc422d73c20)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:167 +0x3e
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc42052e820, 0xc423fe47e0, 0xc42052e810)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:196 +0xf3
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:189 +0xad

goroutine 87067 [semacquire]:
sync.runtime_notifyListWait(0xc421d84410, 0xc4000001ad)
	/usr/local/go/src/runtime/sema.go:507 +0x110
sync.(*Cond).Wait(0xc421d84400)
	/usr/local/go/src/sync/cond.go:56 +0x80
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).worker(0xc424bae360, 0x2e32360, 0xc421da6120)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:198 +0x7c
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).Start.func2(0x2e32360, 0xc421da6120)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:167 +0x3e
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc42052eb70, 0xc423fe47e0, 0xc42052eb60)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:196 +0xf3
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:189 +0xad

goroutine 87114 [select]:
github.com/cockroachdb/cockroach/pkg/ts.(*poller).start.func1(0x2e32360, 0xc422a1d2f0)
	/go/src/github.com/cockroachdb/cockroach/pkg/ts/db.go:113 +0x156
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc42052f7b0, 0xc423fe47e0, 0xc42052f7a0)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:196 +0xf3
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:189 +0xad

goroutine 87208 [chan receive]:
github.com/cockroachdb/cockroach/vendor/github.com/cockroachdb/cmux.muxListener.Accept(...)
	/go/src/github.com/cockroachdb/cockroach/vendor/github.com/cockroachdb/cmux/cmux.go:184
github.com/cockroachdb/cockroach/vendor/github.com/cockroachdb/cmux.(*muxListener).Accept(0xc4235ac400, 0x1fe6a88, 0xc423fe47e0, 0x2e32360, 0xc422375c80)
	<autogenerated>:1 +0x65
github.com/cockroachdb/cockroach/pkg/util/netutil.(*Server).ServeWith(0xc42000e148, 0x2e32360, 0xc422375c80, 0xc423fe47e0, 0x2e31520, 0xc4235ac400, 0xc422375cb0, 0xc422375c80, 0xc422e316d0)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/netutil/net.go:119 +0x50
github.com/cockroachdb/cockroach/pkg/server.(*Server).Start.func17(0x2e32360, 0xc422375c80)
	/go/src/github.com/cockroachdb/cockroach/pkg/server/server.go:1226 +0x1f5
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc4221a00b0, 0xc423fe47e0, 0xc421d85040)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:196 +0xf3
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:189 +0xad

goroutine 87050 [semacquire]:
sync.runtime_notifyListWait(0xc421d84410, 0xc400000195)
	/usr/local/go/src/runtime/sema.go:507 +0x110
sync.(*Cond).Wait(0xc421d84400)
	/usr/local/go/src/sync/cond.go:56 +0x80
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).worker(0xc424bae360, 0x2e32360, 0xc422d73d40)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:198 +0x7c
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).Start.func2(0x2e32360, 0xc422d73d40)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:167 +0x3e
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc42052e8e0, 0xc423fe47e0, 0xc42052e8d0)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:196 +0xf3
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:189 +0xad

goroutine 87070 [semacquire]:
sync.runtime_notifyListWait(0xc421d84410, 0xc4000001ae)
	/usr/local/go/src/runtime/sema.go:507 +0x110
sync.(*Cond).Wait(0xc421d84400)
	/usr/local/go/src/sync/cond.go:56 +0x80
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).worker(0xc424bae360, 0x2e32360, 0xc421da61b0)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:198 +0x7c
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).Start.func2(0x2e32360, 0xc421da61b0)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:167 +0x3e
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc42052ec40, 0xc423fe47e0, 0xc42052ec30)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:196 +0xf3
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:189 +0xad

goroutine 87102 [runnable, locked to thread]:
github.com/cockroachdb/cockroach/pkg/storage/engine._Cfunc_MVCCComputeStats(0x2aea54c1a060, 0xc4228118e8, 0x1, 0x0, 0x0, 0xc4203d0138, 0x1, 0x0, 0x0, 0x1500535f1f87c87b, ...)
	github.com/cockroachdb/cockroach/pkg/storage/engine/_obj/_cgo_gotypes.go:802 +0x76
github.com/cockroachdb/cockroach/pkg/storage/engine.(*rocksDBIterator).ComputeStats.func1(0x2aea54c1a060, 0xc4228118e8, 0x1, 0x0, 0x0, 0xc4203d0138, 0x1, 0x0, 0x0, 0x1500535f1f87c87b, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/engine/rocksdb.go:1771 +0xf6
github.com/cockroachdb/cockroach/pkg/storage/engine.(*rocksDBIterator).ComputeStats(0xc423166750, 0xc4228118e8, 0x1, 0x8, 0x0, 0x0, 0xc4203d0138, 0x1, 0x8, 0x0, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/engine/rocksdb.go:1771 +0x2fe
github.com/cockroachdb/cockroach/pkg/storage/engine.(*rocksDBBatchIterator).ComputeStats(0xc423166750, 0xc4228118e8, 0x1, 0x8, 0x0, 0x0, 0xc4203d0138, 0x1, 0x8, 0x0, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/engine/rocksdb.go:1190 +0xe1
github.com/cockroachdb/cockroach/pkg/storage.ComputeStatsForRange(0xc4213d6e70, 0x2e3c740, 0xc4231666c0, 0x1500535f1f87c87b, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/stats.go:34 +0x26b
github.com/cockroachdb/cockroach/pkg/storage.splitTrigger(0x2e32360, 0xc4240bc930, 0x2e44960, 0xc4210bc300, 0x2e42280, 0xc4231666c0, 0x0, 0x1500535f1f87c87b, 0x0, 0x0, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/replica_command.go:1501 +0x4ca
github.com/cockroachdb/cockroach/pkg/storage.runCommitTrigger(0x2e32360, 0xc4240bc930, 0x2e44960, 0xc4210bc300, 0x2e42280, 0xc4231666c0, 0xc4204e5c00, 0xc4203d01a0, 0xa, 0x10, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/replica_command.go:645 +0x6c3
github.com/cockroachdb/cockroach/pkg/storage.evalEndTransaction(0x2e32360, 0xc4240bc930, 0x2aea426e4320, 0xc4231666c0, 0x2e44960, 0xc4210bc300, 0x1500535f1f87c87b, 0x0, 0x100000001, 0x1, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/replica_command.go:410 +0xc0b
github.com/cockroachdb/cockroach/pkg/storage.evaluateCommand(0x2e32360, 0xc4240bc930, 0xc4203d0e50, 0x8, 0x0, 0x2aea426e4320, 0xc4231666c0, 0x2e44960, 0xc4210bc300, 0xc4204e5c00, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/replica_command.go:114 +0x2d9
github.com/cockroachdb/cockroach/pkg/storage.evaluateBatch(0x2e32360, 0xc4240bc930, 0xc4203d0e50, 0x8, 0x2aea426e4320, 0xc4231666c0, 0x2e44960, 0xc4210bc300, 0xc4204e5c00, 0x1500535f1f87c87b, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/replica.go:5286 +0x3aa
github.com/cockroachdb/cockroach/pkg/storage.(*Replica).evaluateTxnWriteBatch(0xc4210bc300, 0x2e32360, 0xc4240bc930, 0xc4203d0e50, 0x8, 0x1500535f1f87c87b, 0x0, 0x100000001, 0x1, 0x14, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/replica.go:5088 +0x270
github.com/cockroachdb/cockroach/pkg/storage.(*Replica).evaluateProposalInner(0xc4210bc300, 0x2e32360, 0xc4240bc930, 0xc4203d0e50, 0x8, 0x1500535f1f87c87b, 0x0, 0x100000001, 0x1, 0x14, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/replica.go:4924 +0x146
github.com/cockroachdb/cockroach/pkg/storage.(*Replica).evaluateProposal(0xc4210bc300, 0x2e32360, 0xc4240bc930, 0xc4203d0e50, 0x8, 0x1500535f1f87c87b, 0x0, 0x100000001, 0x1, 0x14, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/replica.go:2856 +0xe0
github.com/cockroachdb/cockroach/pkg/storage.(*Replica).requestToProposal(0xc4210bc300, 0x2e32360, 0xc4240bc930, 0xc4203d0e50, 0x8, 0x1500535f1f87c87b, 0x0, 0x100000001, 0x1, 0x14, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/replica.go:2813 +0x19f
github.com/cockroachdb/cockroach/pkg/storage.(*Replica).propose(0xc4210bc300, 0x2e32360, 0xc4240bc930, 0x0, 0x0, 0xc422811950, 0x100000001, 0x1, 0xc422811960, 0xc422811970, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/replica.go:2985 +0x4cf
github.com/cockroachdb/cockroach/pkg/storage.(*Replica).tryExecuteWriteBatch(0xc4210bc300, 0x2e32360, 0xc4240bc930, 0x1500535f1f87c87b, 0x0, 0x100000001, 0x1, 0x14, 0x0, 0xc42105cd20, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/replica.go:2714 +0x361
github.com/cockroachdb/cockroach/pkg/storage.(*Replica).executeWriteBatch(0xc4210bc300, 0x2e32360, 0xc4240bc930, 0x1500535f1f87c87b, 0x0, 0x100000001, 0x1, 0x14, 0x0, 0xc42105cd20, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/replica.go:2568 +0xae
github.com/cockroachdb/cockroach/pkg/storage.(*Replica).Send(0xc4210bc300, 0x2e32360, 0xc4240bc930, 0x1500535f1f87c87b, 0x0, 0x100000001, 0x1, 0x14, 0x0, 0xc42105cd20, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/replica.go:1891 +0x6a5
github.com/cockroachdb/cockroach/pkg/storage.(*Store).Send(0xc420310400, 0x2e32360, 0xc4240bc900, 0x1500535f1f87c87b, 0x0, 0x100000001, 0x1, 0x14, 0x0, 0xc42105cd20, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/store.go:2567 +0x688
github.com/cockroachdb/cockroach/pkg/storage.(*Stores).Send(0xc422d70370, 0x2e32360, 0xc4240bc8a0, 0x0, 0x0, 0x100000001, 0x1, 0x14, 0x0, 0xc42105cd20, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/stores.go:215 +0x214
github.com/cockroachdb/cockroach/pkg/server.(*Node).batchInternal.func1(0x2e32360, 0xc4240bc8a0, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/pkg/server/node.go:861 +0x192
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunTaskWithErr(0xc423fe47e0, 0x2e32360, 0xc4240bc8a0, 0x1f140de, 0x10, 0xc421232ab0, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:246 +0xf7
github.com/cockroachdb/cockroach/pkg/server.(*Node).batchInternal(0xc425888900, 0x2e32360, 0xc4240bc8a0, 0xc4213d74b8, 0xc4240bc8a0, 0x1224a3e, 0x2e32360)
	/go/src/github.com/cockroachdb/cockroach/pkg/server/node.go:848 +0x152
github.com/cockroachdb/cockroach/pkg/server.(*Node).Batch(0xc425888900, 0x2e32360, 0xc4240bc8a0, 0xc4213d74b8, 0x1f, 0x0, 0xc421232dc8)
	/go/src/github.com/cockroachdb/cockroach/pkg/server/node.go:889 +0x99
github.com/cockroachdb/cockroach/pkg/kv.(*grpcTransport).send.func1(0xc421cf49a0, 0xc4213d74a0, 0x2e32360, 0xc421c45f20, 0x0, 0xc421232f90, 0x7beb78)
	/go/src/github.com/cockroachdb/cockroach/pkg/kv/transport.go:244 +0x6b0
github.com/cockroachdb/cockroach/pkg/kv.(*grpcTransport).send(0xc421cf49a0, 0x2e32360, 0xc421c45f20, 0xc4207c3190, 0xf, 0xc4209ead70, 0x0, 0x0, 0x100000001, 0x1, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/kv/transport.go:272 +0x9a
github.com/cockroachdb/cockroach/pkg/kv.(*grpcTransport).SendNext(0xc421cf49a0, 0x2e32360, 0xc421c45f20, 0xc420868ae0)
	/go/src/github.com/cockroachdb/cockroach/pkg/kv/transport.go:209 +0x31b
github.com/cockroachdb/cockroach/pkg/kv.(*DistSender).sendToReplicas(0xc42184c2d0, 0x2e32360, 0xc421c45f20, 0xc42184c320, 0x14, 0xc42371afa0, 0x1, 0x1, 0x0, 0x0, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/kv/dist_sender.go:1229 +0x3a4
github.com/cockroachdb/cockroach/pkg/kv.(*DistSender).sendRPC(0xc42184c2d0, 0x2e32360, 0xc421c45f20, 0x14, 0xc42371afa0, 0x1, 0x1, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/kv/dist_sender.go:383 +0x27b
github.com/cockroachdb/cockroach/pkg/kv.(*DistSender).sendSingleRange(0xc42184c2d0, 0x2e32360, 0xc421c45f20, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0xc42105cc40, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/kv/dist_sender.go:447 +0x16e
github.com/cockroachdb/cockroach/pkg/kv.(*DistSender).sendPartialBatch(0xc42184c2d0, 0x2e32360, 0xc421c45f20, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0xc42105cc40, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/kv/dist_sender.go:1013 +0x347
github.com/cockroachdb/cockroach/pkg/kv.(*DistSender).divideAndSendBatchToRanges(0xc42184c2d0, 0x2e32360, 0xc421c45f20, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0xc42105cc40, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/kv/dist_sender.go:689 +0x16f8
github.com/cockroachdb/cockroach/pkg/kv.(*DistSender).Send(0xc42184c2d0, 0x2e32360, 0xc421c45f20, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0xc42105c1c0, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/kv/dist_sender.go:619 +0x3ea
github.com/cockroachdb/cockroach/pkg/kv.(*TxnCoordSender).Send(0xc422ec8460, 0x2e32360, 0xc421c45ef0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0xc42105c1c0, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/kv/txn_coord_sender.go:444 +0x1ce
github.com/cockroachdb/cockroach/pkg/internal/client.(*DB).send(0xc4235ac0a0, 0x2e322a0, 0xc423bdfd80, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0xc42105c1c0, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/internal/client/db.go:546 +0x2c9
github.com/cockroachdb/cockroach/pkg/internal/client.(*Txn).Send(0xc420d3a780, 0x2e322a0, 0xc423bdfd80, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/internal/client/txn.go:951 +0x308
github.com/cockroachdb/cockroach/pkg/internal/client.(*Txn).Send-fm(0x2e322a0, 0xc423bdfd80, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/internal/client/txn.go:514 +0x76
github.com/cockroachdb/cockroach/pkg/internal/client.sendAndFill(0x2e322a0, 0xc423bdfd80, 0xc4212351f8, 0xc423b1ea00, 0x40, 0x0)
	/go/src/github.com/cockroachdb/cockroach/pkg/internal/client/db.go:457 +0xf8
github.com/cockroachdb/cockroach/pkg/internal/client.(*Txn).Run(0xc420d3a780, 0x2e322a0, 0xc423bdfd80, 0xc423b1ea00, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/pkg/internal/client/txn.go:514 +0xd1
github.com/cockroachdb/cockroach/pkg/storage.(*Replica).adminSplitWithDescriptor.func1(0x2e322a0, 0xc423bdfd80, 0xc420d3a780, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/replica_command.go:1302 +0x689
github.com/cockroachdb/cockroach/pkg/internal/client.(*DB).Txn.func1(0x2e322a0, 0xc423bdfd80, 0xc420d3a780, 0xc4203d0178, 0x1f07aed, 0x7)
	/go/src/github.com/cockroachdb/cockroach/pkg/internal/client/db.go:508 +0x43
github.com/cockroachdb/cockroach/pkg/internal/client.(*Txn).Exec(0xc420d3a780, 0x2e322a0, 0xc423bdfd80, 0xc423bd0101, 0xc4209a22a0, 0xc421a645a0, 0x1)
	/go/src/github.com/cockroachdb/cockroach/pkg/internal/client/txn.go:753 +0xf6
github.com/cockroachdb/cockroach/pkg/internal/client.(*DB).Txn(0xc4235ac0a0, 0x2e322a0, 0xc423bdfd80, 0xc4236bbb60, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/pkg/internal/client/db.go:507 +0x140
github.com/cockroachdb/cockroach/pkg/storage.(*Replica).adminSplitWithDescriptor(0xc4210bc300, 0x2e32320, 0xc421a645a0, 0xc4203d0138, 0x1, 0x8, 0x0, 0x0, 0x0, 0xc4203d0138, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/replica_command.go:1234 +0x881
github.com/cockroachdb/cockroach/pkg/storage.(*splitQueue).process(0xc42052e300, 0x2e32320, 0xc421a645a0, 0xc4210bc300, 0xc422659000, 0x27, 0x40, 0x1, 0xc422811960)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/split_queue.go:91 +0x1a0
github.com/cockroachdb/cockroach/pkg/storage.(*baseQueue).processReplica(0xc42009e800, 0x2e32360, 0xc4236bba40, 0xc4210bc300, 0xc423604100, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/queue.go:636 +0x3de
github.com/cockroachdb/cockroach/pkg/storage.(*baseQueue).processLoop.func1.2(0x2e32360, 0xc4236bba40)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/queue.go:533 +0xbd
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunTask(0xc423fe47e0, 0x2e32360, 0xc4236bba40, 0xc421c26960, 0x21, 0xc420b1be88, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:229 +0xf7
github.com/cockroachdb/cockroach/pkg/storage.(*baseQueue).processLoop.func1(0x2e32360, 0xc422a1cbd0)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/queue.go:529 +0x40a
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc42052f580, 0xc423fe47e0, 0xc422f11340)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:196 +0xf3
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:189 +0xad

goroutine 87057 [semacquire]:
sync.runtime_notifyListWait(0xc421d84410, 0xc4000001a2)
	/usr/local/go/src/runtime/sema.go:507 +0x110
sync.(*Cond).Wait(0xc421d84400)
	/usr/local/go/src/sync/cond.go:56 +0x80
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).worker(0xc424bae360, 0x2e32360, 0xc422d73f20)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:198 +0x7c
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).Start.func2(0x2e32360, 0xc422d73f20)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:167 +0x3e
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc42052e9c0, 0xc423fe47e0, 0xc42052e9b0)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:196 +0xf3
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:189 +0xad

goroutine 87411 [select]:
github.com/cockroachdb/cockroach/pkg/kv.(*TxnCoordSender).heartbeatLoop(0xc422ec8460, 0x2e32360, 0xc4240bc4b0, 0xdb44eb3645a871fd, 0xb2ec7b0fd64005a8)
	/go/src/github.com/cockroachdb/cockroach/pkg/kv/txn_coord_sender.go:657 +0x361
github.com/cockroachdb/cockroach/pkg/kv.(*TxnCoordSender).updateState.func2(0x2e32360, 0xc4236bbc50)
	/go/src/github.com/cockroachdb/cockroach/pkg/kv/txn_coord_sender.go:964 +0x51
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunAsyncTask.func1(0xc423fe47e0, 0x2e32360, 0xc4236bbc50, 0xc421c26a80, 0x29, 0x2e40d40, 0xc423762200, 0xc420374500)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:267 +0xe6
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunAsyncTask
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:262 +0x133

goroutine 87091 [select]:
github.com/cockroachdb/cockroach/pkg/storage.(*Store).startGossip.func4(0x2e32360, 0xc421da65d0)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/store.go:1301 +0x3e9
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc42052eee0, 0xc423fe47e0, 0xc4212f9540)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:196 +0xf3
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:189 +0xad

goroutine 86888 [IO wait]:
internal/poll.runtime_pollWait(0x2aea438e25e0, 0x72, 0xffffffffffffffff)
	/usr/local/go/src/runtime/netpoll.go:173 +0x57
internal/poll.(*pollDesc).wait(0xc423768298, 0x72, 0xc42003dc00, 0x0, 0x0)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:85 +0xae
internal/poll.(*pollDesc).waitRead(0xc423768298, 0xffffffffffffff00, 0x0, 0x0)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:90 +0x3d
internal/poll.(*FD).Accept(0xc423768280, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/internal/poll/fd_unix.go:334 +0x1e2
net.(*netFD).accept(0xc423768280, 0xc420a68b30, 0x0, 0x0)
	/usr/local/go/src/net/fd_unix.go:238 +0x42
net.(*TCPListener).accept(0xc42000e158, 0x122192a, 0x8070a0, 0xc42003de80)
	/usr/local/go/src/net/tcpsock_posix.go:136 +0x2e
net.(*TCPListener).Accept(0xc42000e158, 0x1fe6ba8, 0xc423605080, 0x2e3da00, 0xc420a68b30)
	/usr/local/go/src/net/tcpsock.go:247 +0x49
github.com/cockroachdb/cockroach/vendor/github.com/cockroachdb/cmux.(*cMux).Serve(0xc423605080, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/vendor/github.com/cockroachdb/cmux/cmux.go:124 +0x95
github.com/cockroachdb/cockroach/pkg/server.(*Server).Start.func10.1()
	/go/src/github.com/cockroachdb/cockroach/pkg/server/server.go:958 +0x2f
sync.(*Once).Do(0xc422ef1c30, 0xc422df9758)
	/usr/local/go/src/sync/once.go:44 +0xbe
github.com/cockroachdb/cockroach/pkg/server.(*Server).Start.func10(0x2e32360, 0xc420422000)
	/go/src/github.com/cockroachdb/cockroach/pkg/server/server.go:957 +0x5b
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc42052e050, 0xc423fe47e0, 0xc422f10020)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:196 +0xf3
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:189 +0xad

goroutine 87106 [select]:
github.com/cockroachdb/cockroach/pkg/storage.(*baseQueue).processLoop.func1(0x2e32360, 0xc422a1d0e0)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/queue.go:507 +0x1bb
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc42052f5e0, 0xc423fe47e0, 0xc422f113c0)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:196 +0xf3
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:189 +0xad

goroutine 87037 [semacquire]:
sync.runtime_notifyListWait(0xc421d84410, 0xc40000018d)
	/usr/local/go/src/runtime/sema.go:507 +0x110
sync.(*Cond).Wait(0xc421d84400)
	/usr/local/go/src/sync/cond.go:56 +0x80
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).worker(0xc424bae360, 0x2e32360, 0xc422d73ad0)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:198 +0x7c
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).Start.func2(0x2e32360, 0xc422d73ad0)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:167 +0x3e
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc42052e6a0, 0xc423fe47e0, 0xc42052e680)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:196 +0xf3
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:189 +0xad

goroutine 87077 [semacquire]:
sync.runtime_notifyListWait(0xc421d84410, 0xc400000176)
	/usr/local/go/src/runtime/sema.go:507 +0x110
sync.(*Cond).Wait(0xc421d84400)
	/usr/local/go/src/sync/cond.go:56 +0x80
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).worker(0xc424bae360, 0x2e32360, 0xc421da6300)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:198 +0x7c
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).Start.func2(0x2e32360, 0xc421da6300)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:167 +0x3e
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc42052ed20, 0xc423fe47e0, 0xc42052ed10)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:196 +0xf3
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:189 +0xad

goroutine 86892 [select]:
github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc.(*addrConn).transportMonitor(0xc420cd8000)
	/go/src/github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/clientconn.go:1002 +0x166
github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc.(*addrConn).connect.func1(0xc420cd8000)
	/go/src/github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/clientconn.go:703 +0x1ce
created by github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc.(*addrConn).connect
	/go/src/github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/clientconn.go:694 +0x40d

goroutine 87071 [semacquire]:
sync.runtime_notifyListWait(0xc421d84410, 0xc400000173)
	/usr/local/go/src/runtime/sema.go:507 +0x110
sync.(*Cond).Wait(0xc421d84400)
	/usr/local/go/src/sync/cond.go:56 +0x80
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).worker(0xc424bae360, 0x2e32360, 0xc421da61e0)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:198 +0x7c
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).Start.func2(0x2e32360, 0xc421da61e0)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:167 +0x3e
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc42052ec60, 0xc423fe47e0, 0xc42052ec50)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:196 +0xf3
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:189 +0xad

goroutine 86906 [chan receive]:
github.com/cockroachdb/cockroach/pkg/server.(*Server).Start.func2(0x2e32360, 0xc422062b10)
	/go/src/github.com/cockroachdb/cockroach/pkg/server/server.go:742 +0x53
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc4203cde80, 0xc423fe47e0, 0xc4235ac480)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:196 +0xf3
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:189 +0xad

goroutine 87024 [select]:
github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/transport.loopyWriter(0x2e322a0, 0xc421755440, 0xc422a6e870, 0xc420a0afb8)
	/go/src/github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/transport/transport.go:750 +0x2e4
github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/transport.newHTTP2Client.func3(0xc422da4f00)
	/go/src/github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/transport/http2_client.go:298 +0x5e
created by github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/transport.newHTTP2Client
	/go/src/github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/transport/http2_client.go:297 +0xdd1

goroutine 87022 [select]:
github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/transport.loopyWriter(0x2e32360, 0xc4207f32c0, 0xc4207f3260, 0xc420a0dfb8)
	/go/src/github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/transport/transport.go:750 +0x2e4
github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/transport.newHTTP2Server.func1(0xc420612b00)
	/go/src/github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/transport/http2_server.go:227 +0x5e
created by github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/transport.newHTTP2Server
	/go/src/github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/transport/http2_server.go:226 +0x8d5

goroutine 87063 [semacquire]:
sync.runtime_notifyListWait(0xc421d84410, 0xc4000001a8)
	/usr/local/go/src/runtime/sema.go:507 +0x110
sync.(*Cond).Wait(0xc421d84400)
	/usr/local/go/src/sync/cond.go:56 +0x80
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).worker(0xc424bae360, 0x2e32360, 0xc421da6060)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:198 +0x7c
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).Start.func2(0x2e32360, 0xc421da6060)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:167 +0x3e
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc42052eac0, 0xc423fe47e0, 0xc42052eaa0)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:196 +0xf3
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:189 +0xad

goroutine 86912 [semacquire]:
sync.runtime_notifyListWait(0xc4200aeab8, 0xc40000014d)
	/usr/local/go/src/runtime/sema.go:507 +0x110
sync.(*Cond).Wait(0xc4200aeaa8)
	/usr/local/go/src/sync/cond.go:56 +0x80
github.com/cockroachdb/cockroach/pkg/storage/engine.(*RocksDB).syncLoop(0xc4200ae9a0)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/engine/rocksdb.go:501 +0xa2
created by github.com/cockroachdb/cockroach/pkg/storage/engine.(*RocksDB).open
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/engine/rocksdb.go:488 +0x4b3

goroutine 87136 [select]:
github.com/cockroachdb/cockroach/pkg/storage.(*NodeLiveness).StartHeartbeat.func1(0x2e32360, 0xc4206a4c30)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/node_liveness.go:367 +0x2a9
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc4209a2e10, 0xc423fe47e0, 0xc4209ea9b0)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:196 +0xf3
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:189 +0xad

goroutine 87427 [runnable]:
git
```

Please assign, take a look and update the issue accordingly.

### PR DESCRIPTION
**Pull request by spencerkimball**
Fixes #20745

Release note: None

### CODE REVIEW

File: pkg/sql/schema_changer.go [hunk 1]
```diff
@@ -287,6 +287,12 @@ func (sc *SchemaChanger) maybeAddDropRename(
 			return false, nil
 		}
 
+		// This can happen if a change other than the drop originally
+		// scheduled the changer for this table. If that's the case,
+		// we still need to wait for the deadline to expire.
+		if d := table.GCDeadline; d != 0 && timeutil.Since(timeutil.Unix(0, d)) < 0 {
+			return false, nil
+		}
```
Comment (vivekmenezes) [inline pkg/sql/schema_changer.go]: It's not clear why you need this check here. TRUNCATE will mark the descriptor as DROPPED and it should follow the normal asynchronous code path that deletes the data after the TTL.

Comment (spencerkimball) [reply pkg/sql/schema_changer.go]: In the unittest that fails, two different schema change operations happen for the same table. The one to backfill a column gets scheduled and then this code path gets tripped, even though there's a GC deadline which has not yet expired. So we do need to check it here to ensure that we don't prematurely begin dropping.

**Comment by spencerkimball** [comment]
@vivekmenezes ping

File: pkg/sql/schema_changer.go (hunk 1 above)
Comment (vivekmenezes) [reply pkg/sql/schema_changer.go]: I guess we can't do much here. I'd have preferred returning an error here but returning nil allows the schema changer to be marked as complete and with the next gossip message received when the dropped descriptor appears another schema changer is scheduled with the execAfter time set correctly to the TTL deadline.

**Review by vivekmenezes — APPROVED** [review]

**Comment by spencerkimball** [comment]
Well we return false, which causes the schema changer to proceed to find the column backfill and initiate or continue with that. I believe this is the correct behavior.
