### PR TITLE
roachtest: disable load based splitting and merging in follower read test

### LINKED ISSUE #34732: roachtest: follower-reads/nodes=3 failed
SHA: https://github.com/cockroachdb/cockroach/commits/e4127466ae0a44efb624afcaf0861903028b6e18

Parameters:

To repro, try:

```
# Don't forget to check out a clean suitable branch and experiment with the
# stress invocation until the desired results present themselves. For example,
# using stress instead of stressrace and passing the '-p' stressflag which
# controls concurrency.
./scripts/gceworker.sh start && ./scripts/gceworker.sh mosh
cd ~/go/src/github.com/cockroachdb/cockroach && \
stdbuf -oL -eL \
make stressrace TESTS=follower-reads/nodes=3 PKG=roachtest TESTTIMEOUT=5m STRESSFLAGS='-maxtime 20m -timeout 10m' 2>&1 | tee /tmp/stress.log
```

Failed test: https://teamcity.cockroachdb.com/viewLog.html?buildId=1129825&tab=buildLog

```
The test failed on release-2.1:
	follower_reads.go:191,test.go:1206: error verifying node values: pq: unknown function: experimental_follower_read_timestamp()

```

### PR DESCRIPTION
**Pull request by ajwerner**
The follower read tests insert a lot of data quickly which leads to load based
splitting. Then the data sits idle while the test waits for the follower read
interval to pass at which point the system attempts to merge the split ranges
back together. This causes problems as merging prevents follower reads. This
diff disables both LBS and merginging in the follower read test.

Fixes #34732

Release note: None

### CODE REVIEW

File: pkg/cmd/roachtest/follower_reads.go [hunk 1]
```diff
@@ -78,6 +78,12 @@ func runFollowerReadsTest(ctx context.Context, t *test, c *cluster) {
 	if _, err := db.ExecContext(ctx, "SET CLUSTER SETTING kv.closed_timestamp.follower_reads_enabled = 'true'"); err != nil {
 		t.Fatalf("failed to enable follower reads: %v", err)
 	}
+	if _, err := db.ExecContext(ctx, "SET CLUSTER SETTING kv.range_split.by_load_enabled = 'false'"); err != nil {
```
Comment (nvanbenschoten) [inline pkg/cmd/roachtest/follower_reads.go]: Let's leave a note about why we disable these.

**Review by nvb — APPROVED** [review]
