### PR TITLE
raft: deflake non-determinisctic raft node tests

### LINKED ISSUE #132992: raft/rafttest: TestPause failed
raft/rafttest.TestPause [failed](https://tanzanite.cluster.engflow.com/invocations/default/d8f57495-6363-4ad7-a328-2a423f7cf47d?testReportRun=25&testReportShard=1&testReportAttempt=1#targets-Ly9wa2cvcmFmdC9yYWZ0dGVzdDpyYWZ0dGVzdF90ZXN0) on release-24.3 @ [4cbedefd790c75cb0f21f77ed8d917c8528a7d15](https://github.com/cockroachdb/cockroach/commits/4cbedefd790c75cb0f21f77ed8d917c8528a7d15):

```
raft2024/10/19 04:19:49 INFO: 3 received MsgVoteResp from 2 at term 2
raft2024/10/19 04:19:49 INFO: 3 has received 3 MsgVoteResp votes and 2 vote rejections
raft2024/10/19 04:19:49 INFO: 3 became leader at term 2
raft2024/10/19 04:19:49 INFO: 3 [logterm: 2, index: 6, vote: 3] ignored MsgVote from 4 [logterm: 1, index: 5] at term 2: supporting fortified leader 3 at epoch 1
raft2024/10/19 04:19:49 INFO: 2 [term: 2] received a MsgVote message with higher term from 4 [term: 3]
raft2024/10/19 04:19:49 INFO: 2 became follower at term 3
raft2024/10/19 04:19:49 INFO: 2 [logterm: 1, index: 5, vote: 0] cast MsgVote for 4 [logterm: 1, index: 5] at term 3
raft2024/10/19 04:19:49 INFO: 1 [term: 2] received a MsgVote message with higher term from 4 [term: 3]
raft2024/10/19 04:19:49 INFO: 1 became follower at term 3
raft2024/10/19 04:19:49 INFO: 1 [logterm: 1, index: 5, vote: 0] cast MsgVote for 4 [logterm: 1, index: 5] at term 3
raft2024/10/19 04:19:49 INFO: 1 [term: 3] ignored a MsgFortifyLeader message with lower term from 3 [term: 2]
raft2024/10/19 04:19:49 INFO: 2 [term: 3] ignored a MsgFortifyLeader message with lower term from 3 [term: 2]
raft2024/10/19 04:19:49 INFO: 1 [term: 3] ignored a MsgFortifyLeader message with lower term from 3 [term: 2]
raft2024/10/19 04:19:49 INFO: 4 received MsgVoteResp from 5 at term 3
raft2024/10/19 04:19:49 INFO: 4 has received 2 MsgVoteResp votes and 0 vote rejections
raft2024/10/19 04:19:49 INFO: 4 received MsgVoteResp from 1 at term 3
raft2024/10/19 04:19:49 INFO: 4 has received 3 MsgVoteResp votes and 0 vote rejections
raft2024/10/19 04:19:49 INFO: 4 became leader at term 3
raft2024/10/19 04:19:49 INFO: 4 [term: 3] ignored a MsgFortifyLeader message with lower term from 3 [term: 2]
raft2024/10/19 04:19:49 INFO: 5 [term: 3] ignored a MsgApp message with lower term from 3 [term: 2]
raft2024/10/19 04:19:49 INFO: 5 [term: 3] ignored a MsgApp message with lower term from 3 [term: 2]
raft2024/10/19 04:19:49 INFO: 1 [term: 3] ignored a MsgApp message with lower term from 3 [term: 2]
raft2024/10/19 04:19:49 INFO: 4 [term: 3] ignored a MsgApp message with lower term from 3 [term: 2]
raft2024/10/19 04:19:49 INFO: 1 [term: 3] ignored a MsgFortifyLeader message with lower term from 3 [term: 2]
raft2024/10/19 04:19:49 INFO: 3 [term: 2] received a MsgFortifyLeader message with higher term from 4 [term: 3]
raft2024/10/19 04:19:49 INFO: 3 became follower at term 3
raft2024/10/19 04:19:49 INFO: 2 [term: 3] ignored a MsgFortifyLeader message with lower term from 3 [term: 2]
raft2024/10/19 04:19:49 INFO: 5 [term: 3] ignored a MsgFortifyLeader message with lower term from 3 [term: 2]
raft2024/10/19 04:19:49 INFO: 2 [term: 3] ignored a MsgApp message with lower term from 3 [term: 2]
raft2024/10/19 04:19:49 INFO: 2 [term: 3] ignored a MsgApp message with lower term from 3 [term: 2]
raft2024/10/19 04:19:49 INFO: 4 [term: 3] ignored a MsgFortifyLeader message with lower term from 3 [term: 2]
raft2024/10/19 04:19:49 INFO: 5 [term: 3] ignored a MsgFortifyLeader message with lower term from 3 [term: 2]
raft2024/10/19 04:19:49 INFO: 4 [term: 3] ignored a MsgApp message with lower term from 3 [term: 2]
raft2024/10/19 04:19:49 INFO: 2 [term: 3] ignored a MsgFortifyLeader message with lower term from 3 [term: 2]
raft2024/10/19 04:19:49 INFO: 4 [term: 3] ignored a MsgApp message with lower term from 3 [term: 2]
raft2024/10/19 04:19:49 INFO: 2 [term: 3] ignored a MsgApp message with lower term from 3 [term: 2]
raft2024/10/19 04:19:49 INFO: 1 [term: 3] ignored a MsgApp message with lower term from 3 [term: 2]
raft2024/10/19 04:19:49 INFO: 5 [term: 3] ignored a MsgApp message with lower term from 3 [term: 2]
raft2024/10/19 04:19:49 INFO: found conflict at index 6 [existing term: 2, conflicting term: 3]
raft2024/10/19 04:19:49 INFO: replace the unstable entries from index 6
raft2024/10/19 04:19:49 INFO: 5 [term: 3] ignored a MsgFortifyLeader message with lower term from 3 [term: 2]
raft2024/10/19 04:19:49 INFO: 4 [term: 3] ignored a MsgFortifyLeader message with lower term from 3 [term: 2]
raft2024/10/19 04:19:49 INFO: 1 [term: 3] ignored a MsgApp message with lower term from 3 [term: 2]
    node_test.go:126: commits failed to converge!
I241019 04:19:54.853300 347 (gostd) node.go:162  [-] 13  raft.1: stop
I241019 04:19:54.853411 349 (gostd) node.go:162  [-] 14  raft.2: stop
I241019 04:19:54.853481 351 (gostd) node.go:162  [-] 15  raft.3: stop
I241019 04:19:54.853522 353 (gostd) node.go:162  [-] 16  raft.4: stop
I241019 04:19:54.853565 355 (gostd) node.go:162  [-] 17  raft.5: stop
--- FAIL: TestPause (5.38s)
```

Parameters:
 - <code>attempt=1</code>
 - <code>run=25</code>
 - <code>shard=1</code>
<details><summary>Help</summary>
<p>

See also: [How To Investigate a Go Test Failure \(internal\)](https://cockroachlabs.atlassian.net/l/c/HgfXfJgM)
</p>
</details>
<details><summary>Same failure on other branches</summary>
<p>

- #132205 raft/rafttest: TestPause failed [C-bug C-test-failure O-robot P-1 T-kv branch-master]
</p>
</details>
/cc @cockroachdb/kv
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*TestPause.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/bazci/githubpost/issues)
</sub>

Jira issue: CRDB-43390

### PR DESCRIPTION
**Pull request by iskettaneh**
We sporadically see that some raft node_test tests fail due to the leader not being stable. This commit should reduce the chances of that happening by increasing the election timeout to 250ms (instead of 50ms).

I couldn't reproduce the bug locally with this change.

If the bug still happens, we can try to force leadership to make it more deterministic.

Fixes: #132992, #131676, #132205, #133048

Release note: None

### CODE REVIEW

File: pkg/raft/rafttest/node.go [hunk 1]
```diff
@@ -49,7 +49,7 @@ func startNode(id raftpb.PeerID, peers []raft.Peer, iface iface) *node {
 	st := raft.NewMemoryStorage()
 	c := &raft.Config{
 		ID:                        id,
-		ElectionTick:              10,
```
Comment (pav-kv) [inline pkg/raft/rafttest/node.go:52]: NB: the tick duration is [5ms](https://github.com/cockroachdb/cockroach/blob/fc852a20fa1bc479baf39b739506b62a38bc31aa/pkg/raft/rafttest/node.go#L153), so this increase is from 50ms to 250ms (could fix the commit description).

**Comment by pav-kv** [comment]
Does it also fix some other `rafttest` issues currently open?

**Review by pav-kv — APPROVED** [review]
Thanks!

**Review by iskettaneh — COMMENTED** [review]
I updated the description to add the other similar issues that I was able to find. That being said, I will investigate a bit more since all these issues are kind of recent, and there was a change in this test recently as well

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/133270#-:-O9uVnG6Ecud92SuS46Z:bt75uy1)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @iskettaneh and @pav-kv)

___
*[`pkg/raft/rafttest/node.go` line 0 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/133270#gh-1813196450:-O9uUFtqEJ24V0tpKRlD:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/3898d36e60d04f9fcfbf75fd829d865f4e8c73f9/pkg/raft/rafttest/node.go#L0)):*
<details><summary><i>Previously, pav-kv (Pavel Kalinnikov) wrote…</i></summary><blockquote>

*(Reviewable was [unable](https://github.com/Reviewable/Reviewable/issues/14) to map [this GitHub inline comment thread](https://github.com/cockroachdb/cockroach/pull/133270#discussion_r1813196450) to the right spot — sorry!)*

NB: the tick duration is [5ms](https://github.com/cockroachdb/cockroach/blob/fc852a20fa1bc479baf39b739506b62a38bc31aa/pkg/raft/rafttest/node.go#L153), so this increase is from 50ms to 250ms (could fix the commit description).
</blockquote></details>

Done.
