### PR TITLE
release-21.2: sql: assign sequence ownership created when create/alter table

### LINKED ISSUE #69298: sql: related sequence from a `SERIAL` column is not deleted when `DROP TABLE`
**Describe the problem**

The `SERIAL` syntax under `CREATE TABLE` creates an underlying sequence. When we `DROP TABLE`, in PostgreSQL this underlying sequence will be deleted at the same time. But in CRDB, this sequence stays.

**To Reproduce**

I'm using PostgreSQL 13.3 and CockroachDB 21.1.7 on MacOS.

In PostgreSQL:

```
postgres=# \d
Did not find any relations.

postgres=# CREATE TABLE t (x SERIAL);
CREATE TABLE

postgres=# \d
           List of relations
 Schema |  Name   |   Type   |  Owner
--------+---------+----------+----------
 public | t       | table    | postgres
 public | t_x_seq | sequence | postgres
(2 rows)

postgres=# DROP TABLE  t;
DROP TABLE

postgres=# \d
Did not find any relations
```

In CockroachDB (with unrelated lines deleted):

```
demo@127.0.0.1:26257/movr> set serial_normalization=sql_sequence;
SET

demo@127.0.0.1:26257/movr> CREATE TABLE t (x SERIAL);
CREATE TABLE

demo@127.0.0.1:26257/movr> \d
  schema_name |         table_name         |   type   | owner | estimated_row_count | locality
--------------+----------------------------+----------+-------+---------------------+-----------
  public      | t                          | table    | demo  |                   0 | NULL
  public      | t_x_seq                    | sequence | demo  |                   0 | NULL



demo@127.0.0.1:26257/movr> DROP TABLE t;
DROP TABLE


demo@127.0.0.1:26257/movr> \d
  schema_name |         table_name         |   type   | owner | estimated_row_count | locality
--------------+----------------------------+----------+-------+---------------------+-----------
  public      | t_x_seq                    | sequence | demo  |                   0 | NULL
```

**If possible, provide steps to reproduce the behavior:**
I ran cockroachDB with:

cd ~/your/path/to/cockroachdb/cockroach
gmake buildshort
./cockroach demo

**Expected behavior**
In this `DROP TABLE` case, the SERIAL column in CRDB is expected to behave the same as in PostgreSQL.

### PR DESCRIPTION
**Pull request by chengxiong-ruan**
Backport 1/1 commits from #74840.

/cc @cockroachdb/release

---

  Fixes #69298

  Release note (bug fix): A sequence is created when a column is
  defined as `SERIAL` type and the `serial_normalization` session
  variable is set to `sql_sequence`. In this case, the sequence is
  owned by the column and the table where the column exists. The
  sequence should be dropped when the owner table/column is dropped,
  which is the postgres behavior. However, cockroach never set
  ownership information correctly but only dependecy relationship.
  So the sequence stays even the owner table/column does not exist
  anymore. This fix assigns correct ownership information to sequence
  descriptor and column descriptor so that cockroach can align with
  postgres behavior.

---

Release justification: backporting so that 21.2 can have same sequence drop behavior as postgres

### CODE REVIEW

**Review by ajwerner — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/75704#-:-Muhh6NZA974zGvncSNN:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @adityamaru)

File: pkg/sql/create_table.go [hunk 1]
```diff
@@ -2409,6 +2375,17 @@ func newTableDesc(
 		)
 	})
 
+	// We need to ensure sequence ownerships so that column owned sequences are
+	// correctly dropped when a column/table is dropped.
+	for colName, seqDesc := range colNameToOwnedSeq {
```
Comment (otan) [inline pkg/sql/create_table.go:2380]: i think this is broken if there is an error during `NewTableDesc`. in particular, you need an `if err != nil { return ret, err}` check above this stanza

**Review by otan — CHANGES_REQUESTED** [review]

File: pkg/sql/create_table.go (hunk 1 above)
Comment (otan) [reply pkg/sql/create_table.go:2380]:
```
root@127.0.0.1:26257/defaultdb> SET serial_normalization = sql_sequence;
SET


Time: 0ms total (execution 0ms / network 0ms)

root@127.0.0.1:26257/defaultdb>
CREATE TABLE test_serial (
        a INT PRIMARY KEY,
        b SERIAL
) with (fillfactor = 70000);

*
* ERROR: a SQL panic has occurred while executing the following statement:
* CREATE TABLE test_serial (a INT8 PRIMARY KEY, b INT8 NOT NULL DEFAULT nextval('defaultdb.public.test_serial_b_seq')) WITH (fillfactor = 70000)
*
*
* ERROR: a panic has occurred!
* runtime error: invalid memory address or nil pointer dereference
* (1) attached stack trace
*   -- stack trace:
*   | github.com/cockroachdb/cockroach/pkg/sql.(*Server).ServeConn.func1
*   | 	/Users/otan/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:678
*   | [...repeated from below...]
* Wraps: (2) while executing: CREATE TABLE _ (_ INT8 PRIMARY KEY, _ INT8 NOT NULL DEFAULT nextval('_')) WITH (_ = _)
* Wraps: (3) attached stack trace
*   -- stack trace:
*   | github.com/cockroachdb/cockroach/pkg/sql.(*Server).ServeConn.func1
*   | 	/Users/otan/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:678
*   | runtime.gopanic
*   | 	/usr/local/opt/go/libexec/src/runtime/panic.go:1038
*   | github.com/cockroachdb/cockroach/pkg/sql/colexecerror.CatchVectorizedRuntimeError.func1
*   | 	/Users/otan/go/src/github.com/cockroachdb/cockroach/pkg/sql/colexecerror/error.go:58
*   | runtime.gopanic
*   | 	/usr/local/opt/go/libexec/src/runtime/panic.go:1038
*   | runtime.panicmem
*   | 	/usr/local/opt/go/libexec/src/runtime/panic.go:221
*   | runtime.sigpanic
*   | 	/usr/local/opt/go/libexec/src/runtime/signal_unix.go:735
*   | github.com/cockroachdb/cockroach/pkg/sql.setSequenceOwner
*   | 	/Users/otan/go/src/github.com/cockroachdb/cockroach/pkg/sql/create_table.go:2606
*   | github.com/cockroachdb/cockroach/pkg/sql.newTableDesc
*   | 	/Users/otan/go/src/github.com/cockroachdb/cockroach/pkg/sql/create_table.go:2248
*   | github.com/cockroachdb/cockroach/pkg/sql.(*createTableNode).startExec
*   | 	/Users/otan/go/src/github.com/cockroachdb/cockroach/pkg/sql/create_table.go:375
*   | github.com/cockroachdb/cockroach/pkg/sql.startExec.func2
*   | 	/Users/otan/go/src/github.com/cockroachdb/cockroach/pkg/sql/plan.go:516
*   | github.com/cockroachdb/cockroach/pkg/sql.(*planVisitor).visitInternal.func1
*   | 	/Users/otan/go/src/github.com/cockroachdb/cockroach/pkg/sql/walk.go:112
*   | github.com/cockroachdb/cockroach/pkg/sql.(*planVisitor).visitInternal
*   | 	/Users/otan/go/src/github.com/cockroachdb/cockroach/pkg/sql/walk.go:295
*   | github.com/cockroachdb/cockroach/pkg/sql.(*planVisitor).visit
*   | 	/Users/otan/go/src/github.com/cockroachdb/cockroach/pkg/sql/walk.go:79
*   | github.com/cockroachdb/cockroach/pkg/sql.walkPlan
*   | 	/Users/otan/go/src/github.com/cockroachdb/cockroach/pkg/sql/walk.go:43
*   | github.com/cockroachdb/cockroach/pkg/sql.startExec
*   | 	/Users/otan/go/src/github.com/cockroachdb/cockroach/pkg/sql/plan.go:519
*   | github.com/cockroachdb/cockroach/pkg/sql.(*planNodeToRowSource).Start
*   | 	/Users/otan/go/src/github.com/cockroachdb/cockroach/pkg/sql/plan_node_to_row_source.go:146
*   | github.com/cockroachdb/cockroach/pkg/sql/colexec.(*Columnarizer).Init
*   | 	/Users/otan/go/src/github.com/cockroachdb/cockroach/pkg/sql/colexec/columnarizer.go:158
*   | github.com/cockroachdb/cockroach/pkg/sql/colflow.(*batchInfoCollector).Init
*   | 	/Users/otan/go/src/github.com/cockroachdb/cockroach/pkg/sql/colflow/stats.go:87
*   | github.com/cockroachdb/cockroach/pkg/sql/colflow.(*BatchFlowCoordinator).init.func1
*   | 	/Users/otan/go/src/github.com/cockroachdb/cockroach/pkg/sql/colflow/flow_coordinator.go:235
*   | github.com/cockroachdb/cockroach/pkg/sql/colexecerror.CatchVectorizedRuntimeError
*   | 	/Users/otan/go/src/github.com/cockroachdb/cockroach/pkg/sql/colexecerror/error.go:91
*   | github.com/cockroachdb/cockroach/pkg/sql/colflow.(*BatchFlowCoordinator).init
*   | 	/Users/otan/go/src/github.com/cockroachdb/cockroach/pkg/sql/colflow/flow_coordinator.go:234
*   | github.com/cockroachdb/cockroach/pkg/sql/colflow.(*BatchFlowCoordinator).Run
*   | 	/Users/otan/go/src/github.com/cockroachdb/cockroach/pkg/sql/colflow/flow_coordinator.go:279
*   | github.com/cockroachdb/cockroach/pkg/sql/colflow.(*vectorizedFlow).Run
*   | 	/Users/otan/go/src/github.com/cockroachdb/cockroach/pkg/sql/colflow/vectorized_flow.go:259
*   | github.com/cockroachdb/cockroach/pkg/sql.(*DistSQLPlanner).Run
*   | 	/Users/otan/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsql_running.go:573
*   | github.com/cockroachdb/cockroach/pkg/sql.(*DistSQLPlanner).PlanAndRun
*   | 	/Users/otan/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsql_running.go:1409
*   | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execWithDistSQLEngine
*   | 	/Users/otan/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:1411
*   | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).dispatchToExecutionEngine
*   | 	/Users/otan/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:1088
*   | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execStmtInOpenState
*   | 	/Users/otan/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:718
*   | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execStmt
*   | 	/Users/otan/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:137
*   | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execCmd.func1
*   | 	/Users/otan/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:1742
*   | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execCmd
*   | 	/Users/otan/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:1746
*   | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).run
*   | 	/Users/otan/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:1675
* Wraps: (4) runtime error: invalid memory address or nil pointer dereference
* Error types: (1) *withstack.withStack (2) *safedetails.withSafeDetails (3) *withstack.withStack (4) runtime.errorString
* ```

Comment (otan) [reply pkg/sql/create_table.go:2380]: you'll want #75841 too

**Review by chengxiong-ruan — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/75704)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @adityamaru and @otan)

___
*[pkg/sql/create_table.go, line 2380 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/75704#-MuagFdBFurDWaXt2W0g-r1-2380:-MuseL5e9qXJyBvZfQtx:b4954fb) ([raw file](https://github.com/cockroachdb/cockroach/blob/8da2ad8341c592bf555463f9d882bb2581117777/pkg/sql/create_table.go#L2380)):*
<details><summary><i>Previously, otan (Oliver Tan) wrote…</i></summary><blockquote>

you'll want #75841 too
</blockquote></details>

Thanks! Fixed

**Review by otan — APPROVED** [review]

**Review by chengxiong-ruan — COMMENTED** [review]
There are a few tests failing in the CI but shouldn't be relevant to this change. Talked to Marylia that it's because of some limitation on Bazel in 21.2 which was fixed in 22.1. I tested it with `make test` at local and it passed. So it's safe to merge.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/75704#-:-Muv0SBY1wBJiMEbtd8A:b4clr7e)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @adityamaru and @otan)
