### PR TITLE
sql: fix panic in CTAS with some virtual tables

### LINKED ISSUE #65512: Node crash from CTAS using an internal table
**Describe the problem**

By running the following query, my local cluster crashed a node and made the cluster unavailable.
`create table usage as (select * from crdb_internal.node_statement_statistics);`

**To Reproduce**
```
10:34 $ ps -ef | grep "cockroach start"
  502 48495     1   0 10:33AM ttys003    0:08.96 /usr/local/bin/cockroach start --insecure --store=path=/Users/chriscasano/local/1/data --log-dir=/Users/chriscasano/local/1/logs --cache=5% --max-sql-memory=5% --listen-addr=127.0.0.1 --port=26257 --http-port=26258 --locality=region=local,zone=local --join=127.0.0.1:26257
  502 48507     1   0 10:33AM ttys003    0:04.10 /usr/local/bin/cockroach start --insecure --store=path=/Users/chriscasano/local/2/data --log-dir=/Users/chriscasano/local/2/logs --cache=5% --max-sql-memory=5% --listen-addr=127.0.0.1 --port=26259 --http-port=26260 --locality=region=local,zone=local --join=127.0.0.1:26257
  502 48519     1   0 10:33AM ttys003    0:04.01 /usr/local/bin/cockroach start --insecure --store=path=/Users/chriscasano/local/3/data --log-dir=/Users/chriscasano/local/3/logs --cache=5% --max-sql-memory=5% --listen-addr=127.0.0.1 --port=26261 --http-port=26262 --locality=region=local,zone=local --join=127.0.0.1:26257
  502 48531     1   0 10:33AM ttys003    0:03.94 /usr/local/bin/cockroach start --insecure --store=path=/Users/chriscasano/local/4/data --log-dir=/Users/chriscasano/local/4/logs --cache=5% --max-sql-memory=5% --listen-addr=127.0.0.1 --port=26263 --http-port=26264 --locality=region=local,zone=local --join=127.0.0.1:26257
  502 48544     1   0 10:33AM ttys003    0:04.01 /usr/local/bin/cockroach start --insecure --store=path=/Users/chriscasano/local/5/data --log-dir=/Users/chriscasano/local/5/logs --cache=5% --max-sql-memory=5% --listen-addr=127.0.0.1 --port=26265 --http-port=26266 --locality=region=local,zone=local --join=127.0.0.1:26257
  502 48720 48214   0 10:34AM ttys003    0:00.00 grep cockroach start
✔ ~
10:34 $ csql
#
# Welcome to the CockroachDB SQL shell.
# All statements must be terminated by a semicolon.
# To exit, type: \q.
#
# Server version: CockroachDB CCL v21.1.0 (x86_64-apple-darwin19, built 2021/05/17 13:52:51, go1.15.11) (same version as client)
# Cluster ID: 39239ecd-d086-48e2-8537-57f5fcbb80d1
# Organization: Cockroach Labs - Production Testing
#
# Enter \? for a brief introduction.
#
root@:26257/defaultdb> create table usage as (select * from crdb_internal.node_statement_statistics);
W210520 14:35:10.163431 1 cli/sql.go:273  [-] 1  cannot save command-line history: write_history: illegal byte sequence
ERROR: driver: bad connection
warning: connection lost!
opening new connection: all session settings will be lost
warning: error retrieving the transaction status: dial tcp [::1]:26257: connect: connection refused
warning: connection lost!
opening new connection: all session settings will be lost
warning: error retrieving the database name: dial tcp [::1]:26257: connect: connection refused
root@:26257/? ?> exit
ERROR: driver: bad connection
Failed running "sql"
✘-1 ~
10:35 $ ps -ef | grep "cockroach start"
  502 48507     1   0 10:33AM ttys003    0:08.66 /usr/local/bin/cockroach start --insecure --store=path=/Users/chriscasano/local/2/data --log-dir=/Users/chriscasano/local/2/logs --cache=5% --max-sql-memory=5% --listen-addr=127.0.0.1 --port=26259 --http-port=26260 --locality=region=local,zone=local --join=127.0.0.1:26257
  502 48519     1   0 10:33AM ttys003    0:08.47 /usr/local/bin/cockroach start --insecure --store=path=/Users/chriscasano/local/3/data --log-dir=/Users/chriscasano/local/3/logs --cache=5% --max-sql-memory=5% --listen-addr=127.0.0.1 --port=26261 --http-port=26262 --locality=region=local,zone=local --join=127.0.0.1:26257
  502 48531     1   0 10:33AM ttys003    0:08.40 /usr/local/bin/cockroach start --insecure --store=path=/Users/chriscasano/local/4/data --log-dir=/Users/chriscasano/local/4/logs --cache=5% --max-sql-memory=5% --listen-addr=127.0.0.1 --port=26263 --http-port=26264 --locality=region=local,zone=local --join=127.0.0.1:26257
  502 48544     1   0 10:33AM ttys003    0:08.97 /usr/local/bin/cockroach start --insecure --store=path=/Users/chriscasano/local/5/data --log-dir=/Users/chriscasano/local/5/logs --cache=5% --max-sql-memory=5% --listen-addr=127.0.0.1 --port=26265 --http-port=26266 --locality=region=local,zone=local --join=127.0.0.1:26257
  502 48779 48214   0 10:35AM ttys003    0:00.00 grep cockroach start
✔ ~
10:35 $ cockroach sql --insecure --port=26259
#
# Welcome to the CockroachDB SQL shell.
# All statements must be terminated by a semicolon.
# To exit, type: \q.
#
^C
✘-INT ~


10:36 $ tail -25 ~/local/1/logs/cockroach.log
W210520 14:35:11.316637 255 server/node.go:768 ⋮ [n1,summaries] 508  health alerts detected: ‹{Alerts:[{StoreID:1 Category:METRICS Description:ranges.underreplicated Value:21}]}›
I210520 14:35:12.009921 17210 sql/schema_changer.go:571 ⋮ [n1,job=‹660114342532218881›,scExec,id=52] 509  schema change on ‹"usage"› (v1) starting execution...
I210520 14:35:12.010005 17210 sql/schema_changer.go:361 ⋮ [n1,job=‹660114342532218881›,scExec,id=52] 510  starting backfill for CREATE TABLE AS with query ‹"(SELECT * FROM defaultdb.crdb_internal.node_statement_statistics)"›
E210520 14:35:12.034331 17132 1@util/log/logcrash/crash_reporting.go:140 ⋮ [n1,job=‹660114342532218881›,scExec,id=52] 511  a panic has occurred!
E210520 14:35:12.034331 17132 1@util/log/logcrash/crash_reporting.go:140 ⋮ [n1,job=‹660114342532218881›,scExec,id=52] 511 +runtime error: invalid memory address or nil pointer dereference
E210520 14:35:12.034331 17132 1@util/log/logcrash/crash_reporting.go:140 ⋮ [n1,job=‹660114342532218881›,scExec,id=52] 511 +(1) attached stack trace
E210520 14:35:12.034331 17132 1@util/log/logcrash/crash_reporting.go:140 ⋮ [n1,job=‹660114342532218881›,scExec,id=52] 511 +  -- stack trace:
E210520 14:35:12.034331 17132 1@util/log/logcrash/crash_reporting.go:140 ⋮ [n1,job=‹660114342532218881›,scExec,id=52] 511 +  | runtime.gopanic
E210520 14:35:12.034331 17132 1@util/log/logcrash/crash_reporting.go:140 ⋮ [n1,job=‹660114342532218881›,scExec,id=52] 511 +  | 	/usr/local/go/src/runtime/panic.go:969
E210520 14:35:12.034331 17132 1@util/log/logcrash/crash_reporting.go:140 ⋮ [n1,job=‹660114342532218881›,scExec,id=52] 511 +  | runtime.panicmem
E210520 14:35:12.034331 17132 1@util/log/logcrash/crash_reporting.go:140 ⋮ [n1,job=‹660114342532218881›,scExec,id=52] 511 +  | 	/usr/local/go/src/runtime/panic.go:212
E210520 14:35:12.034331 17132 1@util/log/logcrash/crash_reporting.go:140 ⋮ [n1,job=‹660114342532218881›,scExec,id=52] 511 +  | runtime.sigpanic
E210520 14:35:12.034331 17132 1@util/log/logcrash/crash_reporting.go:140 ⋮ [n1,job=‹660114342532218881›,scExec,id=52] 511 +  | 	/usr/local/go/src/runtime/signal_unix.go:742
E210520 14:35:12.034331 17132 1@util/log/logcrash/crash_reporting.go:140 ⋮ [n1,job=‹660114342532218881›,scExec,id=52] 511 +  | github.com/cockroachdb/cockroach/pkg/sql.glob..func54
E210520 14:35:12.034331 17132 1@util/log/logcrash/crash_reporting.go:140 ⋮ [n1,job=‹660114342532218881›,scExec,id=52] 511 +  | 	/go/src/github.com/cockroachdb/cockroach/pkg/sql/crdb_internal.go:885
E210520 14:35:12.034331 17132 1@util/log/logcrash/crash_reporting.go:140 ⋮ [n1,job=‹660114342532218881›,scExec,id=52] 511 +  | github.com/cockroachdb/cockroach/pkg/sql.(*virtualDefEntry).getPlanInfo.func1.1
E210520 14:35:12.034331 17132 1@util/log/logcrash/crash_reporting.go:140 ⋮ [n1,job=‹660114342532218881›,scExec,id=52] 511 +  | 	/go/src/github.com/cockroachdb/cockroach/pkg/sql/virtual_schema.go:526
E210520 14:35:12.034331 17132 1@util/log/logcrash/crash_reporting.go:140 ⋮ [n1,job=‹660114342532218881›,scExec,id=52] 511 +  | github.com/cockroachdb/cockroach/pkg/sql.setupGenerator.func3
E210520 14:35:12.034331 17132 1@util/log/logcrash/crash_reporting.go:140 ⋮ [n1,job=‹660114342532218881›,scExec,id=52] 511 +  | 	/go/src/github.com/cockroachdb/cockroach/pkg/sql/virtual_table.go:121
E210520 14:35:12.034331 17132 1@util/log/logcrash/crash_reporting.go:140 ⋮ [n1,job=‹660114342532218881›,scExec,id=52] 511 +  | github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunAsyncTask.func1
E210520 14:35:12.034331 17132 1@util/log/logcrash/crash_reporting.go:140 ⋮ [n1,job=‹660114342532218881›,scExec,id=52] 511 +  | 	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:351
E210520 14:35:12.034331 17132 1@util/log/logcrash/crash_reporting.go:140 ⋮ [n1,job=‹660114342532218881›,scExec,id=52] 511 +  | runtime.goexit
E210520 14:35:12.034331 17132 1@util/log/logcrash/crash_reporting.go:140 ⋮ [n1,job=‹660114342532218881›,scExec,id=52] 511 +  | 	/usr/local/go/src/runtime/asm_amd64.s:1374
E210520 14:35:12.034331 17132 1@util/log/logcrash/crash_reporting.go:140 ⋮ [n1,job=‹660114342532218881›,scExec,id=52] 511 +Wraps: (2) runtime error: invalid memory address or nil pointer dereference
E210520 14:35:12.034331 17132 1@util/log/logcrash/crash_reporting.go:140 ⋮ [n1,job=‹660114342532218881›,scExec,id=52] 511 +Error types: (1) *withstack.withStack (2) runtime.errorString

✔ ~
10:37 $ tail -25 ~/local/1/logs/cockroach.stderr.log
*
*
* ERROR: [n1,job=660114342532218881,scExec,id=52] a panic has occurred!
* runtime error: invalid memory address or nil pointer dereference
* (1) attached stack trace
*   -- stack trace:
*   | runtime.gopanic
*   | 	/usr/local/go/src/runtime/panic.go:969
*   | runtime.panicmem
*   | 	/usr/local/go/src/runtime/panic.go:212
*   | runtime.sigpanic
*   | 	/usr/local/go/src/runtime/signal_unix.go:742
*   | github.com/cockroachdb/cockroach/pkg/sql.glob..func54
*   | 	/go/src/github.com/cockroachdb/cockroach/pkg/sql/crdb_internal.go:885
*   | github.com/cockroachdb/cockroach/pkg/sql.(*virtualDefEntry).getPlanInfo.func1.1
*   | 	/go/src/github.com/cockroachdb/cockroach/pkg/sql/virtual_schema.go:526
*   | github.com/cockroachdb/cockroach/pkg/sql.setupGenerator.func3
*   | 	/go/src/github.com/cockroachdb/cockroach/pkg/sql/virtual_table.go:121
*   | github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunAsyncTask.func1
*   | 	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:351
*   | runtime.goexit
*   | 	/usr/local/go/src/runtime/asm_amd64.s:1374
* Wraps: (2) runtime error: invalid memory address or nil pointer dereference
* Error types: (1) *withstack.withStack (2) runtime.errorString
*
```

**Environment:**
 - CockroachDB version:  21.1.0
 - Server OS: MacOS
 - Client app: cockroach sql

### PR DESCRIPTION
**Pull request by yuzefovich**
CTAS creates a fake planner that doesn't have `sqlStatsCollector` set
(which lives on the `connExecutor`), so the usage of several virtual
tables in CTAS would previously lead to a crash. The proper fix doesn't
appear to be easy, so this commit prohibits the usage of those virtual
tables in CTAS context.

Fixes: #65512.

Release note (bug fix): CockroachDB would previously crash when
attempting to create a table using CREATE TABLE ... AS syntax where AS
part selects from `crdb_internal.node_statement_statistics`,
`crdb_internal.node_transaction_statistics`, or
`crdb_internal.node_txn_stats` virtual tables.

### CODE REVIEW

**Review by arulajmani — APPROVED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/65516#-:-Ma9qDcaD4hSZClIEI52:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained

**Review by maryliag — APPROVED** [review]

**Comment by yuzefovich** [comment]
TFTRs!

bors r+

File: pkg/sql/crdb_internal.go [hunk 1]
```diff
@@ -836,6 +836,16 @@ func execStatVar(count int64, n roachpb.NumericStat) tree.Datum {
 	return tree.NewDFloat(tree.DFloat(n.GetVariance(count)))
 }
 
+// getSQLStats retrieves a sqlStats object from the planner or returns an error
+// if not available. virtualTableName specifies the virtual table for which this
+// sqlStats object is needed.
+func getSQLStats(p *planner, virtualTableName string) (*sqlStats, error) {
+	if p.extendedEvalCtx.sqlStatsCollector == nil || p.extendedEvalCtx.sqlStatsCollector.sqlStats == nil {
+		return nil, errors.Newf("%s cannot be used in CREATE TABLE AS", virtualTableName)
```
Comment (rafiss) [inline pkg/sql/crdb_internal.go:844]: is CTAS the only context in which this could be nil? i wonder if in the future it might be nil for another reason, but the user will see this error message about CTAS

**Review by yuzefovich — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/65516)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/sql/crdb_internal.go, line 844 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/65516#-Ma9joC3U5HIIQ1gon_y-r1-844:-MaAdIju8hHJ50GCS_VO:b-75jjdo) ([raw file](https://github.com/cockroachdb/cockroach/blob/03ca31b3cbad90191ead63b6929cbc3bd3c0651f/pkg/sql/crdb_internal.go#L844)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

is CTAS the only context in which this could be nil? i wonder if in the future it might be nil for another reason, but the user will see this error message about CTAS
</blockquote></details>

Good point. I'll open up a separate PR to update the message (to `cannot be used in this context`).
