### PR TITLE
builtins: use IdentityReturnType when possible

### LINKED ISSUE #70475: sql/tests: TestRandomSyntaxFunctions failed
sql/tests.TestRandomSyntaxFunctions [failed](https://teamcity.cockroachdb.com/viewLog.html?buildId=3473202&tab=buildLog) with [artifacts](https://teamcity.cockroachdb.com/viewLog.html?buildId=3473202&tab=artifacts#/) on master @ [676dc076dc6a137d88eac9217764bbb63beae86f](https://github.com/cockroachdb/cockroach/commits/676dc076dc6a137d88eac9217764bbb63beae86f):

Random syntax error:

```
    rsg_test.go:779: Crash detected: server panic: pq: internal error: expected *DTuple, found *tree.DOid
```
Query:

```
        SELECT json_populate_recordset(3923269572:::OID, '{"test": "json"}':::JSONB) ;
```
<details><summary>Reproduce</summary>
<p>
To reproduce, try:

```bash
make stressrace TESTS=TestRandomSyntaxFunctions PKG=./pkg/sql/tests TESTTIMEOUT=5m STRESSFLAGS='-timeout 5m' 2>&1
```
</p>
</details>
<details><summary>Same failure on other branches</summary>
<p>

- #66514 sql/tests: TestRandomSyntaxFunctions failed [C-test-failure O-robot branch-release-21.1]
- #63943 sql/tests: TestRandomSyntaxFunctions failed [C-test-failure O-robot T-sql-experience branch-release-20.2]
</p>
</details>
<details><summary>Internal log</summary>
<p>

```
mjibson marked as alumn{us/a}; resolving to rafiss instead
```
</p>
</details>

/cc @cockroachdb/sql-experience rafiss
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*TestRandomSyntaxFunctions.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)
</sub>

### PR DESCRIPTION
**Pull request by rafiss**
fixes #70475

see individual commits

Release note: None

### CODE REVIEW

File: pkg/sql/sem/builtins/generator_builtins.go [hunk 1]
```diff
@@ -1261,13 +1261,8 @@ func makeJSONPopulateImpl(gen tree.GeneratorWithExprsFactory, info string) tree.
...
 		// The second argument can also be null, in which case the first argument
 		// is returned as-is.
-		Types: tree.ArgTypes{{"base", types.Any}, {"from_json", types.Jsonb}},
-		ReturnType: func(args []tree.TypedExpr) *types.T {
-			if len(args) != 2 {
-				return tree.UnknownReturnType
-			}
-			return args[0].ResolvedType()
-		},
+		Types:              tree.ArgTypes{{"base", types.AnyTuple}, {"from_json", types.Jsonb}},
```
Comment (jordanlewis) [inline pkg/sql/sem/builtins/generator_builtins.go:1264]: The reason I set this to be `types.Any` is to match the argument type in Postgres itself, which is any, and not tuple. I'm not sure if this matters, but that's why I did it:

```
postgres=# select proargtypes[0]::regtype from pg_proc where proname = 'jsonb_populate_record';
 proargtypes
-------------
 anyelement
(1 row)
```

Comment (rafiss) [reply pkg/sql/sem/builtins/generator_builtins.go:1264]: hm, so looks like PG must do some other validation on the input args
```
rafiss@127:postgres> select * from json_populate_record(null::int, '{"a":1,"b":2}')
first argument of json_populate_record must be a row type
```

if you try this in crdb:
```
root@:26257/defaultdb> select * from json_populate_record(null::record, '{"a":1,"b":2}');
ERROR: anonymous records cannot be used with json_populate_record
```

which seems like a misleading message

Comment (otan) [reply pkg/sql/sem/builtins/generator_builtins.go:1264]: interesting, postgres caches records, wonder if we should do something similar:
https://github.com/postgres/postgres/blob/4548c76738b368a11a5dad052f9653a349eeb52c/src/backend/utils/adt/jsonfuncs.c#L3815-L3825

anyway yeah it's checked internally i think? the NULL is checked here
https://github.com/postgres/postgres/blob/4548c76738b368a11a5dad052f9653a349eeb52c/src/backend/utils/adt/jsonfuncs.c#L3416-L3422

though i can't find where it returns the signature error if it is a not-null not-tuple. maybe we should just change the `tree.MustBeDTuple` check here: https://github.com/cockroachdb/cockroach/blob/50396a923da22a9685fee5c3c4248e88c921ab8e/pkg/sql/sem/builtins/generator_builtins.go#L1321

Comment (rafiss) [reply pkg/sql/sem/builtins/generator_builtins.go]: It looks like PG checks the not-null not-tuple case in the same place as above. there's also this fun message that PG has, which probably doesn't apply to CRDB's type system:
```
rafiss@127:postgres> select * from json_populate_recordset(null, '{"a":1,"b":2}')
could not determine polymorphic type because input has type unknown
```

**Comment by rafiss** [comment]
this is ready for another review

**Review by otan — APPROVED** [review]

**Comment by rafiss** [comment]
bors r=otan

**Comment by jordanlewis** [comment]
@rafiss thanks for fixing this issue!
