### PR TITLE
sql: give cluster time to upgrade under test

### LINKED ISSUE #154077: pkg/sql/logictest/tests/cockroach-go-testserver-25.3/cockroach-go-testserver-25_3_test: TestLogic_mixed_version_upgrade_preserve_ttl failed [logic test retry too short]
pkg/sql/logictest/tests/cockroach-go-testserver-25.3/cockroach-go-testserver-25_3_test.TestLogic_mixed_version_upgrade_preserve_ttl [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Ci_TestsAwsLinuxArm64_UnitTests/20515632?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Ci_TestsAwsLinuxArm64_UnitTests/20515632?buildTab=artifacts#/) on release-25.4 @ [9221c5318324b33455257088d3a48fae69346359](https://github.com/cockroachdb/cockroach/commits/9221c5318324b33455257088d3a48fae69346359):

```
=== RUN   TestLogic_mixed_version_upgrade_preserve_ttl
    test_log_scope.go:171: test logs captured to: /artifacts/tmp/_tmp/9f5fe453e1e6aefdb79fee60981c27dd/logTestLogic_mixed_version_upgrade_preserve_ttl2187296340
    test_log_scope.go:82: use -show-logs to present logs inline
    logic.go:3205: let $initial_version = 25.3
    logic.go:3143: 
         
        /home/roach/.cache/bazel/_bazel_roach/c5a4e7d36696d9cd970af2045211a7df/sandbox/processwrapper-sandbox/5763/execroot/com_github_cockroachdb_cockroach/bazel-out/aarch64-fastbuild/bin/pkg/sql/logictest/tests/cockroach-go-testserver-25.3/cockroach-go-testserver-25_3_test_/cockroach-go-testserver-25_3_test.runfiles/com_github_cockroachdb_cockroach/pkg/sql/logictest/testdata/logic_test/mixed_version_upgrade_preserve_ttl:19: SELECT version != '25.3' FROM [SHOW CLUSTER SETTING version]
        expected:
            true
            
        but found (query options: "retry") :
            false
            
[22:08:15] --- progress: /home/roach/.cache/bazel/_bazel_roach/c5a4e7d36696d9cd970af2045211a7df/sandbox/processwrapper-sandbox/5763/execroot/com_github_cockroachdb_cockroach/bazel-out/aarch64-fastbuild/bin/pkg/sql/logictest/tests/cockroach-go-testserver-25.3/cockroach-go-testserver-25_3_test_/cockroach-go-testserver-25_3_test.runfiles/com_github_cockroachdb_cockroach/pkg/sql/logictest/testdata/logic_test/mixed_version_upgrade_preserve_ttl: 2 statements
[22:08:15] --- done: /home/roach/.cache/bazel/_bazel_roach/c5a4e7d36696d9cd970af2045211a7df/sandbox/processwrapper-sandbox/5763/execroot/com_github_cockroachdb_cockroach/bazel-out/aarch64-fastbuild/bin/pkg/sql/logictest/tests/cockroach-go-testserver-25.3/cockroach-go-testserver-25_3_test_/cockroach-go-testserver-25_3_test.runfiles/com_github_cockroachdb_cockroach/pkg/sql/logictest/testdata/logic_test/mixed_version_upgrade_preserve_ttl with config cockroach-go-testserver-25.3: 2 tests, 1 failures
    logic.go:4494: 
        /home/roach/.cache/bazel/_bazel_roach/c5a4e7d36696d9cd970af2045211a7df/sandbox/processwrapper-sandbox/5763/execroot/com_github_cockroachdb_cockroach/bazel-out/aarch64-fastbuild/bin/pkg/sql/logictest/tests/cockroach-go-testserver-25.3/cockroach-go-testserver-25_3_test_/cockroach-go-testserver-25_3_test.runfiles/com_github_cockroachdb_cockroach/pkg/sql/logictest/testdata/logic_test/mixed_version_upgrade_preserve_ttl:24: error while processing
    logic.go:4494: /home/roach/.cache/bazel/_bazel_roach/c5a4e7d36696d9cd970af2045211a7df/sandbox/processwrapper-sandbox/5763/execroot/com_github_cockroachdb_cockroach/bazel-out/aarch64-fastbuild/bin/pkg/sql/logictest/tests/cockroach-go-testserver-25.3/cockroach-go-testserver-25_3_test_/cockroach-go-testserver-25_3_test.runfiles/com_github_cockroachdb_cockroach/pkg/sql/logictest/testdata/logic_test/mixed_version_upgrade_preserve_ttl:24: too many errors encountered, skipping the rest of the input
cockroach logs captured in: /artifacts/tmp/_tmp/9f5fe453e1e6aefdb79fee60981c27dd/cockroach-logs1114556003
    panic.go:635: -- test log scope end --
test logs left over in: /artifacts/tmp/_tmp/9f5fe453e1e6aefdb79fee60981c27dd/logTestLogic_mixed_version_upgrade_preserve_ttl2187296340
--- FAIL: TestLogic_mixed_version_upgrade_preserve_ttl (93.54s)
```
<details><summary>Help</summary>
<p>

See also: [How To Investigate a Go Test Failure \(internal\)](https://cockroachlabs.atlassian.net/l/c/HgfXfJgM)
</p>
</details>
/cc @cockroachdb/sql-foundations
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*TestLogic_mixed_version_upgrade_preserve_ttl.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/bazci/githubpost/issues)

</sub>

Jira issue: CRDB-54769

### LINKED ISSUE #154550: pkg/sql/logictest/tests/cockroach-go-testserver-25.3/cockroach-go-testserver-25_3_test: TestLogic_mixed_version_upgrade_preserve_ttl failed [logic test retry too short]
pkg/sql/logictest/tests/cockroach-go-testserver-25.3/cockroach-go-testserver-25_3_test.TestLogic_mixed_version_upgrade_preserve_ttl [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Ci_TestsAwsLinuxArm64_UnitTests/20544935?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Ci_TestsAwsLinuxArm64_UnitTests/20544935?buildTab=artifacts#/) on master @ [0c9c77ff672980fbdd7526aae23c2391b642b22d](https://github.com/cockroachdb/cockroach/commits/0c9c77ff672980fbdd7526aae23c2391b642b22d):

```
=== RUN   TestLogic_mixed_version_upgrade_preserve_ttl
    test_log_scope.go:171: test logs captured to: /artifacts/tmp/_tmp/9f5fe453e1e6aefdb79fee60981c27dd/logTestLogic_mixed_version_upgrade_preserve_ttl40455405
    test_log_scope.go:82: use -show-logs to present logs inline
    logic.go:3205: let $initial_version = 25.3
    logic.go:3143: 
         
        /home/roach/.cache/bazel/_bazel_roach/c5a4e7d36696d9cd970af2045211a7df/sandbox/processwrapper-sandbox/3238/execroot/com_github_cockroachdb_cockroach/bazel-out/aarch64-fastbuild/bin/pkg/sql/logictest/tests/cockroach-go-testserver-25.3/cockroach-go-testserver-25_3_test_/cockroach-go-testserver-25_3_test.runfiles/com_github_cockroachdb_cockroach/pkg/sql/logictest/testdata/logic_test/mixed_version_upgrade_preserve_ttl:19: SELECT version != '25.3' FROM [SHOW CLUSTER SETTING version]
        expected:
            true
            
        but found (query options: "retry") :
            false
            
[18:15:12] --- progress: /home/roach/.cache/bazel/_bazel_roach/c5a4e7d36696d9cd970af2045211a7df/sandbox/processwrapper-sandbox/3238/execroot/com_github_cockroachdb_cockroach/bazel-out/aarch64-fastbuild/bin/pkg/sql/logictest/tests/cockroach-go-testserver-25.3/cockroach-go-testserver-25_3_test_/cockroach-go-testserver-25_3_test.runfiles/com_github_cockroachdb_cockroach/pkg/sql/logictest/testdata/logic_test/mixed_version_upgrade_preserve_ttl: 2 statements
[18:15:12] --- done: /home/roach/.cache/bazel/_bazel_roach/c5a4e7d36696d9cd970af2045211a7df/sandbox/processwrapper-sandbox/3238/execroot/com_github_cockroachdb_cockroach/bazel-out/aarch64-fastbuild/bin/pkg/sql/logictest/tests/cockroach-go-testserver-25.3/cockroach-go-testserver-25_3_test_/cockroach-go-testserver-25_3_test.runfiles/com_github_cockroachdb_cockroach/pkg/sql/logictest/testdata/logic_test/mixed_version_upgrade_preserve_ttl with config cockroach-go-testserver-25.3: 2 tests, 1 failures
    logic.go:4494: 
        /home/roach/.cache/bazel/_bazel_roach/c5a4e7d36696d9cd970af2045211a7df/sandbox/processwrapper-sandbox/3238/execroot/com_github_cockroachdb_cockroach/bazel-out/aarch64-fastbuild/bin/pkg/sql/logictest/tests/cockroach-go-testserver-25.3/cockroach-go-testserver-25_3_test_/cockroach-go-testserver-25_3_test.runfiles/com_github_cockroachdb_cockroach/pkg/sql/logictest/testdata/logic_test/mixed_version_upgrade_preserve_ttl:24: error while processing
    logic.go:4494: /home/roach/.cache/bazel/_bazel_roach/c5a4e7d36696d9cd970af2045211a7df/sandbox/processwrapper-sandbox/3238/execroot/com_github_cockroachdb_cockroach/bazel-out/aarch64-fastbuild/bin/pkg/sql/logictest/tests/cockroach-go-testserver-25.3/cockroach-go-testserver-25_3_test_/cockroach-go-testserver-25_3_test.runfiles/com_github_cockroachdb_cockroach/pkg/sql/logictest/testdata/logic_test/mixed_version_upgrade_preserve_ttl:24: too many errors encountered, skipping the rest of the input
cockroach logs captured in: /artifacts/tmp/_tmp/9f5fe453e1e6aefdb79fee60981c27dd/cockroach-logs1689881549
    panic.go:635: -- test log scope end --
test logs left over in: /artifacts/tmp/_tmp/9f5fe453e1e6aefdb79fee60981c27dd/logTestLogic_mixed_version_upgrade_preserve_ttl40455405
--- FAIL: TestLogic_mixed_version_upgrade_preserve_ttl (92.22s)
```
<details><summary>Help</summary>
<p>

See also: [How To Investigate a Go Test Failure \(internal\)](https://cockroachlabs.atlassian.net/l/c/HgfXfJgM)
</p>
</details>
<details><summary>Same failure on other branches</summary>
<p>

- #154077 pkg/sql/logictest/tests/cockroach-go-testserver-25.3/cockroach-go-testserver-25_3_test: TestLogic_mixed_version_upgrade_preserve_ttl failed [C-test-failure O-robot T-sql-foundations branch-release-25.4]
</p>
</details>
/cc @cockroachdb/sql-foundations
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*TestLogic_mixed_version_upgrade_preserve_ttl.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/bazci/githubpost/issues)

</sub>

Jira issue: CRDB-54993

### LINKED ISSUE #155046: pkg/sql/logictest/tests/cockroach-go-testserver-25.2/cockroach-go-testserver-25_2_test: TestLogic_mixed_version_upgrade_preserve_ttl failed [logic test retry too short]
pkg/sql/logictest/tests/cockroach-go-testserver-25.2/cockroach-go-testserver-25_2_test.TestLogic_mixed_version_upgrade_preserve_ttl [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Ci_TestsAwsLinuxArm64_UnitTests/20577548?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Ci_TestsAwsLinuxArm64_UnitTests/20577548?buildTab=artifacts#/) on master @ [c5714b6b8be8ac555ad3f4ae490c5b0b0c7cf295](https://github.com/cockroachdb/cockroach/commits/c5714b6b8be8ac555ad3f4ae490c5b0b0c7cf295):

```
=== RUN   TestLogic_mixed_version_upgrade_preserve_ttl
    test_log_scope.go:171: test logs captured to: /artifacts/tmp/_tmp/210a1640ebc83bc17df545fd465448e8/logTestLogic_mixed_version_upgrade_preserve_ttl502623305
    test_log_scope.go:82: use -show-logs to present logs inline
    logic.go:3205: let $initial_version = 25.2
    logic.go:3143: 
         
        /home/roach/.cache/bazel/_bazel_roach/c5a4e7d36696d9cd970af2045211a7df/sandbox/processwrapper-sandbox/3636/execroot/com_github_cockroachdb_cockroach/bazel-out/aarch64-fastbuild/bin/pkg/sql/logictest/tests/cockroach-go-testserver-25.2/cockroach-go-testserver-25_2_test_/cockroach-go-testserver-25_2_test.runfiles/com_github_cockroachdb_cockroach/pkg/sql/logictest/testdata/logic_test/mixed_version_upgrade_preserve_ttl:19: SELECT version != '25.2' FROM [SHOW CLUSTER SETTING version]
        expected:
            true
            
        but found (query options: "retry") :
            false
            
[11:03:18] --- progress: /home/roach/.cache/bazel/_bazel_roach/c5a4e7d36696d9cd970af2045211a7df/sandbox/processwrapper-sandbox/3636/execroot/com_github_cockroachdb_cockroach/bazel-out/aarch64-fastbuild/bin/pkg/sql/logictest/tests/cockroach-go-testserver-25.2/cockroach-go-testserver-25_2_test_/cockroach-go-testserver-25_2_test.runfiles/com_github_cockroachdb_cockroach/pkg/sql/logictest/testdata/logic_test/mixed_version_upgrade_preserve_ttl: 2 statements
[11:03:18] --- done: /home/roach/.cache/bazel/_bazel_roach/c5a4e7d36696d9cd970af2045211a7df/sandbox/processwrapper-sandbox/3636/execroot/com_github_cockroachdb_cockroach/bazel-out/aarch64-fastbuild/bin/pkg/sql/logictest/tests/cockroach-go-testserver-25.2/cockroach-go-testserver-25_2_test_/cockroach-go-testserver-25_2_test.runfiles/com_github_cockroachdb_cockroach/pkg/sql/logictest/testdata/logic_test/mixed_version_upgrade_preserve_ttl with config cockroach-go-testserver-25.2: 2 tests, 1 failures
    logic.go:4494: 
        /home/roach/.cache/bazel/_bazel_roach/c5a4e7d36696d9cd970af2045211a7df/sandbox/processwrapper-sandbox/3636/execroot/com_github_cockroachdb_cockroach/bazel-out/aarch64-fastbuild/bin/pkg/sql/logictest/tests/cockroach-go-testserver-25.2/cockroach-go-testserver-25_2_test_/cockroach-go-testserver-25_2_test.runfiles/com_github_cockroachdb_cockroach/pkg/sql/logictest/testdata/logic_test/mixed_version_upgrade_preserve_ttl:24: error while processing
    logic.go:4494: /home/roach/.cache/bazel/_bazel_roach/c5a4e7d36696d9cd970af2045211a7df/sandbox/processwrapper-sandbox/3636/execroot/com_github_cockroachdb_cockroach/bazel-out/aarch64-fastbuild/bin/pkg/sql/logictest/tests/cockroach-go-testserver-25.2/cockroach-go-testserver-25_2_test_/cockroach-go-testserver-25_2_test.runfiles/com_github_cockroachdb_cockroach/pkg/sql/logictest/testdata/logic_test/mixed_version_upgrade_preserve_ttl:24: too many errors encountered, skipping the rest of the input
cockroach logs captured in: /artifacts/tmp/_tmp/210a1640ebc83bc17df545fd465448e8/cockroach-logs853003522
    panic.go:635: -- test log scope end --
test logs left over in: /artifacts/tmp/_tmp/210a1640ebc83bc17df545fd465448e8/logTestLogic_mixed_version_upgrade_preserve_ttl502623305
--- FAIL: TestLogic_mixed_version_upgrade_preserve_ttl (93.71s)
```
<details><summary>Help</summary>
<p>

See also: [How To Investigate a Go Test Failure \(internal\)](https://cockroachlabs.atlassian.net/l/c/HgfXfJgM)
</p>
</details>
/cc @cockroachdb/sql-foundations
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*TestLogic_mixed_version_upgrade_preserve_ttl.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/bazci/githubpost/issues)

</sub>

Jira issue: CRDB-55252

### PR DESCRIPTION
**Pull request by bghal**
In local 3-node testing the upgrade takes ~80s to get to the cluster
version bump so relaxing the retries helps the tests pass.

Epic: none
Fixes: #154550
Fixes: #154077
Fixes: #155046

Release note: None

### CODE REVIEW

File: pkg/server/auto_upgrade.go [hunk 1]
```diff
@@ -26,7 +26,7 @@ func (s *topLevelServer) startAttemptUpgrade(ctx context.Context) error {
 		defer cancel()
 
 		retryOpts := retry.Options{
-			InitialBackoff: time.Second,
+			InitialBackoff: 5 * time.Second,
```
Comment (rafiss) [inline pkg/server/auto_upgrade.go]: just checking -- do we actually want to change this value? this would affect real clusters, not just tests

**Review by rafiss — CHANGES_REQUESTED** [review]

File: pkg/server/auto_upgrade.go (hunk 1 above)
Comment (bghal) [reply pkg/server/auto_upgrade.go]: Don't think it really matters but don't think the initial backoff is useful as is.

**Review by rafiss — APPROVED** [review]
lgtm! gonna start the merge in order to prevent flakiness sooner

bors r+
