### PR TITLE
sql: fix a crash when an INSERT ON CONFLICT SET UPDATE uses the resul…

### LINKED ISSUE #32473: sql: Panic when ON CONFLICT clause contains tuple assignment
Repro:
```
CREATE TABLE customers (                                                                                                            customer_id serial PRIMARY KEY,                                                                                                                           name VARCHAR UNIQUE,                                                                                                                                      email VARCHAR NOT NULL                                                                                                                                   );
insert into customers (name, email) values ('bob', 'bob@email.com') on conflict (name) do update set (name, email) = (select 'bob', 'otherbob@email.com');
```

EXPECTED: No panic, record should be inserted or updated.

ACUAL: Panic, with this callstack:
```
*
* ERROR: [n1,client=[::1]:62918,user=root] a SQL panic has occurred while executing "INSERT INTO customers(name, email) VALUES ('bob', 'bob@email.com') ON CONFLICT (name) DO UPDATE SET (name, email) = (SELECT 'bob', 'otherbob@email.com')": ReturnType called on TypedExpr with empty typeAnnotation. Was the underlying Expr type-checked before asserting a type of TypedExpr?
*
*
* ERROR: [n1,client=[::1]:62918,user=root] a panic has occurred!
*
panic while executing 1 statements: INSERT INTO _(_, _) VALUES (_, _) ON CONFLICT (_) DO UPDATE SET (_, _) = (SELECT _, _); caused by ReturnType called on TypedExpr with empty typeAnnotation. Was the underlying Expr type-checked before asserting a type of TypedExpr?

goroutine 332 [running]:
runtime/debug.Stack(0x6d540a0, 0xc4207764c0, 0x3)
	/usr/local/go/src/runtime/debug/stack.go:24 +0xa7
github.com/cockroachdb/cockroach/pkg/util/log.ReportPanic(0x6d540a0, 0xc4207764c0, 0xc4204e5980, 0x6638f00, 0xc425427800, 0x1)
	/Users/andy/go/src/github.com/cockroachdb/cockroach/pkg/util/log/crash_reporting.go:213 +0xa5
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).closeWrapper(0xc420605300, 0x6d540a0, 0xc4207764c0, 0x631e480, 0x6d14c10)
	/Users/andy/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:640 +0x2df
github.com/cockroachdb/cockroach/pkg/sql.(*Server).ServeConn.func1(0xc420605300, 0x6d540a0, 0xc4207764c0)
	/Users/andy/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:388 +0x61
panic(0x631e480, 0x6d14c10)
	/usr/local/go/src/runtime/panic.go:502 +0x229
github.com/cockroachdb/cockroach/pkg/sql/sem/tree.typeAnnotation.assertTyped(0x0, 0x0)
	/Users/andy/go/src/github.com/cockroachdb/cockroach/pkg/sql/sem/tree/expr.go:136 +0x4d
github.com/cockroachdb/cockroach/pkg/sql/sem/tree.typeAnnotation.ResolvedType(0x0, 0x0, 0xc420062a00, 0xc4254f8258)
	/Users/andy/go/src/github.com/cockroachdb/cockroach/pkg/sql/sem/tree/expr.go:130 +0x35
github.com/cockroachdb/cockroach/pkg/sql.(*planner).namesForExprs(0xc420605728, 0xc420522958, 0x1, 0x1, 0x6d54160, 0xc425427260, 0x1, 0x0, 0x0)
	/Users/andy/go/src/github.com/cockroachdb/cockroach/pkg/sql/update.go:829 +0x439
github.com/cockroachdb/cockroach/pkg/sql.(*planner).newUpsertNode(0xc420605728, 0x6d54160, 0xc425427260, 0xc4252a5090, 0xc4208ad180, 0xc4208ad180, 0xc425423500, 0x1, 0x1, 0x0, ...)
	/Users/andy/go/src/github.com/cockroachdb/cockroach/pkg/sql/upsert.go:129 +0x63f
github.com/cockroachdb/cockroach/pkg/sql.(*planner).Insert(0xc420605728, 0x6d54160, 0xc425427260, 0xc4252a5090, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/Users/andy/go/src/github.com/cockroachdb/cockroach/pkg/sql/insert.go:296 +0xdca
github.com/cockroachdb/cockroach/pkg/sql.(*planner).newPlan(0xc420605728, 0x6d54160, 0xc425427260, 0x6d57a60, 0xc4252a5090, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/Users/andy/go/src/github.com/cockroachdb/cockroach/pkg/sql/plan.go:817 +0x2b19
github.com/cockroachdb/cockroach/pkg/sql.(*planner).makePlan(0xc420605728, 0x6d54160, 0xc425427260, 0x6d57a60, 0xc4252a5090, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/Users/andy/go/src/github.com/cockroachdb/cockroach/pkg/sql/plan.go:307 +0x169
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).dispatchToExecutionEngine(0xc420605300, 0x6d54160, 0xc425427260, 0x6d57a60, 0xc4252a5090, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/Users/andy/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:786 +0xd99
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execStmtInOpenState(0xc420605300, 0x6d54160, 0xc425427260, 0x6d57a60, 0xc4252a5090, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/Users/andy/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:416 +0xe7a
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execStmt(0xc420605300, 0x6d54160, 0xc425427260, 0x6d57a60, 0xc4252a5090, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/Users/andy/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:99 +0x341
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).run(0xc420605300, 0x6d540a0, 0xc4207764c0, 0xc420d420d8, 0x5400, 0x15000, 0xc420d42170, 0xc4202e1790, 0x0, 0x0)
	/Users/andy/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:1113 +0x219b
github.com/cockroachdb/cockroach/pkg/sql.(*Server).ServeConn(0xc4209f01e0, 0x6d540a0, 0xc4207764c0, 0xc420605300, 0x5400, 0x15000, 0xc420d42170, 0xc4202e1790, 0x0, 0x0)
	/Users/andy/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:390 +0xce
github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*conn).serveImpl.func4(0xc4209f01e0, 0x6d540a0, 0xc4207764c0, 0xc420605300, 0x5400, 0x15000, 0xc420d42170, 0xc4202e1790, 0xc4202e17a0, 0xc42042c120)
	/Users/andy/go/src/github.com/cockroachdb/cockroach/pkg/sql/pgwire/conn.go:309 +0x81
created by github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*conn).serveImpl
	/Users/andy/go/src/github.com/cockroachdb/cockroach/pkg/sql/pgwire/conn.go:308 +0x107c
```

### PR DESCRIPTION
**Pull request by BramGruneir**
…ts of a subquery

The upsert path did not perform the subquery analysis so there was no typing
available for the subquery.

Note that only with the optimizer enabled does this correctly perform the
SET UPDATE path.

Fixes #32473.

Release note(bug fix): Fixed a crash that occurred when performing an INSERT ON
CONFLICT with a SET UPDATE that uses values from a subquery.

### CODE REVIEW

**Comment by BramGruneir** [comment]
Probably worth a backport to 2.1 as well.

File: pkg/sql/upsert.go [hunk 1]
```diff
@@ -126,7 +126,7 @@ func (p *planner) newUpsertNode(
 		// Determine which columns are updated by the RHS of INSERT
 		// ... ON CONFLICT DO UPDATE, or the non-PK columns in an
 		// UPSERT.
-		names, err := p.namesForExprs(updateExprs)
+		names, _, err := p.namesForExprs(ctx, updateExprs)
```
Comment (knz) [inline pkg/sql/upsert.go]: that's not the end of the story unfortunately... Either:

- you must the resulting setExprs in the same way UPDATE does. This is "interesting" because it requires the same "slot" machinery that was created for UPDATE by Justin.

- or, you can throw the towel and return a "not supported" error. I'd be fine with that -- we never supported subqueries in that place before.

I think the same problem exists with tuple assignments too (eg `ON CONFLICT DO UPDATE (a,b) = (c+d,e+f)` since the slot solution was intended to solve that problem too)

**Comment by BramGruneir** [comment]
Just a head's up that since this is from the Monday bugday work, new work is postponed until next Monday.

**Review by knz — APPROVED** [review]
LGTM - perhaps take the opportunity to add pgerror.NewErrorf in the refactored namesForExprs().

> Reviewed 5 of 5 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/33553#-:-LWDNUB0DXnkrX31Gqij:b12gies)* status: :shipit: complete! 0 of 0 LGTMs obtained

**Comment by BramGruneir** [comment]
Fixed the error codes.  Thanks for the help @knz!  

bors r+

**Comment by knz** [comment]
@BramGruneir this may need a backport.
