### PR TITLE
roachprod,roachtest: change default zones and cluster size for some tests

### LINKED ISSUE #90504: roachtest: unoptimized-query-oracle/disable-rules=all/seed-multi-region failed
roachtest.unoptimized-query-oracle/disable-rules=all/seed-multi-region [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/7070913?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/7070913?buildTab=artifacts#/unoptimized-query-oracle/disable-rules=all/seed-multi-region) on master @ [a3b578466bcdcc5d2bbea628d33c337d87b9f4b8](https://github.com/cockroachdb/cockroach/commits/a3b578466bcdcc5d2bbea628d33c337d87b9f4b8):

```
test artifacts and logs in: /artifacts/unoptimized-query-oracle/disable-rules=all/seed-multi-region/run_1
(test_runner.go:1062).teardownTest: test timed out (1h0m0s)
```
<p>Parameters: <code>ROACHTEST_cloud=gce</code>
, <code>ROACHTEST_cpu=4</code>
, <code>ROACHTEST_encrypted=false</code>
, <code>ROACHTEST_ssd=0</code>
</p>
<details><summary>Help</summary>
<p>

See: [roachtest README](https://github.com/cockroachdb/cockroach/blob/master/pkg/cmd/roachtest/README.md)

See: [How To Investigate \(internal\)](https://cockroachlabs.atlassian.net/l/c/SSSBr8c7)

</p>
</details>
/cc @cockroachdb/sql-queries
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*unoptimized-query-oracle/disable-rules=all/seed-multi-region.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)
</sub>

Jira issue: CRDB-20803

### PR DESCRIPTION
**Pull request by rytaft**
This commit updates the default zones used for roachprod clusters to include three different zones from three different regions.

This commit also changes the cluster size for the multi-region versions of `costfuzz` and `unoptimized-query-oracle` to 9, so that we won't get errors related to a fragile quorum and underreplicated ranges.

Fixes #90504

Release note: None

### CODE REVIEW

**Comment by rytaft** [comment]
Friendly ping @srosenberg @herkolategan @jlinder

**Review by srosenberg — APPROVED** [review]

File: pkg/roachprod/vm/gce/gcloud.go [hunk 1]
```diff
@@ -246,10 +246,18 @@ type ProjectsVal struct {
 
 // defaultZones is the list of  zones used by default for cluster creation.
 // If the geo flag is specified, nodes are distributed between zones.
+// These are GCP zones available according to this page:
+// https://cloud.google.com/compute/docs/regions-zones#available
 var defaultZones = []string{
 	"us-east1-b",
 	"us-west1-b",
 	"europe-west2-b",
+	"us-east1-c",
```
Comment (jlinder) [inline pkg/roachprod/vm/gce/gcloud.go:255]: How about listing the zones in alphabetical order? Or would that affect the order in which nodes are chosen and thus make node placement for clusters with <= 6 nodes not be well distributed?

**Review by jlinder — APPROVED** [review]
One thought. Good either way.

File: pkg/roachprod/vm/gce/gcloud.go (hunk 1 above)
Comment (srosenberg) [reply pkg/roachprod/vm/gce/gcloud.go:255]: When numNodes < numZones, `ZonePlacement` assigns the first `numNodes` (from `defaultZones`); otherwise, it assigns an equal number of zones (in the given order) modulo the remainder, if any. So, the order doesn't really matter except for highly unbalanced cases.

**Review by rytaft — COMMENTED** [review]
TFTRs!

bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/91244#-:-NGS2psm7hAH02AG7vCF:b-tlx7ko)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @herkolategan and @jlinder)

___
*[`pkg/roachprod/vm/gce/gcloud.go` line 255 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/91244#-NFzNYlRoLzOKDa0Kkd3-r1-255:-NGS2SWF-RmoB46r3XAX:b-qd15kw) ([raw file](https://github.com/cockroachdb/cockroach/blob/e8a458d52a1ad441995e293bf7f17d14aadf94ce/pkg/roachprod/vm/gce/gcloud.go#L255)):*
<details><summary><i>Previously, srosenberg (Stan Rosenberg) wrote…</i></summary><blockquote>

When numNodes < numZones, `ZonePlacement` assigns the first `numNodes` (from `defaultZones`); otherwise, it assigns an equal number of zones (in the given order) modulo the remainder, if any. So, the order doesn't really matter except for highly unbalanced cases.
</blockquote></details>

Yea, I'd rather keep it as-is if you don't mind since I want to make sure that tests with fewer than 9 nodes will still get zones spread across regions.
