### PR TITLE
try to resolve the deadlock between multiraft eventsChan and callbackChan and advance after ApplyConfChanges

### LINKED ISSUE #1185: MultiRaft can deadlock between sendEvent and attempting to write to callbackChan
From a clean master at the time of writing (@de153f0f619c9b837cbb4481dccbef44da34b80b):

- change the put test so that it leaves the cluster running when it's done (add `<-stopper`)
- TESTS=TestPut TESTTIMEOUT=24h TESTFLAGS="-d 65s" acceptance/run.sh
- wait until it's done
- check the status endpoints for the three nodes. for most runs, I get the following:
  - range descriptors indicate three (may vary slightly) ranges (via ./cockroach range ls on any of the nodes)
  - first and third node show those on the web frontend (well, they show "3" ranges)
  - second node has never split any ranges - it only shows one range (debugging shows that it's the initial range spanning everything)
  - stats indicate furthermore that that node doesn't hold any data (14 keys and handful more of values).

In my tests with a lot of debug statements (in particular for EndTransaction calls) I don't see any such calls logged after the replica changes. The node does however receive Put requests (though presumably not all of them), these fail because store.GetRange doesn't know anything but the old incorrect range 1 (""-"\xff\xff").

Something really weird is going on here; the node seems to be left out.

```
root@e2d00c9b91b3:/# du -sh data*
196M	data0
100K	data1
195M	data2
```

### PR DESCRIPTION
**Pull request by es-chow**
try to resolve the #1185 and make s.Multinode.Advance after ApplyConfChange.

Closes #1185.

### CODE REVIEW

File: multiraft/multiraft.go [hunk 1]
```diff
@@ -428,14 +436,18 @@ type state struct {
 	groups    map[proto.RangeID]*group
 	nodes     map[proto.RaftNodeID]*node
 	writeTask *writeTask
+	// buffer the event if s.Events channel is full to avoid the deadlock
+	// between s.Events channel and callbackChan.
+	pendingEvents []interface{}
```
Comment (bdarnell) [inline multiraft/multiraft.go]: We now have two kinds of buffers for events: this slice and the buffer in the channel itself. I don't think it makes sense to keep both. Make the `Events` channel unbuffered and only write to it in the select loop(s) (removing the EventBufferSize setting). In `sendEvent`, always append to the slice and don't touch the channel.

File: multiraft/multiraft.go [hunk 2]
```diff
@@ -568,8 +625,29 @@ func (s *state) start() {
 					s.coalescedHeartbeat()
 				}
 
-			case cb := <-s.callbackChan:
-				cb()
+			case eventsChan <- event:
+				// Send as many as possible events to eventsChan
```
Comment (bdarnell) [inline multiraft/multiraft.go]: Why do you have this extra loop? You could just set `s.pendingEvents = s.pendingEvents[1:]` and let the next event be sent on the next loop iteration.

File: multiraft/multiraft.go [hunk 3]
```diff
@@ -550,7 +571,43 @@ func (s *state) start() {
 
 				select {
 				case resp := <-s.writeTask.out:
-					s.handleWriteResponse(resp, writingGroups)
+					callbackCount := s.handleWriteResponse(resp, writingGroups)
+					// Wait till all callback returned and send buffered event if any.
```
Comment (bdarnell) [inline multiraft/multiraft.go]: We should try not to have too much stuff in the `start()` method. Either move this into `handleWriteResponse` or make a new `waitForCallbacks` method.

File: multiraft/multiraft.go [hunk 4]
```diff
@@ -550,7 +571,43 @@ func (s *state) start() {
...
+								if !drained {
+									s.pendingEvents = s.pendingEvents[sendIndex:]
+								}
+								break
+							}
+							select {
+							case <-s.stopper.ShouldStop():
+								return
+							case eventsChan <- event:
+								sendIndex++
```
Comment (bdarnell) [inline multiraft/multiraft.go]: If you set `s.pendingEvents = s.pendingEvents[1:]` after each event is sent, I think you can simplify this code by getting rid of the `draining` variable.

**Comment by bdarnell** [comment]
This generally looks good. I'm slightly concerned about blocking the whole select loop while we wait for callbacks to be processed, but fixing that is complicated so I'm willing to wait and see if it turns out to be a problem.

To answer your question from email (about why we need to wait for all callbacks before calling Advance): The callbacks call ApplyConfChange, which is what actually changes the raft configuration and the quorum used to commit future entries. If we call Advance before ApplyConfChange, then the next entries may try to commit using the old quorum configuration instead of the new one, so we may commit the entry before it is present on a majority of the new nodes.

File: multiraft/multiraft.go (hunk 1 above)
Comment (es-chow) [inline multiraft/multiraft.go]: I am not sure if we keep the buffer in the channel can help for performance as the channel filling will not depend on the select loop, so the event consuming goroutine in can keep busy if there is any event in the buffering channel.

File: multiraft/multiraft.go (hunk 3 above)
Comment (es-chow) [inline multiraft/multiraft.go]: can be done.

**Comment by es-chow** [comment]
The select loop blocking when waiting for callbacks to be processed only happens on the configuration change, the frequency of this kind of event should be low, so it may be acceptable.

If we want to ensure the quorum of configuration change, should we block the proposal (buffer it in `s.pending`) of the same groupID just after a `ChangeGroupMembership` is called? 

If we just ensure call Advance before ApplyConfChange, some proposal by `SubmitCommand` just follow  configuration change by `ChangeGroupMembership` may use the quorum of the old configuration to check for committing as the `AppResp` for those proposal can be received and checked by raft before the ConfChange applied.

File: multiraft/multiraft.go (hunk 1 above)
Comment (bdarnell) [inline multiraft/multiraft.go]: It will be a little faster to have the buffered channel, but how much faster? Most of the time the select loop should be idle, so it should be able to hand off the next event to the processing goroutine. I'm not convinced the channel buffer is worth the complexity, but I'm willing to be persuaded if you see a difference.

**Comment by bdarnell** [comment]
We don't need to block all proposals while a `ChangeGroupMembership` is pending. Between `ProposeConfChange` and `ApplyConfChange`, it's safe to use either the old or the new quorum, since the two are guaranteed to overlap. But as soon as the config change is applied, we must switch over to the new config.

File: multiraft/multiraft.go (hunk 1 above)
Comment (es-chow) [inline multiraft/multiraft.go]: fix this by make the channel unbuffered and the channel content is event slice.

**Comment by es-chow** [comment]
Make the channel as unbuffered and make the channel as event slice other than event, this idea taken from ready channel between multinode and multiraft. PTAL.

`make testrace` fail in `TestLeaderElectionEvent` as `maybeSendLeaderEvent` call `sendEvent` directly other than in `s.start()` loop. Have to find a way to resolve it.

Will try to resolve the block issue.

**Comment by es-chow** [comment]
try to resolve the block issue by block the proposal other than the select. PTAL.

File: multiraft/multiraft.go (hunk 1 above)
Comment (bdarnell) [inline multiraft/multiraft.go]: Cool, sending a slice of events is a good solution. Since the channel is unbuffered. I think we can just remove the comment here - there's no longer any question of "if the s.Events channel is full"

File: multiraft/multiraft.go [hunk 5]
```diff
@@ -428,14 +429,18 @@ type state struct {
...
 	return &state{
-		MultiRaft: m,
-		groups:    make(map[proto.RangeID]*group),
-		nodes:     make(map[proto.RaftNodeID]*node),
-		writeTask: newWriteTask(m.Storage),
+		MultiRaft:     m,
+		groups:        make(map[proto.RangeID]*group),
+		nodes:         make(map[proto.RaftNodeID]*node),
+		writeTask:     newWriteTask(m.Storage),
+		pendingEvents: make([]interface{}, 0),
```
Comment (bdarnell) [inline multiraft/multiraft.go]: Remove this line - `nil` is a valid empty slice; there's no reason to use `make(slice, 0)`. You can also replace this expression with `nil` when you reset `pendingEvents` in the select loop.

File: multiraft/multiraft.go [hunk 6]
```diff
@@ -551,6 +563,12 @@ func (s *state) start() {
 				select {
 				case resp := <-s.writeTask.out:
 					s.handleWriteResponse(resp, writingGroups)
+					// Try to send events
+					select {
```
Comment (bdarnell) [inline multiraft/multiraft.go]: Does this need to be here? I don't think it'll be any faster than just letting the next iteration of the main loop send it.

If we do keep this, it needs to be consistent with the main loop's version (including the `log.V(8)` message), so that log line and the clearing of `s.pendingEvents` should be factored out into a separate method.

File: multiraft/multiraft.go [hunk 7]
```diff
@@ -921,6 +953,7 @@ func (s *state) processCommittedEntry(groupID proto.RangeID, g *group, entry raf
 					// redundant since most pending proposals won't benefit from this but
 					// config changes should be rare enough (and the size of the pending queue
 					// small enough) that it doesn't really matter.
```
Comment (bdarnell) [inline multiraft/multiraft.go]: This comment is no longer accurate; replace it with "Re-submit all pending proposals that were held while the config change was pending".

**Comment by bdarnell** [comment]
LGTM

**Comment by es-chow** [comment]
updated as per comments.

@bdarnell, do you have any idea on how to fix the `make testrace` failure? The test case `TestLeaderElectionEvent` call `maybeSendLeaderEvent` API directly other than in s.start(), so it cause a  data race.

**Comment by bdarnell** [comment]
It's a little dirty, but you could use the `callbackChan` to get on the right goroutine:
```
s.callbackChan <- func() {
  s.maybeSendLeaderEvent(...)
}
```

**Comment by es-chow** [comment]
Thanks ben. Updated and rebased.

**Comment by bdarnell** [comment]
LGTM
