### PR TITLE
roachtest: fix `roachprod create` runs more than `maxAttempts` times

### LINKED ISSUE #72514: roachtest: cluster creation only gives up after `maxAttempts+2` attempts
`roachtest` should make at most `maxAttempts` attempts to create a roachprod cluster before giving up. In its current state, it makes `maxAttempts+2` attempts.

**To Reproduce**

1. Add any changes that will cause `roachprod create` to fail such as hardcoding cluster name to an invalid name ("a.b-test")
2. Run any `roachtest` and observe it making 5 attempts instead of 3

### PR DESCRIPTION
**Pull request by healthy-pod**
Previously, roachtest made `maxAttempts+2` attempts before
giving up.

This patch changes that to run at most `maxAttempts` attempts.

Release note: None

Fixes #72514

### CODE REVIEW

**Review by stevendanna — APPROVED** [review]
LGTM.  I imagine most times we've failed 3 times in a row, we are going to keep failing.

File: pkg/cmd/roachtest/cluster.go [hunk 1]
```diff
@@ -898,7 +899,7 @@ func (f *clusterFactory) newCluster(
 		// (when selecting the test) it's the best we can do for now.
 		c.destroyState.alloc = nil
 		c.Destroy(ctx, closeLogger, l)
-		if i > maxAttempts {
+		if i == maxAttempts {
```
Comment (rail) [inline pkg/cmd/roachtest/cluster.go:902]: A nit: using `>=` here would make me less paranoid :D

**Review by rail — APPROVED** [review]

**Comment by healthy-pod** [comment]
bors r=[stevendanna,rail]
