### PR TITLE
sql: fix rename temporary table bug

### LINKED ISSUE #48233: sql: rename on temporary table promotes it to a persistent table
To repro, create a temporary table, and then rename it. Then, look into system.namespace, and you'll see that the namespace entry for the table has been changed to be moved into the public schema.

A side effect of this is that name collisions between two temporary tables in rename are not detected correctly.

### PR DESCRIPTION
**Pull request by arulajmani**
Previously, when a temporary table was renamed, it was moved out of the
temp schema and into the `public` schema, thus making it a persistent
table. This patch fixes that.

Additionally, we also disallow a user from explicitly moving a temp
table into the `public` schema by providing a FQN during rename. This
is more in line with PG, which doesn't allow changing schemas during
rename.

Fixes #48233

peer programmed w @otan

Release note (bug fix): Renaming a temporary table no longer converts
it to a persistent table -- the table continues to remain temporary
after a rename. Moreover, this patch disallows users to convert a
temp table to a persistent table by renaming using an fully qualified
name with the schema reffering to `public`.

### CODE REVIEW

File: pkg/sql/logictest/testdata/logic_test/temp_table [hunk 1]
```diff
@@ -241,3 +241,21 @@ query I
 SELECT * FROM regression_47030
 ----
 2
+
```
Comment (otan) [inline pkg/sql/logictest/testdata/logic_test/temp_table:244]: nit: extra \n

File: pkg/sql/logictest/testdata/logic_test/temp_table [hunk 2]
```diff
@@ -241,3 +241,21 @@ query I
...
+statement ok
+ALTER TABLE regression_48233 RENAME TO reg_48233
+
+query IITI rowsort
+SELECT * FROM system.namespace WHERE name LIKE '%48233'
+----
+50  65  reg_48233  79
+
+statement error cannot convert a temporary table to a persistent table during rename
```
Comment (otan) [inline pkg/sql/logictest/testdata/logic_test/temp_table:260]: nit: during renames

File: pkg/sql/logictest/testdata/logic_test/temp_table [hunk 3]
```diff
@@ -241,3 +241,21 @@ query I
...
+ALTER TABLE reg_48233 RENAME TO public.reg_48233
```
Comment (otan) [inline pkg/sql/logictest/testdata/logic_test/temp_table:261]: can you also test conversion of public schema to temp schema?

**Review by arulajmani — COMMENTED** [review]
Thanks for the quick review :) 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/50500#-:-MASh-z07gDjnE5c-xMr:bky99xw)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @otan and @solongordon)

___
*[pkg/sql/logictest/testdata/logic_test/temp_table, line 261 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/50500#-MASdtJYP__a8qr3it2h-r1-261:-MASfQIy9HaB0yO2eqJt:b6sdxfm) ([raw file](https://github.com/cockroachdb/cockroach/blob/62a75f7ab751793c9b9de2370dcdb27e7ec37e6a/pkg/sql/logictest/testdata/logic_test/temp_table#L261)):*
<details><summary><i>Previously, otan (Oliver Tan) wrote…</i></summary><blockquote>

can you also test conversion of public schema to temp schema?
</blockquote></details>

Good call. That error is caught in the optimizer currently -- we are not allowed to plan a rename into a schema that isn't public. When we support other physical schemas, I'm assuming that error will go away, and therefore this test will fail. 

I think adding a test that fails in that situation will serve as a reminder to tackle this case when we have other physical schemas. (If it isn't handled already by disallowing moving between schemas during a rename)

File: pkg/sql/rename_table.go [hunk 4]
```diff
@@ -105,6 +107,13 @@ func (n *renameTableNode) startExec(params runParams) error {
 		return err
 	}
 
+	if newTn.ExplicitSchema && newTn.Schema() == tree.PublicSchema && tableDesc.Temporary {
```
Comment (rohany) [inline pkg/sql/rename_table.go:110]: We are going to add user defined schemas, so let's be proactive and check if the new schema isn't the temporary schema.

**Review by arulajmani — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/50500)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @otan, @rohany, and @solongordon)

___
*[pkg/sql/rename_table.go, line 110 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/50500#-MASdtJYP__a8qr3it2i-r2-110:-MASpomt5kb3hj2ZovoY:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/8f9189fcd91d855824e1b654ea2830660034ad03/pkg/sql/rename_table.go#L110)):*
<details><summary><i>Previously, rohany (Rohan Yadav) wrote…</i></summary><blockquote>

We are going to add user defined schemas, so let's be proactive and check if the new schema isn't the temporary schema.
</blockquote></details>

Done.

File: pkg/storage/enginepb/mvcc3.pb.go [hunk 5]
```diff
@@ -4207,7 +4207,9 @@ var (
 	ErrIntOverflowMvcc3   = fmt.Errorf("proto: integer overflow")
 )
 
-func init() { proto.RegisterFile("storage/enginepb/mvcc3.proto", fileDescriptor_mvcc3_9bc532bf92053320) }
+func init() {
```
Comment (otan) [inline pkg/storage/enginepb/mvcc3.pb.go]: revert these

File: pkg/sql/logictest/testdata/logic_test/temp_table [hunk 6]
```diff
@@ -241,3 +241,26 @@ query I
...
+----
+50  65  reg_48233  79
+
+statement error cannot convert a temporary table to a persistent table during renames
+ALTER TABLE reg_48233 RENAME TO public.reg_48233
+
+statement ok
+CREATE TABLE persistent_48233(a int)
+
+statement error schema cannot be modified: "pg_temp"
```
Comment (otan) [inline pkg/sql/logictest/testdata/logic_test/temp_table:265]: this isn't a great error message, but ok for this PR.

looks like the earlier code stops us from triggering this code path based on https://github.com/cockroachdb/cockroach/blob/c7fadb7dd88addaea0d7677aabd3f45b71cf7fbb/pkg/sql/catalog/resolver/resolver.go#L219... i'm starting to think we should actually fix this by changing the sql.y to only take in one table name, as postgres treats `schema_name.table_name` as a syntax error. we can do that in a separate PR as we should backport this to 20.1. 

schema changes should use the `SET SCHEMA` syntax instead. feel free to file a ticket.

i think we can delete the
```
isNewSchemaTemp, _, err := temporarySchemaSessionID(newTn.Schema())
	if err != nil {
		return err
	}

	if newTn.ExplicitSchema && !isNewSchemaTemp && tableDesc.Temporary {
		return pgerror.New(
			pgcode.FeatureNotSupported,
			"cannot convert a temporary table to a persistent table during renames",
		)
	}
```
block if we use the SET SCHEMA syntax and only let this take in a table name.

Comment (rohany) [reply pkg/sql/logictest/testdata/logic_test/temp_table:265]: It's probably better to go down this route, but it could break existing scripts. Agreed, rename table shouldn't have ever taken a qualification...

**Review by arulajmani — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/50500)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @otan, @rohany, and @solongordon)

___
*[pkg/sql/logictest/testdata/logic_test/temp_table, line 265 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/50500#-MASdtJYP__a8qr3it2h-r3-265:-MASugzn16fMrD32W7HA:b-2d1mx1) ([raw file](https://github.com/cockroachdb/cockroach/blob/c4cb97bf9aa0f520b548e0b0fe0228ef86a2f63a/pkg/sql/logictest/testdata/logic_test/temp_table#L265)):*
<details><summary><i>Previously, rohany (Rohan Yadav) wrote…</i></summary><blockquote>

It's probably better to go down this route, but it could break existing scripts. Agreed, rename table shouldn't have ever taken a qualification...
</blockquote></details>

I agree with both of you and echo the same reservations about breaking existing behavior.

 My gut is that this is ok for this PR, as it fixes the issue, and the reanaming conversation can be had in a bigger context of user defined schemas. If it is decided that we disallow qualified names during a rename, this test fails and serves as a nod to remove this code block. Let me know what yall think!

**Review by otan — APPROVED** [review]

**Comment by arulajmani** [comment]
bors r=otan
