### PR TITLE
sql/stats: support partial stats over indexes implied by the filter

### LINKED ISSUE #154891: sql/stats: support partial statistics over implied partial indexes
We currently only support partial statistics with a `WHERE` clause when the predicate fully constrains the first column of a non-partial index. We should also allow partial stats collections over partial indexes that are implied by the `WHERE` clause, such as:

```
CREATE TABLE t (
    a INT,
    INDEX idx_partial (a) WHERE a > 5
);

# Error: table t does not contain a non-partial forward index with a as a prefix column
CREATE STATISTICS pstat ON a FROM t WHERE a > 7;
```

Jira issue: CRDB-55181

### PR DESCRIPTION
**Pull request by Uzair5162**
This commit adds support to collect arbitrary partial statistics when a partial index with a predicate implied by the stat collection's filters exists.

Fixes: #154891

Release note (sql change): Added support for collecting partial statistics when the given `WHERE` clause implies the predicate of a partial index with the requested column as the first key column. For example:

```
CREATE TABLE t (a INT, INDEX idx_partial (a) WHERE a > 5);
CREATE STATISTICS pstat ON a FROM t WHERE a > 7;
```

### CODE REVIEW

File: pkg/sql/opt/optbuilder/misc_statements.go [hunk 1]
```diff
@@ -265,17 +266,36 @@ func (b *Builder) buildWhereForStatistics(
...
-		if _, isPartial := idx.Predicate(); isPartial || idx.Type() != idxtype.FORWARD {
+		if idx.Type() != idxtype.FORWARD {
 			continue
 		}
+
+		// If this is a partial index, check if the filter implies its predicate.
+		if pred, isPartialIndex := tabMeta.PartialIndexPredicate(i); isPartialIndex {
+			predFilters := *pred.(*memo.FiltersExpr)
+			var computedCols map[opt.ColumnID]opt.ScalarExpr
+			if b.evalCtx.SessionData().OptimizerProveImplicationWithVirtualComputedColumns {
```
Comment (mgartner) [inline pkg/sql/opt/optbuilder/misc_statements.go]: This setting was added so that this PR could be backported without changing the default behavior: https://github.com/cockroachdb/cockroach/pull/123163

I don't really think we need to respect it for `CREATE STATISTICS`, so maybe remove it. If you're convinced we need it, we should have tests for it.

**Review by mgartner — APPROVED** [review]
Nice! LGTM, just one suggestion.

**Review by michae2 — APPROVED** [review]
:lgtm: Very nice!

> @michae2 reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/154892#-:-ObZywIDEnaVo3GLckxC:b-kerl87)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @michae2 and @Uzair5162)

___
*[`pkg/sql/opt/optbuilder/misc_statements.go` line 301 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/154892#-ObZsuRZ0udzBcxhzZqQ:-ObZsuRZ0udzBcxhzZqR:bqu12si) ([raw file](https://github.com/cockroachdb/cockroach/blob/a4e5147ea65d302fe8a08cd39bfbfe0b320f61a8/pkg/sql/opt/optbuilder/misc_statements.go#L301)):*
> ```Go
> 		if idx.KeyColumnCount() > 0 {
> 			col := idx.Column(0)
> 			if tabID.IndexColumnID(idx, 0) == filterColID {
> ```

comment: If the filter is identical to the partial index predicate, we can do a full scan of the partial index, and in that case the column doesn't have to be the first in the index. (But we don't need to support this initially.)
___
*[`pkg/sql/opt/optbuilder/misc_statements.go` line 327 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/154892#-ObZtO7u145SIgnWkmTv:-ObZtO7u145SIgnWkmTw:brofh58) ([raw file](https://github.com/cockroachdb/cockroach/blob/a4e5147ea65d302fe8a08cd39bfbfe0b320f61a8/pkg/sql/opt/optbuilder/misc_statements.go#L327)):*
> ```Go
> 
> 	var ic idxconstraint.Instance
> 	// TODO(uzair): Pass in optionalFilters here to produce a better constraint.
> ```

idea: Should the partial index predicate be included as an optionalFilter?

(I'm thinking about a case like:

```
CREATE TABLE a (a INT, INDEX (a) WHERE a % 2 = 0);
CREATE STATISTICS stats ON a FROM a WHERE a % 2 = 0 AND a >= 6 AND a < 10;
```

which seems like it might be possible if we include the partial index predicate as an optionalFilter... hmm, though I suppose we wouldn't be able to merge such a partial stat into the histogram, so maybe it's moot...)

File: pkg/sql/opt/optbuilder/misc_statements.go (hunk 1 above)
Comment (Uzair5162) [reply pkg/sql/opt/optbuilder/misc_statements.go]: Done, removed.

**Review by Uzair5162 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/154892)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @mgartner and @michae2)

___
*[`pkg/sql/opt/optbuilder/misc_statements.go` line 327 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/154892#-ObZtO7u145SIgnWkmTv:-ObhFpiW0lBxjKkPHOeC:beu14r8) ([raw file](https://github.com/cockroachdb/cockroach/blob/a4e5147ea65d302fe8a08cd39bfbfe0b320f61a8/pkg/sql/opt/optbuilder/misc_statements.go#L327)):*
<details><summary><i>Previously, michae2 (Michael Erickson) wrote…</i></summary><blockquote>

idea: Should the partial index predicate be included as an optionalFilter?

(I'm thinking about a case like:

```
CREATE TABLE a (a INT, INDEX (a) WHERE a % 2 = 0);
CREATE STATISTICS stats ON a FROM a WHERE a % 2 = 0 AND a >= 6 AND a < 10;
```

which seems like it might be possible if we include the partial index predicate as an optionalFilter... hmm, though I suppose we wouldn't be able to merge such a partial stat into the histogram, so maybe it's moot...)
</blockquote></details>

Yeah, something like this is tricky with merging but I like the idea. This example would produce a single span [/6 - /9] if we included the partial index predicate as an optionalFilter, which we could technically merge since it's a single span, but we'd need to still consider the index predicate somehow.

**Review by michae2 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/154892)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @mgartner and @Uzair5162)

___
*[`pkg/sql/opt/optbuilder/misc_statements.go` line 327 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/154892#-ObZtO7u145SIgnWkmTv:-ObiAQC5DxH63jwtRSs8:bd96u93) ([raw file](https://github.com/cockroachdb/cockroach/blob/a4e5147ea65d302fe8a08cd39bfbfe0b320f61a8/pkg/sql/opt/optbuilder/misc_statements.go#L327)):*
<details><summary><i>Previously, Uzair5162 (Uzair Ahmad) wrote…</i></summary><blockquote>

Yeah, something like this is tricky with merging but I like the idea. This example would produce a single span [/6 - /9] if we included the partial index predicate as an optionalFilter, which we could technically merge since it's a single span, but we'd need to still consider the index predicate somehow.
</blockquote></details>

Hmm right. This actually makes me think we should add a negative testcase like:

```
CREATE TABLE ab (a INT PRIMARY KEY, b INT, INDEX (b) WHERE b > 1 AND b % 2 = 0) WITH (sql_stats_automatic_collection_enabled = false);
INSERT INTO ab VALUES (1, 1), (2, 2);
CREATE STATISTICS fstat FROM ab;
INSERT INTO ab VALUES (3, 3), (4, 4), (5, 5), (6, 6);
CREATE STATISTICS pstat ON b FROM ab WHERE b > 1 AND b % 2 = 0;
SHOW STATISTICS FOR TABLE ab;
```

which should show that we aren't allowed to create pstat because it can't safely be merged.

**Review by Uzair5162 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/154892)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @mgartner and @michae2)

___
*[`pkg/sql/opt/optbuilder/misc_statements.go` line 327 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/154892#-ObZtO7u145SIgnWkmTv:-ObiXwjYE32_IW32eQ_I:btokius) ([raw file](https://github.com/cockroachdb/cockroach/blob/a4e5147ea65d302fe8a08cd39bfbfe0b320f61a8/pkg/sql/opt/optbuilder/misc_statements.go#L327)):*
<details><summary><i>Previously, michae2 (Michael Erickson) wrote…</i></summary><blockquote>

Hmm right. This actually makes me think we should add a negative testcase like:

```
CREATE TABLE ab (a INT PRIMARY KEY, b INT, INDEX (b) WHERE b > 1 AND b % 2 = 0) WITH (sql_stats_automatic_collection_enabled = false);
INSERT INTO ab VALUES (1, 1), (2, 2);
CREATE STATISTICS fstat FROM ab;
INSERT INTO ab VALUES (3, 3), (4, 4), (5, 5), (6, 6);
CREATE STATISTICS pstat ON b FROM ab WHERE b > 1 AND b % 2 = 0;
SHOW STATISTICS FOR TABLE ab;
```

which should show that we aren't allowed to create pstat because it can't safely be merged.
</blockquote></details>

Good idea, I've added a test for this.

**Review by michae2 — APPROVED** [review]
Very nice!
