### PR TITLE
roachtest: fix mixedversion context in startup functions

### LINKED ISSUE #125749: roachtest: sql-stats/mixed-version failed
roachtest.sql-stats/mixed-version [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyAwsBazel/15681889?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyAwsBazel/15681889?buildTab=artifacts#/sql-stats/mixed-version) on master @ [3aa5bdf40527e2f60b179094403b4302a1c2cbe1](https://github.com/cockroachdb/cockroach/commits/3aa5bdf40527e2f60b179094403b4302a1c2cbe1):

```
(mixedversion.go:612).Run: mixed-version test failure while running step 18 (set cluster setting "storage.ingest_split.enabled" to false on system tenant): panic (stack trace above): invalid argument to Intn [owner=test-eng]
test artifacts and logs in: /artifacts/sql-stats/mixed-version/cpu_arch=arm64/run_1
```

Parameters:
 - <code>ROACHTEST_arch=arm64</code>
 - <code>ROACHTEST_cloud=aws</code>
 - <code>ROACHTEST_coverageBuild=false</code>
 - <code>ROACHTEST_cpu=4</code>
 - <code>ROACHTEST_encrypted=false</code>
 - <code>ROACHTEST_fs=ext4</code>
 - <code>ROACHTEST_localSSD=true</code>
 - <code>ROACHTEST_metamorphicBuild=false</code>
 - <code>ROACHTEST_ssd=0</code>
<details><summary>Help</summary>
<p>

See: [roachtest README](https://github.com/cockroachdb/cockroach/blob/master/pkg/cmd/roachtest/README.md)

See: [How To Investigate \(internal\)](https://cockroachlabs.atlassian.net/l/c/SSSBr8c7)

_Grafana is not yet available for aws clusters_</p>
</details>
/cc @cockroachdb/test-eng
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*sql-stats/mixed-version.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/bazci/githubpost/issues)
</sub>

Jira issue: CRDB-39590

### PR DESCRIPTION
**Pull request by renatolabs**
Previously, the context assigned to startup functions (`OnStartup`) always had the `FromVersion` and `ToVersion` fields assigned to the very first and last versions in the upgrade test, respectively. This is because the concept of "from" and "to" versions are less well defined for these functions -- they run *before* the upgrades being tested happen, not during.

However, this can have undesired consequences. Specifically, if:

- the test introduced "setup upgrades" (i.e., upgrades that happen using unsupported versions of cockroachdb where user hooks do not run); **and**
- a mutator decides to insert a step relative to a startup step

then, the step added by the mutator will have an inaccurate view of the binaries running on each node -- they would think every node is running the very first version in the upgrade path, when in reality the "setup upgrades" had already finished by that point.

This commit updates the context passed to startup functions so that they know the actual binary versions running on the nodes by the time they run (via `FromVersion`).

Fixes: #125749

Release note: None

### CODE REVIEW

File: pkg/cmd/roachtest/roachtestutil/mixedversion/planner.go [hunk 1]
```diff
@@ -260,9 +260,14 @@ func (p *testPlanner) Plan() *TestPlan {
 		}
 	}
 
+	// Use first tested upgrade version in the context passed to startup
+	// functions; the setup upgrades that happened before should be
+	// invisible to them.
+	firstTestedUpgradeVersion := testUpgrades[0].from
```
Comment (nameisbhaskar) [inline pkg/cmd/roachtest/roachtestutil/mixedversion/planner.go:266]: I am just trying to understand that there is no possibility of the length of testUpgrades to be 0 because the latest versions have webhooks?

Comment (renatolabs) [reply pkg/cmd/roachtest/roachtestutil/mixedversion/planner.go:266]: `testUpgrades` would be empty if the test's `minimumSupportedVersion` corresponds to a cluster version less than or equal to the the final build (i.e., the release where the test is running).

We validate[^1] that the minimum supported version is at least one release series older than the current build, so `testUpgrades` should never be empty.

[^1]: https://github.com/cockroachdb/cockroach/blob/8455f1b6714329fc2d7d2b57621b83d71c0e6578/pkg/cmd/roachtest/roachtestutil/mixedversion/mixedversion.go#L942-L957

**Review by nameisbhaskar — APPROVED** [review]
Thanks @renatolabs for the clarification! LGTM!

**Review by DarrylWong — APPROVED** [review]
>the test introduced "setup upgrades" (i.e., upgrades that happen using unsupported versions of cockroachdb where user hooks do not run); and

Oh interesting, so when a mvt  specifies`MinimumSupportedVersion()`, it's actually just upgrading until it hits that version?  Is there additional coverage gained by doing this or was it just easier to implement this way?

**Comment by renatolabs** [comment]
> it's actually just upgrading until it hits that version?

Yes, the test will perform between `MinUpgrades` and `MaxUpgrades`. If there are versions in the chosen upgrade path that are older than the test's min supported version, the upgrades will happen, but the user functions won't run.

>  Is there additional coverage gained by doing this or was it just easier to implement this way?

What we're trying to verify with this logic is that functionality (and crucially, upgrade logic) works regardless of whether the cluster was bootstrapped at a certain version, or upgraded to that same version from an older release. We've had some bugs in the past where the state of the DB (especially internal tables) is different in those two scenarios (we actually have a very recent example: #125702).

*****

Mixed-version tests [passed](https://teamcity.cockroachdb.com/viewLog.html?buildId=15700641&buildTypeId=Cockroach_Nightlies_RoachtestNightlyGceBazel) on this branch.

TFTRs!

bors r=nameisbhaskar,DarrylWong

**Comment by renatolabs** [comment]
bors retry
