### PR TITLE
sql/schemachanger: ensure CREATE TABLE/VIEW attempts to use the DSC

### LINKED ISSUE #147657: sql/schemachanger: CREATE TABLE not implemented in DSC but still runs with unsafe_always
**Describe the problem**

`CREATE TABLE` is not implemented in the Declarative Schema Changer and thus when we 
`set use_declarative_schema_changer=unsafe_always` the command should fail.

However with these repro steps we can see that the command still runs:
```
demo@127.0.0.1:26257/demoapp/movr> set use_declarative_schema_changer=unsafe_always;                                                                                                                                             
SET

Time: 1ms total (execution 1ms / network 0ms)

demo@127.0.0.1:26257/demoapp/movr> explain (ddl) create table test_table(log int);                                                                                                                                               
ERROR: cannot explain a statement which is not supported by the declarative schema changer
SQLSTATE: 0A000
demo@127.0.0.1:26257/demoapp/movr> create table test_table(log int);                                                                                                                                                             
CREATE TABLE

Time: 8ms total (execution 3ms / network 5ms)

```

Jira issue: CRDB-51180

Epic CRDB-25312

### PR DESCRIPTION
**Pull request by fqazi**
Previously, these statements bypassed the declarative schema changer (DSC) checks entirely because the optimizer directly generated the plan nodes for these statements. To address this, the optimizer will attempt to generate the plan nodes via the declarative schema changer first, then use the legacy schema changer. These are all unimplemented, but this ensures correctness for the unsafe_always option.

Fixes: #147657
Release note: None

### CODE REVIEW

**Review by eric-alton — APPROVED** [review]
:lgtm:

> @eric-alton reviewed 5 files and all commit messages, and made 1 comment.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/166430#-:-OoQarjm-zKynAV6gICv:bnfp4nl)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on michae2).

File: pkg/sql/opt_exec_factory.go [hunk 1]
```diff
@@ -2065,6 +2082,14 @@ func (ef *execFactory) ConstructCreateView(
 		return nil, err
 	}
 
+	plan, err := ef.planner.SchemaChange(ef.ctx, createView)
```
Comment (rafiss) [inline pkg/sql/opt_exec_factory.go:2080]: nit: we could move `toPlanDependencies` to be after this call, since we don't need `planDeps` if this gives us the `plan` already.

**Review by rafiss — APPROVED** [review]

**Comment by fqazi** [comment]
Needs a rebase and updates to rttanalysis
