### PR TITLE
sql: don't panic on $0 parameters

### LINKED ISSUE #5375: panic (index out of range) on incorrect parameter
Using Go and the cockroachdb/pg driver, if you use $0 as a parameter it crashes the database server.

e.g.

```
db.Exec(`INSERT INTO person(name, email) VALUES($0, $1)`, name, email)
```

```
panic: runtime error: index out of range

goroutine 37179 [running]:
panic(0x1636820, 0xc82000e090)
        /usr/local/go/src/runtime/panic.go:464 +0x3e6
github.com/cockroachdb/cockroach/sql/pgwire.(*v3Conn).handleParse(0xc820318000, 0xc820318028, 0x0, 0x0)
        /usr/local/gopath/src/github.com/cockroachdb/cockroach/sql/pgwire/v3.go:349 +0xf65
github.com/cockroachdb/cockroach/sql/pgwire.(*v3Conn).serve(0xc820318000, 0x0, 0x0, 0x0)
        /usr/local/gopath/src/github.com/cockroachdb/cockroach/sql/pgwire/v3.go:251 +0xf1b
github.com/cockroachdb/cockroach/sql/pgwire.(*Server).ServeConn(0xc820333a58, 0x7ff1e708d578, 0xc82019e580, 0x0, 0x0)
        /usr/local/gopath/src/github.com/cockroachdb/cockroach/sql/pgwire/server.go:161 +0xb0b
github.com/cockroachdb/cockroach/server.(*Server).Start.func4.1(0x7ff1e708d578, 0xc82019e580)
        /usr/local/gopath/src/github.com/cockroachdb/cockroach/server/server.go:292 +0x4b
github.com/cockroachdb/cockroach/util.ServeHandler.func3.1(0xc82014c080, 0x7ff1e708d578, 0xc82019e580, 0xc8202b6020)
        /usr/local/gopath/src/github.com/cockroachdb/cockroach/util/net.go:123 +0x5a
created by github.com/cockroachdb/cockroach/util.ServeHandler.func3
        /usr/local/gopath/src/github.com/cockroachdb/cockroach/util/net.go:125 +0x31f

```

### PR DESCRIPTION
**Pull request by petermattis**
Fixes #5375.

---

This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/5378)

### CODE REVIEW

**Comment by tamird** [comment]
I think this error message better than #5377's since $0 is never valid.

**Comment by tamird** [comment]
LGTM

**Comment by dt** [comment]
heh, I checked and postgres says `pq: there is no parameter $0`

**Comment by petermattis** [comment]
@dt I like `invalid parameter: $0` better. Do you think we need to be compatible with postgres error messages?

**Comment by tamird** [comment]
Ah, this is all at prepare-time. OK, seems like we should use postgres' message. I was confused because #5377 combined the check with another unrelated check.

**Comment by petermattis** [comment]
@tamird Is compatibility with postgres error messages important?

**Comment by dt** [comment]
considering we don't (currently) even match their error codes, I can't imagine the exact strings matter that much?

**Comment by tamird** [comment]
Probably not, but in cases like this where there's no clear reason to be incompatible, why not match them?

**Comment by dt** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/5378#-:-KD9MnBxMUBOOVDydg5z:1417088721)*

**Comment by petermattis** [comment]
Heh, guess I don't really care. Switched to the postgres error message.

File: sql/pgwire/v3.go [hunk 1]
```diff
@@ -337,12 +337,12 @@ func (c *v3Conn) handleParse(buf *readBuffer) error {
...
 		if err != nil {
-			return c.sendError(fmt.Sprintf("non-integer parameter name: %s", k))
+			return c.sendError(fmt.Sprintf("non-integer parameter: %s", k))
 		}
 		// ValArgs are 1-indexed, pq.inTypes are 0-indexed.
 		i--
-		if len(pq.inTypes) <= i {
-			return c.sendError("internal error: leftover valargs")
+		if i < 0 || len(pq.inTypes) <= i {
+			return c.sendError(fmt.Sprintf("there is no parameter $%s", k))
```
Comment (tamird) [inline sql/pgwire/v3.go]: could you not combine these checks? they seem to be about different error conditions entirely. the pre-existing check is more of a sanity check and doesn't happen in practice AFAICT

Comment (tamird) [inline sql/pgwire/v3.go]: ah, i see you added a test for that case. that query actually successfully prepares in PG, fwiw.

Comment (dt) [inline sql/pgwire/v3.go]: Does it? I get:
```
SELECT 0 > $2; pq: could not determine data type of parameter $1
```

Comment (tamird) [inline sql/pgwire/v3.go]: original comment was incorrect, fixed via edit

Comment (petermattis) [inline sql/pgwire/v3.go]: Hmm, ok. I changed the way this loop works so that we grow the `pq.inTypes` array as necessary instead of assuming it is the same size as `len(args)`. And I've changed the error for unable to infer parameter type to match postgres.

**Comment by tamird** [comment]
LGTM
