### PR TITLE
release-22.2: ccl/sqlproxyccl: fix status code and hint reporting

### LINKED ISSUE #93474: Misleading error message when using    sslmode=require
**Describe the problem**

The following message is received when using `sslmode=require` instead of `sslmode=verify-full` :

```
failed to connect to `host=test-stuff123.cockroachlabs.cloud user=test database=defaultdb`: server error (FATAL: codeParamsRoutingFailed: missing cluster identifier (SQLSTATE 08004))
```

Message is misleading as it complains about missing cluster ID rather than wrong sslmode. Can we change it please?

Jira issue: CRDB-22352

gz#14985

### PR DESCRIPTION
**Pull request by darinpp**
Backport 1/1 commits from #94030.

/cc @cockroachdb/release

---

The error with code that the proxy uses doesn't follow the same pattern as the rest of the repo code and as a result the hint that we add to the error was not being passed to the end user. This PR refactors the error to be in line with the rest of the code, refactors the hint that we use in case of missing routing info and adds a test to verify that it works.

Fixes #93474

Release note: None

Release justification: Fixes a customer reported bug that only affects
the sqlproxy.

### CODE REVIEW

File: pkg/ccl/sqlproxyccl/connector.go [hunk 1]
```diff
@@ -156,7 +156,7 @@ func (c *connector) OpenTenantConnWithAuth(
 	}
 	defer func() {
 		if retErr != nil {
-			serverConn.Close()
+			_ = serverConn.Close()
```
Comment (knz) [inline pkg/ccl/sqlproxyccl/connector.go:159]: I didn't catch that in the main PR. Don't you want to use errors.CombineErrors here?

Comment (darinpp) [reply pkg/ccl/sqlproxyccl/connector.go]: Yes. I added the call to CombineErrors

**Review by rafiss — APPROVED** [review]
