### PR TITLE
workload/schemachange: deflake violatesFkConstraintsHelper in workload

### LINKED ISSUE #119288: pkg/ccl/testccl/workload/schemachange/schemachange_test: TestWorkload failed [mismatched type in violatesFkConstraintsHelper query]
pkg/ccl/testccl/workload/schemachange/schemachange_test.TestWorkload [failed](https://tanzanite.cluster.engflow.com/invocations/default/e0d64c03-bbe8-4af3-b0cb-5866cef06f13?testReportRun=8&testReportShard=1&testReportAttempt=1#targets-Ly9wa2cvY2NsL3Rlc3RjY2wvd29ya2xvYWQvc2NoZW1hY2hhbmdlOnNjaGVtYWNoYW5nZV90ZXN0) on master @ [617bf347978dcc0d711399b1a76402d7f88de958](https://github.com/cockroachdb/cockroach/commits/617bf347978dcc0d711399b1a76402d7f88de958):

```
        	            	  | "fatal error when running txn"
        	            	  | github.com/cockroachdb/errors/withstack/*withstack.withStack::
        	            	Wraps: (2)
        	            	Wraps: (3) attached stack trace
        	            	  -- stack trace:
        	            	  | github.com/cockroachdb/cockroach/pkg/workload/schemachange.(*schemaChangeWorker).runInTxn
        	            	  | 	github.com/cockroachdb/cockroach/pkg/workload/schemachange/schemachange.go:454
        	            	  | [...repeated from below...]
        	            	Wraps: (4) ***UNEXPECTED ERROR; Failed to generate a random operation
        	            	Wraps: (5) attached stack trace
        	            	  -- stack trace:
        	            	  | github.com/cockroachdb/cockroach/pkg/workload/schemachange.CollectOne[...]
        	            	  | 	github.com/cockroachdb/cockroach/pkg/workload/schemachange/query_util.go:167
        	            	  | github.com/cockroachdb/cockroach/pkg/workload/schemachange.Scan[...]
        	            	  | 	github.com/cockroachdb/cockroach/pkg/workload/schemachange/query_util.go:149
        	            	  | github.com/cockroachdb/cockroach/pkg/workload/schemachange.(*operationGenerator).scanBool
        	            	  | 	github.com/cockroachdb/cockroach/pkg/workload/schemachange/error_screening.go:88
        	            	  | github.com/cockroachdb/cockroach/pkg/workload/schemachange.(*operationGenerator).violatesFkConstraintsHelper
        	            	  | 	github.com/cockroachdb/cockroach/pkg/workload/schemachange/error_screening.go:1202
        	            	  | github.com/cockroachdb/cockroach/pkg/workload/schemachange.(*operationGenerator).violatesFkConstraints
        	            	  | 	github.com/cockroachdb/cockroach/pkg/workload/schemachange/error_screening.go:1121
        	            	  | github.com/cockroachdb/cockroach/pkg/workload/schemachange.(*operationGenerator).insertRow
        	            	  | 	github.com/cockroachdb/cockroach/pkg/workload/schemachange/operation_generator.go:2921
        	            	  | github.com/cockroachdb/cockroach/pkg/workload/schemachange.(*operationGenerator).randOp
        	            	  | 	github.com/cockroachdb/cockroach/pkg/workload/schemachange/operation_generator.go:196
        	            	  | github.com/cockroachdb/cockroach/pkg/workload/schemachange.(*schemaChangeWorker).runInTxn
        	            	  | 	github.com/cockroachdb/cockroach/pkg/workload/schemachange/schemachange.go:441
        	            	  | github.com/cockroachdb/cockroach/pkg/workload/schemachange.(*schemaChangeWorker).run
        	            	  | 	github.com/cockroachdb/cockroach/pkg/workload/schemachange/schemachange.go:545
        	            	  | pkg/ccl/testccl/workload/schemachange/schemachange_test_test.TestWorkload.TestWorkload.func4.func6
        	            	  | 	pkg/ccl/testccl/workload/schemachange/schemachange_test_test/pkg/ccl/testccl/workload/schemachange/schema_change_external_test.go:121
        	            	  | golang.org/x/sync/errgroup.(*Group).Go.func1
        	            	  | 	golang.org/x/sync/errgroup/external/org_golang_x_sync/errgroup/errgroup.go:75
        	            	  | runtime.goexit
        	            	  | 	src/runtime/asm_amd64.s:1650
        	            	Wraps: (6) CollectOne: Query: "\n\t    SELECT false = ANY (ARRAY ['6383303776005880229306.14565726'::DECIMAL = '1999-08-20 22:33:07.000795':::TIMESTAMP]) AND count(*) = 0 from schema_w1_11.table_w0_31\n\t    WHERE cȍl31_w0_36 = ('1999-08-20 22:33:07.000795':::TIMESTAMP)\n\t" []
        	            	Wraps: (7) ERROR: unsupported comparison operator: <decimal> = <timestamp> (SQLSTATE 22023)
        	            	Error types: (1) *markers.withMark (2) *schemachange.ErrorState (3) *withstack.withStack (4) *errutil.withPrefix (5) *withstack.withStack (6) *errutil.withPrefix (7) *pgconn.PgError
        	Test:       	TestWorkload
Schema Workload Stats
Total Schema Statements Executed = 113
Total Schema Statements Succeeded = 113
Total Schema Statement Expected Failures = 0
Total Transactions Committed = 67
Total Transactions Rolled Back = 56
Total Transactions Executed = 123
    schema_change_external_test.go:98: backup, tracing data, and system table dumps in /var/lib/engflow/worker/work/1/exec/bazel-out/k8-fastbuild/testlogs/pkg/ccl/testccl/workload/schemachange/schemachange_test/run_8_of_30/test.outputs/logTestWorkload675587457
    panic.go:523: -- test log scope end --
test logs left over in: outputs.zip/logTestWorkload675587457
--- FAIL: TestWorkload (22.44s)
```

Parameters:
 - <code>attempt=1</code>
 - <code>run=8</code>
 - <code>shard=1</code>
<details><summary>Help</summary>
<p>

See also: [How To Investigate a Go Test Failure \(internal\)](https://cockroachlabs.atlassian.net/l/c/HgfXfJgM)
</p>
</details>
<details><summary>Same failure on other branches</summary>
<p>

- #118879 pkg/ccl/testccl/workload/schemachange/schemachange_test: TestWorkload failed [C-test-failure O-robot P-3 T-sql-foundations branch-release-23.1.15-rc]
- #117782 pkg/ccl/testccl/workload/schemachange/schemachange_test: TestWorkload failed [C-test-failure O-robot P-3 T-sql-foundations branch-release-23.2.0-rc]
</p>
</details>
/cc @cockroachdb/sql-foundations
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*TestWorkload.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)
</sub>

Jira issue: CRDB-36128

### PR DESCRIPTION
**Pull request by annrpom**
Previously, we saw flakes like `ERROR: unsupported comparison operator: <string> = <timetz>` occurring in the rsw because at times, we were indexing a column name in a map without any guards. This meant that if any improperly quoted column name was being looked up in the map, we would just return the default for that key not existing in our map (0). This caused us to refer an arbitrary column's values when validating FK constraints, causing a mismatch that we see above.

We now have checks to guard us from making this mistake again, along with proper quotes around column names.

In addition, alter FK statements and inserts in the same explicit txn did not bode well - as the query to get our `fkConstraints` relied on the `crdb_internal.is_constraint_active` builtin, which does not work in the legacy schema changer: https://github.com/cockroachdb/cockroach/issues/120702. In this case, we do not need the builtin to filter for our FK constraints.

Epic: none
Fixes: #119288

Release note: None

### CODE REVIEW

**Comment by annrpom** [comment]
Here is `tab_ json`:

```
 {"id": 1, "name": "i", "nullable": true, "type": {"family": "IntFamily", "oid": 20, "width": 64}}
  {"id": 2, "name": "j", "nullable": true, "type": {"family": "IntFamily", "oid": 20, "width": 64}}
  {"defaultExpr": "unique_rowid()", "hidden": true, "id": 3, "name": "rowid", "type": {"family": "IntFamily", "oid": 20, "width": 64}}
```
is
ordinal(n) = column_id(n)-1 ?

**Comment by annrpom** [comment]
Found the issue I think:

We aren't getting the correct `fkConstraints` https://github.com/cockroachdb/cockroach/blob/82e2be01134e43a010972eda547290cdb662fdaf/pkg/workload/schemachange/error_screening.go#L1064 in an explicit txn.

Repro: 

```
create table t(i int, j int unique);

create table t2(q int, w int unique);

BEGIN;

alter table t add constraint aa foreign key (j) references public.t2 (w);

SELECT array[parent.table_schema, parent.table_name, quote_ident(parent.column_name), quote_ident(child.column_name)]
		  FROM (
		        SELECT conname, conkey, confkey, conrelid, confrelid
		          FROM pg_constraint
		         WHERE contype = 'f'
		           AND conrelid = 'public.t'::REGCLASS::INT8
		       ) AS con
			JOIN ( SELECT CONSTRAINT_NAME from information_schema.table_constraints 
				      WHERE table_schema ='public' AND
								    table_name='t' AND
										(crdb_internal.is_constraint_active('public.t', constraint_name) = true)
           ) AS tc ON conname = tc.CONSTRAINT_NAME
		  JOIN (
		        SELECT column_name, ordinal_position, column_default
		          FROM information_schema.columns
		         WHERE table_schema = 'public'
		           AND table_name = 't'
		       ) AS child ON conkey[1] = child.ordinal_position
		  JOIN (
		        SELECT pc.oid,
		               cols.table_schema,
		               cols.table_name,
		               cols.column_name,
		               cols.ordinal_position
		          FROM pg_class AS pc
		          JOIN pg_namespace AS pn ON pc.relnamespace = pn.oid
		          JOIN information_schema.columns AS cols ON (pc.relname = cols.table_name AND pn.nspname = cols.table_schema)
		       ) AS parent ON (
		                       con.confkey[1] = parent.ordinal_position
		                       AND con.confrelid = parent.oid
		                      )
		 WHERE child.column_name != 'rowid';
<--- nothing returned here

COMMIT;

SELECT array[parent.table_schema, parent.table_name, quote_ident(parent.column_name), quote_ident(child.column_name)]
		  FROM (
		        SELECT conname, conkey, confkey, conrelid, confrelid
		          FROM pg_constraint
		         WHERE contype = 'f'
		           AND conrelid = 'public.t'::REGCLASS::INT8
		       ) AS con
			JOIN ( SELECT CONSTRAINT_NAME from information_schema.table_constraints 
				      WHERE table_schema ='public' AND
								    table_name='t' AND
										(crdb_internal.is_constraint_active('public.t', constraint_name) = true)
           ) AS tc ON conname = tc.CONSTRAINT_NAME
		  JOIN (
		        SELECT column_name, ordinal_position, column_default
		          FROM information_schema.columns
		         WHERE table_schema = 'public'
		           AND table_name = 't'
		       ) AS child ON conkey[1] = child.ordinal_position
		  JOIN (
		        SELECT pc.oid,
		               cols.table_schema,
		               cols.table_name,
		               cols.column_name,
		               cols.ordinal_position
		          FROM pg_class AS pc
		          JOIN pg_namespace AS pn ON pc.relnamespace = pn.oid
		          JOIN information_schema.columns AS cols ON (pc.relname = cols.table_name AND pn.nspname = cols.table_schema)
		       ) AS parent ON (
		                       con.confkey[1] = parent.ordinal_position
		                       AND con.confrelid = parent.oid
		                      )
		 WHERE child.column_name != 'rowid';

<---- 
   array
--------------
  {public,t2,w,j}
```

**Comment by annrpom** [comment]
This seems a bit off - shouldn't `is_constraint_active` return true for our FK constraint? we are filtering for in AllConstraints https://github.com/cockroachdb/cockroach/blob/7a8844145efd224895a873dc752553da1ffd65dc/pkg/sql/catalog/descriptor.go#L643

**Comment by annrpom** [comment]
Well, it turns out `ALTER TABLE ADD CONSTRAINT FK` in an explicit txn falls back to the legacy schema changer - which exhibits this behavior. If we set `set use_declarative_schema_changer = unsafe_always;` and force the DSC, we see that `crdb_internal.is_constraint_active` is true

**Comment by annrpom** [comment]
cc: @rafiss and @fqazi what do you all think of this (starting from https://github.com/cockroachdb/cockroach/pull/119653#issuecomment-1992601082) - is it intentional that `add constraint FK` falls back to legacy schema changer (noob q: where in the code can i find this out?) and would the fix here be to avoid `add constraint FK` in explicit txns in the schemachange workload?

**Comment by rafiss** [comment]
oh also, is the `is_constraint_active` filter even needed? what happens if we remove that?

**Review by rafiss — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/119653)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @annrpom)

___
*[`pkg/workload/schemachange/optype.go` line 268 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/119653#-Nt2mogR4jaJmZm34okz:-Nt2mogR4jaJmZm34ol-:bqx268q) ([raw file](https://github.com/cockroachdb/cockroach/blob/b22839b50aa46678d1022096462a2ea6c2c08870/pkg/workload/schemachange/optype.go#L268)):*
> ```Go
> 	alterFunctionSetSchema:            1,
> 	alterTableAddColumn:               1,
> 	alterTableAddConstraintForeignKey: 300,
> ```

note: i disabled foreign keys in https://github.com/cockroachdb/cockroach/pull/120575; make sure to re-enable in this PR

**Comment by annrpom** [comment]
Well 🤔 I was getting some flake with refcursors that I just mindlessly put a workaround for; however, I can't seem to track the flake down anymore (and the flake didn't make sense to me since we got to the point where we assumed we had an FK relation on some refcursor columns - which is just not allowed)

So I'll put it up in a draft here in case we need it: https://github.com/cockroachdb/cockroach/pull/120712

File: pkg/workload/schemachange/operation_generator.go [hunk 1]
```diff
@@ -3209,14 +3210,16 @@ func (og *operationGenerator) getTableColumns(
...
+												 c->>'id' AS ordinal
                     FROM columns_json
                  )
   SELECT quote_ident(show_columns.column_name),
          show_columns.data_type,
          show_columns.is_nullable,
          columns.generation_expression IS NOT NULL AS is_generated,
-         COALESCE(columns.generation_expression, '') as generated_expression
+         COALESCE(columns.generation_expression, '') AS generated_expression,
+			   columns.ordinal::INT-1
```
Comment (annrpom) [inline pkg/workload/schemachange/operation_generator.go:3222]: is ordinal(n) = column_id(n)-1 ?

**Comment by annrpom** [comment]
Let me touch up the commit messages

> oh also, is the is_constraint_active filter even needed? what happens if we remove that?

this seems right to include "in theory", but the theory there could be baseless since i am not sure how we would get into a state where we have a constraint that is not active, but that still shows up in `information_schema`

everything seems to not flake when i just don't include this part

**Review by rafiss — APPROVED** [review]
lgtm! just had small nits you can address then merge

can you also check with Faizan in case he knows if the original reason for the `is_constraint_active` check? looks like he added it originally in 57210f015a32962163894df1c325e5b15b12979c

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/119653#-:-NtWY8Zt-yNrnBMvXdGe:bfickd0)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @annrpom, @renatolabs, and @srosenberg)

___
*[`pkg/workload/schemachange/error_screening.go` line 1069 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/119653#-NtWWmSV-cUzp1OegBl3:-NtWWmSV-cUzp1OegBl4:bc1wu9v) ([raw file](https://github.com/cockroachdb/cockroach/blob/0b1eafa15c18d05188d9cbe508a9480bbe6587f4/pkg/workload/schemachange/error_screening.go#L1069)):*
> ```Go
> ) (bool, error) {
> 	fkConstraints, err := og.scanStringArrayRows(ctx, tx, fmt.Sprintf(`
> 		SELECT array[parent.table_schema, parent.table_name, quote_ident(parent.column_name), quote_ident(child.column_name)]
> ```

nit: do the schema and table names also need to be quoted? (i guess it can't hurt?)
___
*[`pkg/workload/schemachange/operation_generator.go` line 890 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/119653#-NtWXMd1122SlxTcBO_C:-NtWXMd22WCOhjm72oF-:bizyazl) ([raw file](https://github.com/cockroachdb/cockroach/blob/0b1eafa15c18d05188d9cbe508a9480bbe6587f4/pkg/workload/schemachange/operation_generator.go#L890)):*
> ```Go
> 	og.potentialCommitErrors.add(pgcode.ForeignKeyViolation)
> 
> 	// TODO(foundations): this was added in #116790 without reason
> ```

assuming the test passes without this, let's remove it

if it does not pass without it, let's change "without reason" to "for an unknown reason that prevents foreign keys from failing in some cases." but if we do in fact see a test fail, the error message will probably tell us the reason

**Review by annrpom — COMMENTED** [review]
`is_constraint_active` check is fine being left out for 2 reasons:
1. constraint schema changes do not need this additional join/filter because being in the ADDING/DROPPING state should still mean that our constraint is enforced on writes. whenever our constraint is gone/removed, we will no longer see it in `pg_constraint`
2. at worst, this change will mean that our workload is more strict for a few inserts (i.e. we pretend a FK constraint is there when it is not and block some harmless inserts)

it sounds like this change was added because txn rollbacks don't play too nicely with DDLs (maybe we have seen a case or are preparing for a case where a constraint is still dangling in pg_constraint, but is not active due to a bad rollback?) either way: i think it's safe in those cases to defer to 2 until #120702 is resolved. i'll just leave a TODO in there for now

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/119653#-:-NtXoi_sAZetVbAhTEhl:b-2j6its)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @rafiss, @renatolabs, and @srosenberg)

___
*[`pkg/workload/schemachange/error_screening.go` line 1069 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/119653#-NtWWmSV-cUzp1OegBl3:-NtXyERuAapCghKmhveN:bgkhwx9) ([raw file](https://github.com/cockroachdb/cockroach/blob/0b1eafa15c18d05188d9cbe508a9480bbe6587f4/pkg/workload/schemachange/error_screening.go#L1069)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

nit: do the schema and table names also need to be quoted? (i guess it can't hurt?)
</blockquote></details>

it can't hurt, but we add random noise to column names - we don't really do that with schema and table names. i can add a callout comment here instead (i think it makes more sense to not start quoting table/schema names out of nowhere)
___
*[`pkg/workload/schemachange/operation_generator.go` line 890 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/119653#-NtWXMd1122SlxTcBO_C:-NtY0WNv9QYyNX_g9vhf:b-vzavzk) ([raw file](https://github.com/cockroachdb/cockroach/blob/0b1eafa15c18d05188d9cbe508a9480bbe6587f4/pkg/workload/schemachange/operation_generator.go#L890)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

assuming the test passes without this, let's remove it

if it does not pass without it, let's change "without reason" to "for an unknown reason that prevents foreign keys from failing in some cases." but if we do in fact see a test fail, the error message will probably tell us the reason
</blockquote></details>

oki done - stressing it a bit more before i merge just to see!
___
*[`pkg/workload/schemachange/optype.go` line 268 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/119653#-Nt2mogR4jaJmZm34okz:-NtXoffq6FhWkzwSRvf-:bb7f2mf) ([raw file](https://github.com/cockroachdb/cockroach/blob/b22839b50aa46678d1022096462a2ea6c2c08870/pkg/workload/schemachange/optype.go#L268)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

note: i disabled foreign keys in https://github.com/cockroachdb/cockroach/pull/120575; make sure to re-enable in this PR
</blockquote></details>

done

**Comment by annrpom** [comment]
TFTR! ('-')7

bors r=rafiss

**Comment by rafiss** [comment]
does this also resolve https://github.com/cockroachdb/cockroach/issues/120771?

**Comment by annrpom** [comment]
i dont believe it does - i was trying to get #120771 to repro outside of these changes and with this change, but had no luck. i can dig into this more next week?

**Comment by rafiss** [comment]
I will just mark https://github.com/cockroachdb/cockroach/issues/120771 as closed by this issue. If it fails again, then we'll investigate at that point.

**Comment by rafiss** [comment]
oh i missed that you said "don't". so I will leave https://github.com/cockroachdb/cockroach/issues/120771 as-is, but yes let's pick it up next week
