### PR TITLE
changefeedccl: Tweak assume-role test params

### LINKED ISSUE #113920: roachtest: cdc/cloud-sink-gcs/assume-role failed
roachtest.cdc/cloud-sink-gcs/assume-role [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/12543044?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/12543044?buildTab=artifacts#/cdc/cloud-sink-gcs/assume-role) on release-22.2.17-rc @ [135acce473babb0109e796343581823b69146ebe](https://github.com/cockroachdb/cockroach/commits/135acce473babb0109e796343581823b69146ebe):

```
test artifacts and logs in: /artifacts/cdc/cloud-sink-gcs/assume-role/run_1
(cdc.go:1818).assertValid: max latency was more than allowed: 1m5.166080858s vs 1m0s
```
<p>Parameters: <code>ROACHTEST_arch=amd64</code>
, <code>ROACHTEST_cloud=gce</code>
, <code>ROACHTEST_cpu=16</code>
, <code>ROACHTEST_encrypted=false</code>
, <code>ROACHTEST_ssd=0</code>
</p>
<details><summary>Help</summary>
<p>

See: [roachtest README](https://github.com/cockroachdb/cockroach/blob/master/pkg/cmd/roachtest/README.md)

See: [How To Investigate \(internal\)](https://cockroachlabs.atlassian.net/l/c/SSSBr8c7)

</p>
</details>
/cc @cockroachdb/cdc
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*cdc/cloud-sink-gcs/assume-role.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)
</sub>

Jira issue: CRDB-33256

### LINKED ISSUE #114221: roachtest: cdc/cloud-sink-gcs/assume-role failed
roachtest.cdc/cloud-sink-gcs/assume-role [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/12604148?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/12604148?buildTab=artifacts#/cdc/cloud-sink-gcs/assume-role) on release-22.2 @ [da4a3b10ddf71baa3bafe85ee8d64db668d74f58](https://github.com/cockroachdb/cockroach/commits/da4a3b10ddf71baa3bafe85ee8d64db668d74f58):

```
test artifacts and logs in: /artifacts/cdc/cloud-sink-gcs/assume-role/run_1
(cdc.go:1818).assertValid: max latency was more than allowed: 1m6.86667373s vs 1m0s
```
<p>Parameters: <code>ROACHTEST_arch=amd64</code>
, <code>ROACHTEST_cloud=gce</code>
, <code>ROACHTEST_cpu=16</code>
, <code>ROACHTEST_encrypted=false</code>
, <code>ROACHTEST_ssd=0</code>
</p>
<details><summary>Help</summary>
<p>

See: [roachtest README](https://github.com/cockroachdb/cockroach/blob/master/pkg/cmd/roachtest/README.md)

See: [How To Investigate \(internal\)](https://cockroachlabs.atlassian.net/l/c/SSSBr8c7)

</p>
</details>
<details><summary>Same failure on other branches</summary>
<p>

- #113920 roachtest: cdc/cloud-sink-gcs/assume-role failed [C-test-failure O-roachtest O-robot branch-release-22.2.17-rc release-blocker]
</p>
</details>
/cc @cockroachdb/cdc
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*cdc/cloud-sink-gcs/assume-role.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)
</sub>

Jira issue: CRDB-33401

### PR DESCRIPTION
**Pull request by miretskiy**
Tweak assume-role parameters to decrease the workload duration, and increase changefeed memory allowance (really only applicable to v22.2 as that allowance was increased in the later versions).
Ensure assume-role test runs only in GCS as the
output buckets reside on GCS.

Fixes #113920
Fixes #114221

Release note: None

### CODE REVIEW

**Comment by miretskiy** [comment]
See last updated on https://github.com/cockroachlabs/support/issues/2716

File: pkg/cmd/roachtest/tests/cdc.go [hunk 1]
```diff
@@ -1305,23 +1305,25 @@ func registerCDC(r registry.Registry) {
...
+		CompatibleClouds: registry.OnlyGCE,
 		Suites:           registry.Suites(registry.Nightly),
 		RequiresLicense:  true,
 		Run: func(ctx context.Context, t test.Test, c cluster.Cluster) {
 			ct := newCDCTester(ctx, t, c)
 			defer ct.Close()
 
-			ct.runTPCCWorkload(tpccArgs{warehouses: 1, duration: "30m"})
+			// Bump memory limit (too low in 22.2)
+			if _, err := ct.DB().Exec("SET CLUSTER SETTING changefeed.memory.per_changefeed_limit = '512MiB';"); err != nil {
```
Comment (nicktrav) [inline pkg/cmd/roachtest/tests/cdc.go:1322]: From what I can tell, [this is the default on `master` already](https://github.com/cockroachdb/cockroach/blob/ba6423f916dc4006bb590c786cf53ad2b0213417/pkg/ccl/changefeedccl/changefeedbase/settings.go#L46-L51)? Instead, shall we just change this on `release-22.2`?

**Review by nicktrav — COMMENTED** [review]
What if we did the following:
- Make this patch just for the `OnlyGCE` diff,
- Backport the above to 22.2,
- Land a 22.2-only patch to update the cluster setting.

File: pkg/cmd/roachtest/tests/cdc.go (hunk 1 above)
Comment (miretskiy) [reply pkg/cmd/roachtest/tests/cdc.go:1322]: Didn't want to make direct 22.2 patch and wanted to backport; do you think it might be okay to merge this; backport it, and then remove this cluster setting since it's the default?

Comment (nicktrav) [reply pkg/cmd/roachtest/tests/cdc.go:1322]: Sg.

**Review by nicktrav — APPROVED** [review]
