### PR TITLE
sqlliveness: add timeouts to heartbeats

### LINKED ISSUE #85540: Logs aren't clear about when SQL pod exits due to a sqlliveness session expiring
**Describe the problem**
The logs aren't clear about when a SQL pod exits due to a sqlliveness session expiring. See the code here: https://github.com/cockroachdb/cockroach/blob/71e1af40a2b32ab040de0f83dfab036fd74928c1/pkg/sql/sqlinstance/instanceprovider/instanceprovider.go#L174-L180. 

**To Reproduce**
N/A

**Expected behavior**
CRDB should log the shutdown reason at fatal severity. CRDB should also probably return a non-zero exit code, since it is not expected for sqlliveness sessions to expire.

**Additional data / screenshots**
Link to a related internal support issue: https://github.com/cockroachlabs/support/issues/1736

Jira issue: CRDB-18301

### LINKED ISSUE #85541: sqlliveness: no deadlines on heartbeats
**Describe the problem**
From what I can see, there are no deadlines on sqlliveness heartbeats. This means a single hung heartbeat will expire a sqliveness session. A hung heartbeat can happen for various reasons, e.g. temporary disk overload. Multi-tenant SQL pods crash if a sqliveness session expires right now. So a single hung heartbeat can actually crash a multi-tenant SQL pod. I believe we have observed this in practice, tho I'm only medium confident about that claim (link to internal support issue: https://github.com/cockroachlabs/support/issues/1736).

**To Reproduce**
N/A

**Expected behavior**
There should be deadlines on sqlliveness heartbeats.

**Additional data / screenshots**
Link to internal support issue: https://github.com/cockroachlabs/support/issues/1736

Jira issue: CRDB-18302

### PR DESCRIPTION
**Pull request by aadityasondhi**
Previously, sqlliveness heartbeat operations could block on the transactions that were involved. This change introduces some timeouts of the length of the heartbeat during the create and refresh operations.

Resolves #85541

Release note: None

Release justification: low-risk bugfix to existing functionality

### CODE REVIEW

File: pkg/sql/sqlliveness/slstorage/test_helpers.go [hunk 1]
```diff
@@ -21,7 +22,8 @@ import (
 
 // FakeStorage implements the sqlliveness.Storage interface.
 type FakeStorage struct {
-	mu struct {
+	InsertSleep time.Duration
```
Comment (ajwerner) [inline pkg/sql/sqlliveness/slstorage/test_helpers.go:25]: Sleeps are generally an anti-pattern in our repo. Especially sleeps that are intended to wait for something to happen. Anything like this would need to be well motivated. I have a hard time understanding how these sleeps fit into the test. 

I think I'd prefer if we did something more explicit, like have a the `FakeStorage` send on a channel here or. One approach is to use a `chan chan struct{}` where the `Insert` call will send a channel on a channel, and then block until it receives from the sent channel. In that way, we can be sure that the Insert does not make progress, and we don't need to wait for timing.

File: pkg/sql/sqlliveness/slinstance/slinstance.go [hunk 2]
```diff
@@ -237,6 +239,58 @@ func (l *Instance) extendSession(ctx context.Context, s *session) (bool, error)
...
+
+	t := timeutil.NewTimer()
+	t.Reset(timeout)
+	select {
+	case <-t.C:
+		return nil, &TimeoutError{}
+	case <-createChan:
+		return s, err
+	}
+}
```
Comment (ajwerner) [inline pkg/sql/sqlliveness/slinstance/slinstance.go:271]: 1) this seems complex
2) This fails to actually cancel the underlying work, which, I think, is bad

Can we instead with `context.WithTimeout` and then detect the deadline exceeded error?

**Review by ajwerner — CHANGES_REQUESTED** [review]

File: pkg/sql/sqlliveness/slstorage/test_helpers.go (hunk 1 above)
Comment (aadityasondhi) [reply pkg/sql/sqlliveness/slstorage/test_helpers.go]: Thanks for pointing it out. Made changes and introduced the pattern you suggested.

File: pkg/sql/sqlliveness/slinstance/slinstance.go (hunk 2 above)
Comment (aadityasondhi) [reply pkg/sql/sqlliveness/slinstance/slinstance.go]: Changed to use `context.WithTimeout`

File: pkg/sql/sqlliveness/slinstance/slinstance.go [hunk 3]
```diff
@@ -103,6 +104,7 @@ func (s *session) invokeSessionExpiryCallbacks(ctx context.Context) {
 	for _, callback := range s.mu.sessionExpiryCallbacks {
 		callback(ctx)
 	}
+	log.Fatal(ctx, "sqlliveness session expired")
```
Comment (ajwerner) [inline pkg/sql/sqlliveness/slinstance/slinstance.go:107]: I don't think this is at all reasonable. The kv node expects to be robust to this failure and the sql pod installs a callback for exactly this purpose. Please remove this from this PR and look at those callbacks. If you want to change the behavior which happens in those callbacks, please do, but in a different PR.

File: pkg/sql/sqlliveness/slinstance/slinstance.go [hunk 4]
```diff
@@ -237,6 +239,48 @@ func (l *Instance) extendSession(ctx context.Context, s *session) (bool, error)
 	return true, nil
 }
 
+func (l *Instance) createSessionWithTimeout(
```
Comment (ajwerner) [inline pkg/sql/sqlliveness/slinstance/slinstance.go:242]: I'm still not quite getting it. The context cancellation should just flow through the underlying calls. Why are you creating these separate goroutines? It feels like all you want to do is context the timeout context in the existing `createSession` and `extendSession` methods.

Comment (aadityasondhi) [reply pkg/sql/sqlliveness/slinstance/slinstance.go:242]: Please correct me if my understanding is wrong. From https://github.com/cockroachdb/cockroach/issues/85541, my understanding was that the underlying storage could hang for whatever reason. When this happens, it would hang the current goroutine (which is running the heartbeat), not really solving the initial problem. By doing this in a separate goroutine, the caller can exit when the context is canceled (after exceeding the deadline) even if the child is stuck on a call. Whenever the child recovers, it will see that the context is canceled and exit.

File: pkg/sql/sqlliveness/slinstance/slinstance.go (hunk 3 above)
Comment (aadityasondhi) [reply pkg/sql/sqlliveness/slinstance/slinstance.go:107]: Makes sense, I will add this to the callback and put it in a separate PR.

**Review by ajwerner — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/87533)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @aadityasondhi, @abarganier, @ajwerner, and @joshimhoff)

___
*[`pkg/sql/sqlliveness/slinstance/slinstance.go` line 242 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/87533#-NBOcSmGuPF4VqnBsU6A-r3-242:-NBmxBBw4XZB_0y16f-p:bsymusl) ([raw file](https://github.com/cockroachdb/cockroach/blob/934e219bff6ac8ae4dc2d5870756183f25dc19da/pkg/sql/sqlliveness/slinstance/slinstance.go#L242)):*
<details><summary><i>Previously, aadityasondhi (Aaditya Sondhi) wrote…</i></summary><blockquote>

Please correct me if my understanding is wrong. From https://github.com/cockroachdb/cockroach/issues/85541, my understanding was that the underlying storage could hang for whatever reason. When this happens, it would hang the current goroutine (which is running the heartbeat), not really solving the initial problem. By doing this in a separate goroutine, the caller can exit when the context is canceled (after exceeding the deadline) even if the child is stuck on a call. Whenever the child recovers, it will see that the context is canceled and exit.
</blockquote></details>

It's a good deal of complexity. I think if we're going to cover that case we need to understand it and have tests which exercise the scenario. In general, my feeling is that we should rely on context cancellation achieving our goals down through the RPC stack. Just adding the timeout to the context would be a 99+% win in my book, whereas this feels like an unclear additional step.

**Review by aadityasondhi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/87533)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @abarganier, @ajwerner, and @joshimhoff)

___
*[`pkg/sql/sqlliveness/slinstance/slinstance.go` line 242 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/87533#-NBOcSmGuPF4VqnBsU6A-r3-242:-NBnRtquCi5YDXe-jry0:bsz14e5) ([raw file](https://github.com/cockroachdb/cockroach/blob/934e219bff6ac8ae4dc2d5870756183f25dc19da/pkg/sql/sqlliveness/slinstance/slinstance.go#L242)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

It's a good deal of complexity. I think if we're going to cover that case we need to understand it and have tests which exercise the scenario. In general, my feeling is that we should rely on context cancellation achieving our goals down through the RPC stack. Just adding the timeout to the context would be a 99+% win in my book, whereas this feels like an unclear additional step. 
</blockquote></details>

I see, that makes sense. I updated the code and tests to rely on context cancellation for exiting early.

**Review by ajwerner — COMMENTED** [review]
> Reviewed 2 of 5 files at r5, 3 of 3 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/87533)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @aadityasondhi, @abarganier, @ajwerner, and @joshimhoff)

___
*[`pkg/sql/sqlliveness/slinstance/slinstance.go` line 288 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/87533#-NBorATC6Je6Mk7iH1-7:-NBorATC6Je6Mk7iH1-8:biwrmho) ([raw file](https://github.com/cockroachdb/cockroach/blob/a89e27fdaad1e91d0ab96b433410cfc9fdf949e4/pkg/sql/sqlliveness/slinstance/slinstance.go#L288)):*
> ```Go
> 				// Unable to extend session due to unknown error.
> 				// Clear and stop heartbeat loop.
> 				log.Errorf(ctx, "sqlliveness failed to extend session: %v", err)
> ```

I wonder if this is the right policy. I know this isn't changed code. Really just asking the question. 



_Code quote:_
```Go
				// Unable to extend session due to unknown error.
				// Clear and stop heartbeat loop.
				log.Errorf(ctx, "sqlliveness failed to extend session: %v", err)
```
___
*[`pkg/sql/sqlliveness/slinstance/slinstance_test.go` line 155 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/87533#-NBore4HCIMHFdztof9J:-NBore4HCIMHFdztof9K:b3uf1dm) ([raw file](https://github.com/cockroachdb/cockroach/blob/a89e27fdaad1e91d0ab96b433410cfc9fdf949e4/pkg/sql/sqlliveness/slinstance/slinstance_test.go#L155)):*
> ```Go
> 	slinstance.DefaultTTL.Override(ctx, &settings.SV, 2*time.Millisecond)
> 	// Must be shorter than the storage sleep amount below
> 	slinstance.DefaultHeartBeat.Override(ctx, &settings.SV, 1*time.Millisecond)
> ```

In my experience, 1ms timers can cause trouble under race. You may want to move them up to something on the order of 10ms if the race detector is enabled. 



_Code quote:_
```Go
	slinstance.DefaultTTL.Override(ctx, &settings.SV, 2*time.Millisecond)
	// Must be shorter than the storage sleep amount below
	slinstance.DefaultHeartBeat.Override(ctx, &settings.SV, 1*time.Millisecond)
```
___
*[`pkg/sql/sqlliveness/slinstance/slinstance_test.go` line 162 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/87533#-NBorVYb-m_u4Pg_Csfl:-NBorVYb-m_u4Pg_Csfm:b8zfupe) ([raw file](https://github.com/cockroachdb/cockroach/blob/a89e27fdaad1e91d0ab96b433410cfc9fdf949e4/pkg/sql/sqlliveness/slinstance/slinstance_test.go#L162)):*
> ```Go
> 
> 	// verify that eventually session is created successfully
> 	require.Eventually(
> ```

I think `testutils.SucceedsSoon` will both be easier to use here and will behave better under stress because it backs off its loop. 
___
*[`pkg/sql/sqlliveness/slstorage/test_helpers.go` line 24 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/87533#-NBoruoX8VHUVo2JCYgL:-NBoruoX8VHUVo2JCYgM:b-6nx9l8) ([raw file](https://github.com/cockroachdb/cockroach/blob/a89e27fdaad1e91d0ab96b433410cfc9fdf949e4/pkg/sql/sqlliveness/slstorage/test_helpers.go#L24)):*
> ```Go
> // FakeStorage implements the sqlliveness.Storage interface.
> type FakeStorage struct {
> 	BlockCh chan struct{}
> ```

My guess is that you're going to need to put this `BlockCh` under the mutex and add a setter for it. It feels to me like the test is not synchronizing setting it with its use.

**Review by aadityasondhi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/87533)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @abarganier, @ajwerner, and @joshimhoff)

___
*[`pkg/sql/sqlliveness/slinstance/slinstance.go` line 288 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/87533#-NBorATC6Je6Mk7iH1-7:-NCLcyhoDeUsEEXuxDeW:b-obng4) ([raw file](https://github.com/cockroachdb/cockroach/blob/a89e27fdaad1e91d0ab96b433410cfc9fdf949e4/pkg/sql/sqlliveness/slinstance/slinstance.go#L288)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

I wonder if this is the right policy. I know this isn't changed code. Really just asking the question. 
</blockquote></details>

I am not sure personally. Who would be the right team/person to ask? 
___
*[`pkg/sql/sqlliveness/slstorage/test_helpers.go` line 24 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/87533#-NBoruoX8VHUVo2JCYgL:-NCLd9C7-31MkqC0uMLy:bkis8i1) ([raw file](https://github.com/cockroachdb/cockroach/blob/a89e27fdaad1e91d0ab96b433410cfc9fdf949e4/pkg/sql/sqlliveness/slstorage/test_helpers.go#L24)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

My guess is that you're going to need to put this `BlockCh` under the mutex and add a setter for it. It feels to me like the test is not synchronizing setting it with its use. 
</blockquote></details>

Good call, it did have a race condition. Thanks! Made the change in the latest revision. 
___
*[`pkg/sql/sqlliveness/slinstance/slinstance_test.go` line 155 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/87533#-NBore4HCIMHFdztof9J:-NCLdIqrDZSXhh_ZjBID:byfr4gh) ([raw file](https://github.com/cockroachdb/cockroach/blob/a89e27fdaad1e91d0ab96b433410cfc9fdf949e4/pkg/sql/sqlliveness/slinstance/slinstance_test.go#L155)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

In my experience, 1ms timers can cause trouble under race. You may want to move them up to something on the order of 10ms if the race detector is enabled. 
</blockquote></details>

Thanks for the pointer. Changed.
___
*[`pkg/sql/sqlliveness/slinstance/slinstance_test.go` line 162 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/87533#-NBorVYb-m_u4Pg_Csfl:-NCLdNQe95nzWh6QJVJ_:byfr4gh) ([raw file](https://github.com/cockroachdb/cockroach/blob/a89e27fdaad1e91d0ab96b433410cfc9fdf949e4/pkg/sql/sqlliveness/slinstance/slinstance_test.go#L162)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

I think `testutils.SucceedsSoon` will both be easier to use here and will behave better under stress because it backs off its loop. 
</blockquote></details>

Thanks for the pointer. Changed.

**Review by ajwerner — COMMENTED** [review]
> Reviewed 2 of 4 files at r7.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/87533)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @aadityasondhi, @abarganier, @ajwerner, and @joshimhoff)

___
*[`pkg/sql/sqlliveness/slstorage/test_helpers.go` line 52 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/87533#-NCRfMW-2h2wYuPg7mQC:-NCRfMW07cUtwypnGuj9:b-xh4jc8) ([raw file](https://github.com/cockroachdb/cockroach/blob/b78b6c45d0dcae34230c1cc2dc9ea2a8c3f0c636/pkg/sql/sqlliveness/slstorage/test_helpers.go#L52)):*
> ```Go
> 	ctx context.Context, sid sqlliveness.SessionID, expiration hlc.Timestamp,
> ) error {
> 	s.mu.Lock()
> ```

is there an issue here if you block while holding the mutex? should you pull the channel out under the mutex and then block? I feel like this is a classic case where mutexes and channels don't compose well. 



_Code quote:_
```Go
	defer s.mu.Unlock()
```

**Review by aadityasondhi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/87533)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @abarganier, @ajwerner, and @joshimhoff)

___
*[`pkg/sql/sqlliveness/slstorage/test_helpers.go` line 52 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/87533#-NCRfMW-2h2wYuPg7mQC:-NCVixSDCw-yGfCrbGrH:bpnd8qg) ([raw file](https://github.com/cockroachdb/cockroach/blob/b78b6c45d0dcae34230c1cc2dc9ea2a8c3f0c636/pkg/sql/sqlliveness/slstorage/test_helpers.go#L52)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

is there an issue here if you block while holding the mutex? should you pull the channel out under the mutex and then block? I feel like this is a classic case where mutexes and channels don't compose well. 
</blockquote></details>

Thanks, fixed in the latest revision

**Review by ajwerner — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/87533)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @aadityasondhi, @abarganier, @ajwerner, and @joshimhoff)

___
*[`pkg/sql/sqlliveness/slinstance/slinstance.go` line 285 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/87533#-NCWu4vX8cy6X63l1T0X:-NCWu4vX8cy6X63l1T0Y:b-50omme) ([raw file](https://github.com/cockroachdb/cockroach/blob/a89e27fdaad1e91d0ab96b433410cfc9fdf949e4/pkg/sql/sqlliveness/slinstance/slinstance.go#L285)):*
> ```Go
> 				found, err = l.extendSession(ctx, s)
> 				return err
> 			}); err != nil && !errors.HasType(err, (*contextutil.TimeoutError)(nil)) {
> ```

It seems to me like if you hit the timeout, you don't know whether the session exists or not, so you probably should not clear the session -- you should keep retrying to extend the current session, no? 
___
*[`pkg/sql/sqlliveness/slinstance/slinstance.go` line 288 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/87533#-NBorATC6Je6Mk7iH1-7:-NCWu8CL6hjzaPPkxJiY:blfg8r4) ([raw file](https://github.com/cockroachdb/cockroach/blob/a89e27fdaad1e91d0ab96b433410cfc9fdf949e4/pkg/sql/sqlliveness/slinstance/slinstance.go#L288)):*
<details><summary><i>Previously, aadityasondhi (Aaditya Sondhi) wrote…</i></summary><blockquote>

I am not sure personally. Who would be the right team/person to ask? 
</blockquote></details>

I think you also want to avoid logging if the `ctx.Err() != nil` because we shouldn't log during clean server shutdown.
___
*[`pkg/sql/sqlliveness/slinstance/slinstance.go` line 285 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/87533#-NCWsuUMCOeeopXb2Pks:-NCWsuUMCOeeopXb2Pkt:b-9t2oln) ([raw file](https://github.com/cockroachdb/cockroach/blob/5bbf6192f0fa7793d3c6eccd9fbedf009aa630a1/pkg/sql/sqlliveness/slinstance/slinstance.go#L285)):*
> ```Go
> 				found, err = l.extendSession(ctx, s)
> 				return err
> 			}); err != nil && !errors.HasType(err, (*contextutil.TimeoutError)(nil)) {
> ```

I think you should also check if the context is canceled, which it will be during shutdown.

**Review by aadityasondhi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/87533)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @abarganier, @ajwerner, and @joshimhoff)

___
*[`pkg/sql/sqlliveness/slinstance/slinstance.go` line 285 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/87533#-NCWu4vX8cy6X63l1T0X:-NCaRof3AdEAhFEqer7j:b3nfxnp) ([raw file](https://github.com/cockroachdb/cockroach/blob/a89e27fdaad1e91d0ab96b433410cfc9fdf949e4/pkg/sql/sqlliveness/slinstance/slinstance.go#L285)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

It seems to me like if you hit the timeout, you don't know whether the session exists or not, so you probably should not clear the session -- you should keep retrying to extend the current session, no? 
</blockquote></details>

Yes, you are correct. Fixed the behavior and tests to match it.
___
*[`pkg/sql/sqlliveness/slinstance/slinstance.go` line 288 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/87533#-NBorATC6Je6Mk7iH1-7:-NCaS3De7upgo_Q97xRc:b1220y3) ([raw file](https://github.com/cockroachdb/cockroach/blob/a89e27fdaad1e91d0ab96b433410cfc9fdf949e4/pkg/sql/sqlliveness/slinstance/slinstance.go#L288)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

I think you also want to avoid logging if the `ctx.Err() != nil` because we shouldn't log during clean server shutdown.
</blockquote></details>

That makes sense. Changed.
___
*[`pkg/sql/sqlliveness/slinstance/slinstance.go` line 285 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/87533#-NCWsuUMCOeeopXb2Pks:-NCaRfGGBJ3e5bANL5dF:b-m0bvw4) ([raw file](https://github.com/cockroachdb/cockroach/blob/5bbf6192f0fa7793d3c6eccd9fbedf009aa630a1/pkg/sql/sqlliveness/slinstance/slinstance.go#L285)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

I think you should also check if the context is canceled, which it will be during shutdown. 
</blockquote></details>

Thanks for pointing it out, fixed.

**Review by ajwerner — APPROVED** [review]
Very close. My refactor is a nit. Feel free to take it or leave it and merge. 

> Reviewed 1 of 3 files at r9, 2 of 4 files at r11, 2 of 2 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/87533#-:-NCb4hbU2za6bKXDHikL:b-xj2nu8)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @aadityasondhi, @abarganier, and @joshimhoff)

___
*[`pkg/sql/sqlliveness/slinstance/slinstance.go` line 292 at r12](https://reviewable.io/reviews/cockroachdb/cockroach/87533#-NCb34jj95amGIox7NZU:-NCb34jj95amGIox7NZV:b61sh0w) ([raw file](https://github.com/cockroachdb/cockroach/blob/3b43176f967e6011de6b37abe54707f3e668dcdd/pkg/sql/sqlliveness/slinstance/slinstance.go#L292)):*
> ```Go
> 				return err
> 			})
> 			if err != nil {
> ```

this logic is getting a bit messy and hard to read how about:

```go
switch {
case errors.HasType(err, (*contextutil.TimeoutError)(nil)):
    // Retry without clearing the session because we don't know the current status.
    t.Reset(0)
    continue
case err != nil && ctx.Err() == nil:
   log.Errorf(ctx, "sqlliveness failed to extend session: %v", err)
   fallthrough
case err != nil:
   // TODO(ajwerner): Decide whether we actually should exit the heartbeat loop here if the context is not
   // canceled. Consider the case of an ambiguous result error: shouldn't we try again?
   l.clearSession()
   return
case !found:
  // No existing session found, immediately create one.
  l.clearSession(ctx)
  // Start next loop iteration immediately to insert a new session.
  t.Reset(0)
default:
  if log.V(2) {
     log.Infof(ctx, "extended SQL liveness session %s", s.ID()) 
  }
  t.Reset(l.gb()
}
```

**Comment by aadityasondhi** [comment]
bors r=ajwerner

**Comment by joshimhoff** [comment]
Thank you!

Can we get a 22.1 backport? CC serverless is running 22.1. Major upgrade can take some time in practice. The lack of these HBs has led to inactionable alerts hitting the pagers of our SREs.

**Comment by ajwerner** [comment]
Why do major upgrades lead to unavailability? I feel like I was missing some context on the motivation here.

**Review by andreimatei — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/87533)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[`pkg/sql/sqlliveness/slinstance/BUILD.bazel` line 40 at r14](https://reviewable.io/reviews/cockroachdb/cockroach/87533#-NElXmXX2BXOpArMK3Wi:-NElXmXYEqxwzPsX7Ixv:b-ox4xql) ([raw file](https://github.com/cockroachdb/cockroach/blob/59a70ba8eb11cd3ce708ca85affc112a26b8741a/pkg/sql/sqlliveness/slinstance/BUILD.bazel#L40)):*
> ```Starlark
>         "//pkg/sql/sqlliveness",
>         "//pkg/sql/sqlliveness/slstorage",
>         "//pkg/testutils",
> ```

for future reference, you definitely want to squash a diff like this into the prior commit. All commits must build.
