### PR TITLE
fix #1536 (multiraft): drain (not close) channels on shutdown

### LINKED ISSUE #1536: MultiRaft writes to its input channels after close
The following test appears to have failed:

[#4232](https://circleci.com/gh/cockroachdb/cockroach/4232):

```
I0628 23:55:50.080297     311 range_command.go:774] range 1: new leader lease replica 1:1 00:00:00.000 +1.000s
I0628 23:55:50.080613     311 range.go:1023] gossiping accounting config from store 1, range 1
I0628 23:55:50.081254     311 range.go:1023] gossiping permissions config from store 1, range 1
I0628 23:55:50.081802     311 range.go:1023] gossiping zones config from store 1, range 1
==================
WARNING: DATA RACE
Read by goroutine 80:
  runtime.chansend()
      /usr/src/go/src/runtime/chan.go:83 +0x0
  github.com/cockroachdb/cockroach/storage.(*Store).ProposeRaftCommand()
      /go/src/github.com/cockroachdb/cockroach/storage/store.go:1408 +0x23f
  github.com/cockroachdb/cockroach/storage.(*Range).proposeRaftCommand()
      /go/src/github.com/cockroachdb/cockroach/storage/range.go:737 +0x5ca
  github.com/cockroachdb/cockroach/storage.(*Range).requestLeaderLease()
      /go/src/github.com/cockroachdb/cockroach/storage/range.go:345 +0x55e
  github.com/cockroachdb/cockroach/storage.(*Range).redirectOnOrAcquireLeaderLease()
--
  github.com/cockroachdb/cockroach/storage.func·034()
      /go/src/github.com/cockroachdb/cockroach/storage/store.go:575 +0x61
  github.com/cockroachdb/cockroach/util.func·001()
      /go/src/github.com/cockroachdb/cockroach/util/stopper.go:75 +0x7f

Previous write by goroutine 10:
  runtime.closechan()
      /usr/src/go/src/runtime/chan.go:257 +0x0
  github.com/cockroachdb/cockroach/multiraft.(*state).stop()
      /go/src/github.com/cockroachdb/cockroach/multiraft/multiraft.go:636 +0x652
  github.com/cockroachdb/cockroach/multiraft.func·004()
      /go/src/github.com/cockroachdb/cockroach/multiraft/multiraft.go:491 +0x763
  github.com/cockroachdb/cockroach/util.func·001()
      /go/src/github.com/cockroachdb/cockroach/util/stopper.go:75 +0x7f

Goroutine 80 (running) created at:
--
  github.com/cockroachdb/cockroach/kv.TestTxnCoordSenderGC()
      /go/src/github.com/cockroachdb/cockroach/kv/txn_coord_sender_test.go:460 +0xda
  testing.tRunner()
      /usr/src/go/src/testing/testing.go:447 +0x133
==================
panic: send on closed channel

goroutine 1376 [running]:
github.com/cockroachdb/cockroach/storage.(*Store).ProposeRaftCommand(0xc2080da000, 0xc2087d8db0, 0x10, 0x1, 0x100000001, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/cockroachdb/cockroach/storage/store.go:1408 +0x240
github.com/cockroachdb/cockroach/storage.(*Range).proposeRaftCommand(0xc20875a360, 0x7f148df0b490, 0xc20823cf90, 0x7f148df09708, 0xc2080da300, 0x7f148df0b4d0, 0xc2080116c0, 0x1, 0x630000006c)
	/go/src/github.com/cockroachdb/cockroach/storage/range.go:737 +0x5cb
github.com/cockroachdb/cockroach/storage.(*Range).requestLeaderLease(0xc20875a360, 0x2540be401, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/storage/range.go:345 +0x55f
github.com/cockroachdb/cockroach/storage.(*Range).redirectOnOrAcquireLeaderLease(0xc20875a360, 0x2540be401, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/storage/range.go:385 +0x296
--
	/go/src/github.com/cockroachdb/cockroach/kv/txn_coord_sender_test.go:490 +0x89e
testing.tRunner(0xc20875a000, 0x1a2dc98)
	/usr/src/go/src/testing/testing.go:447 +0x134
created by testing.RunTests
	/usr/src/go/src/testing/testing.go:555 +0xd4e
FAIL	github.com/cockroachdb/cockroach/kv	5.419s
=== RUN TestHeartbeatSingleGroup-2
--- PASS: TestHeartbeatSingleGroup-2 (0.41s)
=== RUN TestHeartbeatMultipleGroupsJointLeader-2
--- PASS: TestHeartbeatMultipleGroupsJointLeader-2 (0.05s)
=== RUN TestHeartbeatResponseFanout-2
I0628 23:55:52.448233     322 heartbeat_test.go:425] SubmitCommand succeed after Heartbeat Response fanout
E0628 23:55:52.452318     322 transport.go:202] sending rpc failed: read tcp 127.0.0.1:46854: use of closed network connection
--- PASS: TestHeartbeatResponseFanout-2 (0.08s)
=== RUN TestInitialLeaderElection-2
I0628 23:55:52.455317     322 multiraft_test.go:158] testing leader election for node 0

```
Please assign, take a look and update the issue accordingly.

### PR DESCRIPTION
**Pull request by tbg**
fixes #1536

### CODE REVIEW

**Comment by tamird** [comment]
LGTM but ping @bdarnell because there should be a better way to deal with this :(

**Comment by tschottdorf** [comment]
It's possible with a little bit of refactoring. With channel-based communication, the writer needs to close the channel, and that's the Store. We could have MultiRaft not use the Stopper: `NewMultiRaft` should return a closer chan for the `state` loop, and `(*Store).Close()` would close the closer, at which point MultiRaft doesn't even need to close its input channels any more.

File: multiraft/multiraft.go [hunk 1]
```diff
@@ -623,22 +623,22 @@ func (s *state) stop() {
...
-		case op := <-s.proposalChan:
-			op.ch <- util.Errorf("shutting down")
-		default:
-			close(s.createGroupChan)
-			close(s.removeGroupChan)
-			close(s.proposalChan)
-			return
+	// on these operations. We can't close these channels unless we
+	// make sure that we never write to them after, but that would mean
+	// an atomic guard before every write access. Better to just deal
```
Comment (bdarnell) [inline multiraft/multiraft.go]: The only time multiraft writes to its own input channels is when it re-submits all pending proposals after an election; an atomic guard there is fine (and much better than deliberately leaking a goroutine to consume from the channels forever).

Comment (tschottdorf) [inline multiraft/multiraft.go]: it's also about the store writing to the channels. Do we want an atomically updated bool in front of `CreateGroup`, `RemoveGroup` and `Propose` chans? And why is leaking the goroutine bad per se?

Comment (bdarnell) [inline multiraft/multiraft.go]: On the store side all of these things should already be atomically guarded by `Stopper.StartTask`. 

Leaking a goroutine isn't a big problem since this won't happen more than once per process in production (although this implementation holds a reference to the `state` object and might indirectly keep a bunch of objects from GC), but it just seems clumsy to require it.

**Comment by tschottdorf** [comment]
@bdarnell PTAL. I've guarded `store.ProposeRaftCommand` and `store.RemoveRange` so that they shouldn't try to use Raft when it may have shut down. I've removed the channel cleanup in `MultiRaft.close()` because nobody must be using the input channels any more, so nobody blocks. There's also no reason for closing them as far as I can tell.

File: storage/store.go [hunk 2]
```diff
@@ -1123,6 +1123,10 @@ func (s *Store) addRangeToRangeMap(rng *Range) error {
 func (s *Store) RemoveRange(rng *Range) error {
 	// RemoveGroup needs to access the storage, which in turn needs the
 	// lock. Some care is needed to avoid deadlocks.
+	if !s.stopper.StartTask() {
```
Comment (bdarnell) [inline storage/store.go]: This looks like the wrong place for a call to `StartTask`; we need to ensure that a task is started at a higher level before calling whatever calls RemoveRange. I assume this is via `EndTransaction -> mergeTrigger -> mergeRange`, in which case I think the right place to call StartTask is in `Store.processRaft` right after we've read an event from the multiraft channel. Once we're draining we should just drop multiraft events on the floor; they'll be retried by the next incarnation of the node.

File: storage/store.go [hunk 3]
```diff
@@ -1428,13 +1432,23 @@ func (s *Store) ProposeRaftCommand(idKey cmdIDKey, cmd proto.InternalRaftCommand
...
-	if err != nil {
+	errChan := func(err error) chan error {
 		ch := make(chan error, 1)
 		ch <- err
 		return ch
 	}
+	// If the system is shutting down and has drained, don't accept new
+	// proposals: Raft may already have stopped.
+	select {
+	case <-s.stopper.ShouldStop():
```
Comment (tschottdorf) [inline storage/store.go]: we also shouldn't be seeing this one do anything unless spurious requests exist, correct?

Comment (bdarnell) [inline storage/store.go]: Correct.

File: storage/store.go (hunk 2 above)
Comment (tschottdorf) [inline storage/store.go]: we still need to process Raft while draining, it's only right after having drained when Raft no longer needs to be able to make progress. I'll add that check to `processRaft`.

**Comment by tschottdorf** [comment]
I went back to check the commit this error came from, and `getLeaseForGossip` wasn't guarded by a `StartTask` call then. That means this race shouldn't be there now. I've kept the rest (including removing the MultiRaft channel dance which shouldn't be necessary).

**Comment by bdarnell** [comment]
LGTM
