### PR TITLE
backup: use ioctx.ReadAll when reading index metadata

### LINKED ISSUE #153213: pkg/ccl/cloudccl/amazon/amazon_test: TestAWSKMSExternalConnection failed
pkg/ccl/cloudccl/amazon/amazon_test.TestAWSKMSExternalConnection [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_CloudUnitTests/20445838?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_CloudUnitTests/20445838?buildTab=artifacts#/) on master @ [b26650a4c5ddb781eec00f4e06f9f48657427f83](https://github.com/cockroachdb/cockroach/commits/b26650a4c5ddb781eec00f4e06f9f48657427f83):

```
=== RUN   TestAWSKMSExternalConnection
    test_log_scope.go:171: test logs captured to: /artifacts/tmp/_tmp/90c1c2a76fdb8bf273c5e978243dfe5a/logTestAWSKMSExternalConnection1761983997
    test_log_scope.go:82: use -show-logs to present logs inline
    test_server_shim.go:154: automatically injected an external process virtual cluster under test; see comment at top of test_server_shim.go for details.
    s3_connection_test.go:224: error executing query="RESTORE DATABASE foo FROM LATEST IN 'external://backup' WITH new_db_name = bar, kms='external://auth-implicit-kms'" args=[]: pq: getting backup index metadata: reading index file 82fe66d42ff673_0_20250909-001118.28_metadata.pb bytes: EOF
    panic.go:635: -- test log scope end --
test logs left over in: /artifacts/tmp/_tmp/90c1c2a76fdb8bf273c5e978243dfe5a/logTestAWSKMSExternalConnection1761983997
--- FAIL: TestAWSKMSExternalConnection (3.00s)
=== RUN   TestAWSKMSExternalConnection/auth-implicit
    testing.go:1577: test executed panic(nil) or runtime.Goexit: subtest may have called FailNow on a parent test
--- FAIL: TestAWSKMSExternalConnection/auth-implicit (1.51s)
```
<details><summary>Help</summary>
<p>

See also: [How To Investigate a Go Test Failure \(internal\)](https://cockroachlabs.atlassian.net/l/c/HgfXfJgM)
</p>
</details>
/cc @cockroachdb/disaster-recovery
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*TestAWSKMSExternalConnection.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/bazci/githubpost/issues)

</sub>

Jira issue: CRDB-54274

### LINKED ISSUE #153214: pkg/ccl/cloudccl/amazon/amazon_test: TestS3ExternalConnection failed
pkg/ccl/cloudccl/amazon/amazon_test.TestS3ExternalConnection [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_CloudUnitTests/20445838?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_CloudUnitTests/20445838?buildTab=artifacts#/) on master @ [b26650a4c5ddb781eec00f4e06f9f48657427f83](https://github.com/cockroachdb/cockroach/commits/b26650a4c5ddb781eec00f4e06f9f48657427f83):

```
=== RUN   TestS3ExternalConnection
    test_log_scope.go:171: test logs captured to: /artifacts/tmp/_tmp/90c1c2a76fdb8bf273c5e978243dfe5a/logTestS3ExternalConnection2255364495
    test_log_scope.go:82: use -show-logs to present logs inline
    s3_connection_test.go:59: error executing query="RESTORE DATABASE foo FROM LATEST IN 'external://auth-implicit-s3' WITH new_db_name = bar" args=[]: pq: getting backup index metadata: reading index file 82fe66d430009d_0_20250909-001115.68_metadata.pb bytes: EOF
    panic.go:635: -- test log scope end --
test logs left over in: /artifacts/tmp/_tmp/90c1c2a76fdb8bf273c5e978243dfe5a/logTestS3ExternalConnection2255364495
--- FAIL: TestS3ExternalConnection (1.78s)
=== RUN   TestS3ExternalConnection/auth-implicit
    testing.go:1577: test executed panic(nil) or runtime.Goexit: subtest may have called FailNow on a parent test
--- FAIL: TestS3ExternalConnection/auth-implicit (1.18s)
```
<details><summary>Help</summary>
<p>

See also: [How To Investigate a Go Test Failure \(internal\)](https://cockroachlabs.atlassian.net/l/c/HgfXfJgM)
</p>
</details>
/cc @cockroachdb/disaster-recovery
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*TestS3ExternalConnection.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/bazci/githubpost/issues)

</sub>

Jira issue: CRDB-54275

### LINKED ISSUE #153215: backup: TestCloudBackupRestoreS3 failed
backup.TestCloudBackupRestoreS3 [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_CloudUnitTests/20445838?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_CloudUnitTests/20445838?buildTab=artifacts#/) on master @ [b26650a4c5ddb781eec00f4e06f9f48657427f83](https://github.com/cockroachdb/cockroach/commits/b26650a4c5ddb781eec00f4e06f9f48657427f83):

```
=== RUN   TestCloudBackupRestoreS3
    test_log_scope.go:171: test logs captured to: /artifacts/tmp/_tmp/1786afbdea420760d89983de47c28371/logTestCloudBackupRestoreS33384924350
    test_log_scope.go:82: use -show-logs to present logs inline
    backup_cloud_test.go:63: -- test log scope end --
test logs left over in: /artifacts/tmp/_tmp/1786afbdea420760d89983de47c28371/logTestCloudBackupRestoreS33384924350
--- FAIL: TestCloudBackupRestoreS3 (10.53s)
=== RUN   TestCloudBackupRestoreS3/object-locked-bucket
    backup_test.go:1010: error scanning '&{0xc005cb78c0 <nil>}': pq: getting backup index metadata: reading index file 82fe66d42977d0_0_20250909-001823.91_metadata.pb bytes: EOF
    testutils.go:307: no Invalid Descriptors
--- FAIL: TestCloudBackupRestoreS3/object-locked-bucket (5.90s)
=== RUN   TestCloudBackupRestoreS3/regular-bucket
    backup_test.go:1010: error scanning '&{0xc009fc5b00 <nil>}': pq: getting backup index metadata: reading index file 82fe66d42962d8_0_20250909-001829.28_metadata.pb bytes: EOF
    testutils.go:307: no Invalid Descriptors
--- FAIL: TestCloudBackupRestoreS3/regular-bucket (4.61s)
```
<details><summary>Help</summary>
<p>

See also: [How To Investigate a Go Test Failure \(internal\)](https://cockroachlabs.atlassian.net/l/c/HgfXfJgM)
</p>
</details>
/cc @cockroachdb/disaster-recovery
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*TestCloudBackupRestoreS3.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/bazci/githubpost/issues)

</sub>

Jira issue: CRDB-54276

### PR DESCRIPTION
**Pull request by kev-cao**
We currently use `io.Reader`'s `Read` to read the index metadata file. However, `Read` behavior w.r.t to returning an EOF after reading the entire file is not consistent --- S3's implementation returns EOF even if bytes are read, whereas GCS's implementation returns EOF only if a read is attempted after reading the file. The correct solution is to use `ioctx.ReadAll` whenever performing reads.

Fixes: #153215

Fixes: #153214 

Fixes: #153213 

Fixes: #153212

Release note: None

### CODE REVIEW

File: pkg/cloud/cloud_io.go [hunk 1]
```diff
@@ -320,6 +320,13 @@ func (r *ResumingReader) Read(ctx context.Context, p []byte) (int, error) {
 			read += n
 			r.Pos += int64(n)
 			if readErr == nil || readErr == io.EOF {
+				// The Go filesystem will only return EOF if no bytes were read due to
+				// EOF. Some Cloud providers (e.g. S3) may return EOF even if some bytes
+				// were read. To maintain consistency with the filesystem behavior, we
+				// enforce that an EOF is only returned if no bytes were read.
```
Comment (jeffswenson) [inline pkg/cloud/cloud_io.go]: Have you looked at the S3 client to understand why we are observing this error? Is this the normal behavior of their client or are we doing something weird like failing to pass the length through?

File: pkg/cloud/impl/cloudimpltests/main_test.go [hunk 2]
```diff
@@ -24,3 +47,140 @@ func TestMain(m *testing.M) {
...
+	// file, we only get EOF once all bytes of the file have been read.
+	ctx := context.Background()
+	st := cluster.MakeTestingClusterSettings()
+	dir, dirCleanup := testutils.TempDir(t)
+	defer dirCleanup()
+
+	testcases := []struct {
+		name string
+		uri  func(prefix string) (uri string, skipErr error)
+	}{
```
Comment (jeffswenson) [inline pkg/cloud/impl/cloudimpltests/main_test.go]: The existing pattern for shared tests is we add the test implementation to cloudtestutils package, then call it from stubs in each of the cloud packages.

File: pkg/cloud/cloud_io.go (hunk 1 above)
Comment (kev-cao) [reply pkg/cloud/cloud_io.go]: Took some digging around but found the reason! The S3 client returns a [`smithyhttp.Response`, which ultimately just wraps the Go `http.Response`.](https://github.com/aws/aws-sdk-go-v2/blob/70e9f3d91a369c9147a9b09f2e66e270ef5febbb/service/s3/deserializers.go#L5939)

Poking around the Go code a bit, [we find this little snippet](https://cs.opensource.google/go/go/+/master:src/net/http/transfer.go;l=870-880;drc=998ce1c4262aab0153b5e89f84ef2ddd57507ec7) which shows that if you call `.Read` on that body, you get an `EOF` when all bytes are read, even if the call you make is the one that read all the bytes.

You can test this with a minimal HTTP client/server setup like this:
<details>
<summary><h3>Server</h3></summary>

```golang
package main

import (
	rand "crypto/rand"
	"log"
	"net/http"
	"strconv"
)

const size = 1 << 10 // 1 KiB

func fileHandler(w http.ResponseWriter, r *http.Request) {
	if r.Method != http.MethodGet {
		w.Header().Set("Allow", http.MethodGet)
		http.Error(w, "method not allowed", http.StatusMethodNotAllowed)
		return
	}

	buf := make([]byte, size)
	if _, err := rand.Read(buf); err != nil {
		http.Error(w, "random read failed", http.StatusInternalServerError)
		return
	}

	w.Header().Set("Content-Type", "application/octet-stream")
	w.Header().Set("Content-Length", strconv.Itoa(len(buf)))
	w.Header().Set("Cache-Control", "no-store")
	if _, err := w.Write(buf); err != nil {
		log.Printf("write error: %v", err)
	}
}

func main() {
	mux := http.NewServeMux()
	mux.HandleFunc("/file", fileHandler)

	srv := &http.Server{
		Addr:    "127.0.0.1:25565",
		Handler: mux,
	}

	log.Printf("serving on http://%s", srv.Addr)
	log.Fatal(srv.ListenAndServe())
}
```
</details>
<details>
<summary><h3>Client</h3></summary>

```golang
package main

import (
	"log"
	"net/http"
)

func main() {
	resp, err := http.Get("http://127.0.0.1:25565/file")
	if err != nil {
		log.Fatal(err)
	}
	defer resp.Body.Close()

	if resp.StatusCode != http.StatusOK {
		log.Fatalf("unexpected status: %s", resp.Status)
	}

	log.Printf("content length: %d", resp.ContentLength)
	output := make([]byte, resp.ContentLength)
	n, err := resp.Body.Read(output)
	log.Printf("read %d bytes, err: %v", n, err)
}
```
</details>

So why don't we see this error with GCP? Some more digging unveiled that GCP uses HTTP/2 for its transport, and the [`Read` for HTTP/2 does **not** follow this behavior](https://cs.opensource.google/go/x/net/+/master:http2/transport.go;l=2500-2524;drc=6dc6880bcd7edc82184626a363d26d65bc55c195). I was poking around to find an official stance on S3's support of HTTP/2, but couldn't find one. But running the `aws s3` CLI with `--debug`, I do see this:
```
2025-09-11 12:56:51,499 - MainThread - urllib3.connectionpool - DEBUG - https://kevcao-us-east-1.s3.us-east-1.amazonaws.com:443 "GET /testfile HTTP/1.1" 200 1024
```

I also tested out the HTTP/2 behavior with respect to EOF, and as expected, it does not return EOF after a `Read` containing bytes:

<details>
<summary><h3>HTTP/2 Server</h3></summary>

```golang
package main

import (
	rand "crypto/rand"
	"log"
	"net/http"
	"strconv"

	"golang.org/x/net/http2"
	"golang.org/x/net/http2/h2c"
)

const size = 1024 // 1 KiB

func fileHandler(w http.ResponseWriter, r *http.Request) {
	if r.Method != http.MethodGet {
		w.Header().Set("Allow", http.MethodGet)
		http.Error(w, "method not allowed", http.StatusMethodNotAllowed)
		return
	}

	// Log the negotiated protocol to verify h2
	log.Printf("handler proto: %s", r.Proto) // expect "HTTP/2.0"

	buf := make([]byte, size)
	if _, err := rand.Read(buf); err != nil {
		http.Error(w, "random read failed", http.StatusInternalServerError)
		return
	}

	w.Header().Set("Content-Type", "application/octet-stream")
	w.Header().Set("Content-Length", strconv.Itoa(len(buf)))
	w.Header().Set("Cache-Control", "no-store")

	if _, err := w.Write(buf); err != nil {
		log.Printf("write error: %v", err)
	}
}

func main() {
	mux := http.NewServeMux()
	mux.HandleFunc("/file", fileHandler)

	// h2c: HTTP/2 over cleartext (no TLS) for local/dev usage
	h2s := &http2.Server{}
	srv := &http.Server{
		Addr:    "127.0.0.1:25565",
		Handler: h2c.NewHandler(mux, h2s),
	}

	log.Printf("serving h2c on http://%s", srv.Addr)
	log.Fatal(srv.ListenAndServe())
}
```
</details>
<details>
<summary><h3>HTTP/2 Client</h3></summary>

```golang
package main

import (
	"crypto/tls"
	"log"
	"net"
	"net/http"

	"golang.org/x/net/http2"
)

func main() {
	// http2.Transport with AllowHTTP + custom DialTLS enables h2c (cleartext HTTP/2).
	tr := &http2.Transport{
		AllowHTTP: true,
		DialTLS: func(network, addr string, _ *tls.Config) (net.Conn, error) {
			// Plain TCP dial; no TLS handshake. For h2c only.
			return net.Dial(network, addr)
		},
	}
	client := &http.Client{Transport: tr}

	resp, err := client.Get("http://127.0.0.1:25565/file")
	if err != nil {
		log.Fatal(err)
	}
	defer resp.Body.Close()

	if resp.ProtoMajor != 2 {
		log.Fatalf("not HTTP/2: got %s", resp.Proto)
	}
	if resp.StatusCode != http.StatusOK {
		log.Fatalf("unexpected status: %s", resp.Status)
	}

	log.Printf("content length: %d", resp.ContentLength)
	output := make([]byte, resp.ContentLength)
	n, err := resp.Body.Read(output)
	log.Printf("read %d bytes, err: %v", n, err)
}
```
</details>

File: pkg/cloud/impl/cloudimpltests/main_test.go (hunk 2 above)
Comment (kev-cao) [reply pkg/cloud/impl/cloudimpltests/main_test.go]: Ah perfect, was wondering how we get around the import cycles. Thanks!

File: pkg/cloud/cloud_io.go (hunk 1 above)
Comment (jeffswenson) [reply pkg/cloud/cloud_io.go]: Thanks for looking into this! I think digging into the underlying cause is valuable because it mitigates the risk of papering over a bug. Can you add a condensed version of this to the comment?

File: pkg/cloud/cloud_io.go [hunk 3]
```diff
@@ -320,6 +320,13 @@ func (r *ResumingReader) Read(ctx context.Context, p []byte) (int, error) {
...
+				if n > 0 && readErr == io.EOF {
+					readErr = nil
+				}
 				return read, readErr
 			}
 			if r.Size > 0 && r.Pos == r.Size {
```
Comment (jeffswenson) [inline pkg/cloud/cloud_io.go]: This `r.Size > 0 && r.Pos == r.Size` check will return EOF if we read the full size of the file, which is what this change is trying to avoid.

File: pkg/cloud/cloud_io.go [hunk 4]
```diff
@@ -320,6 +320,13 @@ func (r *ResumingReader) Read(ctx context.Context, p []byte) (int, error) {
 			read += n
 			r.Pos += int64(n)
 			if readErr == nil || readErr == io.EOF {
+				// The Go filesystem will only return EOF if no bytes were read due to
+				// EOF. Some Cloud providers (e.g. S3) may return EOF even if some bytes
+				// were read. To maintain consistency with the filesystem behavior, we
+				// enforce that an EOF is only returned if no bytes were read.
+				if n > 0 && readErr == io.EOF {
```
Comment (jeffswenson) [inline pkg/cloud/cloud_io.go]: I think this check is a little too generous. We should return an EOF if we try to read past the end of the file, even if we read a non-zero number of bytes.

E.g.
```
data := make([]byte, size+1)
obj.Read(data) // should return an EOF
```

Comment (kev-cao) [reply pkg/cloud/cloud_io.go]: Hmm, I don't think it should return an EOF. The documentation for `io.Reader` says this:

> Read reads up to len(p) bytes into p. It returns the number of bytes
read (0 <= n <= len(p)) and any error encountered. Even if Read
returns n < len(p), it may use all of p as scratch space during the call.
If some data is available but not len(p) bytes, Read conventionally
returns what is available instead of waiting for more.
>
> When Read encounters an error or end-of-file condition after
successfully reading n > 0 bytes, it returns the number of
bytes read. It may return the (non-nil) error from the same call
or return the error (and n == 0) from a subsequent call.
An instance of this general case is that a Reader returning
a non-zero number of bytes at the end of the input stream may
return either err == EOF or err == nil. The next Read should
return 0, EOF.

And if we test this theory using the Go filesystem, providing a slice larger than the data in the file does not return an EOF.

**Review by msbutler — APPROVED** [review]

**Comment by kev-cao** [comment]
TFTR!

bors r=msbutler
