### PR TITLE
roachtest: deflake `failover/chaos` deadlock failures

### LINKED ISSUE #104045: roachtest: failover/chaos/read-write/lease=expiration failed
roachtest.failover/chaos/read-write/lease=expiration [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/10289770?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/10289770?buildTab=artifacts#/failover/chaos/read-write/lease=expiration) on master @ [87c677569f7af6e72834d68e67493efbd72971ac](https://github.com/cockroachdb/cockroach/commits/87c677569f7af6e72834d68e67493efbd72971ac):

```
test artifacts and logs in: /artifacts/failover/chaos/read-write/lease=expiration/run_1
(assertions.go:333).Fail: 
	Error Trace:	github.com/cockroachdb/cockroach/pkg/cmd/roachtest/tests/failover.go:1533
	            				github.com/cockroachdb/cockroach/pkg/cmd/roachtest/tests/failover.go:290
	            				main/pkg/cmd/roachtest/monitor.go:105
	            				golang.org/x/sync/errgroup/external/org_golang_x_sync/errgroup/errgroup.go:75
	            				GOROOT/src/runtime/asm_amd64.s:1594
	Error:      	Received unexpected error:
	            	pq: query execution canceled
	Test:       	failover/chaos/read-write/lease=expiration
(require.go:1360).NoError: FailNow called
(cluster.go:2095).Run: output in run_142106.583375923_n10_cockroach-workload-r: ./cockroach workload run kv --read-percent 50 --write-seq R0 --duration 45m --concurrency 256 --max-rate 8192 --timeout 1m --tolerate-errors --histograms=perf/stats.json {pgurl:1-2} returned: context canceled
(monitor.go:127).Wait: monitor failure: monitor task failed: t.Fatal() was called
(cluster.go:2095).Run: cluster.RunE: context canceled
(cluster.go:2095).Run: cluster.RunE: context canceled
(cluster.go:2095).Run: cluster.RunE: context canceled
(cluster.go:2095).Run: cluster.RunE: context canceled
```
<p>Parameters: <code>ROACHTEST_cloud=gce</code>
, <code>ROACHTEST_cpu=4</code>
, <code>ROACHTEST_encrypted=false</code>
, <code>ROACHTEST_fs=ext4</code>
, <code>ROACHTEST_localSSD=false</code>
, <code>ROACHTEST_ssd=0</code>
</p>
<details><summary>Help</summary>
<p>

See: [roachtest README](https://github.com/cockroachdb/cockroach/blob/master/pkg/cmd/roachtest/README.md)

See: [How To Investigate \(internal\)](https://cockroachlabs.atlassian.net/l/c/SSSBr8c7)

</p>
</details>
/cc @cockroachdb/kv-triage
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*failover/chaos/read-write/lease=expiration.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)
</sub>

Jira issue: CRDB-28334

Epic CRDB-27234

### LINKED ISSUE #104086: roachtest: failover/chaos/read-only/lease=expiration failed
roachtest.failover/chaos/read-only/lease=expiration [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/10301329?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/10301329?buildTab=artifacts#/failover/chaos/read-only/lease=expiration) on master @ [e48d8a376760498c20aa922ddd3b52b5b31dcb19](https://github.com/cockroachdb/cockroach/commits/e48d8a376760498c20aa922ddd3b52b5b31dcb19):

```
test artifacts and logs in: /artifacts/failover/chaos/read-only/lease=expiration/run_1
(assertions.go:333).Fail: 
	Error Trace:	github.com/cockroachdb/cockroach/pkg/cmd/roachtest/tests/failover.go:1533
	            				github.com/cockroachdb/cockroach/pkg/cmd/roachtest/tests/failover.go:290
	            				main/pkg/cmd/roachtest/monitor.go:105
	            				golang.org/x/sync/errgroup/external/org_golang_x_sync/errgroup/errgroup.go:75
	            				GOROOT/src/runtime/asm_amd64.s:1594
	Error:      	Received unexpected error:
	            	pq: query execution canceled
	Test:       	failover/chaos/read-only/lease=expiration
(require.go:1360).NoError: FailNow called
(cluster.go:2095).Run: output in run_141025.451540487_n10_cockroach-workload-r: ./cockroach workload run kv --read-percent 100 --write-seq R100000 --duration 45m --concurrency 256 --max-rate 8192 --timeout 1m --tolerate-errors --histograms=perf/stats.json {pgurl:1-2} returned: context canceled
(monitor.go:127).Wait: monitor failure: monitor task failed: t.Fatal() was called
(cluster.go:2095).Run: cluster.RunE: context canceled
(cluster.go:2095).Run: cluster.RunE: context canceled
(cluster.go:2095).Run: cluster.RunE: context canceled
(cluster.go:2095).Run: cluster.RunE: context canceled
```
<p>Parameters: <code>ROACHTEST_cloud=gce</code>
, <code>ROACHTEST_cpu=4</code>
, <code>ROACHTEST_encrypted=false</code>
, <code>ROACHTEST_fs=ext4</code>
, <code>ROACHTEST_localSSD=false</code>
, <code>ROACHTEST_ssd=0</code>
</p>
<details><summary>Help</summary>
<p>

See: [roachtest README](https://github.com/cockroachdb/cockroach/blob/master/pkg/cmd/roachtest/README.md)

See: [How To Investigate \(internal\)](https://cockroachlabs.atlassian.net/l/c/SSSBr8c7)

</p>
</details>
/cc @cockroachdb/kv-triage
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*failover/chaos/read-only/lease=expiration.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)
</sub>

Jira issue: CRDB-28348

### LINKED ISSUE #104140: roachtest: failover/chaos/read-only failed
roachtest.failover/chaos/read-only [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/10321116?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/10321116?buildTab=artifacts#/failover/chaos/read-only) on master @ [906e7ade9d3891a974ab02e89b4cb69c35ffda13](https://github.com/cockroachdb/cockroach/commits/906e7ade9d3891a974ab02e89b4cb69c35ffda13):

```
test artifacts and logs in: /artifacts/failover/chaos/read-only/run_1
(assertions.go:333).Fail: 
	Error Trace:	github.com/cockroachdb/cockroach/pkg/cmd/roachtest/tests/failover.go:1533
	            				github.com/cockroachdb/cockroach/pkg/cmd/roachtest/tests/failover.go:290
	            				main/pkg/cmd/roachtest/monitor.go:105
	            				golang.org/x/sync/errgroup/external/org_golang_x_sync/errgroup/errgroup.go:75
	            				GOROOT/src/runtime/asm_amd64.s:1594
	Error:      	Received unexpected error:
	            	pq: query execution canceled
	Test:       	failover/chaos/read-only
(require.go:1360).NoError: FailNow called
(cluster.go:2095).Run: output in run_132015.675752716_n10_cockroach-workload-r: ./cockroach workload run kv --read-percent 100 --write-seq R100000 --duration 45m --concurrency 256 --max-rate 8192 --timeout 1m --tolerate-errors --histograms=perf/stats.json {pgurl:1-2} returned: context canceled
(monitor.go:127).Wait: monitor failure: monitor task failed: t.Fatal() was called
(cluster.go:2095).Run: cluster.RunE: context canceled
(cluster.go:2095).Run: cluster.RunE: context canceled
(cluster.go:2095).Run: cluster.RunE: context canceled
(cluster.go:2095).Run: cluster.RunE: context canceled
```
<p>Parameters: <code>ROACHTEST_cloud=gce</code>
, <code>ROACHTEST_cpu=4</code>
, <code>ROACHTEST_encrypted=false</code>
, <code>ROACHTEST_fs=ext4</code>
, <code>ROACHTEST_localSSD=false</code>
, <code>ROACHTEST_ssd=0</code>
</p>
<details><summary>Help</summary>
<p>

See: [roachtest README](https://github.com/cockroachdb/cockroach/blob/master/pkg/cmd/roachtest/README.md)

See: [How To Investigate \(internal\)](https://cockroachlabs.atlassian.net/l/c/SSSBr8c7)

</p>
</details>
/cc @cockroachdb/kv-triage
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*failover/chaos/read-only.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)
</sub>

Jira issue: CRDB-28369

### LINKED ISSUE #104144: roachtest: failover/chaos/read-write failed
roachtest.failover/chaos/read-write [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/10321116?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/10321116?buildTab=artifacts#/failover/chaos/read-write) on master @ [906e7ade9d3891a974ab02e89b4cb69c35ffda13](https://github.com/cockroachdb/cockroach/commits/906e7ade9d3891a974ab02e89b4cb69c35ffda13):

```
test artifacts and logs in: /artifacts/failover/chaos/read-write/run_1
(assertions.go:333).Fail: 
	Error Trace:	github.com/cockroachdb/cockroach/pkg/cmd/roachtest/tests/failover.go:1533
	            				github.com/cockroachdb/cockroach/pkg/cmd/roachtest/tests/failover.go:290
	            				main/pkg/cmd/roachtest/monitor.go:105
	            				golang.org/x/sync/errgroup/external/org_golang_x_sync/errgroup/errgroup.go:75
	            				GOROOT/src/runtime/asm_amd64.s:1594
	Error:      	Received unexpected error:
	            	pq: query execution canceled
	Test:       	failover/chaos/read-write
(require.go:1360).NoError: FailNow called
(cluster.go:2095).Run: output in run_135504.835106872_n10_cockroach-workload-r: ./cockroach workload run kv --read-percent 50 --write-seq R0 --duration 45m --concurrency 256 --max-rate 8192 --timeout 1m --tolerate-errors --histograms=perf/stats.json {pgurl:1-2} returned: context canceled
(monitor.go:127).Wait: monitor failure: monitor task failed: t.Fatal() was called
(cluster.go:2095).Run: cluster.RunE: context canceled
(cluster.go:2095).Run: cluster.RunE: context canceled
(cluster.go:2095).Run: cluster.RunE: context canceled
(cluster.go:2095).Run: cluster.RunE: context canceled
```
<p>Parameters: <code>ROACHTEST_cloud=gce</code>
, <code>ROACHTEST_cpu=4</code>
, <code>ROACHTEST_encrypted=false</code>
, <code>ROACHTEST_fs=ext4</code>
, <code>ROACHTEST_localSSD=false</code>
, <code>ROACHTEST_ssd=0</code>
</p>
<details><summary>Help</summary>
<p>

See: [roachtest README](https://github.com/cockroachdb/cockroach/blob/master/pkg/cmd/roachtest/README.md)

See: [How To Investigate \(internal\)](https://cockroachlabs.atlassian.net/l/c/SSSBr8c7)

</p>
</details>
/cc @cockroachdb/kv-triage
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*failover/chaos/read-write.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)
</sub>

Jira issue: CRDB-28371

Epic CRDB-27234

### PR DESCRIPTION
**Pull request by erikgrinaker**
The deadlock failure mode used `SHOW RANGES` to fetch range and lease information from the cluster. However, if this was run concurrently with other failures in chaos tests it could hang and time out, since it needed to read lease information from each individual range.

This patch restructures the deadlock failure mode to fetch range/lease information from the cluster before running failures, and skipping any replicas that have since moved.

Resolves #104045.
Resolves #104086.
Resolves #104140.
Resolves #104144.

Epic: none
Release note: None

### CODE REVIEW

File: pkg/cmd/roachtest/tests/failover.go [hunk 1]
```diff
@@ -253,7 +255,7 @@ func runFailoverChaos(
 					}
 				}
 				if d, ok := failer.(*deadlockFailer); ok { // randomize deadlockFailer
-					d.numReplicas = 1 + rng.Intn(3)
```
Comment (tbg) [inline pkg/cmd/roachtest/tests/failover.go:256]: Random fix?

**Review by tbg — APPROVED** [review]

**Comment by erikgrinaker** [comment]
TFTR!

bors r+
