### PR TITLE
cli: quit command waits for server shutdown

### LINKED ISSUE #6585: cli: `cockroach quit` should wait until the server has effectively stopped
Scripts like e.g. the Jepsen tests will start and then restart a server. Now if the following commands are issued quickly in sequence:

```
cockroach start
cockroach quit
cockroach start
```

then the 3rd sometimes fails with an error "the server is already started". This is because "quit" merely issues a termination request and terminates (and gives control back to the shell) before the db server has effectively terminated. 

Script writers need a way to synchronize on the termination of the db server. The easiest way forward would be to have "quit" wait until the shutdown request has been processed and the connection to the server is lost.

Reported by @dationl.

### PR DESCRIPTION
**Pull request by tamird**
Closes #6585.

---

This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/7603)

### CODE REVIEW

File: server/admin.go [hunk 1]
```diff
@@ -668,21 +668,31 @@ func (s *adminServer) Drain(ctx context.Context, req *serverpb.DrainRequest) (*s
...
-			time.Sleep(50 * time.Millisecond)
-			s.server.stopper.Stop()
-		}()
+		go s.server.stopper.Stop()
+	}
+
+	ctx := stream.Context()
+
+	select {
+	case <-s.server.stopper.IsStopped():
```
Comment (tschottdorf) [inline server/admin.go]: Does the stopper close all the listeners? And the connection is still available and can communicate with the client?

Comment (tamird) [inline server/admin.go]: Yes, the stopper closes the connection - see the code on the client side that expressly waits for this to happen.

Comment (tschottdorf) [inline server/admin.go]: If the stopper closes the connection first and then stops some other stuff after, why does the client know that the server has completely terminated by the time its connection is closed? I see what the intention of the code is, but I don't see at all why it works.

Comment (tamird) [inline server/admin.go]: All those things happen already after the stopper is `Quiesce()`d and `Wait()`ed, so yes, there's a race here, but all the stopper is doing before process death is:
```
	for _, c := range s.closers {
		c.Close()
	}
	close(s.stopped)
```

There's a race here, but I just don't see how we can do any better (short of adding yet another phase to the stopper so that connections are the last thing to go).

**Comment by tschottdorf** [comment]
I just can't convince myself that there isn't a race that actually makes the shutdown experience worse. A clean solution would close all the server listeners (and generally file descriptors) first, and then the client connection (as you point out above).
That said, if you and @knz are convinced that nothing funky can happen and that this is a strict improvement, it'll do for me.

**Comment by tamird** [comment]
Well, I do think it's a strict improvement. Do I have your blessing to merge?

**Comment by tschottdorf** [comment]
I don't see much won here except a chance for random errors on shutdown, so
I'd like to defer that decision to @knz (who likely feels more strongly
about this going in than I do).

On Sat, Jul 2, 2016 at 10:53 AM Tamir Duberstein <notifications@github.com>
wrote:

> Well, I do think it's a strict improvement. Do I have your blessing to
> merge?
>
> —
> You are receiving this because you were assigned.
> Reply to this email directly, view it on GitHub
> <https://github.com/cockroachdb/cockroach/pull/7603#issuecomment-230105546>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AE135PyXmnR-OLMY0z0xDEFiJgar8qjdks5qRnttgaJpZM4JDlxi>
> .
>
-- 

-- Tobias

**Comment by knz** [comment]
I do not really like the complexity added by this PR. In my view the simpler approach would be to:

1. client sends drain message, waits for shutdownReady
2. server processes drain locally; when the drain is completed, server sends a shutdownReady to the client, waits for Ack
3. the client sends Ack back to the server
4. server issues os.Exit
4. meanwhile client waits for socket to close remotely (which will be an acknowledgement from the server OS that the server process has died!)

---

Review status: 0 of 5 files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[cli/start.go, line 521 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7603#-KLg7EU-ZFj1GuQYRsHn:-KLg7EU0oyLUwX7Q1WXQ:1987087925) ([raw file](https://github.com/cockroachdb/cockroach/blob/0f02832a4cdf922dbabcd5ab90f93651e681bfc9/cli/start.go#L521)):*
> ```Go
> 				fmt.Println("ok")
> 			}
> 			return err
> ```

I do not like the meaning of encountering an error here. What is the state of the server then?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7603#-:-KLg7otbfJMio75DPAov:1228127414)*

**Comment by bdarnell** [comment]
Introducing bidirectional communication to the `quit` command seems a lot more complex than what's being changed here (a server that has drained but is unable to exit and restart due to an unresponsive client would be a bad failure mode). This change isn't perfect, but it looks like the best we can do with a reasonable amount of effort. LGTM.

---

Review status: 0 of 5 files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[cli/start.go, line 521 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7603#-KLg7EU-ZFj1GuQYRsHn:-KLujoOAlIXA94JXf8_6:-822398131) ([raw file](https://github.com/cockroachdb/cockroach/blob/0f02832a4cdf922dbabcd5ab90f93651e681bfc9/cli/start.go#L521)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary>
> I do not like the meaning of encountering an error here. What is the state of the server then?
</details>
If an error occurs during `quit`, the state of the server is unknown. What else could we do?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7603#-:-KLujzoEg1svyr1J7ZLP:-134485928)*

**Comment by knz** [comment]
As I explained to tamir I do not have a better solution in mind. So of course I'll sign off on this since it brings us closer to a solution. See my comments about code structure below however.

---

Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, 4 unresolved discussions, all commit checks successful.

---

*[cli/start.go, line 526 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7603#-KLwEjybJtelWXD_8qFC:-KLwEjybJtelWXD_8qFD:49508043) ([raw file](https://github.com/cockroachdb/cockroach/blob/0f02832a4cdf922dbabcd5ab90f93651e681bfc9/cli/start.go#L526)):*
> ```Go
> 	}
> 
> 	{
> ```

I;d suggest turning this entire block into its own function and call the same functions 2 times. The code replication here is unnerving.

---

*[cli/start.go, line 528 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7603#-KLwEdoM798_fs8xo94I:-KLwEdoM798_fs8xo94J:-2053876355) ([raw file](https://github.com/cockroachdb/cockroach/blob/0f02832a4cdf922dbabcd5ab90f93651e681bfc9/cli/start.go#L528)):*
> ```Go
> 	{
> 		stream, err := c.Drain(ctx, &serverpb.DrainRequest{
> 			Shutdown: true,
> ```

Please add a comment here to remind the reader why not having "onModes" means the server should perform a hard shutdown.

---

*[server/admin.go, line 691 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7603#-KLdceMhzhP2Ciba0GHB-r1-691:-KLwF7mQR-0GngYBmFCw:-1202467833) ([raw file](https://github.com/cockroachdb/cockroach/blob/0f02832a4cdf922dbabcd5ab90f93651e681bfc9/server/admin.go#L691)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> All those things happen already after the stopper is `Quiesce()`d and `Wait()`ed, so all the stopper is doing before process death is:
> 
> ```
> 
> 	for _, c := range s.closers {
> 
> 		c.Close()
> 
> 	}
> 
> 	close(s.stopped)
> 
> ```
> 
> 
> 
> There's a race here, but I just don't see how we can do any better (short of adding yet another phase to the stopper so that connections are the last thing to go).
</details>
How much work would the additional phase mean?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7603#-:-KLwET_hP5Ba7twgPNyv:1924727429)*

**Comment by tamird** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions, all commit checks successful.

---

*[cli/start.go, line 526 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7603#-KLwEjybJtelWXD_8qFC:-KLwHB_AQ-g-NYG-ASrn:2054961014) ([raw file](https://github.com/cockroachdb/cockroach/blob/0f02832a4cdf922dbabcd5ab90f93651e681bfc9/cli/start.go#L526)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary>
> I;d suggest turning this entire block into its own function and call the same functions 2 times. The code replication here is unnerving.
</details>
Please suggest some code. I looked at this for a while and failed to find an adequate refactor.

---

*[cli/start.go, line 528 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7603#-KLwEdoM798_fs8xo94I:-KLwHFiYf5Q1-xDj0py3:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/0f02832a4cdf922dbabcd5ab90f93651e681bfc9/cli/start.go#L528)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary>
> Please add a comment here to remind the reader why not having "onModes" means the server should perform a hard shutdown.
</details>
Done.

---

*[server/admin.go, line 691 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7603#-KLdceMhzhP2Ciba0GHB-r1-691:-KLwGa9s578h-mxcVScO:-1552112268) ([raw file](https://github.com/cockroachdb/cockroach/blob/0f02832a4cdf922dbabcd5ab90f93651e681bfc9/server/admin.go#L691)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary>
> How much work would the additional phase mean?
</details>
Worse than the work that it would require is that it would further complicate the stopper, which I'd quite like to avoid.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7603)*

**Comment by knz** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

*[cli/start.go, line 526 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7603#-KLwEjybJtelWXD_8qFC:-KLwsBt-I0GKyZfNGtka:-1368657162) ([raw file](https://github.com/cockroachdb/cockroach/blob/0f02832a4cdf922dbabcd5ab90f93651e681bfc9/cli/start.go#L526)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> Please suggest some code. I looked at this for a while and failed to find an adequate refactor.
</details>
What about this:

```go
func waitForShutdown(stream serverpb.Admin_DrainClient) error {
        for {
                if _, err := stream.Recv(); !grpcutil.IsClosedConnection(err) {
                        return err
                }
                return nil
        }
}

func doShutdown(onModes []int32) error {
        stream, err := c.Drain(ctx, &serverpb.DrainRequest{
                On:       onModes,
                Shutdown: true,
        })
        if err != nil {
                return err
        }
        _, err = stream.Recv()
        if err == nil {
                err = waitForShutdown(stream)
                if err == nil {
                        fmt.Println("ok")
                }
                return err
        }
        return nil
}
func blah() {
        if err := doShutdown(onModes); err != nil {
                fmt.Printf("graceful shutdown failed, proceeding with hard shutdown: %v\n", err)

                // Not passing drain modes so the server doesn't bother and goes
                // straight to shutdown.
                if err := doShutdown(nil); err != nil {
                        return fmt.Errorf("hard shutdown failed: %v", err)
                }
        }
        return nil
}
```

---

*[server/admin.go, line 691 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7603#-KLdceMhzhP2Ciba0GHB-r1-691:-KLwsidp9x4gX8FEP_4N:219636691) ([raw file](https://github.com/cockroachdb/cockroach/blob/0f02832a4cdf922dbabcd5ab90f93651e681bfc9/server/admin.go#L691)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> Worse than the work that it would require is that it would further complicate the stopper, which I'd quite like to avoid.
</details>
Ok I see. Fine with me.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7603)*

**Comment by tamird** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

*[cli/start.go, line 526 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7603#-KLwEjybJtelWXD_8qFC:-KLwvMpHPBw4Qtx9Cdsx:-1052887719) ([raw file](https://github.com/cockroachdb/cockroach/blob/0f02832a4cdf922dbabcd5ab90f93651e681bfc9/cli/start.go#L526)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary>
> What about this:
> 
> ```go
> func waitForShutdown(stream serverpb.Admin_DrainClient) error {
>         for {
>                 if _, err := stream.Recv(); !grpcutil.IsClosedConnection(err) {
>                         return err
>                 }
>                 return nil
>         }
> }
> 
> func doShutdown(onModes []int32) error {
>         stream, err := c.Drain(ctx, &serverpb.DrainRequest{
>                 On:       onModes,
>                 Shutdown: true,
>         })
>         if err != nil {
>                 return err
>         }
>         _, err = stream.Recv()
>         if err == nil {
>                 err = waitForShutdown(stream)
>                 if err == nil {
>                         fmt.Println("ok")
>                 }
>                 return err
>         }
>         return nil
> }
> func blah() {
>         if err := doShutdown(onModes); err != nil {
>                 fmt.Printf("graceful shutdown failed, proceeding with hard shutdown: %v\n", err)
> 
>                 // Not passing drain modes so the server doesn't bother and goes
>                 // straight to shutdown.
>                 if err := doShutdown(nil); err != nil {
>                         return fmt.Errorf("hard shutdown failed: %v", err)
>                 }
>         }
>         return nil
> }
> ```
</details>
Not equivalent. If `stream.Recv` returns an error (the first time), doShutdown will return `nil` and this whole thing will do the wrong thing.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7603)*
