### PR TITLE
sql: cache role existence checks to fix perf regression

### LINKED ISSUE #112102: sql: 23.2 performance regression caused by role existence checks
In https://github.com/cockroachdb/cockroach/commit/12ec26ff28294a8c9e0f89b3dbcc2c60910fd8e5, we started to check for the existence of a role whenever a privilege for the public role was checked. This can hapen multiple times during some pg_catalog queries, so it introduced a performance regression.

The change in https://github.com/cockroachdb/cockroach/pull/111819 revealed the regression - once the tests were changed to use a non-root user (which is how most users will interact with CRDB), the number of round trips required by most of the queries increased.

Jira issue: CRDB-32236

### PR DESCRIPTION
**Pull request by rafiss**
In 12ec26ff28294a8c9e0f89b3dbcc2c60910fd8e5, we started to check for the existence of a role whenever a privilege for the public role was checked. This can hapen multiple times during some pg_catalog queries, so it introduced a performance regression.

Now, the role existence is cached so we avoid the penalty. The existence of a role is cached for the duration of the entire transaction, and also gets inherited by any internal executor used to implement a command run by the user's transaction.

No release note since this is new in 23.2.

informs https://github.com/cockroachdb/cockroach/issues/20718
fixes https://github.com/cockroachdb/cockroach/issues/112102
Release note: None

### CODE REVIEW

File: pkg/sql/user.go [hunk 1]
```diff
@@ -473,9 +473,20 @@ func (p *planner) GetAllRoles(ctx context.Context) (map[username.SQLUsername]boo
 	return users, nil
 }
 
-// RoleExists returns true if the role exists.
+// RoleExists returns true if the role exists. If a role is found to exist,
+// the existence will be cached for the duration of the transaction.
 func (p *planner) RoleExists(ctx context.Context, role username.SQLUsername) (bool, error) {
-	return RoleExists(ctx, p.InternalSQLTxn(), role)
+	cache := p.EvalContext().RoleExistsCache
+	if cache != nil {
```
Comment (ecwall) [inline pkg/sql/user.go:480]: What causes the cache to be nil here?

Comment (rafiss) [reply pkg/sql/user.go:480]: it shouldn't be nil, it was just a defensive check

Comment (ecwall) [reply pkg/sql/user.go:480]: IMO defensive checks like this make the code harder to maintain because it is hard to tell the difference between something that is expected to be nil and a bug, but I'll leave it up to you if you want to keep it.

**Review by ecwall — APPROVED** [review]

**Comment by rafiss** [comment]
tftr

bors r+
