### PR TITLE
sql: fix pg_catalog.pg_proc(proretset) column

### LINKED ISSUE #132733: Some set-returning function is not being marked as `proretset` in table `pg_proc`.
**Describe the problem**

Some set-returning function is not being marked as `proretset` in table `pg_proc`.

**To Reproduce**
```sql
select proname, proretset, prorettype from pg_proc 
       where proname='jsonb_object_keys' or proname='generate_series' or proname='generate_subscripts' order by 1;

/* result:
       proname       | proretset | prorettype 
---------------------+-----------+------------
 generate_series     | f         |         20
 generate_series     | f         |         20
 generate_series     | f         |       1114
 generate_series     | f         |       1184
 generate_subscripts | f         |         20
 generate_subscripts | f         |         20
 generate_subscripts | f         |         20
 jsonb_object_keys   | f         |         25
(8 rows)
*/
```

**Expected behavior**
```sql
select proname, proretset, prorettype from pg_proc 
       where proname='jsonb_object_keys' or proname='generate_series' or proname='generate_subscripts' order by 1;

/* result:
       proname       | proretset | prorettype 
---------------------+-----------+------------
 generate_series     | t         |       1114
 generate_series     | t         |       1184
 generate_series     | t         |         23
 generate_series     | t         |         23
 generate_series     | t         |         20
 generate_series     | t         |         20
 generate_series     | t         |       1700
 generate_series     | t         |       1700
 generate_subscripts | t         |         23
 generate_subscripts | t         |         23
 jsonb_object_keys   | t         |         25
(11 rows)
*/
```

**Environment:**
 - CockroachDB CCL v24.1.4 (x86_64-pc-linux-gnu, built 2024/08/26 19:15:49, go1.22.5 X:nocoverageredesign)
 - Server OS: Ubuntu 22.04
 - Client app: psql

Jira issue: CRDB-43247

Epic CRDB-40419

### PR DESCRIPTION
**Pull request by rafiss**
This column was populated incorrectly ever since 3867776 was merged.
It had an overly sensitive condition that made it only get set if the
function returned tuples.

fixes https://github.com/cockroachdb/cockroach/issues/132733
Release note (bug fix): The proretset column of the pg_catalog.pg_proc
table is now properly set to true for set-returning builtin functions.

### CODE REVIEW

File: pkg/sql/sem/builtins/builtins.go [hunk 1]
```diff
@@ -9948,6 +9951,51 @@ var jsonArrayLengthImpl = tree.Overload{
...
+	// inputs.
+	CalledOnNullInput: true,
+	FnWithExprs: eval.FnWithExprsOverload(func(ctx context.Context, evalCtx *eval.Context, args tree.Exprs) (tree.Datum, error) {
+		tuple, j, err := jsonPopulateRecordEvalArgs(ctx, evalCtx, args)
+		if err != nil {
+			return nil, err
+		}
+		if j != nil {
+			if j.Type() != json.ObjectJSONType {
+				return nil, pgerror.Newf(pgcode.InvalidParameterValue, "argument of json_populate_record must be an object")
```
Comment (annrpom) [inline pkg/sql/sem/builtins/builtins.go:9983]: nit: i don't see any test for this case; can we add one? ignore if i just didn't search properly!

File: pkg/sql/logictest/testdata/logic_test/pg_catalog [hunk 2]
```diff
@@ -2577,6 +2577,27 @@ substring  true         false      i            NULL
...
 
+# Verify that proretset is true for set-returning functions.
+query OTBT
+SELECT oid, proname, proretset, prorettype FROM pg_catalog.pg_proc
+WHERE proname IN (
+  'jsonb_object_keys', 'generate_series', 'generate_subscripts',
+  'json_populate_recordset', 'unnest', 'json_each'
+) ORDER BY 1
+----
+317  generate_series          true  20
```
Comment (annrpom) [inline pkg/sql/logictest/testdata/logic_test/pg_catalog:2588]: are these oids deterministic?

**Review by annrpom — APPROVED** [review]
:lgtm:

File: pkg/sql/logictest/testdata/logic_test/pg_catalog (hunk 2 above)
Comment (rafiss) [reply pkg/sql/logictest/testdata/logic_test/pg_catalog:2588]: yeah they are for builtins, thanks to: https://github.com/cockroachdb/cockroach/blob/9f61a38b670e57873509568f67bb665e50cd1935/pkg/sql/sem/builtins/fixed_oids.go#L15-L27

Comment (annrpom) [reply pkg/sql/logictest/testdata/logic_test/pg_catalog:2588]: oh pffft right; ty

File: pkg/sql/sem/builtins/builtins.go (hunk 1 above)
Comment (rafiss) [reply pkg/sql/sem/builtins/builtins.go]: i just moved this code from a different file. however, looks like the second commit causes other issues so i'll take it out of this PR.

i have added a test for this error now though!

**Comment by rafiss** [comment]
tftr!

bors r+
