### PR TITLE
sql: make aggregate builtins share the same memory account

### LINKED ISSUE #46664: roachtest: tpchvec/perf failed
[(roachtest).tpchvec/perf failed](https://teamcity.cockroachdb.com/viewLog.html?buildId=1832621&tab=buildLog) on [master@c0855e9fcf979cca1094d7edeeacb9882ddc9f96](https://github.com/cockroachdb/cockroach/commits/c0855e9fcf979cca1094d7edeeacb9882ddc9f96):

```
The test failed on branch=master, cloud=gce:
test artifacts and logs in: /home/agent/work/.go/src/github.com/cockroachdb/cockroach/artifacts/20200327-1832621/tpchvec/perf/run_1
	tpchvec.go:579,tpchvec.go:660,test_runner.go:753: error with attached stack trace:
		    main.execCmdWithBuffer
		    	/home/agent/work/.go/src/github.com/cockroachdb/cockroach/pkg/cmd/roachtest/cluster.go:426
		    main.(*cluster).RunWithBuffer
		    	/home/agent/work/.go/src/github.com/cockroachdb/cockroach/pkg/cmd/roachtest/cluster.go:2031
		    main.registerTPCHVec.func1
		    	/home/agent/work/.go/src/github.com/cockroachdb/cockroach/pkg/cmd/roachtest/tpchvec.go:574
		    main.registerTPCHVec.func2
		    	/home/agent/work/.go/src/github.com/cockroachdb/cockroach/pkg/cmd/roachtest/tpchvec.go:660
		    main.(*testRunner).runTest.func2
		    	/home/agent/work/.go/src/github.com/cockroachdb/cockroach/pkg/cmd/roachtest/test_runner.go:753
		    runtime.goexit
		    	/usr/local/go/src/runtime/asm_amd64.s:1357
		  - error with embedded safe details: %s
		    -- arg 1: <string>
		  - /home/agent/work/.go/src/github.com/cockroachdb/cockroach/bin/roachprod run teamcity-1832621-1585293773-20-n3cpu4:1 -- ./workload run tpch --concurrency=1 --db=tpch --max-ops=3 --queries=20 --vectorize=off {pgurl:1-3}:
		  - exit status 30

```

<details><summary>More</summary><p>

Artifacts: [/tpchvec/perf](https://teamcity.cockroachdb.com/viewLog.html?buildId=1832621&tab=artifacts#/tpchvec/perf)
Related:
- #46663 roachtest: tpchvec/perf failed  [C-test-failure](https://api.github.com/repos/cockroachdb/cockroach/labels/C-test-failure) [O-roachtest](https://api.github.com/repos/cockroachdb/cockroach/labels/O-roachtest) [O-robot](https://api.github.com/repos/cockroachdb/cockroach/labels/O-robot) [branch-release-19.2](https://api.github.com/repos/cockroachdb/cockroach/labels/branch-release-19.2) [release-blocker](https://api.github.com/repos/cockroachdb/cockroach/labels/release-blocker)

[See this test on roachdash](https://roachdash.crdb.dev/?filter=status%3Aopen+t%3A.%2Atpchvec%2Fperf.%2A&sort=title&restgroup=false&display=lastcommented+project)
<sub>powered by [pkg/cmd/internal/issues](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)</sub></p></details>

### PR DESCRIPTION
**Pull request by yuzefovich**
Release justification: fixes for high-priority or high-severity
bugs in existing functionality (we could hit memory limit due to
accounting long before the available RAM is actually used up).

We recently fixed a couple of leaks in memory accounting by aggregate
builtins. It was done in the same way that other similar aggregates were
doing - by instantiating a separate memory account for each aggregate
struct. However, when a single aggregate, say `anyNotNull`, wants to
store a single datum, say `DInt` of size 8 bytes, when growing its own
memory account will actually make a reservation of
`mon.DefaultPoolAllocation = 10240` bytes although we will only be using
8 bytes. This can result in "memory-starvation" for OLAP-y queries
because we're likely to hit `max-sql-memory` limit long before we're
getting close to it because of such "overestimation" in the accounting.

This commit fixes this problem by making all aggregates that aggregate
a single datum (these are all aggregate builtins that perform memory
accounting except for `arrayAgg` which works with multiple datums) to
share the same memory account (when non-nil) which is plumbed via
`tree.EvalContext` (this is unfortunate but, as always, seems like
necessary evil). That account is instantiated by `rowexec.aggregator`
and `rowexec.windower` processors. Also it is acceptable from the
concurrency's point of view because the processors run in a single
goroutine, so we will never have concurrent calls to grow/shrink this
shared memory account.

If for some reason the field for shared memory account is nil in the
eval context, then we will fallback to old behavior of instantiating
a memory account for each aggregate builtin struct. A helper struct was
created (that is now embedded by all aggregate builtins in question)
that unifies the memory accounting.

Fixes: #46664.

Release note: None (a follow-up to a recent PR).

### CODE REVIEW

**Review by asubiotto — CHANGES_REQUESTED** [review]
What about other aggregate functions that use a memory account ( e.g. array agg and bytes concat), should those be changed too?

> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/46700#-:-M3elnt33F_GpOI8Vhvq:b-bvdqji)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jordanlewis and @yuzefovich)

___
*[pkg/sql/rowexec/aggregator.go, line 341 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/46700#-M3eildh0nXpu0xSs2ly:-M3eildh0nXpu0xSs2lz:bo9525a) ([raw file](https://github.com/cockroachdb/cockroach/blob/d63022b9e80cb04e028375dd3d79fde5ad45e137/pkg/sql/rowexec/aggregator.go#L341)):*
> ```Go
> 	}
> 
> 	ag.EvalCtx.SingleDatumAggMemAccount = &ag.aggFuncsAcc
> ```

Do we make a copy of this eval ctx before setting this field?
___
*[pkg/sql/sem/builtins/aggregate_builtins.go, line 490 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/46700#-M3ek52C6NzQymnxF7gb:-M3ek52C6NzQymnxF7gc:b-tncigr) ([raw file](https://github.com/cockroachdb/cockroach/blob/d63022b9e80cb04e028375dd3d79fde5ad45e137/pkg/sql/sem/builtins/aggregate_builtins.go#L490)):*
> ```Go
> type anyNotNullAggregate struct {
> 	val       tree.Datum
> 	acc       *mon.BoundAccount
> ```

Not sure if this makes sense but there seems to be a lot of duplicated logic. Would it be possible to extract this and datum size into a utility struct that takes care of the account resizing/closing details?
___
*[pkg/sql/sem/builtins/aggregate_builtins.go, line 546 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/46700#-M3elB4-2BxxrVnyQfzC:-M3elB4-2BxxrVnyQfzD:bnetwg7) ([raw file](https://github.com/cockroachdb/cockroach/blob/d63022b9e80cb04e028375dd3d79fde5ad45e137/pkg/sql/sem/builtins/aggregate_builtins.go#L546)):*
> ```Go
> func (a *anyNotNullAggregate) Reset(ctx context.Context) {
> 	a.val = tree.DNull
> 	if a.acc != nil && a.datumSize != 0 {
> ```

Why is it ok to have a nil acc here but not in `Add`?
___
*[pkg/sql/sem/builtins/aggregate_builtins.go, line 1215 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/46700#-M3ejty7EjIIOn6XYabx:-M3ejty7EjIIOn6XYaby:b-5cu73c) ([raw file](https://github.com/cockroachdb/cockroach/blob/d63022b9e80cb04e028375dd3d79fde5ad45e137/pkg/sql/sem/builtins/aggregate_builtins.go#L1215)):*
> ```Go
> 			oldDatumSize := a.datumSize
> 			a.datumSize = int64(datum.Size())
> 			if err := a.acc.Grow(ctx, a.datumSize-oldDatumSize); err != nil {
> ```

I think this is allowed but makes me wonder why we have both `Grow` and `Shrink` if the former accepts a negative argument.

**Review by yuzefovich — COMMENTED** [review]
I think `arrayAgg` is special because it operates on multiple datums, and it might be benefiting from having its own account. I also initially thought that concat and json aggregates should have their own accounts since they might be using non-trivial amount of memory, but it probably makes sense to unify them with others as well since they do aggregate into a single - possibly very large - datum. Done.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/46700#-:-M3gRZz70WfKoi9IS-mO:b1zq5vs)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto and @jordanlewis)

___
*[pkg/sql/rowexec/aggregator.go, line 341 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/46700#-M3eildh0nXpu0xSs2ly:-M3g5y3wCZOG4x9XWcQO:bml9ntp) ([raw file](https://github.com/cockroachdb/cockroach/blob/d63022b9e80cb04e028375dd3d79fde5ad45e137/pkg/sql/rowexec/aggregator.go#L341)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

Do we make a copy of this eval ctx before setting this field?
</blockquote></details>

A new eval context is created in `aggregatorBase.init` when calling `ag.ProcessorBase.Init`. Added a comment.
___
*[pkg/sql/sem/builtins/aggregate_builtins.go, line 490 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/46700#-M3ek52C6NzQymnxF7gb:-M3goDwm3ePNbiWSbbWW:b-xwi88q) ([raw file](https://github.com/cockroachdb/cockroach/blob/d63022b9e80cb04e028375dd3d79fde5ad45e137/pkg/sql/sem/builtins/aggregate_builtins.go#L490)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

Not sure if this makes sense but there seems to be a lot of duplicated logic. Would it be possible to extract this and datum size into a utility struct that takes care of the account resizing/closing details?
</blockquote></details>

I was thinking about it myself but initially thought that this would give much benefit, but I like it how it turned out, done.
___
*[pkg/sql/sem/builtins/aggregate_builtins.go, line 546 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/46700#-M3elB4-2BxxrVnyQfzC:-M3goFw3CpJrBNdroCTk:beoaz7a) ([raw file](https://github.com/cockroachdb/cockroach/blob/d63022b9e80cb04e028375dd3d79fde5ad45e137/pkg/sql/sem/builtins/aggregate_builtins.go#L546)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

Why is it ok to have a nil acc here but not in `Add`?
</blockquote></details>

I don't know, I wanted to be on the safe side, but I agree, this was ill-designed. Refactored.
___
*[pkg/sql/sem/builtins/aggregate_builtins.go, line 1215 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/46700#-M3ejty7EjIIOn6XYabx:-M3g6cFRCpbDR0UyfEr0:bizi7j4) ([raw file](https://github.com/cockroachdb/cockroach/blob/d63022b9e80cb04e028375dd3d79fde5ad45e137/pkg/sql/sem/builtins/aggregate_builtins.go#L1215)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

I think this is allowed but makes me wonder why we have both `Grow` and `Shrink` if the former accepts a negative argument.
</blockquote></details>

The difference is that if we're `Grow`ing by negative amount, then the memory account's `used` and `reserved` fields will be updated accordingly, but we *will not* release any reservations to the monitor while when `Shrink`ing we *might* release some amount of memory and, thus, reducing `reserved` field.

File: pkg/sql/sem/builtins/aggregate_builtins.go [hunk 1]
```diff
@@ -477,10 +477,98 @@ const sizeOfJSONAggregate = int64(unsafe.Sizeof(jsonAggregate{}))
...
+// otherwise, it is grown by newUsage.
+func (b singleDatumAggregateBase) updateMemoryUsage(ctx context.Context, newUsage int64) error {
+	if err := b.acc.Grow(ctx, newUsage-b.accountedFor); err != nil {
+		return err
+	}
+	b.accountedFor = newUsage
+	return nil
+}
+
+func (b singleDatumAggregateBase) reset(ctx context.Context) {
```
Comment (asubiotto) [inline pkg/sql/sem/builtins/aggregate_builtins.go]: I think the receivers in these methods need to be pointers otherwise `accountedFor` won't be updated correctly.

**Review by asubiotto — CHANGES_REQUESTED** [review]

**Review by yuzefovich — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/46700)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto and @jordanlewis)

___
*[pkg/sql/sem/builtins/aggregate_builtins.go, line 543 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/46700#-M3T9lQqyUk8iBzESaB6-r2-543:-M3kvCrp3QDxhw5H9lcA:b-uty89d) ([raw file](https://github.com/cockroachdb/cockroach/blob/a5c68f95ccb446c0ec74f4eacecd0345ea6121b0/pkg/sql/sem/builtins/aggregate_builtins.go#L543)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

I think the receivers in these methods need to be pointers otherwise `accountedFor` won't be updated correctly.
</blockquote></details>

I think you're right, fixed.

**Review by asubiotto — APPROVED** [review]
:lgtm: 

> Reviewed 2 of 3 files at r2, 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/46700#-:-M3kvi1F6LgpEVMXEWe9:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @asubiotto and @jordanlewis)

**Comment by yuzefovich** [comment]
TFTR!

bors r+
