### PR TITLE
sql: fix detection of number of input values vs. columns with DEFAULT expressions.

### LINKED ISSUE #7862: sql: panic on INSERT: runtime error: index out of range
```
CREATE DATABASE d;
SET DATABASE = d;
CREATE TABLE ident ();
INSERT INTO ident AS TIME VALUES ( TRUE , DEFAULT ) ORDER BY TRUE , TRUE DESC OFFSET TRUE LIMIT TRUE;
```

Panics the server:

```
panic: runtime error: index out of range

goroutine 229 [running]:
panic(0x18a7020, 0xc82000e130)
	/usr/local/go/src/runtime/panic.go:481 +0x3e6
github.com/cockroachdb/cockroach/sql.(*planner).fillDefaults(0xc820394890, 0xc8202e6a30, 0x1, 0x1, 0xc82000b140, 0x1, 0x1, 0xc8202a0a50, 0x0, 0x0, ...)
	/go/src/github.com/cockroachdb/cockroach/sql/insert.go:391 +0xe2e
github.com/cockroachdb/cockroach/sql.(*planner).Insert(0xc820394890, 0xc8202a0a50, 0x0, 0x0, 0x0, 0xc8202a2f01, 0x0, 0x0, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/sql/insert.go:122 +0x7a8
github.com/cockroachdb/cockroach/sql.(*planner).newPlan(0xc820394890, 0x7fc1bb66d3e8, 0xc8202a0a50, 0x0, 0x0, 0x0, 0x25f94601, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/cockroachdb/cockroach/sql/plan.go:260 +0x1535
github.com/cockroachdb/cockroach/sql.(*planner).makePlan(0xc820394890, 0x7fc1bb66d3e8, 0xc8202a0a50, 0x83fb01, 0x0, 0x0, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/sql/plan.go:212 +0x83
github.com/cockroachdb/cockroach/sql.(*Executor).execStmt(0xc8200a6000, 0x7fc1bb66d3e8, 0xc8202a0a50, 0xc820394890, 0xc8202a0a01, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/cockroachdb/cockroach/sql/executor.go:1045 +0x93
github.com/cockroachdb/cockroach/sql.(*Executor).execStmtInOpenTxn(0xc8200a6000, 0x7fc1bb66d3e8, 0xc8202a0a50, 0xc820394890, 0x101, 0xc820394828, 0x0, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/cockroachdb/cockroach/sql/executor.go:943 +0x439
github.com/cockroachdb/cockroach/sql.(*Executor).execStmtsInCurrentTxn(0xc8200a6000, 0xc820582730, 0x1, 0x1, 0xc820394890, 0xc820394828, 0x1fe0101, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/cockroachdb/cockroach/sql/executor.go:691 +0x5da
github.com/cockroachdb/cockroach/sql.runTxnAttempt(0xc8200a6000, 0xc820394890, 0x1, 0xc820394828, 0xc820828580, 0xc820582730, 0x1, 0x1, 0x0, 0x0, ...)
	/go/src/github.com/cockroachdb/cockroach/sql/executor.go:619 +0x18d
github.com/cockroachdb/cockroach/sql.(*Executor).execRequest.func2(0xc820359e40, 0xc820828580, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/sql/executor.go:511 +0x470
github.com/cockroachdb/cockroach/internal/client.(*Txn).Exec(0xc820359e40, 0xc820450101, 0x1461fececbe63048, 0x0, 0xc820459380, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/internal/client/txn.go:548 +0x2eb
github.com/cockroachdb/cockroach/sql.(*Executor).execRequest(0xc8200a6000, 0x7fc1bc800908, 0xc820583f80, 0xc820394800, 0xc8207ce02d, 0xa0, 0x0, 0x0, 0x0, 0xc8207ce000)
	/go/src/github.com/cockroachdb/cockroach/sql/executor.go:516 +0xba7
github.com/cockroachdb/cockroach/sql.(*Executor).ExecuteStatements(0xc8200a6000, 0x7fc1bc800908, 0xc820583f80, 0xc820394800, 0xc8207ce02d, 0xa0, 0x0, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/cockroachdb/cockroach/sql/executor.go:382 +0xf6
github.com/cockroachdb/cockroach/sql/pgwire.(*v3Conn).executeStatements(0xc8204c2c00, 0x7fc1bc800908, 0xc820583f80, 0xc8207ce02d, 0xa0, 0x0, 0x0, 0x0, 0x0, 0x7fc1bc882201, ...)
	/go/src/github.com/cockroachdb/cockroach/sql/pgwire/v3.go:640 +0x98
github.com/cockroachdb/cockroach/sql/pgwire.(*v3Conn).handleSimpleQuery(0xc8204c2c00, 0x7fc1bc800908, 0xc820583f80, 0xc8204c2c28, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/sql/pgwire/v3.go:320 +0xe8
github.com/cockroachdb/cockroach/sql/pgwire.(*v3Conn).serve(0xc8204c2c00, 0xc82087e720, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/sql/pgwire/v3.go:275 +0x100c
github.com/cockroachdb/cockroach/sql/pgwire.(*Server).ServeConn(0xc8201cd740, 0x7fc1bc8c2800, 0xc8200b4300, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/sql/pgwire/server.go:229 +0x98f
github.com/cockroachdb/cockroach/server.(*Server).Start.func8.1(0x7fc1bc8c20d0, 0xc820400000)
	/go/src/github.com/cockroachdb/cockroach/server/server.go:370 +0x42
github.com/cockroachdb/cockroach/util/netutil.(*Server).ServeWith.func1(0xc8201341e0, 0x7fc1bc8c20d0, 0xc820400000, 0xc8204f8010)
	/go/src/github.com/cockroachdb/cockroach/util/netutil/net.go:131 +0x62
created by github.com/cockroachdb/cockroach/util/netutil.(*Server).ServeWith
	/go/src/github.com/cockroachdb/cockroach/util/netutil/net.go:133 +0x333
```

Found with the random syntax generator.

### PR DESCRIPTION
**Pull request by knz**
Fixes #7862.

---

This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/7868)

### CODE REVIEW

File: sql/insert.go [hunk 1]
```diff
@@ -139,7 +139,7 @@ func (p *planner) Insert(
 	}
 
 	if expressions := len(rows.Columns()); expressions > numInputColumns {
-		return nil, fmt.Errorf("INSERT has more expressions than target columns: %d/%d", expressions, numInputColumns)
+		return nil, fmt.Errorf("INSERT error: table %s has %d columns but %d values were supplied", n.Table, numInputColumns, expressions)
```
Comment (knz) [inline sql/insert.go]: Note: this is the error reported by SQLite, which I think is clearer.

**Comment by mjibson** [comment]
LGTM

---

Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[sql/insert.go, line 142 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7868#-KMubNYLU9s_NWeseGwH-r1-142:-KMwjVf1V9iR2CbcKiiV:1613188199) ([raw file](https://github.com/cockroachdb/cockroach/blob/1511899081a28cfa3db00608c4dde85427c8c0fd/sql/insert.go#L142)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary>
> Note: this is the error reported by SQLite, which I think is clearer.
</details>
Agree.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7868#-:-KMwjWyzr4APrUUjpIZ4:676834233)*
