### PR TITLE
release-2.1: sql: fix pg_catalog.pg_constraint's confkey column

### LINKED ISSUE #31545: SQL: Conkey and confkey values in pg_constraints have different number of elements
Dbeaver identified a potential CRDB bug in https://github.com/dbeaver/dbeaver/issues/4386#issuecomment-430512539:

`This happens because conkey and confkey values in pg_constraints have different number of elements.
In standard PG they always have equal size.

Looks like a bug in CC - the value in conkey seems to be equal to the number of columns in table's primary key. This happens only if foreign key columns are also part of primary key (like in stock or order_line tables).`

### PR DESCRIPTION
**Pull request by BramGruneir**
Backport 1/1 commits from #31610.

/cc @cockroachdb/release

---

Prior to this patch, all columns in the index were included instead of only the
ones being used in the foreign key reference.

Fixes #31545.

Release note (bug fix): Fix pg_catalog.pg_constraint's confkey column from
including columns that were not involved in the foreign key reference.

### CODE REVIEW

**Comment by BramGruneir** [comment]
DNM until after 2.1 release.

File: pkg/sql/pg_catalog.go [hunk 1]
```diff
@@ -680,7 +680,21 @@ CREATE TABLE pg_catalog.pg_constraint (
 					confupdtype = fkActionNone
 					confdeltype = fkActionNone
 					confmatchtype = fkMatchTypeSimple
-					if conkey, err = colIDArrayToDatum(con.Index.ColumnIDs); err != nil {
+					columnIDs := con.Index.ColumnIDs
+					if int(con.FK.SharedPrefixLen) > len(columnIDs) {
+						return errors.Errorf(
```
Comment (knz) [inline pkg/sql/pg_catalog.go]: In both `master` and this backport, please replace this by `return pgerror.NewAssertionErrorf(...)` and simplify the sentence.

Comment (BramGruneir) [reply pkg/sql/pg_catalog.go]: Sure, incoming PR for master.

And I'll add the new commit to this PR.

Comment (BramGruneir) [reply pkg/sql/pg_catalog.go]: See #31925.
