### PR TITLE
sql: ensure that internal executors have a valid application_name

### LINKED ISSUE #31998: sql: invalid connEx.application_name causes entire cluster to go down when querying node_queries/_sessions
All nodes panicked at the same time in a 3 node cluster running on GKE, on persistent volumes. 

One node panicked with
```
panic: panic while executing 1 statements: SELECT * FROM _._ LIMIT _; caused by interface conversion: interface {} is nil, not string

goroutine 3070503 [running]:
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).closeWrapper(0xc42bfaea00, 0x2ff6340, 0xc43055b240, 0x2758be0, 0xc42938a480)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:677 +0x36f
github.com/cockroachdb/cockroach/pkg/sql.(*Server).ServeConn.func1(0xc42bfaea00, 0x2ff6340, 0xc43055b240)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:418 +0x61
panic(0x2758be0, 0xc42938a480)
	/usr/local/go/src/runtime/panic.go:502 +0x229
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).serialize(0xc42cf83500, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:2084 +0xa00
github.com/cockroachdb/cockroach/pkg/sql.(*SessionRegistry).SerializeAll(0xc42028c3f0, 0x0, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/exec_util.go:854 +0x1bb
github.com/cockroachdb/cockroach/pkg/server.(*statusServer).ListLocalSessions(0xc4206fc480, 0x2ff6400, 0xc420b73cb0, 0xc429be4bf0, 0x28b6da0, 0x1, 0xc42f47c6e0)
	/go/src/github.com/cockroachdb/cockroach/pkg/server/status.go:1361 +0x9e
```

And the other two with
```
panic: panic while executing 1 statements: SELECT count(_) FROM _._; caused by interface conversion: interface {} is nil, not string

goroutine 1449192 [running]:
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).closeWrapper(0xc4298bc000, 0x2ff6340, 0xc425636f80, 0x2758be0, 0xc425d6e6c0)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:677 +0x36f
github.com/cockroachdb/cockroach/pkg/sql.(*Server).ServeConn.func1(0xc4298bc000, 0x2ff6340, 0xc425636f80)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:418 +0x61
panic(0x2758be0, 0xc425d6e6c0)
	/usr/local/go/src/runtime/panic.go:502 +0x229
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).serialize(0xc422df7500, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:2084 +0xa00
github.com/cockroachdb/cockroach/pkg/sql.(*SessionRegistry).SerializeAll(0xc42048d170, 0x0, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/exec_util.go:854 +0x1bb
github.com/cockroachdb/cockroach/pkg/server.(*statusServer).ListLocalSessions(0xc4206b0360, 0x2ff6400, 0xc42bfa4b40, 0xc4256d8060, 0x28b6da0, 0x1, 0xc428631720)
	/go/src/github.com/cockroachdb/cockroach/pkg/server/status.go:1361 +0x9e
```

Could this have been fixed already in rc2?

### LINKED ISSUE #33086: sentry: conn_executor.go:643: panic while executing 1 statements: SELECT count(_) FROM _._: caused by <redacted>
https://sentry.io/cockroach-labs/cockroachdb/issues/805238884/?referrer=webhooks_plugin

```
github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go in func1 at line 387
Called from: runtime/asm_amd64.s in call32
github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go in serialize at line 2057
github.com/cockroachdb/cockroach/pkg/sql/exec_util.go in SerializeAll at line 854
github.com/cockroachdb/cockroach/pkg/server/status.go in ListLocalSessions at line 1385
github.com/cockroachdb/cockroach/pkg/sql/crdb_internal.go in func39 at line 838
github.com/cockroachdb/cockroach/pkg/sql/virtual_schema.go in func1 at line 134
github.com/cockroachdb/cockroach/pkg/sql/opt_exec_factory.go in func1 at line 130
github.com/cockroachdb/cockroach/pkg/sql/delayed.go in startExec at line 62
github.com/cockroachdb/cockroach/pkg/sql/plan.go in func2 at line 640
github.com/cockroachdb/cockroach/pkg/sql/walk.go in func1 at line 134
github.com/cockroachdb/cockroach/pkg/sql/walk.go in visitInternal at line 543
github.com/cockroachdb/cockroach/pkg/sql/walk.go in visit at line 101
github.com/cockroachdb/cockroach/pkg/sql/walk.go in walkPlan at line 65
github.com/cockroachdb/cockroach/pkg/sql/plan.go in startExec at line 645
github.com/cockroachdb/cockroach/pkg/sql/plan_node_to_row_source.go in Start at line 139
github.com/cockroachdb/cockroach/pkg/sql/distsqlrun/aggregator.go in start at line 403
github.com/cockroachdb/cockroach/pkg/sql/distsqlrun/aggregator.go in Start at line 399
github.com/cockroachdb/cockroach/pkg/sql/distsqlrun/processors.go in Run at line 730
github.com/cockroachdb/cockroach/pkg/sql/distsqlrun/flow.go in StartSync at line 607
github.com/cockroachdb/cockroach/pkg/sql/distsql_running.go in Run at line 253
github.com/cockroachdb/cockroach/pkg/sql/distsql_running.go in PlanAndRun at line 758
github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go in execWithDistSQLEngine at line 982
github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go in dispatchToExecutionEngine at line 824
github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go in execStmtInOpenState at line 402
github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go in execStmt at line 96
github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go in run at line 1116
github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go in ServeConn at line 389
github.com/cockroachdb/cockroach/pkg/sql/pgwire/conn.go in func4 at line 313
```

### PR DESCRIPTION
**Pull request by jordanlewis**
Fixes #33086.
Fixes #31998.

Previously, there was a possibility for an internal conn executor to
have no application name set, leading to a potential panic during show
sessions, queries and other mechanisms that require a valid
application name.

This patch fixes it by ensuring the application name is reliably set.
It also adds a test that validates this on both kinds of internal
executors.

Release note (bug fix): CockroachDB does not crash upon running SHOW
SESSIONS, SHOW QUERIES and inspections of some `crdb_internal` tables
when certain SQL sessions are issuing internal SQL queries.

### CODE REVIEW

**Review by andreimatei — COMMENTED** [review]
cc @knz - is this the `show sessions` crash you were hunting a few weeks ago?
Also deferring the review to you?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/33138#-:-LTcwvWq94J63k-v8pVq:b-544g27)* status: :shipit: complete! 0 of 0 LGTMs obtained

**Review by knz — COMMENTED** [review]
I appreciate the thrust of this PR but in my previous batch of changes I made efforts to ensure that the app name is always set, even for internal executors. As a result I not not expect the ex.applicationName to be invalid in any case any more.

So if your change here is "fixing a bug" that means that the root cause is elsewhere - the initialization of the applicationName field somewhere is missing. This PR is then just a bandaid and not a trust fix for #33086. (I have been using "Informs #xxxx" to annotate these cases in the past.)

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/33138#-:-LTdB43yDjP5tyVCAvn_:b1xjbi7)* status: :shipit: complete! 0 of 0 LGTMs obtained

**Comment by jordanlewis** [comment]
Fine, I can change to informs, but can we still merge this? I don't like panics.

**Comment by andreimatei** [comment]
I don't follow - does Raphael's PR fix the same problem?
Maybe you want to do this as original work on branch 2.1?

**Comment by knz** [comment]
As discussed with Jordan I am taking the PR over - I found the root cause and a candidate test.

**Comment by knz** [comment]
@jordanlewis I have extended the PR and added a test. PTAL.

File: pkg/sql/internal_test.go [hunk 1]
```diff
@@ -134,6 +139,155 @@ func TestSessionBoundInternalExecutor(t *testing.T) {
...
+	case err := <-errChan:
+		if !isClientsideQueryCanceledErr(err) {
+			t.Fatal(err)
+		}
+	case <-time.After(time.Second * 5):
+		t.Fatal("no error received from query supposed to be canceled")
+	}
+
+	// TOOD(knz): remove this skip when we log internal queries in stats.
+	t.Skip("#32215")
```
Comment (jordanlewis) [inline pkg/sql/internal_test.go]: does this only skip the part of the test below it?

**Review by jordanlewis — COMMENTED** [review]
LGTM

**Review by andreimatei — COMMENTED** [review]
don't wait for my review, in case you were. I trust y'all are doing great things.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/33138#-:-LU1mg_W9brwXBmPvZMn:bsm3vmh)* status: :shipit: complete! 0 of 0 LGTMs obtained

File: pkg/sql/internal_test.go (hunk 1 above)
Comment (knz) [reply pkg/sql/internal_test.go]: yes it does (I checked the doc)

**Comment by knz** [comment]
gosh it does seem my new test has a data race. will investigate more.
