### PR TITLE
server: Move heartbeatCallback under mutex

### LINKED ISSUE #13616: Data race in multiTestContext.restartStore
SHA: https://github.com/cockroachdb/cockroach/commits/0ba52ff84a3e67efe3532b9119058aab8231478a

Parameters:
```
COCKROACH_PROPOSER_EVALUATED_KV=false
TAGS=
GOFLAGS=-race
```

Stress build found a failed test: https://teamcity.cockroachdb.com/viewLog.html?buildId=151954&tab=buildLog

```
I170216 09:34:30.066399 43104 storage/store.go:3312  [replicate,n1,s1,r8/1:/Table/5{1-2},@c421c9d880] streamed snapshot: kv pairs: 11, log entries: 5, 34ms
I170216 09:34:30.070320 45011 storage/replica_raftstorage.go:596  [n5,s5,r8/?:{-},@c4227b0000] applying preemptive snapshot at index 15 (id=f2129675, encoded size=2715, 1 rocksdb batches, 5 log entries)
I170216 09:34:30.077838 45011 storage/replica_raftstorage.go:604  [n5,s5,r8/?:/Table/5{1-2},@c4227b0000] applied preemptive snapshot in 7ms [clear=0ms batch=0ms entries=0ms commit=0ms]
I170216 09:34:30.082239 43104 storage/replica_command.go:3253  [replicate,n1,s1,r8/1:/Table/5{1-2},@c421c9d880] change replicas (remove {5 5 4}): read existing descriptor range_id:8 start_key:"\273" end_key:"\274" replicas:<node_id:1 store_id:1 replica_id:1 > replicas:<node_id:4 store_id:4 replica_id:2 > replicas:<node_id:3 store_id:3 replica_id:3 > next_replica_id:4 
I170216 09:34:30.092962 45047 storage/replica_command.go:2397  [n1,s1,r9/1:/{Table/52-Max},@c422da1c00] initiating a split of this range at key /Table/53 [r10]
I170216 09:34:30.243889 44966 storage/raft_transport.go:437  [n2] raft transport stream to node 5 established
I170216 09:34:30.277153 45174 storage/replica_command.go:2397  [n1,s1,r10/1:/{Table/53-Max},@c42182ee00] initiating a split of this range at key /Table/54 [r11]
I170216 09:34:30.285687 45161 storage/replica.go:2487  [n1,s1,r8/1:/Table/5{1-2},@c421c9d880] proposing ADD_REPLICA {NodeID:5 StoreID:5 ReplicaID:4}: [{NodeID:1 StoreID:1 ReplicaID:1} {NodeID:4 StoreID:4 ReplicaID:2} {NodeID:3 StoreID:3 ReplicaID:3} {NodeID:5 StoreID:5 ReplicaID:4}]
I170216 09:34:30.404402 43104 storage/replica_raftstorage.go:414  [replicate,n1,s1,r6/1:/Table/{14-50},@c4205f8380] generated preemptive snapshot 758f99e6 at index 25
I170216 09:34:30.414639 43104 storage/store.go:3312  [replicate,n1,s1,r6/1:/Table/{14-50},@c4205f8380] streamed snapshot: kv pairs: 13, log entries: 15, 4ms
I170216 09:34:30.419206 45133 storage/replica_raftstorage.go:596  [n5,s5,r6/?:{-},@c421ec9c00] applying preemptive snapshot at index 25 (id=758f99e6, encoded size=6120, 1 rocksdb batches, 15 log entries)
I170216 09:34:30.421298 45133 storage/replica_raftstorage.go:604  [n5,s5,r6/?:/Table/{14-50},@c421ec9c00] applied preemptive snapshot in 2ms [clear=0ms batch=0ms entries=1ms commit=0ms]
I170216 09:34:30.433863 43104 storage/replica_command.go:3253  [replicate,n1,s1,r6/1:/Table/{14-50},@c4205f8380] change replicas (remove {5 5 4}): read existing descriptor range_id:6 start_key:"\226" end_key:"\272" replicas:<node_id:1 store_id:1 replica_id:1 > replicas:<node_id:4 store_id:4 replica_id:2 > replicas:<node_id:3 store_id:3 replica_id:3 > next_replica_id:4 
I170216 09:34:30.504433 45193 storage/raft_transport.go:437  [n3] raft transport stream to node 4 established
I170216 09:34:30.522408 45194 storage/raft_transport.go:437  [n3] raft transport stream to node 5 established
I170216 09:34:30.563440 43624 storage/replica_command.go:3253  [replicate,n3,s3,r8/3:/Table/5{1-2},@c4201c3500] change replicas (remove {1 1 1}): read existing descriptor range_id:8 start_key:"\273" end_key:"\274" replicas:<node_id:1 store_id:1 replica_id:1 > replicas:<node_id:4 store_id:4 replica_id:2 > replicas:<node_id:3 store_id:3 replica_id:3 > replicas:<node_id:5 store_id:5 replica_id:4 > next_replica_id:5 
I170216 09:34:30.568124 43011 storage/replicate_queue_test.go:102  not balanced: [11 4 8 8 4]
I170216 09:34:30.569658 43011 storage/replicate_queue_test.go:102  not balanced: [11 4 8 8 4]
I170216 09:34:30.569785 43011 storage/replicate_queue_test.go:102  not balanced: [11 4 8 8 4]
I170216 09:34:30.569875 43011 storage/replicate_queue_test.go:102  not balanced: [11 4 8 8 4]
I170216 09:34:30.569947 43011 storage/replicate_queue_test.go:102  not balanced: [11 4 8 8 4]
I170216 09:34:30.570017 43011 storage/replicate_queue_test.go:102  not balanced: [11 4 8 8 4]
I170216 09:34:30.570085 43011 storage/replicate_queue_test.go:102  not balanced: [11 4 8 8 4]
I170216 09:34:30.570152 43011 storage/replicate_queue_test.go:102  not balanced: [11 4 8 8 4]
I170216 09:34:30.570225 43011 storage/replicate_queue_test.go:102  not balanced: [11 4 8 8 4]
I170216 09:34:30.570299 43011 storage/replicate_queue_test.go:102  not balanced: [11 4 8 8 4]
I170216 09:34:30.570367 43011 storage/replicate_queue_test.go:102  not balanced: [11 4 8 8 4]
I170216 09:34:30.570913 43011 storage/replicate_queue_test.go:102  not balanced: [11 4 8 8 4]
I170216 09:34:30.571050 43011 storage/replicate_queue_test.go:102  not balanced: [11 4 8 8 4]
I170216 09:34:30.571154 43011 storage/replicate_queue_test.go:102  not balanced: [11 4 8 8 4]
I170216 09:34:30.571264 43011 storage/replicate_queue_test.go:102  not balanced: [11 4 8 8 4]
I170216 09:34:30.571465 43011 storage/replicate_queue_test.go:102  not balanced: [11 4 8 8 4]
I170216 09:34:30.571676 43011 storage/replicate_queue_test.go:102  not balanced: [11 4 8 8 4]
I170216 09:34:30.571888 43011 storage/replicate_queue_test.go:102  not balanced: [11 4 8 8 4]
I170216 09:34:30.572146 43011 storage/replicate_queue_test.go:102  not balanced: [11 4 8 8 4]
I170216 09:34:30.572559 43011 storage/replicate_queue_test.go:102  not balanced: [11 4 8 8 4]
I170216 09:34:30.573234 43011 storage/replicate_queue_test.go:102  not balanced: [11 4 8 8 4]
I170216 09:34:30.574547 43011 storage/replicate_queue_test.go:102  not balanced: [11 4 8 8 4]
I170216 09:34:30.576917 43011 storage/replicate_queue_test.go:102  not balanced: [11 4 8 8 4]
I170216 09:34:30.582049 43011 storage/replicate_queue_test.go:102  not balanced: [11 4 8 8 4]
I170216 09:34:30.591647 43011 storage/replicate_queue_test.go:102  not balanced: [11 4 8 8 4]
I170216 09:34:30.603179 45350 storage/replica.go:2487  [n1,s1,r6/1:/Table/{14-50},@c4205f8380] proposing ADD_REPLICA {NodeID:5 StoreID:5 ReplicaID:4}: [{NodeID:1 StoreID:1 ReplicaID:1} {NodeID:4 StoreID:4 ReplicaID:2} {NodeID:3 StoreID:3 ReplicaID:3} {NodeID:5 StoreID:5 ReplicaID:4}]
I170216 09:34:30.616462 43011 storage/replicate_queue_test.go:102  not balanced: [11 4 8 8 4]
I170216 09:34:30.634980 45231 storage/raft_transport.go:437  [n4] raft transport stream to node 3 established
I170216 09:34:30.650446 43011 storage/replicate_queue_test.go:102  not balanced: [11 4 8 8 4]
I170216 09:34:30.686444 45248 storage/raft_transport.go:437  [n5] raft transport stream to node 3 established
I170216 09:34:30.733669 43011 storage/replicate_queue_test.go:102  not balanced: [11 4 8 8 4]
I170216 09:34:30.745393 43104 storage/replica_raftstorage.go:414  [replicate,n1,s1,r10/1:/Table/5{3-4},@c42182ee00] generated preemptive snapshot 566f76f6 at index 16
I170216 09:34:30.761011 43104 storage/store.go:3312  [replicate,n1,s1,r10/1:/Table/5{3-4},@c42182ee00] streamed snapshot: kv pairs: 10, log entries: 6, 15ms
I170216 09:34:30.762725 45475 storage/replica_raftstorage.go:596  [n5,s5,r10/?:{-},@c42335e380] applying preemptive snapshot at index 16 (id=566f76f6, encoded size=2618, 1 rocksdb batches, 6 log entries)
I170216 09:34:30.783086 45475 storage/replica_raftstorage.go:604  [n5,s5,r10/?:/Table/5{3-4},@c42335e380] applied preemptive snapshot in 18ms [clear=0ms batch=0ms entries=17ms commit=0ms]
I170216 09:34:30.802215 43104 storage/replica_command.go:3253  [replicate,n1,s1,r10/1:/Table/5{3-4},@c42182ee00] change replicas (remove {5 5 4}): read existing descriptor range_id:10 start_key:"\275" end_key:"\276" replicas:<node_id:1 store_id:1 replica_id:1 > replicas:<node_id:4 store_id:4 replica_id:2 > replicas:<node_id:3 store_id:3 replica_id:3 > next_replica_id:4 
I170216 09:34:30.856728 45388 storage/replica.go:2487  [n1,s1,r10/1:/Table/5{3-4},@c42182ee00] proposing ADD_REPLICA {NodeID:5 StoreID:5 ReplicaID:4}: [{NodeID:1 StoreID:1 ReplicaID:1} {NodeID:4 StoreID:4 ReplicaID:2} {NodeID:3 StoreID:3 ReplicaID:3} {NodeID:5 StoreID:5 ReplicaID:4}]
I170216 09:34:30.870777 43011 storage/replicate_queue_test.go:102  not balanced: [11 4 8 8 5]
I170216 09:34:30.878451 43104 storage/replica_command.go:3253  [replicate,n1,s1,r10/1:/Table/5{3-4},@c42182ee00] change replicas (remove {3 3 3}): read existing descriptor range_id:10 start_key:"\275" end_key:"\276" replicas:<node_id:1 store_id:1 replica_id:1 > replicas:<node_id:4 store_id:4 replica_id:2 > replicas:<node_id:3 store_id:3 replica_id:3 > replicas:<node_id:5 store_id:5 replica_id:4 > next_replica_id:5 
I170216 09:34:30.977213 45520 storage/replica.go:2487  [n3,s3,r8/3:/Table/5{1-2},@c4201c3500] proposing REMOVE_REPLICA {NodeID:1 StoreID:1 ReplicaID:1}: [{NodeID:5 StoreID:5 ReplicaID:4} {NodeID:4 StoreID:4 ReplicaID:2} {NodeID:3 StoreID:3 ReplicaID:3}]
I170216 09:34:31.006657 45602 storage/replica.go:2487  [n1,s1,r10/1:/Table/5{3-4},@c42182ee00] proposing REMOVE_REPLICA {NodeID:3 StoreID:3 ReplicaID:3}: [{NodeID:1 StoreID:1 ReplicaID:1} {NodeID:4 StoreID:4 ReplicaID:2} {NodeID:5 StoreID:5 ReplicaID:4}]
I170216 09:34:31.033096 43624 storage/replica_command.go:3253  [replicate,n3,s3,r6/3:/Table/{14-50},@c4205f8e00] change replicas (remove {1 1 1}): read existing descriptor range_id:6 start_key:"\226" end_key:"\272" replicas:<node_id:1 store_id:1 replica_id:1 > replicas:<node_id:4 store_id:4 replica_id:2 > replicas:<node_id:3 store_id:3 replica_id:3 > replicas:<node_id:5 store_id:5 replica_id:4 > next_replica_id:5 
I170216 09:34:31.100650 43104 storage/replica_raftstorage.go:414  [replicate,n1,s1,r11/1:/{Table/54-Max},@c422d12000] generated preemptive snapshot ee8f5f63 at index 11
I170216 09:34:31.127385 43104 storage/store.go:3312  [replicate,n1,s1,r11/1:/{Table/54-Max},@c422d12000] streamed snapshot: kv pairs: 9, log entries: 1, 25ms
I170216 09:34:31.138881 43902 storage/store.go:3164  [n1,s1,r8/1:/Table/5{1-2},@c421c9d880] added to replica GC queue (peer suggestion)
I170216 09:34:31.139155 43105 storage/store.go:2134  [replicaGC,n1,s1,r8/1:/Table/5{1-2},@c421c9d880] removing replica
I170216 09:34:31.141183 43105 storage/replica.go:735  [replicaGC,n1,s1,r8/1:/Table/5{1-2},@c421c9d880] removed 11 (0+11) keys in 2ms [clear=1ms commit=1ms]
I170216 09:34:31.147494 45611 storage/replica_raftstorage.go:596  [n2,s2,r11/?:{-},@c422b9ca80] applying preemptive snapshot at index 11 (id=ee8f5f63, encoded size=520, 1 rocksdb batches, 1 log entries)
I170216 09:34:31.160892 45611 storage/replica_raftstorage.go:604  [n2,s2,r11/?:/{Table/54-Max},@c422b9ca80] applied preemptive snapshot in 13ms [clear=0ms batch=0ms entries=0ms commit=0ms]
I170216 09:34:31.162176 45629 util/stop/stopper.go:493  quiescing; tasks left:
1      storage/queue.go:523
1      storage/intent_resolver.go:284
1      server/node.go:847
I170216 09:34:31.162740 45630 util/stop/stopper.go:493  quiescing; tasks left:
1      gossip/infostore.go:301
W170216 09:34:31.162879 43348 gossip/infostore.go:303  [n1] node unavailable; try another peer
W170216 09:34:31.164644 43819 gossip/infostore.go:303  [n1] node unavailable; try another peer
I170216 09:34:31.172980 43923 storage/store.go:3164  [n3,s3,r10/3:/Table/5{3-4},@c422da7c00] added to replica GC queue (peer suggestion)
I170216 09:34:31.173492 43625 storage/store.go:2134  [replicaGC,n3,s3,r10/3:/Table/5{3-4},@c422da7c00] removing replica
E170216 09:34:31.173606 43104 storage/queue.go:628  [replicate,n1,s1,r11/1:/{Table/54-Max},@c422d12000] change replicas of range 11 failed: node unavailable; try another peer
I170216 09:34:31.173805 45629 util/stop/stopper.go:493  quiescing; tasks left:
1      storage/intent_resolver.go:284
1      server/node.go:847
I170216 09:34:31.174438 43625 storage/replica.go:735  [replicaGC,n3,s3,r10/3:/Table/5{3-4},@c422da7c00] removed 11 (0+11) keys in 0ms [clear=0ms commit=0ms]
I170216 09:34:31.177583 45631 util/stop/stopper.go:493  quiescing; tasks left:
2      storage/queue.go:523
1      kv/txn_coord_sender.go:924
W170216 09:34:31.178654 43635 storage/raft_transport.go:443  [n2] raft transport stream to node 1 failed: rpc error: code = 13 desc = transport is closing
W170216 09:34:31.178771 43607 gossip/infostore.go:303  [n1] node unavailable; try another peer
W170216 09:34:31.179205 43625 storage/store.go:1463  [replicaGC,n3,s3,r10/3:/Table/5{3-4},@c422da7c00] unable to gossip on capacity change: node unavailable; try another peer
W170216 09:34:31.179577 45194 storage/raft_transport.go:443  [n3] raft transport stream to node 5 failed: EOF
I170216 09:34:31.179764 45631 util/stop/stopper.go:493  quiescing; tasks left:
1      storage/queue.go:523
1      kv/txn_coord_sender.go:924
W170216 09:34:31.179881 44602 storage/raft_transport.go:443  [n1] raft transport stream to node 5 failed: EOF
W170216 09:34:31.180183 44966 storage/raft_transport.go:443  [n2] raft transport stream to node 5 failed: rpc error: code = 13 desc = transport is closing
W170216 09:34:31.180341 43518 storage/raft_transport.go:443  [n1] raft transport stream to node 2 failed: EOF
E170216 09:34:31.180493 43624 internal/client/txn.go:342  [replicate,n3,s3,r6/3:/Table/{14-50},@c4205f8e00] failure aborting transaction: node unavailable; try another peer; abort caused by: node unavailable; try another peer
E170216 09:34:31.181713 43624 storage/queue.go:628  [replicate,n3,s3,r6/3:/Table/{14-50},@c4205f8e00] change replicas of range 6 failed: node unavailable; try another peer
I170216 09:34:31.181894 45631 util/stop/stopper.go:493  quiescing; tasks left:
1      kv/txn_coord_sender.go:924
W170216 09:34:31.186390 45590 kv/txn_coord_sender.go:713  [n3] node unavailable; try another peer
W170216 09:34:31.187111 44161 gossip/gossip.go:1178  [n5] no incoming or outgoing connections
W170216 09:34:31.187440 44962 storage/raft_transport.go:443  [n5] raft transport stream to node 2 failed: EOF
W170216 09:34:31.189285 43900 storage/raft_transport.go:443  [n1] raft transport stream to node 3 failed: EOF
W170216 09:34:31.189620 44679 storage/raft_transport.go:443  [n5] raft transport stream to node 1 failed: rpc error: code = 13 desc = transport is closing
W170216 09:34:31.192768 43604 gossip/infostore.go:303  [n3] node unavailable; try another peer
W170216 09:34:31.195913 43604 gossip/infostore.go:303  [n3] node unavailable; try another peer
W170216 09:34:31.196308 45248 storage/raft_transport.go:443  [n5] raft transport stream to node 3 failed: rpc error: code = 13 desc = transport is closing
W170216 09:34:31.200718 44213 storage/raft_transport.go:443  [n1] raft transport stream to node 4 failed: EOF
W170216 09:34:31.200780 45231 storage/raft_transport.go:443  [n4] raft transport stream to node 3 failed: rpc error: code = 13 desc = transport is closing
W170216 09:34:31.210772 44242 storage/raft_transport.go:443  [n4] raft transport stream to node 1 failed: rpc error: code = 13 desc = transport is closing
W170216 09:34:31.211056 43905 storage/raft_transport.go:443  [n3] raft transport stream to node 1 failed: EOF
W170216 09:34:31.211761 43205 gossip/infostore.go:303  [n1] node unavailable; try another peer
I170216 09:34:31.211875 43185 kv/transport_race.go:71  transport race promotion: ran 30 iterations on up to 513 requests
W170216 09:34:31.212066 45193 storage/raft_transport.go:443  [n3] raft transport stream to node 4 failed: EOF
W170216 09:34:31.212231 43437 gossip/infostore.go:303  [n2] node unavailable; try another peer
--- PASS: TestReplicateQueueRebalance (4.50s)
=== RUN   TestReplicateQueueDownReplicate
W170216 09:34:31.324133 45617 server/status/runtime.go:116  Could not parse build timestamp: parsing time "" as "2006/01/02 15:04:05": cannot parse "" as "2006"
I170216 09:34:31.326752 45617 server/config.go:482  1 storage engine initialized
I170216 09:34:31.327850 45617 server/node.go:443  [n?] store [n0,s0] not bootstrapped
I170216 09:34:31.338835 45617 server/node.go:372  [n?] **** cluster 4810b056-f230-4f31-b761-3fdc4caf6b9b has been created
I170216 09:34:31.338922 45617 server/node.go:373  [n?] **** add additional nodes by specifying --join=127.0.0.1:36683
I170216 09:34:31.343206 45617 storage/store.go:1261  [n1] [n1,s1]: failed initial metrics computation: [n1,s1]: system config not yet available
I170216 09:34:31.343338 45617 server/node.go:456  [n1] initialized store [n1,s1]: {Capacity:536870912 Available:536870912 RangeCount:1 LeaseCount:0}
I170216 09:34:31.343458 45617 server/node.go:341  [n1] node ID 1 initialized
I170216 09:34:31.343652 45617 gossip/gossip.go:293  [n1] NodeDescriptor set to node_id:1 address:<network_field:"tcp" address_field:"127.0.0.1:36683" > attrs:<> locality:<> 
I170216 09:34:31.349029 45617 storage/stores.go:296  [n1] read 0 node addresses from persistent storage
I170216 09:34:31.349200 45617 server/node.go:605  [n1] connecting to gossip network to verify cluster ID...
I170216 09:34:31.349271 45617 server/node.go:629  [n1] node connected via gossip and verified as part of cluster "4810b056-f230-4f31-b761-3fdc4caf6b9b"
I170216 09:34:31.349566 45617 server/node.go:391  [n1] node=1: started with [[]=] engine(s) and attributes []
I170216 09:34:31.351031 45617 sql/executor.go:333  [n1] creating distSQLPlanner with address {tcp 127.0.0.1:36683}
I170216 09:34:31.358112 45780 storage/split_queue.go:98  [split,n1,s1,r1/1:/M{in-ax},@c420850000] splitting at key /Table/0/0
I170216 09:34:31.365792 45780 storage/replica_command.go:2397  [split,n1,s1,r1/1:/M{in-ax},@c420850000] initiating a split of this range at key /Table/0 [r2]
I170216 09:34:31.367624 45617 server/server.go:644  [n1] starting https server at 127.0.0.1:60566
I170216 09:34:31.367683 45617 server/server.go:645  [n1] starting grpc/postgres server at 127.0.0.1:36683
I170216 09:34:31.367714 45617 server/server.go:646  [n1] advertising CockroachDB node at 127.0.0.1:36683
I170216 09:34:31.432581 45769 sql/event_log.go:95  [n1] Event: "node_join", target: 1, info: {Descriptor:{NodeID:1 Address:{NetworkField:tcp AddressField:127.0.0.1:36683} Attrs: Locality:} ClusterID:4810b056-f230-4f31-b761-3fdc4caf6b9b StartedAt:1487237671349293874 LastUp:1487237671349293874}
I170216 09:34:31.435163 45780 storage/split_queue.go:98  [split,n1,s1,r2/1:/{Table/0-Max},@c42258ce00] splitting at key /Table/11/0
I170216 09:34:31.435391 45780 storage/replica_command.go:2397  [split,n1,s1,r2/1:/{Table/0-Max},@c42258ce00] initiating a split of this range at key /Table/11 [r3]
I170216 09:34:31.536833 45617 sql/event_log.go:95  [n1] Event: "alter_table", target: 12, info: {TableName:eventlog Statement:ALTER TABLE system.eventlog ALTER COLUMN uniqueID SET DEFAULT uuid_v4() User:node MutationID:0 CascadeDroppedViews:[]}
I170216 09:34:31.596633 45780 storage/split_queue.go:98  [split,n1,s1,r3/1:/{Table/11-Max},@c42335e000] splitting at key /Table/12/0
I170216 09:34:31.596846 45780 storage/replica_command.go:2397  [split,n1,s1,r3/1:/{Table/11-Max},@c42335e000] initiating a split of this range at key /Table/12 [r4]
I170216 09:34:31.651919 45780 storage/split_queue.go:98  [split,n1,s1,r4/1:/{Table/12-Max},@c422fa8700] splitting at key /Table/13/0
I170216 09:34:31.652100 45780 storage/replica_command.go:2397  [split,n1,s1,r4/1:/{Table/12-Max},@c422fa8700] initiating a split of this range at key /Table/13 [r5]
I170216 09:34:31.685160 45617 server/server.go:771  [n1] done ensuring all necessary migrations have run
I170216 09:34:31.685275 45617 server/server.go:773  [n1] serving sql connections
I170216 09:34:31.741711 45780 storage/split_queue.go:98  [split,n1,s1,r5/1:/{Table/13-Max},@c42335fc00] splitting at key /Table/14/0
I170216 09:34:31.741913 45780 storage/replica_command.go:2397  [split,n1,s1,r5/1:/{Table/13-Max},@c42335fc00] initiating a split of this range at key /Table/14 [r6]
W170216 09:34:31.863138 45617 gossip/gossip.go:1178  [n?] no incoming or outgoing connections
W170216 09:34:31.886631 45617 server/status/runtime.go:116  Could not parse build timestamp: parsing time "" as "2006/01/02 15:04:05": cannot parse "" as "2006"
I170216 09:34:31.890294 45617 server/config.go:482  1 storage engine initialized
I170216 09:34:31.891046 45617 server/node.go:443  [n?] store [n0,s0] not bootstrapped
I170216 09:34:31.891125 45617 storage/stores.go:296  [n?] read 0 node addresses from persistent storage
I170216 09:34:31.891202 45617 server/node.go:605  [n?] connecting to gossip network to verify cluster ID...
I170216 09:34:31.944988 46014 gossip/client.go:131  [n?] started gossip client to 127.0.0.1:36683
I170216 09:34:31.945716 45963 gossip/server.go:214  [n1] received initial cluster-verification connection from {tcp 127.0.0.1:59075}
I170216 09:34:31.948052 45617 server/node.go:629  [n?] node connected via gossip and verified as part of cluster "4810b056-f230-4f31-b761-3fdc4caf6b9b"
I170216 09:34:31.948890 45964 storage/stores.go:312  [n?] wrote 1 node addresses to persistent storage
I170216 09:34:31.954638 45617 kv/dist_sender.go:367  [n?] unable to determine this node's attributes for replica selection; node is most likely bootstrapping
I170216 09:34:31.958023 45617 server/node.go:334  [n?] new node allocated ID 2
I170216 09:34:31.958280 45617 gossip/gossip.go:293  [n2] NodeDescriptor set to node_id:2 address:<network_field:"tcp" address_field:"127.0.0.1:59075" > attrs:<> locality:<> 
I170216 09:34:31.959018 45617 server/node.go:391  [n2] node=2: started with [[]=] engine(s) and attributes []
I170216 09:34:31.959476 45617 sql/executor.go:333  [n2] creating distSQLPlanner with address {tcp 127.0.0.1:59075}
I170216 09:34:31.966886 45929 storage/stores.go:312  [n1] wrote 1 node addresses to persistent storage
I170216 09:34:32.009972 45993 sql/event_log.go:95  [n2] Event: "node_join", target: 2, info: {Descriptor:{NodeID:2 Address:{NetworkField:tcp AddressField:127.0.0.1:59075} Attrs: Locality:} ClusterID:4810b056-f230-4f31-b761-3fdc4caf6b9b StartedAt:1487237671958680364 LastUp:1487237671958680364}
I170216 09:34:32.022952 45617 server/server.go:644  [n2] starting https server at 127.0.0.1:39773
I170216 09:34:32.023396 45617 server/server.go:645  [n2] starting grpc/postgres server at 127.0.0.1:59075
I170216 09:34:32.027280 45617 server/server.go:646  [n2] advertising CockroachDB node at 127.0.0.1:59075
I170216 09:34:32.027572 45990 server/node.go:586  [n2] bootstrapped store [n2,s2]
I170216 09:34:32.043799 45826 storage/replica_raftstorage.go:414  [replicate,n1,s1,r2/1:/Table/{0-11},@c42258ce00] generated preemptive snapshot 519580b9 at index 27
I170216 09:34:32.067400 45617 server/server.go:771  [n2] done ensuring all necessary migrations have run
I170216 09:34:32.067484 45617 server/server.go:773  [n2] serving sql connections
W170216 09:34:32.167348 45617 gossip/gossip.go:1178  [n?] no incoming or outgoing connections
W170216 09:34:32.173366 45617 server/status/runtime.go:116  Could not parse build timestamp: parsing time "" as "2006/01/02 15:04:05": cannot parse "" as "2006"
I170216 09:34:32.177754 45617 server/config.go:482  1 storage engine initialized
I170216 09:34:32.212448 45617 server/node.go:443  [n?] store [n0,s0] not bootstrapped
I170216 09:34:32.232132 45617 storage/stores.go:296  [n?] read 0 node addresses from persistent storage
I170216 09:34:32.232653 46125 storage/replica_raftstorage.go:596  [n2,s2,r2/?:{-},@c42057ce00] applying preemptive snapshot at index 27 (id=519580b9, encoded size=13987, 1 rocksdb batches, 17 log entries)
I170216 09:34:32.234194 46125 storage/replica_raftstorage.go:604  [n2,s2,r2/?:/Table/{0-11},@c42057ce00] applied preemptive snapshot in 1ms [clear=0ms batch=0ms entries=1ms commit=0ms]
I170216 09:34:32.234819 45826 storage/store.go:3312  [replicate,n1,s1,r2/1:/Table/{0-11},@c42258ce00] streamed snapshot: kv pairs: 34, log entries: 17, 19ms
I170216 09:34:32.234962 45617 server/node.go:605  [n?] connecting to gossip network to verify cluster ID...
I170216 09:34:32.239407 45826 storage/replica_command.go:3253  [replicate,n1,s1,r2/1:/Table/{0-11},@c42258ce00] change replicas (remove {2 2 2}): read existing descriptor range_id:2 start_key:"\210" end_key:"\223" replicas:<node_id:1 store_id:1 replica_id:1 > next_replica_id:2 
I170216 09:34:32.262684 46144 storage/replica.go:2487  [n1,s1,r2/1:/Table/{0-11},@c42258ce00] proposing ADD_REPLICA {NodeID:2 StoreID:2 ReplicaID:2}: [{NodeID:1 StoreID:1 ReplicaID:1} {NodeID:2 StoreID:2 ReplicaID:2}]
I170216 09:34:32.265881 45826 storage/replica_raftstorage.go:414  [replicate,n1,s1,r1/1:/{Min-Table/0},@c420850000] generated preemptive snapshot 46fddcec at index 50
I170216 09:34:32.296697 46157 storage/raft_transport.go:437  [n2] raft transport stream to node 1 established
I170216 09:34:32.318462 45826 storage/store.go:3312  [replicate,n1,s1,r1/1:/{Min-Table/0},@c420850000] streamed snapshot: kv pairs: 594, log entries: 40, 29ms
I170216 09:34:32.319762 46156 storage/replica_raftstorage.go:596  [n2,s2,r1/?:{-},@c42182ea80] applying preemptive snapshot at index 50 (id=46fddcec, encoded size=165766, 1 rocksdb batches, 40 log entries)
I170216 09:34:32.324220 46156 storage/replica_raftstorage.go:604  [n2,s2,r1/?:/{Min-Table/0},@c42182ea80] applied preemptive snapshot in 4ms [clear=0ms batch=1ms entries=2ms commit=1ms]
I170216 09:34:32.331019 45826 storage/replica_command.go:3253  [replicate,n1,s1,r1/1:/{Min-Table/0},@c420850000] change replicas (remove {2 2 2}): read existing descriptor range_id:1 start_key:"" end_key:"\210" replicas:<node_id:1 store_id:1 replica_id:1 > next_replica_id:2 
I170216 09:34:32.333574 46118 gossip/client.go:131  [n?] started gossip client to 127.0.0.1:36683
I170216 09:34:32.335861 46063 gossip/server.go:214  [n1] received initial cluster-verification connection from {tcp 127.0.0.1:43003}
I170216 09:34:32.339091 45617 server/node.go:629  [n?] node connected via gossip and verified as part of cluster "4810b056-f230-4f31-b761-3fdc4caf6b9b"
I170216 09:34:32.340073 46065 storage/stores.go:312  [n?] wrote 1 node addresses to persistent storage
I170216 09:34:32.340606 46065 storage/stores.go:312  [n?] wrote 2 node addresses to persistent storage
I170216 09:34:32.345894 45617 kv/dist_sender.go:367  [n?] unable to determine this node's attributes for replica selection; node is most likely bootstrapping
I170216 09:34:32.349190 45617 server/node.go:334  [n?] new node allocated ID 3
I170216 09:34:32.349505 45617 gossip/gossip.go:293  [n3] NodeDescriptor set to node_id:3 address:<network_field:"tcp" address_field:"127.0.0.1:43003" > attrs:<> locality:<> 
I170216 09:34:32.349985 46229 storage/replica.go:2487  [n1,s1,r1/1:/{Min-Table/0},@c420850000] proposing ADD_REPLICA {NodeID:2 StoreID:2 ReplicaID:2}: [{NodeID:1 StoreID:1 ReplicaID:1} {NodeID:2 StoreID:2 ReplicaID:2}]
I170216 09:34:32.350263 45617 server/node.go:391  [n3] node=3: started with [[]=] engine(s) and attributes []
I170216 09:34:32.350757 45617 sql/executor.go:333  [n3] creating distSQLPlanner with address {tcp 127.0.0.1:43003}
I170216 09:34:32.366025 45826 storage/replica_raftstorage.go:414  [replicate,n1,s1,r3/1:/Table/1{1-2},@c42335e000] generated preemptive snapshot 33a34117 at index 19
I170216 09:34:32.373591 46214 storage/stores.go:312  [n1] wrote 2 node addresses to persistent storage
I170216 09:34:32.382982 45826 storage/store.go:3312  [replicate,n1,s1,r3/1:/Table/1{1-2},@c42335e000] streamed snapshot: kv pairs: 11, log entries: 9, 14ms
I170216 09:34:32.387179 46203 storage/replica_raftstorage.go:596  [n2,s2,r3/?:{-},@c4201c2380] applying preemptive snapshot at index 19 (id=33a34117, encoded size=3770, 1 rocksdb batches, 9 log entries)
I170216 09:34:32.398789 46166 storage/stores.go:312  [n2] wrote 2 node addresses to persistent storage
I170216 09:34:32.399919 45617 server/server.go:644  [n3] starting https server at 127.0.0.1:43227
I170216 09:34:32.399993 45617 server/server.go:645  [n3] starting grpc/postgres server at 127.0.0.1:43003
I170216 09:34:32.400027 45617 server/server.go:646  [n3] advertising CockroachDB node at 127.0.0.1:43003
I170216 09:34:32.401359 46203 storage/replica_raftstorage.go:604  [n2,s2,r3/?:/Table/1{1-2},@c4201c2380] applied preemptive snapshot in 14ms [clear=0ms batch=0ms entries=13ms commit=0ms]
I170216 09:34:32.405173 45826 storage/replica_command.go:3253  [replicate,n1,s1,r3/1:/Table/1{1-2},@c42335e000] change replicas (remove {2 2 2}): read existing descriptor range_id:3 start_key:"\223" end_key:"\224" replicas:<node_id:1 store_id:1 replica_id:1 > next_replica_id:2 
I170216 09:34:32.453350 46307 storage/replica.go:2487  [n1,s1,r3/1:/Table/1{1-2},@c42335e000] proposing ADD_REPLICA {NodeID:2 StoreID:2 ReplicaID:2}: [{NodeID:1 StoreID:1 ReplicaID:1} {NodeID:2 StoreID:2 ReplicaID:2}]
I170216 09:34:32.470022 45826 storage/replica_raftstorage.go:414  [replicate,n1,s1,r5/1:/Table/1{3-4},@c42335fc00] generated preemptive snapshot fce0d9c8 at index 30
I170216 09:34:32.479109 46255 server/node.go:586  [n3] bootstrapped store [n3,s3]
I170216 09:34:32.496100 46258 sql/event_log.go:95  [n3] Event: "node_join", target: 3, info: {Descriptor:{NodeID:3 Address:{NetworkField:tcp AddressField:127.0.0.1:43003} Attrs: Locality:} ClusterID:4810b056-f230-4f31-b761-3fdc4caf6b9b StartedAt:1487237672349913079 LastUp:1487237672349913079}
I170216 09:34:32.499327 45826 storage/store.go:3312  [replicate,n1,s1,r5/1:/Table/1{3-4},@c42335fc00] streamed snapshot: kv pairs: 56, log entries: 20, 22ms
I170216 09:34:32.508109 46311 storage/replica_raftstorage.go:596  [n2,s2,r5/?:{-},@c421a8f500] applying preemptive snapshot at index 30 (id=fce0d9c8, encoded size=14873, 1 rocksdb batches, 20 log entries)
I170216 09:34:32.519446 45617 server/server.go:771  [n3] done ensuring all necessary migrations have run
I170216 09:34:32.519612 45617 server/server.go:773  [n3] serving sql connections
I170216 09:34:32.523893 46311 storage/replica_raftstorage.go:604  [n2,s2,r5/?:/Table/1{3-4},@c421a8f500] applied preemptive snapshot in 16ms [clear=0ms batch=0ms entries=15ms commit=0ms]
I170216 09:34:32.526746 45826 storage/replica_command.go:3253  [replicate,n1,s1,r5/1:/Table/1{3-4},@c42335fc00] change replicas (remove {2 2 2}): read existing descriptor range_id:5 start_key:"\225" end_key:"\226" replicas:<node_id:1 store_id:1 replica_id:1 > next_replica_id:2 
I170216 09:34:32.552011 46333 storage/replica.go:2487  [n1,s1,r5/1:/Table/1{3-4},@c42335fc00] proposing ADD_REPLICA {NodeID:2 StoreID:2 ReplicaID:2}: [{NodeID:1 StoreID:1 ReplicaID:1} {NodeID:2 StoreID:2 ReplicaID:2}]
I170216 09:34:32.555234 45826 storage/replica_raftstorage.go:414  [replicate,n1,s1,r6/1:/{Table/14-Max},@c422b9c380] generated preemptive snapshot ea377802 at index 11
W170216 09:34:32.612238 45617 gossip/gossip.go:1178  [n?] no incoming or outgoing connections
I170216 09:34:32.613675 45826 storage/store.go:3312  [replicate,n1,s1,r6/1:/{Table/14-Max},@c422b9c380] streamed snapshot: kv pairs: 9, log entries: 1, 7ms
I170216 09:34:32.614472 46419 storage/replica_raftstorage.go:596  [n3,s3,r6/?:{-},@c420078380] applying preemptive snapshot at index 11 (id=ea377802, encoded size=508, 1 rocksdb batches, 1 log entries)
I170216 09:34:32.625389 46419 storage/replica_raftstorage.go:604  [n3,s3,r6/?:/{Table/14-Max},@c420078380] applied preemptive snapshot in 1ms [clear=0ms batch=0ms entries=0ms commit=0ms]
I170216 09:34:32.668257 45826 storage/replica_command.go:3253  [replicate,n1,s1,r6/1:/{Table/14-Max},@c422b9c380] change replicas (remove {3 3 2}): read existing descriptor range_id:6 start_key:"\226" end_key:"\377\377" replicas:<node_id:1 store_id:1 replica_id:1 > next_replica_id:2 
W170216 09:34:32.670325 45617 server/status/runtime.go:116  Could not parse build timestamp: parsing time "" as "2006/01/02 15:04:05": cannot parse "" as "2006"
I170216 09:34:32.672939 45617 server/config.go:482  1 storage engine initialized
I170216 09:34:32.677779 45617 server/node.go:443  [n?] store [n0,s0] not bootstrapped
I170216 09:34:32.677866 45617 storage/stores.go:296  [n?] read 0 node addresses from persistent storage
I170216 09:34:32.677950 45617 server/node.go:605  [n?] connecting to gossip network to verify cluster ID...
I170216 09:34:32.717997 46407 storage/replica.go:2487  [n1,s1,r6/1:/{Table/14-Max},@c422b9c380] proposing ADD_REPLICA {NodeID:3 StoreID:3 ReplicaID:2}: [{NodeID:1 StoreID:1 ReplicaID:1} {NodeID:3 StoreID:3 ReplicaID:2}]
I170216 09:34:32.722152 45826 storage/replica_raftstorage.go:414  [replicate,n1,s1,r4/1:/Table/1{2-3},@c422fa8700] generated preemptive snapshot 6c12c1ba at index 28
I170216 09:34:32.732287 45826 storage/store.go:3312  [replicate,n1,s1,r4/1:/Table/1{2-3},@c422fa8700] streamed snapshot: kv pairs: 31, log entries: 18, 9ms
I170216 09:34:32.733365 46466 storage/replica_raftstorage.go:596  [n3,s3,r4/?:{-},@c421a8f880] applying preemptive snapshot at index 28 (id=6c12c1ba, encoded size=11460, 1 rocksdb batches, 18 log entries)
I170216 09:34:32.734778 46466 storage/replica_raftstorage.go:604  [n3,s3,r4/?:/Table/1{2-3},@c421a8f880] applied preemptive snapshot in 1ms [clear=0ms batch=0ms entries=1ms commit=0ms]
I170216 09:34:32.737756 45826 storage/replica_command.go:3253  [replicate,n1,s1,r4/1:/Table/1{2-3},@c422fa8700] change replicas (remove {3 3 2}): read existing descriptor range_id:4 start_key:"\224" end_key:"\225" replicas:<node_id:1 store_id:1 replica_id:1 > next_replica_id:2 
I170216 09:34:32.764207 46445 gossip/client.go:131  [n?] started gossip client to 127.0.0.1:36683
I170216 09:34:32.767074 46458 gossip/server.go:214  [n1] received initial cluster-verification connection from {tcp 127.0.0.1:53985}
I170216 09:34:32.772723 45617 server/node.go:629  [n?] node connected via gossip and verified as part of cluster "4810b056-f230-4f31-b761-3fdc4caf6b9b"
I170216 09:34:32.774280 46392 storage/replica.go:2487  [n1,s1,r4/1:/Table/1{2-3},@c422fa8700] proposing ADD_REPLICA {NodeID:3 StoreID:3 ReplicaID:2}: [{NodeID:1 StoreID:1 ReplicaID:1} {NodeID:3 StoreID:3 ReplicaID:2}]
I170216 09:34:32.776245 46490 storage/stores.go:312  [n?] wrote 1 node addresses to persistent storage
I170216 09:34:32.776498 46490 storage/stores.go:312  [n?] wrote 2 node addresses to persistent storage
I170216 09:34:32.777105 46490 storage/stores.go:312  [n?] wrote 3 node addresses to persistent storage
I170216 09:34:32.778676 46384 storage/raft_transport.go:437  [n3] raft transport stream to node 1 established
I170216 09:34:32.781957 45617 kv/dist_sender.go:367  [n?] unable to determine this node's attributes for replica selection; node is most likely bootstrapping
I170216 09:34:32.785407 45826 storage/queue.go:693  [n1,replicate] purgatory is now empty
I170216 09:34:32.787112 45781 storage/replica_raftstorage.go:414  [replicate,n1,s1,r3/1:/Table/1{1-2},@c42335e000] generated preemptive snapshot 99dcde88 at index 22
I170216 09:34:32.794729 45781 storage/store.go:3312  [replicate,n1,s1,r3/1:/Table/1{1-2},@c42335e000] streamed snapshot: kv pairs: 12, log entries: 12, 2ms
I170216 09:34:32.800820 46504 storage/replica_raftstorage.go:596  [n3,s3,r3/?:{-},@c4227b0a80] applying preemptive snapshot at index 22 (id=99dcde88, encoded size=4963, 1 rocksdb batches, 12 log entries)
I170216 09:34:32.808113 46504 storage/replica_raftstorage.go:604  [n3,s3,r3/?:/Table/1{1-2},@c4227b0a80] applied preemptive snapshot in 2ms [clear=0ms batch=0ms entries=1ms commit=0ms]
I170216 09:34:32.814550 45617 server/node.go:334  [n?] new node allocated ID 4
I170216 09:34:32.814878 45617 gossip/gossip.go:293  [n4] NodeDescriptor set to node_id:4 address:<network_field:"tcp" address_field:"127.0.0.1:53985" > attrs:<> locality:<> 
I170216 09:34:32.815686 45617 server/node.go:391  [n4] node=4: started with [[]=] engine(s) and attributes []
I170216 09:34:32.816200 45617 sql/executor.go:333  [n4] creating distSQLPlanner with address {tcp 127.0.0.1:53985}
I170216 09:34:32.823279 45781 storage/replica_command.go:3253  [replicate,n1,s1,r3/1:/Table/1{1-2},@c42335e000] change replicas (remove {3 3 3}): read existing descriptor range_id:3 start_key:"\223" end_key:"\224" replicas:<node_id:1 store_id:1 replica_id:1 > replicas:<node_id:2 store_id:2 replica_id:2 > next_replica_id:3 
I170216 09:34:32.831712 46515 storage/stores.go:312  [n1] wrote 3 node addresses to persistent storage
I170216 09:34:32.834958 45617 server/server.go:644  [n4] starting https server at 127.0.0.1:51398
I170216 09:34:32.835051 45617 server/server.go:645  [n4] starting grpc/postgres server at 127.0.0.1:53985
I170216 09:34:32.835095 45617 server/server.go:646  [n4] advertising CockroachDB node at 127.0.0.1:53985
I170216 09:34:32.841491 46516 storage/stores.go:312  [n3] wrote 3 node addresses to persistent storage
I170216 09:34:32.848557 46517 storage/stores.go:312  [n2] wrote 3 node addresses to persistent storage
I170216 09:34:32.896047 45617 server/server.go:771  [n4] done ensuring all necessary migrations have run
I170216 09:34:32.896156 45617 server/server.go:773  [n4] serving sql connections
I170216 09:34:32.936113 46463 server/node.go:586  [n4] bootstrapped store [n4,s4]
W170216 09:34:32.970153 45617 gossip/gossip.go:1178  [n?] no incoming or outgoing connections
I170216 09:34:32.986816 46521 storage/replica.go:2487  [n1,s1,r3/1:/Table/1{1-2},@c42335e000] proposing ADD_REPLICA {NodeID:3 StoreID:3 ReplicaID:3}: [{NodeID:1 StoreID:1 ReplicaID:1} {NodeID:2 StoreID:2 ReplicaID:2} {NodeID:3 StoreID:3 ReplicaID:3}]
W170216 09:34:32.997599 45617 server/status/runtime.go:116  Could not parse build timestamp: parsing time "" as "2006/01/02 15:04:05": cannot parse "" as "2006"
I170216 09:34:33.000395 45617 server/config.go:482  1 storage engine initialized
I170216 09:34:33.002033 45617 server/node.go:443  [n?] store [n0,s0] not bootstrapped
I170216 09:34:33.002089 45617 storage/stores.go:296  [n?] read 0 node addresses from persistent storage
I170216 09:34:33.002158 45617 server/node.go:605  [n?] connecting to gossip network to verify cluster ID...
I170216 09:34:33.028527 45781 storage/replica_command.go:3253  [replicate,n1,s1,r3/1:/Table/1{1-2},@c42335e000] change replicas (remove {3 3 3}): read existing descriptor range_id:3 start_key:"\223" end_key:"\224" replicas:<node_id:1 store_id:1 replica_id:1 > replicas:<node_id:2 store_id:2 replica_id:2 > next_replica_id:3 
I170216 09:34:33.044233 46546 sql/event_log.go:95  [n4] Event: "node_join", target: 4, info: {Descriptor:{NodeID:4 Address:{NetworkField:tcp AddressField:127.0.0.1:53985} Attrs: Locality:} ClusterID:4810b056-f230-4f31-b761-3fdc4caf6b9b StartedAt:1487237672815371697 LastUp:1487237672815371697}
I170216 09:34:33.084039 46399 storage/replica.go:2487  [n1,s1,r3/1:/Table/1{1-2},@c42335e000] proposing ADD_REPLICA {NodeID:3 StoreID:3 ReplicaID:3}: [{NodeID:1 StoreID:1 ReplicaID:1} {NodeID:2 StoreID:2 ReplicaID:2} {NodeID:3 StoreID:3 ReplicaID:3}]
I170216 09:34:33.097438 45781 storage/replica_raftstorage.go:414  [replicate,n1,s1,r5/1:/Table/1{3-4},@c42335fc00] generated preemptive snapshot 55b8d21a at index 41
I170216 09:34:33.106492 46660 gossip/client.go:131  [n?] started gossip client to 127.0.0.1:36683
I170216 09:34:33.111129 46649 gossip/server.go:214  [n1] received initial cluster-verification connection from {tcp 127.0.0.1:46134}
I170216 09:34:33.114872 45617 server/node.go:629  [n?] node connected via gossip and verified as part of cluster "4810b056-f230-4f31-b761-3fdc4caf6b9b"
I170216 09:34:33.116771 46712 storage/stores.go:312  [n?] wrote 1 node addresses to persistent storage
I170216 09:34:33.117040 46712 storage/stores.go:312  [n?] wrote 2 node addresses to persistent storage
I170216 09:34:33.117867 46709 storage/stores.go:312  [n?] wrote 3 node addresses to persistent storage
I170216 09:34:33.119143 46709 storage/stores.go:312  [n?] wrote 4 node addresses to persistent storage
I170216 09:34:33.142419 45617 kv/dist_sender.go:367  [n?] unable to determine this node's attributes for replica selection; node is most likely bootstrapping
I170216 09:34:33.150384 45617 server/node.go:334  [n?] new node allocated ID 5
I170216 09:34:33.150671 45617 gossip/gossip.go:293  [n5] NodeDescriptor set to node_id:5 address:<network_field:"tcp" address_field:"127.0.0.1:46134" > attrs:<> locality:<> 
I170216 09:34:33.151374 45617 server/node.go:391  [n5] node=5: started with [[]=] engine(s) and attributes []
I170216 09:34:33.156291 45617 sql/executor.go:333  [n5] creating distSQLPlanner with address {tcp 127.0.0.1:46134}
I170216 09:34:33.158674 46649 gossip/server.go:265  [n1] refusing gossip from node 5 (max 3 conns); forwarding to 3 ({tcp 127.0.0.1:43003})
I170216 09:34:33.159773 46740 storage/stores.go:312  [n1] wrote 4 node addresses to persistent storage
I170216 09:34:33.162994 46660 gossip/client.go:136  [n5] closing client to node 1 (127.0.0.1:36683): received forward from node 1 to 3 (127.0.0.1:43003)
I170216 09:34:33.164391 46631 server/node.go:586  [n5] bootstrapped store [n5,s5]
I170216 09:34:33.168202 46658 gossip/gossip.go:1192  [n5] node has connected to cluster via gossip
I170216 09:34:33.168463 46759 storage/stores.go:312  [n4] wrote 4 node addresses to persistent storage
I170216 09:34:33.169242 46658 storage/stores.go:312  [n5] wrote 4 node addresses to persistent storage
I170216 09:34:33.180866 46741 storage/stores.go:312  [n3] wrote 4 node addresses to persistent storage
I170216 09:34:33.185200 46728 storage/stores.go:312  [n2] wrote 4 node addresses to persistent storage
I170216 09:34:33.185458 45781 storage/store.go:3312  [replicate,n1,s1,r5/1:/Table/1{3-4},@c42335fc00] streamed snapshot: kv pairs: 77, log entries: 31, 10ms
I170216 09:34:33.185569 46526 storage/replica_raftstorage.go:596  [n4,s4,r5/?:{-},@c423430e00] applying preemptive snapshot at index 41 (id=55b8d21a, encoded size=24298, 1 rocksdb batches, 31 log entries)
I170216 09:34:33.187656 46526 storage/replica_raftstorage.go:604  [n4,s4,r5/?:/Table/1{3-4},@c423430e00] applied preemptive snapshot in 2ms [clear=0ms batch=0ms entries=1ms commit=0ms]
I170216 09:34:33.191031 45617 server/server.go:644  [n5] starting https server at 127.0.0.1:45825
I170216 09:34:33.191095 45617 server/server.go:645  [n5] starting grpc/postgres server at 127.0.0.1:46134
I170216 09:34:33.191131 45617 server/server.go:646  [n5] advertising CockroachDB node at 127.0.0.1:46134
I170216 09:34:33.205193 45781 storage/replica_command.go:3253  [replicate,n1,s1,r5/1:/Table/1{3-4},@c42335fc00] change replicas (remove {4 4 3}): read existing descriptor range_id:5 start_key:"\225" end_key:"\226" replicas:<node_id:1 store_id:1 replica_id:1 > replicas:<node_id:2 store_id:2 replica_id:2 > next_replica_id:3 
I170216 09:34:33.218600 45617 server/server.go:771  [n5] done ensuring all necessary migrations have run
I170216 09:34:33.218695 45617 server/server.go:773  [n5] serving sql connections
I170216 09:34:33.266738 46634 sql/event_log.go:95  [n5] Event: "node_join", target: 5, info: {Descriptor:{NodeID:5 Address:{NetworkField:tcp AddressField:127.0.0.1:46134} Attrs: Locality:} ClusterID:4810b056-f230-4f31-b761-3fdc4caf6b9b StartedAt:1487237673151096664 LastUp:1487237673151096664}
I170216 09:34:33.340080 46522 gossip/client.go:131  [n5] started gossip client to 127.0.0.1:43003
I170216 09:34:33.371459 46896 storage/replica.go:2487  [n1,s1,r5/1:/Table/1{3-4},@c42335fc00] proposing ADD_REPLICA {NodeID:4 StoreID:4 ReplicaID:3}: [{NodeID:1 StoreID:1 ReplicaID:1} {NodeID:2 StoreID:2 ReplicaID:2} {NodeID:4 StoreID:4 ReplicaID:3}]
I170216 09:34:33.381753 45781 storage/replica_command.go:3253  [replicate,n1,s1,r5/1:/Table/1{3-4},@c42335fc00] change replicas (remove {4 4 3}): read existing descriptor range_id:5 start_key:"\225" end_key:"\226" replicas:<node_id:1 store_id:1 replica_id:1 > replicas:<node_id:2 store_id:2 replica_id:2 > next_replica_id:3 
I170216 09:34:33.421983 46898 storage/replica.go:2487  [n1,s1,r5/1:/Table/1{3-4},@c42335fc00] proposing ADD_REPLICA {NodeID:4 StoreID:4 ReplicaID:3}: [{NodeID:1 StoreID:1 ReplicaID:1} {NodeID:2 StoreID:2 ReplicaID:2} {NodeID:4 StoreID:4 ReplicaID:3}]
I170216 09:34:33.432267 45781 storage/replica_raftstorage.go:414  [replicate,n1,s1,r4/1:/Table/1{2-3},@c422fa8700] generated preemptive snapshot ed86a14f at index 36
I170216 09:34:33.450529 46858 storage/raft_transport.go:437  [n4] raft transport stream to node 1 established
I170216 09:34:33.499576 45781 storage/store.go:3312  [replicate,n1,s1,r4/1:/Table/1{2-3},@c422fa8700] streamed snapshot: kv pairs: 42, log entries: 26, 2ms
I170216 09:34:33.500874 46900 storage/replica_raftstorage.go:596  [n5,s5,r4/?:{-},@c42182e700] applying preemptive snapshot at index 36 (id=ed86a14f, encoded size=16939, 1 rocksdb batches, 26 log entries)
I170216 09:34:33.502657 46900 storage/replica_raftstorage.go:604  [n5,s5,r4/?:/Table/1{2-3},@c42182e700] applied preemptive snapshot in 1ms [clear=0ms batch=0ms entries=1ms commit=0ms]
I170216 09:34:33.511087 45781 storage/replica_command.go:3253  [replicate,n1,s1,r4/1:/Table/1{2-3},@c422fa8700] change replicas (remove {5 5 3}): read existing descriptor range_id:4 start_key:"\224" end_key:"\225" replicas:<node_id:1 store_id:1 replica_id:1 > replicas:<node_id:3 store_id:3 replica_id:2 > next_replica_id:3 
I170216 09:34:33.538790 46938 storage/replica.go:2487  [n1,s1,r4/1:/Table/1{2-3},@c422fa8700] proposing ADD_REPLICA {NodeID:5 StoreID:5 ReplicaID:3}: [{NodeID:1 StoreID:1 ReplicaID:1} {NodeID:3 StoreID:3 ReplicaID:2} {NodeID:5 StoreID:5 ReplicaID:3}]
I170216 09:34:33.564587 45781 storage/replica_raftstorage.go:414  [replicate,n1,s1,r2/1:/Table/{0-11},@c42258ce00] generated preemptive snapshot a7e162c3 at index 30
I170216 09:34:33.568654 45781 storage/store.go:3312  [replicate,n1,s1,r2/1:/Table/{0-11},@c42258ce00] streamed snapshot: kv pairs: 35, log entries: 20, 3ms
I170216 09:34:33.570541 46903 storage/replica_raftstorage.go:596  [n4,s4,r2/?:{-},@c421950e00] applying preemptive snapshot at index 30 (id=a7e162c3, encoded size=15180, 1 rocksdb batches, 20 log entries)
I170216 09:34:33.571992 46903 storage/replica_raftstorage.go:604  [n4,s4,r2/?:/Table/{0-11},@c421950e00] applied preemptive snapshot in 1ms [clear=0ms batch=0ms entries=1ms commit=0ms]
I170216 09:34:33.576822 45781 storage/replica_command.go:3253  [replicate,n1,s1,r2/1:/Table/{0-11},@c42258ce00] change replicas (remove {4 4 3}): read existing descriptor range_id:2 start_key:"\210" end_key:"\223" replicas:<node_id:1 store_id:1 replica_id:1 > replicas:<node_id:2 store_id:2 replica_id:2 > next_replica_id:3 
I170216 09:34:33.587541 46879 storage/raft_transport.go:437  [n5] raft transport stream to node 1 established
I170216 09:34:33.610937 46953 storage/replica.go:2487  [n1,s1,r2/1:/Table/{0-11},@c42258ce00] proposing ADD_REPLICA {NodeID:4 StoreID:4 ReplicaID:3}: [{NodeID:1 StoreID:1 ReplicaID:1} {NodeID:2 StoreID:2 ReplicaID:2} {NodeID:4 StoreID:4 ReplicaID:3}]
I170216 09:34:33.636687 45781 storage/replica_raftstorage.go:414  [replicate,n1,s1,r6/1:/{Table/14-Max},@c422b9c380] generated preemptive snapshot ec9d3e1b at index 16
I170216 09:34:33.647500 45781 storage/store.go:3312  [replicate,n1,s1,r6/1:/{Table/14-Max},@c422b9c380] streamed snapshot: kv pairs: 11, log entries: 6, 10ms
I170216 09:34:33.648531 46909 storage/replica_raftstorage.go:596  [n4,s4,r6/?:{-},@c421c9dc00] applying preemptive snapshot at index 16 (id=ec9d3e1b, encoded size=2178, 1 rocksdb batches, 6 log entries)
I170216 09:34:33.649771 46909 storage/replica_raftstorage.go:604  [n4,s4,r6/?:/{Table/14-Max},@c421c9dc00] applied preemptive snapshot in 1ms [clear=0ms batch=0ms entries=0ms commit=0ms]
I170216 09:34:33.652568 45781 storage/replica_command.go:3253  [replicate,n1,s1,r6/1:/{Table/14-Max},@c422b9c380] change replicas (remove {4 4 3}): read existing descriptor range_id:6 start_key:"\226" end_key:"\377\377" replicas:<node_id:1 store_id:1 replica_id:1 > replicas:<node_id:3 store_id:3 replica_id:2 > next_replica_id:3 
I170216 09:34:33.686810 46969 storage/replica.go:2487  [n1,s1,r6/1:/{Table/14-Max},@c422b9c380] proposing ADD_REPLICA {NodeID:4 StoreID:4 ReplicaID:3}: [{NodeID:1 StoreID:1 ReplicaID:1} {NodeID:3 StoreID:3 ReplicaID:2} {NodeID:4 StoreID:4 ReplicaID:3}]
I170216 09:34:33.692394 45781 storage/replica_raftstorage.go:414  [replicate,n1,s1,r1/1:/{Min-Table/0},@c420850000] generated preemptive snapshot 0fa022a6 at index 93
I170216 09:34:33.743912 45781 storage/store.go:3312  [replicate,n1,s1,r1/1:/{Min-Table/0},@c420850000] streamed snapshot: kv pairs: 1379, log entries: 83, 50ms
I170216 09:34:33.745437 46913 storage/replica_raftstorage.go:596  [n3,s3,r1/?:{-},@c42206c700] applying preemptive snapshot at index 93 (id=0fa022a6, encoded size=451926, 1 rocksdb batches, 83 log entries)
I170216 09:34:33.752751 46913 storage/replica_raftstorage.go:604  [n3,s3,r1/?:/{Min-Table/0},@c42206c700] applied preemptive snapshot in 7ms [clear=0ms batch=0ms entries=4ms commit=2ms]
I170216 09:34:33.755605 45781 storage/replica_command.go:3253  [replicate,n1,s1,r1/1:/{Min-Table/0},@c420850000] change replicas (remove {3 3 3}): read existing descriptor range_id:1 start_key:"" end_key:"\210" replicas:<node_id:1 store_id:1 replica_id:1 > replicas:<node_id:2 store_id:2 replica_id:2 > next_replica_id:3 
I170216 09:34:33.777920 47003 storage/replica.go:2487  [n1,s1,r1/1:/{Min-Table/0},@c420850000] proposing ADD_REPLICA {NodeID:3 StoreID:3 ReplicaID:3}: [{NodeID:1 StoreID:1 ReplicaID:1} {NodeID:2 StoreID:2 ReplicaID:2} {NodeID:3 StoreID:3 ReplicaID:3}]
I170216 09:34:33.930544 47058 storage/replica_command.go:2397  [n1,s1,r1/1:/{Min-Table/0},@c420850000] initiating a split of this range at key "m" [r7]
I170216 09:34:34.032261 45617 storage/replica_raftstorage.go:414  [n1,s1,r7/1:{"m"-/Table/0},@c4210b6a80] generated preemptive snapshot 5efc1af1 at index 10
I170216 09:34:34.035614 46959 storage/replica_raftstorage.go:596  [n4,s4,r7/?:{-},@c421281500] applying preemptive snapshot at index 10 (id=5efc1af1, encoded size=513, 1 rocksdb batches, 0 log entries)
I170216 09:34:34.036333 46959 storage/replica_raftstorage.go:604  [n4,s4,r7/?:{"m"-/Table/0},@c421281500] applied preemptive snapshot in 1ms [clear=0ms batch=0ms entries=0ms commit=0ms]
I170216 09:34:34.039533 45617 storage/store.go:3312  [n1,s1,r7/1:{"m"-/Table/0},@c4210b6a80] streamed snapshot: kv pairs: 9, log entries: 0, 6ms
I170216 09:34:34.042280 45617 storage/replica_command.go:3253  [n1,s1,r7/1:{"m"-/Table/0},@c4210b6a80] change replicas (remove {4 4 4}): read existing descriptor range_id:7 start_key:"m" end_key:"\210" replicas:<node_id:1 store_id:1 replica_id:1 > replicas:<node_id:2 store_id:2 replica_id:2 > replicas:<node_id:3 store_id:3 replica_id:3 > next_replica_id:4 
I170216 09:34:34.082855 47095 storage/replica.go:2487  [n1,s1,r7/1:{"m"-/Table/0},@c4210b6a80] proposing ADD_REPLICA {NodeID:4 StoreID:4 ReplicaID:4}: [{NodeID:1 StoreID:1 ReplicaID:1} {NodeID:2 StoreID:2 ReplicaID:2} {NodeID:3 StoreID:3 ReplicaID:3} {NodeID:4 StoreID:4 ReplicaID:4}]
I170216 09:34:34.123565 45617 storage/replica_raftstorage.go:414  [n1,s1,r7/1:{"m"-/Table/0},@c4210b6a80] generated preemptive snapshot 8d8e4210 at index 15
I170216 09:34:34.133747 45617 storage/store.go:3312  [n1,s1,r7/1:{"m"-/Table/0},@c4210b6a80] streamed snapshot: kv pairs: 10, log entries: 5, 9ms
I170216 09:34:34.134895 47108 storage/replica_raftstorage.go:596  [n5,s5,r7/?:{-},@c422618700] applying preemptive snapshot at index 15 (id=8d8e4210, encoded size=2202, 1 rocksdb batches, 5 log entries)
I170216 09:34:34.136435 47108 storage/replica_raftstorage.go:604  [n5,s5,r7/?:{"m"-/Table/0},@c422618700] applied preemptive snapshot in 1ms [clear=0ms batch=0ms entries=0ms commit=0ms]
I170216 09:34:34.144221 45617 storage/replica_command.go:3253  [n1,s1,r7/1:{"m"-/Table/0},@c4210b6a80] change replicas (remove {5 5 5}): read existing descriptor range_id:7 start_key:"m" end_key:"\210" replicas:<node_id:1 store_id:1 replica_id:1 > replicas:<node_id:2 store_id:2 replica_id:2 > replicas:<node_id:3 store_id:3 replica_id:3 > replicas:<node_id:4 store_id:4 replica_id:4 > next_replica_id:5 
I170216 09:34:34.170034 47154 storage/replica.go:2487  [n1,s1,r7/1:{"m"-/Table/0},@c4210b6a80] proposing ADD_REPLICA {NodeID:5 StoreID:5 ReplicaID:5}: [{NodeID:1 StoreID:1 ReplicaID:1} {NodeID:2 StoreID:2 ReplicaID:2} {NodeID:3 StoreID:3 ReplicaID:3} {NodeID:4 StoreID:4 ReplicaID:4} {NodeID:5 StoreID:5 ReplicaID:5}]
I170216 09:34:35.606977 45781 storage/replica_command.go:3253  [replicate,n1,s1,r7/1:{"m"-/Table/0},@c4210b6a80] change replicas (remove {3 3 3}): read existing descriptor range_id:7 start_key:"m" end_key:"\210" replicas:<node_id:1 store_id:1 replica_id:1 > replicas:<node_id:2 store_id:2 replica_id:2 > replicas:<node_id:3 store_id:3 replica_id:3 > replicas:<node_id:4 store_id:4 replica_id:4 > replicas:<node_id:5 store_id:5 replica_id:5 > next_replica_id:6 
I170216 09:34:35.676031 47190 storage/replica.go:2487  [n1,s1,r7/1:{"m"-/Table/0},@c4210b6a80] proposing REMOVE_REPLICA {NodeID:3 StoreID:3 ReplicaID:3}: [{NodeID:1 StoreID:1 ReplicaID:1} {NodeID:2 StoreID:2 ReplicaID:2} {NodeID:5 StoreID:5 ReplicaID:5} {NodeID:4 StoreID:4 ReplicaID:4}]
I170216 09:34:35.707178 45781 storage/replica_command.go:3253  [replicate,n1,s1,r7/1:{"m"-/Table/0},@c4210b6a80] change replicas (remove {2 2 2}): read existing descriptor range_id:7 start_key:"m" end_key:"\210" replicas:<node_id:1 store_id:1 replica_id:1 > replicas:<node_id:2 store_id:2 replica_id:2 > replicas:<node_id:5 store_id:5 replica_id:5 > replicas:<node_id:4 store_id:4 replica_id:4 > next_replica_id:6 
I170216 09:34:35.757593 46514 storage/store.go:3164  [n3,s3,r7/3:{"m"-/Table/0},@c4202e0000] added to replica GC queue (peer suggestion)
I170216 09:34:35.913138 46357 storage/store.go:2134  [replicaGC,n3,s3,r7/3:{"m"-/Table/0},@c4202e0000] removing replica
I170216 09:34:35.920086 47171 storage/replica.go:2487  [n1,s1,r7/1:{"m"-/Table/0},@c4210b6a80] proposing REMOVE_REPLICA {NodeID:2 StoreID:2 ReplicaID:2}: [{NodeID:1 StoreID:1 ReplicaID:1} {NodeID:4 StoreID:4 ReplicaID:4} {NodeID:5 StoreID:5 ReplicaID:5}]
I170216 09:34:35.922246 46357 storage/replica.go:735  [replicaGC,n3,s3,r7/3:{"m"-/Table/0},@c4202e0000] removed 11 (0+11) keys in 2ms [clear=2ms commit=0ms]
I170216 09:34:35.981085 46159 storage/store.go:3164  [n2,s2,r7/2:{"m"-/Table/0},@c422618380] added to replica GC queue (peer suggestion)
I170216 09:34:36.009469 46091 storage/store.go:2134  [replicaGC,n2,s2,r7/2:{"m"-/Table/0},@c422618380] removing replica
I170216 09:34:36.032229 46091 storage/replica.go:735  [replicaGC,n2,s2,r7/2:{"m"-/Table/0},@c422618380] removed 11 (0+11) keys in 6ms [clear=1ms commit=5ms]
W170216 09:34:36.276489 45949 storage/raft_transport.go:443  [n1] raft transport stream to node 2 failed: rpc error: code = 13 desc = transport is closing
I170216 09:34:36.278936 47215 vendor/google.golang.org/grpc/server.go:645  grpc: Server.processUnaryRPC failed to write status stream error: code = 1 desc = "context canceled"
W170216 09:34:36.280801 46879 storage/raft_transport.go:443  [n5] raft transport stream to node 1 failed: rpc error: code = 13 desc = transport is closing
W170216 09:34:36.283668 46384 storage/raft_transport.go:443  [n3] raft transport stream to node 1 failed: rpc error: code = 13 desc = transport is closing
W170216 09:34:36.284525 46658 gossip/gossip.go:1178  [n5] no incoming or outgoing connections
W170216 09:34:36.285225 46225 storage/raft_transport.go:443  [n1] raft transport stream to node 3 failed: rpc error: code = 13 desc = transport is closing
W170216 09:34:36.285866 46844 storage/raft_transport.go:443  [n1] raft transport stream to node 4 failed: rpc error: code = 13 desc = transport is closing
W170216 09:34:36.286233 46157 storage/raft_transport.go:443  [n2] raft transport stream to node 1 failed: rpc error: code = 13 desc = transport is closing
W170216 09:34:36.288870 46858 storage/raft_transport.go:443  [n4] raft transport stream to node 1 failed: rpc error: code = 13 desc = transport is closing
I170216 09:34:36.380395 45639 kv/transport_race.go:71  transport race promotion: ran 43 iterations on up to 454 requests
--- PASS: TestReplicateQueueDownReplicate (5.19s)
=== RUN   TestEagerReplication
I170216 09:34:36.430342 47134 gossip/gossip.go:293  [n1] NodeDescriptor set to node_id:1 address:<network_field:"" address_field:"" > attrs:<> locality:<> 
I170216 09:34:36.454570 47166 storage/split_queue.go:98  [split,s1,r1/1:/M{in-ax},@c422d1b500] splitting at key /Table/0/0
I170216 09:34:36.458202 47166 storage/replica_command.go:2397  [split,s1,r1/1:/M{in-ax},@c422d1b500] initiating a split of this range at key /Table/0 [r2]
I170216 09:34:36.468553 47166 storage/split_queue.go:98  [split,s1,r2/1:/{Table/0-Max},@c4223ae000] splitting at key /Table/11/0
I170216 09:34:36.468760 47166 storage/replica_command.go:2397  [split,s1,r2/1:/{Table/0-Max},@c4223ae000] initiating a split of this range at key /Table/11 [r3]
W170216 09:34:36.511318 47166 storage/stores.go:218  range not contained in one range: [/Meta2/Table/11,/Table/11/NULL), but have [/Min,/Table/0)
W170216 09:34:36.527952 47299 storage/intent_resolver.go:338  [n1,s1,r1/1:/{Min-Table/0}]: failed to push during intent resolution: failed to push "unnamed" id=0d822d51 key=/Local/Range/"\x88"/RangeDescriptor rw=true pri=0.02199309 iso=SERIALIZABLE stat=PENDING epo=0 ts=0.000000123,165 orig=0.000000123,50 max=0.000000123,50 wto=false rop=false
W170216 09:34:36.558073 47300 storage/intent_resolver.go:338  [n1,s1,r1/1:/{Min-Table/0}]: failed to push during intent resolution: failed to push "unnamed" id=0d822d51 key=/Local/Range/"\x88"/RangeDescriptor rw=true pri=0.02199309 iso=SERIALIZABLE stat=PENDING epo=0 ts=0.000000123,165 orig=0.000000123,50 max=0.000000123,50 wto=false rop=false
W170216 09:34:36.568960 47301 storage/intent_resolver.go:338  [n1,s1,r1/1:/{Min-Table/0}]: failed to push during intent resolution: failed to push "unnamed" id=0d822d51 key=/Local/Range/"\x88"/RangeDescriptor rw=true pri=0.02199309 iso=SERIALIZABLE stat=PENDING epo=1 ts=0.000000123,165 orig=0.000000123,50 max=0.000000123,50 wto=false rop=false
W170216 09:34:36.576195 47314 storage/intent_resolver.go:338  [n1,s1,r1/1:/{Min-Table/0}]: failed to push during intent resolution: failed to push "unnamed" id=0d822d51 key=/Local/Range/"\x88"/RangeDescriptor rw=true pri=0.02199309 iso=SERIALIZABLE stat=PENDING epo=1 ts=0.000000123,165 orig=0.000000123,50 max=0.000000123,50 wto=false rop=false
I170216 09:34:36.589762 47166 storage/split_queue.go:98  [split,s1,r3/1:/{Table/11-Max},@c4223afc00] splitting at key /Table/12/0
I170216 09:34:36.589981 47166 storage/replica_command.go:2397  [split,s1,r3/1:/{Table/11-Max},@c4223afc00] initiating a split of this range at key /Table/12 [r4]
I170216 09:34:36.651854 47166 storage/split_queue.go:98  [split,s1,r4/1:/{Table/12-Max},@c420f26700] splitting at key /Table/13/0
I170216 09:34:36.652679 47166 storage/replica_command.go:2397  [split,s1,r4/1:/{Table/12-Max},@c420f26700] initiating a split of this range at key /Table/13 [r5]
I170216 09:34:36.773064 47166 storage/split_queue.go:98  [split,s1,r5/1:/{Table/13-Max},@c420111180] splitting at key /Table/14/0
I170216 09:34:36.807733 47166 storage/replica_command.go:2397  [split,s1,r5/1:/{Table/13-Max},@c420111180] initiating a split of this range at key /Table/14 [r6]
I170216 09:34:36.875959 47134 util/stop/stopper.go:493  quiescing; tasks left:
1      storage/intent_resolver.go:284
W170216 09:34:36.883932 47315 storage/replica.go:2218  [s1,r5/1:/Table/1{3-4},@c420111180] shutdown cancellation after 0.0s of attempting command GC [/Table/13,/Table/13/NULL)
W170216 09:34:36.886611 47315 storage/intent_resolver.go:395  could not GC completed transaction anchored at /Local/Range/"\x95"/RangeDescriptor: result is ambiguous (server shutdown)
--- PASS: TestEagerReplication (0.53s)
=== RUN   TestTimeSeriesMaintenanceQueue
I170216 09:34:36.958586 47177 gossip/gossip.go:293  [n1] NodeDescriptor set to node_id:1 address:<network_field:"" address_field:"" > attrs:<> locality:<> 
I170216 09:34:36.972893 47177 storage/store.go:1261  [n1,s1]: failed initial metrics computation: [n1,s1]: system config not yet available
I170216 09:34:36.983596 47177 storage/replica_command.go:2397  [s1,r1/1:/M{in-ax},@c421951500] initiating a split of this range at key "c" [r2]
I170216 09:34:36.996270 47177 storage/replica_command.go:2397  [s1,r1/1:{/Min-"c"},@c421951500] initiating a split of this range at key "b" [r3]
I170216 09:34:37.005616 47177 storage/replica_command.go:2397  [s1,r1/1:{/Min-"b"},@c421951500] initiating a split of this range at key "a" [r4]
--- PASS: TestTimeSeriesMaintenanceQueue (0.10s)
=== RUN   TestTimeSeriesMaintenanceQueueServer
W170216 09:34:37.204694 47367 server/status/runtime.go:116  Could not parse build timestamp: parsing time "" as "2006/01/02 15:04:05": cannot parse "" as "2006"
I170216 09:34:37.207063 47367 server/config.go:482  1 storage engine initialized
I170216 09:34:37.207961 47367 server/node.go:443  [n?] store [n0,s0] not bootstrapped
I170216 09:34:37.218734 47367 server/node.go:372  [n?] **** cluster dea231b7-6b30-49ac-aa56-0967f0ad8326 has been created
I170216 09:34:37.218801 47367 server/node.go:373  [n?] **** add additional nodes by specifying --join=127.0.0.1:50078
I170216 09:34:37.240871 47367 storage/store.go:1261  [n1] [n1,s1]: failed initial metrics computation: [n1,s1]: system config not yet available
I170216 09:34:37.241003 47367 server/node.go:456  [n1] initialized store [n1,s1]: {Capacity:536870912 Available:536870912 RangeCount:1 LeaseCount:0}
I170216 09:34:37.257081 47367 server/node.go:341  [n1] node ID 1 initialized
I170216 09:34:37.257302 47367 gossip/gossip.go:293  [n1] NodeDescriptor set to node_id:1 address:<network_field:"tcp" address_field:"127.0.0.1:50078" > attrs:<> locality:<> 
I170216 09:34:37.258021 47367 storage/stores.go:296  [n1] read 0 node addresses from persistent storage
I170216 09:34:37.258175 47367 server/node.go:605  [n1] connecting to gossip network to verify cluster ID...
I170216 09:34:37.258766 47367 server/node.go:629  [n1] node connected via gossip and verified as part of cluster "dea231b7-6b30-49ac-aa56-0967f0ad8326"
I170216 09:34:37.259111 47367 server/node.go:391  [n1] node=1: started with [[]=] engine(s) and attributes []
I170216 09:34:37.259534 47367 sql/executor.go:333  [n1] creating distSQLPlanner with address {tcp 127.0.0.1:50078}
I170216 09:34:37.273473 47442 storage/split_queue.go:98  [split,n1,s1,r1/1:/M{in-ax},@c4201c2380] splitting at key /Table/0/0
I170216 09:34:37.303788 47367 server/server.go:644  [n1] starting https server at 127.0.0.1:47107
I170216 09:34:37.303858 47367 server/server.go:645  [n1] starting grpc/postgres server at 127.0.0.1:50078
I170216 09:34:37.303894 47367 server/server.go:646  [n1] advertising CockroachDB node at 127.0.0.1:50078
I170216 09:34:37.323551 47442 storage/replica_command.go:2397  [split,n1,s1,r1/1:/M{in-ax},@c4201c2380] initiating a split of this range at key /Table/0 [r2]
I170216 09:34:37.402733 47442 storage/split_queue.go:98  [split,n1,s1,r2/1:/{Table/0-Max},@c421720a80] splitting at key /Table/11/0
I170216 09:34:37.402938 47442 storage/replica_command.go:2397  [split,n1,s1,r2/1:/{Table/0-Max},@c421720a80] initiating a split of this range at key /Table/11 [r3]
I170216 09:34:37.427369 47430 sql/event_log.go:95  [n1] Event: "node_join", target: 1, info: {Descriptor:{NodeID:1 Address:{NetworkField:tcp AddressField:127.0.0.1:50078} Attrs: Locality:} ClusterID:dea231b7-6b30-49ac-aa56-0967f0ad8326 StartedAt:1487237677258824724 LastUp:1487237677258824724}
I170216 09:34:37.445231 47367 sql/event_log.go:95  [n1] Event: "alter_table", target: 12, info: {TableName:eventlog Statement:ALTER TABLE system.eventlog ALTER COLUMN uniqueID SET DEFAULT uuid_v4() User:node MutationID:0 CascadeDroppedViews:[]}
I170216 09:34:37.592763 47442 storage/split_queue.go:98  [split,n1,s1,r3/1:/{Table/11-Max},@c422618000] splitting at key /Table/12/0
I170216 09:34:37.592986 47442 storage/replica_command.go:2397  [split,n1,s1,r3/1:/{Table/11-Max},@c422618000] initiating a split of this range at key /Table/12 [r4]
I170216 09:34:37.635876 47367 server/server.go:771  [n1] done ensuring all necessary migrations have run
I170216 09:34:37.635964 47367 server/server.go:773  [n1] serving sql connections
I170216 09:34:37.834218 47442 storage/split_queue.go:98  [split,n1,s1,r4/1:/{Table/12-Max},@c422b9ca80] splitting at key /Table/13/0
I170216 09:34:37.834723 47442 storage/replica_command.go:2397  [split,n1,s1,r4/1:/{Table/12-Max},@c422b9ca80] initiating a split of this range at key /Table/13 [r5]
I170216 09:34:37.880846 47442 storage/split_queue.go:98  [split,n1,s1,r5/1:/{Table/13-Max},@c4202e1880] splitting at key /Table/14/0
I170216 09:34:37.881095 47442 storage/replica_command.go:2397  [split,n1,s1,r5/1:/{Table/13-Max},@c4202e1880] initiating a split of this range at key /Table/14 [r6]
I170216 09:34:37.993216 47641 storage/replica_command.go:2397  [n1,s1,r1/1:/{Min-Table/0},@c4201c2380] initiating a split of this range at key /System/tsd/test.metric/source1/10s/2016-11-18T09:00:00Z [r7]
I170216 09:34:38.058095 47367 util/stop/stopper.go:493  quiescing; tasks left:
1      storage/queue.go:523
I170216 09:34:38.066080 47451 kv/transport_race.go:71  transport race promotion: ran 37 iterations on up to 173 requests
--- PASS: TestTimeSeriesMaintenanceQueueServer (1.06s)
=== RUN   Example_rebalancing
--- PASS: Example_rebalancing (2.10s)
PASS
Found 1 data race(s)


ERROR: exit status 66

make: *** [stress] Error 1
43 runs completed, 1 failures, over 9m54s
FAIL
Makefile:173: recipe for target 'stress' failed

```

### PR DESCRIPTION
**Pull request by mrtracy**
Move the node liveness's heartbeatCallback field under the existing mutex.

Fixes #13616

---
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/13680)

### CODE REVIEW

**Comment by mrtracy** [comment]
Thanks for finding this @a-robinson

**Comment by bdarnell** [comment]
:lgtm:

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/13680#-:-KdTUC5Q3eaG4QHUQ_BC:bnfp4nl)*

**Review by petermattis — APPROVED** [review]

**Review by a-robinson — APPROVED** [review]
Thanks!

File: pkg/storage/node_liveness.go [hunk 1]
```diff
@@ -229,7 +229,10 @@ func (nl *NodeLiveness) StartHeartbeat(
 	log.VEventf(ctx, 1, "starting liveness heartbeat")
 	retryOpts := base.DefaultRetryOptions()
 	retryOpts.Closer = stopper.ShouldQuiesce()
-	nl.heartbeatCallback = alive
+
+	nl.mu.Lock()
+	nl.mu.heartbeatCallback = alive
```
Comment (petermattis) [inline pkg/storage/node_liveness.go]: Hrmm, my comment here disappeared. I wonder if `alive` should be passed to `NewNodeLiveness` instead of `StartHeartbeat`. That would avoid any locking issues.
