### PR TITLE
tree: fix serialization of null values in tuples with enums

### LINKED ISSUE #58889: sql: problem with type checking enums on the remote nodes
Extracted from [here](https://github.com/cockroachdb/cockroach/issues/58285#issuecomment-755132738).

Reproduction steps (on a 3 node demo cluster):
```
CREATE TYPE greeting AS ENUM ('hello', 'howdy', 'hi', 'good day', 'morning');
CREATE TABLE t AS SELECT enum_range('hello'::greeting)[g] as _enum FROM generate_series(1, 5) as g;
ALTER TABLE t SPLIT AT SELECT i FROM generate_series(1, 5) as g(i);
ALTER TABLE t SCATTER;
SELECT _enum FROM t WHERE _enum::greeting IN (NULL, 'hi':::greeting);
```
Results in
```
ERROR: internal error: unable to vectorize execution plan: "$0" IN (NULL::public.greeting, b'\x80':::@100052): unsupported comparison operator: "$0" IN (NULL::public.greeting, b'\x80':::@100052): cannot resolve types in DistSQL by name
SQLSTATE: XX000
DETAIL: stack trace:
github.com/cockroachdb/cockroach/pkg/sql/execinfrapb/expr.go:81: processExpression()
github.com/cockroachdb/cockroach/pkg/sql/execinfrapb/expr.go:154: DeserializeExpr()
github.com/cockroachdb/cockroach/pkg/sql/execinfrapb/expr.go:183: Init()
github.com/cockroachdb/cockroach/pkg/sql/rowexec/filterer.go:61: newFiltererProcessor()
github.com/cockroachdb/cockroach/pkg/sql/rowexec/processors.go:144: NewProcessor()
github.com/cockroachdb/cockroach/pkg/sql/colexec/colbuilder/execplan.go:573: func1()
github.com/cockroachdb/cockroach/pkg/sql/colexec/colbuilder/execplan.go:95: wrapRowSources()
github.com/cockroachdb/cockroach/pkg/sql/colexec/colbuilder/execplan.go:561: createAndWrapRowSource()
github.com/cockroachdb/cockroach/pkg/sql/colexec/colbuilder/execplan.go:1302: planAndMaybeWrapFilter()
github.com/cockroachdb/cockroach/pkg/sql/colexec/colbuilder/execplan.go:762: NewColOperator()
...
```
It looks like we somehow fail to deserialize `'hi':::greeting` part of the filter on the remote node.

The problem is present when using the row-by-row engine too.

cc @arulajmani in case you're curious to take a look

### PR DESCRIPTION
**Pull request by yuzefovich**
Enum values need to be serialized in a special way - with the type
annotation containing an Oid type reference. Previously, NULL values
when used in a tuple with enum values had a different type annotation
which caused the remote nodes to hit an assertion about not being able
to resolve the type by name.

Fixes: #58889.

Release note (bug fix): Previously, CockroachDB could encounter an
internal error when executing queries with tuples containing null values
and enums in a distributed setting, and this is now fixed.

### CODE REVIEW

**Comment by yuzefovich** [comment]
I'm not very familiar with this code, and the fix was inspired by https://github.com/cockroachdb/cockroach/blob/d00f2c75c69e771e66e96192903071181e695667/pkg/sql/sem/tree/format.go#L389-L398 which was most recently touched by Rafi, hence I added you as the reviewer. I'm also happy to hand the issue to SQL Experience for a proper fix (if this isn't) :)

File: pkg/sql/sem/tree/datum.go [hunk 1]
```diff
@@ -3507,8 +3507,14 @@ func (d *DTuple) Format(ctx *FmtCtx) {
 			// an error message in this case, if necessary, so just skip the
 			// annotation and continue.
 			if typ.TupleContents()[i].Family() != types.UnknownFamily {
-				ctx.WriteString("::")
-				ctx.WriteString(typ.TupleContents()[i].SQLString())
+				nullType := typ.TupleContents()[i]
```
Comment (rafiss) [inline pkg/sql/sem/tree/datum.go:3510]: maybe extract `type.TupleContents()` as a variable, since it's used in 3 places now

File: pkg/sql/sem/tree/format_test.go [hunk 2]
```diff
@@ -343,7 +343,7 @@ func TestFormatExpr2(t *testing.T) {
 			types.MakeTuple([]*types.T{types.Int, types.String}),
 			tree.DNull, tree.NewDString("foo")),
 			tree.FmtParsable,
-			`(NULL::INT8, 'foo':::STRING)`,
+			`(NULL:::INT8, 'foo':::STRING)`,
```
Comment (rafiss) [inline pkg/sql/sem/tree/format_test.go:346]: can you add another test case that tests enum values in a tuple

**Review by rafiss — CHANGES_REQUESTED** [review]
the fix looks good to me. thank you!

left other comments

**Review by yuzefovich — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/58894)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rafiss)

___
*[pkg/sql/sem/tree/datum.go, line 3510 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/58894#-MQsvCHrDNsOFyxsjM5n-r1-3510:-MQxxm7V7aNxay3R1Q0X:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/f885a9452d4219ccb5e4f1bb19512c4002d0e147/pkg/sql/sem/tree/datum.go#L3510)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

maybe extract `type.TupleContents()` as a variable, since it's used in 3 places now
</blockquote></details>

Done.
___
*[pkg/sql/sem/tree/format_test.go, line 346 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/58894#-MQt3n8vFAC6v9PKziEn-r1-346:-MQy1z975xrfvgsbk5G6:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/f885a9452d4219ccb5e4f1bb19512c4002d0e147/pkg/sql/sem/tree/format_test.go#L346)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

can you add another test case that tests enum values in a tuple
</blockquote></details>

Done.

**Review by rafiss — APPROVED** [review]
lgtm!

**Comment by yuzefovich** [comment]
TFTR!

bors r+
