### PR TITLE
ui: fix smaller typos on SQL Activity

### LINKED ISSUE #85224: minor typos in SQL Activity pages
There are some minor typos on the SQL Activity pages:
- [ ] There is a whitespace missing in the Statement Fingerprints description dropdown between the end of the second sentence and the “Learn more” link.
- [ ] In the Statement Fingerprints and Transaction Fingerprints overview pages, there is a whitespace missing in the tooltip text for Max Memory between the first and second sentences.
- [ ] On the Statement Fingerprint details page, the table of plans under the Explain Plans tab have tooltips that refer to the explain plan as just “Plan”. We should change this to “explain plan”, with a link to https://www.cockroachlabs.com/docs/stable/explain.html.
- [ ] When the pages under SQL Activity take longer to load, we show a message using "time period". Change the text to say "time interval"
Screen Shot 2022-07-26 at 10 17 30 AM

Jira issue: CRDB-18117

### PR DESCRIPTION
**Pull request by maryliag**
Add missing spaces, words and doc links on SQL
Activity page.

Fixes #85224

Release justification: low risk changes
Release note (ui change): Add link to explain plan table linking
to explain doc page.

### CODE REVIEW

**Review by ericharmeling — COMMENTED** [review]
Just a couple nits. Otherwise LGTM!

> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/86581#-:-NA5a0Zo18-rsjHvjzad:b-zat0pp)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @maryliag)

___
*[`pkg/ui/workspaces/cluster-ui/src/statementDetails/planDetails/plansTable.tsx` line 93 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/86581#-NA5__U84GqLwrfqmE36:-NA5__U84GqLwrfqmE37:undefined) ([raw file](https://github.com/cockroachdb/cockroach/blob/7cb3b9ea3e774dc70f7af34610b151fb37950058/pkg/ui/workspaces/cluster-ui/src/statementDetails/planDetails/plansTable.tsx#L93)):*
> ```XML
>         style="tableTitle"
>         placement="bottom"
>         content={"The execution count for this Explain Explain Plan."}
> ```





_Suggestion:_
```XML
Explain Plan.
```
___
*[`pkg/ui/workspaces/cluster-ui/src/statementDetails/planDetails/plansTable.tsx` line 115 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/86581#-NA5_jOfD27bA_7Xd7yw:-NA5_jOfD27bA_7Xd7yx:b45h) ([raw file](https://github.com/cockroachdb/cockroach/blob/7cb3b9ea3e774dc70f7af34610b151fb37950058/pkg/ui/workspaces/cluster-ui/src/statementDetails/planDetails/plansTable.tsx#L115)):*
> ```XML
>         style="tableTitle"
>         placement="bottom"
>         content={"If the Explain Plan executed a Full Scan."}
> ```





_Suggestion:_
```XML
If the Explain Plan executed a full scan.
```

File: pkg/ui/workspaces/cluster-ui/src/statementDetails/planDetails/plansTable.tsx [hunk 1]
```diff
@@ -81,7 +90,7 @@ export const planDetailsTableTitles: PlanDetailsTableTitleType = {
       <Tooltip
         style="tableTitle"
         placement="bottom"
-        content={"The execution count for this Plan."}
+        content={"The execution count for this Explain Explain Plan."}
```
Comment (THardy98) [inline pkg/ui/workspaces/cluster-ui/src/statementDetails/planDetails/plansTable.tsx:93]: Double `Explain` here.

File: pkg/ui/workspaces/cluster-ui/src/statementsPage/statementsPageRoot.tsx [hunk 2]
```diff
@@ -41,7 +41,7 @@ export const StatementsPageRoot = ({
           {`A statement fingerprint represents one or more completed SQL
           statements by replacing literal values (e.g., numbers and strings)
           with underscores (_).\nThis can help you quickly identify
-          frequently executed SQL statements and their latencies.`}
+          frequently executed SQL statements and their latencies. `}
```
Comment (THardy98) [inline pkg/ui/workspaces/cluster-ui/src/statementsPage/statementsPageRoot.tsx:44]: Is the trailing space intended?

**Review by THardy98 — COMMENTED** [review]
Just a couple `nits`

File: pkg/ui/workspaces/cluster-ui/src/statementsPage/statementsPageRoot.tsx (hunk 2 above)
Comment (maryliag) [reply pkg/ui/workspaces/cluster-ui/src/statementsPage/statementsPageRoot.tsx:44]: Yes, that was one of the issues, because this is followed by a learn more link, and was wrong without this space between them

File: pkg/ui/workspaces/cluster-ui/src/statementDetails/planDetails/plansTable.tsx (hunk 1 above)
Comment (maryliag) [reply pkg/ui/workspaces/cluster-ui/src/statementDetails/planDetails/plansTable.tsx:93]: ops... I'm really trying to explain it :D

File: pkg/ui/workspaces/cluster-ui/src/statementsPage/statementsPageRoot.tsx (hunk 2 above)
Comment (THardy98) [reply pkg/ui/workspaces/cluster-ui/src/statementsPage/statementsPageRoot.tsx:44]: Ah I see

**Review by maryliag — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/86581)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ericharmeling and @THardy98)

___
*[`pkg/ui/workspaces/cluster-ui/src/statementDetails/planDetails/plansTable.tsx` line 93 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/86581#-NA5__U84GqLwrfqmE36:-NA5o74S2O9L4pCmgeE3:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/7cb3b9ea3e774dc70f7af34610b151fb37950058/pkg/ui/workspaces/cluster-ui/src/statementDetails/planDetails/plansTable.tsx#L93)):*
> ```XML
>         style="tableTitle"
>         placement="bottom"
>         content={"The execution count for this Explain Explain Plan."}
> ```

Done.
___
*[`pkg/ui/workspaces/cluster-ui/src/statementDetails/planDetails/plansTable.tsx` line 115 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/86581#-NA5_jOfD27bA_7Xd7yw:-NA5oDpP1tORZKNQbtX6:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/7cb3b9ea3e774dc70f7af34610b151fb37950058/pkg/ui/workspaces/cluster-ui/src/statementDetails/planDetails/plansTable.tsx#L115)):*
> ```XML
>         style="tableTitle"
>         placement="bottom"
>         content={"If the Explain Plan executed a Full Scan."}
> ```

Done.



_Code quote:_
```XML
If the Explain Plan executed a Ful
```

**Review by THardy98 — APPROVED** [review]
LGTM :)

**Review by ericharmeling — APPROVED** [review]
