### PR TITLE
sql: initialize sql instance during instance provider start

### LINKED ISSUE #81567: ccl/serverccl: TestSQLServer failed
ccl/serverccl.TestSQLServer [failed](https://teamcity.cockroachdb.com/buildConfiguration/BUILDTYPE_ID-not-found-in-env/5213796?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/BUILDTYPE_ID-not-found-in-env/5213796?buildTab=artifacts#/) on master @ [92947c29c55ff909f50a5e625811d34a1bbe71f7](https://github.com/cockroachdb/cockroach/commits/92947c29c55ff909f50a5e625811d34a1bbe71f7):

```
=== RUN   TestSQLServer
    test_log_scope.go:79: test logs captured to: /artifacts/tmp/_tmp/bdf0d69e85b4e9625d25e2f39af80117/logTestSQLServer2021352501
    test_log_scope.go:80: use -show-logs to present logs inline
    server_sql_test.go:67: error executing 'CREATE INDEX ON foo.kv (v)': pq: VERIFY INDEX: no healthy sql instances available for planning
    panic.go:642: -- test log scope end --
--- FAIL: TestSQLServer (3.29s)
```
<details><summary>Help</summary>
<p>

See also: [How To Investigate a Go Test Failure \(internal\)](https://cockroachlabs.atlassian.net/l/c/HgfXfJgM)
Parameters in this failure:

- TAGS=bazel,gss
</p>
</details>
/cc @cockroachdb/server
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*TestSQLServer.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)
</sub>

Jira issue: CRDB-15075

### LINKED ISSUE #81807: ccl/serverccl: TestTenantRowIDs failed
ccl/serverccl.TestTenantRowIDs [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_StressBazel/5264917?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_StressBazel/5264917?buildTab=artifacts#/) on master @ [321e96667fda4f896f96d7b61660d6ad28c5bd29](https://github.com/cockroachdb/cockroach/commits/321e96667fda4f896f96d7b61660d6ad28c5bd29):

```
=== RUN   TestTenantRowIDs
    test_log_scope.go:79: test logs captured to: /artifacts/tmp/_tmp/bdf0d69e85b4e9625d25e2f39af80117/logTestTenantRowIDs1181443882
    test_log_scope.go:80: use -show-logs to present logs inline
    server_sql_test.go:219: error executing 'SELECT key FROM foo': pq: no healthy sql instances available for planning
    panic.go:642: -- test log scope end --
--- FAIL: TestTenantRowIDs (2.35s)
```
<details><summary>Help</summary>
<p>

See also: [How To Investigate a Go Test Failure \(internal\)](https://cockroachlabs.atlassian.net/l/c/HgfXfJgM)
Parameters in this failure:

- TAGS=bazel,gss
</p>
</details>
/cc @cockroachdb/server
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*TestTenantRowIDs.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)
</sub>

Jira issue: CRDB-16075

### LINKED ISSUE #82706: ccl/streamingccl/streamingest: TestTenantStreaming failed
ccl/streamingccl/streamingest.TestTenantStreaming [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_StressBazel/5432052?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_StressBazel/5432052?buildTab=artifacts#/) on master @ [e1cdb469d4828e2e1df0f801ac50d4e4f9943e1e](https://github.com/cockroachdb/cockroach/commits/e1cdb469d4828e2e1df0f801ac50d4e4f9943e1e):

```
=== RUN   TestTenantStreaming
    test_log_scope.go:79: test logs captured to: /artifacts/tmp/_tmp/045fecfe9e18c9da6f776a53d446f2c5/logTestTenantStreaming711556021
    test_log_scope.go:80: use -show-logs to present logs inline
    stream_ingestion_job_test.go:191: error executing 'SELECT * FROM d.t1': pq: no healthy sql instances available for planning
    panic.go:661: -- test log scope end --
--- FAIL: TestTenantStreaming (62.10s)
```
<p>Parameters: <code>TAGS=bazel,gss</code>
</p>
<details><summary>Help</summary>
<p>

See also: [How To Investigate a Go Test Failure \(internal\)](https://cockroachlabs.atlassian.net/l/c/HgfXfJgM)
</p>
</details>
/cc @cockroachdb/bulk-io
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*TestTenantStreaming.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)
</sub>

Jira issue: CRDB-16620

### PR DESCRIPTION
**Pull request by rharding6373**
Before this change, there was a race condition where the instance
provider and the instance reader would start before the instance
provider created a SQL instance, potentially causing the reader to not
cache the instance before initialization was complete. This is
a problem in multi-tenant environments, where we may not be able to plan
queries if the reader does not know of any SQL instances.

This change moves sql instance initialization into the instance
provider's `Start()` function before starting the reader, so that the
instance is guaranteed to be visible to the reader on its first
rangefeed scan of the `system.sql_instances` table.

Fixes: #82706
Fixes: #81807
Fixes: #81567

Release note: None

### CODE REVIEW

File: pkg/sql/sqlinstance/instanceprovider/test_helpers.go [hunk 1]
```diff
@@ -43,6 +44,14 @@ func NewTestInstanceProvider(
 	return p
 }
 
+// InitAndWaitForTest explicitly calls initAndWait for testing purposes.
+func (p *provider) InitAndWaitForTest(ctx context.Context) {
+	if err := p.initAndWait(ctx); err != nil {
+		//nolint:returnerrcheck
+		return
+	}
```
Comment (ajwerner) [inline pkg/sql/sqlinstance/instanceprovider/test_helpers.go:52]: You can also type this to defeat the linter:

```go
// InitAndWaitForTest explicitly calls initAndWait for testing purposes.
func (p *provider) InitAndWaitForTest(ctx context.Context) {
    _ = p.initAndWait(ctx)
}
```

**Review by rimadeodhar — COMMENTED** [review]
Thanks for the fix. Code LGTM. Andrew's comment on potentially making a skeleton instance provider that returns error which can be used for the storage server seems like a good idea. 

> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/83358#-:-N5gH1AL8b4eI1s8jJFK:b-srn12n)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rharding6373 and @rhu713)

**Review by rharding6373 — COMMENTED** [review]
TFTRs! I'm currently working on fixing a timeout that occurs in `TestTenantUnauthenticatedAccess`, but have incorporated the other suggestions so far.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/83358#-:-N5l6hFY5dnLEe2kg1WA:b-tnw0m2)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @rhu713, and @rimadeodhar)

___
*[`pkg/server/server_sql.go` line 412 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/83358#-N5MiWyj-7h87Lnxul7d-r1-412:-N5bX8M7-v_CjFVKozRf:b-trnwcf) ([raw file](https://github.com/cockroachdb/cockroach/blob/35d13bb35ce300d85f85289f72e07c6bd8d8e694/pkg/server/server_sql.go#L412)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

My first instinct was to ask whether we can we just make this field nil in a kv server? From what I can tell, all of the code-paths which use the instanceProvider are defensive.

On some level, I don't love that because in the future somebody might not be defensive. How about as an alternative, we make an implementation of sqlinstance.Provider which just returns errors from all of its methods and then for the kv server we instantiate that fake implementation, otherwise, we instantiate the usual one.

That way we don't need to introduce this skeleton concept and we'll uncover bugs in the future more readily if one of these things which might have been marked as a skeleton makes its way somewhere it shouldn't be and instead of returning nothing, it returns a clear error.
</blockquote></details>

That's a good suggestion. We still need a Reader to implement the AddressResolver interface for SQL liveness heartbeat loops, so instead of throwing errors for every function it's still a bare bones implementation. This can probably be disentangled in the future, but it's out of scope for this PR.
___
*[`pkg/sql/sqlinstance/instanceprovider/test_helpers.go` line 52 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/83358#-N5MiWyj-7h87Lnxul7g-r1-52:-N5bop6bEaXWyLT_wF8O:b-p1bteq) ([raw file](https://github.com/cockroachdb/cockroach/blob/35d13bb35ce300d85f85289f72e07c6bd8d8e694/pkg/sql/sqlinstance/instanceprovider/test_helpers.go#L52)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

You can also type this to defeat the linter:

```go
// InitAndWaitForTest explicitly calls initAndWait for testing purposes.
func (p *provider) InitAndWaitForTest(ctx context.Context) {
    _ = p.initAndWait(ctx)
}
```
</blockquote></details>

Thanks for the tip!

**Review by ajwerner — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/83358)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @rharding6373, @rhu713, and @rimadeodhar)

___
*[`pkg/server/server_sql.go` line 412 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/83358#-N5MiWyj-7h87Lnxul7d-r1-412:-N5l9v0ZDKSNRlQzL3G2:b-8lvosz) ([raw file](https://github.com/cockroachdb/cockroach/blob/35d13bb35ce300d85f85289f72e07c6bd8d8e694/pkg/server/server_sql.go#L412)):*
> We still need a Reader to implement the AddressResolver interface for SQL liveness heartbeat loops

Shouldn't the address resolver for the kv-node be gossip-backed?

File: pkg/sql/sqlinstance/instanceprovider/instanceprovider.go [hunk 2]
```diff
@@ -35,7 +35,42 @@ type writer interface {
...
+
+// GetInstance implements the AddressResolver interface.
+func (p *placeholderProvider) GetInstance(context.Context, base.SQLInstanceID) (sqlinstance.InstanceInfo, error) {
+	return sqlinstance.InstanceInfo{}, sqlinstance.NotASQLInstanceError
+}
+
+// GetAllInstances implements the AddressResolver interface.
+func (p *placeholderProvider) GetAllInstances(context.Context) ([]sqlinstance.InstanceInfo, error) {
+	return nil, sqlinstance.NotASQLInstanceError
+}
```
Comment (ajwerner) [inline pkg/sql/sqlinstance/instanceprovider/instanceprovider.go:70]: I can see just defining this in the `sqlinstance` package. It doesn't know anything about implementation details that this package knows about.

File: pkg/server/server_sql.go [hunk 3]
```diff
@@ -1115,6 +1123,24 @@ func newSQLServer(ctx context.Context, cfg sqlServerArgs) (*SQLServer, error) {
...
+	err := db.Txn(ctx, func(ctx context.Context, txn *kv.Txn) error {
+		start := codec.TenantPrefix()
+		end := start.PrefixEnd()
+		if _, err := txn.Scan(ctx, start, end, 1); err != nil {
+			return err
+		}
+		return nil
+	})
+	return err
+}
```
Comment (ajwerner) [inline pkg/server/server_sql.go:1142]: Oof this hurts in the context of https://github.com/cockroachdb/cockroach/issues/79043 

Is the deal that the `Init` just hangs because the retry gets stuck restarting internally? I think we can do some more plumbing to get that error propagated without needing to wait for the extra round-trip here. 

FWIW, I'd expect authorization errors to propagate to the rangefeed via this code here: https://github.com/cockroachdb/cockroach/blob/f7bb118d8298eabe16a8ce99146225f7133fe3a5/pkg/sql/sqlinstance/instancestorage/instancereader.go#L143-L145

**Review by rharding6373 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/83358)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @rharding6373, @rhu713, and @rimadeodhar)

___
*[`pkg/server/server_sql.go` line 1142 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/83358#-N5MiWyj-7h87Lnxul7d-r3-1142:-N5qM4I07y-0MBrMTJUD:b-50hvcs) ([raw file](https://github.com/cockroachdb/cockroach/blob/2b887f05638d99835cc3284e7f085335f1731afd/pkg/server/server_sql.go#L1142)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

Oof this hurts in the context of https://github.com/cockroachdb/cockroach/issues/79043 

Is the deal that the `Init` just hangs because the retry gets stuck restarting internally? I think we can do some more plumbing to get that error propagated without needing to wait for the extra round-trip here. 

FWIW, I'd expect authorization errors to propagate to the rangefeed via this code here: https://github.com/cockroachdb/cockroach/blob/f7bb118d8298eabe16a8ce99146225f7133fe3a5/pkg/sql/sqlinstance/instancestorage/instancereader.go#L143-L145
</blockquote></details>

I don't think having a read here just to check if the tenant has permissions is ideal, no...

The hanging actually occurs when creating a session for initializing the instance (instanceprovider.go:l196 in this PR), which is to say it's waiting for the sql liveness provider to create a session after it's started. The problem is that we also get an unauthenticated error when trying to create the session, and then we retry an infinite number of times. Before this PR we started the instance reader first, so it would propagate the error before being stuck in this loop was a problem. 

Maybe the solution here is to back out of the heartbeat loop if there are authentication errors?

**Review by rharding6373 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/83358)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @rhu713, and @rimadeodhar)

___
*[`pkg/server/server_sql.go` line 412 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/83358#-N5MiWyj-7h87Lnxul7d-r1-412:-N5qb2rB7eMEw7J0jcq5:b2ky2yv) ([raw file](https://github.com/cockroachdb/cockroach/blob/35d13bb35ce300d85f85289f72e07c6bd8d8e694/pkg/server/server_sql.go#L412)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

> We still need a Reader to implement the AddressResolver interface for SQL liveness heartbeat loops

Shouldn't the address resolver for the kv-node be gossip-backed?
</blockquote></details>

I take that back. Can't reproduce the error I had any more.
___
*[`pkg/server/server_sql.go` line 1142 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/83358#-N5MiWyj-7h87Lnxul7d-r3-1142:-N5qcBePB1UTX9xDluBe:b-u6yqca) ([raw file](https://github.com/cockroachdb/cockroach/blob/2b887f05638d99835cc3284e7f085335f1731afd/pkg/server/server_sql.go#L1142)):*
<details><summary><i>Previously, rharding6373 (Rachael Harding) wrote…</i></summary><blockquote>

I don't think having a read here just to check if the tenant has permissions is ideal, no...

The hanging actually occurs when creating a session for initializing the instance (instanceprovider.go:l196 in this PR), which is to say it's waiting for the sql liveness provider to create a session after it's started. The problem is that we also get an unauthenticated error when trying to create the session, and then we retry an infinite number of times. Before this PR we started the instance reader first, so it would propagate the error before being stuck in this loop was a problem. 

Maybe the solution here is to back out of the heartbeat loop if there are authentication errors?
</blockquote></details>

I made some changes in slinstance.go instead so we exit the loop on an unrecoverable error like authentication issues. I'm not sure if there's a corner case that could cause an issue with this implementation. Let me know what you think.
___
*[`pkg/sql/sqlinstance/instanceprovider/instanceprovider.go` line 70 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/83358#-N5MiWyj-7h87Lnxul7e-r3-70:-N5qb0Ck4HfPqi6fQzc8:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/2b887f05638d99835cc3284e7f085335f1731afd/pkg/sql/sqlinstance/instanceprovider/instanceprovider.go#L70)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

I can see just defining this in the `sqlinstance` package. It doesn't know anything about implementation details that this package knows about. 
</blockquote></details>

Done.

**Comment by rharding6373** [comment]
The MT team is going to find another owner to shepherd this PR through since I'm going on leave and may not have a chance to look at it again -- I know this bug is still causing CI pain.

There's still one more unresolved test failure caused by this change afaict, `TestTenantStreaming`. Although it appears that both source and dest tenants initialize without issues in the test, streaming between them never progresses and there is unexpected memory allocated when the test ends.

**Comment by stevendanna** [comment]
@rharding6373 On the TestTenantStreaming, does https://github.com/cockroachdb/cockroach/issues/83697 cover the "unexpected memory allocated when the test ends" issue, or are you seeing a different issue?

Might be worth it to keep TestTenantStreaming skipped if this change otherwise fixes the other issues we are seeing, then I can dig into what is happening on the TenantStreaming side.

**Review by yuzefovich — COMMENTED** [review]
@ajwerner does this PR have your blessing?

> Reviewed 1 of 6 files at r1, 1 of 4 files at r2, 1 of 4 files at r4, 4 of 4 files at r5, 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/83358#-:-N6FK6pC9aVkgmTmx4sU:b-2dwziz)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @rharding6373, and @rhu713)

___
*[`pkg/ccl/streamingccl/streamingest/stream_ingestion_job_test.go` line 82 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/83358#-N6FK0Om1O4ji17OhOb4:-N6FK0On97ew1werxanN:b-s5qkr0) ([raw file](https://github.com/cockroachdb/cockroach/blob/41855f7dd960ff67d7d921e85d0786fd57335070/pkg/ccl/streamingccl/streamingest/stream_ingestion_job_test.go#L82)):*
> ```Go
> 	defer leaktest.AfterTest(t)()
> 	defer log.Scope(t).Close(t)
> 	skip.WithIssue(t, 83697)
> ```

I made the change here for `TestTenantStreaming` to point to the new issue Steven linked above.

**Review by ajwerner — APPROVED** [review]
I suppose. If I were being nit-picky, it'd be nice to have a test which exercises the change, but I'd rather we merge this to stop the flakes. 

> Reviewed 1 of 6 files at r1, 1 of 4 files at r2, 2 of 4 files at r5, 2 of 2 files at r6.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/83358#-:-N6FLehT7O-fdTurn_Aj:b-3lyd3z)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rharding6373 and @rhu713)

___
*[`pkg/sql/sqlliveness/slinstance/slinstance.go` line 195 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/83358#-N6FKqfi-4A4WmFt6CtC:-N6FKqfi-4A4WmFt6CtD:bxiywgn) ([raw file](https://github.com/cockroachdb/cockroach/blob/41855f7dd960ff67d7d921e85d0786fd57335070/pkg/sql/sqlliveness/slinstance/slinstance.go#L195)):*
> ```Go
> 			// Unauthenticated errors are unrecoverable, we should break instead of
> 			// retrying.
> 			if strings.Contains(err.Error(), "rpc error: code = Unauthenticated") {
> ```

https://github.com/cockroachdb/cockroach/blob/3fc6cc56772a9b26aea7a28f50f1089a06051f4d/pkg/util/grpcutil/grpc_util.go#L120 ?
___
*[`pkg/sql/sqlliveness/slinstance/slinstance.go` line 258 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/83358#-N6FKuHkC0AgeiXn8O1z:-N6FKuHkC0AgeiXn8O2-:b-1emmqe) ([raw file](https://github.com/cockroachdb/cockroach/blob/41855f7dd960ff67d7d921e85d0786fd57335070/pkg/sql/sqlliveness/slinstance/slinstance.go#L258)):*
> ```Go
> 				newSession, err := l.createSession(ctx)
> 				if err != nil {
> 					l.mu.Lock()
> ```

these days we do these in a closure like:
```go
func() {
    l.mu.Lock()
    defer l.mu.Unlock()
    l.startErr = err
    // There was an unrecoverable error when trying to create the session.
    // Notify all calls to Session that the session failed.
    close(l.mu.blockCh)
}
```



_Code quote:_
```Go
					l.mu.Lock()
					l.startErr = err
					// There was an unrecoverable error when trying to create the session.
					// Notify all calls to Session that the session failed.
					close(l.mu.blockCh)
					l.mu.Unlock()
```
___
*[`pkg/sql/sqlliveness/slinstance/slinstance.go` line 359 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/83358#-N6FLApG5bZaoMgXMznl:-N6FLApG5bZaoMgXMznm:b-7p9ssd) ([raw file](https://github.com/cockroachdb/cockroach/blob/41855f7dd960ff67d7d921e85d0786fd57335070/pkg/sql/sqlliveness/slinstance/slinstance.go#L359)):*
> ```Go
> 			l.mu.Lock()
> 			err := l.startErr
> 			l.mu.Unlock()
> ```

same comment about the closure



_Code quote:_
```Go
			err := l.startErr
			l.mu.Unlock()
```

**Review by yuzefovich — COMMENTED** [review]
Thanks! I agree with you on merging this to stop flakes, will merge once the CI is green.

> Reviewed 1 of 1 files at r8, 1 of 1 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/83358#-:-N6FMcVpB5Wx0zRupBvq:b-vs3uil)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @rharding6373, and @rhu713)

___
*[`pkg/sql/sqlliveness/slinstance/slinstance.go` line 195 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/83358#-N6FKqfi-4A4WmFt6CtC:-N6FNFBV4lw6MXCUOr6A:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/41855f7dd960ff67d7d921e85d0786fd57335070/pkg/sql/sqlliveness/slinstance/slinstance.go#L195)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

https://github.com/cockroachdb/cockroach/blob/3fc6cc56772a9b26aea7a28f50f1089a06051f4d/pkg/util/grpcutil/grpc_util.go#L120 ?
</blockquote></details>

Done.
___
*[`pkg/sql/sqlliveness/slinstance/slinstance.go` line 258 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/83358#-N6FKuHkC0AgeiXn8O1z:-N6FNFyM5ilGATuIyq-K:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/41855f7dd960ff67d7d921e85d0786fd57335070/pkg/sql/sqlliveness/slinstance/slinstance.go#L258)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

these days we do these in a closure like:
```go
func() {
    l.mu.Lock()
    defer l.mu.Unlock()
    l.startErr = err
    // There was an unrecoverable error when trying to create the session.
    // Notify all calls to Session that the session failed.
    close(l.mu.blockCh)
}
```
</blockquote></details>

Done.
___
*[`pkg/sql/sqlliveness/slinstance/slinstance.go` line 359 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/83358#-N6FLApG5bZaoMgXMznl:-N6FNHBT5A8iO21u0xuT:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/41855f7dd960ff67d7d921e85d0786fd57335070/pkg/sql/sqlliveness/slinstance/slinstance.go#L359)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

same comment about the closure
</blockquote></details>

Done.

**Comment by yuzefovich** [comment]
Quite a few tests in `streamingest` package fail under the race on the CI run, but they also do on master, before this patch, so I filed #83867 and added a skip for those. Let's see what CI says now.

**Comment by yuzefovich** [comment]
Looks like the race tests passed, so merging.

bors r=ajwerner

**Review by yuzefovich — COMMENTED** [review]
> Reviewed 3 of 3 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/83358)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @rharding6373, and @rhu713)

___
*[`pkg/sql/sqlliveness/slinstance/slinstance.go` line 195 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/83358#-N6FKqfi-4A4WmFt6CtC:-N6G0LCECDPsLUx5wrR_:bptlk4k) ([raw file](https://github.com/cockroachdb/cockroach/blob/41855f7dd960ff67d7d921e85d0786fd57335070/pkg/sql/sqlliveness/slinstance/slinstance.go#L195)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

@ajwerner I just stumbled on this piece of code: https://github.com/cockroachdb/cockroach/blob/9c5472e9dcbabc2afdec43dd6c23c0010e5ab231/pkg/sql/sqlinstance/instancestorage/instancereader.go#L142-L145
do you think it's worth doing the same here? Looks like `err` here comes from `slstorage.Insert` which might issue a gRPC call.
