### PR TITLE
roachtest/multitenant-upgrade: hard-code predecessor version temporarily

### LINKED ISSUE #107851: roachtest: multitenant-upgrade failed
roachtest.multitenant-upgrade [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/11108583?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/11108583?buildTab=artifacts#/multitenant-upgrade) on master @ [f295bd861a3a427652b19c2254d2401ebb4a3c8e](https://github.com/cockroachdb/cockroach/commits/f295bd861a3a427652b19c2254d2401ebb4a3c8e):

```
(test_runner.go:1075).runTest: test timed out (1h0m0s)
test artifacts and logs in: /artifacts/multitenant-upgrade/run_1
```
<p>Parameters: <code>ROACHTEST_arch=amd64</code>
, <code>ROACHTEST_cloud=gce</code>
, <code>ROACHTEST_cpu=4</code>
, <code>ROACHTEST_encrypted=false</code>
, <code>ROACHTEST_fs=ext4</code>
, <code>ROACHTEST_localSSD=true</code>
, <code>ROACHTEST_ssd=0</code>
</p>
<details><summary>Help</summary>
<p>

See: [roachtest README](https://github.com/cockroachdb/cockroach/blob/master/pkg/cmd/roachtest/README.md)

See: [How To Investigate \(internal\)](https://cockroachlabs.atlassian.net/l/c/SSSBr8c7)

See: [Grafana](https://go.crdb.dev/p/roachfana//1690653988967/1690657636148)

</p>
</details>
/cc @cockroachdb/multi-tenant
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*multitenant-upgrade.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)
</sub>

Jira issue: CRDB-30217
Epic: CRDB-18499

### PR DESCRIPTION
**Pull request by healthy-pod**
Hard-code the pre-decessor release to 23.1.4 until a new patch release is out (23.1.9) because the test is in-compatible with 23.1.{5,6,7,8} due to an erroneous PR merged on the 23.1 branch.

Release note: None
Epic: CRDB-18499
Fixes #107851.

### CODE REVIEW

File: pkg/cmd/roachtest/tests/multitenant_upgrade.go [hunk 1]
```diff
@@ -82,8 +81,11 @@ func runMultiTenantUpgrade(
 	currentBinaryMinSupportedVersion, ok := versionToMinSupportedVersion[curBinaryMajorAndMinorVersion]
 	require.True(t, ok, "current binary '%s' not found in 'versionToMinSupportedVersion' map", curBinaryMajorAndMinorVersion)
 
-	predecessor, err := release.LatestPredecessor(v)
-	require.NoError(t, err)
+	// predecessor, err := release.LatestPredecessor(v)
+	// require.NoError(t, err)
+	// Hard-code the pre-decessor release to 23.1.4 until a new patch release is out (23.1.9) because
+	// the test is in-compatible with 23.1.{5,6,7,8} due to an erroneous PR merged on the 23.1 branch.
+	predecessor := "23.1.4"
```
Comment (knz) [inline pkg/cmd/roachtest/tests/multitenant_upgrade.go:88]: Thanks. Could you make this override temporary by actually encoding a condition on the output of `release.LatestPredecessor`? Something like:

```
if major == 23 and minor == 1 and patch < 7 {
       predecessor = "23.1.4"
}
```

so that the condition automatically ceases to apply once .7 is released.

Comment (healthy-pod) [reply pkg/cmd/roachtest/tests/multitenant_upgrade.go]: Done

**Review by knz — APPROVED** [review]
thank you

**Comment by knz** [comment]
You could also include a mention to the specific patch that was problematic and the PR that was merged to fix it.

**Comment by healthy-pod** [comment]
TFTR!
bors r=knz
