### PR TITLE
sql: allow get_bit() and set_bit() builtin functions to support byte array

### LINKED ISSUE #45851: sql: Missing get_bit and set_bit functions
Repro:
```
root@:26257/defaultdb> SELECT get_bit(B'0101011000100', 10);
ERROR: unknown function: get_bit()
root@:26257/defaultdb> SELECT set_bit(B'0101011000100100', 15, 1);
ERROR: unknown function: set_bit()
```

### PR DESCRIPTION
**Pull request by abhishek20123g**
Fixes https://github.com/cockroachdb/cockroach/issues/45851

This commit modified get_bit and set_bit to allow them to support
byte array along with their respective testcases.

Release justification: low-risk change to existing functionality.

Release note (sql change): This PR is modified get_bits()
and set_bit() functions to allow them support byte array.

### CODE REVIEW

**Comment by abhishek20123g** [comment]
Small overview:
1. Thought of using `bytesOverload1` instead of just writing a custom `tree.Overload` but there was a conflict with arguments name as `bytesOverload1` name input arguments as `val`.
2. Tried to avoid bitwise operations inside function definition  but can't able to find support to access and modify a bit in `bytes library` and there was no predefined function which converts byte Array to bit Array so we could reuse `SetBitAtIndex and GetBitAtIndex in bitarray.BitArray`

File: pkg/sql/sem/builtins/builtins.go [hunk 1]
```diff
@@ -336,6 +336,27 @@ var builtins = map[string]builtinDefinition{
...
+				index := int(tree.MustBeDInt(args[1]))
+				// Check whether index asked is inside ByteArray.
+				if index < 0 || index >= 8*len(byteString) {
+					return nil, pgerror.Newf(pgcode.ArraySubscript,
+						"bit index %d out of valid range (0..%d)", index, 8*len(byteString)-1)
+				}
+				// To extract a bit at the given index, we have to determine the
+				// position within byte array, i.e. index/8 after that checked
+				// the bit at residual index.
+				if byteString[index/8]&(byte(1)<<(8-1-byte(index)%8)) != 0 {
```
Comment (abhishek20123g) [inline pkg/sql/sem/builtins/builtins.go]: We could replace `8` with a `globally constant variable` or by `len(byte)` but avoided because, it very less likely it would be modified in future, and we had previously used it as `8` instead of defining as some constant.
```
if byteString[index/8]&(byte(1)<<(8-1-byte(index)%8)) != 0 {
```
use `8-1` instead of `7` thought it would be more understandable.

File: pkg/sql/sem/builtins/builtins.go [hunk 2]
```diff
@@ -364,6 +385,38 @@ var builtins = map[string]builtinDefinition{
...
+				// To update a bit at the given index, we have to determine the
+				// position within byte array, i.e. index/8 after that checked
+				// the bit at residual index.
+				// Forcefully making bit at the index to 0.
+				byteString[index/8] &= ^(byte(1) << (8 - 1 - byte(index)%8))
+				// Updating value at the index to toSet.
+				byteString[index/8] |= byte(toSet) << (8 - 1 - byte(index)%8)
+				return tree.NewDBytes(tree.DBytes(byteString)), nil
+			},
+			Info: "Updates a bit at given index in the byte array",
```
Comment (otan) [inline pkg/sql/sem/builtins/builtins.go]: nit: can you modify this (and the above get/set bit related builtins) the have a full stop (.) at the end of the sentence?

File: pkg/sql/sem/builtins/builtins.go (hunk 1 above)
Comment (otan) [reply pkg/sql/sem/builtins/builtins.go]: i think this is fine :)

File: pkg/sql/sem/builtins/builtins.go (hunk 2 above)
Comment (abhishek20123g) [reply pkg/sql/sem/builtins/builtins.go]: Sure

**Review by otan — APPROVED** [review]

**Comment by abhishek20123g** [comment]
**TF[YT]R** :blush:
