### PR TITLE
opt: relax assertion for lookup join columns

### LINKED ISSUE #120136: opt: query with ON CONFLICT DO NOTHING with a UNIQUE partial index causes test assertion failure
**Describe the problem**

I am hitting this error:
```
        (XX000) internal error: lookup join with columns that are not required
        check_expr.go:245: in CheckExpr()
        DETAIL: stack trace:
        github.com/cockroachdb/cockroach/pkg/sql/opt/memo/check_expr.go:245: CheckExpr()
        github.com/cockroachdb/cockroach/bazel-out/darwin_arm64-fastbuild/bin/pkg/sql/opt/memo/expr.og.go:25725: AddLookupJoinToGroup()
        github.com/cockroachdb/cockroach/pkg/sql/opt/xform/join_funcs.go:517: func1()
        github.com/cockroachdb/cockroach/pkg/sql/opt/xform/scan_index_iter.go:304: ForEachStartingAfter()
        github.com/cockroachdb/cockroach/pkg/sql/opt/xform/scan_index_iter.go:207: ForEach()
        github.com/cockroachdb/cockroach/pkg/sql/opt/xform/join_funcs.go:414: generateLookupJoinsImpl()
        github.com/cockroachdb/cockroach/pkg/sql/opt/xform/join_funcs.go:263: GenerateLookupJoins()
        github.com/cockroachdb/cockroach/bazel-out/darwin_arm64-fastbuild/bin/pkg/sql/opt/xform/explorer.og.go:2463: exploreAntiJoin()
        github.com/cockroachdb/cockroach/bazel-out/darwin_arm64-fastbuild/bin/pkg/sql/opt/xform/explorer.og.go:40: exploreGroupMember()
        github.com/cockroachdb/cockroach/pkg/sql/opt/xform/explorer.go:185: exploreGroup()
        github.com/cockroachdb/cockroach/pkg/sql/opt/xform/optimizer.go:537: optimizeGroup()
        github.com/cockroachdb/cockroach/pkg/sql/opt/xform/optimizer.go:300: optimizeExpr()
        github.com/cockroachdb/cockroach/pkg/sql/opt/xform/optimizer.go:579: optimizeGroupMember()
        github.com/cockroachdb/cockroach/pkg/sql/opt/xform/optimizer.go:524: optimizeGroup()
        github.com/cockroachdb/cockroach/pkg/sql/opt/xform/optimizer.go:300: optimizeExpr()
        github.com/cockroachdb/cockroach/pkg/sql/opt/xform/optimizer.go:579: optimizeGroupMember()
        github.com/cockroachdb/cockroach/pkg/sql/opt/xform/optimizer.go:524: optimizeGroup()
        github.com/cockroachdb/cockroach/pkg/sql/opt/xform/optimizer.go:718: optimizeEnforcer()
        github.com/cockroachdb/cockroach/pkg/sql/opt/xform/optimizer.go:669: enforceProps()
        github.com/cockroachdb/cockroach/pkg/sql/opt/xform/optimizer.go:564: optimizeGroupMember()
        github.com/cockroachdb/cockroach/pkg/sql/opt/xform/optimizer.go:524: optimizeGroup()
        github.com/cockroachdb/cockroach/pkg/sql/opt/xform/optimizer.go:270: Optimize()
        github.com/cockroachdb/cockroach/pkg/sql/plan_opt.go:606: buildExecMemo()
        github.com/cockroachdb/cockroach/pkg/sql/plan_opt.go:245: makeOptimizerPlan()
        github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:2225: makeExecPlan()
        github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:1698: dispatchToExecutionEngine()
        github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:1104: execStmtInOpenState()
        github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:145: func1()
        github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:3317: execWithProfiling()
        github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:144: execStmt()
        github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:2228: func1()
        github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:2233: execCmd()
```

**To reproduce**

Uncomment this line: https://github.com/cockroachdb/cockroach/blob/97d0582c752c2d6d36cdfa66f11d745ac221c874/pkg/sql/opt/memo/check_expr.go#L29-L31

then run
```
> create table t (a text primary key, b text, UNIQUE INDEX idx (b) WHERE a = 'xyz');

> INSERT INTO t values ('a', 'b') ON CONFLICT DO NOTHING;
ERROR: internal error: lookup join with columns that are not required
SQLSTATE: XX000
```

(or just add the above SQL statements to a logic test)

**Expected behavior**
No error

**Additional data / screenshots**
Using a master build based on 0440fd0c4d9.

I also encountered this in v23.2.

**Additional context**
I noticed this when trying to add a unique partial index on a system table, in https://github.com/cockroachdb/cockroach/pull/120068/

Jira issue: CRDB-36505

### PR DESCRIPTION
**Pull request by DrewKimball**
#### opt: relax assertion for lookup join columns

This commit relaxes the assertion that all columns projected by a
lookup join are "required". In particular, we can ignore "required"
columns from the right input for semi- and anti-joins, since they
have an implicit projection that removes right-input columns.

There is no release note because the error can only be encountered
during testing.

Fixes #120136

Release note: None

### CODE REVIEW

**Review by mw5h — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/129711#-:-O5Jea4u1RQFb7xzw8-Z:bnfp4nl)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained

**Review by mgartner — COMMENTED** [review]
The commit that added this check mentions how these extra columns can cause issues with costing: https://github.com/cockroachdb/cockroach/commit/81f3dfa64d35170990d4d37e7819624fba3bd9f2

So it seems like this check would be nice to have, in an ideal world. Did you explore what it would take to correct the lookup-join columns, mentioned here: https://github.com/cockroachdb/cockroach/issues/120136#issuecomment-1986209808

**Comment by DrewKimball** [comment]
>The commit that added this check mentions how these extra columns can cause issues with costing: 81f3dfa
>
>So it seems like this check would be nice to have, in an ideal world. Did you explore what it would take to correct the lookup-join columns, mentioned here: #120136 (comment)

I've updated this PR to relax the restriction for semi- and anti-joins, instead of removing it altogether.

File: pkg/sql/opt/xform/join_funcs.go [hunk 1]
```diff
@@ -480,6 +480,18 @@ func (c *CustomFuncs) generateLookupJoinsImpl(
...
+		//requiredCols.UnionWith(t.Relational().OutputCols)
+		//requiredCols.UnionWith(t.AllLookupFilters.OuterCols())
+		//requiredCols.UnionWith(t.On.OuterCols())
+		//requiredCols.UnionWith(t.KeyCols.ToSet())
+		//requiredCols.UnionWith(t.LookupExpr.OuterCols())
+		//requiredCols.UnionWith(t.RemoteLookupExpr.OuterCols())
+		//idx := m.Metadata().Table(t.Table).Index(t.Index)
+		//for i := range t.KeyCols {
+		//	requiredCols.Add(t.Table.ColumnID(idx.Column(i).Ordinal()))
+		//}
```
Comment (mgartner) [inline pkg/sql/opt/xform/join_funcs.go:493]: Looks like this was mistakenly included.

**Review by mgartner — APPROVED** [review]
Thanks for fixing this!

File: pkg/sql/opt/xform/join_funcs.go (hunk 1 above)
Comment (DrewKimball) [reply pkg/sql/opt/xform/join_funcs.go]: My mistake, removed it.

**Review by mgartner — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/129711#-:-O8x90lJ9X1jhijQo1tb:bnfp4nl)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @mw5h)

**Comment by DrewKimball** [comment]
TFTRs!

bors r+
