### PR TITLE
sql: fix COPY bugs for binary/csv formats

### LINKED ISSUE #63235: sql: COPY IN BINARY doesn't return correct format code to client
lib/pq's `txn.Prepare("COPY temp (num) FROM STDIN WITH binary")` should fail with `pq: only text format supported for COPY`, however this does not happen for CRDB, no error is returned. 

The error should be generated by lib/pq here: https://github.com/lib/pq/blob/master/copy.go#L89

Roughly 9/10 times no error will be returned, however 1/10 `pq: unrecognized client message type ClientMsgSimpleQuery` is returned.

To reproduce (This correctly errors when pointing it to a pg db):
Start a CRDB Cluster
1. `cockroach demo --empty `
2. Run the following script after replacing the postgres url with the one given by CRDB's console.
```
package main

import (
	"database/sql"
	"log"

	_ "github.com/lib/pq"
)

func main() {
	db, err := sql.Open("postgres", "postgres://root:admin@127.0.0.1:55977?sslmode=require")

	if err != nil {
		log.Fatal("error connecting to the database: ", err)
	}

	defer db.Close()

	txn, err := db.Begin()
	if err != nil {
		panic(err)
	}
	defer txn.Rollback()
	_, err = txn.Exec("CREATE TEMP TABLE temp (num INTEGER)")
	if err != nil {
		panic(err)
	}

	println("prepare?")
	_, err = txn.Prepare("COPY temp (num) FROM STDIN WITH binary")
	if err != nil {
		panic(err.Error())
	}

	// check that the protocol is in a valid state
	err = txn.Commit()
	if err != nil {
		panic(err)
	}
}
```

### LINKED ISSUE #68804: COPY CSV doesn't support bytea column
**Describe the problem**
COPY CSV does not support binary data. Since CSV is a text-based format, you have to encode `bytea` columns to hex or octal when generating the CSV. CockroachDB doesn't decode these encoded fields embedded in the CSV and instead inserts them as string into the bytea column.

**To Reproduce**

1. `cockroach demo`
2. `psql "postgres://demo:<password>@127.0.0.1:26257/movr?sslmode=require"`
2. `alter table users add column data bytea;`
3. `COPY users(id,city,data) FROM STDIN CSV;`
4. `8a3d70a3-d70a-4000-8000-00000000001d,seattle,"\x00"`
5. `\.`
6. `select * from users where id = '8a3d70a3-d70a-4000-8000-00000000001d';`
```sql
                  id                  |  city   | name | address | credit_card |    data
--------------------------------------+---------+------+---------+-------------+------------
 8a3d70a3-d70a-4000-8000-00000000001d | seattle |      |         |             | \x5c783030
```
7. `insert into users (id, city, data) values (gen_random_uuid(), 'new york', decode('00', 'hex'));`
8. `select * from users where data = '\x00';`
```sql
                  id                  |     city      |        name         |            address             | credit_card |     data
--------------------------------------+---------------+---------------------+--------------------------------+-------------+--------------
d4272cf3-589d-481b-97bb-ef8712b5d227  | new york      |                     |                                |             | \x00
```

The `data` column should be `\x00` and not `\x5c783030`. `5c783030` is the characters `\x00` encoded to hex, so it's doubly encoded. Regular insert works fine and can insert `\x00`. If you repeat the above steps using COPY in PostgreSQL, you also get `\x00`.

**Expected behavior**
Binary data to be inserted as is without being doubly encoded. In the above example the `data` should be `\x00` and not `\x5c783030`.

It should also probably support octal encoded `\00` format as well to have [parity](https://www.postgresql.org/docs/13/sql-copy.html) with PostgreSQL.

**Additional data / screenshots**

**Environment:**
* CockroachDB version v21.1.6
* Server OS: MacOS
* Client app: JDBC

**Additional context**
What was the impact?

Unable to move forward with the PoC.

cc @rafiss 

Epic CRDB-7217

### LINKED ISSUE #68805: pgwire: COPY binary protocol fails when the client chunks the data stream in the middle of a record
Per the pgwire spec:
> CopyData: Messages sent from the backend will always correspond to single data rows, but messages sent by frontends might divide the data stream arbitrarily.

The pgx/pgconn library divides binary COPY streams at arbitrary 64k boundaries
https://github.com/jackc/pgconn/blob/53f5fed36c570f0b5c98d6ec2415658c7b9bd11c/pgconn.go#L1217-L1222

Copying large amount of data thus leads to "partial copy data row" errors at https://github.com/cockroachdb/cockroach/blob/8de063f1c60767797f143a60c2413685794f21f6/pkg/sql/copy.go#L485 because the overall structure of the `copyMachine` code assumes that tuples aren't split across wire-message boundaries.

X-Ref: https://github.com/cockroachdb/cdc-sink/issues/45

Epic CRDB-7217

### PR DESCRIPTION
**Pull request by rafiss**
See individual commits:

sql: return correct format code for COPY
fixes #63235 

sql: COPY BINARY messages can be split at arbitrary boundaries 
fixes #68805 

sql: COPY CSV handles arbitrary message boundaries
refs #68805 

sql: fix byte escaping in COPY CSV input 
fixes #68804 

Release justification: Fixes for high-priority bugs in existing functionality. ("Another rule of thumb to consider: if a customer hit this bug after releasing, would we patch the release to fix it? If we would patch the release later to fix the bug, then usually it's best to fix the bug now.")

### CODE REVIEW

File: pkg/sql/copy.go [hunk 1]
```diff
@@ -387,6 +387,15 @@ func (c *copyMachine) readTextData(ctx context.Context, final bool) (brk bool, e
 }
 
 func (c *copyMachine) readCSVData(ctx context.Context, final bool) (brk bool, err error) {
+	// Don't try to parse the CSV until we read all the data. This is because
```
Comment (otan) [inline pkg/sql/copy.go:390]: should we look at improving this in future / make an issue?

File: pkg/sql/copy.go [hunk 2]
```diff
@@ -424,6 +424,17 @@ func (c *copyMachine) readCSVTuple(ctx context.Context, record []string) error {
 			exprs[i] = tree.DNull
 			continue
 		}
+		switch t := c.resultColumns[i].Typ; t.Family() {
+		case types.BytesFamily,
```
Comment (otan) [inline pkg/sql/copy.go:428]: where did you get this list from? how do we know it's complete?
(it's weird to me that e.g. Timestamp is ehre but Time is not)

File: pkg/sql/pgwire/testdata/pgtest/copy [hunk 3]
```diff
@@ -310,3 +310,184 @@ ReadyForQuery
...
+{"Type":"CopyInResponse","ColumnFormatCodes":[0,0]}
+{"Type":"CommandComplete","CommandTag":"COPY 2"}
+{"Type":"ReadyForQuery","TxStatus":"I"}
+{"Type":"DataRow","Values":[{"text":"1"},{"text":"6f6e65"}]}
+{"Type":"DataRow","Values":[{"text":"2"},{"text":"54"}]}
+{"Type":"CommandComplete","CommandTag":"SELECT 2"}
+{"Type":"ReadyForQuery","TxStatus":"I"}
+
+# Verify that byte-escape sequences are processed in CSV mode.
+# `MixceDU0` is base64 for `2,\x54`.
```
Comment (steven-sheehy) [inline pkg/sql/pgwire/testdata/pgtest/copy:466]: Does this support octal encoding as well like PostgreSQL [does](https://www.postgresql.org/docs/13/sql-copy.html)? Something like `1,"\157\156\145"`. Would be good to add a test if so.

File: pkg/sql/copy.go [hunk 4]
```diff
@@ -383,6 +387,15 @@ func (c *copyMachine) readTextData(ctx context.Context, final bool) (brk bool, e
 }
 
 func (c *copyMachine) readCSVData(ctx context.Context, final bool) (brk bool, err error) {
+	// Don't try to parse the CSV until we read all the data. This is because
+	// newlines can appear in the middle of CSV input if it's quoted, so
+	// we don't have a good way of knowing how many bytes to read for the next
+	// record ahead of time (without reimplementing all the CSV parsing logic
+	// here). This means the input buffer will keep growing -- the memory is
+	// accounted in processCopyData.
```
Comment (steven-sheehy) [inline pkg/sql/copy.go:395]: So what will happen if I want to upload a CSV file that's 10GB? It won't process a single row from it until all 10GBs are uploaded to memory? If so, that just trades one problem for another.

Comment (rafiss) [reply pkg/sql/copy.go:395]: I agree. I was thinking about how to do this and I think we'll need to fork the csv reader implementation from go. (we'd also need to do that anyway in order to support some of the other COPY options)

one added challenge is that the COPY CSV format requires a newline to appear after each record *except* for the last one. so if we encounter an EOF on an individual CopyData input buffer, it's hard to tell if that's the end of all the CSV input or if we need to check for another input buffer

tomorrow I'll take a look at how postgres does this and explore some other CSV parsers in go.

File: pkg/sql/copy.go (hunk 2 above)
Comment (rafiss) [reply pkg/sql/copy.go:428]: the list comes from from what `COPY FROM ... TEXT` is already doing: https://github.com/cockroachdb/cockroach/blob/61fdb08be3835e3c4e18ba6c0389bc7edc43d7d1/pkg/sql/copy.go#L660-L670

it seems old, wouldn't be surprised if it has the wrong types in it

i can extract that into its own function

File: pkg/sql/copy.go (hunk 1 above)
Comment (rafiss) [reply pkg/sql/copy.go:390]: as @steven-sheehy says this behavior isn't that good, and it might even be better to leave the CSV parsing as-is instead of doing this workaround

i'll give a real fix another shot.

File: pkg/sql/pgwire/testdata/pgtest/copy (hunk 3 above)
Comment (rafiss) [reply pkg/sql/pgwire/testdata/pgtest/copy:466]: yes it should. adding a test

File: pkg/sql/copy.go (hunk 4 above)
Comment (steven-sheehy) [reply pkg/sql/copy.go:395]: Would it help if I create a separate ticket just for partial records with COPY CSV with the info in my [comment](https://github.com/cockroachdb/cockroach/issues/68805#issuecomment-897891364)? That way this ticket could be merged sooner while the bigger problem with the CSV reader could be worked on separately?

File: pkg/sql/copy.go (hunk 2 above)
Comment (rafiss) [reply pkg/sql/copy.go:428]: hmmm actually looks like the list we have is already too big -- PG doesn't do this decoding for `TEXT` columns. i think we only want this for `BytesFamily`

File: pkg/sql/copy.go (hunk 4 above)
Comment (rafiss) [reply pkg/sql/copy.go:395]: yes, sure another ticket would help. if i don't get to this soon then we can go ahead with this PR without the CSV buffering changes

I did find that Postgres solves this by buffering line-by-line, and taking into account whether it is in a quoted field or not: https://github.com/postgres/postgres/blob/9626325da5e8e23ff90091bc96535495d350f06e/src/backend/commands/copyfromparse.c#L1090-L1096

File: pkg/sql/copy.go (hunk 2 above)
Comment (rafiss) [reply pkg/sql/copy.go:428]: hmmm actually this is wrong. I tested in PG, and COPY CSV does not do `\xdd` or `\ddd` escaping. Left a comment on https://github.com/cockroachdb/cockroach/issues/68804 explaining why that issue is happening

**Comment by rafiss** [comment]
This is ready for another look -- I updated the CSV buffering logic so it searches for a non-escaped newline.

File: pkg/sql/copy.go [hunk 5]
```diff
@@ -244,7 +245,9 @@ func (c *copyMachine) run(ctx context.Context) error {
 	case tree.CopyFormatText:
 		c.textDelim = []byte{c.delimiter}
 	case tree.CopyFormatCSV:
-		c.csvReader = csv.NewReader(&c.buf)
+		c.csvInput.Reset()
+		c.csvReader = csv.NewReader(&c.csvInput)
+		//c.csvReader = csv.NewReader(&c.buf)
```
Comment (otan) [inline pkg/sql/copy.go:250]: delete?

**Review by otan — APPROVED** [review]
nice!

File: pkg/sql/copy.go (hunk 5 above)
Comment (rafiss) [reply pkg/sql/copy.go:250]: fixed

**Comment by rafiss** [comment]
tftr!

bors r=otan
