### PR TITLE
diagnostics: ignore timeout errors; extend client timeout

### LINKED ISSUE #136224: diagnostics: client fails to update delivery timestamp when timeouts are experienced
Diagnostic delivery relies on an HTTP client successfully delivering a payload to the cockroach labs registration server. These payloads can get large on some clusters and cause timeouts during delivery.

When timeouts are hit, we currently don't update the delivery timestamp which, after recent licensing changes can eventually cause clusters to get throttled if enough consecutive timeouts are experienced.

We should update the successful delivery timestamp on HTTP client timeouts because those will typically signal a successful contact **attempt** on the part of the client, and usually result in successful processing of the response on the server even if the client doesn't receive a response back.

Jira issue: CRDB-45036

### PR DESCRIPTION
**Pull request by dhartunian**
diagnostics: ignore timeout errors; extend client timeout
Previously, we would not update the telemetry success timestamp on
http client timeouts. This can cause throttling on clusters that are
sending large payloads and timing out.

Additionally, the client timeout is extended to 1 minute from 3
seconds (default) to account for this.

Epic: None
Resolves: https://github.com/cockroachdb/cockroach/issues/136224

Release note (ops change): telemetry delivery is now considered
successful even in cases where we experience a network timeout. This
will prevent throttling in cases outside an operator's control.

### CODE REVIEW

File: pkg/server/diagnostics/reporter.go [hunk 1]
```diff
@@ -46,6 +49,11 @@ import (
 	"google.golang.org/protobuf/proto"
 )
 
+// TelemetryHttpTimeout allows for configuration of the client timeout
+// for sending telemetry reports. It is not expected that customers
+// whould tweak this.
```
Comment (kyle-a-wong) [inline pkg/server/diagnostics/reporter.go:54]: nit: sp

File: pkg/server/diagnostics/reporter.go [hunk 2]
```diff
@@ -46,6 +49,11 @@ import (
...
+var TelemetryHttpTimeout = envutil.EnvOrDefaultDuration("COCKROACH_TELEMETRY_HTTP_CLIENT_TIMEOUT", 5*time.Minute)
```
Comment (kyle-a-wong) [inline pkg/server/diagnostics/reporter.go:55]: nit: can this be private?

File: pkg/server/diagnostics/reporter.go [hunk 3]
```diff
@@ -184,7 +197,18 @@ func (r *Reporter) ReportDiagnostics(ctx context.Context) {
 		return
 	}
 
-	res, err := httputil.Post(
+	r.client.Do(func() {
+		timeout := TelemetryHttpTimeout
+		if timeout > 5*time.Minute {
+			timeout = 5 * time.Minute
+		}
+		if timeout < 3*time.Second {
```
Comment (kyle-a-wong) [inline pkg/server/diagnostics/reporter.go:205]: nit: else if

File: pkg/server/diagnostics/reporter.go [hunk 4]
```diff
@@ -99,6 +107,11 @@ type Reporter struct {
 	// regardless of whether the response we get back is successful or
 	// not.
 	LastSuccessfulTelemetryPing atomic.Int64
+
+	client struct {
```
Comment (kyle-a-wong) [inline pkg/server/diagnostics/reporter.go:111]: Should we add a docstring to this field, or do you think its self explanatory enough to need one?

File: pkg/server/diagnostics/reporter.go [hunk 5]
```diff
@@ -99,6 +107,11 @@ type Reporter struct {
...
+		sync.Once
```
Comment (kyle-a-wong) [inline pkg/server/diagnostics/reporter.go:112]: Would it be better t o create a `newDiagnosticReporter` constructor that sets this field instead of using sync.Once?

File: pkg/server/diagnostics/reporter.go (hunk 2 above)
Comment (dhartunian) [reply pkg/server/diagnostics/reporter.go:55]: I modify this in the test which is in a separate package

File: pkg/server/diagnostics/reporter.go (hunk 5 above)
Comment (dhartunian) [reply pkg/server/diagnostics/reporter.go]: agreed. done.

File: pkg/server/diagnostics/reporter.go (hunk 4 above)
Comment (dhartunian) [reply pkg/server/diagnostics/reporter.go]: removed.

File: pkg/server/diagnostics/reporter.go (hunk 3 above)
Comment (dhartunian) [reply pkg/server/diagnostics/reporter.go]: done.

File: pkg/server/diagnostics/reporter.go (hunk 1 above)
Comment (dhartunian) [reply pkg/server/diagnostics/reporter.go]: done.

File: pkg/server/diagnostics/diagnostics.go [hunk 6]
```diff
@@ -64,6 +65,10 @@ type TestingKnobs struct {
 	// OverrideReportingURL if set, overrides the URL used to report diagnostics.
 	// It is a pointer to pointer to allow overriding to the nil URL.
 	OverrideReportingURL **url.URL
+
+	// TimeSource if set will andused to set timestamp for last
```
Comment (kyle-a-wong) [inline pkg/server/diagnostics/diagnostics.go:69]: nit: sp

File: pkg/server/diagnostics/reporter.go (hunk 2 above)
Comment (kyle-a-wong) [reply pkg/server/diagnostics/reporter.go:54]: ack

**Review by kyle-a-wong — APPROVED** [review]
lgtm

File: pkg/server/diagnostics/diagnostics.go (hunk 6 above)
Comment (dhartunian) [reply pkg/server/diagnostics/diagnostics.go]: done

**Comment by dhartunian** [comment]
TFTR!

bors r+
