### PR TITLE
changefeedccl: fix TestAvroSchemaNaming

### LINKED ISSUE #150537: changefeedccl: TestAvroSchemaNaming sometimes has unexplained transient errors
Under https://github.com/cockroachdb/cockroach/pull/147705 , TestAvroSchemaNaming exhibits unexplained transient errors. It has been opted out of that PR's changes for now, but we should investigate it at some point.

Jira issue: CRDB-52749

### LINKED ISSUE #165169: ccl/changefeedccl: TestAvroSchemaNaming failed
ccl/changefeedccl.TestAvroSchemaNaming [failed](https://mesolite.cluster.engflow.com/invocations/default/8b918c97-59c1-4d1d-bbc6-bc6de936e50c?testReportRun=9&testReportShard=6&testReportAttempt=1#targets-Ly9wa2cvY2NsL2NoYW5nZWZlZWRjY2w6Y2hhbmdlZmVlZGNjbF90ZXN0) on master @ [7a924823002246b4fb02b54c3e71639d7a7a1e7c](https://github.com/cockroachdb/cockroach/commits/7a924823002246b4fb02b54c3e71639d7a7a1e7c):

Fatal error:

```
panic: close of closed channel [recovered, repanicked]

```
Stack: 

```
goroutine 253623 [running]:
testing.tRunner.func1.2({0x6c88dc0, 0x88dc530})
	GOROOT/src/testing/testing.go:1872 +0x237
testing.tRunner.func1()
	GOROOT/src/testing/testing.go:1875 +0x35b
panic({0x6c88dc0?, 0x88dc530?})
	GOROOT/src/runtime/panic.go:783 +0x132
github.com/cockroachdb/cockroach/pkg/ccl/changefeedccl.(*jobFeed).Close(0xc01a861740)
	pkg/ccl/changefeedccl/testfeed_test.go:649 +0x239
github.com/cockroachdb/cockroach/pkg/ccl/changefeedccl.(*kafkaFeed).Close(0xc01980c0c0)
	pkg/ccl/changefeedccl/testfeed_test.go:2188 +0x6b
github.com/cockroachdb/cockroach/pkg/ccl/changefeedccl.closeFeed({0x89fcd00, 0xc0043fec40}, {0x892eaa0?, 0xc01980c0c0?})
	pkg/ccl/changefeedccl/helpers_test.go:1428 +0x2f
github.com/cockroachdb/cockroach/pkg/ccl/changefeedccl.TestAvroSchemaNaming.func1(_, {0xc018ea8750, {0x7fa9060abcd8, 0xc019f3ce00}, {{0xd6f1c00, 0xd6f1c20, {0x1}}, {0xd6f1c00}, 0x0}, {{0x88f30a0, ...}, ...}}, ...)
	pkg/ccl/changefeedccl/encoder_test.go:740 +0xbbe
github.com/cockroachdb/cockroach/pkg/ccl/changefeedccl.cdcTestNamed.func1(_, {{0xc018ea8750, {0x7fa9060abcd8, 0xc019f3ce00}, {{0xd6f1c00, 0xd6f1c20, {...}}, {0xd6f1c00}, 0x0}, {{0x88f30a0, ...}, ...}}, ...}, ...)
	pkg/ccl/changefeedccl/helpers_test.go:1794 +0x56
github.com/cockroachdb/cockroach/pkg/ccl/changefeedccl.cdcTestNamedWithSystem.func1(0xc0043fec40)
	pkg/ccl/changefeedccl/helpers_test.go:1830 +0x293
testing.tRunner(0xc0043fec40, 0xc018f06ba0)
	GOROOT/src/testing/testing.go:1934 +0xea
created by testing.(*T).Run in goroutine 253618
	GOROOT/src/testing/testing.go:1997 +0x465
```
<details><summary>Log preceding fatal error</summary>
<p>

```
=== RUN   TestAvroSchemaNaming
    test_log_scope.go:172: test logs captured to: outputs.zip/logTestAvroSchemaNaming4221780520
    test_log_scope.go:82: use -show-logs to present logs inline
--- FAIL: TestAvroSchemaNaming (5.41s)
```
</p>
</details>

Parameters:
 - <code>attempt=1</code>
 - <code>run=9</code>
 - <code>shard=6</code>
<details><summary>Help</summary>
<p>

See also: [How To Investigate a Go Test Failure \(internal\)](https://cockroachlabs.atlassian.net/l/c/HgfXfJgM)
</p>
</details>
/cc @cockroachdb/cdc
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*TestAvroSchemaNaming.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/bazci/githubpost/issues)

</sub>

Jira issue: CRDB-61240

### PR DESCRIPTION
**Pull request by KeithCh**
**changefeedccl: fix TestAvroSchemaNaming**

The ALTER statement was causing feeds to fail with
"CHANGEFEED created on a table with a single column family (drivers)
cannot now target a table with 2 families". This is expected and we
separate the test into two cases to avoid the issue.

Fixes: #150537 
Release Note: None

---

**changefeedccl: fix testfeed shutdown**

Add synchronization to prevent the shutdown channel from being closed more than once.

Fixes: #165169 #165814
Release note: None

Note that I was able to repro both error cases consistently before the fixes and I have not seen them at all after.

### CODE REVIEW

File: pkg/ccl/changefeedccl/encoder_test.go
Comment (rharding6373) [inline pkg/ccl/changefeedccl/encoder_test.go]: Are these `defer closeFeed` redundant now?

File: pkg/ccl/changefeedccl/encoder_test.go [hunk 1]
```diff
@@ -715,6 +715,11 @@ func TestAvroSchemaNaming(t *testing.T) {
 		require.Contains(t, foo.registry.SchemaForSubject(`supermovr.public.drivers-key`), `supermovr`)
 		require.Contains(t, foo.registry.SchemaForSubject(`supermovr.public.drivers-value`), `supermovr`)
 
+		closeFeed(t, movrFeed)
+		closeFeed(t, fqnFeed)
+		closeFeed(t, prefixFeed)
+		closeFeed(t, prefixFQNFeed)
+
 		sqlDB.Exec(t, `ALTER TABLE movr.drivers ADD COLUMN vehicle_id int CREATE FAMILY volatile`)
```
Comment (rharding6373) [inline pkg/ccl/changefeedccl/encoder_test.go]: Is it possible to restructure the test to turn it into 2 sub-tests, or alter a different movr table to test the multi-family feed? Closing feeds before continuing with the test smells like the test is too complicated and is testing too many things.

**Review by rharding6373 — COMMENTED** [review]
Nice find!

File: pkg/ccl/changefeedccl/encoder_test.go (hunk 1 above)
Comment (KeithCh) [reply pkg/ccl/changefeedccl/encoder_test.go]: I like the idea of subtests.

File: pkg/ccl/changefeedccl/encoder_test.go [hunk 2]
```diff
@@ -640,109 +640,109 @@ func TestAvroSchemaNaming(t *testing.T) {
...
+			require.Contains(t, foo.registry.SchemaForSubject(`supermovr.public.drivers-key`), `supermovr`)
+			require.Contains(t, foo.registry.SchemaForSubject(`supermovr.public.drivers-value`), `supermovr`)
 		})
 
-		assertRegisteredSubjects(t, foo.registry, []string{
-			`supermovr.public.drivers-key`,
-			`supermovr.public.drivers-value`,
-		})
+		t.Run("multi_family", func(t *testing.T) {
+			sqlDB.Exec(t, `ALTER TABLE movr.drivers ADD COLUMN vehicle_id int CREATE FAMILY volatile`)
```
Comment (rharding6373) [inline pkg/ccl/changefeedccl/encoder_test.go]: It would still be ideal if this were on a different table. I'm not 100% sure that the subtests won't interfere.

**Review by rharding6373 — APPROVED** [review]
Thanks! I have one more suggestion to solidify the test.
