### PR TITLE
streamingccl: deflake TestRandomClientGeneration

### LINKED ISSUE #99343: ccl/streamingccl/streamingest: TestRandomClientGeneration failed
ccl/streamingccl/streamingest.TestRandomClientGeneration [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_StressBazel/9207044?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_StressBazel/9207044?buildTab=artifacts#/) on release-23.1 @ [751b17200b6026b73351c57cab734415d2c4b02a](https://github.com/cockroachdb/cockroach/commits/751b17200b6026b73351c57cab734415d2c4b02a):

```
=== RUN   TestRandomClientGeneration
    test_log_scope.go:161: test logs captured to: /artifacts/tmp/_tmp/90c1b75d835f45b8488807abb5b1092d/logTestRandomClientGeneration1740823187
    test_log_scope.go:79: use -show-logs to present logs inline
*
* INFO: Running test with the default test tenant. If you are only seeing a test case failure when this message appears, there may be a problem with your test case running within tenants.
*
*
* INFO: Running test with the default test tenant. If you are only seeing a test case failure when this message appears, there may be a problem with your test case running within tenants.
*
*
* INFO: Running test with the default test tenant. If you are only seeing a test case failure when this message appears, there may be a problem with your test case running within tenants.
*
    stream_ingestion_processor_test.go:404: 
        	Error Trace:	github.com/cockroachdb/cockroach/pkg/ccl/streamingccl/streamingest/stream_ingestion_processor_test.go:404
        	            				github.com/cockroachdb/cockroach/pkg/ccl/streamingccl/streamingest/stream_ingestion_processor_test.go:552
        	Error:      	"0" is not greater than "0"
        	Test:       	TestRandomClientGeneration
    panic.go:540: -- test log scope end --
test logs left over in: /artifacts/tmp/_tmp/90c1b75d835f45b8488807abb5b1092d/logTestRandomClientGeneration1740823187
--- FAIL: TestRandomClientGeneration (67.69s)
```
<p>Parameters: <code>TAGS=bazel,gss,race</code>
</p>
<details><summary>Help</summary>
<p>

See also: [How To Investigate a Go Test Failure \(internal\)](https://cockroachlabs.atlassian.net/l/c/HgfXfJgM)
</p>
</details>
/cc @cockroachdb/disaster-recovery
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*TestRandomClientGeneration.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)
</sub>

Jira issue: CRDB-25832

### PR DESCRIPTION
**Pull request by msbutler**
This patch fixes 4 bugs in TestRandomClientGeneration that were responsible for the persistent flakiness and lack of coverage in this test:
- the randomeStreamClient no longer instantiates keys with a table prefix that collides with the job info table prefix. This collision was the original cause of the flakes reported in #99343.
- getPartitionSpanToTableId() now generates a correct map from source partition key space to table Id. Previously, the key spans in the map didn't contain keys that mapped to anything logical in the cockroach key space.
- assertKVs() now checks for keys in the destination tenant keyspace.
- assertKVs() now actually asserts that kvs were found. Before, the assertion could pass if no keys were actually checked, which has been happening for months and allowed the bugs above to infest this test.

Fixes #99343

Release note: None

### CODE REVIEW

File: pkg/ccl/streamingccl/streamingest/stream_ingestion_processor_test.go [hunk 1]
```diff
@@ -545,13 +551,23 @@ func TestRandomClientGeneration(t *testing.T) {
...
+		// Note that target span must be rekeyed to the destination
+		// tenant key space.
+		startKey := ingestionCodec.TablePrefix(uint32(id))
+		targetSpan := roachpb.Span{Key: startKey, EndKey: startKey.PrefixEnd()}
+		if assertEqualKVs(t, srv, streamValidator, targetSpan,
+			maxResolvedTimestampPerPartition[pSpan]) {
+			foundKVs = true
+		}
 	}
+	require.Equal(t, true, foundKVs, "expected to find and assert equal kvs")
```
Comment (adityamaru) [inline pkg/ccl/streamingccl/streamingest/stream_ingestion_processor_test.go:570]: nit: could use `require.True`

File: pkg/ccl/streamingccl/streamingest/stream_ingestion_processor_test.go [hunk 2]
```diff
@@ -545,13 +551,23 @@ func TestRandomClientGeneration(t *testing.T) {
...
 		// the partition.
-		assertEqualKVs(t, tc, streamValidator, id, maxResolvedTimestampPerPartition[pSpan])
+		//
+		// Note that target span must be rekeyed to the destination
+		// tenant key space.
+		startKey := ingestionCodec.TablePrefix(uint32(id))
+		targetSpan := roachpb.Span{Key: startKey, EndKey: startKey.PrefixEnd()}
+		if assertEqualKVs(t, srv, streamValidator, targetSpan,
+			maxResolvedTimestampPerPartition[pSpan]) {
+			foundKVs = true
```
Comment (adityamaru) [inline pkg/ccl/streamingccl/streamingest/stream_ingestion_processor_test.go:567]: don't we want to assert equal kvs for each iteration of this loop? IIUC the way this is structured even if one partition has equal KVs but the others don't the test will pass, cause `foundKVs` will be true.

Comment (msbutler) [reply pkg/ccl/streamingccl/streamingest/stream_ingestion_processor_test.go:567]: ah good q, under stress-race, it's possible for one partition to produce no checkpoint events. The stream ingestion processor only shuts down 1000 checkpoint events were recorded, which can all occur from a single partition. I'll add a comment about this.

Comment (adityamaru) [reply pkg/ccl/streamingccl/streamingest/stream_ingestion_processor_test.go:567]: I see, but how will we differentiate actual key mismatches vs partitions not producing any checkpoint events? Will something fatal in `assertEqualKVs`?

**Review by adityamaru — APPROVED** [review]
Just one comment about how an unequal KV will bubble up to us but otherwise LGTM!

File: pkg/ccl/streamingccl/streamingest/stream_ingestion_processor_test.go (hunk 2 above)
Comment (msbutler) [reply pkg/ccl/streamingccl/streamingest/stream_ingestion_processor_test.go:568]: the function returns true if it validated at least one kv. So if there are no checkpoints, it will not validate any kvs and return false. If it surfaces any kvs, they will be validated with assertions. Added a bit more the func docstring to reflect this.

**Comment by msbutler** [comment]
TFTR!

bors r=adityamaru
