### PR TITLE
ui: Fixes the Problem Ranges Page to again display all node's problem ranges

### LINKED ISSUE #21236: ui: problemranges page never loads on local cluster
If I start a local cluster from scratch on current master (fa9a248617ffe4ab06f22c3b5cfef9165091a9a4) with fresh data directories and try to load the problemranges page, it hangs forever during the "Loading cluster status..." phase. There are no errors in the console.

I also saw this behavior when running on a 3-node cluster that had data in it when one node was down.

### PR DESCRIPTION
**Pull request by BramGruneir**
When the problem ranges page was updated in
284315a6c9c7859297fc9a41b4baca0fb8c5b17e to use a keyed cached value for each
request type (all nodes or an individual single node) instead of a single cached
value for all requests, that was causing the page to not always reload, had a
bug. Results for all nodes are stored using an empty string key, but
the lookup in ProblemRanges' component the was using an `undefined` key instead.
So even if the data was correctly returned it wouldn't update the display.

Release note (ui): Bug fix for the Problem Ranges debug page to again display
all the problem ranges for the cluster.

Fixes #21236.

### CODE REVIEW

**Comment by a-robinson** [comment]
Thanks!

**Review by vilterp — APPROVED** [review]
Looks good, though please either
- comment somewhere saying that "0" is a special value used to store the response for all ranges. (Is this a different type — an array instead of a single range?)
- better yet, use the string "index" or something instead of "0"

**Comment by BramGruneir** [comment]
Done.  I have no idea how to reply to your comment directly in github's review system. 

However, this whole page needs to be re-written with a loading spinner.  I might tackle that when I have some free time.

File: pkg/ui/src/redux/apiReducers.ts [hunk 1]
```diff
@@ -162,7 +161,7 @@ const problemRangesReducerObj = new KeyedCachedDataReducer(
 export const refreshProblemRanges = problemRangesReducerObj.refresh;
 
 export const certificatesRequestKey = (req: api.CertificatesRequestMessage): string =>
-  _.isEmpty(req.node_id) ? "" : req.node_id.toString();
+  _.isEmpty(req.node_id) ? "0" : req.node_id;
```
Comment (vilterp) [inline pkg/ui/src/redux/apiReducers.ts]: do you need to change this and the other `"0"` to `"all"` as well?

Comment (BramGruneir) [reply pkg/ui/src/redux/apiReducers.ts]: Doing that in a follow up PR already.  It might upset too much if I do it here.

Comment (vilterp) [reply pkg/ui/src/redux/apiReducers.ts]: So, the page won't work until you merge the follow up PR? What else is in the follow up PR?

Comment (BramGruneir) [reply pkg/ui/src/redux/apiReducers.ts]: Nah, this will always work.  The 0 doesn't matter.  There is no 0 node and we never request all certs at once, only one at a time.

Comment (vilterp) [reply pkg/ui/src/redux/apiReducers.ts]: oh, didn't realize that those changes weren't related. Just prettier reformatting things? got me again.

**Review by vilterp — APPROVED** [review]

**Comment by BramGruneir** [comment]
It wasn't prettier.  I've turn that horribleness off, it was messing with me.  That was me tinkering.  But it doesn't do any harm and my follow up PR (which will drop in 30 mins) fixes this again.  Just seemed pointless to remove the line here and rerun the CI.
