### PR TITLE
sql: return error message instead of panicking when altering default privileges on virtual schema

### LINKED ISSUE #81328: "ERROR: internal error: interface conversion: catalog.SchemaDescriptor is schemadesc.virtual, not *schemadesc.Mutable" thrown when altering default privileges on specific schema
**Describe the problem**

When I attempt to alter default privileges for a role on a specific schema in v22.1.0-rc.1, I get the following error:

~~~
demo@127.0.0.1:26257/movr> ALTER DEFAULT PRIVILEGES IN SCHEMA crdb_internal GRANT SELECT ON TABLES to cockroachlabs;
*
* ERROR: Queued as error a3d77143b5a04018bf744d67204c0460
*
ERROR: internal error: interface conversion: catalog.SchemaDescriptor is schemadesc.virtual, not *schemadesc.Mutable
SQLSTATE: XX000
DETAIL: stack trace:
github.com/cockroachdb/cockroach/pkg/util/errorutil/catch.go:29: ShouldCatch()
github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder/builder.go:182: func1()
GOROOT/src/runtime/panic.go:1038: gopanic()
GOROOT/src/runtime/iface.go:261: panicdottypeE()
GOROOT/src/runtime/iface.go:271: panicdottypeI()
github.com/cockroachdb/cockroach/pkg/sql/alter_default_privileges.go:82: alterDefaultPrivileges()
github.com/cockroachdb/cockroach/pkg/sql/opaque.go:105: planOpaque()
github.com/cockroachdb/cockroach/pkg/sql/opaque.go:68: buildOpaque()
github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder/opaque.go:69: tryBuildOpaque()
github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder/builder.go:377: buildStmt()
github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder/builder.go:241: buildStmtAtRoot()
github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder/builder.go:215: Build()
github.com/cockroachdb/cockroach/pkg/sql/plan_opt.go:540: buildExecMemo()
github.com/cockroachdb/cockroach/pkg/sql/plan_opt.go:213: makeOptimizerPlan()
github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:1345: makeExecPlan()
github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:1039: dispatchToExecutionEngine()
github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:686: execStmtInOpenState()
github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:143: execStmt()
github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:1873: func1()
github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:1877: execCmd()
github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:1799: run()
github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:747: ServeConn()
github.com/cockroachdb/cockroach/pkg/sql/pgwire/conn.go:724: func1()
src/runtime/asm_amd64.s:1581: goexit()

HINT: You have encountered an unexpected error.

Please check the public issue tracker to check whether this problem is
already tracked. If you cannot find it there, please report the error
with details by creating a new issue.

If you would rather not post publicly, please contact us directly
using the support form.

We appreciate your feedback.
~~~

The docs indicate this setting is a no-op meant for compatibility with PostgreSQL, but it would be helpful to have a more distinct error message.

I also imagine default privileges should be alterable given we’re expected to show default privileges in a specific schema per https://github.com/cockroachdb/cockroach/pull/79177 .
**To Reproduce**

What did you do? Describe in your own words.

1. In v22.1.0-rc.1, run `cockroach demo`.
2. Run `CREATE ROLE cockroachlabs WITH LOGIN;`
3. Run `ALTER DEFAULT PRIVILEGES IN SCHEMA crdb_internal GRANT SELECT ON TABLES to cockroachlabs;`
4. Observe error.

**Expected behavior**
A more useful error message if this statement isn't supported or a correction to the problem if it is.

**Environment:**
 - v22.1.0-rc.1
 - macOS 12.3.1
 - `cockroach demo`

Jira issue: CRDB-15239

### PR DESCRIPTION
**Pull request by RichardJCai**
Release note (sql change): Previously when one did
ALTER DEFAULT PRIVILEGES IN SCHEMA <virtual schema> a panic occured.

Now this returns the error message <virtual schema> is not a physical schema.

Fixes https://github.com/cockroachdb/cockroach/issues/81328

### CODE REVIEW

File: pkg/sql/alter_default_privileges.go [hunk 1]
```diff
@@ -80,7 +80,11 @@ func (p *planner) alterDefaultPrivileges(
 		if err != nil {
 			return nil, err
 		}
-		schemaDescs = append(schemaDescs, schemaDesc.(*schemadesc.Mutable))
+		mutableSchemaDesc, ok := schemaDesc.(*schemadesc.Mutable)
+		if !ok {
+			return nil, errors.Newf("%s is not a physical schema", schemaDesc.GetName())
```
Comment (rafiss) [inline pkg/sql/alter_default_privileges.go:85]: nit: could we make it use `pgerror.Newf` with `pgcode.invalid_parameter_value`?

**Review by rafiss — CHANGES_REQUESTED** [review]
minor nit then lgtm

**Comment by RichardJCai** [comment]
bors r=rafiss

**Comment by rafiss** [comment]
oh just noticed a nit - instead of `Release note (sql change)` this should be `Release note (bug fix)`

**Comment by RichardJCai** [comment]
Updated git message

bors r=rafiss
