### PR TITLE
roachtest: add passing tests for lib/pq and pgjdbc

### LINKED ISSUE #69190: roachtest: lib/pq failed
roachtest.lib/pq [failed](https://teamcity.cockroachdb.com/viewLog.html?buildId=3329754&tab=buildLog) with [artifacts](https://teamcity.cockroachdb.com/viewLog.html?buildId=3329754&tab=artifacts#/lib/pq) on master @ [7897f24246bef3cb94f9f4bfaed474ecaa9fdee6](https://github.com/cockroachdb/cockroach/commits/7897f24246bef3cb94f9f4bfaed474ecaa9fdee6):

```
The test failed on branch=master, cloud=gce:
test artifacts and logs in: /home/agent/work/.go/src/github.com/cockroachdb/cockroach/artifacts/lib/pq/run_1
	orm_helpers.go:245,orm_helpers.go:171,java_helpers.go:220,libpq.go:134,test_runner.go:777: 
		Tests run on Cockroach v21.2.0-alpha.00000000-3472-g7897f24246
		Tests run against lib/pq v1.10.2
		201 Total Tests Run
		168 tests passed
		33 tests failed
		7 tests skipped
		0 tests ignored
		1 test passed unexpectedly
		0 tests failed unexpectedly
		0 tests expected failed but skipped
		0 tests expected failed but not run
		---
		--- PASS: pq.TestErrorDuringStartup - https://github.com/cockroachdb/cockroach/issues/41551 (unexpected)
		For a full summary look at the lib/pq artifacts 
		
		An updated blocklist (libPQBlocklist21_2) is available in the artifacts' lib/pq log
```
<details><summary>Reproduce</summary>
<p>

See: [roachtest README](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/roachtest)

See: [CI job to stress roachtests](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestStress)

<p>For the CI stress job, click the ellipsis (...) next to the Run button and fill in:
* Changes / Build branch: master
* Parameters / `env.TESTS`: `^lib/pq$`
* Parameters / `env.COUNT`: &lt;number of runs&gt;
</p>
</p>
</details>
/cc @cockroachdb/sql-experience
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*lib/pq.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)
</sub>

### LINKED ISSUE #69527: roachtest: pgjdbc failed
roachtest.pgjdbc [failed](https://teamcity.cockroachdb.com/viewLog.html?buildId=3373578&tab=buildLog) with [artifacts](https://teamcity.cockroachdb.com/viewLog.html?buildId=3373578&tab=artifacts#/pgjdbc) on master @ [44ea1fa0eba8fc78544700ef4afded62ab98a021](https://github.com/cockroachdb/cockroach/commits/44ea1fa0eba8fc78544700ef4afded62ab98a021):

```
The test failed on branch=master, cloud=gce:
test artifacts and logs in: /home/agent/work/.go/src/github.com/cockroachdb/cockroach/artifacts/pgjdbc/run_1
	orm_helpers.go:245,orm_helpers.go:171,java_helpers.go:220,pgjdbc.go:185,pgjdbc.go:197,test_runner.go:777: 
		Tests run on Cockroach v21.2.0-alpha.00000000-3698-g44ea1fa0eb
		Tests run against pgjdbc REL42.2.19
		5298 Total Tests Run
		4469 tests passed
		829 tests failed
		60 tests skipped
		185 tests ignored
		2 tests passed unexpectedly
		0 tests failed unexpectedly
		0 tests expected failed but skipped
		0 tests expected failed but not run
		---
		--- PASS: org.postgresql.test.jdbc2.ParameterStatusTest.transactionalParametersAutocommit - https://github.com/cockroachdb/cockroach/issues/32562 (unexpected)
		--- PASS: org.postgresql.test.jdbc2.ParameterStatusTest.transactionalParametersCommit - https://github.com/cockroachdb/cockroach/issues/32562 (unexpected)
		For a full summary look at the pgjdbc artifacts 
		
		An updated blocklist (pgjdbcBlockList21_2) is available in the artifacts' pgjdbc log
```
<details><summary>Reproduce</summary>
<p>

See: [roachtest README](https://github.com/cockroachdb/cockroach/blob/master/pkg/cmd/roachtest/README.md)

</p>
</details>
/cc @cockroachdb/sql-experience
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*pgjdbc.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)
</sub>

### PR DESCRIPTION
**Pull request by rafiss**
fixes https://github.com/cockroachdb/cockroach/issues/69527
fixes https://github.com/cockroachdb/cockroach/issues/69190

Release justification: test only change
Release note: None

### CODE REVIEW

File: pkg/cmd/roachtest/tests/libpq_blocklist.go [hunk 1]
```diff
@@ -38,7 +71,6 @@ var libPQBlocklist20_2 = blocklist{
 	"pq.TestCopyInTypes":                             "5807",
 	"pq.TestCopyRespLoopConnectionError":             "5807",
 	"pq.TestEncodeAndParseTs":                        "41563",
-	"pq.TestErrorDuringStartup":                      "41551",
```
Comment (otan) [inline pkg/cmd/roachtest/tests/libpq_blocklist.go:41]: is this intentional (does it close issues on 21_1?) that said, i guess at some stage we should cleanup all these older version blocklists because they're per branch now (?)

**Review by arulajmani — COMMENTED** [review]
> Reviewed 1 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/69934)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rafiss and @RichardJCai)

___
*[pkg/cmd/roachtest/tests/libpq_blocklist.go, line 41 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/69934#-MjUiP0D5_BTM0wYBCbI:-MjUiP0D5_BTM0wYBCbJ:beh81oo) ([raw file](https://github.com/cockroachdb/cockroach/blob/b444f8594a8d714d7118f709d10c0759376ed22a/pkg/cmd/roachtest/tests/libpq_blocklist.go#L41)):*
> ```Go
> 	"pq.TestCopyRespLoopConnectionError":             "5807",
> 	"pq.TestEncodeAndParseTs":                        "41563",
> 	"pq.TestErrorDuringStartup":                      "41551",
> ```

Same question as Oliver, is this intentional?

**Comment by rafiss** [comment]
nope that was a mistake!

**Review by arulajmani — APPROVED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/69934#-:-MjUjvsI9b69SZrZelPW:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @otan, @rafiss, and @RichardJCai)

**Comment by rafiss** [comment]
tftr!

bors r=arulajmani
