### PR TITLE
roachtest: update ORMs under test

### LINKED ISSUE #79208: roachtest: typeorm failed
roachtest.typeorm [failed](https://teamcity.cockroachdb.com/viewLog.html?buildId=4755605&tab=buildLog) with [artifacts](https://teamcity.cockroachdb.com/viewLog.html?buildId=4755605&tab=artifacts#/typeorm) on master @ [fa0291175ecb983301d980247ad2ec6c7b233660](https://github.com/cockroachdb/cockroach/commits/fa0291175ecb983301d980247ad2ec6c7b233660):

```
		  | github.com/cockroachdb/cockroach/pkg/cmd/roachtest/tests.registerTypeORM.func1
		  | 	github.com/cockroachdb/cockroach/pkg/cmd/roachtest/tests/typeorm.go:151
		  | github.com/cockroachdb/cockroach/pkg/cmd/roachtest/tests.registerTypeORM.func2
		  | 	github.com/cockroachdb/cockroach/pkg/cmd/roachtest/tests/typeorm.go:185
		  | main.(*testRunner).runTest.func2
		  | 	main/pkg/cmd/roachtest/test_runner.go:875
		  | runtime.goexit
		  | 	GOROOT/src/runtime/asm_amd64.s:1581
		Wraps: (4) output in run_102252.459081583_n1_cd
		Wraps: (5) cd /mnt/data1/typeorm/ && sudo npm install --unsafe-perm=true --allow-root returned
		  | stderr:
		  | npm WARN old lockfile 
		  | npm WARN old lockfile The package-lock.json file was created with an old version of npm,
		  | npm WARN old lockfile so supplemental metadata must be fetched from the registry.
		  | npm WARN old lockfile 
		  | npm WARN old lockfile This is a one-time fix-up, please be patient...
		  | npm WARN old lockfile 
		  | npm WARN deprecated @types/dotenv@8.2.0: This is a stub types definition. dotenv provides its own type definitions, so you do not need this installed.
		  | npm WARN deprecated source-map-resolve@0.6.0: See https://github.com/lydell/source-map-resolve#deprecated
		  | npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
		  | npm WARN deprecated mkdirp@0.5.3: Legacy versions of mkdirp are no longer supported. Please update to mkdirp 1.x. (Note that the API surface has changed to use Promises in 1.x.)
		  | npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
		  | npm WARN deprecated source-map-url@0.4.0: See https://github.com/lydell/source-map-url#deprecated
		  | npm WARN deprecated har-validator@5.1.5: this library is no longer supported
		  | npm WARN deprecated chokidar@2.1.8: Chokidar 2 does not receive security updates since 2019. Upgrade to chokidar 3 with 15x fewer dependencies
		  | npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
		  | npm WARN deprecated source-map-resolve@0.5.2: See https://github.com/lydell/source-map-resolve#deprecated
		  | npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
		  | npm WARN deprecated node-pre-gyp@0.11.0: Please upgrade to @mapbox/node-pre-gyp: the non-scoped node-pre-gyp package is deprecated and only the @mapbox scoped package will recieve updates in the future
		  | npm WARN deprecated istanbul@0.4.5: This module is no longer maintained, try this instead:
		  | npm WARN deprecated   npm i nyc
		  | npm WARN deprecated Visit https://istanbul.js.org/integrations for other alternatives.
		  | npm WARN deprecated tar@2.2.2: This version of tar is no longer supported, and will not receive security updates. Please upgrade asap.
		  | npm ERR! code 243
		  | npm ERR! path /mnt/data1/typeorm/node_modules/better-sqlite3
		  | npm ERR! command failed
		  | npm ERR! command sh -c prebuild-install || npm run build-release
		  | npm ERR! 
		  |
		  | npm ERR! A complete log of this run can be found in:
		  | npm ERR!     /root/.npm/_logs/2022-04-01T10_22_53_327Z-debug-0.log
		  |
		  | stdout:
		Wraps: (6) COMMAND_PROBLEM
		Wraps: (7) Node 1. Command with error:
		  | ``````
		  | cd /mnt/data1/typeorm/ && sudo npm install --unsafe-perm=true --allow-root
		  | ``````
		Wraps: (8) exit status 243
		Error types: (1) *withstack.withStack (2) *errutil.withPrefix (3) *withstack.withStack (4) *errutil.withPrefix (5) *cluster.WithCommandDetails (6) errors.Cmd (7) *hintdetail.withDetail (8) *exec.ExitError
```
<details><summary>Help</summary>
<p>

See: [roachtest README](https://github.com/cockroachdb/cockroach/blob/master/pkg/cmd/roachtest/README.md)

See: [How To Investigate \(internal\)](https://cockroachlabs.atlassian.net/l/c/SSSBr8c7)

</p>
</details>
<details><summary>Same failure on other branches</summary>
<p>

- #77523 roachtest: typeorm failed [C-test-failure O-roachtest O-robot T-sql-experience branch-release-21.1]
</p>
</details>
/cc @cockroachdb/sql-experience
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*typeorm.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)
</sub>

Jira issue: CRDB-14637

### PR DESCRIPTION
**Pull request by rafiss**
fixes https://github.com/cockroachdb/cockroach/issues/79208

- typeorm: also fixes permission issues
- sqlalchemy
- pgx
- lib/pq
- pgjdbc
  -  also use secure mode for pgjdbc test. this lets us test SCRAM functionality.
  - includes a small error code change: pgwire: use InvalidPassword error code when appropriate

Release note: None

### CODE REVIEW

File: pkg/cmd/roachtest/tests/typeorm.go [hunk 1]
```diff
@@ -24,7 +24,7 @@ import (
 )
 
 var typeORMReleaseTagRegex = regexp.MustCompile(`^(?P<major>\d+)\.(?P<minor>\d+)\.(?P<point>\d+)$`)
-var supportedTypeORMRelease = "0.2.32"
+var supportedTypeORMRelease = "0.3.4"
```
Comment (rafiss) [inline pkg/cmd/roachtest/tests/typeorm.go:27]: holding off until 0.3.5 is released since we want https://github.com/typeorm/typeorm/commit/ec6c11920b70132396cd2e098b378b753f6e4d3f

**Review by otan — APPROVED** [review]

**Comment by rafiss** [comment]
bors r=otan

**Comment by rafiss** [comment]
bors r=otan
