### PR TITLE
roachtest: fix upreplicate/1to3 and rebalance/3to5

### LINKED ISSUE #56406: roachtest: replicate/up/1to3 failed
[(roachtest).replicate/up/1to3 failed](https://teamcity.cockroachdb.com/viewLog.html?buildId=2424980&tab=buildLog) on [master@61c96aaca632dfba5154d55d82c5af0732053b72](https://github.com/cockroachdb/cockroach/commits/61c96aaca632dfba5154d55d82c5af0732053b72):

```
The test failed on branch=master, cloud=gce:
test artifacts and logs in: /home/agent/work/.go/src/github.com/cockroachdb/cockroach/artifacts/replicate/up/1to3/run_1
	cluster.go:2670,allocator.go:70,allocator.go:78,test_runner.go:755: monitor failure: monitor task failed: 181s elapsed without changes, but replica count standard deviation is 543.86 (>10.00)
		(1) attached stack trace
		  -- stack trace:
		  | main.(*monitor).WaitE
		  | 	/home/agent/work/.go/src/github.com/cockroachdb/cockroach/pkg/cmd/roachtest/cluster.go:2658
		  | main.(*monitor).Wait
		  | 	/home/agent/work/.go/src/github.com/cockroachdb/cockroach/pkg/cmd/roachtest/cluster.go:2666
		  | main.registerAllocator.func1
		  | 	/home/agent/work/.go/src/github.com/cockroachdb/cockroach/pkg/cmd/roachtest/allocator.go:70
		  | main.registerAllocator.func2
		  | 	/home/agent/work/.go/src/github.com/cockroachdb/cockroach/pkg/cmd/roachtest/allocator.go:78
		  | main.(*testRunner).runTest.func2
		  | 	/home/agent/work/.go/src/github.com/cockroachdb/cockroach/pkg/cmd/roachtest/test_runner.go:755
		Wraps: (2) monitor failure
		Wraps: (3) attached stack trace
		  -- stack trace:
		  | main.(*monitor).wait.func2
		  | 	/home/agent/work/.go/src/github.com/cockroachdb/cockroach/pkg/cmd/roachtest/cluster.go:2714
		Wraps: (4) monitor task failed
		Wraps: (5) attached stack trace
		  -- stack trace:
		  | main.waitForRebalance
		  | 	/home/agent/work/.go/src/github.com/cockroachdb/cockroach/pkg/cmd/roachtest/allocator.go:240
		  | main.registerAllocator.func1.3
		  | 	/home/agent/work/.go/src/github.com/cockroachdb/cockroach/pkg/cmd/roachtest/allocator.go:68
		  | main.(*monitor).Go.func1
		  | 	/home/agent/work/.go/src/github.com/cockroachdb/cockroach/pkg/cmd/roachtest/cluster.go:2648
		  | golang.org/x/sync/errgroup.(*Group).Go.func1
		  | 	/home/agent/work/.go/pkg/mod/golang.org/x/sync@v0.0.0-20201020160332-67f06af15bc9/errgroup/errgroup.go:57
		  | runtime.goexit
		  | 	/usr/local/go/src/runtime/asm_amd64.s:1357
		Wraps: (6) 181s elapsed without changes, but replica count standard deviation is 543.86 (>10.00)
		Error types: (1) *withstack.withStack (2) *errutil.withPrefix (3) *withstack.withStack (4) *errutil.withPrefix (5) *withstack.withStack (6) *errutil.leafError

```

<details><summary>More</summary><p>

Artifacts: [/replicate/up/1to3](https://teamcity.cockroachdb.com/viewLog.html?buildId=2424980&tab=artifacts#/replicate/up/1to3)

[See this test on roachdash](https://roachdash.crdb.dev/?filter=status%3Aopen+t%3A.%2Areplicate%2Fup%2F1to3.%2A&sort=title&restgroup=false&display=lastcommented+project)
<sub>powered by [pkg/cmd/internal/issues](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)</sub></p></details>

### LINKED ISSUE #56412: roachtest: replicate/rebalance/3to5 failed
[(roachtest).replicate/rebalance/3to5 failed](https://teamcity.cockroachdb.com/viewLog.html?buildId=2424980&tab=buildLog) on [master@61c96aaca632dfba5154d55d82c5af0732053b72](https://github.com/cockroachdb/cockroach/commits/61c96aaca632dfba5154d55d82c5af0732053b72):

```
The test failed on branch=master, cloud=gce:
test artifacts and logs in: /home/agent/work/.go/src/github.com/cockroachdb/cockroach/artifacts/replicate/rebalance/3to5/run_1
	cluster.go:2670,allocator.go:70,allocator.go:86,test_runner.go:755: monitor failure: monitor task failed: 181s elapsed without changes, but replica count standard deviation is 482.45 (>42.00)
		(1) attached stack trace
		  -- stack trace:
		  | main.(*monitor).WaitE
		  | 	/home/agent/work/.go/src/github.com/cockroachdb/cockroach/pkg/cmd/roachtest/cluster.go:2658
		  | main.(*monitor).Wait
		  | 	/home/agent/work/.go/src/github.com/cockroachdb/cockroach/pkg/cmd/roachtest/cluster.go:2666
		  | main.registerAllocator.func1
		  | 	/home/agent/work/.go/src/github.com/cockroachdb/cockroach/pkg/cmd/roachtest/allocator.go:70
		  | main.registerAllocator.func3
		  | 	/home/agent/work/.go/src/github.com/cockroachdb/cockroach/pkg/cmd/roachtest/allocator.go:86
		  | main.(*testRunner).runTest.func2
		  | 	/home/agent/work/.go/src/github.com/cockroachdb/cockroach/pkg/cmd/roachtest/test_runner.go:755
		Wraps: (2) monitor failure
		Wraps: (3) attached stack trace
		  -- stack trace:
		  | main.(*monitor).wait.func2
		  | 	/home/agent/work/.go/src/github.com/cockroachdb/cockroach/pkg/cmd/roachtest/cluster.go:2714
		Wraps: (4) monitor task failed
		Wraps: (5) attached stack trace
		  -- stack trace:
		  | main.waitForRebalance
		  | 	/home/agent/work/.go/src/github.com/cockroachdb/cockroach/pkg/cmd/roachtest/allocator.go:240
		  | main.registerAllocator.func1.3
		  | 	/home/agent/work/.go/src/github.com/cockroachdb/cockroach/pkg/cmd/roachtest/allocator.go:68
		  | main.(*monitor).Go.func1
		  | 	/home/agent/work/.go/src/github.com/cockroachdb/cockroach/pkg/cmd/roachtest/cluster.go:2648
		  | golang.org/x/sync/errgroup.(*Group).Go.func1
		  | 	/home/agent/work/.go/pkg/mod/golang.org/x/sync@v0.0.0-20201020160332-67f06af15bc9/errgroup/errgroup.go:57
		  | runtime.goexit
		  | 	/usr/local/go/src/runtime/asm_amd64.s:1357
		Wraps: (6) 181s elapsed without changes, but replica count standard deviation is 482.45 (>42.00)
		Error types: (1) *withstack.withStack (2) *errutil.withPrefix (3) *withstack.withStack (4) *errutil.withPrefix (5) *withstack.withStack (6) *errutil.leafError

```

<details><summary>More</summary><p>

Artifacts: [/replicate/rebalance/3to5](https://teamcity.cockroachdb.com/viewLog.html?buildId=2424980&tab=artifacts#/replicate/rebalance/3to5)

[See this test on roachdash](https://roachdash.crdb.dev/?filter=status%3Aopen+t%3A.%2Areplicate%2Frebalance%2F3to5.%2A&sort=title&restgroup=false&display=lastcommented+project)
<sub>powered by [pkg/cmd/internal/issues](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)</sub></p></details>

### PR DESCRIPTION
**Pull request by tbg**
2988709487df12590eb8c117e8a79317eae660bf changed the proto enum
names for rangelog events related to up/downreplication, which
unfortunately leak into the `system.rangelog` table, breaking
the test due to its reliance on the original names.

Fixes #56406.
Fixes #56412.

Release note: None

### CODE REVIEW

File: pkg/cmd/roachtest/allocator.go [hunk 1]
```diff
@@ -23,11 +23,9 @@ import (
 
 func registerAllocator(r *testRegistry) {
 	runAllocator := func(ctx context.Context, t *test, c *cluster, start int, maxStdDev float64) {
-		const fixturePath = `gs://cockroach-fixtures/workload/tpch/scalefactor=10/backup`
 		c.Put(ctx, cockroach, "./cockroach")
-		c.Put(ctx, workload, "./workload")
 
-		// Start the first `start` nodes and restore the fixture
+		// Start the first `start` nodes and restore a tpch fixture.
```
Comment (tbg) [inline pkg/cmd/roachtest/allocator.go:28]: I had trouble loading the fixture locally so I just went and switched this to import and also use the built-in workload binary instead of the external one.

File: pkg/cmd/roachtest/allocator.go [hunk 2]
```diff
@@ -181,7 +181,8 @@ func allocatorStats(db *gosql.DB) (s replicationStats, err error) {
 	// NB: These are the storage.RangeLogEventType enum, but it's intentionally
 	// not used to avoid pulling in the dep.
 	eventTypes := []interface{}{
-		`split`, `add`, `remove`,
+		// NB: these come from storagepb.RangeLogEventType.
```
Comment (tbg) [inline pkg/cmd/roachtest/allocator.go:184]: the actual fix.

**Review by knz — APPROVED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/56727)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @aayushshah15)

**Comment by tbg** [comment]
TFTR!

bors r=knz
