### PR TITLE
kvserver: let BenchmarkEmptyRebalance wait for the raft group to be ready

### LINKED ISSUE #144940: kvserver: fix BenchmarkEmptyRebalance regression
BenchmarkEmptyRebalance started showing ~8000% increased time per operation in March. This issue it to investigate why this happened.

Jira issue: CRDB-49624

### PR DESCRIPTION
**Pull request by iskettaneh**
For leader leases, the raft group will take a few seconds before it can propose new entries because it needs store liveness heartbeats to start. This commit modifies the benchmark by making it wait until the group is ready.

Benchmark results:
name                          old time/op    new time/op    delta
EmptyRebalance/add-remove-12     2.85s ± 1%     0.03s ± 8%  -98.96%  (p=0.000 n=7+8)

name                          old alloc/op   new alloc/op   delta
EmptyRebalance/add-remove-12    12.3MB ±13%     1.9MB ± 3%  -84.85%  (p=0.000 n=10+8)

name                          old allocs/op  new allocs/op  delta
EmptyRebalance/add-remove-12     64.7k ± 2%     10.8k ± 0%  -83.29%  (p=0.000 n=10+8)

Fixes: #144940

Release note: None

### CODE REVIEW

**Review by pav-kv — APPROVED** [review]

File: pkg/kv/kvserver/client_replica_test.go [hunk 1]
```diff
@@ -5795,6 +5795,15 @@ func BenchmarkEmptyRebalance(b *testing.B) {
...
 
 	scratchRange := tc.ScratchRange(b)
+
+	// Before actually starting the benchmark, we need to make sure that the raft
+	// group is able to add/remove voters. This is important because in leader
+	// leases, it takes a few seconds for store liveness heartbeats to start.
+	// Therefore, it will take the first operation a few seconds to complete. This
+	// will skew the benchmark results.
+	tc.AddVotersOrFatal(b, scratchRange, tc.Target(1))
+	tc.RemoveVotersOrFatal(b, scratchRange, tc.Target(1))
```
Comment (pav-kv) [inline pkg/kv/kvserver/client_replica_test.go:5805]: Would making an arbitrary write to this scratch range achieve the same waiting effect? We just need the range to warm up?

Comment (iskettaneh) [reply pkg/kv/kvserver/client_replica_test.go:5807]: I don't think just issuing a write would have the same effect for this benchmark specifically. If there is only one peer in the current config, I believe that writes should be able to commit normally. However, proposing config changes require that the new config doesn't cause LeadSupportUntil regressing. We really need to make sure that store liveness heartbeats started before running the benchmark.

**Review by iskettaneh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/144941)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @arulajmani and @pav-kv)

File: pkg/kv/kvserver/client_replica_test.go (hunk 1 above)
Comment (pav-kv) [reply pkg/kv/kvserver/client_replica_test.go:5807]: Makes sense, thanks.

**Comment by iskettaneh** [comment]
TFTR!

bors r+
