### PR TITLE
roachtest: jepsen - ignore analysis timeouts

### LINKED ISSUE #164919: roachtest: jepsen/g2/parts-start-kill-2 failed
roachtest.jepsen/g2/parts-start-kill-2 [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/21199852?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/21199852?buildTab=artifacts#/jepsen/g2/parts-start-kill-2) on master @ [4559deed7a69713aa0874bd436e5453786517102](https://github.com/cockroachdb/cockroach/commits/4559deed7a69713aa0874bd436e5453786517102):

Failed with:

```
(jepsen.go:442).runJepsen: timed out
test artifacts and logs in: /artifacts/jepsen/g2/parts-start-kill-2/run_1
```
Cluster Node to Ip Mapping:
| Node | Public IP | Private IP |
| --- | --- | --- |
| teamcity-21199852-1772695740-98-n6cpu4-0001 | 35.231.37.200 | 10.142.3.23 |
| teamcity-21199852-1772695740-98-n6cpu4-0002 | 34.26.3.47 | 10.142.3.34 |
| teamcity-21199852-1772695740-98-n6cpu4-0003 | 34.23.84.8 | 10.142.3.38 |
| teamcity-21199852-1772695740-98-n6cpu4-0004 | 34.24.37.237 | 10.142.3.42 |
| teamcity-21199852-1772695740-98-n6cpu4-0005 | 34.23.67.234 | 10.142.3.10 |
| teamcity-21199852-1772695740-98-n6cpu4-0006 | 34.26.226.57 | 10.142.2.233 |

Parameters:
 - <code>arch=amd64</code>
 - <code>cloud=gce</code>
 - <code>coverageBuild=false</code>
 - <code>cpu=4</code>
 - <code>diskCount=0</code>
 - <code>encrypted=false</code>
 - <code>metamorphicLeases=epoch</code>
 - <code>runtimeAssertionsBuild=false</code>
<details><summary>Help</summary>
<p>

See: [roachtest README](https://github.com/cockroachdb/cockroach/blob/master/pkg/cmd/roachtest/README.md)

See: [How To Investigate \(internal\)](https://cockroachlabs.atlassian.net/l/c/SSSBr8c7)

See: [Grafana](https://go.crdb.dev/roachtest-grafana/teamcity-21199852/jepsen-g2-parts-start-kill-2/1772715343848/1772718258849)

</p>
</details>
/cc @cockroachdb/test-eng
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*jepsen/g2/parts-start-kill-2.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/bazci/githubpost/issues)

</sub>

Jira issue: CRDB-61077

### PR DESCRIPTION
**Pull request by golgeek**
During its run, Jepsen can accumulate a very large operation history (e.g., due to transaction retries that Jepsen does not handle at the client level).

This causes the post-run linearizability analysis to exceed the 40 min. roachtest timeout, generating numerous issues that are test flakes.

This patch detects scenarios in which the test times out, but the Jepsen workload succeeded (indicated by "Run complete" in jepsen.log). This situation means the timeout happened during the analysis phase, which is known to be flaky. We return a `TransientFailure` to file the failure as an X-Infra-Flake.

Epic: none
Fixes: #164919
Release note: None

### CODE REVIEW

File: pkg/cmd/roachtest/tests/jepsen.go [hunk 1]
```diff
@@ -424,6 +424,20 @@ func runJepsen(ctx context.Context, t test.Test, c cluster.Cluster, testName, ne
...
+		// Check for timeouts where the Jepsen workload completed but
+		// analysis took too long. This typically happens when the history
+		// is large (e.g., due to many transaction retries under chaos
+		// nemeses), making linearizability checking slow.
+		if !ignoreErr && testErr.Error() == "timed out" {
+			if err := runE(c, ctx, controller,
+				`grep -q "Run complete" /mnt/data1/jepsen/cockroachdb/store/latest/jepsen.log`,
+			); err == nil {
+				t.L().Printf("Jepsen workload completed but analysis timed out. " +
+					"Ignoring timeout as this indicates slow analysis, not a CockroachDB bug.")
```
Comment (srosenberg) [inline pkg/cmd/roachtest/tests/jepsen.go]: The fact that the checker timed out doesn't imply it's not a cockroachdb bug :) I think we should treat it as an infra flake by returning `TransientFailure`. This way, we'll still file an `X-infra-flake`.

Comment (golgeek) [reply pkg/cmd/roachtest/tests/jepsen.go]: > The fact that the checker timed out doesn't imply it's not a cockroachdb bug :)

Right, this stating this can't be a CRDB bug might be an overstatement.

I assume we could start a list of patterns that are not CRDB bugs, but generate a slow down in the analyze phase (`TransactionRetryError`, being one of them), but I'm afraid this will evolve into something unmaintainable that will timeout itself because of so many patterns to check.

> I think we should treat it as an infra flake by returning TransientFailure. This way, we'll still file an X-infra-flake.

Will we even look at them, if they're only flagged as `X-infra-flake`? Wouldn't that create a situation similar to the cluster creation failures?

Comment (srosenberg) [reply pkg/cmd/roachtest/tests/jepsen.go]: > Will we even look at them, if they're only flagged as X-infra-flake? 

We should. E.g., here is a recent unrelated jepsen X-infra-flake [1]. Both types are technically avoidable. Having them observable lets us track the frequency.

> Wouldn't that create a situation similar to the cluster creation failures?

Yes, but isn't that orthogonal? All known types of X-infra-flake are currently handled via github, that is, until [2] is tackled.

[1] https://github.com/cockroachdb/cockroach/issues/124052#issuecomment-3940944765
[2] https://github.com/cockroachdb/cockroach/issues/121696

Comment (golgeek) [reply pkg/cmd/roachtest/tests/jepsen.go]: Got it. Pushed an update to return a `TransientFailure` error after grabbing the logs, this way we'll have all info without the noise.

**Review by srosenberg — APPROVED** [review]
