### PR TITLE
roachtest: deflake `kv/quiescence/nodes=3`

### LINKED ISSUE #105980: roachtest: kv/quiescence/nodes=3 failed
roachtest.kv/quiescence/nodes=3 [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/10756609?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/10756609?buildTab=artifacts#/kv/quiescence/nodes=3) on release-23.1 @ [e12e85479312972b551677203849d29aeb38ad5f](https://github.com/cockroachdb/cockroach/commits/e12e85479312972b551677203849d29aeb38ad5f):

```
(kv.go:457).func1: QPS dropped from 3194.65 to 2361.53 (factor of 0.74, min allowed 0.80)
test artifacts and logs in: /artifacts/kv/quiescence/nodes=3/run_1
```
<p>Parameters: <code>ROACHTEST_arch=amd64</code>
, <code>ROACHTEST_cloud=gce</code>
, <code>ROACHTEST_cpu=4</code>
, <code>ROACHTEST_encrypted=false</code>
, <code>ROACHTEST_ssd=0</code>
</p>
<details><summary>Help</summary>
<p>

See: [roachtest README](https://github.com/cockroachdb/cockroach/blob/master/pkg/cmd/roachtest/README.md)

See: [How To Investigate \(internal\)](https://cockroachlabs.atlassian.net/l/c/SSSBr8c7)

</p>
</details>
/cc @cockroachdb/kv-triage
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*kv/quiescence/nodes=3.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)
</sub>

Jira issue: CRDB-29306

Epic CRDB-27234

### PR DESCRIPTION
**Pull request by erikgrinaker**
This roachtest measures kv0 QPS to ensure quiescence does not affect throughput too much. However, the test also runs a backup, which can interfere with QPS.

This patch disables backups for this test. It also disables expiration lease metamorphism, and reassigns the test to replication.

Resolves #105980.
Epic: none
Release note: None

### CODE REVIEW

File: pkg/cmd/roachtest/tests/kv.go [hunk 1]
```diff
@@ -433,15 +433,15 @@ func registerKVContention(r registry.Registry) {
...
 		Cluster:             r.MakeClusterSpec(4),
-		Leases:              registry.MetamorphicLeases,
+		Leases:              registry.EpochLeases,
 		SkipPostValidations: registry.PostValidationNoDeadNodes,
 		Run: func(ctx context.Context, t test.Test, c cluster.Cluster) {
 			nodes := c.Spec().NodeCount - 1
 			c.Put(ctx, t.Cockroach(), "./cockroach", c.Range(1, nodes))
 			c.Put(ctx, t.DeprecatedWorkload(), "./workload", c.Node(nodes+1))
-			c.Start(ctx, t.L(), option.DefaultStartOpts(), install.MakeClusterSettings(), c.Range(1, nodes))
+			c.Start(ctx, t.L(), option.DefaultStartOptsNoBackups(), install.MakeClusterSettings(), c.Range(1, nodes))
```
Comment (aliher1911) [inline pkg/cmd/roachtest/tests/kv.go:444]: I deflaked another test that relies on kv0 QPS and most effect was from:
```
install.MakeClusterSettings(install.ClusterSettingsOption{"sql.stats.automatic_collection.enabled": "false"})
```
we should disable them here as well.

**Review by aliher1911 — APPROVED** [review]
I think it needs another noisy neighbour disabled to make more stable. Otherwise 🚀
