### PR TITLE
release-20.2: sql: fix bug in temp object cleaner

### LINKED ISSUE #55086: sql: temp schema cleaner job always fails
**Describe the problem**

I have a local cluster that never cleans up it's temporary schemas.

The error log shows this:
```
406 sql/temporary_schema.go:468 ⋮ [n1] error during schema cleanup, retrying: ‹delete-temp-TABLE›: ‹unimplemented: schema change statement cannot follow
a statement that has written in the same transaction›
```

**To Reproduce**

```
root@:26257/defaultdb> SET CLUSTER SETTING sql.defaults.experimental_temporary_tables.enabled = 'true';

root@:26257/defaultdb> create temp table tmp(a int primary key);
CREATE TABLE

# exit the session, and start a new one

root@:26257/defaultdb> \d
           schema_name          |   table_name    | type  | estimated_row_count
--------------------------------+-----------------+-------+----------------------
  pg_temp_1601505050722443000_1 | tmp             | table |                   0
```

**Expected behavior**
The cleanup job should work and the temp schemas should be removed.

**Environment:**
Happening on CockroachDB master and release-20.2 branch.

### PR DESCRIPTION
**Pull request by thoszhang**
The temp object cleaner used to fail in some cases in the presence of
databases with no temp objects, because we would update the namespace
table in the transaction prior to deleting the descriptors without
setting the system config trigger. This PR fixes the bug by setting the
system config trigger explicitly.

Fixes #55086.

Release note (bug fix): Fixed a bug that caused temp tables to not be
cleaned up after the associated session was closed.

### CODE REVIEW

**Comment by lucy-zhang** [comment]
This was unintentionally fixed on master by switching to `descs.Txn` in https://github.com/cockroachdb/cockroach/commit/86eee612ff1fe7e825ed230b5ad93c3814609998.

File: pkg/sql/temporary_schema_test.go [hunk 1]
```diff
@@ -231,6 +231,14 @@ func TestTemporaryObjectCleaner(t *testing.T) {
 	)
 	defer tc.Stopper().Stop(context.Background())
 
+	{
+		// Create another empty database to ensure that cleanup still works in the
+		// presence of databases without temp objects. Regression test for #55086.
```
Comment (rafiss) [inline pkg/sql/temporary_schema_test.go:236]: would you mind adding this test to master as well? and perhaps a test in `pkg/sql/logictest/testdata/logic_test/temp_table` as well?

Comment (lucy-zhang) [reply pkg/sql/temporary_schema_test.go:236]: I can add a test to master. Do the logic tests test the cleanup path, though? I thought we issued all the statements in a single session.

Comment (rafiss) [reply pkg/sql/temporary_schema_test.go:236]: ah yes you are right.

**Review by rafiss — APPROVED** [review]
looks good! thanks

**Comment by adityamaru** [comment]
@lucy-zhang is this good to merge? We have a RESTORE fix which depends on this 🙂

**Comment by lucy-zhang** [comment]
@adityamaru merging now.
