### PR TITLE
ui: extract sql box to standalone component

### LINKED ISSUE #26079: ui: tab freezes chrome after some minutes, can't be refreshed
In Chrome, looking at a table schema view in a tab. After some minutes (5-10) it becomes unresponsive, can't be reloaded (i.e., I have to create a new tab and close the broken one), and the chrome task manager reports it using 150% CPU.

### PR DESCRIPTION
**Pull request by couchand**
This pulls out a component to display a SQL query.  The only page currently using it is the table details, but making it a separate component makes fixing a bug with highlight.js easier, and we hope to include SQL on more pages moving forward.

Fixes the issue that React re-renders would cause highlight.js to repeatedly add the same wrapper elements over and over.

Fixes #26079
Release note (admin ui change): Fixes an issue where the database table details page would become nonresponsive after some time.

### CODE REVIEW

File: pkg/ui/src/views/shared/components/sql/box.tsx [hunk 1]
```diff
@@ -0,0 +1,32 @@
...
+
+interface SqlBoxProps {
+  value: string;
+}
+
+export class SqlBox extends React.Component<SqlBoxProps> {
+  preNode: Node;
+
+  shouldComponentUpdate(newProps: SqlBoxProps) {
+    return newProps.value !== this.props.value;
```
Comment (vilterp) [inline pkg/ui/src/views/shared/components/sql/box.tsx]: 👍

File: pkg/ui/src/views/shared/components/sql/box.tsx [hunk 2]
```diff
@@ -0,0 +1,32 @@
...
+    hljs.highlightBlock(this.preNode);
+  }
+
+  componentDidUpdate() {
+    hljs.highlightBlock(this.preNode);
+  }
+
+  render() {
+    return (
+      <pre className="sql-highlight" ref={ (node) => this.preNode = node }>
```
Comment (vilterp) [inline pkg/ui/src/views/shared/components/sql/box.tsx]: Style nit: I prefer `(node) => { this.preNode = node }`, since having the `=>` and the `=` on the same level (i.e. neither is surrounded by braces) makes it a little hard to read. Don't super care though.

**Review by vilterp — APPROVED** [review]
