### PR TITLE
changefeedccl: deflake tests that expect frequent span-level checkpoints

### LINKED ISSUE #151279: ccl/changefeedccl: TestChangefeedSchemaChangeBackfillCheckpoint failed
ccl/changefeedccl.TestChangefeedSchemaChangeBackfillCheckpoint [failed](https://mesolite.cluster.engflow.com/invocations/default/a89e4432-e4fe-445c-b6a9-7194d3e86f15?testReportRun=2&testReportShard=3&testReportAttempt=1#targets-Ly9wa2cvY2NsL2NoYW5nZWZlZWRjY2w6Y2hhbmdlZmVlZGNjbF90ZXN0) on master @ [b065097dfc3353bea82cea588ce337d4a7c435c6](https://github.com/cockroachdb/cockroach/commits/b065097dfc3353bea82cea588ce337d4a7c435c6):

```
=== RUN   TestChangefeedSchemaChangeBackfillCheckpoint
    test_log_scope.go:171: test logs captured to: outputs.zip/logTestChangefeedSchemaChangeBackfillCheckpoint1127481135
    test_log_scope.go:82: use -show-logs to present logs inline
    changefeed_test.go:2704: random seed: 5818914711028344323
    changefeed_stmt.go:1584: requireNoFeedsFail: unexpected error: context canceled while waiting in queue: kv-elastic-cpu-queue, pri: bulk-normal-pri, start: 2025-08-02 11:37:26.610317718 +0000 UTC m=+105.780335885, dur: 173.500592ms
    changefeed_test.go:2973: -- test log scope end --
test logs left over in: outputs.zip/logTestChangefeedSchemaChangeBackfillCheckpoint1127481135
--- FAIL: TestChangefeedSchemaChangeBackfillCheckpoint (27.69s)
```

Parameters:
 - <code>attempt=1</code>
 - <code>race=true</code>
 - <code>run=2</code>
 - <code>shard=3</code>
<details><summary>Help</summary>
<p>

See also: [How To Investigate a Go Test Failure \(internal\)](https://cockroachlabs.atlassian.net/l/c/HgfXfJgM)
</p>
</details>
/cc @cockroachdb/cdc
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*TestChangefeedSchemaChangeBackfillCheckpoint.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/bazci/githubpost/issues)

</sub>

### PR DESCRIPTION
**Pull request by andyyang890**
**changefeedccl: delete leftover comment**

This patch deletes a leftover comment that should've been deleted in
the commit that had aggregators periodically flush their progress.

Release note: None

---

**changefeedccl: deflake tests that expect frequent span-level checkpoints**

In a recent commit, the interval at which change aggregators would
flush their frontiers to the change frontier was decoupled from
the span-level checkpoint interval (which is configurable via a
cluster setting). This caused some tests that only set the cluster
setting (and not `min_checkpoint_frequency`) to a low value to
sometimes flake. This patch updates all such tests to also configure
the `min_checkpoint_frequency` option.

[master]
Fixes #151279

[release-25.4]
Informs #154066

Release note: None

---

**changefeedccl: deflake initial backfill checkpoint tests**

This patch deflakes the initial backfill checkpoint tests, which filter
out resolved spans to force gaps during a backfill. The tests however
did not ensure that there would be at least one span that was not
filtered out, which would result in no span-level checkpoint being
created, leading the tests to time out.

Release note: None

### CODE REVIEW

File: pkg/ccl/changefeedccl/alter_changefeed_test.go [hunk 1]
```diff
@@ -1542,7 +1542,8 @@ func TestAlterChangefeedAddTargetsDuringBackfill(t *testing.T) {
 			context.Background(), &s.Server.ClusterSettings().SV, maxCheckpointSize)
 
 		registry := s.Server.JobRegistry().(*jobs.Registry)
-		testFeed := feed(t, f, `CREATE CHANGEFEED FOR foo WITH resolved = '100ms'`)
+		testFeed := feed(t, f, `CREATE CHANGEFEED FOR foo
+WITH resolved = '100ms', min_checkpoint_frequency='1ns'`)
```
Comment (aerfrei) [inline pkg/ccl/changefeedccl/alter_changefeed_test.go:1554]: Did we get test failures for flakes for these? If so, can we include issues in the commit message? If not, how did we discover this?

File: pkg/ccl/changefeedccl/alter_changefeed_test.go [hunk 2]
```diff
@@ -1542,7 +1542,8 @@ func TestAlterChangefeedAddTargetsDuringBackfill(t *testing.T) {
 			context.Background(), &s.Server.ClusterSettings().SV, maxCheckpointSize)
 
 		registry := s.Server.JobRegistry().(*jobs.Registry)
-		testFeed := feed(t, f, `CREATE CHANGEFEED FOR foo WITH resolved = '100ms'`)
+		testFeed := feed(t, f, `CREATE CHANGEFEED FOR foo
```
Comment (aerfrei) [inline pkg/ccl/changefeedccl/alter_changefeed_test.go:1553]: This test failed in extended CI for this commit. Is that related?

File: pkg/ccl/changefeedccl/alter_changefeed_test.go [hunk 3]
```diff
@@ -1520,19 +1520,27 @@ func TestAlterChangefeedAddTargetsDuringBackfill(t *testing.T) {
 
 		// Emit resolved events for the majority of spans. Be extra paranoid and ensure that
 		// we have at least 1 span for which we don't emit resolvedFoo timestamp (to force checkpointing).
-		haveGaps := false
-		knobs.FilterSpanWithMutation = func(r *jobspb.ResolvedSpan) (bool, error) {
+		// We however also need to ensure there's at least one span that isn't filtered out.
+		var allowedOne, haveGaps bool
```
Comment (aerfrei) [inline pkg/ccl/changefeedccl/alter_changefeed_test.go:1524]: Also here curious to see any linked flakes/issues.

File: pkg/ccl/changefeedccl/alter_changefeed_test.go (hunk 2 above)
Comment (andyyang890) [reply pkg/ccl/changefeedccl/alter_changefeed_test.go:1553]: I'm not currently seeing a failure in extended CI, maybe you're looking at an outdated run?

File: pkg/ccl/changefeedccl/alter_changefeed_test.go (hunk 3 above)
Comment (andyyang890) [reply pkg/ccl/changefeedccl/alter_changefeed_test.go:1524]: I fixed this in this PR because it was failing on Extended CI and I was also able to reproduce it on my gceworker

File: pkg/ccl/changefeedccl/alter_changefeed_test.go (hunk 1 above)
Comment (andyyang890) [reply pkg/ccl/changefeedccl/alter_changefeed_test.go:1554]: We haven't yet, but I'm preemptively updating it because of failures on other tests

Comment (aerfrei) [reply pkg/ccl/changefeedccl/alter_changefeed_test.go:1554]: Which other tests?

File: pkg/ccl/changefeedccl/alter_changefeed_test.go (hunk 2 above)
Comment (aerfrei) [reply pkg/ccl/changefeedccl/alter_changefeed_test.go:1553]: I'm seeing it for the second commit here: https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_BazelExtendedCi/20518187?expandBuildDeploymentsSection=false&hideTestsFromDependencies=false&expandBuildTestsSection=true&hideProblemsFromDependencies=false&expandBuildProblemsSection=true&expandBuildChangesSection=true.

**Review by aerfrei — APPROVED** [review]

File: pkg/ccl/changefeedccl/alter_changefeed_test.go (hunk 2 above)
Comment (andyyang890) [reply pkg/ccl/changefeedccl/alter_changefeed_test.go:1553]: Yeah that's the issue that the third commit is fixing, which I'm referencing in https://github.com/cockroachdb/cockroach/pull/154143#discussion_r2379773635

File: pkg/ccl/changefeedccl/alter_changefeed_test.go (hunk 1 above)
Comment (andyyang890) [reply pkg/ccl/changefeedccl/alter_changefeed_test.go:1554]: The one in the PR description (#151279) and previously #153918

File: pkg/ccl/changefeedccl/changefeed_test.go [hunk 4]
```diff
@@ -9115,22 +9117,21 @@ func TestChangefeedBackfillCheckpoint(t *testing.T) {
 
 		// Emit resolved events for majority of spans.  Be extra paranoid and ensure that
 		// we have at least 1 span for which we don't emit resolved timestamp (to force checkpointing).
-		haveGaps := false
+		// We however also need to ensure there's at least one span that isn't filtered out.
+		var allowedOne, haveGaps bool
 		knobs.FilterSpanWithMutation = func(r *jobspb.ResolvedSpan) (bool, error) {
 			if r.Span.Equal(tableSpan) {
-				// Do not emit resolved events for the entire table span.
```
Comment (asg0451) [inline pkg/ccl/changefeedccl/changefeed_test.go:9121]: why remove this bit? seems potentially useful

**Review by asg0451 — APPROVED** [review]

File: pkg/ccl/changefeedccl/changefeed_test.go (hunk 4 above)
Comment (andyyang890) [reply pkg/ccl/changefeedccl/changefeed_test.go:9121]: I had to remove the analogous piece of code in `TestAlterChangefeedAddTargetsDuringBackfill` in #153758 because it was causing rare flakes where this fake span got flushed to the change frontier and showed up in the checkpoint, which caused a test assertion to fail. Preemptively removing it here in case it causes similar flakes.

(Also a lot of other tests do something similar where they filter out the full table spans.)
