### PR TITLE
cli: make cockroach user atomic

### LINKED ISSUE #23203: Inconsistent behavior between CREATE USER and cockroach user set in insecure cluster
If you attempt to create a user with a password in an insecure cluster:
- When using `CREATE USER`, the user creation fails.
- When using `cockroach user set`, the user creation succeeds but without the password. 

I'm not sure which behavior is correct. I'd vote for failing user creation entirely. 

```
~/src/github.com/cockroachdb/cockroach$ cockroach user set jpointsman --insecure --password
Enter password:
Confirm password:
CREATE USER 1
Error: pq: cluster in insecure mode; user cannot use password authentication
Failed running "user"

~/src/github.com/cockroachdb/cockroach$ cockroach sql --insecure -e "SHOW USERS;"
+------------+
|  username  |
+------------+
| jpointsman |
| root       |
+------------+
(2 rows)

~/src/github.com/cockroachdb/cockroach$ cockroach sql --insecure -e "CREATE USER jesse WITH PASSWORD 'Q7gc8rEdS';"
Error: pq: cluster in insecure mode; user cannot use password authentication
Failed running "sql"

~/src/github.com/cockroachdb/cockroach$ cockroach sql --insecure -e "SHOW USERS;"
+------------+
|  username  |
+------------+
| jpointsman |
| root       |
+------------+
(2 rows)
```

### PR DESCRIPTION
**Pull request by vivekmenezes**
Run CREATE USER in a single transaction
so that a failure doesn't result in a partial success.
Before this change cockroach user would call
CREATE USER and ALTER USER FOR PASSWORD as two command.
If the ALTER USER failed after the CREATE USER the
user would still be created.

fixes #23203

Release note: None

### CODE REVIEW

File: pkg/cli/user.go [hunk 1]
```diff
@@ -150,16 +150,19 @@ func runSetUser(cmd *cobra.Command, args []string) error {
...
+		); err != nil {
+			return err
+		}
+	} else {
+		if err := runQueryAndFormatResults(conn, os.Stdout,
+			makeQuery(`CREATE USER IF NOT EXISTS $1`, args[0])); err != nil {
+			return err
+		}
 	}
+
```
Comment (benesch) [inline pkg/cli/user.go]: This could simplify:

```go
	if password {
		runQueryAndFormatResults(conn, os.Stdout,
			makeQuery(`CREATE USER IF NOT EXISTS $1 PASSWORD $2`, args[0], pwdString))
	}
	return runQueryAndFormatResults(conn, os.Stdout,
			makeQuery(`CREATE USER IF NOT EXISTS $1`, args[0]))
```

**Review by benesch — APPROVED** [review]

**Comment by vivekmenezes** [comment]
TFTR!

---

Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[pkg/cli/user.go, line 165 at r1](https://beta.reviewable.io/reviews/cockroachdb/cockroach/23207#-L6RGkE1zpifNxSV0OTi-r1-165:-L6RuYIz51yC0AZdE4Wg:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/6aaff17cd519e26a33eefb42e6a1171d63c22925/pkg/cli/user.go#L165)):*
<details><summary><i>Previously, benesch (Nikhil Benesch) wrote…</i></summary><blockquote>

This could simplify:

```go
	if password {
		runQueryAndFormatResults(conn, os.Stdout,
			makeQuery(`CREATE USER IF NOT EXISTS $1 PASSWORD $2`, args[0], pwdString))
	}
	return runQueryAndFormatResults(conn, os.Stdout,
			makeQuery(`CREATE USER IF NOT EXISTS $1`, args[0]))
```
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/cockroachdb/cockroach/23207#-:-L6Ru_r1EGcxUMucK7Pk:b-814g8k)*
