### PR TITLE
sql: clean up protected timestamps automatically on errors

### LINKED ISSUE #90774: sql: clean up protected timestamp installation logic for backfills
As a follow on to https://github.com/cockroachdb/cockroach/pull/89540, we need to deal with the following:

1. Stash the ID of the protected timestamp ID during job creation, so that we can easily clean up if things go wrong, instead of relying on the collection mechanism in pathological scenarios
2. Clean up the dependencies involved in installing protected timestamps and ideally move this logic into an interface, which can update or set this as needed.

Jira issue: CRDB-20939

### PR DESCRIPTION
**Pull request by fqazi**
Fixes: #90774

Previously, if a cockroach node was to crash, we would rely on the deleted protected timestamp clean up logic to remove ones installed for validation. This change allows, the clean up to happen during job fail / cancel, so that no delays occurs dealing with these protected timestamps.

Additionally, the entire logic to support adding these protected timestamps is now done in a dependency injection friendly manner,

Release note: None

### CODE REVIEW

**Review by ajwerner — COMMENTED** [review]
This is close. My feedback is cosmetic. 

> Reviewed 2 of 15 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/91135#-:-NGMarVn5w5Gmy97yUa5:bxjcy1r)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @benbardin and @fqazi)

___
*[`pkg/jobs/jobspb/jobs.proto` line 566 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/91135#-NGMZBFM1bVRTiNeYVnC:-NGMZBFN8QRgCb09X6g1:bllb9ly) ([raw file](https://github.com/cockroachdb/cockroach/blob/c1eb34d55da4bdb22e661755aa85acdd467e9429/pkg/jobs/jobspb/jobs.proto#L566)):*
> ```protobuf
>   // corresponding to this job.
>   bytes protected_timestamp_record = 7 [
>     (gogoproto.customname) = "ProtectedTimestampRecord",
> ```

nit: why the custom name?
___
*[`pkg/jobs/jobspb/jobs.proto` line 773 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/91135#-NGMZCQ681Dqr9JfxKJl:-NGMZCQ681Dqr9JfxKJm:bllb9ly) ([raw file](https://github.com/cockroachdb/cockroach/blob/c1eb34d55da4bdb22e661755aa85acdd467e9429/pkg/jobs/jobspb/jobs.proto#L773)):*
> ```protobuf
>   // corresponding to this job.
>   bytes protected_timestamp_record = 11 [
>     (gogoproto.customname) = "ProtectedTimestampRecord",
> ```

nit: why the custom name?
___
*[`pkg/jobs/jobsprotectedts/jobs_protected_ts_provider.go` line 34 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/91135#-NGMag-mC59qc2y1fr8Q:-NGMag-mC59qc2y1fr8R:b6pn2lj) ([raw file](https://github.com/cockroachdb/cockroach/blob/c1eb34d55da4bdb22e661755aa85acdd467e9429/pkg/jobs/jobsprotectedts/jobs_protected_ts_provider.go#L34)):*
> ```Go
> // timedProtectTimeStampGCPct wait a percentage of the GC time before
> // creating a protected timestamp record.
> const timedProtectTimeStampGCPct = 80
> ```

nit: make this constant `.8` as opposed to 80 to avoid any chance of integer division bugs in the type system. 
___
*[`pkg/jobs/jobsprotectedts/jobs_protected_ts_provider.go` line 94 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/91135#-NGM_Dys5G9OJ7Dj0WZC:-NGM_Dys5G9OJ7Dj0WZD:b755xv5) ([raw file](https://github.com/cockroachdb/cockroach/blob/c1eb34d55da4bdb22e661755aa85acdd467e9429/pkg/jobs/jobsprotectedts/jobs_protected_ts_provider.go#L94)):*
> ```Go
> 
> // Protect implements scexec.ProtectedTimestampForJobProvider.
> func (p *protectedTimestampForJobProvider) Protect(
> ```

is there a way we can make this take the `*jobs.Job` object itself? That provides additional safety. 
___
*[`pkg/jobs/jobsprotectedts/jobs_protected_ts_provider.go` line 99 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/91135#-NGMZRUT4I-PICO6GAz3:-NGMZRUT4I-PICO6GAz4:b-7ezdgz) ([raw file](https://github.com/cockroachdb/cockroach/blob/c1eb34d55da4bdb22e661755aa85acdd467e9429/pkg/jobs/jobsprotectedts/jobs_protected_ts_provider.go#L99)):*
> ```Go
> 	tableDesc catalog.TableDescriptor,
> 	readAsOf hlc.Timestamp,
> ) scexec.ProtectedTimestampForJobCleaner {
> ```

nit: I think it's more elegant to just rename `protectedTimestampForJobRecord` to `Manager` (which will read `jobprotectedts.Manager`) and then have that thing implicitly implement the `scexec` interfaces rather than tightly coupling this package to `scexec`. 
___
*[`pkg/jobs/jobsprotectedts/jobs_protected_ts_provider.go` line 99 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/91135#-NGMaRk_Et1TP1CXl905:-NGMaRk_Et1TP1CXl906:b-5ahd1e) ([raw file](https://github.com/cockroachdb/cockroach/blob/c1eb34d55da4bdb22e661755aa85acdd467e9429/pkg/jobs/jobsprotectedts/jobs_protected_ts_provider.go#L99)):*
> ```Go
> 	tableDesc catalog.TableDescriptor,
> 	readAsOf hlc.Timestamp,
> ) scexec.ProtectedTimestampForJobCleaner {
> ```

I think it's be totally fine to just have this thing return a function as opposed to an interface. 
___
*[`pkg/jobs/jobsprotectedts/jobs_protected_ts_provider.go` line 105 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/91135#-NGMa6HP8Y4Iro_Y3R4m:-NGMa6HP8Y4Iro_Y3R4n:bkyh57n) ([raw file](https://github.com/cockroachdb/cockroach/blob/c1eb34d55da4bdb22e661755aa85acdd467e9429/pkg/jobs/jobsprotectedts/jobs_protected_ts_provider.go#L105)):*
> ```Go
> 		jobID:                    int64(jobID),
> 	}
> 	jr.waitGrp.GoCtx(func(ctx context.Context) error {
> ```

How do you feel about refactoring this a bit into methods for waiting for the time to expire and then a method to do the protection? The logic is a bit too composed right now for my taste.

**Review by fqazi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/91135)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner and @benbardin)

___
*[`pkg/jobs/jobspb/jobs.proto` line 773 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/91135#-NGMZCQ681Dqr9JfxKJl:-NGO6Cu99QQWruKJA012:b-5mdk6a) ([raw file](https://github.com/cockroachdb/cockroach/blob/c1eb34d55da4bdb22e661755aa85acdd467e9429/pkg/jobs/jobspb/jobs.proto#L773)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

nit: why the custom name?
</blockquote></details>

Done.

The other ones in the jobs.proto package did the same, but its not needed.
___
*[`pkg/jobs/jobsprotectedts/jobs_protected_ts_provider.go` line 94 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/91135#-NGM_Dys5G9OJ7Dj0WZC:-NGONJTGEi5jCGFXKTXS:bummdzj) ([raw file](https://github.com/cockroachdb/cockroach/blob/c1eb34d55da4bdb22e661755aa85acdd467e9429/pkg/jobs/jobsprotectedts/jobs_protected_ts_provider.go#L94)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

is there a way we can make this take the `*jobs.Job` object itself? That provides additional safety. 
</blockquote></details>

Done.

Involved pushing the current job in the declarative world, which I think is fine.
___
*[`pkg/jobs/jobsprotectedts/jobs_protected_ts_provider.go` line 105 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/91135#-NGMa6HP8Y4Iro_Y3R4m:-NGON8HDArx0BnvoNHYg:b-5aeu0s) ([raw file](https://github.com/cockroachdb/cockroach/blob/c1eb34d55da4bdb22e661755aa85acdd467e9429/pkg/jobs/jobsprotectedts/jobs_protected_ts_provider.go#L105)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

How do you feel about refactoring this a bit into methods for waiting for the time to expire and then a method to do the protection? The logic is a bit too composed right now for my taste.
</blockquote></details>

Done.

I modified it into two parts, a method called ProtectBeforeGC and Protect. The former will install it before a GC occurs on a timer, and the latter instantly installs it.

File: pkg/jobs/jobsprotectedts/jobs_protected_ts_manager.go [hunk 1]
```diff
@@ -0,0 +1,225 @@
...
+	"github.com/cockroachdb/cockroach/pkg/sql/catalog"
+	"github.com/cockroachdb/cockroach/pkg/sql/catalog/descpb"
+	"github.com/cockroachdb/cockroach/pkg/util/ctxgroup"
+	"github.com/cockroachdb/cockroach/pkg/util/hlc"
+	"github.com/cockroachdb/cockroach/pkg/util/uuid"
+)
+
+// timedProtectTimeStampGCPct wait a percentage of the GC time before
+// creating a protected timestamp record.
+const timedProtectTimeStampGCPct = 0.8
```
Comment (msbutler) [inline pkg/jobs/jobsprotectedts/jobs_protected_ts_manager.go:33]: nit: sub "gc ttl"  for "gc time". This is less confusing for people without context, i.e. me :)

File: pkg/jobs/jobsprotectedts/jobs_protected_ts_manager.go [hunk 2]
```diff
@@ -0,0 +1,225 @@
...
+		systemConfig:        systemConfig,
+		jr:                  jr,
+	}
+}
+
+// ProtectBeforeGC adds a protected timestamp record for a historical
+// transaction for a specific table, once a certain percentage of the GC time has
+// elapsed. Returns a Cleaner function to cancel installation or remove the
+// protected  timestamp.
+func (p *Manager) ProtectBeforeGC(
```
Comment (msbutler) [inline pkg/jobs/jobsprotectedts/jobs_protected_ts_manager.go:96]: Is this function  supposed to guarantee that it will issue a PTS before the next GC job on the table? Either in this function or in the commit message, could you explain the purpose of this function? I.e. why would the caller use this as oppose to the Protect function?

File: pkg/jobs/jobsprotectedts/jobs_protected_ts_manager.go [hunk 3]
```diff
@@ -0,0 +1,225 @@
...
+	}
+}
+
+// Protect adds a protected timestamp record for a historical
+// transaction for a specific table immediately. Returns a Cleaner
+// function to remove the protected timestamp, if one was installed.
+func (p *Manager) Protect(
+	ctx context.Context,
+	jobID jobspb.JobID,
+	tableDesc catalog.TableDescriptor,
```
Comment (msbutler) [inline pkg/jobs/jobsprotectedts/jobs_protected_ts_manager.go:156]: Side note: i might refactor this function to pass a pts Target instead of a tableDesc, so DR could use this infra in Restore and Import.

**Review by msbutler — COMMENTED** [review]
I had a few questions, mostly for my own edification. I may use this infra in future work.

File: pkg/jobs/jobsprotectedts/jobs_protected_ts_manager.go (hunk 2 above)
Comment (fqazi) [reply pkg/jobs/jobsprotectedts/jobs_protected_ts_manager.go:98]: I clarified this with comments on ProtectBeforeGC:
//This method can be preferred in scenarios where the cost of installing
// a protected timestamp is more expensive relative to the typical length of an
// operation (for example multi-region)

and in the commit message:

A new jobsprotectedts.Manager object is introduced, which
can install timestamps synchronous or before the GC TTL
occurs. The asynchronous version ProtectedBeforeGC is
suited for validation where the cost of the protected
timestamp validation could be costly relative to validating
indexes. Whereas, the synchronous version is better suited
for cases where we know its an expensive operation and
a protected timestamp will always be needed.

File: pkg/jobs/jobsprotectedts/jobs_protected_ts_manager.go (hunk 3 above)
Comment (fqazi) [reply pkg/jobs/jobsprotectedts/jobs_protected_ts_manager.go:159]: Definitely, should try and get this adopted in other areas to streamline things, and the descriptor in this case was because it was natural on the schema change side.

File: pkg/jobs/jobsprotectedts/jobs_protected_ts_manager.go (hunk 2 above)
Comment (msbutler) [reply pkg/jobs/jobsprotectedts/jobs_protected_ts_manager.go:98]: Thanks, this makes thing clearer! One last q, that I think could be clarified. 

This function does not guarantee that a PTS will be written before the next gc run, right? It only guarantees that a PT will be issued in `time.Duration(float64(time.Duration(zoneCfg.GC.TTLSeconds)*time.Second) *
			timedProtectTimeStampGCPct)` seconds. I.e. if a GC is about to run, the PTS will get issued after this next GC job. IIUC, then perhaps this function should be renamed.

Comment (fqazi) [reply pkg/jobs/jobsprotectedts/jobs_protected_ts_manager.go:98]: That's a good point and both of them have the property to update existing records inside them which needs to be documented too. I'm tempted to call it TryToProtectBeforeGC, and document that it's best effort bases. For validation, this is done early so it should be pretty effective unless the GC TTL is crazy small.

Comment (fqazi) [reply pkg/jobs/jobsprotectedts/jobs_protected_ts_manager.go:98]: Added for the TryToProtectBeforeGC:
// The approach here is taken is heuristic
// and can be considered a best-effort basis since the GC TTL could change or
// the caller may not invoke this early enough in the transaction.

Added for Protect:
// If an existing record is found, it will be updated with
// a new timestamp

Comment (msbutler) [reply pkg/jobs/jobsprotectedts/jobs_protected_ts_manager.go]: sweet! this looks good to me, though I'll wait for andrew to give this a stamp. The DR refactors look good too.

**Review by msbutler — APPROVED** [review]

**Review by ajwerner — APPROVED** [review]
:lgtm: this is going to be handy. Let's let this bake on master for a bit before backporting it to 22.2

> Reviewed 4 of 15 files at r1, 13 of 16 files at r2, 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/91135#-:-NGXSlZf8_oqCk2v0BzP:b-dhlpah)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @benbardin, @fqazi, and @msbutler)

___
*[`pkg/jobs/jobsprotectedts/jobs_protected_ts_manager.go` line 70 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/91135#-NGXRsHc6EQOMrc3DWce:-NGXRsHc6EQOMrc3DWcf:bugoymx) ([raw file](https://github.com/cockroachdb/cockroach/blob/3ac09bc0cd9f2b3dec8170525ef96006a24a5369/pkg/jobs/jobsprotectedts/jobs_protected_ts_manager.go#L70)):*
> ```Go
> 		return v.ProtectedTimestampRecord
> 	default:
> 		panic("not supported")
> ```

nit: panic an assertion failed error so it doesn't get redacted?
___
*[`pkg/jobs/jobsprotectedts/jobs_protected_ts_manager.go` line 74 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/91135#-NGXRnxIA2XtfmoHQ5Dt:-NGXRnxIA2XtfmoHQ5Du:b-yfogau) ([raw file](https://github.com/cockroachdb/cockroach/blob/3ac09bc0cd9f2b3dec8170525ef96006a24a5369/pkg/jobs/jobsprotectedts/jobs_protected_ts_manager.go#L74)):*
> ```Go
> }
> 
> // NewManager creates a new protected timestamp provider
> ```

nit: `Manager`? 
___
*[`pkg/jobs/jobsprotectedts/jobs_protected_ts_manager.go` line 124 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/91135#-NGXSOt24loCRbcZbB86:-NGXSOt24loCRbcZbB87:b45j5zk) ([raw file](https://github.com/cockroachdb/cockroach/blob/3ac09bc0cd9f2b3dec8170525ef96006a24a5369/pkg/jobs/jobsprotectedts/jobs_protected_ts_manager.go#L124)):*
> ```Go
> 			return err
> 		}
> 		waitBeforeProtectedTS := time.Duration(float64(time.Duration(zoneCfg.GC.TTLSeconds)*time.Second) *
> ```

nit: `time.Duration` has a `Seconds()` method which returns a float64
___
*[`pkg/jobs/jobsprotectedts/jobs_protected_ts_manager.go` line 157 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/91135#-NGXS7p45T3yZM2aXL2C:-NGXS7p45T3yZM2aXL2D:bfshdbf) ([raw file](https://github.com/cockroachdb/cockroach/blob/3ac09bc0cd9f2b3dec8170525ef96006a24a5369/pkg/jobs/jobsprotectedts/jobs_protected_ts_manager.go#L157)):*
> ```Go
> // transaction for a specific table immediately in a synchronous
> // manner. If an existing record is found, it will be updated with
> // a new timestamp. Returns a Cleaner  function to remove the protected timestamp,
> ```

uber-nit: extra space after `Cleaner`

**Review by fqazi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/91135)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ajwerner, @benbardin, and @msbutler)

___
*[`pkg/jobs/jobsprotectedts/jobs_protected_ts_manager.go` line 96 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/91135#-NGOR_Ki94oHg6cJIE4c-r2-96:-NGZ9ZM5582xCqTcvOk8:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/3166b447084db8eb87bddd81766eee3048a3e5c1/pkg/jobs/jobsprotectedts/jobs_protected_ts_manager.go#L96)):*
<details><summary><i>Previously, msbutler (Michael Butler) wrote…</i></summary><blockquote>

sweet! this looks good to me, though I'll wait for andrew to give this a stamp. The DR refactors look good too.
</blockquote></details>

Done.
___
*[`pkg/jobs/jobsprotectedts/jobs_protected_ts_manager.go` line 157 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/91135#-NGXS7p45T3yZM2aXL2C:-NGZ9oA36-X9h9rEnm0P:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/3ac09bc0cd9f2b3dec8170525ef96006a24a5369/pkg/jobs/jobsprotectedts/jobs_protected_ts_manager.go#L157)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

uber-nit: extra space after `Cleaner`
</blockquote></details>

Done.

**Comment by fqazi** [comment]
@ajwerner @msbutler TFTR!
