### PR TITLE
sqlbase: bugfix in rowfetcher with multiple cfs

### LINKED ISSUE #29374: panic: Non-nullable column with no value!
Running v2.1.0-beta.20180827 on a 5 nodes cluster. One of the node crash with this panic message.

The column screenview:lastmodified was defined with default value.

lastmodified TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()

```
panic: Non-nullable column "screenview:lastmodified" with no value! Index scanned was "primary" with the index key columns (fp) and the values ('a6b301a0-1e78-4263-b351-e1347c99c2fa')

goroutine 160961941 [running]:
github.com/cockroachdb/cockroach/pkg/sql/sqlbase.(*RowFetcher).finalizeRow(0xc42687fc90, 0x2efbe40, 0xc43a67a0c0)
        /go/src/github.com/cockroachdb/cockroach/pkg/sql/sqlbase/rowfetcher.go:1276 +0x9d9
github.com/cockroachdb/cockroach/pkg/sql/sqlbase.(*RowFetcher).NextRow(0xc42687fc90, 0x2efbe40, 0xc43a67a0c0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
        /go/src/github.com/cockroachdb/cockroach/pkg/sql/sqlbase/rowfetcher.go:1028 +0x183
github.com/cockroachdb/cockroach/pkg/sql/distsqlrun.(*rowFetcherWrapper).Next(0xc430304ca0, 0xc42b1efb30, 0x0, 0x0, 0xc42b1efb30)
        /go/src/github.com/cockroachdb/cockroach/pkg/sql/distsqlrun/tablereader.go:141 +0x4a
github.com/cockroachdb/cockroach/pkg/sql/distsqlrun.(*tableReader).Next(0xc42687f800, 0x0, 0x0, 0x0, 0xc42b1efb30)
        /go/src/github.com/cockroachdb/cockroach/pkg/sql/distsqlrun/tablereader.go:238 +0x4e
github.com/cockroachdb/cockroach/pkg/sql/distsqlrun.Run(0x2efbe40, 0xc446d8aba0, 0x2f06300, 0xc42687f800, 0x2eda000, 0xc432698000)
        /go/src/github.com/cockroachdb/cockroach/pkg/sql/distsqlrun/base.go:170 +0x35
github.com/cockroachdb/cockroach/pkg/sql/distsqlrun.(*ProcessorBase).Run(0xc42687f800, 0x2efbe40, 0xc446d8aba0, 0xc42be2ff38)
        /go/src/github.com/cockroachdb/cockroach/pkg/sql/distsqlrun/processors.go:739 +0x98
created by github.com/cockroachdb/cockroach/pkg/sql/distsqlrun.(*Flow).StartAsync
        /go/src/github.com/cockroachdb/cockroach/pkg/sql/distsqlrun/flow.go:574 +0x1e3
```

### PR DESCRIPTION
**Pull request by jordanlewis**
A bug (introduced during the 2.1 cycle) caused scans issued via distsql
against tables with multiple column families to return incorrect results
or panic the server if some of the column families were marked as
non-nullable. This bug could only occur in distsql because it only
manifested when a rowfetcher was initialized with multiple input spans,
which only occurs in distsql where a particular node owns 2
non-contiguous portions of the keyspace. In this case, the code would
misinterpret the empty response from the scan request on the second
input span to mean that there was a limit on the last scan and that
we might have entered a new input span, which caused the rowfetcher to
mark the current row as ended and expect a full row starting from the
next key retrieved.

This was not the case, as this could happen in normal circumstances.
When a row had multiple column families, the rowfetcher would fail to
remember the results it had already seen for the earlier column families
in a row, if a batch happened to end half way through the row's column
families, and return incorrect and/or panic depending on the definition
of the table.

This patch removes this problem and adds a test for it. The test is a
little complicated but I verified that it does in fact panic before the
patch. It should catch problems like this in the future. We had no
explicit tests of the rowfetcher before with multiple input spans.

Note that this patch also deletes a test case, that tests correct
behavior in the case of seeing duplicate rows from the input stream
during an index join. This test case is contrived - index joins can
never encounter duplicate rows from the input stream - so it's safe to
delete.

Closes #29374.
Partially reverts #23474. The code no longer has protection against the condition that that PR was trying to guard against. But I don't think this is a problem in practice. If it crops up in new code it'll be very easy to notice and fix at that point.

cc @vivekmenezes

Release note: None

### CODE REVIEW

File: pkg/sql/sqlbase/kvfetcher.go [hunk 1]
```diff
@@ -357,48 +353,29 @@ func (f *txnKVFetcher) fetch(ctx context.Context) error {
 	return nil
 }
 
-func (f *txnKVFetcher) batchIsLimited(batchSize int64) bool {
-	if f.useBatchLimit {
-		// f.batchIdx - 1 refers to the most recent fetch.
-		return batchSize == f.getBatchSizeForIdx(f.batchIdx-1)
-	}
-	return false
```
Comment (vivekmenezes) [inline pkg/sql/sqlbase/kvfetcher.go]: return f.useBatchLimit && batchSize == f.getBatchSizeForIdx(f.batchIdx-1)

**Comment by jordanlewis** [comment]
So, turns out you do in fact need the duplicate spans protection - the index joiner can emit duplicate spans. So glad there's a test for that! Either way, I'll come up with a more precise way of determining whether we're on a new span - there should be no reason to have a "maybeNewSpan" boolean, since we are in fact able in the kvFetcher to detect precisely when a new span begins.

**Review by vivekmenezes — APPROVED** [review]

File: pkg/sql/sqlbase/kvfetcher.go (hunk 1 above)
Comment (jordanlewis) [reply pkg/sql/sqlbase/kvfetcher.go]: But I'm removing this code, not adding it! :)

**Comment by jordanlewis** [comment]
@solongordon reminded me that the test case that produces duplicate spans during an index join is contrived. An index join can never see duplicate rows in the input stream, because the input stream is made up of the full rows from an index - and indexes never have duplicate values inside of them. So, I've deleted that old contrived test case and left the patch alone.

**Review by RaduBerinde — COMMENTED** [review]
Duplicate spans are possible with lookup joins.

> This bug could only occur in distsql because it only
> manifested when a rowfetcher was initialized with multiple input spans,
> which only occurs in distsql where a particular node owns 2
> non-contiguous portions of the keyspace

I don't get this part, you can have multiple spans in local mode too, e.g. `SELECT * FROM t WHERE (k>=0 AND k<=5) OR (k>=10 AND k<=15))`.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/30394#-:-LMmIcvw3E49ZbT4cfci:bxuj9ey)* status: :shipit: complete! 0 of 0 LGTMs obtained

**Review by jordanlewis — COMMENTED** [review]
> Duplicate spans are possible with lookup joins.

Yes, but the lookup join code de-duplicates the spans before sending them in a request.

> I don't get this part, you can have multiple spans in local mode too, e.g. SELECT * FROM t WHERE (k>=0 AND k<=5) OR (k>=10 AND k<=15)).

Oh, I forgot about that. Hmm, maybe there was another way to create this panic then.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/30394#-:-LMmKM9w6ks4JxLooDxF:bl639dg)* status: :shipit: complete! 0 of 0 LGTMs obtained

**Review by solongordon — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/30394)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/sqlbase/rowfetcher_test.go, line 375 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/30394#-LMmKtS4CoyNeX_YlC0Z:-LMmKtS53Ou7WeCLzpc7:b13lahh) ([raw file](https://github.com/cockroachdb/cockroach/blob/cdbed6b246c0955916c06383c7b5edaf273da099/pkg/sql/sqlbase/rowfetcher_test.go#L375)):*
> ```Go
> 	// We try to read rows from each table.
> 	for tableName, table := range tables {
> 		t.Run(tableName, func(t *testing.T) {
> ```

Nit: There's some unnecessary boilerplate here since you one have one test case. Fine with me if you think it's clearer this way though.
___
*[pkg/sql/sqlbase/rowfetcher_test.go, line 425 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/30394#-LMmL53d1zVYUgE6O0Bh:-LMmL53e4TQAe4YMCGZ2:bp6izc8) ([raw file](https://github.com/cockroachdb/cockroach/blob/cdbed6b246c0955916c06383c7b5edaf273da099/pkg/sql/sqlbase/rowfetcher_test.go#L425)):*
> ```Go
> 			}
> 
> 			for {
> ```

I think it's better to be explicit about how many rows you expect.
___
*[pkg/sql/sqlbase/rowfetcher_test.go, line 432 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/30394#-LMmLB9gDFJbgy2Z1mH_:-LMmLB9gDFJbgy2Z1mHa:b-9dtla9) ([raw file](https://github.com/cockroachdb/cockroach/blob/cdbed6b246c0955916c06383c7b5edaf273da099/pkg/sql/sqlbase/rowfetcher_test.go#L432)):*
> ```Go
> 					t.Fatal(err)
> 				}
> 				if datums == nil {
> ```

`datums` is currently nil the first time around. Is that what you expect?

**Review by RaduBerinde — COMMENTED** [review]
Oh, I forgot we have separate code for index and lookup join.. I found the deduplication code you mentioned.

Maybe it's worth adding an assertion in RowFetcher that we don't have consecutive spans that are overlapping. Would help catch subtle bugs if we ever try to send those.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/30394#-:-LMmM00H7hvbypZ2m2-r:b-jlpotu)* status: :shipit: complete! 0 of 0 LGTMs obtained

**Review by jordanlewis — COMMENTED** [review]
We already have a similar assertion for span sortedness, but it's turned off if limitbatches is set to false, since index joiner needs to output unsorted spans. I added a similar assertion for overlapping spans, but only activated during race builds since normally there will be a lot of spans to check this condition on.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/30394#-:-LMmrJbSE74hT27guomL:b-1y2bn3)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/sqlbase/rowfetcher_test.go, line 375 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/30394#-LMmKtS4CoyNeX_YlC0Z:-LMmr-ro2yN4_yZU6V48:baio5wx) ([raw file](https://github.com/cockroachdb/cockroach/blob/cdbed6b246c0955916c06383c7b5edaf273da099/pkg/sql/sqlbase/rowfetcher_test.go#L375)):*
<details><summary><i>Previously, solongordon (Solon) wrote…</i></summary><blockquote>

Nit: There's some unnecessary boilerplate here since you one have one test case. Fine with me if you think it's clearer this way though.
</blockquote></details>

 Done.
___
*[pkg/sql/sqlbase/rowfetcher_test.go, line 425 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/30394#-LMmL53d1zVYUgE6O0Bh:-LMmr0ai42AgPhmYz1Ys:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/cdbed6b246c0955916c06383c7b5edaf273da099/pkg/sql/sqlbase/rowfetcher_test.go#L425)):*
<details><summary><i>Previously, solongordon (Solon) wrote…</i></summary><blockquote>

I think it's better to be explicit about how many rows you expect.
</blockquote></details>

Done.
___
*[pkg/sql/sqlbase/rowfetcher_test.go, line 432 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/30394#-LMmLB9gDFJbgy2Z1mH_:-LMmr1bJ1OQ7yLM6Nobl:bfj2bin) ([raw file](https://github.com/cockroachdb/cockroach/blob/cdbed6b246c0955916c06383c7b5edaf273da099/pkg/sql/sqlbase/rowfetcher_test.go#L432)):*
<details><summary><i>Previously, solongordon (Solon) wrote…</i></summary><blockquote>

`datums` is currently nil the first time around. Is that what you expect?
</blockquote></details>

No it's not, unless I"m missing something - I added a log statement here and I see 2 rows printed before the nil, as expected. Added the row count as an assertion though.

**Review by solongordon — APPROVED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/30394#-:-LMn9FJk-FvGnevc1_6h:bg7igkv)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/sql/sqlbase/rowfetcher_test.go, line 432 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/30394#-LMmLB9gDFJbgy2Z1mH_:-LMn8leo1NAexkssZT7N:b-2f1jie) ([raw file](https://github.com/cockroachdb/cockroach/blob/cdbed6b246c0955916c06383c7b5edaf273da099/pkg/sql/sqlbase/rowfetcher_test.go#L432)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

No it's not, unless I"m missing something - I added a log statement here and I see 2 rows printed before the nil, as expected. Added the row count as an assertion though.
</blockquote></details>

Sorry, my debugger was misbehaving and misled me. Feel free to ditch the print statement.

**Comment by jordanlewis** [comment]
Oops, of course I left the print statement in.
