### PR TITLE
ui: don't add highlight for * and ^

### LINKED ISSUE #81695: ui: searching for `*` in stmts/txns pages crashes page
In the statements and transactions fingerprints pages in SQL Activity, searching for a string containing `*` will crash the page.

This is due to the creation of a regex expression from the search string in the `getHighlightedText` function used in the stmts/txns tables to highlight words in the search string. We should escape the `*` char to avoid creating a malformed regex expr.

https://github.com/cockroachdb/cockroach/blob/1d09af89020b13f1afe56df46d91f641bb8e56a9/pkg/ui/workspaces/cluster-ui/src/highlightedText/highlightedText.tsx#L70

### PR DESCRIPTION
**Pull request by maryliag**
We don't highlight special characters that are normally
used on regex, but the characters `*` and `^` were not on
the list.
This commit adds them on the list to be ignored to highlight.
This commit also adds tests for the higlight function.

Fixes #81695

Release note (bug fix): properly handle special characters to
not being highlighted.

### CODE REVIEW

**Review by THardy98 — APPROVED** [review]
👍

File: pkg/ui/workspaces/cluster-ui/src/highlightedText/highlightedText.tsx [hunk 1]
```diff
@@ -80,18 +80,12 @@ export function getHighlightedText(
     return text;
   }
   highlight = highlight.replace(
-    /[°§%()\[\]{}\\?´`'#|;:+-]+/g,
+    /[°§%()\[\]{}\\?´`'#|;:+-^*]+/g,
```
Comment (knz) [inline pkg/ui/workspaces/cluster-ui/src/highlightedText/highlightedText.tsx:83]: The position of `-` here doesn't seem to be valid. A regexp of the form `[abc-jkl]` includes all characters between `c` and `j`, that is it is equivalent to `[abcdefghijkl]`.

If you want to include `-` in the list, you need to do it in a different way.

Comment (maryliag) [reply pkg/ui/workspaces/cluster-ui/src/highlightedText/highlightedText.tsx:83]: on the test of the function it works, also when I check manually for the replace:
```
let highlight = "select * from long-name";
highlight = highlight.replace(
    /[°§%()\[\]{}\\?´`'#|;:+-^*]+/g,
    "highlightNotDefined",
  );
  
  
value printed = 'select highlightNotDefined from longhighlightNotDefinedname'
```

Comment (maryliag) [reply pkg/ui/workspaces/cluster-ui/src/highlightedText/highlightedText.tsx:83]: what if I remove from the list and do a replace just for it, e.g.
```
let a = "abc-def-dert-rtwer-qwe + * ?";
a = a.replace(/[°§%()\[\]{}\\?´`'#|;:+^*]+/g, "X");
'abc-def-dert-rtwer-qwe X X X'
a = a.replace(/[-]/g, "X");
'abcXdefXdertXrtwerXqwe X X X'
```

Comment (maryliag) [reply pkg/ui/workspaces/cluster-ui/src/highlightedText/highlightedText.tsx:83]: if the regex ends with `-` it uses that literal character, but if the `-` is between two value then it uses the value in between, so I just need to move it back to the "end of the line", like it was previous to me adding the two new ones
