### PR TITLE
sql: update error message for primary key change on an interleave parent

### LINKED ISSUE #45537: sql: improve pk error messaging when using interleave tables
Consider this example with three tables. You can't alter the middle relationship because the bottom table is interleaved but this is confusing to the user because they are trying to remove the interleaving relationship with the top and middle tables:
```SQL
root@127.0.0.1:62260/movr> CREATE TABLE customers (
    id INT PRIMARY KEY,
    name STRING(50)
  );
CREATE TABLE
Time: 2.977ms
root@127.0.0.1:62260/movr> CREATE TABLE orders (
    customer INT,
    id INT,
    total DECIMAL(20, 5),
    PRIMARY KEY (customer, id),
    CONSTRAINT fk_customer FOREIGN KEY (customer) REFERENCES customers
  ) INTERLEAVE IN PARENT customers (customer);
CREATE TABLE
Time: 9.277ms
root@127.0.0.1:62260/movr> CREATE TABLE packages (
    customer INT,
    "order" INT,
    id INT,
    address STRING(50),
    delivered BOOL,
    delivery_date DATE,
    PRIMARY KEY (customer, "order", id),
    CONSTRAINT fk_order FOREIGN KEY (customer, "order") REFERENCES orders
  ) INTERLEAVE IN PARENT orders (customer, "order");
CREATE TABLE
Time: 10.423ms
root@127.0.0.1:62260/movr> set experimental_enable_primary_key_changes =true;
SET
Time: 257µs
root@127.0.0.1:62260/movr> ALTER TABLE orders ALTER PRIMARY KEY USING COLUMNS (id);
ERROR: cannot change the primary key of an interleaved parent
```

We could improve this error message to read something like:
```
ERROR: cannot change the primary key of orders because table packages is interleaved into it
```

### PR DESCRIPTION
**Pull request by rohany**
Fixes #45537.

This PR updates the error message when trying to perform a primary
key change on an interleaved parent to include the name of the
table as well as the names of the interleaved children.

Release note: None

### CODE REVIEW

File: pkg/sql/alter_table.go [hunk 1]
```diff
@@ -405,7 +406,39 @@ func (n *alterTableNode) startExec(params runParams) error {
 
 			// Disable primary key changes on tables that are interleaved parents.
 			if len(n.tableDesc.PrimaryIndex.InterleavedBy) != 0 {
-				return errors.New("cannot change the primary key of an interleaved parent")
+				if len(n.tableDesc.PrimaryIndex.InterleavedBy) == 1 {
+					childTable, err := params.p.Tables().getTableVersionByID(
+						params.ctx, params.p.Txn(), n.tableDesc.PrimaryIndex.InterleavedBy[0].Table, tree.ObjectLookupFlags{})
```
Comment (otan) [inline pkg/sql/alter_table.go]: wonder if it's worth less duplicating code by having just the one error message, looks something like

```
statement error pq: cannot change primary key of table parent because table(s) [child, child2, child3] is interleaved into it
```

also minor nit: prefer one arg per line if there are multiple lines for a function call (but not sure if this is a crdb convention).

**Review by otan — COMMENTED** [review]
nit: typo in commit message of `update`

File: pkg/sql/alter_table.go (hunk 1 above)
Comment (rohany) [reply pkg/sql/alter_table.go]: I'm a fan, updated.

**Comment by rohany** [comment]
Fixed both, ptal.

**Review by otan — APPROVED** [review]

**Comment by rohany** [comment]
bors r=otan

**Comment by rohany** [comment]
bors r=otan

**Comment by rohany** [comment]
bors r=otan

**Comment by rohany** [comment]
bors r=otan

**Comment by rohany** [comment]
dude what is bors doing

**Comment by otan** [comment]
May have crashed last night
