### PR TITLE
kvserver: deflake BenchmarkBumpSideTransportClosed

### LINKED ISSUE #151295: pkg/kv/kvserver: BenchmarkBumpSideTransportClosed failed
pkg/kv/kvserver.BenchmarkBumpSideTransportClosed [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachprodMicrobenchmarkWeeklyWip/20289400?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachprodMicrobenchmarkWeeklyWip/20289400?buildTab=artifacts#./artifacts/microbench/experiment) on master @ [ca0d4076c381609d6487040141c87e36a68b211f](https://github.com/cockroachdb/cockroach/commits/ca0d4076c381609d6487040141c87e36a68b211f):

```
goos: linux
goarch: amd64
cpu: Intel(R) Xeon(R) CPU @ 2.60GHz
BenchmarkBumpSideTransportClosed
    test_log_scope.go:171: test logs captured to: /tmp/logBenchmarkBumpSideTransportClosed1507158493
    test_log_scope.go:82: use -show-logs to present logs inline
    replica_closedts_test.go:736: -- test log scope end --
    test_log_scope.go:171: test logs captured to: /tmp/logBenchmarkBumpSideTransportClosed354871636
    test_log_scope.go:82: use -show-logs to present logs inline
    replica_closedts_test.go:736: -- test log scope end --
    test_log_scope.go:171: test logs captured to: /tmp/logBenchmarkBumpSideTransportClosed1630114694
    test_log_scope.go:82: use -show-logs to present logs inline
    replica_closedts_test.go:736: -- test log scope end --
    test_log_scope.go:171: test logs captured to: /tmp/logBenchmarkBumpSideTransportClosed4113031375
    test_log_scope.go:82: use -show-logs to present logs inline
    replica_closedts_test.go:736: -- test log scope end --
    test_log_scope.go:171: test logs captured to: /tmp/logBenchmarkBumpSideTransportClosed3499275865
    test_log_scope.go:82: use -show-logs to present logs inline
    replica_closedts_test.go:733: BumpSideTransportClosed unexpectedly failed
    panic.go:636: -- test log scope end --
--- FAIL: BenchmarkBumpSideTransportClosed-32
FAIL

I250803 23:11:05.788308 1 (gostd) rand.go:268  [-] 1  random seed: 1809778845682530433
test logs left over in: /tmp/logBenchmarkBumpSideTransportClosed3499275865
```
<details><summary>Help</summary>
<p>

See also: [How To Investigate a Go Test Failure \(internal\)](https://cockroachlabs.atlassian.net/l/c/HgfXfJgM)
</p>
</details>
/cc @cockroachdb/kv-triage
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*BenchmarkBumpSideTransportClosed.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/bazci/githubpost/issues)

</sub>

Jira issue: CRDB-53196

### PR DESCRIPTION
**Pull request by pav-kv**
Fixes #151295

### CODE REVIEW

File: pkg/kv/kvserver/replica_closedts_test.go [hunk 1]
```diff
@@ -730,6 +732,8 @@ func BenchmarkBumpSideTransportClosed(b *testing.B) {
 		// Perform the call.
 		res := r.BumpSideTransportClosed(ctx, now, targets)
 		if !res.OK {
+			d := kvtestutils.RaftLogDumper{Dir: scope.GetDirectory()}
+			d.Dump(b, store.LogEngine(), store.StoreID(), r.RangeID)
```
Comment (pav-kv) [inline pkg/kv/kvserver/replica_closedts_test.go]: I guess I can remove this raft dump now, after getting to the bottom of this.

Comment (pav-kv) [reply pkg/kv/kvserver/replica_closedts_test.go]: Done.

**Review by iskettaneh — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/151317#-:-OX3m7DBCCA-9F_nOpIW:bnfp4nl)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @arulajmani)

**Comment by pav-kv** [comment]
TFTR!

bors r=iskettaneh
