### PR TITLE
changefeedccl: Tolerate a lack of trailing zeroes when encoding decimal columns

### LINKED ISSUE #38058: cdc: Avro number roundtrip error on changefeed creation
This Github issue is synchronized with Zendesk:

**Ticket ID:** [#3388](https://cockroachdb.zendesk.com/agent/tickets/3388)
**Group:** Support
**Requester:** hakan.wikstrom@kindredgroup.com
**Organization:** Kindred Group
**Assignee:** Ricardo Rocha
**Issue escalated by:** Ricardo Rocha

**Original ticket description:**

<blockquote><div class="zd-comment" dir="auto">
<p dir="auto">Hi, I am trying to enable a changefeed from CRDB to Kafka but I get an error I do not understand. The exact same command works for a less complex table with less data.</p>

<p dir="auto">Actual SQL:
<br>CREATE CHANGEFEED FOR TABLE tx_engine_si1.tx INTO 'kafka://kafka-0.pt1.d2-dev.aws.kindredgroup.com:20000' WITH confluent_schema_registry = '<a href="http://pt1-schema-registry.d2-dev.aws.kindredgroup.com:80" target="_blank" rel="nofollow noreferrer">http://pt1-schema-registry.d2-dev.aws.kindredgroup.com:80</a>', format = 'experimental_avro'</p>

<p dir="auto">Result: Failed, with error as follows:
<br>internal error: uncaught error: 1E+2 will not roundtrip at scale 2
<br>github.com/cockroachdb/cockroach/pkg/ccl/changefeedccl.decimalToRat
<br>	/go/src/github.com/cockroachdb/cockroach/pkg/ccl/changefeedccl/avro.go:593
<br>github.com/cockroachdb/cockroach/pkg/ccl/changefeedccl.columnDescToAvroSchema.func19
<br>	/go/src/github.com/cockroachdb/cockroach/pkg/ccl/changefeedccl/avro.go:263
<br>github.com/cockroachdb/cockroach/pkg/ccl/changefeedccl.columnDescToAvroSchema.func27
<br>	/go/src/github.com/cockroachdb/cockroach/pkg/ccl/changefeedccl/avro.go:320
<br>github.com/cockroachdb/cockroach/pkg/ccl/changefeedccl.(*avroDataRecord).nativeFromRow
<br>	/go/src/github.com/cockroachdb/cockroach/pkg/ccl/changefeedccl/avro.go:458
<br>github.com/cockroachdb/cockroach/pkg/ccl/changefeedccl.(*avroEnvelopeRecord).BinaryFromRow
<br>	/go/src/github.com/cockroachdb/cockroach/pkg/ccl/changefeedccl/avro.go:572
<br>github.com/cockroachdb/cockroach/pkg/ccl/changefeedccl.(*confluentAvroEncoder).EncodeValue
<br>	/go/src/github.com/cockroachdb/cockroach/pkg/ccl/changefeedccl/encoder.go:358
<br>github.com/cockroachdb/cockroach/pkg/ccl/changefeedccl.emitEntries.func1
<br>	/go/src/github.com/cockroachdb/cockroach/pkg/ccl/changefeedccl/changefeed.go:188
<br>github.com/cockroachdb/cockroach/pkg/ccl/changefeedccl.emitEntries.func2
<br>	/go/src/github.com/cockroachdb/cockroach/pkg/ccl/changefeedccl/changefeed.go:236
<br>github.com/cockroachdb/cockroach/pkg/ccl/changefeedccl.(*changeAggregator).tick
<br>	/go/src/github.com/cockroachdb/cockroach/pkg/ccl/changefeedccl/changefeed_processors.go:270
<br>github.com/cockroachdb/cockroach/pkg/ccl/changefeedccl.(*changeAggregator).Next
<br>	/go/src/github.com/cockroachdb/cockroach/pkg/ccl/changefeedccl/changefeed_processors.go:252
<br>github.com/cockroachdb/cockroach/pkg/sql/distsqlrun.Run
<br>	/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsqlrun/base.go:174
<br>github.com/cockroachdb/cockroach/pkg/sql/distsqlrun.(*ProcessorBase).Run
<br>	/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsqlrun/processors.go:801
<br>github.com/cockroachdb/cockroach/pkg/sql/distsqlrun.(*Flow).startInternal.func1
<br>	/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsqlrun/flow.go:566
<br>runtime.goexit
<br>	/usr/local/go/src/runtime/asm_amd64.s:1333</p>
</div></blockquote>

### PR DESCRIPTION
**Pull request by HonoreDB**
Our avro encoder errors out when given a decimal with a fixed width
that normalizes to a different width. This does not work with how
we currently store and retrieve decimal data, so when we know we've
hit this case, normalize to the stored width before encoding.

Release note (bug fix): Changefeeds no longer error with
"1e2 is not roundtrippable at scale 2" when 100 is stored
in a column with width 2.

Closes #38058

### CODE REVIEW

File: pkg/ccl/changefeedccl/avro.go [hunk 1]
```diff
@@ -299,14 +299,23 @@ func columnDescToAvroSchema(colDesc *descpb.ColumnDescriptor) (*avroSchemaField,
...
+			Precision:   prec,
+			Scale:       width,
 		}
 		schema.encodeFn = func(d tree.Datum) (interface{}, error) {
 			dec := d.(*tree.DDecimal).Decimal
+
+			// If the decimal happens to fit a smaller width than the
+			// column allows, add trailing zeroes so the scale is constant
+			if colDesc.Type.Width() > -dec.Exponent {
+				tree.DecimalCtx.WithPrecision(uint32(prec)).Quantize(&dec, &dec, -int32(width))
```
Comment (shermanCRL) [inline pkg/ccl/changefeedccl/avro.go:316]: Probably want to check the return values of `Quantize`?

Also, `Quantize` seems to offer the possibility of rounding – can we guarantee that doesn’t happen?

Comment (HonoreDB) [reply pkg/ccl/changefeedccl/avro.go]: `WithPrecision` (and the column definition) should be guaranteeing that doesn't happen. Added a return value check just in case. Thanks for reviewing!

**Review by miretskiy — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/59075)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @HonoreDB and @shermanCRL)

___
*[pkg/ccl/changefeedccl/avro_test.go, line 485 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/59075#-MS05Var2ynF_4cmTO9q:-MS05Var2ynF_4cmTO9r:b-nzxec7) ([raw file](https://github.com/cockroachdb/cockroach/blob/6041ecb0cd19b44cebe3ed85f075614b8df4583d/pkg/ccl/changefeedccl/avro_test.go#L485)):*
> ```Go
> 			{sqlType: `DECIMAL(12,2)`,
> 				sql:  `1e2`,
> 				avro: `{"bytes.decimal":"'\u0010"}`},
> ```

perhaps fe more test cases? maybe w/ negative exponent?
___
*[pkg/ccl/changefeedccl/avro_test.go, line 488 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/59075#-MS057DF8Ce0UYJRLybS:-MS057DF8Ce0UYJRLybT:b5rifqw) ([raw file](https://github.com/cockroachdb/cockroach/blob/6041ecb0cd19b44cebe3ed85f075614b8df4583d/pkg/ccl/changefeedccl/avro_test.go#L488)):*
> ```Go
> 		}
> 
> 		for _, test := range truncs {
> ```

isn't it more common to have truncs test cases defined outside of the t.Run...
```
truncs := ...
for i, test := range truncs{
   t.Run(fmt.Sprintf("lossless-%d", i), func(....))
}
```

**Review by miretskiy — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/59075)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @HonoreDB and @shermanCRL)

___
*[pkg/ccl/changefeedccl/avro.go, line 315 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/59075#-MS3JPcEA7OW_mCVIAV6:-MS3JPcEA7OW_mCVIAV7:b-jtaahz) ([raw file](https://github.com/cockroachdb/cockroach/blob/6041ecb0cd19b44cebe3ed85f075614b8df4583d/pkg/ccl/changefeedccl/avro.go#L315)):*
> ```Go
> 			// If the decimal happens to fit a smaller width than the
> 			// column allows, add trailing zeroes so the scale is constant
> 			if colDesc.Type.Width() > -dec.Exponent {
> ```

Curious: Why are we checking for negative exponent?

**Review by HonoreDB — COMMENTED** [review]
> Dismissed @shermanCRL from a discussion.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/59075)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @HonoreDB, @miretskiy, and @shermanCRL)

___
*[pkg/ccl/changefeedccl/avro.go, line 316 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/59075#-MR7H7yoLmiBHiPyfafx-r1-316:-MS3yoQv6VwArrFK5NSh:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/97a3702a69f627fa9942bf20a5070569c3420229/pkg/ccl/changefeedccl/avro.go#L316)):*
<details><summary><i>Previously, HonoreDB (Aaron Zinger) wrote…</i></summary><blockquote>

`WithPrecision` (and the column definition) should be guaranteeing that doesn't happen. Added a return value check just in case. Thanks for reviewing!
</blockquote></details>

Done.
___
*[pkg/ccl/changefeedccl/avro.go, line 315 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/59075#-MS3JPcEA7OW_mCVIAV6:-MS3zOLT-bNP-y-cTmT3:b-vizshx) ([raw file](https://github.com/cockroachdb/cockroach/blob/6041ecb0cd19b44cebe3ed85f075614b8df4583d/pkg/ccl/changefeedccl/avro.go#L315)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

Curious: Why are we checking for negative exponent?
</blockquote></details>

In order to honor a column width of greater than 0, you need digits after the decimal point, and the only way to get those is with a negative exponent. For example if you need a width of two, you need 600 to be rendered as 600.00, so it needs to be 60000e-2 rather than 6e+2.
___
*[pkg/ccl/changefeedccl/avro_test.go, line 488 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/59075#-MS057DF8Ce0UYJRLybS:-MS3yupq0NxDX4rTNg9V:b-l33wpr) ([raw file](https://github.com/cockroachdb/cockroach/blob/6041ecb0cd19b44cebe3ed85f075614b8df4583d/pkg/ccl/changefeedccl/avro_test.go#L488)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

isn't it more common to have truncs test cases defined outside of the t.Run...
```
truncs := ...
for i, test := range truncs{
   t.Run(fmt.Sprintf("lossless-%d", i), func(....))
}
```
</blockquote></details>

Maybe in general, but I'm just copying the style in this file, e.g. https://github.com/cockroachdb/cockroach/blob/6041ecb0cd19b44cebe3ed85f075614b8df4583d/pkg/ccl/changefeedccl/avro_test.go#L348-L349

**Comment by HonoreDB** [comment]
___
*[pkg/ccl/changefeedccl/avro_test.go, line 485 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/59075#-MS05Var2ynF_4cmTO9q:-MS4dILAE1ZF44usojh2:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/6041ecb0cd19b44cebe3ed85f075614b8df4583d/pkg/ccl/changefeedccl/avro_test.go#L485)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

perhaps fe more test cases? maybe w/ negative exponent?
</blockquote></details>

Done.

**Review by miretskiy — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/59075)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @HonoreDB and @shermanCRL)

___
*[pkg/ccl/changefeedccl/avro.go, line 315 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/59075#-MS3JPcEA7OW_mCVIAV6:-MS508M69HuuLFvlD-mN:b-n57vcd) ([raw file](https://github.com/cockroachdb/cockroach/blob/6041ecb0cd19b44cebe3ed85f075614b8df4583d/pkg/ccl/changefeedccl/avro.go#L315)):*
<details><summary><i>Previously, HonoreDB (Aaron Zinger) wrote…</i></summary><blockquote>

In order to honor a column width of greater than 0, you need digits after the decimal point, and the only way to get those is with a negative exponent. For example if you need a width of two, you need 600 to be rendered as 600.00, so it needs to be 60000e-2 rather than 6e+2.
</blockquote></details>

Argh... Why, oh why did we choose to use width instead of scale? 

Can the dec.Exponent be negative?

The confusing part about this if statement (and the comment) has to do with the fact that we have a datum (which is an arbitrary precision decimal), and avro -- which may or may not have same scale/precision...

**Comment by HonoreDB** [comment]
___
*[pkg/ccl/changefeedccl/avro.go, line 315 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/59075#-MS3JPcEA7OW_mCVIAV6:-MS8cJIj7Fs7jNDdT4jC:bjmy4k8) ([raw file](https://github.com/cockroachdb/cockroach/blob/6041ecb0cd19b44cebe3ed85f075614b8df4583d/pkg/ccl/changefeedccl/avro.go#L315)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

Argh... Why, oh why did we choose to use width instead of scale? 

Can the dec.Exponent be negative?

The confusing part about this if statement (and the comment) has to do with the fact that we have a datum (which is an arbitrary precision decimal), and avro -- which may or may not have same scale/precision...


</blockquote></details>

Yeah, I don't know why that discrepancy since it's our decimal library.

In a bug-free world, the Avro datatype has been mapped directly from the column datatype, and the datum being encoded comes from that column, so the scale, precision, width, whatever should all be identical. That means that dec.Exponent should always be negative, and in fact equal to negative the column's width, as that's the only way to encode a fixed-width decimal. 600 should have been encoded as a decimal with coefficient (600 * 10^width) and exponent `-width`. And this in fact usually happens, just not when the upstream bug occurs.

**Comment by HonoreDB** [comment]
See also https://github.com/cockroachdb/cockroach/issues/59489

**Review by miretskiy — APPROVED** [review]
> Reviewed 1 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/59075)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @miretskiy and @shermanCRL)

**Comment by HonoreDB** [comment]
bors r=[miretskiy]

**Comment by ajstorm** [comment]
Bors run got messed up by a bad merge of #59407.  Resubmitting on your behalf.

bors r=[miretskiy]
