### PR TITLE
changefeedccl: disable experimental sink for TestChangefeedBackfillCheckpoint

### LINKED ISSUE #159640: ccl/changefeedccl: TestChangefeedBackfillCheckpoint failed
ccl/changefeedccl.TestChangefeedBackfillCheckpoint [failed](https://mesolite.cluster.engflow.com/invocations/default/a0de4f0e-960c-4426-bb73-748b91f8a108?testReportRun=1&testReportShard=7&testReportAttempt=1#targets-Ly9wa2cvY2NsL2NoYW5nZWZlZWRjY2w6Y2hhbmdlZmVlZGNjbF90ZXN0) on release-26.1 @ [590b5b95ded9f09f1c370bfb0b0a7226ce5c1f14](https://github.com/cockroachdb/cockroach/commits/590b5b95ded9f09f1c370bfb0b0a7226ce5c1f14):

```
        	            	  |   foo: [959]->{"after": {"a": 959, "b": "d"}}
        	            	  |   foo: [960]->{"after": {"a": 960}}
        	            	  |   foo: [961]->{"after": {"a": 961, "b": "d"}}
        	            	  |   foo: [962]->{"after": {"a": 962}}
        	            	  |   foo: [963]->{"after": {"a": 963}}
        	            	  |   foo: [964]->{"after": {"a": 964}}
        	            	  |   foo: [965]->{"after": {"a": 965}}
        	            	  |   foo: [966]->{"after": {"a": 966, "b": "d"}}
        	            	  |   foo: [967]->{"after": {"a": 967}}
        	            	  |   foo: [968]->{"after": {"a": 968}}
        	            	  |   foo: [969]->{"after": {"a": 969, "b": "d"}}
        	            	  |   foo: [96]->{"after": {"a": 96, "b": "d"}}
        	            	  |   foo: [96]->{"after": {"a": 96}}
        	            	  |   foo: [970]->{"after": {"a": 970, "b": "d"}}
        	            	  |   foo: [971]->{"after": {"a": 971}}
        	            	  |   foo: [972]->{"after": {"a": 972}}
        	            	  |   foo: [973]->{"after": {"a": 973}}
        	            	  |   foo: [974]->{"after": {"a": 974, "b": "d"}}
        	            	  |   foo: [975]->{"after": {"a": 975}}
        	            	  |   foo: [976]->{"after": {"a": 976, "b": "d"}}
        	            	  |   foo: [977]->{"after": {"a": 977}}
        	            	  |   foo: [978]->{"after": {"a": 978}}
        	            	  |   foo: [979]->{"after": {"a": 979}}
        	            	  |   foo: [97]->{"after": {"a": 97}}
        	            	  |   foo: [980]->{"after": {"a": 980}}
        	            	  |   foo: [981]->{"after": {"a": 981}}
        	            	  |   foo: [982]->{"after": {"a": 982, "b": "d"}}
        	            	  |   foo: [983]->{"after": {"a": 983}}
        	            	  |   foo: [984]->{"after": {"a": 984}}
        	            	  |   foo: [985]->{"after": {"a": 985, "b": "d"}}
        	            	  |   foo: [986]->{"after": {"a": 986, "b": "d"}}
        	            	  |   foo: [987]->{"after": {"a": 987}}
        	            	  |   foo: [988]->{"after": {"a": 988}}
        	            	  |   foo: [989]->{"after": {"a": 989, "b": "d"}}
        	            	  |   foo: [98]->{"after": {"a": 98, "b": "d"}}
        	            	  |   foo: [990]->{"after": {"a": 990, "b": "d"}}
        	            	  |   foo: [991]->{"after": {"a": 991}}
        	            	  |   foo: [992]->{"after": {"a": 992}}
        	            	  |   foo: [993]->{"after": {"a": 993, "b": "d"}}
        	            	  |   foo: [994]->{"after": {"a": 994}}
        	            	  |   foo: [995]->{"after": {"a": 995}}
        	            	  |   foo: [996]->{"after": {"a": 996, "b": "d"}}
        	            	  |   foo: [997]->{"after": {"a": 997, "b": "d"}}
        	            	  |   foo: [998]->{"after": {"a": 998, "b": "d"}}
        	            	  |   foo: [999]->{"after": {"a": 999}}
        	            	  |   foo: [99]->{"after": {"a": 99}}
        	            	  |   foo: [9]->{"after": {"a": 9, "b": "d"}}
        	            	Error types: (1) *withstack.withStack (2) *errutil.leafError
        	Test:       	TestChangefeedBackfillCheckpoint/enterprise/limit=100_B
--- FAIL: TestChangefeedBackfillCheckpoint/enterprise/limit=100_B (10.87s)
```

Parameters:
 - <code>attempt=1</code>
 - <code>run=1</code>
 - <code>shard=7</code>
<details><summary>Help</summary>
<p>

See also: [How To Investigate a Go Test Failure \(internal\)](https://cockroachlabs.atlassian.net/l/c/HgfXfJgM)
</p>
</details>
/cc @cockroachdb/cdc
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*TestChangefeedBackfillCheckpoint.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/bazci/githubpost/issues)

</sub>

Jira issue: CRDB-57963

### PR DESCRIPTION
**Pull request by KeithCh**
Omitting experimental sink type for TestChangefeedBackfillCheckpoint 
since it is flaky and not officially supported. 

Fixes: #159640
Release Note: none

### CODE REVIEW

**Review by log-head — APPROVED** [review]
lgtm

File: pkg/ccl/changefeedccl/changefeed_test.go [hunk 1]
```diff
@@ -9541,9 +9541,10 @@ WITH resolved='100ms', min_checkpoint_frequency='1ns'`)
 	}
 
 	// TODO(ssd): Tenant testing disabled because of use of DB()
+	// TODO(#159640): Add experimental sink type back after fixing the flakiness.
```
Comment (andyyang890) [inline pkg/ccl/changefeedccl/changefeed_test.go:9544]: Could you either file a new issue to track re-enabling it or add the `skipped-test` and `X-noreuse` labels to the test failure issue?

**Review by andyyang890 — APPROVED** [review]

**Comment by KeithCh** [comment]
bors r=andyyang890,log-head

**Comment by KeithCh** [comment]
bors r=andyyang890,log-head

File: pkg/ccl/changefeedccl/changefeed_test.go (hunk 1 above)
Comment (andyyang890) [reply pkg/ccl/changefeedccl/changefeed_test.go:9544]: Mentioning this for next time, but please keep `skipped-test` issues open (i.e. don't close when you merge the skip) so we have a tracking issue
