### PR TITLE
sql: fix pg_type_is_visible and ::regtype cast to handle UDTs

### LINKED ISSUE #60008: sql: pg_type_is_visible does not handle user-defined types
The following should return `true`, but it returns `null`. 

```
root@:26257/defaultdb> create type mood as enum('Sad', 'Okk', 'Happy');
CREATE TYPE

root@:26257/defaultdb>  select pg_type_is_visible(t.oid) from pg_type t where t.typname = 'mood';
  pg_type_is_visible
----------------------
         NULL    
```

the `pg_type_is_visible` only checks for the hardcoded list of builtin types.

### LINKED ISSUE #61216: sql: ::regtype casts don't work for user defined types
Currently, trying to cast from a type id to a type name via `::regtype` does not work if the type is user-defined.

Repro:

```
demo@127.0.0.1:26257/defaultdb> create type t as enum('a', 'b');
CREATE TYPE

Time: 6ms total (execution 6ms / network 0ms)

demo@127.0.0.1:26257/defaultdb> select oid::regtype from pg_type where typname = 't';
   oid
----------
  100052
(1 row)

Time: 5ms total (execution 4ms / network 0ms)

demo@127.0.0.1:26257/defaultdb>
```

This should return `t`, not `100052`.

### PR DESCRIPTION
**Pull request by rafiss**
fixes https://github.com/cockroachdb/cockroach/issues/61216
fixes https://github.com/cockroachdb/cockroach/issues/60008

The 1st commit is a simple refactor.

Release note (bug fix): Previously, casting an OID to a regtype did not
work for user-defined types. This is now fixed.

Release note (bug fix): Previously, the pg_type_is_visible builtin
function did not correctly handle user-defined types. This is fixed now.

### CODE REVIEW

File: pkg/sql/logictest/testdata/logic_test/pg_builtins [hunk 1]
```diff
@@ -127,3 +133,54 @@ query B
...
+
+query B
+SELECT pg_table_is_visible(NULL)
+----
+NULL
+
+query B
+SELECT pg_type_is_visible(t.oid)
+FROM pg_type t
+WHERE t.typname = 'int8'
```
Comment (otan) [inline pkg/sql/logictest/testdata/logic_test/pg_builtins:145]: maybe:
```
query B
SELECT t.typname pg_type_is_visible(t.oid)
FROM pg_type t
WHERE t.typname IN ( 'int8', '_date', ...)
```

File: pkg/sql/resolver.go [hunk 2]
```diff
@@ -251,6 +251,36 @@ func (p *planner) IsTableVisible(
...
 
+// IsTypeVisible is part of the tree.EvalDatabase interface.
+func (p *planner) IsTypeVisible(
+	ctx context.Context, curDB string, searchPath sessiondata.SearchPath, typeID oid.Oid,
+) (isVisible bool, exists bool, err error) {
+	// Check builtin types first. They are always globally visible.
+	if _, ok := types.OidToType[typeID]; ok {
+		return true, true, nil
+	}
+	// TODO(ajwerner): look at this error and only no-op if it is
```
Comment (otan) [inline pkg/sql/resolver.go:262]: any reason we can't do this now

Comment (rafiss) [reply pkg/sql/resolver.go:262]: doesn't seem there's a reason we can't do it now -- i meant to ask @ajwerner about this comment (which was just added recently). it does look like there's a few more errors than just `ErrDescriptorNotFound` that we need to check for

File: pkg/sql/logictest/testdata/logic_test/pg_builtins (hunk 1 above)
Comment (rafiss) [reply pkg/sql/logictest/testdata/logic_test/pg_builtins:145]: fixd

File: pkg/sql/resolver.go (hunk 2 above)
Comment (otan) [reply pkg/sql/resolver.go:262]: i guess my concern is if it fails due to some transient error it will return False instead of error. arguably this is bad...

Comment (ajwerner) [reply pkg/sql/resolver.go:262]: Right, also, if it is a transaction restart I think it could expose some other anomalies. 

FWIW cleaning up the errors here and probably making these methods return clear booleans and deal with flags properly to declare desired behavior is a major roadmap item for schema this release. 

This code is actually a nightmare right now. I'm trying to untangle all of the errors you can get and it's making my angry. I'm 75% sure that the condition at the moment here is:

```
errors.Is(err, catalog.ErrDescriptorNotFound) || errors.Is(err, catalog.ErrDescriptorDropped) || pgcode.GetPGCode(err) == pgcode.UndefinedObject
```

Sorry :sweat:

Comment (rafiss) [reply pkg/sql/resolver.go:262]: thank you for that list and the roadmap item!

**Review by otan — APPROVED** [review]

**Review by ajwerner — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/62181)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @otan, @pbardea, and @rafiss)

___
*[pkg/sql/resolver.go, line 262 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/62181#-MW1XR-8JmDkYcqnCi0_-r2-262:-MW5qE3kBqh_iT-K0Sap:bb6w9fb) ([raw file](https://github.com/cockroachdb/cockroach/blob/cada0f1cf83ee5c114775a76d699f0e2eb7b896a/pkg/sql/resolver.go#L262)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

thank you for that list and the roadmap item!
</blockquote></details>

Gah 
___
*[pkg/sql/resolver.go, line 220 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/62181#-MW5r8vp8AwQ3O_YQbwy:-MW5r8vp8AwQ3O_YQbwz:b-joxko) ([raw file](https://github.com/cockroachdb/cockroach/blob/c3c2ab8ad9d765e0ea845f903642855562ed4e42/pkg/sql/resolver.go#L220)):*
> ```Go
> 		if errors.Is(err, catalog.ErrDescriptorNotFound) ||
> 			errors.Is(err, catalog.ErrDescriptorDropped) ||
> 			pgerror.GetPGCode(err) == pgcode.UndefinedObject {
> ```

This one needs `pgcode.UndefinedTable` :tada:

**Comment by rafiss** [comment]
ty for the tip!

bors r=otan,ajwerner
