### PR TITLE
privilege: don't include NOSQLLOGIN in ALL check

### LINKED ISSUE #101292: GRANT SYSTEM ALL removes login privilege from role
**Describe the problem**

The `GRANT SYSTEM ALL` statement removes login permission from a role.

**To Reproduce**

To reproduce

1. Create a user
2. Verify that the user can log in
3. Grant `SYSTEM ALL` privileges to the user
4. Verify that the user can no longer log in

If possible, provide steps to reproduce the behavior:

```
▶ cockroach start-single-node --insecure --background
*
* WARNING: ALL SECURITY CONTROLS HAVE BEEN DISABLED!
* 
* This mode is intended for non-production testing only.
* 
* In this mode:
* - Your cluster is open to any client that can access any of your IP addresses.
* - Intruders with access to your machine or network can observe client-server traffic.
* - Intruders can log in without password and read or write any data in the cluster.
* - Intruders can consume all your server's resources and cause unavailability.
*
*
* INFO: To start a secure server without mandating TLS for clients,
* consider --accept-sql-without-tls instead. For other options, see:
* 
* - https://go.crdb.dev/issue-v/53404/v22.2
* - https://www.cockroachlabs.com/docs/v22.2/secure-a-cluster.html
*
*
* WARNING: Running a server without --sql-addr, with a combined RPC/SQL listener, is deprecated.
* This feature will be removed in the next version of CockroachDB.
*
*
* WARNING: neither --listen-addr nor --advertise-addr was specified.
* The server will advertise "crlMBP-NRWLD7WPC6MTc1.local" to other nodes, is this routable?
* 
* Consider using:
* - for local-only servers:  --listen-addr=localhost:36257 --sql-addr=localhost:26257
* - for multi-node clusters: --listen-addr=:36257 --sql-addr=:26257 --advertise-addr=<host/IP addr>
* 
*

▶ cockroach sql --insecure -e "show users";
  username | options | member_of
-----------+---------+------------
  admin    |         | {}
  root     |         | {admin}
(2 rows)


Time: 20ms


▶ cockroach sql --insecure -e "create user abc";
CREATE ROLE


Time: 114ms


▶ cockroach sql --insecure --user abc -e "show databases";
  database_name | owner | primary_region | secondary_region | regions | survival_goal
----------------+-------+----------------+------------------+---------+----------------
  defaultdb     | root  | NULL           | NULL             | {}      | NULL
  postgres      | root  | NULL           | NULL             | {}      | NULL
(2 rows)


Time: 2ms


▶ cockroach sql --insecure -e "grant system all to abc";  
GRANT


Time: 88ms


▶ cockroach sql --insecure --user abc -e "show databases";
ERROR: abc does not have login privilege
SQLSTATE: 28000
Failed running "sql"
```

**Expected behavior**

The user should not lose the login privilege when they are granted all system privileges.

**Environment:**
 - CockroachDB version: 22.2.7
 - Server OS: reproduced on Linux and MacOS
 - Client app: `cockroach sql`

Jira issue: CRDB-26895

Epic CRDB-27601

### PR DESCRIPTION
**Pull request by rafiss**
fixes https://github.com/cockroachdb/cockroach/issues/101292

Release note (bug fix): GRANT SYSTEM ALL ... no longer causes the grantee to be unable to login. This was due to a UX oversight/bug where ALL would include the NOSQLLOGIN system privilege. Since NOSQLLOGIN is the only "negative" privilege, it is now excluded from the ALL shorthand, and must be granted explicitly in order to restrict logins.

### CODE REVIEW

File: pkg/sql/catalog/catpb/privilege.go [hunk 1]
```diff
@@ -513,7 +513,10 @@ func (p PrivilegeDescriptor) CheckPrivilege(user username.SQLUsername, priv priv
 		return user.IsNodeUser()
 	}
 
-	if privilege.ALL.IsSetIn(userPriv.Privileges) {
+	if privilege.ALL.IsSetIn(userPriv.Privileges) && priv != privilege.NOSQLLOGIN {
```
Comment (ecwall) [inline pkg/sql/catalog/catpb/privilege.go:516]: Is there a reason why we have a "negative" privilege? It should probably be reversed to be positive to avoid requiring special casing like this since I think it makes the code hard to reason about.

Comment (rafiss) [reply pkg/sql/catalog/catpb/privilege.go:516]: probably the reason is that unlike other privileges, we want people to be able to log in by default, and storing and managing a SQLLOGIN privilege for every user would have its own set of complexities that would make the code hard to reason about.

our team wasn't actually the one who added this privilege, so I don't know the specific reason.

but regardless, it would be a very expensive project for us to remove the old privilege and migrate to a new inverse one. and even apart from engineering effort, it would be a disruptive change for operators of CRDB. I don't think the amount of effort of that project is worth it compared to adding a special case to this privilege check.

Comment (ecwall) [reply pkg/sql/catalog/catpb/privilege.go:516]: Ok I approved this since it looks like it addresses the issue we have currently, but I think we need a better long term fix in order to prevent this from causing future issues.

**Review by ecwall — APPROVED** [review]

File: pkg/sql/catalog/catpb/privilege.go (hunk 1 above)
Comment (rafiss) [reply pkg/sql/catalog/catpb/privilege.go:516]: in a followup PR i will make a way to make privileges be marked as negative, so it is easy to handle them all in the same way. but i don't want to backport that, since it will lead to more merge conflicts.

**Comment by rafiss** [comment]
tftr

bors r+
