### PR TITLE
cli: check cluster setting before crashing in log stall

### LINKED ISSUE #124474: roachtest: failover/non-system/pause failed
roachtest.failover/non-system/pause [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyAzureBazel/15340216?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyAzureBazel/15340216?buildTab=artifacts#/failover/non-system/pause) on master @ [d146ecff6f687e438706cf63591cafca60cc116d](https://github.com/cockroachdb/cockroach/commits/d146ecff6f687e438706cf63591cafca60cc116d):

```
(failover.go:1775).sleepFor: sleep failed: context canceled
(monitor.go:154).Wait: monitor failure: monitor user task failed: t.Fatal() was called
test artifacts and logs in: /artifacts/failover/non-system/pause/run_1
```

Parameters:
 - <code>ROACHTEST_arch=amd64</code>
 - <code>ROACHTEST_cloud=azure</code>
 - <code>ROACHTEST_coverageBuild=false</code>
 - <code>ROACHTEST_cpu=2</code>
 - <code>ROACHTEST_encrypted=false</code>
 - <code>ROACHTEST_fs=ext4</code>
 - <code>ROACHTEST_localSSD=true</code>
 - <code>ROACHTEST_metamorphicBuild=false</code>
 - <code>ROACHTEST_ssd=0</code>
<details><summary>Help</summary>
<p>

See: [roachtest README](https://github.com/cockroachdb/cockroach/blob/master/pkg/cmd/roachtest/README.md)

See: [How To Investigate \(internal\)](https://cockroachlabs.atlassian.net/l/c/SSSBr8c7)

_Grafana is not yet available for azure clusters_</p>
</details>
<details><summary>Same failure on other branches</summary>
<p>

- #118422 roachtest: failover/non-system/pause failed [A-testing C-bug C-test-failure O-roachtest O-robot P-3 T-kv branch-release-23.2.0-rc no-test-failure-activity]
</p>
</details>
/cc @cockroachdb/kv-triage
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*failover/non-system/pause.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/bazci/githubpost/issues)
</sub>

Jira issue: CRDB-38919

### PR DESCRIPTION
**Pull request by itsbilal**
Previously, we'd unconditionally crash the process if the logger stalled, even if the cluster setting for not crashing the cockroach process on disk stalls was set. This change has the file logger respect that cluster setting,
storage.max_sync_duration.fatal.enabled, as well.

Fixes #124474.

Epic: none

Release note: None

### CODE REVIEW

**Review by RaduBerinde — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/125703#-:-O-NDF6p8tc1ExGxsUsR:bnfp4nl)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @andrewbaptist, @herkolategan, @itsbilal, @nameisbhaskar, @sumeerbhola, and @xinhaoz)

___
*[`pkg/util/log/file.go` line 264 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/125703#-O-ND7iN0_c89vo8GG2g:-O-ND7iN0_c89vo8GG2h:b-v5468x) ([raw file](https://github.com/cockroachdb/cockroach/blob/00c42bf585ab7897ef8682f90eb68947b4e8ed5f/pkg/util/log/file.go#L264)):*
> ```Go
> 		// OPS and disk slowness detection here. (See the implementation
> 		// of logfDepth for details.)
> 		sev := severity.FATAL
> ```

[superdupernit] I'd reverse the default so `sev = FATAL` is in the same block with` MakeProcessUnavailable()`

**Review by itsbilal — COMMENTED** [review]
TFTR!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/125703#-:-O-O_FOw7Xc-4cpU4wAG:b-814g8k)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @andrewbaptist, @herkolategan, @nameisbhaskar, @sumeerbhola, and @xinhaoz)

___
*[`pkg/util/log/file.go` line 264 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/125703#-O-ND7iN0_c89vo8GG2g:-O-O_Dxx6IisSgiMHWWT:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/00c42bf585ab7897ef8682f90eb68947b4e8ed5f/pkg/util/log/file.go#L264)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

[superdupernit] I'd reverse the default so `sev = FATAL` is in the same block with` MakeProcessUnavailable()`
</blockquote></details>

Done.

File: pkg/util/log/file.go [hunk 1]
```diff
@@ -259,14 +261,18 @@ func (l *fileSink) flushAndMaybeSyncLocked(doSync bool) {
...
 		// of logfDepth for details.)
+		sev := severity.ERROR
+		// We default to assuming a fatal on log stall.
+		if l.fatalOnLogStall == nil || l.fatalOnLogStall() {
+			sev = severity.FATAL
+			// The write stall may prevent the process from exiting. If the process
+			// won't exit, we can at least terminate all our RPC connections first.
+			//
+			// See pkg/cli.runStart for where this function is hooked up.
+			MakeProcessUnavailable()
```
Comment (srosenberg) [inline pkg/util/log/file.go:272]: Note that this doesn't cause an exit, which is what happened in the referenced issue. There is a separate timer in `logfDepthInternal` which invokes `exitFunc`.

Comment (itsbilal) [reply pkg/util/log/file.go:272]: Yep I'm aware. The severity being Fatal triggers that exit function, which is what I'm mostly changing here.

Comment (srosenberg) [reply pkg/util/log/file.go:272]: It's not immediately clear why we have `ExitTimeoutOnFatalLog` and `maxSyncDuration`, which behave rather differently.

Comment (srosenberg) [reply pkg/util/log/file.go:272]: > The severity being Fatal triggers that exit function, which is what I'm mostly changing here.

Oh, I see, but that still leaves calls like `l.Error` exposed to the same exit. Don't we want to plug that entirely via the same cluster setting?

Comment (itsbilal) [reply pkg/util/log/file.go:272]: @srosenberg Good question and thanks for asking it as it sent me on a detour and shored up my understanding of the current logging code.

1) I don't think we want to plug all fatal logs with the cluster setting; other reasons to fatally crash the process (eg. inconsistent stores or ranges) should continue to do their thing. We just want to avoid crashing just because of disk stalls being seen by the logger.

2) It looks like `ExitTimeoutOnFatalLog` is the timeout on any fatal log entry taking too long to write to any sink (fluent, etc), while `maxSyncDuration` is for any log entry (not necessarily a fatal one) writing to a _file_ sync. Given that definition, and given point 3 below, I think having the cluster setting just neutralize the latter config parameter is correct. I'll fix the maxSyncDuration comment though to clarify this.

3) There's _another_ place in `loggerT.outputLogEntry` that actually calls the exit function, assuming the Shoutf succeeds in writing the fatal message to the ops log within the ExitTimeoutOnFatalLog. So it's still correct to just change severity to Error for disk stalls and bypass all the crashing logic.

Comment (srosenberg) [reply pkg/util/log/file.go:272]: @itsbilal Thanks for taking a closer look and summarizing the findings! I do agree that this PR addresses the immediate issue, namely `exit 7` resulting from an expired (`maxSyncDuration`) timer in `fileSink.flushAndMaybeSyncLocked`,  which invokes `outputLogEntry` with `severity.FATAL`; reducing the severity effectively disables the exit.

I do want to mention one _pathological_ case which still remains at large. Owing to [1], it's theoretically possible for `write` to stall _before_ `flush`. (Recall that `outputLogEntry` invokes `sink.output`, which does `write`, followed by `flush`.) Now, the `flushDaemon` is scheduled to periodically invoke `flush`. Imagine the following scenario. A `write` has been issued (which may or may not end up rotating logs), subsequently the runtime stops the world long enough such that a _potential_ disk stall goes undetected; i.e., `maxSyncDuration` timer never expires yet we spend 10 seconds waiting for `write` and another 5 for STW.

[1] https://github.com/cockroachdb/cockroach/issues/56893

**Comment by srosenberg** [comment]
> This change has the logger respect that cluster setting, storage.max_sync_duration.fatal.enabled, as well.

Nit: could we please make the commit msg. more precise, e.g., "This change has the _file_ logger respect...".

**Review by srosenberg — APPROVED** [review]
Thanks and LGTM!

File: pkg/util/log/file.go (hunk 1 above)
Comment (itsbilal) [reply pkg/util/log/file.go:272]: @srosenberg thanks for highlighting that! We probably should reopen #56893 and try to address that on its own. It's just a lower priority issue seeing as Pebble's disk stall detection (ie. the stuff configured in `pkg/storage/pebble.go` through `WithDiskHealthChecks`) has become far more robust over the years since that issue was filed, in detecting stalls in the data directories/volumes themselves.

I remember questioning if we need to even crash if the logger is stalling but the stores aren't, so by that lower prioritization it's less of a concern if some stalls are going undetected by the logger as long as Pebble is robust at catching stalls where they can really hose the cluster.

**Comment by itsbilal** [comment]
TFTRs!

> Nit: could we please make the commit msg. more precise, e.g., "This change has the file logger respect...".

Done.

**Comment by itsbilal** [comment]
bors r=RaduBerinde

**Comment by itsbilal** [comment]
blathers backport 24.1
blathers backport 23.2
