### PR TITLE
sql: avoid stampede on synthetic privilege cache in vtable population

### LINKED ISSUE #108781: A SQL query used for introspecting a large database schema got 200x slower
**Describe the problem**

Prisma has an introspecting feature that looks at a database and creates a Prisma schema out of it, it is called `prisma db pull`
One of the introspection SQL query is now very slow, 500s+ for `discourse` which has 140 tables (see link in To Reproduce).

I do not know exactly at the moment for which version it started, my best guest is v23.1.x 

**To Reproduce**

What did you do? Describe in your own words.

If possible, provide steps to reproduce the behavior:

1. Set up a serverless CockroachDB cluster in the Cloud UI
2. Use https://github.com/prisma/database-schema-examples/blob/main/postgres/discourse/schema.sql to create a database
3. Run the following SQL query on that database
```sql
SELECT
  oid.namespace,
  info.table_name,
  info.column_name,
  format_type(att.atttypid, att.atttypmod) AS formatted_type,
  info.numeric_precision,
  info.numeric_scale,
  info.numeric_precision_radix,
  info.datetime_precision,
  info.data_type,
  info.udt_schema AS type_schema_name,
  info.udt_name AS full_data_type,
  pg_get_expr(attdef.adbin, attdef.adrelid) AS column_default,
  info.is_nullable,
  info.is_identity,
  info.character_maximum_length,
  description.description
FROM
  information_schema.columns AS info
  JOIN pg_attribute AS att ON att.attname = info.column_name
  JOIN (
      SELECT
        pg_class.oid, relname, pg_namespace.nspname AS namespace
      FROM
        pg_class
        JOIN pg_namespace ON
            pg_namespace.oid = pg_class.relnamespace AND pg_namespace.nspname = ANY (ARRAY['public'])
    )
      AS oid ON
      oid.oid = att.attrelid AND relname = info.table_name AND namespace = info.table_schema
  LEFT JOIN pg_attrdef AS attdef ON
      attdef.adrelid = att.attrelid AND attdef.adnum = att.attnum AND table_schema = namespace
  LEFT JOIN pg_description AS description ON
      description.objoid = att.attrelid AND description.objsubid = ordinal_position
WHERE
  table_schema = ANY (ARRAY['public']) AND info.is_hidden = 'NO'
ORDER BY
  namespace, table_name, ordinal_position
```
5. Wait for 500~ seconds for it to complete
6. Note that removing this part of the query `table_schema = ANY (ARRAY['public']) AND` and running it again makes it succeed in 2s.

**Expected behavior**
It should be (a lot?) faster to execute.

**Additional data / screenshots**
Diagnostic archive from the Cloud UI, from https://cockroachlabs.cloud/cluster/6fcad804-83d9-4f9b-b80b-b5b7b789a93c/statement/true/11919201472824938241?appNames=%28unset%29&cluster-type=serverless&tab=overview :
[stmt-bundle-890298509353746433.zip](https://github.com/cockroachdb/cockroach/files/12346113/stmt-bundle-890298509353746433.zip)

Screenshot 2023-08-15 at 18 02 16
Screenshot 2023-08-15 at 18 02 30

Screenshot 2023-08-15 at 18 22 05
Screenshot 2023-08-15 at 18 21 28

**Environment:**
 - CockroachDB version: v23.1.8 - cockroachlabs.cloud / Serverless
 - Server OS: Linux - Ubuntu - GitHub Actions  
 - Client app: Prisma Client

**Additional context**
The CockroachDB server is https://cockroachlabs.cloud/cluster/6fcad804-83d9-4f9b-b80b-b5b7b789a93c/overview?cluster-type=serverless
It's only used for tests, feel free to take a look, there is no data, only schemas we gathered for running tests.

Shared in our shared [Slack channel](https://prisma-company.slack.com/archives/C01CSQXTNJ3/p1691768436839419)

Jira issue: CRDB-30636

Epic CRDB-27601

### PR DESCRIPTION
**Pull request by rafiss**
Accessing the synthetic privilege cache requires fetching the descriptor
for system.system_privileges, even in the case of a cache hit. This is
ok for the basic case of fetching a single privilege descriptor for one
virtual table, which is done when executing something like `SELECT *
FROM a_virtual_table`.

However, for some virtual tables, like pg_class, populating the table
itself requires fetching a privilege descriptor for each row in the result.
If a query does a lot of joins, that can mean hundreds of thousands of
calls to the synthetic privilege cache and the descriptor catalog. This
leads to a lot of thrashing in the descriptor catalog, since the catalog
is also being upserted into at the same time, since populating virtual
tables also requires fetching many descriptors.

This can be avoided by some small code changes that short-circuit and
avoid hitting the synthetic privilege cache entirely.

Before:
```
BenchmarkORMQueries/prisma_column_descriptions-10         	       1	6824922583 ns/op
```
After:
```
BenchmarkORMQueries/prisma_column_descriptions-10         	       1	2601088125 ns/op
```

fixes https://github.com/cockroachdb/cockroach/issues/108781

Release note (performance improvement): Queries that access the
pg_catalog and information_schema that perform introspection on other
tables in those schemas are now signicantly faster.

Release note (sql change): Introspection queries will now show the
internal `node` user as the owner of tables in pg_catalog and
information_schema. Previously the owner was shown as `admin`, but that
was inaccurate since users with the `admin` role could not modify these
tables in any way.

### CODE REVIEW

File: pkg/bench/rttanalysis/orm_queries_bench_test.go [hunk 1]
```diff
@@ -476,5 +456,56 @@ FROM
...
+      description.objoid = att.attrelid AND description.objsubid = ordinal_position
+WHERE
+  table_schema = ANY (ARRAY['public']) AND info.is_hidden = 'NO'
+ORDER BY
+  namespace, table_name, ordinal_position`,
+		},
 	})
 }
+
+func buildNTables(n int) string {
```
Comment (ecwall) [inline pkg/bench/rttanalysis/orm_queries_bench_test.go:505]: Nice

File: pkg/sql/information_schema.go [hunk 2]
```diff
@@ -2931,26 +2931,28 @@ func userCanSeeDescriptor(
...
-	if parentDBDesc != nil {
-		if !canSeeDescriptor {
-			if ok, err := p.HasPrivilege(ctx, parentDBDesc, privilege.CONNECT, p.User()); err != nil {
-				return false, err
-			} else {
-				canSeeDescriptor = ok
-			}
-		}
+	} else if ok {
+		return true, nil
```
Comment (ecwall) [inline pkg/sql/information_schema.go:2953]: Can be simplified to `return ok, nil`.

**Review by ecwall — APPROVED** [review]

File: pkg/sql/information_schema.go (hunk 2 above)
Comment (rafiss) [reply pkg/sql/information_schema.go:2953]: i like doing it this way since if the code is copy-pasted, or if something else is added after this line, it's less likely for something to be forgotten.

**Review by rafiss — COMMENTED** [review]
tftr

bors r+
