### PR TITLE
randgen: avoid overflow in computed column expressions

### LINKED ISSUE #125747: roachtest: schemachange/mixed-versions failed
roachtest.schemachange/mixed-versions [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/15681888?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/15681888?buildTab=artifacts#/schemachange/mixed-versions) on master @ [3aa5bdf40527e2f60b179094403b4302a1c2cbe1](https://github.com/cockroachdb/cockroach/commits/3aa5bdf40527e2f60b179094403b4302a1c2cbe1):

```
(mixedversion.go:612).Run: mixed-version test failure while running step 7 (run "run schemachange workload and validation in mixed version"): full command output in run_063057.453204075_n4_COCKROACHRANDOMSEED6.log: COMMAND_PROBLEM: exit status 1
test artifacts and logs in: /artifacts/schemachange/mixed-versions/run_1
```

Parameters:
 - <code>ROACHTEST_arch=amd64</code>
 - <code>ROACHTEST_cloud=gce</code>
 - <code>ROACHTEST_coverageBuild=false</code>
 - <code>ROACHTEST_cpu=4</code>
 - <code>ROACHTEST_encrypted=false</code>
 - <code>ROACHTEST_metamorphicBuild=false</code>
 - <code>ROACHTEST_ssd=0</code>
<details><summary>Help</summary>
<p>

See: [roachtest README](https://github.com/cockroachdb/cockroach/blob/master/pkg/cmd/roachtest/README.md)

See: [How To Investigate \(internal\)](https://cockroachlabs.atlassian.net/l/c/SSSBr8c7)

See: [Grafana](https://go.crdb.dev/roachtest-grafana/teamcity-15681888/schemachange-mixed-versions/1718519392312/1718519610668)

</p>
</details>
<details><summary>Same failure on other branches</summary>
<p>

- #125617 roachtest: schemachange/mixed-versions failed [C-test-failure O-roachtest O-robot T-sql-foundations branch-release-24.1 release-blocker]
- #125379 roachtest: schemachange/mixed-versions failed [attempting to append refresh spans after the tracked timestamp has moved forward] [C-test-failure O-roachtest O-robot T-sql-queries branch-release-23.2]
- #124722 roachtest: schemachange/mixed-versions failed [debug doctor validation: existing descriptors that still need to be dropped] [C-test-failure O-roachtest O-robot P-2 T-sql-foundations branch-release-23.1.22-rc]
</p>
</details>
/cc @cockroachdb/sql-foundations
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*schemachange/mixed-versions.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/bazci/githubpost/issues)
</sub>

Jira issue: CRDB-39588

### PR DESCRIPTION
**Pull request by rafiss**
The computed column definition could lead to overflow errors since it adds a number that is randomly chosen and could be very large. Using absolute value instead avoids this.

fixes https://github.com/cockroachdb/cockroach/issues/125747
Release note: None

### CODE REVIEW

File: pkg/sql/randgen/expr.go [hunk 1]
```diff
@@ -216,8 +216,9 @@ func randExpr(
 	switch xTyp.Family() {
 	case types.IntFamily, types.FloatFamily, types.DecimalFamily:
 		typ = xTyp
+		// Avoid using an arithmetic operation that could overflow.
 		expr = &tree.BinaryExpr{
-			Operator: treebin.MakeBinaryOperator(treebin.Plus),
+			Operator: treebin.MakeBinaryOperator(treebin.Div),
 			Left:     tree.NewUnresolvedName(string(x.Name)),
 			Right:    RandDatum(rng, xTyp, nullOk),
```
Comment (annrpom) [inline pkg/sql/randgen/expr.go:223]: could we have a chance for division by zero here?

Comment (rafiss) [reply pkg/sql/randgen/expr.go:223]: good call. it is annoyingly complex to check if the random value is 0, so i changed this to be an absolute value expression.

**Review by annrpom — APPROVED** [review]
seems reasonable to me!

nit: could we update the following comment https://github.com/cockroachdb/cockroach/blob/8ae68eb258b24fc0e523831f13b26f00138301b8/pkg/sql/randgen/expr.go#L201

**Comment by rafiss** [comment]
fixed the comment; thanks for catching that. tftr!

bors r+
