### PR TITLE
roachtest: run post test health checks on system

### LINKED ISSUE #140774: roachtest: decommission/mixed-versions failed
roachtest.decommission/mixed-versions [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/18769736?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/18769736?buildTab=artifacts#/decommission/mixed-versions) on release-25.1.0-rc @ [e32dca763783603b41fc08dbc3cf40f2cc0c1ec8](https://github.com/cockroachdb/cockroach/commits/e32dca763783603b41fc08dbc3cf40f2cc0c1ec8):

```
(mixedversion.go:804).Run: mixed-version test failure while running step 40 (run "test decommission"): full command output in run_063957.844480889_n2_v2430cockroach-node-.log: COMMAND_PROBLEM: exit status 1
test artifacts and logs in: /artifacts/decommission/mixed-versions/run_1
```

Parameters:
 - <code>arch=amd64</code>
 - <code>cloud=gce</code>
 - <code>coverageBuild=false</code>
 - <code>cpu=4</code>
 - <code>encrypted=false</code>
 - <code>mvtDeploymentMode=shared-process</code>
 - <code>mvtVersions=v24.1.6 → v24.2.2 → v24.3.0 → release-25.1.0-rc</code>
 - <code>runtimeAssertionsBuild=false</code>
 - <code>ssd=0</code>
<details><summary>Help</summary>
<p>

See: [roachtest README](https://github.com/cockroachdb/cockroach/blob/master/pkg/cmd/roachtest/README.md)

See: [How To Investigate \(internal\)](https://cockroachlabs.atlassian.net/l/c/SSSBr8c7)

See: [Grafana](https://go.crdb.dev/roachtest-grafana/teamcity-18769736/decommission-mixed-versions/1738996292738/1738996938048)

</p>
</details>
<details><summary>Same failure on other branches</summary>
<p>

- #139413 roachtest: decommission/mixed-versions failed [B-runtime-assertions-enabled C-bug C-test-failure O-roachtest O-robot P-2 T-kv branch-master]
- #139411 roachtest: decommission/mixed-versions failed [A-kv-server C-bug C-test-failure O-roachtest O-robot T-kv X-duplicate branch-release-25.1]
- #139393 roachtest: decommission/mixed-versions failed [B-runtime-assertions-enabled C-test-failure O-roachtest O-robot T-kv X-duplicate branch-release-24.3]
</p>
</details>
/cc @cockroachdb/kv-triage
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*decommission/mixed-versions.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/bazci/githubpost/issues)

</sub>

Jira issue: CRDB-47357

### PR DESCRIPTION
**Pull request by DarrylWong**
This changes the post test assertions to always run the health checks on the system tenant (KV pod). Previously it would run these health checks on the default virtual cluster, which may be a SQL pod. We run consistency checks on the system tenant so we care about the liveness of the system tenant here.

Fixes: https://github.com/cockroachdb/cockroach/issues/140774

-----

After this change, running `decomission/mixed-versions`:

```
test-post-assertions: 2025/02/13 16:23:02 cluster.go:2577: running cmd `./cockroach auth-session lo...` on nodes [:1]; details in run_162302.356113000_n1_cockroach-authsessio.log
test-post-assertions: 2025/02/13 16:23:17 test_runner.go:1502: n1: https://127.0.0.1:29001/health?ready=1 status=503 body={
  "error": "node is shutting down",
  "code": 14,
  "message": "node is shutting down",
  "details": [
  ]
}
test-post-assertions: 2025/02/13 16:23:17 test_runner.go:1509: n2: https://127.0.0.1:29005/health?ready=1 status=200 ok
test-post-assertions: 2025/02/13 16:23:17 test_runner.go:1509: n3: https://127.0.0.1:29003/health?ready=1 status=200 ok
test-post-assertions: 2025/02/13 16:23:17 test_runner.go:1509: n4: https://127.0.0.1:29007/health?ready=1 status=200 ok
test-post-assertions: 2025/02/13 16:23:17 test_runner.go:1525: running validation checks on node 2 (<10m)
```

We can see it correctly identifies node 1 as shutting down and runs the validation checks on node 2. It also only attempts one `auth-session login`.

### CODE REVIEW

**Review by srosenberg — APPROVED** [review]

File: pkg/cmd/roachtest/roachtestutil/httpclient.go [hunk 1]
```diff
@@ -134,6 +134,9 @@ func (r *RoachtestHTTPClient) addCookies(ctx context.Context, cookieUrl string)
 	if !r.cluster.IsSecure() {
 		return nil
 	}
+
+	r.mu.Lock()
+	defer r.mu.Unlock()
```
Comment (srosenberg) [inline pkg/cmd/roachtest/roachtestutil/httpclient.go:139]: Nice find! Because of this data race, there was a high bias to return `n1`; now, all other nodes are equally likely to be picked (in `postTestAssertions`).

**Comment by DarrylWong** [comment]
TFTR!

bors r=srosenberg

**Comment by DarrylWong** [comment]
unrelated flake

bors retry
