### PR TITLE
changefeedccl: fix test failure

### LINKED ISSUE #141463: ccl/changefeedccl: TestAlterChangefeedAddTargetsDuringBackfill failed
ccl/changefeedccl.TestAlterChangefeedAddTargetsDuringBackfill [failed](https://mesolite.cluster.engflow.com/invocations/default/5bcf2ed8-b4e8-444a-b5bc-3bba90df2b00?testReportRun=1&testReportShard=8&testReportAttempt=1#targets-Ly9wa2cvY2NsL2NoYW5nZWZlZWRjY2w6Y2hhbmdlZmVlZGNjbF90ZXN0) on master @ [557a7c4008e689744952ece73adf3fa98a6a25ef](https://github.com/cockroachdb/cockroach/commits/557a7c4008e689744952ece73adf3fa98a6a25ef):

```
    alter_changefeed_test.go:1472: resolved span: &jobspb.ResolvedSpan{Span:roachpb.Span{Key:/Tenant/10/Table/107/1, EndKey:/Tenant/10/Table/107/2}, Timestamp:hlc.Timestamp{WallTime:1739496081043322852, Logical:0}, BoundaryType:0}
    alter_changefeed_test.go:1472: resolved span: &jobspb.ResolvedSpan{Span:roachpb.Span{Key:/Tenant/10/Table/106/1, EndKey:/Tenant/10/Table/106/1/165/0}, Timestamp:hlc.Timestamp{WallTime:1739496081044180533, Logical:0}, BoundaryType:0}
    alter_changefeed_test.go:1472: resolved span: &jobspb.ResolvedSpan{Span:roachpb.Span{Key:/Tenant/10/Table/106/1/165/0, EndKey:/Tenant/10/Table/106/2}, Timestamp:hlc.Timestamp{WallTime:1739496081044180533, Logical:0}, BoundaryType:0}
    alter_changefeed_test.go:1472: resolved span: &jobspb.ResolvedSpan{Span:roachpb.Span{Key:/Tenant/10/Table/107/1, EndKey:/Tenant/10/Table/107/2}, Timestamp:hlc.Timestamp{WallTime:1739496081044180533, Logical:0}, BoundaryType:0}
    alter_changefeed_test.go:1472: resolved span: &jobspb.ResolvedSpan{Span:roachpb.Span{Key:/Tenant/10/Table/106/1, EndKey:/Tenant/10/Table/106/1/165/0}, Timestamp:hlc.Timestamp{WallTime:1739496081775447043, Logical:0}, BoundaryType:0}
    alter_changefeed_test.go:1472: resolved span: &jobspb.ResolvedSpan{Span:roachpb.Span{Key:/Tenant/10/Table/106/1/165/0, EndKey:/Tenant/10/Table/106/2}, Timestamp:hlc.Timestamp{WallTime:1739496081775447043, Logical:0}, BoundaryType:0}
    alter_changefeed_test.go:1472: resolved span: &jobspb.ResolvedSpan{Span:roachpb.Span{Key:/Tenant/10/Table/107/1, EndKey:/Tenant/10/Table/107/2}, Timestamp:hlc.Timestamp{WallTime:1739496081775447043, Logical:0}, BoundaryType:0}
    alter_changefeed_test.go:1472: resolved span: &jobspb.ResolvedSpan{Span:roachpb.Span{Key:/Tenant/10/Table/106/1, EndKey:/Tenant/10/Table/106/1/165/0}, Timestamp:hlc.Timestamp{WallTime:1739496081780054409, Logical:0}, BoundaryType:0}
    alter_changefeed_test.go:1472: resolved span: &jobspb.ResolvedSpan{Span:roachpb.Span{Key:/Tenant/10/Table/106/1/165/0, EndKey:/Tenant/10/Table/106/2}, Timestamp:hlc.Timestamp{WallTime:1739496081780054409, Logical:0}, BoundaryType:0}
    alter_changefeed_test.go:1472: resolved span: &jobspb.ResolvedSpan{Span:roachpb.Span{Key:/Tenant/10/Table/107/1, EndKey:/Tenant/10/Table/107/2}, Timestamp:hlc.Timestamp{WallTime:1739496081780054409, Logical:0}, BoundaryType:0}
    alter_changefeed_test.go:1472: resolved span: &jobspb.ResolvedSpan{Span:roachpb.Span{Key:/Tenant/10/Table/106/1, EndKey:/Tenant/10/Table/106/1/165/0}, Timestamp:hlc.Timestamp{WallTime:1739496081780577400, Logical:0}, BoundaryType:0}
    alter_changefeed_test.go:1472: resolved span: &jobspb.ResolvedSpan{Span:roachpb.Span{Key:/Tenant/10/Table/106/1/165/0, EndKey:/Tenant/10/Table/106/2}, Timestamp:hlc.Timestamp{WallTime:1739496081780577400, Logical:0}, BoundaryType:0}
    alter_changefeed_test.go:1472: resolved span: &jobspb.ResolvedSpan{Span:roachpb.Span{Key:/Tenant/10/Table/107/1, EndKey:/Tenant/10/Table/107/2}, Timestamp:hlc.Timestamp{WallTime:1739496081780577400, Logical:0}, BoundaryType:0}
    alter_changefeed_test.go:1472: resolved span: &jobspb.ResolvedSpan{Span:roachpb.Span{Key:/Tenant/10/Table/106/1, EndKey:/Tenant/10/Table/106/1/165/0}, Timestamp:hlc.Timestamp{WallTime:1739496081781361210, Logical:0}, BoundaryType:0}
    alter_changefeed_test.go:1472: resolved span: &jobspb.ResolvedSpan{Span:roachpb.Span{Key:/Tenant/10/Table/106/1/165/0, EndKey:/Tenant/10/Table/106/2}, Timestamp:hlc.Timestamp{WallTime:1739496081781361210, Logical:0}, BoundaryType:0}
    alter_changefeed_test.go:1472: resolved span: &jobspb.ResolvedSpan{Span:roachpb.Span{Key:/Tenant/10/Table/107/1, EndKey:/Tenant/10/Table/107/2}, Timestamp:hlc.Timestamp{WallTime:1739496081781361210, Logical:0}, BoundaryType:0}
    alter_changefeed_test.go:1472: resolved span: &jobspb.ResolvedSpan{Span:roachpb.Span{Key:/Tenant/10/Table/106/1, EndKey:/Tenant/10/Table/106/1/165/0}, Timestamp:hlc.Timestamp{WallTime:1739496081782005841, Logical:0}, BoundaryType:0}
    alter_changefeed_test.go:1472: resolved span: &jobspb.ResolvedSpan{Span:roachpb.Span{Key:/Tenant/10/Table/106/1/165/0, EndKey:/Tenant/10/Table/106/2}, Timestamp:hlc.Timestamp{WallTime:1739496081782005841, Logical:0}, BoundaryType:0}
    alter_changefeed_test.go:1472: resolved span: &jobspb.ResolvedSpan{Span:roachpb.Span{Key:/Tenant/10/Table/107/1, EndKey:/Tenant/10/Table/107/2}, Timestamp:hlc.Timestamp{WallTime:1739496081782005841, Logical:0}, BoundaryType:0}
    alter_changefeed_test.go:1472: resolved span: &jobspb.ResolvedSpan{Span:roachpb.Span{Key:/Tenant/10/Table/106/1, EndKey:/Tenant/10/Table/106/1/165/0}, Timestamp:hlc.Timestamp{WallTime:1739496081782725032, Logical:0}, BoundaryType:0}
    alter_changefeed_test.go:1472: resolved span: &jobspb.ResolvedSpan{Span:roachpb.Span{Key:/Tenant/10/Table/106/1/165/0, EndKey:/Tenant/10/Table/106/2}, Timestamp:hlc.Timestamp{WallTime:1739496081782725032, Logical:0}, BoundaryType:0}
    alter_changefeed_test.go:1472: resolved span: &jobspb.ResolvedSpan{Span:roachpb.Span{Key:/Tenant/10/Table/107/1, EndKey:/Tenant/10/Table/107/2}, Timestamp:hlc.Timestamp{WallTime:1739496081782725032, Logical:0}, BoundaryType:0}
    alter_changefeed_test.go:1472: resolved span: &jobspb.ResolvedSpan{Span:roachpb.Span{Key:/Tenant/10/Table/106/1, EndKey:/Tenant/10/Table/106/1/165/0}, Timestamp:hlc.Timestamp{WallTime:1739496081784040424, Logical:0}, BoundaryType:0}
    alter_changefeed_test.go:1472: resolved span: &jobspb.ResolvedSpan{Span:roachpb.Span{Key:/Tenant/10/Table/106/1/165/0, EndKey:/Tenant/10/Table/106/2}, Timestamp:hlc.Timestamp{WallTime:1739496081784040424, Logical:0}, BoundaryType:0}
    alter_changefeed_test.go:1472: resolved span: &jobspb.ResolvedSpan{Span:roachpb.Span{Key:/Tenant/10/Table/107/1, EndKey:/Tenant/10/Table/107/2}, Timestamp:hlc.Timestamp{WallTime:1739496081784040424, Logical:0}, BoundaryType:0}
    alter_changefeed_test.go:1472: resolved span: &jobspb.ResolvedSpan{Span:roachpb.Span{Key:/Tenant/10/Table/106/1, EndKey:/Tenant/10/Table/106/1/165/0}, Timestamp:hlc.Timestamp{WallTime:1739496081785838626, Logical:0}, BoundaryType:0}
    alter_changefeed_test.go:1472: resolved span: &jobspb.ResolvedSpan{Span:roachpb.Span{Key:/Tenant/10/Table/106/1/165/0, EndKey:/Tenant/10/Table/106/2}, Timestamp:hlc.Timestamp{WallTime:1739496081785838626, Logical:0}, BoundaryType:0}
    alter_changefeed_test.go:1472: resolved span: &jobspb.ResolvedSpan{Span:roachpb.Span{Key:/Tenant/10/Table/107/1, EndKey:/Tenant/10/Table/107/2}, Timestamp:hlc.Timestamp{WallTime:1739496081785838626, Logical:0}, BoundaryType:0}
    alter_changefeed_test.go:1472: resolved span: &jobspb.ResolvedSpan{Span:roachpb.Span{Key:/Tenant/10/Table/106/1, EndKey:/Tenant/10/Table/106/1/165/0}, Timestamp:hlc.Timestamp{WallTime:1739496082871376880, Logical:0}, BoundaryType:0}
    alter_changefeed_test.go:1472: resolved span: &jobspb.ResolvedSpan{Span:roachpb.Span{Key:/Tenant/10/Table/106/1/165/0, EndKey:/Tenant/10/Table/106/2}, Timestamp:hlc.Timestamp{WallTime:1739496082871376880, Logical:0}, BoundaryType:0}
    alter_changefeed_test.go:1472: resolved span: &jobspb.ResolvedSpan{Span:roachpb.Span{Key:/Tenant/10/Table/107/1, EndKey:/Tenant/10/Table/107/2}, Timestamp:hlc.Timestamp{WallTime:1739496082871376880, Logical:0}, BoundaryType:0}
    alter_changefeed_test.go:1472: resolved span: &jobspb.ResolvedSpan{Span:roachpb.Span{Key:/Tenant/10/Table/106/1, EndKey:/Tenant/10/Table/106/1/165/0}, Timestamp:hlc.Timestamp{WallTime:1739496082873653473, Logical:0}, BoundaryType:0}
    alter_changefeed_test.go:1472: resolved span: &jobspb.ResolvedSpan{Span:roachpb.Span{Key:/Tenant/10/Table/106/1/165/0, EndKey:/Tenant/10/Table/106/2}, Timestamp:hlc.Timestamp{WallTime:1739496082873653473, Logical:0}, BoundaryType:0}
    alter_changefeed_test.go:1472: resolved span: &jobspb.ResolvedSpan{Span:roachpb.Span{Key:/Tenant/10/Table/107/1, EndKey:/Tenant/10/Table/107/2}, Timestamp:hlc.Timestamp{WallTime:1739496082873653473, Logical:0}, BoundaryType:0}
    alter_changefeed_test.go:1472: resolved span: &jobspb.ResolvedSpan{Span:roachpb.Span{Key:/Tenant/10/Table/106/1/165/0, EndKey:/Tenant/10/Table/106/2}, Timestamp:hlc.Timestamp{WallTime:0, Logical:0}, BoundaryType:0}
    alter_changefeed_test.go:1472: resolved span: &jobspb.ResolvedSpan{Span:roachpb.Span{Key:/Tenant/10/Table/106/1/165/0, EndKey:/Tenant/10/Table/106/2}, Timestamp:hlc.Timestamp{WallTime:1739496082891789977, Logical:0}, BoundaryType:0}
    alter_changefeed_test.go:1472: resolved span: &jobspb.ResolvedSpan{Span:roachpb.Span{Key:/Tenant/10/Table/106/1, EndKey:/Tenant/10/Table/106/1/165/0}, Timestamp:hlc.Timestamp{WallTime:1739496082891789977, Logical:0}, BoundaryType:0}
    alter_changefeed_test.go:1472: resolved span: &jobspb.ResolvedSpan{Span:roachpb.Span{Key:/Tenant/10/Table/107/1, EndKey:/Tenant/10/Table/107/2}, Timestamp:hlc.Timestamp{WallTime:0, Logical:0}, BoundaryType:0}
    alter_changefeed_test.go:1472: resolved span: &jobspb.ResolvedSpan{Span:roachpb.Span{Key:/Tenant/10/Table/107/1, EndKey:/Tenant/10/Table/107/2}, Timestamp:hlc.Timestamp{WallTime:1739496082891789977, Logical:0}, BoundaryType:0}
    alter_changefeed_test.go:1472: resolved span: &jobspb.ResolvedSpan{Span:roachpb.Span{Key:/Tenant/10/Table/106/1, EndKey:/Tenant/10/Table/106/1/165/0}, Timestamp:hlc.Timestamp{WallTime:1739496083907301750, Logical:0}, BoundaryType:0}
    alter_changefeed_test.go:1472: resolved span: &jobspb.ResolvedSpan{Span:roachpb.Span{Key:/Tenant/10/Table/106/1/165/0, EndKey:/Tenant/10/Table/106/2}, Timestamp:hlc.Timestamp{WallTime:1739496083907301750, Logical:0}, BoundaryType:0}
    helpers_test.go:749: waiting for highwater
    helpers_test.go:752: read highwater: 1739496081.775447043,0
    alter_changefeed_test.go:1493: 
        	Error Trace:	pkg/ccl/changefeedccl/alter_changefeed_test.go:1493
        	            				pkg/ccl/changefeedccl/helpers_test.go:1202
        	Error:      	Should be false
        	Test:       	TestAlterChangefeedAddTargetsDuringBackfill/kafka
        	Messages:   	span should not have been resolved: /Tenant/10/Table/106/1{-/165/0}
    --- FAIL: TestAlterChangefeedAddTargetsDuringBackfill/kafka (10.43s)
```

Parameters:
 - <code>attempt=1</code>
 - <code>run=1</code>
 - <code>shard=8</code>
<details><summary>Help</summary>
<p>

See also: [How To Investigate a Go Test Failure \(internal\)](https://cockroachlabs.atlassian.net/l/c/HgfXfJgM)
</p>
</details>
/cc @cockroachdb/cdc
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*TestAlterChangefeedAddTargetsDuringBackfill.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/bazci/githubpost/issues)

</sub>

Jira issue: CRDB-47832

### PR DESCRIPTION
**Pull request by asg0451**
TestAlterChangefeedAddTargetsDuringBackfill was
failing due to the interaction of the llrb span
merging issue (#141405) and the new checkpoint
system. Force the test to run with the btree
frontier.

Fixes: #141463

Release note: None

### CODE REVIEW

File: pkg/ccl/changefeedccl/alter_changefeed_test.go [hunk 1]
```diff
@@ -1472,7 +1476,7 @@ func TestAlterChangefeedAddTargetsDuringBackfill(t *testing.T) {
 		var resolvedFoo []roachpb.Span
 		knobs.FilterSpanWithMutation = func(r *jobspb.ResolvedSpan) (bool, error) {
 			t.Logf("resolved span: %#v", r)
-			if !r.Span.Equal(fooTableSpan) {
+			if !r.Span.Equal(fooTableSpan) { // ignore spans that are the whole table, as that indicates normal non-backfill operation
```
Comment (andyyang890) [inline pkg/ccl/changefeedccl/alter_changefeed_test.go:1479]: nit: comment should go on its own line

**Review by andyyang890 — APPROVED** [review]
Thanks!

**Comment by asg0451** [comment]
bors r=andyyang890

**Comment by asg0451** [comment]
bors r=andyyang890
