### PR TITLE
sql: fix SHOW CREATE output for partitioned and interleaved partial indexes

### LINKED ISSUE #60019: sql: incorrect formatting of partitioned partial indexes in SHOW CREATE
The output of a partitioned partial index in `SHOW CREATE` displays the partial index predicate`WHERE` clause before the `PARTITION` clause. This format is incompatible with the parser which expects the `WHERE` clause to come after the `PARTITION` clause.

```
statement ok
CREATE TABLE t (
  pk INT PRIMARY KEY,
  a INT,
  b INT,
  INDEX (a, b) PARTITION BY LIST (a) (
    PARTITION c_implicit VALUES IN (3)
  ) WHERE b > 0,
  FAMILY (pk, a, b)
)

query T
SELECT create_statement FROM [SHOW CREATE TABLE t]
----
CREATE TABLE public.t (
  pk INT8 NOT NULL,
  a INT8 NULL,
  b INT8 NULL,
  CONSTRAINT "primary" PRIMARY KEY (pk ASC),
  INDEX t_a_b_idx (a ASC, b ASC) WHERE b > 0:::INT8 PARTITION BY LIST (a) (
    PARTITION c_implicit VALUES IN ((3))
  ),
  FAMILY fam_0_pk_a_b (pk, a, b)
) LOCALITY REGIONAL BY TABLE IN PRIMARY REGION
-- Warning: Partitioned table with no zone configurations.
```

### LINKED ISSUE #60701: sql: SHOW CREATE displays interleaved partial indexes incorrectly
The `WHERE` clause should come after the `INTERLEAVE` clause, to match the accepted syntax.

```
root@127.0.0.1:50155/defaultdb> create table a (a int primary key);
CREATE TABLE

Time: 3ms total (execution 3ms / network 0ms)

root@127.0.0.1:50155/defaultdb> create table b (b int primary key, a int references a (a));
CREATE TABLE

Time: 34ms total (execution 6ms / network 28ms)

root@127.0.0.1:50155/defaultdb> create index i on b (a) interleave in parent a (a) where b > 0;
CREATE INDEX

Time: 69ms total (execution 13ms / network 56ms)

root@127.0.0.1:50155/defaultdb> show create table b;
  table_name |                             create_statement
-------------+----------------------------------------------------------------------------
  b          | CREATE TABLE public.b (
             |     b INT8 NOT NULL,
             |     a INT8 NULL,
             |     CONSTRAINT "primary" PRIMARY KEY (b ASC),
             |     CONSTRAINT fk_a_ref_a FOREIGN KEY (a) REFERENCES public.a(a),
             |     INDEX i (a ASC) WHERE b > 0:::INT8 INTERLEAVE IN PARENT public.a (a),
             |     FAMILY "primary" (b, a)
             | )
(1 row)

Time: 8ms total (execution 8ms / network 0ms)
```

### PR DESCRIPTION
**Pull request by mgartner**
#### sql: fix SHOW CREATE output for partitioned partial indexes

The accepted syntax for creating partitioned partial indexes requires
the `PARTITION BY` clause to precede the `WHERE` predicate clause.
Previously, `SHOW CREATE` formatted indexes with the `WHERE` clause
preceding the `PARTITION BY` clause. This commit fixes `SHOW CREATE` to
match the parser's accepted ordering of clauses.

Fixes #60019

Release note (bug fix): The `SHOW CREATE` output of a partitioned
partial index now lists the `PARTITION BY` and `WHERE` clauses in the
order accepted by the parser.

Release justification: Fixes a bug that makes `SHOW CREATE` not
round-trippable.

#### sql: fix SHOW CREATE output for partial interleaved indexes

The accepted syntax for creating partial interleaved indexes requires
the `INTERLEAVE` clause to precede the `WHERE` clause. This commit fixes
the output of partial interleaved indexes in `SHOW CREATE` to match this
syntax.

Fixes #60701

Release note (bug fix): The `SHOW CREATE` output of a partial
interleaved index now lists the `INTERLEAVED` and `WHERE` clauses in the
order accepted by the parser.

Release justification: Fixes a bug that makes `SHOW CREATE` not
round-trippable.

### CODE REVIEW

File: pkg/ccl/logictestccl/testdata/logic_test/partitioning_index [hunk 1]
```diff
@@ -184,3 +184,31 @@ inverted  CREATE TABLE public.inverted (
           FAMILY "primary" (a, b, j)
 )
 -- Warning: Partitioned table with no zone configurations.
+
+# Regression test for #60019. The index predicate should be formatted after the
+# PARTITION BY clause to match the syntax that is accepted.
```
Comment (otan) [inline pkg/ccl/logictestccl/testdata/logic_test/partitioning_index:189]: you can add a CREATE TABLE round-trip style test after https://github.com/cockroachdb/cockroach/pull/60513 merges :P oh well

File: pkg/sql/crdb_internal.go [hunk 2]
```diff
@@ -2002,7 +2002,7 @@ func showCreateIndexWithInterleave(
 	semaCtx *tree.SemaContext,
 ) error {
 	f.WriteString("CREATE ")
-	idxStr, err := catformat.IndexForDisplay(ctx, table, &tableName, idx, semaCtx)
+	idxStr, err := catformat.IndexForDisplay(ctx, table, &tableName, idx, "" /* partition */, semaCtx)
```
Comment (otan) [inline pkg/sql/crdb_internal.go:2005]: is it possible to partition an interleave?

**Review by otan — APPROVED** [review]

File: pkg/sql/crdb_internal.go (hunk 2 above)
Comment (mgartner) [reply pkg/sql/crdb_internal.go:2005]: heh, no: https://github.com/cockroachdb/cockroach/issues/60699

but also the interleave ordering in SHOW CREATE is incorrect: https://github.com/cockroachdb/cockroach/issues/60701. I'll add another commit to this PR to fix that.

**Comment by mgartner** [comment]
@otan This is ready for another look.

**Comment by mgartner** [comment]
@otan friendly ping

File: pkg/ccl/logictestccl/testdata/logic_test/partitioning_index (hunk 1 above)
Comment (otan) [reply pkg/ccl/logictestccl/testdata/logic_test/partitioning_index:189]: (this is now possible!)

**Review by otan — APPROVED** [review]
LGTM!

if you hit the "re-request review" button next time (the grey thing below) these float onto my github review TODO list and makes it easier to not miss!

image

File: pkg/ccl/logictestccl/testdata/logic_test/partitioning_index (hunk 1 above)
Comment (mgartner) [reply pkg/ccl/logictestccl/testdata/logic_test/partitioning_index:189]: I added one.

**Review by otan — APPROVED** [review]
