### PR TITLE
backupccl: ingest range on node running scatter if scatter fails

### LINKED ISSUE #81247: backupccl: if scatter sends range to 'node 0', route range to scattering node's stream instead of default stream
When AdminScatterRequest fails to find a node to scatter a range to, the split scatter processor will route the range to the fake "node 0". Right now, ranges sent to 'node 0' are sent to the [default stream](https://github.com/cockroachdb/cockroach/blob/master/pkg/ccl/backupccl/restore_processor_planning.go#L129) for ingestion, i.e. whatever the first node is in [this slice](https://github.com/cockroachdb/cockroach/blob/master/pkg/ccl/backupccl/restore_processor_planning.go#L158).  

If AdminScatterRequest consistently fails to find a node to scatter to, such as when the replication queue is wedged on several nodes, then the default stream node becomes responsible for ingesting way too many ranges. Instead, if scatter returns 'node 0', the range should be routed to the node running the split and scatter processor.

### PR DESCRIPTION
**Pull request by msbutler**
Fixes #81247

Release note: none

### CODE REVIEW

File: pkg/ccl/backupccl/split_and_scatter_processor.go [hunk 1]
```diff
@@ -375,6 +372,13 @@ func runSplitAndScatter(
 			if err != nil {
 				return err
 			}
+			if chunkDestination == 0 {
+				// If scatter failed to find a node for range ingestion, route the range
+				// to the node currently running the split and scatter processor.
+				if nodeId, ok := flowCtx.NodeID.OptionalNodeID(); ok {
```
Comment (msbutler) [inline pkg/ccl/backupccl/split_and_scatter_processor.go:378]: @stevendanna could you confirm this is the proper function call, at least in a non multi-tenant world? Here's what i'm trying to do:  If scatter fails, I want the node currently running the split and scatter to also ingest the range. 

I think we need to rewire the split and scatter planning and execution logic for tenants. Processors are assigned to nodes by `sqlInstanceID`. But `chunkDestination`, the object used  to route a range to a node for ingestion, is of type `nodeID`, as inputed from the adminScatter return. In other words, to route ranges for restore ingestion after scatter, we currently assume the list of `sqlInstanceIds` from planning are identical to the nodeID's returned by split and scatter during execution, which is certainly not the case, implying restore for tenants could be significantly slower.

Comment (msbutler) [reply pkg/ccl/backupccl/split_and_scatter_processor.go]: @stevendanna friendly ping here! Perhaps this merits a discussion with the larger group?

Comment (msbutler) [reply pkg/ccl/backupccl/split_and_scatter_processor.go]: filed https://github.com/cockroachdb/cockroach/issues/81989 for further investigation
