### PR TITLE
unsafesql: avoid panicking during query formatting

### LINKED ISSUE #153590: sql: FormatAstAsRedactableString while building trigger expression: runtime error: invalid memory address or nil pointer dereference
pkg/ccl/testccl/workload/schemachange/schemachange_test.TestWorkload [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Ci_TestsAwsLinuxArm64_UnitTests/20474143?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Ci_TestsAwsLinuxArm64_UnitTests/20474143?buildTab=artifacts#/) on master @ [1572ff3199f6c9d1971034a5ee8de6258b741864](https://github.com/cockroachdb/cockroach/commits/1572ff3199f6c9d1971034a5ee8de6258b741864):

```
      "ExplicitSchema": true
     }
    ],
    "result": false
   }
  ],
  "previousStatements": [
   "INSERT INTO public.table_w1_226 (col226_w1_227) VALUES (3220:::OID),(1083:::OID),(3614:::OID)"
  ],
  "usesDeclarativeSchemaChanger": true
 }
}
    schema_change_external_test.go:165: 
        	Error Trace:	pkg/ccl/testccl/workload/schemachange/schema_change_external_test.go:165
        	Error:      	Received unexpected error:
        	            	***UNEXPECTED ERROR; Received an unexpected execution error.: ERROR: internal error: while building trigger expression: runtime error: invalid memory address or nil pointer dereference (SQLSTATE XX000)
        	            	(1) forced error mark
        	            	  | "fatal error when running txn"
        	            	  | github.com/cockroachdb/errors/withstack/*withstack.withStack::
        	            	Wraps: (2)
        	            	Wraps: (3) attached stack trace
        	            	  -- stack trace:
        	            	  | github.com/cockroachdb/cockroach/pkg/workload/schemachange.(*opStmt).executeStmt
        	            	  | 	pkg/workload/schemachange/operation_generator.go:3391
        	            	  | github.com/cockroachdb/cockroach/pkg/workload/schemachange.(*schemaChangeWorker).runInTxn
        	            	  | 	pkg/workload/schemachange/schemachange.go:523
        	            	  | github.com/cockroachdb/cockroach/pkg/workload/schemachange.(*schemaChangeWorker).run
        	            	  | 	pkg/workload/schemachange/schemachange.go:611
        	            	  | pkg/ccl/testccl/workload/schemachange/schemachange_test_test.TestWorkload.TestWorkload.func5.func7
        	            	  | 	pkg/ccl/testccl/workload/schemachange/schema_change_external_test.go:154
        	            	  | golang.org/x/sync/errgroup.(*Group).Go.func1
        	            	  | 	external/org_golang_x_sync/errgroup/errgroup.go:93
        	            	  | runtime.goexit
        	            	  | 	src/runtime/asm_arm64.s:1223
        	            	Wraps: (4) ***UNEXPECTED ERROR; Received an unexpected execution error.
        	            	Wraps: (5) ERROR: internal error: while building trigger expression: runtime error: invalid memory address or nil pointer dereference (SQLSTATE XX000)
        	            	Error types: (1) *markers.withMark (2) *schemachange.ErrorState (3) *withstack.withStack (4) *errutil.withPrefix (5) *pgconn.PgError
        	Test:       	TestWorkload
Schema Workload Stats
Total Schema Statements Executed = 91
Total Schema Statements Succeeded = 91
Total Schema Statement Expected Failures = 0
Total Transactions Committed = 65
Total Transactions Rolled Back = 56
Total Transactions Executed = 121
    schema_change_external_test.go:118: backup, tracing data, and system table dumps in /artifacts/tmp/_tmp/67537770b84c3a4ea177539c1e46bd43/logTestWorkload2916073494
    schema_change_external_test.go:127: running DROP with use_declarative_schema_changer = off
    panic.go:635: -- test log scope end --
test logs left over in: /artifacts/tmp/_tmp/67537770b84c3a4ea177539c1e46bd43/logTestWorkload2916073494
--- FAIL: TestWorkload (62.83s)
```
<details><summary>Help</summary>
<p>

See also: [How To Investigate a Go Test Failure \(internal\)](https://cockroachlabs.atlassian.net/l/c/HgfXfJgM)
</p>
</details>
<details><summary>Same failure on other branches</summary>
<p>

- #153442 pkg/ccl/testccl/workload/schemachange/schemachange_test: TestWorkload failed [C-test-failure O-robot T-sql-foundations branch-release-24.3 release-blocker]
- #153126 pkg/ccl/testccl/workload/schemachange/schemachange_test: TestWorkload failed [column &#34;crdb_internal_column_3_name_placeholder&#34; does not exist] [C-test-failure O-robot P-2 T-sql-foundations branch-release-24.3.20-rc]
</p>
</details>
/cc @cockroachdb/sql-foundations
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*TestWorkload.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/bazci/githubpost/issues)

</sub>

Jira issue: CRDB-54507

### PR DESCRIPTION
**Pull request by angles-n-daemons**
Part of the effort to guard access to the crdb_internal and system namespaces includes auditing override access (and denied access) to these unsafe internals. Included in this audit is the offending query which attempted to pry into these namespaces.

In multiple locations however, this auditing caused the system to panic, for different reasons. In one case, an incorrect number of annotations on the query caused a panic. Another included a plan builder which had no associated statement.

We see the process of going from plan -> query as a difficult one, and thus guard this attempt to audit these accesses in a blanket panic catcher, as it's not common that this will happen, and when it does we don't want the system to wholesale fail the query.

Fixes: #153590 Epic: CRDB-24527

Release note: none

### CODE REVIEW

File: pkg/sql/unsafesql/unsafesql.go [hunk 1]
```diff
@@ -69,3 +70,20 @@ func CheckInternalsAccess(
 	}
 	return sqlerrors.ErrUnsafeTableAccess
 }
+
+// SafeFormatQuery attempts to format the query for logging, but recovers from
+// any panics that may occur during formatting.
+func SafeFormatQuery(
```
Comment (dhartunian) [inline pkg/sql/unsafesql/unsafesql.go:76]: please add a unit test that exercises the panic

Comment (angles-n-daemons) [reply pkg/sql/unsafesql/unsafesql.go:76]: good idea - yeah I'll do so now

File: pkg/sql/unsafesql/unsafesql_test.go [hunk 2]
```diff
@@ -255,3 +257,35 @@ func TestAccessCheckServer(t *testing.T) {
...
+
+// panickingStatement is a mock Statement that panics during formatting
+type panickingStatement struct{}
+
+func (ps panickingStatement) String() string {
+	return "panicking statement"
+}
+
+func (ps panickingStatement) Format(ctx *tree.FmtCtx) {
+	panic("deliberate panic for testing")
```
Comment (angles-n-daemons) [inline pkg/sql/unsafesql/unsafesql_test.go:269]: trying to find an exact statement tree which panics when translating into a query string seems difficult, this is a quick way around it to test the panic catching behavior.

Comment (dhartunian) [reply pkg/sql/unsafesql/unsafesql_test.go:269]: reasonable :)

**Review by dhartunian — APPROVED** [review]
