### PR TITLE
rpc: improve test coverage of initial heartbeat failures

### LINKED ISSUE #19708: util/grpcutil: Can no longer detect unambiguous failures
SHA: https://github.com/cockroachdb/cockroach/commits/98f1623d60254505b65c457728617af5c5fec33b

Parameters:
```
TAGS=
GOFLAGS=
```

Stress build found a failed test: https://teamcity.cockroachdb.com/viewLog.html?buildId=394944&tab=buildLog

```
I171101 07:09:42.489844 41 vendor/google.golang.org/grpc/resolver_conn_wrapper.go:64  dialing to target with scheme: ""
I171101 07:09:42.489870 41 vendor/google.golang.org/grpc/resolver_conn_wrapper.go:70  could not get resolver for scheme: ""
W171101 07:09:42.490535 56 vendor/google.golang.org/grpc/server.go:839  grpc: Server.processUnaryRPC failed to write status: connection error: desc = "transport is closing"
W171101 07:09:42.490640 21 vendor/google.golang.org/grpc/transport/log.go:36  transport: http2Server.HandleStreams failed to read frame: read tcp 127.0.0.1:49561->127.0.0.1:33576: use of closed network connection
W171101 07:09:42.491825 52 vendor/google.golang.org/grpc/clientconn.go:934  grpc: addrConn.resetTransport failed to create client transport: connection error: desc = "transport: Error while dialing dial tcp 127.0.0.1:49561: operation was canceled"; Reconnecting to {127.0.0.1:49561 0  <nil>}
W171101 07:09:42.491862 52 vendor/google.golang.org/grpc/clientconn.go:1028  grpc: addrConn.transportMonitor exits due to: context canceled
	grpc_util_test.go:117: request should not have started, but got rpc error: code = Unavailable desc = transport is closing


ERROR: exit status 1

40000 runs completed, 1 failures, over 4m25s
context canceled
Makefile:276: recipe for target 'stress' failed
make: *** [stress] Error 1
```

### PR DESCRIPTION
**Pull request by erikgrinaker**
This patch improves test coverage for `InitialHeartbeatFailedError` and `grpcutil.RequestDidNotStart()`.

It also removes some stale references about wanting gRPC to return unambiguious errors for certain types of connection failures. `InitialHeartbeatFailedError` has largerly replaced this need.

Resolves #19708.

Epic: none
Release note: None

### CODE REVIEW

File: pkg/util/grpcutil/grpc_util_test.go [hunk 1]
```diff
@@ -153,13 +53,19 @@ func TestRequestDidNotStart_Errors(t *testing.T) {
...
 	}{
-		"breaker":          {errors.Wrapf(circuit.ErrBreakerOpen, "unable to dial n%d", 42), true},
-		"waiting for init": {errors.Wrapf(server.NewWaitingForInitError("foo"), "failed"), true},
-		"plain":            {errors.New("foo"), false},
+		"failed heartbeat":    {&netutil.InitialHeartbeatFailedError{}, true},
+		"waiting for init":    {server.NewWaitingForInitError("foo"), true},
+		"unauthenticated":     {status.Error(codes.Unauthenticated, "unauthenticated"), true},
+		"permission denied":   {status.Error(codes.PermissionDenied, "permission denied"), true},
+		"failed precondition": {status.Error(codes.FailedPrecondition, "failed precondition"), true},
+		"circuit breaker":     {circuit.ErrBreakerOpen, true},
```
Comment (tbg) [inline pkg/util/grpcutil/grpc_util_test.go:61]: this one could be dangerous, right? If you send a write through DistSender, and it actually does stuff on a few ranges, but then hits a _replica_ circuit breaker error somewhere else, DistSender might think "request did not start" but it very much started indeed.
I see that we're only using `RequestDidNotStart` when sending to a single range, so it's probably... truer? But we could also be getting this error from another replica during intent resolution (see your PR from yesterday). I don't see how it can cause problems, exactly, but it seems a little unclean.

**Review by tbg — COMMENTED** [review]
Thanks! Basically good, just FUD about circuit breakers.

File: pkg/util/grpcutil/grpc_util_test.go (hunk 1 above)
Comment (erikgrinaker) [reply pkg/util/grpcutil/grpc_util_test.go:61]: Note that `circuit` here points to the old RPC circuit breaker package (`cockroachdb/circuitbreaker`), not your new circuit breakers.

But considering you recently refactored RPC to use the same circuit breaker infrastructure, I'd say yeah, it's probably worth revisiting this stuff. I think this probably doesn't work anymore at all, because we don't return that circuit breaker error.

Furthermore, the RPC circuit breaker error will be caught by the dial and promoted to an `InitialHeartbeatFailedError`, which is really the error we're interested in. I think we can probably just remove the circuit breaker case here, and it'll be good.

In any case, there are no logic changes in this PR, so it's sort of orthogonal. Do you mind following up on this and making sure there aren't any bad interactions?

Comment (tbg) [reply pkg/util/grpcutil/grpc_util_test.go:61]: Ok, filed an issue.

**Review by tbg — APPROVED** [review]
