### PR TITLE
spanconfig: stop generating split points for views

### LINKED ISSUE #77744: spanconfig: don't generate splits for views
**Describe the problem**

Views use table descriptors, but are not physical tables. They should not have split points. If they did, it would be a regression.

**To Reproduce**

Create a view and wait.
**Expected behavior**
No split.

Jira issue: CRDB-13747

### PR DESCRIPTION
**Pull request by arulajmani**
The range corresponding to a view's descriptor ID contains no data,
and as such, should not be treated as a split point.

Fixes #77744

Release justification: bug fixes and low-risk updates to new functionality
Release note: None

### CODE REVIEW

File: pkg/spanconfig/spanconfigsqltranslator/sqltranslator.go [hunk 1]
```diff
@@ -320,6 +320,14 @@ func (s *SQLTranslator) generateSpanConfigurationsForTable(
 			"expected table descriptor, but got descriptor of type %s", desc.DescriptorType(),
 		)
 	}
+
+	// Views aren't physical tables and the range corresponding to their
+	// descriptor ID doesn't contain any data. As such, we don't create a span
+	// config record (and in-turn a split point) for them.
+	if desc.(catalog.TableDescriptor).IsView() {
```
Comment (ajwerner) [inline pkg/spanconfig/spanconfigsqltranslator/sqltranslator.go:327]: rather than all of this type assertion, how about you just make a variable `table := desc.(catalog.TableDescriptor`?

`IsView` is wrong because it would include materialized views, I do believe. I think you want `IsPhysicalTable`. Can you add a test that materialized views do get split off?

**Review by arulajmani — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/77776)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner)

___
*[pkg/spanconfig/spanconfigsqltranslator/sqltranslator.go, line 327 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/77776#-My8NZh_BHKyetuqxuM3-r1-327:-My97G_GC6A4L-Qid2X9:b-yx91p1) ([raw file](https://github.com/cockroachdb/cockroach/blob/5b76be21857b653423a629f3d88361d88ab6d6cf/pkg/spanconfig/spanconfigsqltranslator/sqltranslator.go#L327)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

rather than all of this type assertion, how about you just make a variable `table := desc.(catalog.TableDescriptor`?

`IsView` is wrong because it would include materialized views, I do believe. I think you want `IsPhysicalTable`. Can you add a test that materialized views do get split off?
</blockquote></details>

Ah, forgot about materialized views. Fixed + added a test.

**Review by ajwerner — APPROVED** [review]
:lgtm:

> Reviewed 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/77776#-:-My97iVc-zXQIAAs2-xf:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @arulajmani)

**Comment by arulajmani** [comment]
TFTR! 

bors r=ajwerner
