### PR TITLE
jobs: hold claim on failed job for one adoption cycle

### LINKED ISSUE #158597: jobs: prevent jobs that failed from being picked up immediately
As a follow up to @msbutler's discoveries in cockroachlabs/support#3466, we should teach the job system to prevent jobs that failed from being picked up immediately. In the current state, the job system does not attempt to uniformly distribute node adoption loops across the adoption interval. As a result of this, nodes can end up all performing an adoption cycle within a short time frame.

For jobs that are fast-failing, this may result in a hot-loop of a node claiming a job, the job failing, the node releasing its lease, and then another node claiming the job again within one adoption interval. To alleviate this, we should prevent failing jobs from being adopted immediately. One way of doing this is to add a sleep before a node releases its claim on a failing job equal to the adoption interval.

Jira issue: CRDB-57409

### PR DESCRIPTION
**Pull request by kev-cao**
This commit teaches the job system to hold the claim on failed jobs for one adoption cycle before releasing the claim. This alleviates hot loops where a fast-failing job can be picked up repeatedly by different nodes within an adoption cycle.

Fixes: #158597

Release note: None

### CODE REVIEW

File: pkg/jobs/adopt.go [hunk 1]
```diff
@@ -426,11 +428,28 @@ func (r *Registry) runJob(
 	// NB: After this point, the job may no longer have the claim
 	// and further updates to the job record from this node may
 	// fail.
```
[the remark this answers is not in the document]
Comment (kev-cao) [reply pkg/jobs/adopt.go]: > if the job succeeded, it no longer has the claim

This is just patently false

File: pkg/jobs/config.go [hunk 2]
```diff
@@ -84,6 +85,20 @@ var (
 		settings.PositiveInt,
 	)
 
+	claimTTLOnFailure = settings.RegisterDurationSetting(
```
Comment (dt) [inline pkg/jobs/config.go]: @msbutler do you think this justifies another cluster setting? could we just say it reused the adoption interval directly?

File: pkg/jobs/adopt.go [hunk 3]
```diff
@@ -426,11 +428,28 @@ func (r *Registry) runJob(
...
-	r.maybeClearLease(job, err)
-	r.maybeDumpTrace(ctx, resumer, job.ID())
+	grp := ctxgroup.WithContext(ctx)
```
Comment (dt) [inline pkg/jobs/adopt.go]: do we need the parallelism / group? can we just dump the trace and then take our tap?

**Review by dt — APPROVED** [review]

File: pkg/jobs/config.go (hunk 2 above)
Comment (kev-cao) [reply pkg/jobs/config.go]: Oh the reason why I ended up doing this is because there was an import test that failed because of the adoption delay. Although in hindsight, instead of adding a whole cluster setting, just adding the override would be sufficient.

File: pkg/jobs/adopt.go (hunk 3 above)
Comment (kev-cao) [reply pkg/jobs/adopt.go]: Yeah it's not 100% necessary, was thinking that dumping a trace might take a bit of time, which would impact how long before the lease is released.

Comment (stevendanna) [reply pkg/jobs/adopt.go]: If that is a big worry, we could calculate a "releaseAt" time before starting the trace, then sleep until that time after.

File: pkg/jobs/adopt.go [hunk 4]
```diff
@@ -426,11 +428,28 @@ func (r *Registry) runJob(
...
+	if err != nil {
+		grp.GoCtx(func(ctx context.Context) error {
+			// We delay clearing the lease to avoid situations where a job fast-fails
+			// and is immediately re-adopted by another node, causing a hot loop of job
+			// status changes. See #158597 for more info.
```
Comment (stevendanna) [inline pkg/jobs/adopt.go]: I think we might also remind the reader that _our_ node that holds the claim won't re-run this job while we are waiting for this interval because the job is not removed from the list of currently running jobs until the enclosing function returns.

**Review by stevendanna — COMMENTED** [review]
Interesting. This `maybeClearLease` function is in the running for the least favourite change I never made to this subsystem 😭 .

File: pkg/jobs/adopt.go (hunk 3 above)
Comment (kev-cao) [reply pkg/jobs/adopt.go]: Not if taking the trace exceeds the adoption interval right?

Comment (msbutler) [reply pkg/jobs/adopt.go]: i'm in david's camp. we want this thing to go to sleep, so a bit more time to gather the trace is no big deal.

Comment (kev-cao) [reply pkg/jobs/adopt.go]: How long does it usually take for a trace to be taken?

**Review by stevendanna — APPROVED** [review]

File: pkg/jobs/adopt.go (hunk 3 above)
Comment (msbutler) [reply pkg/jobs/adopt.go]: less than a second
