### PR TITLE
workload: allow rows=0 for workload

### LINKED ISSUE #160972: roachtest: copy/bank/rows=1000000,nodes=9,txn=false failed
roachtest.copy/bank/rows=1000000,nodes=9,txn=false [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyAzureBazel/20964942?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyAzureBazel/20964942?buildTab=artifacts#/copy/bank/rows=1000000,nodes=9,txn=false) on master @ [279d420e76108f43259b5a5efcfd13a3ddcfc87d](https://github.com/cockroachdb/cockroach/commits/279d420e76108f43259b5a5efcfd13a3ddcfc87d):

Failed with:

```
(cluster.go:2513).Run: full command output in run_072726.048043547_n1_cockroach-workload-i.log: COMMAND_PROBLEM: exit status 1
(monitor.go:267).Wait: monitor failure: monitor user task failed: t.Fatal() was called
test artifacts and logs in: /artifacts/copy/bank/rows=1000000_nodes=9_txn=false/run_1
```
Cluster Node to Ip Mapping:
| Node | Public IP | Private IP |
| --- | --- | --- |
| teamcity-20964942-1768287291-84-n9cpu4-0001 | 20.127.211.213 | 10.1.0.107 |
| teamcity-20964942-1768287291-84-n9cpu4-0002 | 172.206.227.159 | 10.1.0.104 |
| teamcity-20964942-1768287291-84-n9cpu4-0003 | 20.127.212.125 | 10.1.0.123 |
| teamcity-20964942-1768287291-84-n9cpu4-0004 | 57.151.99.91 | 10.1.0.119 |
| teamcity-20964942-1768287291-84-n9cpu4-0005 | 20.55.89.244 | 10.1.0.105 |
| teamcity-20964942-1768287291-84-n9cpu4-0006 | 74.235.123.215 | 10.1.0.125 |
| teamcity-20964942-1768287291-84-n9cpu4-0007 | 172.203.240.201 | 10.1.0.117 |
| teamcity-20964942-1768287291-84-n9cpu4-0008 | 20.55.90.39 | 10.1.0.114 |
| teamcity-20964942-1768287291-84-n9cpu4-0009 | 20.127.185.243 | 10.1.0.122 |

Parameters:
 - <code>arch=amd64</code>
 - <code>cloud=azure</code>
 - <code>coverageBuild=false</code>
 - <code>cpu=4</code>
 - <code>encrypted=false</code>
 - <code>fs=ext4</code>
 - <code>localSSD=true</code>
 - <code>metamorphicLeases=leader</code>
 - <code>runtimeAssertionsBuild=false</code>
 - <code>ssd=0</code>
<details><summary>Help</summary>
<p>

See: [roachtest README](https://github.com/cockroachdb/cockroach/blob/master/pkg/cmd/roachtest/README.md)

See: [How To Investigate \(internal\)](https://cockroachlabs.atlassian.net/l/c/SSSBr8c7)

_Grafana is not yet available for azure clusters_</p>
</details>
/cc @cockroachdb/kv-triage
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*copy/bank/rows=1000000,nodes=9,txn=false.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/bazci/githubpost/issues)

</sub>

Jira issue: CRDB-58637

### LINKED ISSUE #161049: roachtest: copy/bank/rows=100000,nodes=5,txn=true failed
roachtest.copy/bank/rows=100000,nodes=5,txn=true [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/20971544?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/20971544?buildTab=artifacts#/copy/bank/rows=100000,nodes=5,txn=true) on master @ [2eeff2e7ccd8a50ea573e2c7c42a4829cde1e398](https://github.com/cockroachdb/cockroach/commits/2eeff2e7ccd8a50ea573e2c7c42a4829cde1e398):

Failed with:

```
(cluster.go:2513).Run: full command output in run_104539.276798448_n1_cockroach-workload-i.log: COMMAND_PROBLEM: exit status 1
(monitor.go:267).Wait: monitor failure: monitor user task failed: t.Fatal() was called
test artifacts and logs in: /artifacts/copy/bank/rows=100000_nodes=5_txn=true/cpu_arch=arm64/run_1
```
Cluster Node to Ip Mapping:
| Node | Public IP | Private IP |
| --- | --- | --- |
| teamcity-20971544-1768375480-70-n5cpu4-0001 | 34.44.244.155 | 10.128.0.95 |
| teamcity-20971544-1768375480-70-n5cpu4-0002 | 34.57.91.253 | 10.128.0.89 |
| teamcity-20971544-1768375480-70-n5cpu4-0003 | 136.116.249.49 | 10.128.0.14 |
| teamcity-20971544-1768375480-70-n5cpu4-0004 | 136.119.52.205 | 10.128.0.12 |
| teamcity-20971544-1768375480-70-n5cpu4-0005 | 34.68.206.104 | 10.128.0.139 |

Parameters:
 - <code>arch=arm64</code>
 - <code>cloud=gce</code>
 - <code>coverageBuild=false</code>
 - <code>cpu=4</code>
 - <code>encrypted=false</code>
 - <code>fs=ext4</code>
 - <code>localSSD=false</code>
 - <code>metamorphicLeases=default</code>
 - <code>metamorphicWriteBuffering=true</code>
 - <code>runtimeAssertionsBuild=false</code>
 - <code>ssd=0</code>
<details><summary>Help</summary>
<p>

See: [roachtest README](https://github.com/cockroachdb/cockroach/blob/master/pkg/cmd/roachtest/README.md)

See: [How To Investigate \(internal\)](https://cockroachlabs.atlassian.net/l/c/SSSBr8c7)

See: [Grafana](https://go.crdb.dev/roachtest-grafana/teamcity-20971544/copy-bank-rows-100000-nodes-5-txn-true/1768387510661/1768387701044)

</p>
</details>
/cc @cockroachdb/kv-triage
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*copy/bank/rows=100000,nodes=5,txn=true.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/bazci/githubpost/issues)

</sub>

Jira issue: CRDB-58679

### PR DESCRIPTION
**Pull request by wenyihu6**
The validation added in https://github.com/cockroachdb/cockroach/commit/cd6bd43b10ff010fb2a6e21905a56f03a7fd07b8 failed rows=0 which is
legitimately used by the copy/bank
roachtest to create an empty table schema.

This change allows rows=0 (schema-only init) while still rejecting
rows=1.

Fixes: https://github.com/cockroachdb/cockroach/issues/160972
Fixes: https://github.com/cockroachdb/cockroach/issues/161049

### CODE REVIEW

**Comment by DarrylWong** [comment]
I don't have a strong opinion but would `db.Exec("CREATE TABLE bank.bank (LIKE bank.bank_orig)")` instead of the `rows=0` workload import work here too?

**Comment by wenyihu6** [comment]
Given that this is a recent regression introduced by the commit and it’s currently failing, I’d prefer to first revert to the previous behavior to stop the failures, and then we can revisit improvements. Happy to revisit later though.

**Review by DarrylWong — APPROVED** [review]
I still think we (testeng) should determine if this is a pattern we want to allow

1. If it is then I think we should cherry pick the runtime validation from https://github.com/cockroachdb/cockroach/pull/155719
2. If it isn't then I think we should update the test with an alternate approach since this is seemingly the only use case for `rows=0`.

I stamped it but FWIW the nightlies already ran so merging now won't stop any flakes from popping up.

File: pkg/workload/bank/bank.go [hunk 1]
```diff
@@ -117,8 +117,9 @@ func (b *bank) ConnFlags() *workload.ConnFlags { return b.connFlags }
 func (b *bank) Hooks() workload.Hooks {
 	return workload.Hooks{
 		Validate: func() error {
-			if b.rows < 2 {
+			if b.rows != 0 && b.rows < 2 {
```
Comment (herkolategan) [inline pkg/workload/bank/bank.go:120]: I forgot to check if there are roachtests using bank with rows 0. Sorry for the noise / inconvenience. But I think to @DarrylWong's point we aim to not allow 0 rows for this workload - since then it's technically an un-runnable workload.
