### PR TITLE
roachtest: expand support for metamorphic arm64 runs in CI

### LINKED ISSUE #104213: roachtest: enable perf. benchmarks for arm64 and fips
After the introduction of the metamorphic cpu architecture [1], nightly roachtests are using arm64 and fips-enabled clusters, in addition to amd64 (default). Performance tests have been disabled since we need to either route them to a different dashboard or append the (cpu) architecture to the test name in order to disambiguate; otherwise, we will inevitably run into regressions.

[1] https://github.com/cockroachdb/cockroach/pull/103710

Jira issue: CRDB-28412

### PR DESCRIPTION
**Pull request by srosenberg**
CI support for metamorphic arm64 runs was enabled in [1]
with some limitations. This PR addresses those limitations.

Specifically, we now support all compatible performance
tests by separating the resulting performance artifacts
from runs using a different cpu architecture.
(The corresponding artifacts path includes the cpu arch.)

We also fix up docker install script to support arm64
runs, e.g., tpce.

Resolves: https://github.com/cockroachdb/cockroach/issues/104213
Epic: none
Release note: None

[1] https://github.com/cockroachdb/cockroach/pull/104303

### CODE REVIEW

**Comment by srosenberg** [comment]
First run with `--metamorphic-probability 1` is [green](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyAwsBazel/13495452?buildTab=tests&status=passed)--all 93 roachtests pass, out of which 79 ran on graviton3. The remaining 14 are currently opted out,

```
grep amd64 test_runner-1704953933.log |grep "Starting test" |awk -F":" '{print $6}'
 restore/nodeShutdown/coordinator
 restore/nodeShutdown/worker
 restore/online/workload=false/tpce/400GB/aws/inc-count=1/nodes=4/cpus=8
 restore/online/workload=true/tpce/400GB/aws/inc-count=1/nodes=4/cpus=8
 restore/pause/tpce/15GB/aws/nodes=4/cpus=8
 restore/tpce/15GB/aws/nodes=4/cpus=8
 restore/tpce/400GB/aws/inc-count=48/nodes=4/cpus=8
 restore/tpce/400GB/aws/nodes=4/cpus=8
 restore/tpce/400GB/aws/nodes=4/cpus=16
 restore/tpce/400GB/aws/nodes=8/cpus=8
 restore/tpce/400GB/aws/nodes=9/cpus=8/zones=us-east-2b,us-west-2b,eu-west-1b
 restore/tpce/8TB/aws/nodes=10/cpus=8
 kv0/enc=false/nodes=3/cpu=96
 kv95/enc=false/nodes=3/cpu=96
```

File: pkg/cmd/roachtest/tests/tpce.go [hunk 1]
```diff
@@ -80,7 +80,7 @@ func initTPCESpec(
 }
 
 func (ts *tpceSpec) newCmd(o tpceCmdOptions) *roachtestutil.Command {
-	cmd := roachtestutil.NewCommand(`sudo docker run cockroachdb/tpc-e:latest`)
+	cmd := roachtestutil.NewCommand(`sudo docker run us-east1-docker.pkg.dev/crl-ci-images/cockroach/tpc-e:latest`)
```
Comment (srosenberg) [inline pkg/cmd/roachtest/tests/tpce.go:83]: Rebased on top of https://github.com/cockroachdb/cockroach/pull/117691

**Comment by srosenberg** [comment]
Everything now passes on graviton3 with the exception of `cpu=96`, which falls back to `c6a.24xlarge`.

```
grep amd64 test_runner-1711339732.log |grep "Starting test" |awk -F":" '{print $6}'
 kv0/enc=false/nodes=3/cpu=96
 kv95/enc=false/nodes=3/cpu=96
```

**Comment by srosenberg** [comment]
[GCE](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/14643911?buildTab=log&focusLine=6898&logView=linear) run with the overridden `SELECT_PROBABILITY=0.1` and `ARM_PROBABILITY=0.25`

**Review by rail — APPROVED** [review]
LGTM, :shipit:

File: build/teamcity/cockroach/nightlies/roachtest_weekly_aws_impl.sh
Comment (herkolategan) [inline build/teamcity/cockroach/nightlies/roachtest_weekly_aws_impl.sh:1]: Nice!

**Review by herkolategan — APPROVED** [review]

**Review by DarrylWong — APPROVED** [review]

**Comment by srosenberg** [comment]
TFTR!

bors r=rail,herkolategan,DarrylWong

File: pkg/cmd/roachtest/test_runner.go [hunk 2]
```diff
@@ -712,8 +719,14 @@ func (r *testRunner) runWorker(
...
 			artifactsRootDir, _ = os.MkdirTemp("", "roachtest-logger")
 		}
-
-		escapedTestName := teamCityNameEscape(testToRun.spec.Name)
+		testName := testToRun.spec.Name
+		// N.B. c may be nil owing to clusterCreateErr
+		if c != nil && c.arch != vm.ArchAMD64 {
+			// N.B. For non-default cpu architecture, encode it in the test name. This helps to differentiate test
+			// artifacts/results by cpu architecture.
+			testName = fmt.Sprintf("%s/cpu_arch=%s", testName, c.arch)
```
Comment (renatolabs) [inline pkg/cmd/roachtest/test_runner.go:727]: I wonder if this will be confusing. AFAICT, this `testName` is only used when reporting the test name on TC. Everywhere else (github issue, source code, etc) will use the name without suffix.

**Comment by renatolabs** [comment]
I believe we should disable arm64 if we _know_ it won't work -- i.e., if the test specified one or more regions, and we know at least one of those regions don't support T2As. In that case, we shouldn't try to run an arm64 build.

Am I missing something?

Related: https://github.com/cockroachdb/cockroach/issues/120621#issuecomment-2040328085.

**Comment by srosenberg** [comment]
> I believe we should disable arm64 if we _know_ it won't work -- i.e., if the test specified one or more regions, and we know at least one of those regions don't support T2As. In that case, we shouldn't try to run an arm64 build.
> 
> Am I missing something?
> 
> Related: [#120621 (comment)](https://github.com/cockroachdb/cockroach/issues/120621#issuecomment-2040328085).

Indeed, if it's known a priori, the specific test should opt out from arm64. I'll send a PR for the test in question.

File: pkg/cmd/roachtest/test_runner.go (hunk 2 above)
Comment (srosenberg) [reply pkg/cmd/roachtest/test_runner.go:727]: We have `ROACHTEST_arch=` parameter in GH. Short of serializing test specs as part of artifacts, I don't believe I found a less hackier way of encoding the architecture to ensure the artifacts (for amd64 and arm64) don't get mixed. Did you have another idea?

**Comment by DarrylWong** [comment]
A bunch of ORM tests also don't work because they need to download a ARM64 binary. I can put out an PR for those tests since I was already looking at it.

Is there already a way to opt out a test from arm64 or should I add one similar to `CompatibleClouds`?
