### PR TITLE
harden ChaosMonkey

### LINKED ISSUE #3450: TestChaos is flaky
The following test appears to have failed:

[#10187](https://circleci.com/gh/cockroachdb/cockroach/10187):

```
I1215 02:44:53.894710 17886 client/db.go:478  failed batch: failed to send RPC request Server.Batch: client is unhealthy
I1215 02:44:57.358427 17886 acceptance/chaos_test.go:98  client 2 shutting down
I1215 02:44:57.426019 17886 acceptance/chaos_test.go:98  client 1 shutting down
I1215 02:44:57.426126 17886 acceptance/chaos_test.go:201  635 49.0/sec
I1215 02:44:57.579907 17886 acceptance/cluster/localcluster.go:523  stopping
--- FAIL: TestChaos (30.63s)
	chaos_test.go:167: failed to send RPC request Server.Batch: client is unhealthy
=== RUN   TestGossipPeerings
I1215 02:45:02.160923 17886 acceptance/cluster/localcluster.go:211  started docker-spy: 172.17.0.17
I1215 02:45:02.160955 17886 acceptance/cluster/localcluster.go:218  initializing cluster
I1215 02:45:05.212672 17886 acceptance/cluster/localcluster.go:326  creating ca (1024bit) in: /home/ubuntu/cockroach/.localcluster.certs.672848760
I1215 02:45:05.270569 17886 acceptance/cluster/localcluster.go:331  creating node (1024bit) certs in: /home/ubuntu/cockroach/.localcluster.certs.672848760
I1215 02:45:07.395121 17886 acceptance/cluster/localcluster.go:379  *** started roach0.local ***
  ui:    https://0.0.0.0:32777
  trace: https://0.0.0.0:32777/debug/requests
  logs:  /tmp/circle-artifacts.OpjNpm4/acceptance/roach0.local/cockroach.INFO
--
--- SKIP: TestBuildCluster (0.00s)
	terraform_test.go:33: only enabled during testing
=== RUN   TestFiveNodesAndWriters
--- SKIP: TestFiveNodesAndWriters (0.00s)
	main_test.go:54: running in docker mode
FAIL
ok github.com/cockroachdb/cockroach/acceptance 1337s

```
Please assign, take a look and update the issue accordingly.

### PR DESCRIPTION
**Pull request by tbg**
while nodes are restarting, clients (now) return errors
more eagerly. Ignore those (for they're expected). The
log output has become a little more spammy, but I think
that's acceptable for the time being.

Fixes #3450.

[Review on Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/3453)

### CODE REVIEW

File: acceptance/chaos_test.go [hunk 1]
```diff
@@ -85,7 +84,7 @@ func TestChaos(t *testing.T) {
 					// These originate from DistSender when, for example, the
 					// leader is down. With more realistic retry options, we
 					// should probably not see them.
-					if _, ok := err.(*roachpb.SendError); ok || testutils.IsError(err, rpc.ErrShutdown.Error()) {
+					if _, ok := err.(*roachpb.SendError); ok || testutils.IsError(err, rpc.ErrShutdown.Error()) || testutils.IsError(err, "client is unhealthy") {
```
Comment (petermattis) [inline acceptance/chaos_test.go]: Perhaps `rpcSender.Send` should return a `SendError` if the client is unhealthy.

File: acceptance/chaos_test.go [hunk 2]
```diff
@@ -73,11 +73,10 @@ func TestChaos(t *testing.T) {
 		go func(i int) {
 			r, _ := randutil.NewPseudoRand()
 			value := randutil.RandBytes(r, 8192)
+			k := atomic.LoadInt64(&count)
```
Comment (petermattis) [inline acceptance/chaos_test.go]: Won't this allow multiple goroutines to write to the same key?

Comment (tschottdorf) [inline acceptance/chaos_test.go]: yes, but that doesn't matter here. We use counts only to track client activity.

Comment (petermattis) [inline acceptance/chaos_test.go]: I'm confused. You're using `k` to generate the key.

File: acceptance/chaos_test.go (hunk 1 above)
Comment (tschottdorf) [inline acceptance/chaos_test.go]: maybe, but that should be in a different change. There are some things to be considered (will this `SendError` be retryable or not? If so, there are infinite retries at `DistSender`). For the purpose of the chaos test, it's convenient to get errors.

File: acceptance/chaos_test.go (hunk 2 above)
Comment (tschottdorf) [inline acceptance/chaos_test.go]: as discussed in person, the values written here don't matter. This is mostly an artifact of this having spawned from `TestPut`.

**Comment by petermattis** [comment]
LGTM

**Comment by BramGruneir** [comment]
I was working on a different version of this, just having circleci issues last night.
https://github.com/BramGruneir/cockroach/tree/monkey

**Comment by BramGruneir** [comment]
LGTM
