### PR TITLE
sql: support query cancellation for COPY TO

### LINKED ISSUE #97500: roachtest: asyncpg failed
roachtest.asyncpg [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/8785686?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/8785686?buildTab=artifacts#/asyncpg) on master @ [286b3e235171a39b8f9910555affcc7ce310741a](https://github.com/cockroachdb/cockroach/commits/286b3e235171a39b8f9910555affcc7ce310741a):

```
test artifacts and logs in: /artifacts/asyncpg/run_1
(test_runner.go:989).runTest: test timed out (10h0m0s)
(orm_helpers.go:201).summarizeFailed: 
Tests run on Cockroach v23.1.0-alpha.3-236-g286b3e2351
Tests run against asyncpg v0.24.0
55 Total Tests Run
33 tests passed
22 tests failed
29 tests skipped
0 tests ignored
0 tests passed unexpectedly
0 tests failed unexpectedly
0 tests expected failed but skipped
53 tests expected failed but not run
---
For a full summary look at the asyncpg artifacts
An updated blocklist (asyncpgBlocklist) is available in the artifacts' asyncpg log
```
<p>Parameters: <code>ROACHTEST_cloud=gce</code>
, <code>ROACHTEST_cpu=16</code>
, <code>ROACHTEST_encrypted=false</code>
, <code>ROACHTEST_fs=ext4</code>
, <code>ROACHTEST_localSSD=true</code>
, <code>ROACHTEST_ssd=0</code>
</p>
<details><summary>Help</summary>
<p>

See: [roachtest README](https://github.com/cockroachdb/cockroach/blob/master/pkg/cmd/roachtest/README.md)

See: [How To Investigate \(internal\)](https://cockroachlabs.atlassian.net/l/c/SSSBr8c7)

</p>
</details>
/cc @cockroachdb/sql-sessions
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*asyncpg.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)
</sub>

Jira issue: CRDB-24729

### PR DESCRIPTION
**Pull request by rafiss**
This is done by making COPY TO respect the conn executor state transitions.

No release note since COPY TO is new.

fixes https://github.com/cockroachdb/cockroach/issues/97500

Release note: None

### CODE REVIEW

File: pkg/sql/pgwire/pgwirecancel/cancel_test.go [hunk 1]
```diff
@@ -162,3 +164,38 @@ func TestCancelQueryOtherNode(t *testing.T) {
...
+		url.User(username.RootUser),
+	)
+	defer cleanup()
+
+	conn, err := pgx.Connect(ctx, pgURL.String())
+	require.NoError(t, err)
+
+	g := ctxgroup.WithContext(ctx)
+	g.GoCtx(func(ctx context.Context) error {
+		_, err = conn.Exec(ctx, "COPY (SELECT pg_sleep(1) FROM ROWS FROM (generate_series(1, 1000)) AS i) TO STDOUT")
```
Comment (otan) [inline pkg/sql/pgwire/pgwirecancel/cancel_test.go:191]: oh my

**Review by otan — APPROVED** [review]

File: pkg/sql/pgwire/pgwirecancel/cancel_test.go (hunk 1 above)
Comment (otan) [reply pkg/sql/pgwire/pgwirecancel/cancel_test.go:191]: (maybe make this 5min just in case? haha!)

**Comment by rafiss** [comment]
tftr!

bors r=otan
