### PR TITLE
sql/schemachanger: CREATE SEQUENCE is incorrectly adding a rowid column

### LINKED ISSUE #119108: sql/schemachanger: CREATE SEQUENCE is incorrectly adding a rowid column
The declarative schema changer implementation ends up creating sequence descriptors with a extra rowid column, which happens because we implicitly end up allocating this column when allocating column IDs. The logic for the descriptor logic to allocate column IDs ends up allocating a new primary key if its missing, which is unnecessary for the declarative schema changer and leads to incorrect behaviour.

Jira issue: CRDB-36035

Epic CRDB-31332

### PR DESCRIPTION
**Pull request by fqazi**
Previously, CREATE SEQUENCE in the declarative schema changer incorrectly created a rowid column. This occurred because the default logic for allocating column IDs also created a primary index with the rowid column, if one was missing. To address this, this patch modifies the allocation logic to make primary index creation optional and adds a regression test.

Fixes: #119108
Release note: None

### CODE REVIEW

File: pkg/sql/schemachanger/testdata/end_to_end/create_sequence/create_sequence.side_effects [hunk 1]
```diff
@@ -29,21 +29,13 @@ upsert descriptor #104
   +      family: IntFamily
   +      oid: 20
   +      width: 64
-  +  - defaultExpr: unique_rowid()
```
Comment (rafiss) [inline pkg/sql/schemachanger/testdata/end_to_end/create_sequence/create_sequence.side_effects:32]: ah, good reminder that we should try to review what's in these expectation files closely

File: pkg/sql/catalog/tabledesc/structured.go [hunk 2]
```diff
@@ -545,9 +545,11 @@ func (desc *Mutable) AllocateIDs(ctx context.Context, version clusterversion.Clu
 
 // AllocateIDsWithoutValidation allocates column, family, and index ids for any
 // column, family, or index which has an ID of 0.
-func (desc *Mutable) AllocateIDsWithoutValidation(ctx context.Context) error {
+func (desc *Mutable) AllocateIDsWithoutValidation(
+	ctx context.Context, createMissingPrimaryKey bool,
+) error {
 	// Only tables with physical data can have / need a primary key.
-	if desc.IsPhysicalTable() {
+	if desc.IsPhysicalTable() && createMissingPrimaryKey {
```
Comment (rafiss) [inline pkg/sql/catalog/tabledesc/structured.go:552]: instead of adding a new boolean parameter, can this just be 
```
if desc.IsPhysicalTable() && !desc.IsSequence()
```

**Review by rafiss — CHANGES_REQUESTED** [review]
really nice find! just one question

**Review by fqazi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/119115)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @rafiss)

___
*[`pkg/sql/catalog/tabledesc/structured.go` line 552 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/119115#gh-1487133648:-NqXqS5W4UBtaMcvgOq8:bhi0t5r) ([raw file](https://github.com/cockroachdb/cockroach/blob/41f9312938ec2d38d5921721136e7b3e2bc66680/pkg/sql/catalog/tabledesc/structured.go#L552)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

instead of adding a new boolean parameter, can this just be 
```
if desc.IsPhysicalTable() && !desc.IsSequence()
```
</blockquote></details>

The problem is that we will hit this when we try to implement CREATE TABLE too. The general issue is that the ordering of the declarative schema changer is more logically correct and we are going to be always explicitly making the primary index and the columns needed to back it. i.e. We will always create columns before we make the indexes backing them.
___
*[`pkg/sql/schemachanger/testdata/end_to_end/create_sequence/create_sequence.side_effects` line 0 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/119115#gh-1487105029:-NqXqrYp8ZVzhtR4TrBN:bssoxi4) ([raw file](https://github.com/cockroachdb/cockroach/blob/41f9312938ec2d38d5921721136e7b3e2bc66680/pkg/sql/schemachanger/testdata/end_to_end/create_sequence/create_sequence.side_effects#L0)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

*(Reviewable was [unable](https://github.com/Reviewable/Reviewable/issues/14) to map [this GitHub inline comment thread](https://github.com/cockroachdb/cockroach/pull/119115#discussion_r1487105029) to the right spot — sorry!)*

ah, good reminder that we should try to review what's in these expectation files closely 
</blockquote></details>

Yeah, this was big miss for me too. I'm shocked we also don't have validation, but I'll dig into that later (i.e. something should be backing this column).

**Review by rafiss — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/119115)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @fqazi)

___
*[`pkg/sql/catalog/tabledesc/structured.go` line 552 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/119115#gh-1487133648:-NqXxY1_EDae799w4S8q:b1rn8e5) ([raw file](https://github.com/cockroachdb/cockroach/blob/41f9312938ec2d38d5921721136e7b3e2bc66680/pkg/sql/catalog/tabledesc/structured.go#L552)):*
<details><summary><i>Previously, fqazi (Faizan Qazi) wrote…</i></summary><blockquote>

The problem is that we will hit this when we try to implement CREATE TABLE too. The general issue is that the ordering of the declarative schema changer is more logically correct and we are going to be always explicitly making the primary index and the columns needed to back it. i.e. We will always create columns before we make the indexes backing them.
</blockquote></details>

ah i see, so when we implement CREATE TABLE in the DSC, we also need to pass in false. then maybe we should change the comment. instead of
```
	// Only tables with physical data can have / need a primary key.
```

maybe 
```
	// Only tables with physical data can have / need a primary key. In the new schema changer,
	// the primary key is created explicitly so we don't need to create it here.
```
(or something like that that sounds accurate to you)

**Review by fqazi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/119115)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @rafiss)

___
*[`pkg/sql/catalog/tabledesc/structured.go` line 552 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/119115#gh-1487133648:-NqYpJioDk-xLxv8P85C:b-ohiynd) ([raw file](https://github.com/cockroachdb/cockroach/blob/41f9312938ec2d38d5921721136e7b3e2bc66680/pkg/sql/catalog/tabledesc/structured.go#L552)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

ah i see, so when we implement CREATE TABLE in the DSC, we also need to pass in false. then maybe we should change the comment. instead of
```
	// Only tables with physical data can have / need a primary key.
```

maybe 
```
	// Only tables with physical data can have / need a primary key. In the new schema changer,
	// the primary key is created explicitly so we don't need to create it here.
```
(or something like that that sounds accurate to you)
</blockquote></details>

Done.

Added: 
// Only tables with physical data can have / need a primary key. In the  
// declarative schema changer the primary key is always created explicitly,  
// so we don't need to create it here.

**Comment by fqazi** [comment]
@rafiss TFTR!

bors r+
