### PR TITLE
catalog: utilize scans for a large number of descriptors

### LINKED ISSUE #100871: sql: Django introspection query performance regression (still)
**Describe the problem**

A regression is causing the following query (which Django's test suite runs quite often) to take 1-2 seconds (instead of milliseconds).

**To Reproduce**

```sql
SELECT
    c.relname,
    CASE
        WHEN c.relispartition THEN 'p'
        WHEN c.relkind IN ('m', 'v') THEN 'v'
        ELSE 't'
    END
FROM pg_catalog.pg_class c
LEFT JOIN pg_catalog.pg_namespace n ON n.oid = c.relnamespace
WHERE c.relkind IN ('f', 'm', 'p', 'r', 'v')
    AND n.nspname NOT IN ('pg_catalog', 'pg_toast')
    AND pg_catalog.pg_table_is_visible(c.oid)
```

**Environment:**
 - CockroachDB version v23.1.0-alpha.8-dev-af563f889
    Build Time: 2023/04/06 20:05:50

**Additional context**

The same issue was reported in https://github.com/cockroachdb/cockroach/issues/93955 where performance was improved a little.

Related PRs:
- https://github.com/cockroachdb/cockroach/pull/94325
- https://github.com/cockroachdb/cockroach/pull/96397

The full Django test suite runtime is up from ~40 minutes with 22.2.x to ~1.5 hrs (though I'm not sure it's entirely attributable to this query).

Jira issue: CRDB-26663

### PR DESCRIPTION
**Pull request by fqazi**
Previously, the catalog descriptor would fetch descriptors via point lookups using Get when scanning large batches of descriptors. This was further extended to also look up ZoneConfigs and comments in a similar way. Recently, we we started seeing regression on the Django test suite involving the pg_catalog tables, which tend to do read large number of descriptors, likely linked to extra overhead linked to both comments and zone configs in 23.1. To address this, this patch ill now start using scans for runs of descriptor IDs for batch scans which reduces the overall cost of fetching a large number of descriptors hiding this cost.

Fixes: #100871

Release note: None

### CODE REVIEW

File: pkg/sql/catalog/internal/catkv/catalog_reader.go [hunk 1]
```diff
@@ -228,18 +228,62 @@ func (cr catalogReader) GetByIDs(
...
+					catalogkeys.MakeObjectCommentsMetadataPrefix(codec, t, runEndID+1))
+			}
+			scanRange(ctx, b, config.MakeZoneKey(codec, runStartID),
+				config.MakeZoneKey(codec, runEndID+1))
+		}
+		startIDSet = false
+	}
+
+	err := cq.query(ctx, txn, &mc, func(codec keys.SQLCodec, b *kv.Batch) {
+		for _, id := range ids {
```
Comment (chengxiong-ruan) [inline pkg/sql/catalog/internal/catkv/catalog_reader.go:264]: I think this works. But I also think it would be nice to have a function to calculate the continuous segments instead of having the function scope variables which can be hard to interpret in the future :) Nice work though!

Comment (fqazi) [reply pkg/sql/catalog/internal/catkv/catalog_reader.go]: Done, pulled the logic into a function

**Review by chengxiong-ruan — APPROVED** [review]
very nice!

**Comment by fqazi** [comment]
@chengxiong-ruan TFTR!

bors r+
