### PR TITLE
gossip: fix pending callbacks not dropping to zero

### LINKED ISSUE #147982: gossip: pending callbacks not dropping to zero
Discussion and a suggestion on the fix: https://cockroachlabs.slack.com/archives/C08U1QLQHE1/p1749464544044589

Image

Jira issue: CRDB-51348

Epic CRDB-48943

### PR DESCRIPTION
**Pull request by iskettaneh**
We have seen cases before where there was an issue with the pending callbacks metric that it's stuck at some non-zero number. This commit fixes that by:

1) If the infoStore stopper() is quiescing, we should not add more items to the work queue, because they could not be processed, and the pending callbacks metrics won't get decremented.

2) Only increment the pending callbacks metric when we actually add items to the work queue, and not before. Otherwise, there could be a race condition where we increment the pending callbacks metric, and then the infostore Stopper gets quiesced before we added any items to the work queue. This means that we won't decrement the pending callbacks metric.

3) When the callback gets cancelled, or when the infostore stopper gets quiesced, we decrement the pending callbacks metric by the number of items in the work queue. Otherwise, we might not decrement the number of pending callbacks.

Fixes: #147982

Release note: None

### CODE REVIEW

File: pkg/gossip/infostore.go [hunk 1]
```diff
@@ -274,8 +287,14 @@ func (is *infoStore) launchCallbackWorker(ambient log.AmbientContext, cw *callba
 			case <-cw.callbackCh:
 				// New work has just arrived.
 			case <-is.stopper.ShouldQuiesce():
+				// We are never going to process the work in the queues anymore, so
+				// clean up the pending callbacks metric.
+				is.cleanupCallbackMetric(cw)
```
Comment (stevendanna) [inline pkg/gossip/infostore.go]: Could we defer this at the beginning of the async task?

File: pkg/gossip/infostore.go [hunk 2]
```diff
@@ -444,11 +463,19 @@ func (is *infoStore) processCallbacks(key string, content roachpb.Value, changed
 // It adds work to the callback work slices, and signals the associated callback
 // workers to execute the work.
 func (is *infoStore) runCallbacks(key string, content roachpb.Value, callbacks ...*callback) {
+	// Check if the stopper is quiescing. If so, do not add the callbacks to the
+	// callback work list because they won't be processed anyways.
+	select {
+	case <-is.stopper.ShouldQuiesce():
+		return
+	default:
+	}
```
Comment (stevendanna) [inline pkg/gossip/infostore.go:469]: Isn't another case where this could happen the stopperCh on the callback worker itself?

I suppose the "big gun" here to avoid having to think hard about this might be a `stopped` boolean that lives under `cw.mu` that would be set by our cleanup function and would be checked before adding anything to the queue.  I'm not familiar with exactly how tight our budgets are here to know whether that extra check would be too costly.

**Review by stevendanna — COMMENTED** [review]
Thanks for not losing track of this!

**Comment by stevendanna** [comment]
Not sure why github posted my review twice 🤷

File: pkg/gossip/infostore.go (hunk 1 above)
Comment (iskettaneh) [reply pkg/gossip/infostore.go]: If you want, I could ~duplicate the select statement at the beginning of the async task.

However, I think we need some select case here because imagine there are NO work coming to the queue, we need to still keep an eye on signals that make us stop

File: pkg/gossip/infostore.go (hunk 2 above)
Comment (iskettaneh) [reply pkg/gossip/infostore.go:469]: I don't see the case happening here for the following reason:

1) We atomically increment the metric and add it to the work queue for that goroutine (due to holding cb.cw.mu)
2) If after we added a work item to the worker queue and we signal to that goroutine, it will either consume is (and decrement the metric), or return (and cleanup the metric)

**Review by iskettaneh — COMMENTED** [review]
Thank you so much for the review!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/150187#-:-OVDl_ar5CF3_Xif-Gmn:b-bz2g)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @stevendanna)

File: pkg/gossip/infostore.go (hunk 1 above)
Comment (stevendanna) [reply pkg/gossip/infostore.go]: What I meant here was that as far as I can see, the only return points for the func we are currently in are at lines 293 and 298, both of which call cleanupCallbackMetric. To me that implies we could unconditionally `defer is.cleanupCallbackMetric(cw)` rather than calling it right before each return explicitly.

File: pkg/gossip/infostore.go (hunk 2 above)
Comment (iskettaneh) [reply pkg/gossip/infostore.go:469]: Oh sorry I was looking at a different code by mistake, but I still think that the part you mentioned is safe because:

1) If we added work, we are sure that the worker will either execute it, or clean up the metric
2) If we return here before adding work. We having incremented the metric, so the worker will not clean-up anything (nothing needs cleaning)

Note that the worker is running on a different goroutine

File: pkg/gossip/infostore.go (hunk 1 above)
Comment (iskettaneh) [reply pkg/gossip/infostore.go]: Got it! Yes that makes total sense

File: pkg/gossip/infostore.go (hunk 2 above)
Comment (stevendanna) [reply pkg/gossip/infostore.go:469]: Apologies, I'm not that familiar with this code so perhaps I didn't read carefully enough. I was thinking of a scenario where:
0. Someone calls the unregister callback. 
1. `stopperC` is closed. But the callback isn't removed from infostore yet.
2. worker goroutine sees this, cleans up, and returns. At this point we have the callback still in our infostore set but nothing will process events put in its queue.
3. We arrive at this function which doesn't check stopperC, we increment the metric but nothing will decrement it.

Comment (iskettaneh) [reply pkg/gossip/infostore.go:469]: Oh I see what you mean. This will also not happen because of this: We only add new info (which will eventually call the code location that you pointed) while holding the [general gossip lock](https://github.com/cockroachdb/cockroach/blob/a9d047a894dec13822e96be04e7006360f488a34/pkg/gossip/gossip.go#L922-L926). Also, we hold the same mutex when we are [unregistering a callback](https://github.com/cockroachdb/cockroach/blob/a9d047a894dec13822e96be04e7006360f488a34/pkg/gossip/gossip.go#L1166-L1170). So If the callback is deregistered, removing the callback from the list is atomic. Therefore, there should be no race with the codeplace you mentioned above since the same mutex needs to be held.

File: pkg/gossip/infostore.go (hunk 1 above)
Comment (iskettaneh) [reply pkg/gossip/infostore.go]: I have done it and repushed the change. Thank you!

File: pkg/gossip/infostore.go (hunk 2 above)
Comment (stevendanna) [reply pkg/gossip/infostore.go:469]: Aha, that makes sense

File: pkg/gossip/gossip_test.go [hunk 3]
```diff
@@ -1140,3 +1140,68 @@ func TestGossipBatching(t *testing.T) {
...
+			// Execute the cleanup action (either unregister or stopper.Stop)
+			tc.cleanup(g, unregister, stopper, ctx)
+
+			// Add another 100 infos to the gossip that will be processed by the callback.
+			for i := 0; i < 100; i++ {
+				slice := []byte("b")
+				if err := g.AddInfo(fmt.Sprintf("test.key%d", i), slice, time.Hour); err != nil {
+					t.Fatal(err)
+				}
+			}
```
Comment (stevendanna) [inline pkg/gossip/gossip_test.go]: I wonder if this test would be more interesting if we did these two steps in different goroutines.

**Review by stevendanna — APPROVED** [review]

File: pkg/gossip/gossip_test.go (hunk 3 above)
Comment (iskettaneh) [reply pkg/gossip/gossip_test.go]: That's a great idea! Done

**Comment by iskettaneh** [comment]
TFTR!

bors r+

**Comment by yuzefovich** [comment]
There is a lint failure.

bors r-

**Comment by iskettaneh** [comment]
Hopefully that fixes the lint error

bors r+
