### PR TITLE
sql/schemachanger/*: optimize performance, primarily by adding support for containment

### LINKED ISSUE #86042: drop database with hundreds of tables takes hours
**Describe the problem**

The build for [django-cockroachdb](https://github.com/cockroachdb/django-cockroachdb) typically takes about an hour. A change in CockroachDB nightly between July 22 and August 3 increased the build time to around 24 hours. The tests run in the same amount of time, but the two `DROP DATABASE` queries at the conclusion of the test suite now take hours.

**Additional data / screenshots**

The roachtest build of django-cockroachdb which runs [some cluster queries](https://github.com/cockroachdb/cockroach/blob/25fe0db12911a60571c3788b9403a6f42b52e003/pkg/cmd/roachtest/tests/orm_helpers.go#L38-L50) isn't affected by this performance regression.

**Environment:**
 - CockroachDB version: v22.2.0-alpha.00000000-2394-g6c24f3564e @ 2022/08/10 06:04:30

Jira issue: CRDB-18542

### PR DESCRIPTION
**Pull request by ajwerner**
#### sql/schemachanger/rel: support inverted indexes and slice containment

This commit introduces some new concepts to rel:
* Slice attributes
* Inverted indexing of slice attributes
* Containment queries over slice attributes

One note is that the only support for containment queries is via an inverted
index. In the future, we could add direct containment evaluation such that if
we have a slice we could go iterate its members.

The basic idea is to introduce a slice membership type for the slice column
and to use the attribute in question to refer to the slice member value.

#### sql/schemachanger/rel: optimize error checking
This change ends up making a huge difference. Otherwise, each subquery
invocation would lead to allocations which showed up in the profiles.

Fixes #86042

Release note: None

### CODE REVIEW

**Comment by ajwerner** [comment]
I've tried to add more commentary and to clean this up a bit. It's ready for a look.

File: pkg/sql/schemachanger/rel/database.go [hunk 1]
```diff
@@ -145,6 +159,78 @@ func NewDatabase(sc *Schema, indexes ...Index) (*Database, error) {
...
+	for _, idx := range indexes {
+		if !idx.Inverted {
+			expanded = append(expanded, idx)
+			continue
+		}
+		if err := validatedInvertedIndexProperties(sc, idx); err != nil {
+			return nil, err
+		}
+		expanded = append(expanded, Index{
+			Attrs:    []Attr{idx.Attrs[0], sliceSource, sliceIndex},
```
Comment (chengxiong-ruan) [inline pkg/sql/schemachanger/rel/database.go:185]: maybe a redundant commentary here that there'll be only one attribute if it's inverted index so it's safe to just do `idx.Attrs[0]`

File: pkg/sql/schemachanger/rel/database.go [hunk 2]
```diff
@@ -170,6 +264,9 @@ func (t *Database) insert(v interface{}, es entityStore) (id int, err error) {
 		if idx.exists != 0 && !idx.exists.isContainedIn(e.attrs) {
 			continue
 		}
+		if typ.isSliceMemberType && !idx.isInverted {
```
Comment (chengxiong-ruan) [inline pkg/sql/schemachanger/rel/database.go:267]: I'd appreciate some commentary on why we want to skip in such case even it's clear that slice member can only be inserted into inverted index. like the good one you have on line #377

File: pkg/sql/schemachanger/rel/database_entity_set.go [hunk 3]
```diff
@@ -60,6 +60,32 @@ func (t *entitySet) insert(v interface{}, es entityStore) (int, error) {
...
+			fv := reflect.ValueOf(fvi)
+			if fv.Kind() != reflect.Slice {
+				return 0, errors.AssertionFailedf(
+					"expected a slice type, got %v", fv.Type(),
+				)
+			}
+			for i := 0; i < fv.Len(); i++ {
+				smpv := reflect.New(field.sliceMemberType.Elem())
+				smv := smpv.Elem()
+				smv.Field(sliceMemberSourceFieldIndex).Set(value)
```
Comment (chengxiong-ruan) [inline pkg/sql/schemachanger/rel/database_entity_set.go:79]: what about the other index we expanded with attributes `Attrs: []Attr{idx.Attrs[0], sliceSource, sliceIndex}` ?

File: pkg/sql/schemachanger/rel/doc.go [hunk 4]
```diff
@@ -153,12 +153,17 @@
...
+// Rel supports inverted indexes over slices. In order to use them, you create
+// an attribute referencing a slice. Internally, rel will create a new
+// element internally for each member. The containment operator can be used
+// to perform an inverted lookup.
+//
 // # Future work
 //
 // Below find a listing of features not yet done.
 //
-//   - Arrays, Maps, Slices.
```
Comment (chengxiong-ruan) [inline pkg/sql/schemachanger/rel/doc.go:160]: Do we support Maps and Arrays already?

File: pkg/sql/schemachanger/rel/query_build.go [hunk 5]
```diff
@@ -145,15 +145,73 @@ func (p *queryBuilder) processClause(t Clause) {
...
+		p.handleContains(fd.entity, ord, contains.v)
+		return true
+	}
+}
+
+// handleContains will add facts to join the source to the slice member
+// value by joining the source and a slice member entity.
+//
+// Importantly we choose to create the entity for the slice member prior
+// to creating marking the variable which is the source of the slice
```
Comment (chengxiong-ruan) [inline pkg/sql/schemachanger/rel/query_build.go:181]: `creating marking` -> `creating` ?

File: pkg/sql/schemachanger/rel/query_build.go [hunk 6]
```diff
@@ -245,26 +303,28 @@ func (p *queryBuilder) processValueExpr(rawValue expr) slotIdx {
...
 		return p.fillSlot(slot{not: tv}, false)
+	case containsExpr:
+		return p.processValueExpr(v.v)
 	default:
 		panic(errors.AssertionFailedf("unknown expr type %T", rawValue))
 	}
 }
 
-func (p *queryBuilder) maybeAddVar(v Var, entity bool) slotIdx {
+func (p *queryBuilder) maybeAddVar(v Var, isEntity bool) slotIdx {
```
Comment (chengxiong-ruan) [inline pkg/sql/schemachanger/rel/query_build.go:313]: thanks for this renaming

**Review by chengxiong-ruan — APPROVED** [review]
LGTM. awesome changes!

**Review by postamar — CHANGES_REQUESTED** [review]
This is a wonderful change. I have only minor requests. Admittedly, I've only given somewhat superficial treatment to the second commit.

**Review by ajwerner — COMMENTED** [review]
TFTR!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/87820#-:-NCrnrIC0mi6W5yJpInw:bodgj64)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @chengxiong-ruan, @postamar, and @Xiang-Gu)

___
*[`pkg/sql/schemachanger/rel/database.go` line 170 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/87820#-NBlumtK6poDafokP7NI-r2-170:-NCriBkfDdBmASl29gbe:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/83426156d0635c2070e3a50dd22ab1d8903cbadc/pkg/sql/schemachanger/rel/database.go#L170)):*
<details><summary><i>Previously, postamar (Marius Posta) wrote…</i></summary><blockquote>

Thanks for this explanation!
</blockquote></details>

Done.
___
*[`pkg/sql/schemachanger/rel/database.go` line 174 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/87820#-NBlumtK6poDafokP7NI-r2-174:-NCaEVCn8EBtTJ7QarFd:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/83426156d0635c2070e3a50dd22ab1d8903cbadc/pkg/sql/schemachanger/rel/database.go#L174)):*
<details><summary><i>Previously, postamar (Marius Posta) wrote…</i></summary><blockquote>

nit: this seems superfluous
</blockquote></details>

Done.
___
*[`pkg/sql/schemachanger/rel/database.go` line 185 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/87820#-NBlumtK6poDafokP7NI-r4-185:-NCaJxoEEVakbpK2NE86:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/bb67bade2e85203ab48eed44266aed6f87822fb2/pkg/sql/schemachanger/rel/database.go#L185)):*
<details><summary><i>Previously, chengxiong-ruan (Chengxiong Ruan) wrote…</i></summary><blockquote>

maybe a redundant commentary here that there'll be only one attribute if it's inverted index so it's safe to just do `idx.Attrs[0]`
</blockquote></details>

Done.
___
*[`pkg/sql/schemachanger/rel/database.go` line 267 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/87820#-NBlumtK6poDafokP7NI-r4-267:-NCf7DKD8QIbD9t4FEPn:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/bb67bade2e85203ab48eed44266aed6f87822fb2/pkg/sql/schemachanger/rel/database.go#L267)):*
<details><summary><i>Previously, chengxiong-ruan (Chengxiong Ruan) wrote…</i></summary><blockquote>

I'd appreciate some commentary on why we want to skip in such case even it's clear that slice member can only be inserted into inverted index. like the good one you have on line #377
</blockquote></details>

Done.
___
*[`pkg/sql/schemachanger/rel/database_entity_set.go` line 79 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/87820#-NBlumtK6poDafokP7NM-r4-79:-NCf7GDJ53ejrdlQr_sx:b-l6b4px) ([raw file](https://github.com/cockroachdb/cockroach/blob/bb67bade2e85203ab48eed44266aed6f87822fb2/pkg/sql/schemachanger/rel/database_entity_set.go#L79)):*
<details><summary><i>Previously, chengxiong-ruan (Chengxiong Ruan) wrote…</i></summary><blockquote>

what about the other index we expanded with attributes `Attrs: []Attr{idx.Attrs[0], sliceSource, sliceIndex}` ?
</blockquote></details>

That's handled transparently. The indexing is independent of the struct fields. There's essentially two layers of indirection. We go from a struct (entity) to a `rel.values` which is a effectively a `map[Attr]interface{}` with some optimizations and then we go from a `rel.values` to a `rel.valuesItem` which combines the `values` with the `indexSpec` to describe how to sort it relative to other index entries. 
___
*[`pkg/sql/schemachanger/rel/query_build.go` line 184 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/87820#-NBlumtLM3Tq_GetAMEy-r2-184:-NCfAkZB2cYlLiXgIjKq:bcev121) ([raw file](https://github.com/cockroachdb/cockroach/blob/83426156d0635c2070e3a50dd22ab1d8903cbadc/pkg/sql/schemachanger/rel/query_build.go#L184)):*
<details><summary><i>Previously, postamar (Marius Posta) wrote…</i></summary><blockquote>

nit: this sentence is very hard to read
</blockquote></details>

I rewrote it.
___
*[`pkg/sql/schemachanger/rel/query_build.go` line 181 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/87820#-NBlumtLM3Tq_GetAMEy-r4-181:-NCriCO5Aeswa2BVqbYi:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/bb67bade2e85203ab48eed44266aed6f87822fb2/pkg/sql/schemachanger/rel/query_build.go#L181)):*
<details><summary><i>Previously, chengxiong-ruan (Chengxiong Ruan) wrote…</i></summary><blockquote>

`creating marking` -> `creating` ?
</blockquote></details>

Done.
___
*[`pkg/sql/schemachanger/rel/reltest/registry.go` line 97 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/87820#-NBlumtLM3Tq_GetAMF1-r2-97:-NCfB2kM54JrmjJXm2R4:b8amr83) ([raw file](https://github.com/cockroachdb/cockroach/blob/83426156d0635c2070e3a50dd22ab1d8903cbadc/pkg/sql/schemachanger/rel/reltest/registry.go#L97)):*
<details><summary><i>Previously, postamar (Marius Posta) wrote…</i></summary><blockquote>

Just curious but how did this come about?
</blockquote></details>

slices are unhashable.

This code exists to make it possible to display pointers to structs (entities) elegantly by giving them names and replaying their inline yaml with their name. It allows the graph structure to be more apparent. Slices themselves are never part of that. 
___
*[`pkg/sql/schemachanger/scplan/internal/rules/dep_drop_column.go` line 91 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/87820#-NCX13M4vgw7EePZiL6p-r4-91:-NCrid9Z3wIGD3SSYNVn:bn54kz9) ([raw file](https://github.com/cockroachdb/cockroach/blob/bb67bade2e85203ab48eed44266aed6f87822fb2/pkg/sql/schemachanger/scplan/internal/rules/dep_drop_column.go#L91)):*
<details><summary><i>Previously, postamar (Marius Posta) wrote…</i></summary><blockquote>

Yes please. Could you wrap this clause in a function which takes a `nodeVars`? I think it's worth going the extra mile with type safety in these rule definitions for any clause used more than once or twice.
</blockquote></details>

Done. Added a method.
___
*[`pkg/sql/schemachanger/scplan/internal/rules/dep_drop_object.go` line 124 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/87820#-NCVcVyCSCpgpECY_u5J-r3-124:-NCrkgazE2QDg1O_h34g:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/872d0be2837480a526deaefd721de3c0a758ccdd/pkg/sql/schemachanger/scplan/internal/rules/dep_drop_object.go#L124)):*
<details><summary><i>Previously, postamar (Marius Posta) wrote…</i></summary><blockquote>

Can you replace this with a named rule? Something like `joinReferencedTypeIDInSlice(from, to, "typeDescID")`? Same for referenced sequences below.
</blockquote></details>

Done.
___
*[`pkg/sql/schemachanger/scplan/internal/rules/dep_drop_object.go` line 126 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/87820#-NCVcVyCSCpgpECY_u5J-r3-126:-NCrkhEI-X9O4HD9eI9P:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/872d0be2837480a526deaefd721de3c0a758ccdd/pkg/sql/schemachanger/scplan/internal/rules/dep_drop_object.go#L126)):*
<details><summary><i>Previously, postamar (Marius Posta) wrote…</i></summary><blockquote>

We already have a `not` function defined in `helpers.go` which takes a predicate and constructs its complement,  so you should also define an `or` combinator which builds a disjunction. It's worth it, it makes rule definitions easier to read, it's hard enough as it is.
</blockquote></details>

Done.
___
*[`pkg/sql/schemachanger/screl/attr.go` line 81 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/87820#-NCVcVyCSCpgpECY_u5W-r3-81:-NCrl6sn7Ogqc8pycNP5:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/872d0be2837480a526deaefd721de3c0a758ccdd/pkg/sql/schemachanger/screl/attr.go#L81)):*
<details><summary><i>Previously, postamar (Marius Posta) wrote…</i></summary><blockquote>

`s/ReferencedTypeDescIDs/ReferencedTypeIDs/`?
</blockquote></details>

Done.
___
*[`pkg/sql/schemachanger/screl/attr.go` line 82 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/87820#-NCVcVyCSCpgpECY_u5W-r3-82:-NCrl6Pu9a68C4EXx0yd:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/872d0be2837480a526deaefd721de3c0a758ccdd/pkg/sql/schemachanger/screl/attr.go#L82)):*
<details><summary><i>Previously, postamar (Marius Posta) wrote…</i></summary><blockquote>

nit: comments plz
</blockquote></details>

Done.
___
*[`pkg/sql/schemachanger/screl/compare.go` line 26 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/87820#-NCVcVyCSCpgpECY_u5Y-r3-26:-NCrnj5oDVgLj3cQSZgn:b-eq3leb) ([raw file](https://github.com/cockroachdb/cockroach/blob/872d0be2837480a526deaefd721de3c0a758ccdd/pkg/sql/schemachanger/screl/compare.go#L26)):*
<details><summary><i>Previously, postamar (Marius Posta) wrote…</i></summary><blockquote>

This means that `EqualElements` does not mean what one might assume. I think we've reached the point where we need to surface the notion of keying an entity in the screl model. It is, after all, a relational model. Until now the key was assumed to be the tuple formed by all attributes. This change makes it become all attributes minus the slice attributes. It works, but I find it somewhat unsatisfying. Exposing this notion of key would have the added benefit of making the string representation of elements more compact and also stable. I've found its instability in the face of changes to the attributes in the model to be quite annoying, in the past.

At the very least we should rename `EqualElements` to `EqualKeys` and `equalityAttrs` to `keyEqualityAttrs`.

</blockquote></details>

I renamed the function and added clearer commentary. 
___
*[`pkg/sql/schemachanger/rel/testdata/entitynode` line 10 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/87820#-NBlumtLM3Tq_GetAMF4-r2-10:-NCri7WL7bbZ--Ao_Iey:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/83426156d0635c2070e3a50dd22ab1d8903cbadc/pkg/sql/schemachanger/rel/testdata/entitynode#L10)):*
<details><summary><i>Previously, postamar (Marius Posta) wrote…</i></summary><blockquote>

Can you add a test case with a slice longer than 1 please?
</blockquote></details>

Done.

**Review by postamar — APPROVED** [review]

**Comment by ajwerner** [comment]
TFTR!

bors r+
