### PR TITLE
roachtestutil: limit GetDiskUsageInBytes retries

### LINKED ISSUE #134611: roachtest: import/tpch/nodes=8 failed [disk usage checker stuck]
roachtest.import/tpch/nodes=8 [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/17632465?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/17632465?buildTab=artifacts#/import/tpch/nodes=8) on release-24.3 @ [7252771de42bf0752052fae4f945c0e7a88d0ecd](https://github.com/cockroachdb/cockroach/commits/7252771de42bf0752052fae4f945c0e7a88d0ecd):

```
(test_runner.go:1316).runTest: test timed out (10h0m0s)
test artifacts and logs in: /artifacts/import/tpch/nodes=8/run_1
```

Parameters:
 - <code>ROACHTEST_arch=amd64</code>
 - <code>ROACHTEST_cloud=gce</code>
 - <code>ROACHTEST_coverageBuild=false</code>
 - <code>ROACHTEST_cpu=4</code>
 - <code>ROACHTEST_encrypted=false</code>
 - <code>ROACHTEST_fs=ext4</code>
 - <code>ROACHTEST_localSSD=true</code>
 - <code>ROACHTEST_runtimeAssertionsBuild=false</code>
 - <code>ROACHTEST_ssd=0</code>
<details><summary>Help</summary>
<p>

See: [roachtest README](https://github.com/cockroachdb/cockroach/blob/master/pkg/cmd/roachtest/README.md)

See: [How To Investigate \(internal\)](https://cockroachlabs.atlassian.net/l/c/SSSBr8c7)

See: [Grafana](https://go.crdb.dev/roachtest-grafana/teamcity-17632465/import-tpch-nodes-8/1730996879037/1731033494469)

</p>
</details>
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*import/tpch/nodes=8.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/bazci/githubpost/issues)

</sub>

Jira issue: CRDB-44165

### PR DESCRIPTION
**Pull request by DarrylWong**
Previously, this method would infinitely retry on non context cancelled errors. However, the disk usage runner uses a done channel to signal completion, rather than cancelling the context.

This change limits the amount of retries attempted, so the runner can check the done channel and exit.

Fixes: https://github.com/cockroachdb/cockroach/issues/134611
Epic: none
Release note: none

### CODE REVIEW

File: pkg/cmd/roachtest/roachtestutil/disk_usage.go [hunk 1]
```diff
@@ -133,34 +134,23 @@ func GetDiskUsageInBytes(
...
-		var err error
-		// `du` can warn if files get removed out from under it (which
-		// happens during RocksDB compactions, for example). Discard its
-		// stderr to avoid breaking Atoi later.
-		// TODO(bdarnell): Refactor this stack to not combine stdout and
-		// stderr so we don't need to do this (and the Warning check
-		// below).
+	var err error
+	// `du` can warn if files get removed out from under it (which
+	// happens during RocksDB compactions, for example). Discard its
```
Comment (srosenberg) [inline pkg/cmd/roachtest/roachtestutil/disk_usage.go:139]: Nit: `RocksDB` -> `pebble`.

File: pkg/cmd/roachtest/roachtestutil/disk_usage.go [hunk 2]
```diff
@@ -133,34 +134,23 @@ func GetDiskUsageInBytes(
...
+	// stderr to avoid breaking Atoi later.
+	// TODO(bdarnell): Refactor this stack to not combine stdout and
```
Comment (srosenberg) [inline pkg/cmd/roachtest/roachtestutil/disk_usage.go:141]: Can remove this TODO since it's no longer relevant.

**Comment by yuzefovich** [comment]
Nice find! Perhaps also consider backporting this fix? Thanks!

File: pkg/cmd/roachtest/roachtestutil/disk_usage.go [hunk 3]
```diff
@@ -133,34 +134,23 @@ func GetDiskUsageInBytes(
...
+	// stderr so we don't need to do this (and the Warning check
+	// below).
+	for r := retry.StartWithCtx(ctx, *install.DefaultRetryOpt); r.Next(); {
```
Comment (srosenberg) [inline pkg/cmd/roachtest/roachtestutil/disk_usage.go:144]: I didn't even know we have multiple versions of essentially the same operation. The test runner uses `saveDiskUsageToLogsDir` (from `collectArtifacts`), which uses the hardcoded `/mnt/data1` instead of `{store-dir}`. It seems like a further refactoring would pay dividends on having one version that's correct and reliable.

Comment (DarrylWong) [reply pkg/cmd/roachtest/roachtestutil/disk_usage.go:143]: Done. Although I had to stuff the `grep` and `>>` commands as args to the new helper, which is arguably a bit confusing that we allow the caller to do more than just "GetDiskUsage".

**Review by DarrylWong — COMMENTED** [review]
Reran `import/tpch/nodes=8` on my gceworker and test passed.

File: pkg/cmd/roachtest/test_runner.go [hunk 4]
```diff
@@ -1656,8 +1656,8 @@ func (r *testRunner) collectArtifacts(
 		t.L().PrintfCtx(ctx, "collecting cluster logs")
 		// Do this before collecting logs to make sure the file gets
 		// downloaded below.
-		if err := saveDiskUsageToLogsDir(ctx, c); err != nil {
-			t.L().Printf("failed to fetch disk uage summary: %s", err)
```
Comment (srosenberg) [inline pkg/cmd/roachtest/test_runner.go:1660]: Good catch!

File: pkg/cmd/roachtest/roachtestutil/disk_usage.go [hunk 5]
```diff
@@ -128,40 +129,41 @@ func NewDiskUsageTracker(
 	return &DiskUsageTracker{c: c, l: diskLogger}, nil
 }
 
-// GetDiskUsageInBytes does what's on the tin. nodeIdx starts at one.
```
Comment (srosenberg) [inline pkg/cmd/roachtest/roachtestutil/disk_usage.go:131]: Let's add a description... something of the form, "GetDiskUsageInBytes executes the command `du {store-dir}`. Optional `args` are appended."

File: pkg/cmd/roachtest/roachtestutil/disk_usage.go (hunk 3 above)
Comment (srosenberg) [reply pkg/cmd/roachtest/roachtestutil/disk_usage.go:143]: > which is arguably a bit confusing that we allow the caller to do more than just "GetDiskUsage".

Agreed. We don't really have an API for composing remote commands, which could make this cleaner. But it seems ok for now, considering the callers of `GetDiskUsage` aren't likely to change.

Comment (srosenberg) [reply pkg/cmd/roachtest/roachtestutil/disk_usage.go:143]: On second thought, `GetDiskUsage` isn't doing anything specific, really. We might as well "inline" it by replacing with a direct call to `RunWithDetails`.

File: pkg/cmd/roachtest/roachtestutil/disk_usage.go [hunk 6]
```diff
@@ -128,39 +128,23 @@ func NewDiskUsageTracker(
...
-		}
-
-		break
+	var err error
+	// Retry a few times since `du` can warn if files get removed out from under
+	// it (which happens during pebble compactions, for example).
+	result, err = c.RunWithDetailsSingleNode(
+		ctx,
+		logger,
+		option.WithNodes(c.Node(nodeIdx)).WithShouldRetryFn(install.AlwaysTrue),
```
Comment (DarrylWong) [inline pkg/cmd/roachtest/roachtestutil/disk_usage.go:143]: Realized I was completely misusing the `retry` package, and it wasn't actually retrying. Switched to the roachprod retry instead :) 

Want to double check my retry reasoning here though. We want to retry here since we are parsing the result and a stray warning can throw that off. We don't need to retry in `saveDiskUsageToLogsDir` since we are just writing to logs and the warnings are benign.

File: pkg/cmd/roachtest/roachtestutil/disk_usage.go [hunk 7]
```diff
@@ -128,39 +128,23 @@ func NewDiskUsageTracker(
 	return &DiskUsageTracker{c: c, l: diskLogger}, nil
 }
 
-// GetDiskUsageInBytes does what's on the tin. nodeIdx starts at one.
+// GetDiskUsageInBytes executes the command `du {store-dir}` on node `nodeIdx`.
+// Optional args are appended, so it can parse the result to bytes. nodeIdx starts at one.
```
Comment (srosenberg) [inline pkg/cmd/roachtest/roachtestutil/disk_usage.go:132]: No more args in the signature.

File: pkg/cmd/roachtest/roachtestutil/disk_usage.go (hunk 6 above)
Comment (srosenberg) [reply pkg/cmd/roachtest/roachtestutil/disk_usage.go:143]: > We want to retry here since we are parsing the result and a stray warning can throw that off. We don't need to retry in saveDiskUsageToLogsDir since we are just writing to logs and the warnings are benign.

Exactly! If `grep` fails to match a number, the entire command exits with an error, which would trigger a retry attempt.

**Review by srosenberg — APPROVED** [review]
LGTM. Thanks for refactoring!

**Comment by DarrylWong** [comment]
TFTR!

bors r=srosenberg
