### PR TITLE
sql: fix schema privileges on descriptor read

### LINKED ISSUE #65697: Converting database to schema leaves the schema in an unusable state
**Describe the problem**

Converting database to schema "succeeds" but is missing the `USAGE` permission for user `appuser` and adding the `USAGE` permission to the schema fails with the following error
```
ERROR: user appuser must not have DROP, SELECT, INSERT, DELETE, UPDATE privileges on system schema with ID=174
```

**To Reproduce**

Run the following script
```sql
---
CREATE USER appuser;

CREATE DATABASE maindb;
GRANT CREATE, DROP, SELECT, INSERT, DELETE, UPDATE ON DATABASE maindb TO appuser;
SET DATABASE TO maindb;

CREATE DATABASE test2;
GRANT CREATE, DROP, SELECT, INSERT, DELETE, UPDATE ON DATABASE test2 TO appuser;
CREATE TABLE test2.test_table(hello int);

ALTER DATABASE test2 CONVERT TO SCHEMA WITH PARENT maindb;
GRANT USAGE ON SCHEMA test2 TO appuser; -- fails here
```

**Expected behavior**
All statements should execute successfully.
The final result should be a database `maindb` with a schema `test2` and a table `test2.test_table` that is usable by user `appuser`.

**Environment:**
 - CockroachDB: v20.2.7
 - Server OS: Amazon Linux 2
 - Client app: `cockroach sql`

**Additional context**
Since the issue occurs after the database is converted to a schema, all tables under that schema are left in an unusable state as only admin users can access the tables and app users cannot be granted access.

### PR DESCRIPTION
**Pull request by RichardJCai**
Release note (bug fix): Previously a schema's privilege descriptor
could become corrupted upon executing ALTER DATABASE ...
CONVERT TO SCHEMA due to privileges that are invalid on a schema
being copied over to the schema rendering the schema inusable due
to invalid privileges.

Fixes #65697

### CODE REVIEW

File: pkg/sql/catalog/descpb/privilege.go [hunk 1]
```diff
@@ -249,6 +249,27 @@ func MaybeFixUsagePrivForTablesAndDBs(ptr **PrivilegeDescriptor) bool {
...
+// the schema may become unusable.
+func MaybeFixSchemaPrivileges(ptr **PrivilegeDescriptor) {
+	if *ptr == nil {
+		*ptr = &PrivilegeDescriptor{}
+	}
+	p := *ptr
+
+	validPrivs := privilege.GetValidPrivilegesForObject(privilege.Schema).ToBitField()
+
+	for i := range p.Users {
```
Comment (RichardJCai) [inline pkg/sql/catalog/descpb/privilege.go:266]: I couldn't think of a way to differentiate if this issue came specifically from `ALTER DATABASE ... CONVERT TO SCHEMA` or some other way.

I wonder if we should always just remove invalid privileges?

**Review by ajwerner — COMMENTED** [review]
Maybe annoying but can you write a more integration-level test where we go and write the corruption into a schema descriptor on disk and make sure everything is still happy? You don't need to backport that test to 20.2 if it's painful. 

> Reviewed 1 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/65750#-:-Maeo5R7DzzCA4-lzI3K:bv193af)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @RichardJCai)

___
*[pkg/sql/catalog/descpb/privilege.go, line 266 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/65750#-MaefSyxfVyKT1Vh4e5R-r1-266:-MaenHf96l-D70HbMuQP:b-bdbemk) ([raw file](https://github.com/cockroachdb/cockroach/blob/aabf0829ec7e17143dd17b7e3d6ba82ea6cc2d52/pkg/sql/catalog/descpb/privilege.go#L266)):*
<details><summary><i>Previously, RichardJCai (Richard Cai) wrote…</i></summary><blockquote>

I couldn't think of a way to differentiate if this issue came specifically from `ALTER DATABASE ... CONVERT TO SCHEMA` or some other way.

I wonder if we should always just remove invalid privileges?
</blockquote></details>

I think it's fine to always remove them. Given we don't support the idea of pseudo-default privileges on schemas, we're stuck with just throwing these privileges away.
___
*[pkg/sql/catalog/descpb/privilege.go, line 269 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/65750#-Maen_5E6GNYHamrOQ1V:-Maen_5E6GNYHamrOQ1W:b-qedz7o) ([raw file](https://github.com/cockroachdb/cockroach/blob/aabf0829ec7e17143dd17b7e3d6ba82ea6cc2d52/pkg/sql/catalog/descpb/privilege.go#L269)):*
> ```
> 		// Users is a slice of values, we need pointers to make them mutable.
> 		userPrivileges := &p.Users[i]
> 		userPrivileges.Privileges &= validPrivs
> ```
If you're going to write out this whole sentence explaining why you're taking the address, might as well just do:

```go
p.Users[i].Privileges &= validPrivs
```

**Review by RichardJCai — COMMENTED** [review]
What's the best way to do this integration-level test? I'm thinking we can do a restore test or a versionupgrade roachtest. 

Is there an alternative / better way than these two?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/65750#-:-Maj_OlvA83P_PiOavXL:b-b0xtaq)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @RichardJCai)

**Review by ajwerner — COMMENTED** [review]
I was thinking something much much simpler. Just create a schema descriptor, then in a `descs.Txn` give it the bogus privileges that would have resulted from the relevant bug and then make sure you can still access stuff in the schema. Shouldn't be a very big test. 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/65750#-:-MajfjpJ6iePqUWBSJzN:b-fu07uf)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @RichardJCai)

**Review by ajwerner — APPROVED** [review]
:lgtm_strong: mod the doctor test that's now borked 

> Reviewed 2 of 3 files at r1, 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/65750#-:-MapiZ6vElRsxmgeggNH:b732vox)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @RichardJCai)

File: pkg/sql/doctor/doctor_test.go [hunk 2]
```diff
@@ -97,10 +97,14 @@ func TestExamineDescriptors(t *testing.T) {
 		tbl.State = descpb.DescriptorState_DROP
 	}
 
-	inSchemaValidTableDesc := protoutil.Clone(validTableDesc).(*descpb.Descriptor)
+	// Use 51 as the Schema ID, we do not want to use a reserved system ID (1-49)
```
Comment (RichardJCai) [inline pkg/sql/doctor/doctor_test.go:100]: Had to change schema ids to 51 so it wouldn't be checked for system privileges.

Our SystemAllowedPrivileges check is a bit weird since it doesn't check object type just id. I don't think we have system schemas or system types in this context.

**Comment by RichardJCai** [comment]
Thanks for the review!

bors r=ajwerner
