### PR TITLE
sql: regtype casts now use the full type parser

### LINKED ISSUE #3: Error when creating table
I'm using the latest activerecord-cockroachdb-adapter gem (0.1.1).

This is my table in the migration (generated by devise):
```
  def change
    create_table :users do |t|
      ## Database authenticatable
      t.string :email,              null: false, default: ""
      t.string :encrypted_password, null: false, default: ""

      ## Recoverable
      t.string   :reset_password_token
      t.datetime :reset_password_sent_at

      ## Rememberable
      t.datetime :remember_created_at

      ## Trackable
      t.integer  :sign_in_count, default: 0, null: false
      t.datetime :current_sign_in_at
      t.datetime :last_sign_in_at
      t.string   :current_sign_in_ip
      t.string   :last_sign_in_ip

      ## Confirmable
      # t.string   :confirmation_token
      # t.datetime :confirmed_at
      # t.datetime :confirmation_sent_at
      # t.string   :unconfirmed_email # Only if using reconfirmable

      ## Lockable
      # t.integer  :failed_attempts, default: 0, null: false # Only if lock strategy is :failed_attempts
      # t.string   :unlock_token # Only if unlock strategy is :email or :both
      # t.datetime :locked_at

      t.boolean :premium, default: false

      t.timestamps null: false
    end

    add_index :users, :email,                unique: true
    add_index :users, :reset_password_token, unique: true
    # add_index :users, :confirmation_token,   unique: true
    # add_index :users, :unlock_token,         unique: true
  end
```

When I try to run the migration I get 
```
PG::InternalError: ERROR:  type 'character varying' does not exist
: SELECT 'character varying'::regtype::oid
```

Heres the full stacktrace:
```
$ rake db:migrate
== 20170406053035 DeviseCreateUsers: migrating ================================
-- create_table(:users)
rake aborted!
StandardError: An error has occurred, this and all later migrations canceled:

PG::InternalError: ERROR:  type 'character varying' does not exist
: SELECT 'character varying'::regtype::oid
/Users/adam/.rvm/gems/ruby-2.4.0/gems/activerecord-5.0.2/lib/active_record/connection_adapters/postgresql/database_statements.rb:98:in `async_exec'
/Users/adam/.rvm/gems/ruby-2.4.0/gems/activerecord-5.0.2/lib/active_record/connection_adapters/postgresql/database_statements.rb:98:in `block in execute'
/Users/adam/.rvm/gems/ruby-2.4.0/gems/activerecord-5.0.2/lib/active_record/connection_adapters/abstract_adapter.rb:589:in `block in log'
/Users/adam/.rvm/gems/ruby-2.4.0/gems/activesupport-5.0.2/lib/active_support/notifications/instrumenter.rb:21:in `instrument'
/Users/adam/.rvm/gems/ruby-2.4.0/gems/activerecord-5.0.2/lib/active_record/connection_adapters/abstract_adapter.rb:583:in `log'
/Users/adam/.rvm/gems/ruby-2.4.0/gems/activerecord-5.0.2/lib/active_record/connection_adapters/postgresql/database_statements.rb:97:in `execute'
/Users/adam/.rvm/gems/ruby-2.4.0/gems/activerecord-5.0.2/lib/active_record/connection_adapters/postgresql_adapter.rb:384:in `lookup_cast_type'
/Users/adam/.rvm/gems/ruby-2.4.0/gems/activerecord-5.0.2/lib/active_record/connection_adapters/abstract/quoting.rb:110:in `quote_default_expression'
/Users/adam/.rvm/gems/ruby-2.4.0/gems/activerecord-5.0.2/lib/active_record/connection_adapters/postgresql/quoting.rb:67:in `quote_default_expression'
/Users/adam/.rvm/gems/ruby-2.4.0/gems/activerecord-5.0.2/lib/active_record/connection_adapters/abstract/schema_creation.rb:17:in `quote_default_expression'
/Users/adam/.rvm/gems/ruby-2.4.0/gems/activerecord-5.0.2/lib/active_record/connection_adapters/abstract/schema_creation.rb:113:in `add_column_options!'
/Users/adam/.rvm/gems/ruby-2.4.0/gems/activerecord-5.0.2/lib/active_record/connection_adapters/postgresql/schema_statements.rb:18:in `add_column_options!'
/Users/adam/.rvm/gems/ruby-2.4.0/gems/activerecord-5.0.2/lib/active_record/connection_adapters/abstract/schema_creation.rb:34:in `visit_ColumnDefinition'
/Users/adam/.rvm/gems/ruby-2.4.0/gems/activerecord-5.0.2/lib/active_record/connection_adapters/postgresql/schema_statements.rb:11:in `visit_ColumnDefinition'
/Users/adam/.rvm/gems/ruby-2.4.0/gems/activerecord-5.0.2/lib/active_record/connection_adapters/abstract/schema_creation.rb:14:in `accept'
/Users/adam/.rvm/gems/ruby-2.4.0/gems/activerecord-5.0.2/lib/active_record/connection_adapters/abstract/schema_creation.rb:45:in `block in visit_TableDefinition'
/Users/adam/.rvm/gems/ruby-2.4.0/gems/activerecord-5.0.2/lib/active_record/connection_adapters/abstract/schema_creation.rb:45:in `map'
/Users/adam/.rvm/gems/ruby-2.4.0/gems/activerecord-5.0.2/lib/active_record/connection_adapters/abstract/schema_creation.rb:45:in `visit_TableDefinition'
/Users/adam/.rvm/gems/ruby-2.4.0/gems/activerecord-5.0.2/lib/active_record/connection_adapters/abstract/schema_creation.rb:14:in `accept'
/Users/adam/.rvm/gems/ruby-2.4.0/gems/activerecord-5.0.2/lib/active_record/connection_adapters/abstract/schema_statements.rb:278:in `create_table'
/Users/adam/.rvm/gems/ruby-2.4.0/gems/activerecord-5.0.2/lib/active_record/migration.rb:846:in `block in method_missing'
/Users/adam/.rvm/gems/ruby-2.4.0/gems/activerecord-5.0.2/lib/active_record/migration.rb:815:in `block in say_with_time'
/Users/adam/.rvm/gems/ruby-2.4.0/gems/activerecord-5.0.2/lib/active_record/migration.rb:815:in `say_with_time'
/Users/adam/.rvm/gems/ruby-2.4.0/gems/activerecord-5.0.2/lib/active_record/migration.rb:835:in `method_missing'
/Users/adam/Dropbox (Personal)/Projects/myproject/db/migrate/20170406053035_devise_create_users.rb:3:in `change'
/Users/adam/.rvm/gems/ruby-2.4.0/gems/activerecord-5.0.2/lib/active_record/migration.rb:789:in `exec_migration'
/Users/adam/.rvm/gems/ruby-2.4.0/gems/activerecord-5.0.2/lib/active_record/migration.rb:773:in `block (2 levels) in migrate'
/Users/adam/.rvm/gems/ruby-2.4.0/gems/activerecord-5.0.2/lib/active_record/migration.rb:772:in `block in migrate'
/Users/adam/.rvm/gems/ruby-2.4.0/gems/activerecord-5.0.2/lib/active_record/connection_adapters/abstract/connection_pool.rb:398:in `with_connection'
/Users/adam/.rvm/gems/ruby-2.4.0/gems/activerecord-5.0.2/lib/active_record/migration.rb:771:in `migrate'
/Users/adam/.rvm/gems/ruby-2.4.0/gems/activerecord-5.0.2/lib/active_record/migration.rb:951:in `migrate'
/Users/adam/.rvm/gems/ruby-2.4.0/gems/activerecord-5.0.2/lib/active_record/migration.rb:1214:in `block in execute_migration_in_transaction'
/Users/adam/.rvm/gems/ruby-2.4.0/gems/activerecord-5.0.2/lib/active_record/migration.rb:1282:in `block in ddl_transaction'
/Users/adam/.rvm/gems/ruby-2.4.0/gems/activerecord-5.0.2/lib/active_record/connection_adapters/abstract/database_statements.rb:232:in `block in transaction'
/Users/adam/.rvm/gems/ruby-2.4.0/gems/activerecord-5.0.2/lib/active_record/connection_adapters/abstract/transaction.rb:189:in `within_new_transaction'
/Users/adam/.rvm/gems/ruby-2.4.0/gems/activerecord-5.0.2/lib/active_record/connection_adapters/abstract/database_statements.rb:232:in `transaction'
/Users/adam/.rvm/gems/ruby-2.4.0/gems/activerecord-5.0.2/lib/active_record/transactions.rb:211:in `transaction'
/Users/adam/.rvm/gems/ruby-2.4.0/gems/activerecord-5.0.2/lib/active_record/migration.rb:1282:in `ddl_transaction'
/Users/adam/.rvm/gems/ruby-2.4.0/gems/activerecord-5.0.2/lib/active_record/migration.rb:1213:in `execute_migration_in_transaction'
/Users/adam/.rvm/gems/ruby-2.4.0/gems/activerecord-5.0.2/lib/active_record/migration.rb:1185:in `block in migrate_without_lock'
/Users/adam/.rvm/gems/ruby-2.4.0/gems/activerecord-5.0.2/lib/active_record/migration.rb:1184:in `each'
/Users/adam/.rvm/gems/ruby-2.4.0/gems/activerecord-5.0.2/lib/active_record/migration.rb:1184:in `migrate_without_lock'
/Users/adam/.rvm/gems/ruby-2.4.0/gems/activerecord-5.0.2/lib/active_record/migration.rb:1132:in `block in migrate'
/Users/adam/.rvm/gems/ruby-2.4.0/gems/activerecord-5.0.2/lib/active_record/migration.rb:1301:in `with_advisory_lock'
/Users/adam/.rvm/gems/ruby-2.4.0/gems/activerecord-5.0.2/lib/active_record/migration.rb:1132:in `migrate'
/Users/adam/.rvm/gems/ruby-2.4.0/gems/activerecord-5.0.2/lib/active_record/migration.rb:1006:in `up'
/Users/adam/.rvm/gems/ruby-2.4.0/gems/activerecord-5.0.2/lib/active_record/migration.rb:984:in `migrate'
/Users/adam/.rvm/gems/ruby-2.4.0/gems/activerecord-5.0.2/lib/active_record/tasks/database_tasks.rb:161:in `migrate'
/Users/adam/.rvm/gems/ruby-2.4.0/gems/activerecord-5.0.2/lib/active_record/railties/databases.rake:58:in `block (2 levels) in <top (required)>'
/Users/adam/.rvm/gems/ruby-2.4.0@global/gems/rake-12.0.0/exe/rake:27:in `<top (required)>'
ActiveRecord::StatementInvalid: PG::InternalError: ERROR:  type 'character varying' does not exist
: SELECT 'character varying'::regtype::oid
/Users/adam/.rvm/gems/ruby-2.4.0/gems/activerecord-5.0.2/lib/active_record/connection_adapters/postgresql/database_statements.rb:98:in `async_exec'
/Users/adam/.rvm/gems/ruby-2.4.0/gems/activerecord-5.0.2/lib/active_record/connection_adapters/postgresql/database_statements.rb:98:in `block in execute'
/Users/adam/.rvm/gems/ruby-2.4.0/gems/activerecord-5.0.2/lib/active_record/connection_adapters/abstract_adapter.rb:589:in `block in log'
/Users/adam/.rvm/gems/ruby-2.4.0/gems/activesupport-5.0.2/lib/active_support/notifications/instrumenter.rb:21:in `instrument'
/Users/adam/.rvm/gems/ruby-2.4.0/gems/activerecord-5.0.2/lib/active_record/connection_adapters/abstract_adapter.rb:583:in `log'
/Users/adam/.rvm/gems/ruby-2.4.0/gems/activerecord-5.0.2/lib/active_record/connection_adapters/postgresql/database_statements.rb:97:in `execute'
/Users/adam/.rvm/gems/ruby-2.4.0/gems/activerecord-5.0.2/lib/active_record/connection_adapters/postgresql_adapter.rb:384:in `lookup_cast_type'
/Users/adam/.rvm/gems/ruby-2.4.0/gems/activerecord-5.0.2/lib/active_record/connection_adapters/abstract/quoting.rb:110:in `quote_default_expression'
/Users/adam/.rvm/gems/ruby-2.4.0/gems/activerecord-5.0.2/lib/active_record/connection_adapters/postgresql/quoting.rb:67:in `quote_default_expression'
/Users/adam/.rvm/gems/ruby-2.4.0/gems/activerecord-5.0.2/lib/active_record/connection_adapters/abstract/schema_creation.rb:17:in `quote_default_expression'
/Users/adam/.rvm/gems/ruby-2.4.0/gems/activerecord-5.0.2/lib/active_record/connection_adapters/abstract/schema_creation.rb:113:in `add_column_options!'
/Users/adam/.rvm/gems/ruby-2.4.0/gems/activerecord-5.0.2/lib/active_record/connection_adapters/postgresql/schema_statements.rb:18:in `add_column_options!'
/Users/adam/.rvm/gems/ruby-2.4.0/gems/activerecord-5.0.2/lib/active_record/connection_adapters/abstract/schema_creation.rb:34:in `visit_ColumnDefinition'
/Users/adam/.rvm/gems/ruby-2.4.0/gems/activerecord-5.0.2/lib/active_record/connection_adapters/postgresql/schema_statements.rb:11:in `visit_ColumnDefinition'
/Users/adam/.rvm/gems/ruby-2.4.0/gems/activerecord-5.0.2/lib/active_record/connection_adapters/abstract/schema_creation.rb:14:in `accept'
/Users/adam/.rvm/gems/ruby-2.4.0/gems/activerecord-5.0.2/lib/active_record/connection_adapters/abstract/schema_creation.rb:45:in `block in visit_TableDefinition'
/Users/adam/.rvm/gems/ruby-2.4.0/gems/activerecord-5.0.2/lib/active_record/connection_adapters/abstract/schema_creation.rb:45:in `map'
/Users/adam/.rvm/gems/ruby-2.4.0/gems/activerecord-5.0.2/lib/active_record/connection_adapters/abstract/schema_creation.rb:45:in `visit_TableDefinition'
/Users/adam/.rvm/gems/ruby-2.4.0/gems/activerecord-5.0.2/lib/active_record/connection_adapters/abstract/schema_creation.rb:14:in `accept'
/Users/adam/.rvm/gems/ruby-2.4.0/gems/activerecord-5.0.2/lib/active_record/connection_adapters/abstract/schema_statements.rb:278:in `create_table'
/Users/adam/.rvm/gems/ruby-2.4.0/gems/activerecord-5.0.2/lib/active_record/migration.rb:846:in `block in method_missing'
/Users/adam/.rvm/gems/ruby-2.4.0/gems/activerecord-5.0.2/lib/active_record/migration.rb:815:in `block in say_with_time'
/Users/adam/.rvm/gems/ruby-2.4.0/gems/activerecord-5.0.2/lib/active_record/migration.rb:815:in `say_with_time'
/Users/adam/.rvm/gems/ruby-2.4.0/gems/activerecord-5.0.2/lib/active_record/migration.rb:835:in `method_missing'
/Users/adam/Dropbox (Personal)/Projects/myproject/db/migrate/20170406053035_devise_create_users.rb:3:in `change'
/Users/adam/.rvm/gems/ruby-2.4.0/gems/activerecord-5.0.2/lib/active_record/migration.rb:789:in `exec_migration'
/Users/adam/.rvm/gems/ruby-2.4.0/gems/activerecord-5.0.2/lib/active_record/migration.rb:773:in `block (2 levels) in migrate'
/Users/adam/.rvm/gems/ruby-2.4.0/gems/activerecord-5.0.2/lib/active_record/migration.rb:772:in `block in migrate'
/Users/adam/.rvm/gems/ruby-2.4.0/gems/activerecord-5.0.2/lib/active_record/connection_adapters/abstract/connection_pool.rb:398:in `with_connection'
/Users/adam/.rvm/gems/ruby-2.4.0/gems/activerecord-5.0.2/lib/active_record/migration.rb:771:in `migrate'
/Users/adam/.rvm/gems/ruby-2.4.0/gems/activerecord-5.0.2/lib/active_record/migration.rb:951:in `migrate'
/Users/adam/.rvm/gems/ruby-2.4.0/gems/activerecord-5.0.2/lib/active_record/migration.rb:1214:in `block in execute_migration_in_transaction'
/Users/adam/.rvm/gems/ruby-2.4.0/gems/activerecord-5.0.2/lib/active_record/migration.rb:1282:in `block in ddl_transaction'
/Users/adam/.rvm/gems/ruby-2.4.0/gems/activerecord-5.0.2/lib/active_record/connection_adapters/abstract/database_statements.rb:232:in `block in transaction'
/Users/adam/.rvm/gems/ruby-2.4.0/gems/activerecord-5.0.2/lib/active_record/connection_adapters/abstract/transaction.rb:189:in `within_new_transaction'
/Users/adam/.rvm/gems/ruby-2.4.0/gems/activerecord-5.0.2/lib/active_record/connection_adapters/abstract/database_statements.rb:232:in `transaction'
/Users/adam/.rvm/gems/ruby-2.4.0/gems/activerecord-5.0.2/lib/active_record/transactions.rb:211:in `transaction'
/Users/adam/.rvm/gems/ruby-2.4.0/gems/activerecord-5.0.2/lib/active_record/migration.rb:1282:in `ddl_transaction'
/Users/adam/.rvm/gems/ruby-2.4.0/gems/activerecord-5.0.2/lib/active_record/migration.rb:1213:in `execute_migration_in_transaction'
/Users/adam/.rvm/gems/ruby-2.4.0/gems/activerecord-5.0.2/lib/active_record/migration.rb:1185:in `block in migrate_without_lock'
/Users/adam/.rvm/gems/ruby-2.4.0/gems/activerecord-5.0.2/lib/active_record/migration.rb:1184:in `each'
/Users/adam/.rvm/gems/ruby-2.4.0/gems/activerecord-5.0.2/lib/active_record/migration.rb:1184:in `migrate_without_lock'
/Users/adam/.rvm/gems/ruby-2.4.0/gems/activerecord-5.0.2/lib/active_record/migration.rb:1132:in `block in migrate'
/Users/adam/.rvm/gems/ruby-2.4.0/gems/activerecord-5.0.2/lib/active_record/migration.rb:1301:in `with_advisory_lock'
/Users/adam/.rvm/gems/ruby-2.4.0/gems/activerecord-5.0.2/lib/active_record/migration.rb:1132:in `migrate'
/Users/adam/.rvm/gems/ruby-2.4.0/gems/activerecord-5.0.2/lib/active_record/migration.rb:1006:in `up'
/Users/adam/.rvm/gems/ruby-2.4.0/gems/activerecord-5.0.2/lib/active_record/migration.rb:984:in `migrate'
/Users/adam/.rvm/gems/ruby-2.4.0/gems/activerecord-5.0.2/lib/active_record/tasks/database_tasks.rb:161:in `migrate'
/Users/adam/.rvm/gems/ruby-2.4.0/gems/activerecord-5.0.2/lib/active_record/railties/databases.rake:58:in `block (2 levels) in <top (required)>'
/Users/adam/.rvm/gems/ruby-2.4.0@global/gems/rake-12.0.0/exe/rake:27:in `<top (required)>'
PG::InternalError: ERROR:  type 'character varying' does not exist
/Users/adam/.rvm/gems/ruby-2.4.0/gems/activerecord-5.0.2/lib/active_record/connection_adapters/postgresql/database_statements.rb:98:in `async_exec'
/Users/adam/.rvm/gems/ruby-2.4.0/gems/activerecord-5.0.2/lib/active_record/connection_adapters/postgresql/database_statements.rb:98:in `block in execute'
/Users/adam/.rvm/gems/ruby-2.4.0/gems/activerecord-5.0.2/lib/active_record/connection_adapters/abstract_adapter.rb:589:in `block in log'
/Users/adam/.rvm/gems/ruby-2.4.0/gems/activesupport-5.0.2/lib/active_support/notifications/instrumenter.rb:21:in `instrument'
/Users/adam/.rvm/gems/ruby-2.4.0/gems/activerecord-5.0.2/lib/active_record/connection_adapters/abstract_adapter.rb:583:in `log'
/Users/adam/.rvm/gems/ruby-2.4.0/gems/activerecord-5.0.2/lib/active_record/connection_adapters/postgresql/database_statements.rb:97:in `execute'
/Users/adam/.rvm/gems/ruby-2.4.0/gems/activerecord-5.0.2/lib/active_record/connection_adapters/postgresql_adapter.rb:384:in `lookup_cast_type'
/Users/adam/.rvm/gems/ruby-2.4.0/gems/activerecord-5.0.2/lib/active_record/connection_adapters/abstract/quoting.rb:110:in `quote_default_expression'
/Users/adam/.rvm/gems/ruby-2.4.0/gems/activerecord-5.0.2/lib/active_record/connection_adapters/postgresql/quoting.rb:67:in `quote_default_expression'
/Users/adam/.rvm/gems/ruby-2.4.0/gems/activerecord-5.0.2/lib/active_record/connection_adapters/abstract/schema_creation.rb:17:in `quote_default_expression'


/Users/adam/.rvm/gems/ruby-2.4.0/gems/activerecord-5.0.2/lib/active_record/connection_adapters/abstract/schema_creation.rb:113:in `add_column_options!'
/Users/adam/.rvm/gems/ruby-2.4.0/gems/activerecord-5.0.2/lib/active_record/connection_adapters/postgresql/schema_statements.rb:18:in `add_column_options!'
/Users/adam/.rvm/gems/ruby-2.4.0/gems/activerecord-5.0.2/lib/active_record/connection_adapters/abstract/schema_creation.rb:34:in `visit_ColumnDefinition'
/Users/adam/.rvm/gems/ruby-2.4.0/gems/activerecord-5.0.2/lib/active_record/connection_adapters/postgresql/schema_statements.rb:11:in `visit_ColumnDefinition'
/Users/adam/.rvm/gems/ruby-2.4.0/gems/activerecord-5.0.2/lib/active_record/connection_adapters/abstract/schema_creation.rb:14:in `accept'
/Users/adam/.rvm/gems/ruby-2.4.0/gems/activerecord-5.0.2/lib/active_record/connection_adapters/abstract/schema_creation.rb:45:in `block in visit_TableDefinition'
/Users/adam/.rvm/gems/ruby-2.4.0/gems/activerecord-5.0.2/lib/active_record/connection_adapters/abstract/schema_creation.rb:45:in `map'
/Users/adam/.rvm/gems/ruby-2.4.0/gems/activerecord-5.0.2/lib/active_record/connection_adapters/abstract/schema_creation.rb:45:in `visit_TableDefinition'
/Users/adam/.rvm/gems/ruby-2.4.0/gems/activerecord-5.0.2/lib/active_record/connection_adapters/abstract/schema_creation.rb:14:in `accept'
/Users/adam/.rvm/gems/ruby-2.4.0/gems/activerecord-5.0.2/lib/active_record/connection_adapters/abstract/schema_statements.rb:278:in `create_table'
/Users/adam/.rvm/gems/ruby-2.4.0/gems/activerecord-5.0.2/lib/active_record/migration.rb:846:in `block in method_missing'
/Users/adam/.rvm/gems/ruby-2.4.0/gems/activerecord-5.0.2/lib/active_record/migration.rb:815:in `block in say_with_time'
/Users/adam/.rvm/gems/ruby-2.4.0/gems/activerecord-5.0.2/lib/active_record/migration.rb:815:in `say_with_time'
/Users/adam/.rvm/gems/ruby-2.4.0/gems/activerecord-5.0.2/lib/active_record/migration.rb:835:in `method_missing'
/Users/adam/Dropbox (Personal)/Projects/myproject/db/migrate/20170406053035_devise_create_users.rb:3:in `change'
/Users/adam/.rvm/gems/ruby-2.4.0/gems/activerecord-5.0.2/lib/active_record/migration.rb:789:in `exec_migration'
/Users/adam/.rvm/gems/ruby-2.4.0/gems/activerecord-5.0.2/lib/active_record/migration.rb:773:in `block (2 levels) in migrate'
/Users/adam/.rvm/gems/ruby-2.4.0/gems/activerecord-5.0.2/lib/active_record/migration.rb:772:in `block in migrate'
/Users/adam/.rvm/gems/ruby-2.4.0/gems/activerecord-5.0.2/lib/active_record/connection_adapters/abstract/connection_pool.rb:398:in `with_connection'
/Users/adam/.rvm/gems/ruby-2.4.0/gems/activerecord-5.0.2/lib/active_record/migration.rb:771:in `migrate'
/Users/adam/.rvm/gems/ruby-2.4.0/gems/activerecord-5.0.2/lib/active_record/migration.rb:951:in `migrate'
/Users/adam/.rvm/gems/ruby-2.4.0/gems/activerecord-5.0.2/lib/active_record/migration.rb:1214:in `block in execute_migration_in_transaction'
/Users/adam/.rvm/gems/ruby-2.4.0/gems/activerecord-5.0.2/lib/active_record/migration.rb:1282:in `block in ddl_transaction'
/Users/adam/.rvm/gems/ruby-2.4.0/gems/activerecord-5.0.2/lib/active_record/connection_adapters/abstract/database_statements.rb:232:in `block in transaction'
/Users/adam/.rvm/gems/ruby-2.4.0/gems/activerecord-5.0.2/lib/active_record/connection_adapters/abstract/transaction.rb:189:in `within_new_transaction'
/Users/adam/.rvm/gems/ruby-2.4.0/gems/activerecord-5.0.2/lib/active_record/connection_adapters/abstract/database_statements.rb:232:in `transaction'
/Users/adam/.rvm/gems/ruby-2.4.0/gems/activerecord-5.0.2/lib/active_record/transactions.rb:211:in `transaction'
/Users/adam/.rvm/gems/ruby-2.4.0/gems/activerecord-5.0.2/lib/active_record/migration.rb:1282:in `ddl_transaction'
/Users/adam/.rvm/gems/ruby-2.4.0/gems/activerecord-5.0.2/lib/active_record/migration.rb:1213:in `execute_migration_in_transaction'
/Users/adam/.rvm/gems/ruby-2.4.0/gems/activerecord-5.0.2/lib/active_record/migration.rb:1185:in `block in migrate_without_lock'
/Users/adam/.rvm/gems/ruby-2.4.0/gems/activerecord-5.0.2/lib/active_record/migration.rb:1184:in `each'
/Users/adam/.rvm/gems/ruby-2.4.0/gems/activerecord-5.0.2/lib/active_record/migration.rb:1184:in `migrate_without_lock'
/Users/adam/.rvm/gems/ruby-2.4.0/gems/activerecord-5.0.2/lib/active_record/migration.rb:1132:in `block in migrate'
/Users/adam/.rvm/gems/ruby-2.4.0/gems/activerecord-5.0.2/lib/active_record/migration.rb:1301:in `with_advisory_lock'
/Users/adam/.rvm/gems/ruby-2.4.0/gems/activerecord-5.0.2/lib/active_record/migration.rb:1132:in `migrate'
/Users/adam/.rvm/gems/ruby-2.4.0/gems/activerecord-5.0.2/lib/active_record/migration.rb:1006:in `up'
/Users/adam/.rvm/gems/ruby-2.4.0/gems/activerecord-5.0.2/lib/active_record/migration.rb:984:in `migrate'
/Users/adam/.rvm/gems/ruby-2.4.0/gems/activerecord-5.0.2/lib/active_record/tasks/database_tasks.rb:161:in `migrate'
/Users/adam/.rvm/gems/ruby-2.4.0/gems/activerecord-5.0.2/lib/active_record/railties/databases.rake:58:in `block (2 levels) in <top (required)>'
/Users/adam/.rvm/gems/ruby-2.4.0@global/gems/rake-12.0.0/exe/rake:27:in `<top (required)>'
Tasks: TOP => db:migrate
(See full trace by running task with --trace)
```

### LINKED ISSUE #13993: sql: `SELECT 'decimal(18,2)'::regtype::oid` no worky
Discovered when adding a default value to a column in a rails app:
```
    create_table :orders do |t|
      t.decimal :subtotal, precision: 18, scale: 2, null: false, default: 0
    end
```

Somehow, this resulted in AR issuing the query:
```
SELECT 'decimal(18,2)'::regtype::oid
```
which came back with
```
PG::InternalError: ERROR:  type 'decimal(18,2)' does not exist
```

This query works in PG.

I've also confirmed that `decimal(18,2)` is indeed a type in CRDB:
```
root@:26257/company_activerecord> CREATE TABLE foo (id int, value decimal(18,2));
CREATE TABLE
root@:26257/company_activerecord> select * from foo;
+----+-------+
| id | value |
+----+-------+
+----+-------+
(0 rows)
```

### PR DESCRIPTION
**Pull request by jordanlewis**
Previously, string casts to `regtype` such as `'foo'::regtype` used a custom
parser to match the string with the correct type OID. This led to a few
problems, such as missing the mapping for longer type names such as
`character varying` as well as improperly parsing parameterized types
such as `decimal(10,2)`.

Rather than fix our separate parser, we now just delegate this type
parsing to the full SQL parser and interpret the results.

If our standard type parser fails, we fall back to the previous method
of searching `pg_type`. That's required since we don't provide syntax for
every type whose OID we understand - such as `float4`.

Fixes #13993.
Fixes https://github.com/cockroachdb/activerecord-cockroachdb-adapter/issues/3.

### CODE REVIEW

File: pkg/sql/parser/parse.go [hunk 1]
```diff
@@ -153,6 +153,33 @@ func ParseTableName(sql string) (*TableName, error) {
 	return rename.Name.Normalize()
 }
 
+// ParseType parses a column type.
+func ParseType(sql string) (CastTargetType, error) {
+	stmt, err := ParseOne(fmt.Sprintf("SELECT 1::%s", sql))
```
Comment (knz) [inline pkg/sql/parser/parse.go]: reuse `parser.ParseExpr`

**Review by knz — APPROVED** [review]
LGTM modulo simplification of ParseType

File: pkg/sql/parser/parse.go (hunk 1 above)
Comment (jordanlewis) [inline pkg/sql/parser/parse.go]: Good point, done

**Comment by knz** [comment]
:+1:

**Comment by jordanlewis** [comment]
BTW, working on this PR gave me an idea for how to solve #12481, #16395 and other related issues in a unified way.

Postgres has an extra rule for types in their parser that we don't - a catchall rule that indicates a type that isn't covered by the SQL standard. We could easily add a rule like that to our parser and have it simply look up the name in our `pg_type` implementation to find the matching OID.

That would instantly provide support for all of the types that we half-support like `int4` and `float4`, and also allow us to easily support namespaced types.

**Comment by knz** [comment]
do you want to make a prototype in a separate PR? we can then argue over code
