### PR TITLE
roachtest/tpccbench: increase HAProxy connection limit

### LINKED ISSUE #41027: roachtest: tpccbench/nodes=9/cpu=4/chaos/partition failed
SHA: https://github.com/cockroachdb/cockroach/commits/6b14c0aa3ed1b4ba6d5f937e9352c5383afe1c37

Parameters:

To repro, try:

```
# Don't forget to check out a clean suitable branch and experiment with the
# stress invocation until the desired results present themselves. For example,
# using stress instead of stressrace and passing the '-p' stressflag which
# controls concurrency.
./scripts/gceworker.sh start && ./scripts/gceworker.sh mosh
cd ~/go/src/github.com/cockroachdb/cockroach && \
stdbuf -oL -eL \
make stressrace TESTS=tpccbench/nodes=9/cpu=4/chaos/partition PKG=roachtest TESTTIMEOUT=5m STRESSFLAGS='-maxtime 20m -timeout 10m' 2>&1 | tee /tmp/stress.log
```

Failed test: https://teamcity.cockroachdb.com/viewLog.html?buildId=1502387&tab=artifacts#/tpccbench/nodes=9/cpu=4/chaos/partition

```
The test failed on branch=provisional_201909231358_v19.1.5, cloud=gce:
test artifacts and logs in: /home/agent/work/.go/src/github.com/cockroachdb/cockroach/artifacts/20190923-1502387/tpccbench/nodes=9/cpu=4/chaos/partition/run_1
	test_runner.go:704: test timed out (10h0m0s)

```

### PR DESCRIPTION
**Pull request by nvb**
Fixes #41027.

The test was getting stuck trying to establish SQL connections after its
warehouse count climbed from 600 to 1230. This was due to the HAProxy
connection limit, which was preventing new connections from being
established. This commit increases this connection limit, which fixes
the stall.

Release note: None

### CODE REVIEW

**Review by tbg — APPROVED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/41527)* status: :shipit: complete! 0 of 0 LGTMs obtained

File: pkg/cmd/roachtest/tpcc.go [hunk 1]
```diff
@@ -728,6 +728,14 @@ func runTPCCBench(ctx context.Context, t *test, c *cluster, b tpccBenchSpec) {
 				t.Fatal(err)
 			}
 			c.Run(ctx, loadNodes, "./cockroach gen haproxy --insecure --url {pgurl:1}")
+			// Increase the maximum connection limit to ensure that no TPC-C
+			// load gen workers get stuck during connection initialization.
+			// 10k warehouses requires at least 20,000 connections, so add a
+			// bit of breathing room and check the warehouse count.
+			c.Run(ctx, loadNodes, "sed -i 's/maxconn 4096/maxconn 21000/' haproxy.cfg")
```
Comment (bdarnell) [inline pkg/cmd/roachtest/tpcc.go]: Should we increase the limit in `gen haproxy` instead?

The sed command will fail silently if we ever change the default; we should either make it match on `maxconn [0-9]+` or check the number of changes made.

Comment (nvanbenschoten) [reply pkg/cmd/roachtest/tpcc.go]: > Should we increase the limit in gen haproxy instead?

I'd rather not make an external change like that just to fix a test.

> we should either make it match on maxconn [0-9]+

Done.

**Comment by nvanbenschoten** [comment]
The bors flake was https://github.com/cockroachdb/cockroach/issues/37468.

bors r+

**Comment by nvanbenschoten** [comment]
Bors didn't bite.

bors r+
