### PR TITLE
inspect: fix false row count mismatch errors after IMPORT

### LINKED ISSUE #168001: sql: import validation job fails with 2x as many rows
While doing some manual testing of IMPORT I managed to reproduce #165540, but I'm on c44991f4a32c4273b685c4bb7ac941c8a6198b51 which should already have the fix.

Here was the sequence of events on my 5-node roachprod cluster, I'm not sure which contributed, but maybe it was the fact that there were *two* imports of the same table? (The failed inspection was after the *second* import.)

1. `CREATE TABLE import_test.public.lineitem (...);`
2. first import: `IMPORT INTO import_test.public.lineitem CSV DATA (...) WITH OPTIONS (delimiter = '|', detached);`
3. paused import
4. killed process on node 2
5. restarted process on node 2
6. resumed import
7. killed process on node 3
8. paused import
9. resumed import
10. first import succeeded and inspect job started
11. `DROP TABLE import_test.public.lineitem;`
12. `CREATE TABLE import_test.public.lineitem (...);`
13. second import: `IMPORT INTO import_test.public.lineitem CSV DATA (...) WITH OPTIONS (delimiter = '|', detached);`
14. restarted process on node 3
15. second import succeeded and inspect job started
16. inspect job failed with error

```
root@localhost:26257/defaultdb> SHOW INSPECT ERRORS FOR JOB 1165358734994833410 WITH DETAILS;
      error_type     | database_name | schema_name | table_name | primary_key |       job_id        |            aost            |         details
---------------------+---------------+-------------+------------+-------------+---------------------+----------------------------+--------------------------
  row_count_mismatch | import_test   | public      | lineitem   |             | 1165358734994833410 | 2026-04-09 04:41:02.359791 | {
                     |               |             |            |             |                     |                            |     "actual": 12002430,
                     |               |             |            |             |                     |                            |     "expected": 6001215
                     |               |             |            |             |                     |                            | }
(1 row)

Time: 14ms total (execution 14ms / network 0ms)

root@localhost:26257/defaultdb> select version();
                                                                     version
--------------------------------------------------------------------------------------------------------------------------------------------------
  CockroachDB CCL v26.3.0-alpha.00000000-dev-c44991f4a32c4273b685c4bb7ac941c8a6198b51 (x86_64-pc-linux-gnu, built 2026/04/08 06:14:21, go1.25.5)
(1 row)

Time: 1ms total (execution 0ms / network 0ms)

root@localhost:26257/defaultdb> SELECT count(*) FROM import_test.public.lineitem;
   count
-----------
  6001215
(1 row)

Time: 1.878s total (execution 1.877s / network 0.000s)
```

The table fingerprints after both imports were the same, so I think the imports completed successfully:

```
index_name	fingerprint
----------------------
lineitem_pkey	57cbacf023ca5558
l_ok	8f43dfc469bcb971
l_pk	d1b66e031be06eff
l_sk	7338968c4dca4923
l_sd	35b94d81795cc0d0
l_cd	45ecbbeebfb1688c
l_rd	fe76d18daaf79ef4
l_pk_sk	03a8b662abfb8505
l_sk_pk	9f903a52c281154d
```

I have a debug.zip which I can share, and the roachprod cluster is still up.

Jira issue: CRDB-62742

### PR DESCRIPTION
**Pull request by spilchen**
IMPORT validates data integrity by running an inspect job that checks the row count against the expected number of imported rows. When the primary index has an empty span (a range with no rows), the inspect job incorrectly inflates the accumulated row count, producing a spurious RowCountMismatch error. This makes it appear that the imported data is corrupt when the data is actually correct.

The root cause is in getPredicateAndQueryArgs, which returned an empty predicate for empty spans. Downstream queries then ran without a WHERE clause, counting all rows in the table instead of zero for the empty span. The fix derives query bounds directly from the span boundaries when no rows exist, keeping all queries properly scoped. The function now also returns a hasRows bool so callers can distinguish empty spans without relying on a sentinel empty string.

Closes #168001

Release note: None

### CODE REVIEW

File: pkg/sql/inspect/uniqueness_check.go [hunk 1]
```diff
@@ -99,16 +99,15 @@ func (c *uniquenessCheck) Start(
 		keyColNames[i] = col.GetName()
 	}
 
-	lPredicate, lQueryArgs, err := getPredicateAndQueryArgs(
+	lPredicate, lQueryArgs, hasRows, err := getPredicateAndQueryArgs(
```
Comment (bghal) [inline pkg/sql/inspect/uniqueness_check.go]: nit: `lHasRows` for consistency

File: pkg/sql/inspect/index_consistency_check.go [hunk 2]
```diff
@@ -164,11 +164,9 @@ func (c *indexConsistencyCheck) Start(
 	otherColNames := colNames(otherColumns)
 	allColNames := colNames(c.columns)
 
-	// If no rows exist in the primary index span, we still need to check for dangling
-	// secondary index entries. We run the check with an empty predicate, which will
-	// scan the entire secondary index within the span. Any secondary index entries found
-	// will be dangling since there are no corresponding primary index rows.
```
Comment (bghal) [inline pkg/sql/inspect/index_consistency_check.go:170]: super nit: I feel like some detail is lost here.

**Review by fqazi — APPROVED** [review]
:lgtm:

Nice find @spilchen 

> @fqazi reviewed 8 files and all commit messages, and made 1 comment.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/168158#-:-OpskfT5CfHvUWBd2zu8:b-n324mx)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on spilchen).

File: pkg/sql/inspect/index_consistency_check.go
Comment (bghal) [inline pkg/sql/inspect/index_consistency_check.go:185]: Is the overly broad count here? Would it make sense for the `inspectCheckRowCount` interface to expose an invalid count rather than relying on its user doing the its own scan validation?

Comment (bghal) [reply pkg/sql/inspect/index_consistency_check.go:185]: I can make the interface changes in a subsequent diff if they're sensible and not worth holding off on.

**Review by bghal — APPROVED** [review]
Stamping to unblock the release but had some questions on the interface.

File: pkg/sql/inspect/index_consistency_check.go (hunk 2 above)
Comment (spilchen) [reply pkg/sql/inspect/index_consistency_check.go:170]: Done.

File: pkg/sql/inspect/index_consistency_check.go
Comment (spilchen) [reply pkg/sql/inspect/index_consistency_check.go:185]: Yes, this is where we double counted. The query had no predicates so scanned the entire table. 

I'm not sure 100% sure what you are suggesting for the interface change. Can you clarify? It sounds like something to handle in a follow-on as it doesn't impact the fix.

File: pkg/sql/inspect/uniqueness_check.go (hunk 1 above)
Comment (spilchen) [reply pkg/sql/inspect/uniqueness_check.go]: Done

**Review by spilchen — COMMENTED** [review]
Thanks for the reviews

> @spilchen made 4 comments.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/168158#-:-Opt-jPJ2RTwM1h0H-fY:b-9qdowt)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on bghal and fqazi).

File: pkg/sql/inspect/row_count_check.go
Comment (bghal) [inline pkg/sql/inspect/row_count_check.go:31]:
```suggestion
	RowCount() *uint64
```

The interface can indicate there is no valid row count for the span.

Comment (bghal) [inline pkg/sql/inspect/row_count_check.go:132]:
```suggestion
if check, ok := check.(inspectCheckRowCount); ok {
	if rowCount := check.RowCount(); rowCount != nil {
		data.SpanRowCount = check.RowCount()
		return nil
	}
}
```

Same behavior but the row count check never gets an incorrect value from the consistency check.

File: pkg/sql/inspect/index_consistency_check.go
Comment (bghal) [reply pkg/sql/inspect/index_consistency_check.go:185]: I'm thinking that `c.rowCount` should never be filled if we know it's a bad count from `hasRows`.

Noted down my thoughts but best as a follow-up.

**Comment by spilchen** [comment]
TFTR!

/trunk merge

**Comment by rafiss** [comment]
blathers backport 26.2.0-rc
