### PR TITLE
sqlproxyccl: pass in ctx when transferring connections

### LINKED ISSUE #153569: ccl/sqlproxyccl: TestCancelQuery failed
ccl/sqlproxyccl.TestCancelQuery [failed](https://mesolite.cluster.engflow.com/invocations/default/fbce7f04-dc49-4c87-ac1d-5206d445513e?testReportRun=1&testReportShard=7&testReportAttempt=1#targets-Ly9wa2cvY2NsL3NxbHByb3h5Y2NsOnNxbHByb3h5Y2NsX3Rlc3Q=) on release-24.3.20-rc @ [917f8feb69e137770694819f17dc31363aa82ec7](https://github.com/cockroachdb/cockroach/commits/917f8feb69e137770694819f17dc31363aa82ec7):

Fatal error:

```
panic: use of Span after Finish. Span: proxy-con-serve. Finish previously called at: <stack not captured. Set debugUseAfterFinish> [recovered]
	panic: use of Span after Finish. Span: proxy-con-serve. Finish previously called at: <stack not captured. Set debugUseAfterFinish>

```
Stack: 

```
goroutine 4767 [running]:
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).recover(0xc004c68c70?, {0xe3c0518, 0xc00d67a180})
	pkg/util/stop/stopper.go:226 +0x74
panic({0xa7611a0?, 0xc0020fb5a0?})
	GOROOT/src/runtime/panic.go:770 +0x132
github.com/cockroachdb/cockroach/pkg/util/tracing.(*Span).detectUseAfterFinish(0xc0071b2008)
	pkg/util/tracing/span.go:177 +0x274
github.com/cockroachdb/cockroach/pkg/util/tracing.(*Span).RecordingType(0xc0071b2008)
	pkg/util/tracing/span.go:437 +0x27
github.com/cockroachdb/cockroach/pkg/util/tracing.(*Span).IsVerbose(...)
	pkg/util/tracing/span.go:445
github.com/cockroachdb/cockroach/pkg/util/log.getSpan({0xe3c03c0, 0xc0072b1500})
	pkg/util/log/trace.go:22 +0x45
github.com/cockroachdb/cockroach/pkg/util/log.logfDepthInternal({0xe3c03c0, 0xc0072b1500}, 0x2, 0x3, 0x1, 0x0, {0xaf57945, 0x27}, {0xc00909b698, 0x2, ...})
	pkg/util/log/channels.go:99 +0x66b
github.com/cockroachdb/cockroach/pkg/util/log.logfDepth(...)
	pkg/util/log/channels.go:34
github.com/cockroachdb/cockroach/pkg/util/log.loggerOps.Errorf(...)
	bazel-out/k8-fastbuild/bin/pkg/util/log/log_channels_generated.go:1281
github.com/cockroachdb/cockroach/pkg/ccl/sqlproxyccl.(*connector).dialTenantCluster(0xc008005100, {0xe3c03c0, 0xc0072b1500}, {0xe3c0270, 0xc00448b900})
	pkg/ccl/sqlproxyccl/connector.go:243 +0xcd8
github.com/cockroachdb/cockroach/pkg/ccl/sqlproxyccl.(*connector).OpenTenantConnWithToken(0xc008005100, {0xe3c03c0, 0xc0072b1500}, {0xe3c0270, 0xc00448b900}, {0xc003e5a460, 0x9c})
	pkg/ccl/sqlproxyccl/connector.go:106 +0x1ba
github.com/cockroachdb/cockroach/pkg/ccl/sqlproxyccl.transferConnection(0xc0072b1500, {0xe3c0270, 0xc00448b900}, 0xc008005100, 0xc004fd37a0, 0xc006d7c5d0, 0xc00783e750)
	pkg/ccl/sqlproxyccl/conn_migration.go:274 +0x40d
github.com/cockroachdb/cockroach/pkg/ccl/sqlproxyccl.(*forwarder).TransferConnection(0xc00448b900)
	pkg/ccl/sqlproxyccl/conn_migration.go:213 +0x509
github.com/cockroachdb/cockroach/pkg/ccl/sqlproxyccl/balancer.(*Balancer).processQueue.func1.1({0xe3c0518, 0xc00d67a180})
	pkg/ccl/sqlproxyccl/balancer/balancer.go:371 +0x268
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunAsyncTaskEx.func2({0xae98922, 0x11})
	pkg/util/stop/stopper.go:498 +0x339
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunAsyncTaskEx in goroutine 4545
	pkg/util/stop/stopper.go:488 +0x786
```
<details><summary>Log preceding fatal error</summary>
<p>

```
=== RUN   TestCancelQuery
    test_log_scope.go:165: test logs captured to: outputs.zip/logTestCancelQuery3798647868
    test_log_scope.go:76: use -show-logs to present logs inline
=== RUN   TestCancelQuery/cancel_after_migrating_a_session
=== RUN   TestCancelQuery/cancel_over_http
=== RUN   TestCancelQuery/cancel_over_sql
=== RUN   TestCancelQuery/forward_over_http
=== RUN   TestCancelQuery/ignore_unknown_secret_key
*
* ERROR: a panic has occurred!
* use of Span after Finish. Span: proxy-con-serve. Finish previously called at: <stack not captured. Set debugUseAfterFinish>
* (1) attached stack trace
*   -- stack trace:
*   | runtime.gopanic
*   | 	GOROOT/src/runtime/panic.go:770
*   | [...repeated from below...]
* Wraps: (2) assertion failure
* Wraps: (3) attached stack trace
*   -- stack trace:
*   | github.com/cockroachdb/cockroach/pkg/util/tracing.(*Span).detectUseAfterFinish
*   | 	pkg/util/tracing/span.go:177
*   | github.com/cockroachdb/cockroach/pkg/util/tracing.(*Span).RecordingType
*   | 	pkg/util/tracing/span.go:437
*   | github.com/cockroachdb/cockroach/pkg/util/tracing.(*Span).IsVerbose
*   | 	pkg/util/tracing/span.go:445
*   | github.com/cockroachdb/cockroach/pkg/util/log.getSpan
*   | 	pkg/util/log/trace.go:22
*   | github.com/cockroachdb/cockroach/pkg/util/log.logfDepthInternal
*   | 	pkg/util/log/channels.go:99
*   | github.com/cockroachdb/cockroach/pkg/util/log.logfDepth
*   | 	pkg/util/log/channels.go:34
*   | github.com/cockroachdb/cockroach/pkg/util/log.loggerOps.Errorf
*   | 	bazel-out/k8-fastbuild/bin/pkg/util/log/log_channels_generated.go:1281
*   | github.com/cockroachdb/cockroach/pkg/ccl/sqlproxyccl.(*connector).dialTenantCluster
*   | 	pkg/ccl/sqlproxyccl/connector.go:243
*   | github.com/cockroachdb/cockroach/pkg/ccl/sqlproxyccl.(*connector).OpenTenantConnWithToken
*   | 	pkg/ccl/sqlproxyccl/connector.go:106
*   | github.com/cockroachdb/cockroach/pkg/ccl/sqlproxyccl.transferConnection
*   | 	pkg/ccl/sqlproxyccl/conn_migration.go:274
*   | github.com/cockroachdb/cockroach/pkg/ccl/sqlproxyccl.(*forwarder).TransferConnection
*   | 	pkg/ccl/sqlproxyccl/conn_migration.go:213
*   | github.com/cockroachdb/cockroach/pkg/ccl/sqlproxyccl/balancer.(*Balancer).processQueue.func1.1
*   | 	pkg/ccl/sqlproxyccl/balancer/balancer.go:371
*   | github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunAsyncTaskEx.func2
*   | 	pkg/util/stop/stopper.go:498
*   | runtime.goexit
*   | 	src/runtime/asm_amd64.s:1695
* Wraps: (4) use of Span after Finish. Span: proxy-con-serve. Finish previously called at: <stack not captured. Set debugUseAfterFinish>
* Error types: (1) *withstack.withStack (2) *assert.withAssertionFailure (3) *withstack.withStack (4) *errutil.leafError
*
```
</p>
</details>

Parameters:
 - <code>attempt=1</code>
 - <code>race=true</code>
 - <code>run=1</code>
 - <code>shard=7</code>
<details><summary>Help</summary>
<p>

See also: [How To Investigate a Go Test Failure \(internal\)](https://cockroachlabs.atlassian.net/l/c/HgfXfJgM)
</p>
</details>
<details><summary>Same failure on other branches</summary>
<p>

- #151664 ccl/sqlproxyccl: TestCancelQuery failed [C-test-failure O-robot T-serverless branch-release-24.3.19-rc]
- #151651 ccl/sqlproxyccl: TestCancelQuery failed [C-test-failure O-robot T-serverless branch-release-24.1.23-rc]
- #149408 ccl/sqlproxyccl: TestCancelQuery failed [C-test-failure O-robot P-3 T-cloud-platform branch-release-25.3]
- #148599 ccl/sqlproxyccl: TestCancelQuery failed [C-test-failure O-robot T-serverless branch-release-24.1]
- #145279 ccl/sqlproxyccl: TestCancelQuery failed [C-test-failure O-robot T-serverless branch-release-25.1]
- #144691 ccl/sqlproxyccl: TestCancelQuery failed [C-test-failure O-robot T-serverless branch-release-24.3]
- #142810 ccl/sqlproxyccl: TestCancelQuery failed [C-test-failure O-robot T-serverless branch-master]
</p>
</details>
/cc @cockroachdb/sql-foundations @cockroachdb/server
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*TestCancelQuery.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/bazci/githubpost/issues)

</sub>

Jira issue: CRDB-54499

### PR DESCRIPTION
**Pull request by davidwding**
Previously, the span used when transferring connections was reused from
the forwarder. However, transferring connections has async components,
so it's possible that the forwarder calls `Finish` on the span before
the connection transfer is done using the span. This leads to a panic:
`panic: use of Span after Finish`. To address this, this patch passes a
context in when transferring a connection, instead of using the
forwarder's context.

Fixes: https://github.com/cockroachdb/cockroach/issues/153569
Release note: None

### CODE REVIEW

File: pkg/ccl/sqlproxyccl/conn_migration.go [hunk 1]
```diff
@@ -46,11 +47,16 @@ type transferContext struct {
 }
 
 func newTransferContext(backgroundCtx context.Context) (*transferContext, context.CancelFunc) {
```
Comment (jeffswenson) [inline pkg/ccl/sqlproxyccl/conn_migration.go:48]: This is subtle, but I don't think this a complete fix. It's possible the forwarder's span was already free'd by the time we are calling `newTransferContext`.

I think fixing this requires us to attach a span to the `forwarder`, or add a context as an argument to `TransferConnection` and use that context instead of the forwarder's context.

Passing a context with a span into TransferConnection feels more idiomatic. I'm not sure why this code was using the forwarder's context.

Comment (davidwding) [reply pkg/ccl/sqlproxyccl/conn_migration.go:48]: PTAL. I don't believe that I need to fork the span anymore in `newTransferContext`, but let me know if I'm misunderstanding.

Comment (jeffswenson) [reply pkg/ccl/sqlproxyccl/conn_migration.go:48]: This change looks good to me. I'll approve it once CI is green.

File: pkg/ccl/sqlproxyccl/conn_migration.go [hunk 2]
```diff
@@ -127,7 +127,7 @@ var errTransferCannotStart = errors.New("transfer cannot be started")
 // error).
 //
 // TransferConnection implements the balancer.ConnectionHandle interface.
-func (f *forwarder) TransferConnection() (retErr error) {
+func (f *forwarder) TransferConnection(transferCtx context.Context) (retErr error) {
```
Comment (jeffswenson) [inline pkg/ccl/sqlproxyccl/conn_migration.go]: nit: I think you can call this parameter `ctx`. Since it is used as a conventional context.

Comment (davidwding) [reply pkg/ccl/sqlproxyccl/conn_migration.go]: Sounds good. I had to rename another variable to `transferCtx`

**Review by davidwding — COMMENTED** [review]
Let's see if I fixed the test failure too...I wasn't handling the context objects in the test properly 🤞

**Review by jeffswenson — APPROVED** [review]
LGTM

**Comment by davidwding** [comment]
TFTR!
