### PR TITLE
roachtest: mark polled VM preemptions as non reportable

### LINKED ISSUE #139004: roachtest: kv0/enc=false/nodes=1/mt-shared-process failed
roachtest.kv0/enc=false/nodes=1/mt-shared-process [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyAwsBazel/18490643?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyAwsBazel/18490643?buildTab=artifacts#/kv0/enc=false/nodes=1/mt-shared-process) on release-24.3 @ [ef0e25554c256e3c014d1588a526f96258f91e95](https://github.com/cockroachdb/cockroach/commits/ef0e25554c256e3c014d1588a526f96258f91e95):

```
(test_runner.go:2128).func1: monitorForPreemptedVMs: Preempted VMs detected: [{i-07c3c8b4213937215 0001-01-01 00:00:00 +0000 UTC}]
(cluster.go:2455).Run: context canceled
(monitor.go:149).Wait: monitor failure: monitor user task failed: t.Fatal() was called
test artifacts and logs in: /artifacts/kv0/enc=false/nodes=1/mt-shared-process/cpu_arch=arm64/run_1
```

Parameters:
 - <code>arch=arm64</code>
 - <code>cloud=aws</code>
 - <code>coverageBuild=false</code>
 - <code>cpu=8</code>
 - <code>encrypted=false</code>
 - <code>fs=ext4</code>
 - <code>localSSD=true</code>
 - <code>runtimeAssertionsBuild=false</code>
 - <code>ssd=0</code>
<details><summary>Help</summary>
<p>

See: [roachtest README](https://github.com/cockroachdb/cockroach/blob/master/pkg/cmd/roachtest/README.md)

See: [How To Investigate \(internal\)](https://cockroachlabs.atlassian.net/l/c/SSSBr8c7)

_Grafana is not yet available for aws clusters_</p>
</details>
/cc @cockroachdb/test-eng
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*kv0/enc=false/nodes=1/mt-shared-process.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/bazci/githubpost/issues)

</sub>

Jira issue: CRDB-46461

### LINKED ISSUE #139931: roachtest: tpccbench/nodes=3/cpu=16 failed
roachtest.tpccbench/nodes=3/cpu=16 [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyAwsBazel/18631199?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyAwsBazel/18631199?buildTab=artifacts#/tpccbench/nodes=3/cpu=16) on release-24.3.4-rc @ [2e8d8e7f91b39e3e4148571f4495e5f0c9a4bd77](https://github.com/cockroachdb/cockroach/commits/2e8d8e7f91b39e3e4148571f4495e5f0c9a4bd77):

```
(test_runner.go:2128).func1: monitorForPreemptedVMs: Preempted VMs detected: [{i-01b8ddf1dafb00ff2 0001-01-01 00:00:00 +0000 UTC}]
(cluster.go:2342).Start: cluster.StartE: context canceled
test artifacts and logs in: /artifacts/tpccbench/nodes=3/cpu=16/cpu_arch=arm64/run_1
```

Parameters:
 - <code>arch=arm64</code>
 - <code>cloud=aws</code>
 - <code>coverageBuild=false</code>
 - <code>cpu=16</code>
 - <code>encrypted=false</code>
 - <code>fs=ext4</code>
 - <code>localSSD=true</code>
 - <code>runtimeAssertionsBuild=false</code>
 - <code>ssd=0</code>
<details><summary>Help</summary>
<p>

See: [roachtest README](https://github.com/cockroachdb/cockroach/blob/master/pkg/cmd/roachtest/README.md)

See: [How To Investigate \(internal\)](https://cockroachlabs.atlassian.net/l/c/SSSBr8c7)

_Grafana is not yet available for aws clusters_</p>
</details>
/cc @cockroachdb/test-eng
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*tpccbench/nodes=3/cpu=16.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/bazci/githubpost/issues)

</sub>

Jira issue: CRDB-46908

### PR DESCRIPTION
**Pull request by DarrylWong**
Previously, polled VM preemptions would simply cancel the test, as post test processing would recheck for preemptions again. However, we've seen some cases in AWS where the post test check returns no preemptions despite the polling returning preemptions.

This may be just be the AWS check being eventually consistent, so we want to avoid posting if either check finds preemptions.

----

The second change resets failures in the case of a vm preemption, in case a timeout occurred which normally takes precedence over all other failures. While a timeout suggests that something should be fixed with the test (usually respecting the test context cancellation), we see that in practice, engineers tend to close the issue without investigating as soon as they see the preemption.

This also removes the potential duplicate vm_preemption failure that may have been added by the preemption polling.

Fixes: https://github.com/cockroachdb/cockroach/issues/139004
Fixes: https://github.com/cockroachdb/cockroach/issues/139931
Release note: none
Epic: none

### CODE REVIEW

**Comment by DarrylWong** [comment]
On the fence on the second commit. One one hand there have been two cases where teams fix their tests, but in general it appears [most engineers just close out the issue](https://github.com/cockroachdb/cockroach/issues?q=is%3Aissue%20state%3Aclosed%20%22VMs%20preempted%20during%20the%20test%20run%3A%22). Arguable how much value is even gained from fixing said tests anyway.

File: pkg/cmd/roachtest/test_test.go [hunk 1]
```diff
@@ -767,4 +767,54 @@ func TestVMPreemptionPolling(t *testing.T) {
 		// be treated as a flake instead of a failed test.
 		require.NoError(t, err)
 	})
+
+	// Test that if VM preemption polling finds a preempted VM but the post test failure
+	// check doesn't, the test is still marked as a flake.
+	t.Run("post test check doesn't catch preemption", func(t *testing.T) {
+		setPollPreemptionInterval(50 * time.Millisecond)
```
Comment (srosenberg) [inline pkg/cmd/roachtest/test_test.go:774]: This would flake under `--stress`, right?

File: pkg/cmd/roachtest/test_test.go [hunk 2]
```diff
@@ -767,4 +767,54 @@ func TestVMPreemptionPolling(t *testing.T) {
...
+		}
+
+		mockTest.Run = func(ctx context.Context, t test.Test, c cluster.Cluster) {
+			for {
+				<-ctx.Done()
+			}
+		}
+		mockTest.Timeout = 50 * time.Millisecond
+
+		err := runner.Run(ctx, []registry.TestSpec{mockTest}, 1, /* count */
```
Comment (srosenberg) [inline pkg/cmd/roachtest/test_test.go:815]: Same as above...  timeout may never occur under `--stress`.

**Comment by DarrylWong** [comment]
Yup, `stress` didn't fail but `race` did. Interestingly, the failure being added by the preemption polling races with the post test assertion check replacing the logger. This isn't specific to preemption polling, I can repro this by just running:

```
		mockTest.Run = func(ctx context.Context, t test.Test, c cluster.Cluster) {
			t.Error("test failed")
		}
		mockTest.Timeout = 1 * time.Nanosecond
```

So this is a possible data race we could see in actual roachtests if it times out. From what I can tell, the only impact is that we might lose the failure being logged to `test.log`, which is not a huge deal since the test timed out which is most likely the real failure anyway.

For these unit tests, I just made sure the above race doesn't happen since it doesn't affect what it's testing. Not sure if we want to add a real fix for the data race though.

File: pkg/cmd/roachtest/test_test.go (hunk 2 above)
Comment (DarrylWong) [reply pkg/cmd/roachtest/test_test.go:823]: Lowered the timeout to 10 ms, we have another unit test that uses that time and seems to be doing fine, so hopefully it should be for this as well. Stressed 3000 times with no flakes.

**Comment by srosenberg** [comment]
>  Interestingly, the failure being added by the preemption polling races with the post test assertion check replacing the logger.

Not entirely following... I thought `addFailure` was thread-safe. Can you post the report from the data race, i.e., the racing goroutine stacks.

**Comment by DarrylWong** [comment]
Sure, here's a simple repro of what I'm seeing:

```
func TestRunnerTestTimeoutRace(t *testing.T) {
	ctx := context.Background()
	stopper := stop.NewStopper()
	defer stopper.Stop(ctx)
	cr := newClusterRegistry()
	runner := newUnitTestRunner(cr, stopper)

	var buf syncedBuffer
	copt := defaultClusterOpt()
	lopt := defaultLoggingOpt(&buf)
	test := registry.TestSpec{
		Name:             `timeout`,
		Owner:            OwnerUnitTest,
		Timeout:          1 * time.Millisecond,
		Cluster:          spec.MakeClusterSpec(0),
		CompatibleClouds: registry.AllExceptAWS,
		Suites:           registry.Suites(registry.Nightly),
		CockroachBinary:  registry.StandardCockroach,
		Run: func(ctx context.Context, t test.Test, c cluster.Cluster) {
			t.Error("test failed")
		},
	}
	_ = runner.Run(ctx, []registry.TestSpec{test}, 1, /* count */
		defaultParallelism, copt, testOpts{}, lopt)
}
```

Running `./dev test pkg/cmd/roachtest -f TestRunnerTestTimeoutRace --stress --race` hits:

```
==================
WARNING: DATA RACE
Read at 0x00c004b9e888 by goroutine 40:
  github.com/cockroachdb/cockroach/pkg/cmd/roachtest.(*testImpl).L()
      pkg/cmd/roachtest/test_impl.go:262 +0x520
  github.com/cockroachdb/cockroach/pkg/cmd/roachtest.(*testImpl).addFailure()
      pkg/cmd/roachtest/test_impl.go:470 +0x530
  github.com/cockroachdb/cockroach/pkg/cmd/roachtest.(*testImpl).addFailureAndCancel()
      pkg/cmd/roachtest/test_impl.go:441 +0x5c
  github.com/cockroachdb/cockroach/pkg/cmd/roachtest.(*testImpl).Error()
      pkg/cmd/roachtest/test_impl.go:432 +0x4c
  github.com/cockroachdb/cockroach/pkg/cmd/roachtest.TestRunnerTestTimeoutRace.func1()
      pkg/cmd/roachtest/test_test.go:381 +0x88
  github.com/cockroachdb/cockroach/pkg/cmd/roachtest.(*testRunner).runTest.func2()
      pkg/cmd/roachtest/test_runner.go:1315 +0x168

Previous write at 0x00c004b9e888 by goroutine 39:
  github.com/cockroachdb/cockroach/pkg/cmd/roachtest.(*testImpl).ReplaceL()
      pkg/cmd/roachtest/test_impl.go:268 +0x1d0
  github.com/cockroachdb/cockroach/pkg/cmd/roachtest.(*testRunner).runTest.func4()
      pkg/cmd/roachtest/test_runner.go:1380 +0x1cc
  github.com/cockroachdb/cockroach/pkg/cmd/roachtest.(*testRunner).runTest()
      pkg/cmd/roachtest/test_runner.go:1402 +0x14d8
  github.com/cockroachdb/cockroach/pkg/cmd/roachtest.(*testRunner).runWorker()
      pkg/cmd/roachtest/test_runner.go:937 +0x2b6c
  github.com/cockroachdb/cockroach/pkg/cmd/roachtest.(*testRunner).Run.func1()
      pkg/cmd/roachtest/test_runner.go:389 +0x3b4
  github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunAsyncTaskEx.func2()
      pkg/util/stop/stopper.go:500 +0x214
  github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunAsyncTaskEx.gowrap1()
      pkg/util/stop/stopper.go:501 +0x54

Goroutine 40 (running) created at:
  github.com/cockroachdb/cockroach/pkg/cmd/roachtest.(*testRunner).runTest()
      pkg/cmd/roachtest/test_runner.go:1296 +0xba8
  github.com/cockroachdb/cockroach/pkg/cmd/roachtest.(*testRunner).runWorker()
      pkg/cmd/roachtest/test_runner.go:937 +0x2b6c
  github.com/cockroachdb/cockroach/pkg/cmd/roachtest.(*testRunner).Run.func1()
      pkg/cmd/roachtest/test_runner.go:389 +0x3b4
  github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunAsyncTaskEx.func2()
      pkg/util/stop/stopper.go:500 +0x214
  github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunAsyncTaskEx.gowrap1()
      pkg/util/stop/stopper.go:501 +0x54

Goroutine 39 (running) created at:
  github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunAsyncTaskEx()
      pkg/util/stop/stopper.go:489 +0x52c
  github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunAsyncTask()
      pkg/util/stop/stopper.go:360 +0xfd4
  github.com/cockroachdb/cockroach/pkg/cmd/roachtest.(*testRunner).Run()
      pkg/cmd/roachtest/test_runner.go:378 +0xcc4
  github.com/cockroachdb/cockroach/pkg/cmd/roachtest.TestRunnerTestTimeoutRace()
      pkg/cmd/roachtest/test_test.go:384 +0x5e4
  testing.tRunner()
      GOROOT/src/testing/testing.go:1689 +0x180
  testing.(*T).Run.gowrap1()
      GOROOT/src/testing/testing.go:1742 +0x40
==================
```

So the `failures` struct in `addFailure` is thread safe, but the logger it uses here: 

https://github.com/cockroachdb/cockroach/blob/1de6c82abe9e266af65bcd9428548aad8d9abd33/pkg/cmd/roachtest/test_impl.go#L349

isn't because we replace the logger after the test is done:

https://github.com/cockroachdb/cockroach/blob/3c64af25d55d8ce568e5d9735ee74a87b9d3c32e/pkg/cmd/roachtest/test_runner.go#L1090-L1098

Note the comment: `We still want to run the post-test assertions even if the test timed out` along with the fact that on test timeouts we purposely don't cancel the test context and let the test keep running.

So my understanding is that the following ordering can happen:

1. The test times out and the test runner stops blocking.
2. The test runner starts post tests assertion checks, replacing the logger.
3. The test itself runs `t.Error("test failed")` which eventually calls `t.L().Printf`. This races with the above.

----

The original test was hitting the same race w/ the same stack trace, it was just the polling preemption adding the failure instead of the test itself.

**Comment by srosenberg** [comment]
> The test times out and the test runner stops blocking.
The test runner starts post tests assertion checks, replacing the logger.
The test itself runs t.Error("test failed") which eventually calls t.L().Printf. This races with the above.

Yep. That's a perfectly plausible scenario. We should fix it; e.g., changing the type of `testImpl.L` to `atomic.Pointer`.

File: pkg/cmd/roachtest/test_test.go [hunk 3]
```diff
@@ -767,4 +767,62 @@ func TestVMPreemptionPolling(t *testing.T) {
...
+			return preemptedVMs, nil
+		}
+
+		mockTest.Run = func(ctx context.Context, t test.Test, c cluster.Cluster) {
+			defer func() {
+				getPreemptedVMsHook = func(c cluster.Cluster, ctx context.Context, l *logger.Logger) ([]vm.PreemptedVM, error) {
+					return nil, nil
+				}
+			}()
+			// Make sure the preemption polling is called and the test context is cancelled
```
Comment (srosenberg) [inline pkg/cmd/roachtest/test_test.go:791]: Good. This removes the clock, and the corresponding "flakiness", from the equation.

File: pkg/cmd/roachtest/test_test.go [hunk 4]
```diff
@@ -767,4 +767,62 @@ func TestVMPreemptionPolling(t *testing.T) {
...
+			}}
+			return preemptedVMs, nil
+		}
+
+		mockTest.Run = func(ctx context.Context, t test.Test, c cluster.Cluster) {
+			for {
+				<-ctx.Done()
+			}
+		}
+		mockTest.Timeout = 10 * time.Millisecond
```
Comment (srosenberg) [inline pkg/cmd/roachtest/test_test.go:821]: Nit: I'd move this before `Run` since, logically, `Timeout` is intended to modify `Run's` behavior.

File: pkg/cmd/roachtest/test_test.go [hunk 5]
```diff
@@ -767,4 +767,62 @@ func TestVMPreemptionPolling(t *testing.T) {
...
+		getPreemptedVMsHook = func(c cluster.Cluster, ctx context.Context, l *logger.Logger) ([]vm.PreemptedVM, error) {
+			preemptedVMs := []vm.PreemptedVM{{
+				Name:        "test_node",
+				PreemptedAt: time.Now(),
+			}}
+			return preemptedVMs, nil
+		}
+
+		mockTest.Run = func(ctx context.Context, t test.Test, c cluster.Cluster) {
+			for {
```
Comment (srosenberg) [inline pkg/cmd/roachtest/test_test.go:817]: Nit: `for` is redundant since a cancelled context remains cancelled.

File: pkg/cmd/roachtest/test_test.go [hunk 6]
```diff
@@ -767,4 +767,62 @@ func TestVMPreemptionPolling(t *testing.T) {
...
+		setPollPreemptionInterval(10 * time.Minute)
+		getPreemptedVMsHook = func(c cluster.Cluster, ctx context.Context, l *logger.Logger) ([]vm.PreemptedVM, error) {
+			preemptedVMs := []vm.PreemptedVM{{
+				Name:        "test_node",
+				PreemptedAt: time.Now(),
+			}}
+			return preemptedVMs, nil
+		}
+
+		mockTest.Run = func(ctx context.Context, t test.Test, c cluster.Cluster) {
```
Comment (srosenberg) [inline pkg/cmd/roachtest/test_test.go:816]: We should add an explainer since it's not immediately clear as to what's expected to happen. We expect that the context will be cancelled only when `Timeout` expires, at which point the test would normally be marked as failed. However, due to injected preemption, the test isn't marked as failed. Thus, `runner.Run` is expected not to return `errTestsFailed`, or any other error.

**Review by srosenberg — APPROVED** [review]

File: pkg/cmd/roachtest/test_test.go (hunk 5 above)
Comment (DarrylWong) [reply pkg/cmd/roachtest/test_test.go]: Ah true, changed. I wanted it to block forever but linter was complaining about an empty for loop. Blocking on the context does what I want though.

File: pkg/cmd/roachtest/test_test.go (hunk 6 above)
Comment (DarrylWong) [reply pkg/cmd/roachtest/test_test.go:824]: Done.

**Comment by DarrylWong** [comment]
> We should fix it; e.g., changing the type of testImpl.L to atomic.Pointer

SGTM, will put it out as a followup PR.

**Review by srosenberg — APPROVED** [review]

**Comment by srosenberg** [comment]
blathers backport 25.1.0-rc
