### PR TITLE
catalog/lease: deflake TestLeaseManagerSessionIDChanges

### LINKED ISSUE #146226: sql/catalog/lease: TestLeaseManagerSessionIDChanges failed
sql/catalog/lease.TestLeaseManagerSessionIDChanges [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Ci_TestsAwsLinuxArm64_UnitTests/19631527?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Ci_TestsAwsLinuxArm64_UnitTests/19631527?buildTab=artifacts#/) on master @ [cab3b7f31e202a4e6e94d9ba901cccbdc47b25e3](https://github.com/cockroachdb/cockroach/commits/cab3b7f31e202a4e6e94d9ba901cccbdc47b25e3):

```
=== RUN   TestLeaseManagerSessionIDChanges
    test_log_scope.go:165: test logs captured to: /artifacts/tmp/_tmp/be0d053872b35521d816dbd3d2572df0/logTestLeaseManagerSessionIDChanges746944333
    test_log_scope.go:76: use -show-logs to present logs inline
    lease_internal_test.go:1722: query 'SELECT session_id FROM system.lease WHERE desc_id=106': expected:
        session-1
        
        got:
        ����"bζDK}����=��f
        session-1
        
    panic.go:635: -- test log scope end --
test logs left over in: /artifacts/tmp/_tmp/be0d053872b35521d816dbd3d2572df0/logTestLeaseManagerSessionIDChanges746944333
--- FAIL: TestLeaseManagerSessionIDChanges (0.52s)
```
<details><summary>Help</summary>
<p>

See also: [How To Investigate a Go Test Failure \(internal\)](https://cockroachlabs.atlassian.net/l/c/HgfXfJgM)
</p>
</details>
/cc @cockroachdb/sql-foundations
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*TestLeaseManagerSessionIDChanges.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/bazci/githubpost/issues)

</sub>

Jira issue: CRDB-50436

### PR DESCRIPTION
**Pull request by fqazi**
Previously, TestLeaseManagerSessionIDChanges would flake if the lease managers range feed got notification of a table after it had been leased with a "fake" session ID. The session ID override used by this test is toggled between querying the system.lease tables, which allows the target can allow entries with a real session ID to get inserted (if a race condition occurs). To address this, this patch disables the range feed used by the lease manager to avoid this flake.

Fixes: #146226
Release note: None

### CODE REVIEW

File: pkg/sql/catalog/lease/lease_internal_test.go [hunk 1]
```diff
@@ -1653,7 +1653,11 @@ func TestLeaseManagerSessionIDChanges(t *testing.T) {
 	runner := sqlutils.MakeSQLRunner(sqlDB)
 	runner.Exec(t, `SET CLUSTER SETTING sql.stats.automatic_collection.enabled = false`)
 	runner.Exec(t, `SET CLUSTER SETTING sql.catalog.descriptor_wait_for_initial_version.enabled = false`)
-
+	// Disable the range feed for this test to prevent race conditions between
+	// the session ID hook being enabled / disabled. Previously, the initial acquisition of
+	// the descriptor could be faster than the range feed, causing the range feed to
+	// insert a lease with the real session ID (when the hook was disabled).
```
Comment (rafiss) [inline pkg/sql/catalog/lease/lease_internal_test.go]: should this say "when the hook was enabled" ?

Comment (fqazi) [reply pkg/sql/catalog/lease/lease_internal_test.go]: The real session ID is only used then `enableHook` is set to false

**Review by fqazi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/147649)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @rafiss)

File: pkg/sql/catalog/lease/lease_internal_test.go (hunk 1 above)
Comment (fqazi) [reply pkg/sql/catalog/lease/lease_internal_test.go]: Updated this text to make things clearer:

	// Disable the range feed for this test. This prevents a race condition
	// where the range feed could insert a lease with the real session ID
	// (if the session ID hook was disabled) before the initial descriptor
	// acquisition completes.

**Review by fqazi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/147649)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @rafiss)

File: pkg/sql/catalog/lease/lease_internal_test.go (hunk 1 above)
Comment (rafiss) [reply pkg/sql/catalog/lease/lease_internal_test.go]: lgtm!

**Review by rafiss — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/147649)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained

**Comment by fqazi** [comment]
@rafiss TFTR!

bors r+

**Comment by fqazi** [comment]
bors retry
