### PR TITLE
sqlccl: deflake TestExplainGist when run with concurrent ALTER PK

### LINKED ISSUE #130282: pkg/ccl/testccl/sqlccl/sqlccl_test: TestExplainGist failed
pkg/ccl/testccl/sqlccl/sqlccl_test.TestExplainGist [failed](https://tanzanite.cluster.engflow.com/invocations/default/9d55697b-0b19-4835-a348-dd23409708d9?testReportRun=19&testReportShard=2&testReportAttempt=1#targets-Ly9wa2cvY2NsL3Rlc3RjY2wvc3FsY2NsOnNxbGNjbF90ZXN0) on master @ [fa9c0528fc0d06be1b4cfc534ec0501448111fbe](https://github.com/cockroachdb/cockroach/commits/fa9c0528fc0d06be1b4cfc534ec0501448111fbe):

```
        LIMIT
        	58:::INT8;
        DELETE FROM
        	defaultdb.public.seed AS tab_725
        USING
        	defaultdb.public.seed AS tab_726, defaultdb.public.seed AS tab_727, defaultdb.public.seed AS tab_728
        LIMIT
        	91:::INT8;
        
    explain_test.go:204: pq: internal error: requested column col_647 not in index: WITH
        	with_108 (col_1144)
        		AS (
        			SELECT * FROM (VALUES ('hello':::greeting), ('added_val_1':::greeting)) AS tab_733 (col_1144)
        			UNION
        				SELECT
        					*
        				FROM
        					(
        						VALUES
        							('howdy':::greeting),
        							(
        								(
        									SELECT
        										'added_val_1':::greeting AS col_1145
        									FROM
        										defaultdb.public.seed AS tab_734
        									WHERE
        										false
        									GROUP BY
        										tab_734._timestamptz
        									HAVING
        										bool_or(tab_734._bool::BOOL)::BOOL
        									ORDER BY
        										tab_734._timestamptz DESC
        									LIMIT
        										1:::INT8
        								)
        							)
        					)
        						AS tab_735 (col_1146)
        		),
        	with_109 (col_1147, col_1148)
        		AS (SELECT * FROM (VALUES (NULL, e'7!$\x126$\x0b':::STRING:::NAME)) AS tab_736 (col_1147, col_1148))
        SELECT
        	(-15528):::INT8 AS col_1149, 'morning':::greeting AS col_1150, tab_737._inet AS col_1151
        FROM
        	with_109 AS cte_ref_33, defaultdb.public.seed@seed__int8__float8__date_idx AS tab_737
        WHERE
        	tab_737._bool
    --- FAIL: TestExplainGist/main (8.95s)
```

Parameters:
 - <code>attempt=1</code>
 - <code>run=19</code>
 - <code>shard=2</code>
<details><summary>Help</summary>
<p>

See also: [How To Investigate a Go Test Failure \(internal\)](https://cockroachlabs.atlassian.net/l/c/HgfXfJgM)
</p>
</details>
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*TestExplainGist.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/bazci/githubpost/issues)
</sub>

Jira issue: CRDB-41972

### PR DESCRIPTION
**Pull request by spilchen**
TestExplainGist occasionally fails when a query using a secondary index tries to fetch a column not included in that index (see issue #130282). This change doesn’t address the root cause, but instead ignores the error when it occurs. I've also created a more reliable reproducer in the TestDMLInjectionTest, which we can use to validate the eventual fix (#133129).

Epic: none
Closes #130282
Release note: none

### CODE REVIEW

File: pkg/sql/schemachanger/dml_injection_test.go [hunk 1]
```diff
@@ -523,6 +537,12 @@ func TestAlterTableDMLInjection(t *testing.T) {
 								require.Subset(t, expectedResults, actualResults, errorMessage)
 								require.Subset(t, actualResults, expectedResults, errorMessage)
 
+								// If a query is provided, run it without checking the results—just
+								// ensure it doesn't fail.
+								if tc.query != "" {
+									_ = sqlDB.QueryStr(t, tc.query)
```
Comment (rafiss) [inline pkg/sql/schemachanger/dml_injection_test.go:543]: super nit: this could use `Exec` instead of `QueryStr` since we don't care about the results.

**Review by rafiss — APPROVED** [review]

**Review by michae2 — APPROVED** [review]
:lgtm:

> Reviewed 1 of 2 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/133130#-:-O9u4-ay7ZcKz1SoTcOV:bnfp4nl)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @spilchen)

**Comment by spilchen** [comment]
TFTR!

bors r=rafiss,michae2

**Comment by spilchen** [comment]
@rafiss do you think we should backport this?

**Comment by rafiss** [comment]
I believe the test was only flaking on master, so there's not a strong need to backport. However, since the test is test-only, there's very low risk, so we may as well if there are no conflicts that need to be resolved manually.

**Comment by spilchen** [comment]
blathers backport 23.1 23.2 24.1 24.2 24.3

**Comment by spilchen** [comment]
We’re only doing automatic backports to 24.2 and 24.3, so we’ll stick with those versions.
