### PR TITLE
physical: ignore status message from aggregate stats collector

### LINKED ISSUE #154230: crosscluster/physical: TestStreamingZoneConfigsMismatchedRegions failed
crosscluster/physical.TestStreamingZoneConfigsMismatchedRegions [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Ci_TestsAwsLinuxArm64_UnitTests/20524653?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Ci_TestsAwsLinuxArm64_UnitTests/20524653?buildTab=artifacts#/) on master @ [cb0be5ffdd1589843614ae5a84114c3d8e726cd2](https://github.com/cockroachdb/cockroach/commits/cb0be5ffdd1589843614ae5a84114c3d8e726cd2):

```
=== RUN   TestStreamingZoneConfigsMismatchedRegions
    test_log_scope.go:171: test logs captured to: /artifacts/tmp/_tmp/9cca1e0b118933509f3f2f6a2527bece/logTestStreamingZoneConfigsMismatchedRegions2395393345
    test_log_scope.go:82: use -show-logs to present logs inline
    testutils.go:607: 
        	Error Trace:	pkg/crosscluster/replicationtestutils/testutils.go:607
        	            				pkg/crosscluster/replicationtestutils/testutils.go:296
        	            				pkg/crosscluster/physical/replication_stream_e2e_test.go:1513
        	Error:      	Not equal: 
        	            	expected: "replicating"
        	            	actual  : "initial scan on 4 out of 17 ranges"
        	            	
        	            	Diff:
        	            	--- Expected
        	            	+++ Actual
        	            	@@ -1 +1 @@
        	            	-replicating
        	            	+initial scan on 4 out of 17 ranges
        	Test:       	TestStreamingZoneConfigsMismatchedRegions
        	Messages:   	job should be in replicating state after reaching start time
    panic.go:635: -- test log scope end --
test logs left over in: /artifacts/tmp/_tmp/9cca1e0b118933509f3f2f6a2527bece/logTestStreamingZoneConfigsMismatchedRegions2395393345
--- FAIL: TestStreamingZoneConfigsMismatchedRegions (9.15s)
```
<details><summary>Help</summary>
<p>

See also: [How To Investigate a Go Test Failure \(internal\)](https://cockroachlabs.atlassian.net/l/c/HgfXfJgM)
</p>
</details>
/cc @cockroachdb/disaster-recovery
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*TestStreamingZoneConfigsMismatchedRegions.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/bazci/githubpost/issues)

</sub>

Jira issue: CRDB-54820

### PR DESCRIPTION
**Pull request by kev-cao**
#153893 taught PCR to update its status message based on the checkpoint events. However, as it also updates the status based on the range updates, this can cause race conditions that result in unexpected statuses. For now, we will ignore the status messages from the aggregate stats collector and keep the original behavior.

Epic: None

Fixes: #154230

### CODE REVIEW

File: pkg/crosscluster/replicationutils/stats.go [hunk 1]
```diff
@@ -89,13 +91,13 @@ func (r *AggregateRangeStatsCollector) RollupStats() (
 		(float32(total.RangeCount-incompleteCount) / float32(total.RangeCount)))
 
 	if len(r.stats) != r.processorCount || total.RangeCount == 0 {
-		return streampb.StreamEvent_RangeStats{}, 0, fmt.Sprintf("starting streams (%d out of %d)", len(r.stats), r.processorCount)
+		return streampb.StreamEvent_RangeStats{}, 0, jobspb.InitializingReplication, fmt.Sprintf("starting streams (%d out of %d)", len(r.stats), r.processorCount)
```
Comment (msbutler) [inline pkg/crosscluster/replicationutils/stats.go]: hrmm, i don't think the stats aggregator should be in the business of determining the replication status of PCR.

File: pkg/jobs/jobspb/wrap.go [hunk 2]
```diff
@@ -137,6 +138,8 @@ func (rs ReplicationStatus) String() string {
 		return "creating initial splits"
 	case InitialScan:
 		return "running initial scan"
+	case CatchupScan:
```
Comment (msbutler) [inline pkg/jobs/jobspb/wrap.go]: this feels out of scope for this patch. adding a new replication status has a bunch of downstream implications.

File: pkg/crosscluster/physical/stream_ingestion_frontier_processor.go [hunk 3]
```diff
@@ -361,8 +361,16 @@ func (sf *streamIngestionFrontier) maybeUpdateProgress() error {
 		if replicatedTime.IsSet() && streamProgress.ReplicationStatus == jobspb.InitialScan {
 			streamProgress.ReplicationStatus = jobspb.Replicating
 			md.Progress.StatusMessage = streamProgress.ReplicationStatus.String()
-		} else if statusByStats != "" {
```
Comment (msbutler) [inline pkg/crosscluster/physical/stream_ingestion_frontier_processor.go:364]: could we deflake this test by simply removing this condition added in the og PR? I feel like adding new metrics is a separate unit of work than updating the status message of PCR. Your og PR didn't add any e2e testing for metrics, which is fine. But, i think modifying status updates deserves it's own testing.

how about quickly deflake the test by removing this condition, then in a follow up, we think about how incorporate the status message updates into pcr?

**Review by msbutler — CHANGES_REQUESTED** [review]

**Review by msbutler — APPROVED** [review]
