### PR TITLE
backup: add start_time as suffix to incremental backup path

### LINKED ISSUE #142629: backup: compacted backups can clobber other compacted backups and fail
Using a heuristic for backup compactions (see #142367), means that the heuristic could potentially choose a backup chain such that the last backup in the chain is a compacted backup. The way that we currently resolve the destination for a compacted backup is to take the `end_time` of coverage and add 10 milliseconds before resolving it to a path. This prevents the path from clashing with the path of the last backup in the chain. 

However, if the last backup in the chain is a compacted backup, adding 10 milliseconds to its `end_time` will result in it an attempted compacted backup to the same location of the existing compacted backup. As such, all compaction jobs will continuously fail until the chain grows long enough that a better candidate is chosen by the heuristic.

Our proposed solution is to append the `start_time` of the backup to its resolved destination and remove the 10 millisecond padding entirely. While compacted backups may share end times with other backups in its chain, the `(start_time, end_time)` will always uniquely identify a backup and prevent destination conflicts. This also has an added side benefit of allowing us to manipulate `SHOW BACKUP`, displaying more compacted backups earlier.

Jira issue: CRDB-48452

### PR DESCRIPTION
**Pull request by kev-cao**
Due to the issues outlined in #142629, compacted backups can end up attempting to write to the same location as another compacted backup under the right conditions. This patch appends the `start_time` of an incremental as a suffix to its directory.

Fixes: #142629

Release note: None

### CODE REVIEW

File: pkg/backup/backupdest/backup_destination.go [hunk 1]
```diff
@@ -224,8 +233,39 @@ func ResolveDest(
 	}
 	prevBackupURIs = append([]string{plannedBackupDefaultURI}, prevBackupURIs...)
 
+	baseEncryptionOptions, err := backupencryption.GetEncryptionFromBase(
```
Comment (msbutler) [inline pkg/backup/backupdest/backup_destination.go:236]: could you push this into the if startTime.IsEmpty() block?

File: pkg/backup/backupdest/backup_destination.go [hunk 2]
```diff
@@ -224,8 +233,39 @@ func ResolveDest(
...
+			return ResolvedDestination{}, err
+		}
+		defer mem.Shrink(ctx, size)
+		startTime = precedingBackupManifest.EndTime
+		if startTime.IsEmpty() {
+			return ResolvedDestination{}, errors.Errorf("empty end time in prior backup manifest")
+		}
+	}
 	// Within the chosenSuffix dir, differentiate incremental backups with partName.
-	partName := endTime.GoTime().Format(backupbase.DateBasedIncFolderName)
```
Comment (msbutler) [inline pkg/backup/backupdest/backup_destination.go:228]: we need to add a 25.2 version gate here: in a mixed version cluster, we would not want a 25.2 node to begin the backup (writing the fancy new suffix), have that node die and have a helpless 25.1 node pick up the job and have no idea how to resolve its destination.

File: pkg/backup/backupdest/backup_destination.go [hunk 3]
```diff
@@ -224,8 +233,39 @@ func ResolveDest(
...
+	}
+
+	if startTime.IsEmpty() {
+		// TODO (kev-cao): Once we have completed the backup directory index work, we
+		// can remove the need to read an entire backup manifest just to fetch the
+		// start time. We can instead read the metadata protobuf.
+		mem := execCfg.RootMemoryMonitor.MakeBoundAccount()
+		defer mem.Close(ctx)
+		precedingBackupManifest, size, err := backupinfo.ReadBackupManifestFromURI(
+			ctx, &mem, prevBackupURIs[len(prevBackupURIs)-1], user,
```
Comment (msbutler) [inline pkg/backup/backupdest/backup_destination.go:251]: could you add one note: that we're assuming that FindPriorBackups returns prev backups in ascending end time order, i.e. the backup with the highest end time will be last in the list. We make this assumption later in the codebase as well.

Comment (msbutler) [reply pkg/backup/backupdest/backup_destination.go:251]: Uh oh:
>The order that results are passed to the callback is undefined.

https://github.com/kev-cao/cockroach/blob/backup/incremental-path-suffix/pkg/cloud/external_storage.go#L81

Comment (msbutler) [reply pkg/backup/backupdest/backup_destination.go:251]: Oh, lord have mercy.  We're good. Thought we had bad bad bug for a second.

https://github.com/kev-cao/cockroach/blob/backup/incremental-path-suffix/pkg/backup/backupdest/incrementals.go#L113

Comment (msbutler) [reply pkg/backup/backupdest/backup_destination.go:251]: Maybe add an extra line to FindPriorBackups explaining the order in which backups are returned lol

File: pkg/backup/backupdest/incrementals_test.go [hunk 4]
```diff
@@ -117,3 +125,131 @@ func TestJoinURLPath(t *testing.T) {
 	require.Equal(t, "/../path", backuputils.JoinURLPath("/top", "../../path"))
 
 }
+
+func TestFindPriorBackups(t *testing.T) {
+	defer leaktest.AfterTest(t)()
```
Comment (msbutler) [inline pkg/backup/backupdest/incrementals_test.go:130]: awesome test!!!!

File: pkg/backup/backupdest/incrementals_test.go [hunk 5]
```diff
@@ -117,3 +125,131 @@ func TestJoinURLPath(t *testing.T) {
...
+				"/20250320/003000.00",
+			},
+		},
+	} {
+		t.Run(tc.name, func(t *testing.T) {
+			store, err := execCfg.DistSQLSrv.ExternalStorageFromURI(
+				ctx, fmt.Sprintf("nodelocal://1/%d", idx), username.RootUserName(),
+			)
+			require.NoError(t, err)
+			defer store.Close()
```
Comment (msbutler) [inline pkg/backup/backupdest/incrementals_test.go:246]: nit: randomize the order of tc.paths? This will ensure FindPrioriBackups returns stuff in order, regardless of the input.

File: pkg/backup/backup_compaction_test.go [hunk 6]
```diff
@@ -340,6 +340,39 @@ crdb_internal.json_to_pb(
 			t, db, []string{"foo"}, "'nodelocal://1/backup/9'", start, end, opts,
 		)
 	})
+
+	t.Run("compaction of chain ending in a compacted backup", func(t *testing.T) {
+		// This test is to ensure that the second compaction job does not
+		// clobber the first compaction in the bucket. To do so, we take the
+		// following chain:
+		// F -> I1 -> I2 -> I3
+		// We compact I2 and I3 to get C1 and then compact I1 and C1 to get C2.
```
Comment (msbutler) [inline pkg/backup/backup_compaction_test.go:349]: nice description!

File: pkg/backup/backup_compaction_test.go [hunk 7]
```diff
@@ -340,6 +340,39 @@ crdb_internal.json_to_pb(
...
+		db.Exec(t, "INSERT INTO foo VALUES (3, 3)")
+		end := getTime(t)
+		db.Exec(t, fmt.Sprintf(incBackupAostCmd, 11, end))
+
+		c1JobID := startCompaction(11, mid, end)
+		waitForSuccessfulJob(t, tc, c1JobID)
+
+		c2JobID := startCompaction(11, start, end)
+		waitForSuccessfulJob(t, tc, c2JobID)
+		validateCompactedBackupForTables(t, db, []string{"foo"}, "'nodelocal://1/backup/11'", start, end)
```
Comment (msbutler) [inline pkg/backup/backup_compaction_test.go:374]: why does this validate cmd verify that C2 did not clobber C1? I would imagine that we'd want to check that both compacted backups appear in SHOW BACKUP, right?

**Review by msbutler — COMMENTED** [review]
Nice work here! This was a tough change and this is nearly there.

File: pkg/backup/backup_compaction_test.go (hunk 7 above)
Comment (kev-cao) [reply pkg/backup/backup_compaction_test.go:374]: Well `validateCompactedBackup` doesn't need to be call I guess — if it does clobber, we'll get a failed job since it won't be able to write to the location. That being said, I think I'll pull out the code from `validateCompactedBackupForTables` that checks if the backup exists using `SHOW BACKUP` so that we can test it explicitly here.

Comment (msbutler) [reply pkg/backup/backup_compaction_test.go:374]: sg, i think it would also be good to run and validate restore from both timestamps.

File: pkg/backup/backupdest/backup_destination.go (hunk 2 above)
Comment (msbutler) [reply pkg/backup/backupdest/backup_destination.go:228]: version gate looks good! let me know if you want to hop on a call to chat about any general questions about versioning in crdb

**Review by msbutler — APPROVED** [review]

**Comment by kev-cao** [comment]
TFTR!

bors r=msbutler
