### PR TITLE
workload/schemachanger: version gate JSON indexes in workload

### LINKED ISSUE #103452: roachtest: acceptance/mixed version flaked on master
See CI flake [here](https://teamcity.cockroachdb.com/viewLog.html?buildId=10114577&problemId=11989). Error that bubbled up:
```
(mixedversion.go:399).Run: mixed-version test failure while running step 19 (run "run backup"): pq: relation "table2" (184): PARTITION table2_part0: unimplemented: unable to encode JSON as a table key

```

Jira issue: CRDB-28007

### LINKED ISSUE #103758: roachtest: schemachange/mixed-versions failed
roachtest.schemachange/mixed-versions [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/10200554?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/10200554?buildTab=artifacts#/schemachange/mixed-versions) on master @ [a1b8517dd93d386fdf6b170982c604e6396b50e9](https://github.com/cockroachdb/cockroach/commits/a1b8517dd93d386fdf6b170982c604e6396b50e9):

```
test artifacts and logs in: /artifacts/schemachange/mixed-versions/run_1
(cluster.go:2060).Run: output in run_054044.408067101_n2_workload-run-schemac: ./workload run schemachange --verbose=1 --max-ops 100 --concurrency 5 {pgurl:1-4} returned: COMMAND_PROBLEM: ssh verbose log retained in ssh_054045.185203022_n2_workload-run-schemac.log: exit status 1
```
<p>Parameters: <code>ROACHTEST_cloud=gce</code>
, <code>ROACHTEST_cpu=4</code>
, <code>ROACHTEST_encrypted=false</code>
, <code>ROACHTEST_ssd=0</code>
</p>
<details><summary>Help</summary>
<p>

See: [roachtest README](https://github.com/cockroachdb/cockroach/blob/master/pkg/cmd/roachtest/README.md)

See: [How To Investigate \(internal\)](https://cockroachlabs.atlassian.net/l/c/SSSBr8c7)

</p>
</details>
/cc @cockroachdb/sql-foundations
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*schemachange/mixed-versions.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)
</sub>

Jira issue: CRDB-28177

### PR DESCRIPTION
**Pull request by fqazi**
Previously, the randomized schema changer workload could try to use JSON indexes in a mixed version state where not all nodes supported them. This could lead to errors during the randomized workload. To address this, this patch version gates CREATE INDEX statements to avoid JSON indexes until the active version is high enough.

Fixes: #103452
Fixes https://github.com/cockroachdb/cockroach/issues/103758

Release note: None

### CODE REVIEW

File: pkg/workload/schemachange/operation_generator.go [hunk 1]
```diff
@@ -1089,6 +1089,10 @@ func (og *operationGenerator) createIndex(ctx context.Context, tx pgx.Tx) (*opSt
 	duplicateRegionColumn := false
 	nonIndexableType := false
 	def.Columns = make(tree.IndexElemList, 1+og.randIntn(len(columnNames)))
+	jsonInvertedIndexesAllowed, err := isClusterVersionLessThan(ctx, tx, clusterversion.ByKey(clusterversion.V23_2))
```
Comment (rafiss) [inline pkg/workload/schemachange/operation_generator.go:1092]: this seems backwards -- the check is `version < 23.2` but the variable name is `jsonInvertedIndexesAllowed`. it should either be:
```
jsonInvertedIndexesAllowed, err := isClusterVersionGreaterThan(ctx, tx, clusterversion.ByKey(clusterversion.V23_2))
```
or
```
jsonInvertedIndexesNotSupported, err := isClusterVersionLessThan(ctx, tx, clusterversion.ByKey(clusterversion.V23_2))
```

**Review by rafiss — CHANGES_REQUESTED** [review]

File: pkg/workload/schemachange/operation_generator.go (hunk 1 above)
Comment (fqazi) [reply pkg/workload/schemachange/operation_generator.go]: Ah, good catch

**Review by rafiss — APPROVED** [review]

**Comment by fqazi** [comment]
@rafiss TFTR!

bors r+
