### PR TITLE
sql: protect WaitGroup decrement in CopyIn via sync.Once

### LINKED ISSUE #112095: sql: v23.1.11: panic in execCopyIn
This issue was auto filed by Sentry. It represents a crash or reported error on a live cluster with telemetry enabled.

Sentry Link: [https://cockroach-labs.sentry.io/issues/4538404754/?referrer=webhooks_plugin](https://cockroach-labs.sentry.io/issues/4538404754/?referrer=webhooks_plugin)

Panic Message:

```
conn_executor.go:900: panic: ×
(1) attached stack trace
  -- stack trace:
  | github.com/cockroachdb/cockroach/pkg/sql.(*Server).ServeConn.func1
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:900
  | [...repeated from below...]
Wraps: (2) attached stack trace
  -- stack trace:
  | github.com/cockroachdb/cockroach/pkg/sql.(*Server).ServeConn.func1
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:900
  | runtime.gopanic
  | 	GOROOT/src/runtime/panic.go:884
  | sync.(*WaitGroup).Add
  | 	GOROOT/src/sync/waitgroup.go:83
  | sync.(*WaitGroup).Done
  | 	GOROOT/src/sync/waitgroup.go:108
  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execCopyIn
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:3178
  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execCmd
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:2364
  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).run
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:2105
  | github.com/cockroachdb/cockroach/pkg/sql.(*Server).ServeConn
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:902
  | github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*conn).processCommandsAsync.func1
  | 	github.com/cockroachdb/cockroach/pkg/sql/pgwire/conn.go:310
  | runtime.goexit
  | 	GOROOT/src/runtime/asm_amd64.s:1594
Wraps: (3) panic: ×
Error types: (1) *withstack.withStack (2) *withstack.withStack (3) *errutil.leafError
-- report composition:
*errutil.leafError: panic: ×
conn_executor.go:900: *withstack.withStack (top exception)
conn_executor.go:900: *withstack.withStack (1)
(check the extra data payloads)
```

<details>
<summary>Stacktrace (expand for inline code snippets):</summary>

[GOROOT/src/runtime/asm_amd64.s#L1593-L1595](GOROOT/src/runtime/asm_amd64.s#L1593-L1595)
[https://github.com/cockroachdb/cockroach/blob/62ad175cbc0e9041d993ea1cc911e07d279671f5/pkg/sql/pgwire/conn.go#L309-L311](https://github.com/cockroachdb/cockroach/blob/62ad175cbc0e9041d993ea1cc911e07d279671f5/pkg/sql/pgwire/conn.go#L309-L311)
[https://github.com/cockroachdb/cockroach/blob/62ad175cbc0e9041d993ea1cc911e07d279671f5/pkg/sql/conn_executor.go#L901-L903](https://github.com/cockroachdb/cockroach/blob/62ad175cbc0e9041d993ea1cc911e07d279671f5/pkg/sql/conn_executor.go#L901-L903)
[https://github.com/cockroachdb/cockroach/blob/62ad175cbc0e9041d993ea1cc911e07d279671f5/pkg/sql/conn_executor.go#L2104-L2106](https://github.com/cockroachdb/cockroach/blob/62ad175cbc0e9041d993ea1cc911e07d279671f5/pkg/sql/conn_executor.go#L2104-L2106)
[https://github.com/cockroachdb/cockroach/blob/62ad175cbc0e9041d993ea1cc911e07d279671f5/pkg/sql/conn_executor.go#L2363-L2365](https://github.com/cockroachdb/cockroach/blob/62ad175cbc0e9041d993ea1cc911e07d279671f5/pkg/sql/conn_executor.go#L2363-L2365)
[https://github.com/cockroachdb/cockroach/blob/62ad175cbc0e9041d993ea1cc911e07d279671f5/pkg/sql/conn_executor.go#L3177-L3179](https://github.com/cockroachdb/cockroach/blob/62ad175cbc0e9041d993ea1cc911e07d279671f5/pkg/sql/conn_executor.go#L3177-L3179)
[GOROOT/src/sync/waitgroup.go#L107-L109](GOROOT/src/sync/waitgroup.go#L107-L109)
[GOROOT/src/sync/waitgroup.go#L82-L84](GOROOT/src/sync/waitgroup.go#L82-L84)
[GOROOT/src/runtime/panic.go#L883-L885](GOROOT/src/runtime/panic.go#L883-L885)
[https://github.com/cockroachdb/cockroach/blob/62ad175cbc0e9041d993ea1cc911e07d279671f5/pkg/sql/conn_executor.go#L899-L901](https://github.com/cockroachdb/cockroach/blob/62ad175cbc0e9041d993ea1cc911e07d279671f5/pkg/sql/conn_executor.go#L899-L901)
</details>

```
GOROOT/src/runtime/asm_amd64.s in runtime.goexit at line 1594
pkg/sql/pgwire/conn.go in pkg/sql/pgwire.(*conn).processCommandsAsync.func1 at line 310
pkg/sql/conn_executor.go in pkg/sql.(*Server).ServeConn at line 902
pkg/sql/conn_executor.go in pkg/sql.(*connExecutor).run at line 2105
pkg/sql/conn_executor.go in pkg/sql.(*connExecutor).execCmd at line 2364
pkg/sql/conn_executor.go in pkg/sql.(*connExecutor).execCopyIn at line 3178
GOROOT/src/sync/waitgroup.go in sync.(*WaitGroup).Done at line 108
GOROOT/src/sync/waitgroup.go in sync.(*WaitGroup).Add at line 83
GOROOT/src/runtime/panic.go in runtime.gopanic at line 884
pkg/sql/conn_executor.go in pkg/sql.(*Server).ServeConn.func1 at line 900
```

### Tags

| Tag | Value |
| --- | --- |
| Command | server |
| Environment | v23.1.11 |
| Go Version | go1.19.10 |
| Platform | linux amd64 |
| Distribution | CCL |
| Cockroach Release | v23.1.11 |
| Cockroach SHA | 62ad175cbc0e9041d993ea1cc911e07d279671f5 |
| # of CPUs | 12 |
| # of Goroutines | 5797 |

Jira issue: CRDB-32233
Epic CRDB-34178

### PR DESCRIPTION
**Pull request by yuzefovich**
We've recently seen "negative WaitGroup counter" server crash during COPY FROM execution a few times, but we have been unable to understand the root cause. It appears that the problem can happen right after the COPY execution is canceled due to `statement_timeout`. The synchronization setup is the following:
- the network-handling goroutine calls `wg.Add(1)`, pushes CopyIn command onto the stmt buf, and then blocks via `wg.Wait()`
- the copy-handling connExecutor calls `wg.Done()` in the defer of `execCopyIn`. It must be the case that that defer is executed at least twice, but it's unclear to me how that can happen.

In the absence of understanding of how this can happen and with no reproduction, this commit attempts to mitigate the problem by ensuring that `wg.Done()` is called exactly once. This is achieved via `sync.Once`.

Fixes: #112095.

Release note: None

### CODE REVIEW

**Comment by yuzefovich** [comment]
I'm not very happy with this change, but I don't have any other ideas on how to mitigate #112095 / https://github.com/cockroachlabs/support/issues/2741. Curious about thoughts on whether it's worth making this change or not.

File: pkg/sql/conn_executor.go [hunk 1]
```diff
@@ -3006,7 +3006,9 @@ func (ex *connExecutor) execCopyIn(
 	}()
 
 	// When we're done, unblock the network connection.
-	defer cmd.CopyDone.Done()
+	defer func() {
```
Comment (rafiss) [inline pkg/sql/conn_executor.go:3009]: one more idea instead of a buffered channel: could we change this to something like:
```
once.Do(func() { close(ch) })
```
or
```
once.Do(func() { cmd.CopyDone.Done() })
```

**Review by yuzefovich — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/115712)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @michae2 and @rafiss)

___
*[`pkg/sql/conn_executor.go` line 3009 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/115712#gh-1417880287:-Nl-hQ9n2o-r2_Ey3AjJ:b-p1fz7h) ([raw file](https://github.com/cockroachdb/cockroach/blob/396f7b2a041f25ccd37241f4b7eeacddb4a84e4d/pkg/sql/conn_executor.go#L3009)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

one more idea instead of a buffered channel: could we change this to something like:
```
once.Do(func() { close(cmd.CopyDone) })
```
or
```
once.Do(func() { cmd.CopyDone.Done() })
```
</blockquote></details>

I like it, thanks, done.

File: pkg/sql/conn_io.go [hunk 2]
```diff
@@ -370,6 +370,8 @@ type CopyIn struct {
 	// CopyDone is decremented once execution finishes, signaling that control of
 	// the connection is being handed back to the network routine.
 	CopyDone *sync.WaitGroup
+	// Once is used to decrement CopyDone exactly once.
+	Once *sync.Once
```
Comment (rafiss) [inline pkg/sql/conn_io.go:374]: one thought i had is if this would be more clear with an embedded struct:
```
	CopyDone struct {
		*sync.WaitGroup
		*sync.Once
	}
```

(so that it's obvious the two should be used together

**Review by rafiss — APPROVED** [review]
lgtm. ty for fixing!

**Review by yuzefovich — COMMENTED** [review]
TFTR!

bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/115712#-:-Nl4Glx64obHCbRDPPXP:b-oduykh)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @michae2 and @rafiss)

___
*[`pkg/sql/conn_io.go` line 374 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/115712#gh-1418238698:-Nl4GkCL3QuxNs6bJiz8:b-bhrc22) ([raw file](https://github.com/cockroachdb/cockroach/blob/9fb1d63a35ae0bc8b931648f8951768eb106d348/pkg/sql/conn_io.go#L374)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

one thought i had is if this would be more clear with an embedded struct:
```
	CopyDone struct {
		*sync.WaitGroup
		*sync.Once
	}
```

(so that it's obvious the two should be used together
</blockquote></details>

Very nice, done.

**Review by rafiss — APPROVED** [review]

**Comment by yuzefovich** [comment]
blathers backport 23.2.0

**Comment by yuzefovich** [comment]
blathers backport 23.2.0-rc
