### PR TITLE
sql/catalog/lease: attempt to fix flake

### LINKED ISSUE #78479: ccl/changefeedccl: TestChangefeedSchemaChangeAllowBackfill failed
ccl/changefeedccl.TestChangefeedSchemaChangeAllowBackfill [failed](https://teamcity.cockroachdb.com/viewLog.html?buildId=4672429&tab=buildLog) with [artifacts](https://teamcity.cockroachdb.com/viewLog.html?buildId=4672429&tab=artifacts#/) on master @ [d2a588523715f914906f08b1365f8fc9c8ae2805](https://github.com/cockroachdb/cockroach/commits/d2a588523715f914906f08b1365f8fc9c8ae2805):

```
=== RUN   TestChangefeedSchemaChangeAllowBackfill
    test_log_scope.go:79: test logs captured to: /artifacts/tmp/_tmp/a77002d7c9453d7cd2d382f907780e13/logTestChangefeedSchemaChangeAllowBackfill1739784690
    test_log_scope.go:80: use -show-logs to present logs inline
=== CONT  TestChangefeedSchemaChangeAllowBackfill
    changefeed_test.go:1611: -- test log scope end --
--- FAIL: TestChangefeedSchemaChangeAllowBackfill (37.46s)
=== RUN   TestChangefeedSchemaChangeAllowBackfill/kafka/add_column_computed
    changefeed_test.go:1487: 
        	Error Trace:	helpers_test.go:159
        	            				helpers_test.go:211
        	            				changefeed_test.go:1487
        	Error:      	Received unexpected error:
        	            	lease-insert: duplicate key value violates unique constraint "primary"
        	            	(1) attached stack trace
        	            	  -- stack trace:
        	            	  | github.com/cockroachdb/cockroach/pkg/ccl/changefeedccl.(*jobFeed).FetchTerminalJobErr
        	            	  | 	github.com/cockroachdb/cockroach/pkg/ccl/changefeedccl/testfeed_test.go:352
        	            	  | github.com/cockroachdb/cockroach/pkg/ccl/changefeedccl.(*jobFeed).jobFailed
        	            	  | 	github.com/cockroachdb/cockroach/pkg/ccl/changefeedccl/testfeed_test.go:268
        	            	  | github.com/cockroachdb/cockroach/pkg/ccl/changefeedccl.(*reportErrorResumer).OnFailOrCancel
        	            	  | 	github.com/cockroachdb/cockroach/pkg/ccl/changefeedccl/testfeed_test.go:218
        	            	  | github.com/cockroachdb/cockroach/pkg/jobs.(*Registry).stepThroughStateMachine.func3
        	            	  | 	github.com/cockroachdb/cockroach/pkg/jobs/registry.go:1218
        	            	  | github.com/cockroachdb/cockroach/pkg/jobs.(*Registry).stepThroughStateMachine
        	            	  | 	github.com/cockroachdb/cockroach/pkg/jobs/registry.go:1219
        	            	  | github.com/cockroachdb/cockroach/pkg/jobs.(*Registry).stepThroughStateMachine
        	            	  | 	github.com/cockroachdb/cockroach/pkg/jobs/registry.go:1168
        	            	  | github.com/cockroachdb/cockroach/pkg/jobs.(*Registry).runJob
        	            	  | 	github.com/cockroachdb/cockroach/pkg/jobs/adopt.go:408
        	            	  | github.com/cockroachdb/cockroach/pkg/jobs.(*StartableJob).Start.func2
        	            	  | 	github.com/cockroachdb/cockroach/pkg/jobs/jobs.go:942
        	            	  | github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunAsyncTaskEx.func2
        	            	  | 	github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:494
        	            	  | runtime.goexit
        	            	  | 	GOROOT/src/runtime/asm_amd64.s:1581
        	            	Wraps: (2) lease-insert: duplicate key value violates unique constraint "primary"
        	            	Error types: (1) *withstack.withStack (2) *errutil.leafError
        	Test:       	TestChangefeedSchemaChangeAllowBackfill/kafka/add_column_computed
        --- FAIL: TestChangefeedSchemaChangeAllowBackfill/kafka/add_column_computed (0.18s)
=== RUN   TestChangefeedSchemaChangeAllowBackfill/kafka
    --- FAIL: TestChangefeedSchemaChangeAllowBackfill/kafka (4.45s)
```
<details><summary>Help</summary>
<p>

See also: [How To Investigate a Go Test Failure \(internal\)](https://cockroachlabs.atlassian.net/l/c/HgfXfJgM)
Parameters in this failure:

- TAGS=bazel,gss
</p>
</details>
/cc @cockroachdb/cdc
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*TestChangefeedSchemaChangeAllowBackfill.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)
</sub>

Jira issue: CRDB-14147

Epic CRDB-11732

### PR DESCRIPTION
**Pull request by ajwerner**
It's not really clear exactly how we run into a conflict, we'd
need to pick the same expiration as an already existing lease but
not the same as the current lease. This means that the lease which
we conflict with must be in the process of being dropped. We'll
handle the edge case, but I'm not sure how to test whether it
happens in practice.

Fixes #78479.

Release note: None

### CODE REVIEW

File: pkg/sql/catalog/lease/storage.go [hunk 1]
```diff
@@ -167,11 +169,15 @@ func (s storage) acquire(
...
 		err := s.db.Txn(ctx, acquireInTxn)
 		var pErr *roachpb.AmbiguousResultError
-		if errors.As(err, &pErr) {
+		switch {
+		case errors.As(err, &pErr):
 			log.Infof(ctx, "ambiguous error occurred during lease acquisition for %v, retrying: %v", id, err)
 			continue
-		}
-		if err != nil {
+		case pgerror.GetPGCode(err) == pgcode.UniqueViolation:
```
Comment (postamar) [inline pkg/sql/catalog/lease/storage.go:176]: Couldn't we instead salt the least significant bits of the jittered expiration timestamp somehow to prevent collisions?

Comment (ajwerner) [reply pkg/sql/catalog/lease/storage.go:176]: How does that help?

Comment (postamar) [reply pkg/sql/catalog/lease/storage.go:176]: The expiration timestamp is guaranteed to be unique for that node and since that's part of the PK we won't ever be inserting duplicate rows.

I'm obviously misunderstanding something here but I have no idea what.

Comment (ajwerner) [reply pkg/sql/catalog/lease/storage.go:176]: We're already jittering randomly by 5%. The hazard is that the same node picks a timestamp which is now + 5m +/- 5% and then releases it and then picks another one and it happens to be the same. This is a ~1/5M conflict (we store leases at microsecond resolution). Seems very very rare. Maybe there's something else going on, but I couldn't spot it.

Comment (postamar) [reply pkg/sql/catalog/lease/storage.go:176]: This matches my understanding. I was suggesting we maintain a global `var jitterCounter int64` with which we call `jitteredLeaseDuration(atomic.AddInt64(&jitterCounter, 1))` which salts the timestamp somehow, perhaps by overwriting the least significant 20 bits.

I took a bit more time to see how `rand.Float64` works and it seems exceedingly unlikely that collisions would occur unless `descriptor_lease_duration` and `descriptor_lease_jitter_fraction` were set to ridiculous values, which doesn't appear to be the case. The random number generator's internal state is protected by a mutex so each call to `rand.Float64` should generate a unique-enough value regardless of concurrency.

Comment (postamar) [reply pkg/sql/catalog/lease/storage.go:176]: So, the likelihood of a collision would be on the order or one in ten million: "rare but not rare enough" sounds about right to me.

**Review by postamar — APPROVED** [review]
I'm sold.
