### PR TITLE
sql: use SQLInstanceID in EXPLAIN instead of OptionalNodeIDErr

### LINKED ISSUE #49072: sql: handle unavailable node ID in EXPLAIN (DISTSQL)
Some logic tests fail because EXPLAIN (DISTSQL) uses a node ID to generate flow specs. We should figure out how to make it work without one or handle the case where it isn't available more gracefully.

### PR DESCRIPTION
**Pull request by asubiotto**
Tenants would previously not be able to run EXPLAIN because they wouldn't have
access to a NodeID. This is now fixed by using the SQLInstanceID instead, which
will provide an expected SQL-scoped identifier in a multi-tenant environment
and will translate to a NodeID in a single-tenant environment.

Release note: None (multitenancy-related change)

Closes #49072

### CODE REVIEW

File: pkg/sql/explain_distsql.go [hunk 1]
```diff
@@ -227,11 +227,7 @@ func (n *explainDistSQLNode) startExec(params runParams) error {
 		}
 		diagram.AddSpans(spans)
 	} else {
-		nodeID, err := params.extendedEvalCtx.NodeID.OptionalNodeIDErr(distsql.MultiTenancyIssueNo)
-		if err != nil {
-			return err
-		}
-		flows := plan.GenerateFlowSpecs(nodeID)
+		flows := plan.GenerateFlowSpecs(roachpb.NodeID(params.extendedEvalCtx.NodeID.SQLInstanceID()))
```
Comment (tbg) [inline pkg/sql/explain_distsql.go:230]: Casting to NodeID makes me uneasy on general principles as confusing them in general can lead to correctness problems. Can you get away with a zero NodeID here and elsewhere? Taking a step back, SQL flows for a tenant will never be scheduled on a "Node" in a multi-tenant world, it will always be a tenant. I don't think we necessarily want to do the code changes for that now (since we won't schedule nonlocal flows anyway, at least not for the time being), but it seems good to keep the concepts as separate as we can until then.

Comment (asubiotto) [reply pkg/sql/explain_distsql.go:230]: I agree. the best way to go about this is to change `GenerateFlowSpecs` to work with SQL instance IDs, but that'll mean changing a lot of the planning code which doesn't seem worth to do at this stage. I'm not sure whether a 0 node ID would work.

My goal was to just get `EXPLAIN` working. I think having this cast is worth the cost of making that work. I should at least add a TODO here though. Do you prefer to hold off on merging this?

Comment (tbg) [reply pkg/sql/explain_distsql.go:230]: No, this looks like a SQL team decision and that's you :-) Go ahead and merge.

Comment (asubiotto) [reply pkg/sql/explain_distsql.go:232]: Added a TODO and a linked issue.

**Review by tbg — APPROVED** [review]

**Comment by asubiotto** [comment]
bors r=tbg
