### PR TITLE
changefeedccl: fix job progress checkpoint fields invariant violation

### LINKED ISSUE #148560: roachtest: cdc/mixed-version/checkpointing failed
roachtest.cdc/mixed-version/checkpointing [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/19971991?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/19971991?buildTab=artifacts#/cdc/mixed-version/checkpointing) on master @ [1dcc89f79cebeaafbfb350f879e8b3db3c14a4f1](https://github.com/cockroachdb/cockroach/commits/1dcc89f79cebeaafbfb350f879e8b3db3c14a4f1):

```
(test_runner.go:1420).runTest: test timed out (3h0m0s)
test artifacts and logs in: /artifacts/cdc/mixed-version/checkpointing/run_1
```

Parameters:
 - <code>arch=amd64</code>
 - <code>cloud=gce</code>
 - <code>coverageBuild=false</code>
 - <code>cpu=4</code>
 - <code>encrypted=false</code>
 - <code>fs=ext4</code>
 - <code>localSSD=true</code>
 - <code>mvtDeploymentMode=system-only</code>
 - <code>mvtVersions=v24.3.9 → v25.2.0 → master</code>
 - <code>runtimeAssertionsBuild=false</code>
 - <code>ssd=0</code>
<details><summary>Help</summary>
<p>

See: [roachtest README](https://github.com/cockroachdb/cockroach/blob/master/pkg/cmd/roachtest/README.md)

See: [How To Investigate \(internal\)](https://cockroachlabs.atlassian.net/l/c/SSSBr8c7)

See: [Grafana](https://go.crdb.dev/roachtest-grafana/teamcity-19971991/cdc-mixed-version-checkpointing/1750319469909/1750330420437)

</p>
</details>
/cc @cockroachdb/cdc
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*cdc/mixed-version/checkpointing.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/bazci/githubpost/issues)

</sub>

Jira issue: CRDB-51671

### LINKED ISSUE #148620: changefeedccl: job progress checkpoint fields invariant violation
An assertion failure with the error message `both legacy and current checkpoint set on change aggregator spec` may cause a changefeed that was created and running on versions <25.2 to fail after the cluster is upgraded to 25.2. This may happen if the changefeed had a span-level checkpoint at the time the cluster is upgraded. The bug will often be mitigated because the span-level checkpoint will be cleared whenever the highwater is updated and not enough time has passed to write another one.

This issue was detected by the mixed-version roachtest in #148560.

Jira issue: CRDB-51701

### PR DESCRIPTION
**Pull request by andyyang890**
Fixes #148560
Fixes #148620

---

**changefeedccl: avoid creating checkpoint string all the time**

This patch modifies the changefeed job progress saving code so that
we only create a string for a span-level checkpoint when we actually
need it for logging.

Release note: None

---

**changefeedccl: fix job progress checkpoint fields invariant violation**

Release note (bug fix): A bug where a changefeed that was created before
v25.2 could fail after upgrading to v25.2 with the error message
`both legacy and current checkpoint set on change aggregator spec`
has now been fixed.

### CODE REVIEW

**Comment by andyyang890** [comment]
TeamCity run with 20 successful runs of `cdc/mixed-version/checkpointing` with the same seed as the original test failure (`-8499046220098865847`): https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/19997835?buildTab=overview&hideProblemsFromDependencies=false&hideTestsFromDependencies=false&expandBuildChangesSection=true

**Review by asg0451 — APPROVED** [review]

**Comment by asg0451** [comment]
lgtm but consider adding a regression test for this if it's not too much work

File: pkg/ccl/changefeedccl/alter_changefeed_stmt.go [hunk 1]
```diff
@@ -859,21 +861,15 @@ func generateNewProgress(
 }
 
 func removeSpansFromProgress(
-	prevProgress jobspb.Progress, spansToRemove []roachpb.Span, statementTime hlc.Timestamp,
+	progress jobspb.Progress, spansToRemove []roachpb.Span, statementTime hlc.Timestamp,
 ) error {
-	changefeedProgress := prevProgress.GetChangefeed()
-	if changefeedProgress == nil {
```
Comment (asg0451) [inline pkg/ccl/changefeedccl/alter_changefeed_stmt.go:865]: is this a bug? did this mean that alters would fail to remove tables from new style checkpoints?

**Comment by andyyang890** [comment]
> lgtm but consider adding a regression test for this if it's not too much work

We discussed this offline and unfortunately we can't add a test-only assertion that this bug won't happen anymore because it'll cause the mixed-version test to fail when it tries upgrading from earlier versions of 25.2 that still had the bug. I'll add the assertion to the 25.2 backport though.

**Comment by andyyang890** [comment]
TFTR!

bors r=asg0451

File: pkg/ccl/changefeedccl/changefeed_dist.go [hunk 2]
```diff
@@ -261,16 +261,33 @@ func startDistChangefeed(
...
+				"changefeed job progress and legacy checkpoint has later timestamp")
+		}
+		// This should be an assertion failure but unfortunately due to a bug
+		// that was included in earlier versions of 25.2 (#148620), we may fail
+		// to clear the legacy checkpoint when we start writing the new one.
+		// We instead discard the legacy checkpoint here and it will eventually be
+		// cleared once the cluster is running a newer patch release with the fix.
+		log.Warningf(ctx, "both legacy and current checkpoint set on changefeed job progress; "+
+			"discarding legacy checkpoint")
+		legacyCheckpoint = nil
```
Comment (asg0451) [inline pkg/ccl/changefeedccl/changefeed_dist.go:287]: reading makePlan i'm a little concerned that this could result in a nil ptr panic. do you think we have test coverage for this?

**Review by asg0451 — APPROVED** [review]

File: pkg/ccl/changefeedccl/alter_changefeed_stmt.go (hunk 1 above)
Comment (andyyang890) [reply pkg/ccl/changefeedccl/alter_changefeed_stmt.go:865]: Yeah it appears so

File: pkg/ccl/changefeedccl/changefeed_dist.go (hunk 2 above)
Comment (andyyang890) [reply pkg/ccl/changefeedccl/changefeed_dist.go:287]: It should be fine given the legacy checkpoint will be nil most of the time (i.e. either when no span-level checkpoint is set or in the cases where only the new checkpoint is set, which would be true for any changefeeds created on 25.2+)

**Comment by andyyang890** [comment]
blathers backport 25.3
