### PR TITLE
backupccl: all full cluster restore of backup with no user data

### LINKED ISSUE #49573: backupccl: full cluster restore fails to restore a full cluster backup with no user tables
**Describe the problem**

When restoring a full cluster backup that did not have any user tables, the restore fails. Note: that there is an error on 20.1.1, but the planning of the RESTORE will hang on earlier versions.

**To Reproduce**

In a SQL shell on a fresh cluster:
```sql
BACKUP TO 'nodelocal://1/test';
RESTORE FROM 'nodelocal://1/test';
```
We see the error: `pq: restoring 0 TableDescriptors from 1 databases: restoring table desc and namespace entries: table already exists` (and a hang on earlier versions).

### PR DESCRIPTION
**Pull request by pbardea**
This commit fixes a bug in which full cluster restore assumed that a
full cluster backup had at least one user database/table to restore.

Fixes #49573.

Release note (bug fix): Previously, if one attempted to perform a full
cluster RESTORE on a backup that did not contain any user data it would
fail.

### CODE REVIEW

File: pkg/ccl/backupccl/restore_job.go [hunk 1]
```diff
@@ -889,15 +889,15 @@ func createImportingTables(
 			}
 		}
 	}
-	var tempSystemDBID sqlbase.ID
+	tempSystemDBID := uint32(keys.MinNonPredefinedUserDescID)
```
Comment (miretskiy) [inline pkg/ccl/backupccl/restore_job.go:892]: Why do we need to cast to uint32?

File: pkg/ccl/backupccl/backup_test.go [hunk 2]
```diff
@@ -97,6 +97,32 @@ func backupRestoreTestSetupEmptyWithParams(
...
+
+	dir, dirCleanupFn := testutils.TempDir(t)
+	params := base.TestClusterArgs{}
+	params.ServerArgs.ExternalIODir = dir
+	tc = testcluster.StartTestCluster(t, clusterSize, params)
+
+	sqlDB = sqlutils.MakeSQLRunner(tc.Conns[0])
+
+	cleanupFn := func() {
+		tc.Stopper().Stop(context.Background()) // cleans up in memory storage's auxiliary dirs
```
Comment (miretskiy) [inline pkg/ccl/backupccl/backup_test.go:119]: ctx instead?

File: pkg/ccl/backupccl/backup_test.go [hunk 3]
```diff
@@ -97,6 +97,32 @@ func backupRestoreTestSetupEmptyWithParams(
...
+		dirCleanupFn()                          // cleans up dir, which is the nodelocal:// storage
+	}
+
+	return ctx, tc, sqlDB, dir, cleanupFn
```
Comment (miretskiy) [inline pkg/ccl/backupccl/backup_test.go:123]: do we need to return ctx and tc? These don't appear to be used

File: pkg/ccl/backupccl/backup_test.go [hunk 4]
```diff
@@ -97,6 +97,32 @@ func backupRestoreTestSetupEmptyWithParams(
 	return ctx, tc, sqlDB, cleanupFn
 }
 
+func createEmptyCluster(
```
Comment (miretskiy) [inline pkg/ccl/backupccl/backup_test.go:100]: should this function be moved to full_cluster_backup_restore_test where it is used?

**Review by miretskiy — APPROVED** [review]

File: pkg/ccl/backupccl/backup_test.go (hunk 4 above)
Comment (pbardea) [reply pkg/ccl/backupccl/backup_test.go]: Good point - I also moved the other cluster creation helper which is only used in full cluster tests.

File: pkg/ccl/backupccl/backup_test.go (hunk 3 above)
Comment (pbardea) [reply pkg/ccl/backupccl/backup_test.go]: I originally kept this to keep a consistent interface with the other creation helpers in case we wanted an easy drop-in replacement to those. But I think we can add those when we need it.

File: pkg/ccl/backupccl/backup_test.go (hunk 2 above)
Comment (pbardea) [reply pkg/ccl/backupccl/backup_test.go]: Yep - I've also updated the other creation helpers.

File: pkg/ccl/backupccl/restore_job.go (hunk 1 above)
Comment (pbardea) [reply pkg/ccl/backupccl/restore_job.go]: Done - was flipping back and forth about which side of the comparison below to cast and ended up casting both. Int will suffice.

**Comment by pbardea** [comment]
Thanks for the quick review!
bors r=miretskiy
