### PR TITLE
storage: do not share *roachpb.Error

### LINKED ISSUE #6099: stability: data race in storage.(*Store).Send.func1()
build sha: 78369d7 with `--race`

[rho](https://rho.gce.cockroachdb.com:8080/) cluster (4 nodes with photos and block_writers running against each node). Behavior will be subtly different from the regular cluster since the race detector blows up cpu and memory.

Only one data race found so far, about ~1h after startup. (it's been ~12h).
```
==================
WARNING: DATA RACE
Write by goroutine 55:
  github.com/cockroachdb/cockroach/storage.(*Store).Send.func1()
      /home/marc/cockroach/src/github.com/cockroachdb/cockroach/storage/store.go:1589 +0x3d6
  github.com/cockroachdb/cockroach/storage.(*Store).Send()
      /home/marc/cockroach/src/github.com/cockroachdb/cockroach/storage/store.go:1699 +0x1b97
  github.com/cockroachdb/cockroach/storage.(*Stores).Send()
      /home/marc/cockroach/src/github.com/cockroachdb/cockroach/storage/stores.go:178 +0x67e
  github.com/cockroachdb/cockroach/server.(*Node).Batch.func2()
      /home/marc/cockroach/src/github.com/cockroachdb/cockroach/server/node.go:729 +0x698
  github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunTask()
      /home/marc/cockroach/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:166 +0xeb
  github.com/cockroachdb/cockroach/server.(*Node).Batch()
      /home/marc/cockroach/src/github.com/cockroachdb/cockroach/server/node.go:741 +0x40b
  github.com/cockroachdb/cockroach/roachpb._Internal_Batch_Handler()
      /home/marc/cockroach/src/github.com/cockroachdb/cockroach/roachpb/api.pb.go:1306 +0x150
  google.golang.org/grpc.(*Server).processUnaryRPC()
      /home/marc/cockroach/src/google.golang.org/grpc/server.go:497 +0x11c0
  google.golang.org/grpc.(*Server).handleStream()
      /home/marc/cockroach/src/google.golang.org/grpc/server.go:646 +0x1418
  google.golang.org/grpc.(*Server).serveStreams.func1.1()
      /home/marc/cockroach/src/google.golang.org/grpc/server.go:323 +0xad

Previous write by goroutine 213:
  github.com/cockroachdb/cockroach/storage.(*Store).Send.func1()
      /home/marc/cockroach/src/github.com/cockroachdb/cockroach/storage/store.go:1589 +0x3d6
  github.com/cockroachdb/cockroach/storage.(*Store).Send()
      /home/marc/cockroach/src/github.com/cockroachdb/cockroach/storage/store.go:1699 +0x1b97
  github.com/cockroachdb/cockroach/storage.(*Stores).Send()
      /home/marc/cockroach/src/github.com/cockroachdb/cockroach/storage/stores.go:178 +0x67e
  github.com/cockroachdb/cockroach/server.(*Node).Batch.func2()
      /home/marc/cockroach/src/github.com/cockroachdb/cockroach/server/node.go:729 +0x698
  github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunTask()
      /home/marc/cockroach/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:166 +0xeb
  github.com/cockroachdb/cockroach/server.(*Node).Batch()
      /home/marc/cockroach/src/github.com/cockroachdb/cockroach/server/node.go:741 +0x40b
  github.com/cockroachdb/cockroach/roachpb._Internal_Batch_Handler()
      /home/marc/cockroach/src/github.com/cockroachdb/cockroach/roachpb/api.pb.go:1306 +0x150
  google.golang.org/grpc.(*Server).processUnaryRPC()
      /home/marc/cockroach/src/google.golang.org/grpc/server.go:497 +0x11c0
  google.golang.org/grpc.(*Server).handleStream()
      /home/marc/cockroach/src/google.golang.org/grpc/server.go:646 +0x1418
  google.golang.org/grpc.(*Server).serveStreams.func1.1()
      /home/marc/cockroach/src/google.golang.org/grpc/server.go:323 +0xad

Goroutine 55 (running) created at:
  google.golang.org/grpc.(*Server).serveStreams.func1()
      /home/marc/cockroach/src/google.golang.org/grpc/server.go:324 +0xa7
  google.golang.org/grpc/transport.(*http2Server).operateHeaders()
      /home/marc/cockroach/src/google.golang.org/grpc/transport/http2_server.go:213 +0x19c8
  google.golang.org/grpc/transport.(*http2Server).HandleStreams()
      /home/marc/cockroach/src/google.golang.org/grpc/transport/http2_server.go:272 +0xf56
  google.golang.org/grpc.(*Server).serveStreams()
      /home/marc/cockroach/src/google.golang.org/grpc/server.go:325 +0x1dc
  google.golang.org/grpc.(*Server).serveNewHTTP2Transport()
      /home/marc/cockroach/src/google.golang.org/grpc/server.go:312 +0x54d
  google.golang.org/grpc.(*Server).handleRawConn()
      /home/marc/cockroach/src/google.golang.org/grpc/server.go:289 +0x5b1

Goroutine 213 (finished) created at:
  google.golang.org/grpc.(*Server).serveStreams.func1()
      /home/marc/cockroach/src/google.golang.org/grpc/server.go:324 +0xa7
  google.golang.org/grpc/transport.(*http2Server).operateHeaders()
      /home/marc/cockroach/src/google.golang.org/grpc/transport/http2_server.go:213 +0x19c8
  google.golang.org/grpc/transport.(*http2Server).HandleStreams()
      /home/marc/cockroach/src/google.golang.org/grpc/transport/http2_server.go:272 +0xf56
  google.golang.org/grpc.(*Server).serveStreams()
      /home/marc/cockroach/src/google.golang.org/grpc/server.go:325 +0x1dc
  google.golang.org/grpc.(*Server).serveNewHTTP2Transport()
      /home/marc/cockroach/src/google.golang.org/grpc/server.go:312 +0x54d
  google.golang.org/grpc.(*Server).handleRawConn()
      /home/marc/cockroach/src/google.golang.org/grpc/server.go:289 +0x5b1
==================
```

Node 1 (`104.196.105.82`) log from startup until a few seconds past data race:
[data_race.txt](https://github.com/cockroachdb/cockroach/files/222561/data_race.txt)

Full node log (until nowish):
[node1.log.txt.gz](https://github.com/cockroachdb/cockroach/files/222562/node1.log.txt.gz)

### LINKED ISSUE #6100: stability: data race in error during shutdown
Build sha: 78369d7 with race detector enabled.

Rho cluster, ran with load for a while. I went through a full shutdown of the cluster (one node at a time: shut down node N+1 when node N finally exited, usually after shutdown timeout).

The very last node to be shutdown detected a data race.
Relevant lines from shutdown timing:
```
I160417 16:05:31.031335 cli/start.go:222  initiating graceful shutdown of server
E160417 16:06:31.031866 cli/start.go:245  time limit reached, initiating hard shutdown
```

Data race (plus some surrounding log lines):
```
I160417 16:05:46.032154 cli/start.go:234  8 running tasks
I160417 16:05:46.063724 /home/marc/cockroach/src/google.golang.org/grpc/clientconn.go:462  grpc: Conn.resetTransport failed to create client transport: connection error: desc = "transport: dial tcp 10.240.0.10:26257: getsockopt: connection refused"; Reconnecting to "cockroach-rho-3:26257"
I160417 16:05:46.067796 /home/marc/cockroach/src/google.golang.org/grpc/clientconn.go:317  Failed to dial cockroach-rho-3:26257: grpc: timed out trying to connect; please retry.
W160417 16:05:46.068512 sql/lease.go:645  /Table/3/1/51/2/1: failed to send RPC: too many errors encountered (3 of 3 total): server/node.go:742: node 4 stopped
==================
WARNING: DATA RACE
Read by goroutine 75:
  github.com/cockroachdb/cockroach/kv.(*TxnCoordSender).updateState()
      /home/marc/cockroach/src/github.com/cockroachdb/cockroach/kv/txn_coord_sender.go:783 +0x206d
  github.com/cockroachdb/cockroach/kv.(*TxnCoordSender).Send()
      /home/marc/cockroach/src/github.com/cockroachdb/cockroach/kv/txn_coord_sender.go:405 +0x1072
  github.com/cockroachdb/cockroach/client.(*txnSender).Send()
      /home/marc/cockroach/src/github.com/cockroachdb/cockroach/client/txn.go:59 +0x110
  github.com/cockroachdb/cockroach/client.(*DB).send()
      /home/marc/cockroach/src/github.com/cockroachdb/cockroach/client/db.go:474 +0x501
  github.com/cockroachdb/cockroach/client.(*Txn).send()
      /home/marc/cockroach/src/github.com/cockroachdb/cockroach/client/txn.go:649 +0xcb4
  github.com/cockroachdb/cockroach/client.(*Txn).(github.com/cockroachdb/cockroach/client.send)-fm()
      /home/marc/cockroach/src/github.com/cockroachdb/cockroach/client/txn.go:361 +0x5d
  github.com/cockroachdb/cockroach/client.sendAndFill()
      /home/marc/cockroach/src/github.com/cockroachdb/cockroach/client/db.go:386 +0x9a
  github.com/cockroachdb/cockroach/client.(*Txn).RunWithResponse()
      /home/marc/cockroach/src/github.com/cockroachdb/cockroach/client/txn.go:361 +0xe5
  github.com/cockroachdb/cockroach/client.(*Txn).Run()
      /home/marc/cockroach/src/github.com/cockroachdb/cockroach/client/txn.go:349 +0x38
  github.com/cockroachdb/cockroach/client.runOneRow()
      /home/marc/cockroach/src/github.com/cockroachdb/cockroach/client/db.go:498 +0x78
  github.com/cockroachdb/cockroach/client.(*Txn).Get()
      /home/marc/cockroach/src/github.com/cockroachdb/cockroach/client/txn.go:225 +0x18e
  github.com/cockroachdb/cockroach/sql.(*planner).getDescriptor()
      /home/marc/cockroach/src/github.com/cockroachdb/cockroach/sql/descriptor.go:130 +0xde
  github.com/cockroachdb/cockroach/sql.(*planner).getDatabaseDesc()
      /home/marc/cockroach/src/github.com/cockroachdb/cockroach/sql/database.go:81 +0x12b
  github.com/cockroachdb/cockroach/sql.(*planner).getTableDesc()
      /home/marc/cockroach/src/github.com/cockroachdb/cockroach/sql/table.go:226 +0x14f
  github.com/cockroachdb/cockroach/sql.(*planner).getTableLease()
      /home/marc/cockroach/src/github.com/cockroachdb/cockroach/sql/table.go:267 +0x1c4
  github.com/cockroachdb/cockroach/sql.(*planner).Insert()
      /home/marc/cockroach/src/github.com/cockroachdb/cockroach/sql/insert.go:40 +0x106
  github.com/cockroachdb/cockroach/sql.(*planner).makePlan()
      /home/marc/cockroach/src/github.com/cockroachdb/cockroach/sql/plan.go:225 +0x1b9b
  github.com/cockroachdb/cockroach/sql.(*planner).query()
      /home/marc/cockroach/src/github.com/cockroachdb/cockroach/sql/plan.go:320 +0x1e4
  github.com/cockroachdb/cockroach/sql.(*planner).exec()
      /home/marc/cockroach/src/github.com/cockroachdb/cockroach/sql/plan.go:345 +0x6d
  github.com/cockroachdb/cockroach/sql.InternalExecutor.ExecuteStatementInTransaction()
      /home/marc/cockroach/src/github.com/cockroachdb/cockroach/sql/internal.go:44 +0x2bc
  github.com/cockroachdb/cockroach/sql.EventLogger.InsertEventRecord()
      /home/marc/cockroach/src/github.com/cockroachdb/cockroach/sql/event_log.go:106 +0x4ae
  github.com/cockroachdb/cockroach/server.(*Node).recordJoinEvent.func1.1()
      /home/marc/cockroach/src/github.com/cockroachdb/cockroach/server/node.go:663 +0x1cd
  github.com/cockroachdb/cockroach/client.(*DB).Txn.func1()
      /home/marc/cockroach/src/github.com/cockroachdb/cockroach/client/db.go:438 +0x32
  github.com/cockroachdb/cockroach/client.(*Txn).Exec()
      /home/marc/cockroach/src/github.com/cockroachdb/cockroach/client/txn.go:531 +0x5db
  github.com/cockroachdb/cockroach/client.(*DB).Txn()
      /home/marc/cockroach/src/github.com/cockroachdb/cockroach/client/db.go:439 +0x36b
  github.com/cockroachdb/cockroach/server.(*Node).recordJoinEvent.func1()
      /home/marc/cockroach/src/github.com/cockroachdb/cockroach/server/node.go:664 +0x40f
  github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker.func1()
      /home/marc/cockroach/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:139 +0x5f

Previous write by goroutine 24:
  github.com/cockroachdb/cockroach/client.(*Txn).Exec()
      /home/marc/cockroach/src/github.com/cockroachdb/cockroach/client/txn.go:573 +0x6f4
  github.com/cockroachdb/cockroach/client.(*DB).Txn()
      /home/marc/cockroach/src/github.com/cockroachdb/cockroach/client/db.go:439 +0x36b
  github.com/cockroachdb/cockroach/sql.(*LeaseManager).refreshLease()
      /home/marc/cockroach/src/github.com/cockroachdb/cockroach/sql/lease.go:678 +0x146
  github.com/cockroachdb/cockroach/sql.(*LeaseManager).RefreshLeases.func1()
      /home/marc/cockroach/src/github.com/cockroachdb/cockroach/sql/lease.go:644 +0xcd5
  github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker.func1()
      /home/marc/cockroach/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:139 +0x5f

Goroutine 75 (running) created at:
  github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker()
      /home/marc/cockroach/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:140 +0x6f
  github.com/cockroachdb/cockroach/server.(*Node).recordJoinEvent()
      /home/marc/cockroach/src/github.com/cockroachdb/cockroach/server/node.go:670 +0x163
  github.com/cockroachdb/cockroach/server.(*Node).start()
      /home/marc/cockroach/src/github.com/cockroachdb/cockroach/server/node.go:336 +0x7be
  github.com/cockroachdb/cockroach/server.(*Server).Start()
      /home/marc/cockroach/src/github.com/cockroachdb/cockroach/server/server.go:342 +0x18a1
  github.com/cockroachdb/cockroach/cli.runStart()
      /home/marc/cockroach/src/github.com/cockroachdb/cockroach/cli/start.go:184 +0xca9
  github.com/spf13/cobra.(*Command).execute()
      /home/marc/cockroach/src/github.com/spf13/cobra/command.go:561 +0x7f2
  github.com/spf13/cobra.(*Command).ExecuteC()
      /home/marc/cockroach/src/github.com/spf13/cobra/command.go:651 +0x6bb
  github.com/spf13/cobra.(*Command).Execute()
      /home/marc/cockroach/src/github.com/spf13/cobra/command.go:610 +0x3a
  github.com/cockroachdb/cockroach/cli.Run()
      /home/marc/cockroach/src/github.com/cockroachdb/cockroach/cli/cli.go:87 +0xcd
  main.main()
      /home/marc/cockroach/src/github.com/cockroachdb/cockroach/main.go:37 +0x20b

Goroutine 24 (running) created at:
  github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker()
      /home/marc/cockroach/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:140 +0x6f
  github.com/cockroachdb/cockroach/sql.(*LeaseManager).RefreshLeases()
      /home/marc/cockroach/src/github.com/cockroachdb/cockroach/sql/lease.go:657 +0x13d
  github.com/cockroachdb/cockroach/server.NewServer()
      /home/marc/cockroach/src/github.com/cockroachdb/cockroach/server/server.go:161 +0x1956
  github.com/cockroachdb/cockroach/cli.runStart()
      /home/marc/cockroach/src/github.com/cockroachdb/cockroach/cli/start.go:174 +0xae7
  github.com/spf13/cobra.(*Command).execute()
      /home/marc/cockroach/src/github.com/spf13/cobra/command.go:561 +0x7f2
  github.com/spf13/cobra.(*Command).ExecuteC()
      /home/marc/cockroach/src/github.com/spf13/cobra/command.go:651 +0x6bb
  github.com/spf13/cobra.(*Command).Execute()
      /home/marc/cockroach/src/github.com/spf13/cobra/command.go:610 +0x3a
  github.com/cockroachdb/cockroach/cli.Run()
      /home/marc/cockroach/src/github.com/cockroachdb/cockroach/cli/cli.go:87 +0xcd
  main.main()
      /home/marc/cockroach/src/github.com/cockroachdb/cockroach/main.go:37 +0x20b
==================
W160417 16:05:46.069484 server/node.go:665  [node=4] unable to log node_restart event for node 4: failed to send RPC: too many errors encountered (3 of 3 total): server/node.go:742: node 4 stopped
I160417 16:05:47.069979 /home/marc/cockroach/src/google.golang.org/grpc/clientconn.go:462  grpc: Conn.resetTransport failed to create client transport: connection error: desc = "transport: dial tcp 10.240.0.8:26257: getsockopt: connection refused"; Reconnecting to "cockroach-rho-1:26257"
I160417 16:05:47.070044 /home/marc/cockroach/src/google.golang.org/grpc/clientconn.go:462  grpc: Conn.resetTransport failed to create client transport: connection error: desc = "transport: dial tcp 10.240.0.11:26257: getsockopt: connection refused"; Reconnecting to "cockroach-rho-4:26257"
```

Full log from node 3 (`104.196.19.81`) since last restart:
[node3.log.txt](https://github.com/cockroachdb/cockroach/files/222730/node3.log.txt)

### PR DESCRIPTION
**Pull request by tbg**
Previous code was returning the same `*roachpb.Error` to multiple
clients blocked on a LeaderLease request, which cause data races.

In the absence of similar issues present elsewhere, this fixes #6100
and fixes #6099.

---

This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/6111)

### CODE REVIEW

**Comment by mberhault** [comment]
LGTM.

nice. I'll push it to the rho cluster as soon as it's merged.

File: storage/replica.go [hunk 1]
```diff
@@ -513,8 +513,12 @@ func (r *Replica) requestLeaderLease(timestamp roachpb.Timestamp) <-chan *roachp
 		// Send result of leader lease to all waiter channels.
 		r.mu.Lock()
 		defer r.mu.Unlock()
-		for _, llChan := range r.mu.llChans {
-			llChan <- pErr
+		for i, llChan := range r.mu.llChans {
+			if i == 0 {
+				llChan <- pErr
+			} else {
+				llChan <- protoutil.Clone(pErr).(*roachpb.Error)
```
Comment (bdarnell) [inline storage/replica.go]: Won't this panic if `pErr` is nil? Looks like we need some test coverage of multiple operations waiting on the same lease request.

Comment (tschottdorf) [inline storage/replica.go]: Geez, I think you're right. Will write a test.

On Mon, Apr 18, 2016, 15:27 Ben Darnell <notifications@github.com> wrote:

> In storage/replica.go
> <https://github.com/cockroachdb/cockroach/pull/6111#discussion_r60056865>:
>
> > @@ -513,8 +513,12 @@ func (r *Replica) requestLeaderLease(timestamp roachpb.Timestamp) <-chan *roachp
> >  		// Send result of leader lease to all waiter channels.
> >  		r.mu.Lock()
> >  		defer r.mu.Unlock()
> > -		for _, llChan := range r.mu.llChans {
> > -			llChan <- pErr
> > +		for i, llChan := range r.mu.llChans {
> > +			if i == 0 {
> > +				llChan <- pErr
> > +			} else {
> > +				llChan <- protoutil.Clone(pErr).(*roachpb.Error)
>
> Won't this panic if pErr is nil? Looks like we need some test coverage of
> multiple operations waiting on the same lease request.
>
> —
> You are receiving this because you modified the open/close state.
>
>
> Reply to this email directly or view it on GitHub
> <https://github.com/cockroachdb/cockroach/pull/6111/files/e7d357b97777afa2c78a0321ef57eb1deeb3fe06#r60056865>
>
-- 

-- Tobias
