### PR TITLE
workload/mixed-version/schemachanger: re-enable mixed version workload

### LINKED ISSUE #58489: roachtest: schemaChangeStep is skipped in acceptance/version-upgrade
[(roachtest).acceptance/version-upgrade failed](https://teamcity.cockroachdb.com/viewLog.html?buildId=2561359&tab=buildLog) on [master@cee475331ca3629b503cd2e7c7919b72c98a5ca5](https://github.com/cockroachdb/cockroach/commits/cee475331ca3629b503cd2e7c7919b72c98a5ca5):

```
The test failed on branch=master, cloud=gce:
test artifacts and logs in: /home/agent/work/.go/src/github.com/cockroachdb/cockroach/artifacts/acceptance/version-upgrade/run_1
	versionupgrade.go:258,versionupgrade.go:114,versionupgrade.go:189,versionupgrade.go:177,acceptance.go:69,acceptance.go:110,test_runner.go:760: write tcp 172.17.0.3:52698->35.192.202.190:26257: write: broken pipe

	cluster.go:1637,context.go:140,cluster.go:1626,test_runner.go:841: dead node detection: /home/agent/work/.go/src/github.com/cockroachdb/cockroach/bin/roachprod monitor teamcity-2561359-1609916496-07-n4cpu4 --oneshot --ignore-empty-nodes: exit status 1 3: 5485
		4: 5484
		2: 5508
		1: dead
		Error: UNCLASSIFIED_PROBLEM: 1: dead
		(1) UNCLASSIFIED_PROBLEM
		Wraps: (2) attached stack trace
		  -- stack trace:
		  | main.glob..func14
		  | 	/home/agent/work/.go/src/github.com/cockroachdb/cockroach/pkg/cmd/roachprod/main.go:1147
		  | main.wrap.func1
		  | 	/home/agent/work/.go/src/github.com/cockroachdb/cockroach/pkg/cmd/roachprod/main.go:271
		  | github.com/spf13/cobra.(*Command).execute
		  | 	/home/agent/work/.go/src/github.com/cockroachdb/cockroach/vendor/github.com/spf13/cobra/command.go:830
		  | github.com/spf13/cobra.(*Command).ExecuteC
		  | 	/home/agent/work/.go/src/github.com/cockroachdb/cockroach/vendor/github.com/spf13/cobra/command.go:914
		  | github.com/spf13/cobra.(*Command).Execute
		  | 	/home/agent/work/.go/src/github.com/cockroachdb/cockroach/vendor/github.com/spf13/cobra/command.go:864
		  | main.main
		  | 	/home/agent/work/.go/src/github.com/cockroachdb/cockroach/pkg/cmd/roachprod/main.go:1850
		  | runtime.main
		  | 	/usr/local/go/src/runtime/proc.go:204
		  | runtime.goexit
		  | 	/usr/local/go/src/runtime/asm_amd64.s:1374
		Wraps: (3) 1: dead
		Error types: (1) errors.Unclassified (2) *withstack.withStack (3) *errutil.leafError

```

<details><summary>More</summary><p>

Artifacts: [/acceptance/version-upgrade](https://teamcity.cockroachdb.com/viewLog.html?buildId=2561359&tab=artifacts#/acceptance/version-upgrade)
Related:
- #58329 roachtest: acceptance/version-upgrade failed  [C-test-failure](https://api.github.com/repos/cockroachdb/cockroach/labels/C-test-failure) [O-roachtest](https://api.github.com/repos/cockroachdb/cockroach/labels/O-roachtest) [O-robot](https://api.github.com/repos/cockroachdb/cockroach/labels/O-robot) [branch-release-note-script-update](https://api.github.com/repos/cockroachdb/cockroach/labels/branch-release-note-script-update) [release-blocker](https://api.github.com/repos/cockroachdb/cockroach/labels/release-blocker)

- #58307 roachtest: acceptance/version-upgrade failed  [A-schema-descriptors](https://api.github.com/repos/cockroachdb/cockroach/labels/A-schema-descriptors) [C-bug](https://api.github.com/repos/cockroachdb/cockroach/labels/C-bug) [C-test-failure](https://api.github.com/repos/cockroachdb/cockroach/labels/C-test-failure) [O-roachtest](https://api.github.com/repos/cockroachdb/cockroach/labels/O-roachtest) [branch-release-20.2](https://api.github.com/repos/cockroachdb/cockroach/labels/branch-release-20.2)

- #58139 roachtest: acceptance/version-upgrade failed  [C-test-failure](https://api.github.com/repos/cockroachdb/cockroach/labels/C-test-failure) [O-roachtest](https://api.github.com/repos/cockroachdb/cockroach/labels/O-roachtest) [O-robot](https://api.github.com/repos/cockroachdb/cockroach/labels/O-robot) [branch-release-20.1](https://api.github.com/repos/cockroachdb/cockroach/labels/branch-release-20.1)

- #53812 roachtest: acceptance/version-upgrade failed  [C-test-failure](https://api.github.com/repos/cockroachdb/cockroach/labels/C-test-failure) [O-roachtest](https://api.github.com/repos/cockroachdb/cockroach/labels/O-roachtest) [O-robot](https://api.github.com/repos/cockroachdb/cockroach/labels/O-robot) [branch-release-19.2](https://api.github.com/repos/cockroachdb/cockroach/labels/branch-release-19.2)

[See this test on roachdash](https://roachdash.crdb.dev/?filter=status%3Aopen+t%3A.%2Aacceptance%2Fversion-upgrade.%2A&sort=title&restgroup=false&display=lastcommented+project)
<sub>powered by [pkg/cmd/internal/issues](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)</sub></p></details>

Jira issue: CRDB-3386

### PR DESCRIPTION
**Pull request by fqazi**
Fixes: #58489 #87477

Previously the mixed version schema changer workload was disabled because of the lack of version gates. These changes will do the following:

- Start reporting errors on this workload again.
- Disable trigrams in a mixed version state.
- Disable the insert part of the workload in a mixed version state (there is an optimizer on 22.1 that can cause some of the queries to fail)

Release justification: low risk only extends test coverage

### CODE REVIEW

File: pkg/workload/schemachange/operation_generator.go [hunk 1]
```diff
@@ -2488,7 +2498,6 @@ func (og *operationGenerator) insertRow(ctx context.Context, tx pgx.Tx) (stmt *o
 	for _, row := range rows {
 		formattedRows = append(formattedRows, fmt.Sprintf("(%s)", strings.Join(row, ",")))
 	}
-
```
Comment (Xiang-Gu) [inline pkg/workload/schemachange/operation_generator.go:2463]: nit: empty line deletion.

File: pkg/workload/schemachange/operation_generator.go [hunk 2]
```diff
@@ -2373,6 +2373,16 @@ func (og *operationGenerator) insertRow(ctx context.Context, tx pgx.Tx) (stmt *o
...
 	}
+	// If we aren't on 22.2 then disable the insert plugin, since 21.X
+	// can have queries fail due to an optimizer bug.
+	skipInserts, err := isClusterVersionLessThan(ctx, tx, clusterversion.ByKey(clusterversion.Start22_2))
+	if err != nil {
+		return nil, err
+	}
+	if skipInserts {
+		tableExists = false
+		tableName.SchemaName = "InvalidObjectName"
```
Comment (Xiang-Gu) [inline pkg/workload/schemachange/operation_generator.go:2384]: How does these two lines disable selects? In particular, why is the second line (`tableName.SchemaName = "InvalidObjectName"`) needed?

File: pkg/cmd/roachtest/tests/mixed_version_schemachange.go [hunk 3]
```diff
@@ -64,7 +64,7 @@ func runSchemaChangeWorkloadStep(loadNode, maxOps, concurrency int) versionStep
 			// crashes, deadlocks, etc.
 			// TODO(spaskob): remove when https://github.com/cockroachdb/cockroach/issues/47430
 			// is closed.
-			"--tolerate-errors=true",
+			//"--tolerate-errors=true",
```
Comment (Xiang-Gu) [inline pkg/cmd/roachtest/tests/mixed_version_schemachange.go:67]: why do we want to comment out this line? It seems necessary.

**Review by fqazi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/87142)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @Xiang-Gu)

___
*[`pkg/cmd/roachtest/tests/mixed_version_schemachange.go` line 67 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/87142#-NAkTostKK1TESR24KmX-r3-67:-NBxc8Xj2pRJjIqkAzyZ:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/1fd825176c78065f05b8a7e817ecb6610f005723/pkg/cmd/roachtest/tests/mixed_version_schemachange.go#L67)):*
<details><summary><i>Previously, Xiang-Gu (Xiang Gu) wrote…</i></summary><blockquote>

why do we want to comment out this line? It seems necessary.
</blockquote></details>

Done.
___
*[`pkg/workload/schemachange/operation_generator.go` line 2384 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/87142#-NAkTostKK1TESR24KmZ-r3-2384:-NBxg-r_EtSCcCEvLQuX:btzadd7) ([raw file](https://github.com/cockroachdb/cockroach/blob/1fd825176c78065f05b8a7e817ecb6610f005723/pkg/workload/schemachange/operation_generator.go#L2384)):*
<details><summary><i>Previously, Xiang-Gu (Xiang Gu) wrote…</i></summary><blockquote>

How does these two lines disable selects? In particular, why is the second line (`tableName.SchemaName = "InvalidObjectName"`) needed?
</blockquote></details>

Done.

So, the second line basically makes the inserts always target a non-existent table to skip all the logic.

**Comment by ajwerner** [comment]
@fqazi I noticed something similar in https://github.com/cockroachdb/cockroach/issues/87477

**Comment by fqazi** [comment]
@Xiang-Gu Can you take another look at this, if you have the cycles?

**Review by Xiang-Gu — APPROVED** [review]
Thanks for your work! This LGTM

**Comment by fqazi** [comment]
@Xiang-Gu @TFTR!

bors r+

**Comment by renatolabs** [comment]
bors r-

@fqazi we recently changed the native library API for roachtests -- see #86451. Roachtests shouldn't call `PutLibraries` directly anymore, but instead specify the required native libraries in the test spec.

Cancelling the build here to let you rebase against master and fix the compilation issue.

**Comment by fqazi** [comment]
@renatolabs Missed that change, I'll confirm that CI is happy then bors this again.
