### PR TITLE
roachprod: split start-up script logic for disks

### LINKED ISSUE #122094: roachprod: fstab entry fails with local SSDs
When creating a cluster using `roachprod` on GCP. The generated start-up script will create entries in `/etc/fstab` to ensure the disk gets mounted after a reboot/start/stop (or in the case of preempted VMs, after the VM is recreated):

```
    mount -o ${mount_opts} ${disk} ${mountpoint}
    echo "${d} ${mountpoint} ext4 ${mount_opts} 1 1" | tee -a /etc/fstab
```

This however fails with Local SSDs because a _completely_ new disk is attached after reboot (Local SSDs are ephemeral on GCP). 

The entry itself is not bad, but the disk is not formatted; hence it is missing its filesystem on boot. This causes the boot to fail and the VM becomes unavailable:

```
[[0;32m  OK  [0m] Reached target [0;1;39mMounted snaps[0m.

Checking in progress on 1 disk (0.0% complete)
[[0;32m  OK  [0m] Finished [0;1;39mFile System Check…by-id/google-local-nvme-ssd-0[0m.
         Mounting [0;1;39m/mnt/data1[0m...
[    3.067493] EXT4-fs (nvme0n1): VFS: Can't find ext4 filesystem
[[0;1;31mFAILED[0m] Failed to mount [0;1;39m/mnt/data1[0m.
See 'systemctl status mnt-data1.mount' for details.
[[0;1;38;5;185mDEPEND[0m] Dependency failed for [0;1;39mLocal File Systems[0m.
[[0;32m  OK  [0m] Stopped [0;1;39mForward Password R…uests to Wall Directory Watch[0m.
[[0;32m  OK  [0m] Reached target [0;1;39mTimer Units[0m.
```

Jira issue: CRDB-37698

### PR DESCRIPTION
**Pull request by herkolategan**
Previously, the start-up script for GCE VMs would determine if it should run by looking at `/mnt/data1/.roachprod-initialized`. This logic fails if the disks are ephemeral. The VM also completely fails to boot due to an `fstab` entry that does not have the `nofail` option. Because, a new disk is attached, but it's not formatted.

This change adds the `nofail` option, but also divides the start-up script into parts to handle the scenario where the OS might have been previously initialed, but the disks are not initialised. To fix this we now track OS initialization via `/.roachprod-initialized` and disk initialization via `/mnt/data1/.roachprod-initialized`. We also prevent the `fstab` entries from being written again, as these are part of the OS initialization.

Fixes: #122094

Epic: None
Release Note: None

### CODE REVIEW

File: pkg/roachprod/vm/gce/utils.go [hunk 1]
```diff
@@ -46,109 +46,133 @@ const gceDiskStartupScriptTemplate = `#!/usr/bin/env bash
...
-  raiddisk="/dev/md0"
-  mdadm -q --create ${raiddisk} --level=0 --raid-devices=${#disks[@]} "${disks[@]}"
-  mkfs.ext4 -q -F ${raiddisk}
-  mount -o ${mount_opts} ${raiddisk} ${mountpoint}
-  echo "${raiddisk} ${mountpoint} ext4 ${mount_opts} 1 1" | tee -a /etc/fstab
-  tune2fs -m 0 ${raiddisk}
-{{ end }}
-  chmod 777 ${mountpoint}
+if [ -e /.roachprod-initialized ]; then
+  echo "OS already initialized, only initialing disks."
```
Comment (renatolabs) [inline pkg/roachprod/vm/gce/utils.go:168]: Initializing?

**Review by renatolabs — APPROVED** [review]
This LGTM, but if you feel like documenting this a little better, would be nice to extract those paths (`/mnt/data1/.roachprod-initialized` and `/.roachprod-initalized`) to constants that document what they mean, since their names are a bit generic. If I understand this correctly, the former means that the disks have been initialized (and implies OS-initialized) and the latter is just that the OS (packages, etc) has been initialized, but disks still need setup.

Then we could also reference the constant in the `Wipe` function.

File: pkg/roachprod/vm/gce/utils.go (hunk 1 above)
Comment (herkolategan) [reply pkg/roachprod/vm/gce/utils.go:168]: Yes! fixed.

File: pkg/roachprod/vm/vm.go [hunk 2]
```diff
@@ -47,6 +47,17 @@ const (
...
+	// OSInitializedFile is a marker file that is created on a VM to indicate
+	// that it has been initialized at least once by the VM start-up script. This
+	// is used to avoid re-initializing a VM that has been stopped and restarted.
+	OSInitializedFile = "/.roachprod-initialized"
+	// DisksInitializedFile is a marker file that is created on a VM to indicate
+	// that the disks have been initialized by the VM start-up script. This is
+	// separate from OSInitializedFile, because the disks may be ephemeral and
+	// need to be re-initialized on every start. The presence of this file
+	// automatically implies the presence of OSInitializedFile.
+	DisksInitializedFile = "/mnt/disk1/.roachprod-initialized"
```
Comment (renatolabs) [inline pkg/roachprod/vm/vm.go:60]: I believe this is `/mnt/data1`

Comment (herkolategan) [reply pkg/roachprod/vm/vm.go]: Haha yeah, autocomplete got the best of me.
Going to do a small CI run just in case to check all is working as should.

**Review by srosenberg — APPROVED** [review]
Nice!
