### PR TITLE
roachprod: elide expiration notification for GCed dangling resources (in Azure)

### LINKED ISSUE #110183: roachprod: gc slack notifications have wrong expiration time for dangling resources
roachprod-gc-cronjob attempts to send a slack message to users notifying them when their cluster is being destroyed. However, roachprod-gc also cleans up dangling resources even if the expiration date has not passed yet. This results in the slack notification saying that a cluster was destroyed in the future.
image

Ideally this message would indicate that this cluster was destroyed due to being a dangling resource, and show the adjusted expiration time of one hour after it's creation in addition to it's original expiration. This could be achieved by creating a section for dangling destroyed clusters to separate it from regular destroyed clusters.

**To Reproduce**

1. Create an azure cluster through roachprod
2. Delete the VM(s) through the azure portal
3. Roachprod-gc should clean it up within 2 hours and send a notification

Jira issue: CRDB-31307

### PR DESCRIPTION
**Pull request by srosenberg**
In Azure, VM destroy is non-transactional; dangling resources, e.g., a resource group, may outlive a VM. Previously, `roachprod gc` would correctly destroy dangling resources, but its slack notification may have contained an expiration time in the future.

This change elides expiration time since it's ambiguous for an arbitrary dangling resource. Instead, such notifications are now under the rubric of `Destroyed Empty Clusters/Dangling Resources` which is disjoint from `Destroyed Clusters`.

Epic: none
Fixes: #110183

Release note: None

### CODE REVIEW

**Comment by srosenberg** [comment]
Manually tested deletion of dangling resources; slack notifications are now of this form,

roachprod_gc_slack

File: pkg/roachprod/cloud/gc.go [hunk 1]
```diff
@@ -421,10 +445,18 @@ func GCClusters(l *logger.Logger, cloud *Cloud, dryrun bool) error {
 		if err := destroyResource(dryrun, func() error {
 			return DestroyCluster(l, c)
 		}); err == nil {
-			destroyedClusters = append(destroyedClusters, resourceDescription{
-				Description:      fmt.Sprintf("%s (expiration: %s)", c.Name, c.ExpiresAt().String()),
-				SlackDescription: fmt.Sprintf("`%s` (expiration: %s)", c.Name, slackClusterExpirationDate(c)),
-			})
+			if !c.IsEmptyCluster() {
```
Comment (renatolabs) [inline pkg/roachprod/cloud/gc.go:448]: Nit: we could lift cloud formatting to avoid always saying `cloud(s)` in the common case of single-cloud clusters. Something like:

```go
clouds := strings.Join(c.Clouds(), ", ")
cloudsDesc := "cloud"
if len(c.Clouds()) > 1 {
    cloudsDesc = "clouds"
}

// ... later ...
// Description: fmt.Sprintf("%s (%s: %s, expiration: %s)", c.Name, cloudsDesc, clouds, c.GCAt().String()),
```

File: pkg/roachprod/cloud/gc.go [hunk 2]
```diff
@@ -421,10 +445,18 @@ func GCClusters(l *logger.Logger, cloud *Cloud, dryrun bool) error {
...
+				destroyedClusters = append(destroyedClusters, resourceDescription{
+					Description:      fmt.Sprintf("%s (cloud(s): %s, expiration: %s)", c.Name, strings.Join(c.Clouds(), ","), c.GCAt().String()),
+					SlackDescription: fmt.Sprintf("`%s` (cloud(s): `%s`, *expiration*: %s)", c.Name, strings.Join(c.Clouds(), ","), slackClusterExpirationDate(c)),
```
Comment (renatolabs) [inline pkg/roachprod/cloud/gc.go:451]: Nit: for multi-cloud clusters, this will render as `gce, azure` instead, arguably nicer, `gce`, `azure`.

File: pkg/roachprod/roachprod.go [hunk 3]
```diff
@@ -1462,6 +1462,7 @@ func Create(
 		// No need for ssh for local clusters.
 		return LoadClusters()
 	}
+	l.Printf("Created cluster %s; setting up SSH...", clusterName)
```
Comment (renatolabs) [inline pkg/roachprod/roachprod.go:1465]: Did you intend to commit these changes in this PR? Just making sure as they are not GC related.

**Review by renatolabs — APPROVED** [review]
Thanks for the fix! Optional formatting comments.

File: pkg/roachprod/roachprod.go (hunk 3 above)
Comment (srosenberg) [reply pkg/roachprod/roachprod.go:1465]: During testing, `roachprod create` failed several times in Azure during `SetupSSH`. I wasn't able to reproduce it, so chalking it up to a transient error. However, the above log message was useful for debugging since we can better isolate the failed step.

File: pkg/roachprod/cloud/gc.go (hunk 2 above)
Comment (srosenberg) [reply pkg/roachprod/cloud/gc.go:451]: Yep, I can make it prettier :)

File: pkg/roachprod/cloud/gc.go (hunk 1 above)
Comment (srosenberg) [reply pkg/roachprod/cloud/gc.go:448]: Yep, I'll refactor; the duplication was already making me question it.

**Review by herkolategan — APPROVED** [review]

**Comment by srosenberg** [comment]
TFTR!

bors r=renatolabs,herkolategan
