### PR TITLE
kvnemesis: report splits to raft asserter

### LINKED ISSUE #157765: kvnemesis: investigate snapshot state mismatch
In #157253, we hit a panic in the `apply.Asserter` which wasn't handled properly. Reproducing with the same seed, I got the actual panic message:

```
panic: r82/3 snapshot from 1 at index 12: state differs from log state: cmd "" index 12 term 6 (LAI=10 CTS=1763048328.444873980,0) (cmd "" index 12 term 6 (LAI=10 CTS=1763048328.444873980,0)) [recovered, repanicked]
```

To help investigate this more easily, #157762 improves the logging of that message and switches the `Asserter` to use `log.Fatalf` instead of panic.

Repro steps:

Set the kvnemesis seed to `1795589098147348365` for the `TestKVNemesisMultiNode_Restart_Liveness` test:
```
diff --git a/pkg/kv/kvnemesis/kvnemesis_test.go b/pkg/kv/kvnemesis/kvnemesis_test.go
index 68fc57aaa60..5cf440f40c2 100644
--- a/pkg/kv/kvnemesis/kvnemesis_test.go
+++ b/pkg/kv/kvnemesis/kvnemesis_test.go
@@ -525,7 +525,7 @@ func TestKVNemesisMultiNode_Restart_Liveness(t *testing.T) {
                numNodes:                     4,
                numSteps:                     defaultNumSteps,
                concurrency:                  5,
-               seedOverride:                 0,
+               seedOverride:                 1795589098147348365,
                invalidLeaseAppliedIndexProb: 0.2,
                injectReproposalErrorProb:    0.2,
                assertRaftApply:              true,
```

Run:
```
./dev test pkg/kv/kvnemesis -v --filter=TestKVNemesisMultiNode_Restart_Liveness --stress
```

I hit it after 800-ish runs.

Jira issue: CRDB-56943

### PR DESCRIPTION
**Pull request by pav-kv**
This PR passes the information about newly created replicas into the raft asserter. This helps tracking the applied state more accurately. Previously, there was a window of time (between a replica splits out and applies the first non-trivial command) during which its tracked applied state is zero while the real one is not.

Resolves #157765, #158624
Informs #158247

### CODE REVIEW

File: pkg/kv/kvserver/apply/asserter.go [hunk 1]
```diff
@@ -342,6 +342,33 @@ func (r *rangeAsserter) apply(
 	r.seedAppliedAs[seedID] = cmdID
 }
 
+// ApplySplitRHS tracks and asserts command applications which split out a new
+// range. Accepts the state of the RHS.
+func (a *Asserter) ApplySplitRHS(
+	rangeID roachpb.RangeID,
+	replicaID roachpb.ReplicaID,
+	raftAppliedIndex kvpb.RaftIndex,
+	raftAppliedIndexTerm kvpb.RaftTerm,
```
Comment (pav-kv) [inline pkg/kv/kvserver/apply/asserter.go:351]: Name `index/term` the same way as in `ApplySnapshot`.

**Review by miraradeva — APPROVED** [review]
:lgtm: Just one question to make sure I understand this. 

We need the new split pseudo-command in order to keep the nice assertion (in the asserter) that there is always some command applied before applying a snapshot. In reality, that's not always the case, as we saw in the test failures where snapshots raced and applied before other commands (excluding lease requests).

> @miraradeva reviewed 2 of 3 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/158349#-:-OfUx6lV07suwvp27GMe:bycatzz)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @stevendanna)

**Review by pav-kv — COMMENTED** [review]
Yes. Note that we need "some command applied" anywhere for this range, not necessarily on our own replica. For the assertion in the snapshot path, we also needed the CT / LAI to be known.

This wasn't always the case because there could be a prefix of commands that are one of: (a) no-op commands at the beginning of new term, (b) lease commands that don't carry CT / LAI.

I think the (b) part was less likely to happen, so we only had a fix accounting for (a). Somehow node restarts made us more sensitive to (b). Now it's more general and works with (a) and (b). The invariant now is that the CT / LAI for a range is always known (becomes true when any replica of a newly split range materializes for the first time, which is necessarily earlier than any snapshot for this range).

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/158349#-:-OfVi-dg2c_tNTjuAko6:bijz6ea)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @stevendanna)

**Comment by pav-kv** [comment]
bors retry
