### PR TITLE
roachtest: deflake multi-store-remove

### LINKED ISSUE #146435: roachtest: multi-store-remove failed
**Note:** This build has runtime assertions enabled. If the same failure was hit in a run without assertions enabled, there should be a similar failure without this message. If there isn&#39;t one, then this failure is likely due to an assertion violation or (assertion) timeout.

roachtest.multi-store-remove [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/19654360?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/19654360?buildTab=artifacts#/multi-store-remove) on release-25.2 @ [c19b9c5748e1e0219c435e72435275989bc07733](https://github.com/cockroachdb/cockroach/commits/c19b9c5748e1e0219c435e72435275989bc07733). A Side-Eye cluster snapshot was captured on timeout: [https://app.side-eye.io/#/snapshots/812](https://app.side-eye.io/#/snapshots/812).

```
(test_runner.go:1401).runTest: test timed out (30m0s)
test artifacts and logs in: /artifacts/multi-store-remove/run_1
```

Parameters:
 - <code>arch=amd64</code>
 - <code>cloud=gce</code>
 - <code>coverageBuild=false</code>
 - <code>cpu=4</code>
 - <code>encrypted=true</code>
 - <code>fs=ext4</code>
 - <code>localSSD=true</code>
 - <code>metamorphicBufferedSender=true</code>
 - <code>metamorphicLeases=default</code>
 - <code>runtimeAssertionsBuild=true</code>
 - <code>ssd=2</code>
<details><summary>Help</summary>
<p>

See: [roachtest README](https://github.com/cockroachdb/cockroach/blob/master/pkg/cmd/roachtest/README.md)

See: [How To Investigate \(internal\)](https://cockroachlabs.atlassian.net/l/c/SSSBr8c7)

See: [Grafana](https://go.crdb.dev/roachtest-grafana/teamcity-19654360/multi-store-remove/1746790102403/1746792083919)

</p>
</details>
/cc @cockroachdb/storage
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*multi-store-remove.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/bazci/githubpost/issues)

</sub>

Jira issue: CRDB-50519

### LINKED ISSUE #147763: roachtest: multi-store-remove failed
roachtest.multi-store-remove [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/19853803?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/19853803?buildTab=artifacts#/multi-store-remove) on release-25.2.1-rc @ [f9f183de9d58b822d6cf4c12c560e1fbbc70707f](https://github.com/cockroachdb/cockroach/commits/f9f183de9d58b822d6cf4c12c560e1fbbc70707f):

```
(multi_store_remove.go:91).runMultiStoreRemove: wanted no stores without ranges; found 1
test artifacts and logs in: /artifacts/multi-store-remove/run_1
```

Parameters:
 - <code>arch=amd64</code>
 - <code>cloud=gce</code>
 - <code>coverageBuild=false</code>
 - <code>cpu=4</code>
 - <code>encrypted=false</code>
 - <code>fs=ext4</code>
 - <code>localSSD=true</code>
 - <code>metamorphicBufferedSender=true</code>
 - <code>metamorphicLeases=default</code>
 - <code>runtimeAssertionsBuild=false</code>
 - <code>ssd=2</code>
<details><summary>Help</summary>
<p>

See: [roachtest README](https://github.com/cockroachdb/cockroach/blob/master/pkg/cmd/roachtest/README.md)

See: [How To Investigate \(internal\)](https://cockroachlabs.atlassian.net/l/c/SSSBr8c7)

See: [Grafana](https://go.crdb.dev/roachtest-grafana/teamcity-19853803/multi-store-remove/1749036835417/1749037008643)

</p>
</details>
<details><summary>Same failure on other branches</summary>
<p>

- #146435 roachtest: multi-store-remove failed [A-kv B-runtime-assertions-enabled C-bug C-test-failure O-roachtest O-robot P-2 T-kv branch-release-25.2]
</p>
</details>
/cc @cockroachdb/storage
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*multi-store-remove.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/bazci/githubpost/issues)

</sub>

Jira issue: CRDB-51218

### LINKED ISSUE #156447: roachtest: multi-store-remove failed
**Note:** This build has runtime assertions enabled. If the same failure was hit in a run without assertions enabled, there should be a similar failure without this message. If there isn&#39;t one, then this failure is likely due to an assertion violation or (assertion) timeout.

roachtest.multi-store-remove [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/20665616?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/20665616?buildTab=artifacts#/multi-store-remove) on release-25.4.0-rc @ [4f4179243a351bc48c00dd9243dc56b8af98e210](https://github.com/cockroachdb/cockroach/commits/4f4179243a351bc48c00dd9243dc56b8af98e210):

```
(test_runner.go:1452).runTest: test timed out (30m0s)
test artifacts and logs in: /artifacts/multi-store-remove/run_1
```

Parameters:
 - <code>arch=amd64</code>
 - <code>cloud=gce</code>
 - <code>coverageBuild=false</code>
 - <code>cpu=4</code>
 - <code>encrypted=true</code>
 - <code>fs=ext4</code>
 - <code>localSSD=true</code>
 - <code>metamorphicLeases=default</code>
 - <code>metamorphicWriteBuffering=true</code>
 - <code>runtimeAssertionsBuild=true</code>
 - <code>ssd=2</code>
<details><summary>Help</summary>
<p>

See: [roachtest README](https://github.com/cockroachdb/cockroach/blob/master/pkg/cmd/roachtest/README.md)

See: [How To Investigate \(internal\)](https://cockroachlabs.atlassian.net/l/c/SSSBr8c7)

See: [Grafana](https://go.crdb.dev/roachtest-grafana/teamcity-20665616/multi-store-remove/1761736064581/1761738029341)

</p>
</details>
<details><summary>Same failure on other branches</summary>
<p>

- #147763 roachtest: multi-store-remove failed [A-kv-distribution A-storage C-test-failure O-roachtest O-robot P-3 T-storage branch-release-25.2.1-rc]
- #146435 roachtest: multi-store-remove failed [A-kv B-runtime-assertions-enabled C-bug C-test-failure O-roachtest O-robot P-3 T-kv branch-release-25.2 branch-release-25.3]
</p>
</details>
/cc @cockroachdb/storage
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*multi-store-remove.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/bazci/githubpost/issues)

</sub>

Jira issue: CRDB-56020

### PR DESCRIPTION
**Pull request by tbg**
The test was checking on replication by asserting that the number of ranges
times the replication factor is equal to the number of replicas.

Replicas can persist after no longer being part of a range (waiting for
replicaGC), which is why this test was flaky.

I first tried to fix it by lowering the replicaGC queue's interval at
which it checks ranges (defaults to 12h), but looking more closely at
what the test was doing, I decided to change that instead by no longer
caring about what replicas each store reports. What matters is what
the meta ranges report, and now the test checks replication similar
to how many other tests do, by querying ranges_no_leases.

Fixes #146435.
Fixes #147763.
Fixes #156447.

Epic: none

### CODE REVIEW

File: pkg/cmd/roachtest/tests/multi_store_remove.go [hunk 1]
```diff
@@ -151,32 +158,30 @@ func runMultiStoreRemove(ctx context.Context, t test.Test, c cluster.Cluster) {
...
-			`SELECT
-			    (SELECT count(1) FROM crdB_internal.ranges) AS ranges
-			  , (SELECT sum(range_count) FROM crdb_internal.kv_store_status) AS replicas`,
-		).Scan(&ranges, &replicas); err != nil {
-			t.Fatalf("replication status: %s", err)
-		}
-		if replicas == 3*ranges {
-			t.L().Printf("up-replication complete")
+		res := sr.QueryStr(t, `
+SELECT
```
Comment (pav-kv) [inline pkg/cmd/roachtest/tests/multi_store_remove.go:166]: Took me a few min to understand this query.

nit: since we need the sample anyway, the `cnt` bit is redundant. We could query only the sample, and check `len(sample) == 0` in Go code.

**Review by pav-kv — APPROVED** [review]
LGTM % nit

**Comment by tbg** [comment]
TFTR! I'll wait for the roachtest run to clear before merge.

Re your inline comment: `cnt` provides the global count, so that the test prints the actual amount of outstanding work (alongside a few concrete rangeIDs to look into).
