### PR TITLE
sql: don't show schema in constraint defs if in search_path

### LINKED ISSUE #52356: sql: 20.2 regression: foreign key constraint should not show schema name if schema is in search_path
**Describe the problem**

The SQLAlchemy test `test/dialect/test_suite.py::ComponentReflectionTest::test_get_foreign_keys` started failing. It fails because CockroachDB started including unexpected schema information when describing foreign key constraints. The cause of the failure is the change in PR #50889.

In Postgres, if you do `SELECT pg_catalog.pg_get_constraintdef(<constraintOid>, true)`, it will not include the schema name if the schema is in the `search_path`. However, that PR makes the schema always be included in the result.

**To Reproduce**

Setup:
```
> create table a (a int primary key);
> create table b(a int primary key, aa int references a(a));
```

In Postgres:
```
> SELECT r.conname,
                 pg_catalog.pg_get_constraintdef(r.oid, true) as condef,
                 n.nspname as conschema
           FROM  pg_catalog.pg_constraint r,
                 pg_namespace n,
                 pg_class c
           WHERE c.relname = 'a' AND
                 r.contype = 'f' AND
                 c.oid = confrelid AND
                 n.oid = c.relnamespace
           ORDER BY 1
+-----------+----------------------------------+-------------+
| conname   | condef                           | conschema   |
|-----------+----------------------------------+-------------|
| b_aa_fkey | FOREIGN KEY (aa) REFERENCES a(a) | public      |
+-----------+----------------------------------+-------------+
```

In CockroachDB
```
> SELECT r.conname,
                 pg_catalog.pg_get_constraintdef(r.oid, true) as condef,
                 n.nspname as conschema
           FROM  pg_catalog.pg_constraint r,
                 pg_namespace n,
                 pg_class c
           WHERE c.relname = 'a' AND
                 r.contype = 'f' AND
                 c.oid = confrelid AND
                 n.oid = c.relnamespace
           ORDER BY 1;

    conname   |                 condef                  | conschema
--------------+-----------------------------------------+------------
  fk_aa_ref_a | FOREIGN KEY (aa) REFERENCES public.a(a) | public
```

**Expected behavior**
If the schema name is in `search_path`, then do not include the schema name in the foreign key definition returned by `pg_get_constraintdef`.

### PR DESCRIPTION
**Pull request by rafiss**
If the schema name is in search_path, then do not include the schema
name in the foreign key definition in the pg_constraint table. This
matches the behavior of the pg_get_constraintdef function from Postgres.

The create_statements logic test ensures that the schema name still is
included when displaying create statements. The pg_catalog and
builtin_function tests were updated to check for the desired display
behavior when showing constraint definitions alone.

There is no release note because this changes behavior that was
introduced in an alpha.

fixes: #52356

Release note: None

### CODE REVIEW

File: pkg/sql/crdb_internal.go [hunk 1]
```diff
@@ -1610,7 +1610,14 @@ func showAlterStatementWithInterleave(
...
 		f.FormatNameP(&fk.Name)
 		f.WriteByte(' ')
-		if err := showForeignKeyConstraint(&f.Buffer, contextName, table, fk, lCtx); err != nil {
+		if err := showForeignKeyConstraint(
+			&f.Buffer,
+			contextName,
+			table,
+			fk,
+			lCtx,
+			sessiondata.EmptySearchPath,
```
Comment (rohany) [inline pkg/sql/crdb_internal.go:1619]: comment about this

Comment (rafiss) [reply pkg/sql/crdb_internal.go:1619]: Done

**Review by rohany — APPROVED** [review]

**Comment by rafiss** [comment]
bors r=rohany
