### PR TITLE
sql: bulk insert/update in implicit txn can retry indefinitely

### LINKED ISSUE #69089: sql: bulk UPDATE statement in implicit txn will retry indefinitely due to txn commit deadline errors
**Describe the problem**

Attempting to run an UPDATE which touches all 100 million rows of a table continuously fails ('retries' number on the DBConsole slowly increases).  There are no other queries running on the cluster.

**To Reproduce**

New cluster with the following SQL used to populate 100,000,000 rows:

```
create database shaun;
use shaun;

create table a (
        a int primary key default unique_rowid(),
        b varchar,
        c uuid default gen_random_uuid()
);

insert into a select a from generate_series(1, 1000000) g(a);
insert into a select a from generate_series(1000001, 2000000) g(a);
insert into a select a from generate_series(2000001, 3000000) g(a);
insert into a select a from generate_series(3000001, 4000000) g(a);
insert into a select a from generate_series(4000001, 5000000) g(a);
insert into a select a from generate_series(5000001, 6000000) g(a);
insert into a select a from generate_series(6000001, 7000000) g(a);
insert into a select a from generate_series(7000001, 8000000) g(a);
insert into a select a from generate_series(8000001, 9000000) g(a);
insert into a select a from generate_series(9000001, 10000000) g(a);

insert into a select a from generate_series(10000001, 11000000) g(a);
insert into a select a from generate_series(11000001, 12000000) g(a);
insert into a select a from generate_series(12000001, 13000000) g(a);
insert into a select a from generate_series(13000001, 14000000) g(a);
insert into a select a from generate_series(14000001, 15000000) g(a);
insert into a select a from generate_series(15000001, 16000000) g(a);
insert into a select a from generate_series(16000001, 17000000) g(a);
insert into a select a from generate_series(17000001, 18000000) g(a);
insert into a select a from generate_series(18000001, 19000000) g(a);
insert into a select a from generate_series(19000001, 20000000) g(a);

insert into a select a from generate_series(20000001, 21000000) g(a);
insert into a select a from generate_series(21000001, 22000000) g(a);
insert into a select a from generate_series(22000001, 23000000) g(a);
insert into a select a from generate_series(23000001, 24000000) g(a);
insert into a select a from generate_series(24000001, 25000000) g(a);
insert into a select a from generate_series(25000001, 26000000) g(a);
insert into a select a from generate_series(26000001, 27000000) g(a);
insert into a select a from generate_series(27000001, 28000000) g(a);
insert into a select a from generate_series(28000001, 29000000) g(a);
insert into a select a from generate_series(29000001, 30000000) g(a);

insert into a select a from generate_series(30000001, 31000000) g(a);
insert into a select a from generate_series(31000001, 32000000) g(a);
insert into a select a from generate_series(32000001, 33000000) g(a);
insert into a select a from generate_series(33000001, 34000000) g(a);
insert into a select a from generate_series(34000001, 35000000) g(a);
insert into a select a from generate_series(35000001, 36000000) g(a);
insert into a select a from generate_series(36000001, 37000000) g(a);
insert into a select a from generate_series(37000001, 38000000) g(a);
insert into a select a from generate_series(38000001, 39000000) g(a);
insert into a select a from generate_series(39000001, 40000000) g(a);

insert into a select a from generate_series(40000001, 41000000) g(a);
insert into a select a from generate_series(41000001, 42000000) g(a);
insert into a select a from generate_series(42000001, 43000000) g(a);
insert into a select a from generate_series(43000001, 44000000) g(a);
insert into a select a from generate_series(44000001, 45000000) g(a);
insert into a select a from generate_series(45000001, 46000000) g(a);
insert into a select a from generate_series(46000001, 47000000) g(a);
insert into a select a from generate_series(47000001, 48000000) g(a);
insert into a select a from generate_series(48000001, 49000000) g(a);
insert into a select a from generate_series(49000001, 50000000) g(a);

insert into a select a from generate_series(50000001, 51000000) g(a);
insert into a select a from generate_series(51000001, 52000000) g(a);
insert into a select a from generate_series(52000001, 53000000) g(a);
insert into a select a from generate_series(53000001, 54000000) g(a);
insert into a select a from generate_series(54000001, 55000000) g(a);
insert into a select a from generate_series(55000001, 56000000) g(a);
insert into a select a from generate_series(56000001, 57000000) g(a);
insert into a select a from generate_series(57000001, 58000000) g(a);
insert into a select a from generate_series(58000001, 59000000) g(a);
insert into a select a from generate_series(59000001, 60000000) g(a);

insert into a select a from generate_series(60000001, 61000000) g(a);
insert into a select a from generate_series(61000001, 62000000) g(a);
insert into a select a from generate_series(62000001, 63000000) g(a);
insert into a select a from generate_series(63000001, 64000000) g(a);
insert into a select a from generate_series(64000001, 65000000) g(a);
insert into a select a from generate_series(65000001, 66000000) g(a);
insert into a select a from generate_series(66000001, 67000000) g(a);
insert into a select a from generate_series(67000001, 68000000) g(a);
insert into a select a from generate_series(68000001, 69000000) g(a);
insert into a select a from generate_series(69000001, 70000000) g(a);

insert into a select a from generate_series(70000001, 71000000) g(a);
insert into a select a from generate_series(71000001, 72000000) g(a);
insert into a select a from generate_series(72000001, 73000000) g(a);
insert into a select a from generate_series(73000001, 74000000) g(a);
insert into a select a from generate_series(74000001, 75000000) g(a);
insert into a select a from generate_series(75000001, 76000000) g(a);
insert into a select a from generate_series(76000001, 77000000) g(a);
insert into a select a from generate_series(77000001, 78000000) g(a);
insert into a select a from generate_series(78000001, 79000000) g(a);
insert into a select a from generate_series(79000001, 80000000) g(a);

insert into a select a from generate_series(80000001, 81000000) g(a);
insert into a select a from generate_series(81000001, 82000000) g(a);
insert into a select a from generate_series(82000001, 83000000) g(a);
insert into a select a from generate_series(83000001, 84000000) g(a);
insert into a select a from generate_series(84000001, 85000000) g(a);
insert into a select a from generate_series(85000001, 86000000) g(a);
insert into a select a from generate_series(86000001, 87000000) g(a);
insert into a select a from generate_series(87000001, 88000000) g(a);
insert into a select a from generate_series(88000001, 89000000) g(a);
insert into a select a from generate_series(89000001, 90000000) g(a);

insert into a select a from generate_series(90000001, 91000000) g(a);
insert into a select a from generate_series(91000001, 92000000) g(a);
insert into a select a from generate_series(92000001, 93000000) g(a);
insert into a select a from generate_series(93000001, 94000000) g(a);
insert into a select a from generate_series(94000001, 95000000) g(a);
insert into a select a from generate_series(95000001, 96000000) g(a);
insert into a select a from generate_series(96000001, 97000000) g(a);
insert into a select a from generate_series(97000001, 98000000) g(a);
insert into a select a from generate_series(98000001, 99000000) g(a);
insert into a select a from generate_series(99000001, 100000000) g(a);
```

Once I give the current intents from the INSERTS some time to clear and settle down, I then run this:

```
UPDATE a SET b = 'Hello world' WHERE b IS NULL;
```

I then watch the intents climb with this query:

```
select sum((crdb_internal.range_stats(start_key)->'intent_count')::int) as intent_count
from crdb_internal.ranges_no_leases as r
join crdb_internal.tables as t on r.table_id = t.table_id;
```

The intents climb to 100,000,000 as expected, then I would expect the write to 'complete' and the intents to start dropping.  However, what happens instead is it reaches 100,000,000 then hangs.  In the DBConsole, I see the query and the 'retries' value goes to 1.  There are no other queries running (unless there are internal ones?) so I wouldn't expect this to fail.  Of course, I realise this is bad practise for bulk-insertions, and I would expect it to take a long time, but I would also expect it to complete.

**Environment:**
 - CockroachDB version 21.1.7
 - Server OS: Linux
 - Client app: cockroach sql

### PR DESCRIPTION
**Pull request by fqazi**
Fixes: #69089

Previously, the transaction deadline was only refreshed
when we bubbled back up to the transaction state machinery
inside the SQL layer. This was inadequate for implicit
transactions, since we will not bubble back up and refresh
the deadline and leading to a retry error. If the implicit transaction
takes longer than the lease time, then we will be indefinitely
retrying the transaction. To address this, this patch
will add logic to bubble back up to the SQL layer to
refresh the deadline before trying to commit.

Release justification: low risk and addresses a severe issue with bulk
operations
Release note (bug fix): Bulk insert/update in implicit txn can
retry indefinitely if the statement exceeds the default leasing
deadline of 5 minutes.

### CODE REVIEW

**Review by ajwerner — COMMENTED** [review]
Cool! 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/69936#-:-Mj5rwFb54V3nDIUIBIi:brqw03x)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @fqazi)

___
*[pkg/kv/txn.go, line 760 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/69936#-Mj5psCtCrxZZCtr2VMw:-Mj5psCtCrxZZCtr2VMx:bxd67x5) ([raw file](https://github.com/cockroachdb/cockroach/blob/b8538554c3f929a13e57f8088b55a42009f49957/pkg/kv/txn.go#L760)):*
> ```Go
> 	txn.mu.Lock()
> 	defer txn.mu.Unlock()
> 	isExpired := !txn.mu.deadline.IsEmpty() &&
> ```

nit: just return it instead of assigning to a variable. 
___
*[pkg/kv/txn.go, line 764 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/69936#-Mj5pY0x0xX87KadYgDF:-Mj5pY0x0xX87KadYgDG:bm8sgk) ([raw file](https://github.com/cockroachdb/cockroach/blob/b8538554c3f929a13e57f8088b55a42009f49957/pkg/kv/txn.go#L764)):*
> ```Go
> 		// it off the sender.
> 		(txn.mu.deadline.Less(txn.mu.sender.ProvisionalCommitTimestamp()) ||
> 			txn.mu.deadline.Less(txn.DB().Clock().Now()))
> ```

how about: `txn.mu.deadline.GoTime().After(txn.DB().Clock().PhysicalTime()))` to avoid hitting the `hlc`. We don't care about the logical bits. 
___
*[pkg/sql/catalog/lease/lease_test.go, line 2854 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/69936#-Mj5q5kM1Nu7phL1BM7y:-Mj5q5kM1Nu7phL1BM7z:bxjqr5q) ([raw file](https://github.com/cockroachdb/cockroach/blob/b8538554c3f929a13e57f8088b55a42009f49957/pkg/sql/catalog/lease/lease_test.go#L2854)):*
> ```Go
> 	ctx := context.Background()
> 
> 	beforeAutoCommit := syncutil.Mutex{}
> ```

nit: put the mutex near above the variables it protects?
___
*[pkg/sql/catalog/lease/lease_test.go, line 2868 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/69936#-Mj5rMonEruzpwqtJdnu:-Mj5rMonEruzpwqtJdnv:b-z7s6bt) ([raw file](https://github.com/cockroachdb/cockroach/blob/b8538554c3f929a13e57f8088b55a42009f49957/pkg/sql/catalog/lease/lease_test.go#L2868)):*
> ```Go
> 	// require the lease to be reacquired.
> 	lease.LeaseDuration.Override(ctx, &params.SV, 0)
> 	params.Knobs.SQLExecutor = &sql.ExecutorTestingKnobs{
> ```

this is pretty subtle. The subtest works because we inject this hook which only gets called from the conn executor performing the commit as opposed to the commit being performed during execution. Can you add commentary so a reader might be able to understand?
___
*[pkg/sql/catalog/lease/lease_test.go, line 2875 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/69936#-Mj5rt2fBMeVlaQtJstT:-Mj5rt2fBMeVlaQtJstU:b-5xjvix) ([raw file](https://github.com/cockroachdb/cockroach/blob/b8538554c3f929a13e57f8088b55a42009f49957/pkg/sql/catalog/lease/lease_test.go#L2875)):*
> ```Go
> 				blockAutoCommitResume <- struct{}{}
> 			}
> 			beforeAutoCommit.Unlock()
> ```

nit: defer?
___
*[pkg/sql/catalog/lease/lease_test.go, line 3052 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/69936#-Mj5qJU3APO5VkQPZog8:-Mj5qJU3APO5VkQPZog9:b-1b2ojo) ([raw file](https://github.com/cockroachdb/cockroach/blob/b8538554c3f929a13e57f8088b55a42009f49957/pkg/sql/catalog/lease/lease_test.go#L3052)):*
> ```Go
> 		_, err = conn.ExecContext(ctx, `
> INSERT INTO t1 select a from generate_series(1, 100) g(a);
> SET SQL_SAFE_UPDATES=no
> ```

why the `SQL_SAFE_UPDATES`?
___
*[pkg/sql/catalog/lease/lease_test.go, line 3059 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/69936#-Mj5qEFu-CMNbEmjXJ-H:-Mj5qEFu-CMNbEmjXJ-I:bw4j6d6) ([raw file](https://github.com/cockroachdb/cockroach/blob/b8538554c3f929a13e57f8088b55a42009f49957/pkg/sql/catalog/lease/lease_test.go#L3059)):*
> ```Go
> 		go func() {
> 			beforeAutoCommit.Lock()
> 			blockAutoCommitStmt = "UPDATE t1 SET val = 2"
> ```

nit: define this string as a const and then us it here and in the `ExecContext` call.

**Review by fqazi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/69936)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner and @fqazi)

___
*[pkg/sql/catalog/lease/lease_test.go, line 2868 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/69936#-Mj5rMonEruzpwqtJdnu:-Mj6-SndDK8R6YHf_wqL:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/b8538554c3f929a13e57f8088b55a42009f49957/pkg/sql/catalog/lease/lease_test.go#L2868)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

this is pretty subtle. The subtest works because we inject this hook which only gets called from the conn executor performing the commit as opposed to the commit being performed during execution. Can you add commentary so a reader might be able to understand?
</blockquote></details>

Done.

**Review by ajwerner — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/69936)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @fqazi)

___
*[pkg/sql/catalog/lease/lease_test.go, line 2870 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/69936#-Mj64EMM52fHI3_TZpdb:-Mj64EMM52fHI3_TZpdc:bc3413x) ([raw file](https://github.com/cockroachdb/cockroach/blob/5b343699c5e64e82ab472ab762e372e1e859b5fa/pkg/sql/catalog/lease/lease_test.go#L2870)):*
> ```Go
> 	// Inject a hook to slow down the autocommit coming from
> 	// the connection executor side, which will allow us to
> 	// add potential delays that cause leases to expire.
> ```

This comment is making me question the intention of the hook. My reading was that we inject this hook only to make sure that the hook gets called and not to inject any sort of delay for anything to expire. The test does not exercise the case where a transaction issuing an `UPDATE` would actually fail, it just verifies that the transaction does not attempt to commit in the writing batch. The mechanism for that verfication is the fact that this got called. 

If you wanted to ensure that the transaction actually would have failed, then you'd need to force its timestamp to get pushed.

**Review by fqazi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/69936)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner)

___
*[pkg/sql/catalog/lease/lease_test.go, line 3052 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/69936#-Mj5qJU3APO5VkQPZog8:-Mj7QA86BCmrpoH6gduk:bb6un1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/b8538554c3f929a13e57f8088b55a42009f49957/pkg/sql/catalog/lease/lease_test.go#L3052)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

why the `SQL_SAFE_UPDATES`?
</blockquote></details>

Done
___
*[pkg/sql/catalog/lease/lease_test.go, line 3059 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/69936#-Mj5qEFu-CMNbEmjXJ-H:-Mj7Q8gh36S2mQXDrOtQ:bb6un1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/b8538554c3f929a13e57f8088b55a42009f49957/pkg/sql/catalog/lease/lease_test.go#L3059)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

nit: define this string as a const and then us it here and in the `ExecContext` call. 
</blockquote></details>

Done
___
*[pkg/sql/catalog/lease/lease_test.go, line 2870 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/69936#-Mj64EMM52fHI3_TZpdb:-Mj7QBZm49g-JwP2zfOm:bfuw413) ([raw file](https://github.com/cockroachdb/cockroach/blob/5b343699c5e64e82ab472ab762e372e1e859b5fa/pkg/sql/catalog/lease/lease_test.go#L2870)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

This comment is making me question the intention of the hook. My reading was that we inject this hook only to make sure that the hook gets called and not to inject any sort of delay for anything to expire. The test does not exercise the case where a transaction issuing an `UPDATE` would actually fail, it just verifies that the transaction does not attempt to commit in the writing batch. The mechanism for that verfication is the fact that this got called. 

If you wanted to ensure that the transaction actually would have failed, then you'd need to force its timestamp to get pushed.
</blockquote></details>

Ugh, yes I misunderstood why I saw a hang without the fix. The auto-commit hook is only called if a 1PC optimization doesn't occur. With this change we expect this optimization to be skipped in the expiry case and bubble to the SQL executor layer for the commit.

I fixed the comment.

**Review by ajwerner — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/69936)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @fqazi)

___
*[pkg/sql/catalog/lease/lease_test.go, line 3051 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/69936#-Mj9lFt204erk-ONArYq:-Mj9lFt204erk-ONArYr:b-ef05ud) ([raw file](https://github.com/cockroachdb/cockroach/blob/8d900a1a46ccf20af81a9c4b1efd0e32e17da79b/pkg/sql/catalog/lease/lease_test.go#L3051)):*
> ```Go
> 	// above via the LeaseDuration override. The auto-commit hook allows
> 	// us to confirm the 1 phase commit optimization is bypassed due,
> 	// to the lease expiring.
> ```

I'm still unclear on how the initial deadline from leasing related to the transaction timestamp. Did you ever investigate that? I'd have expected that the expiration would be after the transaction timestamp because it'll be at the timestamp of the leasing transaction, which will be after the user transaction timestamp. Then, nothing should push, so I'm not clear on why we hit the retries in this test without the case to bubble back up. I think the deal is that we would not. In that case, the test is a little confusing and complex given the expiration isn't really relevant. 

One option would be to block the update request, and then read the data and then unblock the update request which will push the timestamp.

**Review by ajwerner — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/69936)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @fqazi)

___
*[pkg/sql/catalog/lease/lease_test.go, line 3115 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/69936#-MjAZZuZ9SDK846jaKc-:-MjAZZuZ9SDK846jaKc0:b-iuzsi0) ([raw file](https://github.com/cockroachdb/cockroach/blob/ee8efb2f2095f73ab31b97b9a50d2bc59f1f8b7a/pkg/sql/catalog/lease/lease_test.go#L3115)):*
> ```Go
> 		beforeExecuteResumeStmt = selectQuery
> 		beforeExecute.Unlock()
> 		pushLimit := 4
> ```

I think this ends up being sort of confusing because we should only ever get pushed once, right? Why even have a limit?

**Review by ajwerner — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r2, 1 of 2 files at r6.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/69936)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @fqazi)

___
*[pkg/sql/conn_executor_exec.go, line 1797 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/69936#-MjB1Sgg8BHNdalgb33I:-MjB1SghEAz6lc5lMpTA:b-8so11) ([raw file](https://github.com/cockroachdb/cockroach/blob/1d3d2f5d8475e3c1162aaee89628acf398be0fea/pkg/sql/conn_executor_exec.go#L1797)):*
> ```Go
> 	}
> 
> 	// Attempt to refresh the deadline before the autocommit
> ```

nit: period
___
*[pkg/sql/tablewriter.go, line 226 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/69936#-MjB1cnD337ctdK_wm_G:-MjB1cnD337ctdK_wm_H:b-wc5pmt) ([raw file](https://github.com/cockroachdb/cockroach/blob/1d3d2f5d8475e3c1162aaee89628acf398be0fea/pkg/sql/tablewriter.go#L226)):*
<details><summary><i alt="summary">Quoted 4 lines of code…</i></summary>

> ```
> 		// We can only auto commit if the rows written guardrail is disabled or
> 		// we haven't reached the specified limit (the optimizer is responsible
> 		// for making sure that there is exactly one mutation before enabling
> 		// the auto commit).
> ```
</details>

delete this now duplicated comment. 
___
*[pkg/sql/catalog/lease/lease_test.go, line 3029 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/69936#-MjB1lOCBPHG04oFl6pt:-MjB1lOCBPHG04oFl6pu:b9z4roo) ([raw file](https://github.com/cockroachdb/cockroach/blob/1d3d2f5d8475e3c1162aaee89628acf398be0fea/pkg/sql/catalog/lease/lease_test.go#L3029)):*
> ```Go
> }
> 
> func TestLeaseBulkInsert(t *testing.T) {
> ```

give this a comment explaining the problem that this test is making sure we fixed. 
___
*[pkg/sql/catalog/lease/lease_test.go, line 3047 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/69936#-MjB_WK67PVLcRgbWum9:-MjB_WK67PVLcRgbWumA:b-552bnp) ([raw file](https://github.com/cockroachdb/cockroach/blob/1d3d2f5d8475e3c1162aaee89628acf398be0fea/pkg/sql/catalog/lease/lease_test.go#L3047)):*
> ```Go
> 	lease.LeaseDuration.Override(ctx, &params.SV, 0)
> 	params.Knobs.SQLExecutor = &sql.ExecutorTestingKnobs{
> 		BeforeExecute: func(ctx context.Context, stmt string) {
> ```

comment this?
___
*[pkg/sql/catalog/lease/lease_test.go, line 3108 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/69936#-MjBaAVn1n_5te4_tvay:-MjBaAVn1n_5te4_tvaz:b-s14qrd) ([raw file](https://github.com/cockroachdb/cockroach/blob/1d3d2f5d8475e3c1162aaee89628acf398be0fea/pkg/sql/catalog/lease/lease_test.go#L3108)):*
> ```Go
> 		// go through.
> 		for atomic.LoadUint32(&executingUpdate) == 1 {
> 			beforeExecuteWait <- struct{}{}
> ```

I feel like this synchronization is not what I expected. I'd have expected that the beforeExecute hook sends a channel and then this goroutine closes the channel after it does the read. This here seems racy.

**Review by fqazi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/69936)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner)

___
*[pkg/sql/catalog/lease/lease_test.go, line 3051 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/69936#-Mj9lFt204erk-ONArYq:-MjAUc9E3fDIK3umxCB3:bq8dk7i) ([raw file](https://github.com/cockroachdb/cockroach/blob/8d900a1a46ccf20af81a9c4b1efd0e32e17da79b/pkg/sql/catalog/lease/lease_test.go#L3051)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

I'm still unclear on how the initial deadline from leasing related to the transaction timestamp. Did you ever investigate that? I'd have expected that the expiration would be after the transaction timestamp because it'll be at the timestamp of the leasing transaction, which will be after the user transaction timestamp. Then, nothing should push, so I'm not clear on why we hit the retries in this test without the case to bubble back up. I think the deal is that we would not. In that case, the test is a little confusing and complex given the expiration isn't really relevant. 

One option would be to block the update request, and then read the data and then unblock the update request which will push the timestamp. 
</blockquote></details>

Reworked this push out the transaction a limited amount of time and confirm the autocommit side of things, where we should bubble back up to the top.
___
*[pkg/sql/catalog/lease/lease_test.go, line 3047 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/69936#-MjB_WK67PVLcRgbWum9:-MjCPYRsC4oKTp6Cc5a5:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/1d3d2f5d8475e3c1162aaee89628acf398be0fea/pkg/sql/catalog/lease/lease_test.go#L3047)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

comment this?
</blockquote></details>

Done.

**Review by andreimatei — COMMENTED** [review]
can you please explain to me what layer the endless retries were happening at?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/69936#-:-MjZko04EJBs9M3n3I9z:bl9k201)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner and @fqazi)

___
*[pkg/sql/catalog/lease/lease_test.go, line 3127 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/69936#-MjZYxIq0tsdySnXovZn:-MjZYxIq0tsdySnXovZo:b3kqk) ([raw file](https://github.com/cockroachdb/cockroach/blob/667f4777ae33a719b01633f5f8344ca3d8bc271a/pkg/sql/catalog/lease/lease_test.go#L3127)):*
> ```Go
> 			`+selectQuery+";\n"+
> 				`END;`)
> 			/*	require.NoError(t, err)
> ```

!

**Review by fqazi — COMMENTED** [review]
The retires are not necessarily endless, and from transaction, protocol refresh errors due to deadline expirey. Bulk operations can be extremely long, so it will *look* endless, but not really endless it should eventually timeout. But, that could be a really long time.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/69936#-:-MjZr6sI4V-vQcjAn4rZ:blrukab)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner and @fqazi)

**Review by andreimatei — COMMENTED** [review]
Consider talking about auto-commit in the commit message. As written I've found it confusing.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/69936#-:-MjZycfU0m-o29HFfk60:bispgt5)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner and @fqazi)

___
*[pkg/kv/txn.go, line 755 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/69936#-MjZyMYX5WW5qt37zVP2:-MjZyMYX5WW5qt37zVP3:bt6dviy) ([raw file](https://github.com/cockroachdb/cockroach/blob/c6b56383bde6e8ed99619ed9e9a03a91dfd00899/pkg/kv/txn.go#L755)):*
> ```Go
> // DeadlineMightBeExpired returns true if there currently is a deadline and
> // that deadline is earlier than either the ProvisionalCommitTimestamp or
> // the current timestamp. This can be used as a hint that we do not want to
> ```

Please explain the "current timestamp" part. I think it's only relevant if there are going to be more writes in the txn, so consider taking a flag and letting the client say that interactions with the timestamp cache are impossible because the rest of the txn is read-only. I think that's an important case to consider, and it would also help the code clarify that the MVCC timestamp domain is different from the wall-clock domain - the descriptor leases work in the MVCC domain, so that's the main thing that a method like this cares about.
When the client declares that there's no more writes, you could use `Transaction.global_uncertainty_limit` instead of `ProvisionalCommitTimestamp` to account for the possibility of running into `ReadWithinUncertaintyErrors` that can push the timestamp up.
___
*[pkg/kv/txn.go, line 756 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/69936#-MjZy5b65JjxFXNC1Tga:-MjZy5b65JjxFXNC1Tgb:bwa5fu1) ([raw file](https://github.com/cockroachdb/cockroach/blob/c6b56383bde6e8ed99619ed9e9a03a91dfd00899/pkg/kv/txn.go#L756)):*
> ```Go
> // that deadline is earlier than either the ProvisionalCommitTimestamp or
> // the current timestamp. This can be used as a hint that we do not want to
> // auto-commit the transaction in a batch with writes.
> ```

I'd either say more or say less about the relation with auto-commit. Consider striking that part of the comment.

File: pkg/kv/txn.go [hunk 1]
```diff
@@ -761,6 +761,31 @@ func (txn *Txn) UpdateDeadline(ctx context.Context, deadline hlc.Timestamp) erro
...
+		// Avoids getting the txn mutex again by getting
+		// it off the sender.
+		(txn.mu.deadline.Less(txn.mu.sender.ProvisionalCommitTimestamp()) ||
+			// In case the transaction gets pushed and the push is not observed,
+			// we cautiously also indicate that a refresh is needed if the current
+			// wall time exceeds the deadline. Note: The MVCC timestamp is used for
+			// leases so the comparison here is between that and wall time, to be
+			// cautious we will add the global uncertainty limit of the txn.
+			txn.mu.deadline.GoTime().Before(txn.DB().Clock().PhysicalTime().Add(
+				(time.Second*time.Duration(globalUncertaintyTime.Second()))+
```
Comment (ajwerner) [inline pkg/kv/txn.go:785]: I don't understand this duration conversion. I know we talked about clock offsets but there's a bunch of concepts here that are not well described. 

Like, this last part of this conditional doesn't make sense to me. It seems like a timestamp is being treated as a duration but even then the nanoseconds and seconds calculations aren't very clear to me.

File: pkg/kv/sender.go [hunk 2]
```diff
@@ -231,6 +231,11 @@ type TxnSender interface {
 	// field on TxnMeta.
 	ProvisionalCommitTimestamp() hlc.Timestamp
 
+	// GlobalUncertaintyLimit returns the transaction's global uncertainty
+	// limit, which is the maximum clock drift observed across. This is used
+	// for dealing with clock time vs MVCC time for certain hueristics.
+	GlobalUncertaintyLimit() hlc.Timestamp
```
Comment (ajwerner) [inline pkg/kv/sender.go:237]: Something seems off about the need to expose this. Also, I was envisioning a duration. This deserves commentary if we need to expose it.

**Review by fqazi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/69936)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @andreimatei, and @fqazi)

___
*[pkg/kv/txn.go, line 785 at r12](https://reviewable.io/reviews/cockroachdb/cockroach/69936#-Mj5itXNGAO3-Aa_Gdam-r12-785:-MkHye6XCVmeObjV0O-j:br4rnk8) ([raw file](https://github.com/cockroachdb/cockroach/blob/d1f15bb99dc1393ac4d1cfa169d1e2a6a16d9ac6/pkg/kv/txn.go#L785)):*
> s duration conversion. I know we talked about clock offsets but there's a b
This was incorrect on my part, I thought we were storing a duration inside a hlc.Timestamp or something funny, but that's not the case. Let me revisit this.

**Review by fqazi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/69936)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @andreimatei, and @fqazi)

___
*[pkg/kv/txn.go, line 785 at r12](https://reviewable.io/reviews/cockroachdb/cockroach/69936#-Mj5itXNGAO3-Aa_Gdam-r12-785:-MkI3hT98eD7UTR_4Ynr:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/d1f15bb99dc1393ac4d1cfa169d1e2a6a16d9ac6/pkg/kv/txn.go#L785)):*
<details><summary><i>Previously, fqazi (Faizan Qazi) wrote…</i></summary><blockquote>

> s duration conversion. I know we talked about clock offsets but there's a b
This was incorrect on my part, I thought we were storing a duration inside a hlc.Timestamp or something funny, but that's not the case. Let me revisit this.
</blockquote></details>

Done.
___
*[pkg/sql/catalog/lease/lease_test.go, line 3127 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/69936#-MjZYxIq0tsdySnXovZn:-MkI3jSc-vQEqYzfiS89:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/667f4777ae33a719b01633f5f8344ca3d8bc271a/pkg/sql/catalog/lease/lease_test.go#L3127)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

!
</blockquote></details>

Done.
___
*[pkg/kv/sender.go, line 237 at r12](https://reviewable.io/reviews/cockroachdb/cockroach/69936#-MjoQxwCexWtxUQxD3xX-r12-237:-MkI3kaOBV2-ps6UO8YS:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/d1f15bb99dc1393ac4d1cfa169d1e2a6a16d9ac6/pkg/kv/sender.go#L237)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

Something seems off about the need to expose this. Also, I was envisioning a duration. This deserves commentary if we need to expose it. 
</blockquote></details>

Done.

**Review by ajwerner — COMMENTED** [review]
Thanks for the stamina working through this!

> Reviewed 1 of 8 files at r12.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/69936#-:-MkILWyN7pBlmirAI9gA:b-yatk34)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @andreimatei, and @fqazi)

___
*[pkg/kv/txn.go, line 766 at r13](https://reviewable.io/reviews/cockroachdb/cockroach/69936#-MkIHzGfBYkiQxVZ08HS:-MkIHzGfBYkiQxVZ08HT:branx9v) ([raw file](https://github.com/cockroachdb/cockroach/blob/dab4673fd31328ae53dcaf844fcfb5abdcefcbe6/pkg/kv/txn.go#L766)):*
> ```Go
> // DeadlineMightBeExpired returns true if there currently is a deadline and
> // that deadline is earlier than either the ProvisionalCommitTimestamp or
> // the current timestamp.  If the expiration is past the current timestamp,
> ```

say `or the current reading of the node's hlc clock. The second condition is a conservative optimization to deal with the fact that the provisional commit timestamp may not represent the true commit timestamp; the transaction may have been pushed but not yet discovered that fact. Deadlines, in general, should not commonly be at risk of expiring near the current time, except in extraordinary circumstances. In cases where considering it helps, it helps a lot. In cases where considering it does not help, it does not hurt much.`
___
*[pkg/sql/catalog/lease/lease_test.go, line 3127 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/69936#-MjZYxIq0tsdySnXovZn:-MkIJ01a1IR5hqWXUIxC:b-4fdpvm) ([raw file](https://github.com/cockroachdb/cockroach/blob/667f4777ae33a719b01633f5f8344ca3d8bc271a/pkg/sql/catalog/lease/lease_test.go#L3127)):*
<details><summary><i>Previously, fqazi (Faizan Qazi) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

nit: I'd just inline the statement in a const

```
const (
    selectStmt = `SELECT * FROM t1`
   selectTxn = `BEGIN PRIORITY HIGH; `+selectStmt+`; COMMIT;`
)
```
___
*[pkg/sql/catalog/lease/lease_test.go, line 3057 at r13](https://reviewable.io/reviews/cockroachdb/cockroach/69936#-MkIKaQa3Rtw2H0hVilF:-MkIKaQa3Rtw2H0hVilG:bp7ify) ([raw file](https://github.com/cockroachdb/cockroach/blob/dab4673fd31328ae53dcaf844fcfb5abdcefcbe6/pkg/sql/catalog/lease/lease_test.go#L3057)):*
> ```Go
> 			beforeExecute.Lock()
> 			if stmt == beforeExecuteStmt {
> 				log.Errorf(ctx, "TEST: WAITING FOR SELECT")
> ```

nit: remove
___
*[pkg/sql/catalog/lease/lease_test.go, line 3084 at r13](https://reviewable.io/reviews/cockroachdb/cockroach/69936#-MkIKc3O0GjcSOm14Hrv:-MkIKc3O0GjcSOm14Hrw:bp7ify) ([raw file](https://github.com/cockroachdb/cockroach/blob/dab4673fd31328ae53dcaf844fcfb5abdcefcbe6/pkg/sql/catalog/lease/lease_test.go#L3084)):*
> ```Go
> 			beforeExecute.Lock()
> 			if stmt == beforeExecuteResumeStmt {
> 				log.Errorf(ctx, "TEST: UNPAUSING FOR UPDATE")
> ```

nit: remove
___
*[pkg/sql/catalog/lease/lease_test.go, line 3102 at r13](https://reviewable.io/reviews/cockroachdb/cockroach/69936#-MkIL-hKBEJrYWFbHL1R:-MkIL-hKBEJrYWFbHL1S:b-5r8mqz) ([raw file](https://github.com/cockroachdb/cockroach/blob/dab4673fd31328ae53dcaf844fcfb5abdcefcbe6/pkg/sql/catalog/lease/lease_test.go#L3102)):*
> ```
> 	_, err := conn.Exec(`
> CREATE TABLE t1(val int);
> 	`)
> ```
it might be interesting and worthwhile to split this table so we're doing a cross-range transaction. In practice, the cases we care about involve cross range transactions. It'd be a bummer if a single-range optimization hid some issue.

How about the following in setup here?

```sql
ALTER TABLE t1 SPLIT AT VALUES (1)
```
___
*[pkg/sql/catalog/lease/lease_test.go, line 3119 at r13](https://reviewable.io/reviews/cockroachdb/cockroach/69936#-MkIJonrCoJUwd3_HSyT:-MkIJonrCoJUwd3_HSyU:b-e9pjwr) ([raw file](https://github.com/cockroachdb/cockroach/blob/dab4673fd31328ae53dcaf844fcfb5abdcefcbe6/pkg/sql/catalog/lease/lease_test.go#L3119)):*
> ```Go
> 	// transaction readline for this.
> 	t.Run("validate-lease-txn-deadline-ext-update", func(t *testing.T) {
> 		runSelects := uint32(1)
> ```

thoughts on:

1) making this an atomic.Value with a bool?
2) calling it updateCompleted (and thus initializing it to false)?
___
*[pkg/sql/catalog/lease/lease_test.go, line 3137 at r13](https://reviewable.io/reviews/cockroachdb/cockroach/69936#-MkIK14JBpoiX0LfMpIe:-MkIK14JBpoiX0LfMpIf:bwosg2n) ([raw file](https://github.com/cockroachdb/cockroach/blob/dab4673fd31328ae53dcaf844fcfb5abdcefcbe6/pkg/sql/catalog/lease/lease_test.go#L3137)):*
> ```Go
> 			// Execute a bulk UPDATE, which will get its
> 			// timestamp pushed by a read operation.
> 			_, err := conn.ExecContext(ctx, bulkUpdateQuery)
> ```

I'd expect this to use `updateConn` and the select to use `conn` (or call it `selectConn`)?

**Review by fqazi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/69936)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @andreimatei, and @fqazi)

___
*[pkg/sql/catalog/lease/lease_test.go, line 3127 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/69936#-MjZYxIq0tsdySnXovZn:-MkI_QAm4nq5D_1iv2mw:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/667f4777ae33a719b01633f5f8344ca3d8bc271a/pkg/sql/catalog/lease/lease_test.go#L3127)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

nit: I'd just inline the statement in a const

```
const (
    selectStmt = `SELECT * FROM t1`
   selectTxn = `BEGIN PRIORITY HIGH; `+selectStmt+`; COMMIT;`
)
```
</blockquote></details>

Done.
___
*[pkg/sql/catalog/lease/lease_test.go, line 3119 at r13](https://reviewable.io/reviews/cockroachdb/cockroach/69936#-MkIJonrCoJUwd3_HSyT:-MkIZ9oz8UpTBugs_OIW:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/736c324b4acdfec9d06d09a07fa2900d094582eb/pkg/sql/catalog/lease/lease_test.go#L3119)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

thoughts on:

1) making this an atomic.Value with a bool?
2) calling it updateCompleted (and thus initializing it to false)?
</blockquote></details>

Done.

**Review by ajwerner — COMMENTED** [review]
:lgtm:

> Reviewed 2 of 8 files at r12, 1 of 2 files at r14, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/69936#-:-MkIpNcH8PW2335c2yeo:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ajwerner, @andreimatei, and @fqazi)

___
*[pkg/sql/catalog/lease/lease_test.go, line 3035 at r14](https://reviewable.io/reviews/cockroachdb/cockroach/69936#-MkIpj5LEhhZHY-mQeyG:-MkIpj5LEhhZHY-mQeyH:b-8so11) ([raw file](https://github.com/cockroachdb/cockroach/blob/160a79cd8a6c5a1ae6b444c5c0ae5fc78e97d7a1/pkg/sql/catalog/lease/lease_test.go#L3035)):*
> ```Go
> 
> 	beforeExecute := syncutil.Mutex{}
> 	// Statement that will be paused
> ```

nit: period
___
*[pkg/sql/catalog/lease/lease_test.go, line 3039 at r14](https://reviewable.io/reviews/cockroachdb/cockroach/69936#-MkIplU2977HLzZTG3mp:-MkIplU2977HLzZTG3mq:boj675i) ([raw file](https://github.com/cockroachdb/cockroach/blob/160a79cd8a6c5a1ae6b444c5c0ae5fc78e97d7a1/pkg/sql/catalog/lease/lease_test.go#L3039)):*
> ```
> 	// Statement that will allow any paused
> 	// statement to resume.
> ```
nit: unnecessary wrapping
___
*[pkg/sql/opt/exec/execbuilder/testdata/autocommit_nonmetamorphic, line 807 at r14](https://reviewable.io/reviews/cockroachdb/cockroach/69936#-MkIq2KYEuLGvmFwHTve:-MkIq2KYEuLGvmFwHTvf:brml7r9) ([raw file](https://github.com/cockroachdb/cockroach/blob/160a79cd8a6c5a1ae6b444c5c0ae5fc78e97d7a1/pkg/sql/opt/exec/execbuilder/testdata/autocommit_nonmetamorphic#L807)):*
> ```
> ----
> dist sender send  r43: sending batch 1 CPut to (n1,s1):1
> dist sender send  r43: sending batch 1 EndTxn to (n1,s1):1
> ```
I don't think we were trying to change this case. Why did it change?

**Review by fqazi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/69936)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @ajwerner, @andreimatei, and @fqazi)

___
*[pkg/sql/opt/exec/execbuilder/testdata/autocommit_nonmetamorphic, line 807 at r14](https://reviewable.io/reviews/cockroachdb/cockroach/69936#-MkIq2KYEuLGvmFwHTve:-MkJ9vBI3s9P6Ewy5IJb:bo8t92i) ([raw file](https://github.com/cockroachdb/cockroach/blob/160a79cd8a6c5a1ae6b444c5c0ae5fc78e97d7a1/pkg/sql/opt/exec/execbuilder/testdata/autocommit_nonmetamorphic#L807)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

> ```
> ----
> dist sender send  r43: sending batch 1 CPut to (n1,s1):1
> dist sender send  r43: sending batch 1 EndTxn to (n1,s1):1
> ```
I don't think we were trying to change this case. Why did it change? 
</blockquote></details>

This was caused by me accidentally deleting an equal sign on the row limit enforcement.

**Review by fqazi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/69936)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @ajwerner, @andreimatei, and @fqazi)

___
*[pkg/kv/txn.go, line 755 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/69936#-MjZyMYX5WW5qt37zVP2:-MkJB9jhAckxYxPCGRoU:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/c6b56383bde6e8ed99619ed9e9a03a91dfd00899/pkg/kv/txn.go#L755)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

Please explain the "current timestamp" part. I think it's only relevant if there are going to be more writes in the txn, so consider taking a flag and letting the client say that interactions with the timestamp cache are impossible because the rest of the txn is read-only. I think that's an important case to consider, and it would also help the code clarify that the MVCC timestamp domain is different from the wall-clock domain - the descriptor leases work in the MVCC domain, so that's the main thing that a method like this cares about.
When the client declares that there's no more writes, you could use `Transaction.global_uncertainty_limit` instead of `ProvisionalCommitTimestamp` to account for the possibility of running into `ReadWithinUncertaintyErrors` that can push the timestamp up.
</blockquote></details>

Done.
___
*[pkg/kv/txn.go, line 756 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/69936#-MjZy5b65JjxFXNC1Tga:-MkJB9HgAgYAm4aSfNxV:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/c6b56383bde6e8ed99619ed9e9a03a91dfd00899/pkg/kv/txn.go#L756)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

I'd either say more or say less about the relation with auto-commit. Consider striking that part of the comment.
</blockquote></details>

Done.

**Review by ajwerner — APPROVED** [review]
:lgtm_strong: 

> Reviewed 2 of 3 files at r15.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/69936#-:-MkJhObl6-W1kp7aJRfO:b-uwkowd)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ajwerner and @andreimatei)

**Comment by fqazi** [comment]
@ajwerner TFTR

**Comment by ajwerner** [comment]
Can we bors this?

**Comment by ajwerner** [comment]
@andreimatei want to review the commentary?

**Review by andreimatei — APPROVED** [review]
:lgtm: but see comments.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/69936#-:-MkbxcKRDA8CnPE0HtsE:b-sq0wch)* status: :shipit: complete! 2 of 0 LGTMs obtained (waiting on @ajwerner, @andreimatei, and @fqazi)

___
*[pkg/kv/txn.go, line 755 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/69936#-MjZyMYX5WW5qt37zVP2:-Mkbo3aYEi-9vLK7UsZi:bfawt0w) ([raw file](https://github.com/cockroachdb/cockroach/blob/c6b56383bde6e8ed99619ed9e9a03a91dfd00899/pkg/kv/txn.go#L755)):*
<details><summary><i>Previously, fqazi (Faizan Qazi) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

You say "Done", but you haven't taken a position on whether we should make a distinction between transactions that have finished writing vs transactions that still want to write. Instead, you're making the remark that `the transaction may have been pushed but not yet discovered that fact`. That's interesting; I hadn't considered it. At first I wasn't gonna buy that that's a significant case, but I've read the rangefeed pusher code and I see that it does high-priority pushes, and it also pushes right up to the present time. So I guess I do buy it as likely enough. But still, at the very least, I'd make an additional note of the fact that, if the transaction is writing, it's likely enough to be pushed when it writes. I think that's at least as important as the case where we have already been pushed but we don't know it.

One thing I still struggle with is that this method makes too big of a deal out of the present time. As far as I can think, that's unprincipled and, even worse, confusing. First of all, clocks are desynchronized, so if we've been pushed, we might have been pushed above the present time. Second, the door is open to races with concurrent pushes. Third, if the transaction is writing to non-blocking ranges, then it's commit timestamps is going to be in the future of present time. The method already accounts for the txn's previous writes to non-blocking ranges because it considers the `ProvisionalCommitTimestamp`, but it doesn't account for future writes to non-blocking ranges. I think we should easily account for all these things by setting the threshold for the commit timestamp a bit in the future. Putting a fudge factor in there will also suggest to the reader that this is all best-effort. Consider using `TargetForPolicy(...,LEAD_FOR_GLOBAL_READS) + 1s`.
___
*[pkg/kv/txn.go, line 770 at r15](https://reviewable.io/reviews/cockroachdb/cockroach/69936#-MkbifK9BeRtC5VUvvTd:-MkbifKA6TT3lEIlH3Xf:bjfvxo2) ([raw file](https://github.com/cockroachdb/cockroach/blob/f23ffbefa78941f7b86d133f6bd6fbaa28121b7e/pkg/kv/txn.go#L770)):*
> ```Go
> // the true commit timestamp; the transaction may have been pushed but not yet discovered that fact.
> // Deadlines, in general, should not commonly be at risk of expiring near the current time, except in
> // extraordinary circumstances. In cases where considering it helps, it helps a lot. In cases where
> ```

nit: this paragraph is not wrapped at 80 cols
___
*[pkg/kv/txn.go, line 774 at r15](https://reviewable.io/reviews/cockroachdb/cockroach/69936#-MkbjfdyB1_4nrLhVlVa:-MkbjfdyB1_4nrLhVlVb:bhtz9ug) ([raw file](https://github.com/cockroachdb/cockroach/blob/f23ffbefa78941f7b86d133f6bd6fbaa28121b7e/pkg/kv/txn.go#L774)):*
> ```Go
> func (txn *Txn) DeadlineMightBeExpired() bool {
> 	txn.mu.Lock()
> 	txn.mu.sender.ProvisionalCommitTimestamp()
> ```

was this call intended?
___
*[pkg/kv/txn.go, line 778 at r15](https://reviewable.io/reviews/cockroachdb/cockroach/69936#-MkbjSQi1FtmIc-IyYHV:-MkbjSQi1FtmIc-IyYHW:buzjx75) ([raw file](https://github.com/cockroachdb/cockroach/blob/f23ffbefa78941f7b86d133f6bd6fbaa28121b7e/pkg/kv/txn.go#L778)):*
> ```Go
> 	return txn.mu.deadline != nil &&
> 		!txn.mu.deadline.IsEmpty() &&
> 		// Avoids getting the txn mutex again by getting
> ```

Who's "it"? I don't think this comment will make sense to any reader. I'd add a `txn.provisionalCommitTimestampLocked` and avoid any comment.
___
*[pkg/kv/txn.go, line 782 at r15](https://reviewable.io/reviews/cockroachdb/cockroach/69936#-Mkbk1sR4cj7aBkjXvcZ:-Mkbk1sR4cj7aBkjXvc_:bbscyct) ([raw file](https://github.com/cockroachdb/cockroach/blob/f23ffbefa78941f7b86d133f6bd6fbaa28121b7e/pkg/kv/txn.go#L782)):*
> ```Go
> 		(txn.mu.deadline.Less(txn.mu.sender.ProvisionalCommitTimestamp()) ||
> 			// In case the transaction gets pushed and the push is not observed,
> 			// we cautiously also indicate that a refresh is needed if the current
> ```

This is the first time this function mentions the word "refresh", which is inappropriate. If you want to equate "refresh is needed" with the return value of this function (or generally if you want to talk about what a caller might do with the retval), do so in the function-level commentary. Also, I think you're using the word "refresh" to mean something different than it means throughout the KV layer, which is very confusing. You're using it to mean updating the deadline based on new leases. "Refresh" in KV is widely used as short-form for "refreshing a transaction's read timestamp"  through a `RefreshRequest`. So please don't use this word.
___
*[pkg/sql/tablewriter.go, line 222 at r15](https://reviewable.io/reviews/cockroachdb/cockroach/69936#-Mkbwwm_8R5Zst_PFCGI:-Mkbwwma3S9_1iBaiUw4:bwgu8l3) ([raw file](https://github.com/cockroachdb/cockroach/blob/f23ffbefa78941f7b86d133f6bd6fbaa28121b7e/pkg/sql/tablewriter.go#L222)):*
> ```Go
> 		// If we bubble back up to SQL then maybe we can get a fresh deadline
> 		// before committing.
> 		!tb.txn.DeadlineMightBeExpired() {
> ```

Instead of pessimistically inhibiting the auto-commit, have you considered whether it's feasible to reach back in to the lease machinery and call `MaybeUpdateDeadline`, and then allow the auto-commit regardless of the outcome? If feasible, that'd be more directly encode what we really want.

**Review by fqazi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/69936)* status: :shipit: complete! 2 of 0 LGTMs obtained (waiting on @ajwerner and @andreimatei)

___
*[pkg/kv/txn.go, line 755 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/69936#-MjZyMYX5WW5qt37zVP2:-MkcMdux7SBSxAVgKRFn:b-m7l62a) ([raw file](https://github.com/cockroachdb/cockroach/blob/c6b56383bde6e8ed99619ed9e9a03a91dfd00899/pkg/kv/txn.go#L755)):*
> You say "Done", but you haven't taken a position on whether we should make a distinction between transactions that have finished writing vs transactions that still want to write. Instead, you're making the remark that the transaction may have been pushed but not yet discovered that fact. That's interesting; I hadn't considered it. At first I wasn't gonna buy that that's a significant case, but I've read the rangefeed pusher code and I see that it does high-priority pushes, and it also pushes right up to the present time. So I guess I do buy it as likely enough. But still, at the very least, I'd make an additional note of the fact that, if the transaction is writing, it's likely enough to be pushed when it writes. I think that's at least as important as the case where we have already been pushed but we don't know it.
> One thing I still struggle with is that this method makes too big of a deal out of the present time. As far as I can think, that's unprincipled and, even worse, confusing. First of all, clocks are desynchronized, so if we've been pushed, we might have been pushed above the present time. Second, the door is open to races with concurrent pushes. Third, if the transaction is writing to non-blocking ranges, then it's commit timestamps is going to be in the future of present time. The method already accounts for the txn's previous writes to non-blocking ranges because it considers the ProvisionalCommitTimestamp, but it doesn't account for future writes to non-blocking ranges. I think we should easily account for all these things by setting the threshold for the commit timestamp a bit in the future. Putting a fudge factor in there will also suggest to the reader that this is all best-effort. Consider using TargetForPolicy(...,LEAD_FOR_GLOBAL_READS) + 1s.

I added the phrasing: for the first part: 
// Transactions that write from now on can still get pushed, versus
// transactions which are done writing where it will be less clear
// how those get pushed.

Second part I updated the code and described why we are doing a fudge factor.
___
*[pkg/kv/txn.go, line 774 at r15](https://reviewable.io/reviews/cockroachdb/cockroach/69936#-MkbjfdyB1_4nrLhVlVa:-MkcDkYC8VEZejfM1dzb:b4nyjtt) ([raw file](https://github.com/cockroachdb/cockroach/blob/f23ffbefa78941f7b86d133f6bd6fbaa28121b7e/pkg/kv/txn.go#L774)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

was this call intended?
</blockquote></details>

Accidental, removed.
___
*[pkg/kv/txn.go, line 778 at r15](https://reviewable.io/reviews/cockroachdb/cockroach/69936#-MkbjSQi1FtmIc-IyYHV:-MkcJCES2QPxAaENVUAc:bh0qakh) ([raw file](https://github.com/cockroachdb/cockroach/blob/f23ffbefa78941f7b86d133f6bd6fbaa28121b7e/pkg/kv/txn.go#L778)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

Who's "it"? I don't think this comment will make sense to any reader. I'd add a `txn.provisionalCommitTimestampLocked` and avoid any comment.
</blockquote></details>

We can't use the  Locked one because we need the mutex for the deadline. So, I clarified the comment as:
		// Avoid trying to get get the txn mutex again by directly
		// invoking ProvisionalCommitTimestamp versus calling
		// ProvisionalCommitTimestampLocked on the Txn.
___
*[pkg/kv/txn.go, line 782 at r15](https://reviewable.io/reviews/cockroachdb/cockroach/69936#-Mkbk1sR4cj7aBkjXvcZ:-MkcJvJ2D1CGeEcu3Zgz:b-bglhei) ([raw file](https://github.com/cockroachdb/cockroach/blob/f23ffbefa78941f7b86d133f6bd6fbaa28121b7e/pkg/kv/txn.go#L782)):*
> 		// Avoid trying to get get the txn mutex again by directly
> 		// invoking ProvisionalCommitTimestamp versus calling
> 		// ProvisionalCommitTimestampLocked on the Txn.
Good point, changed this comment to:
			// In case the transaction gets pushed and the push is not observed,
			// we cautiously also indicate that the deadline maybe expired if
			// the current HLC clock exceeds the deadline.
___
*[pkg/sql/tablewriter.go, line 222 at r15](https://reviewable.io/reviews/cockroachdb/cockroach/69936#-Mkbwwm_8R5Zst_PFCGI:-MkcLmczAhRyULaiZgBh:b-8mg5qb) ([raw file](https://github.com/cockroachdb/cockroach/blob/f23ffbefa78941f7b86d133f6bd6fbaa28121b7e/pkg/sql/tablewriter.go#L222)):*
> Instead of pessimistically inhibiting the auto-commit, have you considered whether it's feasible to reach back in to the lease machinery and call MaybeUpdateDeadline, and then allow the auto-commit regardless of the outcome? If feasible, that'd be more directly encode what we really want.

Are there scenarios where the violation of the existing boundaries is worth keeping this optimization?  The state machinery that manages the leasing logic is encapsulated at a higher layer and I think ideally we don't want to deal with that logic in the tableWriter directly, since it would break encapsulation.

**Comment by rafiss** [comment]
@fqazi @ajwerner friendly ping - does this still need to be backported?
