### PR TITLE
loqrecovery: fix Recv error being swallowed by forwardReplicaFilter

### LINKED ISSUE #162609: cli: TestHalfOnlineLossOfQuorumRecovery failed
cli.TestHalfOnlineLossOfQuorumRecovery [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Ci_TestsAwsLinuxArm64_UnitTests/21077416?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Ci_TestsAwsLinuxArm64_UnitTests/21077416?buildTab=artifacts#/) on master @ [47eae13ca072761c1708116e66776ca01f8d96f9](https://github.com/cockroachdb/cockroach/commits/47eae13ca072761c1708116e66776ca01f8d96f9):

```
=== RUN   TestHalfOnlineLossOfQuorumRecovery
    test_log_scope.go:172: test logs captured to: /artifacts/tmp/_tmp/6c689cc523db9d8596d03c0a6ef213e4/logTestHalfOnlineLossOfQuorumRecovery3776359264
    test_log_scope.go:82: use -show-logs to present logs inline
[debug recover make-plan --confirm=y --certs-dir=test_certs --host=127.0.0.1:36465 --cluster-name=TestCluster-uhPiKE1Ptl --plan=/artifacts/tmp/_tmp/6c689cc523db9d8596d03c0a6ef213e4/TestHalfOnlineLossOfQuorumRecovery3559714859/recovery-plan.json]
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x42ee854]

goroutine 17444 [running]:
github.com/cockroachdb/cockroach/pkg/kv/kvserver/loqrecovery.Server.ServeClusterReplicas.serveClusterReplicasParallelFn.func3(0x3, {0x7453ed0, 0x4009352bf8})
	pkg/kv/kvserver/loqrecovery/server.go:268 +0x1b4
github.com/cockroachdb/cockroach/pkg/kv/kvserver/loqrecovery.visitNodeWithRetry({0x7397aa8, _}, _, {_, _, _, _, _, _, _, ...}, ...)
	pkg/kv/kvserver/loqrecovery/server.go:786 +0x1e8
github.com/cockroachdb/cockroach/pkg/kv/kvserver/loqrecovery.NewServer.makeVisitAvailableNodesInParallel.func1.3()
	pkg/kv/kvserver/loqrecovery/server.go:752 +0x70
golang.org/x/sync/errgroup.(*Group).Go.func1()
	external/org_golang_x_sync/errgroup/errgroup.go:93 +0x4c
created by golang.org/x/sync/errgroup.(*Group).Go in goroutine 17425
	external/org_golang_x_sync/errgroup/errgroup.go:78 +0x90
```
<details><summary>Help</summary>
<p>

See also: [How To Investigate a Go Test Failure \(internal\)](https://cockroachlabs.atlassian.net/l/c/HgfXfJgM)
</p>
</details>
/cc @cockroachdb/kv-triage @cockroachdb/server
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*TestHalfOnlineLossOfQuorumRecovery.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/bazci/githubpost/issues)

</sub>

Jira issue: CRDB-59556

### PR DESCRIPTION
**Pull request by suj-krishnan**
- When `inStream.Recv()` returned a non-EOF error during fan-out replica collection, the error was passed to `forwardReplicaFilter` (via the overwrite `err = forwardReplicaFilter(r)`). Since `r` is `nil` on `Recv` error, the filter would return `nil`, silently discarding the original error. This caused the code to fall through to `r.ReplicaInfo` access, panicking on the `nil` response. The fix guards the filter call with `err == nil` so that `Recv` errors propagate to the retry logic unchanged. 
- [Claude's analysis](https://github.com/cockroachdb/cockroach/issues/162609#issuecomment-3988899504)
- **Note:**  This bug only manifests when `forwardReplicaFilter` is set, which only happens via the `TestingKnobs` so it can't trigger in production (where `forwardReplicaFilter` is nil and the original `err` from `Recv()`flows through correctly). 
- The fix also renames the testing knob `ForwardReplicaFilter` to `MaybeInjectError` to be consistent with its existing usage ([slack discussion](https://cockroachlabs.slack.com/archives/C0KB9Q03D/p1772613557241359?thread_ts=1772598003.618319&cid=C0KB9Q03D)). 

Fixes: #162609
Epic: none

Release note: None

### CODE REVIEW

File: pkg/kv/kvserver/loqrecovery/server.go [hunk 1]
```diff
@@ -244,7 +244,7 @@ func serveClusterReplicasParallelFn(
 			if err == io.EOF {
 				break
 			}
-			if forwardReplicaFilter != nil {
+			if err == nil && forwardReplicaFilter != nil {
```
Comment (cthumuluru-crdb) [inline pkg/kv/kvserver/loqrecovery/server.go]: `inStream.Recv()` is throwing an error that is non-EOF. In case of EOF we are breaking the loop. When the test knob is available we all the test knob with the response we get and in this particular case since the response is nil, testknob is a no-op.

I wonder if we should skip the testknob in case of an error since the response is going to be nil? Otherwise I feel like the testknob implementation is sort of broken.

Comment (suj-krishnan) [reply pkg/kv/kvserver/loqrecovery/server.go]: AFAIU, this testknob [ForwardReplicaFilter](https://github.com/cockroachdb/cockroach/blob/1dadaff8d7f77fdaa8b1a599161bd4bb8cf5ad5a/pkg/cli/debug_recover_loss_of_quorum_test.go#L492) is used to artificially inject failure - it requires a valid response from `Recv()` as its input argument and induces the failure if the response is non-nil. When `err` from Recv() is non-nil, usually`response` would be `nil`, and the testknob will be no-op anyway. So in this case, I don't see  much value in calling it when there is an error.

Comment (cthumuluru-crdb) [reply pkg/kv/kvserver/loqrecovery/server.go]: Aside from that one implementation, the testing knob’s specification doesn’t clearly state that its sole purpose is to inject failures. I wish the spec were more explicit about that, because then the proposal to skip invoking the knob in case of an error would make perfect sense.

Comment (suj-krishnan) [reply pkg/kv/kvserver/loqrecovery/server.go]: I get your point. The two existing usages of `ForwardReplicaFilter` (one more usage [here](https://github.com/cockroachdb/cockroach/blob/36c5e80271f7bddd469f9648be26ea8ffdbcd3c1/pkg/kv/kvserver/loqrecovery/server_integration_test.go#L147)) both inject failures. Even if the knob's purpose cannot be inferred just based on this, the fact that the filter takes the response as input strongly _suggests_ that it is intended to be called when there is a non-nil response (which almost always translates to no err). But I agree that a clear description regarding the usage of the filter would have helped here.  I guess we can defer this question to the kv team (?) or modify the fix to avoid the variable shadowing but call the filter in either case.

**Review by tbg — CHANGES_REQUESTED** [review]
The code change is good, but a merge commit slipped in. Please clean up the history before merging.

Also, and this is a nit (i.e. no need to do this now, it's just extra work, but for next time): if you had done the rename first (in a separate commit) and then the fix, it would be easier to review. Again, not worth retrofitting, just a suggestion for next time.

I'll approve but add a do-not-merge label to make sure the commit history gets cleaned up. You can remove that label when that is addressed and merge.

Thanks for the fix!

**Review by tbg — APPROVED** [review]
Wrong button.
Also I'm not sure the `do-not-merge` label still blocks merges 😄 just fix the commit history before merging regardless.

**Comment by suj-krishnan** [comment]
TFTR @cthumuluru-crdb
