### PR TITLE
kvserver: fix TestTransferRaftLeadership flake

### LINKED ISSUE #99213: kvserver: TestTransferRaftLeadership flakes
The test timed out with:

```
Failed
=== RUN   TestTransferRaftLeadership
    test_log_scope.go:161: test logs captured to: /artifacts/tmp/_tmp/09357cecfdbbab5926b4b055936a9b62/logTestTransferRaftLeadership739910387
    test_log_scope.go:79: use -show-logs to present logs inline
    client_raft_test.go:4118: condition failed to evaluate within 45s: expected raft leader be 2; got 1
    panic.go:522: -- test log scope end --
--- FAIL: TestTransferRaftLeadership (46.39s)
```

Happened 2 times over last 1000 runs in CI.

Jira issue: CRDB-25762

### PR DESCRIPTION
**Pull request by pav-kv**
After adding voters (`tc.AddVotersOrFatal`), the test proceeds to commit a lease transfer command. The leader then attempts to transfer leadership to the new leaseholder, by stepping a `MsgTransferLeader` into its `raft.RawNode` instance, which sends a *single* `MsgTimeoutNow` to that node which triggers it to campaign. Subsequent `MsgTransferLeader` messages are ignored because the leader transfer is considered in progress.

The test expects that node 2 campaigns, but the flake happens when it doesn't because it is `!r.promotable()`. It does so in a rare case when node 2 is still a learner by the time it gets this message (probably it hasn't applied the config change yet).

Normally, the current leader would reset the transfer if it doesn't complete within the election timeout (see `raft.tickHeartbeat`), and retry it with the next `MsgTransferLeader` message. This test, however, sets a high election timeout to disable Raft's election for the purpose of this test. So the retry never happens.

This commit fixes the flake by waiting until node 2 becomes `VOTER_FULL`, so that it doesn't reject the leadership transfer.

> 18060 runs so far, 0 failures, over 1h32m35s

Fixes #99213
Epic: none
Release note: none

### CODE REVIEW

File: pkg/kv/kvserver/client_raft_test.go [hunk 1]
```diff
@@ -4057,61 +4057,52 @@ func TestTransferRaftLeadership(t *testing.T) {
...
-		t.Fatalf("expect get nil, actual get %v ", pErr)
-	}
+	_, pErr := kv.SendWrappedWith(ctx, store0, kvpb.Header{RangeID: repl0.RangeID}, getArgs(key))
+	require.NoError(t, pErr.GoError())
 
-	status := repl0.RaftStatus()
-	if status == nil || status.Lead != uint64(rd0.ReplicaID) {
-		t.Fatalf("raft leader should be %d, but got status %+v", rd0.ReplicaID, status)
-	}
+	require.Equal(t, uint64(rd0.ReplicaID), repl0.RaftStatus().Lead)
```
Comment (tbg) [inline pkg/kv/kvserver/client_raft_test.go:4099]: `RaftStatus()` can - in principle - return `nil`, it would be better if this didn't crash the entire test shard.

**Review by tbg — APPROVED** [review]

File: pkg/kv/kvserver/client_raft_test.go (hunk 1 above)
Comment (pavelkalinnikov) [reply pkg/kv/kvserver/client_raft_test.go]: Fixed.

**Comment by pavelkalinnikov** [comment]
bors r=tbg

**Comment by knz** [comment]
Merging as per https://github.com/cockroachdb/cockroach/pull/99929

**Comment by yuzefovich** [comment]
Do we want to backport this to 23.1? I saw a failure [here](https://teamcity.cockroachdb.com/viewLog.html?buildId=11206074&buildTypeId=Cockroach_BazelEssentialCi).

**Comment by yuzefovich** [comment]
I'll just open up a backport and let people decide.

blathers backport 23.1
