### PR TITLE
sql/schemachanger: add back TXN_DROPPED, stop using OFFLINE

### LINKED ISSUE #77148: rel: add element nonexistence clause support
This will allow us to define schema changer dependency rules which are conditional on an element _not_ being present, which isn't possible right now. 

There is already a need for this, we want certain rules to apply on a column only if a table is being dropped. In that case there will be a `Table` element, and its target will be `ABSENT`. However in an ALTER TABLE there will be no such `Table` element.

Epic: CRDB-13602

Jira issue: CRDB-13433

### LINKED ISSUE #86626: sql/schemachanger: ensure dropping descriptors are not taken OFFLINE
**Describe the problem**

In https://github.com/cockroachdb/cockroach/pull/83915 we moved descriptors to transition through `OFFLINE` before being dropped. This was done for two reasons:
1) To enable us to drop descriptors in the same transaction where something which might fail occurs
2) To fix a bug in the existing `TXN_DROPPED` state whereby virtual tables would see descriptors which should not be seen.

Note that `TXN_DROPPED` did not preclude (1). The problem with `OFFLINE` is that it is not backwards compatible, and the removal of `TXN_DROPPED` is not forwards compatible. 

Jira issue: CRDB-18846

### LINKED ISSUE #86691: sql/schemachanger: Mixed version drop operations can fail due to OFFLINE state
When dropping objects in a mixed version state, we encountered failures related to the offline state: 

`failed to validate TestLogic_system_privileges_mixed_TestLogic_system_privileges_mixed_DROP DATABASE test CASCADE_1 with error invalid execution plan: final status is 15 instead of ABSENT at index 5 for adding Database:{DescID: 104}`

The previous version of cockroach at 22.1 cannot plan for this state, which could lead to issues. This can be reproduced by generating a corpus on logictest --declartaive-corpus option on 22.1 and using it on 22.1 via cockroach debug.

Jira issue: CRDB-18872

### PR DESCRIPTION
**Pull request by ajwerner**
The first two commits enable synthetic descriptors to be used during transaction
execution to influence the virtual tables.

We added the `OFFLINE` and performed write operations during drops to move the
descriptor into that state in order to deal with the fact that synthetically
dropped descriptors would not appear so in virtual tables. Fortunately, this
shortcoming has been rectified. We now revive the TXN_DROPPED state. This
proves to be important because the `OFFLINE` state is not backwards compatible,
and the `TXN_DROPPED` state is. Ideally we'd find a way to move the descriptors
straight to `DROPPED` in the pre-commit case for all the cases we today support,
but doing that would require an overhaul of the dependency rules which, at this
point in the cycle, feels risky.

Fixes https://github.com/cockroachdb/cockroach/issues/86626
Fixes #77148
Fixes #86691

Release justification: Fixes a release-blocking backwards incompatibility.

Release note: None

### CODE REVIEW

**Comment by ajwerner** [comment]
This turns out to be insufficient; we need to make it such that the bulk of the work in the drop cases does happen during pre-commit. Otherwise, we're stuck with incompatibilities.

**Comment by Xiang-Gu** [comment]
I fixed a few build errors,  rebase on Master, and ran `--rewrite` on affected tests in the above push.

CI now reports test failures; we will need to look into them next.

File: pkg/sql/schemachanger/scplan/internal/rules/helpers.go [hunk 1]
```diff
@@ -465,3 +465,20 @@ func registerDepRuleForDrop(
...
+var descriptorIsNotBeingDropped = screl.Schema.DefNotJoin1(
+	"descriptorIsNotBeingDropped", "element", func(
+		element rel.Var,
+	) rel.Clauses {
+		descriptor := mkNodeVars("descriptor")
+		return rel.Clauses{
+			descriptor.typeFilter(IsDescriptor),
+			descriptor.joinTarget(),
+			joinOnDescIDUntyped(descriptor.el, element, "id"),
+			descriptor.targetStatus(scpb.ToAbsent),
```
Comment (Xiang-Gu) [inline pkg/sql/schemachanger/scplan/internal/rules/helpers.go:481]: should this line be `descriptor.targetStatus(scpb.ToPublic)`?

File: pkg/sql/schemachanger/scplan/internal/rules/dep_drop_object.go [hunk 2]
```diff
@@ -26,8 +26,36 @@ import (
...
+	registerDepRule(
+		"descriptor txn_drop before descriptor drop",
+		scgraph.PreviousStagePrecedence,
+		"descriptor", "dependent",
+		func(from, to nodeVars) rel.Clauses {
+			return rel.Clauses{
+				from.typeFilter(IsDescriptor),
+				from.el.AttrEqVar(screl.DescID, "_"),
+				from.el.AttrEqVar(rel.Self, to.el),
+				to.el.AttrEqVar(rel.Self, to.el),
```
Comment (Xiang-Gu) [inline pkg/sql/schemachanger/scplan/internal/rules/dep_drop_object.go:41]: Isn't this line always true and hence redundant?

File: pkg/sql/schemachanger/scplan/internal/rules/dep_drop_object.go [hunk 3]
```diff
@@ -26,8 +26,36 @@ import (
 //   reaches the ABSENT state, but afterwards in the stage, so as to not
 //   interfere with the event logging op which is tied to the descriptor element
 //   removal.
+
 func init() {
 
+	registerDepRule(
+		"descriptor txn_drop before descriptor drop",
+		scgraph.PreviousStagePrecedence,
+		"descriptor", "dependent",
```
Comment (Xiang-Gu) [inline pkg/sql/schemachanger/scplan/internal/rules/dep_drop_object.go:35]: If this rule is about making sure one descriptor reached `TXN_DROPPED` before reaching `DROPPED` in a previous stage, then we probably should change the name of the second variable `dependent` to, maybe, `descriptor_self`.

File: pkg/sql/schemachanger/scplan/internal/rules/dep_two_version.go [hunk 4]
```diff
@@ -0,0 +1,171 @@
...
+// in separate transactions.
+func init() {
+	type depElement struct {
+		name string
+		el   scpb.Element
+	}
+	type statusFunc = func(
+		from nodeVars, fromStatus scpb.Status, to nodeVars, toStatus scpb.Status,
+	) rel.Clause
+	addRules := func(c depElement, targetStatus scpb.TargetStatus, sf statusFunc) {
```
Comment (Xiang-Gu) [inline pkg/sql/schemachanger/scplan/internal/rules/dep_two_version.go:68]: it seems `sf statusFunc` is not used. Did I miss something?

File: pkg/sql/schemachanger/scplan/internal/scgraph/edge.go [hunk 5]
```diff
@@ -102,6 +95,10 @@ const (
 	// be reached before the destination (to), and _must_ do so in a previous
 	// stage.
 	PreviousStagePrecedence
+
+	// PreviousTransactionPrecedence is like PreviousStagePrecedence but does
+	// not allow the transition to occur if the current phase is not PostCommit.
```
Comment (Xiang-Gu) [inline pkg/sql/schemachanger/scplan/internal/scgraph/edge.go:100]: Can you be elobarate a bit more on the comment? Does it mean`from` must be reached before `to` in a previous stage, and both stages must be in PostCommit phase? If so, what do you think of the name `PreviousStageInPostCommitPrecendence`?

File: pkg/sql/schemachanger/scplan/internal/rules/dep_drop_object.go (hunk 3 above)
Comment (ajwerner) [reply pkg/sql/schemachanger/scplan/internal/rules/dep_drop_object.go]: Good catch, fixed

File: pkg/sql/schemachanger/scplan/internal/rules/dep_drop_object.go (hunk 2 above)
Comment (ajwerner) [reply pkg/sql/schemachanger/scplan/internal/rules/dep_drop_object.go]: Yes, removed

File: pkg/sql/schemachanger/scplan/internal/rules/helpers.go (hunk 1 above)
Comment (ajwerner) [reply pkg/sql/schemachanger/scplan/internal/rules/helpers.go:459]: No, we want this rule to unify if we *are* dropping the descriptor. The `NotJoin` implies negation where it is used if everything inside the rule unifies.

**Review by ajwerner — COMMENTED** [review]
Thanks for taking a look and fixing the issues. The validation things are interesting. I'll get to the bottom of them one way or another. I think I addressed the basic comments, but did it on the old version of the branch. I'll find and add back your changes.

File: pkg/sql/schemachanger/scdeps/sctestdeps/test_deps.go [hunk 6]
```diff
@@ -560,9 +560,18 @@ func (s *TestState) MustReadDescriptor(ctx context.Context, id descpb.ID) catalo
 	return desc
 }
 
+// AddSyntheticDescriptor is part of the scexec.Catalog interface.
+func (s *TestState) AddSyntheticDescriptor(desc catalog.MutableDescriptor) {
+	s.LogSideEffectf("added synthetic descriptor: %v", desc)
```
Comment (postamar) [inline pkg/sql/schemachanger/scdeps/sctestdeps/test_deps.go:565]: Can we instead print the yaml diff between the synthetic descriptor and the existing immutable descriptor if it exists?

File: pkg/sql/schemachanger/scexec/scmutationexec/dependencies.go [hunk 7]
```diff
@@ -117,4 +117,6 @@ type MutationVisitorStateUpdater interface {
 
 	// RefreshStats refresh stats for a given descriptor.
 	RefreshStats(id descpb.ID)
+	MarkDescriptorSynthetic(id descpb.ID)
+	//	MarkDescriptorSynthetic(id descpb.ID)
```
Comment (postamar) [inline pkg/sql/schemachanger/scexec/scmutationexec/dependencies.go:121]: detritus

File: pkg/sql/schemachanger/scplan/internal/scstage/build.go [hunk 8]
```diff
@@ -322,7 +322,7 @@ func (sb stageBuilder) isOutgoingOpEdgeAllowed(e *scgraph.OpEdge) bool {
 	if e.Type() != sb.opType {
 		return false
 	}
-	if !e.IsPhaseSatisfied(sb.bs.phase) {
+	if !e.IsPhaseSatisfied(sb.bs.phase) && !sb.bc.g.IsNoOp(e) {
```
Comment (postamar) [inline pkg/sql/schemachanger/scplan/internal/scstage/build.go]: Nice. By the way, you probably should remove `hasOpEdgeWithOps` and the logic around it in this PR. Search for `// TODO(postamar): uphold the 2-version invariant using dep rules instead.`

File: pkg/sql/schemachanger/rel/schema_rules.go [hunk 9]
```diff
@@ -87,19 +100,29 @@ var (
 	clausesType = reflect.TypeOf((*Clauses)(nil)).Elem()
 )
 
+func makeRandomVars(n int) (ret []Var) {
+	ret = make([]Var, n)
+	for i := range ret {
+		ret[i] = Var(hex.EncodeToString(uuid.MakeV4().GetBytes()))
```
Comment (postamar) [inline pkg/sql/schemachanger/rel/schema_rules.go:124]: This is going to hurt legibility when debugging. Can't we instead use a reserved prefix followed by a counter? You probably can assert that this reserved prefix isn't used in vars outside of rel.

File: pkg/sql/schemachanger/rel/query_build.go [hunk 10]
```diff
@@ -110,6 +121,16 @@ func (p *queryBuilder) processClause(t Clause) {
...
+	case ruleInvocation:
+		if !t.rule.isNotJoin {
+			panic(errors.AssertionFailedf("rule invocations which aren't not-joins" +
+				" should have been flattened away"))
+		}
+		p.processNotJoin(t)
+	// if we have a not-join, then we need to find the slots for the inputs
+	// and we have to build the sub-query, which is a whole new query, and
+	// we have to then figure out its depth. In general, its depth should be
+	// the current join depth, so the current
```
Comment (postamar) [inline pkg/sql/schemachanger/rel/query_build.go:133]: incomplete comment

File: pkg/sql/schemachanger/rel/query_lang_clauses.go [hunk 11]
```diff
@@ -38,7 +38,9 @@ func expanded(c Clauses) Clauses {
 			case and:
 				return true
 			case ruleInvocation:
-				return !cl.rule.isNotJoin
+				if !cl.rule.isNotJoin {
+					return true
+				}
```
Comment (postamar) [inline pkg/sql/schemachanger/rel/query_lang_clauses.go:43]: this should instead be in the penultimate commit

File: pkg/sql/schemachanger/scop/ops.go [hunk 12]
```diff
@@ -30,6 +30,13 @@ const (
 	// ValidationType represents constraint and unique index validations
 	// performed using internal queries.
 	ValidationType
+
+	maxType
```
Comment (postamar) [inline pkg/sql/schemachanger/scop/ops.go:34]: This isn't a max, though, it's the max + 1...

In these cases where the enum is unlikely to change in the future it's better to have `const maxType = ValidationType` instead. The alternative (for enums which often have values added to them) is to define a `$<whateverEnumType>ValuesCount` along with `const max$<whateverEnumType> = $<whateverEnumType>ValuesCount - 1`.

File: pkg/sql/schemachanger/scplan/internal/rules/helpers.go [hunk 13]
```diff
@@ -465,3 +469,20 @@ func registerDepRuleForDrop(
...
+		}
+	},
+)
```
Comment (postamar) [inline pkg/sql/schemachanger/scplan/internal/rules/helpers.go:488]: Very nice.

File: pkg/sql/schemachanger/scplan/internal/scgraph/edge.go (hunk 5 above)
Comment (postamar) [reply pkg/sql/schemachanger/scplan/internal/scgraph/edge.go:100]: `does not allow the transition to occur unless the current phase is at least PostCommitPhase, because StatementPhase and PreCommitPhase are special in that they take place in the same transaction`?

File: pkg/sql/schemachanger/scplan/internal/rules/dep_two_version.go [hunk 14]
```diff
@@ -0,0 +1,163 @@
...
+						from, to, el, targetStatus, t, statusMap[t.From()],
+					)
+				},
+			)
+			return nil
+		}); err != nil {
+			panic(err)
+		}
+	}
+	_ = screl.ForEachElementType(func(el scpb.Element) error {
```
Comment (postamar) [inline pkg/sql/schemachanger/scplan/internal/rules/dep_two_version.go:106]: We already have a function `forEachElement` in `rules` just like this one.

File: pkg/sql/schemachanger/scplan/internal/rules/dep_two_version.go [hunk 15]
```diff
@@ -0,0 +1,163 @@
...
+		if opgen.HasTransient(el) {
+			addRules(el, scpb.Transient)
+		}
+		addRules(el, scpb.ToAbsent) // every element has ToAbsent
+		return nil
+	})
+
+}
+
+// notJoinOnNodeWithStatusIn is a cache to memoize getNotJoinOnNodeWithStatusIn. a not-join rule which will
```
Comment (postamar) [inline pkg/sql/schemachanger/scplan/internal/rules/dep_two_version.go:122]: incomplete comment

File: pkg/sql/schemachanger/scplan/internal/scgraph/edge.go [hunk 16]
```diff
@@ -67,11 +65,6 @@ func (oe *OpEdge) Type() scop.Type {
 	return oe.typ
 }
 
-// IsPhaseSatisfied returns true iff the operations can run in the given phase.
-func (oe *OpEdge) IsPhaseSatisfied(phase scop.Phase) bool {
-	return phase >= oe.minPhase
-}
```
Comment (postamar) [inline pkg/sql/schemachanger/scplan/internal/scgraph/edge.go:73]: Good riddance.

File: pkg/sql/schemachanger/scplan/internal/scstage/build.go [hunk 17]
```diff
@@ -361,7 +358,7 @@ func (sb stageBuilder) nextTargetState(t currentTargetState) currentTargetState
 		} else {
 			next.hasOpEdgeWithOps = true
 		}
-	}
+	}*/
```
Comment (postamar) [inline pkg/sql/schemachanger/scplan/internal/scstage/build.go:361]: Just get rid of this, as suggested in a previous comment, along with `hasOpEdgeWithOps`.

File: pkg/sql/schemachanger/scplan/internal/scstage/build.go [hunk 18]
```diff
@@ -373,8 +370,8 @@ func (sb stageBuilder) nextTargetState(t currentTargetState) currentTargetState
 // scheduled.
 func (sb stageBuilder) hasUnmetInboundDeps(n *screl.Node) (ret bool) {
 	_ = sb.bc.g.ForEachDepEdgeTo(n, func(de *scgraph.DepEdge) error {
-		if sb.isUnmetInboundDep(de) {
-			ret = true
+		ret = sb.isUnmetInboundDep(de)
+		if ret {
```
Comment (postamar) [inline pkg/sql/schemachanger/scplan/internal/scstage/build.go:374]: nit: is this really more readable?

File: pkg/sql/schemachanger/scplan/internal/scstage/build.go [hunk 19]
```diff
@@ -386,6 +383,13 @@ func (sb *stageBuilder) isUnmetInboundDep(de *scgraph.DepEdge) bool {
 	_, fromIsFulfilled := sb.bs.fulfilled[de.From()]
 	_, fromIsCandidate := sb.fulfilling[de.From()]
 	switch de.Kind() {
+
+	case scgraph.PreviousTransactionPrecedence:
+		return !fromIsFulfilled ||
+			(sb.bs.phase <= scop.PreCommitPhase &&
+				// If it has been fulfilled implicitly because it's the initial
+				// status, then it doesn't matter the current phase, let it go.
```
Comment (postamar) [inline pkg/sql/schemachanger/scplan/internal/scstage/build.go:391]: `then the current phase doesn't matter`?

**Review by postamar — COMMENTED** [review]
This is coming along nicely!

**Review by postamar — APPROVED** [review]
My comments are just nits, so LGTM.

**Review by ajwerner — COMMENTED** [review]
I took your changes and addressed the comments.

File: pkg/sql/schemachanger/scop/ops.go (hunk 12 above)
Comment (ajwerner) [reply pkg/sql/schemachanger/scop/ops.go:34]: meh I fixed the max definition

File: pkg/sql/schemachanger/rel/query_lang_clauses.go (hunk 11 above)
Comment (ajwerner) [reply pkg/sql/schemachanger/rel/query_lang_clauses.go:43]: Fixed.

**Comment by postamar** [comment]
CI is failing due to a compilation error:
`pkg/sql/schemachanger/rel/query_build.go:323:3: unnecessary assignment to the blank identifier (S1005)`

Let's 🚢 🇮🇹. My very minor concern about the var generator can wait another day.

**Comment by ajwerner** [comment]
TFTR!

bors r=postamar
