### PR TITLE
cli: fix node status --decommission

### LINKED ISSUE #28620: cli: `node status --decommission` mixes up output
On current master 5b184df62c5b21d82c2b6f03623ebd4ec5f92629.

Note the `is_draining` field, which appears to be showing a replica count (?).
Reminds me of https://github.com/cockroachdb/cockroach/pull/27808 which fixed something similar on release-2.0, though the assumption was that the same bug had been taken care of in master.

While this is fixed, we should also add a cli test which evidently doesn't exist today.

@petermattis you just touched this, but feel free to kick it into the cli team.

```
$ ./cockroach node status --insecure --decommission
  id |          address          |                    build                     |            started_at            |            updated_at            | is_live | gossiped_replicas | is_decommissioning | is_draining
+----+---------------------------+----------------------------------------------+----------------------------------+----------------------------------+---------+-------------------+--------------------+-------------+
   1 | toblerone.fritz.box:26257 | v2.1.0-alpha.20180702-1566-g5b184df62c-dirty | 2018-08-15 11:08:32.646778+00:00 | 2018-08-15 11:10:07.199025+00:00 |    true |       false       |              false |     22
   2 | toblerone.fritz.box:26259 | v2.1.0-alpha.20180702-1566-g5b184df62c-dirty | 2018-08-15 11:09:01.224461+00:00 | 2018-08-15 11:10:04.24526+00:00  |    true |       false       |              false |     22
   3 | toblerone.fritz.box:26261 | v2.1.0-alpha.20180702-1566-g5b184df62c-dirty | 2018-08-15 11:10:06.092988+00:00 | 2018-08-15 11:10:06.142856+00:00 |    true |       false       |              false |      0
(3 rows)
```

Same with `--all`:

```
./cockroach node status --insecure --all
  id |          address          |                    build                     |            started_at            |            updated_at            | is_live | replicas_leaders | replicas_leaseholders | ranges | ranges_unavailable | ranges_underreplicated | live_bytes | key_bytes | value_bytes | intent_bytes | system_bytes | gossiped_replicas | is_decommissioning | is_draining
+----+---------------------------+----------------------------------------------+----------------------------------+----------------------------------+---------+------------------+-----------------------+--------+--------------------+------------------------+------------+-----------+-------------+--------------+--------------+-------------------+--------------------+-------------+
   1 | toblerone.fritz.box:26257 | v2.1.0-alpha.20180702-1566-g5b184df62c-dirty | 2018-08-15 11:08:32.646778+00:00 | 2018-08-15 11:12:44.703472+00:00 |    true |               13 |                    12 |     22 |                  0 |                      0 |    1547475 |     41825 |     1514268 |            0 |         9087 |             false |              false |     22
   2 | toblerone.fritz.box:26259 | v2.1.0-alpha.20180702-1566-g5b184df62c-dirty | 2018-08-15 11:09:01.224461+00:00 | 2018-08-15 11:12:46.242897+00:00 |    true |                6 |                     6 |     22 |                  0 |                      0 |    1546965 |     62729 |     1492819 |            0 |         9087 |             false |              false |     22
   3 | toblerone.fritz.box:26261 | v2.1.0-alpha.20180702-1566-g5b184df62c-dirty | 2018-08-15 11:10:06.092988+00:00 | 2018-08-15 11:12:48.149831+00:00 |    true |                3 |                     3 |     22 |                  0 |                      0 |    1590941 |     62765 |     1536864 |            0 |         9087 |             false |              false |     22
```

### PR DESCRIPTION
**Pull request by petermattis**
Fix #28620

Release note: None

### CODE REVIEW

File: pkg/cli/cli_test.go [hunk 1]
```diff
@@ -2097,6 +2104,16 @@ func checkNodeStatus(t *testing.T, c cliTest, output string, start time.Time) {
 			t.Errorf("value for %s (%d) greater than max (%d)", tc.name, val, tc.maxval)
 		}
 	}
+
+	if nodeCtx.statusShowDecommission || nodeCtx.statusShowAll {
+		names := []string{"is_decommissioning", "is_draining"}
+		for i := range names {
+			idx := baseIdx + i
```
Comment (tschottdorf) [inline pkg/cli/cli_test.go]: nit: wouldn't it be cleaner to use the same `baseIdx++` pattern as before? Otherwise any code added below will have a wrong baseIdx.

**Review by tbg — APPROVED** [review]
Thanks for the prompt fix!

File: pkg/cli/cli_test.go (hunk 1 above)
Comment (petermattis) [reply pkg/cli/cli_test.go]: Done.

**Comment by petermattis** [comment]
bors r=tschottdorf
