### PR TITLE
roachtest: update libpq blocklist to ignore TestCopyInBinaryError

### LINKED ISSUE #57855: roachtest: lib/pq failed
[(roachtest).lib/pq failed](https://teamcity.cockroachdb.com/viewLog.html?buildId=2515122&tab=buildLog) on [master@960b4cfc54c8b78df56e62f07d7a07b986ceacff](https://github.com/cockroachdb/cockroach/commits/960b4cfc54c8b78df56e62f07d7a07b986ceacff):

```
The test failed on branch=master, cloud=gce:
test artifacts and logs in: /home/agent/work/.go/src/github.com/cockroachdb/cockroach/artifacts/lib/pq/run_1
	orm_helpers.go:228,orm_helpers.go:154,java_helpers.go:216,libpq.go:99,test_runner.go:760: 
		Tests run on Cockroach v21.1.0-alpha.1-289-g960b4cfc54
		Tests run against lib/pq v1.9.0
		122 Total Tests Run
		112 tests passed
		10 tests failed
		2 tests skipped
		0 tests ignored
		0 tests passed unexpectedly
		0 tests failed unexpectedly
		0 tests expected failed but skipped
		25 tests expected failed but not run
		---
		For a full summary look at the lib/pq artifacts 
		
		An updated blocklist (libPQBlocklist21_1) is available in the artifacts' lib/pq log

```

<details><summary>More</summary><p>

Artifacts: [/lib/pq](https://teamcity.cockroachdb.com/viewLog.html?buildId=2515122&tab=artifacts#/lib/pq)
Related:
- #56486 roachtest: lib/pq failed  [C-test-failure](https://api.github.com/repos/cockroachdb/cockroach/labels/C-test-failure) [O-roachtest](https://api.github.com/repos/cockroachdb/cockroach/labels/O-roachtest) [O-robot](https://api.github.com/repos/cockroachdb/cockroach/labels/O-robot) [branch-release-20.2](https://api.github.com/repos/cockroachdb/cockroach/labels/branch-release-20.2)

- #54338 roachtest: lib/pq failed  [C-test-failure](https://api.github.com/repos/cockroachdb/cockroach/labels/C-test-failure) [O-roachtest](https://api.github.com/repos/cockroachdb/cockroach/labels/O-roachtest) [O-robot](https://api.github.com/repos/cockroachdb/cockroach/labels/O-robot) [branch-release-20.1](https://api.github.com/repos/cockroachdb/cockroach/labels/branch-release-20.1)

[See this test on roachdash](https://roachdash.crdb.dev/?filter=status%3Aopen+t%3A.%2Alib%2Fpq.%2A&sort=title&restgroup=false&display=lastcommented+project)
<sub>powered by [pkg/cmd/internal/issues](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)</sub></p></details>

### PR DESCRIPTION
**Pull request by RichardJCai**
roachtest: update libpq blocklist to ignore TestCopyInBinaryError

TestCopyInBinary's behaviour was incorrect in the test since we were not receiving an expected error (`pq: only text format supported for COPY`). 
Furthermore the test would sporadically panic causing the following tests to fail.

Release note: None

Resolves #57855

### CODE REVIEW

**Comment by RichardJCai** [comment]
Gonna need to backport this all the way to 20.1 I think.

**Review by rafiss — CHANGES_REQUESTED** [review]
i think we need a different approach -- the ignore list still runs the test but ignores the result. so we need a way to skip entirely

**Review by RichardJCai — COMMENTED** [review]
Updated to ignore by generating an "allow list".

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/63238#-:-MXisqpUCM2ZHVONDDIv:b-jf5n3s)* status: :shipit: complete! 0 of 0 LGTMs obtained

**Comment by RichardJCai** [comment]
Note that now the ignored tests are not run at all instead of having their results ignored.

File: pkg/cmd/roachtest/libpq.go [hunk 1]
```diff
@@ -81,24 +82,52 @@ func registerLibPQ(r *testRegistry) {
...
+			t.Fatal(err)
+		}
+
+		// Convert the output of go test -list into an list.
+		tests := strings.Fields(string(buf))
+		var allowedTests []string
+
+		// The last line of output from go test -list Test is something like
+		// "ok  	github.com/lib/pq	0.003s", we ignore this by slicing the last entry.
+		for _, testName := range tests[:len(tests)-1] {
```
Comment (rafiss) [inline pkg/cmd/roachtest/libpq.go:111]: just to be sure we don't miss anything, maybe we could loop over the whole slice, but then add a check like `if testName does not start with "Test"`

File: pkg/cmd/roachtest/libpq_blocklist.go [hunk 2]
```diff
@@ -176,7 +173,17 @@ var libPQIgnorelist21_1 = libPQIgnorelist20_2
...
+	"TestFormatTsBackend": "41690",
+	// TestTxOptions fails because it attempts to change isolation levels.
+	"TestTxOptions": "41690",
+	// TestCopyInBinaryError is expected to error with:
+	// pq: only text format supported for COPY, however no error is returned
+	// for CRDB.
+	"TestCopyInBinaryError": "63235",
+}
 
 var libPQIgnorelist19_2 = blocklist{
```
Comment (rafiss) [inline pkg/cmd/roachtest/libpq_blocklist.go:188]: the test names in the ignore list here start with pq. also, we maybe can just get rid of the the 19.2 stuff and change the min version of the test to 20.1

File: pkg/cmd/roachtest/libpq.go [hunk 3]
```diff
@@ -81,24 +82,52 @@ func registerLibPQ(r *testRegistry) {
...
+		blocklistName, expectedFailures, ignorelistName, ignoreList := libPQBlocklists.getLists(version)
 		if expectedFailures == nil {
 			t.Fatalf("No lib/pq blocklist defined for cockroach version %s", version)
 		}
 		c.l.Printf("Running cockroach version %s, using blocklist %s, using ignorelist %s", version, blocklistName, ignorelistName)
 
 		t.Status("running lib/pq test suite and collecting results")
 
+		// List all the tests that start with Test or Example.
+		testListRegex := `"(Test|Example)"`
```
Comment (rafiss) [inline pkg/cmd/roachtest/libpq.go:94]: technically if it's about what the string starts with, should it be `^(Test|Example)` ?

**Review by rafiss — CHANGES_REQUESTED** [review]
awesome -- just some minor cleanups

**Review by RichardJCai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/63238)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rafiss)

___
*[pkg/cmd/roachtest/libpq.go, line 94 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/63238#-MXisqGGU0Fwv_Pi7LqC-r1-94:-MY6Rk1J1Ys2tcPABkNn:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/1eb4ee2ece8b14d5714f092ca83b7c0e3f92601d/pkg/cmd/roachtest/libpq.go#L94)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

technically if it's about what the string starts with, should it be `^(Test|Example)` ?
</blockquote></details>

Done.
___
*[pkg/cmd/roachtest/libpq.go, line 111 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/63238#-MXisqGGU0Fwv_Pi7LqC-r1-111:-MY6RkQ31IiD5AHpFVPP:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/1eb4ee2ece8b14d5714f092ca83b7c0e3f92601d/pkg/cmd/roachtest/libpq.go#L111)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

just to be sure we don't miss anything, maybe we could loop over the whole slice, but then add a check like `if testName does not start with "Test"`
</blockquote></details>

Done.
___
*[pkg/cmd/roachtest/libpq_blocklist.go, line 188 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/63238#-MXhQKNzf9qHXdlNp_Wz-r1-188:-MY6RXHvDycbVVgWaxt8:bbnkggp) ([raw file](https://github.com/cockroachdb/cockroach/blob/1eb4ee2ece8b14d5714f092ca83b7c0e3f92601d/pkg/cmd/roachtest/libpq_blocklist.go#L188)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

the test names in the ignore list here start with pq. also, we maybe can just get rid of the the 19.2 stuff and change the min version of the test to 20.1
</blockquote></details>

Removed 19.2. The reason I had to remove the pq. here is that the name returned from the `go test -list` does not include pq. and we use that to determine whether we ignore the test or not.

**Review by rafiss — APPROVED** [review]
lgtm!!

> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/63238#-:-MYjp_yq7lMkBd_GgCVN:b-nzoorr)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rafiss)

**Comment by RichardJCai** [comment]
Thanks! 
bors r=rafiss
