### PR TITLE
 importccl: Correctly resolve column names when importing.

### LINKED ISSUE #45421: IMPORT INTO has problems with quoted identifiers
**Describe the problem**

I'm attempting to migrate some data over from an SQLite intermediary format and having trouble with `IMPORT INTO` tripping up over a column it says doesn't exist:

```
root@localhost:26257/cpsasurvey> IMPORT INTO "cpsasurvey"."gradedSurveys" ("id", "timestamp", "graderId", "responseId", "flags", "gradingTime", "scrollCount", "remoteJobId")
    CSV DATA ('http://localhost:9001/cpsasurvey.gradedSurveys.csv');
pq: verifying target columns: column "\"timestamp\"" does not exist
root@localhost:26257/cpsasurvey>
root@localhost:26257/cpsasurvey> show columns from "gradedSurveys";
  column_name | data_type | is_nullable | column_default | generation_expression |                                                                                                    indices                                                                                                    | is_hidden
+-------------+-----------+-------------+----------------+-----------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------+
  id          | STRING    |    false    | NULL           |                       | {pK_gradedSurveys,gradedSurveys_auto_index_fK_gradedSurveys_Graders_graderId,gradedSurveys_auto_index_fK_gradedSurveys_Responses_responseId,iX_gradedSurveys_responseId,iX_gradedSurveys_graderId_responseId} |   false
  timestamp   | INT8      |    false    | NULL           |                       | {}                                                                                                                                                                                                            |   false
  graderId    | STRING    |    false    | NULL           |                       | {gradedSurveys_auto_index_fK_gradedSurveys_Graders_graderId,iX_gradedSurveys_graderId_responseId}                                                                                                             |   false
  remoteJobId | STRING    |    true     | NULL           |                       | {}                                                                                                                                                                                                            |   false
  responseId  | STRING    |    false    | NULL           |                       | {gradedSurveys_auto_index_fK_gradedSurveys_Responses_responseId,iX_gradedSurveys_responseId,iX_gradedSurveys_graderId_responseId}                                                                             |   false
  flags       | INT8      |    false    | NULL           |                       | {}                                                                                                                                                                                                            |   false
  gradingTime | FLOAT8    |    false    | NULL           |                       | {}                                                                                                                                                                                                            |   false
  scrollCount | INT8      |    false    | NULL           |                       | {}                                                                                                                                                                                                            |   false
(8 rows)

Time: 21.412ms
```

Two thoughts:

* `"timestamp"` is being treated as a reserved keyword rather than as a column name, despite being quoted?
* it seems from the output that the literal `"` used to "special-case" the reserved keyword `timestamp` may be treated as part of the column name? (note the escaped `\"` within the outer quotes in the error message)

I altered the table to temporarily rename `timestamp` to `tstamp` and tried again, this time it threw an error on `"graderId"`, confirming the second point above:

```
root@localhost:26257/cpsasurvey> IMPORT INTO "cpsasurvey"."gradedSurveys" ("id", "tstamp", "graderId", "responseId", flags, "gradingTime", "scrollCount", "remoteJobId")
    CSV DATA ('http://localhost:9001/cpsasurvey.gradedSurveys.csv');
pq: verifying target columns: column "\"graderId\"" does not exist
```

I thought perhaps the bug was that columns were being treated as literal values (no quoting *and* no case-folding), and tried with `graderId` rather than `"graderId"` but the error confirmed that it's not the case: case-folding *is* performed but double-quoting is *not* accounted for:


```
root@localhost:26257/cpsasurvey> IMPORT INTO "cpsasurvey"."gradedSurveys" (id, tstamp, graderId, responseId, flags, gradingTime, scrollCount, remoteJobId)
    CSV DATA ('http://localhost:9001/cpsasurvey.gradedSurveys.csv');
pq: verifying target columns: column "graderid" does not exist
```

So the real problem is that the code is entirely unaware of the semantics of double quotes altogether.

(I have the explicit column names in the query as the order differs from the `.dump` output of `sqlite3`, but I believe it's a bug even if I didn't need to reorder the data, no? So long as `IMPORT INTO` has the option of taking column names, I believe it should respect the same naming rules and quoting formats as the rest of the SQL commands.)


**To Reproduce**

Started a new single-node cluster in insecure mode and created the following table:

```sql
CREATE TABLE "gradedSurveys" (
	id STRING NOT NULL,
	"timestamp" INT8 NOT NULL,
	"graderId" STRING NOT NULL,
	"remoteJobId" STRING NULL,
	"responseId" STRING NOT NULL,
	flags INT8 NOT NULL,
	"gradingTime" FLOAT8 NOT NULL,
	"scrollCount" INT8 NOT NULL,
	/*CONSTRAINT "pK_gradedSurveys" PRIMARY KEY (id ASC),
	CONSTRAINT "fK_gradedSurveys_Graders_graderId" FOREIGN KEY ("graderId") REFERENCES graders(id) ON DELETE CASCADE,
	CONSTRAINT "fK_gradedSurveys_Responses_responseId" FOREIGN KEY ("responseId") REFERENCES responses(id) ON DELETE CASCADE,
	INDEX "gradedSurveys_auto_index_fK_gradedSurveys_Graders_graderId" ("graderId" ASC),
	INDEX "gradedSurveys_auto_index_fK_gradedSurveys_Responses_responseId" ("responseId" ASC),
	INDEX "iX_gradedSurveys_responseId" ("responseId" ASC),
	UNIQUE INDEX "iX_gradedSurveys_graderId_responseId" ("graderId" ASC, "responseId" ASC),
	FAMILY "primary" (id, tstamp, "graderId", "remoteJobId", "responseId", flags, "gradingTime", "scrollCount")*/
);
```

then executed the import statement above at the cli. 

**Expected behavior**
The quoted column name should be used as-is and found.

**Additional data / screenshots**

**Environment:**
 - CockroachDB version: 19.2.4
 - Server OS: Windows 10 1909
 - Client app: `cockroach sql`

EDIT: note that there was no problem with the quoted identifiers for the database and table names.

### PR DESCRIPTION
**Pull request by miretskiy**
Fixes #45421

Previously, import processors used column names when
identifying which columns to import the data into.

This is problematic because column names might contain
special characters and need to be quoted. We thus would
fail to find a matching column in the table descriptor,
resulting in an error.

Instead of storing column names directly in the jobs
descriptor, resolve column name first, and then use
the resolved name.

Release justification: Bug fix.  This change is a low
risk bug fix.
Release notes (bug fix): Correctly handle columns named with
reserved keywords.

### CODE REVIEW

File: pkg/ccl/importccl/import_stmt_test.go [hunk 1]
```diff
@@ -2174,6 +2174,25 @@ func TestImportIntoCSV(t *testing.T) {
 		)
 	})
 
+	// Tests that we can import into the table even if the table has columns named with
+	// reserved keywords.
+	t.Run("cols-named-with-reserved-keywords", func(t *testing.T) {
+		sqlDB.Exec(t, `CREATE TABLE t ("select" INT PRIMARY KEY, "from" INT, "timestamp" STRING NOT NULL)`)
```
Comment (dt) [inline pkg/ccl/importccl/import_stmt_test.go]: i think one or two reserved words if probably fine but i do think we should have a case that requires quoting for special chars, case preservation, etc. e.g. replace timestamp with `Some c,o.l-'Name'`

File: pkg/ccl/importccl/import_stmt.go [hunk 2]
```diff
@@ -507,13 +507,13 @@ func importPlanHook(
 			var intoCols []string
 			var isTargetCol = make(map[string]bool)
 			for _, name := range importStmt.IntoCols {
-				var err error
-				if _, err = found.FindActiveColumnByName(name.String()); err != nil {
-					return errors.Wrap(err, "verifying target columns")
+				active, err := found.FindActiveColumnsByNames(tree.NameList{name})
+				if err != nil {
+					return errors.Wrapf(err, "verifying target columns: norm=%q str=%q", name.Normalize(), name.String())
```
Comment (dt) [inline pkg/ccl/importccl/import_stmt.go]: this error message might have been useful in debugging but from a user point of view is very cryptic. The expected case here is they specify something which isn't a column and the less noise we add to the "not found" error the better i think? i'd probably just leave it as it was.

**Comment by dt** [comment]
nit: commit message is also mangled and still references IDs.

**Review by dt — APPROVED** [review]
