### PR TITLE
server: Fix --advertise-port

### LINKED ISSUE #18932: ports defined in --join are ignored
Here is a log of a node that I'm trying to --join to the main node. All nodes on this cluster have a public-facing port `3000` (though internally run in docker on port `26257`).

Notice:
 - `--join=45.77.103.118:3000,45.76.95.210:3000` in args
 - `started gossip client to 45.77.103.118:3000`
 - `"transport: dial tcp 45.77.103.118:26257: i/o timeout"; Reconnecting to {45.77.103.118:26257 <nil>}`

It's gossiping correctly at port `3000`, but still trying to connect at default port `26257`. I'd expect that `--join=45.77.103.118:3000` would have effect on both.

```
I171002 06:48:03.534424 1 util/log/clog.go:1013  [config] file created at: 2017/10/02 06:48:03
I171002 06:48:03.534424 1 util/log/clog.go:1013  [config] running on machine: 1fa305e46744
I171002 06:48:03.534424 1 util/log/clog.go:1013  [config] binary: CockroachDB CCL v1.0.6 (linux amd64, built 2017/09/14 15:15:48, go1.8.3)
I171002 06:48:03.534424 1 util/log/clog.go:1013  [config] arguments: [cockroach start --locality=region=sg,datacenter=sg-a --cache=128MiB --insecure --advertise-host=45.76.188.73 --pid-file=/var/run/db.analytics.pid --store=attrs=ssd,path=/cockroach/cockroach-data --join=45.77.103.118:3000,45.76.95.210:3000]
I171002 06:48:03.534424 1 util/log/clog.go:1013  line format: [IWEF]yymmdd hh:mm:ss.uuuuuu goid file:line msg utf8=✓
W171002 06:48:03.534424 1 cli/start.go:587  RUNNING IN INSECURE MODE!

- Your cluster is open for any client that can access <all your IP addresses>.
- Any user, even root, can log in without providing a password.
- Any user, connecting as root, can read or write any data in your cluster.
- There is no network encryption nor authentication, and thus no confidentiality.

Check out how to secure your cluster: https://www.cockroachlabs.com/docs/secure-a-cluster.html
I171002 06:48:03.535302 1 cli/start.go:593  CockroachDB CCL v1.0.6 (linux amd64, built 2017/09/14 15:15:48, go1.8.3)
I171002 06:48:03.636829 1 server/config.go:281  available memory from cgroups (8.0 EiB) exceeds system memory 992 MiB, using system memory
I171002 06:48:03.636867 1 server/config.go:375  system total memory: 992 MiB
I171002 06:48:03.636969 1 server/config.go:377  server configuration:
max offset                   500ms
cache size                   128 MiB
SQL memory pool size         248 MiB
scan interval                10m0s
scan max idle time           200ms
consistency check interval   24h0m0s
metrics sample interval      10s
time until store dead        5m0s
send next timeout            10m0s
event log enabled            true
linearizable                 false
PID file                     /var/run/db.analytics.pid
I171002 06:48:03.637185 12 cli/start.go:340  starting cockroach node
W171002 06:48:03.643349 12 gossip/gossip.go:1196  [n?] no incoming or outgoing connections
I171002 06:48:03.644714 12 storage/engine/rocksdb.go:380  opening rocksdb instance at "/cockroach/cockroach-data"
I171002 06:48:03.654725 12 server/config.go:475  [n?] 1 storage engine initialized
I171002 06:48:03.654751 12 server/config.go:477  [n?] RocksDB cache size: 128 MiB
I171002 06:48:03.654764 12 server/config.go:477  [n?] store 0: RocksDB, max size 0 B, max open file limit -1
I171002 06:48:03.655817 12 server/node.go:454  [n?] store [n0,s0] not bootstrapped
I171002 06:48:03.655862 12 storage/stores.go:296  [n?] read 0 node addresses from persistent storage
I171002 06:48:03.656006 12 server/node.go:608  [n?] connecting to gossip network to verify cluster ID...
I171002 06:48:03.908469 29 gossip/client.go:131  [n?] started gossip client to 45.77.103.118:3000
I171002 06:48:04.160379 12 server/node.go:633  [n?] node connected via gossip and verified as part of cluster "bfc1ac39-3fe6-46da-a332-8db05b81d6bc"
I171002 06:48:04.161410 39 storage/stores.go:312  [n?] wrote 1 node addresses to persistent storage
I171002 06:48:24.162635 48 vendor/google.golang.org/grpc/clientconn.go:806  grpc: addrConn.resetTransport failed to create client transport: connection error: desc = "transport: dial tcp 45.77.103.118:26257: i/o timeout"; Reconnecting to {45.77.103.118:26257 <nil>}
I171002 06:48:27.878424 27 gossip/gossip.go:1210  [n?] node has connected to cluster via gossip
I171002 06:48:27.878733 27 storage/stores.go:312  [n?] wrote 1 node addresses to persistent storage
```
Thanks!

### PR DESCRIPTION
**Pull request by a-robinson**
Previously we'd end up sticking the listening port the server bound to
into `unresolvedAdvertAddr` instead of the user-provided advertise-port,
which effectively made the --advertise-port not have any effect at all.
I'm not sure how it originally worked for Irfan's use case.

Tested manually by setting up a GCE firewall on all port 26257 traffic,
proxying local port 3000 to local port 26257, and starting a cockroach
process with advertise host set to the VM's external IP address (to go
through the firewall) and advertise port set to 3000. This setup works
after this commit, but fails when run on v1.1-beta.20170928.

Fixes #18932 

Thanks for helping find this, @tomholub!

### CODE REVIEW

**Comment by nvanbenschoten** [comment]
Nice catch!

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[pkg/server/server.go, line 1335 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/18957#-KvTt7AKg5Eetajf2hkO:-KvTt7AKg5Eetajf2hkP:b-2cxs3p) ([raw file](https://github.com/cockroachdb/cockroach/blob/80a88aea8c44c5dacfa07ce9e3b504ee4580ac68/pkg/server/server.go#L1335)):*
> may need to be used set

wording's messed up here. Drop `used`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/18957#-:-KvTtNOeV4JWAqU6NF-P:b-73m6vw)*

**Comment by a-robinson** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[pkg/server/server.go, line 1335 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/18957#-KvTt7AKg5Eetajf2hkO:-KvTv87NC6_im1E1Z2zb:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/80a88aea8c44c5dacfa07ce9e3b504ee4580ac68/pkg/server/server.go#L1335)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

> may need to be used set

wording's messed up here. Drop `used`
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/18957)*

**Comment by nvanbenschoten** [comment]
LGTM

File: pkg/server/server.go [hunk 1]
```diff
@@ -1331,5 +1332,11 @@ func officialAddr(
 		return nil, errors.Errorf("hostname %q did not resolve to any addresses; listener address: %s", host, lnHost)
 	}
 
-	return util.NewUnresolvedAddr(lnAddr.Network(), net.JoinHostPort(host, lnPort)), nil
+	// cfgPort may need to be used if --advertise-port was set on the command line.
+	port := lnPort
+	if i, err := strconv.Atoi(cfgPort); err == nil && i > 0 {
```
Comment (tamird) [inline pkg/server/server.go]: Are you sure that parsing the port as an integer is correct? I recall @bdarnell mentioning that ports can be non-numeric.

Comment (bdarnell) [reply pkg/server/server.go]: Yeah, it's possible (but rarely done) to use strings like "http" in place of "80". We should probably allow anything but an empty string or literal "0" here. (although it doesn't matter much for this undocumented flag)
