### PR TITLE
sql/pgwire: report "too large" errors in extended protocol

### LINKED ISSUE #35699: sql: Connection reset by peer while performing bulk inserts
Trying to perform a bulk insert for a very large dataset, where every query has around 10000 records to be inserted. Only the first batch of 10000 records is successfully inserted and then the error ` write: connection reset by peer` is incurred. Tried playing around with the batch size, but after a particular cap amount, the same error occurs again. How can this issue be resolved?

### LINKED ISSUE #50330: pgwire: improve error messaging for large requests in prepared statements
A customer recently tried to complete a large transaction and ran into the hard limit of 16MB with this error message:
```SQL
Error message:
invalid syntax: statement ignored: unexpected error: write tcp 127.0.0.1:47362->127.0.0.1:26257: write: connection reset by peer
warning: error retrieving the transaction status: driver: bad connection
warning: connection lost!
opening new connection: all session settings will be lost
```
This error message is fairly opaque and hard to understand. We should try to improve this error message so that customers can understand that this is our limit. 

We could also add hints that encourage the customer to break this into smaller transactions.

### PR DESCRIPTION
**Pull request by rafiss**
In order to accomplish this, our pgwire implementation is updated so
that when an error occurs during the extended protocol, we now ignore
all messages until receiving a sync command. This matches the PostgreSQL
implementation of the protocol.

fixes #50330
fixes #35699
related to #57869 and possibly fixes it

Release note (sql change): Previously, SQL commands that were
sent during the PostgreSQL extended protocol that were too big
would error opaquely. This is now resolved by returning a more friendly
error message.

Release note (bug fix): CockroachDB now handles errors during the pgwire
extended protocol correctly. Specifically, when an error is detected while
processing any extended protocol message, an ErrorResponse is returned, then
the server reads and discards messages until a Sync command is received from
the client. This matches Postgres behavior: https://www.postgresql.org/docs/13/protocol-flow.html#PROTOCOL-FLOW-EXT-QUERY

### CODE REVIEW

File: pkg/sql/pgwire/pgwire_test.go [hunk 1]
```diff
@@ -1956,3 +1957,31 @@ func TestFailPrepareFailsTxn(t *testing.T) {
 		t.Fatal(err)
 	}
 }
+
+func TestOverlyLargeRequest(t *testing.T) {
```
Comment (otan) [inline pkg/sql/pgwire/pgwire_test.go:1961]: any reason this you chose to implement a new test method instead of extending `TestConnMessageTooBig`?

**Review by otan — APPROVED** [review]
cheers!

File: pkg/sql/pgwire/pgwire_test.go (hunk 1 above)
Comment (rafiss) [reply pkg/sql/pgwire/pgwire_test.go:1961]: ah nope! i had copied this test that jordan wrote and forgot i had it committed.
 i think i should modify `TestConnMessageTooBig` so it uses `postLongStrAction` for the prepared statements.

**Review by otan — APPROVED** [review]

**Comment by rafiss** [comment]
bors r=otan

**Comment by rafiss** [comment]
bors r-

`TestConnMessageTooBig/disallow_big_messages/prepared_statement_has_string/long_string` flaked on the first bors attempt, so gonna dig in a bit more

**Comment by rafiss** [comment]
Kinda scary: looks like it passes locally on my Mac even with `make stress`, but when I run in my Linux GCE worker, it fails pretty quickly when i do `make stress PKG=./pkg/sql/pgwire TESTS=TestConnMessageTooBig`

**Comment by rafiss** [comment]
It seems related to the cluster setting not taking effect in time. If I add a sleep after changing the cluster setting, then it no longer has this flakiness.

**Comment by knz** [comment]
I think this PR is still relevant.

**Comment by rafiss** [comment]
Yes it is. I still hope to get back to it in time for 21.1, but haven't had any new ideas for how to debug next.

**Comment by rafiss** [comment]
I rebased this to account for @otan's work on #59460 hoping that the code shuffling would help me figure out something that was wrong.

I still have the situation where `make test` passes on my Linux GCE instance, but ` make stress PKG=./pkg/sql/pgwire TESTS=TestConnMessageTooBig` does not. It just seems like the client doesn't get back the "this message was to big" error sometimes. It only seems to affect `prepared_statement_with_argument` and not `prepared_statement_has_string` so I guess that's a lead...

**Comment by rafiss** [comment]
i am currently feeling like i won't be able to pick this up in time for 21.1

**Comment by knz** [comment]
> It just seems like the client doesn't get back the "this message was too big" error sometimes, and i confirmed that the server is indeed sending that error. 

If the server sends the data and then closes the TCP connection, the TCP close message (RST) can catch up the data client-side (i.e. it's not like a Go channel: the TCP connection closing can erase the data queued in the receive buffer).

It's also possible that the client driver in our case gets confused by the combination of error + conn close and simply forgets to process the received error properly.

In any case, I would suggest to move forward with this with a pgtest datadriven test (see pgwire/pgtest_test.go). This will reduce the number of layers and also clarify what the exact intended behavior is.

**Comment by otan** [comment]
may also be worth retrying in case it was that pesky go HTTP bug which was fixed in Go 1.15.11

**Comment by knz** [comment]
I agree on retrying altough pgwire doesn't use http so I'm not sure how that specific bug would apply

**Comment by otan** [comment]
ah well in that case /shrug

**Comment by rafiss** [comment]
I figured out the issue -- this is ready for another look now. 

When reporting the "too big" error back, we had to change how the error is sent as per this diff:

```
-                    if err := writeErr(
-                        ctx,
-                        &sqlServer.GetExecutorConfig().Settings.SV,
-                        err,
-                        &c.msgBuilder,
-                        &c.writerState.buf,
-                    ); err != nil {
+                    if err := c.stmtBuf.Push(ctx, sql.SendError{Err: err}); err != nil {
                         return false, errors.New("pgwire: error writing too big error message to the client")
                     }
```

The old `writeErr` approach is not correct since it writes to `writerState.buf` directly. Since this error is written in a different goroutine from the goroutine that may flush data _from_ `writerState.buf`, it is possible for the error that is written to get lost in a race. We have to send `sql.SendError` into the `stmtBuf` so that the correct goroutine ends up writing the error into `writerState.buf`.

**Review by knz — COMMENTED** [review]
I really like your change, because it means we are now handling the situation of multiple statements after an error properly in the extended protocol; am I right?

I think this would warrant an extra datadriven test in pgwire/pgtest_test.go, that shows how this behaves in both the simple query and extended query protocols side-by-side.

(I also thought we had an issue about "statements after an error not behaving properly", but I can't seem to find it any more. Does that ring a bell? If it had been there, this fix would probably address that.)

> Reviewed 4 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/57590#-:-MbLqlZm37Ei6V1eJwod:b-hmutm7)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @otan)

**Comment by rafiss** [comment]
> it means we are now handling the situation of multiple statements after an error properly in the extended protocol; am I right?

yes, that's part of the change. i should also include that in a release note.

> I think this would warrant an extra datadriven test in pgwire/pgtest_test.go, that shows how this behaves in both the simple query and extended query protocols side-by-side.

i agree -- i'll work on that

> (I also thought we had an issue about "statements after an error not behaving properly", but I can't seem to find it any more. Does that ring a bell? If it had been there, this fix would probably address that.)

hmm i don't remember, i believe i was only aware of this discrepancy in our pgwire implementation because of the TODO comment i removed.

**Review by knz — APPROVED** [review]
:lgtm: thank you for the new test.

(A small suggestion to make it even more compact)

> Reviewed 6 of 6 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/57590#-:-Mb_wmJu4tomwDhJaVw2:bar5uxz)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @otan and @rafiss)

___
*[pkg/sql/pgwire/pgtest_test.go, line 50 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/57590#-Mb_wag51tkvSvFySnn2:-Mb_wag65HBE6cY0TEJ9:b-bct6j4) ([raw file](https://github.com/cockroachdb/cockroach/blob/992812623e3719c25659f0a0d1c2b169fb196f76/pkg/sql/pgwire/pgtest_test.go#L50)):*
> ```Go
> 			// size to something small. This lets us test the handling of large
> 			// query inputs. See the large_input test.
> 			_, _ = db.ExecContext(ctx, "SET CLUSTER SETTING sql.conn.max_read_buffer_message_size = '32 KiB'")
> ```

I don't think any of the tests need more than 1KiB even, which would make your reference test file slightly easier to open in a regular text editor.

**Comment by rafiss** [comment]
> I don't think any of the tests need more than 1KiB even, which would make your reference test file slightly easier to open in a regular text editor.

Unfortunately, the minimum allowed value of this cluster setting is 16 KiB. And also, there is another test (`decimal`) that uses a value this is ~17 KiB. We can try to reduce all these sizes later if it is causing annoyance.

tftr!

bors r=otan,knz
