### PR TITLE
cli: skip excluded node in debug zip

### LINKED ISSUE #128590: Cockroach debug zip --nodes flag still creates node-level folders and CPU profiles for skipped nodes
**Describe the problem**

Using the `--nodes` flag for the `debug zip` command leads to some misleading behavior. Node-level folders will be created for nodes not explicitly included with that flag, and the debug zip command will still get CPU profiles for each node in the cluster.

**To Reproduce**

For any cluster, run the `cockroach debug zip` command with the `--nodes` command. In my example, I have a 24.1.2 3-node cluster and I ran the following such that node 3 is skipped:

```
cockroach debug zip debug.zip --nodes=1,2 --insecure
```

The debug zip command will still reach out to each node in the cluster and get a `cpu.pprof` regardless of this `--nodes` flag. It will always then create a folder for each node, as well as a `<node_id>.skipped` file for each node not included in the `--nodes` flag:

```
debug/nodes % ls
1		2		3		3.skipped
```

This is misleading, and perhaps a bit problematic. We still spend time reaching out to those nodes for data and create a node-level folder for each node that is supposed to be excluded.

**Expected behavior**

I would expect there to be no node-level folder or CPU profile for nodes I don't care to get info from via the debug zip.

This is pretty minor, but confusing behavior.

**Additional data / screenshots**

n/a

**Environment:**

I believe this applies to all versions, but only tested in 24.1.

Jira issue: CRDB-41092

Epic CRDB-32134

### PR DESCRIPTION
**Pull request by aa-joshi**
Previously, debug zip cli command generates node directory with format `nodeID.skipped` for excluded nodes. It was causing confusion in analysing debug zip artifacts. To address this, this patch skips CPU profiles and directory generation for excluded nodes.

Epic: CRDB-32134
Fixes: #128590
Release note: None

### CODE REVIEW

File: pkg/cli/zip_test.go [hunk 1]
```diff
@@ -1252,3 +1252,60 @@ func TestCommandFlags(t *testing.T) {
...
+
+	tc := testcluster.StartTestCluster(t, 1, base.TestClusterArgs{
+		ServerArgs: base.TestServerArgs{
+			DefaultTestTenant: base.TestIsSpecificToStorageLayerAndNeedsASystemTenant,
+			Insecure:          true,
+		},
+	})
+	defer tc.Stopper().Stop(ctx)
+
+	_, err := c.RunWithCapture("debug zip --concurrency=1 --exclude-nodes=1 --cpu-profile-duration=0 " + dir + "/debug.zip")
```
Comment (arjunmahishi) [inline pkg/cli/zip_test.go:1291]: We should probably test with a permutation of `--exclude-nodes` and `--nodes`

File: pkg/cli/zip_test.go [hunk 2]
```diff
@@ -1252,3 +1252,60 @@ func TestCommandFlags(t *testing.T) {
...
+
+	d, err := r.Open("debug/nodes/1")
+	defer func() {
+		if d != nil {
+			_ = d.Close()
+		}
+	}()
+	if err == nil {
+		t.Fatal("node directory should not be present in the zip", err)
+	}
```
Comment (arjunmahishi) [inline pkg/cli/zip_test.go:1310]: We should probable check for that exact error. We should fail the test if there is any other error.

```suggestion
  require.True(t, os.IsNotExist(err), "node directory should not be present in the zip")
```

File: pkg/cli/zip_test.go [hunk 3]
```diff
@@ -1252,3 +1252,60 @@ func TestCommandFlags(t *testing.T) {
...
+			DefaultTestTenant: base.TestIsSpecificToStorageLayerAndNeedsASystemTenant,
+			Insecure:          true,
+		},
+	})
+	defer tc.Stopper().Stop(ctx)
+
+	_, err := c.RunWithCapture("debug zip --concurrency=1 --exclude-nodes=1 --cpu-profile-duration=0 " + dir + "/debug.zip")
+	if err != nil {
+		t.Fatal(err)
+	}
```
Comment (arjunmahishi) [inline pkg/cli/zip_test.go:1294]: NIT

```suggestion
  require.NoError(t, err)
```

(same applies below as well)

File: pkg/cli/zip_test.go (hunk 1 above)
Comment (aa-joshi) [reply pkg/cli/zip_test.go:1291]: We have range selection test:
https://github.com/cockroachdb/cockroach/blob/a44a9b1ffce25f51026b494a1dcb393cfc5361f3/pkg/cli/zip_test.go#L1060
One more challenge to club with current test is that `RunWithCapture` command runs against a single node even if we have a multi node cluster. So we are always getting end up with single node folder in debug zip.
Considering above both points, I didn't include in this test.

File: pkg/cli/zip_test.go (hunk 3 above)
Comment (aa-joshi) [reply pkg/cli/zip_test.go]: DONE

File: pkg/cli/zip_test.go (hunk 2 above)
Comment (aa-joshi) [reply pkg/cli/zip_test.go]: DONE

**Review by aa-joshi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/134379)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @angles-n-daemons and @arjunmahishi)

File: pkg/cli/zip_test.go (hunk 1 above)
Comment (arjunmahishi) [reply pkg/cli/zip_test.go:1291]: Ohh ok! Makes sense.

**Review by arjunmahishi — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/134379#-:-OB9nEd47sCH4x3Fpjvz:bnfp4nl)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @aa-joshi and @angles-n-daemons)

**Comment by aa-joshi** [comment]
TFTR!

bors r+
