### PR TITLE
sql: harden stmt bundle building code a bit

### LINKED ISSUE #149987: sql: v24.3.13: nil pointer when adding DistSQL diagrams to the bundle
This issue was auto filed by Sentry. It represents a crash or reported error on a live cluster with telemetry enabled.

Sentry Link: [https://cockroach-labs.sentry.io/issues/6741443189/?referrer=webhooks_plugin](https://cockroach-labs.sentry.io/issues/6741443189/?referrer=webhooks_plugin)

Panic Message:

```
conn_executor.go:963: runtime error: invalid memory address or nil pointer dereference
(1) attached stack trace
  -- stack trace:
  | github.com/cockroachdb/cockroach/pkg/sql.(*Server).ServeConn.func1
  | 	pkg/sql/conn_executor.go:963
  | [...repeated from below...]
Wraps: (2) while executing: EXPLAIN ANALYZE (DEBUG) SELECT _ FROM _ LIMIT _
Wraps: (3) attached stack trace
  -- stack trace:
  | github.com/cockroachdb/cockroach/pkg/sql.(*Server).ServeConn.func1
  | 	pkg/sql/conn_executor.go:963
  | runtime.gopanic
  | 	GOROOT/src/runtime/panic.go:770
  | runtime.panicmem
  | 	GOROOT/src/runtime/panic.go:261
  | runtime.sigpanic
  | 	GOROOT/src/runtime/signal_unix.go:881
  | github.com/cockroachdb/cockroach/pkg/sql.(*stmtBundleBuilder).addDistSQLDiagrams
  | 	pkg/sql/explain_bundle.go:432
  | github.com/cockroachdb/cockroach/pkg/sql.buildStatementBundle
  | 	pkg/sql/explain_bundle.go:163
  | github.com/cockroachdb/cockroach/pkg/sql.(*instrumentationHelper).Finish
  | 	pkg/sql/instrumentation.go:707
  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execStmtInOpenState.func11
  | 	pkg/sql/conn_executor_exec.go:655
  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execStmtInOpenState.func3
  | 	pkg/sql/conn_executor_exec.go:315
  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execStmtInOpenState
  | 	pkg/sql/conn_executor_exec.go:683
  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execStmt.func1
  | 	pkg/sql/conn_executor_exec.go:141
  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execWithProfiling
  | 	pkg/sql/conn_executor_exec.go:3471
  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execStmt
  | 	pkg/sql/conn_executor_exec.go:140
  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execCmd.func1
  | 	pkg/sql/conn_executor.go:2343
  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execCmd
  | 	pkg/sql/conn_executor.go:2348
  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).run
  | 	pkg/sql/conn_executor.go:2265
  | github.com/cockroachdb/cockroach/pkg/sql.(*Server).ServeConn
  | 	pkg/sql/conn_executor.go:965
  | github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*conn).processCommands
  | 	pkg/sql/pgwire/conn.go:251
  | github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*Server).serveImpl.func4
  | 	pkg/sql/pgwire/server.go:1196
  | runtime.goexit
  | 	src/runtime/asm_arm64.s:1222
Wraps: (4) runtime error: invalid memory address or nil pointer dereference
Error types: (1) *withstack.withStack (2) *safedetails.withSafeDetails (3) *withstack.withStack (4) runtime.errorString
-- report composition:
runtime.errorString
conn_executor.go:963: *withstack.withStack (top exception)
*safedetails.withSafeDetails: while executing: EXPLAIN ANALYZE (DEBUG) SELECT _ FROM _ LIMIT _
conn_executor.go:963: *withstack.withStack (1)
(check the extra data payloads)
```

<details>
<summary>Stacktrace (expand for inline code snippets):</summary>

[src/runtime/asm_arm64.s#L1221-L1223](src/runtime/asm_arm64.s#L1221-L1223)
[pkg/sql/pgwire/server.go#L1195-L1197](pkg/sql/pgwire/server.go#L1195-L1197)
[pkg/sql/pgwire/conn.go#L250-L252](pkg/sql/pgwire/conn.go#L250-L252)
[pkg/sql/conn_executor.go#L964-L966](pkg/sql/conn_executor.go#L964-L966)
[pkg/sql/conn_executor.go#L2264-L2266](pkg/sql/conn_executor.go#L2264-L2266)
[pkg/sql/conn_executor.go#L2347-L2349](pkg/sql/conn_executor.go#L2347-L2349)
[pkg/sql/conn_executor.go#L2342-L2344](pkg/sql/conn_executor.go#L2342-L2344)
[pkg/sql/conn_executor_exec.go#L139-L141](pkg/sql/conn_executor_exec.go#L139-L141)
[pkg/sql/conn_executor_exec.go#L3470-L3472](pkg/sql/conn_executor_exec.go#L3470-L3472)
[pkg/sql/conn_executor_exec.go#L140-L142](pkg/sql/conn_executor_exec.go#L140-L142)
[pkg/sql/conn_executor_exec.go#L682-L684](pkg/sql/conn_executor_exec.go#L682-L684)
[pkg/sql/conn_executor_exec.go#L314-L316](pkg/sql/conn_executor_exec.go#L314-L316)
[pkg/sql/conn_executor_exec.go#L654-L656](pkg/sql/conn_executor_exec.go#L654-L656)
[pkg/sql/instrumentation.go#L706-L708](pkg/sql/instrumentation.go#L706-L708)
[pkg/sql/explain_bundle.go#L162-L164](pkg/sql/explain_bundle.go#L162-L164)
[pkg/sql/explain_bundle.go#L431-L433](pkg/sql/explain_bundle.go#L431-L433)
[GOROOT/src/runtime/signal_unix.go#L880-L882](GOROOT/src/runtime/signal_unix.go#L880-L882)
[GOROOT/src/runtime/panic.go#L260-L262](GOROOT/src/runtime/panic.go#L260-L262)
[GOROOT/src/runtime/panic.go#L769-L771](GOROOT/src/runtime/panic.go#L769-L771)
[pkg/sql/conn_executor.go#L962-L964](pkg/sql/conn_executor.go#L962-L964)
</details>

```
src/runtime/asm_arm64.s in runtime.goexit at line 1222
pkg/sql/pgwire/server.go in pkg/sql/pgwire.(*Server).serveImpl.func4 at line 1196
pkg/sql/pgwire/conn.go in pkg/sql/pgwire.(*conn).processCommands at line 251
pkg/sql/conn_executor.go in pkg/sql.(*Server).ServeConn at line 965
pkg/sql/conn_executor.go in pkg/sql.(*connExecutor).run at line 2265
pkg/sql/conn_executor.go in pkg/sql.(*connExecutor).execCmd at line 2348
pkg/sql/conn_executor.go in pkg/sql.(*connExecutor).execCmd.func1 at line 2343
pkg/sql/conn_executor_exec.go in pkg/sql.(*connExecutor).execStmt at line 140
pkg/sql/conn_executor_exec.go in pkg/sql.(*connExecutor).execWithProfiling at line 3471
pkg/sql/conn_executor_exec.go in pkg/sql.(*connExecutor).execStmt.func1 at line 141
pkg/sql/conn_executor_exec.go in pkg/sql.(*connExecutor).execStmtInOpenState at line 683
pkg/sql/conn_executor_exec.go in pkg/sql.(*connExecutor).execStmtInOpenState.func3 at line 315
pkg/sql/conn_executor_exec.go in pkg/sql.(*connExecutor).execStmtInOpenState.func11 at line 655
pkg/sql/instrumentation.go in pkg/sql.(*instrumentationHelper).Finish at line 707
pkg/sql/explain_bundle.go in pkg/sql.buildStatementBundle at line 163
pkg/sql/explain_bundle.go in pkg/sql.(*stmtBundleBuilder).addDistSQLDiagrams at line 432
GOROOT/src/runtime/signal_unix.go in runtime.sigpanic at line 881
GOROOT/src/runtime/panic.go in runtime.panicmem at line 261
GOROOT/src/runtime/panic.go in runtime.gopanic at line 770
pkg/sql/conn_executor.go in pkg/sql.(*Server).ServeConn.func1 at line 963
```

### Tags

| Tag | Value |
| --- | --- |
| Command | demo |
| Environment | v24.3.13 |
| Go Version | go1.22.8 X:nocoverageredesign |
| Platform | darwin arm64 |
| Distribution | CCL |
| Cockroach Release | v24.3.13 |
| Cockroach SHA | 4b1048c740f790a97a4a088e06e5781ad7b1114f |
| # of CPUs | 12 |
| # of Goroutines | 8548 |

Jira issue: CRDB-52454

### PR DESCRIPTION
**Pull request by yuzefovich**
We just saw a sentry report where on explicit stmt bundle collection via EXPLAIN ANALYZE (DEBUG) we hit a nil pointer because `flowInfo.diagram` was nil. I've audited the code and don't know how this could've happened, so this commit hardens the code a bit by adding nil checks (and crashing in the test-only builds).

Fixes: #149987.

Release note: None

### CODE REVIEW

File: pkg/sql/plan.go [hunk 1]
```diff
@@ -320,7 +320,10 @@ type planNodeSpooled interface {
 var _ planNodeSpooled = &spoolNode{}
 
 type flowInfo struct {
-	typ     planComponentType
+	typ planComponentType
+	// diagram is only populated when instrumentationHelper.shouldSaveDiagrams()
+	// returns true. (Even in that case we've seen a sentry report where it was
+	// nil.)
```
Comment (mgartner) [inline pkg/sql/plan.go]: nit: if you're going to mention the sentry issue it might be nice to add a link to it. up to you.

**Review by mgartner — APPROVED** [review]
LGTM

**Review by yuzefovich — COMMENTED** [review]
TFTR!

bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/150115#-:-OWH28bAEtbPvWkGGQdN:b-oduykh)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @michae2)
