### PR TITLE
sql,copy: fix test infrastructure and update pgconn

### LINKED ISSUE #88801: copy: client side of copy in pgconn has an I/O race
https://github.com/jackc/pgconn/issues/128

Not sure if this is a regression or a release blocker but figured a tracking issue was worthwhile.  I think this doesn't affect 22.1 because we used lib/pq?   So this should probably be a release blocking regression.

The bug is a race that only occurs when failing (ie malformed in some way) COPY commands are occurring so its a bit of an edge case.

Jira issue: CRDB-19973

### PR DESCRIPTION
**Pull request by cucaroach**
sql/copy: update jackc/pgconn to fix copy bug

Fixes: https://github.com/cockroachdb/cockroach/issues/88801

Release note: None

sql,copy: fix test infrastructure

Previously we hacked around lack of copy protocol support in logictest
by doing an in memory hack that bypassed the client connection entirely.
Now that the client supports use pgx to support copy use that instead.

Also move copy test stuff to its own package.

Fixes: #84619

Release note: None

### CODE REVIEW

File: pkg/sql/copy/copy_test.go [hunk 1]
```diff
@@ -0,0 +1,301 @@
...
+			}
+			err = rows.Close()
+			require.NoError(t, err)
+			return results
+		default:
+			return fmt.Sprintf("unknown command: %s\n", d.Cmd)
+		}
+
+	}
+	datadriven.RunTest(t, testutils.TestDataPath(t, "copyfrom"), testCopy)
```
Comment (rafiss) [inline pkg/sql/copy/copy_test.go:133]: instead of `copyfrom` being a file, should it be a directory? then this will automatically test every file in that directory

Comment (cucaroach) [reply pkg/sql/copy/copy_test.go:133]: I was just following convention for when testdata only had one file, if we decide to add more we can throw in a dir walk here but seems like overkill ATM.

**Comment by cucaroach** [comment]
Okay test had some parallelism issues causing crashes in stress, should be good now.  Thanks!

**Review by otan — APPROVED** [review]

**Comment by cucaroach** [comment]
Okay I think this is RFAL.   I upgraded pgconn and hopefully did everything right.

**Comment by cucaroach** [comment]
@rafiss and @knz this is my first foray into go.mod changes so I won't bors this until one of you joins @otan in the green check department, thanks!

**Comment by otan** [comment]
what are you saying about my go.mod knowledge :')

**Review by knz — COMMENTED** [review]
yep you did this well :100:

**Comment by cucaroach** [comment]
Sorry is that a 👍 @knz or should I wait for the green check mark?  No rush...

**Comment by knz** [comment]
I can review+approve this if @rafiss would like me to, but i think you'll get a higher quality review from him.

**Comment by cucaroach** [comment]
@rafiss friendly ping

Should I rebase vendor again or wait till all the reviews are in?   Thanks!

**Review by rafiss — CHANGES_REQUESTED** [review]
i'm liking this new stuff! thanks for the reminder on this

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/88196#-:-NE73JZpDebooBrHHpPJ:b-f5fc55)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @cucaroach and @otan)

___
*[`pkg/sql/copy.go` line 59 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/88196#-NE6zitZD79xzZKcFhPh:-NE6zitZD79xzZKcFhPi:b2nhfwu) ([raw file](https://github.com/cockroachdb/cockroach/blob/076ff699d98a72cd44cae24ad33a5a997643da4c/pkg/sql/copy.go#L59)):*
> ```Go
> 		panic("SetCopyFromBatchSize is a test utility that requires crdb_test tag")
> 	}
> 	return old
> ```

nit: you could make this return a `reset` function, so in the tests you can use it like:
```
defer SetCopyFromBatchSize(x)()
```

also, would this work as a testing knob instead?
___
*[`pkg/sql/copy/copy_test.go` line 113 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/88196#-NE730tv-sql_ajTNTF1:-NE730tv-sql_ajTNTF2:by0t3xg) ([raw file](https://github.com/cockroachdb/cockroach/blob/076ff699d98a72cd44cae24ad33a5a997643da4c/pkg/sql/copy/copy_test.go#L113)):*
> ```Go
> 				if err := rows.Next(vals); err == io.EOF {
> 					break
> 				} else if err != nil {
> ```

nit: this could just be `else`, not `else if`
___
*[`pkg/sql/copy/copy_test.go` line 170 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/88196#-NE7-IM11Wsc3_U73lkS:-NE7-IM11Wsc3_U73lkT:b-9y9kkt) ([raw file](https://github.com/cockroachdb/cockroach/blob/076ff699d98a72cd44cae24ad33a5a997643da4c/pkg/sql/copy/copy_test.go#L170)):*
> ```Go
> 		query  string
> 		data   []string
> 		testf  func(clisqlclient.Conn, func(clisqlclient.Conn))
> ```

i find the `testf` wrapper thing a bit confusing. any reason why to do it this way instead of having a `setup` and `teardown` function?
___
*[`pkg/sql/copy/copy_test.go` line 171 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/88196#-NE70OcFCV12G00ynURT:-NE70OcFCV12G00ynURU:b-ugj5d1) ([raw file](https://github.com/cockroachdb/cockroach/blob/076ff699d98a72cd44cae24ad33a5a997643da4c/pkg/sql/copy/copy_test.go#L171)):*
> ```Go
> 		data   []string
> 		testf  func(clisqlclient.Conn, func(clisqlclient.Conn))
> 		result func(f1, f2 driver.Value) bool
> ```

i don't follow why this is named `result`. should it be named something like `checkResults`?
___
*[`pkg/sql/copy/copy_test.go` line 218 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/88196#-NE71VN5-ZZJ84xG4qQ8:-NE71VN5-ZZJ84xG4qQ9:bjf8q9o) ([raw file](https://github.com/cockroachdb/cockroach/blob/076ff699d98a72cd44cae24ad33a5a997643da4c/pkg/sql/copy/copy_test.go#L218)):*
> ```Go
> 			tconn := sqlConnCtx.MakeSQLConn(io.Discard, io.Discard, url.String())
> 			tc.testf(tconn, func(tconn clisqlclient.Conn) {
> 				// Without this everything comes back as strings
> ```

hm, well technically couldn't we just do all the equality checks using the strings?
___
*[`pkg/sql/copy/copy_test.go` line 236 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/88196#-NE72DBF7qb0D-RSRkWP:-NE72DBF7qb0D-RSRkWQ:b-mx7lk) ([raw file](https://github.com/cockroachdb/cockroach/blob/076ff699d98a72cd44cae24ad33a5a997643da4c/pkg/sql/copy/copy_test.go#L236)):*
> ```Go
> 
> 				results, err := tconn.Query(ctx, "SELECT crdb_internal_mvcc_timestamp FROM lineitem")
> 				require.NoError(t, err)
> ```

after this, you need to add a `defer func() { _ = results.Close() }()` (and maybe also add error checking to that)
___
*[`pkg/sql/copy/copy_test.go` line 280 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/88196#-NE70vorEJRrsT3SarwK:-NE70vorEJRrsT3SarwL:b-kdloc7) ([raw file](https://github.com/cockroachdb/cockroach/blob/076ff699d98a72cd44cae24ad33a5a997643da4c/pkg/sql/copy/copy_test.go#L280)):*
> ```Go
> 
> 	// send data in 5 batches of 10k rows
> 	const ROWS = sql.CopyBatchRowSizeDefault * 4
> ```

is referencing `CopyBatchRowSizeDefault` really correct here? can't it change based on being a metamorphic constant?

super nit: using all caps for inline constants is not really a convention we have
___
*[`pkg/sql/copy/copy_test.go` line 294 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/88196#-NE71B9XCAv_KSzCptHu:-NE71B9XCAv_KSzCptHv:b9sgc4a) ([raw file](https://github.com/cockroachdb/cockroach/blob/076ff699d98a72cd44cae24ad33a5a997643da4c/pkg/sql/copy/copy_test.go#L294)):*
> ```Go
> 			actualRows := rows[:batchSize]
> 			for i := 0; i < b.N; i++ {
> 				pprof.Do(ctx, pprof.Labels("run", "copy"), func(ctx context.Context) {
> ```

this feels off -- isn't the benchmark is going to be thrown off by the overhead of doing profiling? i thought normally our microbenchmarks just call the function being benchmarked

**Review by cucaroach — COMMENTED** [review]
Thanks for the fast review and good comments @rafiss !

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/88196#-:-NE7vioZ9uQ_zuClW95-:bi4rgyt)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @otan and @rafiss)

___
*[`pkg/sql/copy.go` line 59 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/88196#-NE6zitZD79xzZKcFhPh:-NE7Ve0eAuKCxFZt3oqT:bynk7o1) ([raw file](https://github.com/cockroachdb/cockroach/blob/076ff699d98a72cd44cae24ad33a5a997643da4c/pkg/sql/copy.go#L59)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

nit: you could make this return a `reset` function, so in the tests you can use it like:
```
defer SetCopyFromBatchSize(x)()
```

also, would this work as a testing knob instead?
</blockquote></details>

Too clever for me, maybe if it was used more than twice.
___
*[`pkg/sql/copy/copy_test.go` line 243 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/88196#-NCN1A_gutJsfstERT3a-r3-243:-NE7Vn6_2duzFyJgTQMG:b-73m6vw) ([raw file](https://github.com/cockroachdb/cockroach/blob/40d822670a50b0f4631390d8a6563986f6b974cb/pkg/sql/copy/copy_test.go#L243)):*
<details><summary><i>Previously, otan (Oliver Tan) wrote…</i></summary><blockquote>

this `err` gets shadowed as you use `err :=` in the `if` statement. you'll need to do:
```
err = results.Next(vals)
if err == ...
```
</blockquote></details>

Nice catch!
___
*[`pkg/sql/copy/copy_test.go` line 170 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/88196#-NE7-IM11Wsc3_U73lkS:-NE7Vv3M3aP1f5I5okq0:b-j7h617) ([raw file](https://github.com/cockroachdb/cockroach/blob/076ff699d98a72cd44cae24ad33a5a997643da4c/pkg/sql/copy/copy_test.go#L170)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

i find the `testf` wrapper thing a bit confusing. any reason why to do it this way instead of having a `setup` and `teardown` function?
</blockquote></details>

No this was just the first approach I thought of, seemed simpler to have just one "meat" lambda instead of two "sandwich" lambdas but maybe I misunderstand your suggestion.
___
*[`pkg/sql/copy/copy_test.go` line 171 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/88196#-NE70OcFCV12G00ynURT:-NE7W9JTDS72QCpdpsQp:b-8fx2u7) ([raw file](https://github.com/cockroachdb/cockroach/blob/076ff699d98a72cd44cae24ad33a5a997643da4c/pkg/sql/copy/copy_test.go#L171)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

i don't follow why this is named `result`. should it be named something like `checkResults`?
</blockquote></details>

:+1: 
___
*[`pkg/sql/copy/copy_test.go` line 218 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/88196#-NE71VN5-ZZJ84xG4qQ8:-NE7WdoO9Z_im8tC0_aR:b-6y0u3) ([raw file](https://github.com/cockroachdb/cockroach/blob/076ff699d98a72cd44cae24ad33a5a997643da4c/pkg/sql/copy/copy_test.go#L218)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

hm, well technically couldn't we just do all the equality checks using the strings?
</blockquote></details>

You would know better than me, I assumed I wanted to compare decimals to avoid any "lost in translation" problems but maybe that's not warranted.  Originally I used decimals before doing things across the CLI wire so it was easier to just keep it that way.
___
*[`pkg/sql/copy/copy_test.go` line 236 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/88196#-NE72DBF7qb0D-RSRkWP:-NE7X0w44GDm-zndqxsC:b-73m6vw) ([raw file](https://github.com/cockroachdb/cockroach/blob/076ff699d98a72cd44cae24ad33a5a997643da4c/pkg/sql/copy/copy_test.go#L236)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

after this, you need to add a `defer func() { _ = results.Close() }()` (and maybe also add error checking to that)
</blockquote></details>

Nice catch!
___
*[`pkg/sql/copy/copy_test.go` line 280 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/88196#-NE70vorEJRrsT3SarwK:-NE7XQuq9lGCZT-B-J4o:b-8yntnn) ([raw file](https://github.com/cockroachdb/cockroach/blob/076ff699d98a72cd44cae24ad33a5a997643da4c/pkg/sql/copy/copy_test.go#L280)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

is referencing `CopyBatchRowSizeDefault` really correct here? can't it change based on being a metamorphic constant?

super nit: using all caps for inline constants is not really a convention we have
</blockquote></details>

Yes but only because dev bench doesn't enable crdb_test.  
___
*[`pkg/sql/copy/copy_test.go` line 294 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/88196#-NE71B9XCAv_KSzCptHu:-NE7XXep7OkBQ4IRrQBQ:b-iblyth) ([raw file](https://github.com/cockroachdb/cockroach/blob/076ff699d98a72cd44cae24ad33a5a997643da4c/pkg/sql/copy/copy_test.go#L294)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

this feels off -- isn't the benchmark is going to be thrown off by the overhead of doing profiling? i thought normally our microbenchmarks just call the function being benchmarked
</blockquote></details>

Yeah it was nice when I was doing the copyshim thing but now that the client is going over the network it makes no sense.  For what its worth the cost of the copy is >>> than the cost of building the profiler label map.

**Review by rafiss — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/88196)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @cucaroach and @otan)

___
*[`pkg/sql/copy.go` line 59 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/88196#-NE6zitZD79xzZKcFhPh:-NE8HC3o3tz4LBjRn6w7:bcgcz7i) ([raw file](https://github.com/cockroachdb/cockroach/blob/076ff699d98a72cd44cae24ad33a5a997643da4c/pkg/sql/copy.go#L59)):*
<details><summary><i>Previously, cucaroach (Tommy Reilly) wrote…</i></summary><blockquote>

Too clever for me, maybe if it was used more than twice.
</blockquote></details>

heh, well i made the suggestion because we use this pattern in every unit test (including the `TestCopy` that you've added in this PR), so it just feels more conventional. even if you don't want to use the inlined defer, i think it's more readable to have this return a `reset` function which you could store in a variable and then call explicitly.

examples of what i'm talking about:

https://github.com/cockroachdb/cockroach/blob/b955fd662f17671c2a246ade635f4cfbee13ffeb/pkg/sql/tests/system_table_test.go#L46

https://github.com/cockroachdb/cockroach/blob/b955fd662f17671c2a246ade635f4cfbee13ffeb/pkg/ccl/multiregionccl/region_test.go#L141-L144

**Review by rafiss — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/88196)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @cucaroach and @otan)

___
*[`pkg/sql/copy/copy_test.go` line 170 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/88196#-NE7-IM11Wsc3_U73lkS:-NE8JkrHDj-u9izg0gXS:b5xtdq) ([raw file](https://github.com/cockroachdb/cockroach/blob/076ff699d98a72cd44cae24ad33a5a997643da4c/pkg/sql/copy/copy_test.go#L170)):*
<details><summary><i>Previously, cucaroach (Tommy Reilly) wrote…</i></summary><blockquote>

No this was just the first approach I thought of, seemed simpler to have just one "meat" lambda instead of two "sandwich" lambdas but maybe I misunderstand your suggestion.
</blockquote></details>

fine by me, i just had to get used to it
___
*[`pkg/sql/copy/copy_test.go` line 153 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/88196#-NE8KVUM60DF65hFa3nZ:-NE8KVUM60DF65hFa3n_:byqdpnt) ([raw file](https://github.com/cockroachdb/cockroach/blob/19b5ac834969f91c22683c7a46854a0ba18e773a/pkg/sql/copy/copy_test.go#L153)):*
> ```Go
> 
> 	decEq := func(v1, v2 driver.Value) bool {
> 		valToDecimal := func(v driver.Value) *apd.Decimal {
> ```

moving over my earlier thread here: i feel like it would be simpler to keep `alwaysInferResultTypes` = false, then we can just compare the strings directly

if for some reason you find that doesn't work, then you can still call  `apd.NewFromString` on the result from the sqlclient directly.

**Review by cucaroach — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/88196)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @otan and @rafiss)

___
*[`pkg/sql/copy.go` line 59 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/88196#-NE6zitZD79xzZKcFhPh:-NEB_xTz5l-YGmpYohVA:b-3bqkyo) ([raw file](https://github.com/cockroachdb/cockroach/blob/076ff699d98a72cd44cae24ad33a5a997643da4c/pkg/sql/copy.go#L59)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

heh, well i made the suggestion because we use this pattern in every unit test (including the `TestCopy` that you've added in this PR), so it just feels more conventional. even if you don't want to use the defer, i think it's more readable to have this return a `reset` function which you could store in a variable and then call explicitly.

examples of what i'm talking about:

https://github.com/cockroachdb/cockroach/blob/b955fd662f17671c2a246ade635f4cfbee13ffeb/pkg/sql/tests/system_table_test.go#L46

https://github.com/cockroachdb/cockroach/blob/b955fd662f17671c2a246ade635f4cfbee13ffeb/pkg/ccl/multiregionccl/region_test.go#L141-L144
</blockquote></details>

Ha!  I've looked at that `defer leaktest.AfterTest(t)()` and didn't fully grok what was going on until now!   Yeah, that's much cleaner, good call.
___
*[`pkg/sql/copy/copy_test.go` line 153 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/88196#-NE8KVUM60DF65hFa3nZ:-NEBdV9v5UjF_ExD_XfQ:b-8fx2u7) ([raw file](https://github.com/cockroachdb/cockroach/blob/19b5ac834969f91c22683c7a46854a0ba18e773a/pkg/sql/copy/copy_test.go#L153)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

moving over my earlier thread here: i feel like it would be simpler to keep `alwaysInferResultTypes` = false, then we can just compare the strings directly

if for some reason you find that doesn't work, then you can still call  `apd.NewFromString` on the result from the sqlclient directly. 
</blockquote></details>

:+1:

**Review by rafiss — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/88196)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @cucaroach and @otan)

___
*[`pkg/sql/copy/copy_test.go` line 153 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/88196#-NE8KVUM60DF65hFa3nZ:-NEBoHHJ3wa4JyHjDLUI:b-6ej9za) ([raw file](https://github.com/cockroachdb/cockroach/blob/19b5ac834969f91c22683c7a46854a0ba18e773a/pkg/sql/copy/copy_test.go#L153)):*
<details><summary><i>Previously, cucaroach (Tommy Reilly) wrote…</i></summary><blockquote>

:+1: 
</blockquote></details>

also i think you can just use `require.Equal` on the `driver.Value`s directly

**Review by rafiss — APPROVED** [review]
looks great! thanks for making copy super easy to test

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/88196#-:-NECMtRp6IinRtG2Wjme:biehpvr)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @cucaroach and @otan)

**Comment by cucaroach** [comment]
TFTRs!  
bors r+
