### PR TITLE
workload/schemachange: make column default errors more lenient

### LINKED ISSUE #128946: roachtest: schemachange/mixed-versions failed [computed column cannot also have DEFAULT]
roachtest.schemachange/mixed-versions [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/16458698?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/16458698?buildTab=artifacts#/schemachange/mixed-versions) on master @ [abe3d27bee5120afa287df2f8cc81c82ab6864da](https://github.com/cockroachdb/cockroach/commits/abe3d27bee5120afa287df2f8cc81c82ab6864da):

```
(mixedversion.go:696).Run: mixed-version test failure while running step 10 (run "run schemachange workload and validation in mixed version"): full command output in run_064350.914163844_n4_COCKROACHRANDOMSEED1.log: COMMAND_PROBLEM: exit status 1
test artifacts and logs in: /artifacts/schemachange/mixed-versions/run_1
```

Parameters:
 - <code>ROACHTEST_arch=amd64</code>
 - <code>ROACHTEST_cloud=gce</code>
 - <code>ROACHTEST_coverageBuild=false</code>
 - <code>ROACHTEST_cpu=4</code>
 - <code>ROACHTEST_encrypted=false</code>
 - <code>ROACHTEST_metamorphicBuild=false</code>
 - <code>ROACHTEST_ssd=0</code>
<details><summary>Help</summary>
<p>

See: [roachtest README](https://github.com/cockroachdb/cockroach/blob/master/pkg/cmd/roachtest/README.md)

See: [How To Investigate \(internal\)](https://cockroachlabs.atlassian.net/l/c/SSSBr8c7)

See: [Grafana](https://go.crdb.dev/roachtest-grafana/teamcity-16458698/schemachange-mixed-versions/1723617760213/1723617998898)

</p>
</details>
<details><summary>Same failure on other branches</summary>
<p>

- #128093 roachtest: schemachange/mixed-versions failed [C-test-failure O-roachtest O-robot P-2 T-sql-foundations branch-release-23.2]
- #127320 roachtest: schemachange/mixed-versions failed [unexpected unique constraint violation] [C-test-failure O-roachtest O-robot P-2 T-sql-foundations branch-release-24.2]
- #126883 roachtest: schemachange/mixed-versions failed [C-test-failure O-roachtest O-robot P-2 T-sql-foundations branch-release-24.1]
</p>
</details>
/cc @cockroachdb/sql-foundations
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*schemachange/mixed-versions.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/bazci/githubpost/issues)
</sub>

Jira issue: CRDB-41292

### PR DESCRIPTION
**Pull request by annrpom**
The fix (and backports) for https://github.com/cockroachdb/cockroach/pull/127545 are not released yet; our
workload (across all versions) expects the following errors for
the following cases:
```
CREATE TABLE t (
    id SERIAL PRIMARY KEY,
    value1 INT,
    value2 INT,
    computed_column INT GENERATED ALWAYS AS (value1 + value2) STORED
);

-- 1. setting a default on a computed column should produce a
syntax error:
demo@127.0.0.1:26257/demoapp/movr> alter table t alter column computed_column set
                                -> default 42;
ERROR: computed column "computed_column" cannot also have a DEFAULT expression
SQLSTATE: 42601

-- 2. even if the default is referencing an invalid type, setting a
default on a computed column should produce a syntax error:
demo@127.0.0.1:26257/demoapp/movr> alter table t alter column computed_column set default
                                -> 'nonexistent'::typedoesntexist;
ERROR: computed column "computed_column" cannot also have a DEFAULT expression
SQLSTATE: 42601

-- 3. even if the default is NULL, we block setting a default on a
computed column:
demo@127.0.0.1:26257/demoapp/movr> alter table t alter column computed_column set default
                                -> NULL;
ERROR: computed column "computed_column" cannot also have a DEFAULT expression
SQLSTATE: 42601

```

This aligns with postgres behavior as well:
```
postgres=# CREATE TABLE t (
    id SERIAL PRIMARY KEY,
    value1 INT,
    value2 INT,
    computed_column INT GENERATED ALWAYS AS (value1 + value2) STORED
);
CREATE TABLE
-- 1. setting a default on a computed column should produce a
syntax error:
postgres=# alter table t alter column computed_column set default null;
ERROR:  42601: column "computed_column" of relation "t" is a generated column
LOCATION:  ATExecColumnDefault, tablecmds.c:7644
-- 2. even if the default is referencing an invalid type, setting a
default on a computed column should produce a syntax error:
postgres=# ALTER TABLE t ALTER COLUMN computed_column SET DEFAULT 'IrrelevantValue'::nonexistent;
ERROR:  42601: column "computed_column" of relation "t" is a generated column
LOCATION:  ATExecColumnDefault, tablecmds.c:7712
-- 3. even if the default is NULL, we block setting a default on a
computed column:
postgres=# ALTER TABLE t ALTER COLUMN computed_column SET DEFAULT NULL;
ERROR:  42601: column "computed_column" of relation "t" is a generated column
LOCATION:  ATExecColumnDefault, tablecmds.c:7712
```

Previously, before https://github.com/cockroachdb/cockroach/pull/127545, we would disallow setting a default on a
computed column, but provide a different error message than postgres
(42P16). In addition, we would allow setting a NULL default on a
computed column.

Fixes: #128946

Release note: None

### CODE REVIEW

File: pkg/workload/schemachange/operation_generator.go [hunk 1]
```diff
@@ -2364,16 +2364,12 @@ func (og *operationGenerator) setColumnDefault(ctx context.Context, tx pgx.Tx) (
...
-			if columnForDefault.generated {
-				errCode = pgcode.Syntax
-			}
-			return makeOpStmtForSingleError(OpStmtDDL,
-				fmt.Sprintf(`ALTER TABLE %s ALTER COLUMN %s SET DEFAULT 'IrrelevantValue':::%s`,
-					tableName.String(), columnForDefault.name.String(), newTypeName.SQLString()),
-				errCode), nil
+			stmt := makeOpStmt(OpStmtDDL)
+			stmt.potentialExecErrors.add(pgcode.UndefinedObject)
+			stmt.potentialExecErrors.add(pgcode.Syntax)
```
Comment (rafiss) [inline pkg/workload/schemachange/operation_generator.go:2369]: just curious, does postgres also return a syntax error for this case? 

also, it could help to add a comment saying which scenario causes this error code.

Comment (annrpom) [reply pkg/workload/schemachange/operation_generator.go:2369]: it does -- here is what postgres does:

```
postgres=# CREATE TABLE t (
    id SERIAL PRIMARY KEY,
    value1 INT,
    value2 INT,
    computed_column INT GENERATED ALWAYS AS (value1 + value2) STORED
);
CREATE TABLE
postgres=# alter table t alter column computed_column set default null;
ERROR:  42601: column "computed_column" of relation "t" is a generated column
LOCATION:  ATExecColumnDefault, tablecmds.c:7644
```

also: fair point, let me add comments

Comment (annrpom) [reply pkg/workload/schemachange/operation_generator.go:2369]: https://github.com/cockroachdb/cockroach/blob/c73c32e36fce79ebc424184e3f560bd460c5f2b0/pkg/sql/pgwire/pgcode/plpgsql_codenames.go#L175

File: pkg/workload/schemachange/operation_generator.go [hunk 2]
```diff
@@ -2385,7 +2383,8 @@ func (og *operationGenerator) setColumnDefault(ctx context.Context, tx pgx.Tx) (
 	}
 	// Generated columns cannot have default values.
 	if columnForDefault.generated {
-		stmt.expectedExecErrors.add(pgcode.Syntax)
+		stmt.potentialExecErrors.add(pgcode.Syntax)
```
Comment (rafiss) [inline pkg/workload/schemachange/operation_generator.go:2386]: should we only add this to potential errors if `generated` is true? 

I'm mostly just trying to make sure I understand. why should we not always expect the UndefinedObject code here? this is in the if statement where we know we're using a type that doesn't exist, so aren't we always getting that error code? is it a mixed version issue where older versions are still returning SyntaxError even for types that don't exist?

also, what does postgres return if you set a default on a computed column on a type that doesn't exist?

maybe the thing that would help me the most is if the commit message could explain the postgres behavior, the CRDB behavior before https://github.com/cockroachdb/cockroach/pull/127545, and the CRDB behavior after https://github.com/cockroachdb/cockroach/pull/127545.

Comment (annrpom) [reply pkg/workload/schemachange/operation_generator.go:2388]: yes -- does the new commit message help? let me know if can do anything else

**Comment by annrpom** [comment]
Hm -- I just double-checked the enum failures and yeah they aren't related to this thing @rafiss 

Trying to see why the enum failures happen

**Review by rafiss — APPROVED** [review]
really great summary! thanks for fixing this!

**Comment by annrpom** [comment]
opened up https://github.com/cockroachdb/cockroach/pull/129133, https://github.com/cockroachdb/cockroach/pull/129134#pullrequestreview-2243188705, https://github.com/cockroachdb/cockroach/pull/129135, for the enum issues

will merge this for the mixed-version issues https://github.com/cockroachdb/cockroach/issues/128947

**Comment by annrpom** [comment]
TFTR! ('-')7 

bors r=rafiss
