### PR TITLE
sql: prevent concurrent create objects during drop schema

### LINKED ISSUE #134494: roachtest: backup-restore/round-trip failed
roachtest.backup-restore/round-trip [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/17632465?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/17632465?buildTab=artifacts#/backup-restore/round-trip) on release-24.3 @ [7252771de42bf0752052fae4f945c0e7a88d0ecd](https://github.com/cockroachdb/cockroach/commits/7252771de42bf0752052fae4f945c0e7a88d0ecd):

```
(monitor.go:149).Wait: monitor failure: full command output in run_093308.982838484_n4_COCKROACHRANDOMSEED7.log: COMMAND_PROBLEM: exit status 1
test artifacts and logs in: /artifacts/backup-restore/round-trip/run_1
```

Parameters:
 - <code>ROACHTEST_arch=amd64</code>
 - <code>ROACHTEST_cloud=gce</code>
 - <code>ROACHTEST_coverageBuild=false</code>
 - <code>ROACHTEST_cpu=4</code>
 - <code>ROACHTEST_encrypted=true</code>
 - <code>ROACHTEST_fs=ext4</code>
 - <code>ROACHTEST_localSSD=true</code>
 - <code>ROACHTEST_runtimeAssertionsBuild=false</code>
 - <code>ROACHTEST_ssd=0</code>
<details><summary>Help</summary>
<p>

See: [roachtest README](https://github.com/cockroachdb/cockroach/blob/master/pkg/cmd/roachtest/README.md)

See: [How To Investigate \(internal\)](https://cockroachlabs.atlassian.net/l/c/SSSBr8c7)

See: [Grafana](https://go.crdb.dev/roachtest-grafana/teamcity-17632465/backup-restore-round-trip/1730971873135/1730973026593)

</p>
</details>
/cc @cockroachdb/disaster-recovery
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*backup-restore/round-trip.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/bazci/githubpost/issues)

</sub>

Jira issue: CRDB-44113

### PR DESCRIPTION
**Pull request by fqazi**
Previously, we allowed CREATE object operations under a schema that was being dropped concurrently. This could lead to scenarios where descriptors could be created under the schema that is being dropped, which could lead to dangling namespace entries. To address this, this patch requires CREATE operations to wait for schema changes to complete on the target schema object.

Fixes: #134494

Release note (bug fix): Create relation / type could leave dangling namespace entries if the schema was concurrently being dropped.

### CODE REVIEW

**Review by spilchen — COMMENTED** [review]
Looks good. I just had a few questions for my own understanding.

> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/136325#-:-OCn_4-483OLtiYNGmN_:b-d7ym5n)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @fqazi)

___
*[`pkg/sql/create_table.go` line 100 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/136325#-OCnTU6gBePY_N7jkOuV:-OCnTU6gBePY_N7jkOuW:b-cy2rh3) ([raw file](https://github.com/cockroachdb/cockroach/blob/8e9d44ca1819ed22350e02841868a6f179a3eb64/pkg/sql/create_table.go#L100)):*
> ```Go
> 		// Exit early with an error if the schema is undergoing a declarative schema
> 		// change.
> 		if catalog.HasConcurrentDeclarativeSchemaChange(sc) {
> ```

What ensures a `DROP SCHEMA` operation doesn’t start immediately after this check? Does the code above acquire a lease on the schema, ensuring that the `DROP SCHEMA` operation is queued behind this one?
___
*[`pkg/sql/create_table.go` line 100 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/136325#-OCnVUQz2Diwx-v1nQA9:-OCnVUQz2Diwx-v1nQAA:b-64hqyk) ([raw file](https://github.com/cockroachdb/cockroach/blob/8e9d44ca1819ed22350e02841868a6f179a3eb64/pkg/sql/create_table.go#L100)):*
> ```Go
> 		// Exit early with an error if the schema is undergoing a declarative schema
> 		// change.
> 		if catalog.HasConcurrentDeclarativeSchemaChange(sc) {
> ```

Can the legacy schema changer be used to drop a schema, perhaps within an explicit transaction? Should we add protections against that, or is this error something we’re okay ignoring in the context of the legacy schema changer?
___
*[`pkg/sql/schema_changer_test.go` line 7884 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/136325#-OCn_-xrB4m53geYhCKh:-OCn_-xrB4m53geYhCKi:bds3i29) ([raw file](https://github.com/cockroachdb/cockroach/blob/8e9d44ca1819ed22350e02841868a6f179a3eb64/pkg/sql/schema_changer_test.go#L7884)):*
> ```Go
> }
> 
> func TestConcurrentDropAndCreateTable(t *testing.T) {
> ```

Nice test!

File: pkg/sql/create_table.go [hunk 1]
```diff
@@ -90,7 +91,16 @@ func (p *planner) getNonTemporarySchemaForCreate(
...
 	case catalog.SchemaUserDefined:
-		return p.Descriptors().MutableByID(p.txn).Schema(ctx, sc.GetID())
+		sc, err := p.Descriptors().MutableByID(p.txn).Schema(ctx, sc.GetID())
+		if err != nil {
+			return nil, err
+		}
+		// Exit early with an error if the schema is undergoing a declarative schema
+		// change.
+		if catalog.HasConcurrentDeclarativeSchemaChange(sc) {
+			return nil, scerrors.ConcurrentSchemaChangeError(sc)
```
Comment (rafiss) [inline pkg/sql/create_table.go:101]: could we make this error occur for _all_ legacy schema changes? (e.g., put this check in a common code path like writeSchemaChange.) seems like it might save us a lot of headaches. or would that be too much of a behavior change?

Comment (fqazi) [reply pkg/sql/create_table.go:101]: writeSchemaChange already has this logic, so that covers most if not all modification operations. The problem in this case is that the name resolution logic for new objects does not need to modify the parent objects. So, there isn't a singular code path outside of shared logic for resolving schema / databases for parent objects.

**Review by fqazi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/136325)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @rafiss and @spilchen)

___
*[`pkg/sql/create_table.go` line 100 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/136325#-OCnTU6gBePY_N7jkOuV:-OCoA2B78Kjfg9pAz3vH:b-xqkwx6) ([raw file](https://github.com/cockroachdb/cockroach/blob/8e9d44ca1819ed22350e02841868a6f179a3eb64/pkg/sql/create_table.go#L100)):*
<details><summary><i>Previously, spilchen wrote…</i></summary><blockquote>

What ensures a `DROP SCHEMA` operation doesn’t start immediately after this check? Does the code above acquire a lease on the schema, ensuring that the `DROP SCHEMA` operation is queued behind this one?
</blockquote></details>

The descriptor is read from KV as mutable, so if it gets modified this txn will retry. Or the modifying txn will wait depending on priorities.
___
*[`pkg/sql/create_table.go` line 100 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/136325#-OCnVUQz2Diwx-v1nQA9:-OCoAI2-8pT18UwAVQM3:b-x3k91h) ([raw file](https://github.com/cockroachdb/cockroach/blob/8e9d44ca1819ed22350e02841868a6f179a3eb64/pkg/sql/create_table.go#L100)):*
<details><summary><i>Previously, spilchen wrote…</i></summary><blockquote>

Can the legacy schema changer be used to drop a schema, perhaps within an explicit transaction? Should we add protections against that, or is this error something we’re okay ignoring in the context of the legacy schema changer?
</blockquote></details>

Fairpoint let me change this to a more generic check for any schema changes.
___
*[`pkg/sql/schema_changer_test.go` line 7884 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/136325#-OCn_-xrB4m53geYhCKh:-OCoAYsZ0B5ulSCMkX75:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/8e9d44ca1819ed22350e02841868a6f179a3eb64/pkg/sql/schema_changer_test.go#L7884)):*
<details><summary><i>Previously, spilchen wrote…</i></summary><blockquote>

Nice test!
</blockquote></details>

Done.

**Review by spilchen — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/136325)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @fqazi and @rafiss)

___
*[`pkg/sql/create_table.go` line 100 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/136325#-OCnVUQz2Diwx-v1nQA9:-OCoPbTM-GGJEV4yHHvK:b-j6xnlf) ([raw file](https://github.com/cockroachdb/cockroach/blob/8e9d44ca1819ed22350e02841868a6f179a3eb64/pkg/sql/create_table.go#L100)):*
<details><summary><i>Previously, fqazi (Faizan Qazi) wrote…</i></summary><blockquote>

Fairpoint let me change this to a more generic check for any schema changes.
</blockquote></details>

Did you address this with your change to use `HasConcurrentSchemaChanges` in `table.go`?
___
*[`pkg/sql/table.go` line 273 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/136325#-OCoN5tF4qMfcMOweo0K:-OCoN5tF4qMfcMOweo0L:b4apom4) ([raw file](https://github.com/cockroachdb/cockroach/blob/678dfd136d07945ae3fb243743a11339f7423545/pkg/sql/table.go#L273)):*
> ```Go
> 			tableDesc.Name)
> 	}
> 	// Exit early with an error if the table is undergoing a declarative schema
> ```

nit: should this comment still reference declarative? I believe the check below now also applies to legacy schema changes.

**Review by fqazi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/136325)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @rafiss and @spilchen)

___
*[`pkg/sql/create_table.go` line 100 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/136325#-OCnVUQz2Diwx-v1nQA9:-OCoQUx112KghpT1UAq3:bxwxto4) ([raw file](https://github.com/cockroachdb/cockroach/blob/8e9d44ca1819ed22350e02841868a6f179a3eb64/pkg/sql/create_table.go#L100)):*
<details><summary><i>Previously, spilchen wrote…</i></summary><blockquote>

Did you address this with your change to use `HasConcurrentSchemaChanges` in `table.go`?
</blockquote></details>

Ugh, I modified the wrong file. Should have been here, good catch.
___
*[`pkg/sql/table.go` line 273 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/136325#-OCoN5tF4qMfcMOweo0K:-OCoRO6L7UYUT2Jp9dPu:bn6lb3z) ([raw file](https://github.com/cockroachdb/cockroach/blob/678dfd136d07945ae3fb243743a11339f7423545/pkg/sql/table.go#L273)):*
<details><summary><i>Previously, spilchen wrote…</i></summary><blockquote>

nit: should this comment still reference declarative? I believe the check below now also applies to legacy schema changes.
</blockquote></details>

Done.

Didn't mean to modify this code :facepalm:

**Review by spilchen — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/136325#-:-OCoStQS9z2HVFlAXn2Z:bnfp4nl)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @rafiss)

**Comment by fqazi** [comment]
@spilchen TFTR!

bors r+

**Comment by fqazi** [comment]
blathers backport 24.3

**Comment by fqazi** [comment]
blathers backport 24.2

**Comment by fqazi** [comment]
blathers backport 24.1
