### PR TITLE
release-22.2: backupccl: upgrade restoreTPCCIncLatest/nodes=10 backup fixture

### LINKED ISSUE #88090: roachtest: restoreTPCCIncLatest/nodes=10 failed
roachtest.restoreTPCCIncLatest/nodes=10 [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/6495720?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/6495720?buildTab=artifacts#/restoreTPCCIncLatest/nodes=10) on release-22.2 @ [aac413cd4ca62f3392029b42219ebb2788979fb8](https://github.com/cockroachdb/cockroach/commits/aac413cd4ca62f3392029b42219ebb2788979fb8):

```
		Wraps: (2) output in run_091015.901604956_n1_cockroach_sql
		Wraps: (3) ./cockroach sql --insecure -e "
		  | 				RESTORE FROM '/2022/09/07-000000.00' IN
		  | 				'gs://cockroach-fixtures/tpcc-incrementals-22.2?AUTH=implicit'
		  | 				AS OF SYSTEM TIME '2022-09-07 12:15:00'" returned
		  | stderr:
		  | ERROR: backup from version 1000022.1-70 is newer than current version 22.1-70
		  | Failed running "sql"
		  |
		  | stdout:
		Wraps: (4) COMMAND_PROBLEM
		Wraps: (5) Node 1. Command with error:
		  | ``````
		  | ./cockroach sql --insecure -e "
		  | 				RESTORE FROM '/2022/09/07-000000.00' IN
		  | 				'gs://cockroach-fixtures/tpcc-incrementals-22.2?AUTH=implicit'
		  | 				AS OF SYSTEM TIME '2022-09-07 12:15:00'"
		  | ``````
		Wraps: (6) exit status 1
		Error types: (1) *withstack.withStack (2) *errutil.withPrefix (3) *cluster.WithCommandDetails (4) errors.Cmd (5) *hintdetail.withDetail (6) *exec.ExitError

	monitor.go:127,restore.go:474,test_runner.go:908: monitor failure: monitor task failed: t.Fatal() was called
		(1) attached stack trace
		  -- stack trace:
		  | main.(*monitorImpl).WaitE
		  | 	main/pkg/cmd/roachtest/monitor.go:115
		  | main.(*monitorImpl).Wait
		  | 	main/pkg/cmd/roachtest/monitor.go:123
		  | github.com/cockroachdb/cockroach/pkg/cmd/roachtest/tests.registerRestore.func1
		  | 	github.com/cockroachdb/cockroach/pkg/cmd/roachtest/tests/restore.go:474
		  | main.(*testRunner).runTest.func2
		  | 	main/pkg/cmd/roachtest/test_runner.go:908
		Wraps: (2) monitor failure
		Wraps: (3) attached stack trace
		  -- stack trace:
		  | main.(*monitorImpl).wait.func2
		  | 	main/pkg/cmd/roachtest/monitor.go:171
		Wraps: (4) monitor task failed
		Wraps: (5) attached stack trace
		  -- stack trace:
		  | main.init
		  | 	main/pkg/cmd/roachtest/monitor.go:80
		  | runtime.doInit
		  | 	GOROOT/src/runtime/proc.go:6340
		  | runtime.main
		  | 	GOROOT/src/runtime/proc.go:233
		  | runtime.goexit
		  | 	GOROOT/src/runtime/asm_amd64.s:1594
		Wraps: (6) t.Fatal() was called
		Error types: (1) *withstack.withStack (2) *errutil.withPrefix (3) *withstack.withStack (4) *errutil.withPrefix (5) *withstack.withStack (6) *errutil.leafError
```
<p>Parameters: <code>ROACHTEST_cloud=gce</code>
, <code>ROACHTEST_cpu=4</code>
, <code>ROACHTEST_ssd=0</code>
</p>
<details><summary>Help</summary>
<p>

See: [roachtest README](https://github.com/cockroachdb/cockroach/blob/master/pkg/cmd/roachtest/README.md)

See: [How To Investigate \(internal\)](https://cockroachlabs.atlassian.net/l/c/SSSBr8c7)

</p>
</details>
/cc @cockroachdb/bulk-io
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*restoreTPCCIncLatest/nodes=10.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)
</sub>

Jira issue: CRDB-19677

### PR DESCRIPTION
**Pull request by msbutler**
Backport 1/1 commits from #90669.

/cc @cockroachdb/release

---

restoreTPCCIncLatest/nodes=10 has been consistently failing because the backup fixture is more than one major version behind the cluster running the restore. This patch updates the backup fixture used by this roachtest.

Fixes #88090

Release note: None

Release justification: test only change, fixes a failing roachtest

### CODE REVIEW

File: pkg/cmd/roachtest/tests/restore.go [hunk 1]
```diff
@@ -612,6 +565,17 @@ func registerRestore(r registry.Registry) {
 						t.L().Printf("pausing RESTORE job")
 						// Pause the job and wait for it to transition to a paused state.
 						_, err = conn.ExecContext(ctx, `PAUSE JOB $1`, jobID)
+						if err != nil {
```
Comment (adityamaru) [inline pkg/cmd/roachtest/tests/restore.go:568]: I think we should error out if we're not able to pause atleast once? Otherwise this test is not doing what it says it is, wdyt

Comment (msbutler) [reply pkg/cmd/roachtest/tests/restore.go:568]: good idea. Will send the patch to master and then add it to the backports.

Comment (msbutler) [reply pkg/cmd/roachtest/tests/restore.go:568]: opened this on master https://github.com/cockroachdb/cockroach/pull/91024

Comment (msbutler) [reply pkg/cmd/roachtest/tests/restore.go:568]: added cherry pick to this branch

**Review by adityamaru — APPROVED** [review]
