### PR TITLE
cli: ensure user set --password can also modify the password

### LINKED ISSUE #27882: cli: cockroachdb user set --password not updating the password
**BUG REPORT**

Please describe the issue you observed:

- What did you do?

I inserted a new user in a secure cluster setup without a password first 

`cockraochdb user set test --certs-dir=/cockroach-certs --host=cockroachdb-public`. 

Then i tried to update the user with `--password` flag. However, the password was not updated and still remained empty. Therefore, i removed the user again and readded it with `--password` flag.

- What did you expect to see?

The user with empty password to be updated.

- What did you see instead?

User password remained empty.

### PR DESCRIPTION
**Pull request by knz**
Fixes  #27882.

Until now the flag `--password` could only set the password if the
user did not exist previously (ie. during user creation). This patch
fixes the feature so that `--password` can be used to change an
existing user's password.

Release note (bug fix): `cockroach user set --password` can now change
the password of existing users.

### CODE REVIEW

**Comment by knz** [comment]
@mberhault @bdarnell should we backport this to 2.0?

**Review by petermattis — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28197#-:-LIuuj9p8VlzTNfKXb1s:bnfp4nl)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

File: pkg/sql/create_user.go [hunk 1]
```diff
@@ -106,25 +106,23 @@ func (n *CreateUserNode) startExec(params runParams) error {
...
-			"%s named %s already exists",
-			msg, normalizedUsername)
 	}
 
 	n.run.rowsAffected, err = params.extendedEvalCtx.ExecCfg.InternalExecutor.Exec(
 		params.ctx,
 		opName,
 		params.p.txn,
-		"insert into system.users values ($1, $2, $3)",
+		`upsert into system.users(username, "hashedPassword", "isRole") values ($1, $2, $3)`,
```
Comment (mberhault) [inline pkg/sql/create_user.go]: this isn't right, you can't use the `CREATE USER` command to modify a user, that's what the `ALTER USER` command is for.

**Review by mberhault — DISMISSED** [review]

**Review by knz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28197)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/sql/create_user.go, line 125 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/28197#-LIuflYHAtrikD2P9tRM-r1-125:-LIvCJnwDc-48spmK3Nz:bcla5pk) ([raw file](https://github.com/cockroachdb/cockroach/blob/16c67a160901d0d585c5dee04e1479f68e3068a0/pkg/sql/create_user.go#L125)):*
<details><summary><i>Previously, mberhault (marc) wrote…</i></summary><blockquote>

this isn't right, you can't use the `CREATE USER` command to modify a user, that's what the `ALTER USER` command is for.
</blockquote></details>

Oh I see.

Thanks for catching this. Fixed. PTAL.

**Comment by mberhault** [comment]
LGTM. Thanks for that.
This should be fairly safe to backport to 2.0 but given that we have an alternative solution with `ALTER USER` I think we can skip it.

**Review by knz — COMMENTED** [review]
All right. Thanks!

bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28197#-:-LIvKuuQ8zBUm1347dVp:bxrjkot)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)
