### PR TITLE
kvserver: deflake TestPromoteNonVoterInAddVoter

### LINKED ISSUE #156701: kv/kvserver.TestPromoteNonVoterInAddVoter: TestPromoteNonVoterInAddVoter failed
kv/kvserver.TestPromoteNonVoterInAddVoter.TestPromoteNonVoterInAddVoter [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Ci_TestsIbmCloudLinuxS390x_UnitTestsS390x/20681543?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Ci_TestsIbmCloudLinuxS390x_UnitTestsS390x/20681543?buildTab=artifacts#/) on master @ [98557a6304fe239582e20ebd07f69a3ee8e47bdf](https://github.com/cockroachdb/cockroach/commits/98557a6304fe239582e20ebd07f69a3ee8e47bdf):

```
=== RUN   TestPromoteNonVoterInAddVoter
    test_log_scope.go:171: test logs captured to: /artifacts/tmp/_tmp/135a86ba3501d232b0a98ae8902ff534/logTestPromoteNonVoterInAddVoter903965342
    test_log_scope.go:82: use -show-logs to present logs inline
    test_server_shim.go:594: DRPC is enabled (override by TestingGlobalDRPCOption)
    replicate_queue_test.go:2283: 
        	Error Trace:	pkg/kv/kvserver/replicate_queue_test.go:2283
        	            				pkg/kv/kvserver/replicate_queue_test.go:2308
        	            				pkg/testutils/soon.go:71
        	            				pkg/util/retry/retry.go:355
        	            				pkg/testutils/soon.go:77
        	            				pkg/testutils/soon.go:56
        	            				pkg/testutils/soon.go:38
        	            				pkg/kv/kvserver/replicate_queue_test.go:2307
        	Error:      	Received unexpected error:
        	            	sql: no rows in result set
        	Test:       	TestPromoteNonVoterInAddVoter
    exectrace.go:39: execution trace written to /artifacts/tmp/_tmp/135a86ba3501d232b0a98ae8902ff534/logTestPromoteNonVoterInAddVoter903965342/exectrace_goid_89908.bin
    panic.go:615: -- test log scope end --
test logs left over in: /artifacts/tmp/_tmp/135a86ba3501d232b0a98ae8902ff534/logTestPromoteNonVoterInAddVoter903965342
--- FAIL: TestPromoteNonVoterInAddVoter (47.29s)
```
<details><summary>Help</summary>
<p>

See also: [How To Investigate a Go Test Failure \(internal\)](https://cockroachlabs.atlassian.net/l/c/HgfXfJgM)
</p>
</details>
/cc @cockroachdb/kv-triage
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*TestPromoteNonVoterInAddVoter.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/bazci/githubpost/issues)

</sub>

Jira issue: CRDB-56123

### PR DESCRIPTION
**Pull request by pav-kv**
Fixes #156701

### CODE REVIEW

File: pkg/kv/kvserver/replicate_queue_test.go [hunk 1]
```diff
@@ -2279,12 +2279,19 @@ SELECT * FROM (
...
-SELECT start_key from crdb_internal.ranges_no_leases WHERE range_id IN
-(SELECT range_id FROM [SHOW RANGES FROM TABLE t] LIMIT 1);
-`).Scan(&key))
+		if err := db.QueryRow(q).Scan(&key); errors.Is(err, gosql.ErrNoRows) {
+			return 0, 0, roachpb.RangeDescriptor{}, nil
+		} else if err != nil {
+			return 0, 0, roachpb.RangeDescriptor{}, err
+		}
+
 		desc, err := tc.LookupRange(key)
```
Comment (pav-kv) [inline pkg/kv/kvserver/replicate_queue_test.go:2295]: Could probably leverage this `LookupRange` instead, by passing in some key that we know belongs to `TABLE t`.

**Review by tbg — APPROVED** [review]

**Comment by pav-kv** [comment]
bors r=tbg

**Comment by pav-kv** [comment]
blathers backport-all
