### PR TITLE
roachprod: bump node_exporter to v1.10.2

### LINKED ISSUE #160375: roachtest: tpcc-nowait/literal/w=1000/nodes=5/cpu=16 failed
roachtest.tpcc-nowait/literal/w=1000/nodes=5/cpu=16 [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/20919590?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/20919590?buildTab=artifacts#/tpcc-nowait/literal/w=1000/nodes=5/cpu=16) on release-25.3 @ [1c6dfd7dab4327c9af986aec63762267925d1b05](https://github.com/cockroachdb/cockroach/commits/1c6dfd7dab4327c9af986aec63762267925d1b05):

```
(tpcc.go:2336).setupPrometheusForRoachtest: grafana-start currently cannot run on darwin: COMMAND_PROBLEM: exit status 1
test artifacts and logs in: /artifacts/tpcc-nowait/literal/w=1000/nodes=5/cpu=16/run_1
```

Parameters:
 - <code>arch=amd64</code>
 - <code>cloud=gce</code>
 - <code>coverageBuild=false</code>
 - <code>cpu=16</code>
 - <code>encrypted=false</code>
 - <code>fs=ext4</code>
 - <code>localSSD=true</code>
 - <code>runtimeAssertionsBuild=false</code>
 - <code>ssd=0</code>
<details><summary>Help</summary>
<p>

See: [roachtest README](https://github.com/cockroachdb/cockroach/blob/master/pkg/cmd/roachtest/README.md)

See: [How To Investigate \(internal\)](https://cockroachlabs.atlassian.net/l/c/SSSBr8c7)

See: [Grafana](https://go.crdb.dev/roachtest-grafana/teamcity-20919590/tpcc-nowait-literal-w-1000-nodes-5-cpu-16/1767276571367/1767276728264)

</p>
</details>
/cc @cockroachdb/test-eng
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*tpcc-nowait/literal/w=1000/nodes=5/cpu=16.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/bazci/githubpost/issues)

</sub>

Jira issue: CRDB-58324

### LINKED ISSUE #160527: roachprod: prometheus node_exporter may crash due to concurrent map read/write
In [1] we have evidence that the `node_exporter` can crash on concurrent map read/write,

```
Jan 01 14:08:54 teamcity-20919590-1767249508-171-n6cpu16-0004 node_exporter[4121]: fatal error: concurrent map read and map write
Jan 01 14:08:54 teamcity-20919590-1767249508-171-n6cpu16-0004 node_exporter[4121]: goroutine 112 [running]:
Jan 01 14:08:54 teamcity-20919590-1767249508-171-n6cpu16-0004 node_exporter[4121]: runtime.throw(0xc27b20, 0x21)
Jan 01 14:08:54 teamcity-20919590-1767249508-171-n6cpu16-0004 node_exporter[4121]:         /usr/local/go/src/runtime/panic.go:1117 +0x72 fp=0xc00052bc00 sp=0xc00052bbd0 pc=0x438132
Jan 01 14:08:54 teamcity-20919590-1767249508-171-n6cpu16-0004 node_exporter[4121]: runtime.mapaccess2_faststr(0xb35160, 0xc0002ba690, 0xc00044cc90, 0xc, 0x1, 0x1)
Jan 01 14:08:54 teamcity-20919590-1767249508-171-n6cpu16-0004 node_exporter[4121]:         /usr/local/go/src/runtime/map_faststr.go:116 +0x4a5 fp=0xc00052bc70 sp=0xc00052bc00 pc=0x4143e5
Jan 01 14:08:54 teamcity-20919590-1767249508-171-n6cpu16-0004 node_exporter[4121]: github.com/prometheus/node_exporter/collector.(*netDevCollector).Update(0xc0001768c0, 0xc0003af800, 0x10d9580, 0x0)
Jan 01 14:08:54 teamcity-20919590-1767249508-171-n6cpu16-0004 node_exporter[4121]:         /app/collector/netdev_common.go:96 +0x15c fp=0xc00052be10 sp=0xc00052bc70 pc=0xa51e9c
Jan 01 14:08:54 teamcity-20919590-1767249508-171-n6cpu16-0004 node_exporter[4121]: github.com/prometheus/node_exporter/collector.execute(0xc0e5a8, 0x6, 0xcf2120, 0xc0001768c0, 0xc0003af800, 0xcf1a80, 0xc000134690)
Jan 01 14:08:54 teamcity-20919590-1767249508-171-n6cpu16-0004 node_exporter[4121]:         /app/collector/collector.go:161 +0x84 fp=0xc00052bf50 sp=0xc00052be10 pc=0xa214e4
Jan 01 14:08:54 teamcity-20919590-1767249508-171-n6cpu16-0004 node_exporter[4121]: github.com/prometheus/node_exporter/collector.NodeCollector.Collect.func1(0xc0003af800, 0xc0002ba1e0, 0xcf1a80, 0xc000134690, 0xc0002f4ef0, 0xc0e5a8, 0x6, 0xcf2120, 0xc0001768c0)
Jan 01 14:08:54 teamcity-20919590-1767249508-171-n6cpu16-0004 node_exporter[4121]:         /app/collector/collector.go:152 +0x71 fp=0xc00052bf98 sp=0xc00052bf50 pc=0xa93391
Jan 01 14:08:54 teamcity-20919590-1767249508-171-n6cpu16-0004 node_exporter[4121]: runtime.goexit()
Jan 01 14:08:54 teamcity-20919590-1767249508-171-n6cpu16-0004 node_exporter[4121]:         /usr/local/go/src/runtime/asm_amd64.s:1371 +0x1 fp=0xc00052bfa0 sp=0xc00052bf98 pc=0x471081
Jan 01 14:08:54 teamcity-20919590-1767249508-171-n6cpu16-0004 node_exporter[4121]: created by github.com/prometheus/node_exporter/collector.NodeCollector.Collect
Jan 01 14:08:54 teamcity-20919590-1767249508-171-n6cpu16-0004 node_exporter[4121]:         /app/collector/collector.go:151 +0x13c
```

Perhaps it's time to upgrade the `node_exporter`?! While at it, we should also fix the error message in `prometheus.Init`. As amusing as it is,

```
grafana-start currently cannot run on darwin
```

I'm pretty sure the roachtest nightlies don't run off of a mac. :)

[1] https://github.com/cockroachdb/cockroach/issues/160375#issuecomment-3713072383

Jira issue: CRDB-58398

### PR DESCRIPTION
**Pull request by golgeek**
We've been running node_exporter 1.2.2 for the last 4 years or so, and while it has been pretty reliable, we've seen some issues [1].

This patch bumps node_exporter to the latest version, released a few months ago. It is noted that an issue has been identified around the reporting of readonly filesystems [2] in this version, but this should not impact our use of node_exporter. That being said, we should probably bump to the next version when it is released.

This patch also ensures improves the process starting of `node_exporter` in case of tests with local prometheus and grafana if a systemd service existed in a stopped or failed state.

[1] https://github.com/cockroachdb/cockroach/issues/160527
[2] https://github.com/prometheus/node_exporter/issues/3484

Fixes: #160527
Closes: #160375
Release note: None

### CODE REVIEW

File: pkg/roachprod/prometheus/prometheus.go [hunk 1]
```diff
@@ -247,41 +247,45 @@ func Init(
...
+		cd node_exporter &&
+		sudo systemd-run --unit node_exporter --same-dir ./node_exporter \
+			--web.listen-address=":%[2]d" --web.telemetry-path="%[3]s"
+	fi
 fi
 `, cfg.PrometheusNode, vm.NodeExporterPort, vm.NodeExporterMetricsPath, nodeExporterStarted),
 		); err != nil {
 			// TODO(msbutler): download binary for target platform. currently we
 			// hardcode downloading the linux binary.
-			return nil, errors.Wrap(err, "grafana-start currently cannot run on darwin")
```
Comment (srosenberg) [inline pkg/roachprod/prometheus/prometheus.go:284]: Good riddance :)

**Review by srosenberg — APPROVED** [review]
