### PR TITLE
pgwire: increase timeout and add Error() call

### LINKED ISSUE #118741: sql/pgwire: TestParseClientProvidedSessionParameters failed
sql/pgwire.TestParseClientProvidedSessionParameters [failed](https://tanzanite.cluster.engflow.com/invocations/default/c3af9552-3cdb-4ea6-b57c-71957ce8d83e?testReportRun=22&testReportShard=16&testReportAttempt=1#targets-Ly9wa2cvc3FsL3Bnd2lyZTpwZ3dpcmVfdGVzdA==) on master @ [3c41c509a87cba7a1fd3f5cfdb0f6badb78e3704](https://github.com/cockroachdb/cockroach/commits/3c41c509a87cba7a1fd3f5cfdb0f6badb78e3704):

Fatal error:

```
panic: test timed out after 4m57s
running tests:
	TestParseClientProvidedSessionParameters (4m57s)
	TestParseClientProvidedSessionParameters/user_is_set_from_query (4m57s)

```
Stack: 

```
goroutine 24 [running]:
testing.(*M).startAlarm.func1()
	GOROOT/src/testing/testing.go:2259 +0x3b9
created by time.goFunc
	GOROOT/src/time/sleep.go:176 +0x2d
```
<details><summary>Log preceding fatal error</summary>
<p>

```
=== RUN   TestParseClientProvidedSessionParameters
    test_log_scope.go:170: test logs captured to: outputs.zip/logTestParseClientProvidedSessionParameters2373417980
    test_log_scope.go:81: use -show-logs to present logs inline
=== RUN   TestParseClientProvidedSessionParameters/user_is_set_from_query
```
</p>
</details>

Parameters:
 - <code>attempt=1</code>
 - <code>run=22</code>
 - <code>shard=16</code>
<details><summary>Help</summary>
<p>

See also: [How To Investigate a Go Test Failure \(internal\)](https://cockroachlabs.atlassian.net/l/c/HgfXfJgM)
</p>
</details>
/cc @cockroachdb/sql-foundations @cockroachdb/server
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*TestParseClientProvidedSessionParameters.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)
</sub>

Jira issue: CRDB-35879

### PR DESCRIPTION
**Pull request by rickystewart**
This test seems to deadlock sporadically under remote execution. I believe the connection is timing out, which due to the way this test was written causes it to deadlock. I'm increasing the timeout to attempt to increase reliability, and separately, we also add a call to `Error()` to mark the test as failed should the connection fail.

Closes #118741.

Epic: None
Release note: None

### CODE REVIEW

**Comment by rickystewart** [comment]
Uh, it seems like this created CI failures. 🤔

**Comment by rickystewart** [comment]
@rafiss I'm going to need your help with this. It seems that this test ALWAYS fails if you add the `t.Error()` call. I don't know what's wrong with it. However, the test seems to be broken without it as well.

**Review by rafiss — APPROVED** [review]
i think i figured out the right fix. i've added one more change so the server actually returns something to the client. previously, the client would always see a "connection timeout" since even though the server accepted the connection, it never replied with anything.

File: pkg/sql/pgwire/conn_test.go [hunk 1]
```diff
@@ -1610,11 +1617,16 @@ func TestParseClientProvidedSessionParameters(t *testing.T) {
...
 				defer wg.Done()
-				ctx, cancel := context.WithTimeout(context.Background(), 100*time.Millisecond)
+				ctx, cancel := context.WithTimeout(context.Background(), 500*time.Millisecond)
 				defer cancel()
 				url := fmt.Sprintf("%s&%s", baseURL, query)
 				c, connErr := pgx.Connect(ctx, url)
 				if connErr != nil {
+					// If we didn't get the expected error from the server, then it
+					// means there was a connection failure.
+					if !testutils.IsError(connErr, "received connection") {
```
Comment (rickystewart) [inline pkg/sql/pgwire/conn_test.go:1627]: Nit: maybe better would be `var ReceivedConnectionError = errors.New("received connection")`, then `errors.Is(connErr, ReceivedConnectionError)`. This also seems fine.

**Review by rickystewart — COMMENTED** [review]
@rafiss Seems like a new test is failing now? `TestConn`

File: pkg/sql/pgwire/conn_test.go (hunk 1 above)
Comment (rafiss) [reply pkg/sql/pgwire/conn_test.go]: to avoid breaking TestConn, i changed this to instead send a "connection successful" response

**Comment by rickystewart** [comment]
TFTR!

bors r=rafiss
