### PR TITLE
changefeedccl: add retry to TestChangefeedFailOnTableOffline

### LINKED ISSUE #142033: ccl/changefeedccl: TestChangefeedFailOnTableOffline failed
ccl/changefeedccl.TestChangefeedFailOnTableOffline [failed](https://tanzanite.cluster.engflow.com/invocations/default/266997f1-f50e-4209-aeac-fa624c0ee096?testReportRun=3&testReportShard=5&testReportAttempt=1#targets-Ly9wa2cvY2NsL2NoYW5nZWZlZWRjY2w6Y2hhbmdlZmVlZGNjbF90ZXN0) on release-24.2 @ [8fd5bb201dbb7699d3c6231f52214b9d1884b314](https://github.com/cockroachdb/cockroach/commits/8fd5bb201dbb7699d3c6231f52214b9d1884b314):

```
=== RUN   TestChangefeedFailOnTableOffline
    test_log_scope.go:165: test logs captured to: outputs.zip/logTestChangefeedFailOnTableOffline3713681840
    test_log_scope.go:76: use -show-logs to present logs inline
    changefeed_test.go:3987: -- test log scope end --
test logs left over in: outputs.zip/logTestChangefeedFailOnTableOffline3713681840
--- FAIL: TestChangefeedFailOnTableOffline (37.09s)
=== RUN   TestChangefeedFailOnTableOffline/cloudstorage/reverted_import_fails_changefeed_with_earlier_cursor
    helpers_test.go:869: making server as secondary tenant
    helpers_test.go:948: making cloudstorage feed factory
    sql_runner.go:237: expected query 'IMPORT INTO for_import CSV DATA ($1);' error 'pause point', got: pq: aborted in DistSender: result is ambiguous: context canceled
    --- FAIL: TestChangefeedFailOnTableOffline/cloudstorage/reverted_import_fails_changefeed_with_earlier_cursor (18.85s)
```

Parameters:
 - <code>attempt=1</code>
 - <code>race=true</code>
 - <code>run=3</code>
 - <code>shard=5</code>
<details><summary>Help</summary>
<p>

See also: [How To Investigate a Go Test Failure \(internal\)](https://cockroachlabs.atlassian.net/l/c/HgfXfJgM)
</p>
</details>
/cc @cockroachdb/cdc
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*TestChangefeedFailOnTableOffline.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/bazci/githubpost/issues)

</sub>

Jira issue: CRDB-48132

### PR DESCRIPTION
**Pull request by aerfrei**
Previously, this TestChangefeedFailOnTableOffline test could fail if the import attempt failed with "result is ambiguous". This error should be retried. This should reduce this source of flakiness for that test.

Fixes: #142033
Release note: None

### CODE REVIEW

File: pkg/testutils/sqlutils/sql_runner.go [hunk 1]
```diff
@@ -244,6 +244,31 @@ func (sr *SQLRunner) ExpectErrWithTimeout(
...
+) {
+	helperOrNoop(t)()
+	d := sr.SucceedsSoonDuration
+	if d == 0 {
+		d = testutils.SucceedsSoonDuration()
+	}
+	err := timeutil.RunWithTimeout(context.Background(), "expect-err", d, func(ctx context.Context) error {
+		_, err := sr.DB.ExecContext(ctx, query, args...)
+		// If the error matches the retryable error expression, retry the query once.
+		if err != nil && testutils.IsError(err, retryableErrorRE) {
```
Comment (asg0451) [inline pkg/testutils/sqlutils/sql_runner.go:259]: why retry only once, immediately? maybe do exponential backoff within the allotted timeout

Comment (aerfrei) [reply pkg/testutils/sqlutils/sql_runner.go:259]: Yes, I'll definitely try to do an exponential backoff.

Do you think it should be possible to implement this with testutils.SucceedsWithin or testutils.SucceedsWithinError? I was trying to do that but was facing the issue that we want this function to both sometimes immediately fail (the exec context call succeeds with no errors) and sometimes immediately succeed (sees the pause point error) and sometimes retry (ambigious result error). I think that may make this impossible.

Wanted to confirm before trying to reinvent the wheel. Unfortunately the implementation of succeedsWithin relies on a deprecated function (retry.ForDuration) which also complicates writing this new kind of three option retry loop.

cc: @rharding6373

Comment (asg0451) [reply pkg/testutils/sqlutils/sql_runner.go:259]: i dont know of a helper that does that, i think making your own is fine

File: pkg/util/retry/retry.go [hunk 2]
```diff
@@ -180,6 +180,30 @@ func (opts Options) Do(ctx context.Context, fn func(ctx context.Context) error)
...
+		err, retryable := fn(ctx)
+		if err == nil {
+			return nil
+		}
+		if !retryable {
+			return err
+		}
+	}
+	// TODO: CI fails with this check, even though the check in the previous function is the same.
+	// if err == nil {
```
Comment (aerfrei) [inline pkg/util/retry/retry.go:201]: Linting seems to think this check is tautological. I did it because it seemed like it should behave similarly to how it does above in the Do function. Am I missing the difference here?

Comment (asg0451) [reply pkg/util/retry/retry.go:201]: is it bc of the err nil check on line 193? how can the err be nil after that check?

Comment (aerfrei) [reply pkg/util/retry/retry.go:201]: My understanding was that we are protecting against r.Next() evaluating to false on the first invocation. Regardless, isn't the previous function doing the same thing with a return on nil error in the for loop but a check for nil again after the loop? I feel like I'm missing the difference. I tried asking copilot and didn't get an answer that made sense.

Comment (KeithCh) [reply pkg/util/retry/retry.go:201]: I'm not sure either, I commented out the `if !retryable` block in `DoWithRetryable` so it basically matches `Do()`, but I still get the lint error

Comment (andyyang890) [reply pkg/util/retry/retry.go:201]: The value of `err` at line 200 will always be `nil` because it is never assigned to. If you want to reassign to it on line 191, you need to do:
```
		var retryable bool
		err, retryable = fn(ctx)
```

Comment (aerfrei) [reply pkg/util/retry/retry.go:201]: Ah, I had a feeling it was something like that. Thanks for taking a look!

**Review by KeithCh — APPROVED** [review]

File: pkg/util/retry/retry.go [hunk 3]
```diff
@@ -180,6 +180,29 @@ func (opts Options) Do(ctx context.Context, fn func(ctx context.Context) error)
 	return err
 }
 
+// DoWithRetryable invokes the closure according to the retry options until it
+// returns success or a non-retryable error. Always returns an error unless the
+// return is prompted by a successful invocation of `fn`.
+func (opts Options) DoWithRetryable(
+	ctx context.Context, fn func(ctx context.Context) (err error, retryable bool),
```
Comment (andyyang890) [inline pkg/util/retry/retry.go:187]: nit: error should be the last return value

File: pkg/testutils/sqlutils/sql_runner.go [hunk 4]
```diff
@@ -244,6 +245,27 @@ func (sr *SQLRunner) ExpectErrWithTimeout(
...
+	helperOrNoop(t)()
+	var err error
+
+	retryOpts := retry.Options{MaxRetries: 5}
+	err = retryOpts.DoWithRetryable(context.Background(), func(ctx context.Context) (error, bool) {
+		_, err = sr.DB.ExecContext(context.Background(), query, args...)
+		if testutils.IsError(err, retryableErrorRE) {
+			return err, true
+		}
+		if err == nil {
```
Comment (andyyang890) [inline pkg/testutils/sqlutils/sql_runner.go:261]: nit: this check is unnecessary

**Review by asg0451 — APPROVED** [review]
looks good to me % andy's nits

**Comment by aerfrei** [comment]
blathers backport-all
