### PR TITLE
sql: fix CDC expression planning for tables without columns

### LINKED ISSUE #114058: changefeedccl: using CDC query with empty table causes a crash
This crashes:
```
create table empty();
create changefeed into 'null://sink' as select * from empty; 
```

Stack trace:
```
ERROR: internal error: unable to determine result columns
SQLSTATE: XX000
DETAIL: stack trace:
github.com/cockroachdb/cockroach/pkg/sql/distsql_plan_changefeed.go:168: PlanCDCExpression()
github.com/cockroachdb/cockroach/pkg/ccl/changefeedccl/cdceval/plan.go:86: normalizeExpression()
github.com/cockroachdb/cockroach/pkg/ccl/changefeedccl/cdceval/plan.go:52: func1()
github.com/cockroachdb/cockroach/pkg/ccl/changefeedccl/cdceval/plan.go:188: func2()
github.com/cockroachdb/cockroach/pkg/sql/exec_util.go:3813: func1()
github.com/cockroachdb/cockroach/pkg/sql/internal.go:1681: func2()
github.com/cockroachdb/cockroach/pkg/sql/internal.go:1770: func4()
github.com/cockroachdb/cockroach/pkg/kv/txn.go:1012: exec()
github.com/cockroachdb/cockroach/pkg/kv/db.go:1055: runTxn()
github.com/cockroachdb/cockroach/pkg/kv/db.go:1018: TxnWithAdmissionControl()
github.com/cockroachdb/cockroach/pkg/kv/db.go:993: Txn()
github.com/cockroachdb/cockroach/pkg/sql/internal.go:1757: txn()
github.com/cockroachdb/cockroach/pkg/sql/internal.go:1679: DescsTxn()
github.com/cockroachdb/cockroach/pkg/sql/exec_util.go:3812: DescsTxn()
github.com/cockroachdb/cockroach/pkg/ccl/changefeedccl/cdceval/plan.go:172: withPlanner()
github.com/cockroachdb/cockroach/pkg/ccl/changefeedccl/cdceval/plan.go:48: NormalizeExpression()
github.com/cockroachdb/cockroach/pkg/ccl/changefeedccl/changefeed_stmt.go:1080: validateAndNormalizeChangefeedExpression()
github.com/cockroachdb/cockroach/pkg/ccl/changefeedccl/changefeed_stmt.go:508: createChangefeedJobRecord()
github.com/cockroachdb/cockroach/pkg/ccl/changefeedccl/changefeed_stmt.go:194: func1()
github.com/cockroachdb/cockroach/pkg/ccl/changefeedccl/changefeed_stmt.go:324: func2()
github.com/cockroachdb/cockroach/pkg/sql/planhook.go:206: func1()
src/runtime/asm_arm64.s:1197: goexit()
```

Jira issue: CRDB-33318

### PR DESCRIPTION
**Pull request by massimo-ua**
Fixes an issue in the CDC expression planning that was causing an error when planning for tables without columns. The error occurred because the planner
returned an assertion failure when it couldn't determine any result columns. The issue happens when using a CDC expression with a table that has no user-defined columns (e.g. created with CREATE TABLE empty()) and running a query like SELECT * FROM empty. Since there are no columns to select, the presentation list is empty, which triggered the assertion failure. This fix removes the check that returns an error when the presentation is empty, allowing CDC expressions to work with tables that have no user-defined columns. The planner now correctly handles this edge case and returns a valid plan with an empty presentation.
Fixes #114058.
Fixes https://cockroachlabs.atlassian.net/browse/CRDB-33318.
Release note (bug fix): Fixed an issue where changefeed expressions on tables without columns would fail with an internal error: "unable to determine result columns".

### CODE REVIEW

File: pkg/sql/distsql_plan_changefeed_test.go [hunk 1]
```diff
@@ -687,3 +687,46 @@ func copyColumnAs(t *testing.T, table catalog.TableDescriptor, from, to tree.Nam
 	desc.SystemColumnKind = catpb.SystemColumnKind_NONE
 	return dst
 }
+
+// TestChangefeedPlanWithEmptyTable verifies that PlanCDCExpression can handle
+// tables with no columns without causing the "unable to determine result columns" error.
+// This test specifically targets a fix for the SQL error [XX000]:
+// "ERROR: internal error: unable to determine result columns" which occurs
+// when a CDC expression is planned against a table without columns.
+func TestChangefeedPlanWithEmptyTable(t *testing.T) {
```
Comment (andyyang890) [inline pkg/sql/distsql_plan_changefeed_test.go:696]: Could you also add a test that creates a changefeed on an empty table and validates getting rows? `TestChangefeedDiff` is an example of a such a test.

You could consider using something like this to get the row keys:
```
INSERT INTO empty DEFAULT VALUES RETURNING rowid;
```

**Review by andyyang890 — COMMENTED** [review]
Thanks for your contribution!

File: pkg/sql/distsql_plan_changefeed_test.go (hunk 1 above)
Comment (massimo-ua) [reply pkg/sql/distsql_plan_changefeed_test.go:696]: Test added

File: pkg/ccl/changefeedccl/changefeed_test.go [hunk 2]
```diff
@@ -10197,3 +10197,27 @@ func TestChangefeedProtectedTimestampUpdate(t *testing.T) {
 
 	cdcTest(t, testFn, feedTestForceSink("kafka"), withTxnRetries)
 }
+
+// TestChangefeedDiffEmptyTable verifies that a changefeed with the diff option
+// correctly captures changes on an initially empty table. It ensures changefeed
+// behavior is consistent when tables start with no data.
+func TestChangefeedDiffEmptyTable(t *testing.T) {
```
Comment (andyyang890) [inline pkg/ccl/changefeedccl/changefeed_test.go:10204]: Thanks for adding this test. It appears to be timing out under stress on CI when the randomly selected sink is `sinkless`. The reason for this is creating a core changefeed blocks until a row is received.

To fix that, could you please make this change:
```
diff --git a/pkg/ccl/changefeedccl/changefeed_test.go b/pkg/ccl/changefeedccl/changefeed_test.go
index c7a91bae1b1..a8bf27a3f53 100644
--- a/pkg/ccl/changefeedccl/changefeed_test.go
+++ b/pkg/ccl/changefeedccl/changefeed_test.go
@@ -10208,12 +10208,12 @@ func TestChangefeedDiffEmptyTable(t *testing.T) {
        testFn := func(t *testing.T, s TestServer, f cdctest.TestFeedFactory) {
                sqlDB := sqlutils.MakeSQLRunner(s.DB)
                sqlDB.Exec(t, `CREATE TABLE empty()`)
-               empty := feed(t, f, `CREATE CHANGEFEED FOR empty WITH diff`)
-               defer closeFeed(t, empty)
-
                var rowid int
                sqlDB.QueryRow(t, `INSERT INTO empty DEFAULT VALUES RETURNING rowid`).Scan(&rowid)
 
+               empty := feed(t, f, `CREATE CHANGEFEED FOR empty WITH diff`)
+               defer closeFeed(t, empty)
+
                assertPayloads(t, empty, []string{
                        fmt.Sprintf(`empty: [%d]->{"after": {"rowid": %d}, "before": null}`, rowid, rowid),
                })
```

File: pkg/sql/distsql_plan_changefeed.go [hunk 3]
```diff
@@ -163,10 +163,6 @@ func PlanCDCExpression(
 		return cdcPlan, errors.AssertionFailedf("expected at least 1 span to scan")
 	}
 
-	if len(presentation) == 0 {
```
Comment (andyyang890) [inline pkg/sql/distsql_plan_changefeed.go:166]: I'm hesitant to simply delete this check because it would prevent us from catching a developer error in the vast majority of cases when the table isn't empty. I think we might want to check a more specific condition instead, although I don't currently know what that should be. I'll consult with my team to see if they have any ideas.

Comment (massimo-ua) [reply pkg/sql/distsql_plan_changefeed.go:166]: Thanks. I'd appreciate any tips

Comment (massimo-ua) [reply pkg/sql/distsql_plan_changefeed.go:166]: Hey @andyyang890 Any updates?

**Comment by asg0451** [comment]
hey @massimo-ua, Andy asked me to have a look at this. I will review it Monday so we can unblock you. Thanks for the contribution!

**Comment by asg0451** [comment]
i agree with andy here, that we shouldnt remove the protection that check provides. it guards against allowing bad contents of cdc queries. 

your test cases show an interesting case where the changefeed *would* have returned data. my take is that if the changefeed would return data (aka there are NOT VISIBLE columns), the error should not arise and the feed should be created as normal.

can you alter the code to take into account NOT VISIBLE columns when doing these checks? (this might not be feasible, but it would be a better solution if it is). and then if the projection is STILL empty, that signifies a bug.

**Review by asg0451 — CHANGES_REQUESTED** [review]
i agree with andy here, that we shouldnt remove the protection that check provides. it guards against allowing bad contents of cdc queries.

your test cases show an interesting case where the changefeed would have returned data. my take is that if the changefeed would return data (aka there are NOT VISIBLE columns), the error should not arise and the feed should be created as normal.

can you alter the code to take into account NOT VISIBLE columns when doing these checks? (this might not be feasible, but it would be a better solution if it is). and then if the projection is STILL empty, that signifies a bug.

if this turns out to be infeasible we can talk about alternatives

**Comment by massimo-ua** [comment]
> i agree with andy here, that we shouldnt remove the protection that check provides. it guards against allowing bad contents of cdc queries.
> 
> your test cases show an interesting case where the changefeed would have returned data. my take is that if the changefeed would return data (aka there are NOT VISIBLE columns), the error should not arise and the feed should be created as normal.
> 
> can you alter the code to take into account NOT VISIBLE columns when doing these checks? (this might not be feasible, but it would be a better solution if it is). and then if the projection is STILL empty, that signifies a bug.
> 
> if this turns out to be infeasible we can talk about alternatives

Thanks for the hint, @asg0451! I added the condition back and improved it with error suppression for empty tables containing only hidden columns.

File: pkg/sql/distsql_plan_changefeed.go [hunk 4]
```diff
@@ -164,7 +164,22 @@ func PlanCDCExpression(
 	}
 
 	if len(presentation) == 0 {
-		return cdcPlan, errors.AssertionFailedf("unable to determine result columns")
+		hasHiddenColumns := false
+		// There are no columns to return, let's try to find out if there are hidden columns.
+		cdcPlan.CollectPlanColumns(func(column colinfo.ResultColumn) bool {
```
[the remark this answers is not in the document]
Comment (massimo-ua) [reply pkg/sql/distsql_plan_changefeed.go:169]: Do you have any suggestions about how to verify not visible columns? I haven’t found a way to do that

File: pkg/ccl/changefeedccl/changefeed_test.go (hunk 2 above)
Comment (asg0451) [inline pkg/ccl/changefeedccl/changefeed_test.go:10204]: this test tests that `create changefeed for empty` works, but this already works. the issue is with `create changefeed as select * from empty`. can you add a test for this?

also, i think the correct behaviour would either be 1) error more gracefully (not an "unexpected error" -- maybe an unimplemented error?), or 2) succeed and have rows look like this: `{"key":"[1053964827675656193]","value":"{\"after\": {}"}` (with after being empty obj, or null, or similar). 

can you implement one of the above and test it?

**Review by asg0451 — CHANGES_REQUESTED** [review]

File: pkg/sql/distsql_plan_changefeed.go (hunk 4 above)
[the remark this answers is not in the document]
Comment (asg0451) [reply pkg/sql/distsql_plan_changefeed.go:169]: not off the top of my head, here. see my latest comment as well though for thoughts on what we should do here

[the remark this answers is not in the document]
Comment (massimo-ua) [reply pkg/sql/distsql_plan_changefeed.go:169]: @asg0451 My biggest struggle is that I can't figure out how to properly implement the NOT VISIBLE columns check. The planColumns(plan) in this case returns an empty colinfo.ResultColumns list so it can't be used to identify any hidden columns. However, the cdcOptCatalog created above has extraColumns property and it seems like in this specific case there are some extra columns present that can be iterated over and checked with IsHidden() method.
Not sure if the extraColumns should be considered as a proper way to identify this specific use case since those are the columns added only with WithExtraColumn option. If it's possible I'd like to get more specific guidance on this since it's quite challenging to catch all the details

[the remark this answers is not in the document]
Comment (asg0451) [reply pkg/sql/distsql_plan_changefeed.go:169]: can you look at `n.desc.PublicColumns()` inside the `case *scanNode:` block?

[the remark this answers is not in the document]
Comment (massimo-ua) [reply pkg/sql/distsql_plan_changefeed.go]: It works as expected when using n.desc.PublicColumns()

[the remark this answers is not in the document]
Comment (massimo-ua) [reply pkg/sql/distsql_plan_changefeed.go]: But I don't know how trigger the failure

[the remark this answers is not in the document]
Comment (asg0451) [reply pkg/sql/distsql_plan_changefeed.go]: yeah i'm not sure how to construct a situation where that would now fail either tbh. i'll think about it some more but i think that's ok

File: pkg/ccl/changefeedccl/changefeed_test.go (hunk 2 above)
Comment (massimo-ua) [reply pkg/ccl/changefeedccl/changefeed_test.go]: Fixed

File: pkg/sql/distsql_plan_changefeed.go [hunk 5]
```diff
@@ -164,7 +167,9 @@ func PlanCDCExpression(
 		return cdcPlan, errors.AssertionFailedf("expected at least 1 span to scan")
 	}
 
-	if len(presentation) == 0 {
+	// if there are no result columns and public columns list is empty,
```
Comment (asg0451) [inline pkg/sql/distsql_plan_changefeed.go:170]: nit: capitalize

File: pkg/ccl/changefeedccl/changefeed_test.go [hunk 6]
```diff
@@ -10774,3 +10774,27 @@ func assertReasonableMVCCTimestamp(t *testing.T, ts string) {
 	now := timeutil.Now()
 	require.GreaterOrEqual(t, epochNanos, now.Add(-1*time.Hour).UnixNano())
 }
+
+// TestChangefeedAsSelectForEmptyTable verifies that a changefeed with the diff option
```
Comment (asg0451) [inline pkg/ccl/changefeedccl/changefeed_test.go:10778]: what does this have to do with diff?

File: pkg/sql/distsql_plan_changefeed.go [hunk 7]
```diff
@@ -164,7 +167,9 @@ func PlanCDCExpression(
...
+	// it might be a bug.
+	if len(presentation) == 0 && !hasPublicColumns {
```
Comment (asg0451) [inline pkg/sql/distsql_plan_changefeed.go:172]: can you clarify the comment as to why this is ok? something like "even if the SELECTed columns would be empty, as long as the scan node has public columns, we'll still get at least a key out of the changefeed"

also i'm still a little worried about losing protection against bugs here. if the root node is something unexpected, this new condition would not error, right? this can't happen today but..

Comment (massimo-ua) [reply pkg/sql/distsql_plan_changefeed.go:172]: Would you like to narrow down the condition to scanNode only?

File: pkg/ccl/changefeedccl/changefeed_test.go (hunk 6 above)
Comment (massimo-ua) [reply pkg/ccl/changefeedccl/changefeed_test.go:10778]: My bad. I forgot to fix this part of a comment after the recent changes when changefeed statement was updated
Fixed

File: pkg/sql/distsql_plan_changefeed.go (hunk 5 above)
Comment (massimo-ua) [reply pkg/sql/distsql_plan_changefeed.go:170]: Fixed

File: pkg/sql/distsql_plan_changefeed.go (hunk 7 above)
Comment (asg0451) [reply pkg/sql/distsql_plan_changefeed.go:174]: Yeah but the scan node isnt necessarily the root node -- that's why the plan walk is implemented the way it is. take these as examples:

```
root@localhost:26257/defaultdb> explain select * from t where a = 'a';
                                      info
---------------------------------------------------------------------------------
  distribution: local
  vectorized: false

  • filter
  │ estimated row count: 0
  │ filter: a = 'a'
  │
  └── • scan
        estimated row count: 2 (100% of the table; stats collected 2 hours ago)
        table: t@t_pkey
        spans: FULL SCAN

root@localhost:26257/defaultdb> explain select *, 1+1 from t where a = 'a';

                                        info
-------------------------------------------------------------------------------------
  distribution: local
  vectorized: false

  • render
  │
  └── • filter
      │ estimated row count: 0
      │ filter: a = 'a'
      │
      └── • scan
            estimated row count: 2 (100% of the table; stats collected 2 hours ago)
            table: t@t_pkey
            spans: FULL SCAN
```

Comment (massimo-ua) [reply pkg/sql/distsql_plan_changefeed.go:174]: So, the suggestion is to add a few more test cases and verify that they will work correctly for other more complex queries, right?

**Comment by mgartner** [comment]
@asg0451 and I talked about this a bit last week. IMO it should be a user error if the `SELECT` statement provided by the user yields zero columns. If some user actually wants to have a changefeed for the hidden `rowid` column of a zero-column table, then they can be explicit about it: `CREATE CHANGEFEED ... SELECT rowid ...`. The nice thing about this would be that the semantics of `SELECT *` are consistent with SQL.

**Comment by massimo-ua** [comment]
> @asg0451 and I talked about this a bit last week. IMO it should be a user error if the `SELECT` statement provided by the user yields zero columns. If some user actually wants to have a changefeed for the hidden `rowid` column of a zero-column table, then they can be explicit about it: `CREATE CHANGEFEED ... SELECT rowid ...`. The nice thing about this would be that the semantics of `SELECT *` are consistent with SQL.

So the suggestion is to revert the changes to an initial state and replace the `errors.AssertionFailedf("unable to determine result columns")` with something like that
```
  errors.WithHintf(
    errors.New("SELECT yields no columns"),
    "Specify at least one column in your SELECT statement or use SELECT rowid if you need a changefeed for the hidden rowid column of a zero-column table."
  )
```
Does it look ok to you?

**Comment by massimo-ua** [comment]
I've made a change to replace generic error with user error

**Comment by mgartner** [comment]
Let's make sure @asg0451 agrees with the approach I suggested [here](https://github.com/cockroachdb/cockroach/pull/142068#issuecomment-2743562158).

**Review by asg0451 — APPROVED** [review]

**Comment by asg0451** [comment]
LGTM! Thanks @massimo-ua for your contribution (and your patience 😉)

**Comment by asg0451** [comment]
@massimo-ua can you look into why the extended ci failed for the new test under `--stress` before merging?

**Comment by massimo-ua** [comment]
> @massimo-ua can you look into why the extended ci failed for the new test under `--stress` before merging?

The test is flacky. Under some circumstances, execution doesn't reach [this check](https://github.com/cockroachdb/cockroach/pull/142068/files#diff-736c119b9b7287b3a07115e6497844c61f0aec06aefc21485d9666f7ba27240bR136) and statement returns no error

**Comment by asg0451** [comment]
@massimo-ua looks like the test now times out in extended ci

**Comment by massimo-ua** [comment]
> @massimo-ua looks like the test now times out in extended ci

Fixed
