### PR TITLE
pgwire: validate binary numeric digits

### LINKED ISSUE #166641: pgwire: slice bounds panic in binary numeric decoding allows remote DoS
## Summary

The binary numeric decoder in `DecodeDatum` does not validate the `Weight` header field from the pgwire protocol. A crafted binary numeric payload with a very negative `Weight` value (e.g., -3) and small `Ndigits` (e.g., 1) causes the `overScale` variable to exceed the length of the `decDigits` slice, resulting in a runtime panic at the slice operation `decDigits[:len(decDigits)-int(overScale)]`. Since the pgwire connection goroutine has no `recover` handler in production, this crashes the CockroachDB process. Any authenticated client can trigger this via a binary-format Bind message or COPY BINARY.

## Affected code

- `pkg/sql/pgwire/pgwirebase/encoding.go:668-670` -- `overScale` computation and unchecked slice truncation
- `pkg/sql/pgwire/pgwirebase/encoding.go:599-621` -- missing validation of digit values (secondary: data corruption risk)

## Reproduction

This bug requires sending a crafted binary-format parameter via the pgwire protocol. It cannot be reproduced via `cockroach sql` (which uses text format). A unit test sketch is provided below.

### Unit test sketch

```
func TestDecodeBinaryNumericPanic(t *testing.T):
    // Encode: Ndigits=1, Weight=-3, Sign=0x0000 (positive), Dscale=0, digit=1
    payload := []byte{
        0x00, 0x01, // Ndigits = 1
        0xFF, 0xFD, // Weight = -3
        0x00, 0x00, // Sign = positive
        0x00, 0x00, // Dscale = 0
        0x00, 0x01, // digit[0] = 1
    }

    require.NotPanics(t, func() {
        _, err := pgwirebase.DecodeDatum(
            ctx, &evalCtx, types.Decimal,
            pgwirebase.FormatBinary, payload, &da,
        )
        // Should return an error, not panic
        require.Error(t, err)
    })
```

Also test digit validation:
```
func TestDecodeBinaryNumericInvalidDigit(t *testing.T):
    // Encode: Ndigits=1, Weight=0, Sign=0, Dscale=0, digit=-1 (0xFFFF)
    payload := []byte{
        0x00, 0x01, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
        0xFF, 0xFF, // digit[0] = -1 (invalid)
    }
    _, err := DecodeDatum(ctx, &evalCtx, types.Decimal, FormatBinary, payload, &da)
    require.Error(t, err) // Currently silently returns wrong value
```

## Suggested fix direction

1. Before the slice truncation at line 670, add a bounds check:
   ```go
   if int(overScale) > len(decDigits) {
       return nil, pgerror.Newf(pgcode.InvalidBinaryRepresentation,
           "invalid numeric: weight %d is inconsistent with ndigits %d and dscale %d",
           alloc.pgNum.Weight, alloc.pgNum.Ndigits, alloc.pgNum.Dscale)
   }
   ```

2. Add digit value validation after `binary.Read` at line 599:
   ```go
   if alloc.i16 < 0 || alloc.i16 > 9999 {
       return nil, pgerror.Newf(pgcode.InvalidBinaryRepresentation,
           "invalid numeric digit: %d", alloc.i16)
   }
   ```

3. Consider performing the `overScale` computation in `int` rather than `int16` to avoid overflow on extreme `Weight` values.

_This issue was found via automated deep static analysis._

Jira issue: CRDB-62047

### PR DESCRIPTION
**Pull request by officialasishkumar**
Validate binary numeric headers and base-10000 digit values before
constructing the decimal string. Malformed inputs now return an invalid
binary representation error instead of panicking or accepting invalid digit
values.

Fixes #166641

Release note (bug fix): Fixed a bug that could cause malformed binary
numeric values sent over pgwire to trigger an internal panic instead of
returning an invalid binary representation error.

Tests:
- `./dev test pkg/sql/pgwire -f TestInvalidBinaryNumericEncodings -v`
- `./dev test pkg/sql/pgwire -f TestExoticNumericEncodings -v`

### CODE REVIEW

File: pkg/sql/pgwire/pgwirebase/encoding.go [hunk 1]
```diff
@@ -599,6 +603,9 @@ func DecodeDatum(
 					if err := binary.Read(r, binary.BigEndian, &alloc.i16); err != nil {
 						return nil, err
 					}
+					if alloc.i16 < 0 || alloc.i16 >= 10000 {
```
Comment (rafiss) [inline pkg/sql/pgwire/pgwirebase/encoding.go]: instead of an unnamed constant `10000`, can you define PGDecBase alongside PGDecDigits: https://github.com/cockroachdb/cockroach/blob/6486a17d05468bd0861d8234f3c42d7eceaf9ef4/pkg/sql/pgwire/pgwirebase/encoding.go#L1028

File: pkg/sql/pgwire/encoding_test.go [hunk 2]
```diff
@@ -350,6 +352,50 @@ func TestExoticNumericEncodings(t *testing.T) {
...
+	defer leaktest.AfterTest(t)()
+	defer log.Scope(t).Close(t)
+
+	testCases := []struct {
+		name     string
+		encoding []byte
+	}{
+		{
+			name:     "negative digit count",
+			encoding: []byte{0xff, 0xff, 0, 0, 0, 0, 0, 0},
```
Comment (rafiss) [inline pkg/sql/pgwire/encoding_test.go:368]: Could you include a comment that says what each byte in the slices means?

e.g. above each test case, you could have a comment like `// Ndigits=-1, Weight=0, Sign=Pos, Dscale=0` so a future debugger doesn't have to reverse-engineer the PGNumeric layout.

**Review by rafiss — CHANGES_REQUESTED** [review]
thanks for your contribution!

I had small comments, and one more idea for an additional test: A happy-path regression for int-promotion in encoding_test.go. Only rejection paths are covered right now. A future change that removes the int widening would silently regress decoding of extreme-but-legal weights without breaking any new test. Add a positive case to `TestExoticNumericEncodings` exercising a weight that would have overflowed the old int16 arithmetic.

File: pkg/sql/pgwire/pgwirebase/encoding.go (hunk 1 above)
Comment (officialasishkumar) [reply pkg/sql/pgwire/pgwirebase/encoding.go]: Defined `PGDecBase` next to `PGDecDigits` and use it for binary numeric digit validation. Commit: 51437ad124

File: pkg/sql/pgwire/encoding_test.go (hunk 2 above)
Comment (officialasishkumar) [reply pkg/sql/pgwire/encoding_test.go:368]: Added byte-layout comments to the invalid binary numeric cases. Commit: 51437ad124

**Comment by officialasishkumar** [comment]
Addressed the review-body test request as well by adding a valid upper-bound binary numeric digit case (`9999`) in `TestExoticNumericEncodings`. Commit: 51437ad124. I tried `go test ./pkg/sql/pgwire -run 'TestExoticNumericEncodings|TestInvalidBinaryNumericEncodings'`, but the plain Go test path fails in this checkout because generated protobuf packages are missing; Cockroach appears to require the repo dev/Bazel test flow for this package.

**Comment by rafiss** [comment]
please read the contributing guide: https://github.com/cockroachdb/cockroach/blob/master/CONTRIBUTING.md

`go test ...` will not work. use `./dev test --help` to learn about how to run tests locally.

**Comment by rafiss** [comment]
Thanks for the contribution! I've taken over this PR with some small adjustments (squashed commits, switched to require.* assertions). Superseded by #169086.

**Review by rafiss — APPROVED** [review]
actually, i just made the final fixes here. thanks for your PR!

/trunk merge
