### PR TITLE
bench/rttanalysis: allow roundtrips to be off by 1

### LINKED ISSUE #73884: bench/rttanalysis: TestBenchmarkExpectation failed
bench/rttanalysis.TestBenchmarkExpectation [failed](https://teamcity.cockroachdb.com/viewLog.html?buildId=3922786&tab=buildLog) with [artifacts](https://teamcity.cockroachdb.com/viewLog.html?buildId=3922786&tab=artifacts#/) on master @ [9df83c67afab064b5177e2663ed42b8fbeef8ba3](https://github.com/cockroachdb/cockroach/commits/9df83c67afab064b5177e2663ed42b8fbeef8ba3):

```
--- FAIL: TestBenchmarkExpectation (25.62s)
=== RUN   TestBenchmarkExpectation/AlterTableDropColumn/alter_table_drop_1_column
=== CONT  TestBenchmarkExpectation/AlterTableDropColumn/alter_table_drop_1_column
    rtt_analysis_bench.go:152: AlterTableDropColumn/alter_table_drop_1_column: got 22, expected 21
    rtt_analysis_bench.go:158: wrote jaeger trace to /go/src/github.com/cockroachdb/cockroach/artifacts/logTestBenchmarkExpectation420642434/AlterTableDropColumn_alter_table_drop_1_column.jaeger.json
        --- FAIL: TestBenchmarkExpectation/AlterTableDropColumn/alter_table_drop_1_column (9.26s)
=== RUN   TestBenchmarkExpectation/AlterTableDropColumn
    --- FAIL: TestBenchmarkExpectation/AlterTableDropColumn (18.55s)
```
<details><summary>Help</summary>
<p>
See also: [How To Investigate a Go Test Failure \(internal\)](https://cockroachlabs.atlassian.net/l/c/HgfXfJgM)Parameters in this failure:

- GOFLAGS=-json
</p>
</details>
<details><summary>Same failure on other branches</summary>
<p>

- #73168 bench/rttanalysis: TestBenchmarkExpectation failed [C-test-failure O-robot branch-release-21.2]
</p>
</details>
/cc @cockroachdb/sql-schema
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*TestBenchmarkExpectation.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)
</sub>

### PR DESCRIPTION
**Pull request by ajwerner**
If we don't have a range, let the currently estimate be wrong by 1.
We mostly care about the ballpark and the growth rate. I'm sick of
these flakes.

Fixes #73884.

Release note: None

### CODE REVIEW

**Review by chengxiong-ruan — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/74111)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rafiss and @RichardJCai)

File: pkg/bench/rttanalysis/validate_benchmark_data.go [hunk 1]
```diff
@@ -319,7 +319,9 @@ func (b benchmarkExpectations) find(name string) (benchmarkExpectation, bool) {
 }
 
 func (e benchmarkExpectation) matches(roundTrips int) bool {
-	return e.min <= roundTrips && roundTrips <= e.max
+	return (e.min <= roundTrips && roundTrips <= e.max) ||
+		e.min == e.max &&
```
Comment (rafiss) [inline pkg/bench/rttanalysis/validate_benchmark_data.go:323]: would
```
(e.min <= roundTrips && roundTrips <= e.max) || (e.min == e.max && (roundTrips == e.min-1 || roundTrips == e.min+1))
```

be even more clear?

**Review by rafiss — APPROVED** [review]

File: pkg/bench/rttanalysis/validate_benchmark_data.go (hunk 1 above)
Comment (ajwerner) [reply pkg/bench/rttanalysis/validate_benchmark_data.go]: I unwrapped it one level and added commentary

**Review by stevendanna — APPROVED** [review]
yes please
