### PR TITLE
sql: fix pg_catalog.pg_constraint's confkey column

### LINKED ISSUE #31545: SQL: Conkey and confkey values in pg_constraints have different number of elements
Dbeaver identified a potential CRDB bug in https://github.com/dbeaver/dbeaver/issues/4386#issuecomment-430512539:

`This happens because conkey and confkey values in pg_constraints have different number of elements.
In standard PG they always have equal size.

Looks like a bug in CC - the value in conkey seems to be equal to the number of columns in table's primary key. This happens only if foreign key columns are also part of primary key (like in stock or order_line tables).`

### PR DESCRIPTION
**Pull request by BramGruneir**
Prior to this patch, all columns in the index were included instead of only the
ones being used in the foreign key reference.

Fixes #31545.

Release note (bug fix): Fix pg_catalog.pg_constraint's confkey column from
including columns that were not involved in the foreign key reference.

### CODE REVIEW

**Comment by BramGruneir** [comment]
At @knz's suggestion, I've added a guard to make sure we don't have an out of bounds error.

**Comment by knz** [comment]
Thanks for this.
Don't you want to fail with an error if the prefix Len is too large? This would suggest an inconsistency.

LGTM otherwise
-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

File: pkg/sql/pg_catalog.go [hunk 1]
```diff
@@ -680,7 +680,11 @@ CREATE TABLE pg_catalog.pg_constraint (
 					confupdtype = fkActionNone
 					confdeltype = fkActionNone
 					confmatchtype = fkMatchTypeSimple
-					if conkey, err = colIDArrayToDatum(con.Index.ColumnIDs); err != nil {
+					columnIDs := con.Index.ColumnIDs
+					if con.FK.SharedPrefixLen < int32(len(columnIDs)) {
```
Comment (dt) [inline pkg/sql/pg_catalog.go]: I thought this check was usually just `!= 0`? In very old table descs, it might be unset, and thus zero, so `< len`  could get us in trouble.

Comment (BramGruneir) [reply pkg/sql/pg_catalog.go]: Can you point to an example?  Having to check 0 as well is a little strange.

Comment (BramGruneir) [reply pkg/sql/pg_catalog.go]: Ok, I think this is ready to go.  PTAL

I added a comment on `structured.proto` to reflect the need to check for >0 to use the `sharedprefixlen`.

**Review by dt — APPROVED** [review]
