### PR TITLE
roachtest: deflake activerecord test

### LINKED ISSUE #136460: roachtest: activerecord failed
**Note:** This build has runtime assertions enabled. If the same failure was hit in a run without assertions enabled, there should be a similar failure without this message. If there isn&#39;t one, then this failure is likely due to an assertion violation or (assertion) timeout.

roachtest.activerecord [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/17990793?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/17990793?buildTab=artifacts#/activerecord) on release-24.2 @ [8a1ed05f5ef63eab776779a8625b328e06cc6512](https://github.com/cockroachdb/cockroach/commits/8a1ed05f5ef63eab776779a8625b328e06cc6512):

```
(orm_helpers.go:224).summarizeFailed: 
Tests run on Cockroach v24.2.6-dev-8a1ed05f5ef63eab776779a8625b328e06cc6512
Tests run against activerecord 7.2.1
8487 Total Tests Run
8463 tests passed
24 tests failed
60 tests skipped
5 tests ignored
0 tests passed unexpectedly
1 test failed unexpectedly
0 tests expected failed but skipped
0 tests expected failed but not run
---
--- PASS: SerializedAttributeTestWithYamlSafeLoad#test_unexpected_serialized_type (expected)
--- PASS: SerializedAttributeTest#test_unexpected_serialized_type (expected)
--- FAIL: CockroachDB::FixturesTest#test_create_fixtures (unexpected)
For a full summary look at the activerecord artifacts 
An updated blocklist (activeRecordBlocklist) is available in the artifacts' activerecord log
test artifacts and logs in: /artifacts/activerecord/run_1
```

Parameters:
 - <code>arch=amd64</code>
 - <code>cloud=gce</code>
 - <code>coverageBuild=false</code>
 - <code>cpu=4</code>
 - <code>encrypted=false</code>
 - <code>fs=ext4</code>
 - <code>localSSD=true</code>
 - <code>runtimeAssertionsBuild=true</code>
 - <code>ssd=0</code>
<details><summary>Help</summary>
<p>

See: [roachtest README](https://github.com/cockroachdb/cockroach/blob/master/pkg/cmd/roachtest/README.md)

See: [How To Investigate \(internal\)](https://cockroachlabs.atlassian.net/l/c/SSSBr8c7)

See: [Grafana](https://go.crdb.dev/roachtest-grafana/teamcity-17990793/activerecord/1733122259794/1733130295810)

</p>
</details>
<details><summary>Same failure on other branches</summary>
<p>

- #136066 roachtest: activerecord failed [PostGISTest#test_point_to_json] [C-test-failure O-roachtest O-robot P-2 T-sql-foundations branch-master]
</p>
</details>
/cc @cockroachdb/sql-foundations
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*activerecord.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/bazci/githubpost/issues)

</sub>

Jira issue: CRDB-45079

### PR DESCRIPTION
**Pull request by fqazi**
Previously, the active record test had a test flake on CockroachDB::FixturesTest#test_create_fixtures. This patch adds that test on the ignore list.

Fixes: #136460

Release note: None

### CODE REVIEW

File: pkg/cmd/roachtest/tests/activerecord_blocklist.go [hunk 1]
```diff
@@ -27,4 +27,5 @@ var activeRecordIgnoreList = blocklist{
 	`TestAutosaveAssociationOnAHasAndBelongsToManyAssociation#test_should_not_save_and_return_false_if_a_callback_cancelled_saving_in_either_create_or_update`: "flaky",
 	`TestAutosaveAssociationOnAHasAndBelongsToManyAssociation#test_should_not_update_children_when_parent_creation_with_no_reason`:                             "flaky",
 	`TestAutosaveAssociationOnAHasAndBelongsToManyAssociation#test_should_update_children_when_autosave_is_true_and_parent_is_new_but_child_is_not`:            "flaky",
+	`CockroachDB::FixturesTest#test_create_fixtures`:                                                                                                           "flaky",
```
Comment (rafiss) [inline pkg/cmd/roachtest/tests/activerecord_blocklist.go:30]: super nit: this is normally alphabetically sorted, but don't think it matters much when the list is small.

**Review by rafiss — APPROVED** [review]

**Review by fqazi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/136688)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @rafiss, @srosenberg, and @vidit-bhat)

**Comment by fqazi** [comment]
@rafiss TFTR!

bors r+
