### PR TITLE
sql/schemachanger: block concurrent declarative schema changes

### LINKED ISSUE #74021: roachtest: knex failed
See: https://github.com/cockroachdb/cockroach/issues/74021#issuecomment-1015851607

tl;dr:
* regression in e89093f causing `DROP CONSTRAINT ... PRIMARY KEY` and `ADD CONSTRAINT ... PRIMARY KEY` in the same txn to fail. repro:
```
BEGIN;
create table t (a int, b int, constraint "bob" primary key (a, b));
alter table t drop constraint "bob";
alter table t add constraint "bob" primary key (a, b);
COMMIT;
```

* `TransactionRetryWithProtoRefreshError` applying a migration, regression from v21.2. might be related to span config work. git bisect points to
```
commit 610aa0441cbc57031c076689f8bdf4957122b395
Author: irfan sharif <irfanmahmoudsharif@gmail.com>
Date:   Tue Dec 21 22:26:41 2021 -0500

    *: enable span configs by default

    We were previously using opt-in flags to enable span configs; this
    commit flips it into opt-out ones (DisableSpanConfigs and
    COCKROACH_DISABLE_SPAN_CONFIGS). This has the following effects:
    a. fresh crdb nodes/clusters run with span configs enabled.
    b. our entire test suite runs using the span configs infrastructure, save
       for a select few written:
       (i)  with the gossipped system config span in mind;
       (ii) using legacy testing harnesses that prevent injection of
            spanconfig dependencies due to circular imports.

    We also introduce a more minified form of the opt-out testing flag:
    UseSystemConfigSpanForQueues. Using the minified form still enables the
    SQL-side of span configs to run (Reconciler, SQLWatcher, SQLTranslator)
    but defaults to using the system config span down in KV.

    Release note: None
```

----

roachtest.knex [failed](https://teamcity.cockroachdb.com/viewLog.html?buildId=3948712&tab=buildLog) with [artifacts](https://teamcity.cockroachdb.com/viewLog.html?buildId=3948712&tab=artifacts#/knex) on master @ [3f95a4bd83cce2952a12497de82692866b4da659](https://github.com/cockroachdb/cockroach/commits/3f95a4bd83cce2952a12497de82692866b4da659):

```
The test failed on branch=master, cloud=gce:
test artifacts and logs in: /home/agent/work/.go/src/github.com/cockroachdb/cockroach/artifacts/knex/run_1
	knex.go:116,knex.go:126,test_runner.go:779: /home/agent/work/.go/src/github.com/cockroachdb/cockroach/bin/roachprod run teamcity-3948712-1639818405-40-n1cpu4:1 -- cd /mnt/data1/knex/ && DB='cockroachdb' npm test: exit status 20
		(1) attached stack trace
		  -- stack trace:
		  | main.execCmdWithBuffer
		  | 	/home/agent/work/.go/src/github.com/cockroachdb/cockroach/pkg/cmd/roachtest/cluster.go:550
		  | main.(*clusterImpl).RunWithBuffer
		  | 	/home/agent/work/.go/src/github.com/cockroachdb/cockroach/pkg/cmd/roachtest/cluster.go:2079
		  | github.com/cockroachdb/cockroach/pkg/cmd/roachtest/tests.registerKnex.func1
		  | 	/home/agent/work/.go/src/github.com/cockroachdb/cockroach/pkg/cmd/roachtest/tests/knex.go:107
		  | github.com/cockroachdb/cockroach/pkg/cmd/roachtest/tests.registerKnex.func2
		  | 	/home/agent/work/.go/src/github.com/cockroachdb/cockroach/pkg/cmd/roachtest/tests/knex.go:126
		  | main.(*testRunner).runTest.func2
		  | 	/home/agent/work/.go/src/github.com/cockroachdb/cockroach/pkg/cmd/roachtest/test_runner.go:779
		  | runtime.goexit
		  | 	/usr/local/go/src/runtime/asm_amd64.s:1581
		Wraps: (2) /home/agent/work/.go/src/github.com/cockroachdb/cockroach/bin/roachprod run teamcity-3948712-1639818405-40-n1cpu4:1 -- cd /mnt/data1/knex/ && DB='cockroachdb' npm test
		Wraps: (3) exit status 20
		Error types: (1) *withstack.withStack (2) *errutil.withPrefix (3) *exec.ExitError
```
<details><summary>Help</summary>
<p>

See: [roachtest README](https://github.com/cockroachdb/cockroach/blob/master/pkg/cmd/roachtest/README.md)

See: [How To Investigate \(internal\)](https://cockroachlabs.atlassian.net/l/c/SSSBr8c7)

</p>
</details>
/cc @cockroachdb/sql-experience
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*knex.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)
</sub>

Jira issue: CRDB-11861

### LINKED ISSUE #77172: schemachanger: schema changes in knex test cause assertion error in SetJobStateOnDescriptor
This is causing https://github.com/cockroachdb/cockroach/issues/74021

I haven't yet figured out which series of commands is resulting in these errors, but it can be repro'd with the `knex` roachtest. v21.2 passes the test, but `master` currently has failures.

Errors are in this gist: https://gist.github.com/rafiss/1e44cf546d03565ed43409f1a2ec2d7b

And an example below:
```
Unhandled rejection: error: drop schema if exists "schema_2" - internal error: error executing PreCommitPhase stage 1 of 1 with 7 MutationType ops: unexpected schema change job ID 740454782435098625 on table 104, expected 0
    at Parser.parseErrorMessage (/mnt/data1/knex/node_modules/pg-protocol/src/parser.ts:369:69)
    at Parser.handlePacket (/mnt/data1/knex/node_modules/pg-protocol/src/parser.ts:188:21)
    at Parser.parse (/mnt/data1/knex/node_modules/pg-protocol/src/parser.ts:103:30)
    at Socket.<anonymous> (/mnt/data1/knex/node_modules/pg-protocol/src/index.ts:7:48)
    at Socket.emit (events.js:314:20)
    at addChunk (_stream_readable.js:297:12)
    at readableAddChunk (_stream_readable.js:272:9)
    at Socket.Readable.push (_stream_readable.js:213:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:188:23) {
  length: 5939,
  severity: 'ERROR',
  code: 'XX000',
  detail: 'stages: https://cockroachdb.github.io/scplan/viz.html#H4sIAAAAAAAA/+xa227bOBO+jp9C8A/8F0WTWicf2kRAGqdYF41jxAm2QFAYtMTaQmVSICkX7aJAXqt9nDzJgpJ1tFRRltwm3dwEjGaG4nzfiBzO2LIXBLhLSfqndUC9efCP6XiUQTKjMn+c81xVfMGBA+bQOWlPMGVneLWy2RijK7iGhNlzB06WgEKJMrCAkizhj5IsfbbZUtKlC48BZmN0/cWFEnZp+xWfDanq7WbGzsvT19Pz8XX7w0aihRI5K9FDiZKVdEOJmpX0QomWlfRDiZ6VDEJJNyPROqGkl5XIt00h9FKyvNXqS/s5XQIXnrRdbCPWfk7ZFweetG20tunmra2Dg2+5pCkZ0ggMVlS0iF4RTUohTUohTUohTUohTUohTUqCpuHV5WRyPoxEhTyphTypMU/VQWmAGTVFDGWAwRVELMRbu/2IEaP2V3jSHrSfB2rHxwzMHSiZDqD0pI09BknbOGbEOGZW+HQJgcUfU9OdH03DeY9fMMs4fuGr+upGei7/n2gu4wpawGTQytgzy+DQS9Ozv84vTqXRG+n8/Wh6PZXu777//3+q9sr/c3/34+j+7js1l3AFZsr93Y/tt4tOHE7ykxmuwSJvkoTFC987I37SCh+1jJBChBEs/ZpSnDFAFjAiTK9N2DOfsTFYQeoCE1ZkzAIMzAGFIysCQ+5o25NYkJrEdhkmCU2lO9jWRGAFI40cHiqiiroNIXT5GUFSFR1hr3E8O7MMgjGr4XKvIZdvKCQTYq9tBy4g3ZvvbuYVXG9by6OQjJOxAayVjWqg1H9cKG3573pzxzZrADB4XADsGCY1vyW50xBKU38rq4hOsP8VIlPZGblRZyaAVD/jXd9oKHhuNA2A0igAPIGrjoCZtGKWMZu5DjDhEjsWJLONdDbbPxhRcl0xrYyzxwUMEhEka3GiPrl5/W50FpggWY/z9LSgG6fpaUEvztLTgn6cpKcFgzhHv34/nqXydKR04jQ9ZabIcZaeFLS4k60DpB8aCb8YljapfIiMBegSWr4N6nJdXUy3x3W7Yrp9rtsT0x1w3b6YrtzhygNBZfnQSMBYoqxwZVlMWVEPDX4XD0WYsUikcZGWK+LMqHquiBOhdnNFHHe1lyviMKv1E4LbD9TE7tGlW3FH6ERf9DN/gnd4cb4Ot4hWqfmpx5aY2F/9y2I01U9Nbqoek6HhuZO+P/30Lckzr+mjrniJ+789lt/9NhbX/mXtAjLAL0qCoGGPmHCD82gYn485C/Lmf2PyqUCpEKBgVdwbL86lgq9UxFzOROsQOpDBYZTICUZtbJBYf2XSE2dc8CnzXVAd5H3lKt/ztE6uiO9wWv3sqKkN4Aqu8Bq+xXM/5N4QvGoG3twc6y2eJ1R6WkfTtV5f0fq9jqoPOvouMbEvB3JvBk04oGQcuHEtwOAmzVsCtIDkLZ4LLn1ExxidAWRChwuiqRnxcgostZZf+kHI/hH7cEJ7ClkYFpdoj1E9QjazgWN/LYPfX4rY1vwrD9pmo6LoO90DG7mf6GNn48wj/NoanJmJCkT6bWvgJJaXOFBr/ru50IhoNxZULCzJO3ANAs+DVoGI70FC586P4gjxJ5ilc7PyCNvO5f7LDYTsE8FM7wqgT0K0dbJ5ZOpgVKORFo30aNSNw0p8ZdWCKbARjJxNAj0hmGGx4Mn0QMrUH0DroxjeP+LKYf1S+i9TLZjf0td54rNBPvPaEs0Ru6+m1VMIPJoQ2KEj98Tuo2F3T+3GpwhoMAJ+T335iagdiUr2i8ss9tsmfiK3cXLPMl3th9EC//OJFvZbuPR9RuDupe9fWZRLlh+FKgnR3iEQOGzXitmOlbKqlbE/utRVK663OiDaoYEU9cF0QIYE2IlaexT65ZxXrFBFp2dJq0S8jD9uoEJVzpfO+dL8YZcPdX/Y48OuP+zzYc8fDvjw4fxy4wKQTzGcp3RIsOtCS5BfbtloM7zD0an/O89m29pbyWA5MFUyx0k6cyyJ/WAxdUAXoEE+NJBa/4ek+6AhmbYJtGNqo5XBpvWt9W8AAAD//2d9W6wYNgAA\n' +
    '--\n' +
    'dependencies: https://cockroachdb.github.io/scplan/viz.html#H4sIAAAAAAAA/+RY3W7aSBS+xk9heaW9qNIEOwTCFiylgdUiNQQFoq0UVWjwnIJV47FmhqzaVaS8Vvs4eZJqxthjDIQBO1Kq3iAx58dzvm9+vjnYn1IUzUzzf6PCFpP4jxcsGAc6ZrYY3jB+KscrAZpA0LYYRxzmEHJmvRPDYe3uMwk5879B22paR7Fbq8XRJADTCxBjbYssOFDLbXHqtjhORmeAsBhmXjQ5HiZ5Wyccu60T6Srd3dVc8k+ay70BjDwOOBfPsdu5uR6Yw8t/ulcXZu9vs/uxNxwNzafH73/+cVp7J3+eHn8cPz1+Z94M5mjsPD3+WP+6buIkyTMZRmi6KUkm4kRW56oRIxky3CM2QxG0rZCEYH2S4BuVysNGzpwVzjiiU0gJOytM2BvJWB/NgUXIgz0Zw4ijCWLQwykYdrW2ngQD86gfcUIznk69ue4ZojmkHht42BPVsF4SQtf/hUD3RUe7aqKyc+xSQniBkhsllXzLgA6of+8HMAX2YrVHuU8Iv3WvBQPaz64NhOd+WACl818LpbX6o8Uk8L0CADR/LQAOXCYF95JdLQmloTzK9kQnPv+2IrN3MXapxQwQ3f+Oj2RQR/PeKBsAp1QALsn8AJXjZaM4dsfjKEAezEiAgY6X1vH4pcFY6o2lrMAQxZoitE/vlmPVvy7eD7v9URwQ2jVlGNy+/9C7TAxnicHORdSVYTWikRicXMS5MqxGNBPD6WqEU1WGlQjHTgy1XISjDKsRaeVnuYgzZRBab9DtJJaasow+9sc5a1p/PZewoQyrU0jrb+QimsqwCszpW1dM0CMBoW2LAk6WteAUQgwhNyGQmtWkMCf3KDAn8JlQMNXha2JKopTnt65YBUV3yt0n5pHo+Drac39U0/X9RiboUOSHnXSq6elu7MyUU7W73NNDqfP8oaTmkvHceGf19xWzOiOZbZ3sv9KXQF0sgeKPi7KWQJ/w3jyKKwCsyX439h99jbIcbJDyB2HeKB3zc4F5ce3+OjHfKhIPAr9ZNvhOVYBfXBH/BuA7dungOyJjcW36O4Avj/rXczd/INPufSJmd4N0seAzQv1viPsk1LuUb/d90OUI0ftK9nVW9qNs+xRfvs+5u0u5jBjJtuIVcIQR1wRiSBbUgyXOWdG0YUKLyb+EftnitBWgeFaimoV69ce6WCfczitJCICDkm+aq1ZD7x20l2vxQfpa9vIVol9UqResQ0kUaZ9/IrJceOql3zNSsxVvCJcF+I2YNKz1UnZjnW286PnqPm3iyRThUYfZ89KZlYKweEf3JZjNNol2U1ucgDzcRuXBqBiVUCgH1cLhxFz2F44Y/xpA28KIzQBLQEP5/Kvr+YpNpdo2z/tK4qt6vpJSR8/XFvLd0SzOlgK2oekstWlTy9l4MH4GAAD//xN1vXqWHQAAstack trace:\n' +
    'github.com/cockroachdb/cockroach/pkg/sql/schemachanger/scexec/scmutationexec/schema_change_job.go:53: SetJobStateOnDescriptor()\n' +
    'github.com/cockroachdb/cockroach/bazel-out/k8-opt/bin/pkg/sql/schemachanger/scop/mutation_visitor_generated.go:316: Visit()\n' +
    'github.com/cockroachdb/cockroach/pkg/sql/schemachanger/scexec/exec_mutation.go:39: executeDescriptorMutationOps()\n' +
    'github.com/cockroachdb/cockroach/pkg/sql/schemachanger/scexec/executor.go:32: ExecuteStage()\n' +
    'github.com/cockroachdb/cockroach/pkg/sql/schemachanger/scrun/scrun.go:144: executeStage()\n' +
    'github.com/cockroachdb/cockroach/pkg/sql/schemachanger/scrun/scrun.go:70: runTransactionPhase()\n' +
    'github.com/cockroachdb/cockroach/pkg/sql/schemachanger/scrun/scrun.go:44: RunPreCommitPhase()\n' +
    'github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:3132: runPreCommitStages()\n' +
    'github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:920: commitSQLTransactionInternal()\n' +
    'github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:861: commitSQLTransaction()\n' +
    'github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:2042: handleAutoCommit()\n' +
    'github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:520: func6()\n' +
    'github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:733: execStmtInOpenState()\n' +
    'github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:143: execStmt()\n' +
    'github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:1846: func1()\n' +
    'github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:1850: execCmd()\n' +
    'github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:1779: run()\n' +
    'github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:746: ServeConn()\n' +
    'github.com/cockroachdb/cockroach/pkg/sql/pgwire/conn.go:723: func1()\n' +
    'GOROOT/src/runtime/asm_amd64.s:1581: goexit()\n',
  hint: 'You have encountered an unexpected error.\n' +
    '\n' +
    'Please check the public issue tracker to check whether this problem is\n' +
    'already tracked. If you cannot find it there, please report the error\n' +
    'with details by creating a new issue.\n' +
    '\n' +
    'If you would rather not post publicly, please contact us directly\n' +
    'using the support form.\n' +
    '\n' +
    'We appreciate your feedback.\n',
  position: undefined,
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'schema_change_job.go',
  line: '53',
  routine: 'SetJobStateOnDescriptor'
}
```

Jira issue: CRDB-13446

### LINKED ISSUE #77648: schemachanger: concurrent schema changes are not properly detected
**Describe the problem**

The new schema changer seeks to avoid complexity due to concurrent mutation of descriptors via a simple locking protocol. Unfortunately the detecting of existing locking was not completely implemented and was not checked in a uniform place. This means we don't properly deal with a variety of concurrency-related issues.

The below check is too simplistic. It only applies to tables, and it doesn't detect all of the possible concurrent changes. It needs to apply to all descriptor types and it needs to check whether a job exists. 

https://github.com/cockroachdb/cockroach/blob/5a97a11337dbd3874bea2342a727d8b4500ac224/pkg/sql/catalog/table_elements.go#L792-L800

Also, the place where the call happens is not layered well to prevent all concurrent interactions: 
https://github.com/cockroachdb/cockroach/blob/master/pkg/sql/schemachanger/scbuild/builder_state.go#L279-L288

It should probably happen above `scbuildstmt` in the `scbuild` layer where there's a uniform view of all affected descriptors.

**To Reproduce**

See https://github.com/cockroachdb/cockroach/issues/74021.

**Expected behavior**
We should properly synchronize these schema changes. The handling above throwing the error has some testing.

**Additional context**

There may be some hazards related to mixing of the old and new schema changer when it comes to types and dropping enum members.

We should also test concurrent removals of foreign key back-references. 

Epic: CRDB-2356

Jira issue: CRDB-13695

### PR DESCRIPTION
**Pull request by fqazi**
Fixes: #77648, #77172

Previously, the declarative schema change only blocked
concurrent schema change operations for tables, 
specifically when adding new columns. This was inadequate
because concurrent updates on certain objects like databases
when dropping can lead to issues as well. For example, when
dropping a schema, the database will need to be modified to
remove the dropped schema. To address this, this patch enforces
that only one schema change is allowed for a given schema object
at a time when using the declarative schema changer.

Release justification: low risk and leads to better concurrency
safety guarantees for declarative schema changer by allowing
a single drop along with the set of impacted objects.
Release note: None

### CODE REVIEW

File: pkg/sql/schemachanger/scbuild/internal/scbuildstmt/dependencies.go [hunk 1]
```diff
@@ -75,6 +75,10 @@ type BuilderState interface {
 	// Ensure ensures the presence of the given element in the BuilderState with
 	// the given statuses and metadata.
 	Ensure(current scpb.Status, target scpb.TargetStatus, elem scpb.Element, meta scpb.TargetMetadata)
+
+	// CheckNoConcurrentSchemaChange checks no concurrent schema change exists for
+	// a given descriptor ID.
+	CheckNoConcurrentSchemaChange(descID catid.DescID)
```
Comment (ajwerner) [inline pkg/sql/schemachanger/scbuild/internal/scbuildstmt/dependencies.go:81]: Given we call this `scbuild`, can we remove it from the interface? Do we need any calls to it in `scbuildstmt`?

**Review by ajwerner — COMMENTED** [review]
Nice, thanks for jumping on this so quickly!

**Review by fqazi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/77656)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner)

___
*[pkg/sql/schemachanger/scbuild/internal/scbuildstmt/dependencies.go, line 81 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/77656#-MxrCmml5sPUOHgoj7xf-r1-81:-MxuNAQFDs4FxutU7xKW:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/221e7718d9210fc70d572d3051562ecc38ed12fe/pkg/sql/schemachanger/scbuild/internal/scbuildstmt/dependencies.go#L81)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

Given we call this `scbuild`, can we remove it from the interface? Do we need any calls to it in `scbuildstmt`?
</blockquote></details>

Done.

**Review by ajwerner — COMMENTED** [review]
I wonder if it'd be better to make this a catalog function as it was before and just specialize the logic per descriptor type? What do you think? 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/77656#-:-MxuWUXd-63QDX0eCctg:bwy0mps)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner and @fqazi)

___
*[pkg/sql/schemachanger/screl/scalars.go, line 50 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/77656#-MxuWRwGAU2-FD9B51yu:-MxuWRwGAU2-FD9B51yv:b17emrk) ([raw file](https://github.com/cockroachdb/cockroach/blob/9c695e0b9750d9e924eea7374507da594ca296cf/pkg/sql/schemachanger/screl/scalars.go#L50)):*
> ```Go
> 			//   will be captured by the scpb.SchemaParent target.
> 			if te.DescriptorID == 104 {
> 				fmt.Println("HERE")
> ```

debug code?

**Review by postamar — DISMISSED** [review]
> Reviewed 16 of 21 files at r1, 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/77656)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner and @fqazi)

___
*[-- commits, line 18 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/77656#-MxuRMQh58P_b-3eaSHm):*
or, more simply: you're fixing a correctness bug.
___
*[pkg/sql/catalog/dbdesc/database_desc.go, line 483 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/77656#-MxuQ5Q53htJeq2vOPxP:-MxuQ5Q67GgqQZdFQ6UH:bwdnlis) ([raw file](https://github.com/cockroachdb/cockroach/blob/9c695e0b9750d9e924eea7374507da594ca296cf/pkg/sql/catalog/dbdesc/database_desc.go#L483)):*
> ```Go
> func (desc *immutable) HasConcurrentSchemaChanges() bool {
> 	return desc.DeclarativeSchemaChangerState != nil &&
> 		desc.DeclarativeSchemaChangerState.JobID != catpb.InvalidJobID
> ```

I think this check should remain as it is but, for my own information, is it possible to have a non-nil state with a zero job ID? I was under the impression that if there were no post-commit ops to run, we simply wouldn't set DeclarativeSchemaChangerState at all. I may be wrong.
___
*[pkg/sql/catalog/schemadesc/synthetic_schema_desc.go, line 122 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/77656#-MxuQhpu1VNuBKzfgP4V:-MxuQhpu1VNuBKzfgP4W:bhjm84p) ([raw file](https://github.com/cockroachdb/cockroach/blob/9c695e0b9750d9e924eea7374507da594ca296cf/pkg/sql/catalog/schemadesc/synthetic_schema_desc.go#L122)):*
> ```Go
> func (p synthetic) HasConcurrentSchemaChanges() bool {
> 	log.Fatalf(context.TODO(),
> 		"synthetic descriptor cannot have schema changes")
> ```

If you're going to print a log message at all, you might as well surface more information in it?

FWIW I'd be happy to simply return `false` here. It's not wrong.
___
*[pkg/sql/catalog/typedesc/table_implicit_record_type.go, line 338 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/77656#-MxuR6078IHNKT4l1r8J:-MxuR6078IHNKT4l1r8K:b-gah2r7) ([raw file](https://github.com/cockroachdb/cockroach/blob/9c695e0b9750d9e924eea7374507da594ca296cf/pkg/sql/catalog/typedesc/table_implicit_record_type.go#L338)):*
> ```Go
> // HasConcurrentSchemaChanges implements catalog.Descriptor.
> func (v TableImplicitRecordType) HasConcurrentSchemaChanges() bool {
> 	v.panicNotSupported("HasConcurrentSchemaChanges")
> ```

Same comment as above re. simply returning `false`. I don't feel strongly about this.
___
*[pkg/sql/catalog/typedesc/type_desc.go, line 962 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/77656#-MxuSd_GEwRsYzGUIWeV:-MxuSIOtEk07aEEVlb_a:b-j1909v) ([raw file](https://github.com/cockroachdb/cockroach/blob/9c695e0b9750d9e924eea7374507da594ca296cf/pkg/sql/catalog/typedesc/type_desc.go#L962)):*
> ```Go
> 	// job targets.
> 	for _, t := range desc.DeclarativeSchemaChangerState.Targets {
> 		if t.EnumType != nil &&
> ```

You might want to `switch e := t.Element().(type)` or something like that instead. Also shouldn't you be also checking alias types in addition to enum types?
___
*[pkg/sql/catalog/typedesc/type_desc.go, line 964 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/77656#-MxuSeKj7wDcTmKazGLe:-MxuSeKj7wDcTmKazGLf:b-xiijw6) ([raw file](https://github.com/cockroachdb/cockroach/blob/9c695e0b9750d9e924eea7374507da594ca296cf/pkg/sql/catalog/typedesc/type_desc.go#L964)):*
> ```Go
> 		if t.EnumType != nil &&
> 			(t.EnumType.TypeID == desc.ID ||
> 				t.EnumType.ArrayTypeID == desc.ID) &&
> ```

I'm not sure about this whole thing. Isn't it enough to check whether the `DeclarativeSchemaChangerState` is non-nil? I feel like we'd do well to cast the net a bit wide here. A type descriptor may not have any elements in this schema change but will still be tagged with a `DeclarativeSchemaChangerState` because we're modifying its back-references, which, remember, are owned by the forward-referencing element following my recent changes.
___
*[pkg/sql/catalog/typedesc/type_desc.go, line 965 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/77656#-MxuRmPpBAzcnIMhiNCz:-MxuRmPpBAzcnIMhiND-:bkg5bdn) ([raw file](https://github.com/cockroachdb/cockroach/blob/9c695e0b9750d9e924eea7374507da594ca296cf/pkg/sql/catalog/typedesc/type_desc.go#L965)):*
> ```Go
> 			(t.EnumType.TypeID == desc.ID ||
> 				t.EnumType.ArrayTypeID == desc.ID) &&
> 			t.TargetStatus != scpb.Status_UNKNOWN {
> ```

You don't need this check on `TargetStatus`, I think it's safe to assume this can't happen. I'll put a PR up that adds a validation check that actually enforces this, I just checked and there's none.
___
*[pkg/sql/schemachanger/scbuild/build.go, line 91 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/77656#-MxuVzEg6B9ubY4i7vr9:-MxuUA8R1ZuIA_jnwxe0:b-kyoa93) ([raw file](https://github.com/cockroachdb/cockroach/blob/9c695e0b9750d9e924eea7374507da594ca296cf/pkg/sql/schemachanger/scbuild/build.go#L91)):*
> ```Go
> 	// Ensure that no concurrent schema change are on going on any targets.
> 	descSet := screl.AllTargetDescIDs(ts)
> 	descSet.ForEach(bs.CheckNoConcurrentSchemaChange)
> ```

Suggestion: inline `CheckNoConcurrentSchemaChange` here, and then you don't need to call `ensureDescriptor` here either because it'll always be a no-op.
___
*[pkg/sql/schemachanger/scbuild/builder_state.go, line 767 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/77656#-MxuX86Y7JYK56JBOxT4:-MxuX86Y7JYK56JBOxT5:bd17089) ([raw file](https://github.com/cockroachdb/cockroach/blob/9c695e0b9750d9e924eea7374507da594ca296cf/pkg/sql/schemachanger/scbuild/builder_state.go#L767)):*
> ```Go
> 		}
> 	case catalog.SchemaDescriptor:
> 		b.ensureDescriptor(c.desc.GetParentID())
> ```

Why are you making this function recursive? If it's to cache the results of `readDescriptor`, there's no need, the descriptors are already cached in the descs.Collection after the first read, so there's not really any point.
___
*[pkg/sql/schemachanger/scbuild/internal/scbuildstmt/helpers.go, line 68 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/77656#-MxuVAWo137kVkvWiW8m:-MxuVAWo137kVkvWiW8n:b-12poso) ([raw file](https://github.com/cockroachdb/cockroach/blob/9c695e0b9750d9e924eea7374507da594ca296cf/pkg/sql/schemachanger/scbuild/internal/scbuildstmt/helpers.go#L68)):*
> ```Go
> // CASCADE.
> func dropCascadeDescriptor(b BuildCtx, id catid.DescID) {
> 	// Drop should be disallowed if concurrent schema changes exist.
> ```

Isn't this comment unnecessary? This PR ensures that it is so for all schema changes, after all.
___
*[pkg/sql/schemachanger/screl/scalars.go, line 17 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/77656#-MxuVTQm5u4NydwnBX0I:-MxuVTQm5u4NydwnBX0J:bspavka) ([raw file](https://github.com/cockroachdb/cockroach/blob/9c695e0b9750d9e924eea7374507da594ca296cf/pkg/sql/schemachanger/screl/scalars.go#L17)):*
> ```Go
> 
> 	"github.com/cockroachdb/cockroach/pkg/sql/catalog"
> 	"github.com/cockroachdb/cockroach/pkg/sql/catalog/descpb"
> ```

use the `catid` package instead
___
*[pkg/sql/schemachanger/screl/scalars.go, line 65 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/77656#-MxuVXaN6qEV1kk18x_3:-MxuVXaN6qEV1kk18x_4:b-hasvcj) ([raw file](https://github.com/cockroachdb/cockroach/blob/9c695e0b9750d9e924eea7374507da594ca296cf/pkg/sql/schemachanger/screl/scalars.go#L65)):*
> ```Go
> 				}
> 				ids.Add(id)
> 			}
> ```

detritus
___
*[pkg/sql/schemachanger/scrun/testing_knobs.go, line 22 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/77656#-MxuVdc423-swbZlmtiz:-MxuVdc423-swbZlmtj-:bsu1vt) ([raw file](https://github.com/cockroachdb/cockroach/blob/9c695e0b9750d9e924eea7374507da594ca296cf/pkg/sql/schemachanger/scrun/testing_knobs.go#L22)):*
> ```Go
> 	BeforeStage func(p scplan.Plan, stageIdx int) error
> 
> 	// AfterStage is invoked after all ops are execute.
> ```

nit: typo: s/execute/executed

**Comment by postamar** [comment]
> I wonder if it'd be better to make this a catalog function as it was before and just specialize the logic per descriptor type? What do you think?

If indeed it's enough to check that `DeclarativeSchemaChangerState` is not nil, in addition to the mutations slice not being empty in the special case of tables, then I agree.

**Review by ajwerner — COMMENTED** [review]
> If indeed it's enough to check that DeclarativeSchemaChangerState is not nil, in addition to the mutations slice not being empty in the special case of tables, then I agree.

It is certainly not enough to check that. We need to check for the signs of a non-declarative schema changer job which might be concurrently mucking with things. 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/77656#-:-Mxub3GV9XummrGasF8B:b-cqw8d7)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner and @fqazi)

**Comment by postamar** [comment]
Oh yeah, that. Does that mean we need to add a reference to the legacy type schema changer job to the type descriptor proto?

**Comment by ajwerner** [comment]
> Oh yeah, that. Does that mean we need to add a reference to the legacy type schema changer job to the type descriptor proto? I'm assuming there's nothing particular involved for schemas and databases though I may be wrong.

I don't know that we need to change the proto. We can. Just looking at the enum members is sufficient and was what I suggested. I'd rather not change proto interactions at this point.

**Review by fqazi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/77656)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner and @postamar)

___
*[-- commits, line 18 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/77656#-MxuRMQh58P_b-3eaSHm):*
<details><summary><i>Previously, postamar (Marius Posta) wrote…</i></summary><blockquote>

or, more simply: you're fixing a correctness bug.
</blockquote></details>

Done.
___
*[pkg/sql/catalog/dbdesc/database_desc.go, line 483 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/77656#-MxuQ5Q53htJeq2vOPxP:-MxusvtIEEBtEM6fdbKs:blxj9k6) ([raw file](https://github.com/cockroachdb/cockroach/blob/9c695e0b9750d9e924eea7374507da594ca296cf/pkg/sql/catalog/dbdesc/database_desc.go#L483)):*
<details><summary><i>Previously, postamar (Marius Posta) wrote…</i></summary><blockquote>

I think this check should remain as it is but, for my own information, is it possible to have a non-nil state with a zero job ID? I was under the impression that if there were no post-commit ops to run, we simply wouldn't set DeclarativeSchemaChangerState at all. I may be wrong.
</blockquote></details>

In the future, it may be possible since there will be schema changes that don't require jobs. Right now there shouldn't be any case like that.
___
*[pkg/sql/catalog/schemadesc/synthetic_schema_desc.go, line 122 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/77656#-MxuQhpu1VNuBKzfgP4V:-Mxupz6P5b46gi5uWcYg:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/9c695e0b9750d9e924eea7374507da594ca296cf/pkg/sql/catalog/schemadesc/synthetic_schema_desc.go#L122)):*
<details><summary><i>Previously, postamar (Marius Posta) wrote…</i></summary><blockquote>

If you're going to print a log message at all, you might as well surface more information in it?

FWIW I'd be happy to simply return `false` here. It's not wrong.
</blockquote></details>

Done.



_Code quote:_
```Go
HasConcurrentSchemaChanges
```
___
*[pkg/sql/catalog/typedesc/table_implicit_record_type.go, line 338 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/77656#-MxuR6078IHNKT4l1r8J:-MxupzuW6xITxl00qoL0:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/9c695e0b9750d9e924eea7374507da594ca296cf/pkg/sql/catalog/typedesc/table_implicit_record_type.go#L338)):*
<details><summary><i>Previously, postamar (Marius Posta) wrote…</i></summary><blockquote>

Same comment as above re. simply returning `false`. I don't feel strongly about this.
</blockquote></details>

Done.
___
*[pkg/sql/catalog/typedesc/type_desc.go, line 962 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/77656#-MxuSd_GEwRsYzGUIWeV:-MxuqHeA4J755oSkIy3G:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/9c695e0b9750d9e924eea7374507da594ca296cf/pkg/sql/catalog/typedesc/type_desc.go#L962)):*
<details><summary><i>Previously, postamar (Marius Posta) wrote…</i></summary><blockquote>

You might want to `switch e := t.Element().(type)` or something like that instead. Also shouldn't you be also checking alias types in addition to enum types?
</blockquote></details>

Done.
___
*[pkg/sql/catalog/typedesc/type_desc.go, line 964 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/77656#-MxuSeKj7wDcTmKazGLe:-MxutEwY4EAJCzGfMhD3:bv8jk8t) ([raw file](https://github.com/cockroachdb/cockroach/blob/9c695e0b9750d9e924eea7374507da594ca296cf/pkg/sql/catalog/typedesc/type_desc.go#L964)):*
<details><summary><i>Previously, postamar (Marius Posta) wrote…</i></summary><blockquote>

I'm not sure about this whole thing. Isn't it enough to check whether the `DeclarativeSchemaChangerState` is non-nil? I feel like we'd do well to cast the net a bit wide here. A type descriptor may not have any elements in this schema change but will still be tagged with a `DeclarativeSchemaChangerState` because we're modifying its back-references, which, remember, are owned by the forward-referencing element following my recent changes.
</blockquote></details>

Done.

I agree this is preemptive. I'll simplify this to just checking for a job ID for now, and leave TODO for future potential scenarios.
___
*[pkg/sql/catalog/typedesc/type_desc.go, line 965 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/77656#-MxuRmPpBAzcnIMhiNCz:-MxuqLna-oyKce43_Fc2:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/9c695e0b9750d9e924eea7374507da594ca296cf/pkg/sql/catalog/typedesc/type_desc.go#L965)):*
<details><summary><i>Previously, postamar (Marius Posta) wrote…</i></summary><blockquote>

You don't need this check on `TargetStatus`, I think it's safe to assume this can't happen. I'll put a PR up that adds a validation check that actually enforces this, I just checked and there's none.
</blockquote></details>

Done.
___
*[pkg/sql/schemachanger/scbuild/build.go, line 91 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/77656#-MxuVzEg6B9ubY4i7vr9:-MxuqPSx2MwCqbdbrPf4:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/9c695e0b9750d9e924eea7374507da594ca296cf/pkg/sql/schemachanger/scbuild/build.go#L91)):*
<details><summary><i>Previously, postamar (Marius Posta) wrote…</i></summary><blockquote>

Suggestion: inline `CheckNoConcurrentSchemaChange` here, and then you don't need to call `ensureDescriptor` here either because it'll always be a no-op.
</blockquote></details>

Done.
___
*[pkg/sql/schemachanger/scbuild/builder_state.go, line 767 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/77656#-MxuX86Y7JYK56JBOxT4:-MxuqyQL7CVLVIMm14da:b-9mdkbr) ([raw file](https://github.com/cockroachdb/cockroach/blob/9c695e0b9750d9e924eea7374507da594ca296cf/pkg/sql/schemachanger/scbuild/builder_state.go#L767)):*
> Why are you making this function recursive? If it's to cache the results of readDescriptor, there's no need, the descriptors are already cached in the descs.Collection after the first read, so there's not really any point.

No the reason for the recursion is that we detect temporary schemas correctly since those will fail on normal look-ups. When we ensureDescritor for databases these are all handled correctly.
___
*[pkg/sql/schemachanger/scbuild/internal/scbuildstmt/helpers.go, line 68 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/77656#-MxuVAWo137kVkvWiW8m:-MxusPHV-T7vspQLzkQd:bl64sow) ([raw file](https://github.com/cockroachdb/cockroach/blob/9c695e0b9750d9e924eea7374507da594ca296cf/pkg/sql/schemachanger/scbuild/internal/scbuildstmt/helpers.go#L68)):*
<details><summary><i>Previously, postamar (Marius Posta) wrote…</i></summary><blockquote>

Isn't this comment unnecessary? This PR ensures that it is so for all schema changes, after all.
</blockquote></details>

Done.
Left over from an older code change.



_Code quote:_
```Go
	// Drop should be disallowed if concurrent schema changes exist.
```
___
*[pkg/sql/schemachanger/screl/scalars.go, line 17 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/77656#-MxuVTQm5u4NydwnBX0I:-MxusheH2iPVcDP9-d-9:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/9c695e0b9750d9e924eea7374507da594ca296cf/pkg/sql/schemachanger/screl/scalars.go#L17)):*
<details><summary><i>Previously, postamar (Marius Posta) wrote…</i></summary><blockquote>

use the `catid` package instead
</blockquote></details>

Done.
___
*[pkg/sql/schemachanger/screl/scalars.go, line 50 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/77656#-MxuWRwGAU2-FD9B51yu:-MxusYjIDV_gIhM8JvKT:bh5zpw3) ([raw file](https://github.com/cockroachdb/cockroach/blob/9c695e0b9750d9e924eea7374507da594ca296cf/pkg/sql/schemachanger/screl/scalars.go#L50)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

debug code?
</blockquote></details>

Done.

Yes from the temporary schema case.
___
*[pkg/sql/schemachanger/screl/scalars.go, line 65 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/77656#-MxuVXaN6qEV1kk18x_3:-MxusiOWA4-4LSHOZ2S2:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/9c695e0b9750d9e924eea7374507da594ca296cf/pkg/sql/schemachanger/screl/scalars.go#L65)):*
<details><summary><i>Previously, postamar (Marius Posta) wrote…</i></summary><blockquote>

detritus
</blockquote></details>

Done.

**Review by postamar — COMMENTED** [review]
I'm OK with this code but don't know if it works or not and for that I defer to Andrew.

It would be nice to have another test on types in addition to that on schemas which you added.

Also, if you're not going to deal with enum value additions and deletions in this PR (your choice) please file a follow-up issue, link it to the CRDB-2356 epic and tag it as a release blocker.

> Reviewed 8 of 8 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/77656#-:-MxuxsyH4GNhJgs5gxJA:b-vo2rsk)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @fqazi, and @postamar)

___
*[pkg/sql/catalog/typedesc/type_desc.go, line 962 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/77656#-MxuSd_GEwRsYzGUIWeV:-Mxux05u684C81plOskC:b-u0dgrc) ([raw file](https://github.com/cockroachdb/cockroach/blob/9c695e0b9750d9e924eea7374507da594ca296cf/pkg/sql/catalog/typedesc/type_desc.go#L962)):*
<details><summary><i>Previously, fqazi (Faizan Qazi) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Please add an explicit `case *scpb.AliasType` even if it's to do nothing. in which case add a comment explaining why we're doing nothing.
___
*[pkg/sql/schemachanger/scbuild/build.go, line 95 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/77656#-MxuxXw-1SXt4Av2BcRq:-MxuxXw-1SXt4Av2BcRr:bt06p71) ([raw file](https://github.com/cockroachdb/cockroach/blob/4a81d5798335f3c3e7f8d28ec82051a4ab14254b/pkg/sql/schemachanger/scbuild/build.go#L95)):*
> ```Go
> 	descSet.ForEach(func(id descpb.ID) {
> 		bs.ensureDescriptor(id)
> 		desc := bs.descCache[id]
> ```

I think you want `desc := bs.descCache[id].desc` here instead
___
*[pkg/sql/schemachanger/scbuild/builder_state.go, line 767 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/77656#-MxuX86Y7JYK56JBOxT4:-Mxuxbnc4Lge4gjCbm0_:b-tl1hc7) ([raw file](https://github.com/cockroachdb/cockroach/blob/9c695e0b9750d9e924eea7374507da594ca296cf/pkg/sql/schemachanger/scbuild/builder_state.go#L767)):*
<details><summary><i>Previously, fqazi (Faizan Qazi) wrote…</i></summary><blockquote>

> Why are you making this function recursive? If it's to cache the results of readDescriptor, there's no need, the descriptors are already cached in the descs.Collection after the first read, so there's not really any point.

No the reason for the recursion is that we detect temporary schemas correctly since those will fail on normal look-ups. When we ensureDescritor for databases these are all handled correctly.
</blockquote></details>

Ah, that makes sense! Thanks for the explanation.

**Review by fqazi — COMMENTED** [review]
I'll add a test to confirm the type-related code. Enum type addition removal / addition is a longer-term thing and shouldn't be a release blocker. We only support fully dropping types and those always generate a job ID today. Not sure if I'm missing something

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/77656#-:-MxuznL06h41pUNoJviF:b-sl9vma)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner and @postamar)

___
*[pkg/sql/catalog/typedesc/type_desc.go, line 962 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/77656#-MxuSd_GEwRsYzGUIWeV:-MxuzcWl6hyAZoeaHaLI:bst7pox) ([raw file](https://github.com/cockroachdb/cockroach/blob/9c695e0b9750d9e924eea7374507da594ca296cf/pkg/sql/catalog/typedesc/type_desc.go#L962)):*
<details><summary><i>Previously, postamar (Marius Posta) wrote…</i></summary><blockquote>

Please add an explicit `case *scpb.AliasType` even if it's to do nothing. in which case add a comment explaining why we're doing nothing.
</blockquote></details>

I'm removing this code now all the drop cases right now will always set job ID. So, this stuff is *pre-emptive*. I'll update the TODO to state that in the future we may have cases where no job ID exists.
___
*[pkg/sql/schemachanger/scbuild/build.go, line 95 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/77656#-MxuxXw-1SXt4Av2BcRq:-Mxv-23A3u5J8AVSlIuj:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/4a81d5798335f3c3e7f8d28ec82051a4ab14254b/pkg/sql/schemachanger/scbuild/build.go#L95)):*
<details><summary><i>Previously, postamar (Marius Posta) wrote…</i></summary><blockquote>

I think you want `desc := bs.descCache[id].desc` here instead
</blockquote></details>

Done.
___
*[pkg/sql/schemachanger/scbuild/builder_state.go, line 767 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/77656#-MxuX86Y7JYK56JBOxT4:-Mxv-2vl0UtUh9dHDNB9:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/9c695e0b9750d9e924eea7374507da594ca296cf/pkg/sql/schemachanger/scbuild/builder_state.go#L767)):*
<details><summary><i>Previously, postamar (Marius Posta) wrote…</i></summary><blockquote>

Ah, that makes sense! Thanks for the explanation.
</blockquote></details>

Done.

**Review by postamar — COMMENTED** [review]
Thanks

> Reviewed 4 of 4 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/77656#-:-MyCmpnk4jDW6BYnT0Rx:b-zcjvte)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner)

**Review by ajwerner — APPROVED** [review]
:lgtm:

Sorry for the delay

> Reviewed 8 of 21 files at r1, 2 of 5 files at r2, 4 of 8 files at r3, 4 of 4 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/77656#-:-MyDkk9321_bpre9aALM:bk91kdl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @fqazi)

**Comment by fqazi** [comment]
@ajwerner TFTR!

**Comment by fqazi** [comment]
bors+

**Comment by rafiss** [comment]
I see that this PR closed a few release blockers. This was merged after the branch cut. Does it need to be backported to `release-22.1`?
