### PR TITLE
roachtest: cleanup job-compat cleanup

### LINKED ISSUE #127473: roachtest: declarative_schema_changer/job-compatibility-mixed-version-V242-V243 failed
roachtest.declarative_schema_changer/job-compatibility-mixed-version-V242-V243 [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyAzureBazel/16140145?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyAzureBazel/16140145?buildTab=artifacts#/declarative_schema_changer/job-compatibility-mixed-version-V242-V243) on master @ [6154ebfa1482bcaecc1988a10f1f0f124b5c6b27](https://github.com/cockroachdb/cockroach/commits/6154ebfa1482bcaecc1988a10f1f0f124b5c6b27):

```
(mixedversion.go:645).Run: mixed-version test failure while running step 8 (run "test step in mixed version"): pq: unknown function: fn()
test artifacts and logs in: /artifacts/declarative_schema_changer/job-compatibility-mixed-version-V242-V243/cpu_arch=arm64/run_1
```

Parameters:
 - <code>ROACHTEST_arch=arm64</code>
 - <code>ROACHTEST_cloud=azure</code>
 - <code>ROACHTEST_coverageBuild=false</code>
 - <code>ROACHTEST_cpu=4</code>
 - <code>ROACHTEST_encrypted=false</code>
 - <code>ROACHTEST_metamorphicBuild=false</code>
 - <code>ROACHTEST_ssd=0</code>
<details><summary>Help</summary>
<p>

See: [roachtest README](https://github.com/cockroachdb/cockroach/blob/master/pkg/cmd/roachtest/README.md)

See: [How To Investigate \(internal\)](https://cockroachlabs.atlassian.net/l/c/SSSBr8c7)

_Grafana is not yet available for azure clusters_</p>
</details>
/cc @cockroachdb/sql-foundations
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*declarative_schema_changer/job-compatibility-mixed-version-V242-V243.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/bazci/githubpost/issues)
</sub>

Jira issue: CRDB-40447

### PR DESCRIPTION
**Pull request by annrpom**
These objects no longer need to be dropped since they no longer get created.

Fixes: #127473

Release note: None

### CODE REVIEW

**Review by rafiss — APPROVED** [review]
thanks lgtm! just checking, we don't need to have functions in the `setup` phase either right? (they are not there now, but should they be?)

**Comment by rafiss** [comment]
i guess we'd only need it there if we wanted to test an ALTER FUNCTION

**Comment by annrpom** [comment]
> thanks lgtm

np -- it was my bad for not catching this in the review

> (they are not there now, but should they be?)

> i guess we'd only need it there if we wanted to test an ALTER FUNCTION

^ yes

another thing i noticed while running this was that our session var was not being set properly in the setup txn:

image

so i went ahead and separated that logic -- wdyt @rafiss (mainly seeing if i understood that SetMaxOpenConns needs to be applied only once per db connection)

File: pkg/cmd/roachtest/tests/mixed_version_job_compatibility_in_declarative_schema_changer.go [hunk 1]
```diff
@@ -62,7 +62,7 @@ func setShortGCTTLInSystemZoneConfig(
 	return h.Exec(r, "ALTER RANGE default CONFIGURE ZONE USING gc.ttlseconds = 1;")
 }
 
-// executeSupportedDDLs tests all stmts supported in V23_1.
+// executeSupportedDDLs tests all stmts supported in V24_2.
```
Comment (rafiss) [inline pkg/cmd/roachtest/tests/mixed_version_job_compatibility_in_declarative_schema_changer.go:65]: ah nice catch on the comment. even better so we don't have to remember each time would be:
> executeSupportedDDLs tests all stmts which had DSC support added in the previous major version.

**Review by rafiss — APPROVED** [review]
> so i went ahead and separated that logic -- wdyt @rafiss (mainly seeing if i understood that SetMaxOpenConns needs to be applied only once per db connection)

i agree, this should work! i am surprised that the SET as the first statement in the batch didn't seem to take effect right away, but that is a separate issue we can debug if we feel the need to.

File: pkg/cmd/roachtest/tests/mixed_version_job_compatibility_in_declarative_schema_changer.go (hunk 1 above)
Comment (annrpom) [reply pkg/cmd/roachtest/tests/mixed_version_job_compatibility_in_declarative_schema_changer.go:65]: true lol let me reword

**Comment by annrpom** [comment]
> i am surprised that the SET as the first statement in the batch didn't seem to take effect right away

yeah i saw that there was work to make setting session variables transaction-lived via SET LOCAL which could be another workaround, but the multi-line transactional statement didnt seem to fit in:

```
demo@127.0.0.1:26257/demoapp/movr> set use_declarative_schema_changer = unsafe_always;        
SET

demo@127.0.0.1:26257/demoapp/movr> set local use_declarative_schema_changer = off;create      
                                -> database bleh;                                             
WARNING: SET LOCAL can only be used in transaction blocks
SQLSTATE: 00000
SET
CREATE DATABASE

Note: timings for multiple statements on a single line are not supported. See https://go.crdb.dev/issue-v/48180/v24.2.
```
so at least for this PR, I left it be at that 

so the mystery continues -- i'll put up something to in case we want debug more

**Comment by annrpom** [comment]
TFTR! ('-')7

bors r=rafiss
