### PR TITLE
sqlstats: generate PCT_RUNTIME sort when requested

### LINKED ISSUE #123841: sqlstats: requests for `% of all Runtime` in SQL Activity are incorrectly sorted by `svcLatency`
**Describe the problem**

**To Reproduce**

Ran the `sqlstats` and `movr` workloads on a cluster, and then opened SQL Activity.
Sorting by top 100 and top 500 produces inconsistent results:

### Top 100
Screenshot 2024-05-08 at 15 03 13

### Top 500
Screenshot 2024-05-08 at 15 04 59

**Expected behavior**
The top 100 entries in the top 500 view should be identical.

**Environment:**
 - CockroachDB version: 23.1.16

Jira issue: CRDB-38567

Epic CRDB-37544

### PR DESCRIPTION
**Pull request by dhartunian**
Previously, when a request was made to the combined stats endpoint on CRDB with a `PCT_RUNTIME` sort, we'd default to a `svcLatency` sort instead because of a missing switch case.

This change fills that gap and adds some datadriven tests to inspect the resulting `WHERE` clauses.

Fixes: #123841
Epic: CRDB-37544

Release note (ui change): Viewing SQL Activity sorted by `% of Runtime` now correctly sorts entries by the runtime amount.

### CODE REVIEW

File: pkg/server/combined_statement_stats_test.go [hunk 1]
```diff
@@ -0,0 +1,56 @@
...
+			var internal bool
+			d.ScanArgs(t, "sort", &sortString)
+			d.ScanArgs(t, "limit", &limit)
+			d.ScanArgs(t, "internal", &internal)
+
+			gotWhereClause, gotOrderAndLimitClause, gotArgs := getCombinedStatementsQueryClausesAndArgs(
+				&serverpb.CombinedStatementsStatsRequest{
+					FetchMode: &serverpb.CombinedStatementsStatsRequest_FetchMode{
+						StatsType: serverpb.CombinedStatementsStatsRequest_StmtStatsOnly,
+						Sort:      serverpb.StatsSortOptions(serverpb.StatsSortOptions_value[sortString]),
```
Comment (xinhaoz) [inline pkg/server/combined_statement_stats_test.go:42]: I think you're missing the limit here, and I don't think internal is a field on the request.

**Review by xinhaoz — COMMENTED** [review]
Nice tests. I think in the future (as part of the redesign for this api) it'd be cool to do something like this where we can programmatically do this for all of the available sort options in the request.

Just the one comment with the sort and internal options.

File: pkg/server/combined_statement_stats_test.go (hunk 1 above)
Comment (xinhaoz) [reply pkg/server/combined_statement_stats_test.go:47]: Oh, I missed that internal was being passed below in the function - ignore that part.

Comment (dhartunian) [reply pkg/server/combined_statement_stats_test.go:51]: I just took out internal as a flag in the test cases, and added start/end

File: pkg/server/testdata/combined_statement_stats [hunk 2]
```diff
@@ -0,0 +1,136 @@
...
+----
+--WHERE--
+ WHERE app_name NOT LIKE '$ internal%' AND app_name NOT LIKE '$$ %' AND aggregated_ts >= $1 AND aggregated_ts <= $2
+--ORDER AND LIMIT--
+ ORDER BY ((statistics -> 'statistics' -> 'svcLat' ->> 'mean')::FLOAT *
+                         (statistics -> 'statistics' ->> 'cnt')::FLOAT) DESC LIMIT $3
+--ARGS--
+[1970-01-01 00:00:01 +0000 UTC 1970-01-01 00:00:02 +0000 UTC 100]
+
+query sort=SERVICE_LAT limit=100 start=1 end=2
```
Comment (xinhaoz) [inline pkg/server/testdata/combined_statement_stats:11]: nit: Could we have some test cases where limit is something other than 100 / when it's omitted? Just to verify it's putting the correct value.

**Review by xinhaoz — APPROVED** [review]

File: pkg/server/testdata/combined_statement_stats (hunk 2 above)
Comment (dhartunian) [reply pkg/server/testdata/combined_statement_stats:43]: done.

**Comment by dhartunian** [comment]
bors r=xinhaoz
