### PR TITLE
roachtest: improve WaitForUpdatedReplicationReport

### LINKED ISSUE #78284: roachtest: follower-reads/survival=region/locality=regional/reads=bounded-staleness/insufficient-quorum failed [test loses quorum on ts ranges]
roachtest.follower-reads/survival=region/locality=regional/reads=bounded-staleness/insufficient-quorum [failed](https://teamcity.cockroachdb.com/viewLog.html?buildId=4632355&tab=buildLog) with [artifacts](https://teamcity.cockroachdb.com/viewLog.html?buildId=4632355&tab=artifacts#/follower-reads/survival=region/locality=regional/reads=bounded-staleness/insufficient-quorum) on master @ [10e0c5d92f8ef953d6b497b448893bb5044cdd31](https://github.com/cockroachdb/cockroach/commits/10e0c5d92f8ef953d6b497b448893bb5044cdd31):

```
The test failed on branch=master, cloud=gce:
test artifacts and logs in: /artifacts/follower-reads/survival=region/locality=regional/reads=bounded-staleness/insufficient-quorum/run_1
	follower_reads.go:712,follower_reads.go:373,follower_reads.go:72,test_runner.go:875: Post "http://34.145.50.48:26258/ts/query": EOF

	test_runner.go:1006,test_runner.go:905: test timed out (0s)
```
<details><summary>Help</summary>
<p>

See: [roachtest README](https://github.com/cockroachdb/cockroach/blob/master/pkg/cmd/roachtest/README.md)

See: [How To Investigate \(internal\)](https://cockroachlabs.atlassian.net/l/c/SSSBr8c7)

</p>
</details>
/cc @cockroachdb/kv-triage
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*follower-reads/survival=region/locality=regional/reads=bounded-staleness/insufficient-quorum.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)
</sub>

Jira issue: CRDB-14044

### PR DESCRIPTION
**Pull request by ajwerner**
Before this change, it was possible to wait for only some of the replication
reports to exist without waiting for the critical localities test to exist.

Fixes #78284.

Release note: None

### CODE REVIEW

File: pkg/cmd/roachtest/tests/util.go [hunk 1]
```diff
@@ -82,15 +82,17 @@ func WaitForUpdatedReplicationReport(ctx context.Context, t test.Test, db *gosql
...
+			ctx, `SELECT count(*), min(generated) FROM system.reports_meta`,
+		).Scan(&count, &gen); err != nil {
 			if !errors.Is(err, gosql.ErrNoRows) {
 				t.Fatal(err)
 			}
-			// No report generated yet.
-		} else if tStart.Before(gen) {
+			// No report generated yet. There are 3 types of reports. We want to
+			// see a result for all of them.
+		} else if count == 3 && tStart.Before(gen.Time) {
```
Comment (nvanbenschoten) [inline pkg/cmd/roachtest/tests/util.go:95]: It's unfortunate that we'll bake this assumption that there are exactly 3 types of reports into this roachtest, but I'm not seeing better options. I don't really understand how we expect users to use this stuff. We reference the "ID of the report that this report entry is part of" in https://www.cockroachlabs.com/docs/stable/query-replication-reports.html#system-reports_meta, but never document which ID maps to which report. These are also unexported symbols in the code. Am I missing something?

**Review by nvb — APPROVED** [review]
Nice find!

File: pkg/cmd/roachtest/tests/util.go (hunk 1 above)
Comment (ajwerner) [reply pkg/cmd/roachtest/tests/util.go:95]: They're currently unexported constants with an unexported type. It could be refactored to be better. I'd rather leave that for later. I'll file an issue about it if you're okay with that.

Comment (nvanbenschoten) [reply pkg/cmd/roachtest/tests/util.go:95]: An issue sounds fine. Thanks again.

**Comment by ajwerner** [comment]
TFTR!

bors r=nvanbenschoten

File: pkg/cmd/roachtest/tests/util.go (hunk 1 above)
Comment (ajwerner) [reply pkg/cmd/roachtest/tests/util.go:95]: https://github.com/cockroachdb/cockroach/issues/80002
