### PR TITLE
microbench-ci: add performance gain label

### LINKED ISSUE #147748: microbench-ci: add `X-perf-gain` to gains
Currently, the microbenchmark CI job only posts regressions and adds the `X-perf-check` label to any PR with a regression.

But we would like to track gains as well. Gains should not post to the PR itself as it might become noisy, but if a valid gain is detected adding a label would allow easier tracing of such PRs.

Jira issue: CRDB-51210

### PR DESCRIPTION
**Pull request by herkolategan**
Previously, microbench-ci did not report performance gains. Since we want a way
of tracking PRs that increase performance, we now add a performance gain label,
`X-perf-gain`, if the microbenchmark comparisons detected a performance gain.

Performance gains work the same way as a regression. All retries have to be
positive for a gain before it is considered a performance gain.

Fixes: #147748

Epic: None
Release note: None

### CODE REVIEW

File: pkg/cmd/microbench-ci/main.go [hunk 1]
```diff
@@ -99,8 +99,8 @@ func (s *Suite) binURL(revision Revision, benchmark *Benchmark) string {
 		Bucket, s.revisionSHA(revision), benchmark.binaryName())
 }
 
-func (s *Suite) changeDetected() bool {
-	for _, status := range []Status{Regressed} {
+func (s *Suite) hasPerformanceChange(status Status) bool {
+	for _, status := range []Status{status} {
```
Comment (DarrylWong) [inline pkg/cmd/microbench-ci/main.go]: nit: is this outer for loop necessary? Especially since we now take in just a singular `Status`?

File: pkg/cmd/microbench-ci/main.go [hunk 2]
```diff
@@ -152,36 +152,49 @@ func makeCompareCommand() *cobra.Command {
 
 		// If the `PerfLabel` is present on the PR, or a change was detected, we
```
Comment (DarrylWong) [inline pkg/cmd/microbench-ci/main.go]: nit: 
```suggestion
		// If the `PerfRegressionLabel` is present on the PR, or a regression was detected, we
```

File: pkg/cmd/microbench-ci/github.go [hunk 3]
```diff
@@ -25,8 +25,9 @@ type GitHubConfig struct {
 }
 
 const (
-	CommentTag = "<!-- microbench-ci -->"
-	PerfLabel  = "X-perf-check"
+	CommentTag          = "<!-- microbench-ci -->"
+	PerfRegressionLabel = "X-perf-check"
+	PerfGainLabel       = "X-perf-gain"
```
Comment (DarrylWong) [inline pkg/cmd/microbench-ci/github.go:30]: We use the terminology `Regressed` and `Improved` already. Should we reflect that here or is it too late since we already have regressions under `X-perf-check`?

**Comment by golgeek** [comment]
Might have missed the logic, but what happens if a PR had a perf improvement tag, but then a new commit adds a perf regression and a per regression tag is posted? Do we have both tags attached?

**Comment by herkolategan** [comment]
> Might have missed the logic, but what happens if a PR had a perf improvement tag, but then a new commit adds a perf regression and a per regression tag is posted? Do we have both tags attached?

That could probably happen, it will be up to the author to remove the label, or keep the correct one. We could probably have the code automatically remove it, but the labels are meant to be sticky and reviewed by the author of the PR. The performance checks are only assistive, not an end-all.

File: pkg/cmd/microbench-ci/main.go (hunk 1 above)
Comment (herkolategan) [reply pkg/cmd/microbench-ci/main.go]: Good point, the outer loop serves no purpose here anymore.

File: pkg/cmd/microbench-ci/github.go (hunk 3 above)
Comment (herkolategan) [reply pkg/cmd/microbench-ci/github.go:30]: I think `X-perf-check` still makes sense: meaning the author should check if performance has regressed, and try to resolve the regression - eventually removing the label. Almost like a check engine light :)

It could maybe make sense to have a `X-perf-regression` that could be added if the `X-perf-check` does indicate a real regression, but the regression is expected to remain due to some required feature and will be merged.

The `X-perf-gain` label is also expected to remain, to indicate the PR improved performance. In a sense the `X-perf-gain` could also be a false positive, so then it should be removed.

But given that this is not well known info around the labels and their meaning, it should be documented and added to the comment the job makes on a PR.

@tbg Any thoughts on the label names and logic of the above here?

Comment (tbg) [reply pkg/cmd/microbench-ci/github.go:30]: No strong feelings held on my part.

**Review by DarrylWong — APPROVED** [review]
Reasoning on the labels makes sense to me 👍

**Comment by herkolategan** [comment]
TFTR!

bors r=DarrylWong
