### PR TITLE
roachprod: fix prom service update issue

### LINKED ISSUE #127503: roachprod: the prometheus config gets overwritten if a node is started instead of the entire cluster
The prometheus config file for a cluster is created at cluster start. But, if we are starting one node at a time, the node specific config is written to the file and any previous config gets overwritten.

### PR DESCRIPTION
**Pull request by nameisbhaskar**
When a single node of a cluster is started, the
prometheus config specific to that node is only
updated. This is because we just query information
specific to that node. This change considers all the nodes
in the cluster during cluster start and updates the information
for all the nodes.

 Fixes: #127503
 Epic: None

### CODE REVIEW

File: pkg/roachprod/roachprod.go [hunk 1]
```diff
@@ -783,7 +782,9 @@ func UpdateTargets(
 	if err := LoadClusters(); err != nil {
 		return err
 	}
-	c, err := newCluster(l, clusterName, clusterSettingsOpts...)
+	// use the custer name without the node suffix. This ensures that we update the target with details of all nodes
```
Comment (vidit-bhat) [inline pkg/roachprod/roachprod.go:785]: cluster*

**Comment by nameisbhaskar** [comment]
Thanks @vidit-bhat for reviewing. I have corrected the typo.

**Comment by srosenberg** [comment]
> When a single node of a cluster is started, the prometheus config specific to that node is only updated. This is because we just query information specific to that node. This change fixes the same. 

Not sure I follow the last sentence... "fixes the same"?

File: pkg/roachprod/roachprod.go [hunk 2]
```diff
@@ -769,8 +769,7 @@ func Start(
 	if err = c.Start(ctx, l, startOpts); err != nil {
 		return err
 	}
-	updatePrometheusTargets(ctx, l, c)
-	return nil
+	return UpdateTargets(ctx, l, clusterName, clusterSettingsOpts...)
```
Comment (srosenberg) [inline pkg/roachprod/roachprod.go:772]: Why is this change necessary?

Comment (srosenberg) [reply pkg/roachprod/roachprod.go:772]: Nm, I see that's because of the stripping of the node suffix from the clusterName. In that case, we should update the comment for `updatePrometheusTargets` that it _requires_ cluster names without node selector; otherwise, the same bug could resurface later if someone mistakenly uses `updatePrometheusTargets` instead of ` UpdateTargets`.

Comment (nameisbhaskar) [reply pkg/roachprod/roachprod.go:772]: This makes sense, I will actually move the split code to the updatePrometheusTargets.

**Comment by nameisbhaskar** [comment]
Thanks @srosenberg for reviewing the change. I have made the changes.

File: pkg/roachprod/roachprod.go [hunk 3]
```diff
@@ -783,16 +782,23 @@ func UpdateTargets(
...
+}
+
+// updatePrometheusTargets updates the prometheus instance cluster config. Any error is logged and ignored.
+func updatePrometheusTargets(
+	ctx context.Context,
+	l *logger.Logger,
+	clusterName string,
+	clusterSettingsOpts ...install.ClusterSettingOption,
+) error {
+	// use the cluster name without the node suffix. This ensures that we update the target with details of all nodes
```
Comment (kvoli) [inline pkg/roachprod/roachprod.go:795]: nit: use full sentences for comments, unless they are in-line (discouraged).

File: pkg/roachprod/roachprod.go [hunk 4]
```diff
@@ -783,16 +782,23 @@ func UpdateTargets(
...
+	cn := strings.Split(clusterName, ":") // no error check. cluster name will either have : or not, we use index 0
```
Comment (kvoli) [inline pkg/roachprod/roachprod.go:796]: nit: same here, capitalize the first char of the sentence and consider moving this up above in one long-form comment, instead of in-line.

**Comment by nameisbhaskar** [comment]
Thanks @kvoli for your review. I have updated the comments.

**Review by kvoli — APPROVED** [review]
LGTM! 

I tested out the prior revision. The cluster metrics showed up in prometheus with `perturbation/full/restart`, which starts nodes individually.

**Comment by nameisbhaskar** [comment]
Thanks @kvoli !

**Comment by nameisbhaskar** [comment]
bors r=@kvoli
