### PR TITLE
loqrecovery: enable DRPC for loqrecovery tests randomly

### LINKED ISSUE #159372: kvserver: Tests in `loqrecovery` fail with DRPC enabled
**Describe the problem**

When enabling DRPC for tests throughout the `kvserver` package, tests in `loqrecovery` consistently fail with DRPC on in all the tenant modes (off, external or shared)

One such instance is with `TestNodeDecommisioned` which fails with the following error:

```
--- FAIL: TestNodeDecommissioned (54.31s)
    test_log_scope.go:171: test logs captured to: /tmp/cockroach/_tmp/c87d7e65c1e00835d84bcde1797d3f9a/logTestNodeDecommissioned763084530
    test_server_shim.go:658: DRPC is enabled (via testserver factory defaults)
    server_integration_test.go:461: condition failed to evaluate within 45s: rpc error: code = Unknown desc = DRPC: failed to connect to n3 at 127.0.0.1:59364: initial connection heartbeat failed: EOF; EOF
    panic.go:615: -- test log scope end --
FAIL
I251211 09:16:02.831818 1 (gostd) testmain.go:160  [-] 1  Test //pkg/kv/kvserver/loqrecovery:loqrecovery_test exited with error code 1
``` 

The following tests fail with drpc enabled:
```
TestReplicaCollection
TestGetPlanStagingState
TestRetrieveApplyStatus
TestNodeDecommissioned
```

**To Reproduce**

With drpc enabled;
`./dev test pkg/kv/kvserver/loqrecovery/ --filter TestNodeDecommissioned --show-logs --stream-output`

**Expected behavior**
The test should pass.

**Environment:**
 - CockroachDB version : master

**Additional context**

Have disabled DRPC for the whole package for now, will re-enable once fixed.

Epic: CRDB-55382

Jira issue: CRDB-57818

### PR DESCRIPTION
**Pull request by cthumuluru-crdb**
Previously, loqrecovery tests would fail when DRPC was enabled because DRPC returns codes.Unknown for connection errors, while gRPC returns codes.Unavailable. DRPC version used in this patch has a fix to return codes.Unavailable for connection errors.

Fixes: #159372
Epic: CRDB-55382
Release note: None

### CODE REVIEW

File: pkg/kv/kvserver/loqrecovery/main_test.go [hunk 1]
```diff
@@ -22,7 +22,7 @@ func TestMain(m *testing.M) {
 	securityassets.SetLoader(securitytest.EmbeddedAssets)
 	randutil.SeedForTests()
 	serverutils.InitTestServerFactory(server.TestServerFactory,
-		serverutils.WithDRPCOption(base.TestDRPCDisabled))
+		serverutils.WithDRPCOption(base.TestDRPCEnabledRandomly))
```
Comment (Nukitt) [inline pkg/kv/kvserver/loqrecovery/main_test.go:25]: `TestReplicaCollection` in `pkg/kv/kvserver/loqrecovery/server_integration_test.go` will fail currently. We should disable drpc for that test and have a tracking ticket for it.

**Review by Nukitt — CHANGES_REQUESTED** [review]

File: pkg/kv/kvserver/loqrecovery/main_test.go (hunk 1 above)
Comment (cthumuluru-crdb) [reply pkg/kv/kvserver/loqrecovery/main_test.go:25]: Done. Thank you!

**Review by Nukitt — APPROVED** [review]

**Comment by Nukitt** [comment]
LGTM!
