### PR TITLE
roachtest: update cdc/mixed-versions to set mux rangefeeds correctly

### LINKED ISSUE #117315: roachtest: cdc/mixed-versions failed
roachtest.cdc/mixed-versions [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/13388651?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/13388651?buildTab=artifacts#/cdc/mixed-versions) on master @ [f2917d82b235db6fda145a932050e5a58f957b9f](https://github.com/cockroachdb/cockroach/commits/f2917d82b235db6fda145a932050e5a58f957b9f):

```
(mixedversion.go:539).Run: mixed-version test failure while running step 43 (run "use mux"): pq: unknown cluster setting 'changefeed.mux_rangefeed.enabled'
(cluster.go:2220).Run: context canceled
test artifacts and logs in: /artifacts/cdc/mixed-versions/run_1
```

Parameters:
 - <code>ROACHTEST_arch=amd64</code>
 - <code>ROACHTEST_cloud=gce</code>
 - <code>ROACHTEST_coverageBuild=false</code>
 - <code>ROACHTEST_cpu=4</code>
 - <code>ROACHTEST_encrypted=false</code>
 - <code>ROACHTEST_fs=ext4</code>
 - <code>ROACHTEST_localSSD=true</code>
 - <code>ROACHTEST_metamorphicBuild=false</code>
 - <code>ROACHTEST_ssd=0</code>
<details><summary>Help</summary>
<p>

See: [roachtest README](https://github.com/cockroachdb/cockroach/blob/master/pkg/cmd/roachtest/README.md)

See: [How To Investigate \(internal\)](https://cockroachlabs.atlassian.net/l/c/SSSBr8c7)

See: [Grafana](https://go.crdb.dev/roachtest-grafana/teamcity-13388651/cdc-mixed-versions/1704369860626/1704371159073)

</p>
</details>
/cc @cockroachdb/cdc
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*cdc/mixed-versions.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)
</sub>

Jira issue: CRDB-35119

### PR DESCRIPTION
**Pull request by andyyang890**
This patch updates the `cdc/mixed-versions` roachtest to only attempt to set the mux rangefeeds cluster setting on pre-24.1 nodes.

Fixes #117315

Release note: None

### CODE REVIEW

**Comment by andyyang890** [comment]
Here's a successful TeamCity run: https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/13407308?hideProblemsFromDependencies=false&hideTestsFromDependencies=false

**Review by RaduBerinde — APPROVED** [review]

**Review by erikgrinaker — APPROVED** [review]
Thanks!

File: pkg/cmd/roachtest/tests/mixed_version_cdc.go [hunk 1]
```diff
@@ -426,14 +426,36 @@ func (cmvt *cdcMixedVersionTester) initWorkload(
...
 	}
-	// Mux setting only exists in 22.2 to 23.2 inclusive.
-	return cv.AtLeast(roachpb.MustParseVersion(v222CV)) &&
-		!cv.AtLeast(roachpb.MustParseVersion(v241CV)), nil
+
+	// If we are upgrading to 24.1, the setting is only known to pre-24.1 nodes.
+	if h.Context.ToVersion.Major() == 24 && h.Context.ToVersion.Minor() == 1 {
+		nodesInPreviousVersion := h.Context.NodesInPreviousVersion()
+		if len(nodesInPreviousVersion) > 0 {
+			return true, nodesInPreviousVersion, nil
```
Comment (renatolabs) [inline pkg/cmd/roachtest/tests/mixed_version_cdc.go:453]: A potential way to simplify, or just for awareness: this could also be written as:

```go
if h.Context.ToVersion.Major() == 24 && h.Context.ToVersion.Minor() == 1 && h.Context.MixedBinary() {
    return true, h.Context.NodesInPreviousVersion(), nil
}
```

**Review by renatolabs — APPROVED** [review]

File: pkg/cmd/roachtest/tests/mixed_version_cdc.go (hunk 1 above)
Comment (andyyang890) [reply pkg/cmd/roachtest/tests/mixed_version_cdc.go]: Updated, thanks for the tip!

**Comment by andyyang890** [comment]
TFTRs!

bors r=RaduBerinde,erikgrinaker,renatolabs
