### PR TITLE
opt: do not plan unnecessary paired semi- and anti- lookup joins

### LINKED ISSUE #87306: sql: internal error: lookup join with no lookup columns
When running SQLite logic tests with `--crdb_test` flag (which is currently not added in CI due to #58089) with
```
./dev testlogic sqlite --ignore-cache --config=local --files=slt_good_22 -- --test_env=COCKROACH_RANDOM_SEED='-6676986672122001987'
```
```
        /private/var/tmp/_bazel_yahor/e311b1c2454b7c301a6b73bddff450e7/sandbox/darwin-sandbox/2421/execroot/com_github_cockroachdb_cockroach/bazel-out/darwin-fastbuild/bin/pkg/sql/sqlitelogictest/tests/local/local_test_/local_test.runfiles/com_github_cockroachdb_cockroach/external/com_github_cockroachdb_sqllogictest/test/index/commute/10/slt_good_22.test:14596: SELECT pk FROM tab3 WHERE (col3 < 12 OR col0 BETWEEN 5 AND 30 AND (col1 >= 76.11) OR col3 = 95 OR col4 < 73.16 AND col1 IN (SELECT col4 FROM tab3 WHERE (col1 = 29.20 OR (((col0 > 3 AND ((col4 IS NULL AND (col3 IN (36,23,85,48,2,81)))))) OR col3 <= 2) AND col3 > 91 AND (col3 <= 54))) OR (col0 = 56) OR ((col4 <= 59.52)) OR col4 IN (29.33,64.35))
        expected success, but found
        (XX000) internal error: lookup join with no lookup columns
        check_expr.go:225: in CheckExpr()
        DETAIL: stack trace:
        github.com/cockroachdb/cockroach/pkg/sql/opt/memo/check_expr.go:225: CheckExpr()
        github.com/cockroachdb/cockroach/bazel-out/darwin-fastbuild/bin/pkg/sql/opt/memo/expr.og.go:24495: AddLookupJoinToGroup()
        github.com/cockroachdb/cockroach/pkg/sql/opt/xform/join_funcs.go:667: func1()
        github.com/cockroachdb/cockroach/pkg/sql/opt/xform/scan_index_iter.go:306: ForEachStartingAfter()
        github.com/cockroachdb/cockroach/pkg/sql/opt/xform/scan_index_iter.go:209: ForEach()
        github.com/cockroachdb/cockroach/pkg/sql/opt/xform/join_funcs.go:392: generateLookupJoinsImpl()
        github.com/cockroachdb/cockroach/pkg/sql/opt/xform/join_funcs.go:260: GenerateLookupJoins()
        github.com/cockroachdb/cockroach/bazel-out/darwin-fastbuild/bin/pkg/sql/opt/xform/explorer.og.go:1967: exploreSemiJoin()
        github.com/cockroachdb/cockroach/bazel-out/darwin-fastbuild/bin/pkg/sql/opt/xform/explorer.og.go:34: exploreGroupMember()
        github.com/cockroachdb/cockroach/pkg/sql/opt/xform/explorer.go:182: exploreGroup()
        github.com/cockroachdb/cockroach/pkg/sql/opt/xform/optimizer.go:529: optimizeGroup()
        github.com/cockroachdb/cockroach/pkg/sql/opt/xform/optimizer.go:291: optimizeExpr()
        github.com/cockroachdb/cockroach/pkg/sql/opt/xform/optimizer.go:571: optimizeGroupMember()
        github.com/cockroachdb/cockroach/pkg/sql/opt/xform/optimizer.go:516: optimizeGroup()
        github.com/cockroachdb/cockroach/pkg/sql/opt/xform/optimizer.go:291: optimizeExpr()
        github.com/cockroachdb/cockroach/pkg/sql/opt/xform/optimizer.go:571: optimizeGroupMember()
        github.com/cockroachdb/cockroach/pkg/sql/opt/xform/optimizer.go:516: optimizeGroup()
        github.com/cockroachdb/cockroach/pkg/sql/opt/xform/optimizer.go:291: optimizeExpr()
        github.com/cockroachdb/cockroach/pkg/sql/opt/xform/optimizer.go:571: optimizeGroupMember()
        github.com/cockroachdb/cockroach/pkg/sql/opt/xform/optimizer.go:516: optimizeGroup()
        github.com/cockroachdb/cockroach/pkg/sql/opt/xform/optimizer.go:291: optimizeExpr()
        github.com/cockroachdb/cockroach/pkg/sql/opt/xform/optimizer.go:571: optimizeGroupMember()
        github.com/cockroachdb/cockroach/pkg/sql/opt/xform/optimizer.go:516: optimizeGroup()
        github.com/cockroachdb/cockroach/pkg/sql/opt/xform/optimizer.go:291: optimizeExpr()
        github.com/cockroachdb/cockroach/pkg/sql/opt/xform/optimizer.go:571: optimizeGroupMember()
        github.com/cockroachdb/cockroach/pkg/sql/opt/xform/optimizer.go:516: optimizeGroup()
        github.com/cockroachdb/cockroach/pkg/sql/opt/xform/optimizer.go:291: optimizeExpr()
        github.com/cockroachdb/cockroach/pkg/sql/opt/xform/optimizer.go:571: optimizeGroupMember()
        github.com/cockroachdb/cockroach/pkg/sql/opt/xform/optimizer.go:516: optimizeGroup()
        github.com/cockroachdb/cockroach/pkg/sql/opt/xform/optimizer.go:291: optimizeExpr()
        github.com/cockroachdb/cockroach/pkg/sql/opt/xform/optimizer.go:571: optimizeGroupMember()
        github.com/cockroachdb/cockroach/pkg/sql/opt/xform/optimizer.go:516: optimizeGroup()
```
seems likely it's related to recent work by @mgartner, so I'm adding a release blocker label.

Jira issue: CRDB-19263

### PR DESCRIPTION
**Pull request by mgartner**
This commit fixes an issue where the optimizer would plan a paired semi
or anti lookup join in cases when a single lookup join would suffice.
This only occurred in rare cases when the join filter contained a
tautology or contradiction that could not be normalized to true or false
in the canonical query plan, but could be eliminated from the filters
when building a lookup join. If the tautology or contradiction
referenced a column not covered by the lookup index, the optimizer
mistakenly assumed that the index was not covering and planned a paired
join. Now the optimizer can recognize that the index is actually
covering, because the referenced column is not needed to evaluate the
filters, and a single lookup join is planned.

Fixes #87306

Release note (performance improvement): The optimizer now explores plans
with a single lookup join expressions in rare cases where it previously
planned two lookup join expressions.

### CODE REVIEW

File: pkg/sql/opt/xform/join_funcs.go [hunk 1]
```diff
@@ -515,13 +517,32 @@ func (c *CustomFuncs) generateLookupJoinsImpl(
...
+			// the secondary index not covering y.
+			//
+			// Note that these are special cases that only works for semi- and
 			// anti-joins because they never include columns from the right side
 			// in their output columns. Other joins include columns from the
 			// right side in their output columns, so even if the ON filters no
 			// longer reference an un-covered column, they must be fetched (case
 			// 2, see function comment).
-			filterColsFromRight := rightCols.Intersection(onFilters.OuterCols())
+			remainingFilterCols := rightKeyCols.Union(lookupJoin.On.OuterCols())
```
Comment (mgartner) [inline pkg/sql/opt/xform/join_funcs.go:544]: Hmm, I think I might need to include outer columns of the lookup expression here too...

**Review by michae2 — COMMENTED** [review]
The idea makes sense, but your comment below is undermining my confidence a bit haha :slightly_smiling_face:

> Reviewed 2 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/88491#-:-NCfxo_k9VGMOOjfuUN1:bl4333q)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @mgartner and @rytaft)

___
*[`pkg/sql/opt/xform/join_funcs.go` line 544 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/88491#-NCaRItcA0UDMJcwG565-r1-544:-NCbdA-P3_29oUjHw9lz:b4imy21) ([raw file](https://github.com/cockroachdb/cockroach/blob/27302db5e9208b9169e8ea004da409791cb03b92/pkg/sql/opt/xform/join_funcs.go#L544)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

Hmm, I think I might need to include outer columns of the lookup expression here too...
</blockquote></details>

I'm having trouble understanding the various columnsets in play here, and this comment is making me a little scared :slightly_smiling_face:
* Is `rightKeyCols` the columns from the join conditions that are part of the lookup index key?
* What are the outer columns of the lookup expression? Are those different from `lookupJoin.On.OuterCols()`?
* What is `onFilters.OuterCols()` and how is it different from `lookupJoin.On.OuterCols()`?

File: pkg/sql/opt/xform/join_funcs.go (hunk 1 above)
Comment (DrewKimball) [reply pkg/sql/opt/xform/join_funcs.go:544]: I think this is right... only the ON condition should need to see the right-side rows, while the lookup condition is only used to generate spans.

**Review by rytaft — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/88491#-:-NCuJ0mX5UaLBHB5cmIZ:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @DrewKimball, @mgartner, and @michae2)

___
*[`pkg/sql/opt/xform/join_funcs.go` line 538 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/88491#-NCuG8zG2HQYFXlMUbbO:-NCuG8zG2HQYFXlMUbbP:b-hz1u7m) ([raw file](https://github.com/cockroachdb/cockroach/blob/27302db5e9208b9169e8ea004da409791cb03b92/pkg/sql/opt/xform/join_funcs.go#L538)):*
> ```Go
> 			// the secondary index not covering y.
> 			//
> 			// Note that these are special cases that only works for semi- and
> ```

nit: only works -> only work
___
*[`pkg/sql/opt/xform/join_funcs.go` line 544 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/88491#-NCaRItcA0UDMJcwG565-r1-544:-NCuGu6hAtjIUoKQBbx_:b7pmuwr) ([raw file](https://github.com/cockroachdb/cockroach/blob/27302db5e9208b9169e8ea004da409791cb03b92/pkg/sql/opt/xform/join_funcs.go#L544)):*
<details><summary><i>Previously, DrewKimball (Drew Kimball) wrote…</i></summary><blockquote>

I think this is right... only the ON condition should need to see the right-side rows, while the lookup condition is only used to generate spans.
</blockquote></details>

You have this comment above `RightSideCols`:
```
	// RightSideCols is an ordered list of prefix index columns that are
	// constrained by this constraint. It corresponds 1:1 with the columns in
	// KeyCols if KeyCols is non-nil. Otherwise, it includes the prefix of index
	// columns constrained by LookupExpr.
```
Based on the last sentence there, I think this code is correct as-is (what @drewkimball said).

**Review by mgartner — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/88491)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @DrewKimball, @michae2, and @rytaft)

___
*[`pkg/sql/opt/xform/join_funcs.go` line 538 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/88491#-NCuG8zG2HQYFXlMUbbO:-NCzw4hvDYIJwiC-xxnW:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/27302db5e9208b9169e8ea004da409791cb03b92/pkg/sql/opt/xform/join_funcs.go#L538)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

nit: only works -> only work
</blockquote></details>

Done.
___
*[`pkg/sql/opt/xform/join_funcs.go` line 544 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/88491#-NCaRItcA0UDMJcwG565-r1-544:-NCzwPAu7Zf3GjygD9ak:b-eus6yg) ([raw file](https://github.com/cockroachdb/cockroach/blob/27302db5e9208b9169e8ea004da409791cb03b92/pkg/sql/opt/xform/join_funcs.go#L544)):*
Ok good, I agree that this looks fine as-is.

> Is rightKeyCols the columns from the join conditions that are part of the lookup index key?

`rightKeyCols` contains the columns in the lookup index that are constrained by either the key columns or the lookup expression.

> What are the outer columns of the lookup expression? Are those different from lookupJoin.On.OuterCols()?

Outer columns of the lookup expression all come from the left side of the join. As Drew pointed out, the column values of each input row are substituted in the lookup expression to generate lookup spans.

> What is onFilters.OuterCols() and how is it different from lookupJoin.On.OuterCols()?

This one is tricky. There's 3 versions of the on filters, each one slightly different:

1. `on` - These are the original ON filters passed as an argument to the function.
2. `onFilters` - These are the same as `on` unless the lookup index is a partial index. In that case, `onFilters` may be a subset of `on` which has been reduced because they match the partial index predicate. For example, if the original ON condition is `ON t1.id = t2.id AND t2.deleted = false` and there exists `INDEX t2(id) WHERE deleted = false`, then `on` would be `t1.id = t2.id AND t2.deleted = false` and `onFilters` would be `t1.id = t2.id`. The `t2.deleted = false` no longer needs to be applied explicitly because a lookup into the partial index implicitly applies that filter.
3. `lookupJoin.On` - These are the remaining filters after the lookup constraint has been built. They are the same as `lookupConstraint.RemainingFilters`:

```
	// RemainingFilters contains explicit ON filters that are not represented by
	// KeyCols or LookupExpr. These filters must be included as ON filters in
	// the lookup join.
```

In order words, these filters could not be part of the lookup spans themselves, so they must be applied after the lookup is performed.

**Comment by mgartner** [comment]
It might be good to backport this into v22.2.1 so I've added the label.

**Comment by mgartner** [comment]
TFTRs!

bors r+
