### PR TITLE
backupccl: allow user to run SHOW BACKUP on an encrypted incremental backup

### LINKED ISSUE #77984: backupccl: support SHOW BACKUP <incremental_location> WITH KMS=blah;
Using the old backup syntax, `SHOW BACKUP <incremental_location> WITH KMS='blah'` fails because the `ENCRYPTION-INFO` file is stored in the full backup directory, not in the incremental directory. 

To reproduce: 
```
// Run a full backup with encryption
BACKUP TO <full_location> WITH KMS=<uri>

// Create a remote incremental with encryption
BACKUP TO <incremental_location> INCREMENTAL FROM <full_location> WITH KMS=<uri>;

// fail running show backup on the incremental backup
SHOW BACKUP <incremental_location> WITH KMS=<uri>
```

How ought we support `SHOW BACKUP <incremental_location> WITH KMS=<uri>`?
1. I think we should add a `kms_dir` option that users must point to their full backup directory. Only code in the show backup would path would get changed.
2. an alternative that @adityamaru and I ruled out over slack: write `ENCRYPTION-INFO` to every incremental backup during planning. This approach has two drawbacks:
   - encrypted incremental backups created before this patch would still have the bug
   - serious surgery would be required for `ALTER BACKUPS`, as the cmd would need to alter the encryption info in every backup in a given chain-- which is hard to do since some backups were created with the new and old backup location syntax. 

Code walkthrough of bug: SHOW BACKUP fails on the encrypted incremental backup because the `ENCRYPTION-INFO` file only gets written in the full backup directory. Why? During `backup_planning.go` for the incremental backup, `fetchPreviousBackups` gets the full backup's `encryptionOptions`, preventing `makeNewEncryptionOptions` from running and populating `encryptionInfo`.  Then, in `backup_job`,  `writeEncryptionInfoIfNotExists` doesn't get called because `details.EncryptionInfo==nil`. 

With collections for SHOW BACKUP and BACKUP, there's no bug.

Jira issue: CRDB-13885

### PR DESCRIPTION
**Pull request by msbutler**
Previously, SHOW BACKUP <incremental_location> WITH kms='blah' (or with
encryption_passphrase) failed because the ENCRYPTION-INFO file is stored in the
full backup directory, not in the incremental directory. This patch adds the
encryption_dir parameter to SHOW BACKUP, which the user must set to the full
backup directory in order to view an incremental backup created with kms or an
encryption passphrase.

Fixes #77984

Release note (sql change): when the user runs SHOW BACKUP
on an encrypted incremental backup created using the deprecated backup syntax, they must set the encryption_info_dir directory
to the full backup directory in order for SHOW BACKUP to work.

### CODE REVIEW

**Comment by msbutler** [comment]
technically, the test only covers backups with `encryption_passphrase` as the kms subtest gets skipped. To prep for a cleaner backport, I stashed a change  to the kms roachtest that I can open into a seperate PR.

File: pkg/ccl/backupccl/show.go [hunk 1]
```diff
@@ -324,9 +325,16 @@ func showBackupPlanHook(
 		}
 		defer store.Close()
 
+		encStore := store
```
Comment (adityamaru) [inline pkg/ccl/backupccl/show.go:328]: Lets add a comment that fleshes out the need for this options.

File: pkg/ccl/backupccl/manifest_handling.go [hunk 2]
```diff
@@ -1098,8 +1098,11 @@ func readEncryptionOptions(
 	ctx context.Context, src cloud.ExternalStorage,
 ) ([]jobspb.EncryptionInfo, error) {
 	files, err := getEncryptionInfoFiles(ctx, src)
+	wrappedError := `could not find or read encryption information.
```
Comment (adityamaru) [inline pkg/ccl/backupccl/manifest_handling.go:1101]: I'd prefer if we did this in the following way:

let readEncryptionOptions returned a marked error when it is unable to find the encryption info file, you can checkout `errors.Mark`. The callsite in SHOW BACKUP that calls readEncryptionOptions should then check for this mark, and issue an `errors.WithHint`. This method is used by more than just show and so I'd prefer not having this NOTE in this shared path.

File: pkg/ccl/backupccl/backup_planning.go [hunk 3]
```diff
@@ -67,6 +67,7 @@ const (
 	localityURLParam          = "COCKROACH_LOCALITY"
 	defaultLocalityValue      = "default"
 	backupOptDebugMetadataSST = "debug_dump_metadata_sst"
+	backupOptEncDir           = "encryption_dir"
```
Comment (adityamaru) [inline pkg/ccl/backupccl/backup_planning.go:70]: I noted this in the original slack thread too, but for the sake of discussion what if we made this more general than just `encryption_dir`. The only time we need users to specify this additional path to the base backup is when `SHOW BACKUP` is being pointed to an incremental. What if we used:

`SHOW BACKUP x WITH KMS = '…' INCREMENTAL FROM '<base_backup>'` instead?

**Review by adityamaru — CHANGES_REQUESTED** [review]

File: pkg/ccl/backupccl/manifest_handling.go (hunk 2 above)
Comment (msbutler) [reply pkg/ccl/backupccl/manifest_handling.go]: done. interestingly, the marked error does not get wrapped; hence the gymnastics in manifest_handling.go.

File: pkg/ccl/backupccl/show.go (hunk 1 above)
Comment (msbutler) [reply pkg/ccl/backupccl/show.go:332]: Done

File: pkg/ccl/backupccl/backup_planning.go (hunk 3 above)
Comment (msbutler) [reply pkg/ccl/backupccl/backup_planning.go]: resolved in slack. keeping original approach.

**Review by adityamaru — APPROVED** [review]

File: pkg/ccl/backupccl/manifest_handling.go [hunk 4]
```diff
@@ -1099,7 +1101,7 @@ func readEncryptionOptions(
 ) ([]jobspb.EncryptionInfo, error) {
 	files, err := getEncryptionInfoFiles(ctx, src)
 	if err != nil {
-		return nil, errors.Wrap(err, "could not find or read encryption information")
+		return nil, errors.Mark(errors.Wrap(err, encryptionReadErrorMsg), errEncryptionInfoRead)
```
[the remark this answers is not in the document]
Comment (msbutler) [reply pkg/ccl/backupccl/manifest_handling.go:1105]: oops! should have looked at all th errors in readEncryptionOptions. Only the first one will pickup this bug; thus its the only error that should get marked. good catch!

File: pkg/ccl/backupccl/show.go [hunk 5]
```diff
@@ -324,9 +325,26 @@ func showBackupPlanHook(
...
+			defer encStore.Close()
+		}
 		var encryption *jobspb.BackupEncryptionOptions
+		showEncErr := `HINT: If you are running SHOW BACKUP exclusively on an incremental backup, 
+you must pass the 'encryption_info_dir' parameter that points to the directory of your full backup`
 		if passphrase, ok := opts[backupOptEncPassphrase]; ok {
-			opts, err := readEncryptionOptions(ctx, store)
+			opts, err := readEncryptionOptions(ctx, encStore)
+			if errors.Is(err, errEncryptionInfoRead) {
+				return errors.WithHintf(err, showEncErr)
```
[the remark this answers is not in the document]
Comment (msbutler) [reply pkg/ccl/backupccl/show.go]: Done

File: pkg/ccl/backupccl/show.go [hunk 6]
```diff
@@ -324,9 +325,26 @@ func showBackupPlanHook(
 		}
 		defer store.Close()
 
+		// A user that calls BACKUP TO <incremental_dir> on an encrypted incremental
```
[the remark this answers is not in the document]
Comment (msbutler) [reply pkg/ccl/backupccl/show.go]: Done

File: pkg/ccl/backupccl/show.go [hunk 7]
```diff
@@ -324,9 +325,26 @@ func showBackupPlanHook(
 		}
 		defer store.Close()
 
+		// A user that calls SHOW BACKUP TO <incremental_dir> on an encrypted incremental
```
Comment (adityamaru) [inline pkg/ccl/backupccl/show.go:328]: nit: drop the TO

File: pkg/ccl/backupccl/show.go [hunk 8]
```diff
@@ -336,7 +354,10 @@ func showBackupPlanHook(
 				Key:  encryptionKey,
 			}
 		} else if kms, ok := opts[backupOptEncKMS]; ok {
-			opts, err := readEncryptionOptions(ctx, store)
+			opts, err := readEncryptionOptions(ctx, encStore)
+			if errors.Is(err, errEncryptionInfoRead) {
+				return errors.WithHintf(err, showEncErr)
```
Comment (adityamaru) [inline pkg/ccl/backupccl/show.go:359]: nit: s/errors.WithHintf/errors.WithHint/g

**Review by adityamaru — APPROVED** [review]

File: pkg/ccl/backupccl/show.go (hunk 7 above)
Comment (msbutler) [reply pkg/ccl/backupccl/show.go]: ooof. apologies for my sloppiness. thanks for catching these little nits!

File: pkg/ccl/backupccl/show.go (hunk 8 above)
Comment (msbutler) [reply pkg/ccl/backupccl/show.go]: Done.

**Comment by msbutler** [comment]
TFTR!!

bors r=adityamaru
