### PR TITLE
sql/catkv: refresh stale name->ID mappings in SystemDatabaseCache

### LINKED ISSUE #153555: roachtest: c2c/kv0 failed
roachtest.c2c/kv0 [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/20472139?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/20472139?buildTab=artifacts#/c2c/kv0) on master @ [e7245933f8b6ca04a728d459b0f8f91df0a9177a](https://github.com/cockroachdb/cockroach/commits/e7245933f8b6ca04a728d459b0f8f91df0a9177a):

```
(sql_runner.go:286).Scan: error scanning '&{0xc00a2178c0 <nil>}': pq: internal error while retrieving user account memberships: resolved privileges to 100052 but found no descriptor with id 100052: referenced descriptor ID 100052: looking up ID 100052: descriptor not found
(1) pq: internal error while retrieving user account memberships: resolved privileges to 100052 but found no descriptor with id 100052: referenced descriptor ID 100052: looking up ID 100052: descriptor not found
Error types: (1) *pq.Error
(monitor.go:267).Wait: monitor failure: monitor user task failed: t.Fatal() was called
test artifacts and logs in: /artifacts/c2c/kv0/run_1
```

Parameters:
 - <code>arch=amd64</code>
 - <code>cloud=gce</code>
 - <code>coverageBuild=false</code>
 - <code>cpu=8</code>
 - <code>encrypted=false</code>
 - <code>fs=ext4</code>
 - <code>localSSD=false</code>
 - <code>metamorphicLeases=default</code>
 - <code>runtimeAssertionsBuild=false</code>
 - <code>ssd=0</code>
<details><summary>Help</summary>
<p>

See: [roachtest README](https://github.com/cockroachdb/cockroach/blob/master/pkg/cmd/roachtest/README.md)

See: [How To Investigate \(internal\)](https://cockroachlabs.atlassian.net/l/c/SSSBr8c7)

See: [Grafana](https://go.crdb.dev/roachtest-grafana/teamcity-20472139/c2c-kv0/1758011851792/1758012782683)

</p>
</details>
/cc @cockroachdb/disaster-recovery
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*c2c/kv0.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/bazci/githubpost/issues)

</sub>

Jira issue: CRDB-54488

### PR DESCRIPTION
**Pull request by dt**
The per-node `SystemDatabaseCache` holds name→ID mappings for system database namespace entries for the lifetime of the process. Until now it treated the first observation of any name as authoritative: once a name was cached, subsequent observations of the same name with a different ID were silently dropped. The comment on the type even codified this as an assumption (_"for a given name and a given cluster version, the name to ID mapping will never change for the life of process"_).

That assumption does not hold for PCR reader tenants. A reader tenant is bootstrapped with its own dynamically-allocated IDs for system tables that lack a fixed reserved-range ID (e.g. `system.privileges`), and then `SetupOrAdvanceStandbyReaderCatalog` rewrites the namespace to point those names at the externalized descriptors replicated from the source tenant, which carry the source's IDs.

Any cache entry populated between reader tenant startup and that rewrite — and the very first user authentication populates one for `system.privileges` via the synthetic privilege cache — pins the bootstrap-time ID forever. Since the rewrite also deletes the descriptor at the bootstrap-time ID, every subsequent name resolution that hits the cache returns an ID that no descriptor exists for, and lookups fail with `resolved <name> to <id> but found no descriptor with id <id>`. Restarting the reader tenant masks the bug because it discards the cache.

This change permits the cache to replace an existing entry when an incoming observation has the same name but a different ID and a strictly newer MVCC timestamp than the cached entry. The MVCC timestamp guard ensures a stale read at an older AOST cannot regress a fresher mapping, and the same check is repeated under the write lock in `update` so a concurrent fresher write cannot be clobbered by a slower stale one. The warm-up entries inserted at construction carry a zero MVCC timestamp, so any real KV-sourced observation dominates them, which is the desired behavior.

Resolves #153555.

Epic: none
Release note (bug fix): A physical cluster replication reader tenant no longer fails authentication and other queries with errors of the form `resolved <name> to <id> but found no descriptor with id <id>` after the reader tenant ingests a system table at an ID different from the one it was bootstrapped with. Previously, a per-node namespace cache could pin the bootstrap-time ID and require a tenant restart to recover.

### CODE REVIEW

File: pkg/sql/catalog/internal/catkv/system_database_cache.go [hunk 1]
```diff
@@ -134,6 +134,17 @@ func (c *SystemDatabaseCache) update(version clusterversion.ClusterVersion, in n
 		c.mu.m[version.Version] = cached
 	}
 	for _, e := range nameCandidates {
+		// Re-check under the write lock: a concurrent update may have raced ahead
```
Comment (msbutler) [inline pkg/sql/catalog/internal/catkv/system_database_cache.go:143]: to reduce the blast radius of this backportable change, should we plumb `isReaderTenant` on to the `SystemDatabaseCache`, and then gate this check?

Comment (dt) [reply pkg/sql/catalog/internal/catkv/system_database_cache.go:143]: I'd lean against gating: I think this fix is correct for any caller, not just reader tenants.

The doctype comment on `SystemDatabaseCache` already anticipates this case: _"It only comes into use if we rename or drop a system object during a cluster version upgrade migration. This possibly has never happened yet, but it's safer to be a bit defensive..."_ The current code is silently broken for that scenario; this change makes it work. Restricting it to reader tenants would re-leave it broken for the case the original author specifically called out.

The new path is also narrow by construction — it triggers only when `existing.ID != incoming.ID && existing.MVCCTimestamp < incoming.MVCCTimestamp`. For non-reader tenants nothing produces that input today, so for them this is effectively dead code. The blast-radius concern is theoretical.

If you'd still rather have a kill switch on release branches, I'd reach for a cluster setting (default on) over plumbing `isReaderTenant`, but I don't think we need one.

Comment (dt) [reply pkg/sql/catalog/internal/catkv/system_database_cache.go:143]: David actual: absolutely not on the cluster setting. we can plumb the flag if you really want but IMO the behavior is either more correct -- and thus is correct for everyone -- or it isn't, but no reason to add the special case.

Comment (fqazi) [reply pkg/sql/catalog/internal/catkv/system_database_cache.go:143]: Its okay to generally make this change, and the change is small enough on its own. I worry about plumbing increasing complexity. 

Also playings devils advocate, we may just want to consider always blanket updating namespace entries if a new MVCC timestamp exists. But, we can leave that for the future for scenarios where renames occur, etc...

**Review by fqazi — APPROVED** [review]
:lgtm_strong: 

Looks good!

> @fqazi reviewed 4 files and all commit messages, and made 3 comments.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/169044#-:-OqzzsmVDAvXV5sQtr59:brut7ol)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on dt and msbutler).

___
*[`pkg/sql/catalog/internal/catkv/system_database_cache.go` line 26 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/169044#-Oqzzc-l7lMXVZOfmcN-:-Oqzzc-l7lMXVZOfmcN0:bjyq279) ([raw file](https://github.com/cockroachdb/cockroach/blob/e4bc5879e16c2314fed7189d72cad304874ace38/pkg/sql/catalog/internal/catkv/system_database_cache.go#L26)):*
> ```Go
> // SystemDatabaseCache is used to cache the system descriptor IDs.
> // We get to assume that for a given name and a given cluster version, the name
> // to ID mapping will never change for the life of process.
> ```

nit: we can update the text here

File: pkg/sql/catalog/internal/catkv/system_database_cache.go (hunk 1 above)
Comment (fqazi) [reply pkg/sql/catalog/internal/catkv/system_database_cache.go:143]: Actually my previous suggestion of the MVCC timestamp always updating would be problematic if the timestamp isn't from the namespace table.

**Review by fqazi — APPROVED** [review]
> @fqazi made 1 comment.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/169044)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on dt and msbutler).

**Review by msbutler — APPROVED** [review]

**Comment by dt** [comment]
> nit: we can update the text here

Done.

**Comment by dt** [comment]
TFTR!

/trunk merge
