### PR TITLE
roachtest: mark cluster as expected to die in validate_system_schema_after_version_upgrade

### LINKED ISSUE #148981: roachtest: validate-system-schema-after-version-upgrade/separate-process failed
roachtest.validate-system-schema-after-version-upgrade/separate-process [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/20042624?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/20042624?buildTab=artifacts#/validate-system-schema-after-version-upgrade/separate-process) on master @ [d94e3501a43b45740331a70ddfddd9f08f567971](https://github.com/cockroachdb/cockroach/commits/d94e3501a43b45740331a70ddfddd9f08f567971):

```
(test_monitor.go:35).func1: test monitor: unexpected node event: n3: cockroach process for virtual cluster "mixed-version-tenant-sducq", instance 0 died (exit code 137)
(cluster.go:2485).Wipe: one or more parallel execution failure(s): context canceled
test artifacts and logs in: /artifacts/validate-system-schema-after-version-upgrade/separate-process/run_1
```

Parameters:
 - <code>arch=amd64</code>
 - <code>cloud=gce</code>
 - <code>coverageBuild=false</code>
 - <code>cpu=4</code>
 - <code>encrypted=false</code>
 - <code>mvtDeploymentMode=separate-process</code>
 - <code>mvtVersions=v25.2.1 → master</code>
 - <code>runtimeAssertionsBuild=false</code>
 - <code>ssd=0</code>
<details><summary>Help</summary>
<p>

See: [roachtest README](https://github.com/cockroachdb/cockroach/blob/master/pkg/cmd/roachtest/README.md)

See: [How To Investigate \(internal\)](https://cockroachlabs.atlassian.net/l/c/SSSBr8c7)

See: [Grafana](https://go.crdb.dev/roachtest-grafana/teamcity-20042624/validate-system-schema-after-version-upgrade-separate-process/1751007274868/1751007652635)

</p>
</details>
/cc @cockroachdb/sql-foundations
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*validate-system-schema-after-version-upgrade/separate-process.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/bazci/githubpost/issues)

</sub>

### LINKED ISSUE #148998: roachtest: validate-system-schema-after-version-upgrade/separate-process failed
roachtest.validate-system-schema-after-version-upgrade/separate-process [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/20042778?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/20042778?buildTab=artifacts#/validate-system-schema-after-version-upgrade/separate-process) on release-25.3 @ [50a2d61d2543dc79ec72fd9dc8494592ce3de97f](https://github.com/cockroachdb/cockroach/commits/50a2d61d2543dc79ec72fd9dc8494592ce3de97f):

```
(test_monitor.go:35).func1: test monitor: unexpected node event: n1: cockroach process for virtual cluster "mixed-version-tenant-yfwnm", instance 0 died (exit code 137)
(cluster.go:2485).Wipe: one or more parallel execution failure(s): context canceled
test artifacts and logs in: /artifacts/validate-system-schema-after-version-upgrade/separate-process/run_1
```

Parameters:
 - <code>arch=amd64</code>
 - <code>cloud=gce</code>
 - <code>coverageBuild=false</code>
 - <code>cpu=4</code>
 - <code>encrypted=false</code>
 - <code>mvtDeploymentMode=separate-process</code>
 - <code>mvtVersions=v24.3.14 → v25.2.1 → release-25.3</code>
 - <code>runtimeAssertionsBuild=false</code>
 - <code>ssd=0</code>
<details><summary>Help</summary>
<p>

See: [roachtest README](https://github.com/cockroachdb/cockroach/blob/master/pkg/cmd/roachtest/README.md)

See: [How To Investigate \(internal\)](https://cockroachlabs.atlassian.net/l/c/SSSBr8c7)

See: [Grafana](https://go.crdb.dev/roachtest-grafana/teamcity-20042778/validate-system-schema-after-version-upgrade-separate-process/1751022238199/1751023505117)

</p>
</details>
<details><summary>Same failure on other branches</summary>
<p>

- #148981 roachtest: validate-system-schema-after-version-upgrade/separate-process failed [C-test-failure O-roachtest O-robot T-sql-foundations branch-master release-blocker]
</p>
</details>
/cc @cockroachdb/sql-foundations
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*validate-system-schema-after-version-upgrade/separate-process.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/bazci/githubpost/issues)

</sub>

### PR DESCRIPTION
**Pull request by rafiss**
Before wiping the cluster, we need to indicate to the test that the
cluster is going to go down. This is needed after
eae1e78.

fixes #148981
fixes #148998

Release note: None

### CODE REVIEW

**Comment by rafiss** [comment]
Testing here: https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/20081655?hideProblemsFromDependencies=false&hideTestsFromDependencies=false

File: pkg/cmd/roachtest/tests/validate_system_schema_after_version_upgrade.go [hunk 1]
```diff
@@ -134,7 +134,13 @@ func validateSystemSchemaAfterUpgradeTest(
 	mvt.Run()
 
 	// Start a cluster with the latest binary and get the system schema
-	// from the cluster.
+	// from the cluster. Mark all processes as expected to die before wiping.
+	t.Monitor().ExpectProcessDead(c.All())
```
Comment (DarrylWong) [inline pkg/cmd/roachtest/tests/validate_system_schema_after_version_upgrade.go:138]: `c.Wipe` already calls `c.t.Monitor().ExpectProcessDead(selectedNodesOrDefault(nodes, c.All()))` so this should be unnecessary. No harm in calling it again but more curious if you ran into any issues without this line as that would indicate a bug.

**Review by DarrylWong — APPROVED** [review]
Ah, I missed the fact that wiping all the system tenants would cause the SQL pods to die as well. Sorry for the noise and thanks for fixing!

File: pkg/cmd/roachtest/tests/validate_system_schema_after_version_upgrade.go (hunk 1 above)
Comment (rafiss) [reply pkg/cmd/roachtest/tests/validate_system_schema_after_version_upgrade.go:138]: This line wasn't needed; but I thought it would be more clear to include it as long as we needed to explicitly do this for virtual clusters.

**Comment by rafiss** [comment]
tftr!

bors r+
