### PR TITLE
bazel: run `yarn --check-files` to validate `node_modules` consistency

### LINKED ISSUE #70867: bazel: build fails with "could not find dependency" npm error
**Describe the problem**

When running ./dev babel generate I'm getting back following error:

```
Loading: 
Loading: 0 packages loaded
Analyzing: target //:gazelle (0 packages loaded, 0 targets configured)
INFO: Analyzed target //:gazelle (1 packages loaded, 390 targets configured).
INFO: Found 1 target...
WARNING: failed to create one or more convenience symlinks for prefix '_bazel/':
  cannot create symbolic link bazel-out -> /private/var/tmp/_bazel_user/3de4b0d5f2cd1e24107aaf9b3a0a01a6/execroot/cockroach/bazel-out:  /Users/user/go/src/github.com/cockroachdb/cockroach/bazel-out (File exists)
[0 / 2] [Prepa] BazelWorkspaceStatusAction stable-status.txt
Target //:gazelle up-to-date:
  _bazel/bin/gazelle-runner.bash
  _bazel/bin/gazelle
INFO: Elapsed time: 1.037s, Critical Path: 0.00s
INFO: 1 process: 1 internal.
INFO: Build completed successfully, 1 total action
INFO: Running command line: _bazel/bin/gazelle update-repos '-from_file=go.mod' '-build_file_proto_mode=disable_global' '-to_macro=DEPS.bzl%go_deps' '-prune=true'
INFO: Build completed successfully, 1 total action
Loading: 
Loading: 0 packages loaded
INFO: Build option --run_under has changed, discarding analysis cache.
Analyzing: target //pkg/cmd/generate-test-suites:generate-test-suites (0 packages loaded, 0 targets configured)
INFO: Analyzed target //pkg/cmd/generate-test-suites:generate-test-suites (0 packages loaded, 7402 targets configured).
INFO: Found 1 target...
WARNING: failed to create one or more convenience symlinks for prefix '_bazel/':
  cannot create symbolic link bazel-out -> /private/var/tmp/_bazel_user/3de4b0d5f2cd1e24107aaf9b3a0a01a6/execroot/cockroach/bazel-out:  /Users/user/go/src/github.com/cockroachdb/cockroach/bazel-out (File exists)
[0 / 4] [Prepa] BazelWorkspaceStatusAction stable-status.txt
Target //pkg/cmd/generate-test-suites:generate-test-suites up-to-date:
  _bazel/bin/pkg/cmd/generate-test-suites/generate-test-suites_/generate-test-suites
INFO: Elapsed time: 1.223s, Critical Path: 0.00s
INFO: 1 process: 1 internal.
INFO: Build completed successfully, 1 total action
INFO: Running command line: /bin/bash -c 'cd /Users/user/go/src/github.com/cockroachdb/cockroach &&  _bazel/bin/pkg/cmd/generate-test-suites/generate-test-suites_/generate-test-suites '
INFO: Build completed successfully, 1 total action
2021/09/29 16:12:31 Could not query Bazel tests: got error exit status 7
2021/09/29 16:12:31 Got error output: Loading: 0 packages loaded
Loading: 1 packages loaded
    currently loading: pkg/ui/workspaces/db-console ... (4 packages)
Loading: 1 packages loaded
    currently loading: pkg/ui/workspaces/db-console ... (4 packages)
Loading: 1 packages loaded
    currently loading: pkg/ui/workspaces/db-console ... (4 packages)
INFO: Repository npm instantiated at:
  /Users/user/go/src/github.com/cockroachdb/cockroach/WORKSPACE:67:13: in <toplevel>
  /private/var/tmp/_bazel_user/3de4b0d5f2cd1e24107aaf9b3a0a01a6/external/build_bazel_rules_nodejs/index.bzl:83:18: in yarn_install
Repository rule yarn_install defined at:
  /private/var/tmp/_bazel_user/3de4b0d5f2cd1e24107aaf9b3a0a01a6/external/build_bazel_rules_nodejs/internal/npm_install/npm_install.bzl:890:31: in <toplevel>
Loading: 1 packages loaded
    currently loading: pkg/ui/workspaces/db-console ... (4 packages)
ERROR: An error occurred during the fetch of repository 'npm':
   Traceback (most recent call last):
	File "/private/var/tmp/_bazel_user/3de4b0d5f2cd1e24107aaf9b3a0a01a6/external/build_bazel_rules_nodejs/internal/npm_install/npm_install.bzl", line 888, column 24, in _yarn_install_impl
		_create_build_files(repository_ctx, "yarn_install", node, repository_ctx.attr.yarn_lock, repository_ctx.attr.generate_local_modules_build_files)
	File "/private/var/tmp/_bazel_user/3de4b0d5f2cd1e24107aaf9b3a0a01a6/external/build_bazel_rules_nodejs/internal/npm_install/npm_install.bzl", line 465, column 13, in _create_build_files
		fail("generate_build_file.ts failed: \nSTDOUT:\n%s\nSTDERR:\n%s" % (result.stdout, result.stderr))
Error in fail: generate_build_file.ts failed: 
STDOUT:

STDERR:
could not find dependency '@babel/helper-define-map' of 'babel-preset-react-app/node_modules/@babel/preset-env/node_modules/@babel/plugin-transform-classes'
ERROR: Error fetching repository: Traceback (most recent call last):
	File "/private/var/tmp/_bazel_user/3de4b0d5f2cd1e24107aaf9b3a0a01a6/external/build_bazel_rules_nodejs/internal/npm_install/npm_install.bzl", line 888, column 24, in _yarn_install_impl
		_create_build_files(repository_ctx, "yarn_install", node, repository_ctx.attr.yarn_lock, repository_ctx.attr.generate_local_modules_build_files)
	File "/private/var/tmp/_bazel_user/3de4b0d5f2cd1e24107aaf9b3a0a01a6/external/build_bazel_rules_nodejs/internal/npm_install/npm_install.bzl", line 465, column 13, in _create_build_files
		fail("generate_build_file.ts failed: \nSTDOUT:\n%s\nSTDERR:\n%s" % (result.stdout, result.stderr))
Error in fail: generate_build_file.ts failed: 
STDOUT:

STDERR:
could not find dependency '@babel/helper-define-map' of 'babel-preset-react-app/node_modules/@babel/preset-env/node_modules/@babel/plugin-transform-classes'
ERROR: generate_build_file.ts failed: 
STDOUT:

STDERR:
could not find dependency '@babel/helper-define-map' of 'babel-preset-react-app/node_modules/@babel/preset-env/node_modules/@babel/plugin-transform-classes'
Loading: 1 packages loaded
    currently loading: pkg/ui/workspaces/db-console ... (4 packages)
Loading: 1 packages loaded
    currently loading: pkg/ui/workspaces/db-console ... (4 packages)
ERROR: exit status 1

```

using make to build cockroach works fine with/without ui.

**To Reproduce**

Using commit: 55e2bcd4affa844b8288da23407649d8f52a1e23
run
`./dev generate bazel
`

Building under macos, using bazelisk.

Epic CRDB-8036

### PR DESCRIPTION
**Pull request by koorosh**
Resolves: https://github.com/cockroachdb/cockroach/issues/70867

Before, running `make build` and then `dev build` caused bazel build
to fail because of missing `node_modules` dependencies.

One of possible reasons of these might be in Make target `pkg/ui/yarn.installed`,
where `@types/node` module is removed manually after running `yarn install`
(`rm -rf pkg/ui/node_modules/@types/node`). It leads to the state where missing
package in `node_modules` cannot be found by `bazel`.

Current change resolves this issue by running `yarn --check-files` command
before every bazel build that includes ui, to ensure consistency of `node_modules`.

Release note: none

### CODE REVIEW

File: pkg/cmd/dev/build.go [hunk 1]
```diff
@@ -110,6 +110,15 @@ func (d *dev) build(cmd *cobra.Command, commandLine []string) error {
 	args = append(args, additionalBazelArgs...)
 
 	if cross == "" {
+		// run "yarn --check-files" before any bazel target that includes UI to ensure that node_modules dir is consistent
+		// see related issue: https://github.com/cockroachdb/cockroach/issues/70867
+		for _, arg := range args {
+			if arg == "--config=with_ui" {
+				logCommand("bazel", "run", "@nodejs//:yarn", "--", "--check-files", "--cwd", "pkg/ui", "--offline")
+				d.exec.CommandContextInheritingStdStreams(ctx, "bazel", "run", "@nodejs//:yarn", "--", "--check-files", "--cwd", "pkg/ui", "--offline")
```
Comment (rickystewart) [inline pkg/cmd/dev/build.go:118]: This will require some updates to the test files.

**Review by rickystewart — CHANGES_REQUESTED** [review]

**Review by sjbarag — APPROVED** [review]
This makes sense — thanks for keeping these consistent, @koorosh !

File: pkg/cmd/dev/build.go (hunk 1 above)
Comment (rickystewart) [reply pkg/cmd/dev/build.go:118]: Hey @koorosh -- 

* In `pkg/cmd/dev/testdata/build.txt` you'll find a bunch of test cases along with all the OS operations each of those test cases will run. At a glance, it looks like the `dev build --skip-generate -- --verbose_failures --sandbox_debug` test case is the only one affected by your change. It looks like you will have to add a `bazel run @nodejs//:yarn -- --check-files --cwd pkg/ui --offline` line, before the build proper.
* Then in `pkg/cmd/dev/testdata/recording/build.txt` there are the recordings for all of those test cases. Add the following in the appropriate spot:

```
bazel run @nodejs//:yarn -- --check-files --cwd pkg/ui --offline
----

```

That should be it. You can DM me for any more questions.

Comment (rickystewart) [reply pkg/cmd/dev/build.go:118]: Oh, you can `dev test pkg/cmd/dev` to test your changes.

Comment (koorosh) [reply pkg/cmd/dev/build.go:118]: Thank you @rickystewart !

Comment (koorosh) [reply pkg/cmd/dev/build.go]: Done!

**Comment by rickystewart** [comment]
bors r=sjbarag
