### PR TITLE
sql: respect IF NOT EXISTS in CREATE EXTERNAL CONNECTION

### LINKED ISSUE #116997: CREATE EXTERNAL CONNECTION IF NOT EXISTS does not work as expected
**Describe the problem**
I have some sql scripts which i run inside a kubernetes job for DB Setup on every deployment. Goal is to run them idempotent.

**To Reproduce**
Run create external connection twice:
```
CREATE EXTERNAL CONNECTION IF NOT EXISTS azure AS "azure://${AZURE_STORAGE_CONTAINER}/${NAMESPACE}?AUTH=specified&AZURE_ACCOUNT_NAME=${AZURE_ACCOUNT_NAME}&AZURE_TENANT_ID=${AZURE_TENANT_ID}&AZURE_CLIENT_ID=${AZURE_CLIENT_ID}&AZURE_CLIENT_SECRET=${AZURE_CLIENT_SECRET}&AZURE_ENVIRONMENT=AZUREPUBLICCLOUD";
```

I would have not created that issue if not i found that file for test data in the repo:
https://github.com/cockroachdb/cockroach/blob/master/pkg/sql/parser/testdata/create_external_connection#L10

The docs state that "IF NOT EXISTS" does not work:
https://www.cockroachlabs.com/docs/stable/create-external-connection#synopsis

However the SQL Command fails with:
```
ERROR: failed to create external connection: external connection with connection name 'azure' already exists                                                                                                                                  
SQLSTATE: 42710
```

Please clarify if "CREATE EXTERNAL CONNECTION IF NOT EXISTS" does exist or how to reach idempotency here.

Cockroach Version is: v23.1.5

Jira issue: CRDB-34893

### PR DESCRIPTION
**Pull request by stevendanna**
Previously, while the IF NOT EXISTS syntax was allowed nothing checked the boolean on the constructed tree node. Here, we check the boolean and elide DuplicateViolation errors from create.

Fixes #116997

Release note (bug fix): CREATE EXTERNAL CONNECTION IF NOT EXISTS no longer returns an error if the connection already exists.

### CODE REVIEW

File: pkg/sql/create_external_connection.go [hunk 1]
```diff
@@ -144,6 +144,10 @@ func (p *planner) createExternalConnection(
 	// Create the External Connection and persist it in the
 	// `system.external_connections` table.
 	if err := ex.Create(params.ctx, txn); err != nil {
+		isNotExists := n.ConnectionLabelSpec.IfNotExists
```
Comment (msbutler) [inline pkg/sql/create_external_connection.go:147]: nit: s/is/if/r

also, I think a few words in the commit message could be swapped for clearer reading.

**Review by msbutler — APPROVED** [review]
Thanks for doing this!

**Comment by stevendanna** [comment]
bors r=msbutler
