### PR TITLE
sql: Fix for invalid value for parameter "TimeZone": "GMT-08:00" #41776

### LINKED ISSUE #41776: sql: invalid value for parameter "TimeZone": "GMT-08:00"
The `TimeZone` parameter should support `GMT-08:00` as a value, but it doesn't. This is used in a PGJDBC test. See https://github.com/pgjdbc/pgjdbc/blob/master/pgjdbc/src/test/java/org/postgresql/test/jdbc2/TimezoneTest.java

### PR DESCRIPTION
**Pull request by droidnoob**
Resolves #41776

Previously, the inputs starting with `UTC` and `GMT` would cause error.
Postgres supports inputs like this. So adding support for
these inputs was necessary.
sql: Added a check to convert the strings to offset.
timeutil: added a function to convert input to offset seconds.
Added unit tests. Added a regex to accept the above inputs.
Cleaned the code.

Release note (sql change): `SET TIME ZONE` now accepts inputs
beginning with `GMT` and `UTC`, such as `GMT+5` and
`UTC-3:59`. This was previously unsupported.

@otan

### CODE REVIEW

**Comment by knz** [comment]
@droidnoob thank you for your submission. Note that your commit message was truncated: the `git` command removes every line from a commit message that starts with `#`. I suspect you had an issue number in there. Please reformat the commit message and try again.

Our commit message guidelines are here: https://wiki.crdb.io/wiki/spaces/CRDB/pages/73072807/Git+Commit+Messages

File: pkg/sql/logictest/testdata/logic_test/timestamp [hunk 1]
```diff
@@ -192,3 +192,14 @@ query R
 SELECT extract(timezone FROM '2001-01-01 13:00:00+01:15'::timestamptz)
 ----
 10800
+
+
+# Test timezone() 
+
+statement ok
+SET TIME ZONE 'GMT+1';
```
Comment (otan) [inline pkg/sql/logictest/testdata/logic_test/timestamp]: nit: going to make a minor tweak for you here to remove this semicolon

File: pkg/util/timeutil/time_zone_util.go [hunk 2]
```diff
@@ -12,12 +12,17 @@ package timeutil
...
 import (
 	"fmt"
+	"regexp"
 	"strconv"
 	"strings"
 	"time"
 )
 
 const fixedOffsetPrefix string = "fixed offset:"
+const pattern = `(?i)(GMT|UTC)([+-])(\d{1,3}(:[0-5]\d){0,2})\b$`
```
Comment (otan) [inline pkg/util/timeutil/time_zone_util.go]: nit: making a minor tweak here to have more descriptive var names.
also changed regexp to support `UTC+3:5:6`.

File: pkg/util/timeutil/time_zone_util.go [hunk 3]
```diff
@@ -68,3 +73,44 @@ func ParseFixedOffsetTimeZone(location string) (offset int, origRepr string, suc
 	}
 	return offset, strings.TrimSuffix(strings.TrimPrefix(origRepr, "("), ")"), true
 }
+
+// TimeZoneOffsetStringConversion converts a time string to offset seconds
+// Supported time zone strings :- GMT/UTC±[00:00:00 - 15:59:59], GMT/UTC±[0-16]
```
Comment (otan) [inline pkg/util/timeutil/time_zone_util.go]: nit: making a minor comment update here.

File: pkg/util/timeutil/time_zone_util.go [hunk 4]
```diff
@@ -68,3 +73,44 @@ func ParseFixedOffsetTimeZone(location string) (offset int, origRepr string, suc
...
+// Unsupported time zone strings :- GMT/UTC±16:00 to upper, GMT/UTC±6.5
+// (case insensitive)
+func TimeZoneOffsetStringConversion(s string) (offset int64, ok bool) {
+	if !(re.MatchString(s)) {
+		return 0, false
+	}
+	prefix := string(re.FindStringSubmatch(s)[0][3])
```
Comment (otan) [inline pkg/util/timeutil/time_zone_util.go]: nit: going to re-use the result of `re.FindStringSubmatch` for you here, and also add a test for whitespaces.

**Review by otan — COMMENTED** [review]
i have made some minor nits, which i have commented on below! after that, lgtm!

File: pkg/sql/logictest/testdata/logic_test/timestamp [hunk 5]
```diff
@@ -192,3 +192,14 @@ query R
 SELECT extract(timezone FROM '2001-01-01 13:00:00+01:15'::timestamptz)
 ----
 10800
+
+
+# Test timezone()
```
Comment (otan) [inline pkg/sql/logictest/testdata/logic_test/timestamp]: nit: this line is a little misleading. maybe use `subtest regression_41776` instead? (no comment)

File: pkg/util/timeutil/time_zone_util_test.go [hunk 6]
```diff
@@ -0,0 +1,45 @@
...
+
+import "testing"
+
+func TestTimeZoneOffsetStringConversion(t *testing.T) {
+	testCases := []struct {
+		timezone   string
+		offsetSecs int64
+		ok         bool
+	}{
+		{`GMT+00:00`, 0, true},
```
Comment (otan) [inline pkg/util/timeutil/time_zone_util_test.go]: i added a few more edge cases (and some changes after accepting `5:6:7`:

```
               {`GMT+00:00`, 0, true},
               {`UTC-1:00:00`, -3600, true},
               {`UTC+15:59`, 57540, true},
               {`UTC+5:9`, 5*60*60 + 9*60, true},
               {`UTC-5:9:1`, -(5*60*60 + 9*60 + 1), true},
               {`GMT-15:59:59`, -57599, true},
               {`GMT-06:59`, -25140, true},
               {`GMT+167:59:00`, 604740, true},
               {`GMT-167:59:00`, -604740, true},
               {` GMT +167:59:00  `, 604740, true},
               {`GMT+6:0:59`, 6*60*60 + 59, true},
               {`GMT+6:00:0`, 6 * 60 * 60, true},
               {`GMT+5`, 18000, true},
               {`GMT-16`, -57600, true},

               {`GMT-15:59:5Z`, 0, false},
               {`GMT+6:`, 0, false},
               {`GMT-6:00:`, 0, false},
               {`GMT-168:00:00`, 0, false},
               {`GMT+168:00:00`, 0, false},
               {`GMT-170:00:59`, 0, false},
```

**Review by otan — COMMENTED** [review]
also please update your commit message (different to PR description) to not reference a task number, but instead give specifics, e.g.
```
    Release note (sql change): `SET TIME ZONE` now accepts inputs
    beginning with 'GMT' and 'UTC', such as 'GMT+5' and
    'UTC-3:59'. This was previously unsupported.
```

File: pkg/util/timeutil/time_zone_util.go (hunk 2 above)
Comment (droidnoob) [reply pkg/util/timeutil/time_zone_util.go]: Wouldn't this regex accept an input like `utc+3:67:99`.  Ideally minutes and secs shouldn't be more than 59 right? This particular input won't be out of bounds

Comment (droidnoob) [reply pkg/util/timeutil/time_zone_util.go]: `(?i)(GMT|UTC)([+-])(\d{1,3}(:[0-5]?\d){0,2})\b$`
This regex accepts cases like `UTC+3:5:6`

Comment (otan) [reply pkg/util/timeutil/time_zone_util.go]: ah that's true :) we want to allow single digits though, e.g. `GMT+3:5` works

File: pkg/util/timeutil/time_zone_util.go [hunk 7]
```diff
@@ -68,3 +74,49 @@ func ParseFixedOffsetTimeZone(location string) (offset int, origRepr string, suc
 	}
 	return offset, strings.TrimSuffix(strings.TrimPrefix(origRepr, "("), ")"), true
 }
+
+// TimeZoneOffsetStringConversion converts a time string to offset seconds.
+// Supported time zone strings: GMT/UTC±[00:00:00 - 169:59:00].
+// Seconds/minutes omittable and is case insensitive.
+func TimeZoneOffsetStringConversion(s string) (offset int64, ok bool) {
+	timeZoneString := strings.ReplaceAll(s, " ", "")
+	if !(timezoneOffsetRegex.MatchString(timeZoneString)) {
```
Comment (otan) [inline pkg/util/timeutil/time_zone_util.go]: Do we need this check if we check Len of submatch below?

**Review by otan — COMMENTED** [review]
I'll merge this in the US morning!

File: pkg/util/timeutil/time_zone_util.go (hunk 7 above)
Comment (droidnoob) [reply pkg/util/timeutil/time_zone_util.go]: I guess not. Changing now

**Review by otan — APPROVED** [review]

**Comment by otan** [comment]
bors r+

thanks for contributing!
