### PR TITLE
bulkio: use correct context in processor initialization

### LINKED ISSUE #60940: bulkio: audit context usage when starting processors
After a refactor in https://github.com/cockroachdb/cockroach/pull/59834/files, RowSource's Start interface no longer returns a context since it was almost never used. There were TODOs added for bulk io to check that the correct contexts are being used after this change. This ticket tracks that work.

### LINKED ISSUE #60975: ccl/importccl: TestCSVImportCanBeResumed failed
[(ccl/importccl).TestCSVImportCanBeResumed failed](https://teamcity.cockroachdb.com/viewLog.html?buildId=2707940&tab=buildLog) on [master@2572200f7612c6508a52735a6a18767cfb7cc09d](https://github.com/cockroachdb/cockroach/commits/2572200f7612c6508a52735a6a18767cfb7cc09d):

```
  github.com/cockroachdb/cockroach/pkg/ccl/importccl.(*readImportDataProcessor).Start()
      /go/src/github.com/cockroachdb/cockroach/pkg/ccl/importccl/import_processor.go:105 +0xa4
  github.com/cockroachdb/cockroach/pkg/sql/execinfra.(*ProcessorBase).Run()
      /go/src/github.com/cockroachdb/cockroach/pkg/sql/execinfra/processorsbase.go:764 +0x8e
  github.com/cockroachdb/cockroach/pkg/ccl/importccl.(*readImportDataProcessor).Run()
      <autogenerated>:1 +0x57
  github.com/cockroachdb/cockroach/pkg/sql/flowinfra.(*FlowBase).Run()
      /go/src/github.com/cockroachdb/cockroach/pkg/sql/flowinfra/flow.go:382 +0x2c6
  github.com/cockroachdb/cockroach/pkg/sql/rowflow.(*rowBasedFlow).Run()
      <autogenerated>:1 +0x84
  github.com/cockroachdb/cockroach/pkg/sql.(*DistSQLPlanner).Run()
      /go/src/github.com/cockroachdb/cockroach/pkg/sql/distsql_running.go:367 +0x7a7
  github.com/cockroachdb/cockroach/pkg/sql.DistIngest.func6()
      /go/src/github.com/cockroachdb/cockroach/pkg/sql/distsql_plan_csv.go:332 +0x1b2
  github.com/cockroachdb/cockroach/pkg/util/ctxgroup.Group.GoCtx.func1()
      /go/src/github.com/cockroachdb/cockroach/pkg/util/ctxgroup/ctxgroup.go:166 +0x4e
  golang.org/x/sync/errgroup.(*Group).Go.func1()
      /go/src/github.com/cockroachdb/cockroach/vendor/golang.org/x/sync/errgroup/errgroup.go:57 +0x94

Goroutine 26 (running) created at:
  golang.org/x/sync/errgroup.(*Group).Go()
      /go/src/github.com/cockroachdb/cockroach/vendor/golang.org/x/sync/errgroup/errgroup.go:54 +0x73
  github.com/cockroachdb/cockroach/pkg/util/ctxgroup.Group.GoCtx()
      /go/src/github.com/cockroachdb/cockroach/pkg/util/ctxgroup/ctxgroup.go:165 +0xe4
  github.com/cockroachdb/cockroach/pkg/sql.DistIngest()
      /go/src/github.com/cockroachdb/cockroach/pkg/sql/distsql_plan_csv.go:328 +0x128d
  github.com/cockroachdb/cockroach/pkg/ccl/importccl.(*importResumer).Resume()
      /go/src/github.com/cockroachdb/cockroach/pkg/ccl/importccl/import_stmt.go:1632 +0xe38
  github.com/cockroachdb/cockroach/pkg/ccl/importccl.(*cancellableImportResumer).Resume()
      /go/src/github.com/cockroachdb/cockroach/pkg/ccl/importccl/import_processor_test.go:554 +0x1cc
  github.com/cockroachdb/cockroach/pkg/jobs.(*Registry).stepThroughStateMachine.func1()
      /go/src/github.com/cockroachdb/cockroach/pkg/jobs/registry.go:1170 +0x141
  github.com/cockroachdb/cockroach/pkg/jobs.(*Registry).stepThroughStateMachine()
      /go/src/github.com/cockroachdb/cockroach/pkg/jobs/registry.go:1171 +0xa85
  github.com/cockroachdb/cockroach/pkg/jobs.(*Registry).runJob()
      /go/src/github.com/cockroachdb/cockroach/pkg/jobs/adopt.go:250 +0x43e
  github.com/cockroachdb/cockroach/pkg/jobs.(*StartableJob).Start.func3()
      /go/src/github.com/cockroachdb/cockroach/pkg/jobs/jobs.go:867 +0x25c
  github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunAsyncTask.func1()
      /go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:351 +0x149
==================
E210223 06:16:33.560091 1505 jobs/adopt.go:255  [n1] 1  job 635668376058003457: adoption completed with error job 635668376058003457: could not mark as reverting: context canceled: job with status pause-requested cannot be reverted
    import_processor_test.go:733: Resume pos: 30
E210223 06:16:34.408378 635 jobs/registry.go:672  [-] 2  error claiming jobs: could not query jobs table: claim-jobs: context canceled
E210223 06:16:34.408913 633 jobs/registry.go:662  [-] 3  failed to serve pause and cancel requests: could not query jobs table: cancel/pause-requested: context canceled
E210223 06:16:34.410822 635 jobs/registry.go:682  [-] 4  error processing claimed jobs: could not query for claimed jobs: select-running/get-claimed-jobs: context canceled
    import_processor_test.go:747: -- test log scope end --
test logs left over in: /go/src/github.com/cockroachdb/cockroach/artifacts/logTestCSVImportCanBeResumed385659822
    testing.go:1038: race detected during execution of test
--- FAIL: TestCSVImportCanBeResumed (1.85s)

```

<details><summary>More</summary><p>
Parameters:

- TAGS=
- GOFLAGS=-race -parallel=4

```
make stressrace TESTS=TestCSVImportCanBeResumed PKG=./pkg/ccl/importccl TESTTIMEOUT=5m STRESSFLAGS='-timeout 5m' 2>&1
```

[See this test on roachdash](https://roachdash.crdb.dev/?filter=status%3Aopen+t%3A.%2ATestCSVImportCanBeResumed.%2A&sort=title&restgroup=false&display=lastcommented+project)
<sub>powered by [pkg/cmd/internal/issues](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)</sub></p></details>

### LINKED ISSUE #60976: ccl/importccl: TestImportComputed failed
[(ccl/importccl).TestImportComputed failed](https://teamcity.cockroachdb.com/viewLog.html?buildId=2707940&tab=buildLog) on [master@2572200f7612c6508a52735a6a18767cfb7cc09d](https://github.com/cockroachdb/cockroach/commits/2572200f7612c6508a52735a6a18767cfb7cc09d):

```
      /go/src/github.com/cockroachdb/cockroach/pkg/util/ctxgroup/ctxgroup.go:165 +0xe4
  github.com/cockroachdb/cockroach/pkg/ccl/importccl.runImport()
      /go/src/github.com/cockroachdb/cockroach/pkg/ccl/importccl/read_import_base.go:90 +0x659
  github.com/cockroachdb/cockroach/pkg/ccl/importccl.(*readImportDataProcessor).Start.func1()
      /go/src/github.com/cockroachdb/cockroach/pkg/ccl/importccl/import_processor.go:107 +0x199

Goroutine 469 (running) created at:
  github.com/cockroachdb/cockroach/pkg/sql/flowinfra.(*FlowBase).startInternal()
      /go/src/github.com/cockroachdb/cockroach/pkg/sql/flowinfra/flow.go:326 +0x3f4
  github.com/cockroachdb/cockroach/pkg/sql/flowinfra.(*FlowBase).Start()
      /go/src/github.com/cockroachdb/cockroach/pkg/sql/flowinfra/flow.go:347 +0x97
  github.com/cockroachdb/cockroach/pkg/sql/rowflow.(*rowBasedFlow).Start()
      <autogenerated>:1 +0x84
  github.com/cockroachdb/cockroach/pkg/sql/flowinfra.(*FlowScheduler).runFlowNow()
      /go/src/github.com/cockroachdb/cockroach/pkg/sql/flowinfra/flow_scheduler.go:109 +0x27a
  github.com/cockroachdb/cockroach/pkg/sql/flowinfra.(*FlowScheduler).ScheduleFlow.func1()
      /go/src/github.com/cockroachdb/cockroach/pkg/sql/flowinfra/flow_scheduler.go:130 +0x81b
  github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunTaskWithErr()
      /go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:330 +0x129
  github.com/cockroachdb/cockroach/pkg/sql/flowinfra.(*FlowScheduler).ScheduleFlow()
      /go/src/github.com/cockroachdb/cockroach/pkg/sql/flowinfra/flow_scheduler.go:127 +0xcb
  github.com/cockroachdb/cockroach/pkg/sql/distsql.(*ServerImpl).SetupFlow()
      /go/src/github.com/cockroachdb/cockroach/pkg/sql/distsql/server.go:548 +0x48a
  github.com/cockroachdb/cockroach/pkg/sql/execinfrapb._DistSQL_SetupFlow_Handler.func1()
      /go/src/github.com/cockroachdb/cockroach/pkg/sql/execinfrapb/api.pb.go:510 +0xa1
  github.com/cockroachdb/cockroach/pkg/util/tracing.ServerInterceptor.func1()
      /go/src/github.com/cockroachdb/cockroach/pkg/util/tracing/grpc_interceptor.go:137 +0x3b7
  google.golang.org/grpc.getChainUnaryHandler.func1()
      /go/src/github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/server.go:921 +0x14f
  github.com/cockroachdb/cockroach/pkg/rpc.NewServer.func1()
      /go/src/github.com/cockroachdb/cockroach/pkg/rpc/context.go:176 +0x13a
  google.golang.org/grpc.getChainUnaryHandler.func1()
      /go/src/github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/server.go:921 +0x14f
  github.com/cockroachdb/cockroach/pkg/rpc.kvAuth.unaryInterceptor()
      /go/src/github.com/cockroachdb/cockroach/pkg/rpc/auth.go:60 +0xc8
  github.com/cockroachdb/cockroach/pkg/rpc.kvAuth.unaryInterceptor-fm()
      /go/src/github.com/cockroachdb/cockroach/pkg/rpc/auth.go:47 +0x84
  google.golang.org/grpc.chainUnaryServerInterceptors.func1()
      /go/src/github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/server.go:907 +0x112
  github.com/cockroachdb/cockroach/pkg/sql/execinfrapb._DistSQL_SetupFlow_Handler()
      /go/src/github.com/cockroachdb/cockroach/pkg/sql/execinfrapb/api.pb.go:512 +0x1dd
  google.golang.org/grpc.(*Server).processUnaryRPC()
      /go/src/github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/server.go:1082 +0xa05
  google.golang.org/grpc.(*Server).handleStream()
      /go/src/github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/server.go:1405 +0x138b
  google.golang.org/grpc.(*Server).serveStreams.func1.1()
      /go/src/github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/server.go:746 +0xdc
==================
    testing.go:1038: race detected during execution of test
    --- FAIL: TestImportComputed/addition (1.51s)

```

<details><summary>More</summary><p>
Parameters:

- TAGS=
- GOFLAGS=-race -parallel=4

```
make stressrace TESTS=TestImportComputed PKG=./pkg/ccl/importccl TESTTIMEOUT=5m STRESSFLAGS='-timeout 5m' 2>&1
```

[See this test on roachdash](https://roachdash.crdb.dev/?filter=status%3Aopen+t%3A.%2ATestImportComputed.%2A&sort=title&restgroup=false&display=lastcommented+project)
<sub>powered by [pkg/cmd/internal/issues](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)</sub></p></details>

### LINKED ISSUE #60977: ccl/importccl: TestImportDelimited failed
[(ccl/importccl).TestImportDelimited failed](https://teamcity.cockroachdb.com/viewLog.html?buildId=2707940&tab=buildLog) on [master@2572200f7612c6508a52735a6a18767cfb7cc09d](https://github.com/cockroachdb/cockroach/commits/2572200f7612c6508a52735a6a18767cfb7cc09d):

```

Goroutine 789 (running) created at:
  github.com/cockroachdb/cockroach/pkg/sql/flowinfra.(*FlowBase).startInternal()
      /go/src/github.com/cockroachdb/cockroach/pkg/sql/flowinfra/flow.go:326 +0x3f4
  github.com/cockroachdb/cockroach/pkg/sql/flowinfra.(*FlowBase).Start()
      /go/src/github.com/cockroachdb/cockroach/pkg/sql/flowinfra/flow.go:347 +0x97
  github.com/cockroachdb/cockroach/pkg/sql/rowflow.(*rowBasedFlow).Start()
      <autogenerated>:1 +0x84
  github.com/cockroachdb/cockroach/pkg/sql/flowinfra.(*FlowScheduler).runFlowNow()
      /go/src/github.com/cockroachdb/cockroach/pkg/sql/flowinfra/flow_scheduler.go:109 +0x27a
  github.com/cockroachdb/cockroach/pkg/sql/flowinfra.(*FlowScheduler).ScheduleFlow.func1()
      /go/src/github.com/cockroachdb/cockroach/pkg/sql/flowinfra/flow_scheduler.go:130 +0x81b
  github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunTaskWithErr()
      /go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:330 +0x129
  github.com/cockroachdb/cockroach/pkg/sql/flowinfra.(*FlowScheduler).ScheduleFlow()
      /go/src/github.com/cockroachdb/cockroach/pkg/sql/flowinfra/flow_scheduler.go:127 +0xcb
  github.com/cockroachdb/cockroach/pkg/sql/distsql.(*ServerImpl).SetupFlow()
      /go/src/github.com/cockroachdb/cockroach/pkg/sql/distsql/server.go:548 +0x48a
  github.com/cockroachdb/cockroach/pkg/sql/execinfrapb._DistSQL_SetupFlow_Handler.func1()
      /go/src/github.com/cockroachdb/cockroach/pkg/sql/execinfrapb/api.pb.go:510 +0xa1
  github.com/cockroachdb/cockroach/pkg/util/tracing.ServerInterceptor.func1()
      /go/src/github.com/cockroachdb/cockroach/pkg/util/tracing/grpc_interceptor.go:137 +0x3b7
  google.golang.org/grpc.getChainUnaryHandler.func1()
      /go/src/github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/server.go:921 +0x14f
  github.com/cockroachdb/cockroach/pkg/rpc.NewServer.func1()
      /go/src/github.com/cockroachdb/cockroach/pkg/rpc/context.go:176 +0x13a
  google.golang.org/grpc.getChainUnaryHandler.func1()
      /go/src/github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/server.go:921 +0x14f
  github.com/cockroachdb/cockroach/pkg/rpc.kvAuth.unaryInterceptor()
      /go/src/github.com/cockroachdb/cockroach/pkg/rpc/auth.go:60 +0xc8
  github.com/cockroachdb/cockroach/pkg/rpc.kvAuth.unaryInterceptor-fm()
      /go/src/github.com/cockroachdb/cockroach/pkg/rpc/auth.go:47 +0x84
  google.golang.org/grpc.chainUnaryServerInterceptors.func1()
      /go/src/github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/server.go:907 +0x112
  github.com/cockroachdb/cockroach/pkg/sql/execinfrapb._DistSQL_SetupFlow_Handler()
      /go/src/github.com/cockroachdb/cockroach/pkg/sql/execinfrapb/api.pb.go:512 +0x1dd
  google.golang.org/grpc.(*Server).processUnaryRPC()
      /go/src/github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/server.go:1082 +0xa05
  google.golang.org/grpc.(*Server).handleStream()
      /go/src/github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/server.go:1405 +0x138b
  google.golang.org/grpc.(*Server).serveStreams.func1.1()
      /go/src/github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/server.go:746 +0xdc
==================
    testing.go:1038: race detected during execution of test
        --- FAIL: TestImportDelimited/escape-and-enclose/import-into-target-cols-reordered (1.48s)
=== RUN   TestImportDelimited/escape-and-enclose
E210223 06:18:24.304365 76788 jobs/adopt.go:117  [-] 1  could not run claimed job 635668737530626049: job 635668737530626049: status changed to succeeded which is not resumable`
=== CONT  TestImportDelimited/escape-and-enclose
    testing.go:1038: race detected during execution of test
    --- FAIL: TestImportDelimited/escape-and-enclose (3.81s)

```

<details><summary>More</summary><p>
Parameters:

- TAGS=
- GOFLAGS=-race -parallel=4

```
make stressrace TESTS=TestImportDelimited PKG=./pkg/ccl/importccl TESTTIMEOUT=5m STRESSFLAGS='-timeout 5m' 2>&1
```

[See this test on roachdash](https://roachdash.crdb.dev/?filter=status%3Aopen+t%3A.%2ATestImportDelimited.%2A&sort=title&restgroup=false&display=lastcommented+project)
<sub>powered by [pkg/cmd/internal/issues](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)</sub></p></details>

### LINKED ISSUE #60978: ccl/importccl: TestImportIgnoresProcessedFiles failed
[(ccl/importccl).TestImportIgnoresProcessedFiles failed](https://teamcity.cockroachdb.com/viewLog.html?buildId=2707940&tab=buildLog) on [master@2572200f7612c6508a52735a6a18767cfb7cc09d](https://github.com/cockroachdb/cockroach/commits/2572200f7612c6508a52735a6a18767cfb7cc09d):

```
=== RUN   TestImportIgnoresProcessedFiles
    test_log_scope.go:73: test logs captured to: /go/src/github.com/cockroachdb/cockroach/artifacts/logTestImportIgnoresProcessedFiles812962161
    test_log_scope.go:74: use -show-logs to present logs inline
=== CONT  TestImportIgnoresProcessedFiles
    import_processor_test.go:315: -- test log scope end --
    testing.go:1038: race detected during execution of test
--- FAIL: TestImportIgnoresProcessedFiles (0.09s)
=== RUN   TestImportIgnoresProcessedFiles/processes-files-once-csv-two-invalid
==================
WARNING: DATA RACE
Read at 0x00c0000d5650 by goroutine 63:
  github.com/cockroachdb/cockroach/pkg/ccl/importccl.(*readImportDataProcessor).Start.func1()
      /go/src/github.com/cockroachdb/cockroach/pkg/ccl/importccl/import_processor.go:107 +0xbd

Previous write at 0x00c0000d5650 by goroutine 64:
  github.com/cockroachdb/cockroach/pkg/ccl/importccl.(*readImportDataProcessor).Start()
      /go/src/github.com/cockroachdb/cockroach/pkg/ccl/importccl/import_processor.go:110 +0x114
  github.com/cockroachdb/cockroach/pkg/sql/execinfra.(*ProcessorBase).Run()
      /go/src/github.com/cockroachdb/cockroach/pkg/sql/execinfra/processorsbase.go:764 +0x8e
  github.com/cockroachdb/cockroach/pkg/ccl/importccl.(*readImportDataProcessor).Run()
      <autogenerated>:1 +0x57
  github.com/cockroachdb/cockroach/pkg/ccl/importccl.TestImportIgnoresProcessedFiles.func3()
      /go/src/github.com/cockroachdb/cockroach/pkg/ccl/importccl/import_processor_test.go:312 +0x559
  testing.tRunner()
      /usr/local/go/src/testing/testing.go:1123 +0x202

Goroutine 63 (running) created at:
  github.com/cockroachdb/cockroach/pkg/ccl/importccl.(*readImportDataProcessor).Start()
      /go/src/github.com/cockroachdb/cockroach/pkg/ccl/importccl/import_processor.go:105 +0xa4
  github.com/cockroachdb/cockroach/pkg/sql/execinfra.(*ProcessorBase).Run()
      /go/src/github.com/cockroachdb/cockroach/pkg/sql/execinfra/processorsbase.go:764 +0x8e
  github.com/cockroachdb/cockroach/pkg/ccl/importccl.(*readImportDataProcessor).Run()
      <autogenerated>:1 +0x57
  github.com/cockroachdb/cockroach/pkg/ccl/importccl.TestImportIgnoresProcessedFiles.func3()
      /go/src/github.com/cockroachdb/cockroach/pkg/ccl/importccl/import_processor_test.go:312 +0x559
  testing.tRunner()
      /usr/local/go/src/testing/testing.go:1123 +0x202

Goroutine 64 (running) created at:
  testing.(*T).Run()
      /usr/local/go/src/testing/testing.go:1168 +0x5bb
  github.com/cockroachdb/cockroach/pkg/ccl/importccl.TestImportIgnoresProcessedFiles()
      /go/src/github.com/cockroachdb/cockroach/pkg/ccl/importccl/import_processor_test.go:302 +0x174a
  testing.tRunner()
      /usr/local/go/src/testing/testing.go:1123 +0x202
==================
    import_processor_test.go:186: receiver got an error: <nil>
    testing.go:1038: race detected during execution of test
    --- FAIL: TestImportIgnoresProcessedFiles/processes-files-once-csv-two-invalid (0.01s)

```

<details><summary>More</summary><p>
Parameters:

- TAGS=
- GOFLAGS=-race -parallel=4

```
make stressrace TESTS=TestImportIgnoresProcessedFiles PKG=./pkg/ccl/importccl TESTTIMEOUT=5m STRESSFLAGS='-timeout 5m' 2>&1
```

[See this test on roachdash](https://roachdash.crdb.dev/?filter=status%3Aopen+t%3A.%2ATestImportIgnoresProcessedFiles.%2A&sort=title&restgroup=false&display=lastcommented+project)
<sub>powered by [pkg/cmd/internal/issues](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)</sub></p></details>

### LINKED ISSUE #60979: ccl/importccl: TestImportObjectLevelRBAC failed
[(ccl/importccl).TestImportObjectLevelRBAC failed](https://teamcity.cockroachdb.com/viewLog.html?buildId=2707940&tab=buildLog) on [master@2572200f7612c6508a52735a6a18767cfb7cc09d](https://github.com/cockroachdb/cockroach/commits/2572200f7612c6508a52735a6a18767cfb7cc09d):

```
      /go/src/github.com/cockroachdb/cockroach/pkg/util/ctxgroup/ctxgroup.go:165 +0xe4
  github.com/cockroachdb/cockroach/pkg/ccl/importccl.runImport()
      /go/src/github.com/cockroachdb/cockroach/pkg/ccl/importccl/read_import_base.go:114 +0x848
  github.com/cockroachdb/cockroach/pkg/ccl/importccl.(*readImportDataProcessor).Start.func1()
      /go/src/github.com/cockroachdb/cockroach/pkg/ccl/importccl/import_processor.go:107 +0x199

Goroutine 834 (running) created at:
  github.com/cockroachdb/cockroach/pkg/sql/flowinfra.(*FlowBase).startInternal()
      /go/src/github.com/cockroachdb/cockroach/pkg/sql/flowinfra/flow.go:326 +0x3f4
  github.com/cockroachdb/cockroach/pkg/sql/flowinfra.(*FlowBase).Start()
      /go/src/github.com/cockroachdb/cockroach/pkg/sql/flowinfra/flow.go:347 +0x97
  github.com/cockroachdb/cockroach/pkg/sql/rowflow.(*rowBasedFlow).Start()
      <autogenerated>:1 +0x84
  github.com/cockroachdb/cockroach/pkg/sql/flowinfra.(*FlowScheduler).runFlowNow()
      /go/src/github.com/cockroachdb/cockroach/pkg/sql/flowinfra/flow_scheduler.go:109 +0x27a
  github.com/cockroachdb/cockroach/pkg/sql/flowinfra.(*FlowScheduler).ScheduleFlow.func1()
      /go/src/github.com/cockroachdb/cockroach/pkg/sql/flowinfra/flow_scheduler.go:130 +0x81b
  github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunTaskWithErr()
      /go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:330 +0x129
  github.com/cockroachdb/cockroach/pkg/sql/flowinfra.(*FlowScheduler).ScheduleFlow()
      /go/src/github.com/cockroachdb/cockroach/pkg/sql/flowinfra/flow_scheduler.go:127 +0xcb
  github.com/cockroachdb/cockroach/pkg/sql/distsql.(*ServerImpl).SetupFlow()
      /go/src/github.com/cockroachdb/cockroach/pkg/sql/distsql/server.go:548 +0x48a
  github.com/cockroachdb/cockroach/pkg/sql/execinfrapb._DistSQL_SetupFlow_Handler.func1()
      /go/src/github.com/cockroachdb/cockroach/pkg/sql/execinfrapb/api.pb.go:510 +0xa1
  github.com/cockroachdb/cockroach/pkg/util/tracing.ServerInterceptor.func1()
      /go/src/github.com/cockroachdb/cockroach/pkg/util/tracing/grpc_interceptor.go:137 +0x3b7
  google.golang.org/grpc.getChainUnaryHandler.func1()
      /go/src/github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/server.go:921 +0x14f
  github.com/cockroachdb/cockroach/pkg/rpc.NewServer.func1()
      /go/src/github.com/cockroachdb/cockroach/pkg/rpc/context.go:176 +0x13a
  google.golang.org/grpc.getChainUnaryHandler.func1()
      /go/src/github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/server.go:921 +0x14f
  github.com/cockroachdb/cockroach/pkg/rpc.kvAuth.unaryInterceptor()
      /go/src/github.com/cockroachdb/cockroach/pkg/rpc/auth.go:60 +0xc8
  github.com/cockroachdb/cockroach/pkg/rpc.kvAuth.unaryInterceptor-fm()
      /go/src/github.com/cockroachdb/cockroach/pkg/rpc/auth.go:47 +0x84
  google.golang.org/grpc.chainUnaryServerInterceptors.func1()
      /go/src/github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/server.go:907 +0x112
  github.com/cockroachdb/cockroach/pkg/sql/execinfrapb._DistSQL_SetupFlow_Handler()
      /go/src/github.com/cockroachdb/cockroach/pkg/sql/execinfrapb/api.pb.go:512 +0x1dd
  google.golang.org/grpc.(*Server).processUnaryRPC()
      /go/src/github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/server.go:1082 +0xa05
  google.golang.org/grpc.(*Server).handleStream()
      /go/src/github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/server.go:1405 +0x138b
  google.golang.org/grpc.(*Server).serveStreams.func1.1()
      /go/src/github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/server.go:746 +0xdc
==================
    testing.go:1038: race detected during execution of test
    --- FAIL: TestImportObjectLevelRBAC/import-RBAC (2.34s)

```

<details><summary>More</summary><p>
Parameters:

- TAGS=
- GOFLAGS=-race -parallel=4

```
make stressrace TESTS=TestImportObjectLevelRBAC PKG=./pkg/ccl/importccl TESTTIMEOUT=5m STRESSFLAGS='-timeout 5m' 2>&1
```

[See this test on roachdash](https://roachdash.crdb.dev/?filter=status%3Aopen+t%3A.%2ATestImportObjectLevelRBAC.%2A&sort=title&restgroup=false&display=lastcommented+project)
<sub>powered by [pkg/cmd/internal/issues](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)</sub></p></details>

### LINKED ISSUE #60980: ccl/importccl: TestImportRowLimit failed
[(ccl/importccl).TestImportRowLimit failed](https://teamcity.cockroachdb.com/viewLog.html?buildId=2707940&tab=buildLog) on [master@2572200f7612c6508a52735a6a18767cfb7cc09d](https://github.com/cockroachdb/cockroach/commits/2572200f7612c6508a52735a6a18767cfb7cc09d):

```
      /go/src/github.com/cockroachdb/cockroach/pkg/ccl/importccl/import_processor.go:110 +0xf2
  github.com/cockroachdb/cockroach/pkg/sql/execinfra.(*ProcessorBase).Run()
      /go/src/github.com/cockroachdb/cockroach/pkg/sql/execinfra/processorsbase.go:764 +0x8e
  github.com/cockroachdb/cockroach/pkg/ccl/importccl.(*readImportDataProcessor).Run()
      <autogenerated>:1 +0x57
  github.com/cockroachdb/cockroach/pkg/sql/flowinfra.(*FlowBase).Run()
      /go/src/github.com/cockroachdb/cockroach/pkg/sql/flowinfra/flow.go:382 +0x2c6
  github.com/cockroachdb/cockroach/pkg/sql/rowflow.(*rowBasedFlow).Run()
      <autogenerated>:1 +0x84
  github.com/cockroachdb/cockroach/pkg/sql.(*DistSQLPlanner).Run()
      /go/src/github.com/cockroachdb/cockroach/pkg/sql/distsql_running.go:367 +0x7a7
  github.com/cockroachdb/cockroach/pkg/sql.DistIngest.func6()
      /go/src/github.com/cockroachdb/cockroach/pkg/sql/distsql_plan_csv.go:332 +0x1b2
  github.com/cockroachdb/cockroach/pkg/util/ctxgroup.Group.GoCtx.func1()
      /go/src/github.com/cockroachdb/cockroach/pkg/util/ctxgroup/ctxgroup.go:166 +0x4e
  golang.org/x/sync/errgroup.(*Group).Go.func1()
      /go/src/github.com/cockroachdb/cockroach/vendor/golang.org/x/sync/errgroup/errgroup.go:57 +0x94

Goroutine 272 (running) created at:
  golang.org/x/sync/errgroup.(*Group).Go()
      /go/src/github.com/cockroachdb/cockroach/vendor/golang.org/x/sync/errgroup/errgroup.go:54 +0x73
  github.com/cockroachdb/cockroach/pkg/util/ctxgroup.Group.GoCtx()
      /go/src/github.com/cockroachdb/cockroach/pkg/util/ctxgroup/ctxgroup.go:165 +0xe4
  github.com/cockroachdb/cockroach/pkg/ccl/importccl.runImport()
      /go/src/github.com/cockroachdb/cockroach/pkg/ccl/importccl/read_import_base.go:114 +0x848
  github.com/cockroachdb/cockroach/pkg/ccl/importccl.(*readImportDataProcessor).Start.func1()
      /go/src/github.com/cockroachdb/cockroach/pkg/ccl/importccl/import_processor.go:107 +0x199

Goroutine 108 (running) created at:
  golang.org/x/sync/errgroup.(*Group).Go()
      /go/src/github.com/cockroachdb/cockroach/vendor/golang.org/x/sync/errgroup/errgroup.go:54 +0x73
  github.com/cockroachdb/cockroach/pkg/util/ctxgroup.Group.GoCtx()
      /go/src/github.com/cockroachdb/cockroach/pkg/util/ctxgroup/ctxgroup.go:165 +0xe4
  github.com/cockroachdb/cockroach/pkg/sql.DistIngest()
      /go/src/github.com/cockroachdb/cockroach/pkg/sql/distsql_plan_csv.go:328 +0x128d
  github.com/cockroachdb/cockroach/pkg/ccl/importccl.(*importResumer).Resume()
      /go/src/github.com/cockroachdb/cockroach/pkg/ccl/importccl/import_stmt.go:1632 +0xe38
  github.com/cockroachdb/cockroach/pkg/jobs.(*Registry).stepThroughStateMachine.func1()
      /go/src/github.com/cockroachdb/cockroach/pkg/jobs/registry.go:1170 +0x141
  github.com/cockroachdb/cockroach/pkg/jobs.(*Registry).stepThroughStateMachine()
      /go/src/github.com/cockroachdb/cockroach/pkg/jobs/registry.go:1171 +0xa85
  github.com/cockroachdb/cockroach/pkg/jobs.(*Registry).runJob()
      /go/src/github.com/cockroachdb/cockroach/pkg/jobs/adopt.go:250 +0x43e
  github.com/cockroachdb/cockroach/pkg/jobs.(*StartableJob).Start.func3()
      /go/src/github.com/cockroachdb/cockroach/pkg/jobs/jobs.go:867 +0x25c
  github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunAsyncTask.func1()
      /go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:351 +0x149
==================
    testing.go:1038: race detected during execution of test
    --- FAIL: TestImportRowLimit/pgdump_single_table_with_insert (1.03s)

```

<details><summary>More</summary><p>
Parameters:

- TAGS=
- GOFLAGS=-race -parallel=4

```
make stressrace TESTS=TestImportRowLimit PKG=./pkg/ccl/importccl TESTTIMEOUT=5m STRESSFLAGS='-timeout 5m' 2>&1
```

[See this test on roachdash](https://roachdash.crdb.dev/?filter=status%3Aopen+t%3A.%2ATestImportRowLimit.%2A&sort=title&restgroup=false&display=lastcommented+project)
<sub>powered by [pkg/cmd/internal/issues](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)</sub></p></details>

### LINKED ISSUE #60981: ccl/importccl: TestImportUserDefinedTypes failed
[(ccl/importccl).TestImportUserDefinedTypes failed](https://teamcity.cockroachdb.com/viewLog.html?buildId=2707940&tab=buildLog) on [master@2572200f7612c6508a52735a6a18767cfb7cc09d](https://github.com/cockroachdb/cockroach/commits/2572200f7612c6508a52735a6a18767cfb7cc09d):

```
      /go/src/github.com/cockroachdb/cockroach/pkg/sql/execinfra/processorsbase.go:764 +0x8e
  github.com/cockroachdb/cockroach/pkg/ccl/importccl.(*readImportDataProcessor).Run()
      <autogenerated>:1 +0x57
  github.com/cockroachdb/cockroach/pkg/sql/flowinfra.(*FlowBase).Run()
      /go/src/github.com/cockroachdb/cockroach/pkg/sql/flowinfra/flow.go:382 +0x2c6
  github.com/cockroachdb/cockroach/pkg/sql/rowflow.(*rowBasedFlow).Run()
      <autogenerated>:1 +0x84
  github.com/cockroachdb/cockroach/pkg/sql.(*DistSQLPlanner).Run()
      /go/src/github.com/cockroachdb/cockroach/pkg/sql/distsql_running.go:367 +0x7a7
  github.com/cockroachdb/cockroach/pkg/sql.DistIngest.func6()
      /go/src/github.com/cockroachdb/cockroach/pkg/sql/distsql_plan_csv.go:332 +0x1b2
  github.com/cockroachdb/cockroach/pkg/util/ctxgroup.Group.GoCtx.func1()
      /go/src/github.com/cockroachdb/cockroach/pkg/util/ctxgroup/ctxgroup.go:166 +0x4e
  golang.org/x/sync/errgroup.(*Group).Go.func1()
      /go/src/github.com/cockroachdb/cockroach/vendor/golang.org/x/sync/errgroup/errgroup.go:57 +0x94

Goroutine 252 (running) created at:
  golang.org/x/sync/errgroup.(*Group).Go()
      /go/src/github.com/cockroachdb/cockroach/vendor/golang.org/x/sync/errgroup/errgroup.go:54 +0x73
  github.com/cockroachdb/cockroach/pkg/util/ctxgroup.Group.GoCtx()
      /go/src/github.com/cockroachdb/cockroach/pkg/util/ctxgroup/ctxgroup.go:165 +0xe4
  github.com/cockroachdb/cockroach/pkg/ccl/importccl.runImport()
      /go/src/github.com/cockroachdb/cockroach/pkg/ccl/importccl/read_import_base.go:90 +0x659
  github.com/cockroachdb/cockroach/pkg/ccl/importccl.(*readImportDataProcessor).Start.func1()
      /go/src/github.com/cockroachdb/cockroach/pkg/ccl/importccl/import_processor.go:107 +0x199

Goroutine 83 (running) created at:
  golang.org/x/sync/errgroup.(*Group).Go()
      /go/src/github.com/cockroachdb/cockroach/vendor/golang.org/x/sync/errgroup/errgroup.go:54 +0x73
  github.com/cockroachdb/cockroach/pkg/util/ctxgroup.Group.GoCtx()
      /go/src/github.com/cockroachdb/cockroach/pkg/util/ctxgroup/ctxgroup.go:165 +0xe4
  github.com/cockroachdb/cockroach/pkg/sql.DistIngest()
      /go/src/github.com/cockroachdb/cockroach/pkg/sql/distsql_plan_csv.go:328 +0x128d
  github.com/cockroachdb/cockroach/pkg/ccl/importccl.(*importResumer).Resume()
      /go/src/github.com/cockroachdb/cockroach/pkg/ccl/importccl/import_stmt.go:1632 +0xe38
  github.com/cockroachdb/cockroach/pkg/jobs.(*Registry).stepThroughStateMachine.func1()
      /go/src/github.com/cockroachdb/cockroach/pkg/jobs/registry.go:1170 +0x141
  github.com/cockroachdb/cockroach/pkg/jobs.(*Registry).stepThroughStateMachine()
      /go/src/github.com/cockroachdb/cockroach/pkg/jobs/registry.go:1171 +0xa85
  github.com/cockroachdb/cockroach/pkg/jobs.(*Registry).runJob()
      /go/src/github.com/cockroachdb/cockroach/pkg/jobs/adopt.go:250 +0x43e
  github.com/cockroachdb/cockroach/pkg/jobs.(*StartableJob).Start.func3()
      /go/src/github.com/cockroachdb/cockroach/pkg/jobs/jobs.go:867 +0x25c
  github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunAsyncTask.func1()
      /go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:351 +0x149
==================
    import_stmt_test.go:1270: -- test log scope end --
test logs left over in: /go/src/github.com/cockroachdb/cockroach/artifacts/logTestImportUserDefinedTypes189301203
    testing.go:1038: race detected during execution of test
--- FAIL: TestImportUserDefinedTypes (3.72s)

```

<details><summary>More</summary><p>
Parameters:

- TAGS=
- GOFLAGS=-race -parallel=4

```
make stressrace TESTS=TestImportUserDefinedTypes PKG=./pkg/ccl/importccl TESTTIMEOUT=5m STRESSFLAGS='-timeout 5m' 2>&1
```

[See this test on roachdash](https://roachdash.crdb.dev/?filter=status%3Aopen+t%3A.%2ATestImportUserDefinedTypes.%2A&sort=title&restgroup=false&display=lastcommented+project)
<sub>powered by [pkg/cmd/internal/issues](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)</sub></p></details>

### LINKED ISSUE #60983: ccl/workloadccl: TestImportFixture failed
[(ccl/workloadccl).TestImportFixture failed](https://teamcity.cockroachdb.com/viewLog.html?buildId=2707982&tab=buildLog) on [master@2572200f7612c6508a52735a6a18767cfb7cc09d](https://github.com/cockroachdb/cockroach/commits/2572200f7612c6508a52735a6a18767cfb7cc09d):

```
  golang.org/x/sync/errgroup.(*Group).Go()
      /go/src/github.com/cockroachdb/cockroach/vendor/golang.org/x/sync/errgroup/errgroup.go:54 +0x73
  github.com/cockroachdb/cockroach/pkg/util/ctxgroup.Group.GoCtx()
      /go/src/github.com/cockroachdb/cockroach/pkg/util/ctxgroup/ctxgroup.go:165 +0xe4
  github.com/cockroachdb/cockroach/pkg/sql.DistIngest()
      /go/src/github.com/cockroachdb/cockroach/pkg/sql/distsql_plan_csv.go:328 +0x128d
  github.com/cockroachdb/cockroach/pkg/ccl/importccl.(*importResumer).Resume()
      /go/src/github.com/cockroachdb/cockroach/pkg/ccl/importccl/import_stmt.go:1632 +0xe38
  github.com/cockroachdb/cockroach/pkg/jobs.(*Registry).stepThroughStateMachine.func1()
      /go/src/github.com/cockroachdb/cockroach/pkg/jobs/registry.go:1170 +0x141
  github.com/cockroachdb/cockroach/pkg/jobs.(*Registry).stepThroughStateMachine()
      /go/src/github.com/cockroachdb/cockroach/pkg/jobs/registry.go:1171 +0xa85
  github.com/cockroachdb/cockroach/pkg/jobs.(*Registry).runJob()
      /go/src/github.com/cockroachdb/cockroach/pkg/jobs/adopt.go:250 +0x43e
  github.com/cockroachdb/cockroach/pkg/jobs.(*StartableJob).Start.func3()
      /go/src/github.com/cockroachdb/cockroach/pkg/jobs/jobs.go:867 +0x25c
  github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunAsyncTask.func1()
      /go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:351 +0x149
==================
I210223 06:24:55.059955 1318 jobs/registry.go:1152  [n1] 38  IMPORT job 635670019457417217: stepping through state succeeded with error: <nil>
I210223 06:24:55.086698 1135 ccl/workloadccl/fixture.go:472  [-] 39  imported 190 B in fx table (10 rows, 0 index entries, took 309.542677ms, 0.00 MiB/s)
I210223 06:24:55.148887 1623 jobs/registry.go:1152  [n1] 40  AUTO CREATE STATS job 635670020478795777: stepping through state running with error: <nil>
W210223 06:24:55.254580 1464 kv/kvserver/intentresolver/intent_resolver.go:758  [-] 41  failed to gc transaction record: could not GC completed transaction anchored at /Table/15/1/635670019457417217: node unavailable; try another peer
I210223 06:24:55.254699 58 kv/kvclient/kvcoord/transport_race.go:106  [-] 42  transport race promotion: ran 26 iterations on up to 445 requests
W210223 06:24:55.257101 282 sql/sqlliveness/slinstance/slinstance.go:183  [n1] 43  exiting heartbeat loop
W210223 06:24:55.260174 283 jobs/registry.go:705  [-] 44  canceling all adopted jobs due to stopper quiescing
I210223 06:24:55.262864 1623 jobs/registry.go:1152  [n1] 45  AUTO CREATE STATS job 635670020478795777: stepping through state succeeded with error: <nil>
W210223 06:24:55.263306 1623 kv/txn.go:635  [n1] 46  failure aborting transaction: node unavailable; try another peer; abort caused by: context canceled
I210223 06:24:55.263735 1623 jobs/registry.go:1152  [n1] 47  AUTO CREATE STATS job 635670020478795777: stepping through state reverting with error: could not mark job 635670020478795777 as succeeded: context canceled
I210223 06:24:55.263735 1623 jobs/registry.go:1152  [n1] 47 +(1) attached stack trace
I210223 06:24:55.263735 1623 jobs/registry.go:1152  [n1] 47 +  -- stack trace:
I210223 06:24:55.263735 1623 jobs/registry.go:1152  [n1] 47 +  | github.com/cockroachdb/cockroach/pkg/jobs.(*Registry).stepThroughStateMachine
I210223 06:24:55.263735 1623 jobs/registry.go:1152  [n1] 47 +  | 	/go/src/github.com/cockroachdb/cockroach/pkg/jobs/registry.go:1226
I210223 06:24:55.263735 1623 jobs/registry.go:1152  [n1] 47 +  | github.com/cockroachdb/cockroach/pkg/jobs.(*Registry).stepThroughStateMachine
I210223 06:24:55.263735 1623 jobs/registry.go:1152  [n1] 47 +  | 	/go/src/github.com/cockroachdb/cockroach/pkg/jobs/registry.go:1174
I210223 06:24:55.263735 1623 jobs/registry.go:1152  [n1] 47 +  | github.com/cockroachdb/cockroach/pkg/jobs.(*Registry).runJob
I210223 06:24:55.263735 1623 jobs/registry.go:1152  [n1] 47 +  | 	/go/src/github.com/cockroachdb/cockroach/pkg/jobs/adopt.go:250
I210223 06:24:55.263735 1623 jobs/registry.go:1152  [n1] 47 +  | github.com/cockroachdb/cockroach/pkg/jobs.(*StartableJob).Start.func3
I210223 06:24:55.263735 1623 jobs/registry.go:1152  [n1] 47 +  | 	/go/src/github.com/cockroachdb/cockroach/pkg/jobs/jobs.go:867
I210223 06:24:55.263735 1623 jobs/registry.go:1152  [n1] 47 +  | github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunAsyncTask.func1
I210223 06:24:55.263735 1623 jobs/registry.go:1152  [n1] 47 +  | 	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:351
I210223 06:24:55.263735 1623 jobs/registry.go:1152  [n1] 47 +  | runtime.goexit
I210223 06:24:55.263735 1623 jobs/registry.go:1152  [n1] 47 +  | 	/usr/local/go/src/runtime/asm_amd64.s:1374
I210223 06:24:55.263735 1623 jobs/registry.go:1152  [n1] 47 +Wraps: (2) could not mark job 635670020478795777 as succeeded
I210223 06:24:55.263735 1623 jobs/registry.go:1152  [n1] 47 +Wraps: (3) context canceled
I210223 06:24:55.263735 1623 jobs/registry.go:1152  [n1] 47 +Error types: (1) *withstack.withStack (2) *errutil.withPrefix (3) *errors.errorString
W210223 06:24:55.264982 1623 kv/txn.go:635  [n1] 48  failure aborting transaction: node unavailable; try another peer; abort caused by: context canceled
W210223 06:24:55.267515 1555 sql/stats/automatic_stats.go:477  [-] 49  failed to create statistics on table 53: create-stats: job 635670020478795777: could not mark as reverting: could not mark job 635670020478795777 as succeeded: context canceled: context canceled
    testing.go:1038: race detected during execution of test
--- FAIL: TestImportFixture (1.20s)

```

<details><summary>More</summary><p>
Parameters:

- TAGS=
- GOFLAGS=-race -parallel=4

```
make stressrace TESTS=TestImportFixture PKG=./pkg/ccl/workloadccl TESTTIMEOUT=5m STRESSFLAGS='-timeout 5m' 2>&1
```

[See this test on roachdash](https://roachdash.crdb.dev/?filter=status%3Aopen+t%3A.%2ATestImportFixture.%2A&sort=title&restgroup=false&display=lastcommented+project)
<sub>powered by [pkg/cmd/internal/issues](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)</sub></p></details>

### LINKED ISSUE #60984: ccl/backupccl: TestBackupRestoreMultiNodeLocal failed
[(ccl/backupccl).TestBackupRestoreMultiNodeLocal failed](https://teamcity.cockroachdb.com/viewLog.html?buildId=2707910&tab=buildLog) on [master@2572200f7612c6508a52735a6a18767cfb7cc09d](https://github.com/cockroachdb/cockroach/commits/2572200f7612c6508a52735a6a18767cfb7cc09d):

```
      /go/src/github.com/cockroachdb/cockroach/pkg/ccl/backupccl/backup_processor.go:114 +0x164

Goroutine 1170 (running) created at:
  github.com/cockroachdb/cockroach/pkg/sql/flowinfra.(*FlowBase).startInternal()
      /go/src/github.com/cockroachdb/cockroach/pkg/sql/flowinfra/flow.go:326 +0x3f4
  github.com/cockroachdb/cockroach/pkg/sql/flowinfra.(*FlowBase).Start()
      /go/src/github.com/cockroachdb/cockroach/pkg/sql/flowinfra/flow.go:347 +0x97
  github.com/cockroachdb/cockroach/pkg/sql/rowflow.(*rowBasedFlow).Start()
      <autogenerated>:1 +0x84
  github.com/cockroachdb/cockroach/pkg/sql/flowinfra.(*FlowScheduler).runFlowNow()
      /go/src/github.com/cockroachdb/cockroach/pkg/sql/flowinfra/flow_scheduler.go:109 +0x27a
  github.com/cockroachdb/cockroach/pkg/sql/flowinfra.(*FlowScheduler).ScheduleFlow.func1()
      /go/src/github.com/cockroachdb/cockroach/pkg/sql/flowinfra/flow_scheduler.go:130 +0x81b
  github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunTaskWithErr()
      /go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:330 +0x129
  github.com/cockroachdb/cockroach/pkg/sql/flowinfra.(*FlowScheduler).ScheduleFlow()
      /go/src/github.com/cockroachdb/cockroach/pkg/sql/flowinfra/flow_scheduler.go:127 +0xcb
  github.com/cockroachdb/cockroach/pkg/sql/distsql.(*ServerImpl).SetupFlow()
      /go/src/github.com/cockroachdb/cockroach/pkg/sql/distsql/server.go:548 +0x48a
  github.com/cockroachdb/cockroach/pkg/sql/execinfrapb._DistSQL_SetupFlow_Handler.func1()
      /go/src/github.com/cockroachdb/cockroach/pkg/sql/execinfrapb/api.pb.go:510 +0xa1
  github.com/cockroachdb/cockroach/pkg/util/tracing.ServerInterceptor.func1()
      /go/src/github.com/cockroachdb/cockroach/pkg/util/tracing/grpc_interceptor.go:137 +0x3b7
  google.golang.org/grpc.getChainUnaryHandler.func1()
      /go/src/github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/server.go:921 +0x14f
  github.com/cockroachdb/cockroach/pkg/rpc.NewServer.func1()
      /go/src/github.com/cockroachdb/cockroach/pkg/rpc/context.go:176 +0x13a
  google.golang.org/grpc.getChainUnaryHandler.func1()
      /go/src/github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/server.go:921 +0x14f
  github.com/cockroachdb/cockroach/pkg/rpc.kvAuth.unaryInterceptor()
      /go/src/github.com/cockroachdb/cockroach/pkg/rpc/auth.go:60 +0xc8
  github.com/cockroachdb/cockroach/pkg/rpc.kvAuth.unaryInterceptor-fm()
      /go/src/github.com/cockroachdb/cockroach/pkg/rpc/auth.go:47 +0x84
  google.golang.org/grpc.chainUnaryServerInterceptors.func1()
      /go/src/github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/server.go:907 +0x112
  github.com/cockroachdb/cockroach/pkg/sql/execinfrapb._DistSQL_SetupFlow_Handler()
      /go/src/github.com/cockroachdb/cockroach/pkg/sql/execinfrapb/api.pb.go:512 +0x1dd
  google.golang.org/grpc.(*Server).processUnaryRPC()
      /go/src/github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/server.go:1082 +0xa05
  google.golang.org/grpc.(*Server).handleStream()
      /go/src/github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/server.go:1405 +0x138b
  google.golang.org/grpc.(*Server).serveStreams.func1.1()
      /go/src/github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/server.go:746 +0xdc
==================
    backup_test.go:930: job *jobspb.Payload_SchemaChange is not a backup: &{resume_span_list:<> desc_id:53 table_mutation_id:1 format_version:2 }
E210223 06:14:16.539690 22161 jobs/adopt.go:117  [-] 1  could not run claimed job 635667925497577473: job 635667925497577473: status changed to succeeded which is not resumable`
    backup_test.go:380: -- test log scope end --
test logs left over in: /go/src/github.com/cockroachdb/cockroach/artifacts/logTestBackupRestoreMultiNodeLocal192826056
    testing.go:1038: race detected during execution of test
--- FAIL: TestBackupRestoreMultiNodeLocal (22.82s)

```

<details><summary>More</summary><p>
Parameters:

- TAGS=
- GOFLAGS=-race -parallel=4

```
make stressrace TESTS=TestBackupRestoreMultiNodeLocal PKG=./pkg/ccl/backupccl TESTTIMEOUT=5m STRESSFLAGS='-timeout 5m' 2>&1
```

[See this test on roachdash](https://roachdash.crdb.dev/?filter=status%3Aopen+t%3A.%2ATestBackupRestoreMultiNodeLocal.%2A&sort=title&restgroup=false&display=lastcommented+project)
<sub>powered by [pkg/cmd/internal/issues](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)</sub></p></details>

### PR DESCRIPTION
**Pull request by pbardea**
This commit ensures that producer goroutines created during the
initialization of bulk processors use the same context as bp.Ctx.

This does change the context that these goroutines were using,
but that shouldn't actually have any effects on the processors, other
than missing tracing capabilities.

Closes https://github.com/cockroachdb/cockroach/issues/60940.

Closes https://github.com/cockroachdb/cockroach/issues/60984
Closes https://github.com/cockroachdb/cockroach/issues/60983
Closes https://github.com/cockroachdb/cockroach/issues/60977
Closes https://github.com/cockroachdb/cockroach/issues/60990
Closes https://github.com/cockroachdb/cockroach/issues/60989
Closes https://github.com/cockroachdb/cockroach/issues/60979
Closes https://github.com/cockroachdb/cockroach/issues/60987
Closes https://github.com/cockroachdb/cockroach/issues/60986
Closes https://github.com/cockroachdb/cockroach/issues/60985
Closes https://github.com/cockroachdb/cockroach/issues/60981
Closes https://github.com/cockroachdb/cockroach/issues/60980
Closes https://github.com/cockroachdb/cockroach/issues/60978
Closes https://github.com/cockroachdb/cockroach/issues/60978
Closes https://github.com/cockroachdb/cockroach/issues/60976
Closes https://github.com/cockroachdb/cockroach/issues/60975

Release note: None

### CODE REVIEW

File: pkg/ccl/streamingccl/streamingest/stream_ingestion_processor.go [hunk 1]
```diff
@@ -176,14 +172,14 @@ func (sip *streamIngestionProcessor) Start(ctx context.Context) {
 	startTime := timeutil.Unix(0 /* sec */, sip.spec.StartTime.WallTime)
 	eventChs := make(map[streamingccl.PartitionAddress]chan streamingccl.Event)
 	for _, partitionAddress := range sip.spec.PartitionAddresses {
-		eventCh, err := sip.client.ConsumePartition(sip.Ctx, partitionAddress, startTime)
+		eventCh, err := sip.client.ConsumePartition(ctx, partitionAddress, startTime)
```
Comment (pbardea) [inline pkg/ccl/streamingccl/streamingest/stream_ingestion_processor.go:175]: @yuzefovich Just wanted to check if there was a convention to use `ctx` here rather than `sip.Ctx`?

**Review by yuzefovich — COMMENTED** [review]
> Reviewed 1 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/60958)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @adityamaru and @pbardea)

___
*[pkg/ccl/streamingccl/streamingest/stream_ingestion_processor.go, line 175 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/60958#-MUAs24b4hOqaqyeWtWJ-r1-175:-MUAs_3VBcOSULmQGHvn:b48p58i) ([raw file](https://github.com/cockroachdb/cockroach/blob/53e60713c3dec6f2bfea959d95612bd03cc66b10/pkg/ccl/streamingccl/streamingest/stream_ingestion_processor.go#L175)):*
<details><summary><i>Previously, pbardea (Paul Bardea) wrote…</i></summary><blockquote>

@yuzefovich Just wanted to check if there was a convention to use `ctx` here rather than `sip.Ctx`?
</blockquote></details>

I think we tend to use `ctx` in most places (the only exceptions are `sampler` and `sample_aggregator`, I think), so this change LGTM.

**Review by adityamaru — APPROVED** [review]

**Comment by ajstorm** [comment]
Just a heads-up that #60928 is also blocked on this issue.  You can see the test case failure it's getting [here](https://teamcity.cockroachdb.com/viewLog.html?buildId=2707329&buildTypeId=Cockroach_UnitTests_Testrace&tab=buildResultsDiv&branch_Cockroach_UnitTests=60928).

**Comment by pbardea** [comment]
Ack, this has been hitting a lot of flakes. Rebased in case any tests have been updated on master/flakes addressed recently.

**Comment by pbardea** [comment]
Flaked on https://github.com/cockroachdb/cockroach/issues/60803 in https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_UnitTests/2709561?

**Comment by pbardea** [comment]
TFTRs, merging with high priority to address the flakes
bors r=adityamaru p=9999 single on

**Comment by pbardea** [comment]
Hit a couple of flakes
bors r=adityamaru p=9999 single on

**Comment by pbardea** [comment]
@ajstorm this flaked on https://github.com/cockroachdb/cockroach/issues/60773  in https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_UnitTests/2709929?. Unsure what's happening, but I added a commit that skips the entire test. We've been seeing some imports hand due to KV changes, which may be related to these restores hanging.

Could I get a stamp for the second commit?

**Review by adityamaru — APPROVED** [review]

**Comment by pbardea** [comment]
bors r=adityamaru

**Comment by pbardea** [comment]
Got a nil pointer deref on 
TestReplicateRemovedNodeDisruptiveElection in ^

**Comment by pbardea** [comment]
bors r=adityamaru
