### PR TITLE
roachpb: add nil check in BatchRequest.Summary()

### LINKED ISSUE #83690: ccl/sqlproxyccl: TestCurConnCountMetric failed
ccl/sqlproxyccl.TestCurConnCountMetric [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_StressBazel/5618108?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_StressBazel/5618108?buildTab=artifacts#/) on master @ [78caa5c3a8ecd0d0a612798a106b626edb3db2ee](https://github.com/cockroachdb/cockroach/commits/78caa5c3a8ecd0d0a612798a106b626edb3db2ee):

```
=== RUN   TestCurConnCountMetric
    test_log_scope.go:79: test logs captured to: /artifacts/tmp/_tmp/fe188f163e90a7ffb92e92cbaea22b0c/logTestCurConnCountMetric3565568575
    test_log_scope.go:80: use -show-logs to present logs inline
```
<p>Parameters: <code>TAGS=bazel,gss</code>
</p>
<details><summary>Help</summary>
<p>

See also: [How To Investigate a Go Test Failure \(internal\)](https://cockroachlabs.atlassian.net/l/c/HgfXfJgM)
</p>
</details>
/cc @cockroachdb/sql-experience @cockroachdb/server
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*TestCurConnCountMetric.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)
</sub>

Jira issue: CRDB-17208

### PR DESCRIPTION
**Pull request by rafiss**
fixes #83690

We've observed the following stack trace: (https://github.com/cockroachdb/cockroach/issues/83690#issuecomment-1208200276)
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x13394b9]

goroutine 2973215 [running]:
github.com/cockroachdb/cockroach/pkg/roachpb.(*BatchRequest).WriteSummary(0x0, 0xc018fe3ba8)
	github.com/cockroachdb/cockroach/pkg/roachpb/bazel-out/k8-dbg/bin/pkg/roachpb/batch_generated.go:753 +0x39
github.com/cockroachdb/cockroach/pkg/roachpb.(*BatchRequest).Summary(0x0)
	github.com/cockroachdb/cockroach/pkg/roachpb/bazel-out/k8-dbg/bin/pkg/roachpb/batch_generated.go:746 +0x3a
github.com/cockroachdb/cockroach/pkg/kv/kvclient/kvcoord.(*TxnCoordSender).maybeRejectClientLocked(0xc016d36b00, {0x660a708, 0xc00e976a50}, 0x0)
	github.com/cockroachdb/cockroach/pkg/kv/kvclient/kvcoord/txn_coord_sender.go:702 +0x19a
github.com/cockroachdb/cockroach/pkg/kv/kvclient/kvcoord.(*TxnCoordSender).checkTxnStatusLocked(0xc016d36b00, {0x660a708, 0xc00e976a50}, 0x1)
	github.com/cockroachdb/cockroach/pkg/kv/kvclient/kvcoord/txn_coord_sender.go:1212 +0x6b
github.com/cockroachdb/cockroach/pkg/kv/kvclient/kvcoord.(*TxnCoordSender).GetLeafTxnInputState(0xc016d36b00, {0x660a708, 0xc00e976a50}, 0x1)
	github.com/cockroachdb/cockroach/pkg/kv/kvclient/kvcoord/txn_coord_sender.go:1158 +0x114
github.com/cockroachdb/cockroach/pkg/kv.(*Txn).GetLeafTxnInputStateOrRejectClient(0xc00cd10f20, {0x660a708, 0xc00e976a50})
	github.com/cockroachdb/cockroach/pkg/kv/txn.go:1297 +0x1d7
github.com/cockroachdb/cockroach/pkg/sql.(*DistSQLPlanner).Run(0xc00c62af00, {0x660a708, 0xc00e976a50}, 0xc01559a4b0, 0xc00cd10f20, 0xc0032a8500, 0xc0225f1180, 0xc0012bbf08, 0x0)
	github.com/cockroachdb/cockroach/pkg/sql/distsql_running.go:586 +0x1357
```

This patch will prevent the node from crashing.

Release justification: fix a panic
Release note: None

### CODE REVIEW

File: pkg/kv/kvclient/kvcoord/txn_coord_sender.go [hunk 1]
```diff
@@ -698,8 +698,12 @@ func (tc *TxnCoordSender) maybeRejectClientLocked(
 	case txnError:
 		return tc.mu.storedErr
 	case txnFinalized:
+		summary := "nil batch"
+		if ba != nil {
+			summary = ba.Summary()
+		}
```
Comment (erikgrinaker) [inline pkg/kv/kvclient/kvcoord/txn_coord_sender.go:704]: Oops, thanks! Maybe it'd be better to just make `Summary()` safe to use with a `nil` receiver? No strong opinion either way, this works too.

File: pkg/kv/kvclient/kvcoord/txn_coord_sender.go [hunk 2]
```diff
@@ -1209,6 +1213,7 @@ func (tc *TxnCoordSender) checkTxnStatusLocked(ctx context.Context, opt kv.TxnSt
 		// Nothing to check.
 	case kv.OnlyPending:
 		// Check the coordinator's proto status.
+		// todo fix
```
Comment (erikgrinaker) [inline pkg/kv/kvclient/kvcoord/txn_coord_sender.go:1216]: Do we need to fix this?

Comment (rafiss) [reply pkg/kv/kvclient/kvcoord/txn_coord_sender.go:1216]: whoops that was my old scratch note when i was using the debugger

File: pkg/kv/kvclient/kvcoord/txn_coord_sender.go (hunk 1 above)
Comment (rafiss) [reply pkg/kv/kvclient/kvcoord/txn_coord_sender.go:704]: yeah i will make it handle a nil receiver. i wasn't sure which KV would find more conventional

File: pkg/roachpb/batch_generated.go [hunk 3]
```diff
@@ -761,6 +761,10 @@ func (ba *BatchRequest) Summary() string {
 // WriteSummary writes a short summary of the requests in a batch
 // to the provided builder.
 func (ba *BatchRequest) WriteSummary(b *strings.Builder) {
+	if ba == nil {
+		b.WriteString("nil batch")
+		return
+	}
```
[the remark this answers is not in the document]
Comment (rafiss) [reply pkg/roachpb/batch_generated.go:767]: ah thanks for the pointer.

**Review by erikgrinaker — APPROVED** [review]
LGTM, thanks!

**Comment by rafiss** [comment]
thanks for the review!

bors r=erikgrinaker

**Comment by rafiss** [comment]
bors r=erikgrinaker
