### PR TITLE
opt: fix rare incorrect results due to sort between paired joins

### LINKED ISSUE #89603: sql: incorrect results due to sort in-between paired joins
roachtest.costfuzz [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/6837153?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/6837153?buildTab=artifacts#/costfuzz) on release-22.2 @ [64049e4b9210de3af4a1d814a9af0123b59a055f](https://github.com/cockroachdb/cockroach/commits/64049e4b9210de3af4a1d814a9af0123b59a055f):

```
		  | + 	``a	,0,NULL,X,0``,
		  | + 	``a	,0,NULL,X,0``,
		  |   	"a,0,0,X,0",
		  |   	"a,0,NULL,X,0",
		  |   	... // 166 identical elements
		  |   	"\x8eC\xec,0,NULL,X,0",
		  |   	"\x8eC\xec,0,NULL,X,0",
		  | + 	"\x8eC\xec,0,NULL,X,0",
		  |   	"\xa7\xa8\xa1\xcc\xfd\xa6\xc2\xc1,0,0,X,0",
		  | - 	"\xa7\xa8\xa1\xcc\xfd\xa6\xc2\xc1,0,NULL,X,0",
		  |   	"\xa7\xa8\xa1\xcc\xfd\xa6\xc2\xc1,0,NULL,X,0",
		  |   	"\xa7\xa8\xa1\xcc\xfd\xa6\xc2\xc1,0,NULL,X,0",
		  |   	... // 64 identical elements
		  |   	"á,0,NULL,X,0",
		  |   	"\xc4\x12|\x19\xab,0,0,X,0",
		  | + 	"\xc4\x12|\x19\xab,0,NULL,X,0",
		  |   	"\xc4\x12|\x19\xab,0,NULL,X,0",
		  |   	"\xc4\x12|\x19\xab,0,NULL,X,0",
		  |   	... // 30 identical elements
		  |   	"\xc4\x12|\x19\xab,0,NULL,X,0",
		  |   	"\xca,0,0,X,0",
		  | - 	"\xca,0,NULL,X,0",
		  |   	"\xca,0,NULL,X,0",
		  |   	"\xca,0,NULL,X,0",
		  |   	... // 64 identical elements
		  |   }
		  | sql: SELECT
		  | 	tab_17534.col1_3 AS col_52140,
		  | 	0:::OID AS col_52141,
		  | 	tab_17533.col1_7 AS col_52142,
		  | 	'\x58':::BYTES AS col_52143,
		  | 	0:::OID AS col_52144
		  | FROM
		  | 	defaultdb.public.table1@[0] AS tab_17533
		  | 	RIGHT JOIN defaultdb.public.table1@[0] AS tab_17534
		  | 		JOIN defaultdb.public.table1@[0] AS tab_17535 ON
		  | 				(tab_17534.crdb_internal_mvcc_timestamp) = (tab_17535.crdb_internal_mvcc_timestamp)
		  | 				AND (tab_17534.col1_4) = (tab_17535.col1_4)
		  | 		JOIN defaultdb.public.table1@[0] AS tab_17536 ON
		  | 				(tab_17535.col1_1) = (tab_17536.col1_1)
		  | 				AND (tab_17535.col1_3) = (tab_17536.col1_3)
		  | 				AND (tab_17534.col1_6) = (tab_17536.col1_6)
		  | 		JOIN defaultdb.public.table1@[0] AS tab_17537
		  | 			JOIN defaultdb.public.table1@[0] AS tab_17538 ON
		  | 					(tab_17537.crdb_internal_mvcc_timestamp) = (tab_17538.crdb_internal_mvcc_timestamp) ON
		  | 				(tab_17536.col1_2) = (tab_17538.col1_2) AND (tab_17535.col1_4) = (tab_17537.col1_4) ON
		  | 			(tab_17533.col1_3) = (tab_17537.col1_3) AND (tab_17533.col1_6) = (tab_17536.col1_6)
		  | ORDER BY
		  | 	tab_17535.col1_4, tab_17535.col1_3 DESC
		Error types: (1) *withstack.withStack (2) *errutil.withPrefix (3) *withstack.withStack (4) *errutil.leafError
```
<p>Parameters: <code>ROACHTEST_cloud=gce</code>
, <code>ROACHTEST_cpu=4</code>
, <code>ROACHTEST_encrypted=false</code>
, <code>ROACHTEST_ssd=0</code>
</p>
<details><summary>Help</summary>
<p>

See: [roachtest README](https://github.com/cockroachdb/cockroach/blob/master/pkg/cmd/roachtest/README.md)

See: [How To Investigate \(internal\)](https://cockroachlabs.atlassian.net/l/c/SSSBr8c7)

</p>
</details>
<details><summary>Same failure on other branches</summary>
<p>

- #86796 roachtest.costfuzz failed due to scientific notation v. decimal notation [C-test-failure T-sql-queries]
</p>
</details>
/cc @cockroachdb/sql-queries
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*costfuzz.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)
</sub>

Jira issue: CRDB-20329

### PR DESCRIPTION
**Pull request by DrewKimball**
Previously, it was possible for paired joins to produce incorrect results in the case when an ordering was required of their output, and a sort was added between the paired joins to enforce the ordering.

This patch prevents a sort from being added to the output of the first join in a set of paired joins. This is necessary because the continuation column that is used to indicate false positives matched by the first join relies on the ordering being maintained between the joins.

Fixes #89603

Release note: None

### CODE REVIEW

**Review by msirek — APPROVED** [review]
Thanks for fixing this!  It is much simpler and more straightforward than #89840. I will close that PR.
LGTM

**Comment by DrewKimball** [comment]
TFTR! Yeah, it helped to talk things through as a pair-programming project. Still might be ideal to make it a single operator or something, but this seems like the easiest fix considering it's probably a pretty rare bug.

The test failures are the same as #92536, so unrelated.

File: pkg/sql/opt/ordering/ordering.go [hunk 1]
```diff
@@ -31,6 +31,30 @@ func CanProvide(expr memo.RelExpr, required *props.OrderingChoice) bool {
...
+		checkRequired(expr, required)
+	}
+	switch t := expr.(type) {
+	case *memo.ExplainExpr:
+		return false
+	case *memo.LookupJoinExpr:
+		// For paired joins we use a boolean continuation column that to handle
+		// false positive matches in the first join. This relies on the ordering
+		// being unchanged between the first and second joins, so enforcing a
+		// sort on top of this expression could lead to incorrect results.
```
Comment (rytaft) [inline pkg/sql/opt/ordering/ordering.go:50]: nit: that to handle -> to handle
nit: enforcing a sort -> adding a sort (or enforcing an ordering)

**Review by rytaft — APPROVED** [review]
LGTM thanks!

**Comment by rytaft** [comment]
Consider also adding a backport label for 22.2 and 22.1

File: pkg/sql/opt/ordering/ordering.go (hunk 1 above)
Comment (DrewKimball) [reply pkg/sql/opt/ordering/ordering.go:50]: Done.

**Review by rytaft — APPROVED** [review]
LGTM

**Review by mgartner — APPROVED** [review]
Very nice! LGTM

**Comment by DrewKimball** [comment]
TFTRs!

**Comment by DrewKimball** [comment]
The linter failure is a known issue.

bors r+
