### PR TITLE
changefeedccl: fix test flake by waiting for rangefeed start

### LINKED ISSUE #152060: ccl/changefeedccl: TestDistSenderRangeFeedPopulatesVirtualTable failed
ccl/changefeedccl.TestDistSenderRangeFeedPopulatesVirtualTable [failed](https://mesolite.cluster.engflow.com/invocations/default/d2010221-d834-46a0-8d93-28693a66cbb7?testReportRun=1&testReportShard=6&testReportAttempt=1#targets-Ly9wa2cvY2NsL2NoYW5nZWZlZWRjY2w6Y2hhbmdlZmVlZGNjbF90ZXN0) on master @ [fdb56245f7d6367aa1db9adccf80540809998f74](https://github.com/cockroachdb/cockroach/commits/fdb56245f7d6367aa1db9adccf80540809998f74):

```
=== RUN   TestDistSenderRangeFeedPopulatesVirtualTable
    test_log_scope.go:171: test logs captured to: outputs.zip/logTestDistSenderRangeFeedPopulatesVirtualTable4253384554
    test_log_scope.go:82: use -show-logs to present logs inline
    changefeed_test.go:9621: -- test log scope end --
test logs left over in: outputs.zip/logTestDistSenderRangeFeedPopulatesVirtualTable4253384554
--- FAIL: TestDistSenderRangeFeedPopulatesVirtualTable (2.28s)
=== RUN   TestDistSenderRangeFeedPopulatesVirtualTable/cloudstorage
    helpers_test.go:1389: making server as secondary tenant
    helpers_test.go:1468: making cloudstorage feed factory
    helpers_test.go:1196: did not force enriched envelope for CREATE CHANGEFEED FOR table_a; because *changefeedccl.cloudFeedFactory is not supported
    testfeed_test.go:342: creating external connection
    testfeed_test.go:345: ran create external connection
    changefeed_test.go:9609: 
        	Error Trace:	pkg/ccl/changefeedccl/changefeed_test.go:9609
        	            				pkg/ccl/changefeedccl/testfeed_test.go:876
        	            				pkg/ccl/changefeedccl/helpers_test.go:1262
        	            				pkg/ccl/changefeedccl/changefeed_test.go:9606
        	            				pkg/testutils/soon.go:71
        	            				pkg/util/retry/retry.go:346
        	            				pkg/testutils/soon.go:77
        	            				pkg/testutils/soon.go:56
        	            				pkg/testutils/soon.go:38
        	            				pkg/ccl/changefeedccl/changefeed_test.go:9605
        	            				pkg/ccl/changefeedccl/helpers_test.go:1648
        	            				pkg/ccl/changefeedccl/helpers_test.go:1684
        	Error:      	[]int{3, 5, 20, 6, 3, 46, 3, 5, 32} does not contain 108
        	Test:       	TestDistSenderRangeFeedPopulatesVirtualTable/cloudstorage
        	Messages:   	user adminUser should see table 108
--- FAIL: TestDistSenderRangeFeedPopulatesVirtualTable/cloudstorage (2.27s)
```

Parameters:
 - <code>attempt=1</code>
 - <code>run=1</code>
 - <code>shard=6</code>
<details><summary>Help</summary>
<p>

See also: [How To Investigate a Go Test Failure \(internal\)](https://cockroachlabs.atlassian.net/l/c/HgfXfJgM)
</p>
</details>
/cc @cockroachdb/cdc
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*TestDistSenderRangeFeedPopulatesVirtualTable.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/bazci/githubpost/issues)

</sub>

Jira issue: CRDB-53614

### PR DESCRIPTION
**Pull request by aerfrei**
Previously, this test would flake because a table that we were asserting the admin user could see hadn't yet become visible. Now we assert the changefeed and rangefeed have started by waiting for a highwater mark.

Epic: none
Fixes: #152060

Release note: None

### CODE REVIEW

File: pkg/ccl/changefeedccl/changefeed_test.go [hunk 1]
```diff
@@ -9607,10 +9605,10 @@ func TestDistSenderRangeFeedPopulatesVirtualTable(t *testing.T) {
 		user           string
 		shouldSeeTable bool
 	}{
-		{`feedCreator`, false},
-		{`regularUser`, false},
 		{`adminUser`, true},
 		{`viewClusterMetadataUser`, true},
+		{`feedCreator`, false},
```
Comment (andyyang890) [inline pkg/ccl/changefeedccl/changefeed_test.go]: What's the point of reordering the cases? I ask because changes like this have the cost of adding another commit to the git blame history (for these lines) so there needs to be some kind of benefit that outweighs that

**Review by andyyang890 — APPROVED** [review]
Nice find!

File: pkg/ccl/changefeedccl/changefeed_test.go (hunk 1 above)
Comment (aerfrei) [reply pkg/ccl/changefeedccl/changefeed_test.go]: It's possible that the feed creator case was possible not because they lacked the permissions but because no one was able to see the table since the rangefeed hadn't started up yet (this is the reason the admin user case was failing). Putting the true cases before the false cases ensures that the tables are visible to someone when the feed creator can't see them. Do you think it's worth including? I don't feel strongly

Comment (andyyang890) [reply pkg/ccl/changefeedccl/changefeed_test.go]: IMO it's not really worth switching since with either order, the subtest that would fail would still be `adminUser` right? We might actually want to randomize the order by using a map instead of a slice so there's more variance, up to you if you want to make that change

**Comment by aerfrei** [comment]
I believe that between this and #152850 (merging now) that this test should pass. The extended CI failure should be fixed by #152850.

**Comment by aerfrei** [comment]
bors r=andyyang890
