### PR TITLE
bulkio: Dry run backup when creating schedules.

### LINKED ISSUE #52924: backup: dry-run plan a BACKUP during schedule creation
Right now backup schedule creation has a lot of checks that overlap with checks done during BACKUP to try to help prevent operators from making schedules that will fail to run and inform them of errors right away so they can fix them before creating a schedule (and waiting for it to run). Unfortunately these are currently duplicating some, but not all, of the checks done during BACKUP planning. We should be able to use a `DETACHED` backup statement to plan and just roll it back if it succeeds instead to re-use the actual checks of backup itself. We might want to use savepoints to do so nested in the schedule transaction, or in a standalone txn if it is just sanity-checking the args and does not depend on the schedule txn at all.

### PR DESCRIPTION
**Pull request by miretskiy**
Fixes #52924

Dry run execution of the scheduled backup.

Invoking backup planning and execution in dry run ensures
that the scheduled backup is sane since all of the required
sanity checks are performed when attempting to run the backup.
The actual effects of this dry run are removed by rolling back
to the safepoint.

Release Notes: None

### CODE REVIEW

File: pkg/ccl/backupccl/create_scheduled_backup.go [hunk 1]
```diff
@@ -407,6 +384,29 @@ func makeBackupSchedule(
...
+// dryRunBackup executes backup in dry-run mode: we simply execute backup
+// under transaction savepoint, and then rollback to that save point.
+func dryRunBackup(ctx context.Context, p sql.PlanHookState, backupNode *tree.Backup) error {
+	sp, err := p.ExtendedEvalContext().Txn.CreateSavepoint(ctx)
+	if err != nil {
+		return err
+	}
+	err = dryRunInvokeBackup(ctx, p, backupNode)
+	rollbackErr := p.ExtendedEvalContext().Txn.RollbackToSavepoint(ctx, sp)
+	if err == nil {
```
Comment (dt) [inline pkg/ccl/backupccl/create_scheduled_backup.go:396]: I think I'd almost _rather_ see this one as it is rather unexpected, no?

**Review by dt — APPROVED** [review]

**Review by miretskiy — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/52993)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dt)

___
*[pkg/ccl/backupccl/create_scheduled_backup.go, line 396 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/52993#-MF1vSbz6xqZ01veMf9J-r2-396:-MF59fYn3oJ3qvMg2h7F:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/a83d70a9f4eb69405b89c95222a979afd2e1bda4/pkg/ccl/backupccl/create_scheduled_backup.go#L396)):*
<details><summary><i>Previously, dt (David Taylor) wrote…</i></summary><blockquote>

I think I'd almost _rather_ see this one as it is rather unexpected, no?
</blockquote></details>

Done.
