### PR TITLE
sql: avoid splitting the planner when expanding sub-queries

### LINKED ISSUE #11701: sql: DROP DATABASE can hang forever in waitForOneVersion
I discovered this while trying to update `TestLogic` to re-use database infrastructure between subtests. Could be related to #7648, and possibly #10830.

To reproduce, add the following text to the bottom of `sql/testdata/datetime`:

```
statement ok
DROP DATABASE test
```

and execute `make test PKG=./pkg/sql TESTFLAGS=-v TESTS=TestLogic/datetime`. You'll see the test hang. The goroutine that is causing the hang has the following stack trace:
```
goroutine 173 [runnable]:
github.com/cockroachdb/cockroach/pkg/util/retry.(*Retry).Next(0xc421178718, 0xc4200171a8)
        /Users/jordan/repo/src/github.com/cockroachdb/cockroach/pkg/util/retry/retry.go:128 +0x1a5
github.com/cockroachdb/cockroach/pkg/sql.LeaseStore.waitForOneVersion(0x5da2e40, 0xc4205fa500, 0x3ff0000000000000, 0x2faf080, 0x12a05f200, 0x40000000000000
00, 0x0, 0x0, 0x0, 0xc42000dac0, ...)
        /Users/jordan/repo/src/github.com/cockroachdb/cockroach/pkg/sql/lease.go:262 +0x16a
github.com/cockroachdb/cockroach/pkg/sql.(*SchemaChanger).waitToUpdateLeases(0xc420fb8400, 0xc400000037, 0x148ba2ffb149746b, 0x1)
        /Users/jordan/repo/src/github.com/cockroachdb/cockroach/pkg/sql/schema_changer.go:434 +0xf5
github.com/cockroachdb/cockroach/pkg/sql.SchemaChanger.exec(0x37, 0x1, 0x5da2e40, 0xc4205fa500, 0x3ff0000000000000, 0x2faf080, 0x12a05f200, 0x4000000000000
000, 0x0, 0x0, ...)
        /Users/jordan/repo/src/github.com/cockroachdb/cockroach/pkg/sql/schema_changer.go:234 +0x9b6
github.com/cockroachdb/cockroach/pkg/sql.(*schemaChangerCollection).execSchemaChanges(0xc4204a3b90, 0xc4200e0580, 0xc4204a3c70, 0xc4209d82d0, 0x1, 0x1)
        /Users/jordan/repo/src/github.com/cockroachdb/cockroach/pkg/sql/session.go:480 +0x2fa
github.com/cockroachdb/cockroach/pkg/sql.(*Executor).execRequest(0xc4200e0580, 0xc4204a3b00, 0xc420d0efc8, 0x12, 0x0, 0x0, 0x0, 0x0, 0xc420ff9400)
        /Users/jordan/repo/src/github.com/cockroachdb/cockroach/pkg/sql/executor.go:674 +0xb91
github.com/cockroachdb/cockroach/pkg/sql.(*Executor).ExecuteStatements(0xc4200e0580, 0xc4204a3b00, 0xc420d0efc8, 0x12, 0x0, 0x0, 0x0, 0x0, 0xc420d0ef00)
        /Users/jordan/repo/src/github.com/cockroachdb/cockroach/pkg/sql/executor.go:430 +0x11f
github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*v3Conn).executeStatements(0xc420d13c00, 0x5dbb500, 0xc420199710, 0xc420d0efc8, 0x12, 0x0, 0x0, 0x0, 0x0,0
x453a901, ...)
        /Users/jordan/repo/src/github.com/cockroachdb/cockroach/pkg/sql/pgwire/v3.go:746 +0x94
github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*v3Conn).handleSimpleQuery(0xc420d13c00, 0x5dbb500, 0xc420199710, 0xc420d13c28, 0x17, 0x0)
        /Users/jordan/repo/src/github.com/cockroachdb/cockroach/pkg/sql/pgwire/v3.go:420 +0xb3
github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*v3Conn).serve(0xc420d13c00, 0x5dbb500, 0xc420199710, 0x5400, 0xc4200ba138, 0x5dbb500, 0xc4202b8870, 0x0,0
x0)
        /Users/jordan/repo/src/github.com/cockroachdb/cockroach/pkg/sql/pgwire/v3.go:347 +0x8b6
github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*Server).ServeConn(0xc4200ba000, 0x5dbb500, 0xc4202b8870, 0x5dc19a0, 0xc420478700, 0x0, 0x0)
        /Users/jordan/repo/src/github.com/cockroachdb/cockroach/pkg/sql/pgwire/server.go:309 +0x999
github.com/cockroachdb/cockroach/pkg/server.(*Server).Start.func8.1(0x5dc2720, 0xc42088e160)
        /Users/jordan/repo/src/github.com/cockroachdb/cockroach/pkg/server/server.go:504 +0x106
github.com/cockroachdb/cockroach/pkg/util/netutil.(*Server).ServeWith.func1(0xc4200de090, 0xc42016e160, 0x5dc2720, 0xc42088e160, 0xc420275760)
        /Users/jordan/repo/src/github.com/cockroachdb/cockroach/pkg/util/netutil/net.go:136 +0x95
created by github.com/cockroachdb/cockroach/pkg/util/netutil.(*Server).ServeWith
        /Users/jordan/repo/src/github.com/cockroachdb/cockroach/pkg/util/netutil/net.go:138 +0x277
```

### PR DESCRIPTION
**Pull request by knz**
Prior to this patch, the code that expands sub-queries would duplicate
the `planner` object to create the sub-query planNode's
recursively. This was perceived to be needed, as indicated by a
previous comment that had been erased in
4acdc8a77e8554180ca0fbda8b3d14dc7ad35482, because there may be nested
sub-queries that would cause the `subqueryVisitor` embedded in planner
to be reset during the recursion.

The problem with this approach is that whichever leases were acquired
by the sub-queries, and embedded in the planner copy, are then lost
after the sub-query is replaced and cannot be released at the end of
the session.

This patch fixes this problem by ensuring the same planner object is
reused throughout the recursion, and preserves only the state of the
embedded `subqueryVisitor` across the recursive call.

A proper long-term protection against this type of issue would be to
avoid embedding visitors in the planner object, and instead managing a
cache of visitor objects if profiling shows that visitor allocation is
hurting performance.

Fixes #11701.

---
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/11730)

### CODE REVIEW

**Comment by knz** [comment]
@vivekmenezes could you guide me about how to best test this. You explain in the linked issue we can check that all leases are released. How do you propose to do this? 

My proposal would be to add a new directive in our `testdata` input parser (in TestLogic) to forcefully/manually purge leases currently held in the planner, then use a SELECT query in the lease table just after that to see whether there are remaining entries in the lease table. What do you think about this?

**Comment by vivekmenezes** [comment]
Look at the code in lease.go that references removeOnceDereferenced . From the logic tests we should always set this to true, that way the leases are released as soon as they are dereferenced. And then at the end of each test file query the lease table and ensure there are no records.

**Comment by vivekmenezes** [comment]
thanks for fixing it!

**Comment by tamird** [comment]
Should there be a `NoCopy` in `planner`?

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/11730#-:-KXr8hGWbBHZan17jQKY:b-wnu13m)*

**Comment by knz** [comment]
@tamird yes, that's a good idea too!
(Doing so didn't uncover other unwanted copies. Yay.)

**Comment by vivekmenezes** [comment]
https://github.com/golang/go/issues/8005#issuecomment-190753527

is what tamir is referring to

**Comment by tamird** [comment]
not quite https://github.com/cockroachdb/cockroach/blob/master/pkg/util/nocopy.go

**Comment by knz** [comment]
I've used that before, thanks

**Comment by knz** [comment]
Ok I have added the NoCopy members and a specific test. PTAL.

**Comment by tamird** [comment]
:lgtm:

---

Reviewed 4 of 4 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[pkg/sql/lease_test.go, line 646 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/11730#-KXrvljPdHU1CNJooCtR:-KXrvljPdHU1CNJooCtS:b-thuudh) ([raw file](https://github.com/cockroachdb/cockroach/blob/5156138b513bf1603c93f36191b1974aaf4aa708/pkg/sql/lease_test.go#L646)):*
> ```Go
> 			LeaseStoreTestingKnobs: csql.LeaseStoreTestingKnobs{
> 				RemoveOnceDereferenced: true,
> 				LeaseReleasedEvent: func(lease *csql.LeaseState, err error) {
> ```

s/err/_/

---

*[pkg/sql/lease_test.go, line 677 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/11730#-KXrvs4hL4I0XX893ctH:-KXrvs4hL4I0XX893ctI:b-l6mwxj) ([raw file](https://github.com/cockroachdb/cockroach/blob/5156138b513bf1603c93f36191b1974aaf4aa708/pkg/sql/lease_test.go#L677)):*
> ```Go
> 		t.Fatal("lease from sub-query was not released")
> 	case <-fooRelease:
> 		return
> ```

remove

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/11730#-:-KXrvtM_F9V0c5bh0bWa:bnfp4nl)*

File: pkg/sql/lease_test.go [hunk 1]
```diff
@@ -629,3 +630,50 @@ INSERT INTO t.kv VALUES ('a', 'b');
...
+
+	fooRelease := make(chan struct{})
+
+	params.Knobs = base.TestingKnobs{
+		SQLLeaseManager: &csql.LeaseManagerTestingKnobs{
+			LeaseStoreTestingKnobs: csql.LeaseStoreTestingKnobs{
+				RemoveOnceDereferenced: true,
+				LeaseReleasedEvent: func(lease *csql.LeaseState, err error) {
+					if lease.Name == "foo" {
+						fooRelease <- struct{}{}
```
Comment (vivekmenezes) [inline pkg/sql/lease_test.go]: close fooRelease

File: pkg/sql/lease_test.go [hunk 2]
```diff
@@ -629,3 +630,50 @@ INSERT INTO t.kv VALUES ('a', 'b');
...
+CREATE TABLE t.foo (v INT);
+SELECT EXISTS(SELECT * FROM t.foo);
+`); err != nil {
+		t.Fatal(err)
+	}
+
+	// The above SELECT has acquired a lease on the table. Now close the
+	// session, which should release the new lease and delete it because
+	// of the testing knob set above.
+	sqlDB.Close()
```
Comment (vivekmenezes) [inline pkg/sql/lease_test.go]: is this really needed?

**Review by vivekmenezes — APPROVED** [review]

**Comment by knz** [comment]
TFYRs!

---

Review status: all files reviewed at latest revision, 4 unresolved discussions, all commit checks successful.

---

*[pkg/sql/lease_test.go, line 646 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/11730#-KXrvljPdHU1CNJooCtR:-KXtZw-NCJLeMSAVFrtN:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/5156138b513bf1603c93f36191b1974aaf4aa708/pkg/sql/lease_test.go#L646)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

s/err/_/
</blockquote></details>

Done.

---

*[pkg/sql/lease_test.go, line 648 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/11730#-KXrGnVanENsR5v-po47-r2-648:-KXtZwLS_jfUoDruU8Xg:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/5156138b513bf1603c93f36191b1974aaf4aa708/pkg/sql/lease_test.go#L648)):*
<details><summary><i>Previously, vivekmenezes wrote…</i></summary><blockquote>

close fooRelease
</blockquote></details>

Done.

---

*[pkg/sql/lease_test.go, line 668 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/11730#-KXrGnVanENsR5v-po47-r2-668:-KXtZx57OXInZCbhxzCy:btd6qnp) ([raw file](https://github.com/cockroachdb/cockroach/blob/5156138b513bf1603c93f36191b1974aaf4aa708/pkg/sql/lease_test.go#L668)):*
<details><summary><i>Previously, vivekmenezes wrote…</i></summary><blockquote>

is this really needed?
</blockquote></details>

the leases are not released until the session is closed. Closing the connection releases the session.

---

*[pkg/sql/lease_test.go, line 677 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/11730#-KXrvs4hL4I0XX893ctH:-KXt_3ZqvBKV6Y5eGXLO:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/5156138b513bf1603c93f36191b1974aaf4aa708/pkg/sql/lease_test.go#L677)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

remove
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/11730#-:-KXt_4v10mgx5ElHJ3t7:bz5phge)*

**Comment by vivekmenezes** [comment]
:lgtm:

---

Review status: 4 of 5 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[pkg/sql/lease_test.go, line 668 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/11730#-KXrGnVanENsR5v-po47-r2-668:-KXv-Cgc2CG4_8I0w7NT:biybzsr) ([raw file](https://github.com/cockroachdb/cockroach/blob/5156138b513bf1603c93f36191b1974aaf4aa708/pkg/sql/lease_test.go#L668)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

the leases are not released until the session is closed. Closing the connection releases the session.
</blockquote></details>

https://github.com/cockroachdb/cockroach/blob/master/pkg/sql/executor.go#L673

is where it gets released at the end of a transaction. Are you sure this is needed?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/11730#-:-KXv-NVYI92asXe1T7Bj:bnfp4nl)*

**Comment by RaduBerinde** [comment]
LGTM

**Comment by knz** [comment]
TFYRs

---

Review status: 2 of 5 files reviewed at latest revision, 2 unresolved discussions.

---

*[pkg/sql/lease_test.go, line 668 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/11730#-KXrGnVanENsR5v-po47-r2-668:-KYDv9sfoaSko1ETo9Mr:b-kvn3gb) ([raw file](https://github.com/cockroachdb/cockroach/blob/5156138b513bf1603c93f36191b1974aaf4aa708/pkg/sql/lease_test.go#L668)):*
<details><summary><i>Previously, vivekmenezes wrote…</i></summary><blockquote>

https://github.com/cockroachdb/cockroach/blob/master/pkg/sql/executor.go#L673

is where it gets released at the end of a transaction. Are you sure this is needed?
</blockquote></details>

No you are right the close was unnecessary! Thanks for hinting.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/11730#-:-KYDvFoz8f5pkkqdP2ux:b-814cgt)*
