### PR TITLE
sql/gcjob: make index GC robust to descriptors being deleted

### LINKED ISSUE #86340: gcjob: index GC can retry perpetually when racing with table GC
**Describe the problem**

In 22.1, we added exponential backoff and indefinite retries to jobs which cannot be canceled or fail. If you were to say, drop and index or truncate a table and then drop the table, we can hit errors due to the table being dropped or the table which referenced that table being dropped.

The problem is that there's no proper error handling in the index code of the GC job to detect missing descriptors and bail out. The code also ends up validating cross-references when it retrieves the descriptor in question, which means that we can get errors if a referenced descriptor is dropped (however, if a referenced descriptor is dropped, so is this one).

We need to add code to handle missing descriptor and assume that it means that the data and zones are gone. 

Jira issue: CRDB-18704

### PR DESCRIPTION
**Pull request by ajwerner**
First commit is #86690

If the descriptor was deleted, the GC job should exit gracefully.

Fixes https://github.com/cockroachdb/cockroach/issues/86340

Release justification: bug fix for backport

Release note (bug fix): In some scenarios, when a DROP INDEX was
run around the same time as a DROP TABLE or DROP DATABASE covering the same
data, the `DROP INDEX` gc job could get caught retrying indefinitely. This
has been fixed.

### CODE REVIEW

File: pkg/sql/gcjob/index_garbage_collection.go [hunk 1]
```diff
@@ -40,10 +40,28 @@ func deleteIndexData(
...
+			)
+		}
+		return true
+	}
+
 	// Before deleting any indexes, ensure that old versions of the table descriptor
 	// are no longer in use. This is necessary in the case of truncate, where we
 	// schedule a GC Job in the transaction that commits the truncation.
 	parentDesc, err := sql.WaitToUpdateLeases(ctx, execCfg.LeaseManager, parentID)
+	if maybeHandleDeletedDescriptor(err) {
```
Comment (Xiang-Gu) [inline pkg/sql/gcjob/index_garbage_collection.go:62]: I feel like a eaiser to understand implementation is
```go
		if errors.Is(err, catalog.ErrDescriptorNotFound) {
		  // If the descriptor has been removed, then we need to assume that the relevant
		  // zone configs and data have been cleaned up by another process.
			handleDeletedDescriptor()
      return
		}
```
and accordingly, change the other function to
```go
	handleDeletedDescriptor := func() {
		log.Infof(ctx, "descriptor %d dropped, assuming another process has handled GC", parentID)
		for _, index := range droppedIndexes {
			markIndexGCed(
				ctx, index.IndexID, progress, jobspb.SchemaChangeGCProgress_CLEARED,
			)
		}
		return true
	}
```

But I don't really have a strong opinion on this; either way is perfectly fine with me.

File: pkg/sql/gcjob/index_garbage_collection.go [hunk 2]
```diff
@@ -84,11 +102,28 @@ func gcIndexes(
 	if log.V(2) {
 		log.Infof(ctx, "GC is being considered on table %d for indexes indexes: %+v", parentID, droppedIndexes)
 	}
+	maybeHandleDeletedDescriptor := func(err error) (done bool) {
```
Comment (Xiang-Gu) [inline pkg/sql/gcjob/index_garbage_collection.go:105]: reused so maybe considering make it a standalone function?

File: pkg/sql/gcjob_test/gc_job_test.go [hunk 3]
```diff
@@ -506,6 +508,54 @@ func TestGCTenant(t *testing.T) {
...
+	tdb.Exec(t, "DROP INDEX foo@foo_j_i_idx")
+	codec := s.ExecutorConfig().(sql.ExecutorConfig).Codec
+	errCh := make(chan error, 1)
+	// Allow the job to proceed in parallel to deleting the descriptor.
+	jobID := <-gcJobID
+	go func() {
+		k := catalogkeys.MakeDescMetadataKey(codec, tableID)
+		_, err := kvDB.Del(ctx, k)
+		errCh <- err
+	}()
```
Comment (Xiang-Gu) [inline pkg/sql/gcjob_test/gc_job_test.go:553]: Is the ordering of those two steps reversed?
The `DROP INDEX` stmt above will ensure we stall the index-gc job (due to the testing knob). We want to test the scenario where the the index-gc job failed to find the table descriptor, so shouldn't we drop the table first before we allow the index-gc job to proceed?

Comment (ajwerner) [reply pkg/sql/gcjob_test/gc_job_test.go:553]: There's no guarantee of ordering between the two. I don't think it changes the test to say `go` first, but I'll do it to clarify intention.

Comment (Xiang-Gu) [reply pkg/sql/gcjob_test/gc_job_test.go:553]: I still didn't understand this one: gcJobID is a 0-capacity channel. so `jobID := <- jcJobID` will unblock the `DROP INDEX` first and then we schedule a go routine that will delete the descriptor from `system.descriptor` table, which makes the `DROP INDEX` gc-job may or may not observe the deletion.

Shouldn't we make sure that we deleted the descriptor before we "let go" of the `DROP INDEX` index-gc job, which ensures that the gc-index job will observe the deletion?

Comment (ajwerner) [reply pkg/sql/gcjob_test/gc_job_test.go:553]: If this test were better, it'd intercept behavior of the gc job and delete the descriptor at specific moments, but I didn't feel that it was worth it, so I just ran the test on stress for a few minutes and called it a day.

**Comment by Xiang-Gu** [comment]
@ajwerner I didn't forget about this one; Let me know once you added more commentary on the test case, and I'll take a look again.

File: pkg/sql/gcjob_test/gc_job_test.go (hunk 3 above)
Comment (ajwerner) [reply pkg/sql/gcjob_test/gc_job_test.go]: I made the test better.

**Comment by ajwerner** [comment]
@Xiang-Gu I added more commentary, PTAL

File: pkg/sql/gcjob_test/gc_job_test.go [hunk 4]
```diff
@@ -506,6 +508,122 @@ func TestGCTenant(t *testing.T) {
...
+			},
+		}
+		delRangeChan := make(chan chan struct{})
+		var tablePrefix atomic.Value
+		tablePrefix.Store(roachpb.Key{})
+		// If not running beforeDelRange, we want to delete the descriptor during
+		// the DeleteRange operation. To do this, we install the below testing knob.
+		if !beforeDelRange {
+			knobs.Store = &kvserver.StoreTestingKnobs{
+				TestingRequestFilter: func(
```
Comment (Xiang-Gu) [inline pkg/sql/gcjob_test/gc_job_test.go:551]: When `beforeDelRange=false`, this knob is installed but this knob is called *before* evaluating the `deleteRange` request, which means we delete the descriptor *before* evaluating the `deleteRange`. This seems to not achieve what you said in the comment above "... descriptor being removed both before the initial DelRange, and *after*, when going to remove the zone config".

Comment (ajwerner) [reply pkg/sql/gcjob_test/gc_job_test.go:551]: Correct, it's before evaluating `DeleteRange`, but after the code which looked up the descriptor in order to build the `DeleteRange`.

Comment (Xiang-Gu) [reply pkg/sql/gcjob_test/gc_job_test.go:551]: Got ya, thanks for explaining, LGTM!

**Review by Xiang-Gu — APPROVED** [review]

**Comment by ajwerner** [comment]
TFTR!

bors r+
