### PR TITLE
kvserver: deflake `TestReplicaCircuitBreaker_ExemptRequests`

### LINKED ISSUE #112073: kvserver: TestReplicaCircuitBreaker_ExemptRequests failed
Seen on unrelated PR [here](https://teamcity.cockroachdb.com/viewLog.html?buildId=12119436&buildTypeId=Cockroach_BazelEssentialCi):
```
Failed
=== RUN   TestReplicaCircuitBreaker_ExemptRequests
    test_log_scope.go:170: test logs captured to: /artifacts/tmp/_tmp/54ddc9df1a6cbe399a248794e040aa3a/logTestReplicaCircuitBreaker_ExemptRequests3732845436
    test_log_scope.go:81: use -show-logs to present logs inline
    client_replica_circuit_breaker_test.go:1111: info:
             0.000ms      0.000ms    === operation:SendCtx(Put) _verbose:1
             0.000ms      0.000ms    [local proposal: {count: 1, duration 211µs}]
             0.066ms      0.066ms    event:kv/kvserver/replica_send.go:187 [n1,s1,r68/1:/{Table/Max-Max}] read-write path
             0.091ms      0.025ms    event:kv/kvserver/concurrency/concurrency_manager.go:209 [n1,s1,r68/1:/{Table/Max-Max}] sequencing request
             0.100ms      0.010ms    event:kv/kvserver/concurrency/concurrency_manager.go:290 [n1,s1,r68/1:/{Table/Max-Max}] acquiring latches
             0.116ms      0.016ms    event:kv/kvserver/concurrency/concurrency_manager.go:334 [n1,s1,r68/1:/{Table/Max-Max}] scanning lock table for conflicting locks
             0.146ms      0.030ms    event:kv/kvserver/replica_write.go:167 [n1,s1,r68/1:/{Table/Max-Max}] applied timestamp cache
             0.159ms      0.012ms    event:kv/kvserver/replica_write.go:411 [n1,s1,r68/1:/{Table/Max-Max}] executing read-write batch
             0.270ms      0.111ms    event:kv/kvserver/replica_evaluate.go:508 [n1,s1,r68/1:/{Table/Max-Max}] evaluated Put command header:<key:"\372" > value:<raw_bytes:"\224s\302\035\003hello-1" timestamp:<> > , txn=<nil> : resp=header:<> , err=<nil>
             0.324ms      0.055ms    event:kv/kvserver/replica_proposal.go:965 [n1,s1,r68/1:/{Table/Max-Max}] need consensus on write batch with op count=1
             0.346ms      0.022ms    event:kv/kvserver/replica_raft.go:125 [n1,s1,r68/1:/{Table/Max-Max}] evaluated request
             0.360ms      0.014ms    event:kv/kvserver/replica_raft.go:170 [n1,s1,r68/1:/{Table/Max-Max}] proposing command to write 1 new keys, 1 new values, 0 new intents, write batch size=47 bytes
             0.375ms      0.015ms    event:kv/kvserver/replica_raft.go:275 [n1,s1,r68/1:/{Table/Max-Max}] acquiring proposal quota (204 bytes)
             0.395ms      0.020ms    event:kv/kvserver/replica_raft.go:431 [n1,s1,r68/1:/{Table/Max-Max}] submitting proposal to proposal buffer
             0.461ms      0.066ms    event:kv/kvserver/replica_proposal_buf.go:601 [n1,s1,r68/1:/{Table/Max-Max}] flushing proposal to Raft
             0.877ms      0.415ms        === operation:local proposal _verbose:1 node:1 store:1 range:68/1:/{Table/Max-Max} raft:
             0.914ms      0.038ms        event:kv/kvserver/replica_application_cmd.go:148 [n1,s1,r68/1:/{Table/Max-Max},raft] ack-ing replication success to the client; application will continue async w.r.t. the client
             0.943ms      0.029ms        event:kv/kvserver/app_batch.go:121 [n1,s1,r68/1:/{Table/Max-Max},raft] applying command
             1.075ms      0.132ms        event:kv/kvserver/replica_application_state_machine.go:176 [n1,s1,r68/1:/{Table/Max-Max},raft] LocalResult (reply: (err: <nil>), *kvpb.PutResponse, #encountered intents: 0, #acquired locks: 0, #resolved locks: 0#updated txns: 0 #end txns: 0, GossipFirstRange:false MaybeGossipSystemConfig:false MaybeGossipSystemConfigIfHaveFailure:false MaybeAddToSplitQueue:false MaybeGossipNodeLiveness:<nil> 
    client_replica_circuit_breaker_test.go:1111: info:
             0.000ms      0.000ms    === operation:SendCtx(Put) _verbose:1
             0.033ms      0.033ms    event:kv/kvserver/replica_send.go:187 [n1,s1,r68/1:/{Table/Max-Max}] read-write path
             0.050ms      0.017ms    event:kv/kvserver/concurrency/concurrency_manager.go:209 [n1,s1,r68/1:/{Table/Max-Max}] sequencing request
             0.058ms      0.009ms    event:kv/kvserver/concurrency/concurrency_manager.go:290 [n1,s1,r68/1:/{Table/Max-Max}] acquiring latches
             0.071ms      0.013ms    event:kv/kvserver/concurrency/concurrency_manager.go:334 [n1,s1,r68/1:/{Table/Max-Max}] scanning lock table for conflicting locks
             0.120ms      0.049ms    event:kv/kvserver/replica_send.go:520 [n1,s1,r68/1:/{Table/Max-Max}] concurrency retry error: invalid lease
             0.309ms      0.189ms    event:kv/kvserver/replica_send.go:202 [n1,s1,r68/1:/{Table/Max-Max}] replica.Send got error: replica unavailable: (n1,s1):1 unable to serve request to r68:/{Table/Max-Max} [(n1,s1):1, (n2,s2):2, next=3, gen=3, sticky=9223372036.854775807,2147483647]: closed timestamp: 1696888041.170340926,0 (2023-10-09 21:47:21); raft status: {"id":"1","term":6,"vote":"1","commit":17,"lead":"1","raftState":"StateLeader","applied":17,"progress":{"1":{"match":17,"next":18,"state":"StateReplicate"},"2":{"match":17,"next":18,"state":"StateReplicate"}},"leadtransferee":"0"}: injected error
    client_replica_circuit_breaker_test.go:1111: info:
             0.000ms      0.000ms    === operation:SendCtx(Put) _verbose:1
             0.027ms      0.027ms    event:kv/kvserver/replica_send.go:187 [n1,s1,r68/1:/{Table/Max-Max}] read-write path
             0.047ms      0.020ms    event:kv/kvserver/concurrency/concurrency_manager.go:209 [n1,s1,r68/1:/{Table/Max-Max}] sequencing request
             0.055ms      0.008ms    event:kv/kvserver/concurrency/concurrency_manager.go:290 [n1,s1,r68/1:/{Table/Max-Max}] acquiring latches
             0.067ms      0.013ms    event:kv/kvserver/concurrency/concurrency_manager.go:334 [n1,s1,r68/1:/{Table/Max-Max}] scanning lock table for conflicting locks
             0.166ms      0.098ms    event:kv/kvserver/replica_send.go:520 [n1,s1,r68/1:/{Table/Max-Max}] concurrency retry error: invalid lease
             0.395ms      0.229ms    event:kv/kvserver/replica_send.go:202 [n1,s1,r68/1:/{Table/Max-Max}] replica.Send got error: replica unavailable: (n1,s1):1 unable to serve request to r68:/{Table/Max-Max} [(n1,s1):1, (n2,s2):2, next=3, gen=3, sticky=9223372036.854775807,2147483647]: closed timestamp: 1696888041.170340926,0 (2023-10-09 21:47:21); raft status: {"id":"1","term":6,"vote":"1","commit":17,"lead":"1","raftState":"StateLeader","applied":17,"progress":{"1":{"match":17,"next":18,"state":"StateReplicate"},"2":{"match":17,"next":18,"state":"StateReplicate"}},"leadtransferee":"0"}: injected error
    client_replica_circuit_breaker_test.go:1111: info:
             0.000ms      0.000ms    === operation:SendCtx(Put) _verbose:1
             0.028ms      0.028ms    event:kv/kvserver/replica_send.go:187 [n1,s1,r68/1:/{Table/Max-Max}] read-write path
             0.043ms      0.015ms    event:kv/kvserver/concurrency/concurrency_manager.go:209 [n1,s1,r68/1:/{Table/Max-Max}] sequencing request
             0.054ms      0.011ms    event:kv/kvserver/concurrency/concurrency_manager.go:290 [n1,s1,r68/1:/{Table/Max-Max}] acquiring latches
             0.066ms      0.013ms    event:kv/kvserver/concurrency/concurrency_manager.go:334 [n1,s1,r68/1:/{Table/Max-Max}] scanning lock table for conflicting locks
             0.099ms      0.032ms    event:kv/kvserver/replica_send.go:520 [n1,s1,r68/1:/{Table/Max-Max}] concurrency retry error: invalid lease
             0.216ms      0.117ms    event:kv/kvserver/replica_send.go:202 [n1,s1,r68/1:/{Table/Max-Max}] replica.Send got error: replica unavailable: (n1,s1):1 unable to serve request to r68:/{Table/Max-Max} [(n1,s1):1, (n2,s2):2, next=3, gen=3, sticky=9223372036.854775807,2147483647]: closed timestamp: 1696888041.170340926,0 (2023-10-09 21:47:21); raft status: {"id":"1","term":6,"vote":"1","commit":17,"lead":"1","raftState":"StateLeader","applied":17,"progress":{"1":{"match":17,"next":18,"state":"StateReplicate"},"2":{"match":17,"next":18,"state":"StateReplicate"}},"leadtransferee":"0"}: injected error
    client_replica_circuit_breaker_test.go:1111: info:
             0.000ms      0.000ms    === operation:SendCtx(Put) _verbose:1
             0.000ms      0.000ms    [local proposal: {count: 1, duration 101µs}]
             0.227ms      0.227ms    event:kv/kvserver/replica_send.go:187 [n1,s1,r68/1:/{Table/Max-Max}] read-write path
             0.262ms      0.035ms    event:kv/kvserver/concurrency/concurrency_manager.go:209 [n1,s1,r68/1:/{Table/Max-Max}] sequencing request
             0.272ms      0.010ms    event:kv/kvserver/concurrency/concurrency_manager.go:290 [n1,s1,r68/1:/{Table/Max-Max}] acquiring latches
             0.290ms      0.018ms    event:kv/kvserver/concurrency/concurrency_manager.go:334 [n1,s1,r68/1:/{Table/Max-Max}] scanning lock table for conflicting locks
             0.348ms      0.058ms    event:kv/kvserver/replica_send.go:520 [n1,s1,r68/1:/{Table/Max-Max}] concurrency retry error: invalid lease
             0.375ms      0.027ms    event:kv/kvserver/replica_range_lease.go:1336 [n1,s1,r68/1:/{Table/Max-Max}] request range lease (attempt #1)
             1.430ms      1.055ms    event:kv/kvserver/replica_range_lease.go:1426 [n1,s1,r68/1:/{Table/Max-Max}] lease acquisition succeeded: <empty>
             1.480ms      0.050ms    event:kv/kvserver/replica_range_lease.go:1360 [n1,s1,r68/1:/{Table/Max-Max}] valid lease {Lease:repl=(n1,s1):1 seq=7 start=0,0 epo=8 pro=1696888084.710998414,0 Now:1696888084.736863863,0 RequestTime:1696888084.735430133,0 State:VALID ErrInfo: Liveness:liveness(nid:1 epo:8 exp:1696888090.733950793,0) MinValidObservedTimestamp:0,0}
             1.491ms      0.011ms    event:kv/kvserver/concurrency/concurrency_manager.go:209 [n1,s1,r68/1:/{Table/Max-Max}] sequencing request
             1.499ms      0.008ms    event:kv/kvserver/concurrency/concurrency_manager.go:290 [n1,s1,r68/1:/{Table/Max-Max}] acquiring latches
             1.512ms      0.013ms    event:kv/kvserver/concurrency/concurrency_manager.go:334 [n1,s1,r68/1:/{Table/Max-Max}] scanning lock table for conflicting locks
             1.530ms      0.018ms    event:kv/kvserver/replica_write.go:167 [n1,s1,r68/1:/{Table/Max-Max}] applied timestamp cache
             1.541ms      0.011ms    event:kv/kvserver/replica_write.go:411 [n1,s1,r68/1:/{Table/Max-Max}] executing read-write batch
             1.610ms      0.069ms    event:kv/kvserver/replica_evaluate.go:508 [n1,s1,r68/1:/{Table/Max-Max}] evaluated Put command header:<key:"\372" > value:<raw_bytes:"\223\036\006\004\003hello-5" timestamp:<> > , txn=<nil> : resp=header:<> , err=<nil>
             1.623ms      0.013ms    event:kv/kvserver/replica_proposal.go:965 [n1,s1,r68/1:/{Table/Max-Max}] need consensus on write batch with op count=1
             1.642ms      0.018ms    event:kv/kvserver/replica_raft.go:125 [n1,s1,r68/1:/{Table/Max-Max}] evaluated request
             1.654ms      0.012ms    event:kv/kvserver/replica_raft.go:170 [n1,s1,r68/1:/{Table/Max-Max}] proposing command to write 1 new keys, 1 new values, 0 new intents, write batch size=47 bytes
             1.666ms      0.012ms    event:kv/kvserver/replica_raft.go:275 [n1,s1,r68/1:/{Table/Max-Max}] acquiring proposal quota (204 bytes)
             1.681ms      0.015ms    event:kv/kvserver/replica_raft.go:431 [n1,s1,r68/1:/{Table/Max-Max}] submitting proposal to proposal buffer
             1.703ms      0.022ms    event:kv/kvserver/replica_proposal_buf.go:601 [n1,s1,r68/1:/{Table/Max-Max}] flushing proposal to Raft
             2.233ms      0.530ms        === operation:local proposal _verbose:1 node:1 store:1 range:68/1:/{Table/Max-Max} raft:
             2.257ms      0.024ms        event:kv/kvserver/replica_application_cmd.go:148 [n1,s1,r68/1:/{Table/Max-Max},raft] ack-ing replication success to the client; application will continue async w.r.t. the client
             2.281ms      0.024ms        event:kv/kvserver/app_batch.go:121 [n1,s1,r68/1:/{Table/Max-Max},raft] applying command
             2.326ms      0.044ms        event:kv/kvserver/replica_application_state_machine.go:176 [n1,s1,r68/1:/{Table/Max-Max},raft] LocalResult (reply: (err: <nil>), *kvpb.PutResponse, #encountered intents: 0, #acquired locks: 0, #resolved locks: 0#updated txns: 0 #end txns: 0, GossipFirstRange:false MaybeGossipSystemConfig:false MaybeGossipSystemConfigIfHaveFailure:false MaybeAddToSplitQueue:false MaybeGossipNodeLiveness:<nil> 
    replica_raft.go:1343: 2 Gc: using slow replication threshold 10ms
    replica_raft.go:1343: 1 Probe: using slow replication threshold 10ms
    client_replica_circuit_breaker_test.go:1111: info:
             0.000ms      0.000ms    === operation:SendCtx(Put) _verbose:1
             0.063ms      0.063ms    event:kv/kvserver/replica_send.go:187 [n1,s1,r68/1:/{Table/Max-Max}] read-write path
             0.086ms      0.023ms    event:kv/kvserver/concurrency/concurrency_manager.go:209 [n1,s1,r68/1:/{Table/Max-Max}] sequencing request
             0.096ms      0.010ms    event:kv/kvserver/concurrency/concurrency_manager.go:290 [n1,s1,r68/1:/{Table/Max-Max}] acquiring latches
             0.110ms      0.014ms    event:kv/kvserver/concurrency/concurrency_manager.go:334 [n1,s1,r68/1:/{Table/Max-Max}] scanning lock table for conflicting locks
             0.339ms      0.229ms    event:kv/kvserver/replica_send.go:202 [n1,s1,r68/1:/{Table/Max-Max}] replica.Send got error: replica unavailable: (n1,s1):1 unable to serve request to r68:/{Table/Max-Max} [(n1,s1):1, (n2,s2):2, next=3, gen=3, sticky=9223372036.854775807,2147483647]: lost quorum (down: (n2,s2):2); closed timestamp: 1696888082.495749397,0 (2023-10-09 21:48:02); raft status: {"id":"1","term":6,"vote":"1","commit":31,"lead":"0","raftState":"StateFollower","applied":31,"progress":{},"leadtransferee":"0"}: have been waiting 1.00s for slow proposal GC [/Table/Max,"\xfa\x00"), GC [/Table/Max,"\xfa\x00")
    client_replica_circuit_breaker_test.go:686: replica unavailable: (n1,s1):1 unable to serve request to r68:/{Table/Max-Max} [(n1,s1):1, (n2,s2):2, next=3, gen=3, sticky=9223372036.854775807,2147483647]: lost quorum (down: (n2,s2):2); closed timestamp: 1696888082.495749397,0 (2023-10-09 21:48:02); raft status: {"id":"1","term":6,"vote":"1","commit":31,"lead":"0","raftState":"StateFollower","applied":31,"progress":{},"leadtransferee":"0"}: have been waiting 1.00s for slow proposal GC [/Table/Max,"\xfa\x00"), GC [/Table/Max,"\xfa\x00")
    client_replica_circuit_breaker_test.go:1111: info:
             0.000ms      0.000ms    === operation:SendCtx(Get) _verbose:1
             0.024ms      0.024ms    event:kv/kvserver/replica_send.go:183 [n1,s1,r68/1:/{Table/Max-Max}] read-only path
             0.037ms      0.013ms    event:kv/kvserver/concurrency/concurrency_manager.go:209 [n1,s1,r68/1:/{Table/Max-Max}] sequencing request
             0.045ms      0.008ms    event:kv/kvserver/concurrency/concurrency_manager.go:290 [n1,s1,r68/1:/{Table/Max-Max}] acquiring latches
             0.057ms      0.012ms    event:kv/kvserver/concurrency/concurrency_manager.go:334 [n1,s1,r68/1:/{Table/Max-Max}] scanning lock table for conflicting locks
             0.108ms      0.051ms    event:kv/kvserver/replica_read.go:302 [n1,s1,r68/1:/{Table/Max-Max}] can drop latches early for batch (Get [/Table/Max,/Min)); scanning lock table first to detect conflicts
             0.148ms      0.040ms    event:kv/kvserver/replica_read.go:114 [n1,s1,r68/1:/{Table/Max-Max}] lock table scan complete without conflicts; dropping latches early
             0.165ms      0.017ms    event:kv/kvserver/replica_read.go:414 [n1,s1,r68/1:/{Table/Max-Max}] executing read-only batch
             0.254ms      0.089ms    event:kv/kvserver/replica_evaluate.go:508 [n1,s1,r68/1:/{Table/Max-Max}] evaluated Get command header:<key:"\372" > , txn=<nil> : resp=header:<num_keys:1 num_bytes:12 > value:<raw_bytes:"\223\036\006\004\003hello-5" timestamp:<wall_time:1696888084735430133 > > , err=<nil>
             0.280ms      0.026ms    event:scan stats: stepped 0 times (0 internal); seeked 1 times (1 internal); block-bytes: (total 0 B, cached 0 B); points: (count 1, key-bytes 11 B, value-bytes 19 B, tombstoned: 0) ranges: (count 0), (contained-points 0, skipped-points 0) evaluated requests: 1 gets, 0 scans, 0 reverse scans
             0.296ms      0.016ms    event:kv/kvserver/replica_read.go:227 [n1,s1,r68/1:/{Table/Max-Max}] read completed
             0.260ms     -0.037ms    structured:{"@type":"type.googleapis.com/cockroach.roachpb.ScanStats","numInterfaceSeeks":"1","numInternalSeeks":"1","numInterfaceSteps":"0","numInternalSteps":"0","blockBytes":"0","blockBytesInCache":"0","keyBytes":"11","valueBytes":"19","pointCount":"1","pointsCoveredByRangeTombstones":"0","rangeKeyCount":"0","rangeKeyContainedPoints":"0","rangeKeySkippedPoints":"0","separatedPointCount":"0","separatedPointValueBytes":"0","separatedPointValueBytesFetched":"0","numGets":"1","numScans":"0","numReverseScans":"0"}
    client_replica_circuit_breaker_test.go:687: <nil>
    client_replica_circuit_breaker_test.go:687: 
        	Error Trace:	github.com/cockroachdb/cockroach/pkg/kv/kvserver_test/pkg/kv/kvserver/client_replica_circuit_breaker_test.go:1042
        	            				github.com/cockroachdb/cockroach/pkg/kv/kvserver_test/pkg/kv/kvserver/client_replica_circuit_breaker_test.go:687
        	Error:      	Should be true
        	Test:       	TestReplicaCircuitBreaker_ExemptRequests
        	Messages:   	<nil>
    panic.go:522: -- test log scope end --
```

Jira issue: CRDB-32224

### PR DESCRIPTION
**Pull request by erikgrinaker**
**kvserver: add `Replica.NumPendingProposals()` test helper**

**kvserver: deflake `TestReplicaCircuitBreaker_ExemptRequests`**

It was possible for a reproposal from a previous subtest to cause the circuit breaker to trip again when remove quorum. This would violate assertions that were expecting a different command to fail.

This patch waits for all pending proposals to complete before tripping the circuit breaker again.

Resolves #112073.
Epic: none
Release note: None

### CODE REVIEW

File: pkg/kv/kvserver/client_replica_circuit_breaker_test.go [hunk 1]
```diff
@@ -886,6 +888,19 @@ func (cbt *circuitBreakerTest) UntripsSoon(t *testing.T, method func(idx int) er
 	})
 }
 
+func (cbt *circuitBreakerTest) WaitForProposals(t *testing.T, idx int) {
+	t.Helper()
+	testutils.SucceedsSoon(t, func() error {
+		t.Helper()
+
+		repl := cbt.repls[idx].Replica
+		if n := repl.NumPendingProposals(); n > 0 {
```
Comment (pavelkalinnikov) [inline pkg/kv/kvserver/client_replica_circuit_breaker_test.go:897]: I wonder if this can flap between 0 and non-0 for a bit. Depends on whether the sum of reproposals map size and propbuf size that `NumPendingProposals` returns is "exhaustive", i.e. there are no sneaky (re-)proposals in some transition state that is neither in the map nor in the buffer.

Don't need to spend a ton of time figuring this out now though.

**Review by pav-kv — APPROVED** [review]

File: pkg/kv/kvserver/client_replica_circuit_breaker_test.go (hunk 1 above)
Comment (erikgrinaker) [reply pkg/kv/kvserver/client_replica_circuit_breaker_test.go:897]: We're holding the replica mutex across these, so I think they should be in sync.

Comment (pavelkalinnikov) [reply pkg/kv/kvserver/client_replica_circuit_breaker_test.go:897]: I mean "transitions" in between holding mutexes. I.e. does the invariant "all possible (re-)proposals are either in proposals map or in proposals buffer" hold any time we grab replica mu? I vaguely remember there were cases when we delete and reinsert things in the map.

Comment (erikgrinaker) [reply pkg/kv/kvserver/client_replica_circuit_breaker_test.go:897]: >I vaguely remember there were cases when we delete and reinsert things in the map.

I believe those cases happen under lock.
