### PR TITLE
roachtest: disable mutators in backup-restore/mixed-version

### LINKED ISSUE #126189: roachtest: backup-restore/mixed-version failed
roachtest.backup-restore/mixed-version [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/15811817?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/15811817?buildTab=artifacts#/backup-restore/mixed-version) on release-24.1 @ [169ec5c438584975b3b0cd1dd9038f3ef5703477](https://github.com/cockroachdb/cockroach/commits/169ec5c438584975b3b0cd1dd9038f3ef5703477):

```
(mixedversion.go:620).Run: mixed-version test failure while running step 62 (reset cluster setting "storage.sstable.compression_algorithm" on system tenant): pq: unknown cluster setting 'storage.sstable.compression_algorithm'
test artifacts and logs in: /artifacts/backup-restore/mixed-version/run_1
```

Parameters:
 - <code>ROACHTEST_arch=amd64</code>
 - <code>ROACHTEST_cloud=gce</code>
 - <code>ROACHTEST_coverageBuild=false</code>
 - <code>ROACHTEST_cpu=4</code>
 - <code>ROACHTEST_encrypted=false</code>
 - <code>ROACHTEST_metamorphicBuild=false</code>
 - <code>ROACHTEST_ssd=0</code>
<details><summary>Help</summary>
<p>

See: [roachtest README](https://github.com/cockroachdb/cockroach/blob/master/pkg/cmd/roachtest/README.md)

See: [How To Investigate \(internal\)](https://cockroachlabs.atlassian.net/l/c/SSSBr8c7)

See: [Grafana](https://go.crdb.dev/roachtest-grafana/teamcity-15811817/backup-restore-mixed-version/1719303180430/1719307938177)

</p>
</details>
<details><summary>Same failure on other branches</summary>
<p>

- #125677 roachtest: backup-restore/mixed-version failed [C-test-failure O-roachtest O-robot T-disaster-recovery branch-release-23.1 release-blocker]
</p>
</details>
/cc @cockroachdb/disaster-recovery
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*backup-restore/mixed-version.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/bazci/githubpost/issues)
</sub>

Jira issue: CRDB-39794

### PR DESCRIPTION
**Pull request by renatolabs**
It should eventually be re-enabled if/when we add support for mutual exclusion in the mixed-version framework.

Fixes: #126189

Release note: None

### CODE REVIEW

**Review by DarrylWong — APPROVED** [review]

File: pkg/cmd/roachtest/tests/mixed_version_backup.go [hunk 1]
```diff
@@ -2565,6 +2565,20 @@ func registerBackupMixedVersion(r registry.Registry) {
...
+				// We disable cluster setting mutators because this test
+				// resets the cluster to older versions when verifying cluster
+				// backups. This makes the mixed-version context inaccurate
+				// and leads to flakes.
+				//
+				// TODO(renato): don't disable these mutators when the
+				// framework exposes some utility to provide mutual exclusion
+				// of concurrent steps.
+				mixedversion.DisableMutators(
+					mixedversion.ClusterSettingMutator("kv.expiration_elases_only.enabled"),
```
Comment (renatolabs) [inline pkg/cmd/roachtest/tests/mixed_version_backup.go:2577]: 👀

**Comment by renatolabs** [comment]
TFTR!

bors r=DarrylWong
