### PR TITLE
metric: Report aggregate metric when no child metrics are present

### LINKED ISSUE #149481: metric: when `server.child_metrics.include_aggregate.enabled` is set to `false` some SQL metrics fail to export
## Reproduction

Setting `server.child_metrics.include_aggregate.enabled` to `false` and `server.child_metrics.enabled` to `true` will eliminate certain "non-child" metrics like `sql_insert_count` from the output in the `/_status/vars` scrape endpoint.

## Background

This bug is the result of two unrelated changes to the metrics subsystem interacting in an unexpected way.

We recently added support for per-app and per-database metrics for some of our SQL metrics. This is done by treating metrics that were previously "single-counter" metrics into aggregate metrics which conditionally output either a single value or many values depending on the `sql.metrics.application_name.enabled` and `sql.metrics.database_name.enabled` cluster settings.

The implementation of the `server.child_metrics.include_aggregate.enabled` cluster setting assumes that all aggregate metrics will have their children emitted if the aggregate is disabled.

## Solution

We should ensure that when `server.child_metrics.include_aggregate.enabled` is set to `false` that it only takes effect on actual child metrics, and not the more recently introduced "sql aggregate" metrics.

Jira issue: CRDB-52149

### PR DESCRIPTION
**Pull request by alyshanjahani-crl**
SQLMetrics are PrometheusIterable, they are the first and only instance of metrics that dynamically add and remove childset metrics.

This commit fixes a bug where the includeAggregate flag being false (cluster setting disabled) resulting in these SQLMetrics not being reported.

When a PrometheusIterable has no child metrics it should report the aggregate regardless of the cluster setting.

Fixes: #149481

Release note (bug fix): When child metrics are enabled, include_aggregate is disabled, and the sql.metric.application_name/database_name are disabled, a handful of `sql` metrics were not being reported.

### CODE REVIEW

**Review by aa-joshi — APPROVED** [review]
@alyshanjahani-crl Thanks for the quick turn around! One suggestion. Overall approach 
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/149540#-:-OUce8v289G0IkuxuIds:b-gyz8sw)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @Abhinav1299, @arjunmahishi, and @dhartunian)

___
*[`pkg/util/metric/prometheus_exporter.go` line 153 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/149540#-OUcdp33-qqB0Mxk-Y80:-OUcdp33-qqB0Mxk-Y81:b-9e5zi3) ([raw file](https://github.com/cockroachdb/cockroach/blob/d64149df95027a05d7c1a69107c0c40d5f827aa7/pkg/util/metric/prometheus_exporter.go#L153)):*
> ```Go
> 					family.Metric = append(family.Metric, m)
> 				}
> 				numChildren := 0
> ```

I would suggest to extract the custom handling of SQLMetric in `PrometheusReinitialisable`.



_Code snippet:_
```Go
		case PrometheusReinitialisable:
			m := prom.ToPrometheusMetric()
			// Set registry and metric labels.
			m.Label = append(labels, prom.GetLabels(o.useStaticLabels)...)
			family := pm.findOrCreateFamily(prom, o)

			if o.includeAggregateMetrics {
				family.Metric = append(family.Metric, m)
			}

			numChildren := 0
			if o.includeChildMetrics {
				prom.Each(m.Label, func(metric *prometheusgo.Metric) {
					family.Metric = append(family.Metric, metric)
					numChildren += 1
				})
			}

			// If no child metrics are present we want to ensure
			// we report the aggregate regardless of the respective cluster setting.
			if numChildren == 0 && !o.includeAggregateMetrics {
				family.Metric = append(family.Metric, m)
			}
			return
```

**Review by aa-joshi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/149540)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @Abhinav1299, @alyshanjahani-crl, @arjunmahishi, and @dhartunian)

___
*[`pkg/util/metric/prometheus_exporter.go` line 153 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/149540#-OUcdp33-qqB0Mxk-Y80:-OUeNnH_32PCtoG6ylfN:b-x7h0b3) ([raw file](https://github.com/cockroachdb/cockroach/blob/d64149df95027a05d7c1a69107c0c40d5f827aa7/pkg/util/metric/prometheus_exporter.go#L153)):*
<details><summary><i>Previously, aa-joshi (Akshay Joshi) wrote…</i></summary><blockquote>

I would suggest to extract the custom handling of SQLMetric in `PrometheusReinitialisable`.
</blockquote></details>

This should be present before `PrometheusExportable`. This is because `PrometheusReinitialisable` extends `PrometheusExportable`

**Review by alyshanjahani-crl — COMMENTED** [review]
Moved logic to `case PrometheusReinitialisable`.

TFTR!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/149540#-:-OUebv8DCIOFu8452dGw:b-lvmjr)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @aa-joshi, @Abhinav1299, @arjunmahishi, and @dhartunian)

___
*[`pkg/util/metric/prometheus_exporter.go` line 153 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/149540#-OUcdp33-qqB0Mxk-Y80:-OUec7G0-7H__lAIu2Hn:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/d64149df95027a05d7c1a69107c0c40d5f827aa7/pkg/util/metric/prometheus_exporter.go#L153)):*
<details><summary><i>Previously, aa-joshi (Akshay Joshi) wrote…</i></summary><blockquote>

This should be present before `PrometheusExportable`. This is because `PrometheusReinitialisable` extends `PrometheusExportable`
</blockquote></details>

Done.

**Review by aa-joshi — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/149540#-:-OUj15ZL270EuB8qq-__:bnfp4nl)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @Abhinav1299, @arjunmahishi, and @dhartunian)

**Review by aa-joshi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 2 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/149540#-:-OUj1FuY6wAhcZZFPmT4:bnfp4nl)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @Abhinav1299, @arjunmahishi, and @dhartunian)

**Comment by alyshanjahani-crl** [comment]
bors cancel

**Comment by alyshanjahani-crl** [comment]
> I would suggest to extract the custom handling of SQLMetric in PrometheusReinitialisable.

I think in conjunction w/ the backport requirements (needing to introduce the additional cluster setting) this ended up making the diff bigger than i'd like...

For now, i've extracted the code that was handling the `PrometheusExportable` case, so when the backport cluster setting is disabled, the reinitialisable metrics get treated as they were before (i.e. as `PrometheusExportable`). I thought we could just use some kind switch control (`fallthrough`) but that isn't allowed for type cast switch statements :( 

When the backport cluster setting is enabled, the reinitialisable metrics get treated in their own way.

I made the tests work with the backport cluster setting enabled and disabled.

Except for the specific test for reinitialisable metrics which needs the setting enabled.

Lmk what y'all think. I can go back to the original diff where we only make changes to the `case PrometheusExportable` (and don't introduce a `case PrometheusReinitialisable`), with the addition of the backport cluster setting it would look like:

```
		case PrometheusExportable:
			m := prom.ToPrometheusMetric()
			// Set registry and metric labels.
			m.Label = append(labels, prom.GetLabels(o.useStaticLabels)...)
			family := pm.findOrCreateFamily(prom, o)

			// Based on cluster settings may report just the parent, or just the children, or the parent
			// and the children.
			promIter, ok := v.(PrometheusIterable)
			if ok && o.includeChildMetrics {
				if o.includeAggregateMetrics {
					family.Metric = append(family.Metric, m)
				}
				numChildren := 0
				promIter.Each(m.Label, func(metric *prometheusgo.Metric) {
					family.Metric = append(family.Metric, metric)
					numChildren += 1
				})


                                 if o.reinitialisableBugFixEnabled {
				    // Certain PrometheusReinitialisable metrics (like SQLMetric) dynamically
				    // add child metrics. If no child metrics are present we want to ensure
				    // we report the aggregate regardless of the respective cluster setting.
				    if !o.includeAggregateMetrics && numChildren == 0 {
					    family.Metric = append(family.Metric, m)
				    }
                                 }

				return
			}

			// No child metrics.
			family.Metric = append(family.Metric, m)

```

File: pkg/util/metric/prometheus_exporter.go [hunk 1]
```diff
@@ -137,27 +169,39 @@ func (pm *PrometheusExporter) ScrapeRegistry(registry *Registry, options ...Scra
...
-			m := prom.ToPrometheusMetric()
-			// Set registry and metric labels.
-			m.Label = append(labels, prom.GetLabels(o.useStaticLabels)...)
-			family := pm.findOrCreateFamily(prom, o)
-
-			// Based on cluster settings may report just the parent, or just the children, or the parent
-			// and the children.
-			promIter, ok := v.(PrometheusIterable)
-			if ok && o.includeChildMetrics {
+		case PrometheusReinitialisable:
```
Comment (dhartunian) [inline pkg/util/metric/prometheus_exporter.go]: I'd like to leave the `PrometheusExportable` case untouched because this change now modifies that code in a way that we can't "disable" with the setting.

Here's what I think is a reasonable solution here:

```
switch prom := v.(type) {
case PrometheusVector:
  etc...
case PrometheusExportable:
  if reinitV, ok := v.(PrometheusReinitializable); ok && bugfixSettingEnabled {
    <NEW CODE HERE>
    continue
  }
  <OLD CODE HERE UNCHANGED>
default:
  etc...
```

Comment (alyshanjahani-crl) [reply pkg/util/metric/prometheus_exporter.go]: Oh nice that is clean. Done.

PTAL

**Review by dhartunian — APPROVED** [review]
LGTM! Thanks
