### PR TITLE
roachtest/mixedversion: allow registering hooks during cluster startup

### LINKED ISSUE #138750: roachtest/mixedversion: support registering hooks run before cluster is initialized
Recently, [one mixed version test](https://github.com/cockroachdb/cockroach/pull/138343#discussion_r1907534245) has been added, requiring a user hook to run before the cluster has been initialized. The test wants to send authenticated HTTP requests to the server as the cluster is starting, in order to test for a regression where doing so would make the entire server crash. 

However, since the earliest a user hook can be registered is after the cluster has been started, the test registers its user hooks under `BackgroundFunc` which essentially misses out on testing the very first version. 

<pre>
Seed:               8448737306363800971
Upgrades:           v24.3.2 → <current>
Deployment mode:    system-only
Mutators:           cluster_setting[storage.ingest_split.enabled], cluster_setting[kv.snapshot_receiver.excise.enabled]
Plan:
├── start cluster at version "v24.3.2" (1)  <b><--Hooks should ideally run while this is happening</b>
├── wait for all nodes (:1-4) to acknowledge cluster version '24.3' on system tenant (2)
├── start background hooks concurrently
│   ├── set cluster setting "kv.snapshot_receiver.excise.enabled" to 'true' on system tenant, after 500ms delay (3)
│   ├── run "HTTP requests to system tenant", after 500ms delay (4) <b><--When BackgroundFunc hooks run</b>
│   ├── run "HTTP requests to secondary tenant", after 3s delay (5)
│   ├── run "HTTP requests to system tenant", after 500ms delay (6)
│   ├── run "HTTP requests to secondary tenant", after 500ms delay (7)
│   ├── run "HTTP requests to system tenant", after 3s delay (8)
│   ├── set cluster setting "storage.ingest_split.enabled" to 'true' on system tenant, after 0s delay (9)
│   ├── run "HTTP requests to secondary tenant", after 0s delay (10)
│   ├── run "HTTP requests to system tenant", after 10ms delay (11)
│   ├── reset cluster setting "kv.snapshot_receiver.excise.enabled" on system tenant, after 10ms delay (12)
│   ├── reset cluster setting "storage.ingest_split.enabled" on system tenant, after 10ms delay (13)
│   └── run "HTTP requests to secondary tenant", after 3s delay (14)
└── upgrade cluster from "v24.3.2" to "<current>"  <b><--Regression isn't actually tested for until now</b>
</pre>

The mixed version framework should allow for registering hooks before the cluster has started.

------

Note that for most use cases of this feature, including the one described, any meaningful work done on the cluster requires knowledge of connection info (SQL/Admin ports). However, `SyncedCluster.Start` handles both service registration of the ports and starting the CRDB cluster:

https://github.com/cockroachdb/cockroach/blob/ed0921560edf62dbc767c5bf3ffaa8ad1bc78e12/pkg/roachprod/install/cockroach.go#L401-L406

https://github.com/cockroachdb/cockroach/blob/ed0921560edf62dbc767c5bf3ffaa8ad1bc78e12/pkg/roachprod/install/cockroach.go#L450-L468

User hooks cannot run before `SyncedCluster.Start` as connection info is unknown, but waiting until after means the cluster has already started. To workaround this, an API should be implemented that will run a registered callback hook after service registration has happened but before the cluster starts. For example:

```
// In a roachtest
portsRegistered := make(chan struct{})

t.Go(func(context.Context, *logger.Logger) error { 
<-portsRegistered
return foobar()
})

c.Start(ctx, t.L(), startOpts, install.MakeClusterSettings(), c.All(), option.AfterServiceRegistration(func() {
   close(portsRegistered)
}))
```

Jira issue: CRDB-46329

### PR DESCRIPTION
**Pull request by DarrylWong**
Occasionally, a roachtest will want to run some code between two steps normally orchestrated by the roachtest framework, e.g. after service registration so we know connection info but before cockroach init. This change introduces a cluster hook API which allow roachtests to run code at points normally outside of their scope of control

Additionally, mixed version tests can now register hooks that will be run concurrently with cluster startup. 

With the above two changes, the http-register-routes test has been modified so it will make http requests the first time the cluster is started. Previously, it would not be able to do so until the first upgrade, missing out on an entire upgrade worth of coverage.

Fixes: https://github.com/cockroachdb/cockroach/issues/138750

----

We will most likely have to set the min version for `http-register-routes` to 24.2 to stop the test failures it's seeing, so getting this extra coverage is nice. My actual motivation for this change though is that I ran into another use case that wants this. When playing around with the idea of metamorphically simulating MR clusters, I realized it also wants to be run right after service registration so it knows connection info to construct the `tc` rules but before the cluster actually starts.

### CODE REVIEW

File: pkg/cmd/roachtest/roachtestutil/mixedversion/planner.go [hunk 1]
```diff
@@ -557,14 +557,27 @@ func (p *testPlanner) systemSetupSteps() []testStep {
...
+			startStep{
+				version:            initialVersion,
+				rt:                 p.rt,
+				initTarget:         p.currentContext.System.Descriptor.Nodes[0],
+				waitForReplication: p.shouldWaitForReplication(),
+				settings:           p.clusterSettingsForSystem(initialVersion),
+			}),
+	)
+
+	steps = append(steps, p.concurrently(clusterInitLabel, clusterStartSteps)...)
```
Comment (srosenberg) [inline pkg/cmd/roachtest/roachtestutil/mixedversion/planner.go:579]: `p.concurrently` will break the "happens before" ordering wrt clusterInitHooks.

File: pkg/cmd/roachtest/roachtestutil/mixedversion/planner.go [hunk 2]
```diff
@@ -597,20 +611,26 @@ func (p *testPlanner) tenantSetupSteps(v *clusterupgrade.Version) []testStep {
 			settings: p.clusterSettingsForTenant(v),
 		}
 	}
+	var clusterStartSteps []testStep
+	clusterInitHooks := p.hooks.ClusterInitSteps(setupContext, p.prng)
+	if len(clusterInitHooks) > 0 {
+		clusterStartSteps = append(clusterStartSteps, clusterInitHooks...)
+	}
+	clusterStartSteps = append(clusterStartSteps, p.newSingleStepWithContext(setupContext, startStep))
+	steps = append(steps, p.concurrently(clusterInitLabel, clusterStartSteps)...)
```
Comment (srosenberg) [inline pkg/cmd/roachtest/roachtestutil/mixedversion/planner.go:620]: Same as above.

File: pkg/cmd/roachtest/roachtestutil/mixedversion/mixedversion.go [hunk 3]
```diff
@@ -696,6 +698,18 @@ func (t *Test) InMixedVersion(desc string, fn stepFunc) {
 	t.hooks.AddMixedVersion(versionUpgradeHook{name: desc, predicate: predicate, fn: fn})
 }
 
+// InClusterInit registers a callback that is run during cluster
```
Comment (srosenberg) [inline pkg/cmd/roachtest/roachtestutil/mixedversion/mixedversion.go:701]: The hooks will be run concurrently but before any of the framework ones?

Comment (srosenberg) [reply pkg/cmd/roachtest/roachtestutil/mixedversion/mixedversion.go:701]: Actually, no, hooks are run sequentially, in the order, specified.

File: pkg/roachprod/install/cockroach.go [hunk 4]
```diff
@@ -434,6 +438,16 @@ func (c *SyncedCluster) Start(ctx context.Context, l *logger.Logger, startOpts S
 		startOpts.AdminUIPort = config.DefaultAdminUIPort
 	}
 
+	for _, hook := range startOpts.PreStartHooks {
+		if hook.Fn == nil {
```
Comment (srosenberg) [inline pkg/roachprod/install/cockroach.go:442]: We have to be careful in case of (user) `panic`. The mixedversion framework does it via `panicAsError`.

File: pkg/roachprod/install/cockroach.go [hunk 5]
```diff
@@ -434,6 +438,16 @@ func (c *SyncedCluster) Start(ctx context.Context, l *logger.Logger, startOpts S
...
+			continue
+		}
+		l.Printf("running pre-start hook: %s", hook.Name)
+		if err := hook.Fn(ctx); err != nil {
```
Comment (srosenberg) [inline pkg/roachprod/install/cockroach.go:446]: We have to be careful in case of (user) panic. The mixedversion framework does it via panicAsError.

Comment (srosenberg) [reply pkg/roachprod/install/cockroach.go:446]: Technically, we should also impose a maximum running time for each hook, but seems fine for the first iteration.

File: pkg/roachprod/install/cockroach.go [hunk 6]
```diff
@@ -1671,3 +1685,10 @@ func getEnvVars() []string {
 func SuppressMetamorphicConstantsEnvVar() string {
 	return config.DisableMetamorphicTestingEnvVar
 }
+
+// ClusterHook exposes a way to run functions in between steps normally
+// orchestrated by the framework.
```
Comment (srosenberg) [inline pkg/roachprod/install/cockroach.go:1690]: In this context, the only "framework" is `roachprod`; maybe paraphrase to say that it's merely a hook that's executed locally before cockroach process is started in the cluster.

File: pkg/roachprod/install/cockroach.go [hunk 7]
```diff
@@ -1671,3 +1685,10 @@ func getEnvVars() []string {
...
+type ClusterHook struct {
```
Comment (srosenberg) [inline pkg/roachprod/install/cockroach.go:1691]: Nit: why not `PrestartHook`? The `Name` is ambiguous, otherwise; plus, the `func` isn't aware of any cluster.

File: pkg/cmd/roachtest/roachtestutil/mixedversion/mixedversion.go [hunk 8]
```diff
@@ -696,6 +698,18 @@ func (t *Test) InMixedVersion(desc string, fn stepFunc) {
...
+// initialization. In the case of multitenant deployments, hooks
+// will be run for both the system and tenant cluster startup. If
+// only one of the two is desired, the caller can check the upgrade
```
[the remark this answers is not in the document]
Comment (DarrylWong) [reply pkg/cmd/roachtest/roachtestutil/mixedversion/mixedversion.go:704]: When you add hooks outside of the framework, you have to add both types because you don't know the deployment mode.

If you didn't want to unconditionally add both types, you could add it in as a cluster init hook, except checking in `mixedversion.Plan` wouldn't catch that since the hook hasn't run yet.

Maybe adding pre start hooks could be baked into yet another mixed version API call so we can only add whats needed, but perhaps that overkill for an already niche feature? Wdyt?

File: pkg/cmd/roachtest/roachtestutil/mixedversion/planner.go (hunk 1 above)
Comment (DarrylWong) [reply pkg/cmd/roachtest/roachtestutil/mixedversion/planner.go:579]: Hmm, yeah especially with delayed steps that would break the ordering even more. Okay, I've changed `clusterInitHook` to be `beforeClusterStartHook` instead. It works better for this use case to guarantee  it's spun up before cluster start and is imo more generalized for other potential use cases anyway.

Or do you mean that the clusterInitHooks should be run sequentially? I don't have an issue with that, I was just copying what `AfterTestHooks` and `AfterFinalizationHooks` does.

File: pkg/roachprod/install/cockroach.go (hunk 6 above)
Comment (DarrylWong) [reply pkg/roachprod/install/cockroach.go:1690]: Done.

File: pkg/roachprod/install/cockroach.go (hunk 7 above)
Comment (DarrylWong) [reply pkg/roachprod/install/cockroach.go:1691]: I envisioned this being used in `Stop` as well for clean up purposes. Maybe `PreStartStopHook` similar to how we have `StartStopOpts`? I'm okay with just `PrestartHook` for now though until we have other use cases.

File: pkg/roachprod/install/cockroach.go (hunk 5 above)
Comment (DarrylWong) [reply pkg/roachprod/install/cockroach.go]: Done, good catch

File: pkg/cmd/roachtest/roachtestutil/mixedversion/mixedversion.go (hunk 8 above)
[the remark this answers is not in the document]
Comment (srosenberg) [reply pkg/cmd/roachtest/roachtestutil/mixedversion/mixedversion.go:704]: Sounds good. We can revisit later.

**Review by srosenberg — APPROVED** [review]
LGTM! 🚢

**Comment by DarrylWong** [comment]
TFTR!

bors r=srosenberg

**Comment by DarrylWong** [comment]
blathers backport 25.1 24.3
