### PR TITLE
sql/import: fix progress summary loss during concurrent updates

### LINKED ISSUE #152543: jobs/IMPORT: job progress double counts rows if IMPORT job pauses and resumes
Apply [this diff](https://gist.github.com/ZhouXing19/12f0af97b1269a9694a7e5882541a8db) on the current master sha ff8cc3f1c1fc1e6b171abe882b95c90ea85ff24a and run  ./dev test pkg/sql/importer -f TestImportDefaultWithResume

The test will fail with 

```
```

### PR DESCRIPTION
**Pull request by ZhouXing19**
fixes #152543
fixes #152519

Previously, `accumulatedBulkSummary` was reset on each `updateJobProgress` call, assuming the job progress update would always succeed. However, if the update failed due to concurrent job state changes and retried, the reset buffer would cause progress data loss, resulting in incorrect row counts in progress reporting.

Fix this by removing the reset logic and directly assigning `accumulatedBulkSummary` to the progress summary instead of adding to it.

Release note (bug fix): Fixed import progress reporting to show correct row counts when concurrent job state changes occur.

### CODE REVIEW

File: pkg/sql/importer/import_stmt_test.go [hunk 1]
```diff
@@ -3836,6 +3839,22 @@ func TestImportDefaultWithResume(t *testing.T) {
 	defer TestingSetParallelImporterReaderBatchSize(batchSize)()
 	defer row.TestingSetDatumRowConverterBatchSize(2 * batchSize)()
 
+	ctx, cancel := context.WithTimeout(context.Background(), testutils.RaceSucceedsSoonDuration)
```
Comment (dt) [inline pkg/sql/importer/import_stmt_test.go]: do we need this? you can get this -- dumping all stacks after Xs -- by just running with `-timeout Xs` can't you? a bespoke per-test timeout and stack dumper feels a little weird to me.

**Review by dt — APPROVED** [review]

**Review by stevendanna — APPROVED** [review]
Thanks!  Aside from David's comment about the stack printing, this looks good to me!

File: pkg/sql/importer/import_stmt_test.go (hunk 1 above)
Comment (ZhouXing19) [reply pkg/sql/importer/import_stmt_test.go]: Thanks for reviewing!

Good point, removed the timeout here.

**Comment by ZhouXing19** [comment]
TFTR! Also, huge thanks for debugging with me so patiently!!

bors r+
