### PR TITLE
storage: improve TestPushTxnQueueCancel

### LINKED ISSUE #19333: storage: TestPushTxnQueueCancel failed under stress
SHA: https://github.com/cockroachdb/cockroach/commits/f3c7781cdd16160aace3f65663b6848ce103d18c

Parameters:
```
TAGS=
GOFLAGS=
```

Stress build found a failed test: https://teamcity.cockroachdb.com/viewLog.html?buildId=380879&tab=buildLog

```
I171018 06:50:00.936059 1477 storage/store.go:1212  [s1] [n1,s1]: failed initial metrics computation: [n1,s1]: system config not yet available
	soon.go:44: storage/push_txn_queue_test.go:261, condition failed to evaluate within 45s: expected GetDependents [f6fc7d98-e045-48b9-8301-12c507e49abb]; got []
		goroutine 1477 [running]:
		runtime/debug.Stack(0x2, 0x2925de4, 0x1e)
			/usr/local/go/src/runtime/debug/stack.go:24 +0xa7
		github.com/cockroachdb/cockroach/pkg/testutils.SucceedsSoonDepth(0x1, 0x2c15060, 0xc4201c04b0, 0xc42064fdf0)
			/go/src/github.com/cockroachdb/cockroach/pkg/testutils/soon.go:45 +0xa1
		github.com/cockroachdb/cockroach/pkg/testutils.SucceedsSoon(0x2c15060, 0xc4201c04b0, 0xc42064fdf0)
			/go/src/github.com/cockroachdb/cockroach/pkg/testutils/soon.go:36 +0x48
		github.com/cockroachdb/cockroach/pkg/storage.TestPushTxnQueueCancel(0xc4201c04b0)
			/go/src/github.com/cockroachdb/cockroach/pkg/storage/push_txn_queue_test.go:261 +0x486
		testing.tRunner(0xc4201c04b0, 0x1e3c860)
			/usr/local/go/src/testing/testing.go:746 +0xd0
		created by testing.(*T).Run
			/usr/local/go/src/testing/testing.go:789 +0x2de
```

### PR DESCRIPTION
**Pull request by tbg**
I was unable to reproduce

https://github.com/cockroachdb/cockroach/issues/19333

in >25k iterations, but I suspect an error was returned and the
test never got to check it. With these changes, the next time it
flakes we will have more intel.

Closes #19333.

### CODE REVIEW

File: pkg/storage/push_txn_queue_test.go [hunk 1]
```diff
@@ -259,6 +259,11 @@ func TestPushTxnQueueCancel(t *testing.T) {
 	}()
 
 	testutils.SucceedsSoon(t, func() error {
+		select {
+		case rwe := <-retCh:
+			t.Fatal("MaybeWaitForPush terminated prematurely: %+v", rwe)
```
Comment (tamird) [inline pkg/storage/push_txn_queue_test.go]: Fatalf

**Comment by bdarnell** [comment]
:lgtm:

---

Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/19410#-:-KwuuGbHL3QFy9yvYuCv:bnfp4nl)*
