### PR TITLE
server: fix problem range's leader not leaseholder listing

### LINKED ISSUE #15440: server: malformed problem ranges page
The screenshot was taken through an ssh tunnel so perhaps some bit of css wasn't loading:

screen shot 2017-04-27 at 9 27 45 pm

Two problems:
* No spaces between the range IDs
* The range IDs do not wrap

### PR DESCRIPTION
**Pull request by BramGruneir**
There was a missing nbsp so the list of ranges didn't wrap correctly and was really tough to read.

Fixes #15440.

### CODE REVIEW

**Comment by BramGruneir** [comment]
screen shot 2017-04-28 at 14 38 04

**Comment by petermattis** [comment]
:lgtm:

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15481#-:-Kiptl8ECIUTuuQyjaWK:bnfp4nl)*

File: pkg/server/problem_ranges.go [hunk 1]
```diff
@@ -289,7 +289,7 @@ const debugProblemRangesTemplate = `
         <DIV CLASS="row">
           {{- if $.LeaderNotLeaseholder}}
             {{- range $_, $r := $.LeaderNotLeaseholder}}
-              <a href="/debug/range?id={{$r}}">{{$r}}</a>
+              <a href="/debug/range?id={{$r}}">{{$r}}</a> &nbsp;
```
Comment (bdarnell) [inline pkg/server/problem_ranges.go]: There's both a breaking and a non-breaking space here (and the line is getting broken). I think what you want is to remove the whitespace-stripping `-` from the beginning of the `{{- end}}` directive (unless you intend for there to be two spaces between entries in this list).

Comment (BramGruneir) [inline pkg/server/problem_ranges.go]: I want to keep the `-` in `{{- end}}` or else it adds an extra newline (not visible, but make the source ugly).  But you're right, I can remove the breaking space.  Done.

Notice the space difference with the previous screencap.

screen shot 2017-04-28 at 15 03 13

Comment (bdarnell) [inline pkg/server/problem_ranges.go]: So the browser is breaking at non-breaking spaces? Weird. Semantically, breaking whitespace is what you want here. I think if you want a breaking space that the template won't eat you can use `{{" "}}`.

Comment (BramGruneir) [inline pkg/server/problem_ranges.go]: Sadly, going with just `{{" "}}` doesn't produce any spaces either.  I think the `{{- ...` is eating it as well.

So with `<a href="/debug/range?id={{$r}}">{{$r}}</a>{{" "}}`
We get:
```
              <a href="/debug/range?id=0">0</a> 
              <a href="/debug/range?id=1">1</a> 
              <a href="/debug/range?id=2">2</a> 
   ```
But no spaces between ids.

screen shot 2017-05-01 at 11 30 00


I think the nbsp is correct because there's only one anchor per line it is allowed to break on at the newline instead of on the nbsp itself.

Comment (bdarnell) [inline pkg/server/problem_ranges.go]: Weird, but OK. Whatever works.
