### PR TITLE
workload/schemachange: fix date parsing error in SET DEFAULT operations

### LINKED ISSUE #152572: roachtest: backup-restore/online-restore failed [could not parse date]
roachtest.backup-restore/online-restore [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/20395454?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/20395454?buildTab=artifacts#/backup-restore/online-restore) on master @ [776ec8789781412afa041bfe398db6ecf8312073](https://github.com/cockroachdb/cockroach/commits/776ec8789781412afa041bfe398db6ecf8312073):

```
(monitor.go:267).Wait: monitor failure: schema change workload failed: full command output in run_055023.528592494_n4_COCKROACHRANDOMSEED6.log: COMMAND_PROBLEM: exit status 1 [owner=sql-foundations]
test artifacts and logs in: /artifacts/backup-restore/online-restore/run_1
```

Parameters:
 - <code>arch=amd64</code>
 - <code>cloud=gce</code>
 - <code>coverageBuild=false</code>
 - <code>cpu=4</code>
 - <code>encrypted=false</code>
 - <code>fs=ext4</code>
 - <code>localSSD=true</code>
 - <code>metamorphicBufferedSender=true</code>
 - <code>metamorphicWriteBuffering=true</code>
 - <code>runtimeAssertionsBuild=false</code>
 - <code>ssd=0</code>
<details><summary>Help</summary>
<p>

See: [roachtest README](https://github.com/cockroachdb/cockroach/blob/master/pkg/cmd/roachtest/README.md)

See: [How To Investigate \(internal\)](https://cockroachlabs.atlassian.net/l/c/SSSBr8c7)

See: [Grafana](https://go.crdb.dev/roachtest-grafana/teamcity-20395454/backup-restore-online-restore/1756273740395/1756275023952)

</p>
</details>
<details><summary>Same failure on other branches</summary>
<p>

- #150819 roachtest: backup-restore/online-restore failed [A-disaster-recovery B-runtime-assertions-enabled C-test-failure O-roachtest O-robot P-2 T-disaster-recovery branch-release-25.3.0-rc]
</p>
</details>
/cc @cockroachdb/sql-foundations
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*backup-restore/online-restore.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/bazci/githubpost/issues)

</sub>

Jira issue: CRDB-53924

### PR DESCRIPTION
**Pull request by spilchen**
The schemachange workload could generate invalid SQL when testing type mismatches, causing parse errors instead of expected type mismatch errors.

Fix by always using explicit type casting in SET DEFAULT statements.

Fixes: #152572

Release note: None

Epic: None

### CODE REVIEW

File: pkg/workload/schemachange/operation_generator.go [hunk 1]
```diff
@@ -2530,8 +2530,11 @@ func (og *operationGenerator) setColumnDefault(ctx context.Context, tx pgx.Tx) (
 	}
 
 	strDefault := tree.AsStringWithFlags(defaultDatum, tree.FmtParsable)
-	stmt.sql = fmt.Sprintf(`ALTER TABLE %s ALTER COLUMN %s SET DEFAULT %s`,
-		tableName.String(), columnForDefault.name.String(), strDefault)
+	// Always use explicit type casting to ensure consistent behavior and avoid parse errors.
+	// When the types don't match, this will produce the expected DatatypeMismatch error.
+	// When the types do match, the cast is harmless and makes the intent explicit.
+	stmt.sql = fmt.Sprintf(`ALTER TABLE %s ALTER COLUMN %s SET DEFAULT %s:::%s`,
```
Comment (rafiss) [inline pkg/workload/schemachange/operation_generator.go]: super nit: `:::` technically isn't a "cast" -- instead we call that a "type annotation." the difference is described here: https://www.cockroachlabs.com/docs/v25.3/scalar-expressions#explicitly-typed-expressions

if we can use a cast (`::`) here instead, then let's do that.

**Review by rafiss — APPROVED** [review]
nice find!

File: pkg/workload/schemachange/operation_generator.go (hunk 1 above)
Comment (spilchen) [reply pkg/workload/schemachange/operation_generator.go]: Good to know. I had seen both and didn't realize the difference. I updated it to be a cast.

**Review by spilchen — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/152877)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @herkolategan, @rafiss, and @srosenberg)
