### PR TITLE
changefeedccl: flush to sink before initial_scan_only completion

### LINKED ISSUE #90146: changefeedccl: initial_scan_only does not emit all messages before completing
**Describe the problem**

`initial_scan_only` appears to exit the changefeed with a success prior to all messages being received by the external sink.

This is likely due to the `errChangefeedCompleted` exiting after observing a resolved event at the kvfeed level when the messages are being emitted and buffered at the sink level later on in the pipeline.

**To Reproduce**
Verified on 22.1.9

1. Start a local kafka server and a single node CRDB server
2. Load a small `tpcc` fixture (`./bin/workload fixtures import tpcc --warehouses=3 --checks=false`)
3. Start consuming from a topic `confluent local services kafka consume testTopic`
4. Create a changefeed on a table with a decent amount of rows like `tpcc.item` (100000 rows), a large batch configuration makes the effect more pronounced: 
```create changefeed for tpcc.item into 'kafka://localhost:9092?topic_name=testTopic' with initial_scan='only', kafka_sink_config='{"Flush": {"Messages": 5000, "MaxMessages": 10000, "Frequency": "2s"}}';```
5. Once the changefeed succeeds (should be quick, can verify in `show changefeed jobs`), go to the terminal that has the `kafka consume testTopic` running and `ctrl-c` out of it.  It'll print out the number of rows it observed. In my case this was "Processed a total of 1152 messages"

Doing the same without `initial_scan_only` and then closing after no more changes show up results in the correct `100000` messages.

**Expected behavior**
`initial_scan_only` should complete only after all rows in the table have been emitted to the sink

Jira issue: CRDB-20614

### PR DESCRIPTION
**Pull request by samiskin**
Resolves https://github.com/cockroachdb/cockroach/issues/90146

Previously if a changefeed was started with initial_scan_only, the job would be completed as soon as a resolved event was seen by the kv_feed even though we may not have flushed the messages to the sink yet.  This could result in a huge difference where an initial_scan_only changefeed on a 100000 row table could complete successfully with a kafka topic only seeing <2000 messages.  A similar issue of missing messages would also occur with schema_change_policy='stop', though the changefeed is marked failed in that case.

This change ensures the changefeed drains the eventProducer and sink upon a normal kvfeed exit.

This also uncovered a bug in the chunked_event_queue where empty() could return true even if there were many remaining messages due to the first chunk being empty but there still being future chunks.

Release note (bug fix): initial_scan_only changefeeds now ensure that all messages have successfully flushed to the sink prior to completion instead of potentially missing messages.

### CODE REVIEW

File: pkg/ccl/changefeedccl/changefeed_test.go [hunk 1]
```diff
@@ -6348,40 +6348,45 @@ func TestChangefeedOnlyInitialScan(t *testing.T) {
 
 		for testName, changefeedStmt := range initialScanOnlyTests {
 			t.Run(testName, func(t *testing.T) {
-				sqlDB.Exec(t, "CREATE TABLE foo (a INT PRIMARY KEY)")
-				sqlDB.Exec(t, "INSERT INTO foo VALUES (1), (2), (3)")
+				sqlDB.Exec(t, `CREATE TABLE foo (a INT PRIMARY KEY)`)
+				sqlDB.Exec(t, `INSERT INTO foo (a) SELECT * FROM generate_series(1, 5000);`)
```
Comment (samiskin) [inline pkg/ccl/changefeedccl/changefeed_test.go:6352]: All it took to reproduce this issue was to go from 3 values to 1000 in the original test, yet this didn't flake on 3 (as far as I know).  A good reminder that there's distinct value in doing larger tables in our unit tests.

**Comment by samiskin** [comment]
Manually verified that the repro in #90146 now emits all messages 
Screen Shot 2022-10-19 at 11 17 07 AM

File: pkg/ccl/changefeedccl/changefeed_processors.go [hunk 2]
```diff
@@ -478,10 +478,23 @@ func (ca *changeAggregator) Next() (rowenc.EncDatumRow, *execinfrapb.ProducerMet
 		if err := ca.tick(); err != nil {
 			var e kvevent.ErrBufferClosed
 			if errors.As(err, &e) {
-				// ErrBufferClosed is a signal that
-				// our kvfeed has exited expectedly.
+				// ErrBufferClosed is a signal that our kvfeed has exited expectedly. If
+				// so we need to make sure all events are cleared to the sink before
+				// exiting.
```
Comment (miretskiy) [inline pkg/ccl/changefeedccl/changefeed_processors.go:483]: I'm not sure this is the right place for a fix...
consider https://github.com/cockroachdb/cockroach/blob/master/pkg/ccl/changefeedccl/kvfeed/kv_feed.go#L145-L145
We drain kv_feed buffers before we exit.  Perhaps we should do the same here.
Another possibility is to emit EXIT boundary type so that changefeed naturally exits.

**Review by miretskiy — CHANGES_REQUESTED** [review]

File: pkg/ccl/changefeedccl/changefeed_processors.go (hunk 2 above)
Comment (miretskiy) [reply pkg/ccl/changefeedccl/changefeed_processors.go:483]: I understand, but what I don't understand is why can't we drain the buffer at kvfeed -- is that not sufficient -- just like we do in case of schema changes?

File: pkg/ccl/changefeedccl/kvevent/chunked_event_queue.go [hunk 3]
```diff
@@ -117,7 +119,7 @@ func (bec *bufferEventChunk) pop() (e Event, ok bool, consumedAll bool) {
 
 	e = bec.events[bec.head]
 	bec.head++
-	return e, true, false
+	return e, true, bec.head == bec.tail
```
Comment (jayshrivastava) [inline pkg/ccl/changefeedccl/kvevent/chunked_event_queue.go:122]: Can you clarify what these changes fix? I'm not too sure about them.
For example, if `bec.head == bec.tail` is true, `dequeue` will free the chunk. If `bufferEventChunkArrSize < bufferEventChunkArrSize`, we will end up skipping values right?

Comment (jayshrivastava) [reply pkg/ccl/changefeedccl/kvevent/chunked_event_queue.go]: I think returning `bec.head == bufferEventChunkArrSize` should do the trick.

Comment (samiskin) [reply pkg/ccl/changefeedccl/kvevent/chunked_event_queue.go]: Good idea 👍

**Review by miretskiy — APPROVED** [review]
