### PR TITLE
kvserver: explicitly run tests with epoch leases

### LINKED ISSUE #136548: kv/kvserver: TestRequestsOnFollowerWithNonLiveLeaseholder failed
kv/kvserver.TestRequestsOnFollowerWithNonLiveLeaseholder [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Ci_TestsAwsLinuxArm64_UnitTests/18008028?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Ci_TestsAwsLinuxArm64_UnitTests/18008028?buildTab=artifacts#/) on master @ [b3fec61ca90095c664f6432af864f18e9946f8bb](https://github.com/cockroachdb/cockroach/commits/b3fec61ca90095c664f6432af864f18e9946f8bb):

```
=== RUN   TestRequestsOnFollowerWithNonLiveLeaseholder
    test_log_scope.go:165: test logs captured to: /artifacts/tmp/_tmp/7334302ae8c22802de8334e77d6901c9/logTestRequestsOnFollowerWithNonLiveLeaseholder593634506
    test_log_scope.go:76: use -show-logs to present logs inline
    client_raft_test.go:1440: 
        	Error Trace:	pkg/kv/kvserver/client_raft_test.go:1440
        	Error:      	Should be false
        	Test:       	TestRequestsOnFollowerWithNonLiveLeaseholder
    panic.go:626: -- test log scope end --
test logs left over in: /artifacts/tmp/_tmp/7334302ae8c22802de8334e77d6901c9/logTestRequestsOnFollowerWithNonLiveLeaseholder593634506
--- FAIL: TestRequestsOnFollowerWithNonLiveLeaseholder (1.01s)
```
<details><summary>Help</summary>
<p>

See also: [How To Investigate a Go Test Failure \(internal\)](https://cockroachlabs.atlassian.net/l/c/HgfXfJgM)
</p>
</details>
/cc @cockroachdb/kv
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*TestRequestsOnFollowerWithNonLiveLeaseholder.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/bazci/githubpost/issues)

</sub>

Jira issue: CRDB-45116

### LINKED ISSUE #136582: kv/kvserver: TestRaftPreVoteUnquiesceDeadLeader failed
kv/kvserver.TestRaftPreVoteUnquiesceDeadLeader [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Ci_TestsAwsLinuxArm64_UnitTests/18013269?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Ci_TestsAwsLinuxArm64_UnitTests/18013269?buildTab=artifacts#/) on master @ [0ea9ae61bfe16ba95414c287753c67334e92e578](https://github.com/cockroachdb/cockroach/commits/0ea9ae61bfe16ba95414c287753c67334e92e578):

```
=== RUN   TestRaftPreVoteUnquiesceDeadLeader
    test_log_scope.go:165: test logs captured to: /artifacts/tmp/_tmp/dfba1fd6cc9e1d30670286cfc03f3d34/logTestRaftPreVoteUnquiesceDeadLeader416970932
    test_log_scope.go:76: use -show-logs to present logs inline
    client_raft_helpers_test.go:532: from store 1; adding store 2 to drop list
    client_raft_helpers_test.go:532: from store 1; adding store 3 to drop list
    client_raft_helpers_test.go:532: from store 2; adding store 1 to drop list
    client_raft_helpers_test.go:532: from store 3; adding store 1 to drop list
    client_raft_test.go:6950: n1 has lease
    client_raft_test.go:6953: 
        	Error Trace:	pkg/kv/kvserver/client_raft_test.go:6953
        	Error:      	Condition never satisfied
        	Test:       	TestRaftPreVoteUnquiesceDeadLeader
    panic.go:626: -- test log scope end --
test logs left over in: /artifacts/tmp/_tmp/dfba1fd6cc9e1d30670286cfc03f3d34/logTestRaftPreVoteUnquiesceDeadLeader416970932
--- FAIL: TestRaftPreVoteUnquiesceDeadLeader (11.38s)
```
<details><summary>Help</summary>
<p>

See also: [How To Investigate a Go Test Failure \(internal\)](https://cockroachlabs.atlassian.net/l/c/HgfXfJgM)
</p>
</details>
/cc @cockroachdb/kv
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*TestRaftPreVoteUnquiesceDeadLeader.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/bazci/githubpost/issues)

</sub>

Jira issue: CRDB-45146

### PR DESCRIPTION
**Pull request by arulajmani**
This patch explicitly runs a couple of tests
(TestRaftPreVoteUnquiesceDeadLeader and
TestRequestsOnFollowerWithNonLiveLeaseholder) with epoch based leases. These were broken by 3904daa7feeb1b9d537337daec3ade121c76171e.

Closes https://github.com/cockroachdb/cockroach/issues/136582 
Closes https://github.com/cockroachdb/cockroach/issues/136548

Release note: None

### CODE REVIEW

File: pkg/kv/kvserver/client_raft_test.go [hunk 1]
```diff
@@ -1319,7 +1319,7 @@ func TestRequestsOnFollowerWithNonLiveLeaseholder(t *testing.T) {
 
 	st := cluster.MakeTestingClusterSettings()
 	// This test is specifically designed for epoch based leases.
-	kvserver.OverrideLeaderLeaseMetamorphism(ctx, &st.SV)
+	kvserver.OverrideDefaultLeaseType(ctx, &st.SV, roachpb.LeaseEpoch)
```
Comment (pav-kv) [inline pkg/kv/kvserver/client_raft_test.go:1322]: Is this a no-op? The `OverrideLeaderLeaseMetamorphism` does the same invocation.

Comment (arulajmani) [reply pkg/kv/kvserver/client_raft_test.go:1322]: Not any more -- see the commit linked in the PR description.

Comment (pav-kv) [reply pkg/kv/kvserver/client_raft_test.go:1322]: Oh I see, not since 3904daa7.

**Review by pav-kv — APPROVED** [review]

**Comment by arulajmani** [comment]
TFTR!

bors r=pav-kv
