### PR TITLE
roachtest: re-add descriptor version mismatch retry for mixed-version backup

### LINKED ISSUE #166147: roachtest: backup-restore/mixed-version failed
roachtest.backup-restore/mixed-version [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/21273231?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/21273231?buildTab=artifacts#/backup-restore/mixed-version) on master @ [df733c0394b5bd0ffd29eff16b10b4d5a256dfa1](https://github.com/cockroachdb/cockroach/commits/df733c0394b5bd0ffd29eff16b10b4d5a256dfa1):

Failed with:

```
(mixedversion.go:926).Run: mixed-version test failure while running step 43 (run "verify some backups"): mixed-version: error restoring backup: error waiting for job to finish: job 1159452539032535041 failed with error: version mismatch for descriptor 160, expected version 1, got 2
test artifacts and logs in: /artifacts/backup-restore/mixed-version/cpu_arch=arm64/run_1
```
Cluster Node to Ip Mapping:
| Node | Public IP | Private IP |
| --- | --- | --- |
| teamcity-21273231-1773901404-21-n5cpu4-0001 | 136.119.245.131 | 10.128.0.233 |
| teamcity-21273231-1773901404-21-n5cpu4-0002 | 34.55.214.13 | 10.128.0.231 |
| teamcity-21273231-1773901404-21-n5cpu4-0003 | 34.170.82.50 | 10.128.0.232 |
| teamcity-21273231-1773901404-21-n5cpu4-0004 | 136.112.193.113 | 10.128.0.234 |
| teamcity-21273231-1773901404-21-n5cpu4-0005 | 35.238.7.213 | 10.128.0.30 |

Parameters:
 - <code>arch=arm64</code>
 - <code>cloud=gce</code>
 - <code>coverageBuild=false</code>
 - <code>cpu=4</code>
 - <code>diskCount=0</code>
 - <code>encrypted=true</code>
 - <code>fs=ext4</code>
 - <code>localSSD=false</code>
 - <code>mvtDeploymentMode=system-only</code>
 - <code>mvtVersions=v25.1.10 → v25.2.14 → v25.4.5 → v26.2.0-alpha.2-dev-df733c0394b5bd0ffd29eff16b10b4d5a256dfa1 (master)</code>
 - <code>runtimeAssertionsBuild=false</code>
<details><summary>Help</summary>
<p>

See: [roachtest README](https://github.com/cockroachdb/cockroach/blob/master/pkg/cmd/roachtest/README.md)

See: [How To Investigate \(internal\)](https://cockroachlabs.atlassian.net/l/c/SSSBr8c7)

See: [Grafana](https://go.crdb.dev/roachtest-grafana/teamcity-21273231/backup-restore-mixed-version/1773902856486/1773907517177)

</p>
</details>
<details><summary>Same failure on other branches</summary>
<p>

- #157896 roachtest: backup-restore/mixed-version failed [A-disaster-recovery C-test-failure O-roachtest O-robot P-2 T-disaster-recovery branch-release-25.4.0-rc release-blocker]
</p>
</details>
/cc @cockroachdb/disaster-recovery
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*backup-restore/mixed-version.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/bazci/githubpost/issues)

</sub>

Jira issue: CRDB-61770

### PR DESCRIPTION
**Pull request by kev-cao**
The descriptor version mismatch check and restore retry was accidentally removed in #165848. This re-adds the retry logic so that the mixed-version backup test can handle the 25.4 upgrade descriptor rewrite race.

Fixes: #166147

Release note: None

### CODE REVIEW

File: pkg/cmd/roachtest/tests/backup_restore_driver.go [hunk 1]
```diff
@@ -222,11 +224,38 @@ func (d *BackupRestoreTestDriver) verifyBackupCollection(
 	bc *backupCollection,
 	checkFiles bool,
 	internalSystemJobs bool,
+	mvHelper *mixedversion.Helper,
```
Comment (msbutler) [inline pkg/cmd/roachtest/tests/backup_restore_driver.go:227]: ah, that's why we needed the mvt helper :)

**Review by msbutler — APPROVED** [review]
