### PR TITLE
liveness: clarify `IncrementEpoch` race error and log as INFO

### LINKED ISSUE #93791: liveness: clarify IncrementEpoch race error and log as INFO
When a node's liveness record changes while someone else is trying to bump its epoch to invalidate its leases, we log this error:

```
failed to increment leaseholder's epoch: mismatch incrementing epoch for ‹liveness(nid:179 epo:18 exp:1671184637.805479307,0)›; actual is ‹liveness(nid:179 epo:18 exp:1671184646.805496077,0)›'
```

Notably, the epoch is the same. This typically happens because the node failed to heartbeat for a while, someone else tries to grab its leases, but then the node is able to heartbeat again, changing the expiration time of the liveness record. We should clarify this in the log message.

Jira issue: CRDB-22529

### PR DESCRIPTION
**Pull request by erikgrinaker**
Resolves #93791.

Epic: none
Release note: None

### CODE REVIEW

**Comment by erikgrinaker** [comment]
I could even be convinced to not log this at all.

File: pkg/kv/kvserver/liveness/liveness.go [hunk 1]
```diff
@@ -67,6 +67,16 @@ var (
 	ErrEpochAlreadyIncremented = errors.New("epoch already incremented")
 )
 
+type ErrEpochCondFailed struct {
+	expected, actual livenesspb.Liveness
+}
+
+func (e *ErrEpochCondFailed) Error() string {
```
Comment (tbg) [inline pkg/kv/kvserver/liveness/liveness.go:74]: Something something implement redaction.

https://github.com/cockroachdb/cockroach/blob/73014328430907dc831374a6517992f4c7c21325/pkg/cli/clierror/cli_error.go#L45-L71

I would also agree to just suppress the logging for this case.

**Review by tbg — APPROVED** [review]

File: pkg/kv/kvserver/liveness/liveness.go (hunk 1 above)
Comment (erikgrinaker) [reply pkg/kv/kvserver/liveness/liveness.go:74]: There's nothing to redact in this error, the liveness info is not sensitive. Or am I misunderstanding your suggestion?

Comment (tbg) [reply pkg/kv/kvserver/liveness/liveness.go:74]: Just to make sure that this error does show up properly in redacted logs. I think right now it will just turn into `<x>` because you're not implementing the redactable printing?

Comment (erikgrinaker) [reply pkg/kv/kvserver/liveness/liveness.go:74]: Oh right, good point. I'll have a look.
