### PR TITLE
build: fix pebble nightly test binary build

### LINKED ISSUE #101314: storage: pebble metamorphic test failed due to unapplied patch
See [this](https://teamcity.cockroachdb.com/viewLog.html?buildId=9554096&buildTypeId=Cockroach_Nightlies_NightlyPebbleMetamorphicCrossversion) build.

```
[03:59:34][Compile Pebble crl-release-21.2 metamorphic test binary] 1 out of 1 hunk ignored
[03:59:34][Compile Pebble crl-release-21.2 metamorphic test binary] ERROR: Error applying patch @com_github_cockroachdb_cockroach//build/patches:com_github_cockroachdb_pebble.patch:
[03:59:34][Compile Pebble crl-release-21.2 metamorphic test binary] patching file internal/invariants/BUILD.bazel
[03:59:34][Compile Pebble crl-release-21.2 metamorphic test binary] can't find file to patch at input line 15
[03:59:34][Compile Pebble crl-release-21.2 metamorphic test binary] Perhaps you used the wrong -p or --strip option?
[03:59:34][Compile Pebble crl-release-21.2 metamorphic test binary] The text leading up to this was:
[03:59:34][Compile Pebble crl-release-21.2 metamorphic test binary] --------------------------
[03:59:34][Compile Pebble crl-release-21.2 metamorphic test binary] |diff -urN a/objstorage/objstorageprovider/objiotracing/BUILD.bazel b/objstorage/objstorageprovider/objiotracing/BUILD.bazel
[03:59:34][Compile Pebble crl-release-21.2 metamorphic test binary] |--- a/objstorage/objstorageprovider/objiotracing/BUILD.bazel 1969-12-31 19:00:00.000000000 -0500
[03:59:34][Compile Pebble crl-release-21.2 metamorphic test binary] |--- b/objstorage/objstorageprovider/objiotracing/BUILD.bazel 2023-03-29 09:59:04.529504100 -0700
[03:59:34][Compile Pebble crl-release-21.2 metamorphic test binary] --------------------------
[03:59:34][Compile Pebble crl-release-21.2 metamorphic test binary] File to patch: 
[03:59:34][Compile Pebble crl-release-21.2 metamorphic test binary] Skip this patch? [y] 
[03:59:34][Compile Pebble crl-release-21.2 metamorphic test binary] Skipping patch.
[03:59:34][Compile Pebble crl-release-21.2 metamorphic test binary] 1 out of 1 hunk ignored
[03:59:34][Compile Pebble crl-release-21.2 metamorphic test binary] INFO: Elapsed time: 2.936s
[03:59:34][Compile Pebble crl-release-21.2 metamorphic test binary] INFO: 0 processes.
[03:59:34][Compile Pebble crl-release-21.2 metamorphic test binary] FAILED: Build did NOT complete successfully (0 packages loaded)
[03:59:34][Compile Pebble crl-release-21.2 metamorphic test binary] FAILED: Build did NOT complete successfully (0 packages loaded)
[03:59:34][Compile Pebble crl-release-21.2 metamorphic test binary] Process exited with code 1
```

### PR DESCRIPTION
**Pull request by RaduBerinde**
The `pebble_nightly_build_test_binary.sh` is used to create a test binary against older versions of Pebble. The recently updated patch to the pebble `BUILD.bazel` files (`com_github_cockroachdb_pebble.patch`) does not apply against older versions.

The fix is to remove the patch altogether when building the test binary. The "unpatched" configuration corresponds to the `invariant` tag being set (and `pebble_obj_io_tracing` tag being unset), which is what we want.

Fixes #101314.

Release note: None

### CODE REVIEW

File: build/teamcity/cockroach/nightlies/pebble_nightly_build_test_binary.sh [hunk 1]
```diff
@@ -16,6 +16,11 @@ DEST="$2"
 BAZEL_BIN=$(bazel info bazel-bin --config ci)
 
 bazel run @go_sdk//:bin/go get "github.com/cockroachdb/pebble@$PEBBLE_BRANCH"
+
+# Remove the patch, which doesn't work with older versions. The "unpatched"
+# config assumes the invariants tag is set.
+rm -f build/patches/com_github_cockroachdb_pebble.patch
```
Comment (rickystewart) [inline build/teamcity/cockroach/nightlies/pebble_nightly_build_test_binary.sh:22]: Have you tried this? I'm pretty sure the build will fail because it's looking for this file but it doesn't exist.

Making the file contents empty may work, I think if you apply an empty diff then nothing happens?

**Review by RaduBerinde — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/101351)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jbowens, @nicktrav, and @rickystewart)

___
*[`build/teamcity/cockroach/nightlies/pebble_nightly_build_test_binary.sh` line 22 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/101351#gh-1164448512:-NSq_FeM0x29IIXJY1vv:bgur379) ([raw file](https://github.com/cockroachdb/cockroach/blob/8708a514506f0133cde80c487e1fbcd82f58188c/build/teamcity/cockroach/nightlies/pebble_nightly_build_test_binary.sh#L22)):*
<details><summary><i>Previously, rickystewart (Ricky Stewart) wrote…</i></summary><blockquote>

Have you tried this? I'm pretty sure the build will fail because it's looking for this file but it doesn't exist.

Making the file contents empty may work, I think if you apply an empty diff then nothing happens?
</blockquote></details>

Yes, I did. It works because the line below regenerates `DEPS.bzl` and the mirror cmd just looks for patches that exist: https://github.com/cockroachdb/cockroach/blob/master/pkg/cmd/mirror/go/mirror.go#L245

**Comment by RaduBerinde** [comment]
*[`build/teamcity/cockroach/nightlies/pebble_nightly_build_test_binary.sh` line 22 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/101351#gh-1164448512:-NSqa8YJ3CgpSINeGuZK:b-67ih27) ([raw file](https://github.com/cockroachdb/cockroach/blob/8708a514506f0133cde80c487e1fbcd82f58188c/build/teamcity/cockroach/nightlies/pebble_nightly_build_test_binary.sh#L22)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

Yes, I did. It works because the line below regenerates `DEPS.bzl` and the mirror cmd just looks for patches that exist: https://github.com/cockroachdb/cockroach/blob/master/pkg/cmd/mirror/go/mirror.go#L245
</blockquote></details>

Improved the comment to explain this.

**Comment by rickystewart** [comment]
> > _[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/101351)_ status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jbowens, @nicktrav, and @rickystewart)
> 
> _[`build/teamcity/cockroach/nightlies/pebble_nightly_build_test_binary.sh` line 22 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/101351#gh-1164448512:-NSq_FeM0x29IIXJY1vv:bgur379) ([raw file](https://github.com/cockroachdb/cockroach/blob/8708a514506f0133cde80c487e1fbcd82f58188c/build/teamcity/cockroach/nightlies/pebble_nightly_build_test_binary.sh#L22)):_
> 
> Previously, rickystewart (Ricky Stewart) wrote…
> Yes, I did. It works because the line below regenerates `DEPS.bzl` and the mirror cmd just looks for patches that exist: [`master`/pkg/cmd/mirror/go/mirror.go#L245](https://github.com/cockroachdb/cockroach/blob/master/pkg/cmd/mirror/go/mirror.go?rgh-link-date=2023-04-12T17%3A49%3A39Z#L245)

Ah, yes, you are right.

**Review by rickystewart — APPROVED** [review]

**Review by RaduBerinde — COMMENTED** [review]
Ah, `DEPS.bzl` is generated, I can't just randomly add comments to it. Reverted the comments (but instituted the typo fix).

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/101351#-:-NSqmIeFDMkinILfzI0i:b3ms3g9)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jbowens, @nicktrav, and @rickystewart)
