### PR TITLE
roachtest: provision 250 MB/s for 8TB restore test

### LINKED ISSUE #107609: roachtest: bump AWS provisioned write bandwidth for all restore tests
**Describe the problem**

A number of restore tests are failing on AWS with OOMs in the replication layer.

While we improve the memory accounting in the replication layer, it's not useful for these tests to keep failing.

We are fairly confident that the ooms can be traced to disk overload. Default AWS provisioned gp3 volumes come with combined read+write throughput of 125mb/s, which is routinely maxed out in tests. Combined with load imbalances in the cluster, this can lead to OOMs in the replication layer today.

We should double the provisioned write bandwidth and make sure that this is the default on AWS for the restore tests. This should be easy, as these tests have their own little framework (i.e. all tests go through a central code path).

Holistically addressing the OOMs is tracked in [CRDB-25503](https://cockroachlabs.atlassian.net/browse/CRDB-25503).

Jira issue: CRDB-30126

### PR DESCRIPTION
**Pull request by pav-kv**
The `restore/tpce/8TB/aws/nodes=10/cpus=8` test maxes out the default 125 MB/s EBS throughput. This commit provisions throughput to be 250 MB/s so that the test doesn't work at the edge of overload.

See https://github.com/cockroachdb/cockroach/issues/107609#issuecomment-1671415670 for the before/after comparison.

Touches #106496
Fixes #107609
Epic: none
Release note: none

### CODE REVIEW

**Comment by pavelkalinnikov** [comment]
@msbutler PTAL

File: pkg/cmd/roachtest/tests/restore.go [hunk 1]
```diff
@@ -466,6 +469,9 @@ type hardwareSpecs struct {
 	// volumeSize indicates the size of per node block storage (pd-ssd for gcs,
 	// ebs for aws). If zero, local ssd's are used.
 	volumeSize int
+	// throughput is the min provisioned throughput of the storage, in MB/s.
+	// TODO(pavelkalinnikov): currently works only for EBS.
+	throughput int
```
Comment (msbutler) [inline pkg/cmd/roachtest/tests/restore.go:474]: nit: rename to AWSEBSThoughput

File: pkg/roachprod/vm/gce/gcloud.go [hunk 2]
```diff
@@ -1009,6 +1009,7 @@ func (p *Provider) Create(
 			fmt.Sprintf("size=%dGB", providerOpts.PDVolumeSize),
 			"auto-delete=yes",
 		}
+		// TODO(pavelkalinnikov): set the "provisioned-throughput" in MB/s too.
 		args = append(args, "--create-disk", strings.Join(pdProps, ","))
```
Comment (msbutler) [inline pkg/roachprod/vm/gce/gcloud.go:1013]: afaict, gce doesn't allow a user to tweak the throughput of an ssd, but maybe i'm looking in the wrong place? https://cloud.google.com/compute/docs/disks/performance#performance_limits

Comment (pavelkalinnikov) [reply pkg/roachprod/vm/gce/gcloud.go:1013]: I was under impression that this was slightly configurable for the block storage.

I noticed the `provisioned-throughput` option in the [documentation](https://cloud.google.com/sdk/gcloud/reference/compute/instances/create#--create-disk) for the `--create-disk` command:

```
provisioned-throughput
	Indicates how much throughput to provision for the disk. This sets the number of throughput mb per
	second that the disk can handle.
```

There is one in `compute disks create` [command](https://cloud.google.com/sdk/gcloud/reference/compute/disks/create#--provisioned-throughput) too, but it mentions that this works only for [Hyperdisk Throughput](https://cloud.google.com/compute/docs/disks/hyperdisks) disks. So maybe that is the extent to which one can tune throughput in GCE.

Comment (pavelkalinnikov) [reply pkg/roachprod/vm/gce/gcloud.go:1015]: Extended the TODO with a documentation link.

File: pkg/cmd/roachtest/spec/cluster_spec.go [hunk 3]
```diff
@@ -67,12 +67,16 @@ type ClusterSpec struct {
...
-	SSDs                 int
-	RAID0                bool
-	VolumeSize           int
-	PreferLocalSSD       bool
+	CPUs           int
+	Mem            MemPerCPU
+	SSDs           int
+	RAID0          bool
+	VolumeSize     int
+	PreferLocalSSD bool
```
[the remark this answers is not in the document]
Comment (pavelkalinnikov) [reply pkg/cmd/roachtest/spec/cluster_spec.go]: Done.

File: pkg/cmd/roachtest/tests/restore.go (hunk 1 above)
Comment (pavelkalinnikov) [reply pkg/cmd/roachtest/tests/restore.go]: Renamed to `AWSVolumeThroughput`, to make it similar to `VolumeSize`, and to avoid the `AWSEBS` abbreviation hell.

**Review by pav-kv — COMMENTED** [review]
@msbutler Addressed comments, PTAL.

File: pkg/cmd/roachtest/tests/restore.go [hunk 4]
```diff
@@ -885,7 +898,7 @@ func (rd *restoreDriver) initRestorePerfMetrics(
 		// compute throughput as MB / node / second.
 		du := dut.GetDiskUsage(ctx, rd.c.All())
 		throughput := float64(du-startDu) / (float64(rd.sp.hardware.nodes) * testDuration)
-		rd.t.L().Printf("Usage %d , Nodes %d , Duration %f\n; Throughput: %f mb / node / second",
+		rd.t.L().Printf("Usage %d , Nodes %d , Duration %f\n; AWSVolumeThroughput: %f mb / node / second",
```
Comment (msbutler) [inline pkg/cmd/roachtest/tests/restore.go:901]: nit: I think your find+replace accidentally changed this

File: pkg/cmd/roachtest/tests/cdc_stats.go [hunk 5]
```diff
@@ -28,7 +28,7 @@ var (
 	changefeedThroughputAgg = clusterstats.AggQuery{
 		Stat:  changefeedThroughput,
 		Query: "sum(rate(changefeed_emitted_bytes[1m]) / (1000 * 1000))",
-		Tag:   "Throughput (MBps)",
```
Comment (msbutler) [inline pkg/cmd/roachtest/tests/cdc_stats.go:31]: nit: this shouldn't have changed.

File: pkg/roachprod/vm/aws/aws.go [hunk 6]
```diff
@@ -100,7 +100,7 @@ type ebsDisk struct {
 	VolumeType          string `json:"VolumeType"`
 	VolumeSize          int    `json:"VolumeSize"`
 	IOPs                int    `json:"Iops,omitempty"`
-	Throughput          int    `json:"Throughput,omitempty"`
```
Comment (msbutler) [inline pkg/roachprod/vm/aws/aws.go:103]: i suspect these shouldn't have changed, but i'm unsure

File: pkg/roachprod/vm/gce/gcloud.go (hunk 2 above)
Comment (msbutler) [reply pkg/roachprod/vm/gce/gcloud.go:1015]: makes sense. thanks for the explanation!

File: pkg/cmd/roachtest/tests/cdc_stats.go (hunk 5 above)
Comment (pavelkalinnikov) [reply pkg/cmd/roachtest/tests/cdc_stats.go]: Ouch. Fixed here and in other places.

File: pkg/cmd/roachtest/tests/restore.go (hunk 4 above)
Comment (pavelkalinnikov) [reply pkg/cmd/roachtest/tests/restore.go]: Yes.

**Review by msbutler — APPROVED** [review]
perhaps its worth doing a quick ad hoc roachtest startup ( i.e. run the test for 5 minutes then destroy it) to ensure the expected behavior.

**Comment by pavelkalinnikov** [comment]
@msbutler Done. The test does what I expected.
