### PR TITLE
tree: introduce concept of "default" collation

### LINKED ISSUE #54989: sql: pg_attribute table lacks the notion of a 'default' collation
**Describe the problem**

Unlike PostgreSQL, CockroachDB reports a column's collation, even if none is given when creating the column.

**To Reproduce**

```sql
CREATE TABLE test (name VARCHAR(255) NOT NULL);
SELECT
    a.attname AS column_name,
    NOT (a.attnotnull OR (t.typtype = 'd' AND t.typnotnull)) AS is_nullable,
    pg_get_expr(ad.adbin, ad.adrelid) AS column_default,
    CASE WHEN collname = 'default' THEN NULL ELSE collname END AS collation
FROM pg_attribute a
LEFT JOIN pg_attrdef ad ON a.attrelid = ad.adrelid AND a.attnum = ad.adnum
LEFT JOIN pg_collation co ON a.attcollation = co.oid
JOIN pg_type t ON a.atttypid = t.oid
JOIN pg_class c ON a.attrelid = c.oid
JOIN pg_namespace n ON c.relnamespace = n.oid
WHERE c.relkind IN ('f', 'm', 'p', 'r', 'v')
    AND c.relname = 'test'
    AND n.nspname NOT IN ('pg_catalog', 'pg_toast')
    AND pg_catalog.pg_table_is_visible(c.oid);

  column_name | is_nullable | column_default | collation
--------------+-------------+----------------+------------
  name        |    false    | NULL           | en-US
  rowid       |    false    | unique_rowid() | NULL
```

**Expected behavior**

collation for the `name` column should be NULL rather than `en-US`.

**Environment:**
 - CockroachDB version v20.2.0-alpha.1-3651-g1be3227203 @ 2020/09/26 05:50:03

**Additional context**

Django 3.2 adds support for column collations. This causes Django's `inspectdb` utility to add the `db_collation` option to all  `CharField`s. If this behavior can't or won't change, a workaround in the `django-cockroachdb` adapter may be possible by modifying the `CASE WHEN collname = 'default'` SQL with a retrieval of the default collation.

### PR DESCRIPTION
**Pull request by otan**
Resolves https://github.com/cockroachdb/cockroach/issues/54989

Release note (sql change): Introduced a pg_collation of "default".
Strings now return the "default" collation OID in the pg_attribute
table (this was previously en_US). The "default" collation is also
visible on the pg_collation virtual table.

### CODE REVIEW

File: pkg/sql/logictest/testdata/logic_test/pg_catalog [hunk 1]
```diff
@@ -1358,14 +1358,14 @@ ORDER BY oid
 oid     typname        typndims  typcollation  typdefaultbin  typdefault  typacl
 16      bool           0         0             NULL           NULL        NULL
 17      bytea          0         0             NULL           NULL        NULL
-18      char           0         3903121477    NULL           NULL        NULL
-19      name           0         3903121477    NULL           NULL        NULL
+18      char           0         3403232968    NULL           NULL        NULL
```
Comment (rafiss) [inline pkg/sql/logictest/testdata/logic_test/pg_catalog:1361]: seems like `char` in PG has a typcollation of 0

File: pkg/sql/logictest/testdata/logic_test/pg_catalog [hunk 2]
```diff
@@ -1358,14 +1358,14 @@ ORDER BY oid
...
+19      name           0         3403232968    NULL           NULL        NULL
```
Comment (rafiss) [inline pkg/sql/logictest/testdata/logic_test/pg_catalog:1362]: `name` has a collation of `C` in PG

???

File: pkg/sql/sem/tree/create.go [hunk 3]
```diff
@@ -460,15 +460,21 @@ func NewColumnTableDef(
...
-			}
-			collatedTyp, err := processCollationOnType(name, d.Type, t)
-			if err != nil {
-				return nil, err
+			// In postgres, all strings have collations defaulting to "default".
+			// In CRDB, collated strings are treated separately to string family types.
+			// To most behave like postgres, set the CollatedString type if a non-"default"
+			// collation is used.
+			if locale != DefaultCollationTag {
+				_, err := language.Parse(locale)
```
Comment (rafiss) [inline pkg/sql/sem/tree/create.go:468]: so i guess here would be the place where we could normalize the collation name using `lex.EncodeLocaleName`. do you think we should do that?

(either in this PR, or at any point?)

**Review by rafiss — COMMENTED** [review]
lgtm -- but wondering about `char` and `name`

File: pkg/sql/sem/tree/create.go (hunk 3 above)
Comment (otan) [reply pkg/sql/sem/tree/create.go:468]: yeah, as well as change all `language.Parse` calls to ensure it does this appropriately...

File: pkg/sql/logictest/testdata/logic_test/pg_catalog (hunk 1 above)
Comment (otan) [reply pkg/sql/logictest/testdata/logic_test/pg_catalog:1361]: hmm, i think this is a separate issue in that this is what pg_type reports, which is different.
i think that's a separate issue. we currently base this column on the collation of the type...

File: pkg/sql/logictest/testdata/logic_test/pg_catalog (hunk 2 above)
Comment (otan) [reply pkg/sql/logictest/testdata/logic_test/pg_catalog:1362]: yeah i think that makes sense as name is an internal thing isn't it? either way we don't have C, so i think we can leave this as is

File: pkg/sql/sem/tree/create.go (hunk 3 above)
Comment (otan) [reply pkg/sql/sem/tree/create.go:468]: yeah, that sounds about right. maybe somewhere with alter column type as well.
maybe in general we shouldn't use language.Parse but write our own wrapper around it.

**Comment by otan** [comment]
char and name seems like an existing problem based on the type descriptor -- so i'm going to ignore this for now.

https://github.com/cockroachdb/cockroach/blob/master/pkg/sql/pg_catalog.go#L2276

going to leave this to another issue.

TFTR!

bors r=rafiss

**Review by rafiss — APPROVED** [review]
