### PR TITLE
sql: anonymize custom type names if FmtAnonymize is set

### LINKED ISSUE #60674: sql: the names of custom SQL types are not properly anonymized
Found while investigating #60676

The following statement:

```
SELECT 1::schem.typ
```

must render as

```
SELECT 1::_._
```

under FmtAnonymize

otherwise we are reporting potentially sensitive customer data through telemetry and crash reports.

### PR DESCRIPTION
**Pull request by rafiss**
fixes #60674 

Release note (bug fix): The names of custom types are no longer sent to
Cockroach Labs in telemetry and crash reports.

Release justification: Low risk, high benefit change that is important
for keeping PII private.

### CODE REVIEW

File: pkg/sql/sem/tree/type_name.go [hunk 1]
```diff
@@ -180,21 +182,35 @@ func ResolveType(
...
-		switch t := ref.(type) {
-		case *types.T:
-			if t.UserDefined() {
+	switch t := ref.(type) {
+	case *types.T:
+		if t.UserDefined() {
+			if ctx.HasFlags(FmtAnonymize) {
+				ctx.WriteByte('_')
+				return
+			}
```
Comment (knz) [inline pkg/sql/sem/tree/type_name.go:191]: don't you need an else here?

Comment (rafiss) [reply pkg/sql/sem/tree/type_name.go:191]: well the previous case short-circuits, but i can add an else

**Review by RichardJCai — COMMENTED** [review]
LGTM 

Logic looks much cleaner in one switch statement, thanks.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/60806#-:-MV3K_ZV27q-gw7JZ5jx:b-g7534v)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @knz)

**Review by RichardJCai — APPROVED** [review]

**Comment by rafiss** [comment]
thank you!

bors r=RichardJCai
