### PR TITLE
sql: avoid panic for notices in internal executor

### LINKED ISSUE #94344: sql: cursors which buffer notices panic
**Describe the problem**

When we try buffer a notice for a cursor, we panic. This should probably no-op instead (or forward the notice through).

**To Reproduce**

Run
```
BEGIN; declare a cursor for select * from crdb_internal.gossip_network;
```

You'll see:
```

*
* ERROR: a panic has occurred!
* panic: unimplemented
* (1) attached stack trace
*   -- stack trace:
*   | runtime.gopanic
*   | 	GOROOT/src/runtime/panic.go:884
*   | github.com/cockroachdb/cockroach/pkg/sql.(*streamingCommandResult).BufferNotice
*   | 	github.com/cockroachdb/cockroach/pkg/sql/conn_io.go:943
*   | github.com/cockroachdb/cockroach/pkg/sql.(*planner).BufferClientNotice
*   | 	github.com/cockroachdb/cockroach/pkg/sql/notice.go:55
*   | github.com/cockroachdb/cockroach/pkg/sql.glob..func72
*   | 	github.com/cockroachdb/cockroach/pkg/sql/crdb_internal.go:4410
*   | github.com/cockroachdb/cockroach/pkg/sql.(*virtualDefEntry).getPlanInfo.func1.1
*   | 	github.com/cockroachdb/cockroach/pkg/sql/virtual_schema.go:638
*   | github.com/cockroachdb/cockroach/pkg/sql.setupGenerator.func3
*   | 	github.com/cockroachdb/cockroach/pkg/sql/virtual_table.go:127
*   | github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunAsyncTaskEx.func2
*   | 	github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:470
*   | runtime.goexit
*   | 	GOROOT/src/runtime/asm_arm64.s:1172
* Wraps: (2) panic: unimplemented
* Error types: (1) *withstack.withStack (2) *errutil.leafError
*
panic: unimplemented [recovered]
	panic: unimplemented

```

CockroachDB then panics and dies.

Jira issue: CRDB-22841

### PR DESCRIPTION
**Pull request by rafiss**
fixes https://github.com/cockroachdb/cockroach/issues/94344

Release note (bug fix): Fixed a panic that could be caused when using a SQL cursor to access tables in the crdb_internal schema.

### CODE REVIEW

File: pkg/sql/conn_io.go [hunk 1]
```diff
@@ -935,12 +935,12 @@ func (r *streamingCommandResult) SetColumns(ctx context.Context, cols colinfo.Re
...
 // BufferParamStatusUpdate is part of the RestrictedCommandResult interface.
 func (r *streamingCommandResult) BufferParamStatusUpdate(key string, val string) {
-	panic("unimplemented")
+	// Unimplemented: the internal executor does not support status updated.
 }
 
 // BufferNotice is part of the RestrictedCommandResult interface.
 func (r *streamingCommandResult) BufferNotice(notice pgnotice.Notice) {
-	panic("unimplemented")
+	// Unimplemented: the internal executor does not support notices.
```
Comment (otan) [inline pkg/sql/conn_io.go:943]: we still kind of want the notices to be sent down though still someday right? idk if worth an issue.

**Review by otan — APPROVED** [review]

File: pkg/sql/conn_io.go (hunk 1 above)
Comment (rafiss) [reply pkg/sql/conn_io.go:943]: filed https://github.com/cockroachdb/cockroach/issues/94437

**Comment by rafiss** [comment]
tftr!

bors r=otan
