### PR TITLE
roachtest: deflake replicagc-changed-peers

### LINKED ISSUE #98966: roachtest: replicagc-changed-peers/restart=false failed
roachtest.replicagc-changed-peers/restart=false [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/9136340?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/9136340?buildTab=artifacts#/replicagc-changed-peers/restart=false) on release-22.2 @ [73df0dc428ff1e516c5b11a7ca1930e3339da118](https://github.com/cockroachdb/cockroach/commits/73df0dc428ff1e516c5b11a7ca1930e3339da118):

```
test artifacts and logs in: /artifacts/replicagc-changed-peers/restart=false/run_1
(replicagc.go:286).waitForZeroReplicasOnN3: ranges remained on n3 (according to meta2): map[19:{3,5,6} 31:{3,5,6} 48:{3,5,6} 50:{3,4,6} 77:{3,4,6} 83:{3,5,6} 89:{3,5,6} 97:{3,4,6} 121:{3,4,6}]
```
<p>Parameters: <code>ROACHTEST_cloud=gce</code>
, <code>ROACHTEST_cpu=4</code>
, <code>ROACHTEST_encrypted=false</code>
, <code>ROACHTEST_ssd=0</code>
</p>
<details><summary>Help</summary>
<p>

See: [roachtest README](https://github.com/cockroachdb/cockroach/blob/master/pkg/cmd/roachtest/README.md)

See: [How To Investigate \(internal\)](https://cockroachlabs.atlassian.net/l/c/SSSBr8c7)

</p>
</details>
/cc @cockroachdb/replication
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*replicagc-changed-peers/restart=false.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)
</sub>

Jira issue: CRDB-25629

### PR DESCRIPTION
**Pull request by aliher1911**
Test doesn't give enough time for allocator to see that node is dead and move replicas from killed node. This PR changes retry timeout and interval and adds extra logging for visibility.

Release note: None

Fixes #98966

### CODE REVIEW

**Comment by aliher1911** [comment]
Let's fix master and backport to branch where actual test failure happened. Change seem applicable to both.

File: pkg/cmd/roachtest/tests/replicagc.go [hunk 1]
```diff
@@ -62,7 +62,10 @@ func runReplicaGCChangedPeers(
 
 	c.Put(ctx, t.Cockroach(), "./cockroach")
 	c.Put(ctx, t.DeprecatedWorkload(), "./workload", c.Node(1))
-	settings := install.MakeClusterSettings(install.EnvOption([]string{"COCKROACH_SCAN_MAX_IDLE_TIME=5ms"}))
+	settings := install.MakeClusterSettings(install.EnvOption([]string{
+		"COCKROACH_SCAN_MAX_IDLE_TIME=5ms",
```
Comment (tbg) [inline pkg/cmd/roachtest/tests/replicagc.go:66]: drive-by:

`COCKROACH_SCAN_MAX_IDLE_TIME` "should" imply a ScanInterval of `num_replicas* max_idle_time * avg_processing_duration`, shouldn't it? At least that's what the comment[^1] suggests. So is this not working as advertised?

[^1]: https://github.com/cockroachdb/cockroach/blob/58004827905fbec8926a51ea6f751823b1991fa4/pkg/server/config.go#L415-L419

Comment (aliher1911) [reply pkg/cmd/roachtest/tests/replicagc.go:66]: You are right, I'm still running tests locally to see how behaviour changes. Created a PR speculatively.
Something is preventing any moves from happening for 5 minutes so it seems at least now that I added logging on each replica count check attempt.

Comment (aliher1911) [reply pkg/cmd/roachtest/tests/replicagc.go:66]: Funny thing... `COCKROACH_SCAN_MAX_IDLE_TIME` is only applied to first 3 nodes, but nodes doing rebalancing are the second set of nodes which start without any options. So maybe that's the cause.

**Review by tbg — APPROVED** [review]

**Comment by aliher1911** [comment]
bors r=tbg

**Comment by erikgrinaker** [comment]
blathers backport 23.1
