### PR TITLE
release-23.2: changefeedccl: Avoid logging when context may be canceled

### LINKED ISSUE #114130: ccl/changefeedccl: TestChangefeedNemeses failed
ccl/changefeedccl.TestChangefeedNemeses [failed](https://tanzanite.cluster.engflow.com/invocation/485553d2-82cc-4eb4-865f-1928c5443d65) on master @ [e174990dd5015a38b1e9bc6723f270dbe647c3a3](https://github.com/cockroachdb/cockroach/commits/e174990dd5015a38b1e9bc6723f270dbe647c3a3):

```
=== RUN   TestChangefeedNemeses
    test_log_scope.go:170: test logs captured to: outputs.zip/logTestChangefeedNemeses704209802
    test_log_scope.go:81: use -show-logs to present logs inline
=== RUN   TestChangefeedNemeses/webhook
    helpers_test.go:853: making server as system tenant
    helpers_test.go:928: making webhook feed factory
    nemeses_test.go:32: random seed: -8324793835391516166
panic: use of Span after Finish. Span: changefntr. Finish previously called at: <stack not captured. Set debugUseAfterFinish>

goroutine 96003 [running]:
github.com/cockroachdb/cockroach/pkg/util/tracing.(*Span).detectUseAfterFinish(0xbd8d640?)
	github.com/cockroachdb/cockroach/pkg/util/tracing/span.go:182 +0x114
github.com/cockroachdb/cockroach/pkg/util/tracing.(*Span).RecordingType(0xc00ba18000)
	github.com/cockroachdb/cockroach/pkg/util/tracing/span.go:442 +0x18
github.com/cockroachdb/cockroach/pkg/util/tracing.(*Span).IsVerbose(...)
	github.com/cockroachdb/cockroach/pkg/util/tracing/span.go:450
github.com/cockroachdb/cockroach/pkg/util/log.getSpanOrEventLog({0x7bbb530, 0xc008d45540})
	github.com/cockroachdb/cockroach/pkg/util/log/trace.go:92 +0x34
github.com/cockroachdb/cockroach/pkg/util/log.logfDepthInternal({0x7bbb530, 0xc008d45540}, 0x2, 0x3, 0x0, 0x3?, {0x64f156c, 0x21}, {0xc005927c70, 0x1, ...})
	github.com/cockroachdb/cockroach/pkg/util/log/channels.go:104 +0x4b4
github.com/cockroachdb/cockroach/pkg/util/log.logfDepth(...)
	github.com/cockroachdb/cockroach/pkg/util/log/channels.go:39
github.com/cockroachdb/cockroach/pkg/util/log.Errorf(...)
	github.com/cockroachdb/cockroach/bazel-out/k8-fastbuild/bin/pkg/util/log/log_channels_generated.go:654
github.com/cockroachdb/cockroach/pkg/ccl/changefeedccl.(*batchingSink).runBatchingWorker(0xc0117c8e00, {0x7bbb530, 0xc008d45540})
	github.com/cockroachdb/cockroach/pkg/ccl/changefeedccl/batching_sink.go:404 +0x58f
github.com/cockroachdb/cockroach/pkg/ccl/changefeedccl.makeBatchingSink.func1({0x7bbb530?, 0xc008d45540?})
	github.com/cockroachdb/cockroach/pkg/ccl/changefeedccl/batching_sink.go:514 +0x2a
github.com/cockroachdb/cockroach/pkg/ccl/changefeedccl.makeBatchingSink.Group.GoCtx.func2()
	github.com/cockroachdb/cockroach/pkg/util/ctxgroup/ctxgroup.go:168 +0x22
golang.org/x/sync/errgroup.(*Group).Go.func1()
	golang.org/x/sync/errgroup/external/org_golang_x_sync/errgroup/errgroup.go:75 +0x56
created by golang.org/x/sync/errgroup.(*Group).Go in goroutine 95979
	golang.org/x/sync/errgroup/external/org_golang_x_sync/errgroup/errgroup.go:72 +0x96
```
<p>Parameters: <code>attempt=1</code>
, <code>run=17</code>
, <code>shard=13</code>
</p>
<details><summary>Help</summary>
<p>

See also: [How To Investigate a Go Test Failure \(internal\)](https://cockroachlabs.atlassian.net/l/c/HgfXfJgM)
</p>
</details>
/cc @cockroachdb/cdc
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*TestChangefeedNemeses.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)
</sub>

Jira issue: CRDB-33359

### LINKED ISSUE #141917: ccl/changefeedccl: TestTableNameCollision failed
ccl/changefeedccl.TestTableNameCollision [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_StressBazel/18912936?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_StressBazel/18912936?buildTab=artifacts#/) on release-23.2 @ [333a1ca8e2803b38d71278a4d9f37144ebf29db9](https://github.com/cockroachdb/cockroach/commits/333a1ca8e2803b38d71278a4d9f37144ebf29db9):

Fatal error:

```
panic: use of Span after Finish. Span: changefntr. Finish previously called at: goroutine 2021533 [running]:
runtime/debug.Stack()
	GOROOT/src/runtime/debug/stack.go:24 +0x5e
github.com/cockroachdb/cockroach/pkg/util/tracing.(*Span).finishInternal(0xc004abfc00)
	github.com/cockroachdb/cockroach/pkg/util/tracing/span.go:251 +0x67
github.com/cockroachdb/cockroach/pkg/util/tracing.(*Span).Finish(...)
	github.com/cockroachdb/cockroach/pkg/util/tracing/span.go:242
github.com/cockroachdb/cockroach/pkg/sql/execinfra.(*ProcessorBaseNoHelper).InternalClose(0xc010713800)
	github.com/cockroachdb/cockroach/pkg/sql/execinfra/processorsbase.go:918 +0xb5
github.com/cockroachdb/cockroach/pkg/ccl/changefeedccl.(*changeFrontier).close(0xc010713800)
	github.com/cockroachdb/cockroach/pkg/ccl/changefeedccl/changefeed_processors.go:1442 +0x45
github.com/cockroachdb/cockroach/pkg/ccl/changefeedccl.(*changeFrontier).ConsumerClosed(0xc00f134e00?)
	github.com/cockroachdb/cockroach/pkg/ccl/changefeedccl/changefeed_processors.go:1901 +0x13
github.com/cockroachdb/cockroach/pkg/sql/execinfra.Run({0x7db5af8, 0xc006dac000}, {0x7dd7240, 0xc010713800}, {0x7d7efe0?, 0xc00f134e00?})
	github.com/cockroachdb/cockroach/pkg/sql/execinfra/base.go:204 +0xa4
github.com/cockroachdb/cockroach/pkg/sql/execinfra.(*ProcessorBaseNoHelper).Run(0xc010713800, {0x7db5ac0?, 0xc01f31f7c0?}, {0x7d7efe0?, 0xc00f134e00})
	github.com/cockroachdb/cockroach/pkg/sql/execinfra/processorsbase.go:721 +0x6d
github.com/cockroachdb/cockroach/pkg/sql/flowinfra.(*FlowBase).Run(0xc00bdcf900, {0x7db5ac0?, 0xc01f31f7c0}, 0x0?)
	github.com/cockroachdb/cockroach/pkg/sql/flowinfra/flow.go:574 +0x222
github.com/cockroachdb/cockroach/pkg/sql.(*DistSQLPlanner).Run(0xc0164f9400, {0x7db5ac0, 0xc01f31f720}, 0xc011d2b440, 0x0, 0xc007804b80, 0xc00f134e00, 0xc010713000, 0xc0126a9f18)
	github.com/cockroachdb/cockroach/pkg/sql/distsql_running.go:914 +0xb9e
github.com/cockroachdb/cockroach/pkg/ccl/changefeedccl.startDistChangefeed.func1({0x7db5ac0, 0xc01f31f5e0})
	github.com/cockroachdb/cockroach/pkg/ccl/changefeedccl/changefeed_dist.go:316 +0x408
github.com/cockroachdb/cockroach/pkg/util/ctxgroup.GoAndWait.Group.GoCtx.func1()
	github.com/cockroachdb/cockroach/pkg/util/ctxgroup/ctxgroup.go:163 +0x22
golang.org/x/sync/errgroup.(*Group).Go.func1()
	golang.org/x/sync/errgroup/external/org_golang_x_sync/errgroup/errgroup.go:78 +0x56
created by golang.org/x/sync/errgroup.(*Group).Go in goroutine 2021022
	golang.org/x/sync/errgroup/external/org_golang_x_sync/errgroup/errgroup.go:75 +0x96


```
Stack: 

```
goroutine 2021345 [running]:
github.com/cockroachdb/cockroach/pkg/util/tracing.(*Span).detectUseAfterFinish(0xbe9a660?)
	github.com/cockroachdb/cockroach/pkg/util/tracing/span.go:177 +0x114
github.com/cockroachdb/cockroach/pkg/util/tracing.(*Span).RecordingType(0xc004abfc00)
	github.com/cockroachdb/cockroach/pkg/util/tracing/span.go:437 +0x18
github.com/cockroachdb/cockroach/pkg/util/tracing.(*Span).IsVerbose(...)
	github.com/cockroachdb/cockroach/pkg/util/tracing/span.go:445
github.com/cockroachdb/cockroach/pkg/util/log.getSpanOrEventLog({0x7db5ac0, 0xc00b83d360})
	github.com/cockroachdb/cockroach/pkg/util/log/trace.go:87 +0x34
github.com/cockroachdb/cockroach/pkg/util/log.logfDepthInternal({0x7db5ac0, 0xc00b83d360}, 0x2, 0x3, 0x0, 0x3?, {0x66e597a, 0x21}, {0xc00a9e9ca0, 0x1, ...})
	github.com/cockroachdb/cockroach/pkg/util/log/channels.go:99 +0x4b4
github.com/cockroachdb/cockroach/pkg/util/log.logfDepth(...)
	github.com/cockroachdb/cockroach/pkg/util/log/channels.go:34
github.com/cockroachdb/cockroach/pkg/util/log.Errorf(...)
	github.com/cockroachdb/cockroach/bazel-out/k8-fastbuild/bin/pkg/util/log/log_channels_generated.go:654
github.com/cockroachdb/cockroach/pkg/ccl/changefeedccl.(*batchingSink).runBatchingWorker(0xc01608e0e0, {0x7db5ac0?, 0xc00b83d360})
	github.com/cockroachdb/cockroach/pkg/ccl/changefeedccl/batching_sink.go:434 +0x5cf
github.com/cockroachdb/cockroach/pkg/ccl/changefeedccl.makeBatchingSink.func1({0x7db5ac0?, 0xc00b83d360?})
	github.com/cockroachdb/cockroach/pkg/ccl/changefeedccl/batching_sink.go:544 +0x2a
github.com/cockroachdb/cockroach/pkg/ccl/changefeedccl.makeBatchingSink.Group.GoCtx.func2()
	github.com/cockroachdb/cockroach/pkg/util/ctxgroup/ctxgroup.go:163 +0x22
golang.org/x/sync/errgroup.(*Group).Go.func1()
	golang.org/x/sync/errgroup/external/org_golang_x_sync/errgroup/errgroup.go:78 +0x56
created by golang.org/x/sync/errgroup.(*Group).Go in goroutine 2021533
	golang.org/x/sync/errgroup/external/org_golang_x_sync/errgroup/errgroup.go:75 +0x96
```
<details><summary>Log preceding fatal error</summary>
<p>

```
=== RUN   TestTableNameCollision
    test_log_scope.go:165: test logs captured to: /artifacts/tmp/_tmp/905465f697dc04c39f7d8a82cb057bfe/logTestTableNameCollision1206430527
    test_log_scope.go:76: use -show-logs to present logs inline
=== RUN   TestTableNameCollision/kafka
    helpers_test.go:873: making server as system tenant
    helpers_test.go:948: making kafka feed factory
    testfeed_test.go:300: creating external connection
    testfeed_test.go:303: ran create external connection
    testfeed_test.go:300: creating external connection
    testfeed_test.go:303: ran create external connection
    testfeed_test.go:300: creating external connection
    testfeed_test.go:303: ran create external connection
```
</p>
</details>

Parameters:
 - <code>TAGS=bazel,gss</code>
 - <code>stress=true</code>
<details><summary>Help</summary>
<p>

See also: [How To Investigate a Go Test Failure \(internal\)](https://cockroachlabs.atlassian.net/l/c/HgfXfJgM)
</p>
</details>
/cc @cockroachdb/cdc
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*TestTableNameCollision.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)
</sub>

Jira issue: CRDB-48074

### PR DESCRIPTION
**Pull request by andyyang890**
Backport 1/1 commits from #114583.

/cc @cockroachdb/release

---

Calling log  methods on a context that's already canceled may produce "use of Span after Finish" under tests. Avoid doing that when pacing CPU usage.

Fixes #114130

Release note: None

---

Release justification: removes a use of Span after Finish 

---

Fixes #141917

### CODE REVIEW

File: pkg/ccl/changefeedccl/batching_sink.go [hunk 1]
```diff
@@ -429,11 +428,12 @@ func (s *batchingSink) runBatchingWorker(ctx context.Context) {
 	for {
 		select {
 		case req := <-s.eventCh:
-			if err := s.pacer.Pace(ctx); err != nil {
-				if !errors.Is(err, context.Canceled) && pacerLogEvery.ShouldLog() {
```
Comment (asg0451) [inline pkg/ccl/changefeedccl/batching_sink.go:433]: this line already doesn't log if the context is canceled right? are you sure this change is needed

Comment (andyyang890) [reply pkg/ccl/changefeedccl/batching_sink.go:433]: It caused this test to fail: #141917.

In my local testing, the error it gets is:
```
automatic sink batcher pacing: deadline expired while waiting in queue: kv-elastic-cpu-queue, pri: bulk-normal-pri, deadline: 0001-01-01 00:00:00 +0000 UTC, start: 2025-02-
28 05:38:12.288746338 +0000 UTC m=+117.150482568, dur: 2.381637697s
```

**Review by asg0451 — APPROVED** [review]
