### PR TITLE
roachtest: fix TestVMPreemptionPolling data race

### LINKED ISSUE #135267: cmd/roachtest: TestVMPreemptionPolling failed
cmd/roachtest.TestVMPreemptionPolling [failed](https://tanzanite.cluster.engflow.com/invocations/default/52ea7b51-f16e-42ff-97c5-513b6ff0eee6?testReportRun=1&testReportShard=1&testReportAttempt=1#targets-Ly9wa2cvY21kL3JvYWNodGVzdDpyb2FjaHRlc3RfdGVzdA==) on master @ [7d943e9c3875319fe2dc35981c8385c16eb7ee27](https://github.com/cockroachdb/cockroach/commits/7d943e9c3875319fe2dc35981c8385c16eb7ee27):

```
=== RUN   TestVMPreemptionPolling
=== RUN   TestVMPreemptionPolling/polling_cancels_test
2024/11/15 12:57:01 test_runner.go:373: test_run_id: test_user-1731675421
2024/11/15 12:57:01 test_runner.go:534: Creating new cluster for test preemption: n0cpu4 (arch="amd64")
2024/11/15 12:57:01 test_runner.go:434: PASS
=== RUN   TestVMPreemptionPolling/polling_doesn't_catch_preemption
==================
WARNING: DATA RACE
Write at 0x0000146c1b28 by goroutine 745:
  github.com/cockroachdb/cockroach/pkg/cmd/roachtest.TestVMPreemptionPolling.func5()
      pkg/cmd/roachtest/test_test.go:754 +0x84
  testing.tRunner()
      GOROOT/src/testing/testing.go:1689 +0x21e
  testing.(*T).Run.gowrap1()
      GOROOT/src/testing/testing.go:1742 +0x44

Previous read at 0x0000146c1b28 by goroutine 741:
  github.com/cockroachdb/cockroach/pkg/cmd/roachtest.monitorForPreemptedVMs.func1()
      pkg/cmd/roachtest/test_runner.go:2148 +0x9b

Goroutine 745 (running) created at:
  testing.(*T).Run()
      GOROOT/src/testing/testing.go:1742 +0x825
  github.com/cockroachdb/cockroach/pkg/cmd/roachtest.TestVMPreemptionPolling()
      pkg/cmd/roachtest/test_test.go:752 +0xb73
  testing.tRunner()
      GOROOT/src/testing/testing.go:1689 +0x21e
  testing.(*T).Run.gowrap1()
      GOROOT/src/testing/testing.go:1742 +0x44

Goroutine 741 (finished) created at:
  github.com/cockroachdb/cockroach/pkg/cmd/roachtest.monitorForPreemptedVMs()
      pkg/cmd/roachtest/test_runner.go:2143 +0x25a
  github.com/cockroachdb/cockroach/pkg/cmd/roachtest.(*testRunner).runTest.func2()
      pkg/cmd/roachtest/test_runner.go:1305 +0x1a4
==================
```

Parameters:
 - <code>attempt=1</code>
 - <code>race=true</code>
 - <code>run=1</code>
 - <code>shard=1</code>
<details><summary>Help</summary>
<p>

See also: [How To Investigate a Go Test Failure \(internal\)](https://cockroachlabs.atlassian.net/l/c/HgfXfJgM)
</p>
</details>
/cc @cockroachdb/test-eng
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*TestVMPreemptionPolling.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/bazci/githubpost/issues)

</sub>

Jira issue: CRDB-44427

### PR DESCRIPTION
**Pull request by DarrylWong**
This change switches to pollPreemptionInterval to be a mutex protected struct instead, as multiple unit tests modify it and can lead to a data race without.

Fixes: #135267
Epic: none
Release note: none

### CODE REVIEW

**Review by srosenberg — APPROVED** [review]

File: pkg/cmd/roachtest/test_runner.go [hunk 1]
```diff
@@ -2139,13 +2139,14 @@ func monitorForPreemptedVMs(ctx context.Context, t test.Test, c cluster.Cluster,
 	if c.IsLocal() || !c.Spec().UseSpotVMs {
 		return
 	}
+	interval := pollPreemptionInterval
```
Comment (srosenberg) [inline pkg/cmd/roachtest/test_runner.go:2142]: I was going to mention we might need a mutex on the previous PR. In general, when there are multiple hooks (for mocking), it might be best to stick them in a mutex-protected struct. That aside, I'm a bit puzzled by the data race in [1]. The subtests are executed _sequentially_, which btw you'd still have a race, if `t.Parallel()` is enabled. The write on L754 races with the read of the _previous_ subtest, right? That would imply that the `runCtx` passed into `monitorForPreemptedVMs` wasn't cancelled upon completion. If that's the case, we have a leaking goroutine.

[1] https://github.com/cockroachdb/cockroach/issues/135267

Comment (DarrylWong) [reply pkg/cmd/roachtest/test_runner.go:2142]: Ah yes, I was going to but forgot to leave a comment saying something along the lines of "I'm not really sure how this fixes the data race because I'm not 100% what the data race is".

>That would imply that the runCtx passed into monitorForPreemptedVMs wasn't cancelled upon completion. If that's the case, we have a leaking goroutine.

That was my initial thought too, but I commented out the first of the two tests and was *still* getting the data race. Even weirder is that when both tests are running, the data race always happens on the second. That would suggest it is reliant on both tests running but it isn't. To further add to that, commenting the second test causes the first to start failing with a data race.

I also tried adding a `defer leaktest.AfterTest` which didn't catch anything.

Comment (srosenberg) [reply pkg/cmd/roachtest/test_runner.go:2142]: We both missed an essential hint in the data race report–`Goroutine 741 (finished)`. At the time when the data race report is printed [1], the goroutine running `monitorForPreemptedVMs` has already exited. This confirms that the `runCtx` is indeed cancelled. 

We can also conclude that it's the `write` of the _second_ subtest which races with the `read` of the _first_ subtest. The sequence of (scheduled) events is roughly as follows. The goroutine of the first subtest exits _before_ `monitorForPreemptedVMs` exits; at this point, `tsan` has recorded a read from the corresponding goroutine id. Next, the goroutine for the second subtest is executed; `tsan` records the write. A data race is detected. Subsequently, `monitorForPreemptedVMs` exits. The reporter iterates through the implicated goroutines, printing the stack traces, at which point `Goroutine 741` already finished :)

Your fix works because the read in `monitorForPreemptedVMs` must _happen before_ the first subtest goroutine exits, and transitively it _happens before_ the second subtest does the write. `s.Run` essentially establishes the happens-before order; from `runTest`,

```
monitorForPreemptedVMs(runCtx, t, c, l)
// This is the call to actually run the test.
s.Run(runCtx, t, c)
```

Thus, the only read in `monitorForPreemptedVMs` now happens before `s.Run` exits, and by extension `runTest`.

> Yeah, I thought of that but figured it would be unfortunate to have to add a mutex for a unit test only hook. I can go that route though if we think it's safer.

It might be a good idea since the reason the current fix works is rather non-trivial.

[1] https://github.com/llvm/llvm-project/blob/8c7c8eaa1933d24c1eb869ba85469908547e3677/compiler-rt/lib/tsan/rtl/tsan_report.cpp#L424

**Review by herkolategan — APPROVED** [review]

File: pkg/cmd/roachtest/test_runner.go (hunk 1 above)
Comment (DarrylWong) [reply pkg/cmd/roachtest/test_runner.go]: Ahh, yes I think that explanation checks out.

> but I commented out the first of the two tests and was still getting the data race.

I should've taken a closer look at the data race I was getting, it was due to the defer statement which would fail under race for the same reason, but explains why it was failing with only one subtest running.

>It might be a good idea since the reason the current fix works is rather non-trivial.

Done.

File: pkg/cmd/roachtest/test_runner.go [hunk 2]
```diff
@@ -2132,20 +2132,33 @@ var getPreemptedVMsHook = func(c cluster.Cluster, ctx context.Context, l *logger
...
 	if c.IsLocal() || !c.Spec().UseSpotVMs {
 		return
 	}
 
+	pollPreemptionInterval.Lock()
+	defer pollPreemptionInterval.Unlock()
+	interval := pollPreemptionInterval.interval
+	// If no interval is set, default to 5 minutes.
+	if interval == 0 {
+		interval = 5 * time.Minute
```
Comment (srosenberg) [inline pkg/cmd/roachtest/test_runner.go:2153]: This belongs in the `init` function; otherwise, it's not exactly isomorphic to the previous version; e.g., `interval` could be reset to 0 (by another thread).

**Review by srosenberg — APPROVED** [review]
LGTM, modulo a tiny init-related comment.

**Comment by DarrylWong** [comment]
TFTRs!

bors r=srosenberg, herkolategan
