### PR TITLE
roachtest: exit with failure on github post errors

### LINKED ISSUE #147116: roachtest: fail when github issuePoster returns an error
Currently, roachtest logs the error from `github.MaybePost` [1], but doesn't actually fail the run. In CI, this is a problem because a test failure may go unreported. Based on my preliminary check, of `test.log` of several dozen recent failures, there are no occurrences; i.e., it's rare, but we know that GH outages do happen from time to time.

In [2], we added logging to print the issue that was created or appended. Yet, we're missing an active alerting mechanism to detect "silent" issuePoster failures. Failing the run would also fail the CI job which is actively monitored by testeng.

[1] https://github.com/cockroachdb/cockroach/blob/3c6d38dc0498814b0862047bab029e2479bbefe6/pkg/cmd/roachtest/test_runner.go#L854-L855
[2] https://github.com/cockroachdb/cockroach/pull/118914

### PR DESCRIPTION
**Pull request by williamchoe3**
Fixes #147116
#### Highlevel Changes
Added a new failure path first by
* adding a new counter in `testRunner` struct which get's incremented when `github.MaybePost()` (called in `testRunner.runWorkers()` and `testRunner.runTests()` )returns an error. When this count > 0,  `testRunner.Run()` will return a new error `errGithubPostFailed` and when `main()` sees that error, it will return a new exit code `12` which will fail the pipeline (unlike exit code 10, 11)
* ^ very similar to how provisioning errors are tracked and returned to `main()`
* does not trigger test short circuiting mechanism because `testRunner.runWorkers()` doesn't return an error 
```
type testRunner struct {
...
// numGithubPostErrs Counts GitHub post errors across all workers
numGithubPostErrs int32
...
}
...
issue, err := github.MaybePost(t, issueInfo, l, output, params) // TODO add cluster specific args here
if err != nil {
    shout(ctx, l, stdout, "failed to post issue: %s", err)
    atomic.AddInt32(&r.numGithubPostErrs, 1)
}
```
#### Design
In order to do verification via unit tests, i'm used to using something like Python's magic mock, but that's not available in GoLang so i opted for a Dependency Injection approach.  (This was the best I could come up with, I wanted to avoid "if unit test, do this" logic. If anyone has any other approaches / suggestions let me know!) 
I made a new interface `GithubPoster` in such a way that the original `githubIssues` implements that new interface.  I then pass this interface in function signatures all the way from `Run()` to `runTests()`. Then in the unit tests, I could pass a different implementation of `GithubPoster` that has a `MaybePost()` that always fails.
`github.go`
```
type GithubPoster interface {
	MaybePost(
		t *testImpl, issueInfo *githubIssueInfo, l *logger.Logger, message string,
		params map[string]string) (
		*issues.TestFailureIssue, error)
}
```
Another issue with this approach is the original `githubIssues` has information that is cluster specific, but because of dependency injection, it's now a shared struct among all the workers, so it doesn't make sense to store certain fields that are worker dependent.
For the fields that are worker specific, I created a new struct `githubIssueInfo` that is created in `runWorkers()`, similar to how `githubIssues` used to be created there.
Note: I don't love the name `githubIssueInfo`, but i wanted to stick with a similar naming convention to `githubIssues`, open to name suggestions

```
// Original githubIssues
type githubIssues struct {
	disable      bool
	cluster      *clusterImpl
	vmCreateOpts *vm.CreateOpts
	issuePoster func(context.Context, issues.Logger, issues.IssueFormatter, issues.PostRequest,
		*issues.Options) (*issues.TestFailureIssue, error)
	teamLoader func() (team.Map, error)
}
// New githubIssues
type githubIssues struct {
	disable      bool
	issuePoster func(context.Context, issues.Logger, issues.IssueFormatter, issues.PostRequest,
		*issues.Options) (*issues.TestFailureIssue, error)
	teamLoader func() (team.Map, error)
}
```

All this was very verbose and didn't love that i had to change all the function signatures to do this, open to other ways to do verification. 

### Misc
Also first time writing in Go in like ~3 years very open to general go semantic feedback / best practices / design patterns

### Verification
Diff of binary I used to manually confirm if you wanna see where I hardcoded to return errors: https://github.com/cockroachdb/cockroach/commit/611adcce02dbc4934482e6648364d7a9c7d22b7b

### CODE REVIEW

File: pkg/cmd/roachtest/test_test.go [hunk 1]
```diff
@@ -72,6 +73,23 @@ func defaultClusterOpt() clustersOpt {
 	}
 }
 
+// clusterOptWithPreAllocateClusterFn returns a clusterOpt with
+// preAllocateClusterFn set to a function that always returns nil to mock a
+// cluster provisioning error.
+func clusterOptWithPreAllocateClusterFn() clustersOpt {
```
Comment (DarrylWong) [inline pkg/cmd/roachtest/test_test.go]: nit: `clusterOptWithProvisioningError`? To make it obvious from the name itself it will return a provisioning error.

File: pkg/cmd/roachtest/test_test.go [hunk 2]
```diff
@@ -994,6 +1052,55 @@ func TestRunnerFailureAfterTimeout(t *testing.T) {
...
 	err := runner.Run(ctx, []registry.TestSpec{test}, 1, /* count */
-		defaultParallelism, copt, testOpts{}, lopt)
+		defaultParallelism, copt, testOpts{}, lopt, github)
 	require.Error(t, err)
 }
+
+// TestRunnerProvisionErrorGithubError
+//  1. Test Runner Worker experiences provisioning error
+//  2. After provisioning error, the worker will get a GitHub POST error (mocked)
+//  3. Test should still run, and after the runner should have a count of the
```
Comment (DarrylWong) [inline pkg/cmd/roachtest/test_test.go]: I'm missing how the test should still run. You're overriding the cluster allocation with a forced error, so I don't think the runner will ever be able to create a cluster to run the test.

File: pkg/cmd/roachtest/test_runner.go [hunk 3]
```diff
@@ -448,7 +459,16 @@ func (r *testRunner) Run(
 	passFailLine := r.generateReport()
 	shout(ctx, l, lopt.stdout, passFailLine)
 
-	if r.numClusterErrs > 0 {
+	// Prioritize returning GitHub POST errors because we want those to fail the
```
Comment (DarrylWong) [inline pkg/cmd/roachtest/test_runner.go]: nit: could you explain what you mean by "prioritize returning GitHub POST errors"? It seems like this code is taking both into account equally.

File: pkg/cmd/roachtest/test_runner.go [hunk 4]
```diff
@@ -448,7 +459,16 @@ func (r *testRunner) Run(
...
+	// run.
+	if r.numClusterErrs > 0 && r.numGithubPostErrs > 0 {
```
Comment (DarrylWong) [inline pkg/cmd/roachtest/test_runner.go]: nit: seems fine to just log to teamcity twice. e.g.

```
	var err error
	if r.numGithubPostErrs > 0 {
		shout(ctx, l, lopt.stdout, "%d errors occurred while posting to github", r.numGithubPostErrs)
		err = errGithubPostFailed
	}
	if r.numClusterErrs > 0 {
		shout(ctx, l, lopt.stdout, "%d clusters could not be created", r.numClusterErrs)
		err = errors.CombineErrors(err, errSomeClusterProvisioningFailed)
	}
	if err != nil {
		return err
	}
```

File: pkg/cmd/roachtest/main.go [hunk 5]
```diff
@@ -241,10 +247,11 @@ Check --parallelism, --run-forever and --wait-before-next-execution flags`,
 
 	if err := rootCmd.Execute(); err != nil {
 		code := 1
-		if errors.Is(err, errTestsFailed) {
+		if errors.Is(err, errGithubPostFailed) {
+			code = ExitCodeGithubPostFailed
+		} else if errors.Is(err, errTestsFailed) {
```
Comment (DarrylWong) [inline pkg/cmd/roachtest/main.go]: To maintain the same priority as before, shouldn't `errors.Is(err, errTestsFailed)` be last?

File: pkg/cmd/roachtest/test_test.go (hunk 2 above)
Comment (williamchoe3) [reply pkg/cmd/roachtest/test_test.go]: that makes sense, i think i wrote that comment when i had a different understanding of what was happening, will double check the test behavior

File: pkg/cmd/roachtest/main.go (hunk 5 above)
Comment (williamchoe3) [reply pkg/cmd/roachtest/main.go]: your right, just noticed previous logic was back to back if statements and not in an if else, will change the order to errGithubPostFailed, errSomeClusterProvisioningFailed , errTestsFailed,

File: pkg/cmd/roachtest/test_runner.go (hunk 4 above)
Comment (williamchoe3) [reply pkg/cmd/roachtest/test_runner.go]: i can take out the combined log msg and just do the same one twice in the first if clause i.e. i think that makes it more simple like
```
if r.numClusterErrs > 0 && r.numGithubPostErrs > 0 {
  shout(ctx, l, lopt.stdout, "%d errors occurred while posting to github", r.numGithubPostErrs)
  shout(ctx, l, lopt.stdout, "%d clusters could not be created", r.numClusterErrs)
  err = ...
} else if ...
```
but i don't like potentially rewriting `err`, i think the verbosity is worth for the readability, but i don't feel that strongly about this. also if that's how the switch case logic is done in the rest of the package (like in main) / go in general then down to switch

File: pkg/cmd/roachtest/test_runner.go (hunk 3 above)
Comment (williamchoe3) [reply pkg/cmd/roachtest/test_runner.go]: i was trying to capture the idea that we could technically have any combination of 3 errors now, `errSomeClusterProvisioningFailed, errGithubPostFailed, errTestsFailed`
and the comment was supposed to help explain why the if else clauses are set up in the order that they are, BUT I just realized that I should probably just return the joined error up to main and let main handle what to do (and it already does)

will make that change rn

File: pkg/cmd/roachtest/test_test.go (hunk 1 above)
Comment (williamchoe3) [reply pkg/cmd/roachtest/test_test.go]: ty names are tough

File: pkg/cmd/roachtest/test_runner.go (hunk 4 above)
Comment (williamchoe3) [reply pkg/cmd/roachtest/test_runner.go]: ended up rewriting this logic, see this comment https://github.com/cockroachdb/cockroach/pull/149479#discussion_r2195934922

**Comment by herkolategan** [comment]
As tempting as it is to use the issue this addresses in the title, it should be moved to the body of the PR and on the commit message in the following form:
```
roachtest: exit with failure on github post errors
...
Fixes: #147116
```

You can update the PR title to be the same as your commit -> `<comma separated affected packages>: <short desc>`

File: pkg/cmd/roachtest/test_test.go [hunk 6]
```diff
@@ -994,6 +1052,56 @@ func TestRunnerFailureAfterTimeout(t *testing.T) {
...
+	test := registry.TestSpec{
+		Name:             `TestPass`,
+		Owner:            OwnerUnitTest,
+		Timeout:          10 * time.Second,
+		Cluster:          spec.MakeClusterSpec(0),
+		CompatibleClouds: registry.AllExceptAWS,
+		Suites:           registry.Suites(registry.Nightly),
+		CockroachBinary:  registry.StandardCockroach,
+		Run: func(ctx context.Context, t test.Test, c cluster.Cluster) {
+			t.L().Printf("this test should never run")
```
Comment (herkolategan) [inline pkg/cmd/roachtest/test_test.go]: Nit: Even though this should never happen, it would probably be better to panic("...") here if it ever happens, because if it just logged the chances are nobody will ever see it.

File: pkg/cmd/roachtest/test_test.go [hunk 7]
```diff
@@ -994,6 +1052,56 @@ func TestRunnerFailureAfterTimeout(t *testing.T) {
...
+		},
+	}
+
+	err := runner.Run(ctx, []registry.TestSpec{test}, 1, /* count */
+		defaultParallelism, copt, testOpts{}, lopt, github)
+
+	// Assert error is of type errGithubPostFailed && errSomeClusterProvisioningFailed
```
Comment (herkolategan) [inline pkg/cmd/roachtest/test_test.go:1099]: For all these assertions we could use the `require` APIs.

```
	require.ErrorIs(t, err, errGithubPostFailed)
	require.ErrorIs(t, err, errSomeClusterProvisioningFailed)
	require.Equal(t, runner.numGithubPostErrs, int32(1), "expected exactly 1 github post errors")
	require.Equal(t, runner.numClusterErrs, int32(1), "expected exactly 1 cluster errors")
```

It's also a bit cleaner to split them up, so that if one fails it can be viewed in isolation.

Generally produces output like this, so we don't need to add our own print messages as the `require` framework already prints the info.
```
Error:          Target error should be in err chain:
                expected: "failed to POST to GitHub"
                in chain: "some clusters could not be created"
                "some clusters could not be created"
Test:           TestRunnerProvisionErrorGithubError
```
```
Error:          Not equal:
                expected: int32(1)
                actual  : int32(2)
Test:           TestRunnerProvisionErrorGithubError
Messages:       expected exactly 1 github post errors
```

File: pkg/cmd/roachtest/test_runner.go [hunk 8]
```diff
@@ -1136,6 +1164,7 @@ func (r *testRunner) runTest(
 	stdout io.Writer,
 	l *logger.Logger,
 	github *githubIssues,
```
Comment (herkolategan) [inline pkg/cmd/roachtest/test_runner.go]: Any reason to not pass the `GithubPoster` interface here, since I don't think you need the struct here, just the interface methods?

File: pkg/cmd/roachtest/test_runner.go [hunk 9]
```diff
@@ -978,7 +1005,8 @@ func (r *testRunner) runWorker(
 				wStatus.SetTest(t, testToRun)
 				wStatus.SetStatus("running test")
 
-				r.runTest(ctx, t, testToRun.runNum, testToRun.runCount, c, stdout, testL, github)
+				r.runTest(ctx, t, testToRun.runNum, testToRun.runCount, c, stdout, testL,
```
Comment (herkolategan) [inline pkg/cmd/roachtest/test_runner.go:1008]: You should be able to get rid of the type cast `github.(*githubIssues)` here, if you update the `runTest` method to rather take the interface than the implementation struct.

**Review by herkolategan — COMMENTED** [review]
Nice work! Left a few minor comments, but overall the high level implementation looks good.

File: pkg/cmd/roachtest/test_runner.go (hunk 8 above)
Comment (williamchoe3) [reply pkg/cmd/roachtest/test_runner.go]: yep makes sense, initially i was trying to preserve as much original logic / design as i could in the main execution flow but then i ended up changing all the other signatures anyways so might as well change this one too

File: pkg/cmd/roachtest/test_test.go (hunk 7 above)
Comment (williamchoe3) [reply pkg/cmd/roachtest/test_test.go:1099]: thanks for the detailed behavior description!

File: pkg/cmd/roachtest/test_runner.go (hunk 3 above)
Comment (williamchoe3) [reply pkg/cmd/roachtest/test_runner.go]: oh i just realized this is what you were getting at in your other comment, but let me know if the way it is now makes more sense @DarrylWong

File: pkg/cmd/roachtest/test_test.go [hunk 10]
```diff
@@ -994,6 +1052,49 @@ func TestRunnerFailureAfterTimeout(t *testing.T) {
...
+	test := registry.TestSpec{
+		Name:             `TestPass`,
+		Owner:            OwnerUnitTest,
+		Timeout:          10 * time.Second,
+		Cluster:          spec.MakeClusterSpec(0),
+		CompatibleClouds: registry.AllExceptAWS,
+		Suites:           registry.Suites(registry.Nightly),
+		CockroachBinary:  registry.StandardCockroach,
+		Run: func(ctx context.Context, t test.Test, c cluster.Cluster) {
+			panic("this test should never run")
```
Comment (DarrylWong) [inline pkg/cmd/roachtest/test_test.go:1089]: nit: The test runner will recover this panic as a test failure. So you'd have to also add a `require.NotErrorIs(t, err, errTestsFailed)` check to assert that the test itself didn't fail.

File: pkg/cmd/roachtest/test_runner.go (hunk 3 above)
Comment (DarrylWong) [reply pkg/cmd/roachtest/test_runner.go]: Yep, the prioritization comment makes a lot more sense now. Thanks!

File: pkg/cmd/roachtest/test_test.go (hunk 10 above)
Comment (williamchoe3) [reply pkg/cmd/roachtest/test_test.go:1089]: oops got it will add ty

**Review by DarrylWong — APPROVED** [review]

**Comment by williamchoe3** [comment]
The TeamCity build has unfortunately been very inconsistent for me and just me, i've just been assuming it's intermittent failures but i'm the only branch that's hitting it. I've been able to get it to pass by just rerunning but gonna take a look to see what's going on, noticing heap memory issues when publishing artifacts but i'm not adding any new artifacts so i dont know why i'd be getting OOMs

**Review by herkolategan — APPROVED** [review]
Thanks for making the changes! I'll go look at the TC test runs as well. It's usually easy to find using the PR number, but sometimes we paste a link to the TC build on the PR just to make it easier for reviewers to link directly to it.

**Comment by williamchoe3** [comment]
> The TeamCity build has unfortunately been very inconsistent for me and just me, i've just been assuming it's intermittent failures but i'm the only branch that's hitting it. I've been able to get it to pass by just rerunning but gonna take a look to see what's going on, noticing heap memory issues when publishing artifacts but i'm not adding any new artifacts so i dont know why i'd be getting OOMs

some extra context (https://cockroachlabs.slack.com/archives/CJ0H8Q97C/p1752259095090199) 
ran local stress, race testing didn't see anything out of the ordinary, will go ahead with the merge

**Comment by williamchoe3** [comment]
TFTR!

bors r=herkolategan,DarrylWong

**Comment by srosenberg** [comment]
Nice work! As a precaution we usually fire up a smoke test using `SELECT_PROBABILITY` [1] prior to `bors`ing. Here is an example [2]. This rule holds only for any non-trivial changes which touch the roachtest framework. Historically, the smoke test has been pretty effective in finding issues that were missed during the PR review. Worst-case scenario the nightly would crash, preempting some of the roachtests.

[1] https://cockroachlabs.atlassian.net/wiki/spaces/TE/pages/146538717/Roachtest#Roachtest-OverridingSELECT_PROBABILITY
[2] https://github.com/cockroachdb/cockroach/pull/148244#issuecomment-2968510132
