### PR TITLE
rpc: set the max-msg-size to 128 MB

### LINKED ISSUE #8267: storage: up-replication is broken
SHA: 36d693594ca39c91946d6a16735214267df9f763

Steps to repro:
1. Use `roachdemo` or manually start a node on localhost
2. Use `block_writer` until you have some replicas (I had 14 replicas on my node).
3. Add 2 more nodes to the cluster.
4. Wait 8 or so minutes and notice that full replication hasn't occurred.

My UI several minutes after stopping load: 
screenshot 2016-08-02 16 22 34

First node logs have lots of these messages:
```
E160802 16:13:58.079597 storage/queue.go:508  [replicate] (purgatory) on store=1:1 range=11 [/Table/51/1/8066815000180517192/"f1bb11fa-d0a5-4cc2-80d9-47fb499688fa"/12442-/Max): 0 of 1 store with an attribute matching []; likely not enough nodes in cluster
E160802 16:13:58.079718 storage/queue.go:508  [replicate] (purgatory) on store=1:1 range=9 [/Table/51/1/6905099058192869454/"ba47c93d-ba45-46cf-bbca-22d8be3c0b2d"/7257-/Table/51/1/8066815000180517192/"f1bb11fa-d0a5-4cc2-80d9-47fb499688fa"/12442): 0 of 1 store with an attribute matching []; likely not enough nodes in cluster
E160802 16:13:58.079835 storage/queue.go:508  [replicate] (purgatory) on store=1:1 range=12 [/Table/51/1/5746020457527034543/"20c1db92-e9e6-4637-8e2e-f81579f18049"/23352-/Table/51/1/6905099058192869454/"ba47c93d-ba45-46cf-bbca-22d8be3c0b2d"/7257): 0 of 1 store with an attribute matching []; likely not enough nodes in cluster
E160802 16:13:58.081499 storage/queue.go:508  [replicate] (purgatory) on store=1:1 range=4 [/Table/13-/Table/14): 0 of 1 store with an attribute matching []; likely not enough nodes in cluster
E160802 16:13:58.083024 storage/queue.go:508  [replicate] (purgatory) on store=1:1 range=5 [/Table/14-/Table/50): 0 of 1 store with an attribute matching []; likely not enough nodes in cluster
E160802 16:14:44.017542 storage/queue.go:508  [replicate] (purgatory) on store=1:1 range=10 [/Table/51/1/2284333991187876666/"2e5eba36-9f26-44e7-9db2-f6ffae056f5c"/5106-/Table/51/1/3432100885105267539/"fb92fc20-73b3-41c8-a018-5606e6280922"/9173): 0 of 2 stores with an attribute matching []; likely not enough nodes in cluster
E160802 16:14:46.763930 storage/queue.go:497  [replicate] on store=1:1 range=14 [/Table/51/1/1142067297708073482/"27be8a3b-3aed-4db9-9f96-53419dcd0fa5"/8552-/Table/51/1/2284333991187876666/"2e5eba36-9f26-44e7-9db2-f6ffae056f5c"/5106): change replicas of range 14 failed: reservation declined:header:<node_id:3 store_id:3 > from_node_id:1 from_store_id:1 range_id:14 range_size:58970985
E160802 16:14:46.779365 storage/queue.go:497  [replicate] on store=1:1 range=10 [/Table/51/1/2284333991187876666/"2e5eba36-9f26-44e7-9db2-f6ffae056f5c"/5106-/Table/51/1/3432100885105267539/"fb92fc20-73b3-41c8-a018-5606e6280922"/9173): change replicas of range 10 failed: reservation declined:header:<node_id:3 store_id:3 > from_node_id:1 from_store_id:1 range_id:10 range_size:59384404
E160802 16:14:50.291948 storage/queue.go:497  [replicate] on store=1:1 range=11 [/Table/51/1/8066815000180517192/"f1bb11fa-d0a5-4cc2-80d9-47fb499688fa"/12442-/Max): change replicas of range 11 failed: context deadline exceeded
```

Long-running tasks:
screenshot 2016-08-02 16 25 30

### PR DESCRIPTION
**Pull request by petermattis**
Fixes #8267.

---

This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/8274)

### CODE REVIEW

**Comment by petermattis** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[rpc/context.go, line 48 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8274#-KOCsgFPEPUvRYzEqOlT:-KOCsgFPEPUvRYzEqOlU:-713248607) ([raw file](https://github.com/cockroachdb/cockroach/blob/413bcb2b7cccb9916a51b8e02fc761060c86b3fd/rpc/context.go#L48)):*
> ```Go
> func NewServer(ctx *Context) *grpc.Server {
> 	var s *grpc.Server
> 	maxMsgSize := grpc.MaxMsgSize(128 << 20) // 128 MB
> ```

This limits are range size to 128 MB until we implement streaming snapshots. This also deserves a test. Perhaps we should set the limit to `math.MaxInt32` for now.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8274)*

File: rpc/context.go [hunk 1]
```diff
@@ -45,14 +45,15 @@ const (
 // service.
 func NewServer(ctx *Context) *grpc.Server {
 	var s *grpc.Server
+	maxMsgSize := grpc.MaxMsgSize(128 << 20) // 128 MB
```
Comment (tamird) [inline rpc/context.go]: Maybe this wants to build up a slice of options like we do in the client. I'd make it maxint for now.

Comment (petermattis) [inline rpc/context.go]: Sure and done.

File: rpc/context.go [hunk 2]
```diff
@@ -45,15 +46,17 @@ const (
...
+	}
+	if !ctx.Insecure {
 		tlsConfig, err := ctx.GetServerTLSConfig()
 		if err != nil {
 			panic(err)
 		}
-		s = grpc.NewServer(grpc.Creds(credentials.NewTLS(tlsConfig)))
+		opts = append(opts, grpc.Creds(credentials.NewTLS(tlsConfig)))
 	}
+	s = grpc.NewServer(opts...)
```
Comment (tamird) [inline rpc/context.go]: this can be `s :=`

LGTM after that

Comment (tamird) [inline rpc/context.go]: let's file an issue about those tests

Comment (cuongdo) [inline rpc/context.go]: Also worth noting that once #8265 is in, we'll catch this type of issue in
our nightly load tests. However, it'll still require more diagnosis than a
more specific test.

Comment (petermattis) [inline rpc/context.go]: Done. I'll file an issue.
