### PR TITLE
roachtest: delake pcr roachtests that offset reader tenant system tables

### LINKED ISSUE #153555: roachtest: c2c/kv0 failed
roachtest.c2c/kv0 [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/20472139?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/20472139?buildTab=artifacts#/c2c/kv0) on master @ [e7245933f8b6ca04a728d459b0f8f91df0a9177a](https://github.com/cockroachdb/cockroach/commits/e7245933f8b6ca04a728d459b0f8f91df0a9177a):

```
(sql_runner.go:286).Scan: error scanning '&{0xc00a2178c0 <nil>}': pq: internal error while retrieving user account memberships: resolved privileges to 100052 but found no descriptor with id 100052: referenced descriptor ID 100052: looking up ID 100052: descriptor not found
(1) pq: internal error while retrieving user account memberships: resolved privileges to 100052 but found no descriptor with id 100052: referenced descriptor ID 100052: looking up ID 100052: descriptor not found
Error types: (1) *pq.Error
(monitor.go:267).Wait: monitor failure: monitor user task failed: t.Fatal() was called
test artifacts and logs in: /artifacts/c2c/kv0/run_1
```

Parameters:
 - <code>arch=amd64</code>
 - <code>cloud=gce</code>
 - <code>coverageBuild=false</code>
 - <code>cpu=8</code>
 - <code>encrypted=false</code>
 - <code>fs=ext4</code>
 - <code>localSSD=false</code>
 - <code>metamorphicLeases=default</code>
 - <code>runtimeAssertionsBuild=false</code>
 - <code>ssd=0</code>
<details><summary>Help</summary>
<p>

See: [roachtest README](https://github.com/cockroachdb/cockroach/blob/master/pkg/cmd/roachtest/README.md)

See: [How To Investigate \(internal\)](https://cockroachlabs.atlassian.net/l/c/SSSBr8c7)

See: [Grafana](https://go.crdb.dev/roachtest-grafana/teamcity-20472139/c2c-kv0/1758011851792/1758012782683)

</p>
</details>
/cc @cockroachdb/disaster-recovery
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*c2c/kv0.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/bazci/githubpost/issues)

</sub>

Jira issue: CRDB-54488

### PR DESCRIPTION
**Pull request by msbutler**
In this patch, we restart the reader tenant after the poller job bootstraps the reader catalog, to refresh the namespace cache. This is necessary because the reader tenant namespace cache believes the the priv table has id 100052 instead of the newly ingested id 52 from the source.

Fixes #153555

Epic: none

Release note: none

### CODE REVIEW

File: pkg/cmd/roachtest/tests/cluster_to_cluster.go [hunk 1]
```diff
@@ -1019,6 +1018,61 @@ func (rd *replicationDriver) maybeRunSchemaChangeWorkload(
...
+		conn := rd.c.Conn(ctx, rd.t.L(), rd.setup.dst.gatewayNodes[0], option.VirtualClusterName(readerTenantName))
+		defer conn.Close()
+		if err := conn.Ping(); err == nil {
+			return errors.Newf("reader tenant %q still accepting connections", readerTenantName)
+		}
+		return nil
+	})
+
+	// Start the service back up
+	rd.setup.dst.sysSQL.Exec(rd.t, fmt.Sprintf("ALTER VIRTUAL CLUSTER '%s' START SERVICE SHARED", readerTenantName))
```
Comment (jeffswenson) [inline pkg/cmd/roachtest/tests/cluster_to_cluster.go:1071]: Can a user also hit this failure condition and need to restart the reader tenant? Or is there something test specific that causes us to observe it.

Comment (msbutler) [reply pkg/cmd/roachtest/tests/cluster_to_cluster.go:1071]: yes, in the runbook that describes how to use this cluster setting, i will document this known limitation.

**Review by jeffswenson — APPROVED** [review]
LGTM

**Comment by msbutler** [comment]
TFTR

bors r=jeffswenson
