### PR TITLE
sql: gate system database behind session variable

### LINKED ISSUE #149594: sql: gate crdb_internal access behind a cluster setting
As part of an effort to define a more stable sql interface for the introspection of cockroach specific internals, we're increasing the operator overhead for accessing the crdb_internal database. This should make it clear that this catalog is not designed for stable usage, and encourage customers to request production-grade interfaces for the tables defined within it.

To complete this, introduce a cluster and session setting `crdb_restrict_internal_access` which when enabled fails all queries to the crdb_internal catalog with the below error:

```
Access to crdb_internal and System is restricted. These interfaces are unsupported in production. To proceed, set the session variable crdb_restrict_internal_access = false (not recommended), or contact Cockroach Labs for a supported alternative.
```

Epic: CRDB-24527

### LINKED ISSUE #151333: sql: add unsafe access check to CheckPrivilege system descriptors
As part of an effort to define a more stable sql interface for the introspection of cockroach specific internals, we're increasing the operator overhead for accessing the crdb_internal and system catalogs. This should make it clear that this catalog is not designed for stable usage, and encourage customers to request production-grade interfaces for the tables defined within it.

After the access gate has been added to the code, we want to gate CheckPrivilege with this new access gate, to prevent unauthorized access to the system database.

Epic: CRDB-24527

### PR DESCRIPTION
**Pull request by angles-n-daemons**
It today isn't quite clear which internal objects are safe for external usage. For example, selecting from crdb_internal.zones is considered safe, while deleting from system.jobs is not.

To address this, we're adding a gate protecting some of these internals, as well as auditing around their usage so that we can better see how the internal state of the database may have been modified.

The start of this effort is this PR, which adds an gate on the privilege check for system descriptors. This gate is simple now, it checks whether the caller is internal or if the override session variable is set to access "unsafe internals".

It should be noted that allowance is the default to start, so that extensive testing can be done on this feature before its rolled out more widely.

Fixes: #149594 
Fixes: #151333
Epic: CRDB-24527

Release note (sql change): Adds a new session variable `allow_unsafe_internals` and corresponding cluster setting (`sql.defaults.allow_unsafe_internals`) which controls access to the `system` database.

### CODE REVIEW

File: pkg/sql/unsafe/unsafe.go [hunk 1]
```diff
@@ -0,0 +1,28 @@
+// Copyright 2025 The Cockroach Authors.
+//
+// Use of this software is governed by the CockroachDB Software License
+// included in the /LICENSE file.
+
+package unsafe
```
Comment (dt) [inline pkg/sql/unsafe/unsafe.go]: I think we should name this package `unsafesql` or `dbinternals` or something else that avoids ambiguity with the builtin go `unsafe` package. Seeing something like `unsafe.Foo()` in some code typically sets off alarm bells, but it shouldn't here (the opposite in fact) but you would need to see which "unsafe" was imported to know that.

Comment (angles-n-daemons) [reply pkg/sql/unsafe/unsafe.go]: Ah that's a great point, yeah I'll go with `unsafesql`

**Review by rafiss — APPROVED** [review]
lgtm! just had minor nits, so feel free to merge after addressing them.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/151362#-:-OXytmmi59xgJE5OWswq:b49lgyl)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @alyshanjahani-crl and @dt)

___
*[`-- commits` line 26 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/151362#-OXyskmf7MKvGBQO2RVR:-OXyskmf7MKvGBQO2RVS:b-2pp9bu):*
the latest version of this PR doesn't have this cluster setting, so let's make sure to take it out of the release note.
___
*[`pkg/sql/unsafesql/unsafesql_test.go` line 31 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/151362#-OXyth6B0q8hXhKGMhVH:-OXyth6B0q8hXhKGMhVI:b-sav77m) ([raw file](https://github.com/cockroachdb/cockroach/blob/c4d0899d8803868ba77439ad3af91e83e78c1edd/pkg/sql/unsafesql/unsafesql_test.go#L31)):*
> ```Go
> 			Passes               bool
> 		}{
> 			{true, true, true},
> ```

super nit: the tests may be more readable if these inlined structs used named fields.

**Review by angles-n-daemons — COMMENTED** [review]
thanks, will do!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/151362#-:-OY1icPuAtGyxPwUj39p:b-pcb1hy)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @alyshanjahani-crl, @dt, and @rafiss)

___
*[`-- commits` line 26 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/151362#-OXyskmf7MKvGBQO2RVR:-OY1iiEYCZ1yhKMK9jHp:b-m3re19):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

the latest version of this PR doesn't have this cluster setting, so let's make sure to take it out of the release note.
</blockquote></details>

Ahh good point, will change this now.
___
*[`pkg/sql/unsafesql/unsafesql_test.go` line 31 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/151362#-OXyth6B0q8hXhKGMhVH:-OY1ig5o2kJ91JQA4Lgv:bvfnunm) ([raw file](https://github.com/cockroachdb/cockroach/blob/c4d0899d8803868ba77439ad3af91e83e78c1edd/pkg/sql/unsafesql/unsafesql_test.go#L31)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

super nit: the tests may be more readable if these inlined structs used named fields.
</blockquote></details>

Good point, will change this now.

**Comment by yuzefovich** [comment]
bors retry
