### PR TITLE
ui: A collection of fixes the network debugging page

### LINKED ISSUE #23552: ui: Network diagnostics page fails to load on single node cluster
Repro steps:

1. Build cockroach from head (I used b6c934ccee6293b697dff5880cf364c2370bf758)
2. Start a single cockroach node against a fresh data directory: `./cockroach start --logtostderr [--insecure]`
3. Go to http://localhost:8080/#/reports/network or https://localhost:8080/#/reports/network depending on whether you're running in secure mode

I've tried this on my macbook running securely as well as on my gceworker running with `--insecure`. Both of them just hang. This is what the linux gceworker page looks like:

screen shot 2018-03-07 at 2 40 48 pm

The logs of both processes repeatedly include this message that may be related:

`W180307 19:43:54.188056 592 server/server.go:1513  [n1] error closing gzip response writer: http: request method or response status code does not allow body`

cc @mrtracy in case @BramGruneir is too busy to look at this soon. This may be related to other, less easily reproducible flakiness I've seen on this page before in larger clusters. Maybe related to #23349, although that involved killing a node whereas this is much simpler to repro.

### PR DESCRIPTION
**Pull request by BramGruneir**
- Fix the case in which longs had no value during calculation causing the page
to not load.
- Fix latency page to only display when there is at least 2 nodes worth of
latencies to display.
- Add a loading spinner to the network diagnostics page.
- Fix the loading spinner to accept an array of children instead of just a
single child element.
- Add a new top padded style so the loading spinner is not so cramped on the
page.

Fixes #23552.

Release note (admin ui change): The network diagnositcs report will no longer
crash when the latencies are very small or on a single node cluster.

### CODE REVIEW

File: pkg/ui/src/views/reports/containers/network/index.tsx [hunk 1]
```diff
@@ -399,20 +405,37 @@ class Network extends React.Component<NetworkProps, {}> {
...
+      content = [<h2>Cannot show latency chart without two healthy nodes.</h2>];
     } else {
       content = this.renderLatencyTable(latencies, staleIDs, nodesSummary, displayIdentities);
     }
-
     return (
-      <div className="section">
-        <h1>Network Diagnostics</h1>
-        <NodeFilterList nodeIDs={filters.nodeIDs} localityRegex={filters.localityRegex} />
+      <div>
```
Comment (couchand) [inline pkg/ui/src/views/reports/containers/network/index.tsx]: this wrapper div is unfortunate.  we should try to upgrade to React 16 soon after 2.0, so we can use this: https://reactjs.org/blog/2017/11/28/react-v16.2.0-fragment-support.html

In this case I think returning a list would probably be ok...

File: pkg/ui/src/views/shared/components/loading/index.tsx [hunk 2]
```diff
@@ -18,5 +18,9 @@ export default function Loading(props: LoadingProps) {
   if (props.loading) {
     return <div className={props.className} style={image} />;
   }
-  return props.children as JSX.Element;
+  return (
```
Comment (couchand) [inline pkg/ui/src/views/shared/components/loading/index.tsx]: It might be worth commenting on why this wrapper div is necessary so we don't accidentally remove it.  That comment might also mention that after upgrading to React 16 we could convert it to a fragment.

**Review by couchand — COMMENTED** [review]
While verifying this one time I got a console error of `activity is undefined`, but I can't repro that now.  Not sure if that rings a bell...

**Comment by BramGruneir** [comment]
PTAL.  I've added a few new fixes.  `activity is undefined` should be fixed.

Specifically, I've added:
- Fix a crash when a new node doesn't yet have any activity.
- Replace all not yet calculated latencies with a `?`.
- Don't display a legend if there is only one value (and hence no stddev).

As well as now there are `?` when we don't have the latency instead of showing a 0.



---

Review status: 0 of 4 files reviewed at latest revision, 2 unresolved discussions, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/23844#-:-L7_yQMsacpFLNtdUn9T:b7e3y5x)*

**Comment by couchand** [comment]
:lgtm: thanks!

---

Reviewed 2 of 4 files at r1, 2 of 2 files at r2.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/23844#-:-L7aH_lWme9yiheyFu-w:brfqlux)*
