### PR TITLE
tpcc: Fix partition statement in tpcc roachtest

### LINKED ISSUE #41028: roachtest: tpccbench/nodes=9/cpu=4/multi-region failed
SHA: https://github.com/cockroachdb/cockroach/commits/9422434988be7776e733627d808192bae8800fb5

Parameters:

To repro, try:

```
# Don't forget to check out a clean suitable branch and experiment with the
# stress invocation until the desired results present themselves. For example,
# using stress instead of stressrace and passing the '-p' stressflag which
# controls concurrency.
./scripts/gceworker.sh start && ./scripts/gceworker.sh mosh
cd ~/go/src/github.com/cockroachdb/cockroach && \
stdbuf -oL -eL \
make stressrace TESTS=tpccbench/nodes=9/cpu=4/multi-region PKG=roachtest TESTTIMEOUT=5m STRESSFLAGS='-maxtime 20m -timeout 10m' 2>&1 | tee /tmp/stress.log
```

Failed test: https://teamcity.cockroachdb.com/viewLog.html?buildId=1503079&tab=artifacts#/tpccbench/nodes=9/cpu=4/multi-region

```
The test failed on branch=master, cloud=gce:
test artifacts and logs in: /home/agent/work/.go/src/github.com/cockroachdb/cockroach/artifacts/20190924-1503079/tpccbench/nodes=9/cpu=4/multi-region/run_1
	cluster.go:2115,tpcc.go:878,tpcc.go:589,test_runner.go:689: /home/agent/work/.go/src/github.com/cockroachdb/cockroach/bin/roachprod run teamcity-1569301790-81-n12cpu4-geo:4 -- ./workload fixtures load tpcc --warehouses=2000 --scatter --checks=false --partitions=3 --zones="us-east1-b,us-west1-b,europe-west2-b" {pgurl:1} returned:
		stderr:
		
		stdout:
		59152169s (200000000 rows, 200000000 index entries, 15 MiB)
		Error: restoring fixture: pq: importing 306 ranges: split at key /Table/57/1/211/"\x1b\x06:e\x0f\x06L\x00\x80\x00\x00\x00\x00`\xa5\x83"/PrefixEnd failed: descriptor changed: [expected] r248:/Table/5{7/1/44/"\x05\xa7ֺ\xd3\xedJ\x00\x80\x00\x00\x00\x00\x149\xe0"-8} [(n1,s1):1, (n6,s6):2, (n9,s9):8, next=9, gen=52, sticky=1569324995.397571691,0] != [actual] r248:/Table/5{7/1/44/"\x05\xa7ֺ\xd3\xedJ\x00\x80\x00\x00\x00\x00\x149\xe0"-8} [(n1,s1):1, (n6,s6):2, (n9,s9):8, (n2,s2):9LEARNER, next=10, gen=53, sticky=1569324995.397571691,0]: unexpected value: raw_bytes:"\316\347zd\003\010\370\001\022\033\301\211\264\022\005\247\326\272\323\355J\000\377\200\000\377\000\377\000\377\000\377\0249\340\000\001\032\001\302\"\006\010\001\020\001\030\001\"\006\010\006\020\006\030\002\"\006\010\t\020\t\030\010\"\010\010\002\020\002\030\t \001(\n05:\n\010\353\250\301\276\314\230\327\343\025@\001" timestamp:<wall_time:1569321437339978468 logical:1 > 
		Error:  exit status 1
		: exit status 1

```

### PR DESCRIPTION
**Pull request by rohany**
After #41216, zone configuration statements on partitions have some more
validation applied to them. This fixes #41028, which didn't have enough
information in the zone configuration statement.

Release note: None

### CODE REVIEW

File: pkg/workload/tpcc/partition.go [hunk 1]
```diff
@@ -262,7 +262,7 @@ func configureZone(db *gosql.DB, cfg zoneConfig, table, partition string, partId
 		opts = fmt.Sprintf(`constraints = '[+%s]'`, kv)
```
Comment (nvanbenschoten) [inline pkg/workload/tpcc/partition.go]: We also need it here, right?

**Review by nvb — CHANGES_REQUESTED** [review]

File: pkg/workload/tpcc/partition.go (hunk 1 above)
Comment (rohany) [reply pkg/workload/tpcc/partition.go]: No, because the constraints here aren't per replica, so we don't need to set num_replicas

**Review by nvb — APPROVED** [review]

File: pkg/workload/tpcc/partition.go (hunk 1 above)
Comment (nvanbenschoten) [reply pkg/workload/tpcc/partition.go]: 👍

**Comment by rohany** [comment]
This will only work once https://github.com/cockroachdb/cockroach/pull/41506 lands, so I'll wait for that.

**Comment by tbg** [comment]
Looks like the bors run perished
bors r=nvanbenschoten

**Comment by rohany** [comment]
bors r=nvanbenschoten

**Comment by rohany** [comment]
not sure whats going on with trying to merge this. CI is failing repeatedly with "no space left on device" while running make bench, and bors isn't cooperating.

**Comment by rohany** [comment]
bors r=nvanbenschoten

**Comment by rohany** [comment]
Alright, since bors isnt doing so hot, I'm just going to merge this using the button.

**Comment by bobvawter** [comment]
bors try
