### PR TITLE
sql: pg_catalog fixes for int2vector type

### LINKED ISSUE #14929: int2vector has incorrect typelem in pg_type system table
The typelem for int2vector should be `21` instead of the current `20`.

### LINKED ISSUE #14930: int2vector is missing typsend, typreceive, typoutput, typinput in pg_type
in2vector returns null for the above columns while it should return:

|typsend| typreceive|typoutput|typinput|
| ------------- |-------------| -----|-----|
|int2vectorsend | int2vectorrecv | int2vectorout | int2vectorin|

### PR DESCRIPTION
**Pull request by jordanlewis**
- give `int2vector` its correct `typelem` - `int2`, not `int8`.
- give `int2vector` its type IO (typrecv, typsend, etc) functions in `pg_type`

Fixes #14929.
Fixes #14930.

### CODE REVIEW

**Comment by knz** [comment]
LGTM modulo request for extra comment

---

Reviewed 2 of 2 files at r1, 2 of 2 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[pkg/sql/pg_catalog.go, line 1436 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/14989#-Khwz_6BL1sN_SWaNqmO:-Khwz_6CxydwdiTmfj2I:buqbh0w) ([raw file](https://github.com/cockroachdb/cockroach/blob/1a817535993424ba6c49759e579a5a5388920559/pkg/sql/pg_catalog.go#L1436)):*
> ```Go
> 			builtinPrefix := parser.PGIOBuiltinPrefix(typ)
> 			if cat == typCategoryArray {
> 				if typ == parser.TypeIntVector {
> ```

Please add a comment to clarify what is going on here.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14989#-:-Khwznf3xv1MSQfWiL2H:bnp37lw)*

File: pkg/sql/pg_catalog.go [hunk 1]
```diff
@@ -1428,27 +1428,35 @@ CREATE TABLE pg_catalog.pg_type (
...
 			if cat == typCategoryArray {
-				typElem = parser.NewDOid(parser.DInt(parser.UnwrapType(typ).(parser.TArray).Typ.Oid()))
-				if typ != parser.TypeIntVector {
+				if typ == parser.TypeIntVector {
+					// IntVector needs a special case because its a special snowflake
+					// type. It's just like an Int2Array, but it has its own OID. We
+					// can't just wrap our Int2Array type in an OID wrapper, though,
+					// because Int2Array is not an exported, first-class type - it's an
+					// input-only type that translates immediately to int8array. This
+					// would go away if we decided to export Int2Array as a real type.
```
Comment (nvanbenschoten) [inline pkg/sql/pg_catalog.go]: So are there any downsides to exporting `typeInt2Array`?

Also, I'm not sure I get why doing `TypeIntVector = wrapTypeWithOid(typeInt2Array, oid.T_int2vector)` without exporting `typeInt2Array` wouldn't work. Seems like the only other changes would be adding `case parser.TypeIntVector:` as a case to `sql.checkResultType` and may changing something around `NewDIntVectorFromDArray`. I might be missing something though.

Comment (jordanlewis) [inline pkg/sql/pg_catalog.go]: The downside to exporting TypeInt2Array is that it introduces a funky inconsistency - it'd be the only type that's exported from the package but not supported as a first class type.

The reason what you suggest won't work is that `checkResultType` unwraps the input type before checking for equality, so you need to actually be adding `TypeInt2Array` to the switch instead of `TypeIntVector`. I played around with this a little and decided to do it with this special case because it seemed the least messy.

I'm 50/50 on whether we should just export `TypeInt2Array` despite it being inconsistent - if you think that's fine then I'll go ahead and agree.

Comment (nvanbenschoten) [inline pkg/sql/pg_catalog.go]: You've convinced me that either way will be messy, so let's go with what you prefer :)

**Comment by nvanbenschoten** [comment]
LGTM

**Comment by jordanlewis** [comment]
TFTR!
