### PR TITLE
roachprod-microbench: fix missing warning-level in Slack

### LINKED ISSUE #165294: roachprod-microbench: Slack regression reports missing warning-level
## Problem

The weekly microbenchmark Slack reports no longer show the :small_orange_diamond: (warning) emoji for moderate regressions. All reported regressions show :small_red_triangle: (significant) instead.

This was introduced when per-benchmark thresholds were added. The old `isRegression` had no magnitude filter — any regression was included, and the emoji logic differentiated:
- `:small_orange_diamond:` for regressions below the 20% threshold
- `:small_red_triangle:` for regressions above 20%

The new `isRegression` filters out regressions below the threshold (`>= threshold`), but the emoji comparison still uses the same threshold value (`> threshold`). This makes the orange diamond effectively dead — only an exact match at the threshold boundary would produce it.

**Before (working):**
```
• pkg/raft→Status/members=1... :small_red_triangle:21.03%
• pkg/rpc→Authenticate/commonNode-32 :small_orange_diamond:14.24%
```

**After (broken):**
```
• pkg/raft→Status/members=1... :small_red_triangle:21.03%
(14.24% regression not shown at all)
```

This reduces visibility of moderate regressions that may still warrant attention.

Jira issue: CRDB-61313

### PR DESCRIPTION
**Pull request by herkolategan**
The per-benchmark threshold change (#163839) added a magnitude filter to `isRegression`, requiring `abs(delta) >= threshold`. However, the Slack emoji logic still compared against the same threshold to choose between orange diamond (warning) and red triangle (significant), making orange diamonds effectively unreachable.

Fix by using a two-tier system: regressions at half the threshold and above are included in the Slack report with an orange diamond, and regressions at or above the full threshold get a red triangle. For the default 20% threshold this means 10-19.99% gets a warning indicator and
>= 20% gets a significant indicator.

The GitHub issue posting thresholds are unchanged.

Fixes: #165294

Release note: None

### CODE REVIEW

File: pkg/cmd/roachprod-microbench/compare.go [hunk 1]
```diff
@@ -285,7 +285,7 @@ func (c *compare) postToSlack(
 				metric := result.Metric
 
 				threshold := c.benchmarkThreshold(detail.BenchmarkName)
-				if !isRegression(comparison.Delta, threshold, metric.Better) {
+				if !isRegression(comparison.Delta, threshold/2, metric.Better) {
```
Comment (golgeek) [inline pkg/cmd/roachprod-microbench/compare.go]: Nit: maybe add a comment to explain we take a lower threshold for warnings? took me a few back and forth between `isRegression()` and the `if math.Abs(comparison.Delta) >= threshold {}` below to understand why you were dividing the threshold.

Having two different threshold values (warn/crit) would make it even more clear, but it's a bigger change that might not be needed.

**Review by golgeek — APPROVED** [review]

File: pkg/cmd/roachprod-microbench/compare.go (hunk 1 above)
Comment (srosenberg) [reply pkg/cmd/roachprod-microbench/compare.go]: Same comment. The previous version of `isRegression` seemed cleaner, i.e.,

```
return delta*float64(better) < 0
```

The new one conflates regression with tolerance.

Comment (herkolategan) [reply pkg/cmd/roachprod-microbench/compare.go]: Makes sense, I'll update it to make it more ergonomic.
