### PR TITLE
sqlccl: de-flake TestActiveCancelSession

### LINKED ISSUE #123639: pkg/ccl/testccl/sqlccl/sqlccl_test: TestActiveCancelSession failed
pkg/ccl/testccl/sqlccl/sqlccl_test.TestActiveCancelSession [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_StressBazel/15119722?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_StressBazel/15119722?buildTab=artifacts#/) on release-23.2.5-rc @ [57ab10786d6ed277959c8990e2823772893ac873](https://github.com/cockroachdb/cockroach/commits/57ab10786d6ed277959c8990e2823772893ac873):

```
=== RUN   TestActiveCancelSession
    test_log_scope.go:170: test logs captured to: /artifacts/tmp/_tmp/5c751b11a9f469cbdd173f9eebde1a6d/logTestActiveCancelSession2269752954
    test_log_scope.go:81: use -show-logs to present logs inline
    run_control_test.go:289: -- test log scope end --
test logs left over in: /artifacts/tmp/_tmp/5c751b11a9f469cbdd173f9eebde1a6d/logTestActiveCancelSession2269752954
--- FAIL: TestActiveCancelSession (3.07s)
=== RUN   TestActiveCancelSession/Tenant
    run_control_test.go:224: session not canceled; actual error: read tcp 127.0.0.1:36498->127.0.0.1:38811: read: connection reset by peer
    --- FAIL: TestActiveCancelSession/Tenant (0.03s)
```

Parameters:
 - <code>TAGS=bazel,gss</code>
 - <code>stress=true</code>
<details><summary>Help</summary>
<p>

See also: [How To Investigate a Go Test Failure \(internal\)](https://cockroachlabs.atlassian.net/l/c/HgfXfJgM)
</p>
</details>
/cc @cockroachdb/sql-queries
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*TestActiveCancelSession.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)
</sub>

Jira issue: CRDB-38444

### PR DESCRIPTION
**Pull request by yuzefovich**
This commit fixes a possible race in `TestActiveCancelSession`. In particular, that test uses two connections in the following manner:
- conn1 runs `pg_sleep` query that is intended to run forever
- conn2 executes `CANCEL SESSION` for conn1.

Since `pg_sleep` query is executed in a separate goroutine, previously it was possible for CANCEL SESSION statement to be issued before either the separate goroutine was spun up or it began executing the `pg_sleep` query, and in both cases this would result in `connection reset by peer` error which is not what the test expects. This race is now fixed by blocking conn2 until it sees the `pg_sleep` query in the SHOW CLUSTER QUERIES output.

Fixes: #123639.

Release note: None

### CODE REVIEW

**Comment by yuzefovich** [comment]
cc @rafiss - this seems somewhat related to #124465 and #124452

File: pkg/ccl/testccl/sqlccl/run_control_test.go [hunk 1]
```diff
@@ -205,6 +205,29 @@ func testCancelSession(t *testing.T, hasActiveSession bool) {
 					_, err = conn1.ExecContext(ctx, "SELECT pg_sleep(1000000)")
 					errChan <- err
 				}()
+				// Block until the query goroutine was spun up and began
+				// executing the query - this is needed to avoid a race between
+				// canceling the session before vs after 'pg_sleep' query begins
+				// (the former would result in an unexpected error message).
+				toSleep := time.Millisecond
```
Comment (rafiss) [inline pkg/ccl/testccl/sqlccl/run_control_test.go:212]: nit: this might be simplified a little with `testutils.SucceedsSoon`. here's an existing example: https://github.com/cockroachdb/cockroach/blob/3cd24e8377c219b1dd05ef612e0366bd5c3c3dad/pkg/sql/show_test.go#L695-L715

**Review by rafiss — APPROVED** [review]
nice find!

**Review by yuzefovich — COMMENTED** [review]
TFTR!

bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/124564#-:-NyWcKoy64HSkIKVktWK:b-oduykh)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @michae2 and @rafiss)

___
*[`pkg/ccl/testccl/sqlccl/run_control_test.go` line 212 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/124564#gh-1610474638:-NyWcGmf3zGwYeyo6KxA:b-89y3qy) ([raw file](https://github.com/cockroachdb/cockroach/blob/b5263056a689bd2ee660cdb5d8073120c160550c/pkg/ccl/testccl/sqlccl/run_control_test.go#L212)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

nit: this might be simplified a little with `testutils.SucceedsSoon`. here's an existing example: https://github.com/cockroachdb/cockroach/blob/3cd24e8377c219b1dd05ef612e0366bd5c3c3dad/pkg/sql/show_test.go#L695-L715
</blockquote></details>

Good point, thanks - I forgot about that helper, done.
