### PR TITLE
opt: fix selectivity estimates for index constraints

### LINKED ISSUE #31929: opt: incorrect index chosen when using LIKE
This case was encountered by a customer.
```
exec-ddl
CREATE TABLE abcde (
  a INT PRIMARY KEY,
  b INT,
  c STRING,
  d INT,
  e INT,
  INDEX bad(b, d),
  INDEX good(b, c, d)
)
----
TABLE abcde
 ├── a int not null
 ├── b int
 ├── c string
 ├── d int
 ├── e int
 ├── INDEX primary
 │    └── a int not null
 ├── INDEX bad
 │    ├── b int
 │    ├── d int
 │    └── a int not null
 └── INDEX good
      ├── b int
      ├── c string
      ├── d int
      └── a int not null

opt
SELECT * FROM abcde WHERE b = 1 AND c LIKE '+1-1000%'
----
select
 ├── columns: a:1(int!null) b:2(int!null) c:3(string) d:4(int) e:5(int)
 ├── key: (1)
 ├── fd: ()-->(2), (1)-->(3-5)
 ├── index-join abcde
 │    ├── columns: a:1(int!null) b:2(int) c:3(string) d:4(int) e:5(int)
 │    ├── key: (1)
 │    ├── fd: ()-->(2), (1)-->(3-5)
 │    └── scan abcde@bad
 │         ├── columns: a:1(int!null) b:2(int!null) d:4(int)
 │         ├── constraint: /2/4/1: [/1 - /1]
 │         ├── key: (1)
 │         └── fd: ()-->(2), (1)-->(4)
 └── filters [type=bool, outer=(3)]
      └── c LIKE '+1-1000%' [type=bool, outer=(3)]
```

The better plan is to use the other index where we can constrain the second column as well. It seems to be a stat issue, both plans estimate 10 rows for the scan even though one is strictly more constrained than the other:

```
New expression 1 of 2:
  select
   ├── columns: a:1(int!null) b:2(int!null) c:3(string) d:4(int) e:5(int)
   ├── stats: [rows=3.33333333, distinct(2)=1]
   ├── cost: 51.8
   ├── key: (1)
   ├── fd: ()-->(2), (1)-->(3-5)
   ├── prune: (1,4,5)
   ├── index-join abcde
   │    ├── columns: t.public.abcde.a:1(int!null) t.public.abcde.b:2(int) t.public.abcde.c:3(string) t.public.abcde.d:4(int) t.public.abcde.e:5(int)
   │    ├── stats: [rows=10]
   │    ├── cost: 51.7
   │    ├── key: (1)
   │    ├── fd: ()-->(2), (1)-->(3-5)
   │    └── scan abcde@bad
   │         ├── columns: t.public.abcde.a:1(int!null) t.public.abcde.b:2(int!null) t.public.abcde.d:4(int)
   │         ├── constraint: /2/4/1: [/1 - /1]
   │         ├── stats: [rows=10, distinct(2)=1]
   │         ├── cost: 10.6
   │         ├── key: (1)
   │         └── fd: ()-->(2), (1)-->(4)
   └── filters [type=bool, outer=(3)]
        └── like [type=bool, outer=(3)]
             ├── variable: t.public.abcde.c [type=string, outer=(3)]
             └── const: '+1-1000%' [type=string]

New expression 2 of 2:
  index-join abcde
   ├── columns: a:1(int!null) b:2(int!null) c:3(string) d:4(int) e:5(int)
   ├── stats: [rows=3.33333333, distinct(2)=1]
   ├── cost: 51.9
   ├── key: (1)
   ├── fd: ()-->(2), (1)-->(3-5)
   ├── prune: (1,4,5)
   └── scan abcde@good
        ├── columns: t.public.abcde.a:1(int!null) t.public.abcde.b:2(int!null) t.public.abcde.c:3(string!null) t.public.abcde.d:4(int)
        ├── constraint: /2/3/4/1: [/1/'+1-1000' - /1/'+1-1001')
        ├── stats: [rows=10, distinct(2)=1]
        ├── cost: 10.8
        ├── key: (1)
        └── fd: ()-->(2), (1)-->(3,4)
----
```

Note that this works fine on master, but not on release-2.1. We need to figure out which change fixed it, and whether it fixed the root cause or it's just by chance that this particular case is fixed.

CC @rytaft

### PR DESCRIPTION
**Pull request by rytaft**
Unlike the constraints found in Select and Join filters, an index
constraint may represent multiple conjuncts. Therefore, the selectivity
estimate for a Scan should account for the selectivity of each
constrained column in the index constraint. This commit fixes the
selectivity estimation in the optimizer to properly account for
each constrained column in a Scan.

Fixes #31929

Release note (bug fix): In some cases the optimizer was choosing
the wrong index for a scan because of incorrect selectivity
estimation. This estimation error has been fixed.

### CODE REVIEW

**Comment by RaduBerinde** [comment]
LGTM! Thanks for the quick fix!

**Review by rytaft — COMMENTED** [review]
TFTR! I suppose I should wait for two reviews since this will be backported?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/31937#-:-LPq-Eqy9ANTlXWn0srZ:biga7dq)* status: :shipit: complete! 0 of 0 LGTMs obtained

File: pkg/sql/opt/memo/statistics_builder.go [hunk 1]
```diff
@@ -454,22 +454,18 @@ func (sb *statisticsBuilder) buildScan(scan *ScanExpr, relProps *props.Relationa
 	if scan.Constraint != nil {
 		// Calculate distinct counts for constrained columns
 		// -------------------------------------------------
-		applied := sb.applyConstraint(scan.Constraint, scan, relProps)
+		numUnappliedConjuncts := sb.applyIndexConstraint(scan.Constraint, scan, relProps)
 
 		var cols opt.ColSet
-		for i := 0; i < scan.Constraint.Columns.Count(); i++ {
+		for i := 0; i < scan.Constraint.ConstrainedColumns(sb.evalCtx); i++ {
```
Comment (andy-kimball) [inline pkg/sql/opt/memo/statistics_builder.go]: You should use the `for i, n := 0, scan.Constraint.ConstrainedColumns(sb.evalCtx)` pattern. Otherwise, you're unnecessarily recomputing the constrained column count on each iteration.

File: pkg/sql/opt/memo/statistics_builder.go [hunk 2]
```diff
@@ -2102,7 +2106,7 @@ func (sb *statisticsBuilder) selectivityFromDistinctCounts(
 		oldDistinct := inputStat.DistinctCount
 
 		if oldDistinct != 0 && newDistinct < oldDistinct {
-			selectivity *= newDistinct / oldDistinct
+			selectivity *= min(newDistinct/oldDistinct, unknownFilterSelectivity)
```
Comment (andy-kimball) [inline pkg/sql/opt/memo/statistics_builder.go]: This `min` check will probably end up biting us later on, when we have more accurate distinct counts, and yet can never compute a selectivity > 1/3. I see why you have it here, and think it's right way to go to solve the short-term problem. But longer-term, it could be one of many small changes that seem harmless in isolation, but combine together to make the code fragile and filled with special cases.

**Review by andy-kimball — APPROVED** [review]
I've got some concerns, but think we should proceed with the fix (and continue to ponder how we can address concerns longer-term).

**Review by rytaft — COMMENTED** [review]
TFTR!

bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/31937#-:-LQ4ggaj0D-xsYtSCKLA:b-oduykh)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/opt/memo/statistics_builder.go, line 460 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/31937#-LPm0KLA3hy3exlQAgFe-r1-460:-LQ4gfKkEfpfFk3Ycvbg:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/841498ff589a678906e27c8e4bde4238af52c125/pkg/sql/opt/memo/statistics_builder.go#L460)):*
<details><summary><i>Previously, andy-kimball (Andy Kimball) wrote…</i></summary><blockquote>

You should use the `for i, n := 0, scan.Constraint.ConstrainedColumns(sb.evalCtx)` pattern. Otherwise, you're unnecessarily recomputing the constrained column count on each iteration.
</blockquote></details>

Done.
___
*[pkg/sql/opt/memo/statistics_builder.go, line 2109 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/31937#-LPm0KLA3hy3exlQAgFe-r1-2109:-LQ4gSes1tj4v4TYEf8c:bhu0s43) ([raw file](https://github.com/cockroachdb/cockroach/blob/841498ff589a678906e27c8e4bde4238af52c125/pkg/sql/opt/memo/statistics_builder.go#L2109)):*
<details><summary><i>Previously, andy-kimball (Andy Kimball) wrote…</i></summary><blockquote>

This `min` check will probably end up biting us later on, when we have more accurate distinct counts, and yet can never compute a selectivity > 1/3. I see why you have it here, and think it's right way to go to solve the short-term problem. But longer-term, it could be one of many small changes that seem harmless in isolation, but combine together to make the code fragile and filled with special cases.
</blockquote></details>

Based on our offline discussion, I've removed this change. It's not necessary for this particular fix, and it's not clear whether or not it's actually beneficial (as you pointed out).
