### PR TITLE
Fix timestamp regression bug in event txn epoch advances.

### LINKED ISSUE #782: timestamp regression in TestConcurrentIncrements
@BramGruneir had an interesting test failure tonight in `TestConcurrentIncrements`:

> I0423 22:22:41.904893      46 multiraft.go:699] Committed Entry[0]: 7/43 EntryNormal 13d7c4c61e50419a5c33383c18aca777: raft_id:1 cmd:<internal_resolve_intent:<header:<timestamp:<wall_time:1429827761901804411 logical:1 > cmd_id:<wall_time:0 random:0 > key:"value-1" end
	client_test.go:672: txn "test-1" {id=214d3af7-b297-48a6-bffc-75e4bd25e4da pri=1470248948, iso=SERIALIZABLE, stat=PENDING, epo=0, ts=1429827761.846319546,3 orig=1429827761.826247139,0 max=1429827761.826247139,0}: timestamp regression: 1429827761.846319546,5

the interesting bit is that the timestamp of the transaction above, `1429827761.846319546,3`, has moved back from its original timestamp `1429827761.846319546,5` (only the logical component has changed).

That suggests that somewhere, and very likely very close to where the error occured, we're losing the logical.

[Full log here](https://circleci.com/gh/cockroachdb/cockroach/1739)

ping @spencerkimball, @BramGruneir

### PR DESCRIPTION
**Pull request by spencerkimball**
Fixes #782

### CODE REVIEW

File: kv/txn_test.go [hunk 1]
```diff
@@ -640,3 +640,61 @@ func TestTxnRepeatGetWithRangeSplit(t *testing.T) {
 		t.Fatal(err)
 	}
 }
+
+// TestTxnRestartedSerializableTimestampRegression verifies that there is
+// no timestamp regression error in the event that a pushed txn record disagrees
+// with the original timestmap of a restarted transaction.
```
Comment (tschottdorf) [inline kv/txn_test.go]: s/stmap/stamp/

**Comment by tschottdorf** [comment]
LGTM

**Comment by mrtracy** [comment]
LGTM
