### PR TITLE
sql/schemachanger: version gate dropping constraints / functions

### LINKED ISSUE #97576: roachtest: schemachange/mixed-versions-compat failed
roachtest.schemachange/mixed-versions-compat [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/8803571?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/8803571?buildTab=artifacts#/schemachange/mixed-versions-compat) on master @ [e028ce5b14505dfd17ef8b13001c0ab8ac811e3c](https://github.com/cockroachdb/cockroach/commits/e028ce5b14505dfd17ef8b13001c0ab8ac811e3c):

```
validated TestLogic_drop_type_TestLogic_drop_type_DROP TYPE sc2.typ_0
validated TestLogic_drop_type_TestLogic_drop_type_DROP TYPE t, t_0
validated TestLogic_drop_type_TestLogic_drop_type_DROP TYPE t1_0
validated TestLogic_drop_type_TestLogic_drop_type_DROP TYPE t2_0
validated TestLogic_drop_type_TestLogic_drop_type_DROP TYPE t3_0
validated TestLogic_drop_type_TestLogic_drop_type_DROP TYPE t4_0
validated TestLogic_drop_type_TestLogic_drop_type_DROP TYPE t_0
validated TestLogic_drop_type_TestLogic_drop_type_DROP VIEW v_0
validated TestLogic_drop_view_TestLogic_drop_view_DROP DATABASE a CASCADE_0
validated TestLogic_drop_view_TestLogic_drop_view_DROP DATABASE defaultdb CASCADE_0
validated TestLogic_drop_view_TestLogic_drop_view_DROP DATABASE test CASCADE_0
validated TestLogic_drop_view_TestLogic_drop_view_DROP TABLE a CASCADE_0
validated TestLogic_drop_view_TestLogic_drop_view_DROP VIEW testuser1 CASCADE_0
validated TestLogic_drop_view_TestLogic_drop_view_DROP VIEW testuser3_0
validated TestLogic_drop_view_TestLogic_drop_view_DROP VIEW x, y_0
validated TestLogic_drop_view_TestLogic_drop_view_DROP VIEW y, x_0
validated TestLogic_gc_job_mixed_TestLogic_gc_job_mixed_ALTER TABLE db.kv ALTER PRIMARY KEY USING COLUMNS (k)_0
validated TestLogic_gc_job_mixed_TestLogic_gc_job_mixed_ALTER TABLE db.kv ALTER PRIMARY KEY USING COLUMNS (k)_1
validated TestLogic_gc_job_mixed_TestLogic_gc_job_mixed_ALTER TABLE db.kv ALTER PRIMARY KEY USING COLUMNS (k)_10
validated TestLogic_gc_job_mixed_TestLogic_gc_job_mixed_ALTER TABLE db.kv ALTER PRIMARY KEY USING COLUMNS (k)_11
validated TestLogic_gc_job_mixed_TestLogic_gc_job_mixed_ALTER TABLE db.kv ALTER PRIMARY KEY USING COLUMNS (k)_12
validated TestLogic_gc_job_mixed_TestLogic_gc_job_mixed_ALTER TABLE db.kv ALTER PRIMARY KEY USING COLUMNS (k)_13
validated TestLogic_gc_job_mixed_TestLogic_gc_job_mixed_ALTER TABLE db.kv ALTER PRIMARY KEY USING COLUMNS (k)_14
validated TestLogic_gc_job_mixed_TestLogic_gc_job_mixed_ALTER TABLE db.kv ALTER PRIMARY KEY USING COLUMNS (k)_15
validated TestLogic_gc_job_mixed_TestLogic_gc_job_mixed_ALTER TABLE db.kv ALTER PRIMARY KEY USING COLUMNS (k)_16
validated TestLogic_gc_job_mixed_TestLogic_gc_job_mixed_ALTER TABLE db.kv ALTER PRIMARY KEY USING COLUMNS (k)_17
validated TestLogic_gc_job_mixed_TestLogic_gc_job_mixed_ALTER TABLE db.kv ALTER PRIMARY KEY USING COLUMNS (k)_18
validated TestLogic_gc_job_mixed_TestLogic_gc_job_mixed_ALTER TABLE db.kv ALTER PRIMARY KEY USING COLUMNS (k)_2
validated TestLogic_gc_job_mixed_TestLogic_gc_job_mixed_ALTER TABLE db.kv ALTER PRIMARY KEY USING COLUMNS (k)_3
validated TestLogic_gc_job_mixed_TestLogic_gc_job_mixed_ALTER TABLE db.kv ALTER PRIMARY KEY USING COLUMNS (k)_4
validated TestLogic_gc_job_mixed_TestLogic_gc_job_mixed_ALTER TABLE db.kv ALTER PRIMARY KEY USING COLUMNS (k)_5
validated TestLogic_gc_job_mixed_TestLogic_gc_job_mixed_ALTER TABLE db.kv ALTER PRIMARY KEY USING COLUMNS (k)_6
validated TestLogic_gc_job_mixed_TestLogic_gc_job_mixed_ALTER TABLE db.kv ALTER PRIMARY KEY USING COLUMNS (k)_7
validated TestLogic_gc_job_mixed_TestLogic_gc_job_mixed_ALTER TABLE db.kv ALTER PRIMARY KEY USING COLUMNS (k)_8
validated TestLogic_gc_job_mixed_TestLogic_gc_job_mixed_ALTER TABLE db.kv ALTER PRIMARY KEY USING COLUMNS (k)_9
validated TestLogic_gc_job_mixed_TestLogic_gc_job_mixed_DROP DATABASE db_0
validated TestLogic_gc_job_mixed_TestLogic_gc_job_mixed_DROP DATABASE defaultdb CASCADE_0
validated TestLogic_gc_job_mixed_TestLogic_gc_job_mixed_DROP DATABASE test CASCADE_0
validated TestLogic_gc_job_mixed_TestLogic_gc_job_mixed_DROP TABLE db.kv_0, W230223 16:55:24.581810 1 sql/schemachanger/scplan/plan.go:122  [-] 1  failed building declarative schema changer plan in PostCommitNonRevertiblePhase (rollback=false) for ALTER TABLE with error: invalid execution plan: final status is VALIDATED instead of ABSENT at index 15 for adding ForeignKeyConstraint:{DescID: 110, ConstraintID: 2, ReferencedDescID: 107}
W230223 16:55:24.588003 1 sql/schemachanger/scplan/plan.go:122  [-] 2  failed building declarative schema changer plan in PostCommitNonRevertiblePhase (rollback=false) for ALTER TABLE with error: invalid execution plan: final status is VALIDATED instead of ABSENT at index 15 for adding ForeignKeyConstraint:{DescID: 110, ConstraintID: 2, ReferencedDescID: 107}
W230223 16:55:24.593982 1 sql/schemachanger/scplan/plan.go:122  [-] 3  failed building declarative schema changer plan in PostCommitNonRevertiblePhase (rollback=false) for ALTER TABLE with error: invalid execution plan: final status is VALIDATED instead of ABSENT at index 15 for adding ForeignKeyConstraint:{DescID: 110, ConstraintID: 2, ReferencedDescID: 107}
W230223 16:55:24.599962 1 sql/schemachanger/scplan/plan.go:122  [-] 4  failed building declarative schema changer plan in PostCommitNonRevertiblePhase (rollback=false) for ALTER TABLE with error: invalid execution plan: final status is VALIDATED instead of ABSENT at index 15 for adding ForeignKeyConstraint:{DescID: 110, ConstraintID: 2, ReferencedDescID: 107}
W230223 16:55:24.605882 1 sql/schemachanger/scplan/plan.go:122  [-] 5  failed building declarative schema changer plan in PostCommitNonRevertiblePhase (rollback=false) for ALTER TABLE with error: invalid execution plan: final status is VALIDATED instead of ABSENT at index 15 for adding ForeignKeyConstraint:{DescID: 110, ConstraintID: 2, ReferencedDescID: 107}
W230223 16:55:24.611867 1 sql/schemachanger/scplan/plan.go:122  [-] 6  failed building declarative schema changer plan in PostCommitNonRevertiblePhase (rollback=false) for ALTER TABLE with error: invalid execution plan: final status is VALIDATED instead of ABSENT at index 15 for adding ForeignKeyConstraint:{DescID: 110, ConstraintID: 2, ReferencedDescID: 107}
W230223 16:55:24.617807 1 sql/schemachanger/scplan/plan.go:122  [-] 7  failed building declarative schema changer plan in PostCommitNonRevertiblePhase (rollback=false) for ALTER TABLE with error: invalid execution plan: final status is VALIDATED instead of ABSENT at index 15 for adding ForeignKeyConstraint:{DescID: 110, ConstraintID: 2, ReferencedDescID: 107}
W230223 16:55:24.623878 1 sql/schemachanger/scplan/plan.go:122  [-] 8  failed building declarative schema changer plan in PostCommitNonRevertiblePhase (rollback=false) for ALTER TABLE with error: invalid execution plan: final status is VALIDATED instead of ABSENT at index 15 for adding ForeignKeyConstraint:{DescID: 110, ConstraintID: 2, ReferencedDescID: 107}
W230223 16:55:24.629952 1 sql/schemachanger/scplan/plan.go:122  [-] 9  failed building declarative schema changer plan in PostCommitNonRevertiblePhase (rollback=false) for ALTER TABLE with error: invalid execution plan: final status is VALIDATED instead of ABSENT at index 15 for adding ForeignKeyConstraint:{DescID: 110, ConstraintID: 2, ReferencedDescID: 107}
W230223 16:55:24.635978 1 sql/schemachanger/scplan/plan.go:122  [-] 10  failed building declarative schema changer plan in PostCommitNonRevertiblePhase (rollback=false) for ALTER TABLE with error: invalid execution plan: final status is VALIDATED instead of ABSENT at index 15 for adding ForeignKeyConstraint:{DescID: 110, ConstraintID: 2, ReferencedDescID: 107}
ERROR: invalid execution plan: final status is VALIDATED instead of ABSENT at index 15 for adding ForeignKeyConstraint:{DescID: 110, ConstraintID: 2, ReferencedDescID: 107}
Failed running "debug declarative-corpus-validate"
```
<p>Parameters: <code>ROACHTEST_cloud=gce</code>
, <code>ROACHTEST_cpu=4</code>
, <code>ROACHTEST_encrypted=false</code>
, <code>ROACHTEST_fs=ext4</code>
, <code>ROACHTEST_localSSD=true</code>
, <code>ROACHTEST_ssd=0</code>
</p>
<details><summary>Help</summary>
<p>

See: [roachtest README](https://github.com/cockroachdb/cockroach/blob/master/pkg/cmd/roachtest/README.md)

See: [How To Investigate \(internal\)](https://cockroachlabs.atlassian.net/l/c/SSSBr8c7)

</p>
</details>
/cc @cockroachdb/sql-schema
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*schemachange/mixed-versions-compat.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)
</sub>

Jira issue: CRDB-24767

### PR DESCRIPTION
**Pull request by fqazi**
Previously, it was possible in a mixed version state to cleanup constraints (foreign keys, unique without indexes, function bodies) when dropping columns. This would cause down level nodes to fail at planning seeing unsupported status transitions. To address this, this patch adds a version gate to prevent dropping any of these objects when cleaning up a column.

Fixes: #97576

Release note: None

### CODE REVIEW

File: pkg/sql/schemachanger/scbuild/internal/scbuildstmt/alter_table_drop_column.go [hunk 1]
```diff
@@ -246,6 +247,12 @@ func dropColumn(
 				undroppedSeqBackrefsToCheck.Add(e.SequenceID)
 			}
 		case *scpb.FunctionBody:
+			// Until the appropriate version gate is hit, we still do not allow
+			// dropping function bodies.
+			if !b.ClusterSettings().Version.IsActive(b, clusterversion.V23_1) {
```
Comment (chengxiong-ruan) [inline pkg/sql/schemachanger/scbuild/internal/scbuildstmt/alter_table_drop_column.go:252]: Unfortunately this is not enough for function because function elements are skipped before `v23_1` during decomposition. And funny that `Owner` element is not version gated, so I ran into some mixed version test error in #97631, so I added [this version gate ](https://github.com/cockroachdb/cockroach/pull/97631/files#diff-21dd460f3a39bc0cf0a7b11db9436f38bc6ac3c3e415e154b1e87cd11689c74fR120)to fallback all function relevant things until 23.1.

**Review by fqazi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/97769)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @chengxiong-ruan)

___
*[`pkg/sql/schemachanger/scbuild/internal/scbuildstmt/alter_table_drop_column.go` line 252 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/97769#-NPKJ7rOVjc6j5Nr7M_t-r1-252:-NPNRdaI4_0zUzrRRz0W:b-rjh285) ([raw file](https://github.com/cockroachdb/cockroach/blob/d427d3bf259408f64180a5a451a771fb20082812/pkg/sql/schemachanger/scbuild/internal/scbuildstmt/alter_table_drop_column.go#L252)):*
<details><summary><i>Previously, chengxiong-ruan (Chengxiong Ruan) wrote…</i></summary><blockquote>

Unfortunately this is not enough for function because function elements are skipped before `v23_1` during decomposition. And funny that `Owner` element is not version gated, so I ran into some mixed version test error in #97631, so I added [this version gate ](https://github.com/cockroachdb/cockroach/pull/97631/files#diff-21dd460f3a39bc0cf0a7b11db9436f38bc6ac3c3e415e154b1e87cd11689c74fR120)to fallback all function relevant things until 23.1. 

You may remove this version gate you're adding.
</blockquote></details>

Ah, that makes sense because it impacts DROP DATABSASE, etc..

Done.

**Review by chengxiong-ruan — APPROVED** [review]
LGTM!

**Comment by fqazi** [comment]
@chengxiong-ruan TFTR!

bors r+
