### PR TITLE
cli: deflake/strengthen TestLossOfQuorumRecovery

### LINKED ISSUE #161502: cli: TestLossOfQuorumRecovery failed
cli.TestLossOfQuorumRecovery [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Ci_TestsIbmCloudLinuxS390x_UnitTestsS390x/20998338?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Ci_TestsIbmCloudLinuxS390x_UnitTestsS390x/20998338?buildTab=artifacts#/) on master @ [ab9a17f7cc0567df7f89d066421180e198b556ea](https://github.com/cockroachdb/cockroach/commits/ab9a17f7cc0567df7f89d066421180e198b556ea):

```
=== RUN   TestLossOfQuorumRecovery
    test_log_scope.go:172: test logs captured to: /artifacts/tmp/_tmp/8b81fbed93efb7ab499843cacefe9048/logTestLossOfQuorumRecovery2043435851
    test_log_scope.go:82: use -show-logs to present logs inline
[debug recover collect-info --store=/artifacts/tmp/_tmp/8b81fbed93efb7ab499843cacefe9048/TestLossOfQuorumRecovery2290263589/store-1 /artifacts/tmp/_tmp/8b81fbed93efb7ab499843cacefe9048/TestLossOfQuorumRecovery2290263589/node-1.json]
debug recover collect-info --store=/artifacts/tmp/_tmp/8b81fbed93efb7ab499843cacefe9048/TestLossOfQuorumRecovery2290263589/store-1 /artifacts/tmp/_tmp/8b81fbed93efb7ab499843cacefe9048/TestLossOfQuorumRecovery2290263589/node-1.json
Collected recovery info from:
nodes             1
stores            1
Collected info:
replicas          81
range descriptors 0
[debug recover make-plan --confirm=y --plan=/artifacts/tmp/_tmp/8b81fbed93efb7ab499843cacefe9048/TestLossOfQuorumRecovery2290263589/recovery-plan.json /artifacts/tmp/_tmp/8b81fbed93efb7ab499843cacefe9048/TestLossOfQuorumRecovery2290263589/node-1.json]
[debug recover apply-plan --confirm=y --store=/artifacts/tmp/_tmp/8b81fbed93efb7ab499843cacefe9048/TestLossOfQuorumRecovery2290263589/store-1 /artifacts/tmp/_tmp/8b81fbed93efb7ab499843cacefe9048/TestLossOfQuorumRecovery2290263589/recovery-plan.json]

id	is_live	replicas	is_decommissioning	membership	is_draining
2	false	76	true	decommissioning	false
3	false	76	true	decommissioning	false
    debug_recover_loss_of_quorum_test.go:311: 
        	Error Trace:	
        	Error:      	Not equal: 
        	            	expected: "{1,4,5}"
        	            	actual  : "{1,2,3}"
        	            	
        	            	Diff:
        	            	--- Expected
        	            	+++ Actual
        	            	@@ -1 +1 @@
        	            	-{1,4,5}
        	            	+{1,2,3}
        	Test:       	TestLossOfQuorumRecovery
        	Messages:   	Replicas after loss of quorum recovery
    panic.go:615: -- test log scope end --
test logs left over in: /artifacts/tmp/_tmp/8b81fbed93efb7ab499843cacefe9048/logTestLossOfQuorumRecovery2043435851
--- FAIL: TestLossOfQuorumRecovery (354.93s)
```
<details><summary>Help</summary>
<p>

See also: [How To Investigate a Go Test Failure \(internal\)](https://cockroachlabs.atlassian.net/l/c/HgfXfJgM)
</p>
</details>
/cc @cockroachdb/kv-triage @cockroachdb/server
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*TestLossOfQuorumRecovery.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/bazci/githubpost/issues)

</sub>

Jira issue: CRDB-58913

### PR DESCRIPTION
**Pull request by pav-kv**
The test flakes when `WaitForFullReplication` returns too early. Under overload, nodes become unavailable and skew replica counter metrics which this function relies on. Don't rely on it too much: wait for the final "interesting" condition to materialize: all ranges are moved from the decommissioned nodes to the new ones.

Fixes #161502

### CODE REVIEW

File: pkg/cli/debug_recover_loss_of_quorum_test.go [hunk 1]
```diff
@@ -283,33 +282,42 @@ func TestLossOfQuorumRecovery(t *testing.T) {
...
+			var rangeID int
+			var replicas string
+			if err := rows.Scan(&rangeID, &replicas); err != nil {
+				return err
+			} else if replicas != wantReplicas {
+				return errors.Errorf("r%d not reconfigured, replicas: %s", rangeID, replicas)
+			}
+		}
+		return rows.Err()
+	}, testutils.SucceedsSoonDuration()*2)
```
Comment (miraradeva) [inline pkg/cli/debug_recover_loss_of_quorum_test.go:313]: Do we have evidence to believe that the `testutils.SucceedsSoonDuration()` is not sufficient?

**Review by miraradeva — APPROVED** [review]
LGTM!

File: pkg/cli/debug_recover_loss_of_quorum_test.go (hunk 1 above)
Comment (pav-kv) [reply pkg/cli/debug_recover_loss_of_quorum_test.go:313]: Some background. I tried removing `WaitForFullReplication` and `WaitForZoneConfigPropagation`, and just wait for the "final" symptom here. For some reason, that made the test significantly slower (before 40s, after 100s). Might be that there is a lot of contention on the `ranges` table while the reconfigurations are happening. So I put the above waits back.

However, I imagine in our flaky scenario when `WaitForFullReplication` returns too optimistically, we can hit this contention. So I doubled the timeout JIC.
