### PR TITLE
roachtest: fix warehouse count increase in disagg-rebalance

### LINKED ISSUE #127507: roachtest: disagg-rebalance/aws/n4cpu4 failed
roachtest.disagg-rebalance/aws/n4cpu4 [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyAwsBazel/16145921?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyAwsBazel/16145921?buildTab=artifacts#/disagg-rebalance/aws/n4cpu4) on master @ [59be0708627bb27f49d8976182062c6886d64282](https://github.com/cockroachdb/cockroach/commits/59be0708627bb27f49d8976182062c6886d64282):

```
(disagg_rebalance.go:109).3: dial tcp 3.145.206.254:26257: connect: connection refused
test artifacts and logs in: /artifacts/disagg-rebalance/aws/n4cpu4/cpu_arch=arm64/run_1
```

Parameters:
 - <code>ROACHTEST_arch=arm64</code>
 - <code>ROACHTEST_cloud=aws</code>
 - <code>ROACHTEST_coverageBuild=false</code>
 - <code>ROACHTEST_cpu=4</code>
 - <code>ROACHTEST_encrypted=false</code>
 - <code>ROACHTEST_metamorphicBuild=false</code>
 - <code>ROACHTEST_ssd=0</code>
<details><summary>Help</summary>
<p>

See: [roachtest README](https://github.com/cockroachdb/cockroach/blob/master/pkg/cmd/roachtest/README.md)

See: [How To Investigate \(internal\)](https://cockroachlabs.atlassian.net/l/c/SSSBr8c7)

_Grafana is not yet available for aws clusters_</p>
</details>
<details><summary>Same failure on other branches</summary>
<p>

- #127505 roachtest: disagg-rebalance/aws/n4cpu4 failed [A-storage C-test-failure O-roachtest O-robot T-storage branch-release-24.1 release-blocker]
</p>
</details>
/cc @cockroachdb/storage
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*disagg-rebalance/aws/n4cpu4.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/bazci/githubpost/issues)
</sub>

Jira issue: CRDB-40459

### PR DESCRIPTION
**Pull request by itsbilal**
Previously, we increased the warehouse count in the disagg-rebalance roachtest to make it less flaky. However this greatly increased the amount of time it takes for TPCC consistency checks to run, especially on top of disaggregated storage. This change disables those checks and reduces the active warehouse count back down to reduce the amount of foreground resource utilization while leaving the imported warehouse count be larger.

Fixes #127507.

Epic: none

Release note: None

### CODE REVIEW

File: pkg/cmd/roachtest/tests/disagg_rebalance.go [hunk 1]
```diff
@@ -44,10 +44,11 @@ func registerDisaggRebalance(r registry.Registry) {
 
 			initialWaitDuration := 2 * time.Minute
 			warehouses := 1000
+			activeWarehouses := 20
 
 			t.Status("workload initialization")
 			cmd := fmt.Sprintf(
-				"./cockroach workload fixtures import tpcc --warehouses=%d {pgurl:1}",
+				"./cockroach workload fixtures import tpcc --warehouses=%d --checks=false {pgurl:1}",
```
Comment (RaduBerinde) [inline pkg/cmd/roachtest/tests/disagg_rebalance.go:51]: We should add a comment here explaining why we turned off the checks.

**Review by RaduBerinde — APPROVED** [review]

**Comment by itsbilal** [comment]
TFTR!

bors r=RaduBerinde
