### PR TITLE
sqlmigrations: fix handling of mutations in schema change job migration

### LINKED ISSUE #48786: sqlmigrations: v20.1.0: out of bounds panic
This issue was autofiled by Sentry. It represents a crash or reported error on a live cluster with telemetry enabled.

Sentry link: https://sentry.io/organizations/cockroach-labs/issues/1662945493/?referrer=webhooks_plugin

Panic message:

>panic.go:679: runtime.boundsError: runtime error: index out of range [0] with length 0

<details>
<summary>Stacktrace (expand for inline code snippets):</summary>

/usr/local/go/src/runtime/panic.go#L678-L680 in runtime.gopanic
/usr/local/go/src/runtime/panic.go#L74-L76 in runtime.goPanicIndex
https://github.com/cockroachdb/cockroach/blob/9d456b9ec82cbf9a740a092c0d9f56da48779689/pkg/sqlmigrations/migrations.go#L1033-L1035 in pkg/sqlmigrations.migrateMutationJobForTable.func1
https://github.com/cockroachdb/cockroach/blob/9d456b9ec82cbf9a740a092c0d9f56da48779689/pkg/jobs/update.go#L137-L139 in pkg/jobs.(*Job).Update.func1
https://github.com/cockroachdb/cockroach/blob/9d456b9ec82cbf9a740a092c0d9f56da48779689/pkg/jobs/jobs.go#L653-L655 in pkg/jobs.(*Job).runInTxn
https://github.com/cockroachdb/cockroach/blob/9d456b9ec82cbf9a740a092c0d9f56da48779689/pkg/jobs/update.go#L106-L108 in pkg/jobs.(*Job).Update
https://github.com/cockroachdb/cockroach/blob/9d456b9ec82cbf9a740a092c0d9f56da48779689/pkg/sqlmigrations/migrations.go#L1018-L1020 in pkg/sqlmigrations.migrateMutationJobForTable
https://github.com/cockroachdb/cockroach/blob/9d456b9ec82cbf9a740a092c0d9f56da48779689/pkg/sqlmigrations/migrations.go#L806-L808 in pkg/sqlmigrations.migrateSchemaChangeJobs.func1
https://github.com/cockroachdb/cockroach/blob/9d456b9ec82cbf9a740a092c0d9f56da48779689/pkg/kv/db.go#L701-L703 in pkg/kv.(*DB).Txn.func1
https://github.com/cockroachdb/cockroach/blob/9d456b9ec82cbf9a740a092c0d9f56da48779689/pkg/kv/txn.go#L795-L797 in pkg/kv.(*Txn).exec
https://github.com/cockroachdb/cockroach/blob/9d456b9ec82cbf9a740a092c0d9f56da48779689/pkg/kv/db.go#L700-L702 in pkg/kv.(*DB).Txn
https://github.com/cockroachdb/cockroach/blob/9d456b9ec82cbf9a740a092c0d9f56da48779689/pkg/sqlmigrations/migrations.go#L770-L772 in pkg/sqlmigrations.migrateSchemaChangeJobs
https://github.com/cockroachdb/cockroach/blob/9d456b9ec82cbf9a740a092c0d9f56da48779689/pkg/sqlmigrations/migrations.go#L709-L711 in pkg/sqlmigrations.(*Manager).StartSchemaChangeJobMigration.func1
https://github.com/cockroachdb/cockroach/blob/9d456b9ec82cbf9a740a092c0d9f56da48779689/pkg/util/stop/stopper.go#L322-L324 in pkg/util/stop.(*Stopper).RunAsyncTask.func1
</details>

```
/usr/local/go/src/runtime/panic.go in runtime.gopanic at line 679
/usr/local/go/src/runtime/panic.go in runtime.goPanicIndex at line 75
pkg/sqlmigrations/migrations.go in pkg/sqlmigrations.migrateMutationJobForTable.func1 at line 1034
pkg/jobs/update.go in pkg/jobs.(*Job).Update.func1 at line 138
pkg/jobs/jobs.go in pkg/jobs.(*Job).runInTxn at line 654
pkg/jobs/update.go in pkg/jobs.(*Job).Update at line 107
pkg/sqlmigrations/migrations.go in pkg/sqlmigrations.migrateMutationJobForTable at line 1019
pkg/sqlmigrations/migrations.go in pkg/sqlmigrations.migrateSchemaChangeJobs.func1 at line 807
pkg/kv/db.go in pkg/kv.(*DB).Txn.func1 at line 702
pkg/kv/txn.go in pkg/kv.(*Txn).exec at line 796
pkg/kv/db.go in pkg/kv.(*DB).Txn at line 701
pkg/sqlmigrations/migrations.go in pkg/sqlmigrations.migrateSchemaChangeJobs at line 771
pkg/sqlmigrations/migrations.go in pkg/sqlmigrations.(*Manager).StartSchemaChangeJobMigration.func1 at line 710
pkg/util/stop/stopper.go in pkg/util/stop.(*Stopper).RunAsyncTask.func1 at line 323
```

| Tag | Value |
|---|---|
| Cockroach Release | `v20.1.0` |
| Cockroach SHA: | 9d456b9ec82cbf9a740a092c0d9f56da48779689 |
| Platform | linux amd64 |
| Distribution | CCL |
| Environment | v20.1.0 |
| Command | server |
| Go Version | `go1.13.9`|
| # of CPUs |8 |
| # of Goroutines |249 |

### PR DESCRIPTION
**Pull request by thoszhang**
The migration for schema change jobs assumed that a table descriptor's
`MutationJobs` were always synced with `Mutations`, so we were indexing
into `Mutations` with the `MutationJobs` index. In practice, if this
assumption doesn't hold due to some previous buggy schema change, we
risk crashing with an out of bounds error or looking up the wrong
mutation. This PR adds a step to find the mutation with the expected ID
and mark the job as failed if the mutation doesn't exist.

Fixes #48786.

Release note (bug fix): Fix a problem introduced in v20.1.0 where the
migration for ongoing schema change jobs would cause the node to panic
with an index out of bounds error, upon encountering a malformed table
descriptor with no schema change mutation corresponding to the job to be
migrated.

### CODE REVIEW

File: pkg/sqlmigrations/migrations.go [hunk 1]
```diff
@@ -1020,9 +1020,27 @@ func migrateMutationJobForTable(
...
+		var mutation *sqlbase.DescriptorMutation
+		found := false
+		for i := range tableDesc.Mutations {
+			if tableDesc.Mutations[i].MutationID == mutationJob.MutationID {
+				mutation = &tableDesc.Mutations[i]
+				found = true
+				break
+			}
+		}
+		if !found {
```
Comment (pbardea) [inline pkg/sqlmigrations/migrations.go:1035]: Does it make sense to check if `mutation` is nil rather than maintaining the `found` flag? I think this would provide a stronger guarantee.

File: pkg/sqlmigrations/migrations.go [hunk 2]
```diff
@@ -1020,9 +1020,27 @@ func migrateMutationJobForTable(
...
+			// In theory, MutationJobs and Mutations are synced with each other, so
```
Comment (pbardea) [inline pkg/sqlmigrations/migrations.go:1036]: I think it may be worth mentioning what is meant by "synced" here. Additionally, it may also be worth clarifying that `MutationJobs[i]` corresponds to `Mutations[i]` on 19.2 - which is the version we're migrating from (I don't think this is true anymore in 20.1 due to primary schema changes).

File: pkg/sql/schema_change_migrations_test.go [hunk 3]
```diff
@@ -905,3 +905,75 @@ func TestGCJobCreated(t *testing.T) {
 		[][]string{{"1"}},
 	)
 }
+
+// TestMissingMutation tests that a malformed table descriptor with a
+// MutationJob but no Mutation for the given job causes the job to fail with an
+// error.
+func TestMissingMutation(t *testing.T) {
```
Comment (pbardea) [inline pkg/sql/schema_change_migrations_test.go:912]: nit: may be useful to include that this is a regression test for #48786 to have a concrete example to point to.

**Review by pbardea — APPROVED** [review]
LGTM mod minor comments

**Review by ajwerner — COMMENTED** [review]
same

> Reviewed 1 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/48823#-:-M7EwaDy0ALfIfaN0kal:bb7od0r)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @lucy-zhang, and @pbardea)

___
*[pkg/sqlmigrations/migrations.go, line 1035 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/48823#-M7EJLkVryBM9JVngTOm-r1-1035:-M7EwLanBTCQOCuvEsu0:b-3aktkz) ([raw file](https://github.com/cockroachdb/cockroach/blob/9f43bc680119e127693cd6f003a605d2ff76faba/pkg/sqlmigrations/migrations.go#L1035)):*
<details><summary><i>Previously, pbardea (Paul Bardea) wrote…</i></summary><blockquote>

Does it make sense to check if `mutation` is nil rather than maintaining the `found` flag? I think this would provide a stronger guarantee.
</blockquote></details>

I like this.

**Review by thoszhang — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/48823)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner and @pbardea)

___
*[pkg/sql/schema_change_migrations_test.go, line 912 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/48823#-M7EsqlcsYG8LLpcD3H2-r1-912:-M7F1q9pB3a0Bk-OOCq4:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/9f43bc680119e127693cd6f003a605d2ff76faba/pkg/sql/schema_change_migrations_test.go#L912)):*
<details><summary><i>Previously, pbardea (Paul Bardea) wrote…</i></summary><blockquote>

nit: may be useful to include that this is a regression test for `#48786` to have a concrete example to point to.
</blockquote></details>

Done.
___
*[pkg/sqlmigrations/migrations.go, line 1035 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/48823#-M7EJLkVryBM9JVngTOm-r1-1035:-M7F3DrHEDr0R_KrZPD_:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/9f43bc680119e127693cd6f003a605d2ff76faba/pkg/sqlmigrations/migrations.go#L1035)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

I like this. 
</blockquote></details>

Done.
___
*[pkg/sqlmigrations/migrations.go, line 1036 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/48823#-M7EJLkVryBM9JVngTOm-r1-1036:-M7F2Wyc77205N9xoPEc:bircq8k) ([raw file](https://github.com/cockroachdb/cockroach/blob/9f43bc680119e127693cd6f003a605d2ff76faba/pkg/sqlmigrations/migrations.go#L1036)):*
Done.

> I don't think this is true anymore in 20.1 due to primary key swap schema changes

I did not know this. Maybe this bug can happen if someone upgraded to an alpha and did a primary key change?

**Comment by lucy-zhang** [comment]
TFTRs

bors r+

**Comment by lucy-zhang** [comment]
Never mind, this is failing on stressrace.

bors r-

**Comment by lucy-zhang** [comment]
There was a data race in the test itself, which I made a trivial change to fix. I stressed it locally and didn't get any failures. I'll wait for the TC run to finish and then merge.
