### PR TITLE
roachtest: fix hibernate test flake caused by leaked statement_timeout

### LINKED ISSUE #165544: roachtest: multi-region/super-region-failover failed
roachtest.multi-region/super-region-failover [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/21237683?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/21237683?buildTab=artifacts#/multi-region/super-region-failover) on master @ [36dceff5c0dd3125dfe941c051c87fe0ba7ea23a](https://github.com/cockroachdb/cockroach/commits/36dceff5c0dd3125dfe941c051c87fe0ba7ea23a):

Failed with:

```
(assertions.go:387).Fail: 
	Error Trace:	pkg/cmd/roachtest/tests/super_region_failover.go:172
	            				pkg/cmd/roachtest/tests/super_region_failover.go:129
	            				pkg/cmd/roachtest/tests/super_region_failover.go:55
	            				pkg/cmd/roachtest/test_runner.go:1559
	            				src/runtime/asm_amd64.s:1693
	Error:      	Received unexpected error:
	            	pq: parameter "enable_super_regions" cannot be changed
	Test:       	multi-region/super-region-failover
	Messages:   	failed to execute: ALTER ROLE ALL SET enable_super_regions = 'on'
(require.go:1401).NoError: FailNow called
test artifacts and logs in: /artifacts/multi-region/super-region-failover/run_1
```
Cluster Node to Ip Mapping:
| Node | Public IP | Private IP |
| --- | --- | --- |
| teamcity-21237683-1773296762-165-n12cpu2lm-geo-0001 | 34.39.115.216 | 10.154.0.20 |
| teamcity-21237683-1773296762-165-n12cpu2lm-geo-0002 | 34.13.31.90 | 10.154.0.6 |
| teamcity-21237683-1773296762-165-n12cpu2lm-geo-0003 | 34.105.179.94 | 10.154.0.8 |
| teamcity-21237683-1773296762-165-n12cpu2lm-geo-0004 | 34.73.130.195 | 10.142.0.140 |
| teamcity-21237683-1773296762-165-n12cpu2lm-geo-0005 | 35.229.115.240 | 10.142.0.133 |
| teamcity-21237683-1773296762-165-n12cpu2lm-geo-0006 | 34.26.103.105 | 10.142.0.137 |
| teamcity-21237683-1773296762-165-n12cpu2lm-geo-0007 | 34.68.112.143 | 10.128.0.65 |
| teamcity-21237683-1773296762-165-n12cpu2lm-geo-0008 | 136.116.197.2 | 10.128.0.66 |
| teamcity-21237683-1773296762-165-n12cpu2lm-geo-0009 | 136.116.103.82 | 10.128.0.68 |
| teamcity-21237683-1773296762-165-n12cpu2lm-geo-0010 | 8.229.207.238 | 10.138.0.14 |
| teamcity-21237683-1773296762-165-n12cpu2lm-geo-0011 | 136.117.157.223 | 10.138.0.6 |
| teamcity-21237683-1773296762-165-n12cpu2lm-geo-0012 | 136.109.43.107 | 10.138.0.16 |

Parameters:
 - <code>arch=amd64</code>
 - <code>cloud=gce</code>
 - <code>coverageBuild=false</code>
 - <code>cpu=2</code>
 - <code>diskCount=0</code>
 - <code>encrypted=false</code>
 - <code>fs=ext4</code>
 - <code>localSSD=true</code>
 - <code>runtimeAssertionsBuild=false</code>
<details><summary>Help</summary>
<p>

See: [roachtest README](https://github.com/cockroachdb/cockroach/blob/master/pkg/cmd/roachtest/README.md)

See: [How To Investigate \(internal\)](https://cockroachlabs.atlassian.net/l/c/SSSBr8c7)

See: [Grafana](https://go.crdb.dev/roachtest-grafana/teamcity-21237683/multi-region-super-region-failover/1773328846249/1773329605925)

</p>
</details>
/cc @cockroachdb/sql-foundations
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*multi-region/super-region-failover.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/bazci/githubpost/issues)

</sub>

Jira issue: CRDB-61442

### PR DESCRIPTION
**Pull request by spilchen**
Previously, the hibernate roachtest was flaky because Hibernate's `withJdbcTimeout` sets a 1-second `statement_timeout` via a session-level SET, and unlike PostgreSQL, CockroachDB does not revert session-level SET on transaction rollback. This caused the timeout to leak into subsequent tests, which would then fail with "query execution canceled due to statement timeout".

To address this, apply the upstream Hibernate fix (commit 456194394d) as a patch until we upgrade to Hibernate v8.0.0+, which includes the fix natively.

Also remove the `ALTER ROLE ALL SET statement_timeout = '10m'` workaround from `alterZoneConfigAndClusterSettings`. The hibernate test runs as the root user, and `ALTER ROLE ALL` does not apply to the root user, so this setting had no effect.

Fixes: #165544

Release note: None
Epic: None

### CODE REVIEW

File: pkg/cmd/roachtest/tests/orm_helpers.go [hunk 1]
```diff
@@ -74,7 +74,6 @@ func alterZoneConfigAndClusterSettings(
 		`SET CLUSTER SETTING sql.defaults.experimental_temporary_tables.enabled = 'true';`,
 		`ALTER ROLE ALL SET multiple_active_portals_enabled = 'true';`,
 		`ALTER ROLE ALL SET serial_normalization = 'sql_sequence_cached'`,
-		`ALTER ROLE ALL SET statement_timeout = '10m'`,
```
Comment (rafiss) [inline pkg/cmd/roachtest/tests/orm_helpers.go:77]: i don't think we should remove this. this is a shared helper function, and most of the other ORM tests do not run as `root`, so still benefit from this setting.

also, does the hibernate test suite have a way of configuring which user to run as? if so, we should try that.

Comment (spilchen) [reply pkg/cmd/roachtest/tests/orm_helpers.go:77]: I only removed it because it was recently added as an earlier attempt to fix this issue (see #161781), which didn't seem to work. Given that it was recent I figured other tests weren't depending on it's behaviour. I can definitely add it back if you think it's still a good thing to have in general. Let me know.

We can change the user that is used for the run, but it's baked into the hibernate-orm repo:
https://github.com/hibernate/hibernate-orm/blob/de0c65198722794902294fe39fd572899a7e3318/gradle/databases.gradle#L345-L356

Not sure if it's worth it.

**Review by spilchen — COMMENTED** [review]
> @spilchen made 1 comment.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/165567)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on fqazi and rafiss).

File: pkg/cmd/roachtest/tests/orm_helpers.go (hunk 1 above)
Comment (rafiss) [reply pkg/cmd/roachtest/tests/orm_helpers.go:77]: i agree, changing the user doesn't seem worth it.

let's keep this ALTER ROLE command though. it seems useful for other tests.

**Review by rafiss — APPROVED** [review]
