### PR TITLE
backupccl: remove unused PhysicalPlanChangeChecker

### LINKED ISSUE #115844: backupccl: restore fails with `attempt to mutate frontier while iterating`
In a large restore we saw it fail with `attempt to mutate frontier while iterating`. This error is from the new frontier implementation indicating we have a frontier that we are concurrently iterating over and mutating. The error seems to be from inside this method where we forward the checkpoint frontier https://github.com/cockroachdb/cockroach/blob/52b44db51f467f9308fa668eab47e780299d871a/pkg/ccl/backupccl/restore_job.go#L400. This implies that there is some other goroutine iterating over the frontier at the same time.

One place where we iterate over the frontier is https://github.com/cockroachdb/cockroach/blob/c7264978e40967bb73d24667c2574c23a83ea47c/pkg/ccl/backupccl/restore_progress.go#L192, but this is done while holding the same mutex as the goroutine that is mutating the frontier, so it should not be able to execute concurrently.

Another suspicion is around https://github.com/cockroachdb/cockroach/blob/04d27d931eb6aa92449fe5dd22950151fb01010e/pkg/ccl/backupccl/restore_span_covering.go#L150 where we pass in the frontier reference and capture it in the `filter` struct. This reference is then used without a mutex in a few callsites. While this seems dangerous I haven't been able to reason about any of those callsites being called concurrently with when we receive a progress update yet.

Jira issue: CRDB-34250

### PR DESCRIPTION
**Pull request by adityamaru**
Please see individual commits.

Fixes: #115844

### CODE REVIEW

File: pkg/ccl/backupccl/restore_processor_planning.go [hunk 1]
```diff
@@ -279,18 +279,8 @@ func distRestore(
 		return errors.Wrap(err, "making distSQL plan")
 	}
 
-	replanner, stopReplanner := sql.PhysicalPlanChangeChecker(ctx,
```
Comment (miretskiy) [inline pkg/ccl/backupccl/restore_processor_planning.go:282]: do we want to remove PhysicalPlanCHangeChecker since there are no callers remaining?  Or, we'll revisit it at some point?

**Review by miretskiy — APPROVED** [review]

**Review by msbutler — APPROVED** [review]
Thanks for doing this!
