### PR TITLE
changefeedccl: support for multiple seed brokers in kafka v2 sink

### LINKED ISSUE #136616: changefeedccl: unable to specify multiple kafka brokers for the v2 sink
The v2 sink fails if you specify multiple kafka brokers in your create changefeed statement, and the feed is not created: 

```
> CREATE CHANGEFEED FOR TABLE t2 INTO 'kafka://localhost:9092,localhost:9092'
ERROR: unable to dial: dial tcp: lookup localhost:9092,localhost:9092: no such host
```

This works with the v1 sink.

Jira issue: CRDB-45165

### PR DESCRIPTION
**Pull request by asg0451**
Previously the kafka v2 sink did not support multiple seed brokers, where the v1 sink did. This PR adds this support.

Fixes: #136616

Release note (general change): add support for multiple seed brokers in the new kafka sink.

### CODE REVIEW

File: pkg/ccl/changefeedccl/sink_kafka_v2.go [hunk 1]
```diff
@@ -68,18 +68,19 @@ func newKafkaSinkClientV2(
 	ctx context.Context,
 	clientOpts []kgo.Opt,
 	batchCfg sinkBatchConfig,
-	bootstrapAddrs string,
+	bootstrapAddrsStr string,
```
Comment (andyyang890) [inline pkg/ccl/changefeedccl/sink_kafka_v2.go:71]: nit: I prefer the old name, I think it's unnecessary to encode the var type in the name here

**Review by andyyang890 — APPROVED** [review]

File: pkg/ccl/changefeedccl/sink_kafka_v2.go (hunk 1 above)
Comment (asg0451) [reply pkg/ccl/changefeedccl/sink_kafka_v2.go:71]: i agree generally that you dont need to encode types in names, but this is how i've always named things that are strings that are about to be parsed. eg 

```
// given line := "hello=42"
parts := strings.Split(line, "=")
key, valStr := parts[0], parts[1]
val, err := strconv.Atoi(numStr)
```

this is probably just a *me* convention...... i'm open to alternatives though.

Comment (andyyang890) [reply pkg/ccl/changefeedccl/sink_kafka_v2.go:71]: hmm yeah that's fair, although to me the fact that the name is plural (i.e. `...Addrs`) already suggests that it's probably a comma-separated list. maybe you could make the parameter type a `[]string` and do the splitting one level up 😛

**Comment by asg0451** [comment]
bors r=andyyang890
