### PR TITLE
import: fix incomplete successful imports during node failure

### LINKED ISSUE #108547: import: import worker failure can succeed with missing data
Forked from: https://github.com/cockroachdb/cockroach/issues/102839

```test logs left over in: /tmp/_tmp/060246e25d27a0efc6dd14ec672a0f2b/logTestImportWorkerFailure3155831314
--- FAIL: TestImportWorkerFailure (17.54s)
    test_log_scope.go:161: test logs captured to: /tmp/_tmp/060246e25d27a0efc6dd14ec672a0f2b/logTestImportWorkerFailure3155831314
    test_log_scope.go:79: use -show-logs to present logs inline
    import_stmt_test.go:5435: query 'SELECT * FROM t ORDER BY i': expected:
        0
        1
        2
        3
        4
        5
        6
        7
        8
        9
        10
        11
        12
        13
        14
        15
        16
        17
        18
        19
        
        got:
        1
        2
        4
        5
        7
        8
        10
        11
        13
        14
        16
        17
        19
        
    panic.go:522: -- test log scope end --
FAIL
I230509 15:29:22.694464 1 (gostd) testmain.go:254  [-] 1  Test //pkg/sql/importer:importer_test exited with error code 1
```

Jira issue: CRDB-30515

### PR DESCRIPTION
**Pull request by cucaroach**
If a context cancellation occurs during import that aborts the
import-files-to-kv goroutine the ingestKvs goroutine could short circuit
and randomly not fail (ie not return an error) if the select chose the
progress arm over the done checking arm of its select.  This would
record the progress so that on subsequent import retries we'd think we
were done with those rows but we'd never actually have ingested them.
Fix this by only recording the progress if both goroutines sucessfully
complete without error.

Fixes: #108547
Epic: None

Release note (bug fix): Fixed a bug that could cause some rows to be
silently skipped during IMPORT when a node failed.

### CODE REVIEW

**Review by michae2 — APPROVED** [review]
:lgtm_strong: Nice work tracking this down!!!

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/109513#-:-NchbHgh4SpQ1r2oMv4u:b-6jyou1)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @dt)

**Comment by cucaroach** [comment]
I've had a half dozen stress runs be successful or fail for other reasons.  The main one is a timeout due to tenant startup hangs that are tracked by https://github.com/cockroachdb/cockroach/issues/108209.  I'll circle back with another PR to remove the stress/race/deadlock skips when that issue is resolved.

**Comment by michae2** [comment]
I think we should also backport this to v23.1.9 and v22.2.

**Review by michae2 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/109513)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @cucaroach and @dt)

___
*[`-- commits` line 17 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/109513#-NchhjSO9CisIsiWBeLm):*
Would be nice to also mention that the bug has existed since v20.2.

File: pkg/sql/importer/read_import_base.go [hunk 1]
```diff
@@ -112,28 +112,21 @@ func runImport(
...
 	}
 
+	var prog execinfrapb.RemoteProducerMetadata_BulkProcessorProgress
+	prog.ResumePos = make(map[int32]int64)
+	prog.CompletedFraction = make(map[int32]float32)
+	for i := range spec.Uri {
+		prog.CompletedFraction[i] = 1.0
+		prog.ResumePos[i] = math.MaxInt64
+	}
+
```
Comment (dt) [inline pkg/sql/importer/read_import_base.go:129]: Do you want to send `prog` to `progCh` ?

Comment (cucaroach) [reply pkg/sql/importer/read_import_base.go:129]: Oof, yes.

Comment (cucaroach) [reply pkg/sql/importer/read_import_base.go:130]: CI caught it which is nice!

File: pkg/sql/importer/read_import_base.go [hunk 2]
```diff
@@ -112,28 +112,22 @@ func runImport(
...
 	}
 
+	var prog execinfrapb.RemoteProducerMetadata_BulkProcessorProgress
+	prog.ResumePos = make(map[int32]int64)
+	prog.CompletedFraction = make(map[int32]float32)
+	for i := range spec.Uri {
+		prog.CompletedFraction[i] = 1.0
+		prog.ResumePos[i] = math.MaxInt64
+	}
+	progCh <- prog
```
Comment (dt) [inline pkg/sql/importer/read_import_base.go:129]: I think you want this in the select as it was before

Comment (cucaroach) [reply pkg/sql/importer/read_import_base.go:129]: That isn't a concern I know anything about so you'll have to educate me.   Are you saying the progCh consumer goroutine could stop reading when a context is canceled so our send would hang or panic?  Currently it doesn't look like that's possible (the goroutine reading from that channel doesn't check for cancelation) but I guess you mean that select'ing over the context in addition to writing the channel is good hygiene so we should do it anyways?

Comment (dt) [reply pkg/sql/importer/read_import_base.go:129]: yeah, I generally treat any send or recv on a ch that doesn't also select on ctx done as suspect until proven otherwise, but if you're verified this one is known to be okay since the consumer cannot exit before the sender under any circumstance then carry on.

My personal pref is to just always do the select since sometimes someone adds a `return err` or something to the other side than then it can exit or something, but as long as you're convinced it is safe as-is, I'm happy.

**Review by dt — APPROVED** [review]

**Review by dt — APPROVED** [review]

**Comment by cucaroach** [comment]
bors r+
TFTRs!
