### PR TITLE
sql: allow string concat with any non-array type

### LINKED ISSUE #34404: sql: string concatenation operator stricter than with postgres
**Describe the problem**

When running Grafana's migrations (with the postgres database type against CRDB) a string concatenation which works on postgres fails on CRDB. The part that breaks is concatenating `''` and an integer column.

**To Reproduce**

What I did:

    docker run --rm -d --name roach cockroachdb/cockroach:v2.1.4 start --insecure
    docker run --link roach --rm -ti -e "GF_DATABASE_URL=postgres://root@roach:26257/defaultdb?sslmode=disable" --name grafana grafana/grafana

With the second command repeated a few times, while 'fixing' the `DROP INDEX` migrations by manually dropping the index with `CASCADE` and recreating a similarly named index without any constraints.

A simpler case: run any CRDB and issue a query like: 

    select 'Value: ' || 42;

The result of that query is the following:

    root@172.17.0.2:26257/defaultdb> select 'Value: ' || 42 as v;
    pq: unsupported binary operator: <string> || <int>

**Expected behavior**

    root@172.17.0.2:26257/defaultdb> select 'Value: ' || 42 as v;
          v      
    +-----------+
      Value: 42  
    (1 row)
    
    Time: 483.697µs

**Environment:**
 - CockroachDB version 2.1.4
 - Server OS: Linux (in Docker)
 - Client app: `cockroach sql` or grafana migrator

**Additional context**
This is one of the incompatibilities holding back use of Grafana on CRDB. (the two others are `DROP INDEX` needing `CASCADE` for `UNIQUE` constraints, and `ALTER COLUMN` lowering a string field's size)

### LINKED ISSUE #41872: sql: unsupported binary operator: <string> || <oid>
The type checker should allow an OID to be concatenated to a string.

### PR DESCRIPTION
**Pull request by rafiss**
Many tools and ORMs that work with Postgres expect this behavior.

this is retrying the idea from #43190
fixes #41872
fixes #34404

Release note (sql change): the concatenation operator || is now usable
between strings and any other non-array type.

Release note (backward-incompatible change): Concatenation between a
non-null argument and a null argument is now typed as string
concatenation. (It previously used to be typed as array concatentation.)
This means that the result of `NULL || 1` will now be `NULL`.
Previously, the result would be `{1}`. To preserve the old behavior, the NULL
argument can be casted to an explicit type.

### CODE REVIEW

**Review by RaduBerinde — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/55611)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rafiss)

___
*[pkg/sql/sem/tree/eval.go, line 479 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/55611#-MJnrJHp5qA5Z_5B8FLM:-MJnrJHp5qA5Z_5B8FLN:b-dbj710) ([raw file](https://github.com/cockroachdb/cockroach/blob/018b753a01d0c024fbae5ce9061e06cce79ac4d4/pkg/sql/sem/tree/eval.go#L479)):*
> ```Go
> 				return nil, errors.New("neither LHS or RHS matched DString")
> 			},
> 			Volatility: VolatilityImmutable,
> ```

This is not correct. E.g. TIMESTAMPTZ to string is not an immutable cast. Look at the cast volatilities in tree/casts.go (validCasts). Perhaps looking up the volatility of the cast from the given type to string is the right way to initialize this.

**Comment by yuzefovich** [comment]
Before this PR, we fully supported concat binary operator in the vectorized engine, so it'd be good to either confirm that it is still the case or open up an issue to add the support (if the latter is the case, the new issue should be referenced in #49463).

**Comment by rafiss** [comment]
@yuzefovich I created #55841 (the new overloads do not work with colexec)

**Review by rafiss — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/55611)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @otan and @RaduBerinde)

___
*[pkg/sql/sem/tree/eval.go, line 479 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/55611#-MJnrJHp5qA5Z_5B8FLM:-MKGceoW6JucuZw8aE0p:b-n0h3dl) ([raw file](https://github.com/cockroachdb/cockroach/blob/018b753a01d0c024fbae5ce9061e06cce79ac4d4/pkg/sql/sem/tree/eval.go#L479)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

This is not correct. E.g. TIMESTAMPTZ to string is not an immutable cast. Look at the cast volatilities in tree/casts.go (validCasts). Perhaps looking up the volatility of the cast from the given type to string is the right way to initialize this.
</blockquote></details>

thanks for this tip. updated

**Comment by otan** [comment]
sooooo how hard is it to get this to work with `anynonarray`, to be more postgres-esque?

**Comment by rafiss** [comment]
I had a local branch with the `anynonarray` approach. but i didn't have an idea for dealing with the thing you got stuck with: https://github.com/cockroachdb/cockroach/pull/43143#issuecomment-565585435. but i do think i can dive into that problem more.

**Comment by rafiss** [comment]
hmm although to Radu's point above, we can't treat all the `anynonarray` overloads the same, since they have different volatility. unless we are allowed to be pessimistic and make them all `VolatilityStable`

**Comment by rafiss** [comment]
so i did get past the issue of https://github.com/cockroachdb/cockroach/pull/43143#issuecomment-565585435 just by adding explicit string-byte and byte-string concat overloads.

but after that, these cases failed:

```
    --- FAIL: TestEval/opt (0.07s)
        --- FAIL: TestEval/opt/concat (0.00s)
            eval_test.go:49:
                testdata/eval/concat:80: 1 || NULL
                expected:
                NULL

                found:
                ARRAY[1]
    --- FAIL: TestEval/no-opt (0.05s)
        --- FAIL: TestEval/no-opt/concat (0.00s)
            eval_test.go:49:
                testdata/eval/concat:80: 1 || NULL
                expected:
                NULL

                found:
                ARRAY[1]
```

with the `anynonarray` approach i haven't been able to think of a way to make the type checker pick string concat over array concat in the presence of nulls.

**Comment by otan** [comment]
> unless we are allowed to be pessimistic and make them all VolatilityStable

this is what PostgreSQL does

File: pkg/sql/sem/tree/eval.go [hunk 1]
```diff
@@ -417,9 +417,48 @@ func initArrayToArrayConcatenation() {
 	}
 }
 
+// initNonArrayToNonArrayConcatenation initializes string + nonarrayelement
+// and nonarrayelement + string concatenation.
+func initNonArrayToNonArrayConcatenation() {
```
Comment (otan) [inline pkg/sql/sem/tree/eval.go:422]: can you add a test that checks `<anyNonArrayElem> || NULL = anyNonArrayElem.String()` for each non array elem type?

**Review by otan — APPROVED** [review]
lgtm if you can't get anynonarray to work.

File: pkg/sql/sem/tree/eval.go (hunk 1 above)
Comment (rafiss) [reply pkg/sql/sem/tree/eval.go:422]: i may not be following, but in the operation you posted, the result should be NULL.

i added a test to `pkg/sql/sem/tree/testdata/eval/concat`. See https://github.com/rafiss/cockroach/blob/3705e3c7f37effaa644d45344b5c89a461877401/pkg/sql/sem/tree/testdata/eval/concat#L73 

i can add more tests for the other non array types.

Comment (otan) [reply pkg/sql/sem/tree/eval.go:422]: ah woops, i meant anyNonArrayElem || string, as a loop over all current types to make sure it doesn't get resolved unexpectedly.

Comment (rafiss) [reply pkg/sql/sem/tree/eval.go:423]: it didn't seem very nice to loop over types and generate values for each type, so instead i just added more cases to `concat` eval test. it turned up an issue so i updated eval.go to use the FmtBareStrings flag

Comment (otan) [reply pkg/sql/sem/tree/eval.go:423]: > it didn't seem very nice to loop over types and generate values for each type

(i'm not opposed to this landing this as is, but curious)
does `RandDatum` not give you something nice?

Comment (rafiss) [reply pkg/sql/sem/tree/eval.go:423]: i didn't know about `RandDatum` hehehe. thank you for the pointer!

will use that, and anyway looks like i need to fix tuple-string concat:

```
 encountered internal error:
no volatility for cast tuple{int, int}::tuple
(1) assertion failure
Wraps: (2) attached stack trace
  -- stack trace:
  | github.com/cockroachdb/cockroach/pkg/sql/opt/memo.BuildSharedProps
  | 	/go/src/github.com/cockroachdb/cockroach/pkg/sql/opt/memo/logical_props_builder.go:1512
```

**Comment by rafiss** [comment]
I've had to update `tree.ReType` to get things working, so PTAL. I don't think that needs to handle recursive tuples, but let me know if it should.

File: pkg/sql/sem/tree/normalize.go [hunk 2]
```diff
@@ -978,10 +978,19 @@ func init() {
...
 // to the requested type, inserting a cast if necessary.
 func ReType(expr TypedExpr, wantedType *types.T) TypedExpr {
-	if wantedType.Family() == types.AnyFamily || expr.ResolvedType().Identical(wantedType) {
+	resolvedType := expr.ResolvedType()
+	if wantedType.Family() == types.AnyFamily || resolvedType.Identical(wantedType) {
+		return expr
+	}
+	// Casting to an "any" tuple is not allowed because there is no way to define
+	// the volatility in LookupCastVolatility.
+	if wantedType.Family() == types.TupleFamily &&
```
Comment (otan) [inline pkg/sql/sem/tree/normalize.go:990]: can we not always use stable as a volatility? i think that's what Postgres does. in these circumstances.

Comment (rafiss) [reply pkg/sql/sem/tree/normalize.go:990]: that sounds cool! will try.

**Review by otan — APPROVED** [review]

**Comment by rafiss** [comment]
thanks for reviewing :)

bors r=otan
