### PR TITLE
roachtest: disable rate limiters in mixedversion

### LINKED ISSUE #131695: roachtest: tpcc/mixed-headroom/n5cpu16 failed
roachtest.tpcc/mixed-headroom/n5cpu16 [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/17110885?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/17110885?buildTab=artifacts#/tpcc/mixed-headroom/n5cpu16) on master @ [74333311616b937fea6a995462215a1cb5962686](https://github.com/cockroachdb/cockroach/commits/74333311616b937fea6a995462215a1cb5962686):

```
(test_runner.go:1313).runTest: test timed out (7h0m0s)
test artifacts and logs in: /artifacts/tpcc/mixed-headroom/n5cpu16/run_1
```

Parameters:
 - <code>ROACHTEST_arch=amd64</code>
 - <code>ROACHTEST_cloud=gce</code>
 - <code>ROACHTEST_coverageBuild=false</code>
 - <code>ROACHTEST_cpu=16</code>
 - <code>ROACHTEST_encrypted=false</code>
 - <code>ROACHTEST_fs=ext4</code>
 - <code>ROACHTEST_localSSD=true</code>
 - <code>ROACHTEST_runtimeAssertionsBuild=false</code>
 - <code>ROACHTEST_ssd=0</code>
<details><summary>Help</summary>
<p>

See: [roachtest README](https://github.com/cockroachdb/cockroach/blob/master/pkg/cmd/roachtest/README.md)

See: [How To Investigate \(internal\)](https://cockroachlabs.atlassian.net/l/c/SSSBr8c7)

See: [Grafana](https://go.crdb.dev/roachtest-grafana/teamcity-17110885/tpcc-mixed-headroom-n5cpu16/1727786809031/1727812225739)

</p>
</details>
/cc @cockroachdb/test-eng
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*tpcc/mixed-headroom/n5cpu16.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/bazci/githubpost/issues)
</sub>

Jira issue: CRDB-42654

### PR DESCRIPTION
**Pull request by DarrylWong**
This change adds a step for separate process deployments to disable both the KV and tenant rate limiter. The KV rate limiter is disabled by granting the tenant capability: `exempt_from_rate_limiting`. The tenant rate limiter cannot be disabled outright, so instead the tenant is given arbitrarily high limits.

Release note: none
Epic: none
Fixes: #131695

### CODE REVIEW

**Comment by DarrylWong** [comment]
TC run of [tpcc/mixed-headroom](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/18072721?hideProblemsFromDependencies=false&hideTestsFromDependencies=false)

Some of the currently disabled separate process tests should work after this change, but I'd rather take the time to test all of them out before enabling and causing a lot of noise.

File: pkg/cmd/roachtest/roachtestutil/mixedversion/steps.go [hunk 1]
```diff
@@ -547,6 +547,73 @@ func (s deleteAllTenantsVersionOverrideStep) Run(
...
+// exemption from the tenant rate limiter. For older versions, the mvt framework already
+// handles granting said capabilities (see: TenantsAndSystemAlignedSettingsVersion).
+type disableRateLimitersStep struct {
+	virtualClusterName string
+}
+
+func (s disableRateLimitersStep) Background() shouldStop { return nil }
+
+func (s disableRateLimitersStep) Description() string {
+	return fmt.Sprintf("disable KV and tenant rate limiter for virtual cluster %s", s.virtualClusterName)
```
Comment (srosenberg) [inline pkg/cmd/roachtest/roachtestutil/mixedversion/steps.go:567]: Nit: "...and tenant(SQL)..."

File: pkg/cmd/roachtest/roachtestutil/mixedversion/steps.go [hunk 2]
```diff
@@ -547,6 +547,73 @@ func (s deleteAllTenantsVersionOverrideStep) Run(
...
+
+	var tenantID int64
+	if rows.Next() {
+		if err = rows.Scan(&tenantID); err != nil {
+			return err
+		}
+	}
+
+	const (
+		// `+Inf` is used instead of `math.MaxFloat64` to avoid the long
```
Comment (srosenberg) [inline pkg/cmd/roachtest/roachtestutil/mixedversion/steps.go:602]: The long output is due to the missing explicit CAST?

File: pkg/cmd/roachtest/roachtestutil/mixedversion/steps.go [hunk 3]
```diff
@@ -547,6 +547,73 @@ func (s deleteAllTenantsVersionOverrideStep) Run(
...
+	stmt := fmt.Sprintf(
+		"ALTER TENANT %q GRANT CAPABILITY exempt_from_rate_limiting = true",
+		s.virtualClusterName,
+	)
+	if err := h.System.Exec(rng, stmt); err != nil {
+		return err
+	}
+
+	// Disable the tenant rate limiter. Unlike the KV rate limiter, there is no way
+	// to outright disable the tenant rate limiter. Instead, we instead set the tenant's
```
Comment (srosenberg) [inline pkg/cmd/roachtest/roachtestutil/mixedversion/steps.go:583]: Nit: this comment is really about `crdb_internal.update_tenant_resource_limits`

File: pkg/cmd/roachtest/roachtestutil/mixedversion/steps.go [hunk 4]
```diff
@@ -547,6 +547,73 @@ func (s deleteAllTenantsVersionOverrideStep) Run(
...
+	// resource limits to an arbitrarily high value.
+	stmt = fmt.Sprintf(
+		"SELECT id FROM system.tenants WHERE name = '%s'", s.virtualClusterName,
```
Comment (srosenberg) [inline pkg/cmd/roachtest/roachtestutil/mixedversion/steps.go:586]: It seems like this should instead be a (common) helper? Maybe we already do this elsewhere, i.e., mapping tenant name to its id?

**Review by srosenberg — APPROVED** [review]
LGTM! 

P.S. I'm planning to do a couple of runs over the weekend to enlist the off-cpu profiling capabilities of Side-Eye.

File: pkg/cmd/roachtest/roachtestutil/mixedversion/steps.go [hunk 5]
```diff
@@ -547,6 +547,73 @@ func (s deleteAllTenantsVersionOverrideStep) Run(
...
+	const (
+		// `+Inf` is used instead of `math.MaxFloat64` to avoid the long
+		// output when the SQL statement is logged by the framework.
+		availableTokens = "CAST('+Inf' AS FLOAT)"
+		refillRate      = "CAST('+Inf' AS FLOAT)"
+		maxBurstTokens  = 0 // 0 disables the limit.
+	)
+
+	stmt = fmt.Sprintf(
+		"SELECT crdb_internal.update_tenant_resource_limits(%d, %s, %s, %d, now(), 0); ",
```
Comment (herkolategan) [inline pkg/cmd/roachtest/roachtestutil/mixedversion/steps.go:610]: Nit: extra space after ';'

File: pkg/cmd/roachtest/roachtestutil/mixedversion/steps.go [hunk 6]
```diff
@@ -547,6 +547,73 @@ func (s deleteAllTenantsVersionOverrideStep) Run(
...
+		tenantID, availableTokens, refillRate, maxBurstTokens,
```
Comment (herkolategan) [inline pkg/cmd/roachtest/roachtestutil/mixedversion/steps.go:611]: Would be nice to use this at some point: https://github.com/cockroachdb/cockroach/blob/master/pkg/cmd/roachtest/tests/admission_control_multitenant_fairness.go#L184
But I see the change is relatively new: #98160 (won't work for all versions)

We could add a version check here to skip the extra tenant ID logic in cases where the version is new enough.
However, this will probably only complicate this logic. Maybe if it's moved to helper like Stan mentioned above it could be worthwhile, but I don't feel strongly about it, more an observation than anything else.

**Review by herkolategan — APPROVED** [review]
Excellent! I mentioned the tenant ID no longer being needed in newer versions, where you can just use the virtual cluster name. Don't necessarily need to add a conditional branch for that, but could be helpful to add a comment to mention it's possible but that it's using the tenant ID for wider version compatibility.

File: pkg/cmd/roachtest/roachtestutil/mixedversion/steps.go (hunk 6 above)
Comment (DarrylWong) [reply pkg/cmd/roachtest/roachtestutil/mixedversion/steps.go:611]: Ah, thanks for providing that PR! It looks like that change is in v23.1 and up. As long as we don't backport separate process deployments to 23.2 or older, we can unconditionally use tenant names since `OldestSupportedVersion` is `23.1` starting at `24.1`.

I think that should be an okay assumption to make so I'll get rid of the logic completely.

File: pkg/cmd/roachtest/roachtestutil/mixedversion/steps.go (hunk 2 above)
Comment (DarrylWong) [reply pkg/cmd/roachtest/roachtestutil/mixedversion/steps.go:602]: Ah nevermind, the issue was because I was casting `math.MaxFloat64` as a float through `%f`. It's a reasonable length if I just use `%v` so I switched it back.

File: pkg/cmd/roachtest/roachtestutil/mixedversion/steps.go (hunk 4 above)
Comment (DarrylWong) [reply pkg/cmd/roachtest/roachtestutil/mixedversion/steps.go:586]: Given what Herko said below about being able to use cluster name on newer versions, I removed the logic completely since I don't think we will backport separate process deployments to v23.2 or older anytime soon. But let me know if you have other opinions.

**Comment by srosenberg** [comment]
I did a few full runs using `COCKROACH_RANDOM_SEED=7952454220800612121` with and without "disabling" tenant rate limiter. Strangely, I'm still seeing some `limiter.Wait` calls which end up taking the slow path, suggesting some sort of rate limiting still happening, albeit at a very low rate; 6 calls [1] (during 5 minutes) compared to 1194 [2] without "disabling".

```
github.com/cockroachdb/cockroach/pkg/util/quotapool.(*AbstractPool).tryAcquireOnNotify
github.com/cockroachdb/cockroach/pkg/util/quotapool.(*AbstractPool).Acquire.func4
github.com/cockroachdb/cockroach/pkg/util/quotapool.(*AbstractPool).Acquire
github.com/cockroachdb/cockroach/pkg/ccl/multitenantccl/tenantcostclient.(*limiter).Wait
github.com/cockroachdb/cockroach/pkg/ccl/multitenantccl/tenantcostclient.(*tenantSideCostController).OnResponseWait
github.com/cockroachdb/cockroach/pkg/kv/kvclient/kvcoord.(*DistSender).sendToReplicas
github.com/cockroachdb/cockroach/pkg/kv/kvclient/kvcoord.(*DistSender).sendPartialBatch
github.com/cockroachdb/cockroach/pkg/kv/kvclient/kvcoord.(*DistSender).divideAndSendBatchToRanges
```

[1] https://app.side-eye.io/#/logs/91
[2] https://app.side-eye.io/#/logs/92

**Comment by srosenberg** [comment]
I think this is good to merge. I didn't see any timeouts. The explanation for seeing the slow path (`tryAcquireOnNotify`) could be the delay between when the rate limiter is created (and its associated `quotapool`) and `ReconfigureTokenBucket` arrives. When the initial requests are dequeued from the quotapool, all subsequent should hit the fast path, namely `limiter.Wait` -> `qp.acquireFastPath` -> `qp.tb.TryToFulfill` (in token_bucket).

**Comment by DarrylWong** [comment]
>The explanation for seeing the slow path (tryAcquireOnNotify) could be the delay between when the rate limiter is created

Yeah that was my thought too, it seems like most instances of the slow path are seen right at the start of the workload. I do see an instance here or there pop up every 5-10 minutes after that though 🫤 

It seems like `(c *tenantSideCostController) sendTokenBucketRequest` only requests from `tenantcostserver` the tokens it expects to need:

https://github.com/cockroachdb/cockroach/blob/da235018445c50eb668739ae8a1e74d0d3ecff99/pkg/ccl/multitenantccl/tenantcostclient/tenant_side.go#L564-L566

Is it possible that if we see a spike in average RU usage (like when we spin up two intensive workloads), the cost estimation needs a cycle or two to catch up? And in the meanwhile it doesn't request enough tokens from the cost server (even though the cost server knows the tenant has unlimited quota).

Still trying to reason through the code so not fully sure, but in this case I think it would just be unfortunate overhead of separate process mode and we can still merge as is.

**Comment by srosenberg** [comment]
> I do see an instance here or there pop up every 5-10 minutes after that though 🫤

I suspect what's happening is you're seeing the same delay between (tenant) restarts. Upon startup, a hardcoded default (`bufferTokens`) is used [1]. The actual persisted state is in `system.tenant_usage` which isn't consulted on startup. Instead, `sendTokenBucketRequest` must be initiated in order to synchronize the state (via `readTenantAndInstanceState`).
There are several conditions for triggering `sendTokenBucketRequest`, e.g., [2].

[1] https://github.com/cockroachdb/cockroach/blob/4c1602ee6ab32a262d081df5f3f20aa2f5d2dc28/pkg/ccl/multitenantccl/tenantcostclient/tenant_side.go#L155-L158
[2] https://github.com/cockroachdb/cockroach/blob/4c1602ee6ab32a262d081df5f3f20aa2f5d2dc28/pkg/ccl/multitenantccl/tenantcostclient/tenant_side.go#L518-L520

**Comment by DarrylWong** [comment]
>I suspect what's happening is you're seeing the same delay between (tenant) restarts

Ah yeah, I think that may be it. It seems like a low enough rate that it shouldn't be an issue but I'll keep monitoring.

TFTRs!

bors r=srosenberg, herkolategan

**Comment by DarrylWong** [comment]
bors r=srosenberg, herkolategan
