### PR TITLE
changefeedccl: add missing error return during change frontier startup

### LINKED ISSUE #152104: changefeedccl: change frontier ignores span-level checkpoint restore errors
When a changefeed's span-level checkpoint is restored to the change frontier, it silently ignores any errors (other than verbose logging):
https://github.com/cockroachdb/cockroach/blob/96631ad731561f563f02f7fb791b75458aa421ba/pkg/ccl/changefeedccl/changefeed_processors.go#L1445-L1449

Contrast this with how the change aggregator moves to draining when it encounters an error:

* _Restoring happens in `setupSpansAndFrontier` and returns an error when it fails_
https://github.com/cockroachdb/cockroach/blob/96631ad731561f563f02f7fb791b75458aa421ba/pkg/ccl/changefeedccl/changefeed_processors.go#L634-L636

* _The change aggregator then moves to draining upon seeing the error_
https://github.com/cockroachdb/cockroach/blob/96631ad731561f563f02f7fb791b75458aa421ba/pkg/ccl/changefeedccl/changefeed_processors.go#L343-L351

The change frontier code should be modified so that it also moves to draining.

Jira issue: CRDB-53649

### PR DESCRIPTION
**Pull request by andyyang890**
Before this change, when the change frontier encountered an error while
restoring a changefeed's span-level checkpoint, it would ignore the
error instead of moving to draining like change aggregators would.

Fixes #152104

Release note: None

### CODE REVIEW

File: pkg/ccl/changefeedccl/changefeed_processors.go [hunk 1]
```diff
@@ -1479,8 +1479,11 @@ func (cf *changeFrontier) Start(ctx context.Context) {
 
 	if err := checkpoint.Restore(cf.frontier, cf.spec.SpanLevelCheckpoint); err != nil {
 		if log.V(2) {
-			log.Dev.Infof(cf.Ctx(), "change frontier encountered error on checkpoint restore: %v", err)
+			log.Dev.Infof(cf.Ctx(),
+				"change frontier moving to draining due to error restoring span-level checkpoint: %v", err)
```
Comment (rharding6373) [inline pkg/ccl/changefeedccl/changefeed_processors.go]: This seems like it should happen infrequently, should we consider always logging instead of only in verbose logging?

Comment (rharding6373) [inline pkg/ccl/changefeedccl/changefeed_processors.go]: Is there any other info to log that might make it easier to debug in the future? E.g., which checkpoint is potentially problematic (may only be relevant for per-table checkpoints).

File: pkg/ccl/changefeedccl/changefeed_processors.go [hunk 2]
```diff
@@ -1479,8 +1479,11 @@ func (cf *changeFrontier) Start(ctx context.Context) {
...
 		}
+		cf.MoveToDraining(err)
```
Comment (rharding6373) [inline pkg/ccl/changefeedccl/changefeed_processors.go:1455]: In the issue, you point out that L635 (L664 in this file) only returns an error when restore returns an error. Should that also move to draining?

**Review by rharding6373 — COMMENTED** [review]
Nice!

File: pkg/ccl/changefeedccl/changefeed_processors.go [hunk 3]
```diff
@@ -1479,8 +1479,11 @@ func (cf *changeFrontier) Start(ctx context.Context) {
 
 	if err := checkpoint.Restore(cf.frontier, cf.spec.SpanLevelCheckpoint); err != nil {
 		if log.V(2) {
-			log.Dev.Infof(cf.Ctx(), "change frontier encountered error on checkpoint restore: %v", err)
+			log.Dev.Infof(cf.Ctx(),
```
Comment (aerfrei) [inline pkg/ccl/changefeedccl/changefeed_processors.go]: Should this logging level be Error instead of Info?

File: pkg/ccl/changefeedccl/changefeed_processors.go (hunk 2 above)
Comment (andyyang890) [reply pkg/ccl/changefeedccl/changefeed_processors.go:1455]: It gets moved to draining higher up in the call stack (just edited the issue to make that more clear) https://github.com/cockroachdb/cockroach/blob/96631ad731561f563f02f7fb791b75458aa421ba/pkg/ccl/changefeedccl/changefeed_processors.go#L343-L351

File: pkg/ccl/changefeedccl/changefeed_processors.go (hunk 1 above)
Comment (andyyang890) [reply pkg/ccl/changefeedccl/changefeed_processors.go]: I was actually going back and forth on this, I'll change it to be non-verbose

Comment (rharding6373) [reply pkg/ccl/changefeedccl/changefeed_processors.go]: Consider making the change in the other err+log+drain locations, too (if you haven't already)

File: pkg/ccl/changefeedccl/changefeed_processors.go (hunk 3 above)
Comment (andyyang890) [reply pkg/ccl/changefeedccl/changefeed_processors.go]: Hmm that's a good question, I'm not sure if it rises to the level of `Error` per the comment since it's potentially recoverable without user intervention:
https://github.com/cockroachdb/cockroach/blob/61b17be22cf934983374462f87364632d758624c/pkg/util/log/log_channels_generated.go#L599-L602

~I also wanted it to be consistent with the other "move to draining" logs. We could maybe consider upgrading them to `Warning`.~

Edit: I upgraded all the "move to draining" logs to `Warning`.

File: pkg/ccl/changefeedccl/changefeed_processors.go (hunk 1 above)
Comment (andyyang890) [reply pkg/ccl/changefeedccl/changefeed_processors.go]: I modified `checkpoint.Restore` so that it wraps the error with the specific (span, timestamp) pair that failed to be forwarded. We could potentially log the entire checkpoint but I'm leaning towards not doing that for now because it's likely to be large and if the problem is persistent, we could always decode it from the job_info table.

Comment (andyyang890) [reply pkg/ccl/changefeedccl/changefeed_processors.go]: Updated, all of the "move to draining logs" are non-verbose now

File: pkg/ccl/changefeedccl/changefeed_processors.go [hunk 4]
```diff
@@ -345,19 +345,15 @@ func (ca *changeAggregator) Start(ctx context.Context) {
 
 	spans, err := ca.setupSpansAndFrontier()
 	if err != nil {
-		if log.V(2) {
-			log.Dev.Infof(ca.Ctx(), "change aggregator moving to draining due to error setting up spans and frontier: %v", err)
-		}
+		log.Dev.Warningf(ca.Ctx(), "moving to draining due to error setting up spans and frontier: %v", err)
```
Comment (andyyang890) [inline pkg/ccl/changefeedccl/changefeed_processors.go:348]: I stripped the processor type from all the logs because they're redundant now that the processor type is included as a log tag

File: pkg/ccl/changefeedccl/checkpoint/checkpoint.go [hunk 5]
```diff
@@ -78,11 +78,11 @@ type SpanForwarder interface {
 func Restore(sf SpanForwarder, checkpoint *jobspb.TimestampSpansMap) error {
 	for ts, spans := range checkpoint.All() {
 		if ts.IsEmpty() {
-			return errors.New("checkpoint timestamp is empty")
+			return errors.AssertionFailedf("checkpoint timestamp is empty")
```
Comment (rharding6373) [inline pkg/ccl/changefeedccl/checkpoint/checkpoint.go:81]: Won't the `AssertionFailedf` cause the node to panic? Is this the behavior we want, or is there a graceful way to recover?

**Review by rharding6373 — APPROVED** [review]
LGTM, modulo one clarification about errors usage. I'm hopeful that the logging improvements will help in the future, so thanks for making those changes!

File: pkg/ccl/changefeedccl/checkpoint/checkpoint.go (hunk 5 above)
Comment (andyyang890) [reply pkg/ccl/changefeedccl/checkpoint/checkpoint.go:81]: It will, but this would only happen as the result of developer error. It should've been marked as an assertion error when it was first added.

**Comment by andyyang890** [comment]
TFTR!

bors r=rharding6373
