### PR TITLE
roachtest: rerun the test if failed due to VM preemption

### LINKED ISSUE #128450: roachtest: with selective test enabled, the test that failed due to VM preemption is not run on on-demand the next time
The expectation is that if a test fails due to preemption for one day, the test should be run in an on-demand VM the next time. This logic does not work well with selective test.

This is why - 
When selective test is enabled, the tests are run in an interval. But, VM preemption check is done on the previous day. So, as the previous run is ignored, the preemption information is lost.

To solve this, if we run all the tests that have failed due to VM preemption on the next day, the logic will work.

Jira issue: CRDB-41023

### PR DESCRIPTION
**Pull request by nameisbhaskar**
We are considering all tests that have failed due to preemption as success. But, if the test has failed due to a preemption, the test is run one more time to ensure that the test is good. The test is run on an on-demand VM to ensure that the test does not fail again due to preemption.

Without this change, the logic of running a test on demand will not work as we consider preemption test failures as success and can get ignored in the next run. Because of the test getting ignored, the information of the last run being failed due to a preemption is lost.

Fixes: #128450
Epic: none

### CODE REVIEW

**Review by vidit-bhat — APPROVED** [review]
LGTM

File: pkg/cmd/roachtest/testselector/snowflake_query.sql [hunk 1]
```diff
@@ -39,9 +39,14 @@ select
   test_name,
   case when
          -- mark as selected if
-         failure_count > 0 or -- the test has failed at least once in the past "forPastDays" days
-         first_run > dateadd(DAY, ?, ts.t) or -- recently added test - test has not run for more than "firstRunOn" days
-         last_run < dateadd(DAY, ?, ts.t) or -- the test has not been run for last "lastRunOn" days
+          -- the test has failed at least once in the past "forPastDays" days
+          -- recently added test - test has not run for more than "firstRunOn" days
+          -- the test has not been run for last "lastRunOn" days
+          -- the last failure was VM preemption
```
Comment (vidit-bhat) [inline pkg/cmd/roachtest/testselector/snowflake_query.sql:45]: nit: indentation seems a bit off

Comment (nameisbhaskar) [reply pkg/cmd/roachtest/testselector/snowflake_query.sql:45]: I made it that way to make it sub points

**Comment by nameisbhaskar** [comment]
Thanks @vidit-bhat for reviewing the change! I have put the clarification on the indentation.

**Comment by nameisbhaskar** [comment]
bors r=@vidit-bhat

**Comment by nameisbhaskar** [comment]
blathers backport 24.2

**Comment by nameisbhaskar** [comment]
blathers backport 24.2
