### PR TITLE
drpc, server: implement filtering rules for server initialization state

### LINKED ISSUE #153948: kv/kvserver: TestProcessSplitAfterRightHandSideHasBeenRemoved failed
kv/kvserver.TestProcessSplitAfterRightHandSideHasBeenRemoved [failed](https://mesolite.cluster.engflow.com/invocations/default/3d1dca9d-aaef-4eb1-aa97-c0e552454d57?testReportRun=3&testReportShard=1&testReportAttempt=1#targets-Ly9wa2cva3Yva3ZzZXJ2ZXI6a3ZzZXJ2ZXJfdGVzdA==) on master @ [9469c4b269f66f6c4c03dbfcb574faf0a5bb7c85](https://github.com/cockroachdb/cockroach/commits/9469c4b269f66f6c4c03dbfcb574faf0a5bb7c85):

```
      <autogenerated>:1 +0xd5
  storj.io/drpc/drpcmux.getChainedStreamHandler.func1()
      external/io_storj_drpc/drpcmux/interceptor.go:77 +0x109
  github.com/cockroachdb/cockroach/pkg/rpc.NewDRPCServer.makeStopperInterceptors.func3.1()
      pkg/rpc/drpc.go:190 +0x58
  github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunTaskWithErr()
      pkg/util/stop/stopper.go:351 +0x246
  github.com/cockroachdb/cockroach/pkg/rpc.NewDRPCServer.makeStopperInterceptors.func3()
      pkg/rpc/drpc.go:188 +0x13d
  storj.io/drpc/drpcmux.NewWithInterceptors.chainStreamInterceptors.func2()
      external/io_storj_drpc/drpcmux/interceptor.go:63 +0xe9
  storj.io/drpc/drpcmux.(*Mux).HandleRPC()
      external/io_storj_drpc/drpcmux/handle_rpc.go:40 +0x488
  storj.io/drpc/drpcserver.(*Server).handleRPC()
      external/io_storj_drpc/drpcserver/server.go:192 +0x77
  storj.io/drpc/drpcserver.(*Server).ServeOne()
      external/io_storj_drpc/drpcserver/server.go:134 +0x504
  storj.io/drpc/drpcserver.(*Server).Serve.func2()
      external/io_storj_drpc/drpcserver/server.go:182 +0x84
  storj.io/drpc/drpcctx.(*Tracker).track()
      external/io_storj_drpc/drpcctx/tracker.go:35 +0x3a
  storj.io/drpc/drpcctx.(*Tracker).Run.gowrap1()
      external/io_storj_drpc/drpcctx/tracker.go:30 +0x44

Goroutine 46260 (running) created at:
  testing.(*T).Run()
      GOROOT/src/testing/testing.go:1743 +0x825
  github.com/cockroachdb/cockroach/pkg/kv/kvserver_test.TestProcessSplitAfterRightHandSideHasBeenRemoved.func1()
      pkg/kv/kvserver/client_raft_test.go:5513 +0x7a4
  github.com/cockroachdb/cockroach/pkg/testutils.RunValues[go.shape.*uint8,go.shape.int32].func1()
      pkg/testutils/subtest.go:23 +0x41
  testing.tRunner()
      GOROOT/src/testing/testing.go:1690 +0x226
  testing.(*T).Run.gowrap1()
      GOROOT/src/testing/testing.go:1743 +0x44

Goroutine 53582 (running) created at:
  storj.io/drpc/drpcctx.(*Tracker).Run()
      external/io_storj_drpc/drpcctx/tracker.go:30 +0xe5
  storj.io/drpc/drpcserver.(*Server).Serve()
      external/io_storj_drpc/drpcserver/server.go:181 +0x448
  github.com/cockroachdb/cockroach/pkg/rpc.(*drpcServer).Serve()
      <autogenerated>:1 +0x71
  github.com/cockroachdb/cockroach/pkg/server.startListenRPCAndSQL.func6.2()
      pkg/server/start_listen.go:203 +0x13a
  github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunAsyncTaskEx.func1()
      pkg/util/stop/stopper.go:440 +0x115
  github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunAsyncTaskEx.gowrap1()
      pkg/util/stop/stopper.go:441 +0x4f
==================
```

Parameters:
 - <code>attempt=1</code>
 - <code>race=true</code>
 - <code>run=3</code>
 - <code>shard=1</code>
<details><summary>Help</summary>
<p>

See also: [How To Investigate a Go Test Failure \(internal\)](https://cockroachlabs.atlassian.net/l/c/HgfXfJgM)
</p>
</details>
/cc @cockroachdb/kv-triage
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*TestProcessSplitAfterRightHandSideHasBeenRemoved.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/bazci/githubpost/issues)

</sub>

Jira issue: CRDB-54687

### LINKED ISSUE #154144: kv/kvserver: TestRestoreReplicas failed
kv/kvserver.TestRestoreReplicas [failed](https://mesolite.cluster.engflow.com/invocations/default/9ce9467a-1ea6-449e-afde-9308d3bdcfea?testReportRun=2&testReportShard=2&testReportAttempt=1#targets-Ly9wa2cva3Yva3ZzZXJ2ZXI6a3ZzZXJ2ZXJfdGVzdA==) on master @ [66ad1d1fd02864a4ad8cf181a3031f3e12312f5a](https://github.com/cockroachdb/cockroach/commits/66ad1d1fd02864a4ad8cf181a3031f3e12312f5a):

```
      external/io_storj_drpc/drpcmux/interceptor.go:63 +0xe9
  storj.io/drpc/drpcmux.(*Mux).HandleRPC()
      external/io_storj_drpc/drpcmux/handle_rpc.go:40 +0x488
  storj.io/drpc/drpcserver.(*Server).handleRPC()
      external/io_storj_drpc/drpcserver/server.go:192 +0x77
  storj.io/drpc/drpcserver.(*Server).ServeOne()
      external/io_storj_drpc/drpcserver/server.go:134 +0x504
  storj.io/drpc/drpcserver.(*Server).Serve.func2()
      external/io_storj_drpc/drpcserver/server.go:182 +0x84
  storj.io/drpc/drpcctx.(*Tracker).track()
      external/io_storj_drpc/drpcctx/tracker.go:35 +0x3a
  storj.io/drpc/drpcctx.(*Tracker).Run.gowrap1()
      external/io_storj_drpc/drpcctx/tracker.go:30 +0x44

Goroutine 3760 (running) created at:
  testing.(*T).Run()
      GOROOT/src/testing/testing.go:1743 +0x825
  testing.runTests.func1()
      GOROOT/src/testing/testing.go:2168 +0x85
  testing.tRunner()
      GOROOT/src/testing/testing.go:1690 +0x226
  testing.runTests()
      GOROOT/src/testing/testing.go:2166 +0x8be
  testing.(*M).Run()
      GOROOT/src/testing/testing.go:2034 +0xf17
  github.com/cockroachdb/cockroach/pkg/kv/kvserver_test.TestMain()
      pkg/kv/kvserver/main_test.go:41 +0x1f5
  main.main()
      bazel-out/k8-fastbuild/bin/pkg/kv/kvserver/kvserver_test_/testmain.go:1814 +0x753
  runtime.main()
      GOROOT/src/runtime/proc.go:272 +0x28a
  github.com/cockroachdb/cockroach/pkg/util/parquet.box2DDecoder.decode()
      pkg/util/parquet/decoders.go:175 +0x3b
  github.com/cockroachdb/cockroach/pkg/util/parquet.init.0()
      pkg/util/parquet/decoders.go:414 +0x1d0

Goroutine 8123 (running) created at:
  storj.io/drpc/drpcctx.(*Tracker).Run()
      external/io_storj_drpc/drpcctx/tracker.go:30 +0xe5
  storj.io/drpc/drpcserver.(*Server).Serve()
      external/io_storj_drpc/drpcserver/server.go:181 +0x448
  github.com/cockroachdb/cockroach/pkg/rpc.(*drpcServer).Serve()
      <autogenerated>:1 +0x71
  github.com/cockroachdb/cockroach/pkg/server.startListenRPCAndSQL.func6.2()
      pkg/server/start_listen.go:203 +0x13a
  github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunAsyncTaskEx.func1()
      pkg/util/stop/stopper.go:440 +0x115
  github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunAsyncTaskEx.gowrap1()
      pkg/util/stop/stopper.go:441 +0x4f
==================
```

Parameters:
 - <code>attempt=1</code>
 - <code>race=true</code>
 - <code>run=2</code>
 - <code>shard=2</code>
<details><summary>Help</summary>
<p>

See also: [How To Investigate a Go Test Failure \(internal\)](https://cockroachlabs.atlassian.net/l/c/HgfXfJgM)
</p>
</details>
/cc @cockroachdb/kv-triage
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*TestRestoreReplicas.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/bazci/githubpost/issues)

</sub>

Jira issue: CRDB-54756

### PR DESCRIPTION
**Pull request by Nukitt**
Previously, in DRPC, the `batch` RPC was able to access `node.Descriptor` which was yet to be initialized. This led to a data race, described in #153948.

This wasn't the case for gRPC, because of an interceptor that could filter RPCs during different server states. Particularly, it allows only bootstrap, heartbeat, health and gossip methods during initialization to prevent calls to potentially uninitialized services.

This patch adds this interceptor support into drpc as well. In-depth discussion on this: https://github.com/cockroachdb/cockroach/issues/153948#issuecomment-3332458390

Epic: None
Fixes: #153948
Release note: None

### CODE REVIEW

**Review by shubhamdhama — APPROVED** [review]

File: pkg/server/serve_mode.go [hunk 1]
```diff
@@ -5,7 +5,9 @@
 
 package server
 
-import "sync/atomic"
+import (
+	"sync/atomic"
+)
 
 type serveModeHandler struct {
```
Comment (cthumuluru-crdb) [inline pkg/server/serve_mode.go:10]: I would prefer calling this rpcServer. We don't have to make changes in this PR but probably worth considering in a followup.

**Review by cthumuluru-crdb — APPROVED** [review]
LGTM!
