### PR TITLE
Move sql response error from ResponseHeader to each Result.

### LINKED ISSUE #2203: Add application error for each sql statement
The current wire format only allows specifying an error for an entire response. postgres allows you to 
run multiple commands together (we support that), with the capability to report errors for each command.

mydb=# INSERT INTO t VALUES (, 2); INSERT INTO t VALUES (6, 2);
ERROR:  syntax error at or near ","
LINE 1: INSERT INTO t VALUES (, 2);
                              ^
INSERT 0 1
mydb=# select * from t;
 k | v 
---+---
 1 | 2
 2 | 2
 3 | 2
 5 | 2
 6 | 2
(5 rows)

I'm going to move the application error from the driver.ResponseHeader to driver.Result.

### PR DESCRIPTION
**Pull request by vivekmenezes**
Closes #2203.

### CODE REVIEW

**Comment by vivekmenezes** [comment]
closes https://github.com/cockroachdb/cockroach/issues/2203

File: sql/driver/conn.go [hunk 1]
```diff
@@ -112,6 +109,9 @@ func (c *conn) send(args Request) (*rows, error) {
 		return r, nil
 	}
 	result := resp.Results[index]
+	if result.Error != nil {
```
Comment (tamird) [inline sql/driver/conn.go]: how come this?

File: sql/driver/wire.proto [hunk 2]
```diff
@@ -78,6 +76,9 @@ message Datum {
 
 // A Result is a collection of rows.
 message Result {
+  // Error is non-nil if an error occurred while executing the statement.
```
Comment (tamird) [inline sql/driver/wire.proto]: nit: kinda weird that the nested message `Row` comes after this; why not keep it up top?

File: sql/server.go [hunk 3]
```diff
@@ -106,13 +106,27 @@ func (s *Server) ServeHTTP(w http.ResponseWriter, r *http.Request) {
...
-	// on the reply.
-	reply, err := s.exec(args)
-	if err != nil {
-		errProto := proto.Error{}
-		errProto.SetResponseGoError(err)
-		reply.Error = &errProto
+	// for each result in the reply.
+	reply := s.exec(args, &planMaker)
+
+	// Restore the session state even if there were application-level errors.
```
Comment (tamird) [inline sql/server.go]: "Restore" is probably not the right word

File: sql/server.go [hunk 4]
```diff
@@ -106,13 +106,27 @@ func (s *Server) ServeHTTP(w http.ResponseWriter, r *http.Request) {
...
+	if bytes, err := gogoproto.Marshal(&planMaker.session); err != nil {
+		// Marshaling a `Session` never errors (known from reading the code).
+		panic(err)
```
Comment (tamird) [inline sql/server.go]: now that it's not so ugly to handle here, we can actually do proper error handling and write an http error. not required for this PR

File: sql/server.go [hunk 5]
```diff
@@ -154,82 +168,73 @@ func (p parameters) Arg(i int) (parser.Datum, bool) {
...
-		var plan planNode
-		if err = s.db.Txn(func(txn *client.Txn) error {
-			planMaker.txn = txn
-			plan, err = planMaker.makePlan(stmt)
-			planMaker.txn = nil
-			return err
-		}); err != nil {
-			return
-		}
+		var result driver.Result
```
Comment (tamird) [inline sql/server.go]: why change the way this is declared?

File: sql/testdata/multi-statement [hunk 6]
```diff
@@ -0,0 +1,54 @@
...
+
+statement ok
+INSERT INTO kv (k,v) VALUES ('a', 'b'); INSERT INTO kv (k,v) VALUES ('c', 'd')
+
+query TT
+SELECT * FROM kv
+----
+a b
+c d
+
```
Comment (tamird) [inline sql/testdata/multi-statement]: nit: extra newline here

File: sql/testdata/multi-statement [hunk 7]
```diff
@@ -0,0 +1,54 @@
...
+
+# ok if first statement has error
```
Comment (tamird) [inline sql/testdata/multi-statement]: is this really the behaviour that we want?

File: sql/server.go [hunk 8]
```diff
@@ -154,82 +168,73 @@ func (p parameters) Arg(i int) (parser.Datum, bool) {
...
-		// TODO(tschottdorf) will have to validate the Session information (for
-		// instance, whether access to the stored database is permitted).
-		if err = gogoproto.Unmarshal(req.Session, &planMaker.session); err != nil {
-			return
-		}
-	}
-	var stmts parser.StatementList
-	if stmts, err = parser.Parse(req.Sql); err != nil {
-		return
+	// TODO(vivek): This should parse each statement independently, report parse
```
Comment (tamird) [inline sql/server.go]: :+1:

can you add to this TODO that each statement should be handled in its own method so we can avoid doing the `SetResponseGoError` multiple times?

**Comment by tamird** [comment]
Nice refactor, LGTM.

I'm a bit concerned about the first-statement-errors-are-ok behaviour; is that what postgres does?

File: sql/driver/conn.go (hunk 1 above)
Comment (petermattis) [inline sql/driver/conn.go]: Ditto. I would think we should loop over the results and return the first error that occurred.

File: sql/server.go (hunk 3 above)
Comment (petermattis) [inline sql/server.go]: `s/Restore/Save/g` or `s/Restore/Return/g`

File: sql/server.go [hunk 9]
```diff
@@ -154,82 +168,73 @@ func (p parameters) Arg(i int) (parser.Datum, bool) {
...
+	// errors where necessary and execute all statements that were valid.
+	stmts, err := parser.Parse(req.Sql)
+	if err != nil {
+		// A parse error in one of the statements results in all the statements
+		// mistaken as one statement with a parse error.
```
Comment (petermattis) [inline sql/server.go]: That sentence reads a bit funny. I think you're trying to saying something like: `A parse error occured: we can't determine if there were multiple statements or only one, so just pretend there was one.`

**Comment by vivekmenezes** [comment]
yes that is what Postgres does. Unfortunately the go sql driver doesn't allow me to display multiple errors. This is a limitation of the sql driver and should not limit how the database behaves.

File: sql/driver/conn.go (hunk 1 above)
Comment (vivekmenezes) [inline sql/driver/conn.go]: This is checking if the last result has an error.

File: sql/server.go [hunk 10]
```diff
@@ -154,82 +168,73 @@ func (p parameters) Arg(i int) (parser.Datum, bool) {
...
-		if err = s.db.Txn(func(txn *client.Txn) error {
-			planMaker.txn = txn
-			plan, err = planMaker.makePlan(stmt)
-			planMaker.txn = nil
-			return err
-		}); err != nil {
-			return
-		}
+		var result driver.Result
+		if err := func() error {
```
Comment (petermattis) [inline sql/server.go]: I'm not a fan of super-long if-statements like this. Any reason this can't be moved into an `execStmt()` method?

File: sql/driver/conn.go (hunk 1 above)
Comment (petermattis) [inline sql/driver/conn.go]: We could combine all of the individual error messages into a single message.

**Comment by petermattis** [comment]
We're not a postgres clone and this feels like an area where it isn't necessary to blindly follow postgres. A couple of thoughts:

* If an error occurs in any one of the statements we should return it to the user. Not returning an error because it did not occur on the last statement in a multi-statement request is error-prone (and anti-Go).

* Perhaps all of the statements in a multi-statement request should be executed within a single transaction (if a transaction is not otherwise active). This would make the error behavior we should target obvious: if an error occurs in one of the statements it should abort the transaction and not process the remaining statements.

File: sql/driver/conn.go (hunk 1 above)
Comment (vivekmenezes) [inline sql/driver/conn.go]: I think when you are using the driver you are discouraged from using it with multiple statements. I think we should not do anything fancy for a user who wants to use it in this way. Let's stick with reporting whatever the last result says.

Comment (petermattis) [inline sql/driver/conn.go]: Silently dropping errors is extremely surprising. The justification for doing so needs to be high and included in a comment in the code. Note that combining the individual error messages into a single message would take something like 5 lines of code. I'm not sure I would classify that as fancy. Regardless, I think we might want to change the semantics for multi-statement requests so that they are all or nothing, just as single-statement requests are all or nothing.

My understanding of the postgres protocol is that the protocol itself does not support multi-statement requests. That is, each statement is a separate request.

File: sql/driver/wire.proto [hunk 11]
```diff
@@ -78,16 +76,18 @@ message Datum {
 
 // A Result is a collection of rows.
 message Result {
-  // A Row is a collection of values representing a row in a result.
+   // A Row is a collection of values representing a row in a result.
```
Comment (tamird) [inline sql/driver/wire.proto]: oops

File: sql/server.go [hunk 12]
```diff
@@ -106,14 +106,28 @@ func (s *Server) ServeHTTP(w http.ResponseWriter, r *http.Request) {
 		return
 	}
 
+	// Pick up current session state.
+	// The request user is validated in ServeHTTP. Even in insecure mode,
```
Comment (tamird) [inline sql/server.go]: this comment is kinda weird, since we're **in** `ServeHTTP`

Comment (tamird) [inline sql/server.go]: this validation happens in just the preceding block

File: sql/server.go [hunk 13]
```diff
@@ -106,14 +106,28 @@ func (s *Server) ServeHTTP(w http.ResponseWriter, r *http.Request) {
...
+	// it is guaranteed not to be empty.
+	planMaker := planner{user: args.GetUser()}
+	// TODO(tschottdorf) will have to validate the Session information (for
```
Comment (tamird) [inline sql/server.go]: i think it's time to kill this comment. all our methods do the necessary validation down in the sql code

**Comment by vivekmenezes** [comment]
A few things to think about.

When a multi-statement arrives without a BEGIN we treat each statement as its own statement and execute it in it's own transaction. I think that is the right behavior. a user might submit a multi-statement as one just for performance reasons with the expectation that the statements be execute in their own transaction. The user can always make them sit in the same transaction if they want to but then that should be provided explicitly.

File: sql/server.go [hunk 14]
```diff
@@ -154,82 +168,76 @@ func (p parameters) Arg(i int) (parser.Datum, bool) {
...
+		plan, err = planMaker.makePlan(stmt)
+		planMaker.txn = nil
+		return err
+	}); err != nil {
+		return result, err
+	}
+	result.Columns = plan.Columns()
+	for plan.Next() {
+		values := plan.Values()
+		row := driver.Result_Row{}
```
Comment (tamird) [inline sql/server.go]: i know this is code movement, but nit:
```go
row := driver.Result_Row{Values: make([]driver.Datum, 0, len(values))}
```

**Comment by tamird** [comment]
@vivekmenezes I agree that we should not have all-or-nothing semantics for multiple statements. I think the last remaining item here is that the error returned from `send` should combine all the statement errors as @petermattis suggested.

**Comment by vivekmenezes** [comment]
Okay I'll combine the errors for the driver. Thanks

**Comment by petermattis** [comment]
I'm not sure what the user expects when they submit a multi-statement transaction. I can imagine they are doing it for convenience or for performance or maybe something I'm not thinking of. If they are doing it for convenience, I think all-or-nothing semantics make sense. If they are doing it for performance then we should investigate where the perf bottlenecks are. It is not at all clear to me that using a transaction per statement is faster than using a transaction for the entire request. I wouldn't be surprised if it is slower. 

That said, I'm fine with running a transaction per statement for now. We can revisit this in the future if needed or add a flag to the request to control the behavior.

File: sql/server.go (hunk 14 above)
Comment (vivekmenezes) [inline sql/server.go]: done

File: sql/server.go (hunk 13 above)
Comment (vivekmenezes) [inline sql/server.go]: done

File: sql/driver/wire.proto (hunk 11 above)
Comment (vivekmenezes) [inline sql/driver/wire.proto]: done

File: sql/server.go (hunk 12 above)
Comment (vivekmenezes) [inline sql/server.go]: removed.

File: sql/driver/conn.go (hunk 1 above)
Comment (vivekmenezes) [inline sql/driver/conn.go]: This no longer silently drops an error.

File: sql/driver/wire.proto (hunk 2 above)
Comment (vivekmenezes) [inline sql/driver/wire.proto]: done

File: sql/server.go (hunk 3 above)
Comment (vivekmenezes) [inline sql/server.go]: reworded

File: sql/server.go (hunk 4 above)
Comment (vivekmenezes) [inline sql/server.go]: It now returns a server internal error

File: sql/server.go (hunk 5 above)
Comment (vivekmenezes) [inline sql/server.go]: Its actually not present now with the move to using execStmt(). I do prefer the declaration versus assigning to an empty struct.

File: sql/testdata/multi-statement (hunk 7 above)
Comment (vivekmenezes) [inline sql/testdata/multi-statement]: This behavior is no more.

File: sql/server.go (hunk 8 above)
Comment (vivekmenezes) [inline sql/server.go]: done

**Comment by vivekmenezes** [comment]
Ready for another look. Thanks

File: sql/driver/conn.go [hunk 15]
```diff
@@ -111,6 +108,12 @@ func (c *conn) send(args Request) (*rows, error) {
 	if index < 0 {
 		return r, nil
 	}
+	// Check for any application errors.
+	for _, result := range resp.Results {
+		if result.Error != nil {
+			return nil, result.Error
```
Comment (tamird) [inline sql/driver/conn.go]: we should investigate what the Go drivers for other databases do in this situation (the `psql` CLI client appears to handle each statement individually, both in error handling and result printing).

Could you add a TODO?

**Comment by tamird** [comment]
LGTM

File: sql/driver/conn.go (hunk 15 above)
Comment (petermattis) [inline sql/driver/conn.go]: Another option to returning the first error is to make a custom error type which holds all of the individual errors and the index of the result they came from. Probably not worth doing it at this point, but may be worth a comment.

File: sql/server.go (hunk 8 above)
Comment (petermattis) [inline sql/server.go]: How would we parse each statement independently when they are sent in a single string? We can't reasonably ask the client to break the multiple statements into multiple strings as that involves parsing the SQL. And trying to execute some of the statements when a parse error occurred in one of them sounds like a recipe for errors. I'd nuke this TODO unless you have some reasonable answers here.

File: sql/driver/conn.go (hunk 15 above)
Comment (vivekmenezes) [inline sql/driver/conn.go]: I'll add a comment. I don't this is worth it at this stage. It's not even clear if anyone would want to send multiple statements in a single request. Perhaps someone might have a batch workload that could bunch statements from a stream in the future.

File: sql/server.go (hunk 8 above)
Comment (vivekmenezes) [inline sql/server.go]: Didnt see this comment. Let me remove it in a subsequent change.
