### PR TITLE
schemachange/mixed-versions: handle possible syntax error for BIT(0) column usage

### LINKED ISSUE #131162: roachtest: schemachange/mixed-versions failed
**Note:** This build has runtime assertions enabled. If the same failure was hit in a run without assertions enabled, there should be a similar issue without the B-runtime-assertions-enabled label. If there isn&#39;t one, then this failure is likely due to an assertion violation or (assertion) timeout.

roachtest.schemachange/mixed-versions [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/16985038?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/16985038?buildTab=artifacts#/schemachange/mixed-versions) on master @ [83589fb87caa92fb42e83994f1691978f37e4cbb](https://github.com/cockroachdb/cockroach/commits/83589fb87caa92fb42e83994f1691978f37e4cbb):

```
(mixedversion.go:720).Run: mixed-version test failure while running step 18 (run "run schemachange workload and validation in mixed version"): full command output in run_064232.570264793_n4_COCKROACHRANDOMSEED9.log: COMMAND_PROBLEM: exit status 1
test artifacts and logs in: /artifacts/schemachange/mixed-versions/run_1
```

Parameters:
 - <code>ROACHTEST_arch=amd64</code>
 - <code>ROACHTEST_cloud=gce</code>
 - <code>ROACHTEST_coverageBuild=false</code>
 - <code>ROACHTEST_cpu=4</code>
 - <code>ROACHTEST_encrypted=false</code>
 - <code>ROACHTEST_runtimeAssertionsBuild=true</code>
 - <code>ROACHTEST_ssd=0</code>
<details><summary>Help</summary>
<p>

See: [roachtest README](https://github.com/cockroachdb/cockroach/blob/master/pkg/cmd/roachtest/README.md)

See: [How To Investigate \(internal\)](https://cockroachlabs.atlassian.net/l/c/SSSBr8c7)

See: [Grafana](https://go.crdb.dev/roachtest-grafana/teamcity-16985038/schemachange-mixed-versions/1726987025427/1726987520909)

</p>
</details>
/cc @cockroachdb/sql-foundations
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*schemachange/mixed-versions.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/bazci/githubpost/issues)
</sub>

Jira issue: CRDB-42418

### LINKED ISSUE #133339: roachtest: schemachange/mixed-versions failed
roachtest.schemachange/mixed-versions [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/17434699?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/17434699?buildTab=artifacts#/schemachange/mixed-versions) on release-24.3 @ [36f5b311f33775bbeb26d56003f6831ec9ddd837](https://github.com/cockroachdb/cockroach/commits/36f5b311f33775bbeb26d56003f6831ec9ddd837):

```
(mixedversion.go:732).Run: mixed-version test failure while running step 42 (run "run schemachange workload and validation in mixed version"): full command output in run_101745.452827211_n4_COCKROACHRANDOMSEED1.log: COMMAND_PROBLEM: exit status 1
test artifacts and logs in: /artifacts/schemachange/mixed-versions/run_1
```

Parameters:
 - <code>ROACHTEST_arch=amd64</code>
 - <code>ROACHTEST_cloud=gce</code>
 - <code>ROACHTEST_coverageBuild=false</code>
 - <code>ROACHTEST_cpu=4</code>
 - <code>ROACHTEST_encrypted=false</code>
 - <code>ROACHTEST_runtimeAssertionsBuild=false</code>
 - <code>ROACHTEST_ssd=0</code>
<details><summary>Help</summary>
<p>

See: [roachtest README](https://github.com/cockroachdb/cockroach/blob/master/pkg/cmd/roachtest/README.md)

See: [How To Investigate \(internal\)](https://cockroachlabs.atlassian.net/l/c/SSSBr8c7)

See: [Grafana](https://go.crdb.dev/roachtest-grafana/teamcity-17434699/schemachange-mixed-versions/1729763667170/1729765356279)

</p>
</details>
<details><summary>Same failure on other branches</summary>
<p>

- #132815 roachtest: schemachange/mixed-versions failed [use REFCURSOR prior to 23.2] [C-test-failure O-roachtest O-robot P-2 T-sql-foundations branch-release-23.2.13-rc]
- #131335 roachtest: schemachange/mixed-versions failed [C-test-failure O-roachtest O-robot P-2 T-sql-foundations branch-release-24.1]
- #131162 roachtest: schemachange/mixed-versions failed [B-runtime-assertions-enabled C-test-failure O-roachtest O-robot T-sql-foundations branch-master]
- #130545 roachtest: schemachange/mixed-versions failed [don&#39;t use refcursor in mixed version state] [C-test-failure O-roachtest O-robot P-2 T-sql-foundations branch-release-23.2]
- #130278 roachtest: schemachange/mixed-versions failed [computed column cannot reference a foreign key] [C-test-failure O-roachtest O-robot P-2 T-sql-foundations branch-release-24.2]
- #129395 roachtest: schemachange/mixed-versions failed [index contains stored column &#34;&#34; with unknown ID 0] [C-test-failure O-roachtest O-robot P-2 T-sql-foundations branch-master]
</p>
</details>
/cc @cockroachdb/sql-foundations
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*schemachange/mixed-versions.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/bazci/githubpost/issues)
</sub>

Jira issue: CRDB-43548

### LINKED ISSUE #133790: roachtest: schemachange/mixed-versions failed
roachtest.schemachange/mixed-versions [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/17503884?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/17503884?buildTab=artifacts#/schemachange/mixed-versions) on release-23.2 @ [0348bd03504c3bc53a5e5ddb96e389aba643d2d5](https://github.com/cockroachdb/cockroach/commits/0348bd03504c3bc53a5e5ddb96e389aba643d2d5):

```
(mixedversion.go:705).Run: mixed-version test failure while running step 18 (run "run schemachange workload and validation in mixed version"): full command output in run_061336.185553437_n4_COCKROACHRANDOMSEED3.log: COMMAND_PROBLEM: exit status 1
test artifacts and logs in: /artifacts/schemachange/mixed-versions/run_1
```

Parameters:
 - <code>ROACHTEST_arch=amd64</code>
 - <code>ROACHTEST_cloud=gce</code>
 - <code>ROACHTEST_coverageBuild=false</code>
 - <code>ROACHTEST_cpu=4</code>
 - <code>ROACHTEST_encrypted=false</code>
 - <code>ROACHTEST_metamorphicBuild=false</code>
 - <code>ROACHTEST_ssd=0</code>
<details><summary>Help</summary>
<p>

See: [roachtest README](https://github.com/cockroachdb/cockroach/blob/master/pkg/cmd/roachtest/README.md)

See: [How To Investigate \(internal\)](https://cockroachlabs.atlassian.net/l/c/SSSBr8c7)

See: [Grafana](https://go.crdb.dev/roachtest-grafana/teamcity-17503884/schemachange-mixed-versions/1730268503038/1730268991756)

</p>
</details>
<details><summary>Same failure on other branches</summary>
<p>

- #133339 roachtest: schemachange/mixed-versions failed [C-test-failure O-roachtest O-robot P-2 T-sql-foundations branch-release-24.3]
- #131335 roachtest: schemachange/mixed-versions failed [C-test-failure O-roachtest O-robot P-2 T-sql-foundations branch-release-24.1]
- #131162 roachtest: schemachange/mixed-versions failed [B-runtime-assertions-enabled C-test-failure O-roachtest O-robot T-sql-foundations branch-master]
- #130278 roachtest: schemachange/mixed-versions failed [computed column cannot reference a foreign key] [C-test-failure O-roachtest O-robot P-2 T-sql-foundations branch-release-24.2]
- #129395 roachtest: schemachange/mixed-versions failed [index contains stored column &#34;&#34; with unknown ID 0] [C-test-failure O-roachtest O-robot P-2 T-sql-foundations branch-master]
</p>
</details>
/cc @cockroachdb/sql-foundations
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*schemachange/mixed-versions.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)
</sub>

Jira issue: CRDB-43754

### PR DESCRIPTION
**Pull request by spilchen**
A recent fix enabled support for BIT(0) columns (see issue #132944), which has since been backported. However, since this backport hasn’t been released yet, running against an older down-level client may still trigger a syntax error. This change adds a temporary check to handle such errors until the backports for #132944 are publicly released.

This adjustment will be backported to older branches, with slight variations per release:
- release-24.3: Reuse the same fix as in master.
- release-24.2: Use isClusterVersionLessThan with clusterversion.V24.2.
- release-24.1: Use isClusterVersionLessThan with clusterversion.V24.1.
- release-23.2: Use isClusterVersionLessThan with clusterversion.V23.2.

Epic: None
Release note: None
Closes #133339
Closes #133790
Closes #131162

### CODE REVIEW

**Review by rafiss — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/134407)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @DarrylWong, @spilchen, and @vidit-bhat)

___
*[`pkg/workload/schemachange/operation_generator.go` line 1281 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/134407#-OB1nKM89A_d3SXF8sEf:-OB1nKM9Ej1TnyATsZSo:b-fttct2) ([raw file](https://github.com/cockroachdb/cockroach/blob/ffdfb4062a5a5463e7a63dd2769dda151dac0ee9/pkg/workload/schemachange/operation_generator.go#L1281)):*
> ```Go
> 		return false
> 	}()
> 	hasBit0Type := func() bool {
> ```

i think we'll want to block this in other places also, like in ADD COLUMN and SET DEFAULT

perhaps we could add one helper function where we check if the type is allowed so we can use it in a few places.

File: pkg/workload/schemachange/operation_generator.go [hunk 1]
```diff
@@ -4808,6 +4832,22 @@ func isClusterVersionLessThan(
 	return clusterVersion.Less(targetVersion), nil
 }
 
+// isMixedVersionTest works similarly to isClusterVersionLessThan, but without
+// specifying a version. It returns true if the cluster version is not the
+// latest, indicating a mixed-version test.
+func isMixedVersionTest(ctx context.Context, tx pgx.Tx) (bool, error) {
```
Comment (rafiss) [inline pkg/workload/schemachange/operation_generator.go:4838]: super nit: it could be called `inMixedVersionState`, since technically the whole test could be considered a "mixed version test"

**Review by rafiss — APPROVED** [review]
nice! thanks for the fix

**Review by spilchen — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/134407)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @DarrylWong, @rafiss, and @vidit-bhat)

___
*[`pkg/workload/schemachange/operation_generator.go` line 1281 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/134407#-OB1nKM89A_d3SXF8sEf:-OB2GSWm9HH9tFvIFkMD:bb6un1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/ffdfb4062a5a5463e7a63dd2769dda151dac0ee9/pkg/workload/schemachange/operation_generator.go#L1281)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

i think we'll want to block this in other places also, like in ADD COLUMN and SET DEFAULT

perhaps we could add one helper function where we check if the type is allowed so we can use it in a few places.
</blockquote></details>

Done
___
*[`pkg/workload/schemachange/operation_generator.go` line 4838 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/134407#gh-1831688139:-OB2GXM0565814l2t7wJ:bdcv6l8) ([raw file](https://github.com/cockroachdb/cockroach/blob/5750fb9519100a8f651d43629ed0bab0adf82c35/pkg/workload/schemachange/operation_generator.go#L4838)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

super nit: it could be called `inMixedVersionState`, since technically the whole test could be considered a "mixed version test"
</blockquote></details>

Good point.

**Comment by spilchen** [comment]
TFTR!

bors r+
