### PR TITLE
sql: Make tochar.FormatCache thread safe

### LINKED ISSUE #95424: util/tochar: nil pointer when looking up FormatCache
This issue was autofiled by Sentry. It represents a crash or reported error on a live cluster with telemetry enabled.

Sentry link: https://sentry.io/organizations/cockroach-labs/issues/3881949480/?referrer=webhooks_plugin

Panic message:

>conn_executor.go:830: runtime error: invalid memory address or nil pointer dereference
(1) attached stack trace
  -- stack trace:
  | github.com/cockroachdb/cockroach/pkg/sql.(*Server).ServeConn.func1
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:830
  | [...repeated from below...]
Wraps: (2) while executing: SELECT _, _, _, CAST(rtrim(_) AS VARCHAR(1)), _, CAST(rtrim(_) AS VARCHAR(1)), CAST(to_char(_, '_') AS VARCHAR(50)), _, CAST(to_char(_, '_') AS VARCHAR(50)), _, CAST(upper(md5(convert_to(_, '_'))) AS VARCHAR(64)), _, _, _, CAST(to_char(_, '_') AS VARCHAR(50)) FROM _ WHERE (((_ <= '_'))) ORDER BY _ ASC
Wraps: (3) attached stack trace
  -- stack trace:
  | github.com/cockroachdb/cockroach/pkg/sql.(*Server).ServeConn.func1
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:830
  | runtime.gopanic
  | 	GOROOT/src/runtime/panic.go:884
  | github.com/cockroachdb/cockroach/pkg/sql/colexecerror.CatchVectorizedRuntimeError.func1
  | 	github.com/cockroachdb/cockroach/pkg/sql/colexecerror/error.go:58
  | runtime.gopanic
  | 	GOROOT/src/runtime/panic.go:884
  | github.com/cockroachdb/cockroach/pkg/sql/colexecerror.CatchVectorizedRuntimeError.func1
  | 	github.com/cockroachdb/cockroach/pkg/sql/colexecerror/error.go:58
  | runtime.gopanic
  | 	GOROOT/src/runtime/panic.go:884
  | runtime.panicmem
  | 	GOROOT/src/runtime/panic.go:260
  | runtime.sigpanic
  | 	GOROOT/src/runtime/signal_unix.go:835
  | github.com/cockroachdb/cockroach/pkg/util/cache.(*entryList).remove
  | 	github.com/cockroachdb/cockroach/pkg/util/cache/cache.go:153
  | github.com/cockroachdb/cockroach/pkg/util/cache.(*entryList).moveToFront
  | 	github.com/cockroachdb/cockroach/pkg/util/cache/cache.go:168
  | github.com/cockroachdb/cockroach/pkg/util/cache.(*baseCache).access
  | 	github.com/cockroachdb/cockroach/pkg/util/cache/cache.go:314
  | github.com/cockroachdb/cockroach/pkg/util/cache.(*baseCache).Get
  | 	github.com/cockroachdb/cockroach/pkg/util/cache/cache.go:256
  | github.com/cockroachdb/cockroach/pkg/util/tochar.(*FormatCache).lookup.func1
  | 	github.com/cockroachdb/cockroach/pkg/util/tochar/cache.go:46
  | github.com/cockroachdb/cockroach/pkg/util/tochar.(*FormatCache).lookup
  | 	github.com/cockroachdb/cockroach/pkg/util/tochar/cache.go:51
  | github.com/cockroachdb/cockroach/pkg/util/tochar.TimeToChar
  | 	github.com/cockroachdb/cockroach/pkg/util/tochar/tochar.go:29
  | github.com/cockroachdb/cockroach/pkg/sql/sem/builtins.glob..func136
  | 	github.com/cockroachdb/cockroach/pkg/sql/sem/builtins/builtins.go:2458
  | github.com/cockroachdb/cockroach/pkg/sql/colexec.(*defaultBuiltinFuncOperator).Next.func1
  | 	github.com/cockroachdb/cockroach/pkg/sql/colexec/builtin_funcs.go:77
  | github.com/cockroachdb/cockroach/pkg/sql/colmem.(*Allocator).PerformOperation
  | 	github.com/cockroachdb/cockroach/pkg/sql/colmem/allocator.go:441
  | github.com/cockroachdb/cockroach/pkg/sql/colexec.(*defaultBuiltinFuncOperator).Next
  | 	github.com/cockroachdb/cockroach/pkg/sql/colexec/builtin_funcs.go:54
  | github.com/cockroachdb/cockroach/pkg/sql/colexec/colexecutils.(*vectorTypeEnforcer).Next
  | 	github.com/cockroachdb/cockroach/pkg/sql/colexec/colexecutils/operator.go:137
  | github.com/cockroachdb/cockroach/pkg/sql/colexec/colexecbase.(*castStringStringOp).Next
  | 	github.com/cockroachdb/cockroach/bazel-out/k8-opt/bin/pkg/sql/colexec/colexecbase/cast.eg.go:10735
  | github.com/cockroachdb/cockroach/pkg/sql/colexec/colexecbase.(*simpleProjectOp).Next
  | 	github.com/cockroachdb/cockroach/pkg/sql/colexec/colexecbase/simple_project.go:124
  | github.com/cockroachdb/cockroach/pkg/sql/colflow.(*batchInfoCollector).next
  | 	github.com/cockroachdb/cockroach/pkg/sql/colflow/stats.go:116
  | github.com/cockroachdb/cockroach/pkg/sql/colexecerror.CatchVectorizedRuntimeError
  | 	github.com/cockroachdb/cockroach/pkg/sql/colexecerror/error.go:92
  | github.com/cockroachdb/cockroach/pkg/sql/colflow.(*batchInfoCollector).Next
  | 	github.com/cockroachdb/cockroach/pkg/sql/colflow/stats.go:124
  | github.com/cockroachdb/cockroach/pkg/sql/colflow.(*BatchFlowCoordinator).nextAdapter
  | 	github.com/cockroachdb/cockroach/pkg/sql/colflow/flow_coordinator.go:252
  | github.com/cockroachdb/cockroach/pkg/sql/colexecerror.CatchVectorizedRuntimeError
  | 	github.com/cockroachdb/cockroach/pkg/sql/colexecerror/error.go:92
  | github.com/cockroachdb/cockroach/pkg/sql/colflow.(*BatchFlowCoordinator).next
  | 	github.com/cockroachdb/cockroach/pkg/sql/colflow/flow_coordinator.go:256
  | github.com/cockroachdb/cockroach/pkg/sql/colflow.(*BatchFlowCoordinator).Run
  | 	github.com/cockroachdb/cockroach/pkg/sql/colflow/flow_coordinator.go:299
  | github.com/cockroachdb/cockroach/pkg/sql/colflow.(*vectorizedFlow).Run
  | 	github.com/cockroachdb/cockroach/pkg/sql/colflow/vectorized_flow.go:320
  | github.com/cockroachdb/cockroach/pkg/sql.(*DistSQLPlanner).Run
  | 	github.com/cockroachdb/cockroach/pkg/sql/distsql_running.go:731
  | github.com/cockroachdb/cockroach/pkg/sql.(*DistSQLPlanner).PlanAndRun
  | 	github.com/cockroachdb/cockroach/pkg/sql/distsql_running.go:1698
Wraps: (4) runtime error: invalid memory address or nil pointer dereference
Error types: (1) *withstack.withStack (2) *safedetails.withSafeDetails (3) *withstack.withStack (4) runtime.errorString
-- report composition:
runtime.errorString
conn_executor.go:830: *withstack.withStack (top exception)
*safedetails.withSafeDetails: while executing: SELECT _, _, _, CAST(rtrim(_) AS VARCHAR(1)), _, CAST(rtrim(_) AS VARCHAR(1)), CAST(to_char(_, '_') AS VARCHAR(50)), _, CAST(to_char(_, '_') AS VARCHAR(50)), _, CAST(upper(md5(convert_to(_, '_'))) AS VARCHAR(64)), _, _, _, CAST(to_char(_, '_') AS VARCHAR(50)) FROM _ WHERE (((_ <= '_'))) ORDER BY _ ASC
conn_executor.go:830: *withstack.withStack (1)
(check the extra data payloads)

<details>
<summary>Stacktrace (expand for inline code snippets):</summary>

https://github.com/cockroachdb/cockroach/blob/07a53a36601e9ca5fcffcff55f69b43c6dfbf1c1/pkg/sql/conn_executor.go#L829-L831 in pkg/sql.(*Server).ServeConn.func1
GOROOT/src/runtime/panic.go#L883-L885 in runtime.gopanic
https://github.com/cockroachdb/cockroach/blob/07a53a36601e9ca5fcffcff55f69b43c6dfbf1c1/pkg/sql/colexecerror/error.go#L57-L59 in pkg/sql/colexecerror.CatchVectorizedRuntimeError.func1
GOROOT/src/runtime/panic.go#L883-L885 in runtime.gopanic
https://github.com/cockroachdb/cockroach/blob/07a53a36601e9ca5fcffcff55f69b43c6dfbf1c1/pkg/sql/colexecerror/error.go#L57-L59 in pkg/sql/colexecerror.CatchVectorizedRuntimeError.func1
GOROOT/src/runtime/panic.go#L883-L885 in runtime.gopanic
GOROOT/src/runtime/panic.go#L259-L261 in runtime.panicmem
GOROOT/src/runtime/signal_unix.go#L834-L836 in runtime.sigpanic
https://github.com/cockroachdb/cockroach/blob/07a53a36601e9ca5fcffcff55f69b43c6dfbf1c1/pkg/util/cache/cache.go#L152-L154 in pkg/util/cache.(*entryList).remove
https://github.com/cockroachdb/cockroach/blob/07a53a36601e9ca5fcffcff55f69b43c6dfbf1c1/pkg/util/cache/cache.go#L167-L169 in pkg/util/cache.(*entryList).moveToFront
https://github.com/cockroachdb/cockroach/blob/07a53a36601e9ca5fcffcff55f69b43c6dfbf1c1/pkg/util/cache/cache.go#L313-L315 in pkg/util/cache.(*baseCache).access
https://github.com/cockroachdb/cockroach/blob/07a53a36601e9ca5fcffcff55f69b43c6dfbf1c1/pkg/util/cache/cache.go#L255-L257 in pkg/util/cache.(*baseCache).Get
https://github.com/cockroachdb/cockroach/blob/07a53a36601e9ca5fcffcff55f69b43c6dfbf1c1/pkg/util/tochar/cache.go#L45-L47 in pkg/util/tochar.(*FormatCache).lookup.func1
https://github.com/cockroachdb/cockroach/blob/07a53a36601e9ca5fcffcff55f69b43c6dfbf1c1/pkg/util/tochar/cache.go#L50-L52 in pkg/util/tochar.(*FormatCache).lookup
https://github.com/cockroachdb/cockroach/blob/07a53a36601e9ca5fcffcff55f69b43c6dfbf1c1/pkg/util/tochar/tochar.go#L28-L30 in pkg/util/tochar.TimeToChar
https://github.com/cockroachdb/cockroach/blob/07a53a36601e9ca5fcffcff55f69b43c6dfbf1c1/pkg/sql/sem/builtins/builtins.go#L2457-L2459 in pkg/sql/sem/builtins.glob..func136
https://github.com/cockroachdb/cockroach/blob/07a53a36601e9ca5fcffcff55f69b43c6dfbf1c1/pkg/sql/colexec/builtin_funcs.go#L76-L78 in pkg/sql/colexec.(*defaultBuiltinFuncOperator).Next.func1
https://github.com/cockroachdb/cockroach/blob/07a53a36601e9ca5fcffcff55f69b43c6dfbf1c1/pkg/sql/colmem/allocator.go#L440-L442 in pkg/sql/colmem.(*Allocator).PerformOperation
https://github.com/cockroachdb/cockroach/blob/07a53a36601e9ca5fcffcff55f69b43c6dfbf1c1/pkg/sql/colexec/builtin_funcs.go#L53-L55 in pkg/sql/colexec.(*defaultBuiltinFuncOperator).Next
https://github.com/cockroachdb/cockroach/blob/07a53a36601e9ca5fcffcff55f69b43c6dfbf1c1/pkg/sql/colexec/colexecutils/operator.go#L136-L138 in pkg/sql/colexec/colexecutils.(*vectorTypeEnforcer).Next
https://github.com/cockroachdb/cockroach/blob/07a53a36601e9ca5fcffcff55f69b43c6dfbf1c1/bazel-out/k8-opt/bin/pkg/sql/colexec/colexecbase/cast.eg.go#L10734-L10736 in pkg/sql/colexec/colexecbase.(*castStringStringOp).Next
https://github.com/cockroachdb/cockroach/blob/07a53a36601e9ca5fcffcff55f69b43c6dfbf1c1/pkg/sql/colexec/colexecbase/simple_project.go#L123-L125 in pkg/sql/colexec/colexecbase.(*simpleProjectOp).Next
https://github.com/cockroachdb/cockroach/blob/07a53a36601e9ca5fcffcff55f69b43c6dfbf1c1/pkg/sql/colflow/stats.go#L115-L117 in pkg/sql/colflow.(*batchInfoCollector).next
https://github.com/cockroachdb/cockroach/blob/07a53a36601e9ca5fcffcff55f69b43c6dfbf1c1/pkg/sql/colexecerror/error.go#L91-L93 in pkg/sql/colexecerror.CatchVectorizedRuntimeError
https://github.com/cockroachdb/cockroach/blob/07a53a36601e9ca5fcffcff55f69b43c6dfbf1c1/pkg/sql/colflow/stats.go#L123-L125 in pkg/sql/colflow.(*batchInfoCollector).Next
https://github.com/cockroachdb/cockroach/blob/07a53a36601e9ca5fcffcff55f69b43c6dfbf1c1/pkg/sql/colflow/flow_coordinator.go#L251-L253 in pkg/sql/colflow.(*BatchFlowCoordinator).nextAdapter
https://github.com/cockroachdb/cockroach/blob/07a53a36601e9ca5fcffcff55f69b43c6dfbf1c1/pkg/sql/colexecerror/error.go#L91-L93 in pkg/sql/colexecerror.CatchVectorizedRuntimeError
https://github.com/cockroachdb/cockroach/blob/07a53a36601e9ca5fcffcff55f69b43c6dfbf1c1/pkg/sql/colflow/flow_coordinator.go#L255-L257 in pkg/sql/colflow.(*BatchFlowCoordinator).next
https://github.com/cockroachdb/cockroach/blob/07a53a36601e9ca5fcffcff55f69b43c6dfbf1c1/pkg/sql/colflow/flow_coordinator.go#L298-L300 in pkg/sql/colflow.(*BatchFlowCoordinator).Run
https://github.com/cockroachdb/cockroach/blob/07a53a36601e9ca5fcffcff55f69b43c6dfbf1c1/pkg/sql/colflow/vectorized_flow.go#L319-L321 in pkg/sql/colflow.(*vectorizedFlow).Run
https://github.com/cockroachdb/cockroach/blob/07a53a36601e9ca5fcffcff55f69b43c6dfbf1c1/pkg/sql/distsql_running.go#L730-L732 in pkg/sql.(*DistSQLPlanner).Run
https://github.com/cockroachdb/cockroach/blob/07a53a36601e9ca5fcffcff55f69b43c6dfbf1c1/pkg/sql/distsql_running.go#L1697-L1699 in pkg/sql.(*DistSQLPlanner).PlanAndRun
</details>

```
pkg/sql/conn_executor.go in pkg/sql.(*Server).ServeConn.func1 at line 830
GOROOT/src/runtime/panic.go in runtime.gopanic at line 884
pkg/sql/colexecerror/error.go in pkg/sql/colexecerror.CatchVectorizedRuntimeError.func1 at line 58
GOROOT/src/runtime/panic.go in runtime.gopanic at line 884
pkg/sql/colexecerror/error.go in pkg/sql/colexecerror.CatchVectorizedRuntimeError.func1 at line 58
GOROOT/src/runtime/panic.go in runtime.gopanic at line 884
GOROOT/src/runtime/panic.go in runtime.panicmem at line 260
GOROOT/src/runtime/signal_unix.go in runtime.sigpanic at line 835
pkg/util/cache/cache.go in pkg/util/cache.(*entryList).remove at line 153
pkg/util/cache/cache.go in pkg/util/cache.(*entryList).moveToFront at line 168
pkg/util/cache/cache.go in pkg/util/cache.(*baseCache).access at line 314
pkg/util/cache/cache.go in pkg/util/cache.(*baseCache).Get at line 256
pkg/util/tochar/cache.go in pkg/util/tochar.(*FormatCache).lookup.func1 at line 46
pkg/util/tochar/cache.go in pkg/util/tochar.(*FormatCache).lookup at line 51
pkg/util/tochar/tochar.go in pkg/util/tochar.TimeToChar at line 29
pkg/sql/sem/builtins/builtins.go in pkg/sql/sem/builtins.glob..func136 at line 2458
pkg/sql/colexec/builtin_funcs.go in pkg/sql/colexec.(*defaultBuiltinFuncOperator).Next.func1 at line 77
pkg/sql/colmem/allocator.go in pkg/sql/colmem.(*Allocator).PerformOperation at line 441
pkg/sql/colexec/builtin_funcs.go in pkg/sql/colexec.(*defaultBuiltinFuncOperator).Next at line 54
pkg/sql/colexec/colexecutils/operator.go in pkg/sql/colexec/colexecutils.(*vectorTypeEnforcer).Next at line 137
bazel-out/k8-opt/bin/pkg/sql/colexec/colexecbase/cast.eg.go in pkg/sql/colexec/colexecbase.(*castStringStringOp).Next at line 10735
pkg/sql/colexec/colexecbase/simple_project.go in pkg/sql/colexec/colexecbase.(*simpleProjectOp).Next at line 124
pkg/sql/colflow/stats.go in pkg/sql/colflow.(*batchInfoCollector).next at line 116
pkg/sql/colexecerror/error.go in pkg/sql/colexecerror.CatchVectorizedRuntimeError at line 92
pkg/sql/colflow/stats.go in pkg/sql/colflow.(*batchInfoCollector).Next at line 124
pkg/sql/colflow/flow_coordinator.go in pkg/sql/colflow.(*BatchFlowCoordinator).nextAdapter at line 252
pkg/sql/colexecerror/error.go in pkg/sql/colexecerror.CatchVectorizedRuntimeError at line 92
pkg/sql/colflow/flow_coordinator.go in pkg/sql/colflow.(*BatchFlowCoordinator).next at line 256
pkg/sql/colflow/flow_coordinator.go in pkg/sql/colflow.(*BatchFlowCoordinator).Run at line 299
pkg/sql/colflow/vectorized_flow.go in pkg/sql/colflow.(*vectorizedFlow).Run at line 320
pkg/sql/distsql_running.go in pkg/sql.(*DistSQLPlanner).Run at line 731
pkg/sql/distsql_running.go in pkg/sql.(*DistSQLPlanner).PlanAndRun at line 1698
```

| Tag | Value |
|---|---|
| Cockroach Release | `v22.2.2` |
| Cockroach SHA: | 07a53a36601e9ca5fcffcff55f69b43c6dfbf1c1 |
| Platform | linux amd64 |
| Distribution | CCL |
| Environment | v22.2.2 |
| Command | server |
| Go Version | ``|
| # of CPUs ||
| # of Goroutines ||

Jira issue: CRDB-23510

### PR DESCRIPTION
**Pull request by ecwall**
Fixes #95424

`FormatCache.lookup()` previously wrapped calls to `cache.UnorderedCache.Get()` in `RWMutex.RLock()`/`RWMutex.RUnlock()` which allowed for data races because `UnorderedCache.Get()` can modify the state of its LRU cache.

This PR fixes the race condition by changing the `RWMutex` to a `Mutex` to handle cases where the LRU cache is modified.

Release note (bug fix): Fix nil pointer dereference caused by race condition when using to_char builtin.

### CODE REVIEW

**Review by otan — APPROVED** [review]

**Comment by ecwall** [comment]
bors r=otan

**Comment by rafiss** [comment]
bors r-

question before this merges in: does this have a performance impact?

File: pkg/util/tochar/cache_test.go [hunk 1]
```diff
@@ -40,3 +40,17 @@ func TestFormatCache(t *testing.T) {
 	_, ok = c.mu.cache.Get("HH24")
 	require.True(t, ok)
 }
+
+// TestFormatCacheLookupThreadSafe tests that FormatCache.lookup is thread safe.
+// This test is non-deterministic and flakes indicate it is not thread safe.
```
Comment (rafiss) [inline pkg/util/tochar/cache_test.go:45]: nit: i think the comment should be updated. after your fix, it should not be flaky right?

**Comment by ecwall** [comment]
> bors r-
> 
> 
> 
> question before this merges in: does this have a performance impact?

Yes. The cache can only handle one read at a time now.

**Review by rafiss — APPROVED** [review]
nvm, ignore me. i thought this cache was shared by other components, but if this is just used for the to_char function, i don't think we need to worry about that level of performance.

File: pkg/util/tochar/cache_test.go (hunk 1 above)
Comment (ecwall) [reply pkg/util/tochar/cache_test.go:45]: The comment isn't saying that the test is flaky, but if it flakes then the code being tested is probably not thread safe.

Comment (rafiss) [reply pkg/util/tochar/cache_test.go:45]: ah ok. i read at as "This test is non-deterministic and flakes, ..."

maybe add a comma: "This test is non-deterministic, and flakes indicate...

Comment (ecwall) [reply pkg/util/tochar/cache_test.go]: Fixed

**Comment by ecwall** [comment]
bors r=otan,rafiss
