### PR TITLE
roachtest: fix tpchbench

### LINKED ISSUE #37669: roachtest: tpchbench/sql20/nodes=3/cpu=4/sf=1 failed
SHA: https://github.com/cockroachdb/cockroach/commits/9671342fead0509bec0913bae4ae1f244660788e

Parameters:

To repro, try:

```
# Don't forget to check out a clean suitable branch and experiment with the
# stress invocation until the desired results present themselves. For example,
# using stress instead of stressrace and passing the '-p' stressflag which
# controls concurrency.
./scripts/gceworker.sh start && ./scripts/gceworker.sh mosh
cd ~/go/src/github.com/cockroachdb/cockroach && \
stdbuf -oL -eL \
make stressrace TESTS=tpchbench/sql20/nodes=3/cpu=4/sf=1 PKG=roachtest TESTTIMEOUT=5m STRESSFLAGS='-maxtime 20m -timeout 10m' 2>&1 | tee /tmp/stress.log
```

Failed test: https://teamcity.cockroachdb.com/viewLog.html?buildId=1298500&tab=buildLog

```
The test failed on branch=release-19.1, cloud=gce:
	tpchbench.go:93,cluster.go:1812,errgroup.go:57: open sql20: no such file or directory
	cluster.go:1833,tpchbench.go:114,tpchbench.go:190,test.go:1251: Goexit() was called

```

### LINKED ISSUE #37797: roachtest: tpchbench/tpch/nodes=3/cpu=4/sf=1 failed
SHA: https://github.com/cockroachdb/cockroach/commits/699f675c73f8420802f92e46f65e6dce52abc12f

Parameters:

To repro, try:

```
# Don't forget to check out a clean suitable branch and experiment with the
# stress invocation until the desired results present themselves. For example,
# using stress instead of stressrace and passing the '-p' stressflag which
# controls concurrency.
./scripts/gceworker.sh start && ./scripts/gceworker.sh mosh
cd ~/go/src/github.com/cockroachdb/cockroach && \
stdbuf -oL -eL \
make stressrace TESTS=tpchbench/tpch/nodes=3/cpu=4/sf=1 PKG=roachtest TESTTIMEOUT=5m STRESSFLAGS='-maxtime 20m -timeout 10m' 2>&1 | tee /tmp/stress.log
```

Failed test: https://teamcity.cockroachdb.com/viewLog.html?buildId=1306268&tab=buildLog

```
The test failed on branch=release-19.1, cloud=gce:
	tpchbench.go:93,cluster.go:1854,errgroup.go:57: open tpch: no such file or directory
	cluster.go:1875,tpchbench.go:114,tpchbench.go:190,test.go:1251: Goexit() was called

```

### LINKED ISSUE #37799: roachtest: tpchbench/tpchVec/nodes=3/cpu=4/sf=1 failed
SHA: https://github.com/cockroachdb/cockroach/commits/699f675c73f8420802f92e46f65e6dce52abc12f

Parameters:

To repro, try:

```
# Don't forget to check out a clean suitable branch and experiment with the
# stress invocation until the desired results present themselves. For example,
# using stress instead of stressrace and passing the '-p' stressflag which
# controls concurrency.
./scripts/gceworker.sh start && ./scripts/gceworker.sh mosh
cd ~/go/src/github.com/cockroachdb/cockroach && \
stdbuf -oL -eL \
make stressrace TESTS=tpchbench/tpchVec/nodes=3/cpu=4/sf=1 PKG=roachtest TESTTIMEOUT=5m STRESSFLAGS='-maxtime 20m -timeout 10m' 2>&1 | tee /tmp/stress.log
```

Failed test: https://teamcity.cockroachdb.com/viewLog.html?buildId=1306268&tab=buildLog

```
The test failed on branch=release-19.1, cloud=gce:
	tpchbench.go:93,cluster.go:1854,errgroup.go:57: open tpchVec: no such file or directory
	cluster.go:1875,tpchbench.go:114,tpchbench.go:190,test.go:1251: Goexit() was called

```

### PR DESCRIPTION
**Pull request by yuzefovich**
Previously, there was an incorrect assumption that executing
querybench.GetQueries will happen on the same node as the workload
is running from. However, that code actually executes on the machine
issuing the commands for roachprod nodes, so now that machine itself
downloads the query file and parses it in order to populate the
correct workload command.

Fixes #37669, fixes #37799, fixes #37797.

Release note: None

### CODE REVIEW

**Comment by yuzefovich** [comment]
Friendly ping @nvanbenschoten @asubiotto.

File: pkg/cmd/roachtest/tpchbench.go [hunk 1]
```diff
@@ -114,6 +117,44 @@ func runTPCHBench(ctx context.Context, t *test, c *cluster, b tpchBenchSpec) {
...
+		return 0, err
+	}
+	if err = os.Remove(filename); err != nil {
+		return 0, err
+	}
+	return len(queries), nil
+}
+
+// downloadFile will download a url to a local file.
+func downloadFile(filepath string, url string) error {
```
Comment (nvanbenschoten) [inline pkg/cmd/roachtest/tpchbench.go]: Do you want to put this file in the `/tmp` directory? See [`ioutil.TempFile`](https://golang.org/pkg/io/ioutil/#TempFile).

**Review by yuzefovich — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/37695)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto and @nvanbenschoten)

___
*[pkg/cmd/roachtest/tpchbench.go, line 138 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/37695#-LfQT_TrYFFW1-8X3v65-r1-138:-Lfh5sGx57kPhQ5cxcdE:bfbq99i) ([raw file](https://github.com/cockroachdb/cockroach/blob/c4008075c6cdb52b65e139ae8bdf15eee8a7be6a/pkg/cmd/roachtest/tpchbench.go#L138)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Do you want to put this file in the `/tmp` directory? See [`ioutil.TempFile`](https://golang.org/pkg/io/ioutil/#TempFile).
</blockquote></details>

Good point, done.

File: pkg/cmd/roachtest/tpchbench.go [hunk 2]
```diff
@@ -114,6 +118,43 @@ func runTPCHBench(ctx context.Context, t *test, c *cluster, b tpchBenchSpec) {
...
+func downloadFile(filename string, url string) (*os.File, error) {
+	// Get the data.
+	resp, err := http.Get(url)
+	if err != nil {
+		return nil, err
+	}
+	defer resp.Body.Close()
+
+	// Create the file.
+	out, err := ioutil.TempFile(`/tmp` /* dir */, filename)
```
Comment (nvanbenschoten) [inline pkg/cmd/roachtest/tpchbench.go]: I think you can leave the `dir` field empty to get the system default.

**Review by nvb — APPROVED** [review]

**Review by yuzefovich — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/37695)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto and @nvanbenschoten)

___
*[pkg/cmd/roachtest/tpchbench.go, line 147 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/37695#-LfQT_TrYFFW1-8X3v65-r2-147:-LfjZQrW50XyrqDx4jDw:b-staw08) ([raw file](https://github.com/cockroachdb/cockroach/blob/7a7246216894329589eacff343698c8b43251f72/pkg/cmd/roachtest/tpchbench.go#L147)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

I think you can leave the `dir` arg empty to get the system default.
</blockquote></details>

Indeed - didn't read the comment carefully enough.

**Comment by yuzefovich** [comment]
TFTR!

bors r+
