### PR TITLE
roachtest: increase consistency check timeout, and ignore errors

### LINKED ISSUE #68883: roachtest: kv/splits/nodes=3/quiesce=true failed
roachtest.kv/splits/nodes=3/quiesce=true [failed](https://teamcity.cockroachdb.com/viewLog.html?buildId=3296712&tab=buildLog) with [artifacts](https://teamcity.cockroachdb.com/viewLog.html?buildId=3296712&tab=artifacts#/kv/splits/nodes=3/quiesce=true) on master @ [3928f1963833fbf51ae47bd2a42ae6a200ebbb14](https://github.com/cockroachdb/cockroach/commits/3928f1963833fbf51ae47bd2a42ae6a200ebbb14):

```
The test failed on branch=master, cloud=gce:
test artifacts and logs in: /home/agent/work/.go/src/github.com/cockroachdb/cockroach/artifacts/kv/splits/nodes=3/quiesce=true/run_1
	cluster.go:1339,test_runner.go:881: operation "consistency check" timed out after 1m0s: driver: bad connection
		(1) operation "consistency check" timed out after 1m0s
		Wraps: (2) driver: bad connection
		Error types: (1) *contextutil.TimeoutError (2) *errors.errorString
```
<details><summary>Reproduce</summary>
<p>

See: [roachtest README](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/roachtest)

See: [CI job to stress roachtests](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestStress)

<p>For the CI stress job, click the ellipsis (...) next to the Run button and fill in:
* Changes / Build branch: master
* Parameters / `env.TESTS`: `^kv/splits/nodes=3/quiesce=true$`
* Parameters / `env.COUNT`: &lt;number of runs&gt;
</p>
</p>
</details>
/cc @cockroachdb/kv-triage
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*kv/splits/nodes=3/quiesce=true.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)
</sub>

### PR DESCRIPTION
**Pull request by erikgrinaker**
This bumps the consistency check timeout to 5 minutes. There are
indications that a recent libpq upgrade unmasked previously ignored
context cancellation errors, caused by the timeout here being too low.
It also ignores errors during the consistency check, since it is
best-effort anyway.

Resolves #68883.

Release justification: non-production code changes
Release note: None

### CODE REVIEW

**Review by tbg — APPROVED** [review]
Should we bump it up a bit more though? It also seems as though we may want to *not* return an error if we hit the context cancellation. The consistency check is best-effort after all, and we don't want problems with it to post issues for an otherwise healthy test.

File: pkg/cmd/roachtest/cluster.go [hunk 1]
```diff
@@ -1278,6 +1278,7 @@ WHERE t.status NOT IN ('RANGE_CONSISTENT', 'RANGE_INDETERMINATE')`)
 		l.Printf("consistency check failed with %v; ignoring", err)
 		return nil
 	}
+	defer rows.Close()
```
Comment (stevendanna) [inline pkg/cmd/roachtest/cluster.go:1281]: Nice. A quick check using the sqlclosecheck shows we have a few more cases of omitting a Close().  In many cases it likely doesn't matter because we are following up with t.Fatal(). (No need to handle them here, I'll open an issue)

**Comment by erikgrinaker** [comment]
>Should we bump it up a bit more though?

Sure, bumped to 5 minutes.

>It also seems as though we may want to not return an error if we hit the context cancellation. The consistency check is best-effort after all, and we don't want problems with it to post issues for an otherwise healthy test.

Makes sense, used the existing convention of outputting a warning for any errors.

**Review by tbg — APPROVED** [review]
thank you!

**Comment by erikgrinaker** [comment]
bors r=tbg
