### PR TITLE
util/metric: fix +Inf values from histogram quantile computation

### LINKED ISSUE #163958: cli: TestZipQueryFallback failed
cli.TestZipQueryFallback [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Ci_TestsIbmCloudLinuxS390x_UnitTestsS390x/21127973?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Ci_TestsIbmCloudLinuxS390x_UnitTestsS390x/21127973?buildTab=artifacts#/) on release-26.1 @ [5122355c4cddec33691f2bedb42feb36b7785070](https://github.com/cockroachdb/cockroach/commits/5122355c4cddec33691f2bedb42feb36b7785070):

```
          [cluster] tenant hot range summary script... writing binary output: debug/hot-ranges-tenant.sh... done
          [cluster] capture debug zip flags... writing binary output: debug/debug_zip_command_flags.txt... done
        output didn't match expected:
          @@ -8,41 +8,8 @@
           [cluster] requesting data for debug/settings... received response... writing JSON output: debug/settings.json... done
           [cluster] requesting data for debug/reports/problemranges... received response... writing JSON output: debug/reports/problemranges.json... done
           <dumping SQL tables>
           [cluster] retrieving SQL data for crdb_internal.transaction_contention_events: last request failed: ERROR: column "fail" does not exist (SQLSTATE 42703)
           <dumping SQL tables>
          -[cluster] requesting nodes... received response... writing JSON output: debug/nodes.json... done
          -[cluster] requesting liveness... received response... writing JSON output: debug/liveness.json... done
          -[cluster] requesting tenant ranges... received response...
          -[cluster] requesting tenant ranges: last request failed: rpc error: ...
          -[cluster] requesting tenant ranges: creating error output: debug/tenant_ranges.err.txt... done
          -[cluster] collecting the inflight traces for jobs... received response... done
          -[cluster] requesting CPU profiles
          -[cluster] profiles generated
          -[cluster] profile for node 1... writing binary output: debug/nodes/1/cpu.pprof... done
          -[node 1] node status... writing JSON output: debug/nodes/1/status.json... done
          -[node 1] using SQL connection URL: postgresql://...
          -<dumping SQL tables>
          -[node 1] requesting data for debug/nodes/1/details... received response... writing JSON output: debug/nodes/1/details.json... done
          -[node 1] requesting data for debug/nodes/1/gossip... received response... writing JSON output: debug/nodes/1/gossip.json... done
          -[node 1] requesting stacks... received response... writing binary output: debug/nodes/1/stacks.txt... done
          -[node 1] requesting stacks with labels... received response... writing binary output: debug/nodes/1/stacks_with_labels.txt... done
          -[node 1] requesting goroutine profile... received response... writing binary output: debug/nodes/1/stacks.pprof... done
          -[node 1] requesting heap profile... received response... writing binary output: debug/nodes/1/heap.pprof... done
          -[node 1] requesting engine stats... received response... writing binary output: debug/nodes/1/lsm.txt... done
          -[node 1] requesting heap profile list... received response... done
          -[node ?] ? heap profiles found
          -[node 1] requesting goroutine dump list... received response... done
          -[node ?] ? goroutine dumps found
          -[node 1] requesting cpu profile list... received response... done
          -[node ?] ? cpu profiles found
          -[node 1] requesting execution trace list... received response... done
          -[node ?] ? execution traces found
          -[node 1] requesting log files list... received response... done
          -[node ?] ? log files found
          -[node 1] requesting ranges... received response... done
          -[node 1] writing ranges... writing JSON output: debug/nodes/1/ranges.json... done
          -[cluster] pprof summary script... writing binary output: debug/pprof-summary.sh... done
          -[cluster] hot range summary script... writing binary output: debug/hot-ranges.sh... done
          -[cluster] tenant hot range summary script... writing binary output: debug/hot-ranges-tenant.sh... done
          -[cluster] capture debug zip flags... writing binary output: debug/debug_zip_command_flags.txt... done
          +[cluster] requesting nodes... received response... writing JSON output: debug/nodes.json... error:json: unsupported value: +Inf
          +ERROR: json: unsupported value: +Inf
           
    panic.go:615: -- test log scope end --
test logs left over in: /artifacts/tmp/_tmp/0eff02e3d605640c0624f6bcc67cf8d4/logTestZipQueryFallback905151987
--- FAIL: TestZipQueryFallback (46.06s)
```
<details><summary>Help</summary>
<p>

See also: [How To Investigate a Go Test Failure \(internal\)](https://cockroachlabs.atlassian.net/l/c/HgfXfJgM)
</p>
</details>
/cc @cockroachdb/obs-prs @cockroachdb/server @cockroachdb/obs-india-prs
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*TestZipQueryFallback.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/bazci/githubpost/issues)

</sub>

Jira issue: CRDB-60549

### PR DESCRIPTION
**Pull request by dhartunian**
ValueAtQuantile could produce +Inf when a histogram bucket had zero observations, causing division by zero in the interpolation formula. The existing guard only checked for NaN and negative infinity, letting +Inf slip through into node status metrics. This caused debug zip to fail with "json: unsupported value: +Inf" when serializing nodes.json, since Go's encoding/json rejects infinity values.

Fix by explicitly handling the count==0 case before division: return bucketStart for rank 0, or bucketEnd otherwise, consistent with the existing upper-bound clamping behavior.

Fixes #163958

Release note: None

### CODE REVIEW

**Review by aa-joshi — APPROVED** [review]
Thanks for fixing this! Let's backport the PR  as it is failing on 26.1.
:lgtm:

> @aa-joshi made 1 comment.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/164006#-:-OluGaeAAIqsFDjyEKvl:bmz26gs)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on Abhinav1299 and alyshanjahani-crl).

File: pkg/util/metric/histogram_snapshot.go [hunk 1]
```diff
@@ -62,7 +62,18 @@ func (hs HistogramSnapshot) ValueAtQuantile(q float64) float64 {
...
+		// when rank is also 0 (quantile 0), otherwise use the bucket end.
+		if rank == 0 {
+			val = bucketStart
+		} else {
+			val = bucketEnd
+		}
+	} else {
+		val = bucketStart + (bucketEnd-bucketStart)*(float64(rank)/float64(count))
+	}
 	if math.IsNaN(val) || math.IsInf(val, -1) {
```
Comment (jasonlmfong) [inline pkg/util/metric/histogram_snapshot.go]: we probably wont run into this line anyway after the fix above, but to be safe, why do we not use `math.IsInf(val, 0)` to guard against both positive and negative infinity?

**Review by jasonlmfong — APPROVED** [review]

File: pkg/util/metric/histogram_snapshot.go (hunk 1 above)
Comment (dhartunian) [reply pkg/util/metric/histogram_snapshot.go]: done
