### PR TITLE
roachtest: fix blocklist and ignorelist

### LINKED ISSUE #96935: roachtest: lib/pq failed
roachtest.lib/pq [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/8655926?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/8655926?buildTab=artifacts#/lib/pq) on master @ [e51ffa013c81212870891001f0328912550fa75d](https://github.com/cockroachdb/cockroach/commits/e51ffa013c81212870891001f0328912550fa75d):

```
test artifacts and logs in: /artifacts/lib/pq/run_1
(orm_helpers.go:191).summarizeFailed: 
Tests run on Cockroach v23.1.0-alpha.1-1850-ge51ffa013c
Tests run against lib/pq v1.10.5
217 Total Tests Run
189 tests passed
28 tests failed
7 tests skipped
0 tests ignored
1 test passed unexpectedly
0 tests failed unexpectedly
0 tests expected failed but skipped
0 tests expected failed but not run
---
--- PASS: pq.TestEncodeAndParseTs - https://github.com/cockroachdb/cockroach/issues/41563 (unexpected)
For a full summary look at the lib/pq artifacts
An updated blocklist (libPQBlocklist23_1) is available in the artifacts' lib/pq log
```
<p>Parameters: <code>ROACHTEST_cloud=gce</code>
, <code>ROACHTEST_cpu=4</code>
, <code>ROACHTEST_encrypted=false</code>
, <code>ROACHTEST_ssd=0</code>
</p>
<details><summary>Help</summary>
<p>

See: [roachtest README](https://github.com/cockroachdb/cockroach/blob/master/pkg/cmd/roachtest/README.md)

See: [How To Investigate \(internal\)](https://cockroachlabs.atlassian.net/l/c/SSSBr8c7)

</p>
</details>
/cc @cockroachdb/sql-sessions
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*lib/pq.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)
</sub>

Jira issue: CRDB-24418

### PR DESCRIPTION
**Pull request by ZhouXing19**
Previously we have release-based block list for roachtests. This is no longer needed as we can just maintain the block list for each branch.

fixes #96935

Release note: None

### CODE REVIEW

File: pkg/cmd/roachtest/tests/libpq_blocklist.go [hunk 1]
```diff
@@ -19,7 +19,36 @@ var libPQBlocklists = blocklistsForVersion{
 	{"v23.1", "libPQBlocklist23_1", libPQBlocklist23_1, "libPQIgnorelist23_1", libPQIgnorelist23_1},
 }
 
-var libPQBlocklist23_1 = libPQBlocklist22_2
+var libPQBlocklist23_1 = blocklist{
```
Comment (rafiss) [inline pkg/cmd/roachtest/tests/libpq_blocklist.go:22]: can you change the test so it only has one blocklist, similar to how django_blocklist was changed? we don't need per-version maps, since we can now just have one list that is different on each release branch

**Review by rafiss — CHANGES_REQUESTED** [review]

File: pkg/cmd/roachtest/tests/libpq_blocklist.go (hunk 1 above)
Comment (ZhouXing19) [reply pkg/cmd/roachtest/tests/libpq_blocklist.go]: Done. Will change the other versions' in a bit.

**Comment by ZhouXing19** [comment]
RFAL, thanks!

**Review by rafiss — APPROVED** [review]
that's great! thanks for updating them all.

**Comment by ZhouXing19** [comment]
TFTR!

bors r=rafiss
