### PR TITLE
cli/sql: fix the handling of --set

### LINKED ISSUE #46116: cli/sql: `--set` does not properly override defaults
Using e.g. `--set=smart_prompt=false` does not work properly.

Reported by @andreimatei

### PR DESCRIPTION
**Pull request by knz**
Fixes #46116

I intend to backport this to 19.2 (bug fix)

Release justification: Category 2: Bug fixes and low-risk updates to new functionality

Release note (bug fix): The parameter `--set` for `cockroach sql` and
`cockroach demo` is now properly able to override all client-side
options, as advertised.

### CODE REVIEW

File: pkg/cli/sql.go [hunk 1]
```diff
@@ -1416,6 +1323,115 @@ func runInteractive(conn *sqlConn) (exitErr error) {
...
+// The returned cleanupFn must be called even when the err return is
+// not nil.
+func (c *cliState) configurePreShellDefaults() (cleanupFn func(), err error) {
+	if cliCtx.terminalOutput {
+		// If results are shown on a terminal also enable printing of
+		// times by default.
+		sqlCtx.showTimes = true
+	}
+	if cliCtx.isInteractive && !sqlCtx.debugMode {
+		// If the terminal is interactive and this was not explicitly disabled by setting the debug mode,
```
Comment (rohany) [inline pkg/cli/sql.go]: [nit]: long comment

**Review by rohany — COMMENTED** [review]
Just to confirm from reading, this change just moves all the default settings logic into a separate function, and then runs the user provided overrides after the setup logic has run?

**Comment by knz** [comment]
> Just to confirm from reading, this change just moves all the default settings logic into a separate function, and then runs the user provided overrides after the setup logic has run?

yes

**Comment by rohany** [comment]
lgtm

File: pkg/cli/sql.go (hunk 1 above)
Comment (knz) [reply pkg/cli/sql.go]: Fixed.

**Comment by knz** [comment]
TFYR

bors r=rohany

**Comment by knz** [comment]
bors r=rohany
