### PR TITLE
sql: implement pg_catalog.pg_attribute.atttypmod

### LINKED ISSUE #16032: sql: JDBC ResultSetMetaData precision incorrect
For a column created with

  DATA varchar(16384)

the JDBC ResultSetMetaData.getPrecision  (<https://docs.oracle.com/javase/7/docs/api/java/sql/ResultSetMetaData.html#getPrecision(int)>) apparently returns 2GB.

(see also <https://issues.apache.org/jira/browse/OAK-6238>)

### PR DESCRIPTION
**Pull request by jordanlewis**
This field contains information about the scale, precision and/or width
of various datatypes and is important for client compatibility.

Fixes #16032.

Release note (sql change): the atttypmod column of the pg_attribute
catalog table is supported.

### CODE REVIEW

File: pkg/sql/pg_catalog.go [hunk 1]
```diff
@@ -378,19 +378,37 @@ CREATE TABLE pg_catalog.pg_attribute (
 			// addColumn adds adds either a table or a index column to the pg_attribute table.
 			addColumn := func(column *sqlbase.ColumnDescriptor, attRelID tree.Datum, colID sqlbase.ColumnID) error {
 				colTyp := &column.Type
+				attTypMod := -1
+				width := int(colTyp.Width())
```
Comment (mjibson) [inline pkg/sql/pg_catalog.go]: nit: if this isn't used outside the if, might make more sense to `if width := ...; width != 0`

File: pkg/sql/pg_catalog.go [hunk 2]
```diff
@@ -378,19 +378,37 @@ CREATE TABLE pg_catalog.pg_attribute (
 			// addColumn adds adds either a table or a index column to the pg_attribute table.
 			addColumn := func(column *sqlbase.ColumnDescriptor, attRelID tree.Datum, colID sqlbase.ColumnID) error {
 				colTyp := &column.Type
+				attTypMod := -1
```
Comment (mjibson) [inline pkg/sql/pg_catalog.go]: Make this an int32 since that's the type postgres returns

File: pkg/sql/pg_catalog.go [hunk 3]
```diff
@@ -378,19 +378,37 @@ CREATE TABLE pg_catalog.pg_attribute (
...
+				width := int(colTyp.Width())
+				if width != 0 {
+					switch colTyp.Family() {
```
Comment (mjibson) [inline pkg/sql/pg_catalog.go]: should we add a `default: panic` or something here to make sure we don't miss other types that can have a width?

Comment (jordanlewis) [reply pkg/sql/pg_catalog.go]: I don't think so - these are exactly the set of types that need this logic, based on my investigations.

**Comment by jordanlewis** [comment]
RFAL!

**Review by madelynnblue — APPROVED** [review]

**Comment by jordanlewis** [comment]
bors r+

TFTR
