### PR TITLE
c2c: fix rangefeed error propogration race

### LINKED ISSUE #102286: ccl/streamingccl/streamproducer: TestStreamPartition failed
ccl/streamingccl/streamproducer.TestStreamPartition [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Ci_TestsAwsLinuxArm64_UnitTests/9799281?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Ci_TestsAwsLinuxArm64_UnitTests/9799281?buildTab=artifacts#/) on release-23.1 @ [ec0b5087392d49980a2141315aae62bb2563348f](https://github.com/cockroachdb/cockroach/commits/ec0b5087392d49980a2141315aae62bb2563348f):

Fatal error:

```
panic: test timed out after 14m55s

```
Stack: 

```
goroutine 58890 [running]:
testing.(*M).startAlarm.func1()
	GOROOT/src/testing/testing.go:2036 +0x88
created by time.goFunc
	GOROOT/src/time/sleep.go:176 +0x38
```
<details><summary>Log preceding fatal error</summary>
<p>

```
=== RUN   TestStreamPartition
    test_log_scope.go:161: test logs captured to: /artifacts/tmp/_tmp/ec6a3f034611d027670bad7acfd7b3dd/logTestStreamPartition337479638
    test_log_scope.go:79: use -show-logs to present logs inline
=== RUN   TestStreamPartition/stream-table-cursor-error
```
</p>
</details>
<details><summary>Help</summary>
<p>

See also: [How To Investigate a Go Test Failure \(internal\)](https://cockroachlabs.atlassian.net/l/c/HgfXfJgM)
</p>
</details>
<details><summary>Same failure on other branches</summary>
<p>

- #88429 ccl/streamingccl/streamproducer: TestStreamPartition failed [C-test-failure O-robot T-cdc branch-release-22.1]
</p>
</details>
/cc @cockroachdb/disaster-recovery
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*TestStreamPartition.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)
</sub>

Jira issue: CRDB-27382

### PR DESCRIPTION
**Pull request by msbutler**
In the producer dist sql processor, rangefeed errors only propograte to the user if the error can be sent on a non-blocking channel. Because the channel was previously unbuffered, the dist sql processor would inadvertently swallow the error if the receiver was not actively waiting on the channel. This would then cause the sql processor to hang, as the underlying rangefeed would close after the ignored error message.

This patch buffers the errCh, guaranteeing that the first rangefeed error will be processed by the sql processor. If the rangefeed surfaces several errors while the buffered channel is full, these errors will be swallowed, which is fine, as the first error will always shut down the sql processor.

Fixes #102286

Release note: None

### CODE REVIEW

File: pkg/ccl/streamingccl/streamproducer/replication_stream_test.go [hunk 1]
```diff
@@ -375,13 +378,8 @@ USE d;
...
 		require.Nil(t, err)
 
-		expected := replicationtestutils.EncodeKV(t, srcTenant.Codec, t2Descr, 42)
-		feed.ObserveKey(ctx, expected.Key)
 		feed.ObserveError(ctx, func(err error) bool {
-			return strings.Contains(err.Error(), "unexpected MVCC history mutation") ||
-				// TODO(casper): disabled this once we figured out why we have context cancellation
-				// emitted from ingestion side.
-				strings.Contains(err.Error(), "context canceled")
+			return strings.Contains(err.Error(), "unexpected MVCC history mutation")
```
Comment (stevendanna) [inline pkg/ccl/streamingccl/streamproducer/replication_stream_test.go:382]: I assume we have run this under stress and haven't see context canceled any longer?

**Review by stevendanna — APPROVED** [review]
Nice sleuthing here.
