### PR TITLE
Fix Negative SysBytes value in UI

### LINKED ISSUE #4969: ui: Negative "system bytes" displayed in UI
The "system bytes" field occasionally appears as negative for some nodes after applying heavy load.  The negative number is cleared if the server is restarted.  

This is almost certainly an issue with incremental calculations of store-level MVCCStats.

### LINKED ISSUE #5027: storage: TestStoreMetrics is flaky
https://circleci.com/gh/cockroachdb/cockroach/14136

```
E160309 18:42:00.603071 storage/replica.go:1325  [node=1,store=1,range=2] error executing raft command: retry txn "storage/replica_command.go:1841 (*Replica).ChangeReplicas" id=fbba271b key=/Local/Range/"m"/RangeDescriptor rw=false pri=0.02707192 iso=SERIALIZABLE stat=PENDING epo=0 ts=0.000000000,94 orig=0.000000000,94 max=0.000000000,94
E160309 18:42:00.604670 storage/replica.go:1325  [node=2,store=2,range=2] error executing raft command: retry txn "storage/replica_command.go:1841 (*Replica).ChangeReplicas" id=fbba271b key=/Local/Range/"m"/RangeDescriptor rw=false pri=0.02707192 iso=SERIALIZABLE stat=PENDING epo=0 ts=0.000000000,94 orig=0.000000000,94 max=0.000000000,94
I160309 18:42:00.608722 storage/replica.go:1086  raft: proposing ADD_REPLICA {3 3 3} for range 2
I160309 18:42:00.623102 storage/raft_transport.go:173  dialing node 3 at 127.0.0.1:57902
I160309 18:42:00.623454 storage/raft_transport.go:186  establishing Raft transport stream to node 3 at 127.0.0.1:57902
I160309 18:42:00.631976 raft/raft.go:459  [group 2] 3 became follower at term 0
I160309 18:42:00.632280 raft/raft.go:235  [group 2] newRaft 3 [peers: [], term: 0, commit: 0, applied: 0, lastindex: 0, lastterm: 0]
I160309 18:42:00.632387 raft/raft.go:459  [group 2] 3 became follower at term 1
I160309 18:42:00.632552 raft/raft.go:556  [group 2] 3 [term: 1] received a MsgApp message with higher term from 1 [term: 6]
I160309 18:42:00.632624 raft/raft.go:459  [group 2] 3 became follower at term 6
I160309 18:42:00.642544 raft/raft.go:802  [group 2] 3 [commit: 0, lastindex: 0, lastterm: 0] starts to restore snapshot [index: 21, term: 6]
I160309 18:42:00.643784 raft/log.go:291  [group 2] log [committed=0, applied=0, unstable.offset=1, len(unstable.Entries)=0] starts to restore snapshot [index: 21, term: 6]
I160309 18:42:00.643907 raft/raft.go:814  [group 2] 3 restored progress of 1 [next = 22, match = 0, state = ProgressStateProbe, waiting = false, pendingSnapshot = 0]
I160309 18:42:00.644128 raft/raft.go:814  [group 2] 3 restored progress of 2 [next = 22, match = 0, state = ProgressStateProbe, waiting = false, pendingSnapshot = 0]
I160309 18:42:00.644240 raft/raft.go:814  [group 2] 3 restored progress of 3 [next = 22, match = 21, state = ProgressStateProbe, waiting = false, pendingSnapshot = 0]
I160309 18:42:00.644317 raft/raft.go:779  [group 2] 3 [commit: 21] restored snapshot [index: 21, term: 6]
E160309 18:42:00.653462 storage/client_test.go:741  engine 1: missing key "z"
E160309 18:42:00.655016 storage/client_test.go:741  engine 2: missing key "z"
I160309 18:42:00.669143 storage/replica.go:1086  raft: proposing REMOVE_REPLICA {1 1 1} for range 2
W160309 18:42:00.688191 storage/replica.go:1842  could not GC completed transaction: range 2 was not found
I160309 18:42:00.699184 storage/replica_gc_queue.go:131  destroying local data from range 2
E160309 18:42:00.700269 storage/client_test.go:741  engine 0: missing key "z"
I160309 18:42:00.702866 storage/raft_transport.go:221  remote node 2 at 127.0.0.1:34495 closed Raft transport with error: rpc error: code = 13 desc = "transport is closing"
I160309 18:42:00.704078 storage/raft_transport.go:221  remote node 1 at 127.0.0.1:52580 closed Raft transport with error: rpc error: code = 13 desc = "transport is closing"
I160309 18:42:00.704288 storage/raft_transport.go:221  remote node 3 at 127.0.0.1:57902 closed Raft transport with error: rpc error: code = 13 desc = "transport is closing"
I160309 18:42:00.710000 storage/engine/rocksdb.go:141  closing in-memory rocksdb instance
I160309 18:42:00.710268 storage/engine/rocksdb.go:141  closing in-memory rocksdb instance
I160309 18:42:00.710450 storage/engine/rocksdb.go:141  closing in-memory rocksdb instance
	client_metrics_test.go:53: storage/client_metrics_test.go:137: ranges for store: actual 2 != expected 1
	client_metrics_test.go:89: storage/client_metrics_test.go:140: verifyStats failed, aborting test.
      
```

### PR DESCRIPTION
**Pull request by mrtracy**
A bug in the storage system resulted in the "SysBytes" value of MVCCStats being
radically wrong in the UI, and occasionally becoming negative.

The bug occurred when an incoming transaction was rejected due to an application
error (such as a CPut error) - even though the modifications of the batch itself
were rejected, an entry is still written to the sequence cache, which results in
a change to the SysBytes count. This stats change was correctly being applied to
the replica stats, but was _not_ being applied to the store stats. This caused
the store stats to diverge from the cumulative stats of its replicas (as well as
its on-disk count).

Negative numbers resulted when a replica was removed from the store; the
replica's SysBytes number was correct, but the store's SysBytes number would be
significantly too low. When the replica's stats were subtracted, a negative
number results.

This commit also fixes an occassional error in TestStoreMetrics which resulted
from a race condition.

Fixes #5027
Fixes #4969

---

This change is [Review on Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/5040)

### CODE REVIEW

**Comment by tschottdorf** [comment]
:lgtm: 

---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[storage/replica.go, line 1366 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5040#-KCSuHYQVrzFtUWCr-iE:-KCSuHYQVrzFtUWCr-iF:272383651) ([raw file](https://github.com/cockroachdb/cockroach/blob/8c07bec3d81804a04987589c1ba3a5202bbfca91/storage/replica.go#L1366)):*
should we have a common entry point for both this and the one a few lines up? It seems that those two would always happen in unison.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/5040#-:-KCSuTS-iqufZv7WcWMm:980077423)*

**Comment by mrtracy** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[storage/replica.go, line 1366 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5040#-KCSuHYQVrzFtUWCr-iE:-KCSxJHJ0TadqwdLZtuk:-539231680) ([raw file](https://github.com/cockroachdb/cockroach/blob/8c07bec3d81804a04987589c1ba3a5202bbfca91/storage/replica.go#L1366)):*
If you're referring to this and `MergeMVCCStats()`, this is actually the only place in the code base that `MergeMVCCStats()` is called, so I don't feel there's a pressing need. :)

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/5040)*

File: storage/client_metrics_test.go [hunk 1]
```diff
@@ -114,16 +117,31 @@ func TestStoreMetrics(t *testing.T) {
...
+	verifyStats(t, store0)
+	verifyStats(t, store1)
+
+	// Create a transaction statement that fails, but will add an entry to the
+	// sequence cache. Regression test for #4969.
+	if pErr := mtc.db.Txn(func(txn *client.Txn) *roachpb.Error {
+		b := &client.Batch{}
+		b.CPut(dataKey, 7, 6)
+		return txn.Run(b)
+	}); pErr == nil {
```
Comment (tamird) [inline storage/client_metrics_test.go]: You should use a stronger assertion here using testutils.IsPErr
