### PR TITLE
sql: add pgvector in a couple of missing places

### LINKED ISSUE #126797: sql/tests: TestRandomSyntaxFunctions failed [unexpected type *tree.DPGVector for key value]
sql/tests.TestRandomSyntaxFunctions [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RandomSyntaxTestsBazel/15962700?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RandomSyntaxTestsBazel/15962700?buildTab=artifacts#/) on master @ [485975b3a824c68c07340e6a336c7864c00d3c6d](https://github.com/cockroachdb/cockroach/commits/485975b3a824c68c07340e6a336c7864c00d3c6d):

Random syntax error:

```
    rsg_test.go:952: Crash detected: server panic: pq: internal error: json_build_object(): unexpected type *tree.DPGVector for key value
```
Query:

```
        SELECT json_build_object('[4.4863963e+31,1.0620651e-21,-3.0774692e-28,-3.3615404e+12,-5.751797e-36,3.942246e-23,3.341043e+22,9.377869e+19,-1.0892656e+32,-7.1248327e-23,-7.5853667e+21,2.3025588e+16,-2.6126623e+17,-2.2329434e-26,1.1567591e+17,3.7160787e+37,-1.5157945e+14,6.939009e-12,9.593984e-32,-8.293799e+17,-1.8589085e-14,-4.924684e+28,-4.1420842e-07,1.3935711e+24,-1.3725125e+09,8.3007316e+14,-3.021332e+31,4.600241e+07,-4.3771626e-34,3.8841305e-33,-2.6163444e+29,-15.114348,-6.4531405e+09,3.491911e+34,-2.0333033e+37,1.9452971e+24,-2.7444542e-25,-4.930941e+25,-16890.947,2.6423569e+20,1.4498091e-33,-5.4730945,3.49774e-22,1.0783855e-13,-7.2380674e+28,-1.08817135e+20,-4.2827096e+29,-7.5074517e-31,-3.741234e+16,1.0460863e+22,-4.330997e-29,2.2294262e-05,-1.3235696e+07,-1.1223255e+17,-3.658471e-20,-1.4715207e+22,-3.7165906e-34,-3.0788028e+28,1.4521223e+13,-7.7062385e+09,-3.2988925e-36,1.7122341e-18,1.08949533e-16,6.253621e+07,-2.2759272e-07,-2.865124e+10,-3.5318712e+17,-1.1005964e-33,-2.841466e-30,1.5653757e-33,-2.8177482e+10,-1.148251e-36,-7.830025e+31,1.9217614e+34,-6.438044e+14,-7.082459e-07,1.811556e+15,-1.8670433e-07,0.11316652,-2.3336323e+32,1.2805114e-29,-228074.02,1.4850773e-06,-6.899438e+33,1.3105202e+30,-3.0887935e+37,-3.6818792e-27,3.9076608e+18,-1.00252705e+20,-1.2760645e+10,-1.117895e+33,1.2566674e+24,-1.9346928e-26,-2.5484186e+38,1.2107292e-09,-2.4768271e-18,0.0019410405,-6.2767034e+20,-3.5449523e+28,0.056910608,2.5560109e+29,-1.6551216e+31,-1.1486371e+19,-9.328185e-36,-7.2470166e-21,-9.1796284e+16,-5.070185e+10,4.6755167e-23,-2.233391e+23,1.1573487e+18,-5.6681734e+29,0.05661485,-6.3878547e+18,6.948227e+34,1.1971405e-38,-2.4000366e+08,8.170989e+29,4.7696426e-30,-2.7540391e-15,-2.567814e+26,-1.4374724e-05,-1.2220865e+38,3.7437305e+10,-2.5390503e-27,1.8778825e-26,1.0593359e+10,-3.558209e+36,-2.416654e-21,2.7839911e+38,-3.253562e-35,-3.0352075e-15,3.5352505e+22,-2.612087e-13,-3.1507777e-10,-4.069628e-05,-3.329564e-37,1.8313953e+11,6.863465e-19,1.4417783e-25,-0.0059395265,1.1036954e-23,1.8227136e+24,117.789444,135079.23,1.12816324e+36,8.652247e-09,-1.2914163e+24,3.0696932e+16,-6.0331934e-07,2.2575358e+23,-0.7618738,2.5527428e+27,-6.7368676e-22]':::VECTOR, ARRAY[18273:::INT8,28400:::INT8,(-29028):::INT8]) ;
```
<details><summary>Help</summary>
<p>

See also: [How To Investigate a Go Test Failure \(internal\)](https://cockroachlabs.atlassian.net/l/c/HgfXfJgM)
</p>
</details>
/cc @cockroachdb/sql-foundations
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*TestRandomSyntaxFunctions.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/bazci/githubpost/issues)
</sub>

Jira issue: CRDB-40134

### PR DESCRIPTION
**Pull request by yuzefovich**
This commit expands the recently added support for PGVector to the following places:
- PG binary encoding is now supported (see https://github.com/pgvector/pgvector/blob/8772c8de68cf11fba59b381db8f262951222358f/src/vector.c#L413-L430 for the source code)
- `json_build_object` builtin

It also adds a comment for why we consciously didn't add support for PGVector in CDC avro format.

Fixes: #126797.

Release note: None

### CODE REVIEW

**Review by DrewKimball — APPROVED** [review]
:lgtm:

> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/126833#-:-O1JINjJ3fu2h9px_APD:bnfp4nl)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @jordanlewis)

File: pkg/ccl/changefeedccl/avro.go [hunk 1]
```diff
@@ -623,6 +623,16 @@ func typeToAvroSchema(typ *types.T) (*avroSchemaField, error) {
 				return tree.ParseDTSVector(x.(string))
 			},
 		)
+	case types.PGVectorFamily:
+		setNullable(
+			avroSchemaString,
```
Comment (jordanlewis) [inline pkg/ccl/changefeedccl/avro.go:628]: I deliberately removed this code, though I probably should have commented as such, on advice from @asg0451. I assume it'll be more annoying to migrate to a new Avro format later, and stringifying the vectors is probably too inefficient. I think it would be better to leave this unimplemented, or alternatively implement it as a nicely packed binary number array.

**Review by yuzefovich — COMMENTED** [review]
TFTRs!

bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/126833#-:-O1JjO9w7stOlDIy0Wt5:b-tlx7ko)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @asg0451 and @DrewKimball)

___
*[`pkg/ccl/changefeedccl/avro.go` line 628 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/126833#gh-1669370330:-O1JjLFw7kGYghzBMG5b:bn0ii5p) ([raw file](https://github.com/cockroachdb/cockroach/blob/4be6d167d68775924e468b14a031a7ddb751b4d9/pkg/ccl/changefeedccl/avro.go#L628)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

I deliberately removed this code, though I probably should have commented as such, on advice from @asg0451. I assume it'll be more annoying to migrate to a new Avro format later, and stringifying the vectors is probably too inefficient. I think it would be better to leave this unimplemented, or alternatively implement it as a nicely packed binary number array.
</blockquote></details>

Ack, thanks. Removed the code and left a comment.

File: pkg/ccl/changefeedccl/avro.go (hunk 1 above)
Comment (asg0451) [reply pkg/ccl/changefeedccl/avro.go]: just curious, what will happen if a user creates a changeed on a table with a vector? will it fail to create? fail to run? silently ignore that column?

Comment (yuzefovich) [reply pkg/ccl/changefeedccl/avro.go]: I'm assuming that it'll be possible to create the changefeed, but then it'll fail with a terminal error when trying to encode the event into the appropriate format.

Comment (asg0451) [reply pkg/ccl/changefeedccl/avro.go]: can we test this assumption real quick? then we can ask @kathancox to document this known limitation.

Comment (yuzefovich) [reply pkg/ccl/changefeedccl/avro.go]: It's probably going to be easier for someone on CDC to try then for me. I tried doing something like
```sql
CREATE TABLE t (v VECTOR);
INSERT INTO t VALUES('[1]'), ('[2,3]');
CREATE CHANGEFEED FOR t INTO 'null://sink' WITH format='avro';
```
but I'm hitting some errors. I'll leave it up to you @asg0451 to try it and file an issue if necessary.
