### PR TITLE
kvserver,kvnemesis: dump raft logs on failure

### LINKED ISSUE #146043: kv/kvserver: TestMergeReplicatesLocks failed
kv/kvserver.TestMergeReplicatesLocks [failed](https://tanzanite.cluster.engflow.com/invocations/default/1ee40d3b-a12c-462c-9c19-191f01298b26?testReportRun=2&testReportShard=41&testReportAttempt=1#targets-Ly9wa2cva3Yva3ZzZXJ2ZXI6a3ZzZXJ2ZXJfdGVzdA==) on release-25.2.0-rc @ [545da2936c70fdecb9bbbd652aa4bd90b8d26dad](https://github.com/cockroachdb/cockroach/commits/545da2936c70fdecb9bbbd652aa4bd90b8d26dad):

```
=== RUN   TestMergeReplicatesLocks
    test_log_scope.go:165: test logs captured to: outputs.zip/logTestMergeReplicatesLocks2241698621
    test_log_scope.go:76: use -show-logs to present logs inline
    client_replica_test.go:6208: -- test log scope end --
test logs left over in: outputs.zip/logTestMergeReplicatesLocks2241698621
--- FAIL: TestMergeReplicatesLocks (74.13s)
=== RUN   TestMergeReplicatesLocks/rhs-lock
    client_replica_test.go:6159: txn1: lock acquired, waiting for txn2 cancellation
    client_replica_test.go:6171: txn2: tnx1 lock acquisition observed, starting txn
    client_replica_test.go:6192: merging ranges
    client_replica_test.go:6196: cancelling txn2
    client_replica_test.go:6161: txn1: done
    client_replica_test.go:6204: consistency failure: range 75 (/Table/Max) RANGE_CONSISTENT_STATS_INCORRECT:
        stats: {ContainsEstimates:0 LastUpdateNanos:1746267474019367549 LockAge:1 GCBytesAge:0 LiveBytes:25 LiveCount:1 KeyBytes:15 KeyCount:1 ValBytes:10 ValCount:1 IntentBytes:0 IntentCount:0 LockBytes:95 LockCount:1 RangeKeyCount:0 RangeKeyBytes:0 RangeValCount:0 RangeValBytes:0 SysBytes:590 SysCount:8 AbortSpanBytes:0}
        delta (stats-computed): {ContainsEstimates:0 LastUpdateNanos:1746267474019367549 LockAge:0 GCBytesAge:0 LiveBytes:0 LiveCount:0 KeyBytes:0 KeyCount:0 ValBytes:0 ValCount:0 IntentBytes:0 IntentCount:0 LockBytes:0 LockCount:0 RangeKeyCount:0 RangeKeyBytes:0 RangeValCount:0 RangeValBytes:0 SysBytes:-12 SysCount:0 AbortSpanBytes:0}
--- FAIL: TestMergeReplicatesLocks/rhs-lock (35.70s)
```

Parameters:
 - <code>attempt=1</code>
 - <code>race=true</code>
 - <code>run=2</code>
 - <code>shard=41</code>
<details><summary>Help</summary>
<p>

See also: [How To Investigate a Go Test Failure \(internal\)](https://cockroachlabs.atlassian.net/l/c/HgfXfJgM)
</p>
</details>
/cc @cockroachdb/kv-triage
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*TestMergeReplicatesLocks.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/bazci/githubpost/issues)

</sub>

### PR DESCRIPTION
**Pull request by tbg**
This helps diagnose failures such as #146043 and #143317.

```
$ go test [...]
somewhere.go:6207: dumping raft logs to [log-scope]/raftlog
```

```
$ ls [log-scope]/raftlog
r1.txt	r12.txt	r15.txt [...]
```

```
$ tail -n 10 r74.txt
****** index 25 ******
RaftCommand: proposer_lease_sequence:1 max_lease_index:20 closed_timestamp:<wall_time:1746450987106072000 > replicated_eval_result:<write_timestamp:<wall_time:1746450990105858000 > delta:<sys_bytes:147 > > logical_op_log:<>
Put: /Local/Lock/Local/Range/Table/72/RangeDescriptor 032e9bd313c26c4cb99422657288fdc2a8 (0x017a6b12016b12d000ff0172647363000100032e9bd313c26c4cb99422657288fdc2a812): 1746450990.105858000,0 txn={id=2e9bd313 key=/Local/Range/Table/72/RangeDescriptor iso=Serializable pri=0.00381679 epo=0 ts=1746450990.105858000,0 min=1746450990.105858000,0 seq=1} ts=1746450990.105858000,0 del=false klen=12 vlen=49 mergeTs=<nil> txnDidNotUpdateMeta=true
Put: 1746450990.105858000,0 /Local/Range/Table/72/RangeDescriptor (0x016b12d000017264736300183ca3ec22e38fd009): [/Table/72, /Table/Max)
	Raw:r74:/Table/{72-Max} [(n1,s1):1, (n2,s2):2, (n3,s3):3, next=4, gen=5]
****** index 26 ******
RaftCommand: proposer_lease_sequence:1 max_lease_index:21 closed_timestamp:<wall_time:1746450987106175000 > replicated_eval_result:<write_timestamp:<wall_time:1746450990105858000 > delta:<sys_bytes:175 sys_count:1 > > logical_op_log:<>
Put: /Local/Lock/Local/Range/Table/Max/RangeDescriptor 032e9bd313c26c4cb99422657288fdc2a8 (0x017a6b12016b12fa00ff0172647363000100032e9bd313c26c4cb99422657288fdc2a812): 1746450990.105858000,0 txn={id=2e9bd313 key=/Local/Range/Table/72/RangeDescriptor iso=Serializable pri=0.00381679 epo=0 ts=1746450990.105858000,0 min=1746450990.105858000,0 seq=2} ts=1746450990.105858000,0 del=false klen=12 vlen=66 mergeTs=<nil> txnDidNotUpdateMeta=true
Put: 1746450990.105858000,0 /Local/Range/Table/Max/RangeDescriptor (0x016b12fa00017264736300183ca3ec22e38fd009): [/Table/Max, /Max)
	Raw:r75:/{Table/Max-Max} [(n1,s1):1, (n2,s2):2, (n3,s3):3, next=4, gen=5, sticky=9223372036.854775807,2147483647]
```

Closes https://github.com/cockroachdb/cockroach/issues/146043

Epic: none

### CODE REVIEW

File: pkg/kv/kvserver/print/dump_raft_log.go [hunk 1]
```diff
@@ -0,0 +1,57 @@
...
+	ctx := context.Background()
+	put := func(format string, args ...interface{}) {
+		_, _ = fmt.Fprintf(w, format, args...)
+		_, _ = fmt.Fprintln(w)
+	}
+
+	return raftlog.Visit(ctx, reader, rangeID, 0, math.MaxUint64, func(ent raftpb.Entry) error {
+		put("****** index %d ******", ent.Index)
+		e, err := raftlog.NewEntry(ent)
+		defer e.Release()
```
Comment (stevendanna) [inline pkg/kv/kvserver/print/dump_raft_log.go:34]: Is this valid to release in the case of error?

File: pkg/kv/kvserver/print/dump_raft_log.go [hunk 2]
```diff
@@ -0,0 +1,57 @@
...
+		// struct recursively but while omitting zero values. This is the
+		// closest I got without putting in significant amounts of work (like
+		// adjusting dozens of gogoproto moretags or writing custom
+		// formatters).
+		put("RaftCommand: %+v", proto.CompactTextString(&e.Cmd))
+
+		s, err := DecodeWriteBatch(wb.GetData())
+		if err != nil {
+			put("%s", err)
+			// continue
```
Comment (stevendanna) [inline pkg/kv/kvserver/print/dump_raft_log.go:52]: Did you intend to return here?

File: pkg/kv/kvserver/client_replica_test.go [hunk 3]
```diff
@@ -6250,7 +6250,10 @@ func TestMergeDropsLocksIfLargerThanMax(t *testing.T) {
 
 func TestMergeReplicatesLocks(t *testing.T) {
 	defer leaktest.AfterTest(t)()
-	defer log.Scope(t).Close(t)
+	scope := log.Scope(t)
+	defer scope.Close(t)
+
+	skip.UnderDuress(t, "too slow for testrace")
```
Comment (stevendanna) [inline pkg/kv/kvserver/client_replica_test.go:6256]: I can try to follow up here. We can probably get away with a single-node test for this which will probably help a bit.

**Review by stevendanna — COMMENTED** [review]
Thanks for working on this! Just a few minor comments.

File: pkg/kv/kvserver/print/dump_raft_log.go (hunk 1 above)
Comment (tbg) [reply pkg/kv/kvserver/print/dump_raft_log.go:34]: No, good catch, fixed with next push.

File: pkg/kv/kvserver/print/dump_raft_log.go (hunk 2 above)
Comment (tbg) [reply pkg/kv/kvserver/print/dump_raft_log.go:52]: Yep, done

**Review by stevendanna — APPROVED** [review]

**Comment by tbg** [comment]
TFTR!

bors r+
