### PR TITLE
kvserver: check if a node is available before checking draining or de…

### LINKED ISSUE #66648: roachtest: replicagc-changed-peers/restart=true failed
roachtest.replicagc-changed-peers/restart=true [failed](https://teamcity.cockroachdb.com/viewLog.html?buildId=3098030&tab=buildLog) with [artifacts](https://teamcity.cockroachdb.com/viewLog.html?buildId=3098030&tab=artifacts#/replicagc-changed-peers/restart=true) on master @ [69308cce3bb7e660908cb3e2724eedd271ce5585](https://github.com/cockroachdb/cockroach/commits/69308cce3bb7e660908cb3e2724eedd271ce5585):

```
The test failed on branch=master, cloud=gce:
test artifacts and logs in: /home/agent/work/.go/src/github.com/cockroachdb/cockroach/artifacts/replicagc-changed-peers/restart=true/run_1
	replicagc.go:180,replicagc.go:82,replicagc.go:31,test_runner.go:757: replica count on n1 didn't drop to zero: 50

	cluster.go:1328,context.go:89,cluster.go:1317,test_runner.go:838: dead node detection: /home/agent/work/.go/src/github.com/cockroachdb/cockroach/bin/roachprod monitor teamcity-3098030-1624082979-35-n6cpu4 --oneshot --ignore-empty-nodes: exit status 1 3: dead (exit status 137)
		1: 13025
		4: 12814
		2: 12138
		5: 11619
		6: 12409
		Error: UNCLASSIFIED_PROBLEM: 3: dead (exit status 137)
		(1) UNCLASSIFIED_PROBLEM
		Wraps: (2) attached stack trace
		  -- stack trace:
		  | main.glob..func14
		  | 	/home/agent/work/.go/src/github.com/cockroachdb/cockroach/pkg/cmd/roachprod/main.go:1154
		  | main.wrap.func1
		  | 	/home/agent/work/.go/src/github.com/cockroachdb/cockroach/pkg/cmd/roachprod/main.go:276
		  | github.com/spf13/cobra.(*Command).execute
		  | 	/home/agent/work/.go/src/github.com/cockroachdb/cockroach/vendor/github.com/spf13/cobra/command.go:856
		  | github.com/spf13/cobra.(*Command).ExecuteC
		  | 	/home/agent/work/.go/src/github.com/cockroachdb/cockroach/vendor/github.com/spf13/cobra/command.go:960
		  | github.com/spf13/cobra.(*Command).Execute
		  | 	/home/agent/work/.go/src/github.com/cockroachdb/cockroach/vendor/github.com/spf13/cobra/command.go:897
		  | main.main
		  | 	/home/agent/work/.go/src/github.com/cockroachdb/cockroach/pkg/cmd/roachprod/main.go:2051
		  | runtime.main
		  | 	/usr/local/go/src/runtime/proc.go:204
		  | runtime.goexit
		  | 	/usr/local/go/src/runtime/asm_amd64.s:1374
		Wraps: (3) 3: dead (exit status 137)
		Error types: (1) errors.Unclassified (2) *withstack.withStack (3) *errutil.leafError
```
<details><summary>Reproduce</summary>
<p>
<p>To reproduce, try:

```bash
# From https://go.crdb.dev/p/roachstress, perhaps edited lightly.
caffeinate ./roachstress.sh replicagc-changed-peers/restart=true
```
</p>
</p>
</details>
/cc @cockroachdb/kv
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*replicagc-changed-peers/restart=true.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)
</sub>

### PR DESCRIPTION
**Pull request by lunevalex**
…commissioning status

Fixes #66648

Check if a node is alive before checking if it's draining or decommissioning.
We only want to check those flags if the node is up and heartbeating, because we
don't want to accidentally treat that node as live and move a lease to it. If
a node is draining or decommissioning and it's liveness has expired we will consider it
unavailable. 

Release note (bug fix): Previously an unavailable node that started draining or
decommissioning would be treated as live and thus could receive a lease transfer,
leading to the range becoming unavailable.

### CODE REVIEW

File: pkg/kv/kvserver/store_pool.go [hunk 1]
```diff
@@ -174,15 +174,18 @@ func LivenessStatus(
...
+		if !l.Membership.Active() {
+			return livenesspb.NodeLivenessStatus_DECOMMISSIONING
+		}
+		if l.Draining {
+			return livenesspb.NodeLivenessStatus_DRAINING
+		}
 		return livenesspb.NodeLivenessStatus_LIVE
 	}
+	if !l.Membership.Active() {
+		return livenesspb.NodeLivenessStatus_DECOMMISSIONED
```
Comment (tbg) [inline pkg/kv/kvserver/store_pool.go:187]: This seems incorrect, I think this should be UNAVAILABLE as well.

Comment (lunevalex) [reply pkg/kv/kvserver/store_pool.go:187]: I went back and forth on that one, the reason I thought it should be decommissioned was that a node would go Decommissioning -> Decommissioned (Unavailable) -> Decommissioned (Dead) this way, if its shutdown in the middle of the process. No strong feelings on this, so will change it.

Comment (tbg) [reply pkg/kv/kvserver/store_pool.go]: The reason I think this isn't quite right is that while a node is decommissioning, it typically still has data and so when it goes down that is a problem. A `decommissioned` node is one where you don't care any more whether it's down.

Thanks for making the change.

**Review by tbg — APPROVED** [review]
LGTM though the commit/PR message still refers to the old behavior of considering a non-live non-dead decommissioning node "decomissioned", but such a node is now regarded as "unavailable".

**Comment by lunevalex** [comment]
bors r=tbg
