### PR TITLE
sqlmigrations: move namespace migration post-finalization

### LINKED ISSUE #49090: sql: tables created in mixed 19.2-20.1 state after namespace migration is run won't get moved to namespace2
## Problem

When the first 20.1 node joins a 19.2 cluster, the `migrateSystemNamespace` migration will run, which copies all entries from descriptor 2 (the old `system.namespace`) to descriptor 30 (`system.namespace2`).

In a mixed-version state, new tables and databases are added only to descriptor 2 (`system.namespace`).

Since `migrateSystemNamespace` only gets run once, those new tables and databases from the mixed-version state will never automatically get upgraded to the 20.1 format.

## Consequences:

There are no known user-visible errors from this issue.

1. We can't get rid of the fallback namespace table logic until 20.2.
2. Tables that were created in the mixed-version state will always require 2 namespace lookups, since the first one will fail.

## Resolution:

1. We should add another migration that runs `migrateSystemNamespace` in 20.1.1, so that customers upgrading from 20.1.0 to 20.1.1 will repair their namespace2 (descriptor 30) table.
2. We should add an invocation of `migrateSystemNamespace` to the finalized-version hook in 20.1.1 so that customers upgrading from 19.2.x to 20.1.1 will not have this problem.

## Note:

Because of this problem, we can't remove the fallback logic for searching system.namespace (descriptor 2) until 21.1. (cc @nvanbenschoten, since I think you were looking at removing something like this recently).

### LINKED ISSUE #49092: sql: dropping tables or databases on the 19.2 binary in a 19.2-20.1 mixed cluster orphans system.namespace2 entries
## Repro:

1. Start up a 19.2 cluster.
2. Open a SQL shell to one of the nodes. Run `CREATE DATABASE foo`.
3. Replace one of the 19.2 nodes with a 20.1 node.
4. Run `DROP DATABASE foo` on the first SQL shell (running 19.2).
5. Open a SQL shell to the 20.1 node. Run `SHOW DATABASES`.

```
root@localhost:26258/defaultdb> show databases;
ERROR: internal error: "" is not a database
SQLSTATE: XX000
DETAIL: stack trace:
/go/src/github.com/cockroachdb/cockroach/pkg/sql/table.go:788: getDatabaseDescriptorsFromIDs()
/go/src/github.com/cockroachdb/cockroach/pkg/sql/table.go:745: getAllDatabaseDescriptors()
/go/src/github.com/cockroachdb/cockroach/pkg/sql/information_schema.go:1475: forEachDatabaseDesc()
/go/src/github.com/cockroachdb/cockroach/pkg/sql/information_schema.go:967: func71()
/go/src/github.com/cockroachdb/cockroach/pkg/sql/virtual_schema.go:274: func1()
/go/src/github.com/cockroachdb/cockroach/pkg/sql/opt_exec_factory.go:143: func1()
/go/src/github.com/cockroachdb/cockroach/pkg/sql/delayed.go:48: startExec()
/go/src/github.com/cockroachdb/cockroach/pkg/sql/plan.go:395: func2()
/go/src/github.com/cockroachdb/cockroach/pkg/sql/walk.go:144: func1()
/go/src/github.com/cockroachdb/cockroach/pkg/sql/walk.go:721: visitInternal()
/go/src/github.com/cockroachdb/cockroach/pkg/sql/walk.go:111: visit()
/go/src/github.com/cockroachdb/cockroach/pkg/sql/walk.go:75: walkPlan()
/go/src/github.com/cockroachdb/cockroach/pkg/sql/plan.go:398: startExec()
/go/src/github.com/cockroachdb/cockroach/pkg/sql/plan_node_to_row_source.go:117: Start()
/go/src/github.com/cockroachdb/cockroach/pkg/sql/rowexec/distinct.go:153: Start()
/go/src/github.com/cockroachdb/cockroach/pkg/sql/rowexec/sorter.go:283: Start()
/go/src/github.com/cockroachdb/cockroach/pkg/sql/execinfra/processorsbase.go:748: Run()
/go/src/github.com/cockroachdb/cockroach/pkg/sql/flowinfra/flow.go:370: Run()
/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsql_running.go:405: Run()
/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsql_running.go:1019: PlanAndRun()
/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:883: execWithDistSQLEngine()
/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:776: dispatchToExecutionEngine()
/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:481: execStmtInOpenState()
/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:96: execStmt()
/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:1368: execCmd()
/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:1297: run()
/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:476: ServeConn()
/go/src/github.com/cockroachdb/cockroach/pkg/sql/pgwire/conn.go:590: func1()
/usr/local/go/src/runtime/asm_amd64.s:1357: goexit()
```

The cause symptom of this error is an orphaned row in the system.descriptor2 table containing the `foo` database.

If you were to do this same process with a table instead of a database, you'd get an orphaned table row that causes the following symptom:

```
root@:26257/defaultdb> create table a (a int);
ERROR: relation "a" already exists
SQLSTATE: 42P07
root@:26257/defaultdb> drop table a;
ERROR: relation "a" does not exist
SQLSTATE: 42P01
```

## Cause

When the first 20.1 node joins the cluster, it copies all `system.namespace` (descriptor 2) entries to `system.namespace2` (descriptor 30).

When a 19.2 node drops a table or database, it deletes the corresponding row from `system.namespace`, but not from `system.namespace2`, since it doesn't know that `system.namespace2` exists.

The 20.1 node will then experience an orphaned namespace entry when it searches for something.

Note that this sequence is only possible if the `DROP` occurs on the 19.2 binary. It cannot occur on the 20.1 binary before the upgrade is finalized, and once the upgrade is finalized, only 20.1 nodes can be in the cluster, and 20.1 nodes always delete from both the `namespace` and `namespace2` tables during drops.

## Mitigation for users that had this problem

We have to advise users to manually remove the orphaned rows from `system.namespace`.

## Prevention for 20.1.1+

We need to ideally move this migration so that it only happens post-finalization, so that dropping objects on the 19.2 binary in a mixed state doesn't orphan anything in the new namespace table.

If we made this change for 20.1.1, along with #49090, users who migrate from 19.2 to 20.1.1+ would have no chance of running into this issue.

### PR DESCRIPTION
**Pull request by jordanlewis**
Fixes #49090.
Fixes #49092.

This commit removes the namespace migration, and replaces it with a
post-finalization async migration in the style of the schema change jobs
migration that only runs after the 20.1 version bit is flipped.

This change prevents an issue with dropping a table or database from a
19.2 node after the migration ran. That operation would orphan an entry in
system.namespace2, since the migration would have moved the entry to
system.namespace2 already, but the drop would only remove the entry
from system.namespace.

The migration additionally only moves entries from system.namespace to
system.namespace2 if there isn't already an entry in system.namespace2
for that descriptor id. This should be safe and idempotent. Here are
some things to note:

1. No nodes write to namespace2 until 20.1 is finalized.
2. 20.1 nodes always delete from both namespace and namespace2.

In the happy path, there are no entries in system.namespace2 when the
migration runs. All entries are copied in.

If, after finalization but before the migration, a node:

- Adds a table: the new entry will go only to system.namespace2, and
  there will be no system.namespace entry to copy, so no problem
- Deletes a table: the entry will be removed from system.namespace2 and
  system.namespace, so there will be no system.namespace entry to copy.
- Renames a table: the old entry will be removed from system.namespace
  and system.namespce2, and the new entry will be added to
  system.namespace2, so there will be no system.namespace entry to copy.
- Truncates a table: same as rename.

Note this is all the same for views, sequences, and databases, but
databases, views, and sequences don't support truncate.

If this migration is run a second time, it's impossible to find any
entries in system.namespace that aren't also in system.namespace2,
because 20.1 nodes always delete from both tables when they delete, so
the migration will do nothing.

----

One complication is that, due to the issue explained at the top of this
commit, there can exist orphaned entries in system.descriptor2 that are
not in system.descriptor at the time that this migration runs. This
migration makes no effort to clean these orphans up, but it doesn't
affect the run of the migration.

Release note (bug fix): Prevent namespace orphans (manifesting as
`database "" not found` errors) when migrating from 19.2.

### CODE REVIEW

**Comment by jordanlewis** [comment]
Note: This needs tests. Ideally, I'd test each of the scenarios I went through in the commit message. I haven't written the tests yet. I'm pushing up early for review and for CI.

Most importantly, we need to be completely sure that this migration is idempotent and correct. The crux of it is checking the following assumption:

Once 20.1 is finalized, is it always safe to blindly copy all entries from `system.namespace` to `system.namespace2`, such that an entry is only copied if its descriptor id isn't present in any entry in `system.namespace2`?

The way we do that is by running the query:

```
SELECT "parentID", name, id FROM [2 AS namespace]
WHERE id NOT IN (SELECT id FROM [30 AS namespace2])
```

and writing upgraded entries into namespace2 for every entry that's returned by this query.

File: pkg/sqlmigrations/migrations.go [hunk 1]
```diff
@@ -765,6 +772,80 @@ func (m *Manager) StartSchemaChangeJobMigration(ctx context.Context) error {
...
+		for migRetry := retry.Start(migrationRetryOpts); migRetry.Next(); {
+			migrateCtx, _ := m.stopper.WithCancelOnQuiesce(context.Background())
+			migrateCtx = logtags.AddTag(migrateCtx, "system-namespace-migration", nil)
+			if err := migrateSystemNamespace(migrateCtx, r); err != nil {
+				log.Errorf(ctx, "error attempting running system.namespace migration, will retry: %s %s", err.Error(),
+					startTime)
+				continue
+			}
+			log.Infof(ctx, "system.namespace migration completed")
+			if err := m.db.Put(ctx, systemNamespaceMigrationKey, startTime); err != nil {
```
Comment (rohany) [inline pkg/sqlmigrations/migrations.go:837]: So the argument we don't need to write this key as part of the migration txn is that the migration is idempotent, so it doesn't matter how many times it runs?

File: pkg/sqlmigrations/migrations.go [hunk 2]
```diff
@@ -1405,56 +1486,68 @@ func addCreateRoleToAdminAndRoot(ctx context.Context, r runner) error {
...
-			tableKey := sqlbase.NewTableKey(parentID, keys.PublicSchemaID, name)
-			if err := r.db.Put(ctx, tableKey.Key(r.codec), id); err != nil {
-				return err
+	return r.db.Txn(ctx, func(ctx context.Context, txn *kv.Txn) error {
+		// Fetch all entries that are not present in the new namespace table. Each
+		// of these entries will be copied to the new table.
+		//
+		// Note that we are very careful to always delete from both tables in 20.1,
+		// so there's no possibility that we'll be overwriting a deleted table that
+		// existed in the old table and the new table but was deleted from only the
```
Comment (rohany) [inline pkg/sqlmigrations/migrations.go:1504]: [nit] can you say namespace here instead of table?

**Review by rohany — COMMENTED** [review]
Yeah, I buy the argument that we can safely move everything that isn't already present.

File: pkg/sqlmigrations/migrations.go (hunk 1 above)
Comment (jordanlewis) [reply pkg/sqlmigrations/migrations.go:837]: The problem is that different nodes can become 20.1 at different times, I think... I'm not actually sure if there's more problems here. I copied this strategy from the async jobs migration, which is right above this one in the file.

**Review by thoszhang — COMMENTED** [review]
Yeah, this looks reasonable to me so far. I think the main thing now is the testing.

> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/49099#-:-M7NsxSp-ebyDf_6-paz:b9x3ebg)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jordanlewis and @rohany)

___
*[pkg/sqlmigrations/migrations.go, line 837 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/49099#-M7Ld-1Nl5J9YdSJAs9Q-r1-837:-M7NrPe421xVLDtjxD5H:b2owf6i) ([raw file](https://github.com/cockroachdb/cockroach/blob/1d3538c14a7e258f5888123145dc54eca61f0194/pkg/sqlmigrations/migrations.go#L837)):*
> The problem is that different nodes can become 20.1 at different times

I don't follow, could you elaborate? I think using that key to ensure the migration gets run exactly once is not unreasonable.

**Review by jordanlewis — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/49099)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jordanlewis and @rohany)

___
*[pkg/sqlmigrations/migrations.go, line 837 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/49099#-M7Ld-1Nl5J9YdSJAs9Q-r1-837:-M7NtCRq4zPX_u50dtUX:b-neihay) ([raw file](https://github.com/cockroachdb/cockroach/blob/1d3538c14a7e258f5888123145dc54eca61f0194/pkg/sqlmigrations/migrations.go#L837)):*
<details><summary><i>Previously, lucy-zhang (Lucy Zhang) wrote…</i></summary><blockquote>

> The problem is that different nodes can become 20.1 at different times

I don't follow, could you elaborate? I think using that key to ensure the migration gets run exactly once is not unreasonable.
</blockquote></details>

Okay, is the following sequence possible? Terminology: "finalization signal" means that, after it's received, all checks on a node for finalization return true.

1. upgrade finishes in a 3 node cluster
2. Node A receives its finalization signal and begins running the migration
3. Node B creates a table, writing an entry into the old namespace table
3. Node B receives its finalization signal

If so, Node B could leave orphaned rows in the old namespace table (note that this won't cause user-visible problems due to the fallback logic) unless it re-runs the migration when it gets finalized.

Is there a signal that we can listen to that means that all nodes have received their finalization signals?

**Review by thoszhang — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/49099)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jordanlewis and @rohany)

___
*[pkg/sqlmigrations/migrations.go, line 837 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/49099#-M7Ld-1Nl5J9YdSJAs9Q-r1-837:-M7NvwH69gMbZft8TML_:b-r0lfpm) ([raw file](https://github.com/cockroachdb/cockroach/blob/1d3538c14a7e258f5888123145dc54eca61f0194/pkg/sqlmigrations/migrations.go#L837)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

Okay, is the following sequence possible? Terminology: "finalization signal" means that, after it's received, all checks on a node for finalization return true.

1. upgrade finishes in a 3 node cluster
2. Node A receives its finalization signal and begins running the migration
3. Node B creates a table, writing an entry into the old namespace table
3. Node B receives its finalization signal

If so, Node B could leave orphaned rows in the old namespace table (note that this won't cause user-visible problems due to the fallback logic) unless it re-runs the migration when it gets finalized.

Is there a signal that we can listen to that means that all nodes have received their finalization signals?
</blockquote></details>

Yeah, I think that is possible, but it seems okay for basically the reason you stated. But wouldn't that still happen even if we wrote to the key indicating completion of the migration in a second transaction?

**Review by jordanlewis — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/49099)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jordanlewis and @rohany)

___
*[pkg/sqlmigrations/migrations.go, line 837 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/49099#-M7Ld-1Nl5J9YdSJAs9Q-r1-837:-M7OAcde88YggbaV76Q-:bn8e105) ([raw file](https://github.com/cockroachdb/cockroach/blob/1d3538c14a7e258f5888123145dc54eca61f0194/pkg/sqlmigrations/migrations.go#L837)):*
<details><summary><i>Previously, lucy-zhang (Lucy Zhang) wrote…</i></summary><blockquote>

Yeah, I think that is possible, but it seems okay for basically the reason you stated. But wouldn't that still happen even if we wrote to the key indicating completion of the migration in a second transaction?
</blockquote></details>

Yeah, good point.

Is there any sane way for us to make sure that there are no straggling entries before 20.2 (I know that, because of 20.1.0, we'll have to do a re-cleanup in 20.2 anyway, but it would be nicer to not have any stragglers.)?

Maybe it would be possible if you had a migration key per node id or something. But maybe this is just too complicated to try to do.

**Review by thoszhang — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/49099)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jordanlewis and @rohany)

___
*[pkg/sqlmigrations/migrations.go, line 837 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/49099#-M7Ld-1Nl5J9YdSJAs9Q-r1-837:-M7OCAItCYeNB51W2-ob:bg9o5l) ([raw file](https://github.com/cockroachdb/cockroach/blob/1d3538c14a7e258f5888123145dc54eca61f0194/pkg/sqlmigrations/migrations.go#L837)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

Yeah, good point.

Is there any sane way for us to make sure that there are no straggling entries before 20.2 (I know that, because of 20.1.0, we'll have to do a re-cleanup in 20.2 anyway, but it would be nicer to not have any stragglers.)?

Maybe it would be possible if you had a migration key per node id or something. But maybe this is just too complicated to try to do.
</blockquote></details>

Yeah, I don't know of any way to do this. It is annoying but seems like something we can live with.

**Review by irfansharif — COMMENTED** [review]
> in the style of the schema change jobs migration that only after the 20.1 version bit is flipped.

Missing words in the commit message, I think.

> but the drop wouldn't only remove the entry from system.namespace.

Is this right? Shouldn't it be "would only remove from `system.namespace`"?

Skimming through what's here (as a non-sql person), it checks out.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/49099#-:-M7O61rj-rau0s09MprB:b-1ugls3)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jordanlewis and @rohany)

___
*[pkg/sqlmigrations/migrations.go, line 286 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/49099#-M7OB8pq3L_Sq9XCUxGs:-M7OB8pq3L_Sq9XCUxGt:bimz2y9) ([raw file](https://github.com/cockroachdb/cockroach/blob/1d3538c14a7e258f5888123145dc54eca61f0194/pkg/sqlmigrations/migrations.go#L286)):*
> ```Go
> 	},
> 	{
> 		// Introduced in v20.1. Replaced in v20.1.1 and 20.2 by the StartSystemNamespaceMigration
> ```

s/Introduced in v20.1/Introduced in v20.1.0
s/20.2/v20.2

**Review by jordanlewis — COMMENTED** [review]
Fixed the commit message. Added a roachtest that fails before my patch. I still want to add more things to the roachtest.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/49099#-:-M7OEcSt9lPEFWCsCDsy:b-lqofz7)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @irfansharif, @lucy-zhang, and @rohany)

___
*[pkg/sqlmigrations/migrations.go, line 286 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/49099#-M7OB8pq3L_Sq9XCUxGs:-M7OEbkU-vcok2E_72JF:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/1d3538c14a7e258f5888123145dc54eca61f0194/pkg/sqlmigrations/migrations.go#L286)):*
<details><summary><i>Previously, irfansharif (irfan sharif) wrote…</i></summary><blockquote>

s/Introduced in v20.1/Introduced in v20.1.0
s/20.2/v20.2
</blockquote></details>

Done.
___
*[pkg/sqlmigrations/migrations.go, line 837 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/49099#-M7Ld-1Nl5J9YdSJAs9Q-r1-837:-M7OEYCtAU9PpsLl5Ye6:b-42phfz) ([raw file](https://github.com/cockroachdb/cockroach/blob/1d3538c14a7e258f5888123145dc54eca61f0194/pkg/sqlmigrations/migrations.go#L837)):*
<details><summary><i>Previously, lucy-zhang (Lucy Zhang) wrote…</i></summary><blockquote>

Yeah, I don't know of any way to do this. It is annoying but seems like something we can live with.
</blockquote></details>

Ok, I've moved the key to get written in the same txn.
___
*[pkg/sqlmigrations/migrations.go, line 1504 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/49099#-M7Ld-1Nl5J9YdSJAs9Q-r1-1504:-M7OEas-16xn0nU9ZbB8:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/1d3538c14a7e258f5888123145dc54eca61f0194/pkg/sqlmigrations/migrations.go#L1504)):*
<details><summary><i>Previously, rohany (Rohan Yadav) wrote…</i></summary><blockquote>

[nit] can you say namespace here instead of table?
</blockquote></details>

Done.

**Review by thoszhang — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/49099)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @irfansharif, @lucy-zhang, and @rohany)

___
*[pkg/sqlmigrations/migrations.go, line 837 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/49099#-M7Ld-1Nl5J9YdSJAs9Q-r1-837:-M7OF950-veF2RgNLMJ8:bv3qvl0) ([raw file](https://github.com/cockroachdb/cockroach/blob/1d3538c14a7e258f5888123145dc54eca61f0194/pkg/sqlmigrations/migrations.go#L837)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

Ok, I've moved the key to get written in the same txn.
</blockquote></details>

To get exactly-once (well, at-most-once) behavior, shouldn't we also read the value inside the transaction again as well (or use CPut)?

**Review by jordanlewis — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/49099)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @irfansharif, @lucy-zhang, and @rohany)

___
*[pkg/sqlmigrations/migrations.go, line 837 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/49099#-M7Ld-1Nl5J9YdSJAs9Q-r1-837:-M7OGNNYEiv48WEgxBel:b-z0yvzj) ([raw file](https://github.com/cockroachdb/cockroach/blob/1d3538c14a7e258f5888123145dc54eca61f0194/pkg/sqlmigrations/migrations.go#L837)):*
<details><summary><i>Previously, lucy-zhang (Lucy Zhang) wrote…</i></summary><blockquote>

To get exactly-once (well, at-most-once) behavior, shouldn't we also read the value inside the transaction again as well (or use CPut)?
</blockquote></details>

Yeah, good point. I've added another check for whether the migration key exists within the transaction.

**Review by jordanlewis — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/49099)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @irfansharif, @lucy-zhang, and @rohany)

___
*[pkg/sql/truncate.go, line 201 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/49099#-M7OItFp4z376K9DrNvb:-M7OItFp4z376K9DrNvc:bapgjig) ([raw file](https://github.com/cockroachdb/cockroach/blob/ab9462fcc1d6e0a9aac18a901f1fc6747e73311b/pkg/sql/truncate.go#L201)):*
> ```Go
> 
> 	// Remove the old namespace entry.
> 	if err := sqlbase.RemoveObjectNamespaceEntry(
> ```

Note: This changes the TRUNCATE operation to use Del instead of CPut to delete the old namespace entries. It's important because we must guarantee that deleting namespace entries deletes from both `namespace` and `namespace2` in 20.1.

We need to make sure that this is correct.

**Review by ajwerner — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/49099)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @irfansharif, @jordanlewis, @lucy-zhang, and @rohany)

___
*[pkg/sqlmigrations/migrations.go, line 837 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/49099#-M7Ld-1Nl5J9YdSJAs9Q-r1-837:-M7OJG2t3iG2y-lQGkVp:bqphd2y) ([raw file](https://github.com/cockroachdb/cockroach/blob/1d3538c14a7e258f5888123145dc54eca61f0194/pkg/sqlmigrations/migrations.go#L837)):*
>Yeah, I don't know of any way to do this. It is annoying but seems like something we can live with.

How do you envision living with it? Keeping a sqlmigration that runs in 20.2?

---

On a different meta-point I'm confused as to why we're doing this as two transactions. We don't get any isolation here. The outer transaction may get aborted and not find out until the inner one runs to completion, which I guess is fine (I think?) but then begs the question, why is the inner work done as a single transaction? 

Having the migration as a single transaction that issues put requests per entry risks running into problems if there are tons and tons of entries in namespace. If we're cool with the migration itself being one transaction, why wouldn't we just also do the observing and writing of the migration key also in that transaction? Furthermore, if we lay down the intent on the migration key prior to doing any migration work, we will know that there was mutual exclusion if we commit.

So, here's how I see the options:

1) Do everything in a single transaction (not two). First read the key, then put down an intent on it, then run the migration. If it finishes, awesome! This has risks if that transaction get gigantic.

2) Coordinate out-of-band by creating a lease to avoid contention and split the migration into batches. The reason for the lease is really just for contention avoidance anyway given the theoretical idempotence.


----

None of this deals with the stragglers thing. One option to try to ensure that every node sees the version upgrade which is a little crazy would be to touch write the version on every table and wait for all of the table versions to get adopted but that's a terrible idea... 

Another option is to wait for every lease in the lease table to have a start time after you saw the finalization. That'll probably just be another minute. 

To make this idea more concrete: 

1) Note the timestamp when you saw the finalization
2) Wait for every lease in `system.lease` time to be after that
   We don't have the actual start time but we have the expiration and the duration and we can add a clock uncertainty for good measure.
3) Run the migration
___
*[pkg/sqlmigrations/migrations.go, line 782 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/49099#-M7OIZy-0FDSo4MLZKwB:-M7OIZy-0FDSo4MLZKwC:b-duo7j4) ([raw file](https://github.com/cockroachdb/cockroach/blob/ab9462fcc1d6e0a9aac18a901f1fc6747e73311b/pkg/sqlmigrations/migrations.go#L782)):*
> ```Go
> func (m *Manager) StartSystemNamespaceMigration(ctx context.Context) error {
> 	return m.stopper.RunAsyncTask(ctx, "run-system-namespace-migration", func(ctx context.Context) {
> 		log.Info(ctx, "starting wait for upgrade finalization before system.namespace migration")
> ```

If I were feeling nitpicky I'd ask you to refactor this to:

```
helper for wait for version
```

___
*[pkg/sqlmigrations/migrations.go, line 829 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/49099#-M7OIhpFC2heB0PiMFA-:-M7OIhpG3asjyFPPnsoZ:b-azauym) ([raw file](https://github.com/cockroachdb/cockroach/blob/ab9462fcc1d6e0a9aac18a901f1fc6747e73311b/pkg/sqlmigrations/migrations.go#L829)):*
> ```Go
> 		startTime := timeutil.Now().String()
> 		for migRetry := retry.Start(migrationRetryOpts); migRetry.Next(); {
> 			migrateCtx, _ := m.stopper.WithCancelOnQuiesce(context.Background())
> ```

This is a memory leak, albeit a slow one, because we store these contexts in a map. How about we pull the body of this for loop into a helper and construct the context inside that helper and defer the `cancel` returned from this (which cleans up the map state).

**Review by thoszhang — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/49099)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @irfansharif, @jordanlewis, @lucy-zhang, and @rohany)

___
*[pkg/sqlmigrations/migrations.go, line 837 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/49099#-M7Ld-1Nl5J9YdSJAs9Q-r1-837:-M7ONg2i03XLnQhGqwQk:b-qj5nix) ([raw file](https://github.com/cockroachdb/cockroach/blob/1d3538c14a7e258f5888123145dc54eca61f0194/pkg/sqlmigrations/migrations.go#L837)):*
> How do you envision living with it? Keeping a sqlmigration that runs in 20.2?

Yeah, that's what I was thinking. We'll have to do this anyway, since we have no guarantee of the async migration actually completing before we upgrade to 20.2.

I'm okay with the lease timestamp idea, but I just don't know how important it is that we guarantee that there are no stragglers. I guess it might be a useful guarantee to have when we work on this in the future (either in debugging or writing the 20.1 -> 20.2 migration).

**Review by ajwerner — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/49099)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @irfansharif, @jordanlewis, @lucy-zhang, and @rohany)

___
*[pkg/sqlmigrations/migrations.go, line 837 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/49099#-M7Ld-1Nl5J9YdSJAs9Q-r1-837:-M7ON_zn42HPIJZuflVC:b-h4aig7) ([raw file](https://github.com/cockroachdb/cockroach/blob/1d3538c14a7e258f5888123145dc54eca61f0194/pkg/sqlmigrations/migrations.go#L837)):*
<details><summary><i>Previously, lucy-zhang (Lucy Zhang) wrote…</i></summary><blockquote>

> How do you envision living with it? Keeping a sqlmigration that runs in 20.2?

Yeah, that's what I was thinking. We'll have to do this anyway, since we have no guarantee of the async migration actually completing before we upgrade to 20.2.

I'm okay with the lease timestamp idea, but I just don't know how important it is that we guarantee that there are no stragglers. I guess it might be a useful guarantee to have when we work on this in the future (either in debugging or writing the 20.1 -> 20.2 migration).
</blockquote></details>

The fact that this migration is idempotent is a really wonderful thing. I think the way I'd do it is to wait out the interval by leaning on the table lease system as noted at the end there, maybe even waiting out two lease intervals (though I think just one will do given the way table lease expirations interact with transaction deadlines). 

Then in the migration loop, do the  actual migration in batches. You don't need to check the key because if you found a table to migrate, then you know that not all the tables have been migrated but it might be a good idea to cput delete the key in each batch just to avoid contention. Then just write the key at the end in a separate transaction when you find no tables left to be migrated.

**Review by jordanlewis — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/49099)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @irfansharif, @lucy-zhang, and @rohany)

___
*[pkg/sqlmigrations/migrations.go, line 837 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/49099#-M7Ld-1Nl5J9YdSJAs9Q-r1-837:-M7TBTSX5LBo75cag5XQ:b-dqmzdg) ([raw file](https://github.com/cockroachdb/cockroach/blob/1d3538c14a7e258f5888123145dc54eca61f0194/pkg/sqlmigrations/migrations.go#L837)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

The fact that this migration is idempotent is a really wonderful thing. I think the way I'd do it is to wait out the interval by leaning on the table lease system as noted at the end there, maybe even waiting out two lease intervals (though I think just one will do given the way table lease expirations interact with transaction deadlines). 

Then in the migration loop, do the  actual migration in batches. You don't need to check the key because if you found a table to migrate, then you know that not all the tables have been migrated but it might be a good idea to cput delete the key in each batch just to avoid contention. Then just write the key at the end in a separate transaction when you find no tables left to be migrated. 
</blockquote></details>

Is there a performant way to check all leases, or do you have to scan the whole system.lease table on a timer or something like that?

I agree with Lucy though that there isn't any critical need to get this perfect, because of people who could theoretically go 19.2->20.1.0->20.2 - we'll have to have a re-migration in that version anyway.

Is there a really good reason to do this in batches? I hear your argument about contention, but does it really matter? And I'm concerned about tricky effects - there could be more than one node performing this migration at the same time, so I think you have to do the Put of key x in the same transaction as one in which you discovered that key x is present in namespace but not in namespace2. So I think each batch would have to do the diff query anyway, which has to read all of both sides anyway because the table isn't keyed on id...
___
*[pkg/sqlmigrations/migrations.go, line 782 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/49099#-M7OIZy-0FDSo4MLZKwB:-M7TAVO6E-KjTquKshWT:b-hf8bdg) ([raw file](https://github.com/cockroachdb/cockroach/blob/ab9462fcc1d6e0a9aac18a901f1fc6747e73311b/pkg/sqlmigrations/migrations.go#L782)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

If I were feeling nitpicky I'd ask you to refactor this to:

```
helper for wait for version

</blockquote></details>

Yeah... I'll skip this one if it's ok w/ you, it's not that much duplicated code and I feel like it's a sizable refactor of fairly scary code. But I appreciate the suggestion. If we make another one we'll refactor.
___
*[pkg/sqlmigrations/migrations.go, line 829 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/49099#-M7OIhpFC2heB0PiMFA-:-M7T9rEp6bzhfe0or_8g:b-ysw63x) ([raw file](https://github.com/cockroachdb/cockroach/blob/ab9462fcc1d6e0a9aac18a901f1fc6747e73311b/pkg/sqlmigrations/migrations.go#L829)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

This is a memory leak, albeit a slow one, because we store these contexts in a map. How about we pull the body of this for loop into a helper and construct the context inside that helper and defer the `cancel` returned from this (which cleans up the map state).
</blockquote></details>

Done, thanks. I also repalced this context.Background() with the passed in ctx, as I cargo culted this and I don't think it makes sense - this context doesn't live past the lifetime of the calling function, so we don't need to make a fresh one.


<!-- Sent from Reviewable.io -->

**Review by ajwerner — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/49099)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @irfansharif, @lucy-zhang, and @rohany)

___
*[pkg/sqlmigrations/migrations.go, line 837 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/49099#-M7Ld-1Nl5J9YdSJAs9Q-r1-837:-M7TMJ8S33qkySECH0yo:bacv8bx) ([raw file](https://github.com/cockroachdb/cockroach/blob/1d3538c14a7e258f5888123145dc54eca61f0194/pkg/sqlmigrations/migrations.go#L837)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

Is there a performant way to check all leases, or do you have to scan the whole system.lease table on a timer or something like that?

I agree with Lucy though that there isn't any critical need to get this perfect, because of people who could theoretically go 19.2->20.1.0->20.2 - we'll have to have a re-migration in that version anyway.

Is there a really good reason to do this in batches? I hear your argument about contention, but does it really matter? And I'm concerned about tricky effects - there could be more than one node performing this migration at the same time, so I think you have to do the Put of key x in the same transaction as one in which you discovered that key x is present in namespace but not in namespace2. So I think each batch would have to do the diff query anyway, which has to read all of both sides anyway because the table isn't keyed on id...
</blockquote></details>

The batches is a concern about the transaction being too large and then failing to commit. Not contention. Contention is easy to mitigate by laying down an intent at the beginning on a shared key. 

Imagine the namespace tables has hundreds of thousands or millions of entries. 

It should work but out of an abundance of caution I’d do batches of 1000 or so for most clusters it would just be one. 

As for the waiting for leases, I was just expecting a full table scan.

**Review by jordanlewis — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/49099)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @irfansharif, @lucy-zhang, and @rohany)

___
*[pkg/sqlmigrations/migrations.go, line 837 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/49099#-M7Ld-1Nl5J9YdSJAs9Q-r1-837:-M7Tjt4LBy7MNR2W0wQL:b4an2eb) ([raw file](https://github.com/cockroachdb/cockroach/blob/1d3538c14a7e258f5888123145dc54eca61f0194/pkg/sqlmigrations/migrations.go#L837)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

The batches is a concern about the transaction being too large and then failing to commit. Not contention. Contention is easy to mitigate by laying down an intent at the beginning on a shared key. 

Imagine the namespace tables has hundreds of thousands or millions of entries. 

It should work but out of an abundance of caution I’d do batches of 1000 or so for most clusters it would just be one. 

As for the waiting for leases, I was just expecting a full table scan. 
</blockquote></details>

I added the batching. I think it's a good idea.

As for waiting for leases, I admit I don't fully understand why it's important. Could you explain? Preferably, you could give an example that I could test that would fail to get a namespace entry moved unless we waited out the lease interval.

**Review by jordanlewis — COMMENTED** [review]
Pushed another version. I added more robustness to the test. It tests a bunch of operations in a real mixed version cluster. I added a testing cluster setting that can be set to prevent the migration, just for this roachtest. I also added a crdb_internal.completed_migrations() builtin that returns an array of all of the migration keys that have been written, a convenient testing helper.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/49099#-:-M7Tmnj_2YAU0f5r-B_A:b-p10cih)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @irfansharif, @lucy-zhang, and @rohany)

**Comment by ajwerner** [comment]
The waiting for the leases thing was about waiting for stragglers who might not yet know about the version being finalized and might be writing descriptors in the wrong way. I was trying to come up with ideas to deal with stragglers.

**Review by jordanlewis — COMMENTED** [review]
Yes, I understand that. I'm just missing how it would help the situation. Couldn't a node have no leases at all, the migration would run happily, but then that node get a rely delayed version finalization, and someone sneaks in to make a new table?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/49099#-:-M7TvspjEWtytNSLJVX1:blejgbs)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @irfansharif, @lucy-zhang, and @rohany)

**Comment by ajwerner** [comment]
> Yes, I understand that. I'm just missing how it would help the situation. Couldn't a node have no leases at all, the migration would run happily, but then that node get a rely delayed version finalization, and someone sneaks in to make a new table?
> 
> > _[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/49099#-:-M7TvspjEWtytNSLJVX1:blejgbs)_ status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @irfansharif, @lucy-zhang, and @rohany)

I suppose. Seems somewhat farfetched but I’m happy to concede that waiting out the leases is not a proof.

**Review by jordanlewis — COMMENTED** [review]
Is there an API we can poll for current cluster version on all servers? that would be an easy way to do it, and would guarantee that we're good, I think, unless a server could somehow rejoin the cluster later at an older version?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/49099#-:-M7UhMUW06ae1yiGHPlu:bcvadih)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @irfansharif, @lucy-zhang, and @rohany)

**Review by ajwerner — COMMENTED** [review]
No, this is part of the upcoming work to make the version upgrade multi-phase. 

You could try to work something up using some status RPCs but all of it has risks given that just because you know a node has the right view of the version in memory now, you don’t know whether an ongoing query will have already passed the version gate with the old version. 

I’m speculating that you could even read the cluster setting value out of gossip from a status rpc. If you could do that and then conservatively wait until all queries must have table leases after that then I’d feel pretty good. To be honest if you were to just sleep 5 minutes (schema lease duration) after it gets finalized and you ensure that the set of nodes is that same after the waiting I’d feel extremely good about the prospects that there were no stragglers but, it’s still not a proof. 

I’m making a hand-wavy argument about these schema leases but i think it stands. The main argument I have against this extremely conservative waiting approach is that it’s annoying for testing. If we’re not worried about stragglers then none of this commentary matters. 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/49099#-:-M7UhpXW60fpNfJIjEn_:bqh1z7q)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @irfansharif, @lucy-zhang, and @rohany)

**Review by jordanlewis — COMMENTED** [review]
Okay. In this case, let's just skip talking about stragglers so much, since we're guaranteed to have to do a cleanup sweep in 20.2 anyway.

I propose that, once we get ready to cut 20.2, we change this migration to have a different migration key, so it runs again identically. I think that would (probably?) put us in the clear.

I've pushed another version that fixes some little issues and also disables the migration if it's unnecessary due to a high enough bootstrap version. Thanks for the reviews so far, especially on the weekend.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/49099#-:-M7VK_-i9eE-cIfLCRV-:b-9iv5oc)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @irfansharif, @lucy-zhang, and @rohany)

**Review by ajwerner — APPROVED** [review]
:lgtm:

> Reviewed 1 of 5 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/49099#-:-M7c0jJ1A46L_dkuGCPP:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @irfansharif, @jordanlewis, @lucy-zhang, and @rohany)

___
*[pkg/sqlmigrations/migrations.go, line 897 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/49099#-M7c-qeMDO-CFMGoxA-Z:-M7c-qeN88ZiDaS8g8wa:b-n3xisn) ([raw file](https://github.com/cockroachdb/cockroach/blob/bdcc6d4ddf900d9d6f2a89518cae3884d60b0f2f/pkg/sqlmigrations/migrations.go#L897)):*
> ```Go
> 			q := fmt.Sprintf(
> 				`SELECT "parentID", name, id FROM [%d AS namespace_deprecated]
>               WHERE id NOT IN (SELECT id FROM [%d AS namespace])`,
> ```

Seems like we should put a `LIMIT` clause here given we're going be batching it. I'll grant that you'd need 10s of millions for it to be a problem but still seems like if we're going the batching route, may as well. If you want to know whether there's more than the limit you could select your batch limit+1 or come up with some sql to tell you.

**Comment by jordanlewis** [comment]
Added the limit. TFTR!

**Review by thoszhang — APPROVED** [review]
> Reviewed 1 of 3 files at r2, 3 of 5 files at r3, 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/49099)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @irfansharif, @jordanlewis, and @rohany)

___
*[pkg/cmd/roachtest/namespace_upgrade.go, line 26 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/49099#-M7cb6HwBQLcXK9SUIu6:-M7cb6Hx0LnK6SJtchFS:b4ztbud) ([raw file](https://github.com/cockroachdb/cockroach/blob/92a7e224c27450ebd47bc011ca0dc6eb06d78700/pkg/cmd/roachtest/namespace_upgrade.go#L26)):*
> ```Go
> 		Owner: OwnerSQLSchema,
> 		// This test is a regression test designed to test for #49092.
> 		// It
> ```

nit: heads up that this comment is unfinished.
___
*[pkg/server/server_sql.go, line 634 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/49099#-M7cbz6d3hTnnU9x40ph:-M7cbz6d3hTnnU9x40pi:b-efoeuv) ([raw file](https://github.com/cockroachdb/cockroach/blob/92a7e224c27450ebd47bc011ca0dc6eb06d78700/pkg/server/server_sql.go#L634)):*
> ```Go
> 		return err
> 	}
> 	{
> ```

nit: I don't think we really need these extra braces.
___
*[pkg/sqlmigrations/migrations.go, line 844 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/49099#-M7cd8-x4eTKrLJ_I-XA:-M7cd8-x4eTKrLJ_I-XB:b-ida04x) ([raw file](https://github.com/cockroachdb/cockroach/blob/92a7e224c27450ebd47bc011ca0dc6eb06d78700/pkg/sqlmigrations/migrations.go#L844)):*
> ```Go
> 		startTime := timeutil.Now().String()
> 		for migRetry := retry.Start(migrationRetryOpts); migRetry.Next(); {
> 			if err := m.migrateSystemNamespace(ctx, migrationKey, r, startTime); err != nil {
> ```

I think having a log tag is still useful even if you end up wrapping the original context.
___
*[pkg/sqlmigrations/migrations.go, line 909 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/49099#-M7cdX6-5L-q0uBgkz32:-M7cdX6-5L-q0uBgkz33:b-xl5zwu) ([raw file](https://github.com/cockroachdb/cockroach/blob/92a7e224c27450ebd47bc011ca0dc6eb06d78700/pkg/sqlmigrations/migrations.go#L909)):*
> ```Go
> 				return err
> 			}
> 			for i, row := range rows {
> ```

I'd add some more logging around here. Logging each batch query might be useful. Even logging every single entry that's migrated, at level 2 or 3, doesn't seem ridiculous to me.

**Review by jordanlewis — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/49099)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @irfansharif, @lucy-zhang, and @rohany)

___
*[pkg/sqlmigrations/migrations.go, line 844 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/49099#-M7cd8-x4eTKrLJ_I-XA:-M7cfUQS8Or6tWn8kolK:b-f89q3i) ([raw file](https://github.com/cockroachdb/cockroach/blob/92a7e224c27450ebd47bc011ca0dc6eb06d78700/pkg/sqlmigrations/migrations.go#L844)):*
<details><summary><i>Previously, lucy-zhang (Lucy Zhang) wrote…</i></summary><blockquote>

I think having a log tag is still useful even if you end up wrapping the original context.
</blockquote></details>

We make a log tag inside of migrateSystemNamespace.
___
*[pkg/sqlmigrations/migrations.go, line 909 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/49099#-M7cdX6-5L-q0uBgkz32:-M7cgfVf-t6ON5T2FqEo:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/92a7e224c27450ebd47bc011ca0dc6eb06d78700/pkg/sqlmigrations/migrations.go#L909)):*
<details><summary><i>Previously, lucy-zhang (Lucy Zhang) wrote…</i></summary><blockquote>

I'd add some more logging around here. Logging each batch query might be useful. Even logging every single entry that's migrated, at level 2 or 3, doesn't seem ridiculous to me.
</blockquote></details>

Done.

**Comment by jordanlewis** [comment]
bors r+

TFTRs

**Review by yuzefovich — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/49099)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @irfansharif, @jordanlewis, @lucy-zhang, and @rohany)

___
*[docs/generated/sql/functions.md, line 1480 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/49099#-M7kONIl4goebPMGamJi:-M7kONImDGeDrzOu_RiO:b-h27f5e) ([raw file](https://github.com/cockroachdb/cockroach/blob/34b078825fc2e9935f7cc8540eba7b14b157fdc2/docs/generated/sql/functions.md#L1480)):*
> ```Markdown
> <tr><td><a name="crdb_internal.cluster_name"></a><code>crdb_internal.cluster_name() &rarr; <a href="string.html">string</a></code></td><td><span class="funcdesc"><p>Returns the cluster name.</p>
> </span></td></tr>
> <tr><td><a name="crdb_internal.completed_migrations"></a><code>crdb_internal.completed_migrations() &rarr; <a href="string.html">string</a>[]</code></td><td><span class="funcdesc"><p>This function is used only by CockroachDB’s developers for testing purposes.</p>
> ```

nit: I think that it is possible to mark builtins as "private", and that way they won't be showing up in the generated docs.
