### PR TITLE
backupccl: fix error when restoring a table that references a type defined in user-defined schema

### LINKED ISSUE #70168: backup/restore: restoring table that references a type that is already defined in the schema being restored to causes error
Sample test case added to `backup_test.go` to reproduce

Produces error: `error executing 'RESTORE TABLE d.s.t FROM 'nodelocal://0/test/' WITH into_db = 'd2'': pq: restoring 1 TableDescriptors from 0 databases: restoring table desc and namespace entries: table already exists`

```
	// Test cases where we attempt to remap types in the backup to types that
	// already exist in the cluster.
	t.Run("backup-remap2", func(t *testing.T) {
		_, _, sqlDB, _, cleanupFn := BackupRestoreTestSetup(t, singleNode, 0, InitManualReplication)
		defer cleanupFn()
		sqlDB.Exec(t, `
CREATE DATABASE d;
CREATE SCHEMA d.s;
CREATE TYPE d.s.greeting AS ENUM ('hello', 'howdy', 'hi');
CREATE TABLE d.s.t (x d.s.greeting);
INSERT INTO d.s.t VALUES ('hello'), ('howdy');
CREATE TYPE d.s.farewell AS ENUM ('bye', 'cya');
CREATE TABLE d.s.t2 (x d.s.greeting[]);
INSERT INTO d.s.t2 VALUES (ARRAY['hello']);
`)
		{
			// Backup and restore t.
			sqlDB.Exec(t, `BACKUP TABLE d.s.t TO 'nodelocal://0/test/'`)
			sqlDB.Exec(t, `DROP TABLE d.s.t`)
			sqlDB.Exec(t, `RESTORE TABLE d.s.t FROM 'nodelocal://0/test/'`)

			// Check that the table data is restored correctly and the types aren't touched.
			sqlDB.CheckQueryResults(t, `SELECT 'hello'::d.s.greeting, ARRAY['hello']::d.s.greeting[]`, [][]string{{"hello", "{hello}"}})
			sqlDB.CheckQueryResults(t, `SELECT * FROM d.s.t ORDER BY x`, [][]string{{"hello"}, {"howdy"}})

			// d.t should be added as a back reference to greeting.
			sqlDB.ExpectErr(t, `pq: cannot drop type "greeting" because other objects \(.*\) still depend on it`, `DROP TYPE d.s.greeting`)
		}

		{
			// Test that backing up an restoring a table with just the array type
			// will remap types appropriately.
			sqlDB.Exec(t, `BACKUP TABLE d.s.t2 TO 'nodelocal://0/test2/'`)
			sqlDB.Exec(t, `DROP TABLE d.s.t2`)
			sqlDB.Exec(t, `RESTORE TABLE d.s.t2 FROM 'nodelocal://0/test2/'`)
			sqlDB.CheckQueryResults(t, `SELECT 'hello'::d.s.greeting, ARRAY['hello']::d.s.greeting[]`, [][]string{{"hello", "{hello}"}})
			sqlDB.CheckQueryResults(t, `SELECT * FROM d.s.t2 ORDER BY x`, [][]string{{"{hello}"}})
		}

		{
			// Create another database with compatible types.
			sqlDB.Exec(t, `CREATE DATABASE d2`)
			sqlDB.Exec(t, `CREATE SCHEMA d2.s`)
			sqlDB.Exec(t, `CREATE TYPE d2.s.greeting AS ENUM ('hello', 'howdy', 'hi')`)

			// Now restore t into this database. It should remap d.greeting to d2.greeting.
			sqlDB.Exec(t, `RESTORE TABLE d.s.t FROM 'nodelocal://0/test/' WITH into_db = 'd2'`)
                }
})
```
The culprit is that within `restore_planning.go` in the `allocateDescriptorRewrites` function, the collision logic check uses the wrong parent schema id.

https://github.com/cockroachdb/cockroach/blob/master/pkg/ccl/backupccl/restore_planning.go#L721-L728

```
				// See if there is an existing type with the same name.
				desc, err := catalogkv.GetDescriptorCollidingWithObject(
					ctx,
					txn,
					p.ExecCfg().Codec,
					parentID,
					typ.GetParentSchemaID(),
					typ.Name,
				)
```
`typ.GetParentSchemaID()` returns the schema ID of the schema the type was originally backed up from, not the id of the schema being restored to. Note that this is fine with the public schema since it will be 29 either but with UDS, this issue occurs. 

I'm not sure at the moment how to map one schema to the other given just the schema id.

### PR DESCRIPTION
**Pull request by gh-casper**
Previously, restore would fail if trying to restore a table that references a type defined in a user defined schema in a new database.

This change adds logic to use ID of the schema in the restoring DB for a type if this schema has the same name as in the DB backed up.

Fixes: #70168

Release note: none

### CODE REVIEW

File: pkg/ccl/backupccl/restore_planning.go [hunk 1]
```diff
@@ -718,12 +720,19 @@ func allocateDescriptorRewrites(
 				}
 
 				// See if there is an existing type with the same name.
+				getParentSchemaID := func(typ *typedesc.Mutable) (parentSchemaID descpb.ID) {
+					// If we find UDS with same name defined in the restoring DB, use its ID instead.
+					if parentSchemaID, ok = userDefinedSchemaIDMap[typ.GetParentSchemaID()]; !ok {
```
Comment (adityamaru) [inline pkg/ccl/backupccl/restore_planning.go:725]: Just wondering, instead of creating a new `userDefinedSchemaIDMap` can we just use `descriptorRewrites`?

Can we do something like:

```
parentSchemaID = typ.GetParentSchemaID()
if rewrite, ok := descriptorRewrites[typ.ID]; ok {
     // Check if an ID rewrite has been specified.
     if rewrite.ID != 0 {
         parentSchemaID = rewrite.ID
     }
}

File: pkg/ccl/backupccl/backup_test.go [hunk 2]
```diff
@@ -2867,6 +2867,58 @@ INSERT INTO d.t2 VALUES (ARRAY['hello']);
...
+CREATE TYPE d.s.greeting AS ENUM ('hello', 'howdy', 'hi');
+CREATE TABLE d.s.t (x d.s.greeting);
+INSERT INTO d.s.t VALUES ('hello'), ('howdy');
+CREATE TYPE d.s.farewell AS ENUM ('bye', 'cya');
+CREATE TABLE d.s.t2 (x d.s.greeting[]);
+INSERT INTO d.s.t2 VALUES (ARRAY['hello']);
+`)
+		{
+			// Backup and restore t.
+			sqlDB.Exec(t, `BACKUP TABLE d.s.t TO $1`, LocalFoo + "1")
```
Comment (adityamaru) [inline pkg/ccl/backupccl/backup_test.go:2887]: nit: LocalFoo + "/1" maybe? I think we use this pattern elsewhere when we don't have subtest names.

**Review by adityamaru — COMMENTED** [review]
Nice work on this! Just a couple of comments.

File: pkg/ccl/backupccl/backup_test.go (hunk 2 above)
Comment (gh-casper) [reply pkg/ccl/backupccl/backup_test.go]: Done.

File: pkg/ccl/backupccl/restore_planning.go (hunk 1 above)
Comment (gh-casper) [reply pkg/ccl/backupccl/restore_planning.go]: Good call!

**Comment by adityamaru** [comment]
We usually squash all commits that address comments into a single (or sometimes more than one if there is a logical break in code) meaningful commit in the PR. You can find more details here - https://cockroachlabs.atlassian.net/wiki/spaces/PROD/pages/1131119344/Squash+Remove+Commits. Once you do that this LGTM!

**Review by adityamaru — APPROVED** [review]
