### PR TITLE
security: fixes CertificateLoader tests when running as root

### LINKED ISSUE #68485: security: broken test `//pkg/security:security_test` in Bazel
Regressed by `e34411c29e1b9db0f50e14bbe302156a8ae77a6b`

```
W210805 16:49:39.662290 23 security/certificate_loader.go:339  [-] 1  bad filename /tmp/certs_test614838746/ca.foo.crt: CA certificate filename should match ca.crt
W210805 16:49:39.662409 23 security/certificate_loader.go:339  [-] 2  bad filename /tmp/certs_test614838746/client..crt: client certificate filename should match client.<user>.crt
W210805 16:49:39.662450 23 security/certificate_loader.go:339  [-] 3  bad filename /tmp/certs_test614838746/client.crt: client certificate filename should match client.<user>.crt
W210805 16:49:39.662485 23 security/certificate_loader.go:339  [-] 4  bad filename /tmp/certs_test614838746/cr..crt: unknown prefix "cr"
W210805 16:49:39.662521 23 security/certificate_loader.go:339  [-] 5  bad filename /tmp/certs_test614838746/node..crt: node certificate filename should match node.crt
W210805 16:49:39.662554 23 security/certificate_loader.go:339  [-] 6  bad filename /tmp/certs_test614838746/node.foo.crt: node certificate filename should match node.crt
W210805 16:49:39.664125 23 security/certificate_loader.go:357  [-] 7  error finding key for /tmp/certs_test614838746/client.root.crt: could not stat key file /tmp/certs_test614838746/client.root.key: stat /tmp/certs_test614838746/client.root.key: no such file or directory
W210805 16:49:39.664271 23 security/certificate_loader.go:357  [-] 8  error finding key for /tmp/certs_test614838746/node.crt: could not stat key file /tmp/certs_test614838746/node.key: stat /tmp/certs_test614838746/node.key: no such file or directory
W210805 16:49:39.664720 23 security/certificate_loader.go:357  [-] 9  error finding key for /tmp/certs_test614838746/node.crt: key file /tmp/certs_test614838746/node.key has permissions -rwx---r--, exceeds -rwxr-----
W210805 16:49:39.665044 23 security/certificate_loader.go:354  [-] 10  could not parse certificate for /tmp/certs_test614838746/client.root.crt: failed to validate certificate 0 in file client.root.crt: client certificate has principals ["notroot"], expected "root"
--- FAIL: TestNamingScheme (0.03s)
    certificate_loader_test.go:389: #3: mismatched error, expected: .* exceeds -rwx------
        (1) attached stack trace
          -- stack trace:
          | github.com/cockroachdb/cockroach/pkg/security_test.TestNamingScheme
          | 	github.com/cockroachdb/cockroach/pkg/security_test/certificate_loader_test.go:271
          | testing.tRunner
          | 	GOROOT/src/testing/testing.go:1193
          | runtime.goexit
          | 	GOROOT/src/runtime/asm_amd64.s:1371
        Wraps: (2) .* exceeds -rwx------
        Error types: (1) *withstack.withStack (2) *errutil.leafError, got <nil>
    certificate_loader_test.go:389: #3: mismatched error, expected: .* exceeds -rwx------
        (1) attached stack trace
          -- stack trace:
          | github.com/cockroachdb/cockroach/pkg/security_test.TestNamingScheme
          | 	github.com/cockroachdb/cockroach/pkg/security_test/certificate_loader_test.go:273
          | testing.tRunner
          | 	GOROOT/src/testing/testing.go:1193
          | runtime.goexit
          | 	GOROOT/src/runtime/asm_amd64.s:1371
        Wraps: (2) .* exceeds -rwx------
        Error types: (1) *withstack.withStack (2) *errutil.leafError, got key file /tmp/certs_test614838746/node.key has permissions -rwx---r--, exceeds -rwxr-----
        (1) attached stack trace
          -- stack trace:
          | github.com/cockroachdb/cockroach/pkg/security.checkFilePermissions
          | 	github.com/cockroachdb/cockroach/pkg/security/permission_check.go:27
          | github.com/cockroachdb/cockroach/pkg/security.(*CertificateLoader).findKey
          | 	github.com/cockroachdb/cockroach/pkg/security/certificate_loader.go:394
          | github.com/cockroachdb/cockroach/pkg/security.(*CertificateLoader).Load
          | 	github.com/cockroachdb/cockroach/pkg/security/certificate_loader.go:356
          | github.com/cockroachdb/cockroach/pkg/security_test.TestNamingScheme
          | 	github.com/cockroachdb/cockroach/pkg/security_test/certificate_loader_test.go:369
          | testing.tRunner
          | 	GOROOT/src/testing/testing.go:1193
          | runtime.goexit
          | 	GOROOT/src/runtime/asm_amd64.s:1371
        Wraps: (2) key file /tmp/certs_test614838746/node.key has permissions -rwx---r--, exceeds -rwxr-----
        Error types: (1) *withstack.withStack (2) *errutil.leafError
```

### PR DESCRIPTION
**Pull request by catj-cockroach**
This change fixes the CertificateLoader tests when running as the
root user, since the acceptable permissions change depending on
what user owns the certificate files (which is root since the tests
create the certificate files).

Closes #68485

Release note: None

### CODE REVIEW

File: pkg/security/certificate_loader_test.go [hunk 1]
```diff
@@ -167,6 +167,13 @@ func makeTestCert(
 func TestNamingScheme(t *testing.T) {
 	defer leaktest.AfterTest(t)()
 
+	permissionRequirement := ".* exceeds -rwx------"
+
+	processID := os.Getuid()
+	if processID == 0 {
+		permissionRequirement = "exceeds -rwxr-----"
```
Comment (rickystewart) [inline pkg/security/certificate_loader_test.go:174]: A comment here would be great -- it is not clear at first glance why this would be necessary if we're the root user.

**Review by rickystewart — APPROVED** [review]
Thank you :)

**Comment by rickystewart** [comment]
Closes #68485

File: pkg/security/certificate_loader_test.go (hunk 1 above)
Comment (catj-cockroach) [reply pkg/security/certificate_loader_test.go:183]: Done! I want to add some description about this to the CockroachDB docs but I haven't looked into how to do that yet 😅

**Comment by catj-cockroach** [comment]
I wasn't certain if the Bazel CI check was failing because of a change that I made in this PR but it appears to be showing up in other PRs aside from this one. Assuming the tests pass again, I'll submit this to be merged!

**Comment by catj-cockroach** [comment]
bors +r
