### PR TITLE
sql: support referencing a routine from a view query

### LINKED ISSUE #146123: sql: support resolving a user-defined function from a view query
User-defined functions cannot be resolved in view queries. Example:
```
root@localhost:26257/defaultdb> CREATE FUNCTION f() RETURNS BOOL LANGUAGE SQL AS $$ SELECT true; $$;
CREATE FUNCTION

root@localhost:26257/defaultdb> create table t (a int);
CREATE TABLE

root@localhost:26257/defaultdb> create view v as select a, f() from t;
ERROR: unknown function: f()
SQLSTATE: 42883
HINT: There is probably a typo in function name. Or the intention was to use a user-defined function in the view query, which is currently not supported.
```

This issue tracks support for that.

Epic CRDB-19497

### PR DESCRIPTION
**Pull request by DrewKimball**
#### sql,schemachanger: add remaining handling for routine references in views

This commit adds the remaining logic needed to keep track of references
to routines from a view query in the schema changer. The following commit
will resolve these references upon planning the `CREATE VIEW` statement
and pass them to the schema changer.

Informs #146123

Release note: None

#### sql: support referencing a routine from a view query

This commit adds support for invoking a UDF from a view (materialized or
otherwise). This requires resolving routine references while planning the
`CREATE VIEW` statement and passing them to the schema changer.

Fixes #146123

Release note (sql change): Added support for invoking a UDF from a view
query. Renaming or setting the schema on the routine is currently not
allowed if it is referenced by a view.

### CODE REVIEW

**Review by rytaft — COMMENTED** [review]
opt changes :lgtm: 

> Reviewed 9 of 9 files at r1, 13 of 13 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/148616#-:-OTSzxC26C78KqPxFHKx:b-yql68r)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @rafiss)

___
*[`pkg/sql/drop_type.go` line 197 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/148616#-OTSyP8l1w0DacVA2mVk:-OTSyP8l1w0DacVA2mVl:betr92d) ([raw file](https://github.com/cockroachdb/cockroach/blob/702d2a31b36405d6f1286ed38f170835e6687d54/pkg/sql/drop_type.go#L197)):*
> ```Go
> }
> 
> func (p *planner) addRoutineViewBackReference(
> ```

nit: any reason this function is in the drop_type file?
___
*[`pkg/sql/drop_type.go` line 205 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/148616#-OTSyDJI0fNlKaXtdw7z:-OTSyDJI0fNlKaXtdw8-:bqvt47m) ([raw file](https://github.com/cockroachdb/cockroach/blob/702d2a31b36405d6f1286ed38f170835e6687d54/pkg/sql/drop_type.go#L205)):*
> ```Go
> 	}
> 
> 	// TODO(drewk): check if this is necessary.
> ```

Does this need to be resolved before we can merge this?

File: pkg/sql/alter_function.go [hunk 1]
```diff
@@ -210,32 +210,20 @@ func (n *alterFunctionRenameNode) startExec(params runParams) error {
...
-	if len(dependentFuncs) > 0 {
+	if len(dependentObjects) > 0 {
 		return errors.UnimplementedErrorf(
 			errors.IssueLink{
 				IssueURL: build.MakeIssueURL(83233),
 				Detail:   "renames are disallowed because references are by name",
 			},
-			"cannot rename function %q because other functions ([%v]) still depend on it",
-			fnDesc.Name, strings.Join(dependentFuncs, ", "))
+			"cannot rename function %q because other functions or views ([%v]) still depend on it",
```
Comment (rafiss) [inline pkg/sql/alter_function.go:227]: if we complete [`7edd9f0` (#146475)](https://github.com/cockroachdb/cockroach/pull/146475/commits/7edd9f05bdc8f5a874d1bcf3e234ed2fc6a5e6b5) then there would be no need to block the function from being renamed even if a view references it.

i don't mind tackling that separately after this PR gets merged, but a comment mentioning this followup work might be useful.

File: pkg/sql/catalog/descpb/structured.proto [hunk 2]
```diff
@@ -1838,6 +1838,7 @@ message FunctionDescriptor {
       (gogoproto.casttype) = "TriggerID"];
     repeated uint32 policy_ids = 6 [(gogoproto.customname) = "PolicyIDs",
       (gogoproto.casttype) = "PolicyID"];
+    optional bool view_query = 7 [(gogoproto.nullable) = false];
```
Comment (rafiss) [inline pkg/sql/catalog/descpb/structured.proto:1843]: nit: a comment on this field would help.

File: pkg/sql/drop_type.go [hunk 3]
```diff
@@ -194,6 +194,44 @@ func (p *planner) removeTypeBackReferences(
...
 
+func (p *planner) addRoutineViewBackReference(
+	ctx context.Context, routineID descpb.ID, ref descpb.ID,
+) error {
+	mutDesc, err := p.Descriptors().MutableByID(p.txn).Function(ctx, routineID)
+	if err != nil {
+		return err
+	}
+
+	// TODO(drewk): check if this is necessary.
```
Comment (rafiss) [inline pkg/sql/drop_type.go]: i don't see why we would want to check privileges while adding a back-ref. what was the background behind this line?

**Review by rafiss — CHANGES_REQUESTED** [review]
nice work! just had a few nits

File: pkg/sql/alter_function.go (hunk 1 above)
Comment (DrewKimball) [reply pkg/sql/alter_function.go:227]: Done.

File: pkg/sql/drop_type.go (hunk 3 above)
Comment (DrewKimball) [reply pkg/sql/drop_type.go]: I added it based on the fact that we do a similar privilege check for adding a type back-reference. But you're right - it's not needed, and in fact Postgres allows creating a view referencing a function without having execution privileges. I added some tests. It turns out that we end up disallowing a view that would hit this code path anyway, since we build the view query when it's created.

File: pkg/sql/catalog/descpb/structured.proto (hunk 2 above)
Comment (DrewKimball) [reply pkg/sql/catalog/descpb/structured.proto:1843]: Done.

**Review by DrewKimball — COMMENTED** [review]
TFYRs!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/148616#-:-OTd7vnc6bQRO6-E02cV:bz5phge)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @rafiss and @rytaft)

___
*[`pkg/sql/drop_type.go` line 197 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/148616#-OTSyP8l1w0DacVA2mVk:-OTcZFFj16IOl-DNOPLO:b-tq2lqo) ([raw file](https://github.com/cockroachdb/cockroach/blob/702d2a31b36405d6f1286ed38f170835e6687d54/pkg/sql/drop_type.go#L197)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

nit: any reason this function is in the drop_type file?
</blockquote></details>

Good point - moved it to `create_view.go`
___
*[`pkg/sql/drop_type.go` line 205 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/148616#-OTSyDJI0fNlKaXtdw7z:-OTcZOmr1ZT10kW7vi9s:b-1qtt2l) ([raw file](https://github.com/cockroachdb/cockroach/blob/702d2a31b36405d6f1286ed38f170835e6687d54/pkg/sql/drop_type.go#L205)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

Does this need to be resolved before we can merge this?
</blockquote></details>

Yeah - I was hoping to get some Foundations input on it.

**Review by rafiss — APPROVED** [review]
lgtm!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/148616#-:-OTdBK_XDQJKpKI_Kf9A:b-7nbn20)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @rytaft)

**Review by rytaft — APPROVED** [review]
:lgtm:

> Reviewed 19 of 19 files at r3, 14 of 14 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/148616#-:-OTe1N9E7T064ueqWScq:bnfp4nl)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @rafiss)

**Review by mgartner — APPROVED** [review]
Nicely done!

> Reviewed 18 of 18 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/148616#-:-OUAf4-k-OOq8Tr-_M1h:b-ao1qb6)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @rafiss)

___
*[`pkg/sql/opt/optbuilder/testdata/create_view` line 432 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/148616#-OUAebATEsYn7yWCmW-w:-OUAebATEsYn7yWCmW-x:bysuns5) ([raw file](https://github.com/cockroachdb/cockroach/blob/25e04507708816060a571c308bde20e06f755e05/pkg/sql/opt/optbuilder/testdata/create_view#L432)):*
> ```
>       └── [FUNCTION 100060]
> 
> # The routine's dependencies are not added to the view's dependencies.
> ```

nit: Should we have a test like this except the routine references another view? view1 -> routine -> view2, and make sure that view1 doesn't have a direct dependency on view2.

**Review by DrewKimball — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/148616)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @rafiss)

___
*[`pkg/sql/opt/optbuilder/testdata/create_view` line 432 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/148616#-OUAebATEsYn7yWCmW-w:-OUHIzDn2ixif24DX7Ds:bps71af) ([raw file](https://github.com/cockroachdb/cockroach/blob/25e04507708816060a571c308bde20e06f755e05/pkg/sql/opt/optbuilder/testdata/create_view#L432)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

nit: Should we have a test like this except the routine references another view? view1 -> routine -> view2, and make sure that view1 doesn't have a direct dependency on view2.
</blockquote></details>

Done. `baz()` now references a table, a sequence, a view, and a UDT.

**Comment by DrewKimball** [comment]
bors r=rafiss,rytaft,mgartner
