### PR TITLE
storage/cloud: Make google storage reader handle download interrupts.

### LINKED ISSUE #46195: roachtest: import/tpch/nodes=8 failed
[(roachtest).import/tpch/nodes=8 failed](https://teamcity.cockroachdb.com/viewLog.html?buildId=1811809&tab=buildLog) on [master@5a3d0c9539a671f0e55b680d3021b18dde9d190d](https://github.com/cockroachdb/cockroach/commits/5a3d0c9539a671f0e55b680d3021b18dde9d190d):

```
The test failed on branch=master, cloud=gce:
test artifacts and logs in: /home/agent/work/.go/src/github.com/cockroachdb/cockroach/artifacts/20200317-1811809/import/tpch/nodes=8/run_1
	cluster.go:2368,import.go:167,test_runner.go:753: error with attached stack trace:
		    main.(*monitor).WaitE
		    	/home/agent/work/.go/src/github.com/cockroachdb/cockroach/pkg/cmd/roachtest/cluster.go:2356
		    main.(*monitor).Wait
		    	/home/agent/work/.go/src/github.com/cockroachdb/cockroach/pkg/cmd/roachtest/cluster.go:2364
		    main.registerImportTPCH.func1
		    	/home/agent/work/.go/src/github.com/cockroachdb/cockroach/pkg/cmd/roachtest/import.go:167
		    main.(*testRunner).runTest.func2
		    	/home/agent/work/.go/src/github.com/cockroachdb/cockroach/pkg/cmd/roachtest/test_runner.go:753
		    runtime.goexit
		    	/usr/local/go/src/runtime/asm_amd64.s:1357
		  - monitor failure:
		  - error with attached stack trace:
		    main.(*monitor).wait.func2
		    	/home/agent/work/.go/src/github.com/cockroachdb/cockroach/pkg/cmd/roachtest/cluster.go:2412
		    runtime.goexit
		    	/usr/local/go/src/runtime/asm_amd64.s:1357
		  - monitor task failed:
		  - pq: gs://cockroach-fixtures/tpch-csv/sf-100/lineitem.tbl.2: unexpected EOF
		    import failed
		    main.registerImportTPCH.func1.2
		    	/home/agent/work/.go/src/github.com/cockroachdb/cockroach/pkg/cmd/roachtest/import.go:163
		    main.(*monitor).Go.func1
		    	/home/agent/work/.go/src/github.com/cockroachdb/cockroach/pkg/cmd/roachtest/cluster.go:2344
		    github.com/cockroachdb/cockroach/vendor/golang.org/x/sync/errgroup.(*Group).Go.func1
		    	/home/agent/work/.go/src/github.com/cockroachdb/cockroach/vendor/golang.org/x/sync/errgroup/errgroup.go:57
		    runtime.goexit
		    	/usr/local/go/src/runtime/asm_amd64.s:1357

```

<details><summary>More</summary><p>

Artifacts: [/import/tpch/nodes=8](https://teamcity.cockroachdb.com/viewLog.html?buildId=1811809&tab=artifacts#/import/tpch/nodes=8)
Related:
- #45074 roachtest: import/tpch/nodes=8 failed  [C-test-failure](https://api.github.com/repos/cockroachdb/cockroach/labels/C-test-failure) [O-roachtest](https://api.github.com/repos/cockroachdb/cockroach/labels/O-roachtest) [O-robot](https://api.github.com/repos/cockroachdb/cockroach/labels/O-robot) [branch-44941](https://api.github.com/repos/cockroachdb/cockroach/labels/branch-44941) [release-blocker](https://api.github.com/repos/cockroachdb/cockroach/labels/release-blocker)

- #44593 roachtest: import/tpch/nodes=8 failed  [C-test-failure](https://api.github.com/repos/cockroachdb/cockroach/labels/C-test-failure) [O-roachtest](https://api.github.com/repos/cockroachdb/cockroach/labels/O-roachtest) [O-robot](https://api.github.com/repos/cockroachdb/cockroach/labels/O-robot) [branch-release-19.2](https://api.github.com/repos/cockroachdb/cockroach/labels/branch-release-19.2) [release-blocker](https://api.github.com/repos/cockroachdb/cockroach/labels/release-blocker)

[See this test on roachdash](https://roachdash.crdb.dev/?filter=status%3Aopen+t%3A.%2Aimport%2Ftpch%2Fnodes%3D8.%2A&sort=title&restgroup=false&display=lastcommented+project)
<sub>powered by [pkg/cmd/internal/issues](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)</sub></p></details>

### PR DESCRIPTION
**Pull request by miretskiy**
Fixes #46195

Make google storage reader support interrupts during download.
Previous attempts did not use resumingGoogleStorageReader correctly.

In addition, add a unit test that attempts to read GC data with
variouis interrupts injected.  This test requires access
to the external resources, and is disabled by default.
Verified the test cleanly passes on 1000 runs.

Release notes: Improve reliability -- Google Cloud external storage
handles interrupted downloads gracefully.

### CODE REVIEW

File: pkg/util/sysutil/sysutil.go [hunk 1]
```diff
@@ -28,6 +29,12 @@ type Signal = syscall.Signal
 // Errno is syscall.Errno.
 type Errno = syscall.Errno
 
+// Exported syscall.Errno constants.
+const (
```
Comment (dt) [inline pkg/util/sysutil/sysutil.go:33]: Are these unused?

**Review by dt — APPROVED** [review]

**Review by miretskiy — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/48229)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dt)

___
*[pkg/util/sysutil/sysutil.go, line 33 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/48229#-M6AgtBhjt1IY_48QZru-r2-33:-M6WHz86AjOK9LUDmTts:bbvevl1) ([raw file](https://github.com/cockroachdb/cockroach/blob/2590dda29141268a581f9bb4f7122108225268f9/pkg/util/sysutil/sysutil.go#L33)):*
<details><summary><i>Previously, dt (David Taylor) wrote…</i></summary><blockquote>

Are these unused?
</blockquote></details>

They are used in a test.  I wanted to use syscall.ECONNRESET directly, alas lint was complaining.
