### PR TITLE
intentresolver: chunk intent resolution to limit in-flight requests

### LINKED ISSUE #166037: kvserver: unbounded concurrrency when resolving intents as part of txn GC in mvcc GC queue
Assume, hypothetically, that we had 231 ABORTED transaction records. Each such record might reference 1.78M intents.

If these transaction records became eligible for GC (due to inactivity), the following would happen (illustrated here against 24.3 codebase)

`processLocalKeyRange` calls`cleanupTxnIntentsAsyncFn` (for each txn)

https://github.com/cockroachdb/cockroach/blob/917f8feb69e137770694819f17dc31363aa82ec7/pkg/kv/kvserver/gc/gc.go#L1196-L1204

this goes into `(*IntentResolver).CleanupTxnIntentsOnGCAsync` which launches a goroutine for each of the 231 txns (there is a semaphore here, but its size is 1000), and each goroutine calls

https://github.com/cockroachdb/cockroach/blob/917f8feb69e137770694819f17dc31363aa82ec7/pkg/kv/kvserver/intentresolver/intent_resolver.go#L778-L784

and next thing you know we're handing the intents to the `RequestBatcher`'s `resolveIntents` helper:

https://github.com/cockroachdb/cockroach/blob/917f8feb69e137770694819f17dc31363aa82ec7/pkg/kv/kvserver/intentresolver/intent_resolver.go#L856-L861

At this moment, we pause and note: we have 231 goroutines, each in charge of resolving 1.78M intents. Let's further say that ~all of those intent references are actually local and in fact on a single range, the very one that houses the txn records. Of course in practice the actual intents are long gone, but we're trying to clean up just in case.

Each (of the 231) `resolveIntents` goroutines is going to split its work queue of 231 intents into batches of 100. There is a bit of channel gymnastics, but in the end we end up here

https://github.com/cockroachdb/cockroach/blob/917f8feb69e137770694819f17dc31363aa82ec7/pkg/internal/client/requestbatcher/batcher.go#L505-L509

And fatally, `normalizedInFlightBackPressureLimit` returns `MaxInt64` by default. This is easy to miss, since we create batchers in multiple places, and there are conflicting defaults. But I'm pretty sure the one we're using here is constructed here:

https://github.com/cockroachdb/cockroach/blob/917f8feb69e137770694819f17dc31363aa82ec7/pkg/kv/kvserver/intentresolver/intent_resolver.go#L283-L294

and so its limit is this:

https://github.com/cockroachdb/cockroach/blob/917f8feb69e137770694819f17dc31363aa82ec7/pkg/kv/kvserver/intentresolver/intent_resolver.go#L1197-L1205

but that cluster setting is off by default:

https://github.com/cockroachdb/cockroach/blob/917f8feb69e137770694819f17dc31363aa82ec7/pkg/kv/kvserver/intentresolver/intent_resolver.go#L1171-L1190

The effect is that all those batches of 100 `ResolveIntentRequest` are spawned concurrently.

Image

They also all hit the same range, creating a deeply nested giant set of latches that becomes more and more expensive to attach to with each request.

Image

The run would then time out/fail (or the node crash), setting up the next cycle as the range is likely eligible for GC again due to the `largeAbortSpan` heuristic:

https://github.com/cockroachdb/cockroach/blob/917f8feb69e137770694819f17dc31363aa82ec7/pkg/kv/kvserver/mvcc_gc_queue.go#L159-L162

With the change

```
SET CLUSTER SETTING kv.intent_resolver.batcher.in_flight_backpressure_limit.enabled = true
```

this scenario would be defused: we'd get ~1000 goroutines hitting the replica (with batches of 100) each, which is not great but also not terrible. The queue would time out resolving all of the intents and fail, and (after the `TxnCleanupThreshold` cooldown period in the `largeAbortSpan` heuristic, default 1h), try it again. But this would likely be more of a "nuisance" rather than an outage.

## See also

https://github.com/cockroachdb/cockroach/pull/109899 for the original change that introduced this cluster setting. The context was that some intent resolutions have foreground traffic waiting on them, and we didn't want throttling to shift from admission control into a semaphore where, for example, ResolveIntent to remote non-overloaded stores could be delayed because the semaphore is full of ResolveIntent waiting for admission at overloaded stores.

This concern does not apply to the txn GC use case,  and batching between GC and non-GC intent resolution is likely not useful anyway, so perhaps the best thing to do is to give GC its own resolver, or find any other way to make sure it can't spawn `taskLimit(1000) x intents_per_txn/100` goroutines through the batcher.

But even ignoring the problem we saw with txn GC, it does seem concerning that a single foreground txn that for whatever reason references (say) 100k point intents will cause 1000 goroutines to be spawned.

Jira issue: CRDB-61726

### PR DESCRIPTION
**Pull request by tbg**
## Summary

Two-pronged approach to limit the goroutine/intent storm caused by MVCC
GC resolving intents for transactions with many intents (e.g. 70k):

- **Commit 1: Per-caller chunking** — `resolveIntents` now submits
  intents to the request batcher in chunks of 1000 (instead of all at
  once), collecting responses for each chunk before submitting the next.
  When `len(reqs) <= 1000` (the common case), behavior is identical to
  before.

- **Commit 2: Node-level intent budget** — An IntPool-based budget
  limits the total number of in-flight intents across all concurrent
  GC-initiated async cleanup goroutines to 1000. Goroutines block (not
  skip) until budget is available. For large transactions exceeding the
  budget, the IntPool truncates the acquisition to the full capacity,
  effectively consuming the entire budget until that goroutine
  completes ("overshoot by one txn").

- **Commit 3: Package doc** — Adds a package-level doc comment to
  `intentresolver` explaining the use cases, resolution pipeline,
  request batching, and concurrency limiters.

I don't love the additional proliferation of concurrency limiters here,
but at least the resulting picture makes sense and addresses the
problem. A more comprehensive re-working of this is possible, but
would not be something we can backport.

Fixes: #166037
Epic: none

Release note (bug fix): Fixed a problem where MVCC GC resolving intents
for large aborted transactions (with tens of thousands of intents) could
spawn an unbounded number of concurrent goroutines, overwhelming the
node with intent resolution work and potentially causing it to crash or
time out. Intent resolution is now chunked per caller and limited by a
node-level intent budget during GC.

### CODE REVIEW

**Review by themavik — COMMENTED** [review]
Reviewed the changes — the implementation is clean and addresses the reported issue.

**Review by themavik — COMMENTED** [review]
**What this PR does:** Chunks intent resolution to limit in-flight requests and adds gcIntentBudget to prevent GC from overwhelming the node.

**Done well:** The doc.go is excellent—clear explanation of the four use cases, resolution pipeline, request batching, and all concurrency limiters (ir.sem, gcIntentBudget, maxIntentsInFlightPerCaller, lockInFlightTxnCleanup, inFlightPushes). The chunking in resolveIntents (maxIntentsInFlightPerCaller=1000) correctly collects responses per chunk before submitting the next. gcIntentBudget with IntPool truncation handles large transactions.

**Note:** When a transaction has >1000 intents, it consumes the full budget until completion—doc.go explains this. The ctx.Done and stopper.ShouldQuiesce checks in the chunk loop are good for graceful shutdown.

**Review by themavik — COMMENTED** [review]
**What it does:** Chunks intent resolution to limit in-flight requests—adds gcIntentBudget (1000 intents) and per-caller chunking (1000 intents) to prevent goroutine explosion from large transactions.

**Done well:** Excellent doc.go—clearly documents the four use cases, resolution pipeline, request batching, and how the limiters compose. The gcIntentBudget acquisition in CleanupTxnIntentsOnGCAsync with IntPool truncation for oversized txns is the right approach. Chunking resolveIntents with maxIntentsInFlightPerCaller prevents 70k intents from spawning 70k batcher goroutines. Proper ctx.Done and stopper handling in the chunk loop.

**Suggestion:** Consider making gcMaxIntentsInFlight and maxIntentsInFlightPerCaller cluster settings for tuning in production—1000 may not fit all workloads. The doc already mentions gcIntentBudget capacity; adding the chunk size to the doc would help.

File: pkg/kv/kvserver/intentresolver/doc.go [hunk 1]
```diff
@@ -0,0 +1,207 @@
+// Copyright 2026 The Cockroach Authors.
+//
+// Use of this software is governed by the CockroachDB Software License
+// included in the /LICENSE file.
+
+// Package intentresolver resolves intents (and locks more generally)
```
Comment (tbg) [inline pkg/kv/kvserver/intentresolver/doc.go]: just say intents and use it synonymously with locks.

File: pkg/kv/kvserver/intentresolver/doc.go [hunk 2]
```diff
@@ -0,0 +1,207 @@
...
+// backpressure comes from the user's request goroutine itself.
+//
+// 2. Post-transaction cleanup (CleanupTxnIntentsAsync). After a
+// transaction commits or aborts (EndTxn), the executing replica
+// asynchronously resolves the transaction's intents and GCs its
+// record. This is semi-synchronous: if the async semaphore is full,
+// the work runs in the caller's goroutine, applying backpressure to
+// the client. This ensures that a burst of small transactions does
+// not accumulate a large intent resolution backlog. The admission
+// header is derived from the completed transaction's priority
```
Comment (tbg) [inline pkg/kv/kvserver/intentresolver/doc.go]: don't mention the admission details here.

File: pkg/kv/kvserver/intentresolver/doc.go [hunk 3]
```diff
@@ -0,0 +1,207 @@
...
+// asynchronously using PUSH_TOUCH (a non-committal push that only
+// aborts expired transactions). Like post-transaction cleanup, this
+// falls back to synchronous processing when the semaphore is full.
+//
+// 4. MVCC GC cleanup (CleanupTxnIntentsOnGCAsync). The MVCC GC queue
+// encounters old transaction records and resolves their intents. This
+// is background work that must not block the GC queue, so it uses
+// WaitForSem=false: if no async slot is available, the transaction is
+// skipped and retried in a future GC pass. However, a single
+// transaction can have tens of thousands of intents (e.g. a bulk
```
Comment (tbg) [inline pkg/kv/kvserver/intentresolver/doc.go]: this makes it sound a bit like this is the only case in which a txn can reference 1000s of intents, but it can happen in all cases. Rework this accordingly.

File: pkg/kv/kvserver/intentresolver/doc.go [hunk 4]
```diff
@@ -0,0 +1,207 @@
...
+// (ResolveIntentRequest) and irRangeBatcher for ranged intents
+// (ResolveIntentRangeRequest). The batcher groups requests by
+// destination range and coalesces them into batches, so N intents on
+// the same range become a single BatchRequest. This is important
+// because a committed transaction's intents are often co-located on a
+// small number of ranges, and without batching each intent would be a
+// separate RPC.
+//
+// The batcher itself spawns one goroutine per in-flight batch (i.e.
+// per destination range with pending work). For a transaction with
```
Comment (tbg) [inline pkg/kv/kvserver/intentresolver/doc.go]: this makes it sound like it's at most one goroutine per destination range, but I think it can be many goroutines all for the same range (which happened in the motivating issue)? Clarify.

Comment (tbg) [reply pkg/kv/kvserver/intentresolver/doc.go]: you could extend the example below and say "If the 1000 intents were all on the same range, this means ..."

File: pkg/kv/kvserver/intentresolver/doc.go [hunk 5]
```diff
@@ -0,0 +1,207 @@
...
+// 1000 intents spread across 100 ranges, this means ~100 concurrent
+// goroutines (one per range), not 1000.
+//
+// The intent resolution batchers (irBatcher, irRangeBatcher) do not
+// impose their own in-flight backpressure limit by default. This is
+// intentional: the callers already limit concurrency (via ir.sem and
```
Comment (tbg) [inline pkg/kv/kvserver/intentresolver/doc.go]: I think the real motivation was that we wanted to avoid priority inversion: if a bunch of low-priority intent resolutions occupy all slots (maybe blocked since they're talking to an overloaded leaseholder somewhere in the system), then high-priority work would not resolve its intents (which would in turn block other high-prio work). Make that the primary justification for the status quo.

File: pkg/kv/kvserver/intentresolver/doc.go [hunk 6]
```diff
@@ -0,0 +1,207 @@
...
+// gcIntentBudget), so a batcher-level limit would be redundant. The
+// callers have already paid the memory cost of buffering the
+// requests, so there is little benefit in refusing to send them. The
+// GC batcher (gcBatcher, used for GCRequest to clean up txn records)
+// is the exception: GC record cleanup runs outside ir.sem, so the
+// gcBatcher uses an in-flight limit of 1000.
+//
+// A single point intent is resolved via ResolveIntent, which bypasses
```
Comment (tbg) [inline pkg/kv/kvserver/intentresolver/doc.go]: This came out of left field and it's not clear where this applies. For example, if MVCC GC finds a single intent, I doubt it sends a synchronous ResolveIntent batch immediately? Clarify what this comment applies to.

File: pkg/kv/kvserver/intentresolver/doc.go [hunk 7]
```diff
@@ -0,0 +1,207 @@
...
+// full budget and all other GC goroutines block until it finishes.
+//
+// maxIntentsInFlightPerCaller — per-caller chunking (1000 intents).
+// Within a single call to resolveIntents, requests are submitted to
+// the batcher in chunks of 1000. Each chunk's responses are collected
+// before the next chunk is submitted. This bounds the number of
+// in-flight batcher goroutines that a single caller can create.
+// Without this, a transaction with 70,000 intents spread across
+// 70,000 ranges would spawn ~70,000 batcher goroutines
+// simultaneously.
```
Comment (tbg) [inline pkg/kv/kvserver/intentresolver/doc.go]: add sth like this: Instead, it will work through its 70000 intents in sequential batches of 1000, so in the best case the batcher will only create between 10 (ten batches of 100 intents each, when all 1000 intents are colocated) and 1000 (a batch per range, when all 1000 intents reside on different ranges - unlikely).

File: pkg/kv/kvserver/intentresolver/doc.go [hunk 8]
```diff
@@ -0,0 +1,207 @@
...
+//
+// lockInFlightTxnCleanup — per-transaction deduplication.
+// Ensures that only one goroutine is cleaning up a given
+// transaction's intents at a time. If a second attempt arrives (e.g.
+// GC encounters the same transaction again), it is skipped. This
```
Comment (tbg) [inline pkg/kv/kvserver/intentresolver/doc.go]: GC Is a bad example since it kicks in only way after the txn record is dormant. A better example is the transaction's own eager clean-up vs some other request encountering the intent.

File: pkg/kv/kvserver/intentresolver/doc.go [hunk 9]
```diff
@@ -0,0 +1,207 @@
...
+//   - Encountered-intent cleanup: ir.sem (with sync fallback).
+//     Typically small batches of intents from a single read.
+//
+//   - GC cleanup: ir.sem (non-blocking skip) + gcIntentBudget
+//     (blocking). At most 1000 goroutines, but further limited so
+//     that the total in-flight intent count across all of them is
+//     ~1000. Within each goroutine, per-caller chunking limits the
+//     batcher goroutines to 1000 at a time.
+//
+// # Admission control
```
Comment (tbg) [inline pkg/kv/kvserver/intentresolver/doc.go:194]: Narrow this down so that it doesn't rot as we improve this functionality. Instead, just leave a short note about the existence of this problem and refer another comment that hopefully exists that already explains this in detail.

File: pkg/kv/kvserver/intentresolver/intent_resolver.go [hunk 10]
```diff
@@ -755,6 +766,19 @@ func (ir *IntentResolver) CleanupTxnIntentsOnGCAsync(
...
 		}
 		defer release()
+		// Acquire intent budget to limit the total number of in-flight intents
+		// across all concurrent GC goroutines. For transactions with more intents
+		// than the budget capacity, the IntPool truncates the acquisition to the
+		// capacity, effectively consuming the entire budget until this goroutine
+		// completes.
+		numIntents := uint64(len(txn.LockSpans))
+		if numIntents > 0 {
+			alloc, err := ir.gcIntentBudget.Acquire(ctx, numIntents)
```
Comment (tbg) [inline pkg/kv/kvserver/intentresolver/intent_resolver.go:784]: can you point at existing test coverage that ensures that an IntPool created like the one here is can go negative?

File: pkg/kv/kvserver/intentresolver/intent_resolver.go [hunk 11]
```diff
@@ -1102,38 +1126,46 @@ func (ir *IntentResolver) resolveIntents(
...
-			batcher = ir.irBatcher
-		case kvpb.ResolveIntentRange:
-			batcher = ir.irRangeBatcher
-		default:
-			panic("unexpected")
-		}
-		rangeID := ir.lookupRangeID(ctx, req.Header().Key)
-		if err := batcher.SendWithChan(ctx, respChan, rangeID, req, h); err != nil {
-			return kvpb.NewError(err)
+	// Submit intents in chunks to avoid overwhelming the node with
```
Comment (tbg) [inline pkg/kv/kvserver/intentresolver/intent_resolver.go:1141]: Add a test for this. The test can override the chunk size to something more manageable.

File: pkg/kv/kvserver/intentresolver/intent_resolver.go (hunk 10 above)
Comment (tbg) [reply pkg/kv/kvserver/intentresolver/intent_resolver.go:784]: actually just make this unit testable by making this a small helper that takes all of the required arguments (the intpool, the number of intents) and returns the `release` function and an error. Then we can add a nice little unit test and don't need to test this method specifically since the integration is trivial.

**Review by arulajmani — APPROVED** [review]
:lgtm:

> @arulajmani reviewed 3 files and all commit messages, and made 4 comments.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/166156#-:-Op4wU7H358otJ-iFWtS:bnfp4nl)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on tbg).

___
*[`pkg/kv/kvserver/intentresolver/doc.go` line 85 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/166156#-Op4UcY01vU4mCl13qQO:-Op4UcY01vU4mCl13qQP:b-q48ojv) ([raw file](https://github.com/cockroachdb/cockroach/blob/4f8a1577995b143cf181f2050ff2758f3ce70541/pkg/kv/kvserver/intentresolver/doc.go#L85)):*
> Multiple callers may submit
// work for the same range concurrently, each resulting in its own
// goroutine

This sentence seems disconnected from the rest of the paragraph. I don't quite follow it either, so maybe needs some more words?
___
*[`pkg/kv/kvserver/intentresolver/doc.go` line 139 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/166156#-Op4ZeF_EIejHziOryPx:-Op4ZeF_EIejHziOryPy:bjqc1lx) ([raw file](https://github.com/cockroachdb/cockroach/blob/4f8a1577995b143cf181f2050ff2758f3ce70541/pkg/kv/kvserver/intentresolver/doc.go#L139)):*
> ```Go
> // single large transaction may overshoot.
> //
> // Example: 50 GC goroutines each cleaning up a 20-intent transaction
> ```

To check my understanding, there's 1 GC goroutine per-store, right? If so, should we tweak these numbers to be a bit more realistic (say 10 GC goroutines, running 100-intents/transaction concurrently)? 
___
*[`pkg/kv/kvserver/intentresolver/intent_resolver.go` line 63 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/166156#-Op4T9LqDl59ebhqvZA4:-Op4T9LqDl59ebhqvZA5:b-ji7z25) ([raw file](https://github.com/cockroachdb/cockroach/blob/3e0b2518fc8dea2b79c76af552279ad9381cd31c/pkg/kv/kvserver/intentresolver/intent_resolver.go#L63)):*
> ```Go
> // it completes. This prevents a node from being overwhelmed by intent
> // resolution work when MVCC GC encounters many large transactions.
> const gcMaxIntentsInFlight = 1000
> ```

nit: Should we make this, and the `maxIntentsInFlightPerCaller` const below, a cluster setting instead?

**Review by tbg — COMMENTED** [review]
> @tbg made 3 comments and resolved 2 discussions.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/166156)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on arulajmani).

___
*[`pkg/kv/kvserver/intentresolver/doc.go` line 85 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/166156#-Op4UcY01vU4mCl13qQO:-Op7bW9_CJZ_lumYSlhk:b9aqwm2) ([raw file](https://github.com/cockroachdb/cockroach/blob/4f8a1577995b143cf181f2050ff2758f3ce70541/pkg/kv/kvserver/intentresolver/doc.go#L85)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

> Multiple callers may submit
// work for the same range concurrently, each resulting in its own
// goroutine

This sentence seems disconnected from the rest of the paragraph. I don't quite follow it either, so maybe needs some more words?
</blockquote></details>

You're right, this wasn't clear. The main point is actually that at the batcher level, we don't know about callers any more, and there is no concurrency limiting at this level at all. I updated and tightened this section.
___
*[`pkg/kv/kvserver/intentresolver/doc.go` line 139 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/166156#-Op4ZeF_EIejHziOryPx:-Op7deWRAIGT6_e7Y2GF:b-8vtzon) ([raw file](https://github.com/cockroachdb/cockroach/blob/4f8a1577995b143cf181f2050ff2758f3ce70541/pkg/kv/kvserver/intentresolver/doc.go#L139)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

To check my understanding, there's 1 GC goroutine per-store, right? If so, should we tweak these numbers to be a bit more realistic (say 10 GC goroutines, running 100-intents/transaction concurrently)?
</blockquote></details>

There's one goroutine per store running the GC queue, but it will spawn a goroutine per transaction (up to 1000 concurrently). So 50/20 is pretty realistic. I updated this to say "GC-triggered goroutine" so it's clear that there's a one-to-many relationship.
___
*[`pkg/kv/kvserver/intentresolver/intent_resolver.go` line 63 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/166156#-Op4T9LqDl59ebhqvZA4:-Op7dw4y85qlyRk2467D:b-cgtl26) ([raw file](https://github.com/cockroachdb/cockroach/blob/3e0b2518fc8dea2b79c76af552279ad9381cd31c/pkg/kv/kvserver/intentresolver/intent_resolver.go#L63)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

nit: Should we make this, and the `maxIntentsInFlightPerCaller` const below, a cluster setting instead?
</blockquote></details>

Let's discuss separately, I can follow up on this depending on the outcome.
