### PR TITLE
storeliveness: fix flaky TestTransportClusterSettingToggle

### LINKED ISSUE #165968: kv/kvserver/storeliveness: TestTransportClusterSettingToggle failed
kv/kvserver/storeliveness.TestTransportClusterSettingToggle [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Ci_TestsAwsLinuxArm64_UnitTests/21262407?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Ci_TestsAwsLinuxArm64_UnitTests/21262407?buildTab=artifacts#/) on master @ [b214651ebcc22398914c249259675c61880bbf47](https://github.com/cockroachdb/cockroach/commits/b214651ebcc22398914c249259675c61880bbf47):

```
=== RUN   TestTransportClusterSettingToggle
    test_log_scope.go:172: test logs captured to: /artifacts/tmp/_tmp/c445381c574801117807676e0b98cb23/logTestTransportClusterSettingToggle1245443024
    test_log_scope.go:82: use -show-logs to present logs inline
    transport_test.go:929: condition failed to evaluate within 45s: from transport_test.go:932: expected queue size 1, got 0
        
        goroutine dump: /artifacts/tmp/_tmp/c445381c574801117807676e0b98cb23/goroutine_dump_2417280991.txt
    panic.go:615: -- test log scope end --
test logs left over in: /artifacts/tmp/_tmp/c445381c574801117807676e0b98cb23/logTestTransportClusterSettingToggle1245443024
--- FAIL: TestTransportClusterSettingToggle (45.16s)
```
<details><summary>Help</summary>
<p>

See also: [How To Investigate a Go Test Failure \(internal\)](https://cockroachlabs.atlassian.net/l/c/HgfXfJgM)
</p>
</details>
/cc @cockroachdb/kv-triage
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*TestTransportClusterSettingToggle.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/bazci/githubpost/issues)

</sub>

Jira issue: CRDB-61699

### PR DESCRIPTION
**Pull request by pav-kv**
The test asserted that after toggling the heartbeat smearing setting back to enabled and enqueuing a message, `SendQueueSize` should be 1 (message queued but not yet delivered). This is inherently racy: `EnqueueMessage` signals `sendAllMessages`, which wakes `smearingSenderLoop`, which after ~10ms signals `processQueue`, which after another ~10ms drains the queue and decrements the metric. On a loaded CI machine, this entire pipeline completes before `SucceedsSoon` observes the intermediate queue state, causing the test to spin for 45s and fail with "expected queue size 1, got 0".

Remove the mid-test assertion on transient `SendQueueSize`. The test's purpose is to verify no messages are lost during setting toggles, which is already covered by the final assertions: 0 dropped, 3 sent, 3 received.

Fixes: #165968

### CODE REVIEW

File: pkg/kv/kvserver/storeliveness/transport_test.go [hunk 1]
```diff
@@ -924,18 +931,14 @@ func TestTransportClusterSettingToggle(t *testing.T) {
...
 
-	// Give the smearing sender time to drain the queue (reproduces CI flake).
-	time.Sleep(50 * time.Millisecond)
-
-	// Verify the message is enqueued but NOT delivered (waiting in smearing mode).
-	// Use SucceedsSoon to give the system time to stabilize in the correct state.
+	// Verify the message is enqueued but NOT delivered (waiting in smearing
+	// mode). The BeforeSmearingSend knob blocks the smearing sender, so the
+	// message remains in the queue deterministically.
 	testutils.SucceedsSoon(t, func() error {
```
Comment (pav-kv) [inline pkg/kv/kvserver/storeliveness/transport_test.go]: @miraradeva Alternatively, Claude attempted removing this entire block, for it being inherently flaky.

WDYT, is the fix worth the testing knob?

Comment (miraradeva) [reply pkg/kv/kvserver/storeliveness/transport_test.go]: Yeah, I'd say remove it. As long as messages are sent and received as expected, I don't think we particularly care exactly when they are in the various queues.

Comment (pav-kv) [reply pkg/kv/kvserver/storeliveness/transport_test.go]: Yeah, Claude was so attached to the idea of removing this check that, even when asked not to, it went "I'll just remove some comments at least".

Comment (pav-kv) [reply pkg/kv/kvserver/storeliveness/transport_test.go]: Done.

**Review by miraradeva — APPROVED** [review]

File: pkg/kv/kvserver/storeliveness/transport_test.go [hunk 2]
```diff
@@ -919,32 +919,15 @@ func TestTransportClusterSettingToggle(t *testing.T) {
...
-		default:
-		}
-		return nil
-	})
-
-	// Signal to send messages.
-
-	// Verify the message is received.
+	// Verify msg3 is delivered.
 	testutils.SucceedsSoon(
```
Comment (pav-kv) [inline pkg/kv/kvserver/storeliveness/transport_test.go:931]: This looks very similar to `SucceedsSoon` above. So I'm getting the intent here to test for "something" that looks different in the enabled/disabled paths. Otherwise a test that ignores the "toggle back" would still pass, if we only measure the fact that messages are delivered.
