### PR TITLE
roachtest: install dependencies used by pgx

### LINKED ISSUE #63892: roachtest: pgx failed
roachtest.pgx [failed](https://teamcity.cockroachdb.com/viewLog.html?buildId=2898497&tab=buildLog) with [artifacts](https://teamcity.cockroachdb.com/viewLog.html?buildId=2898497&tab=artifacts#/pgx) on master @ [4dc05cceea254854317a9374a4b88df06c0946a6](https://github.com/cockroachdb/cockroach/commits/4dc05cceea254854317a9374a4b88df06c0946a6):

```
The test failed on branch=master, cloud=gce:
test artifacts and logs in: /home/agent/work/.go/src/github.com/cockroachdb/cockroach/artifacts/pgx/run_1
	orm_helpers.go:228,orm_helpers.go:154,pgx.go:119,pgx.go:131,test_runner.go:777: 
		Tests run on Cockroach v21.1.0-alpha.3-2478-g4dc05cceea
		Tests run against pgx v4.11.0
		1 Total Tests Run
		0 tests passed
		1 test failed
		0 tests skipped
		0 tests ignored
		0 tests passed unexpectedly
		1 test failed unexpectedly
		0 tests expected failed but skipped
		0 tests expected failed but not run
		---
		--- FAIL: v4.[build failed] - unknown (unexpected)
		For a full summary look at the pgx artifacts 
		
		An updated blocklist (pgxBlocklist21_1) is available in the artifacts' pgx log
```
<details><summary>Reproduce</summary>
<p>
<p>To reproduce, try:

```bash
# From https://go.crdb.dev/p/roachstress, perhaps edited lightly.
caffeinate ./roachstress.sh pgx
```
</p>
</p>
</details>
<details><summary>Same failure on other branches</summary>
<p>

- #63700 roachtest: pgx failed [C-test-failure O-roachtest O-robot branch-release-20.2]
</p>
</details>
/cc @cockroachdb/sql-experience
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*pgx.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)
</sub>

### PR DESCRIPTION
**Pull request by rafiss**
This seems to have changed since roachprod was changed to use a new
image.

Also fix the blocklist for 20.2.

fixes https://github.com/cockroachdb/cockroach/issues/63892

Release note: None

### CODE REVIEW

**Comment by RichardJCai** [comment]
Just checked and it seems like this is failing for `lib/pq` as well, should we just add installing this into `installGolang` and maybe rename it `installGolangAndTestDeps` or something? 

`gopg.go` doesn't have this issue and I believe it's because `build-essential` includes `gcc`, I similarly installed `build-essential` to my gorm test to fix this.

```		if err := repeatRunE(
			ctx,
			c,
			node,
			"install dependencies",
			`sudo apt-get -qq install build-essential`,
		); err != nil {
			t.Fatal(err)
		}```

**Comment by rafiss** [comment]
oh interesting.. i'll just go ahead and add it to installGolang. i don't think we need to rename the function

File: pkg/cmd/roachtest/go_helpers.go [hunk 1]
```diff
@@ -17,6 +17,22 @@ const goPath = `/mnt/data1/go`
...
+		ctx, c, node, "update apt-get", `sudo apt-get -qq update`,
+	); err != nil {
+		t.Fatal(err)
+	}
+
+	if err := repeatRunE(
+		ctx,
+		c,
+		node,
+		"install dependencies (pgx uses C bindings)",
```
Comment (RichardJCai) [inline pkg/cmd/roachtest/go_helpers.go:30]: not specific to pgx anymore

**Review by RichardJCai — APPROVED** [review]
LGTM after updating description

**Comment by RichardJCai** [comment]
Oh and we should update pgx roachtest to not explicitly install `build-essential`

File: pkg/cmd/roachtest/go_helpers.go (hunk 1 above)
Comment (rafiss) [reply pkg/cmd/roachtest/go_helpers.go:30]: fixed

**Comment by rafiss** [comment]
bors r=RichardJCai
