### PR TITLE
Fix floatMandE to properly determine necessary precision.

### LINKED ISSUE #31: Ordered Key Encoding for float64 keys
Based on http://sqlite.org/src4/doc/trunk/www/key_encoding.wiki

### PR DESCRIPTION
**Pull request by petermattis**
Add DecodeFloat and flesh out the missing decodeSmallNumber.

Handling floating point precision is difficult so these routines
leverage the standard library floating point parsing and formatting.

Fixes #31

### CODE REVIEW

File: util/encoding/key_encoding.go [hunk 1]
```diff
@@ -410,44 +448,102 @@ func floatMandE(f float64) (int, []byte) {
...
+	// precision is necessary to precisely represent f. The 'e' format is
+	// d.dddde±dd.
+	b := strconv.AppendFloat(nil, f, 'e', -1, 64)
+	if len(b) < 5 {
+		// The formatted float must be at least 5 bytes or something unexpected has
+		// occurred.
+		panic(fmt.Errorf("malformed float: %v -> %s", f, b))
+	}
+
+	// Parse the exponent.
```
Comment (bdarnell) [inline util/encoding/key_encoding.go]: The exponent may be three digits for sufficiently large or close-to-zero numbers (a float64 has range of somewhere around 1e308). I also don't see anything in the docs that guarantees a minimum of two digits in the exponent.

File: util/encoding/key_encoding_test.go [hunk 2]
```diff
@@ -291,13 +294,76 @@ func disabledTestFloatMandE(t *testing.T) {
 		{1234.5, 2, []byte{0x19, 0x45, 0x64}},
 		{12.345, 1, []byte{0x19, 0x45, 0x64}},
 		{0.123, 0, []byte{0x19, 0x3c}},
+		{-0.123, 0, []byte{0x19, 0x3c}},
 		{0.0123, 0, []byte{0x03, 0x2e}},
 		{0.00123, -1, []byte{0x19, 0x3c}},
-		{9223372036854775807, 10, []byte{0x13, 0x2d, 0x43, 0x91, 0x07, 0x89, 0x6d, 0x9b, 0x75, 0x0e}},
+		// The following value cannot be precisely represented as a float.
+		// {9223372036854775807, 10, []byte{0x13, 0x2d, 0x43, 0x91, 0x07, 0x89, 0x6d, 0x9b, 0x75, 0x0e}},
```
Comment (bdarnell) [inline util/encoding/key_encoding_test.go]: Include tests for values outside the range of an int64 and especially those with 3-digit exponents; large numbers can be represented precisely in float64s as long as their low bits are zero.

File: util/encoding/key_encoding_test.go [hunk 3]
```diff
@@ -291,13 +294,76 @@ func disabledTestFloatMandE(t *testing.T) {
 		{1234.5, 2, []byte{0x19, 0x45, 0x64}},
 		{12.345, 1, []byte{0x19, 0x45, 0x64}},
 		{0.123, 0, []byte{0x19, 0x3c}},
+		{-0.123, 0, []byte{0x19, 0x3c}},
```
Comment (bdarnell) [inline util/encoding/key_encoding_test.go]: Maybe add the sign bit as a third expected value in the struct; otherwise it's confusing to see 0.123 and -0.123 with the same output.

File: util/encoding/key_encoding.go (hunk 1 above)
Comment (petermattis) [inline util/encoding/key_encoding.go]: Interesting. I was mislead that the output values take the form "+02". Looks like AppendFloat generates either a two digit or three digit exponent. I'll fix.

File: util/encoding/key_encoding_test.go (hunk 2 above)
Comment (petermattis) [inline util/encoding/key_encoding_test.go]: Done. I've included tests for `1e308`, `-1e308`, `1e-307` and `-1e-307` as well as `nan`, `+inf` and `-inf. These tests highlighted a bug in the encoding of "small" positive and negative values.

File: util/encoding/key_encoding_test.go (hunk 3 above)
Comment (petermattis) [inline util/encoding/key_encoding_test.go]: GIven that `floatMandE` takes the absolute value as its first operation, testing negative values isn't terribly interesting. I've removed this test case.

File: util/encoding/key_encoding.go [hunk 4]
```diff
@@ -410,44 +454,119 @@ func floatMandE(f float64) (int, []byte) {
...
+	e := bytes.IndexByte(b, 'e')
+	e10 := 0
+	for i := e + 2; i < len(b); i++ {
+		e10 = e10*10 + int(b[i]-'0')
+	}
+	if b[e+1] == '-' {
```
Comment (bdarnell) [inline util/encoding/key_encoding.go]: Panic if `b[e+1]` is neither '+' or '-'.

File: util/encoding/key_encoding.go [hunk 5]
```diff
@@ -410,44 +454,119 @@ func floatMandE(f float64) (int, []byte) {
...
-	if f >= 1 {
-		for t := f; t >= 1; t /= 100 {
-			i++
-		}
+
+	// Use strconv.FormatFloat to handle the intricacies of determining how much
+	// precision is necessary to precisely represent f. The 'e' format is
+	// d.dddde±dd.
+	b := strconv.AppendFloat(nil, f, 'e', -1, 64)
+	if len(b) < 5 {
```
Comment (bdarnell) [inline util/encoding/key_encoding.go]: If zero-padding to two digit exponents is not guaranteed (and I don't see it in the docs), then 4-byte strings are possible (and I think the code that follows would work with them).

**Comment by bdarnell** [comment]
LGTM

File: util/encoding/key_encoding.go (hunk 4 above)
Comment (petermattis) [inline util/encoding/key_encoding.go]: Sure. Done.

File: util/encoding/key_encoding.go (hunk 5 above)
Comment (petermattis) [inline util/encoding/key_encoding.go]: You're correct, the zero-padding for two digit exponents is not mentioned in the docs. I've adjusted this to be `len(b) < 4` and enhanced the comment.

**Comment by spencerkimball** [comment]
LGTM
