### PR TITLE
sqlstats: fix sampling logic for first recording of a statement

### LINKED ISSUE #123690: sqlstats: exec stats are always sampled when writing to sql stats is throttled
Exec stats are probabilistically sampled according to `sql.txn_stats.sample_rate` (default 1%).
However, if the current sql stats container for the application has never recorded the statement fingerprint, we will also decide to collect exec stats. See:
https://github.com/cockroachdb/cockroach/blob/6f998c90fef64c5ca4478d10970b2152819f9d55/pkg/sql/instrumentation.go#L478-L482
We do not account for the fact that when we stop writing to the container due to max capacity, `previouslySampled` in the above linked code will always be false. This means that once we reach sql stats container capacities, we will always sample fingerprints that aren't already in the stats container.

We should also check if the container has reached max capacity in addition to the last sampled time.

Jira issue: CRDB-38473

Epic CRDB-37544

### PR DESCRIPTION
**Pull request by xinhaoz**
By default we sample execution stats for 1% of statements,
(`sql.txn_stats.sample_rate`). We also turn on sampling if
this is the first time we're recording this fingerprint in the
application container. This 'sample on first encounter' logic did
not factor in the scenario where we may be unable to write new
fingerprints due to reaching max container capacities. Previously,
this meant that once the containers were full we'd begin to trace
every fingerprint that did not already get recorded.

This commit ensures that we also check the capacity when deciding
to sample a fingerprint we haven't recorded yet, skipping the sampling
if it is full.  Note that although the container may reach capacity
during the statement's execution, it's more important that we stop sampling
once we are sure the fingerprint cannot be written to the container.

Fixes: https://github.com/cockroachdb/cockroach/issues/123690

Release note: None

### CODE REVIEW

**Comment by xinhaoz** [comment]
need to add testing

File: pkg/sql/instrumentation.go [hunk 1]
```diff
@@ -470,20 +470,20 @@ func (ih *instrumentationHelper) Setup(
 		}
 	}
 
-	ih.collectExecStats = collectTxnExecStats
-
-	// Don't collect it if Stats Collection is disabled. If it is disabled the
-	// stats are not stored, so it always returns false for previouslySampled.
-	// TODO(117690): Unify StmtStatsEnable and TxnStatsEnable into a single cluster setting.
```
Comment (dhartunian) [inline pkg/sql/instrumentation.go:477]: Should this TODO get deleted?

File: pkg/sql/instrumentation.go [hunk 2]
```diff
@@ -470,20 +470,20 @@ func (ih *instrumentationHelper) Setup(
...
-		statsCollectionDisabled := collectTxnStatsSampleRate.Get(&cfg.Settings.SV) == 0
-		ih.collectExecStats = !statsCollectionDisabled
+	shouldSampleFirstEncounter := func() bool {
+		// If this is the first time we see this statement in the current stats
+		// container, we'll collect its execution stats anyway (unless the user
+		// disabled txn or stmt stats collection entirely). However, we don't want
+		// to collect the stats if the stats container is full, since previouslySampled
+		// will always return false for statements not already in the container.
+		statsCollectionEnabled := collectTxnStatsSampleRate.Get(&cfg.Settings.SV) > 0
+		limitReached := statsCollector.StatementsContainerFull()
```
Comment (dhartunian) [inline pkg/sql/instrumentation.go:480]: I'm a little confused about how `limitReached` is supposed to affect `ih.collectExecStats`. If we're at the limit shouldn't we override `collectTxnExecStats` if it's set to `true`? Or is the assumption that it's set to true only if it's a collected fingerprint already?

Comment (xinhaoz) [reply pkg/sql/instrumentation.go:480]: There's no assumption of that sort here. We're using `limitReached` specifically just to correct the case where we want to override `collectTxnExecStats` because the container hasn't recorded this fingerprint yet since if it's full it'll never insert this new fingerprint. `collectTxnExecStats` could be set for a statement that's in or not in the container.

If we'd prefer to only set `collectTxnExecStats` for statements in the container, we can investigate the implications of that. The only reason I didn't pursue that is I'm not sure if this sampling logic could be used outside of sql stats for any other reporting / metrics.

File: pkg/sql/instrumentation.go (hunk 1 above)
Comment (xinhaoz) [reply pkg/sql/instrumentation.go:477]: Oops, I'll put this back. It still looks relevant.

**Review by abarganier — APPROVED** [review]
Looks like this will fix the bug, :lgtm:.

I have a small readability nit, feel free to take it or leave it.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/123696#-:-NxYEix23VxQL2q1CcV4:b-sy44t8)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @dhartunian and @xinhaoz)

___
*[`pkg/sql/instrumentation.go` line 473 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/123696#-NxYAg_dDIIF8EDgfA-K:-NxYAg_dDIIF8EDgfA-L:b71m5me) ([raw file](https://github.com/cockroachdb/cockroach/blob/6abc367f91f82eb3286f624274278ef1d526f0c7/pkg/sql/instrumentation.go#L473)):*
> ```Go
> 	}
> 
> 	shouldSampleFirstEncounter := func() bool {
> ```

nit: The checks here LGTM, but can we make this more readable with some early returns? 

For example, it seems like if `statsCollectionEnabled == false`, or `limitReached == false`, we'll never indicate that we should sample. So, we can return early in those cases. It would help simplify the conditional. `&&`ing many things together is the same in practice, but can be more difficult for readers to wrap their head around. 

As a small bonus, it speeds things up a tiny bit by avoiding unnecessary reads of cluster settings/atomic ints/etc when we already know the answer based on a single variable.

Factoring this into a function was a great idea for readability, nice work.



_Code quote:_
```Go
	shouldSampleFirstEncounter := func() bool {
```
___
*[`pkg/sql/instrumentation.go` line 480 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/123696#gh-1596029237:-NxYDeUh62OiPDPKeU2I:b-26qrjy) ([raw file](https://github.com/cockroachdb/cockroach/blob/6abc367f91f82eb3286f624274278ef1d526f0c7/pkg/sql/instrumentation.go#L480)):*
> ih.collectExecStats = collectTxnExecStats || shouldSampleFirstEncounter()

Giving precedence to `collectTxnExecStats` makes sense to me. We defer to probabilistic sampling. If our sample rate didn't choose this txn for sampling, then we check `shouldSampleFirstEncounter()` to see if we should sample anyway, based on the criteria defined within that function (which protects against the bug being solved here).

**Comment by xinhaoz** [comment]
TFTR! Cleaned up and split the conditional.
bors r+
