### PR TITLE
allocator: fix incorrect rebalance signal and target

### LINKED ISSUE #42715: sql: localities can't be changed seamlessly if there are replica constraints
A user had the following locality hierarchy:

`continent, region`

The user had leaseholder preferences bound to regions, and replica constraints bound to continents.

The user wished to migrate the continent key to a different name, and decided to do this by restarting all nodes with another locality pair (we'll call it `continent2`). So, the new hierarchy was:

`continent2, continent, region`

When the user restarted, the cluster experienced leaseholder thrashing. The current hypothesis is that this is because the replica constraints don't apply since `continent` is no longer the top level locality.

Whatever the reason, this is not the best experience for a user. We should make it possible to do more locality changes online here.

### PR DESCRIPTION
**Pull request by darinpp**
This change fixes two bugs:
- The first bug is related to the comparison of floating point
numbers when considering to rebalance a range. The diversity score
of two identical ranges (even the same range) may differ by a small
amount. The fix is to consider candidates equal if their diversity score
have very close values (within 1e-10).
- The second bug has been introduced with
https://github.com/cockroachdb/cockroach/pull/39157 and resulted in
ignoring the newly added replica when determining what existing replica
it should replace in Allocator.simulateRemoveTarget.
As a result - when the first bug was triggering and unnecessary
rebalancing was happening - the replica to be dropped was chosen
at random (in the case where all existing replica are necessary).
For example - let's say a range is constrained to have a replica in each
of the regions A,B,C. We are trying to add a new replica in C.
Evaluating what should be removed from the A,B,C may choose any one of them.
If the choice is A or B, the constraint will be violated.
If we however ask the same question for A,B,C(old),C(new) - the result
will be C(old) as this will preserve the constraint (to have one
replica in each region).

Fixes #42715
Fixes https://github.com/cockroachlabs/support/issues/348

Release note (bug fix): the allocator now considers stores with very close
diversity scores equal (all other things being the same) and doesn't attempt
to rebalance.
Release note (bug fix): the allocator considers the new store being added
when looking for target in case of rebalance.

### CODE REVIEW

File: pkg/storage/allocator_scorer.go [hunk 1]
```diff
@@ -162,7 +164,7 @@ func (c candidate) compare(o candidate) float64 {
 		}
 		return -4
 	}
-	if c.diversityScore != o.diversityScore {
+	if math.Abs(c.diversityScore-o.diversityScore) > epsilon {
```
Comment (andy-kimball) [inline pkg/storage/allocator_scorer.go]: I think you should create a helper function like `compareDiversityScores` to encapsulate this and provide more clarity to those reading the code.

Comment (darinpp) [reply pkg/storage/allocator_scorer.go]: This isn't the only case where we compare doubles. It isn't feasible to have helper function for double field. I prefer a system wide helper function (as I've done on multiple occasions in the past) but wasn't sure where to put it.

Comment (andy-kimball) [reply pkg/storage/allocator_scorer.go]: I'm not sure either, but regardless, I'd just add a tiny function at bottom of this file:
```
func scoresAlmostEqual(val1, val2 double) bool {
  return math.Abs(val1-val2) <= epsilon
}
```
Trying to create some general, system-wide function is over-kill IMO, especially since you want this function to use a particular epsilon appropriate for this particular case.

Comment (darinpp) [reply pkg/storage/allocator_scorer.go]: OK, done.

**Review by nvb — COMMENTED** [review]
> Reviewed 3 of 4 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/43041)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andy-kimball and @darinpp)

___
*[pkg/storage/allocator.go, line 704 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/43041#-LvW_2p77_wITE9cygsJ:-LvW_2p89_8IAUGX-enx:ba3ui1u) ([raw file](https://github.com/cockroachdb/cockroach/blob/5ab27748e4e9d56e2d771cffdb35eef3de056093/pkg/storage/allocator.go#L704)):*
> ```Go
> 		existingPlusOneNew := append([]roachpb.ReplicaDescriptor(nil), existingReplicas...)
> 		existingPlusOneNew = append(existingPlusOneNew, newReplica)
> 		replicaCandidates := append([]roachpb.ReplicaDescriptor(nil), existingPlusOneNew...)
> ```

Do we need to make a copy here? `simulateFilterUnremovableReplicas` seems to copy-on-write already.
___
*[pkg/storage/allocator_scorer.go, line 167 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/43041#-LvSjkt3GIi-GVtAKb2O-r1-167:-LvW_yWP1iLirTf_QlQ4:bn3oc44) ([raw file](https://github.com/cockroachdb/cockroach/blob/b8c2f5bad1a8bf452a5bf70a61f6460145a05974/pkg/storage/allocator_scorer.go#L167)):*
<details><summary><i>Previously, darinpp wrote…</i></summary><blockquote>

OK, done.
</blockquote></details>

Do you think it's worth being a little more aggressive and fully preventing misguided comparison of these float vals? Something like:

```
type impreciseFloat64 struct {
    f float64
}

func (a impreciseFloat64) Equal(b impreciseFloat64) bool {
    ...
}

func (a impreciseFloat64) Less(b impreciseFloat64) bool {
    ...
}
```

I worry that we could be missing a use of `scoresAlmostEqual` now, and even if we're not, I'm concerned that we might in the future.
___
*[pkg/storage/allocator_scorer.go, line 29 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/43041#-LvW_TIxESNMac3S-P5x:-LvW_TIxESNMac3S-P5y:b5c1wb9) ([raw file](https://github.com/cockroachdb/cockroach/blob/5ab27748e4e9d56e2d771cffdb35eef3de056093/pkg/storage/allocator_scorer.go#L29)):*
> ```Go
> 
> const (
> 	epsilon = 1e-10
> ```

Give this a comment.

Also, how did you pick this?
___
*[pkg/storage/allocator_scorer_test.go, line 248 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/43041#-LvWap7L6ul9Ud2gwgZe:-LvWap7L6ul9Ud2gwgZf:b-5o2zc9) ([raw file](https://github.com/cockroachdb/cockroach/blob/5ab27748e4e9d56e2d771cffdb35eef3de056093/pkg/storage/allocator_scorer_test.go#L248)):*
> ```Go
> 		{
> 			valid:          true,
> 			diversityScore: math.Nextafter(1, 0),
> ```

Could you give this a comment?
___
*[pkg/storage/allocator_test.go, line 884 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/43041#-LvWax8z5KD-XTjio4vm:-LvWax8z5KD-XTjio4vn:b-2ka3o) ([raw file](https://github.com/cockroachdb/cockroach/blob/5ab27748e4e9d56e2d771cffdb35eef3de056093/pkg/storage/allocator_test.go#L884)):*
> ```Go
> 		)
> 		expTo := stores[1].StoreID
> 		expFrom := map[roachpb.StoreID]bool{stores[0].StoreID: true}
> ```

We can do a direct comparison now instead of this "valid set" business.

**Review by darinpp — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/43041)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andy-kimball and @nvanbenschoten)

___
*[pkg/storage/allocator.go, line 704 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/43041#-LvW_2p77_wITE9cygsJ:-Lvd1Qq70SNjSLdsQ1m3:bt2vr1b) ([raw file](https://github.com/cockroachdb/cockroach/blob/5ab27748e4e9d56e2d771cffdb35eef3de056093/pkg/storage/allocator.go#L704)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Do we need to make a copy here? `simulateFilterUnremovableReplicas` seems to copy-on-write already.
</blockquote></details>

Fixed.
___
*[pkg/storage/allocator_scorer.go, line 167 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/43041#-LvSjkt3GIi-GVtAKb2O-r1-167:-Lvd2V0PDGip7HUpx_7M:b-oidhi6) ([raw file](https://github.com/cockroachdb/cockroach/blob/b8c2f5bad1a8bf452a5bf70a61f6460145a05974/pkg/storage/allocator_scorer.go#L167)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Do you think it's worth being a little more aggressive and fully preventing misguided comparison of these float vals? Something like:

```
type impreciseFloat64 struct {
    f float64
}

func (a impreciseFloat64) Equal(b impreciseFloat64) bool {
    ...
}

func (a impreciseFloat64) Less(b impreciseFloat64) bool {
    ...
}
```

I worry that we could be missing a use of `scoresAlmostEqual` now, and even if we're not, I'm concerned that we might in the future.
</blockquote></details>

I don't think we should do this. `impreciseFloat64` is a bit redundant. The float64 by its very nature has a limited precision so some numbers can't be represented exactly. Every single place in the code where we have float64 == float64 could have this problem. I feel that it would make more sense to discuss perhaps the floating point formats and the operations so people are more aware of what should they expect as a result.
___
*[pkg/storage/allocator_scorer.go, line 29 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/43041#-LvW_TIxESNMac3S-P5x:-Lvd1TNP7RoCLk-Mr4LV:b-tyiduw) ([raw file](https://github.com/cockroachdb/cockroach/blob/5ab27748e4e9d56e2d771cffdb35eef3de056093/pkg/storage/allocator_scorer.go#L29)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Give this a comment.

Also, how did you pick this?
</blockquote></details>

I added a comment. There isn't anything special about the exact value that is here. It could be lower or higher but it has to be hight enough to allow for loss of accuracy related to whatever operations are done on the floating point numbers (which are with a certain precision) and at the same time low enough to make sense when comparing two numbers for equality.
___
*[pkg/storage/allocator_scorer_test.go, line 248 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/43041#-LvWap7L6ul9Ud2gwgZe:-Lvd80mI7EIvf8wFJeCQ:byrpbkq) ([raw file](https://github.com/cockroachdb/cockroach/blob/5ab27748e4e9d56e2d771cffdb35eef3de056093/pkg/storage/allocator_scorer_test.go#L248)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Could you give this a comment?
</blockquote></details>

I changed this one to a const but put a larger comment on one of the other ones. 
___
*[pkg/storage/allocator_test.go, line 884 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/43041#-LvWax8z5KD-XTjio4vm:-Lvd86Lh8X_voa1rp5Tp:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/5ab27748e4e9d56e2d771cffdb35eef3de056093/pkg/storage/allocator_test.go#L884)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

We can do a direct comparison now instead of this "valid set" business.
</blockquote></details>

Done.

**Review by nvb — APPROVED** [review]
:lgtm:

> Reviewed 4 of 4 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/43041#-:-LvgJgUo4qovZCw7oJgn:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @andy-kimball and @darinpp)

___
*[pkg/storage/allocator_scorer.go, line 167 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/43041#-LvSjkt3GIi-GVtAKb2O-r1-167:-LvgJXEP86ZCk303WZPP:bb6sh2i) ([raw file](https://github.com/cockroachdb/cockroach/blob/b8c2f5bad1a8bf452a5bf70a61f6460145a05974/pkg/storage/allocator_scorer.go#L167)):*
<details><summary><i>Previously, darinpp wrote…</i></summary><blockquote>

I don't think we should do this. `impreciseFloat64` is a bit redundant. The float64 by its very nature has a limited precision so some numbers can't be represented exactly. Every single place in the code where we have float64 == float64 could have this problem. I feel that it would make more sense to discuss perhaps the floating point formats and the operations so people are more aware of what should they expect as a result.
</blockquote></details>

Ack.
___
*[pkg/storage/allocator_scorer_test.go, line 119 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/43041#-LvgJZSe6YM93B1-BJSh:-LvgJZSe6YM93B1-BJSi:b-sych13) ([raw file](https://github.com/cockroachdb/cockroach/blob/4475b297079f93dc75fa08fbaa7ba3a93d539d44/pkg/storage/allocator_scorer_test.go#L119)):*
> ```Go
> 					StoreID: roachpb.StoreID(i + idShift),
> 				},
> 				// We want to test here that everything works when the deversity score
> ```

s/deversity/diversity/

File: pkg/storage/allocator_scorer.go [hunk 2]
```diff
@@ -26,6 +26,17 @@ import (
...
+	// This is a somehow arbitrary chosen upper bound on the relative error to be
+	// used when comparing doubles for equality. The assumption that comes with it
+	// is that any sequence of operations on doubles won't produce a result with
+	// accuracy that is worse than this relative error. There is no guarantee
+	// however that this will be the case. A programmer writing code using
+	// floating point numbers will still need to be aware of the effect of the
+	// operations on the results and the possible loss of accuracy.
+	// More info https://en.wikipedia.org/wiki/Machine_epsilon
+	// https://en.wikipedia.org/wiki/Floating-point_arithmetic
+	epsilon = 1e-10
```
Comment (bdarnell) [inline pkg/storage/allocator_scorer.go]: We already have `kv.allocator.range_rebalance_threshold` which is supposed to prevent rebalancing unless there is a 5% difference. Why are we introducing a new magic number instead of reusing that threshold here?

How safe is this number of `1e-10`? The numbers we work with here are often 5 or 6 digits (e.g. number of ranges per node), so I'd be concerned about `1e-10` being smaller than the kinds of rounding errors we could see. I think it would be better to have a much larger cutoff (or better, something proportional to the actual values instead of a constant).

File: pkg/storage/allocator_scorer.go [hunk 3]
```diff
@@ -238,9 +249,9 @@ var _ sort.Interface = byScoreAndID(nil)
 
 func (c byScoreAndID) Len() int { return len(c) }
 func (c byScoreAndID) Less(i, j int) bool {
-	if c[i].diversityScore == c[j].diversityScore &&
+	if scoresAlmostEqual(c[i].diversityScore, c[j].diversityScore) &&
```
Comment (bdarnell) [inline pkg/storage/allocator_scorer.go]: An inconsistent `Less` function could cause all kinds of chaos. Is there any risk of floating-point math causing problems here? I think it might be better to sort things according to the raw float values, then apply the filter at the end so we won't swap to a node that is not a sufficient improvement.
