### PR TITLE
util/log: log nothing to stderr by default

### LINKED ISSUE #5962: "./cockroach start" logs unknown errors
localhost:

1. What version of CockroachDB are you using (`cockroach version`)?

./cockroach version
Build Vers:  go1.6
Build Tag:   beta-20160330
Build Time:  2016/03/30 14:53:35

2. What operating system and processor architecture are you using?

uname -a
Linux localhost.localdomain 3.10.0-327.13.1.el7.x86_64 #1 SMP Thu Mar 31 16:04:38 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

cat /etc/centos-release
CentOS Linux release 7.2.1511 (Core)

3. What flags/environment variables did you pass to `cockroach start`?

nothing

Please describe the issue you observed:

1. What did you do?

./cockroach start

2. What did you expect to see?

info output

3. What did you see instead?

error output:

`E160409 10:22:21.320101 storage/queue.go:511  [replicate] 13 replicas failing with "0 of 1 store with an attribute matching []
`

### LINKED ISSUE #5964: cli: Don't log to stderr by default
When we discussed showing log files in the web UI, everyone in the room recoiled from the idea of showing our raw (or lightly-filtered) logs that prominently. And yet that's exactly what we do when you start a node in the terminal. This gives a bad first impression (most notably with the "no replication targets available" message, although I'm sure there are others). 

Stderr is a part of the app's UI and we should treat it as such. Instead of routing our internal log messages there, the messages that show up on stderr by default should be those from the admin UI's events tab, which are designed for human consumption.

More radically, if stderr is a tty and not just a pipe or file, we could do something more useful than just a log of messages. We could start the SQL shell, or maybe have a curses-based display of some information from the web UI.

### PR DESCRIPTION
**Pull request by petermattis**
Fixes #5962.
Fixes #5964.

---

This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/5979)

### CODE REVIEW

File: util/log/clog.go [hunk 1]
```diff
@@ -586,7 +586,7 @@ func formatLogEntry(entry Entry, stacks []byte, colors *colorProfile) *buffer {
 
 func init() {
 	// Default stderrThreshold to errors and above.
```
Comment (tschottdorf) [inline util/log/clog.go]: stale comment.

**Comment by tschottdorf** [comment]
LGTM

**Comment by bdarnell** [comment]
LGTM
