### PR TITLE
sql/schemachanger: use force puts when writing to new primary indexes

### LINKED ISSUE #98130: Duplicate key when adding computed column to an existing table
**Describe the problem**

In a table with ~2,000,000 rows, the following alter statement results in a duplicate key error:

```sql
ALTER TABLE account
ADD COLUMN overdrawn BOOL AS (amount < 0) STORED;
```

> ERROR: duplicate key value violates unique constraint "account_pkey" (SQLSTATE 23505)

**To Reproduce**

Using code from [this gist](https://gist.github.com/codingconcepts/d4062bd800bb680ed1849a24f5b28e4a), run the following:

### Tools required to reproduce

* **CockroachDB** v22.2.6
* **Benthos** v4.11.0
* **Make** v3.81

### Steps to reproduce

1. Start a single node (the issue occurs with multi-node clusters too):
```
make node
```

2. Create the database:
```
make create
```

3. Generate some data:
```
make data
```

4. Run a little application (this is where the error will be reported):
```
make app
```

5. Perform the schema migration:
```
make alter
```

If the error doesn't present, run step 3 again to add more data to the database.

**Expected behavior**
A computed column is added to the table, with values calculated from the `amount` column. No errors.

Jira issue: CRDB-25093

### PR DESCRIPTION
**Pull request by fqazi**
Previously, when primary indexes where swapped for adding new columns, we would use conditional puts for updates. This was problematic because when computing the expected values for the new primary index we didn't include the new column, since its not readable yet. To address this, this patch uses force puts updating new primary indexes as a result of added / dropped columns, since there is no risk of key duplication.

Additionally, extend our testing to cover IUD during ADD/DROP COLUMN.

Fixes: #98130

Release note (bug fix): If an UPDATE was performed during an on-going ADD/DROP column change on a table, the update could incorrectly fail due to a duplicate key error.

### CODE REVIEW

**Comment by fqazi** [comment]
Originally the end-to-end tests had rows inserted first, but a declarative schema changer bug during restore causes the jobs to fail after the restore (linked to indexes backed up mid-schema change). I'll get an issue and another PR for that problem once its better understood.

File: pkg/sql/catalog/tabledesc/mutation.go [hunk 1]
```diff
@@ -446,3 +450,28 @@ func newMutationCache(desc *descpb.TableDescriptor) *mutationCache {
...
+	}
+
+	if index.GetEncodingType() != catenumpb.PrimaryIndexEncoding {
+		return false
+	}
+	// If we are adding primary indexes with new columns (same key), then
+	// we should also force puts. Attempting conditional puts for UPDATE's
+	// can end badly since we need to compute the expected value with the
+	// new columns.
+	return catalog.MakeTableColSet(tableDesc.PrimaryIndex.KeyColumnIDs...).Difference(
```
Comment (ajwerner) [inline pkg/sql/catalog/tabledesc/mutation.go:475]: Expose `Equals` in the `TableColSet` and use it. This will be true for an index which has more columns as the primary key

**Review by ajwerner — COMMENTED** [review]
The power of the testing framework is manifest in this change. Mostly looks good, but I think you do want an `Equals`.

**Review by ajwerner — APPROVED** [review]
:lgtm:

> Reviewed 2 of 36 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/98354#-:-NQCAZ1bDERRIrRUwXmo:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @fqazi)

___
*[`pkg/sql/catalog/table_col_set.go` line 75 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/98354#-NQCA7lT2dncCLKOP2Dg:-NQCA7lUCYCdZHPPKMnO:b-cn9ou8) ([raw file](https://github.com/cockroachdb/cockroach/blob/abe94ee5d20c068f0157d7fdbabe8c5edc3219a2/pkg/sql/catalog/table_col_set.go#L75)):*
> ```Go
> 
> // Equal returns the column IDs in s are equal to the ones in other.
> func (s TableColSet) Equal(other TableColSet) bool {
> ```

nit: call this `Equals` to maintain the symmetry
___
*[`pkg/sql/catalog/tabledesc/mutation.go` line 475 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/98354#-NQCAH761ChDFxp5FIH1:-NQCAH761ChDFxp5FIH2:b21w656) ([raw file](https://github.com/cockroachdb/cockroach/blob/abe94ee5d20c068f0157d7fdbabe8c5edc3219a2/pkg/sql/catalog/tabledesc/mutation.go#L475)):*
> ```Go
> 	// can end badly since we need to compute the expected value with the
> 	// new columns.
> 	return catalog.MakeTableColSet(tableDesc.PrimaryIndex.KeyColumnIDs...).Equal(
> ```

nit: I think this would read more cleanly and be more compact if written as an `index.GetEncodingType() != catenumpb.PrimaryIndexEncoding &&` rather than the statement above

**Review by fqazi — COMMENTED** [review]
@ajwerner TFTR!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/98354#-:-NQCPukG5EZuV7czFj9G:b-gz014k)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @ajwerner)

___
*[`pkg/sql/catalog/tabledesc/mutation.go` line 475 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/98354#-NQ7ZFrZJcsnnB47ABTg-r1-475:-NQCPtr79dFsyH3_tYWi:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/e2aa66be732bcb2fffef952ec23b451833f3ad55/pkg/sql/catalog/tabledesc/mutation.go#L475)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

Expose `Equals` in the `TableColSet` and use it. This will be true for an index which has more columns as the primary key 
</blockquote></details>

Done.
