### PR TITLE
sql: remove extra type hint from `SHOW CREATE VIEW`

### LINKED ISSUE #87886: SHOW CREATE VIEW adds extra type hint for empty array constructor
**Describe the problem**

`SHOW CREATE VIEW` adds an extra type hint for empty array constructors. This makes the SQL not round-trip, since each trip will add an additional type hint.

**To Reproduce**

```
demo@127.0.0.1:26257/movr> CREATE VIEW abc AS SELECT ARRAY[]:::STRING[];
CREATE VIEW


Time: 4ms total (execution 3ms / network 0ms)

demo@127.0.0.1:26257/movr> SHOW CREATE VIEW abc;
  table_name |             create_statement
-------------+--------------------------------------------
  abc        | CREATE VIEW public.abc (
             |     "array"
             | ) AS SELECT ARRAY[]:::STRING[]:::STRING[]
(1 row)


Time: 6ms total (execution 6ms / network 0ms)
```

**Environment:**
 - CockroachDB v22.1.6

Jira issue: CRDB-19579
Epic CRDB-17785

### PR DESCRIPTION
**Pull request by e-mbrown**
Resolves: #87886

Views created with user provided type hints were given
extra type annotations. The format functions for `AnnotateTypeExpr`
and `Array` were both annotating the expression. This commit alters
the format function of `AnnotateTypeExpr` so it doesnt duplicate
annotations for arrays.

Release note: None

### CODE REVIEW

File: pkg/sql/logictest/testdata/logic_test/views [hunk 1]
```diff
@@ -140,6 +140,27 @@ CREATE DATABASE test2
...
+              "array"
+            ) AS SELECT ARRAY[]::STRING[]:::STRING[]
+
+query TT colnames
+SHOW CREATE VIEW t2
+----
+table_name  create_statement
+t2          CREATE VIEW public.t2 (
+              "array"
+            ) AS SELECT ARRAY[1:::INT8, 2:::INT8, 3:::INT8]::INT8[]:::INT8[]
```
Comment (rafiss) [inline pkg/sql/logictest/testdata/logic_test/views:162]: it looks like this still has an extra `:::INT8[]` type annotation at the end. (and same for `t1` above this)

File: pkg/sql/sem/tree/expr.go [hunk 2]
```diff
@@ -885,7 +885,7 @@ func (node *Array) Format(ctx *FmtCtx) {
 	// UNKNOWN[], since that's not a valid annotation.
 	if ctx.HasFlags(FmtParsable) && node.typ != nil {
 		if node.typ.ArrayContents().Family() != types.UnknownFamily {
-			ctx.WriteString(":::")
+			ctx.WriteString("::")
```
Comment (rafiss) [inline pkg/sql/sem/tree/expr.go:888]: i'm wondering if what we need is to keep track of whether there already was a type annotation wrapping the `Array` expr. or alternatively, update `AnnotateTypeExpr.Format` so it doesn't print the annotation if the inner expr already is going to

**Review by e-mbrown — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/95679)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rafiss)

___
*[`pkg/sql/sem/tree/expr.go` line 888 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/95679#-NMUAkalea9-iLLn-zbF-r1-888:-NNc9urV1HrLq7FJ0_NY:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/f18ef3a9bfb461fe0194356cd4ebdbee79aa8f8d/pkg/sql/sem/tree/expr.go#L888)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

i'm wondering if what we need is to keep track of whether there already was a type annotation wrapping the `Array` expr. or alternatively, update `AnnotateTypeExpr.Format` so it doesn't print the annotation if the inner expr already is going to
</blockquote></details>

Done.
___
*[`pkg/sql/logictest/testdata/logic_test/views` line 162 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/95679#-NMUAkalea9-iLLn-zbE-r1-162:-NNc9suC4mypbtkcA6PM:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/f18ef3a9bfb461fe0194356cd4ebdbee79aa8f8d/pkg/sql/logictest/testdata/logic_test/views#L162)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

it looks like this still has an extra `:::INT8[]` type annotation at the end. (and same for `t1` above this)
</blockquote></details>

Done.

File: pkg/sql/sem/tree/expr.go [hunk 3]
```diff
@@ -884,7 +884,7 @@ func (node *Array) Format(ctx *FmtCtx) {
 	// If the array has a type, add an annotation. Don't add it if the type is
 	// UNKNOWN[], since that's not a valid annotation.
 	if ctx.HasFlags(FmtParsable) && node.typ != nil {
-		if node.typ.ArrayContents().Family() != types.UnknownFamily {
+		if node.typ.ArrayContents().Family() != types.UnknownFamily && node.typeAnnotation.typ == nil {
```
Comment (rafiss) [inline pkg/sql/sem/tree/expr.go:887]: to summarize what we discussed offline: `node.typ` and `node.typeAnnotation.typ` refer to the same thing, so this change doesn't have the intended affect.

perhaps instead our approach should be to update `formatViewQueryForDisplay` to detect when an annotation would be duplicated, and prevent that.

**Review by rafiss — CHANGES_REQUESTED** [review]

**Review by rafiss — APPROVED** [review]
nice work!

**Comment by e-mbrown** [comment]
Woo!

bors r=rafiss
