### PR TITLE
sql: fix telemetry test flake

### LINKED ISSUE #69284: sql: TestTelemetry failed
sql.TestTelemetry [failed](https://teamcity.cockroachdb.com/viewLog.html?buildId=3345544&tab=buildLog) with [artifacts](https://teamcity.cockroachdb.com/viewLog.html?buildId=3345544&tab=artifacts#/) on master @ [46cef2c6f0b36ba2f7d551c8ab017832c1b9d592](https://github.com/cockroachdb/cockroach/commits/46cef2c6f0b36ba2f7d551c8ab017832c1b9d592):

```
=== RUN   TestTelemetry
    test_log_scope.go:73: test logs captured to: /go/src/github.com/cockroachdb/cockroach/artifacts/logTestTelemetry141329993
    test_log_scope.go:74: use -show-logs to present logs inline
=== CONT  TestTelemetry
    telemetry_test.go:45: -- test log scope end --
test logs left over in: /go/src/github.com/cockroachdb/cockroach/artifacts/logTestTelemetry141329993
--- FAIL: TestTelemetry (20.87s)
=== RUN   TestTelemetry/planning/server
    telemetry.go:91: 
        testdata/telemetry/planning:222: SELECT EXISTS(SELECT * FROM generate_series(1,2))
        expected:
        sql.plan.opt.node.project-set
        
        found:
        sql.plan.opt.node.join.algo.lookup
        sql.plan.opt.node.join.type.inner
        sql.plan.opt.node.project-set
        --- FAIL: TestTelemetry/planning/server (0.91s)
=== RUN   TestTelemetry/planning
    --- FAIL: TestTelemetry/planning (1.20s)
```
<details><summary>Reproduce</summary>
<p>
To reproduce, try:

```bash
make stressrace TESTS=TestTelemetry PKG=./pkg/sql TESTTIMEOUT=5m STRESSFLAGS='-timeout 5m' 2>&1
```
Parameters in this failure:

- GOFLAGS=-parallel=4
</p>
</details>
/cc @cockroachdb/sql-queries RaduBerinde
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*TestTelemetry.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)
</sub>

### PR DESCRIPTION
**Pull request by RaduBerinde**
I have not been able to repro the flakiness but I'm hoping this fixes it.

#### sql: fix telemetry test flake

TestTelemetry sometimes flakes with extra lookup and inner join
counters. This is probably due to a new internal background query
(though note that if that's the case, the value of those counters
existing in the first place is dubious).

This change modifies the test to have more specific feature
allow-lists.

Fixes #69284.

Release note: None

Release justification: test-only change.

### CODE REVIEW

**Review by rytaft — COMMENTED** [review]
You could also just update the test file to reduce the allowlist to only `sql.plan.opt.node.project-set` for the flaky test.

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/69550#-:-MiI8Gw69Faa-_NQzE2I:b7iqa2d)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @otan)

**Comment by otan** [comment]
the allow list doesn't sound like a bad idea, hehe

**Comment by RaduBerinde** [comment]
I saw a couple different flaky tests, I will have to hunt them down. In fact, it probably means all tests will need to have a tight allow list (making it impossible to test that a statement does *not* set other counters incorrectly).

File: pkg/sql/sqltestutils/telemetry.go [hunk 1]
```diff
@@ -212,37 +212,49 @@ func (tt *telemetryTest) RunTest(
...
-				// Ignore zero values (shouldn't happen in practice)
-				continue
-			}
-			if !tt.allowlist.Match(k) {
-				// Feature key not in allowlist.
-				continue
+		// Internal background queries can set telemetry counters. Retry for a few
+		// times and stop when we get the expected result.
+		const retries = 10
+		expected := strings.TrimSpace(td.Expected)
```
Comment (otan) [inline pkg/sql/sqltestutils/telemetry.go:224]: we have to detect this in a `-rewrite` to stop it retrying 10 times no?

**Review by otan — COMMENTED** [review]
i guess my fear with retrying is that, e.g., a test can assert telemetry only fires once for a particular statement, but if we retry then the telemetry key may appear multiple times.

**Comment by RaduBerinde** [comment]
But the keys get cleared every time we retrieve them..

File: pkg/sql/sqltestutils/telemetry.go (hunk 1 above)
Comment (RaduBerinde) [reply pkg/sql/sqltestutils/telemetry.go:224]: I don't see a big problem, we will choose the output of the last run.

**Comment by otan** [comment]
ah, i mean, e.g. we only log the first instance of CREATE USER, but never again because, e.g. the user is already created.

can you confirm `go test ./pkg/sql -run TestTelemetry -rewrite` doesn't rewrite anything right now?

**Comment by RaduBerinde** [comment]
Oh, that's interesting, I haven't considered that.

Another option is to hardcode an ignore list of "spurious" metrics.

**Comment by RaduBerinde** [comment]
Updated with @rytaft's suggestion, indeed it's much easier and cleaner.

**Review by otan — APPROVED** [review]

**Review by rytaft — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/69550#-:-MiLyDYO2IgJ2YPkC1uZ:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @otan)
