### PR TITLE
roachtest: extend timeout for fine grained checkpointing

### LINKED ISSUE #146496: roachtest: cdc/fine-grained-checkpointing failed
roachtest.cdc/fine-grained-checkpointing [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyAzureBazel/19661503?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyAzureBazel/19661503?buildTab=artifacts#/cdc/fine-grained-checkpointing) on master @ [58f7422be6001c29dfca0311aa1d3fa723cd96f1](https://github.com/cockroachdb/cockroach/commits/58f7422be6001c29dfca0311aa1d3fa723cd96f1):

```
(test_runner.go:1400).runTest: test timed out (15m0s)
test artifacts and logs in: /artifacts/cdc/fine-grained-checkpointing/run_1
```

Parameters:
 - <code>arch=amd64</code>
 - <code>cloud=azure</code>
 - <code>coverageBuild=false</code>
 - <code>cpu=4</code>
 - <code>encrypted=false</code>
 - <code>runtimeAssertionsBuild=false</code>
 - <code>ssd=0</code>
<details><summary>Help</summary>
<p>

See: [roachtest README](https://github.com/cockroachdb/cockroach/blob/master/pkg/cmd/roachtest/README.md)

See: [How To Investigate \(internal\)](https://cockroachlabs.atlassian.net/l/c/SSSBr8c7)

_Grafana is not yet available for azure clusters_</p>
</details>
/cc @cockroachdb/cdc
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*cdc/fine-grained-checkpointing.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/bazci/githubpost/issues)

</sub>

### PR DESCRIPTION
**Pull request by aerfrei**
This test was failing on master with both timeouts and duplicates in excess of the limit. This commit removes the duplicate limit for this test and extends the timeout from 15 minutes to 30 minutes.

Epic: none
Fixes: #146496

### CODE REVIEW

File: pkg/cmd/roachtest/tests/cdc.go [hunk 1]
```diff
@@ -1388,7 +1388,7 @@ func runCDCFineGrainedCheckpointingBenchmark(
 			return fmt.Errorf("expected %d, got %d", expected, unique)
 		}
 
-		if dupes > dupeLimit {
+		if dupeLimit > 0 && dupes > dupeLimit {
```
Comment (andyyang890) [inline pkg/cmd/roachtest/tests/cdc.go:1391]: If we aren't going to use `dupeLimit`, should we just delete all the related code?

File: pkg/cmd/roachtest/tests/cdc.go [hunk 2]
```diff
@@ -1703,7 +1703,7 @@ func registerCDC(r registry.Registry) {
 		Cluster:          r.MakeClusterSpec(4),
 		CompatibleClouds: registry.AllClouds,
 		Suites:           registry.Suites(registry.Nightly),
-		Timeout:          15 * time.Minute,
+		Timeout:          30 * time.Minute,
 		Run: func(ctx context.Context, t test.Test, c cluster.Cluster) {
 			runCDCFineGrainedCheckpointingBenchmark(ctx, t, c, 1000, 500*time.Millisecond,
```
Comment (andyyang890) [inline pkg/cmd/roachtest/tests/cdc.go:1708]: Could you either make these parameters named vars or add C-style comments?

File: pkg/cmd/roachtest/tests/cdc.go [hunk 3]
```diff
@@ -1191,23 +1191,23 @@ func runCDCInitialScanRollingRestart(
 	}
 }
 
+type FineGrainedCheckpointingParams struct {
```
Comment (andyyang890) [inline pkg/cmd/roachtest/tests/cdc.go:1194]: nit: we don't need to export this struct since we're not using it outside of this package

(in go, all capitalized structs/functions are exported)

File: pkg/cmd/roachtest/tests/cdc.go [hunk 4]
```diff
@@ -1703,10 +1698,12 @@ func registerCDC(r registry.Registry) {
 		Cluster:          r.MakeClusterSpec(4),
 		CompatibleClouds: registry.AllClouds,
 		Suites:           registry.Suites(registry.Nightly),
-		Timeout:          15 * time.Minute,
+		Timeout:          30 * time.Minute,
 		Run: func(ctx context.Context, t test.Test, c cluster.Cluster) {
-			runCDCFineGrainedCheckpointingBenchmark(ctx, t, c, 1000, 500*time.Millisecond,
-				[]time.Duration{
+			runCDCFineGrainedCheckpointingBenchmark(ctx, t, c, FineGrainedCheckpointingParams{
```
Comment (andyyang890) [inline pkg/cmd/roachtest/tests/cdc.go:1703]: nice, this is much easier to read

**Review by andyyang890 — APPROVED** [review]

**Comment by aerfrei** [comment]
bors r=andyyang890
