### PR TITLE
sql: fix CITEXT formatting panic

### LINKED ISSUE #149876: roachtest: panic with CITEXT
roachtest.unoptimized-query-oracle/disable-rules=half/rand-tables [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyAzureBazel/20141915?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyAzureBazel/20141915?buildTab=artifacts#/unoptimized-query-oracle/disable-rules=half/rand-tables) on master @ [9ddf582e7c38e1b5e844b1f6dfc014ac5f8843c0](https://github.com/cockroachdb/cockroach/commits/9ddf582e7c38e1b5e844b1f6dfc014ac5f8843c0):

```
(query_comparison_util.go:419).runOneRoundQueryComparison: failed to set random seed. 1802 statements run: dial tcp 172.203.250.175:26257: connect: connection refused
test artifacts and logs in: /artifacts/unoptimized-query-oracle/disable-rules=half/rand-tables/run_1
```

Parameters:
 - <code>arch=amd64</code>
 - <code>cloud=azure</code>
 - <code>coverageBuild=false</code>
 - <code>cpu=4</code>
 - <code>encrypted=false</code>
 - <code>metamorphicBufferedSender=true</code>
 - <code>metamorphicWriteBuffering=true</code>
 - <code>runtimeAssertionsBuild=false</code>
 - <code>ssd=0</code>
<details><summary>Help</summary>
<p>

See: [roachtest README](https://github.com/cockroachdb/cockroach/blob/master/pkg/cmd/roachtest/README.md)

See: [How To Investigate \(internal\)](https://cockroachlabs.atlassian.net/l/c/SSSBr8c7)

_Grafana is not yet available for azure clusters_</p>
</details>
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*unoptimized-query-oracle/disable-rules=half/rand-tables.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/bazci/githubpost/issues)

</sub>

Jira issue: CRDB-52381

### PR DESCRIPTION
**Pull request by paulniziolek**
#### sql: fix CITEXT formatting panic

CITEXT was taking the default formatting path of `CollatedStringFamily` which formats datums with the COLLATE expression, causing a panic. This PR fixes this by separating CITEXT from the default collated string formatting path.

Fixes: cockroachdb#149876
Epic: None

Release note: None

### CODE REVIEW

File: pkg/sql/sem/tree/expr.go [hunk 1]
```diff
@@ -1522,7 +1523,8 @@ func (node *CastExpr) Format(ctx *FmtCtx) {
 		ctx.WriteString("CAST(")
 		ctx.FormatNode(node.Expr)
 		ctx.WriteString(" AS ")
-		if typ, ok := GetStaticallyKnownType(node.Type); ok && typ.Family() == types.CollatedStringFamily {
+		// CIText shouldn't get formatted the same way collated strings do.
+		if typ, ok := GetStaticallyKnownType(node.Type); ok && typ.Family() == types.CollatedStringFamily && typ.Oid() != oidext.T_citext {
```
Comment (paulniziolek) [inline pkg/sql/sem/tree/expr.go]: it would probably be more maintainable and "correct" to check if the OID is text, varchar, or any OIDs that do display COLLATE explicitly...
would it be preferred to separate this logic into some `typeDisplaysCollate` helper fn and do the above?

Comment (yuzefovich) [reply pkg/sql/sem/tree/expr.go]: I like this idea, let's extract a helper where we'd enumerate all Oids supported for the collated string family.

There are also 2 other spots in `tree/pretty.go` where we will want to use the new helper.

**Review by yuzefovich — COMMENTED** [review]
Thanks for the quick fix! Let's also add a regression test.

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/150348#-:-OVJMUK0BG7vU-ZWPLv9:b-29i14e)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @paulniziolek)

___
*[`-- commits` line 9 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/150348#-OVJL8Iy7y9k16agH_5P:-OVJL8Iy7y9k16agH_5Q:bn1sb08):*
nit: let's skip the release note since we haven't included the bug into any of the releases yet.

**Review by yuzefovich — APPROVED** [review]
I have a couple of nits, but :lgtm:

> Reviewed 2 of 3 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/150348#-:-OVJndIVCTVuM0rLRq_A:b8zjdr1)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @paulniziolek)

___
*[`pkg/sql/sem/tree/pretty.go` line 1096 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/150348#-OVJnPJD5gVEAixt-qQv:-OVJnPJD5gVEAixt-qQw:boir5e8) ([raw file](https://github.com/cockroachdb/cockroach/blob/2ac998b57bf17b20ebc88ce939fedb5f3ffe5ec3/pkg/sql/sem/tree/pretty.go#L1096)):*
> ```Go
> // typeDisplaysCollate is a helper function that returns true if the type
> // displays a COLLATE clause when formatted.
> func typeDisplaysCollate(typ *types.T) bool {
> ```

nit: let's move this method into `expr.go` file since it seems more related to expr serialization than prettification.
___
*[`pkg/sql/sem/tree/pretty.go` line 1099 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/150348#-OVJmXTx4XoD5Uri8ZVM:-OVJmXTx4XoD5Uri8ZVN:bxdbm30) ([raw file](https://github.com/cockroachdb/cockroach/blob/2ac998b57bf17b20ebc88ce939fedb5f3ffe5ec3/pkg/sql/sem/tree/pretty.go#L1099)):*
> ```Go
> 	if typ.Family() == types.CollatedStringFamily {
> 		switch typ.Oid() {
> 		case oid.T_text, oid.T_varchar, oid.T_char, oid.T_name, oid.T_bpchar:
> ```

nit: what do think about doing something like:
```
			switch typ.Oid() {
			case oid.T_text, oid.T_varchar, oid.T_char, oid.T_name, oid.T_bpchar:
				return true
			case oidext.T_citext:
				return false
			default:
				if buildutil.CrdbTestBuild {
					panic(errors.AssertionFailedf("unexpected oid %d for collated string", typ.Oid()))
				}
				return false
			}
```
This way, if we add another oid for collated strings in the future, we're less likely to forget to update this function.
