### PR TITLE
changefeedccl: support envelope=enriched for avro

### LINKED ISSUE #139657: Metadata/Enriched envelope: Implement the new envelope in avro
Generate the avro output.
Includes generating the schema and the payload (with the exception of the source subfields).
Use the work in this issue (https://github.com/cockroachdb/cockroach/issues/139655) to generate the schema.

Epic CRDB-8665
Jira issue: CRDB-46759

### PR DESCRIPTION
**Pull request by asg0451**
Add support for the enriched envelope type to avro.

Epic: CRDB-8665
Fixes: #139657

Release note (enterprise change): Add support for
the enriched envelope type to avro.

### CODE REVIEW

File: pkg/ccl/changefeedccl/encoder_avro.go [hunk 1]
```diff
@@ -256,19 +259,42 @@ func (e *confluentAvroEncoder) EncodeValue(
...
+			sourceFn := func(row cdcevent.Row) (map[string]any, error) {
+				return map[string]any{
+					"changefeed_sink": goavro.Union(avro.SchemaTypeString, "kafka"),
+				}, nil
+
+			}
+			if sourceDataSchema, err = avro.NewFunctionalRecord("source", e.schemaPrefix, fields, sourceFn); err != nil {
+				return nil, err
+			}
+		// key_only handled above, and row is not supported in avro
```
Comment (aerfrei) [inline pkg/ccl/changefeedccl/encoder_avro.go:288]: Where is key_only handled above?

File: pkg/ccl/changefeedccl/avro/avro.go [hunk 2]
```diff
@@ -55,33 +55,33 @@ import (
 // the SQL column type is embedded as metadata in the Avro field schema in a way
 // that Avro ignores it but passes it along.
 
-// schemaType is one of the set of avro primitive types.
-type schemaType interface{}
+// SchemaType is one of the set of avro primitive types.
+type SchemaType interface{}
```
[the remark this answers is not in the document]
Comment (asg0451) [reply pkg/ccl/changefeedccl/avro/avro.go:59]: They're capitalized to allow them to be used in encoder_avro.go

File: pkg/ccl/changefeedccl/encoder_avro.go (hunk 1 above)
Comment (asg0451) [reply pkg/ccl/changefeedccl/encoder_avro.go:288]: on line 207, the first in this method

**Review by aerfrei — APPROVED** [review]

**Comment by asg0451** [comment]
bors r=aerfrei
