### PR TITLE
Makefile: avoid SSE42/AVX2 in non-release builds

### LINKED ISSUE #14443: Error: exit status 2, Failed running "start"
I am getting this error on Ubuntu 16.04

cockroachdb

### PR DESCRIPTION
**Pull request by tamird**
This allows binaries built from source to run on older machines.

Closes #14443.

---
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/14466)

### CODE REVIEW

File: pkg/cli/jemalloc_unix.go [hunk 1]
```diff
@@ -0,0 +1,26 @@
...
+package cli
+
+import (
+	// This is explicit because this Go library does not export any Go symbols.
+	_ "github.com/cockroachdb/c-jemalloc"
+)
+
+// #cgo darwin LDFLAGS: -Wl,-undefined -Wl,dynamic_lookup
+// #cgo !darwin LDFLAGS: -Wl,-unresolved-symbols=ignore-all
+import "C"
```
Comment (petermattis) [inline pkg/cli/jemalloc_unix.go]: Why did you move this from `start_jemalloc.go`? That file is already protected by `!stdmalloc` which is being specified for `windows` builds.

File: pkg/storage/engine/db.cc [hunk 2]
```diff
@@ -39,6 +39,7 @@
 
 extern "C" {
 #include "_cgo_export.h"
+}
```
Comment (petermattis) [inline pkg/storage/engine/db.cc]: Please keep the `// extern "C"` comment.

**Review by petermattis — APPROVED** [review]
LGTM

**Comment by petermattis** [comment]
Perhaps we can also add some code which errors very early in the lifetime of the process if sse4.2 isn't available when we've compiled for it. RocksDB has the following code:

```
static bool isSSE42() {
#if defined(__GNUC__) && defined(__x86_64__) && !defined(IOS_CROSS_COMPILE)
  uint32_t c_;
  uint32_t d_;
  __asm__("cpuid" : "=c"(c_), "=d"(d_) : "a"(1) : "ebx");
  return c_ & (1U << 20);  // copied from CpuId.h in Folly.
#else
  return false;
#endif
}
```

**Comment by tamird** [comment]
I don't really understand this suggestion - if RocksDB has this code (and has since 2014: https://github.com/facebook/rocksdb/commit/318eace49df9ff9686dddd904473884d329fc402), (1) why is USE_SSE a thing? and (2) why do we see crashes on machines that don't support SSE?

**Comment by tamird** [comment]
Review status: 0 of 14 files reviewed at latest revision, 2 unresolved discussions.

---

*[pkg/cli/jemalloc_unix.go, line 26 at r5](https://reviewable.io:443/reviews/cockroachdb/cockroach/14466#-KgSKSXUPt8S4gAr720o-r5-26:-KgUYPeqw8-MpiDEYUnn:bwxsbwu) ([raw file](https://github.com/cockroachdb/cockroach/blob/927e266b0355056d243840db7c27e5c345fce100/pkg/cli/jemalloc_unix.go#L26)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

Why did you move this from `start_jemalloc.go`? That file is already protected by `!stdmalloc` which is being specified for `windows` builds.
</blockquote></details>

Because I'd rather reduce the amount of tribal knowledge required to compile on windows.

---

*[pkg/storage/engine/db.cc, line 42 at r5](https://reviewable.io:443/reviews/cockroachdb/cockroach/14466#-KgSKSXTHnVhzy-gcRk6-r5-42:-KgUYUjucaqd9zaSY_wZ:bjdrjnn) ([raw file](https://github.com/cockroachdb/cockroach/blob/927e266b0355056d243840db7c27e5c345fce100/pkg/storage/engine/db.cc#L42)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

Please keep the `// extern "C"` comment.
</blockquote></details>

Done, and added this comment to the equivalent place in CCL.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14466)*

**Comment by petermattis** [comment]
> I don't really understand this suggestion - if RocksDB has this code (and has since 2014: facebook/rocksdb@318eace), (1) why is USE_SSE a thing? and (2) why do we see crashes on machines that don't support SSE?

Probably because the `-msse4.2` flag allows gcc/clang to use sse4.2 instructions. The suggestion is to check whether the processor supports sse4.2 before we run any cgo code.

---

Review status: 0 of 14 files reviewed at latest revision, 2 unresolved discussions, some commit checks pending.

---

*[pkg/cli/jemalloc_unix.go, line 26 at r5](https://reviewable.io:443/reviews/cockroachdb/cockroach/14466#-KgSKSXUPt8S4gAr720o-r5-26:-KgUZW01t8HDXH544ywE:b-begjyr) ([raw file](https://github.com/cockroachdb/cockroach/blob/927e266b0355056d243840db7c27e5c345fce100/pkg/cli/jemalloc_unix.go#L26)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

Because I'd rather reduce the amount of tribal knowledge required to compile on windows.
</blockquote></details>

I'm not sure how it does that. Seems like random code movement to me.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14466#-:-KgUZabFOIs7rG_aMt5y:b-pacxe0)*

**Comment by tamird** [comment]
Thanks. I'm going to investigate upstream a little bit.

---

Review status: 0 of 14 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[pkg/cli/jemalloc_unix.go, line 26 at r5](https://reviewable.io:443/reviews/cockroachdb/cockroach/14466#-KgSKSXUPt8S4gAr720o-r5-26:-KgUlKZv0UlorrCPXGYt:borq61l) ([raw file](https://github.com/cockroachdb/cockroach/blob/927e266b0355056d243840db7c27e5c345fce100/pkg/cli/jemalloc_unix.go#L26)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

I'm not sure how it does that. Seems like random code movement to me.
</blockquote></details>

It means that windows builds do not require `stdmalloc` to avoid linker errors.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14466#-:-KgUlOk9KKwIW_fgRI4J:b-wmvze)*

**Comment by bdarnell** [comment]
USE_SSE is a thing because `crc32c.cc` needs to know whether `nmmintrin.h` is available. The ideal solution (from a compatibility perspective; I don't know if this would have a material performance impact) would be to make that header available without specifying `-msse4.2` so that `crc32c.cc` can use the optimized version (when the runtime check passes) while still using conservative code generation for the rest of the binary. 

---

Reviewed 5 of 5 files at r1, 2 of 2 files at r7, 1 of 4 files at r8, 6 of 6 files at r9.
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[Makefile, line 95 at r9](https://reviewable.io:443/reviews/cockroachdb/cockroach/14466#-KgUmdXpMGhaaf5Pnoof:-KgUmdXpMGhaaf5Pnoog:b-3970kf) ([raw file](https://github.com/cockroachdb/cockroach/blob/0a4dd30b6f8a0c4253fb7046a3f3365d194a0490/Makefile#L95)):*
> ```Makefile
> override LINKFLAGS += -X github.com/cockroachdb/cockroach/pkg/build.typ=development
> else ifeq ($(TYPE),release)
> override MFLAG = -msse -msse4.2
> ```

This will only work on amd64 architectures so it should probably have some sort of guard. (not a big deal yet, though, since we only test/support amd64)

What if a user wants to specify their own `-m` flag? It looks like the ones specified in this file will always take precedence, which is not ideal.

---

*[pkg/ccl/storageccl/engineccl/rocksdb_unix.go, line 9 at r9](https://reviewable.io:443/reviews/cockroachdb/cockroach/14466#-KgUnpLQ_mURZ-Wpyh7Z:-KgUnpLR5pQd25WRKYwG:b-fn0af0) ([raw file](https://github.com/cockroachdb/cockroach/blob/0a4dd30b6f8a0c4253fb7046a3f3365d194a0490/pkg/ccl/storageccl/engineccl/rocksdb_unix.go#L9)):*
> ```Go
> //     https://github.com/cockroachdb/cockroach/blob/master/pkg/ccl/LICENSE
> 
> package engineccl
> ```

Needs a `!windows` build tag, right?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14466#-:-KgUlmm5TVLvSu5EluO9:b-sb0gqz)*

**Comment by tamird** [comment]
Review status: 2 of 17 files reviewed at latest revision, 4 unresolved discussions.

---

*[Makefile, line 95 at r9](https://reviewable.io:443/reviews/cockroachdb/cockroach/14466#-KgUmdXpMGhaaf5Pnoof:-KgV49kctXzvH5FM73_9:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/0a4dd30b6f8a0c4253fb7046a3f3365d194a0490/Makefile#L95)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

This will only work on amd64 architectures so it should probably have some sort of guard. (not a big deal yet, though, since we only test/support amd64)

What if a user wants to specify their own `-m` flag? It looks like the ones specified in this file will always take precedence, which is not ideal.
</blockquote></details>

Done.

---

*[pkg/ccl/storageccl/engineccl/rocksdb_unix.go, line 9 at r9](https://reviewable.io:443/reviews/cockroachdb/cockroach/14466#-KgUnpLQ_mURZ-Wpyh7Z:-KgUsFHcbC90NW3g0YtO:bqxeao8) ([raw file](https://github.com/cockroachdb/cockroach/blob/0a4dd30b6f8a0c4253fb7046a3f3365d194a0490/pkg/ccl/storageccl/engineccl/rocksdb_unix.go#L9)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

Needs a `!windows` build tag, right?
</blockquote></details>

Thanks for spotting it. Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14466)*

**Comment by bdarnell** [comment]
:lgtm:

---

Review status: 2 of 17 files reviewed at latest revision, 4 unresolved discussions, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14466#-:-KgV4ZbQWnu1MFlTCaXa:bnfp4nl)*

**Comment by petermattis** [comment]
:lgtm:

---

Review status: 2 of 17 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14466#-:-KgV8qhcW5Y7fWuW8IlX:bnfp4nl)*

**Comment by tamird** [comment]
Updated after #14840, PTAL.

**Comment by benesch** [comment]
We should offer some way for users building from source to opt-in to optimizations, but this is better than the current broken state of the world. :lgtm:

---

Reviewed 14 of 14 files at r10.
Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14466#-:-Ki5jlhIF4y-JyvmDfcx:b-60yqiy)*

**Comment by tamird** [comment]
Yeah, I think I'll repurpose `TYPE=release` for that once I'm able to resolve [this TODO](https://github.com/cockroachdb/cockroach/blob/2a6e2d6/Makefile#L64).

---

Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14466#-:-Ki5kAH6_0gQKWcADgc5:bp2ntwo)*
