### PR TITLE
server: de-flake TestClusterVersionMixedVersionTooOld

### LINKED ISSUE #56703: server: TestClusterVersionMixedVersionTooOld failed
[(server).TestClusterVersionMixedVersionTooOld failed](https://teamcity.cockroachdb.com/viewLog.html?buildId=2444785&tab=buildLog) on [master@5d8f1d3dbc356573a1fb2d1d6bf564bf0370daff](https://github.com/cockroachdb/cockroach/commits/5d8f1d3dbc356573a1fb2d1d6bf564bf0370daff):

```
=== RUN   TestClusterVersionMixedVersionTooOld
    test_log_scope.go:155: test logs captured to: /go/src/github.com/cockroachdb/cockroach/artifacts/logTestClusterVersionMixedVersionTooOld355292341
    test_log_scope.go:64: use -show-logs to present logs inline
    version_cluster_test.go:438: 0 pq: n4 required, but unavailable
test logs left over in: /go/src/github.com/cockroachdb/cockroach/artifacts/logTestClusterVersionMixedVersionTooOld355292341
--- FAIL: TestClusterVersionMixedVersionTooOld (0.43s)

```

<details><summary>More</summary><p>
Parameters:

- TAGS=
- GOFLAGS=-parallel=4

```
make stressrace TESTS=TestClusterVersionMixedVersionTooOld PKG=./pkg/server TESTTIMEOUT=5m STRESSFLAGS='-timeout 5m' 2>&1
```

[See this test on roachdash](https://roachdash.crdb.dev/?filter=status%3Aopen+t%3A.%2ATestClusterVersionMixedVersionTooOld.%2A&sort=title&restgroup=false&display=lastcommented+project)
<sub>powered by [pkg/cmd/internal/issues](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)</sub></p></details>

### PR DESCRIPTION
**Pull request by irfansharif**
Fixes #56703.

Release note: None

### CODE REVIEW

File: pkg/server/version_cluster_test.go [hunk 1]
```diff
@@ -433,9 +434,23 @@ func TestClusterVersionMixedVersionTooOld(t *testing.T) {
 
 	// The other nodes are just as careful.
 	for i := 0; i < len(versions)-2; i++ {
-		if err := tc.setVersion(i, v1s); !testutils.IsError(err,
-			fmt.Sprintf("binary version %s less than target version %s", v0s, v1s),
-		) {
+		var err error
+		for {
```
Comment (knz) [inline pkg/server/version_cluster_test.go:438]: testutils.SucceedsSoon?

Comment (irfansharif) [reply pkg/server/version_cluster_test.go]: Done.

**Review by knz — APPROVED** [review]
