### PR TITLE
sql: fix renaming of columns involved in hash sharded indexes

### LINKED ISSUE #47087: sql: cannot rename columns in hash indexes
**Describe the problem**

When trying to rename a column that is involved in a hash index it currently fails with:

```
root@127.0.0.1:37323/movr> CREATE TABLE  t0 (c0 INT  PRIMARY KEY USING HASH WITH BUCKET_COUNT = 8);
CREATE TABLE                                          
```
```
root@127.0.0.1:37323/movr> ALTER TABLE t0 RENAME COLUMN c0 TO c1;
ERROR: column "c0" does not exist
SQLSTATE: 42703
```

It's probably better that this fails as the renaming of columns was poorly considered by the hash sharded index work. We'll likely need to rename the hash column as well. 

cc @rohany but I'll pick this up.

### PR DESCRIPTION
**Pull request by ajwerner**
Prior to this commit, renames in hash sharded indexes were busted in a few
different ways.

1) The column references were using `UnresolvedName` when it should have been
   using `*tree.ColumnItem`. This was going on both in the check constaint and
   in the computed expr.

2) The `ShardedDescriptor` was not being updated to refer to the new name.

Another rough edge in all of this is that we're in deep trouble if we can't
tie the shard column back to the index[es] which are responsible for its
existence. Today this relationship is annoyingly tenuous. In an ideal world
we'd populate the ColumnDescriptor with information to mark it as a sharded
column and, ideally, the sharded descriptor. Furthermore, it's something of a
bummer that we have multiple of the same `ShardedDescriptor`s which each imply
a column but are denormalized into the `IndexDescriptor`.

Given we are where we are however, we really want to keep the name of the
shard column in sync with its source columns. This commit makes sure that
happens when member columns are renamed, the shard column is accordingly
renamed. The commit also disallows the renaming of a shard column as that
would upset the careful name synchronization.

It's worth noting that this is a little bit weird as other auto-generated
names don't change when the members change. For example an index created
with a name in the `CREATE TABLE` statement of a `FAMILY` clause.

Fixes #47087.

Release note (bug fix): In earlier betas, columns which were members of
hash sharded indexes could not be renamed. Indexes created in prior
releases will need to be dropped and recreated to resolve this limitation.

### CODE REVIEW

File: pkg/sql/alter_table.go [hunk 1]
```diff
@@ -729,7 +729,7 @@ func (n *alterTableNode) startExec(params runParams) error {
 			}
 
 		case *tree.AlterTableRenameColumn:
-			descChanged, err := params.p.renameColumn(params.ctx, n.tableDesc, &t.Column, &t.NewName)
+			descChanged, err := params.p.renameColumn(params.ctx, n.tableDesc, &t.Column, &t.NewName, false)
```
Comment (rohany) [inline pkg/sql/alter_table.go:732]: [nit]: comment the constant argument

File: pkg/sql/create_table.go [hunk 2]
```diff
@@ -2012,7 +2009,7 @@ func makeHashShardComputeExpr(colNames []string, buckets int) *string {
 					Exprs: tree.Exprs{
 						&tree.CastExpr{
 							Type: types.String,
-							Expr: unresolvedName(colName),
+							Expr: &tree.ColumnItem{ColumnName: tree.Name(colName)},
```
Comment (rohany) [inline pkg/sql/create_table.go:2012]: What changes when you make this a columnItem vs an unresolved name?

File: pkg/sql/logictest/testdata/logic_test/hash_sharded_index [hunk 3]
```diff
@@ -483,3 +483,36 @@ INSERT INTO sharded_index_with_nulls VALUES (1, NULL);
...
+CREATE TABLE rename_column (
+    c0 INT,
+    c1 INT,
+    c2 INT,
+    PRIMARY KEY (c0, c1) USING HASH WITH BUCKET_COUNT = 8,
+    INDEX (c2) USING HASH WITH BUCKET_COUNT = 8
+);
+
+statement ok
+ALTER TABLE rename_column RENAME c2 TO c3;
```
Comment (rohany) [inline pkg/sql/logictest/testdata/logic_test/hash_sharded_index:500]: Do you need to insert/select from this table to ensure that everything works, or is just doing the rename enough?

File: pkg/sql/rename_column.go [hunk 4]
```diff
@@ -60,7 +60,7 @@ func (n *renameColumnNode) startExec(params runParams) error {
 	ctx := params.ctx
 	tableDesc := n.tableDesc
 
-	descChanged, err := params.p.renameColumn(params.ctx, tableDesc, &n.n.Name, &n.n.NewName)
+	descChanged, err := params.p.renameColumn(params.ctx, tableDesc, &n.n.Name, &n.n.NewName, false)
```
Comment (rohany) [inline pkg/sql/rename_column.go:63]: ^ missing arg comment

File: pkg/sql/rename_column.go [hunk 5]
```diff
@@ -77,9 +77,13 @@ func (n *renameColumnNode) startExec(params runParams) error {
 		ctx, tableDesc, sqlbase.InvalidMutationID, tree.AsStringWithFQNames(n.n, params.Ann()))
 }
 
+// renameColumn will rename the
```
Comment (rohany) [inline pkg/sql/rename_column.go:80]: unfinished comment

File: pkg/sql/sqlbase/structured.go [hunk 6]
```diff
@@ -2032,6 +2032,10 @@ func (desc *TableDescriptor) validateTableIndexes(columnNames map[string]ColumnI
 			if err := desc.ensureShardedIndexNotComputed(index); err != nil {
 				return err
 			}
+			if _, exists := columnNames[index.Sharded.Name]; !exists {
+				return fmt.Errorf("index %q refers to non-existent shard column %q",
```
Comment (rohany) [inline pkg/sql/sqlbase/structured.go:2036]: should this be a pgerror?

**Review by rohany — CHANGES_REQUESTED** [review]

**Review by ajwerner — COMMENTED** [review]
> Reviewed 1 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/47431)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rohany)

___
*[pkg/sql/alter_table.go, line 732 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/47431#-M4oUWZkujb8FUBPboDG-r1-732:-M4tkk2b8rL4JaXHgnID:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/a64fa4e63c7f29cb3d371ae2c66a6ff64e4b71be/pkg/sql/alter_table.go#L732)):*
<details><summary><i>Previously, rohany (Rohan Yadav) wrote…</i></summary><blockquote>

[nit]: comment the constant argument
</blockquote></details>

Done.
___
*[pkg/sql/create_table.go, line 2012 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/47431#-M4oUWZkujb8FUBPboDH-r1-2012:-M4tkkn78Bx91m8d02A3:b-r5zwts) ([raw file](https://github.com/cockroachdb/cockroach/blob/a64fa4e63c7f29cb3d371ae2c66a6ff64e4b71be/pkg/sql/create_table.go#L2012)):*
<details><summary><i>Previously, rohany (Rohan Yadav) wrote…</i></summary><blockquote>

What changes when you make this a columnItem vs an unresolved name?
</blockquote></details>

Nothing, just seems more correct. 
___
*[pkg/sql/rename_column.go, line 63 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/47431#-M4oUWZlpSm60qJLesNg-r1-63:-M4tozjJ1JjWqAPjRegH:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/a64fa4e63c7f29cb3d371ae2c66a6ff64e4b71be/pkg/sql/rename_column.go#L63)):*
<details><summary><i>Previously, rohany (Rohan Yadav) wrote…</i></summary><blockquote>

^ missing arg comment
</blockquote></details>

Done.
___
*[pkg/sql/rename_column.go, line 80 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/47431#-M4oUWZlpSm60qJLesNg-r1-80:-M4tp9R76Ij2A9O0WVUo:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/a64fa4e63c7f29cb3d371ae2c66a6ff64e4b71be/pkg/sql/rename_column.go#L80)):*
<details><summary><i>Previously, rohany (Rohan Yadav) wrote…</i></summary><blockquote>

unfinished comment
</blockquote></details>

Done.
___
*[pkg/sql/logictest/testdata/logic_test/hash_sharded_index, line 500 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/47431#-M4oUWZkujb8FUBPboDI-r1-500:-M4tpA2l7dzwZa8VCZCN:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/a64fa4e63c7f29cb3d371ae2c66a6ff64e4b71be/pkg/sql/logictest/testdata/logic_test/hash_sharded_index#L500)):*
<details><summary><i>Previously, rohany (Rohan Yadav) wrote…</i></summary><blockquote>

Do you need to insert/select from this table to ensure that everything works, or is just doing the rename enough?
</blockquote></details>

Done.
___
*[pkg/sql/sqlbase/structured.go, line 2036 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/47431#-M4oUWZlpSm60qJLesNh-r1-2036:-M4tq99W2bjXG4WS5Aqp:bnxfk2x) ([raw file](https://github.com/cockroachdb/cockroach/blob/a64fa4e63c7f29cb3d371ae2c66a6ff64e4b71be/pkg/sql/sqlbase/structured.go#L2036)):*
<details><summary><i>Previously, rohany (Rohan Yadav) wrote…</i></summary><blockquote>

should this be a pgerror?
</blockquote></details>

heh I typed it that way at first. The testing infra in structured_test.go got in my way. I could move it back. I've sort of changed my mindset  that we should keep these errors as non-specific errors but do validation before we ever hit any of them. Ideally we'd get to the point where any failure under validation here is an assertion failure. At least I'm going with that until I get proven wrong. See my comment here:

https://github.com/cockroachdb/cockroach/issues/47430#issuecomment-613023139

**Review by rohany — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/47431)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner and @rohany)

___
*[pkg/sql/logictest/testdata/logic_test/hash_sharded_index, line 500 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/47431#-M4oUWZkujb8FUBPboDI-r1-500:-M4tyGvV70BX41mCdzlA:b-s24yhp) ([raw file](https://github.com/cockroachdb/cockroach/blob/a64fa4e63c7f29cb3d371ae2c66a6ff64e4b71be/pkg/sql/logictest/testdata/logic_test/hash_sharded_index#L500)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Sorry my other comment here didn't publish -- i think you should also do a show create statement test to check that the shard column got renamed appropriately
___
*[pkg/sql/sqlbase/structured.go, line 2036 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/47431#-M4oUWZlpSm60qJLesNh-r1-2036:-M4tyScmC2Ao68WGdreY:b-dxcbu5) ([raw file](https://github.com/cockroachdb/cockroach/blob/a64fa4e63c7f29cb3d371ae2c66a6ff64e4b71be/pkg/sql/sqlbase/structured.go#L2036)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

heh I typed it that way at first. The testing infra in structured_test.go got in my way. I could move it back. I've sort of changed my mindset  that we should keep these errors as non-specific errors but do validation before we ever hit any of them. Ideally we'd get to the point where any failure under validation here is an assertion failure. At least I'm going with that until I get proven wrong. See my comment here:

https://github.com/cockroachdb/cockroach/issues/47430#issuecomment-613023139
</blockquote></details>

Makes sense!

**Review by ajwerner — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/47431)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner and @rohany)

___
*[pkg/sql/logictest/testdata/logic_test/hash_sharded_index, line 500 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/47431#-M4oUWZkujb8FUBPboDI-r1-500:-M4tyecz9wGtmgSZP2zB:b4eh23m) ([raw file](https://github.com/cockroachdb/cockroach/blob/a64fa4e63c7f29cb3d371ae2c66a6ff64e4b71be/pkg/sql/logictest/testdata/logic_test/hash_sharded_index#L500)):*
<details><summary><i>Previously, rohany (Rohan Yadav) wrote…</i></summary><blockquote>

Sorry my other comment here didn't publish -- i think you should also do a show create statement test to check that the shard column got renamed appropriately
</blockquote></details>

Ha I had several and then realized they were getting mucked up because of the column family randomization and deleted them. I'll add them back with explicit column families.

**Review by ajwerner — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/47431)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner and @rohany)

___
*[pkg/sql/logictest/testdata/logic_test/hash_sharded_index, line 500 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/47431#-M4oUWZkujb8FUBPboDI-r1-500:-M4u2R2I512EmFl_Jh9P:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/a64fa4e63c7f29cb3d371ae2c66a6ff64e4b71be/pkg/sql/logictest/testdata/logic_test/hash_sharded_index#L500)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

Ha I had several and then realized they were getting mucked up because of the column family randomization and deleted them. I'll add them back with explicit column families. 
</blockquote></details>

Done.

**Review by rohany — APPROVED** [review]

**Review by ajwerner — COMMENTED** [review]
bors r=rohany

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/47431#-:-M4uFswG0tRM8ZKAxlaG:bxeqqbd)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner and @rohany)

**Review by ajwerner — COMMENTED** [review]
TFTR!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/47431#-:-M4uFwZE5fvRgy_6Tntn:b-814g8k)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner and @rohany)
