### PR TITLE
sql: fix cached gists panic'ing after schema changes

### LINKED ISSUE #76800: sql: when a table drops a bunch of columns saved gists will runtime panic on decode
```
select crdb_internal.decode_plan_gist('AgH2AQIA/wMAAAADBxQFFCH2AQAA');
ERROR: internal error: runtime error: index out of range [6] with length 6
SQLSTATE: XX000
DETAIL: stack trace:
github.com/cockroachdb/cockroach/pkg/util/errorutil/catch.go:29: ShouldCatch()
github.com/cockroachdb/cockroach/pkg/sql/opt/exec/explain/result_columns.go:33: func1()
runtime/panic.go:1047: gopanic()
runtime/panic.go:90: goPanicIndex()
github.com/cockroachdb/cockroach/pkg/sql/opt_catalog.go:1063: Column()
github.com/cockroachdb/cockroach/pkg/sql/opt/exec/explain/result_columns.go:204: tableColumns()
github.com/cockroachdb/cockroach/pkg/sql/opt/exec/explain/result_columns.go:57: getResultColumns()
github.com/cockroachdb/cockroach/pkg/sql/opt/exec/explain/explain_factory.go:89: newNode()
github.com/cockroachdb/cockroach/pkg/sql/opt/exec/explain/plan_gist_factory.og.go:1081: decodeOperatorBody()
github.com/cockroachdb/cockroach/pkg/sql/opt/exec/explain/plan_gist_factory.go:220: decodeOp()
github.com/cockroachdb/cockroach/pkg/sql/opt/exec/explain/plan_gist_factory.go:193: DecodePlanGistToPlan()
github.com/cockroachdb/cockroach/pkg/sql/opt/exec/explain/plan_gist_factory.go:145: DecodePlanGistToRows()
github.com/cockroachdb/cockroach/pkg/sql/plan_opt.go:661: DecodeGist()
github.com/cockroachdb/cockroach/pkg/sql/sem/builtins/generator_builtins.go:473: Start()
github.com/cockroachdb/cockroach/pkg/sql/rowexec/project_set.go:158: nextInputRow()
github.com/cockroachdb/cockroach/pkg/sql/rowexec/project_set.go:241: Next()
github.com/cockroachdb/cockroach/pkg/sql/colexec/columnarizer.go:229: Next()
github.com/cockroachdb/cockroach/pkg/sql/colflow/stats.go:99: Next()
github.com/cockroachdb/cockroach/pkg/sql/colflow/flow_coordinator.go:240: nextAdapter()
github.com/cockroachdb/cockroach/pkg/sql/colexecerror/error.go:91: CatchVectorizedRuntimeError()
github.com/cockroachdb/cockroach/pkg/sql/colflow/flow_coordinator.go:244: next()
github.com/cockroachdb/cockroach/pkg/sql/colflow/flow_coordinator.go:287: Run()
github.com/cockroachdb/cockroach/pkg/sql/colflow/vectorized_flow.go:259: Run()
github.com/cockroachdb/cockroach/pkg/sql/distsql_running.go:574: Run()
github.com/cockroachdb/cockroach/pkg/sql/distsql_running.go:1410: PlanAndRun()
github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:1420: execWithDistSQLEngine()
github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:1097: dispatchToExecutionEngine()
github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:727: execStmtInOpenState()
github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:140: execStmt()
github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:1782: func1()
github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:1786: execCmd()
github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:1715: run()
```

### PR DESCRIPTION
**Pull request by cucaroach**
Previously we didn't guard against out of bounds column ids in gists,
if a gist is created on a table and then that table drops columns we
would hit a runtime index out of bounds panic. By design gist decoding
is best effort and should silently ignore these columns when this
happens. The columns are used for equality conditions, ie:

             └── • lookup join
                 │ table: broker@broker_pkey
                 │ equality: (tr_s_symb) = (b_id)

So they are a nice to have. Doing anything more sophisticated would
dramatically increase the gist size so isn't worth it.

Fixes: #76800

Release note: None

### CODE REVIEW

File: pkg/sql/opt/exec/execbuilder/testdata/explain_gist [hunk 1]
```diff
@@ -62,3 +62,25 @@ query T
...
+ALTER TABLE t2 DROP COLUMN a;
+ALTER TABLE t2 DROP COLUMN d;
+ALTER TABLE t2 DROP COLUMN e
+
+query T
+SELECT crdb_internal.decode_plan_gist('$gist')
+----
+• scan
+  table: t2@t2_pkey
+  spans: FULL SCAN
```
Comment (mgartner) [inline pkg/sql/opt/exec/execbuilder/testdata/explain_gist:86]: How will the columns be displayed if they can't be decoded? Maybe this query should be a lookup join to test that case: `SELECT * FROM t2 AS t2a INNER LOOKUP JOIN t2 AS t2b ON t2a.a = t2b.a` and add an `INDEX (a)`.

File: pkg/sql/opt/exec/explain/result_columns.go [hunk 2]
```diff
@@ -201,11 +201,14 @@ func getResultColumns(
 func tableColumns(table cat.Table, ordinals exec.TableColumnOrdinalSet) colinfo.ResultColumns {
 	cols := make(colinfo.ResultColumns, 0, ordinals.Len())
 	for i, ok := ordinals.Next(0); ok; i, ok = ordinals.Next(i + 1) {
-		col := table.Column(i)
-		cols = append(cols, colinfo.ResultColumn{
-			Name: string(col.ColName()),
-			Typ:  col.DatumType(),
-		})
+		// Be defensive about bitset values because they may come from cached gists.
```
Comment (mgartner) [inline pkg/sql/opt/exec/explain/result_columns.go:204]: nit: Might be helpful to explain that this guards against deleted columns.

File: pkg/sql/plan_opt.go [hunk 3]
```diff
@@ -655,8 +655,7 @@ func (opc *optPlanningCtx) runExecBuilder(
 	return nil
 }
 
-// DecodeGist Avoid an import cycle by keeping the cat out of the tree, RFC: is
-// there a better way?
+// DecodeGist Avoid an import cycle by keeping the cat out of the tree.
```
Comment (mgartner) [inline pkg/sql/plan_opt.go:658]: Avoids a call to the fire department too!

**Review by cucaroach — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/76801)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @cucaroach, @mgartner, and @RaduBerinde)

___
*[pkg/sql/opt/exec/explain/result_columns.go, line 204 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/76801#-MwEMuZR9SBAzYg80GGC-r1-204:-MwX0nAU5OJIPtPtDBJT:bb6mt9b) ([raw file](https://github.com/cockroachdb/cockroach/blob/635142d5836e91131c166b6b5f3a293ec2e1340b/pkg/sql/opt/exec/explain/result_columns.go#L204)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

nit: Might be helpful to explain that this guards against deleted columns.
</blockquote></details>

:+1:
___
*[pkg/sql/opt/exec/execbuilder/testdata/explain_gist, line 86 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/76801#-MwEMuZR9SBAzYg80GGB-r1-86:-MwX0FG5CZzIxK5FhAdc:bs5vbsb) ([raw file](https://github.com/cockroachdb/cockroach/blob/635142d5836e91131c166b6b5f3a293ec2e1340b/pkg/sql/opt/exec/execbuilder/testdata/explain_gist#L86)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

How will the columns be displayed if they can't be decoded? Maybe this query should be a lookup join to test that case: `SELECT * FROM t2 AS t2a INNER LOOKUP JOIN t2 AS t2b ON t2a.a = t2b.a` and add an `INDEX (a)`.
</blockquote></details>

So if the column index is out of bounds you'll get a "_" in the plan.   But its also possible they aren't out of bounds and now refer to a new column (even "rowid" or "crdb_mvcc_timestamp").  Not perfect but should be rare.

**Review by mgartner — APPROVED** [review]
:lgtm: 

> Reviewed 2 of 3 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/76801#-:-MwX5Dv9BSLRYxJskHuz:bfsmuih)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @cucaroach, @mgartner, and @RaduBerinde)

**Comment by cucaroach** [comment]
bors r=mgartner

**Comment by cucaroach** [comment]
bors r=mgartner
