### PR TITLE
roachprod: fix node environment variable propagation

### LINKED ISSUE #68887: roachperf: July 28th performance regression on `master`
Roachperf graphs for `master` show a performance regression on July 28th, mostly on AWS and on large machines:

* [kv95/enc=false/nodes=3/cpu=32/size=4kb](https://roachperf.crdb.dev/?filter=&view=kv95%2Fenc%3Dfalse%2Fnodes%3D3%2Fcpu%3D32%2Fsize%3D4kb&tab=aws)
* [kv95/enc=false/nodes=3/cpu=96](https://roachperf.crdb.dev/?filter=&view=kv95%2Fenc%3Dfalse%2Fnodes%3D3%2Fcpu%3D96&tab=gce)
* [ycsb/B/nodes=3/cpu=32](https://roachperf.crdb.dev/?filter=&view=ycsb%2FB%2Fnodes%3D3%2Fcpu%3D32&tab=aws)
* [ycsb/C/nodes=3/cpu=32](https://roachperf.crdb.dev/?filter=&view=ycsb%2FC%2Fnodes%3D3%2Fcpu%3D32&tab=aws)

This is less pronounced on GCE, where the only graph with a significant difference is:

* [kv95/enc=false/nodes=3/cpu=96](https://roachperf.crdb.dev/?filter=&view=kv95%2Fenc%3Dfalse%2Fnodes%3D3%2Fcpu%3D96&tab=gce)

#68084 seems like a possible candidate, will run some tests/bisections.

/cc @cockroachdb/test-eng

### PR DESCRIPTION
**Pull request by erikgrinaker**
In #67363, configured environment variables were no longer
propagated to nodes. In particular, the default node envvar
`COCKROACH_ENABLE_RPC_COMPRESSION=false` was not passed,
which caused a 5% performance regression on certain benchmarks.

This patch fixes propagation of environment variables.

Resolves #68887.

Release note: None

/cc @cockroachdb/test-eng 

---

I'm going on vacation next week, I'd appreciate it if you could get this merged for me.

### CODE REVIEW

File: pkg/cmd/roachprod/install/cockroach.go [hunk 1]
```diff
@@ -436,10 +436,10 @@ func (h *crdbInstallHelper) generateStartCmd(
 		LogDir: h.c.Impl.LogDir(h.c, nodes[nodeIdx]),
 		KeyCmd: h.generateKeyCmd(nodeIdx, extraArgs),
 		Tag:    h.c.Tag,
-		EnvVars: append([]string{
+		EnvVars: append(append([]string{
 			"GOTRACEBACK=crash",
 			"COCKROACH_SKIP_ENABLING_DIAGNOSTIC_REPORTING=1",
-		}, h.getEnvVars()...),
+		}, h.c.Env...), h.getEnvVars()...),
```
Comment (stevendanna) [inline pkg/cmd/roachprod/install/cockroach.go:442]: Just for reference, it looks like this used to happen in getEnvVars: https://github.com/cockroachdb/cockroach/pull/67363/files#diff-052e0342a18522387861c55bc7df04d8b6a888977f4593e2c8cd7c5749f94068L757-L761

**Review by stevendanna — APPROVED** [review]
Thanks for hunting this down.

**Review by stevendanna — DISMISSED** [review]
It looks like we might be generating incorrect roachprod commands:

```
  cluster.go:1798,kv.go:630,test_runner.go:777: /go/src/github.com/cockroachdb/cockroach/bin/roachprod start --env COCKROACH_MEMPROF_INTERVAL=1m COCKROACH_DISABLE_QUIESCENCE=false --args=--cache=256MiB local:1-3 returned: exit status 1
```

The argument to `--env` needs to be comma-separated I believe, although I'm not sure why that would have changed here so perhaps I need to read this log more carefully :D.

**Comment by stevendanna** [comment]
I don't mind picking this up while you are on PTO

**Comment by stevendanna** [comment]
Found the cause of the test failure -- details in the commit message. This should be good for another look.

**Review by tbg — APPROVED** [review]
Thanks!

**Comment by stevendanna** [comment]
bors r=tbg

**Comment by erikgrinaker** [comment]
>Found the cause of the test failure -- details in the commit message. This should be good for another look.

Nice catch! Thanks for taking this across the line @stevendanna, appreciate it!
