### PR TITLE
fuzzystrmatch: fix crash and compatibility

### LINKED ISSUE #82640: util/fuzzystrmatch: v22.2.0-alpha: index out of bounds
This issue was autofiled by Sentry. It represents a crash or reported error on a live cluster with telemetry enabled.

Sentry link: https://sentry.io/organizations/cockroach-labs/issues/3335231559/?referrer=webhooks_plugin

Panic message:

>conn_executor.go:750: runtime error: index out of range [4] with length 4
(1) attached stack trace
  -- stack trace:
  | github.com/cockroachdb/cockroach/pkg/sql.(*Server).ServeConn.func1
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:750
  | [...repeated from below...]
Wraps: (2) while executing: WITH _ AS (SELECT _ FROM _ WHERE (_ = '_') AND (_ = _)), _ AS (SELECT ARRAY (SELECT DISTINCT soundex(unnest(regexp_split_to_array(_, '_')))) AS _ FROM _) UPDATE _ SET _ = (SELECT _ FROM _, _) WHERE (_ = '_') AND (_ = _)
Wraps: (3) attached stack trace
  -- stack trace:
  | github.com/cockroachdb/cockroach/pkg/sql.(*Server).ServeConn.func1
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:750
  | runtime.gopanic
  | 	GOROOT/src/runtime/panic.go:1038
  | github.com/cockroachdb/cockroach/pkg/sql/colexecerror.CatchVectorizedRuntimeError.func1
  | 	github.com/cockroachdb/cockroach/pkg/sql/colexecerror/error.go:58
  | runtime.gopanic
  | 	GOROOT/src/runtime/panic.go:1038
  | github.com/cockroachdb/cockroach/pkg/sql/colexecerror.CatchVectorizedRuntimeError.func1
  | 	github.com/cockroachdb/cockroach/pkg/sql/colexecerror/error.go:58
  | runtime.gopanic
  | 	GOROOT/src/runtime/panic.go:1038
  | github.com/cockroachdb/cockroach/pkg/sql/colexecerror.CatchVectorizedRuntimeError.func1
  | 	github.com/cockroachdb/cockroach/pkg/sql/colexecerror/error.go:58
  | runtime.gopanic
  | 	GOROOT/src/runtime/panic.go:1038
  | github.com/cockroachdb/cockroach/pkg/sql/colexecerror.CatchVectorizedRuntimeError.func1
  | 	github.com/cockroachdb/cockroach/pkg/sql/colexecerror/error.go:58
  | runtime.gopanic
  | 	GOROOT/src/runtime/panic.go:1038
  | github.com/cockroachdb/cockroach/pkg/sql/colexecerror.CatchVectorizedRuntimeError.func1
  | 	github.com/cockroachdb/cockroach/pkg/sql/colexecerror/error.go:58
  | runtime.gopanic
  | 	GOROOT/src/runtime/panic.go:1038
  | runtime.goPanicIndex
  | 	GOROOT/src/runtime/panic.go:90
  | github.com/cockroachdb/cockroach/pkg/util/fuzzystrmatch.soundex
  | 	github.com/cockroachdb/cockroach/pkg/util/fuzzystrmatch/soundex.go:59
  | github.com/cockroachdb/cockroach/pkg/util/fuzzystrmatch.Soundex
  | 	github.com/cockroachdb/cockroach/pkg/util/fuzzystrmatch/soundex.go:77
  | github.com/cockroachdb/cockroach/pkg/sql/sem/builtins.glob..func211
  | 	github.com/cockroachdb/cockroach/pkg/sql/sem/builtins/builtins.go:3747
  | github.com/cockroachdb/cockroach/pkg/sql/sem/eval.(*evaluator).EvalFuncExpr
  | 	github.com/cockroachdb/cockroach/pkg/sql/sem/eval/expr.go:421
  | github.com/cockroachdb/cockroach/pkg/sql/sem/tree.(*FuncExpr).Eval
  | 	github.com/cockroachdb/cockroach/bazel-out/k8-opt/bin/pkg/sql/sem/tree/eval_expr_generated.go:256
  | github.com/cockroachdb/cockroach/pkg/sql/sem/eval.Expr
  | 	github.com/cockroachdb/cockroach/pkg/sql/sem/eval/expr.go:23
  | github.com/cockroachdb/cockroach/pkg/sql/execinfrapb.(*ExprHelper).Eval
  | 	github.com/cockroachdb/cockroach/pkg/sql/execinfrapb/pkg/sql/execinfrapb/expr.go:232
  | github.com/cockroachdb/cockroach/pkg/sql/execinfra.(*ProcOutputHelper).ProcessRow
  | 	github.com/cockroachdb/cockroach/pkg/sql/execinfra/processorsbase.go:258
  | github.com/cockroachdb/cockroach/pkg/sql/execinfra.(*ProcessorBase).ProcessRowHelper
  | 	github.com/cockroachdb/cockroach/pkg/sql/execinfra/processorsbase.go:696
  | github.com/cockroachdb/cockroach/pkg/sql.(*planNodeToRowSource).Next
  | 	github.com/cockroachdb/cockroach/pkg/sql/plan_node_to_row_source.go:205
  | github.com/cockroachdb/cockroach/pkg/sql/colexec.(*Columnarizer).Next
  | 	github.com/cockroachdb/cockroach/pkg/sql/colexec/columnarizer.go:231
  | github.com/cockroachdb/cockroach/pkg/sql/colexec.(*UnorderedDistinct).Next
  | 	github.com/cockroachdb/cockroach/pkg/sql/colexec/unordered_distinct.go:97
  | github.com/cockroachdb/cockroach/pkg/sql/colexec/colexecdisk.(*diskSpillerBase).Next.func1
  | 	github.com/cockroachdb/cockroach/pkg/sql/colexec/colexecdisk/disk_spiller.go:198
  | github.com/cockroachdb/cockroach/pkg/sql/colexecerror.CatchVectorizedRuntimeError
  | 	github.com/cockroachdb/cockroach/pkg/sql/colexecerror/error.go:91
  | github.com/cockroachdb/cockroach/pkg/sql/colexec/colexecdisk.(*diskSpillerBase).Next
  | 	github.com/cockroachdb/cockroach/pkg/sql/colexec/colexecdisk/disk_spiller.go:196
  | github.com/cockroachdb/cockroach/pkg/sql/colexec/colexecutils.(*vectorTypeEnforcer).Next
  | 	github.com/cockroachdb/cockroach/pkg/sql/colexec/colexecutils/operator.go:137
  | github.com/cockroachdb/cockroach/pkg/sql/colexec/colexecbase.constBoolOp.Next
  | 	github.com/cockroachdb/cockroach/bazel-out/k8-opt/bin/pkg/sql/colexec/colexecbase/const.eg.go:172
  | github.com/cockroachdb/cockroach/pkg/sql/colexec.(*Materializer).next
  | 	github.com/cockroachdb/cockroach/pkg/sql/colexec/materializer.go:268
  | github.com/cockroachdb/cockroach/pkg/sql/colexec.(*Materializer).nextAdapter
  | 	github.com/cockroachdb/cockroach/pkg/sql/colexec/materializer.go:293
Wraps: (4) runtime error: index out of range [4] with length 4
Error types: (1) *withstack.withStack (2) *safedetails.withSafeDetails (3) *withstack.withStack (4) runtime.boundsError
-- report composition:
runtime.boundsError
conn_executor.go:750: *withstack.withStack (top exception)
*safedetails.withSafeDetails: while executing: WITH _ AS (SELECT _ FROM _ WHERE (_ = '_') AND (_ = _)), _ AS (SELECT ARRAY (SELECT DISTINCT soundex(unnest(regexp_split_to_array(_, '_')))) AS _ FROM _) UPDATE _ SET _ = (SELECT _ FROM _, _) WHERE (_ = '_') AND (_ = _)
conn_executor.go:750: *withstack.withStack (1)
(check the extra data payloads)

<details>
<summary>Stacktrace (expand for inline code snippets):</summary>

https://github.com/cockroachdb/cockroach/blob/5bd3fdd33a351564e7af5e64ce931e82db5e23a1/pkg/sql/conn_executor.go#L749-L751 in pkg/sql.(*Server).ServeConn.func1
GOROOT/src/runtime/panic.go#L1037-L1039 in runtime.gopanic
https://github.com/cockroachdb/cockroach/blob/5bd3fdd33a351564e7af5e64ce931e82db5e23a1/pkg/sql/colexecerror/error.go#L57-L59 in pkg/sql/colexecerror.CatchVectorizedRuntimeError.func1
GOROOT/src/runtime/panic.go#L1037-L1039 in runtime.gopanic
https://github.com/cockroachdb/cockroach/blob/5bd3fdd33a351564e7af5e64ce931e82db5e23a1/pkg/sql/colexecerror/error.go#L57-L59 in pkg/sql/colexecerror.CatchVectorizedRuntimeError.func1
GOROOT/src/runtime/panic.go#L1037-L1039 in runtime.gopanic
https://github.com/cockroachdb/cockroach/blob/5bd3fdd33a351564e7af5e64ce931e82db5e23a1/pkg/sql/colexecerror/error.go#L57-L59 in pkg/sql/colexecerror.CatchVectorizedRuntimeError.func1
GOROOT/src/runtime/panic.go#L1037-L1039 in runtime.gopanic
https://github.com/cockroachdb/cockroach/blob/5bd3fdd33a351564e7af5e64ce931e82db5e23a1/pkg/sql/colexecerror/error.go#L57-L59 in pkg/sql/colexecerror.CatchVectorizedRuntimeError.func1
GOROOT/src/runtime/panic.go#L1037-L1039 in runtime.gopanic
https://github.com/cockroachdb/cockroach/blob/5bd3fdd33a351564e7af5e64ce931e82db5e23a1/pkg/sql/colexecerror/error.go#L57-L59 in pkg/sql/colexecerror.CatchVectorizedRuntimeError.func1
GOROOT/src/runtime/panic.go#L1037-L1039 in runtime.gopanic
GOROOT/src/runtime/panic.go#L89-L91 in runtime.goPanicIndex
https://github.com/cockroachdb/cockroach/blob/5bd3fdd33a351564e7af5e64ce931e82db5e23a1/pkg/util/fuzzystrmatch/soundex.go#L58-L60 in pkg/util/fuzzystrmatch.soundex
https://github.com/cockroachdb/cockroach/blob/5bd3fdd33a351564e7af5e64ce931e82db5e23a1/pkg/util/fuzzystrmatch/soundex.go#L76-L78 in pkg/util/fuzzystrmatch.Soundex
https://github.com/cockroachdb/cockroach/blob/5bd3fdd33a351564e7af5e64ce931e82db5e23a1/pkg/sql/sem/builtins/builtins.go#L3746-L3748 in pkg/sql/sem/builtins.glob..func211
https://github.com/cockroachdb/cockroach/blob/5bd3fdd33a351564e7af5e64ce931e82db5e23a1/pkg/sql/sem/eval/expr.go#L420-L422 in pkg/sql/sem/eval.(*evaluator).EvalFuncExpr
https://github.com/cockroachdb/cockroach/blob/5bd3fdd33a351564e7af5e64ce931e82db5e23a1/bazel-out/k8-opt/bin/pkg/sql/sem/tree/eval_expr_generated.go#L255-L257 in pkg/sql/sem/tree.(*FuncExpr).Eval
https://github.com/cockroachdb/cockroach/blob/5bd3fdd33a351564e7af5e64ce931e82db5e23a1/pkg/sql/sem/eval/expr.go#L22-L24 in pkg/sql/sem/eval.Expr
https://github.com/cockroachdb/cockroach/blob/5bd3fdd33a351564e7af5e64ce931e82db5e23a1/pkg/sql/execinfrapb/pkg/sql/execinfrapb/expr.go#L231-L233 in pkg/sql/execinfrapb.(*ExprHelper).Eval
https://github.com/cockroachdb/cockroach/blob/5bd3fdd33a351564e7af5e64ce931e82db5e23a1/pkg/sql/execinfra/processorsbase.go#L257-L259 in pkg/sql/execinfra.(*ProcOutputHelper).ProcessRow
https://github.com/cockroachdb/cockroach/blob/5bd3fdd33a351564e7af5e64ce931e82db5e23a1/pkg/sql/execinfra/processorsbase.go#L695-L697 in pkg/sql/execinfra.(*ProcessorBase).ProcessRowHelper
https://github.com/cockroachdb/cockroach/blob/5bd3fdd33a351564e7af5e64ce931e82db5e23a1/pkg/sql/plan_node_to_row_source.go#L204-L206 in pkg/sql.(*planNodeToRowSource).Next
https://github.com/cockroachdb/cockroach/blob/5bd3fdd33a351564e7af5e64ce931e82db5e23a1/pkg/sql/colexec/columnarizer.go#L230-L232 in pkg/sql/colexec.(*Columnarizer).Next
https://github.com/cockroachdb/cockroach/blob/5bd3fdd33a351564e7af5e64ce931e82db5e23a1/pkg/sql/colexec/unordered_distinct.go#L96-L98 in pkg/sql/colexec.(*UnorderedDistinct).Next
https://github.com/cockroachdb/cockroach/blob/5bd3fdd33a351564e7af5e64ce931e82db5e23a1/pkg/sql/colexec/colexecdisk/disk_spiller.go#L197-L199 in pkg/sql/colexec/colexecdisk.(*diskSpillerBase).Next.func1
https://github.com/cockroachdb/cockroach/blob/5bd3fdd33a351564e7af5e64ce931e82db5e23a1/pkg/sql/colexecerror/error.go#L90-L92 in pkg/sql/colexecerror.CatchVectorizedRuntimeError
https://github.com/cockroachdb/cockroach/blob/5bd3fdd33a351564e7af5e64ce931e82db5e23a1/pkg/sql/colexec/colexecdisk/disk_spiller.go#L195-L197 in pkg/sql/colexec/colexecdisk.(*diskSpillerBase).Next
https://github.com/cockroachdb/cockroach/blob/5bd3fdd33a351564e7af5e64ce931e82db5e23a1/pkg/sql/colexec/colexecutils/operator.go#L136-L138 in pkg/sql/colexec/colexecutils.(*vectorTypeEnforcer).Next
https://github.com/cockroachdb/cockroach/blob/5bd3fdd33a351564e7af5e64ce931e82db5e23a1/bazel-out/k8-opt/bin/pkg/sql/colexec/colexecbase/const.eg.go#L171-L173 in pkg/sql/colexec/colexecbase.constBoolOp.Next
https://github.com/cockroachdb/cockroach/blob/5bd3fdd33a351564e7af5e64ce931e82db5e23a1/pkg/sql/colexec/materializer.go#L267-L269 in pkg/sql/colexec.(*Materializer).next
https://github.com/cockroachdb/cockroach/blob/5bd3fdd33a351564e7af5e64ce931e82db5e23a1/pkg/sql/colexec/materializer.go#L292-L294 in pkg/sql/colexec.(*Materializer).nextAdapter
</details>

```
pkg/sql/conn_executor.go in pkg/sql.(*Server).ServeConn.func1 at line 750
GOROOT/src/runtime/panic.go in runtime.gopanic at line 1038
pkg/sql/colexecerror/error.go in pkg/sql/colexecerror.CatchVectorizedRuntimeError.func1 at line 58
GOROOT/src/runtime/panic.go in runtime.gopanic at line 1038
pkg/sql/colexecerror/error.go in pkg/sql/colexecerror.CatchVectorizedRuntimeError.func1 at line 58
GOROOT/src/runtime/panic.go in runtime.gopanic at line 1038
pkg/sql/colexecerror/error.go in pkg/sql/colexecerror.CatchVectorizedRuntimeError.func1 at line 58
GOROOT/src/runtime/panic.go in runtime.gopanic at line 1038
pkg/sql/colexecerror/error.go in pkg/sql/colexecerror.CatchVectorizedRuntimeError.func1 at line 58
GOROOT/src/runtime/panic.go in runtime.gopanic at line 1038
pkg/sql/colexecerror/error.go in pkg/sql/colexecerror.CatchVectorizedRuntimeError.func1 at line 58
GOROOT/src/runtime/panic.go in runtime.gopanic at line 1038
GOROOT/src/runtime/panic.go in runtime.goPanicIndex at line 90
pkg/util/fuzzystrmatch/soundex.go in pkg/util/fuzzystrmatch.soundex at line 59
pkg/util/fuzzystrmatch/soundex.go in pkg/util/fuzzystrmatch.Soundex at line 77
pkg/sql/sem/builtins/builtins.go in pkg/sql/sem/builtins.glob..func211 at line 3747
pkg/sql/sem/eval/expr.go in pkg/sql/sem/eval.(*evaluator).EvalFuncExpr at line 421
bazel-out/k8-opt/bin/pkg/sql/sem/tree/eval_expr_generated.go in pkg/sql/sem/tree.(*FuncExpr).Eval at line 256
pkg/sql/sem/eval/expr.go in pkg/sql/sem/eval.Expr at line 23
pkg/sql/execinfrapb/pkg/sql/execinfrapb/expr.go in pkg/sql/execinfrapb.(*ExprHelper).Eval at line 232
pkg/sql/execinfra/processorsbase.go in pkg/sql/execinfra.(*ProcOutputHelper).ProcessRow at line 258
pkg/sql/execinfra/processorsbase.go in pkg/sql/execinfra.(*ProcessorBase).ProcessRowHelper at line 696
pkg/sql/plan_node_to_row_source.go in pkg/sql.(*planNodeToRowSource).Next at line 205
pkg/sql/colexec/columnarizer.go in pkg/sql/colexec.(*Columnarizer).Next at line 231
pkg/sql/colexec/unordered_distinct.go in pkg/sql/colexec.(*UnorderedDistinct).Next at line 97
pkg/sql/colexec/colexecdisk/disk_spiller.go in pkg/sql/colexec/colexecdisk.(*diskSpillerBase).Next.func1 at line 198
pkg/sql/colexecerror/error.go in pkg/sql/colexecerror.CatchVectorizedRuntimeError at line 91
pkg/sql/colexec/colexecdisk/disk_spiller.go in pkg/sql/colexec/colexecdisk.(*diskSpillerBase).Next at line 196
pkg/sql/colexec/colexecutils/operator.go in pkg/sql/colexec/colexecutils.(*vectorTypeEnforcer).Next at line 137
bazel-out/k8-opt/bin/pkg/sql/colexec/colexecbase/const.eg.go in pkg/sql/colexec/colexecbase.constBoolOp.Next at line 172
pkg/sql/colexec/materializer.go in pkg/sql/colexec.(*Materializer).next at line 268
pkg/sql/colexec/materializer.go in pkg/sql/colexec.(*Materializer).nextAdapter at line 293
```

| Tag | Value |
|---|---|
| Cockroach Release | `v22.2.0-alpha.00000000-460-g5bd3fdd33a` |
| Cockroach SHA: | 5bd3fdd33a351564e7af5e64ce931e82db5e23a1 |
| Platform | darwin amd64 |
| Distribution | CCL |
| Environment | v22.2.0-alpha.00000000-460-g5bd3fdd33a |
| Command | start-single-node |
| Go Version | ``|
| # of CPUs ||
| # of Goroutines ||

Jira issue: CRDB-16545

### PR DESCRIPTION
**Pull request by jordanlewis**
Closes #82640

Release note (bug fix): fix behavior of soundex function when passed
certain unicode inputs. Previously, certain unicode inputs could result
in crashes, errors or incorrect outputs.

### CODE REVIEW

**Comment by jordanlewis** [comment]
cc @mgoddard

File: pkg/util/fuzzystrmatch/soundex_test.go [hunk 1]
```diff
@@ -39,12 +42,25 @@ func TestSoundex(t *testing.T) {
 		},
 		{
 			Source:   "🌞",
-			Expected: "000",
+			Expected: "",
```
Comment (rafiss) [inline pkg/util/fuzzystrmatch/soundex_test.go:45]: why did this one change? it looks like PG returns 000 for it (binary `d0303030`)

File: pkg/util/fuzzystrmatch/soundex_test.go [hunk 2]
```diff
@@ -39,12 +42,25 @@ func TestSoundex(t *testing.T) {
...
 			Source:   "😄 🐃 🐯 🕣 💲 🏜 👞 🔠 🌟 📌",
 			Expected: "",
 		},
+		{
+			Source:   "zażółćx",
+			Expected: "Z200",
+		},
+		{
+			Source:   "K😋",
+			Expected: "K000",
```
Comment (rafiss) [inline pkg/util/fuzzystrmatch/soundex_test.go:57]: PG returns `K00` (binary `4bd03030`)

**Review by rafiss — CHANGES_REQUESTED** [review]

**Comment by jordanlewis** [comment]
The differences you wrote don't materialize on the system I was testing on... what version are you testing on?

**Comment by jordanlewis** [comment]
Here's what I get:

```

jordan=> select version();
                                                              version
-----------------------------------------------------------------------------------------------------------------------------------
 PostgreSQL 14.3 (Ubuntu 14.3-1.pgdg20.04+1) on x86_64-pc-linux-gnu, compiled by gcc (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0, 64-bit
(1 row)

jordan=> select soundex('🌞');
 soundex
---------

(1 row)

jordan=> select soundex('K😋');
 soundex
---------
 K000
(1 row)

jordan=>
```

It sounds like this functionality just doesn't work consistently for UTF8:

image

**Comment by jordanlewis** [comment]
BTW, I get this same output even in Postgres 12 (I upgraded to Postgres 14 to see if it would repro on your version)

**Review by rafiss — APPROVED** [review]
ah i see thanks for looking. lgtm  then
