### PR TITLE
backupccl: fix nil pointer exception in restore OnFailOrCancel

### LINKED ISSUE #76720: backupccl: v21.2.4-customer: nil pointer in restoreResumer.cleanupTempSystemTables
This issue was autofiled by Sentry. It represents a crash or reported error on a live cluster with telemetry enabled.

Sentry link: https://sentry.io/organizations/cockroach-labs/issues/3022515119/?referrer=webhooks_plugin

Panic message:

>panic.go:965: runtime error: invalid memory address or nil pointer dereference
--
runtime.errorString
panic.go:965: *withstack.withStack (top exception)

<details>
<summary>Stacktrace (expand for inline code snippets):</summary>

/usr/local/go/src/runtime/panic.go#L964-L966 in runtime.gopanic
/usr/local/go/src/runtime/panic.go#L211-L213 in runtime.panicmem
/usr/local/go/src/runtime/signal_unix.go#L733-L735 in runtime.sigpanic
https://github.com/cockroachdb/cockroach/blob/b4a27f3634e3e41dc3966214cf05ff6870c055c5/pkg/ccl/backupccl/restore_job.go#L2428-L2430 in pkg/ccl/backupccl.(*restoreResumer).cleanupTempSystemTables
https://github.com/cockroachdb/cockroach/blob/b4a27f3634e3e41dc3966214cf05ff6870c055c5/pkg/ccl/backupccl/restore_job.go#L1938-L1940 in pkg/ccl/backupccl.(*restoreResumer).OnFailOrCancel.func1
https://github.com/cockroachdb/cockroach/blob/b4a27f3634e3e41dc3966214cf05ff6870c055c5/pkg/sql/catalog/descs/txn.go#L83-L85 in pkg/sql/catalog/descs.(*CollectionFactory).Txn.func2
https://github.com/cockroachdb/cockroach/blob/b4a27f3634e3e41dc3966214cf05ff6870c055c5/pkg/kv/db.go#L835-L837 in pkg/kv.runTxn.func1
https://github.com/cockroachdb/cockroach/blob/b4a27f3634e3e41dc3966214cf05ff6870c055c5/pkg/kv/txn.go#L907-L909 in pkg/kv.(*Txn).exec
https://github.com/cockroachdb/cockroach/blob/b4a27f3634e3e41dc3966214cf05ff6870c055c5/pkg/kv/db.go#L834-L836 in pkg/kv.runTxn
https://github.com/cockroachdb/cockroach/blob/b4a27f3634e3e41dc3966214cf05ff6870c055c5/pkg/kv/db.go#L816-L818 in pkg/kv.(*DB).Txn
https://github.com/cockroachdb/cockroach/blob/b4a27f3634e3e41dc3966214cf05ff6870c055c5/pkg/sql/catalog/descs/txn.go#L75-L77 in pkg/sql/catalog/descs.(*CollectionFactory).Txn
https://github.com/cockroachdb/cockroach/blob/b4a27f3634e3e41dc3966214cf05ff6870c055c5/pkg/sql/exec_util.go#L3073-L3075 in pkg/sql.DescsTxn
https://github.com/cockroachdb/cockroach/blob/b4a27f3634e3e41dc3966214cf05ff6870c055c5/pkg/ccl/backupccl/restore_job.go#L1908-L1910 in pkg/ccl/backupccl.(*restoreResumer).OnFailOrCancel
https://github.com/cockroachdb/cockroach/blob/b4a27f3634e3e41dc3966214cf05ff6870c055c5/pkg/jobs/registry.go#L1269-L1271 in pkg/jobs.(*Registry).stepThroughStateMachine.func3
https://github.com/cockroachdb/cockroach/blob/b4a27f3634e3e41dc3966214cf05ff6870c055c5/pkg/jobs/registry.go#L1270-L1272 in pkg/jobs.(*Registry).stepThroughStateMachine
https://github.com/cockroachdb/cockroach/blob/b4a27f3634e3e41dc3966214cf05ff6870c055c5/pkg/jobs/adopt.go#L414-L416 in pkg/jobs.(*Registry).runJob
https://github.com/cockroachdb/cockroach/blob/b4a27f3634e3e41dc3966214cf05ff6870c055c5/pkg/jobs/adopt.go#L335-L337 in pkg/jobs.(*Registry).resumeJob.func1
https://github.com/cockroachdb/cockroach/blob/b4a27f3634e3e41dc3966214cf05ff6870c055c5/pkg/util/stop/stopper.go#L441-L443 in pkg/util/stop.(*Stopper).RunAsyncTaskEx.func2
/usr/local/go/src/runtime/asm_amd64.s#L1370-L1372 in runtime.goexit
</details>

```
/usr/local/go/src/runtime/panic.go in runtime.gopanic at line 965
/usr/local/go/src/runtime/panic.go in runtime.panicmem at line 212
/usr/local/go/src/runtime/signal_unix.go in runtime.sigpanic at line 734
pkg/ccl/backupccl/restore_job.go in pkg/ccl/backupccl.(*restoreResumer).cleanupTempSystemTables at line 2429
pkg/ccl/backupccl/restore_job.go in pkg/ccl/backupccl.(*restoreResumer).OnFailOrCancel.func1 at line 1939
pkg/sql/catalog/descs/txn.go in pkg/sql/catalog/descs.(*CollectionFactory).Txn.func2 at line 84
pkg/kv/db.go in pkg/kv.runTxn.func1 at line 836
pkg/kv/txn.go in pkg/kv.(*Txn).exec at line 908
pkg/kv/db.go in pkg/kv.runTxn at line 835
pkg/kv/db.go in pkg/kv.(*DB).Txn at line 817
pkg/sql/catalog/descs/txn.go in pkg/sql/catalog/descs.(*CollectionFactory).Txn at line 76
pkg/sql/exec_util.go in pkg/sql.DescsTxn at line 3074
pkg/ccl/backupccl/restore_job.go in pkg/ccl/backupccl.(*restoreResumer).OnFailOrCancel at line 1909
pkg/jobs/registry.go in pkg/jobs.(*Registry).stepThroughStateMachine.func3 at line 1270
pkg/jobs/registry.go in pkg/jobs.(*Registry).stepThroughStateMachine at line 1271
pkg/jobs/adopt.go in pkg/jobs.(*Registry).runJob at line 415
pkg/jobs/adopt.go in pkg/jobs.(*Registry).resumeJob.func1 at line 336
pkg/util/stop/stopper.go in pkg/util/stop.(*Stopper).RunAsyncTaskEx.func2 at line 442
/usr/local/go/src/runtime/asm_amd64.s in runtime.goexit at line 1371
```

| Tag | Value |
|---|---|
| Cockroach Release | `v21.2.4-53-gb4a27f3634` |
| Cockroach SHA: | b4a27f3634e3e41dc3966214cf05ff6870c055c5 |
| Platform | linux amd64 |
| Distribution | CCL |
| Environment | development |
| Command | server |
| Go Version | ``|
| # of CPUs ||
| # of Goroutines ||

Jira issue: CRDB-13247

### PR DESCRIPTION
**Pull request by adityamaru**
The execCfg field on the restore resumer was not being set correctly
in the OnFailOrCancel hook. This would lead to a nil pointer exception
during cleanup.

Other jobs such as import, backup use the execCfg directly off the
JobExecContext instead of storing it on the resumer. An alternative to
this fix could be to change all `r.ExecCfg` to use the execCfg on the JobExecContext.

Fixes: #76720

Release note (bug fix): Fixes a nil pointer exception during the
cleanup of a failed or cancelled restore job.

### CODE REVIEW

File: pkg/ccl/backupccl/backup_test.go [hunk 1]
```diff
@@ -9854,3 +9854,37 @@ func TestBackupRestoreSeparateExplicitIsDefault(t *testing.T) {
 		sqlDB.Exec(t, "DROP DATABASE inc_fkdb;")
 	}
 }
+
+// TestOnFailOrCancelExecCfgNPE is a regression test that ensures the execCfg on
```
Comment (dt) [inline pkg/ccl/backupccl/backup_test.go:9858]: nit: I'd say it is more broad than just checking execCfg; it is checking that we cancel successfully after pausing mid-backup, which just happens to include this case, but covers others too, right?

**Review by dt — APPROVED** [review]

**Review by stevendanna — APPROVED** [review]

**Comment by adityamaru** [comment]
TFTRs!

bors r=dt,stevendanna
