### PR TITLE
changefeedccl: update timestamp on event descriptor cache hits

### LINKED ISSUE #156091: Changefeeds with CDC queries can fail when by replanning at an old GC'd timestamp
**Describe the problem**

If a changefeed is evaluating a row, it will retrieve the event descriptor from a cache. That event descriptor includes a timestamp which will be the first timestamp of an event on that table descriptor version, which could be well before the highwater.

In CDC queries, it uses that timestamp to replan the query if that descriptor version doesn't match the most recent one that it's seen.

This replan involves fetching the DB descriptor version. If the timestamp is too old (and the db descriptor has been GC'd) the feed will fail doing this replan. 

**To Reproduce**

Here is a commit with a test that reproduces the issue under stress:
https://github.com/cockroachdb/cockroach/compare/master...aerfrei:cockroach:ed-repro

In short:

At time t_0: We populate the cache on old descriptor version by consuming a row event. (Event 1: table desc version A)
We change the DB descriptor version and GC the old one.

We add a row to the table on that same table descriptor version. (Event 2 @ time t_1: table desc version A)
We change the table descriptor.
We add a row with the new table descriptor version. (Event 3: table desc version B)

These events come out of order from the kv feed, so we see events with table descriptor A then B then A.
Since both of these descriptor versions don't match the previous one, they cause query replans.

In that second replan, we hit the cache for the event descriptor (so we try to replan at time t_0).
Fetching the db descriptor at this time fails since it has been GC'd. 

**Expected behavior**
The feed should not fail, those KV events coming out of order should be tolerated. 
The replan should happen at a timestamp that has not been GC'd (e.g. t_1)

**Additional context**
What was the impact?
Could cause feeds to fail for customers.

See also https://github.com/cockroachlabs/support/issues/3455

Jira issue: CRDB-55786

### PR DESCRIPTION
**Pull request by aerfrei**
Before, in some cases we could replan a CDC query with an
old timestamp from the event descriptor cache, which would
try to read the database descriptor at an old potentially
garbage collected timestamp.

Now, we make sure the event descriptor cache always gives
events descriptors with an up to date timestamp.

Epic: none
Fixes: https://github.com/cockroachdb/cockroach/issues/156091

Release note (bug fix): A bug where changefeeds using CDC
queries could sometimes unexpectedly fail after a schema
change with a descriptor retrieval error has been fixed.

### CODE REVIEW

**Comment by aerfrei** [comment]
Linking my self-review notes here for future reference. https://docs.google.com/document/d/1aU6DtK8fZvLf5J7tyhINdReGpQUGND06vStDOxcJSkU/edit?tab=t.0

File: pkg/ccl/changefeedccl/cdcevent/event.go [hunk 1]
```diff
@@ -521,9 +521,14 @@ func getEventDescriptorCached(
...
-		ed := v.(*EventDescriptor)
-		if catalog.UserDefinedTypeColsHaveSameVersion(ed.td, desc) {
-			return ed, nil
+		cached := v.(*EventDescriptor)
+		if catalog.UserDefinedTypeColsHaveSameVersion(cached.td, desc) {
+			// Make a shallow copy to avoid modifying the cached value. The cached
+			// EventDescriptor is shared across changefeed operations and may be
+			// referenced concurrently.
+			ed := *cached
+			ed.SchemaTS = schemaTS
```
Comment (andyyang890) [inline pkg/ccl/changefeedccl/cdcevent/event.go:530]: We should add a release note (with category "bug fix") documenting the fix

File: pkg/ccl/changefeedccl/kvevent/testing_knobs.go [hunk 2]
```diff
@@ -9,7 +9,9 @@ import "context"
 
 // BlockingBufferTestingKnobs are testing knobs for blocking buffers.
 type BlockingBufferTestingKnobs struct {
-	BeforeAdd            func(ctx context.Context, e Event) (context.Context, Event)
+	// BeforeAdd is called before adding a KV event to the buffer. If the function
+	// returns false in the third return value, the event is skipped.
+	BeforeAdd            func(ctx context.Context, e Event) (returnedCtx context.Context, returnedE Event, shouldAdd bool)
```
Comment (andyyang890) [inline pkg/ccl/changefeedccl/kvevent/testing_knobs.go]: nit: remove the names for the return values, they're verbose and don't add much information

File: pkg/ccl/changefeedccl/helpers_test.go [hunk 3]
```diff
@@ -1732,6 +1732,19 @@ func forceTableGC(
 	}
 }
 
+func forceTableGCAtTimestamp(
+	t testing.TB,
+	tsi serverutils.TestServerInterface,
+	sqlDB *sqlutils.SQLRunner,
```
Comment (andyyang890) [inline pkg/ccl/changefeedccl/helpers_test.go]: nit: unused param

(might as well delete the analogous unused param in `forceTableGC` while you're at it)

File: pkg/ccl/changefeedccl/protected_timestamps_test.go [hunk 4]
```diff
@@ -1215,6 +1217,180 @@ func TestChangefeedPerTableProtectedTimestampProgression(t *testing.T) {
 	cdcTest(t, testFn, feedTestEnterpriseSinks)
 }
 
+// TestCachedEventDescriptorGivesUpdatedTimestamp is a regression test for
+// #156091. It tests that when a changefeed with a cdc query recieves events
```
Comment (andyyang890) [inline pkg/ccl/changefeedccl/protected_timestamps_test.go]: nit: typo
```suggestion
// #156091. It tests that when a changefeed with a cdc query receives events
```

File: pkg/ccl/changefeedccl/protected_timestamps_test.go [hunk 5]
```diff
@@ -1215,6 +1217,180 @@ func TestChangefeedPerTableProtectedTimestampProgression(t *testing.T) {
...
+			return ctx, e, true
+		}
+
+		knobs.MakeKVFeedToAggregatorBufferKnobs = func() kvevent.BlockingBufferTestingKnobs {
+			return kvevent.BlockingBufferTestingKnobs{
+				BeforeAdd: beforeAddKnob,
+			}
+		}
+
+		foo := feed(t, f, `CREATE CHANGEFEED WITH RESOLVED = '10ms' AS SELECT * FROM foo`)
```
Comment (andyyang890) [inline pkg/ccl/changefeedccl/protected_timestamps_test.go]: nit: don't capitalize option name
```suggestion
		foo := feed(t, f, `CREATE CHANGEFEED WITH resolved = '10ms' AS SELECT * FROM foo`)
```

File: pkg/ccl/changefeedccl/protected_timestamps_test.go [hunk 6]
```diff
@@ -1215,6 +1217,180 @@ func TestChangefeedPerTableProtectedTimestampProgression(t *testing.T) {
...
+// Previously, we would get an old timestamp from the cached event descriptor
+// and if the db descriptor version had changed and been GC'd, this replan would
+// fail, failing the changefeed.
+func TestCachedEventDescriptorGivesUpdatedTimestamp(t *testing.T) {
+	defer leaktest.AfterTest(t)()
+	defer log.Scope(t).Close(t)
+
+	testFn := func(t *testing.T, s TestServerWithSystem, f cdctest.TestFeedFactory) {
+		sqlDB := sqlutils.MakeSQLRunner(s.DB)
+		spanconfigjob.ReconciliationJobCheckpointInterval.Override(
```
Comment (andyyang890) [inline pkg/ccl/changefeedccl/protected_timestamps_test.go]: Can you add a comment explaining why changing this setting is necessary?

File: pkg/ccl/changefeedccl/protected_timestamps_test.go [hunk 7]
```diff
@@ -1215,6 +1217,180 @@ func TestChangefeedPerTableProtectedTimestampProgression(t *testing.T) {
...
+
+		knobs := s.TestingKnobs.
+			DistSQL.(*execinfra.TestingKnobs).
+			Changefeed.(*TestingKnobs)
+
+		var dbDescTS atomic.Value
+		dbDescTS.Store(hlc.Timestamp{})
+		hasGCdDBDesc := atomic.Bool{}
+		kvEvents := []kvevent.Event{}
+		hasProcessedEvents := atomic.Bool{}
```
Comment (andyyang890) [inline pkg/ccl/changefeedccl/protected_timestamps_test.go]: nit: prefer implicit zero value initialization
```suggestion
		var hasGCdDBDesc atomic.Bool
		var kvEvents []kvevent.Event
		var hasProcessedEvents atomic.Bool
```

File: pkg/ccl/changefeedccl/protected_timestamps_test.go [hunk 8]
```diff
@@ -1215,6 +1217,180 @@ func TestChangefeedPerTableProtectedTimestampProgression(t *testing.T) {
...
+		)
+
+		// Making sure there's only one worker so that there is a single event
+		// descriptor cache. This means that the later events will use the
+		// cached event descriptor and its outdated timestamp, to properly
+		// reproduce the issue.
+		changefeedbase.EventConsumerWorkers.Override(
+			context.Background(), &s.Server.ClusterSettings().SV, 1)
+
+		sqlDB.Exec(t, `CREATE TABLE foo (a INT PRIMARY KEY)`)
```
Comment (andyyang890) [inline pkg/ccl/changefeedccl/protected_timestamps_test.go]: nit: move this closer to where it's actually used

File: pkg/ccl/changefeedccl/protected_timestamps_test.go [hunk 9]
```diff
@@ -1215,6 +1217,180 @@ func TestChangefeedPerTableProtectedTimestampProgression(t *testing.T) {
...
+
+		knobs := s.TestingKnobs.
```
Comment (andyyang890) [inline pkg/ccl/changefeedccl/protected_timestamps_test.go]: nit: move this closer to where it's actually used

File: pkg/ccl/changefeedccl/protected_timestamps_test.go [hunk 10]
```diff
@@ -1215,6 +1217,180 @@ func TestChangefeedPerTableProtectedTimestampProgression(t *testing.T) {
...
+			DistSQL.(*execinfra.TestingKnobs).
+			Changefeed.(*TestingKnobs)
+
+		var dbDescTS atomic.Value
```
Comment (andyyang890) [inline pkg/ccl/changefeedccl/protected_timestamps_test.go:1289]: Can you add a comment explaining what this test is doing? I'm having some trouble following the exact sequence of events

**Review by andyyang890 — CHANGES_REQUESTED** [review]

File: pkg/ccl/changefeedccl/kvevent/testing_knobs.go (hunk 2 above)
Comment (aerfrei) [reply pkg/ccl/changefeedccl/kvevent/testing_knobs.go]: I thought it was helpful for code completion to know if for this boolean true meant include or skip which is why I added it. It is in the comment anyway so I can remove it though.

File: pkg/ccl/changefeedccl/protected_timestamps_test.go (hunk 10 above)
Comment (aerfrei) [reply pkg/ccl/changefeedccl/protected_timestamps_test.go:1289]: I added a long comment which is hopefully worth the length.

File: pkg/ccl/changefeedccl/cdcevent/event.go (hunk 1 above)
Comment (andyyang890) [reply pkg/ccl/changefeedccl/cdcevent/event.go:530]: Could you update the release note to provide more detail on when the bug could occur? (e.g. "A bug where changefeeds using CDC queries could sometimes unexpectedly fail after a schema change with a descriptor retrieval error has been fixed.")

(I want to place less emphasis on the lower-level implementation details and more on symptoms. Also, if we're going to mention replanning, I want to make it clear that we're not referring to the replanning of the entire changefeed, which is how I interpreted when I first read it)

(Also, release notes should be past tense, see https://cockroachlabs.atlassian.net/wiki/spaces/CRDB/pages/186548364/Release+notes)

File: pkg/ccl/changefeedccl/protected_timestamps_test.go [hunk 11]
```diff
@@ -1215,6 +1217,221 @@ func TestChangefeedPerTableProtectedTimestampProgression(t *testing.T) {
...
+			happens when a changefeed is replanning a CDC query for a table descriptor
+			version it has seen before. In that case, it replans the query at the
+			timestamp (stored in the cache) of the first event it saw for that table
+			descriptor version.
+
+			That's problematic because that could be well before the highwater for
+			the feed and therefore not protected by PTS. Even though our protected
+			timestamp system ensures that the relevant table descriptor version has
+			not been GC'd, there is no such guarantee that the *DB* descriptor version
+			from that time has not been GC'd. If we try to fetch the DB descriptor
```
Comment (andyyang890) [inline pkg/ccl/changefeedccl/protected_timestamps_test.go]: > Even though our protected timestamp system ensures that the relevant table descriptor version has not been GC'd, there is no such guarantee that the *DB* descriptor version from that time has not been GC'd.

Hmm is this sentence correct? Table/DB descriptors are both stored in the `system.descriptor` table right? Is it more that the table descriptors have been cached but the DB descriptors haven't?

File: pkg/ccl/changefeedccl/protected_timestamps_test.go (hunk 10 above)
Comment (andyyang890) [reply pkg/ccl/changefeedccl/protected_timestamps_test.go:1289]: Much appreciated, thanks

File: pkg/ccl/changefeedccl/kvevent/testing_knobs.go (hunk 2 above)
Comment (asg0451) [reply pkg/ccl/changefeedccl/kvevent/testing_knobs.go]: drive by: i actually like named return values for documentation when they provide value. however only the bool needs clarification. how about `func(ctx context.Context, e Event) (_ context.Context, _ Event, shouldAdd bool)`?

Comment (andyyang890) [reply pkg/ccl/changefeedccl/kvevent/testing_knobs.go]: Yeah I'd be ok with that. If we add it back, I'd also like to see the named return value used for all implementations of the hook in tests

Comment (aerfrei) [reply pkg/ccl/changefeedccl/kvevent/testing_knobs.go]: Nice, I like that, I'll do that.

File: pkg/ccl/changefeedccl/protected_timestamps_test.go (hunk 11 above)
Comment (aerfrei) [reply pkg/ccl/changefeedccl/protected_timestamps_test.go]: This sentence is correct in the sense that that table descriptor version is still live (we haven't yet emitted a changefeed message for Event 2) and therefore protected. This means that even reads as of timestamp t_0 will succeed for reading the table descriptor version. We are reading it with a query and not merely getting it from the cache. On the other hand, reads of the db descriptor version at that same timestamp will fail since it's been GC'd. 

Edit: Also edited the comment to clarify.

File: pkg/ccl/changefeedccl/protected_timestamps_test.go [hunk 12]
```diff
@@ -1215,6 +1217,223 @@ func TestChangefeedPerTableProtectedTimestampProgression(t *testing.T) {
...
+			5. We update the table descriptor version (to version 2) and make an
+			update (event 3).
+			6. The KV event for event 3 comes in first, causing the changefeed's
+			current table version to be table version 2.
+			7. The KV event for event 2 comes in out of order causing a replan of
+			the CDC query to happen (back to table descriptor version 1).
+
+			If we return the timestamp from the first event we saw on table descriptor
+			version 1, this replan will try to fetch the DB descriptor at time T_0
+			(when event 1 happened)	which has been garbage collected and would fail
```
Comment (andyyang890) [inline pkg/ccl/changefeedccl/protected_timestamps_test.go]: placeholder

**Review by andyyang890 — APPROVED** [review]
Nice work!
