### PR TITLE
backupccl: display correct statement for `SHOW BACKUP with privileges`

### LINKED ISSUE #77617: show backup: with privileges generates incorrect grant statement for types
**Describe the problem**

The `SHOW BACKUP ... WITH PRIVILEGES` statement generates grant statements for type objects with the incorrect GRANT syntax. The generated grant is missing the TYPE keyword.

This is what is generated:
`GRANT ALL ON status TO j4;`

And this is the correct GRANT statement
`GRANT ALL ON TYPE status TO j4;`

**To Reproduce**

```
j4@j4-mr-demo/defaultdb> CREATE TYPE status AS ENUM ('open', 'closed', 'inactive');
CREATE TYPE

j4@j4-mr-demo/defaultdb> show types;
  schema |  name  | owner
---------+--------+--------
  public | status | j4
(1 row)

j4@j4-mr-demo/defaultdb> BACKUP DATABASE defaultdb
INTO 'gs://j4-demo-cc-storage/backups/defaultdb-privs?AUTH=specified&CREDENTIALS=<redacted>'
AS OF SYSTEM TIME '-10s';

        job_id       |  status   | fraction_completed | rows | index_entries | bytes
---------------------+-----------+--------------------+------+---------------+--------
  743386127694954499 | succeeded |                  1 |    0 |             0 |     0
(1 row)

 SHOW BACKUPS IN
'gs://j4-demo-cc-storage/backups/defaultdb-privs?AUTH=specified&CREDENTIALS=<redacted>';

          path
-------------------------
  /2022/03/10-173711.35
(1 row)

j4@j4-mr-demo/defaultdb> select object_name, object_type, privileges
from [SHOW BACKUP
'gs://j4-demo-cc-storage/backups/defaultdb-privs/2022/03/10-173711.35?AUTH=specified&CREDENTIALS=<redacted>'
WITH privileges]
where object_type = 'type';

  object_name | object_type |                                                         privileges
--------------+-------------+------------------------------------------------------------------------------------------------------------------------------
  status      | type        | GRANT ALL ON status TO admin; GRANT ALL ON status TO j4; GRANT USAGE ON status TO public; GRANT ALL ON status TO root;
  _status     | type        | GRANT ALL ON _status TO admin; GRANT ALL ON _status TO j4; GRANT USAGE ON _status TO public; GRANT ALL ON _status TO root;
(2 rows)
```

**Expected behavior**
Type grants should include the TYPE keyword

**Environment:**
```
j4@j4-mr-demo/defaultdb> select version();
                                          version
-------------------------------------------------------------------------------------------
  CockroachDB CCL v21.2.6 (x86_64-unknown-linux-gnu, built 2022/02/22 18:30:37, go1.16.6)
(1 row)
```

**Impact**
Customers have to manually edit the grant statements generated by `SHOW BACKUP ... WITH PRIVILEGES` making it difficult to automate the restoration of a database with its grants into another cluster.

### PR DESCRIPTION
**Pull request by msbutler**
Fixes #77617

Release note (sql change): Previously, `SHOW BACKUP with privileges` displayed
grant statments with incorrect syntax; specifically, without the object type.
This patch fixes this.

As an example, previously displayed:
GRANT ALL ON status TO j4;

Now displayed:
GRANT ALL ON TYPE status TO j4;

### CODE REVIEW

File: pkg/ccl/backupccl/show_test.go [hunk 1]
```diff
@@ -413,19 +413,19 @@ GRANT UPDATE ON top_secret TO agent_bond;
...
-				`GRANT ALL ON locator TO root; `, `root`},
-			{`continent`, `type`, `GRANT ALL ON continent TO admin; GRANT ALL ON continent TO m; GRANT USAGE ON continent TO public; GRANT ALL ON continent TO root; `, `root`},
-			{`_continent`, `type`, `GRANT ALL ON _continent TO admin; GRANT USAGE ON _continent TO public; GRANT ALL ON _continent TO root; `, `root`},
-			{`agent_locations`, `table`, `GRANT ALL ON agent_locations TO admin; ` +
-				`GRANT SELECT ON agent_locations TO agent_bond; GRANT UPDATE ON agent_locations TO agents; ` +
-				`GRANT ALL ON agent_locations TO m; GRANT ALL ON agent_locations TO root; `, `root`},
-			{`top_secret`, `table`, `GRANT ALL ON top_secret TO admin; ` +
-				`GRANT SELECT, UPDATE ON top_secret TO agent_bond; GRANT INSERT ON top_secret TO agents; ` +
-				`GRANT ALL ON top_secret TO m; GRANT ALL ON top_secret TO root; `, `root`},
+			{`mi5`, `database`, `GRANT ALL ON DATABASE mi5 TO admin; GRANT ALL ON DATABASE mi5 TO agents; GRANT CONNECT ON DATABASE mi5 TO public; GRANT ALL ON DATABASE mi5 TO root; `, `root`},
```
Comment (adityamaru) [inline pkg/ccl/backupccl/show_test.go:416]: this is screaming to be a datadriven test 😋  I won't force you, but consider it

**Review by adityamaru — APPROVED** [review]

File: pkg/ccl/backupccl/show_test.go (hunk 1 above)
Comment (msbutler) [reply pkg/ccl/backupccl/show_test.go:416]: bahaha. yeah I know. I'd like to merge this and do the big transfer for SHOW BACKUP all at once at some point.

Comment (adityamaru) [reply pkg/ccl/backupccl/show_test.go:416]: should we backport?

Comment (adityamaru) [reply pkg/ccl/backupccl/show_test.go:416]: oh nevermind, you added the tags 👍

**Comment by msbutler** [comment]
TFTR!

bors r=adityamaru
