### PR TITLE
sql: Fix the re-ordering of reults in upserts with returning

### LINKED ISSUE #29495: sql: panic in INSERT ... ON CONFLICT
```
root@:26257/backboard> *
* ERROR: [n1,client=[::1]:50098,user=root] a SQL panic has occurred while executing "INSERT INTO repos(github_owner, github_repo) VALUES ($1, $2) ON CONFLICT (github_owner, github_repo) DO UPDATE SET github_owner = excluded.github_owner RETURNING id": invalid datum type given: string, expected int
*
*
* ERROR: [n1,client=[::1]:50098,user=root] a panic has occurred!
*
panic while executing 1 statements: INSERT INTO _(_, _) VALUES ($1, $2) ON CONFLICT (_, _) DO UPDATE SET _ = _._ RETURNING _; caused by invalid datum type given: string, expected int

goroutine 177967 [running]:
runtime/debug.Stack(0x6a27780, 0xc42e554bc0, 0x3)
	/usr/local/Cellar/go/1.10.3/libexec/src/runtime/debug/stack.go:24 +0xa7
github.com/cockroachdb/cockroach/pkg/util/log.ReportPanic(0x6a27780, 0xc42e554bc0, 0xc42062b980, 0x63736c0, 0xc427d27770, 0x1)
	/Users/benesch/go/src/github.com/cockroachdb/cockroach/pkg/util/log/crash_reporting.go:213 +0xa5
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).closeWrapper(0xc429716000, 0x6a27780, 0xc42e554bc0, 0x609e3a0, 0xc4262291a0)
	/Users/benesch/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:668 +0x2df
github.com/cockroachdb/cockroach/pkg/sql.(*Server).ServeConn.func1(0xc429716000, 0x6a27780, 0xc42e554bc0)
	/Users/benesch/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:414 +0x61
panic(0x609e3a0, 0xc4262291a0)
	/usr/local/Cellar/go/1.10.3/libexec/src/runtime/panic.go:502 +0x229
github.com/cockroachdb/cockroach/pkg/sql/sqlbase.DatumToEncDatum(0x1, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/Users/benesch/go/src/github.com/cockroachdb/cockroach/pkg/sql/sqlbase/encoded_datum.go:161 +0x281
github.com/cockroachdb/cockroach/pkg/sql.(*planNodeToRowSource).Next(0xc425cfa900, 0x0, 0xc426623ee8, 0x5145530, 0xc420343180)
	/Users/benesch/go/src/github.com/cockroachdb/cockroach/pkg/sql/plan_node_to_row_source.go:207 +0x102
github.com/cockroachdb/cockroach/pkg/sql/distsqlrun.Run(0x6a27840, 0xc425083080, 0x6a30f80, 0xc425cfa900, 0x6a05640, 0xc424ece380)
	/Users/benesch/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsqlrun/base.go:170 +0x35
github.com/cockroachdb/cockroach/pkg/sql.(*planNodeToRowSource).Run(0xc425cfa900, 0x6a27840, 0xc425083080, 0x0)
	/Users/benesch/go/src/github.com/cockroachdb/cockroach/pkg/sql/plan_node_to_row_source.go:264 +0x96
github.com/cockroachdb/cockroach/pkg/sql/distsqlrun.(*Flow).StartSync(0xc42ce96c40, 0x6a27840, 0xc425083080, 0x662f978, 0xc42676e0e0, 0x6a05240)
	/Users/benesch/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsqlrun/flow.go:594 +0x191
github.com/cockroachdb/cockroach/pkg/sql.(*DistSQLPlanner).Run(0xc420aa8200, 0xc4268d0720, 0xc4264e0320, 0xc426624808, 0xc425e8a780, 0xc4297164d0, 0x0)
	/Users/benesch/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsql_running.go:245 +0x879
github.com/cockroachdb/cockroach/pkg/sql.(*DistSQLPlanner).PlanAndRun(0xc420aa8200, 0x6a27840, 0xc425082b10, 0xc4297164d0, 0xc4268d0720, 0xc4264e0320, 0x6a1ac80, 0xc42836eb00, 0xc425e8a780)
	/Users/benesch/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsql_running.go:735 +0x24c
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execWithDistSQLEngine(0xc429716000, 0x6a27840, 0xc425082b10, 0xc429716438, 0x3, 0xc200460, 0xc4259b4360, 0xc425e8da00, 0x1, 0x1)
	/Users/benesch/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:966 +0x2d8
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).dispatchToExecutionEngine(0xc429716000, 0x6a27840, 0xc425082b10, 0x6a2a880, 0xc4264e4320, 0xc425e8da40, 0x1, 0x1, 0xc4260d7a20, 0xa4, ...)
	/Users/benesch/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:808 +0x688
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execStmtInOpenState(0xc429716000, 0x6a27840, 0xc425082b10, 0x6a2a880, 0xc4264e4320, 0xc425e8da40, 0x1, 0x1, 0xc4260d7a20, 0xa4, ...)
	/Users/benesch/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:401 +0xb82
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execStmt(0xc429716000, 0x6a27840, 0xc425082b10, 0x6a2a880, 0xc4264e4320, 0xc425e8da40, 0x1, 0x1, 0xc4260d7a20, 0xa4, ...)
	/Users/benesch/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:95 +0x358
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).run(0xc429716000, 0x6a27780, 0xc42e554bc0, 0xc42d6d2960, 0x0, 0x0)
	/Users/benesch/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:1135 +0x13cd
github.com/cockroachdb/cockroach/pkg/sql.(*Server).ServeConn(0xc420972360, 0x6a27780, 0xc42e554bc0, 0xc4251a7022, 0x9, 0xc4251a7031, 0x4, 0x0, 0x0, 0x6a09180, ...)
	/Users/benesch/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:416 +0x1bb
github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*conn).serveImpl.func3(0xc420972360, 0x6a27780, 0xc42e554bc0, 0xc42783a1c0, 0x5400, 0x15000, 0xc4206c1ec0, 0xc42d6d2960, 0xc42d6d2950, 0xc42726c380, ...)
	/Users/benesch/go/src/github.com/cockroachdb/cockroach/pkg/sql/pgwire/conn.go:267 +0x122
created by github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*conn).serveImpl
	/Users/benesch/go/src/github.com/cockroachdb/cockroach/pkg/sql/pgwire/conn.go:266 +0xf04

*
* ERROR: [n1,client=[::1]:50098,user=root] Reported as error eaaf81189bfe4ab496040203c15e1b9b
*

Error: interrupted
Failed running "sql"
```

The full schema/query are:

```sql
CREATE TABLE IF NOT EXISTS repos (
	id serial PRIMARY KEY,
	github_owner string NOT NULL,
	github_repo string NOT NULL,
	UNIQUE (github_owner, github_repo)
);

INSERT INTO repos (github_owner, github_repo)
VALUES ($1, $2)
ON CONFLICT (github_owner, github_repo) DO UPDATE SET github_owner = excluded.github_owner			RETURNING id
```

@knz for triage

### PR DESCRIPTION
**Pull request by BramGruneir**
There were two bugs here.

The first, was in makeResultFromInsertRow() which would not reorder the result
row if the length of the result row matched the input row.

The second, was we would perform the reordering twice, which in the added test
case would reorder the result back to that of the input.

Fixes #29495

Release note (bug fix): Fixed a bug in which columns could be reordered when
using an upsert with a returning clause. This often would cause a panic.

### CODE REVIEW

**Review by knz — APPROVED** [review]
Awesome, congrats for figuring it out. It seems like a small change but it was all trouble to hunt down.

I am concerned about the mandatory reordering though. This is likely to impact performance. @jordanlewis what do you think?

> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/30328#-:-LMdVSLHA0yUbJw_v7cL:bb2u6d9)* status: :shipit: complete! 0 of 0 LGTMs obtained

**Review by jordanlewis — APPROVED** [review]
Hmm yeah I would have to agree with @knz... is there no way to avoid deleting the fast path here?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/30328#-:-LMdaruG5zxYBOH6IzDn:b-fjv4x9)* status: :shipit: complete! 0 of 0 LGTMs obtained

**Review by BramGruneir — COMMENTED** [review]
Done.  I added a check for the non-reordering fast path.  Was pretty straightforward to add.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/30328#-:-LMh9hxw27n9UXPSFkAe:b1yek31)* status: :shipit: complete! 0 of 0 LGTMs obtained

**Comment by jordanlewis** [comment]
Looks like this is failing `TestUpsertWithColumnMutationAndNotNullDefault ` - just commenting in case you didn't notice :)

**Review by knz — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/30328#-:-LMhUUrM4kM44yLr9qBw:bnfp4nl)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

**Review by knz — COMMENTED** [review]
I wrote LGTM but the CI tests say otherwise.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/30328#-:-LMhU_LW5sD-Bdd07Z1Y:b-rwnbln)* status: :shipit: complete! 1 of 0 LGTMs obtained

**Comment by BramGruneir** [comment]
Ok, after  bit of a battle, I re-wrote a good chunk of this.

Please take a look and make sure I didn't miss anything.  It finally passes all the tests.

The fastpath to skip the reordering is still there for inserts, but not for conflict updates.  I couldn't find an easy way to add that one.

File: pkg/sql/tablewriter_upsert.go [hunk 1]
```diff
@@ -30,19 +30,22 @@ import (
 type tableUpserterBase struct {
 	tableWriterBase
 
-	ri          sqlbase.RowInserter
-	alloc       *sqlbase.DatumAlloc
+	ri    sqlbase.RowInserter
+	alloc *sqlbase.DatumAlloc
+
+	// Should we collect the rows for a RETRUNING clause?
```
Comment (jordanlewis) [inline pkg/sql/tablewriter_upsert.go]: nit: RETURNING

File: pkg/sql/tablewriter_upsert.go [hunk 2]
```diff
@@ -30,19 +30,22 @@ import (
...
-	// back to indices in rowTemplate. Contains dontReturnCol (-1) for indices
-	// in the inserted rows that are mutation columns which shouldn't be returned
-	// to the user.
-	rowIdxToRetIdx []int
+
+	// A mapping of column IDs to the return index used to shape the resulting
+	// rows to those required by the returning clause.
+	colIDToReturnIndex map[sqlbase.ColumnID]int
+
+	// Do the results rows have a different order than insert rows.
```
Comment (jordanlewis) [inline pkg/sql/tablewriter_upsert.go]: nit: result rows

File: pkg/sql/tablewriter_upsert.go [hunk 3]
```diff
@@ -73,32 +72,27 @@ func (tu *tableUpserterBase) init(txn *client.Txn, evalCtx *tree.EvalContext) er
...
-	for i, col := range tu.ri.InsertCols {
-		retID, ok := colIDToRetIndex[col.ID]
-		if !ok {
-			// If the column is missing, it means it's a mutation column. Put -1 in
-			// the map to signal that we don't want it in the returning row.
-			retID = dontReturnCol
+		tu.colIDToReturnIndex[col.ID] = i
+	}
+
+	if len(tu.ri.InsertColIDtoRowIndex) == len(tu.colIDToReturnIndex) {
```
Comment (jordanlewis) [inline pkg/sql/tablewriter_upsert.go]: It occurs to me - is all of this work necessary if `collectRows` is false?

File: pkg/sql/tablewriter_upsert_strict.go [hunk 4]
```diff
@@ -68,11 +66,16 @@ func (tu *strictTableUpserter) atBatchEnd(ctx context.Context, traceKV bool) err
 			return err
 		}
 
-		// for ... RETURNING clause
-		resultRow := tu.makeResultFromInsertRow(insertRow, tableDesc.Columns)
```
Comment (jordanlewis) [inline pkg/sql/tablewriter_upsert_strict.go]: we did this unconditionally before? Oops - this might be a decent speedup?

**Review by jordanlewis — COMMENTED** [review]
Nice work, I'm wondering whether there's still a bunch of redundant work in here in general - do we need to create the resultRow at all if we don't have a returning statement?

**Review by knz — COMMENTED** [review]
No more comment than jordan's for me

> Reviewed 3 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/30328#-:-LMmQMu64E8JLdHZj_ae:bfrzaya)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

**Review by BramGruneir — COMMENTED** [review]
So I went through and removed what I hope is a good amount of the redundant work.  It wasn't much, but these were running per row.

I think this is good to merge, just please take a quick look at the final changes.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/30328#-:-LMmUh1V-gjYIZZIaCJ3:b-lxhlk)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/sql/tablewriter_upsert.go, line 86 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/30328#-LMdQ2c5Hi8g_4MP3llT-r3-86:-LMmUYR57k6OUP9sJHNe:b-kx1qeu) ([raw file](https://github.com/cockroachdb/cockroach/blob/73a55cf29653afb251ffccc084185f4715bfffb2/pkg/sql/tablewriter_upsert.go#L86)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

It occurs to me - is all of this work necessary if `collectRows` is false?
</blockquote></details>

Good idea.  Done.  And I added some extra safeguards.

**Review by jordanlewis — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/30328#-:-LMnORh37SjAvn3Hth3m:bnfp4nl)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale)

___
*[pkg/sql/tablewriter_upsert.go, line 170 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/30328#-LMnOA2o706o60kL0I0n:-LMnOA2o706o60kL0I0o:bgt1uxs) ([raw file](https://github.com/cockroachdb/cockroach/blob/1c4a982b6b703dc58e114620fd16d33683aee1bf/pkg/sql/tablewriter_upsert.go#L170)):*
> ```Go
> 			resultRow[returnIndex] = row[rowIndex]
> 		} else {
> 			resultRow[returnIndex] = tree.DNull
> ```

Sorry for not noticing this in an earlier review, but I liked the comment that was here before - if you don't mind, could you restore it? It's not obvious what's going on - this filling with nulls isn't just for kicks, the columns we're filling with nulls didn't get any values inserted and that's why we've got to give nulls back to the user.

**Comment by BramGruneir** [comment]
___
*[pkg/sql/tablewriter_upsert.go, line 170 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/30328#-LMnOA2o706o60kL0I0n:-LMrezk1DyCYuPa6y7AU:b4fat2z) ([raw file](https://github.com/cockroachdb/cockroach/blob/1c4a982b6b703dc58e114620fd16d33683aee1bf/pkg/sql/tablewriter_upsert.go#L170)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

Sorry for not noticing this in an earlier review, but I liked the comment that was here before - if you don't mind, could you restore it? It's not obvious what's going on - this filling with nulls isn't just for kicks, the columns we're filling with nulls didn't get any values inserted and that's why we've got to give nulls back to the user.
</blockquote></details>

Not a problem, always happy to have more comments.  Done.
