### PR TITLE
sql: dedupe on search path schema when resolving functions

### LINKED ISSUE #97130: sql: unable to resolve UDF when there are duplicate values in the search_path
If there are duplicate items in the `search_path` Cockroach is unable to resolve a UDF without specifically setting the schema. This bug was discovered because DBeaver sets the `search_path` to `public, public, "$user"`, but the issue can be recreated by creating two instances of `public` in the search path via any tool. 

Re-create: 
1. Set up CockroachDB cluster
2. Create a UDF in the public schema
3. Edit search path -> `set search_path=public, public;`
4. Call function without specifying the schema name
5. Observe `ERROR: ambiguous call:` 
6. Call function by prepending `public.` to the function name to have it execute successfully 

**Expected behavior**
Instead of throwing an error, we should be able to resolve this function even though there are dupes in the `search_path`. PostgreSQL is able to handle the duplicates without error. 

**Environment:**
 - Client version: CockroachDB CCL v22.1.8 (x86_64-apple-darwin19, built 2022/09/29 14:38:41, go1.17.11)
 - Server version: CockroachDB CCL v22.2.3 (x86_64-pc-linux-gnu, built 2023/01/23 19:11:57, go1.19.1)
 - Client app: DBeaver, but can be recreated on any app
 

Jira issue: CRDB-24532

### PR DESCRIPTION
**Pull request by chengxiong-ruan**
Fixes: #97130
Previously, if there are duplicate schemas in current searcth path function resolution would fail due to ambiguity because a UDF was seen twice. This commit adds logic to dedupe on the search path schema.

Release note: None

### CODE REVIEW

**Review by fqazi — APPROVED** [review]
:LGTM:

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/97634#-:-NP3P4pl7fFf3s6arUrB:bmxilld)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @chengxiong-ruan)

File: pkg/sql/schema_resolver.go [hunk 1]
```diff
@@ -528,6 +528,7 @@ func maybeLookUpUDF(
 	}
 
 	var udfDef *tree.ResolvedFunctionDefinition
+	var schemaLookedup catalog.DescriptorIDSet
```
Comment (ajwerner) [inline pkg/sql/schema_resolver.go:531]: I think this is going to hurt performance in the happy path. I wonder if the `SearchPath` object itself should track duplicates. I think it'd be cheaper generally if we put a `FastIntSet` in the `SearchPath` and then had a way to ask if a schema was duplicated. WDYT?

Comment (ajwerner) [reply pkg/sql/schema_resolver.go:531]: I think it'd be okay for that to be quadratic.

Consider:
```go
diff --git a/pkg/sql/sessiondata/search_path.go b/pkg/sql/sessiondata/search_path.go
index 8d92fc799b0..018f6fa3b86 100644
--- a/pkg/sql/sessiondata/search_path.go
+++ b/pkg/sql/sessiondata/search_path.go
@@ -19,6 +19,7 @@ import (
        "github.com/cockroachdb/cockroach/pkg/sql/pgwire/pgcode"
        "github.com/cockroachdb/cockroach/pkg/sql/pgwire/pgerror"
        "github.com/cockroachdb/cockroach/pkg/sql/sem/catconstants"
+       "github.com/cockroachdb/cockroach/pkg/util/intsets"
 )
 
 // DefaultSearchPath is the search path used by virgin sessions.
@@ -35,6 +36,7 @@ type SearchPath struct {
        containsPgTempSchema bool
        tempSchemaName       string
        userSchemaName       string
+       duplicatedIndexes    intsets.Fast
 }
 
 // EmptySearchPath is a SearchPath with no schema names in it.
@@ -49,25 +51,29 @@ func DefaultSearchPathForUser(userName username.SQLUsername) SearchPath {
 // MakeSearchPath returns a new immutable SearchPath struct. The paths slice
 // must not be modified after hand-off to MakeSearchPath.
 func MakeSearchPath(paths []string) SearchPath {
-       containsPgCatalog := false
-       containsPgExtension := false
-       containsPgTempSchema := false
-       for _, e := range paths {
+       exists := func(haystack []string, needle string) bool {
+               for i := range haystack {
+                       if haystack[i] == needle {
+                               return true
+                       }
+               }
+               return false
+       }
+       sp := SearchPath{paths: paths}
+       for i, e := range paths {
                switch e {
                case catconstants.PgCatalogName:
-                       containsPgCatalog = true
+                       sp.containsPgCatalog = true
                case catconstants.PgTempSchemaName:
-                       containsPgTempSchema = true
+                       sp.containsPgTempSchema = true
                case catconstants.PgExtensionSchemaName:
-                       containsPgExtension = true
+                       sp.containsPgExtension = true
+               }
+               if exists(paths[:i], e) {
+                       sp.duplicatedIndexes.Add(i)
                }
        }
-       return SearchPath{
-               paths:                paths,
-               containsPgCatalog:    containsPgCatalog,
-               containsPgExtension:  containsPgExtension,
-               containsPgTempSchema: containsPgTempSchema,
-       }
+       return sp
 }
 
```

Comment (chengxiong-ruan) [reply pkg/sql/schema_resolver.go:531]: Fantastic idea. I like it.

Comment (chengxiong-ruan) [reply pkg/sql/schema_resolver.go]: Done what you suggested!

**Review by ajwerner — COMMENTED** [review]
I don't think this quite works. I don't think we want the behavior of the `SearchPathIter` to change per se.

Consider:
```
postgres=# set search_path = a,a,a
postgres-# ;
SET
postgres=# show search_path;
 search_path 
-------------
 a, a, a
(1 row)
```

In fact, I could see waiting it just report whether the entry is a duplicate. I think we want to make sure we display the search path as having the duplicates etc. I feel like what we may want to do here is, to some extent, address then `TODO`s in `NumElements` and `GetSchema` and then deal add a method `IsDuplicate(ord int)`.

It's not *super* trivial to do that, but I also don't think it's super hard either.

**Comment by chengxiong-ruan** [comment]
> I don't think this quite works. I don't think we want the behavior of the `SearchPathIter` to change per se.
> 
> Consider:
> 
> ```
> postgres=# set search_path = a,a,a
> postgres-# ;
> SET
> postgres=# show search_path;
>  search_path 
> -------------
>  a, a, a
> (1 row)
> ```
> 
> In fact, I could see waiting it just report whether the entry is a duplicate. I think we want to make sure we display the search path as having the duplicates etc. I feel like what we may want to do here is, to some extent, address then `TODO`s in `NumElements` and `GetSchema` and then deal add a method `IsDuplicate(ord int)`.
> 
> It's not _super_ trivial to do that, but I also don't think it's super hard either.

I see. `SHOW search_path` still shows the duplicates since we just return the value stored in session data without iterating. But I agree that let's leave the iterator alone for now. What other risks are you seeing if we change the iterate behavior here?

**Comment by chengxiong-ruan** [comment]
As discussed with @ajwerner offline that it's fine to dedupe within the iterator as long as `show search_path` returns what users set. Also added a logic test to show that.

**Review by ajwerner — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/97634#-:-NPJMY6EBgld9tqHfrdv:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @fqazi)

**Comment by chengxiong-ruan** [comment]
TFTR!
bors r+
