### PR TITLE
cli: deflake TestZip

### LINKED ISSUE #44717: cli: TestZip failed
[(cli).TestZip failed](https://teamcity.cockroachdb.com/viewLog.html?buildId=1729104&tab=buildLog) on [master@c7a19fa36c219936277aca80e2f3c0c89c832c58](https://github.com/cockroachdb/cockroach/commits/c7a19fa36c219936277aca80e2f3c0c89c832c58):

```
W200204 20:32:40.697292 17202417 storage/node_liveness.go:546  [n1,liveness-hb] slow heartbeat took 11.1s
W200204 20:32:40.697346 17202417 storage/node_liveness.go:471  [n1,liveness-hb] failed node liveness heartbeat: operation "node liveness heartbeat" timed out after 4.5s
W200204 20:32:41.818995 17202368 storage/store_raft.go:496  [n1,s1,r1/1:/{Min-System/NodeL…}] handle raft ready: 1.1s [applied=1, batches=1, state_assertions=0]
W200204 20:32:41.819281 17202329 storage/store_raft.go:496  [n1,s1,r6/1:/Table/{SystemCon…-11}] handle raft ready: 1.1s [applied=1, batches=1, state_assertions=0]
W200204 20:32:42.396319 17202350 storage/store_raft.go:496  [n1,s1,r2/1:/System/NodeLiveness{-Max}] handle raft ready: 1.7s [applied=1, batches=1, state_assertions=1]
W200204 20:32:42.468701 17202368 storage/store_raft.go:496  [n1,s1,r1/1:/{Min-System/NodeL…}] handle raft ready: 0.6s [applied=1, batches=1, state_assertions=1]
W200204 20:32:44.275590 17202377 storage/store_raft.go:496  [n1,s1,r2/1:/System/NodeLiveness{-Max}] handle raft ready: 1.8s [applied=1, batches=1, state_assertions=0]
W200204 20:32:44.275623 17203962 storage/node_liveness.go:546  [n1,s1,r4/1:/System{/tsd-tse}] slow heartbeat took 6.4s
E200204 20:32:44.275654 17203962 storage/replica_range_lease.go:339  [n1,s1,r4/1:/System{/tsd-tse}] heartbeat failed on epoch increment
W200204 20:32:44.275657 17203942 storage/node_liveness.go:546  [n1,s1,r3/1:/System/{NodeLive…-tsd}] slow heartbeat took 6.4s
E200204 20:32:44.275682 17203942 storage/replica_range_lease.go:339  [n1,s1,r3/1:/System/{NodeLive…-tsd}] heartbeat failed on epoch increment
W200204 20:32:44.275967 17203975 storage/node_liveness.go:546  [n1,s1,r26/1:/NamespaceTable/{30-Max}] slow heartbeat took 5.4s
E200204 20:32:44.275988 17203975 storage/replica_range_lease.go:339  [n1,s1,r26/1:/NamespaceTable/{30-Max}] heartbeat failed on epoch increment
W200204 20:32:44.276084 17203923 storage/node_liveness.go:546  [n1,s1,r6/1:/Table/{SystemCon…-11}] slow heartbeat took 4.2s
E200204 20:32:44.276107 17203923 storage/replica_range_lease.go:339  [n1,s1,r6/1:/Table/{SystemCon…-11}] heartbeat failed on epoch increment
W200204 20:32:44.276181 17204033 storage/node_liveness.go:546  [n1,s1,r10/1:/Table/1{4-5}] slow heartbeat took 3.6s
E200204 20:32:44.276198 17204033 storage/replica_range_lease.go:339  [n1,s1,r10/1:/Table/1{4-5}] heartbeat failed on epoch increment
W200204 20:32:44.276391 17202417 storage/node_liveness.go:546  [n1,liveness-hb] slow heartbeat took 3.6s
W200204 20:32:45.197635 17202417 storage/node_liveness.go:471  [n1,liveness-hb] failed node liveness heartbeat: operation "node liveness heartbeat" timed out after 4.5s
W200204 20:32:45.310117 17202357 storage/store_raft.go:496  [n1,s1,r24/1:/Table/2{8-9}] handle raft ready: 1.0s [applied=1, batches=1, state_assertions=1]
W200204 20:32:45.396347 17202373 storage/store_raft.go:496  [n1,s1,r2/1:/System/NodeLiveness{-Max}] handle raft ready: 1.1s [applied=1, batches=1, state_assertions=0]
W200204 20:32:45.396733 17204279 storage/node_liveness.go:546  [n1,s1,r3/1:/System/{NodeLive…-tsd}] slow heartbeat took 1.1s
W200204 20:32:45.397645 17204308 storage/node_liveness.go:546  [n1,s1,r4/1:/System{/tsd-tse}] slow heartbeat took 1.1s
W200204 20:32:45.400436 17204292 storage/node_liveness.go:546  [n1,s1,r26/1:/NamespaceTable/{30-Max}] slow heartbeat took 1.1s
W200204 20:32:51.018495 17202348 storage/store_raft.go:496  [n1,s1,r14/1:/Table/1{8-9}] handle raft ready: 5.6s [applied=1, batches=1, state_assertions=1]
W200204 20:32:51.019644 17202359 storage/store_raft.go:496  [n1,s1,r4/1:/System{/tsd-tse}] handle raft ready: 5.6s [applied=1, batches=1, state_assertions=0]
W200204 20:32:53.272515 17202331 storage/store_raft.go:496  [n1,s1,r2/1:/System/NodeLiveness{-Max}] handle raft ready: 5.7s [applied=1, batches=1, state_assertions=0]
W200204 20:32:53.272774 17202372 storage/store_raft.go:496  [n1,s1,r24/1:/Table/2{8-9}] handle raft ready: 7.8s [applied=1, batches=1, state_assertions=0]
W200204 20:32:53.273588 17202367 storage/store_raft.go:496  [n1,s1,r5/1:/{Systemtse-Table/System…}] handle raft ready: 3.2s [applied=1, batches=1, state_assertions=1]
W200204 20:32:53.274154 17202378 storage/store_raft.go:496  [n1,s1,r3/1:/System/{NodeLive…-tsd}] handle raft ready: 5.4s [applied=1, batches=1, state_assertions=0]
W200204 20:32:53.297494 17202352 storage/store_raft.go:496  [n1,s1,r26/1:/NamespaceTable/{30-Max}] handle raft ready: 0.5s [applied=1, batches=1, state_assertions=1]
W200204 20:32:53.299291 17202359 storage/store_raft.go:496  [n1,s1,r4/1:/System{/tsd-tse}] handle raft ready: 2.3s [applied=2, batches=1, state_assertions=0]
W200204 20:32:53.299390 17202390 storage/store_raft.go:496  [n1,s1,r1/1:/{Min-System/NodeL…}] handle raft ready: 2.3s [applied=1, batches=1, state_assertions=1]
W200204 20:32:53.312668 17202417 storage/node_liveness.go:546  [n1,liveness-hb] slow heartbeat took 5.8s
W200204 20:32:53.312718 17202417 storage/node_liveness.go:471  [n1,liveness-hb] failed node liveness heartbeat: operation "node liveness heartbeat" timed out after 4.5s
--- FAIL: TestZip (115.61s)
    zip_test.go:199: 
        	Error Trace:	zip_test.go:199
        	Error:      	Not equal: 
        	            	expected: "debug zip /dev/null\nwriting /dev/null\n  debug/events.json\n  debug/rangelog.json\n  debug/liveness.json\n  debug/settings.json\n  debug/reports/problemranges.json\n  debug/crdb_internal.cluster_queries.txt\n  debug/crdb_internal.cluster_sessions.txt\n  debug/crdb_internal.cluster_settings.txt\n  debug/crdb_internal.jobs.txt\n  debug/system.jobs.txt\n  debug/system.descriptor.txt\n  debug/system.namespace.txt\n  debug/system.namespace_deprecated.txt\n  debug/crdb_internal.kv_node_status.txt\n  debug/crdb_internal.kv_store_status.txt\n  debug/crdb_internal.schema_changes.txt\n  debug/crdb_internal.partitions.txt\n  debug/crdb_internal.zones.txt\n  debug/nodes/1/status.json\n  debug/nodes/1/crdb_internal.feature_usage.txt\n  debug/nodes/1/crdb_internal.gossip_alerts.txt\n  debug/nodes/1/crdb_internal.gossip_liveness.txt\n  debug/nodes/1/crdb_internal.gossip_network.txt\n  debug/nodes/1/crdb_internal.gossip_nodes.txt\n  debug/nodes/1/crdb_internal.leases.txt\n  debug/nodes/1/crdb_internal.node_build_info.txt\n  debug/nodes/1/crdb_internal.node_metrics.txt\n  debug/nodes/1/crdb_internal.node_queries.txt\n  debug/nodes/1/crdb_internal.node_runtime_info.txt\n  debug/nodes/1/crdb_internal.node_sessions.txt\n  debug/nodes/1/crdb_internal.node_statement_statistics.txt\n  debug/nodes/1/crdb_internal.node_txn_stats.txt\n  debug/nodes/1/details.json\n  debug/nodes/1/gossip.json\n  debug/nodes/1/enginestats.json\n  debug/nodes/1/stacks.txt\n  debug/nodes/1/heap.pprof\n  debug/nodes/1/ranges/1.json\n  debug/nodes/1/ranges/2.json\n  debug/nodes/1/ranges/3.json\n  debug/nodes/1/ranges/4.json\n  debug/nodes/1/ranges/5.json\n  debug/nodes/1/ranges/6.json\n  debug/nodes/1/ranges/7.json\n  debug/nodes/1/ranges/8.json\n  debug/nodes/1/ranges/9.json\n  debug/nodes/1/ranges/10.json\n  debug/nodes/1/ranges/11.json\n  debug/nodes/1/ranges/12.json\n  debug/nodes/1/ranges/13.json\n  debug/nodes/1/ranges/14.json\n  debug/nodes/1/ranges/15.json\n  debug/nodes/1/ranges/16.json\n  debug/nodes/1/ranges/17.json\n  debug/nodes/1/ranges/18.json\n  debug/nodes/1/ranges/19.json\n  debug/nodes/1/ranges/20.json\n  debug/nodes/1/ranges/21.json\n  debug/nodes/1/ranges/22.json\n  debug/nodes/1/ranges/23.json\n  debug/nodes/1/ranges/24.json\n  debug/nodes/1/ranges/25.json\n  debug/nodes/1/ranges/26.json\n  debug/nodes/1/ranges/27.json\n  debug/nodes/1/ranges/28.json\n  debug/schema/defaultdb@details.json\n  debug/schema/postgres@details.json\n  debug/schema/system@details.json\n  debug/schema/system/comments.json\n  debug/schema/system/descriptor.json\n  debug/schema/system/eventlog.json\n  debug/schema/system/jobs.json\n  debug/schema/system/lease.json\n  debug/schema/system/locations.json\n  debug/schema/system/namespace.json\n  debug/schema/system/namespace_deprecated.json\n  debug/schema/system/protected_ts_meta.json\n  debug/schema/system/protected_ts_records.json\n  debug/schema/system/rangelog.json\n  debug/schema/system/replication_constraint_stats.json\n  debug/schema/system/replication_critical_localities.json\n  debug/schema/system/replication_stats.json\n  debug/schema/system/reports_meta.json\n  debug/schema/system/role_members.json\n  debug/schema/system/settings.json\n  debug/schema/system/table_statistics.json\n  debug/schema/system/ui.json\n  debug/schema/system/users.json\n  debug/schema/system/web_sessions.json\n  debug/schema/system/zones.json\n"
        	            	actual  : "debug zip /dev/null\nwriting /dev/null\n  debug/events.json\n  debug/rangelog.json\n  debug/liveness.json\n  debug/settings.json\n  debug/reports/problemranges.json\n  debug/crdb_internal.cluster_queries.txt\n  debug/crdb_internal.cluster_sessions.txt\n  debug/crdb_internal.cluster_settings.txt\n  debug/crdb_internal.jobs.txt\n  debug/system.jobs.txt\n  debug/system.descriptor.txt\n  debug/system.namespace.txt\n  debug/system.namespace_deprecated.txt\n  debug/crdb_internal.kv_node_status.txt\n  debug/crdb_internal.kv_store_status.txt\n  debug/crdb_internal.schema_changes.txt\n  debug/crdb_internal.partitions.txt\n  debug/crdb_internal.zones.txt\n  debug/nodes/1/status.json\n  debug/nodes/1/crdb_internal.feature_usage.txt\n  debug/nodes/1/crdb_internal.gossip_alerts.txt\n  debug/nodes/1/crdb_internal.gossip_liveness.txt\n  debug/nodes/1/crdb_internal.gossip_network.txt\n  debug/nodes/1/crdb_internal.gossip_nodes.txt\n  debug/nodes/1/crdb_internal.leases.txt\n  debug/nodes/1/crdb_internal.node_build_info.txt\n  debug/nodes/1/crdb_internal.node_metrics.txt\n  debug/nodes/1/crdb_internal.node_queries.txt\n  debug/nodes/1/crdb_internal.node_runtime_info.txt\n  debug/nodes/1/crdb_internal.node_sessions.txt\n  debug/nodes/1/crdb_internal.node_statement_statistics.txt\n  debug/nodes/1/crdb_internal.node_txn_stats.txt\n  debug/nodes/1/details.json\n  debug/nodes/1/gossip.json\n  debug/nodes/1/enginestats.json\n  debug/nodes/1/stacks.txt\n  debug/nodes/1/heap.pprof\n  debug/nodes/1/ranges/1.json\n  debug/nodes/1/ranges/2.json\n  debug/nodes/1/ranges/3.json\n  debug/nodes/1/ranges/4.json\n  debug/nodes/1/ranges/5.json\n  debug/nodes/1/ranges/6.json\n  debug/nodes/1/ranges/7.json\n  debug/nodes/1/ranges/8.json\n  debug/nodes/1/ranges/9.json\n  debug/nodes/1/ranges/10.json\n  debug/nodes/1/ranges/11.json\n  debug/nodes/1/ranges/12.json\n  debug/nodes/1/ranges/13.json\n  debug/nodes/1/ranges/14.json\n  debug/nodes/1/ranges/15.json\n  debug/nodes/1/ranges/16.json\n  debug/nodes/1/ranges/17.json\n  debug/nodes/1/ranges/18.json\n  debug/nodes/1/ranges/19.json\n  debug/nodes/1/ranges/20.json\n  debug/nodes/1/ranges/21.json\n  debug/nodes/1/ranges/22.json\n  debug/nodes/1/ranges/23.json\n  debug/nodes/1/ranges/24.json\n  debug/nodes/1/ranges/25.json\n  debug/nodes/1/ranges/26.json\n  debug/nodes/1/ranges/27.json\n  debug/nodes/1/ranges/28.json\n  debug/schema/defaultdb@details.json\n  debug/schema/postgres@details.json\n  debug/schema/system@details.json\n  debug/schema/system/comments.json\n  ^- resulted in operation \"request table comments\" timed out after 10s: rpc error: code = DeadlineExceeded desc = context deadline exceeded\n  debug/schema/system/descriptor.json\n  debug/schema/system/eventlog.json\n  debug/schema/system/jobs.json\n  debug/schema/system/lease.json\n  debug/schema/system/locations.json\n  debug/schema/system/namespace.json\n  debug/schema/system/namespace_deprecated.json\n  debug/schema/system/protected_ts_meta.json\n  debug/schema/system/protected_ts_records.json\n  debug/schema/system/rangelog.json\n  debug/schema/system/replication_constraint_stats.json\n  debug/schema/system/replication_critical_localities.json\n  debug/schema/system/replication_stats.json\n  debug/schema/system/reports_meta.json\n  debug/schema/system/role_members.json\n  debug/schema/system/settings.json\n  debug/schema/system/table_statistics.json\n  debug/schema/system/ui.json\n  debug/schema/system/users.json\n  debug/schema/system/web_sessions.json\n  debug/schema/system/zones.json\n"
        	            	
        	            	Diff:
        	            	--- Expected
        	            	+++ Actual
        	            	@@ -71,2 +71,3 @@
        	            	   debug/schema/system/comments.json
        	            	+  ^- resulted in operation "request table comments" timed out after 10s: rpc error: code = DeadlineExceeded desc = context deadline exceeded
        	            	   debug/schema/system/descriptor.json
        	Test:       	TestZip

```

<details><summary>More</summary><p>
Parameters:

- GOFLAGS=-json

```
make stressrace TESTS=TestZip PKG=./pkg/cli TESTTIMEOUT=5m STRESSFLAGS='-timeout 5m' 2>&1
```

[See this test on roachdash](https://roachdash.crdb.dev/?filter=status%3Aopen+t%3A.%2ATestZip.%2A&sort=title&restgroup=false&display=lastcommented+project)
<sub>powered by [pkg/cmd/internal/issues](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)</sub></p></details>

### PR DESCRIPTION
**Pull request by andreimatei**
It looks like the server sometimes collects heap profiles while this
test is running.

Fixes #44717

### CODE REVIEW

File: pkg/cli/zip_test.go [hunk 1]
```diff
@@ -128,9 +129,9 @@ func TestZip(t *testing.T) {
 	// Strip any non-deterministic messages.
 	out = eraseNonDeterministicZipOutput(out)
 
-	datadriven.RunTest(t, "testdata/zip/testzip", func(t *testing.T, td *datadriven.TestData) string {
```
Comment (knz) [inline pkg/cli/zip_test.go:131]: Please, no. The purpose of the datadriven calls was to enable TESTFLAGS=-rewrite. Your change breaks that.

File: pkg/cli/zip_test.go [hunk 2]
```diff
@@ -264,6 +263,12 @@ func eraseNonDeterministicZipOutput(out string) string {
 	out = re.ReplaceAllString(out, `RPC connection to ...`)
 	re = regexp.MustCompile(`(?m)\^- resulted in.*$`)
 	out = re.ReplaceAllString(out, `^- resulted in ...`)
+
+	// The number of memory profiles previously collected is not deterministic.
+	re = regexp.MustCompile(`(?m)requesting heap files for node 1\.\.\..*found$`)
```
Comment (knz) [inline pkg/cli/zip_test.go:268]: LGTM to this. Not the rest.

**Review by knz — CHANGES_REQUESTED** [review]

File: pkg/cli/zip_test.go (hunk 1 above)
Comment (andreimatei) [reply pkg/cli/zip_test.go:131]: oh -rewrite, interesting. I've put that in the comment below and got rid of this commit.

**Review by knz — APPROVED** [review]
:lgtm_strong:  - thank you!

> Reviewed 7 of 7 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/48364#-:-M6WWa3k6sUBYWpCXyMb:bwqmx4o)* status: :shipit: complete! 1 of 0 LGTMs obtained
