### PR TITLE
importccl: improve handling of transient errors when importing over http

### LINKED ISSUE #43070: bulk-io: import seems to randomly fail and then succeed on subsequent retry of the import
**Describe the problem**

User is experiencing an issue when running concurrent imports where the import will fail with various errors (i.e. "unexpected EOF", "Expected x columns, found y") Then on subsequent attempts to import the same file the import succeeds without any change to the file. 

**To Reproduce**

User has provided a sample random import : 

```
IMPORT TABLE t1

(

   a string(13) PRIMARY KEY NOT NULL,

   b decimal(10,0),

   c decimal(10,5),

   d decimal(10,5),

   e string(15),

   f string(13) NOT NULL,

   g string(13) NOT NULL

) CSV DATA ('${random_data_0}','${random_data_1}')

WITH decompress = 'gzip', delimiter = '|', skip = '1', experimental_save_rejected

;
```

If possible, provide steps to reproduce the behavior:

1. Import concurrent files, user has seen this issue with a minimum of 4 concurrent imports. 
2. Wait to see if any fail. 
3. Re-run the failed imports

**Expected behavior**
Imports should either fail or succeed, errors should be deterministic if the imports do fail. 

**Additional data / screenshots**

If a node in your cluster encountered a fatal error, supply the contents of the
log directories (at minimum of the affected node(s), but preferably all nodes).

Note that log files can contain confidential information. Please continue
creating this issue, but contact support@cockroachlabs.com to submit the log
files in private.

**Environment:**
 - CockroachDB version 19.2 also 20.1 alpha
 - Server OS: [e.g. Linux/Distrib]
 - Client app - Pentaho client
**Additional context**

### PR DESCRIPTION
**Pull request by miretskiy**
Make importing data into cockroach from external http servers
resilient to connection interruption due to connection reset by peer errors.
Add backoff when retrying.

Release note (enterprise change): more resilient http import

Fixes: #43070

### CODE REVIEW

File: pkg/storage/cloud/external_storage.go [hunk 1]
```diff
@@ -518,39 +556,74 @@ func checkHTTPContentRangeHeader(h string, pos int64) error {
...
+func (r *resumingHTTPReader) sendRequest(
+	reqHeaders map[string]string,
+) (resp *http.Response, err error) {
+	prev := timeutil.Now()
+	attempt := 0
+	for retries := retry.StartWithCtx(r.ctx, httpRetryOptions); retries.Next(); {
+		attempt++
+		resp, err = r.client.req(r.ctx, "GET", r.url, nil, reqHeaders)
+		if resp != nil {
+			r.body = resp.Body
```
Comment (dt) [inline pkg/storage/cloud/external_storage.go]: nit: i find it a little confusing to have this method mutating `r.body` but then also returning `resp` for callers to read (and they then use it to mutate other fields of `r`), plus sometimes callers also assign `r.body`.

I think it'd be cleaner to either 

a.  not return `resp` at all: this method always handles closing/nil-ing `r.body` first, sets `r. body`, `r.canResume`, and checks the range, or
b. not modify `r` at all: perhaps even making this a function that takes a ctx, client, etc as args, and make callers handle mutating r.

File: pkg/storage/cloud/external_storage.go [hunk 2]
```diff
@@ -518,39 +556,74 @@ func checkHTTPContentRangeHeader(h string, pos int64) error {
...
+		}
+
+		delay := timeutil.Since(prev)
+		prev = timeutil.Now()
+
+		if err == nil {
```
Comment (dt) [inline pkg/storage/cloud/external_storage.go]: can more this above the time calls, right? (or just remove the timing altogether -- the log lines themselves have timestamps)

File: pkg/storage/cloud/external_storage.go [hunk 3]
```diff
@@ -518,39 +556,74 @@ func checkHTTPContentRangeHeader(h string, pos int64) error {
 	return nil
 }
 
+func (r *resumingHTTPReader) sendRequest(
+	reqHeaders map[string]string,
+) (resp *http.Response, err error) {
+	prev := timeutil.Now()
+	attempt := 0
```
Comment (dt) [inline pkg/storage/cloud/external_storage.go]: you could declare (and inc) this as part of the `for` loop syntax if you felt like it.

**Review by dt — APPROVED** [review]

**Review by miretskiy — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/43558)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dt and @knz)

___
*[pkg/storage/cloud/external_storage.go, line 432 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/43558#-Lx2g_hF0ShGX-rt-F4D-r1-432:-LxO5f9GC_hwMle5BIMN:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/c3fe08283b84b1930d454b5dac0b0d9e3ef64917/pkg/storage/cloud/external_storage.go#L432)):*
<details><summary><i>Previously, dt (David Taylor) wrote…</i></summary><blockquote>

288s is a pretty long time -- can we go with 2s as the max?
</blockquote></details>

Done.
___
*[pkg/storage/cloud/external_storage.go, line 563 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/43558#-Lx2g_hF0ShGX-rt-F4D-r1-563:-LxO72Q80avvhxaWpx0t:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/c3fe08283b84b1930d454b5dac0b0d9e3ef64917/pkg/storage/cloud/external_storage.go#L563)):*
<details><summary><i>Previously, dt (David Taylor) wrote…</i></summary><blockquote>

you could declare (and inc) this as part of the `for` loop syntax if you felt like it.
</blockquote></details>

Done.
___
*[pkg/storage/cloud/external_storage.go, line 568 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/43558#-Lx2g_hF0ShGX-rt-F4D-r1-568:-LxOHj0sD-bs8GZ4gYKL:btmlriu) ([raw file](https://github.com/cockroachdb/cockroach/blob/c3fe08283b84b1930d454b5dac0b0d9e3ef64917/pkg/storage/cloud/external_storage.go#L568)):*
<details><summary><i>Previously, dt (David Taylor) wrote…</i></summary><blockquote>

nit: i find it a little confusing to have this method mutating `r.body` but then also returning `resp` for callers to read (and they then use it to mutate other fields of `r`), plus sometimes callers also assign `r.body`.

I think it'd be cleaner to either 

a.  not return `resp` at all: this method always handles closing/nil-ing `r.body` first, sets `r. body`, `r.canResume`, and checks the range, or
b. not modify `r` at all: perhaps even making this a function that takes a ctx, client, etc as args, and make callers handle mutating r.
</blockquote></details>

Makes sense; chose option "b" -- updated callers to set r.body
___
*[pkg/storage/cloud/external_storage.go, line 574 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/43558#-Lx2g_hF0ShGX-rt-F4D-r1-574:-LxOCDUkAYHLEu4MMj7O:bss4a2b) ([raw file](https://github.com/cockroachdb/cockroach/blob/c3fe08283b84b1930d454b5dac0b0d9e3ef64917/pkg/storage/cloud/external_storage.go#L574)):*
<details><summary><i>Previously, dt (David Taylor) wrote…</i></summary><blockquote>

can more this above the time calls, right? (or just remove the timing altogether -- the log lines themselves have timestamps)
</blockquote></details>

Removed.
___
*[pkg/storage/cloud/external_storage.go, line 614 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/43558#-Lx2g_hF0ShGX-rt-F4D-r1-614:-LxOCzc73RDirGpQwCwS:bvz97vx) ([raw file](https://github.com/cockroachdb/cockroach/blob/c3fe08283b84b1930d454b5dac0b0d9e3ef64917/pkg/storage/cloud/external_storage.go#L614)):*
<details><summary><i>Previously, dt (David Taylor) wrote…</i></summary><blockquote>

If `r.body.Read` returned an error on the last allowed attempt, i'd rather return _that error_ than this constant, plus it doesn't make sense to call `r.requestNextRange` if we're not going to actually going to read when we loop back around, so I think i'd prefer to do this check below, after the `Read` call, right? then we could a) immediate bail on error if it was the last attempt and b) only inject this no-progress error if we don't have something more useful.
</blockquote></details>

Yes, that makes sense.  Moved the check inside the retry-able error branch (wrapping the original read error)
___
*[pkg/storage/cloud/external_storage.go, line 640 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/43558#-Lx2g_hF0ShGX-rt-F4D-r1-640:-LxOEx7C2ceMVsn56gdp:b-8x1l1q) ([raw file](https://github.com/cockroachdb/cockroach/blob/c3fe08283b84b1930d454b5dac0b0d9e3ef64917/pkg/storage/cloud/external_storage.go#L640)):*
<details><summary><i>Previously, dt (David Taylor) wrote…</i></summary><blockquote>

nit: a `func isResumableError(err error) bool` might make this a bit tidier.
</blockquote></details>

Good idea; done.
___
*[pkg/storage/cloud/external_storage.go, line 734 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/43558#-Lx2g_hF0ShGX-rt-F4D-r1-734:-LxOGSMk2jgo4lJT8ZcG:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/c3fe08283b84b1930d454b5dac0b0d9e3ef64917/pkg/storage/cloud/external_storage.go#L734)):*
<details><summary><i>Previously, dt (David Taylor) wrote…</i></summary><blockquote>

can you add a comment as to why _all errors_ that can come back from `Do` are retryable?
</blockquote></details>

Done.
