### PR TITLE
changefeedbase: fix kafka batch reduction

### LINKED ISSUE #90029: changefeedccl: Kafka batch retry might not work correctly; or at all.
While testing kafka batch retries, the following behavior was observed:

1 topic create with max message size 128K
Changefeed created, with somewhat insane configuration:
```
 create changefeed for tpcc.history into 'kafka://10.11.43.129:9092?topic_name=testTopic' with initial_scan='only', kafka_sin
k_config='{"Flush": {"Messages": 5000, "MaxMessages": 10000, "Frequency": "1s"}}';
```

Each row in tpcc.history is about 216 bytes -- thus, only ~600 messages could ever fit.
The following error messages were observed in the logs:
```
ccl/changefeedccl/sink_kafka.go:452 ⋮ kafka sink with flush config ({Bytes:0 Messages:5000 Frequency:1s MaxMessages:10000}) beginning internal retry with 5640 inflight messages due to error: ‹while sending message with key=[1034, "1a7c3a46-862f-4300-8000-000001d997eb"], size=272, stats=m=5637/b=1508686/largest=546: kafka server: Message was too large, server rejected it to avoid allocation error.›
ccl/changefeedccl/sink_kafka.go:558 ⋮  kafka sink handling 5641 buffered messages for internal retry
ccl/changefeedccl/sink_kafka.go:587 ⋮ kafka sink retrying 5641 messages with reduced flush config: ({Bytes:0 Messages:2500 Frequency:1s MaxMessages:5000})
ccl/changefeedccl/sink_kafka.go:580 ⋮ 17822  kafka sink abandoning internal retry due to error: ‹kafka: Failed to deliver 5641 messages.›
```

The last message `kafka sink abandoning internal retry due to error: ‹kafka: Failed to deliver 5641 messages.>` is particularly
disconcerting.  If I'm reading the code correctly, when that happens, the error returned up the stack:
https://github.com/cockroachdb/cockroach/blob/master/pkg/ccl/changefeedccl/sink_kafka.go#L518-L518

```
if isRetrying() && s.mu.inflight == 0 {
  if err := s.handleBufferedRetries(retryBuf, retryErr); err != nil {
	s.mu.flushErr = err
  }
  endInternalRetry()
}
```
So, the good news is that we do set flushErr; the bad news is that we clear out retryBuf (in endInternalRetry) *and* we clear out retry error:
```
endInternalRetry := func() {
		retryErr = nil
		retryBuf = nil
	}
```
So, at this point, we have swallowed 5641 messages, and set flushErr; 
Now, clearing out retryErr above causes isRetrying function to return false:
```
isRetrying := func() bool {
		return retryErr != nil
	}
```
This is very bad because now, new messages can come in -- that's already fatally broken since we might
be emitting newer key version never having emitted previous version (e.g. it was among those 5641 messages).

The changefeed not exiting with an error is highly problematic.  Best *guess*, and that's just a guess is
that change aggregator does attempt to flush the sink, and it probably does return flushErr, but that error
probably gets swallowed here:
```
if errors.As(err, &e) {
				// ErrBufferClosed is a signal that
				// our kvfeed has exited expectedly.
				err = e.Unwrap()
				if errors.Is(err, kvevent.ErrNormalRestartReason) {
					err = nil
				}
			} else {
```

It appears this issue is very severe, and that batching retries are entirely broken.

Unfortunately, it appears that disabling this feature `changefeed.batch_reduction_retry_enabled=false`
does not work either -- for the same reason as above -- it seems we rely on flushErr , which is wrong.
I'm probably missing some details here (and I hope I'm wrong!), but I think at this point, 
we have to consider kafka entirely broken.

Jira issue: CRDB-20557

### PR DESCRIPTION
**Pull request by samiskin**
Resolves https://github.com/cockroachdb/cockroach/issues/90029

Batch reduction retries would use the error returned by SendMessages to check for if that error was itself retryable and another round was needed.  The problem was SendMessages actually sends a list of errors casted as a single error, and we have to first unwrap that list to access it.

Release note (bug fix): fixes a bug in changefeed.batch_reduction_retry which resulted in only a single level of retry being able to occur.

### CODE REVIEW

File: pkg/ccl/changefeedccl/changefeedbase/settings.go [hunk 1]
```diff
@@ -221,7 +221,7 @@ var ActiveProtectedTimestampsEnabled = settings.RegisterBoolSetting(
 var BatchReductionRetryEnabled = settings.RegisterBoolSetting(
 	settings.TenantWritable,
 	"changefeed.batch_reduction_retry_enabled",
-	"*** DO NOT ENABLE ***; if true, kafka changefeeds upon erroring on an oversized batch will attempt to resend the messages with progressively lower batch sizes",
+	"if true, kafka changefeeds upon erroring on an oversized batch will attempt to resend the messages with progressively lower batch sizes",
 	false,
```
Comment (samiskin) [inline pkg/ccl/changefeedccl/changefeedbase/settings.go:225]: I left this false due to this potentially exacerbating the ordering issue with Sarama

File: pkg/ccl/changefeedccl/sink_kafka.go [hunk 2]
```diff
@@ -605,6 +605,15 @@ func (s *kafkaSink) handleBufferedRetries(msgs []*sarama.ProducerMessage, retryE
 		// SendMessages will attempt to send all messages into an AsyncProducer with
 		// the client's config and then block until the results come in.
 		lastSendErr = newProducer.SendMessages(msgs)
+		if lastSendErr != nil {
+			// nolint:errcmp
+			if sendErrs, ok := lastSendErr.(sarama.ProducerErrors); ok && len(sendErrs) > 0 {
```
Comment (samiskin) [inline pkg/ccl/changefeedccl/sink_kafka.go:610]: I was unclear why the linter triggered here and in the mock below as the lint message suggests the format I've done here as an alternative.

Comment (miretskiy) [inline pkg/ccl/changefeedccl/sink_kafka.go:610]: errors.As() doesn't work?

File: pkg/ccl/changefeedccl/sink_kafka.go [hunk 3]
```diff
@@ -605,6 +605,15 @@ func (s *kafkaSink) handleBufferedRetries(msgs []*sarama.ProducerMessage, retryE
...
+				// Just check the first error since all these messages being retried
+				// were likely from a single partition and therefore would've been
+				// marked with the same error.
+				lastSendErr = sendErrs[0].Err
```
Comment (miretskiy) [inline pkg/ccl/changefeedccl/sink_kafka.go:614]: I assume you've verified this in a live cluster; do you mind pasting log messages as this logic works its way through?

**Review by miretskiy — APPROVED** [review]

File: pkg/ccl/changefeedccl/sink_kafka.go (hunk 2 above)
Comment (samiskin) [reply pkg/ccl/changefeedccl/sink_kafka.go:610]: That didn't pass the linter either 🤷 .  There are some other locations in the codebase that do a cast where either `nolint` is used or the file is ignored in `build/bazelutil/nogo_config.json`.

**Comment by samiskin** [comment]
@miretskiy Sample logs of the full retry process when running 
```create changefeed for tpcc.history into 'kafka://localhost:9092?topic_name=all' with kafka_sink_config='{"Flush": {"Messages": 5000, "MaxMessages": 10000, "Frequency": "2s"}}'```
, going down to `Messages: 156, MaxMessages:312`

The history table was 90,000 rows total, and in the end after backfill the kafka topic received 127,366 messages.

On a topic with a message size limit of 128MB:

```txt
I221018 16:36:50.073346 2775 ccl/changefeedccl/sink_kafka.go:456 ⋮ [n1,job=806225531635761153] 1075  kafka sink with flush config ({Bytes:0 Messages:5000 Frequency:2s MaxMessages:10000}) beginning internal retry with 5344 inflight messages due to error: ‹while sending message with key=[1, "5a3bfbd0-1f4f-4800-8000-000000007beb"], size=265, stats=m=5344/b=1382349/largest=520: kafka server: Message was too large, server rejected it to avoid allocation error.›
I221018 16:36:52.070453 2775 ccl/changefeedccl/sink_kafka.go:562 ⋮ [n1,job=806225531635761153] 1076  kafka sink handling 5345 buffered messages for internal retry
I221018 16:36:52.070531 2775 ccl/changefeedccl/sink_kafka.go:591 ⋮ [n1,job=806225531635761153] 1077  kafka sink retrying 5345 messages with reduced flush config: ({Bytes:0 Messages:2500 Frequency:2s MaxMessages:5000})
I221018 16:36:52.070560 2775 github.com/Shopify/sarama/client.go:141 ⋮ [kafka-producer] 1078  ‹Initializing new client›
I221018 16:36:52.070621 2775 github.com/Shopify/sarama/client.go:884 ⋮ [kafka-producer] 1079  client/metadata fetching metadata for all topics from broker ‹localhost:9092›
I221018 16:36:52.070976 6321 github.com/Shopify/sarama/broker.go:209 ⋮ [kafka-producer] 1080  Connected to broker at ‹localhost:9092› (unregistered)
I221018 16:36:52.071838 2775 github.com/Shopify/sarama/client.go:615 ⋮ [kafka-producer] 1081  client/brokers registered new broker #0 at ‹gceworker-shiranka-2.c.cockroach-workers.internal:9092›
I221018 16:36:52.072065 2775 github.com/Shopify/sarama/client.go:185 ⋮ [kafka-producer] 1082  ‹Successfully initialized new client›
I221018 16:36:52.072208 6458 github.com/Shopify/sarama/async_producer.go:743 ⋮ [kafka-producer] 1083  producer/broker/0 starting up
I221018 16:36:52.072250 6458 github.com/Shopify/sarama/async_producer.go:759 ⋮ [kafka-producer] 1084  producer/broker/0 state change to [open] on ‹all›/0
I221018 16:36:52.075006 6457 github.com/Shopify/sarama/broker.go:207 ⋮ [kafka-producer] 1085  Connected to broker at ‹gceworker-shiranka-2.c.cockroach-workers.internal:9092› (registered as #0)
I221018 16:36:54.081092 6467 github.com/Shopify/sarama/async_producer.go:1054 ⋮ [kafka-producer] 1086  ‹Producer shutting down.›
I221018 16:36:54.081182 6458 github.com/Shopify/sarama/async_producer.go:749 ⋮ [kafka-producer] 1087  producer/broker/0 input chan closed
I221018 16:36:54.081201 6458 github.com/Shopify/sarama/async_producer.go:842 ⋮ [kafka-producer] 1088  producer/broker/0 shut down
I221018 16:36:54.081209 2775 github.com/Shopify/sarama/client.go:248 ⋮ [kafka-producer] 1089  ‹Closing Client›
I221018 16:36:54.081270 2775 ccl/changefeedccl/sink_kafka.go:591 ⋮ [n1,job=806225531635761153] 1090  kafka sink retrying 5345 messages with reduced flush config: ({Bytes:0 Messages:1250 Frequency:2s MaxMessages:2500})
I221018 16:36:54.081311 2775 github.com/Shopify/sarama/client.go:141 ⋮ [kafka-producer] 1091  ‹Initializing new client›
I221018 16:36:54.081334 6499 github.com/Shopify/sarama/broker.go:248 ⋮ [kafka-producer] 1092  Closed connection to broker ‹gceworker-shiranka-2.c.cockroach-workers.internal:9092›
I221018 16:36:54.081367 2775 github.com/Shopify/sarama/client.go:884 ⋮ [kafka-producer] 1093  client/metadata fetching metadata for all topics from broker ‹localhost:9092›
I221018 16:36:54.081404 6500 github.com/Shopify/sarama/broker.go:248 ⋮ [kafka-producer] 1094  Closed connection to broker ‹localhost:9092›
I221018 16:36:54.081667 6501 github.com/Shopify/sarama/broker.go:209 ⋮ [kafka-producer] 1095  Connected to broker at ‹localhost:9092› (unregistered)
I221018 16:36:54.082430 2775 github.com/Shopify/sarama/client.go:615 ⋮ [kafka-producer] 1096  client/brokers registered new broker #0 at ‹gceworker-shiranka-2.c.cockroach-workers.internal:9092›
I221018 16:36:54.082653 2775 github.com/Shopify/sarama/client.go:185 ⋮ [kafka-producer] 1097  ‹Successfully initialized new client›
I221018 16:36:54.082851 6397 github.com/Shopify/sarama/async_producer.go:743 ⋮ [kafka-producer] 1098  producer/broker/0 starting up
I221018 16:36:54.082879 6397 github.com/Shopify/sarama/async_producer.go:759 ⋮ [kafka-producer] 1099  producer/broker/0 state change to [open] on ‹all›/0
I221018 16:36:54.086753 6397 github.com/Shopify/sarama/async_producer.go:783 ⋮ [kafka-producer] 1100  producer/broker/0 maximum request accumulated, waiting for space
I221018 16:36:54.087316 6396 github.com/Shopify/sarama/broker.go:207 ⋮ [kafka-producer] 1101  Connected to broker at ‹gceworker-shiranka-2.c.cockroach-workers.internal:9092› (registered as #0)
I221018 16:36:54.093980 6468 github.com/Shopify/sarama/async_producer.go:1054 ⋮ [kafka-producer] 1102  ‹Producer shutting down.›
I221018 16:36:54.094033 6397 github.com/Shopify/sarama/async_producer.go:749 ⋮ [kafka-producer] 1103  producer/broker/0 input chan closed
I221018 16:36:54.094047 6397 github.com/Shopify/sarama/async_producer.go:842 ⋮ [kafka-producer] 1104  producer/broker/0 shut down
I221018 16:36:54.094050 2775 github.com/Shopify/sarama/client.go:248 ⋮ [kafka-producer] 1105  ‹Closing Client›
I221018 16:36:54.094094 2775 ccl/changefeedccl/sink_kafka.go:591 ⋮ [n1,job=806225531635761153] 1106  kafka sink retrying 5345 messages with reduced flush config: ({Bytes:0 Messages:625 Frequency:2s MaxMessages:1250})
I221018 16:36:54.094139 2775 github.com/Shopify/sarama/client.go:141 ⋮ [kafka-producer] 1107  ‹Initializing new client›
I221018 16:36:54.094168 2775 github.com/Shopify/sarama/client.go:884 ⋮ [kafka-producer] 1108  client/metadata fetching metadata for all topics from broker ‹localhost:9092›
I221018 16:36:54.094169 6506 github.com/Shopify/sarama/broker.go:248 ⋮ [kafka-producer] 1109  Closed connection to broker ‹gceworker-shiranka-2.c.cockroach-workers.internal:9092›
I221018 16:36:54.094224 6507 github.com/Shopify/sarama/broker.go:248 ⋮ [kafka-producer] 1110  Closed connection to broker ‹localhost:9092›
I221018 16:36:54.094460 6508 github.com/Shopify/sarama/broker.go:209 ⋮ [kafka-producer] 1111  Connected to broker at ‹localhost:9092› (unregistered)
I221018 16:36:54.095109 2775 github.com/Shopify/sarama/client.go:615 ⋮ [kafka-producer] 1112  client/brokers registered new broker #0 at ‹gceworker-shiranka-2.c.cockroach-workers.internal:9092›
I221018 16:36:54.095324 2775 github.com/Shopify/sarama/client.go:185 ⋮ [kafka-producer] 1113  ‹Successfully initialized new client›
I221018 16:36:54.095532 6546 github.com/Shopify/sarama/async_producer.go:743 ⋮ [kafka-producer] 1114  producer/broker/0 starting up
I221018 16:36:54.095566 6546 github.com/Shopify/sarama/async_producer.go:759 ⋮ [kafka-producer] 1115  producer/broker/0 state change to [open] on ‹all›/0
I221018 16:36:54.097476 6546 github.com/Shopify/sarama/async_producer.go:783 ⋮ [kafka-producer] 1116  producer/broker/0 maximum request accumulated, waiting for space
I221018 16:36:54.099588 6513 github.com/Shopify/sarama/broker.go:207 ⋮ [kafka-producer] 1117  Connected to broker at ‹gceworker-shiranka-2.c.cockroach-workers.internal:9092› (registered as #0)
I221018 16:36:55.014690 6542 13@kv/kvserver/replicate_queue.go:817 ⋮ [n1,replicate,s1,r94/1:‹/Table/109/1/{26/2/9…-56/3/2…}›] 1118  error processing replica: ‹0 of 1 live stores are able to take a new replica for the range (1 already has a voter, 0 already have a non-voter); likely not enough nodes in cluster›‹›
I221018 16:36:55.014690 6542 13@kv/kvserver/replicate_queue.go:817 ⋮ [n1,replicate,s1,r94/1:‹/Table/109/1/{26/2/9…-56/3/2…}›] 1118 +‹trace:›
I221018 16:36:55.014690 6542 13@kv/kvserver/replicate_queue.go:817 ⋮ [n1,replicate,s1,r94/1:‹/Table/109/1/{26/2/9…-56/3/2…}›] 1118 +‹     0.000ms      0.000ms    === operation:process replica _unfinished:1 _verbose:1 node:1 replicate: store:1 range:94/1:/Table/109/1/{26/2/9…-56/3/2…}›
I221018 16:36:55.014690 6542 13@kv/kvserver/replicate_queue.go:817 ⋮ [n1,replicate,s1,r94/1:‹/Table/109/1/{26/2/9…-56/3/2…}›] 1118 +‹     0.068ms      0.068ms    event:kv/kvserver/allocator/allocatorimpl/allocator.go:682 [n1,replicate,s1,r94/1:/Table/109/1/{26/2/9…-56/3/2…}] add voter - missing voter need=3, have=1, priority=10001.00›
I221018 16:36:55.014690 6542 13@kv/kvserver/replicate_queue.go:817 ⋮ [n1,replicate,s1,r94/1:‹/Table/109/1/{26/2/9…-56/3/2…}›] 1118 +‹     0.081ms      0.013ms    event:kv/kvserver/replicate_queue.go:866 [n1,replicate,s1,r94/1:/Table/109/1/{26/2/9…-56/3/2…}] next replica action: add voter›
I221018 16:36:55.014690 6542 13@kv/kvserver/replicate_queue.go:817 ⋮ [n1,replicate,s1,r94/1:‹/Table/109/1/{26/2/9…-56/3/2…}›] 1118 +‹     0.102ms      0.022ms    event:kv/kvserver/allocator/allocatorimpl/allocator.go:1037 [n1,replicate,s1,r94/1:/Table/109/1/{26/2/9…-56/3/2…}] allocate voter: []›
I221018 16:36:56.013820 6374 13@kv/kvserver/replicate_queue.go:817 ⋮ [n1,replicate,s1,r267/1:‹/Table/15{6-7}›] 1119  error processing replica: ‹0 of 1 live stores are able to take a new replica for the range (1 already has a voter, 0 already have a non-voter); likely not enough nodes in cluster›‹›
I221018 16:36:56.013820 6374 13@kv/kvserver/replicate_queue.go:817 ⋮ [n1,replicate,s1,r267/1:‹/Table/15{6-7}›] 1119 +‹trace:›
I221018 16:36:56.013820 6374 13@kv/kvserver/replicate_queue.go:817 ⋮ [n1,replicate,s1,r267/1:‹/Table/15{6-7}›] 1119 +‹     0.000ms      0.000ms    === operation:process replica _unfinished:1 _verbose:1 node:1 replicate: store:1 range:267/1:/Table/15{6-7}›
I221018 16:36:56.013820 6374 13@kv/kvserver/replicate_queue.go:817 ⋮ [n1,replicate,s1,r267/1:‹/Table/15{6-7}›] 1119 +‹     0.059ms      0.059ms    event:kv/kvserver/allocator/allocatorimpl/allocator.go:682 [n1,replicate,s1,r267/1:/Table/15{6-7}] add voter - missing voter need=3, have=1, priority=10001.00›
I221018 16:36:56.013820 6374 13@kv/kvserver/replicate_queue.go:817 ⋮ [n1,replicate,s1,r267/1:‹/Table/15{6-7}›] 1119 +‹     0.072ms      0.013ms    event:kv/kvserver/replicate_queue.go:866 [n1,replicate,s1,r267/1:/Table/15{6-7}] next replica action: add voter›
I221018 16:36:56.013820 6374 13@kv/kvserver/replicate_queue.go:817 ⋮ [n1,replicate,s1,r267/1:‹/Table/15{6-7}›] 1119 +‹     0.093ms      0.020ms    event:kv/kvserver/allocator/allocatorimpl/allocator.go:1037 [n1,replicate,s1,r267/1:/Table/15{6-7}] allocate voter: []›
I221018 16:36:56.108053 6579 github.com/Shopify/sarama/async_producer.go:1054 ⋮ [kafka-producer] 1120  ‹Producer shutting down.›
I221018 16:36:56.108146 6546 github.com/Shopify/sarama/async_producer.go:749 ⋮ [kafka-producer] 1121  producer/broker/0 input chan closed
I221018 16:36:56.108176 6546 github.com/Shopify/sarama/async_producer.go:842 ⋮ [kafka-producer] 1123  producer/broker/0 shut down
I221018 16:36:56.108159 2775 github.com/Shopify/sarama/client.go:248 ⋮ [kafka-producer] 1122  ‹Closing Client›
I221018 16:36:56.108224 2775 ccl/changefeedccl/sink_kafka.go:591 ⋮ [n1,job=806225531635761153] 1124  kafka sink retrying 5345 messages with reduced flush config: ({Bytes:0 Messages:312 Frequency:2s MaxMessages:625})
I221018 16:36:56.108269 2775 github.com/Shopify/sarama/client.go:141 ⋮ [kafka-producer] 1125  ‹Initializing new client›
I221018 16:36:56.108284 6519 github.com/Shopify/sarama/broker.go:248 ⋮ [kafka-producer] 1126  Closed connection to broker ‹gceworker-shiranka-2.c.cockroach-workers.internal:9092›
I221018 16:36:56.108305 2775 github.com/Shopify/sarama/client.go:884 ⋮ [kafka-producer] 1127  client/metadata fetching metadata for all topics from broker ‹localhost:9092›
I221018 16:36:56.108360 6520 github.com/Shopify/sarama/broker.go:248 ⋮ [kafka-producer] 1128  Closed connection to broker ‹localhost:9092›
I221018 16:36:56.108575 6521 github.com/Shopify/sarama/broker.go:209 ⋮ [kafka-producer] 1129  Connected to broker at ‹localhost:9092› (unregistered)
I221018 16:36:56.109337 2775 github.com/Shopify/sarama/client.go:615 ⋮ [kafka-producer] 1130  client/brokers registered new broker #0 at ‹gceworker-shiranka-2.c.cockroach-workers.internal:9092›
I221018 16:36:56.109588 2775 github.com/Shopify/sarama/client.go:185 ⋮ [kafka-producer] 1131  ‹Successfully initialized new client›
I221018 16:36:56.109828 6611 github.com/Shopify/sarama/async_producer.go:743 ⋮ [kafka-producer] 1132  producer/broker/0 starting up
I221018 16:36:56.109860 6611 github.com/Shopify/sarama/async_producer.go:759 ⋮ [kafka-producer] 1133  producer/broker/0 state change to [open] on ‹all›/0
I221018 16:36:56.111012 6611 github.com/Shopify/sarama/async_producer.go:783 ⋮ [kafka-producer] 1134  producer/broker/0 maximum request accumulated, waiting for space
I221018 16:36:56.114105 6610 github.com/Shopify/sarama/broker.go:207 ⋮ [kafka-producer] 1135  Connected to broker at ‹gceworker-shiranka-2.c.cockroach-workers.internal:9092› (registered as #0)
I221018 16:36:56.117605 6611 github.com/Shopify/sarama/async_producer.go:783 ⋮ [kafka-producer] 1136  producer/broker/0 maximum request accumulated, waiting for space
I221018 16:36:56.120296 6611 github.com/Shopify/sarama/async_producer.go:783 ⋮ [kafka-producer] 1137  producer/broker/0 maximum request accumulated, waiting for space
I221018 16:36:56.123811 6375 github.com/Shopify/sarama/async_producer.go:1054 ⋮ [kafka-producer] 1138  ‹Producer shutting down.›
I221018 16:36:56.123854 6611 github.com/Shopify/sarama/async_producer.go:749 ⋮ [kafka-producer] 1139  producer/broker/0 input chan closed
I221018 16:36:56.123870 6611 github.com/Shopify/sarama/async_producer.go:842 ⋮ [kafka-producer] 1140  producer/broker/0 shut down
I221018 16:36:56.123874 2775 github.com/Shopify/sarama/client.go:248 ⋮ [kafka-producer] 1141  ‹Closing Client›
I221018 16:36:56.123925 2775 ccl/changefeedccl/sink_kafka.go:591 ⋮ [n1,job=806225531635761153] 1142  kafka sink retrying 5345 messages with reduced flush config: ({Bytes:0 Messages:156 Frequency:2s MaxMessages:312})
I221018 16:36:56.123960 2775 github.com/Shopify/sarama/client.go:141 ⋮ [kafka-producer] 1143  ‹Initializing new client›
I221018 16:36:56.123971 6565 github.com/Shopify/sarama/broker.go:248 ⋮ [kafka-producer] 1144  Closed connection to broker ‹gceworker-shiranka-2.c.cockroach-workers.internal:9092›
I221018 16:36:56.123997 2775 github.com/Shopify/sarama/client.go:884 ⋮ [kafka-producer] 1145  client/metadata fetching metadata for all topics from broker ‹localhost:9092›
I221018 16:36:56.124025 6566 github.com/Shopify/sarama/broker.go:248 ⋮ [kafka-producer] 1146  Closed connection to broker ‹localhost:9092›
I221018 16:36:56.124281 6567 github.com/Shopify/sarama/broker.go:209 ⋮ [kafka-producer] 1147  Connected to broker at ‹localhost:9092› (unregistered)
I221018 16:36:56.125000 2775 github.com/Shopify/sarama/client.go:615 ⋮ [kafka-producer] 1148  client/brokers registered new broker #0 at ‹gceworker-shiranka-2.c.cockroach-workers.internal:9092›
I221018 16:36:56.125179 2775 github.com/Shopify/sarama/client.go:185 ⋮ [kafka-producer] 1149  ‹Successfully initialized new client›
I221018 16:36:56.125315 6606 github.com/Shopify/sarama/async_producer.go:743 ⋮ [kafka-producer] 1150  producer/broker/0 starting up
I221018 16:36:56.125358 6606 github.com/Shopify/sarama/async_producer.go:759 ⋮ [kafka-producer] 1151  producer/broker/0 state change to [open] on ‹all›/0
I221018 16:36:56.125946 6606 github.com/Shopify/sarama/async_producer.go:783 ⋮ [kafka-producer] 1152  producer/broker/0 maximum request accumulated, waiting for space
I221018 16:36:56.129254 6605 github.com/Shopify/sarama/broker.go:207 ⋮ [kafka-producer] 1153  Connected to broker at ‹gceworker-shiranka-2.c.cockroach-workers.internal:9092› (registered as #0)
I221018 16:36:56.130193 6606 github.com/Shopify/sarama/async_producer.go:783 ⋮ [kafka-producer] 1154  producer/broker/0 maximum request accumulated, waiting for space
I221018 16:36:56.131079 6606 github.com/Shopify/sarama/async_producer.go:783 ⋮ [kafka-producer] 1155  producer/broker/0 maximum request accumulated, waiting for space
I221018 16:36:56.131944 6606 github.com/Shopify/sarama/async_producer.go:783 ⋮ [kafka-producer] 1156  producer/broker/0 maximum request accumulated, waiting for space
I221018 16:36:56.132788 6606 github.com/Shopify/sarama/async_producer.go:783 ⋮ [kafka-producer] 1157  producer/broker/0 maximum request accumulated, waiting for space
I221018 16:36:56.133595 6606 github.com/Shopify/sarama/async_producer.go:783 ⋮ [kafka-producer] 1158  producer/broker/0 maximum request accumulated, waiting for space
I221018 16:36:56.134471 6606 github.com/Shopify/sarama/async_producer.go:783 ⋮ [kafka-producer] 1159  producer/broker/0 maximum request accumulated, waiting for space
I221018 16:36:56.135270 6606 github.com/Shopify/sarama/async_producer.go:783 ⋮ [kafka-producer] 1160  producer/broker/0 maximum request accumulated, waiting for space
I221018 16:36:56.136070 6606 github.com/Shopify/sarama/async_producer.go:783 ⋮ [kafka-producer] 1161  producer/broker/0 maximum request accumulated, waiting for space
I221018 16:36:56.136897 6606 github.com/Shopify/sarama/async_producer.go:783 ⋮ [kafka-producer] 1162  producer/broker/0 maximum request accumulated, waiting for space
I221018 16:36:56.137774 6606 github.com/Shopify/sarama/async_producer.go:783 ⋮ [kafka-producer] 1163  producer/broker/0 maximum request accumulated, waiting for space
I221018 16:36:56.138535 6606 github.com/Shopify/sarama/async_producer.go:783 ⋮ [kafka-producer] 1164  producer/broker/0 maximum request accumulated, waiting for space
I221018 16:36:56.139291 6606 github.com/Shopify/sarama/async_producer.go:783 ⋮ [kafka-producer] 1165  producer/broker/0 maximum request accumulated, waiting for space
I221018 16:36:56.140140 6606 github.com/Shopify/sarama/async_producer.go:783 ⋮ [kafka-producer] 1166  producer/broker/0 maximum request accumulated, waiting for space
I221018 16:36:56.140872 6606 github.com/Shopify/sarama/async_producer.go:783 ⋮ [kafka-producer] 1167  producer/broker/0 maximum request accumulated, waiting for space
I221018 16:36:56.141668 6606 github.com/Shopify/sarama/async_producer.go:783 ⋮ [kafka-producer] 1168  producer/broker/0 maximum request accumulated, waiting for space
I221018 16:36:56.143489 6580 github.com/Shopify/sarama/async_producer.go:1054 ⋮ [kafka-producer] 1169  ‹Producer shutting down.›
I221018 16:36:56.143534 6606 github.com/Shopify/sarama/async_producer.go:749 ⋮ [kafka-producer] 1170  producer/broker/0 input chan closed
I221018 16:36:56.143547 6606 github.com/Shopify/sarama/async_producer.go:842 ⋮ [kafka-producer] 1171  producer/broker/0 shut down
I221018 16:36:56.143556 2775 github.com/Shopify/sarama/client.go:248 ⋮ [kafka-producer] 1172  ‹Closing Client›
I221018 16:36:56.143591 2775 ccl/changefeedccl/sink_kafka.go:626 ⋮ [n1,job=806225531635761153] 1173  kafka sink internal retry succeeded
```

The process took around 6 seconds total on my gceworker based on the timestamps.

**Comment by miretskiy** [comment]
Ty, @samiskin
