### PR TITLE
kvserver: remove UnregisterFromReplica callback

### LINKED ISSUE #144828: kv/kvserver: TestMergeQueueWithSlowNonVoterSnaps failed
kv/kvserver.TestMergeQueueWithSlowNonVoterSnaps [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Ci_TestsAwsLinuxArm64_UnitTests/19492663?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Ci_TestsAwsLinuxArm64_UnitTests/19492663?buildTab=artifacts#/) on master @ [3fd6c603858b94ec7a76d7e8891caea079a34ab4](https://github.com/cockroachdb/cockroach/commits/3fd6c603858b94ec7a76d7e8891caea079a34ab4):

```
created by github.com/cockroachdb/pebble/internal/genericcache.(*shard[...]).Init in goroutine 7991
	external/com_github_cockroachdb_pebble/internal/genericcache/shard.go:54 +0x17c

goroutine 8301 [chan receive, 14 minutes]:
github.com/cockroachdb/pebble/internal/genericcache.(*shard[...]).releaseLoop(0x400823dd50)
	external/com_github_cockroachdb_pebble/internal/genericcache/shard.go:61 +0x6c
created by github.com/cockroachdb/pebble/internal/genericcache.(*shard[...]).Init in goroutine 7991
	external/com_github_cockroachdb_pebble/internal/genericcache/shard.go:54 +0x17c

goroutine 8922 [chan receive, 14 minutes]:
github.com/cockroachdb/pebble/internal/genericcache.(*shard[...]).releaseLoop(0x4004326e00)
	external/com_github_cockroachdb_pebble/internal/genericcache/shard.go:61 +0x6c
created by github.com/cockroachdb/pebble/internal/genericcache.(*shard[...]).Init in goroutine 7991
	external/com_github_cockroachdb_pebble/internal/genericcache/shard.go:54 +0x17c

goroutine 11880 [select]:
github.com/cockroachdb/cockroach/pkg/util/admission.(*StoreGrantCoordinators).SetPebbleMetricsProvider.func1()
	pkg/util/admission/grant_coordinator.go:107 +0xcc
created by github.com/cockroachdb/cockroach/pkg/util/admission.(*StoreGrantCoordinators).SetPebbleMetricsProvider in goroutine 7991
	pkg/util/admission/grant_coordinator.go:97 +0x2d0

goroutine 11879 [select]:
github.com/cockroachdb/cockroach/pkg/util/admission.makeStoreWorkQueue.func1()
	pkg/util/admission/work_queue.go:2291 +0x7c
created by github.com/cockroachdb/cockroach/pkg/util/admission.makeStoreWorkQueue in goroutine 7991
	pkg/util/admission/work_queue.go:2288 +0x388

goroutine 8903 [chan receive, 14 minutes]:
github.com/cockroachdb/pebble/internal/genericcache.(*shard[...]).releaseLoop(0xe)
	external/com_github_cockroachdb_pebble/internal/genericcache/shard.go:61 +0x6c
created by github.com/cockroachdb/pebble/internal/genericcache.(*shard[...]).Init in goroutine 7991
	external/com_github_cockroachdb_pebble/internal/genericcache/shard.go:54 +0x17c

goroutine 8285 [chan receive, 14 minutes]:
github.com/cockroachdb/pebble/internal/genericcache.(*shard[...]).releaseLoop(0x0)
	external/com_github_cockroachdb_pebble/internal/genericcache/shard.go:61 +0x6c
created by github.com/cockroachdb/pebble/internal/genericcache.(*shard[...]).Init in goroutine 7991
	external/com_github_cockroachdb_pebble/internal/genericcache/shard.go:54 +0x17c

goroutine 8907 [chan receive, 14 minutes]:
github.com/cockroachdb/pebble/internal/genericcache.(*shard[...]).releaseLoop(0xe)
	external/com_github_cockroachdb_pebble/internal/genericcache/shard.go:61 +0x6c
created by github.com/cockroachdb/pebble/internal/genericcache.(*shard[...]).Init in goroutine 7991
	external/com_github_cockroachdb_pebble/internal/genericcache/shard.go:54 +0x17c

goroutine 8909 [chan receive, 14 minutes]:
github.com/cockroachdb/pebble/internal/genericcache.(*shard[...]).releaseLoop(0x4003f777b0)
	external/com_github_cockroachdb_pebble/internal/genericcache/shard.go:61 +0x6c
created by github.com/cockroachdb/pebble/internal/genericcache.(*shard[...]).Init in goroutine 7991
	external/com_github_cockroachdb_pebble/internal/genericcache/shard.go:54 +0x17c
```
<details><summary>Help</summary>
<p>

See also: [How To Investigate a Go Test Failure \(internal\)](https://cockroachlabs.atlassian.net/l/c/HgfXfJgM)
</p>
</details>
/cc @cockroachdb/kv-triage
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*TestMergeQueueWithSlowNonVoterSnaps.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/bazci/githubpost/issues)

</sub>

Jira issue: CRDB-49560

### PR DESCRIPTION
**Pull request by stevendanna**
The UnregisterFromReplica callback required obtaining the rangefeedMu mutex from inside the rangefeed scheduler worker. This is a problem because the current holder of the rangefeedMu (specifically (*ScheduledProcessor).Register) may require a response from the very same scheduler worker to make progress and release rangefeedMu.

Here, we solve that by removing this UnregisterFromReplica callback completely. This callback was responsible for removing the processor from the replica when the processor had been shut down.

But, nearly every code path that calls Stop() already removes the processor from the replica itself. The only case where this wasn't true is when the processor stops itself because it has no more active registrations.

Not removing the processor from the replica in that case has two consequences:

1. We may hold onto memory related to the ScheduledProcessor struct,

2. The replica does extra work because of the rangefeed processor is set.

Here, we choose to ignore (1) as a minor problem since a most ranges that have a rangefeed started once will have one started again in the future.

We solve (2) by making the `stopped` state variable accessible from outside the processor and consulting it before using the rangefeed processor on the replica. The assumption here is that the atomic load is cheap in comparison to the work we need to do when the processor is present.

Fixes #144828

Epic: none

Release note (bug fix): Fix a bug that could lead to a node stall.

### CODE REVIEW

File: pkg/kv/kvserver/rangefeed/scheduled_processor.go [hunk 1]
```diff
@@ -57,9 +57,16 @@ type ScheduledProcessor struct {
 
 	requestQueue chan request
 	eventC       chan *event
-	// If true, processor is not processing data anymore and waiting for registrations
-	// to be complete.
-	stopping bool
+
+	// stopping, when true, indicates that a stop request has been processed.
```
Comment (tbg) [inline pkg/kv/kvserver/rangefeed/scheduled_processor.go:61]: Add a few words about why the two snippets are not equivalent:

```go
stopping.Load()
```

```go
select {
  case <-stoppdC:
    return true
  default:
    return false
}
```

File: pkg/kv/kvserver/replica_rangefeed.go [hunk 2]
```diff
@@ -348,7 +348,18 @@ func (r *Replica) RangeFeed(
 func (r *Replica) getRangefeedProcessorAndFilter() (rangefeed.Processor, *rangefeed.Filter) {
 	r.rangefeedMu.RLock()
 	defer r.rangefeedMu.RUnlock()
-	return r.rangefeedMu.proc, r.rangefeedMu.opFilter
+	p := r.rangefeedMu.proc
```
Comment (tbg) [inline pkg/kv/kvserver/replica_rangefeed.go:351]: Add a comment on `proc` that this should always be obtained via `getRangefeedProcessorAndFilter`. Looking at the accesses, it seems true enough today - the remaining reads are "very internal":

image

**Review by tbg — APPROVED** [review]
This is a nice contained fix! Not suggesting you pursue that change, but for my education, could we additionally unset the processor before calling `p.Stop()`? That way, we wouldn't (in rare cases) leak a stopped processor.

I'm probably missing a few callsites, the only caller to `Stop` that I can see is here:

https://github.com/cockroachdb/cockroach/blob/45e5f2ef00d477e59950e3cae6a563822ca65939/pkg/kv/kvserver/replica_rangefeed.go#L569-L574

and I wonder what would result from flipping the order of those two calls.

**Comment by stevendanna** [comment]
TFTR!

> I'm probably missing a few callsites, the only caller to Stop that I can see is here:

Most of the callers are via StopWithErr.

> could we additionally unset the processor before calling p.Stop()

I think so yes. I'll include this in my list of possible future cleanups here.

File: pkg/kv/kvserver/rangefeed/scheduled_processor.go (hunk 1 above)
Comment (stevendanna) [reply pkg/kv/kvserver/rangefeed/scheduled_processor.go:61]: Interestingly, while I can explain how they are subtly different in the current code, I think one of my conclusions yesterday that really, we probably could live with _only_ `stoppedC` if we wanted to because (1) once stopped is set, all registrations have been disconnected, (2) the processor won't send any more events to those registrations, and (3) all new registrations will fail. So, once stopped is set to true, any following request is effectively going to fail one way or another. So I could see an argument that we should closed stoppedC in stopInternal and then do exactly the snippet you have there.

**Comment by stevendanna** [comment]
bors r=tbg
