### PR TITLE
roachtest: unskip jobs/mixed-versions

### LINKED ISSUE #57230: jobs: unskip jobs/mixed-version roachtest
This test was frequently failing since it was attempting to run an IMPORT in a mixed version cluster, which is known to not be supported. It was failing often enough that it was no longer giving us good signal.

The test should be updated to use a job that supports being run in a mixed-version cluster.

Epic CRDB-7776

### PR DESCRIPTION
**Pull request by pbardea**
This test is now expected to succeed now that this version of IMPORT and the predecessor version support being run in mixed-version clusters. Ran this 10 times (all passed) to confirm.

Resolves https://github.com/cockroachdb/cockroach/issues/57230.

Release note: None

### CODE REVIEW

File: pkg/cmd/roachtest/mixed_version_jobs.go [hunk 1]
```diff
@@ -332,7 +332,6 @@ func registerJobsMixedVersions(r *testRegistry) {
 		// is to to test the state transitions of jobs from paused to resumed and
 		// vice versa in order to detect regressions in the work done for 20.1.
 		MinVersion: "v20.1.0",
```
Comment (adityamaru) [inline pkg/cmd/roachtest/mixed_version_jobs.go:334]: does it make sense to bump the MinVersion?

**Review by adityamaru — APPROVED** [review]

File: pkg/cmd/roachtest/mixed_version_jobs.go (hunk 1 above)
Comment (pbardea) [reply pkg/cmd/roachtest/mixed_version_jobs.go]: I'm... not sure if this was doing anything since old version roachtests now run on their branch.

Comment (pbardea) [reply pkg/cmd/roachtest/mixed_version_jobs.go]: Ah, it was removed in https://github.com/cockroachdb/cockroach/commit/e26d040b38b3f49f6dfd9cfeef549e7529f01df5 🙌

**Comment by pbardea** [comment]
Rebased after a flake.
bors r+
