### PR TITLE
bulk: change AddSSTTable to not be recursive

### LINKED ISSUE #36381: sql: creating an index, user experienced OOM
**Describe the problem**

User ran into OOM while creating an index, also experiencing some slight load from tests.

```
[10782031.209476] Out of memory: Kill process 25243 (cockroach) score 915 or sacrifice child
[10782031.210847] Killed process 25243 (cockroach) total-vm:118637456kB, anon-rss:62702344kB, file-rss:0kB, shmem-rss:0kB
```

Here are the top sources of Memory allocation from the node: 

```File: cockroach
Type: inuse_space
Time: Apr 1, 2019 at 5:41am (EDT)
Showing nodes accounting for 4534.31MB, 96.66% of 4691.17MB total
Dropped 406 nodes (cum <= 23.46MB)
      flat  flat%   sum%        cum   cum%
 4352.75MB 92.79% 92.79%  4352.75MB 92.79%  github.com/cockroachdb/cockroach/vendor/github.com/golang/leveldb/memfs.(*file).Write
      64MB  1.36% 94.15%       64MB  1.36%  github.com/cockroachdb/cockroach/vendor/github.com/andy-kimball/arenaskl.NewArena (inline)
   27.03MB  0.58% 94.73%    49.53MB  1.06%  github.com/cockroachdb/cockroach/pkg/storage.newReplica
   26.54MB  0.57% 95.29%    26.54MB  0.57%  github.com/cockroachdb/cockroach/pkg/storage/raftentry.realloc
      24MB  0.51% 95.80%    27.50MB  0.59%  github.com/cockroachdb/cockroach/pkg/sql/sqlbase.EncodeSecondaryIndex
   20.99MB  0.45% 96.25%    48.49MB  1.03%  github.com/cockroachdb/cockroach/pkg/sql/backfill.(*IndexBackfiller).BuildIndexEntriesChunk
      18MB  0.38% 96.64%    54.89MB  1.17%  github.com/cockroachdb/cockroach/vendor/go.etcd.io/etcd/raft.newRaft
    0.50MB 0.011% 96.65%    55.39MB  1.18%  github.com/cockroachdb/cockroach/vendor/go.etcd.io/etcd/raft.NewRawNode
    0.50MB 0.011% 96.66%    59.58MB  1.27%  github.com/cockroachdb/cockroach/pkg/storage.(*Replica).withRaftGroupLocked
```

[DEBUG ZIP](https://docs.google.com/document/d/1mWGjdHXT6a4ceH1yxTgeLYjICg-qViQcU0fT5wbT-2o/edit?usp=sharing)

**Expected behavior**
Index should complete without OOM

**Additional data / screenshots**
User has been trying to create an index, and has run into multiple issues, may be related to [#34878](https://github.com/cockroachdb/cockroach/issues/34878)

**Environment:**
 - CockroachDB v19.1.0-beta.20190318

### LINKED ISSUE #36769: backfill: OOM from AddSSTable when adding SSTs that span many ranges
During an index backfill, if `bulk.AddSSTable` tries to add an SST spanning many ranges (and the range descriptor cache isn't populated with the ranges overlapping with that span), it will fail and recursively call itself with smaller SSTables that are split on the first range boundary discovered. When this happens, we can run out of memory, since we don't free the SST byte arrays that are allocated until the end.

These are from heap profiles for a node that crashed when I rolled back a CANCEL JOB (causing the backfiller to generate SSTs that span many nonempty ranges):

Screen Shot 2019-04-10 at 3 20 35 PM

Screen Shot 2019-04-10 at 3 21 50 PM

### PR DESCRIPTION
**Pull request by vivekmenezes**
AddSSTTable was recursive to deal with range splits.
Unfortunately the recursive call would create new SSTs
without freeing the older ones creating a memory buildup
that was quadratic. We've seen memory buildup on the order
of GBs due to this recursion.

fixes #36769
fixes #36381

Release note: None

### CODE REVIEW

**Comment by vivekmenezes** [comment]
looks like the tests are failing. Taking a look.

**Comment by dt** [comment]
This still forces us to keep making new iterators every time, on top of the post-split SSTs.

I was thinking we might want to make an internal helper wrapped by `AddSSTable` that in addition to the existing args takes an optional iterator. Then we'd pass the iterator, not []byte, to the split helper, so we'd and we could pass the same iterator the whole time. That also would mean that if a given attempt to add failed, we could throw away the []byte result before we attempted to split-and-and, since we could re-iterate the iter rather than iterating the failed file.

**Comment by vivekmenezes** [comment]
@dt done as requested. PTAL

**Comment by dt** [comment]
if you wanted a test, you could rebase on top of https://github.com/cockroachdb/cockroach/compare/master...dt:addsstable-oom?expand=1

**Comment by vivekmenezes** [comment]
@dt updated this PR with your test. I've confirmed it fails without this PR. PTAL.

File: pkg/storage/bulk/sst_batcher_test.go [hunk 1]
```diff
@@ -203,8 +206,97 @@ func runTestImport(t *testing.T, batchSize int64) {
...
+	var baseline, early, late uint64
+	baseline = getMem()
+	var totalAdditionAttempts int
+	mock := mockSender(func(span roachpb.Span) error {
+		totalAdditionAttempts++
+		for i := range splits {
+			if span.ContainsKey(splits[i]) && !span.Key.Equal(splits[i]) {
+				earlySplit := numKeys / 100
+				if i == earlySplit {
+					early = getMem() - baseline
```
Comment (dt) [inline pkg/storage/bulk/sst_batcher_test.go]: I think we want to get rid of `baseline`  and these `- baseline`s, since they assume that men usage only increases which might not be true -- if for any reason mem usage _dropped_ between establishing baseline once of these calls, this subtraction just overflows.

File: pkg/storage/bulk/sst_batcher.go [hunk 2]
```diff
@@ -189,57 +189,99 @@ func (b *SSTBatcher) GetSummary() roachpb.BulkOpSummary {
...
-	defer iter.Close()
+	return nil
+}
 
+// createSplitSSTable is a helper for splitting up SSTs. The iterator
+// passed in is over the top level SST passed into AddSSTTable().
+func createSplitSSTable(
+	ctx context.Context,
+	db sender,
+	sstBytes []byte,
```
Comment (dt) [inline pkg/storage/bulk/sst_batcher.go]: I don't think we need to pass `sstBytes` and `iter` -- I think we'd be okay with just `iter`?

**Review by vivekmenezes — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/36765)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dt)

___
*[pkg/storage/bulk/sst_batcher.go, line 267 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/36765#-LcC0SBVY4Eez5Q-4tcQ-r1-267:-LcI9dGk9aLkfOj2c05j:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/17beae792f05a2482419746a35754fe84b8defb9/pkg/storage/bulk/sst_batcher.go#L267)):*
<details><summary><i>Previously, dt (David Taylor) wrote…</i></summary><blockquote>

I don't think we need to pass `sstBytes` and `iter` -- I think we'd be okay with just `iter`?
</blockquote></details>

Done.
___
*[pkg/storage/bulk/sst_batcher_test.go, line 279 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/36765#-LcCan3LxBi49GU8u_3g-r1-279:-LcI8NfR2n9KEFqsTfhm:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/17beae792f05a2482419746a35754fe84b8defb9/pkg/storage/bulk/sst_batcher_test.go#L279)):*
<details><summary><i>Previously, dt (David Taylor) wrote…</i></summary><blockquote>

I think we want to get rid of `baseline`  and these `- baseline`s, since they assume that men usage only increases which might not be true -- if for any reason mem usage _dropped_ between establishing baseline once of these calls, this subtraction just overflows.
</blockquote></details>

Done.

**Review by dt — APPROVED** [review]
