### PR TITLE
server: enable `_status/connectivity` for secondary tenants (shared-process)

### LINKED ISSUE #110024: server: the "connectivity" status API endpoint should work with secondary tenants with sufficient capability
Found while investigating #110001.
Also see discussion [here](https://github.com/cockroachdb/cockroach/pull/109656#issuecomment-1696951860).

**Describe the problem**

When `TestNetworkConnectivity` in `server/storage_api` is modified to point to a secondary tenant (e.g. via #110008), the test starts failing when accessing the `/_status/connectivity` endpoint:

```
    network_test.go:42: condition failed to evaluate within 45s: from http.go:190: status: 501 Not Implemented, content-type: application/json, body: {
          "error": "method NetworkConnectivity not implemented",
          "code": 12,
          "message": "method NetworkConnectivity not implemented",
          "details": [
          ]
        }, error: <nil>
```

**How to reproduce**

from #110008 reset `DefaultTestTenant` in `TestNetworkConnectivity`, run the test with a test tenant and observe the failure.

**Expected behavior**

See discussion [here](https://github.com/cockroachdb/cockroach/pull/109656#issuecomment-1696951860).
- for the KV/storage-level connectivity, once the tenant is granted a suitable capability, the endpoint should work properly and retrieve the storage-level connectivity information using the KV tenant connector over the network.
- we need a design discussion for the connectivity stats between SQL pods.

Epic CRDB-38968

Jira issue: CRDB-31229

### PR DESCRIPTION
**Pull request by shubhamdhama**
This works well for shared-process mode where inter-node network
connectivity for a secondary tenant is the same as for the system tenant.
However, in external-process mode, this endpoint won't provide a complete
picture of network connectivity since the SQL server may run entirely
outside the KV node. We may need to extend this endpoint or create a new
one for SQL-SQL servers and SQL server to KV nodes. This work is left for
the future, and currently, this endpoint only shows KV-KV nodes network
connectivity. As a result, this endpoint isn't ready for external-process
mode and should only be enabled for shared-mode tenants. On the backend,
there is nothing enforcing this, which shouldn't be a problem.

Fixes: #110024

Epic: #CRDB-38968

Release note: None

### CODE REVIEW

File: pkg/ccl/logictestccl/testdata/logic_test/tenant_capability [hunk 1]
```diff
@@ -39,6 +39,7 @@ can_check_consistency      false
 can_debug_process          false
 can_use_nodelocal_storage  false
 can_view_all_metrics       false
+can_view_all_metrics       false
```
Comment (stevendanna) [inline pkg/ccl/logictestccl/testdata/logic_test/tenant_capability:42]: Was this supposed to be `can_view_network_info`?  I kinda wonder if we could re-use `can_debug_process` for this endpoint.  The latency of the node we are connecting to is _kinda_ a property of the process so it makes some sense. Thoughts?

File: pkg/multitenant/tenantcapabilities/tenantcapabilitiesauthorizer/authorizer.go [hunk 2]
```diff
@@ -276,33 +268,24 @@ func (a *Authorizer) BindReader(reader tenantcapabilities.Reader) {
...
-	return nil
+var insufficientCapErrMap = map[tenantcapabilities.ID]error{
+	tenantcapabilities.CanViewNodeInfo:        errCannotQueryMetadata,
+	tenantcapabilities.CanViewTSDBMetrics:     errCannotQueryTSDB,
+	tenantcapabilities.CanUseNodelocalStorage: errCannotUseNodelocal,
+	tenantcapabilities.CanDebugProcess:        errCannotDebugProcess,
 }
 
-func (a *Authorizer) HasTSDBQueryCapability(ctx context.Context, tenID roachpb.TenantID) error {
+func (a *Authorizer) hasCapability(
```
Comment (stevendanna) [inline pkg/multitenant/tenantcapabilities/tenantcapabilitiesauthorizer/authorizer.go:286]: I like this cleanup even if we end up re-using CanDebugProcess.

File: pkg/server/status.go [hunk 3]
```diff
@@ -2102,6 +2102,30 @@ func (s *statusServer) NodeUI(
...
+// all nodes. This works well for shared-process mode where inter-node network
+// connectivity for a secondary tenant is same as for the system tenant.
+// However, in external-process mode, this endpoint won't provide a complete
+// picture of network connectivity since the SQL server may run entirely outside
+// the KV node. We may need to extend this endpoint or create a new one for
+// SQL-SQL servers and SQL server to KV nodes. This work is left for the future,
+// and currently, this endpoint only shows KV-KV nodes network connectivity. As
+// a result, this endpoint isn't ready for external-process mode and should only
+// be enabled for secondary tenants. Here is nothing enforcing this, which
+// shouldn't be a problem.
```
Comment (stevendanna) [inline pkg/server/status.go:2115]: Do we have an issue for determining how to expose the concept of SQL Instances in the various status APIs and DB Console? Might be good to make one and link it here.

File: pkg/ccl/logictestccl/testdata/logic_test/tenant_capability (hunk 1 above)
Comment (shubhamdhama) [reply pkg/ccl/logictestccl/testdata/logic_test/tenant_capability]: I agree, it didn't had to be a new permission.

File: pkg/server/status.go (hunk 3 above)
Comment (shubhamdhama) [reply pkg/server/status.go]: Created https://github.com/cockroachdb/cockroach/issues/138156

File: pkg/server/status.go [hunk 4]
```diff
@@ -2119,6 +2119,30 @@ func (s *statusServer) NodeUI(
...
+// NetworkConnectivity collects information about connections statuses across
+// all nodes. This works well for shared-process mode where inter-node network
+// connectivity for a secondary tenant is same as for the system tenant.
+// However, in external-process mode, this endpoint won't provide a complete
+// picture of network connectivity since the SQL server may run entirely outside
+// the KV node. We may need to extend this endpoint or create a new one for
+// SQL-SQL servers and SQL server to KV nodes. This work is left for the future,
+// and currently, this endpoint only shows KV-KV nodes network connectivity. As
+// a result, this endpoint isn't ready for external-process mode and should only
+// be enabled for secondary tenants. Here is nothing enforcing this, which
```
Comment (stevendanna) [inline pkg/server/status.go:2131]:
```suggestion
// be enabled for secondary tenants. There is nothing enforcing this, which
```

**Review by stevendanna — APPROVED** [review]
This seems reasonable to me.

Would it be difficult to add a test that shows that if you _don't_ have the permission then this endpoint returns an error?

**Review by dhartunian — APPROVED** [review]
> Reviewed 18 of 18 files at r3, 2 of 17 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/131830)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @cthumuluru-crdb, @kyle-a-wong, @shubhamdhama, and @stevendanna)

___
*[`-- commits` line 5 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/131830#-OGVUxCc8EHMkbl3suVK:-OGVUxCc8EHMkbl3suVL:bhrnghg):*
nit: The endpoint is `_status/connectivity` if you're going to quote the route.
___
*[`-- commits` line 16 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/131830#-OGVUYQdCKsKfFecqf3Q:-OGVUYQdCKsKfFecqf3R:b-tg2asw):*
nit: This is helpful background but can you just add a note above it describing that this change is just enabling tenant access to the feature via the `can_debug_process` capability? It's not super clear what's being done.
___
*[`pkg/multitenant/tenantcapabilities/tenantcapabilitiesauthorizer/authorizer.go` line 393 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/131830#-OGVUL0sBzplAWnGmmb_:-OGVUL0sBzplAWnGmmba:b-d63tvo) ([raw file](https://github.com/cockroachdb/cockroach/blob/45acbec9702e83c54380458e4e0357db7cc609ab/pkg/multitenant/tenantcapabilities/tenantcapabilitiesauthorizer/authorizer.go#L393)):*
> ```Go
> }
> 
> func (a *Authorizer) HasTSDBAllMetricsCapability(
> ```

Any reason why this check cannot also be refactored?

**Review by shubhamdhama — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/131830)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @cthumuluru-crdb, @dhartunian, @kyle-a-wong, and @stevendanna)

___
*[`-- commits` line 16 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/131830#-OGVUYQdCKsKfFecqf3Q:-OGdo1UYB9pRlGy8GbEB:bb6un1j):*
<details><summary><i>Previously, dhartunian (David Hartunian) wrote…</i></summary><blockquote>

nit: This is helpful background but can you just add a note above it describing that this change is just enabling tenant access to the feature via the `can_debug_process` capability? It's not super clear what's being done.
</blockquote></details>

Done
___
*[`pkg/multitenant/tenantcapabilities/tenantcapabilitiesauthorizer/authorizer.go` line 393 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/131830#-OGVUL0sBzplAWnGmmb_:-OGdnVZjAVJXTC5LOud-:b-7348qq) ([raw file](https://github.com/cockroachdb/cockroach/blob/45acbec9702e83c54380458e4e0357db7cc609ab/pkg/multitenant/tenantcapabilities/tenantcapabilitiesauthorizer/authorizer.go#L393)):*
<details><summary><i>Previously, dhartunian (David Hartunian) wrote…</i></summary><blockquote>

Any reason why this check cannot also be refactored?
</blockquote></details>

Not really, the `authorizerModeV222` case had the `errCaonnotQueryTSDB` error, which is different from the `err...AllMetrics` at the end. But I think that was just a typo, so I refactored this one too.

File: pkg/multitenant/tenantcapabilities/tenantcapabilitiesauthorizer/authorizer.go [hunk 5]
```diff
@@ -354,47 +338,41 @@ func (a *Authorizer) HasTSDBQueryCapability(ctx context.Context, tenID roachpb.T
 	case authorizerModeAllowAll:
 		return nil
 	case authorizerModeV222:
```
Comment (shubhamdhama) [inline pkg/multitenant/tenantcapabilities/tenantcapabilitiesauthorizer/authorizer.go:340]: I wonder if we should do a cleanup and remove this setting option in a separate PR

**Review by cthumuluru-crdb — APPROVED** [review]
> should only be enabled for secondary tenants.

should only be enabled for shared secondary tenants. ?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/131830#-:-OGee-Fs3j0Lu1ftMjkJ:b-wgp7v)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @dhartunian, @kyle-a-wong, @shubhamdhama, and @stevendanna)

**Comment by shubhamdhama** [comment]
Thanks all for the review!

bors r=stevendanna,dhartunian,cthumuluru-crdb
