### PR TITLE
sql: drop partial indexes with predicates that reference drop columns

### LINKED ISSUE #51082: sql: dropping columns referenced in partial index predicates should drop the partial index
Currently this is not done, leading to errors when trying to insert data.

```
root@127.0.0.1:55237/defaultdb> show create table t;
  table_name |                  create_statement
-------------+------------------------------------------------------
  t          | CREATE TABLE t (
             |     a INT8 NULL,
             |     s STRING NULL,
             |     INDEX t_a_idx (a ASC) WHERE s = 'foo':::STRING,
             |     FAMILY "primary" (a, s, rowid)
             | )
(1 row)

Time: 6.786ms

root@127.0.0.1:55237/defaultdb> alter table t drop column s;
ALTER TABLE

Time: 83.609ms

root@127.0.0.1:55237/defaultdb> show create table t;
  table_name |                  create_statement
-------------+------------------------------------------------------
  t          | CREATE TABLE t (
             |     a INT8 NULL,
             |     INDEX t_a_idx (a ASC) WHERE s = 'foo':::STRING,
             |     FAMILY "primary" (a, rowid)
             | )
(1 row)

Time: 5.489ms

root@127.0.0.1:55237/defaultdb> select a from t where s = 'foo';
ERROR: column "s" does not exist
SQLSTATE: 42703
root@127.0.0.1:55237/defaultdb> insert into t values (1);
ERROR: column "s" does not exist
SQLSTATE: 42703
```

### PR DESCRIPTION
**Pull request by mgartner**
This commit updates the behavior of `ALTER TABLE ... DROP COLUMN` to
drop partial indexes with predicates that reference the column being
dropped.

For example:

    CREATE TABLE t (a INT, b INT, INDEX i (a) WHERE b > 1)
    ALTER TABLE t DROP COLUMN b

Index `i` will no longer exist on table `t`.

Fixes #51082

Release note: None

### CODE REVIEW

**Review by mgartner — COMMENTED** [review]
The first commit is from https://github.com/cockroachdb/cockroach/pull/51661.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/51680#-:-MCn5AxK0oaDHJcylSAX:b-9lbiu0)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @RaduBerinde)

File: pkg/sql/schemaexpr/testutils.go [hunk 1]
```diff
@@ -32,7 +32,7 @@ func testTableDesc(
 		cols[i] = sqlbase.ColumnDescriptor{
 			Name: columns[i].name,
 			Type: columns[i].typ,
-			ID:   sqlbase.ColumnID(i),
+			ID:   sqlbase.ColumnID(i + 1),
```
Comment (mgartner) [inline pkg/sql/schemaexpr/testutils.go:35]: This change makes the min column ID 1 instead of 0 in these tests to better mimic the "real world" where column IDs are greater than 0.

**Review by rytaft — APPROVED** [review]
:lgtm: 

> Reviewed 3 of 5 files at r1, 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/51680#-:-MDQJDj6CvuSha78umZX:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @mgartner, @mjibson, and @RaduBerinde)

___
*[pkg/sql/schemaexpr/testutils.go, line 35 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/51680#-MCn58EUkykp59Jt87ts-r1-35:-MDQJ4O26OzBiYtv3DT5:b-x53dr6) ([raw file](https://github.com/cockroachdb/cockroach/blob/ee627418af6474581eeb237f5c7ae5a8daf37a93/pkg/sql/schemaexpr/testutils.go#L35)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

This change makes the min column ID 1 instead of 0 in these tests to better mimic the "real world" where column IDs are greater than 0.
</blockquote></details>

Maybe add a comment to that effect?

**Review by mgartner — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/51680)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @mjibson and @RaduBerinde)

___
*[pkg/sql/schemaexpr/testutils.go, line 35 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/51680#-MCn58EUkykp59Jt87ts-r1-35:-MDRGjad35WGTum4boKy:bcvjgzp) ([raw file](https://github.com/cockroachdb/cockroach/blob/ee627418af6474581eeb237f5c7ae5a8daf37a93/pkg/sql/schemaexpr/testutils.go#L35)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

Maybe add a comment to that effect?
</blockquote></details>

Good idea. Done.

**Review by rytaft — APPROVED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/51680)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @mjibson and @RaduBerinde)

**Comment by mgartner** [comment]
bors r=rytaft

**Comment by mgartner** [comment]
bors r=rytaft
