### PR TITLE
tpcc/large-schema-benchmark: address timeout on multi-region

### LINKED ISSUE #141572: roachtest: tpcc/large-schema-benchmark/multiregion=true/tables=10000 failed
roachtest.tpcc/large-schema-benchmark/multiregion=true/tables=10000 [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestWeeklyBazel/18841942?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestWeeklyBazel/18841942?buildTab=artifacts#/tpcc/large-schema-benchmark/multiregion=true/tables=10000) on master @ [67a82bfc09766413d7f8ae8edb10035940b94c7e](https://github.com/cockroachdb/cockroach/commits/67a82bfc09766413d7f8ae8edb10035940b94c7e). A Side-Eye cluster snapshot was captured on timeout: [https://app.side-eye.io/#/snapshots/649](https://app.side-eye.io/#/snapshots/649).

```
(test_runner.go:1382).runTest: test timed out (24h0m0s)
test artifacts and logs in: /artifacts/tpcc/large-schema-benchmark/multiregion=true/tables=10000/run_1
```

Parameters:
 - <code>arch=amd64</code>
 - <code>cloud=gce</code>
 - <code>coverageBuild=false</code>
 - <code>cpu=8</code>
 - <code>encrypted=false</code>
 - <code>fs=ext4</code>
 - <code>localSSD=false</code>
 - <code>metamorphicBufferedSender=false</code>
 - <code>runtimeAssertionsBuild=false</code>
 - <code>ssd=0</code>
<details><summary>Help</summary>
<p>

See: [roachtest README](https://github.com/cockroachdb/cockroach/blob/master/pkg/cmd/roachtest/README.md)

See: [How To Investigate \(internal\)](https://cockroachlabs.atlassian.net/l/c/SSSBr8c7)

See: [Grafana](https://go.crdb.dev/roachtest-grafana/teamcity-18841942/tpcc-large-schema-benchmark-multiregion-true-tables-10000/1739627365564/1739714669708)

</p>
</details>
/cc @cockroachdb/sql-foundations
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*tpcc/large-schema-benchmark/multiregion=true/tables=10000.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/bazci/githubpost/issues)

</sub>

Jira issue: CRDB-47907

### PR DESCRIPTION
**Pull request by fqazi**
The TPCC large schema benchmark intentionally used transactions for batching DDL operations because of the large number of objects that needed to be created by this test. When
autocommit_before_ddl enabled this test started timing out because just creating the tables can now take a long time. To address this, this patch disables autocommit_before_ddl for the test.

Fixes: #141572

Release note: None

### CODE REVIEW

File: pkg/cmd/roachtest/tests/large_schema_benchmark.go [hunk 1]
```diff
@@ -151,11 +151,16 @@ func registerLargeSchemaBenchmark(r registry.Registry, numTables int, isMultiReg
 						c.Start(ctx, t.L(), startOpts, settings, c.CRDBNodes())
 						conn := c.Conn(ctx, t.L(), 1)
 						defer conn.Close()
+						// Disable autocommit before DDL since we need to batch statements
+						// in a single transaction for them to complete in a reasonable amount
+						// of time. In multi-region this latency can be substantial.
+						_, err := conn.Exec("SET CLUSTER SETTING sql.defaults.autocommit_before_ddl.enabled = 'false'")
```
Comment (rafiss) [inline pkg/cmd/roachtest/tests/large_schema_benchmark.go:157]: this won't change the setting in the current session. i think that's fine since the table setup happens in a different connection, but just wanted to confirm.

**Review by rafiss — APPROVED** [review]
