### PR TITLE
mmaprototype: continue if no candidates left after filtering

### LINKED ISSUE #158833: kv/kvserver/asim/tests: TestDataDriven failed
kv/kvserver/asim/tests.TestDataDriven [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_NightlyCockroachExtraStress/20815339?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_NightlyCockroachExtraStress/20815339?buildTab=artifacts#/) on refs/heads/master @ [c7813f5c090a293dcd9c69bd7de4dc9e06c56c48](https://github.com/cockroachdb/cockroach/commits/c7813f5c090a293dcd9c69bd7de4dc9e06c56c48):

```
        /home/roach/.cache/bazel/_bazel_roach/c5a4e7d36696d9cd970af2045211a7df/sandbox/processwrapper-sandbox/2560/execroot/com_github_cockroachdb_cockroach/bazel-out/k8-fastbuild/bin/pkg/kv/kvserver/asim/tests/tests_test_/tests_test.runfiles/com_github_cockroachdb_cockroach/pkg/kv/kvserver/asim/tests/testdata/non_rand/mma/skewed_cpu_skewed_write_more_ranges.txt:32:
          setting
          ----
    datadriven_simulation_test.go:587: running eval for skewed_cpu_skewed_write_more_ranges
=== RUN   TestDataDriven/mode=mma/full_disk
=== PAUSE TestDataDriven/mode=mma/full_disk
=== CONT  TestDataDriven/mode=mma/full_disk
    datadriven_simulation_test.go:213: 
        /home/roach/.cache/bazel/_bazel_roach/c5a4e7d36696d9cd970af2045211a7df/sandbox/processwrapper-sandbox/2560/execroot/com_github_cockroachdb_cockroach/bazel-out/k8-fastbuild/bin/pkg/kv/kvserver/asim/tests/tests_test_/tests_test.runfiles/com_github_cockroachdb_cockroach/pkg/kv/kvserver/asim/tests/testdata/non_rand/mma/full_disk.txt:14:
          gen_cluster
          ----
    datadriven_simulation_test.go:213: 
        /home/roach/.cache/bazel/_bazel_roach/c5a4e7d36696d9cd970af2045211a7df/sandbox/processwrapper-sandbox/2560/execroot/com_github_cockroachdb_cockroach/bazel-out/k8-fastbuild/bin/pkg/kv/kvserver/asim/tests/tests_test_/tests_test.runfiles/com_github_cockroachdb_cockroach/pkg/kv/kvserver/asim/tests/testdata/non_rand/mma/full_disk.txt:19:
          gen_ranges
          ----
    datadriven_simulation_test.go:587: running eval for full_disk
=== RUN   TestDataDriven/mode=mma/one_voter_skewed_cpu_skewed_write
=== PAUSE TestDataDriven/mode=mma/one_voter_skewed_cpu_skewed_write
=== CONT  TestDataDriven/mode=mma/one_voter_skewed_cpu_skewed_write
    datadriven_simulation_test.go:213: 
        /home/roach/.cache/bazel/_bazel_roach/c5a4e7d36696d9cd970af2045211a7df/sandbox/processwrapper-sandbox/2560/execroot/com_github_cockroachdb_cockroach/bazel-out/k8-fastbuild/bin/pkg/kv/kvserver/asim/tests/tests_test_/tests_test.runfiles/com_github_cockroachdb_cockroach/pkg/kv/kvserver/asim/tests/testdata/non_rand/mma/one_voter_skewed_cpu_skewed_write.txt:8:
          gen_cluster
          ----
    datadriven_simulation_test.go:213: 
        /home/roach/.cache/bazel/_bazel_roach/c5a4e7d36696d9cd970af2045211a7df/sandbox/processwrapper-sandbox/2560/execroot/com_github_cockroachdb_cockroach/bazel-out/k8-fastbuild/bin/pkg/kv/kvserver/asim/tests/tests_test_/tests_test.runfiles/com_github_cockroachdb_cockroach/pkg/kv/kvserver/asim/tests/testdata/non_rand/mma/one_voter_skewed_cpu_skewed_write.txt:11:
          gen_ranges
          {s1}:1
          ----
          {s1:*}:1
    datadriven_simulation_test.go:213: 
        /home/roach/.cache/bazel/_bazel_roach/c5a4e7d36696d9cd970af2045211a7df/sandbox/processwrapper-sandbox/2560/execroot/com_github_cockroachdb_cockroach/bazel-out/k8-fastbuild/bin/pkg/kv/kvserver/asim/tests/tests_test_/tests_test.runfiles/com_github_cockroachdb_cockroach/pkg/kv/kvserver/asim/tests/testdata/non_rand/mma/one_voter_skewed_cpu_skewed_write.txt:16:
          gen_ranges
          {s2}:1
          ----
          {s2:*}:1
    datadriven_simulation_test.go:213: 
        /home/roach/.cache/bazel/_bazel_roach/c5a4e7d36696d9cd970af2045211a7df/sandbox/processwrapper-sandbox/2560/execroot/com_github_cockroachdb_cockroach/bazel-out/k8-fastbuild/bin/pkg/kv/kvserver/asim/tests/tests_test_/tests_test.runfiles/com_github_cockroachdb_cockroach/pkg/kv/kvserver/asim/tests/testdata/non_rand/mma/one_voter_skewed_cpu_skewed_write.txt:23:
          gen_load
          ----
          0.50 access-vcpus
    datadriven_simulation_test.go:213: 
        /home/roach/.cache/bazel/_bazel_roach/c5a4e7d36696d9cd970af2045211a7df/sandbox/processwrapper-sandbox/2560/execroot/com_github_cockroachdb_cockroach/bazel-out/k8-fastbuild/bin/pkg/kv/kvserver/asim/tests/tests_test_/tests_test.runfiles/com_github_cockroachdb_cockroach/pkg/kv/kvserver/asim/tests/testdata/non_rand/mma/one_voter_skewed_cpu_skewed_write.txt:30:
          gen_load
          ----
          0.00 raft-vcpus, 4.8 MiB/s goodput
    datadriven_simulation_test.go:213: 
        /home/roach/.cache/bazel/_bazel_roach/c5a4e7d36696d9cd970af2045211a7df/sandbox/processwrapper-sandbox/2560/execroot/com_github_cockroachdb_cockroach/bazel-out/k8-fastbuild/bin/pkg/kv/kvserver/asim/tests/tests_test_/tests_test.runfiles/com_github_cockroachdb_cockroach/pkg/kv/kvserver/asim/tests/testdata/non_rand/mma/one_voter_skewed_cpu_skewed_write.txt:34:
          setting
          ----
    datadriven_simulation_test.go:587: running eval for one_voter_skewed_cpu_skewed_write
```
<details><summary>Help</summary>
<p>

See also: [How To Investigate a Go Test Failure \(internal\)](https://cockroachlabs.atlassian.net/l/c/HgfXfJgM)
</p>
</details>
/cc @cockroachdb/kv-triage @cockroachdb/kv-triage
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*TestDataDriven.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/bazci/githubpost/issues)

</sub>

Jira issue: CRDB-57504

### PR DESCRIPTION
**Pull request by wenyihu6**
Previously we started filtering candidates based on their lease disposition.
Asim dd don’t have the full integration yet, so every store stays with an
unknown health status instead of the proper initialized state you get in
TestClusterState. Future PR will address that initialization. This commit
simply prevents the panic by continuing early when filtering on health leaves the
candidate set empty.

Fixes: https://github.com/cockroachdb/cockroach/issues/158833
Release note: none

### CODE REVIEW

**Review by iskettaneh — APPROVED** [review]

**Review by tbg — APPROVED** [review]

File: pkg/kv/kvserver/allocator/mmaprototype/cluster_state_rebalance_stores.go [hunk 1]
```diff
@@ -644,6 +644,12 @@ func (re *rebalanceEnv) rebalanceLeasesFromLocalStoreID(
 		}
 
 		candsPL = retainReadyLeaseTargetStoresOnly(ctx, candsPL, re.stores, rangeID)
+		if len(candsPL) == 0 {
```
Comment (tbg) [inline pkg/kv/kvserver/allocator/mmaprototype/cluster_state_rebalance_stores.go:647]: Anchor comment (since I'll need to remove this in an open PR I have)
