### PR TITLE
cli: fix help texts

### LINKED ISSUE #15261: cli: spelling and formatting errors in --allow-ca-key-reuse and --certs-dir help texts
Spelling error:

```
      --allow-ca-key-reuse
        Use the CA key if is exists.
```

Missing spacing/formatting:

```
      --certs-dir string
        The path to the directory containing SSL certificates and keys.
        Cockroach looks for certificates and keys inside the directory using
        the following naming scheme:  CA certificate and key: ca.crt, ca.key
        Server certificate and key: node.crt, node.key Client certificate
        and key: client.<user>.crt, client.<user>.key  When running client
        commands, the user can be specified with the --user flag.  Keys
        have a minimum permission requirement of 0777 (rwx------). This
        restriction can be disabled by setting the environment variable
        COCKROACH_SKIP_KEY_PERMISSION_CHECK to true.
        Environment variable: COCKROACH_CERTS_DIR
        (default "${HOME}/.cockroach-certs")
```

### PR DESCRIPTION
**Pull request by jseldess**
- use `<PRE>` tags to add line breaks/spacing
  to `--certs-dir` text
- fix spelling in `--allow-ca-key-reuse` text

Fixes #15261

### CODE REVIEW

File: pkg/cli/cliflags/flags.go [hunk 1]
```diff
@@ -287,15 +287,17 @@ production usage.`,
 		EnvVar: "COCKROACH_CERTS_DIR",
 		Description: `
 The path to the directory containing SSL certificates and keys.
+<PRE>
```
Comment (mberhault) [inline pkg/cli/cliflags/flags.go]: apparently we already wrap all descriptions in `<PRE>` tags automatically. See https://github.com/cockroachdb/cockroach/blob/master/pkg/cli/flags.go#L90

**Comment by mberhault** [comment]
LGTM. Thanks.
