### PR TITLE
Remove error "no txn persisted, yet intent has heartbeat"

### LINKED ISSUE #2111: TestSingleKey: no txn persisted, yet intent has heartbeat
The following test appears to have failed:

[#5940](https://circleci.com/gh/cockroachdb/cockroach/5940):

```
=== RUN TestPut
--- PASS: TestPut (22.56s)
=== RUN TestRangeReplication
--- PASS: TestRangeReplication (12.07s)
=== RUN TestSingleKey
--- FAIL: TestSingleKey (19.64s)
	single_key_test.go:125: txn "acceptance/single_key_test.go:101 func·008" id=d508bfcc key="test-key" rw=false pri=87.92241271 iso=SERIALIZABLE stat=PENDING epo=1 ts=1439565620.755168676,2 orig=1439565620.742974281,0 max=1439565620.992974043,0: no txn persisted, yet intent has heartbeat
=== RUN TestStatusServer
--- PASS: TestStatusServer (18.48s)
FAIL
ok github.com/cockroachdb/cockroach/acceptance 1337s

```
Please assign, take a look and update the issue accordingly.

### PR DESCRIPTION
**Pull request by thschroeter**
Fixes #2111.

### CODE REVIEW

File: storage/replica_command.go [hunk 1]
```diff
@@ -756,10 +756,8 @@ func (r *Replica) PushTxn(batch engine.Engine, ms *engine.MVCCStats, args proto.
 		}
 	} else {
 		// Some sanity checks for case where we don't find a transaction record.
-		if args.PusheeTxn.LastHeartbeat != nil {
-			return reply, proto.NewTransactionStatusError(&args.PusheeTxn,
-				"no txn persisted, yet intent has heartbeat")
-		} else if args.PusheeTxn.Status != proto.PENDING {
+		// If `args.PusheeTxn.LastHeartbeat != nil`, assume txn is gc'ed, see #2111.
```
Comment (bdarnell) [inline storage/replica_command.go]: This comment doesn't make sense with all references to LastHeartbeat gone from the code. I'd just remove this comment completely.

**Comment by bdarnell** [comment]
LGTM. How hard would it be to add a test for this?

File: storage/replica_command.go (hunk 1 above)
Comment (tschottdorf) [inline storage/replica_command.go]: There's some value in some type of comment to discuss the case of a record being missing. Maybe above the `if ok { ...` above, with content something like

>
// There are three cases in which there is no transaction entry, in decreasing likelyhood
// * a transaction is still active; it just hasn't committed/restarted/aborted/heartbeat yet
// * the transaction resolved its intents synchronously on successful commit; in that case,
// * the transaction record is also removed. Note that in this case, the intent which prompted
//   this `PushTxn` doesn't exist any more.
// * the transaction timed out/was aborted and the intent not cleaned up, but the transaction
//  record recycled.
// We currently make no attempt at guessing which one it is, though we could (see #1939).
// Instead, a new entry is always written, and the Push assumes in all cases that the transaction is still running.
// TODO(tschottdorf): we should actually improve this when we garbage-collect aborted transactions, or we run the risk of a push recreating a GC'ed transaction as `PENDING`, which is an error if it has open intents (which is likely if someone pushes it). Likely a non-issue since the timestamp will indicate the transaction as aborted, yet should be thought out carefully.

Comment (bdarnell) [inline storage/replica_command.go]: SGTM, although the asterisk on the fourth line shouldn't be there.

Comment (tschottdorf) [inline storage/replica_command.go]: If we write a PENDING entry, it could mean having pushed the Txn into the future. That means that it's going to update the intent (see `MVCCResolveWriteIntent`). I've checked that it'll be a no-op since the epoch hasn't increased:
```go
	// This method shouldn't be called in this instance, but there's
	// nothing to do if meta's epoch is greater than or equal txn's
	// epoch and the state is still PENDING.
```

so it ends there (and nobody's going to commit this resuscitated transaction anyways), but we still end up keeping the intent and having a fresh and shiny transaction table entry for others to have to play the conflict resolution game with.

Discussing that with the above seems adequate so that we avoid recreating the entry and allow the push when we know that it's GC at work (being able to do this depends on #2062 though).

**Comment by thschroeter** [comment]
Added comment as Tobias suggests.

@bdarnell not sure if it's hard to test this. I can look into it for a follow-up PR if it makes sense.

File: storage/replica_command.go [hunk 2]
```diff
@@ -743,6 +743,19 @@ func (r *Replica) PushTxn(batch engine.Engine, ms *engine.MVCCStats, args proto.
 	if err != nil {
 		return reply, err
 	}
+	// There are three cases in which there is no transaction entry, in decreasing likelihood
```
Comment (tamird) [inline storage/replica_command.go]: nit: s/likelihood/likelihood:/

File: storage/replica_command.go [hunk 3]
```diff
@@ -743,6 +743,19 @@ func (r *Replica) PushTxn(batch engine.Engine, ms *engine.MVCCStats, args proto.
...
+	// * a transaction is still active; it just hasn't committed/restarted/aborted/heartbeat yet
```
Comment (tamird) [inline storage/replica_command.go]: either "the trasaction" or "a transaction" everywhere

File: storage/replica_command.go (hunk 2 above)
Comment (tamird) [inline storage/replica_command.go]: either "transaction entry" or "transaction record" everywhere

File: storage/replica_command.go [hunk 4]
```diff
@@ -743,6 +743,19 @@ func (r *Replica) PushTxn(batch engine.Engine, ms *engine.MVCCStats, args proto.
...
+	// * the transaction resolved its intents synchronously on successful commit; in this case,
+	// the transaction record is also removed. Note that in this case, the intent which prompted
+	// this PushTxn doesn't exist any more.
+	// * the transaction timed out/was aborted and the intent not cleaned up, but the transaction
+	// record recycled.
```
Comment (tamird) [inline storage/replica_command.go]: what does "recycled" mean exactly?

File: storage/replica_command.go [hunk 5]
```diff
@@ -743,6 +743,19 @@ func (r *Replica) PushTxn(batch engine.Engine, ms *engine.MVCCStats, args proto.
...
+	// We currently make no attempt at guessing which one it is, though we could (see #1939).
+	// Instead, a new entry is always written, and the Push assumes in all cases that the transaction is still running.
```
Comment (tamird) [inline storage/replica_command.go]: either Push or push everywhere

File: storage/replica_command.go (hunk 3 above)
Comment (thschroeter) [inline storage/replica_command.go]: I'm for "the transaction", although the original author of this comment is @tschottdorf.

File: storage/replica_command.go (hunk 5 above)
Comment (thschroeter) [inline storage/replica_command.go]: +1 for push

File: storage/replica_command.go (hunk 2 above)
Comment (tschottdorf) [inline storage/replica_command.go]: can you make sure that the comments don't overflow 80 chars?

File: storage/replica_command.go (hunk 4 above)
Comment (thschroeter) [inline storage/replica_command.go]: I don't know. @tschottdorf, care to chime in?

File: storage/replica_command.go (hunk 3 above)
Comment (tschottdorf) [inline storage/replica_command.go]: it's your comment now ;) I actually suggest s/transaction/pushee/, since a `PushTxn` always involves two transactions: the pusher and pushee.

File: storage/replica_command.go [hunk 6]
```diff
@@ -743,6 +743,19 @@ func (r *Replica) PushTxn(batch engine.Engine, ms *engine.MVCCStats, args proto.
 	if err != nil {
 		return reply, err
 	}
+	// There are three cases in which there is no transaction entry, in decreasing likelihood
+	// * a transaction is still active; it just hasn't committed/restarted/aborted/heartbeat yet
+	// * the transaction resolved its intents synchronously on successful commit; in this case,
+	// the transaction record is also removed. Note that in this case, the intent which prompted
```
Comment (tschottdorf) [inline storage/replica_command.go]: check that for multi-line bullets, the extra lines are properly indented to line up with the first word on the first line.

File: storage/replica_command.go (hunk 4 above)
Comment (tschottdorf) [inline storage/replica_command.go]: s/recycled/garbage collected/

File: storage/replica_command.go [hunk 7]
```diff
@@ -743,6 +743,19 @@ func (r *Replica) PushTxn(batch engine.Engine, ms *engine.MVCCStats, args proto.
...
+	// this PushTxn doesn't exist any more.
+	// * the transaction timed out/was aborted and the intent not cleaned up, but the transaction
+	// record recycled.
+	// We currently make no attempt at guessing which one it is, though we could (see #1939).
+	// Instead, a new entry is always written, and the Push assumes in all cases that the transaction is still running.
+	// TODO(tschottdorf): we should actually improve this when we garbage-collect aborted transactions,
+	// or we run the risk of a push recreating a GC'ed transaction as PENDING, which is an error if it has open
+	// intents (which is likely if someone pushes it). Likely a non-issue since the timestamp will indicate
+	// the transaction as aborted, yet should be thought out carefully.
```
Comment (tschottdorf) [inline storage/replica_command.go]: replace
> Likely a non-issue since the timestamp will indicate the transaction as aborted, yet should be thought out carefully.

with

>
This is not a correctness issue since nobody will ever commit this transaction, but
it also updates the intent, leading to more pointless and, potentially cyclic, conflict
resolution. Simply reporting success to the caller and not writing a new entry will
be preferable. See (#insertissuehere).

File: storage/replica_command.go (hunk 5 above)
Comment (tschottdorf) [inline storage/replica_command.go]: s/and the Push assumes in all cases that the transaction is still running//
(if pusher decides it won, it'll "abort" pushee)

File: storage/replica_command.go (hunk 7 above)
Comment (tschottdorf) [inline storage/replica_command.go]: sorry, skip the issue thingie. Just saw it's already mentioned above.

File: storage/replica_command.go (hunk 4 above)
Comment (tschottdorf) [inline storage/replica_command.go]: (i.e., just not there any more)

**Comment by thschroeter** [comment]
done

**Comment by tschottdorf** [comment]
LGTM :+1: Thanks Thomas!
