### PR TITLE
kvserver: fix Replica.tenantLimiter race

### LINKED ISSUE #109729: sql/colflow: TestDrainingAfterRemoteError failed
sql/colflow.TestDrainingAfterRemoteError [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Ci_TestsAwsLinuxArm64_UnitTests/11554987?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Ci_TestsAwsLinuxArm64_UnitTests/11554987?buildTab=artifacts#/) on master @ [f464c0607bdd695aceec4e51704b9dc11d465204](https://github.com/cockroachdb/cockroach/commits/f464c0607bdd695aceec4e51704b9dc11d465204):

```
=== RUN   TestDrainingAfterRemoteError
    test_log_scope.go:167: test logs captured to: /artifacts/tmp/_tmp/7f1b06f9801c2789f14134f543b8b883/logTestDrainingAfterRemoteError3264099528
    test_log_scope.go:81: use -show-logs to present logs inline
    test_server_shim.go:132: automatically injected virtual cluster under test; see comment at top of test_server_shim.go for details.
    draining_test.go:83: error executing 'SELECT count(*) FROM small;': pq: 10 pool closed: released
    panic.go:522: -- test log scope end --
test logs left over in: /artifacts/tmp/_tmp/7f1b06f9801c2789f14134f543b8b883/logTestDrainingAfterRemoteError3264099528
--- FAIL: TestDrainingAfterRemoteError (10.13s)
```
<details><summary>Help</summary>
<p>

See also: [How To Investigate a Go Test Failure \(internal\)](https://cockroachlabs.atlassian.net/l/c/HgfXfJgM)
</p>
</details>
/cc @cockroachdb/sql-queries
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*TestDrainingAfterRemoteError.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)
</sub>

Jira issue: CRDB-31069

### PR DESCRIPTION
**Pull request by pav-kv**
If a `Replica` is destroyed while or shortly before `Send` waits for the tenant rate limiter, the rate limiter returns a `quotapool.ErrClosed` which propagates all the way up to the SQL client. This commit fixes `maybeRateLimitBatch` to return the `Replica` destruction status error instead, so that the `Send` stack retries the request.

Release note (bug fix): fixed a race condition in `Replica` lifecycle which could result in a failed SQL request in cases where it could be successfully retried.

Fixes #109729
Epic: none

### CODE REVIEW

**Comment by pavelkalinnikov** [comment]
Writing a test for it.

File: pkg/kv/kvserver/replica_rate_limit.go [hunk 1]
```diff
@@ -29,8 +31,25 @@ func (r *Replica) maybeRateLimitBatch(ctx context.Context, ba *kvpb.BatchRequest
...
+	// call. In this case Wait returns an ErrClosed error. Instead of ErrClosed,
+	// return the destruction status error which upper layers recognize.
+	if errors.HasType(err, (*quotapool.ErrClosed)(nil)) {
+		r.mu.RLock()
+		defer r.mu.RUnlock()
+		if !r.mu.destroyStatus.Removed() {
+			return errors.AssertionFailedf("replica not marked as destroyed but limiter is closed: %v", r)
+		}
+		return r.mu.destroyStatus.err
+	}
```
Comment (erikgrinaker) [inline pkg/kv/kvserver/replica_rate_limit.go:50]:
```suggestion
	if err != nil && errors.HasType(err, (*quotapool.ErrClosed)(nil)) {
		if _, err := r.IsDestroyed(); err != nil {
			return err
		} else {
			return errors.AssertionFailedf("replica not marked as destroyed but limiter is closed: %v", r)
		}
	}
```

**Comment by pavelkalinnikov** [comment]
Stressed the new test a bunch, works.

File: pkg/kv/kvserver/replica_rate_limit_test.go [hunk 2]
```diff
@@ -0,0 +1,107 @@
...
+	stopper := stop.NewStopper()
+	defer stopper.Stop(ctx)
+
+	tc := testContext{manualClock: timeutil.NewManualTime(timeutil.Unix(0, 123))}
+	cfg := TestStoreConfig(hlc.NewClockForTesting(tc.manualClock))
+	tenantrate.KVCURateLimit.Override(ctx, &cfg.Settings.SV, 1)
+	cfg.TestingKnobs.DisableMergeWaitForReplicasInit = true
+	cfg.TestingKnobs.TenantRateKnobs.TimeSource = tc.manualClock
+	cfg.TestingKnobs.TenantRateKnobs.Authorizer = tenantcapabilitiesauthorizer.New(cfg.Settings, nil)
+	tc.StartWithStoreConfig(ctx, t, stopper, cfg)
```
Comment (pavelkalinnikov) [inline pkg/kv/kvserver/replica_rate_limit_test.go:45]: Need to add some comments here on why we need each of the knobs.

Could do with some helper too.

**Review by erikgrinaker — APPROVED** [review]
Nice, thanks!

File: pkg/kv/kvserver/replica_rate_limit_test.go [hunk 3]
```diff
@@ -0,0 +1,106 @@
...
+	"github.com/cockroachdb/cockroach/pkg/util/ctxgroup"
+	"github.com/cockroachdb/cockroach/pkg/util/hlc"
+	"github.com/cockroachdb/cockroach/pkg/util/leaktest"
+	"github.com/cockroachdb/cockroach/pkg/util/stop"
+	"github.com/cockroachdb/cockroach/pkg/util/timeutil"
+	"github.com/cockroachdb/errors"
+	"github.com/stretchr/testify/require"
+)
+
+func TestReplicaRateLimit(t *testing.T) {
```
[the remark this answers is not in the document]
Comment (pavelkalinnikov) [reply pkg/kv/kvserver/replica_rate_limit_test.go]: Done.

**Comment by pavelkalinnikov** [comment]
bors r=erikgrinaker
