### PR TITLE
changefeedccl: opt out of db-level feed testing for offline table error

### LINKED ISSUE #159056: ccl/changefeedccl: TestChangefeedFailOnTableOffline failed
ccl/changefeedccl.TestChangefeedFailOnTableOffline [failed](https://mesolite.cluster.engflow.com/invocations/default/718fa127-2b04-4969-b9f5-cec8241a16cb?testReportRun=1&testReportShard=16&testReportAttempt=1#targets-Ly9wa2cvY2NsL2NoYW5nZWZlZWRjY2w6Y2hhbmdlZmVlZGNjbF90ZXN0) on master @ [0dfe683011030a2e335015e62ccd707a29fbc672](https://github.com/cockroachdb/cockroach/commits/0dfe683011030a2e335015e62ccd707a29fbc672):

```
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunAsyncTaskEx in goroutine 211484
	pkg/util/stop/stopper.go:438 +0x125

goroutine 210746 [runnable]:
github.com/cockroachdb/cockroach/pkg/sql.(*ieResultChannel).firstResult(0xc014531980, {0x8c202b0, 0xc00e0bdae0})
	pkg/sql/internal_result_channel.go:118 +0xfc
github.com/cockroachdb/cockroach/pkg/sql.(*InternalExecutor).execInternal(_, {_, _}, {_, _}, _, _, _, {{{0x0, 0x0}}, ...}, ...)
	pkg/sql/internal.go:1387 +0xf5b
github.com/cockroachdb/cockroach/pkg/sql.(*InternalExecutor).execIEStmt(_, {_, _}, {_, _}, _, {{{0x0, 0x0}}, {0x0, 0x0}, ...}, ...)
	pkg/sql/internal.go:859 +0x1c5
github.com/cockroachdb/cockroach/pkg/sql.(*InternalExecutor).ExecEx(...)
	pkg/sql/internal.go:814
github.com/cockroachdb/cockroach/pkg/sql.(*InternalExecutor).Exec(0xc00e0bd9a0, {0x8c1dfe0, 0xc01eb12410}, {0x7b9b7b7, 0xa}, 0xc00e0b8580, {0x7ebca6c, 0x108}, {0xc01c6a5d40, 0x3, ...})
	pkg/sql/internal.go:798 +0x1e5
github.com/cockroachdb/cockroach/pkg/jobs.(*Registry).Start.func5.(*Registry).claimJobs.1({0x8c1dfe0, 0xc01eb12410}, {0x8caddd0, 0xc00e0bd9a0})
	pkg/jobs/adopt.go:104 +0x22e
github.com/cockroachdb/cockroach/pkg/sql.(*internalDBWithOverrides).Txn.func1({0x8c1dfe0, 0xc01eb12410}, {0x8caddd0, 0xc00e0bd9a0})
	pkg/sql/internal.go:2128 +0xa3
github.com/cockroachdb/cockroach/pkg/sql.(*InternalDB).Txn.func1({0x8c1dfe0?, 0xc01eb12410?}, 0x8ca09b0?)
	pkg/sql/internal.go:1965 +0x2b
github.com/cockroachdb/cockroach/pkg/sql.(*InternalDB).txn.func4({0x8c1dfe0, 0xc01eb12410}, 0xc00e0b8580)
	pkg/sql/internal.go:2052 +0x33e
github.com/cockroachdb/cockroach/pkg/kv.(*Txn).exec(0xc00e0b8580, {0x8c1dfe0, 0xc01eb12410}, 0xc014531900)
	pkg/kv/txn.go:1139 +0x9e
github.com/cockroachdb/cockroach/pkg/kv.runTxn({0x8c1dfe0, 0xc01eb12410}, 0xc00e0b8580, 0x1?)
	pkg/kv/db.go:1114 +0x3e
github.com/cockroachdb/cockroach/pkg/kv.(*DB).TxnWithAdmissionControl(0xc006e73998?, {0x8c1dfe0, 0xc01eb12410}, 0x776d3a0?, 0x0?, 0x0, 0xc014531900)
	pkg/kv/db.go:1077 +0xa5
github.com/cockroachdb/cockroach/pkg/kv.(*DB).Txn(...)
	pkg/kv/db.go:1052
github.com/cockroachdb/cockroach/pkg/sql.(*InternalDB).txn(0xc00e6b8000, {0x8c1dfe0, 0xc01eb12410}, 0xc012b1f0a0, {0x0, 0x0, 0x4dd601?})
	pkg/sql/internal.go:2039 +0x27a
github.com/cockroachdb/cockroach/pkg/sql.(*InternalDB).Txn(0xc00e6b8000, {0x8c1dfe0, 0xc01eb12410}, 0xc00f0feee8, {0x0, 0x0, 0x0})
	pkg/sql/internal.go:1966 +0x97
github.com/cockroachdb/cockroach/pkg/sql.(*internalDBWithOverrides).Txn(0xc020e86f00, {0x8c1dfe0, 0xc01eb12410}, 0xc01b1e0fc0, {0x0, 0x0, 0x0})
	pkg/sql/internal.go:2124 +0xa9
github.com/cockroachdb/cockroach/pkg/jobs.(*Registry).claimJobs(...)
	pkg/jobs/adopt.go:98
github.com/cockroachdb/cockroach/pkg/jobs.(*Registry).Start.func5({0x8c1dfe0, 0xc01eb12410}, {0x8c14620, 0xc01e8cd2c0})
	pkg/jobs/registry.go:991 +0x158
github.com/cockroachdb/cockroach/pkg/jobs.(*Registry).withSession(0xc0032e1008, {0x8c1dfe0, 0xc01eb12410}, 0xc020f18e40)
	pkg/jobs/registry.go:926 +0x263
github.com/cockroachdb/cockroach/pkg/jobs.(*Registry).Start.(*Registry).Start.func1.func12({0x8c1dfe0?, 0xc01eb12410?})
	pkg/jobs/registry.go:942 +0x2e
github.com/cockroachdb/cockroach/pkg/jobs.(*Registry).Start.func10({0x8c1e018?, 0xc009bfe870?})
	pkg/jobs/registry.go:1132 +0x2e4
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunAsyncTaskEx.func1({0x8c1e018, 0xc009bfe870})
	pkg/util/stop/stopper.go:440 +0x8a
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunAsyncTaskEx in goroutine 209778
	pkg/util/stop/stopper.go:438 +0x125
```

Parameters:
 - <code>attempt=1</code>
 - <code>run=1</code>
 - <code>shard=16</code>
<details><summary>Help</summary>
<p>

See also: [How To Investigate a Go Test Failure \(internal\)](https://cockroachlabs.atlassian.net/l/c/HgfXfJgM)
</p>
</details>
/cc @cockroachdb/cdc
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*TestChangefeedFailOnTableOffline.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/bazci/githubpost/issues)

</sub>

Jira issue: CRDB-57643

### PR DESCRIPTION
**Pull request by log-head**
A previous patch allowed db-level changefeeds to not end with a terminal error when a watched table becomes offline. The existing test asserted that table-level changefeeds fail with that terminal error. Metamorphic testing caused these changefeeds to instead be changed to db-level, causing the test to fail when no terminal error occurred.

This patch opts out from metamorphic db-level testing for the test that asserts that a table-level changefeed fails with a terminal error when encountering an offline table.

Fixes: #159056
Release note: None

### CODE REVIEW

File: pkg/ccl/changefeedccl/changefeed_test.go [hunk 1]
```diff
@@ -5859,7 +5859,10 @@ func TestChangefeedFailOnTableOffline(t *testing.T) {
 		sqlDB.Exec(t, `CREATE TABLE for_import (a INT PRIMARY KEY, b INT) WITH (schema_locked=false)`)
 		defer sqlDB.Exec(t, `DROP TABLE for_import`)
 		sqlDB.Exec(t, `INSERT INTO for_import VALUES (0, NULL)`)
-		forImport := feed(t, f, `CREATE CHANGEFEED FOR for_import `)
+		forImport := feed(t, f, `CREATE CHANGEFEED FOR for_import `,
+			optOutOfMetamorphicDBLevelChangefeed{
+				reason: "testing error message not applicable to DB level changefeeds",
```
Comment (aerfrei) [inline pkg/ccl/changefeedccl/changefeed_test.go]: This makes sense to me. nit: Can we make the reason parse a bit more unambiguously? Is the testing or the message not applicable? Maybe "DB level changefeeds do not fail with `cannot target offline table` terminal error" or some other phrasing.

**Review by aerfrei — APPROVED** [review]

**Review by asg0451 — APPROVED** [review]
