### PR TITLE
backupccl: add logging to schedule PTS management

### LINKED ISSUE #105710: backcupccl: add logging to backup schedules PTS chaining
We want increased observability into the chaining actions being performed by backup schedules. This will help debug cases like https://github.com/cockroachlabs/support/issues/2409 where a random backup fails because the data it is trying to read has been GC'ed. With active PTS management by schedules we should be entirely decoupled from the GC TTL. 

I would like logs to indicate when:
- the full backup schedule is writing its PTS
- the full backup schedule is releasing the old backup chains PTS
- the incremental backup schedule is updating its PTS

Jira issue: CRDB-29156

### PR DESCRIPTION
**Pull request by adityamaru**
We sometimes get escalations about schedules not
protecting the data we expect. These are very hard to debug after the fact without breadcrumbs about what the schedule did with the PTS records.

Fixes: #105710
Release note: None

### CODE REVIEW

File: pkg/ccl/backupccl/schedule_pts_chaining.go [hunk 1]
```diff
@@ -240,6 +242,9 @@ func manageFullBackupPTSChaining(
 	// about to release. Already running incremental backup jobs would have
 	// written their own pts record during planning, and should complete
 	// successfully.
+	log.Infof(ctx, "schedule %d is releasing a protected timestamp record at %s",
```
Comment (adityamaru) [inline pkg/ccl/backupccl/schedule_pts_chaining.go:245]: rah I think I want the full schedule ID here, one second

**Review by rhu713 — APPROVED** [review]

**Comment by adityamaru** [comment]
TFTR!

bors r=rhu713

**Comment by adityamaru** [comment]
blathers backport 23.1 22.2
