### PR TITLE
changefeedccl: Fix cluster ID check logic

### LINKED ISSUE #106358: cdc: Changefeed fail when upgrading to 23.1.x
https://github.com/cockroachdb/cockroach/pull/99841 introduced logic to changefeed
resume to verify that the changefeed job record has the cluster ID matching the ID of the
node running changefeed.  This was added to ensure that if we fully restore from backup,
or in case of physical replication, that the changefeed jobs does not automatically
start execution in the new cluster (this is dangerous and likely very undesirable).

Unfortunately, the logic is faulty since it will fail any changefeed created prior to 23.1 since
the check was lacking version gate.

Jira issue: CRDB-29526

### PR DESCRIPTION
**Pull request by miretskiy**
Changefeeds created prior to
https://github.com/cockroachdb/cockroach/pull/99841 do not have cluster ID field set in their job record.  As a result, when upgrading to 23.1.x version, changefeeds created prior to that version will fail with an error message introduced by the above PR.

Fix the cluster ID checking logic to handle this case.
Fixes #106358

Release note (enterprise change): Changefeeds should no longer fail when upgrading to version 23.1.5.

### CODE REVIEW

File: pkg/ccl/changefeedccl/changefeed_test.go [hunk 1]
```diff
@@ -1368,6 +1370,48 @@ func TestChangefeedProjectionDelete(t *testing.T) {
...
+			})
+		}())
+
+		// Resume; we expect to see deleted row.
+		require.NoError(t, jobFeed.Resume())
+		assertPayloads(t, foo, []string{
+			`foo: [0]->{"after": null}`,
+		})
+	}
+	cdcTest(t, testFn, feedTestForceSink("cloudstorage"))
```
Comment (samiskin) [inline pkg/ccl/changefeedccl/changefeed_test.go:1412]: I assume this would work with `feedTestEnterpriseSinks`

File: pkg/ccl/changefeedccl/changefeed_test.go [hunk 2]
```diff
@@ -1368,6 +1370,48 @@ func TestChangefeedProjectionDelete(t *testing.T) {
...
+				ju.UpdatePayload(md.Payload)
+				return nil
+			})
+		}())
+
+		// Resume; we expect to see deleted row.
+		require.NoError(t, jobFeed.Resume())
+		assertPayloads(t, foo, []string{
+			`foo: [0]->{"after": null}`,
+		})
```
Comment (samiskin) [inline pkg/ccl/changefeedccl/changefeed_test.go:1410]: Could add a check for us automatically setting the `CreationClusterID` correctly afterwards after resuming

File: pkg/ccl/changefeedccl/changefeed_stmt.go [hunk 3]
```diff
@@ -1108,6 +1108,27 @@ func (b *changefeedResumer) Resume(ctx context.Context, execCtx interface{}) err
 	return nil
 }
 
+// ensureClusterIDMatches verifies that this job record matches
+// the cluster ID of this cluster.
```
Comment (samiskin) [inline pkg/ccl/changefeedccl/changefeed_stmt.go:1112]: could help to mention the context (streaming replication) in which this would error

File: pkg/ccl/changefeedccl/changefeed_stmt.go [hunk 4]
```diff
@@ -1108,6 +1108,27 @@ func (b *changefeedResumer) Resume(ctx context.Context, execCtx interface{}) err
...
+func (b *changefeedResumer) ensureClusterIDMatches(ctx context.Context, clusterID uuid.UUID) error {
+	if createdBy := b.job.Payload().CreationClusterID; createdBy == uuid.Nil {
+		// This cluster was upgraded from the version that did not set clusterID
```
Comment (samiskin) [inline pkg/ccl/changefeedccl/changefeed_stmt.go:1115]:
```suggestion
		// This cluster was upgraded from a version that did not set clusterID
```

**Review by samiskin — APPROVED** [review]

File: pkg/ccl/changefeedccl/changefeed_test.go (hunk 1 above)
Comment (miretskiy) [reply pkg/ccl/changefeedccl/changefeed_test.go:1412]: Sure; I just copied it from elsewhere; changed.

File: pkg/ccl/changefeedccl/changefeed_test.go (hunk 2 above)
Comment (miretskiy) [reply pkg/ccl/changefeedccl/changefeed_test.go:1410]: Good idea; done.

File: pkg/ccl/changefeedccl/changefeed_stmt.go (hunk 4 above)
Comment (miretskiy) [reply pkg/ccl/changefeedccl/changefeed_stmt.go:1115]: Done.

File: pkg/ccl/changefeedccl/changefeed_stmt.go (hunk 3 above)
Comment (miretskiy) [reply pkg/ccl/changefeedccl/changefeed_stmt.go:1112]: extended comment.
