### PR TITLE
storage: tick the logical clock for quiescent ranges

### LINKED ISSUE #9372: storage: quiescence leads to more elections
I'm able to reproduce the additional elections when quiescing is turned on in a local test environment. Within a single scheduler worker iteration we do the following:

```
			// Process the range ID.
			if state&stateRaftTick != 0 {
				// processRaftTick returns true if the range should perform ready
				// processing. Do not reorder this below the call to processRaftReady.
				if s.processor.processTick(id) {
					state |= stateRaftReady
				}
			}
			if state&stateRaftRequest != 0 {
				s.processor.processRequestQueue(id)
			}
			if state&stateRaftReady != 0 {
				s.processor.processReady(id)
			}
```

My untested hypothesis of what is happening:
1. Follower ticks a replica.
2. Follower processes a "quiesce" message from the leader.
3. Followers performs raft ready processing (due to the earlier tick) which unquiesces the replica.

At this point, the leader is "quiesced" but the follower is not. The follower will tick and then perform an election. What I'm not quite clear on is that exact timing for why this causes a disruption of request processing.

### PR DESCRIPTION
**Pull request by petermattis**
Fixes #9372.

I see this being done in addition to #9383. See the commentary on #9372 for details. I'm sending this out for discussion and would add more commentary to this PR if we decide to move ahead with it. This PR relies on the following patch to `github.com/coreos/etcd/raft/rawnode.go`:

``` diff
diff --git a/raft/rawnode.go b/raft/rawnode.go
index 54c5000..e916483 100644
--- a/raft/rawnode.go
+++ b/raft/rawnode.go
@@ -120,6 +120,12 @@ func (rn *RawNode) Tick() {
        rn.raft.tick()
 }

+// TickClock advances the internal logical clock by a single tick without
+// performing any other processing.
+func (rn *RawNode) TickClock() {
+       rn.raft.electionElapsed++
+}
+
 // Campaign causes this RawNode to transition to candidate state.
 func (rn *RawNode) Campaign() error {
        return rn.raft.Step(pb.Message{
```

Cc @cockroachdb/stability

---

This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/9407)

### CODE REVIEW

**Comment by tschottdorf** [comment]
Looks good to me, though the upstream interface is likely to confuse reviewers because the intention isn't clear. Perhaps `TickQuiesced` is the right name, along with more commentary on intended purpose.

**Comment by petermattis** [comment]
Renamed to `TickQuiesced`. See https://github.com/coreos/etcd/pull/6441.

**Review by rjnn — APPROVED** [review]
:lgtm:

**Comment by petermattis** [comment]
Upstream merged. I added a bunch of commentary to the usage of `TickQuiesced`. PTAL.

File: storage/replica.go [hunk 1]
```diff
@@ -1987,6 +1987,24 @@ func (r *Replica) tickRaftMuLocked() (bool, error) {
 		return false, nil
 	}
 	if r.mu.quiescent {
+		// While a replica is quiesced we still advance its logical clock. This is
+		// necessary to avoid a scenario where the leader quiesces and a follower
+		// does not. The follower calls an election but the election fails because
+		// the leader and other follower believe that no time in the current term
+		// has passed. The Raft group is then in a state where one member has a
```
Comment (tschottdorf) [inline storage/replica.go]: Might wanna mention that this is an election thrashing prevention method toggled by the `CheckQuorum` option (enabled at time of writing).

**Review by tbg — APPROVED** [review]
LGTM

File: storage/replica.go (hunk 1 above)
Comment (petermattis) [inline storage/replica.go]: Done.

**Comment by petermattis** [comment]
Doh, accidentally merged this to develop.
