### PR TITLE
azure: use ResumingReader

### LINKED ISSUE #154849: roachtest: backupFixture/tpcc/warehouses=5000/incrementals=48 failed
roachtest.backupFixture/tpcc/warehouses=5000/incrementals=48 [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyAzureBazel/20563533?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyAzureBazel/20563533?buildTab=artifacts#/backupFixture/tpcc/warehouses=5000/incrementals=48) on master @ [14ff833383127fa428b913c5281a8a6c862e2a41](https://github.com/cockroachdb/cockroach/commits/14ff833383127fa428b913c5281a8a6c862e2a41):

```
(sql_runner.go:271).Query: error executing 'SELECT job_id, status, error FROM [SHOW JOBS] WHERE job_type = 'BACKUP' AND description ILIKE 'COMPACT BACKUPS%'': dial tcp 20.106.176.74:26257: connect: connection refused
test artifacts and logs in: /artifacts/backupFixture/tpcc/warehouses=5000/incrementals=48/run_1
```

Parameters:
 - <code>arch=amd64</code>
 - <code>cloud=azure</code>
 - <code>coverageBuild=false</code>
 - <code>cpu=8</code>
 - <code>encrypted=true</code>
 - <code>runtimeAssertionsBuild=false</code>
 - <code>ssd=0</code>
<details><summary>Help</summary>
<p>

See: [roachtest README](https://github.com/cockroachdb/cockroach/blob/master/pkg/cmd/roachtest/README.md)

See: [How To Investigate \(internal\)](https://cockroachlabs.atlassian.net/l/c/SSSBr8c7)

_Grafana is not yet available for azure clusters_</p>
</details>
/cc @cockroachdb/disaster-recovery
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*backupFixture/tpcc/warehouses=5000/incrementals=48.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/bazci/githubpost/issues)

</sub>

### PR DESCRIPTION
**Pull request by jeffswenson**
Previously, the azure client did not use the ResumingReader. This was causing tracing span use after free issues as the client would issue http retries with a span that was already finished. The ResumingReader manages a span for the lifetime of the reader.

There is also some evidence in #154483 that the RetryReader built into the azure client did not properly retry errors that occur while reading the body.

Fixes: #154849
Release note: none

### CODE REVIEW

File: pkg/cloud/azure/azure_storage.go [hunk 1]
```diff
@@ -356,31 +356,47 @@ func isNotFoundErr(err error) bool {
...
-		HTTPRange{Offset: opts.Offset}})
-	if err != nil {
-		if isNotFoundErr(err) {
-			return nil, 0, cloud.WrapErrFileDoesNotExist(err, "azure blob does not exist")
-		}
-		return nil, 0, errors.Wrapf(err, "failed to create azure reader")
-	}
+	sp.SetTag("path", attribute.StringValue(object))
 
-	if !opts.NoFileSize {
```
Comment (msbutler) [inline pkg/cloud/azure/azure_storage.go:371]: i wonder why you removed the NoFileSize logic here.

**Review by msbutler — APPROVED** [review]
Going to merge this now to quiet the test

File: pkg/cloud/azure/azure_storage.go (hunk 1 above)
Comment (jeffswenson) [reply pkg/cloud/azure/azure_storage.go:371]: NoFileSize is an optimization. It exists so that we can sometimes elide an extra request when we don't need the file size. But in this case we get it for free. The new behavior is consistent with the gcp storage implementation.

Comment (msbutler) [reply pkg/cloud/azure/azure_storage.go:371]: ah, after rereading the code, this now makes sense.
