### PR TITLE
pgwire: handle case where TypeHints != PreparedArguments

### LINKED ISSUE #59007: sql/pgwire: Database sometimes will crash if bind incorrect number of parameters
**Describe the problem**

Database crash if bind incorrect number of paramemters to binding slot (I'm using php PDO, not knowing how exactly to do it with raw sql).

In simple case it gave out message like:
```
'SQLSTATE[08P01]: <<Unknown error>>: 7 ERROR:  expected 1 arguments, got 0 (SQL: insert into a (id) values (?))'
```

But for a little more complex it actually bring down database:

```
Jan 15 01:07:21 stormtrooper cockroach[2456254]: * ERROR: [n1,client=127.0.0.1:60676,hostnossl,user=root] a SQL panic has occurred while executing the following statement:
Jan 15 01:07:21 stormtrooper cockroach[2456254]: * INSERT INTO tasks(id, token, prio, endpoint_id, task_id, status, type, biseq_id, biseq_piece_id, endpoint_path, lock_token, retry_reasons, extra, retry_count, cr>
Jan 15 01:07:21 stormtrooper cockroach[2456254]: *
Jan 15 01:07:21 stormtrooper cockroach[2456254]: *
Jan 15 01:07:21 stormtrooper cockroach[2456254]: * ERROR: [n1,client=127.0.0.1:60676,hostnossl,user=root] a panic has occurred!
Jan 15 01:07:21 stormtrooper cockroach[2456254]: * runtime error: index out of range [25] with length 25
Jan 15 01:07:21 stormtrooper cockroach[2456254]: * (1) attached stack trace
Jan 15 01:07:21 stormtrooper cockroach[2456254]: *   -- stack trace:
Jan 15 01:07:21 stormtrooper cockroach[2456254]: *   | github.com/cockroachdb/cockroach/pkg/sql.(*Server).ServeConn.func1
Jan 15 01:07:21 stormtrooper cockroach[2456254]: *   |         /go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:506
Jan 15 01:07:21 stormtrooper cockroach[2456254]: *   | [...repeated from below...]
Jan 15 01:07:21 stormtrooper cockroach[2456254]: * Wraps: (2) while executing: INSERT INTO _(_, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _) SELECT $1::UUID, $2::STRING, $3::INT8, $4::UUID, $5::UUID, $6::STRING, >
Jan 15 01:07:21 stormtrooper cockroach[2456254]: * Wraps: (3) attached stack trace
Jan 15 01:07:21 stormtrooper cockroach[2456254]: *   -- stack trace:
Jan 15 01:07:21 stormtrooper cockroach[2456254]: *   | github.com/cockroachdb/cockroach/pkg/sql.(*Server).ServeConn.func1
Jan 15 01:07:21 stormtrooper cockroach[2456254]: *   |         /go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:506
Jan 15 01:07:21 stormtrooper cockroach[2456254]: *   | runtime.gopanic
Jan 15 01:07:21 stormtrooper cockroach[2456254]: *   |         /usr/local/go/src/runtime/panic.go:679
Jan 15 01:07:21 stormtrooper cockroach[2456254]: *   | runtime.goPanicIndex
Jan 15 01:07:21 stormtrooper cockroach[2456254]: *   |         /usr/local/go/src/runtime/panic.go:75
Jan 15 01:07:21 stormtrooper cockroach[2456254]: *   | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execPrepare
Jan 15 01:07:21 stormtrooper cockroach[2456254]: *   |         /go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_prepare.go:56
Jan 15 01:07:21 stormtrooper cockroach[2456254]: *   | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execCmd
Jan 15 01:07:21 stormtrooper cockroach[2456254]: *   |         /go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:1551
Jan 15 01:07:21 stormtrooper cockroach[2456254]: *   | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).run
Jan 15 01:07:21 stormtrooper cockroach[2456254]: *   |         /go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:1391
Jan 15 01:07:21 stormtrooper cockroach[2456254]: *   | github.com/cockroachdb/cockroach/pkg/sql.(*Server).ServeConn
Jan 15 01:07:21 stormtrooper cockroach[2456254]: *   |         /go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:508
Jan 15 01:07:21 stormtrooper cockroach[2456254]: *   | github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*conn).processCommandsAsync.func1
Jan 15 01:07:21 stormtrooper cockroach[2456254]: *   |         /go/src/github.com/cockroachdb/cockroach/pkg/sql/pgwire/conn.go:626
Jan 15 01:07:21 stormtrooper cockroach[2456254]: *   | runtime.goexit
Jan 15 01:07:21 stormtrooper cockroach[2456254]: *   |         /usr/local/go/src/runtime/asm_amd64.s:1357
Jan 15 01:07:21 stormtrooper cockroach[2456254]: * Wraps: (4) runtime error: index out of range [25] with length 25
Jan 15 01:07:21 stormtrooper cockroach[2456254]: * Error types: (1) *withstack.withStack (2) *safedetails.withSafeDetails (3) *withstack.withStack (4) runtime.boundsError
Jan 15 01:07:21 stormtrooper cockroach[2456254]: *
Jan 15 01:07:21 stormtrooper cockroach[2456254]: *
Jan 15 01:07:21 stormtrooper cockroach[2456254]: * ERROR: [n1,client=127.0.0.1:60676,hostnossl,user=root] Queued as error 16d87805e1c14cab8794d92fbb38815a
Jan 15 01:07:21 stormtrooper cockroach[2456254]: *
Jan 15 01:07:22 stormtrooper systemd[1]: cockroachdb.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
```

I can reproduce this with extra step, but would stack trace above good enough ?

Cockroachdb version:

```CockroachDB CCL v20.2.0 (x86_64-unknown-linux-gnu, built 2020/11/09 16:01:45, go1.13.14)```

### PR DESCRIPTION
**Pull request by otan**
Release note (bug fix): Fix a panic where type hints mismatching
placeholder names cause a crash.

Resolves #59007.

### CODE REVIEW

File: pkg/sql/conn_executor_prepare.go [hunk 1]
```diff
@@ -53,11 +53,20 @@ func (ex *connExecutor) execPrepare(
...
-			if parseCmd.TypeHints[i] == nil && types.IsOIDUserDefinedType(parseCmd.RawTypeHints[i]) {
-				var err error
-				parseCmd.TypeHints[i], err = ex.planner.ResolveTypeByOID(ctx, parseCmd.RawTypeHints[i])
-				if err != nil {
-					return retErr(err)
+			if parseCmd.TypeHints[i] == nil {
+				if i >= len(parseCmd.RawTypeHints) {
+					return retErr(pgerror.Newf(
+						pgcode.ProtocolViolation,
+						"expected type hint at position %d",
```
Comment (rafiss) [inline pkg/sql/conn_executor_prepare.go:60]: maybe we should try to match the error message that happens in the simple case:

https://github.com/cockroachdb/cockroach/blob/32bc171667b6e180fa09669802d45fc9edbe4a52/pkg/sql/conn_executor_prepare.go#L300

**Review by rafiss — CHANGES_REQUESTED** [review]

**Review by rafiss — APPROVED** [review]

**Comment by otan** [comment]
bors r=rafiss
