### PR TITLE
randgen: fix postgres mutator for session vars

### LINKED ISSUE #67791: compose: TestComposeCompare failed
compose.TestComposeCompare [failed](https://teamcity.cockroachdb.com/viewLog.html?buildId=3199215&tab=buildLog) with [artifacts](https://teamcity.cockroachdb.com/viewLog.html?buildId=3199215&tab=artifacts#/) on master @ [5fd1dda1cde0a91643d39209c6458dcefcbfc180](https://github.com/cockroachdb/cockroach/commits/5fd1dda1cde0a91643d39209c6458dcefcbfc180):

```
        test_1        |         compare_test.go:188: SELECT
        test_1        |             	*
        test_1        |             FROM
        test_1        |             	(
        test_1        |             		SELECT
        test_1        |             			tab_319517.col1_4 AS col_496993,
        test_1        |             			tab_319518.col3_13 AS col_496994,
        test_1        |             			NULL AS col_496995,
        test_1        |             			tab_319521.col2_0 AS col_496996,
        test_1        |             			tab_319518.tableoid AS col_496997,
        test_1        |             			ARRAY[14924:::INT8,6093:::INT8,3097:::INT8,(-30703):::INT8] AS col_496998
        test_1        |             		FROM
        test_1        |             			postgres.public.table1@[0] AS tab_319517,
        test_1        |             			postgres.public.table3@table3_col3_4_col3_2_col3_13_col3_8_idx AS tab_319518
        test_1        |             			JOIN postgres.public.table4@table4_col4_6_col4_2_key AS tab_319519
        test_1        |             				JOIN postgres.public.table2@table2_col2_3_col2_2_key AS tab_319520
        test_1        |             					JOIN postgres.public.table2@[0] AS tab_319521 ON (tab_319520.col2_3) = (tab_319521.tableoid)
        test_1        |             					JOIN postgres.public.table3@[0] AS tab_319522 ON (tab_319520.col2_2) = (tab_319522.tableoid) ON
        test_1        |             						(tab_319519.tableoid) = (tab_319520.col2_2)
        test_1        |             						AND (tab_319519.col4_4) = (tab_319520.col2_4)
        test_1        |             						AND (tab_319519.col4_1) = (tab_319522.col3_3)
        test_1        |             				JOIN postgres.public.table2 AS tab_319523
        test_1        |             					JOIN postgres.public.table1 AS tab_319524 ON (tab_319523.col2_3) = (tab_319524.col1_3) ON
        test_1        |             						(tab_319522.col3_12) = (tab_319524.col1_3)
        test_1        |             						AND (tab_319521.col2_3) = (tab_319524.col1_3)
        test_1        |             						AND (tab_319520.col2_3) = (tab_319523.col2_3)
        test_1        |             						AND (tab_319521.col2_2) = (tab_319524.col1_3) ON (tab_319518.col3_13) = (tab_319522.col3_6)
        test_1        |             		ORDER BY
        test_1        |             			tab_319517.crdb_internal_mvcc_timestamp
        test_1        |             	)
        test_1        |             		AS tab_319525
        test_1        |             ORDER BY
        test_1        |             	col_496993 NULLS FIRST,
        test_1        |             	col_496994 NULLS FIRST,
        test_1        |             	col_496995 NULLS FIRST,
        test_1        |             	col_496996 NULLS FIRST,
        test_1        |             	col_496997 NULLS FIRST,
        test_1        |             	col_496998 NULLS FIRST
        test_1        |         compare_test.go:189: cockroach2: ping: context deadline exceeded
        test_1        | FAIL
        compare_test_1 exited with code 1
        Stopping compare_cockroach1_1 ... 
        Stopping compare_postgres_1   ... 
        Stopping compare_cockroach2_1 ... 
        Stopping compare_postgres_1   ... done
        Stopping compare_cockroach1_1 ... done
        Stopping compare_cockroach2_1 ... done
        Aborting on container exit...
        
    compose_test.go:49: exit status 1
```
<details><summary>Reproduce</summary>
<p>
<p>To reproduce, try:

```bash
make stressrace TESTS=TestComposeCompare PKG=./pkg/compose TESTTIMEOUT=5m STRESSFLAGS='-timeout 5m' 2>&1
```
</p>
</p>
</details>
<details><summary>Internal log</summary>
<p>

```
mjibson marked as alumn{us/a}; resolving to rafiss instead
```
</p>
</details>

/cc @cockroachdb/sql-experience rafiss
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*TestComposeCompare.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)
</sub>

Jira issue: CRDB-8721

### PR DESCRIPTION
**Pull request by rafiss**
fixes https://github.com/cockroachdb/cockroach/issues/67791

Release note: None

### CODE REVIEW

File: pkg/sql/randgen/mutator.go [hunk 1]
```diff
@@ -832,6 +833,8 @@ func postgresCreateTableMutator(
 				}
 			}
 			stmt.Defs = newdefs
+		case *tree.SetVar:
+
```
Comment (otan) [inline pkg/sql/randgen/mutator.go:837]: hmm, does this mean we lose out on stuff like `SET intervalstyle = '...'`, and do we (deliberately) want to do that?

**Review by otan — APPROVED** [review]

**Comment by rafiss** [comment]
bors r=otan
