### PR TITLE
concurrency: fix data race in lockTableGuardImpl toResolve mutation

### LINKED ISSUE #164261: logictest: data race in `lockTableGuardImpl`
pkg/sql/logictest/tests/local-legacy-schema-changer/local-legacy-schema-changer_test.TestLogic_sequences_regclass [failed](https://mesolite.cluster.engflow.com/invocations/default/804f1eb1-d48d-4ffb-a567-2ee6561fe51f?testReportRun=3&testReportShard=16&testReportAttempt=1#targets-Ly9wa2cvc3FsL2xvZ2ljdGVzdC90ZXN0cy9sb2NhbC1sZWdhY3ktc2NoZW1hLWNoYW5nZXI6bG9jYWwtbGVnYWN5LXNjaGVtYS1jaGFuZ2VyX3Rlc3Q=) on master @ [943f82fd320a79d23fc71ddb65f0223e10713081](https://github.com/cockroachdb/cockroach/commits/943f82fd320a79d23fc71ddb65f0223e10713081):

```
      pkg/sql/conn_executor.go:2451 +0x375a
  github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).run()
      pkg/sql/conn_executor.go:2359 +0x408
  github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execWithProfiling()
      pkg/sql/conn_executor_exec.go:4651 +0x8d6
  github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execStmt()
      pkg/sql/conn_executor_exec.go:172 +0xbbd
  github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execCmd.func1()
      pkg/sql/conn_executor.go:2446 +0x3ad3
  github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execCmd()
      pkg/sql/conn_executor.go:2451 +0x375a
  github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).run()
      pkg/sql/conn_executor.go:2359 +0x408
  github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execWithProfiling()
      pkg/sql/conn_executor_exec.go:4651 +0x8d6
  github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execStmt()
      pkg/sql/conn_executor_exec.go:172 +0xbbd
  github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execCmd.func1()
      pkg/sql/conn_executor.go:2446 +0x3ad3
  github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execCmd()
      pkg/sql/conn_executor.go:2451 +0x375a
  github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).run()
      pkg/sql/conn_executor.go:2359 +0x408
  github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execWithProfiling()
      pkg/sql/conn_executor_exec.go:4651 +0x8d6
  github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execStmt()
      pkg/sql/conn_executor_exec.go:172 +0xbbd
  github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execCmd.func1()
      pkg/sql/conn_executor.go:2446 +0x3ad3
  github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execCmd()
      pkg/sql/conn_executor.go:2451 +0x375a
  github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).run()
      pkg/sql/conn_executor.go:2359 +0x408
  github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execWithProfiling()
      pkg/sql/conn_executor_exec.go:4651 +0x8d6
  github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execStmt()
      pkg/sql/conn_executor_exec.go:172 +0xbbd
  github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execCmd.func1()
      pkg/sql/conn_executor.go:2446 +0x3ad3
  github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execCmd()
      pkg/sql/conn_executor.go:2451 +0x375a
  github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).run()
      pkg/sql/conn_executor.go:2359 +0x408
  github.com/cockroachdb/cockroach/pkg/sql.(*Server).ServeConn()
      pkg/sql/conn_executor.go:1100 +0x204
  github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*conn).processCommands()
      pkg/sql/pgwire/conn.go:253 +0x727
  github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*Server).serveImpl.func4()
      pkg/sql/pgwire/server.go:1260 +0x210
==================
```

Parameters:
 - <code>attempt=1</code>
 - <code>race=true</code>
 - <code>run=3</code>
 - <code>shard=16</code>
<details><summary>Help</summary>
<p>

See also: [How To Investigate a Go Test Failure \(internal\)](https://cockroachlabs.atlassian.net/l/c/HgfXfJgM)
</p>
</details>
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*TestLogic_sequences_regclass.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/bazci/githubpost/issues)

</sub>

Jira issue: CRDB-60721

### PR DESCRIPTION
**Pull request by stevendanna**
maybeWakeReadersForPushedTxn (introduced in 177e7c96) calls recomputeWaitQueues → conflictsWithHeldLock on guards owned by other requests, mutating their toResolve/toResolveUnreplicated fields without synchronization. The guard's own request may concurrently be in takeToResolveUnreplicated, writing nil to the same field.

Here, we fix this by removing maybeWakeReadersForPushedTxn entirely and instead having each guard handle its own pushed-txn resolution in pushLockTxn. After a successful push, if the guard uses virtual intent resolution, pushLockTxn calls AddReplicatedToResolveAndSignal to append the lock update and signal the guard to rescan. On rescan the guard finds the pushed txn in its resolvableTxns map and proceeds without waiting.

The conflictsWithHeldLock parameter is renamed from resolveMustBeVirtual to readOnly. When readOnly=true (called from recomputeWaitQueues), the cache-based resolution path is skipped entirely, preventing any cross-goroutine mutation.

Fixes: #164261

Release note: None

### CODE REVIEW

**Review by miraradeva — APPROVED** [review]
I like how clean this turned out! 

To confirm, we see no test data-driven changes throughout because we never merged https://github.com/cockroachdb/cockroach/pull/163571, right?

> @miraradeva reviewed 6 files and all commit messages, and made 2 comments.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/164772#-:-OmtIbK25gjxIpXj8C_l:b-vlt4rh)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on stevendanna).

___
*[`pkg/kv/kvserver/concurrency/lock_table.go` line 1008 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/164772#-OmtHaFO1FRTBPBqMhdt:-OmtHaFO1FRTBPBqMhdu:b-y65wes) ([raw file](https://github.com/cockroachdb/cockroach/blob/32a776dcb9101384516edd735444376b924c5816/pkg/kv/kvserver/concurrency/lock_table.go#L1008)):*
> ```Go
> 	g.mu.Lock()
> 	defer g.mu.Unlock()
> 	g.doneActivelyWaitingAtLock()
> ```

Is this essentially recomputing just our own waiting state instead of previously recomputing it for everyone via `recomputeWaitQueues`?

**Review by stevendanna — COMMENTED** [review]
> @stevendanna made 1 comment.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/164772)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on miraradeva).

___
*[`pkg/kv/kvserver/concurrency/lock_table.go` line 1008 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/164772#-OmtHaFO1FRTBPBqMhdt:-OmtaquhDAYR1e7uVACg:b-g5j4nz) ([raw file](https://github.com/cockroachdb/cockroach/blob/32a776dcb9101384516edd735444376b924c5816/pkg/kv/kvserver/concurrency/lock_table.go#L1008)):*
<details><summary><i>Previously, miraradeva (Mira Radeva) wrote…</i></summary><blockquote>

Is this essentially recomputing just our own waiting state instead of previously recomputing it for everyone via `recomputeWaitQueues`?
</blockquote></details>

Not really, but maybe it should be.  This was just signalling that we were done but leaving us in the waitingReaders map, relying on the fact that we'll eventually Dequeue this request (perhaps after waiting on a few more locks) to finally remove ourselves from waiting readers.  Let me poke at this a bit and see if there is a clean way to remove us from the waiting readers list.

**Review by stevendanna — COMMENTED** [review]
> @stevendanna made 1 comment.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/164772)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on miraradeva).

___
*[`pkg/kv/kvserver/concurrency/lock_table.go` line 1008 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/164772#-OmtHaFO1FRTBPBqMhdt:-OmuF_g4BnoHW-vf5vC1:b-73slm5) ([raw file](https://github.com/cockroachdb/cockroach/blob/32a776dcb9101384516edd735444376b924c5816/pkg/kv/kvserver/concurrency/lock_table.go#L1008)):*
<details><summary><i>Previously, stevendanna (Steven Danna) wrote…</i></summary><blockquote>

Not really, but maybe it should be.  This was just signalling that we were done but leaving us in the waitingReaders map, relying on the fact that we'll eventually Dequeue this request (perhaps after waiting on a few more locks) to finally remove ourselves from waiting readers.  Let me poke at this a bit and see if there is a clean way to remove us from the waiting readers list.
</blockquote></details>

The solution here is a _bit_ more code, but I think ultimately it is nice to definitely remove the waiting reader rather than have it exist in the waiting list longer than we need to.

File: pkg/kv/kvserver/concurrency/lock_table.go [hunk 1]
```diff
@@ -1000,6 +1000,12 @@ func (g *lockTableGuardImpl) doneActivelyWaitingAtLock() {
 	g.notify()
 }
 
+// AddReplicatedToResolveAndSignal implements the lockTableGuard interface.
+func (g *lockTableGuardImpl) AddReplicatedToResolveAndSignal(up roachpb.LockUpdate) {
+	g.lt.removeReaderFromKey(g, up.Span.Key)
```
Comment (miraradeva) [inline pkg/kv/kvserver/concurrency/lock_table.go:1005]: Will this *always* notify our guard? I see `removeReader` always notifies but there are a few early returns in `removeReaderFromKey`. I can't come up with a counter example, but just wanted to make sure the various races with someone else removing the lock or the request being dequeued are ok.

File: pkg/kv/kvserver/concurrency/lock_table.go [hunk 2]
```diff
@@ -5056,41 +5063,38 @@ func (t *lockTableImpl) batchPushedLockResolution() bool {
...
-	for iter.First(); iter.Valid(); iter.Next() {
-		kl := iter.Cur()
-		kl.mu.Lock()
+	iter.FirstOverlap(&keyLocks{key: key})
+	if !iter.Valid() {
+		t.locks.mu.RUnlock()
+		return
+	}
+	kl := iter.Cur()
+	t.locks.mu.RUnlock()
```
Comment (miraradeva) [inline pkg/kv/kvserver/concurrency/lock_table.go]: Is it ok to release `t.locks.mu` here and later acquire `kl.mu`? Can `kl` change in between?

File: pkg/kv/kvserver/concurrency/lock_table.go [hunk 3]
```diff
@@ -5056,41 +5063,38 @@ func (t *lockTableImpl) batchPushedLockResolution() bool {
...
+			kl.removeReader(e)
+			return
 		}
-		kl.recomputeWaitQueues(t.settings)
-		kl.mu.Unlock()
 	}
 }
 
+// PushedTransactionUpdated implements the lockTable interface.
+func (t *lockTableImpl) PushedTransactionUpdated(
```
Comment (miraradeva) [inline pkg/kv/kvserver/concurrency/lock_table.go:5098]: This function is the cause of the race being fixed, but I don't think we have any tests that can catch such a race at the concurrency package level. The randomized lock table test runs under `--race` but it doesn't simulate concurrent pushes. Not sure how easy it is to add (not for this PR anyway).

**Review by miraradeva — APPROVED** [review]

File: pkg/kv/kvserver/concurrency/lock_table.go (hunk 1 above)
Comment (stevendanna) [reply pkg/kv/kvserver/concurrency/lock_table.go:1005]: I believe it is the case that anyone _else_ who removed us from this list would have already sent us a notification.  But...it sure would be nice if that was easier to verify.

File: pkg/kv/kvserver/concurrency/lock_table.go (hunk 2 above)
Comment (stevendanna) [reply pkg/kv/kvserver/concurrency/lock_table.go]: I changed this to just lock for the whole region. This is only called on the VIR path for now. We can revisit if we find lock contention.
