### PR TITLE
backupccl: rewrite temp-table datadriven test to be more deterministic

### LINKED ISSUE #79026: ccl/backupccl: TestDataDriven failed
ccl/backupccl.TestDataDriven [failed](https://teamcity.cockroachdb.com/viewLog.html?buildId=4728159&tab=buildLog) with [artifacts](https://teamcity.cockroachdb.com/viewLog.html?buildId=4728159&tab=artifacts#/) on master @ [dce0a307cd242d8575f59a153026b1af9e6a7936](https://github.com/cockroachdb/cockroach/commits/dce0a307cd242d8575f59a153026b1af9e6a7936):

```
        exec-sql [0 args]
        USE d1
        ----
    datadriven_test.go:220: 
        /home/roach/.cache/bazel/_bazel_roach/c5a4e7d36696d9cd970af2045211a7df/sandbox/processwrapper-sandbox/4046/execroot/cockroach/bazel-out/k8-dbg/bin/pkg/ccl/backupccl/backupccl_test_/backupccl_test.runfiles/cockroach/pkg/ccl/backupccl/testdata/backup-restore/temp-tables:98:
        query-sql [0 args]
        SELECT
          regexp_replace(schema_name, 'pg_temp.*', 'pg_temp') AS name
        FROM [SHOW SCHEMAS] ORDER BY name
        ----
        crdb_internal
        information_schema
        pg_catalog
        pg_extension
        public
    datadriven_test.go:220: 
        /home/roach/.cache/bazel/_bazel_roach/c5a4e7d36696d9cd970af2045211a7df/sandbox/processwrapper-sandbox/4046/execroot/cockroach/bazel-out/k8-dbg/bin/pkg/ccl/backupccl/backupccl_test_/backupccl_test.runfiles/cockroach/pkg/ccl/backupccl/testdata/backup-restore/temp-tables:109:
        query-sql [0 args]
        USE d1;
        SELECT table_name FROM [SHOW TABLES] ORDER BY table_name
        ----
        perm_table
    datadriven_test.go:220: 
        /home/roach/.cache/bazel/_bazel_roach/c5a4e7d36696d9cd970af2045211a7df/sandbox/processwrapper-sandbox/4046/execroot/cockroach/bazel-out/k8-dbg/bin/pkg/ccl/backupccl/backupccl_test_/backupccl_test.runfiles/cockroach/pkg/ccl/backupccl/testdata/backup-restore/temp-tables:115:
        new-server [3 args]
        <no input to command>
        ----
    datadriven_test.go:220: 
        /home/roach/.cache/bazel/_bazel_roach/c5a4e7d36696d9cd970af2045211a7df/sandbox/processwrapper-sandbox/4046/execroot/cockroach/bazel-out/k8-dbg/bin/pkg/ccl/backupccl/backupccl_test_/backupccl_test.runfiles/cockroach/pkg/ccl/backupccl/testdata/backup-restore/temp-tables:118:
        exec-sql [0 args]
        USE defaultdb;
        ----
    datadriven_test.go:220: 
        /home/roach/.cache/bazel/_bazel_roach/c5a4e7d36696d9cd970af2045211a7df/sandbox/processwrapper-sandbox/4046/execroot/cockroach/bazel-out/k8-dbg/bin/pkg/ccl/backupccl/backupccl_test_/backupccl_test.runfiles/cockroach/pkg/ccl/backupccl/testdata/backup-restore/temp-tables:122:
        exec-sql [0 args]
        RESTORE FROM LATEST IN 'nodelocal://0/full_cluster_backup/';
        ----
    datadriven_test.go:220: 
        /home/roach/.cache/bazel/_bazel_roach/c5a4e7d36696d9cd970af2045211a7df/sandbox/processwrapper-sandbox/4046/execroot/cockroach/bazel-out/k8-dbg/bin/pkg/ccl/backupccl/backupccl_test_/backupccl_test.runfiles/cockroach/pkg/ccl/backupccl/testdata/backup-restore/temp-tables:127: USE d1;
        SELECT schema_name FROM [SHOW SCHEMAS] ORDER BY schema_name
        output didn't match expected:
        @@ -1,7 +1,6 @@
         crdb_internal
         information_schema
         pg_catalog
         pg_extension
        -pg_temp_0_0
         public
         
    --- FAIL: TestDataDriven/temp-tables (13.10s)
```
<details><summary>Help</summary>
<p>

See also: [How To Investigate a Go Test Failure \(internal\)](https://cockroachlabs.atlassian.net/l/c/HgfXfJgM)
Parameters in this failure:

- TAGS=bazel,gss,deadlock
</p>
</details>
/cc @cockroachdb/bulk-io
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*TestDataDriven.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)
</sub>

Jira issue: CRDB-14502

### PR DESCRIPTION
**Pull request by adityamaru**
Previously, the test would override the temp cleanup frequency and
then sleep for long enough such that the temp cleanup would run. This was
always going to be flaky especially when run under stress, race or deadlock.

This changes the test to instead rely on channels to nudge the reconciliation
loop making it more robust and faster!

Fixes: #79026

Release note: None

### CODE REVIEW

File: pkg/ccl/backupccl/datadriven_test.go [hunk 1]
```diff
@@ -605,6 +634,15 @@ func TestDataDriven(t *testing.T) {
 				ds.clusterTimestamps[timestampTag] = ts
 				return ""
 
+			case "nudge-and-wait-for-temp-cleanup":
+				server := lastCreatedServer
+				if nudgeAndWait, ok := ds.tempObjectCleanupAndWait[server]; !ok {
+					t.Fatalf("server %s was not configured with `control-temp-0object-cleanup`", server)
```
Comment (stevendanna) [inline pkg/ccl/backupccl/datadriven_test.go:640]:
```suggestion
					t.Fatalf("server %s was not configured with `control-temp-object-cleanup`", server)
```

**Review by stevendanna — APPROVED** [review]
LGTM, makes sense to using these existing testing hooks rather than sleeping.  Thanks for taking care of this. 

Just a minor typo.

File: pkg/ccl/backupccl/datadriven_test.go (hunk 1 above)
Comment (adityamaru) [reply pkg/ccl/backupccl/datadriven_test.go]: nice catch, fixed

**Comment by adityamaru** [comment]
bors r=stevendanna
