### PR TITLE
changefeedccl: fix bug with changefeeds on previously backfilled tables

### LINKED ISSUE #34314: changefeeds: error when started on a table with previous schema change backfills
```
> create table foo (a int primary key);
> insert into foo values (0);
> alter table foo add column b int default 7;
> insert into foo values (1, 2);
> create changefeed for foo into <sink>;
```

The changefeed will error with something like "error: detected table ID 52 backfill completed at 1548719620.929314000,0 earlier than highwater timestamp 1548719630.883538000,0". Ironically we get the much more difficult case of keeping the changefeed running through schema changes correct.

Pretty sure this error is just an internal assertion for unexpected conditions that is too broad, but I've got to load this bit of code back up again before I'm sure.

### PR DESCRIPTION
**Pull request by danhhz**
An internal sanity assertion was a bit overeager. It double-check that
if a schema change backfill happened, that we've also done the
changefeed backfill, but it was also triggering on schema change
backfills that happened before the changefeed even started.

Closes #34314

Release note (bug fix): `CHANGEFEED` now can be started on tables that
have previously been backfilled by schema changes.

### CODE REVIEW

**Review by tbg — APPROVED** [review]
> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/34317)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @nvanbenschoten)

**Review by tbg — APPROVED** [review]
PS: this LGTM is based on pattern matching rather than having thoroughly read the surrounding code. Please let me know if you want a thorough review.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/34317#-:-LXOFbIF-x1I_ljq_r_j:bp5fz09)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @nvanbenschoten)

File: pkg/ccl/changefeedccl/poller.go [hunk 1]
```diff
@@ -614,27 +614,30 @@ func (p *poller) validateTable(ctx context.Context, desc *sqlbase.TableDescripto
...
-			// To avoid race conditions with the lease manager, at this point we force
-			// the manager to acquire the freshest descriptor of this table from the
-			// store. In normal operation, the lease manager returns the newest
-			// descriptor it knows about for the timestamp, assuming it's still
-			// allowed; without this explicit load, the lease manager might therefore
-			// return the previous version of the table, which is still technically
-			// allowed by the schema change system.
-			if err := p.leaseMgr.AcquireFreshestFromStore(ctx, desc.ID); err != nil {
-				return err
+			if p.details.StatementTime.Less(boundaryTime) {
```
Comment (nvanbenschoten) [inline pkg/ccl/changefeedccl/poller.go]: Leave a comment on why we need this condition.

**Review by nvb — APPROVED** [review]

**Review by danhhz — COMMENTED** [review]
Thanks for the reviews!

bors r=nvanbenschoten,tbg

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/34317#-:-LXPAv2--YROVwHX6Rk1:b-i49h38)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @nvanbenschoten and @tbg)

___
*[pkg/ccl/changefeedccl/poller.go, line 617 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/34317#-LXMhjwTmlEVtKbOiGFn-r1-617:-LXPAuOcAYftq1m9iero:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/c8e6a0b5639104a8906deaa37a9d67a84e7c64a6/pkg/ccl/changefeedccl/poller.go#L617)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Leave a comment on why we need this condition.
</blockquote></details>

Done.
