### PR TITLE
sql: validate function leakproof volatility at builder level.

### LINKED ISSUE #97427: udf: CREATE FUNCTION with wrong volatility gives weird error
We recently added some verification for function volatility, so if a user attempts to create a function with a more strict level of volatility than is actually guaranteed, the statement returns an error. However, when run from the SQL shell, the error includes a lot of extra and confusing output, which I'm assuming is not expected:
```
root@localhost:26257/defaultdb> CREATE FUNCTION foo(INT) RETURNS INT LEAKPROOF LANGUAGE SQL AS 'SELECT $1*2';
ERROR: error executing StatementPhase stage 1 of 1 with 10 MutationType ops: function "foo" (132): cannot set leakproof on function with non-immutable volatility: VOLATILE
SQLSTATE: 42P13
DETAIL: • Schema change plan for CREATE FUNCTION ‹defaultdb›.‹public›.‹foo›(IN INT8)
│ 	RETURNS INT8
│ 	LEAKPROOF
│ 	LANGUAGE SQL
│ 	AS $$SELECT $1 * ‹2›;$$;
│
├── • StatementPhase
│   │
│   └── • Stage 1 of 1 in StatementPhase
│       │
│       ├── • 8 elements transitioning toward PUBLIC
│       │   │
│       │   ├── • Function:{DescID: 132}
│       │   │     ABSENT → DESCRIPTOR_ADDED
│       │   │
│       │   ├── • ObjectParent:{DescID: 132, ReferencedDescID: 101}
│       │   │   │ ABSENT → PUBLIC
│       │   │   │
│       │   │   ├── • Precedence dependency from DESCRIPTOR_ADDED Function:{DescID: 132}
│       │   │   │     rule: "descriptor existence precedes dependents"
│       │   │   │
│       │   │   └── • Precedence dependency from PUBLIC FunctionName:{DescID: 132}
│       │   │         rule: "function name should be set before parent ids"
│       │   │
│       │   ├── • FunctionName:{DescID: 132}
│       │   │   │ ABSENT → PUBLIC
│       │   │   │
│       │   │   └── • Precedence dependency from DESCRIPTOR_ADDED Function:{DescID: 132}
│       │   │         rule: "descriptor existence precedes dependents"
│       │   │
│       │   ├── • FunctionLeakProof:{DescID: 132}
│       │   │   │ ABSENT → PUBLIC
│       │   │   │
│       │   │   └── • Precedence dependency from DESCRIPTOR_ADDED Function:{DescID: 132}
│       │   │         rule: "descriptor existence precedes dependents"
│       │   │
│       │   ├── • Owner:{DescID: 132}
│       │   │   │ ABSENT → PUBLIC
│       │   │   │
│       │   │   └── • Precedence dependency from DESCRIPTOR_ADDED Function:{DescID: 132}
│       │   │         rule: "descriptor existence precedes dependents"
│       │   │
│       │   ├── • UserPrivileges:{DescID: 132, Name: admin}
│       │   │   │ ABSENT → PUBLIC
│       │   │   │
│       │   │   └── • Precedence dependency from DESCRIPTOR_ADDED Function:{DescID: 132}
│       │   │         rule: "descriptor existence precedes dependents"
│       │   │
│       │   ├── • UserPrivileges:{DescID: 132, Name: root}
│       │   │   │ ABSENT → PUBLIC
│       │   │   │
│       │   │   └── • Precedence dependency from DESCRIPTOR_ADDED Function:{DescID: 132}
│       │   │         rule: "descriptor existence precedes dependents"
│       │   │
│       │   └── • FunctionBody:{DescID: 132}
│       │       │ ABSENT → PUBLIC
│       │       │
│       │       └── • Precedence dependency from DESCRIPTOR_ADDED Function:{DescID: 132}
│       │             rule: "descriptor existence precedes dependents"
│       │
│       └── • 10 Mutation operations
│           │
│           ├── • CreateFunctionDescriptor
│           │     Function:
│           │       FunctionID: 132
│           │       Params:
│           │       - name: ""
│           │         class:
│           │           class: 1
│           │         type:
│           │           type: |
│           │             family: IntFamily
│           │             width: 64
│           │             precision: 0
│           │             locale: ""
│           │             visible_type: 0
│           │             oid: 20
│           │             time_precision_is_set: false
│           │           closedtypeids: []
│           │       ReturnType:
│           │         Type:
│           │           family: IntFamily
│           │           oid: 20
│           │           width: 64
│           │
│           ├── • SetFunctionName
│           │     FunctionID: 132
│           │     Name: foo
│           │
│           ├── • SetFunctionLeakProof
│           │     FunctionID: 132
│           │     LeakProof: true
│           │
│           ├── • UpdateOwner
│           │     Owner:
│           │       DescriptorID: 132
│           │       Owner: root
│           │
│           ├── • UpdateUserPrivileges
│           │     Privileges:
│           │       DescriptorID: 132
│           │       Privileges: 2
│           │       UserName: admin
│           │       WithGrantOption: 2
│           │
│           ├── • UpdateUserPrivileges
│           │     Privileges:
│           │       DescriptorID: 132
│           │       Privileges: 2
│           │       UserName: root
│           │       WithGrantOption: 2
│           │
│           ├── • SetFunctionBody
│           │     Body:
│           │       Body: SELECT $1 * 2;
│           │       FunctionID: 132
│           │       Lang:
│           │         Lang: 1
│           │
│           ├── • UpdateFunctionTypeReferences
│           │     FunctionID: 132
│           │
│           ├── • UpdateFunctionRelationReferences
│           │     FunctionID: 132
│           │
│           └── • SetObjectParentID
│                 ObjParent:
│                   ObjectID: 132
│                   ParentSchemaID: 101
│
└── • PreCommitPhase
    │
    ├── • Stage 1 of 2 in PreCommitPhase
    │   │
    │   ├── • 8 elements transitioning toward PUBLIC
    │   │   │
    │   │   ├── • Function:{DescID: 132}
    │   │   │     DESCRIPTOR_ADDED → ABSENT
    │   │   │
    │   │   ├── • ObjectParent:{DescID: 132, ReferencedDescID: 101}
    │   │   │     PUBLIC → ABSENT
    │   │   │
    │   │   ├── • FunctionName:{DescID: 132}
    │   │   │     PUBLIC → ABSENT
    │   │   │
    │   │   ├── • FunctionLeakProof:{DescID: 132}
    │   │   │     PUBLIC → ABSENT
    │   │   │
    │   │   ├── • Owner:{DescID: 132}
    │   │   │     PUBLIC → ABSENT
    │   │   │
    │   │   ├── • UserPrivileges:{DescID: 132, Name: admin}
    │   │   │     PUBLIC → ABSENT
    │   │   │
    │   │   ├── • UserPrivileges:{DescID: 132, Name: root}
    │   │   │     PUBLIC → ABSENT
    │   │   │
    │   │   └── • FunctionBody:{DescID: 132}
    │   │         PUBLIC → ABSENT
    │   │
    │   └── • 1 Mutation operation
    │       │
    │       └── • UndoAllInTxnImmediateMutationOpSideEffects
    │             {}
    │
    └── • Stage 2 of 2 in PreCommitPhase
        │
        ├── • 8 elements transitioning toward PUBLIC
        │   │
        │   ├── • Function:{DescID: 132}
        │   │   │ ABSENT → PUBLIC
        │   │   │
        │   │   ├── • Precedence dependency from PUBLIC ObjectParent:{DescID: 132, ReferencedDescID: 101}
        │   │   │     rule: "dependents exist before descriptor becomes public"
        │   │   │
        │   │   ├── • Precedence dependency from PUBLIC FunctionName:{DescID: 132}
        │   │   │     rule: "dependents exist before descriptor becomes public"
        │   │   │
        │   │   ├── • Precedence dependency from PUBLIC FunctionLeakProof:{DescID: 132}
        │   │   │     rule: "dependents exist before descriptor becomes public"
        │   │   │
        │   │   ├── • Precedence dependency from PUBLIC Owner:{DescID: 132}
        │   │   │     rule: "dependents exist before descriptor becomes public"
        │   │   │
        │   │   ├── • Precedence dependency from PUBLIC UserPrivileges:{DescID: 132, Name: admin}
        │   │   │     rule: "dependents exist before descriptor becomes public"
        │   │   │
        │   │   ├── • Precedence dependency from PUBLIC UserPrivileges:{DescID: 132, Name: root}
        │   │   │     rule: "dependents exist before descriptor becomes public"
        │   │   │
        │   │   └── • Precedence dependency from PUBLIC FunctionBody:{DescID: 132}
        │   │         rule: "dependents exist before descriptor becomes public"
        │   │
        │   ├── • ObjectParent:{DescID: 132, ReferencedDescID: 101}
        │   │   │ ABSENT → PUBLIC
        │   │   │
        │   │   ├── • Precedence dependency from DESCRIPTOR_ADDED Function:{DescID: 132}
        │   │   │     rule: "descriptor existence precedes dependents"
        │   │   │
        │   │   └── • Precedence dependency from PUBLIC FunctionName:{DescID: 132}
        │   │         rule: "function name should be set before parent ids"
        │   │
        │   ├── • FunctionName:{DescID: 132}
        │   │   │ ABSENT → PUBLIC
        │   │   │
        │   │   └── • Precedence dependency from DESCRIPTOR_ADDED Function:{DescID: 132}
        │   │         rule: "descriptor existence precedes dependents"
        │   │
        │   ├── • FunctionLeakProof:{DescID: 132}
        │   │   │ ABSENT → PUBLIC
        │   │   │
        │   │   └── • Precedence dependency from DESCRIPTOR_ADDED Function:{DescID: 132}
        │   │         rule: "descriptor existence precedes dependents"
        │   │
        │   ├── • Owner:{DescID: 132}
        │   │   │ ABSENT → PUBLIC
        │   │   │
        │   │   └── • Precedence dependency from DESCRIPTOR_ADDED Function:{DescID: 132}
        │   │         rule: "descriptor existence precedes dependents"
        │   │
        │   ├── • UserPrivileges:{DescID: 132, Name: admin}
        │   │   │ ABSENT → PUBLIC
        │   │   │
        │   │   └── • Precedence dependency from DESCRIPTOR_ADDED Function:{DescID: 132}
        │   │         rule: "descriptor existence precedes dependents"
        │   │
        │   ├── • UserPrivileges:{DescID: 132, Name: root}
        │   │   │ ABSENT → PUBLIC
        │   │   │
        │   │   └── • Precedence dependency from DESCRIPTOR_ADDED Function:{DescID: 132}
        │   │         rule: "descriptor existence precedes dependents"
        │   │
        │   └── • FunctionBody:{DescID: 132}
        │       │ ABSENT → PUBLIC
        │       │
        │       └── • Precedence dependency from DESCRIPTOR_ADDED Function:{DescID: 132}
        │             rule: "descriptor existence precedes dependents"
        │
        └── • 11 Mutation operations
            │
            ├── • CreateFunctionDescriptor
            │     Function:
            │       FunctionID: 132
            │       Params:
            │       - name: ""
            │         class:
            │           class: 1
            │         type:
            │           type: |
            │             family: IntFamily
            │             width: 64
            │             precision: 0
            │             locale: ""
            │             visible_type: 0
            │             oid: 20
            │             time_precision_is_set: false
            │           closedtypeids: []
            │       ReturnType:
            │         Type:
            │           family: IntFamily
            │           oid: 20
            │           width: 64
            │
            ├── • SetFunctionName
            │     FunctionID: 132
            │     Name: foo
            │
            ├── • SetFunctionLeakProof
            │     FunctionID: 132
            │     LeakProof: true
            │
            ├── • UpdateOwner
            │     Owner:
            │       DescriptorID: 132
            │       Owner: root
            │
            ├── • UpdateUserPrivileges
            │     Privileges:
            │       DescriptorID: 132
            │       Privileges: 2
            │       UserName: admin
            │       WithGrantOption: 2
            │
            ├── • UpdateUserPrivileges
            │     Privileges:
            │       DescriptorID: 132
            │       Privileges: 2
            │       UserName: root
            │       WithGrantOption: 2
            │
            ├── • SetFunctionBody
            │     Body:
            │       Body: SELECT $1 * 2;
            │       FunctionID: 132
            │       Lang:
            │         Lang: 1
            │
            ├── • UpdateFunctionTypeReferences
            │     FunctionID: 132
            │
            ├── • UpdateFunctionRelationReferences
            │     FunctionID: 132
            │
            ├── • SetObjectParentID
            │     ObjParent:
            │       ObjectID: 132
            │       ParentSchemaID: 101
            │
            └── • MarkDescriptorAsPublic
                  DescriptorID: 132

--
stages graphviz: https://cockroachdb.github.io/scplan/viz.html#H4sIAAAAAAAA/+xa3Y7auhO/Jk8Rob34/6tui53w1e5GYoGt0KFA+dC5WFWVIQbSBjtKTHv2HFXa12ofZ5/kyFkSkhCIIaE9VXO1xjN2PPPzjGd+Wt1Y2MhayvI/UsFZT59+zMy1w7D9wQF8OmZega6gYKIpNq+LAxs36WplsMESOVh2GFpgGch0LkP5i8GWMpDfrhliBiXjewvL1Cq+5suJotxttii9atyM2r1x8f1GonoSEJWUPQmMSiqeRIlKqp5EjUpqnqQcldQ9SSUiUUuepBqVgLuTXfJK1ter1X3xubNEFr4uWtQgrPjcYfcmvi4a5LPhbD4jFQpfY2FRBWCBwTPsHMLZAKMGgBlMbrqdpm9iAJiIJABMRBIAJiIJABORBICJSALAhCXlADARyWFgEpySATQwDM2IIYZXmOxeD7A5RWkfNDAATas9ag47g3F/+KHRarVbnrlwL0hwL0hwL0hwL0hwL0hwL0jKXpAUH6RT3JMBSEoII8c7hB8Ud3NKmGP8ja+L9eLzJ7WrK4amJpZnJnKc6yJdM2wXtStma1dM92aXGOl82plZ0xe+cVcvma5dvXRVXXUtvJf7w99LG2IdzRjWI+uZrjWH7ca4Ld9Oes1xp9+THx++6XiO1ibTp48P3188Pnyz1lPTmG1+zCl9fPj+v05P7vTGtf9LhWF7PBn2Ru5PqdBtN/4YDPv9W6nQbfTeTBpv2vLoXVcqNEbyxcWo3W03x/IFkJ/xD8HHh++vLy52bUk+5pzSDM4AD399jBb7DhBY9dL1tbadkbwpSfMuFKEEJ4Z56AYxZC+wf33Kqa/PM/f+3K7JjF/8I6/PfLOso/v+AArc3cRCNlo5vk54z8/ILIp9zp3ds8tB1c5BXLw17N7CYruLa87RyjDvtwch7DYwE/w6NbZOhKVd+RdDZ0tfo6IetOi0mc2XbMzWtpsDfx9vHI5NUskozvrTj3jGBsg+PlVTd6lApGHCRrMlXqGgbgmksL6acZbpoRU+U6Yh/tZ8EaUprK5lbHUXo08Dm9L5mUw3w/vzwLTXOIUD6lld+i8E20carWNnZhsWo3aS2XS7O89dlLIUJoNSRjZPHGwPbOOzYeIFds5mvBX5BM+Wu1prB9u9YGAgfWXEvPW8DH5jI8L61rYYiGx5tEfBb+HRyL07p0NhxnnphuoxD/BBd079JbwsDhXOuzsJ5y9EFmJlREhz9K6b6VMP/F74yN5v2+It8FN9ToAaz0URUI6nogioxDNRBFTjiSgCavE8FAH1eBqKwFI8C0UgiCehJG6fVCDlSy1gEqPyptf2nKIjZ4l1dw2pcN2ymG6V61bEdGtctyqmW+e6NTFdUOLKdUFlcKkF3JigDLkyEFNWlEuNqErqEL9778yo9aJvHRnZJT+unrkbNG2MGPZSRctPo66alLhduK8U1e60DmeKwRHtpK6Fkt0Hdy1mWNSCpnjP2Tyh5xTvssQ1/6tdVqIzhkc2nr++Sw55A0RC8S2yP20DsOEMXPpN8BpvF+4NruOezqdspfJslZ7DzCpbjTALdtgbU5O9059+DPbkAuq8FU/OUttWvCXaip8EA3+Y1fRcYIYw7LT64m9Fkl97R7T4Ar7jhYqant85g+/ChEF2DuweTRQIuJHXcGp6oigrN04sHTG8ZR4EckCIR0ibTGM3TSInTnI8L4jV9FxVto6PadaTEYh299nBELNzjNZEkCb585Su/iRseQOjpqfhcmx3sY0nbH4YtCpvN8vp2cYzPDs+H5SM6k2QBxLXTGKMhB8yYcaom4oxEq/RnyLEOz/vT4Z4jm1MZsKRkmj83sPAg4cZYhM9/T3/gRKvP1QuNaIo7pD3EIrqDnkdq5TdIS/LlIo75KWFUnWH/LFTau6Q50al7qZJHktqyR0CPkxPOWeWMYlOG6bZIeO/SGe1wrqBGPb+y6RvjQwdt+dzPGOJYJzgZMA9C3MuKalLy7mkX484ybmkjAoRwHMuzCmcn0zhAP7ewZzCOcl3vECAOYWTksIBvLiCOYXzwykcwEtZmFM452jzfzaFA3lvAnMK5xzY/mQKB/JeU8kpnJzC+R0pHOmr9G8AAAD//02rt53oNwAA
--
dependencies graphviz: https://cockroachdb.github.io/scplan/viz.html#H4sIAAAAAAAA/+xY227iRhi+xk9hWbloV9tdbAiHLiARICtUCiwH9SJaRWPPT/Cu8Vgzw6ZpFSmvtXmcPEllG9uY4wCTimp7hfhPnv84/3zYvqPIm6rq30qGzc3wj+XMGQd6y3SfvIGeC+gZB5ngVDXGEYcZuJxpH3yym7+ZEJcz+y+oamXtbShWqXBkOqBaDmKsqpE5B6rVKpzWKhxH1Ckg7JOZ5ZnvhpHdynuOa5X3gWggXkvbCv7EtmoDwMjigFf0Oa41Bq36qKVej7uNUbvXVV+evmOYoLnDsfny9Pzu5em7Nzcd21r8mRDy8vT8U7urtruj0s9KZtAajQfdYfBXyXRa9d/6g17vWsl06t2P4/rHljr81FEy9aF6cTFsdVqNkXqhq2/8DxkvT88fLi7Wfdl/zAkhEs5g7P76CN1tO8CS1vsg1rWEokQkpfaWTZEHVc0lLmifg1JQMpnHjRVkpCqII3oHcflcnlw+b4L6uZ67FreJe2D5TBZqbRzHQ88Z60Y8RNGMxTJpm9+Qo4l9LqBusbJTtL0zL5EOf/BAzLq45ATNbOchOYjLr5coy18ndhJEI7vOv7cxn8YShfxOj46jLL5Egc+pO/qhorG7N92CpD7rmV/A4n1EDx/VJFAV6DRw+dCawgwty2b1E7wvSp4yXTSDV5o0bmzaVyLkBK9Lkr3uAPrap4RMXsl1J23fb0w6hxMCUJZV9Pcu0AOdxsAsanuc0H1uk8S6P7sI4Se4rGcl+TxmQPvU/mY7cAfs1Zz3Vj7hT8t1qTkD2l1uDIRn9oa7/t7m048UubznJcvAismDI6r/EBFdqbvXDKgheS5dEbzhAt4ZTjNW8dfi1OK8bkl4fiH3TmyNSEkOP3VkXvWLNXyxbWPwwlXb1fM3C1r21/rVsNUdhQqufpkwmq1hY9Duj3qD23qz2WpGIrlEpD++6rQbEaMQMfQVo8WEkdYoRwxjRaOUMFIaRjZi5NIahp4w0hrxcfMrGkbCSGvEMbhc0cgnjLRG7HlhRaOYMNIasYPFFY1ywkjHKv9LzU/Pqe1y85lZxHvX8w7skmxco28CAw0KiEPUds14JAViyl5z6TeaqHS7ubvr+gc8zXAtNThuA13gIOpBQ/z91jji/Sb+YhGXPNcXy95gDA58xP33Q3Lw9I/mtz8lcmczJX5H9GsyG+qsH6Bsgh2WKG7t++NjVLyxiENoVaOAoxBpyWalwp824+BaoHoULMDAVAweuDjAO5ctlWRZMnRplgxplvLSLEmLuFGWYakQVsG5dMoQ+DKesqj4/U3SM78sIzAC4mBxgXs0AV6aosDLcd1YDCfWxoxGOQszqpowIRTUpUybYJEZMDVE7+O1MmzLM0rtGlgkviHty1X3AJBIJB8l+fkobR240XNKddEMVDYlcwerJqgMYushCKjamMVvgHBWnmF606iYvBx3DkbDBDJt6NIzbeTCy+dcUjP2MOKQQHYC4zQFwJ26nmw0ug/VOy6ZhvxkLu7/80rmBuRsf1ZXoTZ5qd1geYPUWBCz/OMYiO24esnLr5dCuOX9Xy/y62UzIvsvlov8Lc0ohav8uZTL0jUeg8j7K+VqGTwWl9wHMwsvBsIwc+ckmHk7NKNv7Lro/KMHDwYwAeq/xkS7b6/zWw9j7DzMABwU/r7+gQRaqiy7pZTMo5JRMm6ASsRYNSfqAkh+y/iDA1UNIzYFHOi4wSu4ICYbzICymGzQ3FkxWT8QCUy/W1YPlv9LQWF/wzUEvdP9DSrB5XcKK4/KPwEAAP//nnLtEkEnAAA=
```

### PR DESCRIPTION
**Pull request by chengxiong-ruan**
Fixes: #97427

Previously, in declarative schema, we count on descriptor self validation to error out on invalid function volatility with leakproof flag as true. This is bad because descriptor validation panics at execution time which error out with a whole big print of the plan. This commit add such validation in the builder level to avoid such user unreadable error.

Release note: None

### CODE REVIEW

**Review by ajwerner — COMMENTED** [review]
> Reviewed 1 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/97778)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @chengxiong-ruan)

___
*[`pkg/sql/schemachanger/scbuild/internal/scbuildstmt/create_function.go` line 200 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/97778#-NPLDJ9hEr4HBmcpKLEs:-NPLDJ9hEr4HBmcpKLEt:b6i0xat) ([raw file](https://github.com/cockroachdb/cockroach/blob/61392fab5fc13cc30f0b2986139f31148ff5bca0/pkg/sql/schemachanger/scbuild/internal/scbuildstmt/create_function.go#L200)):*
> ```Go
> 			pgerror.Newf(
> 				pgcode.InvalidFunctionDefinition,
> 				"cannot set leakproof on function with non-immutable volatility: %s",
> ```

make an error in `sqlerrors`, also, please add the same logical validation during the execution of the legacy schema changer, if you can, and make the error in validation not have a pgcode. Pgcodes in validation errors are an anti-pattern. 



_Code quote:_
```Go
cannot set leakproof on function
```
___
*[`pkg/sql/logictest/testdata/logic_test/udf` line 25 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/97778#-NPLDCIH9tf1H3Wk0FwE:-NPLDCIH9tf1H3Wk0FwF:b-rj7qbo) ([raw file](https://github.com/cockroachdb/cockroach/blob/61392fab5fc13cc30f0b2986139f31148ff5bca0/pkg/sql/logictest/testdata/logic_test/udf#L25)):*
> ```
> $$ LANGUAGE made_up_language
> 
> statement error pq: cannot set leakproof on function with non-immutable volatility: STABLE
> ```

can you assert the pg code?

**Review by chengxiong-ruan — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/97778)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner)

___
*[`pkg/sql/schemachanger/scbuild/internal/scbuildstmt/create_function.go` line 200 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/97778#-NPLDJ9hEr4HBmcpKLEs:-NPLLz0jDvMtt90XZ0IP:bpfrwdt) ([raw file](https://github.com/cockroachdb/cockroach/blob/61392fab5fc13cc30f0b2986139f31148ff5bca0/pkg/sql/schemachanger/scbuild/internal/scbuildstmt/create_function.go#L200)):*
In legacy schema changer just conveniently do the validation on the descriptor (not in descriptor validation). But yeah, I'll change it so the logical would look similar.

> Pgcodes in validation errors are an anti-pattern.

TIL.. Thanks for pointing that out.
___
*[`pkg/sql/logictest/testdata/logic_test/udf` line 25 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/97778#-NPLDCIH9tf1H3Wk0FwE:-NPLMJd30Nu9JZKmXSfZ:bjq966u) ([raw file](https://github.com/cockroachdb/cockroach/blob/61392fab5fc13cc30f0b2986139f31148ff5bca0/pkg/sql/logictest/testdata/logic_test/udf#L25)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

can you assert the pg code?
</blockquote></details>

Won't need to assert pg code since I'll remove pgcode from the error.

**Comment by chengxiong-ruan** [comment]
> I was saying that this should have a pgcode, and it should not come from validation code.

Sorry I misunderstood. I think I addressed your comments.

File: pkg/sql/catalog/catpb/function.go [hunk 1]
```diff
@@ -0,0 +1,14 @@
...
+// included in the file licenses/BSL.txt.
+//
+// As of the Change Date specified in that file, in accordance with
+// the Business Source License, use of this software will be governed
+// by the Apache License, Version 2.0, included in the file
+// licenses/APL.txt.
+
+package catpb
+
+const DefaultFunctionVolatility = Function_VOLATILE
```
Comment (ajwerner) [inline pkg/sql/catalog/catpb/function.go:13]: nit: comments

File: pkg/sql/catalog/funcdesc/func_desc.go [hunk 2]
```diff
@@ -836,14 +836,36 @@ func IsOIDUserDefinedFunc(oid oid.Oid) bool {
...
-			pgcode.InvalidFunctionDefinition,
+func ValidateLeakProofVolatility(
+	options tree.FunctionOptions, curLeakProof bool, curVolatility catpb.Function_Volatility,
+) error {
+	for _, option := range options {
+		switch t := option.(type) {
+		case tree.FunctionVolatility:
+			v, err := VolatilityToProto(t)
+			if err != nil {
+				panic(err)
```
Comment (ajwerner) [inline pkg/sql/catalog/funcdesc/func_desc.go:849]: Why panic?

File: pkg/sql/catalog/funcdesc/func_desc.go [hunk 3]
```diff
@@ -836,14 +836,36 @@ func IsOIDUserDefinedFunc(oid oid.Oid) bool {
...
+			}
+			curVolatility = v
+		case tree.FunctionLeakproof:
+			curLeakProof = bool(t)
+		}
+	}
+
+	if err := mustMatchLeakProofVolatility(curLeakProof, curVolatility); err != nil {
+		return pgerror.Wrap(err, pgcode.InvalidFunctionDefinition, "invalid volatility")
```
Comment (ajwerner) [inline pkg/sql/catalog/funcdesc/func_desc.go:858]: I think my preference would be to have this return an unwrapped error and then wrap the pgcode above.

File: pkg/sql/catalog/funcdesc/func_desc.go [hunk 4]
```diff
@@ -836,14 +836,36 @@ func IsOIDUserDefinedFunc(oid oid.Oid) bool {
...
+
+	return nil
+}
+
+func mustMatchLeakProofVolatility(leakProof bool, vol catpb.Function_Volatility) error {
+	if leakProof && vol != catpb.Function_IMMUTABLE {
+		return errors.Newf(
 			"cannot set leakproof on function with non-immutable volatility: %s",
-			fn.GetVolatility().String(),
+			vol.String(),
```
Comment (ajwerner) [inline pkg/sql/catalog/funcdesc/func_desc.go:868]: Why are we calling the string method?

File: pkg/sql/catalog/catpb/function.go (hunk 1 above)
Comment (chengxiong-ruan) [reply pkg/sql/catalog/catpb/function.go:16]: done.

File: pkg/sql/catalog/funcdesc/func_desc.go (hunk 2 above)
Comment (chengxiong-ruan) [reply pkg/sql/catalog/funcdesc/func_desc.go]: huh, forgot to change to it to return error after moving it out of declarative schema changer.
Fixed.

File: pkg/sql/catalog/funcdesc/func_desc.go (hunk 3 above)
Comment (chengxiong-ruan) [reply pkg/sql/catalog/funcdesc/func_desc.go]: Make sense. It is weird returning pg errors from this package.

File: pkg/sql/catalog/funcdesc/func_desc.go (hunk 4 above)
Comment (chengxiong-ruan) [reply pkg/sql/catalog/funcdesc/func_desc.go]: no need indeed, removed.

**Review by ajwerner — COMMENTED** [review]
I've got some more feedback on how I think this could be a bit cleaner. WDYT?

> Reviewed 1 of 5 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/97778#-:-NPP2OHB0tMHt9UK-MvO:bmw36e1)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @chengxiong-ruan)

___
*[`pkg/sql/catalog/funcdesc/func_desc.go` line 849 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/97778#-NPL3h8e66GgAouVVViV-r2-849:-NPOzQ2MCAqM52Cpsq7X:b-6j6ikp) ([raw file](https://github.com/cockroachdb/cockroach/blob/089b7b179dcc5bc440b18ebc00d6651ba76ae718/pkg/sql/catalog/funcdesc/func_desc.go#L849)):*
<details><summary><i>Previously, chengxiong-ruan (Chengxiong Ruan) wrote…</i></summary><blockquote>

huh, forgot to change to it to return error after moving it out of declarative schema changer.
Fixed.
</blockquote></details>

nit: should we wrap this with an assertion failure?
___
*[`pkg/sql/catalog/funcdesc/func_desc.go` line 839 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/97778#-NPP-2Kx5SNyHp8fxQuc:-NPP-2Ky2Y02C9ti689W:bjpv631) ([raw file](https://github.com/cockroachdb/cockroach/blob/4497047ec68b04c9dd1141a6dbc66684ed8551c2/pkg/sql/catalog/funcdesc/func_desc.go#L839)):*
> ```Go
> // ValidateLeakProofVolatility returns an error when a function is defined as
> // leakproof but not immutable. See more details in comments for volatility.V.
> func ValidateLeakProofVolatility(
> ```

the arguments to this function are sort of confusing. Can you say that the arguments are the assumed defaults if the options do not specify? `cur` is not a super obvious prefix to me given this is a top-level function.

To be honest, it feels like what should really be going on here is a function like:

```
package catalog // I'd also be cool with a new package like `funcinfo` in catalog

// VolatilityProperties are properties about the volatility of user-defined functions.
type VolatilityProperties struct {
    LeakProof bool
    Volatility catpb.Function_Volatility
}

// ...
func GetVolatilityPropertiesFromFunctionOptions(
   options tree.FunctionOptions, 
) (VolatilityProperties, error) {
   v := VolatilityProperties{
    LeakProof: catpb.DefaultFunctionLeakProof,
    Volatilit: catpb.DefaultFunctionVolatility,
   }
   
    // ...
}

// ...
func (v VolatilityProperties) Valid() bool {
    return !leakProof || volatility == catpb.Function_IMMUTABLE
}

```

```
package sqlerrors

func NewVolatilityLeakProofMismatchError(...) error
```

Then, in sql, this can be like:

```
volatilityProps, err := catalog.GetVolatilityPropertiesFromFunctionOptions(options)
if err != nil {
    return err
}
if !volatilityProps.Valid() {
   return ..
}
```
___
*[`pkg/sql/catalog/funcdesc/func_desc.go` line 865 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/97778#-NPP0_Yt45mP24xA6WYi:-NPP0_Yt45mP24xA6WYj:b6b14c8) ([raw file](https://github.com/cockroachdb/cockroach/blob/4497047ec68b04c9dd1141a6dbc66684ed8551c2/pkg/sql/catalog/funcdesc/func_desc.go#L865)):*
> ```Go
> 	if leakProof && vol != catpb.Function_IMMUTABLE {
> 		return errors.Newf(
> 			"cannot set leakproof on function with non-immutable volatility: %s",
> ```

I think this is a bad message for the validation error -- nothing is being set.

**Review by chengxiong-ruan — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/97778)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner and @msirek)

___
*[`pkg/sql/catalog/funcdesc/func_desc.go` line 849 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/97778#-NPL3h8e66GgAouVVViV-r2-849:-NPTSqOTB61uvqSfEpLe:b-qu6n94) ([raw file](https://github.com/cockroachdb/cockroach/blob/089b7b179dcc5bc440b18ebc00d6651ba76ae718/pkg/sql/catalog/funcdesc/func_desc.go#L849)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

nit: should we wrap this with an assertion failure?
</blockquote></details>

Good point. Done.
___
*[`pkg/sql/catalog/funcdesc/func_desc.go` line 839 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/97778#-NPP-2Kx5SNyHp8fxQuc:-NPTScS3ESrhbEy3FhfD:b-58xa2a) ([raw file](https://github.com/cockroachdb/cockroach/blob/4497047ec68b04c9dd1141a6dbc66684ed8551c2/pkg/sql/catalog/funcdesc/func_desc.go#L839)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

the arguments to this function are sort of confusing. Can you say that the arguments are the assumed defaults if the options do not specify? `cur` is not a super obvious prefix to me given this is a top-level function.

To be honest, it feels like what should really be going on here is a function like:

```
package catalog // I'd also be cool with a new package like `funcinfo` in catalog

// VolatilityProperties are properties about the volatility of user-defined functions.
type VolatilityProperties struct {
    LeakProof bool
    Volatility catpb.Function_Volatility
}

// ...
func GetVolatilityPropertiesFromFunctionOptions(
   options tree.FunctionOptions, 
) (VolatilityProperties, error) {
   v := VolatilityProperties{
    LeakProof: catpb.DefaultFunctionLeakProof,
    Volatilit: catpb.DefaultFunctionVolatility,
   }
   
    // ...
}

// ...
func (v VolatilityProperties) Valid() bool {
    return !leakProof || volatility == catpb.Function_IMMUTABLE
}

```

```
package sqlerrors

func NewVolatilityLeakProofMismatchError(...) error
```

Then, in sql, this can be like:

```
volatilityProps, err := catalog.GetVolatilityPropertiesFromFunctionOptions(options)
if err != nil {
    return err
}
if !volatilityProps.Valid() {
   return ..
}
```

</blockquote></details>

Thanks for the suggestion. I changed it as mostly like what you proposed.
___
*[`pkg/sql/catalog/funcdesc/func_desc.go` line 865 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/97778#-NPP0_Yt45mP24xA6WYi:-NPTStRZ5TJuzSjypZKM:bk5hd29) ([raw file](https://github.com/cockroachdb/cockroach/blob/4497047ec68b04c9dd1141a6dbc66684ed8551c2/pkg/sql/catalog/funcdesc/func_desc.go#L865)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

I think this is a bad message for the validation error -- nothing is being set.
</blockquote></details>

agree very much, changed it to something more non-action.

File: pkg/sql/catalog/funcdesc/helpers.go [hunk 5]
```diff
@@ -12,74 +12,10 @@ package funcdesc
...
-	"github.com/cockroachdb/cockroach/pkg/sql/catalog/catpb"
-	"github.com/cockroachdb/cockroach/pkg/sql/pgwire/pgcode"
-	"github.com/cockroachdb/cockroach/pkg/sql/pgwire/pgerror"
 	"github.com/cockroachdb/cockroach/pkg/sql/sem/tree"
 	"github.com/cockroachdb/cockroach/pkg/util/errorutil/unimplemented"
 )
 
-// VolatilityToProto converts sql statement input volatility to protobuf
-// type.
-func VolatilityToProto(v tree.FunctionVolatility) (catpb.Function_Volatility, error) {
```
Comment (chengxiong-ruan) [inline pkg/sql/catalog/funcdesc/helpers.go:24]: These are moved to the new `funcinfo` package.

**Review by ajwerner — APPROVED** [review]
LGTM thanks for the cleanup

**Comment by chengxiong-ruan** [comment]
TFTR!
bors r+
