### PR TITLE
server,roachtest: remove leftover usage of `cockroach quit --decommission`

### LINKED ISSUE #49635: roachtest: autoupgrade failed
[(roachtest).autoupgrade failed](https://teamcity.cockroachdb.com/viewLog.html?buildId=1973913&tab=buildLog) on [master@fe74c9b3534ef364f7bf9410bb84ed2034e1624b](https://github.com/cockroachdb/cockroach/commits/fe74c9b3534ef364f7bf9410bb84ed2034e1624b):

```
		  |                                      left empty, the connection flags are used (host, port, user, database,
		  |                                                                                     insecure, certs-dir).
		  |                                                                                     Environment variable: COCKROACH_URL
		  |
		  | Global Flags:
		  |       --logtostderr Severity[=DEFAULT]   logs at or above this threshold go to stderr (default NONE)
		  |       --no-color                         disable standard error log colorization
		  |       --vmodule moduleSpec               comma-separated list of pattern=N settings for file-filtered logging (significantly hurts performance)
		  |
		  | ERROR: unknown flag: --decommission
		  | Failed running "quit"
		  | Error: DEAD_ROACH_PROBLEM: exit status 1
		  | (1) DEAD_ROACH_PROBLEM
		  | Wraps: (2) Node 3. Command with error:
		  |   | ```
		  |   | ./cockroach quit --decommission --insecure --port={pgport:3}
		  |   | ```
		  | Wraps: (3) exit status 1
		  | Error types: (1) errors.Cockroach (2) *hintdetail.withDetail (3) *exec.ExitError
		  |
		  | stdout:
		Wraps: (5) exit status 30
		Error types: (1) *withstack.withStack (2) *safedetails.withSafeDetails (3) *errutil.withMessage (4) *main.withCommandDetails (5) *exec.ExitError

	cluster.go:1512,context.go:135,cluster.go:1501,test_runner.go:825: dead node detection: /home/agent/work/.go/src/github.com/cockroachdb/cockroach/bin/roachprod monitor teamcity-1973913-1590656638-19-n5cpu4 --oneshot --ignore-empty-nodes: exit status 1 2: 4337
		4: dead
		1: 4234
		3: 4539
		5: 4191
		Error: UNCLASSIFIED_PROBLEM: 4: dead
		(1) UNCLASSIFIED_PROBLEM
		Wraps: (2) attached stack trace
		  | main.glob..func13
		  | 	/home/agent/work/.go/src/github.com/cockroachdb/cockroach/pkg/cmd/roachprod/main.go:1129
		  | main.wrap.func1
		  | 	/home/agent/work/.go/src/github.com/cockroachdb/cockroach/pkg/cmd/roachprod/main.go:272
		  | github.com/cockroachdb/cockroach/vendor/github.com/spf13/cobra.(*Command).execute
		  | 	/home/agent/work/.go/src/github.com/cockroachdb/cockroach/vendor/github.com/spf13/cobra/command.go:766
		  | github.com/cockroachdb/cockroach/vendor/github.com/spf13/cobra.(*Command).ExecuteC
		  | 	/home/agent/work/.go/src/github.com/cockroachdb/cockroach/vendor/github.com/spf13/cobra/command.go:852
		  | github.com/cockroachdb/cockroach/vendor/github.com/spf13/cobra.(*Command).Execute
		  | 	/home/agent/work/.go/src/github.com/cockroachdb/cockroach/vendor/github.com/spf13/cobra/command.go:800
		  | main.main
		  | 	/home/agent/work/.go/src/github.com/cockroachdb/cockroach/pkg/cmd/roachprod/main.go:1799
		  | runtime.main
		  | 	/usr/local/go/src/runtime/proc.go:203
		  | runtime.goexit
		  | 	/usr/local/go/src/runtime/asm_amd64.s:1357
		Wraps: (3) 4: dead
		Error types: (1) errors.Unclassified (2) *withstack.withStack (3) *errors.errorString

```

<details><summary>More</summary><p>

Artifacts: [/autoupgrade](https://teamcity.cockroachdb.com/viewLog.html?buildId=1973913&tab=artifacts#/autoupgrade)

[See this test on roachdash](https://roachdash.crdb.dev/?filter=status%3Aopen+t%3A.%2Aautoupgrade.%2A&sort=title&restgroup=false&display=lastcommented+project)
<sub>powered by [pkg/cmd/internal/issues](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)</sub></p></details>

### PR DESCRIPTION
**Pull request by irfansharif**
Fixes #49635. This is fallout from #49350 that wasn't picked up by CI.

Release note: None

### CODE REVIEW

File: pkg/cmd/roachtest/decommission.go [hunk 1]
```diff
@@ -462,20 +462,25 @@ func runDecommissionAcceptance(ctx context.Context, t *test, c *cluster) {
...
 		timeoutCtx, cancel := context.WithTimeout(ctx, 5*time.Minute)
 		defer cancel()
-		if _, err := execCLI(timeoutCtx, t, c, 3, "quit", "--decommission"); err != nil {
-			if timeoutCtx.Err() != nil {
-				t.Fatalf("quit --decommission failed: %s", err)
-			}
-			// TODO(tschottdorf): grep the process output for the string announcing success?
-			t.l.Errorf("WARNING: ignoring error on quit --decommission: %s\n", err)
+		o, err := decommission(timeoutCtx, 3, c.Node(3),
+			"decommission", "--wait", "all", "--format", "csv")
```
Comment (knz) [inline pkg/cmd/roachtest/decommission.go:472]: nit: convention is `--wait=all --format=csv`, with `=` instead of spaces

File: pkg/sql/colexec/hashtable_full.eg.go [hunk 2]
```diff
@@ -0,0 +1,15328 @@
+// Code generated by execgen; DO NOT EDIT.
```
Comment (knz) [inline pkg/sql/colexec/hashtable_full.eg.go:1]: please remove this file from the pr - it does not belong there.

**Review by knz — APPROVED** [review]
LGTM with nits

did you run the roachtest locally to check?

**Review by irfansharif — COMMENTED** [review]
TFTR Raphael! I was holding off on assigning you as a reviewer so to have a TC run before bugging you, but you beat me to it. I did run the test locally.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/49855#-:-M9-6YykB30BOl_kssZK:b-jntfpb)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @knz)

___
*[pkg/cmd/roachtest/decommission.go, line 472 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/49855#-M8wO9F5jL2Iezc4lk2P-r1-472:-M9-20wD65LSzXBX2Y-k:b-hffohn) ([raw file](https://github.com/cockroachdb/cockroach/blob/2d7396e9732f32f878ef85371d5fdcf681dc10ad/pkg/cmd/roachtest/decommission.go#L472)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

nit: convention is `--wait=all --format=csv`, with `=` instead of spaces
</blockquote></details>

Done (I was cargo culting from elsewhere, so fixed it elsewhere as well).
___
*[pkg/sql/colexec/hashtable_full.eg.go, line 1 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/49855#-M8y3RG7Jey7PH0dn28L-r1-1:-M9-0j-hEPdvo_SvASmm:blnl264) ([raw file](https://github.com/cockroachdb/cockroach/blob/2d7396e9732f32f878ef85371d5fdcf681dc10ad/pkg/sql/colexec/hashtable_full.eg.go#L1)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

please remove this file from the pr - it does not belong there.
</blockquote></details>

Looks like my branch was missing #49696, which would've fixed this spurious addition.

**Comment by knz** [comment]
excellent, go ahead

**Comment by irfansharif** [comment]
Weird, I see no test failures yet it's failed overall. Retrying.
image
