### PR TITLE
backup: rewrite UDT oids in histograms when restoring table stats

### LINKED ISSUE #137106: sql: not remapping UDT OIDs in histograms when restoring table statistics
This issue was auto filed by Sentry. It represents a crash or reported error on a live cluster with telemetry enabled.

Sentry Link: [https://cockroach-labs.sentry.io/issues/6127142974/?referrer=webhooks_plugin](https://cockroach-labs.sentry.io/issues/6127142974/?referrer=webhooks_plugin)

Panic Message:

```
types.go:2859: use of enum metadata before hydration as an enum: × ×
(1) attached stack trace
  -- stack trace:
  | github.com/cockroachdb/cockroach/pkg/sql.(*Server).ServeConn.func1
  | 	pkg/sql/conn_executor.go:961
  | runtime.gopanic
  | 	GOROOT/src/runtime/panic.go:770
  | github.com/cockroachdb/cockroach/pkg/sql/colexecerror.CatchVectorizedRuntimeError.func1
  | 	pkg/sql/colexecerror/error.go:137
  | runtime.gopanic
  | 	GOROOT/src/runtime/panic.go:770
  | github.com/cockroachdb/cockroach/pkg/sql/colexecerror.CatchVectorizedRuntimeError.func1
  | 	pkg/sql/colexecerror/error.go:137
  | runtime.gopanic
  | 	GOROOT/src/runtime/panic.go:770
  | github.com/cockroachdb/cockroach/pkg/sql/colexecerror.CatchVectorizedRuntimeError.func1
  | 	pkg/sql/colexecerror/error.go:137
  | runtime.gopanic
  | 	GOROOT/src/runtime/panic.go:770
  | github.com/cockroachdb/cockroach/pkg/sql/types.(*T).ensureHydratedEnum
  | 	pkg/sql/types/types.go:2859
  | github.com/cockroachdb/cockroach/pkg/sql/types.(*T).EnumGetIdxOfPhysical
  | 	pkg/sql/types/types.go:2814
  | github.com/cockroachdb/cockroach/pkg/sql/sem/tree.GetEnumComponentsFromPhysicalRep
  | 	pkg/sql/sem/tree/datum.go:5223
  | github.com/cockroachdb/cockroach/pkg/sql/rowenc/valueside.DecodeUntaggedDatum
  | 	pkg/sql/rowenc/valueside/decode.go:254
  | github.com/cockroachdb/cockroach/pkg/sql/rowenc/valueside.Decode
  | 	pkg/sql/rowenc/valueside/decode.go:41
  | github.com/cockroachdb/cockroach/pkg/sql/stats.DecodeUpperBound
  | 	pkg/sql/stats/histogram.go:135
  | github.com/cockroachdb/cockroach/pkg/sql.(*planner).ShowHistogram.func1
  | 	pkg/sql/show_histogram.go:79
  | github.com/cockroachdb/cockroach/pkg/sql.(*delayedNode).startExec
  | 	pkg/sql/delayed.go:45
  | github.com/cockroachdb/cockroach/pkg/sql.startExec.func2
  | 	pkg/sql/plan.go:525
  | github.com/cockroachdb/cockroach/pkg/sql.(*planVisitor).visitInternal.func1
  | 	pkg/sql/walk.go:107
  | github.com/cockroachdb/cockroach/pkg/sql.(*planVisitor).visitInternal
  | 	pkg/sql/walk.go:294
  | github.com/cockroachdb/cockroach/pkg/sql.(*planVisitor).visit
  | 	pkg/sql/walk.go:74
  | github.com/cockroachdb/cockroach/pkg/sql.walkPlan
  | 	pkg/sql/walk.go:38
  | github.com/cockroachdb/cockroach/pkg/sql.startExec
  | 	pkg/sql/plan.go:528
  | github.com/cockroachdb/cockroach/pkg/sql.(*planNodeToRowSource).Start
  | 	pkg/sql/plan_node_to_row_source.go:166
  | github.com/cockroachdb/cockroach/pkg/sql/colexec.(*Columnarizer).Init
  | 	pkg/sql/colexec/columnarizer.go:178
  | github.com/cockroachdb/cockroach/pkg/sql/colflow.(*batchInfoCollector).init
  | 	pkg/sql/colflow/stats.go:89
  | github.com/cockroachdb/cockroach/pkg/sql/colexecerror.CatchVectorizedRuntimeError
  | 	pkg/sql/colexecerror/error.go:162
  | github.com/cockroachdb/cockroach/pkg/sql/colflow.(*batchInfoCollector).Init
  | 	pkg/sql/colflow/stats.go:98
  | github.com/cockroachdb/cockroach/pkg/sql/colexecop.(*OneInputHelper).Init
  | 	pkg/sql/colexecop/operator.go:313
  | github.com/cockroachdb/cockroach/pkg/sql/colflow.(*batchInfoCollector).init
  | 	pkg/sql/colflow/stats.go:89
  | github.com/cockroachdb/cockroach/pkg/sql/colexecerror.CatchVectorizedRuntimeError
  | 	pkg/sql/colexecerror/error.go:162
  | github.com/cockroachdb/cockroach/pkg/sql/colflow.(*batchInfoCollector).Init
  | 	pkg/sql/colflow/stats.go:98
Wraps: (2) while executing: SELECT count(*) FROM [SHOW HISTOGRAM 1027967971393044485]
Wraps: (3) attached stack trace
  -- stack trace:
  | github.com/cockroachdb/cockroach/pkg/sql.(*Server).ServeConn.func1
  | 	pkg/sql/conn_executor.go:961
  | runtime.gopanic
  | 	GOROOT/src/runtime/panic.go:770
  | github.com/cockroachdb/cockroach/pkg/sql/colexecerror.CatchVectorizedRuntimeError.func1
  | 	pkg/sql/colexecerror/error.go:137
  | runtime.gopanic
  | 	GOROOT/src/runtime/panic.go:770
  | github.com/cockroachdb/cockroach/pkg/sql/colexecerror.CatchVectorizedRuntimeError.func1
  | 	pkg/sql/colexecerror/error.go:137
  | runtime.gopanic
  | 	GOROOT/src/runtime/panic.go:770
  | github.com/cockroachdb/cockroach/pkg/sql/colexecerror.CatchVectorizedRuntimeError.func1
  | 	pkg/sql/colexecerror/error.go:137
  | runtime.gopanic
  | 	GOROOT/src/runtime/panic.go:770
  | github.com/cockroachdb/cockroach/pkg/sql/types.(*T).ensureHydratedEnum
  | 	pkg/sql/types/types.go:2859
  | github.com/cockroachdb/cockroach/pkg/sql/types.(*T).EnumGetIdxOfPhysical
  | 	pkg/sql/types/types.go:2814
  | github.com/cockroachdb/cockroach/pkg/sql/sem/tree.GetEnumComponentsFromPhysicalRep
  | 	pkg/sql/sem/tree/datum.go:5223
  | github.com/cockroachdb/cockroach/pkg/sql/rowenc/valueside.DecodeUntaggedDatum
  | 	pkg/sql/rowenc/valueside/decode.go:254
  | github.com/cockroachdb/cockroach/pkg/sql/rowenc/valueside.Decode
  | 	pkg/sql/rowenc/valueside/decode.go:41
  | github.com/cockroachdb/cockroach/pkg/sql/stats.DecodeUpperBound
  | 	pkg/sql/stats/histogram.go:135
  | github.com/cockroachdb/cockroach/pkg/sql.(*planner).ShowHistogram.func1
  | 	pkg/sql/show_histogram.go:79
  | github.com/cockroachdb/cockroach/pkg/sql.(*delayedNode).startExec
  | 	pkg/sql/delayed.go:45
  | github.com/cockroachdb/cockroach/pkg/sql.startExec.func2
  | 	pkg/sql/plan.go:525
  | github.com/cockroachdb/cockroach/pkg/sql.(*planVisitor).visitInternal.func1
  | 	pkg/sql/walk.go:107
  | github.com/cockroachdb/cockroach/pkg/sql.(*planVisitor).visitInternal
  | 	pkg/sql/walk.go:294
  | github.com/cockroachdb/cockroach/pkg/sql.(*planVisitor).visit
  | 	pkg/sql/walk.go:74
  | github.com/cockroachdb/cockroach/pkg/sql.walkPlan
  | 	pkg/sql/walk.go:38
  | github.com/cockroachdb/cockroach/pkg/sql.startExec
  | 	pkg/sql/plan.go:528
  | github.com/cockroachdb/cockroach/pkg/sql.(*planNodeToRowSource).Start
  | 	pkg/sql/plan_node_to_row_source.go:166
  | github.com/cockroachdb/cockroach/pkg/sql/colexec.(*Columnarizer).Init
  | 	pkg/sql/colexec/columnarizer.go:178
  | github.com/cockroachdb/cockroach/pkg/sql/colflow.(*batchInfoCollector).init
  | 	pkg/sql/colflow/stats.go:89
  | github.com/cockroachdb/cockroach/pkg/sql/colexecerror.CatchVectorizedRuntimeError
  | 	pkg/sql/colexecerror/error.go:162
  | github.com/cockroachdb/cockroach/pkg/sql/colflow.(*batchInfoCollector).Init
  | 	pkg/sql/colflow/stats.go:98
  | github.com/cockroachdb/cockroach/pkg/sql/colexecop.(*OneInputHelper).Init
  | 	pkg/sql/colexecop/operator.go:313
  | github.com/cockroachdb/cockroach/pkg/sql/colflow.(*batchInfoCollector).init
  | 	pkg/sql/colflow/stats.go:89
  | github.com/cockroachdb/cockroach/pkg/sql/colexecerror.CatchVectorizedRuntimeError
  | 	pkg/sql/colexecerror/error.go:162
  | github.com/cockroachdb/cockroach/pkg/sql/colflow.(*batchInfoCollector).Init
  | 	pkg/sql/colflow/stats.go:98
Wraps: (4) assertion failure
Wraps: (5) attached stack trace
  -- stack trace:
  | github.com/cockroachdb/cockroach/pkg/sql/types.(*T).ensureHydratedEnum
  | 	pkg/sql/types/types.go:2859
  | github.com/cockroachdb/cockroach/pkg/sql/types.(*T).EnumGetIdxOfPhysical
  | 	pkg/sql/types/types.go:2814
  | github.com/cockroachdb/cockroach/pkg/sql/sem/tree.GetEnumComponentsFromPhysicalRep
  | 	pkg/sql/sem/tree/datum.go:5223
  | github.com/cockroachdb/cockroach/pkg/sql/rowenc/valueside.DecodeUntaggedDatum
  | 	pkg/sql/rowenc/valueside/decode.go:254
  | github.com/cockroachdb/cockroach/pkg/sql/rowenc/valueside.Decode
  | 	pkg/sql/rowenc/valueside/decode.go:41
  | github.com/cockroachdb/cockroach/pkg/sql/stats.DecodeUpperBound
  | 	pkg/sql/stats/histogram.go:135
  | github.com/cockroachdb/cockroach/pkg/sql.(*planner).ShowHistogram.func1
  | 	pkg/sql/show_histogram.go:79
  | github.com/cockroachdb/cockroach/pkg/sql.(*delayedNode).startExec
  | 	pkg/sql/delayed.go:45
  | github.com/cockroachdb/cockroach/pkg/sql.startExec.func2
  | 	pkg/sql/plan.go:525
  | github.com/cockroachdb/cockroach/pkg/sql.(*planVisitor).visitInternal.func1
  | 	pkg/sql/walk.go:107
  | github.com/cockroachdb/cockroach/pkg/sql.(*planVisitor).visitInternal
  | 	pkg/sql/walk.go:294
  | github.com/cockroachdb/cockroach/pkg/sql.(*planVisitor).visit
  | 	pkg/sql/walk.go:74
  | github.com/cockroachdb/cockroach/pkg/sql.walkPlan
  | 	pkg/sql/walk.go:38
  | github.com/cockroachdb/cockroach/pkg/sql.startExec
  | 	pkg/sql/plan.go:528
  | github.com/cockroa...
```

<details>
<summary>Stacktrace (expand for inline code snippets):</summary>

[pkg/sql/colflow/flow_coordinator.go#L235-L237](pkg/sql/colflow/flow_coordinator.go#L235-L237)
[pkg/sql/colflow/stats.go#L97-L99](pkg/sql/colflow/stats.go#L97-L99)
[pkg/sql/colexecerror/error.go#L161-L163](pkg/sql/colexecerror/error.go#L161-L163)
[pkg/sql/colflow/stats.go#L88-L90](pkg/sql/colflow/stats.go#L88-L90)
[pkg/sql/colexecop/operator.go#L312-L314](pkg/sql/colexecop/operator.go#L312-L314)
[pkg/sql/colflow/stats.go#L97-L99](pkg/sql/colflow/stats.go#L97-L99)
[pkg/sql/colexecerror/error.go#L161-L163](pkg/sql/colexecerror/error.go#L161-L163)
[pkg/sql/colflow/stats.go#L88-L90](pkg/sql/colflow/stats.go#L88-L90)
[pkg/sql/colexec/columnarizer.go#L177-L179](pkg/sql/colexec/columnarizer.go#L177-L179)
[pkg/sql/plan_node_to_row_source.go#L165-L167](pkg/sql/plan_node_to_row_source.go#L165-L167)
[pkg/sql/plan.go#L527-L529](pkg/sql/plan.go#L527-L529)
[pkg/sql/walk.go#L37-L39](pkg/sql/walk.go#L37-L39)
[pkg/sql/walk.go#L73-L75](pkg/sql/walk.go#L73-L75)
[pkg/sql/walk.go#L293-L295](pkg/sql/walk.go#L293-L295)
[pkg/sql/walk.go#L106-L108](pkg/sql/walk.go#L106-L108)
[pkg/sql/plan.go#L524-L526](pkg/sql/plan.go#L524-L526)
[pkg/sql/delayed.go#L44-L46](pkg/sql/delayed.go#L44-L46)
[pkg/sql/show_histogram.go#L78-L80](pkg/sql/show_histogram.go#L78-L80)
[pkg/sql/stats/histogram.go#L134-L136](pkg/sql/stats/histogram.go#L134-L136)
[pkg/sql/rowenc/valueside/decode.go#L40-L42](pkg/sql/rowenc/valueside/decode.go#L40-L42)
[pkg/sql/rowenc/valueside/decode.go#L253-L255](pkg/sql/rowenc/valueside/decode.go#L253-L255)
[pkg/sql/sem/tree/datum.go#L5222-L5224](pkg/sql/sem/tree/datum.go#L5222-L5224)
[pkg/sql/types/types.go#L2813-L2815](pkg/sql/types/types.go#L2813-L2815)
[pkg/sql/types/types.go#L2858-L2860](pkg/sql/types/types.go#L2858-L2860)
[GOROOT/src/runtime/panic.go#L769-L771](GOROOT/src/runtime/panic.go#L769-L771)
[pkg/sql/colexecerror/error.go#L136-L138](pkg/sql/colexecerror/error.go#L136-L138)
[GOROOT/src/runtime/panic.go#L769-L771](GOROOT/src/runtime/panic.go#L769-L771)
[pkg/sql/colexecerror/error.go#L136-L138](pkg/sql/colexecerror/error.go#L136-L138)
[GOROOT/src/runtime/panic.go#L769-L771](GOROOT/src/runtime/panic.go#L769-L771)
[pkg/sql/colexecerror/error.go#L136-L138](pkg/sql/colexecerror/error.go#L136-L138)
[GOROOT/src/runtime/panic.go#L769-L771](GOROOT/src/runtime/panic.go#L769-L771)
[pkg/sql/conn_executor.go#L960-L962](pkg/sql/conn_executor.go#L960-L962)
[pkg/sql/colflow/flow_coordinator.go#L235-L237](pkg/sql/colflow/flow_coordinator.go#L235-L237)
[pkg/sql/colflow/stats.go#L97-L99](pkg/sql/colflow/stats.go#L97-L99)
[pkg/sql/colexecerror/error.go#L161-L163](pkg/sql/colexecerror/error.go#L161-L163)
[pkg/sql/colflow/stats.go#L88-L90](pkg/sql/colflow/stats.go#L88-L90)
[pkg/sql/colexecop/operator.go#L312-L314](pkg/sql/colexecop/operator.go#L312-L314)
[pkg/sql/colflow/stats.go#L97-L99](pkg/sql/colflow/stats.go#L97-L99)
[pkg/sql/colexecerror/error.go#L161-L163](pkg/sql/colexecerror/error.go#L161-L163)
[pkg/sql/colflow/stats.go#L88-L90](pkg/sql/colflow/stats.go#L88-L90)
[pkg/sql/colexec/columnarizer.go#L177-L179](pkg/sql/colexec/columnarizer.go#L177-L179)
[pkg/sql/plan_node_to_row_source.go#L165-L167](pkg/sql/plan_node_to_row_source.go#L165-L167)
[pkg/sql/plan.go#L527-L529](pkg/sql/plan.go#L527-L529)
[pkg/sql/walk.go#L37-L39](pkg/sql/walk.go#L37-L39)
[pkg/sql/walk.go#L73-L75](pkg/sql/walk.go#L73-L75)
[pkg/sql/walk.go#L293-L295](pkg/sql/walk.go#L293-L295)
[pkg/sql/walk.go#L106-L108](pkg/sql/walk.go#L106-L108)
[pkg/sql/plan.go#L524-L526](pkg/sql/plan.go#L524-L526)
[pkg/sql/delayed.go#L44-L46](pkg/sql/delayed.go#L44-L46)
[pkg/sql/show_histogram.go#L78-L80](pkg/sql/show_histogram.go#L78-L80)
[pkg/sql/stats/histogram.go#L134-L136](pkg/sql/stats/histogram.go#L134-L136)
[pkg/sql/rowenc/valueside/decode.go#L40-L42](pkg/sql/rowenc/valueside/decode.go#L40-L42)
[pkg/sql/rowenc/valueside/decode.go#L253-L255](pkg/sql/rowenc/valueside/decode.go#L253-L255)
[pkg/sql/sem/tree/datum.go#L5222-L5224](pkg/sql/sem/tree/datum.go#L5222-L5224)
[pkg/sql/types/types.go#L2813-L2815](pkg/sql/types/types.go#L2813-L2815)
[pkg/sql/types/types.go#L2858-L2860](pkg/sql/types/types.go#L2858-L2860)
[GOROOT/src/runtime/panic.go#L769-L771](GOROOT/src/runtime/panic.go#L769-L771)
[pkg/sql/colexecerror/error.go#L136-L138](pkg/sql/colexecerror/error.go#L136-L138)
[GOROOT/src/runtime/panic.go#L769-L771](GOROOT/src/runtime/panic.go#L769-L771)
[pkg/sql/colexecerror/error.go#L136-L138](pkg/sql/colexecerror/error.go#L136-L138)
[GOROOT/src/runtime/panic.go#L769-L771](GOROOT/src/runtime/panic.go#L769-L771)
[pkg/sql/colexecerror/error.go#L136-L138](pkg/sql/colexecerror/error.go#L136-L138)
[GOROOT/src/runtime/panic.go#L769-L771](GOROOT/src/runtime/panic.go#L769-L771)
[pkg/sql/conn_executor.go#L960-L962](pkg/sql/conn_executor.go#L960-L962)
[pkg/sql/distsql_running.go#L1733-L1735](pkg/sql/distsql_running.go#L1733-L1735)
[pkg/sql/distsql_running.go#L1730-L1732](pkg/sql/distsql_running.go#L1730-L1732)
[pkg/sql/distsql_running.go#L2016-L2018](pkg/sql/distsql_running.go#L2016-L2018)
[pkg/sql/distsql_running.go#L923-L925](pkg/sql/distsql_running.go#L923-L925)
[pkg/sql/colflow/vectorized_flow.go#L314-L316](pkg/sql/colflow/vectorized_flow.go#L314-L316)
[pkg/sql/colflow/flow_coordinator.go#L268-L270](pkg/sql/colflow/flow_coordinator.go#L268-L270)
[pkg/sql/colflow/flow_coordinator.go#L234-L236](pkg/sql/colflow/flow_coordinator.go#L234-L236)
[pkg/sql/colexecerror/error.go#L161-L163](pkg/sql/colexecerror/error.go#L161-L163)
[pkg/sql/colflow/flow_coordinator.go#L235-L237](pkg/sql/colflow/flow_coordinator.go#L235-L237)
[pkg/sql/colflow/stats.go#L97-L99](pkg/sql/colflow/stats.go#L97-L99)
[pkg/sql/colexecerror/error.go#L161-L163](pkg/sql/colexecerror/error.go#L161-L163)
[pkg/sql/colflow/stats.go#L88-L90](pkg/sql/colflow/stats.go#L88-L90)
[pkg/sql/colexecop/operator.go#L312-L314](pkg/sql/colexecop/operator.go#L312-L314)
[pkg/sql/colflow/stats.go#L97-L99](pkg/sql/colflow/stats.go#L97-L99)
[pkg/sql/colexecerror/error.go#L161-L163](pkg/sql/colexecerror/error.go#L161-L163)
[pkg/sql/colflow/stats.go#L88-L90](pkg/sql/colflow/stats.go#L88-L90)
[pkg/sql/colexec/columnarizer.go#L177-L179](pkg/sql/colexec/columnarizer.go#L177-L179)
[pkg/sql/plan_node_to_row_source.go#L165-L167](pkg/sql/plan_node_to_row_source.go#L165-L167)
[pkg/sql/plan.go#L527-L529](pkg/sql/plan.go#L527-L529)
[pkg/sql/walk.go#L37-L39](pkg/sql/walk.go#L37-L39)
[pkg/sql/walk.go#L73-L75](pkg/sql/walk.go#L73-L75)
[pkg/sql/walk.go#L293-L295](pkg/sql/walk.go#L293-L295)
[pkg/sql/walk.go#L106-L108](pkg/sql/walk.go#L106-L108)
[pkg/sql/plan.go#L524-L526](pkg/sql/plan.go#L524-L526)
[pkg/sql/delayed.go#L44-L46](pkg/sql/delayed.go#L44-L46)
[pkg/sql/show_histogram.go#L78-L80](pkg/sql/show_histogram.go#L78-L80)
[pkg/sql/stats/histogram.go#L134-L136](pkg/sql/stats/histogram.go#L134-L136)
[pkg/sql/rowenc/valueside/decode.go#L40-L42](pkg/sql/rowenc/valueside/decode.go#L40-L42)
[pkg/sql/rowenc/valueside/decode.go#L253-L255](pkg/sql/rowenc/valueside/decode.go#L253-L255)
[pkg/sql/sem/tree/datum.go#L5222-L5224](pkg/sql/sem/tree/datum.go#L5222-L5224)
[pkg/sql/types/types.go#L2813-L2815](pkg/sql/types/types.go#L2813-L2815)
[pkg/sql/types/types.go#L2858-L2860](pkg/sql/types/types.go#L2858-L2860)
</details>

```
pkg/sql/colflow/flow_coordinator.go in pkg/sql/colflow.(*BatchFlowCoordinator).Run.(*BatchFlowCoordinator).init.func2 at line 236
pkg/sql/colflow/stats.go in pkg/sql/colflow.(*batchInfoCollector).Init at line 98
pkg/sql/colexecerror/error.go in pkg/sql/colexecerror.CatchVectorizedRuntimeError at line 162
pkg/sql/colflow/stats.go in pkg/sql/colflow.(*batchInfoCollector).init at line 89
pkg/sql/colexecop/operator.go in pkg/sql/colexecop.(*OneInputHelper).Init at line 313
pkg/sql/colflow/stats.go in pkg/sql/colflow.(*batchInfoCollector).Init at line 98
pkg/sql/colexecerror/error.go in pkg/sql/colexecerror.CatchVectorizedRuntimeError at line 162
pkg/sql/colflow/stats.go in pkg/sql/colflow.(*batchInfoCollector).init at line 89
pkg/sql/colexec/columnarizer.go in pkg/sql/colexec.(*Columnarizer).Init at line 178
pkg/sql/plan_node_to_row_source.go in pkg/sql.(*planNodeToRowSource).Start at line 166
pkg/sql/plan.go in pkg/sql.startExec at line 528
pkg/sql/walk.go in pkg/sql.walkPlan at line 38
pkg/sql/walk.go in pkg/sql.(*planVisitor).visit at line 74
pkg/sql/walk.go in pkg/sql.(*planVisitor).visitInternal at line 294
pkg/sql/walk.go in pkg/sql.(*planVisitor).visitInternal.func1 at line 107
pkg/sql/plan.go in pkg/sql.startExec.func2 at line 525
pkg/sql/delayed.go in pkg/sql.(*delayedNode).startExec at line 45
pkg/sql/show_histogram.go in pkg/sql.(*planner).ShowHistogram.func1 at line 79
pkg/sql/stats/histogram.go in pkg/sql/stats.DecodeUpperBound at line 135
pkg/sql/rowenc/valueside/decode.go in pkg/sql/rowenc/valueside.Decode at line 41
pkg/sql/rowenc/valueside/decode.go in pkg/sql/rowenc/valueside.DecodeUntaggedDatum at line 254
pkg/sql/sem/tree/datum.go in pkg/sql/sem/tree.GetEnumComponentsFromPhysicalRep at line 5223
pkg/sql/types/types.go in pkg/sql/types.(*T).EnumGetIdxOfPhysical at line 2814
pkg/sql/types/types.go in pkg/sql/types.(*T).ensureHydratedEnum at line 2859
GOROOT/src/runtime/panic.go in runtime.gopanic at line 770
pkg/sql/colexecerror/error.go in pkg/sql/colexecerror.CatchVectorizedRuntimeError.func1 at line 137
GOROOT/src/runtime/panic.go in runtime.gopanic at line 770
pkg/sql/colexecerror/error.go in pkg/sql/colexecerror.CatchVectorizedRuntimeError.func1 at line 137
GOROOT/src/runtime/panic.go in runtime.gopanic at line 770
pkg/sql/colexecerror/error.go in pkg/sql/colexecerror.CatchVectorizedRuntimeError.func1 at line 137
GOROOT/src/runtime/panic.go in runtime.gopanic at line 770
pkg/sql/conn_executor.go in pkg/sql.(*Server).ServeConn.func1 at line 961
pkg/sql/colflow/flow_coordinator.go in pkg/sql/colflow.(*BatchFlowCoordinator).Run.(*BatchFlowCoordinator).init.func2 at line 236
pkg/sql/colflow/stats.go in pkg/sql/colflow.(*batchInfoCollector).Init at line 98
pkg/sql/colexecerror/error.go in pkg/sql/colexecerror.CatchVectorizedRuntimeError at line 162
pkg/sql/colflow/stats.go in pkg/sql/colflow.(*batchInfoCollector).init at line 89
pkg/sql/colexecop/operator.go in pkg/sql/colexecop.(*OneInputHelper).Init at line 313
pkg/sql/colflow/stats.go in pkg/sql/colflow.(*batchInfoCollector).Init at line 98
pkg/sql/colexecerror/error.go in pkg/sql/colexecerror.CatchVectorizedRuntimeError at line 162
pkg/sql/colflow/stats.go in pkg/sql/colflow.(*batchInfoCollector).init at line 89
pkg/sql/colexec/columnarizer.go in pkg/sql/colexec.(*Columnarizer).Init at line 178
pkg/sql/plan_node_to_row_source.go in pkg/sql.(*planNodeToRowSource).Start at line 166
pkg/sql/plan.go in pkg/sql.startExec at line 528
pkg/sql/walk.go in pkg/sql.walkPlan at line 38
pkg/sql/walk.go in pkg/sql.(*planVisitor).visit at line 74
pkg/sql/walk.go in pkg/sql.(*planVisitor).visitInternal at line 294
pkg/sql/walk.go in pkg/sql.(*planVisitor).visitInternal.func1 at line 107
pkg/sql/plan.go in pkg/sql.startExec.func2 at line 525
pkg/sql/delayed.go in pkg/sql.(*delayedNode).startExec at line 45
pkg/sql/show_histogram.go in pkg/sql.(*planner).ShowHistogram.func1 at line 79
pkg/sql/stats/histogram.go in pkg/sql/stats.DecodeUpperBound at line 135
pkg/sql/rowenc/valueside/decode.go in pkg/sql/rowenc/valueside.Decode at line 41
pkg/sql/rowenc/valueside/decode.go in pkg/sql/rowenc/valueside.DecodeUntaggedDatum at line 254
pkg/sql/sem/tree/datum.go in pkg/sql/sem/tree.GetEnumComponentsFromPhysicalRep at line 5223
pkg/sql/types/types.go in pkg/sql/types.(*T).EnumGetIdxOfPhysical at line 2814
pkg/sql/types/types.go in pkg/sql/types.(*T).ensureHydratedEnum at line 2859
GOROOT/src/runtime/panic.go in runtime.gopanic at line 770
pkg/sql/colexecerror/error.go in pkg/sql/colexecerror.CatchVectorizedRuntimeError.func1 at line 137
GOROOT/src/runtime/panic.go in runtime.gopanic at line 770
pkg/sql/colexecerror/error.go in pkg/sql/colexecerror.CatchVectorizedRuntimeError.func1 at line 137
GOROOT/src/runtime/panic.go in runtime.gopanic at line 770
pkg/sql/colexecerror/error.go in pkg/sql/colexecerror.CatchVectorizedRuntimeError.func1 at line 137
GOROOT/src/runtime/panic.go in runtime.gopanic at line 770
pkg/sql/conn_executor.go in pkg/sql.(*Server).ServeConn.func1 at line 961
pkg/sql/distsql_running.go in pkg/sql.(*DistSQLPlanner).PlanAndRunAll at line 1734
pkg/sql/distsql_running.go in pkg/sql.(*DistSQLPlanner).PlanAndRunAll.func3 at line 1731
pkg/sql/distsql_running.go in pkg/sql.(*DistSQLPlanner).PlanAndRun at line 2017
pkg/sql/distsql_running.go in pkg/sql.(*DistSQLPlanner).Run at line 924
pkg/sql/colflow/vectorized_flow.go in pkg/sql/colflow.(*vectorizedFlow).Run at line 315
pkg/sql/colflow/flow_coordinator.go in pkg/sql/colflow.(*BatchFlowCoordinator).Run at line 269
pkg/sql/colflow/flow_coordinator.go in pkg/sql/colflow.(*BatchFlowCoordinator).init at line 235
pkg/sql/colexecerror/error.go in pkg/sql/colexecerror.CatchVectorizedRuntimeError at line 162
pkg/sql/colflow/flow_coordinator.go in pkg/sql/colflow.(*BatchFlowCoordinator).Run.(*BatchFlowCoordinator).init.func2 at line 236
pkg/sql/colflow/stats.go in pkg/sql/colflow.(*batchInfoCollector).Init at line 98
pkg/sql/colexecerror/error.go in pkg/sql/colexecerror.CatchVectorizedRuntimeError at line 162
pkg/sql/colflow/stats.go in pkg/sql/colflow.(*batchInfoCollector).init at line 89
pkg/sql/colexecop/operator.go in pkg/sql/colexecop.(*OneInputHelper).Init at line 313
pkg/sql/colflow/stats.go in pkg/sql/colflow.(*batchInfoCollector).Init at line 98
pkg/sql/colexecerror/error.go in pkg/sql/colexecerror.CatchVectorizedRuntimeError at line 162
pkg/sql/colflow/stats.go in pkg/sql/colflow.(*batchInfoCollector).init at line 89
pkg/sql/colexec/columnarizer.go in pkg/sql/colexec.(*Columnarizer).Init at line 178
pkg/sql/plan_node_to_row_source.go in pkg/sql.(*planNodeToRowSource).Start at line 166
pkg/sql/plan.go in pkg/sql.startExec at line 528
pkg/sql/walk.go in pkg/sql.walkPlan at line 38
pkg/sql/walk.go in pkg/sql.(*planVisitor).visit at line 74
pkg/sql/walk.go in pkg/sql.(*planVisitor).visitInternal at line 294
pkg/sql/walk.go in pkg/sql.(*planVisitor).visitInternal.func1 at line 107
pkg/sql/plan.go in pkg/sql.startExec.func2 at line 525
pkg/sql/delayed.go in pkg/sql.(*delayedNode).startExec at line 45
pkg/sql/show_histogram.go in pkg/sql.(*planner).ShowHistogram.func1 at line 79
pkg/sql/stats/histogram.go in pkg/sql/stats.DecodeUpperBound at line 135
pkg/sql/rowenc/valueside/decode.go in pkg/sql/rowenc/valueside.Decode at line 41
pkg/sql/rowenc/valueside/decode.go in pkg/sql/rowenc/valueside.DecodeUntaggedDatum at line 254
pkg/sql/sem/tree/datum.go in pkg/sql/sem/tree.GetEnumComponentsFromPhysicalRep at line 5223
pkg/sql/types/types.go in pkg/sql/types.(*T).EnumGetIdxOfPhysical at line 2814
pkg/sql/types/types.go in pkg/sql/types.(*T).ensureHydratedEnum at line 2859
```

### Tags

| Tag | Value |
| --- | --- |
| Command | server |
| Environment | v24.3.1 |
| Go Version | go1.22.8 X:nocoverageredesign |
| Platform | linux amd64 |
| Distribution | CCL |
| Cockroach Release | v24.3.1 |
| Cockroach SHA | 45aad22dcd32df1c3c1b860b078038c493f0011d |
| # of CPUs | 8 |
| # of Goroutines | 806 |

Jira issue: CRDB-45389

### PR DESCRIPTION
**Pull request by michae2**
During restore we need to rewrite any saved references to descriptor IDs and OIDs when restoring table statistics. We were rewriting references to table IDs, but not references to type OIDs for user-defined types.

Fixes: #137106

Release note (bug fix): Fix a bug that caused queries against tables with user-defined types to sometimes fail with errors after restoring those tables.

### CODE REVIEW

**Review by rytaft — APPROVED** [review]
:lgtm: great find!

> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/137242#-:-ODqHNnDBNy3_MqK67E8:b-3952fu)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @jeffswenson and @yuzefovich)

**Comment by michae2** [comment]
Thanks!

bors r=rytaft

File: pkg/backup/restore_job.go [hunk 1]
```diff
@@ -724,8 +724,21 @@ func remapAndFilterRelevantStatistics(
...
-				// Statistics imported only when table re-write is present.
+				// We only restore statistics when all necessary descriptor rewrites are
+				// present in the rewrite map.
 				stat.TableID = tableRewrite.ID
+				// We also need to remap the type OID in the histogram for UDTs.
+				if stat.HistogramData != nil && stat.HistogramData.ColumnType != nil {
+					if typ := stat.HistogramData.ColumnType; typ.UserDefined() {
+						typDescID := typedesc.GetUserDefinedTypeDescID(typ)
+						if _, ok := descriptorRewrites[typDescID]; !ok {
+							continue
```
Comment (mgartner) [inline pkg/backup/restore_job.go:735]: We can still restore statistics if the UDT is not in the rewrite map?

**Review by mgartner — COMMENTED** [review]
Nice job tracking this one down!

File: pkg/backup/restore_job.go (hunk 1 above)
Comment (michae2) [reply pkg/backup/restore_job.go:735]: Maybe I'm misunderstanding your question... the `continue` should prevent the stats from being restored if the UDT is not in the rewrite map. And I think this is what we want, since otherwise we won't know what the UDT OID should be.

**Review by yuzefovich — COMMENTED** [review]
Nice find!

> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/137242#-:-ODrQA_Z0RwPrE-Y-0HM:bdkgtm2)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained

File: pkg/backup/restore_job.go (hunk 1 above)
Comment (mgartner) [reply pkg/backup/restore_job.go:735]: Ahh, I misread the code. It might be time to convert the 5-level nested ifs into some early `continue` ifs instead... 😆
