### PR TITLE
streamingest: fix returned cutover time on `complete to latest`

### LINKED ISSUE #95901: c2c: cutover to latest prints timestamp 0
```
root@localhost:26257/defaultdb> alter tenant dest1 complete replication to latest;
  cutover_time
----------------
         0E-10
(1 row)

Time: 48ms total (execution 48ms / network 0ms)
```
need to print the right time.. oops.

Jira issue: CRDB-23800

Epic CRDB-18752

### PR DESCRIPTION
**Pull request by lidorcarmel**
Currently when cutting over to the LATEST high watermark, the sql command prints that that cutover was done to timestamp 0.

This commit fixes this bug.

Fixes: #95901

Epic: CRDB-18752

Release note: None

### CODE REVIEW

File: pkg/ccl/streamingccl/streamingest/alter_replication_job.go [hunk 1]
```diff
@@ -197,33 +179,44 @@ func alterReplicationJobHook(
...
+				errors.Newf("replicated tenant %q has not yet recorded a safe replication time", tenantName)
 		}
 		cutoverTime = *ts
+	} else {
+		if alterTenantStmt.Cutover.Timestamp == nil {
+			return hlc.Timestamp{}, errors.AssertionFailedf("unexpected nil cutover expression")
+		}
+
+		evalCtx := &p.ExtendedEvalContext().Context
+		ct, err := evalCutoverTime(ctx, evalCtx, p.SemaCtx(), alterTenantStmt.Cutover.Timestamp)
```
Comment (stevendanna) [inline pkg/ccl/streamingccl/streamingest/alter_replication_job.go:215]: We typically try to keep all of these evals outside of the `PlanHookRowFn`. I can't claim to know all the reasons _why_ we need to do that. But perhaps we should keep that pattern here? I know it makes the code a bit uglier.

Alternatively, have I just been cargo-culting this rule around?

Comment (lidorcarmel) [reply pkg/ccl/streamingccl/streamingest/alter_replication_job.go]: definitely not cargo-culting anything, thanks Steven for the helpful chat!
PTAL.

File: pkg/ccl/streamingccl/streamingest/alter_replication_job_test.go [hunk 2]
```diff
@@ -26,6 +26,66 @@ import (
...
+	c.WaitUntilHighWatermark(highWater, jobspb.JobID(ingestionJobID))
+
+	var cutoverStr string
+	testutils.SucceedsSoon(t, func() error {
+		err := c.DestSysSQL.DB.QueryRowContext(ctx, `ALTER TENANT $1 COMPLETE REPLICATION TO LATEST`,
+			args.DestTenantName).Scan(&cutoverStr)
+		if err == nil {
+			return nil
+		}
+		require.ErrorContains(t, err, "is before earliest safe cutover time")
```
Comment (stevendanna) [inline pkg/ccl/streamingccl/streamingest/alter_replication_job_test.go:80]: It's interesting that you can get this error despite waiting for the high water mark.  Do you still hit this error if you wait for a high watermark based on the DstCluster's clock rather than the source cluster's clock?

File: pkg/ccl/streamingccl/streamingest/alter_replication_job_test.go [hunk 3]
```diff
@@ -26,6 +26,66 @@ import (
 	"github.com/stretchr/testify/require"
 )
 
+func TestAlterTenantCompleteToTime(t *testing.T) {
```
Comment (stevendanna) [inline pkg/ccl/streamingccl/streamingest/alter_replication_job_test.go:29]: I do wonder if these tests could be data-driven tests.  But they are already written, so I leave that to your judgement.

**Review by stevendanna — APPROVED** [review]
This looks fine to me.  One small question about the test, but I trust you to resolve it as you see fit.

File: pkg/ccl/streamingccl/streamingest/alter_replication_job_test.go (hunk 3 above)
Comment (lidorcarmel) [reply pkg/ccl/streamingccl/streamingest/alter_replication_job_test.go:29]: good question.. I think I like the data driven tests for running through a user story such as setting up clusters and writing some things and doing a cutover etc., but here these 2 tests are the minimum code needed to verify one small thing which I think is useful. we can also do that with data driven but isn't it a bit harder to debug data driven tests? anyway, my point is that we need both but I see golang tests as better for unit tests and data driven better for longer story tests.
that said, I'll definitely try to remind myself to use data driven more..

**Review by lidorcarmel — COMMENTED** [review]
thanks! done.

**Comment by lidorcarmel** [comment]
merging, but if you think I should change anything I can do that in a followup, TFTR!
bors r+
