### PR TITLE
roachtest: increase passing criteria for elasticWorkload test

### LINKED ISSUE #133557: roachtest: perturbation/full/elasticWorkload failed
roachtest.perturbation/full/elasticWorkload [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/17470768?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/17470768?buildTab=artifacts#/perturbation/full/elasticWorkload) on master @ [1b5c41939197efb0fa50ded9795e2e83f5c1dd34](https://github.com/cockroachdb/cockroach/commits/1b5c41939197efb0fa50ded9795e2e83f5c1dd34):

```
(assertions.go:363).Fail: 
	Error Trace:	github.com/cockroachdb/cockroach/pkg/cmd/roachtest/tests/admission_control_latency.go:903
	            				main/pkg/cmd/roachtest/test_runner.go:1287
	            				src/runtime/asm_amd64.s:1695
	Error:      	Should be true
	Test:       	perturbation/full/elasticWorkload
	Messages:   	FAILURE: follower-read  : Increase 5.4454 > 5.0000 BASE: 5.876161ms SCORE: 31.998262ms
	            	
	            	FAILURE: read           : Increase 5.6014 > 5.0000 BASE: 5.951536ms SCORE: 33.336737ms
(require.go:1950).True: FailNow called
test artifacts and logs in: /artifacts/perturbation/full/elasticWorkload/run_1
```

Parameters:
 - <code>ROACHTEST_arch=amd64</code>
 - <code>ROACHTEST_cloud=gce</code>
 - <code>ROACHTEST_coverageBuild=false</code>
 - <code>ROACHTEST_cpu=16</code>
 - <code>ROACHTEST_encrypted=false</code>
 - <code>ROACHTEST_fs=ext4</code>
 - <code>ROACHTEST_localSSD=true</code>
 - <code>ROACHTEST_runtimeAssertionsBuild=false</code>
 - <code>ROACHTEST_ssd=2</code>
<details><summary>Help</summary>
<p>

See: [roachtest README](https://github.com/cockroachdb/cockroach/blob/master/pkg/cmd/roachtest/README.md)

See: [How To Investigate \(internal\)](https://cockroachlabs.atlassian.net/l/c/SSSBr8c7)

See: [Grafana](https://go.crdb.dev/roachtest-grafana/teamcity-17470768/perturbation-full-elasticworkload/1730120682297/1730123010303)

</p>
</details>
/cc @cockroachdb/kv-triage
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*perturbation/full/elasticWorkload.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/bazci/githubpost/issues)

</sub>

### LINKED ISSUE #134104: roachtest: perturbation/full/elasticWorkload failed
roachtest.perturbation/full/elasticWorkload [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/17542292?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/17542292?buildTab=artifacts#/perturbation/full/elasticWorkload) on release-24.3 @ [c077ebf6e98bcd579481b93c83f14184ab94f2e6](https://github.com/cockroachdb/cockroach/commits/c077ebf6e98bcd579481b93c83f14184ab94f2e6):

```
(assertions.go:363).Fail: 
	Error Trace:	pkg/cmd/roachtest/tests/admission_control_latency.go:903
	            				pkg/cmd/roachtest/test_runner.go:1287
	            				src/runtime/asm_amd64.s:1695
	Error:      	Should be true
	Test:       	perturbation/full/elasticWorkload
	Messages:   	FAILURE: write          : Increase 12.1196 > 5.0000 BASE: 10.968345ms SCORE: 132.931887ms
(require.go:1950).True: FailNow called
test artifacts and logs in: /artifacts/perturbation/full/elasticWorkload/run_1
```

Parameters:
 - <code>ROACHTEST_arch=amd64</code>
 - <code>ROACHTEST_cloud=gce</code>
 - <code>ROACHTEST_coverageBuild=false</code>
 - <code>ROACHTEST_cpu=16</code>
 - <code>ROACHTEST_encrypted=false</code>
 - <code>ROACHTEST_fs=ext4</code>
 - <code>ROACHTEST_localSSD=true</code>
 - <code>ROACHTEST_runtimeAssertionsBuild=false</code>
 - <code>ROACHTEST_ssd=2</code>
<details><summary>Help</summary>
<p>

See: [roachtest README](https://github.com/cockroachdb/cockroach/blob/master/pkg/cmd/roachtest/README.md)

See: [How To Investigate \(internal\)](https://cockroachlabs.atlassian.net/l/c/SSSBr8c7)

See: [Grafana](https://go.crdb.dev/roachtest-grafana/teamcity-17542292/perturbation-full-elasticworkload/1730490247720/1730493092092)

</p>
</details>
<details><summary>Same failure on other branches</summary>
<p>

- #133557 roachtest: perturbation/full/elasticWorkload failed [C-test-failure O-roachtest O-robot T-kv branch-master]
</p>
</details>
/cc @cockroachdb/kv-triage
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*perturbation/full/elasticWorkload.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/bazci/githubpost/issues)

</sub>

Jira issue: CRDB-43916

### PR DESCRIPTION
**Pull request by andrewbaptist**
Change the passing criteria for the perturbation/*/elasticWorkload tests from 5.0 to 20.0. We have seen a number of failures where the value is in the 6-12 range and by increasing this we will prevent many of the flakes. Ideally we will drop this number in the future.

Fixes: https://github.com/cockroachdb/cockroach/issues/133557
Fixes: https://github.com/cockroachdb/cockroach/issues/134104

Release note: None

### CODE REVIEW

File: pkg/cmd/roachtest/tests/admission_control_latency.go [hunk 1]
```diff
@@ -219,7 +219,7 @@ func registerLatencyTests(r registry.Registry) {
 	addFull(r, decommission{drain: true}, 5.0)
 	addFull(r, backfill{}, 40.0)
 	addFull(r, &slowDisk{slowLiveness: true, walFailover: true}, math.Inf(1))
-	addFull(r, elasticWorkload{}, 5.0)
+	addFull(r, elasticWorkload{}, 20.0)
```
Comment (pav-kv) [inline pkg/cmd/roachtest/tests/admission_control_latency.go:222]: What about other tests, e.g. `addNode` / `decommission`? Are they less susceptible to this flakiness?

**Review by pav-kv — APPROVED** [review]

File: pkg/cmd/roachtest/tests/admission_control_latency.go (hunk 1 above)
Comment (andrewbaptist) [reply pkg/cmd/roachtest/tests/admission_control_latency.go:222]: Those tests are much more reliable at 5.0 (see https://roachperf.crdb.dev/?filter=perturbation&view=perturbation&tab=gce for some examples). Decommission is slightly above addNode, but they are both typically well below the 5.0 increase. The elastic workload is typically 3-4x above and often can get above 5x.

**Comment by andrewbaptist** [comment]
TFTR!

bors r=pav-kv
