### PR TITLE
rpc: Fix blackhole recv

### LINKED ISSUE #99104: kvserver: RPC dialback does not resolve `failover/non-system/blackhole-recv`
In #94778, we added RPC dialback to resolve asymmetric network partitions. This fixed the [`failover/non-system/blackhole-send`](https://roachperf.crdb.dev/?filter=&view=failover%2Fnon-system%2Fblackhole-send&tab=gce) roachtest, but the [`failover/non-system/blackhole-recv`](https://roachperf.crdb.dev/?filter=&view=failover%2Fnon-system%2Fblackhole-recv&tab=gce) test still shows persistent unavailability. We need to find out why and fix it.

Jira issue: CRDB-25705

### PR DESCRIPTION
**Pull request by andrewbaptist**
Fixes: #99104
Informs #84289

As part of the previous fix for partition handling, we tracked the state of a previous attempt and use that result on the next attempt. However if there were multiple connections, we may only block system traffic connections and not default class connections.  This change addresses that by ensuring a failed dialback attempt is remembered until we are able to successfully connect back to the pinging node.

Epic: none
Release note: None

### CODE REVIEW

File: pkg/rpc/context.go [hunk 1]
```diff
@@ -2623,71 +2624,86 @@ func (rpcCtx *Context) VerifyDialback(
...
+// connection attempt on future pings. Use the SystemClass to ensure that Raft
+// traffic is not interrupted. It is unusual for some classes to be affected and
+// not others but the SystemClass is the one we really care about.
+
+// loadPreviousAttempt checks if any prior attempt that started but hadn't
+// complete has now completed. Until this attempt completes, the Pings will
+// continue to return success. Once this completes, we remove this from our map
+// and return whatever error this attempt returned.
+func (rpcCtx *Context) loadOrCreateConnAttempt(
+	nodeID roachpb.NodeID, createConnFunc func() *Connection,
```
Comment (erikgrinaker) [inline pkg/rpc/context.go:2703]: nit: why the closure?

File: pkg/rpc/context.go [hunk 2]
```diff
@@ -2623,71 +2624,86 @@ func (rpcCtx *Context) VerifyDialback(
...
-	// Check if there was a previous attempt and if so use that and clear out
-	// the previous attempt.
+// createPreviousAttempt handles the case where we don't have a previous attempt
+// and the current health is not healthy, but we can't just trust that because
+// there might not be new initiated connection attempts. Instead, establish  a
+// new connection using the standard GRPCDialNode, this connection is added to
+// the connection pool. Always return success on this ping, but check this
+// connection attempt on future pings. Use the SystemClass to ensure that Raft
+// traffic is not interrupted. It is unusual for some classes to be affected and
+// not others but the SystemClass is the one we really care about.
```
Comment (erikgrinaker) [inline pkg/rpc/context.go:2696]: nit: Raft/liveness heartbeats (most Raft traffic goes via DefaultClass).

**Review by erikgrinaker — COMMENTED** [review]
> we may only block system traffic connections and not default class connections

Why is this a problem?

In the `blackhole-recv` case, the node has no inbound connections, but it has outbound connections. It therefore can't receive RPC traffic from the gateways. If we close the SystemClass connection, it also can't send Raft heartbeats nor liveness heartbeats, so it can't hold on to leadership or leases. Why does the workload stall in that case?

Are you sure the problem here wasn't that we closed DefaultClass but not SystemClass? That would allow the node to hang onto leases and leadership, even though no gateways could reach it.

> rpc: Fix blackhole recv

Nit: consider describing the actual bug here, i.e. that we often wouldn't detect dialback failures for some classes.

File: pkg/rpc/context.go [hunk 3]
```diff
@@ -2697,19 +2713,26 @@ func (rpcCtx *Context) previousAttempt(nodeID roachpb.NodeID) (error, bool) {
...
 			// The connection attempt was completed, return the outcome of it.
-			err, _ := previousAttempt.err.Load().(error)
-			rpcCtx.dialbackMu.m[nodeID] = nil
-			return err, true
+			err := previousAttempt.err.Load().(error)
+			if err == nil {
+				// If it completed without error then don't track the connection
+				// anymore. If it did have an error we need to track it until it later gets cleared.
+				rpcCtx.dialbackMu.m[nodeID] = nil
+			}
```
[the remark this answers is not in the document]
Comment (erikgrinaker) [reply pkg/rpc/context.go:2725]: On second thought, I guess that's covered by the explicit check for active connections in `VerifyDialback`. Might be nice to call that out.

**Review by erikgrinaker — APPROVED** [review]

**Review by andrewbaptist — COMMENTED** [review]
TFTR! I cleaned up the comments and removed the change to the failover test. I'll bors it once it passes and we should be able to see results tonight.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/99840#-:-NRoI_5oDh1z-7vhH5i5:b-p4oeg1)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @erikgrinaker, @smg260, and @srosenberg)

___
*[`pkg/rpc/context.go` line 0 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/99840#gh-1153170854:-NRo8XTT0maPVKj9zZog:blfp84m) ([raw file](https://github.com/cockroachdb/cockroach/blob/5af4759029177c475a16c1c3a582cea2a16ea7db/pkg/rpc/context.go#L0)):*
<details><summary><i>Previously, erikgrinaker (Erik Grinaker) wrote…</i></summary><blockquote>

*(Reviewable was [unable](https://github.com/Reviewable/Reviewable/issues/14) to map this GitHub inline comment thread to the right spot — sorry!)*

nit: shouldn't this be a warning/error, since it results in a connection failure?
</blockquote></details>

I'm not sure what the option here is we already flood the log with messages when a node goes down. I downgraded the error level since it was not an "abnormal" case in all cases (if they were upgrading, taking a node down, ...) So I didn't want warnings for "normal" operations. I'll leave this for now, but we could consider upgrading it later.
___
*[`pkg/rpc/context.go` line 2689 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/99840#-NRdVCQhI3GqNKGEx2Sy-r1-2689:-NRoEI1-3sRedoxxqdHZ:b-6x4qvo) ([raw file](https://github.com/cockroachdb/cockroach/blob/5af4759029177c475a16c1c3a582cea2a16ea7db/pkg/rpc/context.go#L2689)):*
<details><summary><i>Previously, erikgrinaker (Erik Grinaker) wrote…</i></summary><blockquote>

nit: method names in comments here seem outdated.
</blockquote></details>

Done - cleaned up the name and comments.
___
*[`pkg/rpc/context.go` line 2696 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/99840#-NRdVCQhI3GqNKGEx2Sy-r1-2696:-NRoGKvXEGx20i51m79A:b-bb2fca) ([raw file](https://github.com/cockroachdb/cockroach/blob/5af4759029177c475a16c1c3a582cea2a16ea7db/pkg/rpc/context.go#L2696)):*
<details><summary><i>Previously, erikgrinaker (Erik Grinaker) wrote…</i></summary><blockquote>

nit: Raft/liveness heartbeats (most Raft traffic goes via DefaultClass).
</blockquote></details>

Done - clarified the text regarding this. 
___
*[`pkg/rpc/context.go` line 2703 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/99840#-NRdVCQhI3GqNKGEx2Sy-r1-2703:-NRoGNzNB3dlpz2v80Ox:b6d9vq9) ([raw file](https://github.com/cockroachdb/cockroach/blob/5af4759029177c475a16c1c3a582cea2a16ea7db/pkg/rpc/context.go#L2703)):*
<details><summary><i>Previously, erikgrinaker (Erik Grinaker) wrote…</i></summary><blockquote>

nit: why the closure?
</blockquote></details>

This was to allow us to defer creating the connection until we know we need to, but also do it under the lock. It is similar to the Java's `computeIfAbsent` function. I could also just inline this method back in, but it made it clearer where the locks were held to keep it separated.
___
*[`pkg/rpc/context.go` line 2725 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/99840#-NRdVCQhI3GqNKGEx2Sy-r1-2725:-NRoIWztDHMDTw0pCL5Q:bwxlhw6) ([raw file](https://github.com/cockroachdb/cockroach/blob/5af4759029177c475a16c1c3a582cea2a16ea7db/pkg/rpc/context.go#L2725)):*
<details><summary><i>Previously, erikgrinaker (Erik Grinaker) wrote…</i></summary><blockquote>

On second thought, I guess that's covered by the explicit check for active connections in `VerifyDialback`, which also avoids leaking this stuff all over `rpcContext`. Might be nice to call that out.
</blockquote></details>

Added comments about this.
___
*[`pkg/cmd/roachtest/tests/failover.go` line 0 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/99840#gh-1153147138:-NRo7zvV7SrC7AaTJs6t:b-ct8l3c) ([raw file](https://github.com/cockroachdb/cockroach/blob/5af4759029177c475a16c1c3a582cea2a16ea7db/pkg/cmd/roachtest/tests/failover.go#L0)):*
<details><summary><i>Previously, erikgrinaker (Erik Grinaker) wrote…</i></summary><blockquote>

*(Reviewable was [unable](https://github.com/Reviewable/Reviewable/issues/14) to map this GitHub inline comment thread to the right spot — sorry!)*

Why remove this? This puts `blackhole` nodes into this weird state where they can receive TCP packets from remote port 26257 and send packets from local port 26257, but not the other way around (recall that client ports are randomly chosen). While that's still going to result in a useless TCP connection since packets can't be acked, the common case of a network outage is that all packets are dropped, and we should have coverage for that case.

We could arguably change the input/output cases below to drop packets in both directions (still maintaining connection asymmetry), which would have the same effect. However, asymmetric partitions are often caused by an incorrect firewall rule that drops packets in one direction, so it might be useful to cover that scenario. That seems less important that covering the common scenario of a total outage though.
</blockquote></details>

I pulled this change out of the commit. I think it was not changing anything, but I don't want to change the code and the test at the same time. I'll pull this out to a separate  PR that doesn't need to be backported.

**Review by erikgrinaker — COMMENTED** [review]
Nice!

> Reviewed 2 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/99840#-:-NRoK36E7xXqacKWiQmk:b-83sjoh)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andrewbaptist, @smg260, and @srosenberg)

___
*[`pkg/rpc/context.go` line 2703 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/99840#-NRdVCQhI3GqNKGEx2Sy-r1-2703:-NRoKDaj-DS9LrDN9SZ6:b-b35wee) ([raw file](https://github.com/cockroachdb/cockroach/blob/5af4759029177c475a16c1c3a582cea2a16ea7db/pkg/rpc/context.go#L2703)):*
<details><summary><i>Previously, andrewbaptist (Andrew Baptist) wrote…</i></summary><blockquote>

This was to allow us to defer creating the connection until we know we need to, but also do it under the lock. It is similar to the Java's `computeIfAbsent` function. I could also just inline this method back in, but it made it clearer where the locks were held to keep it separated.
</blockquote></details>

I see. We usually do this by suffixing the method name, e.g. `loadOrCreateConnAttemptLocked()` or `loadOrCreateConnAttemptDialbackMuLocked()`, see e.g. the plethora of `RaftMuLocked()` methods.
___
*[`pkg/cmd/roachtest/tests/failover.go` line 0 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/99840#gh-1153147138:-NRoKaUiB6WqfgjDEc7r:b-jpoc4u) ([raw file](https://github.com/cockroachdb/cockroach/blob/5af4759029177c475a16c1c3a582cea2a16ea7db/pkg/cmd/roachtest/tests/failover.go#L0)):*
>I think it was not changing anything

It sort of does, at least technically. Consider two nodes A and B, with a (randomly picked) client port 16384 and server port 26257. We'll have TCP packets going in four directions, across two TCP connections:

1. A:16384 → B:26257
2. A:16384 ← B:26257
3. A:26257 → B:16384
4. A:26257 ← B:16384

Consider the existing rules, applied on B:

```
iptables -A INPUT -m multiport -p tcp --ports 26257 -j DROP
iptables -A OUTPUT -m multiport -p tcp --ports 26257 -j DROP
```

The first rule blocks 1 and 3, the second rule blocks 2 and 4, because `--ports` matches both the source port and the destination port. Now consider the suggested rules:

```
iptables -A INPUT -p tcp --dport 26257 -j DROP
iptables -A OUTPUT -p tcp --dport 26257 -j DROP
```

This only blocks 1 and 4, allowing packets through for 2 and 3.

As I said, this probably doesn't matter all that much since the TCP connections won't work (SYNs and ACKs don't get through), but on the off chance that stray packets can affect the TCP stack behavior somehow I'd rather cover the common outage scenario where all packets are dropped.

**Comment by andrewbaptist** [comment]
bors r=erikgrinaker
