### PR TITLE
roachtest: report failures to extend cluster as infra flakes

### LINKED ISSUE #115950: roachtest: weekly/tpcc/headroom failed
roachtest.weekly/tpcc/headroom [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestWeeklyBazel/13056170?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestWeeklyBazel/13056170?buildTab=artifacts#/weekly/tpcc/headroom) on master @ [22d9482e646ae127981386d77b7ebf729346fc3b](https://github.com/cockroachdb/cockroach/commits/22d9482e646ae127981386d77b7ebf729346fc3b):

```
(monitor.go:153).Wait: monitor failure: context canceled
test artifacts and logs in: /artifacts/weekly/tpcc/headroom/run_1
```

Parameters:
 - <code>ROACHTEST_arch=amd64</code>
 - <code>ROACHTEST_cloud=gce</code>
 - <code>ROACHTEST_cpu=16</code>
 - <code>ROACHTEST_encrypted=false</code>
 - <code>ROACHTEST_fs=ext4</code>
 - <code>ROACHTEST_localSSD=true</code>
 - <code>ROACHTEST_metamorphicBuild=false</code>
 - <code>ROACHTEST_ssd=0</code>
<details><summary>Help</summary>
<p>

See: [roachtest README](https://github.com/cockroachdb/cockroach/blob/master/pkg/cmd/roachtest/README.md)

See: [How To Investigate \(internal\)](https://cockroachlabs.atlassian.net/l/c/SSSBr8c7)

See: [Grafana](https://go.crdb.dev/roachtest-grafana/teamcity-13056170/weekly-tpcc-headroom/1702125040868/1702171350713)

</p>
</details>
/cc @cockroachdb/test-eng
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*weekly/tpcc/headroom.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)
</sub>

### PR DESCRIPTION
**Pull request by renatolabs**
This commit introduces two main changes:

* always verify if we need to extend a cluster's lifetime before running a test, whether the cluster is being reused or not;
* if we fail to extend the cluster's lifetime, report the error as an infrastructure flake (cluster creation error). Crucially, don't return an error to the worker (which would halt the entire run), and don't notify teams about the failure.

Fixes: #115950.

Release note: None

### CODE REVIEW

**Comment by renatolabs** [comment]
Running `weekly/tpcc/headroom` on this branch now extends the cluster's lifetime based on the test's timeout:

```
20:36:02 cluster.go:2705: [w0] cluster needs to survive until 2023-12-18 07:36:02.060667 +0000 UTC m=+385358.557148573, but has expiration: 2023-12-14 08:33:25.188167036 +0000 UTC m=+43201.684648618. Extending.
20:36:02 cluster.go:2624: [w0] extending cluster by 95h2m36.872499955s
```

Also running a `SELEC_PROBABILITY=0.1` build:

https://teamcity.cockroachdb.com/viewQueued.html?itemId=13127705&tab=queuedBuildOverviewTab

**Review by DarrylWong — APPROVED** [review]
Ahh, totally went over my head that tests could take longer than the default cluster life when I made that change. The original motivation for shifting things around was to let it retry once, but in hindsight that might've been more trouble than it's worth.

Change LGTM and thanks for fixing!

File: pkg/cmd/roachtest/test_runner.go [hunk 1]
```diff
@@ -948,8 +927,7 @@ func (r *testRunner) runTest(
 	stdout io.Writer,
 	l *logger.Logger,
 	github *githubIssues,
-) error {
```
Comment (srosenberg) [inline pkg/cmd/roachtest/test_runner.go:951]: Nice!

**Review by srosenberg — APPROVED** [review]

**Comment by renatolabs** [comment]
Failures on the build are unrelated.

TFTRs!

bors r=DarrylWong,srosenberg
