### PR TITLE
GC Txn entries through GC queue

### LINKED ISSUE #2062: GC of Transaction table
this is the missing part of #1873 .

## GC of proto.Transaction

A `Transaction` record can be removed if its last heartbeat is sufficiently
old (say, `> 4*HeartbeatInterval`) and if no intents which should be visible
remain (i.e. only if it's committed do we need to ensure that).
If no heartbeat timestamp is present,the `Transaction` timestamp is used instead.
Those are HLC timestamps, but on the time scales involved, this is of no concern.

The GC queue is in charge of periodically grooming the `Transaction` table.
It can't ever GC a successfully committed `Transaction` which lists possibly-
unresolved intents, though. Encountering one of those requires prior intent
resolution. It will be easiest if the queue just gives those intents to the range
to handle then asynchronously as skipped intents, which should render
the `Transaction` GCable in the next pass.

Any successful `ResolveIntent` (or collection thereof) should be followed by
an invocation of a new RPC `ResolveTransaction` (or overload `EndTransaction`
for this purpose) which updates the `Transaction` record, removing
the resolved intents from the list stored within the `Transaction`.

## PushTxn

When executing against an absent on-disk record, the `Transaction` is
considered `ABORTED` if the intent's `Transaction` timestamp is older than
`< 2*HeartbeatInterval`, and no new entry is written in that case.

The choice of `{2,4}*HeartbeatInterval` above makes sure that `PushTxn`
will always find the `Transaction` record or decide correctly that it's `ABORTED`
without the need to write a new one.

## successful EndTransaction

Resolve local intents right away. If that includes all intents, we can remove
the record entirely. Otherwise, add the remainder to the `Transaction` record and return them for asynchronous resolution.

## failed EndTransaction

this fails either because of regression errors (these amount to bugs), or,
more interestingly, because the `Transaction` was aborted by a concurrent
writer.

Prime objective is removing the intents as soon as possible, but we can't
write on error. So we leave the `Transaction` record and resolve all intents
asynchronously.

Note that that can leave a `Transaction` in `PENDING` state so that it'll
likely never commit (it can be aborted due to timeout at some point) in
the case of regression errors (which amount to bugs).

### PR DESCRIPTION
**Pull request by tbg**
see #2062. This is a bit of a late Friday throw-over-the-wall but should generally be ready for review.

on each run of the GC queue for a given range, the transaction
and sequence prefixes are scanned and the following actions taken:
- old pending transactions are pushed (which will succeed), effectively
  aborting them
- old aborted transactions are added to the GC request.
- aborted and committed transactions will have the intents referenced
  in their record resolved synchronously and are GCed (on success)
- sequence cache entries which are "old" and belong to "old" (or
  nonexistent) transactions are deleted.

The implementation here isn't as performant as it could be by a long shot,
but very few txn/sequence cache entries should actually persist long enough
to be observed by this queue. Normally, transaction records are eagerly
removed after commit along with their sequence cache entries (much like
intents are usually resolved).

fixes #2062.

[Review on Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/3185)

### CODE REVIEW

File: storage/replica.go [hunk 1]
```diff
@@ -1589,8 +1583,8 @@ func (r *Replica) resolveIntents(ctx context.Context, intents []roachpb.Intent,
 					case *roachpb.NotLeaderError:
 					case *roachpb.RangeNotFoundError:
 					default:
-						// TODO(tschottdorf): Does this need to be a panic?
-						panic(fmt.Sprintf("local intent resolution failed with unexpected error: %s", err))
+						log.Warningf("local intent resolution failed with unexpected error: %s", err)
```
Comment (bdarnell) [inline storage/replica.go]: Does this change imply that you've seen this error in practice now? In general we shouldn't both log and return an error; just pass them up the stack and log them we we can no longer return the error.

File: storage/replica_command.go [hunk 2]
```diff
@@ -924,6 +916,10 @@ func (r *Replica) PushTxn(batch engine.Engine, ms *engine.MVCCStats, h roachpb.H
 		// The transaction doesn't exist yet on disk; we're allowed to abort it.
```
Comment (bdarnell) [inline storage/replica_command.go]: Remove "yet" from this comment.

File: storage/sequence_cache.go [hunk 3]
```diff
@@ -104,6 +104,33 @@ func (sc *SequenceCache) Get(e engine.Engine, id []byte, dest *roachpb.SequenceC
 	return epoch, seq, nil
 }
 
+// GetAllID returns all the key-value pairs for the given ID from the engine.
```
Comment (bdarnell) [inline storage/sequence_cache.go]: s/GetAllID/GetAllTransaction/ (and s/ID/transaction ID/ throughout the file)

The interfaces of all of these methods are somewhat inconsistent (`Get` and `Iterate` decode the value proto, but this method does not; `Get` and `Put` treat the storage as a black box but the two new methods expose the underlying keys directly). But this is also exactly what the callers need so I'm not sure if there are any worthwhile changes to be made.

File: storage/gc_queue_test.go [hunk 4]
```diff
@@ -314,6 +314,138 @@ func TestGCQueueProcess(t *testing.T) {
...
+		// Old, but still heartbeat. No GC.
+		"b": {roachpb.PENDING, 0, now - txnCleanupThreshold + 1, nil, false},
+		// Old and aborted, should delete.
+		"c": {roachpb.ABORTED, now - txnCleanupThreshold - 1, 0, nil, true},
+		// Abandoned and pending, so should push and abort it successfully.
+		// But it's not old enough to actively go after the sequence cache.
+		// There's some room for optimization here by ways of sharing the
+		// transaction grooming results with the corresponding operation for
+		// the sequence cache, but that's only worthwhile in weird cases.
+		"d": {roachpb.PENDING, now - dAbandon, 0, nil, false},
```
Comment (bdarnell) [inline storage/gc_queue_test.go]: `dAbandon` is negative, so `now - dAbandon` is in the future, which doesn't seem to be what is intended here.

File: storage/gc_queue_test.go [hunk 5]
```diff
@@ -314,6 +314,138 @@ func TestGCQueueProcess(t *testing.T) {
...
+			if id == "h" {
+				return util.Errorf("boom")
+			}
+		}
+		return nil
+	}
+	tc := testContext{}
+	tc.Start(t)
+	defer tc.Stop()
+	defer func() { TestingCommandFilter = nil }()
```
Comment (bdarnell) [inline storage/gc_queue_test.go]: Move this up a few lines. `tc.Start` could panic and leave `TestingCommandFilter` in a bad state.

File: storage/gc_queue_test.go [hunk 6]
```diff
@@ -314,6 +314,138 @@ func TestGCQueueProcess(t *testing.T) {
...
+	const dAbandon = -2 * DefaultHeartbeatInterval
+	type spec struct {
+		status      roachpb.TransactionStatus
+		ts          time.Duration
+		heartbeatTS time.Duration
+		intentSpans []roachpb.Span
+		seqGC       bool // expect sequence cache entries removed?
+	}
+	// Describes the state of the Txn table before the test.
+	before := map[string]spec{
```
Comment (bdarnell) [inline storage/gc_queue_test.go]: I would make all of these maps have keys of type `roachpb.Key` instead of casting from `string`. 

The before/after construct is awkward, with `seqGC` defined here and other expectations defined by changes made below. I would just add more "expectation" fields to the spec struct. And the use of `status = -1` could be replaced with a boolean since we don't do anything with this field in the `after` case except see whether it is -1.

File: storage/gc_queue.go [hunk 7]
```diff
@@ -46,6 +46,12 @@ const (
 	// intentAgeThreshold is the threshold after which an extant intent
 	// will be resolved.
 	intentAgeThreshold = 2 * time.Hour // 2 hour
+	// txnCleanupThreshold is the threshold after which a transaction is
+	// considered abandoned and fit for removal, as measured by the maximum
+	// of its last heartbeat and timestamp.
+	// TODO(tschottdorf): need to enforce at all times that this is much
+	// larger than the heartbeat interval used by the coordinator.
+	txnCleanupThreshold = time.Hour
```
Comment (bdarnell) [inline storage/gc_queue.go]: Why is this smaller than `intentAgeThreshold`? Must this always be true?

File: storage/gc_queue.go [hunk 8]
```diff
@@ -54,8 +60,10 @@ const (
...
 //  - GC of version data via TTL expiration (and more complex schemes
 //    as implemented going forward).
-//  - Resolve extant write intents and determine oldest non-resolvable
-//    intent.
+//  - Resolve extant write intents (pushing their transactions).
+//  - GC of old transaction and sequence cache entries. This should include
+//    most committed entries almost immediately and, after a threshold on
+//    inactivity, all others.
 //
 // The shouldQueue function combines the need for both tasks into a
```
Comment (bdarnell) [inline storage/gc_queue.go]: s/both/all three/

`shouldQueue` needs to be updated to account for the number of GC'able transaction records.

File: storage/gc_queue.go [hunk 9]
```diff
@@ -288,17 +292,134 @@ func (gcq *gcQueue) process(now roachpb.Timestamp, repl *Replica,
...
+		}
+		if !cutoff.Less(ts) {
+			// This is it, we can delete our sequence cache entries.
+			gcKeys = append(gcKeys, idToKeys[idStr]...)
+		}
+	}
+	return gcKeys
+}
+
+// processTransactionTable scans the transaction table and updates txnMap with
```
Comment (bdarnell) [inline storage/gc_queue.go]: Move this method above `processSequenceCache` so the order of the methods matches their order of execution.

File: storage/gc_queue.go [hunk 10]
```diff
@@ -288,17 +292,134 @@ func (gcq *gcQueue) process(now roachpb.Timestamp, repl *Replica,
...
+	var wg sync.WaitGroup
+	wg.Add(len(txns))
+	for _, txn := range txns {
+		// Check if the Txn is still alive. If this indicates that the Txn is
+		// aborted and old enough to guarantee that any running coordinator
+		// would have realized that the transaction wasn't running by means
+		// of a heartbeat, then we're free to remove the sequence cache entry.
+		// In the most likely case, there isn't even an entry (which will
+		// be apparent by a zero timestamp and nil last heartbeat).
+		go pushTxn(r, now, txn, roachpb.CLEANUP_TXN, &wg)
```
Comment (bdarnell) [inline storage/gc_queue.go]: Would it make sense to move `processSequenceCache` earlier in `process` so we could push transactions from the sequence cache in the same pass as other transactions?

File: storage/gc_queue.go [hunk 11]
```diff
@@ -139,14 +147,17 @@ func (gcq *gcQueue) process(now roachpb.Timestamp, repl *Replica,
...
-	// timestamp to compute intent age. While this should be fine, could
-	// consider adding a Now timestamp to GCRequest which would be used
-	// instead.
 	gcArgs := &roachpb.GCRequest{}
-	var mu sync.Mutex
-	var oldestIntentNanos int64 = math.MaxInt64
+	// TODO(tschottdorf): This is one of these instances in which we want
+	// to be more careful that the request ends up on the correct Replica,
+	// and we might have to worry about mixing range-local and global keys
+	// in a batch which might up spanning Ranges by the time it executes.
```
Comment (mrtracy) [inline storage/gc_queue.go]: might end up

**Comment by tschottdorf** [comment]
updated, PTAL

---

Review status: 0 of 16 files reviewed at latest revision, 5 unresolved discussions.

---

_[storage/gc_queue.go, line 54 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3185#-K3bfe9QE79LkXTSjjgg-r1-54:-K3ozSb85Mc8muNrZtU2:563277801) ([raw file](https://github.com/cockroachdb/cockroach/blob/97bbec351bb52698e8921c1385892c22a16a42c0/storage/gc_queue.go#L54)):_
No, these two can go either way and the current values are arbitrary. It makes some sense to have `txnCleanupThreshold` lower, though: In many cases, the intents will be linked to by the transaction record, in which case the GC of the transaction record will always reach out to resolve the intents (so the "later" intent GC wouldn't even have to look at those, since they'd already have been resolved).

---

_[storage/gc_queue.go, line 68 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3185#-K3bfe9QE79LkXTSjjgg-r1-68:-K3p-E-S-NWsfI8jOFlH:-1534997744) ([raw file](https://github.com/cockroachdb/cockroach/blob/97bbec351bb52698e8921c1385892c22a16a42c0/storage/gc_queue.go#L68)):_
We don't get that info from `MVCCStats`, want me to file an issue to add that there? Scanning the engine is probably too expensive to do in-place (?).

---

_[storage/gc_queue.go, line 322 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3185#-K3bfe9QE79LkXTSjjgg-r1-322:-K3p0IYdxm7_iFmgyQuV:686554649) ([raw file](https://github.com/cockroachdb/cockroach/blob/97bbec351bb52698e8921c1385892c22a16a42c0/storage/gc_queue.go#L322)):_
I think it's beneficial to deal with the sequence cache last since resolving intents removes a lot of those entries already. But I could pass in the `txnMap` as an argument so that the logic here could simply not push transactions which we've already pushed successfully.

---

_[storage/gc_queue_test.go, line 390 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3185#-K3bfe9QE79LkXTSjjgh-r1-390:-K3pAXRq1ekfH-CcwUif:-1513238471) ([raw file](https://github.com/cockroachdb/cockroach/blob/97bbec351bb52698e8921c1385892c22a16a42c0/storage/gc_queue_test.go#L390)):_
even worse, it's also a possible source of data races where it is now. Fixed.

---

_[storage/replica.go, line 1586 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3185#-K3bfe9QE79LkXTSjjgi-r1-1586:-K3pZ7REbKwS4X2xmT3R:52612337) ([raw file](https://github.com/cockroachdb/cockroach/blob/97bbec351bb52698e8921c1385892c22a16a42c0/storage/replica.go#L1586)):_
no, I haven't, removed the panic to deal with the TODO. I'll remove the log line.

---


_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/3185#-:-K3q5Uw9habmGjUykraz:-714543047)_

**Comment by bdarnell** [comment]
LGTM
