### PR TITLE
sessiondata: fix ListSessions with SET LOCAL / SET ROLE

### LINKED ISSUE #69508: sql: race in sessiondata.Stack
https://teamcity.cockroachdb.com//viewLog.html?buildId=3368714&buildTypeId=Cockroach_MergedExtendedCi

```
=== RUN   TestReplicaTombstone/(3)_ReplicaGCQueue
    test_log_scope.go:73: test logs captured to: /go/src/github.com/cockroachdb/cockroach/artifacts/logTestReplicaTombstone_(3)_ReplicaGCQueue358263899
    test_log_scope.go:74: use -show-logs to present logs inline
==================
WARNING: DATA RACE
Write at 0x00c0017872f0 by goroutine 320:
  github.com/cockroachdb/cockroach/pkg/sql/sessiondata.(*Stack).PopAll()
      /go/src/github.com/cockroachdb/cockroach/pkg/sql/sessiondata/session_data.go:272 +0x125
  github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).commitSQLTransaction.func1()
      /go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:822 +0x42
  github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).reportParamStatusUpdateChanges()
      /go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:834 +0xb2
  github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).commitSQLTransaction()
      /go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:821 +0x22d
  github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).handleAutoCommit()
      /go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:1775 +0x164
  github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execStmtInOpenState.func7()
      /go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:501 +0x1d2
  github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execStmtInOpenState()
      /go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:754 +0x17b4
  github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execStmt()
      /go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:129 +0x12be
  github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execCmd.func1()
      /go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:1687 +0x404
  github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execCmd()
      /go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:1689 +0x1d14
  github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).run()
      /go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:1611 +0x565
  github.com/cockroachdb/cockroach/pkg/sql.(*InternalExecutor).initConnEx.func1()
      /go/src/github.com/cockroachdb/cockroach/pkg/sql/internal.go:204 +0x8e

Previous read at 0x00c0017872f0 by goroutine 1050:
  github.com/cockroachdb/cockroach/pkg/sql/sessiondata.(*Stack).Top()
      /go/src/github.com/cockroachdb/cockroach/pkg/sql/sessiondata/session_data.go:226 +0x1257
  github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).sessionData()
      /go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:1516 +0x1225
  github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).serialize()
      /go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:2810 +0xaaa
  github.com/cockroachdb/cockroach/pkg/sql.(*SessionRegistry).SerializeAll()
      /go/src/github.com/cockroachdb/cockroach/pkg/sql/exec_util.go:1796 +0x247
  github.com/cockroachdb/cockroach/pkg/server.(*baseStatusServer).getLocalSessions()
      /go/src/github.com/cockroachdb/cockroach/pkg/server/status.go:190 +0x28f
  github.com/cockroachdb/cockroach/pkg/server.(*statusServer).ListLocalSessions()
      /go/src/github.com/cockroachdb/cockroach/pkg/server/status.go:1995 +0x92
  github.com/cockroachdb/cockroach/pkg/server/serverpb._Status_ListLocalSessions_Handler.func1()
      /go/src/github.com/cockroachdb/cockroach/pkg/server/serverpb/status.pb.go:5756 +0xa4
  github.com/cockroachdb/cockroach/pkg/util/tracing.ServerInterceptor.func1()
      /go/src/github.com/cockroachdb/cockroach/pkg/util/tracing/grpc_interceptor.go:126 +0x67c
  google.golang.org/grpc.getChainUnaryHandler.func1()
      /go/src/github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/server.go:1134 +0x14f
  github.com/cockroachdb/cockroach/pkg/rpc.NewServer.func1()
      /go/src/github.com/cockroachdb/cockroach/pkg/rpc/context.go:177 +0x124
  google.golang.org/grpc.getChainUnaryHandler.func1()
      /go/src/github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/server.go:1134 +0x14f
  github.com/cockroachdb/cockroach/pkg/rpc.kvAuth.unaryInterceptor()
      /go/src/github.com/cockroachdb/cockroach/pkg/rpc/auth.go:71 +0x138
  github.com/cockroachdb/cockroach/pkg/rpc.kvAuth.unaryInterceptor-fm()
      /go/src/github.com/cockroachdb/cockroach/pkg/rpc/auth.go:47 +0xa4
  google.golang.org/grpc.chainUnaryServerInterceptors.func1()
      /go/src/github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/server.go:1120 +0x112
  github.com/cockroachdb/cockroach/pkg/server/serverpb._Status_ListLocalSessions_Handler()
      /go/src/github.com/cockroachdb/cockroach/pkg/server/serverpb/status.pb.go:5758 +0x1f1
  google.golang.org/grpc.(*Server).processUnaryRPC()
      /go/src/github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/server.go:1293 +0xa65
  google.golang.org/grpc.(*Server).handleStream()
      /go/src/github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/server.go:1618 +0x142b
  google.golang.org/grpc.(*Server).serveStreams.func1.2()
      /go/src/github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/server.go:941 +0xe6
```

```
==================
WARNING: DATA RACE
Read at 0x00c0032b9128 by goroutine 107:
  github.com/cockroachdb/cockroach/pkg/sql/sessiondata.(*Stack).Top()
      /go/src/github.com/cockroachdb/cockroach/pkg/sql/sessiondata/session_data.go:226 +0x1257
  github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).sessionData()
      /go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:1516 +0x1225
  github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).serialize()
      /go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:2810 +0xaaa
  github.com/cockroachdb/cockroach/pkg/sql.(*SessionRegistry).SerializeAll()
      /go/src/github.com/cockroachdb/cockroach/pkg/sql/exec_util.go:1796 +0x247
  github.com/cockroachdb/cockroach/pkg/server.(*baseStatusServer).getLocalSessions()
      /go/src/github.com/cockroachdb/cockroach/pkg/server/status.go:190 +0x28f
  github.com/cockroachdb/cockroach/pkg/server.(*statusServer).ListLocalSessions()
      /go/src/github.com/cockroachdb/cockroach/pkg/server/status.go:1995 +0x92
  github.com/cockroachdb/cockroach/pkg/sql.glob..func53()
      /go/src/github.com/cockroachdb/cockroach/pkg/sql/crdb_internal.go:1481 +0x1a8
  github.com/cockroachdb/cockroach/pkg/sql.(*virtualDefEntry).getPlanInfo.func1.1()
      /go/src/github.com/cockroachdb/cockroach/pkg/sql/virtual_schema.go:533 +0x1f8
  github.com/cockroachdb/cockroach/pkg/sql.setupGenerator.func3()
      /go/src/github.com/cockroachdb/cockroach/pkg/sql/virtual_table.go:120 +0x1a9
  github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunAsyncTaskEx.func2()
      /go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:442 +0x161

Previous write at 0x00c0032b9128 by goroutine 518:
  github.com/cockroachdb/cockroach/pkg/sql/sessiondata.(*Stack).PopAll()
      /go/src/github.com/cockroachdb/cockroach/pkg/sql/sessiondata/session_data.go:272 +0x125
  github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).commitSQLTransaction.func1()
      /go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:822 +0x42
  github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).reportParamStatusUpdateChanges()
      /go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:834 +0xb2
  github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).commitSQLTransaction()
      /go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:821 +0x22d
  github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).handleAutoCommit()
      /go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:1775 +0x164
  github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execStmtInOpenState.func7()
      /go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:501 +0x1d2
  github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execStmtInOpenState()
      /go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:754 +0x17b4
  github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execStmt()
      /go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:129 +0x12be
  github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execPortal()
      /go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:216 +0x1d3
  github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execCmd.func2()
      /go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:1755 +0x872
  github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execCmd()
      /go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:1757 +0x5c4
  github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).run()
      /go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:1611 +0x565
  github.com/cockroachdb/cockroach/pkg/sql.(*InternalExecutor).initConnEx.func1()
      /go/src/github.com/cockroachdb/cockroach/pkg/sql/internal.go:204 +0x8e
```

### PR DESCRIPTION
**Pull request by otan**
Previously, two incorrect phenomena was incorrect due to recent changes:
* SET ROLE would report the user the current session was impersonated
  as, rather than the user who was logged in. The latter seems more
  correct to report here.
* There is a race between a BEGIN/COMMIT/ROLLBACK and listing all
  sessions using ListSessions as they both try to access the stack.

This is both fixed by:
* Changing the returned user of SET ROLE to be the SessionUser.
* Introducing a `base` method to SessionDataStack, which returns the
  base of the stack. This is *always* set, so allow accordingly.

Release justification: fix to new functionality

Resolves: #69508

Release note: None

### CODE REVIEW

File: pkg/sql/sessiondata/session_data.go [hunk 1]
```diff
@@ -229,6 +233,12 @@ func (s *Stack) Top() *SessionData {
 	return s.stack[len(s.stack)-1]
 }
 
+// Base returns the bottom element of the stack.
+// This is a non-racy structure, as the bottom element is always constant.
```
Comment (rafiss) [inline pkg/sql/sessiondata/session_data.go:237]: very smart!

File: pkg/sql/logictest/testdata/logic_test/set_role [hunk 2]
```diff
@@ -338,10 +340,28 @@ SELECT current_user, session_user()
...
 statement ok
 ROLLBACK
 
 query TT
 SELECT current_user, session_user()
 ----
 root  root
+
+statement ok
+SET LOCAL ROLE testuser
```
Comment (rafiss) [inline pkg/sql/logictest/testdata/logic_test/set_role:358]: isn't this a no-op anyway since it's a SET LOCAL outside of a txn? or was it intended to be SET ROLE? (if so, maybe we might as well add a test for SET LOCAL ROLE inside a txn as well)

**Review by rafiss — CHANGES_REQUESTED** [review]

File: pkg/sql/logictest/testdata/logic_test/set_role (hunk 2 above)
Comment (otan) [reply pkg/sql/logictest/testdata/logic_test/set_role:359]: d'oh, yep!

**Review by rafiss — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/69553)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @otan)

___
*[pkg/sql/logictest/testdata/logic_test/set_role, line 358 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/69553#-MiJ2qzkvH8SAZiqOLn_-r1-358:-MiJofOy7k0km-LTqY4l:b-du8vbh) ([raw file](https://github.com/cockroachdb/cockroach/blob/6da24207e6b5e87dd14773bfce04e81f74be0a84/pkg/sql/logictest/testdata/logic_test/set_role#L358)):*
<details><summary><i>Previously, otan (Oliver Tan) wrote…</i></summary><blockquote>

d'oh, yep!
</blockquote></details>

ah oops i didn't see that SET LOCAL ROLE followed by `SELECT ... node_sessions` is already tested on line 336!

so i think the test case here (line 359) should be a normal SET ROLE

**Review by otan — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/69553)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @otan and @rafiss)

___
*[pkg/sql/logictest/testdata/logic_test/set_role, line 358 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/69553#-MiJ2qzkvH8SAZiqOLn_-r1-358:-MiK9O-S0IP04EdjwcvD:b-qkvsni) ([raw file](https://github.com/cockroachdb/cockroach/blob/6da24207e6b5e87dd14773bfce04e81f74be0a84/pkg/sql/logictest/testdata/logic_test/set_role#L358)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

ah oops i didn't see that SET LOCAL ROLE followed by `SELECT ... node_sessions` is already tested on line 336!

so i think the test case here (line 359) should be a normal SET ROLE 
</blockquote></details>

i managed to confuse myself, haha! fixed

**Review by rafiss — APPROVED** [review]

**Comment by otan** [comment]
bors r=rafiss

**Comment by otan** [comment]
bors r=rafiss
