### PR TITLE
kvcoord: fix txnWriteBuffer for batches with limits and Dels

### LINKED ISSUE #151294: kvclient: incorrect "rows affected" and changed locking behavior with DELETEs of more than 600 rows in some cases
pkg/sql/tests.BenchmarkKV [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachprodMicrobenchmarkWeeklyWip/20289400?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachprodMicrobenchmarkWeeklyWip/20289400?buildTab=artifacts#./artifacts/microbench/experiment) on master @ [ca0d4076c381609d6487040141c87e36a68b211f](https://github.com/cockroachdb/cockroach/commits/ca0d4076c381609d6487040141c87e36a68b211f):

```
BenchmarkKV/Delete/Native/rows=100
BenchmarkKV/Delete/Native/rows=100-32       	    1599	    792697 ns/op	  293258 B/op	    1349 allocs/op
BenchmarkKV/Delete/Native/rows=1000
BenchmarkKV/Delete/Native/rows=1000-32      	     226	   5793588 ns/op	 2388421 B/op	   12291 allocs/op
BenchmarkKV/Delete/Native/rows=10000
BenchmarkKV/Delete/Native/rows=10000-32     	      21	  56065942 ns/op	32016176 B/op	  121147 allocs/op
BenchmarkKV/Delete/SQL
BenchmarkKV/Delete/SQL/rows=1
BenchmarkKV/Delete/SQL/rows=1-32            	    2678	    462344 ns/op	   56595 B/op	     353 allocs/op
BenchmarkKV/Delete/SQL/rows=10
BenchmarkKV/Delete/SQL/rows=10-32           	    2004	    573893 ns/op	  101269 B/op	     792 allocs/op
BenchmarkKV/Delete/SQL/rows=100
BenchmarkKV/Delete/SQL/rows=100-32          	     852	   1352191 ns/op	  468761 B/op	    4728 allocs/op
BenchmarkKV/Delete/SQL/rows=1000
    kv_test.go:384: expected 1000 rows affected, found 600
--- FAIL: BenchmarkKV/Delete/SQL/rows=1000
BenchmarkKV/Delete/SQL/rows=10000
    kv_test.go:384: expected 10000 rows affected, found 600
--- FAIL: BenchmarkKV/Delete/SQL/rows=10000
--- FAIL: BenchmarkKV/Delete/SQL
--- FAIL: BenchmarkKV/Delete
BenchmarkKV/Scan
BenchmarkKV/Scan/Native
BenchmarkKV/Scan/Native/rows=1
BenchmarkKV/Scan/Native/rows=1-32           	   44509	     26820 ns/op	    8562 B/op	      42 allocs/op
BenchmarkKV/Scan/Native/rows=10
BenchmarkKV/Scan/Native/rows=10-32          	   39031	     30028 ns/op	   10050 B/op	      46 allocs/op
BenchmarkKV/Scan/Native/rows=100
BenchmarkKV/Scan/Native/rows=100-32         	   23611	     49349 ns/op	   22849 B/op	      50 allocs/op
BenchmarkKV/Scan/Native/rows=1000
BenchmarkKV/Scan/Native/rows=1000-32        	    4528	    241837 ns/op	  174087 B/op	      60 allocs/op
BenchmarkKV/Scan/Native/rows=10000
BenchmarkKV/Scan/Native/rows=10000-32       	     531	   2034796 ns/op	 1521956 B/op	      92 allocs/op
BenchmarkKV/Scan/SQL
BenchmarkKV/Scan/SQL/rows=1
BenchmarkKV/Scan/SQL/rows=1-32              	    4939	    229566 ns/op	   22959 B/op	     202 allocs/op
BenchmarkKV/Scan/SQL/rows=10
BenchmarkKV/Scan/SQL/rows=10-32             	    4795	    246542 ns/op	   24691 B/op	     228 allocs/op
BenchmarkKV/Scan/SQL/rows=100
BenchmarkKV/Scan/SQL/rows=100-32            	    3697	    315854 ns/op	   39333 B/op	     420 allocs/op
BenchmarkKV/Scan/SQL/rows=1000
BenchmarkKV/Scan/SQL/rows=1000-32           	    1210	    915662 ns/op	  213722 B/op	    2992 allocs/op
BenchmarkKV/Scan/SQL/rows=10000
BenchmarkKV/Scan/SQL/rows=10000-32          	     180	   6537974 ns/op	 1363146 B/op	   30121 allocs/op
    kv_test.go:394: -- test log scope end --
--- FAIL: BenchmarkKV
FAIL

I250803 23:08:02.606762 1 (gostd) rand.go:268  [-] 1  random seed: 2643472666182387187
test logs left over in: /tmp/logBenchmarkKV3002410994
```
<details><summary>Help</summary>
<p>

See also: [How To Investigate a Go Test Failure \(internal\)](https://cockroachlabs.atlassian.net/l/c/HgfXfJgM)
</p>
</details>
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*BenchmarkKV.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/bazci/githubpost/issues)

</sub>

Jira issue: CRDB-53195

### LINKED ISSUE #151649: pkg/sql/tests: BenchmarkKV failed [dup of #151294]
pkg/sql/tests.BenchmarkKV [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachprodMicrobenchmarkWeeklyWip/20322595?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachprodMicrobenchmarkWeeklyWip/20322595?buildTab=artifacts#./artifacts/microbench/experiment) on master @ [166d6538fc5bc47b861d81c95e9dbfc19994a1da](https://github.com/cockroachdb/cockroach/commits/166d6538fc5bc47b861d81c95e9dbfc19994a1da):

```
BenchmarkKV/Delete/Native/rows=100
BenchmarkKV/Delete/Native/rows=100-32       	    1596	    794087 ns/op	  293673 B/op	    1349 allocs/op
BenchmarkKV/Delete/Native/rows=1000
BenchmarkKV/Delete/Native/rows=1000-32      	     222	   5936903 ns/op	 2363803 B/op	   12220 allocs/op
BenchmarkKV/Delete/Native/rows=10000
BenchmarkKV/Delete/Native/rows=10000-32     	      20	  57419862 ns/op	33842446 B/op	  121731 allocs/op
BenchmarkKV/Delete/SQL
BenchmarkKV/Delete/SQL/rows=1
BenchmarkKV/Delete/SQL/rows=1-32            	    2556	    466679 ns/op	   56973 B/op	     354 allocs/op
BenchmarkKV/Delete/SQL/rows=10
BenchmarkKV/Delete/SQL/rows=10-32           	    1930	    577924 ns/op	  101566 B/op	     796 allocs/op
BenchmarkKV/Delete/SQL/rows=100
BenchmarkKV/Delete/SQL/rows=100-32          	     854	   1330611 ns/op	  477995 B/op	    4734 allocs/op
BenchmarkKV/Delete/SQL/rows=1000
    kv_test.go:384: expected 1000 rows affected, found 600
--- FAIL: BenchmarkKV/Delete/SQL/rows=1000
BenchmarkKV/Delete/SQL/rows=10000
    kv_test.go:384: expected 10000 rows affected, found 600
--- FAIL: BenchmarkKV/Delete/SQL/rows=10000
--- FAIL: BenchmarkKV/Delete/SQL
--- FAIL: BenchmarkKV/Delete
BenchmarkKV/Scan
BenchmarkKV/Scan/Native
BenchmarkKV/Scan/Native/rows=1
BenchmarkKV/Scan/Native/rows=1-32           	   44234	     26661 ns/op	    8565 B/op	      42 allocs/op
BenchmarkKV/Scan/Native/rows=10
BenchmarkKV/Scan/Native/rows=10-32          	   39600	     28979 ns/op	   10044 B/op	      46 allocs/op
BenchmarkKV/Scan/Native/rows=100
BenchmarkKV/Scan/Native/rows=100-32         	   24750	     48144 ns/op	   22835 B/op	      50 allocs/op
BenchmarkKV/Scan/Native/rows=1000
BenchmarkKV/Scan/Native/rows=1000-32        	    4927	    231696 ns/op	  174005 B/op	      59 allocs/op
BenchmarkKV/Scan/Native/rows=10000
BenchmarkKV/Scan/Native/rows=10000-32       	     542	   1977825 ns/op	 1518177 B/op	      92 allocs/op
BenchmarkKV/Scan/SQL
BenchmarkKV/Scan/SQL/rows=1
BenchmarkKV/Scan/SQL/rows=1-32              	    4519	    230062 ns/op	   23121 B/op	     202 allocs/op
BenchmarkKV/Scan/SQL/rows=10
BenchmarkKV/Scan/SQL/rows=10-32             	    4629	    236831 ns/op	   24784 B/op	     228 allocs/op
BenchmarkKV/Scan/SQL/rows=100
BenchmarkKV/Scan/SQL/rows=100-32            	    3607	    319103 ns/op	   39303 B/op	     419 allocs/op
BenchmarkKV/Scan/SQL/rows=1000
BenchmarkKV/Scan/SQL/rows=1000-32           	    1258	    902573 ns/op	  213618 B/op	    2992 allocs/op
BenchmarkKV/Scan/SQL/rows=10000
BenchmarkKV/Scan/SQL/rows=10000-32          	     183	   6437653 ns/op	 1362338 B/op	   30120 allocs/op
    kv_test.go:394: -- test log scope end --
--- FAIL: BenchmarkKV
FAIL

I250810 11:37:43.256933 1 (gostd) rand.go:268  [-] 1  random seed: 150611251317681597
test logs left over in: /tmp/logBenchmarkKV2130003044
```
<details><summary>Help</summary>
<p>

See also: [How To Investigate a Go Test Failure \(internal\)](https://cockroachlabs.atlassian.net/l/c/HgfXfJgM)
</p>
</details>
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*BenchmarkKV.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/bazci/githubpost/issues)

</sub>

Jira issue: CRDB-53386

### PR DESCRIPTION
**Pull request by yuzefovich**
Previously, the txnWriteBuffer was oblivious to the fact that some transformed requests might be returned incomplete due to limits set on the BatchRequest (either TargetBytes or MaxSpanRequestKeys), so it would incorrectly think that it has acquired locks on some keys when it hasn't. Usage from SQL was only exposed to the bug via special delete-range fast-path where we used point Dels (i.e. a stmt of the form `DELETE FROM t WHERE k IN (<ids>)` where there are gaps between `id`s) since it always sets a key limit of 600. This commit fixes this particular issue for Dels transformed into Gets and adds a couple of assertions that we don't see batches with CPuts and/or Puts with the limits set.

Additionally, it adjusts the comment to indicate which requests are allowed in batches with limits.

Given that this feature is disabled by default and in the private preview AND it's limited to the DELETE fast-path when more than 600 keys are deleted, I decided to omit the release note.

Fixes: #151294.
Fixes: #151649.

Release note: None

### CODE REVIEW

**Review by yuzefovich — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/151559)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @miraradeva and @stevendanna)

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/151559#-OX5L8-rBtDbd7twhRDa:-OX5L8-rBtDbd7twhRDb:br7sob5):*
I think we also have a similar issue with Gets, Scans, and ReverseScans that are transformed from replicated to unreplicated - we call `addDurableLockedReadToBuffer` without looking at the ResumeSpan of the response. I didn't include it into this patch since it would lead to conflicts on 25.2 branch, but we should fix it too.

**Review by yuzefovich — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/151559)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @miraradeva and @stevendanna)

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/151559#-OX5L8-rBtDbd7twhRDa:-OX5MQMH8fa3aV2XwpvD:brcdvn9):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

I think we also have a similar issue with Gets, Scans, and ReverseScans that are transformed from replicated to unreplicated - we call `addDurableLockedReadToBuffer` without looking at the ResumeSpan of the response. I didn't include it into this patch since it would lead to conflicts on 25.2 branch, but we should fix it too.
</blockquote></details>

I filed #151567 - let me know if I'm missing something.

**Review by miraradeva — APPROVED** [review]
:lgtm: Just a couple of questions.

> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/151559#-:-OX99jsj4v1JsrG78kcD:b-yvgwcy)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @stevendanna and @yuzefovich)

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/151559#-OX5L8-rBtDbd7twhRDa:-OX8pspq6-gyKhSDFsUG:b-pbdqz3):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

I filed #151567 - let me know if I'm missing something.
</blockquote></details>

Agreed.
___
*[`pkg/kv/kvclient/kvcoord/txn_interceptor_write_buffer.go` line 438 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/151559#-OX8rX0-DtXGBEeeIUBv:-OX8rX0-DtXGBEeeIUBw:b-ebajj5) ([raw file](https://github.com/cockroachdb/cockroach/blob/bf534904b700cf57f36ff7f32848b4d66bd4df63/pkg/kv/kvclient/kvcoord/txn_interceptor_write_buffer.go#L438)):*
> ```Go
> 			assertTrue(ba.MaxSpanRequestKeys == 0 && ba.TargetBytes == 0, "unexpectedly found CPut in a BatchRequest with a limit")
> 		case *kvpb.PutRequest:
> 			assertTrue(ba.MaxSpanRequestKeys == 0 && ba.TargetBytes == 0, "unexpectedly found Put in a BatchRequest with a limit")
> ```

Doesn't the DistSender code above imply that it's ok to have a Put in a batch with TargetBytes or MaxSpanRequestKeys?

```
case *kvpb.QueryIntentRequest, *kvpb.EndTxnRequest,
    *kvpb.GetRequest, *kvpb.ResolveIntentRequest, *kvpb.DeleteRequest, *kvpb.PutRequest:
    // Accepted point requests that can be in batches with limit.

```
Presumably SQL doesn't make such batches? I think if the DistSender allows it, we'll probably want to handle it here. If that checks out to you, do you mind adding a TODO?
___
*[`pkg/kv/kvclient/kvcoord/txn_interceptor_write_buffer.go` line 1439 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/151559#-OX8v24UBTulmHIEEWZd:-OX8v24UBTulmHIEEWZe:b-rjcnsp) ([raw file](https://github.com/cockroachdb/cockroach/blob/bf534904b700cf57f36ff7f32848b4d66bd4df63/pkg/kv/kvclient/kvcoord/txn_interceptor_write_buffer.go#L1439)):*
> ```Go
> 		var resp kvpb.DeleteResponse
> 		val, _, served := twb.maybeServeRead(req.Key, req.Sequence)
> 		if served {
> ```

Tangentially related: If we send a batch to KV that returns a ResumeSpan, presumably we exceeded the target bytes or max requested keys. If we don't send the batch to KV and serve it all from the buffer, it could return significantly more bytes/keys, right? Presumably this is ok because these limits are there to protect KV/storage, not the client.

File: pkg/kv/kvclient/kvcoord/txn_interceptor_write_buffer.go [hunk 1]
```diff
@@ -1410,6 +1416,11 @@ func (rr requestRecord) toResp(
 
 	case *kvpb.PutRequest:
 		var dla *bufferedDurableLockAcquisition
+		// TODO(yuzefovich): we should check whether ResumeSpan is non-nil if we
+		// transformed the request, in which case the response from KV is
+		// incomplete. This can happen when MaxSpanRequestKeys and/or
+		// TargetBytes limits are set on the batch, and SQL currently doesn't do
+		// that for batches with Puts.
```
Comment (stevendanna) [inline pkg/kv/kvclient/kvcoord/txn_interceptor_write_buffer.go]: What if the Puts are from the buffer and we flushed the buffer because of a batch with TargetBytes/MaxSpanRequestKeys set?

Comment (yuzefovich) [reply pkg/kv/kvclient/kvcoord/txn_interceptor_write_buffer.go]: That's a good question I haven't initially considered.

This method `toResp` is only called for original requests included into the batch by the caller since we strip out all requests that were prepended in order to flush the buffer. Since SQL never sets any BatchRequest limit when including Puts or CPuts, the particular scenario is not possible.

What is possible is that SQL sets the BatchRequest limit, and we're piggy-backing on that batch to flush the buffer, while we have Puts and/or Dels in the buffer. Luckily, when processing both Puts and Dels on the server side, we ignore the limits. Additionally, when the batch has a limit set, then the DistSender will not parallelize across ranges, so all requests in the batch will be processed in order. Thus, I think all prepended Puts and Dels will be fully processed before any of the client requests. (If we did buffer DelRange request, it would've been affected.) I added some simple test-only validation.

Does this make sense? It does look quite fragile overall ... Perhaps we should refactor our flushing mechanism to create a separate BatchRequest when the caller's one has a limit set?

**Review by yuzefovich — COMMENTED** [review]
Thanks for the careful reviews!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/151559#-:-OXR5qpFB9HXSJVJWb3E:b7lnsi)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @miraradeva and @stevendanna)

___
*[`pkg/kv/kvclient/kvcoord/txn_interceptor_write_buffer.go` line 438 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/151559#-OX8rX0-DtXGBEeeIUBv:-OXQtkKh26J4SUNLrpQL:b-vxsm1i) ([raw file](https://github.com/cockroachdb/cockroach/blob/bf534904b700cf57f36ff7f32848b4d66bd4df63/pkg/kv/kvclient/kvcoord/txn_interceptor_write_buffer.go#L438)):*
<details><summary><i>Previously, miraradeva (Mira Radeva) wrote…</i></summary><blockquote>

Doesn't the DistSender code above imply that it's ok to have a Put in a batch with TargetBytes or MaxSpanRequestKeys?

```
case *kvpb.QueryIntentRequest, *kvpb.EndTxnRequest,
    *kvpb.GetRequest, *kvpb.ResolveIntentRequest, *kvpb.DeleteRequest, *kvpb.PutRequest:
    // Accepted point requests that can be in batches with limit.

```
Presumably SQL doesn't make such batches? I think if the DistSender allows it, we'll probably want to handle it here. If that checks out to you, do you mind adding a TODO?
</blockquote></details>

Good point. We included Puts in the allow-list in 66fd5f57bb35a193d8ec34e1c860f6f20ca49c7a specifically because of the case when the txnWriteBuffer needs to be flushed. I agree that this assertion is stricter than what DistSender permits, so I left a TODO with some context.
___
*[`pkg/kv/kvclient/kvcoord/txn_interceptor_write_buffer.go` line 1439 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/151559#-OX8v24UBTulmHIEEWZd:-OXR3fuv9FNx2vZBbwYC:bz2jxeg) ([raw file](https://github.com/cockroachdb/cockroach/blob/bf534904b700cf57f36ff7f32848b4d66bd4df63/pkg/kv/kvclient/kvcoord/txn_interceptor_write_buffer.go#L1439)):*
<details><summary><i>Previously, miraradeva (Mira Radeva) wrote…</i></summary><blockquote>

Tangentially related: If we send a batch to KV that returns a ResumeSpan, presumably we exceeded the target bytes or max requested keys. If we don't send the batch to KV and serve it all from the buffer, it could return significantly more bytes/keys, right? Presumably this is ok because these limits are there to protect KV/storage, not the client.
</blockquote></details>

Another good point I haven't considered. The limits are in place to protect both the client and the server, so the fact that we're effectively ignoring limits when serving reads from the buffer is a violation that could increase the likelihood of OOMs (although given the default 4MiB buffer size, we should never buffer too much data to matter in practice). We also return correct `NumKeys` and `NumBytes` parameters for Scans and ReverseScans. I left a couple of TODOs to look into this.

File: pkg/kv/kvclient/kvcoord/txn_interceptor_write_buffer.go (hunk 1 above)
Comment (stevendanna) [reply pkg/kv/kvclient/kvcoord/txn_interceptor_write_buffer.go]: > Luckily, when processing both Puts and Dels on the server side, we ignore the limits.

We might also have Get's that resulted from buffered replicated locking requests that haven't yet been replaced by writes. It is probably hard to hit on 25.3 because you would need to turn on buffered writes, turn on buffered writes for weak isolation (or durable locks for serialisable) and issue enough point get locks (we don't buffer scans by default on 25.3), and then get either a DeleteRange or some batch with many many Get's that has a limit set and forces a flush.

>  Perhaps we should refactor our flushing mechanism to create a separate BatchRequest when the caller's one has a limit set?

Yeah, I have done something similar for the skipped locked issue we currently have: 

https://github.com/cockroachdb/cockroach/pull/150276

so perhaps this is another condition where we should flush with 2 batches rather than 1.

Comment (arulajmani) [reply pkg/kv/kvclient/kvcoord/txn_interceptor_write_buffer.go]: > so perhaps this is another condition where we should flush with 2 batches rather than 1.

+1.

Comment (yuzefovich) [reply pkg/kv/kvclient/kvcoord/txn_interceptor_write_buffer.go]: Thanks, I didn't fully realize that we now can also flush Gets from the buffer. A scenario where SQL can set a relatively small limit is if the query has a "limit hint", in which case `txnKVFetcher.getBatchKeyLimit` can return a small value for `MaxSpanRequestKeys`. ("Limit hint" is used when the optimizer has a guess of how many rows will need to be scanned, yet due to filter not being pushed into the scan, it might be an underestimate, so more actual rows might be needed.)

I removed the test-only assertion I added in the previous revision based on this realization. Steven, are you ok with the current change? It's related but somewhat orthogonal to the issue with Gets, and this needs to go to 25.2, so I think it can be merged separately.

**Review by yuzefovich — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/151559)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @miraradeva and @stevendanna)

File: pkg/kv/kvclient/kvcoord/txn_interceptor_write_buffer.go (hunk 1 above)
Comment (stevendanna) [reply pkg/kv/kvclient/kvcoord/txn_interceptor_write_buffer.go]: We have an issue open for Gets and definitely won't forget about it as it is on the top of my list.  So I think we are good to do this as a separate change.

**Review by stevendanna — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/151559)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @arulajmani, @miraradeva, and @yuzefovich)

**Comment by yuzefovich** [comment]
TFTRs!

bors r+

**Comment by yuzefovich** [comment]
blathers backport release-25.3.1-rc
