### PR TITLE
ui: fix initial node statuses on Metrics page

### LINKED ISSUE #59253: ui: a fully operational cluster shows dead nodes navigating from statements page to overview
**Describe the problem**
under certain load a cluster with active queries will show dead nodes on the overview page if you navigate from statements page to overview

Please describe the issue you observed, and any steps we can take to reproduce it:

**Environment:**
 - CockroachDB version 20.2.3 and 20.2.4 have that
 - Server OS: Ubuntu 16.04
 - Client app roachprod DB Console

**Additional context**
What was the impact?

image

### PR DESCRIPTION
**Pull request by koorosh**
Release justification: bug fix for existing functionality

Before, Node statuses on Metrics page displayed incorrect node statuses
when page was just loaded and liveness statuses weren't updated immediately
due to incorrect validation condition. It caused all nodes to be recognized
as dead.

Current change fixes validation for presence of liveness statuses in
`nodeSumsSelector` selector which assumes that it's not possible to
have all nodes dead (at least one has to be healthy). So this state
is possible only when no liveness statuses were requested from server yet.

In addition, props for `NodeGraphs` component is cleaned up. It doesn't
require `nodesQueryValid` and `livenessQueryValid` props because validation
on validness of data is performed in CachedDataReducer.refresh function on
every call.

Release note (bug fix): don't display incorrect node statuses on Metrics page,
when page just loaded.

Resolves #59253

Before:
before

After:
after

### CODE REVIEW

File: pkg/ui/src/redux/nodes.ts [hunk 1]
```diff
@@ -185,7 +185,7 @@ export function sumNodeStats(
     unavailableRanges: 0,
     replicas: 0,
   };
-  if (_.isArray(nodeStatuses) && _.isObject(livenessStatusByNodeID)) {
+  if (_.isArray(nodeStatuses) && !_.isEmpty(livenessStatusByNodeID)) {
```
Comment (koorosh) [inline pkg/ui/src/redux/nodes.ts:188]: `livenessStatusByNodeID` is always an object that eiter have or don't have any fields.

File: pkg/ui/src/views/cluster/containers/nodeGraphs/index.tsx [hunk 2]
```diff
@@ -132,14 +135,10 @@ export class NodeGraphs extends React.Component<NodeGraphsProps, {}> {
...
 
-  refresh(props = this.props) {
-    if (!props.nodesQueryValid) {
-      props.refreshNodes();
-    }
-    if (!props.livenessQueryValid) {
-      props.refreshLiveness();
-    }
-  }
+  refresh = () => {
```
Comment (koorosh) [inline pkg/ui/src/views/cluster/containers/nodeGraphs/index.tsx:138]: `nodesQueryValid` and `livenessQueryValid` validations are performed in `CachedDataReducer` when call refresh for any resource.

**Review by dhartunian — CHANGES_REQUESTED** [review]
> So this state
> is possible only when no liveness statuses were requested from server yet.

We have a `state.inFlight` state that `cachedDataReducer` maintains. Can that be used to render a loading state while we fetch the liveness statuses? Or maybe the `valid` status can help too. 
https://github.com/cockroachdb/cockroach/blob/master/pkg/ui/src/redux/cachedDataReducer.ts#L31-L38
Can we track that information more explicitly instead of relying on an "empty object"?

> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/61000#-:-MUFATs83KVkjzDYJf-d:b-6mxwf4)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @koorosh)

___
*[pkg/ui/src/redux/nodes.ts, line 168 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/61000#-MUEOwx7EjnBFC2WzgsW:-MUEOwx7EjnBFC2WzgsX:b-cw50ex) ([raw file](https://github.com/cockroachdb/cockroach/blob/b9faf6a5a4bdcf3448e5e24f906babc5355b2098/pkg/ui/src/redux/nodes.ts#L168)):*
> ```XML
>   nodeStatuses: INodeStatus[],
>   livenessStatusByNodeID: { [id: string]: LivenessStatus },
> ) {
> ```

Can we add an explicit return type here for clarity?
___
*[pkg/ui/src/redux/nodes.ts, line 188 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/61000#-MUE71nb0Tvr163R3i59-r1-188:-MUFAtETEm2W4aXbZmFd:b-n9omvh) ([raw file](https://github.com/cockroachdb/cockroach/blob/b9faf6a5a4bdcf3448e5e24f906babc5355b2098/pkg/ui/src/redux/nodes.ts#L188)):*
<details><summary><i>Previously, koorosh (Andrii Vorobiov) wrote…</i></summary><blockquote>

`livenessStatusByNodeID` is always an object that eiter have or don't have any fields.
</blockquote></details>

This solution works but seems a bit hacky and it's unclear that `!_.isEmpty` is actually intending to capture the "not loaded yet" state. We should definitely keep this change but I'd like to see if we can track the loading status directly.

I made some suggestions in the main PR comment for some more explicit tracking of this information.
___
*[pkg/ui/src/views/cluster/containers/nodeGraphs/index.tsx, line 88 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/61000#-MUFBZP5ETCYnBYlRUez:-MUFBZP5ETCYnBYlRUf-:b-5jyegb) ([raw file](https://github.com/cockroachdb/cockroach/blob/b9faf6a5a4bdcf3448e5e24f906babc5355b2098/pkg/ui/src/views/cluster/containers/nodeGraphs/index.tsx#L88)):*
> ```XML
> });
> 
> type MapStateToProps = {
> ```

I like this simplification here, hopefully we can keep it :)

**Review by koorosh — COMMENTED** [review]
`inFlight` flag is set to true every time request is dispatched and will be triggered back with new data. In this case, we can use `valid` status which is set to `false` only when request is failed or no data available.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/61000#-:-MUS_c7nAAoVUQENLi0j:bse22lb)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dhartunian and @koorosh)

___
*[pkg/ui/src/redux/nodes.ts, line 168 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/61000#-MUEOwx7EjnBFC2WzgsW:-MUS_Xgk5ga-YgCtjmRq:bt1x36e) ([raw file](https://github.com/cockroachdb/cockroach/blob/b9faf6a5a4bdcf3448e5e24f906babc5355b2098/pkg/ui/src/redux/nodes.ts#L168)):*
<details><summary><i>Previously, dhartunian (David Hartunian) wrote…</i></summary><blockquote>

Can we add an explicit return type here for clarity?
</blockquote></details>

Sure, will do!
___
*[pkg/ui/src/redux/nodes.ts, line 188 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/61000#-MUE71nb0Tvr163R3i59-r1-188:-MUSWtql0Ke2bKsbJV2N:b-q9yd9u) ([raw file](https://github.com/cockroachdb/cockroach/blob/b9faf6a5a4bdcf3448e5e24f906babc5355b2098/pkg/ui/src/redux/nodes.ts#L188)):*
<details><summary><i>Previously, dhartunian (David Hartunian) wrote…</i></summary><blockquote>

This solution works but seems a bit hacky and it's unclear that `!_.isEmpty` is actually intending to capture the "not loaded yet" state. We should definitely keep this change but I'd like to see if we can track the loading status directly.

I made some suggestions in the main PR comment for some more explicit tracking of this information.
</blockquote></details>

I agree that it's not obvious, but in scope of `sumNodeStats` function - it shouldn't have any knowledge about "not yet loaded" states I assume. This function always returns an `NodeSummaryStats` object depending on provided inputs. In case of empty statuses - it returns zero-ed object.
To track loading status, I suggest to add explicit props in `ClusterNodeTotals` component that will indicate whether data is ready or not.

**Review by dhartunian — APPROVED** [review]
:lgtm: just needs a release justification before merge. thanks!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/61000#-:-MUi2CqtBhdSjzOZexJe:bilw6td)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @dhartunian)
