### PR TITLE
sql: apply PCR AOST time stamp for authentication flow

### LINKED ISSUE #135829: crosscluster/physical: prepared statement evaluation fails in read from standby workload
If I attempt to start a workload on a read only standby cluster, the workload logs return log messages which suggest prepared statement evaluation failed:
```
W241120 14:45:36.803837 230 workload/pgx_helpers.go:235  [-] 6  error preparing statement. name=kv-2 sql=SELECT k, v FROM kv AS OF SYSTEM TIME follower_read_timestamp() WHERE k IN ($1) ERROR: relation "kv" does not exist (SQLSTATE 42P01)
W241120 14:45:36.803837 187 workload/pgx_helpers.go:235  [-] 7  error preparing statement. name=kv-2 sql=SELECT k, v FROM kv AS OF SYSTEM TIME follower_read_timestamp() WHERE k IN ($1) ERROR: relation "kv" does not exist (SQLSTATE 42P01)
W241120 14:45:36.806227 228 workload/pgx_helpers.go:235  [-] 8  error preparing statement. name=kv-2 sql=SELECT k, v FROM kv AS OF SYSTEM TIME follower_read_timestamp() WHERE k IN ($1) ERROR: relation "kv" does not exist (SQLSTATE 42P01)
W241120 14:45:36.810050 188 workload/pgx_helpers.go:235  [-] 9  error preparing statement. name=kv-5 sql=DELETE FROM kv WHERE k IN ($1) ERROR: cannot mutate materialized view "kv" (SQLSTATE 42809)
W241120 14:45:36.810135 226 workload/pgx_helpers.go:235  [-] 10  error preparing statement. name=kv-5 sql=DELETE FROM kv WHERE k IN ($1) ERROR: cannot mutate materialized view "kv" (SQLSTATE 42809)
W241120 14:45:36.811199 190 workload/pgx_helpers.go:235  [-] 11  error preparing statement. name=kv-3 sql=UPSERT INTO kv (k, v) VALUES ($1, $2) ERROR: cannot mutate materialized view "kv" (SQLSTATE 42809)
W241120 14:45:36.811606 228 workload/pgx_helpers.go:235  [-] 12  error preparing statement. name=kv-5 sql=DELETE FROM kv WHERE k IN ($1) ERROR: cannot mutate materialized view "kv" (SQLSTATE 42809)
W241120 14:45:36.812236 193 workload/pgx_helpers.go:235  [-] 13  error preparing statement. name=kv-5 sql=DELETE FROM kv WHERE k IN ($1) ERROR: cannot mutate materialized view "kv" (SQLSTATE 42809)
```

In addition, the cockroach log stacks below suggest the sql authentication checks are failing on the standby workload. It's unclear if these checks are firing during prepared statement evaluation.

The stack below suggests that `GetUserSessionInitInfo` is hitting this assertion failure
https://github.com/msbutler/cockroach/blob/butler-public-disk-full/pkg/sql/catalog/descs/leased_descriptors.go#L154

Which implies that this `GetUserSessionInitInfo`  func has a connExecutor not using a historical queries, as enforced by [[this PR](https://github.com/cockroachdb/cockroach/commit/6c361b9a9a526bd9bacb9a7cc41b2bbb92e51899#diff-e10255c339480f882118842fb00bc6a10857be5bf2aa1bf09a1fd5f8ace7bd44)](https://github.com/cockroachdb/cockroach/commit/6c361b9a9a526bd9bacb9a7cc41b2bbb92e51899#diff-e10255c339480f882118842fb00bc6a10857be5bf2aa1bf09a1fd5f8ace7bd44).

I can also see in the stack trace that the a cache is being used to retrieve session data, so perhaps this cache was hydrated without historical queries. 

Other notes:
- even after restarting the workload after an hour, the same PCR reader timestamps are surfaced by the error: `existing descriptor ‹role_options›(33) and timestamp: 1732113915.000000000,0 new descritpor ‹users›(4) and timestamp: 1732113960.000000000,0`
- if I open a sql connection to the destination tenant, **i can run queries without a problem**, even while logged in as the roachprod user. 
- to reproduce, you can run  `roachtest run c2c/kv0 --cluster=$CLUSTER --cockroach=cockroach --run-skipped --debug-always` after building the roachtest binary on this [wip pr
](https://github.com/cockroachdb/cockroach/pull/135838)

```
W241120 14:46:22.527772 107414 sql/pgwire/auth.go:161 ⋮ [T4,Vdestination-tenant-readonly,n3,client=10.142.0.177:48093,hostssl,user=‹roachprod›] 340  user retrieval failed for user=‹"roachprod"›: internal error while retrieving user account memberships: internal error while retrieving user account: get auth info error: PCR reader timestamp has moved forward, existing descriptor ‹role_options›(33) and timestamp: 1732113915.000000000,0 new descritpor ‹users›(4) and timestamp: 1732113960.000000000,0
W241120 14:46:22.527772 107414 sql/pgwire/auth.go:161 ⋮ [T4,Vdestination-tenant-readonly,n3,client=10.142.0.177:48093,hostssl,user=‹roachprod›] 340 +(1) attached stack trace
W241120 14:46:22.527772 107414 sql/pgwire/auth.go:161 ⋮ [T4,Vdestination-tenant-readonly,n3,client=10.142.0.177:48093,hostssl,user=‹roachprod›] 340 +  -- stack trace:
W241120 14:46:22.527772 107414 sql/pgwire/auth.go:161 ⋮ [T4,Vdestination-tenant-readonly,n3,client=10.142.0.177:48093,hostssl,user=‹roachprod›] 340 +  | github.com/cockroachdb/cockroach/pkg/sql.GetUserSessionInitInfo
W241120 14:46:22.527772 107414 sql/pgwire/auth.go:161 ⋮ [T4,Vdestination-tenant-readonly,n3,client=10.142.0.177:48093,hostssl,user=‹roachprod›] 340 +  |        pkg/sql/user.go:197
W241120 14:46:22.527772 107414 sql/pgwire/auth.go:161 ⋮ [T4,Vdestination-tenant-readonly,n3,client=10.142.0.177:48093,hostssl,user=‹roachprod›] 340 +  | github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*conn).handleAuthentication
W241120 14:46:22.527772 107414 sql/pgwire/auth.go:161 ⋮ [T4,Vdestination-tenant-readonly,n3,client=10.142.0.177:48093,hostssl,user=‹roachprod›] 340 +  |        pkg/sql/pgwire/auth.go:154
W241120 14:46:22.527772 107414 sql/pgwire/auth.go:161 ⋮ [T4,Vdestination-tenant-readonly,n3,client=10.142.0.177:48093,hostssl,user=‹roachprod›] 340 +  | github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*conn).processCommands
W241120 14:46:22.527772 107414 sql/pgwire/auth.go:161 ⋮ [T4,Vdestination-tenant-readonly,n3,client=10.142.0.177:48093,hostssl,user=‹roachprod›] 340 +  |        pkg/sql/pgwire/conn.go:203
W241120 14:46:22.527772 107414 sql/pgwire/auth.go:161 ⋮ [T4,Vdestination-tenant-readonly,n3,client=10.142.0.177:48093,hostssl,user=‹roachprod›] 340 +  | github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*Server).serveImpl.func4
W241120 14:46:22.527772 107414 sql/pgwire/auth.go:161 ⋮ [T4,Vdestination-tenant-readonly,n3,client=10.142.0.177:48093,hostssl,user=‹roachprod›] 340 +  |        pkg/sql/pgwire/server.go:1196
W241120 14:46:22.527772 107414 sql/pgwire/auth.go:161 ⋮ [T4,Vdestination-tenant-readonly,n3,client=10.142.0.177:48093,hostssl,user=‹roachprod›] 340 +  | runtime.goexit
W241120 14:46:22.527772 107414 sql/pgwire/auth.go:161 ⋮ [T4,Vdestination-tenant-readonly,n3,client=10.142.0.177:48093,hostssl,user=‹roachprod›] 340 +  |        src/runtime/asm_amd64.s:1695
W241120 14:46:22.527772 107414 sql/pgwire/auth.go:161 ⋮ [T4,Vdestination-tenant-readonly,n3,client=10.142.0.177:48093,hostssl,user=‹roachprod›] 340 +Wraps: (2) internal error while retrieving user account memberships
W241120 14:46:22.527772 107414 sql/pgwire/auth.go:161 ⋮ [T4,Vdestination-tenant-readonly,n3,client=10.142.0.177:48093,hostssl,user=‹roachprod›] 340 +Wraps: (3) internal error while retrieving user account: get auth info error: PCR reader timestamp has moved forward, existing descriptor ‹role_options›(33) and timestamp: 1732113915.000000000,0 new descritpor ‹users›(4) and timestamp: 1732113960.000000000,0
W241120 14:46:22.527772 107414 sql/pgwire/auth.go:161 ⋮ [T4,Vdestination-tenant-readonly,n3,client=10.142.0.177:48093,hostssl,user=‹roachprod›] 340 +  | -- cause hidden behind barrier
W241120 14:46:22.527772 107414 sql/pgwire/auth.go:161 ⋮ [T4,Vdestination-tenant-readonly,n3,client=10.142.0.177:48093,hostssl,user=‹roachprod›] 340 +  | internal error while retrieving user account: get auth info error: PCR reader timestamp has moved forward, existing descriptor ‹role_options›(33) and timestamp: 1732113915.000000000,0 new descritpor ‹users›(4) and timestamp: 1732113960.000000000,0
W241120 14:46:22.527772 107414 sql/pgwire/auth.go:161 ⋮ [T4,Vdestination-tenant-readonly,n3,client=10.142.0.177:48093,hostssl,user=‹roachprod›] 340 +  | (1) attached stack trace
W241120 14:46:22.527772 107414 sql/pgwire/auth.go:161 ⋮ [T4,Vdestination-tenant-readonly,n3,client=10.142.0.177:48093,hostssl,user=‹roachprod›] 340 +  |   -- stack trace:
search hit TOP, continuing at BOTTOM
W241120 16:01:37.762964 754710 sql/pgwire/auth.go:161 ⋮ [T4,Vdestination-tenant-readonly,n3,client=10.142.0.177:47312,hostssl,user=‹roachprod›] 5950 +  | github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*Server).serveImpl.func4
W241120 16:01:37.762964 754710 sql/pgwire/auth.go:161 ⋮ [T4,Vdestination-tenant-readonly,n3,client=10.142.0.177:47312,hostssl,user=‹roachprod›] 5950 +  |       pkg/sql/pgwire/server.go:1196
W241120 16:01:37.762964 754710 sql/pgwire/auth.go:161 ⋮ [T4,Vdestination-tenant-readonly,n3,client=10.142.0.177:47312,hostssl,user=‹roachprod›] 5950 +Wraps: (2) internal error while retrieving user account memberships
W241120 16:01:37.762964 754710 sql/pgwire/auth.go:161 ⋮ [T4,Vdestination-tenant-readonly,n3,client=10.142.0.177:47312,hostssl,user=‹roachprod›] 5950 +  | (1) attached stack trace
W241120 16:01:37.762964 754710 sql/pgwire/auth.go:161 ⋮ [T4,Vdestination-tenant-readonly,n3,client=10.142.0.177:47312,hostssl,user=‹roachprod›] 5950 +  |   |   pkg/sql/user.go:278
W241120 16:01:37.762964 754710 sql/pgwire/auth.go:161 ⋮ [T4,Vdestination-tenant-readonly,n3,client=10.142.0.177:47312,hostssl,user=‹roachprod›] 5950 +  |   | github.com/cockroachdb/cockroach/pkg/sql.GetUserSessionInitInfo.func2
W241120 16:01:37.762964 754710 sql/pgwire/auth.go:161 ⋮ [T4,Vdestination-tenant-readonly,n3,client=10.142.0.177:47312,hostssl,user=‹roachprod›] 5950 +  |   |   pkg/sql/user.go:123
W241120 16:01:37.762964 754710 sql/pgwire/auth.go:161 ⋮ [T4,Vdestination-tenant-readonly,n3,client=10.142.0.177:47312,hostssl,user=‹roachprod›] 5950 +  |   | github.com/cockroachdb/cockroach/pkg/util/timeutil.RunWithTimeout
W241120 16:01:37.762964 754710 sql/pgwire/auth.go:161 ⋮ [T4,Vdestination-tenant-readonly,n3,client=10.142.0.177:47312,hostssl,user=‹roachprod›] 5950 +  |   |   pkg/util/timeutil/timeout.go:28
W241120 16:01:37.762964 754710 sql/pgwire/auth.go:161 ⋮ [T4,Vdestination-tenant-readonly,n3,client=10.142.0.177:47312,hostssl,user=‹roachprod›] 5950 +  |   | github.com/cockroachdb/cockroach/pkg/sql.getUserInfoRunFn.func2
W241120 16:01:37.762964 754710 sql/pgwire/auth.go:161 ⋮ [T4,Vdestination-tenant-readonly,n3,client=10.142.0.177:47312,hostssl,user=‹roachprod›] 5950 +  |   |   pkg/sql/user.go:242
W241120 16:01:37.762964 754710 sql/pgwire/auth.go:161 ⋮ [T4,Vdestination-tenant-readonly,n3,client=10.142.0.177:47312,hostssl,user=‹roachprod›] 5950 +  |   | github.com/cockroachdb/cockroach/pkg/sql.GetUserSessionInitInfo
W241120 16:01:37.762964 754710 sql/pgwire/auth.go:161 ⋮ [T4,Vdestination-tenant-readonly,n3,client=10.142.0.177:47312,hostssl,user=‹roachprod›] 5950 +  |   |   pkg/sql/user.go:120
W241120 16:01:37.762964 754710 sql/pgwire/auth.go:161 ⋮ [T4,Vdestination-tenant-readonly,n3,client=10.142.0.177:47312,hostssl,user=‹roachprod›] 5950 +  |   | github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*conn).handleAuthentication
W241120 16:01:37.762964 754710 sql/pgwire/auth.go:161 ⋮ [T4,Vdestination-tenant-readonly,n3,client=10.142.0.177:47312,hostssl,user=‹roachprod›] 5950 +  |   |   pkg/sql/pgwire/auth.go:154
W241120 16:01:37.762964 754710 sql/pgwire/auth.go:161 ⋮ [T4,Vdestination-tenant-readonly,n3,client=10.142.0.177:47312,hostssl,user=‹roachprod›] 5950 +  |   | github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*conn).processCommands
W241120 16:01:37.762964 754710 sql/pgwire/auth.go:161 ⋮ [T4,Vdestination-tenant-readonly,n3,client=10.142.0.177:47312,hostssl,user=‹roachprod›] 5950 +  |   |   pkg/sql/pgwire/conn.go:203
W241120 16:01:37.762964 754710 sql/pgwire/auth.go:161 ⋮ [T4,Vdestination-tenant-readonly,n3,client=10.142.0.177:47312,hostssl,user=‹roachprod›] 5950 +  |   | github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*Server).serveImpl.func4
W241120 16:01:37.762964 754710 sql/pgwire/auth.go:161 ⋮ [T4,Vdestination-tenant-readonly,n3,client=10.142.0.177:47312,hostssl,user=‹roachprod›] 5950 +  |   |   pkg/sql/pgwire/server.go:1196
W241120 16:01:37.762964 754710 sql/pgwire/auth.go:161 ⋮ [T4,Vdestination-tenant-readonly,n3,client=10.142.0.177:47312,hostssl,user=‹roachprod›] 5950 +  |   | runtime.goexit
W241120 16:01:37.762964 754710 sql/pgwire/auth.go:161 ⋮ [T4,Vdestination-tenant-readonly,n3,client=10.142.0.177:47312,hostssl,user=‹roachprod›] 5950 +  |   |   src/runtime/asm_amd64.s:1695
W241120 16:01:37.762964 754710 sql/pgwire/auth.go:161 ⋮ [T4,Vdestination-tenant-readonly,n3,client=10.142.0.177:47312,hostssl,user=‹roachprod›] 5950 +  | Wraps: (2) internal error while retrieving user account
W241120 16:01:37.762964 754710 sql/pgwire/auth.go:161 ⋮ [T4,Vdestination-tenant-readonly,n3,client=10.142.0.177:47312,hostssl,user=‹roachprod›] 5950 +  | Wraps: (3) get auth info error: PCR reader timestamp has moved forward, existing descriptor ‹role_options›(33) and timestamp: 1732118450.000000000,0 new descritpor ‹users›(4) and timestamp: 1732118465.000000000,0
W241120 16:01:37.762964 754710 sql/pgwire/auth.go:161 ⋮ [T4,Vdestination-tenant-readonly,n3,client=10.142.0.177:47312,hostssl,user=‹roachprod›] 5950 +  |   | -- cause hidden behind barrier
W241120 16:01:37.762964 754710 sql/pgwire/auth.go:161 ⋮ [T4,Vdestination-tenant-readonly,n3,client=10.142.0.177:47312,hostssl,user=‹roachprod›] 5950 +  |   | get auth info error: PCR reader timestamp has moved forward, existing descriptor ‹role_options›(33) and timestamp: 1732118450.000000000,0 new descritpor ‹users›(4) and timestamp: 1732118465.000000000,0
W241120 16:01:37.762964 754710 sql/pgwire/auth.go:161 ⋮ [T4,Vdestination-tenant-readonly,n3,client=10.142.0.177:47312,hostssl,user=‹roachprod›] 5950 +  |   | (1) attached stack trace
W241120 16:01:37.762964 754710 sql/pgwire/auth.go:161 ⋮ [T4,Vdestination-tenant-readonly,n3,client=10.142.0.177:47312,hostssl,user=‹roachprod›] 5950 +  |   |   -- stack trace:
W241120 16:01:37.762964 754710 sql/pgwire/auth.go:161 ⋮ [T4,Vdestination-tenant-readonly,n3,client=10.142.0.177:47312,hostssl,user=‹roachprod›] 5950 +  |   |   | github.com/cockroachdb/cockroach/pkg/sql.retrieveSessionInitInfoWithCache.func1
W241120 16:01:37.762964 754710 sql/pgwire/auth.go:161 ⋮ [T4,Vdestination-tenant-readonly,n3,client=10.142.0.177:47312,hostssl,user=‹roachprod›] 5950 +  |   |   |       pkg/sql/user.go:260
W241120 16:01:37.762964 754710 sql/pgwire/auth.go:161 ⋮ [T4,Vdestination-tenant-readonly,n3,client=10.142.0.177:47312,hostssl,user=‹roachprod›] 5950 +  |   |   | github.com/cockroachdb/cockroach/pkg/sql.retrieveSessionInitInfoWithCache
W241120 16:01:37.762964 754710 sql/pgwire/auth.go:161 ⋮ [T4,Vdestination-tenant-readonly,n3,client=10.142.0.177:47312,hostssl,user=‹roachprod›] 5950 +  |   |   |       pkg/sql/user.go:275
W241120 16:01:37.762964 754710 sql/pgwire/auth.go:161 ⋮ [T4,Vdestination-tenant-readonly,n3,client=10.142.0.177:47312,hostssl,user=‹roachprod›] 5950 +  |   |   | github.com/cockroachdb/cockroach/pkg/sql.GetUserSessionInitInfo.func2
W241120 16:01:37.762964 754710 sql/pgwire/auth.go:161 ⋮ [T4,Vdestination-tenant-readonly,n3,client=10.142.0.177:47312,hostssl,user=‹roachprod›] 5950 +  |   |   |       pkg/sql/user.go:123
W241120 16:01:37.762964 754710 sql/pgwire/auth.go:161 ⋮ [T4,Vdestination-tenant-readonly,n3,client=10.142.0.177:47312,hostssl,user=‹roachprod›] 5950 +  |   |   | github.com/cockroachdb/cockroach/pkg/util/timeutil.RunWithTimeout
W241120 16:01:37.762964 754710 sql/pgwire/auth.go:161 ⋮ [T4,Vdestination-tenant-readonly,n3,client=10.142.0.177:47312,hostssl,user=‹roachprod›] 5950 +  |   |   |       pkg/util/timeutil/timeout.go:28
W241120 16:01:37.762964 754710 sql/pgwire/auth.go:161 ⋮ [T4,Vdestination-tenant-readonly,n3,client=10.142.0.177:47312,hostssl,user=‹roachprod›] 5950 +  |   |   | github.com/cockroachdb/cockroach/pkg/sql.getUserInfoRunFn.func2
W241120 16:01:37.762964 754710 sql/pgwire/auth.go:161 ⋮ [T4,Vdestination-tenant-readonly,n3,client=10.142.0.177:47312,hostssl,user=‹roachprod›] 5950 +  |   |   |       pkg/sql/user.go:242
W241120 16:01:37.762964 754710 sql/pgwire/auth.go:161 ⋮ [T4,Vdestination-tenant-readonly,n3,client=10.142.0.177:47312,hostssl,user=‹roachprod›] 5950 +  |   |   | github.com/cockroachdb/cockroach/pkg/sql.GetUserSessionInitInfo
W241120 16:01:37.762964 754710 sql/pgwire/auth.go:161 ⋮ [T4,Vdestination-tenant-readonly,n3,client=10.142.0.177:47312,hostssl,user=‹roachprod›] 5950 +  |   |   |       pkg/sql/user.go:120
W241120 16:01:37.762964 754710 sql/pgwire/auth.go:161 ⋮ [T4,Vdestination-tenant-readonly,n3,client=10.142.0.177:47312,hostssl,user=‹roachprod›] 5950 +  |   |   | github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*conn).handleAuthentication
W241120 16:01:37.762964 754710 sql/pgwire/auth.go:161 ⋮ [T4,Vdestination-tenant-readonly,n3,client=10.142.0.177:47312,hostssl,user=‹roachprod›] 5950 +  |   |   |       pkg/sql/pgwire/auth.go:154
W241120 16:01:37.762964 754710 sql/pgwire/auth.go:161 ⋮ [T4,Vdestination-tenant-readonly,n3,client=10.142.0.177:47312,hostssl,user=‹roachprod›] 5950 +  |   |   | github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*conn).processCommands
W241120 16:01:37.762964 754710 sql/pgwire/auth.go:161 ⋮ [T4,Vdestination-tenant-readonly,n3,client=10.142.0.177:47312,hostssl,user=‹roachprod›] 5950 +  |   |   |       pkg/sql/pgwire/conn.go:203
W241120 16:01:37.762964 754710 sql/pgwire/auth.go:161 ⋮ [T4,Vdestination-tenant-readonly,n3,client=10.142.0.177:47312,hostssl,user=‹roachprod›] 5950 +  |   |   | github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*Server).serveImpl.func4
W241120 16:01:37.762964 754710 sql/pgwire/auth.go:161 ⋮ [T4,Vdestination-tenant-readonly,n3,client=10.142.0.177:47312,hostssl,user=‹roachprod›] 5950 +  |   |   |       pkg/sql/pgwire/server.go:1196
W241120 16:01:37.762964 754710 sql/pgwire/auth.go:161 ⋮ [T4,Vdestination-tenant-readonly,n3,client=10.142.0.177:47312,hostssl,user=‹roachprod›] 5950 +  |   |   | runtime.goexit
W241120 16:01:37.762964 754710 sql/pgwire/auth.go:161 ⋮ [T4,Vdestination-tenant-readonly,n3,client=10.142.0.177:47312,hostssl,user=‹roachprod›] 5950 +  |   |   |       src/runtime/asm_amd64.s:1695
W241120 16:01:37.762964 754710 sql/pgwire/auth.go:161 ⋮ [T4,Vdestination-tenant-readonly,n3,client=10.142.0.177:47312,hostssl,user=‹roachprod›] 5950 +  |   | Wraps: (2) get auth info error
W241120 16:01:37.762964 754710 sql/pgwire/auth.go:161 ⋮ [T4,Vdestination-tenant-readonly,n3,client=10.142.0.177:47312,hostssl,user=‹roachprod›] 5950 +  |   | Wraps: (3) PCR reader timestamp has moved forward, existing descriptor ‹role_options›(33) and timestamp: 1732118450.000000000,0 new descritpor ‹users›(4) and timestamp: 1732118465.000000000,0
```

Jira issue: CRDB-44743

Epic CRDB-43310

### PR DESCRIPTION
**Pull request by fqazi**
Previously, when using PCR reader catalog its was possible to hit "PCR reader timestamp has moved forward" when attempting to execute workloads. This was because internal executors are exempt from the AOST timestamp. To address this, the authentication code paths are updated to set fixed timestamps, when connecting to a PCR reader catalog. Additionally, additional tests are added for validating opening new connections and preparing queries to confirm this problem is fixed.

Fixes: #135829

Release note: None

### CODE REVIEW

File: pkg/sql/catalog/replication/reader_catalog_test.go [hunk 1]
```diff
@@ -322,6 +328,16 @@ func TestReaderCatalogTSAdvance(t *testing.T) {
 		} else {
 			require.NotEqualValues(t, srcRes, destRes)
 		}
+
+		// Sanity: Execute the same query as prepared statement inside the reader
```
Comment (msbutler) [inline pkg/sql/catalog/replication/reader_catalog_test.go:332]: to confirm, were these unit tests with prepared stmts failing before your patch to the source code?

File: pkg/sql/catalog/replication/reader_catalog_test.go [hunk 2]
```diff
@@ -432,7 +473,7 @@ func TestReaderCatalogTSAdvance(t *testing.T) {
 // with PCR even if a long running txn is running.
 func TestReaderCatalogTSAdvanceWithLongTxn(t *testing.T) {
 	defer leaktest.AfterTest(t)()
-	skip.UnderDuress(t)
+	//	skip.UnderDuress(t)
```
Comment (msbutler) [inline pkg/sql/catalog/replication/reader_catalog_test.go:476]: nit: intended?

**Review by msbutler — COMMENTED** [review]
thanks for the patch!! I'll try running my roachtest on top of this. I'll let someone from foundations approve this. 

One other thought: I wonder if there's a more general way to find other internal executor read queries that require a fixed timestamp. Or maybe this points to a larger design problem: perhaps no system tables should be externalized. cc @dt

File: pkg/sql/catalog/replication/reader_catalog_test.go (hunk 1 above)
Comment (fqazi) [reply pkg/sql/catalog/replication/reader_catalog_test.go:332]: I didn't see any issues on the prepared statements, but opening new connections could fail intermittently.

**Review by fqazi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/135929)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @dt and @msbutler)

File: pkg/sql/user.go [hunk 3]
```diff
@@ -288,92 +291,98 @@ func retrieveAuthInfo(
...
+		const getLoginDependencies = `SELECT option, value FROM system.public.role_options ` +
+			`WHERE username=$1 AND option IN ('NOLOGIN', 'VALID UNTIL', 'NOSQLLOGIN', 'REPLICATION', 'SUBJECT')`
 
-	// To support users created before 20.1, allow all USERS/ROLES to login
-	// if NOLOGIN is not found.
-	aInfo.CanLoginSQLRoleOpt = true
-	aInfo.CanLoginDBConsoleRoleOpt = true
-	var ok bool
+		roleOptsIt, err := txn.QueryIteratorEx(
+			ctx, "get-login-dependencies", txn.KV(), /* txn */
```
Comment (msbutler) [inline pkg/sql/user.go:330]: you're fixing this in this PR, but it seems a bit odd that we previously grabbed the login dependencies in a separate txn than the hashed password.

File: pkg/sql/catalog/replication/reader_catalog_test.go [hunk 4]
```diff
@@ -409,6 +410,9 @@ func TestReaderCatalogTSAdvance(t *testing.T) {
 		for !iterationsDone {
 			uniqueIdx++
 			if !useAOST {
+				// Toggle the block on each iteration, so there is some risk
+				// of not all descriptor updates being updated.
+				descriptorRefreshHookEnabled.Swap(true)
```
Comment (msbutler) [inline pkg/sql/catalog/replication/reader_catalog_test.go:415]: I'm finding it hard to reason through all the components of this test, perhaps because i'm unfamiliar with the LeaseManager hooks you're using. Perhaps in a follow up PR after we fix the bug, we could break this test up into a few smaller tests that are easier to understand.

**Review by msbutler — APPROVED** [review]
Thanks again for doing this! Also, are you ok backporting this to 24.3?

File: pkg/sql/user.go (hunk 3 above)
Comment (fqazi) [reply pkg/sql/user.go:330]: Yeah,  I think it was just a subtle miss. I don't think it was because the txn complexity would be too high here, since their both scanning for one row.

File: pkg/sql/catalog/replication/reader_catalog_test.go (hunk 4 above)
Comment (fqazi) [reply pkg/sql/catalog/replication/reader_catalog_test.go:415]: Fair point, and I think a bunch of code can be shared here too. I opened: #136114 for tracking

**Review by fqazi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/135929)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @dt and @msbutler)

**Review by rafiss — CHANGES_REQUESTED** [review]
nice work!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/135929#-:-OCd7_n676eotCcs0IML:b-j4xmku)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @dt, @fqazi, and @msbutler)

___
*[`pkg/sql/user.go` line 290 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/135929#-OCd6-Sb89JbyZkXYUMQ:-OCd6-Sb89JbyZkXYUMR:b-ktg4kf) ([raw file](https://github.com/cockroachdb/cockroach/blob/0ebda72436fb188f432a86d97ccc46bf82777023/pkg/sql/user.go#L290)):*
> ```Go
> ) (aInfo sessioninit.AuthInfo, retErr error) {
> 	// Use fully qualified table name to avoid looking up "".system.users.
> 	// We use a nil txn as login is not tied to any transaction state, and
> ```

can you update this comment to explain that we use a DescsTxn and have it describe why we need `MaybeSetReplicationSafeTS`?
___
*[`pkg/sql/user.go` line 303 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/135929#-OCd764a-TLKlWpfFftk:-OCd764bC8fvOxPfjHkC:b-3jhmdz) ([raw file](https://github.com/cockroachdb/cockroach/blob/0ebda72436fb188f432a86d97ccc46bf82777023/pkg/sql/user.go#L303)):*
> ```Go
> 			getHashedPassword, user)
> 		if err != nil {
> 			return err
> ```

nit: why remove the `errors.Wrap` here?
___
*[`pkg/sql/user.go` line 349 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/135929#-OCd6dvM8XWlkNe1rDe4:-OCd6dvM8XWlkNe1rDe5:b-qd1vi6) ([raw file](https://github.com/cockroachdb/cockroach/blob/0ebda72436fb188f432a86d97ccc46bf82777023/pkg/sql/user.go#L349)):*
> ```Go
> 		var ok bool
> 
> 		for ok, err = roleOptsIt.Next(ctx); ok; ok, err = roleOptsIt.Next(ctx) {
> ```

could you introduce a `var loopErr error` variable? it makes the error handling a bit easier to read
___
*[`pkg/sql/user.go` line 384 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/135929#-OCd6kZHDCIC93_sO11i:-OCd6kZHDCIC93_sO11j:bxtvnub) ([raw file](https://github.com/cockroachdb/cockroach/blob/0ebda72436fb188f432a86d97ccc46bf82777023/pkg/sql/user.go#L384)):*
> ```Go
> 			}
> 		}
> 		return err
> ```

super nit: change to 
```
if loopErr != nil {
  return loopErr
}
return nil
```

File: pkg/sql/user.go (hunk 3 above)
Comment (fqazi) [reply pkg/sql/user.go:338]: Done.

Also added:

// We are going to use a single txn for resolving the user information,  
// and role\_options for the user.

**Review by fqazi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/135929)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @dt, @msbutler, and @rafiss)

___
*[`pkg/sql/user.go` line 290 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/135929#-OCd6-Sb89JbyZkXYUMQ:-OCfRC7uDKUraYhBES2l:bvhzo6t) ([raw file](https://github.com/cockroachdb/cockroach/blob/0ebda72436fb188f432a86d97ccc46bf82777023/pkg/sql/user.go#L290)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

can you update this comment to explain that we use a DescsTxn and have it describe why we need `MaybeSetReplicationSafeTS`?
</blockquote></details>

Done. 

Added the comment:

// When running on a PCR reader catalog we need to ensure all descriptors  
// have matching timestamps for external row data. Certain system tables  
// like users and role\_options are replicated, which can cause mixed  
// external row data timestamps, which can lead to a retryable error.  
// To avoid this we will set a replication safe AOST timestamp when running  
// on a reader catalog.
___
*[`pkg/sql/user.go` line 303 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/135929#-OCd764a-TLKlWpfFftk:-OCfPokoB4GvfZEJ061b:bqstdq7) ([raw file](https://github.com/cockroachdb/cockroach/blob/0ebda72436fb188f432a86d97ccc46bf82777023/pkg/sql/user.go#L303)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

nit: why remove the `errors.Wrap` here?
</blockquote></details>

Done.

That was accidental, good catch.
___
*[`pkg/sql/user.go` line 349 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/135929#-OCd6dvM8XWlkNe1rDe4:-OCfQNHT63D2m-qJWESV:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/0ebda72436fb188f432a86d97ccc46bf82777023/pkg/sql/user.go#L349)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

could you introduce a `var loopErr error` variable? it makes the error handling a bit easier to read
</blockquote></details>

Done.
___
*[`pkg/sql/user.go` line 384 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/135929#-OCd6kZHDCIC93_sO11i:-OCfQSEJ6BlsvcF03zlt:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/0ebda72436fb188f432a86d97ccc46bf82777023/pkg/sql/user.go#L384)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

super nit: change to 
```
if loopErr != nil {
  return loopErr
}
return nil
```
</blockquote></details>

Done.

**Review by rafiss — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/135929)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @dt, @fqazi, and @msbutler)

___
*[`pkg/sql/user.go` line 290 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/135929#-OCjVKQR-h6OKf6yqKl7:-OCjVKQR-h6OKf6yqKl8:b-l51k8m) ([raw file](https://github.com/cockroachdb/cockroach/blob/6659ceca3803cc3938b1bbc9bc0a9d37d0202a1c/pkg/sql/user.go#L290)):*
> ```Go
> ) (aInfo sessioninit.AuthInfo, retErr error) {
> 	// Use fully qualified table name to avoid looking up "".system.users.
> 	// We use a nil txn as login is not tied to any transaction state, and
> ```

super nit: remove the words about using a `nil txn`

**Comment by fqazi** [comment]
@msbutler @rafiss TFTR!

bors r+
