### PR TITLE
sql: fix excess privileges being created from default privileges.

### LINKED ISSUE #72322: sql: default privileges, granting excess privileges when creating an object
```
create user foo with password 'roach';
# login as foo
alter default privileges grant select on tables to foo
# login as root
create table t1();
show grants on table t1;

root@localhost:26257/defaultdb> show grants on table t1;
  database_name | schema_name | table_name | grantee | privilege_type
----------------+-------------+------------+---------+-----------------
  defaultdb     | public      | t1         | admin   | ALL
  defaultdb     | public      | t1         | foo    | SELECT
  defaultdb     | public      | t1         | root    | ALL
```

We're granting too many privileges when creating an object due to default privileges - in this case, foo should not be getting select on this table

### PR DESCRIPTION
**Pull request by RichardJCai**
Release note (bug fix): Previously, when creating an object
default privileges from users that were not the user creating
the object would be added to the privileges of the object.
This fix ensures only the relevant default privileges are applied.

Resolves https://github.com/cockroachdb/cockroach/issues/72322

### CODE REVIEW

File: pkg/sql/catalog/catprivilege/default_privilege.go [hunk 1]
```diff
@@ -148,28 +148,35 @@ func (d *immutable) CreatePrivilegesFromDefaultPrivileges(
 	// If default privileges are not defined for the creator role, we handle
 	// it as the default case where the user has all privileges.
 	role := descpb.DefaultPrivilegesRole{Role: user}
-	if _, found := d.GetDefaultPrivilegesForRole(role); !found {
+	if defaultPrivilegesForRole, found := d.GetDefaultPrivilegesForRole(role); !found {
```
Comment (rafiss) [inline pkg/sql/catalog/catprivilege/default_privilege.go:151]: does the comment above need adjusting?

Comment (RichardJCai) [reply pkg/sql/catalog/catprivilege/default_privilege.go:151]: No this is still accurate but it might be more fitting to put this into the `if !found` clause? Thoughts?

Comment (rafiss) [reply pkg/sql/catalog/catprivilege/default_privilege.go:151]: yeah i'm in favor of putting it inside of `if !found` and then one more comment inside of the `else`

**Review by rafiss — APPROVED** [review]
lgtm after commenting

**Review by ajwerner — APPROVED** [review]
:lgtm: 

Part of me wonders if the thing we were missing here was table-driven unit testing of the functions in `catprivilege`.

> Reviewed 1 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/72323#-:-MnWfYw16amwp3WhqIOx:b-rz7zs5)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ajwerner, @rafiss, and @RichardJCai)

**Comment by RichardJCai** [comment]
TFTR! 
bors r+

**Comment by RichardJCai** [comment]
> :lgtm: 
> 
> Part of me wonders if the thing we were missing here was table-driven unit testing of the functions in `catprivilege`.
> 
> > Reviewed 1 of 2 files at r1.
> > *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/72323#-:-MnWfYw16amwp3WhqIOx:b-rz7zs5)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ajwerner, @rafiss, and @RichardJCai)
> 
> 
> 
> 
> 

Yeah we're definitely missing some unit tests here. I'll add some in, this isn't good

**Comment by RichardJCai** [comment]
Looks like the test failure is a flake.
bors r+
