### PR TITLE
sql: fix error message for ALTER SEQUENCE OWNED BY

### LINKED ISSUE #56347: sql: bad error message for sequence ownership change to nonexistent object
```
demo@127.0.0.1:59385/defaultdb> create sequence test;
CREATE SEQUENCE

Time: 3ms total (execution 3ms / network 0ms)

demo@127.0.0.1:59385/defaultdb> alter sequence test owned by doesntexist;
ERROR: relation "" does not exist
SQLSTATE: 42P01
```

The last error message doesn't look right.

### PR DESCRIPTION
**Pull request by rafiss**
This matches the error and hint that PostgreSQL returns.

fixes #56347 

Release note: None

### CODE REVIEW

File: pkg/sql/sequence.go [hunk 1]
```diff
@@ -432,6 +432,9 @@ func resolveColumnItemToDescriptors(
 	var tableName tree.TableName
 	if columnItem.TableName != nil {
```
Comment (RichardJCai) [inline pkg/sql/sequence.go:433]: Super nit: does it make more sense to do 
```
if columnItem.tableName == nil {
  return error...
}

tableName = columnItem.TableName.ToTableName()
```

**Review by RichardJCai — APPROVED** [review]

File: pkg/sql/sequence.go (hunk 1 above)
Comment (rafiss) [reply pkg/sql/sequence.go:433]: yes for sure! thanks for the catch

**Comment by rafiss** [comment]
bors r=RichardJCai
