### PR TITLE
collatedstring: support default, C, and POSIX in expressions

### LINKED ISSUE #50734: sql: support COLLATE "default" in SELECT queries
Postgres allows a `COLLATE` clause to appear at the end of an expression. See: https://www.postgresql.org/docs/12/sql-expressions.html#SQL-SYNTAX-COLLATE-EXPRS

CockroachDB doesn't support `COLLATE` in general right now, but some tools (e.g. Prisma) use `COLLATE "default"` in their queries, which it seems does not differ from the behavior of not having any `COLLATE` clause at all.

CockroachDB should support a default `COLLATE` expression.

Jira issue: CRDB-4095

### LINKED ISSUE #95667: "invalid locale C: language: tag is not well-formed" when using cast with COLLATE
**To Reproduce**

```python
import psycopg2

print(psycopg2.__version__)  # 2.9.5 (dt dec pq3 ext lo64)

sql = """\
SELECT pg_catalog.pg_class.relname
FROM pg_catalog.pg_class
WHERE pg_catalog.pg_class.relkind = 'foo'::VARCHAR(64) COLLATE "C"
"""

# okay with PostgreSQL
#
pg_cnxn = psycopg2.connect(
    "host=192.168.0.199 dbname=test user=scott password=tiger"
)
crsr = pg_cnxn.cursor()
crsr.execute("SELECT version()")
print(crsr.fetchall())
# [('PostgreSQL 12.3 (Debian 12.3-1.pgdg100+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 8.3.0-6) 8.3.0, 64-bit',)]
crsr.execute(sql)
print(crsr.fetchall())  # []

# error with CockroachDB
#
cr_cnxn = psycopg2.connect(
    "host=localhost port=26257 dbname=defaultdb user=root"
)
crsr = cr_cnxn.cursor()
crsr.execute("SELECT version()")
print(crsr.fetchall())
# [('CockroachDB CCL v22.2.2 (x86_64-pc-linux-gnu, built 2023/01/04 17:23:00, go1.19.1)',)]
crsr.execute(sql)
"""
Traceback (most recent call last):
  File "/home/gord/git/sqlalchemy-cockroachdb/gord_test/collate_issue.py", line 32, in <module>
    crsr.execute(sql)
psycopg2.errors.InvalidParameterValue: invalid locale C: language: tag is not well-formed
"""
```

**Environment**
 - CockroachDB version: 22.2.2
 - Server OS: Ubuntu 20.04
 - Client app: psycopg2, psycopg(3)

**Additional notes**
The same error occurs from Java (DBeaver) using the PostgreSQL JDBC driver.

Jira issue: CRDB-23665

Epic CRDB-17785

### PR DESCRIPTION
**Pull request by rafiss**
fixes https://github.com/cockroachdb/cockroach/issues/50734
fixes https://github.com/cockroachdb/cockroach/issues/95667
informs https://github.com/cockroachdb/cockroach/issues/57255

---
### collatedstring: create new package 

Move the small amount of code from tree/collatedstring.go

---

### collatedstring: support C and POSIX in expressions

Release note (sql change): Expressions of the form `COLLATE "default"`,
`COLLATE "C"`, and `COLLATE "POSIX"` are now supported. Since the
default collation cannot be changed currently, these expressions are all
equivalent. The expressions are evaluated by treating the input as a
normal string, and ignoring the collation.

This means that comparisons between strings and collated strings that
use "default", "C", or "POSIX" are now supported.

Creating a column with the "C" or "POSIX" collations is still not
supported.

### CODE REVIEW

File: pkg/util/collatedstring/collatedstring.go [hunk 1]
```diff
@@ -0,0 +1,52 @@
...
+// CCollationTag is the "C" collation for strings. At the time of writing
+// this, it behaves the same os "default" since LC_COLLATE cannot be modified.
+const CCollationTag = "C"
+
+// PosixCollationTag is the "POSIX" collation for strings. At the time of
+// writing this, it behaves the same os "default" since LC_COLLATE cannot be
+// modified.
+const PosixCollationTag = "POSIX"
+
+var supportedTagNames []string
```
Comment (otan) [inline pkg/util/collatedstring/collatedstring.go:27]: should we use `language.Tag` here?

**Review by otan — COMMENTED** [review]
two broader questions:
* does `pg_catalog.pg_collation` need an update?
* should we add a linter that prevents usage of `collate.Supported()`? can use https://github.com/cockroachdb/cockroach/blob/1b7910292dbea110454c7c04b906ea5bd93946dc/pkg/testutils/lint/lint_test.go#L729 as inspo.

File: pkg/util/collatedstring/collatedstring.go (hunk 1 above)
Comment (otan) [reply pkg/util/collatedstring/collatedstring.go:27]: hmm, maybe we can't because `language.Tag` has metadata in it. oh well!

Comment (rafiss) [reply pkg/util/collatedstring/collatedstring.go:27]: yeah i had tried to get it to work with `Tag`, but it can't. there's no way to even make a "custom" `Tag`.

**Comment by rafiss** [comment]
> does pg_catalog.pg_collation need an update?

that's done as part of this

> should we add a linter that prevents usage of collate.Supported()? 

added

**Review by otan — APPROVED** [review]
ah the logic tests only mention `information_schema.collations`. i can see the code tho - feel free to add the test if you feel it's worth.

**Comment by rafiss** [comment]
tftr!

bors r=otan
