### PR TITLE
importccl: commit planner transaction in planHook

### LINKED ISSUE #61065: roachtest: tpce/c=5000/nodes=3 failed
[(roachtest).tpce/c=5000/nodes=3 failed](https://teamcity.cockroachdb.com/viewLog.html?buildId=2712399&tab=buildLog) on [master@ec011620c7cf299fdbb898db692b36454defc4a2](https://github.com/cockroachdb/cockroach/commits/ec011620c7cf299fdbb898db692b36454defc4a2):

```
		  | cd798458a46f: Pull complete
		  | Digest: sha256:1e299df6b79d4630bdb394ed98211f9303292b35aff2555ba5b997f2f889fdea
		  | Status: Downloaded newer image for cockroachdb/tpc-e:latest
		  | Error: Error { kind: Db, cause: Some(DbError { severity: "ERROR", parsed_severity: None, code: SqlState("XXUUU"), message: "relation \"charge\" is offline: importing", detail: None, hint: None, position: None, where_: None, schema: None, table: None, column: None, datatype: None, constraint: None, file: Some("descriptor.go"), line: Some(525), routine: Some("FilterDescriptorState") }) }
		  | Error: COMMAND_PROBLEM: exit status 1
		  | (1) COMMAND_PROBLEM
		  | Wraps: (2) Node 4. Command with error:
		  |   | ```
		  |   | sudo docker run cockroachdb/tpc-e:latest --customers=5000 --racks=3 --init --hosts=10.128.0.203
		  |   | ```
		  | Wraps: (3) exit status 1
		  | Error types: (1) errors.Cmd (2) *hintdetail.withDetail (3) *exec.ExitError
		  |
		  | stdout:
		  | Initializing schema...
		  | Importing dataset...
		Wraps: (4) exit status 20
		Error types: (1) *withstack.withStack (2) *errutil.withPrefix (3) *main.withCommandDetails (4) *exec.ExitError

	cluster.go:2688,tpce.go:96,tpce.go:113,test_runner.go:767: monitor failure: monitor task failed: t.Fatal() was called
		(1) attached stack trace
		  -- stack trace:
		  | main.(*monitor).WaitE
		  | 	/home/agent/work/.go/src/github.com/cockroachdb/cockroach/pkg/cmd/roachtest/cluster.go:2676
		  | main.(*monitor).Wait
		  | 	/home/agent/work/.go/src/github.com/cockroachdb/cockroach/pkg/cmd/roachtest/cluster.go:2684
		  | main.registerTPCE.func1
		  | 	/home/agent/work/.go/src/github.com/cockroachdb/cockroach/pkg/cmd/roachtest/tpce.go:96
		  | main.registerTPCE.func2
		  | 	/home/agent/work/.go/src/github.com/cockroachdb/cockroach/pkg/cmd/roachtest/tpce.go:113
		  | main.(*testRunner).runTest.func2
		  | 	/home/agent/work/.go/src/github.com/cockroachdb/cockroach/pkg/cmd/roachtest/test_runner.go:767
		Wraps: (2) monitor failure
		Wraps: (3) attached stack trace
		  -- stack trace:
		  | main.(*monitor).wait.func2
		  | 	/home/agent/work/.go/src/github.com/cockroachdb/cockroach/pkg/cmd/roachtest/cluster.go:2732
		Wraps: (4) monitor task failed
		Wraps: (5) attached stack trace
		  -- stack trace:
		  | main.init
		  | 	/home/agent/work/.go/src/github.com/cockroachdb/cockroach/pkg/cmd/roachtest/cluster.go:2646
		  | runtime.doInit
		  | 	/usr/local/go/src/runtime/proc.go:5652
		  | runtime.main
		  | 	/usr/local/go/src/runtime/proc.go:191
		  | runtime.goexit
		  | 	/usr/local/go/src/runtime/asm_amd64.s:1374
		Wraps: (6) t.Fatal() was called
		Error types: (1) *withstack.withStack (2) *errutil.withPrefix (3) *withstack.withStack (4) *errutil.withPrefix (5) *withstack.withStack (6) *errutil.leafError

```

<details><summary>More</summary><p>

Artifacts: [/tpce/c=5000/nodes=3](https://teamcity.cockroachdb.com/viewLog.html?buildId=2712399&tab=artifacts#/tpce/c=5000/nodes=3)

[See this test on roachdash](https://roachdash.crdb.dev/?filter=status%3Aopen+t%3A.%2Atpce%2Fc%3D5000%2Fnodes%3D3.%2A&sort=title&restgroup=false&display=lastcommented+project)
<sub>powered by [pkg/cmd/internal/issues](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)</sub></p></details>

### PR DESCRIPTION
**Pull request by pbardea**
This change commits the planner's transaction during import's plan hook.
It also uses the planner's transaction to create the job record. This
prevents transaction retries from re-running the plan hook and creating
duplicate job records.

Previously, the planner transaction when running the import job may have
retried when the conn executor would auto commit the transaction. Upon
auto commit, uncommited table descriptors would be validated. This
validation could raise a retryable txn error in the case of contention
and cause the entire plan hook to be run again.

Fixes https://github.com/cockroachdb/cockroach/issues/61065.

Release justification: bug fix

Release note (bug fix): Fix a bug where duplicate IMPORT job records
were created due to transaction restarts.

### CODE REVIEW

**Comment by pbardea** [comment]
I want to add a bit more commentary about the exact failure modes that we were seeing in the test failures, but it should be ready for an initial review.

File: pkg/ccl/importccl/import_stmt.go [hunk 1]
```diff
@@ -953,6 +953,18 @@ func importPlanHook(
 			return nil
 		}
 
+		// Double check that this transaction is implicit, so that
+		// we're allowed to commit.
+		if !p.ExtendedEvalContext().TxnImplicit {
+			return errors.AssertionFailedf("expected import planning transaction to be implicit")
+		}
+		// We're about to create the job record. We don't want this transaction
```
Comment (dt) [inline pkg/ccl/importccl/import_stmt.go:961]: More generally: we're about to have some side-effects that are not tied to this txn, which is okay OK if this txn _will_ commit and the only way to be sure of that is to commit it, which we're allowed to do since it is implicit.

File: pkg/ccl/importccl/import_stmt.go [hunk 2]
```diff
@@ -953,6 +953,18 @@ func importPlanHook(
 			return nil
 		}
 
+		// Double check that this transaction is implicit, so that
+		// we're allowed to commit.
+		if !p.ExtendedEvalContext().TxnImplicit {
```
Comment (dt) [inline pkg/ccl/importccl/import_stmt.go:958]: We check this above if not detached, and detached already early returned just above here, so I don't think this is needed?

**Review by dt — APPROVED** [review]

File: pkg/ccl/importccl/import_stmt.go (hunk 2 above)
Comment (pbardea) [reply pkg/ccl/importccl/import_stmt.go]: Yep, not needed. It was more of a sanity check just in-case we introduce a regression at the start of the plan hook to ensure that we don't commit an explicit transaction. I'm not super attached to it, and it may have been too defensive so removed it. I updated the comment with a brief explanation instead.

File: pkg/ccl/importccl/import_stmt.go (hunk 1 above)
Comment (pbardea) [reply pkg/ccl/importccl/import_stmt.go]: Updated the comment.

**Review by dt — APPROVED** [review]

**Comment by pbardea** [comment]
TFTR!
bors r=dt
