### PR TITLE
cli: fix default certs-dir

### LINKED ISSUE #87191: Cockroach CLI commands not using default location for --certs-dir
**Describe the problem**

During testing of the new 22.2.0-alpha.1 build.  It no longer finds my certificates in the default location of `$HOME/.cockroach-certs` when I fail to pass a `--certs-dir` flag.

**To Reproduce**

Have certificates in `$HOME/.cockroach-certs`, in mine I have `ca.crt`, `client.root.crt`, `client.root.key`, `node.crt` and `node.key` - ie the usual suspects.

Attempt to start a new cockroach instance/cluster with this command:

```
/home/vagrant/bin/cockroach start  --advertise-addr=172.28.128.21 --join=172.28.128.21
```

I get this:

```
[vagrant@node-1 ~]$ /home/vagrant/bin/cockroach start  --advertise-addr=172.28.128.21 --join=172.28.128.21
*
* ERROR: ERROR: cannot load certificates.
* Check your certificate settings, set --certs-dir, or use --insecure for insecure clusters.
* 
* failed to start server: problem using security settings: no certificates found; does certs dir exist?
*
ERROR: cannot load certificates.
Check your certificate settings, set --certs-dir, or use --insecure for insecure clusters.

failed to start server: problem using security settings: no certificates found; does certs dir exist?
Failed running "start"
```

Swapping the new binary out for the previous GA release works as expected.  I have no `~/.postgresql`.

Other CLI commands also break in the same way, such as `cockroach sql`, `cockroach init` etc.

**Expected behavior**
Normally, without the `--certs-dir` flag, it finds all the necessary certificates in `$HOME/.cockroach-certs` but now it doesn't. 

Jira issue: CRDB-19204

### PR DESCRIPTION
**Pull request by rafiss**
fixes https://github.com/cockroachdb/cockroach/issues/87191

https://github.com/cockroachdb/cockroach/pull/82020 accidentally broke
the logic for the certs-dir defaulting to ${HOME}/.cockroach-certs/

No release note since this bug was not released.

Release note: None

Release justification: low risk bug fix to new functionality.

### CODE REVIEW

**Comment by rafiss** [comment]
I'm not sure where to test this. do the `tcl` tests have a `${HOME}` directory?

File: pkg/security/certnames/locator.go [hunk 1]
```diff
@@ -24,7 +24,7 @@ type Locator struct {
 
 // MakeLocator initializes a Locator.
 func MakeLocator(certsDir string) Locator {
-	return Locator{certsDir: certsDir}
+	return Locator{certsDir: os.ExpandEnv(certsDir)}
```
Comment (knz) [inline pkg/security/certnames/locator.go:27]: This doesn't seem right. The expansion should be done by the shell, not crdb.

Where is this $HOME default defined?

Comment (knz) [reply pkg/security/certnames/locator.go:27]: oh I found it - base/config.go: `DefaultCertsDirectory = "${HOME}/.cockroach-certs"`

**Comment by knz** [comment]
The proper fix is to change the `base/config.go` file, something like this:

```
var DefaultCertsDirectory = os.ExpandEnv(...)
```

or alternatively, keep the constant as-is, but un-export it, then define a new function `GetDefaultCertsDirectory` that does the expansion.

What's important is to only apply the expansion on the default, but not on the string provided by the user on the command line.

**Comment by rafiss** [comment]
> What's important is to only apply the expansion on the default, but not on the string provided by the user on the command line.

Why is that desired? That would be a regression (or at least, a backwards incompatible change) from the behavior of v22.1.

**Comment by knz** [comment]
That behavior was a misdesign, as discussed in  #81298.
Note that when this came out, the doc team reviewed the docs and confirmed we had not documented the previous behaviour.

**Comment by knz** [comment]
Also, the bug your PR fixes here was an oversight in #81298 and so would like to apologize for the inconvenience.

**Review by knz — APPROVED** [review]

**Comment by rafiss** [comment]
tftr!

bors r=knz
