### PR TITLE
sql: avoid hydration when looking up non-type descriptor within hydration cache

### LINKED ISSUE #93314: Creating a function that returns a table type containing an enum type crashes the server
**Describe the problem**

Create a function that returns a table type, which contains an enum type. The creation of the function crashes the server

**To Reproduce**

```sql
create type e as enum ('a', 'b');
create table t (i int, e e);
insert into t values (1, 'a');

create or replace function f () returns t as 
$$
select i, e
from t
order by i
limit 1;
$$
language sql;
```

After this, the server is gone completely. It appears I also can't start it again!

**Expected behavior**

No crash

**Environment:**
 - CockroachDB version: CockroachDB CCL v22.2.0 (x86_64-pc-linux-gnu, built 2022/12/05 16:37:36, go1.19.1)
 - Server OS: Linux (Docker)
 - Client app: Dbeaver (JDBC)

Jira issue: CRDB-22270

### PR DESCRIPTION
**Pull request by chengxiong-ruan**
Fixes #93314

When creating a UDF whose signature uses implicit record type which has a column of user defined enum type, crdb crashes because of a type hydration deadloop. The reason is that when we try to hydrate the implicit record type, the enum type also needs to be hydrated, and the schema descriptor as well because we need a fully qualified type name which requires a schema lookup and we now have function signatures within schema descriptor which has the type information. Then to hydrate the schema descriptor, the function signature types need to hydrated (again!), such the deadloop happens.

This pr adds a new flag for descriptor lookup to explicitly avoid hydration when looking up descriptor that can't be used as a UDT, so that we can avoid the hydration deadloop when looking up schema descriptor for its name.

Release note (sql change): Previously, cockroach db would crash if user creates a UDF whose function signature includes a implicit record type (essentially a table) which has a column using a user defined enum type. This root cause was that there was  a hydration deadloop when looking up descriptors during hydration. This PR adds a new flag to avoid hydration in order to avoid the deadloop, users shouldn't feel differentce on using UDFs.

### CODE REVIEW

**Review by ajwerner — APPROVED** [review]
I'm good with this. I think it reveals the need for more testing involving implicit record types and udts in functions. Separately can you write some tests which leverage the enum alias type. Another thing to test is adding new columns to a table later which use a new an enum such that the function has a lower id than the enum. 

I worry about the way we hydrate the whole catalog for virtual tables.

**Comment by chengxiong-ruan** [comment]
>  Another thing to test is adding new columns to a table later which use a new an enum such that the function has a lower id than the enum.

hmm...this reveals another bug when trying add such test, open https://github.com/cockroachdb/cockroach/issues/94124 to track.

File: pkg/sql/catalog/hydrateddesc/hydrate.go [hunk 1]
```diff
@@ -68,8 +68,17 @@ func MakeTypeLookupFuncForHydration(
...
-		if typDesc == nil {
-			typDesc, err = lookupFn(ctx, id)
+		// If the type in the fast lookup catalog is a table implicit record type
+		// and  not fully hydrated, we need to make sure we get a hydrated version
+		// of it.
+		// TODO(chengxiong): we may also do topological sort on the descritpors need
+		// to be hydrated and hydrated them in order. In the mean while, we need to
+		// upsert the hydrated version into the fast lookup catalog. This may save
+		// some round trips.
+		if typDesc == nil ||
```
Comment (chengxiong-ruan) [inline pkg/sql/catalog/hydrateddesc/hydrate.go:78]: @ajwerner I'm not sure how you gonna feel about this change. this is address the case where table descriptor returned from the catalog lookup is not hydrated.

Comment (chengxiong-ruan) [reply pkg/sql/catalog/hydrateddesc/hydrate.go:78]: I also thought about sorting the descriptors by type, and hydrating them in order. For example, always hydrate type (no hydration needed for it though) and table descriptor first since they're needed to hydrated other descriptors. And we'd need to upsert the hydrated version back to the lookup catalog. However, I don't think this would be much better...

**Comment by chengxiong-ruan** [comment]
added tests for UDFs using composite type and implicit type contains composite type.

File: pkg/sql/catalog/descriptor.go [hunk 2]
```diff
@@ -763,6 +763,8 @@ type TableDescriptor interface {
 	// GetInProgressImportStartTime returns the start wall time of the in progress import,
 	// if it exists.
 	GetInProgressImportStartTime() int64
+	// Hydrated returns true iff all visible column types are hydrated.
+	Hydrated() bool
```
Comment (postamar) [inline pkg/sql/catalog/descriptor.go:767]: Can you redefine this as a function that takes a `catalog.TableDescriptor` rather than a method? Its logic does not rely on any state that's private to the interface implementation.

File: pkg/sql/catalog/descs/descriptor.go [hunk 3]
```diff
@@ -339,8 +339,10 @@ func getDescriptorsByID(
 	if err := tc.finalizeDescriptors(ctx, txn, flags, descs, vls); err != nil {
 		return err
 	}
-	if err := tc.hydrateDescriptors(ctx, txn, flags, descs); err != nil {
-		return err
+	if !flags.SkipHydration {
+		if err := tc.hydrateDescriptors(ctx, txn, flags, descs); err != nil {
```
Comment (postamar) [inline pkg/sql/catalog/descs/descriptor.go:343]: hydrateDescriptors also gets called by `GetLeasedImmutableTableByID` so perhaps the `flags.SkipHydration` check should happen within `hydrateDescriptors` itself?

File: pkg/sql/catalog/hydrateddesc/hydrate.go [hunk 4]
```diff
@@ -82,6 +85,12 @@ func MakeTypeLookupFuncForHydration(
 		case catalog.TypeDescriptor:
 			typ = t
 		case catalog.TableDescriptor:
+			if !t.Hydrated() {
+				if err := Hydrate(ctx, t, typeLookupFunc); err != nil {
+					return tree.TypeName{}, nil, err
+				}
+				c.UpsertDescriptor(t)
```
Comment (postamar) [inline pkg/sql/catalog/hydrateddesc/hydrate.go:92]: Should we also upsert `c` with all the other descriptors we look up, now that this function is recursive?

File: pkg/sql/catalog/hydrateddesc/hydrate.go [hunk 5]
```diff
@@ -25,7 +25,7 @@ import (
 
 // HydrationLookupFunc is the type of function required to look up type
 // descriptors and their parent schemas and databases when hydrating an object.
-type HydrationLookupFunc func(ctx context.Context, id descpb.ID) (catalog.Descriptor, error)
+type HydrationLookupFunc func(ctx context.Context, id descpb.ID, skipHydration bool) (catalog.Descriptor, error)
```
Comment (postamar) [inline pkg/sql/catalog/hydrateddesc/hydrate.go:28]: I find that this added boolean argument makes `MakeTypeLookupFuncForHydration` really hard to reason about, especially now that it returns a recursive function. Instead can we make it so that the `HydrationLookupFunc` implementations _always_ set `SkipHydration` so that we _know_ that all `lookupFn` calls don't recurse further into the hydration logic?

This requires pulling some logic from the `hydrateDescriptors` method in `descs.Collection` into the recursive function returned by `MakeTypeLookupFuncForHydration` (specifically, after `typDesc, err = lookupFn(ctx, id, false /* skipHydration */)`), but that's probably a good thing anyway and will probably simplify code that's already complicated instead of complicating it further.

**Review by postamar — COMMENTED** [review]
I'm really worried by all the extra recursion this change brings. The bug is severe so my concerns shouldn't block merging this PR if addressing my comments takes more than a few hours, but in that case it should be considered to be necessary follow-up work.

File: pkg/sql/catalog/hydrateddesc/hydrate.go [hunk 6]
```diff
@@ -82,6 +85,12 @@ func MakeTypeLookupFuncForHydration(
 		case catalog.TypeDescriptor:
 			typ = t
 		case catalog.TableDescriptor:
+			if !t.Hydrated() {
+				if err := Hydrate(ctx, t, typeLookupFunc); err != nil {
```
Comment (postamar) [inline pkg/sql/catalog/hydrateddesc/hydrate.go:89]: `Hydrate` is not thread-safe, should we be concerned?

File: pkg/sql/catalog/tabledesc/table_desc.go [hunk 7]
```diff
@@ -143,6 +143,16 @@ func (desc *wrapper) IsTemporary() bool {
 	return desc.GetTemporary()
 }
 
+// Hydrated implements the TableDescriptor interface.
+func (desc *wrapper) Hydrated() bool {
+	for _, col := range desc.VisibleColumns() {
```
Comment (postamar) [inline pkg/sql/catalog/tabledesc/table_desc.go:148]: Why `VisibleColumns` and not `AllColumns`?

Comment (postamar) [reply pkg/sql/catalog/tabledesc/table_desc.go:148]: In fact do we need any of this when we already have `ContainsUserDefinedTypes` in `catalog.HydratableDescriptor`?

File: pkg/sql/catalog/hydrateddesc/hydrate.go (hunk 6 above)
Comment (postamar) [reply pkg/sql/catalog/hydrateddesc/hydrate.go:89]: Ignoring my concerns about the `skipHydration` boolean argument you probably should retrieve a hydrated descriptor using `lookupFn(ctx, id, false /* skipHydration */)` rather than calling `Hydrate` directly.

Comment (chengxiong-ruan) [reply pkg/sql/catalog/hydrateddesc/hydrate.go:89]: I'm afraid that we need to do `Hydrate` because [this path](https://github.com/cockroachdb/cockroach/blob/cf1e7e6bc6ef9e55510b9ed13bd068bb3894cd92/pkg/sql/catalog/descs/hydrate.go#L169-L169) (used by show backup) really doesn't lookup anything, I'm assuming they have all descriptors in the fast lookup catalog....

File: pkg/sql/catalog/hydrateddesc/hydrate.go (hunk 4 above)
Comment (chengxiong-ruan) [reply pkg/sql/catalog/hydrateddesc/hydrate.go:92]: good idea, I think we can do that.

File: pkg/sql/catalog/tabledesc/table_desc.go (hunk 7 above)
Comment (chengxiong-ruan) [reply pkg/sql/catalog/tabledesc/table_desc.go:148]: > Why VisibleColumns and not AllColumns?

because we only look at visible columns when constructing the implicit record type.

> In fact do we need any of this when we already have ContainsUserDefinedTypes in catalog.HydratableDescriptor?

`ContainsUserDefinedTypes` doesn't check if types are hydrated or not :(

File: pkg/sql/catalog/hydrateddesc/hydrate.go (hunk 6 above)
Comment (chengxiong-ruan) [reply pkg/sql/catalog/hydrateddesc/hydrate.go:89]: > Hydrate is not thread-safe, should we be concerned?

Hmm...I'll need to think about this.

File: pkg/sql/catalog/descriptor.go (hunk 2 above)
Comment (chengxiong-ruan) [reply pkg/sql/catalog/descriptor.go:767]: good point. will do.

File: pkg/sql/catalog/descs/descriptor.go (hunk 3 above)
Comment (chengxiong-ruan) [reply pkg/sql/catalog/descs/descriptor.go:343]: we may do that indeed.

File: pkg/sql/catalog/hydrateddesc/hydrate.go (hunk 6 above)
Comment (ajwerner) [reply pkg/sql/catalog/hydrateddesc/hydrate.go:89]: Where does multi-threading come into the picture here?

Comment (chengxiong-ruan) [reply pkg/sql/catalog/hydrateddesc/hydrate.go:89]: I think we're fine here, The only thing shared across threads regarding this hydration domain is the hydrated descriptor cache and that is thread safe.

**Comment by ajwerner** [comment]
Can you run the benchmarks for resolving functions and make sure it's not worse? My hope is that we always hit the cache and then everything is good. If it looks good, ship it.

**Comment by chengxiong-ruan** [comment]
> Can you run the benchmarks for resolving functions and make sure it's not worse? My hope is that we always hit the cache and then everything is good. If it looks good, ship it.

Just ran it, and it's pretty much the same... I'll as much as I can as Marius's concern and will check in with him with tomorrow morning. Thanks again.

```
BENCHTIMEOUT=24h PKG=./pkg/bench BENCHES=BenchmarkFuncExprTypeCheck ./scripts/bench "8d3a94e0e6f27b602ded33f95f5827ba18807961" "a3446ad83d303b4f48303e725ecc076281729ab5"
Comparing a3446ad83d303b4f48303e725ecc076281729ab5 (new) with 8d3a94e0e6f27b602ded33f95f5827ba18807961 (old)

Writing to /tmp/tmp.HKfg5jijrd
Switching to 8d3a94e0e6f27b602ded33f95f5827ba18807961
+ ./dev bench ./pkg/bench --timeout=24h --filter=BenchmarkFuncExprTypeCheck --count=10 --bench-mem -v --stream-output --ignore-cache
Switching to a3446ad83d303b4f48303e725ecc076281729ab5
+ ./dev bench ./pkg/bench --timeout=24h --filter=BenchmarkFuncExprTypeCheck --count=10 --bench-mem -v --stream-output --ignore-cache
name                                                       old time/op    new time/op    delta
FuncExprTypeCheck/builtin_called_on_null_input-24             748ns ± 1%     748ns ± 1%    ~     (p=0.382 n=10+10)
FuncExprTypeCheck/builtin_not_called_on_null_input-24         724ns ± 1%     715ns ± 1%  -1.20%  (p=0.000 n=9+9)
FuncExprTypeCheck/builtin_aggregate-24                       1.17µs ± 1%    1.17µs ± 0%    ~     (p=0.325 n=9+9)
FuncExprTypeCheck/builtin_aggregate_not_called_on_null-24     897ns ± 1%     900ns ± 1%    ~     (p=0.289 n=10+10)
FuncExprTypeCheck/udf_same_name_as_builtin-24                 986ns ± 0%     979ns ± 1%  -0.67%  (p=0.001 n=9+10)
FuncExprTypeCheck/udf_across_different_schemas-24            1.88µs ± 1%    1.85µs ± 1%  -1.63%  (p=0.000 n=10+9)
FuncExprTypeCheck/unary_operator-24                           344ns ± 2%     340ns ± 2%  -1.23%  (p=0.005 n=10+10)
FuncExprTypeCheck/binary_operator-24                         1.24µs ± 0%    1.24µs ± 0%  -0.36%  (p=0.002 n=10+10)
FuncExprTypeCheck/comparison_operator-24                     2.06µs ± 1%    2.07µs ± 1%  +0.54%  (p=0.002 n=9+10)
FuncExprTypeCheck/tuple_comparison_operator-24               6.30µs ± 0%    6.33µs ± 1%  +0.44%  (p=0.040 n=9+9)
FuncExprTypeCheck/tuple_in_operator-24                       1.03µs ± 1%    1.03µs ± 0%    ~     (p=0.156 n=10+10)

name                                                       old alloc/op   new alloc/op   delta
FuncExprTypeCheck/builtin_called_on_null_input-24            0.67B ±500%    0.67B ±500%    ~     (p=1.000 n=9+9)
FuncExprTypeCheck/builtin_not_called_on_null_input-24        0.33B ±200%    0.30B ±233%    ~     (p=0.740 n=9+10)
FuncExprTypeCheck/builtin_aggregate-24                        1.00B ± 0%     1.00B ± 0%    ~     (all equal)
FuncExprTypeCheck/builtin_aggregate_not_called_on_null-24    3.22B ±272%    4.90B ±247%    ~     (p=0.861 n=9+10)
FuncExprTypeCheck/udf_same_name_as_builtin-24                 0.00B         0.44B ±125%    ~     (p=0.106 n=8+9)
FuncExprTypeCheck/udf_across_different_schemas-24              386B ± 0%      386B ± 0%  +0.12%  (p=0.041 n=9+8)
FuncExprTypeCheck/unary_operator-24                           0.00B          0.00B         ~     (all equal)
FuncExprTypeCheck/binary_operator-24                          1.00B ± 0%     1.00B ± 0%    ~     (all equal)
FuncExprTypeCheck/comparison_operator-24                      1.88B ±60%     1.67B ±40%    ~     (p=0.602 n=8+9)
FuncExprTypeCheck/tuple_comparison_operator-24                 438B ± 1%      439B ± 1%    ~     (p=0.689 n=9+8)
FuncExprTypeCheck/tuple_in_operator-24                         345B ± 0%      345B ± 0%    ~     (p=0.246 n=8+7)

name                                                       old allocs/op  new allocs/op  delta
FuncExprTypeCheck/builtin_called_on_null_input-24              0.00           0.00         ~     (all equal)
FuncExprTypeCheck/builtin_not_called_on_null_input-24          0.00           0.00         ~     (all equal)
FuncExprTypeCheck/builtin_aggregate-24                         0.00           0.00         ~     (all equal)
FuncExprTypeCheck/builtin_aggregate_not_called_on_null-24      0.00           0.00         ~     (all equal)
FuncExprTypeCheck/udf_same_name_as_builtin-24                  0.00           0.00         ~     (all equal)
FuncExprTypeCheck/udf_across_different_schemas-24              4.00 ± 0%      4.00 ± 0%    ~     (all equal)
FuncExprTypeCheck/unary_operator-24                            0.00           0.00         ~     (all equal)
FuncExprTypeCheck/binary_operator-24                           0.00           0.00         ~     (all equal)
FuncExprTypeCheck/comparison_operator-24                       0.00           0.00         ~     (all equal)
FuncExprTypeCheck/tuple_comparison_operator-24                 4.00 ± 0%      4.00 ± 0%    ~     (all equal)
FuncExprTypeCheck/tuple_in_operator-24                         4.00 ± 0%      4.00 ± 0%    ~     (all equal)
```

File: pkg/sql/catalog/hydrateddesc/hydrate.go (hunk 5 above)
Comment (chengxiong-ruan) [reply pkg/sql/catalog/hydrateddesc/hydrate.go:28]: I'll look into this in a bit.

Comment (chengxiong-ruan) [reply pkg/sql/catalog/hydrateddesc/hydrate.go:28]: Sorry just came back to this...was looking at other issues. I think the right way to `hydrate a slice of descriptors` is that
(1). go through all target descriptors to figure out what types are need. this would just require getting all interested type OID/IDs. There this no look up needed. Simply just get all IDs. I don't think there'll be recursions. It's simply loop through each descriptor type internally to get types. Though there could be 2 or 3 levels. For example, for function, we'd need to go through args and return type, and if any of these type is a table, we need to go through all the visible table columns.

(2). then we construct a data structure which would contain all the types required with the IDs we get in (1). Here, we need to make sure all types are hydrated. Actually, `hydrating a type` seems the wrong concept here. Only table implicit record type needs hydration. So that, we could lookup all type descriptors first and memoize them in the new data structure. And then, we hydrate the table or implicit record type with the the type descriptors we already have. Now, we have all the types. 
-- There shouldn't be any recursion. Because:
    1> type descriptors doesn't need hydration, or 1 level hydration at most.
    2> table implicit record type only need 1 level hydration, because we can't use record type with in record type yet, and composite type can't use enum yet. Well, the worst case is that things can be very explicit.

(3) simply replace all the type references in each descriptor with the types we all ready got. there is not recursion.

Let me know what you think... But anyhow I don't think I can commit to this now. We can do this later.

Comment (postamar) [reply pkg/sql/catalog/hydrateddesc/hydrate.go:28]: I think that you're completely correct. I'll be happy to do what you suggested as a follow-up to this PR.

File: pkg/sql/catalog/hydrateddesc/hydrate.go (hunk 6 above)
Comment (postamar) [reply pkg/sql/catalog/hydrateddesc/hydrate.go:89]: That's a relief!

File: pkg/sql/catalog/tabledesc/table_desc.go (hunk 7 above)
Comment (postamar) [reply pkg/sql/catalog/tabledesc/table_desc.go]: Thanks!

**Review by postamar — APPROVED** [review]
Ship it! Nice work. We know what to do afterwards. I'll take a stab at it today.

**Comment by chengxiong-ruan** [comment]
TFTRs!
bors r+
