### PR TITLE
kvpb: add ConflictKey field to propagate actual conflict key

### LINKED ISSUE #125787: sql: the key reported by contention events is incorrect
**Describe the problem**

The key reported in a contention event is supposed to be the key on which there was a conflict, as per the comment here:

https://github.com/cockroachdb/cockroach/blob/41c37cbcc53d34b01d5070c52158f63bb78edd13/pkg/kv/kvpb/api.proto#L3661-L3665

However, it's populated here: 

https://github.com/cockroachdb/cockroach/blob/c88a1cedb064f554f38bb5b310e83ac3259ee02e/pkg/sql/conn_executor_exec.go#L3365-L3366

In doing so, we're using the key where the conflicting transaction's transaction record is anchored. See: 

https://github.com/cockroachdb/cockroach/blob/c097c1981a43c293d72e076851c8a7a78fd0628c/pkg/storage/enginepb/mvcc3.proto#L29-L33

This doesn't necessarily mean that this was the key the two transactions conflicted on; just that one of the transactions wrote to this key. This seems unintentional.

### PR DESCRIPTION
**Pull request by angles-n-daemons**
Previously, contention events incorrectly reported the anchor key (TxnMeta.Key) instead of the actual conflict key. The anchor key is where a transaction's record is stored, which is often different from the key where the conflict occurred.

This change adds a ConflictKey field to TransactionRetryError and TransactionRetryWithProtoRefreshError to propagate the actual conflict key from RefreshFailedError through the error chain. The SQL layer now uses this field when recording SERIALIZATION_CONFLICT contention events.

Fixes #125787

Release note (bug fix): Fixed a bug where contention events reported the wrong key. Previously, the key field in contention events showed the transaction's anchor key (used for record placement) rather than the actual key where the conflict occurred. This made it difficult to diagnose contention issues accurately.

(co-authored with claude)

### CODE REVIEW

**Review by stevendanna — COMMENTED** [review]
Overall this looks good, but I'm wondering if we need to go a bit further:

This handles the case of a failed pre-emptive refresh. Are we getting the correct keys for write-write failures that raise WriteTooOld errors? Are we getting the correct keys for cases where we do a non-preemptive refresh?

Both questions _might_ reduce to: Should we handle this TODO while we are here:

https://github.com/cockroachdb/cockroach/blob/1d6747235eda562cce2049448d34f645388cf2e1/pkg/kv/kvclient/kvcoord/txn_interceptor_span_refresher.go#L298

No worries if you don't want to take that on, this is a clear improvement. I'll give the code another pass.

File: pkg/kv/kvclient/kvcoord/dist_sender_server_test.go [hunk 1]
```diff
@@ -4223,6 +4223,81 @@ func TestRefreshFailureIncludesConflictingTxn(t *testing.T) {
...
+func TestRefreshFailureIncludesConflictKey(t *testing.T) {
+	defer leaktest.AfterTest(t)()
+	defer log.Scope(t).Close(t)
+
+	ctx := context.Background()
+	s, _, db := serverutils.StartServer(t, base.TestServerArgs{})
+	defer s.Stopper().Stop(ctx)
+
+	// We use three keys:
+	// - keyA: will be the anchor key for txn2 (first write determines anchor)
```
Comment (stevendanna) [inline pkg/kv/kvclient/kvcoord/dist_sender_server_test.go:4247]: I think there is a metamorphic cluster setting that changes this:

```
pkg/kv/kvclient/kvcoord/txn_interceptor_heartbeater.go
54:     "kv.transaction.randomized_anchor_key.enabled",
56:     metamorphic.ConstantWithTestBool("kv.transaction.randomized_anchor_key.enabled", false)
```

We might want to explicitly set that to false so it doesn't change what we are testing here.

File: pkg/kv/kvclient/kvcoord/txn_coord_sender.go
Comment (stevendanna) [inline pkg/kv/kvclient/kvcoord/txn_coord_sender.go:905]: This one probably also has a tErr.Key you could use.

**Review by stevendanna — APPROVED** [review]
Looks good overall. I left some comments for your consideration.

I'll try to look at that TODO sometime soon. One reason I think it could matter is that once we turn off buffered writes, I think fewer transactions hit the pre-emptive refresh case and more end up on the retry path.
