### PR TITLE
kvserver: deflake `TestRaftPreVote`

### LINKED ISSUE #117596: kv/kvserver: TestRaftPreVote failed
kv/kvserver.TestRaftPreVote [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Ci_TestsAwsLinuxArm64_UnitTests/13478405?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Ci_TestsAwsLinuxArm64_UnitTests/13478405?buildTab=artifacts#/) on master @ [05d1395c556dfb8f6bac6d6dfcc7ae60824edd07](https://github.com/cockroachdb/cockroach/commits/05d1395c556dfb8f6bac6d6dfcc7ae60824edd07):

```
=== RUN   TestRaftPreVote
    test_log_scope.go:170: test logs captured to: /artifacts/tmp/_tmp/da89cade6788d04c28915439cd9b25f2/logTestRaftPreVote256505961
    test_log_scope.go:81: use -show-logs to present logs inline
    client_raft_test.go:6302: -- test log scope end --
test logs left over in: /artifacts/tmp/_tmp/da89cade6788d04c28915439cd9b25f2/logTestRaftPreVote256505961
--- FAIL: TestRaftPreVote (42.27s)
=== RUN   TestRaftPreVote/partial=false
    --- FAIL: TestRaftPreVote/partial=false (20.33s)
=== RUN   TestRaftPreVote/partial=false/quiesce=false
        --- FAIL: TestRaftPreVote/partial=false/quiesce=false (11.41s)
=== RUN   TestRaftPreVote/partial=false/quiesce=false/expLease=false
    client_raft_test.go:6207: n1 has lease
    client_raft_test.go:6215: n3 not quiesced
    client_raft_test.go:6220: n3 partitioned
    client_raft_test.go:6225: n1 StateLeader at term=6 commit=22
    client_raft_test.go:6233: n3 not quiesced
    client_raft_test.go:6239: n3 StateFollower at term=6 commit=22
    client_raft_test.go:6137: r68 proposal rejected: GC [/Table/Max,"\xfa\x00"), GC [/Table/Max,"\xfa\x00"), GC [/Table/Max,"\xfa\x00"), GC [/Table/Max,"\xfa\x00")
    client_raft_test.go:6239: n3 StatePreCandidate at term=6 commit=22
    client_raft_test.go:6242: n3 became pre-candidate
    client_raft_test.go:6249: n3 StatePreCandidate at term=6 commit=22
    client_raft_test.go:6249: n3 StatePreCandidate at term=6 commit=22
    client_raft_test.go:6252: n3 is still pre-candidate
    client_raft_test.go:6259: n1 StateLeader at term=6 commit=23
    client_raft_test.go:6263: 
        	Error Trace:	github.com/cockroachdb/cockroach/pkg/kv/kvserver_test/pkg/kv/kvserver/client_raft_test.go:6263
        	            				github.com/cockroachdb/cockroach/pkg/testutils/subtest.go:28
        	Error:      	Not equal: 
        	            	expected: 0x16
        	            	actual  : 0x17
        	Test:       	TestRaftPreVote/partial=false/quiesce=false/expLease=false
            --- FAIL: TestRaftPreVote/partial=false/quiesce=false/expLease=false (5.65s)
```
<details><summary>Help</summary>
<p>

See also: [How To Investigate a Go Test Failure \(internal\)](https://cockroachlabs.atlassian.net/l/c/HgfXfJgM)
</p>
</details>
/cc @cockroachdb/replication
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*TestRaftPreVote.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)
</sub>

Jira issue: CRDB-35259

### PR DESCRIPTION
**Pull request by erikgrinaker**
It was possible for a txn record GC request to slip in right before proposals were blocked and the follower partitioned. This patch deflakes the test by blocking proposals earlier, and waiting for the range to stabilize.

Resolves #117596.
Epic: none
Release note: None

### CODE REVIEW

File: pkg/kv/kvserver/client_raft_test.go [hunk 1]
```diff
@@ -6206,13 +6206,49 @@ func TestRaftPreVote(t *testing.T) {
...
+							if pr.Match != lastIndex {
+								t.Logf("n%d match %d not at n1 last index %d, waiting", i, pr.Match, lastIndex)
+								return false
+							}
+						}
+						if since := time.Since(lastChanged); since < time.Second {
+							t.Logf("n1 last index %d changed %s ago, waiting",
+								lastIndex, since.Truncate(time.Millisecond))
+							return false
+						}
```
Comment (pav-kv) [inline pkg/kv/kvserver/client_raft_test.go:6247]: Can this be implemented as a simple loop instead of using `Eventually`?

```golang
for !check() {
	sleep
}
```

File: pkg/kv/kvserver/client_raft_test.go [hunk 2]
```diff
@@ -6206,13 +6206,49 @@ func TestRaftPreVote(t *testing.T) {
...
 				if quiesce {
 					require.Eventually(t, repl3.IsQuiescent, 10*time.Second, 100*time.Millisecond)
 					t.Logf("n3 quiesced")
 				} else {
 					require.False(t, repl3.IsQuiescent())
 					t.Logf("n3 not quiesced")
+
+					var lastIndex uint64
+					var lastChanged time.Time
+					require.Eventually(t, func() bool {
```
Comment (pav-kv) [inline pkg/kv/kvserver/client_raft_test.go:6225]: Is there a simpler condition to wait for? For example, all commit indices match the leader's last index. This will imply all the rest, e.g. that `Match` matches on all the nodes.

Or this would be racy? I suspect that things can be flushed to raft in the meantime, so the last index can grow for a bit.

**Review by pav-kv — APPROVED** [review]
LGTM % maybe making this simpler.

File: pkg/kv/kvserver/client_raft_test.go (hunk 2 above)
Comment (erikgrinaker) [reply pkg/kv/kvserver/client_raft_test.go:6225]: We can drop the commit index check, it's sort of implied by the match checks. Looking at the commit index requires looking at the local replica state across all replicas, seems easier to just look at the leader's state.

File: pkg/kv/kvserver/client_raft_test.go (hunk 1 above)
Comment (erikgrinaker) [reply pkg/kv/kvserver/client_raft_test.go:6247]: We'd have to add timeout handling too. Why do this ourselves when `require.Eventually` already does it?
