### PR TITLE
restore: only run proc lag checker on fully updgraded 24.3 clusters

### LINKED ISSUE #128758: roachtest: backup-restore/mixed-version failed
roachtest.backup-restore/mixed-version [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/16414561?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/16414561?buildTab=artifacts#/backup-restore/mixed-version) on master @ [451cdbe687b3303665bfd490af59c5df777c8909](https://github.com/cockroachdb/cockroach/commits/451cdbe687b3303665bfd490af59c5df777c8909):

```
(mixedversion.go:694).Run: mixed-version test failure while running step 23 (run "verify some backups"): mixed-version: error waiting for job to finish: job 993809693168041985 failed with error: importing 3 ranges: nil span /Min: interval: nil range
test artifacts and logs in: /artifacts/backup-restore/mixed-version/run_1
```

Parameters:
 - <code>ROACHTEST_arch=amd64</code>
 - <code>ROACHTEST_cloud=gce</code>
 - <code>ROACHTEST_coverageBuild=false</code>
 - <code>ROACHTEST_cpu=4</code>
 - <code>ROACHTEST_encrypted=true</code>
 - <code>ROACHTEST_fs=ext4</code>
 - <code>ROACHTEST_localSSD=true</code>
 - <code>ROACHTEST_metamorphicBuild=false</code>
 - <code>ROACHTEST_ssd=0</code>
<details><summary>Help</summary>
<p>

See: [roachtest README](https://github.com/cockroachdb/cockroach/blob/master/pkg/cmd/roachtest/README.md)

See: [How To Investigate \(internal\)](https://cockroachlabs.atlassian.net/l/c/SSSBr8c7)

See: [Grafana](https://go.crdb.dev/roachtest-grafana/teamcity-16414561/backup-restore-mixed-version/1723355492189/1723357207990)

</p>
</details>
<details><summary>Same failure on other branches</summary>
<p>

- #125677 roachtest: backup-restore/mixed-version failed [C-test-failure O-roachtest O-robot P-3 T-disaster-recovery branch-release-23.1 release-blocker]
</p>
</details>
/cc @cockroachdb/disaster-recovery
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*backup-restore/mixed-version.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/bazci/githubpost/issues)
</sub>

Jira issue: CRDB-41184

### PR DESCRIPTION
**Pull request by msbutler**
The restore proc lag checker added in #128356 can fail a mixed version restore with an old coordinator, as detailed in #128758. This patch ensures the lag checker only runs once the restore has begun on a fully upgraded cluster.

Fixes #128758

Release note: none

### CODE REVIEW

File: pkg/ccl/backupccl/restore_job.go [hunk 1]
```diff
@@ -541,17 +541,18 @@ func restore(
...
+			restoreTime:            endTime,
+			encryption:             encryption,
+			kmsEnv:                 kmsEnv,
+			uris:                   details.URIs,
+			backupLocalityInfo:     backupLocalityInfo,
+			spanFilter:             filter,
+			numImportSpans:         numImportSpans,
+			execLocality:           details.ExecutionLocality,
+			exclusiveEndKeys:       fsc.isExclusive(),
+			creationClusterVersion: job.Payload().CreationClusterVersion,
```
Comment (stevendanna) [inline pkg/ccl/backupccl/restore_job.go:555]: I wonder if we really need to use the creation cluster version here. One all nodes are on the same version, it is safe to send the new message even if we were started on a lower version.  But, it's fine I suppose, most restores don't span versions and this makes us safe.

**Review by stevendanna — APPROVED** [review]

**Review by azhu-crl — APPROVED** [review]

File: pkg/ccl/backupccl/restore_job.go (hunk 1 above)
Comment (msbutler) [reply pkg/ccl/backupccl/restore_job.go]: Good point. Updated this to be the `ResumeClusterVersion`
