### PR TITLE
sql: add version gate to stop upgrade if interleaved tables exist

### LINKED ISSUE #52009: sql: remove interleaved tables
Interleaved tables are a mixed bag. Their theoretical pros are:

- improved performance for bulk inserts across multiple tables, if the data has a shared prefix, since the keys would go to the same range
- improved performance for joins on co-interleaved tables since data can be read in a single scan on a single range

In reality, they have a large cons list:
- the interleaved join code is complex, undertested, and planned only in precise circumstances. it also only permits joins of 2 interleaved tables at the same time today, severely limiting the performance upside
- doing bulk inserts into more than one table is awkward (you'd need to use CTEs)
- the code today doesn't actually coalesce the writes of these bulk inserts into a single batch anyway, so you get no actual performance gain
- the code's existence is quite burdensome, as it's complex and provides extra surfaces for bugs to accumulate on, and more things to think about when developing everyday features across every SQL team, plus backup and restore. Schema changes and bulk operations are complicated by the existence of interleaved tables, and often features must be shipped without interleaved support due to the complexity of supporting them.

We should remove interleaved tables altogether from CockroachDB, and that's what this issue tracks.

Primary Key Changes gives us an offramp for people who use interleaved tables. The procedure is that you should alter the primary key of all of the child interleaved tables to no longer be interleaved, one by one, until there are no interleaved children left.

Here's a proposal, using input from the schema team and others:

- in 20.2, we'll mark interleaved tables as deprecated in the documentation. Creating new interleaved tables will return a deprecation notice, and won't work unless a session (cluster?) setting is enabled.
- in 21.2, we'll change nodes to fail to join the cluster if any interleaved tables are present in the cluster. In that version or the version after, we can also remove all of the interleave table code from the codebase.

Epic: CRDB-1582

### PR DESCRIPTION
**Pull request by fqazi**
Fixes: #52009

Previously, interleaved tables were only deprecated so users
were allowed to create them after flipping an internal setting.
This was inadequate because we want to completely drop support
for this feature, as a part of the next release we will be
completely disabling support for them. To address this, this
patch will block upgrade to the next version if interleaved
tables exist.

Release note: Upgrade to the next version will be blocked if
interleaved tables/indexes exist. Users should convert existing
interleaved tables/indexes to non-interleaved ones or drop any
tables/indexes before upgrading to the next version.

### CODE REVIEW

**Review by postamar — DISMISSED** [review]
Welcome back!

Your commit message needs some editing:
1. For a start there's a "mend" string that made its way in there by mistake. 
2. Next, your use of the word "migration" instead of "upgrade" is quite confusing. Clusters _upgrade_ from one version to the next, and in so doing they might run _migrations_, but they're not the same thing.
3. If we don't have an issue for this (which is possible) can you please create one and link it to the jira epic?
3. Can you flesh out your release note some more? This is very terse considering the impact on our users, never mind our documentations team.

Unrelated but why are there changes to `migrations.pb.go` checked in this commit?

> Reviewed 1 of 9 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/68074#-:-MfZAvcB3bzj1XfZEXNH:bk2mesv)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @fqazi)

___
*[pkg/migration/migrations/interleaved_tables.go, line 36 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/68074#-MfZBSdr2drGRz57RvRV:-MfZBSdr2drGRz57RvRW:b-iovrwu) ([raw file](https://github.com/cockroachdb/cockroach/blob/5532c422de0c0d8dde4afad5bce17b00c54586bc/pkg/migration/migrations/interleaved_tables.go#L36)):*
> ```Go
> 	}
> 	return nil
> }
> ```

What is the purpose of this migration? My understanding is you need to version-gate the creation of new interleaves, such that when the migration runs in the _next_ version, we are guaranteed that there are no concurrent interleave creations. Such as it is, we're checking that there are no interleaves twice, which isn't cheap, for no apparent good reason (to me).
___
*[pkg/migration/migrations/interleaved_tables.go, line 47 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/68074#-MfZDAfF4QirNGocM8_A:-MfZDAfF4QirNGocM8_B:bl7c5zv) ([raw file](https://github.com/cockroachdb/cockroach/blob/5532c422de0c0d8dde4afad5bce17b00c54586bc/pkg/migration/migrations/interleaved_tables.go#L47)):*
> ```Go
> 	txn := d.DB.NewTxn(ctx, "interleaved-check")
> 	rows, err := d.InternalExecutor.QueryRowEx(ctx, "check-for-interleaved", txn, sessiondata.InternalExecutorOverride{User: security.RootUserName()},
> 		"select * from crdb_internal.interleaved")
> ```

I may be wrong, but the way this table is built, this query seems awfully expensive. The table generator follows the interleave references to get the interleaved table names, etc. Plus we don't actually care about all the rows in this table only whether there are none or not. Perhaps consider adding a `LIMIT 1`? Not sure if this helps. This is worth testing for.

Alternatively, and arguably preferably, consider bypassing the table and instead reimplement the logic from the table generator fn in this migration. It's simple enough. That way you don't need to change the semantics of the table by including dropped indexes like you did. Besides, it seems to me that we'll want to remove that table sooner rather than later. In fact, why not do so in this PR?
___
*[pkg/migration/migrations/interleaved_tables_external_test.go, line 122 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/68074#-MfZFAzw4WbV5grmAK6m:-MfZFAzw4WbV5grmAK6n:b-fhvay8) ([raw file](https://github.com/cockroachdb/cockroach/blob/5532c422de0c0d8dde4afad5bce17b00c54586bc/pkg/migration/migrations/interleaved_tables_external_test.go#L122)):*
> ```Go
> 	// Migration should succeed.
> 	tdb.ExecSucceedsSoon(t, "SET CLUSTER SETTING version = $1",
> 		clusterversion.ByKey(clusterversion.InterleavedTablesRemovedMigration).String())
> ```

perhaps also add an assertion on a `CREATE TABLE ... INTERLEAVE IN PARENT` expecting an ` interleavedTableDisabledMigrationError`, post-upgrade?

**Review by fqazi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/68074)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @postamar)

___
*[pkg/migration/migrations/interleaved_tables.go, line 36 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/68074#-MfZBSdr2drGRz57RvRV:-MfZQmiAALhBBW3OyjsM:b-nzbz40) ([raw file](https://github.com/cockroachdb/cockroach/blob/5532c422de0c0d8dde4afad5bce17b00c54586bc/pkg/migration/migrations/interleaved_tables.go#L36)):*
<details><summary><i>Previously, postamar (Marius Posta) wrote…</i></summary><blockquote>

What is the purpose of this migration? My understanding is you need to version-gate the creation of new interleaves, such that when the migration runs in the _next_ version, we are guaranteed that there are no concurrent interleave creations. Such as it is, we're checking that there are no interleaves twice, which isn't cheap, for no apparent good reason (to me).
</blockquote></details>

So, the first stage is sort of prone to race conditions it only validates no interleaves exist at the current point in time, without blocking CREATE TABLE / CREATE INDEXES or other operations. So, the first stage disables those operations only, the second once again validates no interleaved objects exist. 
___
*[pkg/migration/migrations/interleaved_tables.go, line 47 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/68074#-MfZDAfF4QirNGocM8_A:-MfZRh-TA4w0Pw76enlK:b-dqshqx) ([raw file](https://github.com/cockroachdb/cockroach/blob/5532c422de0c0d8dde4afad5bce17b00c54586bc/pkg/migration/migrations/interleaved_tables.go#L47)):*
> ably preferably, consider bypassing the table and instead reimplement the logi
We can't drop the internal table yet? If you haven't gone past this migration you still need that function to figure out the source of your problem. I think once your past this point on the next release we can drop all the code right?

Let me dig into using the code from the CRDB function directly, or confirm if the limit clause is sufficient.
___
*[pkg/migration/migrations/interleaved_tables_external_test.go, line 122 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/68074#-MfZFAzw4WbV5grmAK6m:-MfZSQiy7i8syRW9OoGV:b-d1bsh6) ([raw file](https://github.com/cockroachdb/cockroach/blob/5532c422de0c0d8dde4afad5bce17b00c54586bc/pkg/migration/migrations/interleaved_tables_external_test.go#L122)):*
<details><summary><i>Previously, postamar (Marius Posta) wrote…</i></summary><blockquote>

perhaps also add an assertion on a `CREATE TABLE ... INTERLEAVE IN PARENT` expecting an ` interleavedTableDisabledMigrationError`, post-upgrade?
</blockquote></details>

Good point, let me confirm that new error shows up :)

**Comment by fqazi** [comment]
> Welcome back!
> 
> Your commit message needs some editing:
> 
> 1. For a start there's a "mend" string that made its way in there by mistake.
> 2. Next, your use of the word "migration" instead of "upgrade" is quite confusing. Clusters _upgrade_ from one version to the next, and in so doing they might run _migrations_, but they're not the same thing.
> 3. If we don't have an issue for this (which is possible) can you please create one and link it to the jira epic?
> 4. Can you flesh out your release note some more? This is very terse considering the impact on our users, never mind our documentations team.
> 
> Unrelated but why are there changes to `migrations.pb.go` checked in this commit?
> 
> > Reviewed 1 of 9 files at r1.
> > _[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/68074#-:-MfZAvcB3bzj1XfZEXNH:bk2mesv)_ status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @fqazi)
> 
> _[pkg/migration/migrations/interleaved_tables.go, line 36 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/68074#-MfZBSdr2drGRz57RvRV:-MfZBSdr2drGRz57RvRW:b-iovrwu) ([raw file](https://github.com/cockroachdb/cockroach/blob/5532c422de0c0d8dde4afad5bce17b00c54586bc/pkg/migration/migrations/interleaved_tables.go#L36)):_
> 
> > ```go
> > 	}
> > 	return nil
> > }
> > ```
> 
> What is the purpose of this migration? My understanding is you need to version-gate the creation of new interleaves, such that when the migration runs in the _next_ version, we are guaranteed that there are no concurrent interleave creations. Such as it is, we're checking that there are no interleaves twice, which isn't cheap, for no apparent good reason (to me).
> 
> _[pkg/migration/migrations/interleaved_tables.go, line 47 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/68074#-MfZDAfF4QirNGocM8_A:-MfZDAfF4QirNGocM8_B:bl7c5zv) ([raw file](https://github.com/cockroachdb/cockroach/blob/5532c422de0c0d8dde4afad5bce17b00c54586bc/pkg/migration/migrations/interleaved_tables.go#L47)):_
> 
> > ```go
> > 	txn := d.DB.NewTxn(ctx, "interleaved-check")
> > 	rows, err := d.InternalExecutor.QueryRowEx(ctx, "check-for-interleaved", txn, sessiondata.InternalExecutorOverride{User: security.RootUserName()},
> > 		"select * from crdb_internal.interleaved")
> > ```
> 
> I may be wrong, but the way this table is built, this query seems awfully expensive. The table generator follows the interleave references to get the interleaved table names, etc. Plus we don't actually care about all the rows in this table only whether there are none or not. Perhaps consider adding a `LIMIT 1`? Not sure if this helps. This is worth testing for.
> 
> Alternatively, and arguably preferably, consider bypassing the table and instead reimplement the logic from the table generator fn in this migration. It's simple enough. That way you don't need to change the semantics of the table by including dropped indexes like you did. Besides, it seems to me that we'll want to remove that table sooner rather than later. In fact, why not do so in this PR?
> 
> _[pkg/migration/migrations/interleaved_tables_external_test.go, line 122 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/68074#-MfZFAzw4WbV5grmAK6m:-MfZFAzw4WbV5grmAK6n:b-fhvay8) ([raw file](https://github.com/cockroachdb/cockroach/blob/5532c422de0c0d8dde4afad5bce17b00c54586bc/pkg/migration/migrations/interleaved_tables_external_test.go#L122)):_
> 
> > ```go
> > 	// Migration should succeed.
> > 	tdb.ExecSucceedsSoon(t, "SET CLUSTER SETTING version = $1",
> > 		clusterversion.ByKey(clusterversion.InterleavedTablesRemovedMigration).String())
> > ```
> 
> perhaps also add an assertion on a `CREATE TABLE ... INTERLEAVE IN PARENT` expecting an ` interleavedTableDisabledMigrationError`, post-upgrade?

3) Linked to the issue for this work in the commit message (I will open a separate one for code clean up after the next release to kill all code for interleaved tables).
4) Sorry, I should have added more detail. Updated the language for release notes based on our documentation.

File: pkg/migration/migrationmanager/manager.go [hunk 1]
```diff
@@ -230,15 +243,17 @@ func (m *Manager) Migrate(
 // until the cluster is stable.
 func bumpClusterVersion(
 	ctx context.Context, c migration.Cluster, clusterVersion clusterversion.ClusterVersion,
-) error {
+) (error, bool) {
 	req := &serverpb.BumpClusterVersionRequest{ClusterVersion: &clusterVersion}
 	op := fmt.Sprintf("bump-cluster-version=%s", req.ClusterVersion.PrettyPrint())
+	anyVersionBumped := false
```
Comment (irfansharif) [inline pkg/migration/migrationmanager/manager.go:249]: I'm not sure if this is sound, and I'm not sure that using this return value to decide whether or not to update system.settings is sound either. The guarantees we want to provide at the level of `(*Manager) Migrate` is that it should be completely idempotent. With the hook passed in, I think we want to instead check that the version stored in system.settings is less than the version we're trying to set it to.

**Review by irfansharif — COMMENTED** [review]
A drive by review of just the migrations package.

File: pkg/sql/exec_util.go [hunk 2]
```diff
@@ -993,11 +993,19 @@ type ExecutorConfig struct {
 	CollectionFactory *descs.CollectionFactory
 }
 
+// SetCurrentVersionHook hook used to update the version both on
+// disk and in memory.
```
[the remark this answers is not in the document]
Comment (fqazi) [reply pkg/sql/exec_util.go:997]: Maybe rename this to UpdateSystemVersionSetting? It's not fully generic, and I'll fix the comments at the same time.

**Review by ajwerner — COMMENTED** [review]
I'm adding testing to https://github.com/cockroachdb/cockroach/pull/68242 which will be nice to adopt in this. 

> Reviewed 1 of 16 files at r9, 4 of 24 files at r10.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/68074#-:-MglDO5g71AZ58W0KRk3:b-xeft29)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @fqazi, @irfansharif, @otan, and @postamar)

___
*[pkg/migration/migrations/migrations.go, line 86 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/68074#-MfZ5vyBN_VVXUuX5KVv-r8-86:-MgkhX7ADPnDFYGM87RN:b5i4hkr) ([raw file](https://github.com/cockroachdb/cockroach/blob/4430141eda66207444517d20301b10db51cd09ce/pkg/migration/migrations/migrations.go#L86)):*
<details><summary><i>Previously, irfansharif (irfan sharif) wrote…</i></summary><blockquote>

See comment above, the migration infrastructure guarantees that the cluster is at least at InterleavedCreationBlockedMigration, not the migration itself.
</blockquote></details>

There are two cluster versions. The first disables the feature but does not have an associated migration. The second runs the migration.

**Review by ajwerner — COMMENTED** [review]
One area where this change needs validation is restore. Can we generate some backups with interleaved tables and then verify that you can restore them in the mixed version state if the version is correct but you cannot restore them after the version changes?

Another thing that came up was the possibility of silently ignoring `INTERLEAVE` statements at some point. We can do that as a follow-up but let's make sure we track it if that's the decision. 

> Reviewed 1 of 3 files at r3, 2 of 14 files at r5, 25 of 51 files at r7, 7 of 16 files at r9, 11 of 24 files at r10, 2 of 9 files at r12, 7 of 13 files at r14, 5 of 5 files at r15.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/68074#-:-MgunJJgCs_KF3CZbybl:bg354y6)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @fqazi, @irfansharif, @otan, and @postamar)

___
*[pkg/ccl/kvccl/kvtenantccl/tenant_upgrade_test.go, line 212 at r15](https://reviewable.io/reviews/cockroachdb/cockroach/68074#-MguiTKE3owAir2HjO3_:-MguiTKE3owAir2HjO3a:b4as5qr) ([raw file](https://github.com/cockroachdb/cockroach/blob/b7b3e7ca8e83d6f7bbb5d18f1eb729f3e63953de/pkg/ccl/kvccl/kvtenantccl/tenant_upgrade_test.go#L212)):*
> ```
> 	// Initialize the version to the BinaryMinSupportedVersion.
> 	require.NoError(t, clusterversion.Initialize(ctx,
> 		clusterversion.TestingBinaryMinSupportedVersion, &settings.SV))
> ```
Do we need to do this initialization?
___
*[pkg/ccl/kvccl/kvtenantccl/tenant_upgrade_test.go, line 247 at r15](https://reviewable.io/reviews/cockroachdb/cockroach/68074#-Mguh7cR6XKKjqpHmAgF:-Mguh7cS5_sjMHZHA8-H:b-itx16o) ([raw file](https://github.com/cockroachdb/cockroach/blob/b7b3e7ca8e83d6f7bbb5d18f1eb729f3e63953de/pkg/ccl/kvccl/kvtenantccl/tenant_upgrade_test.go#L247)):*
> ```Go
> 			false, // initializeVersion
> 		)
> 		tenantStopper := stop.NewStopper()
> ```

nit: consider calling this something like `v2onMigratation` or something that indicates the cause rather than the effect. I found it harder to follower. 
___
*[pkg/ccl/kvccl/kvtenantccl/tenant_upgrade_test.go, line 277 at r15](https://reviewable.io/reviews/cockroachdb/cockroach/68074#-Mguh-zx8CBjRoj-xa5Y:-Mguh-zyD0pe6W-e0H-N:bl9lsw1) ([raw file](https://github.com/cockroachdb/cockroach/blob/b7b3e7ca8e83d6f7bbb5d18f1eb729f3e63953de/pkg/ccl/kvccl/kvtenantccl/tenant_upgrade_test.go#L277)):*
> ```Go
> 						return migration.NewTenantMigration("testing next", clusterversion.ClusterVersion{
> 							Version: v2,
> 						},
> ```

nit: switch on the `cv.Version`
___
*[pkg/ccl/kvccl/kvtenantccl/tenant_upgrade_test.go, line 282 at r15](https://reviewable.io/reviews/cockroachdb/cockroach/68074#-Mguj2E-A__iCSSGFSp6:-Mguj2E-A__iCSSGFSp7:b-21dn1x) ([raw file](https://github.com/cockroachdb/cockroach/blob/b7b3e7ca8e83d6f7bbb5d18f1eb729f3e63953de/pkg/ccl/kvccl/kvtenantccl/tenant_upgrade_test.go#L282)):*
> ```Go
> 								ctx context.Context, version clusterversion.ClusterVersion, deps migration.TenantDeps,
> 							) error {
> 								tenantStopperChannel <- struct{}{}
> ```

there's a chance that this might be fragile in the face of retries. I'm not sure they'll happen but if you run into flakes, that could be it.
___
*[pkg/ccl/kvccl/kvtenantccl/tenant_upgrade_test.go, line 288 at r15](https://reviewable.io/reviews/cockroachdb/cockroach/68074#-MguiDn9DhKKQaZWV_F6:-MguiDn9DhKKQaZWV_F7:bnfcff8) ([raw file](https://github.com/cockroachdb/cockroach/blob/b7b3e7ca8e83d6f7bbb5d18f1eb729f3e63953de/pkg/ccl/kvccl/kvtenantccl/tenant_upgrade_test.go#L288)):*
> ```Go
> 				},
> 			},
> 			Settings: settings,
> ```

I think that this ends up being unfortunate. The reason is that it means that the host cluster and the tenants will all share a single in-memory settings object. When it changes for one, it will change for all. I think what we want is to create a new settings object for each of them. 
___
*[pkg/ccl/kvccl/kvtenantccl/tenant_upgrade_test.go, line 325 at r15](https://reviewable.io/reviews/cockroachdb/cockroach/68074#-MguhZ6P4PcRLSnYdK-0:-MguhZ6P4PcRLSnYdK-1:b-u4xkaz) ([raw file](https://github.com/cockroachdb/cockroach/blob/b7b3e7ca8e83d6f7bbb5d18f1eb729f3e63953de/pkg/ccl/kvccl/kvtenantccl/tenant_upgrade_test.go#L325)):*
> ```Go
> 			"SET CLUSTER SETTING version = $1",
> 			clusterversion.TestingBinaryVersion.String())
> 		tenantInfo.stopper.IsStopped()
> ```

This is a no-op
___
*[pkg/ccl/kvccl/kvtenantccl/tenant_upgrade_test.go, line 327 at r15](https://reviewable.io/reviews/cockroachdb/cockroach/68074#-MguhiJs1Chjy5h7Y1wM:-MguhiJs1Chjy5h7Y1wN:bn19q6v) ([raw file](https://github.com/cockroachdb/cockroach/blob/b7b3e7ca8e83d6f7bbb5d18f1eb729f3e63953de/pkg/ccl/kvccl/kvtenantccl/tenant_upgrade_test.go#L327)):*
> ```Go
> 		tenantInfo.stopper.IsStopped()
> 		cleanup()
> 		tenantInfo = mkTenant(t, initialTenantID, true)
> ```

nit comment this boolean or assign it to a const with a name.
___
*[pkg/migration/migrations/BUILD.bazel, line 76 at r15](https://reviewable.io/reviews/cockroachdb/cockroach/68074#-MgujclND1DKw3IAWcuZ:-MgujclND1DKw3IAWcu_:b-gg90nl) ([raw file](https://github.com/cockroachdb/cockroach/blob/b7b3e7ca8e83d6f7bbb5d18f1eb729f3e63953de/pkg/migration/migrations/BUILD.bazel#L76)):*
> ```Starlark
>         "//pkg/util/protoutil",
>         "@com_github_cockroachdb_errors//:errors",
>         "@com_github_pkg_errors//:errors",
> ```

I don't think this is the `errors` package you're looking for
___
*[pkg/migration/migrations/interleaved_tables.go, line 28 at r15](https://reviewable.io/reviews/cockroachdb/cockroach/68074#-Mguk7556C-0AtPijsOX:-Mguk7556C-0AtPijsOY:b5hp8jg) ([raw file](https://github.com/cockroachdb/cockroach/blob/b7b3e7ca8e83d6f7bbb5d18f1eb729f3e63953de/pkg/migration/migrations/interleaved_tables.go#L28)):*
> ```Go
> 	txn := d.DB.NewTxn(ctx, "interleaved-check")
> 	rows, err := d.InternalExecutor.QueryRowEx(ctx, "check-for-interleaved", txn, sessiondata.InternalExecutorOverride{User: security.RootUserName()},
> 		"SELECT * FROM crdb_internal.interleaved LIMIT 1;")
> ```

nit: if you aren't going to look at the values maybe just `SELECT EXISTS(SELECT * FROM crdb_internal.interleaved)` a check the bool. 
___
*[pkg/migration/migrations/interleaved_tables.go, line 33 at r15](https://reviewable.io/reviews/cockroachdb/cockroach/68074#-MgujyM-9dtAfTWYFoea:-MgujyM-9dtAfTWYFoeb:bpo43lf) ([raw file](https://github.com/cockroachdb/cockroach/blob/b7b3e7ca8e83d6f7bbb5d18f1eb729f3e63953de/pkg/migration/migrations/interleaved_tables.go#L33)):*
> ```Go
> 	}
> 	if rows != nil {
> 		return errors.Newf("interleaved tables are no longer supported at this version, please drop or uninterleave them.")
> ```

Can you give the user a hint to check `crdb_internal.interleaved` for a report on which tables need to be de-interleaved?
___
*[pkg/migration/migrations/interleaved_tables.go, line 35 at r15](https://reviewable.io/reviews/cockroachdb/cockroach/68074#-MgujprI7BR_dg5uHgX5:-MgujprI7BR_dg5uHgX6:b-opu1kd) ([raw file](https://github.com/cockroachdb/cockroach/blob/b7b3e7ca8e83d6f7bbb5d18f1eb729f3e63953de/pkg/migration/migrations/interleaved_tables.go#L35)):*
<details><summary><i alt="summary">Quoted 10 lines of code…</i></summary>

> ```
> 	txn := d.DB.NewTxn(ctx, "interleaved-check")
> 	rows, err := d.InternalExecutor.QueryRowEx(ctx, "check-for-interleaved", txn, sessiondata.InternalExecutorOverride{User: security.RootUserName()},
> 		"SELECT * FROM crdb_internal.interleaved LIMIT 1;")
> 	if err != nil {
> 		return err
> 	}
> 	if rows != nil {
> 		return errors.Newf("interleaved tables are no longer supported at this version, please drop or uninterleave them.")
> 	}
> 	return nil
> ```
</details>

This could use `d.DB.Txn` as opposed to `NewTxn`, however, better yet would be to pass `nil` for the `txn`.
___
*[pkg/migration/migrations/interleaved_tables_external_test.go, line 56 at r15](https://reviewable.io/reviews/cockroachdb/cockroach/68074#-Mgum7-v1xLl9p4v0nG_:-Mgum7-v1xLl9p4v0nGa:bs28he) ([raw file](https://github.com/cockroachdb/cockroach/blob/b7b3e7ca8e83d6f7bbb5d18f1eb729f3e63953de/pkg/migration/migrations/interleaved_tables_external_test.go#L56)):*
> ```
> 	// Migration should succeed to the first phase disabled CREATE INTERLEAVED's.
> 	tdb.ExecSucceedsSoon(t, "SET CLUSTER SETTING version = $1",
> 		clusterversion.ByKey(clusterversion.PreventNewInterleavedTables).String())
> ```
Can you first try to go all the way to the second one to test the pre-condition and then verify that we can still create a new interleaved table. 
___
*[pkg/migration/migrations/interleaved_tables_external_test.go, line 65 at r15](https://reviewable.io/reviews/cockroachdb/cockroach/68074#-MgumN8O-B4XiF3XRaoO:-MgumN8O-B4XiF3XRaoP:b-3ps8px) ([raw file](https://github.com/cockroachdb/cockroach/blob/b7b3e7ca8e83d6f7bbb5d18f1eb729f3e63953de/pkg/migration/migrations/interleaved_tables_external_test.go#L65)):*
> ```
> 	tdb.ExecSucceedsSoon(t, `DROP TABLE orders;`)
> 	tdb.ExecSucceedsSoon(t, `DROP TABLE customers;`)
> ```
Can you de-interleave the table with `ALTER PRIMARY KEY` instead of dropping it?
___
*[pkg/sql/set_cluster_setting.go, line 234 at r15](https://reviewable.io/reviews/cockroachdb/cockroach/68074#-MgumeT72V6NTAD6KkHJ:-MgumeT72V6NTAD6KkHK:b-72u4nw) ([raw file](https://github.com/cockroachdb/cockroach/blob/b7b3e7ca8e83d6f7bbb5d18f1eb729f3e63953de/pkg/sql/set_cluster_setting.go#L234)):*
> ```Go
> 
> 			if isSetVersion {
> 				updateSystemVersionSetting := func(ctx context.Context, version clusterversion.ClusterVersion) error {
> ```

I don't think I understand the word `system` here.

This all feels like it deserves a relatively large block of commentary. Are we doing this on the host and the tenant? If so, why the closure?

File: pkg/sql/logictest/testdata/logic_test/name_escapes [hunk 3]
```diff
@@ -15,7 +15,7 @@ CREATE TABLE unused3(x INT, y INT, FAMILY woo " (x, y),
   CONSTRAINT "getmeoutofhere PRIMARY KEY (x ASC)); -- saveme!
 DROP USER madhatter;
 CREATE TABLE unused4(x INT, CONSTRAINT woo " PRIMARY KEY (x)
-) INTERLEAVE IN PARENT "woo; DROP USER humpty;" (x);
+);
```
Comment (postamar) [inline pkg/sql/logictest/testdata/logic_test/name_escapes:18]: You can remove the whole CREATE TABLE statement here.

File: pkg/sql/logictest/testdata/logic_test/name_escapes [hunk 4]
```diff
@@ -37,7 +37,7 @@ DROP USER queenofhearts;
 CREATE TABLE unused3(x INT, y INT, FAMILY woo " (x, y, "welp INT); -- concerning much
 DROP USER dumpty;
 CREATE TABLE unused (x ")
-) INTERLEAVE IN PARENT public."woo; DROP USER humpty;" (x)
+)
```
Comment (postamar) [inline pkg/sql/logictest/testdata/logic_test/name_escapes:40]: You can remove the whole CREATE TABLE statement here.

File: pkg/sql/revert_test.go [hunk 5]
```diff
@@ -40,7 +42,15 @@ func TestRevertTable(t *testing.T) {
 	ctx := context.Background()
 
 	s, sqlDB, kv := serverutils.StartServer(
-		t, base.TestServerArgs{UseDatabase: "test"})
+		t,
+		base.TestServerArgs{
+			Knobs: base.TestingKnobs{
+				Server: &server.TestingKnobs{
+					DisableAutomaticVersionUpgrade: 1,
+					BinaryVersionOverride:          clusterversion.ByKey(clusterversion.PreventNewInterleavedTables - 1),
```
Comment (postamar) [inline pkg/sql/revert_test.go:50]: Is this change intentional? Shouldn't you instead be removing the `"interleaved"` subtest?

File: pkg/sql/row/fetcher_mvcc_test.go [hunk 6]
```diff
@@ -1,212 +0,0 @@
...
-	if actual, expected := kvsToRows(slurpUserDataKVs(t, store.Engine())), []rowWithMVCCMetadata{
-		{[]string{`1`, `NULL`, `NULL`, `NULL`}, true, ts3},
-		{[]string{`1`, `10`}, false, ts1},
-		{[]string{`2`, `b`, `b`, `NULL`}, false, ts2},
-		{[]string{`2`, `20`}, true, ts2}, // ignore me: artifact of how the test is written
-		{[]string{`2`, `21`}, true, ts3},
-	}; !reflect.DeepEqual(expected, actual) {
-		t.Errorf(`expected %v got %v`, expected, actual)
-	}
-}
```
Comment (postamar) [inline pkg/sql/row/fetcher_mvcc_test.go:212]: It seems (at first glance at least) that this test should remain, probably just with one table instead of two. It seems to me that it exercises more than just interleave-related functionality.

File: pkg/sql/rowenc/index_encoding.go [hunk 7]
```diff
@@ -1702,53 +1702,6 @@ func maxKeyTokens(index catalog.Index, containsNull bool) int {
...
-	// len(keyTokens) > nIndexTokens, so this must be a child key.
-	// Transform /1/#/2 --> /2.
-	firstNTokenLen := 0
-	for _, token := range keyTokens[:nIndexTokens] {
-		firstNTokenLen += len(token)
-	}
-
-	return start[:firstNTokenLen].PrefixEnd(), nil
-}
-
```
Comment (postamar) [inline pkg/sql/rowenc/index_encoding.go:1751]: Shouldn't `AdjustEndKeyForInterleave` defined below also be deleted?

File: pkg/sql/schema_changer_test.go [hunk 8]
```diff
@@ -4245,6 +4247,12 @@ func TestTruncateInterleavedTables(t *testing.T) {
 
 	params, _ := tests.CreateTestServerParams()
 	// Decrease the adopt loop interval so that retries happen quickly.
+	params.Knobs = base.TestingKnobs{
+		Server: &server.TestingKnobs{
+			DisableAutomaticVersionUpgrade: 1,
+			BinaryVersionOverride:          clusterversion.ByKey(clusterversion.PreventNewInterleavedTables - 1),
+		},
+	}
```
Comment (postamar) [inline pkg/sql/schema_changer_test.go:4255]: Why not remove this test altogether?

**Review by postamar — COMMENTED** [review]
I did another pass mostly looking at tests.

**Review by fqazi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/68074)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @fqazi, @irfansharif, @otan, and @postamar)

___
*[pkg/ccl/kvccl/kvtenantccl/tenant_upgrade_test.go, line 212 at r15](https://reviewable.io/reviews/cockroachdb/cockroach/68074#-MguiTKE3owAir2HjO3_:-Mgvr5Mk6e1tf9wOFdaf:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/b7b3e7ca8e83d6f7bbb5d18f1eb729f3e63953de/pkg/ccl/kvccl/kvtenantccl/tenant_upgrade_test.go#L212)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

> ```
> 	// Initialize the version to the BinaryMinSupportedVersion.
> 	require.NoError(t, clusterversion.Initialize(ctx,
> 		clusterversion.TestingBinaryMinSupportedVersion, &settings.SV))
> ```
Do we need to do this initialization?
</blockquote></details>

Done.
___
*[pkg/ccl/kvccl/kvtenantccl/tenant_upgrade_test.go, line 247 at r15](https://reviewable.io/reviews/cockroachdb/cockroach/68074#-Mguh7cR6XKKjqpHmAgF:-Mgvr7gcEXripCi-_HSb:bb6un1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/b7b3e7ca8e83d6f7bbb5d18f1eb729f3e63953de/pkg/ccl/kvccl/kvtenantccl/tenant_upgrade_test.go#L247)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

nit: consider calling this something like `v2onMigratation` or something that indicates the cause rather than the effect. I found it harder to follower. 
</blockquote></details>

Done
___
*[pkg/ccl/kvccl/kvtenantccl/tenant_upgrade_test.go, line 288 at r15](https://reviewable.io/reviews/cockroachdb/cockroach/68074#-MguiDn9DhKKQaZWV_F6:-MgvqsMT7cFo-4bjbfVQ:bkoor71) ([raw file](https://github.com/cockroachdb/cockroach/blob/b7b3e7ca8e83d6f7bbb5d18f1eb729f3e63953de/pkg/ccl/kvccl/kvtenantccl/tenant_upgrade_test.go#L288)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

I think that this ends up being unfortunate. The reason is that it means that the host cluster and the tenants will all share a single in-memory settings object. When it changes for one, it will change for all. I think what we want is to create a new settings object for each of them. 
</blockquote></details>

There is a different seeings object for the tenant versus the cluster in the test? Or am I misinterpreting the comment?
___
*[pkg/clusterversion/cockroach_versions.go, line 272 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/68074#-MfZ5vyBN_VVXUuX5KVs-r8-272:-MgGx5Gf18ytpdJ1JeK5:b8n86tc) ([raw file](https://github.com/cockroachdb/cockroach/blob/4430141eda66207444517d20301b10db51cd09ce/pkg/clusterversion/cockroach_versions.go#L272)):*
> PreventNewInterleavedTables
Those are much better names, let me do that.
___
*[pkg/migration/migrationmanager/manager.go, line 249 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/68074#-MfdRUlw5jZ57iwX3-im-r8-249:-MgH2JdnBSHvBrRyjPL8:b-htlbjn) ([raw file](https://github.com/cockroachdb/cockroach/blob/4430141eda66207444517d20301b10db51cd09ce/pkg/migration/migrationmanager/manager.go#L249)):*
<details><summary><i>Previously, irfansharif (irfan sharif) wrote…</i></summary><blockquote>

I'm not sure if this is sound, and I'm not sure that using this return value to decide whether or not to update system.settings is sound either. The guarantees we want to provide at the level of `(*Manager) Migrate` is that it should be completely idempotent. With the hook passed in, I think we want to instead check that the version stored in system.settings is less than the version we're trying to set it to.
</blockquote></details>

Good point, let me scan first and then update
___
*[pkg/migration/migrations/interleaved_tables.go, line 47 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/68074#-MfZDAfF4QirNGocM8_A:-MfZWe5z8rpUz7Ct8KhO:b-c3sop1) ([raw file](https://github.com/cockroachdb/cockroach/blob/5532c422de0c0d8dde4afad5bce17b00c54586bc/pkg/migration/migrations/interleaved_tables.go#L47)):*
<details><summary><i>Previously, fqazi (Faizan Qazi) wrote…</i></summary><blockquote>

> ably preferably, consider bypassing the table and instead reimplement the logi
We can't drop the internal table yet? If you haven't gone past this migration you still need that function to figure out the source of your problem. I think once your past this point on the next release we can drop all the code right?

Let me dig into using the code from the CRDB function directly, or confirm if the limit clause is sufficient.
</blockquote></details>

Done. Validated the limit clause works correctly, and stops execution instantly.
___
*[pkg/migration/migrations/interleaved_tables.go, line 27 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/68074#-MfZ5vyBN_VVXUuX5KVt-r8-27:-MgGxYHK5zKk5Gqm0G57:bb6un1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/4430141eda66207444517d20301b10db51cd09ce/pkg/migration/migrations/interleaved_tables.go#L27)):*
<details><summary><i>Previously, irfansharif (irfan sharif) wrote…</i></summary><blockquote>

Next? For this error, it's not possible for this migration code path to have executed if `clusterversion.InterleavedCreationBlockedMigration` is not active. The migrations infrastructure steps through defined migrations in version order.
</blockquote></details>

Done
___
*[pkg/migration/migrations/interleaved_tables_external_test.go, line 122 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/68074#-MfZFAzw4WbV5grmAK6m:-MfZWo960s-6bFmPMvhp:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/5532c422de0c0d8dde4afad5bce17b00c54586bc/pkg/migration/migrations/interleaved_tables_external_test.go#L122)):*
<details><summary><i>Previously, fqazi (Faizan Qazi) wrote…</i></summary><blockquote>

3) Linked to the issue for this work in the commit message (I will open a separate one for code clean up after the next release to kill all code for interleaved tables).
4) Sorry, I should have added more detail. Updated the language for release notes based on our documentation.

</blockquote></details>

Done.
___
*[pkg/migration/migrations/interleaved_tables_external_test.go, line 56 at r15](https://reviewable.io/reviews/cockroachdb/cockroach/68074#-Mgum7-v1xLl9p4v0nG_:-MgvqL0p80dDcT6HYdrn:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/b7b3e7ca8e83d6f7bbb5d18f1eb729f3e63953de/pkg/migration/migrations/interleaved_tables_external_test.go#L56)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

> ```
> 	// Migration should succeed to the first phase disabled CREATE INTERLEAVED's.
> 	tdb.ExecSucceedsSoon(t, "SET CLUSTER SETTING version = $1",
> 		clusterversion.ByKey(clusterversion.PreventNewInterleavedTables).String())
> ```
Can you first try to go all the way to the second one to test the pre-condition and then verify that we can still create a new interleaved table. 
</blockquote></details>

Done.
___
*[pkg/migration/migrations/interleaved_tables_external_test.go, line 65 at r15](https://reviewable.io/reviews/cockroachdb/cockroach/68074#-MgumN8O-B4XiF3XRaoO:-MgvqM051jAk26XUFB4M:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/b7b3e7ca8e83d6f7bbb5d18f1eb729f3e63953de/pkg/migration/migrations/interleaved_tables_external_test.go#L65)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

> ```
> 	tdb.ExecSucceedsSoon(t, `DROP TABLE orders;`)
> 	tdb.ExecSucceedsSoon(t, `DROP TABLE customers;`)
> ```
Can you de-interleave the table with `ALTER PRIMARY KEY` instead of dropping it?
</blockquote></details>

Done.
___
*[pkg/migration/migrations/migrations.go, line 86 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/68074#-MfZ5vyBN_VVXUuX5KVv-r8-86:-Mgvr3ySDGqdBFeZ8w4m:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/4430141eda66207444517d20301b10db51cd09ce/pkg/migration/migrations/migrations.go#L86)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

There are two cluster versions. The first disables the feature but does not have an associated migration. The second runs the migration. 
</blockquote></details>

Done.
___
*[pkg/sql/crdb_internal.go, line 4538 at r15](https://reviewable.io/reviews/cockroachdb/cockroach/68074#-MfZ5vyBN_VVXUuX5KVx-r15-4538:-MgvqRk23I2POM8eaFw_:bz9d86c) ([raw file](https://github.com/cockroachdb/cockroach/blob/b7b3e7ca8e83d6f7bbb5d18f1eb729f3e63953de/pkg/sql/crdb_internal.go#L4538)):*
<details><summary><i>Previously, postamar (Marius Posta) wrote…</i></summary><blockquote>

What motivates this change? It's not obvious, and if intentional, is worthy of a comment.

Perhaps related: is there any point in maintaining this table? In other words, is there anything preventing us from removing it in this PR? I did a full codebase search and it doesn't seem to be queried much.
</blockquote></details>

If the migration stops because of interleaved tables, then a user can use this table to figure out which table caused the issue. This change was made so that indexes in an ADD state are also visible.
___
*[pkg/sql/revert_test.go, line 50 at r15](https://reviewable.io/reviews/cockroachdb/cockroach/68074#-Mfc74D5M0r0amwr36Zq-r15-50:-MgvqbKT0P_Hvc_fDDUR:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/b7b3e7ca8e83d6f7bbb5d18f1eb729f3e63953de/pkg/sql/revert_test.go#L50)):*
<details><summary><i>Previously, postamar (Marius Posta) wrote…</i></summary><blockquote>

Is this change intentional? Shouldn't you instead be removing the `"interleaved"` subtest?
</blockquote></details>

Done.
___
*[pkg/sql/schema_changer_test.go, line 4255 at r15](https://reviewable.io/reviews/cockroachdb/cockroach/68074#-Mfc74D5M0r0amwr36Zr-r15-4255:-Mgvqc6M2RPf_zBmO4z4:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/b7b3e7ca8e83d6f7bbb5d18f1eb729f3e63953de/pkg/sql/schema_changer_test.go#L4255)):*
<details><summary><i>Previously, postamar (Marius Posta) wrote…</i></summary><blockquote>

Why not remove this test altogether?
</blockquote></details>

Done.
___
*[pkg/sql/set_cluster_setting.go, line 234 at r15](https://reviewable.io/reviews/cockroachdb/cockroach/68074#-MgumeT72V6NTAD6KkHJ:-MgvqfAS9hPIS42oe6zF:b-ryq9l3) ([raw file](https://github.com/cockroachdb/cockroach/blob/b7b3e7ca8e83d6f7bbb5d18f1eb729f3e63953de/pkg/sql/set_cluster_setting.go#L234)):*
<details><summary><i alt="summary">Quoted 5 lines of code…</i></summary>

> ```
> 				// Updates the version setting on either the host or
> 				// the tenant. This updates the version setting only on
> 				// the current pod and does not reach out to other ones.
> 				// To make sure this change is idempotent, we check if
> 				// the version nubmer is already is set.
> ```
</details>

This this makes it clearer:
				// Updates the version setting on either the host or
				// the tenant. This updates the version setting only on
				// the current pod and does not reach out to other ones.
				// To make sure this change is idempotent, we check if
				// the version nubmer is already is set.
___
*[pkg/sql/logictest/testdata/logic_test/name_escapes, line 18 at r15](https://reviewable.io/reviews/cockroachdb/cockroach/68074#-MgGkVcc96sRtkoBM7jk-r15-18:-MgvqjO37RwhRLTEy0VG:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/b7b3e7ca8e83d6f7bbb5d18f1eb729f3e63953de/pkg/sql/logictest/testdata/logic_test/name_escapes#L18)):*
<details><summary><i>Previously, postamar (Marius Posta) wrote…</i></summary><blockquote>

You can remove the whole CREATE TABLE statement here.
</blockquote></details>

Done.
___
*[pkg/sql/logictest/testdata/logic_test/name_escapes, line 40 at r15](https://reviewable.io/reviews/cockroachdb/cockroach/68074#-MgGkVcc96sRtkoBM7jk-r15-40:-Mgvqn1DEszktwsrHlxn:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/b7b3e7ca8e83d6f7bbb5d18f1eb729f3e63953de/pkg/sql/logictest/testdata/logic_test/name_escapes#L40)):*
<details><summary><i>Previously, postamar (Marius Posta) wrote…</i></summary><blockquote>

You can remove the whole CREATE TABLE statement here.
</blockquote></details>

Done.

**Review by postamar — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/68074)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @fqazi, @irfansharif, @otan, and @postamar)

___
*[pkg/sql/crdb_internal.go, line 4538 at r15](https://reviewable.io/reviews/cockroachdb/cockroach/68074#-MfZ5vyBN_VVXUuX5KVx-r15-4538:-Mgw4613Cmt81z5bBk7w:bimq9t3) ([raw file](https://github.com/cockroachdb/cockroach/blob/b7b3e7ca8e83d6f7bbb5d18f1eb729f3e63953de/pkg/sql/crdb_internal.go#L4538)):*
<details><summary><i>Previously, fqazi (Faizan Qazi) wrote…</i></summary><blockquote>

If the migration stops because of interleaved tables, then a user can use this table to figure out which table caused the issue. This change was made so that indexes in an ADD state are also visible.
</blockquote></details>

FYI `NonDropIndexes` will include indexes in an `ADD` state.

**Review by fqazi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/68074)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @fqazi, @irfansharif, @otan, and @postamar)

___
*[pkg/sql/crdb_internal.go, line 4538 at r15](https://reviewable.io/reviews/cockroachdb/cockroach/68074#-MfZ5vyBN_VVXUuX5KVx-r15-4538:-Mgw7pMS90fl_H7ir5Rw:b-tgqq1y) ([raw file](https://github.com/cockroachdb/cockroach/blob/b7b3e7ca8e83d6f7bbb5d18f1eb729f3e63953de/pkg/sql/crdb_internal.go#L4538)):*
<details><summary><i>Previously, postamar (Marius Posta) wrote…</i></summary><blockquote>

FYI `NonDropIndexes` will include indexes in an `ADD` state.
</blockquote></details>

I meant ones in DROP state. We make sure those are fully removed, or that was the concern that Andrew had.

**Review by ajwerner — COMMENTED** [review]
> Reviewed 1 of 34 files at r16, 8 of 76 files at r20.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/68074)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @fqazi, @irfansharif, @otan, and @postamar)

___
*[pkg/ccl/kvccl/kvtenantccl/tenant_upgrade_test.go, line 288 at r15](https://reviewable.io/reviews/cockroachdb/cockroach/68074#-MguiDn9DhKKQaZWV_F6:-MhGCeak4uOWUE82U2cD:b-tjdktf) ([raw file](https://github.com/cockroachdb/cockroach/blob/b7b3e7ca8e83d6f7bbb5d18f1eb729f3e63953de/pkg/ccl/kvccl/kvtenantccl/tenant_upgrade_test.go#L288)):*
<details><summary><i>Previously, fqazi (Faizan Qazi) wrote…</i></summary><blockquote>

There is a different seeings object for the tenant versus the cluster in the test? Or am I misinterpreting the comment?
</blockquote></details>

This looks good now. I might have been confused earlier. 
___
*[pkg/migration/migrations/interleaved_tables.go, line 27 at r20](https://reviewable.io/reviews/cockroachdb/cockroach/68074#-MhGCxLgAv34vRkv29mD:-MhGCxLgAv34vRkv29mE:b-do48lv) ([raw file](https://github.com/cockroachdb/cockroach/blob/9bf0f8d40ef34cd9e2f25b22d5633c4f8a609534/pkg/migration/migrations/interleaved_tables.go#L27)):*
> ```Go
> 	ctx context.Context, _ clusterversion.ClusterVersion, d migration.TenantDeps,
> ) error {
> 	rows, err := d.InternalExecutor.QueryRowEx(ctx, "check-for-interleaved", nil, sessiondata.InternalExecutorOverride{User: security.RootUserName()},
> ```

nit: wrap the long line
___
*[pkg/sql/crdb_internal.go, line 4538 at r15](https://reviewable.io/reviews/cockroachdb/cockroach/68074#-MfZ5vyBN_VVXUuX5KVx-r15-4538:-MhGBnTWCaiFLreJbR3K:bima6y6) ([raw file](https://github.com/cockroachdb/cockroach/blob/b7b3e7ca8e83d6f7bbb5d18f1eb729f3e63953de/pkg/sql/crdb_internal.go#L4538)):*
<details><summary><i>Previously, fqazi (Faizan Qazi) wrote…</i></summary><blockquote>

I meant ones in DROP state. We make sure those are fully removed, or that was the concern that Andrew had.
</blockquote></details>

Yeah, consider the case where you drop and index in a schema change that adds another index and then that gets reverted then the index comes back. 
___
*[pkg/sql/set_cluster_setting.go, line 234 at r15](https://reviewable.io/reviews/cockroachdb/cockroach/68074#-MgumeT72V6NTAD6KkHJ:-MhGD9hREDUwpyWWt_oD:b-679pwc) ([raw file](https://github.com/cockroachdb/cockroach/blob/b7b3e7ca8e83d6f7bbb5d18f1eb729f3e63953de/pkg/sql/set_cluster_setting.go#L234)):*
> ```
> 				// the tenant. This updates the version setting only on
> 				// the current pod and does not reach out to other ones.
This function does not seem to do what this comment says. Namely, it writes the new version to the settings table. It doesn't do anything about setting the version for the local process at all. 
Also, how does this have anything to do with "Tenant"?

**Review by fqazi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/68074)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @irfansharif, @otan, and @postamar)

___
*[pkg/migration/migrations/interleaved_tables.go, line 47 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/68074#-MfZDAfF4QirNGocM8_A:-MhOVvxd3mxkEVAqmOkZ:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/5532c422de0c0d8dde4afad5bce17b00c54586bc/pkg/migration/migrations/interleaved_tables.go#L47)):*
<details><summary><i>Previously, fqazi (Faizan Qazi) wrote…</i></summary><blockquote>

Done. Validated the limit clause works correctly, and stops execution instantly.
</blockquote></details>

Done.
___
*[pkg/sql/crdb_internal.go, line 4538 at r15](https://reviewable.io/reviews/cockroachdb/cockroach/68074#-MfZ5vyBN_VVXUuX5KVx-r15-4538:-MhOVxWOAwGKBUpeOgna:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/b7b3e7ca8e83d6f7bbb5d18f1eb729f3e63953de/pkg/sql/crdb_internal.go#L4538)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

Yeah, consider the case where you drop and index in a schema change that adds another index and then that gets reverted then the index comes back. 
</blockquote></details>

Done.

**Review by ajwerner — APPROVED** [review]
:lgtm:

> Another thing that came up was the possibility of silently ignoring INTERLEAVE statements at some point. We can do that as a follow-up but let's make sure we track it if that's the decision.

Did we track this?

> Reviewed 1 of 34 files at r16, 40 of 76 files at r20, 4 of 14 files at r22, 1 of 8 files at r23, 1 of 8 files at r25.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/68074#-:-MhOycG1530Pjf7cc_jd:b2ylv5c)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ajwerner, @fqazi, @irfansharif, @otan, and @postamar)

___
*[pkg/ccl/kvccl/kvtenantccl/tenant_upgrade_test.go, line 260 at r25](https://reviewable.io/reviews/cockroachdb/cockroach/68074#-MhOwClZ2er4iXKNQ-iL:-MhOwClZ2er4iXKNQ-iM:bd04er1) ([raw file](https://github.com/cockroachdb/cockroach/blob/d7cb6e59090d6eb18fd7b5dfc2554d857462b928/pkg/ccl/kvccl/kvtenantccl/tenant_upgrade_test.go#L260)):*
> ```
> 						if !cv.Version.Equal(v1) && !cv.Version.Equal(v2) {
> 							return nil, false
> 						}
> ```
nit: just make this the default case.
___
*[pkg/ccl/kvccl/kvtenantccl/tenant_upgrade_test.go, line 324 at r25](https://reviewable.io/reviews/cockroachdb/cockroach/68074#-MhOwQcBCoMEmligYzCI:-MhOwQcBCoMEmligYzCJ:b-sedpo3) ([raw file](https://github.com/cockroachdb/cockroach/blob/d7cb6e59090d6eb18fd7b5dfc2554d857462b928/pkg/ccl/kvccl/kvtenantccl/tenant_upgrade_test.go#L324)):*
> ```Go
> 		// will fail on v1.
> 		initialTenantRunner.ExpectErr(t,
> 			".*(sql: database is closed)*(failed to connect)*.*",
> ```

This will match literally any string. What about `sql: database is closed|failed to connect`. 
___
*[pkg/migration/migrations/interleaved_tables_external_test.go, line 84 at r25](https://reviewable.io/reviews/cockroachdb/cockroach/68074#-MhOyVx16L72KTxzChtV:-MhOyVx26ytft4w9yaqN:b-dkkeq1) ([raw file](https://github.com/cockroachdb/cockroach/blob/d7cb6e59090d6eb18fd7b5dfc2554d857462b928/pkg/migration/migrations/interleaved_tables_external_test.go#L84)):*
> ```Go
> 	})
> 	// Check that creation of interleaved tables is fully disabled.
> 	tdb.ExecSucceedsSoon(t, "CREATE TABLE customers2 (id INT PRIMARY KEY, name STRING(50));")
> ```

Does this needs a succeeds soon?

**Review by fqazi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/68074)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ajwerner, @irfansharif, @otan, and @postamar)

___
*[pkg/ccl/kvccl/kvtenantccl/tenant_upgrade_test.go, line 324 at r25](https://reviewable.io/reviews/cockroachdb/cockroach/68074#-MhOwQcBCoMEmligYzCI:-MhP0gJc70Nhbt6Ld3gG:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/d7cb6e59090d6eb18fd7b5dfc2554d857462b928/pkg/ccl/kvccl/kvtenantccl/tenant_upgrade_test.go#L324)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

This will match literally any string. What about `sql: database is closed|failed to connect`. 
</blockquote></details>

Done.
___
*[pkg/clusterversion/cockroach_versions.go, line 272 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/68074#-MfZ5vyBN_VVXUuX5KVs-r8-272:-MhP0i7xAqGgCNoaQ0Z8:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/4430141eda66207444517d20301b10db51cd09ce/pkg/clusterversion/cockroach_versions.go#L272)):*
<details><summary><i>Previously, fqazi (Faizan Qazi) wrote…</i></summary><blockquote>

> PreventNewInterleavedTables
Those are much better names, let me do that.
</blockquote></details>

Done.

**Comment by fqazi** [comment]
> > Another thing that came up was the possibility of silently ignoring INTERLEAVE statements at some point. We can do that as a follow-up but let's make sure we track it if that's the decision.
> 
> Did we track this?
@ajwerner The issue https://github.com/cockroachdb/cockroach/issues/68344 tracks this

**Comment by fqazi** [comment]
bors cancel
