### PR TITLE
roachtest: improve binaryUpgradeStep

### LINKED ISSUE #52760: roachtest: decommission/mixed-versions failed
[(roachtest).decommission/mixed-versions failed](https://teamcity.cockroachdb.com/viewLog.html?buildId=2177056&tab=buildLog) on [master@457f1af5d19e0bcef9b5ea9e9125b3332717a86c](https://github.com/cockroachdb/cockroach/commits/457f1af5d19e0bcef9b5ea9e9125b3332717a86c):

```
The test failed on branch=master, cloud=gce:
test artifacts and logs in: /home/agent/work/.go/src/github.com/cockroachdb/cockroach/artifacts/decommission/mixed-versions/run_1
	cluster.go:1900,versionupgrade.go:226,versionupgrade.go:305,versionupgrade.go:167,mixed_version_decommission.go:118,decommission.go:73,test_runner.go:754: cluster.Put: /home/agent/work/.go/src/github.com/cockroachdb/cockroach/bin/roachprod put teamcity-2177056-1597299797-06-n4cpu4:1-4 /home/agent/temp/buildTmp/cockroach-v20.1.4.linux-amd64 ./cockroach-20.1.4 returned: exit status 1
		(1) attached stack trace
		  | main.(*cluster).PutE
		  | 	/home/agent/work/.go/src/github.com/cockroachdb/cockroach/pkg/cmd/roachtest/cluster.go:1915
		  | main.(*cluster).Put
		  | 	/home/agent/work/.go/src/github.com/cockroachdb/cockroach/pkg/cmd/roachtest/cluster.go:1899
		  | main.(*versionUpgradeTest).uploadVersion
		  | 	/home/agent/work/.go/src/github.com/cockroachdb/cockroach/pkg/cmd/roachtest/versionupgrade.go:226
		  | main.binaryUpgradeStep.func1
		  | 	/home/agent/work/.go/src/github.com/cockroachdb/cockroach/pkg/cmd/roachtest/versionupgrade.go:305
		  | main.(*versionUpgradeTest).run
		  | 	/home/agent/work/.go/src/github.com/cockroachdb/cockroach/pkg/cmd/roachtest/versionupgrade.go:167
		  | main.runDecommissionMixedVersions
		  | 	/home/agent/work/.go/src/github.com/cockroachdb/cockroach/pkg/cmd/roachtest/mixed_version_decommission.go:118
		  | main.registerDecommission.func3
		  | 	/home/agent/work/.go/src/github.com/cockroachdb/cockroach/pkg/cmd/roachtest/decommission.go:73
		  | main.(*testRunner).runTest.func2
		  | 	/home/agent/work/.go/src/github.com/cockroachdb/cockroach/pkg/cmd/roachtest/test_runner.go:754
		  | runtime.goexit
		  | 	/usr/local/go/src/runtime/asm_amd64.s:1357
		Wraps: (2) cluster.Put
		Wraps: (3) /home/agent/work/.go/src/github.com/cockroachdb/cockroach/bin/roachprod put teamcity-2177056-1597299797-06-n4cpu4:1-4 /home/agent/temp/buildTmp/cockroach-v20.1.4.linux-amd64 ./cockroach-20.1.4 returned
		  | stderr:
		  |
		  | stdout:
		  | teamcity-2177056-1597299797-06-n4cpu4: putting (dist) /home/agent/temp/buildTmp/cockroach-v20.1.4.linux-amd64 ./cockroach-20.1.4
		  | ............
		  |    1: done
		  |    2: ~ scp -r -C -o StrictHostKeyChecking=no -i /root/.ssh/id_rsa -i /root/.ssh/google_compute_engine ubuntu@34.71.117.105:./cockroach-20.1.4 ubuntu@35.225.3.94:./cockroach-20.1.4
		  | scp: ./cockroach-20.1.4: Text file busy
		  | : exit status 1
		  |    3: ~ scp -r -C -o StrictHostKeyChecking=no -i /root/.ssh/id_rsa -i /root/.ssh/google_compute_engine ubuntu@34.71.117.105:./cockroach-20.1.4 ubuntu@35.238.59.77:./cockroach-20.1.4
		  | scp: ./cockroach-20.1.4: Text file busy
		  | : exit status 1
		  |    4: done
		  | I200813 06:27:45.203571 1 cluster_synced.go:1168  put /home/agent/temp/buildTmp/cockroach-v20.1.4.linux-amd64 failed
		Wraps: (4) exit status 1
		Error types: (1) *withstack.withStack (2) *errutil.withMessage (3) *main.withCommandDetails (4) *exec.ExitError

```

<details><summary>More</summary><p>

Artifacts: [/decommission/mixed-versions](https://teamcity.cockroachdb.com/viewLog.html?buildId=2177056&tab=artifacts#/decommission/mixed-versions)

[See this test on roachdash](https://roachdash.crdb.dev/?filter=status%3Aopen+t%3A.%2Adecommission%2Fmixed-versions.%2A&sort=title&restgroup=false&display=lastcommented+project)
<sub>powered by [pkg/cmd/internal/issues](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)</sub></p></details>

### LINKED ISSUE #53617: roachtest: join-init/mixed failed
[(roachtest).join-init/mixed failed](https://teamcity.cockroachdb.com/viewLog.html?buildId=2231078&tab=buildLog) on [master@8b91062f9351d18f9104aff567cb152df162021e](https://github.com/cockroachdb/cockroach/commits/8b91062f9351d18f9104aff567cb152df162021e):

```
The test failed on branch=master, cloud=gce:
test artifacts and logs in: /home/agent/work/.go/src/github.com/cockroachdb/cockroach/artifacts/join-init/mixed/run_1
	cluster.go:1916,versionupgrade.go:245,versionupgrade.go:324,versionupgrade.go:186,mixed_version_join_init.go:137,mixed_version_join_init.go:33,test_runner.go:754: cluster.Put: /home/agent/work/.go/src/github.com/cockroachdb/cockroach/bin/roachprod put teamcity-2231078-1598711360-14-n4cpu4:1-3 /home/agent/work/.go/src/github.com/cockroachdb/cockroach/cockroach.linux-2.6.32-gnu-amd64 ./cockroach returned: exit status 1
		(1) attached stack trace
		  -- stack trace:
		  | main.(*cluster).PutE
		  | 	/home/agent/work/.go/src/github.com/cockroachdb/cockroach/pkg/cmd/roachtest/cluster.go:1931
		  | main.(*cluster).Put
		  | 	/home/agent/work/.go/src/github.com/cockroachdb/cockroach/pkg/cmd/roachtest/cluster.go:1915
		  | main.(*versionUpgradeTest).uploadVersion
		  | 	/home/agent/work/.go/src/github.com/cockroachdb/cockroach/pkg/cmd/roachtest/versionupgrade.go:245
		  | main.binaryUpgradeStep.func1
		  | 	/home/agent/work/.go/src/github.com/cockroachdb/cockroach/pkg/cmd/roachtest/versionupgrade.go:324
		  | main.(*versionUpgradeTest).run
		  | 	/home/agent/work/.go/src/github.com/cockroachdb/cockroach/pkg/cmd/roachtest/versionupgrade.go:186
		  | main.runJoinInitMixed
		  | 	/home/agent/work/.go/src/github.com/cockroachdb/cockroach/pkg/cmd/roachtest/mixed_version_join_init.go:137
		  | main.registerJoinInitMixed.func1
		  | 	/home/agent/work/.go/src/github.com/cockroachdb/cockroach/pkg/cmd/roachtest/mixed_version_join_init.go:33
		  | main.(*testRunner).runTest.func2
		  | 	/home/agent/work/.go/src/github.com/cockroachdb/cockroach/pkg/cmd/roachtest/test_runner.go:754
		  | runtime.goexit
		  | 	/usr/local/go/src/runtime/asm_amd64.s:1357
		Wraps: (2) cluster.Put
		Wraps: (3) /home/agent/work/.go/src/github.com/cockroachdb/cockroach/bin/roachprod put teamcity-2231078-1598711360-14-n4cpu4:1-3 /home/agent/work/.go/src/github.com/cockroachdb/cockroach/cockroach.linux-2.6.32-gnu-amd64 ./cockroach returned
		  | stderr:
		  |
		  | stdout:
		  | teamcity-2231078-1598711360-14-n4cpu4: putting (dist) /home/agent/work/.go/src/github.com/cockroachdb/cockroach/cockroach.linux-2.6.32-gnu-amd64 ./cockroach
		  | .............
		  |    1: done
		  |    2: ~ scp -r -C -o StrictHostKeyChecking=no -i /root/.ssh/id_rsa -i /root/.ssh/google_compute_engine /home/agent/work/.go/src/github.com/cockroachdb/cockroach/cockroach.linux-2.6.32-gnu-amd64 ubuntu@34.122.217.209:./cockroach
		  | scp: ./cockroach: Text file busy: exit status 1
		  |    3: ~ scp -r -C -o StrictHostKeyChecking=no -i /root/.ssh/id_rsa -i /root/.ssh/google_compute_engine /home/agent/work/.go/src/github.com/cockroachdb/cockroach/cockroach.linux-2.6.32-gnu-amd64 ubuntu@34.122.110.156:./cockroach
		  | scp: ./cockroach: Text file busy: exit status 1
		  | I200829 14:35:32.292834 1 cluster_synced.go:1169  put /home/agent/work/.go/src/github.com/cockroachdb/cockroach/cockroach.linux-2.6.32-gnu-amd64 failed
		Wraps: (4) exit status 1
		Error types: (1) *withstack.withStack (2) *errutil.withPrefix (3) *main.withCommandDetails (4) *exec.ExitError

```

<details><summary>More</summary><p>

Artifacts: [/join-init/mixed](https://teamcity.cockroachdb.com/viewLog.html?buildId=2231078&tab=artifacts#/join-init/mixed)

[See this test on roachdash](https://roachdash.crdb.dev/?filter=status%3Aopen+t%3A.%2Ajoin-init%2Fmixed.%2A&sort=title&restgroup=false&display=lastcommented+project)
<sub>powered by [pkg/cmd/internal/issues](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)</sub></p></details>

### PR DESCRIPTION
**Pull request by irfansharif**
Fixes #52760.
Fixes #53617.

We could technically stage the binary on all nodes before restarting
each one, but on Unix it's invalid to write to an executable file while
it is currently running. So we do the simple thing and upload it
serially instead, while the crdb server is stopped.

Previously we were careful to write tests such that they weren't simply
bouncing servers (using the same binary). With the introduction of more
randomized tests (such as join-init/mixed and
decommission/mixed-versions), this was no longer true, so we might as
well make this less of a footgun.

Release justification: non-production code changes
Release note: None

### CODE REVIEW

File: pkg/cmd/roachtest/versionupgrade.go [hunk 1]
```diff
@@ -321,7 +321,11 @@ func uploadAndStartFromCheckpointFixture(nodes nodeListOption, v string) version
 func binaryUpgradeStep(nodes nodeListOption, newVersion string) versionStep {
 	return func(ctx context.Context, t *test, u *versionUpgradeTest) {
 		c := u.c
-		args := u.uploadVersion(ctx, t, nodes, newVersion)
+
+		// NB: We could technically stage the binary on all nodes before
+		// restarting each one, but on Unix it's invalid to write to an
+		// executable file while it is currently running. So we do the
+		// simple thing and upload it serially instead.
```
Comment (knz) [inline pkg/cmd/roachtest/versionupgrade.go:328]: just FYI if you were to implement something like this in the future: upload the binary with a new name in parallel here, then rename it into place in the sequential step below. This parallelizes the time-consuming task and only keeps a short step for the critical path.

**Review by knz — APPROVED** [review]

**Comment by irfansharif** [comment]
Thanks for looking!

bors r+

File: pkg/cmd/roachtest/versionupgrade.go (hunk 1 above)
Comment (irfansharif) [reply pkg/cmd/roachtest/versionupgrade.go:328]: oo, good idea. I'm hoping to eventually pull together all these various version upgraded related tests into dedicated testing infrastructure for this sort of thing, can address it then.
