### PR TITLE
Fix the logic used to push timestamps forward based on the timestamp cache

### LINKED ISSUE #676: lowWater increase to cause repeat read get different value
Scenario A:

 txn | ts1 | (12s delay) | ts2 | ts3 | ts4 | ts5 
 --- | --- | ----------- | --- | --- | --- | ---
 txnA | put(a) |  |  | put(b) | commit |
 txnB |  |  | get(b)|  |  | get(b) 

txnB first get(b) will get null, but second get(b) will get a value by txnA's put(b). 
The reason for this is that at ts2, txnB's get(b) will trigger timestamp cache to increase lowWater to ts1, but txnA's put(b) in ts3 don't push the timestamp, so key 'b' still has timestamp ts1, so at ts5, txnB will get the value txnA put. 
Why txnA's put(b) don't push the timestamp is the statement in range.go line 536 (inside addReadWriteCmd method)
```go
                if !wTS.Less(header.Timestamp) && header.Txn != nil {
                        err := &proto.WriteTooOldError{Timestamp: header.Timestamp, ExistingTimestamp: wTS}
                        reply.Header().SetGoError(err)
                } else if !wTS.Less(header.Timestamp) || !rTS.Less(header.Timestamp) {
                        // Otherwise, make sure we advance the request's timestamp.
                        ...
                }
```
header.Timestamp in second put(b) is ts1, and wTS is also ts1 which is same as lowWater. so timestamp will not be pushed.

Scenario B:                                                                                                                               

 txn|ts1|ts2|ts3|ts4|ts5|ts6                                                 
 ---|---|---|---|---|---|---    
 txnA|put(a)| | | put(c)|commit|
 txnB| |get(c)| | | | get(c)
 txnC| | |splitRange(b)| 

txnB first get(c) will get null, but second get(c) will get a value by txnA's put(c).
The reason for this is that at ts3, txnC's splitRange by key b will cause the split the initial range to 2 ranges. This new range will have a new lowWater ts3, but txnA's put(c) in ts4 don't push the timestamp, so key 'c' still has timestamp ts1, so at ts6, txnB will get the value txnA put.
The reason for txnA's second put don't push the timestamp is the same statement as above:
so header.Timestamp in second put(c) is ts1, and wTS is also ts3 which is same as lowWater in the new range. so timestamp will not be pushed.

 One possible solution is we should always push the timestamp, so the change is:
```go
                if !wTS.Less(header.Timestamp) && header.Txn != nil {
                        err := &proto.WriteTooOldError{Timestamp: header.Timestamp, ExistingTimestamp: wTS}
                        reply.Header().SetGoError(err)
-               } else if !wTS.Less(header.Timestamp) || !rTS.Less(header.Timestamp) {
+               }
+               if !wTS.Less(header.Timestamp) || !rTS.Less(header.Timestamp) {
                        // Otherwise, make sure we advance the request's timestamp.
                }
```
But we found that the test case TestRangeSplitsWithConcurrentTxns in kv/split_test.go failed as it expect the txn will not retry even the range split. After the above change, concurrentTxn may retry because range split and the timestamp of put will be pushed, but the SSI txn expect timestamp in EndTransaction header is same as OrigTImestamp (statement in range.go EndTransaction method), but this may not be true because timestamp push, so the test case failed.
So we should try the above change and make changes to the failed test case, or any another way?
Please comments. 

Test case 
Scenario A:
```go
// When the gap between two writes in a txn is bigger than 10 seconds, lowWater
// in timestamp cache can increase to the timestamp of the first write as
// side effect of read in another txn, but when the txn committed, the write's
// timestamp is not increased. so another txn two reads before and after
// the second write will get different value.
func TestTxnRepeatGetDifferentValue(t *testing.T) {
        db, _, _, mClock, _, stopper, err := createTestDB()
        if err != nil {
                t.Fatal(err)
        } 
        defer stopper.Stop()

        keyA := proto.Key("a")
        keyB := proto.Key("b")
        ch := make(chan struct{})
        // Use snapshot isolation
        txnAOpts := &client.TransactionOptions{
                Name:      "txnA",
                Isolation: proto.SNAPSHOT,
        }
        txnBOpts := &client.TransactionOptions{
                Name:      "txnB",
                Isolation: proto.SNAPSHOT,
        }
        go func() {
                err = db.RunTransaction(txnAOpts, func(txn *client.KV) error {
                        // Put transactional value.
                        if err := txn.Call(proto.Put, proto.PutArgs(keyA, []byte("value1")), &proto.PutResponse{}); err != nil {
                                return err 
                        }
                        // Notify txnB do 1st get(b)
                        ch <- struct{}{}
                        // Wait for txnB notify us to put(b)
                        <-ch
                        // Write now to keyB
                        if err := txn.Call(proto.Put, proto.PutArgs(keyB, []byte("value2")), &proto.PutResponse{}); err != nil {
                                return err
                        }
                        return nil
                })
                // Notify txnB do 2nd get(b)
                ch <- struct{}{}
        }()
 
        // Wait till txnA finish put(a)
        <-ch
        // Delay 12 seconds
        mClock.Set(time.Duration(12 * time.Second).Nanoseconds())
        err = db.RunTransaction(txnBOpts, func(txn *client.KV) error {
                gr1 := &proto.GetResponse{}
                gr2 := &proto.GetResponse{}

                // Attempt to get first keyB
                if err := txn.Call(proto.Get, proto.GetArgs(keyB), gr1); err != nil {
                        return err
                }
                // Notify txnA put(b)
                ch <- struct{}{}
                // Wait for txnA finish commit
                <-ch
                // get(b) again
                if err := txn.Call(proto.Get, proto.GetArgs(keyB), gr2); err != nil {
                        return err
                }

                if gr1.Value == nil && gr2.Value != nil {
                        t.Fatalf("Repeat read same key in same txn but get different value gr1 nil gr2 %v", gr2.Value)
                }
                return nil
        })
        if err != nil {
                t.Fatal(err)
        }
}
```

Scenario B:
```go
// When two writes in a txn is interleaved by a range split, the second write
// may redirect to the new range, this new range will have a new lowWater
// in it's timestamp cache. But the second write don't push its timestamp.
// So another txn two reads before and after the range split will get different value.
func TestTxnRepeatGetWithRangeSplit(t *testing.T) {
        db, _, _, mClock, _, stopper, err := createTestDB()
        if err != nil { 
                t.Fatal(err)
        }
        defer stopper.Stop()
                                                                                                                                          
        keyA := proto.Key("a")
        keyC := proto.Key("c")
        splitKey := proto.Key("b")
        ch := make(chan struct{})
        // Use snapshot isolation
        txnAOpts := &client.TransactionOptions{
                Name:      "txnA", 
                Isolation: proto.SNAPSHOT, 
        }
        txnBOpts := &client.TransactionOptions{                                                                                           
                Name:      "txnB",                                                                                                        
                Isolation: proto.SNAPSHOT,                                                                                                
        }                                                                                                                                 
        go func() {                                                                                                                       
                err = db.RunTransaction(txnAOpts, func(txn *client.KV) error {                                                            
                        // Put transactional value.                                                                                       
                        if err := txn.Call(proto.Put, proto.PutArgs(keyA, []byte("value1")), &proto.PutResponse{}); err != nil {          
                                return err                                                                                                
                        }                                                                                                                 
                        // Notify txnB do 1st get(c)                                                                                      
                        ch <- struct{}{}                                                                                                  
                        // Wait for txnB notify us to put(c)                                                                              
                        <-ch                                                                                                              
                        // Write now to keyC, which will keep timestamp.                                                                   
                        if err := txn.Call(proto.Put, proto.PutArgs(keyC, []byte("value2")), &proto.PutResponse{}); err != nil {          
                                return err                                                                                                
                        }                                                                                                                 
                        return nil
                  })                                                                                                                        
                // Notify txnB do 2nd get(c)                                                                                              
                ch <- struct{}{}                                                                                                          
        }()                                                                                                                               
                                                                                                                                          
        // Wait till txnA finish put(a)                                                                                                   
        <-ch                                                                                                                              
                                                                                                                                          
        err = db.RunTransaction(txnBOpts, func(txn *client.KV) error {                                                                    
                gr1 := &proto.GetResponse{}                                                                                               
                gr2 := &proto.GetResponse{}                                                                                               
                                                                                                                                          
                // First get keyC, value will be nil                                                                                      
                if err := txn.Call(proto.Get, proto.GetArgs(keyC), gr1); err != nil {                                                     
                        return err                                                                                                        
                }                                                                                                                         
                mClock.Set(time.Duration(1 * time.Second).Nanoseconds())                                                                  
                // Split range by keyB                                                                                                    
                req := &proto.AdminSplitRequest{RequestHeader: proto.RequestHeader{Key: splitKey}, SplitKey: splitKey}                    
                resp := &proto.AdminSplitResponse{}                                                                                       
                if err := db.Call(proto.AdminSplit, req, resp); err != nil {                                                              
                        t.Fatal(err)                                                                                                      
                }                                                                                                                         
                // Wait till split complete                                                                                               
                // Check that we split 1 times in allotted time.                                                                          
                if err := util.IsTrueWithin(func() bool {                                                                                 
                        // Scan the txn records.                                                                                          
                        resp := &proto.ScanResponse{}                                                                                     
                        if err := db.Call(proto.Scan, proto.ScanArgs(engine.KeyMeta2Prefix, engine.KeyMetaMax, 0), resp); err != nil {    
                                t.Fatalf("failed to scan meta2 keys: %s", err)                                                            
                        }                                                                                                                 
                        return len(resp.Rows) >= 2                                                                                        
                }, 6*time.Second); err != nil {                                                                                           
                        t.Errorf("failed to split 1 times: %s", err)                                                                      
                }                                                                                                                                                
                // Notify txnA put(c)                                                                                                     
                ch <- struct{}{}                                                                                                          
                // Wait for txnA finish commit                                                                                            
                <-ch                                                                                                                      
                // Get(c) again                                                                                                           
                if err := txn.Call(proto.Get, proto.GetArgs(keyC), gr2); err != nil {                                                     
                        return err                                                                                                        
                }                                                                                                                         
                                                                                                                                          
                if gr1.Value == nil && gr2.Value != nil {                                                                                 
                        t.Fatalf("Repeat read same key in same txn but get different value gr1 nil gr2 %v", gr2.Value)                    
                }                                                                                                                         
                return nil                                                                                                                
        })                                                                                                                                
        if err != nil {                                                                                                                   
                t.Fatal(err)                                                                                                              
        }                                                                                                                                 
} 
```

### PR DESCRIPTION
**Pull request by spencerkimball**
In particular:
- Always push the timestamp forward if the timestamp cache indicates a
  read happened at same time or more recently.
- Next, if there's a write which happened at same time or more recently,
  and we're part of a txn, then set writeTooOldError, but instead of pushing
  the timestamp, we instead try to push the intent if possible.
  - Else, if we're not part of a txn, just set timestamp forward as there's
    no cost.

Also, on splits and merges, we now preserve the timestamp cache. For splits,
we simply copy the cache. For merges, we merge the caches. This preserves
the state of the original range(s) and prevents unnecessary txn restarts.

Added two test cases provided by @es-chow 
Fixes #676.

### CODE REVIEW

File: storage/timestamp_cache.go [hunk 1]
```diff
@@ -146,6 +146,27 @@ func (tc *TimestampCache) GetMax(start, end proto.Key, txnMD5 [md5.Size]byte) (p
 	return maxR, maxW
 }
 
+// MergeInto merges all entries from this timestamp cache into the
+// dest timestamp cache. The copy parameter, if true, copies the
+// values of lowWater and latest.
+func (tc *TimestampCache) MergeInto(dest *TimestampCache, copy bool) {
+	if copy {
+		dest.cache.Clear()
```
Comment (tschottdorf) [inline storage/timestamp_cache.go]: Doesn't this do more than advertised in the comment?

**Comment by tschottdorf** [comment]
LGTM mod perhaps the comment.

File: storage/timestamp_cache.go (hunk 1 above)
Comment (spencerkimball) [inline storage/timestamp_cache.go]: OK.

File: kv/txn_test.go [hunk 2]
```diff
@@ -478,3 +478,172 @@ func TestTxnTimestampRegression(t *testing.T) {
...
 	}
 }
+
+// When the gap between two writes in a txn is bigger than 10 seconds,
+// lowWater in timestamp cache can increase to the timestamp of the
+// first write as side effect of read in another txn, but when the txn
+// committed, the write's timestamp is not increased. so another txn
+// two reads before and after the second write will get different
+// value.
+func TestTxnRepeatGetDifferentValue(t *testing.T) {
```
Comment (bdarnell) [inline kv/txn_test.go]: Now that the bug has been fixed, this test should be renamed to TestTxnRepeatGetSameValue and the comment updated accordingly.

File: kv/txn_test.go [hunk 3]
```diff
@@ -478,3 +478,172 @@ func TestTxnTimestampRegression(t *testing.T) {
...
+			return nil
+		})
+		// Notify txnB do 2nd get(b)
+		ch <- struct{}{}
+	}()
+
+	// Wait till txnA finish put(a)
+	<-ch
+	// Delay 12 seconds
+	mClock.Set(time.Duration(12 * time.Second).Nanoseconds())
```
Comment (bdarnell) [inline kv/txn_test.go]: `time.Duration` is unnecessary here; `(12 * time.Second).Nanoseconds()` works. This should probably also be defined in terms of `minCacheWindow` instead of a separate hard-coded value.

File: kv/txn_test.go [hunk 4]
```diff
@@ -478,3 +478,172 @@ func TestTxnTimestampRegression(t *testing.T) {
...
+	})
+	if err != nil {
+		t.Fatal(err)
+	}
+}
+
+// When two writes in a txn is interleaved by a range split, the second write
+// may redirect to the new range, this new range will have a new lowWater
+// in it's timestamp cache. But the second write don't push its timestamp.
+// So another txn two reads before and after the range split will get different value.
```
Comment (bdarnell) [inline kv/txn_test.go]: This comment also needs to be updated.

File: kv/txn_test.go (hunk 2 above)
Comment (spencerkimball) [inline kv/txn_test.go]: Addressed all comments in a new changelist.
