### PR TITLE
Move Replica.Destroy from replicaGCQueue to store.removeReplicaImpl

### LINKED ISSUE #3447: TestRaftRemoveRace: range not found on store 2
The following test appears to have failed:

[#10183](https://circleci.com/gh/cockroachdb/cockroach/10183):

```
W1215 01:18:50.477119 959 multiraft/multiraft.go:1233  aborting configuration change: key range /Local/Range/RangeDescriptor/""-/Min outside of bounds of range /Min-/Min
W1215 01:18:50.478804 959 multiraft/multiraft.go:1139  failed to look up replica ID for range 1 (disabling replica ID check): storage/store.go:1695: store 3 not found as replica of range 1
I1215 01:18:53.557582 959 storage/engine/rocksdb.go:138  closing in-memory rocksdb instance
I1215 01:18:53.557889 959 storage/engine/rocksdb.go:138  closing in-memory rocksdb instance
I1215 01:18:53.558132 959 storage/engine/rocksdb.go:138  closing in-memory rocksdb instance
--- FAIL: TestRaftRemoveRace (3.53s)
	<autogenerated>:32: storage/client_test.go:521: condition failed to evaluate within 3s: storage/client_test.go:517: range not found on store 2
=== RUN   TestStoreRangeRemoveDead
E1215 01:18:53.562437 959 gossip/gossip.go:181  different node IDs were set for the same gossip instance (2147483647, 1)
I1215 01:18:53.563875 959 multiraft/multiraft.go:579  node 1 starting
I1215 01:18:53.564727 959 storage/replica.go:1308  gossiping cluster id  from store 1, range 1
I1215 01:18:53.565694 959 raft/raft.go:446  [group 1] 1 became follower at term 5
I1215 01:18:53.565898 959 raft/raft.go:234  [group 1] newRaft 1 [peers: [1], term: 5, commit: 10, applied: 10, lastindex: 10, lastterm: 5]
I1215 01:18:53.566074 959 multiraft/multiraft.go:999  node 1 campaigning because initial confstate is [1]
I1215 01:18:53.566196 959 raft/raft.go:526  [group 1] 1 is starting a new election at term 5
I1215 01:18:53.566292 959 raft/raft.go:459  [group 1] 1 became candidate at term 6
--
I1215 01:19:05.063638 959 storage/engine/rocksdb.go:138  closing in-memory rocksdb instance
I1215 01:19:05.063778 959 storage/engine/rocksdb.go:138  closing in-memory rocksdb instance
--- PASS: TestLeaderAfterSplit (0.44s)
=== RUN   Example_rebalancing
--- PASS: Example_rebalancing (0.62s)
FAIL
FAIL	github.com/cockroachdb/cockroach/storage	32.371s
=== RUN   TestBatchBasics
I1215 01:18:45.307778 1019 storage/engine/rocksdb.go:138  closing in-memory rocksdb instance
--- PASS: TestBatchBasics (0.01s)
=== RUN   TestBatchGet
I1215 01:18:45.312076 1019 storage/engine/rocksdb.go:138  closing in-memory rocksdb instance
--- PASS: TestBatchGet (0.01s)
=== RUN   TestBatchMerge
I1215 01:18:45.320845 1019 storage/engine/rocksdb.go:138  closing in-memory rocksdb instance
--- PASS: TestBatchMerge (0.01s)
=== RUN   TestBatchProto

```
Please assign, take a look and update the issue accordingly.

### PR DESCRIPTION
**Pull request by bdarnell**
This removes the possibility of the "replica recreated during deletion"
scenario, and the chance for Store.getOrCreateReplicaLocked to create
a replica for which data already exists on disk.

Fixes #3447.

[Review on Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/3709)

### CODE REVIEW

**Comment by bdarnell** [comment]
I have an alternate solution in https://github.com/cockroachdb/cockroach/compare/master...bdarnell:recreate-initialized-replica?expand=1 , which may perform a bit better but adds complexity to a rare and hard-to-test event, so for now I think this approach is better.

File: storage/store.go [hunk 1]
```diff
@@ -1137,22 +1137,25 @@ func (s *Store) addReplicaToRangeMap(rng *Replica) error {
...
-// RemoveReplica removes the replica from the store's replica map and from
-// the sorted replicasByKey btree. The version of the replica descriptor that
-// was used to make the removal decision is passed in, and the removal is
-// aborted if the replica ID has changed since then.
-func (s *Store) RemoveReplica(rep *Replica, origDesc roachpb.RangeDescriptor) error {
+// RemoveReplica removes the replica from the store's replica map and
+// from the sorted replicasByKey btree. The version of the replica
+// descriptor that was used to make the removal decision is passed in,
+// and the removal is aborted if the replica ID has changed since
+// then. If `destroy` is true, all data beloing to the replica will be
```
Comment (tamird) [inline storage/store.go]: s/beloing/belonging/

**Comment by tamird** [comment]
LGTM

**Comment by BramGruneir** [comment]
LGTM
I agree with this approach.  And the alternative adds a good amount of unneeded complexity.  
The event of deleting a replica is a rare one, so holding the lock for longer shouldn't be that big an issue.
