### PR TITLE
server/debug: don't panic on empty goroutine dumps

### LINKED ISSUE #139130: Sentry: panic.go:770: runtime error: invalid memory address or nil pointer dereference (1) attached stack trace   -- stack trace:   | runtime.gopanic   | 	GOROOT/src/runtime/panic.go:770   | runtime.p...
This issue was auto filed by Sentry. It represents a crash or reported error on a live cluster with telemetry enabled.

Sentry Link: [https://cockroach-labs.sentry.io/issues/6221074478/?referrer=webhooks_plugin](https://cockroach-labs.sentry.io/issues/6221074478/?referrer=webhooks_plugin)

Panic Message:

```
panic.go:770: runtime error: invalid memory address or nil pointer dereference
(1) attached stack trace
  -- stack trace:
  | runtime.gopanic
  | 	GOROOT/src/runtime/panic.go:770
  | runtime.panicmem
  | 	GOROOT/src/runtime/panic.go:261
  | runtime.sigpanic
  | 	GOROOT/src/runtime/signal_unix.go:881
  | github.com/cockroachdb/cockroach/pkg/server/debug/goroutineui.Dump.SortWaitDesc
  | 	pkg/server/debug/goroutineui/dump.go:57
  | github.com/cockroachdb/cockroach/pkg/server/debug.setupProcessWideRoutes.func5
  | 	pkg/server/debug/server.go:130
  | github.com/cockroachdb/cockroach/pkg/server/debug.setupProcessWideRoutes.setupProcessWideRoutes.func2.func17
  | 	pkg/server/debug/server.go:84
  | net/http.HandlerFunc.ServeHTTP
  | 	GOROOT/src/net/http/server.go:2171
  | github.com/cockroachdb/cockroach/pkg/server/debug.(*Server).ServeHTTP
  | 	pkg/server/debug/server.go:308
  | github.com/cockroachdb/cockroach/pkg/server.(*httpServer).setupRoutes.makeAdminAuthzCheckHandler.func2
  | 	pkg/server/server_http.go:264
  | net/http.HandlerFunc.ServeHTTP
  | 	GOROOT/src/net/http/server.go:2171
  | github.com/cockroachdb/cockroach/pkg/server/authserver.(*authenticationMux).ServeHTTP
  | 	pkg/server/authserver/authentication.go:773
  | net/http.(*ServeMux).ServeHTTP
  | 	GOROOT/src/net/http/server.go:2688
  | net/http.HandlerFunc.ServeHTTP
  | 	GOROOT/src/net/http/server.go:2171
  | github.com/NYTimes/gziphandler.NewGzipLevelAndMinSize.func1.1
  | 	external/com_github_nytimes_gziphandler/gzip.go:253
  | net/http.HandlerFunc.ServeHTTP
  | 	GOROOT/src/net/http/server.go:2171
  | github.com/cockroachdb/cockroach/pkg/server.(*nodeProxy).nodeProxyHandler
  | 	pkg/server/node_http_router.go:58
  | github.com/cockroachdb/cockroach/pkg/server.(*httpServer).baseHandler
  | 	pkg/server/server_http.go:377
  | github.com/cockroachdb/cockroach/pkg/server.(*serverController).httpMux
  | 	pkg/server/server_controller_http.go:125
  | net/http.HandlerFunc.ServeHTTP
  | 	GOROOT/src/net/http/server.go:2171
  | net/http.serverHandler.ServeHTTP
  | 	GOROOT/src/net/http/server.go:3142
  | net/http.(*conn).serve
  | 	GOROOT/src/net/http/server.go:2044
  | runtime.goexit
  | 	src/runtime/asm_amd64.s:1695
Wraps: (2) runtime error: invalid memory address or nil pointer dereference
Error types: (1) *withstack.withStack (2) runtime.errorString
-- report composition:
runtime.errorString
panic.go:770: *withstack.withStack (top exception)
```

<details>
<summary>Stacktrace (expand for inline code snippets):</summary>

[src/runtime/asm_amd64.s#L1694-L1696](src/runtime/asm_amd64.s#L1694-L1696)
[GOROOT/src/net/http/server.go#L2043-L2045](GOROOT/src/net/http/server.go#L2043-L2045)
[GOROOT/src/net/http/server.go#L3141-L3143](GOROOT/src/net/http/server.go#L3141-L3143)
[GOROOT/src/net/http/server.go#L2170-L2172](GOROOT/src/net/http/server.go#L2170-L2172)
[pkg/server/server_controller_http.go#L124-L126](pkg/server/server_controller_http.go#L124-L126)
[pkg/server/server_http.go#L376-L378](pkg/server/server_http.go#L376-L378)
[pkg/server/node_http_router.go#L57-L59](pkg/server/node_http_router.go#L57-L59)
[GOROOT/src/net/http/server.go#L2170-L2172](GOROOT/src/net/http/server.go#L2170-L2172)
[external/com_github_nytimes_gziphandler/gzip.go#L252-L254](external/com_github_nytimes_gziphandler/gzip.go#L252-L254)
[GOROOT/src/net/http/server.go#L2170-L2172](GOROOT/src/net/http/server.go#L2170-L2172)
[GOROOT/src/net/http/server.go#L2687-L2689](GOROOT/src/net/http/server.go#L2687-L2689)
[pkg/server/authserver/authentication.go#L772-L774](pkg/server/authserver/authentication.go#L772-L774)
[GOROOT/src/net/http/server.go#L2170-L2172](GOROOT/src/net/http/server.go#L2170-L2172)
[pkg/server/server_http.go#L263-L265](pkg/server/server_http.go#L263-L265)
[pkg/server/debug/server.go#L307-L309](pkg/server/debug/server.go#L307-L309)
[GOROOT/src/net/http/server.go#L2170-L2172](GOROOT/src/net/http/server.go#L2170-L2172)
[pkg/server/debug/server.go#L83-L85](pkg/server/debug/server.go#L83-L85)
[pkg/server/debug/server.go#L129-L131](pkg/server/debug/server.go#L129-L131)
[pkg/server/debug/goroutineui/dump.go#L56-L58](pkg/server/debug/goroutineui/dump.go#L56-L58)
[GOROOT/src/runtime/signal_unix.go#L880-L882](GOROOT/src/runtime/signal_unix.go#L880-L882)
[GOROOT/src/runtime/panic.go#L260-L262](GOROOT/src/runtime/panic.go#L260-L262)
[GOROOT/src/runtime/panic.go#L769-L771](GOROOT/src/runtime/panic.go#L769-L771)
</details>

```
src/runtime/asm_amd64.s in runtime.goexit at line 1695
GOROOT/src/net/http/server.go in net/http.(*conn).serve at line 2044
GOROOT/src/net/http/server.go in net/http.serverHandler.ServeHTTP at line 3142
GOROOT/src/net/http/server.go in net/http.HandlerFunc.ServeHTTP at line 2171
pkg/server/server_controller_http.go in pkg/server.(*serverController).httpMux at line 125
pkg/server/server_http.go in pkg/server.(*httpServer).baseHandler at line 377
pkg/server/node_http_router.go in pkg/server.(*nodeProxy).nodeProxyHandler at line 58
GOROOT/src/net/http/server.go in net/http.HandlerFunc.ServeHTTP at line 2171
external/com_github_nytimes_gziphandler/gzip.go in github.com/NYTimes/gziphandler.NewGzipLevelAndMinSize.func1.1 at line 253
GOROOT/src/net/http/server.go in net/http.HandlerFunc.ServeHTTP at line 2171
GOROOT/src/net/http/server.go in net/http.(*ServeMux).ServeHTTP at line 2688
pkg/server/authserver/authentication.go in pkg/server/authserver.(*authenticationMux).ServeHTTP at line 773
GOROOT/src/net/http/server.go in net/http.HandlerFunc.ServeHTTP at line 2171
pkg/server/server_http.go in pkg/server.(*httpServer).setupRoutes.makeAdminAuthzCheckHandler.func2 at line 264
pkg/server/debug/server.go in pkg/server/debug.(*Server).ServeHTTP at line 308
GOROOT/src/net/http/server.go in net/http.HandlerFunc.ServeHTTP at line 2171
pkg/server/debug/server.go in pkg/server/debug.setupProcessWideRoutes.setupProcessWideRoutes.func2.func17 at line 84
pkg/server/debug/server.go in pkg/server/debug.setupProcessWideRoutes.func5 at line 130
pkg/server/debug/goroutineui/dump.go in pkg/server/debug/goroutineui.Dump.SortWaitDesc at line 57
GOROOT/src/runtime/signal_unix.go in runtime.sigpanic at line 881
GOROOT/src/runtime/panic.go in runtime.panicmem at line 261
GOROOT/src/runtime/panic.go in runtime.gopanic at line 770
```

### Tags

| Tag | Value |
| --- | --- |
| Command | server |
| Environment | development |
| Go Version | go1.22.8 X:nocoverageredesign |
| Platform | linux amd64 |
| Distribution | CCL |
| Cockroach Release | v25.1.0-alpha.2-dev-0a82539a44f38b6cb94c4d15d791537d3afbd200 |
| Cockroach SHA | 0a82539a44f38b6cb94c4d15d791537d3afbd200 |
| # of CPUs | 16 |
| # of Goroutines | 2846 |

Jira issue: CRDB-46514

### PR DESCRIPTION
**Pull request by dhartunian**
Previously, we observed a panic in a running cluster when the goroutine dumper produced a nil result.

We should not panic in this case, but fail gracefully with an error message, even though this situation was not possible to reproduce in a test environment.

Resolves: #139130

Release note: None

### CODE REVIEW

File: pkg/server/debug/goroutineui/dump.go [hunk 1]
```diff
@@ -42,6 +43,9 @@ func (d Dump) SortCountDesc() {
 	if d.err != nil {
 		return
 	}
+	if d.agg == nil {
```
Comment (xinhaoz) [inline pkg/server/debug/goroutineui/dump.go:46]: Is it possible that in `newDumpFromBytes` above, the err being returned could be nil? It wouldn't be EOF then and we'd never write the `agg` field. Unsure if that's even possible though.

Comment (dhartunian) [reply pkg/server/debug/goroutineui/dump.go:46]: Tough to tell from the library code, but it's good to guard against. It seems like that's what probably happened to cause the panic. `err` was `nil` so we leave `agg` set to `nil` which leads to panic when trying to read `d.agg.Buckets`.

Are you implying that I should modify `newDumpFromBytes`?

**Comment by dhartunian** [comment]
@xinhaoz friendly ping

**Review by xinhaoz — APPROVED** [review]

File: pkg/server/debug/goroutineui/dump.go (hunk 1 above)
Comment (xinhaoz) [reply pkg/server/debug/goroutineui/dump.go:46]: I'm not sure what state the returned snapshot would be if err was nil so I think keeping the nil agg checks makes the most sense. Was just trying to throw out an explanation for how we got to this state :)

**Comment by dhartunian** [comment]
TFTR!

bors r=xinhaoz

**Comment by dhartunian** [comment]
bors r=xinhaoz
