### PR TITLE
streamingccl: use correct bounds for range key SSTs

### LINKED ISSUE #112846: streamingccl: range key splitting can produce incorrect SST
When streaming receives a range key from the rangefeed-driven event stream, it adds them to an SST so they can be written at a specific timestamp. When calling AddSSTable for the built SST, the stream ingestion processor may need to split that SST into multiple SSTs if it is found to be at a range boundary.

There is a bug in the current splitting routine:

1) The streaming code inaccurately reports the end key of the SST by calling Next() on the actual end key.  This Next() is unnecessary because the EndKey of range keys are already exclusive.

2) When splitting an SST, the streaming code splits it at the split point returned by KV. We assume that the SST actually does contain values on the left- and right-hand side of the SST.

Given that behaviour, 

1) If we receive a range key for `[a, c)`, we will attempt to AddSSTable with bounds of `[a, c.Next())`.
2) If the destination side has a range split exactly at `c`, it will return a split point of c.
3) We will try to split the `[a, c)` range key at `c`, which will result in an empty right hand side.
4) Since our code assumes the rhs will be non-empty, we attempt to apply a bad SSTable and receive an error.

The stream can only advance past the error if the range boundaries happen to change at some point in the future.

Jira issue: CRDB-32637

### PR DESCRIPTION
**Pull request by stevendanna**
Previously, we were erroneously calling Next() on the end key of our SST even though the end key already represented an exclusive bounds.

This Next() meant that the bounds of our SSTs were slightly incorrect. In most cases, this was harmless, but in the case of a range boundary that aligned directly with the _actual_ bounds of the SST, it could result in us attempting to split an SST into 2 with the RHS ending up empty.

Here, we fix that and also make our SST splitting a bit more robust to bad input. It now errors if the LHS or RHS ends up empty despite a split key inside the given bounds. It also handles split keys outside of the bounds. Neither of these things should happen unless our contract with other parts of the system changes.

Fixes #112846

Release note (bug fix): Fix a bug that could prevent phyiscal replication from advancing in the face of some range deletion operations.

### CODE REVIEW

File: pkg/ccl/streamingccl/streamingest/stream_ingestion_processor.go [hunk 1]
```diff
@@ -985,6 +998,17 @@ func (r *rangeKeyBatcher) flush(ctx context.Context, toFlush mvccRangeKeyValues)
...
+	// Special case: The split key less than the start key.
+	if splitKey.Compare(start) < 0 {
+		return nil, &rangeKeySST{start: start, end: end, data: data}, nil
+	}
+
+	// Special case: The split key is greater or equal to the
+	// exclusive end key.
+	if end.Compare(splitKey) <= 0 {
+		return &rangeKeySST{start: start, end: end, data: data}, nil, nil
+	}
```
Comment (stevendanna) [inline pkg/ccl/streamingccl/streamingest/stream_ingestion_processor.go:1010]: I could be convinced that these should just also return errors since they really should not happen.

File: pkg/ccl/streamingccl/streamingest/stream_ingestion_processor.go [hunk 2]
```diff
@@ -956,7 +958,18 @@ func (r *rangeKeyBatcher) flush(ctx context.Context, toFlush mvccRangeKeyValues)
 				if err != nil {
 					return err
 				}
-				work = append([]*rangeKeySST{left, right}, work...)
+
+				// The second two cases really should not be possible unless we've
```
Comment (msbutler) [inline pkg/ccl/streamingccl/streamingest/stream_ingestion_processor.go:962]: again, curious why you think the second and third cases aren't really possible.

**Review by msbutler — APPROVED** [review]
LGTM and nice tests! Just had one clarifying question.

File: pkg/ccl/streamingccl/streamingest/stream_ingestion_processor.go (hunk 1 above)
Comment (stevendanna) [reply pkg/ccl/streamingccl/streamingest/stream_ingestion_processor.go:1010]: I think I was just not thinking this through when I wrote this.  I think what I had in my mind is that if the whole SST was in a different range, then why did we ever send it to the wrong range.  But, perhaps our entire SST is on one side of a split we don't know about yet.  So, I'll leave these cases and remove the errant comment.

Thanks!

**Comment by stevendanna** [comment]
bors r=msbutler
