### PR TITLE
schemachanger: fix skip_unique_checks not cleared on PK for RBR→GLOBAL

### LINKED ISSUE #167123: sql: RBR -> GLOBAL table doesn't clear skip_unique_checks on the primary key
After `ALTER TABLE SET LOCALITY GLOBAL`, the PK still shows `skip_unique_checks=true` even though implicit partitioning   
was removed. Secondary indexes were correctly cleared. The PK was not.

```sql
CREATE DATABASE db PRIMARY REGION "us-east1" REGIONS "us-west1", "europe-west1";
USE db;

CREATE TABLE t (a INT PRIMARY KEY, b INT, UNIQUE INDEX idx_b (b))
    LOCALITY REGIONAL BY ROW;                                                                                           
  ALTER INDEX t@t_pkey SET (skip_unique_checks = true);                                                                 
  ALTER INDEX t@idx_b SET (skip_unique_checks = true);                                                                  
  ALTER TABLE t SET LOCALITY GLOBAL;                                                                                    
  SHOW CREATE TABLE t;
```

It shows:

```sql
  CREATE TABLE public.t (
      a INT8 NOT NULL,
      b INT8 NULL,
      crdb_region public.crdb_internal_region NOT VISIBLE NOT NULL DEFAULT default_to_database_primary_region(gateway_region())::public.crdb_internal_region,
      CONSTRAINT t_pkey PRIMARY KEY (a ASC) WITH (skip_unique_checks=true),
      UNIQUE INDEX idx_b (b ASC)
  ) WITH (schema_locked = true) LOCALITY GLOBAL;
```

Confirmed that this `PRIMARY KEY (a ASC) WITH (skip_unique_checks=true)` still exists after the schema change job finishes.

Jira issue: CRDB-62258
Epic: [CRDB-39721](https://cockroachlabs.atlassian.net/browse/CRDB-39721)

### PR DESCRIPTION
**Pull request by DrewKimball**
When converting a table from REGIONAL BY ROW to GLOBAL, the declarative schema changer preserved `skip_unique_checks` on the primary key because `setupStorageParams` checked a stale `IndexPartitioning` element (already dropped from builder state) rather than the target partitioning spec.

Fix by checking `t.Partitioning.NewImplicitColumns` instead, matching the pattern already used in `maybeAddUniqueIndexForOldPrimaryKey`.

Fixes: #167123

Release note (bug fix): Fixed a bug where converting a table from REGIONAL BY ROW to GLOBAL would not clear the `skip_unique_checks` storage parameter on the primary key, even though implicit partitioning was removed.

### CODE REVIEW

**Review by yuzefovich — APPROVED** [review]
:lgtm:

> @yuzefovich reviewed 2 files and all commit messages, and made 2 comments.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/167359#-:-OpAQ4lMANG-ae_c4xm7:bnfp4nl)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on DrewKimball and mw5h).

___
*[`-- commits` line 10 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/167359#-OpAPt1ZATOFv9fp5vlJ:-OpAPt1_8wWIwB6Hf_GJ:b-k3zcfe):*
Side question: should we apply the following patch in that method
```
--- a/pkg/sql/schemachanger/scbuild/internal/scbuildstmt/alter_table_alter_primary_key.go
+++ b/pkg/sql/schemachanger/scbuild/internal/scbuildstmt/alter_table_alter_primary_key.go
@@ -942,7 +942,7 @@ func maybeAddUniqueIndexForOldPrimaryKey(
        sec, temp := addNewUniqueSecondaryIndexAndTempIndex(b, tbl, oldPrimaryIndex, newPrimaryIndex)
        // Clear skip_unique_checks if partitioning is being overridden and the new
        // index will not have implicit partitioning (e.g. REGIONAL BY ROW to GLOBAL).
-       if t.Partitioning != nil && len(t.Partitioning.NewImplicitColumns) == 0 {
+       if t.Partitioning == nil || len(t.Partitioning.NewImplicitColumns) == 0 {
                sec.SkipUniqueChecks = false
                temp.SkipUniqueChecks = false
        }
```

**Review by DrewKimball — COMMENTED** [review]
TFTR!

> @DrewKimball made 2 comments.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/167359#-:-OpE3pRy3ce5Fyf9Jk5m:b-814g8k)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on mw5h and yuzefovich).

___
*[`-- commits` line 10 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/167359#-OpAPt1ZATOFv9fp5vlJ:-OpDtSIHEjIZxKLX0QFK:b-i9joir):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

Side question: should we apply the following patch in that method
```
--- a/pkg/sql/schemachanger/scbuild/internal/scbuildstmt/alter_table_alter_primary_key.go
+++ b/pkg/sql/schemachanger/scbuild/internal/scbuildstmt/alter_table_alter_primary_key.go
@@ -942,7 +942,7 @@ func maybeAddUniqueIndexForOldPrimaryKey(
        sec, temp := addNewUniqueSecondaryIndexAndTempIndex(b, tbl, oldPrimaryIndex, newPrimaryIndex)
        // Clear skip_unique_checks if partitioning is being overridden and the new
        // index will not have implicit partitioning (e.g. REGIONAL BY ROW to GLOBAL).
-       if t.Partitioning != nil && len(t.Partitioning.NewImplicitColumns) == 0 {
+       if t.Partitioning == nil || len(t.Partitioning.NewImplicitColumns) == 0 {
                sec.SkipUniqueChecks = false
                temp.SkipUniqueChecks = false
        }
```
</blockquote></details>

When this isn't a locality swap, we want to preserve `SkipUniqueChecks`, so we shouldn't do it when `t.Partitioning` is nil. This did make me realize we can remove the `IsLocalitySwap` field, since it's equivalent to checking `t.Partitioning != nil`.

File: pkg/sql/schemachanger/scbuild/internal/scbuildstmt/alter_table_alter_primary_key.go [hunk 1]
```diff
@@ -248,9 +243,11 @@ func setupStorageParams(
 ) {
 	// Reset to defaults first, since the new PK should not inherit storage
 	// params from the old PK unless explicitly specified in the WITH clause.
-	// For RBR-to-RBR locality swaps, preserve skip_unique_checks from the old
-	// PK since the index remains implicitly partitioned.
-	if t.IsLocalitySwap && partitioning != nil && partitioning.NumImplicitColumns > 0 {
+	// For locality swaps where the new index retains implicit partitioning
```
Comment (shghasemi) [inline pkg/sql/schemachanger/scbuild/internal/scbuildstmt/alter_table_alter_primary_key.go:246]: What about transitions like global --> RBR that add a partitioning? Do we want to preserve SkipUniqueChecks there?

Comment (DrewKimball) [reply pkg/sql/schemachanger/scbuild/internal/scbuildstmt/alter_table_alter_primary_key.go:246]: In that case, there wouldn't have been implicit columns when the table was global, so I don't think `SkipUniqueChecks` could/should have been set originally. Does that answer your question?

Comment (shghasemi) [reply pkg/sql/schemachanger/scbuild/internal/scbuildstmt/alter_table_alter_primary_key.go:246]: Yes, LGTM

**Review by shghasemi — APPROVED** [review]

**Comment by DrewKimball** [comment]
TFTRs!

/trunk merge
