### PR TITLE
sql/schemachanger: alter pk would temporarily disable secondary indexes

### LINKED ISSUE #111076: sql/schemachanger: ALTER PRIMARY KEY on declarative schema changer can disables secondary indexes early
As a part of changing primary keys, we will need to recreate all secondary indexes for a given table, which will replace any existing secondary indexes. Unfortunately, due to a bug in our declarative schema changer implementation, we can disable the old secondary indexes before the new ones are ready, leading to severe performance implications in some cases. A simple scenario to reproduce this is:

```
CREATE TABLE public.t1 (
      n INT8 NOT NULL,
      j INT8 NOT NULL,
      CONSTRAINT t1_pkey PRIMARY KEY (n ASC),
      INDEX a (j ASC)
  );
  CREATE TABLE public.t2 (
      n INT8 NOT NULL,
      c INT8 NULL,
      CONSTRAINT t2_pkey PRIMARY KEY (n ASC)
  );
```

Executing a simple swap:
```
explain (DDL) alter table t1 alter primary key using columns (j);
```

We get the following in the plan:
```
  Schema change plan for ALTER TABLE ‹defaultdb›.public.‹t1› ALTER PRIMARY KEY USING COLUMNS (‹j›);
   ├── StatementPhase
   │    └── Stage 1 of 1 in StatementPhase
   │         ├── 8 elements transitioning toward PUBLIC
   │         │    ├── ABSENT → BACKFILL_ONLY PrimaryIndex:{DescID: 104 (t1), IndexID: 7 (t1_pkey+), ConstraintID: 6, TemporaryIndexID: 8, SourceIndexID: 1 (t1_pkey-)}
   │         │    ├── ABSENT → PUBLIC        IndexColumn:{DescID: 104 (t1), ColumnID: 1 (n), IndexID: 7 (t1_pkey+)}
   │         │    ├── ABSENT → PUBLIC        IndexColumn:{DescID: 104 (t1), ColumnID: 2 (j), IndexID: 7 (t1_pkey+)}
   │         │    ├── ABSENT → PUBLIC        IndexData:{DescID: 104 (t1), IndexID: 7 (t1_pkey+)}
   │         │    ├── ABSENT → BACKFILL_ONLY SecondaryIndex:{DescID: 104 (t1), IndexID: 3 (a+), ConstraintID: 2, TemporaryIndexID: 4, SourceIndexID: 1 (t1_pkey-)}
   │         │    ├── ABSENT → PUBLIC        IndexName:{DescID: 104 (t1), Name: "a", IndexID: 3 (a+)}
   │         │    ├── ABSENT → PUBLIC        IndexColumn:{DescID: 104 (t1), ColumnID: 2 (j), IndexID: 3 (a+)}
   │         │    └── ABSENT → PUBLIC        IndexData:{DescID: 104 (t1), IndexID: 3 (a+)}
   │         ├── 5 elements transitioning toward TRANSIENT_ABSENT
   │         │    ├── ABSENT → DELETE_ONLY   TemporaryIndex:{DescID: 104 (t1), IndexID: 8, ConstraintID: 7, SourceIndexID: 1 (t1_pkey-)}
   │         │    ├── ABSENT → PUBLIC        IndexColumn:{DescID: 104 (t1), ColumnID: 1 (n), IndexID: 8}
   │         │    ├── ABSENT → PUBLIC        IndexColumn:{DescID: 104 (t1), ColumnID: 2 (j), IndexID: 8}
   │         │    ├── ABSENT → DELETE_ONLY   TemporaryIndex:{DescID: 104 (t1), IndexID: 4, ConstraintID: 3, SourceIndexID: 1 (t1_pkey-)}
   │         │    └── ABSENT → PUBLIC        IndexColumn:{DescID: 104 (t1), ColumnID: 2 (j), IndexID: 4}
   │         ├── 1 element transitioning toward ABSENT
   **│         │    └── PUBLIC → VALIDATED     SecondaryIndex:{DescID: 104 (t1), IndexID: 2 (a-)}**
```

Which will end up disabling the secondary index during the pre-commit phase

### PR DESCRIPTION
**Pull request by fqazi**
Previously, when ALTER PRIMARY KEY was issued, the declarative schema changer would instantly move all existing indexes to VALIDATED. Meaning they would no longer be accessible for any read operations. This was problematic because query performance could degrade since the secondary indexes backing a table would be missing until a new secondary index was prepared. To address this, this patch adds a new rule inside the declarative schema changer that says for secondary index re-creates, we need to ensure that the new index is ready to take over before the old one is disabled.

Fixes: #111076

Release note (bug fix): ALTER PRIMARY KEY would incorrectly disable secondary indexes while new secondary indexes were being backfilled when using the declarative schema changer.

The second commit is focused on mixed version compatibility since we need this change to be backportable. It adds a flag into the state to prevent us from using this on states generated on older versions (i.e., they could have the secondary index disabled earlier).

### CODE REVIEW

**Comment by cucaroach** [comment]
Sounds good but I think you want someone more familiar with the schema changer code to review this.

File: pkg/sql/schemachanger/scbuild/internal/scbuildstmt/alter_table_alter_primary_key.go [hunk 1]
```diff
@@ -738,6 +738,9 @@ func recreateAllSecondaryIndexes(
 			}
 		}
 		in, temp := makeSwapIndexSpec(b, out, sourcePrimaryIndex.IndexID, inColumns, false /* inUseTempIDs */)
+		if b.ClusterSettings().Version.IsActive(b, clusterversion.V23_1) {
```
Comment (Xiang-Gu) [inline pkg/sql/schemachanger/scbuild/internal/scbuildstmt/alter_table_alter_primary_key.go:741]: should the gate be V23_2?

File: pkg/sql/schemachanger/scplan/internal/rules/current/dep_swap_index.go [hunk 2]
```diff
@@ -125,3 +124,60 @@ func init() {
...
+// index key is changed, that the secondary indexes are swapped in an atomic
+// manner, so that queries are not impacted by missing indexes.
+func init() {
+	// This ia strict version of the rule that will only work, when a node
+	// is generating a plan on the latest master / 23.1. The StrictRecreate flag
+	// will be used to tag if the existing secondary index was created on a
+	// new enough version.
+	registerDepRule(
+		"secondary index being recreated after a primary key swap",
+		scgraph.SameStagePrecedence,
```
Comment (Xiang-Gu) [inline pkg/sql/schemachanger/scplan/internal/rules/current/dep_swap_index.go:138]: I see why you use SameStagePrecedence here but do we need to? I just have some invalidated fear from past experience so that I try to avoid SameStagePrecedence if possible.

What about a Precedence from (new_index, public) to (old_index, validated)? This is saying to the old index "hey, sorry, you cannot transition to VALIDATED, until your new index is PUBLIC". The planner, being a greedy one, should naturally schedule both transitions to the same stage when new_index transitions to PUBLIC.

**Review by Xiang-Gu — CHANGES_REQUESTED** [review]
I left two questions in the comments. One other question is did you also add some test for the case? Maybe add a test case in `scplan/testdata` and verify that any secondary indexes, during a PK change, indeed move to VALIDATED in the same stage as the new ones move to PUBLIC.

**Review by fqazi — COMMENTED** [review]
@Xiang-Gu The Downside of modifying the protobuf is that many tests got updated. But there is a new test that uses DML injection to validate this called alter_table_add_primary_key_drop_rowid_with_secondary_idx

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/111313#-:-Ng5CU8w0dG80ngDJ8Rm:box3mn1)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @Xiang-Gu)

**Review by fqazi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/111313)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @Xiang-Gu)

___
*[`pkg/sql/schemachanger/scbuild/internal/scbuildstmt/alter_table_alter_primary_key.go` line 741 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/111313#gh-1349154474:-Ng5DAo33ce_5yTRkGrE:b-s2bo4c) ([raw file](https://github.com/cockroachdb/cockroach/blob/52cdf7d7cfd481468266722f7ac6156016371699/pkg/sql/schemachanger/scbuild/internal/scbuildstmt/alter_table_alter_primary_key.go#L741)):*
<details><summary><i>Previously, Xiang-Gu (Xiang Gu) wrote…</i></summary><blockquote>

should the gate be V23_2?
</blockquote></details>

This was intentional since we would backport this into 23.1, too. Since this could be a big issue for customers

**Comment by Xiang-Gu** [comment]
Thanks for the answer. My only question/concern is then the comment I left about the rule.

**Review by fqazi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/111313)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @Xiang-Gu)

___
*[`pkg/sql/schemachanger/scplan/internal/rules/current/dep_swap_index.go` line 138 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/111313#gh-1349163889:-Ng5NbzF2gSYnUNUDaZT:bjss69h) ([raw file](https://github.com/cockroachdb/cockroach/blob/52cdf7d7cfd481468266722f7ac6156016371699/pkg/sql/schemachanger/scplan/internal/rules/current/dep_swap_index.go#L138)):*
<details><summary><i>Previously, Xiang-Gu (Xiang Gu) wrote…</i></summary><blockquote>

I see why you use SameStagePrecedence here but do we need to? I just have some invalidated fear from past experience so that I try to avoid SameStagePrecedence if possible.

What about a Precedence from (new_index, public) to (old_index, validated)? This is saying to the old index "hey, sorry, you cannot transition to VALIDATED, until your new index is PUBLIC". The planner, being a greedy one, should naturally schedule both transitions to the same stage when new_index transitions to PUBLIC.
</blockquote></details>

Good point, this needs two rules to get that behaviour with precedence. Otherwise, the greedy behaviour will schedule things earlier.

**Review by fqazi — COMMENTED** [review]
Good point, done.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/111313#-:-NgxjK5N-7dNlPXBGOku:bfbq99i)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @Xiang-Gu)

**Review by Xiang-Gu — APPROVED** [review]
nice work!

**Comment by fqazi** [comment]
@Xiang-Gu TFTR!

bors r+
