### PR TITLE
kvserver: amortize limiter.WaitN in range scan

### LINKED ISSUE #89695: kvserver: make more coarse, or remove consistency checking rate limit
**Describe the problem**
In a profile, I see us spending as long waiting for quota as we do hashing data. That's wrong. The problem, as far as I can tell, is that we're synchronizing on every single row. That's silly. We should allocate batches of capacity, perhaps a few hundred kilobytes at a time, and wait for that. 
Screen Shot 2022-10-10 at 4 52 55 PM

Jira issue: CRDB-20380

### PR DESCRIPTION
**Pull request by pav-kv**
This commit reduces the relative cost of quota acquisitions in consistency checker's range scan, by requesting it in chunks of at least 256 KiB at a time.

Fixes #89695

Release note: None

### CODE REVIEW

File: pkg/kv/kvserver/replica_consistency.go [hunk 1]
```diff
@@ -500,9 +500,27 @@ func CalcReplicaDigest(
 	var timestampBuf []byte
 	hasher := sha512.New()
 
+	// Request quota from the limiter in chunks of quotaBatchSize, to amortize the
+	// overhead of the limiter when reading many small KVs.
+	var budget int64
+	const quotaBatchSize = int64(4 << 10) // 4 KiB
```
Comment (pavelkalinnikov) [inline pkg/kv/kvserver/replica_consistency.go:506]: Maybe something like 64 KiB would be better, still less than 1% of the total limit. Given that there are only a few parallel tasks, it's ok to overshoot by 1%.

File: pkg/kv/kvserver/replica_consistency.go [hunk 2]
```diff
@@ -500,9 +500,27 @@ func CalcReplicaDigest(
...
+		if size <= budget {
+			budget -= size
+			return nil
+		}
+		batches := (size - budget + quotaBatchSize - 1) / quotaBatchSize
+		tokens := batches * quotaBatchSize
+		if err := limiter.WaitN(ctx, tokens); err != nil {
+			return err
+		}
+		budget += tokens - size
```
Comment (erikgrinaker) [inline pkg/kv/kvserver/replica_consistency.go:517]: I'm not sure I completely understand these calculations. Can't we just allow bursts and do something straightforward like:

```go
var batchSize int64
const targetBatchSize = int64(4 << 10) // 4 KiB
wait := func(size int64) error {
  if batchSize += size; batchSize >= targetBatchSize {
    if err := limiter.WaitN(ctx, batchSize); err != nil {
      return err
    }
    batchSize = 0
  }
  return nil
}
```

**Review by erikgrinaker — COMMENTED** [review]
Did you run a CPU profile to verify that the overhead ~disappears?

File: pkg/kv/kvserver/replica_consistency.go (hunk 2 above)
Comment (pavelkalinnikov) [reply pkg/kv/kvserver/replica_consistency.go:517]: The calculation rounds up to multiples of `quotaBatchSize`. So, after the first row (if it's small) we will have acquired more than its size, and the next few entries will be free. This way the quota acquisition is almost always ahead of reading from the iterator.

You proposal is cleaner, but acquires quota post-factum, so in between acquisitions there is a bigger chance of a thundering herd between tasks.

Both solutions are "leaky" in some sense though, but the one in this PR is not leakier than the status quo: right now we acquire quota post-factum, but on every row; after the change we acquire it post-factum for a single row, and there is a chance that a few next rows are free.

I can mix the 2 ideas though. I think we don't need to always request a multiple of the batch size, so the maths can be simpler. But I think we should try to acquire upfront still.

Comment (erikgrinaker) [reply pkg/kv/kvserver/replica_consistency.go]: I don't think we need to overengineer this. The default setting here is 8 MB/s, which means that we're pausing about 30 ms for each batch (assuming only one check). I don't think reading 256 KB is expensive enough to matter. It's more about making sure it doesn't go full throttle.

Comment (pavelkalinnikov) [reply pkg/kv/kvserver/replica_consistency.go]: Done. Also, added a `WaitN` in the end, for any "uncommitted" quota.

**Review by erikgrinaker — APPROVED** [review]
Thanks!

I don't have a good sense of how long it takes to process one batch, but I'm guessing it's a few milliseconds. Do you mind running a quick timer test to see how long one batch takes (with reasonably sized rows), and how long each wait is? Just to have some basic data to back up the choice of `targetBatchSize`.

**Comment by pavelkalinnikov** [comment]
@erikgrinaker Some stats:
```
histogram ‹waits› (step = 10μs): [1154 10 0 0 1 0 0 0 0 0 0 0 0 1 0 0 0 0 0 371]
histogram ‹reads› (step = 500μs): [3 3 159 355 90 121 159 186 118 100 37 22 24 12 11 7 7 11 5 27]

```
I.e. waits are quick (< 10 microseconds), except when they are slow. I suspect that the slow ones are the legitimate blocking waits.
Batch reads (intervals between `WaitN` calls) are a couple of orders of magnitude slower - a few milliseconds.

**Comment by pavelkalinnikov** [comment]
bors r=erikgrinaker

**Comment by erikgrinaker** [comment]
Thanks! I guess this also confirms that the bursty calculation doesn't matter, because the limiter allows much larger bursts anyway (as evidenced by the 10μs bucket dominating).

File: pkg/kv/kvserver/replica_consistency.go [hunk 3]
```diff
@@ -581,6 +594,11 @@ func CalcReplicaDigest(
 	if !statsOnly {
 		ms, err := rditer.ComputeStatsForRangeWithVisitors(&desc, snap, 0, /* nowNanos */
 			pointKeyVisitor, rangeKeyVisitor)
+		// Consume the remaining quota borrowed in the visitors. Do it even on
+		// iteration error, but prioritize returning the latter if it occurs.
+		if wErr := limiter.WaitN(ctx, batchSize); wErr != nil && err == nil {
```
Comment (erikgrinaker) [inline pkg/kv/kvserver/replica_consistency.go:599]: Can you verify that WaitN(ctx, 0) is valid? I'd expect it to, but worth confirming.

Comment (pavelkalinnikov) [reply pkg/kv/kvserver/replica_consistency.go:599]: I checked it yesterday, it returns immediately, which is what we need.
