### PR TITLE
storage: deflake TestStoreRangeSystemSplits

### LINKED ISSUE #12218: github.com/cockroachdb/cockroach/pkg/storage: TestStoreRangeSystemSplits failed under stress
SHA: https://github.com/cockroachdb/cockroach/commits/d879e9a153024cd4c4d6082a9aa78cc90994d276

Parameters:
```
COCKROACH_PROPOSER_EVALUATED_KV=false
TAGS=
GOFLAGS=-race
```

Stress build found a failed test: https://teamcity.cockroachdb.com/viewLog.html?buildId=85618&tab=buildLog

```
E161209 09:27:22.701747 40201 storage/queue.go:613  [replicate,s1,r3/1:/Table/1{2-3},@c4201a4a00] purgatory: 0 of 0 stores with an attribute matching []; likely not enough nodes in cluster
E161209 09:27:22.703453 40200 storage/queue.go:602  [split,s1,r3/1:/Table/1{2-3},@c4201a4a00] unable to split [n1,s1,r3/1:/Table/1{2-3}] at key "/Table/14/0": key range /Table/14/0-/Table/14/0 outside of bounds of range /Table/12-/Max
I161209 09:27:22.705329 40200 storage/split_queue.go:103  [split,s1,r4/1:/{Table/13-Max},@c420338f00] splitting at keys [/Table/14/0]
I161209 09:27:22.705492 40200 storage/replica_command.go:2379  [split,s1,r4/1:/{Table/13-Max},@c420338f00] initiating a split of this range at key /Table/14 [r5]
E161209 09:27:22.782615 40201 storage/queue.go:613  [replicate,s1,r4/1:/Table/1{3-4},@c420338f00] purgatory: 0 of 0 stores with an attribute matching []; likely not enough nodes in cluster
E161209 09:27:22.783956 40201 storage/queue.go:613  [replicate,s1,r5/1:/{Table/14-Max},@c4201a5900] purgatory: 0 of 0 stores with an attribute matching []; likely not enough nodes in cluster
I161209 09:27:22.800110 40200 storage/split_queue.go:103  [split,s1,r5/1:/{Table/14-Max},@c4201a5900] splitting at keys [/Table/50/0 /Table/51/0 /Table/52/0 /Table/53/0 /Table/54/0 /Table/55/0 /Table/56/0 /Table/57/0 /Table/58/0 /Table/59/0 /Table/60/0 /Table/61/0 /Table/62/0 /Table/63/0 /Table/64/0 /Table/65/0 /Table/66/0 /Table/67/0 /Table/68/0]
I161209 09:27:22.800570 40200 storage/replica_command.go:2379  [split,s1,r5/1:/{Table/14-Max},@c4201a5900] initiating a split of this range at key /Table/50 [r6]
E161209 09:27:22.870161 40200 storage/queue.go:602  [split,s1,r5/1:/Table/{14-50},@c4201a5900] unable to split [n1,s1,r5/1:/Table/{14-50}] at key "/Table/51/0": key range /Table/51/0-/Table/51/0 outside of bounds of range /Table/14-/Max
I161209 09:27:22.871324 40200 storage/split_queue.go:103  [split,s1,r6/1:/{Table/50-Max},@c42022a500] splitting at keys [/Table/51/0 /Table/52/0 /Table/53/0 /Table/54/0 /Table/55/0 /Table/56/0 /Table/57/0 /Table/58/0 /Table/59/0 /Table/60/0 /Table/61/0 /Table/62/0 /Table/63/0 /Table/64/0 /Table/65/0 /Table/66/0 /Table/67/0 /Table/68/0]
I161209 09:27:22.871512 40200 storage/replica_command.go:2379  [split,s1,r6/1:/{Table/50-Max},@c42022a500] initiating a split of this range at key /Table/51 [r7]
E161209 09:27:22.884894 40201 storage/queue.go:613  [replicate,s1,r6/1:/Table/5{0-1},@c42022a500] purgatory: 0 of 0 stores with an attribute matching []; likely not enough nodes in cluster
E161209 09:27:22.885924 40200 storage/queue.go:602  [split,s1,r6/1:/Table/5{0-1},@c42022a500] unable to split [n1,s1,r6/1:/Table/5{0-1}] at key "/Table/52/0": key range /Table/52/0-/Table/52/0 outside of bounds of range /Table/50-/Max
I161209 09:27:22.886892 40200 storage/split_queue.go:103  [split,s1,r7/1:/{Table/51-Max},@c42022af00] splitting at keys [/Table/52/0 /Table/53/0 /Table/54/0 /Table/55/0 /Table/56/0 /Table/57/0 /Table/58/0 /Table/59/0 /Table/60/0 /Table/61/0 /Table/62/0 /Table/63/0 /Table/64/0 /Table/65/0 /Table/66/0 /Table/67/0 /Table/68/0]
I161209 09:27:22.887122 40200 storage/replica_command.go:2379  [split,s1,r7/1:/{Table/51-Max},@c42022af00] initiating a split of this range at key /Table/52 [r8]
E161209 09:27:22.911529 40200 storage/queue.go:602  [split,s1,r7/1:/Table/5{1-2},@c42022af00] unable to split [n1,s1,r7/1:/Table/5{1-2}] at key "/Table/53/0": key range /Table/53/0-/Table/53/0 outside of bounds of range /Table/51-/Max
I161209 09:27:22.921772 40200 storage/split_queue.go:103  [split,s1,r8/1:/{Table/52-Max},@c421542000] splitting at keys [/Table/53/0 /Table/54/0 /Table/55/0 /Table/56/0 /Table/57/0 /Table/58/0 /Table/59/0 /Table/60/0 /Table/61/0 /Table/62/0 /Table/63/0 /Table/64/0 /Table/65/0 /Table/66/0 /Table/67/0 /Table/68/0]
I161209 09:27:22.922000 40200 storage/replica_command.go:2379  [split,s1,r8/1:/{Table/52-Max},@c421542000] initiating a split of this range at key /Table/53 [r9]
E161209 09:27:22.922478 40201 storage/queue.go:613  [replicate,s1,r7/1:/Table/5{1-2},@c42022af00] purgatory: 0 of 0 stores with an attribute matching []; likely not enough nodes in cluster
E161209 09:27:22.980527 40201 storage/queue.go:613  [replicate,s1,r8/1:/Table/5{2-3},@c421542000] purgatory: 0 of 0 stores with an attribute matching []; likely not enough nodes in cluster
E161209 09:27:22.982934 40200 storage/queue.go:602  [split,s1,r8/1:/Table/5{2-3},@c421542000] unable to split [n1,s1,r8/1:/Table/5{2-3}] at key "/Table/54/0": key range /Table/54/0-/Table/54/0 outside of bounds of range /Table/52-/Max
I161209 09:27:22.987248 40200 storage/split_queue.go:103  [split,s1,r9/1:/{Table/53-Max},@c420339400] splitting at keys [/Table/54/0 /Table/55/0 /Table/56/0 /Table/57/0 /Table/58/0 /Table/59/0 /Table/60/0 /Table/61/0 /Table/62/0 /Table/63/0 /Table/64/0 /Table/65/0 /Table/66/0 /Table/67/0 /Table/68/0]
I161209 09:27:22.988271 40200 storage/replica_command.go:2379  [split,s1,r9/1:/{Table/53-Max},@c420339400] initiating a split of this range at key /Table/54 [r10]
E161209 09:27:23.011357 40201 storage/queue.go:613  [replicate,s1,r9/1:/Table/5{3-4},@c420339400] purgatory: 0 of 0 stores with an attribute matching []; likely not enough nodes in cluster
E161209 09:27:23.015728 40200 storage/queue.go:602  [split,s1,r9/1:/Table/5{3-4},@c420339400] unable to split [n1,s1,r9/1:/Table/5{3-4}] at key "/Table/55/0": key range /Table/55/0-/Table/55/0 outside of bounds of range /Table/53-/Max
I161209 09:27:23.016503 40200 storage/split_queue.go:103  [split,s1,r10/1:/{Table/54-Max},@c42023b400] splitting at keys [/Table/55/0 /Table/56/0 /Table/57/0 /Table/58/0 /Table/59/0 /Table/60/0 /Table/61/0 /Table/62/0 /Table/63/0 /Table/64/0 /Table/65/0 /Table/66/0 /Table/67/0 /Table/68/0]
I161209 09:27:23.016677 40200 storage/replica_command.go:2379  [split,s1,r10/1:/{Table/54-Max},@c42023b400] initiating a split of this range at key /Table/55 [r11]
E161209 09:27:23.057044 40201 storage/queue.go:613  [replicate,s1,r10/1:/Table/5{4-5},@c42023b400] purgatory: 0 of 0 stores with an attribute matching []; likely not enough nodes in cluster
E161209 09:27:23.058714 40200 storage/queue.go:602  [split,s1,r10/1:/Table/5{4-5},@c42023b400] unable to split [n1,s1,r10/1:/Table/5{4-5}] at key "/Table/56/0": key range /Table/56/0-/Table/56/0 outside of bounds of range /Table/54-/Max
I161209 09:27:23.064105 40200 storage/split_queue.go:103  [split,s1,r11/1:/{Table/55-Max},@c4201a4500] splitting at keys [/Table/56/0 /Table/57/0 /Table/58/0 /Table/59/0 /Table/60/0 /Table/61/0 /Table/62/0 /Table/63/0 /Table/64/0 /Table/65/0 /Table/66/0 /Table/67/0 /Table/68/0]
I161209 09:27:23.064314 40200 storage/replica_command.go:2379  [split,s1,r11/1:/{Table/55-Max},@c4201a4500] initiating a split of this range at key /Table/56 [r12]
E161209 09:27:23.077907 40201 storage/queue.go:613  [replicate,s1,r11/1:/Table/5{5-6},@c4201a4500] purgatory: 0 of 0 stores with an attribute matching []; likely not enough nodes in cluster
E161209 09:27:23.081898 40200 storage/queue.go:602  [split,s1,r11/1:/Table/5{5-6},@c4201a4500] unable to split [n1,s1,r11/1:/Table/5{5-6}] at key "/Table/57/0": key range /Table/57/0-/Table/57/0 outside of bounds of range /Table/55-/Max
I161209 09:27:23.082581 40200 storage/split_queue.go:103  [split,s1,r12/1:/{Table/56-Max},@c421542500] splitting at keys [/Table/57/0 /Table/58/0 /Table/59/0 /Table/60/0 /Table/61/0 /Table/62/0 /Table/63/0 /Table/64/0 /Table/65/0 /Table/66/0 /Table/67/0 /Table/68/0]
I161209 09:27:23.082770 40200 storage/replica_command.go:2379  [split,s1,r12/1:/{Table/56-Max},@c421542500] initiating a split of this range at key /Table/57 [r13]
E161209 09:27:23.112807 40201 storage/queue.go:613  [replicate,s1,r12/1:/Table/5{6-7},@c421542500] purgatory: 0 of 0 stores with an attribute matching []; likely not enough nodes in cluster
E161209 09:27:23.113064 40200 storage/queue.go:602  [split,s1,r12/1:/Table/5{6-7},@c421542500] unable to split [n1,s1,r12/1:/Table/5{6-7}] at key "/Table/58/0": key range /Table/58/0-/Table/58/0 outside of bounds of range /Table/56-/Max
I161209 09:27:23.114266 40200 storage/split_queue.go:103  [split,s1,r13/1:/{Table/57-Max},@c420338500] splitting at keys [/Table/58/0 /Table/59/0 /Table/60/0 /Table/61/0 /Table/62/0 /Table/63/0 /Table/64/0 /Table/65/0 /Table/66/0 /Table/67/0 /Table/68/0]
I161209 09:27:23.114446 40200 storage/replica_command.go:2379  [split,s1,r13/1:/{Table/57-Max},@c420338500] initiating a split of this range at key /Table/58 [r14]
E161209 09:27:23.159496 40201 storage/queue.go:613  [replicate,s1,r13/1:/Table/5{7-8},@c420338500] purgatory: 0 of 0 stores with an attribute matching []; likely not enough nodes in cluster
E161209 09:27:23.164443 40200 storage/queue.go:602  [split,s1,r13/1:/Table/5{7-8},@c420338500] unable to split [n1,s1,r13/1:/Table/5{7-8}] at key "/Table/59/0": key range /Table/59/0-/Table/59/0 outside of bounds of range /Table/57-/Max
I161209 09:27:23.173553 40200 storage/split_queue.go:103  [split,s1,r14/1:/{Table/58-Max},@c42022a000] splitting at keys [/Table/59/0 /Table/60/0 /Table/61/0 /Table/62/0 /Table/63/0 /Table/64/0 /Table/65/0 /Table/66/0 /Table/67/0 /Table/68/0]
I161209 09:27:23.173855 40200 storage/replica_command.go:2379  [split,s1,r14/1:/{Table/58-Max},@c42022a000] initiating a split of this range at key /Table/59 [r15]
E161209 09:27:23.203060 40200 storage/queue.go:602  [split,s1,r14/1:/Table/5{8-9},@c42022a000] unable to split [n1,s1,r14/1:/Table/5{8-9}] at key "/Table/60/0": key range /Table/60/0-/Table/60/0 outside of bounds of range /Table/58-/Max
E161209 09:27:23.204616 40201 storage/queue.go:613  [replicate,s1,r14/1:/Table/5{8-9},@c42022a000] purgatory: 0 of 0 stores with an attribute matching []; likely not enough nodes in cluster
I161209 09:27:23.208504 40200 storage/split_queue.go:103  [split,s1,r15/1:/{Table/59-Max},@c420338a00] splitting at keys [/Table/60/0 /Table/61/0 /Table/62/0 /Table/63/0 /Table/64/0 /Table/65/0 /Table/66/0 /Table/67/0 /Table/68/0]
I161209 09:27:23.211092 40200 storage/replica_command.go:2379  [split,s1,r15/1:/{Table/59-Max},@c420338a00] initiating a split of this range at key /Table/60 [r16]
E161209 09:27:23.244693 40201 storage/queue.go:613  [replicate,s1,r15/1:/Table/{59-60},@c420338a00] purgatory: 0 of 0 stores with an attribute matching []; likely not enough nodes in cluster
E161209 09:27:23.245963 40200 storage/queue.go:602  [split,s1,r15/1:/Table/{59-60},@c420338a00] unable to split [n1,s1,r15/1:/Table/{59-60}] at key "/Table/61/0": key range /Table/61/0-/Table/61/0 outside of bounds of range /Table/59-/Max
I161209 09:27:23.246705 40200 storage/split_queue.go:103  [split,s1,r16/1:/{Table/60-Max},@c4223f4000] splitting at keys [/Table/61/0 /Table/62/0 /Table/63/0 /Table/64/0 /Table/65/0 /Table/66/0 /Table/67/0 /Table/68/0]
I161209 09:27:23.246902 40200 storage/replica_command.go:2379  [split,s1,r16/1:/{Table/60-Max},@c4223f4000] initiating a split of this range at key /Table/61 [r17]
E161209 09:27:23.284596 40201 storage/queue.go:613  [replicate,s1,r16/1:/Table/6{0-1},@c4223f4000] purgatory: 0 of 0 stores with an attribute matching []; likely not enough nodes in cluster
E161209 09:27:23.285574 40200 storage/queue.go:602  [split,s1,r16/1:/Table/6{0-1},@c4223f4000] unable to split [n1,s1,r16/1:/Table/6{0-1}] at key "/Table/62/0": key range /Table/62/0-/Table/62/0 outside of bounds of range /Table/60-/Max
I161209 09:27:23.291355 40200 storage/split_queue.go:103  [split,s1,r17/1:/{Table/61-Max},@c4223f4500] splitting at keys [/Table/62/0 /Table/63/0 /Table/64/0 /Table/65/0 /Table/66/0 /Table/67/0 /Table/68/0]
I161209 09:27:23.291575 40200 storage/replica_command.go:2379  [split,s1,r17/1:/{Table/61-Max},@c4223f4500] initiating a split of this range at key /Table/62 [r18]
E161209 09:27:23.413118 40201 storage/queue.go:613  [replicate,s1,r17/1:/Table/6{1-2},@c4223f4500] purgatory: 0 of 0 stores with an attribute matching []; likely not enough nodes in cluster
E161209 09:27:23.416791 40200 storage/queue.go:602  [split,s1,r17/1:/Table/6{1-2},@c4223f4500] unable to split [n1,s1,r17/1:/Table/6{1-2}] at key "/Table/63/0": key range /Table/63/0-/Table/63/0 outside of bounds of range /Table/61-/Max
I161209 09:27:23.417708 40200 storage/split_queue.go:103  [split,s1,r18/1:/{Table/62-Max},@c420339900] splitting at keys [/Table/63/0 /Table/64/0 /Table/65/0 /Table/66/0 /Table/67/0 /Table/68/0]
I161209 09:27:23.417878 40200 storage/replica_command.go:2379  [split,s1,r18/1:/{Table/62-Max},@c420339900] initiating a split of this range at key /Table/63 [r19]
E161209 09:27:23.438076 40200 storage/queue.go:602  [split,s1,r18/1:/Table/6{2-3},@c420339900] unable to split [n1,s1,r18/1:/Table/6{2-3}] at key "/Table/64/0": key range /Table/64/0-/Table/64/0 outside of bounds of range /Table/62-/Max
E161209 09:27:23.438180 40201 storage/queue.go:613  [replicate,s1,r18/1:/Table/6{2-3},@c420339900] purgatory: 0 of 0 stores with an attribute matching []; likely not enough nodes in cluster
I161209 09:27:23.439118 40200 storage/split_queue.go:103  [split,s1,r19/1:/{Table/63-Max},@c4223f4f00] splitting at keys [/Table/64/0 /Table/65/0 /Table/66/0 /Table/67/0 /Table/68/0]
I161209 09:27:23.439330 40200 storage/replica_command.go:2379  [split,s1,r19/1:/{Table/63-Max},@c4223f4f00] initiating a split of this range at key /Table/64 [r20]
E161209 09:27:23.463822 40201 storage/queue.go:613  [replicate,s1,r19/1:/Table/6{3-4},@c4223f4f00] purgatory: 0 of 0 stores with an attribute matching []; likely not enough nodes in cluster
E161209 09:27:23.464795 40200 storage/queue.go:602  [split,s1,r19/1:/Table/6{3-4},@c4223f4f00] unable to split [n1,s1,r19/1:/Table/6{3-4}] at key "/Table/65/0": key range /Table/65/0-/Table/65/0 outside of bounds of range /Table/63-/Max
I161209 09:27:23.465424 40200 storage/split_queue.go:103  [split,s1,r20/1:/{Table/64-Max},@c42022b400] splitting at keys [/Table/65/0 /Table/66/0 /Table/67/0 /Table/68/0]
I161209 09:27:23.465620 40200 storage/replica_command.go:2379  [split,s1,r20/1:/{Table/64-Max},@c42022b400] initiating a split of this range at key /Table/65 [r21]
E161209 09:27:23.500843 40201 storage/queue.go:613  [replicate,s1,r20/1:/Table/6{4-5},@c42022b400] purgatory: 0 of 0 stores with an attribute matching []; likely not enough nodes in cluster
E161209 09:27:23.508454 40200 storage/queue.go:602  [split,s1,r20/1:/Table/6{4-5},@c42022b400] unable to split [n1,s1,r20/1:/Table/6{4-5}] at key "/Table/66/0": key range /Table/66/0-/Table/66/0 outside of bounds of range /Table/64-/Max
I161209 09:27:23.511105 40200 storage/split_queue.go:103  [split,s1,r21/1:/{Table/65-Max},@c420232f00] splitting at keys [/Table/66/0 /Table/67/0 /Table/68/0]
I161209 09:27:23.511284 40200 storage/replica_command.go:2379  [split,s1,r21/1:/{Table/65-Max},@c420232f00] initiating a split of this range at key /Table/66 [r22]
E161209 09:27:23.552894 40201 storage/queue.go:613  [replicate,s1,r21/1:/Table/6{5-6},@c420232f00] purgatory: 0 of 0 stores with an attribute matching []; likely not enough nodes in cluster
E161209 09:27:23.556639 40200 storage/queue.go:602  [split,s1,r21/1:/Table/6{5-6},@c420232f00] unable to split [n1,s1,r21/1:/Table/6{5-6}] at key "/Table/67/0": key range /Table/67/0-/Table/67/0 outside of bounds of range /Table/65-/Max
I161209 09:27:23.558676 40200 storage/split_queue.go:103  [split,s1,r22/1:/{Table/66-Max},@c4223f5400] splitting at keys [/Table/67/0 /Table/68/0]
I161209 09:27:23.562197 40200 storage/replica_command.go:2379  [split,s1,r22/1:/{Table/66-Max},@c4223f5400] initiating a split of this range at key /Table/67 [r23]
E161209 09:27:23.618053 40201 storage/queue.go:613  [replicate,s1,r22/1:/Table/6{6-7},@c4223f5400] purgatory: 0 of 0 stores with an attribute matching []; likely not enough nodes in cluster
E161209 09:27:23.626675 40200 storage/queue.go:602  [split,s1,r22/1:/Table/6{6-7},@c4223f5400] unable to split [n1,s1,r22/1:/Table/6{6-7}] at key "/Table/68/0": key range /Table/68/0-/Table/68/0 outside of bounds of range /Table/66-/Max
I161209 09:27:23.628470 40200 storage/split_queue.go:103  [split,s1,r23/1:/{Table/67-Max},@c4223f5900] splitting at keys [/Table/68/0]
I161209 09:27:23.628648 40200 storage/replica_command.go:2379  [split,s1,r23/1:/{Table/67-Max},@c4223f5900] initiating a split of this range at key /Table/68 [r24]
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x6ab425]

goroutine 40205 [running]:
panic(0x1f69f80, 0xc420014120)
	/usr/local/go/src/runtime/panic.go:500 +0x1ae
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).Recover(0xc421080000)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:185 +0xd8
panic(0x1f69f80, 0xc420014120)
	/usr/local/go/src/runtime/panic.go:458 +0x271
github.com/cockroachdb/cockroach/pkg/storage.(*NodeLiveness).GetLiveness(0x0, 0xc400000001, 0x0, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/node_liveness.go:261 +0x55
github.com/cockroachdb/cockroach/pkg/storage.(*NodeLiveness).IsLive(0x0, 0x1, 0x0, 0x0, 0x8bb2c97000)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/node_liveness.go:134 +0x48
github.com/cockroachdb/cockroach/pkg/storage.(*consistencyQueue).shouldQueue(0xc4224cee60, 0x2b7d7ef74078, 0xc421c82f90, 0x7b, 0xc400000615, 0xc420232a00, 0xc422397000, 0x1c, 0x20, 0x61b573, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/consistency_queue.go:77 +0x17a
github.com/cockroachdb/cockroach/pkg/storage.(*baseQueue).MaybeAdd(0xc420016b40, 0xc420232a00, 0x7b, 0xc400000615)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/queue.go:359 +0x368
github.com/cockroachdb/cockroach/pkg/storage.(*consistencyQueue).MaybeAdd(0xc4224cee60, 0xc420232a00, 0x7b, 0x615)
	<autogenerated>:469 +0x7c
github.com/cockroachdb/cockroach/pkg/storage.(*replicaScanner).waitAndProcess(0xc421040be0, 0x2b7d7d3b6000, 0xc420096428, 0xecfdc6ffa, 0xc425486fe9, 0x348f880, 0xc42095a300, 0xc421080000, 0xc420232a00, 0x1068)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scanner.go:221 +0x3b8
github.com/cockroachdb/cockroach/pkg/storage.(*replicaScanner).scanLoop.func1.1(0xc420232a00, 0x58)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scanner.go:269 +0x162
github.com/cockroachdb/cockroach/pkg/storage.(*storeReplicaVisitor).Visit(0xc422399590, 0xc421fa4000)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/store.go:325 +0x5b0
github.com/cockroachdb/cockroach/pkg/storage.(*replicaScanner).scanLoop.func1()
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scanner.go:271 +0x45a
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc421080000, 0xc421f78dc0)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:196 +0x8b
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:197 +0x74

goroutine 1 [chan receive]:
testing.(*T).Run(0xc42032afc0, 0x2116a0a, 0x1a, 0x24d8ec0, 0xa61101)
	/usr/local/go/src/testing/testing.go:647 +0x56e
testing.RunTests.func1(0xc42032afc0)
	/usr/local/go/src/testing/testing.go:793 +0xba
testing.tRunner(0xc42032afc0, 0xc420325b38)
	/usr/local/go/src/testing/testing.go:610 +0xca
testing.RunTests(0x24da998, 0x2faeb40, 0x169, 0x169, 0xc42032cf18)
	/usr/local/go/src/testing/testing.go:799 +0x4bb
testing.(*M).Run(0xc420325ef0, 0xc4202bbcf0)
	/usr/local/go/src/testing/testing.go:743 +0x130
github.com/cockroachdb/cockroach/pkg/storage_test.TestMain(0xc420325ef0)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/main_test.go:57 +0x287
main.main()
	github.com/cockroachdb/cockroach/pkg/storage/_test/_testmain.go:786 +0x1b6

goroutine 17 [syscall, 1 minutes, locked to thread]:
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:2086 +0x1

goroutine 40178 [semacquire]:
sync.runtime_notifyListWait(0xc421c739d0, 0xc40000015b)
	/usr/local/go/src/runtime/sema.go:267 +0x12f
sync.(*Cond).Wait(0xc421c739c0)
	/usr/local/go/src/sync/cond.go:57 +0x8e
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).worker(0xc420ef4790, 0xc421080000)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:212 +0xfd
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).Start.func2()
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:181 +0x4b
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc421080000, 0xc421f783e0)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:196 +0x8b
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:197 +0x74

goroutine 3 [chan receive]:
github.com/cockroachdb/cockroach/pkg/util/log.(*loggingT).flushDaemon(0x3490de0)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/log/clog.go:1016 +0x85
created by github.com/cockroachdb/cockroach/pkg/util/log.init.1
	/go/src/github.com/cockroachdb/cockroach/pkg/util/log/clog.go:581 +0xc3

goroutine 40203 [select]:
github.com/cockroachdb/cockroach/pkg/storage.(*baseQueue).processLoop.func1()
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/queue.go:475 +0x495
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc421080000, 0xc421f78cc0)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:196 +0x8b
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:197 +0x74

goroutine 40200 [select]:
github.com/cockroachdb/cockroach/pkg/storage.(*Replica).tryAddWriteCmd(0xc4223f5900, 0x2b7d7ef74078, 0xc4218956e0, 0x7b, 0x60b, 0x100000001, 0x1, 0x17, 0x0, 0xc421781e00, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/replica.go:2021 +0xdeb
github.com/cockroachdb/cockroach/pkg/storage.(*Replica).addWriteCmd(0xc4223f5900, 0x2b7d7ef74078, 0xc4218956e0, 0x7b, 0x60b, 0x100000001, 0x1, 0x17, 0x0, 0xc421781e00, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/replica.go:1847 +0xa1
github.com/cockroachdb/cockroach/pkg/storage.(*Replica).Send(0xc4223f5900, 0x2b7d7ef74078, 0xc4218956e0, 0x7b, 0x60b, 0x100000001, 0x1, 0x17, 0x0, 0xc421781e00, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/replica.go:1299 +0x26f
github.com/cockroachdb/cockroach/pkg/storage.(*Store).Send(0xc42027ea80, 0x2b7d7ef74078, 0xc4218955f0, 0x7b, 0x60b, 0x100000001, 0x1, 0x17, 0x0, 0xc421781e00, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/store.go:2471 +0x86a
github.com/cockroachdb/cockroach/pkg/storage.(*Stores).Send(0xc4211410e0, 0x2b7d7ef74078, 0xc4218953b0, 0x0, 0x0, 0x100000001, 0x1, 0x17, 0x0, 0xc421781e00, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/stores.go:187 +0x24b
github.com/cockroachdb/cockroach/pkg/kv.(*senderTransport).SendNext(0xc421041680, 0xc4203eaf60)
	/go/src/github.com/cockroachdb/cockroach/pkg/kv/transport.go:309 +0x2c3
github.com/cockroachdb/cockroach/pkg/kv.(*DistSender).sendToReplicas(0xc4200162d0, 0x2b7d7ef74000, 0xc4204b3a40, 0x1dcd6500, 0xc422398a20, 0xc420016308, 0x3, 0xc4214e3820, 0x1, 0x1, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/kv/dist_sender.go:1142 +0x376
github.com/cockroachdb/cockroach/pkg/kv.(*DistSender).sendRPC(0xc4200162d0, 0x2b7d7ef74000, 0xc4204b3a40, 0x3, 0xc4214e3820, 0x1, 0x1, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/kv/dist_sender.go:410 +0x418
github.com/cockroachdb/cockroach/pkg/kv.(*DistSender).sendSingleRange(0xc4200162d0, 0x2b7d7ef7ad98, 0xc4203eaae0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0xc421781080, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/kv/dist_sender.go:479 +0x1ab
github.com/cockroachdb/cockroach/pkg/kv.(*DistSender).sendPartialBatch(0xc4200162d0, 0x2b7d7ef7ad98, 0xc4203eaae0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0xc421781080, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/kv/dist_sender.go:931 +0x3b4
github.com/cockroachdb/cockroach/pkg/kv.(*DistSender).divideAndSendBatchToRanges(0xc4200162d0, 0x2b7d7ef7ad98, 0xc4203eaae0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0xc421781080, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/kv/dist_sender.go:810 +0x568
github.com/cockroachdb/cockroach/pkg/kv.(*DistSender).Send(0xc4200162d0, 0x2b7d7ef7ad98, 0xc4203eaae0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0xc421780d80, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/kv/dist_sender.go:625 +0x382
github.com/cockroachdb/cockroach/pkg/kv.(*TxnCoordSender).Send(0xc4210406e0, 0x2b7d7ef7ad98, 0xc4203eaae0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0xc421780cc0, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/kv/txn_coord_sender.go:418 +0x7f2
github.com/cockroachdb/cockroach/pkg/internal/client.(*Txn).sendInternal(0xc421338420, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0xc421338468, 0x0, 0x0, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/internal/client/txn.go:587 +0x16f
github.com/cockroachdb/cockroach/pkg/internal/client.(*Txn).send(0xc421338420, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/internal/client/txn.go:711 +0x63d
github.com/cockroachdb/cockroach/pkg/internal/client.(*Txn).(github.com/cockroachdb/cockroach/pkg/internal/client.send)-fm(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/internal/client/txn.go:313 +0x7d
github.com/cockroachdb/cockroach/pkg/internal/client.sendAndFill(0xc420772f30, 0xc4207cd800, 0x0, 0xc421154a10)
	/go/src/github.com/cockroachdb/cockroach/pkg/internal/client/db.go:418 +0x1ac
github.com/cockroachdb/cockroach/pkg/internal/client.(*Txn).Run(0xc421338420, 0xc4207cd800, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/pkg/internal/client/txn.go:313 +0xfe
github.com/cockroachdb/cockroach/pkg/storage.(*Replica).adminSplitWithDescriptor.func1(0xc421338420, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/replica_command.go:2407 +0x334
github.com/cockroachdb/cockroach/pkg/internal/client.(*DB).Txn.func1(0xc421338420, 0xc421154990, 0x4000000000000000, 0x0)
	/go/src/github.com/cockroachdb/cockroach/pkg/internal/client/db.go:468 +0x47
github.com/cockroachdb/cockroach/pkg/internal/client.(*Txn).Exec(0xc421338420, 0xc421150101, 0x0, 0xc421154980, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/pkg/internal/client/txn.go:520 +0x234
github.com/cockroachdb/cockroach/pkg/internal/client.(*DB).Txn(0xc422040320, 0x2b7d7ef7ad98, 0xc4203eaae0, 0xc4204b36c0, 0xc420773780, 0x2)
	/go/src/github.com/cockroachdb/cockroach/pkg/internal/client/db.go:469 +0x298
github.com/cockroachdb/cockroach/pkg/storage.(*Replica).adminSplitWithDescriptor(0xc4223f5900, 0x2b7d7ef7ad98, 0xc4203eaae0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0xc421154728, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/replica_command.go:2449 +0xe13
github.com/cockroachdb/cockroach/pkg/storage.(*splitQueue).process(0xc421ff72a0, 0x2b7d7ef7ad98, 0xc4203eaae0, 0xc421894de0, 0xc4223f5900, 0xc422397000, 0x1c, 0x20, 0x0, 0xc421ef7ae0)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/split_queue.go:111 +0x331
github.com/cockroachdb/cockroach/pkg/storage.(*baseQueue).processReplica(0xc420016780, 0x2b7d7ef74078, 0xc421894d20, 0xc4223f5900, 0xc42095a300, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/queue.go:579 +0x5db
github.com/cockroachdb/cockroach/pkg/storage.(*baseQueue).processLoop.func1.2()
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/queue.go:499 +0x119
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunTask(0xc421080000, 0xc420773e40, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:224 +0x10e
github.com/cockroachdb/cockroach/pkg/storage.(*baseQueue).processLoop.func1()
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/queue.go:506 +0x45a
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc421080000, 0xc421f78b80)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:196 +0x8b
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:197 +0x74

goroutine 40179 [semacquire]:
sync.runtime_notifyListWait(0xc421c739d0, 0xc40000015a)
	/usr/local/go/src/runtime/sema.go:267 +0x12f
sync.(*Cond).Wait(0xc421c739c0)
	/usr/local/go/src/sync/cond.go:57 +0x8e
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).worker(0xc420ef4790, 0xc421080000)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:212 +0xfd
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).Start.func2()
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:181 +0x4b
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc421080000, 0xc421f78440)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:196 +0x8b
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:197 +0x74

goroutine 40180 [semacquire]:
sync.runtime_notifyListWait(0xc421c739d0, 0xc40000015d)
	/usr/local/go/src/runtime/sema.go:267 +0x12f
sync.(*Cond).Wait(0xc421c739c0)
	/usr/local/go/src/sync/cond.go:57 +0x8e
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).worker(0xc420ef4790, 0xc421080000)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:212 +0xfd
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).Start.func2()
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:181 +0x4b
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc421080000, 0xc421f78480)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:196 +0x8b
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:197 +0x74

goroutine 40212 [select]:
github.com/cockroachdb/cockroach/pkg/storage.(*Store).startGossip.func1()
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/store.go:1287 +0x4b6
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc421080000, 0xc4223e60c0)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:196 +0x8b
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:197 +0x74

goroutine 40186 [semacquire]:
sync.runtime_notifyListWait(0xc421c739d0, 0xc400000165)
	/usr/local/go/src/runtime/sema.go:267 +0x12f
sync.(*Cond).Wait(0xc421c739c0)
	/usr/local/go/src/sync/cond.go:57 +0x8e
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).worker(0xc420ef4790, 0xc421080000)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:212 +0xfd
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).Start.func2()
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:181 +0x4b
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc421080000, 0xc421f78620)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:196 +0x8b
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:197 +0x74

goroutine 40182 [semacquire]:
sync.runtime_notifyListWait(0xc421c739d0, 0xc40000015c)
	/usr/local/go/src/runtime/sema.go:267 +0x12f
sync.(*Cond).Wait(0xc421c739c0)
	/usr/local/go/src/sync/cond.go:57 +0x8e
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).worker(0xc420ef4790, 0xc421080000)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:212 +0xfd
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).Start.func2()
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:181 +0x4b
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc421080000, 0xc421f78540)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:196 +0x8b
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:197 +0x74

goroutine 40128 [select]:
github.com/cockroachdb/cockroach/pkg/kv.(*TxnCoordSender).printStatsLoop(0xc4210406e0, 0x2b7d7d3b6000, 0xc420096428)
	/go/src/github.com/cockroachdb/cockroach/pkg/kv/txn_coord_sender.go:209 +0x1011
github.com/cockroachdb/cockroach/pkg/kv.NewTxnCoordSender.func1()
	/go/src/github.com/cockroachdb/cockroach/pkg/kv/txn_coord_sender.go:193 +0xc0
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc421080000, 0xc421ff6870)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:196 +0x8b
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:197 +0x74

goroutine 40125 [chan receive]:
github.com/cockroachdb/cockroach/pkg/storage/engine.(*RocksDB).open.func1(0xc42001c050)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/engine/rocksdb.go:373 +0x64
created by github.com/cockroachdb/cockroach/pkg/storage/engine.(*RocksDB).open
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/engine/rocksdb.go:374 +0x8fb

goroutine 40185 [semacquire]:
sync.runtime_notifyListWait(0xc421c739d0, 0xc400000166)
	/usr/local/go/src/runtime/sema.go:267 +0x12f
sync.(*Cond).Wait(0xc421c739c0)
	/usr/local/go/src/sync/cond.go:57 +0x8e
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).worker(0xc420ef4790, 0xc421080000)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:212 +0xfd
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).Start.func2()
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:181 +0x4b
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc421080000, 0xc421f78600)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:196 +0x8b
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:197 +0x74

goroutine 40181 [runnable]:
github.com/cockroachdb/cockroach/pkg/storage/engine.(*rocksDBBatch).Close(0xc420961500)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/engine/rocksdb.go:883
github.com/cockroachdb/cockroach/pkg/storage.(*Replica).applyRaftCommand(0xc4223f5900, 0x2b7d7ef74078, 0xc4218956e0, 0xc4214906f8, 0x8, 0x0, 0xc, 0x1, 0x0, 0x0, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/replica.go:3648 +0x86f
github.com/cockroachdb/cockroach/pkg/storage.(*Replica).processRaftCommand(0xc4223f5900, 0x2b7d7ef74078, 0xc4218956e0, 0xc4214906f8, 0x8, 0xc, 0x100000001, 0x1, 0xc42190e9b0, 0x1, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/replica.go:3429 +0x799
github.com/cockroachdb/cockroach/pkg/storage.(*Replica).handleRaftReadyRaftMuLocked(0xc4223f5900, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/replica.go:2620 +0xa28
github.com/cockroachdb/cockroach/pkg/storage.(*Replica).handleRaftReady(0xc4223f5900, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/replica.go:2453 +0xd3
github.com/cockroachdb/cockroach/pkg/storage.(*Store).processReady(0xc42027ea80, 0x17)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/store.go:3296 +0x181
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).worker(0xc420ef4790, 0xc421080000)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:230 +0x37e
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).Start.func2()
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:181 +0x4b
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc421080000, 0xc421f784c0)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:196 +0x8b
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:197 +0x74

goroutine 40192 [semacquire]:
sync.runtime_notifyListWait(0xc421c739d0, 0xc400000159)
	/usr/local/go/src/runtime/sema.go:267 +0x12f
sync.(*Cond).Wait(0xc421c739c0)
	/usr/local/go/src/sync/cond.go:57 +0x8e
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).worker(0xc420ef4790, 0xc421080000)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:212 +0xfd
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).Start.func2()
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:181 +0x4b
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc421080000, 0xc421f78780)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:196 +0x8b
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:197 +0x74

goroutine 40201 [select]:
github.com/cockroachdb/cockroach/pkg/storage.(*baseQueue).processLoop.func1()
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/queue.go:475 +0x495
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc421080000, 0xc421f78bc0)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:196 +0x8b
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:197 +0x74

goroutine 40183 [semacquire]:
sync.runtime_notifyListWait(0xc421c739d0, 0xc400000160)
	/usr/local/go/src/runtime/sema.go:267 +0x12f
sync.(*Cond).Wait(0xc421c739c0)
	/usr/local/go/src/sync/cond.go:57 +0x8e
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).worker(0xc420ef4790, 0xc421080000)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:212 +0xfd
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).Start.func2()
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:181 +0x4b
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc421080000, 0xc421f78560)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:196 +0x8b
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:197 +0x74

goroutine 40211 [select]:
github.com/cockroachdb/cockroach/pkg/storage.(*Store).startGossip.func1()
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/store.go:1287 +0x4b6
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc421080000, 0xc4223e6000)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:196 +0x8b
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:197 +0x74

goroutine 40196 [select]:
github.com/cockroachdb/cockroach/pkg/storage.(*Store).startCoalescedHeartbeatsLoop.func1()
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/store.go:3414 +0x1c5
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc421080000, 0xc4223f2410)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:196 +0x8b
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:197 +0x74

goroutine 40129 [chan receive]:
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).Start.func1()
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:171 +0x74
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc421080000, 0xc421f78380)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:196 +0x8b
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:197 +0x74

goroutine 40184 [semacquire]:
sync.runtime_notifyListWait(0xc421c739d0, 0xc400000162)
	/usr/local/go/src/runtime/sema.go:267 +0x12f
sync.(*Cond).Wait(0xc421c739c0)
	/usr/local/go/src/sync/cond.go:57 +0x8e
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).worker(0xc420ef4790, 0xc421080000)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:212 +0xfd
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).Start.func2()
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:181 +0x4b
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc421080000, 0xc421f78580)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:196 +0x8b
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:197 +0x74

goroutine 40214 [select]:
github.com/cockroachdb/cockroach/pkg/storage.(*baseQueue).maybeAddToPurgatory.func2()
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/queue.go:637 +0xf66
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc421080000, 0xc421ece9c0)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:196 +0x8b
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:197 +0x74

goroutine 40189 [semacquire]:
sync.runtime_notifyListWait(0xc421c739d0, 0xc400000161)
	/usr/local/go/src/runtime/sema.go:267 +0x12f
sync.(*Cond).Wait(0xc421c739c0)
	/usr/local/go/src/sync/cond.go:57 +0x8e
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).worker(0xc420ef4790, 0xc421080000)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:212 +0xfd
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).Start.func2()
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:181 +0x4b
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc421080000, 0xc421f786e0)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:196 +0x8b
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:197 +0x74

goroutine 40191 [semacquire]:
sync.runtime_notifyListWait(0xc421c739d0, 0xc400000163)
	/usr/local/go/src/runtime/sema.go:267 +0x12f
sync.(*Cond).Wait(0xc421c739c0)
	/usr/local/go/src/sync/cond.go:57 +0x8e
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).worker(0xc420ef4790, 0xc421080000)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:212 +0xfd
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).Start.func2()
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:181 +0x4b
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc421080000, 0xc421f78760)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:196 +0x8b
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:197 +0x74

goroutine 40195 [select]:
github.com/cockroachdb/cockroach/pkg/storage.(*Store).raftTickLoop.func1()
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/store.go:3383 +0x482
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc421080000, 0xc4223f2400)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:196 +0x8b
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:197 +0x74

goroutine 40193 [semacquire]:
sync.runtime_notifyListWait(0xc421c739d0, 0xc40000015e)
	/usr/local/go/src/runtime/sema.go:267 +0x12f
sync.(*Cond).Wait(0xc421c739c0)
	/usr/local/go/src/sync/cond.go:57 +0x8e
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).worker(0xc420ef4790, 0xc421080000)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:212 +0xfd
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).Start.func2()
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:181 +0x4b
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc421080000, 0xc421f787a0)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:196 +0x8b
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:197 +0x74

goroutine 40126 [chan receive]:
github.com/cockroachdb/cockroach/pkg/rpc.NewContext.func1()
	/go/src/github.com/cockroachdb/cockroach/pkg/rpc/context.go:137 +0x95
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc421080000, 0xc420010240)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:196 +0x8b
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:197 +0x74

goroutine 40188 [runnable]:
internal/race.Acquire(0xc4215144d8)
	/usr/local/go/src/internal/race/race.go:16
sync.(*Mutex).Lock(0xc4215144d8)
	/usr/local/go/src/sync/mutex.go:48 +0x207
github.com/cockroachdb/cockroach/pkg/util/syncutil.(*TimedMutex).Lock(0xc4223f54f0)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/syncutil/timedmutex.go:86 +0x53
github.com/cockroachdb/cockroach/pkg/storage.(*Replica).Desc(0xc4223f5400, 0x0)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/replica.go:1071 +0x54
github.com/cockroachdb/cockroach/pkg/storage.(*Replica).GC(0xc4223f5400, 0x2b7d7ef74078, 0xc4211f6810, 0x2b7d7d378980, 0xc422384fc0, 0xc4210028c0, 0x7b, 0x610, 0x100000001, 0x1, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/replica_command.go:1220 +0x697
github.com/cockroachdb/cockroach/pkg/storage.(*Replica).executeCmd(0xc4223f5400, 0x2b7d7ef74078, 0xc4211f6810, 0xc42150e2a8, 0x8, 0x0, 0x2b7d7d378980, 0xc422384fc0, 0xc4210028c0, 0x7b, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/replica_command.go:137 +0x1cb7
github.com/cockroachdb/cockroach/pkg/storage.(*Replica).executeBatch(0xc4223f5400, 0x2b7d7ef74078, 0xc4211f6810, 0xc42150e2a8, 0x8, 0x2b7d7d378980, 0xc422384fc0, 0xc4210028c0, 0x7b, 0x610, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/replica.go:4010 +0x4ec
github.com/cockroachdb/cockroach/pkg/storage.(*Replica).executeWriteBatch(0xc4223f5400, 0x2b7d7ef74078, 0xc4211f6810, 0xc42150e2a8, 0x8, 0x7b, 0x610, 0x100000001, 0x1, 0x16, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/replica.go:3802 +0x294
github.com/cockroachdb/cockroach/pkg/storage.(*Replica).applyRaftCommandInBatch(0xc4223f5400, 0x2b7d7ef74078, 0xc4211f6810, 0xc42150e2a8, 0x8, 0x7b, 0x610, 0x100000001, 0x1, 0x16, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/replica.go:3698 +0x14b
github.com/cockroachdb/cockroach/pkg/storage.(*Replica).evaluateProposal(0xc4223f5400, 0x2b7d7ef74078, 0xc4211f6810, 0xc42150e2a8, 0x8, 0x7b, 0x610, 0x100000001, 0x1, 0x16, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/replica.go:2114 +0x1ae
github.com/cockroachdb/cockroach/pkg/storage.(*Replica).processRaftCommand(0xc4223f5400, 0x2b7d7ef74078, 0xc4211f6810, 0xc42150e2a8, 0x8, 0xf, 0x100000001, 0x1, 0xc421fb7c70, 0x4, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/replica.go:3379 +0x11e9
github.com/cockroachdb/cockroach/pkg/storage.(*Replica).handleRaftReadyRaftMuLocked(0xc4223f5400, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/replica.go:2620 +0xa28
github.com/cockroachdb/cockroach/pkg/storage.(*Replica).handleRaftReady(0xc4223f5400, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/replica.go:2453 +0xd3
github.com/cockroachdb/cockroach/pkg/storage.(*Store).processReady(0xc42027ea80, 0x16)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/store.go:3296 +0x181
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).worker(0xc420ef4790, 0xc421080000)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:230 +0x37e
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).Start.func2()
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:181 +0x4b
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc421080000, 0xc421f786a0)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:196 +0x8b
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:197 +0x74

goroutine 40204 [select]:
github.com/cockroachdb/cockroach/pkg/storage.(*baseQueue).processLoop.func1()
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/queue.go:475 +0x495
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc421080000, 0xc421f78d40)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:196 +0x8b
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:197 +0x74

goroutine 40092 [select]:
github.com/cockroachdb/cockroach/pkg/storage.(*Replica).tryAddWriteCmd(0xc4223f5400, 0x2b7d7ef74078, 0xc4211f6810, 0x7b, 0x610, 0x100000001, 0x1, 0x16, 0x0, 0x0, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/replica.go:2021 +0xdeb
github.com/cockroachdb/cockroach/pkg/storage.(*Replica).addWriteCmd(0xc4223f5400, 0x2b7d7ef74078, 0xc4211f6810, 0x7b, 0x610, 0x100000001, 0x1, 0x16, 0x0, 0x0, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/replica.go:1847 +0xa1
github.com/cockroachdb/cockroach/pkg/storage.(*Replica).Send(0xc4223f5400, 0x2b7d7ef74078, 0xc4211f6810, 0x7b, 0x610, 0x100000001, 0x1, 0x16, 0x0, 0x0, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/replica.go:1299 +0x26f
github.com/cockroachdb/cockroach/pkg/storage.(*Store).Send(0xc42027ea80, 0x2b7d7ef74078, 0xc4211f6780, 0x7b, 0x610, 0x100000001, 0x1, 0x16, 0x0, 0x0, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/store.go:2471 +0x86a
github.com/cockroachdb/cockroach/pkg/storage.(*Stores).Send(0xc4211410e0, 0x2b7d7ef74078, 0xc4211f6690, 0x0, 0x0, 0x100000001, 0x1, 0x16, 0x0, 0x0, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/stores.go:187 +0x24b
github.com/cockroachdb/cockroach/pkg/kv.(*senderTransport).SendNext(0xc42028c460, 0xc4204b5c20)
	/go/src/github.com/cockroachdb/cockroach/pkg/kv/transport.go:309 +0x2c3
github.com/cockroachdb/cockroach/pkg/kv.(*DistSender).sendToReplicas(0xc4200162d0, 0x2b7d7ef74000, 0xc420712d40, 0x1dcd6500, 0xc422398a20, 0xc420016308, 0x3, 0xc4222f60c0, 0x1, 0x1, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/kv/dist_sender.go:1142 +0x376
github.com/cockroachdb/cockroach/pkg/kv.(*DistSender).sendRPC(0xc4200162d0, 0x2b7d7ef74000, 0xc420712d40, 0x3, 0xc4222f60c0, 0x1, 0x1, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/kv/dist_sender.go:410 +0x418
github.com/cockroachdb/cockroach/pkg/kv.(*DistSender).sendSingleRange(0xc4200162d0, 0x2b7d7ef74078, 0xc4211f6570, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/kv/dist_sender.go:479 +0x1ab
github.com/cockroachdb/cockroach/pkg/kv.(*DistSender).sendPartialBatch(0xc4200162d0, 0x2b7d7ef74078, 0xc4211f6570, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/kv/dist_sender.go:931 +0x3b4
github.com/cockroachdb/cockroach/pkg/kv.(*DistSender).divideAndSendBatchToRanges(0xc4200162d0, 0x2b7d7ef74078, 0xc4211f6570, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/kv/dist_sender.go:810 +0x568
github.com/cockroachdb/cockroach/pkg/kv.(*DistSender).Send(0xc4200162d0, 0x2b7d7ef74078, 0xc4211f6570, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/kv/dist_sender.go:625 +0x382
github.com/cockroachdb/cockroach/pkg/kv.(*TxnCoordSender).Send(0xc4210406e0, 0x2b7d7ef74078, 0xc4211f6570, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/kv/txn_coord_sender.go:418 +0x7f2
github.com/cockroachdb/cockroach/pkg/internal/client.(*DB).send(0xc422040320, 0x2b7d7d3b6000, 0xc420096440, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/internal/client/db.go:513 +0x14d
github.com/cockroachdb/cockroach/pkg/internal/client.(*DB).Run.func1(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/internal/client/db.go:447 +0x8f
github.com/cockroachdb/cockroach/pkg/internal/client.sendAndFill(0xc421463f60, 0xc420e37200, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/pkg/internal/client/db.go:418 +0x1ac
github.com/cockroachdb/cockroach/pkg/internal/client.(*DB).Run(0xc422040320, 0x2b7d7d3b6000, 0xc420096440, 0xc420e37200, 0x1, 0xc4211f6540)
	/go/src/github.com/cockroachdb/cockroach/pkg/internal/client/db.go:449 +0x126
github.com/cockroachdb/cockroach/pkg/storage.(*intentResolver).processIntents(0xc422019fa0, 0x2b7d7d3b6000, 0xc420096440, 0xc4223f5400, 0x2fd4ca0, 0xc420cbd2c0, 0xc421812fc0, 0x2, 0x2, 0x7b, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/intent_resolver.go:387 +0xc9f
github.com/cockroachdb/cockroach/pkg/storage.(*intentResolver).processIntentsAsync.func1(0x2b7d7d3b6000, 0xc420096440)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/intent_resolver.go:277 +0xfd
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunLimitedAsyncTask.func1(0xc421080000, 0x2cad066, 0x1a, 0x116, 0xc420b64540, 0x0, 0x0, 0xc421846480, 0x2b7d7d3b6000, 0xc420096440)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:326 +0x11a
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunLimitedAsyncTask
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:327 +0x48e

goroutine 40080 [sleep]:
time.Sleep(0x4000000)
	/usr/local/go/src/runtime/time.go:59 +0xe1
github.com/cockroachdb/cockroach/pkg/util.RetryForDuration(0xa7a358200, 0xc421b1fc00, 0xeb7792, 0x30)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/retry.go:38 +0x116
github.com/cockroachdb/cockroach/pkg/testutils.SucceedsSoonDepth(0x1, 0x2fd8be0, 0xc42108a840, 0xc421b1fc00)
	/go/src/github.com/cockroachdb/cockroach/pkg/testutils/soon.go:41 +0x55
github.com/cockroachdb/cockroach/pkg/storage_test.TestStoreRangeSystemSplits.func2(0x13)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/client_split_test.go:879 +0x92d
github.com/cockroachdb/cockroach/pkg/storage_test.TestStoreRangeSystemSplits(0xc42108a840)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/client_split_test.go:882 +0x49f
testing.tRunner(0xc42108a840, 0x24d8ec0)
	/usr/local/go/src/testing/testing.go:610 +0xca
created by testing.(*T).Run
	/usr/local/go/src/testing/testing.go:646 +0x530

goroutine 40202 [select]:
github.com/cockroachdb/cockroach/pkg/storage.(*baseQueue).processLoop.func1()
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/queue.go:475 +0x495
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc421080000, 0xc421f78c60)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:196 +0x8b
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:197 +0x74

goroutine 40210 [select]:
github.com/cockroachdb/cockroach/pkg/storage.(*Store).Start.func3()
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/store.go:1201 +0x19d
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc421080000, 0xc421ece1a0)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:196 +0x8b
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:197 +0x74

goroutine 40187 [semacquire]:
sync.runtime_notifyListWait(0xc421c739d0, 0xc400000164)
	/usr/local/go/src/runtime/sema.go:267 +0x12f
sync.(*Cond).Wait(0xc421c739c0)
	/usr/local/go/src/sync/cond.go:57 +0x8e
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).worker(0xc420ef4790, 0xc421080000)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:212 +0xfd
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).Start.func2()
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:181 +0x4b
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc421080000, 0xc421f78680)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:196 +0x8b
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:197 +0x74

goroutine 40194 [semacquire]:
sync.runtime_Semacquire(0xc420ef4834)
	/usr/local/go/src/runtime/sema.go:47 +0x30
sync.(*WaitGroup).Wait(0xc420ef4828)
	/usr/local/go/src/sync/waitgroup.go:131 +0xbf
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).Wait(0xc420ef4790)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:187 +0x42
github.com/cockroachdb/cockroach/pkg/storage.(*Store).processRaft.func1()
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/store.go:3357 +0x67
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc421080000, 0xc4223f23f0)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:196 +0x8b
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:197 +0x74

goroutine 40190 [semacquire]:
sync.runtime_notifyListWait(0xc421c739d0, 0xc40000015f)
	/usr/local/go/src/runtime/sema.go:267 +0x12f
sync.(*Cond).Wait(0xc421c739c0)
	/usr/local/go/src/sync/cond.go:57 +0x8e
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).worker(0xc420ef4790, 0xc421080000)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:212 +0xfd
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).Start.func2()
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:181 +0x4b
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc421080000, 0xc421f78700)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:196 +0x8b
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:197 +0x74

goroutine 40156 [runnable]:
internal/race.Acquire(0xc420b3af40)
	/usr/local/go/src/internal/race/race.go:16
sync.(*Mutex).Lock(0xc420b3af40)
	/usr/local/go/src/sync/mutex.go:92 +0xf8
github.com/cockroachdb/cockroach/pkg/util/metric.(*Histogram).RecordValue(0xc420b3af00, 0x5dc)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/metric/metric.go:217 +0x48
github.com/cockroachdb/cockroach/pkg/storage.newReplica.func4(0x5dc)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/replica.go:603 +0xb2
github.com/cockroachdb/cockroach/pkg/util/syncutil.ThresholdLogger.func1(0x5dc)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/syncutil/timedmutex.go:53 +0x84
github.com/cockroachdb/cockroach/pkg/util/syncutil.(*TimedMutex).Unlock(0xc420232af0)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/syncutil/timedmutex.go:97 +0x127
github.com/cockroachdb/cockroach/pkg/storage.(*Replica).Desc(0xc420232a00, 0xc42246d680)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/replica.go:1073 +0xa1
github.com/cockroachdb/cockroach/pkg/storage.(*Store).visitReplicasLocked.func1(0x2fb91c0, 0xc420232a00, 0xc421188080)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/store.go:1599 +0xb2
github.com/cockroachdb/cockroach/vendor/github.com/google/btree.(*node).iterate(0xc421fd4240, 0x1, 0x2fbcac0, 0xc421188080, 0x0, 0x0, 0xc420440001, 0xc4204439c0, 0x749568)
	/go/src/github.com/cockroachdb/cockroach/vendor/github.com/google/btree/btree.go:484 +0x185
github.com/cockroachdb/cockroach/vendor/github.com/google/btree.(*BTree).AscendGreaterOrEqual(0xc4224ce020, 0x2fbcac0, 0xc421188080, 0xc4204439c0)
	/go/src/github.com/cockroachdb/cockroach/vendor/github.com/google/btree/btree.go:655 +0xb7
github.com/cockroachdb/cockroach/pkg/storage.(*Store).visitReplicasLocked(0xc42027ea80, 0xc4201ef030, 0xc, 0xc, 0x2fb32b8, 0x2, 0x2, 0xc420443aa0)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/store.go:1610 +0x1ae
github.com/cockroachdb/cockroach/pkg/storage.(*Store).LookupReplica(0xc42027ea80, 0xc4201ef030, 0xc, 0xc, 0x0, 0x0, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/store.go:1557 +0x161
github.com/cockroachdb/cockroach/pkg/storage.(*Stores).LookupReplica(0xc4211410e0, 0xc4201ef030, 0xc, 0xc, 0xc421155240, 0xd, 0xd, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/stores.go:209 +0x200
github.com/cockroachdb/cockroach/pkg/storage.(*Stores).Send(0xc4211410e0, 0x2b7d7ef74078, 0xc421895c80, 0x0, 0x0, 0x0, 0x0, 0x1, 0x0, 0x0, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/stores.go:152 +0x17a
github.com/cockroachdb/cockroach/pkg/kv.(*senderTransport).SendNext(0xc421041900, 0xc4203eb980)
	/go/src/github.com/cockroachdb/cockroach/pkg/kv/transport.go:309 +0x2c3
github.com/cockroachdb/cockroach/pkg/kv.(*DistSender).sendToReplicas(0xc4200162d0, 0x2b7d7ef74000, 0xc42045ca00, 0x1dcd6500, 0xc422398a20, 0xc420016308, 0x1, 0xc4214e3ee0, 0x1, 0x1, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/kv/dist_sender.go:1142 +0x376
github.com/cockroachdb/cockroach/pkg/kv.(*DistSender).sendRPC(0xc4200162d0, 0x2b7d7ef74000, 0xc42045ca00, 0x1, 0xc4214e3ee0, 0x1, 0x1, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/kv/dist_sender.go:410 +0x418
github.com/cockroachdb/cockroach/pkg/kv.(*DistSender).sendSingleRange(0xc4200162d0, 0x2b7d7ef74078, 0xc421895b00, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/kv/dist_sender.go:479 +0x1ab
github.com/cockroachdb/cockroach/pkg/kv.(*DistSender).sendPartialBatch(0xc4200162d0, 0x2b7d7ef74078, 0xc421895b00, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/kv/dist_sender.go:931 +0x3b4
github.com/cockroachdb/cockroach/pkg/kv.(*DistSender).divideAndSendBatchToRanges(0xc4200162d0, 0x2b7d7ef74078, 0xc421895b00, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/kv/dist_sender.go:810 +0x568
github.com/cockroachdb/cockroach/pkg/kv.(*DistSender).Send(0xc4200162d0, 0x2b7d7ef74078, 0xc421895b00, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/kv/dist_sender.go:625 +0x382
github.com/cockroachdb/cockroach/pkg/kv.(*TxnCoordSender).Send(0xc4210406e0, 0x2b7d7ef74078, 0xc421895b00, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/kv/txn_coord_sender.go:418 +0x7f2
github.com/cockroachdb/cockroach/pkg/internal/client.(*DB).send(0xc422040320, 0x2b7d7ef74078, 0xc4223d11d0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/internal/client/db.go:513 +0x14d
github.com/cockroachdb/cockroach/pkg/internal/client.(*DB).Run.func1(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/internal/client/db.go:447 +0x8f
github.com/cockroachdb/cockroach/pkg/internal/client.sendAndFill(0xc4214e3d40, 0xc420d6e000, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/pkg/internal/client/db.go:418 +0x1ac
github.com/cockroachdb/cockroach/pkg/internal/client.(*DB).Run(0xc422040320, 0x2b7d7ef74078, 0xc4223d11d0, 0xc420d6e000, 0xc4214e3d20, 0x18)
	/go/src/github.com/cockroachdb/cockroach/pkg/internal/client/db.go:449 +0x126
github.com/cockroachdb/cockroach/pkg/internal/client.(*DB).Inc(0xc422040320, 0x2b7d7ef74078, 0xc4223d11d0, 0x202e200, 0xc4214e3d20, 0xa, 0xc421080030, 0xc42147e820, 0x0, 0xc422632100, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/internal/client/db.go:287 +0xec
github.com/cockroachdb/cockroach/pkg/storage.(*idAllocator).start.func1.1()
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/id_alloc.go:107 +0x163
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunTask(0xc421080000, 0xc420445e38, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:224 +0x10e
github.com/cockroachdb/cockroach/pkg/storage.(*idAllocator).start.func1()
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/id_alloc.go:108 +0x49c
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc421080000, 0xc4217695e0)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:196 +0x8b
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:197 +0x74

goroutine 40199 [select]:
github.com/cockroachdb/cockroach/pkg/storage.(*baseQueue).processLoop.func1()
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/queue.go:475 +0x495
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc421080000, 0xc421f78b60)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:196 +0x8b
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:197 +0x74


ERROR: exit status 2

make: *** [stress] Error 1
1 runs completed, 1 failures, over 1m23s
Makefile:138: recipe for target 'stress' failed
```

### PR DESCRIPTION
**Pull request by spencerkimball**
The consistency queue was kicking in and processing before the test could
complete. We don't initialize a `NodeLiveness` instance for the store-only
tests, so this was getting a nil pointer exception.

Fixes #12218

---
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/12224)

### CODE REVIEW

File: pkg/storage/client_test.go [hunk 1]
```diff
@@ -158,6 +158,7 @@ func createTestStoreWithEngine(
 	storeCfg.Transport = storage.NewDummyRaftTransport()
 	// TODO(bdarnell): arrange to have the transport closed.
 	store := storage.NewStore(storeCfg, eng, nodeDesc)
+	store.SetConsistencyQueueActive(false)
```
Comment (tamird) [inline pkg/storage/client_test.go]: can you leave a comment?

**Review by tamird — APPROVED** [review]

File: pkg/storage/client_test.go (hunk 1 above)
Comment (spencerkimball) [inline pkg/storage/client_test.go]: Done.

**Comment by tamird** [comment]
LGTM
