### PR TITLE
logical: convert simple validation tests to table-driven format

### LINKED ISSUE #164187: crosscluster/logical: TestLogicalReplicationCreationChecks failed
crosscluster/logical.TestLogicalReplicationCreationChecks [failed](https://mesolite.cluster.engflow.com/invocations/default/8915596d-056e-4e6b-854c-f18f774f9462?testReportRun=1&testReportShard=3&testReportAttempt=1#targets-Ly9wa2cvY3Jvc3NjbHVzdGVyL2xvZ2ljYWw6bG9naWNhbF90ZXN0) on master @ [7bf9f6dcd17f40b5c5dd7d94241a198e86f6a5ee](https://github.com/cockroachdb/cockroach/commits/7bf9f6dcd17f40b5c5dd7d94241a198e86f6a5ee):

```
=== RUN   TestLogicalReplicationCreationChecks
    test_log_scope.go:172: test logs captured to: outputs.zip/logTestLogicalReplicationCreationChecks789161125
    test_log_scope.go:82: use -show-logs to present logs inline
    sql_runner.go:117: 
        	Error Trace:	pkg/testutils/sqlutils/sql_runner.go:130
        	            				pkg/testutils/sqlutils/sql_runner.go:391
        	            				pkg/crosscluster/replicationtestutils/testutils.go:774
        	            				pkg/crosscluster/logical/logical_replication_job_test.go:2759
        	            				pkg/crosscluster/logical/logical_replication_job_test.go:2861
        	            				src/runtime/asm_amd64.s:1693
        	Error:      	Received unexpected error:
        	            	query 'SELECT distinct(status) FROM [SHOW JOBS] where job_type = 'REPLICATION STREAM PRODUCER'': expected:
        	            	(1) attached stack trace
        	            	  -- stack trace:
        	            	  | github.com/cockroachdb/cockroach/pkg/testutils/sqlutils.(*SQLRunner).CheckQueryResultsRetry.func1
        	            	  | 	pkg/testutils/sqlutils/sql_runner.go:394
        	            	  | github.com/cockroachdb/cockroach/pkg/testutils.SucceedsWithinError.func1
        	            	  | 	pkg/testutils/soon.go:71
        	            	  | github.com/cockroachdb/cockroach/pkg/util/retry.ForDuration
        	            	  | 	pkg/util/retry/retry.go:362
        	            	  | github.com/cockroachdb/cockroach/pkg/testutils.SucceedsWithinError
        	            	  | 	pkg/testutils/soon.go:77
        	            	  | github.com/cockroachdb/cockroach/pkg/testutils/sqlutils.(*SQLRunner).succeedsWithin
        	            	  | 	pkg/testutils/sqlutils/sql_runner.go:130
        	            	  | github.com/cockroachdb/cockroach/pkg/testutils/sqlutils.(*SQLRunner).CheckQueryResultsRetry
        	            	  | 	pkg/testutils/sqlutils/sql_runner.go:391
        	            	  | github.com/cockroachdb/cockroach/pkg/crosscluster/replicationtestutils.WaitForAllProducerJobsToFail
        	            	  | 	pkg/crosscluster/replicationtestutils/testutils.go:774
        	            	  | github.com/cockroachdb/cockroach/pkg/crosscluster/logical.TestLogicalReplicationCreationChecks.func1
        	            	  | 	pkg/crosscluster/logical/logical_replication_job_test.go:2759
        	            	  | github.com/cockroachdb/cockroach/pkg/crosscluster/logical.TestLogicalReplicationCreationChecks
        	            	  | 	pkg/crosscluster/logical/logical_replication_job_test.go:2861
        	            	  | testing.tRunner
        	            	  | 	GOROOT/src/testing/testing.go:1934
        	            	  | runtime.goexit
        	            	  | 	src/runtime/asm_amd64.s:1693
        	            	Wraps: (2) query 'SELECT distinct(status) FROM [SHOW JOBS] where job_type = 'REPLICATION STREAM PRODUCER'': expected:
        	            	  | failed
        	            	  |
        	            	  | got:
        	            	  | failed
        	            	  | running
        	            	Error types: (1) *withstack.withStack (2) *errutil.leafError
    panic.go:615: -- test log scope end --
test logs left over in: outputs.zip/logTestLogicalReplicationCreationChecks789161125
--- FAIL: TestLogicalReplicationCreationChecks (70.34s)
```

Parameters:
 - <code>attempt=1</code>
 - <code>run=1</code>
 - <code>shard=3</code>
<details><summary>Help</summary>
<p>

See also: [How To Investigate a Go Test Failure \(internal\)](https://cockroachlabs.atlassian.net/l/c/HgfXfJgM)
</p>
</details>
/cc @cockroachdb/cdc
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*TestLogicalReplicationCreationChecks.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/bazci/githubpost/issues)

</sub>

Jira issue: CRDB-60678

### PR DESCRIPTION
**Pull request by aerfrei**
Converts the remaining validation failure tests from
TestLogicalReplicationCreationChecks to a table-driven format in the new
TestSchemaValidation test function.

These tests share a server but each creates its own database.

Fixes: https://github.com/cockroachdb/cockroach/issues/164187

Epic: none
Release note: None

### CODE REVIEW

File: pkg/crosscluster/logical/logical_replication_job_test.go [hunk 1]
```diff
@@ -2847,204 +2847,320 @@ func TestSupportedSchemaChecks(t *testing.T) {
...
+			}
 
-	// Kill replication job.
-	dbA.Exec(t, "CANCEL JOB $1", jobAID)
-	jobutils.WaitForJobToCancel(t, dbA, jobAID)
-	replicationtestutils.WaitForAllProducerJobsToFail(t, dbB)
+			dbSource.ExpectErr(
+				t,
+				tc.expectedErr,
+				"CREATE LOGICAL REPLICATION STREAM FROM TABLE tab ON $1 INTO TABLE tab WITH MODE = 'validated'",
```
Comment (jeffswenson) [inline pkg/crosscluster/logical/logical_replication_job_test.go:3172]: The dbSource and dbDestination names are swapped here. The LDR create job is run on the destination cluster.

File: pkg/crosscluster/logical/logical_replication_job_test.go [hunk 2]
```diff
@@ -2847,204 +2847,320 @@ func TestSupportedSchemaChecks(t *testing.T) {
...
+	}
 
-	// Kill replication job.
-	dbA.Exec(t, "CANCEL JOB $1", jobAID)
-	jobutils.WaitForJobToCancel(t, dbA, jobAID)
-	replicationtestutils.WaitForAllProducerJobsToFail(t, dbB)
+	for _, tc := range validationTests {
+		t.Run(tc.name, func(t *testing.T) {
+			// Each test case gets its own server for isolation.
+			server, s, dbSource, dbDest := setupLogicalTestServer(t, ctx, testClusterBaseClusterArgs, 1)
```
Comment (jeffswenson) [inline pkg/crosscluster/logical/logical_replication_job_test.go]: This test is the slowest test in the ldr package and I'm worried starting/stopping a bunch of test servers will make it even slower.

Maybe instead of a test server for each test case you can set up a database for each test case. I know that goes against my stated goal of avoiding test server flakes caused by large load, but I worry creating and turning down a bunch of test servers is also exposes us to flakes and it does make the test take longer to run.

Alternatively, we could switch this from a table driven test to a test helper that looks something like:

requireSchemaValidation(t, SchemaTestCase {
  sourceSetup: ...,
  destSetup: ...,
  tableName: ...
})

Then we can define each of these as their own test:

TestSchemaValidation_RefcursorNotSupport(t *testing.T) {
   requireSchemaValidation(t, ...)
}

The advantage of putting each of these in their own test is they can get sharded by bazel which reduces the overall execution time.

Comment (aerfrei) [reply pkg/crosscluster/logical/logical_replication_job_test.go]: I tried the test helper version but it was timing out under stressrace. I'm going to try to implement the database per test case approach. I'll rerequest review when that's ready

**Review by jeffswenson — APPROVED** [review]
LGTM

Thanks! Looks great!
