### PR TITLE
workload/schemachange: enable inserts

### LINKED ISSUE #127263: workload/schemachange: null value violates not-null constraint
```
 "ops": [
  "BEGIN",
  {
   "sql": "ALTER TABLE public.table_w1_12 ADD COLUMN col_w1_12_w0_13 TIMESTAMP NOT NULL"
  },
  {
   "sql": "ALTER TABLE public.table_w1_12 ADD COLUMN col_w1_12_w0_14 VARCHAR"
  },
  {
   "sql": "INSERT INTO public.table_w1_12 (col5_w1_6,col5_w1_7,col5_w1_8,\"co}%3fl5 _w1_9\",col5_w1_10,col5_w1_11) VALUES (3.4028234663852886e+38:::FLOAT8,true,B'1111100001',(-87):::INT8,93:::INT8,'10:13:58.136719-02:45':::TIMETZ)"
  },
  {
   "sql": "ALTER TABLE public.table_w1_12 ADD COLUMN col_w1_12_w0_15 REGROLE"
  },
  "COMMIT"
 ],
 "expectedExecErrors": "",
 "expectedCommitErrors": "",
 "message": "***UNEXPECTED COMMIT ERROR; Received an unexpected commit error: ERROR: transaction committed but schema change aborted with error: (23502): null value in column \"col_w1_12_w0_13\" violates not-null constraint (SQLSTATE 23502)",
```

I'm not getting too much from the queriesForGeneratingErrors, but I think we need to look to see if theres some syntax issue (first guess) or something wrong with the query in `valuesViolateUniqueConstraints`

<details> <summary> query dump </summary>

```
 "message": "***UNEXPECTED COMMIT ERROR; Received an unexpected commit error: ERROR: transaction committed but schema change aborted with error: (23502): null value in column \"col_w1_12_w0_13\" violates not-null constraint (SQLSTATE 23502)",
 "errorState": {
  "queriesForGeneratingErrors": [
   {
    "query": "WITH descriptors AS (SELECT descriptor.id, \"parentSchemaID\" AS schema_id, namespace.name AS name, crdb_internal.pb_to_json('desc', descriptor) AS descriptor FROM system.descriptor JOIN (SELECT * FROM system.namespace UNION SELECT \"parentID\", \"parentSchemaID\", (json_each).@1 AS name, (json_array_elements((json_each).@2-\u003e'signatures')-\u003e'id')::INT8 AS id FROM (SELECT ns.\"parentID\", ns.id AS \"parentSchemaID\", json_each((crdb_internal.pb_to_json('desc', descriptor)-\u003e'schema')-\u003e'functions') FROM system.descriptor JOIN system.namespace AS ns ON ns.id = descriptor.id WHERE crdb_internal.pb_to_json('desc', descriptor) ? 'schema')) AS namespace ON namespace.id = descriptor.id WHERE \"parentID\" = (SELECT id FROM system.namespace WHERE (name = current_database()) AND (\"parentID\" = 0))), enums AS (SELECT id, schema_id, name, descriptor-\u003e'type' AS descriptor FROM descriptors WHERE descriptor ? 'type'), enum_members AS (SELECT *, jsonb_array_elements(descriptor-\u003e'enumMembers') AS member FROM enums) SELECT (quote_ident(schema_id::REGNAMESPACE::STRING) || '.') || quote_ident(name) AS name, quote_literal(member-\u003e\u003e'logicalRepresentation') AS value, COALESCE((member-\u003e\u003e'direction') = 'REMOVE', false) AS dropping, COALESCE(json_array_length(descriptor-\u003e'referencingDescriptorIds') \u003e 0, false) AS has_references FROM enum_members",
    "result": []
   },
   {
    "query": "SELECT EXISTS (SELECT table_name FROM information_schema.tables WHERE (table_schema = $1) AND (table_name = $2))",
    "queryArgs": [
     "public",
     "table_w0_1"
    ],
    "result": false
   },
   {
    "query": "SELECT EXISTS (SELECT table_name FROM information_schema.tables WHERE (table_schema = $1) AND (table_name = $2))",
    "queryArgs": [
     "public",
     "table_w0_2"
    ],
    "result": false
   },
   {
    "query": "SELECT EXISTS (SELECT table_name FROM information_schema.tables WHERE (table_schema = $1) AND (table_name = $2))",
    "queryArgs": [
     "public",
     "table_w0_3"
    ],
    "result": false
   },
   {
    "query": "SELECT EXISTS (SELECT * FROM [SHOW REGIONS FROM DATABASE])",
    "result": false
   },
   {
    "query": "SELECT EXISTS (SELECT table_name FROM information_schema.tables WHERE (table_schema = $1) AND (table_name = $2))",
    "queryArgs": [
     "schema_w0_4",
     "table_w0_5"
    ],
    "result": false
   },
   {
    "query": "SELECT EXISTS (SELECT schema_name FROM information_schema.schemata WHERE schema_name = $1)",
    "queryArgs": [
     "schema_w0_4"
    ],
    "result": false
   },
   {
    "query": "SELECT EXISTS (SELECT table_name FROM information_schema.tables WHERE (table_schema = $1) AND (table_name = $2))",
    "queryArgs": [
     "public",
     "table_w1_12"
    ],
    "result": true
   },
   {
    "query": "SELECT array_agg(index_name) FROM (SELECT index_name FROM crdb_internal.table_indexes WHERE (index_type = 'primary') AND (descriptor_id = $1::REGCLASS))",
    "queryArgs": [
     "public.table_w1_12"
    ],
    "result": [
     "table_w1_5_pkey"
    ]
   },
   {
    "query": "SELECT count(*) \u003e 0 FROM crdb_internal.schema_changes WHERE (((type = 'INDEX') AND (table_id = $1::REGCLASS)) AND (target_name = $2)) AND (direction = 'DROP')",
    "queryArgs": [
     "public.table_w1_12",
     "table_w1_5_pkey"
    ],
    "result": false
   },
   {
    "query": "SELECT EXISTS (SELECT * FROM [SHOW REGIONS FROM DATABASE])",
    "result": false
   },
   {
    "query": "WITH descriptors AS (SELECT crdb_internal.pb_to_json('cockroach.sql.sqlbase.Descriptor', descriptor)-\u003e'table' AS d FROM system.descriptor WHERE id = $1::REGCLASS) SELECT EXISTS (SELECT 1 FROM descriptors WHERE ((d-\u003e'localityConfig')-\u003e'regionalByRow') IS NOT NULL)",
    "queryArgs": [
     "public.table_w1_12"
    ],
    "result": false
   },
   {
    "query": "SELECT EXISTS (SELECT column_name FROM information_schema.columns WHERE ((table_schema = $1) AND (table_name = $2)) AND (column_name = $3))",
    "queryArgs": [
     "public",
     "table_w1_12",
     "col_w1_12_w0_13"
    ],
    "result": false
   },
   {
    "query": "SELECT EXISTS (SELECT * FROM public.table_w1_12)",
    "result": false
   },
   {
    "query": "WITH descriptors AS (SELECT crdb_internal.pb_to_json('cockroach.sql.sqlbase.Descriptor', descriptor)-\u003e'table' AS d FROM system.descriptor WHERE id = $1::REGCLASS) SELECT EXISTS (SELECT mut FROM (SELECT json_array_elements(d-\u003e'mutations') AS mut FROM descriptors) WHERE (mut-\u003e'primaryKeySwap') IS NOT NULL)",
    "queryArgs": [
     "public.table_w1_12"
    ],
    "result": false
   },
   {
    "query": "SELECT EXISTS (SELECT table_name FROM information_schema.tables WHERE (table_schema = $1) AND (table_name = $2))",
    "queryArgs": [
     "public",
     "table_w1_12"
    ],
    "result": true
   },
   {
    "query": "SELECT array_agg(index_name) FROM (SELECT index_name FROM crdb_internal.table_indexes WHERE (index_type = 'primary') AND (descriptor_id = $1::REGCLASS))",
    "queryArgs": [
     "public.table_w1_12"
    ],
    "result": [
     "table_w1_5_pkey"
    ]
   },
   {
    "query": "SELECT count(*) \u003e 0 FROM crdb_internal.schema_changes WHERE (((type = 'INDEX') AND (table_id = $1::REGCLASS)) AND (target_name = $2)) AND (direction = 'DROP')",
    "queryArgs": [
     "public.table_w1_12",
     "table_w1_5_pkey"
    ],
    "result": false
   },
   {
    "query": "SELECT EXISTS (SELECT * FROM [SHOW REGIONS FROM DATABASE])",
    "result": false
   },
   {
    "query": "WITH descriptors AS (SELECT crdb_internal.pb_to_json('cockroach.sql.sqlbase.Descriptor', descriptor)-\u003e'table' AS d FROM system.descriptor WHERE id = $1::REGCLASS) SELECT EXISTS (SELECT 1 FROM descriptors WHERE ((d-\u003e'localityConfig')-\u003e'regionalByRow') IS NOT NULL)",
    "queryArgs": [
     "public.table_w1_12"
    ],
    "result": false
   },
   {
    "query": "SELECT EXISTS (SELECT column_name FROM information_schema.columns WHERE ((table_schema = $1) AND (table_name = $2)) AND (column_name = $3))",
    "queryArgs": [
     "public",
     "table_w1_12",
     "col_w1_12_w0_14"
    ],
    "result": false
   },
   {
    "query": "SELECT EXISTS (SELECT * FROM public.table_w1_12)",
    "result": false
   },
   {
    "query": "WITH descriptors AS (SELECT crdb_internal.pb_to_json('cockroach.sql.sqlbase.Descriptor', descriptor)-\u003e'table' AS d FROM system.descriptor WHERE id = $1::REGCLASS) SELECT EXISTS (SELECT mut FROM (SELECT json_array_elements(d-\u003e'mutations') AS mut FROM descriptors) WHERE (mut-\u003e'primaryKeySwap') IS NOT NULL)",
    "queryArgs": [
     "public.table_w1_12"
    ],
    "result": false
   },
   {
    "query": "SELECT EXISTS (SELECT table_name FROM information_schema.tables WHERE (table_schema = $1) AND (table_name = $2))",
    "queryArgs": [
     "public",
     "table_w1_12"
    ],
    "result": true
   },
   {
    "query": "SELECT ARRAY[parent.table_schema, parent.table_name, quote_ident(parent.column_name), quote_ident(child.column_name)] FROM (SELECT conname, conkey, confkey, conrelid, confrelid FROM pg_constraint WHERE (contype = 'f') AND (conrelid = 'public.table_w1_12'::REGCLASS::INT8)) AS con JOIN (SELECT column_name, ordinal_position, column_default FROM information_schema.columns WHERE (table_schema = 'public') AND (table_name = 'table_w1_12')) AS child ON conkey[1] = child.ordinal_position JOIN (SELECT pc.oid, cols.table_schema, cols.table_name, cols.column_name, cols.ordinal_position FROM pg_class AS pc JOIN pg_namespace AS pn ON pc.relnamespace = pn.oid JOIN information_schema.columns AS cols ON ((pc.relname = cols.table_name) AND (pn.nspname = cols.table_schema))) AS parent ON ((con.confkey[1] = parent.ordinal_position) AND (con.confrelid = parent.oid)) WHERE child.column_name != 'rowid'",
    "result": null
   },
   {
    "query": "SELECT EXISTS (SELECT table_name FROM information_schema.tables WHERE (table_schema = $1) AND (table_name = $2))",
    "queryArgs": [
     "public",
     "table_w1_12"
    ],
    "result": true
   },
   {
    "query": "SELECT array_agg(index_name) FROM (SELECT index_name FROM crdb_internal.table_indexes WHERE (index_type = 'primary') AND (descriptor_id = $1::REGCLASS))",
    "queryArgs": [
     "public.table_w1_12"
    ],
    "result": [
     "table_w1_5_pkey"
    ]
   },
   {
    "query": "SELECT count(*) \u003e 0 FROM crdb_internal.schema_changes WHERE (((type = 'INDEX') AND (table_id = $1::REGCLASS)) AND (target_name = $2)) AND (direction = 'DROP')",
    "queryArgs": [
     "public.table_w1_12",
     "table_w1_5_pkey"
    ],
    "result": false
   },
   {
    "query": "SELECT EXISTS (SELECT * FROM [SHOW REGIONS FROM DATABASE])",
    "result": false
   },
   {
    "query": "WITH descriptors AS (SELECT crdb_internal.pb_to_json('cockroach.sql.sqlbase.Descriptor', descriptor)-\u003e'table' AS d FROM system.descriptor WHERE id = $1::REGCLASS) SELECT EXISTS (SELECT 1 FROM descriptors WHERE ((d-\u003e'localityConfig')-\u003e'regionalByRow') IS NOT NULL)",
    "queryArgs": [
     "public.table_w1_12"
    ],
    "result": false
   },
   {
    "query": "SELECT EXISTS (SELECT column_name FROM information_schema.columns WHERE ((table_schema = $1) AND (table_name = $2)) AND (column_name = $3))",
    "queryArgs": [
     "public",
     "table_w1_12",
     "col_w1_12_w0_15"
    ],
    "result": false
   },
   {
    "query": "SELECT EXISTS (SELECT * FROM public.table_w1_12)",
    "result": true
   },
   {
    "query": "WITH descriptors AS (SELECT crdb_internal.pb_to_json('cockroach.sql.sqlbase.Descriptor', descriptor)-\u003e'table' AS d FROM system.descriptor WHERE id = $1::REGCLASS) SELECT EXISTS (SELECT mut FROM (SELECT json_array_elements(d-\u003e'mutations') AS mut FROM descriptors) WHERE (mut-\u003e'primaryKeySwap') IS NOT NULL)",
    "queryArgs": [
     "public.table_w1_12"
    ],
    "result": false
   }
  ],
  "previousStatements": [
   "ALTER TABLE public.table_w1_12 ADD COLUMN col_w1_12_w0_13 TIMESTAMP NOT NULL",
   "ALTER TABLE public.table_w1_12 ADD COLUMN col_w1_12_w0_14 VARCHAR",
   "INSERT INTO public.table_w1_12 (col5_w1_6,col5_w1_7,col5_w1_8,\"co}%3fl5 _w1_9\",col5_w1_10,col5_w1_11) VALUES (3.4028234663852886e+38:::FLOAT8,true,B'1111100001',(-87):::INT8,93:::INT8,'10:13:58.136719-02:45':::TIMETZ)",
   "ALTER TABLE public.table_w1_12 ADD COLUMN col_w1_12_w0_15 REGROLE"
  ]
 }
```

</details>

Jira issue: CRDB-40346

Epic CRDB-19168

### PR DESCRIPTION
**Pull request by rafiss**
In order to make inserts work, a few fixes were needed in various helper functions. See the individual commits.

The most extensive change in this PR is a switch from using `string` to `tree.Name` for all variables that store a column name. This addresses issues with needing to double-quote certain column name identifiers.

fixes #127263
Release note: None

### CODE REVIEW

File: pkg/sql/alter_table.go [hunk 1]
```diff
@@ -1298,7 +1298,8 @@ func labeledRowValues(cols []catalog.Column, values tree.Datums) string {
 		if i != 0 {
 			s.WriteString(`, `)
 		}
-		s.WriteString(cols[i].GetName())
+		colName := cols[i].ColName()
+		s.WriteString(colName.String())
```
Comment (annrpom) [inline pkg/sql/alter_table.go:1302]: i think this change requires a rewrite
```
=== RUN   TestTenantLogic_alter_type/regression_64101
    logic.go:2624: 
         
        /var/lib/engflow/worker/work/1/exec/bazel-out/k8-fastbuild/bin/pkg/ccl/logictestccl/tests/3node-tenant/3node-tenant_test_/3node-tenant_test.runfiles/com_github_cockroachdb_cockroach/pkg/sql/logictest/testdata/logic_test/alter_type:619: 
        expected:
        could not remove enum value "a" as it is being used by "t1_64101" in row: bob"b='a'
        got:
        pq: could not remove enum value "a" as it is being used by "t1_64101" in row: "bob""b"='a', rowid=992828355990945793
    logic.go:2205: 
         /var/lib/engflow/worker/work/1/exec/bazel-out/k8-fastbuild/bin/pkg/ccl/logictestccl/tests/3node-tenant/3node-tenant_test_/3node-tenant_test.runfiles/com_github_cockroachdb_cockroach/pkg/sql/logictest/testdata/logic_test/alter_type:622: too many errors encountered, skipping the rest of the input
[19:06:09] --- done: /var/lib/engflow/worker/work/1/exec/bazel-out/k8-fastbuild/bin/pkg/ccl/logictestccl/tests/3node-tenant/3node-tenant_test_/3node-tenant_test.runfiles/com_github_cockroachdb_cockroach/pkg/sql/logictest/testdata/logic_test/alter_type with config 3node-tenant: 161 tests, 2 failures
[19:06:10] --- total progress: 161 statements
--- total: 161 tests, 2 failures
    --- FAIL: TestTenantLogic_alter_type/regression_64101 (1.26s)
```

Comment (annrpom) [reply pkg/sql/alter_table.go:1302]: oops i pressed "add single comment" instead of "start a review" apologies

File: pkg/workload/schemachange/operation_generator.go [hunk 2]
```diff
@@ -195,6 +195,10 @@ func (og *operationGenerator) randOp(
 		} else {
 			op = opType(og.params.ops.Int())
 		}
+		if !allowDML && isDMLOpType(op) {
```
Comment (annrpom) [inline pkg/workload/schemachange/operation_generator.go:198]: oooo

**Review by annrpom — APPROVED** [review]
a new era for our workload! thank you for taking this on -- lgtm 🤜 (fist bump not a punch)

**Comment by rafiss** [comment]
tftr!

bors r+
