### PR TITLE
sql/pgwire: reject prepared queries with too many arguments

### LINKED ISSUE #17236: Cockroach crashes with [runtime error index out of range]
Just quickly dropping this here, I will supply more details later.

Crash message:

```
CockroachDB node starting at 2017-07-26 13:28:00.553866934 +0000 UTC
build:      CCL v1.0.2 @ 2017/06/15 12:58:59 (go1.8.3)
admin:      http://roach1:8080
sql:        postgresql://root@roach1:26257?sslmode=disable
logs:       /cockroach/cockroach-data/logs
store[0]:   path=/cockroach/cockroach-data
status:     restarted pre-existing node
clusterID:  c701695a-d8d3-43d9-be51-27047794b409
nodeID:     1
*
* ERROR: [n1] a panic has occurred!
*
*
* ERROR: [n1] Reported as error b121946441924ceb85beb1c99cab99d1
*
runtime error: index out of range

goroutine 85996 [running]:
runtime/debug.Stack(0x7fb631e164d0, 0xc420274000, 0x192bf80)
	/usr/local/go/src/runtime/debug/stack.go:24 +0x79
github.com/cockroachdb/cockroach/pkg/util/log.ReportPanic(0x7fb631e164d0, 0xc420274000, 0x192bf80, 0x2747ee0, 0x1)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/log/crash_reporting.go:115 +0x32b
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).Recover(0xc4206ab680, 0x7fb631e164d0, 0xc420274000)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:199 +0x99
panic(0x192bf80, 0x2747ee0)
	/usr/local/go/src/runtime/panic.go:489 +0x2cf
github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*v3Conn).serve.func1(0xc42255ee00, 0x7fb631e164d0, 0xc42b184b40)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/pgwire/v3.go:353 +0x74
panic(0x192bf80, 0x2747ee0)
	/usr/local/go/src/runtime/panic.go:489 +0x2cf
github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*v3Conn).handleBind(0xc42255ee00, 0x7fb631e166f0, 0xc42b2c9200, 0xc42255ee28, 0x176014, 0x0)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/pgwire/v3.go:741 +0x61d
github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*v3Conn).serve(0xc42255ee00, 0x7fb631e164d0, 0xc42b184b40, 0xc420e8c360, 0x5400, 0xc42043a310, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/pgwire/v3.go:451 +0x9cd
github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*Server).ServeConn(0xc42043a1c0, 0x7fb631e166f0, 0xc42b2c9180, 0x278f280, 0xc420c92d20, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/pgwire/server.go:421 +0x926
github.com/cockroachdb/cockroach/pkg/server.(*Server).Start.func9.1(0x278f280, 0xc420c92d20)
	/go/src/github.com/cockroachdb/cockroach/pkg/server/server.go:615 +0x149
github.com/cockroachdb/cockroach/pkg/util/netutil.(*Server).ServeWith.func1(0xc4206ab680, 0x7fb631e164d0, 0xc420274000, 0xc42000e038, 0x278f280, 0xc420c92d20, 0xc4202f4510)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/netutil/net.go:142 +0xa9
created by github.com/cockroachdb/cockroach/pkg/util/netutil.(*Server).ServeWith
	/go/src/github.com/cockroachdb/cockroach/pkg/util/netutil/net.go:144 +0x267
```

```
grep -F '[config]' cockroach.log 
I170726 13:27:54.020674 1 util/log/clog.go:1011  [config] file created at: 2017/07/26 13:27:54
I170726 13:27:54.020674 1 util/log/clog.go:1011  [config] running on machine: roach1
I170726 13:27:54.020674 1 util/log/clog.go:1011  [config] binary: CockroachDB CCL v1.0.2 (linux amd64, built 2017/06/15 12:58:59, go1.8.3)
I170726 13:27:54.020674 1 util/log/clog.go:1011  [config] arguments: [/cockroach/cockroach start --insecure]
```

Ignore the 1.0.2 I just upgraded and tested it again, still the same problem. I will provide  details about the query executed soon. All I know currently is that it is related to the number of parameters, as if I reduce them to a smaller amount everything works fine with the same queries.

As said deeper details are provided later.

### PR DESCRIPTION
**Pull request by jordanlewis**
The Postgres wire protocol imposes a hard cap of 65535 on the number of
arguments allowed in a prepared statement.

Under certain circumstances, we were erroneously permitting
wire-protocol prepares of queries with more than that number of
arguments, which led to server crashes when trying to execute them.

Now, we notice when a prepared query has too many arguments and return
a corresponding error during the prepare phase.

Closes #17236.

### CODE REVIEW

**Comment by mjibson** [comment]
:lgtm:

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/17380#-:-KqWZ6M_Cy4vmgfZsfaI:bnfp4nl)*

**Review by knz — APPROVED** [review]

File: pkg/sql/pgwire/v3.go [hunk 1]
```diff
@@ -517,6 +517,13 @@ func (c *v3Conn) handleSimpleQuery(buf *readBuffer) error {
 	return c.finishExecute(results, nil, true, 0)
 }
 
+// maxPreparedStatementArgs is the maximum number of arguments a prepared
+// statement can have when prepared via the Postgres wire protocol. This is not
+// documented by Postgres, but is a consequence of the fact that a 16-bit
+// integer in the wire format is used to indicate the number of values to bind
+// during prepared statement execution.
+const maxPreparedStatementArgs int = (1 << 16) - 1
```
Comment (tamird) [inline pkg/sql/pgwire/v3.go]: math.MaxUint16?

File: pkg/sql/pgwire/v3.go [hunk 2]
```diff
@@ -567,6 +574,9 @@ func (c *v3Conn) handleParse(buf *readBuffer) error {
 	}
 	// Convert the inferred SQL types back to an array of pgwire Oids.
 	inTypes := make([]oid.Oid, 0, len(stmt.SQLTypes))
+	if len(stmt.SQLTypes) > maxPreparedStatementArgs {
+		return c.sendError(pgerror.NewError(pgerror.CodeProtocolViolationError, "more than 65535 arguments to prepared statement"))
```
Comment (tamird) [inline pkg/sql/pgwire/v3.go]: should the number be interpolated in, here?

**Comment by jordanlewis** [comment]
TFTRs

---

Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[pkg/sql/pgwire/v3.go, line 525 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/17380#-KqVzuH7umsX5ztTmOea-r1-525:-KqY0D5Wv2x36hlXAQFh:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/7669c086ef21b09ebe11014c8cecc6ff035a3bfe/pkg/sql/pgwire/v3.go#L525)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

math.MaxUint16?
</blockquote></details>

Done.

---

*[pkg/sql/pgwire/v3.go, line 578 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/17380#-KqVzuH7umsX5ztTmOea-r1-578:-KqY-fQoaPXIo2tDsrjr:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/7669c086ef21b09ebe11014c8cecc6ff035a3bfe/pkg/sql/pgwire/v3.go#L578)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

should the number be interpolated in, here?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/17380#-:-KqY0Dzw9vPI2uKZl91G:b-814g6a)*

**Comment by tamird** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

*[pkg/sql/pgwire/v3.go, line 525 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/17380#-KqVzuH7umsX5ztTmOea-r1-525:-KqYJO5aPNRIpj02ASmU:b-k4dtr1) ([raw file](https://github.com/cockroachdb/cockroach/blob/7669c086ef21b09ebe11014c8cecc6ff035a3bfe/pkg/sql/pgwire/v3.go#L525)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

why give the constant the type `int`, btw?

---

*[pkg/sql/pgwire/v3.go, line 578 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/17380#-KqVzuH7umsX5ztTmOea-r1-578:-KqYJKlXClTs6O62TrjG:bvpjjtu) ([raw file](https://github.com/cockroachdb/cockroach/blob/7669c086ef21b09ebe11014c8cecc6ff035a3bfe/pkg/sql/pgwire/v3.go#L578)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

eh, sorry i meant the 65535

---

*[pkg/sql/pgwire/v3.go, line 39 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/17380#-KqYJEInIpIilmS8TnI6:-KqYJEInIpIilmS8TnI7:b-hnw32e) ([raw file](https://github.com/cockroachdb/cockroach/blob/0f3ff21b2cfe3e25bf97ca46af99d5646db47011/pkg/sql/pgwire/v3.go#L39)):*
> ```Go
> 	"github.com/cockroachdb/cockroach/pkg/util/timeutil"
> 	"github.com/cockroachdb/cockroach/pkg/util/tracing"
> 	"math"
> ```

guh this grouping

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/17380)*
