### PR TITLE
sql: add a view dep on sequence string arguments

### LINKED ISSUE #24556: sql: views do not track string-based dependencies properly
```sql
CREATE SEQUENCE s;
CREATE VIEW v AS SELECT nextval('s');
ALTER SEQUENCE s RENAME TO u;
SELECT * FROM v;
```

Fails with:

```
pq: nextval(): relation "s" does not exist
```

This is because CockroachDB fails to peek into strings that designate object names.

Other possible failing cases: `'tablename'::regclass` and related constructs.

The reason why pg does not suffer from this is that object name strings are converted to OIDs internally, and those OIDs don't change across renames.

cc @jordanlewis

### PR DESCRIPTION
**Pull request by RichardJCai**
Add a dependency on sequences that are used via string argument when creating a view.

Also fixed minor bug where column dependencies were not being added when a sequence is referred to in a currval call.

Fixes (part of) #24556 and #50033

Release note (sql change): Sequences passed as a string argument into views
are now tracked as a dependency. Example: CREATE VIEW v AS SELECT nextval('s')
will now add a dependency on sequence s.

### CODE REVIEW

File: pkg/sql/opt/optbuilder/scalar.go [hunk 1]
```diff
@@ -500,6 +501,21 @@ func (b *Builder) buildFunction(
...
 
+	// Add a dependency on sequences that are used as a string argument.
+	if b.trackViewDeps {
+		seq, found, err := sqlbase.GetSequenceFromFunc(f)
+		if err != nil {
+			panic(err)
+		}
+		if found {
+			tn := tree.MakeUnqualifiedTableName(tree.Name(seq))
+			ds, _ := b.resolveDataSource(&tn, privilege.SELECT)
```
Comment (rohany) [inline pkg/sql/opt/optbuilder/scalar.go:512]: What if resolve datasource returns an error? I think you only want to ignore it if it is a "UnknownDescriptor" error (or something like that)

File: pkg/sql/sqlbase/sequence.go [hunk 2]
```diff
@@ -0,0 +1,75 @@
...
+	"github.com/cockroachdb/cockroach/pkg/sql/sem/tree"
+	"github.com/cockroachdb/cockroach/pkg/sql/sessiondata"
+)
+
+// sequenceFuncs is a set of sequence functions that take in a sequence name
+// (string) as an argument and can be used in a scalar expression.
+// TODO(richardjcai): When implicit casting is supported, these builtins
+// should take RegClass as the arg type for the sequence name instead of
+// string, we will add a dependency on all RegClass types used in a view.
+var sequenceFuncs = map[string]struct{}{
```
Comment (rohany) [inline pkg/sql/sqlbase/sequence.go:23]: Is it not possible to make this an attribute on the overload/`FunctionProperties`?

File: pkg/sql/sqlbase/sequence.go [hunk 3]
```diff
@@ -0,0 +1,75 @@
...
+	"nextval": {},
+	"currval": {},
+}
+
+// GetSequenceFromFunc extracts a sequence name from a FuncExpr if the function
+// takes a sequence name as an arg. Returns the name of the sequence and a bool
+// representing whether a sequence name was found or not.
+func GetSequenceFromFunc(funcExpr *tree.FuncExpr) (string, bool, error) {
+	searchPath := sessiondata.SearchPath{}
```
Comment (rohany) [inline pkg/sql/sqlbase/sequence.go:32]: should we be using the search path of the caller here?

File: pkg/sql/sqlbase/sequence.go [hunk 4]
```diff
@@ -0,0 +1,75 @@
...
+
+	def, err := funcExpr.Func.Resolve(searchPath)
+	if err != nil {
+		return "", false, err
+	}
+
+	if _, ok := sequenceFuncs[def.Name]; ok {
+		arg := funcExpr.Exprs[0]
```
Comment (rohany) [inline pkg/sql/sqlbase/sequence.go:40]: How do we know to only check index 0?

File: pkg/sql/sqlbase/sequence.go [hunk 5]
```diff
@@ -0,0 +1,75 @@
...
+		switch a := arg.(type) {
+		case *tree.DString:
```
Comment (rohany) [inline pkg/sql/sqlbase/sequence.go:42]: Do we need to handle the `Reg*` datums here?

File: pkg/sql/sqlbase/sequence.go [hunk 6]
```diff
@@ -0,0 +1,75 @@
...
+// should take RegClass as the arg type for the sequence name instead of
+// string, we will add a dependency on all RegClass types used in a view.
+var sequenceFuncs = map[string]struct{}{
+	"nextval": {},
+	"currval": {},
+}
+
+// GetSequenceFromFunc extracts a sequence name from a FuncExpr if the function
+// takes a sequence name as an arg. Returns the name of the sequence and a bool
+// representing whether a sequence name was found or not.
```
Comment (rohany) [inline pkg/sql/sqlbase/sequence.go:30]: Does this need to return a bool as well? Returning a `*string` or just a `string` and checking if `!= ""` seems reasonable.

**Review by rohany — CHANGES_REQUESTED** [review]

**Review by RaduBerinde — COMMENTED** [review]
So.. if `nextval('s')` is inside a CASE and it wouldn't necessarily get executed, do we want to error out if the source doesn't exist? E.g. this works in postgres:

```
radu=> CREATE VIEW v AS SELECT CASE WHEN EXISTS (SELECT * FROM t WHERE x=1) THEN nextval('s') ELSE 0 END;
CREATE VIEW
radu=> SELECT * FROM v;
ERROR:  "s" is not a sequence
radu=> DELETE FROM t WHERE true;
DELETE 1
radu=> SELECT * FROM v;
 case 
------
    0
(1 row)
```

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/50103#-:-M9ZBoe71Ftt2vRdQA-n:bki1302)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @RichardJCai)

File: pkg/sql/sqlbase/sequence.go (hunk 5 above)
Comment (RichardJCai) [reply pkg/sql/sqlbase/sequence.go:42]: I don't think so, we can only pass in String args into the functions at the moment.

File: pkg/sql/sqlbase/sequence.go (hunk 6 above)
Comment (RichardJCai) [reply pkg/sql/sqlbase/sequence.go:30]: Yeah I can change it to *string, I thought returning the bool might be more clear. For some reason I don't really like the empty string check

File: pkg/sql/sqlbase/sequence.go (hunk 4 above)
Comment (RichardJCai) [reply pkg/sql/sqlbase/sequence.go:40]: I stole this from the current checking logic, right now the only functions where we have to track sequence string deps have the sequence name as the first argument.

File: pkg/sql/sqlbase/sequence.go (hunk 3 above)
Comment (RichardJCai) [reply pkg/sql/sqlbase/sequence.go:32]: > So.. if `nextval('s')` is inside a CASE and it wouldn't necessarily get executed, do we want to error out if the source doesn't exist? E.g. this works in postgres:
> 
> ```
> radu=> CREATE VIEW v AS SELECT CASE WHEN EXISTS (SELECT * FROM t WHERE x=1) THEN nextval('s') ELSE 0 END;
> CREATE VIEW
> radu=> SELECT * FROM v;
> ERROR:  "s" is not a sequence
> radu=> DELETE FROM t WHERE true;
> DELETE 1
> radu=> SELECT * FROM v;
>  case 
> ------
>     0
> (1 row)
> ```
> 
> > _[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/50103#-:-M9ZBoe71Ftt2vRdQA-n:bki1302)_ status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @RichardJCai)

So would it be correct if we didn't error out if the source didn't exist?

The logic I have here should match PG's behaviour right now.

```
root@127.0.0.1:56309/movr> create table t(x int);
CREATE TABLE

Time: 2.623ms

root@127.0.0.1:56309/movr> CREATE VIEW v AS SELECT CASE WHEN EXISTS (SELECT x FROM t WHERE x=1) THEN nextval('s') ELSE 0 END;
CREATE VIEW

Time: 24.966ms

root@127.0.0.1:56309/movr> insert into t values (1);
INSERT 1

Time: 1.017ms

root@127.0.0.1:56309/movr> select * from v;
ERROR: nextval(): relation "s" does not exist
SQLSTATE: 42P01
root@127.0.0.1:56309/movr>
```

**Comment by RichardJCai** [comment]
> So.. if `nextval('s')` is inside a CASE and it wouldn't necessarily get executed, do we want to error out if the source doesn't exist? E.g. this works in postgres:
> 
> ```
> radu=> CREATE VIEW v AS SELECT CASE WHEN EXISTS (SELECT * FROM t WHERE x=1) THEN nextval('s') ELSE 0 END;
> CREATE VIEW
> radu=> SELECT * FROM v;
> ERROR:  "s" is not a sequence
> radu=> DELETE FROM t WHERE true;
> DELETE 1
> radu=> SELECT * FROM v;
>  case 
> ------
>     0
> (1 row)
> ```
> 
> > _[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/50103#-:-M9ZBoe71Ftt2vRdQA-n:bki1302)_ status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @RichardJCai)

So would it be correct if we didn't error out if the source didn't exist?

The logic I have here should match PG's behaviour right now.

```
root@127.0.0.1:56309/movr> create table t(x int);
CREATE TABLE

Time: 2.623ms

root@127.0.0.1:56309/movr> CREATE VIEW v AS SELECT CASE WHEN EXISTS (SELECT x FROM t WHERE x=1) THEN nextval('s') ELSE 0 END;
CREATE VIEW

Time: 24.966ms

root@127.0.0.1:56309/movr> insert into t values (1);
INSERT 1

Time: 1.017ms

root@127.0.0.1:56309/movr> select * from v;
ERROR: nextval(): relation "s" does not exist
SQLSTATE: 42P01
root@127.0.0.1:56309/movr>
```

**Review by RaduBerinde — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/50103)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @RichardJCai and @rohany)

___
*[pkg/sql/opt/optbuilder/scalar.go, line 512 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/50103#-M9ZA4cQqh-1eYF4q1kJ-r1-512:-M9ZLgtH6t6bgkDJ33sV:b-kg4i2d) ([raw file](https://github.com/cockroachdb/cockroach/blob/89602d5234828acbed2360be4123b52c5b03709a/pkg/sql/opt/optbuilder/scalar.go#L512)):*
<details><summary><i>Previously, rohany (Rohan Yadav) wrote…</i></summary><blockquote>

What if resolve datasource returns an error? I think you only want to ignore it if it is a "UnknownDescriptor" error (or something like that)
</blockquote></details>

The second arg is a name, not an error. Errors are returned via panics that are caught at the optbuilder entrpoint. 

That said, I agree that we probably want to tolerate "UnknownDescriptor" here.. Postgres definitely allows you to create a view with a nextval call for a bogus sequence.

**Comment by RichardJCai** [comment]
> So.. if `nextval('s')` is inside a CASE and it wouldn't necessarily get executed, do we want to error out if the source doesn't exist? E.g. this works in postgres:
> 
> ```
> radu=> CREATE VIEW v AS SELECT CASE WHEN EXISTS (SELECT * FROM t WHERE x=1) THEN nextval('s') ELSE 0 END;
> CREATE VIEW
> radu=> SELECT * FROM v;
> ERROR:  "s" is not a sequence
> radu=> DELETE FROM t WHERE true;
> DELETE 1
> radu=> SELECT * FROM v;
>  case 
> ------
>     0
> (1 row)
> ```
> 
> > _[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/50103#-:-M9ZBoe71Ftt2vRdQA-n:bki1302)_ status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @RichardJCai)

Wait what version of PG are you using @RaduBerinde , I'm using PG 12 and this does raise an error. 

```
postgres=# create table t(x int);
CREATE TABLE
postgres=# CREATE VIEW v AS SELECT CASE WHEN EXISTS (SELECT * FROM t WHERE x=1) THEN nextval('s') ELSE 0 END;
ERROR:  relation "s" does not exist
LINE 1: ...N EXISTS (SELECT * FROM t WHERE x=1) THEN nextval('s') ELSE ...
                                                             ^
postgres=# 
```

Or maybe your error comes from s existing but being a table instead of a sequence?
`ERROR:  "s" is not a sequence`

**Review by RaduBerinde — COMMENTED** [review]
Oh, wow, good catch, yeah it looks like I had a table `'s'` that I forgot about. I retract my comments then, erroring out seems like the correct thing to do.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/50103#-:-M9Zm-9mEHk8Z69hmR8v:b6sjhqo)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @RichardJCai and @rohany)

File: pkg/sql/opt/optbuilder/scalar.go (hunk 1 above)
Comment (RichardJCai) [reply pkg/sql/opt/optbuilder/scalar.go:512]: This should be okay because resolveDataSource will panic if theres an error, as Radu mentioned the 2nd return value is the datasource name and not error.

File: pkg/sql/sqlbase/sequence.go (hunk 2 above)
Comment (RichardJCai) [reply pkg/sql/sqlbase/sequence.go:23]: I think I found a decent way to do this.

File: pkg/sql/sqlbase/sequence.go (hunk 3 above)
Comment (RichardJCai) [reply pkg/sql/sqlbase/sequence.go:32]: For resolving in functions, the searchPath isn't actually used.

File: pkg/sql/sqlbase/sequence.go (hunk 4 above)
Comment (RichardJCai) [reply pkg/sql/sqlbase/sequence.go:40]: Updated to have a more robust check.

File: pkg/sql/sem/builtins/builtins.go [hunk 7]
```diff
@@ -69,6 +69,9 @@ var (
 		"input value must be <= %d (maximum Unicode code point)", utf8.MaxRune)
 	errStringTooLarge = pgerror.Newf(pgcode.ProgramLimitExceeded,
 		"requested length too large, exceeds %s", humanizeutil.IBytes(maxAllocatedStringSize))
+	// SequenceNameArg represents the name of sequence (string) arguments in
```
Comment (rohany) [inline pkg/sql/sem/builtins/builtins.go:72]: How about `SequenceNameArg represents the name of an argument to a builtin that is a sequence name represented as a string`?

File: pkg/sql/sem/tree/function_definition.go [hunk 8]
```diff
@@ -96,6 +96,13 @@ type FunctionProperties struct {
 	// the Postgres ones at test time.
 	// This should be used with caution.
 	IgnoreVolatilityCheck bool
+
+	// TrackSequenceDeps is true if the builtin function takes in a sequence
+	// name (string) and can be used in a scalar expression.
+	// TODO(richardjcai): When implicit casting is supported, these builtins
+	// should take RegClass as the arg type for the sequence name instead of
+	// string, we will add a dependency on all RegClass types used in a view.
+	TrackSequenceDeps bool
```
Comment (rohany) [inline pkg/sql/sem/tree/function_definition.go:105]: What about `HasSequenceArguments`?

File: pkg/util/sequence/sequence.go [hunk 9]
```diff
@@ -0,0 +1,96 @@
...
+	"github.com/cockroachdb/cockroach/pkg/sql/sem/builtins"
+	"github.com/cockroachdb/cockroach/pkg/sql/sem/tree"
+	"github.com/cockroachdb/cockroach/pkg/sql/sessiondata"
+)
+
+// GetSequenceFromFunc extracts a sequence name from a FuncExpr if the function
+// takes a sequence name as an arg. Returns the name of the sequence and a bool
+// representing whether a sequence name was found or not.
+func GetSequenceFromFunc(funcExpr *tree.FuncExpr) (*string, error) {
+	searchPath := sessiondata.SearchPath{}
```
Comment (rohany) [inline pkg/util/sequence/sequence.go:25]: I see, can you add a comment here about why we don't need the search path from the parent context?

File: pkg/util/sequence/sequence.go [hunk 10]
```diff
@@ -0,0 +1,96 @@
...
+	if err != nil {
+		return nil, err
+	}
+
+	fnProps, overloads := builtins.GetBuiltinProperties(def.Name)
+	if fnProps != nil && fnProps.TrackSequenceDeps {
+		found := false
+		for _, overload := range overloads {
+			// Find the overload that matches funcExpr.
+			if funcExpr.ResolvedOverload().Types.Match(overload.Types.Types()) {
```
Comment (rohany) [inline pkg/util/sequence/sequence.go:37]: Is there a chance that there might be ambiguity in which overload we pick?

Comment (RichardJCai) [reply pkg/util/sequence/sequence.go:37]: It shouldn't be possible, it compares the types of the arguments, it doesn't make sense to have two overloads with the exact same arguments.

Comment (rohany) [reply pkg/util/sequence/sequence.go:37]: Good point

**Review by rohany — APPROVED** [review]

**Comment by RichardJCai** [comment]
@RaduBerinde Do you want to take another look before I merge this?

**Review by RaduBerinde — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/50103#-:-M9smj7z7yzvlZ8Ahr-0:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @RaduBerinde, @RichardJCai, and @rohany)

**Comment by RichardJCai** [comment]
Thanks for the reviews!

**Comment by RichardJCai** [comment]
I think TestDistinct is flakey, although I noticed one of my comments is out of date so I'm gonna update that and retry.
