### PR TITLE
dev: have `doctor` advise to set a particular `tmpdir`

### LINKED ISSUE #72918: bazel/dev: add fix/warning for long TMPDIR's, especially on problem OS's (Mac/BSD)
This was first spotted in #72027. The TMPDIR that Bazel gives tests is in the sandbox and is therefore quite long, which can introduce problems especially on macOS or other BSD-derived OS's. Tests can therefore fail in surprising ways. A couple ideas:

1. In general you can work around this problem by setting `--test_tmpdir` to something appropriate. So on macOS or BSD we could check in `dev doctor` whether you have `--test_tmpdir` set in your `~/.bazelrc`/`.bazelrc.user`. This is problematic though if you have a habit of setting `--test_tmpdir` on the command-line, since the two flags will conflict.
2. We can patch e.g. `rules_go` to check whether you're running on macOS or BSD and whether `TMPDIR` is too long and override `TMPDIR` accordingly. We actually [already set `TMPDIR`](https://github.com/cockroachdb/rules_go/commit/4a7bcc9b9051eb6a12bcb03a9bf38138c4bbc2ea) in our fork of `rules_go`, so the logic would fit right in there.

I think (2) makes more sense, but the blanket override could be surprising.

Epic CRDB-8036

### LINKED ISSUE #82413: bazel: path to CRDB log is incorrect after a failed dev test
If a test fails on my mac, I can't seem to cd to the directory that the error msg suggests would have my CRDB log: 
```
 test_log_scope.go:76: test logs captured to: /private/var/tmp/_bazel_michaelbutler/13ba282fa2b19539d0c969c1113bb37c/sandbox/darwin-sandbox/15/execroot/com_github_cockroachdb_cockroach/_tmp/a340ebbb90405137386a0ed860023d6b/logTestRandomParquetExports1960928243
```

Workaround: If I pass the `--show-logs` dev arg, the crdb log prints to stdout without a problem. 

Jira issue: CRDB-16363

Epic CRDB-15061

### PR DESCRIPTION
**Pull request by rickystewart**
Bazel's default behavior of rooting the `tmpdir` to an "in-sandbox"
directory has been a point of confusion for CRL developers. The sandbox
directory does not exist after the test is run (unless `--sandbox_debug`
is provided), which is sometimes confusing for folks who expect their
test's temp files to be present where the logs suggest they should be
(see #82413). Furthermore, the long `tmpdir` used in these cases breaks
tests that create Unix sockets on OS's where Unix sockets have a maximum
path length.

Avoid these problems by having `doctor` just tell you to manually set a
`test_tmpdir`. We add `/tmp` to `gitignore` in case people want to root
it at the `tmp` directory in their checkout.

Closes #72918.
Closes #82413.

Release note: None

### CODE REVIEW

File: pkg/cmd/dev/doctor.go [hunk 1]
```diff
@@ -359,3 +368,19 @@ func (d *dev) checkPresenceInBazelRc(expectedBazelRcLine string) (string, error)
 	}
 	return errString, nil
 }
+
+// checkSubstringPresenceInBazelRcUser checks whether the .bazelrc.user file
```
Comment (rail) [inline pkg/cmd/dev/doctor.go:372]: A nit: the comment function name doesn't match the actual function name.

**Review by rail — APPROVED** [review]

**Comment by rickystewart** [comment]
TFTR! 

bors r=rail
