### PR TITLE
engine: Build with non-executable stacks

### LINKED ISSUE #37885: security: Build with non-executable stacks
Cockroach currently fails on SELinux (with default configurations) because it attempts to mmap a region of memory with PROT_WRITE and PROT_EXEC. Preliminary investigation shows that this is memory used for the stack.

According to [this page](https://www.airs.com/blog/archives/518) (from 2011, don't know if it's still accurate), the executable bit for the stack is controlled by a link-time option. Somewhere in our build toolchain, that's not getting set correctly.

### PR DESCRIPTION
**Pull request by bdarnell**
Three lines of inscrutable magic (and plenty of comments) to avoid
tripping a complex series of heuristics resulting in a security risk.

Fixes #37885

Release note (security improvement): Stack memory used by CockroachDB
is now marked as non-executable, improving security and compatibility
with SELinux.

### CODE REVIEW

File: pkg/cmd/roachtest/build_info.go [hunk 1]
```diff
@@ -47,3 +48,50 @@ func runBuildInfo(ctx context.Context, t *test, c *cluster) {
 		}
 	}
 }
+
+// runBuildAnalyze performs static analysis on the built binary to
+// ensure it's built as expected.
+func runBuildAnalyze(ctx context.Context, t *test, c *cluster) {
+
```
Comment (petermattis) [inline pkg/cmd/roachtest/build_info.go]: Spurious blank line.

File: pkg/storage/engine/slice.s [hunk 2]
```diff
@@ -1 +1,16 @@
-// Empty assembly file to allow go:linkname to work.
+// This empty assembly file has non-obvious side effects.
+//
+// 1. The go:linkname directive is only enabled for packages that
+// contain assembly files; this is the reason this file exists.
+//
+// 2. Completely empty assembly files cause GCC to mark the binary
+// as requiring an executable stack. This is a security risk. The
```
Comment (petermattis) [inline pkg/storage/engine/slice.s]: Why?!?

**Review by petermattis — APPROVED** [review]
The use of go:linkname can go away when we upgrade to go 1.12. The associated perf hack is no longer needed as the problem was fixed upstream.

File: pkg/storage/engine/slice.s (hunk 2 above)
Comment (bdarnell) [reply pkg/storage/engine/slice.s]: I'll rephrase this: it's nothing special about empty files, it's that any assembly file that doesn't have this marker is assumed to contain code that might rely on an executable stack. Empty files are a degenerate case that could be understood to not need executable stack, but that's not something that anyone really considered since there's not normally a reason for an empty file to exist.

Comment (petermattis) [reply pkg/storage/engine/slice.s]: Ok, though I imagine empty assembly files are special in some regard since both the Go runtime and some third-party libraries we use such as `petermattis/goid` have non-empty assembly files which don't seem to cause a problem. My "Why?!?" comment was more about why GCC had such a subtle security behavior.

Comment (bdarnell) [reply pkg/storage/engine/slice.s]: The `.s` files used in `goid` are only used on older go versions. But there are other `.s` files that I'm pretty sure we do use that aren't having this effect. Mysterious.

Fun fact: `pkg/sql/exec` has [its own empty assembly file](https://github.com/cockroachdb/cockroach/blob/master/pkg/sql/exec/noescape.s), which evidently does not cause the executable to get the execstack bit. There is no `import "C"` in the package, so the `.s` file isn't even getting compiled. In current versions of go, it's not required to have a magic empty assembly file, it's required to [import unsafe](https://github.com/golang/go/blob/64c134f90f0cf6d0e55fca93c433b68810d12f12/src/cmd/compile/internal/gc/noder.go#L250) to use `go:linkname`. The "empty assembly file" pattern appears to be meaningless (I looked through blame as far as I could easily go and the logic about importing unsafe has been there since at least 2016). So I'm just going to delete both of these assembly files and keep the new test.

**Review by petermattis — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/37939)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @bdarnell)

___
*[pkg/storage/engine/slice.s, line 7 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/37939#-Lg8gCaZ9Yas17sl1fHk-r1-7:-LgIRssrEro9LshkgGFD:bw8xjx0) ([raw file](https://github.com/cockroachdb/cockroach/blob/a07ce846c1e01013aae8dae333b3671933ebdbc6/pkg/storage/engine/slice.s#L7)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

The `.s` files used in `goid` are only used on older go versions. But there are other `.s` files that I'm pretty sure we do use that aren't having this effect. Mysterious.

Fun fact: `pkg/sql/exec` has [its own empty assembly file](https://github.com/cockroachdb/cockroach/blob/master/pkg/sql/exec/noescape.s), which evidently does not cause the executable to get the execstack bit. There is no `import "C"` in the package, so the `.s` file isn't even getting compiled. In current versions of go, it's not required to have a magic empty assembly file, it's required to [import unsafe](https://github.com/golang/go/blob/64c134f90f0cf6d0e55fca93c433b68810d12f12/src/cmd/compile/internal/gc/noder.go#L250) to use `go:linkname`. The "empty assembly file" pattern appears to be meaningless (I looked through blame as far as I could easily go and the logic about importing unsafe has been there since at least 2016). So I'm just going to delete both of these assembly files and keep the new test.
</blockquote></details>

Huh, I could have sworn the empty `.s` file did something. Well, I trust your research and everything compiles and links, this is certainly the best approach.

**Comment by bdarnell** [comment]
Ah, the empty assembly files are needed not to enable `go:linkname` per se, but to allow you to declare a function with no body. And this changed in go 1.12 (which I have locally), so that's why I though they weren't needed. See https://github.com/golang/go/issues/23311

Putting the empty files back for now.

**Comment by bdarnell** [comment]
Hmm, the two empty assembly files are getting built differently. The one in storage/engine gets run through the preprocessor and the three-line magic works (without it, the binary gets an executable stack). The one in sql/exec does not go through the preprocessor so the three-line magic fails to compile (I didn't try the one-line form without the ifdef). But without the magic line, the binary still doesn't get an executable stack. 

I'll stop shaving this yak now (assuming CI finally passes), and leave it with a comment-only assembly file in sql/exec and one with the magic lines in storage/engine. Both of them should be removed when we require go 1.12.

**Review by petermattis — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/37939)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @bdarnell)

___
*[pkg/storage/engine/slice.s, line 1 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/37939#-LgT8cUfCLCSmLFxkYc7:-LgT8cUfCLCSmLFxkYc8:b3v57gf) ([raw file](https://github.com/cockroachdb/cockroach/blob/a7442c136b885bf26e2138b143390b924353f3b8/pkg/storage/engine/slice.s#L1)):*
> ```
> // This empty assembly file has non-obvious side effects.
> ```

No copyright header?

**Comment by bdarnell** [comment]
> No copyright header?

Whoops :)

**Review by petermattis — COMMENTED** [review]
> > No copyright header?
> 
> Whoops :)

Heh, your left hand didn't know what your right hand was doing.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/37939#-:-LgTEl01B6hNN_xeceRm:b-coip45)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @bdarnell)

**Comment by bdarnell** [comment]
bors r=petermattis
