### PR TITLE
opt: remove outdated hint for unknown functions in views

### LINKED ISSUE #151685: sql: misleading hint when referencing a non-existent function in a view
The hint below is misleading because referencing UDFs in views is now supported.

```sql
CREATE VIEW v0 AS SELECT foo();
-- ERROR: unknown function: foo()
-- SQLSTATE: 42883
-- HINT: There is probably a typo in function name. Or the intention was to use a user-defined function in the view query, which is currently not supported.
```

Jira issue: CRDB-53417

### PR DESCRIPTION
**Pull request by anuj-agrawal-0705**
Fixes #151685

Release note: None

### CODE REVIEW

File: pkg/sql/opt/optbuilder/create_view.go [hunk 1]
```diff
@@ -68,8 +68,7 @@ func (b *Builder) buildCreateView(cv *tree.CreateView, inScope *scope) (outScope
 				panic(
 					errors.WithHint(
```
Comment (mgartner) [inline pkg/sql/opt/optbuilder/create_view.go]: Let's remove the hint altogether.

**Comment by mgartner** [comment]
Thanks for contributing!

**Comment by mohit-nagaraj** [comment]
@anuj-agrawal-0705 can i work on your pr to deliver a fix to this issue

File: pkg/sql/opt/optbuilder/create_view.go (hunk 1 above)
Comment (mgartner) [reply pkg/sql/opt/optbuilder/create_view.go]: I went ahead and updated the PR.

**Review by mgartner — APPROVED** [review]
LGTM. Thanks for contributing! I'll merge once CI passes.

**Comment by anuj-agrawal-0705** [comment]
@mgartner , Thanks for updating the PR! I missed your earlier PR comment.
