### PR TITLE
opt: use expr and input fds to remap index join columns

### LINKED ISSUE #81649: sql: internal error: no output column equivalent
roachtest.sqlsmith/setup=rand-tables/setting=no-mutations [failed](https://teamcity.cockroachdb.com/viewLog.html?buildId=5238654&tab=buildLog) with [artifacts](https://teamcity.cockroachdb.com/viewLog.html?buildId=5238654&tab=artifacts#/sqlsmith/setup=rand-tables/setting=no-mutations) on release-22.1 @ [f143fd81c898f540a0a0db467b5f18beb32644cf](https://github.com/cockroachdb/cockroach/commits/f143fd81c898f540a0a0db467b5f18beb32644cf):

```
The test failed on branch=release-22.1, cloud=gce:
test artifacts and logs in: /artifacts/sqlsmith/setup=rand-tables/setting=no-mutations/run_1
	sqlsmith.go:265,sqlsmith.go:304,test_runner.go:875: error: pq: internal error: no output column equivalent to 5
		stmt:
		SELECT
			tab_30745.col3_11 AS col_65710,
			NULL AS col_65711,
			NULL AS col_65712,
			e'\x13L|9\x03<\f':::STRING AS col_65713,
			tab_30745.col3_9 AS col_65714,
			true AS col_65715,
			parse_time(('28.81.114.123/16':::INET::INET || tab_30745.col3_1::STRING)::STRING::STRING)::TIME AS col_65716,
			tab_30745.col3_1 AS col_65717,
			tab_30745.col3_10 AS col_65718
		FROM
			defaultdb.public.table3@table3_col3_12_col3_9_expr_col3_0_expr1_col3_13_expr2_col3_10_col3_14_col3_16_col3_4_key
				AS tab_30745
		ORDER BY
			tab_30745.col3_1 ASC, tab_30745.col3_2 ASC, tab_30745.col3_12 ASC
		LIMIT
			2:::INT8;
```
<details><summary>Help</summary>
<p>

See: [roachtest README](https://github.com/cockroachdb/cockroach/blob/master/pkg/cmd/roachtest/README.md)

See: [How To Investigate \(internal\)](https://cockroachlabs.atlassian.net/l/c/SSSBr8c7)

</p>
</details>
<details><summary>Same failure on other branches</summary>
<p>

- #81632 roachtest: sqlsmith/setup=rand-tables/setting=no-mutations failed [C-test-failure O-roachtest O-robot T-sql-queries branch-release-21.2 release-blocker]
- #81356 roachtest: sqlsmith/setup=rand-tables/setting=no-mutations failed [C-test-failure O-roachtest O-robot T-sql-queries branch-master]
</p>
</details>
/cc @cockroachdb/sql-queries
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*sqlsmith/setup=rand-tables/setting=no-mutations.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)
</sub>

Jira issue: CRDB-16009

### PR DESCRIPTION
**Pull request by rharding6373**
Before this change index joins would use their own FDs to remap input to
output columns if there was a required ordering. This could miss some
cases where the index joins' FDs were generated from another expression
in the memo group and did not include FDs from its own input, such as
equivalent columns only found the index joins' input. This change
modifies the FDs used for remapping columns to include both the index
join and input FDs.

Fixes: #81649

Release note (bug fix): Index joins now consider functional dependencies
from their input when determining equivalent columns instead of
returning an internal error.

### CODE REVIEW

File: pkg/sql/opt/xform/testdata/rules/join [hunk 1]
```diff
@@ -12378,3 +12378,37 @@ project
...
       └── filters
            └── col3:4 = col0:8 [outer=(4,8), constraints=(/4: (/NULL - ]; /8: (/NULL - ]), fd=(4)==(8), (8)==(4)]
+
+# Regression for #81649
+exec-ddl
+CREATE TABLE t81649 (
+  col0 STRING NULL,
+  col1 DECIMAL NOT NULL,
+  col2 STRING NULL AS (lower(col0)) STORED,
+  col3 DECIMAL NOT NULL AS (col1 + 0:::DECIMAL) VIRTUAL,
```
Comment (mgartner) [inline pkg/sql/opt/xform/testdata/rules/join:12388]: If you change the `VIRTUAL` to `STORED`, the problem reproduces on 21.2, so this is probably something we want to backport.

File: pkg/sql/opt/xform/testdata/rules/join [hunk 2]
```diff
@@ -12378,3 +12378,37 @@ project
...
+----
+
+opt
+SELECT col2 FROM t81649@t81649_col3_col1_key ORDER BY col0 ASC, col3 ASC LIMIT 2;
+----
+index-join t81649
+ ├── columns: col2:3  [hidden: col0:1 col3:4!null]
+ ├── cardinality: [0 - 2]
+ ├── key: (4)
+ ├── fd: (1)-->(3), (4)-->(1,3)
```
Comment (mgartner) [inline pkg/sql/opt/xform/testdata/rules/join:12400]: So is the issue that this fd does not contain `(2)==(4), (4)==(2)`? I suppose it doesn't contain this because column `2` is not an output column.

File: pkg/sql/opt/ordering/lookup_join.go [hunk 3]
```diff
@@ -82,7 +82,8 @@ func indexJoinBuildProvided(expr memo.RelExpr, required *props.OrderingChoice) o
 	// using column equivalencies.
 	indexJoin := expr.(*memo.IndexJoinExpr)
 	rel := indexJoin.Relational()
-	return remapProvided(indexJoin.Input.ProvidedPhysical().Ordering, &rel.FuncDeps, rel.OutputCols)
+	input := indexJoin.Input
+	return remapProvided(input.ProvidedPhysical().Ordering, &input.Relational().FuncDeps, rel.OutputCols)
```
Comment (mgartner) [inline pkg/sql/opt/ordering/lookup_join.go:86]: Are there downsides to using the input's FDs? It seems like we'd potentially break other cases that rely on the FD containing columns that are fetched by the index join.

**Review by rharding6373 — COMMENTED** [review]
TFTR! Needs more work.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/81844#-:-N30EVHB8Bius33jYiD9:b-s6b6yf)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @mgartner and @msirek)

___
*[`pkg/sql/opt/ordering/lookup_join.go` line 86 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/81844#-N2wHC1vnZaO-jAbxJs7-r2-86:-N2xdBeX62g3hZOKHsBh:b-nzxw4f) ([raw file](https://github.com/cockroachdb/cockroach/blob/addcfab6ca02656bf731f2e545ccdc365f7a0aec/pkg/sql/opt/ordering/lookup_join.go#L86)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

Are there downsides to using the input's FDs? It seems like we'd potentially break other cases that rely on the FD containing columns that are fetched by the index join.
</blockquote></details>

If there are we have no test coverage... I'm trying to come up with an example that fails with this change that would not have failed before, but haven't been successful thus far. It's possible that the solution is to expand the source of FDs. Needs more work and a better understanding of FDs.
___
*[`pkg/sql/opt/xform/testdata/rules/join` line 12388 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/81844#-N2wHC1vnZaO-jAbxJs8-r2-12388:-N2xL22j-bhDEbRiW0Nx:b-gdns54) ([raw file](https://github.com/cockroachdb/cockroach/blob/addcfab6ca02656bf731f2e545ccdc365f7a0aec/pkg/sql/opt/xform/testdata/rules/join#L12388)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

If you change the `VIRTUAL` to `STORED`, the problem reproduces on 21.2, so this is probably something we want to backport.
</blockquote></details>

Oh interesting, I didn't get the original query with `STORED` to repro (I think I only tried 21.2.6 though), so I thought this query may have failed in part due to top k ordering. I added backport labels for both 21.2 and 22.1.
___
*[`pkg/sql/opt/xform/testdata/rules/join` line 12400 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/81844#-N2wHC1vnZaO-jAbxJs8-r2-12400:-N2xaSD12r-_ENsSDCop:b-lukddd) ([raw file](https://github.com/cockroachdb/cockroach/blob/addcfab6ca02656bf731f2e545ccdc365f7a0aec/pkg/sql/opt/xform/testdata/rules/join#L12400)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

So is the issue that this fd does not contain `(2)==(4), (4)==(2)`? I suppose it doesn't contain this because column `2` is not an output column.
</blockquote></details>

Yes, this is the issue. They're equivalent, but since `2` is not an output column this property doesn't propagate to the index join's FDs.

**Review by rharding6373 — COMMENTED** [review]
RFAL. Thanks @msirek  for figuring out what was missing from the index join FDs!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/81844#-:-N319UWQAkX37uLOKKgd:b-8sa9xm)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @mgartner and @msirek)

___
*[`pkg/sql/opt/ordering/lookup_join.go` line 86 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/81844#-N2wHC1vnZaO-jAbxJs7-r2-86:-N317cor5Pb0ps7wLxlQ:ba5rhid) ([raw file](https://github.com/cockroachdb/cockroach/blob/addcfab6ca02656bf731f2e545ccdc365f7a0aec/pkg/sql/opt/ordering/lookup_join.go#L86)):*
<details><summary><i>Previously, rharding6373 (Rachael Harding) wrote…</i></summary><blockquote>

If there are we have no test coverage... I'm trying to come up with an example that fails with this change that would not have failed before, but haven't been successful thus far. It's possible that the solution is to expand the source of FDs. Needs more work and a better understanding of FDs.
</blockquote></details>

Thanks to @msirek's sleuthing, it turns out the real issue here is that the FDs for the index join in our particular example come from the first op in its memo group, not from generating its own FDs in the logical props builder (which uses both input FDs and table FDs from the index join, as Marcus guessed above). As a result, the FDs can be inaccurate here.

I've modified this to mimic the behavior of `buildIndexJoin` to include both the input and index join FDs. This solves the issue found by sqlsmith and shouldn't cause a potential regression.

A more long-term solution would be to clean up how we generate FDs (and other logical props) so that they're more accurate within the same memo group, but that's out of scope for this bug fix.

**Review by msirek — APPROVED** [review]
Looks good.  I had played around with adding a call to `buildIndexJoinProps` but I think it was reducing the FD set because not everything was set up properly, for example, maybe the call `rel.FuncDeps.ProjectCols(rel.OutputCols)` didn't include ORDER BY columns.  It would be great to unify the logical props building code for the different operations in the future, if possible.

:lgtm: 

> Reviewed 1 of 2 files at r1, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/81844#-:-N31E-xo2I0148UIClI2:b74tpuo)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @mgartner and @msirek)

**Review by rharding6373 — COMMENTED** [review]
TFTRs!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/81844#-:-N3vX6rb00rfTi2TNsKx:bz5mair)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @mgartner and @msirek)

___
*[`pkg/sql/opt/ordering/lookup_join.go` line 90 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/81844#-N2wHC1vnZaO-jAbxJs7-r4-90:-N3vWSJJCtwLqgS8APWs:b7nyul5) ([raw file](https://github.com/cockroachdb/cockroach/blob/f665378659afc0aeb801bd61e583cf8e6768f161/pkg/sql/opt/ordering/lookup_join.go#L90)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

It looks like this adds a set of FDs to itself, which seems like it would be a no-op. Should this instead be `rel.FuncDeps.AddFrom(&fds)`? Or maybe `fds.AddFrom(&rel.FuncDeps)` so that we don't mutate `rel.FuncDeps`?
</blockquote></details>

Oof, good catch. Fixed.

**Review by rytaft — APPROVED** [review]
:lgtm: thanks for fixing!

> Reviewed 1 of 2 files at r1, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/81844#-:-N3xGQv81_0wLXeHOIct:b-1nny3v)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @mgartner, @msirek, and @rharding6373)

___
*[`-- commits` line 8 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/81844#-N3xFOqD0AkXzONLiVAR):*
nit: I think this is missing a word or two
___
*[`-- commits` line 14 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/81844#-N3xFc3wAfJhliTrqd5K):*
Should this be a bug fix?

**Review by mgartner — APPROVED** [review]
LGTM

**Review by rharding6373 — COMMENTED** [review]
TFTRs!

bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/81844#-:-N3z5RH698FBOQ4An7GG:b-tlx7ko)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale) (waiting on @mgartner, @msirek, and @rytaft)

___
*[`-- commits` line 14 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/81844#-N3xFc3wAfJhliTrqd5K):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

Should this be a bug fix?
</blockquote></details>

Done.

**Comment by rafiss** [comment]
Does this need a backport still?

**Comment by mgartner** [comment]
Yes thanks for catching this. I'll backport.
