### PR TITLE
rac2,replica_rac2: fix deadlock due to HoldsSendTokensRaftMuLocked be…

### LINKED ISSUE #132646: kv/kvserver: TestFlowControlUnquiescedRangeV2 failed
kv/kvserver.TestFlowControlUnquiescedRangeV2 [failed](https://tanzanite.cluster.engflow.com/invocations/default/d1526788-0651-4582-b52a-0c0c23d50dd2?testReportRun=1&testReportShard=20&testReportAttempt=1#targets-Ly9wa2cva3Yva3ZzZXJ2ZXI6a3ZzZXJ2ZXJfdGVzdA==) on master @ [a1b013e763abd1454603985996a45663b6e6bcad](https://github.com/cockroachdb/cockroach/commits/a1b013e763abd1454603985996a45663b6e6bcad):

```
          kvflowcontrol.tokens.eval.regular.unaccounted                     | 0 B      
          kvflowcontrol.tokens.send.elastic.available                       | 21 MiB   
          kvflowcontrol.tokens.send.elastic.deducted                        | 6.0 MiB  
          kvflowcontrol.tokens.send.elastic.deducted.force_flush_send_queue | 0 B      
          kvflowcontrol.tokens.send.elastic.deducted.prevent_send_queue     | 0 B      
          kvflowcontrol.tokens.send.elastic.returned                        | 3.0 MiB  
          kvflowcontrol.tokens.send.elastic.returned.disconnect             | 0 B      
          kvflowcontrol.tokens.send.elastic.unaccounted                     | 0 B      
          kvflowcontrol.tokens.send.regular.available                       | 48 MiB   
          kvflowcontrol.tokens.send.regular.deducted                        | 0 B      
          kvflowcontrol.tokens.send.regular.deducted.prevent_send_queue     | 0 B      
          kvflowcontrol.tokens.send.regular.returned                        | 0 B      
          kvflowcontrol.tokens.send.regular.returned.disconnect             | 0 B      
          kvflowcontrol.tokens.send.regular.unaccounted                     | 0 B      
        
        
        -- (Allow below-raft admission to proceed. We've enabled the piggybacked token
        -- return mechanism so tokens are returned either via this path, or the normal
        -- MsgAppResp flow, depending on which is exercised first.)
        SELECT name, crdb_internal.humanize_bytes(value::INT8)
            FROM crdb_internal.node_metrics
           WHERE name LIKE '%kvflowcontrol%tokens%'
        ORDER BY name ASC;
        
          kvflowcontrol.tokens.eval.elastic.available                       | 24 MiB   
          kvflowcontrol.tokens.eval.elastic.deducted                        | 6.0 MiB  
          kvflowcontrol.tokens.eval.elastic.returned                        | 6.0 MiB  
          kvflowcontrol.tokens.eval.elastic.returned.disconnect             | 0 B      
          kvflowcontrol.tokens.eval.elastic.unaccounted                     | 0 B      
          kvflowcontrol.tokens.eval.regular.available                       | 48 MiB   
          kvflowcontrol.tokens.eval.regular.deducted                        | 0 B      
          kvflowcontrol.tokens.eval.regular.returned                        | 0 B      
          kvflowcontrol.tokens.eval.regular.returned.disconnect             | 0 B      
          kvflowcontrol.tokens.eval.regular.unaccounted                     | 0 B      
          kvflowcontrol.tokens.send.elastic.available                       | 24 MiB   
          kvflowcontrol.tokens.send.elastic.deducted                        | 6.0 MiB  
          kvflowcontrol.tokens.send.elastic.deducted.force_flush_send_queue | 0 B      
          kvflowcontrol.tokens.send.elastic.deducted.prevent_send_queue     | 0 B      
          kvflowcontrol.tokens.send.elastic.returned                        | 6.0 MiB  
          kvflowcontrol.tokens.send.elastic.returned.disconnect             | 0 B      
          kvflowcontrol.tokens.send.elastic.unaccounted                     | 0 B      
          kvflowcontrol.tokens.send.regular.available                       | 48 MiB   
          kvflowcontrol.tokens.send.regular.deducted                        | 0 B      
          kvflowcontrol.tokens.send.regular.deducted.prevent_send_queue     | 0 B      
          kvflowcontrol.tokens.send.regular.returned                        | 0 B      
          kvflowcontrol.tokens.send.regular.returned.disconnect             | 0 B      
          kvflowcontrol.tokens.send.regular.unaccounted                     | 0 B      
        
        
        -- (Now the range can quiesce. Wait for it.)
```

Parameters:
 - <code>attempt=1</code>
 - <code>deadlock=true</code>
 - <code>run=1</code>
 - <code>shard=20</code>
<details><summary>Help</summary>
<p>

See also: [How To Investigate a Go Test Failure \(internal\)](https://cockroachlabs.atlassian.net/l/c/HgfXfJgM)
</p>
</details>
/cc @cockroachdb/kv
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*TestFlowControlUnquiescedRangeV2.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/bazci/githubpost/issues)
</sub>

Jira issue: CRDB-43202

### PR DESCRIPTION
**Pull request by sumeerbhola**
…ing called with Replica.mu held

It isn't convenient to not hold Replica.mu in the caller so instead we avoid needing replicaSendStream.mu (which is and must be ordered before Replica.mu). This is done by lifting replicaSendStream.mu.Tracker out of the mu struct.

Additional changes:
- All methods in replicaState and replicaSendStream are named to include what locks are held. This makes them verbose, but it is important for correctness.
- Assertions are added for replicaSendStream.mu being held.
- Todos are added to make Replica.raftMu and Replica.mu assertions free in replica_rac2 and rac2 code, and once that is done to add more assertions in rac2.
- Todo is added to lift some more fields in replicaSendStream from inside mu (the main reason we need mu is for replicaSendStream.Notify). This todo is ordered after the previous one (more assertions).

Fixes #132646, #132642

Epic: CRDB-37515

Release note: None

### CODE REVIEW

File: pkg/kv/kvserver/kvflowcontrol/rac2/range_controller.go [hunk 1]
```diff
@@ -1886,34 +1898,41 @@ type replicaSendStream struct {
 		}
 		closed bool
 	}
+	// tracker contains entries that have been sent, and have had send-tokens
+	// deducted (and will have had eval-tokens deducted iff index >=
+	// nextRaftIndexInitial).
+	//
+	// Contains no entries in probeRecentlyNoSendQ.
+	tracker Tracker
```
Comment (pav-kv) [inline pkg/kv/kvserver/kvflowcontrol/rac2/range_controller.go:1906]: Is the reason why it's safe to move `tracker` out of `replicaSendStream.mu` the fact that it has its own mutex?

With this change, is there a mental model for what other mutexes are held when `tracker` is accessed? E.g. something like: `raftMu` is held when tokens are registered, and not held when deregistered; or maybe `raftMu` is always held when mutating it?

If there is an easy was to describe this, consider putting it into the comment. If `tracker` is always accessed under `raftMu`, consider making a `raftMu struct` section here containing it.

**Review by kvoli — APPROVED** [review]
:lgtm:

> Reviewed 8 of 8 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/132763#-:-O9L9Lj_2mgE1iLixeNJ:bnfp4nl)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @pav-kv and @sumeerbhola)

___
*[`pkg/kv/kvserver/replica_raft.go` line 606 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/132763#-O9L7HA18j6uQ4bWE2sF:-O9L7HA18j6uQ4bWE2sG:b-yfggw0) ([raw file](https://github.com/cockroachdb/cockroach/blob/1bef707f82a63f473d80609c6c3edd8e43a79b90/pkg/kv/kvserver/replica_raft.go#L606)):*
> ```Go
> // We can't quiesce while any send tokens are held because this could lead to
> // never releasing them. Tokens must be released.
> func (r *Replica) hasSendTokensRaftMuLockedReplicaMuLocked() bool {
> ```

nit: consider adding an assertion on ReplicaMu and raft mu here (might be lower down anyway, so ignore if that is the case).
___
*[`pkg/kv/kvserver/replica_raft_quiesce.go` line 215 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/132763#-O9L7MUb6CuVws3Cgw8d:-O9L7MUb6CuVws3Cgw8e:b-fy6lqg) ([raw file](https://github.com/cockroachdb/cockroach/blob/1bef707f82a63f473d80609c6c3edd8e43a79b90/pkg/kv/kvserver/replica_raft_quiesce.go#L215)):*
> ```Go
> 	hasPendingProposalsRLocked() bool
> 	hasPendingProposalQuotaRLocked() bool
> 	// TODO(pav-kv): this method is a one-off holding raftMu. It should be able to
> ```

nit: this comment seems stale now, since it is both repl mu and raft mu.
___
*[`pkg/kv/kvserver/kvflowcontrol/rac2/range_controller.go` line 1499 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/132763#-O9L82Gh073r37K8mQq-:-O9L82GiDHtWTWMq65dX:b-hjw63i) ([raw file](https://github.com/cockroachdb/cockroach/blob/1bef707f82a63f473d80609c6c3edd8e43a79b90/pkg/kv/kvserver/kvflowcontrol/rac2/range_controller.go#L1499)):*
> ```Go
> 				defer rs.sendStream.mu.Unlock()
> 				stats.SendQueueBytes = int64(rs.sendStream.approxQueueSizeStreamLocked())
> 				stats.SendQueueCount = rs.sendStream.queueLengthRaftMuAndStreamLocked()
> ```

nit: feel free to ignore this one, but remove the `And` between the locked parts here, since I believe the more common pattern is just to concatenate without a separator, by order.
___
*[`pkg/kv/kvserver/kvflowcontrol/rac2/range_controller.go` line 2701 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/132763#-O9L8puR0u2duZMdL7Cn:-O9L8puR0u2duZMdL7Co:b-i6metq) ([raw file](https://github.com/cockroachdb/cockroach/blob/1bef707f82a63f473d80609c6c3edd8e43a79b90/pkg/kv/kvserver/kvflowcontrol/rac2/range_controller.go#L2701)):*
> ```Go
> }
> 
> // NB: raftMu may or may not be held. Specifically, when called from Notify,
> ```

I had to delete my comment above on the call path which holds raftMu :smile:
___
*[`pkg/kv/kvserver/kvflowcontrol/rac2/range_controller.go` line 2722 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/132763#-O9L8yo1Azs_J80-03-j:-O9L8yo1Azs_J80-03-k:b-nbob5o) ([raw file](https://github.com/cockroachdb/cockroach/blob/1bef707f82a63f473d80609c6c3edd8e43a79b90/pkg/kv/kvserver/kvflowcontrol/rac2/range_controller.go#L2722)):*
> ```Go
> 	rss.mu.Lock()
> 	defer rss.mu.Unlock()
> 	if rss.mu.closed {
> ```

Is this a correctness fix?  Seems benign to me after thinking about it for a few seconds but curious on the context of the diff.

**Review by pav-kv — COMMENTED** [review]
Posted one question, to help get my head around the change.

A drive-by comment regarding the structure of the PR (not needed to address now unless you want to, but please keep in mind for future). It would be easier to grok the essence of the fix if it was separated from other drive-by changes / renames / etc. Any time the PR description says "does A and B and C and D", this is a candidate to be split into commits accordingly, for ease of review.

**Review by sumeerbhola — COMMENTED** [review]
> A drive-by comment regarding the structure of the PR (not needed to address now, but please keep in mind for future).

Ack.


TFTRs!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/132763#-:-O9LB41-EJfAlAiP_-_3:b-m790qq)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @kvoli and @pav-kv)

___
*[`pkg/kv/kvserver/replica_raft.go` line 606 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/132763#-O9L7HA18j6uQ4bWE2sF:-O9LEyI82v1FpLrNGvex:blvkxs3) ([raw file](https://github.com/cockroachdb/cockroach/blob/1bef707f82a63f473d80609c6c3edd8e43a79b90/pkg/kv/kvserver/replica_raft.go#L606)):*
<details><summary><i>Previously, kvoli (Austen) wrote…</i></summary><blockquote>

nit: consider adding an assertion on ReplicaMu and raft mu here (might be lower down anyway, so ignore if that is the case).
</blockquote></details>

We do the assertions in `processorImpl`.
___
*[`pkg/kv/kvserver/replica_raft_quiesce.go` line 215 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/132763#-O9L7MUb6CuVws3Cgw8d:-O9LBK3t3uR8AQGcVpmS:ba3dfob) ([raw file](https://github.com/cockroachdb/cockroach/blob/1bef707f82a63f473d80609c6c3edd8e43a79b90/pkg/kv/kvserver/replica_raft_quiesce.go#L215)):*
<details><summary><i>Previously, kvoli (Austen) wrote…</i></summary><blockquote>

nit: this comment seems stale now, since it is both repl mu and raft mu.
</blockquote></details>

Removed
___
*[`pkg/kv/kvserver/kvflowcontrol/rac2/range_controller.go` line 1499 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/132763#-O9L82Gh073r37K8mQq-:-O9LBPT558blFQ1h2epL:b-g5z5h3) ([raw file](https://github.com/cockroachdb/cockroach/blob/1bef707f82a63f473d80609c6c3edd8e43a79b90/pkg/kv/kvserver/kvflowcontrol/rac2/range_controller.go#L1499)):*
<details><summary><i>Previously, kvoli (Austen) wrote…</i></summary><blockquote>

nit: feel free to ignore this one, but remove the `And` between the locked parts here, since I believe the more common pattern is just to concatenate without a separator, by order.
</blockquote></details>

I've seen `RaftMuLockedReplicaMuLocked` in the kvserver code. And I didn't want to repeat "Locked". Having "and" in there helps me a bit wrt readability. And still saved two characters compared to repeating locked :)
___
*[`pkg/kv/kvserver/kvflowcontrol/rac2/range_controller.go` line 1906 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/132763#gh-1803439570:-O9LBz_aEPwcbMafhW4j:bt3ua8) ([raw file](https://github.com/cockroachdb/cockroach/blob/1bef707f82a63f473d80609c6c3edd8e43a79b90/pkg/kv/kvserver/kvflowcontrol/rac2/range_controller.go#L1906)):*
> Is the reason why it's safe to move `tracker` out of `replicaSendStream.mu` the fact that it has its own mutex?

It doesn't have its own mutex. I've added a code comment stating that raftMu is held.

> If `tracker` is always accessed under `raftMu`, consider making a `raftMu struct` section here containing it.

Done
___
*[`pkg/kv/kvserver/kvflowcontrol/rac2/range_controller.go` line 2701 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/132763#-O9L8puR0u2duZMdL7Cn:-O9LDD0l3VrXsLDQ5d1i:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/1bef707f82a63f473d80609c6c3edd8e43a79b90/pkg/kv/kvserver/kvflowcontrol/rac2/range_controller.go#L2701)):*
<details><summary><i>Previously, kvoli (Austen) wrote…</i></summary><blockquote>

I had to delete my comment above on the call path which holds raftMu :smile:
</blockquote></details>

Done.
___
*[`pkg/kv/kvserver/kvflowcontrol/rac2/range_controller.go` line 2722 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/132763#-O9L8yo1Azs_J80-03-j:-O9LDFsZ-X9COO7Iwd2q:b-rw7ffj) ([raw file](https://github.com/cockroachdb/cockroach/blob/1bef707f82a63f473d80609c6c3edd8e43a79b90/pkg/kv/kvserver/kvflowcontrol/rac2/range_controller.go#L2722)):*
<details><summary><i>Previously, kvoli (Austen) wrote…</i></summary><blockquote>

Is this a correctness fix?  Seems benign to me after thinking about it for a few seconds but curious on the context of the diff.
</blockquote></details>

I should not have put it in this PR, but I noticed we never read `rss.mu.closed`. The reason `rss.mu.closed` existed was to ignore `Notify`.

I don't think this was a bug because in `close` we also set `tokenWatcherHandle to empty.

I've added a TODO to remove closed. Currently we print it in unit tests, so I don't want to do it in this PR.

File: pkg/kv/kvserver/kvflowcontrol/rac2/range_controller.go [hunk 2]
```diff
@@ -1904,36 +1916,52 @@ type replicaSendStream struct {
...
+		// replicaSendStream. But closing a send stream also sets
+		// replicaSendStream.mu.sendQueue.tokenWatcherHandle to empty, and Notify
+		// is already a noop in that case. So this field serves no useful purpose.
 		closed bool
 	}
+	// Fields that are read/written while holding raftMu.
+	raftMu struct {
+		// tracker contains entries that have been sent, and have had send-tokens
+		// deducted (and will have had eval-tokens deducted iff index >=
+		// nextRaftIndexInitial).
```
Comment (pav-kv) [inline pkg/kv/kvserver/kvflowcontrol/rac2/range_controller.go:1931]: Aren't eval tokens deducted first? Should "will have had" be "have had" or some form of the past?
Could you make the order of things clearer in this comment?

**Review by pav-kv — APPROVED** [review]

File: pkg/kv/kvserver/kvflowcontrol/rac2/range_controller.go (hunk 2 above)
Comment (sumeerbhola) [reply pkg/kv/kvserver/kvflowcontrol/rac2/range_controller.go:1931]: > Aren't eval tokens deducted first?

Correct.

> Should "will have had" be "have had" or some form of the past? Could you make the order of things clearer in this comment?

Yep -- I'll do so in the next PR. I want to merge this now given CI was green before the last round of changes, and I only made superficial changes in that last round.

**Review by kvoli — APPROVED** [review]

**Comment by sumeerbhola** [comment]
bors r=kvoli,pav-kv
