### PR TITLE
Remove TestOverlappingTransactions

### LINKED ISSUE #2366: go test ./sql/driver/... -count=100 fails
It fails in TestOverlappingTransactions where the second transaction fails every once in a while.

### PR DESCRIPTION
**Pull request by vivekmenezes**
closes #2366

### CODE REVIEW

File: sql/driver/driver_test.go [hunk 1]
```diff
@@ -273,91 +272,3 @@ func TestInsecure(t *testing.T) {
 		t.Fatal(err)
 	}
 }
-
-// Start a transaction to update a row. After updating the row and
-// before committing the transaction, start another transaction in
-// another thread to update the same row. The other transaction succeeds,
-// resulting in the first transaction failing.
-func TestOverlappingTransactions(t *testing.T) {
```
Comment (petermattis) [inline sql/driver/driver_test.go]: I'm fine with seeing this test removed, but as @tschottdorf points out, we do need tests that we're handling various transaction cases correctly.

**Comment by petermattis** [comment]
LGTM

File: sql/driver/driver_test.go (hunk 1 above)
Comment (vivekmenezes) [inline sql/driver/driver_test.go]: True, but this is not the one.
