### PR TITLE
sql: use better identifiers in the rnd schema test

### LINKED ISSUE #95238: sql: pretty-printing of partition clauses is incorrect
**Describe the problem**

When partition names or columns contain special characters, the output of SHOW CREATE is invalid SQL syntax.

For example:
```
demo@127.0.0.1:26257/movr> create table foo("a b" name not null, index ("a b") partition by list ("a b") (partition foo values in ('ab')));
CREATE TABLE

Time: 6ms total (execution 6ms / network 0ms)

demo@127.0.0.1:26257/movr> show create table foo;
  table_name |                       create_statement
-------------+----------------------------------------------------------------
  foo        | CREATE TABLE public.foo (
             |     "a b" NAME NOT NULL,
             |     rowid INT8 NOT VISIBLE NOT NULL DEFAULT unique_rowid(),
             |     CONSTRAINT foo_pkey PRIMARY KEY (rowid ASC),
             |     INDEX "foo_a b_idx" ("a b" ASC) PARTITION BY LIST (a b) (
             |         PARTITION foo VALUES IN (('ab'))
             |     )
             | )
```

The identifier inside PARTITION BY LIST is improperly quoted.

### PR DESCRIPTION
**Pull request by knz**
This extends TestRandomSchema to use the new random identifier generator.

Release note: None
Epic: None

### CODE REVIEW

File: pkg/sql/randgen/schema.go [hunk 1]
```diff
@@ -17,7 +17,7 @@ import (
 	"math/rand"
 	"strings"
 
-	"github.com/cockroachdb/apd/v3"
+	apd "github.com/cockroachdb/apd/v3"
```
Comment (otan) [inline pkg/sql/randgen/schema.go:20]: is this `apd` change necessary?

**Review by otan — APPROVED** [review]

File: pkg/sql/randgen/schema.go (hunk 1 above)
Comment (knz) [reply pkg/sql/randgen/schema.go:20]: my editor does it automatically when the path doesn't match the package name

**Comment by knz** [comment]
bors r=otan
