### PR TITLE
roachtest: export sysbench results to roachperf

### LINKED ISSUE #123071: roachtest: add sysbench suite to roachperf
We run the following sysbench tests nightly:
```bash
➜ roachtest list sysbench
Listing tests which match regex "sysbench" and are compatible with cloud "gce".

sysbench/oltp_delete/nodes=3/cpu=32/conc=256 [test-eng]
sysbench/oltp_insert/nodes=3/cpu=32/conc=256 [test-eng]
sysbench/oltp_point_select/nodes=3/cpu=32/conc=256 [test-eng]
sysbench/oltp_read_only/nodes=3/cpu=32/conc=256 [test-eng]
sysbench/oltp_read_write/nodes=3/cpu=32/conc=256 [test-eng]
sysbench/oltp_update_index/nodes=3/cpu=32/conc=256 [test-eng]
sysbench/oltp_update_non_index/nodes=3/cpu=32/conc=256 [test-eng]
sysbench/oltp_write_only/nodes=3/cpu=32/conc=256 [test-eng]
```

These should be marked as benchmarks and uploaded to roachperf so that we can track performance over time and catch performance regressions.

Jira issue: CRDB-38187

### PR DESCRIPTION
**Pull request by DarrylWong**
This change parses the results of sysbench tests to JSON, so they can be exported to roachperf.

Epic: https://cockroachlabs.atlassian.net/browse/CRDB-38187
Fixes: https://github.com/cockroachdb/cockroach/issues/123071
Release note: none

_________________________________________

See https://github.com/cockroachdb/roachperf/pull/167 for the corresponding roachperf PR.

image

### CODE REVIEW

File: pkg/cmd/roachtest/tests/sysbench.go [hunk 1]
```diff
@@ -179,3 +195,89 @@ func registerSysbench(r registry.Registry) {
...
+	if err != nil {
+		return err
+	}
+
+	var metricBytes []byte
+
+	s := bufio.NewScanner(strings.NewReader(result))
+	for s.Scan() {
+		if matched := regex.MatchString(s.Text()); !matched {
+			continue
```
Comment (srosenberg) [inline pkg/cmd/roachtest/tests/sysbench.go:241]: Should this be an error, or are there lines we don't expect to match? If latter, maybe we should count the number of parsed lines and log it, for ease of debugging; i.e., thinking about the case when all of a sudden we get an empty output, say due to a format change upstream.

**Review by srosenberg — APPROVED** [review]
Thanks! Minor comments, otherwise LGTM.
