### PR TITLE
kvserver: deflake TestReadLoadMetricAccounting

### LINKED ISSUE #159719: kv/kvserver: TestReadLoadMetricAccounting failed
kv/kvserver.TestReadLoadMetricAccounting [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Ci_TestsAwsLinuxArm64_UnitTests/20875529?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Ci_TestsAwsLinuxArm64_UnitTests/20875529?buildTab=artifacts#/) on master @ [72825229532522f6377e706e009c1090eb1f9b23](https://github.com/cockroachdb/cockroach/commits/72825229532522f6377e706e009c1090eb1f9b23):

```
=== RUN   TestReadLoadMetricAccounting
    test_log_scope.go:171: test logs captured to: /artifacts/tmp/_tmp/645d36459c8d7b7939924714a555a08a/logTestReadLoadMetricAccounting564952480
    test_log_scope.go:82: use -show-logs to present logs inline
    test_server_shim.go:668: DRPC is enabled (via override by TestingGlobalDRPCOption)
    replica_rankings_test.go:441: evaluated [logtags=: *kvpb.AddSSTableRequest
    replica_rankings_test.go:444: evaluated [logtags=]: *kvpb.LeaseInfoRequest on /Table/Max: header:<key:"\372" >  {Timestamp:1765988944.111903730,0 TimestampFromServerClock:<nil> Now:1765988944.111903730,0 Replica:(n1,s1):1 RangeID:81 UserPriority:normal Txn:<nil> ReadConsistency:INCONSISTENT RoutingPolicy:NEAREST WaitPolicy:Block LockTimeout:0s MaxSpanRequestKeys:0 TargetBytes:0 WholeRowsOfSize:0 AllowEmpty:false DistinctSpans:false AsyncConsensus:false CanForwardReadTimestamp:false GatewayNodeID:1 ClientRangeInfo:{DescriptorGeneration:1 LeaseSequence:1 ClosedTimestampPolicy:LAG_BY_CLUSTER_SETTING ExplicitlyRequested:false} BoundedStaleness:<nil> TraceInfo:<nil> IndexFetchSpec:<nil> ReturnElasticCPUResumeSpans:false ProfileLabels:[] AmbiguousReplayProtection:false ConnectionClass:default ProxyRangeInfo:<nil> WriteOptions:<nil> DeadlockTimeout:0s HasBufferedAllPrecedingWrites:false IsReverse:false}
    replica_rankings_test.go:444: evaluated [logtags=]: *kvpb.LeaseInfoRequest on /Table/Max: header:<key:"\372" >  {Timestamp:1765988944.112240907,0 TimestampFromServerClock:<nil> Now:1765988944.112240907,0 Replica:(n1,s1):1 RangeID:81 UserPriority:normal Txn:<nil> ReadConsistency:INCONSISTENT RoutingPolicy:NEAREST WaitPolicy:Block LockTimeout:0s MaxSpanRequestKeys:0 TargetBytes:0 WholeRowsOfSize:0 AllowEmpty:false DistinctSpans:false AsyncConsensus:false CanForwardReadTimestamp:false GatewayNodeID:1 ClientRangeInfo:{DescriptorGeneration:1 LeaseSequence:1 ClosedTimestampPolicy:LAG_BY_CLUSTER_SETTING ExplicitlyRequested:false} BoundedStaleness:<nil> TraceInfo:<nil> IndexFetchSpec:<nil> ReturnElasticCPUResumeSpans:false ProfileLabels:[] AmbiguousReplayProtection:false ConnectionClass:default ProxyRangeInfo:<nil> WriteOptions:<nil> DeadlockTimeout:0s HasBufferedAllPrecedingWrites:false IsReverse:false}
    replica_rankings_test.go:444: evaluated [logtags=]: *kvpb.LeaseInfoRequest on /Table/Max: header:<key:"\372" >  {Timestamp:1765988944.112430629,0 TimestampFromServerClock:<nil> Now:1765988944.112430629,0 Replica:(n1,s1):1 RangeID:81 UserPriority:normal Txn:<nil> ReadConsistency:INCONSISTENT RoutingPolicy:NEAREST WaitPolicy:Block LockTimeout:0s MaxSpanRequestKeys:0 TargetBytes:0 WholeRowsOfSize:0 AllowEmpty:false DistinctSpans:false AsyncConsensus:false CanForwardReadTimestamp:false GatewayNodeID:1 ClientRangeInfo:{DescriptorGeneration:1 LeaseSequence:1 ClosedTimestampPolicy:LAG_BY_CLUSTER_SETTING ExplicitlyRequested:false} BoundedStaleness:<nil> TraceInfo:<nil> IndexFetchSpec:<nil> ReturnElasticCPUResumeSpans:false ProfileLabels:[] AmbiguousReplayProtection:false ConnectionClass:default ProxyRangeInfo:<nil> WriteOptions:<nil> DeadlockTimeout:0s HasBufferedAllPrecedingWrites:false IsReverse:false}
    replica_rankings_test.go:444: evaluated [logtags=]: *kvpb.LeaseInfoRequest on /Table/Max: header:<key:"\372" >  {Timestamp:1765988944.112690747,0 TimestampFromServerClock:<nil> Now:1765988944.112690747,0 Replica:(n1,s1):1 RangeID:81 UserPriority:normal Txn:<nil> ReadConsistency:INCONSISTENT RoutingPolicy:NEAREST WaitPolicy:Block LockTimeout:0s MaxSpanRequestKeys:0 TargetBytes:0 WholeRowsOfSize:0 AllowEmpty:false DistinctSpans:false AsyncConsensus:false CanForwardReadTimestamp:false GatewayNodeID:1 ClientRangeInfo:{DescriptorGeneration:1 LeaseSequence:1 ClosedTimestampPolicy:LAG_BY_CLUSTER_SETTING ExplicitlyRequested:false} BoundedStaleness:<nil> TraceInfo:<nil> IndexFetchSpec:<nil> ReturnElasticCPUResumeSpans:false ProfileLabels:[] AmbiguousReplayProtection:false ConnectionClass:default ProxyRangeInfo:<nil> WriteOptions:<nil> DeadlockTimeout:0s HasBufferedAllPrecedingWrites:false IsReverse:false}
    replica_rankings_test.go:444: evaluated [logtags=]: *kvpb.LeaseInfoRequest on /Table/Max: header:<key:"\372" >  {Timestamp:1765988944.112914099,0 TimestampFromServerClock:<nil> Now:1765988944.112914099,0 Replica:(n1,s1):1 RangeID:81 UserPriority:normal Txn:<nil> ReadConsistency:INCONSISTENT RoutingPolicy:NEAREST WaitPolicy:Block LockTimeout:0s MaxSpanRequestKeys:0 TargetBytes:0 WholeRowsOfSize:0 AllowEmpty:false DistinctSpans:false AsyncConsensus:false CanForwardReadTimestamp:false GatewayNodeID:1 ClientRangeInfo:{DescriptorGeneration:1 LeaseSequence:1 ClosedTimestampPolicy:LAG_BY_CLUSTER_SETTING ExplicitlyRequested:false} BoundedStaleness:<nil> TraceInfo:<nil> IndexFetchSpec:<nil> ReturnElasticCPUResumeSpans:false ProfileLabels:[] AmbiguousReplayProtection:false ConnectionClass:default ProxyRangeInfo:<nil> WriteOptions:<nil> DeadlockTimeout:0s HasBufferedAllPrecedingWrites:false IsReverse:false}
    replica_rankings_test.go:444: evaluated [logtags=]: *kvpb.LeaseInfoRequest on /Table/Max: header:<key:"\372" >  {Timestamp:1765988944.113094298,0 TimestampFromServerClock:<nil> Now:1765988944.113094298,0 Replica:(n1,s1):1 RangeID:81 UserPriority:normal Txn:<nil> ReadConsistency:INCONSISTENT RoutingPolicy:NEAREST WaitPolicy:Block LockTimeout:0s MaxSpanRequestKeys:0 TargetBytes:0 WholeRowsOfSize:0 AllowEmpty:false DistinctSpans:false AsyncConsensus:false CanForwardReadTimestamp:false GatewayNodeID:1 ClientRangeInfo:{DescriptorGeneration:1 LeaseSequence:1 ClosedTimestampPolicy:LAG_BY_CLUSTER_SETTING ExplicitlyRequested:false} BoundedStaleness:<nil> TraceInfo:<nil> IndexFetchSpec:<nil> ReturnElasticCPUResumeSpans:false ProfileLabels:[] AmbiguousReplayProtection:false ConnectionClass:default ProxyRangeInfo:<nil> WriteOptions:<nil> DeadlockTimeout:0s HasBufferedAllPrecedingWrites:false IsReverse:false}
    replica_rankings_test.go:444: evaluated [logtags=]: *kvpb.LeaseInfoRequest on /Table/Max: header:<key:"\372" >  {Timestamp:1765988944.113288467,0 TimestampFromServerClock:<nil> Now:1765988944.113288467,0 Replica:(n1,s1):1 RangeID:81 UserPriority:normal Txn:<nil> ReadConsistency:INCONSISTENT RoutingPolicy:NEAREST WaitPolicy:Block LockTimeout:0s MaxSpanRequestKeys:0 TargetBytes:0 WholeRowsOfSize:0 AllowEmpty:false DistinctSpans:false AsyncConsensus:false CanForwardReadTimestamp:false GatewayNodeID:1 ClientRangeInfo:{DescriptorGeneration:1 LeaseSequence:1 ClosedTimestampPolicy:LAG_BY_CLUSTER_SETTING ExplicitlyRequested:false} BoundedStaleness:<nil> TraceInfo:<nil> IndexFetchSpec:<nil> ReturnElasticCPUResumeSpans:false ProfileLabels:[] AmbiguousReplayProtection:false ConnectionClass:default ProxyRangeInfo:<nil> WriteOptions:<nil> DeadlockTimeout:0s HasBufferedAllPrecedingWrites:false IsReverse:false}
    replica_rankings_test.go:444: evaluated [logtags=]: *kvpb.LeaseInfoRequest on /Table/Max: header:<key:"\372" >  {Timestamp:1765988944.113495601,0 TimestampFromServerClock:<nil> Now:1765988944.113495601,0 Replica:(n1,s1):1 RangeID:81 UserPriority:normal Txn:<nil> ReadConsistency:INCONSISTENT RoutingPolicy:NEAREST WaitPolicy:Block LockTimeout:0s MaxSpanRequestKeys:0 TargetBytes:0 WholeRowsOfSize:0 AllowEmpty:false DistinctSpans:false AsyncConsensus:false CanForwardReadTimestamp:false GatewayNodeID:1 ClientRangeInfo:{DescriptorGeneration:1 LeaseSequence:1 ClosedTimestampPolicy:LAG_BY_CLUSTER_SETTING ExplicitlyRequested:false} BoundedStaleness:<nil> TraceInfo:<nil> IndexFetchSpec:<nil> ReturnElasticCPUResumeSpans:false ProfileLabels:[] AmbiguousReplayProtection:false ConnectionClass:default ProxyRangeInfo:<nil> WriteOptions:<nil> DeadlockTimeout:0s HasBufferedAllPrecedingWrites:false IsReverse:false}
    replica_rankings_test.go:444: evaluated [logtags=]: *kvpb.LeaseInfoRequest on /Table/Max: header:<key:"\372" >  {Timestamp:1765988944.113687234,0 TimestampFromServerClock:<nil> Now:1765988944.113687234,0 Replica:(n1,s1):1 RangeID:81 UserPriority:normal Txn:<nil> ReadConsistency:INCONSISTENT RoutingPolicy:NEAREST WaitPolicy:Block LockTimeout:0s MaxSpanRequestKeys:0 TargetBytes:0 WholeRowsOfSize:0 AllowEmpty:false DistinctSpans:false AsyncConsensus:false CanForwardReadTimestamp:false GatewayNodeID:1 ClientRangeInfo:{DescriptorGeneration:1 LeaseSequence:1 ClosedTimestampPolicy:LAG_BY_CLUSTER_SETTING ExplicitlyRequested:false} BoundedStaleness:<nil> TraceInfo:<nil> IndexFetchSpec:<nil> ReturnElasticCPUResumeSpans:false ProfileLabels:[] AmbiguousReplayProtection:false ConnectionClass:default ProxyRangeInfo:<nil> WriteOptions:<nil> DeadlockTimeout:0s HasBufferedAllPrecedingWrites:false IsReverse:false}
    replica_rankings_test.go:444: evaluated [logtags=]: *kvpb.LeaseInfoRequest on /Table/Max: header:<key:"\372" >  {Timestamp:1765988944.114027155,0 TimestampFromServerClock:<nil> Now:1765988944.114027155,0 Replica:(n1,s1):1 RangeID:81 UserPriority:normal Txn:<nil> ReadConsistency:INCONSISTENT RoutingPolicy:NEAREST WaitPolicy:Block LockTimeout:0s MaxSpanRequestKeys:0 TargetBytes:0 WholeRowsOfSize:0 AllowEmpty:false DistinctSpans:false AsyncConsensus:false CanForwardReadTimestamp:false GatewayNodeID:1 ClientRangeInfo:{DescriptorGeneration:1 LeaseSequence:1 ClosedTimestampPolicy:LAG_BY_CLUSTER_SETTING ExplicitlyRequested:false} BoundedStaleness:<nil> TraceInfo:<nil> IndexFetchSpec:<nil> ReturnElasticCPUResumeSpans:false ProfileLabels:[] AmbiguousReplayProtection:false ConnectionClass:default ProxyRangeInfo:<nil> WriteOptions:<nil> DeadlockTimeout:0s HasBufferedAllPrecedingWrites:false IsReverse:false}
    replica_rankings_test.go:444: evaluated [logtags=]: *kvpb.LeaseInfoRequest on /Table/Max: header:<key:"\372" >  {Timestamp:1765988944.114296156,0 TimestampFromServerClock:<nil> Now:1765988944.114296156,0 Replica:(n1,s1):1 RangeID:81 UserPriority:normal Txn:<nil> ReadConsistency:INCONSISTENT RoutingPolicy:NEAREST WaitPolicy:Block LockTimeout:0s MaxSpanRequestKeys:0 TargetBytes:0 WholeRowsOfSize:0 AllowEmpty:false DistinctSpans:false AsyncConsensus:false CanForwardReadTimestamp:false GatewayNodeID:1 ClientRangeInfo:{DescriptorGeneration:1 LeaseSequence:1 ClosedTimestampPolicy:LAG_BY_CLUSTER_SETTING ExplicitlyRequested:false} BoundedStaleness:<nil> TraceInfo:<nil> IndexFetchSpec:<nil> ReturnElasticCPUResumeSpans:false ProfileLabels:[] AmbiguousReplayProtection:false ConnectionClass:default ProxyRangeInfo:<nil> WriteOptions:<nil> DeadlockTimeout:0s HasBufferedAllPrecedingWrites:false IsReverse:false}
    replica_rankings_test.go:444: evaluated [logtags=]: *kvpb.LeaseInfoRequest on /Table/Max: header:<key:"\372" >  {Timestamp:1765988944.114502831,0 TimestampFromServerClock:<nil> Now:1765988944.114502831,0 Replica:(n1,s1):1 RangeID:81 UserPriority:normal Txn:<nil> ReadConsistency:INCONSISTENT RoutingPolicy:NEAREST WaitPolicy:Block LockTimeout:0s MaxSpanRequestKeys:0 TargetBytes:0 WholeRowsOfSize:0 AllowEmpty:false DistinctSpans:false AsyncConsensus:false CanForwardReadTimestamp:false GatewayNodeID:1 ClientRangeInfo:{DescriptorGeneration:1 LeaseSequence:1 ClosedTimestampPolicy:LAG_BY_CLUSTER_SETTING ExplicitlyRequested:false} BoundedStaleness:<nil> TraceInfo:<nil> IndexFetchSpec:<nil> ReturnElasticCPUResumeSpans:false ProfileLabels:[] AmbiguousReplayProtection:false ConnectionClass:default ProxyRangeInfo:<nil> WriteOptions:<nil> DeadlockTimeout:0s HasBufferedAllPrecedingWrites:false IsReverse:false}
    replica_rankings_test.go:444: evaluated [logtags=]: *kvpb.LeaseInfoRequest on /Table/Max: header:<key:"\372" >  {Timestamp:1765988944.114726024,0 TimestampFromServerClock:<nil> Now:1765988944.114726024,0 Replica:(n1,s1):1 RangeID:81 UserPriority:normal Txn:<nil> ReadConsistency:INCONSISTENT RoutingPolicy:NEAREST WaitPolicy:Block LockTimeout:0s MaxSpanRequestKeys:0 TargetBytes:0 WholeRowsOfSize:0 AllowEmpty:false DistinctSpans:false AsyncConsensus:false CanForwardReadTimestamp:false GatewayNodeID:1 ClientRangeInfo:{DescriptorGeneration:1 LeaseSequence:1 ClosedTimestampPolicy:LAG_BY_CLUSTER_SETTING ExplicitlyRequested:false} BoundedStaleness:<nil> TraceInfo:<nil> IndexFetchSpec:<nil> ReturnElasticCPUResumeSpans:false ProfileLabels:[] AmbiguousReplayProtection:false ConnectionClass:default ProxyRangeInfo:<nil> WriteOptions:<nil> DeadlockTimeout:0s HasBufferedAllPrecedingWrites:false IsReverse:false}
    replica_rankings_test.go:444: evaluated [logtags=]: *kvpb.LeaseInfoRequest on /Table/Max: header:<key:"\372" >  {Timestamp:1765988944.115037081,0 TimestampFromServerClock:<nil> Now:1765988944.115037081,0 Replica:(n1,s1):1 RangeID:81 UserPriority:normal Txn:<nil> ReadConsistency:INCONSISTENT RoutingPolicy:NEAREST WaitPolicy:Block LockTimeout:0s MaxSpanRequestKeys:0 TargetBytes:0 WholeRowsOfSize:0 AllowEmpty:false DistinctSpans:false AsyncConsensus:false CanForwardReadTimestamp:false GatewayNodeID:1 ClientRangeInfo:{DescriptorGeneration:1 LeaseSequence:1 ClosedTimestampPolicy:LAG_BY_CLUSTER_SETTING ExplicitlyRequested:false} BoundedStaleness:<nil> TraceInfo:<nil> IndexFetchSpec:<nil> ReturnElasticCPUResumeSpans:false ProfileLabels:[] AmbiguousReplayProtection:false ConnectionClass:default ProxyRangeInfo:<nil> WriteOptions:<nil> DeadlockTimeout:0s HasBufferedAllPrecedingWrites:false IsReverse:false}
    replica_rankings_test.go:444: evaluated [logtags=]: *kvpb.LeaseInfoRequest on /Table/Max: header:<key:"\372" >  {Timestamp:1765988944.115270173,0 TimestampFromServerClock:<nil> Now:1765988944.115270173,0 Replica:(n1,s1):1 RangeID:81 UserPriority:normal Txn:<nil> ReadConsistency:INCONSISTENT RoutingPolicy:NEAREST WaitPolicy:Block LockTimeout:0s MaxSpanRequestKeys:0 TargetBytes:0 WholeRowsOfSize:0 AllowEmpty:false DistinctSpans:false AsyncConsensus:false CanForwardReadTimestamp:false GatewayNodeID:1 ClientRangeInfo:{DescriptorGeneration:1 LeaseSequence:1 ClosedTimestampPolicy:LAG_BY_CLUSTER_SETTING ExplicitlyRequested:false} BoundedStaleness:<nil> TraceInfo:<nil> IndexFetchSpec:<nil> ReturnElasticCPUResumeSpans:false ProfileLabels:[] AmbiguousReplayProtection:false ConnectionClass:default ProxyRangeInfo:<nil> WriteOptions:<nil> DeadlockTimeout:0s HasBufferedAllPrecedingWrites:false IsReverse:false}
    replica_rankings_test.go:444: evaluated [logtags=]: *kvpb.LeaseInfoRequest on /Table/Max: header:<key:"\372" >  {Timestamp:1765988944.115472092,0 TimestampFromServerClock:<nil> Now:1765988944.115472092,0 Replica:(n1,s1):1 RangeID:81 UserPriority:normal Txn:<nil> ReadConsistency:INCONSISTENT RoutingPolicy:NEAREST WaitPolicy:Block LockTimeout:0s MaxSpanRequestKeys:0 TargetBytes:0 WholeRowsOfSize:0 AllowEmpty:false DistinctSpans:false AsyncConsensus:false CanForwardReadTimestamp:false GatewayNodeID:1 ClientRangeInfo:{DescriptorGeneration:1 LeaseSequence:1 ClosedTimestampPolicy:LAG_BY_CLUSTER_SETTING ExplicitlyRequested:false} BoundedStaleness:<nil> TraceInfo:<nil> IndexFetchSpec:<nil> ReturnElasticCPUResumeSpans:false ProfileLabels:[] AmbiguousReplayProtection:false ConnectionClass:default ProxyRangeInfo:<nil> WriteOptions:<nil> DeadlockTimeout:0s HasBufferedAllPrecedingWrites:false IsReverse:false}
    replica_rankings_test.go:444: evaluated [logtags=]: *kvpb.LeaseInfoRequest on /Table/Max: header:<key:"\372" >  {Timestamp:1765988944.116546926,0 TimestampFromServerClock:<nil> Now:1765988944.116546926,0 Replica:(n1,s1):1 RangeID:81 UserPriority:normal Txn:<nil> ReadConsistency:INCONSISTENT RoutingPolicy:NEAREST WaitPolicy:Block LockTimeout:0s MaxSpanRequestKeys:0 TargetBytes:0 WholeRowsOfSize:0 AllowEmpty:false DistinctSpans:false AsyncConsensus:false CanForwardReadTimestamp:false GatewayNodeID:1 ClientRangeInfo:{DescriptorGeneration:1 LeaseSequence:1 ClosedTimestampPolicy:LAG_BY_CLUSTER_SETTING ExplicitlyRequested:false} BoundedStaleness:<nil> TraceInfo:<nil> IndexFetchSpec:<nil> ReturnElasticCPUResumeSpans:false ProfileLabels:[] AmbiguousReplayProtection:false ConnectionClass:default ProxyRangeInfo:<nil> WriteOptions:<nil> DeadlockTimeout:0s HasBufferedAllPrecedingWrites:false IsReverse:false}
    replica_rankings_test.go:444: evaluated [logtags=]: *kvpb.LeaseInfoRequest on /Table/Max: header:<key:"\372" >  {Timestamp:1765988944.117067138,0 TimestampFromServerClock:<nil> Now:1765988944.117067138,0 Replica:(n1,s1):1 RangeID:81 UserPriority:normal Txn:<nil> ReadConsistency:INCONSISTENT RoutingPolicy:NEAREST WaitPolicy:Block LockTimeout:0s MaxSpanRequestKeys:0 TargetBytes:0 WholeRowsOfSize:0 AllowEmpty:false DistinctSpans:false AsyncConsensus:false CanForwardReadTimestamp:false GatewayNodeID:1 ClientRangeInfo:{DescriptorGeneration:1 LeaseSequence:1 ClosedTimestampPolicy:LAG_BY_CLUSTER_SETTING ExplicitlyRequested:false} BoundedStaleness:<nil> TraceInfo:<nil> IndexFetchSpec:<nil> ReturnElasticCPUResumeSpans:false ProfileLabels:[] AmbiguousReplayProtection:false ConnectionClass:default ProxyRangeInfo:<nil> WriteOptions:<nil> DeadlockTimeout:0s HasBufferedAllPrecedingWrites:false IsReverse:false}
    replica_rankings_test.go:444: evaluated [logtags=]: *kvpb.LeaseInfoRequest on /Table/Max: header:<key:"\372" >  {Timestamp:1765988944.117435923,0 TimestampFromServerClock:<nil> Now:1765988944.117435923,0 Replica:(n1,s1):1 RangeID:81 UserPriority:normal Txn:<nil> ReadConsistency:INCONSISTENT RoutingPolicy:NEAREST WaitPolicy:Block LockTimeout:0s MaxSpanRequestKeys:0 TargetBytes:0 WholeRowsOfSize:0 AllowEmpty:false DistinctSpans:false AsyncConsensus:false CanForwardReadTimestamp:false GatewayNodeID:1 ClientRangeInfo:{DescriptorGeneration:1 LeaseSequence:1 ClosedTimestampPolicy:LAG_BY_CLUSTER_SETTING ExplicitlyRequested:false} BoundedStaleness:<nil> TraceInfo:<nil> IndexFetchSpec:<nil> ReturnElasticCPUResumeSpans:false ProfileLabels:[] AmbiguousReplayProtection:false ConnectionClass:default ProxyRangeInfo:<nil> WriteOptions:<nil> DeadlockTimeout:0s HasBufferedAllPrecedingWrites:false IsReverse:false}
    replica_rankings_test.go:444: evaluated [logtags=]: *kvpb.LeaseInfoRequest on /Table/Max: header:<key:"\372" >  {Timestamp:1765988944.117959005,0 TimestampFromServerClock:<nil> Now:1765988944.117959005,0 Replica:(n1,s1):1 RangeID:81 UserPriority:normal Txn:<nil> ReadConsistency:INCONSISTENT RoutingPolicy:NEAREST WaitPolicy:Block LockTimeout:0s MaxSpanRequestKeys:0 TargetBytes:0 WholeRowsOfSize:0 AllowEmpty:false DistinctSpans:false AsyncConsensus:false CanForwardReadTimestamp:false GatewayNodeID:1 ClientRangeInfo:{DescriptorGeneration:1 LeaseSequence:1 ClosedTimestampPolicy:LAG_BY_CLUSTER_SETTING ExplicitlyRequested:false} BoundedStaleness:<nil> TraceInfo:<nil> IndexFetchSpec:<nil> ReturnElasticCPUResumeSpans:false ProfileLabels:[] AmbiguousReplayProtection:false ConnectionClass:default ProxyRangeInfo:<nil> WriteOptions:<nil> DeadlockTimeout:0s HasBufferedAllPrecedingWrites:false IsReverse:false}
    replica_rankings_test.go:444: evaluated [logtags=]: *kvpb.LeaseInfoRequest on /Table/Max: header:<key:"\372" >  {Timestamp:1765988944.119327656,0 TimestampFromServerClock:<nil> Now:1765988944.119327656,0 Replica:(n1,s1):1 RangeID:81 UserPriority:normal Txn:<nil> ReadConsistency:INCONSISTENT RoutingPolicy:NEAREST WaitPolicy:Block LockTimeout:0s MaxSpanRequestKeys:0 TargetBytes:0 WholeRowsOfSize:0 AllowEmpty:false DistinctSpans:false AsyncConsensus:false CanForwardReadTimestamp:false GatewayNodeID:1 ClientRangeInfo:{DescriptorGeneration:1 LeaseSequence:1 ClosedTimestampPolicy:LAG_BY_CLUSTER_SETTING ExplicitlyRequested:false} BoundedStaleness:<nil> TraceInfo:<nil> IndexFetchSpec:<nil> ReturnElasticCPUResumeSpans:false ProfileLabels:[] AmbiguousReplayProtection:false ConnectionClass:default ProxyRangeInfo:<nil> WriteOptions:<nil> DeadlockTimeout:0s HasBufferedAllPrecedingWrites:false IsReverse:false}
    replica_rankings_test.go:444: evaluated [logtags=]: *kvpb.LeaseInfoRequest on /Table/Max: header:<key:"\372" >  {Timestamp:1765988944.122235484,0 TimestampFromServerClock:<nil> Now:1765988944.122235484,0 Replica:(n1,s1):1 RangeID:81 UserPriority:normal Txn:<nil> ReadConsistency:INCONSISTENT RoutingPolicy:NEAREST WaitPolicy:Block LockTimeout:0s MaxSpanRequestKeys:0 TargetBytes:0 WholeRowsOfSize:0 AllowEmpty:false DistinctSpans:false AsyncConsensus:false CanForwardReadTimestamp:false GatewayNodeID:1 ClientRangeInfo:{DescriptorGeneration:1 LeaseSequence:1 ClosedTimestampPolicy:LAG_BY_CLUSTER_SETTING ExplicitlyRequested:false} BoundedStaleness:<nil> TraceInfo:<nil> IndexFetchSpec:<nil> ReturnElasticCPUResumeSpans:false ProfileLabels:[] AmbiguousReplayProtection:false ConnectionClass:default ProxyRangeInfo:<nil> WriteOptions:<nil> DeadlockTimeout:0s HasBufferedAllPrecedingWrites:false IsReverse:false}
    replica_rankings_test.go:444: evaluated [logtags=]: *kvpb.LeaseInfoRequest on /Table/Max: header:<key:"\372" >  {Timestamp:1765988944.128790152,0 TimestampFromServerClock:<nil> Now:1765988944.128790152,0 Replica:(n1,s1):1 RangeID:81 UserPriority:normal Txn:<nil> ReadConsistency:INCONSISTENT RoutingPolicy:NEAREST WaitPolicy:Block LockTimeout:0s MaxSpanRequestKeys:0 TargetBytes:0 WholeRowsOfSize:0 AllowEmpty:false DistinctSpans:false AsyncConsensus:false CanForwardReadTimestamp:false GatewayNodeID:1 ClientRangeInfo:{DescriptorGeneration:1 LeaseSequence:1 ClosedTimestampPolicy:LAG_BY_CLUSTER_SETTING ExplicitlyRequested:false} BoundedStaleness:<nil> TraceInfo:<nil> IndexFetchSpec:<nil> ReturnElasticCPUResumeSpans:false ProfileLabels:[] AmbiguousReplayProtection:false ConnectionClass:default ProxyRangeInfo:<nil> WriteOptions:<nil> DeadlockTimeout:0s HasBufferedAllPrecedingWrites:false IsReverse:false}
    replica_rankings_test.go:444: evaluated [logtags=]: *kvpb.LeaseInfoRequest on /Table/Max: header:<key:"\372" >  {Timestamp:1765988944.134400195,0 TimestampFromServerClock:<nil> Now:1765988944.134400195,0 Replica:(n1,s1):1 RangeID:81 UserPriority:normal Txn:<nil> ReadConsistency:INCONSISTENT RoutingPolicy:NEAREST WaitPolicy:Block LockTimeout:0s MaxSpanRequestKeys:0 TargetBytes:0 WholeRowsOfSize:0 AllowEmpty:false DistinctSpans:false AsyncConsensus:false CanForwardReadTimestamp:false GatewayNodeID:1 ClientRangeInfo:{DescriptorGeneration:1 LeaseSequence:1 ClosedTimestampPolicy:LAG_BY_CLUSTER_SETTING ExplicitlyRequested:false} BoundedStaleness:<nil> TraceInfo:<nil> IndexFetchSpec:<nil> ReturnElasticCPUResumeSpans:false ProfileLabels:[] AmbiguousReplayProtection:false ConnectionClass:default ProxyRangeInfo:<nil> WriteOptions:<nil> DeadlockTimeout:0s HasBufferedAllPrecedingWrites:false IsReverse:false}
    replica_rankings_test.go:444: evaluated [logtags=]: *kvpb.LeaseInfoRequest on /Table/Max: header:<key:"\372" >  {Timestamp:1765988944.143588503,0 TimestampFromServerClock:<nil> Now:1765988944.143588503,0 Replica:(n1,s1):1 RangeID:81 UserPriority:normal Txn:<nil> ReadConsistency:INCONSISTENT RoutingPolicy:NEAREST WaitPolicy:Block LockTimeout:0s MaxSpanRequestKeys:0 TargetBytes:0 WholeRowsOfSize:0 AllowEmpty:false DistinctSpans:false AsyncConsensus:false CanForwardReadTimestamp:false GatewayNodeID:1 ClientRangeInfo:{DescriptorGeneration:1 LeaseSequence:1 ClosedTimestampPolicy:LAG_BY_CLUSTER_SETTING ExplicitlyRequested:false} BoundedStaleness:<nil> TraceInfo:<nil> IndexFetchSpec:<nil> ReturnElasticCPUResumeSpans:false ProfileLabels:[] AmbiguousReplayProtection:false ConnectionClass:default ProxyRangeInfo:<nil> WriteOptions:<nil> DeadlockTimeout:0s HasBufferedAllPrecedingWrites:false IsReverse:false}
    replica_rankings_test.go:444: evaluated [logtags=]: *kvpb.LeaseInfoRequest on /Table/Max: header:<key:"\372" >  {Timestamp:1765988944.161041719,0 TimestampFromServerClock:<nil> Now:1765988944.161041719,0 Replica:(n1,s1):1 RangeID:81 UserPriority:normal Txn:<nil> ReadConsistency:INCONSISTENT RoutingPolicy:NEAREST WaitPolicy:Block LockTimeout:0s MaxSpanRequestKeys:0 TargetBytes:0 WholeRowsOfSize:0 AllowEmpty:false DistinctSpans:false AsyncConsensus:false CanForwardReadTimestamp:false GatewayNodeID:1 ClientRangeInfo:{DescriptorGeneration:1 LeaseSequence:1 ClosedTimestampPolicy:LAG_BY_CLUSTER_SETTING ExplicitlyRequested:false} BoundedStaleness:<nil> TraceInfo:<nil> IndexFetchSpec:<nil> ReturnElasticCPUResumeSpans:false ProfileLabels:[] AmbiguousReplayProtection:false ConnectionClass:default ProxyRangeInfo:<nil> WriteOptions:<nil> DeadlockTimeout:0s HasBufferedAllPrecedingWrites:false IsReverse:false}
    replica_rankings_test.go:444: evaluated [logtags=]: *kvpb.LeaseInfoRequest on /Table/Max: header:<key:"\372" >  {Timestamp:1765988944.195096870,0 TimestampFromServerClock:<nil> Now:1765988944.195096870,0 Replica:(n1,s1):1 RangeID:81 UserPriority:normal Txn:<nil> ReadConsistency:INCONSISTENT RoutingPolicy:NEAREST WaitPolicy:Block LockTimeout:0s MaxSpanRequestKeys:0 TargetBytes:0 WholeRowsOfSize:0 AllowEmpty:false DistinctSpans:false AsyncConsensus:false CanForwardReadTimestamp:false GatewayNodeID:1 ClientRangeInfo:{DescriptorGeneration:1 LeaseSequence:1 ClosedTimestampPolicy:LAG_BY_CLUSTER_SETTING ExplicitlyRequested:false} BoundedStaleness:<nil> TraceInfo:<nil> IndexFetchSpec:<nil> ReturnElasticCPUResumeSpans:false ProfileLabels:[] AmbiguousReplayProtection:false ConnectionClass:default ProxyRangeInfo:<nil> WriteOptions:<nil> DeadlockTimeout:0s HasBufferedAllPrecedingWrites:false IsReverse:false}
    replica_rankings_test.go:444: evaluated [logtags=]: *kvpb.RequestLeaseRequest on /Table/Max: header:<key:"\372" > lease:<start:<> replica:<node_id:1 store_id:1 replica_id:1 type:VOTER_FULL > proposed_ts:<wall_time:1765988944261918514 > sequence:1 acquisition_type:Request min_expiration:<wall_time:1765988950077331053 > term:6 > prev_lease:<start:<> expiration:<wall_time:1765988950077331053 > replica:<node_id:1 store_id:1 replica_id:1 type:VOTER_FULL > deprecated_start_stasis:<wall_time:1765988950077331053 > proposed_ts:<wall_time:1765988944077331053 > sequence:1 acquisition_type:Request min_expiration:<> >  {Timestamp:1765988944.262002629,0 TimestampFromServerClock:<nil> Now:0,0 Replica:(n0,s0):? RangeID:81 UserPriority:normal Txn:<nil> ReadConsistency:CONSISTENT RoutingPolicy:LEASEHOLDER WaitPolicy:Block LockTimeout:0s MaxSpanRequestKeys:0 TargetBytes:0 WholeRowsOfSize:0 AllowEmpty:false DistinctSpans:false AsyncConsensus:false CanForwardReadTimestamp:false GatewayNodeID:0 ClientRangeInfo:{DescriptorGeneration:0 LeaseSequence:0 ClosedTimestampPolicy:LAG_BY_CLUSTER_SETTING ExplicitlyRequested:false} BoundedStaleness:<nil> TraceInfo:<nil> IndexFetchSpec:<nil> ReturnElasticCPUResumeSpans:false ProfileLabels:[] AmbiguousReplayProtection:false ConnectionClass:default ProxyRangeInfo:<nil> WriteOptions:<nil> DeadlockTimeout:0s HasBufferedAllPrecedingWrites:false IsReverse:false}
    replica_rankings_test.go:444: evaluated [logtags=]: *kvpb.LeaseInfoRequest on /Table/Max: header:<key:"\372" >  {Timestamp:1765988944.262738726,0 TimestampFromServerClock:<nil> Now:1765988944.262738726,0 Replica:(n1,s1):1 RangeID:81 UserPriority:normal Txn:<nil> ReadConsistency:INCONSISTENT RoutingPolicy:NEAREST WaitPolicy:Block LockTimeout:0s MaxSpanRequestKeys:0 TargetBytes:0 WholeRowsOfSize:0 AllowEmpty:false DistinctSpans:false AsyncConsensus:false CanForwardReadTimestamp:false GatewayNodeID:1 ClientRangeInfo:{DescriptorGeneration:1 LeaseSequence:1 ClosedTimestampPolicy:LAG_BY_CLUSTER_SETTING ExplicitlyRequested:false} BoundedStaleness:<nil> TraceInfo:<nil> IndexFetchSpec:<nil> ReturnElasticCPUResumeSpans:false ProfileLabels:[] AmbiguousReplayProtection:false ConnectionClass:default ProxyRangeInfo:<nil> WriteOptions:<nil> DeadlockTimeout:0s HasBufferedAllPrecedingWrites:false IsReverse:false}
    testcluster.go:1243: lease is now of type: LeaseLeader
    replica_rankings_test.go:536: test #1
    replica_rankings_test.go:444: evaluated [logtags=]: *kvpb.GetRequest on �000000000: header:<key:"\372000000000" > expect_exclusion_since:<>  {Timestamp:1765988944.263133468,0 TimestampFromServerClock:1765988944.263133468,0 Now:1765988944.263106429,0 Replica:(n1,s1):1 RangeID:81 UserPriority:normal Txn:<nil> ReadConsistency:CONSISTENT RoutingPolicy:LEASEHOLDER WaitPolicy:Block LockTimeout:0s MaxSpanRequestKeys:0 TargetBytes:0 WholeRowsOfSize:0 AllowEmpty:false DistinctSpans:false AsyncConsensus:false CanForwardReadTimestamp:false GatewayNodeID:1 ClientRangeInfo:{DescriptorGeneration:1 LeaseSequence:1 ClosedTimestampPolicy:LAG_BY_CLUSTER_SETTING ExplicitlyRequested:false} BoundedStaleness:<nil> TraceInfo:<nil> IndexFetchSpec:<nil> ReturnElasticCPUResumeSpans:false ProfileLabels:[] AmbiguousReplayProtection:false ConnectionClass:default ProxyRangeInfo:<nil> WriteOptions:<nil> DeadlockTimeout:0s HasBufferedAllPrecedingWrites:false IsReverse:false}
    replica_rankings_test.go:209: 
        	Error Trace:	pkg/kv/kvserver/replica_rankings_test.go:209
        	            				pkg/kv/kvserver/replica_rankings_test.go:564
        	Error:      	Max difference between 0 and 85 allowed is 4, but difference was -85
        	Test:       	TestReadLoadMetricAccounting
    panic.go:615: -- test log scope end --
test logs left over in: /artifacts/tmp/_tmp/645d36459c8d7b7939924714a555a08a/logTestReadLoadMetricAccounting564952480
--- FAIL: TestReadLoadMetricAccounting (0.71s)
```
<details><summary>Help</summary>
<p>

See also: [How To Investigate a Go Test Failure \(internal\)](https://cockroachlabs.atlassian.net/l/c/HgfXfJgM)
</p>
</details>
/cc @cockroachdb/kv-triage
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*TestReadLoadMetricAccounting.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/bazci/githubpost/issues)

</sub>

Jira issue: CRDB-58004

### PR DESCRIPTION
**Pull request by tbg**
`TestReadLoadMetricAccounting` has a history of flaking due to lease-related writes interfering with load metric measurements.

Issue #141716 (and #141586) identified the same failure signature:
```
Error: Max difference between 0 and 85 allowed is 4, but difference was -85
```

The root cause was identified by @pav-kv: an "unexpected" leader lease upgrade write was interfering with the test's write bytes measurements. PR #141843 added `tc.MaybeWaitForLeaseUpgrade()` to wait for lease upgrades before starting measurements.

**The fix from #141843 IS present** in the failing SHA. However, the test still flaked with the same error signature (85 write bytes when expecting 0).

The logs show:
1. AddSSTableRequest evaluated (test setup)
2. Many LeaseInfoRequest polls (from MaybeWaitForLeaseUpgrade)
3. RequestLeaseRequest (the lease upgrade write)
4. More LeaseInfoRequest polls
5. "lease is now of type: LeaseLeader" - **upgrade complete**
6. "test #1" - test loop begins
7. GetRequest evaluated (the actual test request)
8. **Assertion fails** - 85 write bytes observed

The race condition is subtle: `MaybeWaitForLeaseUpgrade()` waits until `FindRangeLeaseEx()` reports the lease is upgraded, but it does **not** guarantee that the write bytes have been recorded to load stats. This is because stats are recorded "awkwardly late" on the client goroutine (`SendWithWriteBytes`).

The fix:
1. Wraps each test case iteration in `SucceedsSoon`
2. Resets load stats, sends the request, checks results
3. If any stat doesn't match (due to background activity like lease upgrades), returns an error to trigger retry
4. Adds a comment noting that test cases must be idempotent (they are—all reads)

## Related Issues/PRs

| Issue/PR | Status | Relevance |
|----------|--------|-----------|
| #159719 | OPEN | Current failure |
| #141716 | CLOSED | Duplicate, Feb 2025 |
| #141586 | CLOSED | Original issue, Feb 2025 |
| #141843 | MERGED | Deflake attempt (wait for lease upgrade) |
| #141599 | MERGED | Added logging to help debug |
| #141905 | CLOSED | Duplicate |
| #134799 | CLOSED | Older occurrence |

This is more robust than trying to synchronize with specific background operations because it handles **any** source of interference, not just lease upgrades.

Epic: none
Closes #159719.

### CODE REVIEW

File: pkg/kv/kvserver/replica_rankings_test.go [hunk 1]
```diff
@@ -534,35 +508,42 @@ func TestReadLoadMetricAccounting(t *testing.T) {
...
+			readBytesAfter := repl.loadStats.TestingGetSum(load.ReadBytes)
+			writeBytesAfter := repl.loadStats.TestingGetSum(load.WriteBytes)
 
-		assertGreaterThanInDelta(t, testCase.expectedRQPS, requestsAfter, epsilonAllowed)
-		assertGreaterThanInDelta(t, testCase.expectedWPS, writesAfter, epsilonAllowed)
-		assertGreaterThanInDelta(t, testCase.expectedRPS, readsAfter, epsilonAllowed)
-		assertGreaterThanInDelta(t, testCase.expectedWBPS, writeBytesAfter, epsilonAllowed)
-		assertGreaterThanInDelta(t, testCase.expectedRBPS, readBytesAfter, epsilonAllowed)
+			// Check write stats first since that's where interference shows up.
+			if writesAfter < testCase.expectedWPS || writesAfter > testCase.expectedWPS+epsilonAllowed {
```
Comment (pav-kv) [inline pkg/kv/kvserver/replica_rankings_test.go:530]: How about making the helper return an error:

```golang
if err := assertEqApprox(testCase.expectedRQPS, requestsAfter, epsilonAllowed); err != nil {
	return errors.Wrapf(err, "writeKeys")
}
```

**Review by pav-kv — APPROVED** [review]

File: pkg/kv/kvserver/replica_rankings_test.go (hunk 1 above)
Comment (tbg) [reply pkg/kv/kvserver/replica_rankings_test.go:530]: Not a bad idea, but not worth my context switch + turnaround on PR.

**Comment by tbg** [comment]
bors r+

Not sure what's wrong with the pull_request build - looks like an infra problem. Asked [here](https://cockroachlabs.slack.com/archives/CJ0H8Q97C/p1766142896171309)
