### PR TITLE
changefeedccl: increase timeout for test making many tables

### LINKED ISSUE #152654: roachtest: cdc/multi-table-pts-benchmark/num-tables=50000 failed
roachtest.cdc/multi-table-pts-benchmark/num-tables=50000 [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyAzureBazel/20402228?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyAzureBazel/20402228?buildTab=artifacts#/cdc/multi-table-pts-benchmark/num-tables=50000) on master @ [91b3eee0f04549bf73bf1d35cc2da8a258ff5324](https://github.com/cockroachdb/cockroach/commits/91b3eee0f04549bf73bf1d35cc2da8a258ff5324):

```
(test_runner.go:1450).runTest: test timed out (1h0m0s)
test artifacts and logs in: /artifacts/cdc/multi-table-pts-benchmark/num-tables=50000/run_1
```

Parameters:
 - <code>arch=amd64</code>
 - <code>cloud=azure</code>
 - <code>coverageBuild=false</code>
 - <code>cpu=16</code>
 - <code>encrypted=false</code>
 - <code>fs=ext4</code>
 - <code>localSSD=true</code>
 - <code>runtimeAssertionsBuild=false</code>
 - <code>ssd=0</code>
<details><summary>Help</summary>
<p>

See: [roachtest README](https://github.com/cockroachdb/cockroach/blob/master/pkg/cmd/roachtest/README.md)

See: [How To Investigate \(internal\)](https://cockroachlabs.atlassian.net/l/c/SSSBr8c7)

_Grafana is not yet available for azure clusters_</p>
</details>
/cc @cockroachdb/cdc
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*cdc/multi-table-pts-benchmark/num-tables=50000.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/bazci/githubpost/issues)

</sub>

Jira issue: CRDB-53962

### LINKED ISSUE #152962: roachtest: cdc/multi-table-pts-benchmark/per-table-pts=false/num-tables=5000/num-ranges=10 failed
roachtest.cdc/multi-table-pts-benchmark/per-table-pts=false/num-tables=5000/num-ranges=10 [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/20427879?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/20427879?buildTab=artifacts#/cdc/multi-table-pts-benchmark/per-table-pts=false/num-tables=5000/num-ranges=10) on master @ [c75f1e29cd50bf638c699f23ff80eeccd9a63598](https://github.com/cockroachdb/cockroach/commits/c75f1e29cd50bf638c699f23ff80eeccd9a63598):

```
(cdc.go:4653).func2: observed value for metric changefeed_stage_pts_create_latency over threshold. observedValue: 26463840.000000, threshold: 25000000.000000
(cdc.go:400).Close: error shutting down prometheus/grafana: context canceled
test artifacts and logs in: /artifacts/cdc/multi-table-pts-benchmark/per-table-pts=false/num-tables=5000/num-ranges=10/cpu_arch=arm64/run_1
```

Parameters:
 - <code>arch=arm64</code>
 - <code>cloud=gce</code>
 - <code>coverageBuild=false</code>
 - <code>cpu=16</code>
 - <code>encrypted=false</code>
 - <code>fs=ext4</code>
 - <code>localSSD=false</code>
 - <code>runtimeAssertionsBuild=false</code>
 - <code>ssd=0</code>
<details><summary>Help</summary>
<p>

See: [roachtest README](https://github.com/cockroachdb/cockroach/blob/master/pkg/cmd/roachtest/README.md)

See: [How To Investigate \(internal\)](https://cockroachlabs.atlassian.net/l/c/SSSBr8c7)

See: [Grafana](https://go.crdb.dev/roachtest-grafana/teamcity-20427879/cdc-multi-table-pts-benchmark-per-table-pts-false-num-tables-50/1756977916453/1756980358792)

</p>
</details>
/cc @cockroachdb/cdc
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*cdc/multi-table-pts-benchmark/per-table-pts=false/num-tables=5000/num-ranges=10.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/bazci/githubpost/issues)

</sub>

Jira issue: CRDB-54130

### PR DESCRIPTION
**Pull request by aerfrei**
This test timed out in CI while trying to create 50000 tables.
After an hour, it created about 40,000. Adding another hour
should be enough time to finish creation and run the 20 minute
workload.

We also saw a test failure where this pts management metric
came in slightly above the threshold of 25ms, so we raise
that to 30ms.

Epic: none
Fixes: #152654
Fixes: #152962
Release note: None

### CODE REVIEW

**Review by log-head — APPROVED** [review]
lgtm!

File: pkg/cmd/roachtest/tests/cdc.go [hunk 1]
```diff
@@ -2912,12 +2912,13 @@ func registerCDC(r registry.Registry) {
 
 	for _, perTablePTS := range []bool{false, true} {
 		for _, config := range []struct {
-			numTables int
-			numRanges int
+			numTables    int
+			numRanges    int
+			timeoutHours int
```
Comment (andyyang890) [inline pkg/cmd/roachtest/tests/cdc.go:2917]: nit: make the field type `time.Duration` directly so that the unit is apparent from the value alone

i.e.
```
diff --git a/pkg/cmd/roachtest/tests/cdc.go b/pkg/cmd/roachtest/tests/cdc.go
index 7f2e87735cf..33ae6f35863 100644
--- a/pkg/cmd/roachtest/tests/cdc.go
+++ b/pkg/cmd/roachtest/tests/cdc.go
@@ -2914,10 +2914,11 @@ func registerCDC(r registry.Registry) {
                for _, config := range []struct {
                        numTables int
                        numRanges int
+                       timeout   time.Duration
                }{
-                       {numTables: 500, numRanges: 10},
-                       {numTables: 5000, numRanges: 10},
-                       {numTables: 50000, numRanges: 1}, // Splitting tables into ranges slows down test setup at this scale
+                       {numTables: 500, numRanges: 10, timeout: time.Hour},
+                       {numTables: 5000, numRanges: 10, timeout: time.Hour},
+                       {numTables: 50000, numRanges: 1, timeout: 2 * time.Hour}, // Splitting tables into ranges slows down test setup at this scale
                } {
                        r.Add(registry.TestSpec{
                                Name:             fmt.Sprintf("cdc/multi-table-pts-benchmark/per-table-pts=%t/num-tables=%d/num-ranges=%d", perTablePTS, config.numTables, config.numRanges),
@@ -2926,7 +2927,7 @@ func registerCDC(r registry.Registry) {
                                Cluster:          r.MakeClusterSpec(4, spec.CPU(16), spec.WorkloadNode()),
                                CompatibleClouds: registry.AllClouds,
                                Suites:           registry.Suites(registry.Nightly),
-                               Timeout:          1 * time.Hour,
+                               Timeout:          config.timeout,
                                Run: func(ctx context.Context, t test.Test, c cluster.Cluster) {
                                        params := multiTablePTSBenchmarkParams{
                                                numTables:   config.numTables,
```

**Review by andyyang890 — APPROVED** [review]
Left a comment for posterity (no need to cancel the merge)
