### PR TITLE
workload: handle new RESTORE results when importing fixtures

### LINKED ISSUE #137671: roachtest: copy/bank/rows=100000,nodes=5,txn=true failed
**Note:** This build has runtime assertions enabled. If the same failure was hit in a run without assertions enabled, there should be a similar failure without this message. If there isn&#39;t one, then this failure is likely due to an assertion violation or (assertion) timeout.

roachtest.copy/bank/rows=100000,nodes=5,txn=true [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/18228286?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/18228286?buildTab=artifacts#/copy/bank/rows=100000,nodes=5,txn=true) on master @ [51693691ed763f700dd06fa2d001cce1ffd42203](https://github.com/cockroachdb/cockroach/commits/51693691ed763f700dd06fa2d001cce1ffd42203):

```
(cluster.go:2481).Run: full command output in run_093953.293662482_n1_cockroach-workload-f.log: COMMAND_PROBLEM: exit status 1
(monitor.go:149).Wait: monitor failure: monitor user task failed: t.Fatal() was called
test artifacts and logs in: /artifacts/copy/bank/rows=100000_nodes=5_txn=true/run_1
```

Parameters:
 - <code>arch=amd64</code>
 - <code>cloud=gce</code>
 - <code>coverageBuild=false</code>
 - <code>cpu=4</code>
 - <code>encrypted=false</code>
 - <code>fs=ext4</code>
 - <code>localSSD=true</code>
 - <code>metamorphicLeases=epoch</code>
 - <code>runtimeAssertionsBuild=true</code>
 - <code>ssd=0</code>
<details><summary>Help</summary>
<p>

See: [roachtest README](https://github.com/cockroachdb/cockroach/blob/master/pkg/cmd/roachtest/README.md)

See: [How To Investigate \(internal\)](https://cockroachlabs.atlassian.net/l/c/SSSBr8c7)

See: [Grafana](https://go.crdb.dev/roachtest-grafana/teamcity-18228286/copy-bank-rows-100000-nodes-5-txn-true/1734514774444/1734514944154)

</p>
</details>
/cc @cockroachdb/kv-triage
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*copy/bank/rows=100000,nodes=5,txn=true.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/bazci/githubpost/issues)

</sub>

Jira issue: CRDB-45692

### PR DESCRIPTION
**Pull request by DarrylWong**
In 03e24093c9b39f6fad45e4e2d972cdab3abe83ab, two columns were removed from the RESTORE results. This change supports handling this. It also removes logging around bytes restored as it is no longer returned.

Fixes: #137671
Release note: none
Epic: none

### CODE REVIEW

File: pkg/ccl/workloadccl/fixture.go [hunk 1]
```diff
@@ -647,40 +646,44 @@ func RestoreFixture(
 			}
 			if len(resCols) == 7 {
 				if err := res.Scan(
-					&discard, &discard, &discard, &rows, &index, &discard, &tableBytes,
+					&discard, &discard, &discard, &rows, &index, &discard, &discard,
+				); err != nil {
+					return err
+				}
+			} else if len(resCols) == 6 {
```
Comment (srosenberg) [inline pkg/ccl/workloadccl/fixture.go:653]: This is the expected result size going forward, right? Then, it seems the above case would benefit from a version gate, since we presumably don't want to keep backward compatibility indefinitely? 

CC @cockroachdb/disaster-recovery

Comment (DarrylWong) [reply pkg/ccl/workloadccl/fixture.go:653]: It's to preserve backwards compatibility so you can use `cockroach workload` built on master to load data into an older version. This is useful for e.g. mixed version tests since figuring out the matching binary needed is cumbersome and instead you can just use master.

That being said, only two tests use `fixtures load` and neither are mixed version tests. If we want to remove it we won't break any tests and backwards compatibility for workload doesn't appear to be a hard rule.

Comment (srosenberg) [reply pkg/ccl/workloadccl/fixture.go:653]: > It's to preserve backwards compatibility so you can use cockroach workload built on master to load data into an older version. 

Interesting, I didn't realize we were relying on that. That's inherently error-prone. I get the convenience aspect, but sooner or later we'll run into other compatibility issues. I think we should switch to using the same versioned binary (for workloads) in mixed version tests.

> If we want to remove it we won't break any tests and backwards compatibility for workload doesn't appear to be a hard rule.

The side-effect of adding special cases (without version gates) for backward compatibility is they tend to pollute the rest of the code; i.e., maintenance over time gets trickier since 6 months from now it won't be as clear as to why there is a special case there.

Comment (DarrylWong) [reply pkg/ccl/workloadccl/fixture.go:653]: > That's inherently error-prone. I get the convenience aspect, but sooner or later we'll run into other compatibility issues

Agreed, [we've already run into compatibility issues due to newly added flags](https://github.com/cockroachdb/cockroach/blame/87b463a09f714af53270f4307d38a01fc76cebf6/pkg/cmd/roachtest/tests/admission_control_elastic_mixed_version.go#L78-L82). We should have the helper expose the binary path of the currently running version.

>I think we should switch to using the same versioned binary 

Need to think about this more, but some tests spin up a workload (e.g. tpcc) in the background, and have it run throughout the entire test uninterrupted.

> The side-effect of adding special cases (without version gates) for backward compatibility is they tend to pollute the rest of the code

Sounds like we're leaning towards removing the backwards compatibility checks then? If so I'm for it, makes it easier for me too :)

Comment (srosenberg) [reply pkg/ccl/workloadccl/fixture.go]: > Need to think about this more, but some tests spin up a workload (e.g. tpcc) in the background, and have it run throughout the entire test uninterrupted.

Right. It's definitely a convenience feature to keep pumping some form of background traffic, continuously. Synchronizing workload binaries with cockroach binaries seems tricky; would require a non-trivial change to the mixedversion framework.

**Review by srosenberg — APPROVED** [review]
LGTM, modulo commit message that's out of sync with the latest change.

**Comment by DarrylWong** [comment]
TFTR!

bors r=srosenberg
