### PR TITLE
streamingest,replicationtestutils: deflake a couple of c2c tests

### LINKED ISSUE #86206: ccl/streamingccl/streamingest: TestTenantStreamingMultipleNodes failed
ccl/streamingccl/streamingest.TestTenantStreamingMultipleNodes [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_StressBazel/6108453?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_StressBazel/6108453?buildTab=artifacts#/) on master @ [f4042d47fa8062a612c38d4696eb6bee9cee7c21](https://github.com/cockroachdb/cockroach/commits/f4042d47fa8062a612c38d4696eb6bee9cee7c21):

```
=== RUN   TestTenantStreamingMultipleNodes
    test_log_scope.go:162: test logs captured to: /artifacts/tmp/_tmp/045fecfe9e18c9da6f776a53d446f2c5/logTestTenantStreamingMultipleNodes1644022259
    test_log_scope.go:80: use -show-logs to present logs inline
    stream_replication_e2e_test.go:286: error executing '
          CREATE TABLE d.scattered (key INT PRIMARY KEY);
          INSERT INTO d.scattered (key) SELECT * FROM generate_series(1, 1000);
          ALTER TABLE d.scattered SPLIT AT (SELECT * FROM generate_series(20, 980, 20));
          ALTER TABLE d.scattered SCATTER;
          ': dial tcp 127.0.0.1:34645: connect: connection refused
    panic.go:500: -- test log scope end --
--- FAIL: TestTenantStreamingMultipleNodes (1191.45s)
```
<p>Parameters: <code>TAGS=bazel,gss,deadlock</code>
</p>
<details><summary>Help</summary>
<p>

See also: [How To Investigate a Go Test Failure \(internal\)](https://cockroachlabs.atlassian.net/l/c/HgfXfJgM)
</p>
</details>
/cc @cockroachdb/tenant-streaming
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*TestTenantStreamingMultipleNodes.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)
</sub>

Jira issue: CRDB-18631

### LINKED ISSUE #86227: ccl: TestTenantStreamingUnavailableStreamAddress failed
Test flake?  https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_BazelEssentialCi/6114999?showRootCauses=true&expandBuildChangesSection=true&expandBuildProblemsSection=true&expandBuildDeploymentsSection=true&expandBuildTestsSection=true

```
=== RUN   TestTenantStreamingUnavailableStreamAddress
    test_log_scope.go:162: test logs captured to: /artifacts/tmp/_tmp/90c1b75d835f45b8488807abb5b1092d/logTestTenantStreamingUnavailableStreamAddress2815750504
    test_log_scope.go:80: use -show-logs to present logs inline
    stream_replication_e2e_test.go:805: condition failed to evaluate within 2m0s: expected job status succeeded, but got paused
    panic.go:482: -- test log scope end --
--- FAIL: TestTenantStreamingUnavailableStreamAddress (209.10s)
```

Jira issue: CRDB-18644

Epic CRDB-11732

### LINKED ISSUE #94738: ccl/streamingccl/streamingest: TestTenantStreamingUnavailableStreamAddress failed
ccl/streamingccl/streamingest.TestTenantStreamingUnavailableStreamAddress [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_StressBazel/8193251?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_StressBazel/8193251?buildTab=artifacts#/) on master @ [d1233022fc2f67a3901c0be08ec71abb13b1e8fe](https://github.com/cockroachdb/cockroach/commits/d1233022fc2f67a3901c0be08ec71abb13b1e8fe):

```
=== RUN   TestTenantStreamingUnavailableStreamAddress
    test_log_scope.go:161: test logs captured to: /artifacts/tmp/_tmp/90c1b75d835f45b8488807abb5b1092d/logTestTenantStreamingUnavailableStreamAddress2661862507
    test_log_scope.go:79: use -show-logs to present logs inline
    replication_stream_e2e_test.go:542: 
        	Error Trace:	/home/roach/.cache/bazel/_bazel_roach/c5a4e7d36696d9cd970af2045211a7df/sandbox/processwrapper-sandbox/572/execroot/com_github_cockroachdb_cockroach/bazel-out/k8-fastbuild/bin/pkg/ccl/streamingccl/streamingest/streamingest_test_/streamingest_test.runfiles/com_github_cockroachdb_cockroach/pkg/ccl/streamingccl/streamingest/replication_stream_e2e_test.go:542
        	Error:      	[]string{"postgres://root@127.0.0.1:42275?sslcert=%2Fartifacts%2Ftmp%2F_tmp%2F90c1b75d835f45b8488807abb5b1092d%2FTestTenantStreamingUnavailableStreamAddress1092229631%2Fcert&sslkey=%2Fartifacts%2Ftmp%2F_tmp%2F90c1b75d835f45b8488807abb5b1092d%2FTestTenantStreamingUnavailableStreamAddress1092229631%2Fkey&sslmode=verify-full&sslrootcert=%2Fartifacts%2Ftmp%2F_tmp%2F90c1b75d835f45b8488807abb5b1092d%2FTestTenantStreamingUnavailableStreamAddress1092229631%2Fca", "postgres://root@127.0.0.1:46117?sslcert=%2Fartifacts%2Ftmp%2F_tmp%2F90c1b75d835f45b8488807abb5b1092d%2FTestTenantStreamingUnavailableStreamAddress1092229631%2Fcert&sslkey=%2Fartifacts%2Ftmp%2F_tmp%2F90c1b75d835f45b8488807abb5b1092d%2FTestTenantStreamingUnavailableStreamAddress1092229631%2Fkey&sslmode=verify-full&sslrootcert=%2Fartifacts%2Ftmp%2F_tmp%2F90c1b75d835f45b8488807abb5b1092d%2FTestTenantStreamingUnavailableStreamAddress1092229631%2Fca"} does not contain "postgres://root@127.0.0.1:38989?sslcert=%2Fartifacts%2Ftmp%2F_tmp%2F90c1b75d835f45b8488807abb5b1092d%2FTestTenantStreamingUnavailableStreamAddress1092229631%2Fcert&sslkey=%2Fartifacts%2Ftmp%2F_tmp%2F90c1b75d835f45b8488807abb5b1092d%2FTestTenantStreamingUnavailableStreamAddress1092229631%2Fkey&sslmode=verify-full&sslrootcert=%2Fartifacts%2Ftmp%2F_tmp%2F90c1b75d835f45b8488807abb5b1092d%2FTestTenantStreamingUnavailableStreamAddress1092229631%2Fca"
        	Test:       	TestTenantStreamingUnavailableStreamAddress
    panic.go:522: -- test log scope end --
test logs left over in: /artifacts/tmp/_tmp/90c1b75d835f45b8488807abb5b1092d/logTestTenantStreamingUnavailableStreamAddress2661862507
--- FAIL: TestTenantStreamingUnavailableStreamAddress (51.70s)
```
<p>Parameters: <code>TAGS=bazel,gss</code>
</p>
<details><summary>Help</summary>
<p>

See also: [How To Investigate a Go Test Failure \(internal\)](https://cockroachlabs.atlassian.net/l/c/HgfXfJgM)
</p>
</details>
/cc @cockroachdb/tenant-streaming
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*TestTenantStreamingUnavailableStreamAddress.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)
</sub>

Jira issue: CRDB-23109

### PR DESCRIPTION
**Pull request by lidorcarmel**
TestTenantStreamingMultipleNodes and
TestTenantStreamingUnavailableStreamAddress were flaky, and fixed here.

I also tried enabling those in under --race, but failed, running with multiple nodes hits the 15 minutes deadline under race.

Changed a few small things:
- we create 2 test clusters for c2c (clearly..) which was done sequentially. Now it's parallelized (speeds up the test a bit).
- we have 50 ranges that we were hoping to scatter over 3 nodes, it should be enough but rarely all leases are on a single node. Increasing this number doesn't help, instead, this pr changed the number of nodes on the source cluster from 3 to 4. This doesn't guarantee success but looks like it should reduce flakiness significantly (I cannot repro this failure locally under stress).
- broke down the CREAT/INSERT/SPLIT/SCATTER command - only to make it easy to see where the issues are and where the time is spent.
- dropped the check in CreateScatteredTable() because we will always have leases on all 3 nodes, the verification that we need is to have the leases of the scattered table spread, not any lease. This check was misleading and therefore removed.

Epic: none
Fixes: #86227
Fixes: #94738
Fixes: #86206

Release note: None

### CODE REVIEW

File: pkg/ccl/streamingccl/replicationtestutils/testutils.go [hunk 1]
```diff
@@ -167,6 +168,28 @@ func (c *TenantStreamingClusters) WaitUntilHighWatermark(
 	})
 }
 
+// Similar to jobutils.WaitForJobToSucceed, but with a longer deadline.
+func waitForJobToSucceedWithin10Min(t testing.TB, db *sqlutils.SQLRunner, jobID jobspb.JobID) {
+	t.Helper()
+	testutils.SucceedsWithin(t, func() error {
+		var status string
+		var payloadBytes []byte
```
Comment (msbutler) [inline pkg/ccl/streamingccl/replicationtestutils/testutils.go:176]: I’m a bit worried that we have to wait 10 minutes for cutover to finish in a unit test. Did you get a sense on why we need this much time? Is it replication lag?

File: pkg/ccl/streamingccl/streamingest/replication_stream_e2e_test.go [hunk 2]
```diff
@@ -644,9 +644,12 @@ func TestTenantStreamingMultipleNodes(t *testing.T) {
 		},
 	}
 
+	args.SrcClusterSettings[`server.sqlliveness.ttl`] = `'5m'`
```
Comment (msbutler) [inline pkg/ccl/streamingccl/streamingest/replication_stream_e2e_test.go:647]: could you explain why this helps?

**Review by msbutler — COMMENTED** [review]
thanks for doing this! Left two high level comments, that perhaps you, me and steven should discuss.

File: pkg/ccl/streamingccl/replicationtestutils/testutils.go (hunk 1 above)
Comment (lidorcarmel) [reply pkg/ccl/streamingccl/replicationtestutils/testutils.go:176]: this fails under stress and race, and in that environment anything can be starved for a while. this unit test is not a performance test so I'm ok with a few more minutes.
that said, if we can make the test run faster then that's always good.. I think right now it runs under 30 seconds (not under race), which is not too bad.

File: pkg/ccl/streamingccl/streamingest/replication_stream_e2e_test.go (hunk 2 above)
Comment (lidorcarmel) [reply pkg/ccl/streamingccl/streamingest/replication_stream_e2e_test.go]: no :) I saw just once the connection being killed so I increased the ttl, but this was when I tried running this test under race, and we're still skipping under race so it's not really needed. BTW even if we want it this needs to be within `CreateTenantStreamingClusters`.

File: pkg/ccl/streamingccl/replicationtestutils/testutils.go (hunk 1 above)
Comment (stevendanna) [reply pkg/ccl/streamingccl/replicationtestutils/testutils.go:176]: Something we do in other places is set a higher timeout if we are under race using util.RaceEnabled. Perhaps something like:

```go
timeout := 2*time.Minutes
if util.RaceEnabled || skip.NightlyStress() {
    timeout = timeout * 5
}
```

Also, I don't mind too much, but if it were me I would probably export something like `WaitForJobToHaveStatus(testing.TB, *sqlutils.SQLRunner, jobspb.JobID, jobs.Status, time.Duration)` from jobutils and then call that here.

File: pkg/ccl/streamingccl/streamingest/replication_stream_e2e_test.go (hunk 2 above)
Comment (lidorcarmel) [reply pkg/ccl/streamingccl/streamingest/replication_stream_e2e_test.go]: the default is 40 seconds, this change (that was reverted) was increasing that ttl. Maybe I'm missing something?
and BTW, if we need to bump this we should only do this under race as you said in the other comment..

File: pkg/ccl/streamingccl/replicationtestutils/testutils.go (hunk 1 above)
Comment (lidorcarmel) [reply pkg/ccl/streamingccl/replicationtestutils/testutils.go:176]: I didn't want to add this to jobutils because I didn't want others to use it much. But doing this for stress/race only makes sense.

Anyway, I tried stressing it now and it doesn't fail with 2 minutes so I'll revert this for now and keep an eye on it in ci. This might have been another fix I did for running under race, before I gave up on it and just made it run under stress only. Or maybe it will fail again.. stressing locally is not super reliable.

BTW, if we think it's important to get this to run under race I can try that again, I have no intuition about what is expected or not expected to run well under race. But that can be a separate pr.

Hopefully this makes sense!

**Comment by lidorcarmel** [comment]
thanks both! PTAL.

**Review by msbutler — APPROVED** [review]
The smaller scope looks good to me. Let's see what happens!

**Comment by lidorcarmel** [comment]
TFTR!
bors r+

**Comment by lidorcarmel** [comment]
blathers backport 23.1
