### PR TITLE
roachtest: fix benchmark failing tests

### LINKED ISSUE #135393: roachtest: admission-control/elastic-io failed
roachtest.admission-control/elastic-io [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/17791386?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/17791386?buildTab=artifacts#/admission-control/elastic-io) on master @ [e83bc46aa42f2476b4b11b9703b8038c660dc980](https://github.com/cockroachdb/cockroach/commits/e83bc46aa42f2476b4b11b9703b8038c660dc980):

```
(cluster.go:2456).Run: full command output in run_064637.959171654_n2_cockroach-workload-r.log: COMMAND_PROBLEM: exit status 4
(test_runner.go:1356).runTest: test timed out (1h0m0s)
test artifacts and logs in: /artifacts/admission-control/elastic-io/cpu_arch=arm64/run_1
```

Parameters:
 - <code>arch=arm64</code>
 - <code>cloud=gce</code>
 - <code>coverageBuild=false</code>
 - <code>cpu=8</code>
 - <code>encrypted=false</code>
 - <code>fs=ext4</code>
 - <code>localSSD=false</code>
 - <code>metamorphicLeases=leader</code>
 - <code>runtimeAssertionsBuild=false</code>
 - <code>ssd=0</code>
<details><summary>Help</summary>
<p>

See: [roachtest README](https://github.com/cockroachdb/cockroach/blob/master/pkg/cmd/roachtest/README.md)

See: [How To Investigate \(internal\)](https://cockroachlabs.atlassian.net/l/c/SSSBr8c7)

See: [Grafana](https://go.crdb.dev/roachtest-grafana/teamcity-17791386/admission-control-elastic-io/1731739543806/1731743292370)

</p>
</details>
/cc @cockroachdb/storage
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*admission-control/elastic-io.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/bazci/githubpost/issues)

</sub>

Jira issue: CRDB-44494

### PR DESCRIPTION
**Pull request by sambhav-jain-16**
This change intends to fix 3 failures detected in benchmark runs after https://github.com/cockroachdb/cockroach/pull/133035
1. `admission-control/elastic-io` due to one wrong flag.
2. `tpcc/headroom/n4cpu16` due to wrong passing of labels in case of openmetrics, removed suite label since it is not required.
3. `tpccbench/*` erroring out with nil pointer error in case of openmetrics, reverted the changes in this PR. Will fix in a different PR.

Epic: none
Fixes: https://github.com/cockroachdb/cockroach/issues/135393

### CODE REVIEW

File: pkg/cmd/roachtest/clusterstats/exporter.go [hunk 1]
```diff
@@ -413,7 +413,6 @@ func GetOpenmetricsLabelMap(
 	defaultMap := map[string]string{
 		"cloud": c.Cloud().String(),
 		"owner": string(t.Spec().(*registry.TestSpec).Owner),
-		"suite": t.Spec().(*registry.TestSpec).Suites.String(),
```
Comment (srosenberg) [inline pkg/cmd/roachtest/clusterstats/exporter.go:416]: Can you say more about this change? It's not immediately clear why it's needed by this hotfix.

**Review by srosenberg — APPROVED** [review]

File: pkg/cmd/roachtest/clusterstats/exporter.go (hunk 1 above)
Comment (sambhav-jain-16) [reply pkg/cmd/roachtest/clusterstats/exporter.go:416]: `tpcc/headroom/n4cpu16` started failing due to the following error.
```
 ./cockroach workload run tpcc   {pgurl:1-3} --duration 2h0m0s --histogram-export-format openmetrics --histograms perf/stats.om --openmetrics-labels cloud="gce",database="",duration="2h0m0s",owner="test-eng",ramp="5m0s",subtest_1="headroom",subtest_2="n4cpu16",suite="nightly,release_qualification",test="tpcc",test_run_id="teamcity-17804790",warehouses="875" --pprofport 33333 --prometheus-port 2112 --ramp 5m0s --warehouses 875
  |   | ```
  |   | stdout: <empty>
  |   | stderr:I241118 01:55:30.585513 1 workload/cli/run.go:665  [-] 1  random seed: 3344266357670910272
  |   | Error: error creating metrics exporter: invalid histogram label "release_qualification"
```
[link](https://teamcity.cockroachdb.com/repository/download/Cockroach_Roachtest_Openmetrics_Gce/17804790:id/tpcc/headroom/n4cpu16/run_1/artifacts.zip!/failure_1.log)

turns out, suites can be multiple values and this caused problems of a label with multiple values. Also, `suites` is not a necessary label so removed it in this change.

**Comment by sambhav-jain-16** [comment]
TFTR!

bors r=@srosenberg
