### PR TITLE
changefeedccl: deflake TestChangefeedContinuousTelemetryOnTermination

### LINKED ISSUE #143700: ccl/changefeedccl: TestChangefeedContinuousTelemetryOnTermination failed
ccl/changefeedccl.TestChangefeedContinuousTelemetryOnTermination [failed](https://tanzanite.cluster.engflow.com/invocations/default/4b4caeb2-0964-44f6-81ae-b79407262409?testReportRun=2&testReportShard=1&testReportAttempt=1#targets-Ly9wa2cvY2NsL2NoYW5nZWZlZWRjY2w6Y2hhbmdlZmVlZGNjbF90ZXN0) on release-25.1 @ [899f1e1a73780f9d12d1a4a61a5f82f2eb4ead94](https://github.com/cockroachdb/cockroach/commits/899f1e1a73780f9d12d1a4a61a5f82f2eb4ead94):

```
=== RUN   TestChangefeedContinuousTelemetryOnTermination
    test_log_scope.go:165: test logs captured to: outputs.zip/logTestChangefeedContinuousTelemetryOnTermination1644168868
    test_log_scope.go:76: use -show-logs to present logs inline
    changefeed_test.go:6411: -- test log scope end --
test logs left over in: outputs.zip/logTestChangefeedContinuousTelemetryOnTermination1644168868
--- FAIL: TestChangefeedContinuousTelemetryOnTermination (18.17s)
=== RUN   TestChangefeedContinuousTelemetryOnTermination/cloudstorage
    helpers_test.go:883: making server as secondary tenant
    helpers_test.go:962: making cloudstorage feed factory
    testfeed_test.go:301: creating external connection
    testfeed_test.go:304: ran create external connection
    helpers_test.go:1280: read message {{{1743329161533029297 changefeed_emitted_bytes} ‹CREATE CHANGEFEED FOR TABLE foo INTO 'external://testconn2199349612120145408' WITH OPTIONS (format = 'parquet')› external 1 no yes parquet 1059254308694753281} 637 1 86400000000000 false}
    helpers_test.go:1280: read message {{{1743329166801677541 changefeed_emitted_bytes} ‹CREATE CHANGEFEED FOR TABLE foo INTO 'external://testconn2199349612120145408' WITH OPTIONS (format = 'parquet')› external 1 no yes parquet 1059254308694753281} 0 0 86400000000000 true}
    helpers_test.go:1280: read message {{{1743329166777610387 changefeed_emitted_bytes} ‹CREATE CHANGEFEED FOR TABLE foo INTO 'external://testconn2199349612120145408' WITH OPTIONS (format = 'parquet')› external 1 no yes parquet 1059254308694753281} 645 2 86400000000000 false}
    helpers_test.go:1288: 
        	Error Trace:	pkg/ccl/changefeedccl/helpers_test.go:1288
        	            				pkg/testutils/soon.go:71
        	            				pkg/util/retry/retry.go:213
        	            				pkg/testutils/soon.go:77
        	            				pkg/testutils/soon.go:56
        	            				pkg/testutils/soon.go:38
        	            				pkg/ccl/changefeedccl/helpers_test.go:1272
        	            				pkg/ccl/changefeedccl/changefeed_test.go:6407
        	            				pkg/ccl/changefeedccl/helpers_test.go:1134
        	            				pkg/ccl/changefeedccl/helpers_test.go:1169
        	Error:      	Not equal: 
        	            	expected: true
        	            	actual  : false
        	Test:       	TestChangefeedContinuousTelemetryOnTermination/cloudstorage
    --- FAIL: TestChangefeedContinuousTelemetryOnTermination/cloudstorage (18.16s)
```

Parameters:
 - <code>attempt=1</code>
 - <code>race=true</code>
 - <code>run=2</code>
 - <code>shard=1</code>
<details><summary>Help</summary>
<p>

See also: [How To Investigate a Go Test Failure \(internal\)](https://cockroachlabs.atlassian.net/l/c/HgfXfJgM)
</p>
</details>
/cc @cockroachdb/cdc
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*TestChangefeedContinuousTelemetryOnTermination.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/bazci/githubpost/issues)

</sub>

Jira issue: CRDB-48998

### PR DESCRIPTION
**Pull request by KeithCh**
There was an attempt to deflake this test in #135961
but we were still seeing this occasionally.
This change expands on that attempt.

The main cause is from a transient KV server error
that occurs when we cancel a changefeed. The
error causes a new changefeed aggregator to
be started, which in turn creates a new
telemetryMetricsRecorder instance. Since the
lastEmitTime field in telemetryMetricsRecorder is
initialized to 0, it emits a
changefeed_emitted_bytes event at the very next
maybeFlushLogs() call. A counter is added to
detect when this transient error occurs, and 
prevents the second logger from emitting any 
logs.

Resolves #143700

Release note: None

### CODE REVIEW

**Comment by KeithCh** [comment]
Discussion items:
1. Does the resulting behavior from the error make sense? 
2. The changefeed_emitted_bytes timestamps in the telemetry logs are consistently out of order
whenever the transient error pops up, do we care about fixing this order? My vote is no since
this error rarely happens and only at termination.

File: pkg/ccl/changefeedccl/telemetry.go [hunk 1]
```diff
@@ -48,19 +48,22 @@ type telemetryLogger interface {
 }
 
 var _ telemetryLogger = (*periodicTelemetryLogger)(nil)
+var name atomic.Int32
```
Comment (aerfrei) [inline pkg/ccl/changefeedccl/telemetry.go:51]: What is this for? I'm not seeing where this is used

Comment (KeithCh) [reply pkg/ccl/changefeedccl/telemetry.go:51]: ah I used it for testing, let me take that out

File: pkg/ccl/changefeedccl/changefeed_test.go [hunk 2]
```diff
@@ -7209,6 +7209,19 @@ func TestChangefeedContinuousTelemetryOnTermination(t *testing.T) {
...
 		sqlDB.Exec(t, `INSERT INTO foo VALUES (2)`)
 		sqlDB.Exec(t, `INSERT INTO foo VALUES (3)`)
+
+		s.TestingKnobs.DistSQL.(*execinfra.TestingKnobs).Changefeed.(*TestingKnobs).OverrideContinuousTelemetryLastEmit =
+			func(lastEmitTime int64) int64 {
+				// If lastEmitTime == 0, we know that a new instance of the logger
+				// is created because we passed verifyLogsWithEmittedBytesAndMessages.
+				// We override this value to prevent the new logger from emitting an event when
+				// they call maybeFlushLogs().
+				if lastEmitTime == 0 {
```
Comment (aerfrei) [inline pkg/ccl/changefeedccl/changefeed_test.go:7219]: Still trying to wrap my head around this.

My understanding is that this test is flaky because sometimes (but not always) we create a new instance of the logger (on starting a new changefeed?), that logger is initialized with lastEmitTime == 0, which means that this logger will emit an event even though we only expect to emit one every 24hr.

Is that to say that it's possible in production for us to create a new logger and emit events more frequently than the 24hr interval?

Comment (KeithCh) [reply pkg/ccl/changefeedccl/changefeed_test.go:7219]: >My understanding is that this test is flaky because sometimes (but not always) we create a new instance of the logger (on starting a new changefeed?)

When we cancel the changefeed,  we get an error from the KV server that causes the change aggregator to [(re)start, which would create the new instance of the logger.](https://github.com/cockroachdb/cockroach/blob/e4fc9d0a3e7baddfb60d4a45ef5279db7aef3dec/pkg/ccl/changefeedccl/changefeed_processors.go#L361)

>Is that to say that it's possible in production for us to create a new logger and emit events more frequently than the 24hr interval?

I believe yes this is how it is for multi-node clusters, since each change aggregator would have their own logger (1--1 relationship). The test was failing because of a rare case where a single node went through 2 changefeed aggregators and thus 2 telemetry loggers.

@andyyang890 can you confirm the last point

**Comment by andyyang890** [comment]
> The main cause is from a transient KV server error
> that occurs when we cancel a changefeed.

Hmm this itself seems like a problem to me. I took a look at the logs from https://github.com/cockroachdb/cockroach/issues/143700#issue-2958839018 and the error message is:
```
W250330 10:06:06.644311 50924 ccl/changefeedccl/changefeed_stmt.go:1389 ⋮ [T10,Vcluster-10,nsql1,job=CHANGEFEED id=1059254308694753281] 452  Changefeed job 1059254308694753281 encountered transient error: job 1059254308694753281: ‹cannot update progress on cancel-requested job (id 1059254308694753281)› (attempt 1)
```

It seems strange to me that we retry a changefeed when we already know it's `cancel-requested`. I wonder if instead we should find a way to make that a terminal error.

File: pkg/ccl/changefeedccl/changefeed_test.go (hunk 2 above)
Comment (andyyang890) [reply pkg/ccl/changefeedccl/changefeed_test.go:7219]: > > Is that to say that it's possible in production for us to create a new logger and emit events more frequently than the 24hr interval?
> 
> I believe yes this is how it is for multi-node clusters, since each change aggregator would have their own logger (1-1 relationship). The test was failing because of a rare case where a single node went through 2 changefeed aggregators and thus 2 telemetry loggers.
> 
> @andyyang890 can you confirm the last point

Sounds right to me. Change aggregators are destroyed and recreated every time the changefeed restarts so it follows that the periodic telemetry logger is recreated as well.

File: pkg/ccl/changefeedccl/changefeed_test.go [hunk 3]
```diff
@@ -7209,6 +7209,19 @@ func TestChangefeedContinuousTelemetryOnTermination(t *testing.T) {
 		seen.Store(false)
 		sqlDB.Exec(t, `INSERT INTO foo VALUES (2)`)
 		sqlDB.Exec(t, `INSERT INTO foo VALUES (3)`)
+
+		s.TestingKnobs.DistSQL.(*execinfra.TestingKnobs).Changefeed.(*TestingKnobs).OverrideContinuousTelemetryLastEmit =
```
Comment (andyyang890) [inline pkg/ccl/changefeedccl/changefeed_test.go:7213]: It might be a data race to modify hooks while there's a running changefeed. Related to my point in https://github.com/cockroachdb/cockroach/pull/144161#issuecomment-2791016850, another option is we could have a hook that's called when the changefeed encounters a transient error that resets the expected logs when that happens.

File: pkg/ccl/changefeedccl/changefeed_test.go [hunk 4]
```diff
@@ -7622,7 +7627,13 @@ func TestChangefeedContinuousTelemetryOnTermination(t *testing.T) {
 
 		// Close the changefeed and ensure logs were created after closing.
 		require.NoError(t, foo.Close())
-		verifyLogsWithEmittedBytesAndMessages(t, jobID, afterFirstLog.UnixNano(), interval.Nanoseconds(), true /* closing */)
+		if numPeriodicTelemetryLogger.Load() > 1 {
```
Comment (asg0451) [inline pkg/ccl/changefeedccl/changefeed_test.go:7630]: i dont quite understand. the issue is that the feed starts up, does stuff, and encounters a transient error before we tell it to shutdown? in that case wouldnt the telemetry logger log the metrics during that first shutdown? and if not, maybe it should...?

(sorry if i'm misunderstanding -- i'm operating on very little sleep at the moment)

Comment (KeithCh) [reply pkg/ccl/changefeedccl/changefeed_test.go:7630]: > in that case wouldnt the telemetry logger log the metrics during that first shutdown?
Yes it would, but a second telemetry logger is created and also logs twice: one having `Closing = false` and the other having `Closing = true`.

So in the case of no error, one continuous log is emitted `afterFirstLog` and has `closing = true`.
In the case of error, we have an extraneous continuous log that has `closing = false`, and one that has `closing = false`. The extraneous `closing = false` message is what is causing the test to fail.

File: pkg/ccl/changefeedccl/testing_knobs.go [hunk 5]
```diff
@@ -116,6 +116,10 @@ type TestingKnobs struct {
 	// MakeKVFeedToAggregatorBufferKnobs is used to make a fresh set of testing knobs
 	// to pass to the constructor of the kv feed to change aggregator buffer.
 	MakeKVFeedToAggregatorBufferKnobs func() kvevent.BlockingBufferTestingKnobs
+
+	// IncNumPeriodicTelemetryLogger is used to keep track of the number of periodicTelemetryLogger created.
+	// More than 1 call to this indicates that there was a transient KV error.
+	IncNumPeriodicTelemetryLogger func()
```
Comment (andyyang890) [inline pkg/ccl/changefeedccl/testing_knobs.go:122]: I think you'd be able to achieve the same thing without introducing a new hook by reusing the WrapTelemetryLogger hook (i.e. doing the inc in there)

File: pkg/ccl/changefeedccl/helpers_test.go [hunk 6]
```diff
@@ -1424,7 +1424,12 @@ func checkContinuousChangefeedLogs(t *testing.T, startTime int64) []eventpb.Chan
 // This function also asserts the LoggingInterval and Closing fields of
 // each message.
 func verifyLogsWithEmittedBytesAndMessages(
-	t *testing.T, jobID jobspb.JobID, startTime int64, interval int64, closing bool,
+	t *testing.T,
+	jobID jobspb.JobID,
+	startTime int64,
+	interval int64,
+	closing bool,
+	numMessagesCanSkip int32,
```
Comment (andyyang890) [inline pkg/ccl/changefeedccl/helpers_test.go:1432]: An alternative idea: what if you wrap the telemetry logger (WrapTelemetryLogger hook) with something that doesn't log any messages when it's not the first periodic telemetry logger created?

Comment (KeithCh) [reply pkg/ccl/changefeedccl/helpers_test.go]: A lot less changes are needed so I think this is the best approach

**Review by andyyang890 — APPROVED** [review]
Nice

**Comment by KeithCh** [comment]
blathers backport 23.2 24.1 24.3 25.1 25.2
