### PR TITLE
roachtest: replace deprecated flags in `rapid-restart`

### LINKED ISSUE #63795: roachtest: acceptance/rapid-restart failed
Epic: CRDB-8501

### PR DESCRIPTION
**Pull request by cameronnunez**
Fixes [#63795](https://github.com/cockroachdb/cockroach/issues/63795).

The use of deprecated flags in `rapid-restart` is causing the test to fail. These 
flags are now replaced.

Release note: None

### CODE REVIEW

File: pkg/cmd/roachtest/tests/rapid_restart.go [hunk 1]
```diff
@@ -51,8 +51,8 @@ func runRapidRestart(ctx context.Context, t test.Test, c cluster.Cluster) {
 			go func() {
 				err := c.RunE(ctx, nodes,
 					`mkdir -p {log-dir} && ./cockroach start-single-node --insecure --store={store-dir} `+
-						`--log-dir={log-dir} --cache=10% --max-sql-memory=10% `+
-						`--listen-addr=:{pgport:1} --http-port=$[{pgport:1}+1] `+
+						`--log={log-dir} --cache=10% --max-sql-memory=10% `+
```
Comment (knz) [inline pkg/cmd/roachtest/tests/rapid_restart.go:54]: that `--log` flag is not going to work. I think `--log-dir` is still what you want here, unless you can use `--log='file-defaults: dir: {log-dir}'`

and then separately is this sufficient to make the test pass?

Comment (cameronnunez) [reply pkg/cmd/roachtest/tests/rapid_restart.go:54]: > that --log flag is not going to work. I think --log-dir is still what you want here, unless you can use --log='file-defaults: > dir: {log-dir}'

Got it.

> and then separately is this sufficient to make the test pass?

Yes. The test passes with these changes, as far as I can tell.

File: pkg/cmd/roachtest/tests/rapid_restart.go [hunk 2]
```diff
@@ -51,9 +51,14 @@ func runRapidRestart(ctx context.Context, t test.Test, c cluster.Cluster) {
 			go func() {
 				err := c.RunE(ctx, nodes,
 					`mkdir -p {log-dir} && ./cockroach start-single-node --insecure --store={store-dir} `+
-						`--log-dir={log-dir} --cache=10% --max-sql-memory=10% `+
-						`--listen-addr=:{pgport:1} --http-port=$[{pgport:1}+1] `+
+						`--log='file-defaults: dir: {log-dir}' --cache=10% --max-sql-memory=10% `+
```
Comment (knz) [inline pkg/cmd/roachtest/tests/rapid_restart.go:54]: I don't think this `--log` syntax is correct after all. Have you actually tried it?

Comment (cameronnunez) [reply pkg/cmd/roachtest/tests/rapid_restart.go:54]: I did. Seemed error-free. what's wrong with the syntax? is it because it is supposed to be `--log='file-defaults: {dir: log-dir}` or is it supposed to be the original value?

Comment (knz) [reply pkg/cmd/roachtest/tests/rapid_restart.go]: yes, I'm getting the following error:
```
% ./cockroach start-single-node --insecure --log='file-defaults: dir: foo'
E210930 18:59:53.860309 1 1@cli/clierror/check.go:35  [-] 1  ERROR: yaml: mapping values are not allowed in this context
ERROR: yaml: mapping values are not allowed in this context
```

Also, I think that `{dir: log-dir}` won't work? The syntax "`{log-dir}`" is a special string that is interpreted by roachprod to inject the logging directory, but I don't know that it recognizes braces in other locations.

Comment (cameronnunez) [reply pkg/cmd/roachtest/tests/rapid_restart.go]: ah yes I see. hmm. in that case maybe it is best to stick with `--log-dir`. It seems like the deprecated http flag was the true problem anyway.

Comment (knz) [reply pkg/cmd/roachtest/tests/rapid_restart.go]: sounds good!

**Comment by cameronnunez** [comment]
Verified that it is just the deprecated flag `--http-port` that is causing the test to fail. RFAL

**Review by knz — APPROVED** [review]

**Comment by cameronnunez** [comment]
TFYR! 

bors r=knz
