### PR TITLE
Ensure that the planner knows about the session during prepare.

### LINKED ISSUE #4550: sql: "no database specified" in pgwire session with database properly set
Assuming #4537 and #4548 , investigating #4036, next error:

- JDBC sends `CREATE TABLE test`, this succeeds;
- next command is `INSERT INTO test VALUES ...`, this fails with `error: no database specified: test`.

Network trace:
```
Internet Protocol Version 4, Src: 127.0.0.1, Dst: 127.0.0.1
PostgreSQL
    Type: Parse
    Length: 13
    Statement: 
    Query: BEGIN
    Parameters: 0
PostgreSQL
    Type: Bind
    Length: 12
    Portal: 
    Statement: 
    Parameter formats: 0
    Parameter values: 0
    Result formats: 0
PostgreSQL
    Type: Execute
    Length: 9
    Portal: 
    Returns: all rows
PostgreSQL
    Type: Parse
    Length: 76
    Statement: 
    Query: INSERT INTO test ( name, val ) VALUES ( $1, $2 ) RETURNING *
    Parameters: 2
        Type OID: 1043
        Type OID: 20
PostgreSQL
    Type: Bind
    Length: 33
    Portal: 
    Statement: 
    Parameter formats: 2
        Format: Text (0)
        Format: Binary (1)
    Parameter values: 2
        Column length: 1
        Data: 61
        Column length: 8
        Data: 0000000000000000
    Result formats: 0
PostgreSQL
    Type: Describe
    Length: 6
    Portal: 
PostgreSQL
    Type: Execute
    Length: 9
    Portal: 
    Returns: all rows
PostgreSQL
    Type: Sync
    Length: 4

Internet Protocol Version 4, Src: 127.0.0.1, Dst: 127.0.0.1
PostgreSQL
    Type: Parse completion
    Length: 4

Internet Protocol Version 4, Src: 127.0.0.1, Dst: 127.0.0.1
PostgreSQL
    Type: Bind completion
    Length: 4

Internet Protocol Version 4, Src: 127.0.0.1, Dst: 127.0.0.1

Internet Protocol Version 4, Src: 127.0.0.1, Dst: 127.0.0.1
PostgreSQL
    Type: Command completion
    Length: 10
    Tag: BEGIN

Internet Protocol Version 4, Src: 127.0.0.1, Dst: 127.0.0.1
PostgreSQL
    Type: Error
    Length: 48
    Severity: ERROR
    Code: XX000
    Message: no database specified: test

Internet Protocol Version 4, Src: 127.0.0.1, Dst: 127.0.0.1
PostgreSQL
    Type: Ready for query
    Length: 5
    Status: In a transaction (84)
```

### PR DESCRIPTION
**Pull request by knz**
Prepare needs the current database name to resolve unqualified
names and globs. This is available from the session. This patch
ensure that the planner knows about the current session in
prepare, not only execute.

Fixes #4550.

[Review on Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/4610)

### CODE REVIEW

**Comment by tamird** [comment]
LGTM but this seems like it can be tested from Go, and doesn't need to be done from Java. WDYT?

**Comment by knz** [comment]
@tamird can you suggest where I should look for Go tests?

File: sql/executor.go [hunk 1]
```diff
@@ -235,18 +235,12 @@ func (e *Executor) newTxn(s Session) *client.Txn {
...
-// args. The column result types are returned (or nil if there are no results).
-func (e *Executor) Prepare(user string, query string, session Session, args parser.MapArgs) ([]ResultColumn, *roachpb.Error) {
-	stmt, err := parser.ParseOne(query, parser.Syntax(session.Syntax))
-	if err != nil {
-		return nil, roachpb.NewError(err)
-	}
+// getPlanner allocates a new planner and initializes it.
+func (e *Executor) getPlanner(user string, session Session) *planner {
 	planMaker := plannerPool.Get().(*planner)
 	defer plannerPool.Put(planMaker)
```
Comment (tamird) [inline sql/executor.go]: whoa, this is super not safe

**Comment by tamird** [comment]
sql/pgwire_test.go

**Comment by andreimatei** [comment]
I've asked R to keep this a lot simpler since I'm changing this code anyway.

---

Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[sql/executor.go, line 299 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4610#-KBFSqUKLLKQL1g7xMEv:-KBFSqUKLLKQL1g7xMEw:-107215232) ([raw file](https://github.com/cockroachdb/cockroach/blob/afa89a59f2f75d9128e71eb5083d7d531be53de4/sql/executor.go#L299)):*
btw, this line here was plain bug, right? Keeping the old callback, not the one from the new session?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4610#-:-KBFSiSvoYKowvMEucSj:-381557772)*

**Comment by knz** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[sql/executor.go, line 299 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4610#-KBFSqUKLLKQL1g7xMEv:-KBFTD4E3DVJFcNxTpRR:-313144195) ([raw file](https://github.com/cockroachdb/cockroach/blob/afa89a59f2f75d9128e71eb5083d7d531be53de4/sql/executor.go#L299)):*
What should it be?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4610)*

**Comment by petermattis** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[sql/executor.go, line 241 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4610#-KBFR10RT7dm-mETOzHa-r1-241:-KBFUB3ihcQt0yTDcLJ3:-1037326263) ([raw file](https://github.com/cockroachdb/cockroach/blob/04c9b253663bc2eb7ea745bc4317c14cf0817760/sql/executor.go#L241)):*
To clarify: the planner we're returning from this method will be put back in the planner pool when this method returns. That is bad. You need to move this `defer` to wherever `getPlanner()` is called.

---

*[sql/executor.go, line 299 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4610#-KBFSqUKLLKQL1g7xMEv:-KBFU1ihDI99ZV33E_g5:45402243) ([raw file](https://github.com/cockroachdb/cockroach/blob/afa89a59f2f75d9128e71eb5083d7d531be53de4/sql/executor.go#L299)):*
Pretty sure this was ok. I think I just explained to @andreimatei why. 

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4610)*

**Comment by knz** [comment]
@tamird it doesn't look like either the test framework or lib/pq supports connecting to a specific database and pre-populating the session's current database. This is longer than the 4-liner I am suggesting.  I submitted #4612 for this.

**Comment by petermattis** [comment]
@knz `cockroach sql --url 'postgresql://root@peters-imac.local:15432?sslmode=disable&database=system' -e 'show tables'`. Notice the `database=system` part of the URL.

**Comment by knz** [comment]
@petermattis ok but that's not what pgwire_test.go does. My point is that we don't have a test harness ready to pass this parameter yet, unless I missed something.

---

Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4610#-:-KBFWE9PeJo-GJ7uFi17:-197714028)*

**Comment by petermattis** [comment]
`pgwire_test.go` calls `sql.Open` where the second parameter is a URL, just like the one I specified above. 

---

Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4610#-:-KBFWr18ObLZOgPIghr2:1992622180)*

**Comment by knz** [comment]
@petermattis, yes, yes, I saw this. Again my point is that 1) PGUrl doesn't currently allow to pre-populate the database name; then 2) none of the tests in pgwire_test.go seem to be interested to do so. 

Modifying both PGUrl to add a db argument, then all its callers accordingly, then also add a new test category for name qualification in pgwire_test.go seems a larger scope change than this PR. This is why I filed #4612 which I will work on separately.

**Comment by petermattis** [comment]
@knz I don't think you need to (or should) change `PGUrl`. You can set `URL.Path` on the `URL` returned from `PGUrl`. I'm not hung up on fixing the problem in this PR, but I don't think it is a lot of code.

**Comment by knz** [comment]
Oh you can do that? TIL.
Then that seems indeed reasonable. I'll have a look.

**Comment by andreimatei** [comment]
LGTM thanks for reverting to the one liner

---

Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[sql/executor.go, line 299 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4610#-KBFSqUKLLKQL1g7xMEv:-KBGQyP9M0B1t80DjGqH:1892017930) ([raw file](https://github.com/cockroachdb/cockroach/blob/afa89a59f2f75d9128e71eb5083d7d531be53de4/sql/executor.go#L299)):*
ok I'm convinced. It was unclear to me that the closure that gets created on line `p.evalCtx.GetLocation = p.session.getLocation` captures `&p.session`. I thought it'd capture `&planMaker`, but of course that was silly. I've now seen the light: https://golang.org/ref/spec#Method_values

Anyway, I'd still argue that the way we used that capture was an abuse. Although maybe it's just a goism I should learn to love?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4610#-:-KBGTrANOclrHJm1RxbL:331938329)*

**Comment by knz** [comment]
I've implemented Go tests now. LGTY?

---

Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4610#-:-KBIbDrqU2EifZ2teivd:-1492533534)*

**Comment by tamird** [comment]
LGTM but I think #4605 should go in first.

---

Reviewed 1 of 2 files at r2, 1 of 2 files at r3.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[sql/pgwire_test.go, line 548 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4610#-KBIo5EGhHUQcouF9uiP:-KBIo5EGhHUQcouF9uiQ:34019723) ([raw file](https://github.com/cockroachdb/cockroach/blob/3068bd7c214446e87a6112ca1feca0b51a8e4572/sql/pgwire_test.go#L548)):*
nit: prefer the shadowing form `if _, err := db.Exec(...); err != nil {`

---

*[sql/pgwire_test.go, line 553 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4610#-KBIoAxeR_z1_SYQf2U4:-KBIoAxeR_z1_SYQf2U5:-1866058253) ([raw file](https://github.com/cockroachdb/cockroach/blob/3068bd7c214446e87a6112ca1feca0b51a8e4572/sql/pgwire_test.go#L553)):*
After #4605 lands, you can `fmt.Sprintf(CREATE DATABASE IF NOT EXISTS %s, pgUrl.Path)` instead of this (or use a prepared statement if they work).

---

*[sql/pgwire_test.go, line 579 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4610#-KBIoSzvAPZ3r5u5DKAK:-KBIoSzvAPZ3r5u5DKAL:-1999618163) ([raw file](https://github.com/cockroachdb/cockroach/blob/3068bd7c214446e87a6112ca1feca0b51a8e4572/sql/pgwire_test.go#L579)):*
prefer shadowing form

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4610#-:-KBIoWMTIe8iiOx_8xws:1408066029)*

**Comment by knz** [comment]
Review status: 1 of 2 files reviewed at latest revision, 4 unresolved discussions.

---

*[sql/pgwire_test.go, line 548 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4610#-KBIo5EGhHUQcouF9uiP:-KBItFj_z1s_vVzQ1Iyx:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/3068bd7c214446e87a6112ca1feca0b51a8e4572/sql/pgwire_test.go#L548)):*
Done.

---

*[sql/pgwire_test.go, line 553 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4610#-KBIoAxeR_z1_SYQf2U4:-KBItHin8HNZMgnEfV8p:-1877883005) ([raw file](https://github.com/cockroachdb/cockroach/blob/3068bd7c214446e87a6112ca1feca0b51a8e4572/sql/pgwire_test.go#L553)):*
The thing is, #4605 can't land until this one lands, because the db prefix will break without this patch!

---

*[sql/pgwire_test.go, line 579 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4610#-KBIoSzvAPZ3r5u5DKAK:-KBItPH_EP8prqQawhq3:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/3068bd7c214446e87a6112ca1feca0b51a8e4572/sql/pgwire_test.go#L579)):*
Done.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4610)*

**Comment by knz** [comment]
Review status: 1 of 2 files reviewed at latest revision, 4 unresolved discussions.

---

*[sql/pgwire_test.go, line 553 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4610#-KBIoAxeR_z1_SYQf2U4:-KBIu8dUVm0fzvAVPkv8:262399565) ([raw file](https://github.com/cockroachdb/cockroach/blob/3068bd7c214446e87a6112ca1feca0b51a8e4572/sql/pgwire_test.go#L553)):*
Oops, never mind me. Actually #4605 still doesnt use unqualified names so it would work.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4610)*

**Comment by mjibson** [comment]
LGTM

---

Review status: 1 of 2 files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4610#-:-KBJZC5Y-fZSA-_b3Cm_:676834233)*

**Comment by tamird** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[sql/pgwire_test.go, line 553 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4610#-KBIoAxeR_z1_SYQf2U4:-KBJj9yezuq8zYQAC9gn:-1799821892) ([raw file](https://github.com/cockroachdb/cockroach/blob/3068bd7c214446e87a6112ca1feca0b51a8e4572/sql/pgwire_test.go#L553)):*
I think you're good to go, #4605 was closed.

---

*[sql/pgwire_test.go, line 541 \[r4\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4610#-KBJjVZ5pi6YXXdkkQFa:-KBJjVZ5pi6YXXdkkQFb:-976586432) ([raw file](https://github.com/cockroachdb/cockroach/blob/86630c2c2d7e5ef073dbe1fa62c43f0a741ebe03/sql/pgwire_test.go#L541)):*
can you give this a different name to distinguish it from the db used below? you have a double close on this one right now, which seems to be a result of this confusion.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4610)*

**Comment by knz** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[sql/pgwire_test.go, line 541 \[r4\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4610#-KBJjVZ5pi6YXXdkkQFa:-KBJmIfmpOf8VarmGs6y:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/86630c2c2d7e5ef073dbe1fa62c43f0a741ebe03/sql/pgwire_test.go#L541)):*
Done.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4610)*

**Comment by tamird** [comment]
Reviewed 2 of 2 files at r5.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[sql/pgwire_test.go, line 552 \[r5\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4610#-KBJnJBwqPcBLXlpiUlf:-KBJnJBwqPcBLXlpiUlg:-837451863) ([raw file](https://github.com/cockroachdb/cockroach/blob/673600b4265696940104348bcfcca33b538c9e7c/sql/pgwire_test.go#L552)):*
for the future: prefer descriptive names. I'd have used something like `qualDB` (that's not great, but anything is better than a number).

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4610)*
