### PR TITLE
sql: report schema change error with txn commit

### LINKED ISSUE #21822: sql: schema change errors are not reported if the DDL statement was not sent in the same query string as the commit
```
create table s (a int primary key, b int);
insert into s values (1, 1);
insert into s values (2, 1);
begin;
alter table s add constraint b_unique unique (b);
commit;
```

No error is reported even though adding the constraint fails.
I think it's because of this [line](https://github.com/cockroachdb/cockroach/blob/f8a8f8f76104494c79c61738e30596ac1da56eda/pkg/sql/session.go#L1401) which swallows the error if the statement that queued up the schema change was part of a prior query string.

I don't know how this was in 1.0, but it's been broken at least since result streaming came in 1.1. I think we should release a fix.

cc @vivekmenezes

### PR DESCRIPTION
**Pull request by andreimatei**
Before this change, an error encountered by a schema change queued up by
a statement in an explicit transaction would not be reported to the
client unless the statement was part of the same query string as the
COMMIT statement. So, generally speaking, schema change errors queued up
in transactions would not be reported :).
This occurs because of remnants of code of code that tried to associate
Before 1.1 I think we used to have code that either associated the error
with the statement that queued the change (if it still had access to its
result) or associated it with the commit otherwise. That broke when we
introduced results streaming. Or maybe it was always broken.

Besides this bug, there's an outstanding issue that the way in which
these errors are reported is no conformant to the pgwire protocol, and
also that these errors confusingly suggest to someone that the
transaction has not been committed. This commit does nothing to address
either of these. These issues are discussed in this Cockroach Labs
internal thread: https://groups.google.com/a/cockroachlabs.com/forum/#!topic/eng/Jc61hd6Pv2US

I will cherry-pick this into a 1.1 release.

Fixes #21822

Release note(sql): Fix reporting of errors from transactional schema
changes: errors from DDL statements sent by a client as part of a
transaction, but in a different query string than the final commit used
to be silently swallowed.

### CODE REVIEW

File: pkg/sql/schema_changer.go [hunk 1]
```diff
@@ -388,6 +388,9 @@ func (sc *SchemaChanger) maybeAddDropRename(
 // Execute the entire schema change in steps.
 // inSession is set to false when this is called from the asynchronous
 // schema change execution path.
+//
+// If the txn that queued the schema changer did not commit, this will be a
+// no-op, as we'll fail to find the job for our mutation in the jobs registry.
```
Comment (vivekmenezes) [inline pkg/sql/schema_changer.go]: TODO(andrei): not call this when a transaction doesn't commit.

**Review by vivekmenezes — APPROVED** [review]

File: pkg/sql/schema_changer.go (hunk 1 above)
Comment (andreimatei) [reply pkg/sql/schema_changer.go]: I've built scaffolding for that in my new execution code.
