### PR TITLE
backupccl: fix SHOW BACKUP on backup with tables with enum columns

### LINKED ISSUE #53659: backupccl: SHOW BACKUP on backup contains tables that refernce enums crashes
When `SHOW BACKUP` is run on a backup that has a table which has a enum column, the node crashes since the tables on which we try to derive the create statement on have not been hydrated.

### PR DESCRIPTION
**Pull request by pbardea**
This commit updates the lookup context used by SHOW BACKUP when
re-creating the create statement for its tables to hydrate the table
descriptors appropriately if there is type information.

Fixes https://github.com/cockroachdb/cockroach/issues/53659.

Release justification: bug fix
Release note: None

### CODE REVIEW

File: pkg/sql/resolver.go [hunk 1]
```diff
@@ -703,6 +707,46 @@ func newInternalLookupCtx(descs []catalog.Descriptor, prefix *dbdesc.Immutable)
 			schemaDescs[desc.GetID()] = desc
 		}
 	}
+
+	if len(typDescs) > 0 {
```
Comment (rohany) [inline pkg/sql/resolver.go:711]: is there a way to reuse this code with the logic done in the descriptor collection?

File: pkg/sql/resolver.go [hunk 2]
```diff
@@ -703,6 +707,46 @@ func newInternalLookupCtx(descs []catalog.Descriptor, prefix *dbdesc.Immutable)
...
+			desc := descs[i]
+			if tblDesc, ok := desc.(*tabledesc.Immutable); ok {
+				if err := typedesc.HydrateTypesInTableDescriptor(
+					ctx,
+					tblDesc.TableDesc(),
+					typedesc.TypeLookupFunc(typeLookup),
+				); err != nil {
+					// If we ran into an error hydrating the types, that means that we
+					// have some sort of corrupted descriptor state. Rather than disable
+					// uses of GetAllDescriptors, just log the error.
```
Comment (rohany) [inline pkg/sql/resolver.go:743]: this comment is out of date. I also think that in this case we should return an error because that means the backup is corrupted.

**Review by rohany — CHANGES_REQUESTED** [review]

File: pkg/sql/resolver.go (hunk 1 above)
Comment (pbardea) [reply pkg/sql/resolver.go]: Played around with a few ways to factor it out. Ended up with a `HydrateDescriptors` in `descs`. Curious what you think of it.

File: pkg/sql/resolver.go (hunk 2 above)
Comment (pbardea) [reply pkg/sql/resolver.go]: Done.

**Review by rohany — APPROVED** [review]
looks good, though I would like for the name `descs.HydrateDescriptors` to somehow say that it is doing to use only the input set of descriptors to perform the hydration. I don't have any suggestions for a new name though

**Comment by pbardea** [comment]
Went with `HydrateGivenDescriptors`. Not the prettiest, but I think it does the job. It's also easy to change if a better name is thought of.
bors r=rohany
