### PR TITLE
cdc: use highwater, if set, to get table descriptors in alter changefeed

### LINKED ISSUE #88050: changefeedccl: Alter changefeed broken when cursor set
When the changefeed is started with cursor option, and then
runs for a while (>gcttl time -- say 25 hours), the attempts to
alter changefeed will fail due to the fact that `createChangefeedJobRecord`
uses cursor (which is now very old) to set the time at which targets
are resolved. 

Jira issue: CRDB-19662

gz#13947

Epic CRDB-14988

### PR DESCRIPTION
**Pull request by biradarganesh25**
When the changefeed is started with cursor option, and then runs for a while (>gcttl time -- say 25 hours), the attempts to alter changefeed will fail due to the fact that createChangefeedJobRecord uses cursor (which is now very old) to set the time at which targets are resolved

To fix this, we will use the highwater timestamp to get the table descriptors. Targets will always be valid at highwater. Since createChangefeedJobRecord is called both during create changefeed and alter changefeed, we use cursor/statement time if highwater is not avaliable (which indicates that currently create changefeed is executing)

Resolves: #88050

Release note (bug fix): Fixed a bug which causes alter changefeed to fail if the changefeed was created with cursor option and had been running for more than gc.ttlseconds

### CODE REVIEW

File: pkg/ccl/changefeedccl/alter_changefeed_test.go [hunk 1]
```diff
@@ -1325,3 +1325,76 @@ func TestAlterChangefeedInitialScan(t *testing.T) {
 		cdcTest(t, testFn(initialScanOpt), feedTestForceSink("kafka"))
 	}
 }
+
+/*
+This test checks that the time used to get table descriptors in alter changefeed command is
+highwatermark (if set).
+*/
```
Comment (miretskiy) [inline pkg/ccl/changefeedccl/alter_changefeed_test.go:1332]: nit: // style comments please.

File: pkg/ccl/changefeedccl/changefeed_stmt.go [hunk 2]
```diff
@@ -348,6 +348,26 @@ func createChangefeedJobRecord(
 		statementTime = initialHighWater
 	}
 
+	// Change the statement time to highwater time if available to make sure
+	// that we do not get an error when getting table descriptors (might happen
+	// in case where cursor time is far behind in the past)
+	var progressHighWater *hlc.Timestamp
+	job, err := p.ExecCfg().JobRegistry.LoadJobWithTxn(ctx, jobID, p.Txn())
```
Comment (miretskiy) [inline pkg/ccl/changefeedccl/changefeed_stmt.go:355]: I don't think you need to load the job at all;
Alter changefeed passes an annotatedChangefeedStatemetn containing changefeed statement, along with things that are necessary to make "alter" work.  So, you can include whatever extra information, such as high watermark there.

File: pkg/ccl/changefeedccl/alter_changefeed_test.go [hunk 3]
```diff
@@ -1325,3 +1325,76 @@ func TestAlterChangefeedInitialScan(t *testing.T) {
...
+			}
+			return errors.New("waiting for checkpoint advance")
+		})
+
+		sqlDB.Exec(t, `PAUSE JOB $1`, castedFeed.JobID())
+		waitForJobStatus(sqlDB, t, castedFeed.JobID(), `paused`)
+
+		sqlDB.Exec(t, `INSERT INTO foo VALUES (2, 'after')`)
+
+		/*
```
Comment (miretskiy) [inline pkg/ccl/changefeedccl/alter_changefeed_test.go:1377]: nit; // comment style

**Review by miretskiy — CHANGES_REQUESTED** [review]

**Review by biradarganesh25 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/88402)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @miretskiy and @stevendanna)

___
*[`pkg/ccl/changefeedccl/changefeed_stmt.go` line 355 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/88402#-NCWtZ4pgOlwUCGackKa-r1-355:-NCYs9eN9pQttkoUEtyx:b-7rl0jd) ([raw file](https://github.com/cockroachdb/cockroach/blob/8f74c8f8833da2ed7970e56b614235f4bc94a527/pkg/ccl/changefeedccl/changefeed_stmt.go#L355)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

I don't think you need to load the job at all;
Alter changefeed passes an annotatedChangefeedStatemetn containing changefeed statement, along with things that are necessary to make "alter" work.  So, you can include whatever extra information, such as high watermark there. 

</blockquote></details>

done.

File: pkg/ccl/changefeedccl/changefeed_stmt.go [hunk 4]
```diff
@@ -84,7 +84,8 @@ func init() {
 
 type annotatedChangefeedStatement struct {
 	*tree.CreateChangefeed
-	originalSpecs map[tree.ChangefeedTarget]jobspb.ChangefeedTargetSpecification
+	originalSpecs         map[tree.ChangefeedTarget]jobspb.ChangefeedTargetSpecification
+	overRideStatementTime *hlc.Timestamp
```
Comment (miretskiy) [inline pkg/ccl/changefeedccl/changefeed_stmt.go:88]: Just keep it hlc.Timestamp
Ignore if ts.IsEmtpy()

Comment (miretskiy) [inline pkg/ccl/changefeedccl/changefeed_stmt.go:88]: nit: perhaps `overrideCursor`; or even `alterChangefeedAsOf` might be better names.

**Review by miretskiy — APPROVED** [review]
Very nice.
Please address few nits, and feel free to merge (provided CI is green)

**Review by stevendanna — APPROVED** [review]
LGTM.

The only thing that makes me a _little_ nervous is that in getChangefeedStatement, the variable is named `statementTime` which could mean it ends up getting used for something where using the highwatermark is inappropriate.  For example, right now, we also use it to set the cursor end time in the case of an initial_scan_only feed, but I think this is OK since the high watermark will be empty until the initial scan is done anyway.

**Comment by amruss** [comment]
Can we backport this change to a 22.2 patch release?

**Comment by miretskiy** [comment]
we should.

**Comment by biradarganesh25** [comment]
I'll do it

**Comment by biradarganesh25** [comment]
Sure!
