### PR TITLE
sql: make crdb_internal.jobs and SHOW JOBS tolerant of data errors

### LINKED ISSUE #27427: sql: SHOW JOBS should not abort if it finds invalid data in `system.jobs`
A user is reporting that their `SHOW JOBS` command completely fails with

```
pq: Job: failed to unmarshal Progress as DBytes (was tree.dNull)
```

It seems (due to unrelated issue which will be worked on) that a botched import has improperly populated the progress field. That separate issue will be worked on separately.

In the meantime, SHOW JOBS should be more tolerant of invalid/incorrect input data and instead perhaps report a NULL value in its output and/or an explanatory error text in its results.

### PR DESCRIPTION
**Pull request by knz**
Fixes #27427.

Prior to this patch, an invalid or incomplete entry in `system.jobs`
would cause `crdb_internal.jobs` and `SHOW JOBS` to choke violently
and refuse to say anything about anything (and fail the query entirely
instead).

This patch corrects the issue by populating the `error` column adequately.

Release note (sql change): SHOW JOBS is now able to report results
even when a job entry is incomplete or incorrect.

### CODE REVIEW

File: pkg/sql/show_test.go [hunk 1]
```diff
@@ -802,3 +802,83 @@ func TestShowJobs(t *testing.T) {
...
+	params, _ := tests.CreateTestServerParams()
+	s, sqlDB, _ := serverutils.StartServer(t, params)
+	defer s.Stopper().Stop(context.TODO())
+
+	// Create at least 4 row, ensuring the last 3 rows are corrupted.
+	if _, err := sqlDB.Exec(`
+     -- Ensure there is at least one row in system.jobs.
+     CREATE TABLE foo(x INT); ALTER TABLE foo ADD COLUMN y INT;
+     -- Create a corrupted payload field from the first row.
+     INSERT INTO system.jobs(id, status, payload, progress) SELECT id+1, status, '\xaaaa'::BYTES, progress FROM system.jobs ORDER BY id LIMIT 1;
```
Comment (dt) [inline pkg/sql/show_test.go]: should test null as well as corrupted -- I know that previously was another unhandled error

**Review by dt — APPROVED** [review]
Thanks!

File: pkg/sql/show_test.go (hunk 1 above)
Comment (knz) [reply pkg/sql/show_test.go]: Done.

**Comment by knz** [comment]
the failure was due to a missing case in the test. bleh.

bors r+
