### PR TITLE
changefeedccl: add test-only assertion for checkpoint fields invariant

### LINKED ISSUE #149100: changefeedccl: add test-only assertion for checkpoint fields invariant
As follow up work for #148617, we should add a test-only assertion to make sure the bug doesn't happen again. As part of this issue, we'll also need to adapt the mixed-version test so that it doesn't fail if it upgrades through one of the patch releases with the bug.

Jira issue: CRDB-51982

### PR DESCRIPTION
**Pull request by andyyang890**
Fixes #149100

---

**roachtest: surface changefeed failures in mixed-version CDC tests** 

Previously, if the changefeed failed in a mixed-version CDC test,
the test wouldn't fail until it hit the timeout. We now periodically
check for changefeed failures and fail the test if one is found.

Release note: None

---

**mixedversion: add RunE method to Test** 

This patch adds a `RunE` method to `Test`. Unlike the existing `Run` function,
it will not immediately fatal the test if an error is encountered and will
instead return the error along with the test plan so that callers may decide
how to handle the error.

Release note: None

---

**changefeedccl: add test-only assertion for checkpoint fields invariant** 

This patch adds a test-only assertion that we won't ever see both
checkpoint fields set on a changefeed job progress struct. It is
test-only because a bug that existed on earlier versions of 25.2
could cause both checkpoint fields to be set and so the production
code continues to discard the legacy checkpoint when that happens.

Release note: None

### CODE REVIEW

**Comment by andyyang890** [comment]
TeamCity run with 25 runs of `cdc/mixed-version/checkpointing`: https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/20069775?buildTab=overview&hideProblemsFromDependencies=false&hideTestsFromDependencies=false&expandBuildChangesSection=true

It shows that the skipping logic works and also that the test still passes most of the time.

File: pkg/cmd/roachtest/tests/mixed_version_cdc.go [hunk 1]
```diff
@@ -653,12 +672,28 @@ func runCDCMixedVersionCheckpointing(ctx context.Context, t test.Test, c cluster
...
+
 	// Test setup.
 	mvt.OnStartup("start changefeed", tester.createChangeFeed)
 	mvt.OnStartup("create validator", tester.setupValidator)
 	mvt.OnStartup("init workload", tester.initWorkload)
 	mvt.OnStartup("set checkpointing settings", forceCheckpointing)
 
+	// Check before we upgrade to each version whether we're upgrading to
+	// a version that is affeced by the checkpoint fields bug (#148620).
+	mvt.BeforeUpgrade("check if affected by #148620", checkIfAffectedBy148620)
```
Comment (DarrylWong) [inline pkg/cmd/roachtest/tests/mixed_version_cdc.go]: I think you could just call this at the start of `waitAndValidate` and avoid the need for the `BeforeUpgrade` hook all together?

Comment (DarrylWong) [reply pkg/cmd/roachtest/tests/mixed_version_cdc.go]: Alternatively, maybe we should add a `mvt.RunE` variant which returns an error and the `plan`. Then you can retroactively check `plan.Versions()` to decide whether or not to skip.

Comment (andyyang890) [reply pkg/cmd/roachtest/tests/mixed_version_cdc.go]: > Alternatively, maybe we should add a `mvt.RunE` variant which returns an error and the `plan`. Then you can retroactively check `plan.Versions()` to decide whether or not to skip.

I went with this idea

**Review by DarrylWong — APPROVED** [review]
mixed version changes LGTM

**Comment by andyyang890** [comment]
TeamCity run with 25 runs of `cdc/mixed-version/checkpointing`:
https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/20074546?buildTab=overview&hideProblemsFromDependencies=false&hideTestsFromDependencies=false&expandBuildChangesSection=true

It shows that most runs still pass, but also both failure modes due to the known checkpoint fields bug are caught and cause the test to be skipped instead of fail:
```
20:58:48   --- SKIP: cdc/mixed-version/checkpointing (N/A)
20:58:48     expected error due to #148620: background step `task-5` returned error: error in task function task-5: changefeed failed: both legacy and current checkpoint set on changefeed job progress
```
```
21:09:36   --- SKIP: cdc/mixed-version/checkpointing (N/A)
21:09:36     expected error due to #148620: background step `task-6` returned error: error in task function task-6: changefeed failed: both legacy and current checkpoint set on change aggregator spec
```

**Review by asg0451 — APPROVED** [review]

**Comment by andyyang890** [comment]
TFTRs!

bors r=DarrylWong,asg0451
