### PR TITLE
opt: permit coexistance of inv, forward histograms

### LINKED ISSUE #84529: sql: forward index histogram on an trigram inverted index column causes internal errors
When the optimizer sees a histogram on a normal column of type `text` (now both forward indexable and inverted indexable with `gin_trgm_ops`) while trying to build spans for an inverted index, an error is returned due to the type mismatch of the bytes (inverted) histogram it expects and the text (forward) histogram it finds.

This is basically a manifestation of #50655, which covers the fact that histograms don't have a "type" attribute that could help distinguish inverted from forward sketches/histograms, or distinguish different types of inverted histograms from each other.

Here is a simple repro:

```
demo@127.0.0.1:26257/defaultdb> create table a (a) as select 'hi';
CREATE TABLE AS

demo@127.0.0.1:26257/defaultdb> analyze a; 
ANALYZE

demo@127.0.0.1:26257/defaultdb> create inverted index on a(a gin_trgm_ops) ;
CREATE INDEX

demo@127.0.0.1:26257/defaultdb> explain select * from a where a like '%ffooo%';
ERROR: unsupported comparison: string to bytes
SQLSTATE: 42804
```

If analyze is re-run, all is well again. I think this is because the most recent histogram for the column becomes the inverted column. This raises the question of whether an ordinary forward scan will find the wrong histogram. I wasn't able to easily discover any internal errors in this state, but I wouldn't be surprised if things were going wrong in more subtle ways.

```
demo@127.0.0.1:26257/defaultdb> analyze a;
ANALYZE


Time: 18ms total (execution 18ms / network 0ms)

demo@127.0.0.1:26257/defaultdb> explain select * from a where a like '%ffooo%';
                                            info
---------------------------------------------------------------------------------------------
  distribution: local
  vectorized: true

  • filter
  │ estimated row count: 0
  │ filter: a LIKE '%ffooo%'
  │
  └── • index join
      │ estimated row count: 0
      │ table: a@a_pkey
      │
      └── • inverted filter
          │ inverted column: a_inverted_key
          │ num spans: 3
          │
          └── • scan
                estimated row count: 0 (<0.01% of the table; stats collected 2 seconds ago)
                table: a@a_a_idx
                spans: 3 spans
(19 rows)


Time: 1ms total (execution 1ms / network 0ms)
```

Jira issue: CRDB-17708

### PR DESCRIPTION
**Pull request by jordanlewis**
Closes #84529.

Previously, when trying to use persisted histograms to filter an
inverted column, if the histogram read from disk was a "forward
histogram", the operation would fail with an internal error.

This is because inverted histograms and forward histograms use different
datatypes on disk, and it's not possible to compare a forward histogram
(represented as the datatype of the column) with the inverted constraint
(represented as DBytes).

Now, this problem is corrected by making sure that we only store forward
histogram data in forward histogram column sets, and likewise for
inverted histogram data being only stored in inverted histogram column
sets.

Release note: None

### CODE REVIEW

**Comment by jordanlewis** [comment]
Note that this is a slightly more precise fix than the one I proposed in #84529. It will only ignore the histogram if the histogram is of the wrong type: in the steady state, the trigram inverted filter will successfully use the trigram inverted histogram when one exists.

I do have a concern: will the reverse problem exist? In other words, once we build an inverted histogram on the trigram-indexed column, will a forward scan use the wrong histogram too?

I couldn't reproduce any problem of this nature, but it surprises me - I'd expect that something would be going wrong of that nature.

File: pkg/sql/logictest/testdata/logic_test/trigram_indexes [hunk 1]
```diff
@@ -143,3 +143,17 @@ INSERT INTO pkt VALUES (1, 'abcd'), (2, 'bcde')
...
 ALTER TABLE pkt ALTER PRIMARY KEY USING COLUMNS (b)
+
+# Ensure that it's okay to perform an inverted filter on a table with a trigram
+# inverted index that only has a forward statistic collected on the inverted
+# column.
+
+statement ok
+CREATE TABLE b (a) AS SELECT 'foo';
+ANALYZE b;
+CREATE INVERTED INDEX ON b(a gin_trgm_ops)
```
Comment (mgartner) [inline pkg/sql/logictest/testdata/logic_test/trigram_indexes:154]: Don't you need to analyze after the index is created? The inverted column doesn't exist until the index is created.

File: pkg/sql/opt/memo/statistics_builder.go [hunk 2]
```diff
@@ -863,9 +864,20 @@ func (sb *statisticsBuilder) constrainScan(
...
+					// If we have a histogram that doesn't contain DBytes, we know we're
+					// looking at a forward histogram, since inverted histograms always
+					// are of type DBytes. We cannot use the histogram if this is the
+					// case.
+					// Note that this is a sketchy situation (no pun intended), because
+					// if we one day supported inverted indexes on bytes types, this check
+					// wouldn't properly reject the histogram. The proper fix, tracked
+					// in #50655, is to add a type field onto the persisted histogram.
+					if inputHist.BucketCount() == 0 ||
+						inputHist.Bucket(0).UpperBound.ResolvedType().Family() == types.BytesFamily {
```
Comment (mgartner) [inline pkg/sql/opt/memo/statistics_builder.go:876]: Internally the type we use for inverted columns is `types.EncodedKey`: https://github.com/cockroachdb/cockroach/blob/10a054b63d9403aa48ef2f7d7b3615a938879240/pkg/sql/types/types.go#L479-L485

But I guess we write the type bytes to the persisted histogram?

File: pkg/sql/opt/memo/statistics_builder.go [hunk 3]
```diff
@@ -863,9 +864,20 @@ func (sb *statisticsBuilder) constrainScan(
...
 				s.RowCount = max(inputHist.ValuesCount(), 1)
 				if colStat, ok := s.ColStats.Lookup(colSet); ok {
-					colStat.Histogram = inputHist.InvertedFilter(scan.InvertedConstraint)
-					histCols.Add(invertedConstrainedCol)
-					sb.updateDistinctCountFromHistogram(colStat, inputStat.DistinctCount)
+					// If we have a histogram that doesn't contain DBytes, we know we're
+					// looking at a forward histogram, since inverted histograms always
+					// are of type DBytes. We cannot use the histogram if this is the
+					// case.
+					// Note that this is a sketchy situation (no pun intended), because
```
Comment (mgartner) [inline pkg/sql/opt/memo/statistics_builder.go:871]: Not only is it sketchy, it means that we won't have accurate row count estimates for queries on trigram indexes. As a result, the optimizer probably won't pick the best plan in a number of cases.

**Review by mgartner — APPROVED** [review]
LGTM! Thanks for fixing this!

File: pkg/sql/logictest/testdata/logic_test/trigram_indexes (hunk 1 above)
Comment (jordanlewis) [reply pkg/sql/logictest/testdata/logic_test/trigram_indexes:154]: The bug was explicitly in this state, where there is an inverted index but a forward histogram on the column that's being inverted indexed. Once you re-analyze, there is no bug. I've added a test case to ensure that both scenarios work okay.

File: pkg/sql/opt/memo/statistics_builder.go (hunk 2 above)
Comment (jordanlewis) [reply pkg/sql/opt/memo/statistics_builder.go:876]: Yeah, we do - there is some commentary about it where we write the persisted inverted histograms.

File: pkg/sql/opt/memo/statistics_builder.go (hunk 3 above)
Comment (jordanlewis) [reply pkg/sql/opt/memo/statistics_builder.go:871]: Yeah :( And even worse, isn't it actually more like we won't have accurate row count estimates for queries against text columns that happen to also be inverted indexed? I think that's the thing I'm most scared of here...

**Comment by jordanlewis** [comment]
Hmm, a bunch of tests failed... I'm going to investigate, but I wonder if there is something more fishy underfoot here.

**Review by rytaft — COMMENTED** [review]
Thanks for fixing this!

> Reviewed 1 of 3 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/84927#-:-N7ghfAs9ELPOWhQsLLB:b-whxd1j)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jordanlewis and @mgartner)

___
*[`pkg/sql/opt/memo/statistics_builder.go` line 871 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/84927#-N7b_KQpUANp5IRsnWbh-r1-871:-N7gfhHWA5IWKImca0B4:b-zdp2i0) ([raw file](https://github.com/cockroachdb/cockroach/blob/f527fe2705dfab3f9297a9d643481fdf4c3df2d0/pkg/sql/opt/memo/statistics_builder.go#L871)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

Yeah :( And even worse, isn't it actually more like we won't have accurate row count estimates for queries against text columns that happen to also be inverted indexed? I think that's the thing I'm most scared of here...
</blockquote></details>

Probably worth adding a stats-specific test for this. Can you add some tests in `opt/memo/testdata/stats/scan` similar to the tests you added in logic /execbuilder tests?

We can probably fix this issue by adding a check before line 865 or saving the previous value of `s.RowCount`.
___
*[`pkg/sql/opt/memo/statistics_builder.go` line 884 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/84927#-N7gf8Y22GbE4VIWb4mM:-N7gf8Y391ES8QzqCAZb:bbn6kr) ([raw file](https://github.com/cockroachdb/cockroach/blob/4e03e3ad7b624a6ba207e43724ff445c355ff8f8/pkg/sql/opt/memo/statistics_builder.go#L884)):*
> ```Go
> 							continue
> 						case types.BytesFamily:
> 							break LOOP
> ```

nit: I'd like to avoid using these GOTO style statements here if possible. I feel like this would be a good candidate for a helper function.

**Review by jordanlewis — COMMENTED** [review]
The execbuilder test I added doesn't have stable results - if I dump the histogram after running ANALYZE, the results differ from run to run. I know the statistics collection uses random sampling, but I guess I figured in logic tests we'd fix the seed. Is the proper way to fix this to inject artificial histograms rather than running ANALYZE? And if so, should all of the test cases that need the histograms really just belong in the stats testdata?

Also, in adding the stats test you suggested, I'm noticing that the stats tests have nice histograms with just a few buckets. How do you generate those nice test histograms? Is there a way to ask the stats system to use a lower bucket count?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/84927#-:-N7hX3WV2pWKyO60drTF:bu0valy)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @mgartner)

___
*[`pkg/sql/opt/memo/statistics_builder.go` line 871 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/84927#-N7b_KQpUANp5IRsnWbh-r1-871:-N7hPVRQEUhWmk-QC3gh:btde2ba) ([raw file](https://github.com/cockroachdb/cockroach/blob/f527fe2705dfab3f9297a9d643481fdf4c3df2d0/pkg/sql/opt/memo/statistics_builder.go#L871)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

Probably worth adding a stats-specific test for this. Can you add some tests in `opt/memo/testdata/stats/scan` similar to the tests you added in logic /execbuilder tests?

We can probably fix this issue by adding a check before line 865 or saving the previous value of `s.RowCount`.
</blockquote></details>

That's true, we should also avoid editing the row count if we're looking at the wrong kind of histogram. I've fixed that.

But isn't there still the problem in the opposite case, where we're trying to use a histogram for an ordinary, non-inverted scan on a text column, and we see a set of inverted statistics? I think we'd want a guard in the opposite direction, in `applyIndexConstraint`, that makes sure that we aren't using an inverted histogram for a forward scan.

What I don't understand is why this theoretical problem doesn't manifest as a type error, like the original bug did.

**Review by rytaft — COMMENTED** [review]
> The execbuilder test I added doesn't have stable results - if I dump the histogram after running ANALYZE, the results differ from run to run. I know the statistics collection uses random sampling, but I guess I figured in logic tests we'd fix the seed. Is the proper way to fix this to inject artificial histograms rather than running ANALYZE? And if so, should all of the test cases that need the histograms really just belong in the stats testdata?

You could use `INJECT STATISTICS`, but I think it's also fine to get rid of these execbuilder tests altogether.

> Also, in adding the stats test you suggested, I'm noticing that the stats tests have nice histograms with just a few buckets. How do you generate those nice test histograms? Is there a way to ask the stats system to use a lower bucket count?

We don't currently have a way to control the number of histogram buckets collected by `CREATE STATISTICS`/`ANALYZE` (it's hardcoded as 200 for index columns, and 2 for other columns). Those histograms in the stats tests were just manually constructed.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/84927#-:-N7n26WMDzMb6-x1sISV:b-lvol5a)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @mgartner)

___
*[`pkg/sql/opt/memo/statistics_builder.go` line 871 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/84927#-N7b_KQpUANp5IRsnWbh-r1-871:-N7n4NAlDUeBg2BYrsy3:b-n07hl) ([raw file](https://github.com/cockroachdb/cockroach/blob/f527fe2705dfab3f9297a9d643481fdf4c3df2d0/pkg/sql/opt/memo/statistics_builder.go#L871)):*
> That's true, we should also avoid editing the row count if we're looking at the wrong kind of histogram. I've fixed that.

Doesn't look like you've pushed the fix.

> But isn't there still the problem in the opposite case, where we're trying to use a histogram for an ordinary, non-inverted scan on a text column, and we see a set of inverted statistics? I think we'd want a guard in the opposite direction, in applyIndexConstraint, that makes sure that we aren't using an inverted histogram for a forward scan.

I think you're right.

> What I don't understand is why this theoretical problem doesn't manifest as a type error, like the original bug did.

I'm not sure -- it would be good to add some tests that exercise this.

File: pkg/sql/opt/memo/statistics_builder.go (hunk 3 above)
Comment (mgartner) [reply pkg/sql/opt/memo/statistics_builder.go:871]: Correct, that's what I meant to say.

**Review by jordanlewis — COMMENTED** [review]
This is ready for another look, I redid it like we discussed on Slack. Now, the code carefully segments inverted histograms from forward histograms in the statistics map, so there's no chance for code to accidentally get the wrong type of histogram when building plans.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/84927#-:-N7s8mNg7Bk4rhxW-ArA:borqe50)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @mgartner and @rytaft)

___
*[`pkg/sql/opt/memo/statistics_builder.go` line 871 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/84927#-N7b_KQpUANp5IRsnWbh-r1-871:-N7s92-E-ve9MpYw_5hm:bad6kck) ([raw file](https://github.com/cockroachdb/cockroach/blob/f527fe2705dfab3f9297a9d643481fdf4c3df2d0/pkg/sql/opt/memo/statistics_builder.go#L871)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

> Yeah :( And even worse, isn't it actually more like we won't have accurate row count estimates for queries against text columns that happen to also be inverted indexed? I think that's the thing I'm most scared of here...

Correct, that's what I meant to say.
</blockquote></details>

Removed this code.
___
*[`pkg/sql/opt/memo/testdata/stats/inverted-geo` line 774 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/84927#-N7s95cx3Tkrsd4K4Fc-:-N7s95cx3Tkrsd4K4Fc0:ba0uc7u) ([raw file](https://github.com/cockroachdb/cockroach/blob/defb512497a57dcd66c03d998a8cdc068ac28b93/pkg/sql/opt/memo/testdata/stats/inverted-geo#L774)):*
> ```
>       │    │    └── stats: [rows=1, distinct(2)=1, null(2)=0, avgsize(2)=4]
>       │    │        histogram(2)=  0                                                                                            4.9994e-05                                                                                            0.99988                                                           7.4991e-05
>       │    │                     <--- '0107000020E6100000010000000103000020E610000001000000040000008C7D4198BD2B574080A6FD3A111E4D40F0DF86928AA12BC03A59212197A35140CEA3CEE206B863C0FC7649EB60BA53408C7D4198BD2B574080A6FD3A111E4D40' --------- '0102000020E61000000300000005D8E086BB6365C03F9E5737DD1A53C0C04ECDED673B55C06711C00C7C0240C0B8EABD96072856404A9D2C529FC74EC0'
> ```

I think the reason for this change is that the test is buggy.

The injected statistics here should have histo_col_type=BYTES, not GEOGRAPHY, unless they were collected on the ordinary column. But I think we don't collect forward statistics on GEOGRAPHY columns. So I think this test is just wrong, thoughts? The fix would be to change the injected stats to be bytes type.

**Review by rytaft — APPROVED** [review]
:lgtm: thanks for working through these details! 

I thought we had discussed iterating through older statistics to find both forward and inverted histograms? Feel free to open an issue and/or save that work for another PR. I think it's probably worth doing at some point, though (even before we fix https://github.com/cockroachdb/cockroach/issues/50655), since we can limit the extra computation to only cases where it's useful. For example, we can limit it to cases where we have a string column that also has an inverted index. We will (almost) always collect a forward histogram (it will just be smaller if there is no forward index), so we should try to find both the forward and inverted histograms for these columns.

> Reviewed 3 of 5 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/84927#-:-N7uwrAr9kTcOvMOccww:b-95jj0w)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @jordanlewis, @mgartner, and @rytaft)

___
*[`pkg/sql/opt/memo/statistics_builder.go` line 666 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/84927#-N7uv4I9-X5qDulf-h9x:-N7uv4I9-X5qDulf-h9y:b-wpx0xo) ([raw file](https://github.com/cockroachdb/cockroach/blob/979b5fbc77430b3c24b891e3e9618652066602fc/pkg/sql/opt/memo/statistics_builder.go#L666)):*
> ```Go
> 			if needHistogram {
> 				invertedColOrds = invertedIndexCols[stat.ColumnOrdinal(0)]
> 				invertedStatistic = len(invertedColOrds) > 0 && !histogramIsNonBytes(stat.Histogram())
> ```

nit: can we remove the double-negative and change this to `histogramIsBytes`?
___
*[`pkg/sql/opt/memo/statistics_builder.go` line 687 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/84927#-N7uuaetE-_TD6bkZU_H:-N7uuaetE-_TD6bkZU_I:b-kmrssi) ([raw file](https://github.com/cockroachdb/cockroach/blob/979b5fbc77430b3c24b891e3e9618652066602fc/pkg/sql/opt/memo/statistics_builder.go#L687)):*
> ```Go
> 				// to calling stats.ColStats.Add() on any inverted column statistics
> 				// created above.
> 				colStat, _ = stats.ColStats.Lookup(cols)
> ```

I don't think you need to do this anymore
___
*[`pkg/sql/opt/memo/testdata/stats/inverted-geo` line 774 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/84927#-N7s95cx3Tkrsd4K4Fc-:-N7uwFKH5WZr-xo8RZpN:b-tpmzan) ([raw file](https://github.com/cockroachdb/cockroach/blob/defb512497a57dcd66c03d998a8cdc068ac28b93/pkg/sql/opt/memo/testdata/stats/inverted-geo#L774)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

I think the reason for this change is that the test is buggy.

The injected statistics here should have histo_col_type=BYTES, not GEOGRAPHY, unless they were collected on the ordinary column. But I think we don't collect forward statistics on GEOGRAPHY columns. So I think this test is just wrong, thoughts? The fix would be to change the injected stats to be bytes type. 
</blockquote></details>

Your change looks good

**Review by jordanlewis — COMMENTED** [review]
I am probably missing something, but I thought that we were actually already doing that (and just ignoring all but the most recent one because of the way colStatsMap works:

```
		for i := 0; i < tab.StatisticCount(); i++ {
			stat := tab.Statistic(i)
```

As I understood, this loop finds every statistic in the table, including historical statistics.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/84927#-:-N7v-valEZ2j4hRd-KTi:b-cq4lqf)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @jordanlewis, @mgartner, and @rytaft)

**Review by rytaft — COMMENTED** [review]
That's correct -- we are ignoring all but the most recent one for each set of columns. So in order to make sure that we get both types of histograms, I think we can make a relatively small change (I added a comment below).

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/84927#-:-N7vPRBa5Ddp7V2nbomK:b-t5q8gf)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @jordanlewis, @mgartner, and @rytaft)

___
*[`pkg/sql/opt/memo/statistics_builder.go` line 669 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/84927#-N7vQC098xrI3iOFWZrh:-N7vQC0A3rburjEVEkgo:b-vv6kv6) ([raw file](https://github.com/cockroachdb/cockroach/blob/979b5fbc77430b3c24b891e3e9618652066602fc/pkg/sql/opt/memo/statistics_builder.go#L669)):*
> ```Go
> 			}
> 
> 			if colStat, ok := stats.ColStats.Add(cols); ok {
> ```

I think we can ensure we get both types of histograms by changing this slightly as follows:
```
if colStat, ok := stats.ColStats.Add(cols); ok {
  // Keep what's already here
} else if colStat.Histogram == nil && needHistogram && !invertedStatistic {
  col := cols.SingleColumn()
  colStat.Histogram = &props.Histogram{}
  colStat.Histogram.Init(sb.evalCtx, col, stat.Histogram())
}
```
This takes advantage of the fact that `stats.ColStats.Add(cols)` returns the existing statistic if `ok` is false.

**Review by jordanlewis — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/84927)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @jordanlewis, @mgartner, and @rytaft)

___
*[`pkg/sql/opt/memo/statistics_builder.go` line 669 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/84927#-N7vQC098xrI3iOFWZrh:-N7vXyzLDjV5QQa-7ozo:b-gtk14o) ([raw file](https://github.com/cockroachdb/cockroach/blob/979b5fbc77430b3c24b891e3e9618652066602fc/pkg/sql/opt/memo/statistics_builder.go#L669)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

I think we can ensure we get both types of histograms by changing this slightly as follows:
```
if colStat, ok := stats.ColStats.Add(cols); ok {
  // Keep what's already here
} else if colStat.Histogram == nil && needHistogram && !invertedStatistic {
  col := cols.SingleColumn()
  colStat.Histogram = &props.Histogram{}
  colStat.Histogram.Init(sb.evalCtx, col, stat.Histogram())
}
```
This takes advantage of the fact that `stats.ColStats.Add(cols)` returns the existing statistic if `ok` is false.
</blockquote></details>

Sorry for being dense, but I still don't understand what situation this branch defends against that the code doesn't already handle. The code as written does handle finding both the forward and inverted statistic for a given column set regardless of where either is in the list of historical statistics, since the new branch on line 700 gets executed regardless of whether we already have a forward statistic for the column set.

The only situation I can think of where this would change behavior is something like this list of statistics for a column t:

1. a forward statistic with no histogram at time x
2. an inverted statistic with a histogram at time x
3. a forward statistic with a histogram at time x-1

Is this the situation you're thinking of too or am I still missing something?

**Review by jordanlewis — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/84927)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @mgartner and @rytaft)

___
*[`pkg/sql/opt/memo/statistics_builder.go` line 666 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/84927#-N7uv4I9-X5qDulf-h9x:-N7zhOh40VNwiTFPpP_7:b-60nt5i) ([raw file](https://github.com/cockroachdb/cockroach/blob/979b5fbc77430b3c24b891e3e9618652066602fc/pkg/sql/opt/memo/statistics_builder.go#L666)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

nit: can we remove the double-negative and change this to `histogramIsBytes`?
</blockquote></details>

I'm not sure - would we ever get into a situation in which the histogram contains all null buckets? If so, we wouldn't be able to guarantee that the histogram was all bytes, just that it had no non-bytes buckets. That's why I named it this way.
___
*[`pkg/sql/opt/memo/statistics_builder.go` line 687 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/84927#-N7uuaetE-_TD6bkZU_H:-N7zhLyS9wqikQexigTg:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/979b5fbc77430b3c24b891e3e9618652066602fc/pkg/sql/opt/memo/statistics_builder.go#L687)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

I don't think you need to do this anymore
</blockquote></details>

Done.

**Review by rytaft — COMMENTED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/84927)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @jordanlewis, @mgartner, and @rytaft)

___
*[`pkg/sql/opt/memo/statistics_builder.go` line 666 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/84927#-N7uv4I9-X5qDulf-h9x:-N7zki5MBcrlKive0_vq:b-di02ah) ([raw file](https://github.com/cockroachdb/cockroach/blob/979b5fbc77430b3c24b891e3e9618652066602fc/pkg/sql/opt/memo/statistics_builder.go#L666)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

I'm not sure - would we ever get into a situation in which the histogram contains all null buckets? If so, we wouldn't be able to guarantee that the histogram was all bytes, just that it had no non-bytes buckets. That's why I named it this way.
</blockquote></details>

I think that could happen if every row in the table is NULL. Maybe the better question is whether we would want to default to creating an inverted or a forward histogram in this case. I'm not sure it really matters in most cases, since I think we should be smart enough to just use the NULL counts and row counts directly to get the correct selectivity even without a histogram. The case where it might matter is if you implement my proposed change below to go back and add a forward histogram when one is found. In particular, if the most recent stats show a table with all NULLs, but historical stats have some non-nulls, we could end up using stale stats.

Alternatively, we could update the `TableStatistic` interface to include a `HistogramType` function that returns the type directly (then we wouldn't need to guess and you can get rid of the `histogramIsNonBytes` function). This info should be available with a bit of plumbing. If you think that's a better route, I'm happy to open a separate PR with that change.

Regardless, it would be good to add a test for this case.
___
*[`pkg/sql/opt/memo/statistics_builder.go` line 669 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/84927#-N7vQC098xrI3iOFWZrh:-N7zqCfh4WvRBgHPy7G4:b-xnjnor) ([raw file](https://github.com/cockroachdb/cockroach/blob/979b5fbc77430b3c24b891e3e9618652066602fc/pkg/sql/opt/memo/statistics_builder.go#L669)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

Sorry for being dense, but I still don't understand what situation this branch defends against that the code doesn't already handle. The code as written does handle finding both the forward and inverted statistic for a given column set regardless of where either is in the list of historical statistics, since the new branch on line 700 gets executed regardless of whether we already have a forward statistic for the column set.

The only situation I can think of where this would change behavior is something like this list of statistics for a column t:

1. a forward statistic with no histogram at time x
2. an inverted statistic with a histogram at time x
3. a forward statistic with a histogram at time x-1

Is this the situation you're thinking of too or am I still missing something? 

</blockquote></details>

I'm thinking of this:
1. an inverted statistic on column c with a histogram at time x
2. a forward statistic on column c with a histogram at time x
3. ... more stats ...

For the first statistic, we will add a forward stat for column c with no histogram, and an inverted stat with a histogram. Once we get to the second statistic, as the code is currently written, we will see that a forward stat has already been added and it will be a no-op. My proposed change would ensure that we still save the histogram for this case.

As an alternative, you could just not add the forward stat if `invertedStatistic` is true. That might also work.

**Review by jordanlewis — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/84927)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @mgartner and @rytaft)

___
*[`pkg/sql/opt/memo/statistics_builder.go` line 666 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/84927#-N7uv4I9-X5qDulf-h9x:-N81yOOe-1DFFJbFJ8-c:b-uoiwse) ([raw file](https://github.com/cockroachdb/cockroach/blob/979b5fbc77430b3c24b891e3e9618652066602fc/pkg/sql/opt/memo/statistics_builder.go#L666)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

I think that could happen if every row in the table is NULL. Maybe the better question is whether we would want to default to creating an inverted or a forward histogram in this case. I'm not sure it really matters in most cases, since I think we should be smart enough to just use the NULL counts and row counts directly to get the correct selectivity even without a histogram. The case where it might matter is if you implement my proposed change below to go back and add a forward histogram when one is found. In particular, if the most recent stats show a table with all NULLs, but historical stats have some non-nulls, we could end up using stale stats.

Alternatively, we could update the `TableStatistic` interface to include a `HistogramType` function that returns the type directly (then we wouldn't need to guess and you can get rid of the `histogramIsNonBytes` function). This info should be available with a bit of plumbing. If you think that's a better route, I'm happy to open a separate PR with that change.

Regardless, it would be good to add a test for this case.
</blockquote></details>

Great point, I took a look and your suggestion was very simple to implement (no plumbing was necessary, the actual data was available on both the test catalog and production stat struct as-is) so I just went ahead and did it.

In the case where the data is all null, no histogram is created at all, so I think we're fine.

```
      {
          "avg_size": 0,
          "columns": [
              "a"
          ],
          "created_at": "2022-07-28 04:05:28.848149",
          "distinct_count": 1,
          "histo_col_type": "",
          "null_count": 3,
          "row_count": 3
      }
```
___
*[`pkg/sql/opt/memo/statistics_builder.go` line 669 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/84927#-N7vQC098xrI3iOFWZrh:-N7zvxgi43dLVgxSm1io:bnvm4ju) ([raw file](https://github.com/cockroachdb/cockroach/blob/979b5fbc77430b3c24b891e3e9618652066602fc/pkg/sql/opt/memo/statistics_builder.go#L669)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

I'm thinking of this:
1. an inverted statistic on column c with a histogram at time x
2. a forward statistic on column c with a histogram at time x
3. ... more stats ...

For the first statistic, we will add a forward stat for column c with no histogram, and an inverted stat with a histogram. Once we get to the second statistic, as the code is currently written, we will see that a forward stat has already been added and it will be a no-op. My proposed change would ensure that we still save the histogram for this case.

As an alternative, you could just not add the forward stat if `invertedStatistic` is true. That might also work.

</blockquote></details>

Ahh, I see, thanks for spelling it out, you're totally right of course. 

We can't not add the forward stat if `invertedStatistic` is true, because in the case of ordinary inverted index types like JSON, we don't ever collect forward stats on that type - so we'd be missing out on the non-histogram stats.

I think your example snippet is also going to do something slightly weird - it has the potential of creating a statistic that consists of counts from an inverted histogram at time t, and a histogram from a forward histogram at a time t-1 when the counts were different.

The updated code now takes the entirety of the most recent forward statistic that has a histogram... I think that is the optimal thing.

And confirmed this change updated a test case in the trigram stats test file for the better! It now can use a forward histogram for a forward scan even though an inverted histogram on the same column was present.

**Review by jordanlewis — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/84927)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @mgartner and @rytaft)

___
*[`pkg/sql/opt/memo/statistics_builder.go` line 669 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/84927#-N7vQC098xrI3iOFWZrh:-N82-GkUEwiP6_2ASNx-:b-9khh0o) ([raw file](https://github.com/cockroachdb/cockroach/blob/979b5fbc77430b3c24b891e3e9618652066602fc/pkg/sql/opt/memo/statistics_builder.go#L669)):*
Wait, is this still going to present a problem in a different case? You mention something similar above:

> In particular, if the most recent stats show a table with all NULLs, but historical stats have some non-nulls, we could end up using stale stats.

time t-1: statistic with forward histogram for column c
time t: user truncates table
time t+1: statistic with no histogram because the table is empty

In this case, I think the code I just pushed (and your suggested snippet?) would fall into a similar hazard. The newest statistic is missing a histogram because the table is empty, so we replace it with an older statistic that *has* a histogram, that's now stale and out of date.

We could avoid this hazard with an extra bit per `ColumnStatistic` that is set to true if the information was derived from an inverted histogram, I guess...

**Review by jordanlewis — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/84927)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @mgartner and @rytaft)

___
*[`pkg/sql/opt/memo/statistics_builder.go` line 669 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/84927#-N7vQC098xrI3iOFWZrh:-N8253TA65R2HzArU90w:bi8mg9b) ([raw file](https://github.com/cockroachdb/cockroach/blob/979b5fbc77430b3c24b891e3e9618652066602fc/pkg/sql/opt/memo/statistics_builder.go#L669)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

Wait, is this still going to present a problem in a different case? You mention something similar above:

> In particular, if the most recent stats show a table with all NULLs, but historical stats have some non-nulls, we could end up using stale stats.

time t-1: statistic with forward histogram for column c
time t: user truncates table
time t+1: statistic with no histogram because the table is empty

In this case, I think the code I just pushed (and your suggested snippet?) would fall into a similar hazard. The newest statistic is missing a histogram because the table is empty, so we replace it with an older statistic that *has* a histogram, that's now stale and out of date.

We could avoid this hazard with an extra bit per `ColumnStatistic` that is set to true if the information was derived from an inverted histogram, I guess...
</blockquote></details>

I added a commit on top that does this, but it bloats the memo by a bit. PTAL. Bummed that this keeps increasing in complexity.

**Review by rytaft — COMMENTED** [review]
> Reviewed 4 of 5 files at r6, 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/84927)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @jordanlewis, @mgartner, and @rytaft)

___
*[`pkg/sql/opt/memo/statistics_builder.go` line 666 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/84927#-N7uv4I9-X5qDulf-h9x:-N83vRS19V83wQy3jSe-:b-83sjoh) ([raw file](https://github.com/cockroachdb/cockroach/blob/979b5fbc77430b3c24b891e3e9618652066602fc/pkg/sql/opt/memo/statistics_builder.go#L666)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

Great point, I took a look and your suggestion was very simple to implement (no plumbing was necessary, the actual data was available on both the test catalog and production stat struct as-is) so I just went ahead and did it.

In the case where the data is all null, no histogram is created at all, so I think we're fine.

```
      {
          "avg_size": 0,
          "columns": [
              "a"
          ],
          "created_at": "2022-07-28 04:05:28.848149",
          "distinct_count": 1,
          "histo_col_type": "",
          "null_count": 3,
          "row_count": 3
      }
```
</blockquote></details>

Nice!
___
*[`pkg/sql/opt/memo/statistics_builder.go` line 669 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/84927#-N7vQC098xrI3iOFWZrh:-N83z0YU4Orb-ahPoCUG:b-ee15r6) ([raw file](https://github.com/cockroachdb/cockroach/blob/979b5fbc77430b3c24b891e3e9618652066602fc/pkg/sql/opt/memo/statistics_builder.go#L669)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

I added a commit on top that does this, but it bloats the memo by a bit. PTAL. Bummed that this keeps increasing in complexity.
</blockquote></details>

Is there a way to avoid storing the extra bit in the `ColStatsMap` since we don't need this info outside of this function? One idea is to just check if we already have an inverted stat for this column. e.g., make a function like this:
```
func alreadyHasInvertedStat(invColOrds int[], stats *props.Statistics) {
  if len(invColOrds) > 0 {
    invCol := tabID.ColumnID(invColOrds[0])
    invCols := opt.MakeColSet(invCol)
    _, ok := stats.ColStats.Lookup(invCols)
    return ok
  }
  return false
}
```

**Comment by rytaft** [comment]
*[`pkg/sql/opt/memo/statistics_builder.go` line 669 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/84927#-N7vQC098xrI3iOFWZrh:-N84BjQO20GEChduLIoF:b2zch62) ([raw file](https://github.com/cockroachdb/cockroach/blob/979b5fbc77430b3c24b891e3e9618652066602fc/pkg/sql/opt/memo/statistics_builder.go#L669)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

Is there a way to avoid storing the extra bit in the `ColStatsMap` since we don't need this info outside of this function? One idea is to just check if we already have an inverted stat for this column. e.g., make a function like this:
```
func alreadyHasInvertedStat(invColOrds int[], stats *props.Statistics) {
  if len(invColOrds) > 0 {
    invCol := tabID.ColumnID(invColOrds[0])
    invCols := opt.MakeColSet(invCol)
    _, ok := stats.ColStats.Lookup(invCols)
    return ok
  }
  return false
}
```
</blockquote></details>

(BTW I didn't check if that compiles -- looks like there's at least a couple fixes needed)

**Review by jordanlewis — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/84927)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @mgartner and @rytaft)

___
*[`pkg/sql/opt/memo/statistics_builder.go` line 669 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/84927#-N7vQC098xrI3iOFWZrh:-N86qKd10otjKSPXpQyK:b-u83mow) ([raw file](https://github.com/cockroachdb/cockroach/blob/979b5fbc77430b3c24b891e3e9618652066602fc/pkg/sql/opt/memo/statistics_builder.go#L669)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

(BTW I didn't check if that compiles -- looks like there's at least a couple fixes needed)
</blockquote></details>

I moved the state into a map that we're already keeping around in the statsbuilder loop and added more tests that ensure we don't use old histograms even if new statistics have no histograms at all for both the inverted and forward case.

**Review by rytaft — APPROVED** [review]
:lgtm_strong: thanks for all your work on this!

> Reviewed 1 of 5 files at r3, 14 of 14 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/84927#-:-N8AG1pe9mU6r0jYi_hi:b-bfdssi)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @jordanlewis and @mgartner)

___
*[`pkg/sql/opt/memo/statistics_builder.go` line 686 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/84927#-N8AF-KHD-lvC9lMnPW4:-N8AF-KI6PozJ2Ee6Cjr:b-euma9k) ([raw file](https://github.com/cockroachdb/cockroach/blob/9a7000f080e8d7662e01d98bbc2380a08c606c48/pkg/sql/opt/memo/statistics_builder.go#L686)):*
> ```Go
> 				//    If these conditions hold, it means that the previous histogram
> 				//    we found for the current colset was derived from an inverted
> 				//    histogram, and therefore doesn't have a histogram at all, and the
> ```

nit: and therefore doesn't -> and therefore the existing forward statistic doesn't
___
*[`pkg/sql/opt/memo/statistics_builder.go` line 715 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/84927#-N8AEJ7q-9iFeUt6q9qw:-N8AEJ7rDcbMEy4C7rko:b-gmaohq) ([raw file](https://github.com/cockroachdb/cockroach/blob/9a7000f080e8d7662e01d98bbc2380a08c606c48/pkg/sql/opt/memo/statistics_builder.go#L715)):*
> ```Go
> 			// Add inverted histograms if necessary.
> 			if needHistogram && invertedStatistic {
> 				// Record the fact that we just added an inverted statistic to this
> ```

nit: just added -> are adding

**Review by jordanlewis — COMMENTED** [review]
Thanks for the patient reviews!

bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/84927#-:-N8AI08DDtWkSH0mTUkM:b96gj0y)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @mgartner and @rytaft)
