### PR TITLE
changefeedccl: fix data race in TestChangefeedIdleness

### LINKED ISSUE #148204: ccl/changefeedccl: TestChangefeedIdleness failed
ccl/changefeedccl.TestChangefeedIdleness [failed](https://tanzanite.cluster.engflow.com/invocations/default/9c82825a-69c4-4f86-b866-5b87d8db191b?testReportRun=3&testReportShard=2&testReportAttempt=1#targets-Ly9wa2cvY2NsL2NoYW5nZWZlZWRjY2w6Y2hhbmdlZmVlZGNjbF90ZXN0) on release-24.3 @ [e8fc847e816ca85232d6320154b854cd83016b8d](https://github.com/cockroachdb/cockroach/commits/e8fc847e816ca85232d6320154b854cd83016b8d):

```
Write at 0x00c00ca64768 by goroutine 17487:
  runtime.racewrite()
      <autogenerated>:1 +0x1e
  github.com/cockroachdb/cockroach/pkg/ccl/changefeedccl.TestChangefeedIdleness.func1()
      pkg/ccl/changefeedccl/changefeed_test.go:542 +0x851
  github.com/cockroachdb/cockroach/pkg/ccl/changefeedccl.cdcTestNamed.func1()
      pkg/ccl/changefeedccl/helpers_test.go:1140 +0x93
  github.com/cockroachdb/cockroach/pkg/ccl/changefeedccl.cdcTestNamedWithSystem.func1()
      pkg/ccl/changefeedccl/helpers_test.go:1175 +0x40d
  testing.tRunner()
      GOROOT/src/testing/testing.go:1689 +0x21e
  testing.(*T).Run.gowrap1()
      GOROOT/src/testing/testing.go:1742 +0x44

Previous read at 0x00c00ca64768 by goroutine 30431:
  runtime.raceread()
      <autogenerated>:1 +0x1e
  github.com/cockroachdb/cockroach/pkg/ccl/changefeedccl.TestChangefeedIdleness.func1.1()
      pkg/ccl/changefeedccl/changefeed_test.go:494 +0x4a
  github.com/cockroachdb/cockroach/pkg/ccl/changefeedccl.TestChangefeedIdleness.func1.gowrap3()
      pkg/ccl/changefeedccl/changefeed_test.go:541 +0x35

Goroutine 17487 (running) created at:
  testing.(*T).Run()
      GOROOT/src/testing/testing.go:1742 +0x825
  github.com/cockroachdb/cockroach/pkg/ccl/changefeedccl.cdcTestNamedWithSystem()
      pkg/ccl/changefeedccl/helpers_test.go:1165 +0x4ba
  github.com/cockroachdb/cockroach/pkg/ccl/changefeedccl.cdcTestNamed()
      pkg/ccl/changefeedccl/helpers_test.go:1142 +0xbd
  github.com/cockroachdb/cockroach/pkg/ccl/changefeedccl.cdcTest()
      pkg/ccl/changefeedccl/helpers_test.go:1135 +0x17d
  github.com/cockroachdb/cockroach/pkg/ccl/changefeedccl.TestChangefeedIdleness()
      pkg/ccl/changefeedccl/changefeed_test.go:482 +0x111
  testing.tRunner()
      GOROOT/src/testing/testing.go:1689 +0x21e
  testing.(*T).Run.gowrap1()
      GOROOT/src/testing/testing.go:1742 +0x44

Goroutine 30431 (running) created at:
  github.com/cockroachdb/cockroach/pkg/ccl/changefeedccl.TestChangefeedIdleness.func1()
      pkg/ccl/changefeedccl/changefeed_test.go:541 +0x844
  github.com/cockroachdb/cockroach/pkg/ccl/changefeedccl.cdcTestNamed.func1()
      pkg/ccl/changefeedccl/helpers_test.go:1140 +0x93
  github.com/cockroachdb/cockroach/pkg/ccl/changefeedccl.cdcTestNamedWithSystem.func1()
      pkg/ccl/changefeedccl/helpers_test.go:1175 +0x40d
  testing.tRunner()
      GOROOT/src/testing/testing.go:1689 +0x21e
  testing.(*T).Run.gowrap1()
      GOROOT/src/testing/testing.go:1742 +0x44
==================
```

Parameters:
 - <code>attempt=1</code>
 - <code>race=true</code>
 - <code>run=3</code>
 - <code>shard=2</code>
<details><summary>Help</summary>
<p>

See also: [How To Investigate a Go Test Failure \(internal\)](https://cockroachlabs.atlassian.net/l/c/HgfXfJgM)
</p>
</details>
/cc @cockroachdb/cdc
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*TestChangefeedIdleness.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/bazci/githubpost/issues)

</sub>

Jira issue: CRDB-51473

### PR DESCRIPTION
**Pull request by aerfrei**
changefeedccl: fix data race in TestChangefeedIdleness
Previously, we saw a failure under race between WaitGroup
Add and Wait calls. The fix removes the WaitGroup pattern
entirely (avoiding the race) and splits the test into two
focused tests for better isolation of future failures:

- TestChangefeedIdlenessPauseResumeCancel: tests idle count transitions
  during pause/resume/cancel operations.
- TestChangefeedIdlenessWithWorkload: tests non-idle
  transitions with a throttled workload.

Fixes: https://github.com/cockroachdb/cockroach/issues/148204
Release note: None

### CODE REVIEW

File: pkg/ccl/changefeedccl/changefeed_test.go [hunk 1]
```diff
@@ -973,13 +949,68 @@ func TestChangefeedIdleness(t *testing.T) {
...
+		done := make(chan struct{})
+		stopWorkload := sync.OnceFunc(func() { close(done) })
+		defer stopWorkload()
+		go func() {
+			for {
+				select {
+				case <-done:
+					return
+				default:
+					// We use s.DB.Exec (not sqlDB.Exec) because t.Fatal from a
```
Comment (jeffswenson) [inline pkg/ccl/changefeedccl/changefeed_test.go]: Fatal on a non-test goroutine should still fail the test as long as it is called before the main goroutine exits.

You could also use an errgroup here.

group := errgroup.WithContext()
group.Go(func() {
   if _, err := sql.DB.Exec(...); err != nil {
      return err
   }
}
require.NoError(t, group.Wait())

I think it is generally best to check errors in tests because ignoring them can make it hard to debug a test failure.

File: pkg/ccl/changefeedccl/changefeed_test.go [hunk 2]
```diff
@@ -923,33 +923,13 @@ func TestChangefeedIdleness(t *testing.T) {
 
 		registry := s.Server.JobRegistry().(*jobs.Registry)
 		currentlyIdle := registry.MetricsStruct().JobMetrics[jobspb.TypeChangefeed].CurrentlyIdle
-		// Use a wait group for cases when the number of idle changefeeds temporarily
-		// decreases, to avoid a race condition where the changefeed becomes idle
-		// before the idleness is checked.
-		var wg sync.WaitGroup
 		waitForIdleCount := func(numIdle int64) {
```
Comment (KeithCh) [inline pkg/ccl/changefeedccl/changefeed_test.go:926]: Let's move this to a helper that takes in `currentlyIdle` and `numIdle`.

Comment (aerfrei) [reply pkg/ccl/changefeedccl/changefeed_test.go:926]: I'm not sure I think it's worth it for short function that we only use twice. It might add more redirection and make the test a little harder to reason about. 

Since the function involves refetching currentlyIdle in a retry loop I think it would only be able to take in numIdle the way it currently does.

**Review by jeffswenson — APPROVED** [review]
LGTM

**Review by KeithCh — APPROVED** [review]
