### PR TITLE
apply: improve Asserter logging and error handling

### LINKED ISSUE #157253: kv/kvnemesis: TestKVNemesisMultiNode_Restart_Liveness failed
kv/kvnemesis.TestKVNemesisMultiNode_Restart_Liveness [failed](https://mesolite.cluster.engflow.com/invocations/default/3721049e-13d5-47d7-9a39-a60149de968a?testReportRun=2&testReportShard=1&testReportAttempt=1#targets-Ly9wa2cva3Yva3ZuZW1lc2lzOmt2bmVtZXNpc190ZXN0) on master @ [b6a0efc2d0a69c31b76ea7083e3fc3e71b2cee01](https://github.com/cockroachdb/cockroach/commits/b6a0efc2d0a69c31b76ea7083e3fc3e71b2cee01):

```
pkg/util/stop/stopper.go:350 stop.(*Stopper).RunTaskWithErr ???
pkg/kv/kvserver/store_raft.go:279 kvserver.(*Store).HandleSnapshot ???
pkg/kv/kvserver/raft_transport.go:565 kvserver.(*RaftTransport).raftSnapshot ???
pkg/kv/kvserver/raft_transport.go:543 kvserver.(*RaftTransport).RaftSnapshot ???
bazel-out/k8-fastbuild/bin/pkg/kv/kvserver/kvserver_go_proto_/github.com/cockroachdb/cockroach/pkg/kv/kvserver/storage_services.pb.go:266 kvserver._MultiRaft_RaftSnapshot_Handler ???
pkg/util/tracing/grpcinterceptor/grpc_interceptor.go:136 rpc.NewServerEx.StreamServerInterceptor.func13 ???
external/org_golang_google_grpc/server.go:1503 grpc.getChainStreamHandler.func1 ???
pkg/rpc/context.go:189 rpc.NewServerEx.func4 ???
external/org_golang_google_grpc/server.go:1503 grpc.getChainStreamHandler.func1.getChainStreamHandler.1 ???
pkg/rpc/auth.go:192 rpc.kvAuth.streamInterceptor ???
external/org_golang_google_grpc/server.go:1503 grpc.getChainStreamHandler.func1 ???
pkg/rpc/context.go:146 rpc.NewServerEx.func2.1 ???
pkg/util/stop/stopper.go:350 stop.(*Stopper).RunTaskWithErr ???
pkg/rpc/context.go:145 rpc.NewServerEx.func2 ???
external/org_golang_google_grpc/server.go:1494 grpc.NewServer.chainStreamServerInterceptors.chainStreamInterceptors.func2 ???
external/org_golang_google_grpc/server.go:1658 grpc.(*Server).processStreamingRPC ???
external/org_golang_google_grpc/server.go:1739 grpc.(*Server).handleStream ???
external/org_golang_google_grpc/server.go:970 grpc.(*Server).serveStreams.func1.1 ???

goroutine 20025835 lock 0xc005276f70
GOROOT/src/sync/atomic/type.go:18 atomic.(*Bool).Load ??? <<<<<
pkg/kv/kvserver/replica.go:310 kvserver.(*ReplicaMutex).Lock ???
external/com_github_sasha_s_go_deadlock/deadlock.go:116 go-deadlock.(*RWMutex).Lock ???
pkg/kv/kvserver/replica_raft.go:1159 kvserver.(*Replica).handleRaftReadyRaftMuLocked ???
pkg/kv/kvserver/store_raft.go:555 kvserver.(*Store).processRaftSnapshotRequest.func1 ???
pkg/kv/kvserver/store_raft.go:432 kvserver.(*Store).withReplicaForRequest ???
pkg/kv/kvserver/store_raft.go:579 kvserver.(*Store).processRaftSnapshotRequest ???
pkg/kv/kvserver/store_snapshot.go:602 kvserver.(*Store).receiveSnapshot ???
pkg/kv/kvserver/store_raft.go:282 kvserver.(*Store).HandleSnapshot.func1 ???
pkg/util/stop/stopper.go:350 stop.(*Stopper).RunTaskWithErr ???
pkg/kv/kvserver/store_raft.go:279 kvserver.(*Store).HandleSnapshot ???
pkg/kv/kvserver/raft_transport.go:565 kvserver.(*RaftTransport).raftSnapshot ???
pkg/kv/kvserver/raft_transport.go:543 kvserver.(*RaftTransport).RaftSnapshot ???
bazel-out/k8-fastbuild/bin/pkg/kv/kvserver/kvserver_go_proto_/github.com/cockroachdb/cockroach/pkg/kv/kvserver/storage_services.pb.go:266 kvserver._MultiRaft_RaftSnapshot_Handler ???
pkg/util/tracing/grpcinterceptor/grpc_interceptor.go:136 rpc.NewServerEx.StreamServerInterceptor.func13 ???
external/org_golang_google_grpc/server.go:1503 grpc.getChainStreamHandler.func1 ???
pkg/rpc/context.go:189 rpc.NewServerEx.func4 ???
external/org_golang_google_grpc/server.go:1503 grpc.getChainStreamHandler.func1.getChainStreamHandler.1 ???
pkg/rpc/auth.go:192 rpc.kvAuth.streamInterceptor ???
external/org_golang_google_grpc/server.go:1503 grpc.getChainStreamHandler.func1 ???
pkg/rpc/context.go:146 rpc.NewServerEx.func2.1 ???
pkg/util/stop/stopper.go:350 stop.(*Stopper).RunTaskWithErr ???
pkg/rpc/context.go:145 rpc.NewServerEx.func2 ???
external/org_golang_google_grpc/server.go:1494 grpc.NewServer.chainStreamServerInterceptors.chainStreamInterceptors.func2 ???
external/org_golang_google_grpc/server.go:1658 grpc.(*Server).processStreamingRPC ???
external/org_golang_google_grpc/server.go:1739 grpc.(*Server).handleStream ???
external/org_golang_google_grpc/server.go:970 grpc.(*Server).serveStreams.func1.1 ???



```

Parameters:
 - <code>attempt=1</code>
 - <code>deadlock=true</code>
 - <code>run=2</code>
 - <code>shard=1</code>
<details><summary>Help</summary>
<p>

See also: [How To Investigate a Go Test Failure \(internal\)](https://cockroachlabs.atlassian.net/l/c/HgfXfJgM)
</p>
</details>
/cc @cockroachdb/kv-triage
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*TestKVNemesisMultiNode_Restart_Liveness.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/bazci/githubpost/issues)

</sub>

Jira issue: CRDB-56437

### PR DESCRIPTION
**Pull request by miraradeva**
Previously, the `Asserter` would panic if it found any discrepancy. This usually works as expected and the panic message in the test failure (e.g. kvnemesis). However, it's possible that the goroutine that invoked the `Asserter` is in a part of the code that doesn't check/recover from panics (e.g. the `defer` logic in `processRaftSnapshotRequest`).

This commit changes the panics to `log.Fatalf`s to have a better chance of logging these. It also improves one of the log messages in the `Asserter` to print out the log state in case of a discrepancy.

Closes: #157253

Release note: None

### CODE REVIEW

File: pkg/kv/kvserver/apply/asserter.go [hunk 1]
```diff
@@ -242,8 +245,8 @@ func (r *rangeAsserter) apply(
 	}
 
 	fail := func(msg string, args ...interface{}) {
-		panic(fmt.Sprintf("r%d/%d: %s (%s)\ndata: %x",
-			r.rangeID, replicaID, fmt.Sprintf(msg, args...), entry, raftEntry.Data))
+		log.KvExec.Fatalf(context.Background(),"r%d/%d: %s (%s)\ndata: %x",
```
Comment (pav-kv) [inline pkg/kv/kvserver/apply/asserter.go]: Linter checks expect a whitespace here and above.

**Review by pav-kv — APPROVED** [review]
Thanks!
