### PR TITLE
Don't fail on missing system config.

### LINKED ISSUE #2566: failed to update Store after split: no system config available
The following test appears to have failed:

[#7681](https://circleci.com/gh/cockroachdb/cockroach/7681):

```
	/go/src/github.com/cockroachdb/cockroach/kv/txn_coord_sender.go:736 +0x4d
github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunAsyncTask.func1(0xc8203f9360, 0xc820017500, 0xc8203f93a0, 0x1a)
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:129 +0x2b
created by github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunAsyncTask
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:131 +0x271
FAIL	github.com/cockroachdb/cockroach/storage	24.499s
=== RUN   TestBatchBasics
I0919 18:19:45.026663 936 storage/engine/rocksdb.go:122  closing in-memory rocksdb instance
--- PASS: TestBatchBasics (0.01s)
=== RUN   TestBatchGet
I0919 18:19:45.031143 936 storage/engine/rocksdb.go:122  closing in-memory rocksdb instance
--- PASS: TestBatchGet (0.01s)
=== RUN   TestBatchMerge
I0919 18:19:45.037866 936 storage/engine/rocksdb.go:122  closing in-memory rocksdb instance
--- PASS: TestBatchMerge (0.00s)
=== RUN   TestBatchProto

```
Please assign, take a look and update the issue accordingly.

### PR DESCRIPTION
**Pull request by mberhault**
Fixes #2566

When the system config is not loaded, MaxBytes will remain 0 and
be ignored for split purposes.
It will be properly updated the next time the system config callback
runs.

### CODE REVIEW

File: storage/replica_raftstorage.go [hunk 1]
```diff
@@ -351,7 +351,10 @@ func (r *Replica) updateRangeInfo() error {
 	// Load the system config.
 	cfg := r.rm.Gossip().GetSystemConfig()
 	if cfg == nil {
-		return fmt.Errorf("no system config available")
+		// This could be before the system config was ever gossiped,
+		// or it expired. Let the gossip callback set the info.
+		log.Warningf("no system config available, cannot determine range MaxBytes")
```
Comment (tamird) [inline storage/replica_raftstorage.go]: can you make this an `errors.New` and check equality in the caller? That would make me feel better than returning `nil`.

Comment (mberhault) [inline storage/replica_raftstorage.go]: why? we're now saying this is no longer an error, merely an acceptable possibility.

Comment (tamird) [inline storage/replica_raftstorage.go]: well, because in this case `updateRangeInfo` didn't actually do its work, so it did not complete without error. I think what we're saying is that failure in this function is sometimes acceptable. We can either model that as a particular error that is safe to ignore, or break the function into two: one which is allowed to fail, and one which is not.

**Comment by tschottdorf** [comment]
Is there technically a race here in which `updateRangeInfo` fails while the gossip callback runs (so that the new range will never get its `MaxBytes` set)?

**Comment by mberhault** [comment]
splits are fine. Not sure about snapshots, I haven't traced through those, but as long as replicas are added to the store first, they'll be fine as well.

File: storage/replica_raftstorage.go (hunk 1 above)
Comment (mberhault) [inline storage/replica_raftstorage.go]: this is the last call to `GetSystemConfig` that throws an error. Everything else just logs a message. Just like failing on this is odd, so would returning an error just in this case.

Comment (tamird) [inline storage/replica_raftstorage.go]: I'm not sold; I'd rather this be broken into two functions (or just change this function to take `cfg` as an argument) with differing error semantics.

LGTM as-is for the purpose of fixing the flaky tests.

**Comment by tschottdorf** [comment]
yeah, `SplitRange` is ok because the call to `updateRangeInfo` is under the store lock (so if the callback comes in in parallel, it's processed strictly before or strictly after). Could you add a comment in the call site at `SplitRange`? For snapshotting, that seems like it would race (so you'd end up with a new range that wouldn't ever split). That's probably worth a new issue.
LGTM otherwise.

**Comment by tamird** [comment]
Really seeing a ton of these now.

**Comment by mberhault** [comment]
Filed #2649
