### PR TITLE
roachtest,sqlinstance: fix multitenant_upgrade test

### LINKED ISSUE #81506: roachtest: acceptance/multitenant failed
roachtest.acceptance/multitenant [failed](https://teamcity.cockroachdb.com/viewLog.html?buildId=5202348&tab=buildLog) with [artifacts](https://teamcity.cockroachdb.com/viewLog.html?buildId=5202348&tab=artifacts#/acceptance/multitenant) on master @ [ce66acdbba801de88f1dd645eaedeb3834f23dbd](https://github.com/cockroachdb/cockroach/commits/ce66acdbba801de88f1dd645eaedeb3834f23dbd):

```
The test failed on branch=master, cloud=gce:
test artifacts and logs in: /artifacts/acceptance/multitenant/run_1
	sql_runner.go:148,sql_runner.go:177,multitenant_upgrade.go:314,multitenant.go:46,acceptance.go:107,test_runner.go:876: error executing 'SELECT * FROM foo LIMIT 1': pq: failed to resolve n4: unable to look up descriptor for nsql4
```
<details><summary>Help</summary>
<p>

See: [roachtest README](https://github.com/cockroachdb/cockroach/blob/master/pkg/cmd/roachtest/README.md)

See: [How To Investigate \(internal\)](https://cockroachlabs.atlassian.net/l/c/SSSBr8c7)

</p>
</details>
/cc @cockroachdb/kv-triage
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*acceptance/multitenant.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)
</sub>

Jira issue: CRDB-15156

### LINKED ISSUE #81517: roachtest: multitenant-upgrade failed
roachtest.multitenant-upgrade [failed](https://teamcity.cockroachdb.com/viewLog.html?buildId=5202348&tab=buildLog) with [artifacts](https://teamcity.cockroachdb.com/viewLog.html?buildId=5202348&tab=artifacts#/multitenant-upgrade) on master @ [ce66acdbba801de88f1dd645eaedeb3834f23dbd](https://github.com/cockroachdb/cockroach/commits/ce66acdbba801de88f1dd645eaedeb3834f23dbd):

```
		Wraps: (2) cluster.RunE
		Wraps: (3) context canceled
		Error types: (1) *withstack.withStack (2) *errutil.withPrefix (3) *errors.errorString

	cluster.go:1936,multitenant_utils.go:92,panic.go:1038,test_impl.go:254,cluster.go:1936,multitenant_utils.go:92,panic.go:1038,test_impl.go:254,cluster.go:1936,multitenant_utils.go:92,panic.go:1038,test_impl.go:260,sql_runner.go:148,sql_runner.go:177,multitenant_upgrade.go:314,multitenant_upgrade.go:177,multitenant_upgrade.go:35,test_runner.go:876: cluster.RunE: context canceled
		(1) attached stack trace
		  -- stack trace:
		  | main.(*clusterImpl).RunE
		  | 	main/pkg/cmd/roachtest/cluster.go:1953
		  | main.(*clusterImpl).Run
		  | 	main/pkg/cmd/roachtest/cluster.go:1934
		  | github.com/cockroachdb/cockroach/pkg/cmd/roachtest/tests.(*tenantNode).stop
		  | 	github.com/cockroachdb/cockroach/pkg/cmd/roachtest/tests/multitenant_utils.go:92
		  | runtime.gopanic
		  | 	GOROOT/src/runtime/panic.go:1038
		  | main.(*testImpl).Fatal
		  | 	main/pkg/cmd/roachtest/test_impl.go:254
		  | main.(*clusterImpl).Run
		  | 	main/pkg/cmd/roachtest/cluster.go:1936
		  | github.com/cockroachdb/cockroach/pkg/cmd/roachtest/tests.(*tenantNode).stop
		  | 	github.com/cockroachdb/cockroach/pkg/cmd/roachtest/tests/multitenant_utils.go:92
		  | runtime.gopanic
		  | 	GOROOT/src/runtime/panic.go:1038
		  | main.(*testImpl).Fatal
		  | 	main/pkg/cmd/roachtest/test_impl.go:254
		  | main.(*clusterImpl).Run
		  | 	main/pkg/cmd/roachtest/cluster.go:1936
		  | github.com/cockroachdb/cockroach/pkg/cmd/roachtest/tests.(*tenantNode).stop
		  | 	github.com/cockroachdb/cockroach/pkg/cmd/roachtest/tests/multitenant_utils.go:92
		  | runtime.gopanic
		  | 	GOROOT/src/runtime/panic.go:1038
		  | main.(*testImpl).Fatalf
		  | 	main/pkg/cmd/roachtest/test_impl.go:260
		  | github.com/cockroachdb/cockroach/pkg/testutils/sqlutils.(*SQLRunner).Query
		  | 	github.com/cockroachdb/cockroach/pkg/testutils/sqlutils/sql_runner.go:148
		  | github.com/cockroachdb/cockroach/pkg/testutils/sqlutils.(*SQLRunner).QueryStr
		  | 	github.com/cockroachdb/cockroach/pkg/testutils/sqlutils/sql_runner.go:177
		  | github.com/cockroachdb/cockroach/pkg/cmd/roachtest/tests.verifySQL
		  | 	github.com/cockroachdb/cockroach/pkg/cmd/roachtest/tests/multitenant_upgrade.go:314
		  | github.com/cockroachdb/cockroach/pkg/cmd/roachtest/tests.runMultiTenantUpgrade
		  | 	github.com/cockroachdb/cockroach/pkg/cmd/roachtest/tests/multitenant_upgrade.go:177
		  | github.com/cockroachdb/cockroach/pkg/cmd/roachtest/tests.registerMultiTenantUpgrade.func1
		  | 	github.com/cockroachdb/cockroach/pkg/cmd/roachtest/tests/multitenant_upgrade.go:35
		  | main.(*testRunner).runTest.func2
		  | 	main/pkg/cmd/roachtest/test_runner.go:876
		  | runtime.goexit
		  | 	GOROOT/src/runtime/asm_amd64.s:1581
		Wraps: (2) cluster.RunE
		Wraps: (3) context canceled
		Error types: (1) *withstack.withStack (2) *errutil.withPrefix (3) *errors.errorString
```
<details><summary>Help</summary>
<p>

See: [roachtest README](https://github.com/cockroachdb/cockroach/blob/master/pkg/cmd/roachtest/README.md)

See: [How To Investigate \(internal\)](https://cockroachlabs.atlassian.net/l/c/SSSBr8c7)

</p>
</details>
/cc @cockroachdb/kv-triage
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*multitenant-upgrade.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)
</sub>

Jira issue: CRDB-15107

### PR DESCRIPTION
**Pull request by rafiss**
fixes https://github.com/cockroachdb/cockroach/issues/81517
fixes https://github.com/cockroachdb/cockroach/issues/81506

### roachtest: fix ordering of multitenant upgrade test step

The tenant must be initialized by a system tenant using an old binary in
order to be running on an old binary itself.

Also, we no longer finalize the secondary tenant upgrade before finalizing the
system tenant upgrade.

### sqlinstance: use the correct timestamp when populating the cache

Previously, the sql instance cache would be populated using the
timestamp of the initial rangefeed scan. This was a bug since the
timestamp is used to determine which sql instance ID to use when there
are two IDs for the same address (i.e., it should use the most recent
one).

This caused problems if a tenant node was shutdown, then started with
the same address. Other layers like DistSQL would try to route requests
to an old sql instance, which would actually be the same as the
requesting node.

Release note: None

Release justification: test only change, and critical bug fix

### CODE REVIEW

File: pkg/sql/sqlinstance/instancestorage/instancereader.go [hunk 1]
```diff
@@ -162,6 +162,7 @@ func (r *Reader) maybeStartRangeFeed(ctx context.Context) *rangefeed.RangeFeed {
 		updateCacheFn,
 		rangefeed.WithInitialScan(initialScanDoneFn),
 		rangefeed.WithOnInitialScanError(initialScanErrFn),
+		rangefeed.WithRowTimestampInInitialScan(true),
```
Comment (ajwerner) [inline pkg/sql/sqlinstance/instancestorage/instancereader.go:165]: honestly, this is the problem with functional options :(

**Review by ajwerner — APPROVED** [review]
LGTM!

**Comment by rafiss** [comment]
tftr!

bors r=ajwerner
