### PR TITLE
changefeedccl: remove fixed latency checks from pts benchmark test

### LINKED ISSUE #152903: roachtest: cdc/multi-table-pts-benchmark/per-table-pts=false/num-tables=50000/num-ranges=1 failed
roachtest.cdc/multi-table-pts-benchmark/per-table-pts=false/num-tables=50000/num-ranges=1 [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/20421799?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/20421799?buildTab=artifacts#/cdc/multi-table-pts-benchmark/per-table-pts=false/num-tables=50000/num-ranges=1) on master @ [9a77ab62090722887cc70dc1d33c1345a2d675a6](https://github.com/cockroachdb/cockroach/commits/9a77ab62090722887cc70dc1d33c1345a2d675a6):

```
(test_runner.go:1450).runTest: test timed out (1h0m0s)
test artifacts and logs in: /artifacts/cdc/multi-table-pts-benchmark/per-table-pts=false/num-tables=50000/num-ranges=1/run_1
```

Parameters:
 - <code>arch=amd64</code>
 - <code>cloud=gce</code>
 - <code>coverageBuild=false</code>
 - <code>cpu=16</code>
 - <code>encrypted=false</code>
 - <code>fs=ext4</code>
 - <code>localSSD=true</code>
 - <code>runtimeAssertionsBuild=false</code>
 - <code>ssd=0</code>
<details><summary>Help</summary>
<p>

See: [roachtest README](https://github.com/cockroachdb/cockroach/blob/master/pkg/cmd/roachtest/README.md)

See: [How To Investigate \(internal\)](https://cockroachlabs.atlassian.net/l/c/SSSBr8c7)

See: [Grafana](https://go.crdb.dev/roachtest-grafana/teamcity-20421799/cdc-multi-table-pts-benchmark-per-table-pts-false-num-tables-50/1756893344088/1756897438521)

</p>
</details>
/cc @cockroachdb/cdc
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*cdc/multi-table-pts-benchmark/per-table-pts=false/num-tables=50000/num-ranges=1.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/bazci/githubpost/issues)

</sub>

### LINKED ISSUE #153017: roachtest: cdc/multi-table-pts-benchmark/per-table-pts=true/num-tables=5000/num-ranges=10 failed
roachtest.cdc/multi-table-pts-benchmark/per-table-pts=true/num-tables=5000/num-ranges=10 [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyAwsBazel/20434226?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyAwsBazel/20434226?buildTab=artifacts#/cdc/multi-table-pts-benchmark/per-table-pts=true/num-tables=5000/num-ranges=10) on master @ [fa76ba12e60927d8aa5ebad0eb64221f121927de](https://github.com/cockroachdb/cockroach/commits/fa76ba12e60927d8aa5ebad0eb64221f121927de):

```
(cdc.go:4653).func2: observed value for metric changefeed_stage_pts_manage_latency over threshold. observedValue: 82337777.829596, threshold: 25000000.000000
(cdc.go:400).Close: error shutting down prometheus/grafana: context canceled
test artifacts and logs in: /artifacts/cdc/multi-table-pts-benchmark/per-table-pts=true/num-tables=5000/num-ranges=10/cpu_arch=arm64/run_1
```

Parameters:
 - <code>arch=arm64</code>
 - <code>cloud=aws</code>
 - <code>coverageBuild=false</code>
 - <code>cpu=16</code>
 - <code>encrypted=false</code>
 - <code>fs=ext4</code>
 - <code>localSSD=true</code>
 - <code>runtimeAssertionsBuild=false</code>
 - <code>ssd=0</code>
<details><summary>Help</summary>
<p>

See: [roachtest README](https://github.com/cockroachdb/cockroach/blob/master/pkg/cmd/roachtest/README.md)

See: [How To Investigate \(internal\)](https://cockroachlabs.atlassian.net/l/c/SSSBr8c7)

_Grafana is not yet available for aws clusters_</p>
</details>
/cc @cockroachdb/cdc
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*cdc/multi-table-pts-benchmark/per-table-pts=true/num-tables=5000/num-ranges=10.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/bazci/githubpost/issues)

</sub>

### LINKED ISSUE #154120: roachtest: cdc/multi-table-pts-benchmark/per-table-pts=false/num-tables=50000/num-ranges=1 failed
roachtest.cdc/multi-table-pts-benchmark/per-table-pts=false/num-tables=50000/num-ranges=1 [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyAwsBazel/20516655?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyAwsBazel/20516655?buildTab=artifacts#/cdc/multi-table-pts-benchmark/per-table-pts=false/num-tables=50000/num-ranges=1) on release-25.4 @ [9221c5318324b33455257088d3a48fae69346359](https://github.com/cockroachdb/cockroach/commits/9221c5318324b33455257088d3a48fae69346359):

```
(cdc.go:4951).func2: observed value for metric changefeed_stage_pts_create_latency over threshold. observedValue: 86564250.000000, threshold: 30000000.000000
(cdc.go:401).Close: error shutting down prometheus/grafana: context canceled
test artifacts and logs in: /artifacts/cdc/multi-table-pts-benchmark/per-table-pts=false/num-tables=50000/num-ranges=1/cpu_arch=arm64/run_1
```

Parameters:
 - <code>arch=arm64</code>
 - <code>cloud=aws</code>
 - <code>coverageBuild=false</code>
 - <code>cpu=16</code>
 - <code>encrypted=false</code>
 - <code>fs=ext4</code>
 - <code>localSSD=true</code>
 - <code>runtimeAssertionsBuild=false</code>
 - <code>ssd=0</code>
<details><summary>Help</summary>
<p>

See: [roachtest README](https://github.com/cockroachdb/cockroach/blob/master/pkg/cmd/roachtest/README.md)

See: [How To Investigate \(internal\)](https://cockroachlabs.atlassian.net/l/c/SSSBr8c7)

_Grafana is not yet available for aws clusters_</p>
</details>
<details><summary>Same failure on other branches</summary>
<p>

- #152903 roachtest: cdc/multi-table-pts-benchmark/per-table-pts=false/num-tables=50000/num-ranges=1 failed [A-cdc C-test-failure O-roachtest O-robot P-3 T-cdc branch-master]
</p>
</details>
/cc @cockroachdb/cdc
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*cdc/multi-table-pts-benchmark/per-table-pts=false/num-tables=50000/num-ranges=1.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/bazci/githubpost/issues)

</sub>

Jira issue: CRDB-54741

### LINKED ISSUE #154122: roachtest: cdc/multi-table-pts-benchmark/per-table-pts=true/num-tables=50000/num-ranges=1 failed
roachtest.cdc/multi-table-pts-benchmark/per-table-pts=true/num-tables=50000/num-ranges=1 [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyAwsBazel/20516655?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyAwsBazel/20516655?buildTab=artifacts#/cdc/multi-table-pts-benchmark/per-table-pts=true/num-tables=50000/num-ranges=1) on release-25.4 @ [9221c5318324b33455257088d3a48fae69346359](https://github.com/cockroachdb/cockroach/commits/9221c5318324b33455257088d3a48fae69346359):

```
(cdc.go:4951).func2: observed value for metric changefeed_stage_pts_create_latency over threshold. observedValue: 86684073.000000, threshold: 30000000.000000
(cdc.go:401).Close: error shutting down prometheus/grafana: context canceled
test artifacts and logs in: /artifacts/cdc/multi-table-pts-benchmark/per-table-pts=true/num-tables=50000/num-ranges=1/cpu_arch=arm64/run_1
```

Parameters:
 - <code>arch=arm64</code>
 - <code>cloud=aws</code>
 - <code>coverageBuild=false</code>
 - <code>cpu=16</code>
 - <code>encrypted=false</code>
 - <code>fs=ext4</code>
 - <code>localSSD=true</code>
 - <code>runtimeAssertionsBuild=false</code>
 - <code>ssd=0</code>
<details><summary>Help</summary>
<p>

See: [roachtest README](https://github.com/cockroachdb/cockroach/blob/master/pkg/cmd/roachtest/README.md)

See: [How To Investigate \(internal\)](https://cockroachlabs.atlassian.net/l/c/SSSBr8c7)

_Grafana is not yet available for aws clusters_</p>
</details>
<details><summary>Same failure on other branches</summary>
<p>

- #152900 roachtest: cdc/multi-table-pts-benchmark/per-table-pts=true/num-tables=50000/num-ranges=1 failed [A-cdc C-test-failure O-roachtest O-robot P-3 T-cdc branch-master]
</p>
</details>
/cc @cockroachdb/cdc
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*cdc/multi-table-pts-benchmark/per-table-pts=true/num-tables=50000/num-ranges=1.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/bazci/githubpost/issues)

</sub>

Jira issue: CRDB-54742

### LINKED ISSUE #154132: roachtest: cdc/multi-table-pts-benchmark/per-table-pts=true/num-tables=5000/num-ranges=10 failed
roachtest.cdc/multi-table-pts-benchmark/per-table-pts=true/num-tables=5000/num-ranges=10 [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/20516654?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/20516654?buildTab=artifacts#/cdc/multi-table-pts-benchmark/per-table-pts=true/num-tables=5000/num-ranges=10) on release-25.4 @ [9221c5318324b33455257088d3a48fae69346359](https://github.com/cockroachdb/cockroach/commits/9221c5318324b33455257088d3a48fae69346359):

```
(cdc.go:4951).func2: observed value for metric changefeed_stage_pts_manage_latency over threshold. observedValue: 94232961.165217, threshold: 30000000.000000
(cdc.go:401).Close: error shutting down prometheus/grafana: context canceled
test artifacts and logs in: /artifacts/cdc/multi-table-pts-benchmark/per-table-pts=true/num-tables=5000/num-ranges=10/run_1
```

Parameters:
 - <code>arch=amd64</code>
 - <code>cloud=gce</code>
 - <code>coverageBuild=false</code>
 - <code>cpu=16</code>
 - <code>encrypted=false</code>
 - <code>runtimeAssertionsBuild=false</code>
 - <code>ssd=0</code>
<details><summary>Help</summary>
<p>

See: [roachtest README](https://github.com/cockroachdb/cockroach/blob/master/pkg/cmd/roachtest/README.md)

See: [How To Investigate \(internal\)](https://cockroachlabs.atlassian.net/l/c/SSSBr8c7)

See: [Grafana](https://go.crdb.dev/roachtest-grafana/teamcity-20516654/cdc-multi-table-pts-benchmark-per-table-pts-true-num-tables-500/1758799347061/1758801602746)

</p>
</details>
<details><summary>Same failure on other branches</summary>
<p>

- #153017 roachtest: cdc/multi-table-pts-benchmark/per-table-pts=true/num-tables=5000/num-ranges=10 failed [A-cdc C-test-failure O-roachtest O-robot P-1 T-cdc X-duplicate branch-master]
</p>
</details>
/cc @cockroachdb/cdc
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*cdc/multi-table-pts-benchmark/per-table-pts=true/num-tables=5000/num-ranges=10.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/bazci/githubpost/issues)

</sub>

Jira issue: CRDB-54748

### LINKED ISSUE #154302: roachtest: cdc/multi-table-pts-benchmark/per-table-pts=true/num-tables=500/num-ranges=10 failed
roachtest.cdc/multi-table-pts-benchmark/per-table-pts=true/num-tables=500/num-ranges=10 [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyAwsBazel/20530008?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyAwsBazel/20530008?buildTab=artifacts#/cdc/multi-table-pts-benchmark/per-table-pts=true/num-tables=500/num-ranges=10) on release-25.4 @ [4188e69004009122ca2c687319561e9d835027a1](https://github.com/cockroachdb/cockroach/commits/4188e69004009122ca2c687319561e9d835027a1):

```
(cdc.go:4951).func2: observed value for metric changefeed_stage_pts_create_latency over threshold. observedValue: 612268467.000000, threshold: 30000000.000000
(cdc.go:401).Close: error shutting down prometheus/grafana: context canceled
test artifacts and logs in: /artifacts/cdc/multi-table-pts-benchmark/per-table-pts=true/num-tables=500/num-ranges=10/cpu_arch=arm64/run_1
```

Parameters:
 - <code>arch=arm64</code>
 - <code>cloud=aws</code>
 - <code>coverageBuild=false</code>
 - <code>cpu=16</code>
 - <code>encrypted=false</code>
 - <code>runtimeAssertionsBuild=false</code>
 - <code>ssd=0</code>
<details><summary>Help</summary>
<p>

See: [roachtest README](https://github.com/cockroachdb/cockroach/blob/master/pkg/cmd/roachtest/README.md)

See: [How To Investigate \(internal\)](https://cockroachlabs.atlassian.net/l/c/SSSBr8c7)

_Grafana is not yet available for aws clusters_</p>
</details>
/cc @cockroachdb/cdc
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*cdc/multi-table-pts-benchmark/per-table-pts=true/num-tables=500/num-ranges=10.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/bazci/githubpost/issues)

</sub>

### PR DESCRIPTION
**Pull request by aerfrei**
Removes the fixed threshold checks for the
`changefeed_stage_pts_manage_latency` and
`changefeed_stage_pts_manage_error_latency` metrics in the
cdc/multi-table-pts-benchmark roachtests. These thresholds were
too rigid and caused noisy failures.

Issue #154447 has been filed to track the goal of monitoring these metrics
via roachperf instead.

Fixes: #152900
Fixes: #152903
Fixes: #153017
Fixes: #154120
Fixes: #154122
Fixes: #154132
Fixes: #154302
Fixes: #154357
Epic: CRDB-1421
Release note: None

### CODE REVIEW

**Comment by aerfrei** [comment]
I kicked off a roachtest run here: https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestStress/20538660?buildTab=buildParameters&buildParametersTab=parameters&buildParametersShowDependencies=false

File: pkg/cmd/roachtest/tests/cdc.go [hunk 1]
```diff
@@ -1881,14 +1881,10 @@ func runCDCMultiTablePTSBenchmark(
 
 	ct.waitForWorkload()
 
-	t.Status("workload finished, verifying metrics")
+	t.Status("workload finished")
```
Comment (KeithCh) [inline pkg/cmd/roachtest/tests/cdc.go]: Nit: could probably remove one of 
`t.Status("workload finished")` or
`t.Status("multi-table PTS benchmark finished")`.

**Review by KeithCh — APPROVED** [review]

**Review by asg0451 — APPROVED** [review]

**Comment by andyyang890** [comment]
Will we need to backport this to 25.4? I was originally thinking yes but maybe not after #154478 merges.

**Comment by aerfrei** [comment]
blathers backport 25.4
