### PR TITLE
pgwire: Add support for cursors with special characters

### LINKED ISSUE #84261: Cursors with invalid names not handled properly in SQL/pgwire mix
**Describe the problem**

If a cursor name is not a valid identifier (but can be used in double quotes), pgwire describe seems unable to find it.

**To Reproduce**

The following script fails with `psycopg.errors.InvalidCursorName: unknown portal "1-2-3"`:

```python
import os
import psycopg

with psycopg.connect(os.environ["DSN"]) as conn:
    with conn.cursor("1-2-3") as cur:
        cur.execute("select generate_series(1,3)")
        cur.fetchall() == [(1,), (2,), (3,)]
```

Handling this name at purely sql level has no problem:

```
defaultdb=> begin;
BEGIN

*defaultdb=> DECLARE "1-2-3" CURSOR FOR select generate_series(1, 3) as bar;
DECLARE CURSOR

*defaultdb=> fetch 1 from "1-2-3";
┌─────┐
│ bar │
├─────┤
│   1 │
└─────┘
(1 row)
```

**Environment:**
 - CockroachDB version 22.1.3

Jira issue: CRDB-17557
Epic CRDB-14049

### PR DESCRIPTION
**Pull request by rimadeodhar**
IIn CockroachDB and Postgres, it is possible to declare
cursors with special characters enclosed within double
quotes, for e.g. "1-2-3". Currently, we store the name
as an unescaped string which causes problems during the
pgwire DESCRIBE step for looking up the cursor. We should
be storing using the tree.Name datatype for the cursor name
while storing and looking up cursors. This PR updates the code
to start using tree.Name instead of raw strings for handling
cursor names. This fixes the issue where the pgwire DESCRIBE
step fails while attempting to look up cursors with names
containing special characters.

Resolves https://github.com/cockroachdb/cockroach/issues/84261

Release note (bug fix): The pgwire DESCRIBE step no longer
fails with an error while attempting to look up cursors
declared with names containing special characters.

### CODE REVIEW

File: pkg/sql/conn_executor_prepare.go [hunk 1]
```diff
@@ -643,3 +644,18 @@ func (ex *connExecutor) isAllowedInAbortedTxn(ast tree.Statement) bool {
...
+// if found.
+func (ex *connExecutor) getSQLCursor(cursorName string) *sqlCursor {
+	cursor := ex.getCursorAccessor().getCursor(cursorName)
+	if cursor == nil {
+		// If an invalid identifier is used as a cursor name, it is stored within the cursor
+		// map as enclosed in double quotes. Attempt to look up the cursor name by enclosing
+		// it in double quotes to cover such a case.
+		// TODO(rimadeodhar): Is there a better way to do this? Do we have any helper methods
+		// for this already?
+		cursor = ex.getCursorAccessor().getCursor(fmt.Sprintf("\"%s\"", cursorName))
```
Comment (knz) [inline pkg/sql/conn_executor_prepare.go:658]: This is incorrect.

You want to use the `tree.Name` type (probably also as argument to `getSQLCusor` and the accessor's `getCursor`, and as datatype for `descCmd.Name` above).  `tree.Name` should take care of quoting for you.

Also don't forget to test identifiers that *contain* a double quote character as well.

Comment (knz) [reply pkg/sql/conn_executor_prepare.go:658]: Also I'm seeing this:
```
//  it is stored within the cursor
// map as enclosed in double quotes.
```

That doesn't seem right. The cursor map should use tree.Name as key type, and the double quotes should not be included. This means that the code that populates the map has done something weird.

**Review by rimadeodhar — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/85859)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @knz)

___
*[`pkg/sql/conn_executor_prepare.go` line 658 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/85859#-N93hTHHHhH3bM0-dJq0-r1-658:-N986f88E7nhEGszX6S9:b9uqcou) ([raw file](https://github.com/cockroachdb/cockroach/blob/a90b5cb0e5e6990d98192c360d6d33848f8dd928/pkg/sql/conn_executor_prepare.go#L658)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

Also I'm seeing this:
```
//  it is stored within the cursor
// map as enclosed in double quotes.
```

That doesn't seem right. The cursor map should use tree.Name as key type, and the double quotes should not be included. This means that the code that populates the map has done something weird.
</blockquote></details>

Ha ok, that makes sense. Let me make those changes!

**Review by rimadeodhar — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/85859)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @knz)

___
*[`pkg/sql/conn_executor_prepare.go` line 658 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/85859#-N93hTHHHhH3bM0-dJq0-r1-658:-N9J5MTg1ZoB5OtLKoEA:b-4b2jpp) ([raw file](https://github.com/cockroachdb/cockroach/blob/a90b5cb0e5e6990d98192c360d6d33848f8dd928/pkg/sql/conn_executor_prepare.go#L658)):*
<details><summary><i>Previously, rimadeodhar (Rima Deodhar) wrote…</i></summary><blockquote>

Ha ok, that makes sense. Let me make those changes!
</blockquote></details>

This is done.

**Review by knz — COMMENTED** [review]
> declare
> cursors with invalid identifiers enclosed within double
> quotes

I would not keep the word "invalid" in this sentence. The identifiers are completely valid. It's just that they use special characters and thus need to be quoted.

Also, I think the remainder of the commit message does not any more describe what is happening in this PR.

Also, I recommend you add some `pg_cursor` logic tests.

Finally, for all the tests (pgtests, go unit tests, logic tests), please ensure each test includes at least one of the following:

- an identifier containing a space, e.g. `a b`  (`DECLARE "a b" CURSOR ...`)
- an identifier containing singe and double quotes, e.g. `a"b'c`  (`DECLARE "a""b'c" CURSOR ...`)
- an identifier containing a backslash character e.g. `a\b` (`DECLARE "a\b" CURSOR ...`)

Then ensure that the expected test output matches what postgres would do with it.

> Reviewed 1 of 2 files at r1, 6 of 6 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/85859#-:-N9MytK6-ivYz1JNNzcz:b22qjsh)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rimadeodhar)

___
*[`pkg/sql/conn_executor_prepare.go` line 566 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/85859#-N9Mz7Ip2_Se1QipSpGK:-N9Mz7Ip2_Se1QipSpGL:bxk93a4) ([raw file](https://github.com/cockroachdb/cockroach/blob/8fb34db0f5bb35d48ad91d6d8e8946719bad4871/pkg/sql/conn_executor_prepare.go#L566)):*
> ```Go
> 	switch descCmd.Type {
> 	case pgwirebase.PrepareStatement:
> 		ps, ok := ex.extraTxnState.prepStmtsNamespace.prepStmts[string(descCmd.Name)]
> ```

Any reason not to change the key type of prepStmts to be tree.Name directly?
___
*[`pkg/sql/pg_catalog.go` line 3774 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/85859#-N9Mzaal4OKtrJTcSQjr:-N9Mzaal4OKtrJTcSQjs:bryomi3) ([raw file](https://github.com/cockroachdb/cockroach/blob/8fb34db0f5bb35d48ad91d6d8e8946719bad4871/pkg/sql/pg_catalog.go#L3774)):*
> ```Go
> 			}
> 			if err := addRow(
> 				tree.NewDString(name.String()), /* name */
> ```

I don't believe this is correct. This `.String()` call will introduce quotes, where none are desired.
You can see for yourself what postgres does:

```
kena=> declare "a b" cursor for table t;
DECLARE CURSOR
kena=> select * from pg_cursors;
 name |             statement             | is_holdable | is_binary | is_scrollable |         creation_time
------+-----------------------------------+-------------+-----------+---------------+-------------------------------
 a b  | declare "a b" cursor for table t; | f           | f         | t             | 2022-08-13 18:16:19.357203+02
(1 row)
```

See the name column contains the raw identifier, there's no quoting involved.
___
*[`pkg/sql/sql_cursor.go` line 56 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/85859#-N9MzoFjCimDHymRoGqP:-N9MzoFjCimDHymRoGqQ:b-o50aeu) ([raw file](https://github.com/cockroachdb/cockroach/blob/8fb34db0f5bb35d48ad91d6d8e8946719bad4871/pkg/sql/sql_cursor.go#L56)):*
> ```Go
> 			}
> 
> 			if p.extendedEvalCtx.PreparedStatementState.HasPortal(s.Name.String()) {
> ```

I think this `.String()` call is misplaced as well.
___
*[`pkg/sql/pgwire/conn_test.go` line 697 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/85859#-N9MzzZa2_n9EphSLH_M:-N9MzzZa2_n9EphSLH_N:b-fws11x) ([raw file](https://github.com/cockroachdb/cockroach/blob/8fb34db0f5bb35d48ad91d6d8e8946719bad4871/pkg/sql/pgwire/conn_test.go#L697)):*
> ```Go
> 	}
> 
> 	if desc.Name.String() != expName {
> ```

I believe this `.String()` call should not be there.

Also please extend the test to include identifiers with special characters.

**Review by rafiss — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/85859)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @knz and @rimadeodhar)

___
*[`pkg/sql/pg_catalog.go` line 3774 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/85859#-N9Mzaal4OKtrJTcSQjr:-N9hP44y6zCVdoRXKTHC:brr5gn1) ([raw file](https://github.com/cockroachdb/cockroach/blob/8fb34db0f5bb35d48ad91d6d8e8946719bad4871/pkg/sql/pg_catalog.go#L3774)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

I don't believe this is correct. This `.String()` call will introduce quotes, where none are desired.
You can see for yourself what postgres does:

```
kena=> declare "a b" cursor for table t;
DECLARE CURSOR
kena=> select * from pg_cursors;
 name |             statement             | is_holdable | is_binary | is_scrollable |         creation_time
------+-----------------------------------+-------------+-----------+---------------+-------------------------------
 a b  | declare "a b" cursor for table t; | f           | f         | t             | 2022-08-13 18:16:19.357203+02
(1 row)
```

See the name column contains the raw identifier, there's no quoting involved.
</blockquote></details>

so in this case we can use `tree.AsStringWithFlags(name, tree.FmtBareStrings)` or perhaps even `string(name)`


can we also add a test for a cursor name with quotes in the name
```
rafiss@127:postgres> declare "a"" b" cursor for table t;
DECLARE CURSOR
Time: 0.001s
rafiss@127:postgres> select * from pg_cursors;
+------+------------------------------------+-------------+-----------+---------------+-------------------------------+
| name | statement                          | is_holdable | is_binary | is_scrollable | creation_time                 |
|------+------------------------------------+-------------+-----------+---------------+-------------------------------|
| a" b | declare "a"" b" cursor for table t | False       | False     | True          | 2022-08-17 20:07:15.322335+00 |
| a b  | declare "a b" cursor for table t   | False       | False     | True          | 2022-08-17 20:07:02.611308+00 |
+------+------------------------------------+-------------+-----------+---------------+-------------------------------+
```

That is, let's add this test to pkg/sql/logictest/testdata/logic_test/pg_catalog

**Review by rimadeodhar — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/85859)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @knz and @rimadeodhar)

___
*[`pkg/sql/conn_executor_prepare.go` line 566 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/85859#-N9Mz7Ip2_Se1QipSpGK:-N9hoMT01hitGBaOMBMU:b-49jkz3) ([raw file](https://github.com/cockroachdb/cockroach/blob/8fb34db0f5bb35d48ad91d6d8e8946719bad4871/pkg/sql/conn_executor_prepare.go#L566)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

Any reason not to change the key type of prepStmts to be tree.Name directly?
</blockquote></details>

I was planning to do it in a follow up PR but probably might be worth address this within this PR itself.
___
*[`pkg/sql/pg_catalog.go` line 3774 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/85859#-N9Mzaal4OKtrJTcSQjr:-N9ho-ca1oyl7I-LdjZk:b-6nt7wp) ([raw file](https://github.com/cockroachdb/cockroach/blob/8fb34db0f5bb35d48ad91d6d8e8946719bad4871/pkg/sql/pg_catalog.go#L3774)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

so in this case we can use `tree.AsStringWithFlags(name, tree.FmtBareStrings)` or perhaps even `string(name)`


can we also add a test for a cursor name with quotes in the name
```
rafiss@127:postgres> declare "a"" b" cursor for table t;
DECLARE CURSOR
Time: 0.001s
rafiss@127:postgres> select * from pg_cursors;
+------+------------------------------------+-------------+-----------+---------------+-------------------------------+
| name | statement                          | is_holdable | is_binary | is_scrollable | creation_time                 |
|------+------------------------------------+-------------+-----------+---------------+-------------------------------|
| a" b | declare "a"" b" cursor for table t | False       | False     | True          | 2022-08-17 20:07:15.322335+00 |
| a b  | declare "a b" cursor for table t   | False       | False     | True          | 2022-08-17 20:07:02.611308+00 |
+------+------------------------------------+-------------+-----------+---------------+-------------------------------+
```

That is, let's add this test to pkg/sql/logictest/testdata/logic_test/pg_catalog
</blockquote></details>

Aah I see, wasn't aware of this difference with postgres. I kept it as `.String()` to keep it compatible with what we do today but seems like we in CRDB we keep the double quotes within the catalog:
```
root@127.0.0.1:26257/defaultdb  OPEN> declare "a b" cursor for table emp;
DECLARE CURSOR


Time: 106ms total (execution 105ms / network 0ms)

root@127.0.0.1:26257/defaultdb  OPEN> select * from pg_cursors;
  name  | statement | is_holdable | is_binary | is_scrollable |         creation_time
--------+-----------+-------------+-----------+---------------+--------------------------------
  "a b" | TABLE emp |      f      |     f     |       f       | 2022-08-17 21:57:15.943795+00
(1 row)
```

I'll fix this.

**Review by rimadeodhar — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/85859)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @knz and @rafiss)

___
*[`pkg/sql/conn_executor_prepare.go` line 566 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/85859#-N9Mz7Ip2_Se1QipSpGK:-NC1PBjw9VwmHIdniZ61:b-iatd1k) ([raw file](https://github.com/cockroachdb/cockroach/blob/8fb34db0f5bb35d48ad91d6d8e8946719bad4871/pkg/sql/conn_executor_prepare.go#L566)):*
<details><summary><i>Previously, rimadeodhar (Rima Deodhar) wrote…</i></summary><blockquote>

I was planning to do it in a follow up PR but probably might be worth address this within this PR itself.
</blockquote></details>

Updating it in this PR is making this PR very big. I will be putting out a PR stacked on top of this one which updates the maps within `prepStmts` to be keyed by tree.Name instead of string.
___
*[`pkg/sql/sql_cursor.go` line 56 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/85859#-N9MzoFjCimDHymRoGqP:-NC1Ogb5EYGqBUZ6kzc5:b14e6kt) ([raw file](https://github.com/cockroachdb/cockroach/blob/8fb34db0f5bb35d48ad91d6d8e8946719bad4871/pkg/sql/sql_cursor.go#L56)):*
<details><summary><i>Previously, knz (Raphael 'kena' Poss) wrote…</i></summary><blockquote>

I think this `.String()` call is misplaced as well.
</blockquote></details>

We need this call since prepared statement state stores the portal name using a raw string. I plan to fix this by updating the `prepStmtNamespace` structs to key maps using tree.Name as well in a subsequent PR.
___
*[`pkg/sql/pgwire/conn_test.go` line 697 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/85859#-N9MzzZa2_n9EphSLH_M:-NC1PA8R-Jf2M2lIzMW8:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/8fb34db0f5bb35d48ad91d6d8e8946719bad4871/pkg/sql/pgwire/conn_test.go#L697)):*
<details><summary><i>Previously, knz (Raphael 'kena' Poss) wrote…</i></summary><blockquote>

I believe this `.String()` call should not be there.

Also please extend the test to include identifiers with special characters.
</blockquote></details>

Done.

**Review by rafiss — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/85859)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @knz and @rimadeodhar)

___
*[`pkg/sql/sql_cursor.go` line 56 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/85859#-N9MzoFjCimDHymRoGqP:-NC6Pt7_E8yGKH3TL7yz:bpdkxll) ([raw file](https://github.com/cockroachdb/cockroach/blob/8fb34db0f5bb35d48ad91d6d8e8946719bad4871/pkg/sql/sql_cursor.go#L56)):*
<details><summary><i>Previously, rimadeodhar (Rima Deodhar) wrote…</i></summary><blockquote>

We need this call since prepared statement state stores the portal name using a raw string. I plan to fix this by updating the `prepStmtNamespace` structs to key maps using tree.Name as well in a subsequent PR.
</blockquote></details>

i'm not following still -- in the conn_executor_prepare.go file we are converting using `string(name)`, but here we are converting with `name.String()`
___
*[`pkg/sql/pgwire/testdata/pgtest/portals` line 1492 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/85859#-NC6QDvD39BHsP_Mt8vC:-NC6QDvD39BHsP_Mt8vD:b-h042t0) ([raw file](https://github.com/cockroachdb/cockroach/blob/f009c2d9cd8941806da4287e9c13d79e36d715ff/pkg/sql/pgwire/testdata/pgtest/portals#L1492)):*
> ```
> # Check declaring cursor with a name enclosed in double quotes
> send
> Query {"String": "BEGIN"}
> ```

just to confirm -- did you run this test against postgres as well? you can do so with:
```
 ./dev test pkg/sql/pgwire --filter='TestPGTest/portals' --test-args='-addr=localhost:5432 -user=rafiss' --rewrite
```

(adjust your username/port as necessary so that it points to a locally running postgres server)

**Review by rafiss — CHANGES_REQUESTED** [review]
i just had questions -- i'll mark it as "changes requested" just to flag them

**Review by knz — APPROVED** [review]
:lgtm: but i'll let rafi finalize this with you.

> Reviewed 8 of 8 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/85859#-:-NC6juZ3BrX5Tc5LbCFB:b-qigbzg)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @knz and @rimadeodhar)

**Review by rimadeodhar — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/85859)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @knz and @rafiss)

___
*[`pkg/sql/pgwire/testdata/pgtest/portals` line 1492 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/85859#-NC6QDvD39BHsP_Mt8vC:-NCQuJfl8_B6wvdzgZIu:b-f3mjor) ([raw file](https://github.com/cockroachdb/cockroach/blob/f009c2d9cd8941806da4287e9c13d79e36d715ff/pkg/sql/pgwire/testdata/pgtest/portals#L1492)):*
> ./dev test pkg/sql/pgwire --filter='TestPGTest/portals' --test-args='-addr=localhost:5432 -user=rafiss' --rewrite
I ran this test against a locally running postgres server and I noticed that it updated the `RowDescription` part of the test to update the `"DataTypeOID":23,"DataTypeSize":4` which differs from what is output when I run it against locally running CRDB. This makes sense to me since integers have a different data type size but what is the right output to put within the test by default? I'm guessing it should be the CRDB one right?

**Review by rafiss — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/85859)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @knz and @rimadeodhar)

___
*[`pkg/sql/pgwire/testdata/pgtest/portals` line 1492 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/85859#-NC6QDvD39BHsP_Mt8vC:-NCQvZRn1hbIJzAhulYH:bwdud7u) ([raw file](https://github.com/cockroachdb/cockroach/blob/f009c2d9cd8941806da4287e9c13d79e36d715ff/pkg/sql/pgwire/testdata/pgtest/portals#L1492)):*
<details><summary><i>Previously, rimadeodhar (Rima Deodhar) wrote…</i></summary><blockquote>

> ./dev test pkg/sql/pgwire --filter='TestPGTest/portals' --test-args='-addr=localhost:5432 -user=rafiss' --rewrite
I ran this test against a locally running postgres server and I noticed that it updated the `RowDescription` part of the test to update the `"DataTypeOID":23,"DataTypeSize":4` which differs from what is output when I run it against locally running CRDB. This makes sense to me since integers have a different data type size but what is the right output to put within the test by default? I'm guessing it should be the CRDB one right?
</blockquote></details>

in this case, you can resolve it either by adding an explicit cast to the query (look for other usages of `generate_series` in the pgtest testdata), or you can use the `ignore_data_type_sizes` and `ignore_type_oids` flag on the `until` directive.

**Review by rafiss — APPROVED** [review]
lgtm! 

> Reviewed 7 of 8 files at r3, 1 of 1 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/85859#-:-NCRB0Cu0upHy0sO_wxg:b-nzoors)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @knz and @rimadeodhar)

**Comment by rimadeodhar** [comment]
TFTR!

bors r=knz,rafiss
