### PR TITLE
roachtest: remove old executables before installing ruby

### LINKED ISSUE #95004: roachtest failure: ruby-pg - !!! Installation of ruby 3.1.2 failed!
Since Dec 10, 2022 there have been a number (12 so far) of `ruby-pg` failures. They are categorised as SSH flakes in https://github.com/cockroachdb/cockroach/issues/90695  but upon closer inspection seem to happen because ruby cannot be installed for a reason unrelated to SSH.

It is not consistently failing, but frequently enough to warrant some investigation

```
/usr/local/src/ruby-3.1.2/lib/rubygems/installer.rb:272:in `check_executable_overwrite': "erb" from erb conflicts with /usr/local/bin/erb (Gem::InstallError)
	from ./tool/rbinstall.rb:868:in `check_executable_overwrite'
	from /usr/local/src/ruby-3.1.2/lib/rubygems/installer.rb:513:in `block in generate_bin'
	from /usr/local/src/ruby-3.1.2/lib/rubygems/installer.rb:492:in `each'
	from /usr/local/src/ruby-3.1.2/lib/rubygems/installer.rb:492:in `generate_bin'
	from /usr/local/src/ruby-3.1.2/lib/rubygems/installer.rb:333:in `install'
	from ./tool/rbinstall.rb:899:in `block in install'
	from ./tool/rbinstall.rb:713:in `no_write'
	from ./tool/rbinstall.rb:899:in `install'
	from ./tool/rbinstall.rb:1002:in `block in install_default_gem'
	from ./tool/rbinstall.rb:989:in `each'
	from ./tool/rbinstall.rb:989:in `install_default_gem'
	from ./tool/rbinstall.rb:927:in `block in <main>'
	from ./tool/rbinstall.rb:1127:in `block in <main>'
	from ./tool/rbinstall.rb:1124:in `each'
	from ./tool/rbinstall.rb:1124:in `<main>'
make: *** [uncommon.mk:383: do-install-all] Error 1
!!! Installation of ruby 3.1.2 failed!
```

2 issues:
- ruby is failing installation
- this is categorised as an SSH flake

Jira issue: CRDB-23268

### LINKED ISSUE #100428: roachtest: ruby-pg failed
roachtest.ruby-pg [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/9382858?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/9382858?buildTab=artifacts#/ruby-pg) on master @ [1e27c65fb5a3810a5e2285cf07b45d95d401cca6](https://github.com/cockroachdb/cockroach/commits/1e27c65fb5a3810a5e2285cf07b45d95d401cca6):

```
test artifacts and logs in: /artifacts/ruby-pg/run_1
(test_runner.go:1010).runTest: test timed out (1h0m0s)
```
<p>Parameters: <code>ROACHTEST_cloud=gce</code>
, <code>ROACHTEST_cpu=4</code>
, <code>ROACHTEST_encrypted=false</code>
, <code>ROACHTEST_ssd=0</code>
</p>
<details><summary>Help</summary>
<p>

See: [roachtest README](https://github.com/cockroachdb/cockroach/blob/master/pkg/cmd/roachtest/README.md)

See: [How To Investigate \(internal\)](https://cockroachlabs.atlassian.net/l/c/SSSBr8c7)

</p>
</details>
/cc @cockroachdb/sql-sessions
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*ruby-pg.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)
</sub>

Jira issue: CRDB-26431

### LINKED ISSUE #100586: roachtest: ruby-pg failed
roachtest.ruby-pg [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/9417479?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/9417479?buildTab=artifacts#/ruby-pg) on release-23.1 @ [35b724947ac464e6af45ce5193e34035fcacb1ef](https://github.com/cockroachdb/cockroach/commits/35b724947ac464e6af45ce5193e34035fcacb1ef):

```
test artifacts and logs in: /artifacts/ruby-pg/run_1
(ruby_pg.go:219).func1: failed to find total number of tests run
```
<p>Parameters: <code>ROACHTEST_cloud=gce</code>
, <code>ROACHTEST_cpu=4</code>
, <code>ROACHTEST_encrypted=false</code>
, <code>ROACHTEST_ssd=0</code>
</p>
<details><summary>Help</summary>
<p>

See: [roachtest README](https://github.com/cockroachdb/cockroach/blob/master/pkg/cmd/roachtest/README.md)

See: [How To Investigate \(internal\)](https://cockroachlabs.atlassian.net/l/c/SSSBr8c7)

</p>
</details>
<details><summary>Same failure on other branches</summary>
<p>

- #100428 roachtest: ruby-pg failed [C-test-failure O-roachtest O-robot T-sql-sessions branch-master]
</p>
</details>
/cc @cockroachdb/sql-sessions
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*ruby-pg.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)
</sub>

### PR DESCRIPTION
**Pull request by rafiss**
This should prevent errors during installation.

fixes https://github.com/cockroachdb/cockroach/issues/95004
fixes https://github.com/cockroachdb/cockroach/issues/100428
backport fixes https://github.com/cockroachdb/cockroach/issues/100586

Release note: None

### CODE REVIEW

File: pkg/cmd/roachtest/tests/ruby_pg.go [hunk 1]
```diff
@@ -87,6 +87,7 @@ func registerRubyPG(r registry.Registry) {
 			"install ruby 3.1.2",
 			`mkdir -p ruby-install && \
         curl -fsSL https://github.com/postmodern/ruby-install/archive/v0.8.3.tar.gz | tar --strip-components=1 -C ruby-install -xz && \
+        sudo rm -rf /usr/local/bin/* && \
```
Comment (andyyang890) [inline pkg/cmd/roachtest/tests/ruby_pg.go:90]: Is it safe to delete everything instead of targeting specific programs?

Comment (rafiss) [reply pkg/cmd/roachtest/tests/ruby_pg.go:90]: yes, a fresh roachprod instance does not have anything in this directory

**Review by andyyang890 — APPROVED** [review]
LGTM!

**Comment by rafiss** [comment]
tftr

bors r+
