### PR TITLE
changefeedccl: move rolling restart test workload to own node

### LINKED ISSUE #166672: release-26.2: roachtest: cdc/no-rolling-restart failed
roachtest.cdc/no-rolling-restart [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/21282728?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/21282728?buildTab=artifacts#/cdc/no-rolling-restart) on release-26.2 @ [5f70452d622f1349e821d703a7f454ef7c07c57d](https://github.com/cockroachdb/cockroach/commits/5f70452d622f1349e821d703a7f454ef7c07c57d):

Failed with:

```
(cdc.go:1505).runCDCRollingRestart: changefeed lag 5m0.456076917s exceeded maximum allowed (5m0s) during rolling restarts
(cdc.go:4473).stop: context canceled
test artifacts and logs in: /artifacts/cdc/no-rolling-restart/run_1
```
Cluster Node to Ip Mapping:
| Node | Public IP | Private IP |
| --- | --- | --- |
| teamcity-21282728-1774418882-93-n5cpu4-0001 | 35.185.2.212 | 10.142.2.0 |
| teamcity-21282728-1774418882-93-n5cpu4-0002 | 35.237.220.106 | 10.142.1.252 |
| teamcity-21282728-1774418882-93-n5cpu4-0003 | 34.74.57.48 | 10.142.1.239 |
| teamcity-21282728-1774418882-93-n5cpu4-0004 | 34.24.18.193 | 10.142.1.231 |
| teamcity-21282728-1774418882-93-n5cpu4-0005 | 35.243.194.138 | 10.142.1.241 |

Parameters:
 - <code>arch=amd64</code>
 - <code>cloud=gce</code>
 - <code>coverageBuild=false</code>
 - <code>cpu=4</code>
 - <code>diskCount=0</code>
 - <code>encrypted=false</code>
 - <code>fs=ext4</code>
 - <code>localSSD=true</code>
 - <code>runtimeAssertionsBuild=false</code>
<details><summary>Help</summary>
<p>

See: [roachtest README](https://github.com/cockroachdb/cockroach/blob/master/pkg/cmd/roachtest/README.md)

See: [How To Investigate \(internal\)](https://cockroachlabs.atlassian.net/l/c/SSSBr8c7)

See: [Grafana](https://go.crdb.dev/roachtest-grafana/teamcity-21282728/cdc-no-rolling-restart/1774444954818/1774446240049)

</p>
</details>
/cc @cockroachdb/cdc
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*cdc/no-rolling-restart.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/bazci/githubpost/issues)

</sub>

Jira issue: CRDB-62069

### LINKED ISSUE #166986: roachtest: cdc/no-rolling-restart failed
roachtest.cdc/no-rolling-restart [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/21288633?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/21288633?buildTab=artifacts#/cdc/no-rolling-restart) on master @ [9e8d4fea37e8623a23ec692862f6bc1b661d32d3](https://github.com/cockroachdb/cockroach/commits/9e8d4fea37e8623a23ec692862f6bc1b661d32d3):

Failed with:

```
(cdc.go:1479).runCDCRollingRestart: changefeed lag 2m35.963885532s exceeded maximum allowed (2m0s) after recovery period
(cdc.go:4418).stop: context canceled
test artifacts and logs in: /artifacts/cdc/no-rolling-restart/run_1
```
Cluster Node to Ip Mapping:
| Node | Public IP | Private IP |
| --- | --- | --- |
| teamcity-21288633-1774765407-59-n5cpu4-0001 | 34.26.24.246 | 10.142.1.99 |
| teamcity-21288633-1774765407-59-n5cpu4-0002 | 104.196.159.74 | 10.142.1.136 |
| teamcity-21288633-1774765407-59-n5cpu4-0003 | 35.185.33.2 | 10.142.1.62 |
| teamcity-21288633-1774765407-59-n5cpu4-0004 | 34.75.239.158 | 10.142.1.1 |
| teamcity-21288633-1774765407-59-n5cpu4-0005 | 35.237.52.82 | 10.142.1.21 |

Parameters:
 - <code>arch=amd64</code>
 - <code>cloud=gce</code>
 - <code>coverageBuild=false</code>
 - <code>cpu=4</code>
 - <code>diskCount=0</code>
 - <code>encrypted=false</code>
 - <code>fs=ext4</code>
 - <code>localSSD=true</code>
 - <code>runtimeAssertionsBuild=false</code>
<details><summary>Help</summary>
<p>

See: [roachtest README](https://github.com/cockroachdb/cockroach/blob/master/pkg/cmd/roachtest/README.md)

See: [How To Investigate \(internal\)](https://cockroachlabs.atlassian.net/l/c/SSSBr8c7)

See: [Grafana](https://go.crdb.dev/roachtest-grafana/teamcity-21288633/cdc-no-rolling-restart/1774777297013/1774778781816)

See: [Datadog Logs](https://us5.datadoghq.com/logs?query=service%3Aroachtest+%40cluster%3Ateamcity-21288633-1774765407-59-n5cpu4&from_ts=1774777297013&to_ts=1774778781816&live=false&storage=flex_tier)

</p>
</details>
/cc @cockroachdb/cdc
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*cdc/no-rolling-restart.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/bazci/githubpost/issues)

</sub>

Jira issue: CRDB-62196

### LINKED ISSUE #166990: release-26.2: roachtest: cdc/rolling-restart failed
roachtest.cdc/rolling-restart [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/21288783?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/21288783?buildTab=artifacts#/cdc/rolling-restart) on release-26.2 @ [64881a0a13a908bb7791d0f831cedcc78ece9130](https://github.com/cockroachdb/cockroach/commits/64881a0a13a908bb7791d0f831cedcc78ece9130):

Failed with:

```
(cdc.go:1533).runCDCRollingRestart: changefeed lag 2m15.499001034s exceeded maximum allowed (2m0s) after recovery period
(cdc.go:4473).stop: context canceled
test artifacts and logs in: /artifacts/cdc/rolling-restart/run_1
```
Cluster Node to Ip Mapping:
| Node | Public IP | Private IP |
| --- | --- | --- |
| teamcity-21288783-1774765513-97-n5cpu4-0001 | 34.75.64.84 | 10.142.1.15 |
| teamcity-21288783-1774765513-97-n5cpu4-0002 | 35.237.198.53 | 10.142.1.7 |
| teamcity-21288783-1774765513-97-n5cpu4-0003 | 34.23.228.208 | 10.142.1.1 |
| teamcity-21288783-1774765513-97-n5cpu4-0004 | 34.74.28.224 | 10.142.0.224 |
| teamcity-21288783-1774765513-97-n5cpu4-0005 | 35.231.108.217 | 10.142.0.172 |

Parameters:
 - <code>arch=amd64</code>
 - <code>cloud=gce</code>
 - <code>coverageBuild=false</code>
 - <code>cpu=4</code>
 - <code>diskCount=0</code>
 - <code>encrypted=false</code>
 - <code>fs=ext4</code>
 - <code>localSSD=true</code>
 - <code>runtimeAssertionsBuild=false</code>
<details><summary>Help</summary>
<p>

See: [roachtest README](https://github.com/cockroachdb/cockroach/blob/master/pkg/cmd/roachtest/README.md)

See: [How To Investigate \(internal\)](https://cockroachlabs.atlassian.net/l/c/SSSBr8c7)

See: [Grafana](https://go.crdb.dev/roachtest-grafana/teamcity-21288783/cdc-rolling-restart/1774795105384/1774796616674)

</p>
</details>
/cc @cockroachdb/cdc
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*cdc/rolling-restart.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/bazci/githubpost/issues)

</sub>

Jira issue: CRDB-62200

### PR DESCRIPTION
**Pull request by aerfrei**
Previously the workload binary ran on a CRDB node, consuming CPU that
caused admission control to throttle the changefeed. Move the workload
to a dedicated workload runner node for both the test and control
variants.

Epic: none
Fixes: https://github.com/cockroachdb/cockroach/issues/166672
Fixes: https://github.com/cockroachdb/cockroach/issues/166986
Fixes: https://github.com/cockroachdb/cockroach/issues/166990

### CODE REVIEW

File: pkg/cmd/roachtest/tests/cdc.go [hunk 1]
```diff
@@ -1244,11 +1310,13 @@ func runCDCRollingRestart(
...
-	// - Node N: Kafka
-	crdbNodes := c.Range(1, c.Spec().NodeCount-1)
-	kafkaNode := c.Node(c.Spec().NodeCount)
+	// - Nodes 1 through N-3: CRDB (subject to rolling restarts)
+	// - Node N-2: CRDB + SQL queries (not restarted)
+	// - Node N-1: Kafka
+	// - Node N: Workload runner only (no CRDB, framework workload node)
+	crdbNodes := c.Range(1, c.Spec().NodeCount-2)
+	kafkaNode := c.Node(c.Spec().NodeCount - 1)
+	sqlNode := c.Spec().NodeCount - 2
```
Comment (jeffswenson) [inline pkg/cmd/roachtest/tests/cdc.go]: Is separately tracking the sqlNode really necessary given the fact we have it set up to tolerate errors? The workload accepts multiple connection uris, so we could spread the write traffic out over the cluster and get a more realistic test.

**Review by jeffswenson — APPROVED** [review]
LGTM

File: pkg/cmd/roachtest/tests/cdc.go (hunk 1 above)
Comment (aerfrei) [reply pkg/cmd/roachtest/tests/cdc.go]: TBH, the real reason I originally was tracking the sql node is so that I could use it to read the highwater to compute the lag. I think it's a bit more annoying to tolerate errors there.

Do you think it's worthwhile spreading the write traffic out regardless? I can file an issue for that.

Comment (jeffswenson) [reply pkg/cmd/roachtest/tests/cdc.go]: Ohh, so this is a way to avoid the errors for the queries that are used to monitor the changefeed? I think it may be worth wrapping that in a retry loop and using a db pool connected to communicate with random nodes in the cluster so that it can always reach one of the healthy nodes.

Comment (aerfrei) [reply pkg/cmd/roachtest/tests/cdc.go]: I think now that I have made this change, this test no longer fails when I remove the changes we made to backoff behavior, making it a less effective regression test :/ Presumably spreading the traffic out gives more headroom to the changefeed or something like that.

Would it be worth merging the more minimal change ([8752717](https://github.com/cockroachdb/cockroach/commit/87527171b744bdf933cafb0eab94d2a20f279df5)) for now and modifying this test or adding more realistic tests in a follow up commit?

We could also potentially keep the test and accept that it's less effective as a regression test, but I don't like the idea of that so much.

Comment (jeffswenson) [reply pkg/cmd/roachtest/tests/cdc.go]: 🤔 Interesting. I think what used to happen is we would end up with the coordinator stuck on the stable node. With this change we are moving the coordinator every three restarts.

I'm okay keeping this split, but we should update the doc comment to describe why it is necessary.

Comment (aerfrei) [reply pkg/cmd/roachtest/tests/cdc.go]: Right! I think this is what you were saying but something clicked for me here. 

We are trying to repro an issue that happens on large clusters. Let's say we were on a large production cluster doing a rolling restart and we encountered this issue of long backoff, restarting the coordinator node would actually help us because it would reset the backoff to its initial value.

As n grows, though, we expect to do more non-coordinator restarts before restarts the coordinator which is what why we see this issue on large cluster. So it makes sense that this test needs to keep one node from restarting to play the role of "coordinator in a large cluster". That's how we repro with only 4 nodes or so and why we want that behavior in our test. I'll leave a comment explaining that. 

I think I should be able to keep the change to spread out write traffic as long as I continue to keep one node from restarting. (At which point I might as well use the non-restarting node for the logging to keep that a little simpler). 

If that doesn't work, I'll merge the version at that previous commit to keep this from taking up more time. 

Edit: This appears to be working. Once CI runs clean, I will merge.
