### PR TITLE
ttl: use JobRegistry.UpdateJobWithTxn to avoid race condition

### LINKED ISSUE #85800: sql/ttl/ttljob: TestRowLevelTTLJobRandomEntries failed
sql/ttl/ttljob.TestRowLevelTTLJobRandomEntries [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_StressBazel/6023773?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_StressBazel/6023773?buildTab=artifacts#/) on master @ [24906bd59e975f607e9ea88cbd4ae5ff0432df45](https://github.com/cockroachdb/cockroach/commits/24906bd59e975f607e9ea88cbd4ae5ff0432df45):

```
=== RUN   TestRowLevelTTLJobRandomEntries
    test_log_scope.go:162: test logs captured to: /artifacts/tmp/_tmp/74bc9dd224da62240eee8570f9dfa5ee/logTestRowLevelTTLJobRandomEntries3126926523
    test_log_scope.go:80: use -show-logs to present logs inline
=== CONT  TestRowLevelTTLJobRandomEntries
    ttljob_test.go:685: -- test log scope end --
--- FAIL: TestRowLevelTTLJobRandomEntries (52.48s)
=== RUN   TestRowLevelTTLJobRandomEntries/one_column_pk_multiple_nodes
    ttljob_test.go:546: test case: ttljob_test.testCase{desc:"one column pk multiple nodes", createTable:"CREATE TABLE tbl (\n\tid UUID PRIMARY KEY DEFAULT gen_random_uuid(),\n\ttext TEXT\n) WITH (ttl_expire_after = '30 days')", preSetup:[]string(nil), postSetup:[]string(nil), numExpiredRows:1001, numNonExpiredRows:5, numSplits:10, forceNonMultiTenant:false, numNodes:5, expirationExpression:"", addRow:(func(*ttljob_test.rowLevelTTLTestJobTestHelper, *tree.CreateTable, time.Time))(nil)}
    ttljob_test.go:679: 
        	Error Trace:	ttljob_test.go:679
        	Error:      	Not equal: 
        	            	expected: 1001
        	            	actual  : 1071
        	Test:       	TestRowLevelTTLJobRandomEntries/one_column_pk_multiple_nodes
    --- FAIL: TestRowLevelTTLJobRandomEntries/one_column_pk_multiple_nodes (10.72s)
```
<p>Parameters: <code>TAGS=bazel,gss</code>
</p>
<details><summary>Help</summary>
<p>

See also: [How To Investigate a Go Test Failure \(internal\)](https://cockroachlabs.atlassian.net/l/c/HgfXfJgM)
</p>
</details>
/cc @cockroachdb/sql-experience
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*TestRowLevelTTLJobRandomEntries.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)
</sub>

Jira issue: CRDB-18438

Epic CRDB-14592

### PR DESCRIPTION
**Pull request by ecwall**
fixes https://github.com/cockroachdb/cockroach/issues/85800

UpdateJobWithTxn updates the job progress with useReadLock=true to prevent
concurrent update attempts from undoing each other.

Release justification: Fix test flake.

Release note: None

### CODE REVIEW

**Comment by ecwall** [comment]
I separated this out of https://github.com/cockroachdb/cockroach/pull/86057 to make reviewing easier as the original PR began to address multiple issues.

File: pkg/sql/ttl/ttljob/ttljob_processor.go [hunk 1]
```diff
@@ -224,18 +225,25 @@ func (ttl *ttlProcessor) work(ctx context.Context) error {
...
+	return serverCfg.JobRegistry.UpdateJobWithTxn(
+		ctx,
+		jobID,
+		nil,  /* txn */
+		true, /* useReadLock */
+		func(_ *kv.Txn, md jobs.JobMetadata, ju *jobs.JobUpdater) error {
 			progress := md.Progress
-			progress.Details.(*jobspb.Progress_RowLevelTTL).RowLevelTTL.RowCount += rowCount
+			existingRowCount := progress.Details.(*jobspb.Progress_RowLevelTTL).RowLevelTTL.RowCount
+			progress.Details.(*jobspb.Progress_RowLevelTTL).RowLevelTTL.RowCount += processorRowCount
```
Comment (ecwall) [inline pkg/sql/ttl/ttljob/ttljob_processor.go:237]: I don't think this needs to use `atomic.LoadInt64` because `processorRowCount` is no longer being modified after `group.Wait()` finishes.

**Review by rafiss — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/86322)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ecwall and @rafiss)

___
*[`pkg/sql/ttl/ttljob/ttljob_processor.go` line 239 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/86322#-N9hUfA72d8NnPNrOBAe:-N9hUfA72d8NnPNrOBAf:bim1rby) ([raw file](https://github.com/cockroachdb/cockroach/blob/8615f063df3d44cffa9fb5c68c149a2d497bdd68/pkg/sql/ttl/ttljob/ttljob_processor.go#L239)):*
> ```Go
> 			progress.Details.(*jobspb.Progress_RowLevelTTL).RowLevelTTL.RowCount += processorRowCount
> 			ju.UpdateProgress(progress)
> 			log.Infof(
> ```

how frequently will this log? i believe it will get logged whenever the TTL job runs, which means it could be a lot of noise...

it feels like it could be something that should only be shown with `log.Vinfof(ctx, 2, ...)`

**Review by ecwall — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/86322)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rafiss)

___
*[`pkg/sql/ttl/ttljob/ttljob_processor.go` line 239 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/86322#-N9hUfA72d8NnPNrOBAe:-N9hdRBG4XFhn0cCg9id:bgg837e) ([raw file](https://github.com/cockroachdb/cockroach/blob/8615f063df3d44cffa9fb5c68c149a2d497bdd68/pkg/sql/ttl/ttljob/ttljob_processor.go#L239)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

how frequently will this log? i believe it will get logged whenever the TTL job runs, which means it could be a lot of noise...

it feels like it could be something that should only be shown with `log.Vinfof(ctx, 2, ...)`
</blockquote></details>

Yeah, I forgot to address that from the other PR. Updated.

**Review by rafiss — APPROVED** [review]
thanks!

**Comment by ecwall** [comment]
bors r=rafiss
