### PR TITLE
kvcoord: force split batch in txnWriteBuffer for mid txn flush

### LINKED ISSUE #161722: pkg/sql/logictest/tests/local/local_test: TestLogic_swap_mutation failed
pkg/sql/logictest/tests/local/local_test.TestLogic_swap_mutation [failed](https://mesolite.cluster.engflow.com/invocations/default/f0a470e7-2fb9-4376-b587-710fe1993a43?testReportRun=1&testReportShard=2&testReportAttempt=1#targets-Ly9wa2cvc3FsL2xvZ2ljdGVzdC90ZXN0cy9sb2NhbDpsb2NhbF90ZXN0) on master @ [f957652150dec24320428995ac8171301aba51a7](https://github.com/cockroachdb/cockroach/commits/f957652150dec24320428995ac8171301aba51a7):

```
=== RUN   TestLogic_swap_mutation
    test_log_scope.go:172: test logs captured to: outputs.zip/logTestLogic_swap_mutation4263344449
    test_log_scope.go:82: use -show-logs to present logs inline
[01:04:15] setting distsql_workmem='22336B';
    logic.go:3249: 
         
        /mnt/engflow/worker/work/0/exec/bazel-out/k8-fastbuild/bin/pkg/sql/logictest/tests/local/local_test_/local_test.runfiles/com_github_cockroachdb_cockroach/pkg/sql/logictest/testdata/logic_test/swap_mutation:88: SELECT * FROM xyz ORDER BY x
        expected:
            1  1  21
            2  2  2
            
        but found (query options: "") :
            1  1  1
            2  2  2
            
[01:04:15] --- done: /mnt/engflow/worker/work/0/exec/bazel-out/k8-fastbuild/bin/pkg/sql/logictest/tests/local/local_test_/local_test.runfiles/com_github_cockroachdb_cockroach/pkg/sql/logictest/testdata/logic_test/swap_mutation with config local: 19 tests, 1 failures
    logic.go:4653: 
        /mnt/engflow/worker/work/0/exec/bazel-out/k8-fastbuild/bin/pkg/sql/logictest/tests/local/local_test_/local_test.runfiles/com_github_cockroachdb_cockroach/pkg/sql/logictest/testdata/logic_test/swap_mutation:94: error while processing
    logic.go:4653: /mnt/engflow/worker/work/0/exec/bazel-out/k8-fastbuild/bin/pkg/sql/logictest/tests/local/local_test_/local_test.runfiles/com_github_cockroachdb_cockroach/pkg/sql/logictest/testdata/logic_test/swap_mutation:94: too many errors encountered, skipping the rest of the input
    panic.go:615: -- test log scope end --
test logs left over in: outputs.zip/logTestLogic_swap_mutation4263344449
--- FAIL: TestLogic_swap_mutation (0.63s)
```

Parameters:
 - <code>attempt=1</code>
 - <code>run=1</code>
 - <code>shard=2</code>
<details><summary>Help</summary>
<p>

See also: [How To Investigate a Go Test Failure \(internal\)](https://cockroachlabs.atlassian.net/l/c/HgfXfJgM)
</p>
</details>
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*TestLogic_swap_mutation.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/bazci/githubpost/issues)

</sub>

Jira issue: CRDB-59038

### PR DESCRIPTION
**Pull request by yuzefovich**
We just found a case where - if a BatchRequest with a CPut forces the txn write buffer to flush (e.g. because of buffer size limit) - we could lose some buffered writes in case that CPut's condition failed the evaluation. This was the case since we could have included the CPut into the same batch as all buffered writes, and the ConditionFailedError would make us discard the whole batch, whereas the higher level (i.e. SQL) could have discarded that error by using savepoints. To prevent this from happening we'll now require a separate batch for the buffered writes for all mid-txn flushes. Additionally, even in the end-txn flush batch case we now require a separate batch if a CPut is found.

Fixes: #161722.

Release note (bug fix): Previously, if buffered writes were enabled (which is a public preview feature, off by default), multi-stmt explicit txns that use SAVEPOINTs to recover from certain errors (like duplicate key value violations) could lose the writes that were performed _before_ the savepoint was created in rare cases. The bug has been present since the buffered writes feature was added in 25.2 and is now fixed.

### CODE REVIEW

**Review by yuzefovich — COMMENTED** [review]
I didn't include the savepoint check as a condition for when we split the batches for the flush although it does feel like a good thing to have. Should we merge that change only to master? Or should we discuss in more depth the [suggestion](https://github.com/cockroachdb/cockroach/issues/160579#issuecomment-3719360654) to Step the write sequence on CreateSavepoint? Or would this discussion be orthogonal to this "separate flush batch if a savepoint was created" question?

> @yuzefovich made 1 comment.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/161972#-:-Ok6FJ_U1tQCh6usBsBy:b-qmxrbu)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @arulajmani, @michae2, and @stevendanna).

**Review by michae2 — COMMENTED** [review]
Nice job tracking this down!

> @michae2 made 2 comments.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/161972#-:-Ok6MLpz61BO6Fppcffa:b-8botvf)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @arulajmani, @stevendanna, and @yuzefovich).

___
*[`pkg/kv/kvclient/kvcoord/txn_interceptor_write_buffer.go` line 1905 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/161972#-Ok6M-8z8_yw4fXd_eud:-Ok6M-8z8_yw4fXd_eue:b-ttodpi) ([raw file](https://github.com/cockroachdb/cockroach/blob/4dfff9bde35962a069c506e173b77308de992484/pkg/kv/kvclient/kvcoord/txn_interceptor_write_buffer.go#L1905)):*
> ```Go
> 	// If we find any CPuts, then we need a separate batch because these can
> 	// fail which would discard any buffered writes (when evaluated as part of
> 	// the same batch).
> ```

Do we also need to check that the CPut has a different sequence number than the earlier items in the batch? If it's the same sequence number, seems like it should all be rolled back together anyway.

**Review by yuzefovich — COMMENTED** [review]
> @yuzefovich made 1 comment.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/161972)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @arulajmani, @michae2, and @stevendanna).

___
*[`pkg/kv/kvclient/kvcoord/txn_interceptor_write_buffer.go` line 1905 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/161972#-Ok6M-8z8_yw4fXd_eud:-Ok6QlGq4vQMODaaQktV:b-cmuzkt) ([raw file](https://github.com/cockroachdb/cockroach/blob/4dfff9bde35962a069c506e173b77308de992484/pkg/kv/kvclient/kvcoord/txn_interceptor_write_buffer.go#L1905)):*
<details><summary><i>Previously, michae2 (Michael Erickson) wrote…</i></summary><blockquote>

Do we also need to check that the CPut has a different sequence number than the earlier items in the batch? If it's the same sequence number, seems like it should all be rolled back together anyway.
</blockquote></details>

That feels like an optimization that might not be worth implementing (or, at least, not including into the backports). Generally speaking, it should be quite infrequent that we need to flush the buffer and effectively disable buffered writes, and here we'd be optimizing for that rare event. We could make this tighter on master in a follow-up PR if you think it's worth it given this "rare scenario" observation.

**Review by michae2 — APPROVED** [review]
This :lgtm: but probably best to wait for KV approval too.

> @michae2 reviewed 2 files and all commit messages, and made 1 comment.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/161972#-:-Ok74RBRDkd_-dSvGmM4:b-oi8hyk)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @arulajmani and @stevendanna).

**Review by stevendanna — COMMENTED** [review]
The code here looks good, but my preference would be that we also require split batches for any mid transaction flush.

File: pkg/kv/kvclient/kvcoord/txn_interceptor_write_buffer.go [hunk 1]
```diff
@@ -1892,11 +1892,24 @@ func separateBatchIsNeeded(ba *kvpb.BatchRequest, optEndTxn kvpb.Request) bool {
...
 		ba.WaitPolicy != 0 ||
 		ba.WriteOptions != nil && (*ba.WriteOptions != kvpb.WriteOptions{}) ||
-		ba.IsReverse
+		ba.IsReverse {
+		return true
+	}
+
+	// If we find any CPuts, then we need a separate batch because these can
+	// fail which would discard any buffered writes (when evaluated as part of
+	// the same batch).
```
Comment (stevendanna) [inline pkg/kv/kvclient/kvcoord/txn_interceptor_write_buffer.go]: Let's note in this comment that it's not just that these can fail (other requests can also fail), but these requests can fail in a way that both (1) isn't retried at levels below us and (2) _can be_ recovered from in the same transaction at higher levels.

Comment (yuzefovich) [reply pkg/kv/kvclient/kvcoord/txn_interceptor_write_buffer.go]: Done.

**Review by yuzefovich — COMMENTED** [review]
Added the logic to require a separate batch with mid-txn flush. Thoughts on whether this deserves a release note or not?

> @yuzefovich made 2 comments and resolved 1 discussion.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/161972#-:-Ok9ITlf0gZ0vTzB8zjd:bs4uht2)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @arulajmani, @michae2, and @stevendanna).

**Review by yuzefovich — COMMENTED** [review]
Added the release note. Plus needed to adjust a few tests due to mid-txn flush (given that we now have 2 batches instead of 1).

TFTRs!

bors r+

> @yuzefovich made 1 comment.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/161972#-:-Ok9xSca3viA-rXF4pYO:b-j8r4vq)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @arulajmani, @michae2, and @stevendanna).
