### PR TITLE
roachtest: Update lib/pq block list

### LINKED ISSUE #141899: roachtest: lib/pq failed
**Note:** This build has runtime assertions enabled. If the same failure was hit in a run without assertions enabled, there should be a similar failure without this message. If there isn&#39;t one, then this failure is likely due to an assertion violation or (assertion) timeout.

roachtest.lib/pq [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyAzureBazel/18906414?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyAzureBazel/18906414?buildTab=artifacts#/lib/pq) on master @ [fa8342d50c1bdfbc307f4bca9bc0d34da4475258](https://github.com/cockroachdb/cockroach/commits/fa8342d50c1bdfbc307f4bca9bc0d34da4475258):

```
(orm_helpers.go:224).summarizeFailed: 
Tests run on Cockroach v25.2.0-alpha.00000000-dev-fa8342d50c1bdfbc307f4bca9bc0d34da4475258
Tests run against lib/pq v1.10.5
216 Total Tests Run
189 tests passed
27 tests failed
7 tests skipped
0 tests ignored
0 tests passed unexpectedly
3 tests failed unexpectedly
0 tests expected failed but skipped
0 tests expected failed but not run
---
--- FAIL: pq.TestCopyInWrongType - unknown (unexpected)
--- FAIL: pq.TestCopyInMultipleValues - unknown (unexpected)
--- FAIL: pq.TestCopyFromError - unknown (unexpected)
For a full summary look at the lib/pq artifacts 
An updated blocklist (libPQBlocklist) is available in the artifacts' lib/pq log
(cluster.go:2490).Run: context canceled
test artifacts and logs in: /artifacts/lib/pq/run_1
```

Parameters:
 - <code>arch=amd64</code>
 - <code>cloud=azure</code>
 - <code>coverageBuild=false</code>
 - <code>cpu=4</code>
 - <code>encrypted=false</code>
 - <code>metamorphicBufferedSender=true</code>
 - <code>metamorphicLeases=default</code>
 - <code>runtimeAssertionsBuild=true</code>
 - <code>ssd=0</code>
<details><summary>Help</summary>
<p>

See: [roachtest README](https://github.com/cockroachdb/cockroach/blob/master/pkg/cmd/roachtest/README.md)

See: [How To Investigate \(internal\)](https://cockroachlabs.atlassian.net/l/c/SSSBr8c7)

_Grafana is not yet available for azure clusters_</p>
</details>
/cc @cockroachdb/sql-foundations
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*lib/pq.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/bazci/githubpost/issues)

</sub>

Jira issue: CRDB-48059

### PR DESCRIPTION
**Pull request by spilchen**
The recent autocommit_before_ddl change (#141145) has affected three lib/pq tests that were not designed with autocommit behavior in mind.

These tests were executing the following sequence:
```
BEGIN
CREATE TEMP TABLE
COPY
```

Since CREATE TEMP TABLE now triggers an auto-commit, the subsequent COPY command fails because it must run inside an active transaction. The error observed was: "pq: COPY is only allowed inside a transaction."

Epic: none
Release note: none

Closes #141899

### CODE REVIEW

**Review by annrpom — APPROVED** [review]
ty for taking these on; we also want to slap backport labels for this for when we merge the backports for the auto commit pr, right?

File: pkg/cmd/roachtest/tests/libpq_blocklist.go [hunk 1]
```diff
@@ -30,6 +30,11 @@ var libPQBlocklist = blocklist{
 	"pq.TestRowsColumnTypes":                         "41688",
 	"pq.TestRuntimeParameters":                       "12137",
 	"pq.TestStringWithNul":                           "26366",
+	// The following tests fail because they weren't designed for the
+	// autocommit_before_ddl behaviour in CRDB.
+	"pq.TestCopyInWrongType":      "unknown",
```
Comment (rafiss) [inline pkg/cmd/roachtest/tests/libpq_blocklist.go:35]: super nit: instead of "unknown", can we put in a short verbal description, or just this PR number so there's a breadcrumb

**Review by rafiss — APPROVED** [review]

File: pkg/cmd/roachtest/tests/libpq_blocklist.go (hunk 1 above)
Comment (spilchen) [reply pkg/cmd/roachtest/tests/libpq_blocklist.go]: Makes sense. I couldn't find a suitable precedence for this sort of thing.

**Review by spilchen — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/142038)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @rafiss)

**Comment by spilchen** [comment]
> ty for taking these on; we also want to slap backport labels for this for when we merge the backports for the auto commit pr, right?

Yes, good point. I'll get this back ported. I'll leave the labels off this PR because I don't want blathers to create a new PR. Instead I'll cherry pick the comment into these two PRs: #141851 and #141987

**Comment by spilchen** [comment]
TFTR!

bors r+
