### PR TITLE
backup: explicitly require full path for backup compaction builtin

### LINKED ISSUE #143543: backup: TestScheduledBackupCompaction failed
backup.TestScheduledBackupCompaction [failed](https://mesolite.cluster.engflow.com/invocations/default/4aca5543-55e8-489e-9f14-60efbcf1ffee?testReportRun=1&testReportShard=18&testReportAttempt=1#targets-Ly9wa2cvYmFja3VwOmJhY2t1cF90ZXN0) on master @ [4c0f5dcfc1b8dd198cded693c646f8f002bc6852](https://github.com/cockroachdb/cockroach/commits/4c0f5dcfc1b8dd198cded693c646f8f002bc6852):

```
=== RUN   TestScheduledBackupCompaction
    test_log_scope.go:165: test logs captured to: outputs.zip/logTestScheduledBackupCompaction1720045015
    test_log_scope.go:76: use -show-logs to present logs inline
    backup_compaction_test.go:515: condition failed to evaluate within 45s: sql: no rows in result set
    panic.go:635: -- test log scope end --
test logs left over in: outputs.zip/logTestScheduledBackupCompaction1720045015
--- FAIL: TestScheduledBackupCompaction (56.66s)
```

Parameters:
 - <code>attempt=1</code>
 - <code>run=1</code>
 - <code>shard=18</code>
<details><summary>Help</summary>
<p>

See also: [How To Investigate a Go Test Failure \(internal\)](https://cockroachlabs.atlassian.net/l/c/HgfXfJgM)
</p>
</details>
/cc @cockroachdb/disaster-recovery
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*TestScheduledBackupCompaction.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/bazci/githubpost/issues)

</sub>

Jira issue: CRDB-48903

### PR DESCRIPTION
**Pull request by kev-cao**
For the backup compaction builtin, the full backup path must be explicitly stated. If LATEST is used, a race condition can occur where a full backup executes before a compaction job can resolve its destination from its triggering incremental. The full backup will overwrite the LATEST file and compaction will run on the wrong chain and fail.

Fixes: #143543

Release note: None

### CODE REVIEW

**Review by msbutler — APPROVED** [review]

**Comment by msbutler** [comment]
lets' make sure extended ci doesn't catch anything before merging

**Comment by kev-cao** [comment]
TFTR!

bors r=msbutler

**Comment by msbutler** [comment]
@kev-cao looks like the test flaked again. Given the race, i no longer think this query works:
https://github.com/msbutler/cockroach/blob/butler-run-compactions-in-roundtrip/pkg/backup/backup_compaction_test.go#L531

**Comment by kev-cao** [comment]
I'm just glad it caught it before the merge, or else we'd have to go through it all over again.

**Comment by msbutler** [comment]
maybe we should manipulate the test env timestamp to always start at a time where we'd hit this race?

**Comment by msbutler** [comment]
I believe that just means setting the timestamp initially to 22:00, or whatever prev failures suggest

**Comment by kev-cao** [comment]
I think perhaps that should be a separate test/subtest. The failure from this past run where no compaction job is found occurs because if a full backup runs before the triggering incremental, then all following incrementals chain off the full backup, and compaction is never triggered because of it.

**Comment by kev-cao** [comment]
Actually, thinking about it some more, probably fine to keep it in the same test.

File: pkg/backup/backup_compaction_test.go [hunk 1]
```diff
@@ -501,6 +534,19 @@ func TestScheduledBackupCompaction(t *testing.T) {
 
 	th.env.SetTime(inc.NextRun().Add(time.Second))
 	require.NoError(t, th.executeSchedules())
+
+	// Artificially force a scheduled full backup to also execute, which will cause
```
Comment (msbutler) [inline pkg/backup/backup_compaction_test.go:538]: could we randomly exercise the "take a second full path"? i.e.:
```
if rng ==2 {
		full, err = jobs.ScheduledJobDB(th.internalDB()).
			Load(context.Background(), th.env, full.ScheduleID())
		require.NoError(t, err)
		th.env.SetTime(full.NextRun().Add(time.Second))
		require.NoError(t, th.executeSchedules())
		
		th.waitForSuccessfulScheduledJob(t, full.ScheduleID())
}
```

File: pkg/backup/backup_compaction_test.go [hunk 2]
```diff
@@ -462,13 +482,24 @@ func TestScheduledBackupCompaction(t *testing.T) {
 	defer leaktest.AfterTest(t)()
 	defer log.Scope(t).Close(t)
 
-	skip.WithIssue(t, 143543, "flaky test")
-
+	secondFullDone := make(chan struct{})
```
Comment (msbutler) [inline pkg/backup/backup_compaction_test.go:485]: nit: call this `blockCompaction`?

File: pkg/backup/backup_compaction.go [hunk 3]
```diff
@@ -116,6 +118,12 @@ func maybeStartCompactionJob(
 	}
 	startTS, endTS := chain[start].StartTime, chain[end-1].EndTime
 	log.Infof(ctx, "compacting backups from %s to %s", startTS, endTS)
+	testingKnobs := execCfg.BackupRestoreTestingKnobs
+	if testingKnobs != nil && testingKnobs.RunBeforeTriggeringCompaction != nil {
```
Comment (msbutler) [inline pkg/backup/backup_compaction.go:122]: responding to your slack message about the complicated inc backup success state verification: could you put the testing knob at the top of the compaction resumer instead in planning?

File: pkg/backup/create_scheduled_backup_test.go [hunk 4]
```diff
@@ -76,18 +76,23 @@ func newTestHelper(t *testing.T) (*testHelper, func()) {
...
+			},
+			CaptureJobExecutionConfig: func(config *scheduledjobs.JobExecutionConfig) {
+				th.cfg = config
+			},
+			IntervalOverrides: jobs.NewTestingKnobsWithShortIntervals().IntervalOverrides,
 		},
-		IntervalOverrides: jobs.NewTestingKnobsWithShortIntervals().IntervalOverrides,
+	}
+	for _, testKnob := range testKnobs {
+		testKnob(&knobs)
```
Comment (msbutler) [inline pkg/backup/create_scheduled_backup_test.go:95]: i like this pattern!

**Review by msbutler — APPROVED** [review]
Nice job here! This was a hard one to debug. Hope 3rd time is the charm

**Comment by kev-cao** [comment]
TFTR! Fingers crossed

bors r=msbutler
