### PR TITLE
sql: better inform the end-user about cluster virtualization

### LINKED ISSUE #111132: cv: Add guardrails to prevent misuse of cluster virtualization
When cluster virtualization is enabled in a shared-process configuration, it's possible for the user to make several UX mistakes:

* Create application data in the system tenant
* Set TenantWritable cluster settings in the system tenant
* Attempt to set TenantReadOnly cluster settings in the application tenant
* Attempt to perform some system debugging/repair from the incorrect tenant

This issue proposes a new cluster setting which, when set in shared-process cluster virtualization, will put guardrails on the cluster's use in the following ways:

* Block DDL and SET CLUSTER SETTING on TenantWritable variables
* Block descriptor repair and other tooling used by troubleshooting; also possibly some of the CLI commands from being executed in the system tenant
* Add an error message which will alert the user to the necessary action should they attempt to modify a SystemOnly or ReadOnly cluster setting from the app tenant 

Epic: CRDB-26691

### PR DESCRIPTION
**Pull request by knz**
First commit from #111569 and #111587.
Fixes #111132.
Epic: CRDB-26691

Release note (cluster virtualization): Two guardrails are available to
system operators to help with users upgrading from single-tenant,
non-virtualized CockroachDB to a deployment using cluster
virtualization.

Specifically, this is intended to help in cases where the user is not
connected to the "right" SQL interface to perform certain
configuration operations.

There are two guardrails included here:

- new cluster setting `sql.restrict_system_interface.enabled` to push
  the user towards using a virtual cluster for their application
  workload. When set, certain common operations that an end-users
  may execute to set up an application workload are disallowed:

  - running DDL.

    For example:
    ```
    demo@127.0.0.1:26257/system/defaultdb> create database foo;
    ERROR: blocked DDL from the system interface
    SQLSTATE: 42501
    HINT: Object creation blocked via sql.restrict_system_interface.enabled to prevent likely user errors.
    Try running the DDL from a virtual cluster instead.
    ```

  - modifying an ApplicationLevel cluster setting.

    For example:
    ```
    demo@127.0.0.1:26257/system/defaultdb> set cluster setting ui.display_timezone = 'America/New_York';
    ERROR: blocked update to application-level setting from the system interface
    SQLSTATE: 42501
    HINT: Access blocked via sql.restrict_system_interface.enabled to prevent likely user errors.
    Try changing the setting from a virtual cluster instead.
    ```

- new cluster setting `sql.error_tip_system_interface.enabled` to
  enhance errors reported when a user mistakenly uses a storage-level
  SQL feature from a virtual cluster, to inform a user who might blindly
  follow an old runbook that they should use the system interface
  instead.

  For example, for setting that were previously application-level:
  ```
  demo@127.0.0.1:26257/demoapp/defaultdb> set cluster setting kv.rangefeed.enabled = true;
  NOTICE: ignoring attempt to modify "kv.rangefeed.enabled"
  HINT: The setting is only modifiable by the operator.
  Normally, an error would be reported, but the operation is silently accepted here as configured by "sql.error_tip_system_interface.enabled".
  ```

  And for settings that were always system-level:
  ```
  demo@127.0.0.1:26257/demoapp/defaultdb> set cluster setting trace.redact_at_virtual_cluster_boundary.enabled = false;
  ERROR: cannot modify storage-level setting from virtual cluster
  SQLSTATE: 42501
  HINT: Connect to the system interface and modify the cluster setting from there.
  ```

### CODE REVIEW

**Review by yuzefovich — COMMENTED** [review]
This looks good to me, but I think we'd benefit from a review from @cockroachdb/sql-foundations to make sure that `createDescriptor` catches all operations that we want to guardrail.

> Reviewed 18 of 18 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/111568#-:-NflPAya4K7j6vWsstEA:b2abia6)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @knz and @stevendanna)

___
*[`-- commits` line 22 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/111568#-NflLximAkIG9iLjHFsv):*
nit: `s/that an/that/`.
___
*[`pkg/sql/descriptor.go` line 226 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/111568#-NflPMVY-g5SCfoO33AE:-NflPMVY-g5SCfoO33AF:ba4vpdr) ([raw file](https://github.com/cockroachdb/cockroach/blob/9ae2ae74afba0d1162d15a33b91be2be7d649335/pkg/sql/descriptor.go#L226)):*
> ```Go
> }
> 
> func (p *planner) createDescriptor(
> ```

Do you think that non-create statements aren't as important to guardrail? Say dropping something or adding a column.

**Comment by knz** [comment]
My reasoning was that if you can't create anything then you also don't have anything to modify.

You could perhaps be concerned with the case when the setting is set after there are some objects already. But that does not seem to match the risk we identified in pre-mortem.

@stevendanna can you remind us precisely which operations should block and why? Once we have that I will approach the sql F team.

File: pkg/sql/set_cluster_setting.go [hunk 1]
```diff
@@ -123,16 +124,76 @@ func checkPrivilegesForSetting(
...
+// to prevent the following UX surprise:
+//
+//   - end-user desires to achieve a certain outcome in a virtual cluster;
+//   - however, they mess up their connection string and connect to the
+//     system tenant instead;
+//   - without this setting, the resulting SQL would succeed in the
+//     system tenant and the user would not realize they were not
+//     connected to the right place.
+var RestrictAccessToSystemInterface = settings.RegisterBoolSetting(
+	settings.SystemOnly,
```
Comment (stevendanna) [inline pkg/sql/set_cluster_setting.go:138]: This is an interesting case of SystemOnly since it is ready via SQL.

File: pkg/sql/descriptor.go [hunk 2]
```diff
@@ -226,6 +226,14 @@ func (p *planner) createDatabase(
 func (p *planner) createDescriptor(
 	ctx context.Context, descriptor catalog.MutableDescriptor, jobDesc string,
 ) error {
+	if p.ExecCfg().Codec.ForSystemTenant() && !p.EvalContext().SessionData().Internal &&
+		RestrictAccessToSystemInterface.Get(&p.ExecCfg().Settings.SV) {
```
Comment (stevendanna) [inline pkg/sql/descriptor.go:230]: I could see having two methods on the planner `(p *planner ) shouldRestrictSystemInterfaceAccess() bool` that you could use here and in set_cluster_setting.go

File: pkg/sql/logictest/testdata/logic_test/tenant [hunk 3]
```diff
@@ -550,3 +550,26 @@ RESET CLUSTER SETTING server.controller.default_target_cluster
...
 statement ok
 DROP TENANT withservice
+
+subtest restrict_system_access
+
+statement ok
+SET CLUSTER SETTING sql.restrict_system_interface.enabled = true
+
+statement error blocked update to application-level setting.*\nHINT:.*\nTry changing the setting from a virtual cluster
+SET CLUSTER SETTING ui.display_timezone = 'America/New_York'
```
Comment (stevendanna) [inline pkg/sql/logictest/testdata/logic_test/tenant:560]: This is an interesting example because on the destination cluster where operators will be managing their physical replication job, perhaps they do what to set this.

However, in that case, they can flip sql.restrict_system_interface.enabled off and back on.

File: pkg/sql/set_cluster_setting.go [hunk 4]
```diff
@@ -143,14 +204,27 @@ func (p *planner) SetClusterSetting(
...
+		}
+	} else {
+		switch setting.Class() {
+		case settings.ApplicationLevel:
+			if !p.EvalContext().SessionData().Internal && RestrictAccessToSystemInterface.Get(&p.ExecCfg().Settings.SV) {
+				return nil, errors.WithHintf(
+					pgerror.Newf(pgcode.InsufficientPrivilege, "blocked update to application-level setting %s from the system interface", setting.Name()),
+					"Access blocked via %s to prevent likely user errors.\n"+
+						"Try changing the setting from a virtual cluster instead.", RestrictAccessToSystemInterface.Name())
+			}
```
Comment (stevendanna) [inline pkg/sql/set_cluster_setting.go:227]: I worry a little that this is going to be too broad.  Some of these settings perhaps well fix to be SystemVisible, but settings like `enterprise.license`, `cluster.organization` need to be set in both clusters currently.

**Review by stevendanna — COMMENTED** [review]
Overall the code looks reasonable to me. I left one question around about our thoughts on whether the restriction on application level tenant settings will be too annoying that I'd love your thoughts on.

**Review by knz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/111568)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @stevendanna and @yuzefovich)

___
*[`-- commits` line 22 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/111568#-NflLximAkIG9iLjHFsv):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

nit: `s/that an/that/`.
</blockquote></details>

Fixed.
___
*[`pkg/sql/descriptor.go` line 230 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/111568#gh-1343707580:-NfvKoys1WICItAlf-FE:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/b3d2ce11c8787cf763ab9e5018d355b083753cc7/pkg/sql/descriptor.go#L230)):*
<details><summary><i>Previously, stevendanna (Steven Danna) wrote…</i></summary><blockquote>

I could see having two methods on the planner `(p *planner ) shouldRestrictSystemInterfaceAccess() bool` that you could use here and in set_cluster_setting.go
</blockquote></details>

Done.
___
*[`pkg/sql/descriptor.go` line 226 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/111568#-NflPMVY-g5SCfoO33AE:-NfvIhYn4C1cG8_QTuQq:b-jhdeyk) ([raw file](https://github.com/cockroachdb/cockroach/blob/9ae2ae74afba0d1162d15a33b91be2be7d649335/pkg/sql/descriptor.go#L226)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

Do you think that non-create statements aren't as important to guardrail? Say dropping something or adding a column.
</blockquote></details>

See the discussion with Steven, yes this is what I think currently. We can add additional checks at a later stage if we find it important.
___
*[`pkg/sql/set_cluster_setting.go` line 138 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/111568#gh-1343697276:-NfvNNqk2KOB0ryS8q5A:b-9l19bb) ([raw file](https://github.com/cockroachdb/cockroach/blob/b3d2ce11c8787cf763ab9e5018d355b083753cc7/pkg/sql/set_cluster_setting.go#L138)):*
<details><summary><i>Previously, stevendanna (Steven Danna) wrote…</i></summary><blockquote>

This is an interesting case of SystemOnly since it is ready via SQL.
</blockquote></details>

Yeah this also raised my eyebrows. What do you think is best? We could tweak the explanatory guidance in settings.go, or change this to SystemVisible here even though it's leaking something that doesn't need to.
___
*[`pkg/sql/set_cluster_setting.go` line 227 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/111568#gh-1343719722:-NfvNYq81Dx6E1YOQf02:bck8q3g) ([raw file](https://github.com/cockroachdb/cockroach/blob/b3d2ce11c8787cf763ab9e5018d355b083753cc7/pkg/sql/set_cluster_setting.go#L227)):*
<details><summary><i>Previously, stevendanna (Steven Danna) wrote…</i></summary><blockquote>

I worry a little that this is going to be too broad.  Some of these settings perhaps well fix to be SystemVisible, but settings like `enterprise.license`, `cluster.organization` need to be set in both clusters currently.
</blockquote></details>

Let's iterate on this. I have an idea. I'll ping you when ready.

**Comment by knz** [comment]
PTAL -- as discussed off-thread, we needed a special case for settings like `cluster.organization` and `enterprise.license` which used to be ApplicationLevel but are not any more. For those, we want to avoid breaking existing automation, and so we turn them into no-ops when the "tip" setting is enabled.

**Review by stevendanna — APPROVED** [review]
Thanks for all of your work on this.  I like what you've landed on here.

> Reviewed 32 of 32 files at r5.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/111568#-:-Ng4aOd33hoxl1vPAuCy:bu3l0cm)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @knz and @yuzefovich)

___
*[`pkg/sql/set_cluster_setting.go` line 138 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/111568#gh-1343697276:-Ng4_IA-7IyzaXAhp_T9:b-srihrq) ([raw file](https://github.com/cockroachdb/cockroach/blob/b3d2ce11c8787cf763ab9e5018d355b083753cc7/pkg/sql/set_cluster_setting.go#L138)):*
<details><summary><i>Previously, knz (Raphael 'kena' Poss) wrote…</i></summary><blockquote>

Yeah this also raised my eyebrows. What do you think is best? We could tweak the explanatory guidance in settings.go, or change this to SystemVisible here even though it's leaking something that doesn't need to.
</blockquote></details>

I think this is resolved with the discussion and update to the terminology we made during the tech pod.

**Review by yuzefovich — APPROVED** [review]
:lgtm:

> Reviewed 32 of 32 files at r5, 30 of 30 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/111568#-:-Ng4ePk67qTPGsXxATwi:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @knz and @stevendanna)

___
*[`pkg/sql/set_cluster_setting.go` line 160 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/111568#-Ng4cq5dEdZaS1zxQ3P9:-Ng4cq5dEdZaS1zxQ3PA:b-2855ax) ([raw file](https://github.com/cockroachdb/cockroach/blob/2aa14f79535c0b5a97fc70a0ef94b60a72937272/pkg/sql/set_cluster_setting.go#L160)):*
> ```Go
> 		//   as a no-op_ with a simple NOTICE.
> 		//
> 		// - the setting exist and has always been non-application. Either
> ```

nit: `s/exist/exists/`.
___
*[`pkg/sql/set_cluster_setting.go` line 167 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/111568#-Ng4cuoK-GG1FZCZg2t1:-Ng4cuoK-GG1FZCZg2t2:b-iipjm8) ([raw file](https://github.com/cockroachdb/cockroach/blob/2aa14f79535c0b5a97fc70a0ef94b60a72937272/pkg/sql/set_cluster_setting.go#L167)):*
> ```Go
> 		//
> 
> 		// Check if the setting exist at all, perhaps as a system setting.
> ```

nit: ditto

**Review by knz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/111568)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @stevendanna and @yuzefovich)

___
*[`pkg/sql/set_cluster_setting.go` line 160 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/111568#-Ng4cq5dEdZaS1zxQ3P9:-NgO4l4X7uODQD7HPEmI:bt2vr1b) ([raw file](https://github.com/cockroachdb/cockroach/blob/2aa14f79535c0b5a97fc70a0ef94b60a72937272/pkg/sql/set_cluster_setting.go#L160)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

nit: `s/exist/exists/`.
</blockquote></details>

Fixed.
___
*[`pkg/sql/set_cluster_setting.go` line 167 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/111568#-Ng4cuoK-GG1FZCZg2t1:-NgO4lif0mmtb5jmKtTV:bt2vr1b) ([raw file](https://github.com/cockroachdb/cockroach/blob/2aa14f79535c0b5a97fc70a0ef94b60a72937272/pkg/sql/set_cluster_setting.go#L167)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

nit: ditto
</blockquote></details>

Fixed.

**Comment by knz** [comment]
bors r=stevendanna,yuzefovich

**Comment by knz** [comment]
bors r=stevendanna,yuzefovich

**Comment by knz** [comment]
bors r=stevendanna,yuzefovich
