### PR TITLE
logictest: skip v22.1 mixed version tests that use ARM

### LINKED ISSUE #95065: logictest: do not run ARM builds in mixed version tests with versions less than v22.2
pkg/sql/logictest/tests/cockroach-go-testserver-22.1-22.2/cockroach-go-testserver-22_1-22_2_test.TestLogic_testserver_test_22_1_22_2 [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Ci_TestsAwsLinuxArm64_UnitTests/8278267?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Ci_TestsAwsLinuxArm64_UnitTests/8278267?buildTab=artifacts#/) on master @ [dc273e05120f28f9ef9a8f8eb60ef678fc105756](https://github.com/cockroachdb/cockroach/commits/dc273e05120f28f9ef9a8f8eb60ef678fc105756):

```
=== RUN   TestLogic_testserver_test_22_1_22_2
    test_log_scope.go:161: test logs captured to: /artifacts/tmp/_tmp/f0512f3559a6f1fc0be49477689a2598/logTestLogic_testserver_test_22_1_22_2994206753
    test_log_scope.go:79: use -show-logs to present logs inline
    logic.go:1838: 
        :0: error while processing
    logic.go:1838: unexpected HTTP response from https://binaries.cockroachdb.com/cockroach-v22.1.6.linux-arm64.tgz?ci=true: 404
        <html><body>
        <h1>404 Error: Not Found</h1>
        </body></html>
    panic.go:522: -- test log scope end --
test logs left over in: /artifacts/tmp/_tmp/f0512f3559a6f1fc0be49477689a2598/logTestLogic_testserver_test_22_1_22_2994206753
--- FAIL: TestLogic_testserver_test_22_1_22_2 (0.52s)
```
<details><summary>Help</summary>
<p>

See also: [How To Investigate a Go Test Failure \(internal\)](https://cockroachlabs.atlassian.net/l/c/HgfXfJgM)
</p>
</details>
/cc @cockroachdb/sql-queries
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*TestLogic_testserver_test_22_1_22_2.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)
</sub>

Jira issue: CRDB-23302

### PR DESCRIPTION
**Pull request by rafiss**
fixes https://github.com/cockroachdb/cockroach/issues/95065

There are no ARM builds for this version.

Release note: None

### CODE REVIEW

File: pkg/sql/logictest/logic.go [hunk 1]
```diff
@@ -1819,6 +1819,9 @@ func (t *logicTest) setup(
 
 	if cfg.UseCockroachGoTestserver {
 		skip.UnderStress(t.t(), "test takes a long time and downloads release artifacts")
+		if runtime.GOARCH == "arm64" && strings.HasPrefix(cfg.CockroachGoBootstrapVersion, "v22.1") {
```
Comment (mgartner) [inline pkg/sql/logictest/logic.go:1822]: Should we check `CockroachGoUpgradeVersion` too?

**Review by mgartner — APPROVED** [review]
LGTM

**Review by rail — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/95098)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @mgartner)

___
*[`pkg/sql/logictest/logic.go` line 1822 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/95098#-NLXF8XZsT99xgfgWUkA-r1-1822:-NLXKNNgCc8jMoSwZMi0:b-k62whq) ([raw file](https://github.com/cockroachdb/cockroach/blob/0a2e2e4fdde2b62c12064ec8e82686d8030ce9d2/pkg/sql/logictest/logic.go#L1822)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

Should we check `CockroachGoUpgradeVersion` too?
</blockquote></details>

Can we use a stricter approach, something like
```if runtime.GOARCH == "arm64" && cfg.BootstrapVersion.Less(roachpb.Version{Major: 22, Minor: 2}) {...}```

**Review by rafiss — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/95098)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @mgartner)

___
*[`pkg/sql/logictest/logic.go` line 1822 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/95098#-NLXF8XZsT99xgfgWUkA-r1-1822:-NLXMKJm2GrWjLLQrg6h:bevv9n8) ([raw file](https://github.com/cockroachdb/cockroach/blob/0a2e2e4fdde2b62c12064ec8e82686d8030ce9d2/pkg/sql/logictest/logic.go#L1822)):*
<details><summary><i>Previously, rail (Rail Aliiev) wrote…</i></summary><blockquote>

Can we use a stricter approach, something like
```if runtime.GOARCH == "arm64" && cfg.BootstrapVersion.Less(roachpb.Version{Major: 22, Minor: 2}) {...}```
</blockquote></details>

the `BootstrapVersion` is not used at all for these mixed-version tests: https://github.com/cockroachdb/cockroach/blob/033a395ae83f8175eee609bd4918a31cf807fc9b/pkg/sql/logictest/logictestbase/logictestbase.go#L477-L483

it instead [uses a string for the version](https://github.com/cockroachdb/cockroach/blob/033a395ae83f8175eee609bd4918a31cf807fc9b/pkg/sql/logictest/logic.go#L1861-L1866) since that's how the [`binfetcher` package
](https://github.com/cockroachdb/cockroach/blob/033a395ae83f8175eee609bd4918a31cf807fc9b/pkg/util/binfetcher/binfetcher.go#L98) works.

I'm not too worried about earlier bootstrap versions or checking the `CockroachGoUpgradeVersion`, since these mixed version tests were only added recently, and i don't think it's likely at all for anyone to add a new logictest config where the bootstrap version is less than v22.1. (and consequently, the upgrade version will always be at least v22.2.)
