### PR TITLE
mixedversion: add MinBootstrapVersion option

### LINKED ISSUE #138861: roachtest: http-register-routes/mixed-version failed
roachtest.http-register-routes/mixed-version [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/18459519?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/18459519?buildTab=artifacts#/http-register-routes/mixed-version) on master @ [3cc42e66a71164bd69195ad3c10ab03607a7bc7e](https://github.com/cockroachdb/cockroach/commits/3cc42e66a71164bd69195ad3c10ab03607a7bc7e):

```
(mixedversion.go:804).Run: unexpected node event: n4: cockroach process for virtual cluster "mixed-version-tenant-tmsr1", instance 0 died (exit code 7) [owner=test-eng]
test artifacts and logs in: /artifacts/http-register-routes/mixed-version/run_1
```

Parameters:
 - <code>arch=amd64</code>
 - <code>cloud=gce</code>
 - <code>coverageBuild=false</code>
 - <code>cpu=4</code>
 - <code>encrypted=false</code>
 - <code>mvtDeploymentMode=separate-process</code>
 - <code>mvtVersions=v24.2.7 → v24.3.2 → master</code>
 - <code>runtimeAssertionsBuild=false</code>
 - <code>ssd=0</code>
<details><summary>Help</summary>
<p>

See: [roachtest README](https://github.com/cockroachdb/cockroach/blob/master/pkg/cmd/roachtest/README.md)

See: [How To Investigate \(internal\)](https://cockroachlabs.atlassian.net/l/c/SSSBr8c7)

See: [Grafana](https://go.crdb.dev/roachtest-grafana/teamcity-18459519/http-register-routes-mixed-version/1736580059888/1736580538932)

</p>
</details>
/cc @cockroachdb/test-eng
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*http-register-routes/mixed-version.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/bazci/githubpost/issues)

</sub>

Jira issue: CRDB-46382

### PR DESCRIPTION
**Pull request by DarrylWong**
This change allows test writers to set a MinBootstrapVersion. This option will tell to the mixed version framework to not generate any plans that create a cluster on any versions older than MinBootstrapVersion.

With this new option, the `http-register-routes/mixed-versions` test now sets the MinBootstrapVersion to 24.2, the oldest release that has the fix contained in https://github.com/cockroachdb/cockroach/issues/138342.

Fixes: https://github.com/cockroachdb/cockroach/issues/138861
Release note: none

### CODE REVIEW

File: pkg/cmd/roachtest/roachtestutil/mixedversion/planner_test.go [hunk 1]
```diff
@@ -310,35 +312,39 @@ func Test_maxNumPlanSteps(t *testing.T) {
...
+		if err != nil {
+			return false
+		}
+		fmt.Println(plan.PrettyPrint())
+		require.LessOrEqual(t, plan.length, 13)
+		return true
+	}, 5*time.Second, 100*time.Millisecond)
 
-	// There is in fact no "basic upgrade" test plan with fewer than 15 steps.
+	// There is in fact no "basic upgrade" test plan with fewer than 13 steps.
```
Comment (DarrylWong) [inline pkg/cmd/roachtest/roachtestutil/mixedversion/planner_test.go:326]: It looks like 13 is the actual smallest plan. The original plan commented ran the `mixed-version 2` hook twice and used fixtures (70%) chance.

File: pkg/cmd/roachtest/roachtestutil/mixedversion/testdata/planner/basic_test_mixed_version_hooks [hunk 2]
```diff
@@ -40,39 +40,40 @@ Plan:
 ├── upgrade cluster from "v24.1.1" to "v24.2.2"
 │   ├── prevent auto-upgrades on system tenant by setting `preserve_downgrade_option` (9)
 │   ├── upgrade nodes :1-4 from "v24.1.1" to "v24.2.2"
-│   │   ├── restart node 4 with binary version v24.2.2 (10)
-│   │   ├── restart node 1 with binary version v24.2.2 (11)
+│   │   ├── restart node 1 with binary version v24.2.2 (10)
```
Comment (DarrylWong) [inline pkg/cmd/roachtest/roachtestutil/mixedversion/testdata/planner/basic_test_mixed_version_hooks:43]: RNG unfortunately changed so all these datadriven tests have huge diffs.

File: pkg/cmd/roachtest/roachtestutil/mixedversion/mixedversion.go [hunk 3]
```diff
@@ -966,35 +977,76 @@ func (t *Test) choosePreviousReleases() ([]*clusterupgrade.Version, error) {
 		return []*clusterupgrade.Version{pred, predPred}, nil
 	}
 
+	// possibleUpgradePathsMap maps a version to the possible upgrade paths that
+	// can be taken with exactly n upgrades.
+	possibleUpgradePathsMap := make(map[*clusterupgrade.Version]map[int][][]*clusterupgrade.Version)
+	// findPossibleUpgradePaths finds all legal upgrade paths ending at version `v` with
+	// exactly `numUpgrades` upgrades.
+	var findPossibleUpgradePaths func(v *clusterupgrade.Version, numUpgrades int) ([][]*clusterupgrade.Version, error)
```
Comment (srosenberg) [inline pkg/cmd/roachtest/roachtestutil/mixedversion/mixedversion.go:985]: Nit: `var` declaration seems redundant

File: pkg/cmd/roachtest/roachtestutil/mixedversion/mixedversion.go [hunk 4]
```diff
@@ -1421,6 +1475,39 @@ func assertValidTest(test *Test, fatalFunc func(...interface{})) {
...
+		}
+		if maxUpgradesFromBootstrapVersion < minUpgrades {
+			fail(errors.Newf(
+				"invalid test options: minimum bootstrap version (%s) does not allow for min %d upgrades",
+				minBootstrapVersion, minUpgrades,
+			))
+		}
+		// Override the max upgrades if the minimum bootstrap version does not allow for that
+		// many upgrades.
+		test.options.maxUpgrades = min(maxUpgrades, maxUpgradesFromBootstrapVersion)
```
Comment (srosenberg) [inline pkg/cmd/roachtest/roachtestutil/mixedversion/mixedversion.go:1509]: We should probably log a warning.

File: pkg/cmd/roachtest/roachtestutil/mixedversion/mixedversion.go [hunk 5]
```diff
@@ -458,6 +461,15 @@ func MinimumSupportedVersion(v string) CustomOption {
 	}
 }
 
+// MinimumBootstrapVersion allows tests to specify that the
+// cluster created should only be bootstrapped on a version
```
Comment (srosenberg) [inline pkg/cmd/roachtest/roachtestutil/mixedversion/mixedversion.go:465]: May also override `MaxUpgrades`.

File: pkg/cmd/roachtest/roachtestutil/mixedversion/mixedversion.go [hunk 6]
```diff
@@ -966,35 +977,76 @@ func (t *Test) choosePreviousReleases() ([]*clusterupgrade.Version, error) {
...
+		// upgrades plus version `v`.
+		var paths [][]*clusterupgrade.Version
+		predecessors, err := possiblePredecessorsFor(v)
+		if err != nil {
+			return nil, err
+		}
+		for _, pred := range predecessors {
+			// If the predecessor is older than the minimum bootstrapped version, then
+			// it's not a legal upgrade path.
+			if t.options.minimumBootstrapVersion != nil && !pred.AtLeast(t.options.minimumBootstrapVersion) {
```
Comment (srosenberg) [inline pkg/cmd/roachtest/roachtestutil/mixedversion/mixedversion.go:1009]: `!x.AtLeast(y)` implies `x < y`. Maybe it's worth adding `Version.Less`? :)

Comment (DarrylWong) [reply pkg/cmd/roachtest/roachtestutil/mixedversion/mixedversion.go]: Added as a helper in `clusterupgrade`. I could add it in the `version` pkg too, but I vaguely remember seeing some discussion around why we don't want to add something like that. Can't find it though, maybe it rings a bell for you?

File: pkg/cmd/roachtest/roachtestutil/mixedversion/mixedversion.go (hunk 5 above)
Comment (DarrylWong) [reply pkg/cmd/roachtest/roachtestutil/mixedversion/mixedversion.go:465]: Done.

File: pkg/cmd/roachtest/roachtestutil/mixedversion/mixedversion.go (hunk 4 above)
Comment (DarrylWong) [reply pkg/cmd/roachtest/roachtestutil/mixedversion/mixedversion.go]: Done.

File: pkg/cmd/roachtest/roachtestutil/mixedversion/mixedversion.go (hunk 3 above)
Comment (DarrylWong) [reply pkg/cmd/roachtest/roachtestutil/mixedversion/mixedversion.go:986]: The `var` declaration is needed for the recursion to work since it's a function literal.

File: pkg/cmd/roachtest/roachtestutil/mixedversion/mixedversion.go [hunk 7]
```diff
@@ -844,7 +857,6 @@ func (t *Test) plan() (plan *TestPlan, retErr error) {
 		if err != nil {
 			return nil, err
 		}
-		upgradePath = append(upgradePath, clusterupgrade.CurrentVersion())
```
Comment (herkolategan) [inline pkg/cmd/roachtest/roachtestutil/mixedversion/mixedversion.go:833]: For my own understanding does `t.choosePreviousReleases()` now include `clusterupgrade.CurrentVersion()`? If so, should we update the comment?

**Comment by herkolategan** [comment]
missing a `./dev gen` to fix build file:
```
+++ b/pkg/cmd/roachtest/roachtestutil/mixedversion/BUILD.bazel
@@ -71,6 +71,7 @@ go_test(
         "//pkg/testutils/release",
         "//pkg/util/intsets",
         "//pkg/util/randutil",
+        "//pkg/util/retry",
```

**Comment by herkolategan** [comment]
A nice to have would be to add a small section to the `/mixedversion/REAMDE.md` doc explaining that min bootstrap is different from min version, and what it does.

**Comment by DarrylWong** [comment]
Fun failure on stress that suggests I broke something with the rng 🙃 :

```
=== RUN   Test_stepSelectorFilter/no_filter
    planner_test.go:622:
          Error Trace:  pkg/cmd/roachtest/roachtestutil/mixedversion/planner_test.go:622
          Error:        Object expected to be of type mixedversion.runHookStep, but was mixedversion.restartWithNewBinaryStep
          Test:         Test_stepSelectorFilter/no_filter
--- FAIL: Test_stepSelectorFilter/no_filter (0.01s)
```

Interestingly, this works fine locally when I run `./dev test pkg/cmd/roachtest/roachtestutil/mixedversion --stress --count=50000` as well as `./dev test pkg/cmd/roachtest/roachtestutil/mixedversion --stress --race --count=10000`, but seems to fail pretty consistently on CI

My current (wild) guess is it's something to do with the fact unit tests now use `clusterupgrade.CurrentVersion()` and this somehow behaves different under CI. Sorry in advance for the large amounts of force pushing as I try to debug with CI :)

**Comment by herkolategan** [comment]
> Test_stepSelectorFilter/no_filter

@DarrylWong this baked my noodle for a while :)

But it seems it's **test execution order** that is causing a different scenario (I think a normal stress always runs it in the same order?).

You can easily reproduce the failure with a Test Order Seed:

`_bazel/bin/pkg/cmd/roachtest/roachtestutil/mixedversion/mixedversion_test_/mixedversion_test -test.run=. -test.v -test.shuffle=5`

There's some randomization somewhere that is dependent on test order; and we should probably fix that, I'm curious where it is, but haven't been able to track it down yet.

**Comment by DarrylWong** [comment]
Okay well that was pretty easy to figure out thanks to Herko's repro.

In `withTestBuildVersion` which is used to configure the build version for a test, we correctly try and reset the build version once we're done:

```
return func() { clusterupgrade.TestBuildVersion = nil }
```

Unfortunately we reset it to `nil` (which means to use the build version of the crdb binary, `25.2`) instead of setting it back to our default "test build version" (`24.2`). So if `Test_stepSelectorFilter` is run before any test that calls `withTestBuildVersion`, it will create an upgrade plan to `24.2`, otherwise it will create a plan to `25.2`.

Another case of "i'm shocked this hasn't flaked until now" 😃

**Review by herkolategan — APPROVED** [review]

**Review by herkolategan — APPROVED** [review]

**Comment by herkolategan** [comment]
Browser + internet glitch says this PR is now twice approved 🙃

File: pkg/cmd/roachtest/roachtestutil/mixedversion/mixedversion.go (hunk 3 above)
Comment (srosenberg) [reply pkg/cmd/roachtest/roachtestutil/mixedversion/mixedversion.go:987]: Ah, I see. Same as `letrec` vs `let`.

**Review by srosenberg — APPROVED** [review]

**Comment by DarrylWong** [comment]
Smoke test here: https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/19115007?hideProblemsFromDependencies=false&hideTestsFromDependencies=false&expandBuildChangesSection=true&expandBuildTestsSection=true

acceptance failure is unrelated.

TFTRs!

bors r=herkolategan,srosenberg
