### PR TITLE
sql: wait for one version lease if no job created for a descriptor

### LINKED ISSUE #90600: sql/schemachanger: schema changes without a job do not wait for descriptors
**Describe the problem**
We need to make sure that we wait for one version after schema changes which finish in the user transaction. 

**To Reproduce**

If you run `DROP OWNED BY` and all that needs to happen is revoking privileges, I do not think we wait out the leases. 

**Expected behavior**
We wait out the leases. I think we can just detect whether we created a job around where the post-commit logic runs and if we didn't but we did stuff, then we can wait.

**Additional context**
One thing that makes this a little bit more tricky is you cannot `EXPLAIN (DDL) DROP OWNED BY ...` 

Jira issue: CRDB-20854

### PR DESCRIPTION
**Pull request by chengxiong-ruan**
Previously we only wait for one version in jobs for descriptors performed with schema changes. The problem is that we don't always create jobs for all descriptors modified. We need to wait for one version for these descriptors too. This pr adds logic to wait if there is no jobs created for a descriptor has new version.

Fixes: #90600

Release note: None

### CODE REVIEW

**Comment by chengxiong-ruan** [comment]
> It looks like your PR touches production code but doesn't add or edit any test code. Did you consider adding tests to your PR?
> 
I promise there'll be tests failing like round trips and some tests relevant to DROP....

**Review by ajwerner — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/95620)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @chengxiong-ruan)

___
*[`pkg/sql/conn_executor_exec.go` line 1079 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/95620#-NMUD7XT8CX6SxfzxtSp:-NMUD7XT8CX6SxfzxtSq:bfnbpdg) ([raw file](https://github.com/cockroachdb/cockroach/blob/7e09c3c9c8ad557d0ab838abd151a3bad94dab21/pkg/sql/conn_executor_exec.go#L1079)):*
> ```Go
> 			return err
> 		}
> 	}
> ```

I don't think this is where it belongs. I think it belongs around here: https://github.com/cockroachdb/cockroach/blob/4d3c36a7701c538d6ba8ee61dae0884526bda7ed/pkg/sql/conn_executor.go#L3081-L3085



_Code quote:_
```Go
	//If there is any descriptor has new version. We want to make sure there is
	//only one version of the descriptor in all nodes. In schema changer jobs,
	//`WaitForOneVersion` has been called for the descriptors included in jobs. So
	//we just need to do this for descriptors not in jobs.
	var descIDsInJobs catalog.DescriptorIDSet
	for _, jobID := range *ex.extraTxnState.jobs {
		job, err := ex.server.cfg.JobRegistry.LoadJob(ctx, jobID)
		if err != nil {
			return err
		}
		payload := job.Payload()
		for _, descID := range payload.DescriptorIDs {
			descIDsInJobs.Add(descID)
		}
	}
	for _, idVersion := range withNewVersion {
		if descIDsInJobs.Contains(idVersion.ID) {
			continue
		}
		if _, err := WaitToUpdateLeases(ctx, ex.planner.LeaseMgr(), idVersion.ID); err != nil {
			return err
		}
	}
```

**Comment by chengxiong-ruan** [comment]
I didn't come up with a good way of testing this, but given the amount of test failed and fixed, plus I tried this within the `CREATE FUNCTION` scenario where schema need to converge at one version before transaction returns (to at least make logic tests working). I think it should work.

File: pkg/sql/conn_executor.go [hunk 1]
```diff
@@ -3113,6 +3128,64 @@ func (ex *connExecutor) handleWaitingForDescriptorIDGeneratorMigration(ctx conte
...
+			if errors.Is(err, catalog.ErrDescriptorNotFound) {
+				continue
+			}
+			return err
+		}
+	}
+	return nil
+}
+
+func (ex *connExecutor) descIDsInJobs() (catalog.DescriptorIDSet, error) {
```
Comment (ajwerner) [inline pkg/sql/conn_executor.go:3158]: I don't know about this -- this is a very expensive thing to do. 

I think we can do better. Namely, we buffer jobs we create with schema changes for a while. We can extract the desc IDs from that set and we can also extract a set from the declarative schema changer state if we create one, maybe. I'd like it to be the case that we don't go to the kv-store to decide what to wait on.

Comment (chengxiong-ruan) [reply pkg/sql/conn_executor.go:3158]: Yeah, I agree. There is sometimes other jobs like query statistics. I think 2 options:
(1) How about we only do this if there is any new version descriptors. This would only affect schema changes with jobs.
(2) Cache job records in the `extraTxnState` as well in addition to the job ids. In legacy schema changer it seems obvious that how job records are passed around. It's not clear to me how we can plumb the job record out of schema changer yet, but I can take a look.

Comment (ajwerner) [reply pkg/sql/conn_executor.go:3158]: For the declarative schema changer, all you need to know is whether a job was created or not.

File: pkg/sql/conn_executor.go [hunk 2]
```diff
@@ -3687,3 +3759,56 @@ func init() {
...
+}
+
+func (j *jobsInfo) addNonUniqueJobToCreate(jobRecord *jobs.Record) {
+	j.nonUniqueJobsToCreate = append(j.nonUniqueJobsToCreate, jobRecord)
+}
+
+func (j *jobsInfo) reset() {
+	j.jobsCreated.reset()
+	j.uniqueJobsToCreate = make(map[descpb.ID]*jobs.Record)
+	j.nonUniqueJobsToCreate = nil
```
Comment (ajwerner) [inline pkg/sql/conn_executor.go:3786]: clear the map rather than making a new one. There's a compiler intrinsic, and nobody else has the map.

```
for id := range j.uniqueJobsToCreate {
    delete(j.uniqueJobsToCreate, id)
}
```

File: pkg/sql/conn_executor.go [hunk 3]
```diff
@@ -3687,3 +3759,56 @@ func init() {
...
+	for _, r := range j.nonUniqueJobsToCreate {
+		if err := fn(r); err != nil {
+			return err
+		}
+	}
+	return nil
+}
+
+func (j *jobsInfo) releaseJobsToRecreate() {
+	j.uniqueJobsToCreate = make(map[descpb.ID]*jobs.Record)
```
Comment (ajwerner) [inline pkg/sql/conn_executor.go:3812]: same here about clearing the map as opposed to allocating a new one

File: pkg/sql/conn_executor.go [hunk 4]
```diff
@@ -3113,6 +3112,79 @@ func (ex *connExecutor) handleWaitingForDescriptorIDGeneratorMigration(ctx conte
...
+		}
+	}
+	return nil
+}
+
+func (ex *connExecutor) descIDsInJobs() (catalog.DescriptorIDSet, error) {
+	// Get descriptor IDs from legacy schema changer jobs.
+	var descIDsInJobs catalog.DescriptorIDSet
+	if err := ex.extraTxnState.jobsInfo.forEachJobToCreate(func(jobRecord *jobs.Record) error {
+		for _, descID := range jobRecord.DescriptorIDs {
```
Comment (ajwerner) [inline pkg/sql/conn_executor.go:3146]: Does this cause problems for other types of jobs than schema changes like gc jobs or changefeeds? can we make sure the job has a relevant type where we know there will be waiting? Maybe rename this function to reference schema change jobs, and describe on this function why those schema change jobs are special?

File: pkg/sql/conn_executor.go [hunk 5]
```diff
@@ -3687,3 +3759,56 @@ func init() {
 		return planGistFromCtx(ctx)
 	})
 }
+
+type jobsInfo struct {
```
Comment (ajwerner) [inline pkg/sql/conn_executor.go:3763]: I think you can come up with a better name for this structure. `txnJobsCollection`?

File: pkg/sql/conn_executor.go [hunk 6]
```diff
@@ -1275,18 +1275,7 @@ type connExecutor struct {
...
-		// pkg/sql/planner.go. The staged jobs are executed once the transaction
-		// that staged them commits.
-		jobs *jobsCollection
-
-		// schemaChangeJobRecords is a map of descriptor IDs to job Records.
-		// Used in createOrUpdateSchemaChangeJob so we can check if a job has been
-		// queued up for the given ID. The cache remains valid only for the current
-		// transaction and it is cleared after the transaction is committed.
-		schemaChangeJobRecords map[descpb.ID]*jobs.Record
+		jobsInfo *jobsInfo
```
Comment (ajwerner) [inline pkg/sql/conn_executor.go:1278]: I feel like `jobs` is a good name for this field

File: pkg/sql/conn_executor.go [hunk 7]
```diff
@@ -3687,3 +3759,56 @@ func init() {
 		return planGistFromCtx(ctx)
 	})
 }
+
+type jobsInfo struct {
+	jobsCreated           jobsCollection
```
Comment (ajwerner) [inline pkg/sql/conn_executor.go:3764]: nit: name this `created`. It's obviously about jobs in this context.

File: pkg/sql/conn_executor.go [hunk 8]
```diff
@@ -3687,3 +3759,56 @@ func init() {
...
+	uniqueJobsToCreate    map[descpb.ID]*jobs.Record
```
Comment (ajwerner) [inline pkg/sql/conn_executor.go:3765]: nit: name this `uniqueToCreate` and the other one `nonUniqueToCreate` and use comments to explain what makes them different.

File: pkg/sql/conn_executor.go [hunk 9]
```diff
@@ -3113,6 +3112,79 @@ func (ex *connExecutor) handleWaitingForDescriptorIDGeneratorMigration(ctx conte
 	return ex.resetTransactionOnSchemaChangeRetry(ctx)
 }
 
+func (ex *connExecutor) waitOneVersionForNewVersionDescriptorsWithoutJobs(
```
Comment (ajwerner) [inline pkg/sql/conn_executor.go:3115]: this file is too big already. What do you think about moving all this job related code to a new file `conn_executor_jobs.go` and moving the `jobsCollection` and its friends to a file `jobs_collection.go`?

File: pkg/sql/conn_executor.go (hunk 4 above)
Comment (ajwerner) [reply pkg/sql/conn_executor.go:3146]: I think it'd be good to describe in commentary here the semantics of this field for the different types of schema changes.

File: pkg/sql/conn_executor.go [hunk 10]
```diff
@@ -3687,3 +3759,56 @@ func init() {
...
+
+func (j *jobsInfo) numJobsToCreate() int {
+	return len(j.uniqueJobsToCreate) + len(j.nonUniqueJobsToCreate)
+}
+
+func (j *jobsInfo) hasJobsToCreate() bool {
+	return j.numJobsToCreate() > 0
+}
+
+func (j *jobsInfo) forEachJobToCreate(fn func(jobRecord *jobs.Record) error) error {
```
Comment (ajwerner) [inline pkg/sql/conn_executor.go:3797]: nit: i think you can remove the word `jobs` from all these methods and improve readability. `x.jobs.forEachToCreate`, `x.jobs.numToCreate`, `x.jobs.hasAnyToCreate`? That's just my taste.

**Review by ajwerner — COMMENTED** [review]
This is close. I want to tighten up the code around waiting. The stuff around jobs code is superficial.

File: pkg/sql/conn_executor.go (hunk 6 above)
Comment (chengxiong-ruan) [reply pkg/sql/conn_executor.go]: done.

File: pkg/sql/conn_executor.go (hunk 9 above)
Comment (chengxiong-ruan) [reply pkg/sql/conn_executor.go]: good point. moved them to new files.

File: pkg/sql/conn_executor.go (hunk 4 above)
Comment (chengxiong-ruan) [reply pkg/sql/conn_executor.go]: jobs like gc and changefeeds are fine. I renamed it to `descIDsInSchemaChangeJobs` as suggested and add more comments. I also move the iteration on `DescriptorIDs` into the `switch` block so that we only use these ids when it's actually a schema change job.

File: pkg/sql/conn_executor.go (hunk 5 above)
Comment (chengxiong-ruan) [reply pkg/sql/conn_executor.go]: yes, done.

File: pkg/sql/conn_executor.go (hunk 7 above)
Comment (chengxiong-ruan) [reply pkg/sql/conn_executor.go]: done.

File: pkg/sql/conn_executor.go (hunk 8 above)
Comment (chengxiong-ruan) [reply pkg/sql/conn_executor.go]: done.

File: pkg/sql/conn_executor.go (hunk 2 above)
Comment (chengxiong-ruan) [reply pkg/sql/conn_executor.go]: done.

File: pkg/sql/conn_executor.go (hunk 10 above)
Comment (chengxiong-ruan) [reply pkg/sql/conn_executor.go]: done.

File: pkg/sql/conn_executor.go (hunk 3 above)
Comment (chengxiong-ruan) [reply pkg/sql/conn_executor.go]: done.

File: pkg/sql/conn_executor_jobs.go [hunk 11]
```diff
@@ -0,0 +1,109 @@
...
+			}
+			descIDsInJobs.Add(t.SchemaChange.DroppedDatabaseID)
+			descIDsInJobs.Add(t.SchemaChange.DescID)
+		}
+		return nil
+	}); err != nil {
+		return catalog.DescriptorIDSet{}, err
+	}
+
+	// Get descriptor IDs with declarative schema changer jobs.
```
Comment (ajwerner) [inline pkg/sql/conn_executor_jobs.go:93]: Is this the best way to do this? I think it's fine, but would it be better if we were more explicit about it? For one, I don't know if `HasConcurrentSchemaChanges` is what you want. I think it works, but it's brute force and relies on the loop above. Could we instead check on the declarative schema changer state and see if it has a job, and, if it does not, go and collect the descriptor IDs which have been modified?

File: pkg/sql/jobs_collection.go [hunk 12]
```diff
@@ -0,0 +1,83 @@
...
+
+package sql
+
+import (
+	"github.com/cockroachdb/cockroach/pkg/jobs"
+	"github.com/cockroachdb/cockroach/pkg/jobs/jobspb"
+	"github.com/cockroachdb/cockroach/pkg/sql/catalog/descpb"
+)
+
+type txnJobsCollection struct {
```
Comment (ajwerner) [inline pkg/sql/jobs_collection.go:19]: nit: comment what this is used for

File: pkg/sql/internal.go [hunk 13]
```diff
@@ -1007,9 +1004,7 @@ func (ie *InternalExecutor) execInternal(
 
 // ReleaseSchemaChangeJobRecords is to release the schema change job records.
 func (ie *InternalExecutor) releaseSchemaChangeJobRecords() {
```
Comment (ajwerner) [inline pkg/sql/internal.go:1006]: kill this function altogether. Look at the one place it was called. That thing can just invoke this function.

File: pkg/sql/internal.go [hunk 14]
```diff
@@ -1239,11 +1234,10 @@ func (ncl *noopClientLock) RTrim(_ context.Context, pos CmdPos) {
...
 // fields here and keep them in sync.
 type extraTxnState struct {
-	txn                    *kv.Txn
-	descCollection         *descs.Collection
-	jobs                   *jobsCollection
-	schemaChangeJobRecords map[descpb.ID]*jobs.Record
-	schemaChangerState     *SchemaChangerState
+	txn                *kv.Txn
+	descCollection     *descs.Collection
+	jobsInfo           *txnJobsCollection
```
Comment (ajwerner) [inline pkg/sql/internal.go:1239]: nit: rename this to `jobs`

File: pkg/sql/internal.go [hunk 15]
```diff
@@ -1361,25 +1355,24 @@ func (ief *InternalDB) newInternalExecutorWithTxn(
...
 		},
 	}
 	populateMinimalSessionData(sd)
 	ie.sessionDataStack = sessiondata.NewStack(sd)
 
 	commitTxnFunc := func(ctx context.Context) error {
 		defer func() {
-			ie.extraTxnState.jobs.reset()
+			ie.extraTxnState.jobsInfo.reset()
 			ie.releaseSchemaChangeJobRecords()
```
Comment (ajwerner) [inline pkg/sql/internal.go:1370]: This relates to my above comment. IIUC, the `reset` already makes the second function a no-op. This can now just be: `defer ie.extraTxnState.jobs.reset()`

File: pkg/sql/planner.go [hunk 16]
```diff
@@ -95,15 +95,7 @@ type extendedEvalContext struct {
...
-	// Jobs refers to jobs in extraTxnState. Jobs is a pointer to a jobsCollection
-	// which is a slice because we need calls to resetExtraTxnState to reset the
-	// jobsCollection.
-	Jobs *jobsCollection
-
-	// SchemaChangeJobRecords refers to schemaChangeJobsCache in extraTxnState of
-	// in sql.connExecutor. sql.connExecutor.createJobs() enqueues jobs with these
-	// records when transaction is committed.
-	SchemaChangeJobRecords map[descpb.ID]*jobs.Record
+	JobsInfo *txnJobsCollection
```
Comment (ajwerner) [inline pkg/sql/planner.go:98]: call this `jobs`. it does not need to be exported.

File: pkg/sql/jobs_collection.go (hunk 12 above)
Comment (chengxiong-ruan) [reply pkg/sql/jobs_collection.go:22]: done

File: pkg/sql/conn_executor_jobs.go [hunk 17]
```diff
@@ -0,0 +1,117 @@
...
+package sql
+
+import (
+	"github.com/cockroachdb/cockroach/pkg/jobs"
+	"github.com/cockroachdb/cockroach/pkg/jobs/jobspb"
+	"github.com/cockroachdb/cockroach/pkg/sql/catalog"
+	"github.com/cockroachdb/errors"
+)
+
+func (ex *connExecutor) waitOneVersionForNewVersionDescriptorsWithoutJobs(
```
Comment (ajwerner) [inline pkg/sql/conn_executor_jobs.go:20]: Give this a comment on why we want to do it / why it matters

File: pkg/sql/jobs_collection.go [hunk 18]
```diff
@@ -0,0 +1,86 @@
...
+	}
+	for _, r := range j.nonUniqueToCreate {
+		if err := fn(r); err != nil {
+			return err
+		}
+	}
+	return nil
+}
+
+func (j *txnJobsCollection) releaseToRecreate() {
```
Comment (ajwerner) [inline pkg/sql/jobs_collection.go:81]: nothing uses this, remove it.

File: pkg/sql/jobs_collection.go [hunk 19]
```diff
@@ -0,0 +1,86 @@
...
+// licenses/APL.txt.
+
+package sql
+
+import (
+	"github.com/cockroachdb/cockroach/pkg/jobs"
+	"github.com/cockroachdb/cockroach/pkg/jobs/jobspb"
+	"github.com/cockroachdb/cockroach/pkg/sql/catalog/descpb"
+)
+
```
Comment (ajwerner) [inline pkg/sql/jobs_collection.go:18]: also move `jobsCollection` to this file

**Review by ajwerner — APPROVED** [review]
LGTM after addressing the comments

File: pkg/sql/conn_executor_jobs.go (hunk 17 above)
Comment (chengxiong-ruan) [reply pkg/sql/conn_executor_jobs.go:27]: done.

File: pkg/sql/jobs_collection.go (hunk 18 above)
Comment (chengxiong-ruan) [reply pkg/sql/jobs_collection.go]: removed.

File: pkg/sql/jobs_collection.go (hunk 19 above)
Comment (chengxiong-ruan) [reply pkg/sql/jobs_collection.go:18]: done.

**Comment by chengxiong-ruan** [comment]
TFTR!
bors r+
