### PR TITLE
sql: fix type hydration in some cases

### LINKED ISSUE #86079: pkg/sql/logictest/tests/fakedist-vec-off/fakedist-vec-off_test: TestLogic_partial_index failed
pkg/sql/logictest/tests/fakedist-vec-off/fakedist-vec-off_test.TestLogic_partial_index [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_SqlLogicTestHighVModuleNightlyBazel/6079428?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_SqlLogicTestHighVModuleNightlyBazel/6079428?buildTab=artifacts#/) on master @ [0dd438d3dc0b42543890455945a7a6b42811def1](https://github.com/cockroachdb/cockroach/commits/0dd438d3dc0b42543890455945a7a6b42811def1):

```
=== RUN   TestLogic_partial_index/enum
[06:13:41] CREATE TYPE enum_type AS ENUM ('foo', 'bar', 'baz');
CREATE TABLE enum_table (
    a INT PRIMARY KEY,
    b enum_type,
    INDEX i (a) WHERE b IN ('foo', 'bar')
);;
[06:13:41] rewrote:
CREATE TYPE enum_type AS ENUM ('foo', 'bar', 'baz');
CREATE TABLE enum_table (a INT8 PRIMARY KEY, b enum_type, INDEX i (a) WHERE b IN ('foo', 'bar'), FAMILY (a), FAMILY (b));


[06:13:41] INSERT INTO enum_table VALUES
    (1, 'foo'),
    (2, 'bar'),
    (3, 'baz');
[06:13:41] SELECT * FROM enum_table@i WHERE b IN ('foo', 'bar');
```
<details><summary>Help</summary>
<p>

See also: [How To Investigate a Go Test Failure \(internal\)](https://cockroachlabs.atlassian.net/l/c/HgfXfJgM)
</p>
</details>
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*TestLogic_partial_index.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)
</sub>

Jira issue: CRDB-18558

### PR DESCRIPTION
**Pull request by yuzefovich**
**flowinfra: fix type hydration for row-based inbound streams**

This commit fixes the usage of unhydrated types in the inbound streams
of the row-based flows which could only occur with high verbosity on
`inbound` file. This is achieved by no longer propagating the unhydrated
types through the wire as part of the first `ProducerMessage` and,
instead, using the types that are hydrated when setting up the input
synchronizers. As a result, `ProducerMessage` is changed slightly which
required the bump to the DistSQL version.

Fixes: #86079.

Release justification: bug fix.

Release note: None

**sql: hydrate types in some edge cases**

This commit fixes a couple of bugs in the edge cases where we forgot to
hydrate the types that could be received over the wire. These spots are:
- when setting up a values operator in the vectorized engine (this case
is correctly handled in the row-by-row engine)
- when using the fixed values of the zigzag joiner.

Additionally, this commit removes some of the allocations in order to
reuse the same type resolver in the vectorized flow setup.

Release justification: bug fix.

Release note: None

### CODE REVIEW

File: pkg/sql/execinfra/utils.go [hunk 1]
```diff
@@ -32,3 +36,15 @@ func DecodeDatum(datumAlloc *tree.DatumAlloc, typ *types.T, data []byte) (tree.D
 	}
 	return datum, nil
 }
+
+// HydrateTypesInDatumInfo hydrates all user-defined types in the provided
+// DatumInfo slice.
+func HydrateTypesInDatumInfo(ctx context.Context, f *FlowCtx, info []execinfrapb.DatumInfo) error {
+	resolver := f.NewTypeResolver(f.Txn)
+	for i := range info {
```
Comment (ajwerner) [inline pkg/sql/execinfra/utils.go:44]: nit: lazily construct this thing so you don't have to construct it if there are no UDTs? Also, it feels like this thing should just be a field in the `FlowCtx` given it just has two members which are both members of the `FlowCtx`, no?

**Review by ajwerner — COMMENTED** [review]
Nice!

**Review by yuzefovich — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/86275)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner)

___
*[`pkg/sql/execinfra/utils.go` line 44 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/86275#-N9dVoOUynkksN_BhJL6-r3-44:-N9da5XiDnKF5JGBtWUS:b-7d3umd) ([raw file](https://github.com/cockroachdb/cockroach/blob/8147ea13f1f07a236073e1b9b1bc2222d3bf7bee/pkg/sql/execinfra/utils.go#L44)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

nit: lazily construct this thing so you don't have to construct it if there are no UDTs? Also, it feels like this thing should just be a field in the `FlowCtx` given it just has two members which are both members of the `FlowCtx`, no?
</blockquote></details>

I refactored this code a bit. There are some callers of `FlowCtx.NewTypeResolver` which pass in a different txn, so I don't think we can completely hide that constructor.

**Review by ajwerner — APPROVED** [review]
:lgtm:

> Reviewed 5 of 5 files at r1, 9 of 10 files at r2, 5 of 5 files at r4, 12 of 12 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/86275#-:-N9dduUM73wq3RqWCXSf:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @yuzefovich)

___
*[`pkg/sql/flowinfra/stream_encoder.go` line 46 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/86275#-N9ddUd28LRk72UsnfAC:-N9ddUd28LRk72UsnfAD:bwrzhm) ([raw file](https://github.com/cockroachdb/cockroach/blob/66377d8886c7278d63734b0a5b8ee9dbbc794603/pkg/sql/flowinfra/stream_encoder.go#L46)):*
> ```Go
> 	types []*types.T
> 	// encodings is fully initialized when the first row is received.
> 	encodings            []descpb.DatumEncoding
> ```

For another PR: this enum should probably move to `execinfrapb`. I think it's only in `descpb` for legacy reasons.

**Review by yuzefovich — COMMENTED** [review]
TFTR!

bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/86275#-:-N9dr_M60-4-iSx8yJ3K:b-oduykh)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @ajwerner)

___
*[`pkg/sql/flowinfra/stream_encoder.go` line 46 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/86275#-N9ddUd28LRk72UsnfAC:-N9dratv0E0sEm1WFRw0:b-mshnym) ([raw file](https://github.com/cockroachdb/cockroach/blob/66377d8886c7278d63734b0a5b8ee9dbbc794603/pkg/sql/flowinfra/stream_encoder.go#L46)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

For another PR: this enum should probably move to `execinfrapb`. I think it's only in `descpb` for legacy reasons.
</blockquote></details>

Left a TODO for this.
