### PR TITLE
persistedsqlstats: unskip TestSQLStatsCompactor

### LINKED ISSUE #120761: pkg/sql/sqlstats/persistedsqlstats/persistedsqlstats_test: TestSQLStatsCompactor failed
pkg/sql/sqlstats/persistedsqlstats/persistedsqlstats_test.TestSQLStatsCompactor [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Ci_TestsAwsLinuxArm64_UnitTests/14474849?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Ci_TestsAwsLinuxArm64_UnitTests/14474849?buildTab=artifacts#/) on master @ [0e6deab01e116667459ba4132a3e6d7c5cd5cbe5](https://github.com/cockroachdb/cockroach/commits/0e6deab01e116667459ba4132a3e6d7c5cd5cbe5):

```
=== RUN   TestSQLStatsCompactor
    test_log_scope.go:170: test logs captured to: /artifacts/tmp/_tmp/da69a73e19420a8109697ab7be6f5bb3/logTestSQLStatsCompactor109822825
    test_log_scope.go:81: use -show-logs to present logs inline
    compaction_test.go:284: -- test log scope end --
test logs left over in: /artifacts/tmp/_tmp/da69a73e19420a8109697ab7be6f5bb3/logTestSQLStatsCompactor109822825
--- FAIL: TestSQLStatsCompactor (42.08s)
=== RUN   TestSQLStatsCompactor/stmtCount=200/maxPersistedRowLimit=40/rowsDeletePerTxn=2
    test_server_shim.go:157: automatically injected a shared process virtual cluster under test; see comment at top of test_server_shim.go for details.
    compaction_test.go:253: expected 32 number of wide scans issued, but 33 number of wide scan issued
        details: [wide scan in Scan [/Tenant/10/Table/42/10/0,/Tenant/10/Table/42/10/1), [txn: a4b0fb2c], [max_span_request_keys: 0], [target_bytes: 10485760] wide scan in Scan [/Tenant/10/Table/42/10/0,/Tenant/10/Table/42/10/0/2024-03-20T15:59:59.999999001Z), [txn: 0fb78906], [can-forward-ts], [max_span_request_keys: 2], [target_bytes: 10485760] wide scan in Scan [/Tenant/10/Table/42/10/1,/Tenant/10/Table/42/10/2), [txn: d088e54e], [max_span_request_keys: 0], [target_bytes: 10485760] wide scan in Scan [/Tenant/10/Table/42/10/1,/Tenant/10/Table/42/10/1/2024-03-20T15:59:59.999999001Z), [txn: 4d84ec78], [can-forward-ts], [max_span_request_keys: 2], [target_bytes: 10485760] wide scan in Scan [/Tenant/10/Table/42/10/2,/Tenant/10/Table/42/10/3), [txn: 069dd345], [max_span_request_keys: 0], [target_bytes: 10485760] wide scan in Scan [/Tenant/10/Table/42/10/2,/Tenant/10/Table/42/10/2/2024-03-20T15:59:59.999999001Z), [txn: dd3422ef], [can-forward-ts], [max_span_request_keys: 2], [target_bytes: 10485760] wide scan in Scan [/Tenant/10/Table/42/10/3,/Tenant/10/Table/42/10/4), [txn: ffbbb0f2], [max_span_request_keys: 0], [target_bytes: 10485760] wide scan in Scan [/Tenant/10/Table/42/10/3,/Tenant/10/Table/42/10/3/2024-03-20T15:59:59.999999001Z), [txn: a55310c0], [can-forward-ts], [max_span_request_keys: 2], [target_bytes: 10485760] wide scan in Scan [/Tenant/10/Table/42/10/4,/Tenant/10/Table/42/10/5), [txn: d60f9a07], [max_span_request_keys: 0], [target_bytes: 10485760] wide scan in Scan [/Tenant/10/Table/42/10/4,/Tenant/10/Table/42/10/4/2024-03-20T15:59:59.999999001Z), [txn: 82463806], [can-forward-ts], [max_span_request_keys: 2], [target_bytes: 10485760] wide scan in Scan [/Tenant/10/Table/42/10/5,/Tenant/10/Table/42/10/6), [txn: 82d36fee], [max_span_request_keys: 0], [target_bytes: 10485760] wide scan in Scan [/Tenant/10/Table/42/10/5,/Tenant/10/Table/42/10/5/2024-03-20T15:59:59.999999001Z), [txn: 30b9ae3c], [can-forward-ts], [max_span_request_keys: 2], [target_bytes: 10485760] wide scan in Scan [/Tenant/10/Table/42/10/6,/Tenant/10/Table/42/10/7), [txn: 362aaa5d], [max_span_request_keys: 0], [target_bytes: 10485760] wide scan in Scan [/Tenant/10/Table/42/10/6,/Tenant/10/Table/42/10/6/2024-03-20T15:59:59.999999001Z), [txn: 362bd2cc], [can-forward-ts], [max_span_request_keys: 2], [target_bytes: 10485760] wide scan in Scan [/Tenant/10/Table/42/10/7,/Tenant/10/Table/42/10/8), [txn: ce143013], [max_span_request_keys: 0], [target_bytes: 10485760] wide scan in Scan [/Tenant/10/Table/42/10/7,/Tenant/10/Table/42/10/7/2024-03-20T15:59:59.999999001Z), [txn: 3dbd5856], [can-forward-ts], [max_span_request_keys: 2], [target_bytes: 10485760] wide scan in Scan [/Tenant/10/Table/43/9/0,/Tenant/10/Table/43/9/1), [txn: 484530e5], [max_span_request_keys: 0], [target_bytes: 10485760] wide scan in Scan [/Tenant/10/Table/43/9/0,/Tenant/10/Table/43/9/0/2024-03-20T15:59:59.999999001Z), [txn: 2452058c], [can-forward-ts], [max_span_request_keys: 2], [target_bytes: 10485760] wide scan in Scan [/Tenant/10/Table/43/9/1,/Tenant/10/Table/43/9/2), [txn: bdb06807], [max_span_request_keys: 0], [target_bytes: 10485760] wide scan in Scan [/Tenant/10/Table/43/9/1,/Tenant/10/Table/43/9/1/2024-03-20T15:59:59.999999001Z), [txn: 17deaeb9], [can-forward-ts], [max_span_request_keys: 2], [target_bytes: 10485760] wide scan in Scan [/Tenant/10/Table/43/9/1,/Tenant/10/Table/43/9/1/2024-03-20T15:59:59.999999001Z), [txn: 17deaeb9], [can-forward-ts], [max_span_request_keys: 2], [target_bytes: 10485760] wide scan in Scan [/Tenant/10/Table/43/9/2,/Tenant/10/Table/43/9/3), [txn: 5c05276f], [max_span_request_keys: 0], [target_bytes: 10485760] wide scan in Scan [/Tenant/10/Table/43/9/2,/Tenant/10/Table/43/9/2/2024-03-20T15:59:59.999999001Z), [txn: 69d2b6d3], [can-forward-ts], [max_span_request_keys: 2], [target_bytes: 10485760] wide scan in Scan [/Tenant/10/Table/43/9/3,/Tenant/10/Table/43/9/4), [txn: bb06791c], [max_span_request_keys: 0], [target_bytes: 10485760] wide scan in Scan [/Tenant/10/Table/43/9/3,/Tenant/10/Table/43/9/3/2024-03-20T15:59:59.999999001Z), [txn: 04189006], [can-forward-ts], [max_span_request_keys: 2], [target_bytes: 10485760] wide scan in Scan [/Tenant/10/Table/43/9/4,/Tenant/10/Table/43/9/5), [txn: 05e1b923], [max_span_request_keys: 0], [target_bytes: 10485760] wide scan in Scan [/Tenant/10/Table/43/9/4,/Tenant/10/Table/43/9/4/2024-03-20T15:59:59.999999001Z), [txn: 5e53d256], [can-forward-ts], [max_span_request_keys: 2], [target_bytes: 10485760] wide scan in Scan [/Tenant/10/Table/43/9/5,/Tenant/10/Table/43/9/6), [txn: bcd2e090], [max_span_request_keys: 0], [target_bytes: 10485760] wide scan in Scan [/Tenant/10/Table/43/9/5,/Tenant/10/Table/43/9/5/2024-03-20T15:59:59.999999001Z), [txn: d97df920], [can-forward-ts], [max_span_request_keys: 2], [target_bytes: 10485760] wide scan in Scan [/Tenant/10/Table/43/9/6,/Tenant/10/Table/43/9/7), [txn: 147904c6], [max_span_request_keys: 0], [target_bytes: 10485760] wide scan in Scan [/Tenant/10/Table/43/9/6,/Tenant/10/Table/43/9/6/2024-03-20T15:59:59.999999001Z), [txn: f2c5af11], [can-forward-ts], [max_span_request_keys: 2], [target_bytes: 10485760] wide scan in Scan [/Tenant/10/Table/43/9/7,/Tenant/10/Table/43/9/8), [txn: 8650fe9d], [max_span_request_keys: 0], [target_bytes: 10485760] wide scan in Scan [/Tenant/10/Table/43/9/7,/Tenant/10/Table/43/9/7/2024-03-20T15:59:59.999999001Z), [txn: 0106446b], [can-forward-ts], [max_span_request_keys: 2], [target_bytes: 10485760]]
    --- FAIL: TestSQLStatsCompactor/stmtCount=200/maxPersistedRowLimit=40/rowsDeletePerTxn=2 (6.82s)
```
<details><summary>Help</summary>
<p>

See also: [How To Investigate a Go Test Failure \(internal\)](https://cockroachlabs.atlassian.net/l/c/HgfXfJgM)
</p>
</details>
/cc @cockroachdb/obs-inf-prs
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*TestSQLStatsCompactor.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/bazci/githubpost/issues)
</sub>

### PR DESCRIPTION
**Pull request by xinhaoz**
This commit unskips TestSQLStatsCompactor. Previously
this test was flaky because it compares the number of
actual KV scans on the sql stats tables with the number
of times a sql scan was issued via the compaction job,
tracked via a testing knob. This counting did not
account for potential txn retries leading to more KV
scans than expected in some test runs.

This commit deflakes the test by ensuring a txn is only
counted once. We also now prepopulate the  sql stats tables
directly instead of flushing collected data, since the collected
data from a test cluster can include internal statements which
can change the number of expected scans across test runs.

Epic: none
Fixes: https://github.com/cockroachdb/cockroach/issues/120761
Release note: None

### CODE REVIEW

File: pkg/sql/sqlstats/persistedsqlstats/compaction_test.go [hunk 1]
```diff
@@ -380,41 +372,45 @@ ORDER BY aggregated_ts`
...
 
 // Tables 42 and 43 and are the IDs of the statement and transactions
 // tables respectively. See `StatementStatisticsTableID` and
 // `TransactionStatisticsTableID`.
 var kvReqWideScanStartKeyPattern = regexp.MustCompile(`(/Tenant/\d+)?/Table/((42)|(43))/[0-9]{1,2}/[0-9]$`)
 
 type kvScanInterceptor struct {
-	totalWideScan   int64
+	totalWideScan   atomic.Int64
 	enabled         int32
```
Comment (dhartunian) [inline pkg/sql/sqlstats/persistedsqlstats/compaction_test.go:387]: curious why `totalWideScan` was converted to an atomic, but not `enabled`.

**Review by dhartunian — APPROVED** [review]
