### PR TITLE
pgdate: allow parsing of dates with year 0

### LINKED ISSUE #56554: roachtest: sqlsmith field year value is out of range
[(roachtest).sqlsmith/setup=seed/setting=no-mutations failed](https://teamcity.cockroachdb.com/viewLog.html?buildId=2433392&tab=buildLog) on [release-20.2@abeb6a501e00a23477aab67951a9b511b7ce7ee5](https://github.com/cockroachdb/cockroach/commits/abeb6a501e00a23477aab67951a9b511b7ce7ee5):

```
The test failed on branch=release-20.2, cloud=gce:
test artifacts and logs in: /home/agent/work/.go/src/github.com/cockroachdb/cockroach/artifacts/sqlsmith/setup=seed/setting=no-mutations/run_1
	sqlsmith.go:181,sqlsmith.go:211,test_runner.go:755: error: pq: internal error: '0000-12-31 00:00:00':::TIMESTAMP::TIMESTAMP: parsing as type timestamp: field year value 0 is out of range
		stmt:
		SELECT
			tab_4100._date AS col_9952,
			(
				SELECT
					('0001-01-01 00:00:00':::TIMESTAMP::TIMESTAMP - tab_4101._interval::INTERVAL)::TIMESTAMP AS col_9953
				FROM
					defaultdb.public.seed@[0] AS tab_4101
				LIMIT
					1:::INT8
			)
				AS col_9954,
			tab_4100._timestamptz AS col_9955,
			tab_4100._string AS col_9956,
			tab_4100._uuid AS col_9957,
			tab_4100._inet AS col_9958
		FROM
			defaultdb.public.seed@seed__int8__float8__date_idx AS tab_4100
		LIMIT
			34:::INT8;

```

<details><summary>More</summary><p>

Artifacts: [/sqlsmith/setup=seed/setting=no-mutations](https://teamcity.cockroachdb.com/viewLog.html?buildId=2433392&tab=artifacts#/sqlsmith/setup=seed/setting=no-mutations)

[See this test on roachdash](https://roachdash.crdb.dev/?filter=status%3Aopen+t%3A.%2Asqlsmith%2Fsetup%3Dseed%2Fsetting%3Dno-mutations.%2A&sort=title&restgroup=false&display=lastcommented+project)
<sub>powered by [pkg/cmd/internal/issues](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)</sub></p></details>

### PR DESCRIPTION
**Pull request by yuzefovich**
We support two formats for specifying the year: ISO8601 and AD/BC
notation while PG supports only the latter. Year 0000 in ISO is 1 BC in
AD/BC, year 0 in AD/BC notation is invalid. Previously we were erroring
out if year 0 is used in ISO notation which could lead to internal
errors when trying to deserialize a date with year 1 BC, and this is now
fixed by allowing year 0 to be used (we still check that it is invalid
in AD/BC notation).

Fixes: #56554.

Release note (bug fix): CockroachDB previously could encounter an
internal error when date/timestamp/timestamptz that is of year 1 BC was
sent between nodes for execution. Additionally, previously it was not
possible to specify the date/timestamp/timestamptz with year 1 BC
without using AD/BC notation. This is now fixed.

### CODE REVIEW

**Comment by yuzefovich** [comment]
I'm not sure whether this is the right approach to take. cc @otan do you have suggestions/thoughts here? It seems like we might be decrementing by 1 more than once in some cases with the current PR :/

**Comment by otan** [comment]
so looks like `0000` is the valid way of representing 1 BC in ISO8601 (https://en.wikipedia.org/wiki/ISO_8601#Years), which is what i assume the timestamp formatting is, so i'm not sure this is the correct way of dealing with this.

I think the problem is that we don't allow the parsing of the year 0000, which should represent 1 BC.

**Comment by otan** [comment]
it is worth noting we allow parsing `select '-0001-12-31 00:00:00'::TIMESTAMP;`, but postgres does not.

**Comment by yuzefovich** [comment]
Good point, thanks, RFAL.

**Review by otan — APPROVED** [review]
mind also adding a test case in parsing_test.go for `-0001-02-15` and `0000-02-15` under `dateTestData`?

**Comment by yuzefovich** [comment]
Added the tests and adjusted the error message a bit.

TFTR!

bors r+

**Comment by yuzefovich** [comment]
Actually, I should also adjust the comment.

bors r-

File: pkg/util/timeutil/pgdate/field_extract.go [hunk 1]
```diff
@@ -884,18 +884,22 @@ func (fe *fieldExtract) validate() error {
...
+		// the latter.
+
 		// Update for BC dates.
-		if era, ok := fe.Get(fieldEra); ok && era < 0 {
-			// No year 0
+		if era, ok := fe.Get(fieldEra); ok {
+			// AD/BC notation supports only positive years.
 			if year <= 0 {
-				return inputErrorf("no year 0 in AD/BC notation")
+				return inputErrorf("only positive years in AD/BC notation")
```
Comment (otan) [inline pkg/util/timeutil/pgdate/field_extract.go:896]: only positive years are permitted in AD/BC notation, maybe?

**Comment by yuzefovich** [comment]
sure

bors r-

**Review by otan — APPROVED** [review]
