### PR TITLE
jobs,sql/importer: retry circuit breaker open errors

### LINKED ISSUE #81353: roachtest: import/nodeShutdown/worker failed
roachtest.import/nodeShutdown/worker [failed](https://teamcity.cockroachdb.com/viewLog.html?buildId=5176244&tab=buildLog) with [artifacts](https://teamcity.cockroachdb.com/viewLog.html?buildId=5176244&tab=artifacts#/import/nodeShutdown/worker) on release-22.1 @ [f6578028f0b029cbb623bd278c57c6bef85c4835](https://github.com/cockroachdb/cockroach/commits/f6578028f0b029cbb623bd278c57c6bef85c4835):

```
The test failed on branch=release-22.1, cloud=gce:
test artifacts and logs in: /artifacts/import/nodeShutdown/worker/run_1
	monitor.go:127,jobs.go:154,import.go:95,test_runner.go:875: monitor failure: monitor task failed: unexpectedly found job 762493548270747650 in state failed
		(1) attached stack trace
		  -- stack trace:
		  | main.(*monitorImpl).WaitE
		  | 	main/pkg/cmd/roachtest/monitor.go:115
		  | main.(*monitorImpl).Wait
		  | 	main/pkg/cmd/roachtest/monitor.go:123
		  | github.com/cockroachdb/cockroach/pkg/cmd/roachtest/tests.jobSurvivesNodeShutdown
		  | 	github.com/cockroachdb/cockroach/pkg/cmd/roachtest/tests/jobs.go:154
		  | github.com/cockroachdb/cockroach/pkg/cmd/roachtest/tests.registerImportNodeShutdown.func2
		  | 	github.com/cockroachdb/cockroach/pkg/cmd/roachtest/tests/import.go:95
		  | main.(*testRunner).runTest.func2
		  | 	main/pkg/cmd/roachtest/test_runner.go:875
		Wraps: (2) monitor failure
		Wraps: (3) attached stack trace
		  -- stack trace:
		  | main.(*monitorImpl).wait.func2
		  | 	main/pkg/cmd/roachtest/monitor.go:171
		Wraps: (4) monitor task failed
		Wraps: (5) attached stack trace
		  -- stack trace:
		  | github.com/cockroachdb/cockroach/pkg/cmd/roachtest/tests.jobSurvivesNodeShutdown.func1
		  | 	github.com/cockroachdb/cockroach/pkg/cmd/roachtest/tests/jobs.go:95
		  | main.(*monitorImpl).Go.func1
		  | 	main/pkg/cmd/roachtest/monitor.go:105
		  | golang.org/x/sync/errgroup.(*Group).Go.func1
		  | 	golang.org/x/sync/errgroup/external/org_golang_x_sync/errgroup/errgroup.go:57
		  | runtime.goexit
		  | 	GOROOT/src/runtime/asm_amd64.s:1581
		Wraps: (6) unexpectedly found job 762493548270747650 in state failed
		Error types: (1) *withstack.withStack (2) *errutil.withPrefix (3) *withstack.withStack (4) *errutil.withPrefix (5) *withstack.withStack (6) *errutil.leafError
```
<details><summary>Help</summary>
<p>

See: [roachtest README](https://github.com/cockroachdb/cockroach/blob/master/pkg/cmd/roachtest/README.md)

See: [How To Investigate \(internal\)](https://cockroachlabs.atlassian.net/l/c/SSSBr8c7)

</p>
</details>
/cc @cockroachdb/bulk-io
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*import/nodeShutdown/worker.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)
</sub>

Jira issue: CRDB-15229

### LINKED ISSUE #85111: roachtest: import/nodeShutdown/coordinator failed
roachtest.import/nodeShutdown/coordinator [failed](https://teamcity.cockroachdb.com/viewLog.html?buildId=5875969&tab=buildLog) with [artifacts](https://teamcity.cockroachdb.com/viewLog.html?buildId=5875969&tab=artifacts#/import/nodeShutdown/coordinator) on release-22.1 @ [672da119afa91df56bf76f1081fdada2b1ef9175](https://github.com/cockroachdb/cockroach/commits/672da119afa91df56bf76f1081fdada2b1ef9175):

```
The test failed on branch=release-22.1, cloud=gce:
test artifacts and logs in: /artifacts/import/nodeShutdown/coordinator/run_1
	monitor.go:127,jobs.go:154,import.go:109,test_runner.go:883: monitor failure: monitor task failed: unexpectedly found job 782594996865433602 in state failed
		(1) attached stack trace
		  -- stack trace:
		  | main.(*monitorImpl).WaitE
		  | 	main/pkg/cmd/roachtest/monitor.go:115
		  | main.(*monitorImpl).Wait
		  | 	main/pkg/cmd/roachtest/monitor.go:123
		  | github.com/cockroachdb/cockroach/pkg/cmd/roachtest/tests.jobSurvivesNodeShutdown
		  | 	github.com/cockroachdb/cockroach/pkg/cmd/roachtest/tests/jobs.go:154
		  | github.com/cockroachdb/cockroach/pkg/cmd/roachtest/tests.registerImportNodeShutdown.func3
		  | 	github.com/cockroachdb/cockroach/pkg/cmd/roachtest/tests/import.go:109
		  | main.(*testRunner).runTest.func2
		  | 	main/pkg/cmd/roachtest/test_runner.go:883
		Wraps: (2) monitor failure
		Wraps: (3) attached stack trace
		  -- stack trace:
		  | main.(*monitorImpl).wait.func2
		  | 	main/pkg/cmd/roachtest/monitor.go:171
		Wraps: (4) monitor task failed
		Wraps: (5) attached stack trace
		  -- stack trace:
		  | github.com/cockroachdb/cockroach/pkg/cmd/roachtest/tests.jobSurvivesNodeShutdown.func1
		  | 	github.com/cockroachdb/cockroach/pkg/cmd/roachtest/tests/jobs.go:95
		  | main.(*monitorImpl).Go.func1
		  | 	main/pkg/cmd/roachtest/monitor.go:105
		  | golang.org/x/sync/errgroup.(*Group).Go.func1
		  | 	golang.org/x/sync/errgroup/external/org_golang_x_sync/errgroup/errgroup.go:57
		  | runtime.goexit
		  | 	GOROOT/src/runtime/asm_amd64.s:1581
		Wraps: (6) unexpectedly found job 782594996865433602 in state failed
		Error types: (1) *withstack.withStack (2) *errutil.withPrefix (3) *withstack.withStack (4) *errutil.withPrefix (5) *withstack.withStack (6) *errutil.leafError
```
<details><summary>Help</summary>
<p>

See: [roachtest README](https://github.com/cockroachdb/cockroach/blob/master/pkg/cmd/roachtest/README.md)

See: [How To Investigate \(internal\)](https://cockroachlabs.atlassian.net/l/c/SSSBr8c7)

</p>
</details>
/cc @cockroachdb/bulk-io
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*import/nodeShutdown/coordinator.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)
</sub>

Jira issue: CRDB-18045

### LINKED ISSUE #89159: roachtest: import/nodeShutdown/coordinator failed [transient error should have caused a retry]
roachtest.import/nodeShutdown/coordinator [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/6741071?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/6741071?buildTab=artifacts#/import/nodeShutdown/coordinator) on master @ [ff6961ef1741766b5cbe0b64ebf754e82343eb00](https://github.com/cockroachdb/cockroach/commits/ff6961ef1741766b5cbe0b64ebf754e82343eb00):

```
test artifacts and logs in: /artifacts/import/nodeShutdown/coordinator/run_1
	monitor.go:127,jobs.go:154,import.go:109,test_runner.go:928: monitor failure: monitor task failed: unexpectedly found job 801564088527749122 in state failed
		(1) attached stack trace
		  -- stack trace:
		  | main.(*monitorImpl).WaitE
		  | 	main/pkg/cmd/roachtest/monitor.go:115
		  | main.(*monitorImpl).Wait
		  | 	main/pkg/cmd/roachtest/monitor.go:123
		  | github.com/cockroachdb/cockroach/pkg/cmd/roachtest/tests.jobSurvivesNodeShutdown
		  | 	github.com/cockroachdb/cockroach/pkg/cmd/roachtest/tests/jobs.go:154
		  | github.com/cockroachdb/cockroach/pkg/cmd/roachtest/tests.registerImportNodeShutdown.func3
		  | 	github.com/cockroachdb/cockroach/pkg/cmd/roachtest/tests/import.go:109
		  | main.(*testRunner).runTest.func2
		  | 	main/pkg/cmd/roachtest/test_runner.go:928
		Wraps: (2) monitor failure
		Wraps: (3) attached stack trace
		  -- stack trace:
		  | main.(*monitorImpl).wait.func2
		  | 	main/pkg/cmd/roachtest/monitor.go:171
		Wraps: (4) monitor task failed
		Wraps: (5) attached stack trace
		  -- stack trace:
		  | github.com/cockroachdb/cockroach/pkg/cmd/roachtest/tests.jobSurvivesNodeShutdown.func1
		  | 	github.com/cockroachdb/cockroach/pkg/cmd/roachtest/tests/jobs.go:95
		  | main.(*monitorImpl).Go.func1
		  | 	main/pkg/cmd/roachtest/monitor.go:105
		  | golang.org/x/sync/errgroup.(*Group).Go.func1
		  | 	golang.org/x/sync/errgroup/external/org_golang_x_sync/errgroup/errgroup.go:74
		  | runtime.goexit
		  | 	GOROOT/src/runtime/asm_amd64.s:1594
		Wraps: (6) unexpectedly found job 801564088527749122 in state failed
		Error types: (1) *withstack.withStack (2) *errutil.withPrefix (3) *withstack.withStack (4) *errutil.withPrefix (5) *withstack.withStack (6) *errutil.leafError
```
<p>Parameters: <code>ROACHTEST_cloud=gce</code>
, <code>ROACHTEST_cpu=4</code>
, <code>ROACHTEST_encrypted=false</code>
, <code>ROACHTEST_ssd=0</code>
</p>
<details><summary>Help</summary>
<p>

See: [roachtest README](https://github.com/cockroachdb/cockroach/blob/master/pkg/cmd/roachtest/README.md)

See: [How To Investigate \(internal\)](https://cockroachlabs.atlassian.net/l/c/SSSBr8c7)

</p>
</details>
<details><summary>Same failure on other branches</summary>
<p>

- #85111 roachtest: import/nodeShutdown/coordinator failed [C-test-failure O-roachtest O-robot T-disaster-recovery branch-release-22.1]
</p>
</details>
/cc @cockroachdb/disaster-recovery
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*import/nodeShutdown/coordinator.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)
</sub>

Jira issue: CRDB-20141

### PR DESCRIPTION
**Pull request by stevendanna**
We would like to retry circuit breaker open errors. In fact, jobs.IsPermanentBulkJobError already looks like it would return false for breaker open errors.

But, there are actually two circuit breaker packages we use:

    github.com/cockroachdb/circuitbreaker
    github.com/cockroachdb/cockroach/pkg/util/circuit

Both define ErrBreakerOpen. IsPermanentBulkJobError would only catch errors from one of these packages. Now, we test for both.

As a result, ErrBreakerOpen errors emerging from the nodedialer will now be retried.

Fixes #89159
Fixes #85111
Fixes #81353

I may be being a bit optimistic that this will fully fixe those failures. Success of the job still requires that the retry of the job is successful.

Release note (bug fix): Fix bug that resulted in some retriable errors not being retried during IMPORT.

### CODE REVIEW

File: pkg/jobs/joberror/errors.go [hunk 1]
```diff
@@ -41,8 +42,11 @@ func IsDistSQLRetryableError(err error) bool {
 }
 
 // isBreakerOpenError returns true if err is a circuit.ErrBreakerOpen.
+//
+// NB: Two packages have ErrBreakerOpen error types.  The cicruitbreaker package
+// is used by the nodedialer. The circuit package is used by kvserver.
 func isBreakerOpenError(err error) bool {
-	return errors.Is(err, circuit.ErrBreakerOpen)
+	return errors.Is(err, circuit.ErrBreakerOpen) || errors.Is(err, circuitbreaker.ErrBreakerOpen)
```
Comment (stevendanna) [inline pkg/jobs/joberror/errors.go:49]: This is the functional change.  The rest is test related.

**Review by dt — APPROVED** [review]

**Comment by stevendanna** [comment]
bors r=dt

**Comment by stevendanna** [comment]
blathers backport 22.2.0
