### PR TITLE
sql, geo: check infinite coordinates in st_minimumboundingcircle and st_linemerge

### LINKED ISSUE #74445: sql: spatial function st_linemerge causes segmentation fault
roachtest.sqlsmith/setup=rand-tables/setting=no-mutations [failed](https://teamcity.cockroachdb.com/viewLog.html?buildId=4042066&tab=buildLog) with [artifacts](https://teamcity.cockroachdb.com/viewLog.html?buildId=4042066&tab=artifacts#/sqlsmith/setup=rand-tables/setting=no-mutations) on release-21.2 @ [fb88f951323864fafd104e132cbf1f2f22f2e3ac](https://github.com/cockroachdb/cockroach/commits/fb88f951323864fafd104e132cbf1f2f22f2e3ac):

```
											1:::INT8
									)
								)
						)
							AS tab_120766 (col_258592)
				)
		SELECT
			cte_ref_14107.col_258590 AS col_258593,
			tab_120767.col1_4 AS col_258594,
			e'~-C%@\fcO':::STRING:::NAME AS col_258595,
			0:::OID AS col_258596,
			tab_120767.col1_1 AS col_258597,
			tab_120767.col1_4 AS col_258598,
			tab_120767.crdb_internal_mvcc_timestamp AS col_258599,
			NULL AS col_258600
		FROM
			with_49211 AS cte_ref_14107, defaultdb.public.table1@primary AS tab_120767
		WHERE
			true
		LIMIT
			33:::INT8;

	cluster.go:1296,context.go:89,cluster.go:1284,test_runner.go:866: dead node detection: /home/agent/work/.go/src/github.com/cockroachdb/cockroach/bin/roachprod monitor teamcity-4042066-1641366923-12-n4cpu4 --oneshot --ignore-empty-nodes: exit status 1 3: 13701
		2: 13122
		4: 12438
		1: dead (exit status 134)
		Error: UNCLASSIFIED_PROBLEM: 1: dead (exit status 134)
		(1) UNCLASSIFIED_PROBLEM
		Wraps: (2) attached stack trace
		  -- stack trace:
		  | github.com/cockroachdb/cockroach/pkg/roachprod.Monitor
		  | 	/home/agent/work/.go/src/github.com/cockroachdb/cockroach/pkg/roachprod/roachprod.go:596
		  | main.glob..func14
		  | 	/home/agent/work/.go/src/github.com/cockroachdb/cockroach/pkg/cmd/roachprod/main.go:569
		  | main.wrap.func1
		  | 	/home/agent/work/.go/src/github.com/cockroachdb/cockroach/pkg/cmd/roachprod/main.go:123
		  | github.com/spf13/cobra.(*Command).execute
		  | 	/home/agent/work/.go/src/github.com/cockroachdb/cockroach/vendor/github.com/spf13/cobra/command.go:856
		  | github.com/spf13/cobra.(*Command).ExecuteC
		  | 	/home/agent/work/.go/src/github.com/cockroachdb/cockroach/vendor/github.com/spf13/cobra/command.go:960
		  | github.com/spf13/cobra.(*Command).Execute
		  | 	/home/agent/work/.go/src/github.com/cockroachdb/cockroach/vendor/github.com/spf13/cobra/command.go:897
		  | main.main
		  | 	/home/agent/work/.go/src/github.com/cockroachdb/cockroach/pkg/cmd/roachprod/main.go:1170
		  | runtime.main
		  | 	/usr/local/go/src/runtime/proc.go:255
		  | runtime.goexit
		  | 	/usr/local/go/src/runtime/asm_amd64.s:1581
		Wraps: (3) 1: dead (exit status 134)
		Error types: (1) errors.Unclassified (2) *withstack.withStack (3) *errutil.leafError
```
<details><summary>Reproduce</summary>
<p>

See: [roachtest README](https://github.com/cockroachdb/cockroach/blob/master/pkg/cmd/roachtest/README.md)

</p>
</details>
/cc @cockroachdb/sql-queries
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*sqlsmith/setup=rand-tables/setting=no-mutations.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)
</sub>

Jira issue: CRDB-12083

### LINKED ISSUE #75305: spatial: st_minimumboundingcircle causes seg fault
roachtest.sqlsmith/setup=empty/setting=no-mutations [failed](https://teamcity.cockroachdb.com/viewLog.html?buildId=4181512&tab=buildLog) with [artifacts](https://teamcity.cockroachdb.com/viewLog.html?buildId=4181512&tab=artifacts#/sqlsmith/setup=empty/setting=no-mutations) on master @ [dc07599dc9db1acd5afa3a6537297815f25c1fca](https://github.com/cockroachdb/cockroach/commits/dc07599dc9db1acd5afa3a6537297815f25c1fca):

```
The test failed on branch=master, cloud=gce:
test artifacts and logs in: /home/agent/work/.go/src/github.com/cockroachdb/cockroach/artifacts/sqlsmith/setup=empty/setting=no-mutations/run_1
	sqlsmith.go:277,sqlsmith.go:297,test_runner.go:780: ping node 1: dial tcp 35.196.6.92:26257: connect: connection refused
		previous sql:
		WITH
			with_68124 (col_378139)
				AS (
					SELECT
						*
					FROM
						(VALUES ((-107002942):::INT8), (1086357167:::INT8), (532063269:::INT8)) AS tab_219729 (col_378139)
					UNION ALL
						SELECT
							*
						FROM
							(
								VALUES
									((-32768):::INT8),
									((-262638999):::INT8),
									((-662209634):::INT8),
									(1366735309:::INT8),
									(1084143704:::INT8)
							)
								AS tab_219730 (col_378140)
				),
			with_68125 (col_378141)
				AS (
					SELECT
						*
					FROM
						(VALUES (NULL), ('07:28:22.363085':::TIME), ('13:30:13.004937':::TIME)) AS tab_219731 (col_378141)
				)
		SELECT
			e'\x7f':::STRING AS col_378150
		FROM
			(VALUES ('B':::STRING), (NULL), ('L':::STRING), ('*':::STRING), ('a':::STRING)) AS tab_219732 (col_378142)
		WHERE
			(true OR (('03:59:35.151436+03:26:00':::TIMETZ::TIMETZ NOT IN (WITH with_68126 (col_378143, col_378144) AS (SELECT * FROM (VALUES ('010700000000000000':::GEOMETRY, '24:00:00':::TIME), ('01050000C000000000':::GEOMETRY, '07:03:10.645568':::TIME), (st_minimumboundingcircle(st_makepoint(((-0.27013513189303495):::FLOAT8::FLOAT8 // 5e-324:::FLOAT8::FLOAT8)::FLOAT8::FLOAT8, (-0.4968052087960828):::FLOAT8::FLOAT8)::GEOMETRY::GEOMETRY)::GEOMETRY, '20:12:24.168025':::TIME)) AS tab_219733 (col_378143, col_378144)), with_68127 (col_378145) AS (SELECT * FROM (VALUES ('1971-07-10':::DATE), ('1986-11-06':::DATE), ('1970-01-01':::DATE), ('1981-04-26':::DATE), ('1976-02-11':::DATE), ('1983-08-12':::DATE)) AS tab_219734 (col_378145) EXCEPT SELECT * FROM (VALUES (localtimestamp(NULL::INT8):::DATE::DATE), ('1975-07-02':::DATE), ('1984-06-29':::DATE)) AS tab_219735 (col_378146) INTERSECT SELECT * FROM (VALUES ('1991-04-07':::DATE), ('1984-07-21':::DATE), ('1988-09-18':::DATE), (NULL), ('1979-03-03':::DATE), ('-infinity':::DATE)) AS tab_219736 (col_378147)) SELECT '11:49:56.666867+12:55:00':::TIMETZ::TIMETZ AS col_378149 FROM (VALUES ('BOX(-0.6669196303257863 0.1401707656476619,-0.5370475799667299 0.6048998170384512)':::BOX2D), ('BOX(-0.8218846060036147 -1.4403177072400855,0.5448787862071454 -0.34082049177980256)':::BOX2D), (NULL), ('BOX(0.6587235517541048 -1.6268781316321395,0.8100310254105514 -1.1279642854480496)':::BOX2D), ('BOX(-0.8051643192704393 -1.1134324048645756,0.7120046221995976 -0.14925328983174546)':::BOX2D)) AS tab_219737 (col_378148) ORDER BY tab_219737.col_378148, tab_219737.col_378148 ASC LIMIT 56:::INT8)) AND true))
		ORDER BY
			tab_219732.col_378142
		LIMIT
			11:::INT8;
```
<details><summary>Help</summary>
<p>

See: [roachtest README](https://github.com/cockroachdb/cockroach/blob/master/pkg/cmd/roachtest/README.md)

See: [How To Investigate \(internal\)](https://cockroachlabs.atlassian.net/l/c/SSSBr8c7)

</p>
</details>
/cc @cockroachdb/sql-queries
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*sqlsmith/setup=empty/setting=no-mutations.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)
</sub>

Jira issue: CRDB-12549

### PR DESCRIPTION
**Pull request by ZhouXing19**
This commit adds a check to determine if the bounding box of a Geometry has
any infinite coordinate in st_minimumboundingcircle and st_linemerge.

Fixes https://github.com/cockroachdb/cockroach/issues/75305
Fixes https://github.com/cockroachdb/cockroach/issues/74445

Release note: None

Jira issue: CRDB-14764

### CODE REVIEW

**Review by otan — APPROVED** [review]

File: pkg/sql/sem/builtins/geo_builtins.go [hunk 1]
```diff
@@ -6468,6 +6468,9 @@ The parent_only boolean is always ignored.`,
 	"st_minimumboundingcircle": makeBuiltin(defProps(),
 		geometryOverload1(
 			func(evalContext *tree.EvalContext, g *tree.DGeometry) (tree.Datum, error) {
+				if geomfn.CheckBoundingBoxInfiniteCoordinates(g.Geometry) {
+					return nil, errors.Newf("value out of range: overflow")
```
[the remark this answers is not in the document]
Comment (ZhouXing19) [reply pkg/sql/sem/builtins/geo_builtins.go]: Done.

**Comment by rafiss** [comment]
lgtm! just wondering if you have a separate PR for LineMerge? (https://github.com/cockroachdb/cockroach/issues/74445)

**Comment by ZhouXing19** [comment]
> lgtm! just wondering if you have a separate PR for LineMerge? (#74445)

Just added same check under `st_linemerge`.
But do we want to have the same error message as in PG?

(On PostgreSQL 13.5)
```
postgres=# select st_linemerge('01020000C003000000000000000000F0FF000000000000F8FF60DB272315DEBAC13CDE36003499DEC1000000000000F0FF000000000000F8FF9CDB5D9AA401E1C1D0C80253A5F1C4C1000000000000F0FF000000000000F8FF003E39CD6CDDD2C1A6909F31D737F4C1'::geometry);
ERROR:  lwgeom_linemerge: GEOS Error: IllegalArgumentException: CGAlgorithmsDD::orientationIndex encountered NaN/Inf numbers
```

**Comment by rafiss** [comment]
I got the error: "RobustDeterminant encountered non-finite numbers"

anyway, don't think the sentence needs to match exactly

File: pkg/geo/geomfn/topology_operations.go [hunk 2]
```diff
@@ -207,3 +207,18 @@ func MinimumRotatedRectangle(g geo.Geometry) (geo.Geometry, error) {
...
+
+// CheckBoundingBoxInfiniteCoordinates checks if the bounding box of a Geometry
+// has infinite coordinate.
+func CheckBoundingBoxInfiniteCoordinates(g geo.Geometry) bool {
+	boundingBox := g.BoundingBoxRef()
+	if boundingBox == nil {
+		return false
+	}
+	for _, coord := range []float64{boundingBox.LoX, boundingBox.LoY, boundingBox.HiX, boundingBox.HiY} {
+		if math.IsInf(coord, 1) || math.IsInf(coord, -1) {
```
Comment (rafiss) [inline pkg/geo/geomfn/topology_operations.go:219]: you can just use `math.IsInf(coord, 0)` if you like

**Review by rafiss — APPROVED** [review]

File: pkg/geo/geomfn/topology_operations.go (hunk 2 above)
Comment (ZhouXing19) [reply pkg/geo/geomfn/topology_operations.go]: Done.

**Comment by ZhouXing19** [comment]
TFTR!
bors r+
