### PR TITLE
sql: improve error message for ColumnConversionGeneral

### LINKED ISSUE #47141: Incorrect/unhelpful error for TIME/TIMESTAMP precision changes
**Describe the problem**

`ALTER COLUMN ... SET DATA TYPE` returns an incorrect/unhelpful error when you try to change the precision of a `TIME`/`TIMESTAMP` column to a precision level lower than the current one.

**To Reproduce**

~~~
> CREATE TABLE time (time_id INT PRIMARY KEY, time_val TIME(4));
~~~
~~~
> SHOW COLUMNS FROM time;
~~~
~~~
  column_name | data_type | is_nullable | column_default | generation_expression |  indices  | is_hidden
--------------+-----------+-------------+----------------+-----------------------+-----------+------------
  time_id     | INT8      |    false    | NULL           |                       | {primary} |   false
  time_val    | TIME(4)   |    true     | NULL           |                       | {}        |   false
(2 rows)
~~~
~~~
> ALTER TABLE time ALTER COLUMN time_val SET DATA TYPE TIME(3);
~~~
~~~
ERROR: unimplemented: type conversion not yet implemented
SQLSTATE: 0A000
HINT: You have attempted to use a feature that is not yet implemented.
See: https://github.com/cockroachdb/cockroach/issues/9851
~~~

**Expected behavior**

This error message isn't correct, and could be a little more helpful. Not sure what the exact wording should be. The hint is also unhelpful. It should read something more specific to the statement, like "You cannot change the precision level of a column of non-default precision to a precision level lower than its current precision level."

**Environment:**
 - CockroachDB version: CockroachDB OSS v20.1.0-beta.4-491-gba8cbe5d0b (x86_64-apple-darwin19.3.0, built 2020/04/07 17:58:22, go1.13.4)
 - Server OS: macOS 10.15.3
 - Client app: cockroach demo

### PR DESCRIPTION
**Pull request by otan**
Resolves https://github.com/cockroachdb/cockroach/issues/47141

Intended for backport to 20.1. Tagging Richard as a reviewer since he's working on SET DATA TYPE :P 

----

In addition to the release note, also modified TIME precision
conversions to use "General" which is the value for which means to
"overwrite" values.

Release note (sql change): Improved the error message for ALTER COLUMN
... SET DATA TYPE ... for data type conversions that involve overwriting
existing values.

### CODE REVIEW

File: pkg/sql/alter_table.go [hunk 1]
```diff
@@ -906,6 +906,16 @@ func applyColumnMutation(
 				col.Type.SQLString(), typ.SQLString())
 		case schemachange.ColumnConversionTrivial:
 			col.Type = *typ
+		case schemachange.ColumnConversionGeneral:
+			return unimplemented.NewWithIssueDetail(
+				9851,
+				fmt.Sprintf("%s->%s", col.Type.SQLString(), typ.SQLString()),
+				fmt.Sprintf(
+					"type conversion from %s to %s requires overwriting existing values which is not yet implemented",
```
Comment (RichardJCai) [inline pkg/sql/alter_table.go:914]: I think you can use NewIssueWithDetailf instead of using fmt.Sprintf

**Review by RichardJCai — APPROVED** [review]
Looks good besides one small nit.

**Comment by otan** [comment]
bors r=RichardJCai
