### PR TITLE
backup: fix up encryption handling in compacted backups

### LINKED ISSUE #143725: backup: encrypted compacted backups break after a pause-resume flow
The encrypted backup/restore code is in terrible tech debt:
- During backup/restore planning, the `EncryptionOptions` [field contains](https://github.com/msbutler/cockroach/blob/butler-compact-encrypt/pkg/jobs/jobspb/jobs.proto#L53) the "raw" user passed password/kms, but on resume, we remove the user passed info and add a key to the EncryptionOptions instead. This replacement is done by `GetEncryptionFromBase`.This pattern goes against all our values:
   - it's bad software engineering to use the same object in completely different ways (in planning this struct holds the raw keys, and on resume, it is used to decrypt/encrypt data)
    - As the job system owners, we preach that fields in `details` should be static. At some point, we should persist the encyrption key (and all other "updated" details) in the info table instead.  
- `EncryptionInfo`, currently persisted in [job details](https://github.com/msbutler/cockroach/blob/butler-compact-encrypt/pkg/jobs/jobspb/jobs.proto#L400), should only ever get set on the first encrypted backup in the chain (hopefully the full, but i have not read closely enough yet)., because it persists the salt that each key in the chain must have. This fact only become clear by [closely reading ](https://github.com/msbutler/cockroach/blob/butler-compact-encrypt/pkg/backup/backup_job.go#L1667) the code. I have not had a chance to understand how the ALTER BACKUP stmt interacts with all of this.

Because of our convoluted encrypted backup logic, two bugs were introduced to compacted backups which cause the backup to use an incompatible key.
- On Resume after pause: `GetEncryptionFromBase` is called with an `EncryptionOptions` struct that already contains a key.
- EncryptionInfo is hydrated on resume. 

Jira issue: CRDB-49015

### PR DESCRIPTION
**Pull request by msbutler**
Fixes https://github.com/cockroachdb/cockroach/issues/143725

Release note: none

### CODE REVIEW

File: pkg/backup/compaction_job.go [hunk 1]
```diff
@@ -492,22 +492,12 @@ func updateCompactionBackupDetails(
...
 	initialDetails jobspb.BackupDetails,
 	resolvedDest backupdest.ResolvedDestination,
-	encryption *jobspb.BackupEncryptionOptions,
+	baseEncryptOpts *jobspb.BackupEncryptionOptions,
 	kmsEnv cloud.KMSEnv,
 ) (jobspb.BackupDetails, error) {
 	if len(compactionChain.chainToCompact) == 0 {
 		return jobspb.BackupDetails{}, errors.New("no backup manifests to compact")
 	}
-	var encryptionInfo *jobspb.EncryptionInfo
```
Comment (kev-cao) [inline pkg/backup/compaction_job.go:501]: I think we can also update `MakeNewEncryptionOptions` to use `encryption.Unencrypted()` too.

File: pkg/jobs/jobspb/jobs.go [hunk 2]
```diff
@@ -138,3 +138,17 @@ func (m *ChangefeedProgress_Checkpoint) IsEmpty() bool {
...
+func (b *BackupEncryptionOptions) HasKey() bool {
+
+	if b.KMSInfo != nil {
+		return len(b.KMSInfo.EncryptedDataKey) > 0
+	}
+	// Used for encryption passphrases.
+	return len(b.Key) > 0
+}
+
+func (b *BackupEncryptionOptions) Unencrypted() bool {
```
Comment (kev-cao) [inline pkg/jobs/jobspb/jobs.go:151]: nit: `IsEncrypted`? I think that's the idiomatic naming convention for predicates.

File: pkg/jobs/jobspb/jobs.proto [hunk 3]
```diff
@@ -396,7 +396,21 @@ message BackupDetails {
...
   map<string, string> uris_by_locality_kv = 5 [(gogoproto.customname) = "URIsByLocalityKV"];
   bytes deprecated_backup_manifest = 4;
+
+  // EncryptionOptions contains user inputed data initially, but once
+  // ResolveDest is called at the beginning of resumption, this field will
+  // contain the encryption key. 
+  //
+  // TODO(msbutler): use job info to persist hydrated encryption keys so
+  // encrypted backup logic becomes easier to reason about. This shouldn't be as
+  // complicated as rocket science.
```
Comment (kev-cao) [inline pkg/jobs/jobspb/jobs.proto:406]: Is this not already the default behavior? My understanding is that once we've generated encryption keys, those are persisted to the job details so that on resume, we can pick up those encryption keys again. And that this was the root cause for all complications — on starting a job, we have raw passphrases/KMS URIs, and on resumption we have encryption keys only.

**Review by kev-cao — APPROVED** [review]
Some nits but LGTM!

File: pkg/backup/compaction_job.go (hunk 1 above)
Comment (msbutler) [reply pkg/backup/compaction_job.go:501]: Nice idea. done.

File: pkg/jobs/jobspb/jobs.go (hunk 2 above)
Comment (msbutler) [reply pkg/jobs/jobspb/jobs.go]: Done.

File: pkg/jobs/jobspb/jobs.proto (hunk 3 above)
Comment (msbutler) [reply pkg/jobs/jobspb/jobs.proto]: i clarified in the todo, but what's sad about the current set up is:
- we're update the job's payload, which we try to keep as static
- we using the same datastructure in semantically different ways. we should just use 2 different data structures.

to solve both problems, i've left a todo to persist the hydrated encrypted keys in a seperate info key. Prior art: https://github.com/cockroachdb/cockroach/pull/143985
