### PR TITLE
security: de-flake TestRotateCerts

### LINKED ISSUE #59667: security: TestRotateCerts failed
[(security).TestRotateCerts failed](https://teamcity.cockroachdb.com/viewLog.html?buildId=2634112&tab=buildLog) on [master@12c20d0f3ea71d52e7dd8277a5633cb3a8ec0e80](https://github.com/cockroachdb/cockroach/commits/12c20d0f3ea71d52e7dd8277a5633cb3a8ec0e80):

```
=== RUN   TestRotateCerts
    certs_rotation_test.go:47: test logs captured to: /go/src/github.com/cockroachdb/cockroach/artifacts/logTestRotateCerts184182196
E210201 19:50:15.388849 1174 (gostd) net/http/server.go:3093  [-] 1  http: TLS handshake error from 127.0.0.1:36264: remote error: tls: bad certificate
E210201 19:50:15.392552 944 1@server/server.go:2032  [n1,client=127.0.0.1:55126] 2  serving SQL client conn: remote error: tls: bad certificate
    certs_rotation_test.go:171: issuing SIGHUP
E210201 19:50:15.425584 1146 (gostd) net/http/server.go:3093  [-] 3  http: TLS handshake error from 127.0.0.1:36272: remote error: tls: bad certificate
    certs_rotation_test.go:216: structured entry for certs_reload not found in log
E210201 19:50:15.904276 1210 1@server/server.go:2032  [n1,client=127.0.0.1:55146] 4  serving SQL client conn: tls: failed to verify client certificate: x509: certificate signed by unknown authority (possibly because of "crypto/rsa: verification error" while trying to verify candidate authority certificate "Cockroach CA")
    certs_rotation_test.go:267: issuing SIGHUP
    certs_rotation_test.go:283: -- test log scope end --
test logs left over in: /go/src/github.com/cockroachdb/cockroach/artifacts/logTestRotateCerts184182196
--- FAIL: TestRotateCerts (1.46s)

```

<details><summary>More</summary><p>
Parameters:

- GOFLAGS=-json

```
make stressrace TESTS=TestRotateCerts PKG=./pkg/security TESTTIMEOUT=5m STRESSFLAGS='-timeout 5m' 2>&1
```

[See this test on roachdash](https://roachdash.crdb.dev/?filter=status%3Aopen+t%3A.%2ATestRotateCerts.%2A&sort=title&restgroup=false&display=lastcommented+project)
<sub>powered by [pkg/cmd/internal/issues](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)</sub></p></details>

### PR DESCRIPTION
**Pull request by knz**
Fixes #59667.

### CODE REVIEW

File: pkg/security/certs_rotation_test.go [hunk 1]
```diff
@@ -187,34 +187,41 @@ func TestRotateCerts(t *testing.T) {
...
-	if err != nil {
-		t.Fatal(err)
-	}
-	foundEntry := false
-	for _, e := range entries {
-		if !strings.Contains(e.Message, "certs_reload") {
-			continue
+	// We use SucceedsSoon here because there may be a delay between
+	// the moment SIGHUP is processed and certs are reloaded, and
+	// the momment the structured logging event is actually
```
Comment (tbg) [inline pkg/security/certs_rotation_test.go:192]: moment

**Review by tbg — APPROVED** [review]

File: pkg/security/certs_rotation_test.go (hunk 1 above)
Comment (knz) [reply pkg/security/certs_rotation_test.go:192]: thanks, fixed

**Comment by knz** [comment]
bors r=tbg
