### PR TITLE
sql: fix memory leak caused by duplicate type in set

### LINKED ISSUE #52762: roachtest: django failed
[(roachtest).django failed](https://teamcity.cockroachdb.com/viewLog.html?buildId=2177056&tab=buildLog) on [master@457f1af5d19e0bcef9b5ea9e9125b3332717a86c](https://github.com/cockroachdb/cockroach/commits/457f1af5d19e0bcef9b5ea9e9125b3332717a86c):

```
The test failed on branch=master, cloud=gce:
test artifacts and logs in: /home/agent/work/.go/src/github.com/cockroachdb/cockroach/artifacts/django/run_1
	orm_helpers.go:218,orm_helpers.go:144,django.go:204,django.go:216,test_runner.go:754: 
		Tests run on Cockroach v20.2.0-alpha.1-2102-g457f1af5d1
		Tests run against django cockroach-3.0.x
		8032 Total Tests Run
		8031 tests passed
		1 test failed
		489 tests skipped
		20 tests ignored
		0 tests passed unexpectedly
		1 test failed unexpectedly
		0 tests expected failed but skipped
		0 tests expected failed but not run
		---
		--- FAIL: get_or_create.tests.UpdateOrCreateTransactionTests.test_creation_in_transaction (unexpected)
		--- SKIP: backends.mysql.test_creation.DatabaseCreationTests.test_create_test_db_unexpected_error due to MySQL tests (expected)
		For a full summary look at the django artifacts 
		
		An updated blocklist (djangoBlocklist20_2) is available in the artifacts' django log

```

<details><summary>More</summary><p>

Artifacts: [/django](https://teamcity.cockroachdb.com/viewLog.html?buildId=2177056&tab=artifacts#/django)
Related:
- #52761 roachtest: django failed  [C-test-failure](https://api.github.com/repos/cockroachdb/cockroach/labels/C-test-failure) [O-roachtest](https://api.github.com/repos/cockroachdb/cockroach/labels/O-roachtest) [O-robot](https://api.github.com/repos/cockroachdb/cockroach/labels/O-robot) [branch-release-20.1](https://api.github.com/repos/cockroachdb/cockroach/labels/branch-release-20.1) [release-blocker](https://api.github.com/repos/cockroachdb/cockroach/labels/release-blocker)

[See this test on roachdash](https://roachdash.crdb.dev/?filter=status%3Aopen+t%3A.%2Adjango.%2A&sort=title&restgroup=false&display=lastcommented+project)
<sub>powered by [pkg/cmd/internal/issues](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)</sub></p></details>

### LINKED ISSUE #53213: sql: Django bulk_update causes OOM when type-checking CASE expression
The django test BulkUpdateTests#test_large_batch does the following
```
    def test_large_batch(self):
        Note.objects.bulk_create([
            Note(note=str(i), misc=str(i))
            for i in range(0, 2000)
        ])
        notes = list(Note.objects.all())
        Note.objects.bulk_update(notes, ['note'])
```

It makes a query like this (except with 2000 cases affected instead of 20):
```
UPDATE
  queries_note
SET
  note
    = CAST(
      CASE
      WHEN (queries_note.id = 583132003825942529) THEN '0'
      WHEN (queries_note.id = 583132003826008065) THEN '1'
      WHEN (queries_note.id = 583132003826302977) THEN '10'
      WHEN (queries_note.id = 583132003826335745) THEN '11'
      WHEN (queries_note.id = 583132003826368513) THEN '12'
      WHEN (queries_note.id = 583132003826401281) THEN '13'
      WHEN (queries_note.id = 583132003826434049) THEN '14'
      WHEN (queries_note.id = 583132003826466817) THEN '15'
      WHEN (queries_note.id = 583132003826499585) THEN '16'
      WHEN (queries_note.id = 583132003826532353) THEN '17'
      WHEN (queries_note.id = 583132003826565121) THEN '18'
      WHEN (queries_note.id = 583132003826597889) THEN '19'
      WHEN (queries_note.id = 583132003826040833) THEN '2'
      WHEN (queries_note.id = 583132003826073601) THEN '3'
      WHEN (queries_note.id = 583132003826106369) THEN '4'
      WHEN (queries_note.id = 583132003826139137) THEN '5'
      WHEN (queries_note.id = 583132003826171905) THEN '6'
      WHEN (queries_note.id = 583132003826204673) THEN '7'
      WHEN (queries_note.id = 583132003826237441) THEN '8'
      WHEN (queries_note.id = 583132003826270209) THEN '9'
      ELSE NULL
      END
        AS VARCHAR(100)
    )
WHERE
  queries_note.id
  IN (
      583132003825942529,
      583132003826008065,
      583132003826302977,
      583132003826335745,
      583132003826368513,
      583132003826401281,
      583132003826434049,
      583132003826466817,
      583132003826499585,
      583132003826532353,
      583132003826565121,
      583132003826597889,
      583132003826040833,
      583132003826073601,
      583132003826106369,
      583132003826139137,
      583132003826171905,
      583132003826204673,
      583132003826237441,
      583132003826270209
    );
```

This causes CockroachDB to crash. I took a heap profile and the function `tree.intersectTypeSlices` was using 20 GB. The problem is from type-checking the CASE expression, as seen below.

image

From looking at the code it seems like the issue might be that a pointer into the input slice is returned, so the whole input slice has to remain in memory. Just a guess.
```
func intersectTypeSlices(xs, ys []*types.T) (out []*types.T) {
	for _, x := range xs {
		for _, y := range ys {
			if x == y {
				out = append(out, x)
			}
		}
	}
	return out
}

func commonConstantType(vals []Expr, idxs []int) (*types.T, bool) {
	var candidates []*types.T

	for _, i := range idxs {
		availableTypes := vals[i].(Constant).DesirableTypes()
		if candidates == nil {
			candidates = availableTypes
		} else {
			candidates = intersectTypeSlices(candidates, availableTypes)
		}
	}

	if len(candidates) > 0 {
		return candidates[0], true
	}
	return nil, false
}
```

### PR DESCRIPTION
**Pull request by rafiss**
The StrValAvailAllParsable slice is supposed to be a set, but it had a
duplicate in it.

This was causing a memory leak in intersectTypeSlices, especially when
type checking a large case expression, which calls this function once for each
case. The "intersection" slice would grow in size exponentially.

fixes #53213
fixes https://github.com/cockroachdb/cockroach/issues/52762

Release note: None

### CODE REVIEW

File: pkg/sql/sem/tree/constant.go [hunk 1]
```diff
@@ -369,12 +369,14 @@ func (expr *NumVal) ResolveAsType(
 }
 
 func intersectTypeSlices(xs, ys []*types.T) (out []*types.T) {
+	seen := make(map[*types.T]bool)
```
Comment (otan) [inline pkg/sql/sem/tree/constant.go:372]: nit: use `map[*types.T]struct{}` instead, with `_, ok := seen[x]` / `seen[x] = struct{}{}`

also this works on a map of pointers -- can we have the same type represented as two different pointers?

would it better to just have a test that `StrValAvailAllParsable` et al have no duplicates?

**Review by otan — COMMENTED** [review]
thanks for catching! couple of questions.

File: pkg/sql/sem/tree/constant.go (hunk 1 above)
Comment (rafiss) [reply pkg/sql/sem/tree/constant.go:372]: > nit: use `map[*types.T]struct{}` instead, with `_, ok := seen[x]` / `seen[x] = struct{}{}`

done

> can we have the same type represented as two different pointers?
i don't think the same type can be represented as two different pointers. or rather, they definitely could, but the assumption everywhere in the codebase (i believe) is that we only operate on the pointers. i'm basing this on #48279. cc @yuzefovich: curious if you have a more well-thought out answer to oliver's question than i do.

> would it better to just have a test that StrValAvailAllParsable et al have no duplicates?

i thought about that.. but didn't do it since i felt like there probably are many slices in the code that need to be sets. i wanted to have a discussion about whether we should be testing for set-hood more generally. or maybe linting? i'm not sure where to have that discussion, but in the mean time i def can add the test you asked for

**Review by yuzefovich — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/53347)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/sem/tree/constant.go, line 372 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/53347#-MFWkcy69Tpl-FId_M5U-r1-372:-MFWr8fQ6ozfqS00KW0F:bexc9cr) ([raw file](https://github.com/cockroachdb/cockroach/blob/5ef7c091bba2a5baa18a65e4ddb545754a7dc810/pkg/sql/sem/tree/constant.go#L372)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

> nit: use `map[*types.T]struct{}` instead, with `_, ok := seen[x]` / `seen[x] = struct{}{}`

done

> can we have the same type represented as two different pointers?

i don't think the same type can be represented as two different pointers. or rather, they definitely could, but the assumption everywhere in the codebase (i believe) is that we only operate on the pointers. i'm basing this on #48279. cc @yuzefovich: curious if you have a more well-thought out answer to oliver's question than i do.

> would it better to just have a test that StrValAvailAllParsable et al have no duplicates?

i thought about that.. but didn't do it since i felt like there probably are many slices in the code that need to be sets. i wanted to have a discussion about whether we should be testing for set-hood more generally. or maybe linting? i'm not sure where to have that discussion, but in the mean time i def can add the test you asked for
</blockquote></details>

Hm, I think we do try to use the same objects to represent the same types, however, upon the inspection of the code of unmarshaling types it seems to me that we're often creating such objects when deserializing `InputSyncSpec` (which is a way to pass the type schema information between different components of a flow).

**Review by otan — APPROVED** [review]

**Comment by rafiss** [comment]
tftr!

bors r=otan

**Comment by otan** [comment]
> [20:35:03]+	defer leaktest.AfterTest(t)()

goddim

**Comment by rafiss** [comment]
yeah.. just noticed that and added it

**Comment by rafiss** [comment]
bors r=otan
