### PR TITLE
sqlstats: add retries to stats test on locked table

### LINKED ISSUE #119067: pkg/sql/sqlstats/persistedsqlstats/persistedsqlstats_test: TestSQLStatsReadLimitSizeOnLockedTable failed
pkg/sql/sqlstats/persistedsqlstats/persistedsqlstats_test.TestSQLStatsReadLimitSizeOnLockedTable [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_StressBazel/13942470?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_StressBazel/13942470?buildTab=artifacts#/) on master @ [b2e31876366324c2ebe5c2ad8bbd644997e90864](https://github.com/cockroachdb/cockroach/commits/b2e31876366324c2ebe5c2ad8bbd644997e90864):

```
=== RUN   TestSQLStatsReadLimitSizeOnLockedTable
    test_log_scope.go:170: test logs captured to: /artifacts/tmp/_tmp/9a30d5271a65be6b3f2aa1433be9011f/logTestSQLStatsReadLimitSizeOnLockedTable3547812076
    test_log_scope.go:81: use -show-logs to present logs inline
    flush_test.go:733: limitReached should be true. loop: 0; shards: [2 5 1 4 7 0 6 3] counts: [13 14 14 10 11 12 11 1]
    panic.go:523: -- test log scope end --
test logs left over in: /artifacts/tmp/_tmp/9a30d5271a65be6b3f2aa1433be9011f/logTestSQLStatsReadLimitSizeOnLockedTable3547812076
--- FAIL: TestSQLStatsReadLimitSizeOnLockedTable (21.19s)
```

Parameters:
 - <code>TAGS=bazel,gss,deadlock</code>
 - <code>stress=true</code>
<details><summary>Help</summary>
<p>

See also: [How To Investigate a Go Test Failure \(internal\)](https://cockroachlabs.atlassian.net/l/c/HgfXfJgM)
</p>
</details>
/cc @cockroachdb/cluster-observability
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*TestSQLStatsReadLimitSizeOnLockedTable.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)
</sub>

Jira issue: CRDB-36018

### PR DESCRIPTION
**Pull request by dhartunian**
Previously, the `TestSQLStatsReadLimitSizeOnLockedTable` test would fail very occasionally due to a rare scenario. When stats are written, they contain a column that's a hashed shard index. It's expected that statements are uniformly distributed across this shard, but that's not guaranteed. Later in the test we check a random shard to make sure its stats count exceeds a minimum of 1 (because we place a total lower bound of 8 in the cluster setting, which is then divided by 8 to derive the per-shard limit). This case will occasionally fail if the random shard that's picked happens to only contain a single statement within.

This change modifies the loop at the end of the test to expect a `false` value and make sure to get at least a single `true` result after 3 iterations, instead of requiring 3 `true` results every single time. The requirement that the queries run despite contention will still stand since we'll return an error in that case.

Resolves: #119067
Epic: None

Release note: None

### CODE REVIEW

File: pkg/sql/sqlstats/persistedsqlstats/flush_test.go [hunk 1]
```diff
@@ -705,7 +704,7 @@ func TestSQLStatsReadLimitSizeOnLockedTable(t *testing.T) {
 
 	// Set table size check interval to .0000001 second. So the next check doesn't
 	// use the cached value.
-	sqlConn.Exec(t, "SET CLUSTER SETTING sql.stats.limit_table_size_check.interval='.0000001s'")
+	persistedsqlstats.SQLStatsLimitTableCheckInterval.Override(ctx, &s.ClusterSettings().SV, time.Nanosecond)
```
Comment (xinhaoz) [inline pkg/sql/sqlstats/persistedsqlstats/flush_test.go:707]: Why did we need to override this instead of using the set statement above?

**Review by xinhaoz — APPROVED** [review]
Nice!

File: pkg/sql/sqlstats/persistedsqlstats/flush_test.go (hunk 1 above)
Comment (dhartunian) [reply pkg/sql/sqlstats/persistedsqlstats/flush_test.go:707]: The new code does the same thing. Override just sets the setting value directly.
This is an unnecessary change but one that simplifies test execution by removing the need for a full SQL parse/exec loop when we have the ability to set the value directly.

**Comment by dhartunian** [comment]
TFTR

bors r=xinhaoz
