### PR TITLE
roachtest: fix decommission/randomize

### LINKED ISSUE #55581: roachtest: decommission/randomized failed
[(roachtest).decommission/randomized failed](https://teamcity.cockroachdb.com/viewLog.html?buildId=2366018&tab=buildLog) on [master@80e7127197f76ef35c1f6ec3984c4d49d4afde7f](https://github.com/cockroachdb/cockroach/commits/80e7127197f76ef35c1f6ec3984c4d49d4afde7f):

```
		  |   | main.main
		  |   | 	/home/agent/work/.go/src/github.com/cockroachdb/cockroach/pkg/cmd/roachprod/main.go:1839
		  |   | runtime.main
		  |   | 	/usr/local/go/src/runtime/proc.go:203
		  |   | runtime.goexit
		  |   | 	/usr/local/go/src/runtime/asm_amd64.s:1357
		  | Wraps: (2) 1: dead
		  | Error types: (1) *withstack.withStack (2) *errutil.leafError
		Wraps: (4) secondary error attachment
		  | 4: dead
		  | (1) attached stack trace
		  |   -- stack trace:
		  |   | main.glob..func14
		  |   | 	/home/agent/work/.go/src/github.com/cockroachdb/cockroach/pkg/cmd/roachprod/main.go:1143
		  |   | main.wrap.func1
		  |   | 	/home/agent/work/.go/src/github.com/cockroachdb/cockroach/pkg/cmd/roachprod/main.go:267
		  |   | github.com/spf13/cobra.(*Command).execute
		  |   | 	/home/agent/work/.go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:830
		  |   | github.com/spf13/cobra.(*Command).ExecuteC
		  |   | 	/home/agent/work/.go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:914
		  |   | github.com/spf13/cobra.(*Command).Execute
		  |   | 	/home/agent/work/.go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:864
		  |   | main.main
		  |   | 	/home/agent/work/.go/src/github.com/cockroachdb/cockroach/pkg/cmd/roachprod/main.go:1839
		  |   | runtime.main
		  |   | 	/usr/local/go/src/runtime/proc.go:203
		  |   | runtime.goexit
		  |   | 	/usr/local/go/src/runtime/asm_amd64.s:1357
		  | Wraps: (2) 4: dead
		  | Error types: (1) *withstack.withStack (2) *errutil.leafError
		Wraps: (5) attached stack trace
		  -- stack trace:
		  | main.glob..func14
		  | 	/home/agent/work/.go/src/github.com/cockroachdb/cockroach/pkg/cmd/roachprod/main.go:1143
		  | main.wrap.func1
		  | 	/home/agent/work/.go/src/github.com/cockroachdb/cockroach/pkg/cmd/roachprod/main.go:267
		  | github.com/spf13/cobra.(*Command).execute
		  | 	/home/agent/work/.go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:830
		  | github.com/spf13/cobra.(*Command).ExecuteC
		  | 	/home/agent/work/.go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:914
		  | github.com/spf13/cobra.(*Command).Execute
		  | 	/home/agent/work/.go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:864
		  | main.main
		  | 	/home/agent/work/.go/src/github.com/cockroachdb/cockroach/pkg/cmd/roachprod/main.go:1839
		  | runtime.main
		  | 	/usr/local/go/src/runtime/proc.go:203
		  | runtime.goexit
		  | 	/usr/local/go/src/runtime/asm_amd64.s:1357
		Wraps: (6) 3: dead
		Error types: (1) errors.Unclassified (2) *secondary.withSecondaryError (3) *secondary.withSecondaryError (4) *secondary.withSecondaryError (5) *withstack.withStack (6) *errutil.leafError

```

<details><summary>More</summary><p>

Artifacts: [/decommission/randomized](https://teamcity.cockroachdb.com/viewLog.html?buildId=2366018&tab=artifacts#/decommission/randomized)

[See this test on roachdash](https://roachdash.crdb.dev/?filter=status%3Aopen+t%3A.%2Adecommission%2Frandomized.%2A&sort=title&restgroup=false&display=lastcommented+project)
<sub>powered by [pkg/cmd/internal/issues](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)</sub></p></details>

### PR DESCRIPTION
**Pull request by tbg**
The test could end up using fully decommissioned nodes for cli commands,
which does not work as of #55286.

Fixes #55581.

Release note: None

### CODE REVIEW

**Comment by tbg** [comment]
Draft because I stressed this locally and it's still whack. Probably will be able to spot the problem via a self-review.

**Comment by tbg** [comment]
The problem is (I assume) that the test wants to see the decommissioned nodes in the `node ls` output. They won't be there any more since they are decommissioned, and forcibly become non-live pretty soon because they lose contact with the cluster. Will have to massage this test a bit more.

**Comment by tbg** [comment]
Finally good to go, got 50 consecutive iterations in.

File: pkg/cmd/roachtest/decommission.go [hunk 1]
```diff
@@ -516,40 +534,51 @@ func runDecommissionRandomized(ctx context.Context, t *test, c *cluster) {
...
-			o, err := execCLI(ctx, t, c, runNode, "node", "ls", "--format=csv")
-			if err != nil {
-				t.Fatalf("node-ls failed: %v", err)
-			}
-			exp := [][]string{{"id"}}
-			for i := 1; i <= c.spec.NodeCount; i++ {
-				exp = append(exp, []string{strconv.Itoa(i)})
-			}
-			if err := h.matchCSV(o, exp); err != nil {
+			if err := retry.WithMaxAttempts(ctx, retry.Options{}, 50, func() error {
```
Comment (irfansharif) [inline pkg/cmd/roachtest/decommission.go:540]: I assume this retry loop here, above and below were all needed for the same reason? Propagation delays to the invoking node?

**Review by irfansharif — APPROVED** [review]

File: pkg/cmd/roachtest/decommission.go (hunk 1 above)
Comment (tbg) [reply pkg/cmd/roachtest/decommission.go:540]: The decommissioned nodes have to lose their liveness first.

**Comment by tbg** [comment]
TFTR!

bors r=irfansharif
