### PR TITLE
roachtest: allow specifying a set of valid architectures

### LINKED ISSUE #153833: roachtest: failover/non-system/disk-stall failed
roachtest.failover/non-system/disk-stall [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/20496298?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/20496298?buildTab=artifacts#/failover/non-system/disk-stall) on master @ [efbdc43d32c100ff000c6223a9b83c2221f27819](https://github.com/cockroachdb/cockroach/commits/efbdc43d32c100ff000c6223a9b83c2221f27819):

```
(disk_stall.go:176).Setup: failed to setup disk stall: unexpected output from lsblk: 
test artifacts and logs in: /artifacts/failover/non-system/disk-stall/cpu_arch=fips/run_1
```

Parameters:
 - <code>arch=fips</code>
 - <code>cloud=gce</code>
 - <code>coverageBuild=false</code>
 - <code>cpu=2</code>
 - <code>encrypted=false</code>
 - <code>fs=ext4</code>
 - <code>localSSD=false</code>
 - <code>runtimeAssertionsBuild=false</code>
 - <code>ssd=0</code>
<details><summary>Help</summary>
<p>

See: [roachtest README](https://github.com/cockroachdb/cockroach/blob/master/pkg/cmd/roachtest/README.md)

See: [How To Investigate \(internal\)](https://cockroachlabs.atlassian.net/l/c/SSSBr8c7)

See: [Grafana](https://go.crdb.dev/roachtest-grafana/teamcity-20496298/failover-non-system-disk-stall/1758366077356/1758366244320)

</p>
</details>
/cc @cockroachdb/kv-triage
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*failover/non-system/disk-stall.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/bazci/githubpost/issues)

</sub>

Jira issue: CRDB-54621

### LINKED ISSUE #154110: roachtest: admission-control/disk-bandwidth-limiter failed
roachtest.admission-control/disk-bandwidth-limiter [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/20516654?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/20516654?buildTab=artifacts#/admission-control/disk-bandwidth-limiter) on release-25.4 @ [9221c5318324b33455257088d3a48fae69346359](https://github.com/cockroachdb/cockroach/commits/9221c5318324b33455257088d3a48fae69346359):

```
(disk_stall.go:141).Slow: failed to slow disk: unexpected output from lsblk: 
test artifacts and logs in: /artifacts/admission-control/disk-bandwidth-limiter/cpu_arch=fips/run_1
```

Parameters:
 - <code>arch=fips</code>
 - <code>cloud=gce</code>
 - <code>coverageBuild=false</code>
 - <code>cpu=8</code>
 - <code>encrypted=false</code>
 - <code>fs=ext4</code>
 - <code>localSSD=true</code>
 - <code>metamorphicLeases=default</code>
 - <code>runtimeAssertionsBuild=false</code>
 - <code>ssd=0</code>
<details><summary>Help</summary>
<p>

See: [roachtest README](https://github.com/cockroachdb/cockroach/blob/master/pkg/cmd/roachtest/README.md)

See: [How To Investigate \(internal\)](https://cockroachlabs.atlassian.net/l/c/SSSBr8c7)

See: [Grafana](https://go.crdb.dev/roachtest-grafana/teamcity-20516654/admission-control-disk-bandwidth-limiter/1758782403648/1758782618255)

</p>
</details>
/cc @cockroachdb/admission-control
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*admission-control/disk-bandwidth-limiter.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/bazci/githubpost/issues)

</sub>

### PR DESCRIPTION
**Pull request by DarrylWong**
Previously, tests could only specify one valid architecture or enable all of them to be metamorphically chosen. This changes the cluster spec to allow multiple architectures to be specified.

This is now needed because we recently started running FIPS metamorphically on our nightlies. Some tests are not compatible with ARM or FIPS, and we want to only disable execution on those architectures.

Fixes: #153833
Fixes: #154110
Informs: #152781

### CODE REVIEW

File: pkg/cmd/roachtest/cluster.go [hunk 1]
```diff
@@ -3221,6 +3210,55 @@ func archForTest(ctx context.Context, l *logger.Logger, testSpec registry.TestSp
...
+	}
+
+	// Since we allow only a subset of architectures, our total probability
+	// may not add up to 1. We normalize the weights amongst the valid architectures
+	// and track cumulative weights that give us "probability buckets" for each
+	// architecture.
+	cumulativeWeights := make([]float64, 0, len(validArchsList))
+	runningTotal := 0.0
+	for _, arch := range validArchsList {
+		normalizedWeight := baseProbabilities[arch] / totalValidWeight
```
Comment (DarrylWong) [inline pkg/cmd/roachtest/cluster.go:3253]: Rejection sampling should give the same distribution I believe. I _mildly_ prefer normalization since we can log and see the probabilities.

File: pkg/cmd/roachtest/cluster_test.go [hunk 2]
```diff
@@ -909,3 +910,125 @@ func TestVerifyLibraries(t *testing.T) {
...
+			arm64Probability: 0.6,
+			fipsProbability:  0.2,
+			expectedDistribution: map[vm.CPUArch]float64{
+				vm.ArchARM64: 0.88235,
+				vm.ArchFIPS:  0.11765,
+			},
+		},
+	}
+
+	// Since this is a statistical test, we want to use a fixed seed to avoid flakes,
```
Comment (srosenberg) [inline pkg/cmd/roachtest/cluster_test.go:1001]: Pretty slick!

File: pkg/cmd/roachtest/cluster_test.go [hunk 3]
```diff
@@ -909,3 +910,125 @@ func TestVerifyLibraries(t *testing.T) {
...
+				counts[arch]++
+			}
+
+			for expectedArch, expectedProb := range test.expectedDistribution {
+				actualCount := float64(counts[expectedArch])
+				actualProb := actualCount / float64(numSamples)
+
+				// Calculate a 95% confidence interval and assert our actual probability falls within it.
+				z := 1.96 // 95% confidence level
+				margin := z * math.Sqrt(expectedProb*(1-expectedProb)/float64(numSamples))
```
Comment (srosenberg) [inline pkg/cmd/roachtest/cluster_test.go]: When `expectedProb` is either 0 or 1, your margin is exactly 0 which isn't great since floating-point equality needs a `delta`. Also, technically, the confidence interval formula assumes a normal distribution. Maybe, a small `delta` will have sufficed instead of the confidence interval?

Comment (DarrylWong) [reply pkg/cmd/roachtest/cluster_test.go]: Sure, done.

File: pkg/cmd/roachtest/spec/cluster_spec.go [hunk 4]
```diff
@@ -37,6 +37,134 @@ const (
 	RoachtestBranch = "roachtest-branch"
 )
 
+// ArchSet represents a set of CPU architectures.
+//
+// N.B. We call this a set to mirror how we represent other sets (e.g. clouds, suites),
+// but we cannot use a map directly since we compare cluster specs for reusability.
+type ArchSet struct {
```
Comment (herkolategan) [inline pkg/cmd/roachtest/spec/cluster_spec.go]: Have you considered using a flag set here?

Some reference code (only as an example), but potentially you could just have a flag mapping for each `vm.Arch*`, and then would be able to get rid of most of the switch boilerplate code, I think?

```
type ArchFlags uint8

const (
	AMD64 ArchFlags = 1 << iota
	ARM64
	FIPS
)

type ArchSet uint8

func (a ArchSet) Has(flag ArchFlags) bool {
	return a&ArchSet(flag) != 0
}

func (a *ArchSet) Add(flag ArchFlags) {
	*a |= ArchSet(flag)
}

func (a *ArchSet) Remove(flag ArchFlags) {
	*a &^= ArchSet(flag)
}
```

Comment (herkolategan) [reply pkg/cmd/roachtest/spec/cluster_spec.go]: And it remains deterministic for comparison.

Comment (DarrylWong) [reply pkg/cmd/roachtest/spec/cluster_spec.go]: I did but opted for the bool for readability since memory and concurrency don't matter here. I don't feel strongly about it though if you think getting rid of the boilerplate is worth it.

**Review by herkolategan — APPROVED** [review]
