### PR TITLE
ts: include metric name in childMetricNameCache key

### LINKED ISSUE #169172: ts: childMetricNameCache collides across metrics with identical labels
**Describe the problem**

`childMetricNameCache` in `pkg/server/status/recorder.go` keys cached
encoded TSDB metric names on a hash of the Prometheus label set alone,
on the assumption that the label set uniquely identifies a child
metric. That assumption does not hold.

Most allowlisted changefeed agg-metrics are constructed via
`aggmetric.MakeBuilder("scope")`, so distinct metrics (e.g.
`changefeed.error_retries` and `changefeed.lagging_ranges`) routinely
share an identical `{scope="..."}` label set. The first metric to
populate the cache for a given label hash wins, and any subsequent
metric with the same labels is recorded into TSDB under the *first*
metric's encoded name.

Effects:
- The displaced metric's values overwrite the winning metric's time
  series, producing wrong values for the winner.
- The displaced metric is dropped from TSDB entirely (no series under
  its own name).

A secondary, lower-probability collision exists in `hashLabels` itself:
adjacent name/value bytes are concatenated without a separator, so
`{name="ab", value="c"}` and `{name="a", value="bc"}` hash to the same
value.

**To Reproduce**

1. Run a cluster with two allowlisted changefeed child metrics that
   share a label set (e.g. both built from
   `aggmetric.MakeBuilder("scope")` with the same scope value).
2. Observe TSDB output: only one of the two metric names appears, and
   its values reflect whichever metric happened to populate the cache
   first for that polling cycle.

A regression test demonstrating the collision is included in #169079.

**Expected behavior**

Each child metric is recorded to TSDB under its own encoded name with
its own values, regardless of whether other metrics share the same
label set.

**Environment:**
- Affected versions: v26.1+ (introduced by b5155c6780f, "ts: memoize
  child metric name transformation"). Present on `release-26.1`,
  `release-26.2`, and `master`.

**Additional context**

Impact: silent corruption of changefeed TSDB metrics on any cluster
running multiple allowlisted child metrics with overlapping label
sets — i.e. effectively any non-trivial production cluster using
changefeeds.

Fix: #169079 includes the unlabeled metric name in both the cache key
(`hashLabeledName`) and the cache-hit verification
(`cacheEntry.matches`), and writes zero-byte separators between hashed
fields.

Jira issue: CRDB-63308

### PR DESCRIPTION
**Pull request by jasonlmfong**
childMetricNameCache previously keyed entries on a hash of the Prometheus label set alone, on the assumption that the label set was sufficient to identify the encoded TSDB metric name. That assumption does not hold: most allowlisted changefeed agg-metrics are constructed via aggmetric.MakeBuilder("scope"), so distinct metrics (e.g. changefeed.error_retries and changefeed.lagging_ranges) routinely share an identical {scope="..."} label set. The first metric to populate the cache for a given label hash would win, and any subsequent metric with the same labels was recorded into TSDB under the first metric's encoded name -- producing wrong values in the affected time series and dropping the displaced metric entirely.

Fix this by including the unlabeled metric name in both the cache key (hashLabeledName) and the cache-hit verification (cacheEntry.matches). hashLabeledName also writes zero-byte separators between fields to close a secondary collision class where adjacent name/value bytes could be reassociated (e.g. {name="ab", value="c"} vs {name="a", value="bc"} hashing to the same value).

Cache footprint grows by roughly the number of allowlisted metrics that share a label set; it remains bounded by the existing per-metric 1024-child cap.

Fixes: https://github.com/cockroachdb/cockroach/issues/169172
Epic: none
Release note: None

### CODE REVIEW

File: pkg/server/status/recorder.go [hunk 1]
```diff
@@ -1162,59 +1162,89 @@ func (rr registryRecorder) recordChild(
...
 }
 
-// cacheEntry holds a cached metric name along with the labels that produced it,
-// used for verification when hash collisions occur.
+// cacheEntry records the inputs that produced an encoded metric name, so that
+// hash collisions and same-label/different-metric scenarios are caught on
+// lookup.
 type cacheEntry struct {
+	// metricName is the unlabeled metric name (e.g. "changefeed.error_retries").
+	// Stored alongside labels so that distinct metrics sharing a label set are
```
Comment (alyshanjahani-crl) [inline pkg/server/status/recorder.go:1196]: nit: in most of the comments the language seems like "distinct metrics sharing a label set" is an edge case - but this is common / always the case isn't it?

Most metrics in cockroach will share the same label set.

I'm kind surprised this wasn't caught/tested in the original PRs

Comment (jasonlmfong) [reply pkg/server/status/recorder.go:1196]: yeah you are right

**Comment by alyshanjahani-crl** [comment]
Let's add backport labels for 26.1 and 26.2 (i believe tsdb writing child metrics was introduced in 26.1).

Let's also do some e2e testing as a sanity check.

**Review by alyshanjahani-crl — APPROVED** [review]
In terms of backporting, all the code changes here are still guarded by the same cluster setting that protects (enables/disabled) this feature / code path right?

**Comment by jasonlmfong** [comment]
> all the code changes here are still guarded by the same cluster setting that protects (enables/disabled) this feature / code path right?

yeah they are only reachable under this code path

**Comment by jasonlmfong** [comment]
/trunk merge

TFTR!
