### PR TITLE
sql: TestReacquireLeaseOnRestart fix

### LINKED ISSUE #129421: sql: TestReacquireLeaseOnRestart failed
sql.TestReacquireLeaseOnRestart [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Ci_TestsAwsLinuxArm64_UnitTests/16567338?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Ci_TestsAwsLinuxArm64_UnitTests/16567338?buildTab=artifacts#/) on master @ [5c51c69e82c471e6667489a828f191940e5c425e](https://github.com/cockroachdb/cockroach/commits/5c51c69e82c471e6667489a828f191940e5c425e):

```
=== RUN   TestReacquireLeaseOnRestart
    test_log_scope.go:170: test logs captured to: /artifacts/tmp/_tmp/492cc08314ebb30515b6f60e383090f4/logTestReacquireLeaseOnRestart3185703012
    test_log_scope.go:81: use -show-logs to present logs inline
    txn_restart_test.go:1221: pq: failed to insert lease {[128] 105 1 1 {{18184000 63859861489 <nil>}} [1 1 128 181 251 85 191 210 136 78 120 162 37 167 116 99 9 168 185]}: unexpected value: raw_bytes:"\035HOc\n3\002" timestamp:<wall_time:1724263801038456666 > 
    panic.go:626: -- test log scope end --
test logs left over in: /artifacts/tmp/_tmp/492cc08314ebb30515b6f60e383090f4/logTestReacquireLeaseOnRestart3185703012
--- FAIL: TestReacquireLeaseOnRestart (0.53s)
```
<details><summary>Help</summary>
<p>

See also: [How To Investigate a Go Test Failure \(internal\)](https://cockroachlabs.atlassian.net/l/c/HgfXfJgM)
</p>
</details>
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*TestReacquireLeaseOnRestart.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/bazci/githubpost/issues)
</sub>

Jira issue: CRDB-41537

### LINKED ISSUE #130491: ccl/backupccl: TestRestoreAsOfSystemTimeGCBounds failed
ccl/backupccl.TestRestoreAsOfSystemTimeGCBounds [failed](https://tanzanite.cluster.engflow.com/invocations/default/f2de0c0b-d9e2-4867-9250-224410255964?testReportRun=1&testReportShard=2&testReportAttempt=1#targets-Ly9wa2cvY2NsL2JhY2t1cGNjbDpiYWNrdXBjY2xfdGVzdA==) on release-24.1 @ [bfc681c36fff728bc396c2d00f84a8c55a7c17af](https://github.com/cockroachdb/cockroach/commits/bfc681c36fff728bc396c2d00f84a8c55a7c17af):

```
=== RUN   TestRestoreAsOfSystemTimeGCBounds
    test_log_scope.go:170: test logs captured to: outputs.zip/logTestRestoreAsOfSystemTimeGCBounds3390737136
    test_log_scope.go:81: use -show-logs to present logs inline
    test_server_shim.go:157: automatically injected a shared process virtual cluster under test; see comment at top of test_server_shim.go for details.
    backup_test.go:4021: error executing query="BACKUP data.bank TO $1 WITH revision_history" args=["nodelocal://1//tbl-after-gc"]: pq: failed to insert lease {[128] 3 1 1 {{552644000 63861648486 <nil>}} [1 1 128 4 38 248 229 85 82 69 241 181 111 55 193 204 189 40 234]}: unexpected value: raw_bytes:"\351\276\277\327\n3\002" timestamp:<wall_time:1726051397830154474 > 
    testutils.go:290: no Invalid Descriptors
    panic.go:626: -- test log scope end --
test logs left over in: outputs.zip/logTestRestoreAsOfSystemTimeGCBounds3390737136
--- FAIL: TestRestoreAsOfSystemTimeGCBounds (13.22s)
```

Parameters:
 - <code>attempt=1</code>
 - <code>race=true</code>
 - <code>run=1</code>
 - <code>shard=2</code>
<details><summary>Help</summary>
<p>

See also: [How To Investigate a Go Test Failure \(internal\)](https://cockroachlabs.atlassian.net/l/c/HgfXfJgM)
</p>
</details>
/cc @cockroachdb/disaster-recovery
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*TestRestoreAsOfSystemTimeGCBounds.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/bazci/githubpost/issues)
</sub>

Jira issue: CRDB-42089

### PR DESCRIPTION
**Pull request by Dedej-Bergin**
upsertLeaseLocked was updated so it clears the session ID from the lease it returned as toRelease. This prevents the old lease from being removed when using session based leasing. Removing it is not desired since in session based we want to keep that row in the lease table.
Previously we had an extra condition in an if statement which caused this failure.  This was the condition `errors.Is(err, errRenewLease)` it is now removed and we now set toRelease to nil when `session != nil`

Fixes: #129421
Fixes: https://github.com/cockroachdb/cockroach/issues/130491

Release note: none

### CODE REVIEW

File: pkg/sql/catalog/lease/descriptor_state.go [hunk 1]
```diff
@@ -172,6 +172,7 @@ func (t *descriptorState) upsertLeaseLocked(
 	}
 	if session != nil {
 		s.mu.lease.sessionID = session.ID().UnsafeBytes()
+		toRelease = nil
```
Comment (fqazi) [inline pkg/sql/catalog/lease/descriptor_state.go:175]: Add a comment stating why toRelease is being cleared here.

// When using session based leasing, if we end up acquiring the same lease again nothing needs to be cleaned up or updated. This is because the system.lease table does not store any expiry inside the table.

File: pkg/sql/catalog/lease/lease.go [hunk 2]
```diff
@@ -821,7 +821,7 @@ func purgeOldVersions(
 	// if we hit this case. Note: This scenario is impossible to hit in the real
 	// world since the lease duration is never set to 0.
 	desc, _, err := t.findForTimestamp(ctx, m.storage.clock.Now())
-	if isInactive := catalog.HasInactiveDescriptorError(err); err == nil || isInactive || errors.Is(err, errRenewLease) {
+	if isInactive := catalog.HasInactiveDescriptorError(err); err == nil || isInactive {
```
Comment (fqazi) [inline pkg/sql/catalog/lease/lease.go:824]: Can you try reverting this part of the change and check if the test is stable? I think it's causing CI failures

**Review by fqazi — CHANGES_REQUESTED** [review]

**Review by fqazi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/137628#-:-OEV_Ryu-EWn38rm9yZv:bnfp4nl)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @Dedej-Bergin)

File: pkg/sql/catalog/lease/descriptor_state.go (hunk 1 above)
Comment (Dedej-Bergin) [reply pkg/sql/catalog/lease/descriptor_state.go]: Thanks Faizan! I added the comment.

File: pkg/sql/catalog/lease/lease.go (hunk 2 above)
Comment (Dedej-Bergin) [reply pkg/sql/catalog/lease/lease.go:816]: Thanks Faizan! I removed the comment.

**Review by Dedej-Bergin — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/137628)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @fqazi)
