### PR TITLE
storage: Really deflake TestStoreRangeSystemSplits

### LINKED ISSUE #12248: github.com/cockroachdb/cockroach/pkg/storage: TestStoreRangeSystemSplits failed under stress
SHA: https://github.com/cockroachdb/cockroach/commits/87064e42812b92232db2c7d3841829a8fe9f26f5

Parameters:
```
COCKROACH_PROPOSER_EVALUATED_KV=false
TAGS=deadlock
GOFLAGS=
```

Stress build found a failed test: https://teamcity.cockroachdb.com/viewLog.html?buildId=86877&tab=buildLog

```
I161210 10:12:45.645209 2326981 storage/engine/rocksdb.go:340  opening in memory rocksdb instance
I161210 10:12:45.645969 2326981 gossip/gossip.go:248  [n?] initial resolvers: []
W161210 10:12:45.646073 2326981 gossip/gossip.go:1124  [n?] no resolvers found; use --join to specify a connected node
I161210 10:12:45.646168 2326981 base/node_id.go:62  NodeID set to 1
I161210 10:12:45.646250 2326981 gossip/gossip.go:290  [n1] NodeDescriptor set to node_id:1 address:<network_field:"" address_field:"" > attrs:<> locality:<> 
I161210 10:12:45.651982 2327257 storage/replica_proposal.go:360  [s1,r1/1:/M{in-ax},@c429174500] new range lease repl={1 1 1} start=0.000000000,0 exp=0.900000123,6 pro=0.000000123,7 following repl={0 0 0} start=0.000000000,0 exp=0.000000000,0 [physicalTime=1970-01-01 00:00:00.000000123 +0000 UTC]
I161210 10:12:45.654151 2327598 storage/split_queue.go:103  [split,s1,r1/1:/M{in-ax},@c429174500] splitting at keys [/Table/11/0 /Table/12/0 /Table/13/0 /Table/14/0]
I161210 10:12:45.658489 2327598 storage/replica_command.go:2389  [split,s1,r1/1:/M{in-ax},@c429174500] initiating a split of this range at key /Table/11 [r2]
E161210 10:12:45.680403 2327598 storage/queue.go:602  [split,s1,r1/1:/{Min-Table/11},@c429174500] unable to split [n1,s1,r1/1:/{Min-Table/11}] at key "/Table/12/0": key range /Table/12/0-/Table/12/0 outside of bounds of range /Min-/Max
E161210 10:12:45.682244 2327599 storage/queue.go:613  [replicate,s1,r1/1:/{Min-Table/11},@c429174500] purgatory: 0 of 0 stores with an attribute matching []; likely not enough nodes in cluster
I161210 10:12:45.684086 2327598 storage/split_queue.go:103  [split,s1,r2/1:/{Table/11-Max},@c433248000] splitting at keys [/Table/12/0 /Table/13/0 /Table/14/0]
I161210 10:12:45.684178 2327598 storage/replica_command.go:2389  [split,s1,r2/1:/{Table/11-Max},@c433248000] initiating a split of this range at key /Table/12 [r3]
W161210 10:12:45.687320 2327598 storage/stores.go:218  range not contained in one range: [/Meta2/Table/12,/Table/12/NULL), but have [/Min,/Table/11)
W161210 10:12:45.693320 2328900 storage/intent_resolver.go:332  [n1,s1,r1/1:/{Min-Table/11}]: failed to push during intent resolution: failed to push "storage/replica_command.go:2459 (*Replica).adminSplitWithDescriptor" id=22610ed3 key=/Local/Range/"\x93"/RangeDescriptor rw=true pri=0.00194088 iso=SERIALIZABLE stat=PENDING epo=0 ts=0.000000123,67 orig=0.000000123,67 max=0.000000123,67 wto=false rop=false
E161210 10:12:45.703059 2327598 storage/queue.go:602  [split,s1,r2/1:/Table/1{1-2},@c433248000] unable to split [n1,s1,r2/1:/Table/1{1-2}] at key "/Table/13/0": key range /Table/13/0-/Table/13/0 outside of bounds of range /Table/11-/Max
E161210 10:12:45.704194 2327599 storage/queue.go:613  [replicate,s1,r2/1:/Table/1{1-2},@c433248000] purgatory: 0 of 0 stores with an attribute matching []; likely not enough nodes in cluster
I161210 10:12:45.704452 2327598 storage/split_queue.go:103  [split,s1,r3/1:/{Table/12-Max},@c4303ed400] splitting at keys [/Table/13/0 /Table/14/0]
I161210 10:12:45.704549 2327598 storage/replica_command.go:2389  [split,s1,r3/1:/{Table/12-Max},@c4303ed400] initiating a split of this range at key /Table/13 [r4]
E161210 10:12:45.724661 2327599 storage/queue.go:613  [replicate,s1,r3/1:/Table/1{2-3},@c4303ed400] purgatory: 0 of 0 stores with an attribute matching []; likely not enough nodes in cluster
E161210 10:12:45.725607 2327598 storage/queue.go:602  [split,s1,r3/1:/Table/1{2-3},@c4303ed400] unable to split [n1,s1,r3/1:/Table/1{2-3}] at key "/Table/14/0": key range /Table/14/0-/Table/14/0 outside of bounds of range /Table/12-/Max
I161210 10:12:45.725985 2327598 storage/split_queue.go:103  [split,s1,r4/1:/{Table/13-Max},@c42f0e0a00] splitting at keys [/Table/14/0]
I161210 10:12:45.726108 2327598 storage/replica_command.go:2389  [split,s1,r4/1:/{Table/13-Max},@c42f0e0a00] initiating a split of this range at key /Table/14 [r5]
E161210 10:12:45.746888 2327599 storage/queue.go:613  [replicate,s1,r4/1:/Table/1{3-4},@c42f0e0a00] purgatory: 0 of 0 stores with an attribute matching []; likely not enough nodes in cluster
E161210 10:12:45.747464 2327599 storage/queue.go:613  [replicate,s1,r5/1:/{Table/14-Max},@c42fb7c500] purgatory: 0 of 0 stores with an attribute matching []; likely not enough nodes in cluster
I161210 10:12:45.761129 2327598 storage/split_queue.go:103  [split,s1,r5/1:/{Table/14-Max},@c42fb7c500] splitting at keys [/Table/50/0 /Table/51/0 /Table/52/0 /Table/53/0 /Table/54/0 /Table/55/0 /Table/56/0 /Table/57/0 /Table/58/0 /Table/59/0 /Table/60/0 /Table/61/0 /Table/62/0 /Table/63/0 /Table/64/0 /Table/65/0 /Table/66/0 /Table/67/0 /Table/68/0]
I161210 10:12:45.761217 2327598 storage/replica_command.go:2389  [split,s1,r5/1:/{Table/14-Max},@c42fb7c500] initiating a split of this range at key /Table/50 [r6]
E161210 10:12:45.804868 2327598 storage/queue.go:602  [split,s1,r5/1:/Table/{14-50},@c42fb7c500] unable to split [n1,s1,r5/1:/Table/{14-50}] at key "/Table/51/0": key range /Table/51/0-/Table/51/0 outside of bounds of range /Table/14-/Max
I161210 10:12:45.807586 2327598 storage/split_queue.go:103  [split,s1,r6/1:/{Table/50-Max},@c433249900] splitting at keys [/Table/51/0 /Table/52/0 /Table/53/0 /Table/54/0 /Table/55/0 /Table/56/0 /Table/57/0 /Table/58/0 /Table/59/0 /Table/60/0 /Table/61/0 /Table/62/0 /Table/63/0 /Table/64/0 /Table/65/0 /Table/66/0 /Table/67/0 /Table/68/0]
I161210 10:12:45.807672 2327598 storage/replica_command.go:2389  [split,s1,r6/1:/{Table/50-Max},@c433249900] initiating a split of this range at key /Table/51 [r7]
E161210 10:12:45.825885 2327599 storage/queue.go:613  [replicate,s1,r6/1:/Table/5{0-1},@c433249900] purgatory: 0 of 0 stores with an attribute matching []; likely not enough nodes in cluster
E161210 10:12:45.826472 2327598 storage/queue.go:602  [split,s1,r6/1:/Table/5{0-1},@c433249900] unable to split [n1,s1,r6/1:/Table/5{0-1}] at key "/Table/52/0": key range /Table/52/0-/Table/52/0 outside of bounds of range /Table/50-/Max
I161210 10:12:45.845304 2327598 storage/split_queue.go:103  [split,s1,r7/1:/{Table/51-Max},@c426eea000] splitting at keys [/Table/52/0 /Table/53/0 /Table/54/0 /Table/55/0 /Table/56/0 /Table/57/0 /Table/58/0 /Table/59/0 /Table/60/0 /Table/61/0 /Table/62/0 /Table/63/0 /Table/64/0 /Table/65/0 /Table/66/0 /Table/67/0 /Table/68/0]
I161210 10:12:45.845491 2327598 storage/replica_command.go:2389  [split,s1,r7/1:/{Table/51-Max},@c426eea000] initiating a split of this range at key /Table/52 [r8]
E161210 10:12:45.878296 2327598 storage/queue.go:602  [split,s1,r7/1:/Table/5{1-2},@c426eea000] unable to split [n1,s1,r7/1:/Table/5{1-2}] at key "/Table/53/0": key range /Table/53/0-/Table/53/0 outside of bounds of range /Table/51-/Max
E161210 10:12:45.878358 2327599 storage/queue.go:613  [replicate,s1,r7/1:/Table/5{1-2},@c426eea000] purgatory: 0 of 0 stores with an attribute matching []; likely not enough nodes in cluster
I161210 10:12:45.879237 2327598 storage/split_queue.go:103  [split,s1,r8/1:/{Table/52-Max},@c42ca3f400] splitting at keys [/Table/53/0 /Table/54/0 /Table/55/0 /Table/56/0 /Table/57/0 /Table/58/0 /Table/59/0 /Table/60/0 /Table/61/0 /Table/62/0 /Table/63/0 /Table/64/0 /Table/65/0 /Table/66/0 /Table/67/0 /Table/68/0]
I161210 10:12:45.879334 2327598 storage/replica_command.go:2389  [split,s1,r8/1:/{Table/52-Max},@c42ca3f400] initiating a split of this range at key /Table/53 [r9]
E161210 10:12:45.913781 2327599 storage/queue.go:613  [replicate,s1,r8/1:/Table/5{2-3},@c42ca3f400] purgatory: 0 of 0 stores with an attribute matching []; likely not enough nodes in cluster
E161210 10:12:45.921788 2327598 storage/queue.go:602  [split,s1,r8/1:/Table/5{2-3},@c42ca3f400] unable to split [n1,s1,r8/1:/Table/5{2-3}] at key "/Table/54/0": key range /Table/54/0-/Table/54/0 outside of bounds of range /Table/52-/Max
I161210 10:12:45.922140 2327598 storage/split_queue.go:103  [split,s1,r9/1:/{Table/53-Max},@c42ca3f900] splitting at keys [/Table/54/0 /Table/55/0 /Table/56/0 /Table/57/0 /Table/58/0 /Table/59/0 /Table/60/0 /Table/61/0 /Table/62/0 /Table/63/0 /Table/64/0 /Table/65/0 /Table/66/0 /Table/67/0 /Table/68/0]
I161210 10:12:45.922230 2327598 storage/replica_command.go:2389  [split,s1,r9/1:/{Table/53-Max},@c42ca3f900] initiating a split of this range at key /Table/54 [r10]
E161210 10:12:45.937120 2327599 storage/queue.go:613  [replicate,s1,r9/1:/Table/5{3-4},@c42ca3f900] purgatory: 0 of 0 stores with an attribute matching []; likely not enough nodes in cluster
E161210 10:12:45.937291 2327598 storage/queue.go:602  [split,s1,r9/1:/Table/5{3-4},@c42ca3f900] unable to split [n1,s1,r9/1:/Table/5{3-4}] at key "/Table/55/0": key range /Table/55/0-/Table/55/0 outside of bounds of range /Table/53-/Max
I161210 10:12:45.937785 2327598 storage/split_queue.go:103  [split,s1,r10/1:/{Table/54-Max},@c430dc6000] splitting at keys [/Table/55/0 /Table/56/0 /Table/57/0 /Table/58/0 /Table/59/0 /Table/60/0 /Table/61/0 /Table/62/0 /Table/63/0 /Table/64/0 /Table/65/0 /Table/66/0 /Table/67/0 /Table/68/0]
I161210 10:12:45.937887 2327598 storage/replica_command.go:2389  [split,s1,r10/1:/{Table/54-Max},@c430dc6000] initiating a split of this range at key /Table/55 [r11]
E161210 10:12:45.952917 2327599 storage/queue.go:613  [replicate,s1,r10/1:/Table/5{4-5},@c430dc6000] purgatory: 0 of 0 stores with an attribute matching []; likely not enough nodes in cluster
E161210 10:12:45.953694 2327598 storage/queue.go:602  [split,s1,r10/1:/Table/5{4-5},@c430dc6000] unable to split [n1,s1,r10/1:/Table/5{4-5}] at key "/Table/56/0": key range /Table/56/0-/Table/56/0 outside of bounds of range /Table/54-/Max
I161210 10:12:45.954188 2327598 storage/split_queue.go:103  [split,s1,r11/1:/{Table/55-Max},@c430dc6500] splitting at keys [/Table/56/0 /Table/57/0 /Table/58/0 /Table/59/0 /Table/60/0 /Table/61/0 /Table/62/0 /Table/63/0 /Table/64/0 /Table/65/0 /Table/66/0 /Table/67/0 /Table/68/0]
I161210 10:12:45.954280 2327598 storage/replica_command.go:2389  [split,s1,r11/1:/{Table/55-Max},@c430dc6500] initiating a split of this range at key /Table/56 [r12]
E161210 10:12:45.990490 2327599 storage/queue.go:613  [replicate,s1,r11/1:/Table/5{5-6},@c430dc6500] purgatory: 0 of 0 stores with an attribute matching []; likely not enough nodes in cluster
E161210 10:12:45.990951 2327598 storage/queue.go:602  [split,s1,r11/1:/Table/5{5-6},@c430dc6500] unable to split [n1,s1,r11/1:/Table/5{5-6}] at key "/Table/57/0": key range /Table/57/0-/Table/57/0 outside of bounds of range /Table/55-/Max
I161210 10:12:45.995161 2327598 storage/split_queue.go:103  [split,s1,r12/1:/{Table/56-Max},@c42fb7ca00] splitting at keys [/Table/57/0 /Table/58/0 /Table/59/0 /Table/60/0 /Table/61/0 /Table/62/0 /Table/63/0 /Table/64/0 /Table/65/0 /Table/66/0 /Table/67/0 /Table/68/0]
I161210 10:12:45.995381 2327598 storage/replica_command.go:2389  [split,s1,r12/1:/{Table/56-Max},@c42fb7ca00] initiating a split of this range at key /Table/57 [r13]
E161210 10:12:46.020939 2327599 storage/queue.go:613  [replicate,s1,r12/1:/Table/5{6-7},@c42fb7ca00] purgatory: 0 of 0 stores with an attribute matching []; likely not enough nodes in cluster
E161210 10:12:46.021302 2327598 storage/queue.go:602  [split,s1,r12/1:/Table/5{6-7},@c42fb7ca00] unable to split [n1,s1,r12/1:/Table/5{6-7}] at key "/Table/58/0": key range /Table/58/0-/Table/58/0 outside of bounds of range /Table/56-/Max
I161210 10:12:46.024505 2327598 storage/split_queue.go:103  [split,s1,r13/1:/{Table/57-Max},@c430dc6a00] splitting at keys [/Table/58/0 /Table/59/0 /Table/60/0 /Table/61/0 /Table/62/0 /Table/63/0 /Table/64/0 /Table/65/0 /Table/66/0 /Table/67/0 /Table/68/0]
I161210 10:12:46.024753 2327598 storage/replica_command.go:2389  [split,s1,r13/1:/{Table/57-Max},@c430dc6a00] initiating a split of this range at key /Table/58 [r14]
E161210 10:12:46.071330 2327599 storage/queue.go:613  [replicate,s1,r13/1:/Table/5{7-8},@c430dc6a00] purgatory: 0 of 0 stores with an attribute matching []; likely not enough nodes in cluster
E161210 10:12:46.071416 2327598 storage/queue.go:602  [split,s1,r13/1:/Table/5{7-8},@c430dc6a00] unable to split [n1,s1,r13/1:/Table/5{7-8}] at key "/Table/59/0": key range /Table/59/0-/Table/59/0 outside of bounds of range /Table/57-/Max
I161210 10:12:46.071946 2327598 storage/split_queue.go:103  [split,s1,r14/1:/{Table/58-Max},@c42e2a4500] splitting at keys [/Table/59/0 /Table/60/0 /Table/61/0 /Table/62/0 /Table/63/0 /Table/64/0 /Table/65/0 /Table/66/0 /Table/67/0 /Table/68/0]
I161210 10:12:46.072045 2327598 storage/replica_command.go:2389  [split,s1,r14/1:/{Table/58-Max},@c42e2a4500] initiating a split of this range at key /Table/59 [r15]
E161210 10:12:46.087541 2327599 storage/queue.go:613  [replicate,s1,r14/1:/Table/5{8-9},@c42e2a4500] purgatory: 0 of 0 stores with an attribute matching []; likely not enough nodes in cluster
E161210 10:12:46.087774 2327598 storage/queue.go:602  [split,s1,r14/1:/Table/5{8-9},@c42e2a4500] unable to split [n1,s1,r14/1:/Table/5{8-9}] at key "/Table/60/0": key range /Table/60/0-/Table/60/0 outside of bounds of range /Table/58-/Max
I161210 10:12:46.088236 2327598 storage/split_queue.go:103  [split,s1,r15/1:/{Table/59-Max},@c42e2a4a00] splitting at keys [/Table/60/0 /Table/61/0 /Table/62/0 /Table/63/0 /Table/64/0 /Table/65/0 /Table/66/0 /Table/67/0 /Table/68/0]
I161210 10:12:46.088353 2327598 storage/replica_command.go:2389  [split,s1,r15/1:/{Table/59-Max},@c42e2a4a00] initiating a split of this range at key /Table/60 [r16]
E161210 10:12:46.109257 2327599 storage/queue.go:613  [replicate,s1,r15/1:/Table/{59-60},@c42e2a4a00] purgatory: 0 of 0 stores with an attribute matching []; likely not enough nodes in cluster
E161210 10:12:46.110449 2327598 storage/queue.go:602  [split,s1,r15/1:/Table/{59-60},@c42e2a4a00] unable to split [n1,s1,r15/1:/Table/{59-60}] at key "/Table/61/0": key range /Table/61/0-/Table/61/0 outside of bounds of range /Table/59-/Max
I161210 10:12:46.110872 2327598 storage/split_queue.go:103  [split,s1,r16/1:/{Table/60-Max},@c430dc7400] splitting at keys [/Table/61/0 /Table/62/0 /Table/63/0 /Table/64/0 /Table/65/0 /Table/66/0 /Table/67/0 /Table/68/0]
I161210 10:12:46.111068 2327598 storage/replica_command.go:2389  [split,s1,r16/1:/{Table/60-Max},@c430dc7400] initiating a split of this range at key /Table/61 [r17]
E161210 10:12:46.130787 2327598 storage/queue.go:602  [split,s1,r16/1:/Table/6{0-1},@c430dc7400] unable to split [n1,s1,r16/1:/Table/6{0-1}] at key "/Table/62/0": key range /Table/62/0-/Table/62/0 outside of bounds of range /Table/60-/Max
E161210 10:12:46.131026 2327599 storage/queue.go:613  [replicate,s1,r16/1:/Table/6{0-1},@c430dc7400] purgatory: 0 of 0 stores with an attribute matching []; likely not enough nodes in cluster
I161210 10:12:46.131252 2327598 storage/split_queue.go:103  [split,s1,r17/1:/{Table/61-Max},@c42eb40500] splitting at keys [/Table/62/0 /Table/63/0 /Table/64/0 /Table/65/0 /Table/66/0 /Table/67/0 /Table/68/0]
I161210 10:12:46.131465 2327598 storage/replica_command.go:2389  [split,s1,r17/1:/{Table/61-Max},@c42eb40500] initiating a split of this range at key /Table/62 [r18]
E161210 10:12:46.159502 2327598 storage/queue.go:602  [split,s1,r17/1:/Table/6{1-2},@c42eb40500] unable to split [n1,s1,r17/1:/Table/6{1-2}] at key "/Table/63/0": key range /Table/63/0-/Table/63/0 outside of bounds of range /Table/61-/Max
E161210 10:12:46.159569 2327599 storage/queue.go:613  [replicate,s1,r17/1:/Table/6{1-2},@c42eb40500] purgatory: 0 of 0 stores with an attribute matching []; likely not enough nodes in cluster
I161210 10:12:46.159830 2327598 storage/split_queue.go:103  [split,s1,r18/1:/{Table/62-Max},@c430dc7900] splitting at keys [/Table/63/0 /Table/64/0 /Table/65/0 /Table/66/0 /Table/67/0 /Table/68/0]
I161210 10:12:46.159925 2327598 storage/replica_command.go:2389  [split,s1,r18/1:/{Table/62-Max},@c430dc7900] initiating a split of this range at key /Table/63 [r19]
E161210 10:12:46.190659 2327599 storage/queue.go:613  [replicate,s1,r18/1:/Table/6{2-3},@c430dc7900] purgatory: 0 of 0 stores with an attribute matching []; likely not enough nodes in cluster
E161210 10:12:46.191439 2327598 storage/queue.go:602  [split,s1,r18/1:/Table/6{2-3},@c430dc7900] unable to split [n1,s1,r18/1:/Table/6{2-3}] at key "/Table/64/0": key range /Table/64/0-/Table/64/0 outside of bounds of range /Table/62-/Max
I161210 10:12:46.193344 2327598 storage/split_queue.go:103  [split,s1,r19/1:/{Table/63-Max},@c42eb40a00] splitting at keys [/Table/64/0 /Table/65/0 /Table/66/0 /Table/67/0 /Table/68/0]
I161210 10:12:46.193715 2327598 storage/replica_command.go:2389  [split,s1,r19/1:/{Table/63-Max},@c42eb40a00] initiating a split of this range at key /Table/64 [r20]
E161210 10:12:46.234111 2327599 storage/queue.go:613  [replicate,s1,r19/1:/Table/6{3-4},@c42eb40a00] purgatory: 0 of 0 stores with an attribute matching []; likely not enough nodes in cluster
E161210 10:12:46.238898 2327598 storage/queue.go:602  [split,s1,r19/1:/Table/6{3-4},@c42eb40a00] unable to split [n1,s1,r19/1:/Table/6{3-4}] at key "/Table/65/0": key range /Table/65/0-/Table/65/0 outside of bounds of range /Table/63-/Max
I161210 10:12:46.240781 2327598 storage/split_queue.go:103  [split,s1,r20/1:/{Table/64-Max},@c42240a000] splitting at keys [/Table/65/0 /Table/66/0 /Table/67/0 /Table/68/0]
I161210 10:12:46.240887 2327598 storage/replica_command.go:2389  [split,s1,r20/1:/{Table/64-Max},@c42240a000] initiating a split of this range at key /Table/65 [r21]
E161210 10:12:46.302121 2327598 storage/queue.go:602  [split,s1,r20/1:/Table/6{4-5},@c42240a000] unable to split [n1,s1,r20/1:/Table/6{4-5}] at key "/Table/66/0": key range /Table/66/0-/Table/66/0 outside of bounds of range /Table/64-/Max
E161210 10:12:46.304354 2327599 storage/queue.go:613  [replicate,s1,r20/1:/Table/6{4-5},@c42240a000] purgatory: 0 of 0 stores with an attribute matching []; likely not enough nodes in cluster
I161210 10:12:46.313326 2327598 storage/split_queue.go:103  [split,s1,r21/1:/{Table/65-Max},@c426ed2000] splitting at keys [/Table/66/0 /Table/67/0 /Table/68/0]
I161210 10:12:46.314940 2327598 storage/replica_command.go:2389  [split,s1,r21/1:/{Table/65-Max},@c426ed2000] initiating a split of this range at key /Table/66 [r22]
E161210 10:12:46.356031 2327599 storage/queue.go:613  [replicate,s1,r21/1:/Table/6{5-6},@c426ed2000] purgatory: 0 of 0 stores with an attribute matching []; likely not enough nodes in cluster
E161210 10:12:46.359120 2327598 storage/queue.go:602  [split,s1,r21/1:/Table/6{5-6},@c426ed2000] unable to split [n1,s1,r21/1:/Table/6{5-6}] at key "/Table/67/0": key range /Table/67/0-/Table/67/0 outside of bounds of range /Table/65-/Max
I161210 10:12:46.359548 2327598 storage/split_queue.go:103  [split,s1,r22/1:/{Table/66-Max},@c42240a500] splitting at keys [/Table/67/0 /Table/68/0]
I161210 10:12:46.359673 2327598 storage/replica_command.go:2389  [split,s1,r22/1:/{Table/66-Max},@c42240a500] initiating a split of this range at key /Table/67 [r23]
E161210 10:12:46.432869 2327599 storage/queue.go:613  [replicate,s1,r22/1:/Table/6{6-7},@c42240a500] purgatory: 0 of 0 stores with an attribute matching []; likely not enough nodes in cluster
E161210 10:12:46.433231 2327598 storage/queue.go:602  [split,s1,r22/1:/Table/6{6-7},@c42240a500] unable to split [n1,s1,r22/1:/Table/6{6-7}] at key "/Table/68/0": key range /Table/68/0-/Table/68/0 outside of bounds of range /Table/66-/Max
I161210 10:12:46.433885 2327598 storage/split_queue.go:103  [split,s1,r23/1:/{Table/67-Max},@c42fe27900] splitting at keys [/Table/68/0]
I161210 10:12:46.433992 2327598 storage/replica_command.go:2389  [split,s1,r23/1:/{Table/67-Max},@c42fe27900] initiating a split of this range at key /Table/68 [r24]
E161210 10:12:46.472953 2327599 storage/queue.go:613  [replicate,s1,r23/1:/Table/6{7-8},@c42fe27900] purgatory: 0 of 0 stores with an attribute matching []; likely not enough nodes in cluster
E161210 10:12:46.474461 2327599 storage/queue.go:613  [replicate,s1,r24/1:/{Table/68-Max},@c426eeaf00] purgatory: 0 of 0 stores with an attribute matching []; likely not enough nodes in cluster
I161210 10:12:46.605800 2327598 storage/split_queue.go:103  [split,s1,r24/1:/{Table/68-Max},@c426eeaf00] splitting at keys [/Table/69/0 /Table/70/0 /Table/71/0]
I161210 10:12:46.605907 2327598 storage/replica_command.go:2389  [split,s1,r24/1:/{Table/68-Max},@c426eeaf00] initiating a split of this range at key /Table/69 [r25]
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x692c91]

goroutine 2327603 [running]:
panic(0x18d8bc0, 0xc420014120)
	/usr/local/go/src/runtime/panic.go:500 +0x1a1
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).Recover(0xc42fc3b3b0)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:185 +0x6e
panic(0x18d8bc0, 0xc420014120)
	/usr/local/go/src/runtime/panic.go:458 +0x243
github.com/cockroachdb/cockroach/pkg/storage.(*NodeLiveness).GetLiveness(0x0, 0x1, 0x0, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/node_liveness.go:261 +0x41
github.com/cockroachdb/cockroach/pkg/storage.(*NodeLiveness).IsLive(0x0, 0xc400000001, 0x0, 0x0, 0x8bb2c97000)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/node_liveness.go:134 +0x37
github.com/cockroachdb/cockroach/pkg/storage.(*consistencyQueue).shouldQueue(0xc4383ae260, 0x2ad938c47350, 0xc42ad48a20, 0x7b, 0xc40000075a, 0xc429174500, 0xc42c895800, 0x1d, 0x20, 0x2, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/consistency_queue.go:77 +0xc6
github.com/cockroachdb/cockroach/pkg/storage.(*baseQueue).MaybeAdd(0xc42af474a0, 0xc429174500, 0x7b, 0x75a)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/queue.go:359 +0x24b
github.com/cockroachdb/cockroach/pkg/storage.(*replicaScanner).waitAndProcess(0xc42e8f2dc0, 0x2ad938c47000, 0xc4200943f8, 0xecfddcc1d, 0x26f93595, 0x2b2cb60, 0xc42e5b7400, 0xc42fc3b3b0, 0xc429174500, 0xecfddcc1d)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scanner.go:221 +0x324
github.com/cockroachdb/cockroach/pkg/storage.(*replicaScanner).scanLoop.func1.1(0xc429174500, 0xc436822150)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scanner.go:269 +0x8e
github.com/cockroachdb/cockroach/pkg/storage.(*storeReplicaVisitor).Visit(0xc436822150, 0xc4378cfea0)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/store.go:325 +0x303
github.com/cockroachdb/cockroach/pkg/storage.(*replicaScanner).scanLoop.func1()
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scanner.go:271 +0x2ca
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc42fc3b3b0, 0xc4377ffee0)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:196 +0x7d
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:197 +0x66

goroutine 1 [chan receive]:
testing.(*T).Run(0xc420176480, 0x1a85372, 0x1a, 0x1c78ef8, 0xc420299a01)
	/usr/local/go/src/testing/testing.go:647 +0x316
testing.RunTests.func1(0xc420176480)
	/usr/local/go/src/testing/testing.go:793 +0x6d
testing.tRunner(0xc420176480, 0xc42004fbc0)
	/usr/local/go/src/testing/testing.go:610 +0x81
testing.RunTests(0x1c7a9b8, 0x264de40, 0x168, 0x168, 0xc42032c180)
	/usr/local/go/src/testing/testing.go:799 +0x2f5
testing.(*M).Run(0xc42004fee8, 0xc420299d30)
	/usr/local/go/src/testing/testing.go:743 +0x85
github.com/cockroachdb/cockroach/pkg/storage_test.TestMain(0xc42004fee8)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/main_test.go:57 +0x1ff
main.main()
	github.com/cockroachdb/cockroach/pkg/storage/_test/_testmain.go:784 +0xc6

goroutine 17 [syscall, 1 minutes, locked to thread]:
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:2086 +0x1

goroutine 4 [chan receive]:
github.com/cockroachdb/cockroach/pkg/util/log.(*loggingT).flushDaemon(0x2b2e0c0)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/log/clog.go:1016 +0x77
created by github.com/cockroachdb/cockroach/pkg/util/log.init.1
	/go/src/github.com/cockroachdb/cockroach/pkg/util/log/clog.go:581 +0x95

goroutine 2327600 [select]:
github.com/cockroachdb/cockroach/pkg/storage.(*baseQueue).processLoop.func1()
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/queue.go:475 +0x383
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc42fc3b3b0, 0xc4377ffe80)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:196 +0x7d
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:197 +0x66

goroutine 2327279 [select]:
github.com/cockroachdb/cockroach/pkg/storage.(*Store).Start.func3()
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/store.go:1209 +0x165
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc42fc3b3b0, 0xc4383afd40)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:196 +0x7d
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:197 +0x66

goroutine 2327262 [semacquire]:
sync.runtime_notifyListWait(0xc4316cddd0, 0xc400000196)
	/usr/local/go/src/runtime/sema.go:267 +0x122
sync.(*Cond).Wait(0xc4316cddc0)
	/usr/local/go/src/sync/cond.go:57 +0x80
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).worker(0xc4379940b0, 0xc42fc3b3b0)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:212 +0xb2
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).Start.func2()
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:181 +0x33
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc42fc3b3b0, 0xc4383afb20)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:196 +0x7d
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:197 +0x66

goroutine 2327255 [semacquire]:
sync.runtime_notifyListWait(0xc4316cddd0, 0xc40000018b)
	/usr/local/go/src/runtime/sema.go:267 +0x122
sync.(*Cond).Wait(0xc4316cddc0)
	/usr/local/go/src/sync/cond.go:57 +0x80
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).worker(0xc4379940b0, 0xc42fc3b3b0)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:212 +0xb2
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).Start.func2()
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:181 +0x33
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc42fc3b3b0, 0xc4383afa40)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:196 +0x7d
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:197 +0x66

goroutine 2327266 [select]:
github.com/cockroachdb/cockroach/pkg/storage.(*Store).raftTickLoop.func1()
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/store.go:3409 +0x334
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc42fc3b3b0, 0xc42eeeb760)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:196 +0x7d
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:197 +0x66

goroutine 2327251 [semacquire]:
sync.runtime_notifyListWait(0xc4316cddd0, 0xc40000018c)
	/usr/local/go/src/runtime/sema.go:267 +0x122
sync.(*Cond).Wait(0xc4316cddc0)
	/usr/local/go/src/sync/cond.go:57 +0x80
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).worker(0xc4379940b0, 0xc42fc3b3b0)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:212 +0xb2
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).Start.func2()
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:181 +0x33
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc42fc3b3b0, 0xc4383af9c0)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:196 +0x7d
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:197 +0x66

goroutine 2327250 [semacquire]:
sync.runtime_notifyListWait(0xc4316cddd0, 0xc400000193)
	/usr/local/go/src/runtime/sema.go:267 +0x122
sync.(*Cond).Wait(0xc4316cddc0)
	/usr/local/go/src/sync/cond.go:57 +0x80
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).worker(0xc4379940b0, 0xc42fc3b3b0)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:212 +0xb2
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).Start.func2()
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:181 +0x33
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc42fc3b3b0, 0xc4383af9a0)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:196 +0x7d
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:197 +0x66

goroutine 2327597 [select]:
github.com/cockroachdb/cockroach/pkg/storage.(*baseQueue).processLoop.func1()
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/queue.go:475 +0x383
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc42fc3b3b0, 0xc4377ffe20)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:196 +0x7d
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:197 +0x66

goroutine 2327253 [semacquire]:
sync.runtime_notifyListWait(0xc4316cddd0, 0xc400000197)
	/usr/local/go/src/runtime/sema.go:267 +0x122
sync.(*Cond).Wait(0xc4316cddc0)
	/usr/local/go/src/sync/cond.go:57 +0x80
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).worker(0xc4379940b0, 0xc42fc3b3b0)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:212 +0xb2
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).Start.func2()
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:181 +0x33
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc42fc3b3b0, 0xc4383afa00)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:196 +0x7d
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:197 +0x66

goroutine 2327265 [semacquire]:
sync.runtime_Semacquire(0xc437994154)
	/usr/local/go/src/runtime/sema.go:47 +0x30
sync.(*WaitGroup).Wait(0xc437994148)
	/usr/local/go/src/sync/waitgroup.go:131 +0x97
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).Wait(0xc4379940b0)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:187 +0x34
github.com/cockroachdb/cockroach/pkg/storage.(*Store).processRaft.func1()
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/store.go:3383 +0x3a
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc42fc3b3b0, 0xc42eeeb750)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:196 +0x7d
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:197 +0x66

goroutine 2368784 [runnable]:
sync.runtime_Semacquire(0xc42e5b7414)
	/usr/local/go/src/runtime/sema.go:47 +0x30
sync.(*Mutex).Lock(0xc42e5b7410)
	/usr/local/go/src/sync/mutex.go:85 +0xd0
sync.(*Mutex).Lock-fm()
	/go/src/github.com/cockroachdb/cockroach/vendor/github.com/sasha-s/go-deadlock/deadlock.go:55 +0x2a
github.com/cockroachdb/cockroach/vendor/github.com/sasha-s/go-deadlock.lock.func1(0xc422baf3a0, 0xc4261221e0)
	/go/src/github.com/cockroachdb/cockroach/vendor/github.com/sasha-s/go-deadlock/deadlock.go:151 +0x27
created by github.com/cockroachdb/cockroach/vendor/github.com/sasha-s/go-deadlock.lock
	/go/src/github.com/cockroachdb/cockroach/vendor/github.com/sasha-s/go-deadlock/deadlock.go:153 +0xf3

goroutine 2327249 [semacquire]:
sync.runtime_notifyListWait(0xc4316cddd0, 0xc400000198)
	/usr/local/go/src/runtime/sema.go:267 +0x122
sync.(*Cond).Wait(0xc4316cddc0)
	/usr/local/go/src/sync/cond.go:57 +0x80
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).worker(0xc4379940b0, 0xc42fc3b3b0)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:212 +0xb2
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).Start.func2()
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:181 +0x33
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc42fc3b3b0, 0xc4383af980)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:196 +0x7d
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:197 +0x66

goroutine 2327257 [semacquire]:
sync.runtime_notifyListWait(0xc4316cddd0, 0xc40000018a)
	/usr/local/go/src/runtime/sema.go:267 +0x122
sync.(*Cond).Wait(0xc4316cddc0)
	/usr/local/go/src/sync/cond.go:57 +0x80
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).worker(0xc4379940b0, 0xc42fc3b3b0)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:212 +0xb2
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).Start.func2()
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:181 +0x33
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc42fc3b3b0, 0xc4383afa80)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:196 +0x7d
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:197 +0x66

goroutine 2326981 [select]:
github.com/cockroachdb/cockroach/pkg/storage.(*Replica).tryAddWriteCmd(0xc429174500, 0x2ad938c47350, 0xc4326b9740, 0x7b, 0x752, 0x100000001, 0x1, 0x1, 0x0, 0x0, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/replica.go:2021 +0xb17
github.com/cockroachdb/cockroach/pkg/storage.(*Replica).addWriteCmd(0xc429174500, 0x2ad938c47350, 0xc4326b9740, 0x7b, 0x752, 0x100000001, 0x1, 0x1, 0x0, 0x0, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/replica.go:1847 +0x90
github.com/cockroachdb/cockroach/pkg/storage.(*Replica).Send(0xc429174500, 0x2ad938c47350, 0xc4326b9740, 0x7b, 0x752, 0x100000001, 0x1, 0x1, 0x0, 0x0, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/replica.go:1299 +0x222
github.com/cockroachdb/cockroach/pkg/storage.(*Store).Send(0xc42ff59c00, 0x2ad938c47350, 0xc4326b96b0, 0x7b, 0x752, 0x100000001, 0x1, 0x1, 0x0, 0x0, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/store.go:2479 +0x6c5
github.com/cockroachdb/cockroach/pkg/storage.(*Stores).Send(0xc42dbd7f20, 0x2ad938c47350, 0xc4326b95f0, 0x0, 0x0, 0x100000001, 0x1, 0x1, 0x0, 0x0, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/stores.go:187 +0x202
github.com/cockroachdb/cockroach/pkg/kv.(*senderTransport).SendNext(0xc4384445a0, 0xc42e02ae40)
	/go/src/github.com/cockroachdb/cockroach/pkg/kv/transport.go:309 +0x1f8
github.com/cockroachdb/cockroach/pkg/kv.(*DistSender).sendToReplicas(0xc42af46d20, 0x2ad938c472d8, 0xc4260d24c0, 0x1dcd6500, 0xc42fe8f050, 0xc42af46d58, 0x1, 0xc43120d440, 0x1, 0x1, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/kv/dist_sender.go:1142 +0x35d
github.com/cockroachdb/cockroach/pkg/kv.(*DistSender).sendRPC(0xc42af46d20, 0x2ad938c472d8, 0xc4260d24c0, 0x1, 0xc43120d440, 0x1, 0x1, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/kv/dist_sender.go:410 +0x372
github.com/cockroachdb/cockroach/pkg/kv.(*DistSender).sendSingleRange(0xc42af46d20, 0x2ad938c47350, 0xc42b02acc0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/kv/dist_sender.go:479 +0x16e
github.com/cockroachdb/cockroach/pkg/kv.(*DistSender).sendPartialBatch(0xc42af46d20, 0x2ad938c47350, 0xc42b02acc0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/kv/dist_sender.go:931 +0x2c7
github.com/cockroachdb/cockroach/pkg/kv.(*DistSender).divideAndSendBatchToRanges(0xc42af46d20, 0x2ad938c47350, 0xc42b02acc0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/kv/dist_sender.go:810 +0x41f
github.com/cockroachdb/cockroach/pkg/kv.(*DistSender).Send(0xc42af46d20, 0x2ad938c47350, 0xc42b02acc0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/kv/dist_sender.go:625 +0x2d8
github.com/cockroachdb/cockroach/pkg/kv.(*TxnCoordSender).Send(0xc42e8f28c0, 0x2ad938c47350, 0xc42b02acc0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/kv/txn_coord_sender.go:418 +0x7e9
github.com/cockroachdb/cockroach/pkg/internal/client.(*DB).send(0xc437ae7810, 0x2ad938c47350, 0xc42b02acc0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/internal/client/db.go:513 +0xbf
github.com/cockroachdb/cockroach/pkg/internal/client.(*DB).Run.func1(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/internal/client/db.go:447 +0x6e
github.com/cockroachdb/cockroach/pkg/internal/client.sendAndFill(0xc43120d2c0, 0xc43317d200, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/pkg/internal/client/db.go:418 +0x168
github.com/cockroachdb/cockroach/pkg/internal/client.(*DB).Run(0xc437ae7810, 0x2ad938c47350, 0xc42b02acc0, 0xc43317d200, 0x2672401, 0xc4326b9470)
	/go/src/github.com/cockroachdb/cockroach/pkg/internal/client/db.go:449 +0xac
github.com/cockroachdb/cockroach/pkg/storage.(*intentResolver).resolveIntents.func1(0x1992580, 0xc4326b9470)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/intent_resolver.go:450 +0x4c
github.com/cockroachdb/cockroach/pkg/storage.(*intentResolver).resolveIntents(0xc42f795ec0, 0x2ad938c47350, 0xc42b02acc0, 0xc42e7c5200, 0x2, 0x2, 0x0, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/intent_resolver.go:461 +0x5de
github.com/cockroachdb/cockroach/pkg/storage.(*intentResolver).processWriteIntentError(0xc42f795ec0, 0x2ad938c47350, 0xc42b02acc0, 0xc42547eaa0, 0x2672560, 0xc42b02aab0, 0x7b, 0x746, 0x100000001, 0x1, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/intent_resolver.go:98 +0x206
github.com/cockroachdb/cockroach/pkg/storage.(*Store).Send(0xc42ff59c00, 0x2ad938c47350, 0xc42b02acc0, 0x7b, 0x745, 0x100000001, 0x1, 0x1, 0x0, 0x0, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/store.go:2516 +0xc20
github.com/cockroachdb/cockroach/pkg/storage.(*Stores).Send(0xc42dbd7f20, 0x2ad938c47350, 0xc42b02ac00, 0x0, 0x0, 0x100000001, 0x1, 0x1, 0x0, 0x0, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/stores.go:187 +0x202
github.com/cockroachdb/cockroach/pkg/kv.(*senderTransport).SendNext(0xc42c0554a0, 0xc426221980)
	/go/src/github.com/cockroachdb/cockroach/pkg/kv/transport.go:309 +0x1f8
github.com/cockroachdb/cockroach/pkg/kv.(*DistSender).sendToReplicas(0xc42af46d20, 0x2ad938c472d8, 0xc424a2bf80, 0x1dcd6500, 0xc42fe8f050, 0xc42af46d58, 0x1, 0xc42b2942c0, 0x1, 0x1, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/kv/dist_sender.go:1142 +0x35d
github.com/cockroachdb/cockroach/pkg/kv.(*DistSender).sendRPC(0xc42af46d20, 0x2ad938c472d8, 0xc424a2bf80, 0x1, 0xc42b2942c0, 0x1, 0x1, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/kv/dist_sender.go:410 +0x372
github.com/cockroachdb/cockroach/pkg/kv.(*DistSender).sendSingleRange(0xc42af46d20, 0x2ad938c47350, 0xc42b02aae0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/kv/dist_sender.go:479 +0x16e
github.com/cockroachdb/cockroach/pkg/kv.(*DistSender).sendPartialBatch(0xc42af46d20, 0x2ad938c47350, 0xc42b02aae0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/kv/dist_sender.go:931 +0x2c7
github.com/cockroachdb/cockroach/pkg/kv.(*DistSender).divideAndSendBatchToRanges(0xc42af46d20, 0x2ad938c47350, 0xc42b02aae0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/kv/dist_sender.go:810 +0x41f
github.com/cockroachdb/cockroach/pkg/kv.(*DistSender).Send(0xc42af46d20, 0x2ad938c47350, 0xc42b02aae0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/kv/dist_sender.go:625 +0x2d8
github.com/cockroachdb/cockroach/pkg/kv.(*TxnCoordSender).Send(0xc42e8f28c0, 0x2ad938c47350, 0xc42b02aae0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/kv/txn_coord_sender.go:418 +0x7e9
github.com/cockroachdb/cockroach/pkg/internal/client.(*DB).send(0xc437ae7810, 0x2ad938c47000, 0xc420094410, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/internal/client/db.go:513 +0xbf
github.com/cockroachdb/cockroach/pkg/internal/client.(*DB).Run.func1(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/internal/client/db.go:447 +0x6e
github.com/cockroachdb/cockroach/pkg/internal/client.sendAndFill(0xc42b294140, 0xc437b65200, 0x0, 0xc42b294120)
	/go/src/github.com/cockroachdb/cockroach/pkg/internal/client/db.go:418 +0x168
github.com/cockroachdb/cockroach/pkg/internal/client.(*DB).Run(0xc437ae7810, 0x2ad938c47000, 0xc420094410, 0xc437b65200, 0xc42b294120, 0xc42b2940a0)
	/go/src/github.com/cockroachdb/cockroach/pkg/internal/client/db.go:449 +0xac
github.com/cockroachdb/cockroach/pkg/internal/client.(*DB).scan(0xc437ae7810, 0x2ad938c47000, 0xc420094410, 0x199cdc0, 0xc42b294100, 0x199cdc0, 0xc42b294120, 0x0, 0x2b294100, 0xc422235968, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/internal/client/db.go:307 +0x105
github.com/cockroachdb/cockroach/pkg/internal/client.(*DB).Scan(0xc437ae7810, 0x2ad938c47000, 0xc420094410, 0x199cdc0, 0xc42b294100, 0x199cdc0, 0xc42b294120, 0x0, 0x1c72069, 0xc41fdaea1b, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/internal/client/db.go:318 +0x9a
github.com/cockroachdb/cockroach/pkg/storage_test.TestStoreRangeSystemSplits.func2.1(0xecfddcc1e, 0xc42629abfb)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/client_split_test.go:867 +0x15e
github.com/cockroachdb/cockroach/pkg/util.RetryForDuration(0xa7a358200, 0xc422235c80, 0xc422235bb8, 0x270)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/retry.go:31 +0xcd
github.com/cockroachdb/cockroach/pkg/testutils.SucceedsSoonDepth(0x1, 0x2675ea0, 0xc4312a2c00, 0xc422235c80)
	/go/src/github.com/cockroachdb/cockroach/pkg/testutils/soon.go:41 +0x41
github.com/cockroachdb/cockroach/pkg/storage_test.TestStoreRangeSystemSplits.func2(0x16)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/client_split_test.go:879 +0x67d
github.com/cockroachdb/cockroach/pkg/storage_test.TestStoreRangeSystemSplits(0xc4312a2c00)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/client_split_test.go:897 +0x448
testing.tRunner(0xc4312a2c00, 0x1c78ef8)
	/usr/local/go/src/testing/testing.go:610 +0x81
created by testing.(*T).Run
	/usr/local/go/src/testing/testing.go:646 +0x2ec

goroutine 2327267 [select]:
github.com/cockroachdb/cockroach/pkg/storage.(*Store).startCoalescedHeartbeatsLoop.func1()
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/store.go:3440 +0x167
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc42fc3b3b0, 0xc42eeeb770)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:196 +0x7d
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:197 +0x66

goroutine 2327598 [select]:
github.com/cockroachdb/cockroach/vendor/github.com/sasha-s/go-deadlock.lock(0xc422baf3a0, 0x18e1800, 0xc42e5b7410)
	/go/src/github.com/cockroachdb/cockroach/vendor/github.com/sasha-s/go-deadlock/deadlock.go:157 +0xc5d
github.com/cockroachdb/cockroach/vendor/github.com/sasha-s/go-deadlock.(*Mutex).Lock(0xc42e5b7410)
	/go/src/github.com/cockroachdb/cockroach/vendor/github.com/sasha-s/go-deadlock/deadlock.go:55 +0x78
github.com/cockroachdb/cockroach/pkg/util/hlc.(*Clock).Update(0xc42e5b7400, 0x7b, 0xc40000073d, 0x0, 0xc400000000)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/hlc/hlc.go:195 +0x5c
github.com/cockroachdb/cockroach/pkg/kv.(*DistSender).sendSingleRange(0xc42af46d20, 0x2ad938c5a9f8, 0xc42655c6c0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0xc428b65140, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/kv/dist_sender.go:486 +0x1dd
github.com/cockroachdb/cockroach/pkg/kv.(*DistSender).sendPartialBatch(0xc42af46d20, 0x2ad938c5a9f8, 0xc42655c6c0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0xc428b65140, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/kv/dist_sender.go:931 +0x2c7
github.com/cockroachdb/cockroach/pkg/kv.(*DistSender).divideAndSendBatchToRanges(0xc42af46d20, 0x2ad938c5a9f8, 0xc42655c6c0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0xc428b65140, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/kv/dist_sender.go:810 +0x41f
github.com/cockroachdb/cockroach/pkg/kv.(*DistSender).Send(0xc42af46d20, 0x2ad938c5a9f8, 0xc42655c6c0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0xc428b65080, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/kv/dist_sender.go:625 +0x2d8
github.com/cockroachdb/cockroach/pkg/kv.(*TxnCoordSender).Send(0xc42e8f28c0, 0x2ad938c5a9f8, 0xc42655c6c0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0xc42f78e888, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/kv/txn_coord_sender.go:418 +0x7e9
github.com/cockroachdb/cockroach/pkg/internal/client.(*Txn).sendInternal(0xc42f78e840, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0xc42f78e888, 0x0, 0x0, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/internal/client/txn.go:587 +0xfd
github.com/cockroachdb/cockroach/pkg/internal/client.(*Txn).send(0xc42f78e840, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/internal/client/txn.go:711 +0x498
github.com/cockroachdb/cockroach/pkg/internal/client.(*Txn).(github.com/cockroachdb/cockroach/pkg/internal/client.send)-fm(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/internal/client/txn.go:313 +0x58
github.com/cockroachdb/cockroach/pkg/internal/client.sendAndFill(0xc42c0951a8, 0xc43317cc00, 0x0, 0xc4239323b0)
	/go/src/github.com/cockroachdb/cockroach/pkg/internal/client/db.go:418 +0x168
github.com/cockroachdb/cockroach/pkg/internal/client.(*Txn).Run(0xc42f78e840, 0xc43317cc00, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/pkg/internal/client/txn.go:313 +0xc6
github.com/cockroachdb/cockroach/pkg/storage.(*Replica).adminSplitWithDescriptor.func1(0xc42f78e840, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/replica_command.go:2458 +0x6fd
github.com/cockroachdb/cockroach/pkg/internal/client.(*DB).Txn.func1(0xc42f78e840, 0xc425846e60, 0x2, 0x1abdcbf)
	/go/src/github.com/cockroachdb/cockroach/pkg/internal/client/db.go:468 +0x2f
github.com/cockroachdb/cockroach/pkg/internal/client.(*Txn).Exec(0xc42f78e840, 0xc425840101, 0x0, 0xc425846e40, 0x26532c0, 0xc426451800)
	/go/src/github.com/cockroachdb/cockroach/pkg/internal/client/txn.go:520 +0x215
github.com/cockroachdb/cockroach/pkg/internal/client.(*DB).Txn(0xc437ae7810, 0x2ad938c5a9f8, 0xc42655c6c0, 0xc4265a43c0, 0xc42c0958a0, 0x2)
	/go/src/github.com/cockroachdb/cockroach/pkg/internal/client/db.go:469 +0x1fa
github.com/cockroachdb/cockroach/pkg/storage.(*Replica).adminSplitWithDescriptor(0xc426eeaf00, 0x2ad938c5a9f8, 0xc42655c6c0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0xc425846978, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/replica_command.go:2459 +0xab4
github.com/cockroachdb/cockroach/pkg/storage.(*splitQueue).process(0xc42ef65d40, 0x2ad938c5a9f8, 0xc42655c6c0, 0xc42b19a6c0, 0xc426eeaf00, 0xc42c895800, 0x1d, 0x20, 0x0, 0x2)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/split_queue.go:111 +0x290
github.com/cockroachdb/cockroach/pkg/storage.(*baseQueue).processReplica(0xc42af46f00, 0x2ad938c47350, 0xc42b19a600, 0xc426eeaf00, 0xc42e5b7400, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/queue.go:579 +0x3e6
github.com/cockroachdb/cockroach/pkg/storage.(*baseQueue).processLoop.func1.2()
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/queue.go:499 +0xf2
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunTask(0xc42fc3b3b0, 0xc42c095e30, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:224 +0x100
github.com/cockroachdb/cockroach/pkg/storage.(*baseQueue).processLoop.func1()
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/queue.go:506 +0x34d
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc42fc3b3b0, 0xc4377ffe40)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:196 +0x7d
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:197 +0x66

goroutine 2326989 [chan receive]:
github.com/cockroachdb/cockroach/pkg/storage/engine.(*RocksDB).open.func1(0xc437ae6e60)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/engine/rocksdb.go:373 +0x44
created by github.com/cockroachdb/cockroach/pkg/storage/engine.(*RocksDB).open
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/engine/rocksdb.go:374 +0x702

goroutine 2327281 [select]:
github.com/cockroachdb/cockroach/pkg/storage.(*Store).startGossip.func1()
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/store.go:1295 +0x39b
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc42fc3b3b0, 0xc436822cc0)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:196 +0x7d
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:197 +0x66

goroutine 2366845 [select]:
github.com/cockroachdb/cockroach/pkg/kv.(*TxnCoordSender).heartbeatLoop(0xc42e8f28c0, 0x2ad938c47350, 0xc42d634960, 0x95462b29c09a1663, 0xe922510b9ab2398d)
	/go/src/github.com/cockroachdb/cockroach/pkg/kv/txn_coord_sender.go:647 +0x41f
github.com/cockroachdb/cockroach/pkg/kv.(*TxnCoordSender).updateState.func2(0x2ad938c47350, 0xc42d634930)
	/go/src/github.com/cockroachdb/cockroach/pkg/kv/txn_coord_sender.go:919 +0x51
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunAsyncTask.func1(0xc42fc3b3b0, 0x23492b3, 0x16, 0x398, 0x26752c0, 0xc42b292640, 0xc43852a3a0, 0x2ad938c47350, 0xc42d634930)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:264 +0xdf
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunAsyncTask
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:265 +0x234

goroutine 2327252 [semacquire]:
sync.runtime_notifyListWait(0xc4316cddd0, 0xc40000018d)
	/usr/local/go/src/runtime/sema.go:267 +0x122
sync.(*Cond).Wait(0xc4316cddc0)
	/usr/local/go/src/sync/cond.go:57 +0x80
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).worker(0xc4379940b0, 0xc42fc3b3b0)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:212 +0xb2
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).Start.func2()
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:181 +0x33
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc42fc3b3b0, 0xc4383af9e0)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:196 +0x7d
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:197 +0x66

goroutine 2327254 [semacquire]:
sync.runtime_notifyListWait(0xc4316cddd0, 0xc400000195)
	/usr/local/go/src/runtime/sema.go:267 +0x122
sync.(*Cond).Wait(0xc4316cddc0)
	/usr/local/go/src/sync/cond.go:57 +0x80
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).worker(0xc4379940b0, 0xc42fc3b3b0)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:212 +0xb2
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).Start.func2()
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:181 +0x33
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc42fc3b3b0, 0xc4383afa20)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:196 +0x7d
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:197 +0x66

goroutine 2327259 [semacquire]:
sync.runtime_notifyListWait(0xc4316cddd0, 0xc40000018e)
	/usr/local/go/src/runtime/sema.go:267 +0x122
sync.(*Cond).Wait(0xc4316cddc0)
	/usr/local/go/src/sync/cond.go:57 +0x80
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).worker(0xc4379940b0, 0xc42fc3b3b0)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:212 +0xb2
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).Start.func2()
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:181 +0x33
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc42fc3b3b0, 0xc4383afac0)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:196 +0x7d
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:197 +0x66

goroutine 2327280 [select]:
github.com/cockroachdb/cockroach/pkg/storage.(*Store).startGossip.func1()
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/store.go:1295 +0x39b
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc42fc3b3b0, 0xc436822c90)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:196 +0x7d
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:197 +0x66

goroutine 2327602 [select]:
github.com/cockroachdb/cockroach/pkg/storage.(*baseQueue).processLoop.func1()
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/queue.go:475 +0x383
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc42fc3b3b0, 0xc4377ffec0)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:196 +0x7d
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:197 +0x66

goroutine 2327263 [semacquire]:
sync.runtime_notifyListWait(0xc4316cddd0, 0xc400000192)
	/usr/local/go/src/runtime/sema.go:267 +0x122
sync.(*Cond).Wait(0xc4316cddc0)
	/usr/local/go/src/sync/cond.go:57 +0x80
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).worker(0xc4379940b0, 0xc42fc3b3b0)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:212 +0xb2
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).Start.func2()
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:181 +0x33
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc42fc3b3b0, 0xc4383afb40)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:196 +0x7d
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:197 +0x66

goroutine 2327030 [select]:
github.com/cockroachdb/cockroach/pkg/kv.(*TxnCoordSender).printStatsLoop(0xc42e8f28c0, 0x2ad938c47000, 0xc4200943f8)
	/go/src/github.com/cockroachdb/cockroach/pkg/kv/txn_coord_sender.go:209 +0xbd3
github.com/cockroachdb/cockroach/pkg/kv.NewTxnCoordSender.func1()
	/go/src/github.com/cockroachdb/cockroach/pkg/kv/txn_coord_sender.go:193 +0x98
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc42fc3b3b0, 0xc42ef648b0)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:196 +0x7d
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:197 +0x66

goroutine 2327258 [runnable]:
sync.runtime_notifyListWait(0xc4316cddd0, 0xc400000189)
	/usr/local/go/src/runtime/sema.go:267 +0x122
sync.(*Cond).Wait(0xc4316cddc0)
	/usr/local/go/src/sync/cond.go:57 +0x80
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).worker(0xc4379940b0, 0xc42fc3b3b0)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:212 +0xb2
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).Start.func2()
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:181 +0x33
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc42fc3b3b0, 0xc4383afaa0)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:196 +0x7d
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:197 +0x66

goroutine 2327264 [semacquire]:
sync.runtime_notifyListWait(0xc4316cddd0, 0xc400000194)
	/usr/local/go/src/runtime/sema.go:267 +0x122
sync.(*Cond).Wait(0xc4316cddc0)
	/usr/local/go/src/sync/cond.go:57 +0x80
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).worker(0xc4379940b0, 0xc42fc3b3b0)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:212 +0xb2
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).Start.func2()
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:181 +0x33
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc42fc3b3b0, 0xc4383afb60)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:196 +0x7d
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:197 +0x66

goroutine 2326991 [chan receive]:
github.com/cockroachdb/cockroach/pkg/rpc.NewContext.func1()
	/go/src/github.com/cockroachdb/cockroach/pkg/rpc/context.go:137 +0x76
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc42fc3b3b0, 0xc42f794140)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:196 +0x7d
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:197 +0x66

goroutine 2327260 [semacquire]:
sync.runtime_notifyListWait(0xc4316cddd0, 0xc40000018f)
	/usr/local/go/src/runtime/sema.go:267 +0x122
sync.(*Cond).Wait(0xc4316cddc0)
	/usr/local/go/src/sync/cond.go:57 +0x80
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).worker(0xc4379940b0, 0xc42fc3b3b0)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:212 +0xb2
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).Start.func2()
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:181 +0x33
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc42fc3b3b0, 0xc4383afae0)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:196 +0x7d
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:197 +0x66

goroutine 2327261 [semacquire]:
sync.runtime_notifyListWait(0xc4316cddd0, 0xc400000191)
	/usr/local/go/src/runtime/sema.go:267 +0x122
sync.(*Cond).Wait(0xc4316cddc0)
	/usr/local/go/src/sync/cond.go:57 +0x80
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).worker(0xc4379940b0, 0xc42fc3b3b0)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:212 +0xb2
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).Start.func2()
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:181 +0x33
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc42fc3b3b0, 0xc4383afb00)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:196 +0x7d
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:197 +0x66

goroutine 2327601 [runnable]:
github.com/cockroachdb/cockroach/pkg/storage.(*baseQueue).processLoop.func1()
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/queue.go:475 +0x383
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc42fc3b3b0, 0xc4377ffea0)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:196 +0x7d
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:197 +0x66

goroutine 2328457 [select]:
github.com/cockroachdb/cockroach/pkg/storage.(*baseQueue).maybeAddToPurgatory.func2()
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/queue.go:637 +0xaef
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc42fc3b3b0, 0xc42f68d1c0)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:196 +0x7d
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:197 +0x66

goroutine 2327632 [select]:
github.com/cockroachdb/cockroach/pkg/storage.(*idAllocator).start.func1()
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/id_alloc.go:133 +0x7c8
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc42fc3b3b0, 0xc42ee77c90)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:196 +0x7d
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:197 +0x66

goroutine 2327599 [select]:
github.com/cockroachdb/cockroach/pkg/storage.(*baseQueue).processLoop.func1()
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/queue.go:475 +0x383
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc42fc3b3b0, 0xc4377ffe60)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:196 +0x7d
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:197 +0x66

goroutine 2327256 [semacquire]:
sync.runtime_notifyListWait(0xc4316cddd0, 0xc400000190)
	/usr/local/go/src/runtime/sema.go:267 +0x122
sync.(*Cond).Wait(0xc4316cddc0)
	/usr/local/go/src/sync/cond.go:57 +0x80
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).worker(0xc4379940b0, 0xc42fc3b3b0)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:212 +0xb2
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).Start.func2()
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:181 +0x33
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc42fc3b3b0, 0xc4383afa60)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:196 +0x7d
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:197 +0x66

goroutine 2327248 [chan receive]:
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).Start.func1()
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:171 +0x55
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc42fc3b3b0, 0xc4383af960)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:196 +0x7d
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:197 +0x66


ERROR: exit status 2

make: *** [stress] Error 1
1 runs completed, 1 failures, over 1m0s
Makefile:138: recipe for target 'stress' failed
```

### PR DESCRIPTION
**Pull request by bdarnell**
The fix in #12224 did nothing because disabling the queue prevents calls
to process() but left the calls to shouldQueue, which were crashing.
Disabling a queue now prevents calls to shouldQueue.

consistencyQueue.shouldQueue is now robust against a missing
NodeLiveness instead of requiring all tests that may omit NodeLiveness
to explicitly disable the queue.

Fixes #12248

---
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/12404)

### CODE REVIEW

**Comment by petermattis** [comment]
:lgtm:

---

Review status: 0 of 5 files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/12404#-:-KZ1wXWJaLpzRex4kiad:bnfp4nl)*

File: pkg/storage/queue.go [hunk 1]
```diff
@@ -323,7 +323,7 @@ func (bq *baseQueue) MaybeAdd(repl *Replica, now hlc.Timestamp) {
 	bq.mu.Lock()
 	defer bq.mu.Unlock()
 
-	if bq.mu.stopped {
+	if bq.mu.stopped && bq.mu.disabled {
```
Comment (a-robinson) [inline pkg/storage/queue.go]: How is this related?

**Review by a-robinson — COMMENTED** [review]
LGTM

File: pkg/storage/queue.go (hunk 1 above)
Comment (bdarnell) [inline pkg/storage/queue.go]: If this line had been in place, then #12224 would have been sufficient as it would have prevented the calls into shouldQueue which panicked. However, I decided to make the rest of this change (essentially undoing #12224 in favor of a different solution) because it seems more robust to fix consistencyQueue to not panic than to require some set of tests to disable the consistency queue (were the tests affected by #12224 the only ones, or were there other tests that were at risk but for whatever reasons hadn't manifested the panic?)

**Comment by tamird** [comment]
Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[pkg/storage/queue.go, line 326 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/12404#-KZ14mLZr5ITpPZjo-4B-r1-326:-KZ2PnwsvFlXGL059G5I:b1b0j2f) ([raw file](https://github.com/cockroachdb/cockroach/blob/6adbe47d957abfd535888a6ec7c886cbcc88b5e4/pkg/storage/queue.go#L326)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

If this line had been in place, then #12224 would have been sufficient as it would have prevented the calls into shouldQueue which panicked. However, I decided to make the rest of this change (essentially undoing #12224 in favor of a different solution) because it seems more robust to fix consistencyQueue to not panic than to require some set of tests to disable the consistency queue (were the tests affected by #12224 the only ones, or were there other tests that were at risk but for whatever reasons hadn't manifested the panic?)
</blockquote></details>

Shouldn't this be `||`?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/12404)*

**Comment by bdarnell** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[pkg/storage/queue.go, line 326 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/12404#-KZ14mLZr5ITpPZjo-4B-r1-326:-KZ4ifz3i9ebO9lDMmb9:bl9dlft) ([raw file](https://github.com/cockroachdb/cockroach/blob/6adbe47d957abfd535888a6ec7c886cbcc88b5e4/pkg/storage/queue.go#L326)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

Shouldn't this be `||`?
</blockquote></details>

Yes. Oops. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/12404)*
