### PR TITLE
util: prioritize cancellations in retry loop

### LINKED ISSUE #154764: util/retry: TestRetryWithMaxDuration failed
util/retry.TestRetryWithMaxDuration [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Ci_TestsAwsLinuxArm64_UnitTests/20557888?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Ci_TestsAwsLinuxArm64_UnitTests/20557888?buildTab=artifacts#/) on release-25.4 @ [0af2a332521ffbc302e71faff74fe112a81cc35e](https://github.com/cockroachdb/cockroach/commits/0af2a332521ffbc302e71faff74fe112a81cc35e):

```
=== RUN   TestRetryWithMaxDuration
--- FAIL: TestRetryWithMaxDuration (0.00s)
=== RUN   TestRetryWithMaxDuration/errors_with_opt.Closer_that_is_closed
    retry_test.go:554: 
        	Error Trace:	pkg/util/retry/retry_test.go:554
        	Error:      	"23ms" is not less than or equal to "20ms"
        	Test:       	TestRetryWithMaxDuration/errors_with_opt.Closer_that_is_closed
        	Messages:   	expected time spent to be less than or equal to max expected time spent
--- FAIL: TestRetryWithMaxDuration/errors_with_opt.Closer_that_is_closed (0.00s)
```
<details><summary>Help</summary>
<p>

See also: [How To Investigate a Go Test Failure \(internal\)](https://cockroachlabs.atlassian.net/l/c/HgfXfJgM)
</p>
</details>
/cc @cockroachdb/unowned
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*TestRetryWithMaxDuration.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/bazci/githubpost/issues)

</sub>

Jira issue: CRDB-55107

### PR DESCRIPTION
**Pull request by sanki92**
This commit teaches `util.Retry` to prioritize context cancellations and stoppers over retry attempts. This ensures more consistent behaviors and reduces test flakes.

Fixes: #154764

Release note: None

### CODE REVIEW

**Review by kev-cao — APPROVED** [review]
This LGTM! While this test does use a manually controlled clock, these two particular subtests have some variability due to the `select` statement randomly picking between the stopped channels versus the clock's timer.

Increasing the timing tolerance like this will decrease the amount of flakes without impacting the correctness of the test, although to fully resolve the issue we'd probably want to look into repeatedly advancing the manual clock by some fraction of the backoff to avoid ties.

**Comment by sanki92** [comment]
@yuzefovich Thanks for the feedback! I appreciate @kev-cao confirming the fix approach.

I notice the CI failures seem to be infrastructure-related rather than issues with the code changes. Should I wait for these to resolve, or is there anything specific I should address?

Also, thank you for pointing me toward #41815 for feature work - I'll definitely explore those opportunities for more substantial contributions!

**Review by kev-cao — CHANGES_REQUESTED** [review]
Well the CI issues were a little weird since those subtests were failing under duress despite the fact that they should be skipped under duress.

That being said, while I was investigating this, I realized that there is a better solution here that eliminates the need to skip running these tests under duress. In `retry.Next`, we currently perform a blocking `select` on the backoff timer, context cancellation, and stopper.

This does mean that with shorter backoffs, context cancellation/stoppers are not prioritized in the event that all three channels are ready. This is the reason why we are running into these flakes.

If we instead do a two-stage `select`, a non-blocking `select` on the context/stopper first before running our blocking `select`, this correctly prioritizes context cancellation/stops and also prevents these flakes entirely and we can delete the code for skipping under duress.

@sanki92 If you'd like to give this a try, you are more than welcome to. Otherwise I can put up a quick PR for it.

File: pkg/util/retry/retry_test.go [hunk 1]
```diff
@@ -476,9 +475,6 @@ func TestRetryWithMaxDuration(t *testing.T) {
 			},
 			maxExpectedTimeSpent: time.Millisecond * 20,
```
Comment (kev-cao) [inline pkg/util/retry/retry_test.go]: We'll also want to get rid of `maxExpectedTimeSpent`. This was originally added because of the non-determinism with `select` priority. But with this change, we now will know exactly how long each test should take.

File: pkg/util/retry/retry_test.go [hunk 2]
```diff
@@ -496,18 +492,11 @@ func TestRetryWithMaxDuration(t *testing.T) {
...
 			expectedErr:          true,
-			// Under duress, closing a channel will not necessarily stop the retry
-			// loop immediately, so we skip this test under duress.
-			skipUnderDuress: true,
 		},
 	}
 
 	for _, tc := range testCases {
 		t.Run(tc.name, func(t *testing.T) {
-			if tc.skipUnderDuress && skip.Duress() {
```
Comment (kev-cao) [inline pkg/util/retry/retry_test.go:507]: You'll need to run `dev gen bazel` because we'll be removing the import of the `skip` package.

**Review by kev-cao — CHANGES_REQUESTED** [review]

File: pkg/util/retry/retry_test.go (hunk 2 above)
Comment (sanki92) [reply pkg/util/retry/retry_test.go:507]: all requested changes implemented! ✅

File: pkg/util/retry/retry_test.go [hunk 3]
```diff
@@ -494,20 +486,13 @@ func TestRetryWithMaxDuration(t *testing.T) {
 			preRetryFunc: func() {
 				close(closeCh)
 			},
-			maxExpectedTimeSpent: time.Millisecond * 20,
-			expectedErr:          true,
-			// Under duress, closing a channel will not necessarily stop the retry
-			// loop immediately, so we skip this test under duress.
-			skipUnderDuress: true,
+			expectedTimeSpent: time.Millisecond,
```
Comment (kev-cao) [inline pkg/util/retry/retry_test.go]: Since the context/stopper is canceled before the retry loop, the expected time would be 0 instead of 1.

Comment (sanki92) [reply pkg/util/retry/retry_test.go]: Fixed ✅

File: pkg/util/retry/retry_test.go [hunk 4]
```diff
@@ -549,13 +534,6 @@ func TestRetryWithMaxDuration(t *testing.T) {
 					t, tc.expectedTimeSpent, timeSource.Since(start), "expected time does not match actual spent time",
```
Comment (kev-cao) [inline pkg/util/retry/retry_test.go]: We'll also need to get rid of the condition or else the tests are essentially a no-op.

Comment (sanki92) [reply pkg/util/retry/retry_test.go]: Done! Let me know if you spot anything else.

**Comment by kev-cao** [comment]
Does the test still pass?

**Comment by sanki92** [comment]
Can't run locally due to missing protobuf deps, but the logic should be correct. If there are any test failures, happy to debug further!

**Comment by kev-cao** [comment]
I think the implementation needs updating. If the context is canceled before the retry loop ever runs, then no backoff will have been performed.

**Comment by sanki92** [comment]
I've made the changes. Could you check it locally when you get a chance? My setup can't handle the build. Thanks!

**Review by kev-cao — APPROVED** [review]
This LGTM! Updated the commit message and PR to follow our conventions. I'll get one more set of eyes on this before we merge it. Thanks for the contribution!

**Review by yuzefovich — APPROVED** [review]
:lgtm: Probably worth backporting to 25.4?

> @yuzefovich reviewed 1 of 2 files at r3, 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/154782#-:-OauW5mU2a0nmhUbe7pR:b8fwquv)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @kev-cao and @sanki92)
