### PR TITLE
changefeedccl: fix incorrect previous values for dropped columns

### LINKED ISSUE #150540: roachtest: cdc/schemareg failed
roachtest.cdc/schemareg [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/20212750?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/20212750?buildTab=artifacts#/cdc/schemareg) on master @ [615874951c647255e83fa32f99cac6809fe04ea2](https://github.com/cockroachdb/cockroach/commits/615874951c647255e83fa32f99cac6809fe04ea2):

```
(cdc.go:1549).runCDCSchemaRegistry: expected
{"before":null,"after":{"foo":{"a":{"long":1}}},"updated":{"string":""}}
{"before":null,"after":{"foo":{"a":{"long":2},"b":{"string":"2"}}},"updated":{"string":""}}
{"before":null,"after":{"foo":{"a":{"long":3},"b":{"string":"3"},"c":{"long":3}}},"updated":{"string":""}}
{"before":null,"after":{"foo":{"a":{"long":4},"c":{"long":4}}},"updated":{"string":""}}
{"before":{"foo_before":{"a":{"long":1},"b":null,"c":null}},"after":{"foo":{"a":{"long":1},"c":null}},"updated":{"string":""}}
{"before":{"foo_before":{"a":{"long":2},"b":{"string":"2"},"c":null}},"after":{"foo":{"a":{"long":2},"c":null}},"updated":{"string":""}}
{"before":{"foo_before":{"a":{"long":3},"b":{"string":"3"},"c":{"long":3}}},"after":{"foo":{"a":{"long":3},"c":{"long":3}}},"updated":{"string":""}}
got
{"before":null,"after":{"foo":{"a":{"long":1}}},"updated":{"string":""}}
{"before":null,"after":{"foo":{"a":{"long":2},"b":{"string":"2"}}},"updated":{"string":""}}
{"before":null,"after":{"foo":{"a":{"long":3},"b":{"string":"3"},"c":{"long":3}}},"updated":{"string":""}}
{"before":null,"after":{"foo":{"a":{"long":4},"c":{"long":4}}},"updated":{"string":""}}
{"before":{"foo_before":{"a":{"long":1},"c":null}},"after":{"foo":{"a":{"long":1},"c":null}},"updated":{"string":""}}
{"before":{"foo_before":{"a":{"long":2},"c":null}},"after":{"foo":{"a":{"long":2},"c":null}},"updated":{"string":""}}
{"before":{"foo_before":{"a":{"long":3},"c":{"long":3}}},"after":{"foo":{"a":{"long":3},"c":{"long":3}}},"updated":{"string":""}}
(cdc.go:3592).stop: context canceled
test artifacts and logs in: /artifacts/cdc/schemareg/run_1
```

Parameters:
 - <code>arch=amd64</code>
 - <code>cloud=gce</code>
 - <code>coverageBuild=false</code>
 - <code>cpu=4</code>
 - <code>encrypted=false</code>
 - <code>metamorphicBufferedSender=true</code>
 - <code>metamorphicLeases=default</code>
 - <code>metamorphicWriteBuffering=true</code>
 - <code>runtimeAssertionsBuild=false</code>
 - <code>ssd=0</code>
<details><summary>Help</summary>
<p>

See: [roachtest README](https://github.com/cockroachdb/cockroach/blob/master/pkg/cmd/roachtest/README.md)

See: [How To Investigate \(internal\)](https://cockroachlabs.atlassian.net/l/c/SSSBr8c7)

See: [Grafana](https://go.crdb.dev/roachtest-grafana/teamcity-20212750/cdc-schemareg/1752903986838/1752904953831)

</p>
</details>
/cc @cockroachdb/cdc
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*cdc/schemareg.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/bazci/githubpost/issues)

</sub>

### PR DESCRIPTION
**Pull request by fqazi**
Previously, when we adjusted when the backfill was emitted for the drop column under the declarative schema changer when schema_locked was active, we wound up emitting the previous values incorrectly. What this meant was that in the Avro format the old and new values would be the same when a column was being dropped. This was observed by the cdc/schemareg test. To address this, this patch correctly resolves the previous values in the drop column case from the last descriptor version.

Fixes: #150540

Release note: None

### CODE REVIEW

File: pkg/sql/catalog/descriptor.go [hunk 1]
```diff
@@ -1207,3 +1208,39 @@ func IsSystemDescriptor(desc Descriptor) bool {
...
+// HasDeclarativeMergedPrimaryIndex returns if a primary key swap is occurring
+// via the declarative schema changer, and the new index is in a write-only state.
+func HasDeclarativeMergedPrimaryIndex(desc TableDescriptor) bool {
+	// For declarative schema changes detect when a new primary index becomes
+	// WRITE_ONLY (i.e. backfill has been completed).
+	for idx, target := range desc.GetDeclarativeSchemaChangerState().Targets {
+		if target.GetPrimaryIndex() != nil &&
+			target.GetPrimaryIndex().TableID == desc.GetID() &&
+			(target.TargetStatus == scpb.Status_PUBLIC || target.TargetStatus == scpb.Status_TRANSIENT_ABSENT) &&
+			desc.GetDeclarativeSchemaChangerState().CurrentStatuses[idx] == scpb.Status_WRITE_ONLY {
```
Comment (andyyang890) [inline pkg/sql/catalog/descriptor.go]: Should we store `desc.GetDeclarativeSchemaChangerState()` in a var so it doesn't need to be called multiple times? Seems like it might be doing a clone each time if it's an `immutable`.

Comment (andyyang890) [inline pkg/sql/catalog/descriptor.go]: For my own understanding, could you explain what the difference between `TargetStatus` and `CurrentStatuses` is?

File: pkg/sql/catalog/descriptor.go [hunk 2]
```diff
@@ -1207,3 +1208,39 @@ func IsSystemDescriptor(desc Descriptor) bool {
...
+	desc TableDescriptor, columnID catid.ColumnID,
+) (bool, string) {
+	state := desc.GetDeclarativeSchemaChangerState()
+	if state == nil {
+		// No declarative schema change is active.
+		return false, ""
+	}
+	// Find the dropped column name element name that maps to the old name.
+	for _, elem := range state.Targets {
+		if nameElem, ok := elem.Element().(*scpb.ColumnName); ok && nameElem.TableID == desc.GetID() && nameElem.ColumnID == columnID && elem.TargetStatus == scpb.Status_ABSENT {
```
Comment (andyyang890) [inline pkg/sql/catalog/descriptor.go]: nit: split long line into multiple lines

File: pkg/ccl/changefeedccl/cdcevent/event.go [hunk 3]
```diff
@@ -302,7 +304,7 @@ func NewEventDescriptor(
 	}
 
 	// addColumn is a helper to add a column to this descriptor.
-	addColumn := func(col catalog.Column, ord int) int {
+	addColumn := func(col catalog.Column, nameOverrideString string, ord int) int {
```
Comment (andyyang890) [inline pkg/ccl/changefeedccl/cdcevent/event.go]: nit: the `String` part of the var name isn't necessary

File: pkg/ccl/changefeedccl/cdcevent/event.go [hunk 4]
```diff
@@ -329,7 +333,43 @@ func NewEventDescriptor(
...
+	if desc.GetDeclarativeSchemaChangerState() != nil {
+		hasMergedIndex := catalog.HasDeclarativeMergedPrimaryIndex(desc)
+		allColumns := desc.AllColumns()
+		columnsToTrack = make([]catalog.Column, 0, len(allColumns))
+		for _, column := range allColumns {
+			// Skip all adding columns and non public column.
+			if column.Adding() {
+				continue
+			}
+			// Pick up any write-only columns
```
Comment (andyyang890) [inline pkg/ccl/changefeedccl/cdcevent/event.go]: nit: add punctuation to end of comment

File: pkg/ccl/changefeedccl/cdcevent/event.go [hunk 5]
```diff
@@ -329,7 +333,43 @@ func NewEventDescriptor(
 	// Primary key columns must be added in the same order they
 	// appear in the primary key index.
 	primaryIdx := desc.GetPrimaryIndex()
-	colOrd := catalog.ColumnIDToOrdinalMap(desc.PublicColumns())
+	// For declarative schema changes, we intentionally select a previous descriptor
+	// where a dropped column is in the WRITE_ONLY state (instead of PUBLIC).
+	// This is necessary because we intentionally shifted the schema change stages
```
Comment (andyyang890) [inline pkg/ccl/changefeedccl/cdcevent/event.go]: Would you mind expanding this comment a bit more to explain why this is necessary?

Comment (fqazi) [reply pkg/ccl/changefeedccl/cdcevent/event.go]: I added updated the comment to clarify this:

```
	// The declarative schema changer requires special handling for dropped columns
	// to ensure their previous values are available to the changefeed.
	// We select a prior descriptor where the column is in the WRITE_ONLY state
	// (instead of PUBLIC) and treat it as visible.
	// This is necessary because the schema change stages for dropped columns were
	// intentionally shifted to support automatic `schema_locked` management. The
	// declarative schema changer cannot make a column WRITE_ONLY and flip
	// `schema_locked` in two separate stages, so we instead treat the WRITE_ONLY
	//  stage as a non-backfilling change for CDC.
```

File: pkg/sql/catalog/descriptor.go (hunk 1 above)
Comment (fqazi) [reply pkg/sql/catalog/descriptor.go]: Done.

Comment (fqazi) [reply pkg/sql/catalog/descriptor.go]: Target status is the final status the declarative schema changer is planning towards. Current status is the status that we have achieved so far. So, a new index will start with an initial / current status of Abset and aim for a target of Public.

**Review by fqazi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/150952)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @andyyang890)

File: pkg/ccl/changefeedccl/cdcevent/event_test.go [hunk 6]
```diff
@@ -173,7 +174,7 @@ CREATE TABLE foo (
   FAMILY main (a, b, e),
   FAMILY only_c (c)
 )`)
-
+	//FIXME: add an event filter?
```
Comment (andyyang890) [inline pkg/ccl/changefeedccl/cdcevent/event_test.go]: Does this still need to be addressed?

**Review by andyyang890 — APPROVED** [review]

File: pkg/ccl/changefeedccl/cdcevent/event_test.go (hunk 6 above)
Comment (fqazi) [reply pkg/ccl/changefeedccl/cdcevent/event_test.go]: No, just a left over comment while debugging

**Comment by fqazi** [comment]
@andyyang890 TFTR!

bors r+
