### PR TITLE
storage: fix `CheckSSTConflicts` handling of MVCC range keys

### LINKED ISSUE #93968: batcheval: `AddSSTable` can write at same timestamp as MVCC range tombstone
In #89145, it was found that an `AddSSTable` can write to the same timestamp as an MVCC range tombstone, e.g. if both requests are pushed by the timestamp cache to the same timestamp before evaluation. This shouldn't be possible, and indicates faulty conflict handling in `CheckSSTConflicts`.

Jira issue: CRDB-22624

### PR DESCRIPTION
**Pull request by erikgrinaker**
`CheckSSTConflicts` keeps an SST and engine iterator in sync while checking for conflicts. To avoid seek costs, it attempts to step the engine iterator in case the corresponding SST key is nearby. However, this stepping could step right past an MVCC range key overlapping the SST key, which would break conflict checks with MVCC range tombstones.

This patch seeks the engine iterator back to the SST key if we step past it and the range key changed.

Resolves #93968.

Release note (bug fix): When experimental MVCC range tombstones are enabled (they're disabled by default), a bulk ingestion (e.g. an import) could in some situations fail to properly check for conflicts with existing MVCC range tombstones. This could cause the ingestion to write below a recently written MVCC range tombstone, in turn losing the ingested data. This could only happen in rare circumstances where a bulk ingestion was applied concurrently with an import cancellation.

### CODE REVIEW

File: pkg/kv/kvserver/batcheval/cmd_add_sstable_test.go [hunk 1]
```diff
@@ -324,6 +324,33 @@ func TestEvalAddSSTable(t *testing.T) {
...
+		// Regression tests for https://github.com/cockroachdb/cockroach/issues/93968.
+		"DisallowConflicts WriteTooOldError straddling at existing range tombstone": {
+			noConflict: true,
+			data:       kvs{rangeKV("b", "z", 3, "")},
+			sst:        kvs{pointKV("a", 3, "sst"), pointKV("c", 3, "sst")},
+			expectErr:  &roachpb.WriteTooOldError{},
+		},
+		"DisallowConflicts WriteTooOldError straddling multiple existing range tombstones": {
+			noConflict: true,
+			data:       kvs{rangeKV("b", "d", 3, ""), rangeKV("d", "f", 3, "")},
```
Comment (itsbilal) [inline pkg/kv/kvserver/batcheval/cmd_add_sstable_test.go:342]: For what's worth, both of these will get defragmented together at read time as the prefix/values match

**Review by itsbilal — APPROVED** [review]
LGTM, thanks for fixing this as well!

File: pkg/kv/kvserver/batcheval/cmd_add_sstable_test.go (hunk 1 above)
Comment (erikgrinaker) [reply pkg/kv/kvserver/batcheval/cmd_add_sstable_test.go]: Whoops, was supposed to be a gap there, thanks -- messed up while I was simplifying the test case.

**Comment by erikgrinaker** [comment]
TFTR!

bors r+
