### PR TITLE
pkg/cli: ensure consistent defaults regardless of TESTFLAGS=-v

### LINKED ISSUE #21355: cli: `Test{SQLLex,RunQuery}` fail with `TESTFLAGS=-v`
Looks like this code gets confused https://github.com/cockroachdb/cockroach/blob/4e6ec545cc65dc0051a797996e9642b4b5e8bdc2/pkg/cli/sql.go#L1046-L1048

```
$ make test PKG=./pkg/cli TESTFLAGS=-v TESTS=SQLLex
...
=== RUN   TestSQLLex
test logs left over in: /tmp/logTestSQLLex831856190
--- FAIL: TestSQLLex (0.13s)
	test_log_scope.go:81: test logs captured to: /tmp/logTestSQLLex831856190
	test_log_scope.go:62: use -show-logs to present logs inline
	sql_test.go:151: 
		select '
		\?
		;
		';
		:
		expected: +---------------+
		| e'\n\\?\n;\n' |
		+---------------+
		| ␤             |
		| \?␤           |
		| ;␤            |
		|               |
		+---------------+
		(1 row)
		
		got: +---------------+
		| e'\n\\?\n;\n' |
		+---------------+
		| ␤             |
		| \?␤           |
		| ;␤            |
		|               |
		+---------------+
		(1 row)
		
		Time: 7.969132ms
		
FAIL
exit status 1
FAIL	github.com/cockroachdb/cockroach/pkg/cli	0.167s
make: *** [test] Error 1
```

### PR DESCRIPTION
**Pull request by knz**
Fixes #21355.
Fix suggested by @tamird.

Prior to this patch, CLI tests using the interactive code path
from `sql.go` would see different results depending on whether
the tests were run with `-v` or not, because the interactive
code path likes its defaults to differ based on whether the
output happens to go to a terminal.

This makes it hard to expect a fixed output in tests regardless
of the test parameters -- in fact, two tests were failing
because of this.

To alleviate this, this patch introduces a new helper function
`setCLIDefaultsForTests` to be used by tests that wish to
call into the interactive code path of `cockroach sql`.

Note: tests calling into `cockroach sql` with `RunWithArgs`
cannot utilize this function. To ensure stable test output,
these tests can use e.g. `cockroach sql -e` which currently
happens to determine the same parameter defaults regardless
of the terminal environment.

Release note: None

### CODE REVIEW

File: pkg/cli/sql_util_test.go [hunk 1]
```diff
@@ -98,12 +98,10 @@ func TestRunQuery(t *testing.T) {
...
 	defer conn.Close()
 
-	// Use a buffer as the io.Writer.
-	var b bytes.Buffer
-
-	cliCtx.tableDisplayFormat = tableDisplayPretty
+	setCLIDefaultsForTests()
 
 	// Non-query statement.
+	var b bytes.Buffer
```
Comment (tamird) [inline pkg/cli/sql_util_test.go]: This gets used for a few other statements, so I'd maybe leave it above the comment.

**Review by tamird — APPROVED** [review]
Thanks @knz!

File: pkg/cli/sql_util_test.go (hunk 1 above)
Comment (knz) [reply pkg/cli/sql_util_test.go]: Aye, done.

**Comment by mberhault** [comment]
LGTM

**Comment by knz** [comment]
Thanks to both!
