### PR TITLE
ccl/sqlproxyccl: fix status code and hint reporting

### LINKED ISSUE #93474: Misleading error message when using    sslmode=require
**Describe the problem**

The following message is received when using `sslmode=require` instead of `sslmode=verify-full` :

```
failed to connect to `host=test-stuff123.cockroachlabs.cloud user=test database=defaultdb`: server error (FATAL: codeParamsRoutingFailed: missing cluster identifier (SQLSTATE 08004))
```

Message is misleading as it complains about missing cluster ID rather than wrong sslmode. Can we change it please?

Jira issue: CRDB-22352

gz#14985

### PR DESCRIPTION
**Pull request by darinpp**
The error with code that the proxy uses doesn't follow the same pattern as the rest of the repo code and as a result the hint that we add to the error was not being passed to the end user. This PR refactors the error to be in line with the rest of the code, refactors the hint that we use in case of missing routing info and adds a test to verify that it works.

Fixes #93474

Release note: None

### CODE REVIEW

**Review by knz — COMMENTED** [review]
What's the rationale for introducing your own `withCode` and not using our existing `pgerror` package?

**Comment by darinpp** [comment]
> What's the rationale for introducing your own `withCode` and not using our existing `pgerror` package?

The PR doesn't introduce the code attached to the error. It is already there. I'm just refactoring it so it works as expected. 
The code attached to the proxy errors is an indication of the proxy condition that resulted in an error (i.e. codeBackendRefusedTLS). These all currently map to a single pgerror code `SQLserverRejectedEstablishmentOfSQLconnection = MakeCode("08004")`
It is possible that we add all these codes as PG error codes and return something besides 08004. Do you think it makes sense adding a new class of PG error code that are proxy specific, adding the existing ones and returning more detailed info to the end user? Should that happen in this PR or in separate if yes?

**Review by knz — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/94030#-:-NJplT6DBGKFncgoMmTq:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @andy-kimball, @jaylim-crl, and @JeffSwenson)

File: pkg/sql/pgwire/pgcode/codes.go [hunk 1]
```diff
@@ -56,6 +56,7 @@ var (
 	SQLserverRejectedEstablishmentOfSQLconnection = MakeCode("08004")
 	TransactionResolutionUnknown                  = MakeCode("08007")
 	ProtocolViolation                             = MakeCode("08P01")
+	ProxyConnectionError                          = MakeCode("08C00")
```
Comment (rafiss) [inline pkg/sql/pgwire/pgcode/codes.go:59]: is this a custom code for CRDB? if so, then i think we should put it below with the others: https://github.com/cockroachdb/cockroach/blob/03a5c4029931237dc204da82bacdca2385c4b2c7/pkg/sql/pgwire/pgcode/codes.go#L319

Comment (knz) [reply pkg/sql/pgwire/pgcode/codes.go:59]: oh yeah that's right. Thanks rafi.

Comment (darinpp) [reply pkg/sql/pgwire/pgcode/codes.go]: ok, I moved it.
