### PR TITLE
changefeedccl: split up TestChangefeedCursor into subtests

### LINKED ISSUE #146179: ccl/changefeedccl: TestChangefeedCursor failed
ccl/changefeedccl.TestChangefeedCursor [failed](https://tanzanite.cluster.engflow.com/invocations/default/8439ffaf-b90b-4520-a3a9-b142e6c3bc5d?testReportRun=2&testReportShard=8&testReportAttempt=1#targets-Ly9wa2cvY2NsL2NoYW5nZWZlZWRjY2w6Y2hhbmdlZmVlZGNjbF90ZXN0) on master @ [561a43d20ce870dbe0ad12fc3e51e3bee49c60e7](https://github.com/cockroachdb/cockroach/commits/561a43d20ce870dbe0ad12fc3e51e3bee49c60e7):

```
=== RUN   TestChangefeedCursor
    test_log_scope.go:165: test logs captured to: outputs.zip/logTestChangefeedCursor2790023106
    test_log_scope.go:76: use -show-logs to present logs inline
    changefeed_test.go:1090: -- test log scope end --
test logs left over in: outputs.zip/logTestChangefeedCursor2790023106
--- FAIL: TestChangefeedCursor (39.71s)
=== RUN   TestChangefeedCursor/kafka
    helpers_test.go:1043: making server as system tenant
    helpers_test.go:1119: making kafka feed factory
    testfeed_test.go:322: creating external connection
    testfeed_test.go:325: ran create external connection
    testfeed_test.go:322: creating external connection
    testfeed_test.go:325: ran create external connection
    testfeed_test.go:322: creating external connection
    testfeed_test.go:325: ran create external connection
    testfeed_test.go:322: creating external connection
    testfeed_test.go:325: ran create external connection
    changefeed_test.go:1073: 
        	Error Trace:	pkg/ccl/changefeedccl/helpers_test.go:268
        	            				pkg/ccl/changefeedccl/helpers_test.go:363
        	            				pkg/ccl/changefeedccl/changefeed_test.go:1073
        	            				pkg/ccl/changefeedccl/helpers_test.go:1291
        	            				pkg/ccl/changefeedccl/helpers_test.go:1326
        	Error:      	Received unexpected error:
        	            	operation "kafka.Next-1069712999854899201" timed out after 30s (given timeout 30s): context deadline exceeded
        	            	(1) operation "kafka.Next-1069712999854899201" timed out after 30s (given timeout 30s)
        	            	Wraps: (2) context deadline exceeded
        	            	Error types: (1) *timeutil.TimeoutError (2) context.deadlineExceededError
        	Test:       	TestChangefeedCursor/kafka
--- FAIL: TestChangefeedCursor/kafka (39.71s)
```

Parameters:
 - <code>attempt=1</code>
 - <code>deadlock=true</code>
 - <code>run=2</code>
 - <code>shard=8</code>
<details><summary>Help</summary>
<p>

See also: [How To Investigate a Go Test Failure \(internal\)](https://cockroachlabs.atlassian.net/l/c/HgfXfJgM)
</p>
</details>
/cc @cockroachdb/cdc
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*TestChangefeedCursor.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/bazci/githubpost/issues)

</sub>

### PR DESCRIPTION
**Pull request by andyyang890**
This patch splits up `TestChangefeedCursor` into subtests. Doing so also
has the side effect of closing each changefeed before starting the next,
which may reduce timeouts due to resource contention.

Fixes #146179

Release note: None

### CODE REVIEW

**Review by aerfrei — APPROVED** [review]

File: pkg/ccl/changefeedccl/changefeed_test.go [hunk 1]
```diff
@@ -1029,62 +1029,70 @@ func TestChangefeedCursor(t *testing.T) {
...
+			defer closeFeed(t, fooLogical)
+			assertPayloads(t, fooLogical, []string{
+				`foo: [2]->{"after": {"a": 2, "b": "after"}}`,
+			})
 
-		fooLogical := feed(t, f, `CREATE CHANGEFEED FOR foo WITH cursor=$1`, eval.TimestampToDecimalDatum(tsLogical).String())
-		defer closeFeed(t, fooLogical)
-		assertPayloads(t, fooLogical, []string{
-			`foo: [2]->{"after": {"a": 2, "b": "after"}}`,
+			// Check that the cursor is properly hooked up to the job statement
```
Comment (rharding6373) [inline pkg/ccl/changefeedccl/changefeed_test.go:1067]: Why only do this for the decimal cursor test?

**Review by rharding6373 — APPROVED** [review]
Nice refactor! This will make the tests much easier to debug in the future.

File: pkg/ccl/changefeedccl/changefeed_test.go (hunk 1 above)
Comment (andyyang890) [reply pkg/ccl/changefeedccl/changefeed_test.go:1067]: This was a code move from later in the test. I did try adding it to the other cases but they flake sometimes because of the logical portion of the `hlc.Timestamp`, which can't be included for the other formats.

**Comment by andyyang890** [comment]
TFTRs!

bors r=aerfrei,rharding6373

**Comment by andyyang890** [comment]
bors retry
