### PR TITLE
changefeedccl: disable unsafe sql updates in nemeses test

### LINKED ISSUE #140591: ccl/changefeedccl: TestChangefeedNemeses failed
ccl/changefeedccl.TestChangefeedNemeses [failed](https://tanzanite.cluster.engflow.com/invocations/default/aae51751-59c0-41e3-ba8f-ec7eabdcf020?testReportRun=19&testReportShard=9&testReportAttempt=1#targets-Ly9wa2cvY2NsL2NoYW5nZWZlZWRjY2w6Y2hhbmdlZmVlZGNjbF90ZXN0) on master @ [bce8eb6edbbe879d376ab0c99e9d1129e5afef96](https://github.com/cockroachdb/cockroach/commits/bce8eb6edbbe879d376ab0c99e9d1129e5afef96):

Fatal error:

```
panic: test timed out after 15m0s
running tests:
	TestChangefeedNemeses (13m14s)
	TestChangefeedNemeses/nemeses_options==fp_validator=true,sql_smith=true (13m14s)
	TestChangefeedNemeses/nemeses_options==fp_validator=true,sql_smith=true/kafka (13m14s)

```
Stack: 

```
goroutine 465257 [running]:
testing.(*M).startAlarm.func1()
	GOROOT/src/testing/testing.go:2366 +0x385
created by time.goFunc
	GOROOT/src/time/sleep.go:177 +0x2d
```
<details><summary>Log preceding fatal error</summary>
<p>

```
=== RUN   TestChangefeedNemeses
    test_log_scope.go:165: test logs captured to: outputs.zip/logTestChangefeedNemeses3389716258
    test_log_scope.go:76: use -show-logs to present logs inline
=== RUN   TestChangefeedNemeses/nemeses_options==fp_validator=true,sql_smith=true
=== RUN   TestChangefeedNemeses/nemeses_options==fp_validator=true,sql_smith=true/kafka
    helpers_test.go:914: making server as system tenant
    helpers_test.go:990: making kafka feed factory
    nemeses_test.go:33: random seed: 3336714395534731464
    nemeses_test.go:40: using legacy schema changer
```
</p>
</details>

Parameters:
 - <code>attempt=1</code>
 - <code>run=19</code>
 - <code>shard=9</code>
<details><summary>Help</summary>
<p>

See also: [How To Investigate a Go Test Failure \(internal\)](https://cockroachlabs.atlassian.net/l/c/HgfXfJgM)
</p>
</details>
/cc @cockroachdb/cdc
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*TestChangefeedNemeses.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/bazci/githubpost/issues)

</sub>

Jira issue: CRDB-47253

### PR DESCRIPTION
**Pull request by rharding6373**
Some queries generated by sql smith can hang due to being unsafe (e.g., executing many self-joins). This PR enables the session setting `sql_safe_updates` in order to reject these kinds of queries, then redisables it for the remainder of the test. It also makes some minor improvements, such as only populating initial table state via sql smith if sql smit is enabled, logging to make it easy to reproduce the table's initial state before the changefeed is created, and only allowing normal sql mutations with sql smith.

Epic: none
Fixes: #140591

Release note: none

### CODE REVIEW

File: pkg/internal/sqlsmith/sqlsmith.go [hunk 1]
```diff
@@ -470,6 +470,17 @@ var InsUpdOnly = simpleOption("inserts and updates only", func(s *Smither) {
 	}
 })
 
+// InsUpdDelOnly causes the Smither to emit 80% INSERT, 10% UPDATE,
+// 10% DELETE statements.
+var InsUpdDelOnly = simpleOption("inserts updates and deletes only",
```
Comment (aerfrei) [inline pkg/internal/sqlsmith/sqlsmith.go:475]: As opposed to "MutationsOnly", "InsUpdDelOnly" doesn't put any weight on makeCrateStatistics or SetSessionCharacteristics. Do those two types of queries create a lot of self joins under the hood and therefore potentially hang? (basing this on the commit message)

Trying to understand better what makes those queries unsafe.

**Review by aerfrei — APPROVED** [review]

File: pkg/internal/sqlsmith/sqlsmith.go (hunk 1 above)
Comment (rharding6373) [reply pkg/internal/sqlsmith/sqlsmith.go:475]: They're not unsafe, but they're not relevant to the CDC use case. SQL Queries added those for additional test coverage of those features, but create statistics mostly (maybe always) fails for the table in the nemeses test, and neither operation results in changefeed output.

**Comment by rharding6373** [comment]
TFTR!

bors r=aerfrei

**Comment by rharding6373** [comment]
blathers auth-check

**Comment by rharding6373** [comment]
You shall pass

**Comment by rharding6373** [comment]
blathers backport 25.2
