### PR TITLE
streamingccl: fix TestTenantStreamingProducerJobTimedOut flaky test

### LINKED ISSUE #84332: ccl/streamingccl/streamingest: TestTenantStreamingProducerJobTimedOut failed
ccl/streamingccl/streamingest.TestTenantStreamingProducerJobTimedOut [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_StressBazel/5731396?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_StressBazel/5731396?buildTab=artifacts#/) on master @ [687171ac6c2cd9992486bb3b8c9d252ac95ca1cd](https://github.com/cockroachdb/cockroach/commits/687171ac6c2cd9992486bb3b8c9d252ac95ca1cd):

```
=== RUN   TestTenantStreamingProducerJobTimedOut
    test_log_scope.go:79: test logs captured to: /artifacts/tmp/_tmp/045fecfe9e18c9da6f776a53d446f2c5/logTestTenantStreamingProducerJobTimedOut3649603095
    test_log_scope.go:80: use -show-logs to present logs inline
    panic.go:1047: -- test log scope end --
    panic.go:1047: runtime error: invalid memory address or nil pointer dereference
        goroutine 9578532 [running]:
        runtime/debug.Stack()
        	GOROOT/src/runtime/debug/stack.go:24 +0x65
        github.com/cockroachdb/cockroach/pkg/util/leaktest.AfterTest.func1()
        	github.com/cockroachdb/cockroach/pkg/util/leaktest/leaktest.go:110 +0x92
        panic({0x61daae0, 0x9966ae0})
        	GOROOT/src/runtime/panic.go:1047 +0x266
        github.com/cockroachdb/cockroach/pkg/ccl/streamingccl/streamingest.TestTenantStreamingProducerJobTimedOut(0xc0153f8820)
        	github.com/cockroachdb/cockroach/pkg/ccl/streamingccl/streamingest/stream_replication_e2e_test.go:330 +0x4af
        testing.tRunner(0xc0153f8820, 0x6b42150)
        	GOROOT/src/testing/testing.go:1259 +0x102
        created by testing.(*T).Run
        	GOROOT/src/testing/testing.go:1306 +0x35a
--- FAIL: TestTenantStreamingProducerJobTimedOut (12.22s)
```
<p>Parameters: <code>TAGS=bazel,gss,deadlock</code>
</p>
<details><summary>Help</summary>
<p>

See also: [How To Investigate a Go Test Failure \(internal\)](https://cockroachlabs.atlassian.net/l/c/HgfXfJgM)
</p>
</details>
/cc @cockroachdb/tenant-streaming
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*TestTenantStreamingProducerJobTimedOut.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)
</sub>

Jira issue: CRDB-17591

### PR DESCRIPTION
**Pull request by gh-casper**
streamingccl: fix TestTenantStreamingProducerJobTimedOut flaky test

Fixes a race between job resumer updating the job high watermark
and reading high watermark when getting a stream ingestion stats.

Closes: https://github.com/cockroachdb/cockroach/issues/84332

Release note: None

### CODE REVIEW

File: pkg/ccl/streamingccl/streamingest/stream_ingestion_processor_planning.go [hunk 1]
```diff
@@ -194,7 +194,7 @@ func (s *streamIngestionResultWriter) AddRow(ctx context.Context, row tree.Datum
 		&ingestedHighWatermark); err != nil {
 		return errors.NewAssertionErrorWithWrappedErrf(err, `unmarshalling resolved timestamp`)
 	}
-	return s.registry.UpdateJobWithTxn(ctx, s.jobID, nil /* txn */, false, /* useReadLock */
+	return s.registry.UpdateJobWithTxn(ctx, s.jobID, nil /* txn */, true, /* useReadLock */
```
Comment (samiskin) [inline pkg/ccl/streamingccl/streamingest/stream_ingestion_processor_planning.go:197]: Could be good to add a TODO here around investigating why this is necessary

**Review by samiskin — APPROVED** [review]
