### PR TITLE
backupccl: fix backup protected timestamp test

### LINKED ISSUE #51066: backup: incremental backups need to protect _start_ time.
Currently we protect `endTime` meaning that a backup reading at time `X` can run as long as it wants and time `X` will remain available. But an incremental backup needs to capture changes from startTime Y to endTime X -- currently we only protect from endTime, but this could mean a GC mid-backup could potentially GC changes in that window and cause it to fail. When StartTime is non-empty, we should protect StartTime instead of EndTime.

### LINKED ISSUE #51068: backupccl: TestProtectedTimestampsDuringBackup does not fail when protectedts skipped
Currently can comment out [the creation of the protectedTS](https://github.com/cockroachdb/cockroach/blob/master/pkg/ccl/backupccl/backup_planning.go#L714) record and the test still succeeds.

### PR DESCRIPTION
**Pull request by pbardea**
The protected timestamp test for backup only tested that the timestamp
was released after the backup, not if the timestamp was actually
protected in the first place. This commit adds an AOST select at what
should otherwise be a timestamp that has been GC'd.

The test will fail on this SELECT command if the timestamp is not
protected.

Fixes #51068.

Release note: None

### CODE REVIEW

File: pkg/ccl/backupccl/backup_test.go [hunk 1]
```diff
@@ -3869,6 +3871,7 @@ func TestProtectedTimestampsDuringBackup(t *testing.T) {
 
 	// We should have refused to GC over the timestamp which we needed to protect.
 	gcTable(true /* skipShouldQueue */)
+	runner.Exec(t, "SELECT * FROM foo AS OF SYSTEM TIME "+tsBefore)
```
Comment (dt) [inline pkg/ccl/backupccl/backup_test.go:3874]: huh, is this require to get it to fail if the backup doesn't protect its TS? I'd have expected the ExportRequest to hit it when we close allowResponse below, right? Oh, I wonder if it is because we're using a *Response* filter, not a Request filter, so it has eagerly executed before GC?

Comment (pbardea) [reply pkg/ccl/backupccl/backup_test.go:3874]: I ~think that it is required to fail with `kv.gc_ttl.strict_enforcement.enabled` which is set by default. I would prefer to test this more explicitly with an ExportRequest hitting the GC threshold. Will try updating it with a request filter.

**Review by ajwerner — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/51072#-:-MC7NyfS7ZAk2lMFnmmM:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ajwerner and @dt)

___
*[pkg/ccl/backupccl/backup_test.go, line 4142 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/51072#-MC7NzLuB8i5qj_wrFl-:-MC7NzLuB8i5qj_wrFl0:b26crwt) ([raw file](https://github.com/cockroachdb/cockroach/blob/918dbe88510cd9f7b25d879cf68bd043040169e9/pkg/ccl/backupccl/backup_test.go#L4142)):*
> ```Go
> 	rowCount := runner.QueryStr(t, "SELECT * FROM foo")
> 
> 	g, _ := errgroup.WithContext(ctx)
> ```

this works but a `chan error` would also have worked.

**Review by dt — APPROVED** [review]

**Comment by pbardea** [comment]
TFTRs
bors r=ajwerner,dt

**Comment by pbardea** [comment]
Looks like bors got canceled. Trying again.
bors r=ajwerner,dt
