### PR TITLE
sql: prevent concurrent DROP and SET SCHEMA operations

### LINKED ISSUE #163156: roachtest: c2c/kv0 failed
roachtest.c2c/kv0 [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/21079983?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/21079983?buildTab=artifacts#/c2c/kv0) on release-25.4 @ [793a72339ad4d0f06887492472921a59622362c4](https://github.com/cockroachdb/cockroach/commits/793a72339ad4d0f06887492472921a59622362c4):

```
(soon.go:60).SucceedsWithin: condition failed to evaluate within 5m0s: from cluster_to_cluster.go:822: standby poller high water 2026-02-08 09:32:30 +0000 UTC not yet at PCR replicated time 2026-02-08 09:41:15 +0000 UTC
(monitor.go:267).Wait: monitor failure: monitor user task failed: t.Fatal() was called
test artifacts and logs in: /artifacts/c2c/kv0/run_1
```

Parameters:
 - <code>arch=amd64</code>
 - <code>cloud=gce</code>
 - <code>coverageBuild=false</code>
 - <code>cpu=8</code>
 - <code>encrypted=false</code>
 - <code>fs=ext4</code>
 - <code>localSSD=false</code>
 - <code>metamorphicLeases=leader</code>
 - <code>runtimeAssertionsBuild=false</code>
 - <code>ssd=0</code>
<details><summary>Help</summary>
<p>

See: [roachtest README](https://github.com/cockroachdb/cockroach/blob/master/pkg/cmd/roachtest/README.md)

See: [How To Investigate \(internal\)](https://cockroachlabs.atlassian.net/l/c/SSSBr8c7)

See: [Grafana](https://go.crdb.dev/roachtest-grafana/teamcity-21079983/c2c-kv0/1770542972421/1770544191066)

</p>
</details>
<details><summary>Same failure on other branches</summary>
<p>

- #161155 roachtest: c2c/kv0 failed [depends-on relation is dropped during DROP SCHEMA CASCADE] [C-test-failure O-roachtest O-robot P-2 T-sql-foundations branch-release-26.1]
</p>
</details>
/cc @cockroachdb/disaster-recovery
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*c2c/kv0.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/bazci/githubpost/issues)

</sub>

Jira issue: CRDB-60083

### PR DESCRIPTION
**Pull request by fqazi**
Previously, we added logic to prevent legacy schema modification operations while a schema was undergoing declarative schema changes. Unfortunately, this logic did not cover ALTER FUNCTION ... SET SCHEMA. This patch ensures all legacy schema write operations are blocked if a concurrent declarative schema change is in progress.

Fixes: #163156
Release note (bug fix): Prevented a race condition/conflict between concurrent ALTER FUNCTION ... SET SCHEMA and DROP SCHEMA operations.

### CODE REVIEW

File: pkg/sql/schema.go [hunk 1]
```diff
@@ -54,11 +59,6 @@ func (p *planner) writeSchemaDesc(ctx context.Context, desc *schemadesc.Mutable)
 func (p *planner) writeSchemaDescChange(
 	ctx context.Context, desc *schemadesc.Mutable, jobDesc string,
 ) error {
-	// Exit early with an error if the schema is undergoing a declarative schema
```
Comment (rafiss) [inline pkg/sql/schema.go:57]: it looks like there are some callers that only call writeSchemaDescChange, but not writeSchemaDesc? do we need to keep the check in both places?

Comment (fqazi) [reply pkg/sql/schema.go:57]: writeSchemaDescChange ends up invoking writeSchemaDesc, so those go through the same logic.

**Review by fqazi — COMMENTED** [review]
> @fqazi made 1 comment.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/164043)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on rafiss).

File: pkg/sql/schema.go (hunk 1 above)
Comment (rafiss) [reply pkg/sql/schema.go:57]: ah thanks missed that on my first read.

**Review by rafiss — APPROVED** [review]
lgtm! great catch

**Comment by fqazi** [comment]
/trunk merge

@rafiss TFTR!
