### PR TITLE
roachtest: fix leaked runBackgroundWorkload call

### LINKED ISSUE #160762: roachtest: backup-restore/round-trip failed
**Note:** This build has runtime assertions enabled. If the same failure was hit in a run without assertions enabled, there should be a similar failure without this message. If there isn&#39;t one, then this failure is likely due to an assertion violation or (assertion) timeout.

roachtest.backup-restore/round-trip [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/20950317?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/20950317?buildTab=artifacts#/backup-restore/round-trip) on release-25.4 @ [ab3b7a3d368a9929279f866833aec31913331c56](https://github.com/cockroachdb/cockroach/commits/ab3b7a3d368a9929279f866833aec31913331c56):

```
(test_runner.go:1452).runTest: test timed out (4h0m0s)
test artifacts and logs in: /artifacts/backup-restore/round-trip/cpu_arch=fips/run_1
```

Parameters:
 - <code>arch=fips</code>
 - <code>cloud=gce</code>
 - <code>coverageBuild=false</code>
 - <code>cpu=4</code>
 - <code>encrypted=true</code>
 - <code>fs=ext4</code>
 - <code>localSSD=true</code>
 - <code>metamorphicWriteBuffering=true</code>
 - <code>runtimeAssertionsBuild=true</code>
 - <code>ssd=0</code>
<details><summary>Help</summary>
<p>

See: [roachtest README](https://github.com/cockroachdb/cockroach/blob/master/pkg/cmd/roachtest/README.md)

See: [How To Investigate \(internal\)](https://cockroachlabs.atlassian.net/l/c/SSSBr8c7)

See: [Grafana](https://go.crdb.dev/roachtest-grafana/teamcity-20950317/backup-restore-round-trip/1767942700056/1767957622677)

</p>
</details>
<details><summary>Same failure on other branches</summary>
<p>

- #160380 roachtest: backup-restore/round-trip failed [C-test-failure O-roachtest O-robot P-2 T-sql-foundations branch-release-26.1]
- #158844 roachtest: backup-restore/round-trip failed [descriptor validate failed] [A-disaster-recovery B-runtime-assertions-enabled C-test-failure O-roachtest O-robot P-2 T-sql-foundations branch-master]
</p>
</details>
/cc @cockroachdb/disaster-recovery
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*backup-restore/round-trip.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/bazci/githubpost/issues)

</sub>

Jira issue: CRDB-58504

### PR DESCRIPTION
**Pull request by kev-cao**
This commit fixes the backup restore roundtrip tests where a background workload would be leaked and never stopped. This specifically occurs because we directly defer the stopping of the first workload call. By doing so, it is specifically the first workload call that is cleaned up. However, whenever we perform a full cluster restore, we stop the background workload, run the restore, and then restart the workload. If after restarting the workload we run into an error, we never run the cleanup from the new workload. The solution is to defer the cleanup in a closure, which allows us to always call the cleanup from the latest reset.

Fixes: #160762

Release note: None

### CODE REVIEW

File: pkg/cmd/roachtest/tests/backup_restore_roundtrip.go [hunk 1]
```diff
@@ -179,7 +179,18 @@ func backupRestoreRoundTrip(
 		if err != nil {
 			return err
 		}
-		defer stopBackgroundCommands()
+		defer func() {
+			if stopBackgroundCommands != nil {
+				// We specifically must defer stopBackgroundCommands in an IIFE here
```
Comment (msbutler) [inline pkg/cmd/roachtest/tests/backup_restore_roundtrip.go]: what does IIFE stand for?


nit: this comment feels a bit over explained. What about: "since stopBackgroundCommands may get reassigned below, call stopBackgroundCommands within an anonymous function to ensure the up to date assignment gets called on defer"

**Review by msbutler — APPROVED** [review]

File: pkg/cmd/roachtest/tests/backup_restore_roundtrip.go (hunk 1 above)
Comment (kev-cao) [reply pkg/cmd/roachtest/tests/backup_restore_roundtrip.go]: > what does IIFE stand for?
Immediately invoked function expression, it's a term originating from Javascript.

And yeah sounds good, that's more concise
