### PR TITLE
changefeedccl: fix timestamp for desc fetches during planning

### LINKED ISSUE #154549: changefeedccl: db-level feeds: use fixed timestamp for descriptor fetches
When a changefeed is planned and executed, there are several places where target table descriptors are fetched. With a db-level changefeed, the set of tables can change during changefeed startup. The table descriptors should be fetched at a fixed time, when the changefeed is starting from.

Jira issue: CRDB-54992

Epic CRDB-55919

### PR DESCRIPTION
**Pull request by log-head**
When a changefeed is planned and executed, there are several places where target table descriptors are fetched. With a db-level changefeed, the set of tables can change during changefeed startup. Now, the timestamp is set to the schema timestamp for retrieving table descriptors.

Adding a schema_ts to the protobuf for ChangeAggregatorSpec and ChangeFrontierSpec.

Fixes: #154549
Epic: CRDB-1421

Release note: None

### CODE REVIEW

File: pkg/ccl/changefeedccl/changefeed_stmt.go [hunk 1]
```diff
@@ -1739,7 +1739,13 @@ func (b *changefeedResumer) resumeWithRetries(
 
 			confPoller := make(chan struct{})
 			g := ctxgroup.WithContext(ctx)
-			targets, err := AllTargets(ctx, details, execCfg)
+			var changefeedStartTS hlc.Timestamp
+			if h := localState.progress.GetHighWater(); h != nil && !h.IsEmpty() {
```
Comment (aerfrei) [inline pkg/ccl/changefeedccl/changefeed_stmt.go]: Is the localstate highwater the right thing to have here so long as it's set? When do we expect to end up in each branch of this if?

Nit: initializing changefeedStartTS with an immediately invoked function might allow you to do early returns and might be a little nicer here.

File: pkg/ccl/changefeedccl/changefeed_test.go [hunk 2]
```diff
@@ -12785,3 +12773,36 @@ func TestCreateTableLevelChangefeedWithDBPrivilege(t *testing.T) {
...
+			go func() {
+				defer wg.Done()
+				sqlDB.Exec(t, fmt.Sprintf(`CREATE TABLE foo%d (a INT PRIMARY KEY, b STRING)`, i))
+				sqlDB.Exec(t, fmt.Sprintf(`INSERT INTO foo%d VALUES (0, 'initial')`, i))
+				sqlDB.Exec(t, fmt.Sprintf(`UPSERT INTO foo%d VALUES (0, 'updated')`, i))
+			}()
+		}
+		wg.Wait()
+		assertPayloads(t, foo, []string{
+			`foo: [0]->{"after": {"a": 0, "b": "updated"}}`,
```
Comment (aerfrei) [inline pkg/ccl/changefeedccl/changefeed_test.go]: Can you leave a top level comment about what this test does? It wasn't immediately obvious to me.

I was also confused by why we make 10 tables and why we insert and update into each of them. I saw that this failed on master even with 1 table and a only a create. Maybe it's worth cutting that down to make it a little clearer what's needed for this to fail.

File: pkg/ccl/changefeedccl/alter_changefeed_stmt.go [hunk 3]
```diff
@@ -448,7 +448,7 @@ func generateAndValidateNewTargets(
 		return nil, nil, hlc.Timestamp{}, nil, err
 	}
 
-	prevTargets, err := AllTargets(ctx, prevDetails, p.ExecCfg())
+	prevTargets, err := AllTargets(ctx, prevDetails, p.ExecCfg(), statementTime)
```
Comment (aerfrei) [inline pkg/ccl/changefeedccl/alter_changefeed_stmt.go]: In this case we're altering a changefeed and getting the previous targets (i.e. before the alter). Is the right timestamp for this the statement time or something like prevProgress.GetHighWater()? My sense is it shouldn't make much of a difference, both should be at the same schema version etc and neither should have been GC'd.

File: pkg/ccl/changefeedccl/changefeed_processors.go [hunk 4]
```diff
@@ -378,7 +378,7 @@ func (ca *changeAggregator) Start(ctx context.Context) {
 	if ca.knobs.OverrideExecCfg != nil {
 		execCfg = ca.knobs.OverrideExecCfg(execCfg)
 	}
-	ca.targets, err = AllTargets(ctx, ca.spec.Feed, execCfg)
+	ca.targets, err = AllTargets(ctx, ca.spec.Feed, execCfg, *ca.spec.SchemaTs)
```
Comment (aerfrei) [inline pkg/ccl/changefeedccl/changefeed_processors.go]: Since the schemaTs is marked as optional, do we need to check here in case it's null? Perhaps it shouldn't be optional.

Also confirming that since we expect to restart changefeeds on schemaChanges, this schemaTs should never need to be updated and it's never inaccurate. 

nit: I think our preferred capitalization is SchemaTS

File: pkg/sql/execinfrapb/processors_changefeeds.proto [hunk 5]
```diff
@@ -68,6 +68,8 @@ message ChangeAggregatorSpec {
   // ResolvedSpans contains the resolved spans that should be restored
   // when the changefeed resumes.
   repeated cockroach.sql.jobs.jobspb.ResolvedSpan resolved_spans = 11 [(gogoproto.nullable) = false];
+
+  optional util.hlc.Timestamp schema_ts = 12;
```
Comment (aerfrei) [inline pkg/sql/execinfrapb/processors_changefeeds.proto]: I think you should call out that we're adding a timestamp into the spec in the commit body/PR desc but that change seems appropriate.

File: pkg/ccl/changefeedccl/enriched_source_provider.go [hunk 6]
```diff
@@ -548,13 +552,16 @@ func init() {
...
 func getDescriptors(
-	ctx context.Context, execCfg *sql.ExecutorConfig, tableID descpb.ID,
+	ctx context.Context, execCfg *sql.ExecutorConfig, tableID descpb.ID, schemaTS hlc.Timestamp,
 ) (catalog.TableDescriptor, catalog.DatabaseDescriptor, catalog.SchemaDescriptor, error) {
 	var tableDescriptor catalog.TableDescriptor
 	var dbDescriptor catalog.DatabaseDescriptor
 	var schemaDescriptor catalog.SchemaDescriptor
 	var err error
 	f := func(ctx context.Context, txn descs.Txn) error {
+		if err := txn.KV().SetFixedTimestamp(ctx, schemaTS); err != nil {
```
Comment (aerfrei) [inline pkg/ccl/changefeedccl/enriched_source_provider.go:562]: Is there a scenario where this fails in a similar way to what we're seeing elsewhere? If so, a test for that case would be cool.

File: pkg/ccl/changefeedccl/changefeed_stmt.go (hunk 1 above)
Comment (log-head) [reply pkg/ccl/changefeedccl/changefeed_stmt.go]: This logic was taken from distChangefeedFlow, which computed the highWater and schemaTS before starting the changefeed. I've broken out computing those two timestamps into computeDistChangefeedTimestamps.

To answer your question, this part was just to use the highwater if it already exists (changefeed resuming after pause or restart); otherwise, since there's no highwater, start from the statement time.

File: pkg/ccl/changefeedccl/alter_changefeed_stmt.go (hunk 3 above)
Comment (log-head) [reply pkg/ccl/changefeedccl/alter_changefeed_stmt.go]: Good callout, fixed this.

File: pkg/ccl/changefeedccl/changefeed_processors.go (hunk 4 above)
Comment (log-head) [reply pkg/ccl/changefeedccl/changefeed_processors.go]: Yes, need to check if it's null. Added that.

That's right, it's just for when the changefeed is first being started.

The capitalization for this is auto-generated from the protobuf, where it's schema_ts.

Comment (aerfrei) [reply pkg/ccl/changefeedccl/changefeed_processors.go]: You can override this with gogoproto.customname

File: pkg/ccl/changefeedccl/enriched_source_provider.go (hunk 6 above)
Comment (log-head) [reply pkg/ccl/changefeedccl/enriched_source_provider.go:562]: Made a unit test for this, similar to the others, but not able to get it to fail on master.

File: pkg/ccl/changefeedccl/changefeed_test.go (hunk 2 above)
Comment (aerfrei) [reply pkg/ccl/changefeedccl/changefeed_test.go]: Why are we introducing a channel here to create the tables? Is it there to make the test fail more consistently? 
If with a single table add and insert it fails consistently and quickly under stress, I think it might be worth it for the simplicity.

File: pkg/ccl/changefeedccl/changefeed_dist.go [hunk 7]
```diff
@@ -74,6 +74,7 @@ const (
 // timestamp is emitted into the changefeed sink (or returned to the gateway if
 // there is no sink) whenever it advances. ChangeFrontier also updates the
 // progress of the changefeed's corresponding system job.
+
```
Comment (aerfrei) [inline pkg/ccl/changefeedccl/changefeed_dist.go]: nit: remove

File: pkg/ccl/changefeedccl/alter_changefeed_stmt.go [hunk 8]
```diff
@@ -448,7 +448,15 @@ func generateAndValidateNewTargets(
 		return nil, nil, hlc.Timestamp{}, nil, err
 	}
 
-	prevTargets, err := AllTargets(ctx, prevDetails, p.ExecCfg())
+	targetTS := prevProgress.GetHighWater()
+	if targetTS == nil || targetTS.IsEmpty() {
+		targetTS = &prevDetails.StatementTime
+	}
+	// targetTS := statementTime
```
Comment (aerfrei) [inline pkg/ccl/changefeedccl/alter_changefeed_stmt.go]: I'm assuming this was left in by mistake.

File: pkg/ccl/changefeedccl/changefeed_test.go [hunk 9]
```diff
@@ -12773,3 +12773,163 @@ func TestCreateTableLevelChangefeedWithDBPrivilege(t *testing.T) {
...
+			knobs.DistSQL = &execinfra.TestingKnobs{}
+		}
+		if knobs.DistSQL.(*execinfra.TestingKnobs).Changefeed == nil {
+			knobs.DistSQL.(*execinfra.TestingKnobs).Changefeed = &TestingKnobs{}
+		}
+		cfKnobs := knobs.DistSQL.(*execinfra.TestingKnobs).Changefeed.(*TestingKnobs)
+		cfKnobs.TablesetChangingCallback = func() {
+			select {
+			case startMakingTables <- struct{}{}:
+				// signal the test once; non-blocking
```
Comment (aerfrei) [inline pkg/ccl/changefeedccl/changefeed_test.go]: nit: We prefer comments to be full sentences.

File: pkg/ccl/changefeedccl/changefeed_test.go (hunk 2 above)
Comment (log-head) [reply pkg/ccl/changefeedccl/changefeed_test.go]: Good point about just needing to add a single table to make it fail, changed that, fails consistently on master. The channel here is to time adding the table to be during the changefeed being started.

**Review by aerfrei — APPROVED** [review]

File: pkg/ccl/changefeedccl/testing_knobs.go [hunk 10]
```diff
@@ -128,6 +123,8 @@ type TestingKnobs struct {
 	// MakeKVFeedToAggregatorBufferKnobs is used to make a fresh set of testing knobs
 	// to pass to the constructor of the kv feed to change aggregator buffer.
 	MakeKVFeedToAggregatorBufferKnobs func() kvevent.BlockingBufferTestingKnobs
+
+	TablesetChangingCallback func()
```
Comment (andyyang890) [inline pkg/ccl/changefeedccl/testing_knobs.go]: Could you add a comment documenting what this knob is for?

File: pkg/sql/execinfrapb/processors_changefeeds.proto [hunk 11]
```diff
@@ -68,6 +68,8 @@ message ChangeAggregatorSpec {
   // ResolvedSpans contains the resolved spans that should be restored
   // when the changefeed resumes.
   repeated cockroach.sql.jobs.jobspb.ResolvedSpan resolved_spans = 11 [(gogoproto.nullable) = false];
+
+  optional util.hlc.Timestamp schema_ts = 12 [(gogoproto.customname) = "SchemaTS"];
```
Comment (andyyang890) [inline pkg/sql/execinfrapb/processors_changefeeds.proto:74]: Could you add a comment for this field? Ditto for `ChangeFrontierSpec`

File: pkg/ccl/changefeedccl/changefeed_processors.go [hunk 12]
```diff
@@ -378,7 +378,11 @@ func (ca *changeAggregator) Start(ctx context.Context) {
 	if ca.knobs.OverrideExecCfg != nil {
 		execCfg = ca.knobs.OverrideExecCfg(execCfg)
 	}
-	ca.targets, err = AllTargets(ctx, ca.spec.Feed, execCfg)
+	targetTS := ca.spec.SchemaTS
```
Comment (andyyang890) [inline pkg/ccl/changefeedccl/changefeed_processors.go]: Considering the number of times we do this if statement, could we define a `GetSchemaTS() hlc.Timestamp` receiver on `ChangeAggregatorSpec`?

ditto for `ChangeFrontierSpec`

File: pkg/ccl/changefeedccl/changefeed_test.go [hunk 13]
```diff
@@ -12772,3 +12773,129 @@ func TestCreateTableLevelChangefeedWithDBPrivilege(t *testing.T) {
...
+			sqlDB.Exec(t, `INSERT INTO bar VALUES (0, 'initial')`)
+		}()
+		foo := feed(t, f, `CREATE CHANGEFEED FOR DATABASE d`)
+		defer closeFeed(t, foo)
+		assertPayloads(t, foo, []string{
+			`foo: [0]->{"after": {"a": 0, "b": "updated"}}`,
+		})
+		wg.Wait()
+	}
+	cdcTest(t, testFnAdd, withKnobsFn(knobsFn), feedTestForceSink("enterprise"))
```
Comment (andyyang890) [inline pkg/ccl/changefeedccl/changefeed_test.go]: Could we make the sink type unrestricted for these tests?

File: pkg/ccl/changefeedccl/changefeed_stmt.go [hunk 14]
```diff
@@ -1757,13 +1743,22 @@ func (b *changefeedResumer) resumeWithRetries(
...
+			initialHighWater, schemaTS, err := computeDistChangefeedTimestamps(ctx, jobExec, details, localState)
+			if err != nil {
+				return err
+			}
+			targets, err := AllTargets(ctx, details, execCfg, schemaTS)
 			if err != nil {
 				return err
 			}
+			maybeCfKnobs, haveKnobs := execCfg.DistSQLSrv.TestingKnobs.Changefeed.(*TestingKnobs)
+			if haveKnobs && maybeCfKnobs.TablesetChangingCallback != nil {
```
Comment (andyyang890) [inline pkg/ccl/changefeedccl/changefeed_stmt.go]: `AllTargets` is called in multiple places, could you explain why this site was picked for `TablesetChangingCallback`?

Comment (log-head) [reply pkg/ccl/changefeedccl/changefeed_stmt.go]: All the other `AllTargets` invocations happen after this one executes. I made a change to put the testing knob before this one as well. Really, trying to have the tableset change after the `schemaTS` is set from `computeDistChangefeedTimestamps`.

Also, adding `TablesetChangingCallback` in `coreChangefeeds` to run for sinkless changefeeds, per your testing comment.

File: pkg/ccl/changefeedccl/changefeed_test.go (hunk 13 above)
Comment (log-head) [reply pkg/ccl/changefeedccl/changefeed_test.go]: We can for this first one! Added the testing knob for sinkless changefeeds. Can't for the 2nd test as it involves pausing/resuming the changefeed.

Added more sink types for the 3rd test for enriched envelopes.

File: pkg/ccl/changefeedccl/testing_knobs.go (hunk 10 above)
Comment (log-head) [reply pkg/ccl/changefeedccl/testing_knobs.go]: done

File: pkg/ccl/changefeedccl/changefeed_processors.go (hunk 12 above)
Comment (log-head) [reply pkg/ccl/changefeedccl/changefeed_processors.go]: done

File: pkg/sql/execinfrapb/processors_changefeeds.proto (hunk 11 above)
Comment (log-head) [reply pkg/sql/execinfrapb/processors_changefeeds.proto:74]: done

File: pkg/ccl/changefeedccl/changefeed_test.go [hunk 15]
```diff
@@ -12772,3 +12773,137 @@ func TestCreateTableLevelChangefeedWithDBPrivilege(t *testing.T) {
...
+			}()
+			sqlDB.Exec(t, `RESUME ALL CHANGEFEED JOBS`)
+			assertPayloads(t, baseFeed, []string{
+				`foo: [0]->{"after": {"a": 0, "b": "initial"}}`,
+				// Don't expect bar because it was created after the changefeed was
+				// paused. The changefeed resumes from where it left off.
+			})
+			wg.Wait()
+		}
+		cdcTest(t, testFnAddDuringResume, withKnobsFn(knobsFn), feedTestForceSink("enterprise"))
```
Comment (andyyang890) [inline pkg/ccl/changefeedccl/changefeed_test.go]: I think what you actually want here is `feedTestEnterpriseSinks`, `"enterprise"` is a specific SQL table-based sink (confusing, I know)

File: pkg/sql/execinfrapb/api.go [hunk 16]
```diff
@@ -60,11 +61,29 @@ func (m *ChangeAggregatorSpec) User() username.SQLUsername {
 	return m.UserProto.Decode()
 }
 
+// GetSchemaTS returns the schema timestamp to use. If SchemaTS is nil or empty,
+// it returns a pointer to Feed.StatementTime; otherwise it returns SchemaTS.
+func (m *ChangeAggregatorSpec) GetSchemaTS() *hlc.Timestamp {
```
Comment (andyyang890) [inline pkg/sql/execinfrapb/api.go]: Could we make these functions return `hlc.Timestamp` instead? Doing so would help us avoid some extra pointer dereferences and help us be confident at the call site that we're not going to dereference a nil pointer

nit: I'd also prefer if the conditions were reversed, so that it was `if m.SchemaTS != nil && m.SchemaTS.IsSet()`

File: pkg/ccl/changefeedccl/testing_knobs.go (hunk 10 above)
Comment (andyyang890) [reply pkg/ccl/changefeedccl/testing_knobs.go]: Hmm I think the comment should document when the hook is called and not what an example use case could be. You can take a look at the other comments in this struct for examples.

File: pkg/ccl/changefeedccl/changefeed_stmt.go [hunk 17]
```diff
@@ -1757,13 +1747,22 @@ func (b *changefeedResumer) resumeWithRetries(
...
+			}
+			maybeCfKnobs, haveKnobs := execCfg.DistSQLSrv.TestingKnobs.Changefeed.(*TestingKnobs)
+			if haveKnobs && maybeCfKnobs.TablesetChangingCallback != nil {
+				maybeCfKnobs.TablesetChangingCallback()
+			}
 			g.GoCtx(func(ctx context.Context) error {
 				defer close(confPoller)
-				return distChangefeedFlow(ctx, jobExec, jobID, details, description, localState, startedCh, onTracingEvent, targets)
+				return startDistChangefeed(ctx, jobExec, jobID, schemaTS, details, description, initialHighWater, localState, startedCh, onTracingEvent, targets)
+
```
Comment (andyyang890) [inline pkg/ccl/changefeedccl/changefeed_stmt.go]: nit: remove extra newline and split long line

File: pkg/ccl/changefeedccl/changefeed_stmt.go (hunk 14 above)
Comment (andyyang890) [reply pkg/ccl/changefeedccl/changefeed_stmt.go]: Hmm ok, I wonder if this hook should actually be called after this line where we fetch the table descriptors and be renamed `AfterFetchTableDescriptors`, WDYT?https://github.com/cockroachdb/cockroach/blob/7d4d3c92d7f96d5dda130a651214c677416fbdec/pkg/ccl/changefeedccl/changefeed_dist.go#L235

One additional benefit of that is you'd get it for sinkless changefeeds for free as well

File: pkg/ccl/changefeedccl/changefeed_test.go [hunk 18]
```diff
@@ -12772,3 +12773,137 @@ func TestCreateTableLevelChangefeedWithDBPrivilege(t *testing.T) {
...
+				`foo: {"a": 0}->{"after": {"a": 0, "b": "initial"}, "op": "c"}`,
+			}, func(source map[string]any) {
+				require.NotNil(t, source)
+				require.Equal(t, "d", source["database_name"])
+				require.Equal(t, "foo", source["table_name"])
+				require.Equal(t, []any{"a"}, source["primary_keys"])
+			})
+			wg.Wait()
+		}
+		supportedSinks := []string{"kafka", "pubsub", "sinkless", "webhook"}
```
Comment (andyyang890) [inline pkg/ccl/changefeedccl/changefeed_test.go:12910]: Would you mind documenting why the other sinks won't work? I'd also prefer if this was a `feedTestOmitSinks` instead of a for loop

File: pkg/ccl/changefeedccl/changefeed_stmt.go (hunk 14 above)
Comment (log-head) [reply pkg/ccl/changefeedccl/changefeed_stmt.go]: I think that would miss testing `AllTargets` from `resumeWithRetries`. `fetchTableDescriptors` fetches the descriptors of that previous `AllTargets`, so it would only fetch incorrect table descriptors if the previous `AllTargets` did.

File: pkg/ccl/changefeedccl/changefeed_test.go (hunk 18 above)
Comment (log-head) [reply pkg/ccl/changefeedccl/changefeed_test.go:12910]: Enriched envelopes are only supported for these sink types. So I feel it's better to whitelist the ones that are allowed, rather than specify which are omitted in case a new sink type is added which doesn't support enriched envelopes.
https://www.cockroachlabs.com/docs/stable/changefeed-message-envelopes#enriched

File: pkg/ccl/changefeedccl/changefeed.go
Comment (andyyang890) [inline pkg/ccl/changefeedccl/changefeed.go:1]: (leaving this here because unlike reviewable, github doesn't let you directly comment on commit messages)

nit: don't capitalize the title after the package prefix https://cockroachlabs.atlassian.net/wiki/spaces/CRDB/pages/73072807/Git+Commit+Messages#Commit-title

File: pkg/ccl/changefeedccl/changefeed_stmt.go (hunk 14 above)
Comment (andyyang890) [reply pkg/ccl/changefeedccl/changefeed_stmt.go]: Ah ok, how would you feel about calling the hook `AfterComputeDistChangefeedTimestamps` instead then given that seems to be the event the hook directly follows?

My main concern with the current name is it it's not clear to me why this specific site is related to table sets.

File: pkg/ccl/changefeedccl/changefeed_test.go [hunk 19]
```diff
@@ -12772,3 +12773,138 @@ func TestCreateTableLevelChangefeedWithDBPrivilege(t *testing.T) {
...
+			go func() {
+				defer wg.Done()
+				<-createAnotherTable
+				sqlDB.Exec(t, `CREATE TABLE bar (a INT PRIMARY KEY, b STRING)`)
+				sqlDB.Exec(t, `INSERT INTO bar VALUES (0, 'initial')`)
+			}()
+			foo := feed(t, f, `CREATE CHANGEFEED FOR foo WITH envelope='enriched', enriched_properties='source'`)
+			defer closeFeed(t, foo)
+			assertPayloadsEnriched(t, foo, []string{
+				`foo: {"a": 0}->{"after": {"a": 0, "b": "initial"}, "op": "c"}`,
```
Comment (andyyang890) [inline pkg/ccl/changefeedccl/changefeed_test.go:12898]: Could you add a similar comment as you did in the previous subtest about not expecting bar to show up?

File: pkg/ccl/changefeedccl/changefeed_test.go [hunk 20]
```diff
@@ -12772,3 +12773,138 @@ func TestCreateTableLevelChangefeedWithDBPrivilege(t *testing.T) {
...
+			go func() {
+				defer wg.Done()
+				<-createAnotherTable
+				sqlDB.Exec(t, `CREATE TABLE bar (a INT PRIMARY KEY, b STRING)`)
+				sqlDB.Exec(t, `INSERT INTO bar VALUES (0, 'initial')`)
+			}()
+			foo := feed(t, f, `CREATE CHANGEFEED FOR DATABASE d`)
+			defer closeFeed(t, foo)
+			assertPayloads(t, foo, []string{
+				`foo: [0]->{"after": {"a": 0, "b": "updated"}}`,
```
Comment (andyyang890) [inline pkg/ccl/changefeedccl/changefeed_test.go:12827]: Could you add a similar comment as you have in the subtest below about not expecting bar to show up?

File: pkg/ccl/changefeedccl/changefeed_test.go [hunk 21]
```diff
@@ -12772,3 +12773,138 @@ func TestCreateTableLevelChangefeedWithDBPrivilege(t *testing.T) {
...
+			wg.Add(1)
+			// goroutine to make tables. Signaled to begin creating tables from test
+			// knob callback after resumeWithRetries picks the first targets.
+			go func() {
+				defer wg.Done()
+				<-createAnotherTable
+				sqlDB.Exec(t, `CREATE TABLE baz (a INT PRIMARY KEY, b STRING)`)
+				sqlDB.Exec(t, `INSERT INTO baz VALUES (0, 'initial')`)
+			}()
+			sqlDB.Exec(t, `RESUME ALL CHANGEFEED JOBS`)
```
Comment (andyyang890) [inline pkg/ccl/changefeedccl/changefeed_test.go]: nit: use `jobFeed.Resume()` instead

File: pkg/ccl/changefeedccl/changefeed_test.go [hunk 22]
```diff
@@ -12772,3 +12773,138 @@ func TestCreateTableLevelChangefeedWithDBPrivilege(t *testing.T) {
...
+			defer closeFeed(t, foo)
+			assertPayloads(t, foo, []string{
+				`foo: [0]->{"after": {"a": 0, "b": "updated"}}`,
+			})
+			wg.Wait()
+		}
+		cdcTest(t, testFnAdd, withKnobsFn(knobsFn))
+	})
+
+	createAnotherTable = make(chan struct{}, 1)
```
Comment (andyyang890) [inline pkg/ccl/changefeedccl/changefeed_test.go]: nit: I don't think you actually need to create another channel here since you never close the channel

File: pkg/ccl/changefeedccl/changefeed_test.go [hunk 23]
```diff
@@ -12772,3 +12773,138 @@ func TestCreateTableLevelChangefeedWithDBPrivilege(t *testing.T) {
...
+				require.Equal(t, "d", source["database_name"])
+				require.Equal(t, "foo", source["table_name"])
+				require.Equal(t, []any{"a"}, source["primary_keys"])
+			})
+			wg.Wait()
+		}
+		// Enriched envelope option is supported only for these sink types.
+		supportedSinks := []string{"kafka", "pubsub", "sinkless", "webhook"}
+		for _, sink := range supportedSinks {
+			createAnotherTable = make(chan struct{}, 1)
```
Comment (andyyang890) [inline pkg/ccl/changefeedccl/changefeed_test.go]: nit: don't think you need to create new channels here either

**Review by andyyang890 — COMMENTED** [review]
Looking good! Just have a few more minor comments

**Review by andyyang890 — APPROVED** [review]
LGTM!

File: pkg/ccl/changefeedccl/changefeed_test.go [hunk 24]
```diff
@@ -12772,3 +12773,143 @@ func TestCreateTableLevelChangefeedWithDBPrivilege(t *testing.T) {
...
+		}
+		cfKnobs := knobs.DistSQL.(*execinfra.TestingKnobs).Changefeed.(*TestingKnobs)
+		cfKnobs.AfterComputeDistChangefeedTimestamps = func(ctx context.Context) {
+			select {
+			case createAnotherTable <- struct{}{}:
+				// This signals the test in a non-blocking way to create tables.
+			case <-time.After(5 * time.Second):
+				t.Error("callback timed out waiting for table creation")
+			case <-ctx.Done():
+				t.Error("context canceled")
```
Comment (andyyang890) [inline pkg/ccl/changefeedccl/changefeed_test.go]: Do we need to error when the context gets canceled? Could we just have an empty case/return here?

File: pkg/ccl/changefeedccl/changefeed_test.go [hunk 25]
```diff
@@ -12772,3 +12772,146 @@ func TestCreateTableLevelChangefeedWithDBPrivilege(t *testing.T) {
 	}
 	cdcTest(t, testFn, feedTestEnterpriseSinks)
 }
+
+func TestDatabaseLevelChangefeedChangingTableset(t *testing.T) {
+	defer leaktest.AfterTest(t)()
+	defer log.Scope(t).Close(t)
+
+	// createAnotherTable := make(chan struct{}, 1)
```
Comment (andyyang890) [inline pkg/ccl/changefeedccl/changefeed_test.go]: nit: delete unused code

File: pkg/ccl/changefeedccl/changefeed_test.go [hunk 26]
```diff
@@ -12772,3 +12772,146 @@ func TestCreateTableLevelChangefeedWithDBPrivilege(t *testing.T) {
...
+
+	makeKnobs := func(sigCh chan struct{}) func(*base.TestingKnobs) {
```
Comment (andyyang890) [inline pkg/ccl/changefeedccl/changefeed_test.go]: Do you think we could retain the `createAnotherTable` name? Or maybe `createTableCh`? It helps make it more clear what the purpose of the channel is.

File: pkg/ccl/changefeedccl/changefeed_test.go [hunk 27]
```diff
@@ -12772,3 +12772,146 @@ func TestCreateTableLevelChangefeedWithDBPrivilege(t *testing.T) {
...
+			if knobs.DistSQL.(*execinfra.TestingKnobs).Changefeed == nil {
+				knobs.DistSQL.(*execinfra.TestingKnobs).Changefeed = &TestingKnobs{}
+			}
+			cfKnobs := knobs.DistSQL.(*execinfra.TestingKnobs).Changefeed.(*TestingKnobs)
+			cfKnobs.AfterComputeDistChangefeedTimestamps = func(ctx context.Context) {
+				select {
+				case sigCh <- struct{}{}:
+					// signal delivered
+				case <-time.After(5 * time.Second):
+					t.Error("callback timed out waiting for table creation signal to be consumed")
```
Comment (andyyang890) [inline pkg/ccl/changefeedccl/changefeed_test.go:12794]: I wonder if the `t.Fatal` that you had before would be more appropriate here, but if it works, it works

**Review by andyyang890 — APPROVED** [review]
