### PR TITLE
Fix idempotence test with multiple CPUs

### LINKED ISSUE #1434: TestRangeIdempotence fails with multiple CPUs
repro:
```
for i in {0..10}; do go test -run TestRangeIdempotence -cpu 1,2 ./storage -timeout 15s; done
```

Subtask of #1406.

### PR DESCRIPTION
**Pull request by spencerkimball**
Fixes #1434

### CODE REVIEW

**Comment by tamird** [comment]
LGTM

**Comment by tamird** [comment]
LGTM again

File: storage/range_test.go [hunk 1]
```diff
@@ -1331,47 +1332,41 @@ func TestRangeIdempotence(t *testing.T) {
...
-			}
-			if idx%2 == 0 && reply.NewValue != 1 {
-				t.Errorf("expected all incremented values to be 1; got %d", reply.NewValue)
-			} else if idx%2 == 1 {
-				atomic.AddInt64(&count, reply.NewValue)
-			}
-			close(incDones[idx])
-		}()
+	wg.Add(numIncs)
+	incFunc(0) // run first iteration without concurrency.
```
Comment (tschottdorf) [inline storage/range_test.go]: what's this for?

**Comment by tschottdorf** [comment]
LGTM.

File: storage/range_test.go (hunk 1 above)
Comment (tamird) [inline storage/range_test.go]: the assertions for the even-numbered half of this test look for a hardcoded value of `1`, so we have to make sure the first iteration that actually runs is even-numbered so that the cached response for that command ID has a value of 1. Otherwise, N odd-numbered operations may get scheduled first, run with a different command ID, and cause even-numbered operations to report something other than 1, depending on the value of N.

Comment (tschottdorf) [inline storage/range_test.go]: :+1:
