### PR TITLE
colexec: use redact.RedactableString for types in cast error message

### LINKED ISSUE #90760: sql: mark type strings as safe from redacting
This issue was autofiled by Sentry. It represents a crash or reported error on a live cluster with telemetry enabled.

Sentry link: https://sentry.io/organizations/cockroach-labs/issues/3700849185/?referrer=webhooks_plugin

Panic message:

>error.go:89: unexpected error from the vectorized engine: unhandled cast × -> ×
(1) assertion failure
Wraps: (2) attached stack trace
  -- stack trace:
  | github.com/cockroachdb/cockroach/pkg/sql/colexecerror.CatchVectorizedRuntimeError.func1
  | 	github.com/cockroachdb/cockroach/pkg/sql/colexecerror/error.go:89
  | runtime.gopanic
  | 	GOROOT/src/runtime/panic.go:1038
  | github.com/cockroachdb/cockroach/pkg/sql/colexecerror.InternalError
  | 	github.com/cockroachdb/cockroach/pkg/sql/colexecerror/error.go:193
  | github.com/cockroachdb/cockroach/pkg/sql/colexec/colbuilder.NewColOperator
  | 	github.com/cockroachdb/cockroach/pkg/sql/colexec/colbuilder/execplan.go:1241
  | github.com/cockroachdb/cockroach/pkg/sql/colflow.(*vectorizedFlowCreator).setupFlow.func1
  | 	github.com/cockroachdb/cockroach/pkg/sql/colflow/vectorized_flow.go:1183
  | github.com/cockroachdb/cockroach/pkg/sql/colexecerror.CatchVectorizedRuntimeError
  | 	github.com/cockroachdb/cockroach/pkg/sql/colexecerror/error.go:92
  | github.com/cockroachdb/cockroach/pkg/sql/colflow.(*vectorizedFlowCreator).setupFlow
  | 	github.com/cockroachdb/cockroach/pkg/sql/colflow/vectorized_flow.go:1122
  | github.com/cockroachdb/cockroach/pkg/sql/colflow.(*vectorizedFlow).Setup
  | 	github.com/cockroachdb/cockroach/pkg/sql/colflow/vectorized_flow.go:275
  | github.com/cockroachdb/cockroach/pkg/sql/distsql.(*ServerImpl).setupFlow
  | 	github.com/cockroachdb/cockroach/pkg/sql/distsql/server.go:411
  | github.com/cockroachdb/cockroach/pkg/sql/distsql.(*ServerImpl).SetupLocalSyncFlow
  | 	github.com/cockroachdb/cockroach/pkg/sql/distsql/server.go:584
  | github.com/cockroachdb/cockroach/pkg/sql.(*DistSQLPlanner).setupFlows
  | 	github.com/cockroachdb/cockroach/pkg/sql/distsql_running.go:373
  | github.com/cockroachdb/cockroach/pkg/sql.(*DistSQLPlanner).Run
  | 	github.com/cockroachdb/cockroach/pkg/sql/distsql_running.go:555
  | github.com/cockroachdb/cockroach/pkg/sql.(*DistSQLPlanner).planAndRunSubquery
  | 	github.com/cockroachdb/cockroach/pkg/sql/distsql_running.go:1313
  | github.com/cockroachdb/cockroach/pkg/sql.(*DistSQLPlanner).PlanAndRunSubqueries
  | 	github.com/cockroachdb/cockroach/pkg/sql/distsql_running.go:1213
  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execWithDistSQLEngine
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:1497
  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).dispatchToExecutionEngine
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:1163
  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execStmtInOpenState
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:699
  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execStmt
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:144
  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execCmd.func1
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:1891
  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execCmd
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:1895
  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).run
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:1817
  | github.com/cockroachdb/cockroach/pkg/sql.(*Server).ServeConn
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:763
  | github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*conn).processCommandsAsync.func1
  | 	github.com/cockroachdb/cockroach/pkg/sql/pgwire/conn.go:728
  | runtime.goexit
  | 	GOROOT/src/runtime/asm_amd64.s:1581
Wraps: (3) unexpected error from the vectorized engine
Wraps: (4) unhandled cast × -> ×
  | -- cause hidden behind barrier
  | unhandled cast × -> ×
  | (1) attached stack trace
  |   -- stack trace:
  |   | github.com/cockroachdb/cockroach/pkg/sql/colexec/colexecbase.GetCastOperator
  |   | 	github.com/cockroachdb/cockroach/bazel-out/k8-opt/bin/pkg/sql/colexec/colexecbase/cast.eg.go:452
  |   | github.com/cockroachdb/cockroach/pkg/sql/colexec/colbuilder.NewColOperator
  |   | 	github.com/cockroachdb/cockroach/pkg/sql/colexec/colbuilder/execplan.go:1236
  |   | github.com/cockroachdb/cockroach/pkg/sql/colflow.(*vectorizedFlowCreator).setupFlow.func1
  |   | 	github.com/cockroachdb/cockroach/pkg/sql/colflow/vectorized_flow.go:1183
  |   | github.com/cockroachdb/cockroach/pkg/sql/colexecerror.CatchVectorizedRuntimeError
  |   | 	github.com/cockroachdb/cockroach/pkg/sql/colexecerror/error.go:92
  |   | github.com/cockroachdb/cockroach/pkg/sql/colflow.(*vectorizedFlowCreator).setupFlow
  |   | 	github.com/cockroachdb/cockroach/pkg/sql/colflow/vectorized_flow.go:1122
  |   | github.com/cockroachdb/cockroach/pkg/sql/colflow.(*vectorizedFlow).Setup
  |   | 	github.com/cockroachdb/cockroach/pkg/sql/colflow/vectorized_flow.go:275
  |   | github.com/cockroachdb/cockroach/pkg/sql/distsql.(*ServerImpl).setupFlow
  |   | 	github.com/cockroachdb/cockroach/pkg/sql/distsql/server.go:411
  |   | github.com/cockroachdb/cockroach/pkg/sql/distsql.(*ServerImpl).SetupLocalSyncFlow
  |   | 	github.com/cockroachdb/cockroach/pkg/sql/distsql/server.go:584
  |   | github.com/cockroachdb/cockroach/pkg/sql.(*DistSQLPlanner).setupFlows
  |   | 	github.com/cockroachdb/cockroach/pkg/sql/distsql_running.go:373
  |   | github.com/cockroachdb/cockroach/pkg/sql.(*DistSQLPlanner).Run
  |   | 	github.com/cockroachdb/cockroach/pkg/sql/distsql_running.go:555
  |   | github.com/cockroachdb/cockroach/pkg/sql.(*DistSQLPlanner).planAndRunSubquery
  |   | 	github.com/cockroachdb/cockroach/pkg/sql/distsql_running.go:1313
  |   | github.com/cockroachdb/cockroach/pkg/sql.(*DistSQLPlanner).PlanAndRunSubqueries
  |   | 	github.com/cockroachdb/cockroach/pkg/sql/distsql_running.go:1213
  |   | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execWithDistSQLEngine
  |   | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:1497
  |   | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).dispatchToExecutionEngine
  |   | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:1163
  |   | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execStmtInOpenState
  |   | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:699
  |   | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execStmt
  |   | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:144
  |   | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execCmd.func1
  |   | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:1891
  |   | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execCmd
  |   | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:1895
  |   | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).run
  |   | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:1817
  |   | github.com/cockroachdb/cockroach/pkg/sql.(*Server).ServeConn
  |   | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:763
  |   | github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*conn).processCommandsAsync.func1
  |   | 	github.com/cockroachdb/cockroach/pkg/sql/pgwire/conn.go:728
  |   | runtime.goexit
  |   | 	GOROOT/src/runtime/asm_amd64.s:1581
  | Wraps: (2) unhandled cast × -> ×
  | Error types: (1) *withstack.withStack (2) *errutil.leafError
Error types: (1) *assert.withAssertionFailure (2) *withstack.withStack (3) *errutil.withPrefix (4) *barriers.barrierErr
-- report composition:
*barriers.barrierErr: details for github.com/cockroachdb/errors/withstack/*withstack.withStack:::
*errutil.withPrefix: unexpected error from the vectorized engine
error.go:89: *withstack.withStack (top exception)
*assert.withAssertionFailure

<details>
<summary>Stacktrace (expand for inline code snippets):</summary>

https://github.com/cockroachdb/cockroach/blob/e438c2f89282e607e0e6ca1d38b2e0a622f94493/pkg/sql/colexecerror/error.go#L88-L90 in pkg/sql/colexecerror.CatchVectorizedRuntimeError.func1
GOROOT/src/runtime/panic.go#L1037-L1039 in runtime.gopanic
https://github.com/cockroachdb/cockroach/blob/e438c2f89282e607e0e6ca1d38b2e0a622f94493/pkg/sql/colexecerror/error.go#L192-L194 in pkg/sql/colexecerror.InternalError
https://github.com/cockroachdb/cockroach/blob/e438c2f89282e607e0e6ca1d38b2e0a622f94493/pkg/sql/colexec/colbuilder/execplan.go#L1240-L1242 in pkg/sql/colexec/colbuilder.NewColOperator
https://github.com/cockroachdb/cockroach/blob/e438c2f89282e607e0e6ca1d38b2e0a622f94493/pkg/sql/colflow/vectorized_flow.go#L1182-L1184 in pkg/sql/colflow.(*vectorizedFlowCreator).setupFlow.func1
https://github.com/cockroachdb/cockroach/blob/e438c2f89282e607e0e6ca1d38b2e0a622f94493/pkg/sql/colexecerror/error.go#L91-L93 in pkg/sql/colexecerror.CatchVectorizedRuntimeError
https://github.com/cockroachdb/cockroach/blob/e438c2f89282e607e0e6ca1d38b2e0a622f94493/pkg/sql/colflow/vectorized_flow.go#L1121-L1123 in pkg/sql/colflow.(*vectorizedFlowCreator).setupFlow
https://github.com/cockroachdb/cockroach/blob/e438c2f89282e607e0e6ca1d38b2e0a622f94493/pkg/sql/colflow/vectorized_flow.go#L274-L276 in pkg/sql/colflow.(*vectorizedFlow).Setup
https://github.com/cockroachdb/cockroach/blob/e438c2f89282e607e0e6ca1d38b2e0a622f94493/pkg/sql/distsql/server.go#L410-L412 in pkg/sql/distsql.(*ServerImpl).setupFlow
https://github.com/cockroachdb/cockroach/blob/e438c2f89282e607e0e6ca1d38b2e0a622f94493/pkg/sql/distsql/server.go#L583-L585 in pkg/sql/distsql.(*ServerImpl).SetupLocalSyncFlow
https://github.com/cockroachdb/cockroach/blob/e438c2f89282e607e0e6ca1d38b2e0a622f94493/pkg/sql/distsql_running.go#L372-L374 in pkg/sql.(*DistSQLPlanner).setupFlows
https://github.com/cockroachdb/cockroach/blob/e438c2f89282e607e0e6ca1d38b2e0a622f94493/pkg/sql/distsql_running.go#L554-L556 in pkg/sql.(*DistSQLPlanner).Run
https://github.com/cockroachdb/cockroach/blob/e438c2f89282e607e0e6ca1d38b2e0a622f94493/pkg/sql/distsql_running.go#L1312-L1314 in pkg/sql.(*DistSQLPlanner).planAndRunSubquery
https://github.com/cockroachdb/cockroach/blob/e438c2f89282e607e0e6ca1d38b2e0a622f94493/pkg/sql/distsql_running.go#L1212-L1214 in pkg/sql.(*DistSQLPlanner).PlanAndRunSubqueries
https://github.com/cockroachdb/cockroach/blob/e438c2f89282e607e0e6ca1d38b2e0a622f94493/pkg/sql/conn_executor_exec.go#L1496-L1498 in pkg/sql.(*connExecutor).execWithDistSQLEngine
https://github.com/cockroachdb/cockroach/blob/e438c2f89282e607e0e6ca1d38b2e0a622f94493/pkg/sql/conn_executor_exec.go#L1162-L1164 in pkg/sql.(*connExecutor).dispatchToExecutionEngine
https://github.com/cockroachdb/cockroach/blob/e438c2f89282e607e0e6ca1d38b2e0a622f94493/pkg/sql/conn_executor_exec.go#L698-L700 in pkg/sql.(*connExecutor).execStmtInOpenState
https://github.com/cockroachdb/cockroach/blob/e438c2f89282e607e0e6ca1d38b2e0a622f94493/pkg/sql/conn_executor_exec.go#L143-L145 in pkg/sql.(*connExecutor).execStmt
https://github.com/cockroachdb/cockroach/blob/e438c2f89282e607e0e6ca1d38b2e0a622f94493/pkg/sql/conn_executor.go#L1890-L1892 in pkg/sql.(*connExecutor).execCmd.func1
https://github.com/cockroachdb/cockroach/blob/e438c2f89282e607e0e6ca1d38b2e0a622f94493/pkg/sql/conn_executor.go#L1894-L1896 in pkg/sql.(*connExecutor).execCmd
https://github.com/cockroachdb/cockroach/blob/e438c2f89282e607e0e6ca1d38b2e0a622f94493/pkg/sql/conn_executor.go#L1816-L1818 in pkg/sql.(*connExecutor).run
https://github.com/cockroachdb/cockroach/blob/e438c2f89282e607e0e6ca1d38b2e0a622f94493/pkg/sql/conn_executor.go#L762-L764 in pkg/sql.(*Server).ServeConn
https://github.com/cockroachdb/cockroach/blob/e438c2f89282e607e0e6ca1d38b2e0a622f94493/pkg/sql/pgwire/conn.go#L727-L729 in pkg/sql/pgwire.(*conn).processCommandsAsync.func1
GOROOT/src/runtime/asm_amd64.s#L1580-L1582 in runtime.goexit
</details>

```
pkg/sql/colexecerror/error.go in pkg/sql/colexecerror.CatchVectorizedRuntimeError.func1 at line 89
GOROOT/src/runtime/panic.go in runtime.gopanic at line 1038
pkg/sql/colexecerror/error.go in pkg/sql/colexecerror.InternalError at line 193
pkg/sql/colexec/colbuilder/execplan.go in pkg/sql/colexec/colbuilder.NewColOperator at line 1241
pkg/sql/colflow/vectorized_flow.go in pkg/sql/colflow.(*vectorizedFlowCreator).setupFlow.func1 at line 1183
pkg/sql/colexecerror/error.go in pkg/sql/colexecerror.CatchVectorizedRuntimeError at line 92
pkg/sql/colflow/vectorized_flow.go in pkg/sql/colflow.(*vectorizedFlowCreator).setupFlow at line 1122
pkg/sql/colflow/vectorized_flow.go in pkg/sql/colflow.(*vectorizedFlow).Setup at line 275
pkg/sql/distsql/server.go in pkg/sql/distsql.(*ServerImpl).setupFlow at line 411
pkg/sql/distsql/server.go in pkg/sql/distsql.(*ServerImpl).SetupLocalSyncFlow at line 584
pkg/sql/distsql_running.go in pkg/sql.(*DistSQLPlanner).setupFlows at line 373
pkg/sql/distsql_running.go in pkg/sql.(*DistSQLPlanner).Run at line 555
pkg/sql/distsql_running.go in pkg/sql.(*DistSQLPlanner).planAndRunSubquery at line 1313
pkg/sql/distsql_running.go in pkg/sql.(*DistSQLPlanner).PlanAndRunSubqueries at line 1213
pkg/sql/conn_executor_exec.go in pkg/sql.(*connExecutor).execWithDistSQLEngine at line 1497
pkg/sql/conn_executor_exec.go in pkg/sql.(*connExecutor).dispatchToExecutionEngine at line 1163
pkg/sql/conn_executor_exec.go in pkg/sql.(*connExecutor).execStmtInOpenState at line 699
pkg/sql/conn_executor_exec.go in pkg/sql.(*connExecutor).execStmt at line 144
pkg/sql/conn_executor.go in pkg/sql.(*connExecutor).execCmd.func1 at line 1891
pkg/sql/conn_executor.go in pkg/sql.(*connExecutor).execCmd at line 1895
pkg/sql/conn_executor.go in pkg/sql.(*connExecutor).run at line 1817
pkg/sql/conn_executor.go in pkg/sql.(*Server).ServeConn at line 763
pkg/sql/pgwire/conn.go in pkg/sql/pgwire.(*conn).processCommandsAsync.func1 at line 728
GOROOT/src/runtime/asm_amd64.s in runtime.goexit at line 1581
```

| Tag | Value |
|---|---|
| Cockroach Release | `v22.1.9` |
| Cockroach SHA: | e438c2f89282e607e0e6ca1d38b2e0a622f94493 |
| Platform | linux amd64 |
| Distribution | CCL |
| Environment | v22.1.9 |
| Command | server |
| Go Version | ``|
| # of CPUs ||
| # of Goroutines ||

Jira issue: CRDB-20931

### PR DESCRIPTION
**Pull request by DrewKimball**
This patch adds a `SQLStringForError` method to `types.T` that returns
a `redact.RedactableString`. It is used by the "unhandled cast" error
message to prevent safe type information from being removed from the
error message. This will make debugging sentry issues easier.

Fixes #90760

Epic: [CRDB-20535](https://cockroachlabs.atlassian.net/browse/CRDB-20535)

Release note: None

### CODE REVIEW

**Review by yuzefovich — COMMENTED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/91892)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @DrewKimball)

___
*[`pkg/sql/colexec/colexecbase/cast_tmpl.go` line 187 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/91892#-NGxM3rK1HzSlg3u6SUR:-NGxM3rL8UJSs_f0cvse:bhdy6z6) ([raw file](https://github.com/cockroachdb/cockroach/blob/7c73bd6d95da475fa5b1b1de84858833a1bdfdb6/pkg/sql/colexec/colexecbase/cast_tmpl.go#L187)):*
> ```Go
> 	return nil, errors.Errorf(
> 		"unhandled cast %s -> %s",
> 		redact.Safe(fromType.SQLString()),
> ```

Should we, instead, make `SQLString` return `redact.SafeString` type? This will make it so that we see unredacted types in all paths, and not just in the vectorized casts. It seems like this would require changing `ResolveTypeReference` interface which some of the protobufs implement, so it might be a little annoying to do, but I think it'd be worth it. I guess if such change becomes too invasive, so we won't backport it, it might be ok to merge as is (although we should use `redact.SafeString` here too). WDYT?

**Review by michae2 — COMMENTED** [review]
Seems like types that are `t.UserDefined()` might not be safe?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/91892#-:-NGxPaGXB_D3XUrhus80:b-xgh0nj)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @DrewKimball)

**Comment by yuzefovich** [comment]
Yes, good point, those should be redacted (I guess for enums we could just say "enum", but for others we can just say "UDT" or whatnot).

**Comment by DrewKimball** [comment]
I added a `SafeSQLString` method to `types.T` that returns a `SafeString`.

**Review by yuzefovich — COMMENTED** [review]
> Reviewed 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/91892)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @DrewKimball)

___
*[`pkg/sql/colexec/colexecbase/cast_tmpl.go` line 187 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/91892#-NGxM3rK1HzSlg3u6SUR:-NHAxZHy16W1mXWpm8lI:b-wucbxh) ([raw file](https://github.com/cockroachdb/cockroach/blob/7c73bd6d95da475fa5b1b1de84858833a1bdfdb6/pkg/sql/colexec/colexecbase/cast_tmpl.go#L187)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

Should we, instead, make `SQLString` return `redact.SafeString` type? This will make it so that we see unredacted types in all paths, and not just in the vectorized casts. It seems like this would require changing `ResolveTypeReference` interface which some of the protobufs implement, so it might be a little annoying to do, but I think it'd be worth it. I guess if such change becomes too invasive, so we won't backport it, it might be ok to merge as is (although we should use `redact.SafeString` here too). WDYT?
</blockquote></details>

Hm, I was under the impression that we use `SQLString` method in more places in the vectorized engine that might trigger the sentry report, but I was wrong. I guess it doesn't hurt to introduce this safe method to `types.T`.

**Comment by knz** [comment]
Generally the go to type should be RedactableString. SafeString is really only suitable for literal constants.

**Review by knz — COMMENTED** [review]
> Reviewed 1 of 3 files at r1, 1 of 4 files at r2, 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/91892)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @DrewKimball)

___
*[`pkg/sql/types/types.go` line 1917 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/91892#-NIc9-556umx571MIyqc:-NIc9-56EDjpMD0D813-:bgzhjbm) ([raw file](https://github.com/cockroachdb/cockroach/blob/f7e4aa72792ff5c7bdc9d2a2b11dc731a84a4969/pkg/sql/types/types.go#L1917)):*
> ```Go
> func (t *T) SQLStringForError() redact.RedactableString {
> 	if t.UserDefined() {
> 		sqlStr := "UDT: " + startRedactionMarker + t.SQLString() + endRedactionMarker
> ```

```go
return redact.Sprintf("UDT: %s", t.SQLString())
```
___
*[`pkg/sql/types/types.go` line 1921 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/91892#-NIc97mBAY7KSGPu4e0H:-NIc97mBAY7KSGPu4e0I:b43kaag) ([raw file](https://github.com/cockroachdb/cockroach/blob/f7e4aa72792ff5c7bdc9d2a2b11dc731a84a4969/pkg/sql/types/types.go#L1921)):*
> ```Go
> 	}
> 	if t.Family() == EnumFamily {
> 		sqlStr := "enum: " + startRedactionMarker + t.SQLString() + endRedactionMarker
> ```

```go
return redact.Sprintf("enum: %s", t.SQLString())
```
___
*[`pkg/sql/types/types.go` line 1925 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/91892#-NIc9CzK172JsdvwJXQK:-NIc9CzL-dNrQcPs1XHl:b-28eyjz) ([raw file](https://github.com/cockroachdb/cockroach/blob/f7e4aa72792ff5c7bdc9d2a2b11dc731a84a4969/pkg/sql/types/types.go#L1925)):*
> ```Go
> 	}
> 	// Other types are safe to leave un-redacted.
> 	return redact.RedactableString(t.SQLString())
> ```

```go
return redact.Sprint(redact.Safe(t.SQLString())
```

**Review by DrewKimball — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/91892)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @knz)

___
*[`pkg/sql/types/types.go` line 1917 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/91892#-NIc9-556umx571MIyqc:-NIcWzd37Vqe89oFAFXx:b-ds1ts9) ([raw file](https://github.com/cockroachdb/cockroach/blob/f7e4aa72792ff5c7bdc9d2a2b11dc731a84a4969/pkg/sql/types/types.go#L1917)):*
<details><summary><i>Previously, knz (Raphael 'kena' Poss) wrote…</i></summary><blockquote>

```go
return redact.Sprintf("UDT: %s", t.SQLString())
```

</blockquote></details>

Thanks, thought I might be missing something convenient like that. Done.
___
*[`pkg/sql/types/types.go` line 1921 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/91892#-NIc97mBAY7KSGPu4e0H:-NIcXN583RE8vNJsa0cz:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/f7e4aa72792ff5c7bdc9d2a2b11dc731a84a4969/pkg/sql/types/types.go#L1921)):*
<details><summary><i>Previously, knz (Raphael 'kena' Poss) wrote…</i></summary><blockquote>

```go
return redact.Sprintf("enum: %s", t.SQLString())
```
</blockquote></details>

Done.
___
*[`pkg/sql/types/types.go` line 1925 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/91892#-NIc9CzK172JsdvwJXQK:-NIcXO5C0LvkCWZuJPCX:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/f7e4aa72792ff5c7bdc9d2a2b11dc731a84a4969/pkg/sql/types/types.go#L1925)):*
<details><summary><i>Previously, knz (Raphael 'kena' Poss) wrote…</i></summary><blockquote>

```go
return redact.Sprint(redact.Safe(t.SQLString())
```
</blockquote></details>

Done.

**Comment by DrewKimball** [comment]
@knz friendly bump, does this look ok?

File: pkg/sql/types/types.go [hunk 1]
```diff
@@ -1923,6 +1924,19 @@ func (t *T) SQLString() string {
...
+// information during redaction. It is suitable for usage in error messages.
+func (t *T) SQLStringForError() redact.RedactableString {
+	if t.UserDefined() {
+		return redact.Sprintf("UDT: %s", t.SQLString())
+	}
+	if t.Family() == EnumFamily {
+		return redact.Sprintf("enum: %s", t.SQLString())
+	}
+	// Other types are safe to leave un-redacted.
+	return redact.Sprint(redact.SafeString(t.SQLString()))
```
Comment (knz) [inline pkg/sql/types/types.go:1937]: Right now as written you are promising that any current _and future_ type implementations will produce safe representations. How do you plan to make good for that promise, for everyone ever adding a new type family in the future?

If i were you i would invert.this logic, and enumerate explicitly the types that are safe, and then fall back to the other case for everything else.

Comment (DrewKimball) [reply pkg/sql/types/types.go:1937]: Done. I also added a test to ensure expected output.

**Review by knz — APPROVED** [review]
> Reviewed 2 of 3 files at r4, 3 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/91892)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @DrewKimball)

**Comment by DrewKimball** [comment]
TFYRs!
