### PR TITLE
intentresolver: serialize race in intent resolution test

### LINKED ISSUE #122360: kv/kvserver/intentresolver: TestIntentResolutionUnavailableRange failed
kv/kvserver/intentresolver.TestIntentResolutionUnavailableRange [failed](https://tanzanite.cluster.engflow.com/invocations/default/03743512-f206-4e98-bdb8-59ecfd62b924?testReportRun=1&testReportShard=1&testReportAttempt=1#targets-Ly9wa2cva3Yva3ZzZXJ2ZXIvaW50ZW50cmVzb2x2ZXI6aW50ZW50cmVzb2x2ZXJfdGVzdA==) on release-24.1 @ [6e3e9e6012dc04dabc64333a87e77a80d9f9d46b](https://github.com/cockroachdb/cockroach/commits/6e3e9e6012dc04dabc64333a87e77a80d9f9d46b):

```
Goroutine 33847 (running) created at:
  github.com/cockroachdb/cockroach/pkg/sql.(*InternalExecutor).runWithEx()
      github.com/cockroachdb/cockroach/pkg/sql/internal.go:227 +0x305
  github.com/cockroachdb/cockroach/pkg/sql.(*InternalExecutor).execInternal()
      github.com/cockroachdb/cockroach/pkg/sql/internal.go:1143 +0x12d1
  github.com/cockroachdb/cockroach/pkg/sql.(*InternalExecutor).QueryIteratorEx()
      github.com/cockroachdb/cockroach/pkg/sql/internal.go:817 +0x274
  github.com/cockroachdb/cockroach/pkg/sql.(*InternalExecutor).QueryIterator()
      github.com/cockroachdb/cockroach/pkg/sql/internal.go:803 +0x13e
  github.com/cockroachdb/cockroach/pkg/sql.(*internalTxn).QueryIterator()
      <autogenerated>:1 +0xd8
  github.com/cockroachdb/cockroach/pkg/jobs.RunningJobExists()
      github.com/cockroachdb/cockroach/pkg/jobs/utils.go:66 +0x761
  github.com/cockroachdb/cockroach/pkg/sql.checkRunningJobsInTxn()
      github.com/cockroachdb/cockroach/pkg/sql/create_stats.go:758 +0xa9
  github.com/cockroachdb/cockroach/pkg/sql.checkRunningJobs.func1()
      github.com/cockroachdb/cockroach/pkg/sql/create_stats.go:748 +0x52
  github.com/cockroachdb/cockroach/pkg/sql.(*InternalDB).Txn.func1()
      github.com/cockroachdb/cockroach/pkg/sql/internal.go:1763 +0x52
  github.com/cockroachdb/cockroach/pkg/sql.(*InternalDB).txn.func4()
      github.com/cockroachdb/cockroach/pkg/sql/internal.go:1850 +0x4d3
  github.com/cockroachdb/cockroach/pkg/kv.(*Txn).exec()
      github.com/cockroachdb/cockroach/pkg/kv/txn.go:1049 +0xad
  github.com/cockroachdb/cockroach/pkg/kv.runTxn()
      github.com/cockroachdb/cockroach/pkg/kv/db.go:1089 +0x6b
  github.com/cockroachdb/cockroach/pkg/kv.(*DB).TxnWithAdmissionControl()
      github.com/cockroachdb/cockroach/pkg/kv/db.go:1052 +0xec
  github.com/cockroachdb/cockroach/pkg/kv.(*DB).Txn()
      github.com/cockroachdb/cockroach/pkg/kv/db.go:1027 +0x5c
  github.com/cockroachdb/cockroach/pkg/kv.(*DB).Txn-fm()
      <autogenerated>:1 +0x1b
  github.com/cockroachdb/cockroach/pkg/sql.(*InternalDB).txn()
      github.com/cockroachdb/cockroach/pkg/sql/internal.go:1837 +0x6f5
  github.com/cockroachdb/cockroach/pkg/sql.(*InternalDB).Txn()
      github.com/cockroachdb/cockroach/pkg/sql/internal.go:1764 +0xd7
  github.com/cockroachdb/cockroach/pkg/sql.checkRunningJobs()
      github.com/cockroachdb/cockroach/pkg/sql/create_stats.go:747 +0x104
  github.com/cockroachdb/cockroach/pkg/sql.(*createStatsResumer).Resume()
      github.com/cockroachdb/cockroach/pkg/sql/create_stats.go:646 +0x408
  github.com/cockroachdb/cockroach/pkg/jobs.(*Registry).stepThroughStateMachine.func2()
      github.com/cockroachdb/cockroach/pkg/jobs/registry.go:1598 +0x1b0
  github.com/cockroachdb/cockroach/pkg/jobs.(*Registry).stepThroughStateMachine()
      github.com/cockroachdb/cockroach/pkg/jobs/registry.go:1599 +0xf47
  github.com/cockroachdb/cockroach/pkg/jobs.(*Registry).runJob()
      github.com/cockroachdb/cockroach/pkg/jobs/adopt.go:456 +0x811
  github.com/cockroachdb/cockroach/pkg/jobs.(*StartableJob).Start.func2()
      github.com/cockroachdb/cockroach/pkg/jobs/jobs.go:812 +0x27b
  github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunAsyncTaskEx.func2()
      github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:485 +0x262
==================
```

Parameters:
 - <code>attempt=1</code>
 - <code>race=true</code>
 - <code>run=1</code>
 - <code>shard=1</code>
<details><summary>Help</summary>
<p>

See also: [How To Investigate a Go Test Failure \(internal\)](https://cockroachlabs.atlassian.net/l/c/HgfXfJgM)
</p>
</details>
/cc @cockroachdb/kv
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*TestIntentResolutionUnavailableRange.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/bazci/githubpost/issues)
</sub>

Jira issue: CRDB-37832

### PR DESCRIPTION
**Pull request by kvoli**
`TestIntentResolutionUnavailableRange` had a race condition on a test only variable. Serialize access to the var to remove the race.

Fixes: #122360
Release note: None

### CODE REVIEW

File: pkg/kv/kvserver/intentresolver/intent_resolver_integration_test.go [hunk 1]
```diff
@@ -404,6 +406,8 @@ func TestIntentResolutionUnavailableRange(t *testing.T) {
 			TestingRequestFilter: func(ctx context.Context, ba *kvpb.BatchRequest) *kvpb.Error {
 				// Configure so that intent resolution on t2 cannot finish
 				// successfully and blocks, relying on the timeout to unblock.
+				t2RangeIDMu.Lock()
```
Comment (nvanbenschoten) [inline pkg/kv/kvserver/intentresolver/intent_resolver_integration_test.go:409]: Do we want to hold this mutex until the request is cancelled? Could this lead to a test deadlock? Should we instead make access to `t2RangeID` atomic?

Comment (kvoli) [reply pkg/kv/kvserver/intentresolver/intent_resolver_integration_test.go]: This passed a few minutes of race runs so I assumed it was safe from deadlocking. It certainly makes more sense to use an atomic here, updated.

**Review by arulajmani — APPROVED** [review]
:lgtm: modulo nit

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/122373#-:-NvYeBq93sRmND0CaHH4:bw0ujha)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @kvoli and @nvanbenschoten)

___
*[`pkg/kv/kvserver/intentresolver/intent_resolver_integration_test.go` line 396 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/122373#-NvYdvzhD-23hiAhTnYi:-NvYdvzhD-23hiAhTnYj:bakalzh) ([raw file](https://github.com/cockroachdb/cockroach/blob/060990149f4ab93997c018247ab557743958f982/pkg/kv/kvserver/intentresolver/intent_resolver_integration_test.go#L396)):*
> ```Go
> 	serverArgs := make(map[int]base.TestServerArgs)
> 	waitForIntentResolutionForT2 := make(chan struct{})
> 	var t2RangeID int32
> ```

nit:  let's use an `atomic.Int32` instead?

**Review by nvb — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/122373#-:-NvYeUQl-mVM6GoeBJ-K:bnfp4nl)* status: <span>:shipit:</span> complete! 2 of 0 LGTMs obtained (waiting on @arulajmani)

___
*[`pkg/kv/kvserver/intentresolver/intent_resolver_integration_test.go` line 396 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/122373#-NvYdvzhD-23hiAhTnYi:-NvYeSC44mtW_sexEGJ7:b32v57) ([raw file](https://github.com/cockroachdb/cockroach/blob/060990149f4ab93997c018247ab557743958f982/pkg/kv/kvserver/intentresolver/intent_resolver_integration_test.go#L396)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

nit:  let's use an `atomic.Int32` instead?
</blockquote></details>

+1

**Comment by kvoli** [comment]
TYFTR

bors r=nvanbenschoten,arulajmani
