### PR TITLE
sql/schemachanger: add decoder for schemaChangerUserError

### LINKED ISSUE #141352: schemachanger: CREATE INDEX is stuck on a retriable parse error
roachtest.sqlsmith/setup=tpcc/setting=ddl-nodrop [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/18811231?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/18811231?buildTab=artifacts#/sqlsmith/setup=tpcc/setting=ddl-nodrop) on master @ [007029617564b747e4f199c990860ad73f299c3a](https://github.com/cockroachdb/cockroach/commits/007029617564b747e4f199c990860ad73f299c3a). A Side-Eye cluster snapshot was captured on timeout: [https://app.side-eye.io/#/snapshots/626](https://app.side-eye.io/#/snapshots/626).

```
(test_runner.go:1367).runTest: test timed out (20m0s)
test artifacts and logs in: /artifacts/sqlsmith/setup=tpcc/setting=ddl-nodrop/run_1
```

Parameters:
 - <code>arch=amd64</code>
 - <code>cloud=gce</code>
 - <code>coverageBuild=false</code>
 - <code>cpu=4</code>
 - <code>encrypted=false</code>
 - <code>metamorphicLeases=default</code>
 - <code>runtimeAssertionsBuild=false</code>
 - <code>ssd=0</code>
<details><summary>Help</summary>
<p>

See: [roachtest README](https://github.com/cockroachdb/cockroach/blob/master/pkg/cmd/roachtest/README.md)

See: [How To Investigate \(internal\)](https://cockroachlabs.atlassian.net/l/c/SSSBr8c7)

See: [Grafana](https://go.crdb.dev/roachtest-grafana/teamcity-18811231/sqlsmith-setup-tpcc-setting-ddl-nodrop/1739347453413/1739348821314)

</p>
</details>
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*sqlsmith/setup=tpcc/setting=ddl-nodrop.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/bazci/githubpost/issues)

</sub>

Jira issue: CRDB-47792

### PR DESCRIPTION
**Pull request by fqazi**
Previously, if a schemaChangerUserError was sent over the network during a backfill it would not be properly recognized on the receiving node. This is because without having a decoder it would be an unresolved opaqueWrapper. The HasSchemaChangerUserError function confirms the error by checking the type, which would not be correctly handled in this case. To address this, this patch adds decoder for this error type, which allows it to be decoded correctly on remote nodes.

Fixes: #141352

Release note: None

### CODE REVIEW

File: pkg/sql/schemachanger/scerrors/errors.go [hunk 1]
```diff
@@ -206,12 +207,26 @@ func (e *schemaChangerUserError) SafeFormatError(p errors.Printer) (next error)
...
+// schemaChangerUserErrorDecodeWrapper is a wrapper decoder for
+// schemaChangerUserError.
+func schemaChangerUserErrorDecodeWrapper(
+	_ context.Context, cause error, _ string, _ []string, payload proto.Message,
+) error {
+	return &schemaChangerUserError{err: cause}
+}
+
+func init() {
+	errors.RegisterWrapperDecoder(errors.GetTypeKey((*schemaChangerUserError)(nil)), schemaChangerUserErrorDecodeWrapper)
```
Comment (rafiss) [inline pkg/sql/schemachanger/scerrors/errors.go:231]: based on other examples i see, it looks like we need a `RegisterWrapperEncoder` also.

can we write a test that would catch this bug, so we can make sure the fix works?

**Review by rafiss — CHANGES_REQUESTED** [review]

File: pkg/sql/schemachanger/scerrors/errors.go (hunk 1 above)
Comment (fqazi) [reply pkg/sql/schemachanger/scerrors/errors.go:231]: I'll add a test but an encoder isn't needed because this is a wrapper error because it implements the Unwrap interface.

**Review by fqazi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/151939)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @rafiss)

___
*[`pkg/sql/schemachanger/scerrors/errors_test.go` line 13 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/151939#-OY30qDf2LCuzJhTVP0A:-OY30qDf2LCuzJhTVP0B:b-uxjctd) ([raw file](https://github.com/cockroachdb/cockroach/blob/bb9582656bc0de6243e3babaac0391750482235f/pkg/sql/schemachanger/scerrors/errors_test.go#L13)):*
> ```Go
> )
> 
> // TestEncodeSchemaChangeUserError tests that the error is encoded and decoded
> ```

This test fails if we don't have a decoder registered confirming this works correctly.

**Review by rafiss — APPROVED** [review]

**Comment by fqazi** [comment]
@rafiss TFTR!

bors r+
