### PR TITLE
sql: Fix bug where dropping table didn't drop corresponding zone config.

### LINKED ISSUE #38392: sql: dropping tables doesn't drop corresponding zone config
Repro:

```
root@127.0.0.1:61922/defaultdb> create table a (a int primary key);
CREATE TABLE

Time: 3.774ms

root@127.0.0.1:61922/defaultdb> alter table a configure zone using num_replicas=7;
CONFIGURE ZONE 1

Time: 4.917ms

root@127.0.0.1:61922/defaultdb> select * from crdb_internal.zones where zone_name like '%a';
  zone_id |  zone_name  | cli_specifier |        config_yaml        |                     config_sql                      |                            config_protobuf
+---------+-------------+---------------+---------------------------+-----------------------------------------------------+-----------------------------------------------------------------------+
       16 | .meta       | .meta         | range_min_bytes: 16777216 | ALTER RANGE meta CONFIGURE ZONE USING               | \020\200\200\200\010\030\200\200\200 "\003\010\220\034(\001P\000X\000
          |             |               | range_max_bytes: 67108864 |     range_min_bytes = 16777216,                     |
          |             |               | gc:                       |     range_max_bytes = 67108864,                     |
          |             |               |   ttlseconds: 3600        |     gc.ttlseconds = 3600,                           |
          |             |               | num_replicas: 1           |     num_replicas = 1,                               |
          |             |               | constraints: []           |     constraints = '[]',                             |
          |             |               | lease_preferences: []     |     lease_preferences = '[]'                        |
          |             |               |                           |                                                     |
       53 | defaultdb.a | defaultdb.a   | range_min_bytes: null     | ALTER TABLE defaultdb.public.a CONFIGURE ZONE USING | (\007P\001X\001
          |             |               | range_max_bytes: null     |     num_replicas = 7                                |
          |             |               | gc: null                  |                                                     |
          |             |               | num_replicas: 7           |                                                     |
          |             |               | constraints: []           |                                                     |
          |             |               | lease_preferences: []     |                                                     |
          |             |               |                           |                                                     |
(2 rows)

Time: 2.994ms

root@127.0.0.1:61922/defaultdb> drop table a;
DROP TABLE

Time: 78.44ms

root@127.0.0.1:61922/defaultdb> select * from crdb_internal.zones where zone_id=53;
  zone_id | zone_name | cli_specifier |      config_yaml      | config_sql | config_protobuf
+---------+-----------+---------------+-----------------------+------------+-----------------+
       53 | NULL      | NULL          | range_min_bytes: null | NULL       | (\007P\001X\001
          |           |               | range_max_bytes: null |            |
          |           |               | gc: null              |            |
          |           |               | num_replicas: 7       |            |
          |           |               | constraints: []       |            |
          |           |               | lease_preferences: [] |            |
          |           |               |                       |            |
(1 row)

Time: 3.046ms

```

### PR DESCRIPTION
**Pull request by rohany**
This PR also addresses a bug where when an index was dropped
the subzone corresponding to that index was left as a
hanging subzone within the system.zones table.

Fixes #38392.

### CODE REVIEW

File: pkg/sql/crdb_internal.go [hunk 1]
```diff
@@ -1901,10 +1901,11 @@ CREATE TABLE crdb_internal.zones (
...
 			if err != nil {
-				// The database or table has been deleted so there is no way
-				// to refer to it anymore. We are still going to show
-				// something but the CLI specifier part will become NULL.
-				zoneSpecifier = nil
+				// If the database or table that we are looking at has been
+				// deleted, do not emit a column for this zone specifier
+				// in the output table. TODO (rohany): should we delete
+				// this zone from the system table as well here?
+				continue
```
Comment (jordanlewis) [inline pkg/sql/crdb_internal.go]: Definitely doesn't seem like the right spot to be deleting the zone. This feels kind of like a bandaid. I don't remember full context here, but maybe a better place to delete the zone would be when we're finalizing the table / index / database drop...

**Comment by rohany** [comment]
RFAL, post discussions.

**Comment by jordanlewis** [comment]
Ugh, just realized - do you think there's any way somebody could be depending on this behavior internally?

**Comment by rohany** [comment]
I have no clue -- I'm not sure who would be using this particular behavior though.

**Review by jordanlewis — APPROVED** [review]

**Comment by jordanlewis** [comment]
A grep doesn't reveal anything that seems to depend on this behavior, so I think we're good to go. Thanks for fixing this!
