### PR TITLE
kvserver: always return NLHE on lease acquisition timeouts

### LINKED ISSUE #84258: roachtest: kv50/enc=false/nodes=1/conc=8192 failed
roachtest.kv50/enc=false/nodes=1/conc=8192 [failed](https://teamcity.cockroachdb.com/viewLog.html?buildId=5718831&tab=buildLog) with [artifacts](https://teamcity.cockroachdb.com/viewLog.html?buildId=5718831&tab=artifacts#/kv50/enc=false/nodes=1/conc=8192) on release-21.2 @ [97c5b1cbd23c109798597e9873544b91da651802](https://github.com/cockroachdb/cockroach/commits/97c5b1cbd23c109798597e9873544b91da651802):

```
		  |    18.0s        0            0.0         2349.8      0.0      0.0      0.0      0.0 write
		  |    19.0s        0           17.9         2518.6  10200.5  10737.4  11274.3  11274.3 read
		  |    19.0s        0          480.2         2251.5  10737.4  11274.3  11811.2  11811.2 write
		  |    20.0s        0         2376.6         2514.5    218.1  10737.4  11274.3  11811.2 read
		  |    20.0s        0         4464.5         2367.8  10737.4  11811.2  11811.2  12348.0 write
		  | _elapsed___errors__ops/sec(inst)___ops/sec(cum)__p50(ms)__p95(ms)__p99(ms)_pMax(ms)
		  |    21.0s        0         6597.8         2708.1    176.2    402.7  10737.4  12884.9 read
		  |    21.0s        0         7044.0         2589.6    704.6  11811.2  11811.2  12348.0 write
		  |    22.0s        0         4185.0         2773.1    184.5    520.1    771.8  12884.9 read
		  |    22.0s        0         4792.8         2687.3    637.5    939.5   1140.9  11274.3 write
		  |    23.0s        0         6766.5         2947.4    109.1   1073.7   1677.7  15032.4 read
		  |    23.0s        0         5626.9         2815.6    771.8   1409.3   2080.4  12884.9 write
		  |    24.0s        0         4888.9         3028.4    125.8    486.5   1610.6  15569.3 read
		  |    24.0s        0         5506.3         2927.9    671.1   1811.9   2281.7  14495.5 write
		  |    25.0s        0         4151.5         3073.8    109.1    637.5   1342.2  16643.0 read
		  |    25.0s        0         5362.8         3026.0   1073.7   1476.4   2281.7  15569.3 write
		Wraps: (4) exit status 20
		Error types: (1) *withstack.withStack (2) *errutil.withPrefix (3) *cluster.WithCommandDetails (4) *exec.ExitError

	monitor.go:128,kv.go:137,kv.go:251,test_runner.go:777: monitor failure: monitor task failed: t.Fatal() was called
		(1) attached stack trace
		  -- stack trace:
		  | main.(*monitorImpl).WaitE
		  | 	/home/agent/work/.go/src/github.com/cockroachdb/cockroach/pkg/cmd/roachtest/monitor.go:116
		  | main.(*monitorImpl).Wait
		  | 	/home/agent/work/.go/src/github.com/cockroachdb/cockroach/pkg/cmd/roachtest/monitor.go:124
		  | github.com/cockroachdb/cockroach/pkg/cmd/roachtest/tests.registerKV.func2
		  | 	/home/agent/work/.go/src/github.com/cockroachdb/cockroach/pkg/cmd/roachtest/tests/kv.go:137
		  | github.com/cockroachdb/cockroach/pkg/cmd/roachtest/tests.registerKV.func3
		  | 	/home/agent/work/.go/src/github.com/cockroachdb/cockroach/pkg/cmd/roachtest/tests/kv.go:251
		  | main.(*testRunner).runTest.func2
		  | 	/home/agent/work/.go/src/github.com/cockroachdb/cockroach/pkg/cmd/roachtest/test_runner.go:777
		Wraps: (2) monitor failure
		Wraps: (3) attached stack trace
		  -- stack trace:
		  | main.(*monitorImpl).wait.func2
		  | 	/home/agent/work/.go/src/github.com/cockroachdb/cockroach/pkg/cmd/roachtest/monitor.go:172
		Wraps: (4) monitor task failed
		Wraps: (5) attached stack trace
		  -- stack trace:
		  | main.init
		  | 	/home/agent/work/.go/src/github.com/cockroachdb/cockroach/pkg/cmd/roachtest/monitor.go:81
		  | runtime.doInit
		  | 	/usr/local/go/src/runtime/proc.go:6498
		  | runtime.main
		  | 	/usr/local/go/src/runtime/proc.go:238
		  | runtime.goexit
		  | 	/usr/local/go/src/runtime/asm_amd64.s:1581
		Wraps: (6) t.Fatal() was called
		Error types: (1) *withstack.withStack (2) *errutil.withPrefix (3) *withstack.withStack (4) *errutil.withPrefix (5) *withstack.withStack (6) *errutil.leafError
```
<details><summary>Reproduce</summary>
<p>

See: [roachtest README](https://github.com/cockroachdb/cockroach/blob/master/pkg/cmd/roachtest/README.md)

</p>
</details>
/cc @cockroachdb/kv-triage
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*kv50/enc=false/nodes=1/conc=8192.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)
</sub>

### LINKED ISSUE #85115: kvserver: lease acquisition timeouts mask `NotLeaseHolderError`
As seen in #84258, lease acquisition timeouts are returned as a `TimeoutError` wrapping the `NotLeaseHolderError`, which prevents the DistSender from handling these, instead returning them to the client.

Jira issue: CRDB-18049

### PR DESCRIPTION
**Pull request by erikgrinaker**
In ab74b974bd42bea1d50bf7c1ec8804180224f825 we added internal timeouts for lease acquisitions. These
were wrapped in `RunWithTimeout()`, as mandated for context timeouts.
However, this would mask the returned `NotLeaseHolderError` as a
`TimeoutError`, preventing the DistSender from retrying it and instead
propagating it out to the client. Additionally, context cancellation
errors from the actual RPC call were never wrapped as a
`NotLeaseHolderError` in the first place.

This ended up only happening in a very specific scenario where the outer
timeout added to the client context did not trigger, but the inner
timeout for the coalesced request context did trigger while the lease
request was in flight. Accidentally, the outer `RunWithTimeout()` call
did not return the `roachpb.Error` from the closure but instead passed
it via a captured variable, bypassing the error wrapping.

This patch replaces the `RunWithTimeout()` calls with regular
`context.WithTimeout()` calls to avoid the error wrapping, and returns a
`NotLeaseHolderError` from `requestLease()` if the RPC request fails and
the context was cancelled (presumably causing the error). Another option
would be to extract an NLHE from the error chain, but this would require
correct propagation of the structured error chain across RPC boundaries,
so out of an abundance of caution and with an eye towards backports, we
instead choose to return a bare `NotLeaseHolderError`.

The empty lease in the returned error prevents the DistSender from
updating its caches on context cancellation.

Resolves #84258.
Resolves #85115.

Release note (bug fix): Fixed a bug where clients could sometimes
receive errors due to lease acquisition timeouts of the form
`operation "storage.pendingLeaseRequest: requesting lease" timed out after 6s`.

### CODE REVIEW

**Review by nvb — COMMENTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/84865)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @erikgrinaker)

___
*[`pkg/kv/kvserver/replica_range_lease.go` line 1241 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/84865#-N7vcZZ-1SG8VNy_ro-3:-N7vcZZ-1SG8VNy_ro-4:bjjsa2v) ([raw file](https://github.com/cockroachdb/cockroach/blob/05c720c9a4ca93346aec4a13447ae4710e1da632/pkg/kv/kvserver/replica_range_lease.go#L1241)):*
> ```Go
> 	timeout := 2 * r.store.cfg.RaftElectionTimeout()
> 
> 	// Does not use RunWithTimeout(), because we do not want to mask the
> ```

Why do we have two different, nested timeouts? The first is here (`redirectOnOrAcquireLeaseForRequest`) and the second is in (`requestLeaseAsync`), which is called by this function. Isn't the timeout here sufficient to accomplish what you wanted in https://github.com/cockroachdb/cockroach/commit/ab74b974bd42bea1d50bf7c1ec8804180224f825? The context deadline handling in `redirectOnOrAcquireLeaseForRequestWithoutTimeout` already correctly promotes a ctx err to a NLHE.

I'm sure there's a good reason, I just can't find it in #81136.

**Review by erikgrinaker — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/84865)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @nvanbenschoten)

___
*[`pkg/kv/kvserver/replica_range_lease.go` line 1241 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/84865#-N7vcZZ-1SG8VNy_ro-3:-N7yx6YI6XUz4W4TVXO6:b-v5ncc8) ([raw file](https://github.com/cockroachdb/cockroach/blob/05c720c9a4ca93346aec4a13447ae4710e1da632/pkg/kv/kvserver/replica_range_lease.go#L1241)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Why do we have two different, nested timeouts? The first is here (`redirectOnOrAcquireLeaseForRequest`) and the second is in (`requestLeaseAsync`), which is called by this function. Isn't the timeout here sufficient to accomplish what you wanted in https://github.com/cockroachdb/cockroach/commit/ab74b974bd42bea1d50bf7c1ec8804180224f825? The context deadline handling in `redirectOnOrAcquireLeaseForRequestWithoutTimeout` already correctly promotes a ctx err to a NLHE.

I'm sure there's a good reason, I just can't find it in #81136.
</blockquote></details>

`requestLeaseAsync` (with the inner timeout) uses a base context that's tied to the number of waiting callers, cancelling when it drops to 0. Even if every caller sets its own timeout, if there is a steady influx of callers then the inner context may never get cancelled and the lease attempt would never return.

You might ask why the inner timeout isn't sufficient then, since all callers will receive an error when it triggers. This was done out of abundance of caution, in case any of the other operations in `redirectOnOrAcquireLeaseForRequest` might stall (haven't found any likely culprits), or if the coalesced context handling in `requestLeaseAsync` might fail to return an error for whatever reason. We should be able to remove it if you have a strong opinion on it, but I figured better safe than sorry given the consequences of a stall here.

File: pkg/kv/kvserver/replica_range_lease.go [hunk 1]
```diff
@@ -374,9 +372,12 @@ func (p *pendingLeaseRequest) requestLeaseAsync(
...
 			// lease.
-			err := contextutil.RunWithTimeout(ctx, taskName, timeout, func(ctx context.Context) error {
-				return p.requestLease(ctx, nextLeaseHolder, reqLease, status, leaseReq)
-			})
+			//
+			// Does not use RunWithTimeout(), because we do not want to mask the
+			// NotLeaseHolderError on context cancellation.
+			requestLeaseCtx, requestLeaseCancel := context.WithTimeout(ctx, timeout) // nolint:context
+			defer requestLeaseCancel()
+			err := p.requestLease(requestLeaseCtx, nextLeaseHolder, reqLease, status, leaseReq)
```
Comment (pavelkalinnikov) [inline pkg/kv/kvserver/replica_range_lease.go:380]: Did the outer code rely on this `err` being a `TimeoutError` in case of a timeout? Cause now it won't be anymore. Do you need to wrap it somewhere down this line, similarly to how `RunWithTimeout` [did](https://github.com/cockroachdb/cockroach/blob/9e44f568647bc06f2e0e33102e09df467f4b8f9a/pkg/util/contextutil/context.go#L93)?

Comment (erikgrinaker) [reply pkg/kv/kvserver/replica_range_lease.go:380]: No, rather the opposite -- the upper-level code relied on it being a `NotLeaseHolderError`, which got masked by the `TimeoutError`.

**Review by nvb — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/84865)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @erikgrinaker, @nvanbenschoten, and @pavelkalinnikov)

___
*[`pkg/kv/kvserver/replica_range_lease.go` line 1241 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/84865#-N7vcZZ-1SG8VNy_ro-3:-N80BhY5-Tx9ws5FMANQ:b1fjz98) ([raw file](https://github.com/cockroachdb/cockroach/blob/05c720c9a4ca93346aec4a13447ae4710e1da632/pkg/kv/kvserver/replica_range_lease.go#L1241)):*
> if there is a steady influx of callers then the inner context may never get cancelled and the lease attempt would never return

Is this a problem? Is there a reason why we believe a canceled and frequently retried lease acquisition attempt has a better chance of succeeding on a given replica than a lease request that is allowed to run for longer than any single caller is willing to wait?

**Review by erikgrinaker — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/84865)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @nvanbenschoten and @pavelkalinnikov)

___
*[`pkg/kv/kvserver/replica_range_lease.go` line 1241 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/84865#-N7vcZZ-1SG8VNy_ro-3:-N80DB3IB44Cd0onuS3P:b-173zzh) ([raw file](https://github.com/cockroachdb/cockroach/blob/05c720c9a4ca93346aec4a13447ae4710e1da632/pkg/kv/kvserver/replica_range_lease.go#L1241)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

> if there is a steady influx of callers then the inner context may never get cancelled and the lease attempt would never return

Is this a problem? Is there a reason why we believe a canceled and frequently retried lease acquisition attempt has a better chance of succeeding on a given replica than a lease request that is allowed to run for longer than any single caller is willing to wait?
</blockquote></details>

Really depends on the specific failure mode, I think. Seems worthwhile to at least give it a shot. Is there a reason to believe it would never help? Is there a downside to it? We would only be able to launch a new request if the previous cancellation took effect anyway, so we shouldn't be risking any pileups.

File: pkg/kv/kvserver/replica_range_lease.go (hunk 1 above)
Comment (erikgrinaker) [reply pkg/kv/kvserver/replica_range_lease.go:380]: We want a lease acquisition timeout to result in a NLHE, so that the DistSender will go try some other replica that may be able to acquire the lease instead. We therefore explicitly construct a NLHE on context cancellation. In the case where the client context was cancelled (e.g. by a disconnect), the DistSender will bail out anyway, around here:

https://github.com/cockroachdb/cockroach/blob/f77e393230fbedb57e5caa0ebbf26356b3899c73/pkg/kv/kvclient/kvcoord/dist_sender.go#L2248-L2262

For reference, the DistSender is a fat KV RPC client that's responsible for e.g. routing KV requests to the correct ranges and leaseholders.

**Review by nvb — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/84865)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @erikgrinaker, @nvanbenschoten, and @pavelkalinnikov)

___
*[`pkg/kv/kvserver/replica_range_lease.go` line 1241 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/84865#-N7vcZZ-1SG8VNy_ro-3:-N8Od0EeC9gmcR3xO36e:bkobaau) ([raw file](https://github.com/cockroachdb/cockroach/blob/05c720c9a4ca93346aec4a13447ae4710e1da632/pkg/kv/kvserver/replica_range_lease.go#L1241)):*
<details><summary><i>Previously, erikgrinaker (Erik Grinaker) wrote…</i></summary><blockquote>

Really depends on the specific failure mode, I think. Seems worthwhile to at least give it a shot. Is there a reason to believe it would never help? Is there a downside to it? We would only be able to launch a new request if the previous cancellation took effect anyway, so we shouldn't be risking any pileups.
</blockquote></details>

I'm just questioning added complexity (two layers of timeouts and custom timeout handling at each level that we need to keep in sync) which doesn't appear to be necessary. It's the kind of thing that we should be clear about the benefit of (or lack thereof) when adding or we'll never be able to remove it in the future.

**Review by erikgrinaker — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/84865)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @nvanbenschoten and @pavelkalinnikov)

___
*[`pkg/kv/kvserver/replica_range_lease.go` line 1241 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/84865#-N7vcZZ-1SG8VNy_ro-3:-N8OeOGd6WGqURC-enre:bsrunac) ([raw file](https://github.com/cockroachdb/cockroach/blob/05c720c9a4ca93346aec4a13447ae4710e1da632/pkg/kv/kvserver/replica_range_lease.go#L1241)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

I'm just questioning added complexity (two layers of timeouts and custom timeout handling at each level that we need to keep in sync) which doesn't appear to be necessary. It's the kind of thing that we should be clear about the benefit of (or lack thereof) when adding or we'll never be able to remove it in the future.
</blockquote></details>

I hear you.

The outer timeout sufficiently addresses the primary problem we're trying to solve, in that it will ensure callers eventually receive an NLHE and go try another replica regardless of what happens to the lease request itself.

The inner timeout attempts to address a separate, secondary concern that a lease request could get stuck, which could prevent that replica from ever acquiring the lease. You could argue that we have sufficient downstream error handling and retry mechanisms to prevent this, but I still think it would be prudent. It isn't really that different from having separate client-side and server-side timeouts, and shouldn't require keeping anything in sync (if either fires, it independently returns a NLHE).

That said, this is a secondary problem, so I'm fine with dropping it for now and revisiting if we see it happening in the wild. Will update the PR shortly.

**Review by erikgrinaker — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/84865)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @nvanbenschoten and @pavelkalinnikov)

___
*[`pkg/kv/kvserver/replica_range_lease.go` line 1241 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/84865#-N7vcZZ-1SG8VNy_ro-3:-N8OylX22fvG5Rr1MiQE:b-rr168b) ([raw file](https://github.com/cockroachdb/cockroach/blob/05c720c9a4ca93346aec4a13447ae4710e1da632/pkg/kv/kvserver/replica_range_lease.go#L1241)):*
<details><summary><i>Previously, erikgrinaker (Erik Grinaker) wrote…</i></summary><blockquote>

I hear you.

The outer timeout sufficiently addresses the primary problem we're trying to solve, in that it will ensure callers eventually receive an NLHE and go try another replica regardless of what happens to the lease request itself.

The inner timeout attempts to address a separate, secondary concern that a lease request could get stuck, which could prevent that replica from ever acquiring the lease. You could argue that we have sufficient downstream error handling and retry mechanisms to prevent this, but I still think it would be prudent. It isn't really that different from having separate client-side and server-side timeouts, and shouldn't require keeping anything in sync (if either fires, it independently returns a NLHE).

That said, this is a secondary problem, so I'm fine with dropping it for now and revisiting if we see it happening in the wild. Will update the PR shortly.
</blockquote></details>

Updated, PTAL.

**Review by nvb — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/84865#-:-N8P0xU_4x5kUO3TQsZw:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @pavelkalinnikov)

**Comment by erikgrinaker** [comment]
TFTR!

bors r=nvanbenschoten
