### PR TITLE
*: enable DRPC for tests in ttljob package

### LINKED ISSUE #158387: drpc, sql: enable TestRowLevelTTLJobMultipleNodes in DRPC mode
**Describe the problem**

`TestRowLevelTTLJobMultipleNodes` fails with DRPC on. First observed [here](https://github.com/cockroachdb/cockroach/issues/158317).

**To Reproduce**

Inconsistently repoducible (~every 2 in 3 fails):
`dev test pkg/sql/ttl/ttljob --filter TestRowLevelTTLJobMultipleNodes -v -- --test_env=COCKROACH_TEST_DRPC=true`

**Expected behavior**
Test should pass with DRPC enabled.

**Additional data / screenshots**
```
=== RUN   TestRowLevelTTLJobMultipleNodes/1_split
    test_server_shim.go:91: cluster virtualization disabled due to issue: #109391 (expected label: C-bug)
    test_server_shim.go:610: DRPC is enabled (override by TestingGlobalDRPCOption)
    ttljob_test.go:219: 
        	Error Trace:	pkg/sql/ttl/ttljob/ttljob_test.go:219
        	            				pkg/sql/ttl/ttljob/ttljob_test.go:740
        	Error:      	Should be true
        	Test:       	TestRowLevelTTLJobMultipleNodes/1_split
        	Messages:   	
        	            	expectedStatus="succeeded"
        	            	actualStatuses="failed"
        	            	 expectedError=""
        	            	  actualErrors="incorrect number of span partitions expected=2 actual=1
        	            	HINT: You have encountered an unexpected error.
        	            	
        	            	Please check the public issue tracker to check whether this problem is
        	            	already tracked. If you cannot find it there, please report the error
        	            	with details by creating a new issue.
        	            	
        	            	If you would rather not post publicly, please contact us directly
        	            	using the support form.
        	            	
        	            	We appreciate your feedback.
        	            	"
--- FAIL: TestRowLevelTTLJobMultipleNodes/1_split (1.79s)
=== RUN   TestRowLevelTTLJobMultipleNodes/2_splits
    test_server_shim.go:91: cluster virtualization disabled due to issue: #109391 (expected label: C-bug)
    test_server_shim.go:610: DRPC is enabled (override by TestingGlobalDRPCOption)
    ttljob_test.go:219: 
        	Error Trace:	pkg/sql/ttl/ttljob/ttljob_test.go:219
        	            				pkg/sql/ttl/ttljob/ttljob_test.go:740
        	Error:      	Should be true
        	Test:       	TestRowLevelTTLJobMultipleNodes/2_splits
        	Messages:   	
        	            	expectedStatus="succeeded"
        	            	actualStatuses="failed"
        	            	 expectedError=""
        	            	  actualErrors="incorrect number of span partitions expected=3 actual=1
        	            	HINT: You have encountered an unexpected error.
        	            	
        	            	Please check the public issue tracker to check whether this problem is
        	            	already tracked. If you cannot find it there, please report the error
        	            	with details by creating a new issue.
        	            	
        	            	If you would rather not post publicly, please contact us directly
        	            	using the support form.
        	            	
        	            	We appreciate your feedback.
        	            	"
--- FAIL: TestRowLevelTTLJobMultipleNodes/2_splits (1.87s)
```
Only fails for the `1_split` and `2_split` testcases, not for the `0_split` testcase.

**Environment:**
 - CockroachDB version [master]

Epic: CRDB-55382

Jira issue: CRDB-57269

### PR DESCRIPTION
**Pull request by cthumuluru-crdb**
Refactor the `Dialbacker` interface to be generic (`Dialbacker[Conn rpcConn]`) and introduce protocol-specific adapters (`GRPCDialbackAdapter`, `DRPCDialbackAdapter`) that implement it. This allows `VerifyDialback` to work with both gRPC and DRPC connections without coupling to a specific rpc framework.

The `VerifyDialback` function now accepts a `Dialbacker[Conn]` instead of directly calling gRPC-specific methods on `*Context`. Each adapter delegates to the appropriate dial methods on `*Context` for its protocol. The mock in `rpc_mock_test.go` is updated to be generic as well.

With this in place, re-enable DRPC in the row-level TTL job test helper (`newRowLevelTTLTestJobTestHelper`) by removing the `DefaultDRPCOption: base.TestDRPCDisabled` override that was added as a workaround.

Epic: CRDB-55382
Fixes: #158387
Release note: None

### CODE REVIEW

File: pkg/server/server.go [hunk 1]
```diff
@@ -369,6 +369,16 @@ func NewServer(cfg Config, stopper *stop.Stopper) (serverctl.ServerStartupInterf
 	}
 	rpcContext := rpc.NewContext(ctx, rpcCtxOpts)
 
+	verifyDialbackFn := func() func(context.Context, *rpc.PingRequest, *rpc.PingResponse) error {
+		if !rpcContext.UseDRPC {
+			return func(ctx context.Context, req *rpc.PingRequest, resp *rpc.PingResponse) error {
+				return rpc.VerifyDialback(ctx, rpc.NewGRPCDialbackAdapter(rpcContext), req, resp, roachpb.Locality{}, &rpcContext.Settings.SV)
```
Comment (Nukitt) [inline pkg/server/server.go]: We should be passing `cfg.Locality` instead of `roachpb.Locality{}`?

File: pkg/server/server.go [hunk 2]
```diff
@@ -369,6 +369,16 @@ func NewServer(cfg Config, stopper *stop.Stopper) (serverctl.ServerStartupInterf
...
+			}
+		}
+		return func(ctx context.Context, req *rpc.PingRequest, resp *rpc.PingResponse) error {
+			return rpc.VerifyDialback(ctx, rpc.NewDRPCDialbackAdapter(rpcContext), req, resp, roachpb.Locality{}, &rpcContext.Settings.SV)
```
Comment (Nukitt) [inline pkg/server/server.go]: Same as above, `cfg.Locality`.

File: pkg/rpc/context_test.go [hunk 3]
```diff
@@ -2045,12 +2055,16 @@ func TestHeartbeatDialback(t *testing.T) {
 func TestVerifyDialback(t *testing.T) {
 	defer leaktest.AfterTest(t)()
 
-	run := func(t *testing.T, name string, f func(t *testing.T, mockRPCCtx *MockDialbacker, sv *settings.Values)) {
+	run := func(
+		t *testing.T,
+		name string,
+		f func(t *testing.T, mockRPCCtx *MockDialbacker[*grpc.ClientConn], sv *settings.Values),
```
Comment (Nukitt) [inline pkg/rpc/context_test.go]: IMO we should also have an equivalent for DRPC so that we have that coverage too.

Comment (cthumuluru-crdb) [reply pkg/rpc/context_test.go]: Done

**Review by Nukitt — APPROVED** [review]
:lgtm:

> @Nukitt reviewed 8 files and all commit messages, and made 1 comment.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/165520#-:-OnuU8b34D787x3oPtF1:bnfp4nl)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on cthumuluru-crdb and shubhamdhama).

**Review by shubhamdhama — APPROVED** [review]
