### PR TITLE
kvserver: fix race on Replica.tenantLimiter

### LINKED ISSUE #95345: kv: data race in `(*Replica).recordImpactOnRateLimiter`
Found here: https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_BazelExtendedCi/8334227?showRootCauses=false&expandBuildChangesSection=true&expandBuildProblemsSection=true&expandBuildTestsSection=true

```
==================
WARNING: DATA RACE
Read at 0x00c00bfd8550 by goroutine 582130:
  github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*Replica).recordImpactOnRateLimiter()
      github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/replica_rate_limit.go:39 +0x58
  github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*Replica).SendWithWriteBytes()
      github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/replica_send.go:213 +0x8a4
  github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*Store).SendWithWriteBytes()
      github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/store_send.go:205 +0xb51
  github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*Stores).SendWithWriteBytes()
      github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/stores.go:203 +0x252
  github.com/cockroachdb/cockroach/pkg/server.(*Node).batchInternal()
      github.com/cockroachdb/cockroach/pkg/server/node.go:1121 +0x712
  github.com/cockroachdb/cockroach/pkg/server.(*Node).Batch()
      github.com/cockroachdb/cockroach/pkg/server/node.go:1173 +0x275
  github.com/cockroachdb/cockroach/pkg/rpc.makeInternalClientAdapter.func1()
      github.com/cockroachdb/cockroach/pkg/rpc/pkg/rpc/context.go:741 +0x7c
[...]
Previous write at 0x00c00bfd8550 by goroutine 567167:
        github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*Replica).postDestroyRaftMuLocked()
            github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/replica_destroy.go:135 +0x21b
        github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*Replica).handleChangeReplicasResult()
            github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/replica_application_result.go:340 +0x2ef
        github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*replicaStateMachine).handleNonTrivialReplicatedEvalResult()
            github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/replica_application_state_machine.go:338 +0xd44
        github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*replicaStateMachine).ApplySideEffects()
            github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/replica_application_state_machine.go:186 +0x633
        github.com/cockroachdb/cockroach/pkg/kv/kvserver/apply.StateMachine.ApplySideEffects-fm()
            <autogenerated>:1 +0x85
        github.com/cockroachdb/cockroach/pkg/kv/kvserver/apply.mapCheckedCmdIter()
            github.com/cockroachdb/cockroach/pkg/kv/kvserver/apply/cmd.go:210 +0x1da
        github.com/cockroachdb/cockroach/pkg/kv/kvserver/apply.(*Task).applyOneBatch()
            github.com/cockroachdb/cockroach/pkg/kv/kvserver/apply/task.go:304 +0x266
        github.com/cockroachdb/cockroach/pkg/kv/kvserver/apply.(*Task).ApplyCommittedEntries()
            github.com/cockroachdb/cockroach/pkg/kv/kvserver/apply/task.go:260 +0xd5
        github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*Replica).handleRaftReadyRaftMuLocked()
            github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/replica_raft.go:984 +0x1df1
        github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*Replica).handleRaftReady()
            github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/replica_raft.go:677 +0x14f
        github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*Store).processReady()
```

cc @tbg @nvanbenschoten for triage.

Jira issue: CRDB-23467

### PR DESCRIPTION
**Pull request by pav-kv**
When Replica is being destroyed, it can set tenantLimiter to nil. However, all accessors assume synchronization through IsInitialized atomic check and that this field can't be modified after the replica is initialized.

There is no particular need in nullifying this limiter, the replica is going away soon, so this commit removes this line in order to fix the data race.

Fixes #95345
Epic: none
Release note: none

### CODE REVIEW

File: pkg/kv/kvserver/replica_destroy.go [hunk 1]
```diff
@@ -132,7 +132,6 @@ func (r *Replica) postDestroyRaftMuLocked(ctx context.Context, ms enginepb.MVCCS
 	// Unhook the tenant rate limiter if we have one.
 	if r.tenantLimiter != nil {
 		r.store.tenantRateLimiters.Release(r.tenantLimiter)
-		r.tenantLimiter = nil
```
Comment (pavelkalinnikov) [inline pkg/kv/kvserver/replica_destroy.go:135]: Alternatively, we could protect `tenantLimiter` with `Replica.mu`, but I don't see much benefit. WDYT?

Comment (tbg) [reply pkg/kv/kvserver/replica_destroy.go:135]: Both options seem a little iffy. I don't want us to introduce another mutex acquisition in the critical path but at the same time it's not trivial to rearrange the users of this into an existing critical section.

Use-after-Release on the `tenantLimiter` might work - I looked at the code a bit and it seems like it doesn't destroy or pool any memory; it really just unlinks the limiter from the parent.

Let's go with the second option (the one you have chosen) but add a test in `tenantrate` that proves that you can use a limiter after it's been released and that this will not crash and also no longer influence the surrounding aggregating metric.

**Review by tbg — CHANGES_REQUESTED** [review]
LGTM mod adding a unit test as per comment.

File: pkg/kv/kvserver/replica_destroy.go (hunk 1 above)
Comment (pavelkalinnikov) [reply pkg/kv/kvserver/replica_destroy.go:135]: I wrote a test. It does not panic after `Release`, but the parent metric is still updated. The `Destroy` method removes the child metric from the parent's tree, but still leaves the child->parent reference and keeps updating the parent metric. This API doesn't quite make sense to me, but it is what it is.

I think it's fine for counter metrics if some in-flight `Inc`rements slip through, but with the `Gauge` metrics we can't reliably reset it to 0 (and update the parent so that it no longer accounts for this value), a racing change may result in a permanent non-zero leak to the aggregate.

Comment (pavelkalinnikov) [reply pkg/kv/kvserver/replica_destroy.go:135]: I don't know, but the whole fact that `Send` can race with `Replica` destruction, and operate on a half-destroyed one, seems iffy.

Comment (pavelkalinnikov) [reply pkg/kv/kvserver/replica_destroy.go:135]: I think that the `Replica` "state machine" is confusing. Many things assume that there are only 2 states: uninitialized and initialized (hence the `IsInitialized` checks in many places, including `Send`, and assumption that many things synchronize through it), but in reality there is also `destroyStatus` which breaks this dichotomy.

File: pkg/kv/kvserver/tenantrate/factory.go [hunk 2]
```diff
@@ -121,6 +121,7 @@ func (rl *LimiterFactory) Release(lim Limiter) {
 	}
 	if rcLim.refCount--; rcLim.refCount == 0 {
 		l.metrics.destroy()
+		l.qp.Close("released")
```
Comment (pavelkalinnikov) [inline pkg/kv/kvserver/tenantrate/factory.go:124]: Nice

**Comment by pavelkalinnikov** [comment]
LGTM

File: pkg/kv/kvserver/replica_destroy.go (hunk 1 above)
Comment (tbg) [reply pkg/kv/kvserver/replica_destroy.go:135]: @RaduBerinde for this usage here

https://github.com/cockroachdb/cockroach/blob/e6e092fefc2a5ba0ff6342728f7b14f51e789899/pkg/ccl/multitenantccl/tenantcostserver/metrics.go#L170-L193

isn't it weird that these are gauges in the first place? And also, I don't see this getting released anywhere (we hold on to a map entry for a tenant forever), I assume this is intentional. So this should not be affected by not resetting gauges to zero but please let me know if we're missing something.

**Comment by tbg** [comment]
I audited the callers to `Unlink()` and they're specific to the use of aggmetric in tenant storage metrics and I think there's only one more that needed to change (see new commit).
Unfortunately this didn't break any tests so wondering if you could backfill a unit test and also double check my analysis that nobody else even called `Unlink` on `Gauge{,Float64}` other than the two places we have now dealt with (tenant rate limiter and tenant store metrics).

**Comment by pavelkalinnikov** [comment]
@tbg Added a test (also verified that it would fail with your penultimate commit). Yes, `Unlink` seems to be only used by the two places that we've covered.

File: pkg/kv/kvserver/tenantrate/factory.go (hunk 2 above)
Comment (pavelkalinnikov) [inline pkg/kv/kvserver/tenantrate/factory.go:124]: Does this strictly prevent the race? The other end may notice the closed channel too late, and still write to the metric, no?

I wonder if the proper solution to this would be ref-counting not only at the `Replica` level, but at the request level. I.e. make it so that `Send` gets a ref-incremented `Limiter`, and `Releases` it in the end; instead of relying on `Replica` to do so.

Comment (pavelkalinnikov) [reply pkg/kv/kvserver/tenantrate/factory.go:124]: Ah, I see, we rely on the fact that there is only one `Gauge` metric which also happens to be related to synchronization. We close the channel, and then some time after the waiters decrement the counter. In the meantime, we only `Unlink`. The counter eventually will stabilize.

Any generic gauge addition would break things again. Worth noting this and TODOing.

Comment (tbg) [reply pkg/kv/kvserver/tenantrate/factory.go:124]: 👍🏽 Did you want to add a TODO?

File: pkg/kv/kvserver/metrics.go [hunk 3]
```diff
@@ -2152,24 +2152,31 @@ func (sm *TenantsStorageMetrics) releaseTenant(ctx context.Context, ref *tenantM
...
+		&m.IntentAge,
+		&m.GcBytesAge,
+		&m.SysBytes,
+		&m.SysCount,
+		&m.AbortSpanBytes,
+	} {
+		// Reset before unlinking, see Unlink.
+		(*gptr).Update(0)
+		(*gptr).Unlink()
+		*gptr = nil
```
[the remark this answers is not in the document]
Comment (tbg) [reply pkg/kv/kvserver/metrics.go:2178]: I'm not opposed, your PR after all! For me personally this is ok as is.

**Review by tbg — APPROVED** [review]

File: pkg/kv/kvserver/tenantrate/factory.go (hunk 2 above)
Comment (pavelkalinnikov) [reply pkg/kv/kvserver/tenantrate/factory.go:124]: I think you covered it well in the comment next to `r.tenantLimiter`. Injected a TODO there.

File: pkg/kv/kvserver/metrics.go (hunk 3 above)
[the remark this answers is not in the document]
Comment (pavelkalinnikov) [reply pkg/kv/kvserver/metrics.go:2178]: Leaving as is.

**Comment by pavelkalinnikov** [comment]
TFTR!

**Comment by pavelkalinnikov** [comment]
bors r=tbg

**Comment by pavelkalinnikov** [comment]
bors retry
