### PR TITLE
changefeedccl: fix TestNoBackfillAfterNonTargetColumnDrop

### LINKED ISSUE #150214: changefeedccl: TestNoBackfillAfterNonTargetColumnDrop is broken
The comment for `TestNoBackfillAfterNonTargetColumnDrop` claims that it tests that we don't backfill when we drop a column from an unwatched family. The test however does not verify this because the backfill messages are filtered out as duplicates by the test sink.

Steps to reproduce:

1. Apply this diff and run the test.
```
diff --git a/pkg/ccl/changefeedccl/schemafeed/table_event_filter.go b/pkg/ccl/changefeedccl/schemafeed/table_event_filter.go
index 84536bbe21c..91a71a0276d 100644
--- a/pkg/ccl/changefeedccl/schemafeed/table_event_filter.go
+++ b/pkg/ccl/changefeedccl/schemafeed/table_event_filter.go
@@ -147,11 +147,7 @@ func (filter tableEventFilter) shouldFilter(
                        // For example, we may be dropping a column which is not
                        // monitored by the changefeed.
                        if filterEvent == tableEventDropColumn {
-                               sf, err := shouldFilterDropColumnEvent(e, targets)
-                               if err != nil {
-                                       return false, err
-                               }
-                               shouldFilter = sf && shouldFilter
+                               shouldFilter = false
                        } else if filterEvent == tableEventAddColumnNoBackfill || filterEvent == tableEventAddColumnWithBackfill {
                                sf, err := shouldFilterAddColumnEvent(e, targets)
                                if err != nil {
```
2. We'd expect the test to now fail, but the test continues to pass.

Jira issue: CRDB-52607

### PR DESCRIPTION
**Pull request by andyyang890**
This patch fixes `TestNoBackfillAfterNonTargetColumnDrop` so that it
actually checks that no backfills occur after a non-target column drop.

Fixes #150214

Release note: None

### CODE REVIEW

File: pkg/ccl/changefeedccl/changefeed_test.go [hunk 1]
```diff
@@ -1931,27 +1931,31 @@ func TestNoBackfillAfterNonTargetColumnDrop(t *testing.T) {
 		}
 
 		// Open up the changefeed.
-		cf := feed(t, f, `CREATE CHANGEFEED FOR TABLE hasfams FAMILY b_and_c`, args...)
+		// NB: `updated` is needed to make sure we aren't getting an extra backfill
```
Comment (aerfrei) [inline pkg/ccl/changefeedccl/changefeed_test.go]: Would it be possible to make this check without having to specify `updated` and then strip the timestamps? My thought is that we could specify `initial_scan='no'` and just remove that first assertion that we get the `hasfams.b_and_c: [0]->{"after": {"b": "b", "c": "c"}}` payload.

Comment (andyyang890) [reply pkg/ccl/changefeedccl/changefeed_test.go]: Is there a reason you're opposed to having `updated`? While your suggestion works, we'd lose the coverage that the initial scan happened.

Comment (aerfrei) [reply pkg/ccl/changefeedccl/changefeed_test.go]: I found it a little confusing to specify updated when we won't actually assert anything about it, though the comment will hopefully make this clear. My sense was that this test was specifically about backfills and how they interact with dropped columns so the initial scan wasn't as relevant. Either way works for me.

**Review by aerfrei — APPROVED** [review]

File: pkg/ccl/changefeedccl/changefeed_test.go (hunk 1 above)
Comment (andyyang890) [reply pkg/ccl/changefeedccl/changefeed_test.go]: Thanks for the feedback. I updated the comment to hopefully be more clear now.

**Review by asg0451 — APPROVED** [review]

**Comment by andyyang890** [comment]
TFTRs!

bors r=aerfrei,asg0451

**Comment by andyyang890** [comment]
bors retry
