### PR TITLE
kvserver: deflake TestLearnerReplicateQueueRace

### LINKED ISSUE #95130: kv/kvserver: TestLearnerReplicateQueueRace failed
kv/kvserver.TestLearnerReplicateQueueRace [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Ci_TestsAwsLinuxArm64_UnitTests/8281964?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Ci_TestsAwsLinuxArm64_UnitTests/8281964?buildTab=artifacts#/) on master @ [033a395ae83f8175eee609bd4918a31cf807fc9b](https://github.com/cockroachdb/cockroach/commits/033a395ae83f8175eee609bd4918a31cf807fc9b):

Fatal error:

```
panic: test timed out after 59m55s

```
Stack: 

```
goroutine 178283 [running]:
testing.(*M).startAlarm.func1()
	GOROOT/src/testing/testing.go:2036 +0x88
created by time.goFunc
	GOROOT/src/time/sleep.go:176 +0x38
```
<details><summary>Log preceding fatal error</summary>
<p>

```
* google.golang.org/grpc.(*Server).serveStreams(0x400543d860, {0x6897bc0?, 0x4006e8d380})
* 	google.golang.org/grpc/external/org_golang_google_grpc/server.go:975 +0x148
* google.golang.org/grpc.(*Server).handleRawConn.func1()
* 	google.golang.org/grpc/external/org_golang_google_grpc/server.go:891 +0x44
* created by google.golang.org/grpc.(*Server).handleRawConn
* 	google.golang.org/grpc/external/org_golang_google_grpc/server.go:890 +0x184
* 
* goroutine 169208 [chan receive, 3 minutes]:
* github.com/cockroachdb/pebble.(*tableCacheShard).releaseLoop.func1({0x684c6f8, 0x40073e4360})
* 	github.com/cockroachdb/pebble/external/com_github_cockroachdb_pebble/table_cache.go:324 +0x80
* runtime/pprof.Do({0x684c688?, 0x40001b2000?}, {{0x400035fd60?, 0x684c6f8?, 0x0?}}, 0x400d5ef798)
* 	GOROOT/src/runtime/pprof/runtime.go:40 +0x80
* github.com/cockroachdb/pebble.(*tableCacheShard).releaseLoop(0x40068441e0?)
* 	github.com/cockroachdb/pebble/external/com_github_cockroachdb_pebble/table_cache.go:322 +0x6c
* created by github.com/cockroachdb/pebble.(*tableCacheShard).init
* 	github.com/cockroachdb/pebble/external/com_github_cockroachdb_pebble/table_cache.go:314 +0xf0
* 
* goroutine 168669 [select]:
* github.com/cockroachdb/cockroach/pkg/util/admission.(*WorkQueue).startClosingEpochs.func1()
* 	github.com/cockroachdb/cockroach/pkg/util/admission/work_queue.go:419 +0x224
* created by github.com/cockroachdb/cockroach/pkg/util/admission.(*WorkQueue).startClosingEpochs
* 	github.com/cockroachdb/cockroach/pkg/util/admission/work_queue.go:392 +0x60
* 
* goroutine 168785 [chan receive, 3 minutes]:
* github.com/cockroachdb/pebble.(*tableCacheShard).releaseLoop.func1({0x684c6f8, 0x400bcf6f90})
* 	github.com/cockroachdb/pebble/external/com_github_cockroachdb_pebble/table_cache.go:324 +0x80
* runtime/pprof.Do({0x684c688?, 0x40001b2000?}, {{0x400035fd60?, 0x400063a601?, 0x0?}}, 0x4001d8e798)
* 	GOROOT/src/runtime/pprof/runtime.go:40 +0x80
* github.com/cockroachdb/pebble.(*tableCacheShard).releaseLoop(0x4001d8e758?)
* 	github.com/cockroachdb/pebble/external/com_github_cockroachdb_pebble/table_cache.go:322 +0x6c
* created by github.com/cockroachdb/pebble.(*tableCacheShard).init
* 	github.com/cockroachdb/pebble/external/com_github_cockroachdb_pebble/table_cache.go:314 +0xf0
* 
* goroutine 169221 [chan receive, 3 minutes]:
* github.com/cockroachdb/pebble.(*tableCacheShard).releaseLoop.func1({0x684c6f8, 0x40073e5ce0})
* 	github.com/cockroachdb/pebble/external/com_github_cockroachdb_pebble/table_cache.go:324 +0x80
* runtime/pprof.Do({0x684c688?, 0x40001b2000?}, {{0x400035fd60?, 0x400d727680?, 0x10160e0?}}, 0x40052b0798)
* 	GOROOT/src/runtime/pprof/runtime.go:40 +0x80
* github.com/cockroachdb/pebble.(*tableCacheShard).releaseLoop(0x40052b0758?)
* 	github.com/cockroachdb/pebble/external/com_github_cockroachdb_pebble/table_cache.go:322 +0x6c
* created by github.com/cockroachdb/pebble.(*tableCacheShard).init
* 	github.com/cockroachdb/pebble/external/com_github_cockroachdb_pebble/table_cache.go:314 +0xf0
* 
* goroutine 168667 [select]:
* github.com/cockroachdb/cockroach/pkg/util/admission.(*WorkQueue).startClosingEpochs.func1()
* 	github.com/cockroachdb/cockroach/pkg/util/admission/work_queue.go:419 +0x224
* created by github.com/cockroachdb/cockroach/pkg/util/admission.(*WorkQueue).startClosingEpochs
* 	github.com/cockroachdb/cockroach/pkg/util/admission/work_queue.go:392 +0x60
* 
*
```
</p>
</details>
<details><summary>Help</summary>
<p>

See also: [How To Investigate a Go Test Failure \(internal\)](https://cockroachlabs.atlassian.net/l/c/HgfXfJgM)
</p>
</details>
/cc @cockroachdb/kv
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*TestLearnerReplicateQueueRace.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)
</sub>

Jira issue: CRDB-23353

### PR DESCRIPTION
**Pull request by tbg**
It's not a good idea to `t.Fatal` on a goroutine. I verified that the test fails cleanly
even when the callback doesn't actually do the removal.

Fixes #95130.

Epic: none
Release note: None

### CODE REVIEW

File: pkg/kv/kvserver/replica_learner_test.go [hunk 1]
```diff
@@ -1300,7 +1302,7 @@ func TestLearnerReplicateQueueRace(t *testing.T) {
 			if err != nil {
 				return err
 			}
-			if !strings.Contains(processErr.Error(), `descriptor changed`) {
+			if processErr == nil || !strings.Contains(processErr.Error(), `descriptor changed`) {
 				// NB: errors.Wrapf(nil, ...) returns nil.
 				// nolint:errwrap
```
Comment (pavelkalinnikov) [inline pkg/kv/kvserver/replica_learner_test.go:1307]: Is this up-to-date? No `Wrapf` I see.

**Review by pav-kv — APPROVED** [review]

File: pkg/kv/kvserver/replica_learner_test.go (hunk 1 above)
Comment (tbg) [reply pkg/kv/kvserver/replica_learner_test.go]: Removed.

**Comment by tbg** [comment]
bors r=pavelkalinnikov
