### PR TITLE
roachtest/mixedversion: `WaitForReplication` must ensure SQL is ready

### LINKED ISSUE #137988: roachtest/mixedversion: `WaitForReplication` (temporally) depends on lazily initialized `SyntheticPrivilegeCache`
### Background

It _appears_ that the addition of _shared-process_ tenants to the mixedversion upgrade tests resulted in a new type of flakes, wherein simple (framework-internal) queries, e.g., `SHOW CLUSTER SETTING version` would suddenly time out [1]. These timeouts typically occur immediately after a tenant is (re)started.

##### First Clue

The framework periodically executes `refreshServiceData` to query the latest cluster version(s), and to refresh its internal cache of  db connections, i.e., `service.connCache`. In [1], `refreshServiceData` timed out after a node with a shared-process tenant was restarted. In fact it was `get-user-session` which timed out, causing the above query to fail. We will come back to this, shortly.

```
W240910 06:01:03.559129 3272 sql/user.go:201 ⋮ [T3,Vmixed-version-tenant-xssxz,n1,client=10.1.0.176:55970,hostssl,user=‹roachprod›] 199  user membership lookup for ‹"roachprod"› failed: operation "get-user-session" timed out after 10s (given timeout 10s): internal error while retrieving user account: get default settings error: interrupted during singleflight ‹load-value:defaultsettings-roachprod-104-1›: context deadline exceeded
```

##### First Workaround Attempt

As was hypothesized in [1], the reason for the actual time out may have been "cluster overload", perhaps induced by under-replicated ranges, triggered by a node restart. Indeed, we have seen such cases in the past, as described in [2],

> We had a number of test failures like (https://github.com/cockroachdb/cockroach/issues/101438) where test fails when initializing or starting workload because cluster is still upreplicating system ranges. This could cause slowness when accessing liveness, metrics, id generators etc and in turn cause timeouts and fail tests.

Furthermore, a number of existing roachtests were already using `WaitFor3XReplication`, immediately after starting (at least 3) nodes. Subsequently, in [3], this option was added to the mixedversion framework, specifically to `startStep` and `restartWithNewBinaryStep`. Note, as of [3], the option's default (for mixedversion tests) was _opt-in_, and it was enabled only for `c2c/mixed-version`.

##### Second Workaround Attempt

Several months later, the same failure mode (i.e., `get-user-session` timed out) is observed, e.g., [4], this time for a _different_ set of mixedversion tests. In [5], `waitForReplication` is changed to _opt-out_, and thus enabled for all mixedversion tests.

##### Status Quo

Despite enabling `waitForReplication` for _all_ mixedversion tests, we are continuing to observe the same failure mode [6].

### Analysis

Before `waitForReplication`, the mixedversion framework saw the addition of `waitForSharedProcess`.

##### Second Clue

In [7], it was observed that a freshly started, shared-process tenant would fail to respond in time,

```
pq: service unavailable for target tenant (mixed-version-tenant-dhpkw)
```

Thus, `waitForSharedProcess` was added to both `startSharedProcessVirtualClusterStep` and `restartWithNewBinaryStep`.

**NOTE**: Upon restart, shared-process tenants are always started _before_ the system tenant (see `startInitialSecondaryTenantServer`). Thus, `waitForSharedProcess` is technically _not_ needed in `restartWithNewBinaryStep`. Furthermore, the cluster setting `server.controller.mux_virtual_cluster_wait.timeout` has a default value of `10s`. This is the amount of time, the sql controller (`serverController->sqlMux`) will automatically wait before the corresponding shared-process tenant is ready to serve. Thus, `waitForSharedProcess` is tantamount to increasing `server.controller.mux_virtual_cluster_wait.timeout`.

##### Final Clue

As described in [8], the final clue came in the following message,

```
I241212 11:19:11.321291 53045 sql/syntheticprivilegecache/cache.go:198 â‹® [T3,Vmixed-version-tenant-mbqzz,n3] 145  warmed privileges for virtual tables in 10.007996435s
```

> This corresponds to the completion of s.execCfg.SyntheticPrivilegeCache.Start(ctx) in SQLServer.preStart. The function is executed asynchronously and reads from system.privileges. Since non-root user authentication requires system.users to be available, and the two system tables are likely to be owned by the same leaseholder, we can infer that it took ~10 seconds for SQLServer to be fully initialized.

##### Root Cause

The root cause of the failures of the form `get-user-session timed out` is due to the fact that `SyntheticPrivilegeCache` is initialized _asynchronously_. (During initialization, `Cache.Get` is blocked by `Cache.waitForWarmed`.) Thus, while both system and shared-process tenants might be ready to serve sql, _session authentication_ isn't ready until after `SyntheticPrivilegeCache.Start` returns.

Interestingly, in [8], we see the following timing sequence on `n3`,

```
I241212 11:19:01.313353 19736 1@server/server_controller_new_server.go:391 â‹® [T3,Vmixed-version-tenant-mbqzz,n3,tenant-orchestration,tenant=â€¹mixed-version-tenant-mbqzzâ€º,start-server] 137  tenant startup completed:
I241212 11:19:01.313507 89 1@cli/start.go:1287 â‹® [T1,Vsystem,n3] 141  node startup completed:
```

```
I241212 11:18:51.175664 18882 sql/syntheticprivilegecache/cache.go:198 â‹® [T1,Vsystem,n3] 94  warmed privileges for virtual tables in 8.064531ms
I241212 11:19:11.321291 53045 sql/syntheticprivilegecache/cache.go:198 â‹® [T3,Vmixed-version-tenant-mbqzz,n3] 145  warmed privileges for virtual tables in 10.007996435s
```

Recall, `startInitialSecondaryTenantServer` ensures that shared-process tenants are started _before_ the system tenant, which is what we observe above. However, the completion times of initializing `SyntheticPrivilegeCache` are _reversed_. Note the asymmetry.

Furthermore, an astute reader will have noticed that the message (in `n3`'s log), correlated to the following message, in `test.log`,

```
[mixed-version-test/20_restart-node-3-with-binary-version-v24.3.0] 2024/12/12 11:19:11 runner.go:366: mixed-version test failure while running step 20 (restart node 3 with binary version v24.3.0): failed to wait for replication after starting cockroach: pq: internal error while retrieving user account memberships: operation "get-user-session" timed out after 10s (given timeout 10s): internal error while retrieving user account: get auth info error: interrupted during singleflight load-value:authinfo-roachprod-2-2: context deadline exceeded
```

refers to the shared-process tenant, namely `mixed-version-tenant-mbqzz`,

```
W241212 11:19:11.338657 53100 sql/user.go:196 â‹® [T3,Vmixed-version-tenant-mbqzz,n3,client=34.162.130.233:33010,hostssl,user=â€¹roachprodâ€º] 147  user membership lookup for â€¹"roachprod"â€º failed: operation "get-user-session" timed out after 10s (given timeout 10s): internal error while retrieving user account: get auth info error: interrupted during singleflight â€¹load-value:authinfo-roachprod-2-2â€º: context deadline exceeded
```

This implies that the sql session used by `WaitForReplication` is _not_ connected to the `system` tenant. How can that be?! The answer is rather subtle... In `test.log`, we can see that step 6 of the upgrade plan resets the cluster setting `server.controller.default_target_cluster` to the `system` tenant. This is indeed a _feature_ of the mixedversion framework [9], designed to fuzz cluster settings, for better (code) coverage.

```
set cluster setting "server.controller.default_target_cluster" to 'mixed-version-tenant-mbqzz' on system tenant (6)
```

##### Unhidden Bug

As bonus of the root cause investigation, another bug was uncovered, which otherwise remained hidden. Recall, the goal of `WaitForReplication` is to ensure the entire cluster is caught up wrt replication. In the above example, we saw that `WaitForReplication`, which reads from `crdb_internal.ranges`, was invoked against a _shared-process_ tenant, not the system tenant. 

Clearly, secondary tenants cannot be allowed to read from system tenant's ranges; otherwise, they could access other secondary tenant's data–breaking tenant isolation. Instead, each secondary tenant gets a view of their own "system" ranges, i.e., ranges prefixed by the tenant id. As a quick illustration, let's create a secondary tenant and count its ranges vs. system,

```
create tenant 'foo';
alter tenant 'foo' start service SHARED;
```

```
root@localhost:26257/foo/defaultdb> select count(1) from crdb_internal.ranges;
  count
---------
     11
(1 row)

root@localhost:26257/defaultdb> select count(1) from crdb_internal.ranges;
  count
---------
     97
(1 row)
```

Thus, even if `WaitForReplication` did not time out during authentication, it would have only ensured that the secondary tenant's ranges are fully replicated, not the whole system's, as originally intended.

### Conclusion

Ironically, `WaitForReplication` times out _not_ because of replication, but because it wrongly assumes that a sql session is _ready_ upon a successful connection; what's missing is the check that `SyntheticPrivilegeCache` is initialized; successful execution of `select 1` would establish it. Furthermore, `WaitForReplication` should always be invoked on the `system` tenant.

While `waitForSharedProcess` is technically redundant in light of `server.controller.mux_virtual_cluster_wait.timeout`, it is orthogonal to `WaitForReplication`. That is, `waitForSharedProcess` only ensures that a shared-process tenant was _started_, and _ready_ to server sql. (Also, unlike `WaitForReplication`, `waitForSharedProcess` does successively retry `select 1`, which is the correct pattern wrt (sql) session readiness.)

[1] https://github.com/cockroachdb/cockroach/issues/130384
[2] https://github.com/cockroachdb/cockroach/issues/101532
[3] https://github.com/cockroachdb/cockroach/pull/130615
[4] https://github.com/cockroachdb/cockroach/issues/136440
[5] https://github.com/cockroachdb/cockroach/pull/136607
[6] https://github.com/cockroachdb/cockroach/issues/137332
[7] https://github.com/cockroachdb/cockroach/pull/127393#pullrequestreview-2184105558
[8] https://github.com/cockroachdb/cockroach/issues/137332#issuecomment-2547439417
[9] https://github.com/cockroachdb/cockroach/blob/master/pkg/cmd/roachtest/roachtestutil/mixedversion/README.md#mutators

Jira issue: CRDB-45840

### PR DESCRIPTION
**Pull request by srosenberg**
Previously, mixedversion roachtests would occassionally fail while trying to execute SQL against a freshly started node; specifically, `get-user-session` would time out. The precise root cause is described in [1].

As of [2], `WaitForReplication` is the default used by all mixedversion roachtests. Thus, it suffices
to ensure that "SQL is ready" before
`WaitForReplication` is invoked.

However, a number of roachtests don't opt into
`StartOpts.WaitForReplication`, which makes them
susceptible to the same failure mode, e.g., [3].
Thus, we unconditionally `WaitForSQLReady`, for
the system tenant, on every started DB node.

[1] https://github.com/cockroachdb/cockroach/issues/137988
[2] https://github.com/cockroachdb/cockroach/pull/136607
[3] https://github.com/cockroachdb/cockroach/issues/137382

Fixes: https://github.com/cockroachdb/cockroach/issues/137988
Informs: https://github.com/cockroachdb/cockroach/issues/137332

Epic: none
Release note: None

### CODE REVIEW

**Comment by srosenberg** [comment]
10 runs using the SEED (`COCKROACH_RANDOM_SEED=-7845636561506696193`) from [1],

```
artifacts-137332/tpcc/mixed-headroom/n5cpu16/run_1/test.log:2024/12/31 10:02:18 test_runner.go:1205: --- PASS: tpcc/mixed-headroom/n5cpu16#1 (17286.21s)
artifacts-137332/tpcc/mixed-headroom/n5cpu16/run_3/test.log:2024/12/31 10:01:44 test_runner.go:1205: --- PASS: tpcc/mixed-headroom/n5cpu16#3 (17265.54s)
artifacts-137332/tpcc/mixed-headroom/n5cpu16/run_4/test.log:2024/12/31 10:01:57 test_runner.go:1205: --- PASS: tpcc/mixed-headroom/n5cpu16#4 (17272.15s)
artifacts-137332/tpcc/mixed-headroom/n5cpu16/run_5/test.log:2024/12/31 11:00:15 test_runner.go:1205: --- PASS: tpcc/mixed-headroom/n5cpu16#5 (17533.08s)
artifacts-137332/tpcc/mixed-headroom/n5cpu16/run_6/test.log:2024/12/31 14:50:13 test_runner.go:1205: --- PASS: tpcc/mixed-headroom/n5cpu16#6 (17271.72s)
artifacts-137332/tpcc/mixed-headroom/n5cpu16/run_7/test.log:2024/12/31 14:50:56 test_runner.go:1205: --- PASS: tpcc/mixed-headroom/n5cpu16#7 (17303.44s)
artifacts-137332/tpcc/mixed-headroom/n5cpu16/run_8/test.log:2024/12/31 14:51:06 test_runner.go:1205: --- PASS: tpcc/mixed-headroom/n5cpu16#8 (17291.17s)
artifacts-137332/tpcc/mixed-headroom/n5cpu16/run_9/test.log:2024/12/31 15:48:04 test_runner.go:1205: --- PASS: tpcc/mixed-headroom/n5cpu16#9 (17231.92s)
```

[1] https://github.com/cockroachdb/cockroach/issues/137332#issue-2735614277

File: pkg/cmd/roachtest/roachtestutil/utils.go [hunk 1]
```diff
@@ -163,9 +165,25 @@ func CloseExporter(
...
+	return retryOpts.Do(ctx, func(ctx context.Context) error {
+		_, err := db.ExecContext(ctx, "SELECT 1")
+		return err
+	})
+}
+
 // WaitForReady waits until the given nodes report ready via health checks.
 // This implies that the node has completed server startup, is heartbeating its
 // liveness record, and can serve SQL clients.
+// FIXME(srosenberg): This function is a bit of a misnomer. It doesn't actually ensure that SQL is ready to serve, only
```
Comment (srosenberg) [inline pkg/cmd/roachtest/roachtestutil/utils.go:185]: @andrewbaptist Just a heads-up since I believe this helper is used only by the tests you authored. While the Admin endpoint may be up, it doesn't guarantee that SQL is ready. The current implementation may be "ok" for these tests, but it's more pronounced in shared-process, multi-tenant configurations.

**Comment by srosenberg** [comment]
`SELECT_PROBABILITY=0.6`

- [GCE](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/18346244?buildTab=log&logFilter=debug&focusLine=6&logView=linear)
- [AWS](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyAwsBazel/18346245?buildTab=log&logFilter=debug&focusLine=6&logView=linear)

File: pkg/cmd/roachtest/roachtestutil/utils.go (hunk 1 above)
Comment (srosenberg) [reply pkg/cmd/roachtest/roachtestutil/utils.go:185]: Less of an issue now after the last iteration, which unconditionally calls `WaitForSQLReady`, for every started db node.

**Comment by srosenberg** [comment]
> `SELECT_PROBABILITY=0.6`
> 
> * [GCE](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/18346244?buildTab=log&logFilter=debug&focusLine=6&logView=linear)
> * [AWS](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyAwsBazel/18346245?buildTab=log&logFilter=debug&focusLine=6&logView=linear)

`decommission/drains` failed, which made me reconsider the initial approach of tying `WaitForSQLReady` to `WaitForReplication`. (Even in that case, it only does it for `n1`.) Now, each started db node has to pass `WaitForSQLReady`, regardless of whether `WaitForReplication` is enabled. In light of that, let's try take two,

`SELECT_PROBABILITY=0.8`

- [GCE](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/18352766?buildTab=log&logFilter=debug&focusLine=6&logView=linear)
- [AWS](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyAwsBazel/18352767?buildTab=log&logFilter=debug&focusLine=6&logView=linear)

File: pkg/cmd/roachtest/cluster.go [hunk 2]
```diff
@@ -2199,12 +2199,30 @@ func (c *clusterImpl) StartE(
 			return err
 		}
 	}
+	nodes := selectedNodesOrDefault(opts, c.CRDBNodes())
+	// N.B. If `SkipInit` is set, we don't wait for SQL since node(s) may not join the cluster in any definite time.
+	if !startOpts.RoachprodOpts.SkipInit {
+		// Wait for SQL to be ready on all nodes, for 'system' tenant, only.
```
Comment (DarrylWong) [inline pkg/cmd/roachtest/cluster.go:2205]: Should something similar be added for the virtual cluster start counterpart: `StartServiceForVirtualClusterE`?

**Review by DarrylWong — APPROVED** [review]
LGTM!

File: pkg/cmd/roachtest/cluster.go (hunk 2 above)
Comment (DarrylWong) [reply pkg/cmd/roachtest/cluster.go:2205]: Ah, I guess it's not needed because we're just mainly waiting for the cache to be ready which is at the system level?

File: pkg/cmd/roachtest/cluster.go [hunk 3]
```diff
@@ -2199,12 +2199,30 @@ func (c *clusterImpl) StartE(
...
+		for _, n := range nodes {
+			conn, err := c.ConnE(ctx, l, nodes[0], option.VirtualClusterName("system"))
```
[the remark this answers is not in the document]
Comment (srosenberg) [reply pkg/cmd/roachtest/cluster.go:2207]: Thanks, I'll update.

File: pkg/cmd/roachtest/cluster.go (hunk 2 above)
Comment (srosenberg) [reply pkg/cmd/roachtest/cluster.go:2205]: Technically, yes, we do need to wait for shared-process tenants. However, there could be any number of them, e.g.,

```
I241212 11:19:11.321291 53045 sql/syntheticprivilegecache/cache.go:198 â‹® [T3,Vmixed-version-tenant-mbqzz,n3] 145  warmed privileges for virtual tables in 10.007996435s
```

I thought it's probably best to tackle them in the mixedversion framework, since the above code already feels heavy wrt additional waiting. What do you think?

Comment (DarrylWong) [reply pkg/cmd/roachtest/cluster.go:2205]: >However, there could be any number of them, e.g.

But don't you just need to wait for the tenant you are starting? Which it should already know from `startOpts.RoachprodOpts.VirtualClusterName`?

>since the above code already feels heavy wrt additional waiting

Yeah I was thinking the same thing, especially since the first SQL check is redundant if `WaitForReplicationFactor > 0` since `WaitForReplication` is also checking if SQL is ready. No arguments against doing it in the mixed version framework here.

Comment (srosenberg) [reply pkg/cmd/roachtest/cluster.go:2205]: > But don't you just need to wait for the tenant you are starting?

Technically, yes. Although, in the case of shared-process tenants, they are _automatically_ restarted by system. The case of shared-process is already handled in the mixedversion framework, via `waitForSharedProcess`. The case of separate-process is also _technically_ handled albeit indirectly. Inside `SyncedCluster.Start`, after starting a _separate_ process, `createAdminUserForSecureCluster` essentially ensures SQL is initialized upon return.

Having said that, mostly as a precaution, I repurposed `waitForSharedProcess` as `waitForTenantProcess` which is now used for each deployment type, other than system.

File: pkg/cmd/roachtest/cluster.go [hunk 4]
```diff
@@ -2199,12 +2199,30 @@ func (c *clusterImpl) StartE(
...
 
 	if startOpts.WaitForReplicationFactor > 0 {
 		l.Printf("WaitForReplicationFactor: waiting for replication factor of at least %d", startOpts.WaitForReplicationFactor)
-		nodes := selectedNodesOrDefault(opts, c.All())
-
-		conn, err := c.ConnE(ctx, l, nodes[0])
+		// N.B. We must explicitly pass the virtual cluster name to `ConnE`, otherwise the default may turn out to be a
+		// secondary tenant, in which case we would only check the tenant's key range, not the whole system's.
+		// See "Unhidden Bug" in https://github.com/cockroachdb/cockroach/issues/137988
+		conn, err := c.ConnE(ctx, l, nodes[0], option.VirtualClusterName("system"))
```
[the remark this answers is not in the document]
Comment (srosenberg) [reply pkg/cmd/roachtest/cluster.go]: Done.

**Comment by srosenberg** [comment]
Final smoke tests,

- [GCE](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/18431348?buildTab=log&logFilter=debug&focusLine=6&logView=linear)
- [AWS](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyAwsBazel/18431349?buildTab=log&logFilter=debug&focusLine=6&logView=linear)

**Comment by msbutler** [comment]
@srosenberg looks like the auto backport prs never generated. are you still planning to open backports of this pr?

**Comment by srosenberg** [comment]
> @srosenberg looks like the auto backport prs never generated. are you still planning to open backports of this pr? Also, looks like it was a wild ride debugging this. Thank you!

Yep. It's been in a holding position to see if it _really_ resolved the issue. I also want to address the side issue, namely exposing an opt-out option, although that's orthogonal. I'll take a closer look tomorrow, at the recent failures, if any, and get the backports, if everything looks good.
