### PR TITLE
cli: add --advertise-http-addr flag

### LINKED ISSUE #79164: Proxying to specific nodes in DB Console errors out for Dedicated clusters
**Describe the problem**

Reported by @dhartunian Proxying to specific nodes from DB Console does not work at all for 21.2 clusters when connecting to a cluster from CockroachDB Dedicated

Jira issue: CRDB-14614

### PR DESCRIPTION
**Pull request by dhartunian**
Previously, the HTTP Advertise Address was derived from either the OS
hostname, the SQL advertise address, or the `--http-addr` flag.

This commit adds an explicit flag for setting this field in order to
provide control over it for scenarios where node to node proxying
requires hostnames different from the ones the HTTP server is listening
on.

Resolves https://github.com/cockroachdb/cockroach/issues/79164

Release note (cli change): A new flag `--advertise-http-addr` is
available for setting the HTTP advertise address explicitly. Previously,
this address was derived from the OS hostname, the `--advertise-addr`
and the `--http-addr` flags in that order. The new logic will override
the HTTP advertise host with the host from `--advertise-addr` first if
set, and then the host from `--http-addr`. The port will *never* inherit
from `--advertise-host` and only from `--http-addr`, which is 8080 by
default. The HTTP advertise address is used to report the DB Console
address to access on a cluster and by nodes to proxy HTTP connections as
described in https://github.com/cockroachdb/cockroach/issues/73285. It may be necessary to set this flag in order for
that feature to work correctly in some deployments.

### CODE REVIEW

File: pkg/cli/flags.go [hunk 1]
```diff
@@ -1215,6 +1221,7 @@ func extraServerFlagInit(cmd *cobra.Command) error {
 		serverCfg.DisableTLSForHTTP = true
 	}
 	serverCfg.HTTPAddr = net.JoinHostPort(serverHTTPAddr, serverHTTPPort)
+	serverCfg.HTTPAdvertiseAddr = net.JoinHostPort(serverHTTPAdvertiseAddr, serverHTTPAdvertisePort)
```
Comment (knz) [inline pkg/cli/flags.go:1224]: maybe before this line, for symmetry with the above:
```go
	if serverHTTPAdvertiseAddr == "" {
		if advSpecified {
			serverHTTPAdvertiseAddr = serverAdvertiseAddr
		} else {
			serverHTTPAdvertiseAddr = serverHTTPAddr
		}
	}
	if serverSQLAdvertisePort == "" {
		if advSpecified {
			serverHTTPAdvertisePort = serverAdvertisePort
		} else {
			serverHTTPAdvertisePort = serverHTTPPort
		}
	}
```

wdyt?

**Review by knz — COMMENTED** [review]
great thanks. I think we have a unit test framework for this around this package.

File: pkg/cli/flags.go (hunk 1 above)
Comment (dhartunian) [reply pkg/cli/flags.go:1239]: SGTM. Done.

There's a bit of duplication of this in `addr_validation.go/ValidateAddrs`, or is that function doing something different?

Comment (knz) [reply pkg/cli/flags.go:1239]: Last time I tried to unify the two parts together, I was getting strange failures in various unit tests + acceptance tests. I did not investigate further at the time.

**Review by knz — APPROVED** [review]

File: pkg/cli/flags.go (hunk 1 above)
Comment (dhartunian) [reply pkg/cli/flags.go:1239]: Hmm upon a second look I'm not sure about this.

The code above applies precedence in this order: CLI flag -> advertiseAddr -> httpAddr, but the `ValidateAddrs` function lets the httpAddr (listen address) take precedence over advertiseAddr. So this would create situations where if someone had both addresses set, the result would be different.

I added a more detailed test that also exercises the `ValidateAddrs` function which confirms this. I assume we don't want the same flags causing modified behavior after an upgrade.

**Review by abarganier — APPROVED** [review]
This was easy to grasp - thanks for the changes! :lgtm: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/79966#-:-N06tt-Q3aDZ-CblkJRo:bjj994k)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @knz)

**Comment by dhartunian** [comment]
@abarganier ran through another iteration and made some tweaks, PTAL

**Review by abarganier — APPROVED** [review]
Ah, nice catch there with the http port! Updates :lgtm: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/79966#-:-N0WRTdk8blHk3DFHk-i:b-turhed)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @knz)

**Comment by dhartunian** [comment]
@knz I'd appreciate a quick look at the modified inheritance logic for this flag as described in the commit msg. We already did mixed host/port inheritance in other parts of the code so it felt okay to introduce here.

**Review by knz — COMMENTED** [review]
Great unit tests. I'd like to double check the final value of HTTPAddr in the unit test though.

> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/79966#-:-N0eUYUf3ekjLFJRNBf5:bnsbnj)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @dhartunian and @knz)

___
*[`pkg/cli/flags_test.go` line 1028 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/79966#-N0eUCeoASnjraF7LuuS:-N0eUCeoASnjraF7LuuT:b-gheiei) ([raw file](https://github.com/cockroachdb/cockroach/blob/ef01ac261ba4bc412c45be9824452895c166c028/pkg/cli/flags_test.go#L1028)):*
> ```Go
> 	for i, tc := range []struct {
> 		args                        []string
> 		expected                    string
> ```

could you extend the test as in TestServerConnSettings to also check the value of the field serverCfg.HTTPAddr?
___
*[`pkg/cli/flags_test.go` line 1044 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/79966#-N0eUM5I-uZ3cuEA_ats:-N0eUM5I-uZ3cuEA_att:bza064t) ([raw file](https://github.com/cockroachdb/cockroach/blob/ef01ac261ba4bc412c45be9824452895c166c028/pkg/cli/flags_test.go#L1044)):*
> ```Go
> 			"adv.example.com:1234",
> 			"adv.example.com:1234", true},
> 		{[]string{"start", "--advertise-addr", "example.com"},
> ```

in particular, we need to verify that if `--listen-addr` is not specified, the config + validation does not inject the advertised address into HTTPAddr, overriding the default.

**Review by dhartunian — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/79966)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @knz)

___
*[`pkg/cli/flags_test.go` line 1028 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/79966#-N0eUCeoASnjraF7LuuS:-N14NJt1CjjeCzypsN3M:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/ef01ac261ba4bc412c45be9824452895c166c028/pkg/cli/flags_test.go#L1028)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

could you extend the test as in TestServerConnSettings to also check the value of the field serverCfg.HTTPAddr?
</blockquote></details>

Done.
___
*[`pkg/cli/flags_test.go` line 1044 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/79966#-N0eUM5I-uZ3cuEA_ats:-N14NMEN6ikWgnzb3ea3:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/ef01ac261ba4bc412c45be9824452895c166c028/pkg/cli/flags_test.go#L1044)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

in particular, we need to verify that if `--listen-addr` is not specified, the config + validation does not inject the advertised address into HTTPAddr, overriding the default.
</blockquote></details>

Done.

**Review by knz — APPROVED** [review]
> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/79966)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @dhartunian)

**Comment by dhartunian** [comment]
TFTRs

bors r=knz,abarganier
