### PR TITLE
sql: prepare support for INSERT, UPDATE, DELETE

### LINKED ISSUE #3819: pgwire panics when opening a connection from jdbc.postgresql
So I am trying to get clojure (for jepsen, see #4036 ) to talk to cockroach via jdbc and `--insecure`. 
For this I use the standard Java org.postgresql JDBC driver (provided by postgres) version 9.4-1204-jdbc42 and clojure/java.jdbc 0.4.1 (JDK 8)

My JDBC object is instantiated with the following config:
```
(fn conn-spec [_]
                            {:classname   "org.postgresql.Driver"
                             :subprotocol "postgresql"
                             :subname     (str "//n1:15432/system")
                             :user        "psql"
                             :password    "dummy"})
```

Upon starting the client, the (Java) client fails with:
```
WARN  jepsen.cockroach - Lost connection {:classname org.postgresql.Driver, :subprotocol postgresql, :subname //n1:15432/system, :user psql, :password dummy, :connection #object[org.postgresql
.jdbc42.Jdbc42Connection 0x28ba4cca org.postgresql.jdbc42.Jdbc42Connection@28ba4cca]} , reconnecting
```

(then the client gives up)
After this happens, I observe the cockroach server has died with the following trace:

```
I0113 23:16:18.354134 17749 server/node.go:389  connecting to gossip network to verify cluster ID...
I0113 23:16:18.354150 17749 server/node.go:406  node connected via gossip and verified as part of cluster "ddd32b9f-4d8e-42c9-b087-2ce276a97cc7"
I0113 23:16:18.354224 17749 server/node.go:258  Started node with [[ssd]=data] engine(s) and attributes []
I0113 23:16:18.354417 17749 server/server.go:262  starting http server at ip-172-31-63-242:26257
I0113 23:16:18.354528 17749 sql/pgwire/server.go:76  starting postgres server at [::]:15432
W0113 23:16:20.355864 17749 storage/store.go:639  error gossiping system config: range 0: replica <nil> not leader; leader is <nil>
I0113 23:16:28.355472 17749 server/status/runtime.go:137  runtime stats: 60 goroutines, 3.94MiB active, 0.00cgo/sec, 0.00/0.00 %(u/s)time, 0.00 %gc (0x)
W0113 23:16:31.376006 17749 sql/pgwire/v3.go:147  unrecognized configuration parameter "client_encoding"
W0113 23:16:31.376175 17749 sql/pgwire/v3.go:147  unrecognized configuration parameter "DateStyle"
W0113 23:16:31.376311 17749 sql/pgwire/v3.go:147  unrecognized configuration parameter "TimeZone"
W0113 23:16:31.376328 17749 sql/pgwire/v3.go:147  unrecognized configuration parameter "extra_float_digits"
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x9c pc=0xb69cfc]

goroutine 127 [running]:
github.com/cockroachdb/cockroach/sql.(*planner).Show(0xc820480500, 0xc8204cd340, 0x0, 0x0, 0x2)
        /go/src/github.com/cockroachdb/cockroach/sql/show.go:47 +0xb9c
github.com/cockroachdb/cockroach/sql.(*planner).makePlan(0xc820480500, 0x7f93d550d978, 0xc8204cd340, 0x0, 0x0, 0x0, 0x0)
        /go/src/github.com/cockroachdb/cockroach/sql/plan.go:130 +0x63e
github.com/cockroachdb/cockroach/sql.(*Executor).StatementResult(0xc8201d0210, 0xc82034f009, 0x4, 0x7f93d550d978, 0xc8204cd340, 0xc8204e65a0, 0x0, 0x0, 0x0, 0x0)
        /go/src/github.com/cockroachdb/cockroach/sql/executor.go:152 +0x275
github.com/cockroachdb/cockroach/sql/pgwire.(*v3Conn).handleParse(0xc82005c000, 0xc82005c038, 0x0, 0x0)
        /go/src/github.com/cockroachdb/cockroach/sql/pgwire/v3.go:321 +0xc31
github.com/cockroachdb/cockroach/sql/pgwire.(*v3Conn).serve(0xc82005c000, 0x0, 0x0, 0x0)
        /go/src/github.com/cockroachdb/cockroach/sql/pgwire/v3.go:223 +0xb62
github.com/cockroachdb/cockroach/sql/pgwire.(*Server).serveConn(0xc8201c3110, 0x7f93d550b228, 0xc8200f41b8, 0x0, 0x0)
        /go/src/github.com/cockroachdb/cockroach/sql/pgwire/server.go:199 +0x9b5
github.com/cockroachdb/cockroach/sql/pgwire.(*Server).serve.func1(0xc8201c3110, 0x7f93d550b228, 0xc8200f41b8)
        /go/src/github.com/cockroachdb/cockroach/sql/pgwire/server.go:108 +0x90
created by github.com/cockroachdb/cockroach/sql/pgwire.(*Server).serve
        /go/src/github.com/cockroachdb/cockroach/sql/pgwire/server.go:113 +0x20a
```

Not sure where to go from here. Is there a way to ask the server to emit the sql queries into its log / stderr?

### PR DESCRIPTION
**Pull request by madelynnblue**
Make sure prepare statements are run in a transaction.

Use a new boolean flag on the planner to indicate prepare. Statement
implementations will gain knowledge of work to omit during prepare. An
alternative implementation would split up the prepare and exec portions of
the work. However, this would require passing around significant amounts
of state and I think the best implementation is the one here.

Keep a whitelist of statement types that support preparation instead of
attempting to exec them during prepare.

This also functions as a refactor for prepare statements in
general. Previously, we called parser.InferArgs, which walked the statement
and ran TypeCheck on all expressions. It turns out this is not needed,
since Select (and others) do this themselves. Thus, we can invoke those
worker functions directly but teach them about prepareOnly so they can
omit work once the val args have been populated and the type checks done.

Fixes #3819

[Review on Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/4037)

### CODE REVIEW

File: sql/pgwire_test.go [hunk 1]
```diff
@@ -316,6 +313,103 @@ func TestPGPrepared(t *testing.T) {
...
+		tests []preparedTest
+	}{
+		{
+			"CREATE DATABASE d",
+			nil,
+		},
+		{
+			"CREATE TABLE d.t (i INT, s STRING, d INT)",
+			nil,
+		},
```
Comment (petermattis) [inline sql/pgwire_test.go]: Sort of strange that these are test cases. They are really part of test setup. I think it would be cleaner to pull them out and actually perform them as separate setup steps. You can do something like:

```
  setup := `CREATE DATABASE d; CREATE TABLE d.t (i INT, s STRING, d INT);`
  if err := db.Exec(setup); err != nil {
    t.Fatal(err)
  }
```

File: sql/pgwire_test.go [hunk 2]
```diff
@@ -316,6 +313,103 @@ func TestPGPrepared(t *testing.T) {
...
+			}
+		}
+		if err := stmt.Close(); err != nil {
+			t.Fatal(err)
+		}
+	}
+
+	testFailures := map[string]string{
+		"CREATE TABLE $1 (id INT)":  "pq: syntax error at or near \"1\"\nCREATE TABLE $1 (id INT)\n             ^\n",
+		"DROP TABLE t":              "pq: prepare statement not supported: *parser.DropTable",
```
Comment (petermattis) [inline sql/pgwire_test.go]: Can we change this error so that it references `DROP TABLE` instead of `*parser.DropTable`? We should try to avoid leaking implementation details like the names of our internal structures into the end-user error messages.

File: sql/plan.go [hunk 3]
```diff
@@ -152,6 +156,25 @@ func (p *planner) makePlan(stmt parser.Statement, autoCommit bool) (planNode, *r
...
+	case *parser.Delete:
+		return p.Delete(n)
+	case *parser.Insert:
+		return p.Insert(n, false)
+	case *parser.Select:
+		return p.Select(n)
+	case *parser.Update:
+		return p.Update(n)
+	default:
+		return nil, roachpb.NewUErrorf("prepare statement not supported: %T", stmt)
```
Comment (petermattis) [inline sql/plan.go]: Perhaps `stmt.PGTag()` (whenever that PR goes in).

File: sql/update.go [hunk 4]
```diff
@@ -132,6 +132,55 @@ func (p *planner) Update(n *parser.Update) (planNode, *roachpb.Error) {
...
+				}
+			} else {
+				if err := f(expr.Expr); err != nil {
+					return nil, err
+				}
+			}
+		}
+
+		return nil, nil
+	}
```
Comment (petermattis) [inline sql/update.go]: Some of our methods are becoming gigantic!

**Comment by mjibson** [comment]
Review status: 0 of 12 files reviewed at latest revision, 4 unresolved discussions.

---

*[sql/pgwire_test.go, line 330 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4037#-K9DrXjZBwSknQiM1aVI-r1-330:-K9EVoXTToVnqbggxLNX:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/998f56bb70274dcb0f765b646b1c97eac65f98f2/sql/pgwire_test.go#L330)):*
Done.

---

*[sql/pgwire_test.go, line 396 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4037#-K9DrXjZBwSknQiM1aVI-r1-396:-K9EUwCZUNtQZonMyPWJ:-625985944) ([raw file](https://github.com/cockroachdb/cockroach/blob/998f56bb70274dcb0f765b646b1c97eac65f98f2/sql/pgwire_test.go#L396)):*
Adding a TODO for this, discussed below.

---

*[sql/plan.go, line 171 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4037#-K9DrXjZBwSknQiM1aVJ-r1-171:-K9EVGvDuI9aur5g6Qqj:-1018314897) ([raw file](https://github.com/cockroachdb/cockroach/blob/998f56bb70274dcb0f765b646b1c97eac65f98f2/sql/plan.go#L171)):*
Adding a TODO for that.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4037)*

**Comment by petermattis** [comment]
LGTM

---

Review status: 0 of 12 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4037#-:-K9FGwMSaeG6pAowVPfV:676834233)*
