### PR TITLE
cdc: do not run fine grained checkpointing test on azure

### LINKED ISSUE #146862: roachtest: cdc/fine-grained-checkpointing failed
roachtest.cdc/fine-grained-checkpointing [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyAzureBazel/19705291?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyAzureBazel/19705291?buildTab=artifacts#/cdc/fine-grained-checkpointing) on master @ [1a847b18290d439c62ff739ebdae00c851d5442e](https://github.com/cockroachdb/cockroach/commits/1a847b18290d439c62ff739ebdae00c851d5442e):

```
(test_runner.go:1400).runTest: test timed out (30m0s)
test artifacts and logs in: /artifacts/cdc/fine-grained-checkpointing/run_1
```

Parameters:
 - <code>arch=amd64</code>
 - <code>cloud=azure</code>
 - <code>coverageBuild=false</code>
 - <code>cpu=4</code>
 - <code>encrypted=false</code>
 - <code>runtimeAssertionsBuild=false</code>
 - <code>ssd=0</code>
<details><summary>Help</summary>
<p>

See: [roachtest README](https://github.com/cockroachdb/cockroach/blob/master/pkg/cmd/roachtest/README.md)

See: [How To Investigate \(internal\)](https://cockroachlabs.atlassian.net/l/c/SSSBr8c7)

_Grafana is not yet available for azure clusters_</p>
</details>
/cc @cockroachdb/cdc
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*cdc/fine-grained-checkpointing.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/bazci/githubpost/issues)

</sub>

### PR DESCRIPTION
**Pull request by aerfrei**
We were seeing a network issue where the changefeed node was unable to connect to the webhook server running on the coordinator node on teamcity for azure only. We make this test, like the initial scan rolling restart test, only run on GCE

Fixes: #146862
Epic: none
Release note: None

### CODE REVIEW

File: pkg/cmd/roachtest/tests/cdc.go [hunk 1]
```diff
@@ -1696,7 +1698,7 @@ func registerCDC(r registry.Registry) {
 		Owner:            registry.OwnerCDC,
 		Benchmark:        true,
 		Cluster:          r.MakeClusterSpec(4),
-		CompatibleClouds: registry.AllClouds,
+		CompatibleClouds: registry.OnlyGCE,
```
Comment (andyyang890) [inline pkg/cmd/roachtest/tests/cdc.go:1701]: if you're confident it works on AWS, maybe we should make it `registry.AllExceptAzure`?

**Review by andyyang890 — APPROVED** [review]

File: pkg/cmd/roachtest/tests/cdc.go (hunk 1 above)
Comment (aerfrei) [reply pkg/cmd/roachtest/tests/cdc.go]: I switched this. Failures have only come in for Azure, so I'd think that means it has been succeeding on AWS. Thanks

**Comment by aerfrei** [comment]
bors r=andyyang890
