### PR TITLE
opt: generate unconstrained scans for pseudo-partial indexes

### LINKED ISSUE #52702: opt: allow usage of partial index predicate that always evaluates to true
To reproduce in a logictest:

```
statement ok
SET experimental_partial_indexes = true;
SET experimental_enable_enums = true;

statement ok
CREATE TABLE t (s STRING, INDEX i (s) WHERE 1 = 1)

statement ok
SELECT * FROM t@i WHERE 1 = 1
```

Falsy predicates seem to work fine.

### PR DESCRIPTION
**Pull request by mgartner**
A "pseudo-partial index" is a partial index with a predicate that always
evaluates to true. Such an index behaves the same as a non-partial
secondary index. It is guaranteed to have an index entry for every row
in the table.

Previously, forcing the optimizer to use a pseudo-partial index in a
query with a truthy filter would result in an error that incorrectly
claimed that not all rows in the table exist in the index. The root
cause was that such a query has no `Select` expression and partial index
scans were only generated in rules that match `(Select (Scan))`.

This commit changes the behavior of the GenerateIndexScans
transformation rule so that it generates scans over pseudo-partial
indexes. This allows forcing pseudo-partial indexes for any query.

Fixes #52702

Release note: None

### CODE REVIEW

File: pkg/sql/opt/partialidx/implicator.go [hunk 1]
```diff
@@ -155,10 +155,9 @@ func (im *Implicator) Init(f *norm.Factory, md *opt.Metadata, evalCtx *tree.Eval
 func (im *Implicator) FiltersImplyPredicate(
 	filters memo.FiltersExpr, pred memo.FiltersExpr,
 ) (remainingFilters memo.FiltersExpr, ok bool) {
-	// An empty FiltersExpr is equivalent to True, which is only implied by
-	// True.
-	if len(pred) == 0 {
-		return filters, len(filters) == 0
+	// True is only implied by true.
+	if pred.IsTrue() {
+		return filters, filters.IsTrue()
```
Comment (mgartner) [inline pkg/sql/opt/partialidx/implicator.go:160]: This was not required for the fix - just figured we should use `IsTrue` here too.

**Review by RaduBerinde — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/52712#-:-MEYqgbP3c3xHgz30k4G:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained

**Comment by mgartner** [comment]
bors r=RaduBerinde
