### PR TITLE
sql: allow foreign key to reference crdb_region column in REGIONAL BY ROW

### LINKED ISSUE #74244: opt: permit foreign key constraint on full primary index of PARTITION ALL BY tables
This issue is similar to the "this shouldn't be needed" part of https://github.com/cockroachdb/cockroach/issues/69617, except smaller in scope.

Currently, a foreign key constraint cannot reference the primary index of a table in cases (e.g. a `PARTITION ALL BY` table) where this primary index differs from the primary key. For example:

```sql
CREATE DATABASE db PRIMARY REGION "us-east1" REGIONS "us-west1", "europe-west1";
USE db;

CREATE TABLE users (
    id         UUID   PRIMARY KEY DEFAULT gen_random_uuid(),
    username   STRING NOT NULL
) LOCALITY REGIONAL BY ROW;

CREATE TABLE user_settings (
    id      UUID   PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID   NOT NULL,
    value   STRING NOT NULL,
    FOREIGN KEY (user_id, crdb_region) REFERENCES users (id, crdb_region) ON DELETE CASCADE ON UPDATE CASCADE
) LOCALITY REGIONAL BY ROW;

ERROR: there is no unique constraint matching given keys for referenced table users
```

This is unfortunate, as we'd like to be able to use foreign keys to enforce collocation across parent-child relationships in REGIONAL BY ROW tables. To get around this, a redundant unique constraint (e.g. `UNIQUE (crdb_region, id)`) must be added, which incurs a significant runtime cost:

```sql
CREATE DATABASE db2 PRIMARY REGION "us-east1" REGIONS "us-west1", "europe-west1";
USE db2;

CREATE TABLE users (
    id         UUID   PRIMARY KEY DEFAULT gen_random_uuid(),
    username   STRING NOT NULL,
    UNIQUE (crdb_region, id)
) LOCALITY REGIONAL BY ROW;

CREATE TABLE user_settings (
    id      UUID   PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID   NOT NULL,
    value   STRING NOT NULL,
    FOREIGN KEY (user_id, crdb_region) REFERENCES users (id, crdb_region) ON DELETE CASCADE ON UPDATE CASCADE
) LOCALITY REGIONAL BY ROW;

# collocation enforced on insert

> INSERT INTO users (crdb_region, id, username) VALUES ('us-east1', DEFAULT, 'artem') RETURNING id;
                   id
----------------------------------------
  5ebfedee-0dcf-41e6-a315-5fa0b51b9882

> INSERT INTO user_settings (crdb_region, id, user_id, value) VALUES ('us-west1', DEFAULT, '5ebfedee-0dcf-41e6-a315-5fa0b51b9882', 'this should work') RETURNING id;
ERROR: insert on table "user_settings" violates foreign key constraint "user_settings_user_id_crdb_region_fkey"
SQLSTATE: 23503
DETAIL: Key (user_id, crdb_region)=('5ebfedee-0dcf-41e6-a315-5fa0b51b9882', 'us-west1') is not present in table "users".
CONSTRAINT: user_settings_user_id_crdb_region_fkey

> INSERT INTO user_settings (crdb_region, id, user_id, value) VALUES ('us-east1', DEFAULT, '5ebfedee-0dcf-41e6-a315-5fa0b51b9882', 'this should work') RETURNING id;
                   id
----------------------------------------
  f1867e8b-3414-425c-b3f8-d7e237f848e6

> SELECT crdb_region, * FROM users;
  crdb_region |                  id                  | username
--------------+--------------------------------------+-----------
  us-east1    | 5ebfedee-0dcf-41e6-a315-5fa0b51b9882 | artem

> SELECT crdb_region, * FROM user_settings;
  crdb_region |                  id                  |               user_id                |      value
--------------+--------------------------------------+--------------------------------------+-------------------
  us-east1    | f1867e8b-3414-425c-b3f8-d7e237f848e6 | 5ebfedee-0dcf-41e6-a315-5fa0b51b9882 | this should work

# collocation enforced on update

> UPDATE user_settings SET crdb_region = 'us-west1' WHERE id = 'f1867e8b-3414-425c-b3f8-d7e237f848e6';
ERROR: update on table "user_settings" violates foreign key constraint "user_settings_user_id_crdb_region_fkey"
SQLSTATE: 23503
DETAIL: Key (user_id, crdb_region)=('5ebfedee-0dcf-41e6-a315-5fa0b51b9882', 'us-west1') is not present in table "users".
CONSTRAINT: user_settings_user_id_crdb_region_fkey

> SELECT crdb_region, * FROM user_settings;
  crdb_region |                  id                  |               user_id                |      value
--------------+--------------------------------------+--------------------------------------+-------------------
  us-east1    | f1867e8b-3414-425c-b3f8-d7e237f848e6 | 5ebfedee-0dcf-41e6-a315-5fa0b51b9882 | this should work

> UPDATE users SET crdb_region = 'us-west1' WHERE id = '5ebfedee-0dcf-41e6-a315-5fa0b51b9882';
UPDATE 1

> SELECT crdb_region, * FROM users;
  crdb_region |                  id                  | username
--------------+--------------------------------------+-----------
  us-west1    | 5ebfedee-0dcf-41e6-a315-5fa0b51b9882 | artem

> SELECT crdb_region, * FROM user_settings;
  crdb_region |                  id                  |               user_id                |      value
--------------+--------------------------------------+--------------------------------------+-------------------
  us-west1    | f1867e8b-3414-425c-b3f8-d7e237f848e6 | 5ebfedee-0dcf-41e6-a315-5fa0b51b9882 | this should work
```

I've tracked this down to logic in `tabledesc.FindFKReferencedUniqueConstraint`, but I don't understand things in that area enough to make a change.

### PR DESCRIPTION
**Pull request by rytaft**
This commit loosens the restrictions on foreign key references to allow
referencing `crdb_region` and other implicit partitioning columns used by
`PARTITION ALL BY` tables. There is no technical reason why such references
should be disallowed, so this commit simply removes the restriction.

Fixes #74244

Release note (sql change): Foreign keys can now reference the `crdb_region`
column in `REGIONAL BY ROW` tables even if `crdb_region` is not explicitly part
of a `UNIQUE` constraint. This is possible since `crdb_region` is implicitly
included in every index on `REGIONAL BY ROW` tables as the partitioning key.
(This applies to whichever column is used as the partitioning column, in
case a different name is used via `REGIONAL BY ROW AS`.)

### CODE REVIEW

**Review by rytaft — COMMENTED** [review]
cc @andy-kimball 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/83375#-:-N5PzZC-739EEiusjpV6:bbj0wwo)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @nvanbenschoten and @otan)

**Review by andy-kimball — COMMENTED** [review]
Great to see this! Will this be back-portable it to 22.1?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/83375#-:-N5Tjm929oefbSXhyrbP:bvr3hq3)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @nvanbenschoten and @otan)

**Comment by rytaft** [comment]
I think that should be possible

**Review by otan — APPROVED** [review]

**Review by postamar — CHANGES_REQUESTED** [review]
Just one small request on my part, otherwise looks good to me.

File: pkg/sql/catalog/descpb/index.go [hunk 1]
```diff
@@ -81,13 +81,29 @@ func (desc *IndexDescriptor) explicitColumnIDsWithoutShardColumn() ColumnIDs {
...
+
 // IsValidReferencedUniqueConstraint  is part of the UniqueConstraint interface.
 // It returns whether the index can serve as a referenced index for a foreign
 // key constraint with the provided set of referencedColumnIDs.
 func (desc *IndexDescriptor) IsValidReferencedUniqueConstraint(referencedColIDs ColumnIDs) bool {
 	return desc.Unique &&
 		!desc.IsPartial() &&
-		desc.explicitColumnIDsWithoutShardColumn().PermutationOf(referencedColIDs)
+		(desc.explicitColumnIDsWithoutShardColumn().PermutationOf(referencedColIDs) ||
+			desc.keyColumnIDsWithoutShardColumn().PermutationOf(referencedColIDs))
```
Comment (postamar) [inline pkg/sql/catalog/descpb/index.go:106]: There seems to be some redundancy here, in that the columns IDs returned by `keyColumnIDsWithoutShardColumn` always form a superset of `explicitColumnIDsWithoutShardColumn`. It seems that what we really want to check is that the referenced column IDs minus the shard and implicit columns equals the key column IDs. This makes referencing any implicit columns possible but not required. Of course right now there's only at most one implicit column but this change seems worth making if only to clarify our intentions in the code.

I'm not sure why the shard column is treated specially but perhaps I'm unaware of something. I don't see why it should be special but I don't have a strong opinion on this matter.

**Review by mgartner — APPROVED** [review]
:lgtm: 

> Reviewed 5 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/83375#-:-N5jhXty04riDCtdmq9R:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @nvanbenschoten and @postamar)

___
*[`pkg/sql/catalog/descpb/index.go` line 106 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/83375#-N5PympZ1TKJddCEkPEQ-r1-106:-N5jgzqt1azkFdkJaV3d:b-f3sa1h) ([raw file](https://github.com/cockroachdb/cockroach/blob/7602c77c64b54f416f4e5677584aee3b81944d2e/pkg/sql/catalog/descpb/index.go#L106)):*
> I'm not sure why the shard column is treated specially but perhaps I'm unaware of something. I don't see why it should be special but I don't have a strong opinion on this matter.

The shard column is computed, so I believe it's not allowed to be an FK because an update to the referenced table can't cascade to a computed column.
___
*[`pkg/ccl/logictestccl/testdata/logic_test/regional_by_row_query_behavior` line 2955 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/83375#-N5jgZPp6S4_Y3z7QRPz:-N5jgZPp6S4_Y3z7QRQ-:b-k5ibo4) ([raw file](https://github.com/cockroachdb/cockroach/blob/7602c77c64b54f416f4e5677584aee3b81944d2e/pkg/ccl/logictestccl/testdata/logic_test/regional_by_row_query_behavior#L2955)):*
> ```
> RESET vectorize
> 
> subtest foreign_keys
> ```

Might be good to add query plan tests for FK checks and cascades to make sure they are efficient.

**Comment by postamar** [comment]
> The shard column is computed, so I believe it's not allowed to be an FK because an update to the referenced table can't cascade to a computed column.

Makes sense. Thanks!

**Review by rytaft — COMMENTED** [review]
TFTRs!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/83375#-:-N6-eHd--zYRPboV-0wC:bz5mair)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @mgartner, @nvanbenschoten, and @postamar)

___
*[`pkg/sql/catalog/descpb/index.go` line 106 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/83375#-N5PympZ1TKJddCEkPEQ-r1-106:-N6-cGB6ATwiBfwMcvjU:b-t7vkfc) ([raw file](https://github.com/cockroachdb/cockroach/blob/7602c77c64b54f416f4e5677584aee3b81944d2e/pkg/sql/catalog/descpb/index.go#L106)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

> I'm not sure why the shard column is treated specially but perhaps I'm unaware of something. I don't see why it should be special but I don't have a strong opinion on this matter.

The shard column is computed, so I believe it's not allowed to be an FK because an update to the referenced table can't cascade to a computed column.
</blockquote></details>

I tried to remove some of the redundancy... let me know if you think this is better now.
___
*[`pkg/ccl/logictestccl/testdata/logic_test/regional_by_row_query_behavior` line 2955 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/83375#-N5jgZPp6S4_Y3z7QRPz:-N6-eFkx73ljVHFw_OjY:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/7602c77c64b54f416f4e5677584aee3b81944d2e/pkg/ccl/logictestccl/testdata/logic_test/regional_by_row_query_behavior#L2955)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

Might be good to add query plan tests for FK checks and cascades to make sure they are efficient.
</blockquote></details>

Done.

**Review by postamar — APPROVED** [review]

**Review by mgartner — APPROVED** [review]
:lgtm:

> Reviewed 1 of 7 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/83375#-:-N6DdKFX7KudUwXItIya:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @nvanbenschoten and @postamar)

**Review by rytaft — COMMENTED** [review]
Thanks!

bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/83375#-:-N6Df9GG94m2p-uj4sXj:b-voiyyw)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @nvanbenschoten and @postamar)
