### PR TITLE
storage: Use snapshots when verifying recomputations of a replica's stats in tests

### LINKED ISSUE #4740: circleci: failed tests (13559): TestStoreRangeMergeStats
The following test appears to have failed:

[#13559](https://circleci.com/gh/cockroachdb/cockroach/13559):

```
I160301 01:04:01.755283 kv/range_cache.go:189  adding descriptor: key=/Meta2/"b" desc=range_id:1 start_key:"" end_key:"b" replicas:<node_id:1 store_id:1 replica_id:1 > next_replica_id:2 
I160301 01:04:01.755907 kv/range_cache.go:128  lookup range descriptor: key="b"
I160301 01:04:01.756073 kv/range_cache.go:189  adding descriptor: key=/Meta2/Max desc=range_id:2 start_key:"b" end_key:"\377\377" replicas:<node_id:1 store_id:1 replica_id:1 > next_replica_id:2 
I160301 01:04:01.756981 storage/replica_command.go:467  auto-gc'ed 1f7929b3 (8 intents)
I160301 01:04:01.765979 storage/engine/rocksdb.go:137  closing in-memory rocksdb instance
--- FAIL: TestStoreRangeMergeStats (0.18s)
	client_merge_test.go:413: failed to verify range's stats after merge: expected range's stats to agree with recomputation: got
		{LastUpdateNanos:0 IntentAge:0 GCBytesAge:0 LiveBytes:41470 LiveCount:219 KeyBytes:16289 KeyCount:220 ValBytes:25370 ValCount:225 IntentBytes:0 IntentCount:0 SysBytes:596 SysCount:8}
		recomputed
		{LastUpdateNanos:0 IntentAge:0 GCBytesAge:0 LiveBytes:41470 LiveCount:219 KeyBytes:16289 KeyCount:220 ValBytes:25370 ValCount:225 IntentBytes:0 IntentCount:0 SysBytes:780 SysCount:10}
=== RUN   TestStoreStatsSplit
I160301 01:04:01.769263 raft/raft.go:459  [group 1] 1 became follower at term 5
I160301 01:04:01.769400 raft/raft.go:235  [group 1] newRaft 1 [peers: [1], term: 5, commit: 10, applied: 10, lastindex: 10, lastterm: 5]
I160301 01:04:01.769430 raft/raft.go:539  [group 1] 1 is starting a new election at term 5
I160301 01:04:01.769465 raft/raft.go:472  [group 1] 1 became candidate at term 6
I160301 01:04:01.769490 raft/raft.go:521  [group 1] 1 received vote from 1 at term 6
--
I160301 01:04:31.775792 stopper.go:273  draining; tasks left:
41     gossip/infostore.go:285
I160301 01:04:31.775823 stopper.go:273  draining; tasks left:
31     gossip/infostore.go:285
--- PASS: Example_rebalancing (0.12s)
FAIL
FAIL	github.com/cockroachdb/cockroach/storage	34.767s
=== RUN   TestBatchBasics
I160301 01:03:54.823706 storage/engine/rocksdb.go:137  closing in-memory rocksdb instance
--- PASS: TestBatchBasics (0.02s)
=== RUN   TestBatchGet
I160301 01:03:54.840908 storage/engine/rocksdb.go:137  closing in-memory rocksdb instance
--- PASS: TestBatchGet (0.01s)
=== RUN   TestBatchMerge
I160301 01:03:54.846221 storage/engine/rocksdb.go:137  closing in-memory rocksdb instance
--- PASS: TestBatchMerge (0.01s)
=== RUN   TestBatchProto

```
Please assign, take a look and update the issue accordingly.

### PR DESCRIPTION
**Pull request by nvb**
Fixes #4740.

The issue was that we had introduced a race condition by not using an
engine snapshot between getting a replica's stats and recomputing a
replica's stats. This issue was present in `TestStoreRangeSplitStats`
and `TestStoreRangeMergeStats`. Now both will stand up to being
stressed.

[Review on Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/4746)

### CODE REVIEW

File: storage/client_merge_test.go [hunk 1]
```diff
@@ -380,18 +380,19 @@ func TestStoreRangeMergeStats(t *testing.T) {
 
 	// Get the range stats for both ranges now that we have data.
 	var msA, msB engine.MVCCStats
-	if err := engine.MVCCGetRangeStats(store.Engine(), aDesc.RangeID, &msA); err != nil {
+	snap := store.Engine().NewSnapshot()
```
Comment (tschottdorf) [inline storage/client_merge_test.go]: all `snap`s like `defer snap.Close()`.

**Comment by tschottdorf** [comment]
LGTM except missing `.Close()` everywhere.

**Comment by nvanbenschoten** [comment]
Ah right, thanks for catching that. PTAL

File: storage/client_merge_test.go (hunk 1 above)
Comment (nvanbenschoten) [inline storage/client_merge_test.go]: Done.
