### PR TITLE
sql: retry on split failures during SPLIT AT

### LINKED ISSUE #9120: sql: new flakiness in TestLogic / select_index_span_ranges
Found in https://circleci.com/gh/cockroachdb/cockroach/22296

```
 	logic_test.go:1247: testdata/select_index_span_ranges:37: expected success, but found
		pq: storage/replica_command.go:2237: split at key /Table/51/1/2 failed: conflict updating range descriptors
	logic_test.go:446: testdata/select_index_span_ranges:37: error in statement, skipping to next file
```

Perhaps a consequence of #9099?

cc @RaduBerinde

### PR DESCRIPTION
**Pull request by RaduBerinde**
Ran testdata/select_index_span_ranges and TestSplitAt under `make stress` with
maxSplitRetries=2 and saw no failures. Setting to 4 for good measure.

Fixes #9120.

---

This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/9125)

### CODE REVIEW

File: sql/split.go [hunk 1]
```diff
@@ -124,7 +127,18 @@ func (n *splitNode) Start() error {
...
-	return n.p.execCfg.DB.AdminSplit(n.key)
+
+	// We retry a few times if we hit an error. One instance of expected errors
+	// happens after a table creation, where AdminSplit will sometimes fail with
+	// "conflict updating range descriptors".
+	var splitErr error
+	for r := retry.Start(retry.Options{MaxRetries: maxSplitRetries}); r.Next(); {
+		splitErr = n.p.execCfg.DB.AdminSplit(n.key)
+		if splitErr == nil {
+			return nil
```
Comment (tamird) [inline sql/split.go]: slightly more expected:

```
if splitErr != nil {
  continue
}
```

Comment (tamird) [inline sql/split.go]: it might also be better to check the error more rigorously rather than blindly retry on all errors

Comment (RaduBerinde) [inline sql/split.go]: TFTR! I don't see the problem with retrying on all errors, given that we're only doing a few retries. If it's a persistent error, we will fail soon enough anyway, and if it's transient and it goes away, all the better..

Comment (tamird) [inline sql/split.go]: > and if it's transient and it goes away, all the better..

Heh, I don't think I agree with that sentiment.

**Comment by andreimatei** [comment]
I don't know about this... No particular strong feelings, but I already don't like this `sql/split` node very much, and now we're adding more magic to it.

And as @tamird also noted, you're blindly swallowing all errors, which is not the philosophy of our code elsewhere because it can hide unexpected errors. I think we should target more specific errors, unless it's particularly hard to anticipate the kind of errors returned by this race.

But may I suggest another idea: don't do any retries, neither here, nor in the tests. Instead, figure out what the race is exactly, and figure out what (and maybe how) to wait such that there's no race any more. E.g. if the race is with another split that is guaranteed to be performed by one of the queue (cause I think they split on table boundaries?), we can spin until one server (or all, in a `TestCluster`) sees all the effects of that other split - e.g. there's methods in the TestCluster to read a range descriptor, and to see one node's information about the Lease of a range.
Or maybe the race involves the a node's RangeCache, in which case forcing an invalidation might help (and there's tests that do this sort of thing already).

---

Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/9125#-:-KR-RZ9ktJ7D3Dg75rrl:b56lcvw)*

**Comment by RaduBerinde** [comment]
I don't understand why you don't like `SPLIT AT`, but that's beside the point. If we have a `SPLIT AT` command, it should work reliably if there are no problems in the cluster.

At a high level, the system can decide to split ranges whenever, so there is always the possibility of a conflict. I am not familiar enough with the lower level details of splitting to figure out exactly how to set up an admin split without hitting this error. For now I am leaving a retry loop (for this specific error), and I am filing an issue to track fixing this in a cleaner way.

---

Review status: 0 of 5 files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/9125#-:-KR-h33ER-7MaCDQyoa5:blqwh2l)*

**Comment by andreimatei** [comment]
LGTM

Well but if your splitting raced with another split, are you sure you still want it? Maybe the client should decide.
I would file that issue and assign it to @mjibson to think about it.

---

Review status: 0 of 5 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/9125#-:-KR0-aoP5iCSZlXq34P7:b-zbxib7)*

**Comment by andreimatei** [comment]
Review status: 0 of 5 files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[sql/split.go, line 141 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/9125#-KR00sMZn0O6FeMAI0X-:-KR00sMZn0O6FeMAI0X0:b43trw8) ([raw file](https://github.com/cockroachdb/cockroach/blob/e03742f314609c7cf24b266320a6b33cb9db7a8a/sql/split.go#L141)):*
> ```Go
> 		err := n.p.execCfg.DB.AdminSplit(n.key)
> 		if err != nil &&
> 			strings.Contains(err.Error(), storage.ErrConflictUpdatingRangeDesc.Error()) &&
> ```

check for the sentinel error explicitly instead of comparing strings?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/9125)*

**Comment by RaduBerinde** [comment]
There is always the possibility of a split happening *and completing* between the time the client decides to issue the command, and the time we actually process the command so there are no guarantees anyway; this PR doesn't change the semantics in that sense.

---

Review status: 0 of 5 files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[sql/split.go, line 141 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/9125#-KR00sMZn0O6FeMAI0X-:-KR0H7xChAb_vFMIf_lj:bksqd7j) ([raw file](https://github.com/cockroachdb/cockroach/blob/e03742f314609c7cf24b266320a6b33cb9db7a8a/sql/split.go#L141)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary>
> check for the sentinel error explicitly instead of comparing strings?
</details>
It goes through pg, it's not the original error anymore

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/9125#-:-KR0HAsmK8qpNfNXfWRk:bokex77)*

**Comment by RaduBerinde** [comment]
Review status: 0 of 5 files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[sql/split.go, line 141 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/9125#-KR00sMZn0O6FeMAI0X-:-KR0XBOLSkXvf-Jcxd4l:b-97n6q6) ([raw file](https://github.com/cockroachdb/cockroach/blob/e03742f314609c7cf24b266320a6b33cb9db7a8a/sql/split.go#L141)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary>
> It goes through pg, it's not the original error anymore
</details>
Sorry, that made no sense (I was confused by the `pq: ` prefix but that's from logic test). `AdminSplit` adds a `split at key %s failed:` prefix. Plus the command can run on a different node so it can't be the same error instance. Maybe I should export just the message string?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/9125)*

File: storage/replica_command.go [hunk 2]
```diff
@@ -49,6 +49,11 @@ import (
 
 var errTransactionUnsupported = errors.New("not supported within a transaction")
 
+// ErrMsgConflictUpdatingRangeDesc is an error message that is returned by
+// AdminSplit when it conflicts with some other process that updates range
+// descriptors.
+var ErrMsgConflictUpdatingRangeDesc = "conflict updating range descriptors"
```
Comment (tamird) [inline storage/replica_command.go]: const?

**Comment by RaduBerinde** [comment]
Review status: 0 of 5 files reviewed at latest revision, 3 unresolved discussions.

---

*[storage/replica_command.go, line 55 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/9125#-KR-k8-iHmbTn0DdFlS--r3-55:-KR0cHw8-dDDwE8ihNzf:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/01263ce5cd3f25279ccc9694e8d5f402b26d2056/storage/replica_command.go#L55)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> const?
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/9125)*

**Comment by andreimatei** [comment]
Dont you have access to the wrapped error inside the error you get?

**Comment by RaduBerinde** [comment]
Again, it can go over the wire..

---

Review status: 0 of 5 files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/9125#-:-KR0laG-azbEiA9jzrWZ:buign32)*

**Comment by RaduBerinde** [comment]
Review status: 0 of 5 files reviewed at latest revision, 4 unresolved discussions, all commit checks successful.

---

*[storage/replica_command.go, line 2242 \[r4\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/9125#-KR0mcIHEqYj4sy7Uqua:-KR0mcIHEqYj4sy7Uqub:bam92wr) ([raw file](https://github.com/cockroachdb/cockroach/blob/3d137a6a8485cf6bca903be19650f729e12bbbc0/storage/replica_command.go#L2242)):*
> ```Go
> 		return txn.Run(b)
> 	}); err != nil {
> 		return reply, roachpb.NewErrorf("split at key %s failed: %s", splitKey, err)
> ```

@andreimatei this is where the error message gets prefixed (it's not really wrapped). In any case, we may be receiving this error on another node (this code is on the replica, we are on the client side of an `AdminSplitRequest`)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/9125)*

**Comment by tamird** [comment]
LGTM
