### PR TITLE
sql: report anonymized statement on panic

### LINKED ISSUE #20613: sql: report anonymized query on SQL panic
Currently, crashes in SQL report an anonymized stack trace. This is good but sometimes doesn't provide enough information to figure out what caused the crash. We should include the anonymized query in the crash report.

### PR DESCRIPTION
**Pull request by tbg**
Fixes #20613.

Release note: None

### CODE REVIEW

**Comment by lego** [comment]
<3 thank you for doing this!

File: pkg/sql/session.go [hunk 1]
```diff
@@ -1383,15 +1385,41 @@ func (scc *schemaChangerCollection) execSchemaChanges(
...
 	if r := recover(); r != nil {
-		err := errors.Errorf("panic while %s %q: %s", action, stmt, r)
+		var anonymized []string
+		{
+			stmts, err := parser.Parse(stmt)
+			if err == nil {
+				var buf bytes.Buffer
+				for _, stmt := range NewStatementList(stmts) {
+					buf.Reset()
+					tree.FormatNode(&buf, tree.FmtHideConstants, stmt.AST)
```
Comment (jordanlewis) [inline pkg/sql/session.go]: I think this might need to be `FmtAnonymize` as well, which hides table and database names.

File: pkg/util/log/crash_reporting.go [hunk 2]
```diff
@@ -109,11 +109,59 @@ func (st SafeType) SafeMessage() string {
...
+// Cause returns the cause of this error. If the cause did not implement
+// `error`, it will be returned as a string error.
+func (ce *chainErr) Cause() error {
+	if err, ok := ce.cause.(error); ok {
+		return err
+	}
+	return errors.Errorf("%v", ce.cause)
+}
+
+// Chain links an error and a casuse together in a way that allows error
```
Comment (jordanlewis) [inline pkg/util/log/crash_reporting.go]: nit: cause

**Review by jordanlewis — COMMENTED** [review]
Sweet! Did you test it?

**Comment by tschottdorf** [comment]
@jordanlewis much has changed, appreciate another look! Tests and necessary tooling for this to work smoothly added.

**Review by jordanlewis — COMMENTED** [review]
Tests look good. Did you try an end-to-end sentry test?

File: pkg/sql/session.go [hunk 3]
```diff
@@ -1381,17 +1383,58 @@ func (scc *schemaChangerCollection) execSchemaChanges(
...
+// (usually a recovered panic) into an error that will be useful when passed to
+// our error reporting as it exposes a scrubbed version of the statements.
+func AnonymizeStatementsForReporting(action, sqlStmts string, r interface{}) error {
+	var anonymized []string
+	{
+		stmts, err := parser.Parse(sqlStmts)
+		if err == nil {
+			var buf bytes.Buffer
+			for _, stmt := range NewStatementList(stmts) {
+				tree.FormatNode(&buf, tree.FmtAnonymize, stmt.AST)
```
Comment (jordanlewis) [inline pkg/sql/session.go]: Heh, can't you make a new FmtFlags that contains both FmtAnonymize and FmtHideConstants rather than parse and reformat each statement twice? Forgive me if I'm missing something that makes that necessary.

File: pkg/sql/session.go [hunk 4]
```diff
@@ -1381,17 +1383,58 @@ func (scc *schemaChangerCollection) execSchemaChanges(
...
+		// A warning header guaranteed to go to stderr. This is unanonymized.
+		cutStmts := stmts
+		if len(cutStmts) > panicLogOutputCutoffChars {
+			cutStmts = stmts[:panicLogOutputCutoffChars] + " [...]"
+		}
 
-		// A short warning header guaranteed to go to stderr.
 		log.Shout(s.Ctx(), log.Severity_ERROR,
-			"a SQL panic has occurred!")
+			fmt.Sprintf("a SQL panic has occurred while %s %q: %s",
```
Comment (jordanlewis) [inline pkg/sql/session.go]: I think there was a reason why only a header was printed here - to prevent duplicate panic stack traces. Won't we get two now?

File: pkg/sql/session_test.go [hunk 5]
```diff
@@ -37,9 +37,49 @@ import (
 	"github.com/cockroachdb/cockroach/pkg/testutils/serverutils"
 	"github.com/cockroachdb/cockroach/pkg/testutils/sqlutils"
 	"github.com/cockroachdb/cockroach/pkg/util/leaktest"
+	"github.com/cockroachdb/cockroach/pkg/util/log"
 	"github.com/cockroachdb/cockroach/pkg/util/timeutil"
 )
 
+func TestAnonymizeStatementsForReporting(t *testing.T) {
```
Comment (jordanlewis) [inline pkg/sql/session_test.go]: CI says you need a leak test here.

**Comment by tschottdorf** [comment]
@jordanlewis yep! 


---

Review status: 0 of 4 files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[pkg/sql/session.go, line 1400 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/20799#-L0eWp1m-_igTzpOFqNY-r1-1400:-L0jN3rwHpbldIYWBrGV:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/ae0f7e615a1cc9c67e0cef9f5c58e0523ad57436/pkg/sql/session.go#L1400)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

I think this might need to be `FmtAnonymize` as well, which hides table and database names.
</blockquote></details>

Done.

---

*[pkg/sql/session.go, line 1398 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/20799#-L0eWp1m-_igTzpOFqNY-r2-1398:-L0jMzgiJRrhm7ZW-hKv:bsbvkbj) ([raw file](https://github.com/cockroachdb/cockroach/blob/b5752110387f13ae76f64368de8581d23dee3b05/pkg/sql/session.go#L1398)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

Heh, can't you make a new FmtFlags that contains both FmtAnonymize and FmtHideConstants rather than parse and reformat each statement twice? Forgive me if I'm missing something that makes that necessary.
</blockquote></details>

I don't think you're missing something, but I don't want to pull on this thread, that can be its own PR: https://github.com/cockroachdb/cockroach/issues/20864

---

*[pkg/sql/session.go, line 1436 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/20799#-L0eWp1m-_igTzpOFqNY-r2-1436:-L0jN5R7gJbS_rlEEp7U:bcemccq) ([raw file](https://github.com/cockroachdb/cockroach/blob/b5752110387f13ae76f64368de8581d23dee3b05/pkg/sql/session.go#L1436)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

I think there was a reason why only a header was printed here - to prevent duplicate panic stack traces. Won't we get two now?
</blockquote></details>

You definitely don't get the unscrubbed statement any more from higher up. I felt it was better to make sure the unredacted value makes it to the user so it can be reported.

---

*[pkg/sql/session_test.go, line 44 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/20799#-L0fv3Kl1t_tYwZhe3Fr-r2-44:-L0jNMLKlLFFLKzM3wI_:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/b5752110387f13ae76f64368de8581d23dee3b05/pkg/sql/session_test.go#L44)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

CI says you need a leak test here.
</blockquote></details>

Done.

---

*[pkg/util/log/crash_reporting.go, line 152 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/20799#-L0eWp1m-_igTzpOFqNZ-r1-152:-L0jNMu0o7oUAM-_UYXD:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/ae0f7e615a1cc9c67e0cef9f5c58e0523ad57436/pkg/util/log/crash_reporting.go#L152)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

nit: cause
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/20799#-:-L0jglTzEY42jvTsI-fa:bwa4fnx)*

**Comment by jordanlewis** [comment]
:lgtm:

---

Reviewed 2 of 4 files at r2, 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/20799#-:-L0kLemkWS-Ay4gSWXFP:bnfp4nl)*

**Comment by tschottdorf** [comment]
TFTRs!
