### PR TITLE
*: Remove freeze-cluster and supporting code

### LINKED ISSUE #7038: stability: freeze-cluster never terminates
In #6985, we found that freeze-cluster would hang without completing. We need to make this process reliable before we can recommend it as a part of the regular upgrade process.

In the meantime, we should be trying freeze-cluster as a part of all of our upgrades for testing purposes even though we're not yet recommending that regular users do so.

### LINKED ISSUE #7238: stability: freeze-cluster failure
sha: c17928f

Tried to freeze nodes on `beta` prior to upgrade. All nodes were currently healthy.
started `cockroach freeze-cluster` against node1:

```
$ cockroach freeze-cluster --host=104.196.97.139 --ca-cert=certs/ca.crt --cert=certs/root.client.c
rt --key=certs/root.client.key
proposed freeze to 4238 ranges
waiting for 6 stores to apply operation
node 1, store 1: 1 replicas report wrong status: [{NodeID:1 StoreID:1 ReplicaID:3}]
node 3, store 3: ready
node 4, store 4: 1 replicas report wrong status: [{NodeID:4 StoreID:4 ReplicaID:6}]
node 2, store 2: 997 replicas report wrong status [truncated]: [{NodeID:2 StoreID:2 ReplicaID:4} {NodeID:2 StoreID:2 Rep
licaID:5} {NodeID:2 StoreID:2 ReplicaID:1} {NodeID:2 StoreID:2 ReplicaID:9} {NodeID:2 StoreID:2 ReplicaID:6} {NodeID:2 S
toreID:2 ReplicaID:4} {NodeID:2 StoreID:2 ReplicaID:7} {NodeID:2 StoreID:2 ReplicaID:4} {NodeID:2 StoreID:2 ReplicaID:6}
 {NodeID:2 StoreID:2 ReplicaID:2}]
node 6, store 6: 1 replicas report wrong status: [{NodeID:6 StoreID:6 ReplicaID:4}]
node 5, store 5: 1 replicas report wrong status: [{NodeID:5 StoreID:5 ReplicaID:1}]
waiting for 5 stores to apply operation
.....
waiting for 5 stores to apply operation
node 4, store 4: 1 replicas report wrong status: [{NodeID:4 StoreID:4 ReplicaID:6}]
node 1, store 1: 1 replicas report wrong status: [{NodeID:1 StoreID:1 ReplicaID:3}]
node 2, store 2: 997 replicas report wrong status [truncated]: [{NodeID:2 StoreID:2 ReplicaID:4} {NodeID:2 StoreID:2 ReplicaID:5} {NodeID:2 StoreID:2 ReplicaID:1} {NodeID:2 StoreID:2 ReplicaID:9} {NodeID:2 StoreID:2 ReplicaID:6} {NodeID:2 StoreID:2 ReplicaID:4} {NodeID:2 StoreID:2 ReplicaID:7} {NodeID:2 StoreID:2 ReplicaID:4} {NodeID:2 StoreID:2 ReplicaID:6} {NodeID:2 StoreID:2 ReplicaID:2}]
node 6, store 6: 1 replicas report wrong status: [{NodeID:6 StoreID:6 ReplicaID:4}]
node 5, store 5: 1 replicas report wrong status: [{NodeID:5 StoreID:5 ReplicaID:1}]
waiting for 5 stores to apply operation
Error: rpc error: code = 2 desc = timed out waiting for 5 stores to report freeze
Failed running "freeze-cluster"
```

I stopped the `block_writer` and `photos` apps sometime after I started the `freeze-cluster` command, but long before it terminated.

### LINKED ISSUE #7928: acceptance: TestFreezeCluster is skipped, possibly due to gossip issues
Happened on two separate (unrelated) branches on CircleCI, as well as locally. If you rebuild enough times it eventually goes away. Here is an example:
- https://circleci.com/gh/arjunravinarayan/cockroach/79
- https://circleci.com/gh/arjunravinarayan/cockroach/80
- (Fixed on rebuild): https://circleci.com/gh/arjunravinarayan/cockroach/82

From the log it looks like the http endpoint is not coming up in time.

```
I160719 17:11:15.170388 acceptance/freeze_test.go:46  requesting: freeze=false, timeout=10s
I160719 17:11:15.172666 acceptance/freeze_test.go:46  requesting: freeze=false, timeout=10s
```

...

```
I160719 17:11:24.342235 acceptance/freeze_test.go:46  requesting: freeze=false, timeout=10s
I160719 17:11:25.344527 acceptance/freeze_test.go:46  requesting: freeze=false, timeout=10s
```

If you look at the `stderr` [log](https://80-59059502-gh.circle-artifacts.com/0//tmp/circle-artifacts.pThZDsX/acceptance/TestFreezeCluster/roach2/stderr.2016-07-19T17_11_36Z.log), you see that gossip isn't connecting for 15 seconds:

```
W160719 17:11:15.255515 kv/dist_sender.go:656  the descriptor for the first range is not available via gossip
W160719 17:11:15.258886 kv/dist_sender.go:656  the descriptor for the first range is not available via gossip
```

...

```
I160719 17:11:32.236670 storage/queue.go:290  [verify] no system config available. skipping
I160719 17:11:32.236693 storage/queue.go:290  [replicate] no system config available. skipping
I160719 17:11:32.236715 storage/queue.go:290  [replicaGC] no system config available. skipping
I160719 17:11:32.236754 storage/queue.go:290  [raftlog] no system config available. skipping
```

That's 15 seconds.

### PR DESCRIPTION
**Pull request by bdarnell**
This command was unfinished, and now it never will be as freezing the
cluster is no longer an acceptable upgrade process.

Closes #7238
Closes #7038
Closes #7928

### CODE REVIEW

**Comment by bdarnell** [comment]
We could take the less drastic step of removing the top-level `freeze-cluster` command but leave the range-level `ChangeFrozen` command (we might want to do something like freezing to support merging ranges). But there's enough magic in this implementation (e.g. the auto-revive on restart) that if we want to use it for anything but version upgrades we'll probably want to start from scratch anyway. 

---

Review status: 0 of 49 files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[pkg/storage/replica.go, line 3509 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/14779#-KhQ99BSupKTUG1PlD8R:-KhQ99BSupKTUG1PlD8S:buopfn) ([raw file](https://github.com/cockroachdb/cockroach/blob/5e485c9ea5089798b8de9279d3c31d75c356dfb6/pkg/storage/replica.go#L3509)):*
> ```Go
> 	// TODO(bdarnell): the isConsistencyRelated field is insufficiently tested;
> 	// no tests fail if it is always set to false.
> 	var isLeaseRequest, isFreeze, isConsistencyRelated bool
> ```

The `isConsistencyRelated` flag was only necessary to permit consistency-checker commands to run even when the range is frozen, so it's gone too.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14779#-:-KhQ9H_yAQN99Qqw3lgo:b-f88qch)*

File: pkg/keys/printer_test.go [hunk 1]
```diff
@@ -57,7 +57,6 @@ func TestPrettyPrint(t *testing.T) {
 		{RangeLeaseKey(roachpb.RangeID(1000001)), "/Local/RangeID/1000001/r/RangeLease"},
 		{RangeStatsKey(roachpb.RangeID(1000001)), "/Local/RangeID/1000001/r/RangeStats"},
 		{RangeTxnSpanGCThresholdKey(roachpb.RangeID(1000001)), `/Local/RangeID/1000001/r/RangeTxnSpanGCThreshold`},
-		{RangeFrozenStatusKey(roachpb.RangeID(1000001)), "/Local/RangeID/1000001/r/RangeFrozenStatus"},
```
Comment (petermattis) [inline pkg/keys/printer_test.go]: Leave this in? We'd want to pretty-print this key if we ever stumble across it, right?

**Review by petermattis — APPROVED** [review]
LGTM

So much code deletion.

File: pkg/keys/printer_test.go (hunk 1 above)
Comment (bdarnell) [inline pkg/keys/printer_test.go]: Yep, and we still have it in `keys/printer.go`. I kept the decoding logic (including in `cli/debug.go`) but dropped the test since keeping the test would require us to keep a function to construct these keys (that otherwise wouldn't be used)

**Comment by spencerkimball** [comment]
Nice!
