### PR TITLE
cmd/roachtest: fix cdc/multi-region-execution-locality-tpcc

### LINKED ISSUE #153825: roachtest: fix cdc/multi-region-execution-locality-tpcc
The `cdc/multi-region-execution-locality-tpcc` roachtest added in #150859 appears to hang on this line, which isn't unexpected given that changefeeds don't complete unless they're initial-scan-only or encounter an error:
https://github.com/cockroachdb/cockroach/blob/47bb79cb2880ca1e99b9fbe74fee9eb1e04055e1/pkg/cmd/roachtest/tests/cdc.go#L2060

It should also be added to the nightly test suite:
https://github.com/cockroachdb/cockroach/blob/47bb79cb2880ca1e99b9fbe74fee9eb1e04055e1/pkg/cmd/roachtest/tests/cdc.go#L2033

Jira issue: CRDB-54614

### PR DESCRIPTION
**Pull request by log-head**
This roachtest hangs waiting for changefeed to complete. Changing changefeed to an initial scan.

Additionally, this test was flaky. This is fixed by removing the check of the exact span distribution and checking only that more than one aggregator was planned. Additionally, before not all lease-holders would always be set to the same region. Now, all leaseholders will be in the specified region.

Additionally, adding to nightly test suite.

Epic: CRDB-38755
Fixes: #153825

Release note: None

### CODE REVIEW

File: pkg/cmd/roachtest/tests/cdc.go [hunk 1]
```diff
@@ -2058,7 +2058,7 @@ func registerCDC(r registry.Registry) {
 		Owner:            registry.OwnerCDC,
 		Cluster:          r.MakeClusterSpec(7, spec.Geo(), spec.GatherCores(), spec.GCEZones("us-east1-b,us-west1-b")),
 		CompatibleClouds: registry.OnlyGCE,
-		Suites:           registry.Suites(),
+		Suites:           registry.Suites(registry.Nightly),
```
Comment (andyyang890) [inline pkg/cmd/roachtest/tests/cdc.go:2047]: Seems like the test might be flaky:
```
2025/09/25 01:13:13 test_runner.go:1293: --- FAIL: cdc/multi-region-execution-locality-tpcc (602.03s)
(assertions.go:369).Fail: 
	Error Trace:	pkg/cmd/roachtest/tests/cdc.go:2097
	            				pkg/cmd/roachtest/test_runner.go:1421
	            				src/runtime/asm_amd64.s:1700
	Error:      	"5" is not less than or equal to "4"
	Test:       	cdc/multi-region-execution-locality-tpcc
	Messages:   	nodeIdx 0 watched 5 spans, total spans watched 9
```

Artifacts from TC run: https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/20516311?buildTab=artifacts#%2Fcdc%2Fmulti-region-execution-locality-tpcc%2Frun_1%2Fdebug.zip;%2Fcdc%2Fmulti-region-execution-locality-tpcc%2Frun_1%2Fartifacts.zip

**Review by andyyang890 — CHANGES_REQUESTED** [review]

File: pkg/cmd/roachtest/tests/cdc.go [hunk 2]
```diff
@@ -2090,18 +2092,12 @@ func registerCDC(r registry.Registry) {
...
-				require.LessOrEqual(t, spansWatched, changefeedDistribution.TotalSpansWatched/2, "nodeIdx %d watched %d spans, total spans watched %d", nodeIdx, spansWatched, changefeedDistribution.TotalSpansWatched)
-			}
 			require.Equal(t, 1, len(changefeedDistribution.ZoneToSpansWatched))
 			require.Equal(t, changefeedDistribution.ZoneToSpansWatched["us-east1-b"], changefeedDistribution.TotalSpansWatched)
-			zoneToLeaseHolderCount := veryifyLeaseHolderDistribution(ct.DB(), t, nodeToZone)
-			// Majority of lease holders should be in us-west1-b. Some may not, but most should.
-			if zoneToLeaseHolderCount["us-east1-b"] != 0 {
-				require.Greater(t, zoneToLeaseHolderCount["us-west1-b"]/zoneToLeaseHolderCount["us-east1-b"], 10)
-			}
+
```
Comment (andyyang890) [inline pkg/cmd/roachtest/tests/cdc.go]: nit: remove extra newline

File: pkg/cmd/roachtest/tests/cdc.go [hunk 3]
```diff
@@ -2011,42 +2011,37 @@ func getChangefeedDistribution(
...
-			replicas[indx]--
+func verifyLeaseHolderLocality(db *gosql.DB, t test.Test, primaryRegion string) {
+	leaseHolderQuery := `SELECT NOT EXISTS (
+	SELECT 1
+	FROM [SHOW CLUSTER RANGES WITH TABLES, DETAILS]
+	WHERE database_name = 'tpcc'
+		AND (lease_holder_locality IS DISTINCT FROM $1::STRING OR lease_holder_locality IS NULL)
+)`
+	t.L().Printf("Waiting for all lease holders to be in region %s", primaryRegion)
+	tStart := timeutil.Now()
```
Comment (andyyang890) [inline pkg/cmd/roachtest/tests/cdc.go]: nit: s/tStart/start/

File: pkg/cmd/roachtest/tests/cdc.go [hunk 4]
```diff
@@ -2011,42 +2011,37 @@ func getChangefeedDistribution(
...
+	ok := false
+	for {
+		if timeutil.Since(tStart) > 5*time.Minute {
+			t.L().Printf("Timeout waiting for lease holders to be in region %s", primaryRegion)
```
Comment (andyyang890) [inline pkg/cmd/roachtest/tests/cdc.go]: nit: it's not necessary to log this since the fatal right after contains the same info

File: pkg/cmd/roachtest/tests/cdc.go [hunk 5]
```diff
@@ -2090,18 +2092,12 @@ func registerCDC(r registry.Registry) {
 			processors, err := getDiagramProcessors(ctx, ct.DB())
 			require.NoError(t, err)
 
+			// Verify changefeed aggregators are distributed across nodes in region us-east.
 			changefeedDistribution := getChangefeedDistribution(processors, nodeToZone, t)
 			require.Greater(t, changefeedDistribution.TotalAggregators, 1)
-			for nodeIdx, spansWatched := range changefeedDistribution.NodeToSpansWatched {
```
Comment (andyyang890) [inline pkg/cmd/roachtest/tests/cdc.go:2088]: There are a few fields on `ChangefeedDistribution` that are no longer used (i.e. `NodeToSpansWatched`, `TotalLeaseHolders`, `TotalRanges`). The latter two seem to not be populated at all. Should we assert on them? If not, could we remove them?

File: pkg/cmd/roachtest/tests/cdc.go
Comment (andyyang890) [inline pkg/cmd/roachtest/tests/cdc.go:1959]: nit: `NodeToZone` does not need to be a field on `ChangefeedDistribution` since it's only used in the function where the structs are created (i.e. `getChangefeedDistribution`)

File: pkg/cmd/roachtest/tests/cdc.go [hunk 6]
```diff
@@ -2090,18 +2092,12 @@ func registerCDC(r registry.Registry) {
...
-				require.LessOrEqual(t, spansWatched, changefeedDistribution.TotalSpansWatched/2, "nodeIdx %d watched %d spans, total spans watched %d", nodeIdx, spansWatched, changefeedDistribution.TotalSpansWatched)
-			}
 			require.Equal(t, 1, len(changefeedDistribution.ZoneToSpansWatched))
```
Comment (andyyang890) [inline pkg/cmd/roachtest/tests/cdc.go]: Could we be extra paranoid here and assert that the zone is the one we expect?

You could do something like adding a contains assertion:
```suggestion
			require.Equal(t, 1, len(changefeedDistribution.ZoneToSpansWatched))
			require.Contains(t, changefeedDistribution.ZoneToSpansWatched, "us-west1-b")
```

Or assert directly on the keys (my preference):
```suggestion
			require.ElementsMatch(t, maps.Keys(changefeedDistribution.ZoneToSpansWatched), []string{"us-east-1b"})
```

(I haven't tested these but something like that should work)

File: pkg/cmd/roachtest/tests/cdc.go [hunk 7]
```diff
@@ -2090,18 +2092,12 @@ func registerCDC(r registry.Registry) {
...
 			require.Equal(t, changefeedDistribution.ZoneToSpansWatched["us-east1-b"], changefeedDistribution.TotalSpansWatched)
```
Comment (andyyang890) [inline pkg/cmd/roachtest/tests/cdc.go:2090]: Maybe we also want an assertion that `TotalSpansWatched` > 0 here?

**Review by andyyang890 — COMMENTED** [review]
Looking good, just some minor comments

**Comment by log-head** [comment]
[tc results](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/20545430?buildTab=overview&expandBuildDeploymentsSection=false&hideTestsFromDependencies=false&hideProblemsFromDependencies=false&expandBuildChangesSection=true) passing after Andy's suggested changes.

File: pkg/cmd/roachtest/tests/cdc.go [hunk 8]
```diff
@@ -68,6 +69,7 @@ import (
 	prompb "github.com/prometheus/client_model/go"
 	"github.com/prometheus/common/expfmt"
 	"github.com/stretchr/testify/require"
+	"golang.org/x/exp/maps"
```
Comment (andyyang890) [inline pkg/cmd/roachtest/tests/cdc.go]: The `maps` package is in the standard library as of go 1.23
```suggestion
	"maps"
```

(it'll need to go at the top in alphabetical order)

File: pkg/cmd/roachtest/tests/cdc.go [hunk 9]
```diff
@@ -2083,25 +2082,20 @@ func registerCDC(r registry.Registry) {
...
 			require.NoError(t, err)
 
+			// Verify changefeed aggregators are distributed across nodes in region us-east.
 			changefeedDistribution := getChangefeedDistribution(processors, nodeToZone, t)
 			require.Greater(t, changefeedDistribution.TotalAggregators, 1)
-			for nodeIdx, spansWatched := range changefeedDistribution.NodeToSpansWatched {
-				require.LessOrEqual(t, spansWatched, changefeedDistribution.TotalSpansWatched/2, "nodeIdx %d watched %d spans, total spans watched %d", nodeIdx, spansWatched, changefeedDistribution.TotalSpansWatched)
-			}
-			require.Equal(t, 1, len(changefeedDistribution.ZoneToSpansWatched))
+			// require.Equal(t, 1, len(changefeedDistribution.ZoneToSpansWatched))
```
Comment (andyyang890) [inline pkg/cmd/roachtest/tests/cdc.go]: nit: remove commented-out code

**Review by andyyang890 — APPROVED** [review]
Nice work!

**Review by andyyang890 — APPROVED** [review]
