### PR TITLE
sql: fix potential nil dereference in parseandrequirestring

### LINKED ISSUE #50463: sql: program panic due to failure in parsing
https://github.com/cockroachdb/cockroach/blob/f0cfa7866f1d9cab837aa83f140fbe9e2d1569dd/pkg/sql/sem/tree/parse_string.go#L53-L55
If `ParseAndRequireString` fails to parse string as Oid type, it should return an error. Current implementation cause panic.

### PR DESCRIPTION
**Pull request by yongyanglai**
Previously, 'ParseAndRequireString' directly dereferenced pointer
without checking when parsing string as OID type, which may leaded to nil
pointer dereference if parsing is failed

This commit fixed this issue.

Fix: #50463
Release note: None

### CODE REVIEW

File: pkg/sql/sem/tree/parse_string.go [hunk 1]
```diff
@@ -52,6 +52,9 @@ func ParseAndRequireString(t *types.T, s string, ctx ParseTimeContext) (Datum, e
 		return ParseDJSON(s)
 	case types.OidFamily:
 		i, err := ParseDInt(s)
+		if err != nil {
+			return nil, err
+		}
 		return NewDOid(*i), err
```
Comment (jordanlewis) [inline pkg/sql/sem/tree/parse_string.go:58]: nit: you can return `NewDOid(*i), nil` here

**Review by jordanlewis — COMMENTED** [review]
Thanks! Just one comment

**Review by yongyanglai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/50550)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/sem/tree/parse_string.go, line 58 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/50550#-MAWmyp7bfptv6i_OkXu-r1-58:-MAWpOVzDFndJMtWBHlh:b-r4oopa) ([raw file](https://github.com/cockroachdb/cockroach/blob/400f61943984fb35cf78ea6a404a029c9aa73a3d/pkg/sql/sem/tree/parse_string.go#L58)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

nit: you can return `NewDOid(*i), nil` here
</blockquote></details>

Done
thanks for the review

**Comment by jordanlewis** [comment]
Thanks!

bors r+
