### PR TITLE
kvserver: use span config reader in entireSpanExcludedFromBackup

### LINKED ISSUE #131993: kv: entireSpanExcludedFromBackupRLocked returning false
We've observed some of our clusters failing to backup citing a gc threshold in the leases table of a tenant. This is interesting since this table has a config that says it is excluded from backup, so typically a gc error to a range for it would be decorated with a bool telling the backup processor that it can ignore the error since it didn't need data from that range anyway. However we're seeing this error bubble up which means it does not have this boolean on it. This seems like it could be because some tables, such as the MR system.leases table, have many span configs for the same table that are applying within the same range, but the entireSpanExcludedFromBackupRLocked check will report false right now if the config is not the same for the whole span (even if every config has the bit). We do see a stream of the warnings logged in this case in the logs.

More context in https://cockroachlabs.slack.com/archives/C0KB9Q03D/p1728074952547289.

Jira issue: CRDB-42779

### PR DESCRIPTION
**Pull request by miraradeva**
Previously, `entireSpanExcludedFromBackup` used the replica's cached span config to determine whether the entire span of an `ExportRequest` can be excluded from backup. This is a problem for ranges with multiple span configs because only the first one is cached at the replica. In these cases, `entireSpanExcludedFromBackup` returned false becasue the span of the `ExportRequest` is not fully contained in the replica's cached span sonfig.

This commit replaces the cached span config with a config reader; `entireSpanExcludedFromBackup` now iterates over all span configs that overlap with the `ExportRequest`'s span.

Fixes: #131993

Release note: None

### CODE REVIEW

File: pkg/kv/kvserver/replica.go [hunk 1]
```diff
@@ -2196,7 +2231,6 @@ func (r *Replica) checkExecutionCanProceedAfterStorageSnapshot(
 	cachedProtectedTS := r.mu.cachedProtectedTS
 	confTTL := r.mu.conf.TTL()
 	desc := r.descRLocked()
-	confSpan := r.mu.confSpan
```
Comment (stevendanna) [inline pkg/kv/kvserver/replica.go:2199]: Is confSpan entirely unused now?

File: pkg/kv/kvserver/replica.go [hunk 2]
```diff
@@ -1483,41 +1484,75 @@ func (r *Replica) GetGCHint() roachpb.GCHint {
...
+	}
+	if confReader == nil {
+		return false, errors.New("span config reader not available")
+	}
+	// Iterate over all span configs covering the request span, verifying
+	// that each one has ExcludeDataFromBackup set.
+	key := roachpb.RKey(sp.Key)
+	endKey := roachpb.RKey(sp.EndKey)
+	for key.Less(endKey) {
+		conf, confSpan, err := confReader.GetSpanConfigForKey(ctx, key)
```
Comment (stevendanna) [inline pkg/kv/kvserver/replica.go]: It would make the change bigger, but I'm wondering how much more work it would be to get access to ForEachOverlappingSpanConfig. I suspect but haven't confirmed that the concrete type we have in here in production is a *KVSubscriber, which has access to an underlying Store with ForEachOverlappingSpanConfig. This would probably require adding it to the interface and then updating a bunch of mock implementations which may be a pain. But, if we end up not worrying about backporting this could be worth it.

**Review by stevendanna — COMMENTED** [review]
Overall, this looks straightforward enough that it definitely feels like what we should do on master and moving forward.

File: pkg/kv/kvserver/replica.go (hunk 2 above)
Comment (arulajmani) [reply pkg/kv/kvserver/replica.go]: +1. I wonder if we should just move this `ForEachOverlappingSpanConfig` on the `StoreReader` instead. Like Steven said, a few mocks might need changing, but that should be fairly mechanical.

**Review by arulajmani — COMMENTED** [review]
Nice work! 

> @arulajmani reviewed 2 files and all commit messages, and made 2 comments.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/164841#-:-OmvgP5IBlEbHW30FSNK:b2ky7ke)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on miraradeva and stevendanna).

File: pkg/kv/kvserver/replica.go (hunk 2 above)
Comment (miraradeva) [reply pkg/kv/kvserver/replica.go]: Agreed. Added a new commit that does the refactor.

**Review by stevendanna — APPROVED** [review]
I like it, thanks for fixing this.

I don't love panic's in functions that return errors, but that is following the existing patterns so it makes sense here.

**Review by arulajmani — APPROVED** [review]
