### PR TITLE
roachprod: better identification of transient failures

### LINKED ISSUE #88044: roachtest: don't fail tests that can't download binary releases from GCS
`StageCockroachRelease` will attempt to download a cockroach binary release from S3 [1]. If this fails -- maybe because of temporary S3 unavailability -- we should be more proactive:

1. retry the failure with some backoff
2. eventually give up, and skip the test (like we do in cases we can't create a cluster for a test)

We should *not* be creating a  test failure GitHub issue, as that leads to wasted developer's time investigating what went wrong (especially since issues are release blockers by default).

Example failure: #88034.

[1] https://github.com/cockroachdb/cockroach/blob/master/pkg/roachprod/install/staging.go#L282

Jira issue: CRDB-19659

### LINKED ISSUE #120339: roachtest: import/tpcc/warehouses=4000/geo failed [failed to find open port]
roachtest.import/tpcc/warehouses=4000/geo [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/14347057?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/14347057?buildTab=artifacts#/import/tpcc/warehouses=4000/geo) on master @ [431d56840cacdc86638ccb48e9f3bdc16897d341](https://github.com/cockroachdb/cockroach/commits/431d56840cacdc86638ccb48e9f3bdc16897d341):

```
(cluster.go:2215).Start: failed to find services to register: failed to find 1 open ports: strconv.Atoi: parsing "expected": invalid syntax
test artifacts and logs in: /artifacts/import/tpcc/warehouses=4000/geo/run_1
```

Parameters:
 - <code>ROACHTEST_arch=amd64</code>
 - <code>ROACHTEST_cloud=gce</code>
 - <code>ROACHTEST_coverageBuild=false</code>
 - <code>ROACHTEST_cpu=16</code>
 - <code>ROACHTEST_encrypted=false</code>
 - <code>ROACHTEST_fs=ext4</code>
 - <code>ROACHTEST_localSSD=true</code>
 - <code>ROACHTEST_metamorphicBuild=false</code>
 - <code>ROACHTEST_ssd=0</code>
<details><summary>Help</summary>
<p>

See: [roachtest README](https://github.com/cockroachdb/cockroach/blob/master/pkg/cmd/roachtest/README.md)

See: [How To Investigate \(internal\)](https://cockroachlabs.atlassian.net/l/c/SSSBr8c7)

See: [Grafana](https://go.crdb.dev/roachtest-grafana/teamcity-14347057/import-tpcc-warehouses-4000-geo/1710254070818/1710254226353)

</p>
</details>
/cc @cockroachdb/sql-queries
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*import/tpcc/warehouses=4000/geo.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)
</sub>

Jira issue: CRDB-36643

### LINKED ISSUE #121126: roachtest: failure to copy certificates to nodes should be automatically marked as infra flake
When setting up a secure cluster, roachtest will create certificates and distribute them to all nodes. In case this fails, the entire test fails, but the failure is not marked as an infrastructure flake. Instead, it is routed to the team that owns the test like a regular failure would.

We already have all the APIs necessary to automatically route these failures to `ssh_problem` (#90695), so we should do that automatically.

Jira issue: CRDB-37087

### PR DESCRIPTION
**Pull request by renatolabs**
This PR introduces a roachprod API to allow certain errors to be labeled as _transient_. When using `roachprod` in the command line, these errors are returned to the caller as usual (and include a `TRANSIENT_ERROR` string). More importantly, when `roachtest` sees a transient error from roachprod, the resulting test failure is marked as a test-flake and routed to Test Eng.

The following commits then use this API to resolve a few related issues:

**roachprod: mark internal scp failures as transient**\
This uses the transient failures mechanism recently introduced to mark
failures from internal `scp` commands (when setting up a cluster or
starting the cockroach process) as transient.

Fixes: #121126

**roachprod: mark failures to stage binaries as transient**
This commit uses the recently introduced transient failure mechanism
in roachprod to automatically detect when staging a cockroach (or
workload) binary on a node fails in order to mark that as a transient
failure.

Note that 404 errors (i.e., binary not found on the GCS bucket)
is *not* marked as a transient failure as that often corresponds to a
programming error where an invalid version was requested.

Fixes: #88044

**roachprod: mark failures to find an open port transient**
These failures should not happen in regular clusters, and if they do,
they shouldn't fail tests as it indicates a problem in the test
infrastructure itself.

Fixes: #120339

**roachtest: mark failures in cluster.Install as transient**
This function only runs a fixed set of installation commands. If they
fail, we create an issue assigned to Test Eng and label the issue as
an infra flake.

Informs: #103316

The final commit in this PR also removes some outdated `install` targets; it's a bit unrelated with the rest of the PR, but I decided to clean that up while I was changing that file.

### CODE REVIEW

**Comment by renatolabs** [comment]
Reviewing per commit is highly advisable. A small build on this branch doesn't reveal any issues (see [link](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/14701876?buildTab=overview&hideProblemsFromDependencies=false&hideTestsFromDependencies=false&expandBuildChangesSection=true&expandBuildTestsSection=true)).

File: pkg/cmd/roachtest/test_impl.go [hunk 1]
```diff
@@ -494,17 +494,17 @@ func (t *testImpl) failureMsg() string {
 	return b.String()
 }
 
-// failuresContainError returns true if any of the errors in any of
-// the given failures matches the reference error.
-func failuresContainsError(failures []failure, refError error) bool {
+// failuresMatchingError returns an error of the same type as
```
Comment (srosenberg) [inline pkg/cmd/roachtest/test_impl.go:497]: Nit: "returns an error" is a bit subtle since `errors.As` updates `refError` via a side-effect. For the record, the official description of `errors.As` makes it more precise,

> As finds the first error in err's tree that matches target, and if one is found, sets target to that error value and returns true. Otherwise, it returns false.

File: pkg/cmd/roachtest/test_impl_test.go [hunk 2]
```diff
@@ -44,14 +44,23 @@ func TestTeamCityEscape(t *testing.T) {
...
 
+type targetError struct {
+	err error
+}
+
+func (te targetError) Error() string {
+	return "TARGET_ERROR"
+}
+
 func Test_failuresContainsError(t *testing.T) {
```
Comment (srosenberg) [inline pkg/cmd/roachtest/test_impl_test.go:55]: Nit: `Test_failureMatchingError`

File: pkg/roachprod/errors/errors.go [hunk 3]
```diff
@@ -66,28 +64,53 @@ func (e Cmd) Unwrap() error {
 	return e.Err
 }
 
-// SSH wraps ssh-specific errors from connections to remote hosts.
-type SSH struct {
-	Err error
+type TransientError struct {
+	Err   error
+	Label string
```
Comment (srosenberg) [inline pkg/roachprod/errors/errors.go:69]: Nit: maybe `Cause`?

**Review by srosenberg — APPROVED** [review]
Very nice! This seems like an exhaustive treatment of all transient errors, known to date. I wonder what we're missing, if anything.

File: pkg/cmd/roachtest/test_impl.go (hunk 1 above)
Comment (renatolabs) [reply pkg/cmd/roachtest/test_impl.go]: Good point, updated to match `errors.As`'s documentation.

File: pkg/cmd/roachtest/test_impl_test.go (hunk 2 above)
Comment (renatolabs) [reply pkg/cmd/roachtest/test_impl_test.go]: Fixed.

File: pkg/roachprod/errors/errors.go (hunk 3 above)
Comment (renatolabs) [reply pkg/roachprod/errors/errors.go]: I like it, renamed.

**Comment by renatolabs** [comment]
> I wonder what we're missing, if anything.

Two that come to mind are `hostError` (#101223) and generalized `apt` failures (#103316).

**Comment by renatolabs** [comment]
TFTR!

bors r=srosenberg
