### PR TITLE
Fix handling of txn commit errors.

### LINKED ISSUE #2368: losing transactions in BenchmarkBank
via @petermattis from #2364:

Run as:

```
go test -run - -bench BenchmarkBank -vmodule=bank_test=1
```

Fairly quickly, you'll see log messages like:

```
I0904 13:34:59.427848 25874 stopper.go:229  draining; tasks left:
2      kv/txn_coord_sender.go:466
```

That number takes seconds to drop to 0 (on the scale of the client inactivity timeout, pointing at abandoned heartbeat goroutines).

### PR DESCRIPTION
**Pull request by petermattis**
If txn Commit fails we need to manually Rollback under certain errors.

Fixes #2368.

I doubt this is clean or correct, but it does allow the bank benchmark to finish without having any outstanding transactions in the `txn_coord_sender`. 

I'm seeing the following error, though, which seems worrisome: `E0905 16:58:02.640145 42289 sql/txn.go:41  failure aborting transaction: txn aborted "sql/server.go:104 sql" id=c35d39a1 key="\xff\n\x02\n\x01\tbank\x00\x01\n\x03" rw=true pri=91.27979548 iso=SERIALIZABLE stat=ABORTED epo=0 ts=1441486682.627189398,1 orig=1441486682.617598295,0 max=1441486682.617598295,0; abort caused by: retry txn "sql/server.go:104 sql" id=c35d39a1 key="\xff\n\x02\n\x01\tbank\x00\x01\n\x03" rw=true pri=91.27979548 iso=SERIALIZABLE stat=PENDING epo=0 ts=1441486682.627189398,1 orig=1441486682.617598295,0 max=1441486682.617598295,0`.

Perhaps I'm trying to rollback in an inappropriate case. This rollback logic probably belongs in `client.Txn` and not in `sql`.

### CODE REVIEW

**Comment by petermattis** [comment]
FYI, this also seems to fix the excessively long `SELECTs` in `examples/sql_bank`. We're now up at a steady 250 transfers/second instead of varying all over the place. This is quite a bit worse than `examples/kv_bank` (1200 transfers/second), but we haven't even begun optimizing.

**Comment by bdarnell** [comment]
LGTM. I think that error is benign: Trying to abort an already-aborted transaction will return a `TransactionAbortedError`. These should probably be swallowed in the client layer.

File: client/txn.go [hunk 1]
```diff
@@ -373,7 +374,6 @@ func (txn *Txn) exec(retryable func(txn *Txn) error) (err error) {
 		// tried to run EndTransaction, it must have failed (or was never run;
 		// after all, it's always the last call to be executed). So we pretend
 		// we never sent one (this is necessary to send another one).
-		txn.haveEndTxn = false // if we sent one, it didn't succeed
```
Comment (vivekmenezes) [inline client/txn.go]: Can you also copy over the comment.

File: sql/txn.go [hunk 2]
```diff
@@ -30,6 +34,15 @@ func (p *planner) BeginTransaction(n *parser.BeginTransaction) (planNode, error)
 // CommitTransaction commits a transaction.
 func (p *planner) CommitTransaction(n *parser.CommitTransaction) (planNode, error) {
 	err := p.txn.Commit()
+	if err != nil {
+		if restartErr, ok := err.(proto.TransactionRestartError); ok {
+			if restartErr.CanRestartTransaction() != proto.TransactionRestart_ABORT {
+				if replyErr := p.txn.Rollback(); replyErr != nil {
+					log.Errorf("failure aborting transaction: %s; abort caused by: %s", replyErr, err)
+				}
```
Comment (vivekmenezes) [inline sql/txn.go]: Do you think it's worth putting this logic into a method that can be shared with client.Txn.exec()

**Comment by vivekmenezes** [comment]
Yeah always calling Rollback from the sql layer and handling it in the
client layer is the way to go.

File: client/txn.go (hunk 1 above)
Comment (petermattis) [inline client/txn.go]: I enhanced the comment in `Rollback` and deleted the comment above these lines.

File: sql/txn.go (hunk 2 above)
Comment (petermattis) [inline sql/txn.go]: This logic has been moved to `client.Txn.Commit`. It didn't seem easy to share with the logic in `client.Txn.exec`, but at least it is all in the same package now.

**Comment by petermattis** [comment]
I reworked this slightly so that the fix is localized to `client/txn.go`. The logic is the same as the original change with the exception that I'm not logging errors if `txn.Rollback` fails due to a `TransactionAbortedError`. PTAL

**Comment by petermattis** [comment]
And I filed #2382. We need to test this code path. Hopefully @bdarnell and @tschottdorf can give some insight into how to do so.

File: client/txn.go [hunk 3]
```diff
@@ -76,6 +76,7 @@ type Txn struct {
 	// is (still) unset.
 	haveTxnWrite bool
 	haveEndTxn   bool // True if there was an explicit EndTransaction
+	execing      bool // True if the txn is run in the exec() loop
```
Comment (tamird) [inline client/txn.go]: instead of having this flag, how about separating `Commit()` into `Commit()` and `commit()`? `Commit()` would include the cleanup logic and the `exec` loop would call `commit()`.

File: client/txn.go [hunk 4]
```diff
@@ -300,18 +301,33 @@ func (txn *Txn) CommitInBatch(b *Batch) error {
...
 
 // Rollback sends an EndTransactionRequest with Commit=false.
 func (txn *Txn) Rollback() error {
-	var err error
-	if txn.Proto.Writing {
-		err = txn.sendEndTxnCall(false /* commit */)
-	}
+	// Always allow the transaction abort request to be sent, even if we have
+	// already sent an EndTransaction request.
+	txn.haveEndTxn = false
```
Comment (tamird) [inline client/txn.go]: `haveEndTxn` doesn't mean one was already sent, it means one is about to be sent, and this flag is only used to strip the EndTransaction call off the sent calls if no intents were written. I don't think it's appropriate to touch it here.

File: client/txn.go (hunk 3 above)
Comment (petermattis) [inline client/txn.go]: Yeah, that was my original attempt, but `kv/txn_correctness_text.go` uses `client.Txn.Commit` explicitly and requires different behavior (not aborting on commit failure) from transactions that are not part of the exec loop. I didn't dive deep enough into why. Want me to file an issue?

File: client/txn.go [hunk 5]
```diff
@@ -300,18 +301,33 @@ func (txn *Txn) CommitInBatch(b *Batch) error {
...
+		}
+	}
+	return err
 }
 
 // Rollback sends an EndTransactionRequest with Commit=false.
 func (txn *Txn) Rollback() error {
-	var err error
-	if txn.Proto.Writing {
-		err = txn.sendEndTxnCall(false /* commit */)
```
Comment (tamird) [inline client/txn.go]: if we're not writing, do we still need to send the EndTransaction call? I don't understand this change.

Comment (tamird) [inline client/txn.go]: oh, this just moved. disregard!

File: client/txn.go [hunk 6]
```diff
@@ -369,11 +389,6 @@ func (txn *Txn) exec(retryable func(txn *Txn) error) (err error) {
 		break
 	}
 	if err != nil {
-		// If the retry logic gave up and haveEndTxn is true, then even if we
-		// tried to run EndTransaction, it must have failed (or was never run;
-		// after all, it's always the last call to be executed). So we pretend
-		// we never sent one (this is necessary to send another one).
-		txn.haveEndTxn = false // if we sent one, it didn't succeed
```
Comment (tamird) [inline client/txn.go]: this code looks correct. can you explain why it was removed/moved?

File: client/txn.go (hunk 4 above)
Comment (tamird) [inline client/txn.go]: perhaps `send` should set `haveEndTxn` to false after calling `txn.db.send`

File: client/txn.go (hunk 3 above)
Comment (tamird) [inline client/txn.go]: yes please

File: client/txn.go [hunk 7]
```diff
@@ -300,18 +301,33 @@ func (txn *Txn) CommitInBatch(b *Batch) error {
...
+	err := txn.sendEndTxnCall(true /* commit */)
+	if err == nil {
+		return nil
 	}
-	return nil
+	if !txn.execing {
+		// If this transaction is not part of the auto-retry loop we need to
+		// cleanup the transaction on retryable commit failures.
+		if restartErr, ok := err.(proto.TransactionRestartError); ok {
+			if restartErr.CanRestartTransaction() != proto.TransactionRestart_ABORT {
```
Comment (tamird) [inline client/txn.go]: by the way, why the special case here? the exec loop does actually send a rollback on `TransactionRestart_ABORT`

Comment (petermattis) [inline client/txn.go]: Hmm, guess I mis-read that code. I've removed the special case.

File: client/txn.go (hunk 4 above)
Comment (petermattis) [inline client/txn.go]: Perhaps. I've reverted this code to its previous location and now set `haveEndTxn = false` in `Txn.Commit` when we're trying to rollback after a failed commit.

File: client/txn.go (hunk 6 above)
Comment (petermattis) [inline client/txn.go]: It was moved to `Rollback`. But now it has been moved back.

File: client/txn.go [hunk 8]
```diff
@@ -300,18 +301,31 @@ func (txn *Txn) CommitInBatch(b *Batch) error {
...
+		return nil
 	}
-	return nil
+	if !txn.execing {
+		// If this transaction is not part of the auto-retry loop we need to
+		// cleanup the transaction on retryable commit failures.
+		if _, ok := err.(proto.TransactionRestartError); ok {
+			// Always allow the transaction abort request to be sent, even if we have
+			// already sent/queued an EndTransaction request.
+			txn.haveEndTxn = false
```
Comment (tamird) [inline client/txn.go]: ok i read over this code again, and i think this needs to be at the end of `send`; it can then also be removed from the error case in `exec`.

File: client/txn.go (hunk 3 above)
Comment (tamird) [inline client/txn.go]: as the immediate hack i think i'd rather have a `CommitNoRollback` for that test, but maybe it's not that important.

**Comment by tamird** [comment]
LGTM but feels pretty dirty to do this without a test :(

File: client/txn.go (hunk 3 above)
Comment (petermattis) [inline client/txn.go]: And how do you know whether to call `Commit` or `CommitNo{Abort,Rollback}`? Seems strange to expose that when the `Txn` itself knows which one you want.

Comment (tamird) [inline client/txn.go]: You always want `Commit` externally, except for that test you mentioned. At least I think that's true, based on your previous comment.

Comment (tamird) [inline client/txn.go]: maybe I misunderstood, since in that test `execing` would be false, and you'd get the same semantics as my original suggestion.

File: client/txn.go (hunk 8 above)
Comment (petermattis) [inline client/txn.go]: Just moving this line to `Txn.send` doesn't work. Various `client` tests fail. Happy to add a `TODO(tamird)` if you feel strongly this belongs somewhere else.

File: client/txn.go (hunk 3 above)
Comment (petermattis) [inline client/txn.go]: `execing` will be true in `kv/txn_correctness_test.go`.

File: client/txn.go (hunk 8 above)
Comment (tamird) [inline client/txn.go]: sure, that TODO sounds fine

Comment (tamird) [inline client/txn.go]:
```diff
diff --git a/client/txn.go b/client/txn.go
index 4211fb4..2783c25 100644
--- a/client/txn.go
+++ b/client/txn.go
@@ -309,9 +309,6 @@ func (txn *Txn) Commit() error {
 		// If this transaction is not part of the auto-retry loop we need to
 		// cleanup the transaction on retryable commit failures.
 		if _, ok := err.(proto.TransactionRestartError); ok {
-			// Always allow the transaction abort request to be sent, even if we have
-			// already sent/queued an EndTransaction request.
-			txn.haveEndTxn = false
 			if replyErr := txn.Rollback(); replyErr != nil {
 				// Log the error only if it is not a TransactionAbortedError.
 				if _, ok := replyErr.(*proto.TransactionAbortedError); !ok {
@@ -362,7 +359,6 @@ func (txn *Txn) exec(retryable func(txn *Txn) error) (err error) {
 	// error condition this loop isn't capable of handling.
 	txn.execing = true
 	for r := retry.Start(txn.db.txnRetryOptions); r.Next(); {
-		txn.haveTxnWrite, txn.haveEndTxn = false, false // always reset before [re]starting txn
 		if err = retryable(txn); err == nil {
 			if !txn.haveEndTxn {
 				// If there were no errors running retryable, commit the txn. This
@@ -372,6 +368,10 @@ func (txn *Txn) exec(retryable func(txn *Txn) error) (err error) {
 				err = txn.Commit()
 			}
 		}
+
+		// We're done with these. Always reset for good hygiene.
+		txn.haveTxnWrite, txn.haveEndTxn = false, false
+
 		if restartErr, ok := err.(proto.TransactionRestartError); ok {
 			if log.V(2) {
 				log.Warning(err)
@@ -387,11 +387,6 @@ func (txn *Txn) exec(retryable func(txn *Txn) error) (err error) {
 		break
 	}
 	if err != nil {
-		// If the retry logic gave up and haveEndTxn is true, then even if we
-		// tried to run EndTransaction, it must have failed (or was never run;
-		// after all, it's always the last call to be executed). So we pretend
-		// we never sent one (this is necessary to send another one).
-		txn.haveEndTxn = false // if we sent one, it didn't succeed
 		if replyErr := txn.Rollback(); replyErr != nil {
 			log.Errorf("failure aborting transaction: %s; abort caused by: %s", replyErr, err)
 		}
@@ -421,6 +416,7 @@ func (txn *Txn) send(calls ...proto.Call) error {
 		}
 		calls = calls[0:lastIndex]
 	}
+
 	return txn.db.send(calls...)
 }
 ```

that seems to do the right thing

**Comment by tschottdorf** [comment]
The way I see it, running a transaction always needs some kind of management. That's why we have `exec`: it handles your retries and makes sure to properly abort your transaction if your retryable gives up (well, it ought to, at least). Now it looks like we're trying to put pieces of txn management somewhere else so that we can avoid going through `exec`.
I would rather see unified usage such as

```go
db.Txn(func(txn *client.Txn) error {
  err := doStuff(txn)
  if err != nil {
     // exec() will abort the txn for us, if required.
    return &SomeErrorWhichDoesntRetry{err: err}
  }
  return nil
})
```

if we don't want to retry. A wrapper for this in the form
```go
db.ResumeTxn(txn, func(txn *client.Txn) error {
  // ...
})
```

seems adequate (which allows starting with a given txn proto, which is required for multiple-roundtrip SQL txns; pass a `nil` txn for starting a new one).

So, is there a reason for not going through `exec` always? Deciding not to do so is really a change from how I thought this was supposed to work.

**Comment by tschottdorf** [comment]
testing should be straightforward. There are already a couple of tests like these in `txn_test.go`. Basically you create a test sender which gives you the specific error you want when you want it, and you just compare the calls you get vs those expected.

**Comment by petermattis** [comment]
@tschottdorf `txn.exec()` either commits, aborts or retries the transaction. What do you return from the `retryable` function to choose a fourth option: exit loop so control can be handed back to the client?

I agree that it sucks that some of the transaction logic is now duplicated, but at least it is now duplicated only within the `client` package. Perhaps there is additional refactoring to be done here that can eliminate the duplication.

I'm taking a look at the `txn_test.go` stuff to see if any of those tests can be re-appropriated to test the new `txn.Commit()` behavior.

File: client/txn.go (hunk 8 above)
Comment (petermattis) [inline client/txn.go]: Did you test this? SQL transactions do not go through the `Txn.exec()` loop so `haveEndTxn` will not get reset which means a `Commit` failure will not cause the transaction to be aborted properly.

Comment (tamird) [inline client/txn.go]: @petermattis here's the [cleanup](https://github.com/tamird/cockroach/commit/342bb0bd4201629ee521cef7c7dc447479626808) i suggested, if you want to pull it in. i can also submit it as a separate PR.

Comment (tamird) [inline client/txn.go]: Since SQL transactions do not go through the `exec()` I believe it's not possible for `haveEndTxn` to be set at all.

**Comment by tschottdorf** [comment]
@petermattis: Ah, good point. I'm thinking turning off auto-committing would be a useful client switch for that (it would still abort if the retryable was unhappy). The interface

```go
db.ResumeTxn(txn, func(txn *client.Txn) error {
  // ...
})
```

would presumably always do this, and the only logic using it would be in `exec` (a new `autoCommit` bool). We wouldn't have to touch anything else, I think.

I agree of course that whatever we do, it shouldn't be anywhere outside of `client`.

File: client/txn_test.go [hunk 9]
```diff
@@ -368,3 +368,51 @@ func TestRunTransactionRetryOnErrors(t *testing.T) {
...
+		abort bool
+	}{
+		{&proto.ReadWithinUncertaintyIntervalError{}, true},
+		{&proto.TransactionAbortedError{}, false},
+		{&proto.TransactionPushError{}, true},
+		{&proto.TransactionRetryError{}, true},
+		{&proto.Error{}, true},
+		{&proto.RangeNotFoundError{}, false},
+		{&proto.RangeKeyMismatchError{}, false},
+		{&proto.TransactionStatusError{}, false},
```
Comment (petermattis) [inline client/txn_test.go]: Are the above 3 cases correct? They occur due to checking whether the error matches the `proto.TransactionRestartError` interface.

**Comment by petermattis** [comment]
Added a test that `Txn.Commit` used on a non-execing transaction will result in a transaction abort. PTAL.

**Comment by tamird** [comment]
This behaviour is inconsistent - the exec loop aborts unconditionally but the new non-exec logic aborts only when the error is a `TransactionRestartError`. Why?

**Comment by petermattis** [comment]
@tamird you're correct this behavior is inconsistent. I was trying to follow the behavior @bdarnell suggested in the bug. I'll switch the behavior to always abort, but perhaps that is unnecessary. @bdarnell? @tschottdorf?

**Comment by tamird** [comment]
LGTM

**Comment by petermattis** [comment]
I'm merging this because it is much better than what is currently in master. Happy to do a follow-on PR if there are additional comments.

**Comment by tschottdorf** [comment]
ok. My comment still stands though.

**Comment by bdarnell** [comment]
Regarding the inconsistency around `TransactionRestartError`:  I mentioned this as a potential optimization. For some errors, `TxnCoordSender` cleans up after itself, so the client only needs to call `Rollback` when `TxnCoordSender` has left the transaction open. I initially thought this would only be the case with a `TransactionRestartError` (since that is the only case handled in `Txn.exec`), but looking at `TxnCoordSender.sendOne`) it's more complicated than that. I don't think it makes sense for the client to track whether the server still has the transaction open so it's safest to unconditionally call `Rollback()`.
