### PR TITLE
tpcc/roachtest: adjust tpcc workload to optionally include deprecated FKs

### LINKED ISSUE #53122: roachtest: import/tpcc/warehouses=1000/nodes=32 failed
[(roachtest).import/tpcc/warehouses=1000/nodes=32 failed](https://teamcity.cockroachdb.com/viewLog.html?buildId=2200626&tab=buildLog) on [release-20.1@18c2c6bb8079a123e5fa37d2e99211d6feefb29b](https://github.com/cockroachdb/cockroach/commits/18c2c6bb8079a123e5fa37d2e99211d6feefb29b):

```
		  | stderr:
		  |  14 ccl/workloadccl/fixture.go:446  imported 17 GiB in customer table (30000000 rows, 30000000 index entries, took 3m40.357604011s, 80.13 MiB/s)
		  | I200820 09:17:24.376965 69 ccl/workloadccl/fixture.go:446  imported 17 GiB in order_line table (300011520 rows, 0 index entries, took 7m1.879844089s, 40.82 MiB/s)
		  | I200820 09:18:12.553274 68 ccl/workloadccl/fixture.go:446  imported 31 GiB in stock table (100000000 rows, 100000000 index entries, took 7m50.056084773s, 68.24 MiB/s)
		  | I200820 09:18:12.634413 1 ccl/workloadccl/fixture.go:325  imported 69 GiB bytes in 9 tables (took 7m50.153513749s, 150.78 MiB/s)
		  | Error: Could not postload: pq: foreign key requires an existing index on columns ("h_c_w_id", "h_c_d_id", "h_c_id")
		  | Error: COMMAND_PROBLEM: exit status 1
		  | (1) COMMAND_PROBLEM
		  | Wraps: (2) Node 1. Command with error:
		  |   | ```
		  |   | ./workload fixtures import tpcc --warehouses=1000 --csv-server='http://localhost:8081'
		  |   | ```
		  | Wraps: (3) exit status 1
		  | Error types: (1) errors.Cmd (2) *hintdetail.withDetail (3) *exec.ExitError
		  |
		  | stdout:
		Wraps: (5) exit status 20
		Error types: (1) *withstack.withStack (2) *safedetails.withSafeDetails (3) *errutil.withMessage (4) *main.withCommandDetails (5) *exec.ExitError

	cluster.go:2597,import.go:47,import.go:58,test_runner.go:754: monitor failure: monitor task failed: t.Fatal() was called
		(1) attached stack trace
		  | main.(*monitor).WaitE
		  | 	/home/agent/work/.go/src/github.com/cockroachdb/cockroach/pkg/cmd/roachtest/cluster.go:2585
		  | main.(*monitor).Wait
		  | 	/home/agent/work/.go/src/github.com/cockroachdb/cockroach/pkg/cmd/roachtest/cluster.go:2593
		  | main.registerImportTPCC.func1
		  | 	/home/agent/work/.go/src/github.com/cockroachdb/cockroach/pkg/cmd/roachtest/import.go:47
		  | main.registerImportTPCC.func2
		  | 	/home/agent/work/.go/src/github.com/cockroachdb/cockroach/pkg/cmd/roachtest/import.go:58
		  | main.(*testRunner).runTest.func2
		  | 	/home/agent/work/.go/src/github.com/cockroachdb/cockroach/pkg/cmd/roachtest/test_runner.go:754
		Wraps: (2) 1 safe detail enclosed
		Wraps: (3) monitor failure
		Wraps: (4) attached stack trace
		  | main.(*monitor).wait.func2
		  | 	/home/agent/work/.go/src/github.com/cockroachdb/cockroach/pkg/cmd/roachtest/cluster.go:2641
		Wraps: (5) 1 safe detail enclosed
		Wraps: (6) monitor task failed
		Wraps: (7) attached stack trace
		  | main.init
		  | 	/home/agent/work/.go/src/github.com/cockroachdb/cockroach/pkg/cmd/roachtest/cluster.go:2555
		  | runtime.doInit
		  | 	/usr/local/go/src/runtime/proc.go:5228
		  | runtime.main
		  | 	/usr/local/go/src/runtime/proc.go:190
		  | runtime.goexit
		  | 	/usr/local/go/src/runtime/asm_amd64.s:1357
		Wraps: (8) 1 safe detail enclosed
		Wraps: (9) t.Fatal() was called
		Error types: (1) *withstack.withStack (2) *safedetails.withSafeDetails (3) *errutil.withMessage (4) *withstack.withStack (5) *safedetails.withSafeDetails (6) *errutil.withMessage (7) *withstack.withStack (8) *safedetails.withSafeDetails (9) *errors.errorString

```

<details><summary>More</summary><p>

Artifacts: [/import/tpcc/warehouses=1000/nodes=32](https://teamcity.cockroachdb.com/viewLog.html?buildId=2200626&tab=artifacts#/import/tpcc/warehouses=1000/nodes=32)
Related:
- #53090 roachtest: import/tpcc/warehouses=1000/nodes=32 failed  [C-test-failure](https://api.github.com/repos/cockroachdb/cockroach/labels/C-test-failure) [O-roachtest](https://api.github.com/repos/cockroachdb/cockroach/labels/O-roachtest) [O-robot](https://api.github.com/repos/cockroachdb/cockroach/labels/O-robot) [branch-provisional_202008191705_v19.2.10](https://api.github.com/repos/cockroachdb/cockroach/labels/branch-provisional_202008191705_v19.2.10) [release-blocker](https://api.github.com/repos/cockroachdb/cockroach/labels/release-blocker)

- #51200 roachtest: import/tpcc/warehouses=1000/nodes=32 failed  [C-test-failure](https://api.github.com/repos/cockroachdb/cockroach/labels/C-test-failure) [O-roachtest](https://api.github.com/repos/cockroachdb/cockroach/labels/O-roachtest) [O-robot](https://api.github.com/repos/cockroachdb/cockroach/labels/O-robot) [branch-provisional_202007081918_v20.2.0-alpha.2](https://api.github.com/repos/cockroachdb/cockroach/labels/branch-provisional_202007081918_v20.2.0-alpha.2) [release-blocker](https://api.github.com/repos/cockroachdb/cockroach/labels/release-blocker)

- #51123 roachtest: import/tpcc/warehouses=1000/nodes=32 failed  [C-test-failure](https://api.github.com/repos/cockroachdb/cockroach/labels/C-test-failure) [O-roachtest](https://api.github.com/repos/cockroachdb/cockroach/labels/O-roachtest) [O-robot](https://api.github.com/repos/cockroachdb/cockroach/labels/O-robot) [branch-provisional_202007071743_v20.2.0-alpha.2](https://api.github.com/repos/cockroachdb/cockroach/labels/branch-provisional_202007071743_v20.2.0-alpha.2) [release-blocker](https://api.github.com/repos/cockroachdb/cockroach/labels/release-blocker)

- #50868 roachtest: import/tpcc/warehouses=1000/nodes=32 failed  [C-test-failure](https://api.github.com/repos/cockroachdb/cockroach/labels/C-test-failure) [O-roachtest](https://api.github.com/repos/cockroachdb/cockroach/labels/O-roachtest) [O-robot](https://api.github.com/repos/cockroachdb/cockroach/labels/O-robot) [branch-master](https://api.github.com/repos/cockroachdb/cockroach/labels/branch-master) [release-blocker](https://api.github.com/repos/cockroachdb/cockroach/labels/release-blocker)

[See this test on roachdash](https://roachdash.crdb.dev/?filter=status%3Aopen+t%3A.%2Aimport%2Ftpcc%2Fwarehouses%3D1000%2Fnodes%3D32.%2A&sort=title&restgroup=false&display=lastcommented+project)
<sub>powered by [pkg/cmd/internal/issues](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)</sub></p></details>

### LINKED ISSUE #53136: roachtest: version/mixed/nodes=3 failed
[(roachtest).version/mixed/nodes=3 failed](https://teamcity.cockroachdb.com/viewLog.html?buildId=2200626&tab=buildLog) on [release-20.1@18c2c6bb8079a123e5fa37d2e99211d6feefb29b](https://github.com/cockroachdb/cockroach/commits/18c2c6bb8079a123e5fa37d2e99211d6feefb29b):

```
		  | main.(*monitor).WaitE
		  | 	/home/agent/work/.go/src/github.com/cockroachdb/cockroach/pkg/cmd/roachtest/cluster.go:2585
		  | main.(*monitor).Wait
		  | 	/home/agent/work/.go/src/github.com/cockroachdb/cockroach/pkg/cmd/roachtest/cluster.go:2593
		  | main.registerVersion.func1
		  | 	/home/agent/work/.go/src/github.com/cockroachdb/cockroach/pkg/cmd/roachtest/version.go:210
		  | main.registerVersion.func2
		  | 	/home/agent/work/.go/src/github.com/cockroachdb/cockroach/pkg/cmd/roachtest/version.go:224
		  | main.(*testRunner).runTest.func2
		  | 	/home/agent/work/.go/src/github.com/cockroachdb/cockroach/pkg/cmd/roachtest/test_runner.go:754
		Wraps: (2) 1 safe detail enclosed
		Wraps: (3) monitor failure
		Wraps: (4) attached stack trace
		  | main.(*monitor).wait.func2
		  | 	/home/agent/work/.go/src/github.com/cockroachdb/cockroach/pkg/cmd/roachtest/cluster.go:2641
		Wraps: (5) 1 safe detail enclosed
		Wraps: (6) monitor task failed
		Wraps: (7) attached stack trace
		  | main.(*cluster).RunE
		  | 	/home/agent/work/.go/src/github.com/cockroachdb/cockroach/pkg/cmd/roachtest/cluster.go:2245
		  | main.registerVersion.func1.1
		  | 	/home/agent/work/.go/src/github.com/cockroachdb/cockroach/pkg/cmd/roachtest/version.go:69
		  | main.(*monitor).Go.func1
		  | 	/home/agent/work/.go/src/github.com/cockroachdb/cockroach/pkg/cmd/roachtest/cluster.go:2575
		  | golang.org/x/sync/errgroup.(*Group).Go.func1
		  | 	/home/agent/work/.go/pkg/mod/golang.org/x/sync@v0.0.0-20190911185100-cd5d95a43a6e/errgroup/errgroup.go:57
		  | runtime.goexit
		  | 	/usr/local/go/src/runtime/asm_amd64.s:1357
		Wraps: (8) 2 safe details enclosed
		Wraps: (9) output in run_063523.667_n4_workload_run_tpcc
		Wraps: (10) /home/agent/work/.go/src/github.com/cockroachdb/cockroach/bin/roachprod run teamcity-2200626-1597904746-11-n4cpu4:4 -- ./workload run tpcc --tolerate-errors --wait=false --drop --init --warehouses=1  --duration=2h0m0s {pgurl:1-3} returned
		  | stderr:
		  | taload.go:140  imported warehouse (0s, 1 rows)
		  | I200820 13:13:06.816588 1 workload/workloadsql/dataload.go:140  imported district (0s, 10 rows)
		  | I200820 13:13:09.235465 1 workload/workloadsql/dataload.go:140  imported customer (2s, 30000 rows)
		  | I200820 13:13:09.734093 1 workload/workloadsql/dataload.go:140  imported history (0s, 30000 rows)
		  | I200820 13:13:10.310859 1 workload/workloadsql/dataload.go:140  imported order (1s, 30000 rows)
		  | I200820 13:13:10.401708 1 workload/workloadsql/dataload.go:140  imported new_order (0s, 9000 rows)
		  | I200820 13:13:11.364152 1 workload/workloadsql/dataload.go:140  imported item (1s, 100000 rows)
		  | I200820 13:13:15.301074 1 workload/workloadsql/dataload.go:140  imported stock (4s, 100000 rows)
		  | I200820 13:13:21.339310 1 workload/workloadsql/dataload.go:140  imported order_line (6s, 300343 rows)
		  | I200820 13:13:24.019356 1 workload/cli/run.go:338  retrying after error during init: Could not postload: pq: foreign key requires an existing index on columns ("h_c_w_id", "h_c_d_id", "h_c_id")
		  |
		  | stdout:
		Wraps: (11) secondary error attachment
		  | signal: killed
		  | (1) signal: killed
		  | Error types: (1) *exec.ExitError
		Wraps: (12) context canceled
		Error types: (1) *withstack.withStack (2) *safedetails.withSafeDetails (3) *errutil.withMessage (4) *withstack.withStack (5) *safedetails.withSafeDetails (6) *errutil.withMessage (7) *withstack.withStack (8) *safedetails.withSafeDetails (9) *errutil.withMessage (10) *main.withCommandDetails (11) *secondary.withSecondaryError (12) *errors.errorString

```

<details><summary>More</summary><p>

Artifacts: [/version/mixed/nodes=3](https://teamcity.cockroachdb.com/viewLog.html?buildId=2200626&tab=artifacts#/version/mixed/nodes=3)
Related:
- #53103 roachtest: version/mixed/nodes=3 failed  [C-test-failure](https://api.github.com/repos/cockroachdb/cockroach/labels/C-test-failure) [O-roachtest](https://api.github.com/repos/cockroachdb/cockroach/labels/O-roachtest) [O-robot](https://api.github.com/repos/cockroachdb/cockroach/labels/O-robot) [branch-provisional_202008191705_v19.2.10](https://api.github.com/repos/cockroachdb/cockroach/labels/branch-provisional_202008191705_v19.2.10) [release-blocker](https://api.github.com/repos/cockroachdb/cockroach/labels/release-blocker)

- #52671 roachtest: version/mixed/nodes=3 failed  [C-test-failure](https://api.github.com/repos/cockroachdb/cockroach/labels/C-test-failure) [O-roachtest](https://api.github.com/repos/cockroachdb/cockroach/labels/O-roachtest) [O-robot](https://api.github.com/repos/cockroachdb/cockroach/labels/O-robot) [branch-master](https://api.github.com/repos/cockroachdb/cockroach/labels/branch-master) [release-blocker](https://api.github.com/repos/cockroachdb/cockroach/labels/release-blocker)

- #51125 roachtest: version/mixed/nodes=3 failed  [C-test-failure](https://api.github.com/repos/cockroachdb/cockroach/labels/C-test-failure) [O-roachtest](https://api.github.com/repos/cockroachdb/cockroach/labels/O-roachtest) [O-robot](https://api.github.com/repos/cockroachdb/cockroach/labels/O-robot) [branch-release-19.1](https://api.github.com/repos/cockroachdb/cockroach/labels/branch-release-19.1) [release-blocker](https://api.github.com/repos/cockroachdb/cockroach/labels/release-blocker)

- #47741 roachtest: version/mixed/nodes=3 failed  [C-test-failure](https://api.github.com/repos/cockroachdb/cockroach/labels/C-test-failure) [O-roachtest](https://api.github.com/repos/cockroachdb/cockroach/labels/O-roachtest) [O-robot](https://api.github.com/repos/cockroachdb/cockroach/labels/O-robot) [branch-release-19.2](https://api.github.com/repos/cockroachdb/cockroach/labels/branch-release-19.2) [release-blocker](https://api.github.com/repos/cockroachdb/cockroach/labels/release-blocker)

[See this test on roachdash](https://roachdash.crdb.dev/?filter=status%3Aopen+t%3A.%2Aversion%2Fmixed%2Fnodes%3D3.%2A&sort=title&restgroup=false&display=lastcommented+project)
<sub>powered by [pkg/cmd/internal/issues](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)</sub></p></details>

### PR DESCRIPTION
**Pull request by rohany**
Fixes #53136.
Fixes #53122.

Updates the TPCC workload to create no longer needed FK indexes based on
a flag, and use that flag when running tpcc on versions below 20.2.

Release note: None

### CODE REVIEW

File: pkg/workload/tpcc/tpcc.go [hunk 1]
```diff
@@ -164,6 +167,7 @@ var tpccMeta = workload.Meta{
 		g.flags.Uint64Var(&g.seed, `seed`, 1, `Random number generator seed`)
 		g.flags.IntVar(&g.warehouses, `warehouses`, 1, `Number of warehouses for loading`)
 		g.flags.BoolVar(&g.fks, `fks`, true, `Add the foreign keys`)
+		g.flags.BoolVar(&g.deprecatedFkIndexes, `deprecated-fk-indexes`, false, `Add deprecated foreign keys`)
```
Comment (irfansharif) [inline pkg/workload/tpcc/tpcc.go:170]: Add "(needed when running against 20.1 clusters)"?

**Review by irfansharif — APPROVED** [review]
LGTM, thanks for the quick fix. Feel free to ignore but if there's an easy way to capture the error you'd get running workload against an older CRDB version without this flag provided, it'd be nice to point to this flag as a possible hint. I know our PMs and SEs use these binaries from time to time.

**Review by nvb — APPROVED** [review]
:lgtm:

> Reviewed 4 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/53367#-:-MFXWbjpDidBYnLxNAuO:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @irfansharif and @rohany)

___
*[pkg/cmd/roachtest/import.go, line 41 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/53367#-MFXWNCdAILScOa0QBat:-MFXWNCdAILScOa0QBau:b-8tg3jo) ([raw file](https://github.com/cockroachdb/cockroach/blob/0c43800cd8549f0bbb8b5dc4a52188d9684ed6fd/pkg/cmd/roachtest/import.go#L41)):*
> ```Go
> 		workloadStr := `./workload fixtures import tpcc --warehouses=%d --csv-server='http://localhost:8081'`
> 		if !t.buildVersion.AtLeast(version.MustParse("v20.2.0")) {
> 			workloadStr += "--deprecated-fk-indexes"
> ```

This needs a space up front, right? 
___
*[pkg/cmd/roachtest/version.go, line 62 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/53367#-MFXWSx26evsDeby6XAc:-MFXWSx26evsDeby6XAd:b-oecj6v) ([raw file](https://github.com/cockroachdb/cockroach/blob/0c43800cd8549f0bbb8b5dc4a52188d9684ed6fd/pkg/cmd/roachtest/version.go#L62)):*
> ```Go
> 		var deprecatedWorkloadsStr string
> 		if !t.buildVersion.AtLeast(version.MustParse("v20.2.0")) {
> 			deprecatedWorkloadsStr += " --deprecated-fk-indexes "
> ```

minor nit: remove the space at the end.
___
*[pkg/workload/tpcc/tpcc.go, line 170 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/53367#-MFXMnbuJYdz58nY-YZi-r1-170:-MFXWYiQ0XVR_JUzcscS:bh2lof1) ([raw file](https://github.com/cockroachdb/cockroach/blob/0c43800cd8549f0bbb8b5dc4a52188d9684ed6fd/pkg/workload/tpcc/tpcc.go#L170)):*
<details><summary><i>Previously, irfansharif (irfan sharif) wrote…</i></summary><blockquote>

Add "(needed when running against 20.1 clusters)"?
</blockquote></details>

"cluster and below"

File: pkg/workload/tpcc/tpcc.go (hunk 1 above)
Comment (rohany) [reply pkg/workload/tpcc/tpcc.go]: Done

**Comment by rohany** [comment]
Good idea, added a catch for the error to include a hint. I had to futz around with some other stuff to get the hint to actually show up, so can you take another look?

> This needs a space up front, right?

Done

> minor nit: remove the space at the end.

done

**Review by irfansharif — APPROVED** [review]

**Comment by rohany** [comment]
tftrs!

bors r+
