### PR TITLE
changefeedccl: deflake TestCoreChangefeedBackfillScanCheckpoint

### LINKED ISSUE #152528: ccl/changefeedccl: TestCoreChangefeedBackfillScanCheckpoint failed
ccl/changefeedccl.TestCoreChangefeedBackfillScanCheckpoint [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Ci_TestsAwsLinuxArm64_UnitTests/20391762?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Ci_TestsAwsLinuxArm64_UnitTests/20391762?buildTab=artifacts#/) on master @ [37243f537529d88f695e409143c4b21539e28d71](https://github.com/cockroachdb/cockroach/commits/37243f537529d88f695e409143c4b21539e28d71):

```
=== RUN   TestCoreChangefeedBackfillScanCheckpoint
    test_log_scope.go:171: test logs captured to: /artifacts/tmp/_tmp/cd414ff17862229220c60c5d6d038c6d/logTestCoreChangefeedBackfillScanCheckpoint2899051899
    test_log_scope.go:82: use -show-logs to present logs inline
    changefeed_test.go:9247: -- test log scope end --
test logs left over in: /artifacts/tmp/_tmp/cd414ff17862229220c60c5d6d038c6d/logTestCoreChangefeedBackfillScanCheckpoint2899051899
--- FAIL: TestCoreChangefeedBackfillScanCheckpoint (16.31s)
=== RUN   TestCoreChangefeedBackfillScanCheckpoint/sinkless
    helpers_test.go:1390: making server as secondary tenant
    helpers_test.go:1469: making sinkless feed factory
    helpers_test.go:1542: pgURL sinkless SinklessFeedUser
    helpers_test.go:1542: pgURL sinkless root
    changefeed_test.go:9235: failed to connect to ``user=SinklessFeedUser database=d``: 127.0.0.1:44087 (127.0.0.1): server error: ERROR: internal error while retrieving user account memberships: operation "get-user-session" timed out after 10.006s (given timeout 10s): internal error while retrieving user account: get auth info error: interrupted during singleflight acquire-lease:33: context deadline exceeded (SQLSTATE 28000)
--- FAIL: TestCoreChangefeedBackfillScanCheckpoint/sinkless (16.28s)
```
<details><summary>Help</summary>
<p>

See also: [How To Investigate a Go Test Failure \(internal\)](https://cockroachlabs.atlassian.net/l/c/HgfXfJgM)
</p>
</details>
/cc @cockroachdb/cdc
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*TestCoreChangefeedBackfillScanCheckpoint.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/bazci/githubpost/issues)

</sub>

Jira issue: CRDB-53901

### PR DESCRIPTION
**Pull request by andyyang890**
This patch updates `TestCoreChangefeedBackfillScanCheckpoint`
to force more frequent frontier persistence instead of span-level
checkpointing since the latter no longer occurs for core changefeeds.
The test has also been hardened to make sure we make some incremental
progress before injecting an error to force a retry.

Fixes #152528

Release note: None

### CODE REVIEW

File: pkg/ccl/changefeedccl/changefeed_test.go [hunk 1]
```diff
@@ -9607,41 +9606,71 @@ func TestCoreChangefeedBackfillScanCheckpoint(t *testing.T) {
...
 		defer closeFeed(t, foo)
 
 		payloads := make([]string, rowCount+1)
 		for i := 0; i < rowCount+1; i++ {
 			payloads[i] = fmt.Sprintf(`foo: [%d]->{"after": {"a": %d}}`, i, i)
 		}
 		assertPayloads(t, foo, payloads)
-		require.GreaterOrEqual(t, errorCount, 1)
+
+		// We want to see that the changefeed restarted at least twice since
```
Comment (rharding6373) [inline pkg/ccl/changefeedccl/changefeed_test.go]: Is it possible for there to only be 1 transient error during the backfill during a successful test? Could this lead to false negative test failures?

**Review by rharding6373 — APPROVED** [review]
LGTM, I have one comment about whether the success criteria is too strict, but otherwise looks good. Nice use of testing knobs. Thanks for the fix!

File: pkg/ccl/changefeedccl/changefeed_test.go (hunk 1 above)
Comment (andyyang890) [reply pkg/ccl/changefeedccl/changefeed_test.go]: It shouldn't be possible given we're having the aggregator checkpoint after each resolved span using `ShouldFlushFrontier`, so we should be seeing at least 10,000(num rows)/25(max batch size)=400 flushes (i.e. >= 4 restarts if we're injecting an error after every 100 batches).

I added some constants and comments to the test to explain that. I also changed it back to every 200 batches so we might only have 2 restarts, but the average number of restarts would still be about 4 given batch size is uniformly distributed in the range [1, 25].

**Review by andyyang890 — COMMENTED** [review]
Thanks for the review!
