### PR TITLE
Fix subquery handling.

### LINKED ISSUE #2402: sql: handle subqueries used in single-value contexts
Currently, `SELECT (SELECT 1) > 0` does not work because we don't consider the context of subqueries. In this example, the subquery is used in a single-value context and thus is required to return only a single row with a single column.

### PR DESCRIPTION
**Pull request by petermattis**
When processing a subquery determine whether it is being used in a single
or multi-value context and how many columns the subquery should contain.

Fixes #2402.

### CODE REVIEW

File: sql/subquery.go [hunk 1]
```diff
@@ -0,0 +1,149 @@
...
+
+package sql
+
+import (
+	"fmt"
+
+	"github.com/cockroachdb/cockroach/sql/parser"
+)
+
+func (p *planner) expandSubqueries(expr parser.Expr) (parser.Expr, error) {
```
Comment (petermattis) [inline sql/subquery.go]: You might want to look at the individual commits which show this code being moved from `select.go` before being enhanced.

File: sql/subquery.go [hunk 2]
```diff
@@ -0,0 +1,149 @@
...
+	v.err = plan.Err()
+	if v.err != nil {
+		return nil, expr
+	}
+	return v, result
+}
+
+// getSubqueryContext returns the number of columns and rows the subquery is
+// allowed to have.
+func (v *subqueryVisitor) getSubqueryContext() (columns int, multipleRows bool) {
```
Comment (tamird) [inline sql/subquery.go]: the named return here is unnecessary.

File: sql/subquery.go [hunk 3]
```diff
@@ -0,0 +1,149 @@
...
+	var plan planNode
+	if plan, v.err = v.makePlan(subquery.Select); v.err != nil {
+		return nil, expr
+	}
+
+	columns, multipleRows := v.getSubqueryContext()
+	if columns != len(plan.Columns()) {
+		switch columns {
+		case 1:
+			v.err = fmt.Errorf("subquery must return only one column")
```
Comment (tamird) [inline sql/subquery.go]: can we make this error message better? spell out the subquery and list how many columns it returns. in cases of `select *` it may be non-obvious.

File: sql/subquery.go (hunk 2 above)
Comment (petermattis) [inline sql/subquery.go]: Yes, but they add a bit of documentation as to what return value is what. Do you really want them removed?

File: sql/subquery.go [hunk 4]
```diff
@@ -0,0 +1,149 @@
...
+			switch len(values) {
+			case 1:
+				result = values[0]
+			default:
+				valuesCopy := make(parser.DTuple, len(values))
+				copy(valuesCopy, values)
+				result = valuesCopy
+			}
+			if plan.Next() {
+				v.err = fmt.Errorf("more than one row returned by a subquery used as an expression")
```
Comment (tamird) [inline sql/subquery.go]: same comment about this error message; can we be more descriptive?

File: sql/subquery.go (hunk 2 above)
Comment (tamird) [inline sql/subquery.go]: i'll leave it up to you. naked return is the real devil, but named returns make me nervous.

File: sql/subquery.go [hunk 5]
```diff
@@ -0,0 +1,149 @@
...
+	if multipleRows {
+		var rows parser.DTuple
+		for plan.Next() {
+			values := plan.Values()
+			switch len(values) {
+			case 1:
+				// This seems hokey, but if we don't do this then the subquery expands to
+				// a tuple of tuples instead of a tuple of values and an expression like
+				// "k IN (SELECT foo FROM bar)" will fail because we're comparing a
+				// single value against a tuple. Perhaps comparison of a single value
```
Comment (tamird) [inline sql/subquery.go]: i think this patterns happens in more places than just here, so it'd be good to extract in the future

File: sql/subquery.go (hunk 3 above)
Comment (petermattis) [inline sql/subquery.go]: These are the exact error messages that postgres gives. I'm not too keen on showing the subquery itself (could be huge) and eventually we'll be able to point to it in error messages as we currently do for parse errors. I will add the number of columns to the message.

**Comment by tamird** [comment]
LGTM

File: sql/subquery.go (hunk 3 above)
Comment (tamird) [inline sql/subquery.go]: actually postgres' error messages are even worse >.>

File: sql/subquery.go (hunk 4 above)
Comment (petermattis) [inline sql/subquery.go]: As above, I'd like all the expression errors to eventually contain a pointer to where in the original expression they occurred. See #2037. Until then, I'm not sure what else to add here. We don't want to actually determine how many rows the subquery returned.

File: sql/subquery.go (hunk 5 above)
Comment (petermattis) [inline sql/subquery.go]: I need to trim this comment. I think this is the only place this occurs, but please correct me if you can find another.

Comment (petermattis) [inline sql/subquery.go]: Well, clearly we're doing this below as well!

Comment (tamird) [inline sql/subquery.go]: ah, this was the place i was thinking of (since it moved in this PR)
