### PR TITLE
sql: exclude implicit partitioning cols from unique violation error

### LINKED ISSUE #59504: opt: hide implicit partitioning columns showing up on UNIQUE index violations
Consider the following:
```
create database if not exists d with primary region "us-west1" regions "us-east1"; use d; set experimental_enable_implicit_column_partitioning = true;
CREATE TABLE public.regional_by_row_table (
  pk INT8 NOT NULL PRIMARY KEY,
  pk2 INT8 NOT NULL,
) LOCALITY REGIONAL BY ROW;


INSERT INTO regional_by_row_table (pk, pk2) VALUES (1, 1);
INSERT INTO regional_by_row_table (pk, pk2) VALUES (2, 1);
ALTER TABLE regional_by_row_table ALTER PRIMARY KEY USING COLUMNS (pk2)
```

the error displays `Key \(crdb_region,pk2\)=\('ap-southeast-2',1\) already exists.`

since crdb_region is implicit, we should hide it's value from appearing

----

simpler case:

```
demo@127.0.0.1:26257/defaultdb> CREATE TABLE t (partition_by INT, v INT);
CREATE TABLE
Time: 3ms total (execution 3ms / network 0ms)
demo@127.0.0.1:26257/defaultdb> INSERT INTO t VALUES (1, 1), (1, 1);
INSERT 2
Time: 3ms total (execution 3ms / network 0ms)
demo@127.0.0.1:26257/defaultdb> CREATE UNIQUE INDEX u ON t(v) PARTITION BY LIST (partition_by) (PARTITION one VALUES IN (1), PARTITION two VALUES IN (2));
ERROR: failed to ingest index entries during backfill: duplicate key value violates unique constraint "u"
SQLSTATE: 23505
DETAIL: Key (partition_by,v)=(1,1) already exists.
CONSTRAINT: u
```

### PR DESCRIPTION
**Pull request by rytaft**
This commit updates the error message produced in case of a unique constraint
violation to exclude the values for implicit partitioning columns and hash sharded
index columns.

Fixes #59504

Release justification: bug fixes and low-risk updates to new functionality.

Release note (sql change): Updated the error message returned in case of
a unique constraint violation to hide the names and values for implicit
partitioning columns and hash sharded index columns.

### CODE REVIEW

File: pkg/sql/row/errors.go [hunk 1]
```diff
@@ -96,12 +96,16 @@ func NewUniquenessConstraintViolationError(
 			"duplicate key value: decoding err=%s", err)
 	}
 
+	// Exclude implicit partitioning columns from the error message.
+	numImplicitCols := index.Partitioning.NumImplicitColumns
```
Comment (otan) [inline pkg/sql/row/errors.go:100]: if we want to exclude hash sharded indexes from displaying as well, we could use `ExplicitColumnStartIdx()`

**Review by otan — APPROVED** [review]

**Review by rytaft — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/61362)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @otan)

___
*[pkg/sql/row/errors.go, line 100 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/61362#-MUocDsNeQfb6z0cuo-_-r1-100:-MUp1tYJBApHDgDXYE1U:br6bb4e) ([raw file](https://github.com/cockroachdb/cockroach/blob/0c57669afc44df30c6564c33adf9f6be365f4714/pkg/sql/row/errors.go#L100)):*
<details><summary><i>Previously, otan (Oliver Tan) wrote…</i></summary><blockquote>

if we want to exclude hash sharded indexes from displaying as well, we could use `ExplicitColumnStartIdx()`
</blockquote></details>

Good idea - done.

**Review by otan — APPROVED** [review]
> Reviewed 1 of 2 files at r1, 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/61362)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @otan)

**Comment by rytaft** [comment]
TFTR!

bors r+
