### PR TITLE
changefeedccl: handle virtual columns

### LINKED ISSUE #73138: Not Null constraint on virtual computed column causes CDC to fail
**Describe the problem**

When adding a computed column that is VIRTUAL and NOT NULL, change feed fails.

**To Reproduce**

Create a table:

```
create table mytable (
	id uuid primary key default gen_random_uuid(),
	v int
);
```

Populate with 10 rows:

```
insert into mytable
(v)
select g from generate_series(1, 10) g;
```

Add a new virtual computed column:

```
ALTER TABLE mytable ADD COLUMN my_computed INT4 NOT NULL AS (v + 1) VIRTUAL;
```

Then I set up a change feed on this table:

```
CREATE CHANGEFEED FOR TABLE defaultdb.mytable;
```

I get this failure:

```
root@:26257/defaultdb> CREATE CHANGEFEED FOR TABLE defaultdb.mytable;
ERROR: internal error: Non-nullable column "mytable:my_computed" with no value! Index scanned was "primary" with the index key columns (id) and the values ('321065f0-d5d1-4777-a278-6ad064698251')
SQLSTATE: XX000
DETAIL: stack trace:
/go/src/github.com/cockroachdb/cockroach/pkg/sql/row/fetcher.go:1580: finalizeRow()
/go/src/github.com/cockroachdb/cockroach/pkg/sql/row/fetcher.go:1304: NextRow()
/go/src/github.com/cockroachdb/cockroach/pkg/ccl/changefeedccl/changefeed_processors.go:725: eventToRow()
/go/src/github.com/cockroachdb/cockroach/pkg/ccl/changefeedccl/changefeed_processors.go:641: ConsumeEvent()
/go/src/github.com/cockroachdb/cockroach/pkg/ccl/changefeedccl/changefeed_processors.go:505: tick()
/go/src/github.com/cockroachdb/cockroach/pkg/ccl/changefeedccl/changefeed_processors.go:457: Next()
/go/src/github.com/cockroachdb/cockroach/pkg/ccl/changefeedccl/changefeed_processors.go:1147: Next()
/go/src/github.com/cockroachdb/cockroach/pkg/sql/execinfra/base.go:171: Run()
/go/src/github.com/cockroachdb/cockroach/pkg/sql/execinfra/processorsbase.go:781: Run()
/go/src/github.com/cockroachdb/cockroach/pkg/sql/flowinfra/flow.go:388: Run()
/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsql_running.go:528: Run()
/go/src/github.com/cockroachdb/cockroach/pkg/ccl/changefeedccl/changefeeddist/distflow.go:134: StartDistChangefeed()
/go/src/github.com/cockroachdb/cockroach/pkg/ccl/changefeedccl/changefeed_dist.go:114: distChangefeedFlow()
/go/src/github.com/cockroachdb/cockroach/pkg/ccl/changefeedccl/changefeed_stmt.go:292: func2()
/go/src/github.com/cockroachdb/cockroach/pkg/sql/planhook.go:145: func1()
/usr/local/go/src/runtime/asm_amd64.s:1374: goexit()

HINT: You have encountered an unexpected error.

Please check the public issue tracker to check whether this problem is
already tracked. If you cannot find it there, please report the error
with details by creating a new issue.

If you would rather not post publicly, please contact us directly
using the support form.

We appreciate your feedback.
```

If I add the computed column and omit the `NOT NULL`, then it works fine.

**Expected behavior**
I expect CDC to function normally and (optionally) emit the computed column.

 - CockroachDB version: 21.2.1

**Additional context**
Change feeds fail.

### PR DESCRIPTION
**Pull request by HonoreDB**
Virtual computed columns aren't populated in kvfeed, so changefeeds
have been quietly populating them with null. We need to maintain this
behavior for now for backwards compatibility and performance, but
this PR tests it and adds a warning when the feed is created.
It also fixes a bug where if a NOT NULL constraint was set on a virtual column,
the changefeed would error out when fetching a row.

Release note (bug fix): Changefeeds will emit null values for virtual computed columns. Previously, they would crash if these were set to NOT NULL.

fixes https://github.com/cockroachdb/cockroach/issues/73138

### CODE REVIEW

File: pkg/ccl/changefeedccl/changefeed_stmt.go [hunk 1]
```diff
@@ -251,6 +251,9 @@ func changefeedPlanHook(
 				if err := changefeedbase.ValidateTable(targets, table); err != nil {
 					return err
 				}
+				for _, warning := range changefeedbase.WarningsForTable(targets, table) {
+					p.BufferClientNotice(ctx, pgnotice.Newf(warning.Error()))
+				}
```
Comment (miretskiy) [inline pkg/ccl/changefeedccl/changefeed_stmt.go:256]: This is probably okay, but I just want to point out that this warning will not be visible to core change feed until change feed terminates

File: pkg/ccl/changefeedccl/rowfetcher_cache.go [hunk 2]
```diff
@@ -173,6 +173,10 @@ func (c *rowFetcherCache) RowFetcherForTableDesc(
 	); err != nil {
 		return nil, err
 	}
+
+	// Necessary because virtual columns are not populated.
+	rf.IgnoreUnexpectedNulls = true
+
```
Comment (miretskiy) [inline pkg/ccl/changefeedccl/rowfetcher_cache.go:179]: Is it possible to do it only if we know that we are hanging virtual non null columns?

**Review by HonoreDB — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/73702)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @gh-casper and @miretskiy)

___
*[pkg/ccl/changefeedccl/changefeed_stmt.go, line 256 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/73702#-MqaWOLDT7yA2IKbR-uE-r1-256:-Mqo9FwC24QuFs8PfkgB:b-dibnm4) ([raw file](https://github.com/cockroachdb/cockroach/blob/a29025bc99c863352eff205d45b90217d84fd8ec/pkg/ccl/changefeedccl/changefeed_stmt.go#L256)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

This is probably okay, but I just want to point out that this warning will not be visible to core change feed until change feed terminates
</blockquote></details>

Yup, we have this limitation with the avro no longer experimental notice too.
___
*[pkg/ccl/changefeedccl/rowfetcher_cache.go, line 179 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/73702#-MqaWOLDT7yA2IKbR-uH-r1-179:-Mqo8YEJ5QHLFx6gsH8w:b-atv4rb) ([raw file](https://github.com/cockroachdb/cockroach/blob/a29025bc99c863352eff205d45b90217d84fd8ec/pkg/ccl/changefeedccl/rowfetcher_cache.go#L179)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

Is it possible to do it only if we know that we are hanging virtual non null columns?
</blockquote></details>

We can do that; it seemed to me like it added more fragility than benefit but I can change it if you'd like. Doesn't feel to me like it's an expectation that changefeeds do integrity checks on stored data.

**Review by miretskiy — APPROVED** [review]

**Comment by HonoreDB** [comment]
bors retry

**Comment by HonoreDB** [comment]
blathers backport 21.2 21.1
