### PR TITLE
backupccl: modify show backup privileges

### LINKED ISSUE #57294: bulkio: allow SHOW BACKUP for non-admin users
It looks like `SHOW BACKUP` requires admin privileges even to show backups executed by a non-admin. See example:

```bash
fabio@:26257/defaultdb> show databases;
  database_name | owner
----------------+--------
  fabio         | fabio


fabio@:26257/defaultdb> backup database fabio TO 's3://fabiog1901qq/fabio?AWS_ACCESS_KEY_ID=xxxyyyzzz&AWS_SECRET_ACCESS_KEY=xxxyyyzzz&AUTH=specified';
        job_id       |  status   | fraction_completed | rows | index_entries | bytes
---------------------+-----------+--------------------+------+---------------+--------
  611984268939100161 | succeeded |                  1 |    2 |             0 |    24


fabio@:26257/defaultdb> show backup 's3://fabio/fabio?AWS_ACCESS_KEY_ID=xxxyyyzzz&AWS_SECRET_ACCESS_KEY=xxxyyyzzz&AUTH=specified';
ERROR: only users with the admin role are allowed to SHOW BACKUP
SQLSTATE: 42501


-- path works with admin
root@:26257/defaultdb> show backup 's3://fabio/fabio?AWS_ACCESS_KEY_ID=xxxyyyzzz&AWS_SECRET_ACCESS_KEY=xxxyyyzzz&AUTH=specified';
  database_name | parent_schema_name | object_name | object_type | start_time |             end_time             | size_bytes | rows | is_full_cluster
----------------+--------------------+-------------+-------------+------------+----------------------------------+------------+------+------------------
  NULL          | NULL               | fabio       | database    | NULL       | 2020-12-01 14:32:56.879062+00:00 |       NULL | NULL |      false
  fabio         | public             | fabio       | table       | NULL       | 2020-12-01 14:32:56.879062+00:00 |         24 |    2 |      false
```

### PR DESCRIPTION
**Pull request by adityamaru**
Previously, show backup was admin only. This change makes it in line
with BACKUP which determines the need for an admin or not based on the
URI and creds.

Fixes: #57294

Release note (sql change): Show backup is no longer admin only. It
depends on the URI construct and the creds specified in the SHOW BACKUP
query.

### CODE REVIEW

**Review by dt — APPROVED** [review]
(reviewing second commit only)

File: pkg/ccl/backupccl/show.go [hunk 1]
```diff
@@ -38,6 +41,28 @@ import (
 	"github.com/cockroachdb/errors"
 )
 
+func checkShowBackupURIPrivileges(ctx context.Context, p sql.PlanHookState, uri string) error {
+	// Check if the user issuing the SHOW BACKUP needs to be of the admin role
+	// depending on the URI destination.
+	hasAdmin, err := p.HasAdminRole(ctx)
```
Comment (dt) [inline pkg/ccl/backupccl/show.go:47]: nit: I'd invert this and only check if isAdmin if we care, i.e. if the URI says we need to.

**Comment by adityamaru** [comment]
TFTR!

bors r=dt

File: pkg/ccl/backupccl/show.go (hunk 1 above)
Comment (adityamaru) [reply pkg/ccl/backupccl/show.go:54]: done.
