### PR TITLE
changefeedccl: fix flaky tests

### LINKED ISSUE #131718: ccl/changefeedccl: TestAlterChangefeedSwitchFamily failed
ccl/changefeedccl.TestAlterChangefeedSwitchFamily [failed](https://mesolite.cluster.engflow.com/invocations/default/cd662f14-548d-412f-9480-077064b9a3d2?testReportRun=1&testReportShard=4&testReportAttempt=1#targets-Ly9wa2cvY2NsL2NoYW5nZWZlZWRjY2w6Y2hhbmdlZmVlZGNjbF90ZXN0) on master @ [ec2573dc6aaeefc226440bb2c5a7c94a63989868](https://github.com/cockroachdb/cockroach/commits/ec2573dc6aaeefc226440bb2c5a7c94a63989868):

```
=== RUN   TestAlterChangefeedSwitchFamily
    test_log_scope.go:170: test logs captured to: outputs.zip/logTestAlterChangefeedSwitchFamily609820803
    test_log_scope.go:81: use -show-logs to present logs inline
    alter_changefeed_test.go:316: -- test log scope end --
test logs left over in: outputs.zip/logTestAlterChangefeedSwitchFamily609820803
--- FAIL: TestAlterChangefeedSwitchFamily (33.70s)
=== RUN   TestAlterChangefeedSwitchFamily/kafka
    helpers_test.go:886: making server as secondary tenant
    helpers_test.go:965: making kafka feed factory
    alter_changefeed_test.go:308: 
        	Error Trace:	github.com/cockroachdb/cockroach/pkg/ccl/changefeedccl/helpers_test.go:201
        	            				github.com/cockroachdb/cockroach/pkg/ccl/changefeedccl/helpers_test.go:276
        	            				github.com/cockroachdb/cockroach/pkg/ccl/changefeedccl/alter_changefeed_test.go:308
        	            				github.com/cockroachdb/cockroach/pkg/ccl/changefeedccl/helpers_test.go:1137
        	            				github.com/cockroachdb/cockroach/pkg/ccl/changefeedccl/helpers_test.go:1172
        	Error:      	Received unexpected error:
        	            	operation "withTimeout-1008518935186341889" timed out after 30s (given timeout 30s): stopping job due to TestFeed timeout
        	            	(1) operation "withTimeout-1008518935186341889" timed out after 30s (given timeout 30s)
        	            	Wraps: (2) attached stack trace
        	            	  -- stack trace:
        	            	  | github.com/cockroachdb/cockroach/pkg/ccl/changefeedccl.stopFeedWhenDone.func3
        	            	  | 	github.com/cockroachdb/cockroach/pkg/ccl/changefeedccl/testfeed_test.go:2954
        	            	  | github.com/cockroachdb/cockroach/pkg/ccl/changefeedccl.stopFeedWhenDone.func1
        	            	  | 	github.com/cockroachdb/cockroach/pkg/ccl/changefeedccl/testfeed_test.go:2943
        	            	  | runtime.goexit
        	            	  | 	src/runtime/asm_amd64.s:1695
        	            	Wraps: (3) stopping job due to TestFeed timeout
        	            	Error types: (1) *timeutil.TimeoutError (2) *withstack.withStack (3) *errutil.leafError
        	Test:       	TestAlterChangefeedSwitchFamily/kafka
    --- FAIL: TestAlterChangefeedSwitchFamily/kafka (33.28s)
```

Parameters:
 - <code>attempt=1</code>
 - <code>run=1</code>
 - <code>shard=4</code>
<details><summary>Help</summary>
<p>

See also: [How To Investigate a Go Test Failure \(internal\)](https://cockroachlabs.atlassian.net/l/c/HgfXfJgM)
</p>
</details>
/cc @cockroachdb/cdc
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*TestAlterChangefeedSwitchFamily.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/bazci/githubpost/issues)
</sub>

Jira issue: CRDB-42657

### LINKED ISSUE #136989: ccl/changefeedccl: TestAlterChangefeedAddTargetFamily failed
ccl/changefeedccl.TestAlterChangefeedAddTargetFamily [failed](https://tanzanite.cluster.engflow.com/invocations/default/40ee6bae-8fa2-49e5-8f89-576e9d363f7e?testReportRun=3&testReportShard=3&testReportAttempt=1#targets-Ly9wa2cvY2NsL2NoYW5nZWZlZWRjY2w6Y2hhbmdlZmVlZGNjbF90ZXN0) on master @ [d7ea85402dc35e36c6cc35520fa91f25fd5c999d](https://github.com/cockroachdb/cockroach/commits/d7ea85402dc35e36c6cc35520fa91f25fd5c999d):

```
=== RUN   TestAlterChangefeedAddTargetFamily
    test_log_scope.go:165: test logs captured to: outputs.zip/logTestAlterChangefeedAddTargetFamily4088767951
    test_log_scope.go:76: use -show-logs to present logs inline
    alter_changefeed_test.go:275: -- test log scope end --
test logs left over in: outputs.zip/logTestAlterChangefeedAddTargetFamily4088767951
--- FAIL: TestAlterChangefeedAddTargetFamily (319.47s)
=== RUN   TestAlterChangefeedAddTargetFamily/kafka
    helpers_test.go:883: making server as secondary tenant
    helpers_test.go:962: making kafka feed factory
    alter_changefeed_test.go:266: 
        	Error Trace:	pkg/ccl/changefeedccl/helpers_test.go:198
        	            				pkg/ccl/changefeedccl/helpers_test.go:273
        	            				pkg/ccl/changefeedccl/alter_changefeed_test.go:266
        	            				pkg/ccl/changefeedccl/helpers_test.go:1134
        	            				pkg/ccl/changefeedccl/helpers_test.go:1169
        	Error:      	Received unexpected error:
        	            	operation "withTimeout-1027569918009311233" timed out after 5m0.005s (given timeout 5m0s): stopping job due to TestFeed timeout
        	            	(1) operation "withTimeout-1027569918009311233" timed out after 5m0.005s (given timeout 5m0s)
        	            	Wraps: (2) attached stack trace
        	            	  -- stack trace:
        	            	  | github.com/cockroachdb/cockroach/pkg/ccl/changefeedccl.stopFeedWhenDone.func3
        	            	  | 	pkg/ccl/changefeedccl/testfeed_test.go:2957
        	            	  | github.com/cockroachdb/cockroach/pkg/ccl/changefeedccl.stopFeedWhenDone.func1
        	            	  | 	pkg/ccl/changefeedccl/testfeed_test.go:2946
        	            	  | runtime.goexit
        	            	  | 	src/runtime/asm_amd64.s:1695
        	            	Wraps: (3) stopping job due to TestFeed timeout
        	            	Error types: (1) *timeutil.TimeoutError (2) *withstack.withStack (3) *errutil.leafError
        	Test:       	TestAlterChangefeedAddTargetFamily/kafka
    --- FAIL: TestAlterChangefeedAddTargetFamily/kafka (319.46s)
```

Parameters:
 - <code>attempt=1</code>
 - <code>race=true</code>
 - <code>run=3</code>
 - <code>shard=3</code>
<details><summary>Help</summary>
<p>

See also: [How To Investigate a Go Test Failure \(internal\)](https://cockroachlabs.atlassian.net/l/c/HgfXfJgM)
</p>
</details>
/cc @cockroachdb/cdc
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*TestAlterChangefeedAddTargetFamily.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/bazci/githubpost/issues)

</sub>

Jira issue: CRDB-45343

### PR DESCRIPTION
**Pull request by asg0451**
Fix flaky tests.

Fixes: #136989
Fixed: #131718

Release note: None

### CODE REVIEW

**Review by rharding6373 — APPROVED** [review]
Drive-by LGTM with minor nits. Nice work finding/fixing this flakiness!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/138780#-:-OGGXsq90VTQTt5dsbtQ:boknchk)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @andyyang890 and @asg0451)

___
*[`pkg/ccl/changefeedccl/alter_changefeed_test.go` line 237 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/138780#-OGGWWbOEx84Zi4-lGWW:-OGGWWbOEx84Zi4-lGWX:bfgdn7m) ([raw file](https://github.com/cockroachdb/cockroach/blob/3f62ed3baad370433f2106c4c2552fc86e60c5ff/pkg/ccl/changefeedccl/alter_changefeed_test.go#L237)):*
> ```Go
> }
> 
> func clusterLogicalTsToHLC(t *testing.T, decimal string) hlc.Timestamp {
> ```

There's a function in ccl/changefeedccl/helpers_test.go that does this that you could reuse instead: `parseTimeToHLC`
___
*[`pkg/ccl/changefeedccl/alter_changefeed_test.go` line 294 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/138780#-OGGXjCh4VYEntuLK0d5:-OGGXjCh4VYEntuLK0d6:by8lt1o) ([raw file](https://github.com/cockroachdb/cockroach/blob/3f62ed3baad370433f2106c4c2552fc86e60c5ff/pkg/ccl/changefeedccl/alter_changefeed_test.go#L294)):*
> ```Go
> 		sqlDB.Exec(t, `INSERT INTO foo VALUES(37, 'goodbye')`)
> 		assertPayloads(t, testFeed, []string{
> 			// Note that we don't see foo.onlyb.[1] here, because we're not
> ```

s/[1]/[42] ?
___
*[`pkg/ccl/changefeedccl/alter_changefeed_test.go` line 296 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/138780#-OGGXkP_2b28hPf1M55S:-OGGXkP_2b28hPf1M55T:b-5sc6rg) ([raw file](https://github.com/cockroachdb/cockroach/blob/3f62ed3baad370433f2106c4c2552fc86e60c5ff/pkg/ccl/changefeedccl/alter_changefeed_test.go#L296)):*
> ```Go
> 			// Note that we don't see foo.onlyb.[1] here, because we're not
> 			// doing a catchup scan and we've already processed that tuple.
> 			// `foo.onlyb: [42]->{"after": {"b": "hello"}}`,
> ```

optional nit: not sure this line adds value to the comment
___
*[`pkg/ccl/changefeedccl/alter_changefeed_test.go` line 331 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/138780#-OGGXLVhCAsmiMmWDfN-:-OGGX4wO2IUvma5Wy_t_:bc3v5q7) ([raw file](https://github.com/cockroachdb/cockroach/blob/3f62ed3baad370433f2106c4c2552fc86e60c5ff/pkg/ccl/changefeedccl/alter_changefeed_test.go#L331)):*
> ```Go
> 		require.True(t, ok)
> 
> 		// Wait for the high water mark to advance past the row we inserted's
> ```

optional nit: s/high water mark/resolved timestamp :-)
___
*[`pkg/ccl/changefeedccl/alter_changefeed_test.go` line 355 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/138780#-OGGXYvpCmDsga5BuZD8:-OGGXYvpCmDsga5BuZD9:by8lt1o) ([raw file](https://github.com/cockroachdb/cockroach/blob/3f62ed3baad370433f2106c4c2552fc86e60c5ff/pkg/ccl/changefeedccl/alter_changefeed_test.go#L355)):*
> ```Go
> 		sqlDB.Exec(t, `INSERT INTO foo VALUES(2, 'goodbye')`)
> 		assertPayloads(t, testFeed, []string{
> 			// Note that we don't see foo.onlyb.[1] here, because we're not
> ```

s/[1]/[42] ?

**Comment by asg0451** [comment]
thx for the review @rharding6373

File: pkg/ccl/changefeedccl/alter_changefeed_test.go [hunk 1]
```diff
@@ -246,13 +246,30 @@ func TestAlterChangefeedAddTargetFamily(t *testing.T) {
...
+		insertTs := parseTimeToHLC(t, insertTsDecStr)
 		assertPayloads(t, testFeed, []string{
-			`foo.onlya: [1]->{"after": {"a": 1}}`,
+			`foo.onlya: [42]->{"after": {"a": 42}}`,
 		})
 
-		feed, ok := testFeed.(cdctest.EnterpriseTestFeed)
-		require.True(t, ok)
+		// Wait for the high water mark (aka resolved ts) to advance past the row we inserted's
+		// mvcc ts. Otherwise, we'd see [1] again due to a catch up scan, and it
```
Comment (andyyang890) [inline pkg/ccl/changefeedccl/alter_changefeed_test.go:261]: nit: s/1/42/

**Review by andyyang890 — APPROVED** [review]
Nice find!

**Comment by asg0451** [comment]
bors r=andyyang890,rharding6373
