### PR TITLE
metric: use cumulative count instead of windowed count in tsdb

### LINKED ISSUE #98745: metrics: -count metrics in internal tsdb are broken/not useful
Look at these:

image

The average and count are taken from the windowed histogram. This is fine for the average, though it's not clear how there would be a zero average ever - we heartbeat every <5s so there should be a nonzero average at all times (we collect at 10s interval and rotate at an even slower interval). The count just doesn't help anyone - it's the windowed count (and you can see it drop to zero periodically, which explains the zero average and this is unexpected too).

In the internal tsdb, we only export a number of quantiles and these "windowed" avg/counts, so we don't have an ability to plot a rate of events affecting a histogram. This has been annoying in a few escalations over the years.

We should export the cumulative count instead of the windowed count. The windowed count is so useless that I doubt that anyone relies on it and we could just change the semantics (this doesn't affect prometheus endpoint).

The windowed average seems to be at least somewhat weird. When I plot -avg for a metric that should see "more regular" data recorded to it the jitter goes away some, but it's still noticeable:

image

so there's probably a data quality issue here. I suspect whatever @aadityasondhi will end up doing for https://github.com/cockroachdb/cockroach/issues/98266 will fix this problem here too.

Jira issue: CRDB-25494

### PR DESCRIPTION
**Pull request by aadityasondhi**
Previously, we were writing the windowed count of a histogram into tsdb.
This meant that on each tick, the count reset. This is useful for
calculating averages and quantiles using windowed histograms, but makes
little sense to record for `count`.

This patch now uses the cumulative count in tsdb.

This patch also adds a `-sum` field to maintain a record of the
cumulative sum along with the cumulative counts.

Fixes https://github.com/cockroachdb/cockroach/issues/98745

Release note (bug fix): Timeseries metric counts will now show
cumulative counts for a histogram rather than the windowed count. A
`-sum` timeseries is also exported to keep track of the cumulative sum
of all samples in the histogram.

### CODE REVIEW

File: pkg/server/status/recorder.go [hunk 1]
```diff
@@ -625,8 +625,9 @@ type registryRecorder struct {
 func extractValue(name string, mtr interface{}, fn func(string, float64)) error {
 	switch mtr := mtr.(type) {
 	case metric.WindowedHistogram:
+		// Use cumulative count here
+		fn(name+"-count", float64(mtr.(*metric.Histogram).TotalCount()))
```
Comment (tbg) [inline pkg/server/status/recorder.go:629]: Is this type assertion always possible? After all, this interface is implemented in a few places:

Comment (aadityasondhi) [reply pkg/server/status/recorder.go:629]: Apparently not, thanks for pointing it out. Will think harder about this! I was hoping to get this one fixed before pushing out the bigger refactor in https://github.com/cockroachdb/cockroach/issues/98621.

**Comment by aadityasondhi** [comment]
Took another stab. PTAL. I want to backport this fix so I am trying to keep it low in code compared to the larger refactor I am working on in https://github.com/cockroachdb/cockroach/issues/98621. Based on the number of touchpoints in the code, I will not be backporting that.

File: pkg/server/status/recorder.go [hunk 2]
```diff
@@ -609,8 +609,9 @@ type registryRecorder struct {
 func extractValue(name string, mtr interface{}, fn func(string, float64)) error {
 	switch mtr := mtr.(type) {
 	case metric.WindowedHistogram:
+		// Use cumulative count here
+		fn(name+"-count", float64(mtr.TotalCount()))
 		n := float64(mtr.TotalCountWindowed())
-		fn(name+"-count", n)
 		avg := mtr.TotalSumWindowed() / n
```
Comment (tbg) [inline pkg/server/status/recorder.go:615]: Sorry for not pointing this out earlier, but we have a similar but more convoluted problem with `TotalSumWindowed`. Normally histograms export total sum and total count, so that you can take rates and compute local averages. Here we can't do that because while we now have a total count, we don't have a total sum but just a "current average". Could we also export `-sum` which has the `TotalSum()`? At that point it would be nice to not write the prometheus histogram again, so perhaps instead of `TotalCount()` we'd have `.Total() (count uint64, sum float64)`.

**Review by tbg — APPROVED** [review]
LGTM, there's a very similar problem that if you knocked it out in this PR would save us the next similar headache.

**Comment by aadityasondhi** [comment]
Note: most of the changes here (outside of the metric package) are in test files.

**Review by abarganier — APPROVED** [review]
:lgtm: - apologies for the review delay. Thanks for all your valuable work on these histogram libraries :pray: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/101909#-:-NVVqJ97BiImnIJOAHLS:bh2zja0)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @aadityasondhi and @tbg)
