### PR TITLE
backupccl: test ignore ProtectionPolicy for exclude_data_from_backup

### LINKED ISSUE #73536: sql,protectedts: mark tables as ephemeral to exclude them from backups
This is a tracking issue that captures an idea proposed by @dt.

Some users have encountered challenges with tables that contain high-churn, ephemeral data, where they want to GC history in that table quickly, but cannot simply configure it to do so because it is contained within a database, tenant or cluster that is backed up incrementally, which requires that history be preserved until that backup can back it up. 

In many such cases, the user does not actually explicitly desire data in these tables to be backed up at all, and are only doing so because it is part of the larger database, tenant or cluster being backed up. Thus one possible solution would be to provide a mechanism for a table like this to _opt out_ of inclusion in backups, freeing it to configure more aggressive GC without affecting the ability of its containing database to backup. Simply excluding the table entirely could be challenging -- it may still be referenced in jobs, logs, views, etc. However excluding its row data would allow the backup to succeed even if its that table's span has been GCed, and would result in it just being empty when restored.

Approach:

One proposed approach would be to mark a table as `ephemeral`. The simplest solution would be to store this information on the `TableDescriptor` but this does not work because of the way tenants are backed up. A `BACKUP TENANT` from the system tenant simply backs up a single-tenant span, and does not look inside the tenant to be able to exclude certain tables. Thus, this information needs to be written to the ZoneConfig, and will subsequently rely on the transport infrastructure that was introduced to support zcfgs in a multi-tenant environment.

The tasks can then largely be broken up into:

- [ ] Add `epehemeral` bit to ZoneConfig for a table, and the corresponding SpanConfig created as a result of reconciliation.

- [ ] Teach `ExportRequest` to return an empty `ExportResponse` when attempting to export a replica that has an assocaited `SpanConfig` marked as `ephemeral`.

- [ ] Teach GC to ignore any protected timestamp records that might be written to a replica that is marked as ephemeral. This way, even if a backup were to protect a set of schema objects that included the ephemeral table, it would allow the low GC TTL to continue garbage collecting the data.

- [ ] Add a migration to mark system tables that opt-out from a cluster backup as `ephemeral` so that they are never backed up or protected.

- [ ] Add SQL to set/unset a table as ephemeral. This might work out of the box with `ALTER ZONE CONFIGURATION`.

- [ ] Think about how to make the fact that a table is `ephemeral` observable to the user during a backup. To avoid surprises where they expect a table to be a part of the backup, but it is silently ignored. This might be solved via documentation, but it is worth calling out explicitly.

Epic: CRDB-10306

Jira issue: CRDB-11627

### PR DESCRIPTION
**Pull request by adityamaru**
This change adds an end to end test to ensure that a table excluded
from backup will not holdup GC on its replica even in the presence
of a protected timestamp record covering the replica

From a users point of view, this allows them to mark a table whose
row data will be excluded from backup, and to set that tables gc.ttl
to a very low value. Backups that write PTS records will no longer
holdup GC on such low GC TTL tables.

Fixes: https://github.com/cockroachdb/cockroach/issues/73536

Release note: None

Release justification: low risk update to new functionality

### CODE REVIEW

File: pkg/ccl/backupccl/backup_test.go [hunk 1]
```diff
@@ -9726,6 +9720,116 @@ func TestExportRequestBelowGCThresholdOnDataExcludedFromBackup(t *testing.T) {
 	require.NoError(t, err)
 }
 
+// TestExcludeDataFromBackupDoesNotHoldupGC tests that a table marked as
+// `exclude_data_from_backup` and with a protected timestamp record covering it
+// does not holdup GC, since its data is not going to be backed up.
+func TestExcludeDataFromBackupDoesNotHoldupGC(t *testing.T) {
```
Comment (adityamaru) [inline pkg/ccl/backupccl/backup_test.go:9726]: I solemnly swear to datadriven-ify these tests as part of https://github.com/cockroachdb/cockroach/issues/77129, but to derisk this change I wanted to postpone building out our backup datadriven framework. I have ideas on how to wrap all these GC/SpanConfig operations that I'll work on as part of our test revamp.

**Comment by adityamaru** [comment]
@irfansharif removing this from your review queue since this has become a test only change after https://github.com/cockroachdb/cockroach/pull/77392. This is RFAL now that that has merged!

**Comment by adityamaru** [comment]
@irfansharif removing this from your review queue since this has become a test only change after https://github.com/cockroachdb/cockroach/pull/77392. This is RFAL now that that has merged!

**Comment by adityamaru** [comment]
friendly ping @dt

**Review by dt — APPROVED** [review]

**Comment by adityamaru** [comment]
CI failure is TestDockerCLI

TFTR!
bors r=dt
