### PR TITLE
Always reply to heartbeats, whether we know of groups in common or not.

### LINKED ISSUE #1980: TestRaftAfterRemoveRange fails with CPUS=4
Discovered in #1839.

https://circleci.com/gh/cockroachdb/cockroach/5526
https://circle-artifacts.com/gh/cockroachdb/cockroach/5526/artifacts/0/tmp/circle-artifacts.F4In60q/testrace.log

Note that this is a different failure from #1911.

### PR DESCRIPTION
**Pull request by bdarnell**
A follower may not have accurate information, and the leader needs a
heartbeat response to trigger retries.

With this change, leadership doesn't matter so
TestHeartbeatMultipleGroupsJointLeader isn't really testing anything
useful (and is fiddly to update), so I've removed it.

Closes #1980.

### CODE REVIEW

File: multiraft/heartbeat_test.go [hunk 1]
```diff
@@ -164,14 +164,14 @@ func validateHeartbeatSingleGroup(nodeCount, tickCount int, t *testing.T) {
...
 
 	expCnt := heartbeatCountMap{
-		// The leader is the only node that receives responses.
-		uint64(leaderIndex + 1): {reqOut: (ltc) * (nc - 1), reqIn: ftc, respOut: 0, respIn: ltc * (nc - 1)},
+		// The leader ticks `ltc` times and gets responses.
+		uint64(leaderIndex + 1): {reqOut: (ltc) * (nc - 1), reqIn: ftc, respOut: ftc, respIn: ltc * (nc - 1)},
 	}
-	// The first follower ticks `ftc` times, but nobody responds.
-	expCnt[2] = heartbeatCount{reqOut: (nc - 1) * ftc, reqIn: ltc, respOut: ltc, respIn: 0}
+	// The first follower ticks `ftc` times, and gets responses
```
Comment (tschottdorf) [inline multiraft/heartbeat_test.go]: nit: s/$/./

**Comment by tschottdorf** [comment]
LGTM

**Comment by tamird** [comment]
LGTM
